### ISSUE TITLE
Report issue not working coretly from VSC

### ISSUE THREAD

**Issue by ManPython** [microsoft/vscode#100074]
VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 6.1.7601
Steps to repair:

1. Exclude extensions or sugest to turn off - someone can not guess that problem is related with hudge list of extensions

Does this issue occur when all extensions are disabled?: Yes

![VSC_report issue](https://user-images.githubusercontent.com/25403861/84566498-f154d600-ad71-11ea-9f72-dd71ee9c8fcc.png)

**Comment by IllusionMH** [comment]
Not sure what you count as a problem. GitHub has limit on content that can be prefilled without user action and therefore this message provides info how to perform next steps - paste info into GitHub page.

What action items you expect here?

I wouldn't recommend to disable extension list because it's first thing that will be asked if there are doubts that this is editor issue and I had cases where this limit can be achieved with all extensions disabled.

**Comment by ManPython** [comment]
>What action items you expect here?
Turn off the checkbox as default for system and extensions. Users have often more than 5.

**Comment by IllusionMH** [comment]
Now it's more clear.
System - looks like good candidate for off by default.
Extensions list - often may be first question asked, so doesn't look good to remove by default.

Anyway someone from team would weight it on this.

**Comment by RMacfarlane** [comment]
Yeah, the extensions list is very useful, this is data we definitely want to have by default.

The system information is less often used, true, but sending it at the beginning can help speed up some issues instead of having to do a back and forth to get this information.

I would prefer to keep both as checked by default, so will close this. There is another issue to leverage GitHub login information and directly create the issue instead of previewing it: https://github.com/microsoft/vscode/issues/95165 Once we move to that, we can avoid showing this clipboard dialog.

**Comment by ManPython** [comment]
Maybe some listing extensions as chexboxlist as important for some case can be more helply?
Most often I not providing info aobut ext due to long list and the main ext realted wuth some problems/issues to be more user friendly in github searching version to provide manualy in this long list. In some way of selecting by checkobx as deafult to add as log list can be more usable, but problem in case of updating. 
I think that easy aceess to extension list can be usefull to faster provide version, etc. info.
By this I observing that many extensions have some debug function with option to turn on/off. This should be solved around this and can help to solve problems - the list with checkbox for debug or other additional functions. Then developers can prepare functions that exist without searching in the source code some options. Again.. then this settings can be as some structure to provide to analyse with logs.
