### ISSUE TITLE
No feedback when choosing "Check for Updates..."

### ISSUE THREAD

**Issue by akbyrd** [microsoft/vscode#100016]
When choosing `Help > Check for Updates...` there is no feedback from the application in some cases. When there are no updates available, a dialog appears. 
![image](https://user-images.githubusercontent.com/484784/84524690-394efc80-ac8f-11ea-8561-2b7eca293f11.png)
When the _are_ updates...nothing happens. You have to open the Help menu again and notice that the text for `Check for Updates...` has changed to `Downloading Update...`.

I think there are two solid improvements to be made here:
1. When an update is available show a notification that says an update is downloading after clicking `Check for Updates...`.
2. When an update is not available show a notification that says no updates are available, instead of an OS dialog.

**Comment by tabaddor** [comment]
I can take a look at this issue. 

Not incredibly familiar with the codebase, but where should I be looking?

**Comment by joaomoreno** [comment]
@tabaddor I suggest you go here first: https://github.com/microsoft/vscode/wiki/How-to-Contribute#contributing-to-visual-studio-code and start with `good first issue` labeled issues.

**Comment by joaomoreno** [comment]
I've decided to switch from modal to normal notification. I'm not sure a notification for the success case is really necessary.

**Comment by akbyrd** [comment]
> I'm not sure a notification for the success case is really necessary.

I'm assuming the success case is "there was an update available and it's downloading". When I click update how do I know something is actually happening? Is it checking? Is it downloading? Is it ready to install? Did vscode register my action at all? Right now I can't tell.

If there's no notification when checking or downloading, which could take arbitrarily long, it is indistinguishable from vscode ignoring my input.

**Comment by joaomoreno** [comment]
> I'm assuming the success case is "there was an update available and it's downloading". When I click update how do I know something is actually happening? Is it checking? Is it downloading? Is it ready to install? Did vscode register my action at all? Right now I can't tell.

Well, there's a badge coming up in the gear icon, don't you see it?

**Comment by akbyrd** [comment]
In the activity bar? Honestly, I forgot that existed.

`"workbench.activityBar.visible": false`

Now I'm a little torn. I can understand "well you've hidden part of the UI...". On the other hand, it's weird that checking for updates depends on a separate piece of UI being available that it can't show as necessary. It feels a bit like hide-and-seek to know where the result of check for updates is going to be shown.

Notifications feel like the 'right' answer for displaying update state/progress. It doesn't require a permanently visible piece of UI to function. It's noticeable and more intuitive than an icon badge. It's not really subject to users hiding UI pieces (aside from zen mode). There's precedent: the C++ extension uses a notification when downloading additional binaries. And notifications are already used for 2 other parts of the update process ('no updates', 'need to restart', and maybe 'failed'?).

**Comment by joaomoreno** [comment]
OK, sure! Wanna submit a PR?

**Comment by akbyrd** [comment]
I do not.

**Comment by dfireBird** [comment]
Hey! I would like to work on this issue, if it's possible. 

Also a question: Since in dev and oss version I can't check for updates how can I debug which function invoke that `Check for updates` in invoked.

**Comment by andrew-maust** [comment]
hi @joaomoreno is this available to work on?

**Comment by andrew-maust** [comment]
actually this issue appears to be fixed atleast on macos.

**Comment by hp77-creator** [comment]
Hey @joaomoreno, Is this issue still open?

**Comment by plainerman** [comment]
Hey @joaomoreno, 

If I read the current version of [update.ts](https://github.com/microsoft/vscode/blob/master/src/vs/workbench/contrib/update/browser/update.ts#L344) correctly, the `NotificationService` is already in use and informs the user.

Further, it seems to me that you have already implemented a notification instead of a popup (if there are no updates available) but [decided to revert it](https://github.com/microsoft/vscode/commit/1069791db98b778fccb7de8b1b966ec27fbd689b).

Does this mean, that the issue can be closed, or is there still some implementation / discussion required? If so, could you elaborate on the current status and state whether this issue is still up for grabs?

Thank you very much.

**Comment by joaomoreno** [comment]
Yeah will close this as won't fix. Thanks for the ping.

**Comment by HenrikHolmIT** [comment]
I've turned off automatic update because sometimes new updates break things. I'd like to choose when my VSCode updates and I agree that the current solution is all but userfriendly.

I'd propose that if there is an update that a changelog page with the changes included is shown to the user. The user can then better see what is updated before they apply the patch. Not showing anything except starting a background download and showing a badge on a gear icon that some users might have hidden away is not the right thing to do.
