### ISSUE TITLE
Panel header usability improvement 

### ISSUE THREAD

**Issue by inwardmovement** [microsoft/vscode#100077]
I suggest to remove the collapsible behavior (or add an option to disable it) in the panel header so that we have the same usability (views not hidden and switch to them in one click) whether the panel is narrow (typically when the panel is sticked to a side) or wide (when it is sticked to bottom).

Wide:
![image](https://user-images.githubusercontent.com/9438102/84568178-f3bd2d00-ad7d-11ea-829f-0b734b555aeb.png)

Narrow:
![image](https://user-images.githubusercontent.com/9438102/84568147-bd7fad80-ad7d-11ea-95d5-4ea99a71480d.png)

Narrow improved:
![Window_000265](https://user-images.githubusercontent.com/9438102/84589422-ac42a980-ae2e-11ea-9059-36bac3a2bcdf.png)

Narrow improved alternative:
![image](https://user-images.githubusercontent.com/9438102/84568149-c2dcf800-ad7d-11ea-84c0-b00cfea04bd9.png)

**Comment by misolori** [comment]
Thanks for the suggestion, unfortunately this wouldn't work since we have flexible layouts where views can be moved into the panel like:

![image](https://user-images.githubusercontent.com/35271042/84709671-73323400-af17-11ea-9ca4-28288d18885e.png)

So moving the panel titles or actions underneath breaks up the visual hierarchy and consistency (actions are always on the right). Please upvote #87347 as that is trying to solve the issue of fitting everything in small widths.
