### ISSUE TITLE
Highlinting .jsx

### ISSUE THREAD

**Issue by maxval94** [Microsoft/vscode#10009]
- VSCode Version: 1.3.1
- OS Version: Ubuntu 14.04
- Theme: Dark+ theme.

The current highlinting makes no difference between a variable, property or method usage. Everything is just white.
http://static.md/5e86605f2c3838d8cc2e7bda5e20ed77.png

**Comment by aeschli** [comment]
The underlying issue is https://github.com/Microsoft/TypeScript-TmLanguage/issues/149.
As an alternative to the built-in grammar you can install the Atom grammar that offers that feature (in combination with a theme that colorises such references, e.g. Monokai):
https://marketplace.visualstudio.com/items?itemName=ms-vscode.js-atom-grammar
