### ISSUE TITLE
I can't able to install any extensions

### ISSUE THREAD

**Issue by JigneshPatel23** [microsoft/vscode#100078]
Issue Type: <b>Bug</b>

I can't able to install any extensions even after removing and reinstalling latest VSCode

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T08:59:06.977Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 5|
|Memory (System)|8.00GB (0.08GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by gjsjohnmurray** [comment]
I suggest you follow the steps listed at https://github.com/microsoft/vscode/issues/99668#issuecomment-641807657

**Comment by sandy081** [comment]
Please follow these steps

- Help -> Toggle Developer Tools -> Network
- Then check for any network failed requests while browsing and installing the extensions if found all requests fails then its probably a proxy or DNS issue at your end.
- To confirm its a DNS issue check if you can access this page https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default, if you cannot please try configuring your DNS like pointing to 1.1.1.1 as suggested here? https://1.1.1.1/dns/. Otherwise please contact your network administrator.
- If it is not a network issue, please share the logs from the following locations
    - Help -> Toggle Developer Tools -> Console
    - View -> Command Pallette... -> Toggle Shared Process -> Console
    - View -> Open View… -> Log (Shared)
    - View -> Open View… -> Log (Window)

**Comment by JigneshPatel23** [comment]
I think the problem seems like something about the permissions but I have tried many things found on other issue or StackOverflow but can't get the working.

I can install extensions only when I start VSCode with sudo and which is not recommended and not a good way.

Attaching a few screenshots which might help me to get exact help from your side. 

<img width="1073" alt="Screen Shot 2020-06-22 at 12 38 53 PM" src="https://user-images.githubusercontent.com/7347854/85258811-b21b3900-b485-11ea-98ed-59bc51564059.png">
<img width="801" alt="Screen Shot 2020-06-22 at 12 38 12 PM" src="https://user-images.githubusercontent.com/7347854/85258821-b5162980-b485-11ea-985f-6f71ad6856e9.png">

**Comment by sandy081** [comment]
It seems you installed VS Code in the beginning with sudo and now as an user you do not have permissions to the folder that sudo (root) created. Recommended is to install VS Code as an user.
