### ISSUE TITLE
HTML data-* Attribute Snippet

### ISSUE THREAD

**Issue by musayazlik** [microsoft/vscode#100069]
Issue Type: <b>Feature Request</b>

I want it to show data- * snippets as a preview when writing html tags. Just as it shows when adding a css class. I would appreciate if you add such a feature.

![Html data Attribute Snippet](https://user-images.githubusercontent.com/33998073/84565256-98387280-ad70-11ea-9ffc-b78b1bcc65a5.png)

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T09:03:20.462Z)
OS version: Windows_NT x64 10.0.19645

**Comment by ArturoDent** [comment]
By way of clarification, do you want completion for `data-` attributes like there is completion for class names in html when you type `class=""`?  And you get all the classes used in linked `css/scsss` files.

If so, I believe that that class completion is provided by an extension:

https://marketplace.visualstudio.com/items?itemName=ecmel.vscode-html-css (and maybe others)

and not natively by vscode.  That particular extension does not support `data-` attributes, perhaps another does.   But it seems unlikely that vscode would add native support for `data-` attributes at this point (since class completion is provided by an extension unless I am mistaken) - it is a good candidate for an extension though.

**Comment by aeschli** [comment]
What currently happens is that HTML suggests `data-xyz` if `data-xyz` is used somewhere wlese in the document:
![image](https://user-images.githubusercontent.com/6461412/84748525-0cfded80-afb9-11ea-9773-162f079ac06b.png)

It's possible to team HTML new attribute using the custom data feature:
See https://code.visualstudio.com/blogs/2020/02/24/custom-data-format for more information.

Is that good useful for you?

**Comment by musayazlik** [comment]
> What currently happens is that HTML suggests `data-xyz` if `data-xyz` is used somewhere wlese in the document:
> ![image](https://user-images.githubusercontent.com/6461412/84748525-0cfded80-afb9-11ea-9773-162f079ac06b.png)
> 
> It's possible to team HTML new attribute using the custom data feature:
> See https://code.visualstudio.com/blogs/2020/02/24/custom-data-format for more information.
> 
> Is that good useful for you?

**Comment by musayazlik** [comment]
@aeschli  Yes, that's exactly what I was looking for. Thank you so much.
