### ISSUE TITLE
Vscode occupies ASAR file

### ISSUE THREAD

**Issue by mapleby** [microsoft/vscode#100163]
- VSCode Version: 1.46.0
- OS Version:windows10 1909

Steps to Reproduce:
Vscode sometimes takes up ASAR's files, causing exceptions in running projects.
1.
2.

Does this issue occur when all extensions are disabled?: Yes/No 
Yes

**Comment by alexdima** [comment]
@mapleby I'm not sure I understand, what do you mean exactly? What steps do you do?

**Comment by mapleby** [comment]
> @mapleby我不确定我是否理解，您到底是什么意思？你要做什么？

![image](https://user-images.githubusercontent.com/45815225/85487017-54f6c300-b5fe-11ea-9d50-e12ced83d870.png)

I'm writing the project of electron, but vscode sometimes takes up these files, which causes the project to run abnormally.

**Comment by mapleby** [comment]
> @mapleby我不确定我是否理解，您到底是什么意思？你要做什么？

![image](https://user-images.githubusercontent.com/45815225/85487309-e9f9bc00-b5fe-11ea-95e3-dd7204eff1a2.png)
I currently use ASAR files for packaging, which is convenient for update and management. However, every time you run it for a while, vscode will occupy the file.

**Comment by mapleby** [comment]
> @mapleby我不确定我是否理解，您到底是什么意思？你要做什么？

I haven't encountered this problem in the previous version

**Comment by alexdima** [comment]
@bpasero This looks like we end up reading from the `.asar` files in the user workspace. From what I can come up with, we use the `FileSystemService` on the renderer process to read from the user workspace and the file watcher is in charge or watching that folder, but since that is written in C# it should not end up opening the `.asar` files, so this brings me back to the `FileSystemService`. AFAIK the extension host process does not do `fs` directly on user workspace files.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/
