### ISSUE TITLE
Extensions don't load 

### ISSUE THREAD

**Issue by EngyScott** [microsoft/vscode#100270]
- VSCode Version: 1.46.0 (user setup)
- OS Version:  windows 7 professional 

Steps to Reproduce:

1.trying to download extensions from extensions icon on the application, gives unknown error
2.trying to download extensions manually at the market place, still giving me the same unknown error

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
Likely a DNS or proxy issue. Please search issues here using those terms.

**Comment by sandy081** [comment]
So you mean to say you cannot access extensions from Marketplace web site too?

Please follow these steps

- Help -> Toggle Developer Tools -> Network
- Then check for any network failed requests while browsing and installing the extensions if found all requests fails then its probably a proxy or DNS issue at your end.
- To confirm its a DNS issue check if you can access this page https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default, if you cannot please try configuring your DNS like pointing to 1.1.1.1 as suggested here? https://1.1.1.1/dns/. Otherwise please contact your network administrator.
- If it is not a network issue, please share the logs from the following locations
    - Help -> Toggle Developer Tools -> Console
    - View -> Command Pallette... -> Toggle Shared Process -> Console
    - View -> Open View… -> Log (Shared)
    - View -> Open View… -> Log (Window)

**Comment by EngyScott** [comment]
Thank you @sandy081 your reply is really helpful.
I followed the steps you mentioned and my software engineer found that most of Microsoft proxy is blocked in Egypt.
I hope you can find a solution for that soon.
anyway the problem solved, thank you again
