### ISSUE TITLE
Why Extensions  wont download or even show details 

### ISSUE THREAD

**Issue by Mina-Mishail** [microsoft/vscode#100245]
Extensions wont download or even show details while using local network but work properly while using mobile hot-spot WiFi ! ?

**Comment by gjsjohnmurray** [comment]
Sounds like DNS and/or proxy settings enforced on your local network are preventing connections to Marketplace. Search here for 'DNS' or 'proxy' to find similar issues.

**Comment by Mina-Mishail** [comment]
> 
> 
> Thanks for creating this issue! We figured it's missing some basic information or in some other way doesn't follow our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines. Please take the time to review these and update the issue.
> 
> Happy Coding!

I can't open VS-code plugins/extensions detail page or even install them on my computer through home/work WiFi , the only way is to connect using my mobile WiFi to do all of that.

Attached print screen shows what happens.

![VS code Error](https://user-images.githubusercontent.com/57733511/84764090-db474f80-afd5-11ea-8efe-766edff8ce3e.png)

**Comment by gjsjohnmurray** [comment]
Did you search for similar issues?

For example, the advice at https://github.com/microsoft/vscode/issues/99649#issuecomment-641089128 from @sandy081 might help you.

**Comment by sandy081** [comment]
Please follow these steps

- Help -> Toggle Developer Tools -> Network
- Then check for any network failed requests while browsing and installing the extensions if found all requests fails then its probably a proxy or DNS issue at your end.
- To confirm its a DNS issue check if you can access this page https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default, if you cannot please try configuring your DNS like pointing to 1.1.1.1 as suggested here? https://1.1.1.1/dns/. Otherwise please contact your network administrator.
- If it is not a network issue, please share the logs from the following locations
    - Help -> Toggle Developer Tools -> Console
    - View -> Command Pallette... -> Toggle Shared Process -> Console
    - View -> Open View… -> Log (Shared)
    - View -> Open View… -> Log (Window)
