### ISSUE TITLE
CPU Spike for golang repositories

### ISSUE THREAD

**Issue by KirilNN** [microsoft/vscode#100369]
- VSCode Version: 1.47.0-insider
- OS Version: macOS Catalina

Steps to Reproduce:

1. Open a golang project and edit some files
2. You will see that a new perl process from watchman is spun off which will cause 100% CPU Usage 

Does this issue occur when all extensions are disabled?: Yes

This issue can be reproduced both with standard/insider versions of VS Code, and with all the disabled extensions.  The settings.json file contains just 3 entries:

```
{
    "go.formatTool": "goimports",
    "go.useLanguageServer": false,
    "go.gopath": ""
}
```

<img width="663" alt="Screenshot 2020-06-17 at 12 19 36" src="https://user-images.githubusercontent.com/4188451/84883056-c67fc000-b098-11ea-8c03-76ad7b2ca272.png">

**Comment by Tyriar** [comment]
I'm confused, you say the go extension is not installed, mention go settings and then show a bunch of perk scripts and watchman both of which VS Code doesn't use? 🤔

You should look into where the problem processes are spawned from because this really seems like either an extension issue or some other software.
