### ISSUE TITLE
require('vscode') error in debug extension  vscode-mock-debug/out/mockDebug.js file 

### ISSUE THREAD

**Issue by guogaigai** [Microsoft/vscode#10031]
- VSCode Version:1.3.1
- OS Version:ubuntu12.04

Steps to Reproduce:

1. I install mock-debug by the guide command below, it is no problem 
git clone https://github.com/Microsoft/vscode-mock-debug.git
cd vscode-mock-debug
npm install
2. vscode-mock-debug/out/extension.js file has the code var vscode = require('vscode') .I try to add var vscode = require('vscode') in vscode-mock-debug/out/mockDebug.js file for some test ,but when i press F5 to debug a read.md file , there is error show: Debug adapter process has terminated unexpectedly , In the console tab of developer tool shows [uncaught exception ]:Error read ECONNRESET. If I not add var vscode = require('vscode') will be ok .

As i checked there is vscode in the vscode-mock-debug/node_modules folder, and the extension.js file require('vscode') has no problem ,why in mockDebug.js is not ok . Is there anybody no this issue ? I am waiting for your reply ,thank you very much

**Comment by guogaigai** [comment]
@weinand  I want to know how to require('vscode') correctly  in debugger program entry file ,such as vscode-mock-debug/out/mockDebug.js . To tell the truth , I am developing my own debugger extension , encounter this issue ,so i test require('vscode') in vscode-mock-debug debugger , it has the same problem . I hope you can help me check it ,it is urgent for me , thank you very much ~

**Comment by isidorn** [comment]
VSCode-mock-debug is a project written in [typescript](https://www.typescriptlang.org/), it is not recommended to modify the generated javascript code. So I would add my changes to the src/mockDebug.ts file and then launch (which will build the js files out of ts files as a preLaunchTask).

Still I followed the exact steps you were doing and I could not reproduce the issue you are seeing.

For your own adapter in order to require('vscode') you need to have a devDependencies to 'vscode'. Checkout the structure of `package.json` of the mock debug adapter

**Comment by guogaigai** [comment]
@isidorn  Do you try to add var vscode = require('vscode') in vscode-mock-debug/out/mockDebug.js  file to check ?  I have checkout the structure of package.json file of mock debug adapter ,but if the mock debug adapter has this problem, how can i solve it with my own adapter

**Comment by isidorn** [comment]
@guogaigai yes I did that and the mock debug does not have this problem.
You can attach a gif to better show the issue you are seeing

**Comment by guogaigai** [comment]
@isidorn  I try to attach a gif by click the "selecting them" link ,but it cannot upload successful , does it is because my question has been closed ??

**Comment by guogaigai** [comment]
![mock-debugger_error](https://cloud.githubusercontent.com/assets/18524505/17322952/8b740ec0-58d2-11e6-9613-fae9836cc866.gif)

**Comment by guogaigai** [comment]
@isidorn   I have attached the gif file successful ,please help me check it . This error is result from I try to added var vscode = require('vscode') in mockDebug.js file.

**Comment by isidorn** [comment]
No it has nothing to do with the issue being closed, you should still be able to drag and drop a .gif file.
Please add a dependency to 'vsode' in your package.json and do an `npm install` in your project

Also checkout my previous comments and edit typescript files, not javascript.

**Comment by guogaigai** [comment]
@isidorn  Even as you said ,modify the src/mockDebug.ts  file ,it has no this issue ,but can you tell me why i modify the out/mockDebug.js file is is not ok . To tell the truth , i am not familiar with typescript , my adapter is written by js.  And in my package.json file i have done as your advice , my main extension.js file is also no problem ,but the debugger file will show the error i describe above

**Comment by guogaigai** [comment]
@isidorn  Can you give me some advice about how to require('vscode') correctly in  adapter debugger  js file directly . This issue have troubled me for a long time . Thank you very much

**Comment by isidorn** [comment]
@guogaigai for that I suggest to use the yeoman generator to generate a brand new vscode js extension. VSCode javascript extensions require('vscode') and everything works properly - so that would be a good starting point.
More details can be found here https://code.visualstudio.com/docs/tools/yocode

**Comment by guogaigai** [comment]
@isidorn  Yes , my adapter extension is created by yo code javascript template . It indeed have require('vscode') in the extension.js file ,and i have add my own js file , it also no problem , but the issue is when i add the debugger program entry file , it will have the issue . Does it is because when do debug , it will start a new standalone process ,or it have some special ?

**Comment by guogaigai** [comment]
@isidorn If possible , i think if you can try to add a debugger in the js extension which created by yo code javascript template , and then add var vscode = require('vscode') in the entry file of your debugger .  I know this may trouble you so much , but i just have no other ideas . Thanks a lot

**Comment by guogaigai** [comment]
@isidorn  For this issue , i have read vscode official docs and common Q&A  much times .I just not find the reason and feasible solved method . I hope you can help me check it . If this issue is not solved ,i just cannot go on with my extension development,and the develop task is urgent . I need your help,thanks again ~

**Comment by weinand** [comment]
@guogaigai a `require('vscode')` makes only sense in extension code because the 'vscode' module defines the extension API and that is only available if the extension code runs in the 'extension host' process.

A debug adapter (e.g. mockDebug.ts) is standalone code that does **not** run in the extension host process. I uses its own runtime and is completely independent from VS Code extensions. It cannot use anything that is defined in 'vscode' because it is not running in an environment that provides the API.

The mock example tries to show this:
- `extension.ts` is the extension code that runs in the extension host and has access to the VS Code API and uses the `require('vscode')`.
- `mockDebug.ts` is a debug adapter that runs as a standalone server independent from the extension host (in the same way a 'language server' runs as a standalone server independent from the extension host).

It does not makes sense to use `require('vscode')` in a debug adapter and VS Code will never support this.
