### ISSUE TITLE
vscode编辑器toggle device失败当是dock to right的时候

### ISSUE THREAD

**Issue by Mirefire** [microsoft/vscode#100354]
帮助---切换开发者工具，dock size 是dock to right ，点击toggle device,窗口为手机模式，当再点一次，失效

**Comment by iigmir** [comment]
Hmm I am not familiar with Simplified Chinese UI, but it's probably talking about reproducing steps:

1. Click "Help" on the menu, then click "Toggle Developer Tools".
2. Make sure the devtool's Dock side is "Right".
3. Click "Toggle device toolbar". The screen should be on the mobile mode(It's called responsive mode by the way).
4. Click "Toggle device toolbar" again. The problem is the device toolbar can't toggle now.

But I can't reproduce. It looks fine to me.

---

@Mirefire

我用英文版看没有问题耶，你能不能提供版本资讯？我想是「帮助」里面的「关于」那边。应该有类似这样的资讯：
![2020-06-19 15_10_56-Visual Studio Code](https://user-images.githubusercontent.com/11061770/85106632-19937780-b23f-11ea-92f0-036d6a746137.png)

**Comment by deepak1556** [comment]
@iigmir thanks for the translation!

I am unable to repro the issue as well following the provided steps.

**Comment by Mirefire** [comment]
对不起，这么久才回，我用的中文语言包之前，现在更新就没有这样问题了

**Comment by Mirefire** [comment]
Sorry, it took me so long to reply. Before I used the Chinese language package, there was no such problem when I updated it now

**Comment by deepak1556** [comment]
Thanks for confirming.
