### ISSUE TITLE
Turning on sync from an old device fails

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#100348]
Had a laptop that was using sync a month ago, today I tried to turn on sync via the gear and was prompted with a "Sign in to turn on sync" toast, even though I was already signed in but sync was off. Logs below:

```log
[2020-06-16 20:49:27.960] [userDataSync] [info] Auto Sync: Started
[2020-06-16 20:49:27.960] [userDataSync] [info] Auto Sync: Triggered by Interval
[2020-06-16 20:49:28.612] [userDataSync] [error] SessionExpired (UserDataSyncError) : Cannot sync because current session is expired
    at _.doSync (file:///C:/Users/misolori/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:514:374)
[2020-06-16 20:49:28.612] [userDataSync] [info] Auto Sync: Sync is turned off in the cloud.
[2020-06-16 20:49:28.718] [userDataSync] [info] Did reset the local sync state.
[2020-06-16 20:49:28.718] [userDataSync] [info] Auto Sync: Disabled because sync is disabled
[2020-06-16 20:49:28.719] [userDataSync] [info] Auto Sync: Stopped
[2020-06-16 20:49:28.720] [userDataSync] [info] Auto Sync: Turned off sync because sync is turned off in the cloud
[2020-06-16 20:49:28.721] [userDataSync] [info] Canelled sync that is in progress
```

**Comment by sandy081** [comment]
@misolori Are there steps to repro this?

**Comment by misolori** [comment]
Unfortunately there are no repro steps besides having an older machine that was previously synced

**Comment by sandy081** [comment]
We show following notification when session gets expired.

<img width="1336" alt="image" src="https://user-images.githubusercontent.com/10746682/85502078-e35f4a80-b5e6-11ea-8000-cc1f69a523d9.png">

Are you seeing a different notification?

**Comment by misolori** [comment]
So yes I did get this notification and when I click on Turn On it failed. What are other logs that I can gather next time in case this happens? Seems to be hard to reproduce.

**Comment by fdncred** [comment]
exact same error. been syncing on one system for weeks. get a new system and turn on sync to get extensions and settings and it pukes. are there any good steps to diagnose this? i'm using github - is there somewhere i can go in my gh account and reset this stuff?

**Comment by sandy081** [comment]
- You were syncing on this machine using your account
- You came back to this machine after long time and you saw `Sign in to Sync preferences` -> It means you are signed out of Sync
- During this period you did reset and started sync using the same account from another machine
- You signed in and it continued syncing preferences on this machine
- Since this machine is still using old session it bailed off and complained that sync was turned off from another device.

I think in this scenario the better message would be `Preferences Sync was turned off because current session is expired` What do you think? Please let me know if you think of better message.

**Comment by sandy081** [comment]
@fdncred Please follow this - https://code.visualstudio.com/docs/editor/settings-sync

**Comment by fdncred** [comment]
Thanks. Maybe i posted to the wrong thread because mine was not about and 'old device'. My complaint was it wasn't working with this exact error listed above. My 'main' system was actively used daily and sync'd to the cloud but no  other system. My new system was a new system and was never used. I tried to sync and it puked for hours. Then all of a sudden it worked.

**Comment by sandy081** [comment]
> I think in this scenario the better message would be Preferences Sync was turned off because current session is expired What do you think? Please let me know if you think of better message.

@misolori Any recommendations for above proposal?

**Comment by misolori** [comment]
@sandy081 I think that message is better than before, but we should be more direct in guiding them on what to do, like:

> Preferences Sync was turned off because current session is expired, **please sign in again to turn on sync**.

**Comment by sandy081** [comment]
To verify:

- **Machine 1** - Turn on Sync
- **Machine 2** - Turn on Sync
- **Machine 1** - Sign out from the account you are using to sync
- **Machine 1** - Quit VS Code
- **Machine 2** - Turn off Sync on all devices (check the option to turn off sync in all devices)
- **Machine 1** - Open VS Code
- **Machine 1** - Make sure you see `Sign in to Sync Preferences` option under Accounts or Gear icon
- **Machine 1** - Sign in
- **Machine 1** - Verify that you see following notification

> Preferences Sync was turned off because current session is expired, please sign in again to turn on sync.
