### ISSUE TITLE
search view: preserve last focused item

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#100328]
@roblourens @JacksonKearl is it possible in the search view to preserve last focused item, such when the view is focused again we move the focus to the previously focused item, and not always to the input. Should I file a new issue for this?

_Originally posted by @isidorn in https://github.com/microsoft/vscode/issues/99564#issuecomment-644763372_

**Comment by isidorn** [comment]
fyi @neurrone 
@JacksonKearl if you do not have plans to tackle this in the near future does it make sense to open it up for PRs from the community?

**Comment by JacksonKearl** [comment]
@isidorn added `help-wanted`. Given this is an a11y concern I've bumped it up to July if it doesn't get lookedat by a community member before then.

**Comment by isidorn** [comment]
@JacksonKearl sounds great, thanks!

**Comment by roblourens** [comment]
You can get to the same item by pressing cmd+down once. I would take a PR that adds a new command to put focus wherever it previously was instead of forcing it into the input, for people who want to opt into this behavior, but I would want to keep the same behavior by default.

Basically another instance of the general issue that the same ctrl+shift+f shortcut is overloaded for starting a new search (focus to input) and manipulating search results (focus to search results)

**Comment by Neurrone** [comment]
I am not sure about how this interacts with other panels but I'm wondering if this is a general problem for these sorts of composite controls, not just this one.

**Comment by roblourens** [comment]
Not really - others have the same layout of an input box on top and some rows of content below, but it's less of a common usecase to want to quickly focus the content with the keyboard, say, the extension viewlet.

**Comment by isidorn** [comment]
Yeah it is up to each view to implement the `focus()` as it wants. Idealy it should remember the last focused item (like the explorer does)

**Comment by mohtamba** [comment]
I was wondering if anyone is working on this issue? If not I would like to attempt to tackle it.

**Comment by isidorn** [comment]
@mohtamba as far as I know nobody is actively looking into this so you can try to create a pr.

**Comment by mohtamba** [comment]
I just wanted to clarify what the desired functionality of this issue is? Do we want the focus to remain on the current item after the search view is opened instead of focusing on the input fields of the search view?

**Comment by Neurrone** [comment]
@mohtamba apologies for the late reply.

When the search view is opened and when you press enter on one of the results, it takes your focus to the editor which is the expected behaviour.

What isn't desirable is that when pressing shift+f6 which brings your focus back to the search pane, focus goes right back to the search input field, i.e the first focusable control. I'd expect it to either:

1. Move focus back to the node that I was on, assuming that I haven't done text edits that causes it to be removed from the tree because it no longer contains the search term
2. If my previously focused node was removed, focus should move to the next one (or the previous one if there is no next one). The intent is to be able to efficiently return to where I was via a keyboard.
3. If my focus was in other parts of the search view, it should also remember it and return there too.

**Comment by isidorn** [comment]
@JacksonKearl thanks for fixing this. Let's add bug label so we get this verified.
@Neurrone you can try it out with vscode insiders from Friday or next week and let us know if it is good for you now.

**Comment by Neurrone** [comment]
Confirmed that this works really well as intended

**Comment by isidorn** [comment]
Thanks, adding verified label.
