### ISSUE TITLE
Extension Host terminated unexpectedly

### ISSUE THREAD

**Issue by sanjivyash** [microsoft/vscode#100413]
![VScodeissue](https://user-images.githubusercontent.com/58814491/84934685-4fc4e000-b0f5-11ea-924c-6220c266860b.png)

- VSCode Version:1.46.0
- OS Version:Windows10 Version 2004 64-bit

As soon as I start working on any project, this issue arises. The following steps have been tried to no avail: 
(1) Turning System Certificates Off
(2) Clearing the editor history

The screenshot of the issue has been attached. I'm fairly new to the editor so don't have much idea about its internal working.

EDIT: An incorrect assertion on my part has been removed, sorry for the confusion.

**Comment by alexdima** [comment]
Here's what code 7 stands for -- https://github.com/nodejs/node/blob/db52ae8b7f9bc458b3ab47369fc828e273efd0df/doc/api/process.md#exit-codes :

![image](https://user-images.githubusercontent.com/5047891/85866230-5e7f5700-b7c7-11ea-9a70-fb37ac0d738d.png)

In your screenshot, I can see that you have not disabled all extensions, but in the issue you state that the crash reproduces with all extensions disabled. Can you please confirm that you have indeed disabled all extensions and the extension host process crashes all the time?

**Comment by sanjivyash** [comment]
I am sorry about the confusion, that was a mistake and a serious miscommunication on my part. I disabled all my extensions, restarted my PC, and enabled all the extensions again and it still crashed. After disabling all extensions, I do not see a reason for the extension host to crash (since it would have no extension to handle), however I do not know how to test it. At the very least, the error message goes away. But the editor is practically useless without the extensions.

I am not sure if this is happening due to a specific extension, but the latest extension I had installed was the live sass compiler. And I also see that particular extension mentioned in the error message. I have tried disabling that one extension and starting, but unfortunately, the editor does not crash immediately so I cannot be certain whether it is working now or not. Moreover, it crashes only when I open a huge folder (a Django Project folder) but smaller projects work seamlessly.

Please suggest what more should be done to convey the relevant information you need.

**Comment by alexdima** [comment]
Well, here is how it basically works: all extensions share a single process called the extension host. A critical bug in a single extension can bring the entire extension host process down. We don't have anything else except collecting crash dumps or error stacks in order to figure out which extension it is, since any one of them could cause such a crash. These crashes are sometimes even more difficult to track down if an extension uses native node modules (basically C++ code that is compiled to a `.dll` and then loaded in the extension host process).

So IMHO, from having dealt with numerous such issues, **this crash is definitely caused by one of your installed extensions**. If your extension host was stable before installing the live sass compiler, and if you cannot reproduce a crash with the extension installed, then yes, it most likely is the live sass compiler.

I have looked at the issues reported against the live sass compiler and searched for "crash" -- https://github.com/ritwickdey/vscode-live-sass-compiler/issues?q=is%3Aissue+is%3Aopen+crash

If you look at the commit log, it appears the extension is basically abandoned since 2018. So, you can:
* create an issue against the extension (will probably be ignored since the extension appears abandoned)
* uninstall the extension (will probably resolve the issue for you)
* give a bad rating to the extension such that others don't install it
