### ISSUE TITLE
Visual Studio Code does not appear to save files until it is closed.

### ISSUE THREAD

**Issue by MarcMenzel** [microsoft/vscode#100433]
Issue Type: <b>Bug</b>

As I edit files in Visual Studio Code, I expect the files to be saved as I edit them.  However, as I attempt to upload the files to the server, I find out that there are no changes to the file that I have updated. Only after I close Visual Studio Code do I see the files updated.

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T09:03:20.462Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3598)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (5.76GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none
(2 theme extensions excluded)

**Comment by MarcMenzel** [comment]
To recreate the issue, try saving an html file in Visual Studio Code and checking the Windows or File Explorer to see if the file write time has changed or try to view the html file in a browser to see if there any changes after modifying it in Visual Studio Code, if there are not any changes in the file try closing  Visual Studio Code and then checking to see if there are any changes after exiting  Visual Studio Code.

**Comment by MarcMenzel** [comment]
I have made changes to html files in Visual Studio Code with AutoSave set on afterDelay. The problem is that when I view the html file in a browser, I don't see any changes. If I open up Notepad to edit the html file and then save it Notepad, I see the changes that I made when I view the html file in a browser. I viewed the html file in the new Microsoft Edge browser.

**Comment by bpasero** [comment]
> To recreate the issue, try saving an html file in Visual Studio Code and checking the Windows or File Explorer to see if the file write time has changed or try to view the html file in a browser to see if there any changes after modifying it in Visual Studio Code

This seems like a very basic thing that - if not working - no user could use VSCode to save files, would you agree. As such, would you agree this maybe specific to your setup and not an issue with VSCode? How is your setup looking like.

**Comment by MarcMenzel** [comment]
I am running VS Code version: Code 1.46.0 on Windows_NT x64 10.0.19041 (basically Windows 10 Profession Edition Version 2004. I am not sure if it is an issue on my end or not. I will have to research it.

**Comment by bpasero** [comment]
PLease do.

**Comment by MarcMenzel** [comment]
If it is on my end, what could the problem be?

**Comment by bpasero** [comment]
Is this a local file system or remote? Does it happen with every folder or only specific? Are you using OneDrive or any other thing?

**Comment by MarcMenzel** [comment]
It is a local system.

**Comment by MarcMenzel** [comment]
I am not using OneDrive for my html files that I edit. It has happened before with other folders.

**Comment by MarcMenzel** [comment]
I wonder if it has to do with "EBADF: bad file descriptor, fdatasync". I am not sure what that is. I saw that on another GitHub issue report. form almost two years ago. It was working just a day or two ago.

**Comment by bpasero** [comment]
@MarcMenzel yeah that error sounds suspicious and maybe points to issues on the file system or hard disk. We only try to `fdatasync` once and then give up. Possibly your disk is corrupt?

**Comment by MarcMenzel** [comment]
I am not to sure.

**Comment by provks** [comment]
Issue Type: <b>Bug</b>

Hi, The issue is the same, file not saved, UI is fine, it shows the file is saved. Although, I have enabled auto file save. But the terminal logs show that the older JS code is executed instead of the updated one.

To actually save the files. I need to close the VS Code and open it again. I am using Ubuntu 20.04. As I am still learning the Nodejs, it took me almost a week to finally realize the issue is with the editor not with my code. Facing this issue since the last VS Code update. Further details are attached below. I have installed VS Code from the snap store.

Version: 1.46.1
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:13:08.304Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.4.0-37-generic snap

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:08.304Z)
OS version: Linux x64 5.4.0-37-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-5010U CPU @ 2.10GHz (4 x 1831)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|0, 1, 1|
|Memory (System)|7.69GB (0.63GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|3.11.0
flutter|Dar|3.11.0
vscode-html-css|ecm|0.2.3
code-runner|for|0.10.0
java|red|0.63.0
LiveServer|rit|5.6.1
bootstrap4-vscode|the|6.1.0
vscodeintellicode|Vis|1.2.8
vscode-java-debug|vsc|0.26.0
vscode-java-dependency|vsc|0.10.2
vscode-java-pack|vsc|0.9.1
vscode-java-test|vsc|0.23.0
vscode-maven|vsc|0.22.0


</details>

**Comment by bpasero** [comment]
@provks to clarify you:
* open a file
* make changes in VSCode
* File > Save
* open a terminal
* run `less <file name>`

And the contents that are printed do not match the changes you did in VSCode until you close VSCode?

**Comment by provks** [comment]
@bpasero Yes, that is what happening. But this gets resolved as soon as I restart the VSCode. Sometimes, I have to restart the system as well for this to be resolved. 

Is this because I have installed it from the snap store?

**Comment by bpasero** [comment]
@provks to check that, here is the archive version to compare with: https://az764295.vo.msecnd.net/stable/cd9ea6488829f560dc949a8b2fb789f3cdc05f5d/code-stable-1592429223.tar.gz

**Comment by provks** [comment]
Thank you @bpasero for the quick response. I will definitely try this.

**Comment by bpasero** [comment]
Thanks
