### ISSUE TITLE
Editor doesn't detect typings in "typings/globals"

### ISSUE THREAD

**Issue by MartinHaeusler** [Microsoft/vscode#10042]
- VSCode Version: 1.3.1
- OS Version: Windows 10, 64bit

Steps to Reproduce:

1. Create a regular typescript project with the files provided below.
2. Remove the "*.txt" file endings to make them json files again (github doesn't allow *.json endings as attachments, sorry)
2. Run "npm install"
3. Run "typings install"
4. Create a *.ts file that imports the 'react' module
5. Look at the typescript error you are getting from the editor.

In short: any typings file that ends up in "typings/globals" will NOT be detected by the editor. However, when running through the typscript compiler, e.g. via webpack, everything's fine. It's only the editor, which is really annoying.

[tsconfig.json.txt](https://github.com/Microsoft/vscode/files/397458/tsconfig.json.txt)
[typings.json.txt](https://github.com/Microsoft/vscode/files/397456/typings.json.txt)
[package.json.txt](https://github.com/Microsoft/vscode/files/397457/package.json.txt)

**Comment by dbaeumer** [comment]
@MartinHaeusler the problem is that most of the properties in the tsconfig.json file are not supported by the 'native' tsc compiler. I tried your example and compiling it with the native tsc compiler using the current version fails as well.

I will move the item to the TS team to comment on the future of these properties in the tsconfig.json and how they will be supported by the tsserver (which VSCode uses for its smartness).

**Comment by dbaeumer** [comment]
Since you are using a special version of TS (the unofficial 2.0.0 version) you need to let VS Code know about this as well. You can do so by using the following setting:

```
	"typescript.tsdk": "./node_modules/typescript/lib"
```

This makes a simple ts file work for me:

![cast](https://cloud.githubusercontent.com/assets/1931590/17367349/ea388068-598f-11e6-9bb2-95471a7a39a7.gif)

**Comment by MartinHaeusler** [comment]
@dbaeumer: Yes we are using typescript 2.0.0. I was wondering how to tell vscode which version to use but I could not find it anywhere in the documentation. I will try this as soon as I get back into the office, thanks a lot!

**Comment by whitecolor** [comment]
adding `"typescript.tsdk": "./node_modules/typescript/lib"` in `.vscode/settings.json` works :+1:
