### ISSUE TITLE
Restoring extensions data from synced view shows wrong data

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#100448]
Somehow I ended up in a state where my extensions were gone after setting it up on a new machine. So I tried to go back and rollback the changes, but when I click on "Restore" for the extension and confirm, nothing happens.

![image](https://user-images.githubusercontent.com/35271042/84975462-4e39ee80-b0da-11ea-8efb-3d515d70d78e.png)

 I go back to my extension list and it's empty

![image](https://user-images.githubusercontent.com/35271042/84975470-585bed00-b0da-11ea-8839-9584de3fe7a7.png)

It isn't until I go back to the sync view that I notice that an entry from a few hours ago actually has different data:

![image](https://user-images.githubusercontent.com/35271042/84975607-b4267600-b0da-11ea-8105-00daf2301fe7.png)

So I revert to this point and now my extensions are installed. So I'm wonder why there are entries in the extensions list when those are empty. We should only show entries for data that exists otherwise it's really confusing.

**Comment by sandy081** [comment]
@misolori Is this similar request to https://github.com/microsoft/vscode/issues/100416 ?

I understand that it is confusing if I try to revert when there is no change, instead of hiding entries (which I reasoned we should not in above issue) I would show a message that there is no change to apply so that user is aware of. Let me know what you think?

**Comment by misolori** [comment]
Yes, this appears to be a duplicate. Now that I realize that the data shows all synced transactions I can see why nothing happens.
