### ISSUE TITLE
Problems Saving JSON

### ISSUE THREAD

**Issue by s1gnalCha0s** [microsoft/vscode#100418]
- VSCode Version: 1.46.0
- OS Version: MacOS 10.15.5

It seems like VSCode is taking the first line of unsaved input and trying to use it as a filename. If it is JSON or other input without any spaces, it will not be able to use the first line as a filename and will not allow the file to be saved. eg., {"swagger":"2.0","info":{"description":"Api Documentation",...}

Steps to Reproduce:

1. Paste the following input into VSCode:

{"swagger":"2.0","info":{"description":"Api Documentation","version":"1.0","title":"Api Documentation","termsOfService":"urn:tos","contact":{},"license":{"name":"Apache 2.0","url":"http://www.apache.org/licenses/LICENSE-2.0"}

2. Try to save the document. Cmd-s

The application will stop responding, and return the error: "The save file operation failed. The save file operation failed to connect to the open and save panel service."

![image](https://user-images.githubusercontent.com/10787787/84937628-ed39f880-b090-11ea-970d-3fc047632f12.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
VSCode is built on top of a large number of components that are not maintained by the VSCode team directly. This includes:
* [Electron](https://github.com/electron/electron) as the cross platform UI framework
* [node.js](https://github.com/nodejs/node) for most integration into the OS
* [Chromium](https://bugs.chromium.org/p/chromium/issues/list) as runtime and rendering engine (HTML, CSS, JS)
* and after all, the operating system VSCode is running on

Reading this issue, it seems to originate not from VSCode itself but rather one of these upstream components. As such, in order to resolve it, it would need to get fixed in the upstream component. I will go ahead and close this issue and kindly ask to report this issue to the upstream component if possible:
* for UI, OS integration: https://github.com/electron/electron
* for Rendering: https://bugs.chromium.org/p/chromium/issues/list
* for file IO: https://github.com/nodejs/node

Thanks for understanding.

**Comment by bpasero** [comment]
Related: https://www.google.com/search?q=the+save+file+operation+failed+to+connect+to+the+open+and+save+panel+service&oq=the+save+file+operation+failed+to+connec&aqs=chrome.0.0j69i57j0.2387j0j7&sourceid=chrome&ie=UTF-8
