### ISSUE TITLE
Reveal in Finder not working if Finder is closed

### ISSUE THREAD

**Issue by normalser** [microsoft/vscode#10041]
- VSCode Version: 1.4.0-insiders
- OS Version: OSX 10.11.6 (15G31)

Steps to Reproduce:
1. Quit Finder
   ![image](https://cloud.githubusercontent.com/assets/1723815/17335162/001b729e-58a7-11e6-8424-23246b33610a.png)
2. Use Command Palette and select `Reveal Active File in Finder` - problem - nothing will happen
3. Use `CMD+K R` combination - problem - status bar will show: 
   ![image](https://cloud.githubusercontent.com/assets/1723815/17335252/4ca07114-58a7-11e6-8f13-839d150788d0.png)

PS. Sublime can handle that case

**Comment by kieferrm** [comment]
@wallverb the command is `⌘K R`. It's correct that `⌘K ⌘R` is not a command.

**Comment by wallverb** [comment]
Right, sorry, point #3 is invalid then, `CMD+K R` in this case does nothing (similar to Command Palette `Reveal Active File in Finder`).Thanks

**Comment by bpasero** [comment]
An electron issue, we use their method to show an item in the finder.

**Comment by bpasero** [comment]
@wallverb  could you give our insider release a try to see if this issue is fixed? 
You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by wallverb** [comment]
@bpasero Still the same issue with insiders @ 0619ede1e469ed23fbb214eaa0377625a402ca87 - although Atom also does not handle this case (only Sublime does) - so must be Electron issue

**Comment by bpasero** [comment]
Got it. I suggest to let Electron know with an issue and link it here.

**Comment by wangweixuan** [comment]
Electron API `showItemInFolder` in fact returns a boolean. But we don't use that result([windowService.ts](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/windows/electron-main/windowsService.ts#L276)), so when the action fails you won't get any feedback.
I think we should handle its result just like what we do for `openExternal`, so that me can at least show a failure message in this case.

In addition, quitting Finder isn't recommended. I tried to do this and then apply 'Reveal in Finder' at an app in the Dock, but nothing happened as well.

**Comment by bpasero** [comment]
That seems possible, PR welcome.

**Comment by trivikr** [comment]
While debugging this issue, I put breakpoints at https://github.com/Microsoft/vscode/blob/39130b09e65865fd2fcaf0d4cb8dd3c6fb6da7a6/src/vs/platform/windows/common/windowsIpc.ts#L301-L303

The `_state` in return value contains **"success"** even when the Finder is not available
![screen shot 2017-10-22 at 9 11 20 pm](https://user-images.githubusercontent.com/16024985/31872108-fad5e270-b76d-11e7-9a20-01e522feae90.png)
