### ISSUE TITLE
Where VSCode save the selected theme

### ISSUE THREAD

**Issue by shanalikhan** [Microsoft/vscode#10046]
is there any place where visual studio code set the current theme in file ? so i can retrieve it from there.

**Comment by kieferrm** [comment]
This is a [good write-up](https://github.com/Microsoft/vscode/issues/3884#issuecomment-230912738). However, as you can see the structure is being reconsidered and it's not consider API at this point.

Does your extension want to know the theme? If so, in way is it using for? I'm asking since for example we already pass in theme marker classes into the html preview command. I.e. content presented in the html preview can find out in which theme its presented.  If that's not sufficient, pls file a feature request requesting and API for extensions to retrieve the current theme.
