### ISSUE TITLE
VSCode Unable to Recognise default "program" in launch.json

### ISSUE THREAD

**Issue by sebasijan** [Microsoft/vscode#10040]
- VSCode Version: 1.3.1
- OS Version: Windows 7 Professional

Steps to Reproduce:

1. Create a new Console Application using the powershell script: 

        function New-ConsoleApplication {
            param (
                [string]$Path,
                [string]$Name,
                [bool]$Open,
                [bool]$Run
            )

            New-Item -Name $Name -Type Directory -Path $Path
            cd "$Path\$Name"
            dotnet new
            dotnet restore 
            if ($Open){code .}
            if ($Run) {dotnet run}
        }

        New-ConsoleApplication -Name "ConsoleApplication" -Path "C:\Users\First.Surname\Source\" -Open $true -Run $true`

2. The folder structure and code is created, and it is opened in VSCode. The application executes and prints "Hello World!" to the PowerShell terminal.

**PowerShell Output:**

		Directory: C:\Users\Seb.Kotze\Source

		Mode                LastWriteTime     Length Name                              
		----                -------------     ------ ----                              
		d----        02/08/2016     16:06            ConsoleApplication                
		Created new C# project in C:\Users\Seb.Kotze\Source\ConsoleApplication.
		log  : Restoring packages for C:\Users\Seb.Kotze\Source\ConsoleApplication\proj
		ect.json...
		log  : Writing lock file to disk. Path: C:\Users\Seb.Kotze\Source\ConsoleApplic
		ation\project.lock.json
		log  : C:\Users\Seb.Kotze\Source\ConsoleApplication\project.json
		log  : Restore completed in 2514ms.
		Project ConsoleApplication (.NETCoreApp,Version=v1.0) will be compiled because 
		expected outputs are missing
		Compiling ConsoleApplication for .NETCoreApp,Version=v1.0

		Compilation succeeded.
			0 Warning(s)
			0 Error(s)

		Time elapsed 00:00:01.5621203
		 

		Hello World!

3. In VSCode, click `Debug` or `Ctrl` + `Shift` + `D`, then press `F5`

4. Select `.NET Core` as the environment - `launch.json` is opened - then press `F5` again

5. > No task runner configured

6. Select `Configure Task Runner` - select `.NET Core` - `tasks.json` is opened

7. Press `F5` to launch

8. >launch: launch.json must be configured. Change 'program' to the path to the executable file that you would like to debug.

9. open `launch.json` 

10. `Program` is given by : `"${workspaceRoot}/bin/Debug/<target-framework>/<project-name.dll>"`

11. Changing this to the physical path of the `.dll` resolves the issue, but `VSCode` complains that : 

>Relative paths will no longer be automatically converted to absolute ones. Consider using ${workspaceRoot} as a prefix.
Path to the application dll or .NET Core host executable to launch. Example: '${workspaceRoot}/bin/Debug/<target-framework>/<project-name.dll>' where:
<target-framework>: (example: 'netstandard1.5') This is the name of the framework that the app is being built for. It is set in the project.json file.
<project-name>: (example: 'MyApp') The name of the project being debugged.

**Comment by isidorn** [comment]
@sebasijan do you still see this issue with vscode 1.4? If you keep using the ${workspaceRoot} do you end in this situation every time you try to start debugging?

**Comment by sebasijan** [comment]
@isidorn After trying the above steps in `1.4.0` it seems to be working fine (I can see the program output in the console after pressing `F5`).

**Comment by gmsDave** [comment]
I'm getting this exact same error on v1.7.1 on macOS 10.11 (El Capitan).  I'm extremely new to macOS so maybe I don't have something configured correctly. When I execute `dotnet run` from the terminal, it works fine.  But after going through the VS Code automatic steps of adding a launch.json and tasks.json, I get this message when I try to debug through VS Code.

**Comment by isidorn** [comment]
@gmsDave make sure your program attribute is launch.json is has a correct absolute paht - or is using ${workspaceRoot}. If the problem still occurs I recommend to file it to the C# extension since the launching of your program is done on the extension side 
https://github.com/OmniSharp/omnisharp-vscode

**Comment by gmsDave** [comment]
It was set to `${workspaceRoot}/bin/Debug/<target-framework>/<project-name.dll>` but even setting program to the exact path, `/Users/daveslinn/desktop/dotnet/bin/debug/netcoreapp1.0/dotnet.dll`, was still giving the same error, "launch: launch.json must be configured. Change 'program' to the path to the executable file that you would like to debug.".  I will head over to OmniSharp and re-post there.

**Comment by qiansen1386** [comment]
```json
"configurations": [
        {
            "name": ".NET Core Launch (console)",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "build",
            "program": "${workspaceRoot}/bin/Debug/<target-framework>/<project-name.dll>",
            "args": [],
            "cwd": "${workspaceRoot}",
            "stopAtEntry": false,
            "externalConsole": false
        },
```
###### launch.json #######
For `"program": "${workspaceRoot}/bin/Debug/<target-framework>/<project-name.dll>",`, you must find and paste in the exact path of the dll file like `${workspaceRoot}/bin/Debug/netcoreapp1.1/project1.dll` in order to hook the debuger up. In this case, what's the point of having the wildcard placeholder anyway?

Dear coordinator, the real issue here is the project kick-starting process is way too tedious for a console project.
You see, to start the project, we have to go through following steps:

1. We can only put bin folders in root folder. If we need more than one project -> Open more than one new windows, instead of creating multiple sub-folder in the same workspace.
2. Run `dotnet new`
3. Run `dotnet restore`
4. Choose debug page on sidebar, click on run button, and select `launch.json` profile to ".net Core"
5. Click on Set task runner, but it only generate a default file, apperently there is nothing to set.
6. Paste the exact path of main dll to program attribute of configuration of launch.json, as being said, otherwise the debugger won't work.
7. Start Debugging

What we really want: 

1. New folder
2. Run `dotnet new` in it.
3. Start Debugging

I wonder if it is possible. Is this the wrong place to report the issue?

**Comment by isidorn** [comment]
@qiansen1386 please file this feedback against the c# extension as this can be improved on their side
https://github.com/OmniSharp/omnisharp-vscode

**Comment by qiansen1386** [comment]
@isidorn Thanks

**Comment by virasana** [comment]
Still happening in 1.10.2 !  very poor "getting-started" experience:  I am following the Microsoft getting started tutorial here: https://docs.microsoft.com/en-gb/aspnet/core/tutorials/your-first-mac-aspnet

**Comment by kendrahavens** [comment]
For anyone still hitting this issue. 

1. Open up your Program.cs file **before** starting to debug. 
2. Opening any .cs file fires the C# extension.
3. The extension will then ask if it can load build assets . Hit **Yes**. 
    - It may take a few seconds to load Omnisharp
    - It only asks this if the launch.json and tasks.json haven't already been added to the project.
4. Then the extension will configure your launch.json and tasks.json for you.


For those interested there is an [issue tracking](https://github.com/Microsoft/vscode/issues/10861) this behavior.
