### ISSUE TITLE
Symbolic links to folders can lead to the same file opened in two tabs

### ISSUE THREAD

**Issue by wackywendell** [microsoft/vscode#100533]
### General Description

When a folder that is itself a symlink is used as a workspace, VS Code does not recognize that the files in that folder are _the same_ as files in the linked-to folder. Saving new files or opening existing files will use the linked-to folder, the Explorer Tree will use the symlinked folder, and Search will allow both, allowing the same file to be opened concurrently in two different editor tabs in the same project.

![Screen Shot 2020-06-18 at 5 39 48 PM](https://user-images.githubusercontent.com/245071/85074569-c5c75680-b18a-11ea-9757-103ab83bbb1b.png)

#### VSCode Version: **1.46.1**

From Code > About Visual Studio Code:

```
Version: 1.46.1
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:17:14.222Z (23 hrs ago)
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0
```

#### OS Version

From Apple > About This Mac: **OS X Catalina 10.15.4**

From Help > Report Issue (copy-pasted):

```
CPUs | Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz (4 x 3100)
-- | --
GPU Status | 2d_canvas: enabledflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmetal: disabled_offmultiple_raster_threads: enabled_onoop_rasterization: disabled_offprotected_video_decode: unavailable_offrasterization: enabledskia_renderer: disabled_off_okvideo_decode: enabledviz_display_compositor: enabled_onviz_hit_test_surface_layer: disabled_off_okwebgl: enabledwebgl2: enabled
Load (avg) | 8, 5, 6
Memory (System) | 16.00GB (2.35GB free)
Process Argv | --disable-extensions test_project_link
Screen Reader | no
VM | 0%
```

### Steps to Reproduce

- Setup
  1. Create a new directory, e.g. `mkdir test_project`
  2. Create a symbolic link to that directory, e.g. `ln -s test_project test_project_link`
  3. Open the symlinked folder in VS Code, e.g. `code  --disable-extensions test_project_link`
- Reproduce
  1. Create a new file in the symlinked workspace, and save it, e.g. to `example.txt`
      - **BUG 1**: File is shown in the open editors in the non-symlinked directory, e.g `example.txt - ~/test_project`
  2. Select the created file in the Explorer Tree. 
      - **BUG 2**: It opens a second editor *for the same file*.
  3. Use the command palette to search for your file, e.g. `⌘P` and type `example.txt`.
      - **BUG 3**: Both the non-symlinked and symlinked file will appear, and can be open in separate editors.

### Extra Notes

- Does this issue occur when all extensions are disabled?: **Yes**
- Does this issue occur in VSCode Insiders?: **Yes**

```
Version: 1.47.0-insider
Commit: 84f52fe1c0124307046ac0f5443493cda946e60f
Date: 2020-06-17T06:56:23.406Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0
```

**Comment by Kangaroux** [comment]
I also experience this issue when debugging on Ubuntu 19.10.

I store my projects in `~/Code` which is symlinked to a `/media` dir. When the debugger needs to display a file, such as when it hits a breakpoint, it opens a new tab with the `/media/...` path instead of the symlinked one.

**Comment by isidorn** [comment]
There might already be issues like this. You might find them if you search for label feature-reqeust and some keyword like symlink.
However for now leaving this issue open and assigning to backlog. Thanks

**Comment by wackywendell** [comment]
Hi @isidorn.

I have searched as you suggested (`is:issue symlink label:feature-request`), and while there are many issues that match that search, none seem to cover this; most are about editing symbolic links as files, instead of following them.

A couple issues look lightly related:

- #44635: mouseover in the Editor shows the "real path" and not symlink path
  - Seems related, and could be added to this list; a solution to this issue might solve #44635, but it seems less likely the other way around unless it were intentional.
- #18837 (and dupes #32649, #30682): Do not resolve symbolic links when opening folders 
  - The feature request there might provide a solution to this issue, but it is not the only possible solution, and that particular solution might not be a complete solution to this issue.

**Comment by MBetters** [comment]
This is a great write-up of a pressing issue. I second this feature request. There are lots of projects where it makes sense to symlink directories.

It's especially useful when using C/C++ and CMake Tools in a multi-root workspace where each workspace folder has its own CMakeLists.txt, toolchain file for its particular target architecture, and build folder. In such a project, the intellisense provided by CMake Tools gets messed up when symlinks are followed between workspace folders instead of treated like regular files. If there was a way to treat symlinks as regular files (by not following the symlinks) within VS Code, then the intellisense provided by CMake Tools would probably work.

I think the settings request posed by https://github.com/microsoft/vscode/issues/97030 is a sensible one and would address this isssue.

**Comment by wackywendell** [comment]
@MBetters: from what I can tell, your issue sounds more similar to #18837. This issue (#100533) occurs specifically when the root workspace directory is a symlink (or one of its parents is a symlink); your issue sounds like it involves symlinks that exist inside the workspace.

As such, this issue does not appear solvable by #97030; the root directory or its parents are not necessarily even visible inside the explorer, much less followable, and so a setting concerned specifically with the explorer would not necessarily solve this issue.

**Comment by gclinux** [comment]
I have the same issue on windows
> mkdir dir1\a.txt
>mklink \D dir1 dir2
>code dir2\a.txt
it will show dir1

**Comment by DavidGoldman** [comment]
I'm seeing the same issue here on macOS, perhaps VS Code should realpath the workspace when it is opened? Doe that seem reasonable?

Below, `foobar` points to `bar` but VS Code treats them separately, leading to duplicate file issues seen above.

```
mkdir -p /tmp/foo/bar && touch /tmp/foo/bar/bar.txt
ln -s /tmp/foo/bar /tmp/foo/foobar
code /tmp/foo/foobar 
code /tmp/foo/bar
```

**Comment by isidorn** [comment]
We are unlikely to detect symbolic links pointing to the same file, thus closing as out of scope.

**Comment by Kangaroux** [comment]
@isidorn When you open a file in the editor it should internally store the path to the original file. You can resolve a file's symlink to get the target file. When opening what looks to be a new file the editor could look through the open tabs and compare the internal path.

The tab's title should remain unchanged, the only difference is storing the canonical path.

**Comment by bpasero** [comment]
We have the infrastructure in place for mapping paths to canonical ones:

https://github.com/microsoft/vscode/blob/e9565331e70e3f5145ae049a3f8d7e50846f4972/src/vs/workbench/services/uriIdentity/common/uriIdentityService.ts#L70-L70

However this is code that can execute sync and does not require any disk lookup. We use this to fix path-casing issues on file systems that are case-insensitive (Windows, macOS). 

We are unlikely to ever make this async given how often this method is used, e.g. for problem markers that can potentially produce millions of entries.

**Comment by teki** [comment]
I run into this issue with `bazel`. It builds by creating a workspace with symlinked source files and builds in that folder. This is all good, but then when a `compile_commands.json` is generated it will contain those symlinked files.

I can see how it is not trivial to integrate any solution to this issue into VS Code as a whole. Maybe a filename resolver hook for opening files and implement this in a plugin would be better. Not totally integrated, but still provide some relieve.

**Comment by depablo** [comment]
> I also experience this issue when debugging on Ubuntu 19.10.
> 
> I store my projects in `~/Code` which is symlinked to a `/media` dir. When the debugger needs to display a file, such as when it hits a breakpoint, it opens a new tab with the `/media/...` path instead of the symlinked one.

If you didn't solve your problem yet try to use below setting of "launch" -> "configurations":
				"sourceFileMap": {
					"/media/": "~/Code", (or maybe /home/YOUR_HOME if ~ doesn't work)
				},

**Comment by Domiii** [comment]
I had an issue where some files showed up multiples times (each with multiple possible paths, due to symlinks). I fixed it with the `File: Clear Recently Opened` command. Afterwards, closing and opening the same file with `code symlink1/myfile` and `code hardlink1/myfile` always resulted in the same path.

**Comment by tronster** [comment]
OneDrive compounds this symbolic link issue on MacOS (Ventura 13.2).

I believe I've experienced this whether starting up with "**zsh**" or the "**Javascript Debug Terminal**".
Closing VSCode at: `/Users/myself/OneDrive/projects/foo`
VSCode reopens at: `/Users/myself/Library/CloudStorage/OneDrive-Personal/projects/foo`

Changing settings to:
```
"debug.javascript.terminalOptions": {
    "cwd" : "${workspaceFolder}"
}
```
Yields a path with `.../Library/CloudStroage/OneDrive-Personal/...` instead of the symbolic link `.../OneDrive/...`

Even kluges (tried so many) like this fails as `cwd` will automatically expand the Symbolic link:
```
"debug.javascript.terminalOptions": {
    "cwd" : "${workspaceFolder}/../../../../../OneDrive"
}
```
One solution may be to add an option for the path to not have it's symbolic links expanded.
e.g, 
```
"expandLinks" : false
```

**Comment by g0r3** [comment]
Affected by this too. Is there a good workaround for this? I want to use symlinks to easily switch in between different git worktrees of a project behind a symlink. But this behavior makes the usage quite annoying.

**Comment by tronster** [comment]
Why is this labeled out-of-scope?  
A Microsoft product "Visual Studio Code" is failing with a Microsoft product "OneDrive" on a platform they both support.
Further, this issue doesn't happen in the standalone Terminal, it only in Visual Studio Code's terminal.

If not Visual Studio Code's team, who should be addressing this issue?  The OneDrive team or ???

**Comment by frostius** [comment]
If vs-code doesn't supported multiple folders in the same workspace referencing a shared symlinked folder, what is the alternative for sharing source across projects?  Perhaps the vs-code team could address the issue direction as part of the vs-code documentation?

I've been using symlinked folders for years and as a result many of the "features" of vs-code are unreliable for me: global search/replace, code navegation, refactoring.  If there is a solution to shared source folders, I'd love to know what it is.

**Comment by Rullec** [comment]
Meet with this problem as well on Linux. It should be noticed as softlink are used not-so-rarely.

**Comment by dukesook** [comment]
Has this issue been resolved yet?

**Comment by synek317** [comment]
Quite disappointing it is considered "out-of-scope".

In the meantime, this workaround did the job for me:

```
# Function: command_realpath
# Description: This function resolves the real path of files or directories passed as arguments.
# Parameters:
#   - command_name: The name of the command to be executed.
#   - args: The list of arguments to be passed to the command.
# Returns: None
command_realpath() {
    local command_name="$1"
    shift
    local args=()
    for arg in "$@"; do
        if [[ -f "$arg" || -d "$arg" ]]; then
            args+=("$(readlink -f "$arg")")
        else
            args+=("$arg")
        fi
    done
    command "$command_name" "${args[@]}"
}

alias code='command_realpath code'
```

**Comment by bgolinvaux** [comment]
The worst part (that happened to me a few times) is making (unsaved) editing changes in a file and its symlinked incarnation and then having to resolve conflicts when saving the 2nd one!

**Comment by CendioOssman** [comment]
We use symlinks quite a bit here when we need some things on local storage instead of NFS, but still want to maintain a convenient file structure. Very annoying that vscode gets so confused by such a basic concept as symlinks. :/

@synek317 provided a nice workaround for invoking vscode on the command line. Thanks for that. Has anyone found something to adjust things when opening workspaces directly from vscode?

**Comment by bgolinvaux** [comment]
@CendioOssman  : I am using this in the `.vscode/settings.json` file at the workspace root.

The symlinks still lead to files being opened "twice" if I deliberately open them, but at least, they don't appear in search results, which dramatically reduces the probability of having them edit through the link and the proper path.

I guess this will do for now (It's a WSL2 project in a Win 11 host, if it matters)

```
{
    // This is a workaround for a VSCode issue: symlinked folders are not properly handed and
    // the same file can appear multiple times in the search results (this is not a bug because
    // the following setting is precisely meant to allow this behavior), but also be opened several
    // times in the editor, with VSCode unable to understand that the file is the same, which can
    // lead to a different set of in-memory changes appear for the same underlying file, thus
    // leading to conflicts and potential data loss if not handled properly.
    "search.followSymlinks":false
}
```

**Comment by araleza** [comment]
Hi, I'm experiencing this issue as well.  I only ever access the files in question via the symlink, but repeatedly end up with two copies of the files open in VS Code.  At no point is this file ever referenced except through the symlink, so VS Code should never have a version of it open that uses the absolute non-symlinked path.

**Comment by araleza** [comment]
@isidorn, you said that:

> we are unlikely to detect symbolic links pointing to the same file, thus closing as out of scope.

but in this case, the non-symlinked version is not referenced anywhere, so you wouldn't need to detect whether they're pointing at the same file or not.  You just need to find any code that converts the symlinked filenames into the non-symlinked versions and stop them from doing so.  Please would it be possible to re-open this?

**Comment by Lassebq** [comment]
Well this is pretty annoying, I encountered this while using debugger on a C project. As a temporary workaround I resolved symlink before opening project folder, that way opening files from built-in terminal doesn't create duplicate tabs.

There is no reason to not resolve symbolic links either when the project is opened or when opening a file. Either of these approaches would solve the issue.

**Comment by Lassebq** [comment]
> The worst part (that happened to me a few times) is making (unsaved) editing changes in a file and its symlinked incarnation and then having to resolve conflicts when saving the 2nd one!

I'm almost certain that's what deleted a source file for me, I had to restore my changes one by one since last commit.

**Comment by Spudd86** [comment]
It seems to me that rather than saying it can't be done, it would be far better to actually just check if two things are the same file the way that you are supposed to on Unix-like systems. Check if they have the same inode number rather than comparing paths. No need to resolve the symlink. just call `stat()` which is probably being done anyway when opening a file.

Please re-open and actually fix this. It's VERY easy to loose work by editing the same file in two places without vscode noticing and saving over work. I've done it multiple times. It also seems to interfere with correct lookup of symbol locations with the clang extension.

**Comment by Lassebq** [comment]
> It seems to me that rather than saying it can't be done, it would be far better to actually just check if two things are the same file the way that you are supposed to on Unix-like systems. Check if they have the same inode number rather than comparing paths. No need to resolve the symlink. just call `stat()` which is probably being done anyway when opening a file.
> 
> Please re-open and actually fix this. It's VERY easy to loose work by editing the same file in two places without vscode noticing and saving over work. I've done it multiple times. It also seems to interfere with correct lookup of symbol locations with the clang extension.

That's for hard links. Soft symlinks have their own inode. You **have to** resolve it first

**Comment by Spudd86** [comment]
When opening a file in an editor it has to follow the symlink. Also `stat()` follows symlinks by default, so you WILL get the inode number of the actual file that would be opened. Even if this is only partially fixed just for editor windows, which HAVE to call open and pay the cost of the symlink being resolved ANYWAY, it would be a significant improvement.

The inode is the unique identifier of a file, and is what should be used to answer the question of if two things are the same FILE, comparing paths only ever tells you if things are the same path witch is not the same thing.

There will still be problems, but it would prevent very confusing behaviour I see CONSTANTLY. There is a symlink in the path to the git repo for the code I work with freqently, it's not inside the repo, but every time I jump to a symbol location it is the RESOLVED path. This seems to also confuse vscode and leads to cases where it doesn't seem to fully be able to use all the refactoring tools since the locations clang gives for things seem to be the resolved path not the one that vscode sees. It makes working with this repo very frustrating.

**Comment by Lassebq** [comment]
Either having an option to follow symlinks for all opened files or making it the default behaviour would definitely solve the issue with duplicate tabs of the same file. Though I can see some cases where you wouldn't want to resolve symlink so imo it's better to be kept as a toggle.

**Comment by navyxliu** [comment]
I don't think it's correct to check inode. Like @Lassebq pointed out, softlink or symbolic links have different inodes from their targets. 

Both Linux and MacOS have readlink. In particular, '-f' or '--canonicalize' mode could be very helpful here. Every time vscode open a new file, I think it should go through so-called canonicalization because the path may contains softlinks.

**Comment by Spudd86** [comment]
> `stat` follows symlinks by default......???
> 
> ```
> $ stat .profile                                                          
>   File: .profile -> /home/lassebq/dots/config/profile
>   Size: 33        	Blocks: 0          IO Block: 4096   symbolic link
> Device: 8,18	Inode: 1838658     Links: 1
> Access: (0777/lrwxrwxrwx)  Uid: ( 1000/ lassebq)   Gid: (  100/   users)
> Access: 2024-05-28 23:17:03.153715491 +0300
> Modify: 2024-04-26 22:26:48.260790036 +0300
> Change: 2024-04-26 22:36:12.874086004 +0300
>  Birth: 2024-04-26 22:26:48.260790036 +0300
> $ stat dots/config/profile 
>   File: dots/config/profile
>   Size: 3042      	Blocks: 8          IO Block: 4096   regular file
> Device: 8,18	Inode: 1835251     Links: 1
> Access: (0644/-rw-r--r--)  Uid: ( 1000/ lassebq)   Gid: (  100/   users)
> Access: 2024-05-29 14:06:49.270614111 +0300
> Modify: 2024-05-19 15:19:40.797907278 +0300
> Change: 2024-05-19 15:19:40.804573953 +0300
>  Birth: 2024-04-05 01:39:22.804816521 +0300
> ```
> 
> 1838658 does not equal 1835251. So unless you're referring to some other `stat` soft symlinks are a unique file with different inode.

I'm talking about the stat syscall not the command which does give you the information about the file pointed at by the symlink.

In either case what stat does with symlinks is irrelevant to what happens if one of the directories in the path to the file is a symlink, that will give you the info about the file with the command too.

From the man page:
>      stat() and fstatat() retrieve information about the file pointed
>      to by pathname; the differences for fstatat() are described
>      below.
> 
>      lstat() is identical to stat(), except that if pathname is a
>      symbolic link, then it returns information about the link itself,
>      not the file that the link refers to.
> 
>      fstat() is identical to stat(), except that the file about which
>      information is to be retrieved is specified by the file
>      descriptor fd.

**Comment by frostius** [comment]
I don't think the core issue is "how" to solve the problem so much, but that Microsoft has chosen to ignore the issue.   Refactoring, search/replace, and symbol navigation all cause duplicate instances of files to be opened which then leads to corrupted files.

I wish they would at least provide a supported alternate workaround for sharing code across multiple projects

**Comment by Spudd86** [comment]
Not even just symlinks within the project. Symlinks in the path to one project that doesn't have symlinks anywhere inside the git repo or project directory cause issues too. I'm using both the ctags extension and the clangd extension. The build system produces a compile_commands.json with resolved paths which if there is a symlink ANYWHERE along the absolute path to the file causes this problem, and seems to just make refactoring and jump to symbol stop working entirely sometimes since the path of the file I'm working in doesn't match the path clangd knows.

**Comment by navyxliu** [comment]
> I don't think the core issue is "how" to solve the problem so much, but that Microsoft has chosen to ignore the issue. Refactoring, search/replace, and symbol navigation all cause duplicate instances of files to be opened which then leads to corrupted files.
> 
> I wish they would at least provide a supported alternate workaround for sharing code across multiple projects

Microsoft folks don't own you. they should not work over time and address your problems. 
It's an open-source project and you can create a PR anytime. that's why it's a "how" problem.

**Comment by phiwi** [comment]
Is there any workaround for this? It's very irritating to to have a file that is being debugged open two times and get confused over the additional break points that are being created.

**Comment by phiwi** [comment]
@Lassebq Thank you, but I open my project from within VScode and there I have multiple directories. 

I read somewhere that you can circumvent the issue by setting `pathMappings` within the launch.json for the debugging configuration. Does anyone happen to know how the `localroot`/`remoteroot` should be set? Assuming the symlinked file is in my home directory `~/file` and the debugger opens the resolved path `beegfs/homes/xxx/file`?

**Comment by Lassebq** [comment]
Unfortunately I don't know how to deal with in-workspace symlinks. My main problem was how it deals with symlinks outside of workspace. And due to the way my /home is laid out, every project I open will have duplicate tabs, one opened by debugger and one opened directly from explorer sidebar. This can be worked around by resolving all parent symlinks prior to opening a directory

**Comment by mhillebrand** [comment]
I just solved this issue by removing the symlink directory from my PYTHONPATH environment variable.

**Comment by frostius** [comment]
Someone justs need to create this as a "new" issue showing copilot 
getting confused by the symlink.  That should help pull it in the next 
release.


------ Original Message ------
From "mhillebrand" ***@***.***>
To "microsoft/vscode" ***@***.***>
Cc "Matt Frost" ***@***.***>; "Comment" ***@***.***>
Date 6/9/2025 3:16:29 PM
Subject Re: [microsoft/vscode] Symbolic links to folders can lead to the 
same file opened in two tabs (#100533)

**Comment by wackywendell** [comment]
This issue looks rather similar - or at least, I believe the config option requested would solve this issue (if enabled): https://github.com/microsoft/vscode/issues/130082
