### ISSUE TITLE
runInTerminalRequest shows unnecessary output when kind: integrated

### ISSUE THREAD

**Issue by davidanthoff** [microsoft/vscode#100538]
I'm trying to use the `DebugAdapterInlineImplementation` version of `runInTerminalRequest`. When I use `kind: 'external'` and run a simple script, I get the following output, which is great:

![image](https://user-images.githubusercontent.com/1036561/85083347-53547780-b186-11ea-9099-fe2981873436.png)

But when I run the same script with `kind: integrated`, I get this output:

![image](https://user-images.githubusercontent.com/1036561/85083412-86970680-b186-11ea-9a64-a4d13853ff60.png)

There are at least three problems with this:
1) it shows the Shell splash screen
2) it shows the command line argument and env vars that I passed to `runInTerminalRequest`
3) once my debuggee is finished, it throws the user into a shell, instead of showing something like the `Press any key to continue...` that is shown in the external case.
4) I'm not sure, but presumably it is actually running any shell startup scripts as well? That seems also undesirable, if that is so.

I think for us to be able to use this, we would need the following behavior:

a) ideally it would not start a shell at all, i.e. show no splash screen, don't throw us into a shell after the program is finished debugging, don't run any shell startup scripts (that might have bugs)
b) don't show any output before the output that the program itself creates, i.e. have the output look like in the case of the external choice
c) at the end, ideally show something like `Press any key to close this terminal...`, and then kill the terminal once a user has pressed that key.

**Comment by davidanthoff** [comment]
I just noticed another problem: if I run something with F5 once, and the debugged program is finished, I end up in a shell. If I then press F5 again, it will reuse that shell, and apparently just copy-paste the new start-command into that shell.

So if a user for example ended up typing some stuff in the shell but didn't finish it, then starting the debugger won't work, because the user might be in a situation like this:

![image](https://user-images.githubusercontent.com/1036561/85085455-c52fbf80-b18c-11ea-831b-a7184c3f9a21.png)

**Comment by weinand** [comment]
@davidanthoff If you don't like the way `runInTerminalRequest` works, just don't use it.
Instead you can just spawn your debugger or debuggee as a sub process yourself from the debug adapter.

Some debug extensions support 3 console options: "integratedTerminal", "externalTerminal", and "debugConsole". The first two are covered by the `runInTerminalRequest` which allow the debug adapter to call back into VS Code in order to launch the debugger or debuggee there. 

The third option "debugConsole" needs to be implemented in the debug adapter because the debugger or debuggee must be spawned as a sub process. In this case the debug adapter is responsible for receiving stdout and stderr from the sub process and converts that into DAP Output events which VS Code will show in the debug console.

**Comment by davidanthoff** [comment]
> Instead you can just spawn your debugger or debuggee as a sub process yourself from the debug adapter.

That is what we are currently doing.

> If you don't like the way `runInTerminalRequest` works, just don't use it.

I was hoping we could move towards using it, it would simplify our code base in some really nice ways.

So this is certainly not an urgent ask, but I am still wondering whether my suggestions wouldn't be better in general? It would essentially align the user experience between the `integratedTerminal` and `externalTerminal` option, so that the only difference between those two is whether an external terminal window or the integrated one is being used, but not all of these other output differences.

And it showing the shell startup screen good for any scenario? Same with showing the pasted command line that gets executed, isn't that more of a distraction for any scenario?

**Comment by weinand** [comment]
@davidanthoff thanks for your suggestions.

Here are some comments that try to explain our reasoning why we are not planning to change the current behavior:

Initially there was only the "debug console" which is not a terminal and does not support to provide keyboard input for a running program.

For that reason we added the "external terminal". Since this is a real terminal a program can read keyboard input and send ANSI control characters for "fancy" ASCII output...
Since we can only pass a single command line to the external terminal, we cannot reuse it for another session. That's the reason why it shows the "Press any key to continue..." when done.
Users did not like the "external terminal" behavior because they ended up with lots of external terminal windows hanging around... 

When VS Code added an "Integrated Terminal", we started to use this to overcome the shortcomings of the "external terminal" by being able to simulate keyboard input. We try to reuse a terminal for new debug sessions as long as there is no command already running in the terminal.

Since "debug" is just a client of the Integrated Terminal, we use it in a fair and transparent way:
-  we use the shell that the user has configured for the integrated terminal without modifying any of the options she is using. If this shell has a "shell startup screen", then the Integrated Terminal will show this on startup. The "runInTerminal" request runs later and has no access to the "shell startup screen" output. And because the Integrated Terminal is used for multiple sessions the "shell startup screen" is only shown once.
- We do not manipulate the command line received from the debug adapter via the  "runInTerminal" request in any other way than escaping arguments for the specific shell a user has configured. If the shell echoes the command line, then that's what the user will see.

And remember: typically a user configures a launch config to use the Integrated Terminal for the reason to be in full control and see all the details of a command.
If he doesn't care, then she will stick to the debug console which can suppress everything to avoid distracting the user.

**Comment by davidanthoff** [comment]
Got it!

So essentially you are using the shell in the integrated terminal as the process that runs in the integrated terminal, and then you send a "command" (really via copy-paste) to that process to launch a debugee as a child process. The shell outlives any one debug session, so you can reuse that terminal.

I guess one option would be to replace the shell process with some javascript file that runs in a node process as the "main" process that runs in the terminal. If you then have a communication channel between the node process there and VS Code, then VS Code could send the command to launch a debuggee via that communication channel, rather than copy paste. This "debug host" could in pseudo code literally just look like:
```
while true {
  dbg_cmd = getNextDebuggee(...) # Just reads a path from the communication channel
  startAsChildProcess(dbg_cmd)
  console.log('Finished debugging')
}
```
This would also enable the terminal to run multiple consecutive debug sessions, but would have a number of benefits: 1) whenever the debug terminal is idle, one is guaranteed that one can launch a new debug session in it, i.e. it doesn't depend on the user not having entered some code in the shell manually, 2) there is full control over the output, i.e. not splash screens, 3) no dropping into the shell after a given session.

**Comment by weinand** [comment]
@davidanthoff your "pseudo code" is basically what you should do in your debug adapter.

Having this code in the core of VS Code has no real advantages but at least two big drawbacks:

- in remote setups the debug extension (and its contained debug adapter) runs remotely and the to be launched debuggee needs to run remotely too. If your "pseudo code" would run inside VS Code, it would **not** run remotely and the debuggee would start locally (which is wrong).  When using the "integrated terminal" or the "external terminal" VS Code can easily handle this remote case by using "remote shells"/"remote terminals" that run remotely. But running your "pseudo code" in the correct locations would require additional infrastructure similar to remote shells. We see no value in building this infrastructure because the alternative - spawning the debuggee locally in the debug adapter - already exists and is trivial to do. 
- when running in the "debug console" the debug adapter is expected to collect any program output from the debuggee's output streams and send this via DAP "Output" events to VS Code. While collecting this output the debug adapter can process the data and add additional information or create inspectable object structures. If the debuggee is launched in VS Code by your pseudo code, it would be much more complex to get the data from the output streams back to the debug adapter for processing. 

So I recommend that you just spawn your debuggee in your debug adapter and hook up its output stream to handlers that generate output events.

By using this approach your 3 issues become non issues too:
1) does not exist because every debug sessions can have its own debug console (or can merge output into a shared debug console) and there is no danger that the user has entered some code manually.
2) you have "real" full control of the output because it passes through your code and there is no splash screen because no shell is involved.
3) there is no dropping into a shell after a given session because there is no shell.

**Comment by int19h** [comment]
There are benefits to using a terminal even in scenarios where it's undesirable for it to remain hanging around after, or when the shell isn't even needed at all. In particular, the terminal provides keyboard input that gets wired to debuggee's stdin. There's no way for a debug adapter to do that, if it spawns the process by itself and does stdio redirection - at least not in a way that integrates into VSCode UI like terminals do.

It sounds like this could be done by adding a flag to `RunInTerminalRequest` that'd it treat `args` as the shell for that particular terminal (i.e. uses it in lieu of `terminal.integrated.shell.*`), and skip the whole `sendText()` part entirely. Or maybe allow specifying `shell` and `shellArgs` in the request, and omitting `args`. This would effectively give adapters a way to hook into terminals directly, giving them all the benefits of a true pty, but without having to deal with the shell, and with full control over the lifetime of the terminal (since VSCode already closes terminals if the underlying shell exits).

**Comment by connor4312** [comment]
Fixed in https://github.com/microsoft/vscode/pull/206376
