### ISSUE TITLE
Improving stopped indication ("breakpoint hit") for Web UI

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#100757]
TBD

**Comment by bpasero** [comment]
From: https://github.com/microsoft/vscode/issues/99223

Web: investigate to use web notifications to indicate breakpoint hit

**Comment by isidorn** [comment]
Makes sense, let me assign to October to experiment with web notifications.

**Comment by isidorn** [comment]
Did not have time for this, moving to November to experiment in debt week.

**Comment by isidorn** [comment]
@bpasero do we maybe already use web notifications for something? I think not, but wanted to double check?
Also if we start using them, should I introduce a web notification service, or should this be part of the current `notificationService` just a new method?

**Comment by bpasero** [comment]
@isidorn we don't use it currently and I don't think we should do this through a service because I feel web notifications should be the absolute exception and not the rule. Maybe do a local fix in your area to begin with.

One downside is that I think a browser will ask you for permissions to show notifications. Would be great is only appears when you debug and need it, not before.

**Comment by isidorn** [comment]
@bpasero makes sense. I looked into the [showNotifications API](https://developers.google.com/web/fundamentals/push-notifications) and I need a `serviceWorker` to call the `showNotifications` on it.
In our code base I only see that we register a service worker [here](https://github.com/microsoft/vscode/blob/f0580d497eb1917bd896647fe1f48161b7d5c5d7/src/vs/workbench/contrib/webview/browser/pre/host.js#L56). Is there some other common service worker which I could use or should I register a new one just for my use case?

p.s I tried out some sites and they ask you for permission as soon as you open the site. Though hopefully I could register the service worker lazily and avoid this...

**Comment by isidorn** [comment]
After discussions with @bpasero we came to the conclussion that a service worker is not something we can register and control in our web experience. Since the web notifications are not possible without a service worker, and web notifications alone do not justify an introduction of a service worker I am moving this to the Backlog.

**Comment by isidorn** [comment]
No action planned here, and I do not think there is something actionable to be done.
Thus closing
