### ISSUE TITLE
CMD+D and multicursor selection

### ISSUE THREAD

**Issue by normalser** [Microsoft/vscode#10074]
- VSCode Version: 1.4.0-insiders
- OS Version: OSX

Steps to Reproduce:
1. Create file with:

```
abc def
abc def
abc def
```
1. Put your cursor at `1,1` location
2. Hit `CMD+D` 3 times to select `abc`s
   ![image](https://cloud.githubusercontent.com/assets/1723815/17364000/ac28b700-594b-11e6-9574-ff73cc70a6ca.png)
3. Hit `right` 3 times to get into middle of `def`
4. Hit `CMD+D`
5. Problem: - It will select first def only - it should select all of them

![image](https://cloud.githubusercontent.com/assets/1723815/17364007/b28132d0-594b-11e6-83c8-575855dea351.png)

For comparison result of the same in Atom/Sublime:
![image](https://cloud.githubusercontent.com/assets/1723815/17364041/d6595d9a-594b-11e6-8539-01911ea8a357.png)

**Comment by duydao** [comment]
@alexandrudima I'm really interested to getting this fixed. Still switching to sublime text for some tasks because of this.

Can you give me a hint in which module I could start looking for this bug?

**Comment by duydao** [comment]
@alexandrudima The problematic line is https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/find/common/findController.ts#L541. This line takes the latest cursor as start position when searching for matches.

Shouldn't it ignore _empty_ selections and use the end of the last _non-empty_ selection as last position when searching for matchings?

btw: when having multiple selections, Sublime Text will expand _empty_ selections to select the word instead of looking for the next selection.

**Comment by npx** [comment]
_(Just a clarification)_

In the case of:
```
abc f|oo        abc [f|oo]
abc b|ar    ->  abc [b|ar]
abc p|izza      abc [p|izza]
```
hitting CMD+D should select the full word the cursor is currently over, not just the same match.

**Comment by duydao** [comment]
@npx actually, it's even easier to create a plugin that replaces the cmd/ctrl+d command. In fact, I've just created one that works as I would've expected. If you're interested, you can find it here:

https://github.com/duydao/vscode-expand-selections

**Comment by Kerollmops** [comment]
Really interested in an option like `expandSelectionToWord` too ! 😄

**Comment by alexandrudima** [comment]
`cmd+d` (or `ctrl+d` on Windows) will now behave as described:

```
abc piz|za
abc ho|use
abc b|ar
--------------
abc [pizza]
abc [house]
abc [bar]
```
