### ISSUE TITLE
Support dark window chrome when dark theme is used

### ISSUE THREAD

**Issue by ganySA** [Microsoft/vscode#10070]
- VSCode Version:
  1.3.1
- OS Version:
  Windows 10
  Steps to Reproduce:

The toolbars and application menu are currently white/gray and many users have a dark theme for the code area and the contrast is quite :/ 

Any way to put in a option to make the toolbar and menu at the top of the screen to be black like in visual studio dark theme...

![image](https://cloud.githubusercontent.com/assets/3189206/17360988/7067cc60-596e-11e6-91b1-11749545cf2c.png)

**Comment by coreh** [comment]
Would also be really nice to have that for OS X:

![](https://cloudup.com/c2C9L4l8ZxI+)

**Comment by bpasero** [comment]
I do not think Electron allows us to change the color of the area.

**Comment by coreh** [comment]
It's possible from OS X 10.10 onwards, via the `{ titleBarStyle: 'hidden' }` option:

https://github.com/electron/electron/blob/master/docs/api/frameless-window.md#alternatives-on-macos

Hyperterm (which is also electron-based) uses this option to great effect:

![](https://cloudup.com/cMzx4JzKTI9+)

Controls are rendered by macOS, so the titlebar background just needs to be rendered using HTML content. The simplest way of doing this would be setting a `margin-top` style on the document body and a background color. 

Changing it so that the tab bar blends more "Seamlessly" with the title bar is also possible, but would probably require more dramatic changes on VSCode's interface:

![](https://cloudup.com/cuVRvDlaDnr+)

**Comment by patrys** [comment]
Here's a related PR that was merged into Atom: https://github.com/atom/atom/pull/11790

**Comment by Emeryao** [comment]
+1 
Please think about it 
REALLY need this feature

**Comment by ringoz** [comment]
+1
just do it!

**Comment by mikaturk** [comment]
+1
Would really like to see this feature!

**Comment by armaandh** [comment]
+1 would really like to see this happen

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/16363

**Comment by 1st** [comment]
As @patrys mentioned, the Atom has this black style title bar already. Can you please do the same change into the VS Code?

**Comment by jlewin** [comment]
GitHub Desktop also makes use of a dark titlebar:
![image](https://user-images.githubusercontent.com/175113/33972284-fc173692-e031-11e7-94d2-21af373831f7.png)
