### ISSUE TITLE
Prettier types on the TS evaluation tooltip.

### ISSUE THREAD

**Issue by omerman** [microsoft/vscode#100827]
Regarding https://github.com/microsoft/TypeScript/issues/39160,

I would like to suggest that object types are pre evaluated using `Id<ObjType>` 
Only when displaying the tooltip that shows the type description.

like such ->
```
type Id<T> = {} & {
  [P in keyof T]: T[P]
}

type Simpleified = Id<P>
```

**Comment by IllusionMH** [comment]
VSCode doesn't "evaluate" any types on it's side, it just displays highlighted `displayString` of`quickinfo` response from TypeScript (tsserver)
Example:
```json
{"seq":0,"type":"response","command":"quickinfo","request_seq":46,"success":true,"body":{"kind":"const","kindModifiers":"export","start":{...},"end":{...},"displayString":"const getFirstPart: () => string","documentation":"Returns first part of uri","tags":[...]}}
```

You need to wrap your types in `Id` to have expected `displayString`. Otherwise you need to find similar requests in TypeScript repo (there were request for behavior of `Id<T>` type and for displaying aliases as is without `Pick<Omit<...>...>`) and provide your feedback there.

**Comment by omerman** [comment]
OK will do, 
Thanks!
