### ISSUE TITLE
Possible problem with multiple  `tsconfig.json` files in subdirectories

### ISSUE THREAD

**Issue by a8775** [Microsoft/vscode#10084]
- VSCode Version: 1.4.0-insider
- OS Version: Windows 10

Please see the demonstration project on git: https://github.com/a8775/vscode-tsconfig

## Setup 
Tested with the following versions:
- nodejs 6.2.0
- typescript 1.8.9
- typings 1.3.2

Steps to reproduce the problem:
1. Clone the project
2. In project directory execute commands:
    - `npm install` - to download  dependencies
    - `typings install` - to download required typings files

## TypeScript
In working directory run the command: `tsc -p .`

Should compile correctly.

## vscode

Select the right file in a editor window and compile the project:
1. Select the the file: `./MySubProject/mySubProjectFile.ts` 
2. Compile the project: `Ctrl-Shift-B`

The project should be compiled without errors. 

Now press space in any *syntactically correct* place. You get compilation errors.

**Comment by dbaeumer** [comment]
I was able to reproduce this.

**Comment by dbaeumer** [comment]
The problem is that the code inside the mySubProject folder doesn't see the code in the typings folder. The compiler only looks from the tsconfig.json file downwards. If you want to keep your layout you can do the following: add a file typings.d.ts with the following content to the MySubProject folder
```
/// <reference path="../typings/index.d.ts" />
```

This makes it work correctly.

**Comment by a8775** [comment]
Thank you @dbaeumer for that hint. 

I have solved the problem by removing/renaming the second `tsconfig.json` in MySubProject.

My main point was that the VSCode is not consistent and it looks like a bug:
1. Once I compile the project and VSCode UI shows *zero* errors, 
2. After that I touch any key eg. space suddenly the errors appears.

What's more, logically when I compile the top project with `tsc` it's not showing any error and so the `VSCode` shouldn't as well.

I guess the problem is in the `VSCode` that it's using both of the `tsconfig.json` contrary to the `tsc -p .` that use only one found in the path passed as a parameter. I believe `VSCode` should do exactly the same.

The more I think about the problem, I am inclined to the opinion that it is a *BUG* in `VSCode`.

**Comment by dbaeumer** [comment]
I do understand that the project has two tsconfig.json files and the problem is a misalignment between the tsc and the tsserver in terms of the project team. I will move the issue to the TS to comment on. For the TS team:

- when running tsc -p . it compiles the files in MySubProject using the tsconfig.json from root.
- when open a file in the tsserver from MySubProject the tsconfig.json from the MySubProject folde is used.

This results in different project scopes.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#10283

**Comment by a8775** [comment]
@dbaeumer sorry I was raising the problem again, I would like the tool I use every day was perfect for everyone :)

I appreciate the work of all team, thanks a lot!
