### ISSUE TITLE
Extensions: Install Extension is slow

### ISSUE THREAD

**Issue by warpdesign** [Microsoft/vscode#1008]
When listing available extensions (typing `ctrl+shift+p`and then `ìnst` and hit `enter`) it takes at least **5 seconds** to display anything.

Meanwhile, there's no user feedback other than an indeterminate loader.

What about having a faster feedback with for example cached results of plugins list while newest plugins list is being retrieved ?

It seems that the more extension are available, the longer it will take to display anything, so it will likely get worse.

**Comment by egamma** [comment]
The query has been improved and it will be significantly faster in the December update.

**Comment by warpdesign** [comment]
@egamma Cool!

**Comment by dbaeumer** [comment]
@joaomoreno I tested this several times and it takes around 8 seconds to show the list. Progress is shown as well. 

Since the issue doesn't state what the expected timing is I will leave it up to you to decide whether there is a regression here or not.

**Comment by joaomoreno** [comment]
:+1:

**Comment by alphashuro** [comment]
What happened to the cache issue? I'm still spending much time waiting for the extension list to show...

**Comment by joaomoreno** [comment]
What version are you on? We've had an extension since March: #2621.

**Comment by alphashuro** [comment]
0.10.11

**Comment by joaomoreno** [comment]
How fast can you GET this request? http://vscode.blob.core.windows.net/gallery/index

**Comment by alphashuro** [comment]
I get it quite fast now because my internet speed is back to normal, but I was asking about the cache because sometimes sometimes its slow and it becomes a pain when I want to quickly look for a package and/or install it. When I used sublime package manager it always downloaded a list of packages the first time I do a search. On subsequent searches it opened instantly and I could continue with my work regardless of internet speed.

**Comment by dbaeumer** [comment]
@joaomoreno giving back to you to follow up on the conversation.

**Comment by joaomoreno** [comment]
I see. We don't cache this locally in your machine, though. We rely on a working Internet connection, since most likely you'd like to install an extension any way, which needs it.

We just implemented a better search experience that no longer relies on downloading the entire list of extensions but runs queries, resulting in a much lighter experience. #4849

**Comment by alphashuro** [comment]
Why not cache the results initially though? I don't mean to access them without an internet connection, but when on a slow internet connection it would be great if you could quickly find an extension and mark it for installation then immediately continue with your work...

**Comment by joaomoreno** [comment]
Because caching introduces other problems such as: *I just published my extension, why is it not available for installation?* or *I see this extension in the list but I can't install it* (when a user deletes an extension).

#4839 is a good solution for a slow internet connection as well, since we won't download the information of all extensions but rather query for them.
