### ISSUE TITLE
Debug python have issue

### ISSUE THREAD

**Issue by KeXu444** [microsoft/vscode#100805]
- VSCode Version: 1.47.0-insider
- OS Version: windows 10

Steps to Reproduce:
1. install package source code with pip install -e
2. start a python file outside of package, and reference the code inside that package
3. use vscode/python plugin to debug.
4. when step into code inside package, vscode does not highlight current line, instead it shows regular edit icon, debug can still work line by line, but without high light, I cannot hover over parameter and see values, has to manually add them to watch, pretty annoying.

Does this issue occur when all extensions are disabled?: N/A

**Comment by weinand** [comment]
Please file against Python extension

**Comment by int19h** [comment]
@weinand
I'm not sure what we can even do here. The extension isn't responsible for highlighting the current active line in a debug session - the debug adapter simply reports the call stack with the appropriate line numbers. This is still the case - indeed, it's clear that those line numbers are received correctly, since VSCode does show the editor cursor on the right line when breakpoint hits. It's just that the line isn't highlighted.

Furthermore, [according to another user](https://github.com/microsoft/vscode-python/issues/12531#issuecomment-649185392), this issue no longer reproduces if they downgrade VSCode itself. 

Did something change in this area recently that might have broken this? One thing that might be contributing to it showing up for Python, but not for other languages, is that we never report `endLine` or `endColumn`, and `column` is always 1 (because Python tracebacks only have line numbers). Previously, this always highlighted the entire line, but it looks like now it doesn't always do that consistently?

**Comment by KeXu444** [comment]
![DbjFPIYK0M](https://user-images.githubusercontent.com/40614413/85666157-f880bb80-b670-11ea-9cec-ce114cb85092.gif)

**Comment by isidorn** [comment]
Works for me with latest insiders and the following python program
`print(7 + 7)`

Please provide exact reproducable steps. I do not know python, thus I have no clue how to reference a file in a python package

![Screenshot 2020-06-25 at 11 56 09](https://user-images.githubusercontent.com/1926584/85698372-e176b380-b6da-11ea-9b21-d959dd2f91e5.png)

**Comment by paulzhn** [comment]
> Works for me with latest insiders and the following python program
> `print(7 + 7)`
> 
> Please provide exact reproducable steps. I do not know python, thus I have no clue how to reference a file in a python package
> 
> ![Screenshot 2020-06-25 at 11 56 09](https://user-images.githubusercontent.com/1926584/85698372-e176b380-b6da-11ea-9b21-d959dd2f91e5.png)

This problem performs strange. I have installed the same version of vscode both on my virtual OS and the physical OS, with the same version of python plugin (all in the latest version); however, this problem only performs on my virtual OS. I had tried to change python version, reinstall the vscode and python plugin, disable and remove other plugins, and the result was clear: the problem still exists. Only downgrading the version of vscode could solve this problem, and after its auto-update to the latest, the problem happens again.

**Comment by paulzhn** [comment]
Version: 1.46.1 (user setup)
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:13:20.174Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by KeXu444** [comment]
Can you try clone this repo?
https://github.com/fairlearn/fairlearn
and try debug this file?
examples/notebooks/plot_binary_classification_COMPAS.py 
set break point before or on line 21 so that you don't need to install the dependencies.
I have 2 computer on my desktop it is fine, but laptop have issue, despite I reset whole windows and start from scratch.

**Comment by paulzhn** [comment]
> Can you try clone this repo?
> https://github.com/fairlearn/fairlearn
> and try debug this file?
> examples/notebooks/plot_binary_classification_COMPAS.py
> set break point before or on line 21 so that you don't need to install the dependencies.
> I have 2 computer on my desktop it is fine, but laptop have issue, despite I reset whole windows and start from scratch.

I find that not only the python debugger have this issue, but also cpp debugger have :sweat: I think maybe I should open a new issue

**Comment by isidorn** [comment]
I can not repro. Also you say that on 2 computers it is fine, but on laptop you have the issue.
@int19h one of your users is using stable another insiders, so I do no think the two issues are related, they are comparing different products.

**Comment by KeXu444** [comment]
Do you think a teams meeting for me to show you can help on this issue?

**Comment by nguyen14ck** [comment]
This also happened to me.
