### ISSUE TITLE
vscode API - window test failing

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#100828]
```
      
      +      "_formatted": "fake-fs:/sarrxnioeu"
      +      "_fsPath": "/sarrxnioeu"
             "authority": ""
             "fragment": ""
      -      "path": "/tybdxihb"
      +      "path": "/sarrxnioeu"
             "query": ""
             "scheme": "fake-fs"
           }
           "_versionId": 1
           }
         }
         "_options": {
           "_cursorStyle": 1
      -    "_id": "vs.editor.ICodeEditor:10,$model6"
      +    "_id": "vs.editor.ICodeEditor:9,$model5"
           "_indentSize": 4
           "_insertSpaces": true
           "_lineNumbers": 1
           "_logService": {
               "_line": 0
             }
           }
         ]
      -  "_viewColumn": 2
      +  "_viewColumn": 1
         "_visibleRanges": [
           {
             "_end": {
               "_character": 0
               "_line": 0
             }
           }
         ]
      -  "id": "vs.editor.ICodeEditor:10,$model6"
      +  "id": "vs.editor.ICodeEditor:9,$model5"
       }
      
      at Context.<anonymous> (/Users/runner/runners/2.170.1/work/1/s/extensions/vscode-api-tests/src/singlefolder-tests/window.test.ts:158:11)
      at processTicksAndRejections (internal/process/task_queues.js:89:5)
```

https://monacotools.visualstudio.com/Monaco/_build/results?buildId=79526&view=logs&j=d71c4c56-574b-5ba9-9268-feb3539ccbff&t=d3ff3f50-fff6-59fa-b73b-20c4bfb3021b

**Comment by bpasero** [comment]
Funky how this guy keeps coming back. Previous issues: https://github.com/microsoft/vscode/issues/90470 and https://github.com/microsoft/vscode/issues/87330

I think last time we identified an issue with focus tracking where suddenly both editors had focus due to missing delivery of focus/blur events.

Given this test seems to rely on flaky/buggy DOM events in build environments, maybe we should remove it for god.

**Comment by bpasero** [comment]
Some thoughts:
* this could be related to Electron 8 update, but speculation
* it looks like we only ran a subset of integration tests due to a bad push from @chrmarti (fixed with https://github.com/microsoft/vscode/commit/3d93daf7cafda5f4b2bdd5a0a494aac37a1c6ff7)

I would like to enable this test again over the next days to see if it is consistently occuring again or not and then make a call.

Thougths?

**Comment by jrieken** [comment]
Yeah, didn't see your message but yeah it's re-enabled and will fail with more better logging.

**Comment by jrieken** [comment]
🤞 

The challenge with this test is that it relies on focus. That means any popup or interaction will likely fail it. This should happen less likely on build machines but it's not impossible. For this particular test I would like it be skipped on the build machines or not fail the build but I still wanna run it locally

**Comment by bpasero** [comment]
Yeah there is likely a build environment variable you could check for that we set during CI.

**Comment by bpasero** [comment]
Looks like you could use `system.debug` according to https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#systemdebug.

**Comment by alexdima** [comment]
@jrieken Please let me know if there is something I can help with from the editor side...

**Comment by jrieken** [comment]
Moving this out for one milestone. Test has been stable in the last week...

**Comment by jrieken** [comment]
Disabled on build machines, still running them locally
