### ISSUE TITLE
not able to install alot od extention

### ISSUE THREAD

**Issue by AbdelrahmanHamdy1996** [microsoft/vscode#100985]
Issue Type: <b>Bug</b>

Unable to open 'Extension: JSON to CSV': An unknown error occurred. Please consult the log for more details..Unable to open 'Extension: JSON to CSV': An unknown error occurred. Please consult the log for more details..Unable to open 'Extension: JSON to CSV': An unknown error occurred. Please consult the log for more details..

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:08.304Z)
OS version: Linux x64 5.4.0-37-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 3000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|7.68GB (0.79GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
arepl|alm|1.0.24
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.5
vscode-html-css|ecm|0.2.3
prettier-vscode|esb|5.1.0
code-runner|for|0.10.0
beautify|Hoo|1.5.0
latex-workshop|Jam|8.10.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
anaconda-extension-pack|ms-|1.0.1
python|ms-|2020.6.89148
remote-containers|ms-|0.122.1
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.4
vscode-remote-extensionpack|ms-|0.20.0
odoo-snippets|mst|1.0.1
autodocstring|njp|0.5.3
vetur|oct|0.24.0
indent-rainbow|ode|7.4.0
vscode-yaml|red|0.8.0
code-spell-checker|str|1.9.0
vscodeintellicode|Vis|1.2.8
vscode-icons|vsc|10.1.1
markdown-all-in-one|yzh|3.1.0
vscode-proto3|zxh|0.4.2

</details>
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by sandy081** [comment]
Please follow these steps

- Help -> Toggle Developer Tools -> Network
- Then check for any network failed requests while browsing and installing the extensions if found all requests fails then its probably a proxy or DNS issue at your end.
- To confirm its a DNS issue check if you can access this page https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default, if you cannot please try configuring your DNS like pointing to 1.1.1.1 as suggested here? https://1.1.1.1/dns/. Otherwise please contact your network administrator.
- If it is not a network issue, please share the logs from the following locations
    - Help -> Toggle Developer Tools -> Console
    - View -> Command Pallette... -> Toggle Shared Process -> Console
    - View -> Open View… -> Log (Shared)
    - View -> Open View… -> Log (Window)
