### ISSUE TITLE
The unpin shortcut does not work on tab of Release Notes

### ISSUE THREAD

**Issue by F8ER** [microsoft/vscode#100953]
- VSCode Version: 1.46.1
- OS Version: Win10 x64 1909 18363.900

Steps to Reproduce:

1. Update VS Code
2. Stay on Release Notes which opens after the update or open using command prompt etc.
3. Pin tab
4. Try to unpin using the shortcut `Ctrl+K Shift+Enter`

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
Since it works using the context menu I suspect that the webview is eating the keybinding.

**Comment by bpasero** [comment]
Yes, verified via debugging that seems to be the case, my command is never triggered.

**Comment by mjbvz** [comment]
Looks like we end up firing `pin` instead of `unpin` here. It seems the resolved context is wrong, specifically the `editorSticky` context key is not set when focused on a webview

**Comment by mjbvz** [comment]
The issue seems to be that webviews are not part of the normal editor dom. Instead they exist as top level nodes in the workbench. We do this to prevent the webview from being re-parented when the editor layout changes (which would cause it to be destroyed.)

However the sticky context keys are set on the normal editor dom nodes: https://github.com/microsoft/vscode/blob/1689304b527a97e79317d5094b35eef00b433ea0/src/vs/workbench/browser/parts/editor/editorGroupView.ts#L223

Not sure about how to fix this. One thought would be to let a node tell the context key service that it contains another node, even if that second node is not a child of the first in the dom

**Comment by mjbvz** [comment]
In 3338ff4e18cd715e6329b5d8fa7bf5a8027fb9f4 (which fixes #100536) I added the concept of parent flow to. This allows a dom node to tell VS code that it's parent is not the normal dom parent, but actually another node somewhere in the dom.

This seems like a potential fix for this issue. I'll take a look into the context service to see if I can also make it observe parent flow to

**Comment by F8ER** [comment]
I very much appreciate you here, dear @mjbvz
