### ISSUE TITLE
Completion provider is invoked on more than just triggerCharacters

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#10098]
- VSCode Version: 1.3.1
- OS Version: Windows 10

Steps to Reproduce:

1. Register a completion handler with a trigger character of `.` like `context.subscriptions.push(vscode.languages.registerCompletionItemProvider(DART_MODE, new DartCompletionItemProvider(analyzer), "."));`
2. Breakpoint on when the `provideCompletionItems` method

It seems to be firing all the time on loads of characters. Eg. I had a type `//a` into a blank Dart file (never touching full stop) and it triggered. This might be related to #719 but I'm not sure (since there is a `triggerCharacter` arg here that it's not being restricted to).

**Comment by jrieken** [comment]
I believe this is because of `24x7` intellisense. @DanTup There is setting `"editor.quickSuggestions": true|false` (default is `true`) which means always provide intellisense when a _word_ is being typed. The trigger characters are yet another source of triggers for intellisense (also the explicit `ctrl+space` action). In short, the default configuration of VS Code is to be very eager with completions.

**Comment by DanTup** [comment]
Gotcha; thanks for clarifying! It might be worth adding a note about this to the docs for registerCompletionItemProvider/triggerCharacter to avoid confusing?
