### ISSUE TITLE
File saving shortcuts bug

### ISSUE THREAD

**Issue by emilime** [microsoft/vscode#101097]
Hello,

in the last 2 releases of VSCode Insiders the file saving shortcuts have been altered and are no longer consistent with the shortcuts indicated in settings:

Save --> ⌘S 
Save As... --> ⇧⌘S 
Save All --> ⌥⌘S 

Currently on VsCodeInsiders:

Save --> no shortcuts!
Save As... --> ⌥⌘S 
Save All --> ⌘S 

I find this modification very inconvenient, in particular having removed the shortcut to save a single file.

**Comment by bpasero** [comment]
We did not change any keybindings, you either installed an extension that took them or manually changed them:

https://github.com/microsoft/vscode/blob/8e1fe1d8999845ef8f88a6131a4a95b0f67fdd44/src/vs/workbench/contrib/files/browser/fileCommands.ts#L419

**Comment by emilime** [comment]
I haven't manually edited them, nor do I think I've installed any new extensions recently that may have altered the shortcuts.
I see the shortcuts changed also in the menu, look:

<img width="281" alt="Schermata 2020-06-26 alle 12 09 27" src="https://user-images.githubusercontent.com/47943/85846323-ea808700-b7a5-11ea-960a-8c8b212e69da.png">

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by emilime** [comment]
I'm on this version:

Versione: 1.47.0-insider
Commit: 6c235c723cb2d8defb840f732eac620f54aa8b9d
Data: 2020-06-26T05:33:20.679Z (4 ore fa) 

installed 4 hours ago.

I see also a bit of confusion in Preferences: Keyboard Shortcuts:

<img width="1262" alt="Schermata 2020-06-26 alle 12 13 36" src="https://user-images.githubusercontent.com/47943/85846997-02a4d600-b7a7-11ea-97ab-2af70146c6a9.png">

**Comment by bpasero** [comment]
@emilime that is strange, for me it shows:

![image](https://user-images.githubusercontent.com/900690/85872668-55df4e80-b7d0-11ea-8629-31ab1cbda3b0.png)

I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by emilime** [comment]
Hello @bpasero,
you were right, disabling all the extensions shortcuts and menus return to normal.
Now investigate which extension is causing problems.
Thanks for the help
