### ISSUE TITLE
Keyboard input in editor is racy (keypresses aren't applied sequentially)

### ISSUE THREAD

**Issue by elieux** [microsoft/vscode#101011]
I couldn't find any ticket describing this issue.

- VSCode Version: 1.46.0
- OS Version: Windows 10.0.18363

### Steps to Reproduce:

1. Add some load to your system and/or to Code.
2. Do stuff in editor that includes writing and navigation.

### Expected result

All keyboard input is processed and applied sequentially.

### Actual result

Writing and navigation are interleaved.

## Recording

![vscode-racy-keys](https://user-images.githubusercontent.com/1399406/85680736-dcaa0380-b6ca-11ea-818f-a68095e181f3.gif)

I have around 6 Code windows open and being actively used for 3+ days with a bunch of extensions. I pressed exactly this:

1. `hello(): string {}`
2. `<left arrow> <enter>`
3. `<shift+tab> <up arrow> <end> <enter>`
5. `const hello = "hello";`
6. `<ctrl+left arrow> <ctrl+left arrow> <ctrl+left arrow> <ctrl+left arrow> <ctrl+left arrow> <ctrl+left arrow>`
7. `:string`
8. `<end> <enter>`

First issue is in step 2, where if Code keeps up I should end up with a properly aligned closing bracket and the cursor on an empty line in the function body. Instead the bracket is misaligned and the cursor is position after it. Step 3 is me correcting this.

Second issue is in step 8, where if Code keeps up I should end up with a properly finished word, but part of it ends up on a different position.

The trigger here seems to be computing the suggestion list when writing `string`.

Generally speaking, all effects of user input (keyboard, mouse etc.) should be independent of current processing power and lags. I guess this isn't super easy to do while retaining responsiveness and some of it might fall in the design trade-offs category, but I believe that in the limited scope of keyboard input inside one editor, as presented here, this is an obvious bug.

Does this issue occur when all extensions are disabled?: Didn't test, but I don't see how an extension could cause this.

**Comment by alexdima** [comment]
@elieux Extensions can cause this and have been the root cause of issues like this in the past.

Ways in which extensions can cause this:
* extensions can contribute keybindings and take over built-in keybindings. (e.g. `enter`, `end`, `left arrow`, etc.)
* extensions can override the type command
* extensions can listen to document change events and then create edits "from the side" on the editor

Given my past investigations, I believe this is again caused by extensions. There is a small chance that this is caused by some format on type (which is technically implemented in the core), but that all depends on your settings + installed extensions.

You can attempt to reproduce by launching multiple 100% CPU processes on your machine or writing an extension that blocks the extension host for 5 seconds every 10 seconds, etc.

So my question is, does this reproduce when disabling all extensions?

**Comment by elieux** [comment]
Oh, I didn't realize. I'll have to check then. Thanks.

**Comment by elieux** [comment]
Interestingly, a pure CPU stress test slowed VSCode to just a few letter per second, but everything was still in sequence.

I propose closing this issue until I get back with something better.
