### ISSUE TITLE
Opening a new project should open in a new window.

### ISSUE THREAD

**Issue by nickatrokit** [microsoft/vscode#101063]
- VSCode Version: Version: 1.45.1
- OS Version: MacOS 10.14.2 

Steps to Reproduce:

1. Have any project open
2. Go to open
3. Select some other project and open it
4. Instead of opening a new window with the new project as everyone on Earth wants the current project is replaced.

I can't count how many times this 'bug' has screwed me up. I'm filing this under bug because no one in the history of the world has every gone to open a new project and wanted their current project closed automatically. I have like 5 projects open at once usually. I can't imagine why this behavior would be on purpose. Would someone only want 1 project open at a time? Why would opening something close the thing you're working on? Why would doing something have this undesired side effect? In order to get the behavior you want you need to open a new blank project unnecessarily and then open the project that you want to open. There does not seem to be any technical limitation involved in opening a new project in a new window. Thanks for your help!

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
VS Code doesn't use the term 'project'. Presumably you are opening either a folder or a workspace (a file with a .code-workspace extension).

When I open either of these from the `Open Recent...` submenu, holding `Shift` down when I click on a recent entry will make it open in a new window. The same happens if I hold down `Ctrl` instead (I work on Windows).

Similarly, if I hold down `Ctrl` when I click an entry in the Recent section of the Welcome page, a new window is created.

If you always want a new window, change the `window.openFoldersInNewWindow` setting.

**Comment by nickatrokit** [comment]
@gjsjohnmurray Great so you have to hold down a button or change a buried project setting to make if function how any sane person would expect. That's fantastic /s.

**Comment by gjsjohnmurray** [comment]
No, you can change a setting once and get the behaviour you prefer.

**Comment by nickatrokit** [comment]
@gjsjohnmurray Or I can use a different IDE that can do one of the most basic things without having to change a setting.

**Comment by gjsjohnmurray** [comment]
@nickatrokit indeed you can.
