### ISSUE TITLE
debug-alt codicon in size for action bar

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#101026]
As mentioned in https://github.com/microsoft/vscode/issues/92269#issuecomment-649311774

We need the debug-alt codicon in size to fit in the editor title action bar.
Is it possible to introdcue a new codicon or to fix the current one such that the icon is well aligned with others?

![Screenshot 2020-06-25 at 15 58 33](https://user-images.githubusercontent.com/1926584/85733752-bd2bce80-b6fc-11ea-9113-61ed87f6dd0d.png)

**Comment by misolori** [comment]
So I can work on making the sizes consistent, that's a separate issue. However, making the play icons align would be trickier because when we overlay the bug we have to shift the play button around. Here's a comparison of current vs making it the same position as the previous play:

![image](https://user-images.githubusercontent.com/35271042/85772792-0ca8d500-b6d2-11ea-844a-c51774e2ab45.png)

Making the bug smaller would then make it harder to see at the 16px size

Here's the closest I could get to making them the same:

![image](https://user-images.githubusercontent.com/35271042/85774465-b9378680-b6d3-11ea-9c1c-f2b1491bcde8.png)

![image](https://user-images.githubusercontent.com/35271042/85774499-c2c0ee80-b6d3-11ea-9a0b-a23c9ec0255d.png)

**Comment by isidorn** [comment]
@misolori thanks for looking into this. I think I would prefer if we just fix the size for now.

The new icon while more aligned has a problem that it looks less like a play button and thus I dislike it a bit.

**Comment by misolori** [comment]
Ok, since this will require some larger changes (I have to re-size all of the activity bar icons and update the icon sizes) I'll push this out to the next milestone since we're nearing the end of the iteration.

**Comment by isidorn** [comment]
@misolori makes sense, thanks a lot!
fyi @weinand

**Comment by weinand** [comment]
What is proposed above (and copied below), looks perfect to me:

<img width="383" alt="2020-07-01_12-25-26" src="https://user-images.githubusercontent.com/1898161/86233635-0022f180-bb96-11ea-9bc4-9279c7f00d91.png">

**Comment by weinand** [comment]
@misolori I just verified how the current icons look in Mock debug and I got the impression that the debug icon (play with bug) is just fine. Only the "play" icon is a little small.

<img width="196" alt="2020-07-01_12-38-24" src="https://user-images.githubusercontent.com/1898161/86235180-509b4e80-bb98-11ea-839e-73865107cbe6.png">

Instead of changing "debug" (and all other icons used in the activity bar), wouldn't it be possible to just make the play icon one pixel larger and move it up one pixel?

**Comment by misolori** [comment]
The problem is that the activity icons (~10) are the only ones that are bigger while the rest (~310) are at the default size. So this would make the play button bigger and create an off-set when used in other cases. We also have variations of this play icon (run-all, debug-start, play-circle) which would make it more noticeable when placed together.

I still think the proper fix is to address the activity bar icons, which is something I've been wanting to do anyways but never got around to doing it.

**Comment by isidorn** [comment]
@misolori makes sense to fix the activity bar icons then. We can do this next milestone, as shipping with this in June is perfectly fine.

**Comment by misolori** [comment]
After trying a couple of different methods, it turns out that updating the rest of the activity bar icons are quite tricky. So not only are those icons bigger but they are also wider by 1.5px (vs 1px). So I'll need a different way to specify these icons to only be used in the activity bar.

In the meantime, I've introduced a new icon, `debug-alt-small` which should fit into the action bar here:

![image](https://user-images.githubusercontent.com/35271042/86657342-01d92480-bf9d-11ea-8997-e3bf972b2ed4.png)

@weinand let me know if you're able to use the new icon and if it works for you.

**Comment by weinand** [comment]
@misolori the new icon looks great.

The only problem is that it introduces a new name. In this milestone we will announce "debug-alt" (and "debug-alt-small" is not yet available) and in the next milestone we have to change the name to "debug-alt-small".

Would it be possible to ship "debug-alt-small" already in the June milestone?
If yes I will adapt the sample and the doc accordingly.

**Comment by misolori** [comment]
It'll have to come through a candidate pr, let me queue one up.

**Comment by weinand** [comment]
@misolori great, thanks

**Comment by weinand** [comment]
Here is the Mock Debug sample with the new "debug-alt-small" icon:

<img width="770" alt="run-and-debug-actions" src="https://user-images.githubusercontent.com/1898161/86757115-30113f80-c043-11ea-92f9-a7af4124fe19.png">

**Comment by weinand** [comment]
I've already changed the 1.47 release notes to use "debug-alt-small" instead of "debug-alt": https://github.com/microsoft/vscode-docs/commit/3f9a91d4a45af8b678ede593c0dd157f26276ea1

**Comment by misolori** [comment]
This is now merged into the `1.47` branch and will make it in for June's release.

**Comment by weinand** [comment]
I've verified that this works in Insiders.
