### ISSUE TITLE
Diagnostic should support source field

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#1010]
Now that extensions can validate files and produce problems we should extend the Diagnostic literal with a source field. Currently extensions start to mangle the source into the message which will make building proper UI for grouping and filtering hard.

**Comment by egamma** [comment]
Also we should have a simple log API where an extender can post an extension error in the case that no error dialog can be posted or it doesn't make sense to post a dialog.

**Comment by jrieken** [comment]
@dbaeumer The owner is exposed indirectly via the `DiagnosticsCollection#name` [property](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L2269). Since that's the only way from the API to post diagnostics and because having owners on the diagnostic maps very badly to our main thread model. Also what does it mean when you post a diagnostic with owner `foo` to a collection with owner `bar`. Is this something where the protocol and the API are different?

**Comment by jrieken** [comment]
@dbaeumer Or is the `source` property more or less a view model property independent of the owner/name concept we internally use. Just like a secondary label?

**Comment by dbaeumer** [comment]
@jrieken a view model property which we could at the beginning at to the end of the message.
