### ISSUE TITLE
Changes view: harder for me to understand "clean" state for a repo

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#101103]
One thing I am not so happy about the new changes UX is that I often think that the other repos are dirty changes I need to review:

![image](https://user-images.githubusercontent.com/900690/85844366-eacb5300-b7a2-11ea-9a9a-b23b85e00fd0.png)

I wonder if there is anyway to distinguish changes (= files) more from other repos. Of course this is harder for me where file icons are turned off.

//cc @misolori

**Comment by joaomoreno** [comment]
From @gjsjohnmurray:

> I don't like that the new UX no longer displays the `label` parameter passed on the `vscode.scm.createSourceControl(...)` call (e.g. `Git` and `Deltanji`). Perhaps they can be added as hovers on the `Trial2` and `WebTerminal` headers.

👍

**Comment by gjsjohnmurray** [comment]
In #101112 I wrote:
> I like how the new UX no longer uppercases the `SourceControl` and `SourceControlResourceGroup` labels, (e.g. `Trial2` and `WebTerminal`, `Changes` and `#4: Fourth`) but perhaps they could be bolded or get some other visual differentiation from the `SourceControlResourceState` entries (e.g. `README2.txt` and `WebTerminal.Updater.CLS [WEBTERMINAL.0]`)

(examples cited are from screenshots in the other issue that compare 1.46 and 1.47 side by side)

**Comment by misolori** [comment]
Adding the scm label I think would definitely help here:

![image](https://user-images.githubusercontent.com/35271042/86148308-4ea99080-baaf-11ea-98c2-bd906f407685.png)

**Comment by joaomoreno** [comment]
I've added the SCM label.

I can't really hide the twistie if the repositories have no changes as it makes it even worse:

![image](https://user-images.githubusercontent.com/22350/86251213-de376800-bbb1-11ea-8f02-4a04cd7aebc0.png)

**Comment by joaomoreno** [comment]
I kinda like this, will push it:

![image](https://user-images.githubusercontent.com/22350/86252153-23a86500-bbb3-11ea-8c71-bb818d784f78.png)

**Comment by joaomoreno** [comment]
Even removing the twistie looks good:

![image](https://user-images.githubusercontent.com/22350/86253729-36239e00-bbb5-11ea-8543-c12534278a77.png)

What do you think?

**Comment by bpasero** [comment]
I would probably prefer a look that is in sync with our split views, e.g. a full border:

![image](https://user-images.githubusercontent.com/900690/86264196-7f2e1f00-bbc2-11ea-8cbc-aaeb24547628.png)

I would even think that bold could work for the first nodes?

**Comment by misolori** [comment]
I thought the solid border was fine, I don't think we ever use a dashed borders so this feels inconsistent.

**Comment by gjsjohnmurray** [comment]
How about the proposal from elsewhere to drop the badge if its value is zero?

**Comment by joaomoreno** [comment]
@bpasero @misolori Using a full border will _fool_ the user into thinking that it can be dragged, since now the core themes all render split views that very same way. This is something I've been trying to avoid since the beginning of this adventure. I'm just going to get an issue: _can't resize SCM provider view_.

@gjsjohnmurray I tried that but didn't really like the fact that the actions wouldn't align with other repositories'.

**Comment by gjsjohnmurray** [comment]
> I tried that but didn't really like the fact that the actions wouldn't align with other repositories'.

@joaomoreno how about styling the badge div as `visibility: hidden;` ?

![image](https://user-images.githubusercontent.com/6726799/86297526-7dc91a80-bbf3-11ea-9559-6bb11e7eec04.png)

**Comment by misolori** [comment]
Do we really need the top level badges at the repo level? Feels like the changes one is the only important one and most of the time it just repeats itself. I think this would look better too:

<img width="400" src="https://user-images.githubusercontent.com/35271042/86310574-4480b280-bbd3-11ea-9395-98b683a67db4.png">

**Comment by bpasero** [comment]
Throwing in another idea: use different background colors for the repos. Compare with our keybindings editor:

![image](https://user-images.githubusercontent.com/900690/86327878-3d45bd00-bc44-11ea-9552-919c3da84a1d.png)

This gives a nice separation between logical units in the list. Though arguably can only be a light change in background color given we have so many selection colors.

**Comment by joaomoreno** [comment]
@misolori Yeah I kinda like that. Though your screenshot shows the _good_ case: you wanna see `vscode-docs` with no changes and `vscode-internalbacklog` with changes. That's the ugly edge case. I'll push the change though!

I'm also going to remove the dotted lines, they haven't grown nicely on me.

@bpasero That's also the style of the splitview for the other half of themes: 

![image](https://user-images.githubusercontent.com/22350/86329325-46d02480-bc46-11ea-8c96-77caf974f0d9.png)

> @joaomoreno how about styling the badge div as `visibility: hidden;` ?

@gjsjohnmurray Good idea but I'll just get the _bad layout in SCM view_ bug right after, since it looks broken.

**Comment by joaomoreno** [comment]
Latest exploration:

![image](https://user-images.githubusercontent.com/22350/86331177-04f4ad80-bc49-11ea-920b-c09d68d626fe.png)

**Comment by joaomoreno** [comment]
And one more iteration, now with a collapse/expand repositories action:

![recording (6)](https://user-images.githubusercontent.com/22350/86337822-e47d2100-bc51-11ea-82d4-6659d184b1ee.gif)

**Comment by gjsjohnmurray** [comment]
@joaomoreno I like the Collapse All, but I see you have also dropped the top level badges entirely. So after Collapse All the only clue about which rows have changes is the presence of absence of the collapse icon at the left end.

I take your earlier point about folk reporting a suppressed 0-badge as a UI bug. How about an empty badge (i.e. no zero in it)? Or fade them?

**Comment by joaomoreno** [comment]
@gjsjohnmurray I'm thinking a setting to show/hide the badge, but maybe keep the default hidden.

**Comment by gjsjohnmurray** [comment]
@joaomoreno a setting sounds like a good compromise. Maybe tri-state, so we can "hide", "show", and "hide if zero". Default to "hide", which has the benefit of leaving a but more space for command buttons and branch name.

**Comment by joaomoreno** [comment]
@gjsjohnmurray Will push a `scm.providerCountBadge` setting with values `['hidden', 'auto', 'visible']`.

**Comment by yume-chan** [comment]
I want to share my thoughts about the new design.

The "check" button used to be visible only if the corresponding repository's view is expanded, rather than showing all the time now. I wonder who would use this button without seeing what's actually changed/stage?

So I tried to move it into the view itself. From this starting point, I also came with the menu refinement ideas.

![Slice 1](https://user-images.githubusercontent.com/1330321/86457460-49ba3a80-bd56-11ea-9f74-b7f776cc0666.png)

I also thought that hovering on the counting badge will show the `...` menu, so more spaces can be saved. But this may cause some confusing so I rejected this one.

**Comment by yume-chan** [comment]
Surprise! There are two more operations when right-clicking the header

![image](https://user-images.githubusercontent.com/1330321/86458818-740cf780-bd58-11ea-8d50-d5fe1d787277.png)

Maybe these can be moved to the left of the "collapse all" button.

**Comment by gjsjohnmurray** [comment]
@yume-chan I really like your ideas. Having multiple "..." menus solves the problem of the very long Git context menu without us having to wait for submenu support for extensions.

Maybe the menu button at (3) should be a "..." rather than an "expand down", for better consistency.

As for the surprise "Close Repository" and "Open in Terminal" context menu, maybe replicate them on menu (2). I don't think they could go alongside "collapse all" because they apply to a single repo.

**Comment by yume-chan** [comment]
> Maybe the menu button at (3) should be a "..." rather than an "expand down", for better consistency.

I want to make it a "button with menu". For example in mail apps usually there is a <kbd>Reply | ▼</kbd> button. Clicking on "Reply" will do one thing, clicking the down arrow will show more operations that relates to the label. But yes I didn't see this pattern in Code.

> As for the surprise "Close Repository" and "Open in Terminal" context menu, maybe replicate them on menu (2). I don't think they could go alongside "collapse all" because they apply to a single repo.

You are right. The explorer can have "New File" and "New Folder" alongside "Collapse All" is because its item can have focus, can't apply to the scm view.

**Comment by gjsjohnmurray** [comment]
> Will push a `scm.providerCountBadge` setting with values `['hidden', 'auto', 'visible']`

@joaomoreno thanks for this, but for auto mode maybe use `visibility: hidden;`

![image](https://user-images.githubusercontent.com/6726799/86462277-422d6e00-bd23-11ea-8387-6bfbd52cc74e.png)

rather than the `display: none;` which you implemented:

![image](https://user-images.githubusercontent.com/6726799/86462444-8ae52700-bd23-11ea-9e38-04ddd030db48.png)

And I suggest default should be 'auto' so people discover the most sophisticated form of the badge feature at this level in the new UX (first screenshot above). Then if they don't like/want these badges they can find the setting and pick 'hidden'.

![image](https://user-images.githubusercontent.com/6726799/86462960-7ce3d600-bd24-11ea-8f4a-585a7fe40fe2.png)

And if the white space to the right of the "..." disturbs them they can pick 'visible'.

![image](https://user-images.githubusercontent.com/6726799/86462995-8cfbb580-bd24-11ea-997a-8d7380db5e1b.png)

**Comment by joaomoreno** [comment]
> @joaomoreno thanks for this, but for auto mode maybe use `visibility: hidden;`

I don't think that's a good idea, since we'd be wasting precious space. Especially if no repository has changes: there would just be an empty column. That is exactly the compromise with `auto`, otherwise we'd take it as the default.

**Comment by gjsjohnmurray** [comment]
> I don't think that's a good idea, since we'd be wasting precious space. Especially if no repository has changes: there would just be an empty column

Maybe make auto smart enough only to use `visibility: hidden;` if at least one other repo has changes?

Are you going to keep the default of `scm.providerCountBadge` as `hidden`? I'd still argue for defaulting to `show`, else some people may not realize it's even possible to show change count badges at this level.

**Comment by joaomoreno** [comment]
> Maybe make auto smart enough only to use visibility: hidden; if at least one other repo has changes?

This will make thing jump around in all repositories if one repository changes.

> Are you going to keep the default of `scm.providerCountBadge` as `hidden`? I'd still argue for defaulting to `show`, else some people may not realize it's even possible to show change count badges at this level.

Yes that's the idea. The hypothesis is that most users don't even care. And the power users have the setting. Trying to stay lightweight here.

**Comment by SailorMax** [comment]
Can you add option to hide action buttons from provider line? They takes too much space +

- Synchronize button we have in "..." menu
- Commit button require commit description => it has to be in "Changes" subtree
- Refresh button also has to be in "Changes" subtree, because of what we have to see after it pressed in closed provider tree?

And look at #102080 . I think it was a mistake.

thank you.

**Comment by vasicsek** [comment]
I have an issue with the action buttons visibility. If my side panel width is not big enough and the names of my repositories are long I can not see the buttons. Below is a screenshot of the issue:
![image](https://user-images.githubusercontent.com/11719529/87150219-f5610e80-c2b1-11ea-8808-d2b6ebb5fdc8.png)
Also, there is no commit button, so I have to increase the width of the panel, which is not the best solution, because when I switch to the explorer view is it wasted space.
![image](https://user-images.githubusercontent.com/11719529/87150527-859f5380-c2b2-11ea-971a-4a0d24dd294e.png)
![image](https://user-images.githubusercontent.com/11719529/87150495-6ef8fc80-c2b2-11ea-8447-c198c2eefaf1.png)

**Comment by misolori** [comment]
Throwing out a few suggestions here:

- What if we moved the refresh action to a global view command? This would free up a bit of space + visual noise
- What if we only showed the commit check icon when there are changes? This would also free some space
- What if we ellipse the repo name? You can still hover the repo to get the title but when the actions are truncated it requires more clicks
- What if we showed the twisties for repos with no changes? We do this in the explorer with empty folders and I think could help with the hierarchy confusion 

<img width="460" src="https://user-images.githubusercontent.com/35271042/87173964-5a553e00-c28b-11ea-952d-8c2540a6cf87.png">

**Comment by joaomoreno** [comment]
> * What if we moved the refresh action to a global view command? This would free up a bit of space + visual noise

We can't really do this since if you have many repositories, refreshing them all is a potentially expensive operation.

> * What if we only showed the commit check icon when there are changes? This would also free some space

This can be interesting yes.

> * What if we ellipse the repo name? You can still hover the repo to get the title but when the actions are truncated it requires more clicks

Yeah that will be the fix of https://github.com/microsoft/vscode/issues/102108

> * What if we showed the twisties for repos with no changes? We do this in the explorer with empty folders and I think could help with the hierarchy confusion

Yeah, let me push that already.

**Comment by gjsjohnmurray** [comment]
> Yeah, let me push that already.

@joaomoreno for bonus points maybe try moving the optional repo-level count badges to the start of the row instead of the end. I think having badges there will help, particularly with `scm.providerCountBadge` set to `auto`. Plus it will solve the button alignment issue `auto` mode gives when badges are on the right.

**Comment by gjsjohnmurray** [comment]
With providerCountBadge set to auto and moved to the left, plus small increases to indents of the tree descendants.

![image](https://user-images.githubusercontent.com/6726799/87737794-d68fda00-c7d3-11ea-9e54-b876e66b6ffd.png)

And with the changed repo collapsed:

![image](https://user-images.githubusercontent.com/6726799/87737897-0ccd5980-c7d4-11ea-9d3b-0fc8b6767589.png)

Without my tweaks:

![image](https://user-images.githubusercontent.com/6726799/87737967-37b7ad80-c7d4-11ea-8d48-8312d6131753.png)

and collapsed:

![image](https://user-images.githubusercontent.com/6726799/87738036-66ce1f00-c7d4-11ea-8555-3886f9248b8c.png)

**Comment by carlocardella** [comment]
Honestly, I prefer the badge count on the right. Maybe my eyes are trained to search for info on the right side but I find the repo names all properly left aligned to be more pleasing and easier to read

**Comment by joaomoreno** [comment]
Yes, I'm really not convinced to move the badge to the left, since it would remove the badge alignment.

**Comment by gjsjohnmurray** [comment]
I still think provider count badges on the left may be helpful to users who are finding it hard to spot where the changed files of one repo end and the title of the next repo starts.  Personally I find the duplication of counts aligned on the right a bit unsatisfactory. When a provider section is collapsed I like to know how many changes it contains, but once I expand it and get subhead counts it's those I want to focus on, and the top-level count is distracting.

How about offering `auto-left` and `visible-left` as additional choices for `scm.providerCountBadge`?

On a related topic, is there any telemetry on the SCM view that would give data on how many providers users have there?

**Comment by misolori** [comment]
We've always had badge counts on the right and moving it to the left would make it inconsistent.

<img width="350" src="https://user-images.githubusercontent.com/35271042/87824114-85aad080-c829-11ea-84df-1b81f7a14453.png">

<img width="350" src="https://user-images.githubusercontent.com/35271042/87824148-90fdfc00-c829-11ea-99e0-d6e0b715350f.png">

<img width="350" src="https://user-images.githubusercontent.com/35271042/87824285-d3273d80-c829-11ea-93e4-00ccdcf170f5.png">

<img width="350" src="https://user-images.githubusercontent.com/35271042/87824300-dc180f00-c829-11ea-92ce-d9c9de3293cd.png">
