### ISSUE TITLE
Feature requests: CTRL+click to follow non-import links

### ISSUE THREAD

**Issue by stephanjust** [Microsoft/vscode#10119]
- VSCode Version: 1.3.1
- OS Version: Windows 7 x64

Currently vscode supports CTRL-clicking links and/or classes in imports to open said file (and clicking certain things to go to the definition, but that's not the point here).
```import {NKDatetime} from '../../lib/ng2-datetime/ng2-datetime';```

If we have an identical definition that's not part of an import statement, CTRL-clicking doesn't work.
```
class Test {
    a = '../../lib/ng2-datetime/ng2-datetime';
}
```
This is probably because it's not clear what the string is supposed to be and therefore it was never added.

The proposal:
If a string is clicked with CTRL as a modifier and the string has a known file ending, vscode should attempt to open the file.

The primary use case that I encountered is opening template files in Angular 2.
```
@Component({
    selector: 'editor',
    templateUrl: 'views/editor.html',
})
```

**Comment by aeschli** [comment]
@jrieken Joh, I guess that can be done with the link detection contributions?

**Comment by jrieken** [comment]
Yes - you can use the `DocumentLinkProvider` orthe `DefinitionProvider` apis to implement this. The latter is wired into the `ctrl-click` (and go to definition, peek definition etc). The former renders a link for this which you then can select as well. 

Closing this as question since this should come via an extension similar or maybe even like this one: https://marketplace.visualstudio.com/items?itemName=abierbaum.vscode-file-peek
