### ISSUE TITLE
Custom renderer output broken on latest insiders

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#101149]
Yesterday:
![image](https://user-images.githubusercontent.com/8586769/85885077-97540780-b798-11ea-9343-7f6ff6996575.png)

Today:
![image](https://user-images.githubusercontent.com/8586769/85884874-2dd3f900-b798-11ea-8b92-a363077af3cb.png)

The custom renderer demo is also a bit wonky:
![image](https://user-images.githubusercontent.com/8586769/85885372-13e6e600-b799-11ea-9835-4f002db1e5fb.png)

**Comment by rebornix** [comment]
@connor4312 any idea what potentially changed?

**Comment by rebornix** [comment]
The url for preload scripts are wrong

```
Failed to load resource: net::ERR_UNKNOWN_URL_SCHEME
vscode-resource://file///Users/penlv/code/vscode/extensions/notebook-test/dist/nteract.js:1 
```

**Comment by connor4312** [comment]
Are you using the `debugWebviews`? This only works on OSS with the special build at the moment (working with Deepak to figure out why Insiders doesn't have it) and will result in empty webviews if you try to use it.

The custom renderer demo looks 'correct'. The text is light blue and I never tested on a dark theme. Oops. I'll change that to add a background color in the yo code generator.

I haven't changed notebook webviews otherwise since last week.

**Comment by JacksonKearl** [comment]
I haven't changed any settings, the custom renderer coloring hasn't changed but the alignment is a bit wonky (notice the double-opaque-bottom, similar can be seen in my example)

My repo is here:

**Comment by JacksonKearl** [comment]
Seems to be fixed by the new release @mjbvz put out.
