### ISSUE TITLE
Go to Symbol shortcut not working in JSON

### ISSUE THREAD

**Issue by KyleRAnderson** [microsoft/vscode#101130]
Issue Type: <b>Bug</b>

Currently, when I press Ctrl+Shift+O to go to symbol while in a json file, nothing happens. I know that this was working before the latest update.
I went to the keybindings page and I had nothing set except for the default bindings, so on Ctrl+Shift+O, I had "Go to Symbol" and "Organize Imports" bound.
I tried removing the binding for "Organize Imports" and then it worked, so it looks like this is the cause, however I'm not sure why this worked before and doesn't now.

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (6.31GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
code-groovy|mar|0.1.2
remote-wsl|ms-|0.44.4
vsliveshare|ms-|1.0.2377
polacode|pnp|0.3.4
java|red|0.63.0
vscodeintellicode|Vis|1.2.8
vscode-java-debug|vsc|0.26.0
vscode-java-dependency|vsc|0.10.2
vscode-java-pack|vsc|0.9.1
vscode-java-test|vsc|0.23.0
vscode-maven|vsc|0.22.0

</details>

**Comment by aeschli** [comment]
I'm not able to reproduce on Linux and Windows on the latest insiders, Ctrl + Shift + O shows the outline.

**Comment by alexdima** [comment]
@KyleRAnderson One of your installed extensions might be contributing the keybinding "Ctrl+Shift+O".  You can see this in the "Source" column of the keybindings editor. By default, we ship only with outline bound to "Ctrl+Shift+O". So the resolution is to:
1. uninstall the extension that contributes this keybindings. (you can see what each extension contributes by clicking on it and going to Feature Contributions):
![image](https://user-images.githubusercontent.com/5047891/85993610-dd0e0b80-b9f6-11ea-9de5-ee3973d912df.png)

2. (or) remove any keybindings that you don't want from the extension. This is what you have done, so you're good to go.

3. (or) report to the extension issue tracker directly and point out that it is unwise to ship keybindings with an extension, since conflicts (like this one) could be introduced by accident.

**Comment by KyleRAnderson** [comment]
@alexdima I had originally thought that that was the issue, but the source column said "default". Now, looking at my keybindings again, the source is still "default" but underneath the action name, you can see that it's for `cgroovy`. 
![image](https://user-images.githubusercontent.com/22606608/86000787-02d9e700-b9dc-11ea-9d0e-46b6d28f40e0.png)

Anyway, thanks for looking into this one!

**Comment by alexdima** [comment]
Oh, I see, the keybindings editor does not distinguish keybindings sources entirely.  It just categorizes things as Default or User.  But Default can be further classified as `core` and `extensions`. My mistake, I think the editor does not render the Source in such a high detail that I thought.
