### ISSUE TITLE
SCM: Support to hide repositories

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#101145]
I have a multiroot workspace with two folders and want to focus on one of them in the SCM view. I haven't used the "close repository" option before so I don't know what's supposed to happen exactly but if I close the repo I don't care about, it just reappears

![Jun-26-2020 11-01-28](https://user-images.githubusercontent.com/323878/85877310-91f8bc00-b79c-11ea-94f6-5fd45ea76976.gif)

I think that if I can't hide or reorder these entries, the new view makes it a little harder to just focus on the changed files in the vscode repo

**Comment by joaomoreno** [comment]
Yeah for now there is no way to hide, just collapsing. We can think about such UX next iteration.

**Comment by ryenus** [comment]
Same here, closed repositories would always comeback. And some of the repositories are just **submodules** nested in another repo already in the Source Control view.

It's probably necessary to provide an option to exclude submodules from the view.

**Comment by daniel-schmidt** [comment]
In my case, I have an SVN repository with many externals, which also show up in the view. Usually, I am interested only in the main repo and a specific external one, so providing an option to hide selected repos would be great. The current state is quite useless for me, since it is way too cluttered with repos I don't care about.

**Comment by joaomoreno** [comment]
Merging into #104151
