### ISSUE TITLE
Extension host debug session keeps lingering around

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#101108]
1. Open vscode repository
2. Start debugging `VS Code` compound config
3. After all is up and running close the newly opened VS Code window
4. In the first window notice how all the sessions get closed, but the Attach to Extension Host remains. Visually it might not be visible and it might look like your are no longer debugging but this is an issue on the VS Code debug ux side.
5. Try to start debugging again, you get the error "There is already a debug configuration "VS Code" running." Reason for this is because the Attach To Extension Host session is still alive 🐛 

After some time, like 10s the Attach to Extension Host goes away.
I am not sure where the exact issue is, so I am investigating. Also assigning to @weinand and @connor4312 since you might know more.

Related to https://github.com/microsoft/vscode/issues/100368

**Comment by connor4312** [comment]
This is because `"restart": true,` is on the extension host launch config, so that launch config will retry attaching to the extension host, which is quite useful if you reload the window.

`stopAll` makes this scenario better, but that only kills other session when the _user_ ends any of the top-level sessions: closing the window doesn't trigger this logic. We could change this behavior, but it also means that if any config times out / fails to launch, then all of the sessions will also be closed.

**Comment by isidorn** [comment]
@connor4312 thanks for letting me know.

I do not think `stopAll` has a large usage and I would like that we experiment with it.
How about at the start of the July milestone we change this behavior as you propose: if any of the configs fails in any way all others are stopped. Or if you feel loco we can do it right away today.

**Comment by isidorn** [comment]
Alternative idea: that we allow Compound to start even if one of it's sessions is running. So we would simply just start all other sessions, and ignore the one which is already running. That might work well in this case.

**Comment by connor4312** [comment]
Or we automatically stop any lingering configurations, which would work for this case and also work in the scenario that someone has one process with old code still running that they would want to clear out.

**Comment by isidorn** [comment]
But VS Code is not really sure it is "lingering" I believe. I would have to double check but I am not sure how to detect this.
If the "automatic stop" is coming from js-debug then this would work of course.

**Comment by connor4312** [comment]
I fixed this in https://github.com/microsoft/vscode-js-debug/commit/0da270a3d75f9e8a613d6d88b3b2967fc8e1fb68

**Comment by isidorn** [comment]
Awesome 👏

**Comment by isidorn** [comment]
I tried this out and did not really get better for me.

1. Start "VS Code" compound configuration
2. Once everything is up and running close the newly opened vscode window by clicking on the red close button
3. Once window is closed all session remain active. Only if closed via Cmd + Q the sessions get closed
4. However even then the "Attach to Extension Host" remains active

Due to this reopening this issue so you can double check if you also see this behavior

**Comment by connor4312** [comment]
3: this is expected since the application is still running, it just doesn't have any open windows. On Windows, where this behavior doesn't exist, the process exits immediately

4: I'm not seeing this -- am I doing something differently? https://memes.peet.io/img/b57d4559-809d-4458-ba2d-f62eb2971f5e.mp4 There is a slight delay if you stop the main config when the extension host config isn't attached which is a bit janky (I'll fix that) but it seems to work

**Comment by isidorn** [comment]
I can no longer repro. Closing this and adding verified label.
Good work.

**Comment by connor4312** [comment]
Okay, thanks! Maybe you had an older version of js-debug that updated asynchronously 🤔
