### ISSUE TITLE
Opening editor: debug service consumes a lot of time changing contexts?

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#101268]
Opening a simple editor (`package.json` in our repo), I see a lot of time spent in `DebugService`, probably triggered from `DebugEditorContribution`.

![image](https://user-images.githubusercontent.com/900690/85988871-f8c1e380-b9ef-11ea-8016-fa29d7d46fc5.png)

There seems to be a lot of time spend in context key changes, not sure if this is a general issue.

Not clear to me why the debug service is needed right on startup.

[Profile-20200629T100530.json.zip](https://github.com/microsoft/vscode/files/4844530/Profile-20200629T100530.json.zip)

//cc @jrieken

**Comment by bpasero** [comment]
Oh, maybe this is flawed, I remember @jrieken I think mentioned that `setTimeout` and `clearTimeout` show up as bottlenecks only when performance tracing is enabled, so might be a red herring:

![image](https://user-images.githubusercontent.com/900690/85989190-7554c200-b9f0-11ea-921a-58e963327c17.png)

**Comment by isidorn** [comment]
Ok, so in this profile it takes 24ms and out of that most of the time is spent on `setTimeout` and `clearTimeout`.
I have changed that when the debug service is created that I pass the `supportsDelayedInstantation` flag.
However it is needed "very early" because the`DebugEditorContribution` needs to know if it is ok to place breakpoints in that file.
Maybe we should split up the `debugService` into two parts, such that the one that knows about breakpoint is immediatly available and the rest only once you want to start debugging.

When I try to repro globaly I get the same as what you attached, and most of the time is spent on `setTimeout` and `clearTimeout`.

For now clossing as the moving `debugService` into two parts is larger debt work, and for now I am hapy with the `supportsDelayedInstantation` flag.
If you have ideas, please let me know.

fyi @weinand for the `delayedInstantationFlag` in case something breaks next week once I am out.

**Comment by jrieken** [comment]
@isidorn Also consider to use [`bufferChangeEvents`](https://github.com/microsoft/vscode/blob/cadabab73fef89fe0c4bfe23b5a33cd58e39ea9c/src/vs/platform/contextkey/common/contextkey.ts#L981). That allows to change many context keys and only a single event is generated from that

**Comment by isidorn** [comment]
@jrieken thanks for the idea, was not aware of that method. I pushed that change.

**Comment by bpasero** [comment]
I think the lazy instantiation of the debug service is not adding a lot because the debug contribution needs it directly. However, buffering context key changes is interesting and the first time I hear about it.

@jrieken shouldn't we make a general push to adopt it widely? E.g. code such as this should use it, no?

https://github.com/microsoft/vscode/blob/aa60541db5ff286ad9ffaaa77f55e537045df7ad/src/vs/workbench/common/resources.ts#L79-L87

**Comment by isidorn** [comment]
@bpasero yes lazy instantiation is not adding a lot as I mentioned above.
Yeah `resources.ts` is another good candidate to adopt to this. And we could look into doing this across the workbench.

**Comment by jrieken** [comment]
> @jrieken shouldn't we make a general push to adopt it widely? E.g. code such as this should use it, no?

Agreed - I never really advertised this. The performance data is unreliable to the gains aren't clear but since each listener is usually doing some per event it's better to have less events
