### ISSUE TITLE
Custom editors - "Open With.." -> "Set as default editor" ignores complex "filenamePattern" from editor definition

### ISSUE THREAD

**Issue by anzwdev** [microsoft/vscode#101220]
- VSCode Version: 1.46.1
- OS Version: Windows 10

It is possible to use complex patterns in "filenamePattern" property of custom editor definition, it works fine but "Set as default editor" option in the menu displayed by Visual Studio after selecting "Open With..." sets selected editor as default for all files with the same extension, even if these files don't match "filenamePattern". From that moment selected editor also becomes available on the list of editors displayed by "Open With..." function.

I am creating my "AZ AL Dev Tools" VS Code extension for "Microsoft Business Central" developers, it extends functionality delivered by Microsoft in their "Microsoft AL Extension". Microsoft delivers separate json schemas for 3 different types of json files:
- app.json
- *.ruleset.json
- AppSourceCop.json
They are all different, but as you can see, they all have *.json file extension. I've created 3 separate editors for these files and later merged my custom editor providers into one, but there are another, standard VS Code files in ".vscode" folder ("launch.json", "settings.json"). Making my editor default makes it also default for them, which is something that I would like to avoid. That's how my settings look like now:

```javascript
"customEditors": [
	{
		"viewType": "azALDevTools.jsonEditor",
		"displayName": "Visual Editor",
		"priority": "option",
		"selector": [
			{
				"filenamePattern": "app.json"
			},
			{
				"filenamePattern": "*.ruleset.json"
			},
			{						
				"filenamePattern": "AppSourceCop.json"						
			}
		]
	}
]
```

It works the same way in both current and insiders versions of VS Code.

![customeditorbug](https://user-images.githubusercontent.com/24944969/85942612-407a3980-b922-11ea-976c-cc47980193b0.gif)

Does this issue occur when all extensions are disabled?: N/A

**Comment by mjbvz** [comment]
I just looked over this issue again. The new experience makes it more clear what you are configuring:

![Screen Shot 2021-10-19 at 3 31 41 PM](https://user-images.githubusercontent.com/12821956/137999739-ae982955-3008-4ac7-8d3b-660dd3126bd7.png)

![Screen Shot 2021-10-19 at 3 32 04 PM](https://user-images.githubusercontent.com/12821956/137999668-aa372cfe-e21a-42d7-aab8-009a828f1334.png)

The current configure option handles the most common use case. Users can dive into the settings if they need to associate a specific filename with a given editor type. If this is a common usecase for your extension, you could also add documentation that explains how to do this

I'm going to close this issue as a feature request that hasn't gotten further much attention from the community since being opened

**Comment by villelahdenvuo** [comment]
@mjbvz The `configure default editor` setting is not in the current stable release yet, right? I want to open markdown files in a notebook editor by default, but I can't find a setting to do that.

**Comment by lramos15** [comment]
@villelahdenvuo It is. F1 -> Reopen Editor With... -> At the bottom configure default
