### ISSUE TITLE
Webview resources not loading in WSL2

### ISSUE THREAD

**Issue by volopasse** [microsoft/vscode#101272]
This issue is similar to [#101093](https://github.com/microsoft/vscode/issues/101093), but only observed in  WSL2. When loading the Git Graph extension, the `.css` and `.js` resources are not loaded, throwing a 404 error. When the WSL environment is converted to v1, it works as expected. 

My unsubstantiated guess is that it has to do with changes to how WSL presents the filesystem to the host between v1 and v2.

I believe @mjbvz was looking at this previously, hence pinging him here.

```
Version: 1.47.0-insider (user setup)
Commit: 7923112cdd20575406ec547b55a99c289dd7d7e2
Date: 2020-06-29T05:53:43.438Z
Electron: 8.3.3
Chrome: 80.0.3987.165
Node.js: 12.13.0
V8: 8.0.426.27-electron.0
OS: Windows_NT x64 10.0.19042
```

Steps to reproduce:
1. Create a new WSL instance using v1 (e.g. I have Ubuntu 20.04)
2. Connect with Remote-WSL extension
3. Install Git Graph extension
4. Create a test repo, observe Git Graph loads as expected
5. Convert WSL to v2 with `wsl --set-version Ubuntu-20.04 2`
6. Reconnect and observe Git Graph assets not being loaded

Does this issue occur when all extensions are disabled?: No (as it's related to the extension)

![git-graph-dev-tools](https://user-images.githubusercontent.com/2857268/85995762-09c32280-b9f9-11ea-995a-a727b68a9917.png)
![git-graph-sources](https://user-images.githubusercontent.com/2857268/85995765-0a5bb900-b9f9-11ea-91cf-1b2955b5f3ed.png)

The extension has two files, `out.min.css` and `out.min.js` that render the UI. As you can see above, `out.min.css` is empty, and `out.min.js` is not present at all, while both of them are available in the filesystem. When converted to WSLv1, both are loaded correctly

**Comment by bobmorane06** [comment]
+1, same issue encountered on my side (I haven't tried with WSL1)

**Comment by mjbvz** [comment]
@alexdima I've tracked this down to whether we use http or https while requesting remote resources:

https://github.com/microsoft/vscode/blob/33142d0202d018e0e5bc11304504c84c33c3e8d5/src/vs/platform/webview/electron-main/webviewProtocolProvider.ts#L159

We always tried to use `https` except tor requests to localhost. However for wsl2, the remote address ends up being something like:

<img width="686" alt="Screen Shot 2020-06-30 at 3 07 45 PM" src="https://user-images.githubusercontent.com/12821956/86181958-d4473380-bae3-11ea-9b8b-08ac70672bd1.png">

This means we try to make a `https` request which fails since the server does not support http.

Not sure what the correct way to fix this is. Should `IRemoteConnectionData` potentially include a `scheme`?

**Comment by alexdima** [comment]
:+1: `http` is the protocol always used by VS Code Desktop in all remote scenarios. The responsibility to secure communication if the machine bou

**Comment by joaomoreno** [comment]
@mjbvz Does this repro with the simple built-in Markdown viewer? If so, feel free to mark it as verified.

**Comment by volopasse** [comment]
Can confirm working on the latest release. Thank you so much!

```
Version: 1.47.0-insider (user setup)
Commit: 04545fa88043fd10d1f3edefd26be1b8245b516f
Date: 2020-07-02T05:48:37.715Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19042
```
