### ISSUE TITLE
No error pop-up notification when throwing an error from extension activate() function

### ISSUE THREAD

**Issue by Veetaha** [microsoft/vscode#101242]
- VSCode Version: 1.47.0-insider
- OS Version: Linux x64 5.4.0-39-generic

Steps to Reproduce:

Create a vscode extension with the following code:
```ts
export async function activate() {
    throw new Error("Failed to bootstrap");
}
export async function deactivate() {}
```

There is no error notification about the failure to activate the extension.
In fact, this is very weird, this bug is kinda floating?
I clearly remember vscode to show a popup error notification with the error message some time ago (when creating this PR: https://github.com/rust-analyzer/rust-analyzer/pull/4993). But now, things stopped working I guess (https://github.com/rust-analyzer/rust-analyzer/issues/5091#issuecomment-650800525)? Now when you throw an error in `activate()` function nothing is displayed in the UI, but if you open the `Developer Tools` console, you will see the message there.

This is very strange, I don't know why it worked before and why it doesn't work now. I even remember it not working before I was writing the PR (and at the point of time when writing the PR it was suddenly working?!...).

Anyway, could you guys confirm this is a bug or not, and/or document the behaviour of throwing an error from `activate()` function?
I haven't seen any API to **fail** or **cancel** the extension activation (i.e. the user has misconfigured something and our extension cannot simply function for this reason so we would like to cancel the extension activation) and even after throwing an error in `activate()` the user can still use the commands registered in our extension `package.json` which doesn't seem right... 

Does this issue occur when all extensions are disabled?: yup

**Comment by yume-chan** [comment]
Relates to #100856

**Comment by alexdima** [comment]
This is expected. It all depends if you are debugging the extension or not.

When throwing from `activate()` and doing extension development (via `F5`), we show a notification. This is because this might be very relevant to the developer building the extension.

When throwing from `activate()` from a user installed extension (and running vscode normally), we do not show a notification. This is intentional. The decision has been to "eat up" this error and only log it to the log and to the developer tools in order to not appear that vscode is broken due to a misbehaving extension.
