### ISSUE TITLE
Text editor not showing all the lines

### ISSUE THREAD

**Issue by ionuttamas** [microsoft/vscode#101303]
Issue Type: <b>Bug</b>

Look at the screen info. Line 32 to 39 are missing.

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.84GB (29.36GB free)|
|Process Argv|--folder-uri file:///d%3A/Edge/src|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.28.3
![image](https://user-images.githubusercontent.com/5080185/86043098-0a5db800-b9fd-11ea-93e8-b1cf0fe78b5a.png)

</details>

**Comment by ionuttamas** [comment]
![image](https://user-images.githubusercontent.com/5080185/86043152-1fd2e200-b9fd-11ea-997a-a7e41bada5c0.png)

**Comment by gjsjohnmurray** [comment]
If you run `Unfold All` from the Command Palette do the missing lines appear?

**Comment by alexdima** [comment]
@ionuttamas I have the same question as @gjsjohnmurray:
* does `Unfold All` restore the missing lines ?
* Also, are there any errors in the Developer Tools Console that you can open via `F1 > Developer: Toggle Developer Tools`. 
* If you closed VS Code since the issue happened, it would be helpful to see some logs from the time the issue occurred. You can find the current running instance's logs via `F1 > Developer: Open Logs Folder` and then you can go up in the directory structure and find the session when the problem occurred. The renderer log would be helpful, particularly if it contains any error stack traces.
