### ISSUE TITLE
Bogous file name when dragging file onto desktop

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#101368]
Testing #101334

* ubuntu 18.04 on parallels
* have `package.json` in the explorer
* move the file to the ubuntu desktop
* :bug: the file get a weird new name which resembles the folder path

<img width="1281" alt="Screenshot 2020-06-30 at 11 33 12" src="https://user-images.githubusercontent.com/1794099/86110281-ab17aa80-bac5-11ea-8fe3-d11626129ba3.png">

**Comment by bpasero** [comment]
This is just how Linux seems to behave. We add the path to the transfer so that you can drag a file e.g. into the terminal to have its path pasted there. And it seems that this results in the file being created if you drop on the desktop. The `DownloadURL` thing we use is something Chrome provides and does not seem to work here. 

I rather would like to keep the support for dragging and dropping paths into the terminal so I will not change this. 

We have https://github.com/microsoft/vscode/issues/164 as issue to make file-dnd better in general.
