### ISSUE TITLE
Can't debug typescript.js code

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#101373]
I tried to debug code inside the typescript.js file but I can't hit breakpoints or steps into the code on neither Windows nor Linux (under WSL). Steps to reproduce:

- clone https://github.com/microsoft/lsif-node.git
- cd into lsif-node
- run `npm install`
- run `npm run symlink`
- run `npm run compile`
- open VS Code
- open lsifs.ts
- set breakpoint on line 59 `const result = ts.getDefaultLibFilePath(options);`
- select launch config `test:lsif`
- run the launch config
- observe: breakpoint is hit
- step out
Observe: the debugger hangs and the source code of `typescript.js` is not shown.

When the breakpoint is hit you can naviagte the stack trace and `typescript.js` is correctly loaded. However any breakpoint you can't set in the file is never hit.

**Comment by weinand** [comment]
I can reproduce this with the new JavaScript debugger "js-debug".

With the setting `"debug.javascript.usePreview": false` stepping out work fine for me.

**Comment by connor4312** [comment]
The problem is caused by `smartStep`, looks like it gets stuck in repeated "step in"s  at this function. You can get around this in the interim by disabling smartStep. If you actually _want_ to stop inside typescript.js, then disabling smart step (whose purpose is to automatically step through code that lacks sourcemaps) is what you want to do.

Interestingly, the smart step in node-debug doesn't kick in for typescript.js. I think this is a bug: js-debug does the right thing in identifying typescript.js as step-worthy, but does the wrong thing when stepping out from it.

**Comment by connor4312** [comment]
smartStep now remembers the step direction, which should help avoid getting stuck stepping in infinitely https://memes.peet.io/img/20-06-f6819224-f665-481c-8508-b85d80fc5861.webm
