### ISSUE TITLE
Notebook: weird drop-shadow border around active cell

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#101375]
Testing #100965

I would prefer just the focus outline I think:

![image](https://user-images.githubusercontent.com/900690/86111283-dd75d780-bac6-11ea-91dd-b27b0cf29240.png)

**Comment by isidorn** [comment]
Related to https://github.com/microsoft/vscode/issues/101285

**Comment by misolori** [comment]
You could try setting `notebook.focusedCellShadow` to `#0000` and seeing if that feels better.

**Comment by bpasero** [comment]
@misolori yes better. I really think we should not have this shadow by default, just see how bad it looks on the edge to the sidebar:

![image](https://user-images.githubusercontent.com/900690/86209528-0e134b00-bb73-11ea-9e96-a43334157abb.png)

Can we consider this for June?

**Comment by bpasero** [comment]
Compare with inline editors that have no shadow:

![image](https://user-images.githubusercontent.com/900690/86209589-2daa7380-bb73-11ea-843b-9a63649b07a5.png)

**Comment by misolori** [comment]
This one is tough because the drop shadow is a common trait in other notebooks (collab, nteract, etc.) and it seems like this comes down to personal preference. We do have some themes that hide shadows altogether, and we've re-used that token here to respect that. 

One thing we could add is a slight border to the top and bottom of the cell like in the case where shadows are hidden:

![image](https://user-images.githubusercontent.com/35271042/86268286-cc879d80-bb7c-11ea-8caa-202b727ce7fa.png)

**Comment by bpasero** [comment]
> This one is tough because the drop shadow is a common trait in other notebooks (collab, nteract, etc.) and it seems like this comes down to personal preference

If in doubt I would go for a consistent design language here and not use shadows to indicate focus. We indicate focus via blue outline everywhere in the UI, so I do not understand why the shadows are used only for notebooks. Imho that is inconsistent design language we should avoid.

**Comment by misolori** [comment]
@bpasero we removed the shadow for the active cell:

![image](https://user-images.githubusercontent.com/35271042/87396537-d4294800-c567-11ea-851b-3ca03188cee3.png)

**Comment by bpasero** [comment]
Love it 👍
