### ISSUE TITLE
Notifications and feedback should not be visible at the same time

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#101376]
Testing #101334

* click on both status bar entries

<img width="550" alt="Screenshot 2020-06-30 at 11 42 46" src="https://user-images.githubusercontent.com/1794099/86111289-dea70480-bac6-11ea-91e8-1d5136b1e14c.png">

**Comment by bpasero** [comment]
I think when one opens the other should maybe hide. Up for grab.

**Comment by jppm99** [comment]
I can reproduce this on the official release but when I run from source I don't have the feedback button. I might have solved this but I'm not sure how to test.

**Comment by bpasero** [comment]
@jppm99 see https://github.com/microsoft/vscode/issues/100897#issuecomment-649232056

**Comment by jppm99** [comment]
I opened a PR for this (had to close the first one because it caused an error when there was no tweet feedback button).
I would also suggest creating a file similar to the notificationsCommands for the tweet feedback commands because I had to hardcode some in the statusbarPart since it wouldn't allow me to create macros in the feedbackStatusBarItem and then include them.

**Comment by bpasero** [comment]
![recording (1)](https://user-images.githubusercontent.com/900690/108966304-4b869480-767e-11eb-9ccb-1f1e12764378.gif)
