### ISSUE TITLE
Notebook: looses contents when moving down

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#101378]
Testing #100965

* have 3 notebooks (2 inactive tabs, 1 active)
* move the active one down

=> contents are not restored
=> there are errors in the console

![recording (7)](https://user-images.githubusercontent.com/900690/86111746-6bea5900-bac7-11ea-8a1c-118f7fb30846.gif)

**Comment by jrieken** [comment]
This is fishy... The widget gets disposed, not re-used because this is considered to be an open-sequence, so [`_disposeWidget`](https://github.com/microsoft/vscode/blob/b91c21b80ea65af62e1b975c6e7449858002fca9/src/vs/workbench/contrib/notebook/browser/notebookEditorWidgetService.ts#L93) is being called. Then a new widget is created but some reason the models don't get resolved again but somehow re-used...
