### ISSUE TITLE
I cannot install extension of VScode

### ISSUE THREAD

**Issue by Hridayshaha** [microsoft/vscode#101349]
when i click on extension its says "We cannot connect to the extensions marketplace at this time please try again later".
How can i solve this issue for this reason i cannot install my important extension and my internet connection is fully fine .
![106550096_268302031273740_4298942809657010919_n](https://user-images.githubusercontent.com/56909705/86104408-d3ac9e00-badf-11ea-85ae-e29c8b503601.jpg)

**Comment by pleabargain** [comment]
Same here.
Cannot connect to market.

video
https://youtu.be/njbbeECNbi8

Visual Studio Code 1.46.1
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04 LTS
Release:	20.04
Codename:	focal

**Comment by sandy081** [comment]
Please follow these steps

- Help -> Toggle Developer Tools -> Network
- Then check for any network failed requests while browsing and installing the extensions if found all requests fails then its probably a proxy or DNS issue at your end.
- To confirm its a DNS issue check if you can access this page https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default, if you cannot please try configuring your DNS like pointing to 1.1.1.1 as suggested here? https://1.1.1.1/dns/. Otherwise please contact your network administrator.
- If it is not a network issue, please share the logs from the following locations
    - Help -> Toggle Developer Tools -> Console
    - View -> Command Pallette... -> Toggle Shared Process -> Console
    - View -> Open View… -> Log (Shared)
    - View -> Open View… -> Log (Window)

**Comment by Hridayshaha** [comment]
Thanks a lot for the help.
