### ISSUE TITLE
Extensions are not installing... Even if I have tried with faster DNS server

### ISSUE THREAD

**Issue by Malaya2184** [microsoft/vscode#101435]
Issue Type: <b>Bug</b>

I am trying to install some extensions but it is neither installing automatically nor by vsix file.... So what can i do right now..

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-7020U CPU @ 2.30GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (1.95GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
c-cpp-compile-run|dan|1.0.11
gitlens|eam|10.2.1
php-debug|fel|1.13.0
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
auto-rename-tag|for|0.1.3
git-graph|mhu|1.23.0
vscode-autoprefixer|mrm|3.0.1
vscode-scss|mrm|0.9.0
anaconda-extension-pack|ms-|1.0.1
python|ms-|2020.5.80290
indent-rainbow|ode|7.4.0
vscode-css-peek|pra|3.0.2
java|red|0.62.0
vscode-yaml|red|0.8.0
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
code-spell-checker|str|1.9.0
sass-indented|syl|1.8.4
vscode-java-debug|vsc|0.26.0
vscode-java-dependency|vsc|0.10.2
vscode-java-pack|vsc|0.9.1
vscode-java-test|vsc|0.22.4
vscode-maven|vsc|0.21.4
vscode-icons|vsc|10.1.1
vscode-todo-highlight|way|1.0.4
html-css-class-completion|Zig|1.19.0

</details>

**Comment by sandy081** [comment]
Please follow these steps

- Help -> Toggle Developer Tools -> Network
- Then check for any network failed requests while browsing and installing the extensions if found all requests fails then its probably a proxy or DNS issue at your end.
- To confirm its a DNS issue check if you can access this page https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default, if you cannot please try configuring your DNS like pointing to 1.1.1.1 as suggested here? https://1.1.1.1/dns/. Otherwise please contact your network administrator.
- If it is not a network issue, please share the logs from the following locations
    - Help -> Toggle Developer Tools -> Console
    - View -> Command Pallette... -> Toggle Shared Process -> Console
    - View -> Open View… -> Log (Shared)
    - View -> Open View… -> Log (Window)

**Comment by anatolyvenzekov** [comment]
I have the same issue as @Malaya2184 related to all my vscode extensions.

`The installation of the C/C++ extension failed. Please see the output window for more information.`

Version: 1.46.1
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:13:08.304Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.3.0-40-generic snap

I can confirm that it is not a DNS issue due to I can acess the page you hace provided.

I share you the following logs:

- Help -> Toggle Developer Tools -> Console
`/snap/code/35/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1670   ERR EACCES: permission denied, open '/home/venze/.vscode/extensions/.obsolete': Error: EACCES: permission denied, open '/home/venze/.vscode/extensions/.obsolete'
    at file:///snap/code/35/usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:545:81
    at async Promise.all (index 1)
/snap/code/35/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:6781 Error querying extensions gallery EACCES: permission denied, open '/home/venze/.vscode/extensions/.obsolete'
(anonymous) @ /snap/code/35/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:6781
/snap/code/35/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:5064 Overwriting grammar scope name to file mapping for scope source.python.
Old grammar file: file:///snap/code/35/usr/share/code/resources/app/extensions/python/syntaxes/MagicPython.tmLanguage.json.
New grammar file: file:///home/venze/.vscode/extensions/magicstack.magicpython-1.1.0/grammars/MagicPython.tmLanguage
register @ /snap/code/35/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:5064
/snap/code/35/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:5064 Overwriting grammar scope name to file mapping for scope source.yaml.
Old grammar file: file:///snap/code/35/usr/share/code/resources/app/extensions/yaml/syntaxes/yaml.tmLanguage.json.
New grammar file: file:///home/venze/.vscode/extensions/pivotal.vscode-spring-boot-1.19.0/yaml-support/yaml.tmLanguage
register @ /snap/code/35/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:5064
/snap/code/35/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:5064 Overwriting grammar scope name to file mapping for scope source.yaml.
Old grammar file: file:///home/venze/.vscode/extensions/pivotal.vscode-spring-boot-1.19.0/yaml-support/yaml.tmLanguage.
New grammar file: file:///home/venze/.vscode/extensions/redhat.vscode-yaml-0.8.0/syntaxes/yaml.tmLanguage.json
register @ /snap/code/35/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:5064
/snap/code/35/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2932 The installation of the C/C++ extension failed. Please see the output window for more information.
onDidChangeNotification @ /snap/code/35/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2932
/snap/code/35/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:265 [Extension Host] [CMakeTools] 2020-07-01T18:16:42.875Z [debug] [main] Safe constructing new CMakeTools instance
/snap/code/35/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:265 [Extension Host] [CMakeTools] 2020-07-01T18:16:42.876Z [debug] [variant] Constructing VariantManager
/snap/code/35/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:265 [Extension Host] [CMakeTools] 2020-07-01T18:16:42.877Z [debug] [main] Constructing new CMakeTools instance
/snap/code/35/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:265 [Extension Host] [CMakeTools] 2020-07-01T18:16:42.877Z [debug] [main] Starting CMakeTools second-phase init
/snap/code/35/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:265 [Extension Host] [CMakeTools] 2020-07-01T18:16:42.958Z [info] [variant] Loaded new set of variants
/snap/code/35/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:265 [Extension Host] [CMakeTools] 2020-07-01T18:16:42.959Z [debug] [main] CMakeTools instance initialization complete.
/snap/code/35/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:265 [Extension Host] [CMakeTools] 2020-07-01T18:16:42.961Z [debug] [kit] Reading kits file /home/venze/.local/share/CMakeTools/cmake-tools-kits.json
/snap/code/35/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:265 [Extension Host] [CMakeTools] 2020-07-01T18:16:42.992Z [info] [kit] Successfully loaded 8 kits from /home/venze/.local/share/CMakeTools/cmake-tools-kits.json
/snap/code/35/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:265 [Extension Host] [CMakeTools] 2020-07-01T18:16:42.994Z [debug] [kit] Not reading non-existent kits file: /home/venze/code/generadron/flight-controller/.vscode/cmake-kits.json
/snap/code/35/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:265 [Extension Host] [CMakeTools] 2020-07-01T18:16:43.006Z [debug] [extension] Configuring workspace on open file:///home/venze/code/generadron/flight-controller
/snap/code/35/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:265 [Extension Host] [CMakeTools] 2020-07-01T18:16:43.006Z [debug] [kitsController] Start selection of kits. Found 10 kits.
/snap/code/35/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:265 [Extension Host] [CMakeTools] 2020-07-01T18:16:43.006Z [debug] [kitsController] Opening kit selection QuickPick
/snap/code/35/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:265 [Extension Host] [vscode-icons] v10.1.1 activated!
/snap/code/35/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:265 [Extension Host] [CMakeTools] 2020-07-01T18:16:44.692Z [debug] [kitsController] User cancelled Kit selection`

- View -> Command Pallette... -> Toggle Shared Process -> Console
`extensionsScanner.ts:61 Uncaught (in promise) Error: EACCES: permission denied, open '/home/venze/.vscode/extensions/.obsolete'
extensionsScanner.ts:72 Uncaught (in promise) Error: EACCES: permission denied, open '/home/venze/.vscode/extensions/.obsolete'
    at extensionsScanner.ts:72
    at async Promise.all (/snap/code/35/usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/index 1)
    at async Promise.all (/snap/code/35/usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/index 1)`
 

- View -> Open View… -> Log (Shared)
`[2020-07-01 19:56:55.314] [sharedprocess] [info] main {"machineId":"710de8f422b5ca4a97ad270e34bf1c6428a69a6aee04c227bdd2a9054ee2a29b","windowId":2}
[2020-07-01 19:57:35.345] [sharedprocess] [info] Starting to clean up unused language packs.
[2020-07-01 20:16:34.178] [sharedprocess] [info] Installing extension: ms-vscode.cpptools
[2020-07-01 20:16:34.197] [sharedprocess] [error] Failed to install extension: ms-vscode.cpptools EACCES: permission denied, open '/home/venze/.vscode/extensions/.obsolete'`

- View -> Open View… -> Log (Window)
`[2020-07-01 19:56:55.849] [renderer1] [error] EACCES: permission denied, open '/home/venze/.vscode/extensions/.obsolete': Error: EACCES: permission denied, open '/home/venze/.vscode/extensions/.obsolete'
    at file:///snap/code/35/usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:545:81
    at async Promise.all (index 1)
[2020-07-01 20:07:34.766] [renderer1] [error] EACCES: permission denied, open '/home/venze/.vscode/extensions/.obsolete': Error: EACCES: permission denied, open '/home/venze/.vscode/extensions/.obsolete'
    at file:///snap/code/35/usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:545:81
    at async Promise.all (index 1)
[2020-07-01 20:16:34.222] [renderer1] [error] EACCES: permission denied, open '/home/venze/.vscode/extensions/.obsolete': scanningUser: EACCES: permission denied, open '/home/venze/.vscode/extensions/.obsolete'
    at file:///snap/code/35/usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:545:81
    at async Promise.all (index 0)
    at async e.installFromGallery (file:///snap/code/35/usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:559:10)
[2020-07-01 20:16:41.361] [renderer1] [error] EACCES: permission denied, open '/home/venze/.vscode/extensions/.obsolete': Error: EACCES: permission denied, open '/home/venze/.vscode/extensions/.obsolete'
    at file:///snap/code/35/usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:545:81
    at async Promise.all (index 1)
`

Thanks for the help!

**Comment by sandy081** [comment]
@anatolyvenzekov It seems you have access (permission) issues with the extensions dir where extensions are installed.

> extensionsScanner.ts:61 Uncaught (in promise) Error: EACCES: permission denied, open '/home/venze/.vscode/extensions/.obsolete'

Providing access to the extensions folder will fix this.
