### ISSUE TITLE
"editor.semanticHighlighting.enabled": true hard to override by users

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#101498]
Refs: https://github.com/microsoft/vscode/issues/101316

As in the testplan have a sematnic langauge extension sample which contributes:
```
"configurationDefaults": {
			"[semanticLanguage]": {
				"editor.semanticHighlighting.enabled": true
			}
		}
```

Run the extension. And now if the user wants to disable semantic highlighting he has to write the following in his settings
```
"[semanticLanguage]": {
		"editor.semanticHighlighting.enabled": false
	},
```

That is the only setting which will have priroity over what extension set.

I find this a bit cumbersome.
As the global
editor.semanticHighlighting.enabled should have prioritiy over any default, even it is a language setting default

**Comment by aeschli** [comment]
Yes, your observation is correct, the user is bsically forced to have semanticHighlighting enabled.

The reason is that some languages very much depend on semantic highlighting as their TextMate grammar are limited due to the language's syntax. Some language want to reduce their TextMate grammars to a minimum.
It will not be in the users interest to turn semantic highlighting for that langauge off.

So I think it's ok that this will be be more cumbersome.

**Comment by isidorn** [comment]
Yes if the feature works well I think it is perfectly fine we force it on the users. Or as a workaround they have to change theme.

**Comment by aeschli** [comment]
No action planed.
