### ISSUE TITLE
Issue hover should not go away this easy

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#101495]
Refs: microsoft/vscode-pull-request-github#1937

Open issues view. Hover over an issue -> the issue hover shows up - great!
Now use the mouse to hover quickly outside of the hover, and quickly move it back to hover over the same issue.
Notice how the issue hover, goes away and quickly comes back.

Idealy it should be smarter (like the issue hover in the editor) and that you do not even hide it in this case. Thus not having this ui flash.

**Comment by alexr00** [comment]
@Tyriar is this more properly addressed in the hover service?

**Comment by Tyriar** [comment]
@isidorn do you expect some delay allowing you to mouse out and mouse back in? Note that GitHub doesn't have that.

**Comment by isidorn** [comment]
@Tyriar I expect it to behave the same way the issue hover behaves in the vscode editor.
So yeah some delay allowing mouse out and mouse back in.

**Comment by Tyriar** [comment]
Oh I see the flash now, I think there's an issue with the implementation in issues then. @alexr00 have you set up your hover target to be an element the size of the full list item without a gap between it and the hover?

**Comment by alexr00** [comment]
I think this is the flash:
![recording](https://user-images.githubusercontent.com/38270282/86254392-05903400-bbb6-11ea-9b6c-ad4246cc007a.gif)
but, @isidorn you say that you move the mouse outside the hover, so is that not the flash you're seeing?

What is happening in that gif is that on mouse over of the tree item, I call `showHover`. The mouse then leaves, and enters the hover. When the mouse is once again over the tree item, I show the hover again because all I know is that the mouse left and came back. 

> have you set up your hover target to be an element the size of the full list item without a gap between it and the hover?
@Tyriar I'm not sure about this. Doesn't the hover already position itself around the target element?

**Comment by alexr00** [comment]
Thanks to a tip from @Tyriar, the flash in the gif is easily fixed.

**Comment by isidorn** [comment]
@alexr00 that is the flash I was refering to. Thanks for fixing it, I will verify tomorrow.
