### ISSUE TITLE
VSCode 1.46.1: Failed to install 'ms-python.python'

### ISSUE THREAD

**Issue by mojiwa** [microsoft/vscode#101472]
- VSCode Version: 1.46.1
- OS Version: Windows 10 Pro x64 10.0.18363

Steps to Reproduce:

This has happened for some time, and I've seen other issues raised for other versions of VS Code, but it's still happening on 1.46.1 for me.
The only solution is to download the extension manually and install it that way.
I had reported this to vscode-python, but they told me to raise it here.

Try to update Python from the side-bar
or
Try to install Python from the side-bar
or
Try to update Python from the notification window
or
Try to install or update Python from Extension:Python page

I get this:
![image](https://user-images.githubusercontent.com/14992663/86205126-077bd800-bb61-11ea-8c0f-612c99105a51.png)

```
[2020-06-30 06:59:21.986] [sharedprocess] [info] Installing extension: ms-python.python
[2020-06-30 06:59:22.047] [sharedprocess] [error] Failed to install extension: ms-python.python 
```

Does this issue occur when all extensions are disabled?: N/A (installing an extension is the issue)

**Comment by sandy081** [comment]
Please follow these steps

- Help -> Toggle Developer Tools -> Network
- Then check for any network failed requests while browsing and installing the extensions if found all requests fails then its probably a proxy or DNS issue at your end.
- To confirm its a DNS issue check if you can access this page https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default, if you cannot please try configuring your DNS like pointing to 1.1.1.1 as suggested here? https://1.1.1.1/dns/. Otherwise please contact your network administrator.
- If it is not a network issue, please share the logs from the following locations
    - Help -> Toggle Developer Tools -> Console
    - View -> Command Pallette... -> Toggle Shared Process -> Console
    - View -> Open View… -> Log (Shared)
    - View -> Open View… -> Log (Window)
