### ISSUE TITLE
Add bottom margin to issue hover

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#101496]
Refs: microsoft/vscode-pull-request-github#1937

Hover over na issue
Notice how there is not a lot of bottom padding -> this gives a wrong visual impression to the user that the bottom is clipped and that he should scroll down - which is not true.
I suggest to add 2px more padding to the bottom.

![Screenshot 2020-07-01 at 11 35 22](https://user-images.githubusercontent.com/1926584/86229153-9a336b80-bb8f-11ea-963f-9de7b9b9e862.png)

**Comment by alexr00** [comment]
I think this should be addressed in the hover service, since all the tree is doing is passing markdown to that.

**Comment by isidorn** [comment]
Yeah this is also visible in the hover in the editor.

**Comment by Tyriar** [comment]
The padding is just right for terminal links:

![image](https://user-images.githubusercontent.com/2193314/86244061-393e7000-bb5c-11ea-9a66-3da34d36b090.png)

It looks like the background around the text is drawing into that padding?

**Comment by alexr00** [comment]
I don't think it is:
![image](https://user-images.githubusercontent.com/38270282/86245136-59485080-bba9-11ea-9b02-ea1dd7609908.png)

The padding at the top is larger than that on the bottom.

**Comment by Tyriar** [comment]
I don't think @isidorn is complaining about a 1px gap though, which is possibly due to the font anyway. The reason the original screenshot looks weird is because the background takes up 4 out of 8 pixels in the bottom padding. It should look like the left side of this:

![image](https://user-images.githubusercontent.com/2193314/86251721-1796b600-bb67-11ea-90f5-14a3321aeb95.png)

**Comment by alexr00** [comment]
Makes sense. This is not solvable with the current API, since the extension API just takes markdown and passes that into the hover. 
To solve this, we would need to change the style that markdown is rendered with in the core when a span has a background color. This is probably going to be a long discussion.

**Comment by Tyriar** [comment]
@alexr00 quick fix seems to be adding this to the spans: `display: inline-block; margin-bottom: 4px`, not sure what the right fix is though.

**Comment by alexr00** [comment]
It seems that a larger bottom margin on the spans would be an improvement even when the spans are not on the last line:
![image](https://user-images.githubusercontent.com/38270282/91425423-6907ac80-e85b-11ea-9c95-b51c92546360.png)

@mattbierner do you know of a good way to add that bottom margin to the rendered markdown?

**Comment by mjbvz** [comment]
Maybe try adding a `<br>` tag or two to insert fake whitespace at the end of the hover? There's not a native way to adjust padding in markdown

**Comment by alexr00** [comment]
@mjbvz I was thinking that we adjust the css to add a little more padding to bottom of all spans in the hover. Adding a <br> goes too far in the other direction with too much whitespace.

**Comment by mjbvz** [comment]
@alexr00 Sure. Try adding some padding or adjusting the line height to see if that makes it look better
