### ISSUE TITLE
do not show twistie for a childless compressed node

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#101431]
Testing #101009

An uncompressed debug session tree shows twisties only where it makes sense:
<img width="346" alt="2020-06-30_18-40-53" src="https://user-images.githubusercontent.com/1898161/86153324-ca342d80-bb01-11ea-94b1-30a3a26bc78b.png">

The corresponding compressed tree shows a twistie despite the fact that it is really the "leaf" from the uncompressed tree:
<img width="339" alt="2020-06-30_18-42-40" src="https://user-images.githubusercontent.com/1898161/86153399-ea63ec80-bb01-11ea-9733-2ca5f0f18c84.png">

**Comment by connor4312** [comment]
I was about to open an issue for this. I can reproduce this by having a parent session that spawns and unspawns a child, specifically running this script via launch config or the debug terminal: https://github.com/microsoft/vscode-js-debug/blob/master/demos/node/parent.js

**Comment by isidorn** [comment]
Well I automatically expand all parent sessions so the compressed state would be immediatly visible..
I also introduced a check to not auto expand the same session twice so that user can explicitlyt collapse something.
I just change the logic now that we allow to auto collapse a session if it has a new child element - what seem to be the case here.
