### ISSUE TITLE
Allow notifications to have newlines

### ISSUE THREAD

**Issue by katelynienaber** [microsoft/vscode#101589]
I would like to be able to use newlines in the notifications.

I know it has already been rejected [here](https://github.com/Microsoft/vscode/issues/48900), but the VSCode native alerts are able to have multi-line comments, so why isn't this an option for the extensions? If `"Notifications are imho not the right place to show structured text with formatting"`, then where else are we supposed to show complex notifications? Is there any other available location in VSCode?

Also I would argue that multi-line notifications are a pretty basic thing. I am not asking for the ability to add sixteen colors and a cursive font, I just need to be able to, say, make a confirmation message which shows the contents of an object in a structured way, for example.

And I am [not the only one who still wants this](https://stackoverflow.com/questions/54300025/how-to-newline-in-vscode-window-showinformationmessage).

Therefore opening this as a feature request again.

**Comment by RandomFractals** [comment]
this can't be a good reason to strip out new lines

```
// Remove newlines from messages as we do not support that and it makes link parsing hard
		message = message.replace(/(\r\n|\n|\r)/gm, ' ').trim();
```

Please reopen.

**Comment by RandomFractals** [comment]
well, good IDEs allow notification messages that contain paragraphs of text for more info.

not sure why this is such a big deal, or what that links parsing comment has to do with this change & such a simple request.

**Comment by eamodio** [comment]
@bpasero Why is this out of scope? This has been asked for by the community many times, and imo feels like a very reasonable request. What is the main objection here?

**Comment by bpasero** [comment]
I feel that notifications are not a good place to show a lot of information. The text should be short and concise. Allowing to use newlines and potentially other formatting only asks for larger notifications that consume even more space. 

Does that make sense?

**Comment by eamodio** [comment]
While I agree with the sentiment and don't want to have larger notifications, the ability of adding a newline or so can often improve readability and user-experience. The space is still constrained so packing too much content would still be highly discouraged. Also, we aren't talking about other formatting here.

**Comment by katelynienaber** [comment]
> I feel that notifications are not a good place to show a lot of information. The text should be short and concise. Allowing to use newlines and potentially other formatting only asks for larger notifications that consume even more space.
> 
> Does that make sense?

@bpasero Isn't that up to us? If we design our extensions badly and the alerts are obnoxiously big, then people just won't use our extension...

**Comment by bpasero** [comment]
Let me bring this to the UX call and then report back the decision here. Depending on that call we may either close or leave the issue open.

**Comment by bpasero** [comment]
@katelynienaber 

> @bpasero Isn't that up to us? If we design our extensions badly and the alerts are obnoxiously big, then people just won't use our extension...

That is not a good argument. Every extension author feels that their extension is the best and greatest and deserves notifications with lots of text to tell the user. The user may not agree but may also not have any alternative (e.g. imagine this was the one and only Python extension or C++). We would at least need https://github.com/microsoft/vscode/issues/41767 so that the user can stop an extension from spamming.

**Comment by misolori** [comment]
I'd be curious to know what the use cases are here. If all we're wanting to do is improve the readability of notifications, then I think we can look at how other systems structure their notifications:

```
Title
Detail
Message
[Actions]
```

<img width="500" src="https://user-images.githubusercontent.com/35271042/97998174-a1b58c00-1d9e-11eb-83d2-0337486f7719.png">

<img width="500" src="https://user-images.githubusercontent.com/35271042/97998216-ada14e00-1d9e-11eb-90ef-f7a50bbe89d8.png">

**Comment by RandomFractals** [comment]
I don't know if Slack and Windows notifications are good examples of UX for IDE notifications.

I would agree that in the short form that toast would display message type (info, warning, error), perhaps an ext. name it's coming from & the 1st line of text with ... in a collapsed state.

However, there are instances when we'd like to display a notification, like an error, where we would provide brief error description, & more information on the new line, if that makes sense.

**Comment by misolori** [comment]
@RandomFractals I don't know, you're comparing a single tool vs multiple platforms that use the same pattern. If you have other examples of better notifications please do share them.

Notifications are intended to be short and concise so that the user can act upon it. If they need more information, there should be an action to see that information. I don't believe we should try to cram too much information here.

**Comment by RandomFractals** [comment]
I don't have a better example. I believe I described the typical use case & notifications in the current form don't support it.

It doesn't sound like you are willing to provide that option, or formatted messages in notifications. So, feel free to close it.

Thanks!

**Comment by fabiospampinato** [comment]
IMO a decent compromise would be to allow a title and a body, but disallowing newlines in the body. There are some use cases where a single uninterrupted line of text just isn't the best way to preset some information. I don't agree that bodies shouldn't be able to use newlines at all, but at least having 2 lines should cover a good chunk of use cases.

**Comment by capaj** [comment]
Two lines FTW.

**Comment by md-base-t** [comment]
The problem is simply that line breaks are not displayed even when the user decides: "This is a message I want to read more about!" - and he/she presses the `^` button to expand the notification. This would not happen if it was spam, but even there the entire text remains unstructured on one line.

**Comment by Muhammad-Mohsen** [comment]
> That is not a good argument. Every extension author feels that their extension is the best and greatest and deserves notifications with lots of text to tell the user. The user may not agree but may also not have any alternative (e.g. imagine this was the one and only Python extension or C++). We would at least need https://github.com/microsoft/vscode/issues/41767 so that the user can stop an extension from spamming

It's extremely amusing to think that the only thing standing in the way of useful-extensions-with-no-alternatives bombarding the living hell out of their poor users with chungus notifications is stripping new lines 👍 👍 

Especially since this is allowed!!!!
![Image](https://github.com/user-attachments/assets/77d65676-1c93-4ec8-b23b-823eaab20d79)

What are we talking about here??!

**Comment by capaj** [comment]
> It's extremely amusing

To me it's more sad than amusing. Needless constraints like this are going to pile up and be the downfall of vscode one day.

**Comment by Muhammad-Mohsen** [comment]
@bpasero I'm not sure how/why is this acceptable, then.
![Image](https://github.com/user-attachments/assets/946f1487-7835-442b-91a0-29c117c276d2)
Like I said, amusing!!

**Comment by gmkado** [comment]
Copilot recommends adding a "Details" button that the user can click to get another notification with more details.  But then the notification doesn't disappear since it is waiting for user input.

I agree with others, it seems like trying to force developers into these constraints (with no obvious alternative) just leads to a worse user experience.
