### ISSUE TITLE
Cut & Copy does not work on iPad OS

### ISSUE THREAD

**Issue by daybrush** [microsoft/vscode#101564]
- VSCode Version: 1.45.1
- OS Version: iPad 13.5

Steps to Reproduce:

I found in this part that forcibly returned empty. 

https://github.com/microsoft/vscode/blob/1fd395773f9f09e86fcb78fa3db8aff6f02960c7/src/vs/editor/browser/controller/textAreaHandler.ts#L182-L188

Is there a reason? If I remove this part, it works fine.

The currentState contains the selection range and cursor position.

TextAreaState is forcibly empty, so the textarea value and selection range cannot be updated.

**Comment by TylerLeonhardt** [comment]
I tried this in Codespaces (insiders) and I just can't get it to work.

* No keybindings work (Cmd + C/V or Ctrl + C/V)
* The `Edit -> Copy` menu item doesn't seem to copy (I pasted using the paste button in the keyboard and it didn't paste what I copied)

I'm fairly new to iPad but I figured at least one of these methods would have worked so I'm reopening.

**Comment by bpasero** [comment]
@TylerLeonhardt for me it works just fine on https://vscode-web-test-playground.azurewebsites.net/?enter=true at least, can you try there?

**Comment by isidorn** [comment]
Also assigning to me so I try it out on Monday (do not have an iPad with me today).

**Comment by TylerLeonhardt** [comment]
Interesting... so when I select some text in the playground, I get the copy and paste buttons and they work as expected (although my shitty Bluetooth keyboard doesn't seem to work... Ctrl/cmd +c/v don't work)
![image](https://user-images.githubusercontent.com/2644648/128582382-cd652d67-ed4f-4fec-acfe-d34b25d7f0af.png)

However in Codespaces, I select some text and the copy button is not rendered. Paste does work as expected:
![image](https://user-images.githubusercontent.com/2644648/128582424-1a0e3c06-6a35-4ad9-9e70-8bd849090968.png)

I'm really not sure why this would be the case... seems unusual...

**Comment by bpasero** [comment]
Oh btw I tried this with a physical external keyboard to the iPad, not the on screen keyboard.

**Comment by isidorn** [comment]
I have just tried the following and all works on my iPad, safari, web:
1. Copy / paste using external mouse
2. Copy / paste using on screen keyboard
3. Copy / paste using external keyboard
4. Copy / paste using touch context menu


As for copy not being present on the screen keyboard, I also did not see that. 
@TylerLeonhardt can you maybe create a follow up issue, since this one seems to be about copy /paste on iPad in general which seems to work.

So all seems good. Closing for now, if somebody from the community is also seeing issue with copy/paste please let me know and I can reopen. Thanks!
