### ISSUE TITLE
Font size changes while scrolling via trackpad

### ISSUE THREAD

**Issue by esviza** [microsoft/vscode#101571]
Issue Type: <b>Bug</b>

On macOS. I have the option that you can change fontsize on the fly with the command key, a nice feature of Visual Studio Code. 

Open a file with many lines so you can see the problem. About ~1000 lines.

Use trackpad to "push" scroll to any direction (up or down). The file will start scrolling and you can feel the "inertia" effect: the scrolling will last even if your hand is not touching the trackpad. Nice effect for me.

Repeat the operation, but when the file is in middle of the inertia-scrolling press the command key. The fontsize will change because it thinks you are changing it via the command key.

Is somebit tedious because in macOs you must use command-tab to change between applications, and is common that you want to scroll the file, then rapid-change between applications for something. In all that moments you are "scrolling" and press the command key the fontsize will change and you must to re-adjust it.

best regards

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:17:14.222Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (5.79GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by JacksonKearl** [comment]
What setting are you using to change font size with scroll?

**Comment by esviza** [comment]
This one. 
```
// Zoom the font of the editor when using mouse wheel and holding `Ctrl`.
  "editor.mouseWheelZoom": true,
```

**Comment by esviza** [comment]
On Firefox, for example, you have that function too: hold command key, then use the trackpad-scroll up and down in order to increment or decrement the zoom.  The macOs inertial effect is the same, BUT they manage to "guess" somehow if the user have release the command key, so if you press it again in the middle of the intertial effect, zoom won't change.

**Comment by alexdima** [comment]
@esviza This is exactly the reason why this setting is not on by default. 

We basically cannot distinguish in the incoming `mousewheel` events if the scrolling happened via a physical mouse wheel or via the touchpad. So, on laptops, people hit this accidentally super often. So that is why the setting is off by default.

**Comment by imthenachoman** [comment]
@alexdima 

I don't know the technical workings but how do other apps handle this? For example, in Chrome or FF, if I scroll and let the inertia keep scrolling, even if I press CTRL it won't zoom. Yet if I do it in VS Code then it will zoom.

**Comment by alexdima** [comment]
@imthenachoman I'm not sure, perhaps the OS gives more properties to the event but those properties are not present in the `wheel` event that the browser creates? For example, the low level event could indicate if the scroll is part of inertia or not or that a single `wheel` event is part of a larger animation. I think in this particular case, on our side we would get individual events like the following:
* `wheel` event with `ctrlKey`: `false`
* `wheel` event with `ctrlKey`: `false`
* `keydown` event for `ctrlKey`
* `wheel` event with `ctrlKey`: `true`
* `wheel` event with `ctrlKey`: `true`
I don't think there is a property on the `wheel` events to let us know that the last two wheel events need to be ignored because they are part of inertia. We could add something like if you press `ctrl`, then ignore the next wheel events for 50ms, but what if the next `wheel` event is a legitimate one where you first start with `ctrl` and then do the `wheel`. I am open to ideas / PRs to improve this.

**Comment by imthenachoman** [comment]
It must be present since Chrome/Firefox handle it fine. I will see if I can research this more. Thanks!
