### ISSUE TITLE
Commands placed in `scm/title` don't always receive the correct args

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#101631]
If there are multiple source controls, then the command will receive the associated `SourceControl` object as its args, but if there is only 1 source control, then no args will be received.

**Comment by joaomoreno** [comment]
@sbatten I believe I'm doing the right right in here: https://github.com/microsoft/vscode/blob/7465af961f29aaf418aabc54d3a581269f4a1178/src/vs/workbench/contrib/scm/browser/scmViewPane.ts#L1773-L1773

But this isn't being respected by the workbench:

- https://github.com/microsoft/vscode/blob/e7279b1c505569c52d9f813b9c76476374001db0/src/vs/workbench/browser/parts/compositePart.ts#L444-L444
- just goes here: https://github.com/microsoft/vscode/blob/e7279b1c505569c52d9f813b9c76476374001db0/src/vs/workbench/browser/composite.ts#L185-L185

And I see no way to override that since neither my SCMViewPane nor SCMViewPaneContainer is a Composite.

**Comment by sbatten** [comment]
Need to look

**Comment by connor4312** [comment]
@eamodio it's probably easier for you to verify this :)

**Comment by eamodio** [comment]
Yup, verified
