### ISSUE TITLE
Always mark the file is unsaved after clicking Command + s to save the file.

### ISSUE THREAD

**Issue by wingwing2012** [Microsoft/vscode#10169]
- VSCode Version: Code - Insiders 1.4.0-insider (e3758d2cdaae78082a08a45ae28ea1bed5f47e8c, 2016-08-01T14:05:40.554Z)
- OS Version: Darwin x64 15.6.0

Steps to Reproduce:

1. Change some file in the editor.
2. Click command+s to save the editor.
3. The file is always marked as unsaved.
4. When I close this file, the dialog popped up that needing to save the file again.

**Comment by bpasero** [comment]
I am very sorry to hear you are having issues with VS Code. I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by wingwing2012** [comment]
Yes. With the  --disable-extensions, I can not reproduce this issue. Could you please tell me which extension is the one which leading this issue:
![image](https://cloud.githubusercontent.com/assets/7115702/17552449/9fe23830-5f32-11e6-9683-8fa3eeb4f686.png)

**Comment by bpasero** [comment]
@jrieken @alexandrudima can you help him?

**Comment by jrieken** [comment]
I would blame one of the formatter extensions (js-css-htm-formatter)
