### ISSUE TITLE
Debugger: debug.inlineValues support for case insensitive variable names 

### ISSUE THREAD

**Issue by chrisdp** [microsoft/vscode#101797]
Hey, I am working on a debugger for a case insensitive language. When looking into the source I didn't see any way to define the expressions as case insensitive.  https://github.com/microsoft/vscode/blob/193483676699fcbde88f7a7748b189cb2bda7efe/src/vs/workbench/contrib/debug/browser/debugEditorContribution.ts#L79

With `debug.inlineValues` set to `true` I can’t get camel case vars to work. In the below example you can see we have the value for `postdata` but it won’t match `postData` in the code even though they are the same reference.

![image](https://user-images.githubusercontent.com/9591618/86607665-ef042700-bf7f-11ea-8032-cab6e900ff57.png)

As an extension maintainer and/or author we would like to be able to define ether the language as a whole as case insensitive or the scope/variables themselves.

**Comment by weinand** [comment]
Yes, this is a valid feature request.

**Comment by isidorn** [comment]
A debug adapter could for example specify this using a `capability`. Or alternativly we could change the `debug.inlineValues` to be a string setting so the user or an extension could change it to be case insensitive. I prefer the `capability` approach.

**Comment by weinand** [comment]
IMO the debug adapter is not in a good position to know about case sensitivity because it has no syntax knowledge of the source language because it doesn't take transpilation into account (e.g. CoffeeScript, TypeScript -> JavaScript).

I'm currently looking into this problem in a broader way: similar to what we did for debug hovers with the `EvaluatableExpressionProvider`, I'm trying to do design an `InlineValueProvider` that can be contributed by a language extension.

**Comment by isidorn** [comment]
@weinand that sounds like a great approach. However why do we need a separate thing for the Inline values, can we just reuse what you already did for the debug hovers with the `EvaluatableExpressionProvider`?

**Comment by weinand** [comment]
@isidorn yes, that's exactly what my protoyping tries to find out: do we need a new abstraction or could we just use a variant for the `EvaluatableExpressionProvider`. Since the `EvaluatableExpressionProvider` uses the mouse position, it is not a very efficient way to find all inline expressions by probing for each character position in a line of source. In addition there is now way to figure out whether an evaluatable expression for one position is the same as for the next position...

**Comment by isidorn** [comment]
@weinand yeah that feels like a way to go here. Just a new method `provideEvaluatableExpressionForLine` on the `EvaluatableExpressionProvider`

**Comment by weinand** [comment]
Since it is a bigger effort to provide extension API for the debugger's "inline values" feature, I've created a new feature request #105690.

**Comment by weinand** [comment]
I've released a first cut of the "inline values provider" implementation which should make it possible to address this issue.

What you need to do:
implement an `InlineValueProvider` for your language that locates variables in the given lines of a document and return them from the provider as an array of `InlineValueVariableLookup` objects. VS Code will match them against the variables in the VARIABLE view to find their values. When creating the `InlineValueVariableLookup` object you can use the constructor argument `caseSensitiveLookup` to control how the lookup should be done.

**Comment by chrisdp** [comment]
@weinand Thanks! Thats great I'll take a look over the next few days.

**Comment by weinand** [comment]
@chrisdp I will provide more infos and a sample when preparing the release notes next week.

**Comment by chrisdp** [comment]
> @chrisdp I will provide more infos and a sample when preparing the release notes next week.

That is perfect. I'll wait for that to drop then. Thanks!

**Comment by weinand** [comment]
@chrisdp a sample that shows a case sensitive variable name lookup appears in the [release notes](https://github.com/microsoft/vscode-docs/blob/vnext/release-notes/v1_54.md#inline-value-provider-api) of the upcoming 1.54 release. In order to make it case-insensitive you need to pass the value `false` as a third argument to the `InlineValueVariableLookup` constructor.
In a addition you will need a regular expression that finds the variables in your language.

**Comment by chrisdp** [comment]
@weinand Thanks. I saw that and let the other maintainer of the extension we are working on know. Hopefully we will be able to take a look soon ™️  and give some feedback 👍

**Comment by weinand** [comment]
I'm closing this because we have addressed the problem by introduction of the Inline Values Provider API.
