### ISSUE TITLE
quick find symbol finder shows 'no matching results' after backspace

### ISSUE THREAD

**Issue by azdavis** [microsoft/vscode#101708]
- VSCode Version: 1.47.0-insider
- OS Version: macOS 10.15.5

## Steps to reproduce

1. make a new folder 'foo'
1. make a new file 'bar.ts' in 'foo' with contents 'const quz = 3;'
1. open the folder 'foo' in VSCode
1. bring up the quick finder
1. type 'bar@'
1. note that the symbol finder for 'bar.ts' has been brought up, with one entry 'quz'
1. type 'foo'
1. note that no results are found
1. delete 'foo'

## Expected results

the symbol finder list goes back to showing all the symbols for the file

## Actual results

the symbol finder continues saying no results are found

video: https://www.dropbox.com/s/trc3k6oirc88mn3/bug.mov?dl=0

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
Good catch, this is due to this check:

https://github.com/microsoft/vscode/blob/2e8b1458ad9fc6df9783cb1d20d888d25e73b119/src/vs/workbench/contrib/search/browser/anythingQuickAccess.ts#L759

Because the "No Results" message comes up from:

https://github.com/microsoft/vscode/blob/2e8b1458ad9fc6df9783cb1d20d888d25e73b119/src/vs/workbench/contrib/search/browser/anythingQuickAccess.ts#L177

Up for grab.
