### ISSUE TITLE
Support linked undo operations

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#101789]
This is left-over work from composite undo and describes the problem that you cannot undo a Java class rename in one operation but need two undo's.

**Comment by joaomoreno** [comment]
Pushing out to August.

**Comment by rebornix** [comment]
One use case from notebook, to split a cell by cursor position, what we do now is

* delete content after the cursor in the cell
* insert new cells into the notebook document

right now when performing above two operations, we explicitly ask them not to push undo elements into the stack, and we create a custom undo element instead. It would be simpler with linking two undo operations.

**Comment by rebornix** [comment]
@alexdima @jrieken it seems there is an issue with edits with the same undo/redo comparison key in the same group, I tried to apply bulk edits like

```ts
await this._bulkEditService.apply(
	[
		new ResourceTextEdit(cell.uri, { range: textModel.getFullModelRange(), text: newLinesContents[0] }),
		new ResourceNotebookCellEdit(this._notebook.uri,
			{
				editType: CellEditType.Replace,
				index: index + 1,
				count: 0,
				cells: newLinesContents.slice(1).map(line => ({
					cellKind: kind,
					language,
					source: line,
					outputs: [],
					metadata: {}
				}))
			}
		)
	],
	{ quotableLabel: 'Split Notebook Cell' }
);
```

The first edit is happening on `file:///.../api.github-issues#00001` and the second edit is on `file:///.../api.github-issues`, and their comparison key is the same. When performing Undo, it seems it will only undo edit one by one instead of undoing them all.

**Comment by rebornix** [comment]
Undo with above setup will not run into this code path

https://github.com/microsoft/vscode/blob/6891688dfcf28d45519bfac271134660b870986d/src/vs/platform/undoRedo/common/undoRedoService.ts#L1038-L1042

**Comment by alexdima** [comment]
@rebornix I did not adopt the undo redo grouping for `ResourceNotebookCellEdit`, basically the call to `IUndoRedoService,pushUndo` must also pass in the exact same `UndoRedoGroup` instance.

**Comment by rebornix** [comment]
@alexdima right I did that (passing the undoRedoGroup created by the BulkEdit service to ResourceNotebookCellEdit at the end) https://github.com/microsoft/vscode/commit/3222df5c5a362a59962a8c1c53e2c252bed35277 but still saw this issue.

**Comment by alexdima** [comment]
I can try debugging if you could tell me the exact repro steps or you can try debugging by using `const DEBUG = true` in `src/vs/platform/undoRedo/common/undoRedoService.ts`

**Comment by rebornix** [comment]
@alexdima thanks, `DEBUG` helps me figure out why these edits are in two different groups. The bulk edit (https://github.com/microsoft/vscode/issues/101789#issuecomment-699063512) includes a text edit and a notebook edit, and we pass in the same undoRedo group. However when applying the text edit, since `tasks.length === 1`, it does not use the undoRedo group passed in (if there are more than one text edit, they then are put in the same group).

https://github.com/microsoft/vscode/blob/4aa873b4d18136dc5bd6622b1b2eb3335c99ebbc/src/vs/workbench/contrib/bulkEdit/browser/bulkTextEdits.ts#L215-L239

**Comment by alexdima** [comment]
@jrieken Can you please help here? I think this is something specific about `bulkTextEdits.ts` , like in this very special case it should behave as a cross file edit and not as a single file edit.

**Comment by jrieken** [comment]
@alexdima Is there any harm if the simple path (task.length === 1) is being removed and we always go through the service?

**Comment by alexdima** [comment]
@jrieken I think it should be fine, but I suggest we do it in the debt week, and test it out a bit. Maybe you have a way to find out this special use-case where the text edit is a part of a larger bulk edit and only do it then?

I think many extensions use some vscode API that ends up here with a single file (e.g. liveshare that I know about), and pushing multi edit stack elements with a single buffer will work, but it might end up always prompting in the undo case ("undo across all files?" even if it is a single file).

**Comment by jrieken** [comment]
created https://github.com/microsoft/vscode/issues/107677 for the follow-up work
