### ISSUE TITLE
Delay between starting a rename and the input gaining focus

### ISSUE THREAD

**Issue by wkronemeijer** [microsoft/vscode#101749]
Issue Type: <b>Bug</b>

There is a small delay between starting a rename operation, and the input gaining focus. Any input during this delay will dismiss the input.

Stops to reproduce: 
1. Create a new file test.ts, with the following contents:
    ```ts
    const variable = "initializer";
    ```
2. Place the cursor on `variable`.
3. Press F2 (to rename) and End quickly after each other.

Expected results: 
* The input box appears, and the cursor jumps to the end of input.  

Actual result: 
* The input box appears, but is immediately dismissed, and the cursor jumps to the end of the line (in the file, not in the input).

The delay is small, but if you are fast enough with the inputs, you can get between the box appearing and the box gaining focus. From my short testing, this is shared with all languages that support a rename \<identifier> operation.

VS Code version: Code - Insiders 1.47.0-insider (376d9d9d785ccca128fdbb16f001446d0ad64d32, 2020-07-03T10:27:06.804Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz (4 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.96GB (1.96GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by jrieken** [comment]
Yes. When rename is triggered code checks first if the current location is a valid rename-able symbol and what range actually should be renamed. Because this involves extensions it async. However, we also don't prevent or ignore further typing but after 250ms you'll see progress being reported. 

I don't think there is anything we can do for this, but I am open for suggestions

**Comment by wkronemeijer** [comment]
I understand why it must be async, but at the same time it feels as if there is a speed limit to editing. No idea how feasable any of this is, but maybe buffer text editing inputs for those 250ms? If rename is possible after the delay, apply them to the input, otherwise apply to them to the file. Starting a rename is not done accidently, so normal editing should never have a delay.

**Comment by IanBellomy** [comment]
> Yes. When rename is triggered code checks first if the current location is a valid rename-able symbol and what range actually should be renamed. Because this involves extensions it async. However, we also don't prevent or ignore further typing but after 250ms you'll see progress being reported.
> 
> I don't think there is anything we can do for this, but I am open for suggestions

It seems to me that that option (or similarly contingent options) shouldn't be selectable in the first place if the selected text isn't valid for the operation, i.e. the check should run _before_ the user can make the selection, likely during dropdown open (if not during selection). 

Obviously running that check (and others) during dropdown open may entail non-trivial overhead (if not a necessary small delay do to async) and given that the dropdown must open immediately it means that the items in it (like 'rename symbol') may need an initial temporary visual state to indicate that their availability is uncertain. 

Alternatively, from a UI perspective, as far as I can tell, it's only essential that the completes before the user input is confirmed (rather than begun), i.e. it's fine if it runs concurrently with (or even after) switching focus to the opening pop-up. 

In such a case, if the check determines in mid-input that the item is not a valid target, the state of the pop-up can change to dim 'not-allowed' style, the 'you can not rename...' flag can be displayed above, and subsequent input confirmation resolve to a no-op.

In the case a user manages to finish their input before the check is complete, a 'spinner' or similar should appear, resolving to the change or the error flag per the outcome of the check. 

Lastly, any safety inherent in performing the check on drop-down section is being undermined by the delay, potentially resulting in the same confusing/unexpected state (an edit in one place). So while it may be preventing a 'bad action' it's created a new one that appears in both the problematic and ideal  circumstances.
