### ISSUE TITLE
Broken shell script highlighting for array elements used as an array index

### ISSUE THREAD

**Issue by foreignmeloman** [microsoft/vscode#101716]
Version: 1.47.0-insider (user setup)
Commit: 376d9d9d785ccca128fdbb16f001446d0ad64d32
Date: 2020-07-03T10:27:06.804Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.16299

Steps to Reproduce:

Seems like vscode struggles with highlighting bash syntax correctly when array elements are used as an array index.
Example code:
```bash
echo ${a[${b[0]}]}
```
As you can see the last two symbols are not colored correctly:
![image](https://user-images.githubusercontent.com/11769352/86513399-f52cc300-be1a-11ea-936b-1890688885a3.png)

This will only be visible with themes that have additional highlighting of some elements like the default Dark+.
I think that the closing square bracket in `${b[0]}` is causing the issue, since when you remove the square brackets the highlighting goes back to normal:
![image](https://user-images.githubusercontent.com/11769352/86513554-1cd05b00-be1c-11ea-8fac-81b7829b31ee.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexr00** [comment]
Thank you for filing this issue. It is a problem with the grammar we use for shell script syntax highlighting. Specifically, this tokenization is incorrect:
![image](https://user-images.githubusercontent.com/38270282/86590963-e536ef80-bf90-11ea-9675-84a01ff936d0.png)

However, the repository we get the shell script grammar from is no longer maintaining the grammar. I'll leave this bug open so that if we adopt a new grammar it can be addressed.

**Comment by alexr00** [comment]
Linking and closing in favor of https://github.com/microsoft/vscode/issues/77675, which tracks considering a new shellscript grammar.
