### ISSUE TITLE
Key binding namespacing

### ISSUE THREAD

**Issue by adriancuadrado** [microsoft/vscode#101759]
There are too many keybindings in vscode, which leads me to feel unconfortable adding my own because most of the time when I think I found the right keybinding it happens that this keybinding is already used for anytning else. I could remove the problematic keybinding and assign it to my own commands, but then at some point it might happen that the keybinding I unassigned to reassign to my own command could be useful too, so that's why I think it could be a good idea to have keybinding namespaces, which work this way:

1. You select from the command palette which keybinding namespace you want to use, or create your own with a custom name.
2. Once you create your own keybinding namespace, you can assign any keybinding to any command even if that keybinding is already used by another command.
3. If you press a combination of keys, vscode will first check if that keybinding is set in the keybinding namespace you are currently using and execute the command specified for this keybinding in the current keybinding namespace. If there is no keybinding in the current keybinding namespace that match the combination of keys that the user pressed, then vscode will proceed to look to the keybindings that are not assigned to any keyboard namespace.

This way you can have a vscode command executed with a custom keybinding even if that keybinding is already in use by another command, because the namespace in use overrides all keybindings. If you want the default behaviour just tell vscode to stop using your keybinding namespace.

**Comment by JacksonKearl** [comment]
Chorded keybinding can help with this. For instance, I have all my git keybindings under an `alt+g` chord. So:
- `alt+g alt+p`: Push
- `alt+g alt+s`: Sync
- `alt+g alt+c`: Checkout
- `alt+g alt+m`: Checkout Master
- `alt+g alt+u`: Revert last commit
etc.

**Comment by alexdima** [comment]
@adriancuadrado Keybindings do not need to be removed in order to be used. Please see https://code.visualstudio.com/docs/getstarted/keybindings#_advanced-customization for an explanation of how the keybindings rules work in VS Code.

It is possible to support what you describe using custom context keys. e.g.:

```json
{ "key": "ctrl+g", "command": "actions.find", "when": "namespace1 && editorTextFocus" }
```

Normally the condition `namespace1 && editorTextFocus` would never be true because nobody defines the context key `namespace1`. But it is possible to write an extension which invokes the `setContext` vscode command and defines the `namespace1` context. [Here](https://github.com/microsoft/vscode-extension-samples/blob/f2a57780639bce99099d5128db2d3be83012d0c0/vim-sample/src/extension.ts#L233-L248) is an example on how to set a custom context key value from an extension. i.e. `vscode.commands.executeCommand('setContext', 'namespace1', true);`.
