### ISSUE TITLE
Can't Install python extention

### ISSUE THREAD

**Issue by DorsiFlexionDev** [microsoft/vscode#101746]
- VSCode Version:1.46.1
- OS Version:10.0.18363

Can't Install python extention. Tried to download menually and when I installed I got the message: "VSIXInstaller.NoApplicableSKUsException: One or more extensions are for Visual Studio Code. Try installing them in Visual Studio Code"

**Comment by yume-chan** [comment]
![image](https://user-images.githubusercontent.com/1330321/86552287-1f48c700-bf7a-11ea-82db-2b68d2ad645f.png)

Install your downloaded .vsix file from here.

**Comment by sandy081** [comment]
Please follow these steps

- Help -> Toggle Developer Tools -> Network
- Then check for any network failed requests while browsing and installing the extensions if found all requests fails then its probably a proxy or DNS issue at your end.
- To confirm its a DNS issue check if you can access this page https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default, if you cannot please try configuring your DNS like pointing to 1.1.1.1 as suggested here? https://1.1.1.1/dns/. Otherwise please contact your network administrator.
- If it is not a network issue, please share the logs from the following locations
    - Help -> Toggle Developer Tools -> Console
    - View -> Command Pallette... -> Toggle Shared Process -> Console
    - View -> Open View… -> Log (Shared)
    - View -> Open View… -> Log (Window)
