### ISSUE TITLE
VSCode Application is not staying on a particular window(desktop) - macOS

### ISSUE THREAD

**Issue by irangareddy** [microsoft/vscode#101938]
- VSCode Version: 1.46.1
- OS Version: macOS Catalina 10.15.5

Steps to Reproduce:

1. open 2 windows(desktops) on mac  
2. open any app (ex.Safari) on desktop1 which sticks to the particular desktop1 only.
3. but, when you open vscode its not sticking to the particular window(desktop).

Does this issue occur when all extensions are disabled?: Yes/No
Yes

Video Link - https://youtu.be/P27e7mM_-Yw

**Comment by bpasero** [comment]
VSCode is built on top of a large number of components that are not maintained by the VSCode team directly. This includes:
* [Electron](https://github.com/electron/electron) as the cross platform UI framework
* [node.js](https://github.com/nodejs/node) for most integration into the OS
* [Chromium](https://bugs.chromium.org/p/chromium/issues/list) as runtime and rendering engine (HTML, CSS, JS)
* and after all, the operating system VSCode is running on

Reading this issue, it seems to originate not from VSCode itself but rather one of these upstream components. As such, in order to resolve it, it would need to get fixed in the upstream component. I will go ahead and close this issue and kindly ask to report this issue to the upstream component if possible:
* for UI, OS integration: https://github.com/electron/electron
* for Rendering: https://bugs.chromium.org/p/chromium/issues/list
* for file IO: https://github.com/nodejs/node

Thanks for understanding.

**Comment by irangareddy** [comment]
Thanks for the reply, but can you make it clear where should I report my error further?
