### ISSUE TITLE
Freeze when deleting files via trash

### ISSUE THREAD

**Issue by guoyunhe** [microsoft/vscode#101920]
- VSCode Version: 1.46.1
- OS Version: openSUSE Tumbleweed
- TypeScript: 3.7.5 (project) 3.9.4 (vscode)

Steps to Reproduce:

1. `npx create-react-app --typescript --use-npm my-app`
2. `code my-app`
3. Copy paste `App.tsx` file to `App copy.tsx`
4. Delete `App copy.tsx`
5. VS Code window freezes for 5~10 seconds

Does this issue occur when all extensions are disabled?: **No**

**Comment by bpasero** [comment]
Can you follow this wiki and post the results back here to understand more about why performance is so bad for you: https://github.com/Microsoft/vscode/wiki/Performance-Issues

Thanks!

**Comment by guoyunhe** [comment]
I did the "Profiling the Renderer Process":
[CPU-20200708T151518.cpuprofile.zip](https://github.com/microsoft/vscode/files/4890548/CPU-20200708T151518.cpuprofile.zip)

`code --status` doesn't work because when the window freeze, `code --status` doesn't response, too.

**Comment by bpasero** [comment]
Thanks, I see a lot of `idle` unfortunately, which is not code from us:

![image](https://user-images.githubusercontent.com/900690/86918180-94f19600-c126-11ea-914b-005dc34acd7f.png)

Can you install `htop` and monitor which process in VSCode is potentially high CPU? If any?

**Comment by guoyunhe** [comment]
I didn't see any process using high CPU when the window freeze. All processes use < 3% CPU.

**Comment by bpasero** [comment]
@guoyunhe can you try "Shift+Delete" to bypass the trash. Wondering if it could be trash related.

**Comment by guoyunhe** [comment]
Yeah, `Shift+Delete` works smoothly. No freeze.

**Comment by bpasero** [comment]
Moving to Electron then, the issue seems to be that `moveItemToTrash` is slow on Linux.

**Comment by jamezrin** [comment]
The issue is that KDE (why I assume you are using) uses a different electron backend for managing file deletion. 

It's actually super slow when moving files to the trash. 

You can specify the backend globally and fix this issue this way, you can see more in a post I wrote about this: https://jamezrin.name/fix-visual-studio-code-freezing-when-deleting

**Comment by guoyunhe** [comment]
@jamezrin Thanks for the info. I can contact KDE community to see if they can do something on their side.

**Comment by guoyunhe** [comment]
@bpasero could the `moveToTrash()` call be moved from rendering thread to a different thread? Even if the performance is improved in Electron or KDE, the function is not async and can make window no response when deleting a large amount of files.

**Comment by bpasero** [comment]
@guoyunhe currently we do not have a different process that can run this method. If do not want to move it into the electron main process as blocking that process would mean any user interaction is blocked across all windows. I think Electron needs to resolve this, or maybe run it in a different thread if it is known to block.

**Comment by joseluisq** [comment]
Any updates on this? This issue is present for very long time. Should be fixed on #25114?

**Comment by meronokbay** [comment]
I'm running KDE on Arch and I still have the same issue.

**Comment by hrobertson** [comment]
Potential workaround described in this comment on a duplicate issue: https://github.com/microsoft/vscode/issues/90034#issuecomment-582115953
(Setting `ELECTRON_TRASH` environment variable)

**Comment by AlirezaHaghshenas** [comment]
I see that setting an Env variable will probably fix this. Thanks for pointing out.

Is there a plan to make vscode independent of this variable (like packaging the value inside vscode, or any other solution?)

Or at least, update the installation docs for linux to instruct affected users to do this?

**Comment by joseluisq** [comment]
> Potential workaround (works for me) described in this comment on a duplicate issue: [#90034 (comment)](https://github.com/microsoft/vscode/issues/90034#issuecomment-582115953)
> (Setting `ELECTRON_TRASH` environment variable)

Temporary workaround confirmed on ArchLinux + KDE

```sh
export ELECTRON_TRASH=gio
```

**Comment by erenatas** [comment]
I am currently on Kubuntu 20.04, issue still exists.

**Comment by Professor-Paradox** [comment]
> The issue is that KDE (why I assume you are using) uses a different electron backend for managing file deletion.
> 
> It's actually super slow when moving files to the trash.
> 
> You can specify the backend globally and fix this issue this way, you can see more in a post I wrote about this: https://jamezrin.name/fix-visual-studio-code-freezing-when-deleting

Hey this worked after creating a file in the location and making it executable no need to reboot either,Thanks for the fix

**Comment by tomastzn** [comment]
This is not happening all the time on Kubuntu (detailed info below). 
Just after logging in, it works fine. However, at a later point (maybe after laptop is suspended and then resume) it will stop working. I have not figured out yet what sequence of steps leads to delete becoming broken.

Kubuntu info:
```
Operating System: Kubuntu 20.04
KDE Plasma Version: 5.18.5
KDE Frameworks Version: 5.68.0
Qt Version: 5.12.8
Kernel Version: 5.4.0-54-generic
OS Type: 64-bit
Processors: 8 × Intel® Core™ i7-8550U CPU @ 1.80GHz
Memory: 15.4 GiB of RAM
```
VS Code info:
```
Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:31:29.624Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.4.0-54-generic
```

**Comment by resynth1943** [comment]
Can reproduce this with the following system configuration:

- Operating System: Fedora 32
- KDE Plasma Version: 5.18.5
- KDE Frameworks Version: 5.75.0
- Qt Version: 5.14.2
- Kernel Version: 5.9.16-100.fc32.x86_64
- OS Type: 64-bit

Code:

- Version: 1.49.2
- Commit: e5e9e69aed6e1984f7499b7af85b3d05f9a6883a
- Date: 2020-09-25T00:37:34.990Z
- Electron: 9.2.1
- Chrome: 83.0.4103.122
- Node.js: 12.14.1
- V8: 8.3.110.13-electron.0
- OS: Linux x64 5.9.16-100.fc32.x86_64

Shift+Delete fixes the problem, but I'd rather not enable that as the default as I've had VSCode delete an entire project in the past.

**Comment by Professor-Paradox** [comment]
The fix
You can fix this issue by creating a file that gets executed automatically on startup/login. I chose to do it in ~/.config/plasma-workspace/env/electron-trash-gio.sh

Edit that file and put this line

Copy 
export ELECTRON_TRASH=gio
After that, reboot or logout and log back for it to apply.


Try this it worked for me

**Comment by deepak1556** [comment]
@bpasero The root is fixed in the runtime https://github.com/electron/electron/pull/25114, we should adopt the async api to resolve on our end. Please reassign to the owner of this code path. Thanks!

**Comment by bpasero** [comment]
Needs Electron 12 though 👍

**Comment by dbidwell94** [comment]
So to be clear: Shift+Click to fix temporarily until VSCode gets updated to Electron 12? (Manjaro-Linux w/ KDE)

Is there a timeframe for Electron12 update? Thanks for looking into this fellas!

**Comment by TechComet** [comment]
(electron) Sending uncompressed crash reports is deprecated and will be removed in a future version of Electron. Set { compress: true } to opt-in to the new behavior. Crash reports will be uploaded gzipped, which most crash reporting servers support.
/usr/lib/x86_64-linux-gnu/gio/modules/libgiognomeproxy.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgiognomeproxy.so
/usr/lib/x86_64-linux-gnu/gio/modules/libgvfsdbus.so: undefined symbol: g_date_time_format_iso8601
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgvfsdbus.so
/usr/lib/x86_64-linux-gnu/gio/modules/libgiolibproxy.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgiolibproxy.so
/snap/code/53/usr/share/code/../../lib/x86_64-linux-gnu/libgnutls.so.30: version `GNUTLS_3_6_3' not found (required by /usr/lib/x86_64-linux-gnu/gio/modules/libgiognutls.so)
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgiognutls.so
/usr/lib/x86_64-linux-gnu/gio/modules/libgioremote-volume-monitor.so: undefined symbol: g_mount_operation_get_is_tcrypt_system_volume
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgioremote-volume-monitor.so
[28074:0208/093334.737367:ERROR:angle_platform_impl.cc(43)] Display.cpp:805 (initialize): ANGLE Display::initialize error 12289: glXQueryExtensionsString returned NULL
[28074:0208/093334.747910:ERROR:gl_surface_egl.cc(773)] EGL Driver message (Critical) eglInitialize: glXQueryExtensionsString returned NULL
[28074:0208/093334.748474:ERROR:gl_surface_egl.cc(1322)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
[28074:0208/093334.752303:ERROR:angle_platform_impl.cc(43)] Display.cpp:805 (initialize): ANGLE Display::initialize error 12289: glXQueryExtensionsString returned NULL
[28074:0208/093334.758263:ERROR:gl_surface_egl.cc(773)] EGL Driver message (Critical) eglInitialize: glXQueryExtensionsString returned NULL
[28074:0208/093334.759545:ERROR:gl_surface_egl.cc(1322)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[28074:0208/093334.760240:ERROR:gl_initializer_linux_x11.cc(160)] GLSurfaceEGL::InitializeOneOff failed.
[28074:0208/093334.774852:ERROR:viz_main_impl.cc(150)] Exiting GPU process due to errors during initialization
Version:          Code 1.53.0 (8490d3dde47c57ba65ec40dd192d014fd2113496, 2021-02-03T15:56:04.185Z)
OS Version:       Linux x64 5.4.0-58-generic
CPUs:             Intel(R) Core(TM)2 CPU          6400  @ 2.13GHz (2 x 1603)
Memory (System):  7.78GB (0.12GB free)
Load (avg):       4, 3, 3
VM:               0%
Screen Reader:    no
Process Argv:     --force-user-env --no-sandbox --unity-launch --no-sandbox --crash-reporter-id 059d028d-c5fd-4826-8d0a-1ac985c63e0a
GPU Status:       2d_canvas:                  unavailable_software
                  gpu_compositing:            disabled_software
                  multiple_raster_threads:    disabled_off
                  oop_rasterization:          disabled_off
                  opengl:                     disabled_off
                  protected_video_decode:     disabled_off
                  rasterization:              disabled_software
                  skia_renderer:              enabled_on
                  video_decode:               disabled_software
                  vulkan:                     disabled_off
                  webgl:                      unavailable_software
                  webgl2:                     unavailable_software

CPU %   Mem MB     PID  Process
    0      119    4944  code main
    0        0    4946     zygote
    0       40    5430       gpu-process
    0        0    4947     zygote
    0       24    5429     utility
    0       72    5545     shared-process
    0      223   27484     window (AnimeCom - Visual Studio Code)
    0      207   27517       extensionHost
    0      104   27554         electron_node server.js 
    0      183   27701         electron_node bundle.js 
    0      223   27518       watcherService
    0       64   27658       searchService
    0        0   27722       /bin/bash
    0       32   27899         python manage.py runserver
    0       32   27901           /home/techcomet/Documents/Projects/MyProjects/Web_Python/AnimeCom/.venv/bin/python manage.py runserver

Workspace Stats: 
|  Window (AnimeCom - Visual Studio Code)
|    Folder (AnimeCom): 8193 files
|      File types: mo(1182) po(1182) py(1097) pyc(1088) html(123) js(90)
|                  whl(27) svg(26) txt(25) css(15)
|      Conf files:

**Comment by TechComet** [comment]
(electron) Sending uncompressed crash reports is deprecated and will be removed in a future version of Electron. Set { compress: true } to opt-in to the new behavior. Crash reports will be uploaded gzipped, which most crash reporting servers support.
/usr/lib/x86_64-linux-gnu/gio/modules/libgiognomeproxy.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgiognomeproxy.so
/usr/lib/x86_64-linux-gnu/gio/modules/libgvfsdbus.so: undefined symbol: g_date_time_format_iso8601
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgvfsdbus.so
/usr/lib/x86_64-linux-gnu/gio/modules/libgiolibproxy.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgiolibproxy.so
/snap/code/53/usr/share/code/../../lib/x86_64-linux-gnu/libgnutls.so.30: version `GNUTLS_3_6_3' not found (required by /usr/lib/x86_64-linux-gnu/gio/modules/libgiognutls.so)
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgiognutls.so
/usr/lib/x86_64-linux-gnu/gio/modules/libgioremote-volume-monitor.so: undefined symbol: g_mount_operation_get_is_tcrypt_system_volume
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgioremote-volume-monitor.so
[28296:0208/093530.653761:ERROR:angle_platform_impl.cc(43)] Display.cpp:805 (initialize): ANGLE Display::initialize error 12289: glXQueryExtensionsString returned NULL
[28296:0208/093530.658256:ERROR:gl_surface_egl.cc(773)] EGL Driver message (Critical) eglInitialize: glXQueryExtensionsString returned NULL
[28296:0208/093530.659234:ERROR:gl_surface_egl.cc(1322)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
[28296:0208/093530.668378:ERROR:angle_platform_impl.cc(43)] Display.cpp:805 (initialize): ANGLE Display::initialize error 12289: glXQueryExtensionsString returned NULL
[28296:0208/093530.669697:ERROR:gl_surface_egl.cc(773)] EGL Driver message (Critical) eglInitialize: glXQueryExtensionsString returned NULL
[28296:0208/093530.670383:ERROR:gl_surface_egl.cc(1322)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[28296:0208/093530.670971:ERROR:gl_initializer_linux_x11.cc(160)] GLSurfaceEGL::InitializeOneOff failed.
[28296:0208/093530.687142:ERROR:viz_main_impl.cc(150)] Exiting GPU process due to errors during initialization
Version:          Code 1.53.0 (8490d3dde47c57ba65ec40dd192d014fd2113496, 2021-02-03T15:56:04.185Z)
OS Version:       Linux x64 5.4.0-58-generic
CPUs:             Intel(R) Core(TM)2 CPU          6400  @ 2.13GHz (2 x 1867)
Memory (System):  7.78GB (0.13GB free)
Load (avg):       3, 3, 3
VM:               0%
Screen Reader:    no
Process Argv:     --force-user-env --no-sandbox --unity-launch --no-sandbox --crash-reporter-id 059d028d-c5fd-4826-8d0a-1ac985c63e0a
GPU Status:       2d_canvas:                  unavailable_software
                  gpu_compositing:            disabled_software
                  multiple_raster_threads:    disabled_off
                  oop_rasterization:          disabled_off
                  opengl:                     disabled_off
                  protected_video_decode:     disabled_off
                  rasterization:              disabled_software
                  skia_renderer:              enabled_on
                  video_decode:               disabled_software
                  vulkan:                     disabled_off
                  webgl:                      unavailable_software
                  webgl2:                     unavailable_software

CPU %   Mem MB     PID  Process
    0      111    4944  code main
    0        0    4946     zygote
    0       40    5430       gpu-process
    0        0    4947     zygote
    0       24    5429     utility
    0       72    5545     shared-process
    0      223   27484     window (AnimeCom - Visual Studio Code)
    0      207   27517       extensionHost
    0      104   27554         electron_node server.js 
    0      183   27701         electron_node bundle.js 
    0      223   27518       watcherService
    0       64   27658       searchService
    0        0   27722       /bin/bash
    0       32   27899         python manage.py runserver
    0       32   27901           /home/techcomet/Documents/Projects/MyProjects/Web_Python/AnimeCom/.venv/bin/python manage.py runserver

Workspace Stats: 
|  Window (AnimeCom - Visual Studio Code)
|    Folder (AnimeCom): 8184 files
|      File types: mo(1182) po(1182) py(1090) pyc(1088) html(123) js(90)
|                  whl(27) svg(26) txt(25) css(15)
|      Conf files:

**Comment by drupalshift** [comment]
`Operating System: Manjaro Linux
KDE Plasma Version: 5.20.5
KDE Frameworks Version: 5.78.0
Qt Version: 5.15.2
Kernel Version: 5.9.16-1-MANJARO
OS Type: 64-bit
Processors: 16 × AMD Ryzen 7 3800X 8-Core Processor
Memory: 63.4 GiB of RAM
Graphics Processor: GeForce RTX 2060 SUPER/PCIe/SSE2`

Having the same issue, It's really annoying hope gets resolved
