### ISSUE TITLE
Can't download for Linux x64

### ISSUE THREAD

**Issue by romu70** [Microsoft/vscode#1019]
Hi,
The web site seems a bit broken. There is no way to download Code for Linux x64. Tested with Fedora, on both Firefox and a WebKit browser.

**Comment by alexandrudima** [comment]
@romu70 The download starts for me automatically when I access https://code.visualstudio.com/Docs/?dv=linux64 in Chrome for example. Here it is: http://go.microsoft.com/fwlink/?LinkID=620884

@bgashler1 Maybe we should render a direct download link on the download confirmation page in case download does not auto-start.
![image](https://cloud.githubusercontent.com/assets/5047891/11596152/b3771ce2-9ab3-11e5-9a8a-48ed1b14c037.png)

**Comment by romu70** [comment]
Thanks @alexandrudima. The first link doesn't work for me. Tested on 2 Fedora PCs. The second link works as expected.

**Comment by bgashler1** [comment]
I like the idea of a direct download link.  I'll put that in there.  Sorry you had trouble @romu70!

**Comment by ulrichSchreiner** [comment]
Hi,

it would be great to have a fixed Download-Link with a version in it. I [bundled vscode](https://github.com/ulrichSchreiner/vschttps://github.com/ulrichSchreiner/vsc) with docker and some go-tools and with every release i have to change the whole downloadlink in the Dockerfile.

i'd like to have one link with a version spec or something comparable ...

thx
</usc>

**Comment by 1dot75cm** [comment]
I just packaged vscode. Can you help me test it? @romu70 
https://copr.fedoraproject.org/coprs/mosquito/vscode/

**Comment by romu70** [comment]
Works great @1dot75cm , thanks a lot!

**Comment by hashhar** [comment]
I have an issue related to this, rather an extra step you could take help automate stuff.

I was trying to write a Python installation script which will download the latest release, unzip it, make symlinks, copy a VSCode.desktop I have written ([here](https://github.com/hashhar/vscode/tree/hashhar-desktop/resources/linux) for my project) into /usr/share/applications to register a launcher into Unity and GNOME.

I have stumbled upon an issue though. Since no releases are being done (not the source files, the actual installation zipballs which are downloaded from the website) I cannot use the GitHub Releases API (I wrote a preliminary proof of concept [here](https://github.com/hashhar/vscode/blob/hashhar-desktop/resources/linux/install.py)).

I also wasn't able to trigger a click on the download page. (I can do it with Mechanize but that is a dependency and I want the script to be as self sustained as possible).

So how do I go about this? I basically need a permalink to the latest VSCode distributable.

**Comment by bgashler1** [comment]
@hashhar here are the **static links** that always point to the latest VS Code distribution.  We are also going to add these links to download confirmation pages so people can restart their downloads if they don't automatically start.

osx: http://go.microsoft.com/fwlink/?LinkID=620882
win: http://go.microsoft.com/fwlink/?LinkID=623230
linux64: http://go.microsoft.com/fwlink/?LinkID=620884
linux32: http://go.microsoft.com/fwlink/?LinkID=620885
winzip: http://go.microsoft.com/fwlink/?LinkID=623231

**Comment by bgashler1** [comment]
This has been addressed on a future version of the website that will be coming out soon.

**Comment by bgashler1** [comment]
Issue moved to [Microsoft/vscode-website #147](https://github.com/Microsoft/vscode-website/issues/147) via [**ZenHub.io**](https://www.zenhub.io/)
