### ISSUE TITLE
Cannot launch Node inside integrated terminal due to broken NODE_OPTIONS

### ISSUE THREAD

**Issue by lumaxis** [microsoft/vscode#101929]
Issue Type: <b>Bug</b>

Steps to reproduce:

1. Open an integrated terminal
2. Try to run `node`

Expected behavior:

Node starts

Actual behavior:

An error is shown:

```sh
$ node
node: Support/Code is not supported in NODE_OPTIONS
```

The content of my environment's `NODE_OPTIONS` variable is:

```sh
$ echo $NODE_OPTIONS
--require "/Users/lukas/Library/Application Support/Code - Insiders/User/workspaceStorage/4a0794f90eb095813ef00701882215ad/ms-vscode.js-debug/bootloader.js" 
```

VS Code version: Code - Insiders 1.47.0-insider (d5e9aa0227e057a60c82568bf31c04730dc15dcd, 2020-07-08T11:58:31.614Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 5, 5|
|Memory (System)|64.00GB (0.21GB free)|
|Process Argv|-psn_0_1544569|
|Screen Reader|no|
|VM|11%|
</details><details><summary>Extensions (65)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-base64|ada|0.1.0
vscode-browser-preview|auc|0.6.7
emojisense|bie|0.7.0
github-markdown-preview|bie|0.0.2
markdown-checkbox|bie|0.1.3
markdown-emoji|bie|0.0.9
markdown-preview-github-styles|bie|0.1.6
markdown-yaml-preamble|bie|0.0.4
LinkCheckMD|bla|0.3.1
better-toml|bun|0.3.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|2.2.1
vscode-eslint|dba|2.1.6
vscode-npm-source|dku|1.0.0
binary-plist|dni|0.4.0
xml|Dot|2.5.0
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
vscode-npm-script|eg2|0.3.12
code-runner|for|0.11.0
vscode-pull-request-github|Git|0.17.0
vscode-mocha-test-adapter|hbe|2.6.1
vscode-test-explorer|hbe|2.19.1
rest-client|hum|0.24.1
customize-ui|ioc|0.1.45
monkey-patch|ioc|0.1.8
ReplaceWithNewline|jma|0.0.1
docthis|joe|0.7.1
vscode-peacock|joh|3.7.2
snippet-copy|lum|1.0.0
ruby-rubocop|mis|0.8.3
vscode-apimanagement|ms-|0.1.3
vscode-azurefunctions|ms-|0.22.1
vscode-azureresourcegroups|ms-|0.2.0
vscode-docker|ms-|1.3.1
extension-manifest-editor|ms-|0.1.5
vscode-aks-tools|ms-|0.0.6
vscode-kubernetes-tools|ms-|1.2.1
remote-containers|ms-|0.127.0
remote-ssh-edit-nightly|ms-|2020.7.9540
remote-ssh-nightly|ms-|2020.7.9540
azure-account|ms-|0.8.11
azurecli|ms-|0.5.0
vscode-node-azure-pack|ms-|0.0.11
vsonline|ms-|2.0.0
debugger-for-chrome|msj|4.12.9
debugger-for-edge|msj|1.0.15
color-highlight|nau|2.3.0
gremlins|nho|0.23.0
vscode-ts-markdown-to-playground|Ort|1.1.0
quicktype|qui|12.0.46
ruby|reb|0.27.0
vscode-yaml|red|0.8.0
vscode-sort-json|ric|1.18.0
vscode-hexdump|sle|1.7.2
code-spell-checker|str|1.9.0
code-spell-checker-german|str|0.1.4
shellcheck|tim|0.9.0
vscodeintellicode|Vis|1.2.9
vscode-icons|vsc|10.1.1
gistfs|vsl|0.1.4
vscode-wakatime|Wak|4.0.0
vscode-todo-highlight|way|1.0.4
vscode-ruby|win|0.27.0
material-theme|zhu|3.8.3

(1 theme extensions excluded)

</details>

**Comment by connor4312** [comment]
@lumaxis this means you're running Node 10 (which doesn't have very good argument parsing behavior). When you first enable auto attach, js-debug will do a check and, if it can verify that you have Node 10 in your path, will try to do some fallback logic. But if you didn't have a discoverable Node binary or installed/downgraded after enabling auto attach, this will not be detected.

You should be able to fix this by either:

 - Toggling your auto attach setting to "disabled", and then "on" again if you want to use it
 - Or upgrading to Node 12+. If you have the option to do so, I would recommend this path since 10 will be EOL in April and there's lots of new features and better performance on 12-14 🙂

**Comment by lumaxis** [comment]
Thanks @connor4312! This project was actually still using Node 8 … 😬💀

It seems like toggling auto-attach doesn't actually work in that case but fortunately, I was able to at least upgrade this one particular service to Node 10 where the issue automagically went away.

Is there a way for me to verify that the fallback logic is really triggered? How would I tell?

**Comment by connor4312** [comment]
After you toggle (make sure you toggle through disabled, not "off"!) a ⚠️ sign will appear in the top right of your terminal prompting you to reload the terminal to get the new environment variables. If that doesn't work and you've previously installed js-debug manually at any point, you may be hitting this issue: https://github.com/microsoft/vscode/issues/98778#issuecomment-649784816

> Is there a way for me to verify that the fallback logic is really triggered? How would I tell?

You can check by echo'ing NODE_OPTIONS as you did. If there are _no_ quotes around the --require, that means we were able to detect Node 10. Otherwise, we'll quote it (the substantial majority of users are on Node 12+ so  that's what we default to).
