### ISSUE TITLE
[Feature Request]**Add Customizable TOOLBAR Option Similar to MS Visual Studio 2019**

### ISSUE THREAD

**Issue by hoopdy** [microsoft/vscode#101961]
Add a toolbar similar to that in MSVS2019 and make it so that user can customize it with whatever commands are needed. 

The Command Palette is a great feature, but often not as convenient as a toolbar would be.  It is also not as natural for users who are accustomed to using the toolbar in most other MS software.  

 <sub>I reviewed the "contributing guidelines" and searched existing requests for "toolbar" or "button.**

**Comment by usernamehw** [comment]
Duplicate of #41309

**Comment by MikeRosoft** [comment]
According to your own rules, the issue is in-scope in accordance with criterion 2. As for criterion 4, a user has started working on a prototype (see https://github.com/Microsoft/vscode/issues/41309#issuecomment-403222101 and https://github.com/junalmeida/vscode/pull/1 ), only to be immediately shut down by saying that a pull request creating a toolbar wouldn't be accepted.

The boilerplate message says that you are "happy to listen and to reconsider". Well, then listen to your users! And if you aren't willing to immediately reconsider, then at least provide some feedback. (Your only feedback so far has been to summarily ignore the existing issue, and to summarily close any new requests for a toolbar as out of scope and/or as a duplicate.)

**Comment by hoopdy** [comment]
I did not intend for this to be such an issue and did not know when I
posted that it had been.

Microsoft does not intend for VS Code to be a full on IDE that competes
with VS. This is one feature they can omit to prevent that. It's very
annoying and I will work to circumvent it as I learn more, but, at the same
time, MS Code is free, and is quite usable for me as a novice. VS (2019,
e.g.), while still free for me as I just do this to learn, is not as usable
(especially since I cannot figure out how to work on Jupyter notebooks in
there).

I appreciate that they are a business that needs to make money.  Also, they
do provide a lot of software on a free or free-for-non-commercial basis,
significantly discount costs for schools and nonprofits, and sponsor a lot
of good causes. MS has, for the most part, always been, more or less, a
good corporation. I have no interest in them whatsoever, but appreciate the
services. I am quite familiar with their data collection practices, and
believe them to be much more ethical than the F and G in FANG.

That being said, I think that people should be allowed (though not
necessarily encouraged) to find creative ways to solve issues such as this,
so long as it is not for commercial gain or with malicious intent. They
should not interfere with that by preventing someone from submitting or
sharing it on Github (if I understand what you are alleging correctly).
However, MS should be able to adapt the software to render those things
non-functional to protect IP and business interests.

Just my 2 cents.
