### ISSUE TITLE
SCM: Setting to render the repository row in single repo view

### ISSUE THREAD

**Issue by SailorMax** [microsoft/vscode#102080]
- VSCode Version: 1.47.0
- OS Version: Windows 10v2004b19041.329

Steps to Reproduce:

1. open any repository

Expected: in SCM sidebar name of repository and its current status

Actual: just input field for commit and "Changes" list

Does this issue occur when all extensions are disabled?: Yes

**Comment by yhatt** [comment]
https://github.com/microsoft/vscode/issues/101112#issuecomment-650149590?

**Comment by SailorMax** [comment]
This option was requested, because of user focus, when he fill commit description, on top part of window. Look at bottom part of window in this moment is not comfortably - #38785

**Comment by yhatt** [comment]
Actually this removal made confusion also for me. User should change the direction of moving eyes to operate sync button, left or bottom, by depending on the number of opening repositories.

Eeven if opening a single repository, having an option to show the new source control tree view with the same look as opening multiple repositories may be great.

**Comment by LeonnardoVerol** [comment]
I also believe "scm.alwaysShowProviders" should be brought back due do User Usability

**Comment by joaomoreno** [comment]
We will not bring back the providers view, since it provides no extra information.

> Even if opening a single repository, having an option to show the new source control tree view with the same look as opening multiple repositories may be great.

I like this idea. Let's add a setting to simply render the repository in the tree.

**Comment by SailorMax** [comment]
@joaomoreno This feature was broken by removing "scm.alwaysShowProviders" in latest build. Can you add this "feature-request" to next (july) build plan? To do not wait restoration too long...

thank you.

**Comment by joaomoreno** [comment]
It's already assigned to the July milestone.

**Comment by bbceg** [comment]
When you say "We will not bring back the providers view, since it provides no extra information" is this only because the information is surfaced at the bottom of VS Code? If so I do understand that thinking but it's much more helpful to have it at the top where you're actually looking while handling commits / changes etc.

Also, as others have suggested, it's pretty jarring when jumping between two projects to have it suddenly disappear. Take this example:

Multiple repo project (repo names redacted):
![image](https://user-images.githubusercontent.com/7188545/88651121-3bdfa700-d0c1-11ea-87e4-5808284623ea.png)

Single rep project:
![image](https://user-images.githubusercontent.com/7188545/88651218-587bdf00-d0c1-11ea-8cc6-26710b884d62.png)

I'm less bothered about the repo name (since there's only one and I usually know which project I'm editing!) but the sync button showing the number of changes is very useful.

**Comment by joaomoreno** [comment]
Setting name: `scm.alwaysShowRepositories`
