### ISSUE TITLE
More options for buttons on notifications

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#102087]
[ ] Permit buttons to be denoted secondary:

![image](https://user-images.githubusercontent.com/35271042/45375780-d8226280-b5aa-11e8-9900-c36d9b5dbd32.png)

_Originally posted by @misolori in https://github.com/microsoft/vscode/issues/58399#issuecomment-420352923_

[ ] Allow codicons in button labels.

[ ] Allow tooltip (title) to be set independently of label. Example use case: an explanation of what a "Skip" button will do.

Surface all of these in the `window.showErrorMessage` and `window.showInformationMessage` APIs.

**Comment by bpasero** [comment]
@gjsjohnmurray ideally can we do 1 issue per request, thanks.

**Comment by gjsjohnmurray** [comment]
> 
> 
> @gjsjohnmurray ideally can we do 1 issue per request, thanks.

@bpasero fair point, but in this case all three features are controlled by the properties of `IButtonOptions` so it seemed likely they'd get implemented together.

**Comment by gjsjohnmurray** [comment]
@misolori any views on whether this deserves to get onto Backlog even if (as seems likely) it doesn't attract 20 votes?

**Comment by misolori** [comment]
I'd love for this to get implemented but I think one of the issues that the team discussed, specifically about notifications, is that it would need to be an option that extensions need to opt  into (because we can't reliably choose a "default" action) and that it may create inconsistencies with some opting into into.
