### ISSUE TITLE
keep integrated terminal in the same location as the active file

### ISSUE THREAD

**Issue by zhyiyu** [microsoft/vscode#102031]
### in brief

I would like to suggest to keep the integrated terminal at the same location as the active file, and I know this has been suggested before, like in [12094](https://github.com/microsoft/vscode/issues/12094). But I would like to bring this up for this one single reason

- **display the correct git branches**

### details

Imagine the following situation, you are working under a directory which has two git repositories in its subdirectories

```bash
.
└── working_directory
    ├── repository_1
    │   ├── file_1_1
    │   ├── file_1_2
    │   ├── file_1_3
    │   └── readme_1.md
    └── repository_2
        ├── file_2_1
        ├── file_2_2
        └── readme_2.md
```

Now the integrated terminal is by default, located at `working_directory`. Let us say you are viewing a file from `working_directory/repository_1` and you would like to switch branches from the bottom left corner of `vscode`, you will not see the correct branches. Because `vscode` is showing branches from `working_directory`, not from the directory of the active file. I tried to change the settings with

```json
"terminal.integrated.cwd": "$PWD"
```

but it does not seem to work.

Thank you for your time and please let me know if thing are not clear enough.

**Comment by jbree** [comment]
Are you suggesting that the active terminal automatically `cd` to "follow" your active file, or that a new terminal be spawned and/or selected each time you open a file in a different directory?

As a user (not a developer) of vscode, I think either of these possibilities is perilous because it would be far too easy to corrupt your "mental model" of where your terminal's CWD is, and ultimately execute a command you didn't intend.

**Comment by zhyiyu** [comment]
I do not use the integrated very often so you may be right. Maybe my suggestion should be more focused on displaying the right git branches part, but I just wanted to point explicitly why the correct git branches were not shown.

**Comment by jbree** [comment]
This may or may not help you, depending on the actual structure of your root folder. For your consideration:

Instead of having one project folder opened at `working_directory`, instead use a Workspace and add separate project for each of `repository_1` and `repository_2`, then the source control view (and the lower-left branch display) will behave the way you imagine. Selecting a file from the other project causes the branch display to change to the correct repo, and displays the file in the correct repo in the source control view (if it is modified).

Additionally, there exist two useful commands for your scenario:
+ `Terminal: Create New Integrated Terminal`
+ `Terminal: Create New Integrated Terminal (In Active Workspace)`

The first of these commands brings up a prompt allowing you to select which project the new terminal is for. I usually end up with one open for each of my selected terminals, and have hotkeys set up for `Focus Next Terminal` and `Focus Previous Terminal`.

I hope this helps!

**Comment by Tyriar** [comment]
It's hard to do this sort of thing reliably and in all situations. I think an extension would be idea here, for example the extension could automatically switch the active terminal when you change files (based on multi-root folders or git repos), or alternatively have a command that sends a `cd <active folder>` command to the terminal.

**Comment by zhyiyu** [comment]
Thanks for helping! I will try to do the workspace thing.
