### ISSUE TITLE
i cant install extensions

### ISSUE THREAD

**Issue by evonady** [microsoft/vscode#102052]
Issue Type: <b>Bug</b>

i cant enable any extenions and i cant run any code and when i open any extenion gets an error any body help?

VS Code version: Code 1.47.0 (d5e9aa0227e057a60c82568bf31c04730dc15dcd, 2020-07-09T08:02:06.629Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (1.65GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
aio-compiler|azt|2.0.0
code-runner|for|0.10.0
python|ms-|2020.4.76186
cpptools|ms-|0.29.0-insiders2

</details>

**Comment by gjsjohnmurray** [comment]
Please post more details. What happens that shouldn't? What doesn't happen that should? Did the problem only appear after 1.47 arrived? If so, were you previously on 1.46.1?

**Comment by banggua** [comment]
I have the same problem, all plugins failed to start. And it only happened in version 1.47.

**Comment by weixisheng** [comment]
I have the same problem, just loading but no result.

**Comment by sandy081** [comment]
Please follow these steps

- Help -> Toggle Developer Tools -> Network
- Then check for any network failed requests while browsing and installing the extensions if found all requests fails then its probably a proxy or DNS issue at your end.
- To confirm its a DNS issue check if you can access this page https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default, if you cannot please try configuring your DNS like pointing to 1.1.1.1 as suggested here? https://1.1.1.1/dns/. Otherwise please contact your network administrator.
- If it is not a network issue, please share the logs from the following locations
    - Help -> Toggle Developer Tools -> Console
    - View -> Command Pallette... -> Toggle Shared Process -> Console
    - View -> Open View… -> Log (Shared)
    - View -> Open View… -> Log (Window)

**Comment by sandy081** [comment]
Please confirm that if you are having this issue - https://github.com/microsoft/vscode/issues/102082

**Comment by evonady** [comment]
after too many tries and after the update
I changed the DNS protocol to google's protocol and it worked
https://developers.google.com/speed/public-dns
the V4 and V6
