### ISSUE TITLE
Webview Extension stopped to work after last update

### ISSUE THREAD

**Issue by AllanOricil** [microsoft/vscode#102044]
- VSCode Version: 1.47.0
- OS Version: Windows 10

Steps to Reproduce:
My extension stopped to load the webview after updating VSCode.

![image](https://user-images.githubusercontent.com/55927613/87101561-d87ef980-c225-11ea-8622-7b55fb807932.png)

I bundled the files I was getting from the CDN but the problem persists

![image](https://user-images.githubusercontent.com/55927613/87102439-4cba9c80-c228-11ea-8711-6cdeefc90515.png)

I just updated the vscode and then it never opened again. This is the extension.
https://marketplace.visualstudio.com/items?itemName=allanoricil.salesforce-soql-editor&ssr=false

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by mjbvz** [comment]
Hi, it looks like your extension is using the hardcoded `vscode-resource` uri scheme (see the `getHtml4Path` function)

You'll need to update to use the `asWebviewUri` function instead. See #97962 for details. 

We have code that tries to automatically rewrite `vscode-resource` usages in html. Hover it does not rewrite your current html since it uses unquoted attribute for the file path:

<img width="637" alt="Screen Shot 2020-07-09 at 5 12 05 PM" src="https://user-images.githubusercontent.com/12821956/87102638-55e74180-c207-11ea-880c-8309240888d3.png">

Try updating to use `asWebviewUri` as covered in #97962 and let me know if you still see problems

**Comment by AllanOricil** [comment]
Ok, but is is something you guys changed today? because it was working without any problem. I will follow the link you sent. Thanks you @mjbvz

**Comment by mjbvz** [comment]
Yes we change this in 1.47. However we have been recommended  all extensions switch off hard coding `vscode-resource` for a while as that approach is not supported when vscode is run browsers

**Comment by AllanOricil** [comment]
> Yes we change this in 1.47. However we have been recommended all extensions switch off hard coding `vscode-resource` for a while as that approach is not supported when vscode is run browsers

thanks

**Comment by AllanOricil** [comment]
@mjbvz I tried to add the method, but seems Im with problem with the vscode import.

Look, it cant find `asWebviewUri`

![image](https://user-images.githubusercontent.com/55927613/87106466-e2a7f480-c233-11ea-9e77-93fb95951f92.png)

And I followed this example:

![image](https://user-images.githubusercontent.com/55927613/87106506-01a68680-c234-11ea-8a8d-5d2221b70872.png)

**Comment by AllanOricil** [comment]
Found the issue!
I was using the old npm package. Changed to @types/vscode and now the method appears.

**Comment by pikadun** [comment]
@mjbvz I use the `asWebviewUri` api but I got a url that looks wrong: vscode-webview-resource://4653f308-3117-4192-97f2-ec249cd8f1a5/file///root/repo/vscode-redis/out/view/js/main.js.

It work well on v1.46

**Comment by AllanOricil** [comment]
@mjbvz and @jrieken  Could you help me with this issue https://github.com/microsoft/vscode/issues/19582
Is there a documentation or a recipe to show how to add an Octicon in a CodeLenses extension? I want to place a "play" icon in a few places.
