### ISSUE TITLE
It takes too many clicks of "Load More Frames" to get the full call stack when there are lots of stack frames.

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode#102048]
I was a debugging a crash with 175+ stack frames and I had to keep hitting the "Load More Frames" over and over (it only loaded a small number of frames like 20). I think the "Load More Frames" should be replaced by "Load All Frames"...I don't know a good use case where you would not want that. I've never had this problem when using the Visual Studio debugger.

It hit another case a few days ago with a possible stack over flow and I gave up trying to obtain stack frames because there were so many I had to manually load.

Originally reported at https://github.com/microsoft/vscode-cpptools/issues/5752 .

**Comment by isidorn** [comment]
I think this feature request makes sense.
However fetching all the frames might be slow, so just replacing "Load More Frames" with "Load All Frames" might not be the best solution in all cases.
However I am open for experimenting with this. Thus assigning to August to change to "Load All Frames" and in that milestone we can see how it behaves in practice.

**Comment by WardenGnaw** [comment]
It would be very slow for the C/C++ extension to load all the frames at once if the call stack is very big, but we have a feature in the backlog to improve the performance on fetching unnecessary data like the function arguments names and types.

**Comment by sean-mcmanus** [comment]
@WardenGnaw Do you know why VS doesn't have the "Load More Frames" issue? Is it because they have the optimizations that don't fetch the unnecessary data?

**Comment by WardenGnaw** [comment]
MIEngine is only used in SSH Attach to Process using GDB. The slowness occurs when we need to request the arguments for each frame in the call stack. Each one of these is a separate evaluate request to GDB.

**Comment by isidorn** [comment]
I think the best would be to only change this on the vscode side on the c++ extensions improves the performance of fetching. So until then assinging this to backlog.

**Comment by gregg-miskelly** [comment]
One clarification: both the C++ and C# debuggers already do all the work up front, so "Load All Frames" would be near instantaneous for these adapters, and the change in this issue would improve the debugging experience for both of them.

In the C++ (GDB/LLDB) case there is an optimization that the C++ extension could have (but currently doesn't) to defer formatting frames until requested. If implemented, this would make clicking "Load All Frames" a little slow, but still faster than obtaining any frames is today (since some of the work would already be done), so still totally acceptable. In the C++(vsdbg)/C# we don't have a good way to obtain the frame count without doing all the work, so we would probably not implement this. Also frame formatting isn't nearly as slow as it is in GDB.

To answer Sean's question -- the optimization that full Visual Studio employs is that, when entering break state, VS will obtain just the the top stack frame with source, which can be done cheaply in the common case, and then the full call stack is obtained asynchronously. This achieves a similar effect to what VS Code achieves with the partial call stack, but without the need for the 'more' frames.

**Comment by isidorn** [comment]
@gregg-miskelly thanks for clarifying. 
Also note that VS Code also does the Visual Studio optimisation, we first fetch the top stack frame, then the rest up to 10. And for frames after that we do it only when the user clicks "Load More Frames"

fyi @connor4312 on potentially changing "Load More Frames" with "Load All Frames" with regards to js-debug performance.

**Comment by connor4312** [comment]
js-debug will do some amount of work mapping compiled locations back to source locations, if source maps area available. This might take some amount of time if remote sourcemaps haven't yet loaded before the user clicks the "load all" button, but otherwise should be fairly instantaneous.

**Comment by isidorn** [comment]
Ok, let me assign it to August so we maybe change it in debt week and we have the whole of august to gather feedback

**Comment by isidorn** [comment]
I have pushed a change as we have agreed.
The action is now call "Load All Stack Frames". I have tried it for some simpler js-debug cases and seems to work just fine.

Please try it out with VS code insiders from Friday and let me know how ti goes. Thanks!

**Comment by isidorn** [comment]
@weinand raised a good point:
"since you are now requesting all stackframes when pressing the "load more" button, how do you protect against the case of an infinite recursion with a 1000000 element stack?"

Currently we are not protecting against this case.
We could for example always ask for up to 1000 stack frames.
Alternativly the debug adapter can cap the `totalFrames` number returned with the `StackTraceResponse`.

Let me know what you think.

**Comment by connor4312** [comment]
Requesting some large number of frames from the start is probably fine. I think most languages with tail call recursion where infinite recursion is possible don't represent each tailed function as part of the stack, but there might be some that do...

**Comment by gregg-miskelly** [comment]
Both the C++ and C# debug adapters have internal max frame counts.

**Comment by isidorn** [comment]
Thanks for feedback. So it seems for now we will not have a limit on the VS Code side. We can easily add this later if we hit into issues.

**Comment by isidorn** [comment]
To verify:
1. Start debugging some program which has more than 30 stack frames. For example some simple recurisve function
2. Make sure that you get the "Load All Frames" button and clicking on it all stack frames are loaded
