### ISSUE TITLE
Remove Keybinding "cursorLeft" (Keybinding: ←). The cursor can be moved to left.

### ISSUE THREAD

**Issue by kimizuy** [microsoft/vscode#102176]
I wanted to seal off the arrow keys for Vim extension.
I removed Keybinding "cursorLeft"(←), but the cursor moves to left.
Also, "cursolUp"(↑) is the same kind of bug too.

- VSCode Version: 1.47.0
- OS Version: macOS Mojave 10.14.6

Steps to Reproduce:

1. Open Keyboard Shortcuts.
2. Remove Keybinding "cursorLeft" (Keybinding: ←).
3. Input LeftArrow on some text.

Does this issue occur when all extensions are disabled?: Yes

**Comment by ArturoDent** [comment]
Verify that you do have this in your keybindings.json:

```
  {
    "key": "left",
    "command": "-cursorLeft",
    "when": "textInputFocus"
  },
```

That does disable the leftArrow key for me but I am on W10.  So could it be macOS itself that is triggered by your leftArrow?

**Comment by kimizuy** [comment]
It's the same setup as mine.
There are likely to be differences depending on OS.

**Comment by alexdima** [comment]
When using something like:
```
  {
    "key": "left",
    "command": "-cursorLeft",
    "when": "textInputFocus"
  }
```
or:
```
  {
    "key": "left",
    "when": "textInputFocus"
  }
```
That effectively leaves <kbd>ArrowLeft</kbd> unassigned. Our keybinding system will not do anything when <kbd>ArrowLeft</kbd> is pressed (will not call `.preventDefault()`), and that will eventually reach electron's/chromium's default behaviour.

The OS difference stems from what we keep in our hidden `<textarea>` that is used as input. When no screen reader is attached, on Windows, we keep the `<textarea>` empty. So the default browser action will be a no-op. On macOS, due to some input composition types, we keep the previous word in the `<textarea>` (e.g. this allows for the long press `e` -> `è` to work). The default browser action will move the cursor inside the textarea to the previous character. We have some other separate piece of code that monitors the cursor location in the hidden `<textarea>`. That is because there are some Braille devices which have the ability to move the cursor, and we want to detect that. So that is what is going on.

This is all kind of as designed, so the workaround would be to use something like:
```
  {
    "key": "left",
    "when": "textInputFocus",
    "command": "type"
  }
```
which will be a no-op because the args are missing, or perhaps bind it to one of your commands that is a no-op.
