### ISSUE TITLE
Debugger Step Over steps over some 'for' loop bodies in source-mapped TypeScript

### ISSUE THREAD

**Issue by rbuckton** [microsoft/vscode#102164]
- VSCode Version: 1.47.0-insider
- OS Version: Windows 10.0.18363
- TypeScript: 4.0.0

This has actually been around for years, but I haven't found an existing bug for it. When debugging a TypeScript project with source maps, and using the "Step Over" command (F10 on windows), in certain cases the entire body of the loop is stepped over.

This occurs when the TypeScript project targets ES5/3 and the `for`, `for..in`, or `for..of` body contains a closure that includes the loop variable. For example:

```ts
for (let i = 0; i < 1; i++) {
    () => i;
}
```

Steps to Reproduce:

1. Compile the above TypeScript code using `--target ES5 --sourceMap`
2. Launch the debugger against the output file using a launch.config target with source maps enabled
3. Step to the line containing `for (let i...`
4. Execute Step Over twice so that the debugger will step through the `let i = 0` and `i < 1` steps individually without moving the highlighted position. At the point the next step should continue into the body of the loop...
5. Execute Step Over and the entire body of the loop is skipped.

The reason for this is that the above code, when compiled using `--target ES5 --sourceMap` produces this output:

```js
"use strict";
var _loop_1 = function (i) {
    (function () { return i; });
};
for (var i = 0; i < 1; i++) {
    _loop_1(i);
}
```

[Playground example](https://www.typescriptlang.org/play/index.html?target=1&ssl=3&ssc=2&pln=1&pc=1#code/GYewTgBAFANgpgFwgSwgXggBgNwogHggEZdkBqMgSggG8AoCR6atAPhWzoF8g)

The `_loop_` function is needed to lexically scope the `i` value to the per-iteration environment created by the `for` loop, per the ECMAScript specification. Unfortunately, this means that a "Step Over" command centered on `_loop_1` will step over the entire body of the loop. While this would make sense if debugging the JavaScript directly, when debugging the TypeScript source it appears as of the debugger has skipped over the entire body. For a loop that does not contain a closure referencing a loop variable, a "Step Over" will step into the loop body normally.

Here's an example of the issue in action:

![Step Over](https://user-images.githubusercontent.com/3902892/87200231-efb6f900-c2b0-11ea-8bff-d0e64d674ea9.gif)

The "Step Over" commands 3 and 6 should have advanced to the body of the loop but instead step over the `_loop` function in the generated code.

I'm curious if there is a way to modify the JavaScript debugger (or possibly the "Smart Step" functionality, if that is where such functionality would live) to detect this case and step *into* the body rather than over it. This can be quite confusing at times for some developers. 

Unfortunately, I don't believe there's anything we can do in TypeScript to *not* emit the `_loop` function and preserve the ECMAScript specification, and I don't believe there's currently anything in the source map specification that could indicate such a transformation, so it may fall to the VSCode Debugger to detect and work around this case.

Does this issue occur when all extensions are disabled?: Yes

**Comment by connor4312** [comment]
Yea, currently we don't drive any debugger behavior based on the contents, nor is there anything in sourcemaps that would allow us to do this.

Additionally, at this point ES3/5 targets are only needed for Internet Explorer and long-since-EOL versions of Node.js (<=4), so I'm not sure there's good return on investment in doing this (though in theory functionality could be reused if any new ES features require similar closures). Thus letting the bot assign it as a backlog candidate, to be prioritized if there's interest.

**Comment by rbuckton** [comment]
Thanks for the feedback. For the time being, the TypeScript compiler is required to target ES5 for its own builds, for a number of reasons. As much as we'd like to have the compiler target ES2015 at a minimum, there are a number of factors preventing us from doing so for the time being.

**Comment by rbuckton** [comment]
As an aside, I often wish there was a way to bring something like .NET's `Debugger` attributes like `DebuggerStepThroughAttribute`, `DebuggerHiddenAttribute`, `DebuggerNonUserCodeAttribute`, and even `DebuggerTypeProxyAttribute`, but perhaps that's a topic for a different issue.

**Comment by connor4312** [comment]
update here -- having debugging be affected by source contents is something I can see us having in the long term to help with minified sources, but this for particular case it's something that is uncommon in most environments now, and will become increasingly less common by the time we implement it. Also, requesting and dealing with source content will have a performance impact, so this is not behavior that would be on by default; users would need to know to toggle it on. I don't think the ROI is there for this feature.

>  I often wish there was a way to bring to JavaScript something like .NET's Debugger attributes like DebuggerStepThroughAttribute, DebuggerHiddenAttribute, DebuggerNonUserCodeAttribute, and even DebuggerTypeProxyAttribute, but perhaps that's a topic for a different issue.

That would be nice, mostly in code generated by compilers. Sourcemaps would be the right place for this, but don't give us anything out of the box to use. We could experiment with some extra fields in there, for instance? Again, I would rather avoid needing runtime evaluation or source-parsing, since that slows things down, but we already efficiently load and deal heavily with sourcemaps.
