### ISSUE TITLE
[SCM] Action buttons are not always visible

### ISSUE THREAD

**Issue by vasicsek** [microsoft/vscode#102108]
I have an issue with the action buttons visibility. If my side panel width is not big enough and the names of my repositories are relative long I can not see the buttons. Below is a screenshot of the issue:

![image](https://user-images.githubusercontent.com/11719529/87150219-f5610e80-c2b1-11ea-8808-d2b6ebb5fdc8.png)

Also, there is no commit button, so I have to increase the width of the panel, which is not the best solution, because when I switch to the Explorer view is it is just wasted space.

![image](https://user-images.githubusercontent.com/11719529/87150527-859f5380-c2b2-11ea-971a-4a0d24dd294e.png)
![image](https://user-images.githubusercontent.com/11719529/87150495-6ef8fc80-c2b2-11ea-8447-c198c2eefaf1.png)

- VSCode Version: 1.47.0
- OS Version: Windows 10 Pro 2004 19041.329

Steps to Reproduce:

1. Add a repository with relative long name to Explorer
2. Switch to Source Control panel

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
@vasicsek Do you have a suggestion on how to improve this?

**Comment by CreativeTechGuy** [comment]
This issue seems to have been introduced in a recent version as this previously wasn't an issue. When we have very long package names this tab is almost unusable as you'd need to expand the panel extremely wide just to click the buttons.

The suggestion is to force those action buttons to always be visible on the right side and truncate the repo name to fit the buttons. The buttons should take higher priority than the name.

**Comment by vasicsek** [comment]
Sorry for the late answer. I agree with @CreativeTechGuy 's suggestion (thank you, btw) https://github.com/microsoft/vscode/issues/102108#issuecomment-657273686. It seems to be the ideal solution for this issue.

**Comment by joaomoreno** [comment]
Here's the fixed version:

![image](https://user-images.githubusercontent.com/22350/87661082-53816c00-c760-11ea-8758-18a83a42d93e.png)
