### ISSUE TITLE
"Duplicate Workspace in New Window" just creates new window and opens workspace.json file

### ISSUE THREAD

**Issue by ryanjkelly** [microsoft/vscode#102148]
- VSCode Version: 1.47
- OS Version: Windows 10 Home (2004, 19041.329)

Steps to Reproduce:

1. Open workspace
2. Duplicate Workspace in New Window

Does this issue occur when all extensions are disabled?: Yes

This happens on both v1.47 and v1.48.0 (Insiders). I downgraded to v1.46.1 and it is working correctly there.

One other thing to note is that when I exit VSCode and reopen it, the duplicated workspaces open correctly. Here's a screencast showing the behavior:

![vscode-duplicate-workspace-bug](https://user-images.githubusercontent.com/4969091/87184459-a7e2a280-c2ad-11ea-8892-610e731dd163.gif)

**Comment by bpasero** [comment]
I can reproduce but only on Windows for some reason. Clearly a regression and up for help if someone wants to drill in. E.g. start with a `git bisect` to understand which commit triggered this 👍

**Comment by bpasero** [comment]
A regression from https://github.com/microsoft/vscode/commit/5ebae68803 where we stopped ignoring case for `isEqualOrParent` on Windows. Bottom line, this is a drive letter casing issue only on Windows where we are unable to understand that the untitled workspace path is inside untitled workspace home folder (from [`isUntitledWorkspace`](https://github.com/microsoft/vscode/blob/97fc588e65bedcb1113baeddd2f67237e52c8c63/src/vs/platform/workspaces/common/workspaces.ts#L179))

I wonder if `resources.ts` should explicitly ignore the case of the drive letter because it is relatively easy to get into a state where a URI ends up having the lowercase form. For example:
* take a URI with uppercase drive letter
* pass it around, use `URI.fsPath`
* construct it again via `URI.file`
* you can no longer compare both URIs due to drive letter case differences

//cc @jrieken

**Comment by jrieken** [comment]
> I wonder if resources.ts should explicitly ignore the case of the drive letter because it is relatively easy to get into a state where a URI ends up having the lowercase form

We actually would do that when using `fsPath` or `toString` - since they normalize the driveletter casing. My refactorings didn't change the original implementations and they use a different fsPath-variant, see [originalFSPath](https://github.com/microsoft/vscode/blob/f570be1d91e698647d0e0ef39eb3071b4c2a874e/src/vs/base/common/resources.ts#L164-L174)-usage. @aeschli would know why that has been done.

**Comment by vinayg-me** [comment]
Thanks a lot for fixing this issue. 
It is part of my muscle memory, and was getting irritated with the bug.
