### ISSUE TITLE
File with Chinese chars appears as changed right after opening

### ISSUE THREAD

**Issue by mkvoya** [microsoft/vscode#102202]
- VS Code version: Code - Insiders 1.48.0-insider (e7920dce7bfd0b707ebfc0a5379c6edd2233e475, 2020-07-10T11:55:11.286Z)
- OS version: Darwin x64 19.5.0
- All extensions disabled

- Steps to Reproduce:
  Step 1. Download the file [bug.tex.txt](https://github.com/microsoft/vscode/files/4906561/bug.tex.txt)
  Step 2. Check line 982 of the file with some other editors
  Step 3. Open the file in vscode and check line 982

- Expected behaviour: the line is read without any change (i.e., the content should be exactly the same as the file on disk).
- Actual behaviour: the line is changed by vscode.

Here is the screenshot:

![image](https://user-images.githubusercontent.com/10482293/87221426-89100900-c39e-11ea-988d-bac6862e2582.png)

<hr />
<b>The following information is generated by VSCode's Report Issue</b>

Issue Type: <b>Bug</b>

When opening the given file, line 982 of the file is changed automatically with one (or two?) wrong characters.
Step to reproduce: open the file and check line 982.
Expected behaviour: the line is read without any change (i.e., the content should be exactly the same as the file on disk).
Actual behaviour: the line is changed by vscode.

Here is the screenshot:

![image](https://user-images.githubusercontent.com/10482293/87221426-89100900-c39e-11ea-988d-bac6862e2582.png)

Here is the file (filename changed to bug.tex.txt, but it doesn't matter):

[bug.tex.txt](https://github.com/microsoft/vscode/files/4906561/bug.tex.txt)

VS Code version: Code - Insiders 1.48.0-insider (e7920dce7bfd0b707ebfc0a5379c6edd2233e475, 2020-07-10T11:55:11.286Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (3.16GB free)|
|Process Argv|-psn_0_146766831|
|Screen Reader|no|
|VM|15%|
</details>Extensions: none

**Comment by mkvoya** [comment]
I updated the post with a better format. The detailed system info is folded at the end of the post (generated by vscode's Report Issue). I'd like to help if more info is still needed.

**Comment by bpasero** [comment]
Thanks, I can reproduce with the following steps:
* create an empty folder
* init git and add [bug.tex.txt](https://github.com/microsoft/vscode/files/4906561/bug.tex.txt)
* commit everything
* open `bug.tex.txt
* 2 characters are not displayed properly and thus appear as change

![image](https://user-images.githubusercontent.com/900690/87227509-cde67080-c39b-11ea-82cb-6ef1a952d321.png)


This is a regression from https://github.com/microsoft/vscode/commit/d3c4b4b4a0683af01748942a004871ae99ef69a5 where I am no longer decoding via `iconv-lite` when the encoding is UTF-8.

@gyzerok @ashtuchkin I might need your help here. Is there anything `iconv-lite` does for UTF-8 that would explain it? My naive assumption would be that for UTF-8, `iconv-lite` is not decoding anything and simply returns the buffer that was given, but stepping through the code with a debugger, I am seeing a few lines where I am not sure if they could be an explanation. For example:

```js
// Returns all complete UTF-8 characters in a Buffer. If the Buffer ended on a
// partial character, the character's bytes are buffered until the required
// number of bytes are available.
function utf8Text(buf, i) {
  var total = utf8CheckIncomplete(this, buf, i);
  if (!this.lastNeed) return buf.toString('utf8', i);
  this.lastTotal = total;
  var end = buf.length - (total - this.lastNeed);
  buf.copy(this.lastChar, 0, end);
  return buf.toString('utf8', i, end);
}
```

**Comment by ashtuchkin** [comment]
Is this utf8 decoding? The problem could be that a utf byte sequence that
corresponds to a single character is split into 2 chunks, so naive decoding
of chunks doesn't work. iconv-lite uses StringDecoder class to handle
situations like this.

**Comment by bpasero** [comment]
@ashtuchkin yes, this is for UTF-8 decoding. 

Can you elaborate on that, trying to understand how I could resolve this in VSCode without having to load `iconv-lite` for UTF-8 at least.

We read the text into 64kb chunks of `Buffer`. Then we call `Buffer.toString()` to get 64kb chunks of text to display in the editor. Is there a better way you say?

Code pointer:

https://github.com/microsoft/vscode/blob/eed137ff2ef7d6b96aa9a7b41307b4c21cda4627/src/vs/editor/common/model/textModel.ts#L79

Interestingly, this seems to be related to our 64kb chunk size. If I change our chunks to be very large (e.g. so that this file fits into a single chunk), the result of `Buffer.toString()` does not reproduce this bug. But of course that would not be a good solution.

**Comment by gyzerok** [comment]
@bpasero I think this is happening when a multi-byte character ends up on the 64kb boundary.

Let's say it is 2 byte character. Then you get 1 byte in the first chunk and 1 in the second. By simply calling `toString()` on the buffers you end up with it being interpreted as 2 single byte characters and thus it gets corrupted.

The solution would be to use streaming converter such as `TextDecoder` or `StringDecoder`. Notice that `TextDecoder` exists in both - browser and node, so likely is a better choice.

**Comment by bpasero** [comment]
@gyzerok thanks, can I ask you to check out this change towards that direction, it seems to resolve the issue with the file at least:

https://github.com/microsoft/vscode/compare/ben/102202

However I can see a test failure from one of your tests now:

```
1) Encoding toDecodeStream - decodes buffer entirely:

      AssertionError [ERR_ASSERTION]: '🖥️💻���' == '🖥️💻�'
      + expected - actual

      -🖥️💻���
      +🖥️💻�
      
      at Context.<anonymous> (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/textfile/test/node/encoding/encoding.test.js:263:20)
```

**Comment by bpasero** [comment]
I am actually not 100% sure `TextDecoder` is stateless, but we seem to be keeping a shared instance around in `VSBuffer` too. Would be good to verify.

**Comment by ashtuchkin** [comment]
TextDecoder is definitely not stateless afaik. It assumes decode() is being called on successive chunks.

**Comment by gyzerok** [comment]
Yeah, I will double Alex here. My understanding is also that `TextDecoder` is stateful, because it might preserve certain bytes in between `decode()` calls.

Going back to the test - it might be that `Buffer.toString()` and `TextDecoder.decode()` use a bit different algorithms of how to convert corrupted bytes to string. However this is not what my test was intended to test. My test was about checking that we are calling `decoder.end()` before ending the stream.

In `toDecodeStream` try to do the following before your change and you will see the error

```diff
// end the target with the remainders of the decoder
-target.end(decoder?.end());
+target.end();
```

Now to make my test work as intended with your change it needs to be changed to the following

```diff
-const expected = incompleteEmojis.toString(encoding.UTF8);
+const expected = new TextDecoder().decode(incompleteEmojis);
```

Then try removing call to `decode.end()` in `toDecodeStream` again to see that it catches the mistake.

**Comment by bpasero** [comment]
@ashtuchkin @gyzerok we seem to share the same instance though in our base `VSBuffer` type:

https://github.com/microsoft/vscode/blob/aa930e56196a1af56cae6d70b0e424fa0e99b824/src/vs/base/common/buffer.ts#L15-L16

Maybe @alexdima as author of this could chime in, but I believe that a text encoder/decoder is not stateful, unless you use the `stream: true` property. In my case likely I should switch to a model where the type is created each time it is needed.

I will try out the suggested changes to fix the test later, thanks.

**Comment by bpasero** [comment]
I pushed this by always creating a new `TextDecoder` instance. Compared to what we had before, we now go through `TextDecoder` when previously we did go through `StringDecoder`. I really hope this does not lead into perf issues where `TextDecoder` is slower for some reason, but I would not expect so given we only use it for `UTF-8`.

**Comment by alexdima** [comment]
:+1: Yes, string decoding/encoding needs to take care that byte sequences are not broken up at chunks starts/ends.

`VSBuffer` shares the same instance of `TextEncoder`/`TextDecoder`, but that is OK, because `VSBuffer` does not give any state guarantees, i.e. users of `VSBuffer.fromString` and `VSBuffer.toString` need to handle chunks edges.
