### ISSUE TITLE
node_modules subdirectory doesn't show up in the UI

### ISSUE THREAD

**Issue by JpnW** [microsoft/vscode#102241]
Issue Type: <b>Bug</b>

After I run npm install or yarn install, the node_modules subdirectory doesn't pop up in the UI. But if I close vscode and reopen it, it appears in the UI.

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:17:14.222Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.34GB free)|
|Process Argv|github-repos|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-apollo|apo|1.16.5
vscode-eslint|dba|2.1.6
emoji-snippets|dev|1.5.3
vscode-babel-coloring|dza|0.0.4
EditorConfig|Edi|0.15.1
prettier-vscode|esb|5.1.3
vscode-styled-components|jpo|0.0.29
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.8
vscode-jest|Ort|3.2.0
open-in-browser|tec|2.0.0

</details>

**Comment by bpasero** [comment]
VS Code is using different file watching strategies depending on your OS and your setup. 

**First thing to check:**
* [ ] I verified that the issue still reproduces in our insiders version (https://code.visualstudio.com/insiders/)
* [ ] I verified that this issue is happening outside of a `node_modules` folder. Our file watcher ignores this folder!

**To find out more about this issue, please first answer this:**
* [ ] What OS are you on
* [ ] Does this happen from an empty workspace, a single-folder workspace or a multi-root workspace?
* [ ] Do you have `files.useExperimentalFileWatcher: true` configured in settings?
* [ ] What is your configured `files.watcherExclude` setting?

**Then please answer the following depending on your setup:**
* [ ] It reproduces with any folder or workspace you open
* [ ] The files/folders you open are on your local disk and not on a network share nor a UNC drive
* [ ] The files/folders you open are not behind a symbolic link
* [ ] The folder(s) opened use the exact same casing as they are on disk
* [ ] It reproduces when I make a change to the file from another VS Code window (either from the editor or the file explorer)

**Then please attach the output of our development console**
* run `code --verbose` from the command line
* perform the action that causes you to not see the file change in VS Code
* attach the output from the console (`Help` > `Toggle Developer Tools` > `Console`)

Thanks for taking the time to fill out this questionnaire.
