### ISSUE TITLE
Node: Prelaunchtask not running on "restart debugging" in June 2020 release

### ISSUE THREAD

**Issue by raufdean** [microsoft/vscode#102296]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Using this launch config:-

 {
        "type": "node",
        "request": "launch",
        "name": "Launch Program",
        "program": "${workspaceFolder}/src/server.ts",
        "preLaunchTask": "tsc: build - tsconfig.json",
        "outFiles": [
          "${workspaceFolder}/build/**/*.js"
        ],
        "outputCapture": "std",
      },

2. Run node debugger
3 Hit "restart debugging", code is not rebuilt
4 Hit stop, then "start debugging", code is rebuilt
5 Downgrade to May2020 and repeat
6 Code is rebuilt on "restart debugging"

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by ChesterYue** [comment]
**Same in launch chrome debug:**

launch.json
``` json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "chrome",
            "request": "launch",
            "name": "Launch Chrome against localhost",
            "url": "http://localhost:8080",
            "webRoot": "${workspaceFolder}",
            "preLaunchTask": "preLaunchTask",
            "postDebugTask": "postDebugTask",
        },
    ]
}
```

task.json

``` json
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "preLaunchTask",
            "type": "shell",
            "command": "echo preLaunchTask",
        },
        {
            "label": "postDebugTask",
            "type": "shell",
            "command": "echo postDebugTask",
        },
    ]
}
```

**Comment by connor4312** [comment]
The problem with not running tasks is that when a session is restarted we only run tasks associated with that session.

https://github.com/microsoft/vscode/blob/eb4a91f7eeb30a96057bcc5f8934ac14171c74dd/src/vs/workbench/contrib/debug/browser/debugService.ts#L615-L624

This is okay -- I can just copy the preLaunch and postDebug tasks into the child session so that they get run. But unfortunately this then causes the `preLaunchTask` to be run twice, once for the root session and then again when the child session is created. I see three possible solutions for this:

1. js-debug runs the tasks manually on restart. Not great since then we don't get problem handling, and it duplicates functionality that might diverge.
1. We make restart take tasks from the root session so that child sessions don't need to have explicit preLaunch/postDebug tasks
1. We additionally add a `preRestartTask` and `postRestartTask`, called only on the session being restarted, in the order
    - `preRestartTask`
    - `postDebugTask`
    - `preLaunchTask`
    - `postRestartTask`

cc @weinand  Since (3) is non-destructive/breaking, I will make that change in VS Code and implement it in js-debug so that Insiders can take it. I'm fine scrapping it and going with a different approach if you have feedback after vacationing 🙂

**Comment by connor4312** [comment]
Users hitting this error -- this requires a change in VS Code itself and therefore is not as simple to get as grabbing the nightly js-debug extension. Instead, you can do one of the following:

1. Get the next VS Code Insiders build where this fix will be released https://code.visualstudio.com/insiders/
1. Set `debug.javascript.usePreview: false` to use the old debugger until the fix is released in VS Code stable.

**Comment by connor4312** [comment]
The VS Code Insiders build (https://code.visualstudio.com/insiders/). It will be released to everyone in the July release.

**Comment by connor4312** [comment]
The July release will be version 1.48.0

**Comment by duzenko** [comment]
> The July release will be version 1.48.0 and will go out early next month

What do you mean by "early"? It's 10th, there's the 1.47.3 update and no 1.48.0

**Comment by connor4312** [comment]
See https://github.com/microsoft/vscode/issues/103792
