### ISSUE TITLE
Ctrl+A no longer selects all in editor when focus is outside

### ISSUE THREAD

**Issue by artaommahe** [Microsoft/vscode#10222]
- VSCode Version: 1.4
- OS Version: Ubuntu 14.04

Steps to Reproduce:

1. Open any file, open terminal
2. Click on empty space in tablist
3. Press 'Ctrl + A'
4. ![_703](https://cloud.githubusercontent.com/assets/1944061/17449545/f25a27b2-5b63-11e6-9b4a-8bd82afa15b6.png)

**Comment by bpasero** [comment]
I can reproduce on Windows and Linux (not on Mac because there the command goes through the menu and does something else). 

@alexandrudima looks like this is caused by the change in https://github.com/Microsoft/vscode/issues/8794#issuecomment-232882323

Previously the editor would register Ctrl+A without any `when` clause and now it requires the editor to have focus. 

This is a pretty bad regression so I would argue to revert that change and revisit the issue with webviews. What do you think?

**Comment by alexandrudima** [comment]
fyi @jrieken The `ctrl+a` change is now going to be reverted.

**Comment by jrieken** [comment]
fyi @f111fei

**Comment by f111fei** [comment]
This means that the second issue in https://github.com/Microsoft/vscode/issues/8794 will appear again in webview.

**Comment by bpasero** [comment]
@f111fei I updated the title of that issue. for the future please file individual issues so that this does not happen.
