### ISSUE TITLE
I am erroneously prompted to 'update git'

### ISSUE THREAD

**Issue by heydojo** [microsoft/vscode#102275]
**VSCode Version Info:**

Version: 1.47.0 (user setup)
Commit: d5e9aa0227e057a60c82568bf31c04730dc15dcd
Date: 2020-07-09T08:02:06.629Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

![4](https://user-images.githubusercontent.com/186629/87240473-c9f53580-c411-11ea-86aa-9b2034d0bfbc.png)

**Steps to Reproduce:**

1. Open a supported vscode file using vscode

Does this issue occur when all extensions are disabled?: No

**What happens:**

1. I am erroneously prompted to 'update git' although git is installed via the [Microsoft Visual Studio Community 2019 installer](https://visualstudio.microsoft.com/vs/community/).

![1](https://user-images.githubusercontent.com/186629/87240518-235d6480-c412-11ea-9fb8-51d0d6b63d0f.png)

2. When I then click on the settings for the vscode git extension, the 'disable' button does not function at all. I don't want this extension or the annoying reminder to update something I don't care about, thanks.

![2](https://user-images.githubusercontent.com/186629/87240552-530c6c80-c412-11ea-85ee-b0bf6d3ff300.png)

So that it is clear as to where and how git is installed here, please see the following image:

![3](https://user-images.githubusercontent.com/186629/87240559-6586a600-c412-11ea-81f7-e7bc2085d3e3.png)

It's fully up to date.

**Further Info:**

My recommendation to the vscode team here is that they maybe try and 'liase' with the team handling Visual Studio 2019. If a git version bump is required, that team will need to do so. But they won't know to do it unless you talk to them. I also find it very strange that developers working on VSCode are installing git adhoc (the portable version I will guess at,) instead of using git for Windows in the Visual Studio installer.

There's no interest here in managing multiple installs of git. I have installed it once and will forget about it and let Visual Studio's installer update git as I pull updates. Sysadmins who provide supported for limited Windows based used accounts likely don't have any interest either.

It would also be really nice if the default expected behaviour to disable the git extension in vscode worked in the screen captured dialog.

I don't use Github at all or often any more, so please don't expect any more from me here.
Thanks.

**Comment by gjsjohnmurray** [comment]
> I also find it very strange that developers working on VSCode are installing git adhoc (the portable version I will guess at,) instead of using git for Windows in the Visual Studio installer.

VS Code doesn't install its own git. It tries to use whatever version you have already installed. The built-in Git extension in your screenshot is the part that connects VS Code to the git it finds on your system.

Strange that the Disable button is inactive on yours. Mine looks like this:

![image](https://user-images.githubusercontent.com/6726799/87248544-de592280-c451-11ea-93de-460002f590e8.png)

Version: 1.47.0 (user setup)
Commit: d5e9aa0227e057a60c82568bf31c04730dc15dcd
Date: 2020-07-09T08:02:06.629Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

If you don't want to use git at all in VS Code, try setting `"git.enabled": false` in your settings.json. But I don't know for sure if that will stop the version warning you're getting. I don't get it because my local git version isn't one that's known to cause problems with VS Code.

If you do use git in your VS Code projects I recommend you upgrade to 2.27 at https://git-scm.com/download/win

**Comment by joaomoreno** [comment]
Does `"git.enabled": false` fix your issue?
