### ISSUE TITLE
Tab scroll not work with Trekstor Primetab

### ISSUE THREAD

**Issue by Stellamaris-ux** [microsoft/vscode#102281]
Issue Type: <b>Bug</b>

cant scroll with tuochpad on tab after update .
kindly fix immediately 

VS Code version: Code 1.47.0 (d5e9aa0227e057a60c82568bf31c04730dc15dcd, 2020-07-09T08:02:06.629Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Celeron(R) CPU N3350 @ 1.10GHz (2 x 1094)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.84GB (0.63GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by Stellamaris-ux** [comment]
after I updated my visual studio code yesterday to the latest version 
VS Code version: Code 1.47.0 (d5e9aa0, 2020-07-09T08:02:06.629Z)
OS version: Windows_NT x64 10.0.18363
other details mentioned in the previous post.

just a few seconds after the update and restarting the application the touchscreen function ceased to work on the app, but works fine in other environments. I can neither scroll up or down with the touchscreen in the studio, I have to keep tapping the scroll bar which is hardly precise on location. I use trekstor primetab with win 10 installed.
I've seen online that I'm not the only one with this problem after updating vsc.
its really frustrating . kindly provide remedy to this .

**Comment by bpasero** [comment]
I wonder if this issue is reproducible when running VSCode in a browser. We allow to run VSCode in a very simplified form in a browser following these steps:
* setup to be able to run VSCode out of sources: https://github.com/microsoft/vscode/wiki/How-to-Contribute
* run `yarn web` from a command line
* it should open a browser with VSCode running

If you are not able to set this up, we also provide a hosted version of VSCode for Web at: https://vscode-web-test-playground.azurewebsites.net. **NOTE**: please give this URL **up to 5 minutes to load**.

Does the issue reproduce in that setup in the browser?
