### ISSUE TITLE
You can connect to the store, but you can't download the expansion file. The setup file cannot be used and to read.

### ISSUE THREAD

**Issue by cjs111208** [microsoft/vscode#102326]
![notOpen](https://user-images.githubusercontent.com/54163641/87264429-87575a00-c4f2-11ea-81c1-bd7436b8fb97.png)
![cannotRead](https://user-images.githubusercontent.com/54163641/87264589-faf96700-c4f2-11ea-8548-d8facf8d89bb.png)

**Comment by sandy081** [comment]
Please follow these steps

- Help -> Toggle Developer Tools -> Network
- Then check for any network failed requests while browsing and installing the extensions if found all requests fails then its probably a proxy or DNS issue at your end.
- To confirm its a DNS issue check if you can access this page https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default, if you cannot please try configuring your DNS like pointing to 1.1.1.1 as suggested here? https://1.1.1.1/dns/. Otherwise please contact your network administrator.
- If it is not a network issue, please share the logs from the following locations
    - Help -> Toggle Developer Tools -> Console
    - View -> Command Pallette... -> Toggle Shared Process -> Console
    - View -> Open View… -> Log (Shared)
    - View -> Open View… -> Log (Window)
