### ISSUE TITLE
任务终止不了

### ISSUE THREAD

**Issue by 1002237913** [Microsoft/vscode#10237]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 10.0.10586

vscode中两个文件的配置片段如下：
package.json
"scripts": {
    "mon": "start /B nodemon --harmony --use-strict app.js && start /B webpack --watch"
  },

task.json
        {
            "taskName": "mon",
            "args": ["run", "mon"]
        },

然后执行命令 ：task mon
运行很正常，但是永远都终止不了这个任务了而且vscode也无法关闭

**Comment by aeschli** [comment]
From google translate:

Configuration snippet vscode two files as follows :
package.json
"Scripts": {
"Mon": "start / B nodemon --harmony --use-strict app.js && start / B webpack --watch"
} ,

task.json
{
"TaskName": "mon",
"Args": [ "run", "mon"]
} ,

Then execute the command : task mon
Run normal, but not always terminate this task can not be closed and vscode

**Comment by PowerSnail** [comment]
Translation:

The two snippets in the configuration file of vscode are as follows:
```
package.json
"scripts": {
"mon": "start /B nodemon --harmony --use-strict app.js && start /B webpack --watch"
},
```

```
task.json
{
"taskName": "mon",
"args": ["run", "mon"]
},
```

When I execute the command: `task mon`, it runs, but there is no way to terminate the task and vscode cannot be closed.

**Comment by dbaeumer** [comment]
To terminate the task do F1 > Terminate Running Task.

You should also being able to close VS Code. What is preventing it?

**Comment by 1002237913** [comment]
@dbaeumer  
use Open with vscode：
https://github.com/1002237913/VsCodeBug.git
https://github.com/1002237913/VsCodeBug

**Comment by dbaeumer** [comment]
@1002237913 thanks for the nice reproducible case.

**Comment by 1002237913** [comment]
Thanks!  @aeschli @PowerSnail  @dbaeumer

**Comment by dbaeumer** [comment]
Interestingly when executed from a cmd prompt I can't cancel this as well since it always starts a new 'ping'

**Comment by dbaeumer** [comment]
The only way I found to get out of this is to close the cmd which started the command.

**Comment by dbaeumer** [comment]
This is actually very tricky since the cmd.exe doesn't have any commands to find the background tasks spawned from it. The background tasks are not child tasks of VS Code anymore and destroying the streams doesn't help either since they are owned by the conhost. Sending Ctrl+Break didn't help either.

At the end of the day there is little VS Code can do since I haven't found a way to find the background tasks started. All I can do is to warn the user about this (since I know the stream isn't closed) and allow to exit VS.

@1002237913 one thing that does work for me is if the last start command has /WAIT in it. Then the cmd.exe doesn't terminate and the process tree is in tact. In our example:
```
"bug": "start /B ping /t localhost && start /B /WAIT ping /t localhost "
```

Will this work for me.

**Comment by dbaeumer** [comment]
I found no way to kill the background tasks since I didn't find a way to query for them. If someone knows how, please let me know.

I changed VS Code so that you can still exit. But it will warn you about the situation and you have to double confirm the exit.
