### ISSUE TITLE
More feature for markdown 

### ISSUE THREAD

**Issue by the1900** [Microsoft/vscode#10235]
- VSCode Version: 1.4.0
- OS Version: Windows 10 x64

First of all, How could I know which classes or elements to customize markdown preview? I read many time on official docs and articles but I couldn't find yet. When I change styles body element then not only preview but also all of UI were adjusted.

I'm migrating to VS code from sublime text 3. This editor is cool I love it. But writing markdown I wish some features added on next version. Well I may make a extension some day.

**Auto paired & Auto deleting like brackets**

I wish VS code add pair when I insert asterisk on words or sentences both begin of & end of. It would be pleasure to delete another pair too. I saw brackets are worked exactly what I want.

**Comment by mjbvz** [comment]
For the auto brace completion, in markdown files we already complete on `(` and `{` and `[`. Complting on `*` may end up annoying users, since a single `*` can also be used for a list.

----

For the markdown preview itself, we're using [markdown it](https://markdown-it.github.io) to render the preview. [You can use your own css for this preview](https://code.visualstudio.com/Docs/languages/markdown#_using-your-own-css) and this css should not leak outside of the preview frame.

To actually inspect the contents of the preview, either use markdown it directly, or, in VSCode with the markdown preview open:

* Go to `Help -> Toggle Developer Tools`
* Run `document.getElementsByTagName('webview')[0].openDevTools()` in the console to open the developer explorer for the markdown preview itself.
* Use the newly opened  developer tools pane to explore the structure of the markdown document and inspect how style rules are applied.

Please let me know if that did not address your questions or if you run into any problems.

Thanks.
