### ISSUE TITLE
Add a setting or always restore the last editor state for editors opening in new groups

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#102485]
While working on https://github.com/microsoft/vscode/issues/101356 I have noticed that `EditorMemento` has an issue because it stores stated based on `group#id` and that keeps changing. These steps

* have an editor
* split the editor - it's now in group 2, no memento state found
* close the 2nd editor, state is persisted for group 2
* split again - it's now in group 3, no memento state found
* close the 2nd editor, state is persisted for group 3
* split again - it's now in group 4, no memento state found
* this repeats...

The capture below shows the memento for a notebook that I have opened (split) and closed a few times

<img width="579" alt="Screenshot 2020-07-14 at 13 07 15" src="https://user-images.githubusercontent.com/1794099/87418974-f4422100-c5d2-11ea-831a-6a562f9a37ad.png">

**Comment by bpasero** [comment]
@jrieken if a group is closed, view state is not restored the next time the group is opened again because it may be frustrating for users to constantly get old view state back in that case. Imagine you had an editor split for a while and then forgot about it after closing. You then split the editor again and would probably expect the split editor to show you the location where you split from, not some state from the past. 

There is code on shutdown that will remove groups from the memento that no longer exist:

https://github.com/microsoft/vscode/blob/2a8c8def27726127d8fe86dfb2a126c9f3f54516/src/vs/workbench/browser/parts/editor/baseEditor.ts#L338-L339

I am not sure what exactly you expect how the editor memento should behave, maybe you can clarify that.

**Comment by jrieken** [comment]
> frustrating for users to constantly get old view state back in that case.

I actually want that and isn't that how the first group behaves? Then I wonder why view state is persisted at all as it won't ever be re-used, right?

**Comment by bpasero** [comment]
@jrieken yes first group is special because you are not starting from a specific group, you open your first initial editor and then there is no existing state to copy from. In that case restoring from the previous one seems ok to me.

**Comment by jrieken** [comment]
I understand the problem with split but what I often do is `cmd+2` to get a new, empty group and when I open a file it never has a view state. The scenario is very similar to the "group 1 case" but works different

**Comment by bpasero** [comment]
I am not brave enough to make that change to be honest, but I added a `fallbackToOtherGroupState?: boolean` to `loadEditorState()` that can optionally be passed in to fallback to the editor state of the last active group. If this makes sense for notebooks it means that a notebook in a new group without previous state will inherit the state from the last group that was active.

**Comment by jrieken** [comment]
Sorry, re-opening as paper cut. This is my biggest issue when working with side editors. I very often open an editor to side to look something up, then close it (with the whole group), just to re-open it very shortly after. I then have lost the view state (scroll position etc).

I understand the concern of breaking existing users but this could be a setting

**Comment by bpasero** [comment]
Yeah I think something like this would be needed:
* anytime editor state is persisted into the memento, it is also stored in a location that is independent from the group id
* whenever we pickup editor state for a new editor, we fallback to that last state we know of unless we have a more specific one for the group
* we might want to have this behind a setting, but maybe it should actually be on by default because I think it is nice to restore things like folded regions across groups

One scenario we currently do not support is the following:
* you open an editor and accumulate view state (selection, folding, etc)
* you open a new group to the side
* via quick open you pick the file that is already opened
* since the editor did not change in the original group, we do not save state to the memento, we only do that if the input changes for an editor or gets closed
* if we wanted to support this scenario as well, we would need to explicitly ask the editor to save state when the same editor is opened in another group

**Comment by bpasero** [comment]
Added a new setting `workbench.editor.sharedViewState` to control this. Not super convinced with the name yet, maybe you have a better idea.

Enabling this setting will:
* always store the last memento that is persisted in a location that is group independent (aka survives group lifecycle)
* will use this memento if not more specific memento in a group is found

![recording](https://user-images.githubusercontent.com/900690/125089185-72de7b00-e0ce-11eb-9643-2ecfabd65058.gif)

From the gif, even though new (unknown) groups are opened, the files that open within get the state that was last persisted.

**Comment by jrieken** [comment]
Thank you

**Comment by alexr00** [comment]
@mjbvz do you know the steps to verify this?

**Comment by roblourens** [comment]
I tried but I don't understand this, I think I am following the same steps in the gif and descriptions but it doesn't load the persisted view state.

**Comment by rzhao271** [comment]
I also tried replicating the gif. When I split the editor, another copy of the file with the same highlighting shows up. I have both the restore and share settings enabled.

**Comment by mjbvz** [comment]
I marked this as verified based on the following test:

1. Enable workbench.editor.sharedViewState
2. Open a file to the side of the current editor
3. Scroll partway down in this file and make a selection
4. Close the entire editor group
5. Now re-open the same file to the side of the current editor and confirm that the view position and selection are restored

**Comment by roblourens** [comment]
> Now re-open the same file to the side 

How are you doing this? I am just curious now, it doesn't really matter, but I still don't see it

**Comment by bpasero** [comment]
Thanks for figuring it out, the steps are 👍
