### ISSUE TITLE
VSCode includes components under a non-free license

### ISSUE THREAD

**Issue by DemiMarie** [Microsoft/vscode#10249]
- VSCode Version: git HEAD
- OS Version: Any

Steps to Reproduce:
1. Clone VSCode repository
2. Read ThirdPartyNotices.txt
3. Find the non-free "%% HTML 5.1 W3C Working Draft NOTICES AND INFORMATION BEGIN HERE" section.

All components under this non-free license should be removed from VSCode or placed in a separate directory that can be removed before building without impacting the ability to build VSCode.

**Comment by siegebell** [comment]
@DemiMarie [GNU.org considers the 2002 W3C software to be "free software"](https://www.gnu.org/licenses/license-list.en.html#W3C). The [current (2015) W3C software license](https://www.w3.org/Consortium/Legal/2015/copyright-software-and-document) appears to be compatible. 

What are you referring to exactly?

**Comment by alexandrudima** [comment]
To keep the number of issues in our inbox at a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: we look at the number of votes the issue has received and the number of duplicate issues filed. Thank you for your time and understanding.

If you disagree and feel that this issue is crucial: we're happy to listen and to reconsider.
