### ISSUE TITLE
skipping node_internals not working when debugging via attach

### ISSUE THREAD

**Issue by craigphicks** [microsoft/vscode#102412]
> - VSCode Version:

```
$ code --version
1.47.0
d5e9aa0227e057a60c82568bf31c04730dc15dcd
x64
```

> - OS Version:

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic
```

> - node version
 
```
$ node  --version
v10.16.3
```

> Steps to Reproduce:

0. set up launch json with attach process option:
```
    {
      "type": "node",
      "request": "attach",
      "name": "Attach by Process ID",
      "processId": "${command:PickProcess}",
      "skipFiles": [
        "<node_internals>/**"
      ]
    },
```
1. select both 'caught exceptions' 
2. attach a running `node` process; it will automatically stop at main module top (good).
3. do continue
4. it stops on internals exception, e.g.,
```
Exception has occurred: Error: No such module: pipe_wrap
  at internalBinding (internal/bootstrap/loaders.js:104:17)
 ```

> Does this issue occur when all extensions are disabled?: Yes/No

Yes

EDIT:  Same behavior even if "select both exceptions' is not performed until debugger has stopped at first line of entry file.

**Comment by connor4312** [comment]
Maybe related: https://github.com/microsoft/vscode-js-debug/issues/565

**Comment by coder-mike** [comment]
I've found a simpler setup that causes this, at least for me (I'm assuming it might be the same issue).

Minimal example code here: https://gist.github.com/coder-mike/638d4d2af1445b6cbe9d65c25e2038fb

- file1.js imports file2.js
- file2.js throws an exception and catches it
- In VSCode, enable breakpoints on "Caught Exceptions"
- Launch debugger. It will break on the exception in `file2.js`, even though `file2.js` is in the skip list.

**Interestingly**, if I first set a manual breakpoint at _beginning_ of `file1.js`, to effectively "stop on entry", then when I _continue_ execution from that point it does _not_ break on the exception.

Environment:
 - Windows
 - VSCode 1.47.0 (`d5e9aa0227e057a60c82568bf31c04730dc15dcd`, x64)
 - Node: v14.3.0

**Comment by craigphicks** [comment]
@coder-mike 

In fact, I am familiar with not setting breaks for exceptions until the first line of entry file has been automatically stopped at, and I tried that this time, but neglected to put it in my report.  Also I tried setting a breakpoint on the first line to see if that would would make a difference.  Based on past experience I would expect that to work, but this time it doesn't.

**Comment by craigphicks** [comment]
@connor4312   Thanks Connor.

**Comment by connor4312** [comment]
Thanks for the issue and repro!

@coder-mike  Previously skip skipping was asynchronous to the loading of the source, since we used to hash the file on disk as part of the verification process (which was relatively slow). However, we no longer need this step and I remove the unnecessary async part in https://github.com/microsoft/vscode-js-debug/commit/f52fbc2fbca6486cb5ac6b3b17e5838a2323b2f8 which solves the issue.

Us telling V8 that a script should be blackboxed _is_ still async, so it's possible that an exception is hit before blackboxing is processed, but now that there's no artificial 500ms debounce, doing so is very fast.

This is fixed in the [nightly build](https://github.com/microsoft/vscode-js-debug#nightly-extension) of js-debug.

@craigphicks I believe I fixed your issue in https://github.com/microsoft/vscode-js-debug/issues/603 -- we just weren't applying blackboxing correctly to node_internals, and our test case for it was broken. This will be fixed in the upcoming [nightly build](https://github.com/microsoft/vscode-js-debug#nightly-extension) at 5 PM PST today.

/duplicate
