### ISSUE TITLE
Inconsistent and Faulty `autoClosingPairs` Behavior  

### ISSUE THREAD

**Issue by cloudRoutine** [Microsoft/vscode#10242]
In F# we have a set of bounding punctuation pairs that can't be implemented properly within the constraints of the current `language-configuration.json` options

``` fsharp
    [ ] , [< >] , [| |] 
    ( ) , (| |) , (* *)
     <@ @> , <@@ @@>
```

The following are the results of testing with a `language-configuration.json` file that only included `"autoClosingPairs":[ ... ]`

``` js
  "autoClosingPairs": [
    ["(|", "|)"],   // fails       
    ["[|", "|]"],   // works
    [ "(*", "*)" ]  // works
  ]
```

There are some hacky workarounds but each one introduces a different kind of undesirable behavior

``` js
  "autoClosingPairs": [
   ["[", "]"],      // works
   ["(", ")"],      // works
   ["(|", "|"],     // fails
   ["[<",">"],      // works
   ["[|", "|"],     // fails
   [ "(*", "*" ],   // fails 
   ["<@", "@>"],    // works 
   ["<@@", "@"]     // fails              
  ]
```

The `<@@ , @` case fails differently than the others which simply refuse to complete.
`|` is representing the cursor in the following example
`<@|` -> `<@|@>` -> `<@@|>` 
the second key input of `@`, it overwrites the `@` that was generated by the completion

This approach creates another issue where if there is already a `[` in the editor and you type `<` next to it, it completes to `[<>`

Inserting a space after the first character works in some instances but not others

``` js
  "autoClosingPairs": [
   ["[ ", "]"],      // fails
   ["( ", ")"],      // works
   ["(|", "|)"],     // fails
   ["[<",">]"],      // works
   ["[|", "|]"],     // works
   [ "(*", "*)" ],   // works
   ["<@ ", "@>"],    // fails 
   ["<@@", "@@>"]    // works              
  ]
```

But even if this were to work in all of these instances it'd still be an undesirable approach since `()` is an operator keyword in F# and more often than not a space following `[` or `(` is undesirable
- VSCode Version: 1.4.0
- OS Version: Windows 10 Pro | Version 1607 | OS Build 14393.10

**Comment by rmunn** [comment]
Regarding the following paragraph:

> This approach creates another issue where if there is already a `[` in the editor and you type `<` next to it, it completes to `[<>`

My preference would be for the following behavior:

- If I've got `[]` and my cursor is between the two brackets, typing `<` will autocomplete `>`, giving me `[<>]` with the cursor between the `<` and `>`, ready to type an attribute name like `[<Test>]`.

- If I've got `[` not immediately followed by `]`, with the cursor immediately after the `[`, then I probably don't want to autocomplete `<`. BUT...

- If I'd highlighted some text that's contained inside square brackets, and I type `<`, I probably want to surround that text with angle brackets. E.g. if I have `[Test]` and I've highlighted the word `Test` and pressed `<`, I probably want to change that into `[<Test>]`.

The behavior I'd like to see for the `[|` and `|]` brackets (used for F# arrays) is similar:

- If I've got `[]` and my cursor is between the two brackets, typing `|` will autocomplete with a second `|`, giving me `[||]` with the cursor between the two `|` characters, ready to type an array like `[|1;2;3|]`.

- If I've got `[` not immediately followed by `]`, with the cursor immediately after the `[`, then I probably don't want to autocomplete `|`. BUT...

- If I'd highlighted some text that's contained inside square brackets, and I type `|`, I probably want to surround that text with a pair of `|` inside the existing square brackets. E.g. if I have `[1;2;3]` and I've highlighted the text `1;2;3` and pressed `|`, I probably want to change that into `[|1;2;3|]`.

Same thing with the `(|` and `|)` brackets: I'd like to be able to highlight text inside parentheses, press `|`, and have it become text surrounded by `(|` and `|)`. But if I press `|` when not immediately next to a `(` or `[` character, I probably don't want to autocomplete it.

**Comment by cloudRoutine** [comment]
There's nothing I can do about this, see - https://github.com/Microsoft/vscode/issues/10242

**Comment by aeschli** [comment]
"autoClosingPairs": [
    ["(|", "|)"],   // fails       
    ["[|", "|]"],   // works
    [ "(*", "*)" ]  // works
  ]
and
  "autoClosingPairs": [
   ["[ ", "]"],      // fails
   ["( ", ")"],      // works
   ["(|", "|)"],     // fails
   ["[<",">]"],      // works
   ["[|", "|]"],     // works
   [ "(*", "*)" ],   // works
   ["<@ ", "@>"],    // fails 
   ["<@@", "@@>"]    // works              
  ]

got fixed in the meantime. I verified in the January build.
Please file your suggestions as separate feature requests.

**Comment by rmunn** [comment]
This bug isn't really fixed AFAICT. In my VS Code installation (version 1.9.1 on Windows 10), I get the following behavior when editing F# files:

- If I type `{`, it autocompletes `}`. Hitting backspace at this point deletes the `{}` pair. **Good**.
- If I type `(`, it does NOT autocomplete `)`, because it's waiting to see whether I type a second key. **Bad**; I wanted to get `()`.
- If I type a space, I then get the closing `)` inserted after the space (so it looks like `( )`), but if I then backspace twice, the first one deletes the space and the second one deletes *only* the opening parenthesis. **Bad**; I wanted the opening *and* closing parentheses to be deleted at that point, just like with `{}`.
- Same with `[`: typing `[` does not create a matching `]` because it's waiting for another keystroke. **Bad**; I wanted to immediately get `[]`.
- If I type `[<`, it fills in `>]` for me. **Good**, but see below.
- If I type `[<`, it fills in `>]` for me so that I have `[<>]`. But if I then press backspace, it only deletes the `<`. I wanted it to delete the entire `<>` so that I would end up with `[]`. **Bad**.

And so on. As far as I can tell, the entire behavior of auto-closing pairs is still inconsistent and faulty, and gives a bad experience when writing F# code. I don't think this issue is solved yet.

BTW, my `language-configuration.json` file from Ionide is unchanged from Ionide's defaults, and looks like this:
```json
{
  
  "comments": {
   "lineComment": "//",
   "blockComment": [ "(*", "*)" ]
  },
 
 "autoClosingPairs": [
   ["[ ", "]"],
   ["( ", ")"],
   ["{", "}"],
   ["<@", "@>"],
   ["``", "``"],
   ["\"", "\""],
   ["(|", "|)"],  
   ["[<",">]"],     
   ["[|", "|]"],		
   ["(*", "*)" ], 
   ["<@@", "@@>"] 
 ],
    
  "surroundingPairs": [
   ["<@@", "@@>"],
   ["(|", "|)"],
   ["[<",">]"],
   ["[|", "|]"],
   ["{", "}"],
   ["[", "]"],
   ["(", ")"],
   ["\"", "\""],
   ["\"\"\"", "\"\"\""],
   ["(*", "*)"],
   ["<@", "@>"],
   ["'", "'"]
  ],
  
  "brackets": [
   ["(", ")"],
   ["(*", "*)"],
   ["{", "}"],
   ["[", "]"],
   ["[|", "|]"],
   ["<@", "@>"],
   ["<@@", "@@>"]
  ]
}
```

**Comment by aeschli** [comment]
You bring up new issues... Backspace not deleting the autoclosed bracked is clearly a bug, the other mentioned issues are more like feature requests. Please file separate issue so they can be discussed one by one.
