### ISSUE TITLE
New debugger hangs on reeentrace function..

### ISSUE THREAD

**Issue by u1pns** [microsoft/vscode#102459]
Hey there,

Im debugging a reentrancy function that runs on nodejs, and the debugger hangs executing it...
Any advice?

Tnx

Joan

**Comment by u1pns** [comment]
Just to clarify; same code, with the old version debugger, worked perfectly while debugging. Now, it stucks while calling a reentrancy function...

**Comment by artu-ole** [comment]
@u1pns I believe your issue might be better suited at https://github.com/microsoft/vscode-js-debug/issues

**Comment by connor4312** [comment]
Can you collect a trace log using these instructions?

> If you're able to, add `"trace": true` to your `launch.json` and reproduce the issue. The location of the log file on your disk will be written to the Debug Console. Share that with us.
>
>⚠️ This log file will not contain source code, but will contain file paths. You can drop it into https://microsoft.github.io/vscode-pwa-analyzer/index.html to see what it contains. If you'd rather not share the log publicly, you can email it to connor@xbox.com

/needsMoreInfo

**Comment by connor4312** [comment]
Since the issue bot bumped this: I have seen occasional reports of Node on 12.x hanging with a debugger attached at seeingly random places. As far as I can tell this is/was an issue with Node and users reported this was resolved by updating to a more recent Node version. That may be what you're running into...
