### ISSUE TITLE
Visual separation between staged and unstaged files in Source Control window

### ISSUE THREAD

**Issue by jonathantwite** [microsoft/vscode#102473]
When viewing the Source Control window in "Tree View" mode, the folder structure is shown as an indented heirachy.  When some files are staged and some are not, the staged files are "grouped" and displayed in (visually at least) another folder.  This makes it difficult to identify quickly

* Which files are staged and which are not
* Where the boundary between the staged and not-staged files lies.

It would be easier if their was either a differentiation between the "actual code" folders and the "Staged Changes" and "Changes" Folders, or a space between the two staged and not staged sections.

For example:
![vscode-sc](https://user-images.githubusercontent.com/13119611/87404176-b84c9300-c5b5-11ea-8f5f-6a120d39f7cd.JPG)

A heading bar like the "GROUP" bars on the "OPEN EDITORS" section of the Explorer window may be good:
![vscode-ex](https://user-images.githubusercontent.com/13119611/87404767-796b0d00-c5b6-11ea-9cee-ab14e1bf8414.JPG)

**Comment by gjsjohnmurray** [comment]
IIRC, prior to 1.47 the 'Staged Changes' and 'Changes' headers were rendered as 'STAGED CHANGES' and 'CHANGES'. This happened because [SourceControlResourceGroup](https://code.visualstudio.com/api/references/vscode-api#SourceControlResourceGroup) items were always forced to UPPERCASE. I think it's good that this no longer happens, since some SCMs use ResourceGroups for purposes where case can be important. But it ought to be easy enough for the (built-in) Git extension to uppercase its ResourceGroup labels.

**Comment by joaomoreno** [comment]
Thanks for the input, merging with https://github.com/microsoft/vscode/issues/102118
