### ISSUE TITLE
Allow remote debugging with local source

### ISSUE THREAD

**Issue by pfalson** [microsoft/vscode#102525]
When using remote-ssh gdb debugging it would be nice to be able to open a workspace folder locally for situations where you do not (and do not want to) have the source on the target machine.

**Comment by weinand** [comment]
You can always open another workspace folder locally (in a new VS Code window) even if you are debugging remotely.
But the (remote) debugger will not automatically use source from that local workspace. 

Since the remote debugger has no access to your local files, it cannot use them (and there is no way that VS Code can provide transparent access to them).

An alternative is to use "classic" remote debugging (without the "remote-ssh" extension). Some debuggers can attach to a remote debuggee. In this case the debugger runs locally and has full access to the local source.

**Comment by pfalson** [comment]
I only thought that as vscode is (in my case) running locally and issuing gdb commands over ssh that you could facilitate a mapping (like phpstorm does).

**Comment by weinand** [comment]
Yes, a debug extension could easily support this ( as we do for the JS/node debuggers).
Please file a feature request against the gdb debug extension.
