### ISSUE TITLE
It is recommended to change snippetsPreventQuickSuggestions to false by default

### ISSUE THREAD

**Issue by Despoinis** [microsoft/vscode#102580]
This default behavior is easily misunderstood as a bug, and I have seen more than one person asking this question.
In fact, I don’t know what is the case to set it to true, can you give an example?
In contrast, I think even this situation is rare.

**Comment by jrieken** [comment]
This is controversial because there is an equal of people on the "other side" that wanted the behaviour you dislike. We cannot make everyone happy and therefore there is a setting. Changing the default will confuse folks and I have plan of doing so.

**Comment by Despoinis** [comment]
> 
> 
> This is controversial because there is an equal of people on the "other side" that wanted the behaviour you dislike. We cannot make everyone happy and therefore there is a setting. Changing the default will confuse folks and I have plan of doing so.

I understand what you mean, but at least I want to know when I need to set it to true. I have never encountered this kind of demand when developing websites with vscode.

**Comment by jrieken** [comment]
Snippets prevent quick suggestions because it is otherwise impossible to type and tab through a snippet. E.g. insert a snippet with multiple tab stops, tab to the first, type, quick suggest shows, press tab, suggestion is inserted but next tab stop should have been selected. That means, out of the box, tab stops don't work or at least they don't work well. Therefore quick suggestions are disabled when snippet mode is active, suggestion can still be triggered manual (usually via ctrl+space) or via trigger characters but they don't get in you face and prevent you from navigating through a tab stops
