### ISSUE TITLE
Moving SCM viewlet breaks badge

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#102578]
Version: 1.48.0-insider (user setup)
Commit: c828a5339bca7222fd8f56ab98361a98f736d185
Date: 2020-07-14T05:39:53.264Z
Electron: 8.3.3
Chrome: 80.0.3987.165
Node.js: 12.13.0
V8: 8.0.426.27-electron.0
OS: Windows_NT x64 10.0.19041

Steps to Reproduce:
1. Modify a file in the workspace so that there is a change in the SCM viewlet
2. Move SCM viewlet from the activity bar to bottom panel (ex: after Problems)
3. Move the SCM viewlet back into the activity bar

Expected behavior: badge should show 1 change
Actual behavior: no badge is being shown

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
@sbatten What's the recommendation here? The badge is currently placed on the view container: https://github.com/microsoft/vscode/blob/4b9c19ab032aaca54f60f937ab325eb00f59f984/src/vs/workbench/contrib/scm/browser/activity.ts#L185-L185 Is there any way to place it on the view, and let the container figure out what should happen?

**Comment by sbatten** [comment]
@joaomoreno see `markers.ts` change here https://github.com/microsoft/vscode/commit/921b9a92a1b662fbe3aa21f47b0f8ed1fd89c947

**Comment by joaomoreno** [comment]
@sbatten Thanks for the pointer.

I believe @sandy081 should've instead added a `activityService.showViewActivity` method instead of having this util that everyone must use. I've refactored his code and added that method to the activity service: https://github.com/microsoft/vscode/commit/8e00e24e2bb18907fd2fa36f136b771bc60b38fa

That just made this fix much simpler: https://github.com/microsoft/vscode/commit/d9e3ecba9e11d0e7dbc622211e5f5d90dde97cfe
