### ISSUE TITLE
VScode Can't Find tsserver

### ISSUE THREAD

**Issue by davidtaylorjr** [microsoft/vscode#102527]
- VSCode Version: 1.47.0 (But does the same thing on Insiders Build)
- OS Version: Windows 10 Professional

Steps to Reproduce:

1. Load a .ts file
2. Receive following error: AppData/Roaming/npm/node_modules/typescript/lib doesn't point to a valid tsserver install. Falling back to bundled TypeScript version.

Does not matter that npm install of global typescript has occured.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by IllusionMH** [comment]
/needsMoreInfo

Please fill all fields required by issue template (VSCode verions, OS version).

Do you have custom `typescript.tsdk` value in User or Workspace config?
Because it should end with `...node_modules/typescript/lib` but your message has `...node_modules/typescript/bin`

Is it reproducible with all extensions disabled?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`

**Comment by davidtaylorjr** [comment]
@IllusionMH yes it does end with lib, I was trying something else to see if I could get it to work and forgot to change it back.

**Comment by davidtaylorjr** [comment]
@IllusionMH it also does it when reloading with extensions disabled.

**Comment by IllusionMH** [comment]
Can you share your `typescript.tsdk`? Do you have spaces in user name? Is TS install actually there (installed with npm without nvm etc.)?
Have you tried full path with Windows separatoes e.g. `"typescript.tsdk": "C:\\ts-location\\node_modules\\typescript\\lib",`? May need to escape spaces in path, but not sure if required.

**Comment by davidtaylorjr** [comment]
@IllusionMH not exactly sure what you are asking of me.  No there are no spaces in the username.  And yes TS install is actually there.

**Comment by davidtaylorjr** [comment]
So I removed the setting and am just using the fallback and/or workspace install and it is working fine.
