### ISSUE TITLE
MERGE folder w/ same name instead of REPLACE while drug'n'drop

### ISSUE THREAD

**Issue by chiboreache** [microsoft/vscode#102505]
i feels now like - **fuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu**

i can't even imagine that there would be something really that destructive, what i shame....................

**Comment by chiboreache** [comment]
EXPLORER is the scope of VSCODE!

**Comment by flisboac** [comment]
I feel you. I assumed VSCode would do the sane thing, which is to merge folders with the same name, but no, it erased all previous files in the destination folder.

Such a bad user experience.

My disappointment is immeasurable, and my day is ruined. :((

Now, if I cared to be reasonable and at least read the prompt, I'd not be in this situation of losing literal days of work, but still...

Can this be improved, somehow?

Also, @isidorn, care to elaborate why this is out of scope?

**Comment by chaeyan** [comment]
bump

**Comment by macks2008** [comment]
I'm also a bit bothered by this behavior. I assumed the default behavior of the second prompt (which I was expecting) would be to merge folders if I clicked yes, since that's what Windows Explorer (the only other Microsoft product I had to go off of with regard to visually moving folders around) does with folder name conflicts. I admit to being hasty with the prompt, and obviously any important work should have been saved to version control (another mistake of mine, though apparently not my mistake alone. So what have we all learned about commit frequency?), but is it out of scope just because "well user error, didn't read the prompt, too bad"?

**Comment by novellat** [comment]
bump

**Comment by osdeverr** [comment]
Bump.

**Comment by azeunkn0wn** [comment]
Bump. This is really bad UX.
