### ISSUE TITLE
JSX doesn't define a line comment token

### ISSUE THREAD

**Issue by OliverJAsh** [microsoft/vscode#102609]
Duplicate of https://github.com/microsoft/vscode/issues/102403 which was prematurely closed—the behaviour I described is still not working as expected.

---

- VSCode Version: latest
- OS Version: macOS latest

Steps to Reproduce:

1. Create a snippet with config
   ```json
   {
     "TODO": {
       "prefix": "todo",
       "body": "$LINE_COMMENT TODO: "
     }
   }
   ```
2. Inside JSX, run the snippet (place cursor after `todo`, open suggestions, then execute)
   ```jsx
   <div>
       todo
       hello, world!
   </div>
   ```

Actual:

```jsx
<div>
    // TODO: 
    hello, world!
</div>
```

Expected:

```jsx
<div>
    {/* TODO:  */}
    hello, world!
</div>
```

This is how the "add line comment" works, so I would expect the snippet variable to behave similarly.

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment]
@mjbvz bottom line is that the snippet refers to the line comment token which doesn't exist. Unsure if it could exist tho

**Comment by mjbvz** [comment]
Yes I don't think there is such a thing as a line comment in JSX.

Not sure how we want to handle this for snippets. I don't think the example expected behavior for  `$LINE_COMMENT` fits with how any other snippet variables work. It looks like what @OliverJAsh is after is a way to mark part of a snippet output as being commented using logic that matches the line comment command in VS Code (which falls back to a block comment if line comments aren't supported). I don't know how that would fit into our current snippet syntax

Short term, we may want to have `$LINE_COMMENT` fallback to an empty string for languages that don't support line based comments

**Comment by jrieken** [comment]
> Short term, we may want to have $LINE_COMMENT fallback to an empty string for languages that don't support line based comments

That's the default behaviour for snippet variables. Falling back to the block comments isn't an option for snippets because they get invoked different and without context.

I all honestly, if you write a snippet for jsx and inserts a comment, then use the block comment variables. That's a very simple workaround.

**Comment by OliverJAsh** [comment]
> I all honestly, if you write a snippet for jsx and inserts a comment, then use the block comment variables. That's a very simple workaround.

It's not really a suitable workaround for the snippet example I gave. I want a snippet that inserts a `TODO` comment, using line comments where possible and otherwise falling back to block comments (e.g. inside JSX or CSS). For context, I'm assigning this snippet to a keyboard shortcut so I can easily insert `TODO` comments no matter where I am (instead of manually creating a line/block comment and then writing `TODO: `).
