### ISSUE TITLE
Snippets - Placeholder-Transform for 2nd (or further) variables.

### ISSUE THREAD

**Issue by brunotacca** [microsoft/vscode#102624]
- VSCode Version: 1.47.1
- OS Version: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Create a new snippet:
```
"bonjourSnippet": {
        "prefix": "bonjourSnippet",
        "body": "$1 ${1/(.*)/${1:/capitalize}/} $2 ${2/(.*)/${2:/capitalize}/}"
},
```
2. Launch the new snippet in any code.
3. Type `zxcv`
4. Press tab once. The first variable will get capitalized.
5. Type `abcd`.
6. Press tab again. The second variable first entry will be registred, but the second entry with the transformation is being erased somehow.

Expected output:
```
zxcv Zxcv abcd Abcd
```

Real output:
```
zxcv Zxcv abcd 
```

Does this issue occur when all extensions are disabled?: Yes

Thanks.

**Comment by ArturoDent** [comment]
Use this as the `body`:

`"body": "$1 ${1/(.*)/${1:/capitalize}/} $2 ${2/(.*)/${1:/capitalize}/}"`

In the replace section of the transform the `${n}`'s , as in `/${2:/capitalize}/` refer to **capture groups**, not to your `$2` tabstop.  So you want `$1` in the replace to refer to your first (and only) capture group.

Your code replaces all of the second tabstop with capture group 2 (capitalized) which is nothing since you didn't have a capture group 2.

**Comment by brunotacca** [comment]
> Use this as the `body`:
> 
> `"body": "$1 ${1/(.*)/${1:/capitalize}/} $2 ${2/(.*)/${1:/capitalize}/}"`
> 
> In the replace section of the transform the `${n}`'s , as in `/${2:/capitalize}/` refer to **capture groups**, not to your `$2` tabstop. So you want `$1` in the replace to refer to your first (and only) capture group.
> 
> Your code replaces all of the second tabstop with capture group 2 (capitalized) which is nothing since you didn't have a capture group 2.

Ah, my bad. Wonderful remark. 

Thanks.
