### ISSUE TITLE
Exclude symlinks from files explorer

### ISSUE THREAD

**Issue by GoToCoding** [microsoft/vscode#102783]
I don't want to see symlinks in files explorer, how can I disable showing them?

There was a closed issue-duplicate of current: https://github.com/microsoft/vscode/issues/74335
But it's closed :(

**Comment by zsilet** [comment]
I would love to see the same support. Working in a massive codebase that builds the same pieces of code under different directory structures for different products, I often find search results showing up multiple times due to the hundreds of symlinked files.

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog and we might add this in the future. Thanks

**Comment by patbl** [comment]
If you're looking for a way of excluding symlinks from search results, there's a way of doing that:

![image](https://user-images.githubusercontent.com/1735266/99753546-3a385580-2a9b-11eb-82e7-90c19ba6dcbb.png)

I realize this isn't what the author of the issue was asking for, but it was what I was looking for when I came across this issue.

**Comment by ssichynskyi** [comment]
@patbl , could you explain a bit where this could be found?

**Comment by patbl** [comment]
Open the [command palette](https://code.visualstudio.com/docs/getstarted/userinterface#_command-palette), then type "follow symlinks."
