### ISSUE TITLE
Use GitHub for marketplace issue tracking

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#102722]
It would be great if issue tracking for marketplace issues was in public GitHub repository instead of sending an email.

**Comment by joaomoreno** [comment]
We do use GitHub, but it's a private repository since the Marketplace is not open-source and serves more products other than VS Code. I will create an issue on that repository asking the team to consider having a public facade for their issues. But for now this will be closed since it's not a VS Code issue per se.

cc @prashantvc
