### ISSUE TITLE
Debugging is not working properly

### ISSUE THREAD

**Issue by kapillx** [microsoft/vscode#102744]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. try to debug node js express apps, its not working properly
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by jothamschwartz** [comment]
i am also experiencing a problem remote-debugging nodejs in 1.47.2. 
ms code is running on win10, node is on linux. 

the behavior has changed since 1.47.1 (where is was more broken). 1.47.2 appears to match the current insiders edition behavior. 

if a file is open for editing, with a breakpoint set, and if that breakpoint is hit while debugging, ms code opens a second copy of the file in read-only mode and hits the breakpoint in that file second file (which cannot be edited). 

the difference between the 'real' file that was open for editing and the file that ms code opens in read-only mode during debugging is that the read-only file contains

(function (exports, require, module, __filename, __dirname) {

added to the beginning of the file, and 

});

added to the end of the file. 

regarding comments on previous node debugging problem: i am using --inspect, not --inspect-brk

i reverted to 1.46 to get debugging working correctly for the time-being.

thank you...

**Comment by manojc** [comment]
For now I reverted the version to 1.46.1 and it works fine for me.

Debian users can rollback to previous version using following command - 

`wget https://vscode-update.azurewebsites.net/1.46.1/linux-deb-x64/stable -O /tmp/code_latest_amd64.deb && sudo dpkg -i /tmp/code_latest_amd64.deb`

Please let me know if I have missed anything.

**Comment by connor4312** [comment]
Please collect a trace log using the following instructions:

> If you're able to, add `"trace": true` to your `launch.json` and reproduce the issue. The location of the log file on your disk will be written to the Debug Console. Share that with us.
>
>⚠️ This log file will not contain source code, but will contain file paths. You can drop it into https://microsoft.github.io/vscode-pwa-analyzer/index.html to see what it contains. If you'd rather not share the log publicly, you can email it to connor@xbox.com

You can also temporarily disable the new debugger on 1.47.* by setting `debug.javascript.usePreview: false`.

**Comment by nodorious** [comment]
[vscode-debugadapter-0.json.gz](https://github.com/microsoft/vscode/files/4938703/vscode-debugadapter-0.json.gz)

as requested

**Comment by nodorious** [comment]
thank you for the response. 

i am using the ms code sftp extension (liximomo.sftp) to open the files from their location on the server and 'edit in local' - so the edited file should be identical to the server file and have behaved as such with previous versions of the debugger. 

if you know of a setting that would cause downloaded files to be somehow modified please let me know. 

>>js-debug does this behavior if it sees that the contents of your file on-disk doesn't match those in the runtime

as i previously reported, the runtime (read-only) file that ms code opens has

(function (exports, require, module, __filename, __dirname) {

prepended to my file contents and 

});

appended to the end of my file contents, so it looks to me like ms code is wrapping my file in something as part of its debugging activities. this added script is not part of the file on disk. this is the only difference i can see between the file i open via sftp (which does not contain the added script) and the runtime file that ms code opens during debugging (that does contain the added code). line endings are consistent. 

thank you...

**Comment by connor4312** [comment]
> appended to the end of my file contents, so it looks to me like ms code is wrapping my file in something as part of its debugging activities. this added script is not part of the file on disk

This is actually a wrapper that Node adds.

If you're able to, it'd be great if you could save one of those "wrapped" files that VS Code opens (should be able to "Save As" once it opens) and the corresponding correct file, and send that to me so I can see what might be going on.

Either here or via email to connor@xbox.com is good

**Comment by kapillx** [comment]
Hi Connor, 

Any reason why I am seeing this button in package.json

![image](https://user-images.githubusercontent.com/61395334/87888263-2807c580-ca6f-11ea-9025-7a852ad29e20.png)

is this a feature, seems out of place

**Comment by connor4312** [comment]
It is, you can configure/toggle it via the `debug.javascript.codelens.npmScripts` setting
