### ISSUE TITLE
No loading indicator when formatting a document

### ISSUE THREAD

**Issue by ZackTherrien** [microsoft/vscode#102718]
- VSCode Version: 1.47.1
- OS Version: Darwin x64 19.5.0

Steps to Reproduce:

1. Create a file with a large amount (2000+ lines) of unformatted JSON data (or any other format) 
2. Right click -> Format Document
3. No indicators are visisble.

Does this issue occur when all extensions are disabled?: Yes

**Comment by ConradSollitt** [comment]
This would be a nice to have feature as I occasionally work with very large JSON files and use the `Format Document` menu and have found myself wishing for this feature in the past.

I started playing around with the VS Code Source for this issue but realize I need to spend more time learning and testing the API than I have today (or likely within the next week) in order to make an update like this.

In case another developer is interested in helping with this here are some links on where to edit the code:

Code for the `Format Document` menu
https://github.com/microsoft/vscode/blob/master/src/vs/editor/contrib/format/formatActions.ts#L209

Function `formatDocumentWithSelectedProvider` that gets called by menu and other VS Code actions
https://github.com/microsoft/vscode/blob/master/src/vs/editor/contrib/format/format.ts#L210

I started doing some testing in a fork using the `INotificationService` however my changes ended up causing the feature not to work. Also there are many different progress or notification API's such as `IEditorProgressService` or `class Progress<T>` that may be more appropriate for this feature however I still need to spend more time to get them working.
https://github.com/ConradSollitt/vscode/commit/729258e276026feb4189acb2916e48d0a564800a

If there is no update on this in a while and I have time I'll work on it (or if someone can provide API direction to get me quickly started I can do more work next week).

I've created a few large JSON files using a Geonames database https://www.geonames.org/ that anyone can download an use for testing. I'll keep these links up for a while and at least until this feature can be completed.

http://dataformsjs.s3-website-us-west-1.amazonaws.com/tmp/geonames-regions.json
`850 kB` - List of the all Territories/Regions (States, Provinces, etc) for all Countries in the World

http://dataformsjs.s3-website-us-west-1.amazonaws.com/tmp/geonames-cities-10k.json
`2.9 MB` - List of the 10,000 largest cities in the World

http://dataformsjs.s3-website-us-west-1.amazonaws.com/tmp/geonames-cities-50k.json
`14.4 MB` - List of the 50,000 largest cities in the World

**Comment by heanzyzabala** [comment]
Hi, Is there anyone else working with this @ConradSollitt? I would like to try and work on this one.

**Comment by ConradSollitt** [comment]
@heanzyzabala I haven't done anything on this since I last posted so feel free as it's useful and seems like a great learning experience. If I were to make a serious effort I'll post an update but right now I don't expect to have enough free time to spend on this. The above JSON downloads I created are good manual test cases for this feature.

**Comment by jrieken** [comment]
To verify:

* open a TypeScript file
* add a breakpoint in [`vs/workbench/api/common/extHostLanguageFeatures.ts#provideDocumentRangeFormattingEdits`](https://github.com/microsoft/vscode/blob/f922e8b7574608d7220d9c39d7f99edfc63c7b68/src/vs/workbench/api/common/extHostLanguageFeatures.ts#L495)
* Run Format Document or Format Selection make sure the UI shows in-editor progress
