### ISSUE TITLE
Node debugging take more time for api call,sometimes request seems to be pending request 

### ISSUE THREAD

**Issue by nikhilpk26** [microsoft/vscode#102764]
- VSCode Version:1.47.2
- OS Version:Windows 10
- Node Version 12.18.2

Steps to Reproduce:

1.Started debugging  with node expressjs
2.API called from reactjs Based UI 

Does this issue occur when all extensions are disabled?: NO

**Comment by connor4312** [comment]
Debugging does cause Node code to run slowly. You can set `"showAsyncStacks": false,` in your launch.json to disable the most expensive of the debugging tools (at the expense of losing async stacks). But for running applications i.e. outside of intense things like webpack builds. I haven't often seen noticable slowdowns. I would consider using the debugger to take a profile (via the "take performance profile" command) of your application to help see what's happening.

Let us know how this turns out.

/needsMoreInfo
