### ISSUE TITLE
Auto complete html tag

### ISSUE THREAD

**Issue by ProtocolLive** [microsoft/vscode#102862]
Issue Type: <b>Bug</b>

When i create a new html tag on a existing document, they are united with the next word, and with enter, the word disapear.

Recriate:
![1](https://user-images.githubusercontent.com/39626142/87851344-408caa00-c8ce-11ea-8a68-84b729de5a78.jpg)
![2](https://user-images.githubusercontent.com/39626142/87851350-50a48980-c8ce-11ea-9c20-03294f8a0cac.jpg)
![3](https://user-images.githubusercontent.com/39626142/87851353-5306e380-c8ce-11ea-98be-bbc9c48b128b.jpg)

A suggestion to, after this bug is fixed, is the closing tag to be placed after the word.

Simulation:
![1](https://user-images.githubusercontent.com/39626142/87851421-f3f59e80-c8ce-11ea-9864-163c00bc062a.jpg)
![2](https://user-images.githubusercontent.com/39626142/87851441-24d5d380-c8cf-11ea-9d43-3abb5cdfdd5f.jpg)
Today:
![3](https://user-images.githubusercontent.com/39626142/87851453-4df66400-c8cf-11ea-8785-86c5285af243.jpg)
Suggested:
![4](https://user-images.githubusercontent.com/39626142/87851462-623a6100-c8cf-11ea-89fe-bb7841eedc61.jpg)

VS Code version: Code - Insiders 1.48.0-insider (ff6b1c5984a4c2116a06318f07e871a4169fdb1b, 2020-07-17T13:18:36.126Z)
OS version: Windows_NT x64 10.0.20170

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|3.91GB (0.54GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|11.3.1
bracket-pair-colorizer-2|Coe|0.2.0
xml|Dot|2.5.1
toggle-upper-case|epr|0.0.1
html-preview-vscode|tht|0.2.5
vscode-input-sequence|tom|0.2.0
html-css-class-completion|Zig|1.19.0

(1 theme extensions excluded)

</details>

**Comment by aeschli** [comment]
For code complete, you can switch between inserting and replacing using the `shift` key when pressing enter to accept the proposal.

When selecting a proposal, we don't automatically close it, as you might want enter attributes as well. Closing happens when entering `>`. Knowing that the closing tag should be after `ipsum` is difficult to guess. It could be as well after `ipsum dolor`.

I think better way to do what you want is with the command `Emmet: Wrap with Abbreviation`:
- select a code block
- run the  `Emmet: Wrap with Abbreviation` command
- enter the tag

No changes planed for now
