### ISSUE TITLE
Pipetables not working in markdown unless declared on new line

### ISSUE THREAD

**Issue by VasuBhog** [microsoft/vscode#102820]
- VSCode Version: 1.47.2
- OS Version: macOS 10.15.5

Steps to Reproduce:

1. In a markdown file that has pipe tables there 'MUST' be a new line prior to the pipe table for the table to show correctly.

**Content**:

Broken:
PG Server life cycle. | req_elastic_server_name | request_id | is_success | latest_state | operation_type | res_upsert_operation_type | min_TIMESTAMP | max_TIMESTAMP | latency | prev_app_name | curr_app_name | control_ring | move_primary_done | move_primary_call_ts | error_message | req_subscription_id | req_resource_group | req_elastic_server_type | req_service_level_objective | req_elastic_server_edition | req_hardware_generation | req_v_core | req_storage_mb | req_version | req_backup_retention_days | req_enforce_ssl | req_enable_storage_auto_grow | req_enable_geo_redundant_backup | req_log_exception_if_not_found | req_src_subscription_id | req_src_resource_group | req_src_elastic_server_type | req_src_elastic_server_name | req_point_in_time | req_replication_role | res_subscription_id | res_resource_group | res_elastic_server_id | res_azure_dns_record_name | res_elastic_server_edition | res_hardware_generation | res_v_core | res_storage_mb | res_version | res_backup_retention_days | res_enforce_ssl | res_enable_storage_auto_grow | res_enable_geo_redundant_backup | res_is_pre_existing_entity | res_user_visible_state | is_recreate_update | |-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-| |

![image](https://user-images.githubusercontent.com/23587151/87826435-7aae6b00-c83e-11ea-8a63-59388b4e1259.png)

Working:

PG Server life cycle.

| req_elastic_server_name | request_id | is_success | latest_state | operation_type | res_upsert_operation_type | min_TIMESTAMP | max_TIMESTAMP | latency | prev_app_name | curr_app_name | control_ring | move_primary_done | move_primary_call_ts | error_message | req_subscription_id | req_resource_group | req_elastic_server_type | req_service_level_objective | req_elastic_server_edition | req_hardware_generation | req_v_core | req_storage_mb | req_version | req_backup_retention_days | req_enforce_ssl | req_enable_storage_auto_grow | req_enable_geo_redundant_backup | req_log_exception_if_not_found | req_src_subscription_id | req_src_resource_group | req_src_elastic_server_type | req_src_elastic_server_name | req_point_in_time | req_replication_role | res_subscription_id | res_resource_group | res_elastic_server_id | res_azure_dns_record_name | res_elastic_server_edition | res_hardware_generation | res_v_core | res_storage_mb | res_version | res_backup_retention_days | res_enforce_ssl | res_enable_storage_auto_grow | res_enable_geo_redundant_backup | res_is_pre_existing_entity | res_user_visible_state | is_recreate_update | |-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-| |

![image](https://user-images.githubusercontent.com/23587151/87826466-8c900e00-c83e-11ea-8daf-e1f911a26f54.png)

**Comment by IllusionMH** [comment]
In MD block elements are supposed to start at the new line (unless wrapped in container block elements), otherwise that characters are just part of the string.

This behavior is consistent with GitHub (tables are part of GitHub Flavored Markdown)

---

Screenshot text
![image](https://user-images.githubusercontent.com/1312662/87830675-3c3e9d80-c88a-11ea-897f-3e34fa2f07aa.png)

---

Screenshot preview 
![image](https://user-images.githubusercontent.com/1312662/87830728-5b3d2f80-c88a-11ea-9120-215b60793e7f.png)

---

Actual example:

table with pipes |a|b|
|-|-|
|c|d|

code block with three backticks ```
code
```

**Comment by rajeshka** [comment]
Dev ops wiki support [this](https://docs.microsoft.com/en-us/azure/devops/project/wiki/markdown-guidance?view=azure-devops)
<img width="973" alt="image" src="https://user-images.githubusercontent.com/29285871/87834492-6d45b080-c83f-11ea-8bb8-ea7ed40c5910.png">

**Comment by IllusionMH** [comment]
@rajeshka with single `\n` before `|` it works same in both DevOps wiki and VS Code
![image](https://user-images.githubusercontent.com/1312662/87835025-ac522100-c894-11ea-8e1c-758b1aa12b70.png)

Initial report doesn't have one (which makes it similar to No line break case), but I since it is reported as issue it implies that it should work
![image](https://user-images.githubusercontent.com/1312662/87835185-110d7b80-c895-11ea-9c5f-8c4a7c2c9e84.png)

**Comment by VasuBhog** [comment]
@IllusionMH I was working on this issue that was mentioned below my issue, it seems that we are addressing a separate issue. No line break case is not the issue we are looking to fix.
