### ISSUE TITLE
Environment service debt between common, browser, native

### ISSUE THREAD

**Issue by inspirer** [microsoft/vscode#102918]
There are `common` and `browser` versions of the environment service but both of them depend on [workbench.web.api.ts](https://github.com/microsoft/vscode/blob/master/src/vs/workbench/workbench.web.api.ts) for IWorkbenchConstructionOptions. This is a type only dependency so it should not create any problems at runtime but it is misleading since `common` code gets access to browser-only interfaces such as IUpdateProvider.

The culprit seems to be the unclear status of workbench.web.api inside `.eslintrc.json`.

See https://github.com/microsoft/vscode/wiki/Source-Code-Organization#target-environments

**Comment by bpasero** [comment]
Yeah, lot's of debt buried inside environment service, but I would hold on changing this until we figured out the sandbox model (https://github.com/microsoft/vscode/issues/92164). I expect that the environment service will change a lot after this and I feel there is a chance to cleanup everything when we have an idea what this thing ends up to be.

If we find out that the web API options are only used in the web version, then maybe they should be removed from the common environment service and only be accessible from the browser workbench environment service. I am not keen on moving the options into core though out of `workbench.web.api.ts` because I like to track these interfaces inside one file ideally. But again, haven't spend a lot of though on it yet.

**Comment by inspirer** [comment]
Sounds good, it is great to hear that this is being taken care of. Let's park (or drop) this PR for now.

The problem with keeping the options inside `workbench.web.api.ts` is that it makes that file a node in the imports graph that connects everything with everything (many services depend on it via the env service, and it depends on everything via `workbench.web.main`). The incremental compilation speed does not seem to suffer much as of now, so it is more of a potential threat of people keep adding more code and converting the env->web.api dependency into a proper dependency, turning half of workbench into a interconnected build component.

**Comment by bpasero** [comment]
From https://github.com/microsoft/vscode/issues/76719: we carry around multiple properties for backups (`backupPath`, `backupHome`, `backupWorkspacesPath`, `backupWorkspaceHome`) that should be consolidated.

**Comment by bpasero** [comment]
As one step to untangle the environment service monster, I introduced a [`IMainEnvironmentService`](https://github.com/microsoft/vscode/blob/0a7c0fd68efa026c34b30dcdb64c6adf6c93b6c2/src/vs/platform/environment/electron-main/environmentMainService.ts#L18-L34) to have only those properties that are used only in `electron-main`. I was able to move the backup related main properties over, as well as some others only used there.

//fyi @sandy081
