### ISSUE TITLE
Releasing Ctrl when Ctrl-N in Quick Open no longer works

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#10298]
> @ithinkihaveacat says

I think #7316 caused a regression from 1.3.

In 1.3, with `ctrl+n` bound to workbench.action.quickOpenNavigateNext, then in Quick Open, holding down `ctrl` and then tapping `n` moved the selection down a line (as it does now). However, after releasing `ctrl`, the selected file was automatically opened, eliminating the need to press the return key.

It took a few goes to get used to this behavior, but eventually I found it preferable. It doesn't work anymore in 1.4. If this change was intentional, is there a way to get the old behavior back?

**Comment by bpasero** [comment]
@joaomoreno the issue is in https://github.com/Microsoft/vscode/blob/master/src/vs/base/parts/quickopen/browser/quickOpenWidget.ts#L159 you are changing the actual key that was pressed and this will result in the event getting canceled in https://github.com/Microsoft/vscode/blob/master/src/vs/base/parts/quickopen/browser/quickOpenWidget.ts#L174 and thus it will never reach the keybinding service.

I am not sure how to get this working again, I find the current code in quick open widget weird because the tree is not even focussed and we still support Ctrl+N and Ctrl+P. I would rather maybe introduce real commands that are active when quick open is visible (we already have this key) and do the navigation in quick open (we could add methods for that).

Moving back to you.

**Comment by joaomoreno** [comment]
I ended up reverting the changes from #7316 related to quick open.
