### ISSUE TITLE
Debug window concatenates file names (filename.component...)

### ISSUE THREAD

**Issue by blixenkrone** [microsoft/vscode#102933]
- VSCode Version: 1.47
- OS Version: MacOS

Steps to Reproduce:

1. Run a local project server (f.ex angular) with a long filename (some 16+ characters) <filename>.<extension>.
2. Run a debug session (f.ex firefox), and check the debug console output.

Does this issue occur when all extensions are disabled?: Yes
![Skærmbillede 2020-07-20 kl  11 02 57](https://user-images.githubusercontent.com/7870735/87920719-e03a6b80-ca79-11ea-816f-b021f7347d0b.png)

**Comment by weinand** [comment]
I don't understand what the screenshot is showing. Please show the whole thing...
I do not understand what gets concatenated in the screenshot.
What exactly are you expecting and what is the erroneous behavior?

**Comment by blixenkrone** [comment]
@weinand attached photo of whole debug console - error occurs on last line. 
Behavior: supposedly filenames (some 16+ characters) will be shortened with (...) instead of showing the whole filename and line number.
Expecting: the whole filename and line number where a console log is being outputted.
![Skærmbillede 2020-07-21 kl  11 40 14](https://user-images.githubusercontent.com/7870735/88039060-62dd2c80-cb47-11ea-8084-a344370cc63c.png)

**Comment by isidorn** [comment]
Yes, I agree this is an issue.
The problem is that we set a `max-width` to 150 [here](https://github.com/microsoft/vscode/blob/2f63aa9e559089436aa237f9c256ebad56913e42/src/vs/workbench/contrib/debug/browser/media/repl.css#L54). The ideal solution would be that the `source` elements gets shrinked first, and that it has unlimited size.

Adding help wanted as I am open to review a PR which fixes this. If nobody tackles this I can also look into this in the future.

**Comment by pfongkye** [comment]
Hi @isidorn, I can give this a try.

**Comment by isidorn** [comment]
@pfongkye great, thanks!
