### ISSUE TITLE
Integration tests fail but mocha never returns

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#103008]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=82590&view=logs&j=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&t=f58c00c4-bf13-5e9c-4e42-b9695c0a283b

**Comment by bpasero** [comment]
This does not seem to reproduce with our other integration tests (e.g. tried with `commands.test.ts`). Not sure what would be different for notebooks.

The code for running integration tests in the browser is: https://github.com/microsoft/vscode/blob/288108c294994b15ad65bfb4aefbe72858bb610f/test/integration/browser/src/index.ts#L57

**Comment by joaomoreno** [comment]
Sorry, @rebornix, I think `bug` categorizes failing tests better than `debt`.

**Comment by rebornix** [comment]
The timeout is due to the first failure of the notebook integration test: `notebook workflow document runnable metadata is respected`. 

Verifier, please test:

* Create a GitHub issue notebook
* Create a code cell
* Type in `$`, the execution button should be visible
* Continue typing `$a=123`, the execution button should be gone
