### ISSUE TITLE
Breakpoints don't persist if they are added during a debug session

### ISSUE THREAD

**Issue by gregg-miskelly** [microsoft/vscode#103111]
- VSCode Version: 1.47.2
Also checked: 1.48.0-insider, Commit: 0a7364f00514c46c9caceece15e1f82f82e3712f, Date: 2020-07-22T05:49:27.463Z

- OS: Windows_NT x64 10.0.18363

### Steps to Reproduce:
1. Create a new C# hello world project -- Run `dotnet new console` and update the code in Program.cs to match below
2. Set a breakpoint on the first Console.WriteLine call and start debugging
3. After the breakpoint hits, set another breakpoint on the second Console.WriteLine call
4. Stop debugging and exit VS Code
5. Restart VS Code

### Expected:
Breakpoints should be persisted. This works if step 3 is omitted

### Actual:
Breakpoints are not persisted.

### Protocol trace
Here is a protocol trace of `setBreakpoints` (step 3)

```
-> (C) {"command":"setBreakpoints","arguments":{"source":{"name":"Program.cs","path":"c:\\proj\\clinew\\Program.cs","sourceReference":0,"sources":[],"checksums":[{"algorithm":"SHA1","checksum":"d298fe5338b73bd66cfa364395e0785cf59d8200"},{"algorithm":"SHA256","checksum":"74e7c2e32557a439e49cae521341e77120131f6d385cfa3490c5851c9f9c4acf"},{"algorithm":"SHA1","checksum":"73a24b05cb68acc86484d71f1b404724201836b4"},{"algorithm":"SHA256","checksum":"b6ebd405573495a38955f30913fb59899244860e3e308e02508633ae5b73e716"}]},"lines":[9,10],"breakpoints":[{"line":9},{"line":10}],"sourceModified":false},"type":"request","seq":13}
<- (R) {"seq":31,"type":"response","request_seq":13,"success":true,"command":"setBreakpoints","message":"","body":{"breakpoints":[{"id":1,"verified":true,"source":{"name":"Program.cs","path":"C:\\proj\\clinew\\Program.cs","sourceReference":0,"sources":[],"checksums":[{"algorithm":"SHA256","checksum":"74e7c2e32557a439e49cae521341e77120131f6d385cfa3490c5851c9f9c4acf"}]},"line":9,"endLine":9},{"id":4,"verified":true,"source":{"name":"Program.cs","path":"C:\\proj\\clinew\\Program.cs","sourceReference":0,"sources":[],"checksums":[{"algorithm":"SHA256","checksum":"74e7c2e32557a439e49cae521341e77120131f6d385cfa3490c5851c9f9c4acf"}]},"line":10,"endLine":10}]}}
```

### Program.cs
```
using System;

namespace clinew
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("One");
            Console.WriteLine("Two");
            Console.WriteLine("Three");
            Console.WriteLine("Hello World!");
        }
    }
}
```

**Comment by weinand** [comment]
I can reproduce the same issue with a trivial JS program.

**Comment by connor4312** [comment]
I'm able to reproduce the exact same thing. However since the issue was reported on C#, I don't think it related to js-debug specifically but more likely some call pattern or timing that js-debug and C# share. Regardless I will look into it this afternoon.

**Comment by connor4312** [comment]
This was because we were using the "from source" uri in `toJSON` when the breakpoint was verified, after https://github.com/microsoft/vscode/issues/89756#issuecomment-583447850

Allowing the source to be changed at runtime is good, but we should probably not persist the changed source (we should persist wherever the user placed the breakpoint originally), so I think this change is a valid fix.

This didn't happen in the old adapters since those always verify breakpoints asynchronously, so we were able to store the breakpoint before its uri was changed by verification.

**Comment by weinand** [comment]
@connor4312 thanks for fixing this.

@isidorn we should never persist any data that comes back from DAs as part of the breakpoint verification. Only the frontend UI has the "truth" (because that's what the user has entered).

However, uninterpreted *payload data" from the DA must be persisted

**Comment by connor4312** [comment]
I think this was probably accidental -- `toJson` used the `uri` getter, which was fine before but changed as part of the linked issue to return the location from the DA. Reflecting the updated location throughout the UI is good, we just missed the special case of persistence.

**Comment by weinand** [comment]
I still wonder why this bug becomes visible only with the new js-debug? 
The initial report is about breakpoints in C# code. Why is js-debug verifying/modifying C# breakpoints?

**Comment by isidorn** [comment]
Thanks @connor4312 for jumping in and for pushing a fix.
The fix is good, and we were behaving like this for a couple of milestones. We were incorectly storing the `uri` coming from the adapter, instead of storing the original `uri` which the user set.

Why did this only now start to appear with js-debug and with C#, well I would argue it was appearing for a couple of milestones but we just did not notice it for C#. The old node debugger was probably using the same uri sa the vscode frontend so there was no problems.

We only persist the uninterpeted payload data from the DA which is the `adapterData` [here](https://github.com/microsoft/vscode/blob/6f21ef0a18416916f86ef67d7218a95c79b68764/src/vs/workbench/contrib/debug/common/debugModel.ts#L695)

@gregg-miskelly can you please verify all is good for you with the latest vscode insiders? Thanks!

**Comment by cateyes99** [comment]
@isidorn i originally raised this bug with the OmniSharp C# extension. I just checked it with `VSCode 1.45.1`, and found that it does have this bug already.

**Comment by isidorn** [comment]
@cateyes99 that makes sense, if you can try to repro with latest vscode insiders that would be great as well
https://code.visualstudio.com/insiders/

**Comment by cateyes99** [comment]
@isidorn Checked with VSCode Insider `1.48.0`, it looked fine to me now. Thanks all.
