### ISSUE TITLE
Cut and paste doesn't work between cells in python notebook files

### ISSUE THREAD

**Issue by financialphysician** [microsoft/vscode#103270]
Open two cells in a ",pynb" file. Type a line in one cell. Try to cut (ctrl+x) and paste (ctrl+v) it into the other cell and it'll print an empty line instead of the cut text. (At least that's what it does for me.) 

However, copy and paste does work between cells.

**Comment by daniel-jozsef** [comment]
I have an idea as to this bug. I have encountered something similar, and kinda managed to understand how it "happens". Thankfully it's apparently fixed in the 1.48.0 insiders version.

So in my experience at least, cut-and-paste didn't (doesn't) work at all in Jupyter notebooks, not just between cells. What happens is the following: by pressing ctrl-x, the ctrl-x action is triggered _twice_: First, the selected text is cut. Then second, there is no selection, so the empty row is cut. This overwrites the selected text in the buffer with a single newline. When trying to paste, it's this newline that gets pasted.

**Comment by rebornix** [comment]
Please upgrade to the latest version of VS Code and the issue should be gone.
