### ISSUE TITLE
Add instructions on how to use Devcontainer with this project to the How to Contribute Wiki

### ISSUE THREAD

**Issue by opethe1st** [microsoft/vscode#103293]
I just pulled this github repo and just as I was about to start struggling with dependencies I noticed there is a Devcontainter config for this. I think it would be super useful to add instructions on how to use it so people don't have to struggle with installing things locally.

**Comment by bamurtaugh** [comment]
Thank you for the feedback! We currently have a [section of the README](https://github.com/microsoft/vscode#development-container) that describes how to use a development container, and it links to a more detailed [development container README](https://github.com/microsoft/vscode/blob/master/.devcontainer/README.md). Were you able to find these instructions? Do you find them helpful?

**Comment by opethe1st** [comment]
I found that useful 👍 . I think it would be useful to link it in the wiki (https://github.com/microsoft/vscode/wiki) under the contributing section (https://github.com/microsoft/vscode/wiki/How-to-Contribute) which was were I was checking and I didn't find it.

**Comment by bamurtaugh** [comment]
Thank you for for sharing your insights @opethe1st! I just merged a PR to add it to the contributing section of the wiki (https://github.com/microsoft/vscode-wiki/pull/152), and it should show up in the next day. Closing this issue since I believe it addresses your concern and provides the requested solution, but please feel free to let us know if you have any other questions or feedback!
