### ISSUE TITLE
Making it easier to build VSCode for an offline system

### ISSUE THREAD

**Issue by max-sixty** [microsoft/vscode#103264]
Firstly, thanks again for providing such an awesome editor, it's one of my favorite products of all products!

I'm in an environment where some of our system is airgapped and so doesn't have access to the internet. In order to use applications in that environment, I write a script to build applications on an online system, and then ship the package to the offline system.

Currently VSCode seems the hardest to do this with a script, verging on impossible. Something like spacemacs is much easier. Here are some of the issues:
- Some extensions seem to require opening VSCode to download things. An example of this is the C/C++ extension. Is there a way to "open" vscode in a script and let it download things? I do that when packaging up Spacemacs, for example (`emacs --daemon`). Without this, I'm not sure it's possible to prepare VSCode for Linux on a MacOS. Even with an online Linux system, this would require manual steps in the script.
- I can't find a link to download VSCode. If I go to the page https://code.visualstudio.com/docs/?dv=linux64, and then click on [Direct download link](https://go.microsoft.com/fwlink/?LinkID=620884), I get a link that I don't think `curl` nor `wget` can use. So this prevents a script from grabbing the latest version.
- I have a workaround for this, but it's non-trivial to install a list of extensions with a config file. Spacemacs has `.spacemacs` where extensions are specified. Instead, I think I need to run a script to generate a list of my local extensions:
  ```sh
  code --list-extensions \
  | xargs -L 1 echo code --user-data-dir=data/ --install-extension --force
  ```
  and then run the output in the script preparing vscode:
  ```sh
  code --user-data-dir=data/ --install-extension --force alefragnani.Bookmarks
  code --user-data-dir=data/ --install-extension --force annsk.alignment
  code --user-data-dir=data/ --install-extension --force bastienboutonnet.vscode-dbt
  ...
  ```

If there are better approaches to these, that would be most welcome. Thank you again!

**Comment by NotWearingPants** [comment]
- The C++ extension provides offline versions of their extension in their [GitHub releases](https://github.com/microsoft/vscode-cpptools/releases).
  The reason they download a separate file is because the extension is platform-dependent and they want to avoid shipping all of the possible options and only use one, to save space.

- You can find direct links to all of the VSCode builds in this JSON endpoint: https://code.visualstudio.com/sha?build=stable

- You can instead download the vsix files from the marketplace (the "download extension" link in the right of the extension webpage) and then install them in the air-gapped system with `code --install-extension path/to/vsix`.

Another good all-around option is to use https://github.com/LOLINTERNETZ/vscodeoffline, which is a VSCode extension registry and update server designed for air-gapped systems 🤙

**Comment by max-sixty** [comment]
Thanks @NotWearingPants !

For any others, here's an example of downloading a specific version from that JSON endpoint:
```sh
wget -O - $(curl -L 'https://code.visualstudio.com/sha?build=stable' \
    | jq -r '.products[] | select(.platform.os==("linux-x64")) | .url') \
    | tar xz
```

**Comment by alexr00** [comment]
Thanks for the thorough response @NotWearingPants

**Comment by max-sixty** [comment]
Yup. Fine to close this, and appreciate @NotWearingPants ' help, but to ensure the remaining points aren't lost: it's still significantly harder to build a working offline version of VSCode than of other editors. In particular, there's no way to allow extensions to run any online configuration they require as part of a script (like `emacs --daemon`), such as the C++ extension, so specific downloading of specific extension versions is required.

Thank you again for such an excellent product overall though!
