### ISSUE TITLE
Can't install extensions

### ISSUE THREAD

**Issue by chssingh** [microsoft/vscode#103367]
there's no way working to install any extension on my system. please check this out immediately
whenever I download it mannualy and try to install with VSIX no process starts.
![1](https://user-images.githubusercontent.com/50863442/88482811-4a26a980-cf81-11ea-944c-643b488c7753.jpg)

**Comment by chssingh** [comment]
![1](https://user-images.githubusercontent.com/50863442/88512963-02496600-d005-11ea-8448-058b2f605961.jpg)
with other extensions also same thing is happening. Please sort this asap as you also know we got so much work to do.

**Comment by sandy081** [comment]
Please follow these steps

- Help -> Toggle Developer Tools -> Network
- Then check for any network failed requests while browsing and installing the extensions if found all requests fails then its probably a proxy or DNS issue at your end.
- To confirm its a DNS issue check if you can access this page https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default, if you cannot please try configuring your DNS like pointing to 1.1.1.1 as suggested here? https://1.1.1.1/dns/. Otherwise please contact your network administrator.
- If it is not a network issue, please share the logs from the following locations
    - Help -> Toggle Developer Tools -> Console
    - View -> Command Pallette... -> Toggle Shared Process -> Console
    - View -> Open View… -> Log (Shared)
    - View -> Open View… -> Log (Window)

**Comment by chssingh** [comment]
[image: image.png]

**Comment by chssingh** [comment]
now what should I do?

**Comment by sandy081** [comment]
I do not see any information or pictures. 

Can you please check and provide the Information ?

**Comment by chssingh** [comment]
However I uninstalled it and deleted every program from my system and
reinstalled it .New version 1.47.3 worked.
Thanks
