### ISSUE TITLE
VSCODE Failed to install VSCODE update.

### ISSUE THREAD

**Issue by HQuang** [microsoft/vscode#103453]
- VSCode Version: 1.47.2
- OS Version: windows 10 - 64bit

Steps to Reproduce:

1. I click **Restart to Update** in vscode.
2. The system reported the following error .

![image](https://user-images.githubusercontent.com/17137922/88615646-93c7df00-d0bc-11ea-8fa7-670bfe340561.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by dsone** [comment]
This issue happened with an earlier version of VS Code, back then it was the RemoteSSH extension - if my memory serves me right -  that prevented the update. Since 1.4.0 I had this issue with every minor version but until now (1.4.2) I was able to "fix" this by a simple restart of my Windows PC. 

The created Log file has only kill attempts listed, 60 in total where VSCode gives up, 11 of those look like this:
```
Jul 29 09:24:40.063 INFO Checking for possible conflicting running processes... (attempt 11)
Jul 29 09:24:40.071 INFO Kill process if found: 9436, Code.exe
Jul 29 09:24:40.071 INFO Found Code.exe running, pid 9436, attempting to kill...
Jul 29 09:24:40.071 INFO Kill process if found: 7788, Code.exe
Jul 29 09:24:40.071 INFO Found Code.exe running, pid 7788, attempting to kill...
Jul 29 09:24:40.071 WARN Kill error Failed to kill process
Jul 29 09:24:40.072 WARN Kill error Failed to kill process
Jul 29 09:25:04.406 ERRO Failed to kill process
```
I only had one VSCode instance running, though. 

In this particular version (1.4.3) a restart alone doesn't help. To be able to update to 1.4.3 I have to restart and start VSCode with 
`code --disable-extensions` from CLI. As soon as I start VSCode normally once with extensions enabled, restarting VSCode with all extensions disabled doesn't help to make the update go through.

I suspect some extension is the culprit here, but it's hard to determine which one.
I do use some Intellisense, Kite and similar extensions, running their own processes, but I am not sure how they are connected to VSCode and how they might interfere here.

Extended system info:
Version: 1.47.3 (user setup)
Commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e
Datum: 2020-07-23T13:12:49.994Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
Betriebssystem: Windows_NT x64 10.0.18363

Since this issue with updates is a recurring one, is there anything that can be done to debug how extensions might be the culprit? Other than disable one after the other and try to update.

**Comment by HQuang** [comment]
I had updated the new version by going to the directory anh update file new version vscode 1.47.3

**Comment by joaomoreno** [comment]
/duplicate #47841

As a workaround, please disable Windows background updates by setting `update.enableWindowsBackgroundUpdates` to `false`.
