### ISSUE TITLE
Make find widget toggles configurable settings

### ISSUE THREAD

**Issue by aybabtme** [Microsoft/vscode#10344]
Related to https://github.com/Microsoft/vscode/issues/4309#issuecomment-225023802

Add to `settings.json` a way to always enable the case-sensitivity feature of Find.

**Comment by jrieken** [comment]
Setting? I believe that's stuff we should store and retrieve using the memento stuff...

**Comment by alexandrudima** [comment]
It would be the default value

**Comment by aybabtme** [comment]
@jrieken not sure what the memento stuff is. As a user, my expectations is that I'd be able to change that in my user settings (the JSON file) and then never have to think about it again.

**Comment by ramya-rao-a** [comment]
Find across files already persists the Find options (case sensitivity, whole word and regex). Find in a single file doesn't. Using configuration setting for default value for Find in File and keeping the existing persisting logic in Find across files will make experience inconsistent.

Can we not use the same persisting logic for Find in File instead of configuration setting?

**Comment by stefcameron** [comment]
I'd love to see a setting default for Alt+C (case-sensitive search and match). I'd like to be able to configure Code such that it defaults to case-sensitive search/match, and then be able to use Alt+C to toggle it on/off (but Alt+C should _not_ change my default setting).

**Comment by rebornix** [comment]
Let's track the setting persistence in #6158
