### ISSUE TITLE
Breakpoints in extension debug can't be hit

### ISSUE THREAD

**Issue by Huachao** [Microsoft/vscode#10341]
- VSCode Version: 1.4.0
- OS Version: Windows 10 Enterprise(10.0.14393) And Ubuntu 16.04

Steps to Reproduce:

1. Set breakpoints in extension typescript code.
2. Press `F5` to start the debugging, the breakpoints seem to be getting hit, but the editor isn't getting updated, and debugger window is empty, the debug breakpoints are disabled. I have to hit the continue button a couple of times before the debugger kicks in.

@DonJayamanne also met the same issue

The issue was originally posted in #10160

**Comment by weinand** [comment]
@Huachao does the "CALL STACK" view show any message?

**Comment by Huachao** [comment]
@weinand show nothing in '__CALL STACK__', '__WATCH__' and '__VARIABLES__'

**Comment by DonJayamanne** [comment]
@weinand , here's a screen recording of the issue along with the steps to reproduce it:  

1. Clone https://github.com/Microsoft/vscode-extension-samples.git  
2. Open previewhtml-sample in vscode (run npm install - usual stuff)   
3. Modify the package.json so that the extension gets activated when python file is opened (not necessary, but to prove that extension launches and debugger is slow)   
4. Add breakpoint (in this case to the activate function)
5. Start debugging

Expected outcome: Breakpoint would hit immediately
Observed outcome: Debugger takes over 45 seconds (sometimes much longer) to hit a breaktpoint.

As a result of this debugging extensions is now very slow.

![debuggerbug](https://cloud.githubusercontent.com/assets/1948812/17726363/eafcf8d8-6495-11e6-8194-87c79a10e52f.gif)

**Comment by DonJayamanne** [comment]
@weinand  Same problem exists in the latest insider build (over 75 seconds!!)

```
55168276e4c0b6ec2404ac20af04eeed5f5b1000
2016-08-17T06:02:28.616Z
```

**Comment by weinand** [comment]
@DonJayamanne please do not add findings like yours to existing issues but create new issues instead. The original issue talks about breakpoints not being hit at all whereas you are seeing a UI delay when hitting the breakpoint. These are different things and it is difficult for me to investigate and address them in a single issue.

@DonJayamanne since VS Code does not ship with source code, extension host debugging has to load the source (a 2 MB file) from a CDN. Here in Zurich (we have a slow connection) this loading takes 2 seconds. So you seem to have a very slow connection.
In VS Code 1.4 this delay should only occur for the first breakpoint in a debug session.
Is this the behaviour you are seeing?
 
In the current insider build 1.5.0 we started to cache the source across sessions, so only the first debug session of a new build VS Code should shows this problem. 
Please try whether this helps in your situation.

What is missing right now is a progress indicator that explains the loading to the user.

**Comment by DonJayamanne** [comment]
@weinand , sorry about updating this issue, will move to another one. I updated this as i believe they are the same - as he too indicates that debugging works after some time (this is exactly what I am experiencing). 
>hit the continue button a couple of times before the debugger kicks in.

Anyways. I'll create a separate issue.

**Comment by weinand** [comment]
@DonJayamanne thanks, and please answer my questions in the comment from above

**Comment by DonJayamanne** [comment]
>In VS Code 1.4 this delay should only occur for the first breakpoint in a debug session.

Yes, this is what I am experiencing.

- However, I have been debugging my extensions for the past few months and it has never been this slow. Something has definitely changed recently. Not sure what.  
- Also, does this mean that without an internet connection, I will not be able to debug a local extension?  

My operating system is still the same:  
- OS X  
- Nodejs 5.10 as per the requirements on vs code dev site

**Comment by weinand** [comment]
In older version of VS Code, debugging an extension would just show the minified JavaScript which was not very helpful. Now VS Code shows the formatted TypeScript source (which is cached starting with VSC 1.5).
If you are offline, and if the source is not in your local cache, the debugger falls back to the minified JavaScript.

**Comment by DonJayamanne** [comment]
I thought it always displayed the typescript source by utilizing the source maps. 
Hmm, well you know this stuff better than me.
Oki doki, thanks then. Guess i'll have to live with the slight delay. I thought my 100Mbps connection would be good (just tested it at 96Mbps) - fyi I live down in Australia and our connections speeds are pretty average.   
At least there's an explanation for this. Won't be creating an issue for this.
Thanks @weinand

**Comment by weinand** [comment]
@DonJayamanne the node debugger was only utilizing the source maps if the source was available locally. It did not fetch the source from remote sites.
Of course this does not not affect the extension under development because there the source is locally available anyways. But it improves the situation if you step from the extension's code into the extension host code. Now you are able to see how your extension's code is called. 

Have you been able to verify that sourcemap caching works for you in the insider's drop? So even after a restart of VS Code hitting the first breakpoint should be in the 1 second range.

**Comment by DonJayamanne** [comment]
@weinand , tested with insider build.
It takes 6 seconds the first time and approx 1 second during subsequent debugs.
So that solves this issue at least for me. Thanks for your help.   

One last question, this feature of tracing through the typescript code for vscode (using cdn, etc) was added recently, correct? If so, that would explain the slight delay in breakpoints being hit in the new version of VS Code.

**Comment by weinand** [comment]
@DonJayamanne yes, loading source code remotely was added in 1.4.
And your issue with the 45 seconds delay for breakpoints being hit is a result of this.

Now you are asking for the reason for a "slight delay in breakpoints". I thought we were discussing exactly the reason for this delay the whole time?
Or is there another delay you are seeing?

**Comment by DonJayamanne** [comment]
@weinand , this is the delay i am seeing. Thanks.

**Comment by Huachao** [comment]
@weinand , I think you can close the issue now, the first time delay takes less than 10 seconds, and after that everything is OK. Thanks for your explanation.
