### ISSUE TITLE
Support multiline description in treeview when the treeItem is collapsed

### ISSUE THREAD

**Issue by HaoboGu** [microsoft/vscode#103403]
I found that VSCode's TreeView cannot display multi-line description:
![image](https://user-images.githubusercontent.com/8640918/88525162-d4781780-d02c-11ea-9076-9dc981773eb8.png)

The description for `java.applet` is actually `"Provides the classes\n necessary to create an applet and the classes an applet uses to communicate with its applet context."`

Many extensions also suffer from this, for example, gitlens:
![image](https://user-images.githubusercontent.com/8640918/88526211-3ab16a00-d02e-11ea-9799-7167944afb45.png)

the user has to hover on it to get full information. 

IMO, the target of the description field is to provide more detailed info to users. So the length of the description is commonly long. But if the description is long, the user has to adjust the window once and once again, or hover on it. Both operations are annoying and unnecessary. I think this can be avoid by supporting multi-line description when the `TreeItem` is **collapsed**. 

If anyone has better solutions, please leave a comment 😉

**Comment by alexr00** [comment]
It is intentional that tree items don't wrap. It would disrupt the layout, and tree views should be scannable (longer lines are generally less scannable.

However, the tree view allows you to do two things that _do_ wrap. You can set a `message` (seen in Test View below), or Welcome Content (seen in the No Folder Open view below):

![image](https://user-images.githubusercontent.com/38270282/88919538-8c930380-d26b-11ea-81fc-f6195f11d11a.png)

`message` API: https://github.com/Microsoft/vscode/blob/bb9c167ef278d1fc5ed64ee2ae15b941e141e0b4/src/vs/vscode.d.ts#L8293-L8297 

Example of Welcome Content: https://github.com/microsoft/vscode-pull-request-github/blob/7fded38d4765d43ab9ce79c18534c727fdd1af83/package.json#L693-L704
