### ISSUE TITLE
extensions are not loading up

### ISSUE THREAD

**Issue by maitrey3196** [microsoft/vscode#103561]
We have written the n
Issue Type: <b>Bug</b>

Your Code installation appears to be corrupt. Please reinstall. this problem is arising while installing visual studio code in windows 10

**Comment by gjsjohnmurray** [comment]
Any antivirus interfering with the files VS Code installed?

**Comment by steshie-cmd** [comment]
Hello, I am experiencing an issue because none of the extensions on my VS Code are loading up or even showing at all. I have tried numerous times to install 'Live Server' from the extensions search field in VS Code, but nothing is showing up in the search results. Is there something I am missing please? I installed the VS Code in the Xubuntu in my VM. However, Windows 10 is my host OS. 
![Screenshot_2020-07-29_19-12-21](https://user-images.githubusercontent.com/68727838/88842628-755f0200-d1e8-11ea-8f68-55683f13650a.png)

**Comment by steshie-cmd** [comment]
Also, another issue is whenever I try to type in a command in the text editor's command line, then hit 'enter', no results are shown in the next line. I would really appreciate some help in all this as I feel very stuck :(
![5](https://user-images.githubusercontent.com/68727838/88842775-b1926280-d1e8-11ea-9e85-9c7ee6915f08.png)

**Comment by joaomoreno** [comment]
@steshie-cmd Please file individual issues for your problems.

@maitrey3196 Can you elaborate on your specific problem?
