### ISSUE TITLE
Intellisense auto-completion is stuck on "Loading"

### ISSUE THREAD

**Issue by Sov3rain** [microsoft/vscode#103567]
- VSCode Version: 1.47.3
- OS Version: Windows 10.0.18363

Steps to Reproduce:

1. Open or create any project.
2. Try to auto complete anything
3. Completion list is stuck on "loading"

Does this issue occur when all extensions are disabled?: I can't tell for sure because it's mainly related to code completion (C#, Dart) with extentions. It appears with any language or framework though.

I get an error in dev tools: ERR Cannot read property 'templateData' of null: TypeError: Cannot read property 'templateData' of null [...].

I attached the complete stack trace. It may be the completion list rendering for what I understand. Everything returns to normal when I restart VS Code.

[stacktrace.log](https://github.com/microsoft/vscode/files/4995908/stacktrace.log)

**Comment by lucaluca** [comment]
I have been having similar issues with Intellisense for months. It works when VS Code starts, but after a short time it just hangs and becomes unresponsive until I reload the window. Search breaks as well when this happens, in that it also hangs on every query. I can find no error in any output logs that explains this, Log (Extension Host) with Trace level debugging shows no warnings or errors at all. I have tried dozens of different configurations including disabling all extensions, completely wiping and re-installing VSCode, etc. I'm reloading VSCode dozens of times a day. Attached is the Log (Extension Host) with Trace level debugging from a crash this afternoon, and the Python log with some Jedi deprecation warnings that don't seem to have anything to do with it but who knows. Python and Remote - WSL were the only extensions enabled. This is on a fresh VS Code installation from this afternoon. 

I also want to chime in with a suggestion. From what I can tell, issues like this have been affecting a large number of people for years because there are a ton of issues being opened about Intellisense hanging. I understand this sort of issue is hard to reproduce, and what makes it difficult is that it's hard for us users to reproduce as well. But the issues keep getting auto-closed because they can't be reproduced. Developers and others have [pointed out](https://github.com/microsoft/vscode/issues/98754#issuecomment-637341917) that Intellisense is a "black box" that is difficult to debug, and the attached logs clearly don't give any indication about what broke. Is there any way to have VS Code proactively give us an actual error message, stack trace, or something like that if Intellisense breaks or doesn't work after X seconds, which we could then report to you? This is a fatal error in the sense that I can't use VS Code without Intellisense or Search and the only remedy is completely reloading it. Please help us gather the data you need to understand and improve this issue. 

[Extension host.log](https://github.com/microsoft/vscode/files/5004109/crash.log)
[Python.log](https://github.com/microsoft/vscode/files/5004114/crash.log)

**Comment by tchapin** [comment]
I also had intellisense and snippets stop working with the latest update. Using Python.

Version: 1.47.3 (user setup)
Commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e
Date: 2020-07-23T13:12:49.994Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362
