### ISSUE TITLE
DebugConfiguration is an empty object when no launch config is present

### ISSUE THREAD

**Issue by ChaseMor** [microsoft/vscode#103530]
- VSCode Version: 1..47.2
- OS Version: Darwin x64 19.5.0

Steps to Reproduce:

1. Delete launch config in .`vscode` folder
2. Start debugger

Does this issue occur when all extensions are disabled?: Yes

If no launch config is present and a debugger is started, when `resolveDebugConfiguration` is called, the `debugConfiguration` parameter passed is an empty object. This is an issue because the empty object is not the correct type for this parameter. The parameter's type is `DebugConfiguration` which has required fields and doesn't include the empty object.
https://github.com/microsoft/vscode/blob/c5ae1f3f45fdb6ae247a4549f3c11f548b6d18b7/src/vs/vscode.d.ts#L10703

**Comment by isidorn** [comment]
Yes, I acknowledge this behavior, and we were always behaving like this.
I believe some debug adapters are relying on this behavior so they can fill in the fields for the debug configuration for the no launch.json case.

So we could either:
1. Change the API signature that it is more relaxed and also allows empty objects to be passed
2. In this case do not call the `resolveDebugConfiguartion`

I think 1. is the proper way to ge here

@weinand let me know what you think

**Comment by weinand** [comment]
This is a trick issue. 
Yes, we should really change the signature of `resolveDebugConfiguration(...)` to use something like `debugConfiguration: DebugConfiguration | {}`, but this will break extensions at compile time. On the other hand they are already broken at runtime because with the current signature they do not have to cope with empty debug configs, but they might receive one.

**Comment by connor4312** [comment]
Hm, yea. I wasn't aware of this behavior, js-debug might work in the scenario but I haven't tested it.

In this scenario, VS Code seems to know the debug `type`. Does it also know the `request` and other information sufficient to restore the `DebugConfiguration` interface?

**Comment by weinand** [comment]
@connor4312 
The scenario is:
no launch config exists and user presses F5. We wanted to give a debug extension a chance to figure out what to do (before we got dynamic launch configs).

Node-debug uses this code:
https://github.com/microsoft/vscode-node-debug/blob/4b2d2ca0dbe3bec12649a90c40bd0e2c904c0ca0/src/node/extension/configurationProvider.ts#L62-L70
and
https://github.com/microsoft/vscode-node-debug/blob/4b2d2ca0dbe3bec12649a90c40bd0e2c904c0ca0/src/node/extension/configurationProvider.ts#L317-L322

As you can see we fill in all properties of the `DebugConfiguration` (but the debug `type` was preselected by some VS Code heuristic). 
@isidorn could you please fill in here the details of how we determine what debug extension to use (which determines the debug `type`).

**Comment by connor4312** [comment]
Oh, right. I copied that from node-debug into js-debug early on but I didn't recognize the case in which it's hit.

**Comment by isidorn** [comment]
@weinand we decide which debug extension to use by looking at the language of the active editor and try to match it with the `languages` contribution of the debug extension.

Code pointer https://github.com/microsoft/vscode/blob/15e410b98b88ca11bd3b059c5b7eec04b08693ce/src/vs/workbench/contrib/debug/browser/debugConfigurationManager.ts#L567

**Comment by weinand** [comment]
yes, I'm aware of that. But what's about the case when no file is open in the editor?

**Comment by isidorn** [comment]
If there is no file open in the editor we ask the user via quick pick what debug extension to use.
In practice there is never just one installed since we have built in js-debug, chrome legacy and node legacy. But even if there was just one we would still ask via quick pick (also to show the `more...` action).

![Screenshot 2020-07-30 at 09 53 38](https://user-images.githubusercontent.com/1926584/88896732-8e000400-d24a-11ea-9dd8-01885889cf26.png)
