### ISSUE TITLE
Trusted Types compatibility: Make VSCode TrustedTypes compliant

### ISSUE THREAD

**Issue by annkamsk** [microsoft/vscode#103699]
Hi, I’m Anna, working as an intern on the Google Security team this summer. I’m working on a project that’s part of the larger effort to harden popular open-source libraries against web vulnerabilities.

Following up on an email exchange with @egamma and @jrieken, we’re planning to add [Trusted Types](https://github.com/w3c/webappsec-trusted-types) to VSCode’s codebase.

# What are Trusted Types

DOM-based cross-site scripting (DOM XSS) is one of the most common web security vulnerabilities, and it's very easy to introduce it in your application. 

Trusted Types give you the tools to write, security review, and maintain applications free of DOM XSS vulnerabilities by making the dangerous web API functions secure by default. Trusted Types are supported in Chrome since version 83. For more information see https://web.dev/trusted-types/

# Why make VSCode compliant with Trusted Types?

Having dealt with large JS/TS codebases, we (the Google ISE team) noticed that while correctly escaping the data is relatively easy - what is hard is assuring that this is done comprehensively. For example, that all "scripty" sinks in innerHTML are covered, and that the escaping is done every time the data reaches them. That's where Trusted Types help tremendously. In our estimations, Trusted Types might effectively kill XSS for serverless applications.

VSCode is a large codebase running in a very sensitive application, having the assurance that it is free of XSS seems like a worthy goal. 

# Approximate cost of the effort

After running a static analysis pass for Trusted Types compliance on VSCode, I discovered [103 potential issues](https://github.com/annkamsk/vscode/blob/docs/vscode_security_issues.md), ranging from trivial refactorings (assigning non-html literal strings to innerHTML, ~45% of issues) to much more complex cases (building arbitrary html). 
I’m planning to start fixing the simplest ones that can be changed without creating a Trusted Types Policy and then take on less trivial problems. Each change will group issues with similar causes and be tracked by a separate more specific github issue. 

You can perform the check for Trusted Types compliance on VSCode yourself by running [this fork of the VSCode](https://github.com/annkamsk/vscode), where I added a script that does exactly that. 

Edit: Tagging @engelsdamien and @koto for visibility

**Comment by engelsdamien** [comment]
Hi there, @koto and myself are mentoring Anna for this project.

Please let us know if there is any process you'd like us to follow for PRs (in addition to the normal contribution guidelines)

**Comment by jrieken** [comment]
@annkamsk Thanks so far. I went through the usages of `innerHTML` and to make it simpler for us to assign and review PRs I suggest the following plan

1.  Lots of `innerHTML`-use is coming from [`renderCodicons`](https://github.com/microsoft/vscode/blob/f0646f81aa1c4ba5cdada749ca1a18bf60b14dc1/src/vs/base/common/codicons.ts#L502). We should have an equivalent that returns elements instead of a string and adopt it. Given this will be a uniform adoption it's OK to put this into a single PR.
1. Another common `innerHTML`-use is updating style elements, like [this](https://github.com/microsoft/vscode/blob/8265dfec6f94dca735fcfd4fd4329fdae5fa71c5/src/vs/base/browser/ui/breadcrumbs/breadcrumbsWidget.ts#L184). This is part of our theming story and I believe usages can be replaced with `textContent`. This should also be a relatively uniform change and OK to have in a single PR. 
1. Other `innerHTML`-use. Since these changes will require more review it's best to create more fine grained PRs so that owners can do the review. A good rule of thumb would a PR per feature folder, like 'breadcrumbs' or 'codelens'. 

Unfortunately, the last item means a little more overhead. An alternative (and that's how we have often done such changes in the past) is to create and manage a list of pending adoptions and to assign people to fix them. That guarantees a broad understanding of the issue since the whole team will be involved. Generally, the team is happy to make those changes but it needs some tool to discover invalid `innerHTML`-usages (I have been using TypeScript reference search).

#HappyCoding

**Comment by engelsdamien** [comment]
Hey @jrieken thanks for the responsiveness. 

We are currently working on releasing tsec on npm so we can add it as a runnable target in you package.json's scripts. As soon as this is done, @annkamsk will send a PR so that it becomes easy to run tsec at head.

Note that tsec is still under developpement and we are still fixing bugs in it, so it might miss some things for now. 
Long term, tsec will also probably get deprecated in favor of something that is more developper friendly to give warnings & suggested fixes directly in the editor. (@uraj can probably give more details.)

Cheers

 - Damien

**Comment by jrieken** [comment]
Thanks for the heads-up. We will prepare the August release next week and after that we'll enter "debt week". Having some workable version by then would be the best because folks are in clean-up-mode and can tackle violations by themselves.

**Comment by annkamsk** [comment]
Hi @jrieken,
I've seen that the VSCode team already fixed a significant number of issues, which is really exciting. To make the expectations clear, would you prefer to collect and solve the rest of the TT violations within your team or would our PRs be still welcome? Either way, I'd be more than happy to provide support. 
If you considered it helpful, I could work on eg. builders for TT policy, so that your team can quickly adapt the code to them. 

I'm attaching also a current list of violations that I haven't seen mentioned in already existing issues. Some of them require use of the policy. 

### innerHTML
- [ ] src/vs/base/browser/markdownRenderer.ts:164:6
- [ ] src/vs/base/browser/markdownRenderer.ts:246:2
- [ ] src/vs/editor/browser/view/domLineBreaksComputer.ts:110:2
- [ ] src/vs/editor/browser/widget/diffEditorWidget.ts:2160:3
- [ ] src/vs/editor/browser/widget/diffEditorWidget.ts:2165:3
- [ ] src/vs/workbench/contrib/notebook/browser/view/renderers/webviewPreloads.ts:83:4
- [ ] src/vs/workbench/contrib/notebook/browser/view/renderers/webviewPreloads.ts:378:7
- [ ] src/vs/code/electron-sandbox/processExplorer/processExplorerMain.ts:323:3
- [ ] src/vs/editor/standalone/browser/colorizer.ts:43:4
- [ ] src/vs/editor/standalone/browser/standaloneThemeServiceImpl.ts:215:4
- [ ] src/vs/editor/standalone/browser/standaloneThemeServiceImpl.ts:224:3
- [ ] src/vs/editor/standalone/browser/standaloneThemeServiceImpl.ts:294:47
- [ ] src/vs/editor/test/browser/controller/imeTester.ts:58:3
- [ ] src/vs/editor/test/browser/controller/imeTester.ts:72:2

### setAttribute
- [ ] src/vs/loader.js:701

### Workers
- [ ] src/vs/base/worker/defaultWorkerFactory.ts:16:15
- [ ] src/vs/base/worker/defaultWorkerFactory.ts:24:14
- [ ] src/vs/workbench/services/extensions/browser/webWorkerExtensionHost.ts:177:22
- [ ] src/vs/workbench/services/extensions/worker/extensionHostWorker.ts:50:18
- [ ] src/vs/workbench/services/extensions/worker/extensionHostWorker.ts:51:2

### Imports
- [ ] src/vs/workbench/services/extensions/worker/extensionHostWorkerMain.ts:12

### DOMParser.parseFromString
- [ ] src/vs/workbench/contrib/extensions/browser/extensionEditor.ts:64
- [ ] src/vs/workbench/contrib/webview/browser/pre/main.js:370

**Comment by engelsdamien** [comment]
@jrieken any updates on this? 

We don't have clear visibility on which issues the VSCode team is planning on fixing & we would like to avoid duplicating work. 

Is it safe to assume that the issue outlined above by annkamsk@ are not being worked on by anyone?

**Comment by jrieken** [comment]
Sorry! This somehow got lost... We still have https://github.com/microsoft/vscode/issues/106395 for some violation cleanup. I can ping folks directly to see if a potential conflict is about to happen - tho it unlikely as this is treated as debt work for of us and that's usually tackled during the first week in the milestone (roughly the first week in the month). So, yeah more PRs are definitely welcome. 

We also have https://github.com/microsoft/vscode/issues/106396 which is about using policies. For that there is some more work on my plate and we should re-focus the discussion from the amd-loader (which is some scenarios like gh-codespaces not in our control or for desktop not used like that) to simpler cases, like markdown-rendering or line-rendering of the editor itself.

**Comment by engelsdamien** [comment]
Thanks for the update @jrieken 

@annkamsk is getting close to the end of her internship, but she will focus on the changes I proposed in https://github.com/microsoft/vscode/issues/106396#issuecomment-692571690 for now and leave most of the remaining `innerHTML` issues to the VSCode team. 

If time permits, we will pick up another issue from non-innerHTML ones above.

**Comment by jrieken** [comment]
> @annkamsk is getting close to the end of her internship, but she will focus on the changes I proposed in #106396 (comment) for now and leave most of the remaining innerHTML issues to the VSCode team.

That makes sense. I like the loader changes you have proposed (and I should probably comment on that issue) but I didn't have enough time to think/understand everything. One thing is that the loader creates many new urls, e.g when asynchronously importing more modules, so it does need to know how to create a trusted url from to strings.

**Comment by Siegrift** [comment]
Hi @jrieken , most of the changes to tsec regarding Trusted Types are merged internally and we would like to release them at the beginning of the next week. I will try to test whether the changes won't cause regressions for your project, but I am fairly confident there shouldn't be any. In case you notice any problems feel free to create an issue in https://github.com/googleinterns/tsec (to avoid spamming this thread).

Notable changes:
* Added new rule for banning the use of dynamic imports (currently this one doesn't support TT)
* All of the sinks accepting a string now accept a form of Trusted Type. Due to [TS limitation](https://github.com/microsoft/TypeScript/issues/30024) you need to use workarounds when using TT in the sinks. We offer a few alternatives, which will be documented in `README.md` once we release the new version.
* There have been small enhancements to the checker and we are able to catch more violating patterns (e.g. `window[eval](someString)`)

**Comment by jrieken** [comment]
> All of the sinks accepting a string now accept a form of Trusted Type. Due to TS limitation you need to use workarounds when using TT in the sinks

Excited for that. I have done more TT-work this week and I am using the `as unknown as string` construct which is ugly and confuses tsec. Another complexity is that we don't always know if trusted types are available or not... That's maybe specific to our project and how we polyfill trusted types(*) but today we end up in situtations where we have or-types like so `string | TrustedHTML`, e.g in the [editor rendering](https://github.com/microsoft/vscode/blob/feca52798c899ebccf6b4c7fdfa555e7c86815aa/src/vs/editor/browser/view/viewLayer.ts#L510-L518)

(*) today the polyfill comes with our amd-loader but not all consumer of the monaco-editor must use this loader.

**Comment by jrieken** [comment]
Related to tsec (and sorry I should have filed an issue) but it doesn't seem to catch innerHTML-assigments like [this](https://github.com/microsoft/vscode/blob/master/src/vs/editor/browser/view/domLineBreaksComputer.ts#L110)

**Comment by Siegrift** [comment]
> Excited for that. I have done more TT-work this week and I am using the as unknown as string construct which is ugly and confuses tsec. Another complexity is that we don't always know if trusted types are available or not... That's maybe specific to our project and how we polyfill trusted types(*) but today we end up in situtations where we have or-types like so string | TrustedHTML, e.g in the editor rendering

The patterns you use are one of the allowed patterns by tsec, so we got you covered :)

> Related to tsec (and sorry I should have filed an issue) but it doesn't seem to catch innerHTML-assigments like this

This will be fixed as well.

I also verified today whether the new changes on vscode repo and they work as expected. You will need to add the language service plugin to the `tsconfig.json`, but it will be documented how and you can just copy&paste the configuration from tsec `README.md` :)

**Comment by Siegrift** [comment]
@jrieken The new version of tsec was released yesterday. I've created a [PR#108682](https://github.com/microsoft/vscode/pull/108682) which enables tsec as a language service plugin, so you can see the violations in the IDE!

As I've mentioned earlier, we also support some "forms" of Trusted Types expressions. All of the variants you can use are documented in the [README of tsec](https://github.com/googleinterns/tsec).

There was one thing I needed to do _(and not sure if it's just my issue)_ was that I needed to explicitly update `tsec` dependency, although there was no change in `yarn.lock` _(it was probably just to invalidate the cache)_. Anyway, I recommend doing an explicit update of `tsec` using `yarn upgrade tsec --latest`.

If there are any problems/questions, be sure to reach out to me :)

**Comment by engelsdamien** [comment]
Sorry I forgot to do it earlier, but wanted to update the bug to mention that @annkamsk has finished her internship at the beginning on this month. She was unfortunately not able to get to the `trustedScriptUrl` rewrites I mentioned above, so feel free to take them over.

I will keep following this and the other trusted types related issues, please reach out if you have any questions or need help with the remaining issues.

**Comment by jrieken** [comment]
fyi - I have just pushed a commit that enables trusted types for tomorrows insiders build 🥳 

Things that are still to be done:

* [ ] perform a thorough review of our policy usages
* [ ] we have a [default policy](https://github.com/microsoft/vscode/blob/bbb0aadc87d1ebf253f93b41eefae0c3fd4f1b44/src/vs/code/electron-browser/workbench/workbench.js#L50) which we use instead of exploding in the face our users. After gaining more confidence we should make this more strict
* [ ] we also have a legit usage of the default policy because of an electron issue (https://github.com/electron/electron/issues/27211), tho that usage is [quite strict](https://github.com/microsoft/vscode/blob/bbb0aadc87d1ebf253f93b41eefae0c3fd4f1b44/src/vs/code/electron-browser/workbench/workbench.js#L56). Maybe @Siegrift or @engelsdamien can advise
* [ ] I don't think tsec is ready to be part of our build pipeline. there is still TS trouble, the inability to ignore policy usage errors, and differences between tsec and chromiums actual behaviour.

**Comment by koto** [comment]
That's awesome! I'm super excited about that! 

We've seen default policies like that one, it seems very expected during the migration. The only alternative for upstream Electron is to I guess use the DOM APIs for the initial HTML, I'll look into the Electron issue directly.

From our experience, the static checks (so tsec) worked better, but of course internally tsec is part of a bigger pipeline tied to our build system, so we don't have many of the integration problems you're facing. We're constantly working on improving tsec, such that it will eventually be ready to integrate, please keep filing bugs and nagging us if we don't fix them ;)

**Comment by koto** [comment]
Can you check on your end if https://github.com/koto/electron/commit/02d0fd09d8c842c393e4949a901e9771b4ab5762 addresses the Electron issue? My environment seems to have some issues building Electron now...

**Comment by koto** [comment]
@jrieken what's the easiest way to reproduce the default policy call caused by Electron? I `yarn run compile`d vscode, followed by `./scripts/code.sh`. 

I see the default policy installed on the Code window, but don't see it being called yet - I tried opening a folder, Terminal window, clicking on the links in the landing page, editing files etc.

**Comment by jrieken** [comment]
> I see the default policy installed on the Code window, but don't see it being called yet

Either go "Extensions Viewlet > Select any extension so that its extension editor shows" or alternatively create a `test.md` file, edit its source and then trigger preview from the editor tool bar

**Comment by jrieken** [comment]
> Can you check on your end if koto/electron@02d0fd0 addresses the Electron issue? My environment seems to have some issues building Electron now...

Sorry, didn't reply here. We actually don't build electron in our machine. Looping in @deepak1556 in case he can help with https://github.com/koto/electron/commit/02d0fd09d8c842c393e4949a901e9771b4ab5762

**Comment by engelsdamien** [comment]
Hey @jrieken,

Thanks for your patience, I have some updates about how we can reduce and review the use of policies.

We just released a library to help with this called "safevalues" ([github](https://github.com/google/safevalues), [npm](https://www.npmjs.com/package/safevalues)). It contains:
 - safe-by-construction builder APIs
 - helpers to assign to DOM sinks without having to use casts
 - utilities to help refactor legacy code & encode patterns not supported by the safe by construction APIs above
 
My plan to improve the current situation is to do the following: 
 
1. Add all current tsec violations to `src/tsec.exemptions.json` explicitly. This make the `tsec-compile-check` script stop outputting violations (including the current false positives), but also force any new code that introduce a violation to have to modify the exemptions list, which should prevent new violations. I think this is what you need to start including tsec in your build/CI pipeline.
2.  Move all the current policy usages to use ["legacy" conversions](https://github.com/google/safevalues#legacy-conversions), which should get rid of all the `TrustedHTML|string` types in favor of pure `TrustedHTML` as well as fix all of the sink assignments. We are working on a tsec release to also track usage of these functions & they will be tracked in the excemption list as any other violation.
3. Incrementally move the "legacy" conversions to callers, until they reach the place where values are produces / mutated at which point they will be either refactored into on of the safe-by-construction builders or use a ["reviewed" conversion](https://github.com/google/safevalues#reviewed-conversions), which includes an explanation of why the code is safe as part of the API.
4. The final state should be that tsec's exemption list only contains a few references to these "reviewed" conversions, which fully encode the security sensitive surface of VSCode & are easy to review for a human.

My questions for you are: 

- Does this sound like a reasonable plan ? I have a [working proof of concept](https://github.com/engelsdamien/vscode/commit/d3fac4c25bd41f8d3a626081d2f6f4236506824c) for points 1 & 2 above if you want to see what it would look like.
- Are there some restrictions in VSCode that would prevent you from depending on `safevalues` ? When creating the proof of concept above, I ran into a linter check complaining that my imports didn't start with 'vs/'
- Do you have experience with GitHub's [code owners](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners) mechanism ? It would be beneficial to restrict who can edit / needs to review changes to tsec's exemption list to ensure that the "reviewed" conversions are used properly.

**Comment by jrieken** [comment]
> Does this sound like a reasonable plan ? I have a working proof of concept for points 1 & 2 above if you want to see what it would look like.

Yes - I like where this is going. The changes to the `src/tsec.exemptions.json` list is very welcome as well. 

> Are there some restrictions in VSCode that would prevent you from depending on safevalues ? When creating the proof of concept above, I ran into a linter check complaining that my imports didn't start with 'vs/'

I am afraid that's a little complicated. Everything in the common-, browser-, and editor-layer is also shipped with the monaco editor and due to bundling challenges we only allow files from within those folders. We solve this by coping dependencies into our source tree (and we then re-export them). The marked-js and insane usages are samples for this, see `src/vs/base/common/marked`. We would do something similar with `safevalues`, likely bundle it first. Depending on how often `safevalues` is going to change this should be manageable. 

> Do you have experience with GitHub's code owners mechanism ? It would be beneficial to restrict who can edit / needs to review changes to tsec's exemption list to ensure that the "reviewed" conversions are used properly.

We have actually not used that. We are a relatively small and close team and so far things have worked out for us. I need to take a look first and then would propose this to the team first.

**Comment by engelsdamien** [comment]
Awesome, thanks for the feedback, you should start receiving PRs by the end of the week then.

> I am afraid that's a little complicated. Everything in the common-, browser-, and editor-layer is also shipped with the monaco editor and due to bundling challenges we only allow files from within those folders. We solve this by coping dependencies into our source tree (and we then re-export them). The marked-js and insane usages are samples for this, see `src/vs/base/common/marked`. We would do something similar with `safevalues`, likely bundle it first. Depending on how often `safevalues` is going to change this should be manageable.

No worries, this also has the positive side effect that you get tsec checking dependencies for free. 

Do you have a script that can pull in the dependencies automatically, or is this a manual process ? If so I will just try to match what marked and insane are doing.

**Comment by jrieken** [comment]
> Do you have a script that can pull in the dependencies automatically, or is this a manual process 

All manual... Since `safevalues` is using dom API it should be living inside `vs/base/browser`. Best would be if it can be compiled into AMD or UMD so that we easily load it - otherwise would need to [massage](https://github.com/microsoft/vscode/blob/3ff057ce33572d07e8087ca5b292fef2ff5e1009/src/vs/base/common/insane/insane.js#L467-L474) it a little.

**Comment by jrieken** [comment]
We didn't get to celebrate this properly but VS Code ships with trusted types enabled since quite while. Closing this epic, popping a drink, and thanks to everyone that has helped us here.

**Comment by koto** [comment]
Thank you Johannes, that was indeed a very joyful ride, and wouldn't be possible with y'all involvement! We're happy to help with anything TT in the future - but in the meantime, may your XSSes be 0 :) 

(btw I think the default policy can now remove the Electron workaround? I'm happy to send a patch if so).
