### ISSUE TITLE
how to fix my error plz tell me

### ISSUE THREAD

**Issue by robin1117** [microsoft/vscode#103692]
plzzzzz help when i compile shows this error
\\ERROR\\
PS C:\Users\Ryzen 2600\Desktop\New folder (2)> gcc first.c
C:/Program Files (x86)/mingw-w64/i686-8.1.0-posix-dwarf-rt_v6-rev0/mingw32/bin/../lib/gcc/i686-w64-mingw32/8.1.0/../../../../i686-w64-mingw32/lib/../lib/libmingw32.a(lib32_libmingw32_a-crt0_c.o):crt0_c.c:(.text.startup+0x39): undefined reference to `WinMain@16'   
collect2.exe: error: ld returned 1 exit status
PS C:\Users\Ryzen 2600\Desktop\New folder (2)>

\\CODE\\
#include<stdio.h>
int WinMain()
{
    printf("helloo");
    return 0;
}

**Comment by cvennel** [comment]
C code should have a main function  not a WinMain() function.

`int WinMain()` should just change to `int main()` 

see this [Hello world example](https://www.learn-c.org/en/Hello%2C_World%21)

Since this is not vscode specific this question would probably have been better asked on a site like [stack overflow](https://stackoverflow.com/)

**Comment by gjsjohnmurray** [comment]
/question. Thanks @cvennel

**Comment by cvennel** [comment]
Happy to help
