### ISSUE TITLE
Intellisense position issue

### ISSUE THREAD

**Issue by normalser** [Microsoft/vscode#10371]
- VSCode Version: Code - Insiders 1.5.0-insider (06d85431730fe33beff7c56b5ef6f4514ad326ba, 2016-08-09T16:02:06.523Z)
- OS Version: Darwin x64 15.6.0

Steps to Reproduce:
1. Have "wide" file and scroll to the right when intellisense is open
2. 
   ![image](https://cloud.githubusercontent.com/assets/1723815/17537903/663d1808-5e6e-11e6-9a9a-3861032f3438.png)

Should probably stay within editor area

**Comment by joaomoreno** [comment]
![image](https://cloud.githubusercontent.com/assets/22350/17548572/befe7224-5eec-11e6-9cd0-9bd8f26e1907.png)

Can't seem to reproduce. Can you show me the screenshot including the whole window?

**Comment by wallverb** [comment]
Hope it helps:

![bfhzar6gje](https://cloud.githubusercontent.com/assets/1723815/17553448/cb460f06-5ed3-11e6-83b9-84bb716cfe8b.gif)

**Comment by joaomoreno** [comment]
Thanks!

**Comment by joaomoreno** [comment]
cc @alexandrudima

**Comment by alexandrudima** [comment]
The suggest widget should not be rendered when the cursor is not visible:

e.g.

![kapture 2018-04-09 at 12 13 43](https://user-images.githubusercontent.com/5047891/38492521-7fb90dfe-3bef-11e8-80e9-0baa5d4cf313.gif)

**Comment by roblourens** [comment]
![apr-25-2018 16-41-35](https://user-images.githubusercontent.com/323878/39278363-91cd97f2-48a7-11e8-94f4-8853eb779190.gif)
 
It can still fly out of the editor when the window is resizing.

**Comment by ramya-rao-a** [comment]
I've pushed a fix to not allocate space for the details/docs section until an item in the list does have details/docs to show.

This will help the above case where textual completions don't have any details/docs to begin with.

Note: This doesn't stop from the suggest widget to flowing into the side bar if there is no space.
But, it does make the suggest widget occupy the space right below the cursor rather than assuming that there are docs and having ghost space.
