### ISSUE TITLE
Request for Debug to handle missing extension from configuration

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode#103719]
I'm developing in a remote .NET dev container. Due to some custom config, I noticed I didn't have the C# extension installed in the container, and when I tried to run my code, I got the error `Configured debug type coreclr is not supported.`

![image](https://user-images.githubusercontent.com/25310137/89065672-f6b9b000-d320-11ea-9241-41022b479214.png)

Upon discussion with @chrmarti, I learned `launch.json` has a debug configuration that may have been created when the C# extension was installed locally, and that debug configuration requires the C# extension:

![image](https://user-images.githubusercontent.com/25310137/89066007-8b241280-d321-11ea-8e67-d51c32580145.png)

Perhaps Debug could handle this case better, such as recommending the right extension based on that identifier.

**Comment by chrmarti** [comment]
/fyi @isidorn (since this might otherwise be closed unseen by the feature workflow)

**Comment by isidorn** [comment]
@bamurtaugh debug is not aware of what extension contributes what debug type.

The general solution to this problem could be the following:
When a `launch.json` is opened if we detect that there is a type "coreclr" we recommend the C# extension to the user to install. Same for `python` and other languages...

Let me know if you are interested in looking into this and I can provide some code pointers.

**Comment by bamurtaugh** [comment]
@isidorn Thank you for the insight. That solution sounds interesting since the current error prompts users to open `launch.json`, so recommending the appropriate extension when `launch.json` is opened could work.

I would be interested in looking into this- if you'd like to follow-up here or offline, any code pointers would be great.

**Comment by isidorn** [comment]
Upon further pondering, here's how I think this could work.

Code pointer https://github.com/microsoft/vscode/blob/1cba068f10d5175c286f43aa6ad33985aee39abd/src/vs/workbench/contrib/debug/browser/debugService.ts#L431

This is the error when the debug type is not supported.
In the `showError` call you can pass additional actions, and one of the actions which you should pass would be "Install Debug Extension" which would simply open the extensions view and filter by `tag:debuggers @sort:installs`. Same as "Run > Install Additional Debuggers" does. Code poitner for that action just as inspiration https://github.com/microsoft/vscode/blob/1cba068f10d5175c286f43aa6ad33985aee39abd/src/vs/workbench/contrib/debug/browser/debugCommands.ts#L486

We do not want to hard code an exact list into our source code that coreclr should be handeld by C# extension since then we would have to manage that list. I think the approach that I propose is general enough and might help users.
Let me know what you think, and feel free to create a PR and I can provide more feedback if needed. Thanks

**Comment by bamurtaugh** [comment]
I appreciate the great insights and code pointers @isidorn! I believe a button to prompt users to view and install debug extensions they are missing would be a positive step. It makes sense we wouldn't want to maintain a hard coded list of certain extensions and rather keep it more general.

I have created a PR with your approach in mind, and it would be great to get your feedback: https://github.com/microsoft/vscode/pull/103891.

**Comment by isidorn** [comment]
Adding label verification-needed so we verify this during the endgame.
Thanks!
