### ISSUE TITLE
Windows always shows "failed to delete using recycle" on latest insiders

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#103875]
```
Version: 1.48.0-insider (user setup)
Commit: 5696babbc1dce41788bae04b1a04ad35140bebfb
Date: 2020-08-03T05:51:31.732Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
```

Steps to Reproduce:

1. Delete a file or folder
2. The prompt "failed to delete" shows every time, though it seems the deletion actually worked

Video: https://memes.peet.io/img/20-08-b5421be8-57e3-482a-8f8c-a73b70b8dd1a.webm

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
I just tried this out and it works just fine for me, both on windows and on macOS with latest insiders.
Since we did not make any changes in the explorer, and this feels like it is coming from Electron I am also assigning to @deepak1556 to see if he can reproduce and if he is aware of any electron regression in this area.

**Comment by JDWilson1980** [comment]
Cornell.law.com

Play(Watson.captive.365)
AI(mirror.builds.co)
Host(Groupon.opp.security)

**Comment by connor4312** [comment]
I wonder if this is a duplicate of https://github.com/microsoft/vscode/issues/103820 -- it doesn't mention context menus but deleting twice would cause this. I can't repro on today's insiders, where I could consistently do so before.
