### ISSUE TITLE
Ctrl+Space does not work on macOS 11 Big Sur

### ISSUE THREAD

**Issue by Kjens93** [microsoft/vscode#103855]
Issue Type: <b>Bug</b>

- Launch vscode
- Open a `*.ts` or `*.tsx` file
- Place your cursor anywhere code completion would be available
- Press `Ctrl+Space`
  - Expected: IntelliSense popover should appear
  - Actual: Nothing happens
- Press `Option+Esc`
  - Expected: IntelliSense popover should appear
  - Actual: IntelliSense popover appears as expected

VS Code version: Code - Insiders 1.48.0-insider (5696babbc1dce41788bae04b1a04ad35140bebfb, 2020-08-03T05:41:11.473Z)
OS version: Darwin x64 20.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.59GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.15.1
prettier-vscode|esb|5.1.3
auto-close-tag|for|0.5.8
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.4
shell-format|fox|7.0.1
vscode-github-actions|me-|3.0.1
vscode-docker|ms-|1.4.1
debugger-for-chrome|msj|4.12.9
vscode-xml|red|0.13.0
vscode-yaml|red|0.9.1
code-settings-sync|Sha|3.4.3

</details>

**Comment by nathanjohnson320** [comment]
Hi @Kjens93 I had this problem in catalina as well and stumbled on a reddit post for a fix but can't find it right now.

The issue is that the "change input source" keyboard shortcut is getting enabled and it is bound to Ctrl+Space

To disable it:
1.  Go to system preferences -> keyboard -> input sources
2. add a new input source (I did english ABC)
3. Go to shortcuts tab (inside of keyboard settings)
4. Click on input sources on the left
5. disable the "select previous input source" shortcut

You might have to restart vs code/your computer to get it to take effect. I think you can also delete the input source you create in step 2.

**Comment by gabrielscr** [comment]
@nathanjohnson320 thank you, works for me
