### ISSUE TITLE
UX improvement for find decoration for line starts

### ISSUE THREAD

**Issue by penetrater** [microsoft/vscode#103809]
- VSCode Version:1.47.3
- OS Version:win10 1909

![regex](https://user-images.githubusercontent.com/50835399/89142549-4e9f2380-d57a-11ea-83d4-a0f866ee2b50.png)

Steps to Reproduce:

1.Who is wrong with this regular expression?
2.

Does this issue occur when all extensions are disabled?: No

**Comment by roblourens** [comment]
I think the problem is that you are using `*`, not `+`, so it matches the start of the line and 0 characters. You can notice that we highlight the first character for a 0-width match if you just search with `^`. I don't know whether we'd consider it a bug or just a quirk. But you will get the result you want with `+`.

**Comment by penetrater** [comment]
yes，using ‘+’，There is no problem.
sorry，My mistake.
I didn't understand the meaning of "*".
