### ISSUE TITLE
Save All Not Working

### ISSUE THREAD

**Issue by MatthewJRoybal** [microsoft/vscode#103879]
- VSCode Version: 1.47.3
- OS Version: Windows 10 Professional 64x - All Windows Updates

Steps to Reproduce:

1. Alter 2 files which then need saving (preferably at the same time)
2. Use the shortcut "Control + K S" for Save All

Does this issue occur when all extensions are disabled?: Yes/No
Yes

I have disabled all extensions and I am holding down control, then hitting K S as indicated. As a result, the keyboard shortcuts shows up showing that combination for save all. No files are saved. "Save All" is not greyed out.

I'm happy to provide any further documentation if needed. Thank you for assistance.

**Comment by bpasero** [comment]
I cannot reproduce, but you need to let go of Control before pressing S. Does that work?

**Comment by jimjja** [comment]
I am having the same issue. 

When I edit any file in my project and when I try to save it using Cmd + S, it still shows on the top bar as not saved but it actually saves the file.
When I try to close it, it asks me if I want to save the changes I made to that file. 
If I press save on the prompt it still doesn't do it and it doesnt close the file. I need to press Don't save in order to close the file.

- VS Code:
Version: 1.47.3
Commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e
- OS Version - macOS Catalina 10.15.4 (19E287)

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by MatthewJRoybal** [comment]
> I cannot reproduce, but you need to let go of Control before pressing S. Does that work?

Yes, that worked. I apologize. I didn't realize the "S" had to be hit separate from "Ctrl + K". 

Issue resolved for me. I appreciate the help!
