### ISSUE TITLE
Pressing Cmd-F overwrites find text even if nothing is selected.

### ISSUE THREAD

**Issue by edmundmk** [Microsoft/vscode#10386]
- VSCode Version: 1.4.0
- OS Version: OSX 10.11.6

Steps to Reproduce:
1. Enter some find text.
2. Press enter.
3. Edit the text in the document.
4. Press Cmd-F to repeat the search.
5. Notice that the text in the find box has been replaced with the word the cursor is over.

This is really annoying when doing repeated find-edit cycles.

**Comment by ramamurthynagaraj** [comment]
Hi guys, created a PR for this issue. Let me know if there are any issues.

**Comment by alexandrudima** [comment]
@edmundmk Rather than jumping and changing the seeding behaviour of `ctrl+f`, I am wondering if in step 4 for you , `f3` would be a more suitable shortcut. If you want to repeat the search, `f3` will take you to the next search hit without even losing focus in the editor.

**Comment by alexandrudima** [comment]
@edmundmk Here I am using `F3`. Is this the sort of thing you are trying to do?

![f3](https://cloud.githubusercontent.com/assets/5047891/18068914/0f927e54-6e44-11e6-85b2-dac0a1f3b9b0.gif)

**Comment by ramamurthynagaraj** [comment]
@alexandrudima I was taking sublime as a reference. The seeding doesn't happen even with the first cmd+f. Both vscode and sublime has cmd+d to seed the current focused word, which can suit your fav https://github.com/Microsoft/vscode/pull/10969#issuecomment-243269090 use case.

I think find next/previous shortcut should suffice @edmundmk use case.
I personally use cmd+f to bring the focus to find widget to make further refinements in the find text. Any thoughts on this?

**Comment by alexandrudima** [comment]
@ramamurthynagaraj That is a fair point. Maybe we can change the behaviour to the following:

Seed the search string on ctrl+f if:
* the search string is empty (what you have in PR #10969)
* [or] if the editor has selected text which is not a find match.

The rationale:
* if the editor has no selected text (collapsed cursor) then the search text does not get overwritten
* if the editor has selected text:
 * it could be that the find widget selected that text (imagine searching for `\w+` in regex mode). If the selection is a find match, then the contents of the selection should not be used to seed the search text
 * otherwise, it is very likely that the selection was "manually"/"intentionally" created and is a good indicator that it can be used to seed the search text.

**Comment by ramamurthynagaraj** [comment]
@alexandrudima I think your proposed behaviour is better. 
Let me see if I could implement the second point.

**Comment by ramamurthynagaraj** [comment]
@alexandrudima Created a new PR incorporating your suggestion. Please let me know if there are any issues.
Also was trying to add tests at `findController.test.ts`. It doesn't seem to be running with `./scripts/test.sh`. How do we run those tests?

**Comment by rebornix** [comment]
Dup of https://github.com/Microsoft/vscode/issues/20768 and we already added an option for seedSearchStringFromSelection.
