### ISSUE TITLE
Issues with toolbar overflow menus with actions that depend on focus context

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#103926]
Testing #103887

I opened the README.md markdown file from this repository https://github.com/microsoft/vscode-languageserver-node.git in the Markdown Notebook editor

Steps:

- put a MD cell into edit mode
- click the ... action. 

Observe: the menu doesn't stay open

![cast](https://user-images.githubusercontent.com/1931590/89275650-d5b7ce80-d642-11ea-861d-11fe90be5624.gif)

**Comment by roblourens** [comment]
@sbatten is this supposed to work without disturbing focus now? Or does that only work for context menus? I think this is the same problem though

**Comment by roblourens** [comment]
I think we can also track the dropdown visibility and avoid calling setActions?

**Comment by roblourens** [comment]
Actually would it make sense for any toolbar to defer doing the work in `setActions` until its dropdown becomes not visible? Or is it good for setActions to always close the dropdown so the user is not looking at a stale menu?

**Comment by roblourens** [comment]
This problem exists outside of notebooks, for example, create an extension with this menu contribution

```json
"editor/title": [
	{
		"command": "extension.helloWorld",
		"when": "inputFocus"
	}
],
```

And run it on Windows or Linux, and you will see the same flashing. It makes sense to kill the active menu when the context changes, because you don't want to pick an action which is no longer valid, so we should not hack around it like what I said above. Really we need to keep synthetic focus in the editor when the menu is activated but I don't know how to track that. cc @joaomoreno @sbatten

**Comment by roblourens** [comment]
I pushed a workaround so this will be usable for now

**Comment by sbatten** [comment]
@roblourens is the toolbar considered having the input still focused? or is mac preventing focus on click of the toolbar? I know the menu will steal focus in the custom case but not native, but if mac is working, somehow the ... item itself also does not take focus. Is that correct?

**Comment by roblourens** [comment]
Yeah, when I click a toolbar item (the dropdown or any other) the actual `document.activeElement` does not change

**Comment by sbatten** [comment]
living with notebook workaround for now
