### ISSUE TITLE
Web smoke test failure - verifies settings

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#103949]
Testing #103819

 _1) VSCode Smoke Tests (Web)
       VSCode Smoke Tests (Web)
         Language Features
           verifies settings:
     Error: Timeout: get element '.view-overlays .cdr.squiggly-error' after 20 seconds.
      at D:\Source\github\microsoft\vscode\test\automation\out\code.js:182:23
      at Generator.next (<anonymous>)
      at fulfilled (D:\Source\github\microsoft\vscode\test\automation\out\code.js:9:58)_

**Comment by aeschli** [comment]
@lszomoru What was the exact command line you used to run the smoke test?

**Comment by joaomoreno** [comment]
@lszomoru Please double check this, since I believe the issue doesn't happen if you skip the notebook tests altogether. Simply replace `describe` with `describe.skip` here: https://github.com/microsoft/vscode/blob/f3e4ff91969764238cedeeaa56ba13305d0f5838/test/smoke/src/areas/notebook/notebook.test.ts#L15-L15 And recompile the smoketests with `yarn --cwd test/smoke`.

**Comment by lszomoru** [comment]
@joaomoreno, I am able to reproduce this failure even after commenting out all the notebook tests.

**Comment by aeschli** [comment]
I also have it reproducible on my machine, although I believe it's a timing issue. No configuration event is triggered here after the settings file is updated.
