### ISSUE TITLE
Not sure what is clearSessionPreference option does

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#104080]
Testing #103871

I am sorry that I have no clue what is this parameter is for, hence creating the issue. 

```ts
/**
 * Whether the existing user session preference should be cleared. Set to allow the user to switch accounts.
 * Defaults to false.
 */
clearSessionPreference?: boolean;
```

I tried to use it in GitHub sample but not sure what is happening when I set this parameter. 

```ts
const session = await vscode.authentication.getSession(GITHUB_AUTH_PROVIDER_ID, SCOPES, { clearSessionPreference: true });
```

Does this clear current session and creates new session?

**Comment by RMacfarlane** [comment]
Ah, yeah, this is confusing especially with GitHub because it doesn't change anything there.

The GitHub auth provider only supports being signed into one account at a time, but you can be signed into many Microsoft accounts at at time. If you call getSession for the first time and there are matching sessions, a quickpick is shown asking if you want to use one of those accounts, or sign into a different account. The preference for that session is stored for that extension, so it keeps getting back that account on subsequent calls to `getSession`. This flag is meant to provide a way for an extension to expose a "switch account" sort of command, otherwise the user will never be able to use a different account with that extension.

I'll add more information in the comment

I'll update the docs

**Comment by sandy081** [comment]
Thanks for explanation.
