### ISSUE TITLE
Settings Sync notification wording

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#104055]
Testing #103613

After turning on Settings sync, I get this notification:

<img width="1204" alt="2020-08-05_13-11-52" src="https://user-images.githubusercontent.com/1898161/89406338-4df2c280-d71d-11ea-90dd-9da9c03ba065.png">

Two issues:
- the embedded link "(details)" does not show details (e.g. what is being synched), but it shows the sync log. I suggest to rename the link to what it actually does, e.g. "show sync log" or "show sync status".
- don't break the flow of the notification message by placing "(details)" inside the message. Place the link at the end: "Settings Sync is turned on (show sync log)."

**Comment by sandy081** [comment]
Link is placed inside the message because while sync is being turned on, the message gets updated. In order to have the link at consistent location and not jumping it is placed at a location where it will not change. Please see the following gif

![Kapture 2020-06-20 at 1 03 58](https://user-images.githubusercontent.com/10746682/85185071-b03d5400-b292-11ea-9e9d-f5efcf815fbc.gif)

Remote set ups also use details link, clicking on it shows terminal. It is picked from there. How about renaming `details` to `log` ?

**Comment by sandy081** [comment]
Changed `details` to `show log` to make it obvious.
