### ISSUE TITLE
View should be shown when it is the only view in the view container even if default is hidden

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#104063]
Testing #103833

Even if view's default state is hidden, it should be shown when it is the only view in the view container.

<img width="1078" alt="image" src="https://user-images.githubusercontent.com/10746682/89418252-1b05fa00-d730-11ea-9fed-0f3b7f6d174b.png">

**Comment by alexr00** [comment]
@sandy081 I thought that the check for if the view container is empty should be [here](https://github.com/Microsoft/vscode/blob/648e55967fcc6b2e04ca4593bc2434dba5f4a74c/src/vs/workbench/services/views/common/viewContainerModel.ts#L111-L111); however, it seems that `updateWorkspaceState` can be called more than once, so I could end up showing a view because not all of the view descriptors have been set yet. Do you have an idea for where I should check if the view container is empty?

**Comment by sandy081** [comment]
Yeah this is tricky. we have to wait until all views are registered and check if there is just one active view and is hidden. 

Probably it is consistent the way it is right now. This can also happen when user hides the view manually and we do not force to make a view visible. 

So I am fine calling this won't fix.

**Comment by alexr00** [comment]
Thanks for the details, will mark as won't fix.
