### ISSUE TITLE
Respect "editor.parameterHints.enabled" and don't show parameter hint on "*.suggest.completeFunctionCalls"

### ISSUE THREAD

**Issue by svipas** [microsoft/vscode#104059]
- VSCode Version: 1.47.3
- OS Version: macOS

Steps to Reproduce:

1. Add `"editor.parameterHints.enabled": false` and `"javascript.suggest.completeFunctionCalls": true` to your settings.
2. Open JavaScript file and write `console.log`, press Tab to autocomplete. Actual behavior, parameter hints are visible even though config is false. Expected behavior, parameter hints are invisible.

/cc @mjbvz

**Comment by svipas** [comment]
Same happens for TypeScript.

**Comment by andrew-maust** [comment]
Should the box not display at all or should "...data: any[]" just not show in case of testing it with console.log?

**Comment by andrew-maust** [comment]
Hi @mjbvz I am currently attempting  to work on this issue and I have a quick question. With "editor.parameterHints.enabled" set to false and "*.suggest.completeFunctionCalls" set to true is the expected behavior to have the parentheses still be inserted but just not have the popup appear or should the parentheses not be inserted?

**Comment by svipas** [comment]
@andrew-maust You just need to disable parameter hints. The problem is they appear even if they are disabled.

Imagine this pseudo code:

```js
if (config.parameterHints) { // bool
  showPopup();
} else {
  // do nothing
}
```

**Comment by andrew-maust** [comment]
I know I fixed it. Im gonna submit a PR now.
