### ISSUE TITLE
Debugging extensionhost tests fail in latest Insiders

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#104004]
Steps to Reproduce:

1. Open the test sample https://github.com/microsoft/vscode-extension-samples/tree/master/helloworld-test-sample
2. Try to "Run Extension Tests"
3. The window opens, and immediately closes. VS Code is orphaned in a debugging state until you manually stop it.

Happens using both js-debug and node-debug

Does this issue occur when all extensions are disabled?: N/A

**Comment by weinand** [comment]
@isidorn Other than adding the stopDebugging API I haven't changed anything in VS Code. Could you please do a bisect for finding the regression. Thanks.

**Comment by weinand** [comment]
I cannot reproduce this on macOS...

**Comment by weinand** [comment]
@connor4312 I cannot reproduce on macOS and Windows.
Does problem reproduce after reboot?

**Comment by connor4312** [comment]
I can repro this on OSX and Windows, but discovered this is _only_ when the web worker extension host is enabled https://memes.peet.io/img/789e74f2-1925-48c6-932a-b95df459048f.mp4

cc @alexdima 

Removing `important` since this won't affect end users yet

**Comment by weinand** [comment]
@connor great find.

**Comment by connor4312** [comment]
I forgot about this issue and hit it again today until I realized what was happening 🤦 This is not related to debugging, since it also happens when I run my tests from the command line.

**Comment by aeschli** [comment]
@alexdima I ran into this yesterday and spend a lot of time on this not realizing that I had webWorker EH on, synced to all my machines.
As discussed the other day, instead of "extensions.webWorker" being a setting it should be a command line option. That way it can be defined in launch configs and will result in a nicer development experience.

**Comment by weinand** [comment]
I fully agree. Ran into the same issue...
My current solution to avoid having "extensions.webWorker" spread like a virus is to define it as a workspace setting.

**Comment by alexdima** [comment]
The problem is that we have two distinct extension hosts (the nodejs and the web worker one), and they both believe they are solely responsible for running extension tests.

In this case, the web worker extension host begins executing, attempts to load the `extensionTestsLocationURI`, which throws since it doesn't run correctly in a web worker, so it communicates to the main thread that it finished with running the extension tests and that it should exit with a certain exit code. In the meantime, the nodejs extension host also loads the same `extensionTestsLocationURI` and proceeds executing the tests. But the renderer process exits on the first call to exit, which comes from the web worker extension host.

So it appears that [the check](https://github.com/microsoft/vscode/blob/532ba43c78c82b24bdf94f9edde30cdf9b9bfa12/src/vs/workbench/api/common/extHostExtensionService.ts#L534-L536) introduced via https://github.com/microsoft/vscode/commit/14f25a610224cea1b7fc97da63ad2304951f60a5 from @aeschli is not sufficient anymore, since both extension hosts see that there is an extension test to execute on the `file:` protocol:
```
if (!(extensionDevelopmentLocationURI && extensionTestsLocationURI && extensionTestsLocationURI.scheme === Schemas.file)) {
	return Promise.resolve(undefined);
}
```

**Comment by connor4312** [comment]
thank you ❤️
