### ISSUE TITLE
Disabling/Enabling extension that requires reload does not full sync automatically

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#104079]
Testing #103613

- enable settings sync (including extension sync)
- enable/disable an extension that requires a reload
- reload
- go to other VS Code instance and force settings sync manually

Observe:
extension is not yet in the same state as on the first VS Code instance because a reload is required.

It would be be nice if a notification would pop up in this case.

**Comment by sandy081** [comment]
@weinand Not sure about the notification you mean. When you go to second machine/instance sync gets kicked off and extension gets disabled (for eg.,). Since it happens behind the scenes are you suggesting to show a notification that inform user that some extensions are disabled by sync and needs reload for the change to have affect?

**Comment by weinand** [comment]
@sandy081 yes, exactly what you explain.
Users probably expect that settings sync takes care of everything and assume that an enabled or disabled extension will be enabled or disabled in the other VS Code instance automatically. But this is not the case.

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/69620 - This is also similar - how to notify user about background updates to an extension.
