### ISSUE TITLE
Notebook Kernel can not be identified by `id`

### ISSUE THREAD

**Issue by sana-ajani** [microsoft/vscode#104015]
Testing #103883 

Is it possible to have the currently active, preferred kernel also show up as the first one or the highlighted one in the quick pick? 

![recording (3)](https://user-images.githubusercontent.com/9721254/89354941-f9910980-d66e-11ea-84df-cf7345005fc8.gif)

**Comment by RMacfarlane** [comment]
When I change the kernel provider to a placeholder one from my sample extension, it doesn't seem to get highlighted in the quick pick:
<img width="712" alt="Screen Shot 2020-08-10 at 11 58 03 AM" src="https://user-images.githubusercontent.com/3672607/89819832-e06dda00-db00-11ea-850a-cc2d2e246885.png">

Here's the code I added in `extension.ts` in the sample renderer:
```
export class TestKernel implements vscode.NotebookKernel {

  constructor(public label: string) {}
  executeCell = () => {};
  cancelCellExecution = () => {};
  executeAllCells = () => {};
  cancelAllCellsExecution = () => {};

}
export class KernelProvider implements vscode.NotebookKernelProvider<TestKernel> {
  provideKernels() {
    const provider1 = new TestKernel('provider1');
    const provider2 = new TestKernel('provider2');

    return Promise.resolve([provider1, provider2]);
  }
}
// This method is called when your extension is activated
// your extension is activated the very first time the command is executed
export function activate(context: vscode.ExtensionContext) {
  
  context.subscriptions.push(
    vscode.notebook.registerNotebookContentProvider(
      'test-notebook-renderer', new TestProvider()
    ),
  );
  
  const provider = new KernelProvider();
  vscode.notebook.registerNotebookKernelProvider({ filenamePattern: '**/*' }, provider);
  
}
```

**Comment by rebornix** [comment]
When users click the kernel status bar item, we will fetch the latest kernels from kernel provider again, and in the snippet @RMacfarlane posted above

```
export class KernelProvider implements vscode.NotebookKernelProvider<TestKernel> {
  provideKernels() {
    const provider1 = new TestKernel('provider1');
    const provider2 = new TestKernel('provider2');

    return Promise.resolve([provider1, provider2]);
  }
}
```

Every time the kernel provider returns two new objects with the same labels but since we only use object identifiers to check if the kernels are identical or not, none of the kernels listed in the quick is selected as they are different from the active kernel.

For example, if we always return same kernels in `providerKernels`, you can see the kernel is selected as expected.

```
export class KernelProvider implements vscode.NotebookKernelProvider<TestKernel> {
	provider1 = new TestKernel('provider1');
	provider2 = new TestKernel('provider2');
	provideKernels() {

		return Promise.resolve([this.provider1, this.provider2]);
	}
}
```

Removing `bug` label for now. We may want to enforce the kernel provider to provider `id`.

**Comment by jrieken** [comment]
This has happened. The new `NotebookController` API enforces the use of unique identifiers
