### ISSUE TITLE
Save cursor location when editor.action.selectAll (Ctrl+a)

### ISSUE THREAD

**Issue by pablospe** [microsoft/vscode#104069]
When `<Ctrl+a>` is pressed (`editor.action.selectAll`) the cursor goes to the end of the file. I would expect to return to the previous position if the selection is cancelled with `<ESC>`.

As an example, let's say you are in the middle of file, if you want to select all (and copy it) but later continue where you left, by pressing `<ESC>` the selection disappear but the cursor will be at the end of the file. I would expect the following behavior: `<Ctrl+A>` (select All), `<Ctrl+C>` (Copy), `<ESC>` and continue where I left.

Also it should be consistent with the `Up/Down/Left/Right` keys (and the rest of the navigation keys).

Can the position of the cursor be on the middle of a selection, instead of only at the beginning/end?

**Comment by alexdima** [comment]
There is a special action, `Cursor Undo` (I believe bound to `ctrl+u` on Windows by default) which undoes the last cursor operation (up to the last edit), so you can use `ctrl+a`, `ctrl+c`, and `ctrl+u`. `Cursor Undo` is a helpful command to know about, since it works the same in all cases, not just for `ctrl+a`. For example, I use it a lot in combination with `ctrl+d` if I go one too many words, etc.

**Comment by pablospe** [comment]
thanks for the recomendation!
