### ISSUE TITLE
Middle mouse button scrolling not working

### ISSUE THREAD

**Issue by csicky** [microsoft/vscode#104183]
- VSCode Version: 1.47.3
- OS Version: Windows 10

Steps to Reproduce:

1. Click with the scroll wheel in the code editor
2. Drag the mouse

Expected outcome: window scrolls
What happens instead: some kind of unnecessary highlighting

Does this issue occur when all extensions are disabled?: Yes

If you notice some familiarity with this issue, is because there is a neglected issue opened 4(FOUR) years ago without any attempt at fixing. And before stamping feature request on this, it is a BUG.

**Comment by csicky** [comment]
It is a bug not a feature request.

**Comment by gillminister** [comment]
@vscode-triage-bot here's a screen recording, in case anyone is genuinely confused

![recording](https://user-images.githubusercontent.com/1084957/89873037-2175f500-dbba-11ea-8993-c21b79c66669.gif)

**Comment by trbot86** [comment]
Voted (immediately as soon as this post was created)... This would be very helpful to me...

**Comment by SetTrend** [comment]
We have more than 20 upvotes on this issue now. Just like with [this issue](58038).

What is the further process of this improvement request? Is the "20 upvotes limit" just a mirage?

**Comment by BihtSift** [comment]
FWIW, I wouldn't call this a bug.  It's definitely a feature request.  The current functionality appears to be modeled after Sublime's multi-line selection (this is different than "block selection") which shouldn't be removed.

Even visual studio doesn't have middle mouse scrolling out of the box (many extensions add this feature).

What I recommend is an option for the middle mouse behavior (multi-select being default).  Since there is a keyboard shortcut for multi-line select, users like myself can get the best of both worlds.

**Comment by csicky** [comment]
Imagine there is a software which decides to do the click on right button and right click on left button of the mouse. It is not a "bug", it is a decision of the software makers. What would people do? Open bug reports. Mouse does not behave as expected. 

A standard mouse has left button for click, right button for right click, and a scroll wheel for scrolling. The scroll wheel when pressed is the middle button. Middle button's standard use is auto scrolling.

We can argue that it is not a bug, it is a decision of developers to hijack the middle button for something else, but in that case the only sensible thing to do is to provide a checkbox to let it work as expected. The middle button was already doing something (auto scroll) before VS Code just hijacked it without notifying users about it.

**Comment by BihtSift** [comment]
Agreed, the point really isn't weather it's a bug or not.  I'm only pointing out that middle mouse scroll is something that isn't always implemented.  It's a feature that originated with web browsers, and many other applications have followed suit (it's not native to the Win32 API and your app doesn't automatically have the functionality).  Many apps don't scroll on middle click:
* Visual studio
* Many source control IDEs (Perforce P4V, Git extensions, etc.)
* Notepad++
* Sublime Text
* Windows Explorer
* etc. - the list is quite large

My main point is that the implementer should consider making it an option, since column select is a useful feature which I use all the time for multi-edit.

**Comment by fireattack** [comment]
With autoscroll, you can click (not hold) middle button and then drag. So it (at least this part) won't be conflicted with column select. 

Of course, we still should have (and probably will get) options if it's ever going to be added.

**Comment by BihtSift** [comment]
That's a great point.  Most implementations have both states, but there's no reason VSCode *needs* to have the drag functionality allowing both functions (though it might feel weird).

I noticed that the extensions browser in VSCode *does* already have the middle mouse scroll functionality, but I'm unsure if it's because that view is actually some sort of 3rdparty web view or if it's actually implemented that way (I didn't get that far looking into it).

**Comment by qooqu** [comment]
Here's an autohotkey workaround:
https://github.com/qooqu/vs-code-mbutton-scroll-ahk

**Comment by ScallyGames** [comment]
With Lenovo Thinkpads on Windows there is a setting whether the middle mouse button should emulate scroll or do an actual middle mouse button input.

With it set to scrolling vscode scrolls properly with middle mouse button. However that breaks a lot of features in other applications, i.e. closing tabs in a browser with middle mouse click.
With it set to middle click, I cannot scroll in vscode using it.

It's a big problem for my workflow having to decide through a system-wide configuration whether I'd prefer scrolling in vscode or closing tabs in my browser / other applications.

**Comment by Tirbo06** [comment]
Duplicates also of #129986 from Aug 2, 2021 and if I remember well everything was working fine before the last update of this period... @vscode-triage-bot is there any update on this bug ? I do not really understand why a necessary functionality that used to work take some much time for you to re-activate... please do something @microsoft

**Comment by hediet** [comment]
Closing as duplicate of #6302, the bot failed.

**Comment by csicky** [comment]
@hediet now that you closed this, the issue from 2016 will get the proper attention? So that is why this was not fixed until now, too many open tickets :D

![image](https://user-images.githubusercontent.com/3931907/179249777-00a7e2cd-6e00-4515-a970-3e1f36eac8d4.png)
