### ISSUE TITLE
API to Open Quick Pick pre-filled

### ISSUE THREAD

**Issue by gfrancischini** [Microsoft/vscode#10413]
Hi,

Would be possible to add the quick pick (ctrl + p) as a extension point?

My requirement is a function similar to Visual Studio (ctrl + ,) where you select a text and press c+, and Visual Studio filters the available file that has the file name = to the selected text

**Comment by jrieken** [comment]
@gfrancischini I assume you want the filter text to be set, right?

**Comment by gfrancischini** [comment]
@jrieken Yes, something like this

[Gif showing the concept](https://giphy.com/gifs/l0HlCqkgAfKWGt0Y0)

**Comment by ColCh** [comment]
Same functionality in atom: https://github.com/atom/fuzzy-finder/pull/314

**Comment by bpasero** [comment]
@ColCh I am not sure your PR addresses this issue where I believe @gfrancischini wants API so that from an extension the text in quick open can be set. However, if the only use case is to take the editor selection and fill it into quick open, then maybe we should rename this issue and the PR would address it.

**Comment by ColCh** [comment]
@bpasero oh really, didn't noticed that at first. I think I will rotate to new issue

**Comment by bpasero** [comment]
@gfrancischini this is already possible, here is an example where quick open uses the selection of the editor to prefill:

`vscode.commands.executeCommand('workbench.action.quickOpen', vscode.window.activeTextEditor.document.getText(vscode.window.activeTextEditor.selection));`
