### ISSUE TITLE
Cannot open file from explorer under admin mode

### ISSUE THREAD

**Issue by torwa** [microsoft/vscode#104165]
Issue Type: <b>Bug</b>

When VSCode is running under admin mode, nothing happens when either right-clicking on the icon on taskbar then creating a new window, or right-clicking on a file in explorer then selecting "Open with Visual Studio Code"

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.18363

**Comment by lszomoru** [comment]
As far as I am aware this behavior is by design - you can only have one window when running in `admin mode`. Having said that, there seems to be a regression as I tend to remember that when trying to open a second window when running in `admin mode` there was an error dialog. You can still hear the "error sound" but the dialog does not appear.

**Comment by bpasero** [comment]
@lszomoru yeah good finding, let's track that particular issue here: https://github.com/microsoft/vscode/issues/104493
