### ISSUE TITLE
Debug: Compound - Python / Attach C Process doesn't work

### ISSUE THREAD

**Issue by jay-pee** [microsoft/vscode#104174]
- VSCode Version: 1.48-insder
- OS Version: Windows 10 1990

Steps to Reproduce:
1. Open folder in VS Code
2. Create a new python file: 
```
print("hello world")
```
3. Add launch.json config:
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [

        {
            "name": "C: Attach to Process",
            "type": "cppvsdbg",
            "request": "attach",
            "processId": "${command:pickProcess}",
            "visualizerFile": ""
        },
        {
            "name":"Python: Current File",
            "type":"python",
            "request":"launch",
            "program":"${file}",
            "console":"integratedTerminal",
            "stopOnEntry": true
        },
    ],
    "compounds":
    [
        {
          "name": "C: Current Python File",
          "configurations": ["Python: Current File", "C: Attach to Process"],
        },
    ]
}
```
4. Select the compound launch in the debugger and start it (F5)
5. See the error Message

![image](https://user-images.githubusercontent.com/9380980/89532410-0722cc80-d7f2-11ea-91bb-34967ec63203.png)

When you launch the python and c launch task separately it works:

![image](https://user-images.githubusercontent.com/9380980/89532838-b95a9400-d7f2-11ea-84d6-1222bbbb56ea.png)

**Bonus Feature Request**
A feature would be great to hand over the python process ID so it has not to be selected manually. But it is just a bonus. ;)
Cheers

**Does this issue occur when all extensions are disabled?**
Not possible because you need python and c++ extension

**Comment by weinand** [comment]
I assume that the "pickProcess" command used in the C++ launch config is provided by the C++ extension.
Please file the issue against the C++ extension.

**Comment by jay-pee** [comment]
Anything to say to the "bonus" feature request @weinand

**Comment by weinand** [comment]
The easiest way to get the process ID from the python process is to make the debuggee print its process ID to stdout in some recognisable format (e.g. a URL). VS Code has a feature `serverReadyAction` that can be used to open a URL in a browser as soon as a server ready message appears in the debug console (see https://code.visualstudio.com/updates/v1_32#_automatically-open-a-uri-when-debugging-a-server-program). 

The problem is that in your case you don't want to open a URL in a browser, but you want to start another debug session and pass along the process ID.

The existing syntax of the `serverReadyAction` could be easily extended to support such a feature. The feature is implemented in VS Code as a built-in "debug-server-ready" extension (https://github.com/microsoft/vscode/tree/master/extensions/debug-server-ready). Hack it and give us a PR!

Or clone the `serverReadyAction` extension and adapt it to your needs.
