### ISSUE TITLE
UI progress indicator not clearly visible in the quickpick

### ISSUE THREAD

**Issue by karrtikr** [microsoft/vscode#104107]
UI progress indicator, set using option [Quickpick.busy](https://code.visualstudio.com/api/references/vscode-api#QuickPick%3CT%3E) is not clearly visible, because the filter box border is also blue and in focus.

![image](https://user-images.githubusercontent.com/13199757/89459095-fce2ce80-d71c-11ea-8406-65eeacf90657.png)

If I click somewhere else so that UI looses focus, then it's clear.

![image](https://user-images.githubusercontent.com/13199757/89458279-a0cb7a80-d71b-11ea-82d1-60a441d1f110.png)

Is it possible to move the indicator at the bottom instead, like it's done in other places like the input box.

![image](https://user-images.githubusercontent.com/13199757/89459259-36b3d500-d71d-11ea-91ca-c1c167070fab.png)

**Comment by TylerLeonhardt** [comment]
Two options:

**Option A (progress goes under title bar or at the top if no title bar):**

With a "description"
![image](https://user-images.githubusercontent.com/2644648/111238791-0dadc980-85b5-11eb-944b-de8e12f72c10.png)

With no title
![image](https://user-images.githubusercontent.com/2644648/111238937-61b8ae00-85b5-11eb-8b73-34b6bbe7a8cf.png)

With a title
![image](https://user-images.githubusercontent.com/2644648/111239200-ed323f00-85b5-11eb-9927-3f0dc6875a2c.png)

**Option B (progress is at the very bottom):**

Below a list item
![image](https://user-images.githubusercontent.com/2644648/111238830-274f1100-85b5-11eb-9c1c-5352b5ee7c5b.png)

with no items in list
![image](https://user-images.githubusercontent.com/2644648/111239145-cd9b1680-85b5-11eb-8823-dad377bd03c5.png)

**My thought**

Idk... I kinda like Option A because:
* it'll always be in the same place and
* it's closer to where you're actually typing _and_
* Views follow this concept of progress under titles.

However Option B does sound nice that:
* it's consistent with Input and
* that really what you're saying is "hey we're progressing your list of options" so it's a better association to what you're actually trying to accomplish.

thoughts? (@chrmarti )

**Comment by chrmarti** [comment]
B makes sense to me because it is often the list that is being loaded and having the progress indicator close to it kind of coveys that association. (As you mention.)

**Comment by TylerLeonhardt** [comment]
verification steps:

* create an extension with this API call:

```ts
class MessageItem implements QuickPickItem {

	label: string;
	description = '';
	detail: string;
	
	constructor(public base: Uri, public message: string) {
		this.label = message.replace(/\r?\n/g, ' ');
		this.detail = base.fsPath;
	}
}

const input = window.createQuickPick<MessageItem>();
input.placeholder = 'Type to search for files';
input.ignoreFocusOut = true;
input.items = [
    new MessageItem(Uri.file("C:\\"), "hello"),
    new MessageItem(Uri.file("C:\\"), "foo"),
    new MessageItem(Uri.file("C:\\"), "bar")
];
// this is the important bit
input.busy = true;
input.show();
```
The progress bar should be under the list rather than in the input field
