### ISSUE TITLE
Support shortcuts to paste content from Linux different  X server's selections

### ISSUE THREAD

**Issue by ghost** [Microsoft/vscode#10422]
- VSCode Version: 1.4.0
- OS Version: Fedora 24 (Xfce4 desktop)

In Linux, X server has 3 selections for clipboard: primary, secondary, and clipboard ([wiki](https://wiki.archlinux.org/index.php/Clipboard)).

I think `Ctrl-V` is for clipboard. Some Linux apps offer `Shift-Insert` for primary selection. Would you please consider supporting this? My suggestions:
- `Ctrl-V`: clipboard
- `Shift-Insert`: primary
- `Ctrl-Shift-Insert`: secondary

Thank you,

**Comment by alexandrudima** [comment]
To keep the number of issues in our inbox at a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: we look at the number of votes the issue has received and the number of duplicate issues filed. Thank you for your time and understanding.

If you disagree and feel that this issue is crucial: we're happy to listen and to reconsider.
