### ISSUE TITLE
Experiments service still reaches out to server even when disabling telemetry

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#104293]
From @rob3c, https://github.com/microsoft/vscode/issues/103159#issuecomment-670773789:

> @joaomoreno VSCode Insiders build still connects to `https://default.exp-tas.com/vscode/ab` even when telemetry is disabled. It does this every 30 minutes.
> 
> Here's a sample redacted request/response pair:
> ```
> GET https://default.exp-tas.com/vscode/ab HTTP/1.1
> Host: default.exp-tas.com
> Connection: keep-alive
> X-MSEdge-ClientId: [REDACTED]
> X-VSCode-TargetPopulation: insider
> X-VSCode-Build: Visual Studio Code - Insiders
> User-Agent: [REDACTED]
> X-FD-Corpnet: 
> X-VSCode-AppVersion: 1.48.0-insider
> Accept: application/json, text/plain, */*
> X-VSCode-Language: en
> X-VSCode-ExtensionName: vscode-core
> X-MSEdge-Market: 
> Sec-Fetch-Site: cross-site
> Sec-Fetch-Mode: cors
> Accept-Encoding: gzip, deflate, br
> Accept-Language: en-US
> If-None-Match: [REDACTED]
> ```
> ```
> HTTP/1.1 304 Not Modified
> ETag: [REDACTED]
> X-Content-Type-Options: nosniff
> X-ExP-TrackingId: [REDACTED]
> X-MSEdge-Ref: [REDACTED]
> Access-Control-Allow-Origin: *
> Date: [REDACTED]
> ```

**Comment by joaomoreno** [comment]
Oh silly me. There's actually a separate issue for the experiments service. @rob3c can you still reproduce if you disable `workbench.enableExperiments`?

**Comment by sbatten** [comment]
reopening until PR is merged

**Comment by joaomoreno** [comment]
@sbatten Can you give a summary of what's happening here? Given that you reopened this I take it that the setting exists, but it isn't being respected at all... so it was just a coincidence that @rob3c was poking around here?

**Comment by sbatten** [comment]
I just added the new experiment service this milestone. I was not aware of this setting existing for the old service, but now that I am, it should be respected in the new service as well.

**Comment by isidorn** [comment]
As far as I see there is a PR which is merged on top of the releaser branch that fixed this issue. Thus closing it.
@joaomoreno and @sbatten please reopen if I am mistaken

**Comment by rob3c** [comment]
@joaomoreno Thanks for tracking down the root cause so quickly!

By characterizing my "poking around" as "just a coincidence", are you suggesting that it's acceptable and expected for vscode to still collect and send experiment-related telemetry even when the global `telemetry.*` settings are disabled?

If they're intended to be orthogonal settings, it would be much less suspicious from a privacy perspective if the `workbench.enableExperiments` setting were discoverable when typing `telemetry` in the settings search box instead of seemingly hidden. Currently, the "Workbench: Enable Experiments" description is "Fetches experiments to run from a Microsoft online service", which doesn't directly disclose that it's sending collected user telemetry data as part of the process.

In any case, at least it's possible to disable it along with the other telemetry settings once you know about it 👍

**Comment by sbatten** [comment]
@rob3c If telemetry is disabled, experiments will not work and that is honored. Disabling telemetry effectively disables experiments. However, there was an issue that we would still ask for experiment information (not upload telemetry) if experiments were disabled which is a separate setting to allow users to opt out of experiments without opting out of telemetry.

**Comment by rob3c** [comment]
@sbatten Thanks for clarifying the settings and intentions behind them.

IMO, whether you choose to define the info as telemetry or not, vscode phoning home with info that uniquely identifies my machine is not expected behavior when I have telemetry globally disabled - even if the seemingly-hidden, on-by-default, practically-undiscoverable, not-using-the-telemetry-keyword, un(der)documented setting for disabling experiments is separate for a good reason.

To avoid even the appearance of bad faith on the part of Microsoft, I again suggest having that any any other such settings appear in the settings UI search results when people go looking for how to disable telemetry.

The easiest way seems to be to work it into the `enableExperiments` description, even if it's only to explicitly state it does not enable experiment telemetry. Maybe a (better-worded) version of something like this would work: "when telemetry is disabled globally, only minimal info strictly related to current experiments will be sent to Microsoft".
