### ISSUE TITLE
Debug hover should respect editor font size

### ISSUE THREAD

**Issue by WardenGnaw** [microsoft/vscode#104214]
- OS and Version: Windows 10
- VS Code Version: 1.47.3
- C/C++ Extension Version: 0.29.0
- Other extensions you installed (and if the issue persists after disabling them): none

Try to hover over a C `char[]` array, like:

`char name[] = "Connie";`

The visualizer displays its content using a font that is too small, as shown in the attached screenshot.

This is annoying, for example when recording for screen casts or presentations that require larger font for easier readability.

The best option would be to **allow the user to easily customize the font used by the visualizer** (just like we can customize fonts in other parts of VS Code, like in the text editor).

Or, at least, the font size of the visualizer should be similar to the font size used to display the code in the editor.

![VS_Code_Bug_Visualizer_Font_Small](https://user-images.githubusercontent.com/4692631/89450388-bca24100-d75a-11ea-8683-e3b220fd455c.png)

--------------

By @GiovanniDicanio
From https://github.com/microsoft/vscode-cpptools/issues/5905

**Comment by isidorn** [comment]
I agree that the debug hover should respect the editor font size. And it respects it when hovering over for an example string.
However it does not work when we use the tree, since we have hard coded limitation in CSS for this.

I am open for a PR which fixes this.
Code pointer, I believe the editor font size is already nicely applied here https://github.com/microsoft/vscode/blob/cf4e4c17544486f6442cb91eeb8f1acfc36d1339/src/vs/workbench/contrib/debug/browser/debugHover.ts#L124

However we hard code the font here https://github.com/microsoft/vscode/blob/cf4e4c17544486f6442cb91eeb8f1acfc36d1339/src/vs/workbench/contrib/debug/browser/media/debugHover.css#L25

if the font were dynamic some sizes in the debug hover computation would also need to be changed.

**Comment by lifez** [comment]
I will work on this

**Comment by lifez** [comment]
@isidorn What do you think if we make this work first then we will add new editor config like `debugFontSize` ?

**Comment by isidorn** [comment]
@lifez there should not be a new config, the debug hover should just respect the editor font size. I will comment more in your PR. Thanks

**Comment by GiovanniDicanio** [comment]
@isidorn I think the best would be having a new config like @lifez suggests, that defaults to the editor font size. But users should be allowed to customize that debug hover font if they need to.

**Comment by GiovanniDicanio** [comment]
The [linked pull request](https://github.com/microsoft/vscode/pull/104701) hasn't resolved this issue, and since August 17th more than **two months** have passed. It's disappointing to read this comment in the PR: _"[...] However I tried out this PR and it still does not work. Unfortunetly I will not have more time to invest in this."_
Looks like this issue is abandoned.

**Comment by GiovanniDicanio** [comment]
I'm using VS Code with the C/C++ Extension for some video courses, and to make the text more readable (including visualizer text), it's important to be able to use a larger font. This is why this issue is important to me.

**Comment by zhangjp0405** [comment]
![Image](https://github.com/user-attachments/assets/d68742d6-6d4f-4c45-819c-af0a5b10e8d7)
Why i debug hover char array not show string value? my cpp-tools version is 1.25.0
