### ISSUE TITLE
cmder on vs code

### ISSUE THREAD

**Issue by sPreet247** [microsoft/vscode#104338]
Issue Type: <b>Feature Request</b>

Hi
Unable to integrate cmder with Vs code.

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.18363

**Comment by IllusionMH** [comment]
/needsMoreInfo

What actually you are trying to achieve and what you've tried?

**Comment by sanket-bhalerao** [comment]
is that an option?

**Comment by sPreet247** [comment]
I am trying to integrate Cmder with the Vs Code terminal.
VS Code config used in settings.json:

  "terminal.integrated.shell.windows": "cmd.exe",
  "terminal.integrated.env.windows": {
    "CMDER_ROOT": "C:\\tools\\cmder"
  },
  "terminal.integrated.shellArgs.windows": [
    "/k",
    "%CMDER_ROOT%\\vendor\\bin\\vscode_init.cmd"
  ],

**Comment by IllusionMH** [comment]
Do you have `CMDER_ROOT` in your Windows environment variables (not in `terminal.integrated.env.windows`)?

You need to have `CMDER_ROOT` in your Windows environment variables, because `shell` and `shellArgs` are used to spawn new process and `env` will be available only inside of that process, not during process start. Therefore proper path to `vscode_init.cmd` won't be resolved during start.

/assign @Tyriar 
Please correct me if I'm wrong.

**Comment by Tyriar** [comment]
Instructions for this were updated just the other day to match what is on the cmder site: https://code.visualstudio.com/docs/editor/integrated-terminal#_can-i-use-cmders-shell-with-the-terminal-on-windows

**Comment by sPreet247** [comment]
It works.Thanks
