### ISSUE TITLE
Can't access settings for extensions that don't specify a title for their settings in package.json

### ISSUE THREAD

**Issue by rccoleman** [microsoft/vscode#104442]
Found on versions:

    code-server: v3.4.1
    VS Code: v1.45.1
    Commit: 48f7c2724827e526eeaa6c2c151c520f48a61259
    Date: 2020-06-04T10:39:14Z
    Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36

and

MacOS 10.15.5:

    Version: 1.47.3
    Commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e
    Date: 2020-07-23T13:08:29.692Z
    Electron: 7.3.2
    Chrome: 78.0.3904.130
    Node.js: 12.8.1
    V8: 7.8.279.23-electron.0
    OS: Darwin x64 19.5.0

Steps to Reproduce:

1. Install an extension that doesn't have a "title" for its settings specified in its package.json.  Example: https://github.com/actboy168/vscode-tasks
2. Hit the cog on the extension and select "Extension Settings..."
3. Note that the Settings window comes up with the proper search terms, but no settings are found.
<img width="994" alt="Screen Shot 2020-08-09 at 9 35 12 PM" src="https://user-images.githubusercontent.com/860888/89928187-4c614880-dbbc-11ea-9eac-b08fb9787647.png">
4. Manually add a title for the settings in package.json like this:

        "configuration": {
            "title": "vscode-tasks",
            "properties": {
                "tasks.statusbar.default.hide": {
                    "type": "boolean",
5. Repackage with `vsce package`, install the resulting .vsix
6. Note that the settings search is successful and settings can be viewed and changed.
<img width="999" alt="Screen Shot 2020-08-09 at 9 38 15 PM" src="https://user-images.githubusercontent.com/860888/89928208-571bdd80-dbbc-11ea-8b15-cd966f723d6d.png">

Discussed with developer of that extension and suspect issue in upstream since this used to work in a previous VSCode version (unclear when it broke).  See https://github.com/actboy168/vscode-tasks/issues/22.

Uninstallling and reinstalling the extension from the Marketplace doesn't appear to refresh the package.json in .vscode/extensions/<extension_name>, so once the settings have been given a title, the settings will continue to work properly even when reinstalling.  Deleting the extension directory and reinstalling from the Marketplace will cause the issue to reappear.

**Comment by sandy081** [comment]
@roblourens Seems the search is in Settings UI. So assigning this to you.

**Comment by roblourens** [comment]
@sandy081 i assigned to you because I don't think this has anything to do with search, rather the settings model, since I don't read the 'title' property or prevent settings from showing up when it's missing.

**Comment by roblourens** [comment]
I think this is in the settings UI, nvm.

**Comment by roblourens** [comment]
Actually this is interesting. @rccoleman since your extension has the display name `Tasks`, and no title, we end up folding your extension settings into the builtin "Tasks" category and so they are not associated with your extension. You can work around this by adding a title like you've discovered, but it's not usually necessary.

> doesn't appear to refresh the package.json in .vscode/extensions/<extension_name>

Make sure you quit vscode and restart so the old version is fully uninstalled, if you want to verify by looking at the disk like this.

@sandy081 I don't understand this code in `parseConfig` in preferencesModels.ts that well, do you think this is expected? The displayname of the extension is used rather than extension id or something else, that comes from here: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/common/configurationExtensionPoint.ts#L170 it seems to easy to lose your extension settings group into another group with the same title.

**Comment by sandy081** [comment]
I think this makes sense in the old editor that displaying settings grouped by title. Not sure how settings are grouped in new editor based on that it has to be changed.

**Comment by roblourens** [comment]
Ok. That grouping condition can probably be changed

**Comment by rccoleman** [comment]
Thanks very much for the quick turnaround on this!
