### ISSUE TITLE
SIGINT not sent when hitting Stop button on MacOSX

### ISSUE THREAD

**Issue by zgz682000** [microsoft/vscode#104464]
VSCode version info
```
版本: 1.47.3
提交: 91899dcef7b8110878ea59626991a18c8a6a1b3e
日期: 2020-07-23T13:08:29.692Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.5.0

```

I have a nodejs test code called main.js trying to listen to sigint event like this:
```
setTimeout(() => {
    console.log("xxxx")
}, 5000);

process.on("SIGINT", ()=>{
    console.log("SIGINT")
})
```

and set launch.json like this:
```
{
"version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "启动程序",
            "skipFiles": [
                "<node_internals>/**"
            ],
            "program": "${workspaceFolder}/main.js"
        }
    ]
}
```

When I launch this process, and press Stop button within 5 sec, SIGINT signal will not be received. Terminal logs `Process exited with code null` instead of `Waiting debugger for disconnecting`

**Comment by weinand** [comment]
@connor4312 does js-debug support the `terminate` request?

**Comment by zgz682000** [comment]
I suppose so, just as the offical document says
![image](https://user-images.githubusercontent.com/9474727/90031138-79fade80-dcef-11ea-8a4f-b1ba474ea715.png)

**Comment by connor4312** [comment]
Thanks for the issue, this duplicates https://github.com/microsoft/vscode-js-debug/issues/630. We use SIGKILL (and actually, [so did node-debug2](https://github.com/microsoft/vscode-node-debug2/blob/fa2233b888cd090311d9e4a1e0c191552e1ce001/src/terminateProcess.sh#L7)) rather than SIGINT/TERM at the moment.

/duplicate

**Comment by weinand** [comment]
@zgz682000 "the official document" (which I wrote after adding the `terminate` feature to DAP and implementing it for node-debug) describes the expected behavior of a debug extension that supports the optional `terminate` feature in a fully conforming way.

Whether a debug extension is "fully conforming" cannot be deduced from the existence of the document. Only if the debug extension opts into the feature and implements it like the doc says, we know for sure - that's the reason why I asked...
