### ISSUE TITLE
Creating new tab stack resets line wrap setting

### ISSUE THREAD

**Issue by jasongrout** [Microsoft/vscode#10441]
- VSCode Version: 1.4.0
- OS Version: OS X 10.10.5

Steps to Reproduce:

1. Create a two new files (so there are two tabs), A and B.
2. Toggle the line wrap setting for file A
3. Drag the tab for the file A to create a new tab stack
4. Observe the line wrap setting is reset.

Here is a screencast:

![wrapping](https://cloud.githubusercontent.com/assets/192614/17598780/1ceabb1c-5fca-11e6-97d2-88d2bced1f4b.gif)

**Comment by bpasero** [comment]
We need to apply more of the editor settings that are defined outside of the real settings to the other side.

**Comment by bpasero** [comment]
@alexandrudima would it make sense to put more of these things into the persisted view state I get from the editor?

Here is my problem: You configure the editor with our toggles and then you move the editor to the side to split it. For me it is just like opening a file to the side, I do not know how the editor was configured (e.g. showing whitespace characters), so it opens without these options applied.

I could look for editor options like those and reapply them but this is fragile when we add more toggles. Today, e.g. the state of expanded/collapsed regions also goes into the view state and restores transparently for me without further knowledge.

If we move more into view state this would actually also allow to set these options on specific files and get these options back when you open the file again after restart 👍

**Comment by alexandrudima** [comment]
@bpasero I am not sure where these "ephemeral" settings should live. I am also not sure if it is OK that today they apply to the focused/active editor only. If they would apply to all editors, then we could centrally manage them for all editor instances...

We can also make them serialized with the view state, but then wouldn't the uri <-> viewstate mapping bite us back?

**Comment by bpasero** [comment]
Not sure applying them to all editors would make sense, if I want to quickly toggle word wrap for the current editor, I would probably not expect it to change it for any other editor.

Today view state is stored per URI + column so that multiple editors of the same resource can have different view state. In this case I would not use this mechanism though but purely ask the source editor for its view state and apply it to the target editor. I already do this for restoring the view state when you move an editor to the side because I need it there already. 

So having this inside viewstate should be OK for this issue as well as restoring the state when you restart for the current editor in the column it is inside.
