### ISSUE TITLE
file are not sorted in ascending order for numeric file name

### ISSUE THREAD

**Issue by rajeevbarde** [microsoft/vscode#104555]
- VSCode Version: 1.47.3
- OS Version: Windows 10 v2004 

On VS Explorer, the file is not sorted in ascending order as shown below, (compared with Window Explorer)
![image](https://user-images.githubusercontent.com/6995156/90131510-e2969980-dd89-11ea-975c-066d77bc7de7.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
We are fine tuning our sorting.
I believe we have not covered this case. Thus assigning to Backlog and we might tackle in the future.

fyi @leilapearson

**Comment by leilapearson** [comment]
Thanks for the report @rajeevbarde

Yes, unfortunately numbers with a decimal separator will not always sort numerically. This is expected.

There are two things at play here:

  1. We're using a standard javascript localeCompare() with numeric sorting enabled, which essentially works by ignoring leading zeros when comparing number segments. That means that 1 < 02 < 003 (good) and 1.1 < 1.02 < 1.003 (_maybe_ not good) 

  2. We're disambiguating equivalent numbers (same number but different number of leading zeros) by length - and putting the shorter numbers first - so `1 < 01 < 001` and `1.1 < 1.01 < 1.001`. 

(1) is tricky. The reason I say "_maybe_ not good" instead of just "not good" is that the decimal character and thousands separator characters differ by locale and also contextually. For example, a dot in a version number or in an IP address is not a decimal separator - it just separates number groups. I think this is why localeCompare() doesn't bother trying to account for decimal separators and thousands separators in different locales.

(2) would be easy enough to change. I could just reverse it so that longer equivalent numbers come first instead of last. I thought it was nicer to sort shorter equivalent numbers first - and more consistent with - for example - sorting a < aa < aaa. It is probably more common to sort them last though. 

The simple change for (2) would resolve the specific cases in this report **but** if you expand the cases a bit you'll still see `2.01 < 2.1 < 2.02 < 2.2` - not the (possibly) desired `2.01 < 2.02 < 2.1 < 2.2` - so numbers with decimals would still not be in numerical order. Thus I'm not sure that a change would be worthwhile.

**Comment by ronakg** [comment]
@leilapearson I want to report another sorting issue here. Let me know if I should create a new bug for this.

For a case where 2 filenames have the same prefix and 1 of them doesn't have any suffix at all, the file without the suffix should be sorted ahead of the one with a suffix. 

Take a look at the following example. `close.go`, `close_test.go` and `close_channel.go` are not sorted alphanumerically.

VSCode sorting -
<img width="352" alt="Screen Shot 2020-11-13 at 11 39 31 AM" src="https://user-images.githubusercontent.com/1058322/99114100-25dcf000-25a5-11eb-8ed1-e63466ce3f4f.png">

Bash sorting -
<img width="488" alt="Screen Shot 2020-11-13 at 11 39 40 AM" src="https://user-images.githubusercontent.com/1058322/99114106-29707700-25a5-11eb-9bdf-3047ed393cc7.png">

**Comment by leilapearson** [comment]
Hi @ronakg. The reason this happens is that vscode sorts in locale order but bash shorts in unicode order. Locale order sorts the underscore character before the dot character, but unicode order does the opposite.  I submitted a PR that adds the option for vscode to sort in unicode order - as well as options to sort in locale order but group by uppercase first or lowercase first. That PR is currently on hold though as the maintainers evaluate the level of demand for these new settings.

See PR #97272 for more detail. Issue #99955 also provides a lot more background if you're interested.

**Comment by ronakg** [comment]
@leilapearson that option would be nice. Thanks for the info.

**Comment by fastrde** [comment]
This is what happened for me with Sort Order = default
> Version: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:30:02.420Z (3 wks ago)
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

![order](https://user-images.githubusercontent.com/1861723/104089494-e282c300-526f-11eb-9001-c0f2c3f1543c.png)

**Comment by leilapearson** [comment]
@fastrde Hex numbers aren't going to sort so nicely unfortunately... The default sort will sort numerically - ignoring leading zeros - and considering the number to be complete once it reaches anything non-numeric... The PR I mentioned above would provide a unicode sorting option that might give you what you are looking for... not a nice hex sort, but at least a character by character comparison sort.

**Comment by fastrde** [comment]
@leilapearson I'm looking for what is described as the _default sorting_ in VSCode. I don't want to sort hex numbers by value. I don't want to sort numbers by value either. I want to sort alphabetical. That's all ;-). The description of sort order _default_ is  _Files and folders are sorted by their names, in **alphabetical** order. Folders are displayed before files_.
 So I hope, that the mentioned PRs implements the *default behavior*. At the moment the description didn't match with the applied sorting.. 

default sorting at the moment
```
01apple    (01apple   = numerical value  1...)
11coconut  (11coconut = numerical value 11...)
012banana  (012banana = numerical value 12...)
```
Sorting I expected when I read the description
```
012banana  (012banana = alphabetic 012...)
01apple    (01apple   = alphabetic 01a...)
11coconut  (11coconut = alphabetic 11c...)
```

**Comment by leilapearson** [comment]
@fastrde that makes sense. Unfortunately the text is misleading. The actual behavior - since way before I got involved - has been to do a `localeCompare` with the `numeric` option enabled. So no, it isn't a truly an alphabetical search. I guess someone could fix the text to better describe the actual behavior since it is somewhat misleading.

I did submit an earlier pull request that provided the ability to do the various sort options with the numeric option turned off, but it didn't seem like many people were asking for that option and the maintainers requested a less complicated PR so I withdrew it. 

If enough people want a locale-based alphabetical comparison that doesn't have numeric sorting enabled - and the maintainers agree - then that feature could certainly be added at a later date.

**Comment by leilapearson** [comment]
Also, I'm happy to submit a new PR to add that new "non-numeric" option if the maintainers give the go ahead.

**Comment by paolieri** [comment]
A "non-numeric" option would be very useful; I was bitten by this too, in the same scenario as @fastrde (a directory with many files containing hex hashes in their name).

**Comment by paolieri** [comment]
@leilapearson was waiting for the go-ahead to submit a PR adding a "non-numeric" file sort option.
This would have the benefits of:
- preserving the current/default behavior (to avoid surprises)
- giving an option for those who need files in true alphabetical order (as `ls` would show them)

I hope maintainers can reconsider this.

**Comment by isidorn** [comment]
I am discussing a potential PR with @leilapearson on another issue, once we tackle that we might look into this.

**Comment by leilapearson** [comment]
@Leedehai the PR he was referring to was merged earlier this month and is currently available in VS Code Insiders builds and should be in the next VS Code release which I think is due out pretty soon. It doesn't directly address this issue, but there is a unicode option which is a non-numeric sort which will perhaps meet your needs? If you have a chance to try it, let us know what you think.
