### ISSUE TITLE
Unable to switch github account in settings sync

### ISSUE THREAD

**Issue by lc-caigwatkin** [microsoft/vscode#104595]
- VSCode Version: 1.48.0
- OS Version: Darwin x64 19.5.0

Steps to Reproduce:

1. Turn settings sync on using a github account
2. Turn settings sync off
3. Attempt to turn settings sync on again to use a different github account, however the only option for github is to use the "Last Used with Sync" account

If I was wanting to switch to a different Microsoft account I would be able to using the menu item "Sign in with Microsoft" but there is no similar item for github after the first time it is used.

![image](https://user-images.githubusercontent.com/34219518/90191036-3bab0f80-de14-11ea-9ca3-6d21b67331bc.png)

The docs say it should be possible https://code.visualstudio.com/docs/editor/settings-sync#_switching-accounts

![image](https://user-images.githubusercontent.com/34219518/90191129-6d23db00-de14-11ea-9be9-c2c872680244.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by wolfired** [comment]
i got this:
```bat
[2020-08-14 11:17:19.763] [userDataSync] [info] Using settings sync service https://vscode-sync.trafficmanager.net/
[2020-08-14 11:17:19.763] [userDataSync] [info] Auto Sync is disabled.
[2020-08-14 11:17:35.745] [userDataSync] [info] Request failed https://vscode-sync.trafficmanager.net/v1/manifest
```

**Comment by misolori** [comment]
You can only be signed into one GitHub account, have you tried signing out of your GitHub account using the account picker in the bottom left?

**Comment by lc-caigwatkin** [comment]
> You can only be signed into one GitHub account, have you tried signing out of your GitHub account using the account picker in the bottom left?

I'm not sure what the account picker you are referring to is. If one exists, then I am unable to easily find it.

My hope was that something similar to this could be implemented: https://github.com/microsoft/vscode/issues/96348#issuecomment-620693950

**Comment by misolori** [comment]
@lc-caigwatkin in the bottom left corner of the app there is the account switcher like so:

![image](https://user-images.githubusercontent.com/35271042/90353632-8d61be80-dffb-11ea-98e5-614487351547.png)

![image](https://user-images.githubusercontent.com/35271042/90353560-63a89780-dffb-11ea-840c-42d186297ed5.png)

If you have an entry for a "GitHub" account, then it means you are signed into a GitHub account. In order to switch accounts you'll need to sign out and then sign in. Does this help?

**Comment by lc-caigwatkin** [comment]
Thanks for that, it does help! I have my vscode set up with that bar on the right so I was looking at the bottom left near the source control UI elements rather than on the sidebar.

 I still think the existing feature (or docs) could be more user friendly because I was not aware this was how to change my account.

**Comment by misolori** [comment]
Thanks for the feedback, @sandy081 we should look into making it easy to sign out of the GitHub account from the Sync menu.

**Comment by sandy081** [comment]
How about showing an option to use different GitHub account and ask user to sign out when selected this option?

**Comment by misolori** [comment]
Yea that would work

**Comment by joelsonejr** [comment]
> You can only be signed into one GitHub account, have you tried signing out of your GitHub account using the account picker in the bottom left?

That did the trick for me.
Thanks.

**Comment by TylerLeonhardt** [comment]
I think we should close this in favor of https://github.com/microsoft/vscode/issues/127967 which is something that might not come right away, but will come in the future, I know it... and when it does, one of the criterias for that will be having Settings Sync support switching.

I will mark this as "wontfix" purely because we will not be fixing this with the "single GitHub account" model that we have today... anytime soon. (after all, it's been 2 years since)
