### ISSUE TITLE
"IPersistFile::Save failed" during installation of VS Code Insiders

### ISSUE THREAD

**Issue by Maxim-Mazurok** [microsoft/vscode#104545]
- VSCode Version: 1.48.0-insider (user setup)
- OS Version: Windows_NT x64 10.0.19041

Commit: db40434f562994116e5b21c24015a2e40b2504e6
Date: 2020-08-11T23:21:50.282Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0

Steps to Reproduce:

1. Download and run "VSCodeUserSetup-x64-1.48.0-insider.exe"
2. 
![image](https://user-images.githubusercontent.com/7756211/90112053-dc58eb00-dd92-11ea-8baf-1e4b18cb8f9f.png)

I'm not sure if it's relevant, but I had VS stable installed prior to the Insiders install. Also, I tried to remove stable and reinstall Insiders, which resulted in the same error. It seems like everything is functioning properly, but there's no shortcut on the desktop.

Does this issue occur when all extensions are disabled?: Yes

**Comment by llagerlof** [comment]
Windows 8.1 64

Same is happening with me, but with the stable installer (VSCodeUserSetup-x64-1.48.0.exe).

**Comment by llagerlof** [comment]
I tried to unistall and install again, but checked only the PATH option. All other options was left unchecked. No error happend. I don't know if was coincidence or that others checked options were causing the error.

**Comment by Maxim-Mazurok** [comment]
I believe "Create desktop shortcut" option may be producing this error.

**Comment by ReyOscuro9999** [comment]
Same happened installing Visual Studio Code. The thing is it happened with a pretty old Windows (not that that old but quite) but it still let me download it. What does this mean then? I had no problem installing it in another more modern computer but I have no idea what is wrong here...

**Comment by cuibty** [comment]
I also encountered the same problem
Win10 2004 (19041.388)

**Comment by yabasha** [comment]
me too

![image](https://user-images.githubusercontent.com/932321/90340482-3363f780-e001-11ea-8465-4d4ecb43a779.png)

**Comment by Seralyn** [comment]
Same exact error, though I installed it on another PC in my network without issue- same version of Windows, same options checked.

**Comment by BertV1** [comment]
Same exact error, also happened during creation of the shortcut.

**Comment by hexaleon** [comment]
Having the same issue. Been using it for over an year but never faced any issue like this. It got updated yesterday when I was working and after that when I tried to use live server, the chrome tab keeps on loading and CPU usage gets above 90% for chrome. Strange. 
Up till now, I have tried re-installation (thats when "ipersistfile save failed code 0x80070005" error occured), installing previous version, window update. Nothing seems to work and I think live server issue is happening because of it. 
Any idea?

**Comment by zeronyms** [comment]
create dekstop shortcut made this error ??

**Comment by aladdin-hub** [comment]
I have the same issue on Windows 7 - and seems like the checked "install link on the desktop" causes the problem, as at the end of installation VS saying "installed fine" and it's running OK.

**Comment by isidorn** [comment]
Users seeing this with vscode insiders when did this start happening?
Users seeing this with vscode stable, do you also see it when you install vscode insiders? https://code.visualstudio.com/insiders/

@bpasero for potential smartness
@deepak1556 even though it is not an electron crash might have some ideas since it looks like a native crash

**Comment by deepak1556** [comment]
Running with `VSCodeUserSetup-x64-1.48.0.exe /LOG="D:\setup.log"`

[setup.log](https://github.com/microsoft/vscode/files/5092040/setup.log)


```
2020-08-18 10:50:23.263   -- Icon entry --
2020-08-18 10:50:23.263   Dest filename: C:\Users\Public\Desktop\Visual Studio Code.lnk
2020-08-18 10:50:23.264   Creating the icon.
2020-08-18 10:50:23.923   Exception message:
2020-08-18 10:50:23.923   Message box (OK):
                          IPersistFile::Save failed; code 0x80070005.
                          Access is denied.
```

in my case it is a permission issue to the folder it is trying to write the shortcut link to. Users having similar error code please check if the setup executable under your current user has permissions to write into that folder.


If anyone else has a different error code, please paste the inno setup log using `/LOG` switch as above.

**Comment by JohnHammell** [comment]
Same issue when installing VSCodeUserSetup-x64-1.48.0.exe stable:

![image](https://user-images.githubusercontent.com/15966304/90594279-07d73d80-e1b8-11ea-89ec-f8d97ea9cd7e.png)

**Comment by bpasero** [comment]
I saw this error as well when I tested the installer (using a Windows VM on Parallels 10).

**Comment by FahanBakht** [comment]
Same Issue with me today, as @Maxim-Mazurok suggested I install it again without **"Creating desktop shortcut"** worked and install without any errors.

**Comment by deepak1556** [comment]
Sorry about the early conclusion, a bit more investigation looking at the logs of `1.47.3` installation, it does install the shortcut link under the desktop for current user rather than public folder. So this behavior change with `1.48` is indeed a bug.

Looking at the changelog, the only relevant changes that went into the setup code path are https://github.com/microsoft/vscode/commit/5f5b75a746c8f4e2a7e583bb17a2a493dd04e4a6 https://github.com/microsoft/vscode/commit/cbc8bd84ae67ba8b2f6dbc1cf582560a6e1f15ce , will check if the change in setup style brought in this behavior.

**Comment by isidorn** [comment]
@deepak1556 thanks for looking into this. I have cycles so let me know if I can help somehow.

**Comment by CRYPTOBRIGHTBUTTERFLY** [comment]
Was doing me like that and also telling me it was a security risk.

**Comment by isidorn** [comment]
Dear users that see this can you please try to install this insiders build and let us know if you can still reproduce. This would be very valuable to us as it contains a potential fix for this issue:

* win64 user setup https://az764295.vo.msecnd.net/insider/eb5f3c7b1246a38bea8e7412d49262a9bd7f04a8/VSCodeUserSetup-x64-1.48.1-insider.exe
* win32 user setup https://az764295.vo.msecnd.net/insider/eb5f3c7b1246a38bea8e7412d49262a9bd7f04a8/VSCodeUserSetup-ia32-1.48.1-insider.exe

**Comment by Maxim-Mazurok** [comment]
> Dear users that see this can you please try to install this insiders build and let us know if you can still reproduce. 

Tried to install your x64 version over my existing installation, same error:

![image](https://user-images.githubusercontent.com/7756211/90620421-c301e400-e255-11ea-9ce4-7fc45a859cf1.png)

**Comment by isidorn** [comment]
@Maxim-Mazurok thanks a lot. We figured out that it did not fix the issue.
We have another candidate that is being built now, soon it will be out and I will share the links so you can try again.
Really appreicate the help.

**Comment by isidorn** [comment]
Here's win32 build:
* https://az764295.vo.msecnd.net/insider/d514f5cbfc789c2f67f583ec20dc129ee7756546/VSCodeUserSetup-ia32-1.48.1-insider.exe

Soon we will have win64

**Comment by isidorn** [comment]
Win64 build: https://az764295.vo.msecnd.net/insider/d514f5cbfc789c2f67f583ec20dc129ee7756546/VSCodeUserSetup-x64-1.48.1-insider.exe

So please try it out and let us know.

What is not 100% clear to me are repro steps. It only happens with the user install, but only when there is a shortcut?
@deepak1556 can you clarify repro steps. Just wondering since there are not that many users that complain, so it is not only user install to trigger this.

**Comment by isidorn** [comment]
I have verified that the Inno-updater revert of version indeed fixes the issue.

**Comment by FahanBakht** [comment]
> Win64 build: https://az764295.vo.msecnd.net/insider/d514f5cbfc789c2f67f583ec20dc129ee7756546/VSCodeUserSetup-x64-1.48.1-insider.exe
>So please try it out and let us know.

Worked for me without any error now with Check in to create a desktop shortcut.

![Screenshot](https://user-images.githubusercontent.com/26104308/90637446-70203080-e245-11ea-80d2-aed84a8a38c9.png)

**Comment by isidorn** [comment]
Great. It also worked for me.

So to recap:
The inno-updated update broke this. We are looking into two options for the recovery build:

1) disable the create shortcut button for this release
2) fix the actual issue captured by https://github.com/microsoft/vscode/issues/104981

We will decide on which one to do depending on the risk.
We will not revert back to the old inno-update version due to other chagnes that have gone in.

fyi @lszomoru @deepak1556

**Comment by Maxim-Mazurok** [comment]
>  It only happens with the user install that creates a desktop shortcut.

Correct, I did check "Create desktop shortcut"

> Win64 build: https://az764295.vo.msecnd.net/insider/d514f5cbfc789c2f67f583ec20dc129ee7756546/VSCodeUserSetup-x64-1.48.1-insider.exe

Worked for me without any errors, created shortcut. Thanks!

**Comment by lszomoru** [comment]
Thanks @Maxim-Mazurok! We have a PR with a fix that will be included in the recovery build.

**Comment by Iceberg86300** [comment]
All with all options checked:

VSCodeUserSetup-x64-1.48.0.exe >> error
VSCodeUserSetup-x64-1.48.0.exe >> run as admin >> "you should use system" popup >> no error
VSCodeSystemSetup-x64-1.48.0.exe >> no error
VSCodeUserSetup-x64-1.48.1-insider.exe >> no error

**Comment by lszomoru** [comment]
Verification steps:
* Uninstall VS Code
* Download user setup
* In setup choose the option to create a desktop icon
* Complete setup wizard

Setup should complete successfully, and a desktop icon should be created
