### ISSUE TITLE
JS: Bad renaming behavior of variables and functions with same name

### ISSUE THREAD

**Issue by ariffjeff** [microsoft/vscode#104575]
Issue Type: <b>Bug</b>

I'm not sure if it is considered bad practice to have a function and a variable in a file with the same name or not. If so, I suppose this bug doesn't really matter too much.

Otherwise, renaming with F2 results in incorrect code being renamed. 

Tested in JavaScript.

```
var x;

x = 1;

if(x) {
    x()
}

function x() {}
```

Highlighting only the function `x` then F2-renaming shows the result is that both variables and function are renamed (except `var x;`).

The same issue occurs for attempting to rename only the variables where the function gets renamed as well. The exception being trying to rename all variables via `var x;` doesn't rename anything else. For some reason `x` the function is taking over the document and making all `x`'s "function colored" except `var x;`

I suppose even if this code is bad practice, F2-renaming should still be able to tell the difference between a variable and function of the same name?

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (2.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
extendscript-debug|Ado|1.1.2

</details>

**Comment by Jaeiya** [comment]
This is very bad practice since you're redefining what `x` is in the middle of your application. There's no way for the engine to know what your intent is here. You're expecting it to make assumptions about your code that are entirely subjective to how you're using the variable.

**Comment by ariffjeff** [comment]
@Jaeiya Thanks for clarifying. I wasn't really trying to produce code that actually worked. I just threw some x's around in various ways for the example. I had no intention of ever running this code haha.

**Comment by Jaeiya** [comment]
> I wasn't really trying to produce code that actually worked.

I kind of assumed that may have been the case, but I just wanted to cover all bases 👍 

> And also I didn't even know you could have x as a string and another as an array at the same time.

JavaScript is incredibly flexible and allows you to do all kinds of things you shouldn't do haha. You can use a single variable throughout your entire application if you wanted, though you would have to keep track of what it means throughout the entire scope of your app. 

In other words if you re-assign it as an array, then you could no longer use it as a string or function. Just like in your example, it's impossible for you to use `x` to validate the `x` function, because you would have to call the function before it's been defined.

If we re-arrange your example to having `x` declared and assigned with the function assignment right after, then `x` would now refer only to the function.

**Comment by ariffjeff** [comment]
Makes sense, thank you!

Ironically, I'm being forced to learn and use ES3 JavaScript so I am unable to use `let` as it doesn't exist in this version of JS! I'm writing Adobe Extendscript scripts for Illustrator and Adobe in their infinite wisdom haven't made it so anyone can use ES6 for any of their products (that I know of).

I will check out TypeScript with eslint regardless though, thanks!

**Comment by Jaeiya** [comment]
ES3...I definitely do **NOT** envy you; all the best luck with that my friend 😄

**Comment by ariffjeff** [comment]
I’m trying! What are the best things to come out of moving from ES3 to ES6 do you think? Since my only experience with JS is ES3...

**Comment by Jaeiya** [comment]
That's a huge topic. One of the most major changes is the addition of `Classes`. I believe they were added to make JavaScript more like other OOL's (Object Oriented Languages). Another few big ones were `Object.keys` and `Object.assign` which are extremely useful for extending/reading objects natively without having to write your own wrappers/factories. 

## ES5
Added `Array.isArray()` since there was no native way to detect an array type since everything in JavaScript is an `Object` type outside of strings and functions. Along with that addition we got `Array.forEach` which is a more explicit way to look through an array, though it is a little slower than just using a standard for-loop - depending on your use-case the performance hit can be negligible.

Another huge one was `Array.map` and `Array.reduce` which are absolutely invaluable when you want to extract/calculate specific values from one array and create a new array using those values.

This was also the first iteration of native **JSON** support with `JSON.parse()` and `JSON.stringify()`. You could say this single-handedly changed the way clients-servers interacted over the web forever, as today pretty much every web API request is a mutual exchange of JSON data.

`use strict;` was a huge boon to code-reliability and clarity as it restricts you to certain "best practices"; I don't remember exactly what it enforces, but nonetheless it's essentially the standard now when writing any JavaScript code. TypeScript turns it on by default so for me it's "out of sight, out of mind".

## ES6
Obviously the `let` and `const` keywords were added.

Arrow functions `() => { return 'somevalue'; }` which are exceptionally useful as they use the outer `this` when created inside objects/classes instead of a function-scoped `this` - that differentiation has left a many web developer wanting to kill themselves, back in the day. They're also very useful at creating succinct helper functions `const add = (x,y) => (x + y);`

Those are the major ones.

**Comment by ariffjeff** [comment]
I had absolutely no idea. Thank you so much for spending the time to write this up for me! When I finally upgrade to ES6 I will learn about all of this in more detail.

**Comment by Jaeiya** [comment]
No problem, glad I could help 😃
