### ISSUE TITLE
New condition for breakpoints: enable after another breakpoint was hit

### ISSUE THREAD

**Issue by alexeyr** [microsoft/vscode#104563]
IntelliJ's IDEs have this and I just had a debugging session where it would be very useful:

> When a breakpoint is selected in the Disable until hitting the following breakpoint box, it acts as a trigger for the current breakpoint. This disables the current breakpoint until the specified breakpoint has been hit.

> You can also choose whether to disable it again after this has happened or leave it enabled.

> This option is useful when you only need to suspend the program under certain conditions or after certain actions. In this case, the trigger breakpoint usually isn't required to stop the program execution and is made non-suspending.

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog and we might add this in the future. Thanks

**Comment by walidbarakat** [comment]
i can understand why this issue was closed, but as well i think such a feature isn't only about add the ability to bind a breakpoint to be enabled after another one, it can be a kick-start for a new mind set of debugging even analysis the code, i was working on this issue and i think i'm gonna continue working till i have a complete commit to show what i mean in it, i hope issue reporting guidelines doesn't mind re-opening closed issues.

**Comment by jeswin** [comment]
As a workaround, you could create a conditional breakpoint at the location which should "switch on" subsequent breakpoints, and in the breakpoint expression set a global variable (say global.enableMyBreakpoints = true). Subsequently, create other conditional breakpoints at which you check if this global variable is truthy or not. Quite easy in dynamic languages, a bit more work in statically typed ones.
