### ISSUE TITLE
I wish the markdown preview would delay loading

### ISSUE THREAD

**Issue by lancerXXXX** [microsoft/vscode#104649]
I use too many mathematical formulas in my markdown files, and when the document reaches a certain number of lines it takes too much CPU resources.

I have to use other editors such as Typora, and if this can't be improved no the performance, can you add an option to delay refreshing the preview, e.g. refresh the preview on save.

**Comment by mjbvz** [comment]
The built-in markdown preview does not support math formulas; they must be coming from one of your extensions

**Comment by lancerXXXX** [comment]
![image](https://user-images.githubusercontent.com/42160297/90617493-51b83600-e241-11ea-9af1-673872888ff6.png)

As I recall, this extension can support the  rendering of math formulas for the build-in markdown preview

@mjbvz

**Comment by mjbvz** [comment]
Yes, that is an extension. If you are using that extension, you should file this feature request against them

**Comment by hlorand** [comment]
The delay of the rendering of the preview is hardcoded into vscode (300 ms). It wold be a great idea to add an option to settings so users can change it.

https://github.com/microsoft/vscode/blob/9262b186b979ca8abd1faff9bed31336e47340a6/extensions/markdown-language-features/src/features/preview.ts#L106

**Comment by yadayadaydadaa** [comment]
It is, I would like to say unbelievable, that this issues not addressed. But, I I don't say so, because software is generally garbage and developers these days don't give a shit about delivering anything that remotely works. VScode is particularly bad. They are not even trying to hide the fact that they are **corrupt**, auto-closing bugs with a bot to keep the issue list clean, trying to make the steaming pile of garbage look good.

Right now, `markdown.preview.scrollPreviewWithEditor` basically has to be disabled, because the ultra-super-duper-frequent but slow re-rendering causes really nasty jumping of the preview. It is extremely apparent with math and the all-in-one extension above, but also occurs without it in longer documents.
