### ISSUE TITLE
Move git pull/push back to root menu level.

### ISSUE THREAD

**Issue by steffanhalv** [microsoft/vscode#104762]
After latest update (1.48.0) "git push" & "git pull" was added to an extra sub menu:

![Skjermbilde 2020-08-16 kl  20 44 58](https://user-images.githubusercontent.com/4593184/90341651-850c8200-e001-11ea-85f6-33c790f610c9.png)

This buttons is used very often (like 30+ times a day) and I would like to see it back at its original position which were on the root level, if possible.

Thank you!

**Comment by ikrong** [comment]
I need pull/push back too! 

臣等复议

**Comment by Shinigami92** [comment]
<img src="https://user-images.githubusercontent.com/7195563/90365486-21687000-e066-11ea-8885-fac56e51c08f.png" width="400px"/>

https://twitter.com/Shini_92/status/1294211655413444610

**Comment by gjsjohnmurray** [comment]
Related - #102109, #103923

**Comment by wilhelmklopp** [comment]
Would love to see this as well 🙏 

Or even moving push/pull out of the overflow menu into the main menu:
![image](https://user-images.githubusercontent.com/7718702/90388529-d196a280-e07f-11ea-938a-0a8fe3a24089.png)

**Comment by gjsjohnmurray** [comment]
As a workaround I just published a [simple extension](https://marketplace.visualstudio.com/items?itemName=georgejames.gitfavorites).

**Comment by ELI7VH** [comment]
This is a necessary amendment to the bad ui decision. Please merge!

**Comment by ELI7VH** [comment]
@wilhelmklopp the only issue with the sync button is that me (and I am assuming anybody else that used this dropdown, is that we would probably do this:

```
- click on "Message" text area
- type message, press "ctrl+enter" to commit
- since our mouse is still right by the ... we use the dropdown to quickly push the code. 
```
esp for people like me who have the browser on the right (because I'm weird), now i have to traverse the entire distance of the screen just to hit the sync button.

In most software, the common bottons are in the immediate dropdown menu, this is just a simple expectation in modern software, it makes zero sense to be backwards, ESPECIALLY in software that subtly influences other software. 

Revert this change, not just for us, but for the sake of all humanity.

**Comment by smaglio81** [comment]
Would it be possible to have a configuration option which would use either the old menu or the new menu?

**Comment by ChronSyn** [comment]
> Would it be possible to have a configuration option which would use either the old menu or the new menu?

This would be my preference. Push is literally the only command from that menu that I even care about (commit is handled with CTRL + Enter for me), but I understand the benefits that some people would see in the new menu system. It's just for me, it's broken my muscle memory without giving me the option to stick with something I had no problem with.

**Comment by Shinigami92** [comment]
I would prefer the best of both worlds...
I like the new submenues, but only want back at least `push`
It seems so, some others here als like `pull` also

https://marketplace.visualstudio.com/items?itemName=georgejames.gitfavorites
and
https://marketplace.visualstudio.com/items?itemName=tomblind.scm-buttons-vscode

are both good solutions, but I would prefer not to need an extension

**Comment by phgmacedo** [comment]
> As a workaround I just published a [simple extension](https://marketplace.visualstudio.com/items?itemName=georgejames.gitfavorites).

The extension does not work, there is no option to push. Only to clone and to checkout.

**Comment by phgmacedo** [comment]
Are there any user satisfaction/usability metrics on this feature? Because it seems there's an unusual amount of hate based on the number of duplicates about this improvement @joaomoreno

**Comment by gjsjohnmurray** [comment]
> 
> 
> > As a workaround I just published a [simple extension](https://marketplace.visualstudio.com/items?itemName=georgejames.gitfavorites).
> 
> The extension does not work, there is no option to push. Only to clone and to checkout.

@phgmacedo here's what my menu looks like when that extension is installed and enabled:

![image](https://user-images.githubusercontent.com/6726799/90606787-32e18180-e1f8-11ea-9171-533f4aeb814f.png)

And when that extension is disabled:

![image](https://user-images.githubusercontent.com/6726799/90607006-89e75680-e1f8-11ea-9f5f-e7646292e0f2.png)

**Comment by isidorn** [comment]
Thanks a lot for the feedback. We really appreciate it.
We do want to improve this menu, however we do not want to rush any change in before discussing it in our UX meeting. As a workaround I suggest to use @gjsjohnmurray extension, and we will most likely tackle this already in the next release.

Some feedback from @egamma 

- ‘push’, ‘pull’ are bread&butter git operations. I don’t think this is a personal preference. So the minimal proposal would be to only promote ‘push’ and ‘pull’ to the top menu.
- ‘sync’ is available in the status bar and not a pure git operation and it doesn’t have to be in the top menu (it is a very useful command but probably underused action).
- in the standup there was a separate discussion what to do with the toolbar and its actions. Given the past experience I would not remove any existing actions. What would be worthwhile to discuss whether we want to show more actions like ‘sync’  in the view toolbar.

My 2cents:

- Breaking user muscle memory is something which we should stay away from as much as possible, so it would be ideal if the push / pull are brought back in the exact same position
- We should look at telemtry data to make sure there is no 3rd action which is very popular

**Comment by gjsjohnmurray** [comment]
>    ‘sync’ is available in the status bar and not a pure git operation and it doesn’t have to be in the top menu (it is a very useful command but probably underused action).

With `"scm.alwaysShowRepositories": true` you don't even have to go as far as the status bar to access sync:

![image](https://user-images.githubusercontent.com/6726799/90631243-47367600-e21a-11ea-8d5d-5c9b81edb4c3.png)

**Comment by ELI7VH** [comment]
> 
> 
> > ‘sync’ is available in the status bar and not a pure git operation and it doesn’t have to be in the top menu (it is a very useful command but probably underused action).
> 
> With `"scm.alwaysShowRepositories": true` you don't even have to go as far as the status bar to access sync:
> 
> ![image](https://user-images.githubusercontent.com/6726799/90631243-47367600-e21a-11ea-8d5d-5c9b81edb4c3.png)

this is actually incredibly helpful. thank you.

**Comment by smaglio81** [comment]
I appreciate @isidorn's thoughtful reply earlier. It made me feel like I could share a few of my thoughts and they might become a part of the consideration process at the next UX meeting.

I actually appreciate having some of the less frequently used commands on the top level menu; not only to be able to easily see all of them, but because I use some of the less popular ones. My top 5 used commands are:

* Pull (Rebase)**
* Push
* Stash (Include untracked)
* Apply latest Stash 
* Pull

** = I prefer Pull (Rebase) and would have the global option set if ...  I didn't have a bad habit of checking in a change on the wrong branch and then cherry-picking it over to the right branch. A while ago, I read some git documentation that when you merge those cherry-picked updates back into master, you should use Pull instead of Pull (Rebase).

So ... here were some options I thought of:

### 1. Toggle for Multilevel Menu or Single Level Menu

Maybe in the User Settings there can be a checkbox that would switch the menu to either be single level or multi-level.

### 2. Multilevel Menu with a Top 5 Most _Recently_ Used Section

Similar to the [Git Favorites (simple) extension](https://marketplace.visualstudio.com/items?itemName=georgejames.gitfavorites), but the small section at the top of the menu would be a list your 5 most recently used commands.

### 3. Multilevel Menu with a Top 5 Most _Frequently_ Used Section

Similar to the [Git Favorites (simple) extension](https://marketplace.visualstudio.com/items?itemName=georgejames.gitfavorites), but the small section at the top of the menu would be list your 5 most frequently used commands.

### 4. Multilevel Menu with configurable Favorites Section

Similar to the [Git Favorites (simple) extension](https://marketplace.visualstudio.com/items?itemName=georgejames.gitfavorites), but the small section at the top of the menu would be configurable by users so they can put the commands they want (in the order they want) at the top.

HTH

**Comment by isidorn** [comment]
@smaglio81 thanks for the feedback. We will consider it. However that might be tackled with customisable menus which we have on our road map I believe.

The feedback from the UX meeting:

1. Most commonly used commands should not be in a submenu (more details bellow)
2. The sorting of the Groups in the context menu should be optimised. It is not respecting the old order, and the new order does not feel intuitive
3. Does the Toggle View Mode deserve an entry in the scm toolbar. There was some user backlash when we removed it @misolori might know the issue number

We have dag into our telemetry and the most used scm context menu actions are (number next to it are just proportions):

Git Push 293
Git Pull 187
Discard All Changes 143
Push to 80
Clean all 70
Stage 60
Undo Commit 55
Pull From 54

Due to these number I suggest that Push and Pull get moved back to the top level and that we consider also moving the Discard All Changes.

Thanks @sana-ajani for the numbers
fyi @eamodio

**Comment by misolori** [comment]
Here's the related issue for the list/tree toggle discussion https://github.com/microsoft/vscode/issues/102138

**Comment by JPNZ4** [comment]
I would like push/pull back into the main menu! At least have most common commands in the first menu.

**Comment by isidorn** [comment]
@misolori thanks. I am not convinced by #102138 and duplicates and would personaly remove it and add a command. But I leave that decision up to @joaomoreno

**Comment by danielehrhardt** [comment]
> @smaglio81 thanks for the feedback. We will consider it. However that might be tackled with customisable menus which we have on our road map I believe.
> 
> The feedback from the UX meeting:
> 
> 1. Most commonly used commands should not be in a submenu (more details bellow)
> 2. The sorting of the Groups in the context menu should be optimised. It is not respecting the old order, and the new order does not feel intuitive. Also maybe move views, view and sort to the bottom.
> 3. Does the Toggle View Mode deserve an entry in the scm toolbar. There was some user backlash when we removed it @misolori might know the issue number. If we remove it, there should be a command to toggle between list and tree.
> 
> We have dag into our telemetry and the most used scm context menu actions are (number next to it are just proportions):
> 
> 1. Git Push 293
> 2. Git Pull 187
> 3. Discard All Changes 143
> 4. Push to 80
> 5. Clean all 70
> 6. Stage 60
> 7. Undo Commit 55
> 8. Pull From 54
> 
> Due to these number I suggest that Push and Pull get moved back to the top level and that we consider also moving the Discard All Changes.
> 
> Thanks @sana-ajani for the numbers
> fyi @eamodio

Nice!

**Comment by KokoDoko** [comment]
This submenu is really clumsy. I often just need to "pull", now I'm stuck with windows 95-style menu diving. Sub-menus rarely add clarity or usability, all they do is hide options and make it unclear what is hidden where.
