### ISSUE TITLE
Explorer: Cmd+Down no longer moves focus to editor

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#104783]
- OS Version: macOS

Steps to Reproduce:

1. open a file with the mouse
2. press `Cmd+ArrowDown`

=> 🐛 focus does not move into editor

Works fine if you arrow down first to another file.

**Comment by isidorn** [comment]
Thanks for opening this, I can repro.
Assignign to August so we fix this.

**Comment by isidorn** [comment]
Same as https://github.com/microsoft/vscode/pull/104373
Had to introdcue a new command that gets also triggered in this case. Since the `list.onDidOpen` does not trigger if the focus did not change. @joaomoreno maybe we should consider changing that and remove all of this unuseful commands which we introduced

**Comment by bpasero** [comment]
It works but I would expect the selection in the explorer to also then be there.

**Comment by isidorn** [comment]
@bpasero can you please clarify what you meant?

**Comment by bpasero** [comment]
@isidorn when I Cmd+Down, the item that opens is not the selected one in the explorer

**Comment by isidorn** [comment]
That is how we always operated. Cmd+Down works on tree focus, not on selection.

**Comment by bpasero** [comment]
Ah ok, then maybe this was changed a while ago. I confirmed that `Enter` is also not moving the selection, which I personally find strange but if no-one else complains, fine.

My rationale is that `Enter` and `Cmd+Down` should behave exactly like a mouse-click but moving focus into the editor.
