### ISSUE TITLE
Auth dialog never shows up once canceled

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#104853]
- VSCode Version: 1.49-Insiders
- OS Version: macOS

Found this while testing https://github.com/microsoft/vscode/issues/104603

Steps to Reproduce:

* Clone https://github.com/joaomoreno/proxy-containers
* cd basic-auth && ./run.sh
* open code-insiders
* Settings > Proxy > http://127.0.0.1:3129
* Open developer tools > fetch('https://github.com') or perform any network request
* cancel the auth dialog

From then all network requests return 407 and reloading the window doesn't fix the problem. Quit and reopen the app helps.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by deepak1556** [comment]
Once a response has been set for proxy server it will be cached for a certain period, so the dialog not showing up for the same proxy server is expected but the auth dialog show up once the proxy config has been changed to a different server. Seems like a bug in `login` event from electron, will check.

**Comment by bpasero** [comment]
@joaomoreno @deepak1556 isn't this simply a consequence of us only showing the dialog once per session?

Check:

https://github.com/microsoft/vscode/blob/7f035b4be73a7ce9ceafb2128c066b717eafaf87/src/vs/code/electron-main/auth.ts#L47-L49

**Comment by deepak1556** [comment]
Oh seems like it, @joaomoreno any context on why we do that ?

**Comment by bpasero** [comment]
I wouldn't change this for now as users are probably used to this behaviour and this does not seem like a recent regression. Also, given my work on bringing this dialog into the workbench, we can revisit this later based on feedback.

**Comment by bpasero** [comment]
One thing we could do is to not show the dialog again for the current window but start to show it again for new windows.

**Comment by deepak1556** [comment]
Just to clarify, the way login event works is that when an authentication server requests 407 status code, electron gets a signal from the network stack and relays that to the app via this login event.

1) If the provided credentials turns out to be successful then the result will be cached by network layer and used for subsequent requests from the same server in a session.

2) And incase of failures the login event will relayed as long as there is active connections being established to the server.

3) If the server changes and an authorization is required then a new login request will be sent to the app.

In the 2) and 3) there is possibility of login event being emitted for the same window > 1 times. Why did we originally limit this to a single retry as pointed in https://github.com/microsoft/vscode/issues/104853#issuecomment-716501610 ?

> One thing we could do is to not show the dialog again for the current window but start to show it again for new windows.

Can we just let the default login signal be forwarded to the user, and if the noise from failures is something that bothers then we could provide a setting to control the number of retries from the event.

**Comment by bpasero** [comment]
@deepak1556 I see 4-5 `login` events right on startup not just one. Ideally Chrome/Electron itself would not fire new `login` events while the first one has not been resolved yet. In other words it would be great if:
* electron fires only 1 login event
* electron waits for username/password provided
* electron then uses that information for the other pending events

We could implement a workaround on our end and simply allow every `login` event to be handled through a dialog but then we also need to ensure only ever 1 dialog shows at the same time and that all subsequent events use the credentials from that dialog.

**Comment by deepak1556** [comment]
@bpasero do we plan to tackle this issue or revisit based on user feedback ?
