### ISSUE TITLE
Can not save on a Read-Only file. Getting a message - Insufficient permissions. Select 'Retry as Admin' to retry as administrator

### ISSUE THREAD

**Issue by mayankrockss** [microsoft/vscode#104822]
- VSCode Version: 1.48.0
- OS Version:Win 10 Enterprise v1809

Steps to Reproduce:

1. Open a Read-Only File
2. Make a change
3. Save it
4. On save we get error popup
- Insufficient permissions. Select 'Retry as Admin' to retry as administrator
![image](https://user-images.githubusercontent.com/39688548/90403593-d6c71200-e0be-11ea-9701-b76de0552547.png)

5. click on Retry as Admin
6. other error is displayed 
- Failed to save 'abc.js': Command failed: "_Some-PATH_\AppData\Local\Programs\Microsoft VS Code\bin\code.cmd" --file-write 
![image](https://user-images.githubusercontent.com/39688548/90403759-0aa23780-e0bf-11ea-97b5-4ec33a6df088.png)

 **NOTE**- It was working on previous versions of VS code. There was an option to "Overwrite". 

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by mayankrockss** [comment]
Can I get the original Issue ID or link?

**Comment by sandipchitale** [comment]
I think there is a confusion about Read-only file owned by the current user vs. ownership (which user owns the file) issues. The file can be owned by the same user but may be read-only, in such situations offering an action to Retry as Administrator does not make sense. The files are read-only in many VCSs like PErforce when the file is not checked out. BTW this started happening since very recent update.

**Comment by mayankrockss** [comment]
The issue was fixed after an update this morning. 😃
