### ISSUE TITLE
Terminal prompt line get higher on 'space'

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#104876]
- Have output in the terminal so the prompt is at the bottom
- Hide the terminal (cmd+j)
- Show the terminal
- Type, it's ok
- Press space, it shifts up by a couple pixels, as if the space is taller and it wasn't accounted for

![Aug-17-2020 17-28-26](https://user-images.githubusercontent.com/323878/90456962-18e85780-e0af-11ea-9683-298e1d4ab19a.gif)

**Comment by thijsputman** [comment]
It appears I'm experiencing a more pronounced version of the same issue. Upon pressing space, almost a full file line's worth of pixels get added:

![vscode](https://user-images.githubusercontent.com/4418373/90622360-48b16f80-e215-11ea-9302-31b1a5a49e49.gif)

I'm using a 4K screen (150% DPI scaling); that might explain the different behaviour?

**Comment by yseymour** [comment]
I have this issue as well.  The terminal seems get shifted up by a fraction of its height — it's worse when the panel is maximised.  It seemed to start happening with the July update.

**Comment by braddurbin** [comment]
I have this issue, but only on Windows, not on Linux. For me, it jumps more like 10 lines when I press 'space'. I "fixed" it for now by setting "terminal.integrated.windowsEnableConpty" to false.

**Comment by Tyriar** [comment]
I can repro on Windows/Windows WSL, I'm seeing a single pixel getting added when I do the space.

Before:

![image](https://user-images.githubusercontent.com/2193314/91503371-21931780-e87f-11ea-8aa0-d5d0964578d6.png)

After:

![image](https://user-images.githubusercontent.com/2193314/91503403-353e7e00-e87f-11ea-8a61-53d29d4bc4f5.png)

@braddurbin that sounds like a different problem of powershell not rendering your lines as expected via conpty, this issue is around the renderer viewport shifting.

**Comment by Tyriar** [comment]
This is likely caused by https://github.com/xtermjs/xterm.js/pull/2996
