### ISSUE TITLE
Go to inferred type definition via keyboard shortcut

### ISSUE THREAD

**Issue by normalser** [Microsoft/vscode#10489]
- VSCode Version: Code - Insiders 1.5.0-insider (e9c80f036645caae7759b3954fc72dbe6c644edf, 2016-08-12T06:04:09.471Z)
- OS Version: Darwin x64 15.6.0

Steps to Reproduce:

``` ts
interface Test {
}

const test:Test = {}
const test2 = test 
```

If your cursor is inside `Test` of `const test:Test` you can click `F12` to go to that type definition - but sometimes you do not have type declared explicitly (infered type) - eg. `const test2` then it's impossible to go easily to type defintion. Maybe combination of some key + click (or extra entry in popup) `Go to type definition`

**Comment by waderyan** [comment]
@dbaeumer this looks like a valid feature request? Is this something provided by VS Code or by Salsa?

**Comment by dbaeumer** [comment]
Nice idea.

@waderyan in these cases I do the following: I create a issue against TS and link to it from a VS Code issue (this one). I keep this one as a feature request on our end.

**Comment by dbaeumer** [comment]
May be we need a depends-on label to mark these.

**Comment by waderyan** [comment]
This issue was moved to Microsoft/TypeScript#10394

**Comment by waderyan** [comment]
Reopening to track feature request.

**Comment by mhegazy** [comment]
As noted in https://github.com/Microsoft/TypeScript/issues/10394#issuecomment-240531553, The feature is already implemented on the TypeScript side, VSCode needs to expose it trough a user gesture.

**Comment by waderyan** [comment]
Excellent thanks @mhegazy. 

@dbaeumer see above.

**Comment by dbaeumer** [comment]
Didn't know it.

@jrieken we first need this in the API. Could be bound to Ctrl+Shift+Click. What do you think.

**Comment by jrieken** [comment]
Makes sense. 

@dbaeumer you can already go ahead and that without additional API (since the feature is pretty UI-less). You can implement that as a command and wire it up with context menu and/or keybindings. I did something similar with my print references [extension](https://github.com/Microsoft/vscode-extension-samples/blob/master/contentprovider-sample/package.json#L34).

I am in favour of that since having TypeScript exercising this once will help to define/refine the API we want for that.
