### ISSUE TITLE
Too big page is too laggy, hope to subdivide

### ISSUE THREAD

**Issue by shijunti19** [microsoft/vscode#104873]
Too big page is too laggy, hope to subdivide

https://code.visualstudio.com/api/references/vscode-api

**Comment by gregvanl** [comment]
Hi @shijunti19 Thank you for your suggestion. The vscode-api page is quite large due to being auto-generated from the VS Code Type Definition file https://github.com/microsoft/vscode/blob/master/src/vs/vscode.d.ts. At this point, we don't plan to break this up by namespace or some other subdivision.

If reviewing the web page is too slow, you could review the vscode.d.ts file directly in VS Code. The file is included in all VS Code extension projects as an npm module. Using Go to Definition on any VS Code type will bring up the vscode.d.ts file in the editor, were you can search, see in Outline view, or use the other code navigation commands.
