### ISSUE TITLE
Clean erases lines but they all are displayed again, with the "Run" command

### ISSUE THREAD

**Issue by christalk** [microsoft/vscode#104920]
In the Terminal screen of VSCode, the Right click with the mouse for the Clear command, erases the lines, but the next "Run" command redisplays all the previous lines.
This does not happen with the "Clean" command directly entered in the "Terminal" screen.

- VSCode Version:  1.48.0
- OS Version:   Windows10   1903 - 18362.959

Steps to Reproduce:

1. Run a script python file.py with print 
2. Clear with right click from the mouse , in screen.
3 . Run the script again.
4. See all the lines 

Does this issue occur when all extensions are disabled?: Yes

**Comment by christalk** [comment]
PS : The more height I leave on the Terminal screen, the more lines of redisplay there will be from previous displays. small space : a few lines.  Big space , more and more lines.

**Comment by Tyriar** [comment]
This issue seems to originate from an upstream component (conpty) and is not something VSCode can fix by making a change to our code. As such, I will go ahead and close it. Please try to reproduce in [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal-preview/9n0dx20hk701) and report to [microsoft/terminal](https://github.com/microsoft/terminal) with repro steps.

Thanks for understanding.
