### ISSUE TITLE
Close action should close all editors of a group not just one

### ISSUE THREAD

**Issue by tinganho** [Microsoft/vscode#10492]
I'm not sure what the benefits of introducing tabs was. But I would like to have back that clicking the X-button means close editor. What's the benefit of just closing one file? My workflow often means switching between 2-3 editors. 

Editor meaning column. And why the name editor? It's confusing.

**Comment by stevencl** [comment]
Thanks for your comment. We received a lot of feedback about our initial editor management user experience which led us to make this change. For example, many people told us that they expected hitting the 'x' button to close just the last editor that they opened, not every one.

Unfortunately it's not straightforward to bring back the exact same behaviour. But one thing you can do is set up your settings and keybindings so that you get almost the same behaviour as before through the keyboard.

One way to get close to the non tabs user experience is to set the following in your user settings:

"workbench.editor.showTabs": false,

Then change the key bindings like so:

[
    {"key": "ctrl+w", "command": "workbench.action.closeEditorsInGroup"},
    {"key": "ctrl+k ctrl+w", "command": "workbench.action.closeActiveEditor"}
]

This way you can use ctrl+w to close all editors in a group.

Hitting the x button will still close the top most editor though.

Let us know if this workaround is satisfactory.

Thanks!

**Comment by bpasero** [comment]
Not planning to change anything, closing.
