### ISSUE TITLE
OccurrencesHighlight flag turns off scrollbar`s highlight

### ISSUE THREAD

**Issue by sartyukhov** [microsoft/vscode#104937]
- VSCode Version: 1.48.0
- OS Version: Manjaro Linux

Steps to Reproduce:

0. Set "editor.occurrencesHighlight" to false (to disable auto highlight element when cusror on it)
1. Open your code
2. Double click any word that multiply repeats on your code -> minimap does not highlights them anymore
(it works in vscode with pylance turned off)

_That bug happends with **Python Pylance** extension enabled, and I've already [opened issue](https://github.com/microsoft/pylance-release/issues/205) there. But @jakebailey is sure it's vscode\`s problem, not Pylance\`s.
Full cases to reproduce that bug are enumerated [here](https://github.com/microsoft/pylance-release/issues/205#issuecomment-670709960)_

Does this issue occur when all extensions are disabled?: No

**Comment by jakebailey** [comment]
See my comment here (and the screenshot comparison above): https://github.com/microsoft/pylance-release/issues/205#issuecomment-670712084

Pylance is an LS and declares document highlight support. With `"editor.occurrencesHighlight": false` and a double click to select a word, the word's uses get highlighted in the file but not in the scrollbar. If you disable Pylance, falling back to the simple word matching for highlighting, then double clicking highlights in both places consistently. This leads me to believe that the scrollbar is using different logic than the editor window that depends on whether or not a document highlight provider is available.

If you simply click on a word without selecting it, the behavior is consistent across all settings with/without an LS.

**Comment by sartyukhov** [comment]
I assume @alexdima  is on vacation :)

**Comment by alexdima** [comment]
There are two features interacting here.

1. `Selection Highlighting`: textual and language independent
2. `Occurrences Highlighting`: semantic and comes in via a `DocumentHighlightProvider`

`Selection Highlighting` does not render the decorations in the overview ruler if there is a `DocumentHighlightProvider`. This is done [here](https://github.com/microsoft/vscode/blob/88f93ee247ebca77b4e500229b3a0eab02ae0583/src/vs/editor/contrib/multicursor/multicursor.ts#L974) and used [here](https://github.com/microsoft/vscode/blob/88f93ee247ebca77b4e500229b3a0eab02ae0583/src/vs/editor/contrib/multicursor/multicursor.ts#L1014). But in this case, there is a `DocumentHighlightProvider`, but it is turned off via `editor.occurrencesHighlight`.

So the problem is that the check for existence of a `DocumentHighlightProvider` is not sufficient, the enablement of the option must be checked too.

**Comment by alexdima** [comment]
@aeschli Thanks for verifying! I don't think we ever rendered selection highlights in the minimap (irrespective of this issue).
