### ISSUE TITLE
Always open the output panel!!

### ISSUE THREAD

**Issue by u3u** [Microsoft/vscode#10491]
- VSCode Version: 1.4.0
- OS Version: Windows 10 1607

Steps to Reproduce:

1. Open vscode
2. Close ouput pannel
3. Reset vscode
4. Always open the output panel

Cannot remember open state

**Comment by bpasero** [comment]
@u3u so you say VS Code is stuck always opening the output panel on start?

**Comment by u3u** [comment]
@bpasero Every time it automatically opens the output panel, even if the output panel is closed!

**Comment by bpasero** [comment]
I am very sorry to hear you are having issues with VS Code. I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by u3u** [comment]
@bpasero Thanks for your reminding!
