### ISSUE TITLE
Enable code folding and collapsing

### ISSUE THREAD

**Issue by egucciar** [Microsoft/vscode#105]
I searched but couldnt find this in the issues. Id love to be able to collapse sections of the code. Any thoughts?

**Comment by sevin7676** [comment]
Now that is being developed, I have a few suggestions:

-----------------------
**Please add support for this code folding operation** *(I don't know what to call it)*:
1. Fold all blocks
2. Unfold the block that the cursor is currently in (where it was located before the fold all command)

In the ACE Editor this is called 'FoldOther' and it is bound to hotkey Alt+0 by default. Try it out [here](http://sevin7676.github.io/Ace.Tern/demo.html#javascript) *(put your cursor inside of a function block and press Alt+0; Shift+Alt+0 then unfolds all)*.

This folding operation is incredibly useful because it allows you to quickly collapse everything except for the block of code you're currently looking at - which lets you focus on a single block of code. 

-----------------------
**Please make all curly braces create a folding block in C-style languages**
Example: In Visual Studio *(not visual studio code)* - curly braces only produce a folding widget for classes and members, which is why [this plugin](https://visualstudiogallery.msdn.microsoft.com/9390e08c-d0aa-42f1-b3d2-5134aabf3b9a) exists. The problem is the plugin has major performance issues in large files, which is something that can be avoided if the proper folding support is added natively. Note: This should be supported in ALL C-style languages including: C, C#, JavaScript, Java, etc...

-----------------------
**Please include support for region folding in all C-style languages**
Regions are officially part of C#, but not other C-style languages. However, they are useful in other C-Style languages. 

The ACE Editor already has [support for this type of folding](https://github.com/ajaxorg/ace/wiki/Non-Standard-Code-Folding).

This feature should have an option to turn it off, because for every person that loves regions, there is another person [who hates them](https://visualstudiogallery.msdn.microsoft.com/0ca60d35-1e02-43b7-bf59-ac7deb9afbca). 

Also, it would be great to have this for SQL-Server (Microsoft's SQL) mode (once the language is added). I personally created a SQL Server mode for the Ace Editor and I included this feature. Try it [here](https://ace.c9.io/build/kitchen-sink.html): Select 'SQLServer' for the document in the top left corner.

**Comment by aliozgur** [comment]
:+1:

**Comment by satahippy** [comment]
+1

**Comment by flyfj** [comment]
I have trouble working with large files without code folding, may switch to other editors for a while until vs code gets this

**Comment by hdf** [comment]
I would like notepad++ compatible code folding:
>//{ This folds
>code here
>//}

**Comment by Nimzozo** [comment]
Important feature indeed.
With Netbeans, we can also add <editor-fold> tags to create a folding block.

**Comment by eugeneniemand** [comment]
Hopefully this will work in all languages for curly braces including PowerShell and Javascript and not only C languages. Comment folding would be nice to.

**Comment by joaomoreno** [comment]
A first version of this feature will be on the February release.

**Comment by Nimzozo** [comment]
> A first version of this feature will be on the February release.

:+1:

**Comment by crmdev** [comment]
1 day left in this month... should we have asked which February? :)

**Comment by hulang** [comment]
Folding function must be in March 31st to have it?

**Comment by glen-84** [comment]
@hulang See the release dates here https://github.com/Microsoft/vscode/issues/2616

**Comment by RANUX** [comment]
After update to latest version of VSCode (0.10.10) if found that folding doesn't work for recommended C# comment tags. ( https://msdn.microsoft.com/en-us/library/5ast78ax.aspx )

**Comment by Novack-** [comment]
#REGION folding seems missing.

**Comment by topgun743** [comment]
Don't understand why Visual Studio Code team not adding this `#region #endregion` feature still after so many builds of theirs. Its a must for their product.

**Comment by rhtpandeyIN** [comment]
Please add #region #endregion feature. Its a must for well management code.

**Comment by atlemael** [comment]
+1 for #region #endregion, needs to be added!

**Comment by CarlosRodrigues** [comment]
And for typrescript/javascript: 
//#region 
code here
//#endregion 

would also be great!

**Comment by john-yick** [comment]
#region and #endregion would be amazing for JS

**Comment by BladeMight** [comment]
+1 for #region and //#region.

**Comment by HecticHiccups** [comment]
yes!

**Comment by Eraph** [comment]
Another request for #region folding here.

**Comment by henioStraszny** [comment]
Same here, would love it for C#, TS and JS.

**Comment by cperezortiz** [comment]
would like it too 😄

**Comment by ChayaCooper** [comment]
+1 for PHP in both Visual Studio and WebMatrix

**Comment by kymowang** [comment]
even Intellij Idea supports //region folding

**Comment by Pulstura** [comment]
Really wish region folding was implemented in VSCode!

**Comment by pedrorolo** [comment]
How to I disable it? I do not want the pluses to take my horizontal space.

**Comment by pedrorolo** [comment]
when you use a small screen it becomes relevant. I have just disabled them by searching for folding in "preferences"

**Comment by ColacX** [comment]
Hello i want this for CSS is this implemented yet? I see that the issue is closed. Thanks for making this great editor btw.

**Comment by aeschli** [comment]
@ColacX The current folding only depends on indentation and is not language aware.
The request for language aware folding is #3422
