### ISSUE TITLE
Add support for passing custom config (that isn't in launch.json) into debug adapters

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#10503]
I'm not sure what's the best way to do this, but we have some config (the location of the Dart SDK) we'd like to pass into the debug adapter. We don't want to force the user to put this into `launch.json` since the extension already knows it (we detect it and/or allow the user to config it).

As far as we can see, there's no way to pass additional info into the debug adapter (if this is incorrect, great, can you point us in the right direction?) or to have it access the Code config?

For now we're discussing dumping this into a temp folder and reading it back out, but obviously that's a bit of a hack!

**Comment by jrieken** [comment]
You can use data from the settings ala `config.foo.bar`

**Comment by DanTup** [comment]
Oh, I figured using `vscode` wasn't possible (I did test and it crashed, but I was trying to show an error message via window). Is it all just the same code as doing it in the extension? Is there an obvious way to know what works in the debug adapter and what does not?

**Comment by weinand** [comment]
@DanTup a debug adapter is not running in the extension host and therefore has no access to the `vscode` API. The reason for this is hat a debug adapter can be implemented in any language and should be independent from VS Code as far as possible. All communication between VS Code and the debug adapters is done through the protocol or the launch config. There are no hidden side channels.
 
I understand your need for a 'side channel' but I do not yet have a good and final solution.
 
What I suggest in the meantime:
In your package.json Introduce a new variable 'dartSettings' that is associated with a 'command' that you can implement in your extension code (not in the debug adapter). This variable can then be used as a value in the launch.json to pass all dart settings into the debug adapter. In order to avoid that the user has to create this attribute/value pair manually, you can add it to the `initialConfigurations` in your package.json.
For details see section 'Debug Extension Authoring: Command Variables' in the [June release notes](https://code.visualstudio.com/updates/June_2016).

**Comment by DanTup** [comment]
That's what I thought, that's why I was confused by @jrieken's comment :(

The value is not known until runtime and it can be changed by the user in settings, so putting it in `initialConfugration` won't work.

We do have a workaround (we write into `%temp%\dart-code.txt` and then read it from the debug adapter) so this isn't critical, but our workaround is a bit hacky (and doesn't handle multiple instances of Code with different Dart SDK paths properly) so a better way to do this would be great.

**Comment by weinand** [comment]
@DanTup the variable's **name** will be put in the `initialConfugration`, not the value. The value is calculated in your extension just before the user launches the debug session. So this would work fine in your case and would eliminate the need to write to some temp file.

**Comment by DanTup** [comment]
Oh, gotcha. I'll have a play around. Thanks! :grinning:

**Comment by weinand** [comment]
Mock debug has a simple example where a command variable evaluates to a string entered by the user: https://github.com/Microsoft/vscode-mock-debug/blob/master/src/extension.ts

**Comment by DanTup** [comment]
Perfect, thank you! :)

**Comment by DanTup** [comment]
@weinand Looks like an update (1.10?) to Code has broken this..

```js
"dartSettings": "${command.dartSettings}"
```

Now says `Unexpected token $ in JSON at position 0`.

I'm struggling to make this work - I tried adding `\\` to the start (I saw [this change](https://github.com/Microsoft/vscode-mock-debug/commit/a723813425595307973103c47b07ac856f4671a5) and wondered if it was related).

This means as people upgrade to `1.10`, launching Dart apps is broken; do you know what the correct fix is? Is there somewhere we can monitor for breaking changes like this?

**Comment by DanTup** [comment]
@weinand Never mind; the tooltip in `launch.json` explained the issue (the fix is changing to `command:`). I think maybe [this one](https://github.com/Microsoft/vscode-mock-debug/blob/master/.vscode/launch.json#L46) might need updating then?

**Comment by weinand** [comment]
@DanTup yes, we started to support ':' as the separator. See our 1.10.1 release notes: https://code.visualstudio.com/updates/v1_10#_new-variable-syntax
But the old syntax does still work, right?

**Comment by DanTup** [comment]
@weinand It didn't in my testing - pressing F5 resulted in an error toast across the top saying `Unexpected token $ in JSON at position 0`. I had to change to `:`.

I've pushed out an updated version of Dart Code that automatically updates the `.` to a `:`, but anyone on the previous version will get this confusing error when trying to debug (I presume other extensions will be affected too?).

**Comment by DanTup** [comment]
@weinand Here's a screenshot I took earlier.

![Code launch error](https://cloud.githubusercontent.com/assets/1078012/23552295/0ac08c48-0013-11e7-970c-9d88596f516b.png)

**Comment by weinand** [comment]
@DanTup I'm not able to reproduce your problem. 

@isidorn @aeschli  do you understand what triggers the syntax error?

**Comment by isidorn** [comment]
@weinand looks like it is coming from the json world

**Comment by DanTup** [comment]
@weinand Apologies, the error I posted is misleading; that's my code - I believe because the variable was not replaced with the expected value. Just adding some trace and will post back..

**Comment by DanTup** [comment]
@weinand So, the SyntaxError is misleading, that's coming from Dart Code. The problem is that the variable comes through without the variable being resolved:

```ts
protected launchRequest(response: DebugProtocol.LaunchResponse, args: DartLaunchRequestArguments): void {
	// args.debugSettings here is the literal string "${command.debugSettings}"
```

If I change the dot to a colon, I get the correct string that is returned from `dart.getDebugSettings`.

Sorry for the confusion; but I still think this is broken.

**Comment by weinand** [comment]
@DanTup yes, i can reproduce. I've create this issue: https://github.com/Microsoft/vscode/issues/21894

**Comment by weinand** [comment]
BTW, you can now pass custom config to the debug adapter without using the $variables approach.
So the user does no longer has to see these attributes in his launch config.

Just contribute a 'startSession' command like node-debug: https://github.com/Microsoft/vscode-node-debug/blob/master/package.json#L100 . In the implementation (https://github.com/Microsoft/vscode-node-debug/blob/master/src/node/extension.ts#L290) you receive the launch config and you can easily retrieve values from settings via official extension API and add it to the launch configuration that is passed to the debug adapter.

Since this feature solves the original issue, I will close the issue.

**Comment by DanTup** [comment]
@weinand awesome, I'll add an issue to move over. Thanks!

**Comment by DanTup** [comment]
@weinand This seems to work great, however as soon as I implement the `startSession` command, Code no longer generates a `launch.json` from the initialConfiguration in `packages.json` when I hit `F5` and select my debugger.

I can see in your definition of `StartSessionResult` there's an optional `content` property with the comment `// launch.json content for 'save'` however I was hoping it'd just continue to use the stuff it used to. Do I need to do something to handle the creation of initial configuration?

**Comment by DanTup** [comment]
Actually, I just realised what's happening here... When the user is pressing F5, you're not just starting a session normally and I'm failing to detect it. This means I can launch the entire session without a launch.json at all!

That said; it might still be nice to write the `launch.json` on the first press of `F5`, so what's the correct way to do that?

**Comment by weinand** [comment]
@DanTup so you know what to do now?

**Comment by DanTup** [comment]
@weinand Yep, think I got it all sorted now :-) Working on attaching to existing processes now, so will also need to ask user for input. Looks like it should be fairly simple though! Thanks for your help and links; they've been very useful!

**Comment by isidorn** [comment]
Adding verified since user confirmed it worked
