### ISSUE TITLE
Debugging multiple extensions after 1.46.0 is not possible

### ISSUE THREAD

**Issue by veredcon** [microsoft/vscode#105075]
- VSCode Version: 
Version: 1.48.0 (user setup)
Commit: db40434f562994116e5b21c24015a2e40b2504e6
Date: 2020-08-13T07:50:42.600Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:

I cannot debug multiple extension after VScode 1.46.0. Me and my colleagues were downgrading to 1.45 as a temporary workaround but now even this doesn't help anymore and my work is blocked.

I had the following launch.json which has always been working for me:

```json
{
"name": "Name of Launch",
"type": "extensionHost",
"request": "launch",
"runtimeExecutable": "${execPath}",
"args": [
"--extensionDevelopmentPath=/Users/path/repos/vscode-wing-cf-tools/wing-vsix",
"--extensionDevelopmentPath=/Users/path/repos/vscode-wing-run-config/wing-vsix",
"--extensionDevelopmentPath=/Users/path/repos/vscode-wing-cap-run"
],
"outFiles": [
"/Users/path/repos/vscode-wing-cf-tools/wing-vsix/out/**.js",
"/Users/path/repos/vscode-wing-run-config/wing-vsix/out/*.js",
"/Users/path/repos/vscode-wing-cap-run/bundle/**/*.js"
],
"preLaunchTask": "npm: webpack"
}
```

This configuration resides in launch.json of the "vscode-wing-cap-run" extension. Only breakpoints in this extension are set properly and stops.
However, **I get "Unbound breakpoint"** when I set breakpoints at the other extensions (vscode-wing-cf-tools and vscode-wing-run-config)

The other extensions are for sure activated as I see the views they contribute in VSCode.
Please help my work is blocked since I cannot debug anymore.

Log:

I tried to add "trace": true like that:
```js
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "trace": true,
  "configurations": [
    {
      ...
    }
  ]
}
```
in order to send you the log but it doesn't print the log file path to the debug console. Please assist in that.

Does this issue occur when all extensions are disabled?: Yes

**Comment by connor4312** [comment]
Also, you will need to set `resolveSourceMapLocations`. Here's an example debugging two extensions: https://github.com/microsoft/vscode-js-debug/blob/master/.vscode/launch.json#L76-L99

I've made a change so that this manual fiddling will no longer be necessary in VS Code 1.49, but on 1.48 it is needed since `resolveSoruceMapLocations` defaults to the workspaceFolder excluding node_modules.

Please let me know if that works for you.

**Comment by veredcon** [comment]
Hi @weinand ,
I am aware of the glob pattern and of course it is the correct glob pattern that has always been working for me. 
I will attach a screenshot because when copy & paste here has changed it:
![image](https://user-images.githubusercontent.com/9718939/90787809-c8226a00-e30d-11ea-8f21-448763512795.png)

Also I'm adding the trace log files:
[vscode-debugadapter-0.json.gz](https://github.com/microsoft/vscode/files/5103819/vscode-debugadapter-0.json.gz)
[vscode-debugadapter-1.json.gz](https://github.com/microsoft/vscode/files/5103820/vscode-debugadapter-1.json.gz)

Thanks!

**Comment by veredcon** [comment]
Hi @connor4312 ,

I'm trying to use extensionHost type and the resolveSource property is not allowed on this type:
![image](https://user-images.githubusercontent.com/9718939/90789579-be016b00-e30f-11ea-988d-cfdc7b01fb2e.png)
I tries it anyway and it did not work...

Also when changing the type to `pwa-extensionHost` like in your example it did not work:
This doesn't work:

![image](https://user-images.githubusercontent.com/9718939/90789444-9c07e880-e30f-11ea-8426-72abba65c58f.png)

**Comment by connor4312** [comment]
Can you send a trace log with `resolveSourceMapLocations` set?

**Comment by veredcon** [comment]
This is the trace when using launch configuration as my last screenshot with type `pwa-extensionHost` and `resolveSourceMapLocations` set as above:

[vscode-debugadapter-3.json.gz](https://github.com/microsoft/vscode/files/5103914/vscode-debugadapter-3.json.gz)

**Comment by connor4312** [comment]
It looks like you're using Unix/linux style paths, but the compiled filed for, for example `vscode-wing-run-config/wing-vsix/src/extension.ts`, is `"c:\Users\i065595\repos\vscode-wing-run-config\wing-vsix\dist\extension.js` which doesn't match `/Users/i065595/repos/vscode-wing-cap-run/**`.

You may want to consider using relative paths as I do in the example I sent you instead of absolute paths, which would let developers on any platform run and debug your extensions (so long as they are cloned next to search other).
