### ISSUE TITLE
Setting WebviewPanel to  vscode.ViewColumn.Active or Beside returns undefined when retrieving the column value from the created panel

### ISSUE THREAD

**Issue by bfitzpat** [microsoft/vscode#105168]
Version: 1.48.0
Commit: db40434f562994116e5b21c24015a2e40b2504e6
Date: 2020-08-13T07:40:55.768Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.4.0-7634-generic

Steps to Reproduce:

1. Create an extension that creates a webview like the https://github.com/microsoft/vscode-extension-samples/tree/master/webview-sample
2. Set the column at start to vscode.ViewColumn.Beside https://github.com/microsoft/vscode-extension-samples/blob/8d43af086869d6fd4353d4c65548732da5cd095f/webview-sample/src/extension.ts#L65
3. Retrieve the column after the panel is created. Use Active or Beside and you get the same result.

```
		// Otherwise, create a new panel.
		const panel = vscode.window.createWebviewPanel(
			CatCodingPanel.viewType,
			'Cat Coding',
			vscode.ViewColumn.Beside,
			{
				// Enable javascript in the webview
				enableScripts: true,

				// And restrict the webview to only loading content from our extension's `media` directory.
				localResourceRoots: [vscode.Uri.file(path.join(extensionPath, 'media'))]
			}
		);

		CatCodingPanel.currentPanel = new CatCodingPanel(panel, extensionPath);
		console.log(`column = ${CatCodingPanel.currentPanel._panel.viewColumn}`);
```

I always get `column = undefined` as a result. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
The original case in the issue is unfortunately not something we can fix.

The good news though is that the `viewColumn` should be correct once the webview starts showing in the editor. However between the call to `createWebviewPanel` and the time the webview first shows in the editor, we don't actually know what `active` or `beside` means. I recommend avoiding relying on `viewColumn` when the webview is in this state
