### ISSUE TITLE
Interactive playground has incorrect key combination for rename refactoring

### ISSUE THREAD

**Issue by arevi** [microsoft/vscode#105154]
- VSCode Version: 1.48.1
- OS Version: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. Visit Help > Interactive Playground

2. Scroll to "Rename Refactoring" and read instructions for renaming variables. The instructions are to select the variable name, then hit F2 to rename the variable across your file.

3. Attempt the recommended instructions, they will not work. The correct default key combination is Ctrl + F2. 

Does this issue occur when all extensions are disabled?: Yes

Remediation:
1. The interactive playground page should be updated to reflect the accurate key combination, Ctrl + F2.

**Comment by fireattack** [comment]
F2 and Ctrl+F2 are not the same thing. 

![image](https://user-images.githubusercontent.com/4130991/93653063-eea2f600-f9dc-11ea-944b-a5dcc4d3d829.png)

F2 is "Rename Symbol", which should only rename the same symbol, while Ctrl+F2 is "Change all occurrence", which will blindly rename every single string that is same as the one you selected, not limited to that symbol. For example, it will rename the "anme" in comment as shown below:

![image](https://user-images.githubusercontent.com/4130991/93653115-1e51fe00-f9dd-11ea-9af1-b62d7cf09d6c.png)

The bug is that in Interactive Playground, for some reason "Rename Symbol" is broken (it is not in a normal JS file) and doesn't even show up. And it's still broken even after https://github.com/microsoft/vscode/issues/103213 (tested with newest Insider,  Commit: 403a6895f401c397933ec5c4f7d89432a33509b6).

So please re-open this issue, thanks!

**Comment by chrmarti** [comment]
Still doesn't work in the Interactive Playground. This works in 1.47 but no longer in 1.48. There is no Rename in the context menu or command palette. @mjbvz Could you advise on where to look?

**Comment by mjbvz** [comment]
40fc0b178934d236510231844de6008a81f221d0 re-enables semantic feature, such as rename, in the interactive playground. These were disabled when I was enabling js/ts support for serverless

**Comment by chrmarti** [comment]
That fixes it, thanks!

**Comment by alexr00** [comment]
Verified that this works now. This sentence it confusing though: "You can also see refactoring in the right click context menu". I right click for the context menu and see "Refactor...". I click that because the instructions say to. There is no rename there.

**Comment by chrmarti** [comment]
Thanks, updating to: You also have `Rename Symbol` in the right-click context menu.
