### ISSUE TITLE
Two Bugs in VS Code 1.48.1  "Unable to open Extensions" AND "Can't install Extensions"

### ISSUE THREAD

**Issue by KirolosAdlyKamel** [microsoft/vscode#105282]
- VSCode Version: 1.48.1
- OS Version: Windows 10 Pro 2019

Steps to Reproduce:

1. Unable to open the documentation of any Extension
2. Can not install any Extension automatically and I must download it manually

Does this issue occur when all extensions are disabled?: Yes
![image](https://user-images.githubusercontent.com/47532610/91032778-bdfcb600-e602-11ea-82bb-6a5af6109bb6.jpg)

**Comment by gjsjohnmurray** [comment]
Search here for "XHR failed" to find similar reports where the problems were caused by DNS issues.

**Comment by sandy081** [comment]
Please follow these steps

- Help -> Toggle Developer Tools -> Network
- Then check for any network failed requests while browsing and installing the extensions if found all requests fails then its probably a proxy or DNS issue at your end.
- To confirm its a DNS issue check if you can access this page https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default, if you cannot please try configuring your DNS like pointing to 1.1.1.1 as suggested here? https://1.1.1.1/dns/. Otherwise please contact your network administrator.
- If it is not a network issue, please share the logs from the following locations
    - Help -> Toggle Developer Tools -> Console
    - View -> Command Pallette... -> Toggle Shared Process -> Console
    - View -> Open View… -> Log (Shared)
    - View -> Open View… -> Log (Window)
