### ISSUE TITLE
Cannot read property 'getCell' of undefined at Object.t.convertLinkRangeToBuffer

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#105333]
Error telemetry shows a ton of exceptions around this:

`TypeError: Cannot read property 'getCell' of undefined at Object.t.convertLinkRangeToBuffer`

![image](https://user-images.githubusercontent.com/900690/91142529-3621b500-e6b1-11ea-8f3c-ebac3cd12873.png)

Unfortunately the sourcemaps do not seem to work properly, but looking at the code manually I see a lot of `line.getCell(x)!` usages. 

Whats the idea here to override strict null check?

**Comment by Tyriar** [comment]
The ! isn't the problem here, it's accessing line off the array:

https://github.com/microsoft/vscode/blob/c539d21915d729ff8f5e008e629f9bfabb30b621/src/vs/workbench/contrib/terminal/browser/links/terminalLinkHelpers.ts#L56

Related: https://github.com/microsoft/vscode/issues/102337, I missed the other case.
