### ISSUE TITLE
VSCode Smoke Tests: cell action execution

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#105330]
```
  1) VSCode Smoke Tests (Electron)
       VSCode Smoke Tests (Electron)
         Notebooks
           cell action execution:
     Error: Timeout: get text content '.notebook-editor .monaco-list-row.focused .monaco-editor .view-lines' after 20 seconds.
      at /Users/runner/work/1/s/test/automation/out/code.js:182:23
      at Generator.next (<anonymous>)
      at fulfilled (/Users/runner/work/1/s/test/automation/out/code.js:9:58)

```

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=85485&view=logs&j=3792f238-f35e-5f82-0dbc-272432d9a0fb&t=6ba55b26-6502-59ae-6c43-7e580fa53cb9&l=78

**Comment by roblourens** [comment]
This command doesn't work and I saw an error that implies that `cell.document` is undefined. 

```ts
context.subscriptions.push(vscode.commands.registerCommand('vscode-notebook-tests.debugAction', async (cell: vscode.NotebookCell) => {
		if (cell) {
			const edit = new vscode.WorkspaceEdit();
			const fullRange = new vscode.Range(0, 0, cell.document.lineCount - 1, cell.document.lineAt(cell.document.lineCount - 1).range.end.character);
			edit.replace(cell.document.uri, fullRange, 'test');
			await vscode.workspace.applyEdit(edit);
		} else {
			throw new Error('Cell not set correctly');
		}
	}));
```

I can repro this in OSS the second time I run the "Create New Notebook" command. So maybe it is a continuation of that issue you fixed earlier with ext host documents @jrieken

**Comment by jrieken** [comment]
How do I debug those tests? `cell.document` being undefined should not be possible, because `document` is computed when getting the cell and if that fails you should have no cell to begin with: https://github.com/microsoft/vscode/blob/f56b64cffbbd86ed346e2c7384d67a3b9d0fdc09/src/vs/workbench/api/common/extHostNotebook.ts#L118

**Comment by roblourens** [comment]
No need to debug the tests, it can be reproed in OSS. I see the problem is that the argument processor fails to find the ExtHostCell. This should probably return undefined when it fails, or it sends a confusing raw object to the command. 

![image](https://user-images.githubusercontent.com/323878/91887365-8cf23600-ec3f-11ea-9fa4-c71a32ffaa4f.png)

Steps

- Run "Create New Notebook" - this comes from the notebook test extension which is loaded in OSS just because it's in the extensions folder
- Create a new code cell, click the toolbar item with the "debug" codicon
- It changes the cell contents to "test" ✅ 
- Close the notebook
- Run "Create New Notebook" again, this wipes the file contents then reopens the notebook
- Create a new code cell, click the "debug" toolbar item
- It doesn't do anything 🐛

**Comment by jrieken** [comment]
I understand the problem in theory but I wasn't able to reproduce. Btw thanks for pushing https://github.com/microsoft/vscode/commit/3ab605c4dea5f3fbd2155ddb54729c9f45b31ccf - again the force of `any` strikes... 

I think the argument processor should loop over notebooks, not editors. Unsure if using the notebook handle is risky or not. 

Apart from all of this, I wanna spend to debt-cycles on the argument processor typings. It could be a little stricter and clearer so that it can express its intend better

**Comment by jrieken** [comment]
fyi - I have pushed ed9c404bf97573acf53ef902e3189bd3cd85849f to make the argument processor somewhat clearer

**Comment by jrieken** [comment]
Unsure if there is anything else left?

**Comment by roblourens** [comment]
I can't repro any issue using my steps above. I also can't repro the mysterious data loss issue I posted about in slack, and the test passes now. Assuming it's all related

**Comment by bpasero** [comment]
Failed today: https://dev.azure.com/monacotools/Monaco/_build/results?buildId=87771&view=logs&j=3792f238-f35e-5f82-0dbc-272432d9a0fb&t=6ba55b26-6502-59ae-6c43-7e580fa53cb9&l=81

**Comment by roblourens** [comment]
This is really annoying. Seems like it is failing in CI with some regularity but I can't repro locally. Maybe I can set it up to take screenshots, that would be useful here. Disabling.

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/126371
