### ISSUE TITLE
Webview with iframes debugging/inspecting partially broken

### ISSUE THREAD

**Issue by vidorteg** [microsoft/vscode#105370]
- VSCode Version: 1.48.2
- OS Version: Windows

Steps to Reproduce:

The "VS Code - Microsoft Edge (Chromium) Tools" extension development is partially broken, previously we were able to see console errors and associated resources but after we migrated to the new webview protocol it does not work anymore. Webview content gets redendered correctly but debugging/inspecting is broken. I think this is associated to using iframes inside a webview, I set up a small repro app that shows what I'm seeing.

1. Clone the following repository which  contains a Simple Repro App (Based on the sample-webview cat application):
https://github.com/vidorteg/webview-context-lost
2. npm install && npm run compile
3. Open VSCode > Debug > Run Extension
4. Run the Cat Coding: Start cat coding session to create the webview.
5. Verify that the view also shows an iframe embedded in the webview (with some content)
6. Open Developer Tools to debug the webview.

Expected
1. Should be able to select HTML elements inside the iframe
2. Should be able to see console context (errors and warnings)
3. Should be able to see resources associated with the iframe
All this is expected based on what is stated in here:
https://code.visualstudio.com/api/extension-guides/webview#inspecting-and-debugging-webviews

Actual
1. Cannot see HTML components in the Elements View or select them using the overlay tool
2. An error is thrown inside the script loaded in the webview but it is not shown on the Devtools Console (or anywhere)
3. Resource associated with the iframe (inspector.html) is not shown in the Devtools

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
You need to use the `Developer: open webview developer tools` command to debug webviews:

<img width="1072" alt="Screen Shot 2020-09-28 at 4 32 07 PM" src="https://user-images.githubusercontent.com/12821956/94496038-2a417b00-01a8-11eb-80e9-a7afed0385d1.png">

The normal developer tools do not show webview content in much detail

**Comment by vidorteg** [comment]
Hi Matt,
Yes, that is exactly what I'm using on Repro steps #6, please let me know if you need more details :)

**Comment by vidorteg** [comment]
Just realized that this is now closed,I think that it still requires some follow up as I'm still seeing the broken behavior on the latest stable. @mjbvz  is there any more information I can help with?

**Comment by mjbvz** [comment]
Are you sure because the description sounds like the wrong developer tools? Can you share a screenshot of when its not working

**Comment by vidorteg** [comment]
Hi @mjbvz,

I added some images to the steps on the original post, please let me me know if there is anymore information I can provide.

**Comment by mjbvz** [comment]
Thanks. That is the correct dev tools. I suspect the issue is related to using an iframe in a webview (which should be avoided when possible)

The dev tools come from Chrome (by way of electron) so this is not in the scope of VS Code itself. Marking as upstream

**Comment by vidorteg** [comment]
Hi @mjbvz 

Spent a little more time on this and did a finding I think is worth sharing. Please take this with a grain of salt as my knowledge on how vscode webviews and devtools interact is minimal.

I used "protocol monitor"(details below) in the devtools to compare the reply from the backend when inspecting the iframe in vscode webview and in the browser. 
I suspect the backend(vscode webview) is not providing the right content DOM in nodes that contain an iframe, in the next two images you can see the discrepancy (red box) when inspecting the same node in different scenarios. One of them (webview vscode) is not providing the contentDocument property for th enode.

Hosted in a browser
https://imgur.com/a/0tawxaZ

Hosted in vscode webview
https://imgur.com/a/iMMKm1x

Steps to get protocol monitor:
- Follow the original steps on this post.
- Once on the "webview developer tools" go to:
  - Settings
  - Experiments
  - Protocol monitor
- Relaunch the Devtools and go to the protocol monitor tool (in the "More Tools menu")
- Reload the webview from vscode (Developer: Reload webviews)
- Inspect the iframe node request and responses.

Please let us know if there is anything else we can do as this is blocking us from further development on the extension.

**Comment by DanTup** [comment]
I'm hitting issues with this too. Sometimes VS Code doesn't render our webview, it just gets a blue square. There are no script errors occurring and the app in the iframe is definitely initialising (I set the log level to trace and can see its console.info() logs). It would really help to be able to inspect the DOM (and see what that blue square is) to debug, but the webview devtools don't allow interacting with the iframe at all:

<img width="1537" alt="Screenshot 2020-10-27 at 10 47 01" src="https://user-images.githubusercontent.com/1078012/97291657-1d18ba00-1842-11eb-850d-1e19b9de5acf.png">

If this is an upstream issue, it would be good to raise upstream - however I don't really understand what's going on - since I can expand the first iframe (that VS Code adds), just not the inner one (that I add to host the app).

**Comment by GaryFNC** [comment]
Ran headlong into this same issue - we have an existing non-trivial app / editor that needs to work in the webview - not really a simple pattern to directly embed it into the webview.    And as others have noted, no way to see into the iframe to get any idea what is going wrong - so almost impossible to debug...     Conceivably, I could rollup the entire app and try to put it in a script, but it's a significant change to the app and a lot of added complexity just because of an inability to debug.

@mjbvz Is there any way to get this re-opened?   I didn't see any response to @vidorteg info on the contentDocument property...

Thanks

**Comment by tamuratak** [comment]
I have found that setting `"webview.experimental.useIframes": true` enables us to inspect DOMs in the iframe with `Developer Tool`, not with `Webview Developer Tool`.

See  #83188 for the experimental option.
