### ISSUE TITLE
Extensions have no chance to clean up on close

### ISSUE THREAD

**Issue by zawys** [microsoft/vscode#105484]
- VSCode Version: 1.49.0-insider
- OS: Linux x64 5.7.17-200.fc32.x86_64

### Steps to Reproduce:

1. Clone and open in VS Code: https://github.com/zawys/deactivate-test
2. `vsce package`
3. Install manually
  → "activate" is written everywhere as expected
4. Disable extension
  → "Reload required"
5. Reload (or Close)

### Actual result

```
$ cat /tmp/deactivate-test/fs_log
init
22217.216092680 activate A 
22217.216092680 activate C
22217.216092680 activate E
22223.367494563 deactivateInstant A 
22223.367494563 deactivateInstant C
22223.367829940 dispose A 
22223.367829940 dispose C

$ grep deactivate-test "$HOME/.config/Code - Insiders/User/settings.json"
    "deactivate-test.deactivate-test-activate": "22217.216092680",
    "deactivate-test.deactivate-test-deactivateInstant": null,
    "deactivate-test.deactivate-test-deactivateEarly": null,
    "deactivate-test.deactivate-test-deactivateLate": null,
    "deactivate-test.deactivate-test-dispose": null,

$ cat /tmp/deactivate-test/tee_log
22217.216092680 activate
```

Comment out the function call to `vscode.workspace.getConfiguration` in `log` and the output is:

```
$ cat /tmp/deactivate-test/fs_log
init
22109.498115667 activate A 
22109.498115667 activate C
22109.498115667 activate E
22133.232153312 deactivateInstant A 
22133.232153312 deactivateInstant C
22133.232153312 deactivateInstant E
22133.232600389 dispose A 
22133.232600389 dispose C
22133.232600389 dispose E
22133.283829548 deactivateEarly A 
22133.283829548 deactivateEarly C
22133.283829548 deactivateEarly E

$ grep deactivate-test "$HOME/.config/Code - Insiders/User/settings.json"
    "deactivate-test.deactivate-test-activate": null,
    "deactivate-test.deactivate-test-deactivateInstant": null,
    "deactivate-test.deactivate-test-deactivateEarly": null,
    "deactivate-test.deactivate-test-deactivateLate": null,
    "deactivate-test.deactivate-test-dispose": null,

$ cat /tmp/deactivate-test/tee_log
22109.498115667 activate
```

Observations:

- (1) Terminal processes are killed before extensions have any chance to do it themselves (more properly).
- (2) Setting configurations on exit/reload is not possible.
- (3) Trying to set configurations on exit/reload somehow stalls `setTimeout` handlers afterward.
- (4) The extension host process seems to be terminated instantly on reload when debugging an extension.
- (5) When not debugging, it seems to have around 5s of time until forcibly terminated, so the `deactivateLate` part is never executed.
- (6) Disposing and `deactivate` are executed in parallel.

### Expected result
- (1) & (2). Give extensions time to do finishing operations on the UI, like closing windows, exiting terminal process, changing configuration.
- (3). Operations should fail with an expressive exception when not available.
- (4). Maybe ok, but that leads to workspace pollution while debugging.
- (5). Ok, but should be documented.
- (6). (Sync) disposing should be executed before (async) `deactivate`.

### Remarks

I need it for an extension’s cleanup tasks, else some temporary files will pollute the repository.

**Comment by weinand** [comment]
Did you verify that your extension was actually activated?

**Comment by zawys** [comment]
Hi!
> Did you verify that your extension was actually activated?
Now yes. I created a test extension and updated the description.

**Comment by zawys** [comment]
The current workaround for my extension is to use `ExtensionContext.globalState` to keep continuously stored what should be cleaned up under what circumstances and do that when VS Code starts. However, that does only limitedly work for terminal processes and requires that the extension is activated at startup.

**Comment by alexdima** [comment]
@zawys Your observations are correct, but the behaviours you have noticed are as designed. 

A VS Code window is backed by a renderer process and an extension host process. Terminal processes are spawned from the renderer process via the extension host API (vscode.d.ts). Most of the extension host API is actually serviced by the renderer, so for example when an extension wants to create a new terminal, a message is sent to the renderer and the renderer does it. Or when an extension wants to write to the user `settings.json`, a message is sent to the renderer and the renderer does it, etc.

When closing the window, the renderer process goes down **immediately**. The extension host process becomes orphaned and has 5 seconds to go down. The renderer process does not wait for extensions in any way.

This is an intentional design decision we took. When we designed this, we have suffered multiple times as operating systems would not shut down, especially when needing to leave and catch a train, etc. Always the reasons appear to be important: an update had to be applied, an application would veto the shutdown, etc. But in comparison with missing the train, that is not so important at that time. We have decided that VS Code should not be like that. As a user, if I close VS Code, it must go down ASAP.

This requirement hits extensions and it means that extensions must be authored with this constraint in mind. Deactivate is not a time to write to user settings. To be honest, the reason we have deactivate is for e.g. cleaning up costly things, like e.g. suppose a server is up and running somewhere and must be shut down, a quick http request can be made, etc. All the rest of the things must be resilient to crashes anyway, so spawned processes must be ready that the extension host process is brutally killed anyways.

**Comment by zawys** [comment]
Thank you very much for your detailed reasonable explanations!

Now I found `createTerminal(options: ExtensionTerminalOptions): Terminal`, which allows to spawn the "fragile" process on the extension host and forward in and output between the renderer and the fragile process (via the extension host). I think, that should do it.

The [documentation on the exit procedure](https://code.visualstudio.com/api/references/activation-events#onStartupFinished) could be extended, though.

**Comment by zawys** [comment]
@alexdima Could you please remote the “needs more info”?
