### ISSUE TITLE
Param helper hover getting cut off at bottom

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#105422]
Helper for `new SecretClient` from https://www.npmjs.com/package/@azure/keyvault-secrets

![image](https://user-images.githubusercontent.com/2193314/91312200-d1c22c80-e768-11ea-9d1d-03f35b164cf0.png)

Looks like just the last line is cut off?

![image](https://user-images.githubusercontent.com/2193314/91312298-f0282800-e768-11ea-8e3a-c389d543a149.png)

**Comment by mjbvz** [comment]
Do you believe this changed recently, such as with the electron 9 update?

**Comment by Tyriar** [comment]
I wouldn't have expected that, I'm also pretty sure my hover changes didn't touch any styles that could affect this either. Perhaps it's related to some top/bottom padding not being factored into something?

**Comment by chenjigeng** [comment]
I think the reason for this problem is that the above signature was not taken into account when calculating the scroll height. 
![image](https://user-images.githubusercontent.com/14784326/101340132-4d7c5b00-38ba-11eb-898a-ea76c38ee51f.png)
I want to see if I can fix this problem, can you tell me where the scroll height was calculated. @Tyriar @mjbvz

**Comment by chenjigeng** [comment]
I think it's because codeBlock generation is an asynchronous process.Before the result is returned, a pure code text is set synchronously which results in the outer layer getting the wrong height
![image](https://user-images.githubusercontent.com/14784326/101354798-ad7dfc00-38d0-11eb-9ec5-8e649452a3b5.png)

**Comment by chenjigeng** [comment]
I found that the markdownRenderer supports the asyncRenderCallback option, so we can just pass this option and call scanDomNode again after the asynchronous rendering.
I try and it work. Please check this PR @mjbvz @Tyriar
