### ISSUE TITLE
Emmet CSS: NaN is suggested by IntelliSense as value

### ISSUE THREAD

**Issue by infinnie** [microsoft/vscode#105697]
![image](https://user-images.githubusercontent.com/8168391/91676879-cf4e4100-eb73-11ea-94f4-2ab618b7d82f.png)

- VSCode Version: 1.48.2
- OS Version: Windows 7

Steps to Reproduce:

1. Create a CSS file.
2. Type `opa.` within a CSS rule.

Does this issue occur when all extensions are disabled?: Yes

**Comment by rzhao271** [comment]
I am wondering what should be suggested instead for `opa.`?
I noticed when `opa1` is typed it suggests `opacity: 1;`, so it looks like it's trying to parse the period.

Keeping this issue as a bug because #107578 (duplicate) is still unresolved.

**Comment by infinnie** [comment]
@rzhao271 May you reopen it?

**Comment by rzhao271** [comment]
I'll reopen if you give a suggestion for what should be suggested instead.

**Comment by infinnie** [comment]
> I'll reopen if you give a suggestion for what should be suggested instead.

Maybe something like `<property name>: <caret position>`

**Comment by rzhao271** [comment]
`opacity: |;` makes sense, though I just noticed Sublime does `opacity: .;`.
I think the latter option is pretty good, because then the user can type a number like 5 and it would update to `opacity: .5;`.
Another point is that VS Code Emmet shouldn't automatically attempt to parse the value into a number anyway

Anyway, back to reopening this issue. Sorry about that

**Comment by rzhao271** [comment]
\closedWith dc5a3da
