### ISSUE TITLE
TypeScript QuickInfo should not wrap in the middle of an operator

### ISSUE THREAD

**Issue by amcasey** [microsoft/vscode#105630]
Version: 1.48.2 (user setup)
Commit: a0479759d6e9ea56afa657e454193f72aef85bd0
Date: 2020-08-25T10:13:11.295Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

![image](https://user-images.githubusercontent.com/10508071/91625498-b881d180-e95c-11ea-99a8-d31884dce749.png)

Breadcrumb for myself, in case a repro is required: I was reducing material-ui for abug.

**Comment by amcasey** [comment]
FYI @mjbvz

**Comment by Zuckjet** [comment]
Thanks for your great project, I would like to try to fix this issue. Before I begin to do, I want to have a discussion there.

my idea for fixing this issue is that:
I will check the current string(in this issuse is '=>') whether hit the scopes(produced by vscode-textmate) such as "keyword.operator.xxxx" defined in TypeScript.tmLanguage.json file.
But the problem is that we can't get scopes info, because we don't allow use tokenize but can ony use tokenize2(because of performance reason): https://github.com/microsoft/vscode/blob/1025f4aae70267a81dd8b2023f27c88517902025/src/vs/workbench/services/textMate/browser/abstractTextMateService.ts#L448-L450
So in my opinion,  this idea seems not the right fix for the issuse, right ?

If so, how about just detect whether the current string is typescript operator, such as `ts.isOperator(string)` through typescript api(I am not sure this api is really exist) ? @alexdima @jrieken

**Comment by alexdima** [comment]
@Zuckjet Doing a fix specific about the token scope list would make this change tied up to TextMate, while the editor itself supports another tokenization engine named Monarch, which does not produce scope lists. 

What I find interesting is that our wrapping computer does a lot better in this case:

![Kapture 2020-09-16 at 17 55 54](https://user-images.githubusercontent.com/5047891/93362183-f9775280-f845-11ea-91d4-3d292fcb89d2.gif)

Even when using the wrapping points computed by the browser via `"editor.wrappingStrategy": "advanced"`, that symbol is not broken:

![Kapture 2020-09-16 at 17 57 37](https://user-images.githubusercontent.com/5047891/93362307-2166b600-f846-11ea-8d0f-6fd251004f75.gif)

So I believe there might be something off in the CSS of the hover widget that is causing the browser to break in the middle of `=>`. When computing wrapping points via the browser, [here](https://github.com/microsoft/vscode/blob/d80f324ecb0958a7936c488ce3b330b8531ae457/src/vs/editor/browser/view/domLineBreaksComputer.ts#L114) is the CSS we use for `word-wrap`. Perhaps the hover widget is using something else that would cause such behavior?

**Comment by Zuckjet** [comment]
Thanks for offering these information. It seems I misunderstood this issue before. the message "TypeScript QuickInfo should not wrap in the middle of an operator", make me think I need only handle the operator not other single word, this make things more complicated. So I just remove relevant css as you suggested

**Comment by alexdima** [comment]
I did a quick blame on the CSS and it looks like it was introduced via https://github.com/microsoft/vscode/pull/74582
