### ISSUE TITLE
Integrated PowerShell not working properly

### ISSUE THREAD

**Issue by anshdhinhgra47** [microsoft/vscode#105710]
- VSCode Version: 1.48.2
- OS Version: Windows_NT x64 10.0.18362

Steps to Reproduce:

The integrated PowerShell kills the server even after accepting n/N as an input. An image for reference is attached below.

![PowerShell-error](https://user-images.githubusercontent.com/56676059/91695822-57d8db80-eb8c-11ea-90cb-cf37f7c549b3.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to our code. As such, I will go ahead and close it. Please try to reproduce in [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal-preview/9n0dx20hk701) and report to [microsoft/terminal](https://github.com/microsoft/terminal) with repro steps.

Thanks for understanding.

**Comment by anshdhinhgra47** [comment]
Sure.
