### ISSUE TITLE
Theme: implement and adopt service for handling ColorSchemes (dark, light, hc)

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#105715]
The idea is to introduce central methods in `IHostService` to:
- figure out the current color scheme
- register to events when color schemes change

Idea for `ColorScheme` is an enum of:
- `DEFAULT`
- `DARK`
- `HIGHT_CONTRAST`

Implementation depends on the runtime:
- `Electron`: `nativeTheme` allows to figure out high contrast and dark scheme preference
- `Browser`: we can currently only detect preference for dark theme via a CSS check

**Comment by bpasero** [comment]
@aeschli please check https://github.com/microsoft/vscode/pull/105716 for a first cut of support in the `IHostService`. Unfortunately I was not able to move the listener into `IThemeService` due to some cyclic dependencies, so maybe we have to put this into a separate workbench contribution that gets instantiated in the right lifecycle phase.

Things to do:
- move into theme component
- properly listen to dark theme changes in native environment
- figure out if we can support color scheme changes and HC detection logic somehow into the browser

**Comment by aeschli** [comment]
We now have a separate `IHostColorSchemeService` with a browser and electron variant.

The browser uses the experimental force-colors to detect hc: https://drafts.csswg.org/css-color-adjust-1/#forced-colors-mode
Forced colors is already enabled in Edge, and can be enabled in Chrome.
We also now set the rule `forced-color-adjust: none` so that we stay in control of all the colors.

**Comment by bpasero** [comment]
I suggest to either put this on test plan or verify.

**Comment by aeschli** [comment]
I'll put this on the test plan, there's enough to test
