### ISSUE TITLE
Search sentence broken into multiple lines.

### ISSUE THREAD

**Issue by tjustel** [microsoft/vscode#105766]
- VSCode Version: 1.48.2
- OS Version: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. Open any text file.
2. Type a sentence and break it into 2 lines.
3. Type this sentence in search bar (with regular expression mode disabled).
4. It does not appears in search results.

![research_failed](https://user-images.githubusercontent.com/34620135/91772307-ec6f2800-ebe4-11ea-8b73-5d55c58e7b02.JPG)

Does this issue occur when all extensions are disabled?: Yes.

It does not make sense that a sentence broken into two lines does not appear in search result when typed into the search bar. If one really wants to research only unbroken sentences they can use the regular expression search mode. What is currently implemented forces users who want to find all chains (including ones broken into multiple lines) to use the regular expression mode and I think this use case is the most frequent.

**Comment by tjustel** [comment]
Maybe a parameter in users settings that allows to set up this kind of behavior ?

**Comment by rebornix** [comment]
This is by design, we only search for what you type in. The multiple line text contains line break so it won't match.

If you want to search for multiple line in particular, you can do that also in the Find Widget

<img width="1220" alt="image" src="https://user-images.githubusercontent.com/876920/91895736-93d37580-ec4c-11ea-9447-af754a1db355.png">
