### ISSUE TITLE
Add event listeners to vscode.Tunnel

### ISSUE THREAD

**Issue by xisui-MSFT** [microsoft/vscode#105754]
Not sure if this is feasible, but it would sometimes be very helpful if there can be such listeners. One example is, when using gdb protocol, [server sends ACK upon connection and expect an ACK back] (https://sourceware.org/gdb/onlinedocs/gdb/Packet-Acknowledgment.html#Packet-Acknowledgment). Currently we need to write an intermediate server to do this. It would be a lot easier if there can be an onConnectToRemoteEnd listener.

**Comment by alexr00** [comment]
This is an interesting request. The original intent behind `openTunnel` was for forwarding ports that something is running on in the remote to the local setup for direct user access. This would be useful because there could be process running that an extension knows the user will want access to. Because ports forwarded like this are intended for user use, they all show in the Forwarded Ports view.

**Comment by xisui-MSFT** [comment]
Thanks for the response! A clarification, the 'onConnect' I said above is 'onConnectToRemoteEnd' (I'll change the original ticket as well). But 'onConnectToLocalEnd' could also be useful. And the same for many other events, both sides need to be considered. However, as you said, each event needs to be evaluated, so its function wouldn't be too far from a 'tunnel'.
