### ISSUE TITLE
Output bounces on update

### ISSUE THREAD

**Issue by colombod** [microsoft/vscode#105884]
- VSCode Version: 1.49.0 Insider
- OS Version: Win10 
Open a .NET Interactive notebook with ```#r``` produces bouncing output

![bug_output](https://user-images.githubusercontent.com/375556/91906826-be4f1e00-eca0-11ea-88c4-e02e79996a3c.gif)

@rebornix , @jrieken

**Comment by rebornix** [comment]
We are seeing this issue as the first output is a HTML output who intends to be "hidden" (`display: none`) but we have paddings around the output so its container has some height.

<img width="439" alt="image" src="https://user-images.githubusercontent.com/876920/91914781-baee6f00-ec6d-11ea-81a9-709802a71f27.png">

And we are seeing the flickering because the HTML outputs are sometimes inserted but sometimes not.

@colombod can you help us understand what's the condition of when the first html output should be in the `outputs` property and when not?

**Comment by colombod** [comment]
In .NET Interactive the first cell executed will inject that hidden Dom element that is needed to perform part of our http hand shake protocol to setup the environment used for the polyglot cells and js api for interoperability. @Brettfo also can help explain this part. This is how the kernel will know on what endpoint the fronted is able to talk back to it over http on a random port that is not known until the kernel is up and running.

**Comment by roblourens** [comment]
It seems like we might want to just get rid of padding on outputs. If jupyter allows 0-height outputs, we should too. But it's a little suspicious how that output is added and removed over and over?

**Comment by colombod** [comment]
we do not add or remove it, we set the output list for the cell

**Comment by rebornix** [comment]
Fixed via 6026ab576dc6a4fbb8e255241a364816f42464c5.
