### ISSUE TITLE
Notebook cell execution model

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#105847]
Somewhat a continuation of https://github.com/microsoft/vscode/issues/103713

Today, execution results are parts metadata and output and execution itself is done via kernels which come from kernel providers. We should try to model execution results into a single entity, e.g execution status (idle, running, scheduled? etc)

**Comment by jrieken** [comment]
One thing that we should do is to allow the `executeCell`-functions to return a promise. The promise should resolve that execution has been successfully _started_. It would allow to show feedback on the run button in cases in which the kernel needs to be resolved or isn't idle. 

<img width="596" alt="Screenshot 2020-09-21 at 11 41 29" src="https://user-images.githubusercontent.com/1794099/93752922-a44d8f00-fbff-11ea-85a4-5cf6ecc52101.png">

**Comment by roblourens** [comment]
Some execution API TODOs that I didn't have time to put into code, including some suggestions from Kai a few weeks ago

- Rethink naming to be more explicit in the intent. Write all the jsdoc to explain the usage to check whether a normal person can follow the flow. Get someone else on the team to review it. Check which words are used in the explanation and use those in names.
  - Should the execution object be called "execution", maybe it is a "task".
  - "executeCells" could be "executeCellsRequest" because it really is just a request
- Normalize "run" vs "execution" name
- `createNotebookCellExecution` - only a kernel can access this, and only the active kernel can trigger an execution.

**Comment by roblourens** [comment]
Two things not in the PR

- Preemptively setting a cell as "pending" as soon as it is clicked, not having to wait for a Task to be created. We discussed this some, but in trying to implement it and explain it in the API jsdoc, I was wondering whether it's really worth the extra complexity. Will leave it alone for now until we really think it's an issue.
- Canceling executions when a cell is deleted. Just because I'm not sure of the right place to implement this. https://github.com/microsoft/vscode/issues/119504

**Comment by roblourens** [comment]
@jrieken maybe you can call this verified since you implemented it and filed some issues
