### ISSUE TITLE
debugProtocolVariableMenuContext is not robust

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#105810]
Testing #105593

In Mock Debug I've added a `"__vscodeVariableMenuContext": "simple"` on the integer variables ("local_i") [here](https://github.com/microsoft/vscode-mock-debug/blob/f4b0e37cfd0cb1653c82a26bdab4910c87489713/src/mockDebug.ts#L302) and the corresponding "when" clause in the [package.json](https://github.com/microsoft/vscode-mock-debug/blob/f4b0e37cfd0cb1653c82a26bdab4910c87489713/package.json#L83).

But the menu contribution is not showing up in a robust way on the correct Variable.

- checkout Mock Debug latest
- F5
- start "mock debugging" a readme.md
- in the Variables view open context menu on "local_i"
- Observe: no "Show As Hex" is shown
- open context menu on "local_f"
- Observe: "Show As Hex" does shown
- open context menu on "local_f" again
- Observe: no "Show As Hex" is shown

![2020-09-01_12-40-38 (1)](https://user-images.githubusercontent.com/1898161/91840799-92587c00-ec51-11ea-9913-9d1a9c0448fd.gif)

Expected:
"Show As Hex" is shown for "local_i" in a robust way

**Comment by isidorn** [comment]
Great catch.
The issue seems to be a timing wise: now I simply set the context a bit earlier in the code and I can no longer reproduce this.
I find that this was not working weird since all the methods were sync. So maybe some of them were lying, and the contextKey.set needs some time to propage.

Anyways with the fix I can no longer repro this. I always get your action on `local_i` and not on the other variables.

**Comment by weinand** [comment]
"setting the context a bit earlier in the code" sounds a bit dangerous.
With a fast machine "a bit earlier" might not be "early enough"...

**Comment by isidorn** [comment]
This is how we set context keys in all other cases (explorer, variables, open editors). So I believe it should be fine.

**Comment by weinand** [comment]
Seems to work fine now.
