### ISSUE TITLE
When clause not respected

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#105828]
Testing #105593

```
	"contributes": {
		"commands": [
			{
				"command": "105593.helloWorld",
				"title": "Hello World"
			},
			{
				"command": "105593.helloWorld2",
				"title": "Hello World 2"
			}
		],
		"menus": {
			"debug/variables/context": [
				{
					"command": "105593.helloWorld"
				},
				{
					"command": "105593.helloWorld2",
					"when": "editorLangId == typescript"
				}
			]
		}
	},
```

but the menu item is missing when hitting a breakpoint in a TS file

<img width="940" alt="capture" src="https://user-images.githubusercontent.com/1931590/91853043-ec613d80-ec61-11ea-946c-8a330809b256.png">

**Comment by isidorn** [comment]
Thanks for trying it out. However the issue here is that the `editorLangId` context is only set on the editor and when you invoke the Variables context menu focus is no longer in the editor and this key is unset.
To prove all is good I have used a different context key and everything worked just fine.
Due to this closing this issue. Feel free to reopen if you still think there is a problem.

```
{
					"command": "extension.helloWorld",
					"when": "activeViewlet == workbench.view.debug"
}
```

**Comment by weinand** [comment]
The general question behind this problem is: what context keys are considered part of a specific context?

Since the context is defined by the client of the context (here debug's variable view), it is not obvious for users what keys are available and what are not.

It would be great if code assist in the editor could help here.
