### ISSUE TITLE
Debugger shows wrong value of a C# property when hovered

### ISSUE THREAD

**Issue by anass-b** [Microsoft/vscode#10580]
- VSCode Version: 1.4.0
- OS Version: OS X 10.11.5

It seems that the debugger is showing the wrong value of a C# property when hovered.
As shown in the screenshot, the value of SomeProperty is false, but VSCode shows true while hovering.

Screenshot:
![vscode_bug](https://cloud.githubusercontent.com/assets/8070594/17698049/1199e3a8-63b9-11e6-9ab9-5113294c2eaa.png)

I'm wondering if this is connected to this issue: https://github.com/Microsoft/vscode/issues/9290, and if this bug has to do with the C# extension of VSCode or with VSCode itself.

Steps to Reproduce:

1. Create an empty .NET Core App
2. Use the code in the screenshot
3. Put a breakpoint after the line that says in a comment `// Put breakpoint here`
4. Hover on `SomeProperty` in the line `if (someNumber > 1 || !someValue.SomeProperty)`

Thanks.

**Comment by alexandrudima** [comment]
@isidorn Maybe some caching issue?

**Comment by isidorn** [comment]
This is the issue with the C# extension, can you please file an issue here: https://github.com/OmniSharp/omnisharp-vscode

The problem is that the C# extension evalutes the hovered expression on hover, thus the negation is also evaluted and you get the wrong result. There is also a PR in progress that might take care of this issue https://github.com/Microsoft/vscode/pull/9821

**Comment by anass-b** [comment]
@isidorn Thanks. I filed an issue in the C# extension's repository: https://github.com/OmniSharp/omnisharp-vscode/issues/697

**Comment by gregg-miskelly** [comment]
@isidorn this is an issue with VS Code. But I believe you are correct that #9821 will resolve this.
