### ISSUE TITLE
Can't debug builtin extensions

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#105859]
- Start the "Renderer and Extension Host" launch config in vscode
- Set a breakpoint in a .ts file in a builtin extension under `./extensions`
- It doesn't bind, but I can set breakpoints in the .js files

**Comment by roblourens** [comment]
So it doesn't load the sourcemaps at all unless they are in outfiles? I thought that is only used for pre-loading.

**Comment by connor4312** [comment]
We should load at runtime as well. I'll look at that.

**Comment by connor4312** [comment]
Oh, yea. By default, now for Node we set `resolveSourceMapLocations` to the `outFiles` (if it's unset). So because we specified outfiles to use `out/**/*.js`, js-debug saw the sourcemap for the extension was outside of there and didn't resolve it.

I think this is good behavior, actually. It makes things more deterministic -- if you set a breakpoint, in a file, we know that it will get bound and hit consistently, or it won't. Previously, poor configurations were 'hidden' by the runtime loading -- we'd hit the BP if we were able to load sourcemaps fast enough, but we might miss it sometimes.

**Comment by roblourens** [comment]
I think that does make sense. If I don't set outFiles, we do the best we can. If I set outFiles and it's wrong, we don't bind breakpoints in files that are missed by outFiles. I like things being deterministic.

**Comment by kennyyyb** [comment]
I was also having this issue when I upgraded to 1.49.0.

My use case was debugging mocha tests. 

The fix for me was to add `"outFiles": ["${workspaceFolder}/dist/**/*.js"]` to my lauch.json configuration. N.B., my tsconfig.json has `"outDir": "dist"`. 

```
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "args": ["--timeout", "999999", "--colors", "${workspaceFolder}/test"],
      "internalConsoleOptions": "openOnSessionStart",
      "name": "Mocha Tests",
      "program": "${workspaceFolder}/node_modules/mocha/bin/_mocha",
      "request": "launch",
      "skipFiles": ["<node_internals>/**"],
      "type": "pwa-node",
      "outFiles": ["${workspaceFolder}/dist/**/*.js"]
    }
  ]
}
```

As a side note, when I use "Add Configuration" --> "Node.js: Mocha Tests" the config added to launch.json includes: `      "args": [
        "-u",
        "tdd",
        "--timeout",
        "999999",
        "--colors",
        "${workspaceFolder}/test"
      ],`

I have to remove the "-u" and the "tdd" for the debug to work.
