### ISSUE TITLE
tasks.json showOutput IntelliSense shows silent as the default

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#10595]
- VSCode Version:1.4.0
- OS Version:Windows 7

Steps to Reproduce:

1. Hover over tasks.json showOutput variable. Text says "...If omitted, 'always' is used."
2. Now show suggestions for showOutput and down arrow to 'silent'. "Default value" is shown.

I believe the default is 'always'.

**Comment by dbaeumer** [comment]
@aeschli the message comes from the json schema / extension. What I do is the following (example for a Boolean). if the programmatic default is false then I set the json default in the schema to true so that if a user selects it from code compete, code complete inserts true. The idea behind this is that if the user inserts it he will very likely want a different value than the programmatic default. My question: can I control this in any other way. Could we tweak the json message. Or should we have two: default and code complete default properties on the schema?

**Comment by aeschli** [comment]
Maybe better don't use default then, but enums. The completion will take the first one.

**Comment by dbaeumer** [comment]
Hard to do with booleans. Possible with the showOutput value with is already an enum. But picking the first one is actually not what I want to do either (I sorted them by output impact and always is the first). @aeschli  Could we extend the json schema with a property to control this ?

**Comment by aeschli** [comment]
Boolean also can define an enum set ('true', 'false'). Why would the order in the enum sets matter? The code completion UI will resort them alphabetically anyway.
What would the name of the property be (and what would the specification of that property be?)

**Comment by dbaeumer** [comment]
The sorting is actually a good point. I will remove the default property then.

**Comment by dbaeumer** [comment]
Fixed for 1.5.
