### ISSUE TITLE
Markdown cell header styling

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#105900]
Testing #105769

H4 Markdown elements are rendered in bold which looks out of place when all other text elements are regular weight.

![image](https://user-images.githubusercontent.com/12818376/91925928-ecc1fe80-ec8a-11ea-9656-efa53375bd36.png)

**Comment by roblourens** [comment]
The normal markdown preview styling looks more consistent:

![image](https://user-images.githubusercontent.com/323878/92010235-6ba44f00-ecfe-11ea-9718-46a3050519ba.png)

than the notebook:

![image](https://user-images.githubusercontent.com/323878/92010286-7b239800-ecfe-11ea-8fca-ac9d82801de9.png)

**Comment by bheston** [comment]
I was looking for an issue tracking markdown preview formatting because headings are hard to distinguish. This issue wasn't opened very long ago, but I'm seeing different results with the default included preview:
![image](https://user-images.githubusercontent.com/47367562/94977595-5291e800-04ce-11eb-8426-1317f5b147dd.png)

Building from the convention in html, as well as common / classic heading formatting, they _should_ be bold. As you can see in this example h4 text is indistinguishable from plain text.

I didn't find any configuration to customize this, but VS Code default should be more like conventional markdown styling.

**Comment by mjbvz** [comment]
Here's an updated comparison of notebook markdown vs markdown preview:

![Screen Shot 2021-11-05 at 3 42 20 PM](https://user-images.githubusercontent.com/12821956/140586294-8634470f-ac0e-4f0d-b75a-83e4ecff44e3.png)


The bold styling in the notebook comes from the user agent. We override it for the md preview

Here's the tweaked version:

![Screen Shot 2021-11-05 at 3 55 29 PM](https://user-images.githubusercontent.com/12821956/140587101-6820478d-379e-44db-8d7e-183d5ac758b2.png)

**Comment by rzhao271** [comment]
LGTM, though a nitpick is that h6 is very tiny for Markdown notebook cells.
![Example](https://user-images.githubusercontent.com/7199958/144114169-30ce721d-1f9a-4d74-ac51-f82e76a58957.PNG)
