### ISSUE TITLE
The window is no logner responding

### ISSUE THREAD

**Issue by tvprasad** [microsoft/vscode#105945]
- VSCode Version:Version: 1.48.2 (user setup)
Commit: a0479759d6e9ea56afa657e454193f72aef85bd0
Date: 2020-08-25T10:13:11.295Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.17763
- OS Version: Windows 10 Ent

Steps to Reproduce:

1. Open command prompt in Elevated (Administrator) level
2. Navigate to source location
3. type code . to open VS Code
4. Open Terminal and run angular and nodejs code
You may use two terminals or split option
5. For angular 
> ng build --output-path ../backend/dist --watch=true

7. For nodejs
> node --inspect server.js
![no longer responding](https://user-images.githubusercontent.com/915494/91992352-094d4d80-ed02-11ea-95d3-969d526a4133.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by reallydivs** [comment]
No it does not occur when all extension are disabled, and you may need to check if running vscode from a admin prompt might be causing the issue as some files might be locked by windows and that is causing the app to crash.

**Comment by weinand** [comment]
@tvprasad It is possible that this issue is caused by an installed extension. Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.
