### ISSUE TITLE
Opening link in Markdown file wrongly decodes %2F

### ISSUE THREAD

**Issue by mhchem** [microsoft/vscode#106097]
Issue Type: <b>Bug</b>

- Open a new editor of type Markdown
- Paste a link including %2F, e.g. `[test](https://example.com/This%20is%20a%20test%20with%2F%20in%20the%20URL)`
- Ctrl-Click or Cmd-Click the https link and open it in a browser
- The %2F is wrongly decoded before the URL is handed to the browser

(This does not occur when clicking the link in the Markdown preview.)

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.18363

**Comment by jeanp413** [comment]
I was taking a look at this and found this is related to #85930

**Comment by tomerstav** [comment]
> I was taking a look at this and found this is related to #85930

Seems to be related to a larger issue #79474

**Comment by mjbvz** [comment]
Based on #79474 and #83645, I think this is a limitation of `vscode.Uri` and not something we can easily work around in the markdown extension (right now we use `vscode.Uri.parse` but I also tried using `.with`, which seems to cause its own set of issues)

I'm going to close this issue since it has not gotten much attention since it was opened, but if anyone still wants to try looking into this, we'd still take PRs
