### ISSUE TITLE
IntelliSense not Working in VS Code

### ISSUE THREAD

**Issue by vinaykeenable** [microsoft/vscode#106034]
For any case, if i'm trying to use auto complete word or suggestion, It is not working. Could you help me on this?

**Comment by vinaykeenable** [comment]
I have checked multiple on GitHub, but those are not valuable for me.

**Comment by jrieken** [comment]
> Could you help me on this?

Sorry, I cannot help you because your issue contains absolutely nothing that would allow me to understand or reproduce the problem you are having. 

So, please update this issue after reading https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests.

**Comment by vinaykeenable** [comment]
@jrieken 
I'm sharing required detail such as Extensions details and screenshot of auto suggestion not working.

VS code version: 1.48.2

[Installed_Extensions.xlsx](https://github.com/microsoft/vscode/files/5168540/Installed_Extensions.xlsx)
![Proof_of_autosuggestion_not_working](https://user-images.githubusercontent.com/70699315/92116389-6552c780-ee11-11ea-984b-4f1e82456cf3.png)


Issue is not related to particular Extension, it is for all Extensions. I have taken one example by sharing screenshot.

**Comment by jrieken** [comment]
Please read again https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests.
