### ISSUE TITLE
How to remove action button and add new action button in breakpoints viewlet's action bar?

### ISSUE THREAD

**Issue by Nina0408** [microsoft/vscode#106263]
Hi there,

I have some requests as below:

1.  How to add a new action button and remove a existing action button from breakpoints viewlet's action bar?
2.  How to customize the workflow of  persisting breakpoint locations after debug session ended ?

I have not found any doc about it, Please help, Thanks very much!

**Comment by isidorn** [comment]
1. Not possible. Breakpoints action bar is not contributable to. Though I know @connor4312 wanted something like this
2. Can you clarify this please, I do not know what you mean?

Are you writing an extension or?

**Comment by connor4312** [comment]
> Though I know @connor4312 wanted something like this

For my need I opened a DAP proposal (https://github.com/microsoft/debug-adapter-protocol/issues/137) since it was a generic behavior and adding a button to the breakpoints view would not have been sufficient -- I also wanted to show these breakpoints, which is a large surface area that's not contributable to right now. I wonder if @Nina0408 will face the same issue...

**Comment by Nina0408** [comment]
Thanks @isidorn 
@connor4312 My request is to remove the "add function breakpoint " action button and add "remove the selected breakpoints" action button in below action bar.
<img width="616" alt="屏幕快照 2020-09-09 上午9 18 56" src="https://user-images.githubusercontent.com/20856567/92543340-c3eacc00-f27d-11ea-9698-b3f9c3ab6510.png">

My second issue is after the debug session ended, vscode will save the current breakpoint locations by itself, and at the next debugging session, the breakpoints will be added to the corresponding file automatically by current default scenario.
and I would like to injest my own code logic to do some customizing about saving the breakpoint locations.

Thanks!

**Comment by weinand** [comment]
@Nina0408 yes, VS Code deletes breakpoints when the underlying file is deleted (or renamed).
Instead of deleting the file you could just replace  the contents. The the breakpoint will be preserved.
Or you can re-create the breakpoints through the extension API `vscode.debug.addBreakpoint`.


@isidorn please correct me if my suggestions from above are incorrect.
BTW, breakpoints are lost if a file is renamed. Why are we not updating the breakpoint instead?

**Comment by Nina0408** [comment]
@weinand Thank you for your suggestion, I will try this API vscode.debug.addBreakpoint.

**Comment by isidorn** [comment]
@weinand yes you are correct.
When the file gets renamed we probably get a delete event from the underlying `fileService` and we get rid of the breakpoints. There probably is not a rename event and that is the reason why we do not just update the breakpoints.

**Comment by Nina0408** [comment]
Hi @weinand ,

As you suggested, use API`vscode.debug.addBreakpoints ` in DAP to reloaded the breakpoints.  

So when the debuggee file is deleted, I plan to save the breakpoints line number list into a local file.
And next time , when the debuggee file is recreated, I will can `vscode.debug.addBreakpoints ` to re-add the breakpoints.

But after I checked the api doc as below:
<img width="685" alt="屏幕快照 2020-09-11 下午1 55 36" src="https://user-images.githubusercontent.com/20856567/92870509-84b3ab00-f436-11ea-9a7a-56dcce18c923.png">

The keys of input parameter "Breakpoint" as below, There is no key for line number 
<img width="766" alt="屏幕快照 2020-09-11 下午1 57 05" src="https://user-images.githubusercontent.com/20856567/92870750-c5abbf80-f436-11ea-89aa-0dce520d5f6b.png">

Please advice, Thanks!!

**Comment by weinand** [comment]
`Breakpoint` is the base class of all breakpoint types. You are interested in `SourceBreakpoint`.

**Comment by Nina0408** [comment]
@weinand I see, Thank you very much!
