### ISSUE TITLE
Typescript language server errors for virtual files from SCM providers (e.g. hg extension)

### ISSUE THREAD

**Issue by DavidGoldman** [microsoft/vscode#106299]
- VSCode Version: 1.48.2
- OS Version: macOS 10.15.5

The TS LSP has a [special deny list for specific schemes](https://github.com/microsoft/vscode/blob/a7a501f07a367f7de74e876a0b827deff9721949/extensions/typescript-language-features/src/utils/fileSchemes.ts#L23) but it does not contain schemes for custom SCM providers, such as the [hg extension](https://marketplace.visualstudio.com/items?itemName=mrcrowl.hg) or private extensions.

1. If the SCM provider does use their own scheme and keeps the file extension (e.g. .ts), the user will see errors reported in those virtual files but receive regex based syntax highlighting in the two-pane diff view.
2. If the SCM provider does use their own scheme and removes the file extension (e.g. adds .hg), all LSP and syntax highlighting functionality will disappear for the SCM files (no regex based syntax highlighting).

Steps to Reproduce:

1. Create an hg repository (e.g. `yo code` and `hg init`)
2. Create and open a TS file in the repository which imports other files, observe errors

Possible Solutions:
* Denote in LSP that these files are specific to SCM or virtual files. Even better, don't send them to the LSPs, they're an implementation detail from SCM providers. LSPs cannot scale to support all possible virtual file schemes.
* Add an API/user setting to customize these lists globally (possibly for all LSPs)

Does this issue occur when all extensions are disabled?: No

**Comment by mjbvz** [comment]
e969bc1 should disable error reporting but keep most other language features enabled in virtual files.

However keep in mind that we cannot provide project wide intellisense in virtual files. This is because the TypeScript server that provides IntelliSense and error reporting has no clue how to read `hg:` files for example, only VS Code itself can do that. The compromise is to treat virtual files as independent units which means we never try to resolve imports for example

**Comment by DavidGoldman** [comment]
Thank you, when will the fix be available? VS Code 1.49?

**Comment by mjbvz** [comment]
The September release. Try it out once the 1.50 insiders comes out later this week
