### ISSUE TITLE
Expensive scopes should be automatically collapsed after an evaluation

### ISSUE THREAD

**Issue by kenkangxgwe** [microsoft/vscode#106233]
I have a scope `A` marked `expensive = true` in the response to `scopes`. Expanding it in the `variables` drawer took ~20s. 
An evaluation in the `debug console`, which does a simple update in another small scope `B`, makes the `variables` drawer reload the expensive scope `A` as well. I confirm that if I let the debugger `continue` and `pause` again, the expensive scope will be collapse automatically but an evaluation in the `debug console` obviously doesn't do this.

**Comment by kenkangxgwe** [comment]
Sorry, just confirmed that `continue`ing and `pause'ing the debugger only clean the `variables` drawer, but clicking on the `call stack` will reopen the expensive scope `A` and expend it.
Reading https://github.com/microsoft/debug-adapter-protocol/issues/116, seems that expensive scope should be auto collapsed, wondering why it does not on my side.

**Comment by kenkangxgwe** [comment]
Also, I've marked the scope with `namedVariables = 6718` children, wondering why doesn't expanding it send the `variables` requests in chunks.

**Comment by isidorn** [comment]
Currently we do not auto colapse expensive scopes. Since I still think that if the user explicity expands the scope we should respect that. User's preference should have priority.
Though I am open to change this and for now I would prefer to leave this open to gather more user feedback.

**Comment by weinand** [comment]
@isidorn I agree.
From user feedback we have learned again and again that VS Code should preserve the expand state whenever possible.
So automatically collapsing or expand **existing** variable nodes is not an option.

However, "auto expanding" of **new** variable nodes is OK, because in this case there is nothing to preserve.

**Comment by kenkangxgwe** [comment]
Thanks for the clarification. I will not have complaints if it is a WAI. 

Two more questions:
1. Why does continuing and pausing the debugger clear the variables area, and I have to re-click the stackframe to show it up again?
2. Could you give more details about how I can get `variables` requests in chunks?

**Comment by isidorn** [comment]
1. This should ideally not be visible to the user. Continue and pause should clear the variables area and re-populate it quickly. Do you have some minimal repro steps so we try this out. You should not need to re-click the stackframe to show it again
2. You need to provide [`indexedVariables` field](https://github.com/microsoft/vscode/blob/707ce447cb14b0d40bdd9d348ef6d6afc381f38e/src/vs/workbench/contrib/debug/common/debugProtocol.d.ts#L1782) I suggest to search the debugProtocol for all instances of "paged UI" since that can give you a good idea.  As an example here's how js-debug does it https://github.com/microsoft/vscode-js-debug/blob/c04dc706c03a01a0bbfb75d3e01ae7da3286f980/src/adapter/variables.ts#L602

**Comment by isidorn** [comment]
@kenkangxgwe we will only be able to investigate futher into this if you fork VS Code mock debug https://github.com/microsoft/vscode-mock-debug and create a repro sample

2. Named children currently do not support paging. Here's a feature request for that https://github.com/microsoft/vscode/issues/87718
