### ISSUE TITLE
File not saving with ctrl+s on first try

### ISSUE THREAD

**Issue by FireDog31262** [Microsoft/vscode#10629]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 6.1.7601

Steps to Reproduce:

1. Modify a file.
2. Press ctrl+s, and file does not save until you hit ctrl+s a second time.

**Comment by bpasero** [comment]
I am very sorry to hear you are having issues with VS Code. I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by AaronMorgan** [comment]
I found disabling the `lonefy.vscode-JS-CSS-HTML-formatter` extension corrected the behaviour. 

There's an open [fault](https://github.com/Lonefy/vscode-JS-CSS-HTML-formatter/issues/28) on their extension page.
