### ISSUE TITLE
Typescript intellisense isn't showing the name of the class

### ISSUE THREAD

**Issue by mhamri** [microsoft/vscode#106306]
Version: 1.48.2 (user setup)
Commit: a0479759d6e9ea56afa657e454193f72aef85bd0
Date: 2020-08-25T10:13:11.295Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

# Steps to Reproduce:

https://github.com/mhamri/vscode-typescript-intellisense-bug

1- go to `src\app\app-routing.module.ts`

2- try to import NotFoundComponent in line 63

3- if you couldn't like me, try to uncomment line 20. it's there, but typescript won't pick it up

![image](https://user-images.githubusercontent.com/8991783/92511926-99c6e900-f240-11ea-80ed-d6b48ce7e9f8.png)

this always happen if I'm in middle of some work in the repo. as you can see, I have some missing files and broken import in the repo. but this cause the whole intellisense goes missing and increase the latency to open the intellisense box, including snippet and local variables name. some times it stuck in thinking ... stage for 30 seconds or more. 

 **Does this issue occur when all extensions are disabled?**: Yes

**Comment by mjbvz** [comment]
`src/app/@theme/pages/not-found/not-found.component.ts` is not part of your tsconfig project. You can check this by opening the file and running `TypeScript: Go to project configuration` in the command palette

I suspect this is because of the `"files"` section which means that if `not-found.component` is never imported into an existing file that is part the project, `not-found.component` will not be included in the project automatically
