### ISSUE TITLE
Debug action bar doesn't disappear after clicking stop button

### ISSUE THREAD

**Issue by Nina0408** [microsoft/vscode#106324]
- VSCode Version:Version: 1.48.2
- OS Version:Darwin x64 18.7.0

Steps to Reproduce:
I am developing a debugger in VSCode, and when I clicking the stop button of debug action popup bar
<img width="375" alt="屏幕快照 2020-09-09 下午12 25 34" src="https://user-images.githubusercontent.com/20856567/92554839-e0483200-f298-11ea-9d1c-5421bae52dd3.png">

1. when I clicking the stop button of debug action popup bar
2. I debugged the code and saw vscode called terminateRequest (I put some clean up code in this request ) and the action popup bar should be disappeared, but it didn't. 
3. When I clicked the stop button again, I saw vscode called disconnectRequest, and then the action popup bar finally disappeared.
4. It should be disappeared at the first stop, 
5. and I don't know what's the difference between terminateRequest and disconnectRequestIn my understanding, terminateRequest will be triggered when user click the stop button of above bar. and disconnectRequest will be triggered when send terminateEvent in the code logic. 

I am not sure if my understanding is right, please advice. Thanks!!!

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Nina0408** [comment]
<img width="375" alt="屏幕快照 2020-09-09 下午12 25 34" src="https://user-images.githubusercontent.com/20856567/92554858-eb9b5d80-f298-11ea-818b-a2efe9b5e125.png">

**Comment by weinand** [comment]
Please read:
https://microsoft.github.io/debug-adapter-protocol/specification#Requests_Terminate and 
https://microsoft.github.io/debug-adapter-protocol/specification#Requests_Disconnect

The "terminate" request is only called if the debug adapter has a capability "supportsTerminateRequest".
The debug adapter can implement that request to shut down the debuggee in a way that gives it a chance to clean up properly (on Unix a SIGINT signal is sent to the debuggee). Since the debug session continues, it is still possible to debug the shutdown phase of the debuggee.

If you return `"supportsTerminateRequest": false` then the "terminate" request is not called and the first click on the stop button will stop the debuggee immediately.

**Comment by Nina0408** [comment]
Hi @weinand ,

I already read the doc before. but I still didn't quite understand it through the description.

My dev env is on MAC and my situation is :
1. when user clicks "stop" debug session button, DAP needs to do some clean up job. so I set `"supportsTerminateRequest": true,` and put some code in` terminateRequest.` 
2. when some exception happened which need to shut down the debug session. so DAP will catch the exception and send `TerminateEvent()`, which will make disconnectRequest called, so I put some clean up job there also.
3. Based on above 2 code logics, now the debug actions bar will be closed by clicking "stop" button twice. which is not expected.

Please advice me what is a better way to do . Thank you!

**Comment by weinand** [comment]
@Nina0408 please note that there is a difference between the debug adapter (an implementation detail of VS Code debuggers) and the debuggee (the program to debug).

The "terminate" request is for giving the **debuggee** a chance to clean up, not for the debug adapter. This is clearly stated in the description. The typical implementation of "terminate" in the debug adapter does nothing more than sending a signal to the debuggee (e.g. SIGINT on linux/macOS). It does not clean up anything in the debug adapter.

If the debuggee receives this signal, it can intercept the signal to do its cleanup work and then terminate. The debug adapter should detect the termination of the debuggee and should send a terminate event upstream (to VS Code). This will end the debug session.
If the debuggee hits a breakpoint or exception while shutting down, the debug adapter and the debug session is still alive and can "debug" this.

If all of this is not something you want to deal with, then set "supportsTerminateRequest" to false. In this case the first "stop" button press sends a "disconnect" which should terminate the debuggee forcefully.

If you want to have this behavior, then leave "supportsTerminateRequest" at true, but then you will have to implement your "terminate" request to send a signal that the debuggee can intercept but will kill it by default.  Without the correct implementation of the "terminate" request, the first "stop" button press (which sends the "terminate") has no effect, and you need the second "stop" button press which sends the "disconnect" request.

**Comment by Nina0408** [comment]
Hi @weinand ,

Thank you for your nice detailed explanation, they are so helpful, and I finally understand the difference between terminate and disconnect request. 

I just have one last question :
After debuggee receives the SIGINT , and does its clean up work and terminates. And then as you mentioned, debug adapter should detect the termination of the debuggee,  and my question is here, how can DA detect it ? 

Thank you very much!!

**Comment by weinand** [comment]
Detecting the termination of the debuggee is independent from the SIGINT signal and must be done in any case.
Even if the debuggee terminates normally (because it reaches the end of the code), the debug adapter needs to be notified of this.

You can do this easily with this node.js API: https://nodejs.org/api/child_process.html#child_process_event_exit
And you even receive a code that tells you the reason for the termination (e.g. the SIGINT signal).

Please note: the debug adapter only needs to track the termination of the debuggee in the "launch" case (when it had launched the debuggee). In the "attach" case, the DA does not have to track termination (and it cannot easily).

**Comment by Nina0408** [comment]
Thank you @weinand
