### ISSUE TITLE
Autocomplete Private JS methods adds some extra gibberish

### ISSUE THREAD

**Issue by jellymann** [microsoft/vscode#106351]
- VSCode Version: 1.48.2 (user setup)
- OS Version: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Write a JavaScript class with a private method
2. Attempt to auto-complete the private method somewhere.

Expected outcome:

* Private method is autocompleted correctly

Actual outcome

* Private method is autocompleted with some extra characters

See the following screenshots

![image](https://user-images.githubusercontent.com/1171825/92615648-9faedf80-f2bd-11ea-8dcc-74330e3d65f7.png)
![image](https://user-images.githubusercontent.com/1171825/92615681-a89fb100-f2bd-11ea-818c-5ad4b2821ce1.png)

Does this issue occur when all extensions are disabled?: N/A autocomplete doesn't recognise JavaScript at all if extensions are disabled. I did try this with a vanilla install of Insiders (no _extra_ extensions enabled) and the problem still occurs

**Comment by IllusionMH** [comment]
I guess this is because private methods aren't supported by TS (provides JS features) https://github.com/microsoft/TypeScript/issues/39066

Currently only private fields are supported and work as expected
![image](https://user-images.githubusercontent.com/1312662/92621632-b6a8fe00-f2cc-11ea-8be9-d06abe5ba55e.png)

/assign @mjbvz

**Comment by mjbvz** [comment]
That sounds correct

Closing as upstream
