### ISSUE TITLE
Save prompt is shown while saving from settings split json editor

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#106330]
Running from Sources

- Enable Settings split json UI `"workbench.settings.useSplitJSON": true,`
- Open the Split JSON editor
- Do some changes and type `cmd+s`

🐛 Default settings resource is opened and save dialog is shown

**Comment by bpasero** [comment]
Rather than reverting the support for being able to save readonly editors via `Cmd+S` I went ahead and added a condition under which a side by side editor will not save both sides: if any of the 2 sides is untitled, it will not save both. This fixes this issue while still allowing to e.g. `Cmd+S` on the "Default Settings (JSON)" editor, which I think is fine.

The only downside is that when you now compare 2 untitled files and hit `Cmd+S` you can no longer save both sides. Let's see how this goes.
