### ISSUE TITLE
Branch change doesn't update the opened file with the new code.

### ISSUE THREAD

**Issue by thakursaurabh1998** [microsoft/vscode#106481]
- VSCode Version: 1.49
- OS Version: MacOS Catalina

Steps to Reproduce:

1. Open a file which has some changes on some other branch.
2. Change your branch either via cli or the vs code branch button in the lower left corner.
3. The file doesn't get updated with the changes. To see the change, I have to once open another file, and come back to the main file to check if something has changed.

Looks to me like a re render issue

Does this issue occur when all extensions are disabled?: Yes

**Comment by thakursaurabh1998** [comment]
VS Code version doesn't matter here because this is happening from quite some time now.

**Comment by walidbarakat** [comment]
> VS Code version doesn't matter here because this is happening from quite some time now.

i think it does matter, i have same OS but VSCode version is 1.48.2 and it's not reproducible, just for the record.

**Comment by thakursaurabh1998** [comment]
This is happening for me from last 1 year. Tried to solve it myself but failed so finally created an issue.

**Comment by thakursaurabh1998** [comment]
> > VS Code version doesn't matter here because this is happening from quite some time now.
> 
> i think it does matter, i have same OS but VSCode version is 1.48.2 and it's not reproducible, just for the record.

This is happening for me from last 1 year. Tried to solve it myself but failed so finally created an issue.

**Comment by bpasero** [comment]
VS Code is using different file watching strategies depending on your OS and your setup. 

**First thing to check:**
* [ ] I verified that the issue still reproduces in our insiders version (https://code.visualstudio.com/insiders/)
* [ ] I verified that this issue is happening outside of a `node_modules` folder. Our file watcher ignores this folder!

**To find out more about this issue, please first answer this:**
* [ ] What OS are you on
* [ ] Does this happen from an empty workspace, a single-folder workspace or a multi-root workspace?
* [ ] Do you have `files.useExperimentalFileWatcher: true` configured in settings?
* [ ] What is your configured `files.watcherExclude` setting?

**Then please answer the following depending on your setup:**
* [ ] It reproduces with any folder or workspace you open
* [ ] The files/folders you open are on your local disk and not on a network share nor a UNC drive
* [ ] The files/folders you open are not behind a symbolic link
* [ ] The folder(s) opened use the exact same casing as they are on disk
* [ ] It reproduces when I make a change to the file from another VS Code window (either from the editor or the file explorer)

**Then please attach the output of our development console**
* run `code --verbose` from the command line
* perform the action that causes you to not see the file change in VS Code
* attach the output from the console (`Help` > `Toggle Developer Tools` > `Console`)

Thanks for taking the time to fill out this questionnaire.
