### ISSUE TITLE
How to unconfig a configed plugin by calling `configurePlugin`

### ISSUE THREAD

**Issue by CGQAQ** [microsoft/vscode#106402]
How to unconfig a configed plugin by calling `configurePlugin(pluginId: string, configuration: ConfigurationField): void;` from `vscode.typescript-language-features`

I tried restart the `tsServer` by doing this `commands.executeCommand("typescript.restartTsServer");`, but didn't work

Or how to communicate between the `tssever plugin` and the `languageclient`

**Comment by mjbvz** [comment]
What do you mean by unconfigure? Can you share an example

You can use configure to send a `reset` message if that's what you are after

**Comment by CGQAQ** [comment]
@mjbvz I mean just unload the tsserver plugin completely, here's the thing: I need to implement a feature so that the lsp run conditionally determined by both `deno.enable` and `deno.include`, I added a flag to the languageserver and client, but the tsserver plugin still configed and don't obay `deno.enable` and `deno.include`.
I was thinking just unload the tsserver plugin completely, it's more easily to be implement, if not possible, how to send the message to tsserver plugin to let it know it show enable/disable now

**Comment by mjbvz** [comment]
There's no support for explicitly unloading a plugin. What you probably want to do is make it so that plugin itself can easily enable/disable itself based on a configuration value (or a configuration sent by `configurePlugin`)

`configurePlugin` essentially just lets you post messages to a plugin from a vs code extension. Again the specifics depend on your use case but all the tools you need should be there to enable/disable the plugin's functionality based on some configuration

**Comment by CGQAQ** [comment]
> You can use configure to send a `reset` to your plugin message if that's what you are after

Could I `reset` it by letting it do nothing? What do you mean by `reset`? Rerun the tsserver plugin's create method?
