### ISSUE TITLE
one click/keypress option to escape invalid regular expression in searches

### ISSUE THREAD

**Issue by graingert** [microsoft/vscode#106401]
sometimes I'm about to use a regex but most of the regex is a literal match, so I'd like to be able to type all that out, then click the error message to automatically escape my regex:

![image](https://user-images.githubusercontent.com/413772/92718646-f9fd7e00-f359-11ea-99e3-d7028081596f.png)

**Comment by myfonj** [comment]
It took me some time to understand this so idea, so alternative use case for illustration:

*"Find all occurrences of characters folded in two curly brackets, like first and last "word" in `{{a}} b {{c}}`"*

"Nice looking" `{{.}}` is obviously not a valid regexp: we need `\{\{.\}\}` which is cumbersome to write; so if I understand it well this proposal asks for introduction of mean to [RegExp.escape](https://github.com/benjamingr/RegExp.escape) current search input value.  Resulting workflow would be:

1) *Type `{{.}}` into search field.*
2) *Invoke proposed feature and get search field value replaced with `\{\{\.\}\}`.*
3) *Manually delete the middle backslash and get intended regexp, `\{\{.\}\}`.*

---

(It is different from already well supported use case  *"I need to toggle RexExp altogether"*, because there is visible "`.*` button" with <kbd>Alt</kbd><kbd>r</kbd> shortcut in tooltip hint for this.)

**Comment by roblourens** [comment]
How would you feel about escaping/unescaping regex characters when toggling regex mode on/off? So the flow would be

- Type `foo(`
- Turn regex mode on
- The query becomes `foo\(`
- Turn regex mode off
- The query reverts to `foo(`

This isn't exactly what you are asking for but I like it better than something that looks like a "fix this error" button which has the potential to give a technically wrong result, like in @myfonj's example.

**Comment by myfonj** [comment]
> How would you feel about escaping/unescaping regex characters when toggling regex mode on/off?

For me it feels that switching mode should not have unexpected effect on the value: if you start writing or paste proper regexp into search field and only after that realize that you haven't regexp enabled, you probably do not want to have your (pasted) regexp escaped.

I think this proposal could be better fulfilled by introducing commands (and corresponding buttons) that would "blindly" add/remove regexp escape, but I see there is no good place to add them. Like:

<kbd><strong>.</strong>\*</kbd> → <kbd>\\<strong>.</strong>\\\*</kbd> add regexp escape sequences (+ switch regexp mode on?)
<kbd>\\<strong>.</strong>\\\*</kbd> → <kbd><strong>.</strong>\*</kbd> remove regexp escape sequences (+ switch regexp mode off?)

I think such buttons still should not switch modes, because it feels like unexpected side effect.

BTW, I suppose extensions cannot hook into find/replace panel, can they? Considering that spell-checking extensions are not checking SCM commit messages by now I deduce it is not possible for them to operate outside main editor. But if they could then this proposal would be nice adept for small extension.
