### ISSUE TITLE
Debug control bar no longer shows correct state when using multiple debug sessions

### ISSUE THREAD

**Issue by thegecko** [microsoft/vscode#106414]
**Describe the bug**
When debugging with multiple sessions, I expect the state of the debug control bar to update and reflect the state of the selected session.

Since switching to the new debug engine, the continue button fails to appear when switching to a paused debug session and the paused session isn't automatically selected.

**To Reproduce**
Steps to reproduce the behaviour:
1. Begin debugging multiple sessions (perhaps using a compound configuration)
2. Set a breakpoint in one of them and run to it. Observe the continue button button is shown correctly, but the session paused may be wrong.

In this example, I have multiple sessions and I have set a breakpoint in the `Plugin Host` session.

__Before new debugger__
Correct paused session displayed
<img width="352" alt="Screenshot 2020-09-10 at 09 05 13" src="https://user-images.githubusercontent.com/61341/92699619-bb5dc880-f345-11ea-8ca7-377c7bc7e699.png">

__After new debugger__
Incorrect paused session displayed
<img width="351" alt="Screenshot 2020-09-10 at 09 06 01" src="https://user-images.githubusercontent.com/61341/92699671-cca6d500-f345-11ea-9e0c-79f3436ecc23.png">

3. Select the correct session and observe the continue button is no longer available

<img width="356" alt="Screenshot 2020-09-10 at 09 06 10" src="https://user-images.githubusercontent.com/61341/92699757-e5af8600-f345-11ea-9db9-7716f0898d0d.png">

__Workaround__
Selecting the debug session in the debug panel correctly updates the debug control bar:

<img width="531" alt="Screenshot 2020-09-10 at 09 06 36" src="https://user-images.githubusercontent.com/61341/92699787-ee07c100-f345-11ea-8fb6-61f85a776a3e.png">

Control bar now shown correctly:

<img width="352" alt="Screenshot 2020-09-10 at 09 05 13" src="https://user-images.githubusercontent.com/61341/92699857-ffe96400-f345-11ea-8da4-99a72ad52239.png">

**VS Code Version:**
Version: 1.48.2
Commit: a0479759d6e9ea56afa657e454193f72aef85bd0
Date: 2020-08-25T10:09:08.021Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.6.0

**Additional context**
Debugger for chrome: 4.12.10

**Comment by isidorn** [comment]
This seems like an issue on the VS Code UI side. Thus unassigning @connor4312 

@thegecko so the gist is: instead of the `continue` you see a `pause` action in the debug toolbar when debugging mulitple sessions.
I can not reproduce this? Can you:
1) Try to repro with vscode insiders https://code.visualstudio.com/insiders/
2) Create a minimal reproducable repository on GitHub so I simply clone it and reproduce this issue on my machine

**Comment by connor4312** [comment]
I actually hit this on insiders today

![](https://memes.peet.io/img/20-09-2c9a07e1-5080-4482-9b32-712fd564cb55.png)

I don't have a consistent repro, though. Maybe @thegecko does?

**Comment by thegecko** [comment]
1. I can confirm this is still an issue with the vscode insiders version (and can see it without the chrome debug extension installed)
2. I'll try to find some time to create a repro

**Comment by thegecko** [comment]
I've been able to repro this with a minimal app here:

https://github.com/thegecko/vscode-106414

**Comment by isidorn** [comment]
Thanks for the great repro steps, I cloned this repository and I can reproduce the problem.
The issue here is that the First session `Main` has a child session `main.js` and they get nicely compressed into one session node. However that child session has another child `fork.js` and they do not get compressed because the `main.js` reports it has a thread with an empty call stack.

So when @thegecko changes the focused session via dropdown we focus the parent session and not the `fork.js` child which does not get compressed due to this empty thread

@connor4312 can you please investigate on your side why is there an empty thread and can you maybe fix this on the js-debug side of things?

![Screenshot 2020-09-16 at 11 16 10](https://user-images.githubusercontent.com/1926584/93317702-12fca800-f80e-11ea-9b86-13307d51cb73.png)

**Comment by connor4312** [comment]
> However that child session has another child fork.js and they do not get compressed because the main.js reports it has a thread with an empty call stack.

This is actually intentional in js-debug -- we only compact the top level sessions https://github.com/microsoft/vscode-js-debug/blob/master/src/ui/vsCodeSessionManager.ts#L42

I think the problem that @thegecko is referring to is that when I switch to the "Fork" config via the dropdown in the debug toolbar, the state of the buttons are not updated. I'm guessing that although "Fork"'s compressed child session is paused, so in the callstack view the visual state of "Fork" is paused, the toolbar selects the parent who is still "Running".

![recording(3)](https://user-images.githubusercontent.com/2230985/93631401-67d02800-f9a0-11ea-88cf-a5814d2bdd91.gif)

**Comment by isidorn** [comment]
Correct. The dropdown simply selects the parent. The dropdown does not care if a session is running or stopped. And I would not change that since I think that approach makes sense.

**Comment by connor4312** [comment]
It seems weird that we would show `Fork: Remove Process [0]` as focused within the call stack view when selected from the dropdown, but clicking on it focus it would yield a different result. From a user's POV I don't know that `Fork` has a compacted child.

**Comment by thegecko** [comment]
What further information is needed?

**Comment by isidorn** [comment]
This was a mistake by the bot. Reopening

**Comment by thegecko** [comment]
@isidorn Is this bug to be left?
