### ISSUE TITLE
Auto closing quotes not working on Ubuntu 20.04 with English (US, intl., with dead keys) keyboard layout

### ISSUE THREAD

**Issue by OCmilo** [microsoft/vscode#106503]
- VSCode Version: 1.49.0
- OS Version: Linux x64 5.4.0-47-generic

Steps to Reproduce:

1. press " twice to get " (because of dead keys)
2. quote doesn't auto close, even with single quote.
OBS: when I change my keyboard layout to English (US) it auto closes as it should.

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexdima** [comment]
@OCmilo I have installed the English (US, intl., with dead keys) keyboard layout on Ubuntu 20.04, but it appears to me that pressing <kbd>"</kbd> twice does not produce a `"` character, but it produces `¨` - [`Unicode Character 'DIAERESIS' (U+00A8)`](https://www.fileformat.info/info/unicode/char/00a8/index.htm):

```
# " vs ¨
```

![image](https://user-images.githubusercontent.com/5047891/101628749-8e8e7f80-3a20-11eb-83fc-6d0f55325f68.png)

So I believe this is working as expected, because the produced character, [`Unicode Character 'DIAERESIS' (U+00A8)`](https://www.fileformat.info/info/unicode/char/00a8/index.htm) is not defined as an auto-closing character.
