### ISSUE TITLE
Removing keybindings with when clauses not working anymore

### ISSUE THREAD

**Issue by Mogami95** [microsoft/vscode#106524]
- VSCode Version: 1.49.0
- OS Version: MacOS 10.14.6 (18G6020)

Steps to Reproduce:

1.
Preference -> Keyboard shortcuts -> search "terminal.find next" -> Remove Keybinding -> doesn't work

Does this issue occur when all extensions are disabled?: Yes

**Comment by spasche** [comment]
Also affects Windows. It's a regression, it used to work with 1.48.
`keybindings.json` testcase:
```` 
    {
        "key": "ctrl+f",
        "command": "-workbench.action.terminal.focusFind",
        "when": "terminalFocus"
    }
````

**Comment by Mogami95** [comment]
@spasche Hi Spasche, I found this bug with the 1.49. 
It used to work with the 1.48 on MacOS as well.

**Comment by thernstig** [comment]
It seems it's not possible to remove other keybindings as well. None of these work to remove `ctrl+f` when in the terminal:

```json
// Place your key bindings in this file to overwrite the defaults

[
  {
    "key": "ctrl+k f",
    "command": "workbench.action.terminal.focusFind",
    "when": "terminalFindFocused && terminalProcessSupported || terminalFocus && terminalProcessSupported"
  },
  {
    "key": "ctrl+f",
    "command": "-workbench.action.terminal.focusFind",
    "when": "terminalFindFocused && terminalProcessSupported || terminalFocus && terminalProcessSupported"
  },
  {
    "key": "ctrl+f",
    "command": "-actions.find"
    // "when": "terminalFocus && terminalProcessSupported"
  }
]
```

**Comment by Tyriar** [comment]
This works:

```
{ "key": "ctrl+f", "command": "-workbench.action.terminal.focusFind" }
```

I'm guessing the issue is that `&&` and `||` don't work when you're removing keybindings.

**Comment by spasche** [comment]
Testcase on https://github.com/microsoft/vscode/issues/106524#issuecomment-691658426 also doesn't work and doesn't contain `&&` or `||` in the `when` condition.

So the issue may not be related to `&&` or `||` (or not only).

**Comment by Tyriar** [comment]
@spasche good point, tested and I can see that too. Updated title.

**Comment by thernstig** [comment]
Yup, this does not work:

```json
    {
        "key": "ctrl+f",
        "command": "-workbench.action.terminal.focusFind",
        "when": "terminalFocus"
    }
```

This does:

```json
    {
        "key": "ctrl+f",
        "command": "-workbench.action.terminal.focusFind"
    }
```

**Comment by alexdima** [comment]
This is a problem limited for now to the terminal actions and it has to do with the way the default keybindings are constructed in code by using `AND` between the `precondition` and the `when` context. So [the registration of `workbench.action.terminal.focusFind`](https://github.com/microsoft/vscode/blob/bedc2bf60259723b0b6fa324c516dbde14c42755/src/vs/workbench/contrib/terminal/browser/terminalActions.ts#L949-L960) leads to a when expression looking like:

 `(terminalFindFocused || terminalFocus) && terminalProcessSupported`.

But the context keys do not support parentheses in their serialized form (that is intentional), so we distribute the `AND` against the `OR` to create:

`terminalFindFocused && terminalProcessSupported || terminalFocus && terminalProcessSupported`.

Unfortunately there is a bug in that code path where the normalized form is not fully equal to the deserialized form. The normalized form contains an extra `AND` expression with a single operand which should be removed:

![image](https://user-images.githubusercontent.com/5047891/93323344-c5376e00-f814-11ea-9a8d-0575da2b21b1.png)

The workaround is to remove the keybindings without a `"when"` clause.
