### ISSUE TITLE
Latest version of Code causes Arduino plugin to fail

### ISSUE THREAD

**Issue by damianpowell** [microsoft/vscode#106500]
Issue Type: <b>Bug</b>

Execute the "Arduino: Open Serial Monitor" command. get the error:

Failed to open serial port COM3 due to error: + Error: The module '\\?\c:\Users\damia\.vscode\extensions\vsciot-vscode.vscode-arduino-0.3.2\out\node_modules\usb-detection\build\Release\detection.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 75. This version of Node.js requires
NODE_MODULE_VERSION 80. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).

This feature worked in the last hour (before I closed and updated VS Code and got an update!)

VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T13:22:08.892Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.86GB (17.42GB free)|
|Process Argv|--folder-uri file:///c%3A/Work/Zapinamo/Hubz-LowLevel --crash-reporter-id 807c183f-8d40-4816-bbb9-90a2316c1ee6|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
gitdiffer|aag|0.0.3
path-intellisense|chr|2.3.0
codealignment-vscode|cpm|2.0.19
xml|Dot|2.5.1
EditorConfig|Edi|0.15.1
vscode-npm-script|eg2|0.3.13
git-extensions-for-vs-code|for|1.1.3
svg|joc|1.3.9
vscode-home-assistant|kee|1.8.1
vscode-docker|ms-|1.5.0
csharp|ms-|1.23.2
vscode-kubernetes-tools|ms-|1.2.1
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.5
cpptools|ms-|0.29.0
powershell|ms-|2020.6.0
vsliveshare|ms-|1.0.2740
team|ms-|1.161.0
debugger-for-chrome|msj|4.12.10
vscode-yaml|red|0.10.1
autoimport|ste|1.5.3
scrolloff|tic|0.0.4
vscode-arduino|vsc|0.3.2
markdown-all-in-one|yzh|3.3.0
hocon-colorizer|zzz|0.2.7

</details>

**Comment by fidelbrea** [comment]
Hi there,

I got the same problem since today (before I was working with usb serial port correctly).
I installed npm package, went into _~/.vscode/extensions/vsciot-vscode.vscode-arduino-0.3.2/out/node_modules/usb-detection_ path and execute **npm install** without success. I executed **npm rebuild** (just in case) but no success.

I followed the links proposed by the vscodebot ([link](https://github.com/microsoft/vscode/issues/106500#issuecomment-691165129)) but I did not find a solution.

This is my error message I get:

Failed to open serial port /dev/ttyACM0 due to error: + Error: The module '/home/fidel/.vscode/extensions/vsciot-vscode.vscode-arduino-0.3.2/out/node_modules/usb-detection/build/Release/detection.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 67. This version of Node.js requires
NODE_MODULE_VERSION 80. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).

Visual Studio Code about:
      Version: 1.49.0
      Commit: e790b931385d72cf5669fcefc51cdf65990efa5d
      Date: 2020-09-10T13:20:50.359Z 
      Electron: 9.2.1 
      Chrome: 83.0.4103.122
      Node.js: 12.14.1
      V8: 8.3.110.13-electron.0 
      OS: Linux x64 5.4.0-47-generic snap

Arduino for Visual Studio Code (Microsoft)
      Extension Id: vsciot-vscode.vscode-arduino
      Version: 0.3.2


Thank you for reading this.

Regards and thanks in advance for your time,
Fidel Brea.

**Comment by modermo** [comment]
I'm getting the same error.

**Comment by deepak1556** [comment]
`1.49` has been updated to a newer runtime of Electron `9.2.1` which has NODE_MODULE_VERSION 80 , please file an issue against the extension to compile their native node module `usb-detection` for this version. Thanks!

**Comment by Xinyu-Wu-0000** [comment]
I'm getting the same error, I can not open the serial port.

**Comment by fidelbrea** [comment]
Downgrade. This is a solution. I fixed downgrading up to 1.48.2.
I hope you find this useful to fix your own situations.

**Comment by bramosrys** [comment]
I'm getting the same errror: 
Failed to open serial port /dev/ttyUSB0 due to error: + Error: The module '/home/bramos/.vscode/extensions/vsciot-vscode.vscode-arduino-0.3.2/out/node_modules/usb-detection/build/Release/detection.node' was compiled against a different Node.js version using NODE_MODULE_VERSION 67. This version of Node.js requires NODE_MODULE_VERSION 80. Please try re-compiling or re-installing the module (for instance, using `npm rebuild` or `npm install`).

**Comment by patrikf11** [comment]
got the same erroe in vs 1.50 .. downgrading to 1.48.2 solved the problem
