### ISSUE TITLE
Disable Ligatures & Ligatures Limited no longer work

### ISSUE THREAD

**Issue by Dam1ran** [microsoft/vscode#106596]
- VSCode Version: 1.49.0
- OS Version:  Windows 10
- tried both User and general installers

 on older version it works fine!

Steps to Reproduce:

1. have latest version of VS code
2. have installed 'Fira Code' font
3. settings. json -> "editor.fontLigatures": true,
3. install "Disable Ligatures" at https://marketplace.visualstudio.com/items?itemName=CoenraadS.disableligatures
4. or install "Ligatures Limited" at https://marketplace.visualstudio.com/items?itemName=kshetline.ligatures-limited

Ligatures no longer disabled when required.
![Screenshot 2020-09-13 184101](https://user-images.githubusercontent.com/53400364/93022213-be301600-f5f0-11ea-8c9a-d56d215b63bb.png)

In My case i used to disable them at the cursor, now it does not disable with any settings

I did some research on code of those extensions and they both rely on:

**vscode.window.createTextEditorDecorationType({ color: "" });** <-- in this version of VS Code - this statement no longer disables ligatures when writing -> **editor.setDecorations(decoration, ranges);**

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexdima** [comment]
With 1.49.0, we have updated to Electron 9, which ships with a new Chromium layout implementation, LayoutNG. I believe that these extensions were using a technique to disable ligatures by injecting custom CSS which somehow caused the previous Chromium layout implementation to stop a ligature. Since this was not a feature implemented by us, I suggest that you please create issues directly against the extensions.

**Comment by Dam1ran** [comment]
After 1.49.3 it works again! thanks
