### ISSUE TITLE
Japanese IME text does not align with editor text

### ISSUE THREAD

**Issue by raygo0312** [microsoft/vscode#106663]
When inputting Japanese, the text is displayed out of alignment in the state before conversion (underlined state). As the number of characters increases, it will shift significantly. This was solved by changing to a monospace font, but the misalignment itself was not solved.
OS is Windows 10
Keyboard input is IME.
It happened with or without WSL.
It happened even without the extension.

<details><summary>Original (in Japanese)</summary>

日本語を入力する際に、変換前の状態(下線が引かれてる状態)でテキストがずれて表示されてしまいます。文字数が多くなると大きくずれていきます。これは等角フォントに変更することで解決しましたが、ずれて表示されること自体は解決しませんでした。
OSはWindows10
キーボード入力はIME
を使用しています。WSLの使用でもそうでなくても起こりました。拡張機能をいれていない状態でも起こりました。

</details>

**Comment by Harukero** [comment]
As far as I understand it seems that when inputting text in Japanese in VSCode there are some display issues. 
This happens right before changing the inputted text into kanjis (or not) when the text is underlined. 
The issue is that the text will be displayed out of alignment. 
Using a monospaced font seems to fix the issue.
@raygo0312 uses IME on Windows 10.

**Comment by alexdima** [comment]
Could you please explain in great detail exactly what you are doing? 

It would be very helpful if you would even include a gif. 

Here is the kind of detail we are looking for, such that we can reproduce even without having Japanese language knowledge -- e.g. -- https://github.com/microsoft/vscode/wiki/IME-Test#windowsmac-japanese

**Comment by Harukero** [comment]
@raygo0312 詳しくバグが出る状況を説明してもらいませんか？
できればGIFを添付してもらったら助かります。

**Comment by raygo0312** [comment]
figure_a は対策前の状況です。文字を打つとテキストがずれていきます。

figure_b は等角フォントにした後の状況です。多少改善されますが、少しずれが残っており、青いカーソルと白いカーソルの二つ出てきて違和感があります。

@Harukero 翻訳ありがとうございます。こちらもお願いしたいです。英語を読むことはできるので、英和は無理をしなくていいです。

![figure_a](https://user-images.githubusercontent.com/18397781/93694219-0cd73600-fb44-11ea-9cb3-312514cfd711.gif)
![figure_b](https://user-images.githubusercontent.com/18397781/93694221-119bea00-fb44-11ea-8d6a-3aed8744dec7.gif)

**Comment by Harukero** [comment]
On the first GIF, we can see that the more he writes, the more the text feels pushed and moves.
The second GIF shows what happens when using monospaced fonts.
While the use of monospaced fonts makes everything way better, on both GIFs we can see that there is space between white and blue cursors, which feels weird.

@raygo0312 とんでもないです。仕事で英語のドキュメンテーションをよく書いているのでどんどん慣れてきました。いい練習になってます。

**Comment by alexdima** [comment]
@raygo0312 I am having trouble reproducing the issue.

I have configured the following vscode settings:
```
"editor.fontFamily": "Arial"
```

I have installed the Japanese IME. It looks like this in the status bar of Windows:
  ![image](https://user-images.githubusercontent.com/5047891/99794079-ee80bd00-2b29-11eb-8939-cba29ee0a72d.png)

I open the editor and type the key labeled `A` on my physical keyboard, then the one labeled `E`:
![TO_UPLOAD](https://user-images.githubusercontent.com/5047891/99794270-330c5880-2b2a-11eb-9879-4b95c3635e09.gif)

The text of the IME and of the editor appear aligned. Also, the cursors appear aligned.

**Comment by raygo0312** [comment]
That state is the same as mine. The cursor is blue because I have changed the design. If you look closely at your image, you will see that there is a double white cursor. They are both white, so they are just not noticeable.

**Comment by raygo0312** [comment]
@alexdima Forgot to Mention.

**Comment by alexdima** [comment]
I've pushed a change which hides our cursor when the IME textarea is visible. This should make it that only one cursor is visible.
