### ISSUE TITLE
Git: Support optional branch picking in the repository picker

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#106664]

**Comment by joaomoreno** [comment]
Pushing this out, unfortunately.

**Comment by joaomoreno** [comment]
A `RemoteSourceProvider` can now optionally implemented `getBranches`:

```ts
export interface RemoteSourceProvider {
	getBranches?(url: string): ProviderResult<string[]>;
}
```

I've implemented it for our Github extension.

And when passing `branch: true` to the `git.api.getRemoteSources` API command, the user will be prompted to pick a branch, if the provider implements `getBranches`:

```ts
await commands.executeCommand('git.api.getRemoteSources', {
	providerLabel: (provider: RemoteSourceProvider) => `Test this for ${provider.name}`,
	urlLabel: `Test this for URL`,
	branch: true
});
```

And the result will be the following object instead of a string:

```ts
export interface PickRemoteSourceResult {
	readonly url: string;
	readonly branch?: string;
}
```
