### ISSUE TITLE
Extension debugging: breakpoints not hit if package.json has both "main" and "browser" property

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#106698]
VS Code 1.49 **Stable** (due to #106669 Insiders is unusable for me at the moment).

If a VS Code extension has both a "main" and a "browser" property (entry point) in its package.json, and the extension is debugged with debug type `"pwa-extensionHost"`  and `"debugWebWorkerHost": true`, I'm not able to hit all breakpoints.

If I rename the property "main" to "main2", breakpoints are hit without problems.

Steps:
- use vscode-mock-debug
- set a breakpoint in method "activateMockDebug:14" in "activateMockDebug.ts" 
- run the launch config "Web Extension"
- in the new workspace start debugging with F5 
- the breakpoint should be hit

Observe: it is not.
After renaming property "main" to "main2" in package.json, the breakpoint is hit.

I wonder whether this is a timing issue: a breakpoint in "mockDebug.ts:355" is always hit...

**Comment by connor4312** [comment]
Hm, I'm not able to repro this on 1.49.1; I pulled down mock debug, added `extensionKind: ["web"]`, and ran it. It looks like our instrumentation bp is working so we should be guaranteed to set the breakpoint in the activation before it's executed, avoiding any timing issues.

Can you enable `trace: true` and share the log file printed to the console?

**Comment by weinand** [comment]
Hmm, I did not add `extensionKind: ["web"]` because the extension published on the Marketplace does not have this, and it installs and works fine both in "serverless" and "desktop".

**Comment by connor4312** [comment]
Without adding the `extensionKind`, it looks like VS Code tries to load the non-web version, e.g. I haven't built the non-web version and I get an activation error

> Activating extension 'andreweinand.mock-debug' failed: Cannot find module 'c:\Users\Connor\Documents\Github\vscode-mock-debug\dist\ext\extension.js' 

I think this is as-designed (`web` being required).

However I actually was able to hit this _if_ I hit F5 fast enough after the debugged instance of VS Code was launched. What I see in the logs (highlighted lines) is that the mock debug is actually parsed and available before we're able to attach to the web worker extension host.

The alternative we have is to tell the browser to pause all new sessions until a debugger attaches to them. If I recall correctly I had some issues with that when I tried it earlier, but I can give it another shot. A less nice approach would be to add code in the web worker extension host to wait for a debugger to attach before running extensions if one is expected.

**Comment by connor4312** [comment]
> The alternative we have is to tell the browser to pause all new sessions until a debugger attaches to them. If I recall correctly I had some issues with that when I tried it earlier, but I can give it another shot. 

Oh, yes, the reason why this doesn't work is that attachment here is still async -- even if we ask for a pause, the renderer doesn't wait for the debugger before loading the page. Currently this doesn't happen and I don't think it can be done safely, since to do this we need to attach to electron and ask for all renderers to pause waiting on attachment. If the debugger or extension host exits ungracefully without removing this pause request, then any new webview or vscode instance the user opens will be frozen until they fully restart VS Code.

@alexdima what do you think about adding some mechanism in the web worker extension host that would wait for attachment? E.g. I could have js-debug set some global variable in the iframe when it's ready to debug and you could avoid activation before that's set (up to some reasonable timeout; should generally never take more than a second)

**Comment by alexdima** [comment]
> what do you think about adding some mechanism in the web worker extension host that would wait for attachment? E.g. I could have js-debug set some global variable in the iframe when it's ready to debug and you could avoid activation before that's set (up to some reasonable timeout; should generally never take more than a second)

That makes sense. The two methods where a delay/await could be added are:
- [`_startInsideIframe`](https://github.com/microsoft/vscode/blob/da13bb75621520267be23109b0341bf5d909585f/src/vs/workbench/services/extensions/browser/webWorkerExtensionHost.ts#L95)
- [`_startOutsideIframe `](https://github.com/microsoft/vscode/blob/da13bb75621520267be23109b0341bf5d909585f/src/vs/workbench/services/extensions/browser/webWorkerExtensionHost.ts#L182)

The latest state of things is that VS Code Desktop will run the web worker extension host outside an `<iframe>`, whereas the web bits will run it inside an `<iframe>`.

That piece of code runs on the UI thread of the page. Or do you mean that a delay needs to be added inside the web worker?

**Comment by connor4312** [comment]
I think we'd actually want something inside the worker, since attachment both to the worker and renderer is async -- we attach to the renderer, ask for its targets list (and to be notified of new targets), then whenever we see the webworker we attach to it. At that point there is still some initialization to do, since we create a new debug session for it and wait for VS Code to set that up and send up breakpoints before processing.

So something like

```js
if (isInDebugMode) {
  const deadline = Date.now() + 5000;
  while (typeof __jsDebugIsReady === 'undefined' && Date.now() < deadline) {
    await delay(5);
  }
}
```

I can take a shot at getting a PR in for October. Not sure how to transmit the debug state, but once I figure that out it should be easy

**Comment by alexdima** [comment]
PR most welcome. [Here](https://github.com/microsoft/vscode/blob/19c3db8ed47b728945b9b1b7f74b2df570bc407e/src/vs/workbench/api/common/extHost.protocol.ts#L87) is the init data that extension hosts receive from the UI. If none of the fields can cover this case, then that is the place where we can add more (optional) arguments.
