### ISSUE TITLE
Implement the DAP Invalidate request

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#106745]
A new `InvalidatedEvent` has been added to the DAP:  https://github.com/microsoft/vscode/blob/6781d16f05b2e93549675ec79a4ab2917c85faaa/src/vs/workbench/contrib/debug/common/debugProtocol.d.ts#L378-L393

This feature request asks for handling the event in VS Code and sending the corresponding `supportsInvalidatedEvent` property in the `initialize` request.

**Comment by weinand** [comment]
@isidorn I've added the new `InvalidatedEvent` to VS Code's `debugProtocol.d.ts`.

**Comment by isidorn** [comment]
Great. I can look into adding this. For now this event on the VS Code side would refresh the corresponding InvalidatedAreas and would probably automatically re-evaluate all watch expressions?
Also I am not sure if we need a different event for `stacks` and `threads`?

**Comment by weinand** [comment]
@isidorn yes, reevaluating the watches makes sense because they are unknown to the DAP.

> different event for stacks and threads
Yes, for VS Code stacks and threads are combined in one UI, but for other clients that might not be the case.

**Comment by isidorn** [comment]
Related DAP request https://github.com/microsoft/debug-adapter-protocol/issues/128

**Comment by weinand** [comment]
I've released "invalidated" event support in Mock debug. Just use the context menu action "Toggle between decimal and hex formatting".

**Comment by isidorn** [comment]
I have pushed a first version of this and it seems to work just fine.
Try it out and let me know how it goes

fyi @gregg-miskelly @testforstephen

![recording (2)](https://user-images.githubusercontent.com/1926584/93795429-a6344400-fc39-11ea-9d57-b9c05c60f257.gif)

**Comment by testforstephen** [comment]
Have a quick try on this new event, it works well. Thanks for your amazing work. @weinand @isidorn 

After i change the formatter setting, then send an invalidatedEvent to client, the whole variables view will be refreshed. One drawback is the Variables menu doesn't support icon. If icon is allowed, it's very easy to express the toggle effect since most of my formatter options are boolean. This is out of scope of this issue. If icon is viable, i can create a new issue for it.

![refreshVariables](https://user-images.githubusercontent.com/14052197/94397472-7e436400-0196-11eb-9c44-7d03c52d153e.gif)

**Comment by isidorn** [comment]
@testforstephen thanks a lot for trying it out. Based on your comment adding verified label.
As for the icons -> we do not support them, and we can not support them (electron does not support icons in native context menus). Though feel free to file a feature reuqest (though there might be something open already, I am not sure)
