### ISSUE TITLE
Disable wordBasedSuggestions when in TypeScript strict mode

### ISSUE THREAD

**Issue by cyrilletuzi** [microsoft/vscode#106802]
Hi and thanks for VS Code. 👍🏻 

Currently, `editor.wordBasedSuggestions` is enabled by default. This was useful in JavaScript projects where the autocomplete was partial due to a lack or loss of typings.

Now, in TypeScript projects in `strict` mode, it feels inappropriate as the editor suggests invalid code (for example properties that do not exist at all in an object). As all types are provided, completion is always available in TS strict mode, without the need to suggest everything and anything.

So it would be nice if it could stay enabled by default in JavaScript and non-strict TypeScript projects, but disabled by default in strict TypeScript projects.

**Comment by mjbvz** [comment]
Word based suggestions should only show in TypeScript files when no other suggestions are available. Does this match what you see? If not, can you share an example where word based suggestions are incorrectly offered?

**Comment by cyrilletuzi** [comment]
> Word based suggestions should only show in TypeScript files when no other suggestions are available.

Indeed. But when in TypeScript strict mode, suggesting everything and anything does not seem the right behavior even in that case. It usually means that something is `any`, thus the initial type should be fixed or casted.

To give you some context, the issue happens when I teach Angular trainings. There is an Angular property returning `any`, and so VS Code is proposing everything and anything, leading the students in the wrong direction. If on the other hand nothing was suggested, it would alert them, make them aware of the `any` issue and lead them to a better solution (in that case a cast).

**Comment by mjbvz** [comment]
Thanks.

I feel that making `editor.wordBasedSuggestions` depend on a language configuration may be pretty confusing since most of our settings are only controlled per language. There are places in TS files where you still may want word based suggestions even in strict mode, such as in strings and comments. 

I think telling your students to disable `editor.wordBasedSuggestions` is probably the best solution. You could also use a language specific setting to disable word based suggestions just in TypeScript files:

```json
"[typescript]": {
    "editor.wordBasedSuggestions": false
}
```
