### ISSUE TITLE
Quick pick: selecting entry with keyboard does not put focus back to editor

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#106824]
Steps to Reproduce:

1. use the language mode picker to pick a language for an untitled file
2. use the mouse to select an entry and focus moves back to the editor
3. do it again and use the keyboard (pressing enter) on an entry

=> 🐛 focus is not moving in to the editor

I think it would make sense to be consistent here and always move focus back to the editor, especially given the picker is changing the editor so you are likely to continue to type afterwards.

**Comment by chrmarti** [comment]
This happens when clicking the mode picker in the statusbar because the QuickPick remembers the previous focus element. Not sure why with the mouse the focus goes to the editor, but since the mode picker knows that its target is the current editor, maybe it is the mode picker that should set the focus to the editor.

I'll look into the inconsistency.

**Comment by susiwen8** [comment]
@chrmarti Hi I have a solution for this issue, could you review my PR?
