### ISSUE TITLE
Intellisense inside code snippet fields

### ISSUE THREAD

**Issue by jnooree** [microsoft/vscode#106837]
When a code snippet is inserted, for instance, in python:
<img width="115" alt="image" src="https://user-images.githubusercontent.com/63093572/93306208-861c1380-f83a-11ea-92d6-14047caf57df.png">
No autocompletion is provided in the field (the shaded part). I think it would be better to show the autocompletion drop-down menu even inside the code snippets (or at least, an option to turn that feature on).

**Comment by jrieken** [comment]
When a snippet is active, IntelliSense as you type (aka quick suggestions) is disabled. That is because there is a conflict between the <kbd>Tab</kbd>-key which moves to the next placeholder but also accepts a completion. You wouldn't be able to type in a placeholder and then move to the next placeholder as you would accept a suggestion then. You have the following options

* change the default via the `editor.suggest.snippetsPreventQuickSuggestions`-setting
* in snippets trigger suggestions manually (via Ctrl+Space, Alt+ESC (macOS), or `ctrl/cmd+i`)

**Comment by jnooree** [comment]
Thank you for such a fast feedback. I didn't knew that there was already a setting related to this!

**Comment by xgdgsc** [comment]
I think snippetsPreventQuickSuggestions should be false by default. I hardly use snippet tab switching. Can' t it just prioritize completion over move to next placeholder by default?
