### ISSUE TITLE
Node.js: Successive DNS Requests Fail with Message "Canceled"

### ISSUE THREAD

**Issue by raymondlaw** [microsoft/vscode#106821]
- VSCode Version: 1.49
- Node Version v14.3.0
- OS Version: Windows 10

Steps to Reproduce:

Run this Node.js code (once or twice sometimes it works, more often it prints Canceled)

```js
const dns = require("dns");
const venus = "venus.cs.qc.cuny.edu";
const mars  = "mars.cs.qc.cuny.edu";

dns.resolve(venus, after_venus);
console.log("Prints Immediately 01");
function after_venus (err, records){
    if(err){
        console.error("Failed to resolve", venus);
    }
    else{
        console.log(venus, records);
    }
}

dns.resolve(mars, after_mars);
console.log("Prints Immediately 02");
function after_mars(err, records){
    if(err){
        console.error("Failed to resolve", mars);
    }
    else{
        console.log(mars, records);
    }
}
```

![Capture](https://user-images.githubusercontent.com/2231426/93293042-06983100-f7b5-11ea-99e6-4acba3beaf18.PNG)

Notice the output prints the message "Canceled" despite it never appearing in the code, it's also blue signaling it's a string?
When I run this program from within Terminal everything works as expected, it is only in VSCode that there is an issue.

I've tested with various domains, the problem persists

If the request actually failed, the error messages should print, not this arbitrary string Canceled

I tested with on a separate machine running 1.42 and everything works no "Canceled" message prints, 
I then upgraded to 1.49 and upon upgrading the behavior is reintroduced which at least to me confirmed the problem was within vscode.

Does this issue occur when all extensions are disabled?: Yes

**Comment by connor4312** [comment]
Thanks for the issue and repro. This is a variation of https://github.com/microsoft/vscode-js-debug/issues/161, I'm guessing the old debugger just exited slightly slower which made you not hit this. There are a couple things you can do to work around it (pick one):

- Set `"outputCapture": "std",` in your launch.json, so that output is given as a simple string and not subject to races
- Set `"console": "integratedTerminal"` to run the program in a real terminal where output is not handled through the debugger

/duplicate
