### ISSUE TITLE
explore sidebar title should left align with file icon

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#106845]
When there is only `Folders` section in explore sidebar, title should left align with file icon.

![93023082-1978fd00-f61f-11ea-9e29-46fc6a0d0b96 (1)](https://user-images.githubusercontent.com/41773861/93317120-a7cbc980-f83f-11ea-9df0-2c7ad89eb79e.png)

**Comment by misolori** [comment]
We do actually align the items in the explorer with the title:

![image](https://user-images.githubusercontent.com/35271042/93363624-5d752900-f7fc-11ea-820f-74ad9a3a0258.png)

![image](https://user-images.githubusercontent.com/35271042/93363794-97462f80-f7fc-11ea-98bd-c0339c9aae89.png)

It seems your file theme is disabling the tree chevrons, which is why it's not aligned
