### ISSUE TITLE
"Could not load source" error when attempting to use JavaScript debugging auto-attach

### ISSUE THREAD

**Issue by aslatter** [microsoft/vscode#106803]
- VSCode Version: 1.49.0
- OS Version: Windows 10 2004

Steps to Reproduce:

1. Create a demo TypeScript project, with the following settings:
 + 'sourceMap' set to 'true'
 + 'outDir' set to './dist'
 + 'rootDir' set to './src'
 + Have 'typescript' set up as an npm "dev" dependency
2. Create a basic 'src/index.ts' file
3. Build the project (`npx tsc -p .`)
4. Enable "Auto Attach"
5. Set a breakpoint
6. In the terminal, run `node dist/index.js`

Then, my program starts, the debugger attaches, and execution stops at any breakpoints I have set. However instead of seeing my TypeScript code I see a new buffer open with the text:

```
Could not load source 'c:\Users\some_username\AppData\Local\Programs\src\index.ts': Unable to retrieve source content.
```

My project is not located in 'AppData\Local', so I'm not sure why VS Code thinks it should look there for sources.

If I look for paths in "dist/index.map.js" I see the property `"sources":["../src/index.ts"]` in the map.

If I repeat the above workflow with the terminal created from the "Create JavaScript Debug Terminal" command the correct source-file is loaded and I do not see the error.

Does this issue occur when all extensions are disabled?: Yes

**Comment by connor4312** [comment]
Thank you for the nice issue. This is fixed in the latest version of the debugger. For this month you have three options, in order of preference:

1. Grab the upcoming [nightly build](https://github.com/microsoft/vscode-js-debug#nightly-extension) of the debugger which will be available in about an hour from now
1. Use the old version of auto attach (available in the next release only) by setting `debug.javascript.usePreviewAutoAttach: false`
1. Set `rootDir` in your tsconfig to be an absolute, rather than relative path.

**Comment by aslatter** [comment]
lgtm on nightly. Thanks for the quick turnaround.

**Comment by AnthonyScottMoncrieff** [comment]
I too am getting this issue, although it is looking in my userprofile, and setting the rootDir doesn't work

**Comment by connor4312** [comment]
@AnthonyScottMoncrieff please create an issue using the template here: https://github.com/microsoft/vscode-js-debug/issues/new/choose

**Comment by AnthonyScottMoncrieff** [comment]
^^ https://github.com/microsoft/vscode/issues/108208
