### ISSUE TITLE
Web: running yarn commands from integrated terminal auto-attaches

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#106983]
Ever since 2 days or so when I run `yarn <something>` my VSCode web enters debug mode.

**Comment by weinand** [comment]
@bpasero does it help if you set the "Auto Attach" mode in the status bar to "Only with flag" or "Disabled"?

**Comment by bpasero** [comment]
Doing so works, but the console shows this error:

```
~/Development/Microsoft/monaco> yarn valid-layers-check
yarn run v1.22.4
$ node build/lib/layersChecker.js
Debugger listening on ws://127.0.0.1:57706/14d129f0-0e07-41d7-b25e-4de2451d9d0b
For help, see: https://nodejs.org/en/docs/inspector
Error activating auto attach, please report to https://aka.ms/js-dbg-issue
```

**Comment by connor4312** [comment]
> ~/Development/Microsoft/monaco> yarn valid-layers-check
> yarn run v1.22.4
> $ node build/lib/layersChecker.js

In this case this is working correctly -- the yarn script is running a user-authored node script, for which smart attach mode will want to smartly attach to.

However, there was an issue where auto attach defaulted to on with "smart" mode; I had updated some settings in auto-attach but did not bump js-debug at the same time. This is fixed in https://github.com/microsoft/vscode/commit/75e55d195fc7ddc764b2b720244fe788bbce39ba.
