### ISSUE TITLE
load keybindings.json from .vscode dir if there is any ?

### ISSUE THREAD

**Issue by mahald** [Microsoft/vscode#10708]
- VSCode Version: 1.4.0
- OS Version: Windows 10 Latest

Not sure wheter it's a good idea, however for me it would make sense to put the keybindings.json into the .vscode dir, so all devs get the same keybindings on the project.

maybe it should load it from .vscode (if a dir is openend), then from the user location (and overwrite if conflicting). or is it already possible to define keybindings in the .vscode dir (didn't work as i just put the keybindings.json into it)?

**Comment by alexandrudima** [comment]
@mahald The current recommended way of sharing keybindings is via extensions in the marketplace. You can create an extension that only adds keybinding rules. See for example https://github.com/Microsoft/vscode-sublime-keybindings

The reasons we don't want to load keybindings from the `.vscode` folder:
* the current overwriting story for settings (which are part of the `.vscode` folder) is: default settings -> user settings -> workspace settings. This means that when you change a setting in the `.vscode` folder for a workspace, there is no way to change it further, it is "locked" in this folder. We believe this makes sense when used responsibly (e.g. it is impolite to set `editor.fontFamily` in the workspace settings as people like to use different fonts, but it makes sense to set `files.eol` as it relates to files in the workspace).

* if we would add keybindings reading from the `.vscode` folder, to avoid confusions, it should behave the same. But that would make it impossible for a user to change their keybindings for a certain workspace. We believe that keybindings are personal and not workspace bound, as a dev could work with multiple workspaces and would like to maintain the same keybindings. Keybindings are overwritable: default keybindings -> extension keybindings -> user keybindings.

* if we would add keybindings reading from the `.vscode` folder, we would need to change the file format to accomodate expressing variants across OSes. Since a workspace could be worked upon from developers using Windows, or developers using OSX, or using Linux, we would need to expand the file format (to be more similar to the extension keybindings).

All in all, we don't believe this would add much value and it would possibly make things more confusing for the majority of cases. Therefore, we recommend sharing keybindings via extensions.
