### ISSUE TITLE
Help PowerShell debugger to auto expand variables and keeping it expanded

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#10705]
When using the PowerShell debugger I noticed that the 'Auto' scope in the variables view collapses a lot on stepping.

![2016-08-19_12-00-47](https://cloud.githubusercontent.com/assets/1898161/17806414/adcd404c-6604-11e6-985a-32677d256636.gif)

This makes stepping through code a pain. We should help the PS team to improve this or fix any VS Code issues that lead to this behavior.

/cc @daviwil @rkeithhill

**Comment by rkeithhill** [comment]
I thought this used to work back in the pre 1.0 VSCode releases. Anyway, YES I would love to get this fixed! Should have time this weekend to work on it.

**Comment by weinand** [comment]
@rkeithhill I did not mean that you have to fix this; it is assigned to us ;-)
I just played with the PowerShell extension on macOS (which BTW works great), and noticed the collapse issue.

**Comment by rkeithhill** [comment]
Ah, well much thanks in advance then!! 😊

**Comment by daviwil** [comment]
Thanks a lot for offering to help with that!  Honestly I hadn't even noticed it that much but it'd be great to have that not closing so often.  You guys rock!

**Comment by isidorn** [comment]
The code which automatically expands first scope after each step is [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/debugViews.ts#L125)
So it should work if the `Auto` scope is marked as `expansive === false`

**Comment by isidorn** [comment]
And I am also very happy that I will no longer have to spin up my win VM to look into powershell debug issues 😊

**Comment by daviwil** [comment]
Haha, me too!

**Comment by rkeithhill** [comment]
@weinand We fixed this in the 0.7.1 release of the PowerShell extension.  We were incorrectly setting `expensive` to `true` for the `Autos` container.  I believe you can close this issue now.

**Comment by weinand** [comment]
@rkeithhill great, thanks!

**Comment by rkeithhill** [comment]
@weinand With either VSCode 1.5.0/1/2 debug hover tips stopped working in the PowerShell extension. 
https://github.com/PowerShell/vscode-powershell/issues/302 

If I change the `Auto` scope's `Expensive` property back to True, we get debug hover tips but then the pseudo-scope is not opened by default when debugging.  However, once I do open it, it at least stays open (on 1.5.3).  Any ideas on this?  

It really seems like `Expensive` should be set to False (because it isn't expensive to get the variables for this pseudo-scope).  That said, not having debug hover is very painful.  And no, we can't turn on the supportsEvaluateForHovers because there would be side-effects.

**Comment by isidorn** [comment]
@rkeithhill the debug hover should work even if a scope is expensive. Is the variable name you are hovering over is unique across multiple scopes - if not then due to the lack of language knowledge we are not showing anything since we can not know over which exact variable is the user hovering over.
However if the name is unique then this is an unrelated bug on the vscode and please create a new issue for this.

On a side - I tried debugging powershell on my os x and failed. I just installed the latest os x package from https://github.com/PowerShell/PowerShell/releases and tried debugging from vscode but got the debug adapter crashed errors. Am I missins something here or should I file a bug on your repository?

**Comment by rkeithhill** [comment]
See this [page on OS X install instructions](https://github.com/PowerShell/PowerShell/blob/master/docs/learning-powershell/using-vscode.md).  There's an issue with open ssl and the extension.  You may need to `brew install openssl`.  

Unfortunately, our `Auto` variable container will contain duplicates of variables that are in the `Local` scope.  That's because PowerShell provides a ton of "local" variables that make it hard for the user to see "their" local variables.  So `Auto` provides a view of "their" local variables.  

The two scopes we are setting to "not expensive" are Auto and Local.  That's exactly where dupes would appear.  But then why would setting `Auto` back to expensive fix debug hover?  At that point, the only non-expensive scope would be `Local`.

I can imagine other debuggers having something like an `Auto` scope.  It might be nice to be able to designate a scope as a "pseudo-scope" or "pure container" i.e. not a scope but a container of variables related in some other way than scope.  Another idea is that VSCode could provide the `Auto` container and debug servers could decorate a variable indicating it should be shown in that container.

**Comment by isidorn** [comment]
Debug hover does not look inside expensive scopes and as a side effect this all works. If debug hover would look inside expenive scopes the hover would be considerably slower.
I think this might be the original reason why you guys put the auto scope as expensive. 

And yes we might need a way to specify a scope which is not expensive but should be hoverable, for that please create a feature request for a protocl change and ping @weinand 
Though a proper way to solve this is to add more lanugage understanding to vscode's debugger which we plan to tackle in the future.

**Comment by rkeithhill** [comment]
> I think this might be the original reason why you guys put the auto scope as expensive. 

I suspect you're right on that.

OK I'll file a request.  BTW yet another option might be an explicit "open this scope by default" field on Scope objects.  Sort of an override of the internal check for expensive scope to determine if a variable scope should be opened by default.

**Comment by isidorn** [comment]
I think that other option might be better, at least I prefer it.

**Comment by rkeithhill** [comment]
Enh req submitted https://github.com/Microsoft/vscode/issues/12651
