### ISSUE TITLE
SCM Repositories view cleanup

### ISSUE THREAD

**Issue by raschan** [microsoft/vscode#107145]
This would be a continuation of this: https://github.com/microsoft/vscode/issues/104151#

Thank you, for more or less bringing back the old View of the SCM panel, I really appreciate it 🙏

I still have one detail, that is bothering me a lot: in the old view, all the options and extensions were only visible on the "Changes" pane, leaving the different repos looking clean. My major problem with new look was this clean space got cluttered, and sadly this change doesn't really solve that.

I'm not sure if it is doable, but if it is, could we please have it back that all the various options are:
a) selectable (so I can turn it off, if I don't need it)
b) only appear on the selected Source Controls and not in the Source Control Repositories section.

Until this can happen (or confirmed that it is impossible), I'm gonna go back to 1.46, hopefully temporary.

for reference, this is how it looks like for me:
![Screenshot 2020-09-18 at 16 26 38](https://user-images.githubusercontent.com/6605186/93609360-0cb42a80-f9cc-11ea-8c2a-d58b97e52d35.png)

and how it looked like in 1.46
![Screenshot 2020-09-18 at 16 39 50](https://user-images.githubusercontent.com/6605186/93610712-b8aa4580-f9cd-11ea-9eea-ab44997fb21a.png)

**Comment by astrowonk** [comment]
+ 1. All that chrome is distracting and it'd be great to clean it up back to the 1.46 look.

**Comment by mikestopcontinues** [comment]
I agree with the sentiment, but I disagree with the solution. Some of the new buttons are useful. Here's some ideas:

1. Ellipsis menu — This is powerful. How about adding all of the features in this menu to row context menu? Additionally, all of the features of the buttons should be added to the menu, so that regardless of other changes, you can access the functionality.
2. Refresh button — How about just one refresh button at the top of the sidebar? I'm ok with only being able to refresh all repos at the same time.
3. Commit button — This shouldn't appear in the Repos view since it doesn't do anything, and it should only appear in the Changes view when (a) there are staged changes and (b) There's a message in the input. To that end, it would be even better to but this icon next to the message input.
4. Branch button — I like this one. But for people who don't, how about offering the option to `alwaysShow`, `showOnHover`, or `neverShow`.
5. Changes — I like this one too. I would offer the same options as for the branch button.

Thoughts? 

(Also, @joaomoreno thanks for working on the sidebar. Some of the new features have made it easy for me to consolidate my workflow into VSCode.)

**Comment by raschan** [comment]
@mikestopcontinues imho any button on the `Repositories` view are just clutter and redundant with buttons on `Changes` view (see screenshot)
![Screenshot 2020-10-30 at 14 25 52](https://user-images.githubusercontent.com/6605186/97710344-f1086d80-1abb-11eb-95de-8e78f4009e9d.png)

That being said, I do agree with having options to toggle the visibility.

@joaomoreno any update maybe on when this could be scheduled in for work?

**Comment by lszomoru** [comment]
Starting with VS Code 1.86 (already available in VS Code Insiders) users are now able to right click on actions and pick to hide them. Only actions that cannot be hidden are checkout, and sync. Actions can be hidden independently in the "Source Control Repositories" and "Source Control" views.

**Comment by TheophileMot** [comment]
@aiday-mar I see this issue was added to the Dec/Jan 2024 milestone, and it's currently closed, but the problem still remains. Do you know if there is any intention to address it?

Or is there another way to remove unwanted icons? In earlier versions of VSCode, it was possible to customize the CSS, so it was easy to hide them (e.g., using `display: none`). This is how I used to manage the interface, but that feature got taken away...

**Comment by aiday-mar** [comment]
Hi @TheophileMot thank you for posting your concern. I am not sure what the state of this issue is, you would have to ask @lszomoru about it. I added this to the `December / January 2024` milestone because it was initially assigned to it, and then at some point I deleted the milestone, so I had to assign it back.

**Comment by lszomoru** [comment]
@TheophileMot, could you please provide a screenshot with the exact icons that you cannot hide? Thanks!

**Comment by TheophileMot** [comment]
@lszomoru Certainly; here's what I mean:

<img width="690" alt="image" src="https://github.com/microsoft/vscode/assets/34871447/6777357e-3b40-47a9-82cb-48aa7132f94e">

In practice, I only ever use one of the buttons ("Compare with HEAD"), so I would ideally like to hide the remaining five. To motivate the request:
* The extra icons are visual clutter;
* In particular, when the side panel is narrow, as mine often is, the icons take up so much space that they hide the branch name entirely;
* There is the possibility of clicking on the wrong action by accident;
* The icons are all so similar (arrows going in a circle) that to make sure I'm clicking on the right one, I need to look at the tooltip, but this means waiting a second for the tooltip to appear, which adds an unnecessary delay and distraction.

Thanks for looking into this!

**Comment by TheophileMot** [comment]
@lszomoru Ah, I see! Thank you for the explanation (and sorry for any confusion); for some reason I thought it was a built-in feature. I'll raise an issue in that repo.
