### ISSUE TITLE
Extension list, clicking on multiple extensions quickly loads them twice

### ISSUE THREAD

**Issue by lintaba** [microsoft/vscode#107104]
probably a promise cancel would be useful

![image](https://user-images.githubusercontent.com/375078/93709877-558def80-fb42-11ea-8d35-c2ea2ff386ae.png)

**Comment by sandy081** [comment]
@mjbvz Not sure in which layer this issue is, are you familiar with this?

**Comment by mjbvz** [comment]
The extension editor probably needs to way to cancel the web request to get the extension readme (or cancel the rendering of the markdown after the request is made). A good starting point is here:

https://github.com/microsoft/vscode/blob/175730751395dbb5526c89413ea7d29df74cdf3e/src/vs/workbench/contrib/extensions/browser/extensionEditor.ts#L840

**Comment by darkred** [comment]
Hoping that my STR below is helpful to you (also see the video capture at the end):

- launched VSCode 1.49.2 (x64 in win 10)
- immediately switched to the Extensions tab,
- noticed there was an update available for one of my installed extensions (AutoHotkey Plus),
so the focus automatically was on the 1st tab, 'Details', for that extension.
- quickly switched to the 'Changelog' tab while the 'Details' hadn't completed loading yet(because my internet connection was slow/busy at the moment), 
- noticed that the contents of 'Details' appeared mixed up with/on top of the 'Changelog' contents.

When I switched back to the 'Details' tab there no text on top of each other anymore.


[video.zip](https://github.com/microsoft/vscode/files/5288268/Video_2020-09-27_152841.zip) (1.7 MB, zipped)

**Comment by jeanp413** [comment]
Created a PR https://github.com/microsoft/vscode/pull/110370 to fix this
