### ISSUE TITLE
Ability to toggle warnings and problems squiggly lines

### ISSUE THREAD

**Issue by codesnik** [microsoft/vscode#107217]
Squiggly lines are severely impeding my ability to read code, they are very distractive. One thing is warnings on code I'm writing or where I at least have a word in styleguides, other thing is reading code of 3rd party library. It looks like the only way to disable them is to actually disable all the linting extensions. There should be something less drastic, "hide warnings" or something like that. Setting on project or on individual opened file buffer would work.

**Comment by alexdima** [comment]
On the editor side, there is a setting `editor.renderValidationDecorations`, but that is currently always configured to be `"on"` for editors in the workbench due to https://github.com/microsoft/vscode/issues/89057.

@bpasero we might consider changing the default of the editor (to be`"on"` by default). But as it is right now, when I configure `"editor.renderValidationDecorations":"off"`, it always gets set again to `"on"` by the workbench.
