### ISSUE TITLE
Multiple debuggers

### ISSUE THREAD

**Issue by wallverb** [Microsoft/vscode#10728]
- VSCode Version: Code - Insiders 1.5.0-insider (3d9622208b2167921b6664e04fd1fbd51507a4a0, 2016-08-19T06:04:28.517Z)
- OS Version: Darwin x64 15.6.0

Nodejs debugger = awesome
Chrome debugger = awesome
Not sure if possible, but would be nice to be able to run both backend (nodejs) debugger and frontend(chrome debugger) at the same time.

**Comment by weinand** [comment]
@wallverb each VS Code window can run its own debugger. So if you open another window you can run the node and the chrome debugger at the same time.
But since you cannot open a single project in multiple windows, it is not yet (easily) possible two run more than one debug session on a single project.
Workaround: open a new VS Code window on a sub folder in your project.
