### ISSUE TITLE
Indent always changing to Spaces: 2

### ISSUE THREAD

**Issue by dimritium** [microsoft/vscode#107376]
Even after saving settings to set indent as Spaces: 4, restarting vs code changes it back to 2 everytime

Version: 1.49.1 (user setup)
Commit: 58bb7b2331731bf72587010e943852e13e6fd3cf
Date: 2020-09-16T23:27:51.792Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by kieferrm** [comment]
Pls provide concrete steps. Thank you!

**Comment by rmunn** [comment]
Is there a .editorconfig file in your project that's set to use 2 spaces? That overrides your user settings for that particular project.

**Comment by dimritium** [comment]
@rmunn I guess I found a way to reproduce the issue.

First I create a react project using ```npx create-react-app demo```

Then inside ```src``` folder all ```.js``` files have space 2 and if I set indent to spaces:4 it auto resets to 2 after restarting VS code

This only happens to files created by npx, If I add my custom files, they stay at 4 indent spaces.

And I do not see .editorconfig file.

Version and system info:

Version: 1.49.1 (user setup)
Commit: 58bb7b2
Date: 2020-09-16T23:27:51.792Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by rmunn** [comment]
In your VS Code settings, is the setting "Editor: Detect Indentation" turned on? If so, then when you open a file that uses different indentation than your configured indent size (such as the .js files created by npx, because 2-space indent seems to be a *de facto* standard in Javascript), VS Code will say "Okay, indent size is configured to be 4 but this file obviously has 2-space indents, so I'll change indent size to 2 for just this file." And you don't have to restart VS Code to see it change: change the indent to 4 for that file by clicking on the "Spaces: 2" text in the lower right, then close and reopen the file and it will be back to "Spaces: 2" because "Editor: Detect Indentation" works on every opened file.

Turn that setting off and you should see your 4-space indent size being used even when a file's contents already have a different indent size such as 2. (Though then you'll need to edit the file to change the indent size of the existing code, otherwise you'll end up with a messy file after editing it.) If that's the case, then this isn't a bug, but a config setting working as designed, and you just need to turn that setting off to get the behavior that you want.

**Comment by dimritium** [comment]
I turned off my "Detect Indentation" setting, then I changed the file to use Spaces 4 but still whenever I reopen the file I see indent being spaces 2 for the files created using npx.

How do I change the settings so that the npx created files also have indent as Spaces 4? I want my global setting to override.
Is it good to have such a setting?

I again created a project by turning off "Detect indentation" but still npx created files are at Spaces 2.

It never seemed to happen before, feels like a recent change. I may be wrong though.

**Comment by rmunn** [comment]
You could create an [.editorconfig file](https://editorconfig.org/) in the root of your project that says "Use 4-space tabs for .js files" (or for any extension) if you want. I don't know if npx has a setting to have it make 4-space-indented files when it creates a project, but that's a bit off topic here anyway. But if you have the "EditorConfig for VS Code" plugin installed, then you can use .editorconfig files in your project to set indent settings on a per-file basis (e.g., you might want 4 spaces for certain file types and 2 spaces for others. VS Code's settings aren't granular enough, but .editorconfig can do that).

**Comment by dimritium** [comment]
Okay I will use editorconfig then, so this issue is not related to VS code? Shall I close this?
