### ISSUE TITLE
`ifdef` keyword in middle of a statement is not highlighted in vscode

### ISSUE THREAD

**Issue by wsrfad** [microsoft/vscode#107344]
- VSCode Version: 1.49.0
- OS Version: Linux x64 3.13.0-71-generic

REPRO
```
class TestClass {
    int m_x;
    #ifdef FLAG  // This ifdef keyword is highlighted
    int m_variable_used_when_flag_enabled;
    #endif
    TestClass(int x) : m_x(x) 
    #ifdef FLAG // This ifdef keyword is NOT highlighted
        ,m_variable_used_when_flag_enabled() 
    #endif
        {
            
        }
};
```

Does this issue occur when all extensions are disabled?: YES

**Comment by wsrfad** [comment]
In my opinion, this is not covered by the specified issue

**Comment by rioj7** [comment]
They have different TextMate scopes

```
class TestClass {
    int m_x;
    #ifdef FLAG  // keyword.control.directive.conditional.ifdef.cpp
    int m_variable_used_when_flag_enabled;
    #endif
    TestClass(int x) : m_x(x) 
    #ifdef FLAG // meta.head.function.definition.special.constructor.cpp
        ,m_variable_used_when_flag_enabled() 
    #endif
    {
        #ifdef FLAG // keyword.control.directive.conditional.ifdef.cpp
        m_variable_used_when_flag_enabled = 5;
        #endif
    }
};
```

**Comment by alexr00** [comment]
Moved to the repo where we get our C++ syntax highlighting grammar: https://github.com/jeff-hykin/cpp-textmate-grammar/issues/505

**Comment by alexr00** [comment]
@wsrfad regarding your question about closing this bug [here ](https://github.com/jeff-hykin/cpp-textmate-grammar/issues/505#issuecomment-700738387), we have several reasons:

- The bug is in a VS Code dependency, so it makes the most sense to have the bug in the repo that owns the dependency.
- Every year, we in VS Code go through literally every single open issue in our repository (as of time of writing there are 5,389). This takes a lot of time, so if a bug doesn't need further addressing, then it should be closed. Instead of spending time reading the same issue again, we can work on other features and bugs.
- Open issues are reserved for things we can address, we have limited power or expertise over upstream bugs.

**Comment by wsrfad** [comment]
I understand the point 1 is applicable in this case, which is bucketing into correct node. I don't seem to understand why (2) and (3) have been mentioned. Otherwise, I would suggest using priorities, so you can query the opened issues and address them accordingly
