### ISSUE TITLE
debug.openDebug not working in certain cases

### ISSUE THREAD

**Issue by OkazakiNagisa** [microsoft/vscode#107354]
- VSCode Version: 1.49.1
- OS Version: Windows 10 2004 x64

Steps to Reproduce:

1. Use these settings:
```
"debug.openDebug": "openOnSessionStart",
"debug.openExplorerOnEnd": true
```

2. Launch a debugging session, then restart current debugging session.

3. Sidebar will switch to explorer, which is not expected.

Does this issue occur when all extensions are disabled?: idk because if then there will be no debug adapters to use.

**Comment by isidorn** [comment]
I acknowledge this issue.
The problem is that restart does not respect the `openDebug` flag, and it respects the `openExplorerOnEnd` since restart shares regular path when a session goes down.

No immediate plans to fix this. Though a valid bug so assigning to backlog and might tackle in the future.
