### ISSUE TITLE
Behavior of ArrowUp/ArrowDown in filter/search boxes

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#107458]
Issue Type: <b>Bug</b>

Focus filter box in the Problems or Debug Console panel:
- <kbd>Cmd</kbd>+<kbd>ArrowUp</kbd> == preview filter
- <kbd>Cmd</kbd>+<kbd>ArrowDown</kbd> == next filter
- <kbd>ArrowUp</kbd> == move keyboard focus in the "toolbar" to the left
- <kbd>ArrowDown</kbd> == move keyboard focus in the "toolbar" to the right

Focus search box in the search sidebar:
- <kbd>Cmd</kbd>+<kbd>ArrowUp</kbd> == preview search
- <kbd>Cmd</kbd>+<kbd>ArrowDown</kbd> == next search
- <kbd>ArrowUp</kbd> == preview search when cursor is on the first line or move cursor one line up
- <kbd>ArrowDown</kbd> == next search when cursor is on the last line or move cursor one line down

We should have the same behavior in all places although Problems and Debug Console don't support multi-line. @meganrogge is now adding history to the SCM commit message box, so we'll have a forth place, and it supports multi-lines.

VS Code version: Code - Insiders 1.50.0-insider (ddc98c3f620ab1d2ecad5942ebf4736060403d67, 2020-09-25T05:30:51.469Z)
OS version: Darwin x64 18.7.0
Remote OS version: Linux x64 5.3.0-1020-azure

**Comment by isidorn** [comment]
I believe i have fixed this via 785f9ce8e4
@kieferrm let me know if you still see issues with VS Code insiders from Tuesday. Thaks

**Comment by rzhao271** [comment]
Setting this issue to verified because arrowup/arrowdown works, at least.

However, in search, ctrl+arrowdown refocuses on search results, and then following that by ctrl+arrowup/arrowdown scrolls the results up or down. The attached gif also shows it inconsistently going back to the search toolbar.
If this isn't the intended behaviour of ctrl+arrowup/arrowdown in search, we should open a new bug for it.
![arrowkeydown-verify](https://user-images.githubusercontent.com/7199958/94848516-f731fe00-03d8-11eb-881a-4b37b0b7996b.gif)

**Comment by isidorn** [comment]
fyi @JacksonKearl and @roblourens for search

**Comment by roblourens** [comment]
Once you are in the list, then normal list keybindings take effect like ctrl+up/down to scroll. That is by design but yes, it combines a little awkwardly with the ctrl+down to focus search results. It can be customized if you want something different.
