### ISSUE TITLE
"Code" creates non-UTF8 file name on Linux with zero length of data

### ISSUE THREAD

**Issue by CodeTrol** [Microsoft/vscode#10745]
- VSCode Version:
1.4.0
- OS Version:
GNU/Linux Ubuntu 14.04
Steps to Reproduce:

1.  Open any directory with Visual Studio Code

![visual studio code_014](https://cloud.githubusercontent.com/assets/6751374/17832574/f24ba988-670e-11e6-8ace-1556866c25bc.png)

Each time when I remove the 1st file from file system it gets back if to open Visual Studio Code again.

**Comment by bpasero** [comment]
I am very sorry to hear you are having issues with VS Code. I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by CodeTrol** [comment]
Yes, you're right. One of installed extensions does this, not Visual Studio Code itself. Sorry for the alarm.
