### ISSUE TITLE
Markdown footnote is underlined and gives right-click option to `Execute command`

### ISSUE THREAD

**Issue by robenkleene** [microsoft/vscode#107471]
(Apologize in advance if this is the wrong place to file this, I'm having trouble tracking down the right place.) When I make a Markdown footnote, like `[^ioshasinnovativeapps]: I don't want` the first word or letter is underlined and when I right-click it it offers to `Execute command`.
<img width="473" alt="image" src="https://user-images.githubusercontent.com/1058778/94300184-a03eab80-ff36-11ea-83ac-9cc2b5e52b62.png">

**Comment by mjbvz** [comment]
VS Code's built-in markdown extension targets standard markdown, which doesn't include footnote support. As a compromise, could update the regular expression it uses to support clickable links in markdown files to exclude links starting with `^`

Starting point in code: 

https://github.com/microsoft/vscode/blob/fdf23dc5f95f4a17b246dbebc9af14dab5043334/extensions/markdown-language-features/src/features/documentLinkProvider.ts#L108

**Comment by robenkleene** [comment]
Yeah, thanks. That's an understandable perspective. I might do a PR for this myself. One question that still confuses me though, why does it say "Execute command" (and not "Follow link" like other links show).
<img width="597" alt="Follow Link" src="https://user-images.githubusercontent.com/1058778/94303427-c9156f80-ff3b-11ea-9fcb-a13f4f1a25a5.png">

**Comment by Nafana** [comment]
@robenkleene  First day looking at the code base, so I could be off on this, but looks like the logic for when "Execute Command" is displayed is in this function:
https://github.com/microsoft/vscode/blob/200296d6e6efba09a84b00003dbdf975ceb93739/src/vs/editor/contrib/links/links.ts#L32

Also, are you planning on doing a PR for this still? If not I can do it.

**Comment by robenkleene** [comment]
@Nafana Thanks for the additional info!

Please go ahead if you're ready to work on a PR now.

**Comment by Nafana** [comment]
@mjbvz I may be wrong about this, however it seems to me the problem is with how `LinkProvider` validates a definition link. In the image below notice how the last line is considered valid, and would have a tooltip and underline in the editor.

![old-regex](https://user-images.githubusercontent.com/25810344/94887569-8962f200-042b-11eb-8304-077c810a9b6b.png)

The regex produces a valid match since the last capture group ignores everything past the first space after the link. What if we modified the expression to something like this? (tests pass)

![link-provider-proposal](https://user-images.githubusercontent.com/25810344/94887084-2cb30780-042a-11eb-8537-7a196b5c2d5c.png)

**Comment by mjbvz** [comment]
Yes looks like the regular expression may just need to be updated, either to check that there are not multiple words after the references or to check that the definition does not start with  `[^]`
