### ISSUE TITLE
Feature request: bold_folder_labels setting like Sublime's

### ISSUE THREAD

**Issue by zertosh** [Microsoft/vscode#10748]
I really appreciate the minimal UI, however, I really do miss Sublime's `bold_folder_labels`. It does just that - makes folder labels bold - adding a distinguishing characteristic between them and files. This helps a lot when:
- Dealing with long file and folder names, since it's no longer necessary to visually scan the entire right-to-left range of an item to determine what it is (i.e. spotting the expansion triangle);
- Scanning the Explorer vertically, since the boundary between when folders end and files begin becomes clearer.

There are multiple issues (#123, #1833, #3200, many more) requesting a more powerful API for UI customization. But I couldn't find any issue requesting a specific setting to control the visual aspect of folders.

<img width="235" alt="bold_folder_labels" src="https://cloud.githubusercontent.com/assets/830952/17833292/be5ddcc2-66cd-11e6-9303-9cfdc492c03d.png">

**Comment by bpasero** [comment]
@zertosh we plan to add support for icons in the next release, would that help?

**Comment by bpasero** [comment]
We should decide in a UX meeting if we really want this.

**Comment by stemcc** [comment]
I think at least having this as an option in settings.json would be really helpful, and you can default the behavior to what it does now. In a project with hundreds of folders and thousands of files, file names in bold would really help my eyes scanning the file tree.

**Comment by bgashler1** [comment]
@stemcc have you tried one of the [icon themes](https://code.visualstudio.com/blogs/2016/09/08/icon-themes#_file-icon-themes) in VS Code?  Does that mitigate the concern of differentiating folders from files?

**Comment by stemcc** [comment]
@bgashler1  indeed, I've tried Minimal, Seti (VSCode), and Nomo Dark Icon Theme.

I plan on sticking with Seti, but you'll notice that both Seti and Nomo Dark use carrots/arrows for their folder icons. That makes the folder tree easier on my eyes than without them, but it still doesn't quite feel "fast enough" for my brain/eyes to grok. 

Immediately contrasting folders require little processing power on the part of my brain, and if the bolded folders were an option in settings, then we could use both the icon themes (which I really like and will continue using) along with contrasting folder font. 

I never realized how little I actually acutely focused my eyes on my file tree tree when Im working on code across multiple folders. I wonder if this is simply a matter of VSCode doing things differently than Sublime and I just need more time to adjust. 

But I'm the kind of person who increases the contrast on all my screens whenever possible because it's just so much more "comfortable" for me to use that way. Otherwise I find myself being aware of my eyes focusing in on text, whereas with more contrast, focusing on text seems more "automatic" for me. 

I hope this doesn't sound hopelessly subjective!

**Comment by equinusocio** [comment]
@bpasero Any update? I think this setting should be added showing only folder icons is not enough and the users should decide if using `icons` or `file + bolded folders` or `both`.

Also having the ability to differentiate the folders foreground color from files is critical since colors are perceived before icons and text.

**Comment by isidorn** [comment]
This feature request will not be considered in the next 6-12 months roadmap and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!

**Comment by equinusocio** [comment]
a 2hrs features...

**Comment by klaasman** [comment]
I'm really interested in this feature. Visual differences between files and folders are way more apparent with bold / non-bold styles compared to only some icons.

**Comment by thatdoorsajar** [comment]
I'm also really interested in this feature. All vscode-icon setting are great but the reduction in cognative load you get from Sublimes `bold_folder_labels` option is quite a lot better.

**Comment by darkobits** [comment]
This would definitely be nice to have.

In a monorepo, its not uncommon to have a sidebar with enough entries to fill the entire screen (1440px in my case) and the _immediate_ visual feedback one gets from the difference in font weight between folders and files makes a significant impact on the signal-to-noise ratio.

**Comment by mcescalante** [comment]
I also miss this feature in VSCode and would love to see this make it in the future. Sure, there are arrows, carets, or icons but I prefer having bolded (or colored) folders - it really makes a difference when browsing in a sidebar with lots of files.
