### ISSUE TITLE
History on Debug Console filter lost

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#107461]
Issue Type: <b>Bug</b>

1) Open the Debug Console
2) Enter a filter text, press Enter
3) repeat 2) a couple of times
4) Go through the history in the fiter box with <kbd>Cmd</kbd>+<kbd>ArrowUp</kbd> to ensure you have the entries
5) Close the panel
6) Reopen the panel
7) Repeat step 4
-> no history (note: Problems retains the history)

VS Code version: Code - Insiders 1.50.0-insider (ddc98c3f620ab1d2ecad5942ebf4736060403d67, 2020-09-25T05:30:51.469Z)
OS version: Darwin x64 18.7.0
Remote OS version: Linux x64 5.3.0-1020-azure

**Comment by isidorn** [comment]
Yes I akcnolwedge this. The history of the debug console filter is not preserved when debug console gets closed. We can add this, and I think it is an appropriate issue for the Grace Hopper event. Adding help wanted and if nobody tackles I can tackle next milestone

Code pointer https://github.com/microsoft/vscode/blob/f05e467ebc6c439466c89ca2cd91bc6fa42aa5db/src/vs/workbench/contrib/debug/browser/replFilter.ts#L169

However when trying to repro this I found another issue, the `up / down` history navigation is broken, because of my change that action bar uses the up / down for navigation also in horizontal mode. I will look into fixing that.

**Comment by isidorn** [comment]
I have pushed a fix for the `up` / `down` not navigating history via 785f9ce8e4

**Comment by tvgirl90** [comment]
Hi, I'm part of Grace Hopper OSD day and I'll try to tackle this!

**Comment by alexr00** [comment]
It no persists across reloads. Very useful!
