### ISSUE TITLE
FEATURE REQUESTS: Occurrence editing

### ISSUE THREAD

**Issue by DarceyLloyd** [Microsoft/vscode#10744]
**Occurrence editing**
Having occurrence editing is a huge step forward, however “select next occurrence” and “select previous occurrence” is missing, selecting all is nice but I often find myself using those functions more than select all occurrences in phpstorm (select next especially - which I have mapped to alt+mouse back).

> Moved to Microsoft/vscode#10778
~~**Mouse shortcuts**
Shortcuts are fine, however would love to get access to the mouse. Eg in phpstorm I use the side mouse buttons (forward and back) with ALT and CTRL combinations for an additional 6 very quick and easy shortcuts that don’t require you to let go of the mouse when coding.~~

Loving the editor by the way!

**Comment by alexandrudima** [comment]
I have extracted the mouse shortcuts feature request in a different issue, as these are independent feature requests: Microsoft/vscode#10778

**Comment by DarceyLloyd** [comment]
ADDITIONAL: Occurrence Editing
The way select all occurrence editing works at the moment is the same as search and replace, just an inline method of it. Essentially to be useful it needs to go beyond search and replace with:

- Select next occurrence (single)
- Select all next occurrences (multi after cursor position)
- Select previous occurrence (single)
- Select all previous occurrences (multi before cursor position)

# Case Sensitivity
Currently select all occurrences is not case sensitive, in effect it's a weak search and replace which can affect more than what you wish to edit (can be dangerous to use - happened to me a few times already). I would suggest having it case sensitive by default and give the user the option to turn case sensitivity off in config.

This functionality would end (uninstall) sublime and notepad++ for me.

**Comment by alexandrudima** [comment]
@DarceyLloyd 
Here I have added the following keybindings. I am doing it on Windows, but the same principles apply on OSX or Linux, it is just the keybindings are different for `alt+c` and `alt+w` that I touch on below:

I have bound `editor.action.addSelectionToPreviousFindMatch` and `editor.action.moveSelectionToPreviousFindMatch` which are not bound by default:
```
    { "key": "ctrl+d", "command": "editor.action.addSelectionToNextFindMatch", "when": "editorFocus" },
    { "key": "ctrl+k ctrl+d", "command": "editor.action.moveSelectionToNextFindMatch", "when": "editorFocus" },
    { "key": "ctrl+e", "command": "editor.action.addSelectionToPreviousFindMatch", "when": "editorFocus" },
    { "key": "ctrl+k ctrl+e", "command": "editor.action.moveSelectionToPreviousFindMatch", "when": "editorFocus" },
```

Here I am using `ctrl+d` initially and then `ctrl+e`. Notice how the extra highlights show what will match (where the selection will be added). I didn't use `ctrl+k ctrl+d` or `ctrl+k ctrl+e` here, but those will basically move the selection to the next/prev match.

![multicursor](https://cloud.githubusercontent.com/assets/5047891/17960909/0333b5fe-6aa9-11e6-9b36-7c3066871531.gif)

It is sort of annoying that `getAge` and `agent` are matches, but that is because the search is originally case insensitive and does not match word. Here I press `alt+c` and `alt+w` to toggle those modifiers and notice how the highlights adjust and how the operations now select case sensitive word only matches. At the end, I do `ctrl+f` to reveal the find widget which now has those two modifiers on (given that I turned them on via `alt+c` and `alt+w`). I use this all the time and I love it, but I know we have a problem in that this is totally "hidden":
![multicursor2](https://cloud.githubusercontent.com/assets/5047891/17961019/98e54a2c-6aa9-11e6-9602-4093461a4723.gif)

@waderyan Maybe a video on this topic would be helpful
@bgashler1 How can we make these case sensitive and word match modifiers "visible" when the find widget is hidden. I can try showing a message in the status bar, but that will work only if folks already know about `alt+c` and `alt+w`.

**Comment by DarceyLloyd** [comment]
@alexandrudima 
Nice! I will look into implementing this shortly. This is a feature I would put on the front page in a large gif / HD video as it would hands down grab my attention straight away, aswell as many fellow developers I work with.

**Comment by waderyan** [comment]
@alexandrudima @DarceyLloyd very cool! This would work well in the next iteration of the [code editing intro video](https://code.visualstudio.com/docs/introvideos/codeediting) or possibly as an advanced Tips and Tricks topic.

**Comment by bgashler1** [comment]
Maybe we want to have small widget that appears like the Find/Replace widget that lets you toggle case sensitivity.

But wouldn't it make more sense to do this case sensitivity by default for case sensitive languages?  Visual Studio IDE is smart enough to know where you're refactoring and doesn't even bother asking you about case sensitivity.  It can also distinguish between a string or comment contains the same text and has checkboxes for if you want to include those in the refactoring.

<img width="1440" alt="screen shot 2016-08-25 at 11 29 21 am" src="https://cloud.githubusercontent.com/assets/11839736/17981379/55ebd1dc-6ab8-11e6-9a01-7247daef9aa8.png">

**Comment by alexandrudima** [comment]
@bgashler1 In the above gifs I do not do rename (F2), I use a text-only technique based on multicursor that works in any language. Visual Studio has a great rename experience nowadays (they moved away from the modal text box) but I am not presenting rename in this thread.

With multicursor you can go quite far for any language, even those we don't have rich language services for. This works also for plain text:

![multicursor-plaintext](https://cloud.githubusercontent.com/assets/5047891/18006751/672c8bc8-6ba1-11e6-8ef2-4a08cf2e9b50.gif)

**Comment by DarceyLloyd** [comment]
Multi-caret occurrence editing selection capabilities:

- Select next occurrence (single)
- Select all next occurrences (multi after cursor position)
- Select previous occurrence (single)
- Select all previous occurrences (multi before cursor position)
- Select all occurrences

Should/Needs to work regardless of the language, it should be as easily accessible as possible via shortcuts and mouse button mappings.

# @alexandrudima those short cuts are perefect, big thank you!


I am looking into creating an extension but vscode API is a little confusing at the moment (I've only had a quick look so far and setup the basic template). I need to find a way to listen for mouse button events for buttons 1 to 8 (any more than that is mouse driver specific), which I think is going to require GYP c/c++ work. Once I work that out I just need to work out from the vscode API how to execute "editor.action.addSelectionToNextFindMatch" & "editor.action.addSelectionToPreviousFindMatch".

However I'm tempted to use autohot key to handle the mouse button key combo events and fire a keypress into vscode.

**Comment by DarceyLloyd** [comment]
Sure and thanks again.

**Comment by pxwise** [comment]
@alexandrudima The case sensitivity aspects of Change All Occurrences in this request do not appear to be addressed. Agree that this command should be case sensitive by default. Makes this feature unusable in Typescript for me.

**Comment by alexandrudima** [comment]
@pxwise For TypeScript, the best is if you do 'Rename' (F2) which is powered by the TypeScript language service and is able to do a semantic rename of a symbol. Change All Occurences is textual and respects the case sensitivity / whole words settings that are in the editor's find widget.

**Comment by lommaj** [comment]
I cant imagine a situation where select next occurrence doesnt need to be case sensitive unless I was using VSCODE to write text documents.  At least making this configurable would be great.  Thanks!!
