### ISSUE TITLE
crash when turn on settings sync

### ISSUE THREAD

**Issue by BruceKangCN** [microsoft/vscode#107456]
- VSCode Version: 1.49.2(from Snap)
- OS Version: 5.8.6-1-MANJARO

Steps to Reproduce:

1.click "Accounts"
2.click "Turn on Settings Sync..."

Does this issue occur when all extensions are disabled?: Yes/No
Yes

Contact:
name: Bruce Kang
e-mail: brucekangcn@gmail.com

Additional Infomation:
i just installed manjaro and then i installed gcc and vscode,
then i launched vscode and tried to turn on settings sync.
once i clicked the button, vscode suddenly crashed.
i used vscode in ubuntu with no issues before.

**Comment by mikeeheler** [comment]
Also hitting this.

* VSCode 1.49.2 (Snap)
* OS: CentOS Linux release 8.2.2004 (Core)

Occurs when I try to turn on settings sync and also when I attempt to close an unsaved scratch file.

Dump file:
* [be84a2e7-7faf-43dc-9fb83da3-77d4e9a4.dmp.gz](https://github.com/microsoft/vscode/files/5284219/be84a2e7-7faf-43dc-9fb83da3-77d4e9a4.dmp.gz)

**Comment by Tyriar** [comment]
@mikeeheler were you using the snap package as well by chance?

I thought this was triggered by some config changes happening on the service which I just mitigated but that timing appears to be a coincidence since you're using the stable service and the changes were on the insiders service only. If the window is crashing it's a client issue though.

**Comment by mikeeheler** [comment]
> @mikeeheler were you using the snap package as well by chance

Yeah, the snap package. Snap reports version **e5e9e69a** revision **45**.

**Comment by mikeeheler** [comment]
May be related: I'm having a similar issue with another Electron-based app I installed using Snap, GitKraken. Its debug output prints this:

```plain
(gitkraken:19670): GdkPixbuf-WARNING **: 11:37:45.060: Cannot open pixbuf loader module file '/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache': No such file or directory

This likely means that your installation is broken.
Try running the command
  gdk-pixbuf-query-loaders > /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache
to make things work again for the time being.
```

Even with gdk-pixbuf2 package installed on my system, that app and directory do not exist. However, it does exist at `/var/lib/snapd/snap/gitkraken/163/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/gdk-pixbuf-query-loaders`, `/var/lib/snapd/snap/code/45/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/gdk-pixbuf-query-loaders`, and notably, `/var/lib64/gdk-pixbuf-2.0/gdk-pixbuf-query-loaders`.

Perhaps noteworthy is I'm on CentOS8 and gdk-pixbuf2 puts relevant files in /usr/lib64, rather than /usr/lib. The contents of the package can be viewed here: https://centos.pkgs.org/8/centos-baseos-x86_64/gdk-pixbuf2-2.36.12-5.el8.x86_64.rpm.html.

Creating a symlink at `/var/lib/x86_64-linux-gnu/gdk-pixbuf-2.0` that targets `/var/lib64/gdk-pixbuf-2.0` cleared the loaders.cache error, however it now still crashes with a seemingly related error: 

```plain
Gtk-WARNING **: 11:53:48.089: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:/build/gtk+3.0-24RAPQ/gtk+3.0-3.22.24/./gtk/gtkiconhelper.c:493:ensure_surface_for_gicon: assertion failed: (destination)
```

**Comment by Tyriar** [comment]
Looks like this is related to the native dialog issue https://github.com/microsoft/vscode/issues/100940, which makes sense as settings sync opens a native dialog.
