### ISSUE TITLE
Terminal leaves cursor artifacts

### ISSUE THREAD

**Issue by AregGhazaryan** [microsoft/vscode#107541]
- VSCode Version: 1.49.2
- OS Version: Windows 10 64 bit

I am getting weird terminal cursor blocks from time to time, here's an example. Sometimes they even occur in the middle of the text too.
![image](https://user-images.githubusercontent.com/38076644/94366197-855f6900-00e7-11eb-8192-088e10e3a288.png)

Steps to Reproduce:

1. Write some commands in the terminal, I think the possibility rises when you make the overall text size of the editor smaller

Does this issue occur when all extensions are disabled?: Yes

**Comment by timfelle** [comment]
Another way to reproduce is to do the following:
1. have the termianl window focused.
2. move focus to another window, the editor will do, the cursor in the terminal should now be hollow.
3. move focus back into the terminal and write any character or change line.

It seems the issue is the outer frame of the cursor when the window is not focussed is 1 pixel too big so it is not cleared when focus returns. 
if you follow my steps above a couple of times, pressing characters (not breaking the line) and then delete the characters with backspace, the top and bottom part of the artifact remains.

**Comment by AregGhazaryan** [comment]
Here's much more crazy example by just running node script 
![image](https://user-images.githubusercontent.com/38076644/94423762-2e669c00-019a-11eb-872a-e625be49ae8b.png)

**Comment by kneefer** [comment]
Have the same problem:
![image](https://user-images.githubusercontent.com/5238147/94538087-dd12e700-0243-11eb-86a4-74f75e7ceff9.png)

**Comment by strarsis** [comment]
Hu, I first though this is intentional for adding style/dynamics to the terminal. 😹
