### ISSUE TITLE
Cannot read property "split" of undefined, when pressing TAB

### ISSUE THREAD

**Issue by jonathansampson** [Microsoft/vscode#10754]
- VSCode Version: 1.4.0
- OS Version: Windows 10 14393.51

Steps to Reproduce:

1. Load the sample code from below, set HTML as Language Mode
2. Place cursor at Line 8, Col 5
3. Press Tab
4. Note message

```html
<!DOCTYPE html>
<html lang="en">
	<head data-prerender-ignore="">
		<script type="text/javascript">
			var trackingConfig = {
				postId: "118290"
			}
	</script>
```

![canttab](https://cloud.githubusercontent.com/assets/815158/17835198/2a7100c8-6715-11e6-973d-d355a3e3d998.gif)

**Comment by alexandrudima** [comment]
Looks like it occurs in emmet's editorAccessor, which calls `getModeIdAtPosition`, that apparently returns null.

![image](https://cloud.githubusercontent.com/assets/5047891/17847730/e09fb52a-684f-11e6-889a-2fb476e1c04b.png)

**Comment by ramamurthynagaraj** [comment]
@alexandrudima , created a PR for this issue. 

The issue can also be fixed by removing the optimization at https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/model/textModelWithTokens.ts#L495 which checks just the first element to be ModeTransition, but other elements are not. Let me know if this fix makes more sense than the PR I submitted, so that I can provide a PR for that as well.
