### ISSUE TITLE
File permission issues 

### ISSUE THREAD

**Issue by yangfree** [microsoft/vscode#107525]
- VSCode Version: 1.49.2 (user setup)
- OS Version: windows 10 subsystem Ubuntu 20.04.1

Steps to Reproduce:

1. Copy folder to modify name prompts Error: EACCES: permission denied, rename
2. Checking the permissions, I found that it has read and write permissions
3. Can be modified successfully after closing vscode 

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by yangfree** [comment]
**More info:**
![1](https://user-images.githubusercontent.com/24789671/94637784-fc287c00-030a-11eb-8f69-8b3733cb8e64.png)
![2](https://user-images.githubusercontent.com/24789671/94637782-faf74f00-030a-11eb-9705-06e47643b9a1.png)
![3](https://user-images.githubusercontent.com/24789671/94637783-fb8fe580-030a-11eb-96bf-1be720f5b523.png)
![4](https://user-images.githubusercontent.com/24789671/94637778-f92d8b80-030a-11eb-83b5-017b69267980.png)

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.
