### ISSUE TITLE
Full debug experience clinet/backend ASP.NET

### ISSUE THREAD

**Issue by pankleks** [Microsoft/vscode#10752]
Dear all,

I've been searching web for that, but I can't find answer.
Is it possible to debug in at the same time client (JS/TS files) and back-end (C# ASP.NET core)?

I'm looking for similar experience as in standard Visual Studio and IE.

Tired different configurations, but I can't seem to find one that:
1) runs asp.net backend in debug
2) runs chrome browser in debug
3) hit breakpoints on both

Thanks for advice!

**Comment by weinand** [comment]
@pankleks each VS Code window can run its own debugger. So if you open another window you can run the .NET and the chrome debugger at the same time.
But since you cannot open a single project in multiple windows, it is not yet (easily) possible to run more than one debug session on a single project.
Workaround: open a new VS Code window on a sub folder of your project.
