### ISSUE TITLE
Two hovers showing

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#107672]
Testing #107156

With some playing of moving while pressing alt I can get both hovers showing, for different elements. The debug hover shows for the `element` argument (line 160) while the TS hover shows for the `provider` property (line 162)

<img width="873" alt="Screenshot 2020-09-29 at 11 48 18" src="https://user-images.githubusercontent.com/1794099/94543019-d2f3e700-0249-11eb-876e-0c1f1a4b16ff.png">

**Comment by isidorn** [comment]
I can reproduce this and it is a valid bug.
The issue is that when alt is released we do not want to immediatly hide the editor hover due to reasons discussed in https://github.com/microsoft/vscode/issues/107667
If we change that one to be that `alt` is a live toggle then this would get fixed as well.
