### ISSUE TITLE
Web: switching between dark and light color scheme does not restore previous theme

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#107669]
Testing #106389

On Windows I enabled `"window.autoDetectColorScheme": true` and then set a theme of my liking. When I switch between dark and light mode in Windows, my previous set theme was not restored.

**Comment by aeschli** [comment]
How did you set the theme of my liking? By setting `workbench.colorTheme`? Once you have `"window.autoDetectColorScheme": true` set you would rather modify `workbench.preferredDarkColorTheme`.

**Comment by bpasero** [comment]
I am quite sure I was configuring the theme via `workbench.colorTheme` setting directly in settings JSOn.

**Comment by aeschli** [comment]
The deal is that when `window.autoDetectColorScheme` is enabled and the OS changes the scheme, we switch to the theme in `preferredDarkColorTheme` resp `preferredLightColorTheme`.

If you now manually switch the color theme to something else, we let you do it, and will also keep that theme on restart, but on the next OS scheme change we use again the `preferredDarkColorTheme` resp `preferredLightColorTheme`.

So that's as designed.
