### ISSUE TITLE
Web: settings sync reports as not enabled after enabling

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#107660]
In web selfhost today: 

![recording](https://user-images.githubusercontent.com/900690/94534886-36c5e200-0241-11eb-8f62-81b6a4752bcf.gif)

**Comment by bpasero** [comment]
I think there is a window reload after settings sync enabled, I don't think we had that before.

**Comment by sandy081** [comment]
Caused by this https://github.com/microsoft/vscode/commit/a6dbf4c82c8505b3ab15bb2534004d0b8454bc26#diff-59b1dee2be28a3fac235b08089425173

Added settings sync enablement handler to `workbench.ts` and since this is being shared across multiple set ups, this got broken in our web self host set up.

Fixed.
