### ISSUE TITLE
Test ExtensionRecommendationsService: Able to retrieve collection of all ignored recommendations

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#107657]
```
 1) ExtensionRecommendationsService Test ExtensionRecommendationsService: Able to retrieve collection of all ignored recommendations:
     TypeError: call.getFileName is not a function
      at getErrMessage (assert.js:270:25)
      at innerOk (assert.js:361:17)
      at Function.ok (assert.js:381:3)
      at Context.<anonymous> (file:///D:/a/1/s/out/vs/workbench/contrib/extensions/test/electron-browser/extensionRecommendationsService.test.js:349:20)


```

https://dev.azure.com/vscode/VSCode/_build/results?buildId=54035&view=logs&j=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&t=4f94dfce-af9e-52fd-5eb8-ca3006505634&l=13880

**Comment by sandy081** [comment]
Cannot reproduce it locally. Will check how often this is failing.

**Comment by michael-watson** [comment]
I was able to reproduce this same bug locally with just using the [getting started project](https://code.visualstudio.com/api/get-started/your-first-extension).

Reproduction:

1. Run `yo code` and select TypeScript (I also used `npm` and no `webpack`)
2.  Open `src/test/suite/extension.test.ts` and change the test to only have `assert.ok(false)`
3. Launch debugger for tests

Output:
![Screen Shot 2020-12-22 at 9 22 05 AM](https://user-images.githubusercontent.com/8645958/102915766-2df73d80-4437-11eb-9ecb-e20d494dcc42.png)

VSCode install version:
![Screen Shot 2020-12-22 at 9 23 01 AM](https://user-images.githubusercontent.com/8645958/102915854-5717ce00-4437-11eb-9b29-85d79313a55c.png)

Happy to send along the reproduction project if needed

I also have a short term workaround for anyone else that is hitting this.  If you throw an error instead of `assert`, that will pop up as expected you just lose the entire `assert` framework (which is kinda big deal imo).. This also works fine in an async pattern:

```
test('Sync sample test', () => {
	throw new Error('test')
});

test('Async sample test', async (resolve) => {
	try {
		...async stuff
	} catch(err) {
		resolve(err);
	}
});
``` 

I'm also going to look into some of the other supported paths in `mocha` to see if this issue persists across other `assert` implementations (I don't expect it to)
