### ISSUE TITLE
VSCode cannot start when filename argument contains colons in certain cases

### ISSUE THREAD

**Issue by skippi** [microsoft/vscode#107625]
- VSCode Version: 1.49.2
- OS Version: Windows 10

Steps to Reproduce:

1.  Launch vscode using any of the following commands. In this case, `my_file.txt` should be in the current working directory:
```powershell
code --disable-extensions -wg my_file.txt:1
code --disable-extensions -wg my_file.txt:1:1
```
2. vscode fails to open.

Does this issue occur when all extensions are disabled?: Yes

## Extra

This problem also happens if trying to open files past the current working directory:
```powershell
code --disable-extensions -wg temp/my_file.txt:1 # Note the filename here doesn't have a '.'
```
I can still successfully open files with these variants:
```powershell
code --disable-extensions -wg ./my_file.txt:1        # qualified filename via '.'
code --disable-extensions -wg C:/src/my_file.txt:1:1 # qualified filename via absolute path
code --disable-extensions -g my_file.txt:1:1         # non-qualified filename with line numbers, but still works since no -w option
code --disable-extensions -wg my_file.txt            # non-qualified filename, but still works since no line/column numbers
code --disable-extensions -w                         # -w is here, but still works since no -g option
```

**Comment by bpasero** [comment]
I can reproduce it even running out of sources with this:

`scripts\code.bat -g package.json:3:3`

And I do not even see our application starting at all, it just terminates. I can only speculate but maybe Windows does not allow such arguments when they are not relative or absolute.

I see now fix on our end, but leaving open if someone has an idea.

**Comment by vivekmthr** [comment]
Hi! I'm not sure how to go about fixing this, but I'd love to help. I'm very new, but if you could give me some guidance I'd love to help.

**Comment by the-ress** [comment]
Electron rejects arguments that look like URLs when followed by another argument. It's a security mitigation from 2018.

VS Code starts with this command line: `"C:\Program Files\Microsoft VS Code\Code.exe" -wg my_file.txt:3:3 --waitMarkerFilePath C:\Users\user\AppData\Local\Temp\uqjqzwbd`
Electron then interprets `my_file.txt:3:3` as an URL and exits because it's followed by another argument (`--waitMarkerFilePath`).

Related sources:
https://github.com/electron/electron/blob/master/shell/app/command_line_args.cc#L38
https://github.com/electron/electron/issues/16384#issuecomment-453915907
electron/electron#13039
https://www.electronjs.org/blog/protocol-handler-fix
