### ISSUE TITLE
vscode-file: Extension development locations are blocked

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#107690]
Testing #107466

Platform: Windows

- Debugging the tree view sample extension of our extension samples
- In the debugging window, the package explorer icon is not shown

Here is the css it is using

```
-webkit-mask: url(vscode-file://vscode-app/c:/Work/vscode-extension-samples/tree-view-sample/media/dep.svg) 50% 50% / 24px no-repeat;
```

<img width="48" alt="image" src="https://user-images.githubusercontent.com/10746682/94558810-a13a4a80-0260-11eb-9476-76970e8f3eee.png">

It works correctly when I used normal build

**Comment by bpasero** [comment]
Interesting, the issue is that we do not know about the extension development location here:

https://github.com/microsoft/vscode/blob/adb9b2c299dce1e5d0d31aa69a364852158eea0d/src/vs/code/electron-main/protocol.ts#L28-L32

Because the location is only present when the second window opens. We will have to find a way to dynamically update the allowed locations based on opened windows.

//cc @deepak1556

**Comment by sandy081** [comment]
@bpasero Is there a build I can use to verify this?

**Comment by bpasero** [comment]
No, I think this is fine to not verify as we dont ship this.
