### ISSUE TITLE
Unclear when SymbolTreeInput#with is called

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#107710]
Testing #107585

I was not able to make the widget call that method. I also have difficulties to understand what my responsibility is in terms of implementing it: is position the current position in the editor of a tracked position on which the reference provider was called before?

**Comment by jrieken** [comment]
> is position the current position in the editor of a tracked position on which the reference provider was called before?

Yeah, more or less. When the original input was created for word "foo" then we try to find the word again when re-running from history. What you have to do is create a new instance of your input with a location having that position. I agree it's cumbersome. The challenge is that the input is just an interface and I don't know how to "tweak" instances of it. That's why I make you implement this function...

**Comment by dbaeumer** [comment]
OK. Understood. May be it is enough to simply document it more
