### ISSUE TITLE
After closing brackets copy paste content doesn't copy or reopen or paste whole content.

### ISSUE THREAD

**Issue by NikhilGangurde** [microsoft/vscode#107783]
- VSCode about: 
```
Version: 1.49.2
Date: 2020-09-24T16:23:52.277Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 18.6.0
```
- OS Version: **MAC OS mojave 10.14.5**

Steps to Reproduce:

1. create a <div></div> element put sample content in there may be more to be sure.
2. and close element group copy and try to paste in new or another VS Code file it doesn't copy the whole content only <div></div> and also the closed group doesn't open either.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

Explanation: 
I created a div element under that I up the unordered list the I had to make a copy of the same element as I hide/close div element and tried to copy only opening div and closing div gets copied and the rest of the content doesn't and also the same element doesn't open again. and if I go any further let say delete content click option appears after hiding that part it remains as it is it doesn't get removed.

**Comment by NikhilGangurde** [comment]
@jrieken what more info you are required. I posted exactly what the template asked.

**Comment by jrieken** [comment]
Please note that I do not sit next to you. So you need explain steps in great detail. You say

> create a element put sample content in there may be more to be sure.

What element? What sample content? What is more? I don't even know the language are trying this with.

> and close element group copy and try to paste in new or another VS Code file it doesn't copy the whole content only
and also the closed group doesn't open either.

I don't know what en element is, what is then a group? How do I close that? Do you close the editor? Your laptop lit?

Compare this to playing chess. You can say: "move your figures so that you win" or can say move figure A from c to d, move figure B from  e to f etc. The latter is a step by step recipe and the former is worth nothing.
