### ISSUE TITLE
Single space at the end of wrapped lines

### ISSUE THREAD

**Issue by andrew0attard** [microsoft/vscode#107716]
I feel as though on all parts of a wrapped line, except for the last part, should not show the space indicator when there is a single space at the end of the line. In the below image, I feel like the dot at the end of the first line should not appear since it is a single space, but the two dots on the second and single dot on the third line should.
![AFE16941-CC27-496C-BDE7-C0FDD1AE7036](https://user-images.githubusercontent.com/38967273/94581887-9de79480-0249-11eb-9f1d-e3f3d6e70bee.jpeg)

**Comment by alexdima** [comment]
@andrew0attard How do you configure render whitespace ?

**Comment by andrew0attard** [comment]
Render Whitespace is currently set to trailing.

**Comment by hediet** [comment]
I'm not sure if this really is a bug.
I understand the point, but you could also argue that showing "trailing" whitespace is about rendering whitespace at the end of the line, i.e. those that you don't notice otherwise.

Consider this:
![image](https://user-images.githubusercontent.com/2931520/118287226-88229900-b4d3-11eb-82ba-197b9a709936.png)

Rendering trailing whitespaces is the least amount of visual noise required to see whitespace that you wouldn't notice otherwise.
