### ISSUE TITLE
Log file colorization issues

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#107766]
Testing https://github.com/microsoft/vscode-remote-release/issues/3750

I opened a log file in the editor. I think this used the built-in log TM grammar. The highlighted colorizations don't make sense to me.

![image](https://user-images.githubusercontent.com/4674940/94632985-de163980-0280-11eb-8697-9d50cfe71738.png)

**Comment by alexr00** [comment]
I wasn't able to find such a log locally for myself. @chrmarti or @kieferrm can you share a sample of it? Since it is a `.log` file and it is just being opened by the user, it will automatically get the built in log syntax highlighting. 

Some options:
- Find a different log grammar (I'm not in favor of this since I rarely get issues about the log grammar)
- Change what the output looks like a little (perhaps putting some items in quotes would help)
- Don't call it .log

**Comment by kieferrm** [comment]
Here is an example: 
[remoteContainers-2020-09-30T01:05:59.055Z.log](https://github.com/microsoft/vscode/files/5306122/remoteContainers-2020-09-30T01.05.59.055Z.log)

**Comment by chrmarti** [comment]
We don't control most of the output which comes from CLIs. Not calling it .log would also create the need for a slightly improved log grammar.

**Comment by alexr00** [comment]
Those awkward colorings aren't as bad as I thought they were going to be. I've opened an issue in the repo that owns the log grammar. https://github.com/emilast/vscode-logfile-highlighter/issues/162

Closing in favor up the upstream issue.
