### ISSUE TITLE
Redo of rename Java Class name has no effect

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#107739]
Testing #107617

- Remote-Containers: Try a Sample
- Select Java
- Open AppTest.java
- Rename the class name in the file to AppTest2 -> the file is renamed to AppTest2.java
- undo -> the class name is changed back to AppTest, the file name is renamed to AppTest.java
- redo -> no effect

**Comment by alexdima** [comment]
An independent extension that creates the same workspace edits:

* `AppTest.java`:
```java
package com.mycompany.app;

import org.junit.Test;
import static org.junit.Assert.*;


public class AppTest
{
    public AppTest() {
    }

    @Test
    public void testApp()
    {
        assertTrue( true );
    }

    @Test
    public void testMore()
    {
        assertTrue( true );
    }
}
```

* `package.json`:
```json
{
    "name": "test",
    "publisher": "alex",
    "version": "0.0.1",
    "engines": {
        "vscode": "^1.0.0"
    },
    "activationEvents": [
        "*",
        "onCommand:test1"
    ],
    "main": "index.js",
    "contributes": {
        "commands": [{
            "command": "test1",
            "title": "Run workspace test edit"
        }]
    }
}
```
* `index.js`:
```js
const vscode = require('vscode');

exports.activate = () => {
    vscode.commands.registerCommand('test1', async () => {
        const oldUri = vscode.Uri.file('/Users/alex/src/working_dir/AppTest.java');
        const newUri = vscode.Uri.file('/Users/alex/src/working_dir/AppTest2.java');
        const edit = new vscode.WorkspaceEdit();
        edit.replace(oldUri, new vscode.Range(6, 20, 6, 20), '2');
        edit.replace(oldUri, new vscode.Range(8, 18, 8, 18), '2');
        edit.renameFile(oldUri, newUri);
        await vscode.workspace.applyEdit(edit);
    });
}
```

**Comment by alexdima** [comment]
When autosave is off, the problem here is that the `RenameOperation` invokes `IWorkingCopyFileService.move`. That ends up calling `IModelService.updateModel` and that pushes an undo/redo element to the undo/redo service. This is really bad news, because an undo/redo element should not push to the undo/redo service as part of executing/undoing/redoing.

The undo/redo stack looks like this after the operation (the id:2 stack element was introduced in the middle of executing the rename by `IWorkingCopyFileService.move`):
```
------------------------------------
AFTER pushElement: 
* vscode-remote://dev-container/workspaces/vscode-remote-try-java/src/test/java/com/mycompany/app/AppTest.java:
   * [UNDO] [id:1] [group:1] [INVALID] SingleModelEditStackElement - (insert@107 "2"), (insert@128 "2")
   * [UNDO] [id:3] [group:1] [  VALID] FileUndoRedoElement - (rename AppTest2.java to AppTest.java)
* vscode-remote://dev-container/workspaces/vscode-remote-try-java/src/test/java/com/mycompany/app/AppTest2.java:
   * [UNDO] [id:2] [group:0] [  VALID] SingleModelEditStackElement - (replace@87 "public class AppTest\n{\n    public AppTest() {\n" with "public class AppTest2\n{\n    public AppTest2() {\n")
   * [UNDO] [id:3] [group:1] [  VALID] FileUndoRedoElement - (rename AppTest2.java to AppTest.java)
```

After a discussion with @jrieken, it is really not clear what the correct thing to do here is, because the implementation of `IWorkingCopyFileService.move` appears correct, but the problem here is that we are moving a dirty text buffer, which as part of moving, ends up pushing an element to the undo/redo service.

This situation is not reached if `RenameOperation` saves the file to be renamed to disk before moving via `IModelService.updateModel`

**Comment by alexdima** [comment]
I've created https://github.com/microsoft/vscode/issues/107815 so we follow up and think of what to do to be able to remove the `save` from the `RenameOperation`.
