### ISSUE TITLE
VS Code Locks Up While Changing User Settings

### ISSUE THREAD

**Issue by BitwiseGuy** [Microsoft/vscode#10770]
- VSCode Version: 1.4
- OS Version: 14905.rs_prerelease.160811-1789

Steps to Reproduce:

1. Open user settings
2. Change a user setting

VS Code locks up and must be shutdown via Task Manager and restarted.

**Comment by bpasero** [comment]
I am very sorry to hear you are having issues with VS Code. I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by BitwiseGuy** [comment]
That is indeed what it turned out to be. I ran from the command line as you suggested and the problem went away. So now I need to narrow it down to which extension. Thank you for your reply, very helpful.
