### ISSUE TITLE
Tag translation/20160817.01 breaks npm installation

### ISSUE THREAD

**Issue by dennisfrostlander** [Microsoft/vscode#10779]
- VSCode Version: 1.4.0
- OS Version: Windows 10

npm install vscode --save-dev 

The installation of vscode as a dependency seems to be broken because of the new tag translation/20160817.01. The script "node ./node_modules/vscode/bin/install" fetches all tags from the repository and parses them via semver. This operation fails because 20160817.01 is not a valid semver.

**Comment by bpasero** [comment]
@dennisfrostlander I cannot reproduce, are you sure you are using latest vscode as dependency? I think this bug was fixed already in previous releases. Maybe you are on an older vscode version?

**Comment by dennisfrostlander** [comment]
Yes, sorry, for some reason I was getting vscode 0.11.0, and I can see now that in 0.11.17 this is already fixed. Apologies for false alarm.

**Comment by rozzzly** [comment]
I got the same error last night, but for a different reason. Took me quite a while to figure it out. I use `arch` for an OS, and the existing [packages on the `AUR`](https://aur.archlinux.org/packages/?O=0&SeB=nd&K=visual-studio-code&outdated=&SB=n&SO=a&PP=50&do_Search=Go) for vscode don't build the nightlies/are broken. So I made my own package that builds from from `HEAD`.

Anyway, a few days ago I started getting this message:
```
==> Creating package "vscode-insiders"...
  -> Generating .PKGINFO file...
  -> Generating .BUILDINFO file...
  -> Generating .MTREE file...
  -> Compressing package...
/usr/bin/makepkg: line 1176: /home/rozzzly/Projects/cssculpt/build/misc/vscode-build/package/vscode-insiders-translation/20160817.01.r99.g3d0aea0-1-x86_64.pkg.tar.xz: No such file or directory
bsdtar: Write error
==> ERROR: Failed to create package file.
```

I waited a few days to see if a fix would come from downstream, and then eventually got impatient and proceeded to spend a few hours of ripping out my hair. I finally realized the issue was that my (arch) package was trying to compress the compiled source into an archive with a name like this. 
> vscode-insiders-**translation/20160817.01**.r99.g3d0aea0-1-x86_64.pkg.tar.xz

The bold part is most recent git tag _(found via: `git describe --tags`)_. Normally, when the tagged version is something like `v1.4.0`/`0.10.1-extensionbuilders`/etc, everything works fine. But as of earlier this week, the most recent git tag on `master` is [`translation/20160817.01`](https://github.com/Microsoft/vscode/releases/tag/translation%2F20160817.01).

This was causing `bsdtar` to fail because filenames cannot contain `/`s. I remedied this by [using `sed` to substitute **`/`** with **`.`**](https://github.com/rozzzly/cssculpt/commit/0153c73b8f6cde34b568650a4a90462d87b0cba4#diff-e9e77caad82d603de4dcbd5cd46fbcf6R39) so the file name was was no longer invalid and everything worked.

I didn't bother making an issue for this before because I don't expect the vscode team to support every distro/let alone self-built packages... But I saw this issue so I though I'd post my story here so perhaps someday a dev with a similar issue can find it when googling for fixes.

---------------------
I see that git tags have caused a very similar issue in the past. Apparently that particular instance of the issue was fixed from within the vscode build script itself, but that didn't prevent that git tag from breaking my package build script. Might I humbly suggest that the vscode team caution contributors against pushing tags containing `/`s? Such git tags will no longer break my package, nor the vscode build script, but who knows, it could be breaking packages for other distros. Requiring semver-compatible tags would be a bit much, but at least something that could be a valid file name? I think that's reasonable. 

Anyway, thanks for the awesome IDE everyone! Much :heart:
