### ISSUE TITLE
ESLint: Levels enablement control

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#107760]
Testing https://github.com/microsoft/vscode/issues/107584

We now have `ESLint: Enable ESLint`, `ESLint: Disable ESLint` on top of that ESLint execution is allowed or not (either for a workspace or for a session or for everything). Although there are cases where all of that makes sense, that's a lot of enabling/disabling for a linter. Can we merge the concepts?

**Comment by dbaeumer** [comment]
Actually no. The first one is to tell the extension to not try to validate any files (so ESLint is totally disabled). The ESLint server is not started. The other concept is the security concept for which we need to start the server and then find out which library to load. I need to think about the wording. 

There is another reason why I can't merge them. When trusted workspaces arrive I still need the enable / disable.

What we could do is to remote the command since this can now be done in the extensions viewlet by enabling / disabling the extension there. So may be the best is to simple remove the commands.

**Comment by dbaeumer** [comment]
Marking as dup of #107759. Fix is to remove the commands.
