### ISSUE TITLE
Large JS/JSON Files Lock Up VS Code

### ISSUE THREAD

**Issue by BitwiseGuy** [Microsoft/vscode#10771]
- VSCode Version: 1.4
- OS Version: 14905.rs_prerelease.160811-1739

Steps to Reproduce:
1. Drop in a large JS/JSON file, say a large array of objects.

VS Code can't process such a file and locks up. Also tested in Sublime 3 and there were no issues with the same data set, was able to move around the file with no problem.

**Comment by alexandrudima** [comment]
@BitwiseGuy Can you please attach an example file (real or generated) that can help us reproduce?

**Comment by BitwiseGuy** [comment]
Here is the attached file. It was originally a JSON file, converted to TXT for upload here. It is a list of worldwide airports and various properties. The data will ultimately be stored in a database, but for testing was pulled into the project as a JSON file. When opening the file in the editor, it locks up VS Code. I am unable to navigate in any way and I eventually get a not responding error.

I tried the same project in Sublime 3 and had no issues and also opened the file in Notepad++ with no issues.

I just ran with project with all extensions disabled. Initially I was able to navigate to the file and move around a bit (an improvement), but after trying to scroll up and down through the data I encountered the error again.

[airports.txt](https://github.com/Microsoft/vscode/files/430657/airports.txt)

**Comment by mjbvz** [comment]
Can you please try out with VSCode 1.7+ and let me know if this issue still repos for you. I just tested this on 1.7.1 and did not notice any real slowdown (although syntax highlighting takes a moment to kick in for the whole file once you tell VSCode that the file is json):

![](https://cloud.githubusercontent.com/assets/12821956/20450015/f7562366-ada1-11e6-8b85-e3f95ee868b4.gif)


If you are still seeing performance problems, please also let us know what platform you are on so that we can better attempt to reproduce this issue. Thanks.
