### ISSUE TITLE
CodeLens activated on mouse up

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#107736]
Issue Type: <b>Bug</b>

**Repro**
1. Enable the references code lens for JS/TS
1. In a JS/TS file with a references code lens.
1. Click down and drag to make a selection
1. Release the mouse while the pointer is over one of the references code lenses

**Bug**
This activates the code lens.

My expectation is that the code lens would only be activated if I clicked on it, not on mouse up

VS Code version: Code - Insiders 1.50.0-insider (0580328b728a69768558cc8242067cae7b6a1c21, 2020-09-29T09:05:00.729Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.76GB free)|
|Process Argv|-psn_0_57833252 --crash-reporter-id cc7f0c9b-aa2b-4a45-8baa-81ffda32679e|
|Screen Reader|no|
|VM|11%|
</details>

**Comment by olajohn-ajiboye** [comment]
Hi , I'd love to work on this as my first OSS contribution please😗

**Comment by vivekmthr** [comment]
Hi! I would like to try this issue. Do you think it is beginner friendly? Any ideas where to start?

**Comment by jrieken** [comment]
Great. This is the pointer: https://github.com/microsoft/vscode/blob/68ff54f9759cebbb3b038e6145e5d60c0685564a/src/vs/editor/contrib/codelens/codelensController.ts#L229-L238

There is two ways to fix this:

1. Instead of listening for "mouse up" listen for "mouse down". This is simple but makes code lenses also very eager, alternatively 
1. Check that on "mouse up" you still on the right element. On line 230 there is already a check but it seems to be not enough

**Comment by vivekmthr** [comment]
I made the onMouseDown change but the lens still seems to appear without a click. How do I know if the changes I've made are being compiled when I re-run? Currently I use 
_npm compile - vscode/build  to build and .\scripts\code.bat to run. 
Sorry if this is a very basic question and thanks for your help in advance!

**Comment by vivekmthr** [comment]
Hi! Worked on it a little. I think on mouseup will trigger the tagname == 'A', if the target is a code lens regardless of whether you have selected other text. Is there an editor mouse event that is equivalent to a click, such that it will only trigger if the mouse is pressed up and down on the same target? Because that would be ideal for only having the code lens open on click rather than on accident when other text is being selected.

**Comment by vivekmthr** [comment]
This is the bug we're trying to fix correct?

![ezgif com-gif-maker](https://user-images.githubusercontent.com/62236642/95464615-c97c2480-0997-11eb-992a-935420de3a0e.gif)

**Comment by jrieken** [comment]
Yeah. So option 1 should fix it, option 2 needs knowledge about what happened in "mouse down"

**Comment by vivekmthr** [comment]
Cool! Got it : ) I tried both options and I think option 1 looks good. I'm going to create a pull request!
