### ISSUE TITLE
Can only undo one notebook workspace edit that toggles the `editable` metadata

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#107809]
Testing #107622

I have this edit that is executed in a command:
```
		workspaceEdit.replaceNotebookCellMetadata(editor.document.uri, selection.index, {
			...selection.metadata,
			editable: !selection.metadata.editable
		});
```

I ran the command several times.

The little lock icon indicating editable state toggled each time I ran the command ✔

I hit undo a few times. I expected the lock to toggle several time. However, the editable state only toggled once. 🐛

**Comment by rebornix** [comment]
Really good catch @alexr00 !

If you press Undo/Redo when focusing on the cell container, you will see the lock button is updated properly. However if you Undo/Redo inside the cell editor, it stops once the cell is locked. What happens under the hood:

* Focus in cell editor
* Run the command more than 2 times (flip cell.metadata.editable) and make sure after the last run, the cell is unlocked.
* Undo
  * Undo is a multi-implementation command, the top priority one is EditorCommand (priority 10000) https://github.com/microsoft/vscode/blob/76bc88fd9d2e658c3ed3b46e3c47ab746a274d48/src/vs/editor/browser/controller/coreCommands.ts#L282-L290
  * EditorCommand activates as the editor has focus.
  * And the cell is locked
* Undo again
  * EditorCommand activates again, and since the model is readonly (as we lock it), it doesn't perform Undo at all, but it finishes successfully, so no other implementations will be activated at all
  * Nothing happens


Our Notebook specific notebook undo/redo has priority 50. Maybe we should bump to 10050 and then return `false` when the Dom focus is not inside the notebook, otherwise, just run our own Undo.

**Comment by rebornix** [comment]
We don't have such metadata anymore.
