### ISSUE TITLE
retainContextWhenHidden not working as expected

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#107843]
Testing #105764

Either I am using it wrong or it is not working but I expect if this value is true, the webview just exists and is not recreated when the view is collapsed.

**Comment by mjbvz** [comment]
Try adding a `console.log` in the script run inside the webview. With `retainContextWhenHidden` disabled, you should see logging when the webview is first shown and when it is expanded

With `retainContextWhenHidden` true, you should only see logging when the view is recreated (and not on expand). This would happen: on first load, when the webview is disposed, the webview is hidden using the context menu and then shown again

**Comment by mjbvz** [comment]
Note that #107842 causes the webview to be disposed more often than it should be, but the main thing to confirm is that simply collapsing and expanding the webview should not destroy the webview when `retainContextWhenHidden` is set

**Comment by sbatten** [comment]
As discussed: turns out I was setting the value in the wrong place because I misread the documentation and the sample does not include an example. 

Potential improvement: Include this option in the sample with the value set to false. include a comment explaining that this is the default, not necessary but included for clarifying how and why to change it to true.

**Comment by usernamehw** [comment]
Can we have a separate option to never dispose webview view? (false by default).

**Comment by mjbvz** [comment]
Closing this since from our discussion it does sound like the setting is behaving as expected.

Regarding documenting this in the sample: On second thought, I don't think we should include this option. We strongly encourage extensions to use VS Code's default webview behavior, which performs better and is suitable for most cases. An advanced extension user can use this setting if they need to, but with all the performance downsides of `retainContextWhenHidden` I want to avoid making it an easy options that normal extension authors fallback to instead of making their webviews quick to setup and teardown
