### ISSUE TITLE
Moving a file between working set and staging should preserve selection

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#107871]
I find it looks bad if every time I move a file between the groups, the blue focus ring appears over the entire list instead of keeping focus on the item I had selected:

![recording](https://user-images.githubusercontent.com/900690/94779267-f2fce500-03c6-11eb-8fc1-c74bffec993b.gif)

**Comment by joaomoreno** [comment]
This is hard since these are not files, but changes. `Staged Geometry.ts` is a different element than `Unstaged Geometry.ts`. List selection preservation works via identity matching and those two elements have different ids, since they are indeed different:

![image](https://user-images.githubusercontent.com/22350/94820996-5e63a880-0401-11eb-905f-89e299eeb2bc.png)

You're actually the first to ask for this, after years of this implementation, so I'm tempted to just close it.

**Comment by bpasero** [comment]
Yeah not a big deal as I typically have the focus color disabled anyway.
