### ISSUE TITLE
Dispose scoped contextKeyService for treeview menu?

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#107903]
Continuing https://github.com/microsoft/vscode/pull/107887, @alexr00 @joaomoreno 

Why can't the contextKeyService be disposed here, @joaomoreno, it causes some issue with submenus? It would make sense if we need the contextKeyService to still be alive to execute the actions or to evaluate the menu for a submenu, but the actual menu that uses the contextKeyService in that code is being disposed, so it's weird that the contextKeyService can't be disposed.

It's weird that the CKS is in a sort of half-disposed state after this code runs.

**Comment by joaomoreno** [comment]
These are the problematic locations:

- https://github.com/microsoft/vscode/blob/b1c54c1483e2dfcf3101f233b3f8f28436127fba/src/vs/workbench/contrib/timeline/browser/timelinePane.ts#L1228-L1229
- https://github.com/microsoft/vscode/blob/87d7c6dd51aef587c9ac0d543a86609438223fce/src/vs/workbench/contrib/views/browser/treeView.ts#L1019-L1020

**Comment by joaomoreno** [comment]
The problem here exists because the context key menu gets sent around and will be accessed after that call stack. So despite the fact that we create it, we can't really dispose it since others reach onto it.

First it gets sent to the menu itself: https://github.com/microsoft/vscode/blob/86ec53614c06a8e9aed708fbd6d01134fd6c7e80/src/vs/platform/actions/common/menuService.ts#L41-L41

Then to the actions inside the menu: https://github.com/microsoft/vscode/blob/86ec53614c06a8e9aed708fbd6d01134fd6c7e80/src/vs/platform/actions/common/menuService.ts#L117-L118

Submenu are where the problem arises, since they will reach out to that service in an async fashion when using native menus:

https://github.com/microsoft/vscode/blob/883749806b2b7e3494e5dd148ddb577857463d87/src/vs/platform/actions/common/actions.ts#L313-L313

It's hard to understand who exactly should be the owner of the context key service and thus be responsible for disposing it.

**Comment by joaomoreno** [comment]
Another alternative is to snapshot the entire submenu tree, similarly to how we do it in native menus.

**Comment by joaomoreno** [comment]
Yeah that was much simpler than anticipated. Just needed to make submenus stricter. Also found another missing dispose in `extensionActions.ts`.

@roblourens @alexr00 please review: https://github.com/microsoft/vscode/commit/993c987e939b43d2cab404bcce8222c3e69f1105

**Comment by roblourens** [comment]
Cool, looks good, thanks!

**Comment by alexr00** [comment]
Looks good, thank you!

**Comment by jrieken** [comment]
> Another alternative is to snapshot the entire submenu tree, similarly to how we do it in native menus. Maybe this is the lowest effort fix.

@joaomoreno that's coming back as menus are eagerly created, they all are listening, and a parent menu now needs to know when a sub or sub-sub menu changes so that it can update the UI

> In order to fix this we have to declare the rightful owner of the context key service which should be responsible for disposing it. This doesn't look trivial to me.

Menus are just receivers of CKS. I surely don't know the details here but for me it seems that a menu must be disposed when its CKS is being disposed.
