### ISSUE TITLE
Improve NVDA for setting search input

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#107933]
Testing #107797

Steps to Reproduce:

1. On windows with NVDA enabled
1. Open the settings editor and search for `file`
1. Click off of the search input
1. Then focus the search input again

**Bug**
This reads:

```
Search settings. Last synced: 1 mo ago  editor  has auto complete  multi line  file
158 Settings Found 
```

A few areas where things could be improved:

1. The `editor  has auto complete  multi line  file` part does not seem helpful
1. In my opinion it would be better if it read the number of results was read before `Last synced:`
1. The screen pronounces `1 mo` as `1 moe`

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by roblourens** [comment]
I moved the search count to before "last synced". The basic editor stuff I don't think I can customize but I guess users want to know the attributes of the thing they are editing. I'm not going to expand the time label to full words unless someone else complains, because there are 28 different time strings all with abbreviations, and expanding them would add 28 new strings to be localized.
