### ISSUE TITLE
Copying File On Click

### ISSUE THREAD

**Issue by bpj101** [microsoft/vscode#107978]
- VSCode Version: 1.49.2
- OS Version: 10.13.6

Steps to Reproduce:

1. Focus on an opened file, make a change, but do not save.
2. Change focus to a second opened file.

The content of the second file is copied to the first file that was not saved.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.
