### ISSUE TITLE
Debug console has light green background color 

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#10800]
Theme: Quiet Light

![screen shot 2016-08-22 at 4 29 17 pm](https://cloud.githubusercontent.com/assets/10746682/17858360/b0e0fe94-6885-11e6-8db4-f8a2dd23f6d1.png)

**Comment by isidorn** [comment]
@sandy081 looking into your status I see that you are deep into themes and editors, thus you might investigate into this. The issue is that I am currently taking a theme from the editor [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/repl.ts#L232). I want the theme but not the current line highlight.
One option would be to overwrite that css on my side, but that might be a bit ugly

**Comment by alexandrudima** [comment]
@isidorn I am looking into creating a boolean option for this

**Comment by isidorn** [comment]
@alexandrudima that would be lovely!

**Comment by alexandrudima** [comment]
@isidorn I will track the work in #7942

**Comment by alexandrudima** [comment]
@isidorn Option is `renderLineHighlight`

**Comment by isidorn** [comment]
@alexandrudima works like a charm!
