### ISSUE TITLE
Light+ theme use same grey for pinned tab separators as for view separators

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#108173]
The grey used as the pinned tab separator could be a bit stronger and I suggest it is the same grey as for the View separators.

![image](https://user-images.githubusercontent.com/172399/95191525-2da0bc00-07d1-11eb-9283-1e4673e3a8ef.png)

**Comment by bpasero** [comment]
Yeah, this color is pretty much randomly selected. @misolori would you be interested in picking colors for our default themes? Just today I pushed https://github.com/microsoft/vscode/commit/cc594b88d8380e2cacb03f3091e971a7405e6bfe to add the color to our default themes but I did not really spend a lot of time thinking about which color fits best. Most often I picked the border color of the peek view inside the editor.

The color key is `tab.lastPinnedBorder`

**Comment by misolori** [comment]
Are we sure we don't want to push this asa a default for all themes? Because out of the box it's nearly impossible to tell the difference in other themes. Like below, can you tell which files are pinned?

![image](https://user-images.githubusercontent.com/35271042/95224178-3e403a80-07af-11eb-983c-a7f607af66e5.png)
