### ISSUE TITLE
Insiders: exthost.log file already exists

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#108168]
Just starting my Insiders gives me this:

![image](https://user-images.githubusercontent.com/22350/95181169-3be7db80-07c3-11eb-9e81-00d96668a151.png)

@sandy081 Let me know if you need more info.

**Comment by sandy081** [comment]
Thats a great catch buddy, this is because I am not checking if file existence before creating it.

I also revealed another bug while investigating this - Web worker extension hosts across windows are using the same log file as I am not scoping it to window while creating. See the first entry `exthost.log` in the following picture - this is the single log file that all web worker extension hosts are logging to.

<img width="268" alt="image" src="https://user-images.githubusercontent.com/10746682/95482254-34c0f900-098e-11eb-99b7-3985e3e00a03.png">

Also fixed this by pointing web worker ext host logs to a new folder `webWorker` under `extHost{windowId}` 

<img width="295" alt="image" src="https://user-images.githubusercontent.com/10746682/95482741-bb75d600-098e-11eb-9136-5cbd761d854d.png">

@alexdima FYI

**Comment by sandy081** [comment]
To verify:

- Enable web worker ext host using setting ` "extensions.webWorker": true`
- Restart VS Code
- Open Developer tools console and make sure there are no errors like in description
- Run command `Open Extensions Log Folder` and make sure web worker ext host log is in separate folder `webWorker`
