### ISSUE TITLE
Pressing Ctrl+Q key combination with terminal focused opens Quick Actions

### ISSUE THREAD

**Issue by cpibm** [microsoft/vscode#108130]
- VSCode Version: 1.49.3
- OS Version:  Mac OS Catalina 10.15.6

Steps to Reproduce:

1. Open, let's say the `micro` text editor in the integrated terminal.
2. Send the Ctrl+Q key combination to the integrated terminal.
3. VS Code opens Quick Actions instead of sending the keybinding to the terminal. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by Bulletninja** [comment]
Mine doesn't get focus right, can't use any shortcuts, they are run like nothing else is open (i.e. opening finder window instead of searching through the project.). 

It's even worse, VSCode doesn't appear in the app switcher. And the only way i'm able to close it is if i use the activity monitor to kill it. On the other hand VSCode Insiders seems to be working fine.

**Comment by Tyriar** [comment]
You can use this setting to send the keystroke to the terminal instead:

```jsonc
"terminal.integrated.commandsToSkipShell": [
  "-workbench.action.quickOpenView"
]
```
