### ISSUE TITLE
CAN'T Install any extension

### ISSUE THREAD

**Issue by Jmiize** [microsoft/vscode#108181]
Issue Type: <b>Bug</b>

I'm not able to install any extensions. Vetur or similar for example. 

VS Code version: Code 1.49.3 (2af051012b66169dde0c4dfae3f5ef48f787ff69, 2020-10-02T17:57:01.595Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|31.88GB (21.28GB free)|
|Process Argv|--crash-reporter-id e75a71fd-5320-4475-82d3-e99ded0e9f48|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.1
code-spell-checker|str|1.9.2
vscode-status-bar-format-toggle|tom|2.0.0
vscode-todo-highlight|way|1.0.4
vscode-jumpy|wma|0.3.1

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

Do you see any error popups or errors in DevTools console (Help > Toggle Developer Tools)?

**Comment by sandy081** [comment]
Please follow these steps

- Help -> Toggle Developer Tools -> Network
- Then check for any network failed requests while browsing and installing the extensions if found all requests fails then its probably a proxy or DNS issue at your end.
- To confirm its a DNS issue check if you can access this page https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default, if you cannot please try configuring your DNS like pointing to 1.1.1.1 as suggested here? https://1.1.1.1/dns/. Otherwise please contact your network administrator.
- If it is not a network issue, please share the logs from the following locations
    - Help -> Toggle Developer Tools -> Console
    - View -> Command Pallette... -> Toggle Shared Process -> Console
    - View -> Open View… -> Log (Shared)
    - View -> Open View… -> Log (Window)

**Comment by johnnyasantoss** [comment]
I'm having the same problem. I've also found this other issue (#38179) related to this bug and followed the process there but there is nothing in my network tab after searching for extensions or even trying to install them through console.

#### Info
- I don't have any proxies in my network. And have been using code since forever on this laptop.
- Can't install using console
```log
$ code --install-extension sissel.shopify-liquid
Installing extensions...
Extension 'sissel.shopify-liquid' not found.
Make sure you use the full extension ID, including the publisher, e.g.: ms-dotnettools.csharp
Failed Installing Extensions: sissel.shopify-liquid
```
- `Shared Process` window shows absolutely nothing in the Network tab :(
![image](https://user-images.githubusercontent.com/14189387/95639821-4da1db00-0a70-11eb-9809-4438167cd2ac.png)
- I'm using `code-oss`

**Comment by johnnyasantoss** [comment]
Using the `@id:` (from here https://github.com/microsoft/vscode/issues/108147#issuecomment-704910000) thing it worked but still can't search :/
![image](https://user-images.githubusercontent.com/14189387/95640059-4f1fd300-0a71-11eb-8da7-6895f324f58d.png)

**Comment by kikuKeii** [comment]
I can only install extensions manually. how can I fix it ?

**Comment by sandy081** [comment]
Seems this issue is getting distracted from what original author has created. So please file separate issue for specific problem.

@johnnyasantoss 

`code --install-extension sissel.shopify-liquid` works for me with latest. Please try again and file a separate issue for that with necessary info and steps to repro.
