### ISSUE TITLE
Kotlin Error Stuck at Initializing

### ISSUE THREAD

**Issue by Crustalplates** [microsoft/vscode#108175]
I installed Kotlin today and restarted VSCode for around 4 times because i kept being stuck an random % then after installation this pops-up.
"The Kotlin Language Client server crashed 5 times in the last 3 minutes. The server will not be restarted."
I'm new to VSCode so please help..

**Comment by JacksonKearl** [comment]
Hey! It sound's like you're probably using the Kotlin Language extension for vscode and that's what is causing this error, rather than VS Code itself. I recommend filing an issue at https://github.com/mathiasfrohlich/vscode-kotlin. You can help the maintainers of the kotlin language extension out by including things like your extension version, the version of kotlin installed on your system, and the operating system you're using.
