### ISSUE TITLE
New Feature link on repository page is broken and have a request for more user friendly FTP

### ISSUE THREAD

**Issue by AnthonyMichaelc** [Microsoft/vscode#10811]
- VSCode Version: 1.4.0
- OS Version: OSX 10.11.6

This is not so much an issue, more of a feature request. While I along with others enjoy the git integration, the lack of FTP extensions is what makes me have to use other programs to send the files out. I tried the two ftp extensions and their user friendliness is not completely there. 

To make this short, would be nice to see a simple ftp extension that you can hit a command or right click and say upload, delete, create, etc and then a small notification saying uploaded. Also maybe a panel or command that shows the current server you are connected to. This is similar to plugins found on Sublime Text and Atom. 

If there is a different extension then the ftp sync and ftp simple that produces similar features as to what I described I would gladly check them out.

**Comment by sandy081** [comment]
@AnthonyMichaelc We are happy to receive your feedback and enhance the product. Since you mentioned there are already two extensions in this area, I would suggest to communicate with those extensions via issues about your feedback and make them enhance/improve so that the whole community will get benefit. I think coming up with duplicates won't be a good idea. 

So, I would recommend to move this issue to corresponding extension repositories.

Thanks.
