### ISSUE TITLE
Auto attach affects whether the debug console shows up when I start debugging

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#108209]
From https://github.com/microsoft/vscode/issues/108202

- Auto attach -> smart
- Run "Launch VS Code"
- Debug console does not appear
- Disable auto attach
- Start debugging again
- The debug console does appear

**Comment by connor4312** [comment]
I'm guessing that auto attach is attaching to the prelaunch script (which is as designed in 'smart' mode, since it's a normal .js script in the workspace.) In auto attach we use `internalConsoleOptions: 'neverOpen'` to not reveal the console, since that would be quite annoying when using the terminal. There may be some overlap between the attach in the prelaunch script exiting and the debug session starting, and I'm guessing that the new session doesn't then also open the terminal.

I don't think this is something tweakable in js-debug, so deassigning myself, but let me know if there's anything for me to do here

**Comment by roblourens** [comment]
>  In auto attach we use internalConsoleOptions: 'neverOpen' to not reveal the console

Oh, that makes perfect sense then.
