### ISSUE TITLE
PDF Preview in VS Code

### ISSUE THREAD

**Issue by lw-schick** [Microsoft/vscode#10821]
- VSCode Version: 1.4
- OS Version: Windows 7

It would be cool to have a PDF Preview in vs code. We're using vscode to read our documentation repository, and there are still many PDFs from external service providers we have to keep there...

**Comment by martin-azpillaga** [comment]
This would be great particularly for TeX users.

Being able to compile and see the resulting PDF all from within the editor is unvaluable and would definitely attract TeX users to the VSCode community.

**Comment by astewartau** [comment]
I completely agree. I use VSCode as my primary TeX editor for its simplicity. I would love for VS Code to be able to display PDF files.

**Comment by gulshan** [comment]
Check this extension- https://marketplace.visualstudio.com/items?itemName=tomoki1207.pdf

**Comment by WilsenHernandez** [comment]
It would be excellent, I use VSCode as my main editor for a lot of things including TeX.

I would like to be able to edit & preview my documents in the same editor!

**Comment by chengs** [comment]
The extension (https://marketplace.visualstudio.com/items?itemName=tomoki1207.pdf) you mentioned is nice but not perfect.

It works perfectly when using its preview mode (right click a pdf file and then select View PDF). However, when you directly open a pdf by clicking the name, you may find that it cannot open many PDF documents. 

In this direct open mode, the pdf file is firstly loaded as a text file. So it suffers all the limits of reading text files (no binary file, too large size, or wrong encoding). But actually, with pdf.js, only the uri of the pdf is required. I tried to fix this problem and find that vscode has no hook to interrupt the creation of TextDocumentProvider. So the extension cannot work perfectly.


I still suggest vscode make a built-in pdf viewer via pdf.js, for better performance. Indeed, it is not very difficult to integrate pdf.js.

**Comment by changkun** [comment]
@chengs built-in a new third-party module is quite dangerous, that's why vscode have extension feature.

The only problem for this issue is rearding how vscode implement [reasourceVIewer](https://github.com/Microsoft/vscode/blob/6f790f7676581a97918f014bec0cff8f0d690e81/src/vs/base/browser/ui/resourceviewer/resourceViewer.ts), see `Handle generic Binary Files`.

So far, extensions can only process the file that vscode loaded, which means the pdfviewer extension cannot be opened if vscode do not even load it.

If vscode decide to implement a feature that pass the file to extensions before it display a "not open" warning, and check whether there exsists an extension can process the file or not. Then the problem  will be simply solved.

Related issue:
- https://github.com/tomoki1207/vscode-pdfviewer/issues/4

**Comment by aberardinelli** [comment]
Bumping this thread. It's annoying I can't open pdfs natively in VSCode. My workflow would be so much cleaner if I could.

**Comment by andselisk** [comment]
Bumping again. A reliable *.pdf viewer that would work with synctex would indeed make life easier.

**Comment by chengs** [comment]
Bumping again

**Comment by curio77** [comment]
+1
