### ISSUE TITLE
Cannot open folder from vscode on Gnome 3

### ISSUE THREAD

**Issue by nixenos** [microsoft/vscode#108260]
- VSCode Version: 1.49.3
- OS Version: Manjaro 20.1.1

Steps to Reproduce:

1. Install newest code package from snap store on Manjaro
2. Try to open folder

Does this issue occur when all extensions are disabled?: Yes

Hi, I couldn't open directories from newest code package on snap. It would just crash and not even open a dialog. When ran with --verbose flag I discovered that there's no /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/ directory and that's why it was failing to open. gdk-pixbuf-query-loaders > /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache that was being proposed as temporary solution couldn't be executed as there wasn't such directory. Making it and executing that command did the trick and it works for now.

**Comment by JacksonKearl** [comment]
Hey there, I'm not entirely sure what the issue is here -- is this something that happens reproducibly? And is it new with 1.49.3 versus 1.49.2? There was very little code change between the two versions so it's not clear to mea what's going on here. 

We explicitly test installing snaps before each release, so I don't think this is a general snap problem (could be wrong!), is there any chance this is an issue local to your machine versus our packaging?

**Comment by nixenos** [comment]
Yes it happened after update to 1.49.3. I'm not sure how snap packages handle dependencies so it might be Manjaro's fault. I've reinstalled VSCode's snap package several times and the issue persisted, before updating snap package everything was working fine. It might be because I updated form vscode package to code snap package as noted in notification I received in the application. Unfortunately I haven't noted version of vscode package I had.

**Comment by bkcsfi** [comment]
I have been having a similar problem for a few weeks. I cannot tell you which version this began with, since I upgrade every day to get a new code-insiders.  Today this version is failing, yesterday it was 1.50 that was failing:

Version: 1.51.0-insider
Commit: f5d3ba4d61146b78f0c75c82f3f85232d3409bc1
Date: 2020-10-09T05:34:46.257Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.0.0-37-generic

My setup is a little unusual.   I run vscode over ssh. vscode runs on ubuntu 18.04, I ssh to it from ubuntu 16 that is running awesome-wm

When I start vcode it works ok "for a while", but eventually it enters a failure condition where 'open' of all kinds fails to work.

i.e. in the "bad" state, none of these commands do anything. No error appears, its as if the application does not react.

1. ctrl-o
2. ctrl-r
3. menu file / open file
4. help / about (just discovered this today) - sometimes this works, sometimes not
5. clicking 'Recent / More' on the Welcome page (same as ctrl-R) However clicking on any of the other options in 'Recent' does work. see that the cursor changes, its a "hand" over other options, but its a pointer over 'More'
6. File / Add folder to workspace
7. File / Open recent - shows a menu, if I click on an existing item it works, but if I click on "more" nothing happens
8. File / Open Folder and CTRL-K CTRL-O
9. File / Open workspace

I normally have multiple open windows. When I start vscode, all my previous windows open, and the previously opened folders or workspaces  in those windows also load.

I can choose any window and press CTRL-R  to open a recent project or folder.

Once I've done that, all windows are now broken and the menu/ctrl keys do not work as indicated above.

Same thing happens if I use CTRL-O to open a single file.. Once I open the file, all windows enter a bad state.

However if I click on a file in the explorer, that file will open and the application will still respond to CTRL-R, etc.  

I think the problem is somewhere in command handling, whatever Menu options and control key handling has in common, and is likely not related to the actual opening of workspaces, folders or files..


--

aha, so I restarted vscode.. In a window I chose Help / Toggle developer tools. The chrome dev tools window appears. I then press CTRL-O and it doesn't work! Neither does CTRL-R, etc.

I think that confirms this is a menu/command handling issue

Strangely, even in this bad state, most other menu choices and hot keys continue to work

and .. restart, choose Help / About . same problem .. now the app is in a "bad" state.

**Comment by bkcsfi** [comment]
@JacksonKearl is this 'more info' enough? thanks

**Comment by JacksonKearl** [comment]
Yes thanks, there's a lot going on here.. cc @bpasero or @deepak1556 for any ideas.

**Comment by bkcsfi** [comment]
I am not using the snap version, I'm using the .deb version of code-insiders.

**Comment by deepak1556** [comment]
For the OP issue, /duplicate https://github.com/microsoft/vscode/issues/100940

@bkcsfi can you open a separate issue ? Also can you try launching code with `--no-xshm`
