### ISSUE TITLE
Add keybindings to "Kill Terminal" action

### ISSUE THREAD

**Issue by turara** [microsoft/vscode#108248]
Issue Type: <b>Feature Request</b>

How about adding keybindings to "Kill Terminal" action?

I recommend the same keybindings for "Close Editor" like cmd+w (macOS). This can prevents "cmd+w" from closing unfocused editor when a terminal is active.

<hr />

If this is OK, I will make a PR with the following,

```typescript
actionRegistry.registerWorkbenchAction(SyncActionDescriptor.from(KillTerminalAction, {
	primary: KeyMod.CtrlCmd | KeyCode.KEY_W,
	win: {
		primary: KeyMod.CtrlCmd | KeyCode.F4,
		secondary: [KeyMod.CtrlCmd | KeyCode.KEY_W]
	}
}), 'Terminal: Kill the Active Terminal Instance', category, KEYBINDING_CONTEXT_TERMINAL_PROCESS_SUPPORTED);
```
https://github.com/turara/vscode/blob/d8abc0c3a007117d5475ff55e6d7bd1222a80513/src/vs/workbench/contrib/terminal/browser/terminal.contribution.ts#L87-L93

<hr />

VS Code version: Code 1.49.3 (2af051012b66169dde0c4dfae3f5ef48f787ff69, 2020-10-02T17:54:06.165Z)
OS version: Darwin x64 19.6.0

**Comment by Tyriar** [comment]
Currently cmd+w will close the editor and people may be relying on that so I'm hesitant to change the default at this point. Additionally ctrl+w is a special keybindings in some shells so that wouldn't be appropriate. I'd say just stick to custom keybindings for now, you can use settings sync to just set it once and sync it to all your machines:

```jsonc
{ "key": "cmd+w", "command": "workbench.action.terminal.kill", "when": "isMac" }
```
