### ISSUE TITLE
Freeze and 100% CPU after doing cat binary file in the terminal

### ISSUE THREAD

**Issue by frank-dspeed** [microsoft/vscode#108317]
Visual Code Consumes 100% Cpu on a 8 core i7 4 ghz hangs total i hitted crtl + c and it interrupted as it should but the system was still not use able anymore. That makes me think that there is something bad in the terminal component when it gets some characters that it does not like.

- VSCode Version:
current nightly
- OS Version:
ubuntu focal

Steps to Reproduce:

1. start a terminal inside vscode
2. cat $(which node)
the node file is in this case the nodejs binary elf 

Does this issue occur when all extensions are disabled?: Yes/No
yes

**Comment by Tyriar** [comment]
This might is likely because it takes a long time to parse the entire binary file and the parsing is done on the UI thread. I'm not sure if it's tracked to move parsing to a worker, but that would be a cool improvement to make eventually. I'll leave this open for now to track that.

**Comment by frank-dspeed** [comment]
@Tyriar no i am pritty sure that there is something leaking i also found other information in other projects that doing cat on binary files in the Terminal (Nodejs Based one) do end up in undiscovered sideEffects. It does not happen in a real terminal but at last the NodeJS Term Emulation does do 100% bad things when you return binary code and it is not because of the size.

i will not use the vscode terminal anymore soon as i expirenced such issues over the last year more then once.

**Comment by Tyriar** [comment]
Strange I can repro this sometimes, not sure what it could be atm as it happens after the parsing appears to be done. Additionally doing the same thing in Edge using xterm.js' demo doesn't reproduce the problem.

I moved the worker idea to upstream https://github.com/xtermjs/xterm.js/issues/1515

**Comment by jerch** [comment]
@Tyriar I can repro this every single time. The weird thing about it - the terminal itself seems to act nice and responsive (gets through all data without any issue), but vscode itself gets unresponsive. To me it looks like some follow-up code chewing on some terminal chunks cannot keep up and thus stocks up data.

**Comment by Tyriar** [comment]
@jerch yeah it gets through everything for me as well and only then freezes. Not sure how I can get a performance profile out of it if the main thread locks up, if we had that it would be easy to see where the problem was.

**Comment by jerch** [comment]
@Tyriar Could that be a `onLineFeed` handler trying to merging the whole "binary" buffer into one line right after the shell prompt returned? Since the content is binary, chances are high that the whole buffer did not see a single LF in between. Just a wild guess.

**Comment by frank-dspeed** [comment]
@jerch do i understand that right that vscode has a api that it exposes to analyze terminal output? Becuase linkMatch sounds for me exactly like that. And If that is the case we are doomed as i am Security researcher that means for me nothing good i see then 1000 additional issues that need investigation asap

**Comment by jerch** [comment]
@frank-dspeed Plz lets not jump to random conclusions. If you are a user with very high security constraints you already should have done security audits. For the terminal component https://xtermjs.org/docs/guides/security/ might be a good starting point (though written for embedders as audience). 

To shed some light on this:
vscode uses xterm.js as terminal library component. Ofc the terminal lib exposes several API functions to read or write data, otherwise it would be quite meaningless for embedding purpose with advanced interactions (like path updates, debugger line jumps or links that open in the editor). From a security perspective it is not really possible to prohibit access to private terminal data structures in a reasonable way - simply because JS works that way. But as a security researcher you are already aware of that problem and that it is not any different for libraries in other languages (private accessors are a coding help, not meant to hide memory segments during runtime). Still one big difference to compiled langs remains - JS makes it much easier to inject code at runtime. Yes, this needs careful application development with security in mind, as the bar to inject random code at runtime is freaking low in JS.
The link matching function I wrote about above is a built-in functionality of the terminal itself to help identifying buffer content that shapes an URL.

Further note that there is some sandbox isolation done in vscode for plugins. To get more insights here, either consult the source code or ask a vscode developer about the mechanics.

**Comment by frank-dspeed** [comment]
@jerch your right lets not do that and run it inside a log everything virtual machine and fuzz it a bit. thats a great idea would microsoft sponsor that?

**Comment by frank-dspeed** [comment]
@Tyriar who is the right person to ask for azure resources to make sure that this is not as scary as i think it is.

**Comment by frank-dspeed** [comment]
i will only use the vscode online fork till that got addressed via real testing with BPF-Trace: "Dtrace" .

The Browser version does not have that issues not even js is crashing but i am not sure why that is the fact. maybe it leaks some functions that the electron build has or maybe electron it self is the problem.

**Comment by jerch** [comment]
> @jerch your right lets not do that and run it inside a log everything virtual machine and fuzz it a bit. thats a great idea would microsoft sponsor that?

Idk and to be honest I doubt that. They most likely have their own security teams doing all sorts of hardening stuff. Same goes for azure - a service that big (1. or 2. in the world, idk the numbers compared to AWS) cannot go easy with security aspects as it would create such a big threat for many customers (and follow-up lawsuits). I am pretty sure they have done their homework here. Ofc my hand-waving position has no meaning for high security requirements, under such circumstances you always should ask yourself, if the security standards of a service fits your own needs.

> The Browser version does not have that issues not even js is crashing but i am not sure why that is the fact. maybe it leaks some functions that the electron build has or maybe electron it self is the problem.

The browser demo of xterm.js has some differences to the vscode integration, to name a few I am aware of:
- pty binding runs in electron windows JS context (within the frontend event loop), the demo decouples that with websocket transport
- vscode has a couple of additional event listeners to achieve the neat integration with the rest of vscode

**Comment by Tyriar** [comment]
> Could that be a onLineFeed handler trying to merge the whole "binary" buffer into one string line right after the shell prompt returned? Since the content is binary, chances are high that the whole buffer did not see a single LF in between. Just a wild guess.

@jerch that is totally what it is! The window is crashing because we're trying to extract links from a line that's several mbs long, this is tracked in https://github.com/microsoft/vscode/issues/100338

/duplicate

---

> And If that is the case we are doomed as i am Security researcher that means for me nothing good i see then 1000 additional issues that need investigation asap

@frank-dspeed you can read exactly what extensions are capable of around this by looking at the `registerTerminalLinkProvider` API. A summary of it is that extensions will be asked to provide links for lines when the user hovers over them, so the order in which they're asked is somewhat random based on what the user hovers. There are several built-in link providers that provide web and local links for example.

There is also a proposed `onDidWriteTerminalData` API which it sounds like you would likely be very concerned about, but only a small subset of Microsoft extensions are permitted to use that due to security and performance concerns (live share and remote).
