### ISSUE TITLE
Display not visible block start for large blocks

### ISSUE THREAD

**Issue by whitecolor** [Microsoft/vscode#10832]
Looking at the bottom of the code block (`{...}`) We don't know what this block refers to:
VSCode:
![image](https://cloud.githubusercontent.com/assets/736697/17890041/e69c4a62-694c-11e6-927b-ad4414ad910b.png)

Webstorm has a nice feature of displaying clicked block beginning if it is not visible on the sreen
![image](https://cloud.githubusercontent.com/assets/736697/17890140/72865dce-694d-11e6-89da-38ac2d2f826e.png)

So VSCode could support something like this

**Comment by sercanov** [comment]
Aaand this is exactly I'm looking for. Great to have it on backlog

**Comment by alexandrudima** [comment]
To keep the number of issues in our inbox at a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: we look at the number of votes the issue has received and the number of duplicate issues filed. Thank you for your time and understanding.

If you disagree and feel that this issue is crucial: we're happy to listen and to reconsider.
