### ISSUE TITLE
ctr+r should default to having an option to reload the window

### ISSUE THREAD

**Issue by thernstig** [microsoft/vscode#108393]
Opening `Show All Commands` by pressing `ctrl+shift+p` has the option `Developer: Reload Window`, see here:

![reload_window](https://user-images.githubusercontent.com/30827238/95584290-c3408380-0a3d-11eb-97e1-cd7702d339a3.png)

There, you can see the keybinding `ctrl+r` bound to reload the window. selecting that option from the command list will properly reload the window. However, pressing `ctrl+r` gives the a menu to open previously selected workspaces and files. There is nothing there lets you quickly reload the window.

I believe that the first, default option selected when pressing `ctrl´r` should actually be "Reload Window", the same way as is done in the command selection, and which is also indicated there that it should happen if pressing `ctrl+r`.

**Comment by IllusionMH** [comment]
The issue here is that this keybindings that have context that is not currently active (in this case `inDevelopment`) to still be shown across UI (there are several open issues about why keybindings are shown)
![image](https://user-images.githubusercontent.com/1312662/95594728-0148a200-0a54-11eb-8b14-7539cfaac40d.png)
This keybinding here only for cases when you are starting VS Code version from sources while debugging VS Code itself and need to pull updated sources. Same true for Toggle Developer Tools in Help menu.

For regular editor use Recent files will be more used that reloading editor window.
If you really need that keybinding you can change it using command palette with  `>Preferences: Open Keyboard Shortcuts`, remove context from Reload window and remove shortcut from Open recent.

**Comment by JacksonKearl** [comment]
To add on to @IllusionMH, the UI for removing the development requirement can be accessed via the below "Change When Expression", you'd set it empty for this: 

![image](https://user-images.githubusercontent.com/8586769/95619591-b57e0480-0a23-11eb-8107-76711489fc1a.png)

**Comment by thernstig** [comment]
@JacksonKearl I did not mean that it should default to reloading the window, I meant that the default option in the drop-down list when pressing `ctrl+r` should be to be an item in the list to reload the Window.

I understand the logic behind the `isDevelopment` due to @IllusionMH's description, but I still think it makes sense to have it as the first option in the list when pressing `ctrl+r`.

**Comment by JacksonKearl** [comment]
I understand. I don't think this is likely to happen -- on other platforms (macOS) the two have different keybinds which is likely to cause confusion if we group them everywhere when they aren't the same everywhere, or if we group them but only on some platforms.

**Comment by bpasero** [comment]
>  I meant that the default option in the drop-down list when pressing ctrl+r should be to be an item in the list to reload the Window.

I have no clue what this means.

**Comment by thernstig** [comment]
@bpasero Does this make more sense?

![ctrl_r](https://user-images.githubusercontent.com/30827238/95764052-36513080-0cb0-11eb-8e81-0366a648e981.png)

This is the dropdown you get when pressing `ctrl+r`. It would have been nice with an item there that said "Reload Window", which is selected by default.

**Comment by bpasero** [comment]
To clarify: you expect a "Reload window" in this picker? But why, it is about switching to another workspace.

**Comment by thernstig** [comment]
Yes. Because there is no way to quickly reload the window right now, and I felt that was a good place to place such a functionality so when one presses `ctrl+R` you can either "load another workspace" or "reload current workspace".

I am completely fine with closing this if it does not make any sense to you.

**Comment by bpasero** [comment]
> I am completely fine with closing this if it does not make any sense to you.

👍
