### ISSUE TITLE
Asking for vscode github login

### ISSUE THREAD

**Issue by WesleySalesberry** [microsoft/vscode#108352]
Issue Type: <b>Bug</b>

It is popping up every few seconds asking me for confidential information in vscode GitHub login. No steps are needed, I enter my password and it goes away only to pop up again in a few seconds. 

VS Code version: Code 1.50.0

**Comment by LuvTian** [comment]
The same problem.

**Comment by ghostraddish** [comment]
![image](https://user-images.githubusercontent.com/32915080/95536384-cf760380-099f-11eb-8c00-82a01c873c2c.png)

I am having the same issue. I thought my extensions were causing it, so I removed a lot of them because I didn't need most of them, and now I am left with C/C++, Pylance, and Python.

![image](https://user-images.githubusercontent.com/32915080/95536545-1bc14380-09a0-11eb-8791-42196c033402.png)

Yet, it keeps happening. I have even disabled all of the extensions above and it still pops up in several second intervals. So, this makes me think it has nothing to do with extensions

**Comment by SachinShekhar** [comment]
The issue was there in Insiders: https://github.com/microsoft/vscode/issues/107480
And then, they pushed the changes to stable channel without addressing it: https://github.com/microsoft/vscode/issues/108342

The issue has already been noted.

**Comment by gjsjohnmurray** [comment]
@all Please clarify whether you dismiss the dialog by clicking Allow or by clicking Always  Allow..

**Comment by cyberpirate92** [comment]
In my case it was just confusion, I initially thought the "Always allow" button was disabled as it was greyed out, 

<img width="463" alt="Screenshot 2020-10-09 at 10 31 31 AM" src="https://user-images.githubusercontent.com/10222413/95545239-f887aa00-0a1a-11eb-9dea-3bc5b8fd596a.png">

turns out it's not disabled. After clicking "Always Allow" it doesn't happen anymore.

**Comment by ghostraddish** [comment]
> @ALL Please clarify whether you dismiss the dialog by clicking Allow or by clicking Always Allow..

I am able to dismiss the prompt only with Always Allow, not with Allow.

**Comment by jogo-** [comment]
Details from VS Code version: 1.50 [release notes](https://code.visualstudio.com/updates/v1_50#_macos-keychain-access-moved-to-a-different-process)

**Comment by gjsjohnmurray** [comment]
related #108342

**Comment by WesleySalesberry** [comment]
> @ALL Please clarify whether you dismiss the dialog by clicking Allow or by clicking Always Allow..

When I press dismiss it go away then pops back up a few seconds later same with allow, when I press always allow, it stay gone a little longer but it will pop back up.

**Comment by devmachiine** [comment]
Same issue for deny.

**Comment by sampittko** [comment]
It happens to me too but I cannot click anything other than Deny because it does not accept my valid GitHub password. Pops up again every 15 seconds after dismissing.

![Screen Shot 2020-10-09 at 16 19 05](https://user-images.githubusercontent.com/38221262/95594398-27b60f80-0a4b-11eb-9f4f-dec7b949edcc.png)

**Comment by cyberpirate92** [comment]
> It happens to me too but I cannot click anything other than Deny because it does not accept my valid GitHub password. Pops up again every 15 seconds after dismissing.
> 
> 
> 
> ![Screen Shot 2020-10-09 at 16 19 05](https://user-images.githubusercontent.com/38221262/95594398-27b60f80-0a4b-11eb-9f4f-dec7b949edcc.png)
> 
> 

You have to enter the password for your user account, not the GitHub password.

**Comment by sampittko** [comment]
> > It happens to me too but I cannot click anything other than Deny because it does not accept my valid GitHub password. Pops up again every 15 seconds after dismissing.
> > ![Screen Shot 2020-10-09 at 16 19 05](https://user-images.githubusercontent.com/38221262/95594398-27b60f80-0a4b-11eb-9f4f-dec7b949edcc.png)
> 
> You have to enter the password for your macOS user account, not the GitHub password.

Thanks for your response @cyberpirate92, I clicked **Always Allow** after entering my macOS account password and it has not popped up ever since. 👌🏼

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/108342#issuecomment-706340396 , please check that comment for background.
