### ISSUE TITLE
Terminal tooltips render markdown if they span a range that includes colons

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#108301]
If the range returned from a TerminalLinkProvider spans a colon, it seems to cause the tooltip to render markdown instead of being a clickable link.

Normal:

![Screenshot 2020-10-08 at 12 57 27](https://user-images.githubusercontent.com/1078012/95455570-ff081a00-0965-11eb-8c20-9d4ba2ec4eea.png)

But if I increase the returned `length` slightly to include the space/line/col, it does this:

![Screenshot 2020-10-08 at 12 57 49](https://user-images.githubusercontent.com/1078012/95455573-00394700-0966-11eb-8017-8865e0f65d88.png)

The `TerminaLink` I'm returning looks like this:

```js
{
	length, // This is the only property changing between the screenshots
	startIndex,
	tooltip: "Open file in editor",
});
```

**Comment by samrg123** [comment]
Is this issue still? I'm available to work on it

**Comment by Tyriar** [comment]
@samrg123 yep, here are some code pointers:

- Where all the link logic is held https://github.com/microsoft/vscode/tree/master/src/vs/workbench/contrib/terminal/browser/links
- The hover widget used by the links https://github.com/microsoft/vscode/blob/master/src/vs/workbench/contrib/terminal/browser/widgets/terminalHoverWidget.ts

**Comment by samrg123** [comment]
Thanks!

**Comment by samrg123** [comment]
Sorry for the long delay. Finally got around to look into the issue. 

Looks like the problem isn't from spanning colons, but actually from spanning spaces (or control characters 0x00-0x1f). 

TerminalLinks get rendered via "marked.js" which parses markdown into html with the help of some regular expressions.
When you hover a link in the terminal a MarkdownString in the form of '\[Name](PATH)' is sent to marked.js which only gets parsed as a link if 'PATH' matches the regular expression '[^\s\x00-\x1f]*'. Otherwise the string gets rendered as a paragraph element instead.

To fix this I'd escape the TerminalLink URI before creating a MarkdownString in TerminalLinkManager.ts::_getLinkHoverString, but wanted to run this by you guys to first to see if there were any other suggestions.
