### ISSUE TITLE
can't download the plugin

### ISSUE THREAD

**Issue by leoxucn822** [microsoft/vscode#108456]
Issue Type: <b>Bug</b>

I can't download the plugin, my network is normal

VS Code version: Code 1.50.0 (93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3, 2020-10-07T06:01:33.073Z)
OS version: Linux x64 5.4.0-48-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 2553)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|31.27GB (19.12GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id e577ee2a-e6ed-487b-8a0f-5ce856a55284|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
shell|bbe|0.3.0
go|gol|0.17.2
ansible|haa|0.2.8
better-shellscript-syntax|jef|1.1.0
ansible-autocomplete|tim|0.0.2
autocomplate-shell|tru|0.1.1
vscode-ansible|vsc|0.5.2

</details>

**Comment by sandy081** [comment]
Please follow these steps

- Help -> Toggle Developer Tools -> Network
- Then check for any network failed requests while browsing and installing the extensions if found all requests fails then its probably a proxy or DNS issue at your end.
- To confirm its a DNS issue check if you can access this page https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default, if you cannot please try configuring your DNS like pointing to 1.1.1.1 as suggested here? https://1.1.1.1/dns/. Otherwise please contact your network administrator.
- If it is not a network issue, please share the logs from the following locations
    - Help -> Toggle Developer Tools -> Console
    - View -> Command Pallette... -> Toggle Shared Process -> Console
    - View -> Open View… -> Log (Shared)
    - View -> Open View… -> Log (Window)

**Comment by mrmehi** [comment]
@sandy081 Sorry I'm sort of new to this section of github. My DNS addresses are properly set but I'm still having this issue. Should I send screenshoots from logs that you talked about above?

**Comment by sandy081** [comment]
> Should I send screenshoots from logs that you talked about above?

Please copy/paste the logs here.
