### ISSUE TITLE
Debug console auto-completion interferes and messes up my command when it shouldn't (AKA return key grabbed from me when it shouldn't be))

### ISSUE THREAD

**Issue by ell1e** [microsoft/vscode#108439]
- VSCode Version: 1.50.0
- OS Version: Fedora 32 / Linux x64 5.8.7

Steps to Reproduce:

1. See video below, not sure how to do this in a minimal project.
2. Basically I typed `(int)` and then pressed enter to run the command
3. What happens is that the auto completion thinks I want to use it even though I am **in the middle of the line**, and clearly the insert is plain broken anyway (while what I typed does make sense & runs):

![vscodebug](https://user-images.githubusercontent.com/64124388/95650758-11549600-0ad5-11eb-97bf-ca5a514939ef.gif)

I think there is just a fundamental issue of defaulting to "Enter" -> triggers auto completion in an input box where clearly Enter is expected to just run the command. That seems unfortunate to me, I would suggest to limit auto completion to tab or shift-enter **by default** please (and then to simply add a remark like "Press Shift+Enter to pick" into the auto complete pop up box). Convenience is nice and all, but if I'm just blindly entering a command or a line of code then IMHO the auto completion shouldn't just drop things that don't run in the middle of what I am typing. It's frustrating for me to stare at the screen and babysit things not getting in the way when I just plain type :flushed: and I imagine maybe it's not just me

**Does this issue occur when all extensions are disabled?** I don't know, because the debugger isn't really usable without the extension to enable it. I suppose this could also be a problem with the clangd extension, but I assumed the auto-completion handling is in the end likely triggered in the editor.

**Comment by ell1e** [comment]
Here is another instance of this, I just typed `print inst->type` and pressed return (twice because the first time it seemingly didn't react - which was caused by the auto complete getting in the way again):

![vscodebug2](https://user-images.githubusercontent.com/64124388/95651245-90979900-0ad8-11eb-950d-421b0c777f8b.gif)

Again it breaks the command, that just makes me sad using VS Code for debugging really :weary: and wishing for a plain gdb command line (which is **not** something you would want to lose out against in comparison)

**Comment by isidorn** [comment]
I understand the issue you are facing. However I would not change the default.
I believe most of the user expect enter to pick the suggest item. For example chrome dev tools behaves the same way.

However I will leave this issue open to gather more user feedback and potentially change this in the future. Thank you

**Comment by ell1e** [comment]
@isidorn yeah in chrome dev tools I am having the exact same problem all the time. I think this is just user hostile especially for the faster typer among us, especially since tab is also a quite established key (is it not? Am I too old? I used to expect to need to press tab, this "enter" thing I haven't seen in a while).

Also, the excuse that "the user expects" this I find somewhat weak as an argument, because it would be trivial to add an additional notice "Press Tab to Choose" into the popup of suggestions to solve this. So if your only worry is confused users that don't know how to auto-complete, that seems like it shouldn't be the reason to keep the current default. Of course if you think people will get angry if  they can't use enter to select, that would be a different problem.

The regular autocomplete has exactly the same problem by the way, although that ticket was closed: https://github.com/microsoft/vscode/issues/108536

**Comment by eamodio** [comment]
I hit this issue very often as well (and it drives me nuts). And I feel it is made worse because the matching seems to come up way to often without good matches (see the now closed https://github.com/microsoft/vscode/issues/91617). I would love to disable the enter behavior here.

I also feel like there are other issues lingering here with debug console auto-complete, but I haven't been able to capture/quantify them -- but the auto-complete in the debug console constantly aggravates me, while I never feel that way in the editor.

**Comment by ell1e** [comment]
Yeah, it seems like one thing is fundamentally broken about the debug console:

`print <expr>` will happily change a *valid* expression parameter to *another* one without user interaction (sometimes it's a longer match, sometimes just a fuzzy one which is even worse). Maybe I'm missing something, but for all situations I can think of this is at best unexpected, at worst definitely not what the user wants to do. I just can't wrap my head around how an auto complete that happily messes with a valid variable name `my_var` that exists in a scope, and changes it to `my_var_ref` or something is useful to me in *any* situation. Offering that as a 2nd or later result is fine, but automated top result without intervention over the exact match? When is that ever useful?

**Comment by NelsonAPenn** [comment]
I also find that the autocomplete in the debug console is unnecessarily agressive. Many other places where autocomplete is used (including VSCode's file editor) are not like this. In the debug console, it replaces what I'm writing when I press enter. If I don't want the suggestion to occur I have to explicitly press escape. It would be much better to have tab use the autocomplete suggestion, and have enter simply execute the command.

I wholeheartedly agree with the person who opened the issue originally: in a shell-like environment, enter is expected to execute what has been typed, not replace it with something unwanted.

**Comment by ell1e** [comment]
> . In the debug console, it replaces what I'm writing when I press enter. If I don't want the suggestion to occur I have to explicitly press escape.

This is actually exactly what the VSCode's file editor also does, see #108536 . It just happens that all the programmers using languages with `;` line terminators (like C/C++) work around this since that also terminates auto completion before you hit enter and inadvertently toggle something. Sadly, the opposite is  the case for languages like Lua or Python: no line terminator other than line break, so hitting undesired auto completions unless you hammer escape all the type **is the norm**, not the exception. In conclusion, I think the auto complete defaults in the entirety of VS Code are just bad and should be changed. However, #108536 was just closed without allowing any discussion, which I think is a mistake. The argument there was as well that supposedly everyone is used to this now and "expects this," which as I already explained above I think is poor reasoning to leave a bad default as-is. There are ways to deprecate settings that allow people with older installs to opt-in, it's not black magic.

**Comment by uglycoyote** [comment]
I agree that this is user-hostile and poor UI.  

@isidorn  wrote:

> I believe most of the user expect enter to pick the suggest item

I think this is only true in the case where the user is concious that auto-complete item has been selected.  Often for me this is not the case.

Consider the case of a programmer that likes to use a lot very short variable names and use the debug console to evaluate their current value while debugging.  To evaluate the variable, they would expect to be able to just quickly type the variable name and press enter.

Sometimes this works and sometimes it does not, and that's what I find hostile about.  If what you type in before hitting enter happens to match up with something in the auto-complete list, then you'll get that.  This is the frustrating thing, needing to expend the mental effort before pressing Enter to ask one's self "is the auto-complete going to thwart me if I press Enter right now"

In the situation where I'm quickly typing something short,  often I'm typing fast and I don't really want so slow and and look to see whether I'm matching something in the autocomplete list.  It's the fact that it automatically chooses the first match in the list which I find hostile.

For an improvement, I would like to see it either:

* use different hotkey to autocomplete (tab is common, as is modifier+enter), or
* Automatically show the auto-complete list, but don't automatically select an item in the list.  Require the user to explicitly enter into the autocomplete list using the arrow keys.  Then it will be clearer that they are going to accept one of the completions when they press Enter, since they have consciously chosen one of the items.

**Comment by bersbersbers** [comment]
Related: #60877

**Comment by CombatVolcano** [comment]
This absolutely is just the worst. Please fix this. I end up having to hammer spacebar on all of my debug lines. Absolutely the worst. Makes me hate that I have to use VS code on regular basis.

**Comment by jan93** [comment]
I totally agree with what has been said already. This is really frustrating, ie. having to use my mouse pointer and click somewhere else before being able to press Enter. Since both tab and enter currently selects an autocomplete option, why have both?

The debug console is a very handy tool when debugging and experimenting in Python. With the only (major) setback being the autocomplete on enter. Please fix this!

**Comment by AnthonyWeston** [comment]
Related: https://github.com/microsoft/vscode/issues/45156

I know this issue doesn't have quite as much discussion as some others, but I would assume most users use the debug console and are very aware of this bug, and I think most would agree that fix for this would be a great benefit for the user. @isidorn Is there a process for prioritizing issues with high impact potential but lower community discussion, or for actively soliciting community feedback on such issues?

**Comment by eamodio** [comment]
I would love to see this resolved as well -- it is an almost daily aggravation for me.

**Comment by anka-213** [comment]
This is extremely frustrating and forces me to press escape before pressing enter each time and makes the debug console almost unusable. Does anyone actually want the current behaviour?

**Comment by jrieken** [comment]
You can try to disable this setting: `debug.console.historySuggestions`. I figured that I also often run into this but mostly with history suggestions and not with contextual suggestions. E.g in one debug session `foo.bar.bazz` makes much sense but in the next debug session only `foo.b` makes sense

**Comment by weinand** [comment]
@isidorn above you said:
> However I will leave this issue open to gather more user feedback and potentially change this in the future.

 IMO enough user feedback has been gathered to address this paint point.

We can either respect this editor setting:

![2021-06-10_11-38-52](https://user-images.githubusercontent.com/1898161/121502945-e7939c00-c9e0-11eb-8181-f31ba9221ecb.png)

or duplicate the setting for the debug console.

I'd prefer the latter approach.

**Comment by ell1e** [comment]
@weinand I'd also suggest reconsidering the defaults for these settings, as suggested by me here #108536 . why does the default have to be "cannot type properly" for all things that don't end in semicolons, in something that at the end of the day is a *text editor*? (@ doesn't end in semicolons: which, turns out, outside of a few specific languages is a huge amount of things. Python exists after all)

**Comment by jrieken** [comment]
I would also love to see a refinement of the `debug.console.historySuggestions` setting. Instead of on/off I would like to have "on but scoped to session", e.g history should be limited to a debug session and not globally.

**Comment by ssmooncoder** [comment]
Well, since it's amazing this issue has been open for so long, there _is_ a way around this using ctf0's macro extension.

In settings.json
```json
    "macros.list": {
        "unscrewDebugRepl": [
            "hideSuggestWidget",
            "repl.action.acceptInput"
        ]
    }
```

Remove the default `enter` `repl.action.acceptInput` binding and add this to keybindings.json

```json
  {
    "key": "enter",
    "command": "macros.unscrewDebugRepl",
    "when": "inDebugRepl && textInputFocus"
  }
```

This would be like pressing escape right before enter.

**Comment by isidorn** [comment]
After some pondering I came to the following solution:

* We will not accept suggestion in the repl input on `Enter`. Only on `Tab` and `Shift+Enter`
* To educate users about this change we will always render the status bar for the Repl suggest widget

I do not like adding obscure settings to control this that would only make people that are following this issue happy. Due to that I made this general change which I think will improve the experience for everybody.

As for the idea to have the history per session: the history is already per workspace. So this would help only for "advanced" scenario of having multiple different debug sessions in a same workspace. I think this idea make sense but I have not tackled this as part of this issue, please open a new issue for this and ping me on it. Or would you like the history to be cleared between session restarts? Thanks

Thanks to @jrieken for fixing the suggest status bar keybindings rendering via https://github.com/microsoft/vscode/commit/84323a804695ab15b8f3796412f20ef97771a39f

Please try it out with VS Code insiders from tomorrow and let me know what you think.

Adding verification needed as I would like this to be tested for 15mins at least. If there are volunteers please let me know.

![Screenshot 2021-06-30 at 17 45 03](https://user-images.githubusercontent.com/1926584/123991544-1a6ef580-d9cb-11eb-86af-f2f806818984.png)

**Comment by anka-213** [comment]
Awesome!
I'm a bit skeptical about the specific choice of `Shift+Enter` though, since `Shift+Enter` usually means "create a line-break, do not submit" in most other programs.
1. Was `Shift+Enter` bound to anything in the debug console before this?
2. Is there a way to create a line break without submitting in the debug console?

It's probably okay still and most definitely better than the old situation!

**Comment by AnthonyWeston** [comment]
> I'm a bit skeptical about the specific choice of `Shift+Enter` though, since `Shift+Enter` usually means "create a line-break, do not submit" in most other programs. Two questions:
I mean it feels like a step up for sure, but as a user I would expect it to "just work" like the suggestion widget in the text editor, unless specifically configured otherwise.

> 2. Is there a way to create a line break without submitting in the debug console?
It sounds like that would be an issue, but there's a `suggestWidgetVisible` context for When expressions for keybindings, which may work.
