### ISSUE TITLE
"Last active workspace" behavior in terminal setup is confusing

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#108549]
When a terminal is launched, we look at the terminal configuration, resolve variables in the config, and use it for the new terminal. One thing we need is the folder to use for variables like `${cwd}`. When you start a new vscode window in a multiroot workspace, and open a terminal, we don't want to ask the user which folder to open the terminal in, so we use the "last active workspace". This is fine, but when I open a second terminal, and select the folder to use, it still uses the "last active workspace" to resolve variables, even if it's different from the one I picked. This seems wrong and gives a confusing result:

- Have a workspace containing "folderA" and "folderB"
- Set this in user settings
```json
    "terminal.integrated.shell.osx": "bash",
    "terminal.integrated.shellArgs.osx": [
        "--rcfile", "${cwd}/test.sh"
    ],
    "terminal.integrated.env.osx": {
        "TEST_CWD": "${cwd}"
    }
```
- Add a "test.sh" file in each workspace folder, that echoes the name of the folder
- Open the terminal view
- It opens a terminal on one of the folders, doesn't matter
- Open the file from "folderA" to force it to be the "last active workspace"
- Click the + to create a new terminal, select folderB from the picker that appears
- See that the variables were resolved with folderA as `cwd`, but with folderB as the actual cwd

![image](https://user-images.githubusercontent.com/323878/95797919-8971b600-0ca5-11eb-9f6c-d77ec4a6f011.png)

I think that when `shellLaunchConfig.cwd` is set, that should be used instead of the "last active workspace"

**Comment by Tyriar** [comment]
I think the issue here is that it's relying on `${cwd}` variable substitution that was built for tasks that can only take a workspace folder. https://code.visualstudio.com/docs/editor/variables-reference

Here's the code that resolves:

https://github.com/microsoft/vscode/blob/7831795dcb7a21ce22f1974943a99a64e9faa8f7/src/vs/workbench/services/configurationResolver/common/variableResolver.ts#L233-L234

Currently only a workspace folder may be passed in as the root:

https://github.com/microsoft/vscode/blob/7831795dcb7a21ce22f1974943a99a64e9faa8f7/src/vs/workbench/services/configurationResolver/common/variableResolver.ts#L62
https://github.com/microsoft/vscode/blob/7831795dcb7a21ce22f1974943a99a64e9faa8f7/src/vs/workbench/services/configurationResolver/common/variableResolver.ts#L62

Thoughts @alexr00? I don't think this is that important as it's a rarely used part (cwd) of a rarely used feature (shell args) that generally has better solutions (like `$(pwd)`).

**Comment by alexr00** [comment]
If the fix for the terminal is to simply let `resolve` take a uri here, then I am happy to make the change:

https://github.com/microsoft/vscode/blob/0e04bb7b5da8c232d13a45c5d2d5273a8512dda7/src/vs/workbench/services/configurationResolver/common/variableResolver.ts#L58-L61

Otherwise, I would call this out of scope, as I agree that not many people will use it.

**Comment by Tyriar** [comment]
@alexr00 I don't think it's that simple as that would then break `workspaceRoot`/`workspaceFolder`, feel free to close if you think it's not worth it.
