### ISSUE TITLE
Breadcrumb menu collapsing when displaying an image

### ISSUE THREAD

**Issue by svillar** [microsoft/vscode#108596]
Issue Type: <b>Bug</b>

Steps to reproduce

1. Open an image file from a project on a tab.
2. Now click on any of the path elements of the breadcrumb menu (not sure if you use this name) just bellow editor tabs. The popup menu is shown for a fraction of time and then immediately dissapears.

VS Code version: Code 1.50.0 (93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3, 2020-10-07T06:01:33.073Z)
OS version: Linux x64 5.8.0-2-amd64

**Comment by svillar** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [breadcrumb menu doesn't work right (#84536)](https://www.github.com/microsoft/vscode/issues/84536)

Definitely not the same issues (I had already checked it when I filed the bug report).

**Comment by jrieken** [comment]
That's due to the webview

**Comment by jrieken** [comment]
Trying with https://github.com/microsoft/vscode-github-issue-notebooks/blob/beda8d4a7d5ff2332f7bb3d9c9955b1baaae5137/sample.png and I see still unhappy behaviour

![Oct-29-2020 12-34-26](https://user-images.githubusercontent.com/1794099/97563353-3442dd80-19e3-11eb-9364-0875a8e2b35b.gif)

**Comment by mjbvz** [comment]
@jrieken Seems to work for me:

![Oct-29-2020 14-21-37](https://user-images.githubusercontent.com/12821956/97633909-1630a980-19f2-11eb-950b-91cf90ae7ee6.gif)

What OS is this for? Were you using codespaces?

**Comment by jrieken** [comment]
macOS, code desktop

**Comment by jrieken** [comment]
tho, I am using webview-iframe thing

**Comment by jrieken** [comment]
Yeah, happen only when using `"webview.experimental.useIframes": true`

**Comment by mjbvz** [comment]
Moving to November since it only happens with iframes enabled in my testing

**Comment by mjbvz** [comment]
Not happy with my fix and it will probably not work in all cases since it simply increased a timeout 

The root problem is that our codebase largely assumes the focus issync, but I don't think that's possible with our webviews

@jrieken  Perhaps the breadcrumbs could be tweaked the make it easier for the webview to do the correct thing here. Right now I see focus happening in two phases when you first click in the breadcrumbs bar: 

1. We focus on the `class="outline-element monaco-breadcrumb-item"` element. This then [calls `.focus` on an editor group](https://github.com/microsoft/vscode/blob/84671392320342523902c1d974a89f4479b7f00b/src/vs/workbench/browser/parts/editor/breadcrumbsControl.ts#L358) which ultimately calls `.focus` on the webview
     
    This is triggered by `BreadcrumbsWidget._select`. However I don't know if the editor really should be focused like this when you simply click in the breadcrumbs bar to first open the breadcrumbs

2. At some later point, we end up focused into the breadcrumbs list instead: `class="monaco-list list_id_36 mouse-support selection-none element-focused"`

I believe that not triggering the initial focus would also fix this bug
