### ISSUE TITLE
【Error: Error: Illegal value for `line`】 after "save all"

### ISSUE THREAD

**Issue by cjqpker** [Microsoft/vscode#10869]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:41:29.513Z)
- OS Version: Darwin x64 15.6.0

Steps to Reproduce:

1.Edit -> replace in Files ----> replace sth in more than one files
2.File -> save all ----> 【Error: Error: Illegal value for `line`】

**Comment by bpasero** [comment]
I am very sorry to hear you are having issues with VS Code. I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by cjqpker** [comment]
I tested it and find out it was caused by "go extension", thanks!
