### ISSUE TITLE
strange behavior when one workspace is another workspace's subfolder

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode#108662]
Issue Type: <b>Bug</b>

as title
if one workspace is another workspace subfolder,  that will be strange with file explorer
for example, click file of small workspace,then all workspace tree view would fold.

VS Code version: Code 1.50.0 (93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3, 2020-10-07T06:10:52.432Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (2.80GB free)|
|Process Argv|--crash-reporter-id 23358751-c21f-47f9-b523-bb026a2a76e7|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by heartacker** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [Consistency with the use of "workspace"  (#77718)](https://www.github.com/microsoft/vscode/issues/77718)
> * [Allow to open multiple workspaces in the same window (#43188)](https://www.github.com/microsoft/vscode/issues/43188)

no,not the same

**Comment by Akuukis** [comment]
I have the same problem.

### Repro

1. make a workspace with two folder, one being subfolder of other (e.g. `/` and `/src`)
2. add the subfolder to `"files.exclude"`
3. select a file in file explorer in the subfolder

### Expected behavior
> worked flawlessly few months back, still works nice in my huge JS monorepos, e.g. [here](https://github.com/Akuukis/sepraisal/)

- Open the file
- in breadcrumbs, see file as part of the sub-workspace
- in file explorer, see file selected in the sub-workspace

### Actual Behavior
> in my smaller python projects, e.g. [here](https://github.com/Akuukis/beancount_interpolate/)

- Open file (so far so good)
- in breadcrumbs, see file as part of the sub-workspace (so far so good)
- in file explorer, see file selected as in subfolder of the root workspace
- in file explorer, sub-workspace get collapsed

Frankly, only the  currently focused file is visible in the root workspaces subfolder, even if more than one are open in other tabs.

Also, the sub-workspace gets collapsed when closing a file in the sub-workspace IF the next focused file is not from the sub-workspace.

**Comment by isidorn** [comment]
Acknowledge this issue. For now assigning to backlog and we might tackle in the future.

**Comment by isidorn** [comment]
There is already an issue to add a setting to disable this.
Apart from that no changes are planned, thus closing this as out of scope
