### ISSUE TITLE
Intellisense Lightbulb does not appear when green squiggle hovered in C++ file

### ISSUE THREAD

**Issue by jgoshi** [Microsoft/vscode#10868]
- VSCode Version: 1.4
- OS Version: Windows 10
- Cpptools Version: 0.8.1

Steps to Reproduce:

1. Open any folder that has a cpp file. The cpp file can be really simple and just include a header that cannot be found.
2. Mouse over the green squiggle line. I would expect the light bulb (code action) to show up but it doesn't. Note that if you move the keyboard cursor (either move the arrow keys or mouse click) the light bulb shows up.

**Comment by jrieken** [comment]
Currently, we only show them on cursor change events. @egamma We talked about being more explicit for code actions. New ideas?

**Comment by jrieken** [comment]
After experimenting with this we decided not to show the light bulb on hover. Since you can hover anywhere (far away from your cursors) it a little unclear to what position the light bulb refers to. Also it's unclear it then two light bulbs should show (one for the hover position and one for the cursor position) or how the light bulb should move

![aug-29-2016 15-01-36](https://cloud.githubusercontent.com/assets/1794099/18052276/ae1de05e-6df9-11e6-9bbc-dc0c0e9a25fe.gif)

**Comment by jgoshi** [comment]
Ok sounds good. Thank you.
