### ISSUE TITLE
New windows should get the size of the previous active window

### ISSUE THREAD

**Issue by heese** [Microsoft/vscode#10864]
- VSCode Version: 1.4.0
- OS Version: Win10

Steps to Reproduce:
1. Open VSC and resize the window, e.g., make it a bit larger
2. Open a new window by File => New Window or Ctrl + Shift + N

The new window has some pre-defined size. I would expect that it has the same size as the first one.

**Comment by c633** [comment]
It's probably a personal preference. It should be a user setting instead of hard-coded.

**Comment by kidlj** [comment]
+1. Need this as a preference setting option.

**Comment by youurayy** [comment]
adding desc from #17105 to also include window position:

When I open a new window in VS Code (Ctrl/Cmd+Shift+N), the new window takes about 1/3 of the screen and I need to manually resize it to make it bigger. (On Windows this may not be a huge issue since there's the maximize button. But on a Mac, laborious manual resizing is needed to keep windows in the same space.)

Wanted behavior: The window is sized and positioned with the size and position taken from the last user-sized and the last user-positioned window.

Possible workaround if this is hard to implement: add an option to specify new default window size and an option to specify a new default window position, both in pixels.

**Comment by DanTup** [comment]
> On Windows this may not be a huge issue since there's the maximize button

It's still annoying having to perform extra steps.. I dislike this:

1. Open a terminal, type "code ." to open code. It opens full-screen (how I left it)
2. Open another terminal (or change to another folder) and type "code ." to open code. It opens in a small window

It's a little annoying that the window size is different depending on whether it's the first time you launch code or not!

**Comment by sryze** [comment]
I too find this annoying. I like keeping VS Code window at a certain position / size and have a browser window open next to it, but when I open a second project / window I have to manually resize it (or close the first window).

I think this should be saved in somewhere in workspace settings or globally per folder.

**Comment by bpasero** [comment]
A new setting `window.newWindowDimensions` allows to control how new windows should open. By default, a new window will open in the center of the screen with small dimensions. If you change this setting to `inherit`, the new window will get the same dimensions as the last active one. Setting it to `maximized` or `fullscreen` will always open new windows either maximized or in fullscreen.

**Comment by infeng** [comment]
Can I customize new window size?
