### ISSUE TITLE
You Should Always Be Able to Redo Your "Undo"

### ISSUE THREAD

**Issue by machineghost** [microsoft/vscode#108688]
Version: 1.49.2
Commit: e5e9e69aed6e1984f7499b7af85b3d05f9a6883a
Date: 2020-09-24T16:26:09.944Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.4.0-48-generic

Steps to Reproduce:

To be clear, this is a report of an non reproducible bug (but presumably you at least want to know about them right?)

1. Make some changes in a Javascript file: nothing special, but JSX and automatic importing is involved.
2. Undo a bunch of changes (eg. so you can see an earlier version of the file) *expecting* to be able to redo your changes to get them back.
3. DO NOT make any changes (literally press nothing but CTRL + Z, and a single CTRL + C to copy the code)
4. Redo is *enabled* in the menu .... but you can press CTRL + Y (or pick the menu option) until the cows come home, and nothing happens.

Does this issue occur when all extensions are disabled?: Yes/No

Again, if I restart I can all but guarantee undo/redo *will* work normally, because 99% of the time it does so just fine.  But it just failed, and that seems like something which shouldn't happen.

**Comment by alexdima** [comment]
@machineghost Did you by any chance save at any time or use auto-save with save participants like trimming line endings or inserting final newlines, etc. ?

**Comment by machineghost** [comment]
That makes perfect sense ... but shouldn't it disable the "Redo" option in the menu when that happens?

Also, it _might_ be nice if some tiny pop-up happened (just) the first time an auto format was about to invalidate a "redo", to make users aware of this ... but then again I imagine you want to minimize annoying little pop-ups, and most people don't care about redo, so probably not.

**Comment by scscgit** [comment]
This also randomly happens to me when trying to undo and redo a few times in a row, often having "empty" entries that require doing the action several times, and after some attempts or waiting I can no longer do the Redo after Undo however much I try. That's why an extension like [xyz.local-history](https://marketplace.visualstudio.com/items?itemName=xyz.local-history) is a necessity, considering VS Code ignores the original local history issue since 2017 in spite of 200 upvotes; this default UX is a joke without a bit of common sense.

The issue is made that much worse due to a bug of CTRL+Y being a yank (delete line) despite the fake menu item description

![obrázok](https://user-images.githubusercontent.com/3118390/96704229-231b2080-1394-11eb-936c-6ad442ce3246.png)

plus I don't understand why the Redo button is active (clickable) even when there's no history entry, making it impossible to debug. Is there any way to log when some actions get registered, maybe using some extension?

**Comment by fab1o** [comment]
It's also happening to me, **Redo** is simply not working anymore. I used to rely on it all the time for codinf, going back and forth my change history. Now it has become a major headache when I catch myself doing undo, I have to re-write everything again cos Redo simply does not work anymore.

**Comment by fab1o** [comment]
This bug should a **Top priority** to be fixed

**Comment by machineghost** [comment]
It definitely still happens (it happened just the other day), but I can't confirm what causes it because whatever does happens minutes, if not hours  *before* the problem itself (which happens later, when I try to "undo" the action).

I strongly suspect the action was plug-in based (eg. a refactoring), but can't confirm for sure.

**Comment by alexdima** [comment]
@machineghost @scscgit @fab1o I whole-heartedly agree that undo and redo should always work. But I would need some repro steps to find the case where they are not working correctly, such that I can investigate the problem and make a code change.

**Comment by machineghost** [comment]
Why not simply add some code to the redo command: whenever it can't redo, it checks the undo history to see what extension was responsible?

**Comment by alexdima** [comment]
The redo buffer is intentionally destroyed when a do operation occurs. So for example, if you undo and then type something, then redo will not work. This is expected.

**Comment by machineghost** [comment]
Could you track whenever an extension destroys undo history (just keep a running buffer of the last extension to remove history), and then when someone tries to redo and can't you could make an alert "Such and such extension performed a Foo action, destroying redo history beyond this point."?

Or if such an alert would be too disruptive, hide it behind a flag, so only people with problems could turn the flag on?

**Comment by scscgit** [comment]
Undo/Redo is definitely one of core functionalities that would deserve some additional configuration options, including a way to limit or log the actions of some extensions. Personally I'd argue for a new "Redo-Undo buffer" that would let us undo any buffer destruction by simply chronologically coming back to the previous "physical" state; think about all the developers who irrecoverably lose some work by mistakenly overriding the buffer instead of pressing the Redo key :) I mean come on, there's plenty of space in our RAMs for one more buffer, and the UI action can stay hidden from plain sight by default to avoid cluttering (though I'd wish for a community feedback as I doubt a majority would explicitly agree with most of the current UI decisions). But once again, if VS Code cared about implementing a local history, we'd already have a workaround in place to prevent worst case scenarios.

**Comment by Aleksion** [comment]
I'm having the same issue and I'm trying to track down which extension is causing this. 
It's **not** a keyboard issue. Opening the command palette and manually triggering the redo doesn't work either.

- Write a pair of brackets `[]`
- Delete the pair of brackets
- Run Undo - they come back
- Run Redo - nothing happens

Any suggestions on how I can further trace this?
- there's nothing in the logs
- nothing in the developer tools

**Comment by alexdima** [comment]
@Aleksion Since you can reproduce so easily on your machine, please use extension bisect to figure out which extension it is:
* run `F1 > Help: Start Extension Bisect`
* (this will restart VS Code with half of your extensions disabled)
* try to do the steps which reproduce the problem
* if the problem reproduces, click "This is bad" (this narrows down the problematic extension to the half which was enabled)
* if the problem does not reproduce, click "Good now" (this narrows down the problematic extension to the half which was disabled)
* these steps will repeat until the problematic extension is found

| initial | step | final |
|---|---|---|
| ![image](https://user-images.githubusercontent.com/5047891/101918658-e9170f80-3bc9-11eb-9977-857baa291937.png) | ![image](https://user-images.githubusercontent.com/5047891/101918683-ef0cf080-3bc9-11eb-9f9e-98b0177991b2.png) | ![image](https://user-images.githubusercontent.com/5047891/101918706-f502d180-3bc9-11eb-8c86-e56355958bd4.png) |
