### ISSUE TITLE
Can not clear auth token for one extension if not sign out my account completely

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#108680]
Issue Type: <b>Bug</b>

I have mutiple extensions using github account: Settings Sync, GHPRI and GitHub Issue Notebook. I often get `Bad credential` error with GitHub Issue Notebook. I guess it's because of SSO so I need to reauthenticate.

* Manage Trusted Extension
* Uncheck GitHub Issue Notebook
* Run query
* Allow access to the GitHub account
* It's using the old token and still leads to the same error

The only way to workaround this is sign out my GitHub account completely. However that means I need to three times of authentication (dialog, and then open a page in browser, come back. repeat three times), which is also bad.

IIRC, extensions under the same github account are using different tokens, but currently I didn't see a way to clear the token.

VS Code version: Code - Insiders 1.51.0-insider (2ed16d0ce8713a5dfed9729071141be0ccf7fbec, 2020-10-14T05:48:54.391Z)
OS version: Darwin x64 19.5.0

**Comment by rebornix** [comment]
It's much worse. I signed out of my GitHub account, reload the window, open a GitHub issue notebook file, and then it shows "allow the extension to GitHub account" three times, even if every time I say allow, and finish the authentication in the browser.

**Comment by RMacfarlane** [comment]
I'm sorry this was such a bad experience!

I think we should delete credentials that return the `Bad credentials` response so that it's not necessary to sign out completely and remove all tokens. This still creates an annoying experience of having to sign in again, but at least it would only be for one thing. I'm not sure yet how to avoid getting into the `Bad credentials` state, I think this is because the number of tokens GitHub will issue to an OAuth app is limited, and it will start to revoke older ones when you request new ones.

**Comment by roblourens** [comment]
What is `Manage Trusted Extension` here? I don't see a command with that name

**Comment by rebornix** [comment]
@roblourens 
<img width="465" alt="image" src="https://user-images.githubusercontent.com/876920/97904616-9c503700-1cf5-11eb-8fb3-86669021668e.png">

**Comment by rzhao271** [comment]
To start, I don't have any Bad Credential Error. But, if I follow the steps, this is how it looks now:

1. Click on Manage Trusted Extensions
2. Uncheck GitHub Issue Notebook
3. Run query in a notebook
4. Allow access to the GitHub account
5. I'm not redirected to the browser, instead it just signs me in and the query runs.

Is this the new expected behaviour? @rebornix @RMacfarlane

**Comment by RMacfarlane** [comment]
This is expected behavior, yes, but isn't related to this fix.

Steps to verify: (these are assuming mac, I'm not sure if all of these operations are possible using Windows Credential Manager or gnome keyring)
1. Open Keychain Access and click the '+' at the top to create a new password, enter `vscode-insiders-github.login` as item name, `account` as account name, and `[{"id":"738dcd4d-3a51-4d79-9eab-04cfc9e7531d","accessToken”:”garbage”,”account":{"label":"RMacfarlane","id":3672607},"scopes":["read:user","repo","user:email"]}]` as the value
2. Delete `vscode-insidersvscode.github-authentication` from the keychain if you have it
(The reason for these steps is that the key for auth was migrated this iteration. The new value has additional encryption, so to be able to test bad data in the keychain, we need to use the old key value and let VS Code migrate it over to the new one)
3. Open VS Code. You'll be prompted that VS Code wants access to the keychain for this value, since VS Code was not the process that created it
4. Check that the "GitHub Authentication" output channel has a message that says "Getting account info failed: Unauthorized" and that you are not signed into the GitHub Pull Requests and Issues extension, meaning that the bad credential was removed
