### ISSUE TITLE
Add support for filtering in the output window

### ISSUE THREAD

**Issue by chairy** [microsoft/vscode#108776]
The recent filter support for the debug console is amazing. Could you also make this available in the output as well because having the ability to filter would make it a lot easier to find information amongst walls of text in output.

@misolori

**Comment by misolori** [comment]
I think this makes sense and a natural progression. Though you can use the find widget in output, it’s not the same as filtering. Would love to get this added.

**Comment by misolori** [comment]
@sandy081 is this really out of scope? the output window is terrible to navigate when looking at long strings and given that other panel views have this, this makes sense to keep open:

![image](https://user-images.githubusercontent.com/35271042/99289530-f3740280-27f1-11eb-9e03-fd8c7db8b1d8.png)

**Comment by sandy081** [comment]
Unlike other panels which are based on List/Tree widgets, Output panel is built on top of editor widget. Filtering text in an editor is not trivial and needs some considerable effort. I agree it adds value but not sure if it is worth the effort. I also think that this will not meet our priorities given the effort it needs. Hence closed this as out of scope instead of keeping it open.
