### ISSUE TITLE
Go > Forward menu mneumonic confusing

### ISSUE THREAD

**Issue by jeffmcaffer** [microsoft/vscode#108880]
Issue Type: <b>Bug</b>

The Go > Back entry is ^- (dash) and Go > Forward is ^_ (underscore). Notice that in the menu the underscore appears shorter than the dash making the user think that the entries are inverted. That is, based on the line length, and comparing to the keyboard symbols, it *appears* as though Back is ^_ (underscore) and Forward is ^- (dash). It is quite easy to miss that one line is higher/lower than the other.

Suggest changing the menu entry to match the notation in the doc (https://code.visualstudio.com/shortcuts/keyboard-shortcuts-macos.pdf) and use ^<up arrow for shift>- for Back.

VS Code version: Code 1.50.0 (93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3, 2020-10-07T06:00:00.397Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.20GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
go|gol|0.17.2
vscode-docker|ms-|1.6.0
ruby|reb|0.27.0
vscode-ruby|win|0.27.0

</details>

**Comment by bpasero** [comment]
This is about how we render keybindings in the menu that Electron cannot display:

![image](https://user-images.githubusercontent.com/900690/96429240-039fbe80-1201-11eb-9204-7d573cc009bb.png)

I am [registering](https://github.com/microsoft/vscode/blob/d1578555f7247b8070df0ba625d046859a163f04/src/vs/workbench/browser/parts/editor/editor.contribution.ts#L374-L374) the key as: `KeyMod.WinCtrl | KeyCode.US_MINUS`

**Comment by bpasero** [comment]
@jeffmcaffer did you change your keybindings? For me the default key for "Forward" is `Ctrl+Shift+Minus`

**Comment by jeffmcaffer** [comment]
I have not changed any bindings etc. Forward in indeed `Ctrl-Shift-Minus` but as you can see in the screen shot, my menu looks different from yours for some reason. Notice how the <shift> part is not explicitly shown and the dash looks longer than the underscore leading the user to think they are actually opposite.

![Screen Shot 2020-10-19 at 10 00 18 AM](https://user-images.githubusercontent.com/10070956/96487537-f3ccae00-11f1-11eb-9c49-514cf4eefcac.png)

**Comment by bpasero** [comment]
@jeffmcaffer yes, we have some logic that tries to be clever and detect if we can put the keybinding label into the menu or not. It looks like my keybinding was detected to not be supported and thus appears as label right after the command name. 

Do you have any other program (native, macOS) to compare the appearance with? This could be a macOS issue in the end, since this looks like the native appearance to me.

**Comment by alexdima** [comment]
I also get this rendering:
![image](https://user-images.githubusercontent.com/5047891/96553613-b5002c00-12b5-11eb-9b34-0458c4d9350f.png)

@bpasero it might be that you are not using a US standard keyboard layout and that's why it renders differently for you.

I think the problem here is that Electron can render these keybindings fine, it's just that we don't quite like how it renders them because the difference is too subtle.

**Comment by alexdima** [comment]
These ones will now render like this:
![image](https://user-images.githubusercontent.com/5047891/96556447-48872c00-12b9-11eb-9f60-11a1235e60a9.png)
