### ISSUE TITLE
Active indent guide scope improvement

### ISSUE THREAD

**Issue by cateyes99** [microsoft/vscode#108848]
In VSCode, as shown in the below screenshot, when placing the cursor on the **Line 87**, the **active indent guide scope** is its own level.
![ActiveIndentGuid1](https://user-images.githubusercontent.com/19678455/96798980-8ffaed00-145e-11eb-92aa-d31549c77892.png)
But normally in this case,  what I would really be interested in is its **parent**'s scope. To do so in VSCode, I have to temporarily add  a new line in Line 87 😞 
![ActiveIndentGuid2](https://user-images.githubusercontent.com/19678455/96799009-a1dc9000-145e-11eb-9161-80bd5c489d66.png)
This is very inconvenient & tedious, particularly for a long document, I've to do it and undo quite a lot.

But I notice that **Azure Portal**’s **Cosmos DB Data Explorer** & **OneDrive**'s **file editor** in a browser, both have the more desired behaviour as show below, unlike with VSCode, I don't need to add that new line. I believe both actually share the same engine with VSCode.
* **Azure Portal**’s **Cosmos DB Data Explorer** in a browser
![ActiveIndentGuid3](https://user-images.githubusercontent.com/19678455/96799042-bcaf0480-145e-11eb-95a6-d8fc7fc47150.png)
* **OneDrive**'s **file editor** in a browser
![image](https://user-images.githubusercontent.com/19678455/96330066-e9ee6200-10ae-11eb-8cd0-e282385d9633.png)

**Comment by alexdima** [comment]
Our initial logic for these cases was similar to what you propose here.

We changed it in February (see https://github.com/microsoft/vscode/pull/77762) and IMHO it was a good change because it aligns with many examples of what people are asking for in #49342 (just take a look through that thread). 

Azure Portal or OneDrive have probably not updated yet to a newer monaco editor version.

I think what would help here is to have the active indent guide be sensitive on the cursor position. So if the cursor position is before the `{`, then the parent one should be considered active (as you propose). If the cursor position is after the `{`, then the child scope should be considered active (as it is today).

**Comment by cateyes99** [comment]
@alexdima thanks, your suggestion makes it even much better 😄. IMHO, I wish it would have been implemented in this way when #77762 was done, don't quite understand why now we need to wait for 20 up votes 🤭 🙄 ...
