### ISSUE TITLE
The F2 rename tag cannot be used in a VUE file

### ISSUE THREAD

**Issue by zengchulin** [microsoft/vscode#108854]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by usernamehw** [comment]
https://github.com/vuejs/vetur/issues/610

**Comment by nicoespeon** [comment]
Hi there 👋 

If you're looking for renaming symbols in `.vue` files, I recently adapted this extension to enable such refactoring: https://marketplace.visualstudio.com/items?itemName=nicoespeon.abracadabra

The UX is similar to the one you'd have with VS Code (although I didn't managed to get the input box just below the symbol). It's seamless since you trigger that with `F2`.

I hope that could help you until Vetur supports such refactoring itself 👍
