### ISSUE TITLE
File-Save on a .ipynb does not remove the * on the tab and 

### ISSUE THREAD

**Issue by pierre01** [microsoft/vscode#108883]
Issue Type: <b>Bug</b>

File-Save on a .ipynb does not remove the * on the tab and  closing the tab triggers the "do you wanbt to save " dialog.  
Workaround: Enable autosave

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.52GB (37.82GB free)|
|Process Argv|--crash-reporter-id e537dbd6-c3f9-4d50-ba40-082bba9983b7|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
anaconda-extension-pack|ms-|1.0.1
python|ms-|2020.9.114305
remote-wsl|ms-|0.50.1
vscode-yaml|red|0.11.1

</details>

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.
