### ISSUE TITLE
Regex find with line start matches mid-line on "find next"

### ISSUE THREAD

**Issue by mrwonko** [Microsoft/vscode#10887]
- VSCode Version: 1.4.0
- OS Version: Mac OS X 10.11.6

Steps to Reproduce:

1. Open/create a document containing a line with multiple characters except `{`
    1. alternatively, just fill the line with a bunch of `a`s
2. Search for `^[^{]`. The first character of the matching line is selected, as expected, with the find box stating something like "1 of 338"
    1. or `^a`, if you went with 1.i
3. Find next. Instead of going to the next matching line, the next character on the current line is selected, with the find box stating "? of 338"
4. Find previous works as expected

It seems as if the search is run on the substring starting after the current match; but the beginning of this substring is erroneously interpreted as "start of line".

A symmetric issue occurs with `a$` and find previous.

For the moment, my workaround is searching for `^[^{].*$`

**Comment by sandy081** [comment]
Find is broken if reg ex has beginning of line pattern for some cases. When cursor is at the beginning of the line, Find next gives correct result. Otherwise not. 

Because, find next takes the input from current position. If at current position, it starts with expected match then it matches it and goes into a bad state. 

Simple case: `ifif` with reg ex `^if` => Get me all lines that start with `if`

![aug-31-2016 16-52-57](https://cloud.githubusercontent.com/assets/10746682/18133572/6c75928e-6f9b-11e6-84aa-0041d3a52759.gif)
