### ISSUE TITLE
Windows Scripting Host (WSH) can not react to *wrong* JS scripts after installing VS Code

### ISSUE THREAD

**Issue by DBJDBJ** [microsoft/vscode#108847]
This is a problem only with **wrong** Javascript *.js WSH scripts on Windows 10. These scripts are executed from the Windows command line.

This happens always if you leave it to the OS to find and run the exe associated with the *js file. But if you execute it like so:

```
cscript sieve.js
```

cscript.exe will take it and execute it (or react to wrong code).  Electron will not get involved.

After I installed VS Code on this Windows 10 machine I can not see WSH response to the **wrong** js files anymore.  They are wrong because they use DOM which is non-existent obviously.

```cpp
// this is wrong WSH js file
alert("There is no DOM here, I am bad");
```
Only if ***js** file is wrong then somehow Electron "get's in a way" and one is greeted with the Electron debug dump:

![image](https://user-images.githubusercontent.com/145155/96329982-17f18900-1052-11eb-93d8-14d41b3e4f1e.png)

One can use wsf file for developing and testing a mixture of both VBS and JS

```cpp
<job>
<script language="VBScript">
  MsgBox "hello world (from vb)"
</script>
<script language="JScript">
// this uses WSH object model
  WSH.echo("hello world (from js)");
alert("there is no dom.this is wrong. But this does not provoke Electron debug dump.");
</script>
</job>
``` 
Above is executed and Electron does not get-in-a-way and on that alert WSH reacts as ever before during the last 20 years of service

![image](https://user-images.githubusercontent.com/145155/96331087-c1d51380-105a-11eb-8e61-39ed57b2d479.png)

**VSCode Version:**

Version: 1.50.1 (user setup)
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T15:06:15.712Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

**OS Version:**

OS: Windows_NT x64 10.0.19041

**Steps to Reproduce:**

Try to execute any *wrong*  *.js file on windows where VS Code is installed,

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by deepak1556** [comment]
If you have opened the `,js` file with `code.exe` then windows will associate the application for opening such files because we have registered certain file type associations for javascript extensions https://github.com/microsoft/vscode/blob/master/build/win32/code.iss#L522-L555. So running `test.js` was opening the file with code.exe instead of wscript. 

* You can either remove the file association in regedit.exe or open with wscript
* You can also change the extension to `wsf` for which code.exe doesn't have any association

the debug dump is unrelated to the issue, its just a warning log associated with the application. Closing as there is nothing actionable from the app.
