### ISSUE TITLE
Notebooks - HTML elements (widgets) in output overflow & get displayed under the editor

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#108947]
In the Python extension when enabling IPyWidgets:
* Some widgest such as beakerx (have calendar controls)
* These controls are floating HTML elements, however when they overflow the bounds of the widget, they end up getting displayed behind the monaco editor.
* Seems like a zindex issue (monaco editors) are dislayed over the HTML content, hence get displayed over outputs.

@rebornix /cc

**Comment by rebornix** [comment]
We can't fix this issue completely as long as the outputs and cell input (editors) are rendered in different frames, an output renderer can use `position: absolute` to put a DOM element anywhere it wants. However we can improve the experience case by case.

For example, on Google Colab, we can use native calendar widget without any issue (the output is rendered in an iframe, and the calendar is not being covered by anything)

![image](https://user-images.githubusercontent.com/876920/103308730-f99bf800-49c7-11eb-93c2-e80dc0fdee88.png)

The way it works is 

* an output is rendered in a dedicated iframe, so its inner native element can escape the iframe and also be on top of editors (while in our architecture, the webview/iframe is a single giant one so it's always below editors)
* every iframe load shim code for ipywidgets, so the widget can talk to the kernel to get/save states
* catch is if you have two widgets linked with the same data entry, you will notice latency when updating one, as it will send data to the kernel first and then communicate back to the other widget

We can probably do the same thing, if an output doesn't need to access outputs' DOM elements directly. Every output can be rendered in its own iframe, and everyone of them talks to the kernel to sync widget states.

Short summary:

* If an output's renderer doesn't need access to the DOM elements out of the output container, we can render it in a separate iframe. For ipywidgets, it syncs states directly through kernel, every iframe will have its own widget manager
* If an output's renderer tries to absolute position a DOM element, it needs to be aware of the output container, otherwise it won't behave properly (same in Google Colab or any other frontend which separates editor and output in different frames)


@DonJayamanne

**Comment by rebornix** [comment]
Well I spoke a bit earlier, Chromium is smart enough to render native inputs

![image](https://user-images.githubusercontent.com/876920/103320062-e3526400-49e8-11eb-906b-8cbd2425c658.png)

**Comment by rebornix** [comment]
Since the browser is doing the work for us, so we don't have to render outputs in dedicated iframes on top of editors. The challenge left is tweaking the renderers to know about the boundary of the output container.

One example with beakerx, they have customized context menu based on where you right click, it's a div element created under `body` and absolutely positioned. In VS Code/AZNB environment, it needs to check the boundary of the output container, and then make sure the context menu doesn't overflow.

![image](https://user-images.githubusercontent.com/876920/103320491-6b853900-49ea-11eb-847f-30152e6aaa12.png)

**Comment by rebornix** [comment]
Thought about it twice, rendering outputs in dedicated iframes still has its value. Some renderers are smart enough to position its widgets inside visual viewport, e.g.

![image](https://user-images.githubusercontent.com/876920/103372701-95406d80-4a87-11eb-808f-28e2b6df220b.png)

having an output in its own iframe will make sure this type of renderers work oob.

**Comment by rebornix** [comment]
Closing as we have come to conclusion that there aren't any we can do to support floating DOMs if they are not native floating elements (input), we would need to contribute to the community to help polish the experience.
