### ISSUE TITLE
Debugging in same  chrome instance will occur "Unable to attach to browser"

### ISSUE THREAD

**Issue by leonkong** [microsoft/vscode#108912]
- VSCode Version: 1.50
- OS Version: macOS 10.14.6
nodejs 10.21.0

Steps to Reproduce:
project A launch.json
"configurations": [
        {
            "type": "chrome",
            "request": "launch",
            "name": "Launch Chrome localhost",
            "url": "http://localhost:8000",
            "webRoot": "${workspaceFolder}",
            "userDataDir": false,
        }
    ]

project B launch.json
"configurations": [
        {
            "type": "chrome",
            "request": "launch",
            "name": "Launch Chrome localhost",
            "url": "http://localhost:8001",
            "webRoot": "${workspaceFolder}",
            "userDataDir": false,
        }
    ]

1. Run debug on project A and vscode launch a chrome instance, "http://localhost:8000" will display in chrome tab's address bar。The page displays normally too.
2. Run debug on project B and vscode open a new chrome tab on previous chrome window。But this time the page can't 
display normally, and "about:blank" displays in this new chrome tab's address bar. Vscode will get a error: "Unable to attach to browser"
![image](https://user-images.githubusercontent.com/26429579/96401103-09979e80-1205-11eb-96bd-c861ca99f043.png)

Does this issue occur when all extensions are disabled?: Yes/No
No

**Comment by connor4312** [comment]
This is because you have `"userDataDir": false,` -- by default we can only attach to the instance of Chrome that we control, since we pass in pipes for communication when launching the process. If the launch "merges" with an existing instance of Chrome, this doesn't happen. You have two options:

- Remove `userDataDir: false` so that each launch will use a different data dir, or
- Set a `port` number to listen on. This is less secure but could work if required for your scenario.
