### ISSUE TITLE
Feature Request : Provide multiple terminal choices within same instance of VSC

### ISSUE THREAD

**Issue by abhishekanand** [Microsoft/vscode#10893]
- VSCode Version: NA 
- OS Version: NA 

Steps to Reproduce: NA

Per this link, Integrated Terminal in the docs , you can create multiple instances of the terminal and even change it from CMD to BASH to PowerShell. 
Can VScode provide options have multiple terminals choice.  1: CMD, 2: BASH, 3: PowerShell within the same instance of VSC?

**Comment by avikenjale** [comment]
Stackoverflow question - http://stackoverflow.com/questions/42032232/vscode-multiple-terminals-configuration-issue

**Comment by Tyriar** [comment]
From duplicate I created https://github.com/Microsoft/vscode/issues/20057

> Perhaps the + icon could open a quick pick or popup which presented:
> 
> - cmd
> - powershell
> - bash for windows
> - git bash
> 
> These could be configured using some settings behind the scenes which knows about the paths to these since they will almost always be in the same spot. The setting could look something like this:
> 
> ```js
> "...shells": {
>   "cmd": "%windir%\\sysnative\\cmd.exe",
>   "PowerShell": "windir%\\sysnative\\WindowsPowerShell\\v1.0\\powershell.exe",
>   "Bash on Windows": "%windir%\\sysnative\\bash.exe",
>   "Git Bash": "%programfiles^\\Git\\bin\\bash.exe" // if it exists
> }
> ```
> 
> Note that we don't want to run into the same issues as `commandsToSkipShell` https://github.com/Microsoft/vscode/issues/19770 if we create such a setting.

**Comment by rotemdan** [comment]
I have nothing special against PowerShell but I found the sounds it emitted when hitting `backspace` a little bit annoying. I realize it is probably [not that difficult to disable them](https://superuser.com/questions/1113429/disable-powershell-beep-on-backspace) (actually it [requires creating and editing a profile, through a series of commands](https://msdn.microsoft.com/powershell/reference/5.1/Microsoft.PowerShell.Core/about/about_Profiles), so I wouldn't say it is "super-easy"), but instead I quickly switched to the good-old `cmd`. Probably because `cmd` already does all I need and doesn't require me to learn anything new.

I guess there would be many people who would choose do the same, so making the switch easily accessible would be convenient. Also, having `bash` readily accessible might prove useful for Windows users as well, especially to run specialized scripts.

**Comment by ryansully** [comment]
There is a (hacky) workaround until this feature becomes official:
http://ammonsonline.com/vscode-multiple-integrated-terminals/

I'm currently using ConEmu for multiple terminals, but would like to see this built into VSC natively.

**Comment by Tyriar** [comment]
@ryansully in most cases you should simply be able to launch the shell from the other one (run "powershell" in cmd), bash.exe may be an exception though as it has some special properties.

**Comment by Tyriar** [comment]
I just published an extension that covers this use case, enjoy :smiley: https://marketplace.visualstudio.com/items?itemName=Tyriar.shell-launcher
