### ISSUE TITLE
Consolidate ModifierKeyEmitter and AlternativeKeyEmitter

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#109062]
We seem to be having 2 solutions for detecting keypress globally:
* [`ModifierKeyEmitter`](https://github.com/microsoft/vscode/blob/b3204b9260357b44047d8b7fd5f57d8a28fb541c/src/vs/base/browser/ui/menu/menubar.ts#L1011-L1011)
* [`AlternativeKeyEmitter`](https://github.com/microsoft/vscode/blob/e8572c022163b7db3e0424549bdb5ac32b7ebd4e/src/vs/platform/actions/browser/menuEntryActionViewItem.ts#L23-L23)

They both seem to be doing the same thing but with some different strategies. 

I suggest to consolidate this into one helper function in `dom.ts` to allow for reuse from everywhere.

//cc @jrieken

**Comment by sbatten** [comment]
@isidorn the one for the menu bar listens and emits a bit more info so it can handle special cases for the menu bar. it also uses capture in order to be like native. would you be able to adopt my version safely?

**Comment by bpasero** [comment]
@sbatten is `capture` really needed, I was wondering what issues you found that required to use `capture`.

**Comment by isidorn** [comment]
@sbatten I checked your implementation and I will be able to use it if you add a simple `isAltPressed` method. In my use case I can not have listeners. If you can also move your implementation to common that would be great, then I can delete my thing.

**Comment by sbatten** [comment]
@bpasero the focusing behaviour for the menu bar relies on knowing if other keys are pressed along with the alt key, this also includes click events as well. e.g. alt-clicking something should not trigger the menu but we need to know about the alt key and the click event before they are eaten to know we shouldn't do anything. otherwise we may see the alt key without the cancellation event. we also have to cancel if a keybind triggers instead of a mnemonic. we always get the alt but without capture we won't be able to tell whether it is a valid alt.

**Comment by sbatten** [comment]
@isidorn moved to dom.ts as suggested by ben and added a simple `keyStatus` property to access the current key status

**Comment by isidorn** [comment]
@sbatten thanks. I tried adopting it, however there is one issue if I adopt it.
VS Code does not get key events from Electron while a context menu is shown.
So if a user presses `Alt`, trigger a context menu, releases `Alt` while a context menu is visible the `ModifierKeyEmitter` will still think `Alt` key is pressed.

Actually use case is that there are alternative commands in the Explorer so than a user can easily get stuck with the wrong alternative command. "Delete Permantly" instead of "Delete" if the user lets the `Alt` key while the context menu is shown.

Due to that we had this hack workaround https://github.com/microsoft/vscode/blob/9eaeb4db68efee5b9650fc1cc63f9128f80437a6/src/vs/platform/actions/browser/menuEntryActionViewItem.ts#L49

@sbatten @bpasero any ideas how the `MenuKeyEmitter` could work around this?

**Comment by bpasero** [comment]
Hm not really, I guess the `menubar.ts` is not able to pass down the context menu service to the `ModifierKeyEmitter` easily. Maybe the `ModifierKeyEmitter` nedds an explicit method to tell it from the outside to reset?

**Comment by isidorn** [comment]
Yeah I had to go with that approach.
Added `resetKeyStatus` method that the context menu service call as a workaround.
Good news: got to delete lots and lots of depenencies on the contextMenuService

**Comment by bpasero** [comment]
Very cool!
