### ISSUE TITLE
scm.alwaysShowRepositories won't show status unless git.enableStatusBarSync is set

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#109055]
We shouldn't be linking these 2 settings. I hide the status bar entry, but want the status in the view.

**Comment by joaomoreno** [comment]
These aren't synced. The first controls the visibility of a view. The second controls the visibility of a status bar command.

The fact that we show status bar commands in repository rows is a hack to avoid having more API, but this will end pretty soon with the new UX advancements. We can no longer show the status bar actions up there, so this will automatically be fixed by that. I'm closing this for now.
