### ISSUE TITLE
Disable HTML tags mirroring cursor

### ISSUE THREAD

**Issue by yukpun** [microsoft/vscode#109018]
Issue Type: <b>Feature Request</b>

Please make possible to disable cursor mirroring for HTML syntax. 

VS Code version: Code 1.49.1 (58bb7b2331731bf72587010e943852e13e6fd3cf, 2020-09-16T23:21:17.533Z)
OS version: Darwin x64 19.6.0

![2020-10-20 17 30 28](https://user-images.githubusercontent.com/23419090/96600791-00d4c480-12fa-11eb-8eb8-8e7456af7bd5.jpg)

**Comment by IllusionMH** [comment]
/needsMoreInfo

This looks more like highlight for matched bracket pair instead of mirroring (there is no second cursor or synced changes there).
Is it what you want to disable?

`"editor.matchBrackets": "never"` will disable highlighting. If you need it only for HTML - the use [language specific setting](https://code.visualstudio.com/docs/getstarted/settings#_language-specific-editor-settings)

```json
"[html]": {
    "editor.matchBrackets": "never"
  }
```

**Comment by yukpun** [comment]
This is what I was looking for. Thanks
