### ISSUE TITLE
Editor context menu sometimes wrong

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#109166]
* open a TS file in a a codespace
* right click for context menu and see the usual goodness
* right click precisely on the cursor
* :bug: the context menu shows default entires only

<img width="898" alt="Screenshot 2020-10-22 at 15 32 40" src="https://user-images.githubusercontent.com/1794099/96879193-035f2780-147c-11eb-93b3-fd358dc0238c.png">

**Comment by ajschmidt8** [comment]
Also seeing incorrect context menu behavior. When I right-click in Python files, it only shows a few entries.

Here's my setup:

```
Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:31:29.624Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.8.18-050818-generic snap
```

![image](https://user-images.githubusercontent.com/7400326/99884603-95825900-2bfd-11eb-8374-f5f8892c77cb.png)

**Comment by bpasero** [comment]
I am seeing this very often in Chrome/Edge as well btw. I think @alexdima and me looked into this a long time ago and we found that it could be related to the editor not knowing that the right click happened on a word but somewhere in between. I also have zooming enabled which maybe makes this worse.

**Comment by alexdima** [comment]
This is caused by `TextInputActionsProvider` which shows a special context menu even when `e.defaultPrevented` is true for the `contextmenu` event. In other words, in Safari (I don't know why) it is possible to end up right clicking on the editor textarea when right clicking on the cursor. This triggers a `contextmenu` event. The editor handles it and calls `e.preventDefault()`. The editor never stops event propagation for any event and thus the event reaches the `TextInputActionsProvider`. This one sees that the target is a `textarea` and decides to show its own context menu. Doing the following diff in `src/vs/workbench/browser/actions/textInputActions.ts`:

![image](https://user-images.githubusercontent.com/5047891/105509069-6a83b680-5ccd-11eb-8487-ca14c7f6060e.png)

I can see that this log statement executes when managing to right click on the editor's textarea. 

I suggest that the default `TextInputActionsProvider` honors `e.defaultPrevented` as the browser would and should not render its context menu when that is set:


https://user-images.githubusercontent.com/5047891/105509153-84bd9480-5ccd-11eb-8fa1-8213e5ae3393.mp4

**Comment by bpasero** [comment]
Good findings, I hope this is the reason why I often got this generic context menu in web selfhost because it was very annoying 👍
