### ISSUE TITLE
Diff editor: show path as description

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#109224]
I often miss that git diff editors do not show the path of a resource as description, e.g. here:

![image](https://user-images.githubusercontent.com/900690/96989440-f5fe7780-1525-11eb-8702-79400331a567.png)

**Comment by joaomoreno** [comment]
Me too. It happens because [git uses the `title` option when invoking `vscode.diff`](https://github.com/microsoft/vscode/blob/0f1904834ba4d85ea4700ae24794de54ff03335e/extensions/git/src/commands.ts#L368-L368), as you once told me to do. Without passing a `title` option, this is how it looks:

![image](https://user-images.githubusercontent.com/22350/97003295-82fffb80-153b-11eb-87c8-2559d3e7f540.png)

Notice the description never appears, independently of using `title` or not. The `vscode.diff` command also [does not support passing `description`](https://github.com/microsoft/vscode/blob/a1932df627f36f77ad037a8d2bd46f70c0d089fa/src/vs/workbench/api/common/apiCommands.ts#L105-L105).

Ultimately I think the fix should be in the diff editor: it just seems like it never shows a description.

**Comment by bpasero** [comment]
@joaomoreno opened https://github.com/microsoft/vscode/pull/109289 to support passing in a description to the `vscode.diff` command, e.g.:

```ts
commands.executeCommand<void>('vscode.diff', left, right, title, 'Hello Diff Description', opts)
```

As I am not an expert in git code, could you adopt this for those diffs where the left and right resource is basically the same? I think that is the only case where the description would make sense.

In workbench core, we use this code to get a description label:

```ts
this.labelService.getUriLabel(dirname(resource), { relative: true });
```

**Comment by joaomoreno** [comment]
Replied in PR.

**Comment by bpasero** [comment]
Pushed a generic solution on the layer of the diff editor: if left and right resource can be handled by our file service and share the same parent path, a description is added.

![image](https://user-images.githubusercontent.com/900690/98656825-689e8e00-2341-11eb-9ac4-0d3f9ce1cb8a.png)

Unfortunately on the index, we only show the full path because of the `git` query I think:

![image](https://user-images.githubusercontent.com/900690/98656853-73f1b980-2341-11eb-9d67-a58e4244a47b.png)

**Comment by bpasero** [comment]
**Verification:** with tabs disabled, verify you see the folder as part of the editor label description when you click on a change from the SCM changes view. Make sure to click on a simple file change, not a rename, add or delete operation.
