### ISSUE TITLE
Option to change the title of the integrated terminal in vscode?

### ISSUE THREAD

**Issue by ldarshan1991** [microsoft/vscode#109235]
When I launch an application in vscode via launch.json. The application launches from the integrated terminal with the title of the terminal set to that application name.

How can enforce my choice of name for the terminal? Can I set some attribute in launch.json to achieve this?

![image](https://user-images.githubusercontent.com/28981482/96998740-a766d280-1551-11eb-8d20-3d89769d0423.png)

**Comment by weinand** [comment]
Currently it is not possible to configure the name of the integrated terminal session. On reason for this is that VS Code tries to reuse "free" integrated terminals before create a new one. WIth this strategy there is no guarantee that a configured name will be actually used.

**Comment by ldarshan1991** [comment]
Thanks for reverting @weinand 
But what I have observed is that - when I launch a C application using launch configuration, debugger always run the application in the new terminal.
How can I make it to use the existing terminal. Or a particular terminal number?

**Comment by ldarshan1991** [comment]
@weinand after contemplating your comment, I felt even if it reuses a free integrated terminal group it should be okay, since our application started to run under that integrated terminal. Renaming that terminal would provide the current context. Isn't it

**Comment by ldarshan1991** [comment]
@weinand Can I get an update on this?

**Comment by weinand** [comment]
VS Code determines whether the current (debug) terminal is "free" by trying to find child processes of the shell process running in the current terminal. If there are no such processes, the terminal is considered free and is reused. VS Code only looks at the integrated terminal that was started for launching a debuggee. It does not try to reuse other terminals (started explicitly by the user). 

Since it is not always possible to find the shell process of the terminal and determine its children, VS Code will fall back to always create a new terminal.

The only way to help VS Code in reusing a terminal is by making sure that no processes run in the debug terminal.

---

Supporting to name a terminal via a launch config involves the debug extension because the names and types of properties of a launch config are not defined by VS Code. So we (VS Code) cannot just add a "terminalName" property generically. Every debug extension that supports the integrated terminal needs to introduce a "terminalName" property in its launch config schema and pass this to the [`runInTerminal`API](https://microsoft.github.io/debug-adapter-protocol/specification#Reverse_Requests_RunInTerminal).

I suggest to file a feature request against the C++ debug extension.

(We can leave this issue open because VS Code has to make sure that the "name" used in a `runInTerminal` overrides the name of an existing terminal in the reuse case)

**Comment by ldarshan1991** [comment]
Thanks for your details explanation.
I will raise a feature request on C++ debug extension for this support.
