### ISSUE TITLE
Tasks: Cmd+Shift+B no longer starts default build task

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#109207]
Steps to Reproduce:

1. run selfhost web
2. open a multi root workspace with `vscode` and `vscode-docs`
3. hit `Cmd+Shift+B`

=> 🐛 you see this picker

![image](https://user-images.githubusercontent.com/900690/96959467-6eead880-1500-11eb-938b-0d6ace6d7a36.png)

I have never seen this before.

**Comment by alexr00** [comment]
It's because you have `extensions.webWorker` set to true. To work around until its fixed unset that.

**Comment by bpasero** [comment]
@alexr00 I tried that but now the experience seems worse:

![image](https://user-images.githubusercontent.com/900690/96970135-85e6f600-1513-11eb-8cfa-99733b0ca088.png)

After I hit `Cmd+Shift+B`

**Comment by bpasero** [comment]
Hm, I killed all my running build tasks, added this setting and reloaded web-selfhost and now it seems to work. But this seems very fragile to me, I have no clue what is going on behind the scenes :-/

**Comment by bpasero** [comment]
Btw this setting seems to be `false` by default already.

**Comment by alexr00** [comment]
Fixed by 0eda23e1122b9d6b863be9962d4d9f020276220d

There are task related code paths that don't work with the webworker extension host, and the task system was always using the webworker extension host if it exists (due to a bug). I've fixed this by correctly prioritizing non-webworker extension hosts.

**Comment by bpasero** [comment]
Thanks 🤝
