### ISSUE TITLE
No didClose/didOpen event when rename Java file to different cases

### ISSUE THREAD

**Issue by xqzlgy2** [microsoft/vscode#109220]
When renaming a Java file in file explorer, if old file name is `App.java` and new name is `App1.java`, Java language server will receive textDocument/didClose for old uri, then textDocument/didOpen for new uri, which is what we expected.

However, if we try to rename `App.java` to `ApP.java`, these two events will not be triggered, which may cause problems when Java language server try to update Java model.

**Environment**
- VSCode Version: 1.50.1
- OS Version: Windows 10
- JDK version: 11
- Language Support for Java version: 0.69.0

**Steps to Reproduce:**

1.Rename Java filename to different cases in file explorer (e.g App->ApP, ApP->App...)
2.Monitor Java language server's output and search for corresponding events, no search result found
3.Try other filename (e.g. App->App1), events triggered correctly.

**Current Result:**
No didClose/didOpen events in language server output

![image](https://user-images.githubusercontent.com/30518415/96976993-1131ad00-154f-11eb-8f6c-40ab60ebf359.png)

**Expected Result:**
Like rename file to a different name (App.java->App1.java), two events are triggered

![image](https://user-images.githubusercontent.com/30518415/96977949-61f5d580-1550-11eb-86bb-806e88b7b579.png)
![image](https://user-images.githubusercontent.com/30518415/96978000-733ee200-1550-11eb-93fc-3736b6120168.png)

**Comment by isidorn** [comment]
Forwarding to @jrieken and @bpasero since this comes from the WorkginFilesService if I am not mistaken

**Comment by bpasero** [comment]
You have to use `vscode.workspace.onDidRenameFiles` API to detect that a rename happened. Looking for text document events does not work. We have no way of renaming the URI of a text model unless you close all editors and restart. This is a consequence of introducing canonical URIs to fix https://github.com/microsoft/vscode/issues/12448

We will not go back because even though the current solution has its own set of issues, the other one was worse imho.
