### ISSUE TITLE
Weird word selection on double click

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#109353]
Steps to Reproduce:

1. have a ts file with `let storedUsername: string | undefined = undefined;`
2. double click `undefined`

=> 🐛 the word `undefined` is selected but also 1 space to the left

**Comment by alexdima** [comment]
@bpasero I cannot reproduce:

![TO_UPLOAD](https://user-images.githubusercontent.com/5047891/97177720-d9b54180-1796-11eb-92e1-19e4c072a6d3.gif)

**Comment by bpasero** [comment]
No clue, maybe a non-breakable-space was somehow part of it. I use web daily and sometimes see weird chars appearing out of nowhere but have not figured out what that is and typically they show with a `??`

**Comment by MrAndersen1** [comment]
This usually occurs (for me) if you have a nbsp instead of a regular space before said word.
These forms seem to replace them with regular spaces however the playground keeps them.
[Playground Link](https://www.typescriptlang.org/play?ts=4.0.2#code/DYUwLgBAzmD2BOIAmBVKJ4DsCGBbEAXNGPAJaYDmEAPgAUCumSIAZuchALwSPNubIA3EA)
Note that it is the first undefined that has a nbsp space in front of it in my link.

If you also add one before storedUsername and doubleclick it then it will select the let too.

Double-clicking the word is one way of finding that you have an unwanted space there. I assume you would just go with pretending that you only have regular spaces but I would prefer if they went away altogether as they break searches amongst other.

**Comment by bpasero** [comment]
@MrAndersen1 ah yeah that playground behaviour is exactly what I have seen 👍

**Comment by MrAndersen1** [comment]
@bpasero I never insert an nbsp, but when I do it is by accident.
