### ISSUE TITLE
Undo stack lost

### ISSUE THREAD

**Issue by FAQinghere** [Microsoft/vscode#10932]
**Update from bpasero on the issue:**

We loose the undo stack very easily when leaving a dirty file in a tab (not visible) and then saving the dirty file:

* open some tabs and make them dirty
* wait for a few seconds
* press "Save All"
* go to those tabs that where not visible and try to undo
=> you cannot undo

**Original description:**

- VSCode Version:
- OS Version: 1.4.0

Steps to Reproduce:

1. Make a change, with auto-save on focus lost enabled
2. Navigate away
3. Come back and find the undo stack lost

This bug was introduced on OSX a few version ago, but was not then affecting me on Windows (not sure how/why, given the common shell, but nonetheless, that's how it was).

I recently switched back to Windows, updated to the latest VSCode, and now I am suffering the same problem on Windows too.

**Comment by FAQinghere** [comment]
upon further investigation, upon auto-save (didn't check manual save... will do that next), it is throwing away the undo buffer for all changes made prior to the previous autosave. So you need to repeat the above steps 2 rounds to see the effect.
1. Make a test.txt file
2. Type "buffer 1"
3. Navigate away from VSCode
4. Navigate back to VSCode
5. Type "buffer 2"
6. Navigate away from VSCode
7. Navigate back to VSCode
8. Ctrl-z -> "buffer 2" disappears
9. Ctrl-z -> "buffer 1" SHOULD disappear, and used to, but no longer does
10. Sob :)

**Comment by FAQinghere** [comment]
This does NOT happen if you save manually, regardless of the auto-save setting.

**Comment by bpasero** [comment]
@FAQinghere I cannot reproduce. I am on Mac and I Alt+Tab out of the window and then come back. Can you try if this reproduces with extensions disabled:

From the command line, execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by FAQinghere** [comment]
Thanks for the quick follow-up. After disabling the only installed extension (just a syntax/color theme), everything seems to working correctly (on the Mac, I don't have the SP4 with me today).

Even after re-enabling the extension(s), everything still seems to be working just fine.

I'll let you know if it pops up again. Thanks again.

**Comment by bpasero** [comment]
@FAQinghere seems unlikely that this extension would cause an issue. It rather sounds to me that your issue is not as easy to reproduce as you described in your steps so there must be something else going on that causes it. 

I managed to find an issue which I am planning to fix: 
* open some tabs and make them dirty
* wait for a few seconds
* press "Save All"
* go to each tab and try to undo

=> you lost the undo stack

This happens independent from the auto save setting.

**Comment by FAQinghere** [comment]
Ah, that would explain why I saw it while working in real projects, but not when doing a little single file test project today. Thanks for sticking with it! I've been using Atom for a couple of months because of this, but I keep trying VSCode and look forward to coming back to it full time.

**Comment by bpasero** [comment]
@FAQinghere great, I actually see that many people have reported this. The fix is also available in our insider release on Monday if you want to try it earlier.

We are releasing preview releases of the next stable VS Code version for everyone to try and give feedback. These preview releases are not 100% tested and might be unstable but contain our latest features and bugfixes. You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders
