### ISSUE TITLE
Loosing resize handle when making widget too large

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#109447]
Testing #109394

See screen cast

![cast](https://user-images.githubusercontent.com/1931590/97276819-fd7c9400-1837-11eb-933d-4ea8c3a097cb.gif)

The problem is:

- the left broader doesn't offer a resize handle
- the right broader always resizes the window not the code completion widget.

**Comment by jrieken** [comment]
I think with some fine fiddling you can grad it again, esp when trying the lower right corner but I agree it's not good. I think I can tweak the sash size/width

**Comment by jrieken** [comment]
You should still be able to grab it but inwards. The sash handle sits center-aligned onto the border and since the outer part isn't visible anymore you should be able to grab the inner part. This can also be made simpler via the `workbench.sash.size`-setting. The only tweak I see here is to subtract half the sash width from the max width of the widget

<img width="1114" alt="Screenshot 2020-10-27 at 14 57 32" src="https://user-images.githubusercontent.com/1794099/97311532-beb10300-1864-11eb-808c-4e965dbedb91.png">

**Comment by jrieken** [comment]
There is now a padding of 22px for the top/bottom (matching the status bar and menu bar) and padding of 14px for the sides (matching the scroll bar width). That should make things much better
