### ISSUE TITLE
[css] Setting to hide CSS Color preview boxes

### ISSUE THREAD

**Issue by bjankord** [Microsoft/vscode#10943]
- VSCode Version: 1.4.0
- OS Version: Mac OSX El Capitan v10.11.5

I was curious if there is a setting I can change to hide the CSS color preview boxes?
I'm using the [Color Highlight extension](https://marketplace.visualstudio.com/items?itemName=naumovs.color-highlight) which reduces the need for the color preview box.

Here is an example of some colors with both the preview box and the color highlight extension.

<img width="621" alt="screen shot 2016-08-25 at 6 44 44 am" src="https://cloud.githubusercontent.com/assets/633148/17967979/ef768230-6a8f-11e6-8bc5-788d59e59b56.png">

**Comment by aeschli** [comment]
Unless there are more requests for that I'd rather add not add such an option in order to keep the number of options small.

**Comment by Matt-Butler** [comment]
+1, I would really like this feature too! I prefer to use the color highlight extension

**Comment by munteana** [comment]
I'd rather have the Color highlight functionality implemented to VSCode. The color highlight extension is poor documented. Besides that I would want to have a color preview to the scss/less color variables, in my projects I prefer to define colors variables instead of writing the hex or rgb code all the time. In other words the color preview is useless to me because it shows the preview in my _variables.scss file only. Should I add this as a new thread??

**Comment by bjankord** [comment]
@munteana I'd open a separate issue to request having the color highlight functionality implemented to VS Code. I'd like to keep this focused on a setting to hide CSS Color preview boxes.

**Comment by octref** [comment]
Hope I can turn it off. First I enjoy each left/right moving the same space, not two spaces. Second the square doesn't go well with my font.

**Comment by JasonEtco** [comment]
@aeschli I'm going to have to write my own CSS to do this, so here's a +1 request :)

**Comment by evrimoztamur** [comment]
I would like to have this option as well, as it currently messes up vertical cursor positioning as well. See the GIF below (I'm pressing the up and down arrow keys):

![2017-01-02_00-31-41](https://cloud.githubusercontent.com/assets/11677504/21583475/e479f49e-d082-11e6-85bf-90ce39fa5d42.gif)

**Comment by jmlntw** [comment]
I think it is better if we have a option to hide this. It messes up cursor positioning.

**Comment by nmsmith22389** [comment]
How could you not add this as an option? Am I the only one that finds these swatches super annoying? Not to mention they update very slowly, like if I move a line that has one up or down the swatch sticks on the old line for like a second before it finally move. Not to mention the fact that it also messes up spacing perception. I really don't like them and really prefer to just have the background of the color shaded but those extensions are basically pointless because I'm still stuck with that stupid square.

**Comment by aeschli** [comment]
I'll add an option for February...

**Comment by braver** [comment]
Would be *so* nice to be able to turn this off/on for specific scopes. eg. I could really use these in tmTheme files.

**Comment by wpjim** [comment]
So glad this option is being added! Really, any feature that adds extra characters to your code (not just colorizing or marking it in some way) should be optional.

**Comment by bjankord** [comment]
Thanks @aeschli!

**Comment by jmbelloteau** [comment]
Any news about this features? Can't found any option to color box off...

**Comment by dutzi** [comment]
@jmbelloteau `"css.colorDecorators.enable": false`

**Comment by jmbelloteau** [comment]
Is it suppose to work on SCSS too? I'm only using SCSS and it's not working for me.

**Comment by aeschli** [comment]
@jmbelloteau "scss.colorDecorators.enable": false

**Comment by jmbelloteau** [comment]
@astitcher sharp answer amazing 😄  !

**Comment by mitjafelicijan** [comment]
I am also having some doubts about the current implementation. Color picker is messing up with padding. As you can see in attachment this adds some additional padding on the left and it is kind of distracting.

![screenshot from 2017-09-15 00-29-50](https://user-images.githubusercontent.com/296714/30458712-0c677f6e-99ad-11e7-9362-2e8aebc02687.png)
