### ISSUE TITLE
Ask again if credentials don't work

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#109495]
Testing #109377

Entering the wrong credentials makes the dialog disappear for the current session. I'd expect it to stay and tell me that the credentials didn't go through. I can then correct them or cancel.

**Comment by bpasero** [comment]
Yeah, though this is exactly how we behave today already.

**Comment by bpasero** [comment]
Slightly related to https://github.com/microsoft/vscode/issues/104853

**Comment by joaomoreno** [comment]
I forget why this was implemented this way, but I bet it has something to do with the inability to distinguish between bad credentials and multiple requests.

**Comment by bpasero** [comment]
Yeah, Electron itself does not distinguish from the event I fear. @deepak1556 is that true? You cannot tell if the login event originates because the credentials are wrong vs. not provided?

Maybe we can implement our own smartness here if we know that the credentials have been provided in the session and simply show it again.

**Comment by deepak1556** [comment]
Actually there is a way, just not documented because it was added in recent versions. [firstAuthAttempt](https://github.com/electron/electron/blob/master/shell/browser/login_handler.cc#L70) on the details object will indicate whether this is primary attempt for a given server otherwise we can conclude its from a failed attempt.

**Comment by joaomoreno** [comment]
Seems to work, lets me correct the credentials only one.
