### ISSUE TITLE
notification is not shown when extension waderyan.gitblame is hogging filesystem and CPU after hundreds of files get changed at once

### ISSUE THREAD

**Issue by capaj** [microsoft/vscode#109410]
Currently vscode logs a message into the console when the an extension host is hogging CPU. Here is the line:
https://github.com/microsoft/vscode/blob/55476af3b00ecfee88dc684738232c9cbda40785/src/vs/workbench/contrib/extensions/electron-browser/extensionsAutoProfiler.ts#L144

well my request is that it also shows a notification down right.  The message can be exactly the same as the one logged.
I hate slow extensions and I want to eradicate them from my vscode. Most users who suffer from slow extensions don't even realize it. This will make it apparent for them.
If we'd want to make it supercool, the notification would also have "disable" and "uninstall" buttons.

**Comment by jrieken** [comment]
Scroll a little further and see that we are doing this 🤓 Tho, only when it's really bad because we don't want to be annoying and short'ish blocks happen more often than you would think

https://github.com/microsoft/vscode/blob/55476af3b00ecfee88dc684738232c9cbda40785/src/vs/workbench/contrib/extensions/electron-browser/extensionsAutoProfiler.ts#L180-L195

**Comment by capaj** [comment]
I have a huge repo-about 280k lines of code.
And I ran into this with a very popular extension(687k downloads): `waderyan.gitblame` when I was generating a lot of files using https://graphql-code-generator.com/

I don't know how `this._blame.size` is computed, but it seems like it may be tweaked a bit, because the editor was in a weird state. It was not really stuck-I could click around, but when I saved a file, prettier couldn't run and I couldn't refresh git.
Now that I think about it, that extensions is probably watching files in the whole project and probably doing nasty stuff on filesystem with each change it detects or something like that.
And as the codegen changes hundreds of files at once, it probably ran amok.
It's certainly a problem of the extension, I just wish VSCode could detect and warn about such a bad behaviour. Especially when there is a code in place attempting to do it already.
Will rephrase the issue title.

**Comment by jrieken** [comment]
We show a notification when the extension host freezes so that other extensions cannot run. However, we don't blame extensions that are just using many resources because that's what many extensions needs to do. I suggest you follow up with the author of that extension. No changes planned on our side.
