### ISSUE TITLE
Why is `editor.suggest.maxVisibleSuggestions` limited to 15

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#109478]
Testing #109394

With the new resize behavior I can make it larger than 15 items.

**Comment by jrieken** [comment]
Yeah, the whole setting lost its value. It's now interpreted as the preferred size

**Comment by jrieken** [comment]
There these options

1. remove the limit of 15 items (e.g use 100) but honour the setting. 
1. deprecate the the setting

I am in favour of option 2 because custom sizes of the suggestion widget are also persisted/synced which makes the setting obsolete. Also, many users that have configured the setting will have a bad experience with resizing suggestions because till today it cannot be more than 15

**Comment by jrieken** [comment]
Closing - the setting is deprecated and not honoured anymore
