### ISSUE TITLE
Redo is not working anymore

### ISSUE THREAD

**Issue by fab1o** [microsoft/vscode#109503]
- VSCode Version: 1.50.1
- OS Version: 10.14.6

Redo is simply not working anymore (inconsistently)

Redo used to work before just fine with Auto Save enabled.

**Redo should always work, all the time, regardless of any other external factor or condition.**

Steps to Reproduce (not consistent):

1. Enable Auto Save
2. Undo then try to Redo 

Expected: Redo to work just fine

Actual: Redo doesn't do anything

Related issue: https://github.com/microsoft/vscode/issues/108688

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexdima** [comment]
> Redo should always work, all the time, regardless of any other external factor or condition

The redo stack is destroyed when an edit occurs. e.g.:

* if you open a file: the undo stack is `[]`, the redo stack is `[]`
* if you do an edit `A`: the undo stack is `[inv(A)]`, the redo stack is `[]`
* if you undo once: the undo stack is `[]`, the redo stack is `[A]`
* if you now proceed and do an edit `B`, the redo stack is destroyed: the undo stack is `[inv(B)]`, the redo stack is `[]`.
* obs: `A` cannot be left in the redo stack because it cannot be applied without some kind of transformation after `B` has been applied. AFAIK this is normal behavior for any text/code editor.

So the redo stack is destroyed only when the text buffer gets a new edit.

I have tried on my machine with your provided steps and for me the undo/redo stacks work correctly. Do you perhaps have some special setting or perform special steps (e.g. format on save) that might cause an edit to be applied on the text buffer?

**Comment by ccornici** [comment]
Having the same issue, I've hit CTRL+Z by mistake and undone a few dozen changes, then hit CTRL+Y and it undone only 2-3 changes, also hit CTRL+SHIFT+Z and nothing.....this only started happening in the past few days

**Comment by alexdima** [comment]
@ccornici Could you please create a new issue with reproducible steps?

**Comment by TGotwig** [comment]
I have the english version of vs-code and a us keyboard but somehow `ctrl + z` removes the current line and `ctrl + y` makes the redo, which I want to be happen on `ctrl + z` like usual for us keyboards, maybe because I switched often between german and english layout I broke something 😖

keybindings.json just:
```json
[
  {
    "key": "alt+p",
    "command": "workbench.action.quickOpen"
  },
  {
    "key": "shift+alt+p",
    "command": "workbench.action.showCommands"
  },
  {
    "key": "shift+alt+up",
    "command": "editor.action.copyLinesUpAction",
    "when": "editorTextFocus && !editorReadonly"
  },
  {
    "key": "shift+alt+down",
    "command": "editor.action.copyLinesDownAction",
    "when": "editorTextFocus && !editorReadonly"
  }
]
```

**Comment by alexdima** [comment]
@TGotwig Can you please create a new issue? It would be helpful to learn your OS, like are you on linux on windows? If you have a problem with keybindings, you can self troubleshoot it by using [the following](https://github.com/microsoft/vscode/wiki/Keybinding-Issues#basic-troubleshooting):

* Run the command `Developer: Toggle Keyboard Shortcuts Troubleshooting`
* This will activate logging of dispatched keyboard shortcuts and will open an output panel with the corresponding log file.
* Press exactly the keybinding you desire
* check what VS Code detects and what command is invoked.

**Comment by TGotwig** [comment]
Fixed by just removing the german keyboard layout from Ubuntu 20.04 🔥😊👍
