### ISSUE TITLE
Explorer: Install VSIX context action UX tweak

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode#109509]
Testing #109357

- Downloaded https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode VSIX file
- Copied to workspace, right-click, `Install VSIX` from the context menu

The extension installed correctly, I was given a notification, and I was moved to the Extensions viewlet, but I was anticipating the newly installed extension to be selected and its readme to show up in focus as well.

![image](https://user-images.githubusercontent.com/25310137/97331845-1173c600-1837-11eb-8ead-161d9b6cacb3.png)

Perhaps we could detect the most recently-installed extension and set it in focus? Or add an option in the notification to open the readme?

**Comment by bamurtaugh** [comment]
I just tried with https://marketplace.visualstudio.com/items?itemName=softwaredotcom.music-time, and after installing, my focus was automatically moved to the readme within the extension itself:

![image](https://user-images.githubusercontent.com/25310137/97333140-72e86480-1838-11eb-98f2-d5e6c0b565ce.png)

**Comment by joaomoreno** [comment]
I don't think we should show anything by default other than that notification. But it needs tweaking. This is what I got after installing the Panda theme:

![image](https://user-images.githubusercontent.com/22350/97421253-967cdf00-190c-11eb-8a3f-b85833fd96da.png)

- I expected no changes to my views: file explorer should stay active and focused.
- The notification should have a button to `View Details`, which then opens [the extension editor](![image](https://user-images.githubusercontent.com/22350/97421626-09865580-190d-11eb-9da1-823ee403cc46.png))

Additionally maybe we should rephrase more like:

```
The 'Panda Theme' extension has been successfully installed.
```

Finally, should the action be `Install Extension VSIX` rather than simply `Install VSIX`?

**Comment by lszomoru** [comment]
Thanks for the feedback. At the moment all actions to install an extension (Extensions viewlet, context menu, drag'n'drop) have the same default behavior - Extensions viewlet is shown with the `@installed` query. Having said that, I see why we do not want to break the flow when the VSIX is installed from the explorer. 

I do like the idea of a button to `View Details` of the installed extension. @sandy081, what's your take on that?

**Comment by sandy081** [comment]
I agree that installing the VSIX from explorer should not change the view. Instead user shall be asked in the prompt.

**Comment by lszomoru** [comment]
@sandy081, do you want me to file an issue to track the improvement to add the `View Details` button into the notification dialog?

**Comment by sandy081** [comment]
Yeah sure/

**Comment by lszomoru** [comment]
Filed #109607
