### ISSUE TITLE
Possibly leaking notebook documents

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#109594]
I don't have reproducible steps yet, but I suspect this to be related to me taking the screenshots and verifying the steps in https://github.com/microsoft/vscode/issues/109549. Happened when I wanted to restart for update.

![image](https://user-images.githubusercontent.com/4674940/97441274-c664bc00-18e5-11eb-9054-dec3c5effd57.png)

**Comment by jrieken** [comment]
@rebornix I suspect this is because the notebook SCM logic doesn't use the ref counted notebook model but because it creates its own models

**Comment by jrieken** [comment]
Wait... It does use ref-counted notebooks except for the original which I believe makes sense... Maybe this is actually caused by #110479 which means we have been leaking editors and such

**Comment by jrieken** [comment]
I am confused, looks like `src/vs/workbench/contrib/notebook/browser/contrib/scm/scm.ts` isn't used at all. @rebornix can you confirm? can we nuke that?

**Comment by rebornix** [comment]
@jrieken the SCM contrib was not loaded at all and I pushed a change to remove the files for now. What else do you think can cause this or you think the problem is gone now?

**Comment by jrieken** [comment]
idk - didn't see this anymore. might have been #110479 which leaked the list templates which then leaked editor and documents. optimistically closing

**Comment by jrieken** [comment]
I have just seen this, happens when pulling from git and when changes for the same notebook arrived

**Comment by jrieken** [comment]
This actually very easy to reproduce. Tho, I might do something different which yields the same error but the first steps win ;-)

Do this

* open a GH issue notebook
* in the integrated terminal open the same notebook in vim
* in VIM make changes and save
* go to the notebook and save
* :bug: the error shows

It seems that the core isn't listening for file events and isn't asking the notebook provider for new contents... I do remember that we have discussed this and concluded that the core should be responsible for this, not the extension (since a notebook content provider is more or less stateless)

**Comment by jrieken** [comment]
ping @rebornix

**Comment by rebornix** [comment]
> open a GH issue notebook
in the integrated terminal open the same notebook in vim
in VIM make changes and save
go to the notebook and save
🐛 the error shows

@jrieken we currently didn't do notebook content auto update yet, right now we only compare on save.

**Comment by jrieken** [comment]
Closing this as dupe of the actual leakage #110479 and extracting the previous comment into a new issue. Tho, us not reloading notebook when they change on disk is major selfhost pain and IMO we should tackle that rather sooner than later
