### ISSUE TITLE
unbound breakpoint with preview debugger and runtimeArguments launch config

### ISSUE THREAD

**Issue by restjohn** [microsoft/vscode#109631]
I am using VS Code for debugging my TypeScript/JavaScript Node app.  I have a launch configuration like the following in my `launch.json`.
```
        {
            "name": "mage instance dist",
            "type": "node",
            "request": "launch",
            "program": "${workspaceFolder}/instance/main.js",
            "runtimeArgs": [ "--preserve-symlinks" ],
            "cwd": "${workspaceFolder}/instance",
            "console": "integratedTerminal",
            "preLaunchTask": "service:build",
            "sourceMaps": true,
            "outFiles": [
                "${workspaceFolder}/service/src/**/*",
                "${workspaceFolder}/service/lib/**/*.js",
                "${workspaceFolder}/instance/main.js"
             ]
        },
```
This used to work some time in the last few weeks, however, with the current version of VS Code, breakpoints will not bind to my TS files.  Peculiarly, when I remove the `runtimeArguments` option from my launch configuration, the debugger binds the breakpoints as expected.  When I uncheck the setting to use the in-preview debugger, the breakpoints bind as expected with the `runtimeArguments` setting present in the launch configuration.

**VS Code Version**
Version: 1.50.1
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T14:53:05.704Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0
 
A trace file is attached.
[vscode-debugadapter-8.json.gz](https://github.com/microsoft/vscode/files/5455313/vscode-debugadapter-8.json.gz)

**Comment by connor4312** [comment]
In the log you sent, you set a breakpoint in

```
/Users/stjohnr/sandbox/mage/mage-server/service/src/main.impl/main.impl.plugins.ts
```

However it looks like Node.js reported that it loaded what I assume is that file from

```
/Users/stjohnr/sandbox/mage/mage-server/instance/node_modules/@ngageoint/mage.service/lib/main.impl/main.impl.plugins.js
```

The problem is that this path does match and. (And because it is outside of the outFiles we ignore its sourcemap.) I'm not sure what your build setup look like, but you may also need [--perserve-symlinks-main](https://nodejs.org/api/cli.html#cli_preserve_symlinks_main) if the entire 'instance' folder is symlinked....

**Comment by restjohn** [comment]
Thanks for your reply.  I see the discrepancy.

My project is basically a monorepo of packages, one being `instance` and one being `service` (among others).  The `instance` packages depends on `service`.  When debugging, I use relative path dependencies in `instance` on the other packages,
```
"dependencies": {
    "@ngageoint/mage.service": "../service",
   ...
 }
```
which npm installs as symlinks in `instance/node_modules`.  This is apparently what causes the path discrepancy you found.

When debugging against symlinked modules this way, I need `--perserve-symlinks` so that the non-relative imports that reference the "local" package names resolve correctly.  `--preserve-symlinks-main` did not help.  I assume the underlying issue is the way the old debugger handles the sourcemaps compared to the new debugger.

**Comment by connor4312** [comment]
Okay, thanks for following up. You could change the last line of your outFiles to `"${workspaceFolder}/instance/**"` to resolve everything in that folder, or set `resolverSourceMapLocations: null` to remove filtering places where we resolve sourcemaps to the outFiles.

This will cause us to resolve the sourcemap in the file, which depending on how your sourcemap is built may be sufficient to look up the original file.

I intend to add some smarter handling to try to detect and deal with symlinks automatically, since difficulty or confusion is common in monorepo cases https://github.com/microsoft/vscode-js-debug/issues/776

**Comment by restjohn** [comment]
Thanks.  Unfortunately, neither of those two config changes caused the breakpoint to bind successfully.  However, if I change `outFiles` to include `${workspaceFolder}/instance/node_modules/@ngageoint/mage.service/lib/**/*.js`, then I browse to the symlinked `main.impl.plugins.ts` under `instance/node_modules` instead of its normal source tree location, and set the breakpoint there, the debugger binds and pauses on the breakpoint.  The problem is that VS Code treats the symlinked and native path versions of `main.impl.plugin.ts` as different paths and opens them with different editors, and I can create two separate breakpoints referencing both paths of that file.

**Comment by connor4312** [comment]
Sorry, I had it switched around in mind head.

You have `--preserve-symlinks` turn on, which will cause the path in `node_modules/@ngageoint/mage.service/lib/main.impl/main.impl.plugins.js` to be preserved. You want to turn preserve symlinks _off_, so that Node resolves it to the source file location that we can cross-referenced against your input source correctly. So I believe removing the `--preserve-symlinks` argument is the right thing to do for you.

I want to explore adding some logic to avoid needing to manual preserve (or, in this case, un-preserve) symlinks. Follow https://github.com/microsoft/vscode-js-debug/issues/776 for updates.

**Comment by restjohn** [comment]
Unfortunately I need `--preserve-symlinks` to remain enabled so I can properly resolve my monorepo package modules by their package names.  I'll have to stick to the old debugger until this is fixed in the new one, unless you know of another way to resolve my monorepo package modules by non-relative names that works with the current preview debugger's behavior.

**Comment by connor4312** [comment]
You can adjust your tsconfig's [`sourceRoot`](https://www.typescriptlang.org/tsconfig#sourceRoot) to point to your sourceFiles

**Comment by restjohn** [comment]
My apologies; I don't follow how that helps.  Can you elaborate?

**Comment by connor4312** [comment]
The issue is that you have a sourcemap in `node_modules/@ngageoint/mage.service/lib/main.impl/main.impl.plugins.js.map` which points to a relative path for its .ts, like `../../src/main.impl/main.impl.plugins.ts` which points to a location in your node_modules that looks different from the source you have your breakpoints in. If you set the sourceRoot, you can configure the base path used for the relative path resolution to be the real location rather than the symlinked one.

**Comment by restjohn** [comment]
Ah, so I'd have to set the `sourceRoot` to an absolute path then?

**Comment by connor4312** [comment]
You can set it to a relative path -- however many `../` and transversals are needed to point to your source location 🙂
