### ISSUE TITLE
New File improvements

### ISSUE THREAD

**Issue by matejkramny** [Microsoft/vscode#10967]
**Scenario:**
- Editing a file `y.txt` inside a directory `x`
- I want to create a new file `z.txt` in directory `x`
- I am a user who likes to be efficient and loves keyboard shortcuts

**Workflows to create new files:**
1. Take over control of the mouse/trackpad, navigate to +file icon (top left next to explorer). A new file is created inside `x` and I can name it `z.txt`, then edit its contents.
2. Press `cmd+n`, which opens a new file. Now I want to save it so I press `cmd+s` and proceed to name the file, navigate to `x` directory and save. I can edit the contents before and after saving

**Problems with current workflows:**
- Method 1 of creating a new file is good, but I need to take control of the mouse/trackpad. 
- Method 2 can be done keyboard-only but is less efficient than method 1 as it requires thinking about where `x` directory is and how to find it.

**Improvement proposal:**

I am proposing the ideal workflow with the given scenario.
1. Edit the file `y.txt`, which is in `x`
2. Press `cmd+n`, editor opens new file
3. I type the file name inside the new editor tab (as file content)
4. Press `cmd+s` to save file, the editor takes the first line of the content as file name and saves it into `x`b y default
5. The first line either stays as it is or is deleted and I can go on writing the new file

**Comment by mattferderer** [comment]
Atom has a great package called Advanced Open File which is a fork of multiple earlier projects. I think this would be the ideal solution to what is being described above & should be added to the core functionality of VS Code instead of a plugin.  It does pretty much what you're describing @matejkramny and a bit more. Instead of writing the text in the new line you write it in the Command Pallete or the Goto File window. It essentially allows you to either open a file or create a new file (including any necessary folders that need to be created). It also lets you tab to open a folder that you have partially typed. Very slick.

**Comment by ScFix** [comment]
A improvement to this could be when your focus is on a folder in the Explorer pressing Ctrl+n would provide the same functionality as right clicking the folder and selecting new file. 

This functionality could be extended to the files inside the folder so it would create a file next to the currently selected file when the focus is on the explorer.

**Comment by isidorn** [comment]
There is `file: new file` command that does this. Just add a custom keyboard shortcut which will smoothen your process.
