### ISSUE TITLE
Debug hover expands over cursor

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#109653]
* see gif
* have the debug hover above the cursor
* expand some objects
* the hover grows over the current line/cursor

![Oct-29-2020 09-33-21](https://user-images.githubusercontent.com/1794099/97544443-e79ed880-19c9-11eb-8b31-d29e57cfdd75.gif)

**Comment by isidorn** [comment]
Yeah, this is a consequence of the change to not make it jump.
Since in this scenario it does not have enough space above to grow, it can only grow over the line and below. Alternative would be to show it down, which would cause a jump. Or to limit the size, that it does not grow over the current line. That I think makes sense. However will not tackle during endgame.

**Comment by jrieken** [comment]
> Since in this scenario it does not have enough space above to grow, it can only grow over the line and below.

How about not growing and use the scrollbar sooner? Just measure the max size above the cursor and don't go over that

**Comment by isidorn** [comment]
I think this makes sense. My current max height is 70% of the editor height. Idealy as you suggest the max height should be the size above the cursor if I am placed above, or max size below the cursor if I am placed below.
However I am not aware of editor API that gives me height above or below the cursor. Are you already using something like this for the suggest?

**Comment by jrieken** [comment]
I am using `getScrolledVisiblePosition` and some math: https://github.com/microsoft/vscode/blob/cd0c631b1fe6833a53533d89e143a9bd5dc010b9/src/vs/editor/contrib/suggest/suggestWidget.ts#L757
