### ISSUE TITLE
Html previewer

### ISSUE THREAD

**Issue by hamid647** [microsoft/vscode#109739]
Issue Type: <b>Feature Request</b>

provide live html preview like Atom

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T14:57:08.739Z)
OS version: Windows_NT ia32 10.0.17763

**Comment by COD3BREAK3R** [comment]
> We try to keep VS Code lean and we think the functionality you're asking for is great for a VS Code extension. Maybe you can already find one that suits you in the [VS Code Marketplace](https://aka.ms/vscodemarketplace). Just in case, in a few simple steps you can get started [writing your own extension](https://aka.ms/vscodewritingextensions). See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.
> 
> Happy Coding!

VS Code Team, really want to keep vs code clean? Why have include the auto close functionality of html tags when there was an extension that did it? and why have included the auto rename html tag function when exist a extension that do this? I think it is not a valid justification to say that they have not implemented it because it would be great for a VS Code extension.
