### ISSUE TITLE
OPEN_TO_SIDE_COMMAND_ID should not use fileservice to detect folders

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#109780]
I think this `resolveAll` code can be avoided by simply checking the explorer model wether the selected files are files or folders:

https://github.com/microsoft/vscode/blob/b9a84341783c5aa6c103dec203bf2808dd1b9b57/src/vs/workbench/contrib/files/browser/fileCommands.ts#L137-L137

Maybe use the file service only as a fallback if the resources are not originating from the explorer or open editors view.

**Comment by isidorn** [comment]
Makes sense. Assigning to November to tackle this week.

**Comment by isidorn** [comment]
Pushed a change as you suggested.
Had to use the file service as fallback as it can happen that a file is in open editors view and that it is not resolved in the explorer. For example have a/b/test.txt open and not focused tab, do not have that file expanded, reload. Open to the side from open editors on that item will have to go to the file service, since explorer service is not aware of it.
