### ISSUE TITLE
configurationDefaults contribution changes JSON auto-complete behavior

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#109709]
Reported originally by @JacksonKearl where GitLens seemed to be breaking JSON auto-complete behavior -- causing an extra `"` being added at the end.

![recording (16)](https://user-images.githubusercontent.com/641685/97644218-2495ba00-1a20-11eb-9442-b1e44789c4d4.gif)

I tracked it down to this contribution causing the issue

```json
"configurationDefaults": {
	"[json]": {
		"gitlens.codeLens.scopes": [
			"document"
		]
	}
}
```

I was able to reproduce this with a clean vscode user-dir/extensions-dir and a simple extension with that contribution

**Comment by aeschli** [comment]
That JSON extension has `[json]` configurationDefault for the `editor.suggest.insertMode` setting:
https://github.com/microsoft/vscode/blob/master/extensions/json-language-features/package.json#L109

That configurationDefault is lost when the gitlens extension also makes a  `[json]` configurationDefault 

The bug is that all default overrides for the same language need to be merged, not set.
https://github.com/microsoft/vscode/blob/master/src/vs/platform/configuration/common/configurationRegistry.ts#L240
