### ISSUE TITLE
Keep editors open instead of closing them when loading fails on startup

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#110062]
Helps for https://github.com/microsoft/vscode-remote-release/issues/3475

**Comment by CodeSammich** [comment]
For me, it seems to only occur in two scenarios:

1) When disconnected from SSH, any options besides "Reload Window" is selected will remove old tabs (e.g. Close Remote)

2) When disconnected from SSH due to inactivity and the auto-reconnect options are not given, possible due to "successful" reconnect. This may be due to the auto-reconnect using the same logic as "Close Remote" -> "Connect" instead of "Reload Window" after SSH connection is established.

**Comment by bpasero** [comment]
Pushed a change to keep editors open when the fail to restore:

![recording](https://user-images.githubusercontent.com/900690/129537532-8f40090d-6a19-4bdf-b1e9-a6fc55dffc4d.gif)

This is enabled by default but depending on feedback might warrant for a setting. The editor will still close automatically when the act of opening an editor newly fails.

**Comment by apeforever** [comment]
Could you add a setting please ? Thanks a lot

**Comment by bpasero** [comment]
Can you open a new feature request for that please.
