### ISSUE TITLE
Terminal local echo may not remove predictions when typing while yarn is running

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#110042]
This happened when I typed `yarn watch<enter>` during `yarn`

![image](https://user-images.githubusercontent.com/2193314/98302443-3c65c480-1f71-11eb-9cf0-99edb98191ec.png)

It's expected that these characters may pop up, but I think they should always show in the default text color. We want to match the regular behavior when local echo is off.

This is what happens when local echo is off (the enter moves to the next line and it continues on thinking the next line is the progress bar):

![image](https://user-images.githubusercontent.com/2193314/98302594-83ec5080-1f71-11eb-81cf-cc56d2f81079.png)

**Comment by connor4312** [comment]
> > It's expected that these characters may pop up, but I think they should always show in the default text color. 

Do you mean to use the default text color for predictions in this case (with some way to detect?)

It's not good that predictions remained on your screen after the next progress bar invalidated them. But this scenario is likely to be racey I think because there's a lot of data coming down the pipe with cursor moves; the position at which we read the cursor when we start predictions initially might not be synchronized exactly right with the remote...

**Comment by Tyriar** [comment]
> Do you mean to use the default text color for predictions in this case (with some way to detect?)

No I mean typing without local echo will result in the characters being printed using the default color before the progress bar replaces them. So when the predictions get rolled back that should be the state as well.

> But this scenario is likely to be racey I think because there's a lot of data coming down the pipe with cursor moves

I might be misunderstanding, isn't xterm.js' state all you need to rely upon, not the cursor position on the other side? Since all data goes through the addon it's inherently non-racey provided we reliably rollback the predictions?
