### ISSUE TITLE
vscodebot is adding the tag *out-of-scope, and the issue closed

### ISSUE THREAD

**Issue by tamuratak** [microsoft/vscode#110047]
`vscodebot` itself, not a member of the dev team, is adding the tag `*out-of-scope` to some issues with enough upvotes, and the issues are closed. Is this an intended behavior?

- #11723
- #22841
- #41289
- #42170
- #50035
- #61838
- #84120

**Comment by mika76** [comment]
Any news on this - all these issues were supposed to be on the backlog and then just disappeared...

**Comment by shanecbauman** [comment]
Commenting for some more visibility on this post. Any updates?

**Comment by hammypants** [comment]
+1 searched for two issues today where the bot closed things

**Comment by HuskyNator** [comment]
Still hoping for backgrounds

**Comment by Mrkol** [comment]
Implementing backgrounds is such a simple feature, why is it getting swept under the rug? Background transparency as well. Windows terminal guys figured this stuff out years ago, yet vscode closes relevant issues via an automated bot with zero explanation? What the heck?!

**Comment by OmgImAlexis** [comment]
@Tyriar if you're not the right person to tag can you please tag them as this is getting worse as time goes on with it closing more and more issues.

**Comment by Tyriar** [comment]
These were closed as out of scope while we were issue grooming as mentioned in the closing comment. See https://github.com/Microsoft/vscode/wiki/Issue-Grooming#out-of-scope-feature-requests

> Here are the criteria we use to make the decision about closing a feature request:
> 
> - Does the functionality described in the feature request have any reasonable chance to be implemented in the next 24 months? 24 months is longer than our roadmap which outlines the next 6-12 months. Thus, there is some crystal ball reading on our part, and we'll most likely keep more feature requests open than what we can accomplish in 24 months.
> - Has the community at large expressed interest in this functionality? I.e. has it gathered more than 10 up-votes or more than 10 comments? This criterion alone covers more than 650 of the 2850 open feature requests as of right now, October 9th, 2019.
> - Do we think the feature request is bold and forward looking and would we like to see it be tackled at some point even if it's further out than 24 months? (Clearly, this one is the most subjective criterion.)
If the answer to any of the three questions is yes then we ask about affordability:
> 
> Can our team afford to implement the feature? I.e. are the costs to implement the functionality reasonable compared to the size of our team?

Chances are they were closed because they likely won't get done in the next 24 months or ever. The team needs to make some decisions sometimes which are hard for the sake of avoiding feature bloat and maintaining our sanity (issue count); no the bot didn't close the issues without some human interaction. You can see why we would let a bot do this instead of a person because of some of the reactions you see in the issues and here.

Regardless, it's much better for everyone if we're honest and close the issue instead of keeping your hopes up. Taking custom background as an example, I expect this would simply never get implemented as it's kind of the definition of feature bloat, there's also extensions available that give you a workaround if it's that important to you.
