### ISSUE TITLE
Feature request: go to file by full path from git repository root

### ISSUE THREAD

**Issue by vvakame** [microsoft/vscode#110055]
I want to go to file(Cmd+P) by absolute path from git repository root.

I'm coding with below project structure.
```
.
├── .git
│   └── ....
├── api
│   └── main.go
└── front
    └── app.ts
```
and, I open `./front` directory with VSCode.

when I execute `git status` command in project root, I got below result.
```
Changes to be committed:
  (use "git rm --cached <file>..." to unstage)
	new file:   front/app.ts
```
so, I copy&paste `front/app.ts` to `go to file` input box, but got `No matching result`.
I understand that I will input `app.ts` to input box, but sometimes it gets messy...
JetBrains's IDE support it. I hope it will be easier to transfer if this is supported.

**Comment by joaomoreno** [comment]
There isn't much we can do here. Quick open always runs off the top of the workspace folder, regardless of what your git roots are.

My suggestion is to simply open the terminal from within VS Code. I say this because since you opened the `./folder` folder as the workspace folder, the terminal will have its cwd in `./folder` and git will return this instead:

```
Changes to be committed:
  (use "git rm --cached <file>..." to unstage)
	new file:   app.ts
```

Then, there's a quick tip: hold <kbd>Ctrl</kbd> and hover over the file name in the Terminal, you'll be able to click it directly to open, instead of having to copy paste the value.
