### ISSUE TITLE
Mulitline copy/pasting

### ISSUE THREAD

**Issue by vsamy** [Microsoft/vscode#11007]
- VSCode Version: 1.4.0
- OS Version: ubuntu 14.04

Steps to Reproduce:
1. shift+alt to get multicursors on several lines
2. ctrl+x to cut
3. ctrl+c to paste

![out](https://cloud.githubusercontent.com/assets/8289611/18000166/0b569e98-6b7d-11e6-87b7-e9f3818eb854.gif)

**Comment by sandy081** [comment]
@vsamy I am not sure if I understand what is your requirement / issue here. Can you please elaborate more?

**Comment by vsamy** [comment]
Sure.

In vscode to copy/cut paste a line you usually do a ctrl+x/ctrl+c then a ctrl+v. This is very convenient but it only can be done one line at a time. If i have multicursor and try to cut/copy paste all the line at the same time it does not work and leave blank lines. Maybe i missed a shorcut on multiline copy pasting.

It is like a '4dd' 'p' in vim for example.

I hope it is more clear to you now.

**Comment by Bill-Stewart** [comment]
Does code have a 'select current line' command (like if I move to column 1 then press `shift+end`)?

**Comment by Bill-Stewart** [comment]
You can do this by selecting all or part of the lines, press command for `expandLineSelection` (default `ctrl+i`), then cut/copy/paste or reposition lines using `moveLinesUp` (default `alt+up`) and/or `moveLinesDown` (default `alt+down`).

**Comment by vsamy** [comment]
Ok, thank you for the tips.

**Comment by Bill-Stewart** [comment]
@vsamy - does this answer it - can this issue be closed?

**Comment by vsamy** [comment]
Sorry for the late answer.

It does give me a way to bypass my problem and it works properly. It depends on whether or not you do want to correct this copy/paste problem or not.

**Comment by Bill-Stewart** [comment]
@vsamy - what copy/paste problem are you referring to?

**Comment by vsamy** [comment]
The copy/paste when having multicursors.

**Comment by Bill-Stewart** [comment]
What behavior were you expecting?

**Comment by vsamy** [comment]
Ok let's get back from zero.

The aim is to copy/paste multiple lines at the same time.
For example if i want to cut line 10 to 14 and paste it in another file.
You suggested to use ctrl+i to get the 5 lines and paste it. It works but when pasting it it does not behaves like a ctrl+x/ctrl+v on one line. Typically when doing it on one line, it pastes over the current cursor line not at the cursor position.
When getting multiline cursors (shift+alt+(down/up/clic)) and copying it (ctrl+c). It does paste (ctrl+v) over the current cursor but the lines are blank lines (as my first comment's gif shows).

Note for me, shift+alt+down does not behaves the same on windows and ubuntu (is it just me ?).

**Comment by Bill-Stewart** [comment]
I am not sure I understand. The `expandLineSelection` (default <kbd>ctrl</kbd>+<kbd>i</kbd>) command selects all entire lines where there are cursors or where there is a current selection. If you want paste to replace lines, then select the lines you want to replace, then paste. (That is, paste will replace any selected text.)

**Comment by vsamy** [comment]
The aim is not to replace lines but rather add the copied lines to another location.
Also when having multicursors and doing a ctrl+i then a ctrl+x leaves blank lines which needs to be deleted.

Im just saying that having multicursors and doing a ctrl+x/ctrl+v should work the same (but for several lines) as doing it with one cursor.

**Comment by Bill-Stewart** [comment]
OK, I think I understand. If you use multiple cursors and use `expandLineSelection` and then cut or delete, then yes it leaves blank lines. What you are saying: If there are multiple cursors and entire lines are selected using `expandLineSelection`, then cut or delete should delete the lines rather than leaving them empty. Is this correct?

**Comment by vsamy** [comment]
From what i understood there are two problems:

When using `expandLineSelection`:
 - ctrl+x: leaves blank lines which needs to be deleted afterwards
 - ctrl+v: Paste works fine

When **not** using `expandLineSelection` (only get multiple cursors by doing shift+alt+down/up):
 - ctrl+x: Works fine. Does not leave blank lines.
 - ctrl+v: Paste is bad. Paste blank lines instead of the text cut before.

**Comment by Bill-Stewart** [comment]
For first use case with `expandLineSelection`: Yes, the cut leaves a blank line because the final newline is not selected when you use `expandLineSelection` (you can observe this by looking carefully at the selection). You can work around it this by pressing <kbd>shift<kbd>+</kbd>right</kbd> after the `expandLineSelection` command. It is a good feature request to say "we would like `expandLineSelection` to include the final newline".

I think the answer in your second use case is not to expect that selecting only ends of lines will work for copy/cut entire lines. The editor's behavior in this case is possibly a bug, but you don't need multiple cursors to select/copy/cut entire lines.

**Comment by vsamy** [comment]
"you don't need multiple cursors to select/copy/cut entire lines". True enough. 
It is just it would much faster to copy/cut/paste this way (only one command to get all the lines). The first option demands more to do :)

**Comment by Bill-Stewart** [comment]
There are a couple of extensions that may provide the "select entire lines" feature you are looking for?

https://marketplace.visualstudio.com/items?itemName=bigous.vscode-multi-line-tricks

https://marketplace.visualstudio.com/items?itemName=andreaskian.vscode-select-line

**Comment by usernamehw** [comment]
But ... but ... this is unexpected. Look how it is done in Sublime Text or Atom:

![sublime](https://user-images.githubusercontent.com/9638156/30665897-4b49ba14-9e5b-11e7-9c7e-01199c38bb1d.gif) ![atom](https://user-images.githubusercontent.com/9638156/30665887-43e2ecaa-9e5b-11e7-9b52-cd73f8a45724.gif)

And vscode just swallows your multi-line targets:
![vscode](https://user-images.githubusercontent.com/9638156/30666054-cf2cd9ce-9e5b-11e7-85ba-d62596f22d2c.gif)

As I see it can be done by `expandLineSelection` and then cut/copy.
![newvidvscode](https://user-images.githubusercontent.com/9638156/30666800-26ea26ba-9e5e-11e7-9b7c-10c0e3765cc6.gif)

So why it isn't the default behavior?

**Comment by Bill-Stewart** [comment]
I have disabled `editor.emptySelectionClipboard`, so when I select only end-of-lines the "cut" action does nothing. This seems a bit odd, because if I press the <kbd>delete</kbd> key, vscode joins the lines (this is expected). When `editor.emptySelectionClipboard` is enabled, the behavior is different. Interesting.
