### ISSUE TITLE
Provided default build task doesn't do the thing right

### ISSUE THREAD

**Issue by hjs0410hc** [microsoft/vscode#110292]
Issue Type: <b>Bug</b>

argument was given like this. 			
"args": [
				"-g",
				"${file}",
				"-o",
				"${fileDirname}\\${fileBasenameNoExtension}.exe"
			],
(this is default, no touched)

this do not result "${fileDirname}\\${fileBasenameNoExtension}.exe"
but "${workspaceFolder}\\${fileBasenameNoExtension}.exe"
so provided default launch task does not work because it launches "${fileDirname}\\${fileBasenameNoExtension}.exe".

VS Code version: Code 1.51.0 (fcac248b077b55bae4ba5bab613fd6e9156c2f0c, 2020-11-05T18:18:23.642Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600 6-Core Processor               (12 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.95GB (12.08GB free)|
|Process Argv|--crash-reporter-id f63c287b-e30c-4c33-b6ce-9d726aa3fdfd|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
doxdocgen|csc|1.1.0
vscode-pull-request-github|Git|0.21.0
better-cpp-syntax|jef|1.15.5
python|ms-|2020.10.332292344
remote-containers|ms-|0.148.0
remote-ssh|ms-|0.55.0
remote-ssh-edit|ms-|0.55.0
cpptools|ms-|1.1.1
cpptools-extension-pack|ms-|1.0.0
vsliveshare|ms-|1.0.3121
vsliveshare-audio|ms-|0.1.91
vsonline|ms-|1.0.3075

(1 theme extensions excluded)

</details>

**Comment by sean-mcmanus** [comment]
This is bug microsoft/vscode-cpptools#6386 with the C/C++ extension -- we're looking at shipping a patch update tomorrow.

@alexr00 Could something be done to inform us when users report bugs with our extension? Maybe the bot could be configured to send us an email or some notification?

**Comment by alexr00** [comment]
@sean-mcmanus The current idea is that the user who filled the issue here will go and make in issue in the right repo, but I'd guess that doesn't always work.

@JacksonKearl is it possible to add a new feature for this to the bot? It would be great to be able to do a "/causedByExtension cpp", then the bot maps cpp to an email address or a repo and sends an email or creates an issue. Or we could do "/causedByExtension microsoft/vscode-cpptools" if the full repo is needed.

**Comment by sean-mcmanus** [comment]
@alexr00 Yeah, I didn't see any of the VS Code users report the issue to us (I agree that seems unusual and I don't know why they wouldn't), and most of the user reports were in the VS Code repo, so it took us longer to realize the bug was a high hitter and needed a patch update.

@JacksonKearl Yeah, a ping to c_cpp_support@microsoft.com would work for us -- that's set in our package.json bug.email field: https://github.com/microsoft/vscode-cpptools/blob/master/Extension/package.json#L18 . Or maybe the bot could leverage GitHub's "transfer issue" feature if we add the bot as a contributor to our repo.

**Comment by hjs0410hc** [comment]
This bug report was directly written by VS Code 'Report Issue' feature and I expect many users to disagree to write another one in other place again. (or don't know where they should go)

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.1.2
