### ISSUE TITLE
Support to start multiple debug sessions from a single launch config

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#110226]
Today VS Code prohibits (silently) launching multiple debug sessions from a single launch config.

I suggest that we improve this obscure behavior in the following way:
when trying to launch a launch config a second time an alert is shown explaining that a debug session is already running and provides an option to launch another session under a different name, e.g. "program" -> "program (2)" or to cancel the attempt.

**Comment by isidorn** [comment]
I agree this could be improved. Do you think we should simply add these "Launch anyway" button in the notification? Or would you expect a modal dialog? Or something else?

**Comment by weinand** [comment]
@isidorn good question. Initially I thought a modal dialog would be ok because the situation is rare and users should have the problem "right in their face".
But maybe a notification would be less intrusive.
On the other hand: the run button next to the debug down is very far away from the notification (opposite corner). Do users realise that the notification explains why pressing the run button has no effect?
So I do not really know...

"Launch anyway" is a good action text for both cases.

**Comment by isidorn** [comment]
I started thinking about this and some thoughts:
* Initialy we had this error to prevent users from creating multiple sessions on accident by double click
* once debugging is started `F5` is taken over by the `Continue` action
* we now disable the Start action while a session is `initialising`

Due to the above, I think it is quite hard for the user to accidently get into this state. He has to click two times on the action in the Debug Viewlet, but in correct time intervals (since while initialising he would not be able to do that).

And due to that, I suggest that we simply start a new session automatically and give it a different name `2`.
So no prompts to start. Only if we hear feedback from users that they end up in this state by accident we can add a prompt.

Let me know what you think.
fyi @connor4312

**Comment by connor4312** [comment]
Sounds good to me. I know at some point I'll accidentally start a duplicate session if I have multiple launch configs and forget to switch, but the impact of this is minor and easily fixed by stopping the new sesion.

**Comment by weinand** [comment]
@isidorn yep, let's try this.

**Comment by isidorn** [comment]
I have pushed a first version of this. Try it out and let me know how it works for you.
I just played with it and seems to work just fine.
