### ISSUE TITLE
Change Open file icon in Git Source Control view

### ISSUE THREAD

**Issue by peterpoliwoda** [microsoft/vscode#110240]
Let me describe the problem I'm having, albeit trivial but quite confusing. I find the Open File arrow very confusing due to its close resemblance to the Discard Changes icon. The arrow on the Open file as in the below screenshot looks just like the arrow and in my opinion describes the action of reverting the file even better than the actual reverting icon itself. I've been using VSCode for years now and I thought I'll get used to this but as of now I still can't handle it and need to double check every time by hovering over the icon to make sure I am opening a file and not reverting it every single time. Could you please look into this? I know it's a trivial change but in reality it has serious implications if people delete their changes by accident when all they wanted to do is open a source file. I attached a suggestion which might perhaps solve this by literally just removing the arrow from the icon.

This way we would know:
**File icon** -> means **Open file** 
**Twisty Arrow icon** -> means **Revert**

I think at some stage earlier this used to be the case at the very beginning with a full bodied icon not an outilne. A return to that would be great.

**Change the current Icon with an arrow like today:**
![image](https://user-images.githubusercontent.com/14016749/98562511-0e9abb80-22a2-11eb-9765-8c958fb85a87.png)

**Into this**

Into a very similar yet arrow-less icon just with a file so that it doesn't confuse:
![image](https://user-images.githubusercontent.com/14016749/98563383-05f6b500-22a3-11eb-97e8-3261f5013789.png)

**Comment by peterpoliwoda** [comment]
Hey @misolori what do you think? Doable?

**Comment by misolori** [comment]
Thanks for the feedback! This is the first time I've heard of someone confusing the discard and go to actions. Just so we're clear, clicking on the discard icon still opens a confirmation dialog, so this revert isn't a single click action:

<img width="600" src="https://user-images.githubusercontent.com/35271042/98569286-fb1e2f00-2266-11eb-8072-dcf7a960a194.png">

Secondly, we've had this icon for a very long time so I would be much more concerned about breaking existing muscle memory and association:

<img width="600" src="https://user-images.githubusercontent.com/35271042/98570265-1b022280-2268-11eb-8880-3f34b7311189.png">


Everyone has different preferences when it comes to icons and we know not everyone will like the ones we chose. That's why we created https://github.com/microsoft/vscode/issues/92791 so that you can customize any icon to fit your preference. Please upvote that issue as I will be closing this as `as-designed`.

**Comment by peterpoliwoda** [comment]
Yeah, but you see before one of them was straight and the other was round which somehow worked. The current one ever since it was changed is confusing and I never trust pressing it and I do use it enough 🙂. I don't know something for me just doesn't click. Thanks for answering.
