### ISSUE TITLE
Feature request: Clone repository option on welcome page

### ISSUE THREAD

**Issue by sana-ajani** [microsoft/vscode#110333]
Since we've added "clone repository" as an action in the file explorer of an empty workspace, can we add that to the start page? We could try this as an experiment and see if folks notice it/click on it more than the other options. 

![image](https://user-images.githubusercontent.com/9721254/98711590-29793880-2353-11eb-8329-ee2d481c1299.png)

**Comment by gjsjohnmurray** [comment]
Related to this, I hope https://github.com/microsoft/vscode/pull/105823#issuecomment-700921355 will also get merged.

**Comment by sana-ajani** [comment]
fyi @misolori @JacksonKearl

**Comment by misolori** [comment]
My main concern here is that that list is starting to get long and adds visual clutter.

**Comment by chrmarti** [comment]
We had that before and didn't see much engagement. We eventually replaced it with `Add workspace folder...` to improve discoverability of multi-root workspaces. We didn't add to the list to keep the number of entries down, more than 3 entries seem hard to see at a single glance (e.g., compare with the sections below that).

**Comment by burkeholland** [comment]
The "Add workspace folder..." option feels awkward to me as a "Start" point. That seems like something you would do after you got started. My hypothesis is that people who are using that menu are genuinely new to the editor and probably don't even know what a "Workspace" is.

All to say - given what @sana-ajani has seen in her interviews, could we propose replacing the "Add workspace folder" with "Clone a Repository"?

**Comment by misolori** [comment]
"Add workspace folder" is similar to opening a folder (both are workspaces). I imagine we added this to increase discoverability but I'd be curious to see the telemetry/usage on this item (you can still do this from the command palette). I'd be in favor of appending clone to open folder like:

> [Open a folder...]() or [clone a repository...]()

**Comment by chrmarti** [comment]
Haven't checked telemetry, but I'd expect engagement to be low. I like the suggestion, should we spell out 'repository'?
![image](https://user-images.githubusercontent.com/9205389/99380702-96984b00-28ca-11eb-93f3-c26083166667.png)

**Comment by gjsjohnmurray** [comment]
Related to this, since the arrival of the viewsWelcome contribution point I think it would be good for a "nothing open" startup to reveal the Explorer alongside the Welcome page. That way, "getting started" options and text contributed by extensions will get seen. For example,

![image](https://user-images.githubusercontent.com/6726799/99552717-3df1ac80-29b5-11eb-9dc8-c5f2984ef5c1.png)

This also deals with the issue that the built-in Git extension's "Clone Repository" command doesn't become available until that extension has completed activation. On a slow enough system you can see this on the Explorer view in the way the command button doesn't appear immediately. Can the new "clone repository..." link in the welcome page have a when-clause to provide the same protection against it being used when invalid? For example, what happens on environments where another SCM is used and the built-in Git has been disabled?

**Comment by misolori** [comment]
We have separate plans for getting started experiences (see https://github.com/microsoft/vscode/issues/106717). Those welcome views are there for when the user is exploring and doesn't know they haven't opened a folder. I don't think we'd want to show this as it can get overloaded very quickly (your screenshot is a good example of this).

**Comment by chrmarti** [comment]
This is in insiders now. Closing. Let me know if anything needs an update.
