### ISSUE TITLE
VS Code crashes frequently while typing in a PHP file. 

### ISSUE THREAD

**Issue by swimmernewman** [Microsoft/vscode#11041]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 10.0.10586

I have a Laravel PHP project that I am editing with Visual Studio Code. It will work fine for hours, and then it will crash a dozen times in a row while I am trying to type code in a PHP file. I don't have any reliable steps as there doesn't seem to be any rhyme or reason to when I see this behavior.  I am just typing.  I have tried closing all VS Code processes and rebooting my computer. Doesn't seem to help.

Here is the error message. 
![image](https://cloud.githubusercontent.com/assets/5430691/18024126/46f9feb4-6bd1-11e6-8b17-67bc73aadfc3.png)

Any suggestions welcome.

**Comment by sandy081** [comment]
@lgreenlee Very sorry to hear that VS Code is crashing. In order to know the root cause for it would you let us know

- How big is the project?
- Is it a Git repository
- Do you have a special setup?

When this happens would you be able to run a CPU profile from the developer tools (help > toggle developer tools) to see where we spend so much time?

Also, did this not happen with the previous release?

And finally, since this might be related to an extension, does it reproduce when you run with extensions disabled (code --disable-extensions from the command line)?

**Comment by swimmernewman** [comment]
@sandy081 Thanks for the response and sorry for the delay. The problem seemed to be related to an extension. I was using Crane - PHP Intellisense by Hvy Industries, and HTML Snippets by Mohamed Abusaid. I uninstalled both a few days ago and since then it has not been crashing. Just last night I reinstalled Crane - PHP Intellisense and am waiting to see if it starts happening again. 

Just for completeness, the project is a GIT project hosted in GitLab and it looks like it is only 470KB in size. As for a special setup, I have a LAMP setup that is serving the public folder in my Laravel project, but that shouldn't affect VS Code I wouldn't think. This is my first experience with VS Code so I don't know if it happened in previous releases.

If it starts happening again, I will get a CPU profile and either reopen this issue or submit an issue to the extension maintainers. I think for now I can close this issue as signs seem to point to this being an extension issue.

Cheers!
