### ISSUE TITLE
Support --diff parameter with reading from stdin

### ISSUE THREAD

**Issue by septatrix** [microsoft/vscode#110426]
Issue Type: <b>Feature Request</b>

Calling `cat /some/file | code --diff /some/other/file -` simply opens `/some/other/file` instead of generating a diff between its content and stdin. Obviously one would not cat the stdin but the point still holds and generating an intermediate file is not always desired nor possible.

VS Code version: Code 1.51.0 (fcac248b077b55bae4ba5bab613fd6e9156c2f0c, 2020-11-05T18:16:10.374Z)
OS version: Linux x64 5.8.0-26-generic

**Comment by bpasero** [comment]
I cannot recall why I added this check that prevents reading from stdin when file paths are provided:

https://github.com/microsoft/vscode/blob/b813399093b699c719d33bfcb419639dbbc79a7d/src/vs/code/node/cli.ts#L160

Removing it seems to allow to diff properly.

//cc @aeschli since I saw you touched this code recently too, probably for remote support.
