### ISSUE TITLE
Integrated Terminal opens to automatically scroll few lines and prompt is invisible

### ISSUE THREAD

**Issue by paritosh149** [microsoft/vscode#110434]
Issue Type: <b>Bug</b>

1. Launch Integrated Terminal, (the issue is reproducable for both PowerShell and cmd.exe.)

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz (4 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (3.90GB free)|
|Process Argv|--crash-reporter-id 07176252-0d46-44ab-8953-bcbbaafb357a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
atlascode|atl|2.8.4
rest-client|hum|0.24.4
java|red|0.70.0
vscode-yaml|red|0.12.0
LiveServer|rit|5.6.1
sonarlint-vscode|Son|1.18.0
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.29.0
vscode-java-pack|vsc|0.10.0

</details>

**Comment by meganrogge** [comment]
Please provide a [a gif](https://gifcap.dev/) illustrating the problem. See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more general info on how to report actionable terminal issues.
/label "needs more info" integrated-terminal

**Comment by Zjl37** [comment]
I'm also running into this bug on my Windows 10 with and without all the extensions disabled.

![a a gif](https://i.loli.net/2020/11/13/lDEJMkiOjqQYsha.gif)

Note that my VSCode version and OS version are exactly the same as paritosh149.

It seems that the bug has nothing to do with the recent release since I often encounter it.

**Comment by meganrogge** [comment]
This looks like an issue with our old terminal backend "winpty", going forward we are focusing our efforts on the new backend "conpty" which is build by the Console team at Microsoft and should fix many issues with the terminal under Windows. You can read more about getting ConPTY [here](https://github.com/Microsoft/vscode/issues/57803#issuecomment-449495423).
/duplicate https://github.com/Microsoft/vscode/issues/45693

**Comment by paritosh149** [comment]
Just tested with settings changed to "terminal.integrated.windowsEnableConpty": false. and the issue persists.

**Comment by Zjl37** [comment]
Oh no, turning this setting off won't help at all. 

If I wasn't wrong, changing this setting to false will cause the newer version of Windows 10 to use the old terminal backend winpty instead of conpty, while on our windows 10 version 1809, there is no conpty support and this setting is ignored, so it is expected that the issue persists.

... and if I wasn't wrong, the vscode team will no longer care about the bug. The only way to fix this is to upgrade the windows 10 to at least versoin 1903, and leave this setting on.

**Comment by meganrogge** [comment]
You are correct @Zjl37 and we do care, but are unable to fix the windows problem.
