### ISSUE TITLE
Too many issues for VSCode XD

### ISSUE THREAD

**Issue by faustinoaq** [Microsoft/vscode#11056]
- VSCode Version: 1.4
- OS Version: Manjaro KDE Linux

Just a comment :-)

![atom-issues](http://i.imgur.com/e8zm0te.png)
![vscode-issues](http://i.imgur.com/va65V76.png)

The six first pages of vscode/issues have issues for the last five days.

We need something like this [Codetriage](https://www.codetriage.com/atom/atom)

Hey guys, VSCode is Open Source! :-)

**Comment by sandy081** [comment]
@faustinoaq Thanks for pointing this out. But, VS Code team does actively triage the incoming issues every day. Take a look at our [issue tracking](https://github.com/Microsoft/vscode/wiki/Issue-Tracking) process. Community (also including you :)) is also helping us in validating or requesting additional info or finding duplicates except assigning owner. Currently our inbox is less than two pages and most of them are waiting for additional info. 

We also retrospect and actively update our process so that we get down the numbers effectively and is working great.

**Comment by faustinoaq** [comment]
@sandy081 Congrats VS Code team!
More than 1900 issues in two months!
*August* ![issues](http://i.imgur.com/va65V76.png)
*October* ![issues](http://i.imgur.com/tdJERhQ.png)
