### ISSUE TITLE
Feature: Terminal button to restart last command

### ISSUE THREAD

**Issue by BeSpunky** [microsoft/vscode#110682]
## What
A small `🔁 Restart last command` button on the terminal's toolbar would be so useful.
Clicking the button will kill the command running in the terminal (if there is one) and automatically re-execute the last one.

## Why
It is sometimes necessary to stop the current command execution and rerun it.
#### Example 1:
A compilation command takes time to complete, during which you change some code and want to recompile.
#### Example 2:
An always-on process like a server (e.g. `ng serve`, `nodemon`, `ng test`) needs a restart to start with new configuration.

## Seriously why
Currently, this is how I execute it:
1. Change something that requires relaunching the last command
2. Focus terminal using keyboard
3. Anxiously press `Ctrl` + `C`
4. Anxiously press `Ctrl` + `C`
5. Anxiously press `Ctrl` + `C`
6. Anxiously press `Ctrl` + `C` faster, repeatedly until the process is stopped.
7. Press `Up` then `Enter`

Great job on VSCode,
Cheers 🥂

**Comment by Tyriar** [comment]
I don't think we should add a feature like this to core because it would be inherently unreliable by design. As you call our that you anxiously await ctrl+c to do something, that's what the feature would do as well (although once should be enough?). Here are some alternatives that would probably work even better though:

- Set up [a task](https://code.visualstudio.com/docs/editor/tasks) for the command, these are essentially processes that VS Code own the lifecycle of so you can actually run a restart task command for example.
- Set up a keybinding to send ctrl+c, up, enter like so:

```json
{
	"key": "ctrl+shift+enter",
	"command": "workbench.action.terminal.sendSequence",
	"when": "terminalFocus",
	"args": { "text": "\u0003\u001b[A\u0013" }
}
```
