### ISSUE TITLE
Node.JS setter & getter methods show in debug window their source instead of values

### ISSUE THREAD

**Issue by 5saviahv** [microsoft/vscode#110780]
- VSCode Version: 1.42.1 (I downgraded to get rid of this bug)
- OS Version: Linux x64 4.15.0-121-generic

Newer VS Code versions when debug node.js programs. Setter & Getter methods show their source code instead of values. It makes very hard to understand what stage program actually is, basically only hand calculator or console.log give you answers.

Steps to Reproduce:

1. Install latest VS Code
2. Write some class with getters / setters
3. Set break point and debug

Getters / Setters show source code instead of values. I have searched information about it from documentation, but cant find 
anything so it has to be some bug (probably).

Does this issue occur when all extensions are disabled?: I dont know

**Comment by connor4312** [comment]
This is the default behavior to avoid any side-effects from automatically calling getter functions (and this matches Chrome's behavior). You can configure this by:

1. Changing your launch `type` to `pwa-node` instead of `node`, or `pwa-chrome` instead of `chrome` so that config resolution uses the new logic
1. Updating the user setting `debug.javascript.autoExpandGetters` to `true`
