### ISSUE TITLE
� in minimap for Chinese characters

### ISSUE THREAD

**Issue by UsernameFull** [microsoft/vscode#110781]
Issue Type: <b>Bug</b>

When I open a document, I notice that the Chinese string in the thumbnail is displayed incorrectly, it looks like '��',I think it's a bug

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.17134

**Comment by yume-chan** [comment]
I believe the "thumbnail" refers to the minimap (screenshot taken with `"editor.minimap.scale": 3`, the minimap doesn't zoom with `window.zoomLevel` or `workbench.action.zoomIn`)

![image](https://user-images.githubusercontent.com/1330321/99369111-fc9ac780-28f6-11eb-816a-803fbcd83157.png)

**Comment by yume-chan** [comment]
Looks like it's by design in #82265 because drawing every character can be expensive.

However, in worst case, a non-English text file can have nothing but question marks and it's very noticeable. @alexdima @Tyriar 

![image](https://user-images.githubusercontent.com/1330321/135700130-fcf97f4d-311d-42fc-a09d-575d2f5babbe.png)
