### ISSUE TITLE
Guide users to set user.name and/or user.email if missing from git config

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#110880]

**Comment by rzhao271** [comment]
Adding verification-steps-needed since I'm not sure what the new behaviour should be.

Firstly, I was able to make a commit with a name but no email. GitHub allows this by writing `name <>` instead of `name <someemail>` in the log.

When both were missing, I remember getting an error, along with an option to view the log, where I can then see the "missing name" message.

**Comment by eamodio** [comment]
Yeah, you should get the following:
![image](https://user-images.githubusercontent.com/641685/100963146-c151e880-34f3-11eb-91f3-1096e570855c.png)

If either `user.name` or `user.email` is missing from your git configuration.
