### ISSUE TITLE
Use a keyboard icon for the add/configure keybinding rather than the gear

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#110976]
I LOVE the new Configure keybinding option in the command palette, but I don't think the icon is quite right.

![image](https://user-images.githubusercontent.com/641685/99717753-d6e8fc00-2a77-11eb-9065-a49460628175.png)

Maybe use the keyboard icon?

![image](https://user-images.githubusercontent.com/641685/99717691-bc168780-2a77-11eb-8579-01895a11e3d7.png)

Also, I think it would be nice if the command changed its tooltip between _Add Keybinding_ or _Configure Keybinding_ depending on if there was an existing keybinding or not -- just add more clarity and polish imo.

/cc @misolori

**Comment by misolori** [comment]
I think we use the same gear icon in settings:

![image](https://user-images.githubusercontent.com/35271042/99730093-bec1ae80-2a70-11eb-819b-f0e35fc6f370.png)

I think because there's already a keyboard icon in the keybindings editor (record keys), people might get confused when they land there and then have to know which icon/action to use:

![image](https://user-images.githubusercontent.com/35271042/99730270-021c1d00-2a71-11eb-95a6-e9eb5ce949aa.png)

**Comment by sandy081** [comment]
We use gear icon at many places to configure (also in tasks menu, extensions etc). So it is consistent with others. 

Also `Configure` goes with the gear icon.
