### ISSUE TITLE
Invalid text selection with two @ symbols

### ISSUE THREAD

**Issue by mrmlnc** [Microsoft/vscode#11099]
- VSCode Version: 1.4.0 + 1.5.0 (92d3324e3d05a6d2b765c08651d89e9ec1d19f4c)
- OS Version: Windows 10 redstone 1

Steps to Reproduce:

  1. Create document with any syntax.
  2. Write: `<p>@@</p>`
  3. Double-click on `@@`

![2016-08-29_15-01-07](https://cloud.githubusercontent.com/assets/7034281/18050806/6f4b2ecc-6df9-11e6-92c1-f6adf4a10e09.gif)

P.S.: Sorry if this issue already exists. I tried to use search, but nothing found.

**Comment by alexandrudima** [comment]
This is sort of by design. Here you double click on a word separator (`@`) and the current logic for double clicking when the target is a word separator is to select all surrounding word separators.

You can configure this via `editor.wordSeparators`. For example, removing `@` from the word separators: `"editor.wordSeparators": "`~!#$%^&*()-=+[{]}\\|;:'\",.<>/?"`:

![wordseparators](https://cloud.githubusercontent.com/assets/5047891/18354244/2188b5e4-75e5-11e6-99f9-34fd267f11c9.gif)
