### ISSUE TITLE
Can't type Polish characters in editor

### ISSUE THREAD

**Issue by PawelGIX** [Microsoft/vscode#11090]
- VSCode Version: 1.4.0 (1.4.0)
- OS Version: MacOS 10.10.5 (14F1808

Steps to reproduce: 

1. Add Polish Pro keyboard in System Preferences and try type in editor

2. ALT + z 
3. ALT + c 
4. ALT + n 

Expected results:
2. ż
3. ć
4. ń

**Comment by alexandrudima** [comment]
@PawelGIX Did you install any extensions? Are you perhaps pressing `AltGr`? What happens when you type the same key combination in the `Define keybinding widget` (`Preferences` > `Keyboard Shortcuts`):

![image](https://cloud.githubusercontent.com/assets/5047891/18050864/6cb0f3ac-6df1-11e6-9fda-4513bb3f34a5.png)

You can then search for the displayed string in the default keybindings (in the left) and identify the bad keybinding.

**Comment by PawelGIX** [comment]
@alexandrudima
Thanks. That was default keybindings. I just override it with empty command like this:
```
{
    "key": "alt+c",
    "command": "",
    "when": "editorTextFocus"
}
```
