### ISSUE TITLE
Web: URL trusted prompt can be bypassed

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#110953]
From @LeuisKen

Here is the reproduce screenshot:

![ezgif-7-c575d3262b01](https://user-images.githubusercontent.com/7701575/99519716-2e7e5d80-29cd-11eb-9881-4ef2a5862a9e.gif)

1. Open VS Code Web.
2. Ctrl + shift + p to show all commands.
3. Using `Open URL` command, type `vscode://vscode.git/clone` URL and waiting for the extensionHost start.
4. See that VS Code warning us that it will open the `vscode://vscode.git/clone` URL, just cancel it.
5. Using `Open URL` command again and type `vscode://vscode.git/clone` URL.
6. The URL open directly without any warning.

**Comment by bpasero** [comment]
Looking at the code there is no way that the trust dialog can appear when you use this command because we set `trusted: true` here:

https://github.com/microsoft/vscode/blob/8fcf778ba251131780f2a110d311161f39b97b03/src/vs/workbench/contrib/url/browser/url.contribution.ts#L40-L40

I see no issue here.

**Comment by LeuisKen** [comment]
Let me explain the callstack:

1. At first time, before ExtHost start, `urlService.open(uri, { trusted: true })` is called, that's right;
2. It will go to `AbstractURLService.open` at `src/vs/platform/url/common/urlService.ts`;
3. But at this time, the handlers are like this:
![image](https://user-images.githubusercontent.com/7701575/99786120-10ddff00-2b59-11eb-98fa-3d1a8a141dd5.png)
4. So, we will go into the `ExtensionUrlBootstrapHandler.handleURL` at `src/vs/workbench/services/extensions/browser/extensionUrlHandler.ts`
5. As you can see, we lose the options here, and that's what my pull request try to fix.

**Comment by bpasero** [comment]
@LeuisKen it is very hard for me to follow your steps without having a clear explanation how I can reproduce the actual issue here. Unfortunately I did not write that code originally so I would appreciate a reproducible step by step case that exhibits the issue.

**Comment by LeuisKen** [comment]
I find an easy way to reproduce this issue, add the following code here to the `src/vs/workbench/browser/web.main.ts`:

```diff
// Return API Facade
return instantiationService.invokeFunction(accessor => {
 const commandService = accessor.get(ICommandService);
 const lifecycleService = accessor.get(ILifecycleService);
+ const urlService = accessor.get(IURLService);
+ urlService.open(URI.parse(`${product.urlProtocol}://vscode.git/clone`), { trusted: true });

 return {
  commands: {
   executeCommand: (command, ...args) => commandService.executeCommand(command, ...args)
  },
  shutdown: () => lifecycleService.shutdown()
 };
});
```

And you'll see that `{ trusted: true }` will lose. Feel free to wrap `setTimeout` to the open call to simulate the user behavior.

**Comment by bpasero** [comment]
@LeuisKen I was asking for a reproducible case where I can follow some steps in the UI to eventually reach this bug. 

When I follow your steps this is what happens: a input box appears asking for the URL to clone. I do not get any prompt.

**Comment by LeuisKen** [comment]
Yes, that's because you have a powerful computer and that extension host immediately so you can't reproduce the case. This issue is a race condition issue, you can't see the prompt after extension host starts because the `ExtensionUrlBootstrapHandler` is disposed.
The diff I suggest you to apply to reproduce the case is just for simulate the user behavior on the powerful computer, just for proof of the race condition existing. On a computer which extension host needs some time to start, you could see what my screenshot shows.

**Comment by LeuisKen** [comment]
And, by the way, why we don't cache the options in `ExtensionUrlBootstrapHandler`, just for save some memory?

**Comment by joaomoreno** [comment]
Thanks for the explanation @LeuisKen!

**Comment by joaomoreno** [comment]
Fixed by https://github.com/microsoft/vscode/pull/110725

**Comment by rzhao271** [comment]
@LeuisKen has the issue been resolved for you now?

**Comment by LeuisKen** [comment]
> @LeuisKen has the issue been resolved for you now?

Yes.
