### ISSUE TITLE
The Find/Replace window covers the content

### ISSUE THREAD

**Issue by jkarr** [Microsoft/vscode#11102]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

1.Open a file with lots of content
2.Press Ctrl+F or Ctrl+H and the content underneath the find/replace is hidden

**Comment by cparker4486** [comment]
I think it's important to note that this issue is an _actual_ problem when the content that's being covered is at the very top of a file. In this case you can't scroll up to reveal the hidden content. Your only recourse is to temporarily add empty lines at the top to push the content down.

My preferred fix would be to adopt Sublime Text's implementation: a small horizontal control that slides up from the bottom of the window.

I recognize that my preferred fix completely changes the UI which might be too much to accept for the dev team and some users. (Even though I think it would be a net positive change.) So here are some other possible fixes.

1. Display the dialog in the same place but shrink the content area by a maximum of three lines. Line 1 would visually move down and lines at the bottom of the window would be pushed below the visible area.
2. Move the dialog itself down, up to three lines, if it covers matches. If it _still_ covers matches (on lines 4,5,6) then move the dialog one line at a time when stepping through the matches. Move the dialog progressively downward, up to three lines, when stepping forward. Move the dialog back up, up to three lines, when coming from below the dialog while stepping backward. In other words, push the dialog in the direction the user is moving through the matches.

Let's be creative and find a good solution.

Thank you for your consideration!

**Comment by rebornix** [comment]
Let's track it in https://github.com/Microsoft/vscode/issues/5525 and solve it in May.
