### ISSUE TITLE
Support msdepoy/publishsettings

### ISSUE THREAD

**Issue by jhaisley** [Microsoft/vscode#11105]
VS Code should support MS Deploy & publishsettings files, webmatrix users are directed to VS.Code, and are unable easily work with Azure app services as a result of the lack of support.

**Comment by jon64digital** [comment]
+1

**Comment by PeterWone** [comment]
I tried to set this up myself with the task runner, since pubxml is simply an msbuild script. There is material on Stack Overflow about doing this but changes in VS Code and my own ignorance of the subtleties of both task runner and msbuild prevented me from seeing it through.

But I suspect that anyone who understands both the task runner and msbuild would not find this much of a challenge, so rather than a heavyweight solution how about some up to date guidance?
