### ISSUE TITLE
Selecting run / add configuration downloads .net debugger

### ISSUE THREAD

**Issue by metaflow** [microsoft/vscode#111059]
Issue Type: <b>Bug</b>

I work on an npm application and wanted to add a run configuration. When I clicked "run > add configuration.." VSCode started to download and installed ".net core debugger" in which I have no interest.

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.18363

<details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-npm-script|eg2|0.3.13
vscode-nuget-package-manager|jmr|1.1.6
csharp|ms-|1.23.6
python|ms-|2020.11.371526539
jupyter|ms-|2020.11.372831992
cpptools|ms-|1.1.2
vscode-scss-formatter|sib|2.0.2
vscode-todo-list|thi|1.0.4

</details>

**Comment by weinand** [comment]
When executing the "Add configuration" command VS Code has to activate all your installed debuggers in order to collect their "configurations". Since you have the "csharp" extension installed (which includes the .net core debugger), activation of that extension results in downloading additional components.
If you do not have interest in .net, you might want to disable the csharp extension for your workspace.

Closing issue because the behaviour you are seeing is expected.
