### ISSUE TITLE
Visual Studio-like custom data visualizers

### ISSUE THREAD

**Issue by chopeen** [microsoft/vscode#111105]
Visual Studio allows to extend the debugger with [custom data visualizers](https://docs.microsoft.com/en-us/visualstudio/debugger/create-custom-visualizers-of-data?view=vs-2019) and developing them is trivial. They can display a variable in a manner appropriate to its data type, e.g. picture for a bitmap type, rendered content for a markup language or tree view for a hierarchical data structure.

A similar feature in VS Code would allow - for example - to create a [much-requsted](https://github.com/microsoft/vscode-jupyter/issues/1286) visualizer for pandas DataFrame objects (PyCharm offers [such feature](https://www.jetbrains.com/help/pycharm/viewing-as-array.html#view-as-array)).

Is the **ability to add custom data visualizers** on the roadmap?

**Comment by weinand** [comment]
We did already an investigation of this feature and came to this conclusion:
https://github.com/microsoft/vscode/issues/26234#issuecomment-524269464 

Summary:

- custom object formatters are runtime/debugger specific,
- concrete formatters cannot be shared across languages because they depend on access to the underlying object representation (which is debugger/runtime specific),
- formatters need to be "close" to the debugger/runtime so that they can determine the low-level type of objects.

I suggest to file feature requests against the debug extensions you are interested in.

**Comment by chopeen** [comment]
Thank you @weinand for a detailed explanation! I will analyze the topic deeper over the weekend and post here again if I have further questions.

**Comment by chopeen** [comment]
Thank you for the links! I will read about [Debug Adapter Protocol](https://code.visualstudio.com/blogs/2018/08/07/debug-adapter-protocol-website).
