### ISSUE TITLE
Status bar: focus border pushes status bar up

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#111180]
![recording (2)](https://user-images.githubusercontent.com/900690/99975665-d798cf80-2da2-11eb-9c64-b817d3a12b09.gif)

**Comment by isidorn** [comment]
It does not really push the status bar up, but the focus border get's rendered on the outside of the status bar. Thus you get 1 px more on top and thus the visual effect.
It should be rendered on the inside - however blue on blue will not be visible.

Adding help wanted, maybe @jeanp413 might be interested since he already did some fixes in the status bar - or might your PR already fix this?

**Comment by bpasero** [comment]
I think on Joao's machine I have seen a slight push, but that was windows.

**Comment by jeanp413** [comment]
I've seen this issue with the outline rendering incorrectly before in different parts of the workbench when having a negative `zoomLevel`, for example in the scm input, the settings ui toc, etc
![image](https://user-images.githubusercontent.com/25115070/100059854-be6f3d80-2df9-11eb-9d0c-5cdac7adc240.png) ![image](https://user-images.githubusercontent.com/25115070/100060056-08f0ba00-2dfa-11eb-940e-1f01dd6268c3.png)

Looks like a chromium issue with the fractional pixel width/height of the elements and I don't know if we can do something about it 🤔

**Comment by isidorn** [comment]
@jeanp413 thanks for being smart.

**Comment by isidorn** [comment]
Closing as no action planned
