### ISSUE TITLE
Reopen Editor with breaks --wait behavior

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#111187]
Because _Reopen Editor with_ seems to close the current document, and re-open it again in with the new editor, this break the `--wait` behavior. IMO, switching editors, shouldn't cause the document to be closed/opened nor break `--wait`

FYI, this causes issues for the new GitLens rebase editor, as it relies on the `--wait` behavior.

**Comment by bpasero** [comment]
When we detect `--wait` we install a listener to observe editors closing, e.g. here:

https://github.com/microsoft/vscode/blob/a14600c325fe43a34d57a42695cf1bb6708d2892/src/vs/workbench/electron-sandbox/window.ts#L665-L665

To then delete a wait marker file which the calling side polls on for deletion before returning:

https://github.com/microsoft/vscode/blob/a14600c325fe43a34d57a42695cf1bb6708d2892/src/vs/workbench/electron-sandbox/window.ts#L668-L668

The code for observing editors closing probably needs to be made more clever around the fact that editors can reopen:

https://github.com/microsoft/vscode/blob/eebf8e876ab99688b167b98874ca2b3c17822e4f/src/vs/workbench/browser/editor.ts#L174-L174

Currently we just listen to `onDidCloseEditor` which will fire even for the reopen case. 

Some ideas:
* enrich the `IEditorCloseEvent` to carry a boolean that can be used to figure out if the editor was closed because it was reopened
* instead of reacting to the close event directly, add some debouncing to give the reopen a chance to bring up the new editor

Not a big fan of the debouncing because that solution sounds fragile to me. A property would make more sense to me.

Note that we already have a [`replaced`](https://github.com/microsoft/vscode/blob/903e219ccb8f8a0bccf8ffce33b79cb66bd9a4f4/src/vs/workbench/common/editor.ts#L734-L734) property on `IEditorCloseEvent` which maybe is a bit misleading: it does not tell whether the editor was replaced from a `replaceEditors` call, but rather indicates that the editor was in preview mode and got replaced because another editor was opened. Maybe the property could still be reused though.

**Comment by bpasero** [comment]
Given my recent change in this area, if we were to enrich `EditorCloseContext` with another context for the reopen, we can easily fix this:

https://github.com/microsoft/vscode/blob/cc4ace196cf5482f801b2ac06128bace2906f874/src/vs/workbench/common/editor.ts#L736-L736

**Comment by lramos15** [comment]
> Given my recent change in this area, if we were to enrich `EditorCloseContext` with another context for the reopen, we can easily fix this:
> 
> https://github.com/microsoft/vscode/blob/cc4ace196cf5482f801b2ac06128bace2906f874/src/vs/workbench/common/editor.ts#L736-L736

This sounds like a good solution

**Comment by lramos15** [comment]
Tested this and it seems the `REPLACE` closed context is passed in the wait works properly.
