### ISSUE TITLE
Sandbox: provide a functional logger that does not depend on spdlog in renderer

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#111297]
Today we require `spdlog` from the renderer as native module. It is pretty clear that once we enable `sandbox`, this dependency cannot be met anymore. This issue is to discuss alternatives, some thoughts:
* use shared process for logging (ideal because it would not block the main process)
* just use a file based logger that uses file service (I guess that goes against why `spdlog` was introduced at first)

//cc @deepak1556 @joaomoreno

**Comment by joaomoreno** [comment]
Both approaches would block the JS thread at some point in time, so I don't see a clear winner from that standpoint.

I would prefer the renderer not depend on the shared process for logging since we wouldn't get any rendered logs in case the shared process goes down or doesn't start.

I'd much rather we have a channel implementation of the ILogService which forwards logging to the main process and have that call spdlog.

**Comment by bpasero** [comment]
> in case the shared process goes down or doesn't start.

Isn't that a case that pretty much makes VSCode unusable in many areas? Do we think this actually happens a lot?

Maybe we can try with shared process first always and have a fallback.

**Comment by joaomoreno** [comment]
No, when the shared process doesn't work you basically don't get extension searching/browsing. Everything pretty much works. It doesn't happen a lot, but it does happen.

**Comment by bpasero** [comment]
I think by now we have more things running there, like settings sync. But yeah, you might not notice easily.

I am all for logging from a process that is rock solid but I am worried that this puts more pressure on the main side than needed. In the end this is the process that handles keyboard/mouse input and forwards to the window.

**Comment by joaomoreno** [comment]
Yeah it is definitely a trade-off, but worth in imo... 😕 We should at least give it a try.

**Comment by bpasero** [comment]
@deepak1556 do you have any knowledge about Chrome's logger? I wonder if we could turn this around and let Electron expose such a logger API from Chrome? I am sure they must have something efficient...

**Comment by deepak1556** [comment]
Can you provide some details about how spdlog logging functionality is used ? What are the usages across different process ? Is it just used to log stuff to disk or do we replay it from memory too ?

**Comment by joaomoreno** [comment]
We use it to log as fast as possible to disk, with minimal overhead. We use the async logging API from spdlog which yields asap once logged.

**Comment by sandy081** [comment]
Adding more details. Spdlog is used in following processes and purposes 
- main process for logging 
- shared process for logging 
- renderer process for logging and output channels (core output views like tasks)
- ext host process for logging and output channels of extensions 
- remote server for logging.

**Comment by bpasero** [comment]
To clarify: we can keep using `spdlog` in all processes except for renderer.

**Comment by bpasero** [comment]
@deepak1556 pointed me to an event [`console-message`](https://github.com/electron/electron/blob/9-x-y/docs/api/web-contents.md#event-console-message) that the `electron-main` side could subscribe to log any `console` usage from the renderer via `spdlog`. Since we already seem to be printing any log message to `console`, this could be one potential solution.

However, we would need a strategy to know to which log file to log to. My understanding is that the renderer logs to different output channels. One way of solving this would be to agree on a prefix for any log message depending on the channel, for example:

`[watcher] <message>` would end up in a `watcher.log` file, or `[JSON Language Server] <message>` in a `json_language_server.log` file.

This would even help to tell log mesages apart in dev tools 👍 

@sandy081 besides having support for different log files, is there something missing if we were to use this event and handle it from the main side? We would probably also need to handle complex objects so that their contents are printed as string, otherwise they do not seem to survive.

**Comment by bpasero** [comment]
@joaomoreno 

> I don't understand how that's a better approach than using the main process as the log service implementation for the renderer

It is not better, it is exactly what I am suggesting.

> Why would we pollute the devtools console

Today, everything we log via `ILogService` already "pollutes" the devtools console:

![image](https://user-images.githubusercontent.com/900690/101461121-befbee00-393a-11eb-9feb-85bb7435b881.png)

> at the same time waste cpu cycles on main parsing every log message?
> If we're gonna have the main do any work, it should just create an IPC channel to which renderers can send log messages, 
> and main just forwards them to spdlog.

This IPC channel already exists and is called [`console-message`](https://github.com/electron/electron/blob/9-x-y/docs/api/web-contents.md#event-console-message). I we'd leverage it we don't send the same log messages over twice.

**Comment by joaomoreno** [comment]
@bpasero Got it! I didn't know we automatically sent everything to the devtools console, since we have the output channels.

Your proposal makes sense to me. The only difference I see would be that in `console-message` we're restricted to strings while in our IPC we can send JSONable objects. But I don't think that's a blocker anyway. 👍

**Comment by sandy081** [comment]
I would prefer to use our IPC and log to spdlog & window console from main, so that the message format remains same for each logger (spdlog & console). This will also prevent sending the message twice as we use only our IPC.

**Comment by bpasero** [comment]
@sandy081 are you suggesting to no longer log to devtools? The reason I brought up the `console-message` event is that we already send each message over to `electron-main` because we log to devtools. If we keep doing that, we could avoid a second IPC call with the same data.

**Comment by sandy081** [comment]
Actually not, but ignore my previous comment because I did not think `console-message` is an event. 

I think we might need an IPC channel for spd logger because some render output channels use spdlog logger and we do not log to devtools console in this case. 

Another point is that console.log and spdlogger.log have different formats. So not sure if using the message from `console-message` event might change the format of how it is logged in spdlog, for example logging errors?

It seems we also need to introduce a new message format so that we can interpret the spdlog file. So if I am not wrong, message with this new format will be logged into the console right?

May I know if this `console-message` event captures additional arguments those are passed to log?

**Comment by bpasero** [comment]
> I think we might need an IPC channel for spd logger because some render output channels use spdlog logger and we do not log to devtools console in this case.

If that is a requirement, then yes, we cannot rely on `console-message` alone.

> Another point is that console.log and spdlogger.log have different formats. So not sure if using the message from console-message event might change the format of how it is logged in spdlog, for example logging errors?

Yeah, the result on the `main` side will be just `string`. I was logging the `window` object and found `[object object]` on the `main` side. 

> May I know if this console-message event captures additional arguments those are passed to log?

From my testing, they are all captured, but only send over as `thing.toString()` it seems.

> Since we need an IPC channel anyways, how costly it is to use this for all spdlog logging?

Probably fine, I was just bringing this up in case we could reuse something here. It might have been a bit too optimistic.

I still think that the shared process is OK for this because it will eventually be our main backend process for everything (e.g. file system access), so it will need to be 100% reliable and VSCode workbench would not run if that process goes down.

**Comment by sandy081** [comment]
No hard opinions between shared vs main process, but having a separate IPC would be good.

**Comment by joaomoreno** [comment]
> No hard opinions between shared vs main process,

Again, I am strongly opposed from using the shared process. Code should still be able to run when [the](https://github.com/microsoft/vscode/issues/112115) [shared](https://github.com/microsoft/vscode/issues/111266) [process](https://github.com/microsoft/vscode/issues/103295) [malfunctions](https://github.com/microsoft/vscode/issues/110993) and all critical components should run as well. I argue that logging is an absolutely critical component, since it's the best tool we have to figure out problems when things don't work correctly.
