### ISSUE TITLE
Support for csv/tsv files. Please.

### ISSUE THREAD

**Issue by pcherkasova** [Microsoft/vscode#11123]
- VSCode Version: Version 1.4.0 (1.4.0)
- OS Version: Mac OS

Steps to Reproduce:
1. 
2.

**Comment by alexandrudima** [comment]
To keep the number of issues in our inbox at a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: we look at the number of votes the issue has received and the number of duplicate issues filed. Thank you for your time and understanding.

If you disagree and feel that this issue is crucial: we're happy to listen and to reconsider.
