### ISSUE TITLE
can not connect to the Extension Marketplace 

### ISSUE THREAD

**Issue by alazyfatcat** [microsoft/vscode#111277]
- VSCode Version:
- OS Version:

Steps to Reproduce:
![image](https://user-images.githubusercontent.com/59616597/100197718-b3cfa980-2ec8-11eb-9bf6-6ef5604128e3.png)

1. Vscode keeps saying that "We can not connect to the Extension Marketplace at this time, please try again later."
2. I tried every tips on google. change dns, completely uninstall and then re-install and still. the same message shows up. 
3. When I try install extension from https://code.visualstudio.com/docs/editor/extension-gallery it says XHR failed
![image](https://user-images.githubusercontent.com/59616597/100198424-d4e4ca00-2ec9-11eb-8c61-eabb3ba2f9c1.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by gjsjohnmurray** [comment]
Please review https://github.com/microsoft/vscode/issues/111266#issuecomment-733478842 and post the information @sandy081  asks for.

**Comment by sandy081** [comment]
Please follow these steps

- Help -> Toggle Developer Tools -> Network
- Then check for any network failed requests while browsing and installing the extensions if found all requests fails then its probably a proxy or DNS issue at your end.
- To confirm its a DNS issue check if you can access this page https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default, if you cannot please try configuring your DNS like pointing to 1.1.1.1 as suggested here? https://1.1.1.1/dns/. Otherwise please contact your network administrator.
- If it is not a network issue, please share the logs from the following locations
    - Help -> Toggle Developer Tools -> Console
    - Help -> Toggle Developer Tools -> Network (any failed requests)
    - View -> Command Pallette... -> Toggle Shared Process -> Console
    - View -> Open View… -> Log (Shared)
    - View -> Open View… -> Log (Window)

Also please check if you are behind any proxy settings?

**Comment by alazyfatcat** [comment]
![image](https://user-images.githubusercontent.com/59616597/100265199-e788ee80-2f1d-11eb-916a-cdf462d28c0b.png)
![image](https://user-images.githubusercontent.com/59616597/100265223-f374b080-2f1d-11eb-99c5-628a5d55ae8f.png)
![image](https://user-images.githubusercontent.com/59616597/100265323-1737f680-2f1e-11eb-88d6-db965d654eda.png)
![image](https://user-images.githubusercontent.com/59616597/100265437-3f275a00-2f1e-11eb-95bb-4ab060eaf065.png)
I changed DNS as https://1.1.1.1/dns/ suggested and it is still the same. I completely removed vs code and then reinstalled it. It is still the same

**Comment by sandy081** [comment]
Seems proxy issues

**Comment by chrmarti** [comment]
@alazyfatcat Are you behind a network proxy?

@deepak1556 Are we seeing more of these recently?

**Comment by chrmarti** [comment]
Closing due to lack of information. Maybe related to https://github.com/microsoft/vscode/issues/34385.
