### ISSUE TITLE
Environment Resolution

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#111246]
With the latest insider I see the double notification warning and error for my remote SSH box as well as for my local machine. 

![image](https://user-images.githubusercontent.com/4674940/100141522-6b23dc00-2e47-11eb-856c-45e0467f5c48.png)

It's unclear what the error actually means for me as a user. The Learn More link only talks about the warning.  Also, in my case: 
- On the remote I have a vanilla `.bashrc` as it comes when creating a new account on ubuntu + nvm.
- On the local machine the script mostly comes from conda. 

In both cases those are default configurations for many users.  What are we - the users - supposed to do?

**Comment by bpasero** [comment]
Connecting to a remote or not has no impact, because in order to resolve the shell environment we spawn a local shell and try to get the environment:

https://github.com/microsoft/vscode/blob/52098eaeb028e123b3f8af1d4a3d64df6db528be/src/vs/code/node/shellEnv.ts#L81-L85

I have updated https://github.com/microsoft/vscode/wiki/Resolving-Shell-Environment-is-Slow to talk in greater detail about the notifications and how to resolve this. 

The only sort of "bug" I see here is that arguably showing both notifications is not very helpful. Otherwise I really don't see us fixing this unless https://github.com/microsoft/vscode/issues/108804 is addressed. 

I am fine disabling these notifications again as I am also not entirely sure asking our users to comment out shell configuration is clever, given that there is very likely a reason for it?

@joaomoreno thoughts?

**Comment by joaomoreno** [comment]
Good edits on the wiki 👍 

I think we should definitely try to only show one notification, at most. If it's slow (3-10s), a warning. If it times out (>10s), an error. Would that be possible, @bpasero? Another though is that if it's only slow, we could consider placing a status bar indicator instead of a notification.

**Comment by bpasero** [comment]
Yeah let me try to reduce to just one.
