### ISSUE TITLE
Setting sync is destructive

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#111291]
I have just setup a new computer and enabled settings sync. Instead of accepting UX customizations, like visible views etc, the new computer overrides the standard config onto all machines

sync log from the new computer: 
[new.txt](https://github.com/microsoft/vscode/files/5596073/new.txt)

sync log form the old computer: 
[old.txt](https://github.com/microsoft/vscode/files/5596075/old.txt)

**Comment by sandy081** [comment]
Caused by - https://github.com/microsoft/vscode/commit/f4b9edc5876dad1471b35542265a8c9b4582db09

This happened because, I recently changed the global state merge strategy to take local value always when there is a conflict. Hence sync is taking local value on the machine during set up and syncing it on other machines. 

Made merging while conflict smarter - local value is taken only if the machine was already synced before, otherwise remote value is taken. So in case of set up, remote value always wins as before.

**Comment by sandy081** [comment]
To verify:

- Set up Settings Sync on Machine 1 - Hide some activity bar icons, views & status bar entries and sync the state
- On machine 2, Open VS Code and Turn on Sync 
- Make sure UI state from Machine 1 is synced on to Machine 2.
