### ISSUE TITLE
Git API call getRepository(uri) returns null on any Uri that is not opened in the workspace

### ISSUE THREAD

**Issue by nturinski** [microsoft/vscode#111210]
- VSCode Version: 1.52.0-insider
- OS Version:

Steps to Reproduce:

1. Activate and get Git API export
2. Call `git.getRepository(uri)` with a URI that is not in your current workspace
3. `getRepository` returns null.  However, if that workspace _is_ in your workspace, it will return the repo
4. If you call `git.init(uri)` on the URI that is not in your workspace, it will "initialize" the repo, but in actuality, it just recognizes that there is a repository there now.  All of the commits and remotes will exist as normal and as far as I can tell, this has no adverse effects on the repository (though if there was no git repo there before, there is now)

Does this issue occur when all extensions are disabled?: Yes

**Comment by eamodio** [comment]
So as far as I can tell this is behaving as designed.

`git.getRepository` only returns repositories that are currently known to the Git extension (which is controlled by its discovery setting `git.autoRepositoryDetection`)

While `git.init` will initialize (create) a new repository at the Uri you provide, and then "open" the repository so that the Git extension will now know about it.

Currently there isn't an api to "open" a repository, but it is something I am considering adding. Is that what you are asking for?

**Comment by nturinski** [comment]
Yeah, I think it would be nice if either `git.getRepository` also opened the repo if it wasn't opened already, or have a separate command that does open the repo.  It'd be really convenient for us to be able to access repositories that aren't currently in the active workspace.

**Comment by eamodio** [comment]
I added a new `openRepository` api. FYI, you can use this as a get/open call -- since if the repo is already known it will return it, otherwise it will "open" it and return it.

**Comment by eamodio** [comment]
To verify you could write an extension to use the git api and call the new `openRepository` method, and see that the repository opens in the SCM view.

Or much more easily verify with GitLens Insiders edition:
- open a folder in VS Code where the repository is nested more than 2 levels deep 1 > 2 > 3 > repo-folder
- observe that no repository shows up in the SCM view
- set `"gitlens.advanced.repositorySearchDepth": 3` and retry
- observe that the repository will show up in the SCM view
