### ISSUE TITLE
Confusing ports view

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#111379]
* create code space for vscode
* open in browser
* also open in vscode desktop

The browser view makes somewhat sense, there is 127.0.0.1 (which I understand is the container) which makes some ports available behind an url. The desktop view is confusing because it says 127.0.0.1:<port> goes to 127.0.0.1<another_port>. By now I have learnt what the UI wants to says but using "127.0.0.1" to talk about the container _and_ my machine is confusing. 

<img width="944" alt="Screenshot 2020-11-26 at 18 36 23" src="https://user-images.githubusercontent.com/1794099/100380131-7f6a0380-3016-11eb-9c59-44d0a53a4d8f.png">

<img width="1288" alt="Screenshot 2020-11-26 at 18 36 25" src="https://user-images.githubusercontent.com/1794099/100380132-809b3080-3016-11eb-9287-a2c7eb92ca07.png">

**Comment by jrieken** [comment]
Attaching a screen capture from my router's port forwarding config. I am not saying it's pretty but the table headers make it pretty clear what is where


<img width="839" alt="Screenshot 2020-11-26 at 14 29 50" src="https://user-images.githubusercontent.com/1794099/100380855-fd7ada00-3017-11eb-901d-a777affaa4b5.png">

**Comment by alexr00** [comment]
It should look more like this:
![image](https://user-images.githubusercontent.com/38270282/100456306-703f9000-30c0-11eb-961f-cfb15ce91f7a.png)

What you are seeing is because of this bug: https://github.com/github/codespaces/issues/1747

**Comment by jrieken** [comment]
idk... looking at the second line it, says `My Server 3000 -> localhost:3000 - /usr/local/bin/node`. Does "/usr/local/bin/node" denote a path on the remote or local machine? If it's remote (which I assume) why isn't it rendered closer to the server part. Also, I assume I am typing the bits after the arrow, like localhost:2000, into my browser/tool. So should that maybe go first?

**Comment by alexr00** [comment]
Hmm. It's a battle between keeping the lines scannable and putting the most immediately actionable info first. I put the remote port first because that is the thing I expect users to look for. You know that the server would be available at 3000 if you were developing locally, so that's what I'd expect you to look for. However, having the thing you need to copy/type/otherwise use first could be more useful. Downside of that though is that then there would be a lot of duplication with (i.e. every line might start with localhost).

**Comment by alexr00** [comment]
Closing since the table view is easier to parse.
