### ISSUE TITLE
Please make the IDE more intuitive to use

### ISSUE THREAD

**Issue by nav9** [microsoft/vscode#111339]
Hi. There's a lot about the intelligent design aspects of VS Code I like, but like many other users, I'm totally lost about how to use it. I watched a video on using the C++ extension, but even after installing a C++ project extension, when I look for options to create a C++ project, I don't see any options. So now I'd have to go back to some tutorial page/video and learn how to do this in VS Code. I had the same issue while wanting to use Python. 
I understand you may have taken certain decisions, perhaps to keep the IDE lightweight, but the JSON files for settings and the total cluelessness that a even an experienced programmer ends up when trying to just create a project, speaks a lot about the IDE's un-intuitiveness (or my inability to grasp the concept you want me to).
At least in my humble opinion, an IDE should take away a lot of the unnecessary steps or the need to hack JSON scripts. When I install a C++ extension, it should do everything that's necessary to provide the user a view for creating a new project, options for building/compiling the project, running and debugging it and menu interfaces for the project settings (instead of JSON). So many IDE's already provide these options that programmers are already familiar with. Why did VS Code try to re-invent the wheel?
I noticed you plan to have an [onboarding experience](https://github.com/microsoft/vscode/issues/106717), but really, it's not onboarding that the user needs. **The IDE needs to be modified/re-designed so that a user can simply look at the options available and start using the IDE intuitively.** I've seen other people (on StackOverflow) also mention their confusion on using the IDE.

**Comment by LiterallyJohnny** [comment]
Not an expert, I am a beginner programmer. I believe you have to add the .[file type] at the end of the file when using VS Code. Let's say I wanted to make a Python file. In order to do this, I would have to name the file `example_name.py`. It would then use the Python extension in VS Code, and activate all of the neat features for Python. I don't know how to do it in C++ though, you would have to find out the one for C++ yourself.

**Comment by egamma** [comment]
@nav9 this this highly valuable feedback thank you. From your comments it sounds like you are developing in C++, therefore please also provide to the C++ extension.

**Comment by nav9** [comment]
@egamma : You are welcome. Perhaps a good way to find out what needs to be improved about the IDE, would be to ask a few programmers who have never used VS Code, to start using it while you observe how they struggle with creating a project. They can be encouraged to tell you what problems they are facing with understanding how to setup a new project etc. I believe this is called "hallway testing". From your mention of "C++ extension", I believe you want me to write to the developers of the C++ extension? I checked, but danielpinto8z (he created the C/C++ Project extension) hasn't mentioned an email id. The other extensions of C++ were created by Microsoft, and I believe this github project belongs to Microsoft anyway.
@LiterallyJohnny : Thanks, but what I'm mentioning is not about the file extension.

**Comment by egamma** [comment]
@nav9 this repository is for VS Code issues, the C++ support is provided by a separate extension that has its own repository for issues. Therefore pls report this issue against the repository of the C++ extension: https://github.com/Microsoft/vscode-cpptools

**Comment by nav9** [comment]
> @nav9 this repository is for VS Code issues, the C++ support is provided by a separate extension that has its own repository for issues. Therefore pls report this issue against the repository of the C++ extension: https://github.com/Microsoft/vscode-cpptools

Thank you. Will do. What I mentioned though, isn't specifically about C++.

**Comment by yume-chan** [comment]
I understand you, however the problem is that, there are so many ways to create a "project" for each language.

For example in C++, different build system, including MSBuild, make, ninja, gyp (I can count these even without being a C++ programmer), and more, all uses different "project" structure.

What the C++ extension does, is essentially created a new, of its own, edit time only, project system, because it's impossible to support each of those build systems. It's useless on its own, because you can't build your project with the extension.

It's same for "creating a new project", which build system do you want to use? Which version? What arguments? There are so many combinations that's simple impossible to cover with a "easy-to-use", "GUI based" operation. If someone managed to do this, I expect the UI will be like this:

![image](https://user-images.githubusercontent.com/1330321/100418354-97e12900-30bd-11eb-8764-986d3fd0a0e8.png)

**Comment by egamma** [comment]
@yume-chan good feedback, but please see my comment above https://github.com/microsoft/vscode/issues/111339#issuecomment-734480449

**Comment by nav9** [comment]
> I understand you, however the problem is that, there are so many ways to create a "project" for each language.
> 
> For example in C++, different build system, including MSBuild, make, ninja, gyp (I can count these even without being a C++ programmer), and more, all uses different "project" structure.
> 
> What the C++ extension does, is essentially created a new, of its own, edit time only, project system, because it's impossible to support each of those build systems. It's useless on its own, because you can't build your project with the extension.
> 
> It's same for "creating a new project"
Sure. But even after I installed the C++ extension, I was clueless on how to proceed. So like I mentioned earlier, y'all could get a few experienced programmers and inexperienced programmers (where both categories have never used VS code). Ask them to try creating a project in any language and note down their questions and reactions.
After that, it could also be possible to create a basic set of guidelines for anyone who creates an extension to follow, so that there would at least be a high-level uniformity and intuitiveness in using the IDE. I know it's easier said than done, and it'd require a lot of thought to figure out the details. But getting user opinions is crucial.

**Comment by nav9** [comment]
The people maintaining the C++ extension mentioned that VS Code is designed to be as such, so there's nothing more for me to say. I apologize for taking up your time.
