### ISSUE TITLE
Ports should be inside sidebar and not panel

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#111402]
I setup once @egamma express app in codespaces and ran it.

I find that ports do not benefit from all the space a panel offers:

![image](https://user-images.githubusercontent.com/900690/100426706-9b5ebb00-3091-11eb-838e-8c43d33fc044.png)

I would put ports closer to where contextual information about the remote target is shown to me. I feel that the list of forwarded ports is a detail and should not deserve such a prominent place. 

As for the "Open in Browser" entry point, I would still allow this from a different entry point like quick pick.

**Comment by alexr00** [comment]
@bpasero, what if there was another view next to the ports view in the panel? That would remove the space problem. Mockup:

![image](https://user-images.githubusercontent.com/38270282/100439721-2fd21900-30a4-11eb-832a-88d49f526240.png)

**Comment by alexr00** [comment]
@bpasero I have added an Open Port in Browser command since this is a fair thing to have.

**Comment by bpasero** [comment]
@alexr00 shouldn't ports be just another node in the tree on the right? at least if we had a different way for the user to discover the "open in browser" command, do we still need ports as standalone view?

And would this kind of machine information be in its own top level view or part of the remote explorer?

**Comment by alexr00** [comment]
A command is not as discoverable as a view, and we want to make forwarded ports discoverable so that users can understand that their work is available even though its not on their local machine.

I have received _a lot_ of feedback that ports do not belong in the remote explorer. The main reason for this is tat the "explorer" part of the remote explorer isn't useful in a remote context. Therefore, we shouldn't put useful and useless information in there together.

I have also gotten feedback that machine information also maybe doesn't belong in the remote explorer for the same reason.

**Comment by bpasero** [comment]
Does that mean we maybe need a new view that puts all the information of the running remote machine together?

**Comment by alexr00** [comment]
Yes, that's what I'm suggesting with https://github.com/microsoft/vscode/issues/111402#issuecomment-734765924

**Comment by bpasero** [comment]
I am fine either way, as long as the top level view name is not "Ports" 👍

**Comment by alexr00** [comment]
Closing since we decided to put the Ports view in the panel.
