### ISSUE TITLE
Hardware Acceleration and (maybe) Big Sur - screen corruption

### ISSUE THREAD

**Issue by flipswitchingmonkey** [microsoft/vscode#111412]
- VSCode Version: 1.51.1
- OS Version:Darwin x64 20.1.0 (Big Sur 11.0.1)

Steps to Reproduce:

1. Just open vscode...

To temporary fix: disable hardware acceleration

This also appears to happen in some Chrome tabs. Thus, I assume it is Chromium related? Only started to happen in the last few days, not immediately after Big Sur update, so probably the issue lies somewhere with Chrome?

Seems to happen mostly with a second screen attached.

![image](https://user-images.githubusercontent.com/6930367/100444799-53995d00-30ac-11eb-8505-fa3ce7b9d958.png)

Does this issue occur when all extensions are disabled?: Yes

--disable-gpu fixes it for the moment

**Comment by IllusionMH** [comment]
/needsMoreInfo

Could you check if this issue is reproducible with Insiders build https://code.visualstudio.com/insiders/?

**Comment by thblt-thlgn** [comment]
Just got the same issue

**Comment by IllusionMH** [comment]
@thblt-thlgn could you please try Insiders build (has latest Electron version) https://code.visualstudio.com/insiders/ and check if its reproducible there ?

**Comment by flipswitchingmonkey** [comment]
At first glance it looks like the insider build may be working! Is it using a different chromium version or something like that?

**Comment by IllusionMH** [comment]
Yes, Stable build should have Electron 9.3 (Chromium 83), while Insiders has 11.0 which comes with Chromium 87.

So it has a great chance that render was fixed in lates 4 versions (I'm on Windows so can't tell for sure).

December 9 Expected release date for stable (this may change), hope that there wouldn't be any blockers for Electron 11.

**Comment by deepak1556** [comment]
Thanks for checking with insiders, we don't plan to release Electron 11 for November stable release since it only got a short time testing in insiders and also it is right before vacation. So instead we will keep Electron 9 for upcoming stable release and update to Electron 11 right after. This will give enough time for insiders testing, as the next-to-next stable release will happen in January 2021.

**Comment by thblt-thlgn** [comment]
I confirm that I also no longer have the issue on the insider version. And more strangely, after rebooting my laptop, VSCode 1.51.1 is working fine again and I cannot reproduce the bug anymore (not sure I should complain about it though)

**Comment by flipswitchingmonkey** [comment]
> I confirm that I also no longer have the issue on the insider version. And more strangely, after rebooting my laptop, VSCode 1.51.1 is working fine again and I cannot reproduce the bug anymore (not sure I should complain about it though)

That happened to me too after a reboot, but it came back soon after. When it did happen, it also happened in some of Chrome's tabs as well, until I disabled hardware acceleration in the browser as well. No other apps affected so far, so it looks like Chromium is involved here somehow.

**Comment by egorgam** [comment]
I have similar nasty behavior with all v8 apps (vscode too) - hardware acceleration is full broken and I see a lot of lags, but there are not graphic artifacts. It happen when I work with with external 2k display, Big Sur cleanly installed on Macbook Pro 16"

**Comment by iAmWillShepherd** [comment]
Any update on this? 

#### I'm experiencing the same issue

<img width="1176" alt="Screen Shot 2021-01-05 at 9 58 23 PM" src="https://user-images.githubusercontent.com/1715082/103727552-24c2b080-4fa1-11eb-9745-633e81524b61.png">

I only see corruption in the _Explorer_ workspace area. This has been a consistent occurrence over this past week.

#### Using VSCode

```
Version: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:30:02.420Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 20.2.0
```

#### On a MacBook Pro

```
MacBook Pro (16-inch, 2019)
AMD Radeon Pro 5500M 8 GB
Intel UHD Graphics 630 1536 MB
```

#### Stranger things
![stranger things](https://user-images.githubusercontent.com/1715082/103728492-cba84c00-4fa3-11eb-8be3-8086d64113a7.gif)

The sudden shift in corruption when resizing the window is surely a bug. This behavior persists after quitting the app and even after restarting the computer. However, it's extremely distracting; I've found that I can skirt around the issue by
* randomly resizing sections in the sidebar and randomly scrolling until things render properly (see ☝🏾) * or turning off my GPU 
* except when switching graphics on **after** VSCode has started by
	1. disabling discrete graphics
	2. starting VSCode
	3. then enabling discrete graphics 

#### My attempts to troubleshoot
* Quit the app
* Restarted computer
* Disconnected the thunderbolt monitor
* **Disabled discrete graphics**

The issue seems to be with discrete graphics. I'm on a 5K monitor with _Automatic graphics switching_ checked; unchecking this results in discrete graphics **always** being used, but I can't use my monitor without discrete graphics; so it seems VSCode will not work reliably with a thunderbolt display connected. 

🤔 

VSCode should render properly regardless of the underlying hardware.

#### FWIW 
* The same bug exists in Discord; it occurs more erratically and isn't
constrained to a specific portion of the UI.
* I have not experienced this bug in Slack.

**Comment by IllusionMH** [comment]
@iAmWillShepherd as was mentioned above Electron 11 should have updated Chromium that contain fix.
You can use Insiders https://code.visualstudio.com/insiders/ in the meantime.

**Comment by rweisse** [comment]
This is still an issue. Visual Studio Code behaves exactly as described by @iAmWillShepherd .

#### Using VSCode
```
Version: 1.53.2
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:45:54.515Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.3.0
```

#### On a MacBook Pro
```
MacBook Pro (16-inch, 2019)
AMD Radeon Pro 5500M 4 GB
Intel UHD Graphics 630 1536 MB
OS: Big Sur 11.2.1
```

My MacBook is connected by Thunderbolt to an external 4K-Screen.

**Comment by deepak1556** [comment]
Can you quit the app and restart with `--disable-gpu-rasterization`

**Comment by rweisse** [comment]
Thx @deepak1556 . After the glitch suddenly appeared I set the setting `"disable-hardware-acceleration": true` in `argv.json`. After restarting Visual Studio Code the problem disappeared. I have now undone the setting and will follow your instruction as soon as the problem occurs again.

**Comment by Ivan0xFF** [comment]
I am also still seeing this issue on the 16-inch MacBook Pro.

`
Version: 1.53.2
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:45:54.515Z (1 wk ago)
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.3.0
`

Only solution is to disable hardware acceleration. Any chance we'll see a fix for this soon?

**Comment by deepak1556** [comment]
@Ivan0xFF the fix needs to be addressed in chromium, currently tracked at https://bugs.chromium.org/p/chromium/issues/detail?id=1068170
