### ISSUE TITLE
Command to clear ALL outputs

### ISSUE THREAD

**Issue by minig0d** [microsoft/vscode#111452]
Currently it doesn't look like there is a working command that clears ALL of the output channels

workbench.output.action.clearOutput only clears the active channel's output so suggesting a new command "workbench.output.action.clearAllOutput" which would clear all output channels at once, (including VSC ones and extension contributed ones).

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog and we might add this in the future. Thanks

fyi @sandy081

**Comment by TonyGravagno** [comment]
Just adding a +1 to a dead request. I have a need for this every day. See screenshot - I do not look forward to going through so many channels (select next channel. something there? clear. repeat) That's a primitive workflow. I want to clear all output channels so that I can get a clear view of current activity after some starting action.

I understand this isn't in the queue for processing. Can someone post here where this data is so that we can clear it by some other means, SQL query, file deletion, etc.? Or should this request for information be in another ticket? Thanks.

![image](https://user-images.githubusercontent.com/499473/182897734-ac6a3ee0-acdf-4a7a-9be2-240007592d02.png)
