### ISSUE TITLE
Ports: consider to distinguish a view for managing ports and a way to launch my app

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#111403]
I setup once @egamma express app in codespaces and ran it.

I see that we have a view for ports that is both to:
- manage ports (remove, public/private, etc)
- launch my app

I feel that we need another way to discover how to launch my app after I started it from the terminal. The notification that appears is very useful in that regard:

![image](https://user-images.githubusercontent.com/900690/100426978-090ae700-3092-11eb-8fa0-45362d37e625.png)

I also find the status bar very good:

![image](https://user-images.githubusercontent.com/900690/100427012-145e1280-3092-11eb-8644-7574e853b907.png)

Maybe we could:
- have one view specifically to manage ports (as today) close to where contextual information about the remote I am connected to is shown
- have another entry point specifically for running my web app in the browser (that does not necessarily talk about "ports")

**Comment by misolori** [comment]
I wonder if when you click on the status bar item we show a quick pick with these two options?

![image](https://user-images.githubusercontent.com/35271042/100650193-67390380-32f8-11eb-8924-1bc09800016a.png)

**Comment by bpasero** [comment]
Yes, that is going towards what I had in mind 👍

**Comment by misolori** [comment]
I believe when you launch an application from the terminal we now open the browser if it launches that (like in a create-react-app) so I don't think this is much of an issue now. We also show a badge on the Ports view, since this is visible when you launch an app from the terminal:

![image](https://user-images.githubusercontent.com/35271042/136114867-e5c8ab47-02c6-4e3c-8522-81c7c76560a8.png)
