### ISSUE TITLE
Semantic Highlighting token types does not apply to primitive types

### ISSUE THREAD

**Issue by wesbos** [microsoft/vscode#111511]
Looks like Semantic highlighting does not highlight primitive types 

Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-11T01:11:34.018Z (2 wks ago)
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

Steps to Reproduce:

1. Paste the following code in a `test.ts` file:

```ts
type Age = 1 | 2;

const age: Age = 2;
const myString: string = 'hey';

async function myString(): Promise<string> {
  
}

async function myAge(): Promise<Age> {
  
}
```

2. Notice how `string` is not highlighted the same as `Age`. 

<img width="643" alt="image" src="https://user-images.githubusercontent.com/176013/100623979-de6a9980-32f0-11eb-9f9c-95aca8b6470a.png">

There is not semantic token for for `string` (or number, or boolean, or any primitive types)

<img width="627" alt="image" src="https://user-images.githubusercontent.com/176013/100624063-f7734a80-32f0-11eb-9732-664a929e5009.png">

But there is for custom types:

<img width="825" alt="image" src="https://user-images.githubusercontent.com/176013/100624135-0b1eb100-32f1-11eb-8fb8-a02c697bf04a.png">

Not sure if this is intentional or a bug :) 

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment]
It was intentional not to emit semantic tokens for primitive types. The idea was to focus on identifiers that need to be resolved in the context and where semantic highlighting can make a difference to syntax highlighting.
(after all semantic highlighting is thought as a refinement on top of syntax highlighting)

Also several themes have special colors for built-in types, so we need a 'primitive' modifiers (maybe even more than one)

Semantic highlighting for TypeScript is now being taken over by TypeScript, so if you feel we need support for primitive types, the issue needs to go there

**Comment by wesbos** [comment]
Sounds good- thanks for your time and the reply! I appreciate it
