### ISSUE TITLE
Unsupported format for ecmascript-rest-spread

### ISSUE THREAD

**Issue by simonguo** [Microsoft/vscode#11158]
![0d17f687-2426-4fe4-958c-12b537d7ac77](https://cloud.githubusercontent.com/assets/1203827/18078403/ea9a15f6-6ebd-11e6-8338-b7df390936ac.png)

.editorconfig

```
root = true

[*]
charset = utf-8
end_of_line = lf
indent_style = space
indent_size = 4
trim_trailing_whitespace = true
insert_final_newline = false

[package.json]
indent_style = space
indent_size = 2
```

I can't bear it

**Comment by waderyan** [comment]
Thank you for opening this issue @simonguo. In order to help us solve this issue, can you please provide more information, including the following. 

1. What specific steps did you take? For example, 1) I typed "...state.formReadyDate" 2) I right clicked and chose "Format Code", etc. 
2. Please indicate the version of VS Code you are on and the OS. 
3. Explain what you expect to see and what is different with what you actually see. 
4. Copy the code sample you used to see the bug here so I can copy and paste it in my editor. 

I will reproduce the steps you provide on my machine to confirm I am seeing the same error.

**Comment by simonguo** [comment]
- VSCode Version: 1.4.0
- OS Version: OS X EI Capitan  10.11.5


I expect:

```js
switch (type) {
    case ADD_NODE:
        return Object.assign({}, state, {
            ...state,
            propA,
            propB
        });
    default:
        return {
            propC,
            propD
        };
}
```


Executing shift+cmd+f, Formatted:

```js
switch (type) {
    case ADD_NODE:
        return Object.assign({}, state, {
            ...state,
            propA,
            propB
        });
    default:
return {
    propC,
    propD
};
}
```

**Comment by waderyan** [comment]
This is confirmed on the latest insiders build.

**Comment by waderyan** [comment]
This issue was moved to Microsoft/TypeScript#10643
