### ISSUE TITLE
Remote explorer should be more user-centric

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#111550]
Today (for me) using the Remote Explorer consists of having to switch between remote types to find the box I want to connect to. I often am switching between WSL, SSH, and Codespaces. I find that this hard switch between these types, hampers usability.

I would much prefer a more unified user-centric view, that shows me my "favorite" and/or recent connections and I could add new connections (regardless of type) from the same unified UX. I don't really want to have to think about what type of connection I am making, rather I just want to connect to a certain machine/folder/etc.

I also think there should be a more consistent user experience across the different types -- i.e. the same menu choices, etc. For example, the context menu for a WSL connection doesn't have an option to open the folder in a new window, and while SSH does, its inline action is set to it.

/cc @misolori @bamurtaugh

**Comment by misolori** [comment]
I wonder if having a dedicated recent menu, for all remote connections, would be useful here? I've always wanted a single list for all remotes so I could access it via a keyboard shortcut. Right now you have to filter recents via `[` which isn't pretty:

![image](https://user-images.githubusercontent.com/35271042/100683522-5f478680-332d-11eb-9779-fd552001fe24.png)

**Comment by bamurtaugh** [comment]
I like the idea of being more user-centric too, especially for viewing recent connections since this seems like a popular workflow (i.e. I have a box I consistently SSH into or dev container I consistently work within). 

> I wonder if having a dedicated recent menu, for all remote connections, would be useful here?

What would be considered a "menu?" Would that be in the command palette? Or an additional option in the top Remote Explorer dropdown (shown below)? 
![image](https://user-images.githubusercontent.com/25310137/100688961-61fba900-3338-11eb-9f26-60de7cfe3243.png)

I also remember it was mentioned to potentially have each group (Codespaces, SSH, WSL, etc) be its own view in the Remote Explorer to avoid having to switch between the groups.

This discussion brings up a few initial ideas:
- Dropdown menu item for "most recently used," or even potentially more user customizable options like "favorite connections"
     - Wouldn't totally mitigate painpoint of having to switch between groups, although you could potentially change to this view and be more likely to stick with it
- Having a most recent under each existing view, i.e. adding a "Recently Used" section above "SSH Targets" in the image below
     - Do we already sort by most recently used? 
     - "Recently Used" could include _any_ remote connections, not just SSH in this case, to help avoid switching groups
![image](https://user-images.githubusercontent.com/25310137/100689146-c0288c00-3338-11eb-97cf-3083e1ad646e.png)
- Allowing multiple remote views at once, which could then also include other user customizable views like a "recently used" or "favorites"
     - Potentially right-click to add one of the groups as an additional view, or being able to drag one from the drop down menu
- Some sort of button in the Remote Explorer (or a command) to "View Recent Connections" or "View Recent Remotes," which could bring up the filtered list in the command palette, or another group/view in the Remote Explorer
![image](https://user-images.githubusercontent.com/25310137/100689625-a76ca600-3339-11eb-9bbf-7f089a80b299.png)

**Comment by misolori** [comment]
I could also imagine a "All Remotes" dropdown menu item from the view that would house all remotes:

![image](https://user-images.githubusercontent.com/35271042/100697688-890fa600-334b-11eb-8e3b-4aae9e680230.png)

**Comment by alexr00** [comment]
Before we get too involved in coming up with new ways to show this we should look at the data again. We decided to only show one remote kind at a time because most users actually only use one remote kind. If that's changed, then I totally agree that there are better ways to show everything.

**Comment by bamurtaugh** [comment]
> I also think there should be a more consistent user experience across the different types -- i.e. the same menu choices, etc. For example, the context menu for a WSL connection doesn't have an option to open the folder in a new window, and while SSH does, its inline action is set to it.

Is there a reason we open WSL folders in the same window and SSH folders in a new window? It'd seem to make sense to have both inline actions behave the same way.

**Comment by alexr00** [comment]
I made the views for both WSL and Containers, and I followed the "opening a folder from a menu causes the folder to open in the current Window". I'm not sure if that's documented anywhere, but someone mentioned that was the way to go when I was implementing them.

**Comment by bamurtaugh** [comment]
> "opening a folder from a menu causes the folder to open in the current Window"

That tends to make sense to me- do you think it'd be jarring to users if we changed the inline menu action for SSH to open the folder in the current window to help with consistency and follow this paradigm?

**Comment by alexr00** [comment]
I would be very nervous about changing that. I expect users would file lots of bugs.
