### ISSUE TITLE
Test: new LSP concepts

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#111508]
Refs: https://github.com/microsoft/language-server-protocol/milestones/3.16

- [x] anyOS @aeschli 

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23111508%0A%0A)

---

A couple of new concepts have been added to LSP for the upcoming 3.16 version. We should review these concepts to ensure that they

1. fit into the LSP model
1. don't cause harm to existing LSP servers / clients

The concepts are:

- `AnotatedTextEdit` and `ChangeAnnotation` to implement `WorkspaceEditEntryMetadata` see: https://microsoft.github.io/language-server-protocol/specifications/specification-3-16/#textEdit, https://microsoft.github.io/language-server-protocol/specifications/specification-3-16/#textDocumentEdit and https://microsoft.github.io/language-server-protocol/specifications/specification-3-16/#resourceChanges
- Clarification of the `MarkupContent` here: https://microsoft.github.io/language-server-protocol/specifications/specification-3-16/#markupContent and the new client capability `general.markupContent`.
- Clarification of regular expressions here https://microsoft.github.io/language-server-protocol/specifications/specification-3-16/#regExp
- `onTypeRenameSupport` defined here (minus the fact that we will rename it): https://microsoft.github.io/language-server-protocol/specifications/specification-3-16/#textDocument_onTypeRename

**Comment by aeschli** [comment]
`ChangeAnnotation`: Likely a change consists of more than a single edit. Can multiple AnotatedTextEdits have the same ChangeAnnotation?
The problem I see is that over the wire, each AnotatedTextEdit will be flattened and on the receiving side there will a ChangeAnnotation instance for each AnotatedTextEdit.

-> needs to be spec'ed how ChangeAnnotation's are identified in order to combine them again
-> not so nice as this can result in the same label and description be sent over the wire multiple times

IMO it would be better to model this in a different way:
`AnotatedTextEdits.annotationId: number`
`TextDocumentEdit.annotations: ChangeAnnotation[]`

**Comment by aeschli** [comment]
The tables for well know regex and markdown flavors are not layouted nicely

**Comment by aeschli** [comment]
Annotatoon could also be mentioned in the Waht's new in 3.16 section. https://github.com/Microsoft/language-server-protocol/blob/gh-pages/_specifications/specification-3-16.md#-whats-new-in-316-

Otherwise all looks good!

I also read through Semantic highlighting and all other 3.16 changes.

**Comment by dbaeumer** [comment]
@aeschli regarding https://github.com/microsoft/vscode/issues/111508#issuecomment-737270028

Actually a change annotation is for a single text edit or a resource edit (create, move or delete of a file). It describes that single change. There is currently no way to add a description to a whole workspace edit. So my question is: do you think we should come up with a better name to make this more clear. Or is it simply that we should clarify what happens on the wire if two text edits refer to the same annotation?

**Comment by dbaeumer** [comment]
Closing the issue. @aeschli concerns where addressed.
