### ISSUE TITLE
Change size of terminal output.

### ISSUE THREAD

**Issue by chagai95** [microsoft/vscode#111500]
Would like to make terminal text size bigger without having to make all VScode bigger.

I can not move the terminal to an new window like suggested [here](https://github.com/microsoft/vscode/issues/10121#issuecomment-315778189) 

Happy for any workarounds.

**Comment by IllusionMH** [comment]
/question

1. Add shortcut for "Maximize/Restore Panel Size" (command `workbench.action.toggleMaximizedPanel`) and toggle it when necessary
1. Open new window VS Code just for terminal
1. Wait when #10121 implemented
1. Use separate terminal application and configure terminal.external.windowsExec` (`...linuxExec`, `...osxExec`) and `terminal.explorerKind` to use external terminal application
[Example for Windows terminal](https://medium.com/analytics-vidhya/how-to-replace-external-terminal-in-visual-studio-code-with-the-new-windows-terminal-66e8460f2d31) but you can use same approach for terminal of your choice

/cc @Tyriar

**Comment by chagai95** [comment]
Hey, this is not a question but a feature request. Why did you close it?

**Comment by IllusionMH** [comment]
Sorry, but it's really unclear what you are requesting.

Then first line is about text size.
Missed that, but you already can do that with existing `terminal.integrated.fontSize` and `terminal.integrated.lineHeight` to control font only in integrated terminal.


My answer was to how provide more area for terminal (that what I've understand under "size of terminal output" and moving to other window).

Dragging for files works only because it's just creates new editor which opens same file again.
Terminal is panel and you can't D'n'D Explorer/Search/Debug to other window.

If you are requesting this feature please create separate issue with more details and use cases for this feature, not just state fact that you can't drag panels between windows.

**Comment by chagai95** [comment]
Thanks, what I meant was change the font size with scroll wheel feature, should I change the title?. I now understand that scrolling to change font size is probably only possible in editors...

**Comment by IllusionMH** [comment]
Unfortunately I have no rights to re-open this issue and I think it's better to open separate issue focused on changing font size with scroll (or at least key binding similar to `editor.action.fontZoomIn`) that won't have comments from this this thread which are off-topic to actual request.
