### ISSUE TITLE
Progress and Status says copying files while copying folders

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#111617]
Testing #111250

- Drag and Drop two large folders into explorer
- You will see a dialog to add/copy folders. Select copy folders
- Status bar says copying 2 files - Instead it shall say copying two folders
- Progress notification (that is shown after clicking the status bar entry) says copying 2 files - Instead it shall say copying two folders

![Kapture 2020-12-01 at 14 37 18](https://user-images.githubusercontent.com/10746682/100747810-d0954100-33e2-11eb-9d75-701757fcc4f9.gif)

**Comment by isidorn** [comment]
Yeah we always say Copying N files. Even though it might be folder
I can change to say `Copying N resources`. I want a term that contains both files and folders. Let me know if you have a better suggestion

**Comment by sandy081** [comment]
How about ->

If all of them are folders - say folders.
If all of them are files - says files.
If they are mixed - You can say Copying folders and files

**Comment by isidorn** [comment]
As you suggested I have improved the label. However I will only have the precise lable for in explrorer actions - where I already have the items resolved and I know if they are folders and files.
For dragging outside of vscode I actually do not know if they are files or folders. And due to that in your particular use case I will say "resources".
I think that is fine for now
