### ISSUE TITLE
Running a script from the NPM Scripts view doesn't show the multiple lock file warning

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#111635]
Testing #111514

When running a script from the NPM Scripts view then there is no warning about having multiple lockfiles.

**Comment by alexr00** [comment]
You should have seen the warning when the script view loaded, since that is when we first notice the multiple lock files. Did you see the warning then?

**Comment by egamma** [comment]
I see a notification when I run `Run Tasks`

![image](https://user-images.githubusercontent.com/172399/100781432-50cf9c80-340b-11eb-82fc-171ecbeddfbf.png)

When I then reload the window and open the NPM Script Explorer then I don't get a notification. Would it be the same notification?

**Comment by alexr00** [comment]
Yes, you should be seeing the same notification when the NPM scripts view is opened. Were there two lock files at the time that the view was opened?

**Comment by egamma** [comment]
I see, there is a notification when the NPM Script Explorer is visible, but the notification only briefly flashes and you can almost not spot it.
![recording](https://user-images.githubusercontent.com/172399/101165912-b86a2f80-3637-11eb-876b-47f1a3edaa27.gif)

You could show the notification or an alert only when a script is run for the first time.
Since there is an npm output channel I would also log the message there.

**Comment by alexr00** [comment]
New behavior:
- If you **do** have the NPM script view open, then you will only see the warning when you run a script from the view.
- If you **do not** have the NPM script view open, and haven't had it open since the package.json changed or there was reload, then you will see the warning when you run the run an NPM task from one of the task commands.

**Comment by rzhao271** [comment]
I have the npm scripts view open and ran a task, but the warning still showed up.
To me, this is expected behaviour, but https://github.com/microsoft/vscode/issues/111635#issuecomment-740739685 says otherwise?

![recording (11)](https://user-images.githubusercontent.com/7199958/106195608-3b55c500-6165-11eb-8797-bc588abbabc8.gif)

**Comment by alexr00** [comment]
My comment did say otherwise, but after looking at it I like this behavior.
