### ISSUE TITLE
Clear output action takes 1 second to execute

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#11165]
When clicking the clear output action, the output is only cleared after 1 second. 😢 

![image](https://cloud.githubusercontent.com/assets/22350/18081139/de5f04e2-6e98-11e6-96dd-d2af8c7fa57e.png)

**Comment by isidorn** [comment]
Every console update is done with a 0.5s delay to not kill the tree with too many updates
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/repl.ts#L67
Closing this as designed as this is the limitation we will have to live with as long as we use the tree. In the next couple of milestones I plan to investigate into using the editor instead of the tree.

**Comment by joaomoreno** [comment]
...

**Comment by joaomoreno** [comment]
Created a PR with a fix.

**Comment by isidorn** [comment]
Great fix - thanks!
