### ISSUE TITLE
Unable to force-toggle word wrap with diffEditor word wrap option

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#111649]
Testing #111544

Version: 1.52.0-insider (user setup)
Commit: bf21395291146c014220eb70b54fdfc0a15956b5
Date: 2020-12-01T09:19:32.000Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

I had a Markdown file with long lines, then duplicated each line to make them twice as long. Then I opened the difftool and the lines were wrapped even though the setting was set to off.

**Comment by sandy081** [comment]
I think this works for me. This is same old language overrides UX issue. Markdown settings are overridden at language so, you need to update the setting using markdown language as follows

```
"[markdown]": {
		"editor.wordWrap": "off",
	}
```

**Comment by alexdima** [comment]
@sandy081 Thank you for taking a look. But I can reproduce, this issue is about using `diffEditor.wordWrap` which I introduced as an override for the `editor.wordWrap`, even if `editor.wordWrap` comes in via language specific settings. In other words, using `"diffEditor.wordWrap": "off"` should disable word wrap in all diff editors, including markdown files.

**Comment by sandy081** [comment]
Yeah I am sorry, I was mistaken about the setting while testing. I was testing with `editor.wordrWrap` and I thought this issue was about that.

I can repro the issue with `diffEditor.wordWrap` setting.
