### ISSUE TITLE
Show a confirmation dialog if window is asked to reload while copying the folder 

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#111610]
Testing #111250

- Drag and Drop a large folder into explorer
- While the operation is in progress, reload the window
- Window silently reloads and the operation is half performed

Inform user about the operation in this case

**Comment by isidorn** [comment]
This is a fair request.
@bpasero do we have some common service where I can say I want to be involved when the reload happens. I guess save does the same when hot exit is disable, when there are unsaved files we prompt?

**Comment by isidorn** [comment]
I hate you bot.

**Comment by bpasero** [comment]
@isidorn yeah you can veto from the `ILifecycleService`. Check the before unload event.

**Comment by isidorn** [comment]
Great, will try to add in Debt week, not for endgame -> december

**Comment by isidorn** [comment]
If we decide to do this feature we might want to do it on the `BulkEditService` layer.
Since the same can be said if there is a long running bulk edit operation that is not triggered from the explorer. If the user quits VS Code we should prompt the user

I can also do this from the Explorer, but might be better if we have a unified story
@jrieken @bpasero let me know what you think

I also checked when we veto currently and it is from Tasks, Terminal. And I know we also do this for unsaved files

**Comment by jrieken** [comment]
Having in the bulk edit service makes sense

**Comment by isidorn** [comment]
Okey, I can look into creating a PR for this.

**Comment by isidorn** [comment]
I have added this to the `bulkEditService` and seems to work fine.
@jrieken if you are interested you can checkout the commit 9321b2f141

I do the confirm dialog per `bulkEdit` applied, so in theory there could be many `bulkEdits` at the same time and the user can get a lot of these dialogs. Let me know if you think this can happen in practice and if yes I can try to sum all the edits that are in progress in one dialog. 

![Screenshot 2021-01-22 at 10 17 18](https://user-images.githubusercontent.com/1926584/105471657-460ee680-5c9b-11eb-8ae0-0db7fab952d3.png)
