### ISSUE TITLE
运行程序意外停止

### ISSUE THREAD

**Issue by Tuzhiqiang1996** [microsoft/vscode#111794]
Issue Type: <b>Bug</b>

启动项目，自动停止

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3591)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|5.87GB (0.91GB free)|
|Process Argv|--crash-reporter-id 741e1152-cf12-44ff-870d-bb154984dfbe|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tomcat|ada|0.11.3
simple-react-snippets|bur|1.2.3
wechat-snippet|Cha|0.4.11
path-intellisense|chr|2.3.0
wxml-vscode|cny|0.1.2
vscode-wxml|cod|0.1.9
bracket-pair-colorizer|Coe|1.0.61
app-migrator|deb|0.0.6
es7-react-js-snippets|dsz|3.0.0
prettier-vscode|esb|5.8.0
vscode-reveal|evi|4.0.3
auto-close-tag|for|0.5.9
auto-rename-tag|for|0.1.5
code-runner|for|0.11.1
pdf|fri|0.0.6
vscode-hexdump|ili|1.8.2
vue|jcb|0.1.5
template-string-converter|meg|0.3.3
react-native-styled-component-snippets|mil|1.0.1
vscode-language-pack-zh-hans|MS-|1.51.2
debugger-for-chrome|msj|4.12.11
vscode-react-native|msj|1.1.1
vetur|oct|0.30.3
minapp-vscode|qiu|2.2.2
java|red|0.64.1
vscode-xml|red|0.14.0
wxapp-helper|sea|0.2.1
vscode-hexdump|sle|1.8.1
open-in-browser|tec|2.0.0
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.29.0
vscode-java-pack|vsc|0.11.0
vscode-maven|vsc|0.26.0
vscode-icons|vsc|11.0.0
axios-snippets|Ygg|1.0.0

</details>

**Comment by Tuzhiqiang1996** [comment]
![78778977](https://user-images.githubusercontent.com/57666259/100987909-10e2f380-358a-11eb-819a-b8a3eedd3cbe.png)
![Snipaste_2020-12-03_17-05-59](https://user-images.githubusercontent.com/57666259/100987973-21936980-358a-11eb-9bcc-62ff9f61f432.png)
![Snipaste_2020-12-03_17-06-12](https://user-images.githubusercontent.com/57666259/100987979-235d2d00-358a-11eb-9f6c-2d727b43d044.png)
![Snipaste_2020-12-03_17-06-22](https://user-images.githubusercontent.com/57666259/100987981-23f5c380-358a-11eb-8c13-d8c1dee0fdfe.png)
The program starts and stops, the above is the screenshot of error report, please tell me how to solve, thank you

**Comment by Tuzhiqiang1996** [comment]
![78778977](https://user-images.githubusercontent.com/57666259/100988328-91095900-358a-11eb-9b42-1792916a021d.png)
![Snipaste_2020-12-03_17-05-59](https://user-images.githubusercontent.com/57666259/100988365-9d8db180-358a-11eb-873b-6dfa6a359d74.png)
![Snipaste_2020-12-03_17-06-12](https://user-images.githubusercontent.com/57666259/100988388-a2eafc00-358a-11eb-9007-6d69cc53c4be.png)
![Snipaste_2020-12-03_17-06-22](https://user-images.githubusercontent.com/57666259/100988420-aaaaa080-358a-11eb-8863-31b33cb545b5.png)

**Comment by yume-chan** [comment]
Noticing the `Memory (System): 5.87GB (0.91GB free)` and `Window has crashed (reason: oom)`, maybe it's just too little memory?

**Comment by Tuzhiqiang1996** [comment]
okey

**Comment by sandy081** [comment]
Can you please try our latest insiders and check if you are seeing the same issue or not - https://code.visualstudio.com/insiders/

**Comment by Tuzhiqiang1996** [comment]
okay

**Comment by alexdima** [comment]
**NOTE**: **Be sure you are using a version of VS Code >= 1.52** 
It looks like the issue is caused by one of your installed extensions. All extensions execute together on a single nodejs process, so in order to narrow down the possible problematic extension, please try the following:
* run `F1 > Help: Start Extension Bisect`
* (this will restart VS Code with half of your extensions disabled)
* try to do the steps which reproduce the problem
* if the problem reproduces, click "This is bad" (this narrows down the problematic extension to the half which was enabled)
* if the problem does not reproduce, click "Good now" (this narrows down the problematic extension to the half which was disabled)
* these steps will repeat until the problematic extension is found

| initial | step | final |
|---|---|---|
| ![image](https://user-images.githubusercontent.com/5047891/101918658-e9170f80-3bc9-11eb-9977-857baa291937.png) | ![image](https://user-images.githubusercontent.com/5047891/101918683-ef0cf080-3bc9-11eb-9f9e-98b0177991b2.png) | ![image](https://user-images.githubusercontent.com/5047891/101918706-f502d180-3bc9-11eb-8c86-e56355958bd4.png) |
