### ISSUE TITLE
Program 'a.exe' failed to run in C++ 

### ISSUE THREAD

**Issue by Mukeshbadyal** [microsoft/vscode#111721]
When i write the program in C++ 
Execution is run successfully 
but a.exe file is not run
Note:a.exe file is shown but suddenly disappear 
![image](https://user-images.githubusercontent.com/68585320/100845832-c8e9a100-34a3-11eb-9b6c-de58362b9383.png)
![image](https://user-images.githubusercontent.com/68585320/100845888-dbfc7100-34a3-11eb-8e81-5d2e78d1ef95.png)

**Comment by Dragonmetiore** [comment]
<img width="960" alt="Vscode Problem" src="https://user-images.githubusercontent.com/88475466/128297130-fdcb2d8f-d5b6-435a-b1ed-e6e7d0d653ad.PNG">

Is there any virus in your printf or scanf because macfee again and again showing that we stop a virus and I am unable to run the code pls solve this issue as soon as possible

**Comment by Dragonmetiore** [comment]
if I remove printf and scanf function then the code is working fine. I install vscode yesterday. Can you tell me any solution except "off the antivirus".
