### ISSUE TITLE
Javascript objects not highlighting correctly on master

### ISSUE THREAD

**Issue by jhealy86** [Microsoft/vscode#1118]
It looks like highlighting of JavaScript objects was broken on the current master. For reference, here's what it looks like on the current production build (0.10.3):

![0.10.3 JS Objects](http://i.imgur.com/UZ9XqoF.png)

And here's how it looks on master:

![Master JS Objects](http://i.imgur.com/N2ED6Fq.png)

I tried fiddling around with tokens.css a little but reverting the changes there didn't do anything. I think this may be related to the changes made to JavaScript.tmLanguage as a result of #133.

**Comment by aeschli** [comment]
Yes, that's related to the change to use the TypeScript textmate grammar. The new grammar has chosen to not emmit specific tokens for object keys.
Moving as an enhancement request to the typescript grammar repo.

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#23

**Comment by rajanand02** [comment]
This issue seems to be there in plain javascript as well.

![image](https://cloud.githubusercontent.com/assets/4851763/18981866/777a433e-86ff-11e6-99a2-b63992019e16.png)

The same snippet in Atom

![image](https://cloud.githubusercontent.com/assets/4851763/18981931/f64e209a-86ff-11e6-9d3f-35ea7ba58ad4.png)
