### ISSUE TITLE
vscode.workspace.openTextDocument(uri) can't open file bigger than 50MB: cannot be synchronized with extensions

### ISSUE THREAD

**Issue by rioj7** [microsoft/vscode#111849]
- VSCode Version: 1.49
- OS Version: Windows 8

Steps to Reproduce:

1. Have some text file bigger than 50MB
1. In an extension create an URI for that file with `file` sceme
1. call `vscode.workspace.openTextDocument(uri)` to open the file
1. you get an error message with Details: `Files above 50MB cannot be synchronized with extensions`

Opening the file with File|Open File... : No problem

`cat` a file to the terminal with the file path as content and then Ctrl+Click to open file: No problem

How can I open this big file in an editor from an extension?

Problem surfaced on a StackOverflow question: [Browsing lines/columns in a big file in VSCode
](https://stackoverflow.com/q/65077295/9938317)

**Comment by jrieken** [comment]
That the designed behaviour. Many extensions run brute-force operations on text document and when documents are above a certain size those operation become catastrophically slow and they would prevent all other extensions from working. That's why we don't expose such monster documents to extensions in the first place. We use this graceful degeneration in many parts, e.g we open the document but don't sync it for extensions, or we open a document but disable certain native editor features etc. This generally makes performance good but I do agree that there is the occasional corner case that's unpleasant
