### ISSUE TITLE
Windows: Investigate writing native library / command line tool for file traversal

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#11182]
Testing https://github.com/Microsoft/vscode/issues/11035
- open a path in VS Code using UNC loopback (e.g. \localhost\c$\GitDevelopment\vscode)
- quick open to find a file

=> it takes a lot longer compared to our raw node.js solution in 1.4
=> maybe we need to detect UNC cases and avoid using dir command

**Comment by bpasero** [comment]
I am seeing the same when opening a folder that is mapped into Windows from the Parallels host (Mac). Since this seems like a normal use case, I am marking this one as important.

**Comment by chrmarti** [comment]
The Parallels case seems to work for me. I've opened, e.g.: \\psf\Home\Development\repos\target

**Comment by chrmarti** [comment]
Ah...both work, I need to investigate the performance.

**Comment by bpasero** [comment]
@chrmarti shouldn't you be on vacation :)? My suggestion for the windows issues is to go back to the node.js search for this release on Windows only and then revisit in September with a different solution.

**Comment by chrmarti** [comment]
Bummer, dir doesn't perform well with these high latency cases. (Measured on Parallels myself now.)

I agree, we should revert. Longer term we might just detect UNC paths and fall back. The bigger problem might be the long paths (#11183) and circular symlinks (#11179), since we can't detect these upfront. Even detecting these from the output of dir might not be trivial, because the only hint is a message about a path being too long on stderr that might get translated (I need to check that though).

(12 hours behind you in the middle of the Pacific :)

**Comment by bpasero** [comment]
@chrmarti I can add a check for windows and use the old node.js approach. From testing it seems there are no such issues on Mac and Linux.

I do think that for Windows we should look into writing C#/C++ command line tool to handle this (similar how we do for the Windows file watcher). E.g. leveraging `Directory.GetFiles`. There does not seem to be a way to prevent dir from running into symlink loops.

**Comment by chrmarti** [comment]
We reverted to use the existing tree traversal in node.js (#11293). Closing bugs due to the use of 'dir' as duplicates of this one.

**Comment by chrmarti** [comment]
Moving this out from the September release due to its scope.

**Comment by chrmarti** [comment]
Using ripgrep now.
