### ISSUE TITLE
Command 'Remote-Containers: Open Folder in Container...' results in an error (Cannot read property 'forceNewWindow' of null)

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#111898]
Found while testing https://github.com/microsoft/vscode-remote-release/issues/1817

1. Clone https://github.com/Microsoft/vscode-remote-try-dotnetcore and open it in VSCode
2. Run the command "Remote-Containers: Open Folder in Container..." and select the folder

<img width="486" alt="Screen Shot 2020-12-03 at 4 41 39 PM" src="https://user-images.githubusercontent.com/3672607/101107103-70d79b00-3586-11eb-816f-60f750ce9ed7.png">

**Comment by alexdima** [comment]
I think the rpc protocol is fine, since I had the same bug a while ago. It has a unit test in place for that [here](https://github.com/microsoft/vscode/blob/b8aa4141d28dfa6ba667df8a19e9d71b13858331/src/vs/workbench/services/extensions/test/common/rpcProtocol.test.ts#L195-L204) so I do not think that has regressed. 

@jrieken I think the command arguments serialization might suffer from the `undefined` becomes `null` problem. IIRC this happened for the rpc protocol when using `JSON.parse(JSON.stringify([0,undefined,2]))` which becomes `[0,null,2]`

**Comment by jrieken** [comment]
What has changes is that some commands are now registered in the renderer and invoked with slightly different argument structured (I believe is was a single object before). Adding @bpasero because API commands should be somewhat graceful. 

Also back to @alexdima because I do see this as an IPC issue. We are calling this with `undefined` and receiving `null`.


<img width="1281" alt="Screenshot 2020-12-04 at 17 15 10" src="https://user-images.githubusercontent.com/1794099/101187147-46541380-3654-11eb-8eb2-b7dfe0afad7f.png">


<img width="590" alt="Screenshot 2020-12-04 at 17 17 01" src="https://user-images.githubusercontent.com/1794099/101187354-8a471880-3654-11eb-987b-b2f8988108ac.png">

**Comment by jrieken** [comment]
Makes sense. I didn't expect you to tackle this and generally I try to be defensive wrt undefined/null when they come via RPC. Leaving this to @bpasero to more graceful
