### ISSUE TITLE
Text areas should use native mouse cursor

### ISSUE THREAD

**Issue by marcoms** [microsoft/vscode#111813]
- VSCode Version: 1.51.1
- OS Version: macOS Big Sur

Steps to Reproduce:

1. Hover over any text area/text field and see the following:

![Screen Shot 2020-12-03 at 1 10 17 pm](https://user-images.githubusercontent.com/4211302/101022314-24ca2d80-3569-11eb-9500-3e5743fd45e4.png)

This is because of: https://github.com/microsoft/vscode/blob/f74e473238aca7b79c08be761d99a0232838ca4c/src/vs/base/browser/ui/mouseCursor/mouseCursor.css#L10-L14

I'm not sure why a custom bitmap cursor is used on macOS, but IMO is a downgrade over the native cursor, and the blurriness is more pronounced as I use a larger cursor size.

See the improved version after just using `cursor: text` in custom CSS:

![Screen Shot 2020-12-03 at 1 11 26 pm](https://user-images.githubusercontent.com/4211302/101022478-593de980-3569-11eb-85d5-1d25c1ab552f.png)

In the fixed version, both contrast and clarity are improved since it is not a bitmap and is black with a white border around it

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexdima** [comment]
This is always coming back since years.
- when we used the default OS cursor, people complained that they cannot see it.
- so we added our custom cursor
- but then macOS Catalina shipped with support for dark themes, which improved their native cursor on dark background, so we removed our custom cursor
- then people complained again and wanted back our custom cursor

I think this needs to be an option, it appears we aren't pleasing everybody regardless what we do.

The latest addition via https://github.com/microsoft/vscode/pull/96947#issue-413229918
