### ISSUE TITLE
The pointer shifts itself while typing.

### ISSUE THREAD

**Issue by magusikrak** [microsoft/vscode#111808]
- VSCode Version: 1.51.1
- OS Version:  Linux x64 5.4.0-54-generic

![The bug in gif](https://user-images.githubusercontent.com/51502114/101014011-476e3d80-358d-11eb-9c05-dec457f7714e.gif)

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by alexdima** [comment]
What linux distro do you use? Do you have a specific font family? Did you just install this font family? Do you use some sort of display scaling? 

The workaround is to configure `"editor.disableMonospaceOptimizations": true` -- this is an internal setting so it might render greyed out in `settings.json`, but even if the workaround works for you, I would like to understand what the issue is and be able to reproduce on my side.

**Comment by magusikrak** [comment]
> What linux distro do you use? Do you have a specific font family? Did you just install this font family? Do you use some sort of display scaling?
> 
> The workaround is to configure `"editor.disableMonospaceOptimizations": true` -- this is an internal setting so it might render greyed out in `settings.json`, but even if the workaround works for you, I would like to understand what the issue is and be able to reproduce on my side.

I am using Zorin Os 15. I am using Fira Code. No, the font family has been installed for a long time, and changing the font family to default doesn't solve this. No, I do not use display scaling.
I've added ``` "editor.disableMonospaceOptimizations": true ``` to my settings but that hasn't solved my issue.

**Comment by alexdima** [comment]
@magusikrak I have just tried on a fresh Zorin OS 15 Lite with a fresh VS Code installation (no settings, no extensions) and I cannot reproduce:

![Kapture 2020-12-09 at 15 30 36](https://user-images.githubusercontent.com/5047891/101642667-8e4baf80-3a33-11eb-8172-ecc843bef3b4.gif)

Could you please try to close all instances of vscode and execute `code --user-data-dir=/some/new/folder`?
