### ISSUE TITLE
Debug Console: Copy multiple lines

### ISSUE THREAD

**Issue by jpoon** [Microsoft/vscode#112]
Enable copying of multiple lines (e.g. all highlighted lines) from the debug console.

Repro:

1. Select several lines in debug console
2. Right click->copy
3. Only one line is copied.

**Comment by isidorn** [comment]
This works if you selecet several lines and do ctrl + c, but not via context menu since this copies only the value of one variable (we also evaluate that variable first). I understand it is a bit confuzing and will look into improving this experience.

**Comment by jpoon** [comment]
And it only copies text selected that is in current view. Select something, scroll away, and un-copiable which is another confusing thing.

**Comment by isidorn** [comment]
Copy value action was causing confusion and because we now wrap lines in repl I have removed the copy value action. User can always select what he wants and ctrl/cmd + C to copy it.

As the selection is not being preserved when scrolling that is because we use a virtualised tree and that is captured in #2163
