### ISSUE TITLE
Request: Provide the ability to list extensions by all/enabled/disabled

### ISSUE THREAD

**Issue by fade2gray** [microsoft/vscode#112088]
Please provide the ability to list extensions by all/enabled/disabled, e.g...

```
>Code --list-extensions -all
>Code --list-extensions -enabled
>Code --list-extensions -disabled
```
Thank you.

**Comment by sandy081** [comment]
What is the use case for this requirement?

**Comment by fade2gray** [comment]
@sandy081 
I am trying to develop an AutoHotkey script the relies on being able to determine whether any installed AutoHotkey related extensions have been disbabled.

The purpose of the cript is to dispaly an AHK GUI that enables changes to be made to the extension's settings by wrting to the `User\settings json` with a couple of mouse clicks rather than manually using the keyboard to change the settings via the VSC sidebar.

I have recently discoverd that I can determine this by using regular expressions to search `state.vscdb` for strings contaning `extensionsIdentifiers/disabled`, but it would make things easier if I could discover, via the command line, what extensions have been disabled.

**Comment by sandy081** [comment]
I see, but unfortunately enablement info is not available from CLI and we do not have plans to provide this.

**Comment by AltitudeApps** [comment]
The use case for this would be when I am asked to restart VSCode with all extentions disabled, except for the extension I am trying to file a bug for.

I need to get a list of enabled extensions so that I can start vscode with the --disable-extension flag, listing all enabled extensions except the one I need to leave enabled.

(I will also then have a list of enabled extensions which I can use on other machines, in scenarios where I cannot use the sync features.)
