### ISSUE TITLE
Failed to install '[extensions-name]' Download Manually

### ISSUE THREAD

**Issue by daffa-db5** [microsoft/vscode#112014]
- VSCode Version: 1.51.1 (system setup)
- OS Version: Windows 10 20H2
`
Version: 1.51.1 (system setup)
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:34:32.027Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042
`

Steps to Reproduce:

1. I installed a fresh install of vscode using system setup
2. And then i want to install some extensions like "ESLint" for example
3. But it cannot install and I got a popup message saying "Failed to install '[extensions-name]'. Download Manually"
4. Like this
![image](https://user-images.githubusercontent.com/69158099/101353288-e8c6fd80-38c5-11eb-811b-d8c8e595c539.png)
5. I've been searching on the internet and they're saying that I have to change DNS configuration, but it didn't work
6. Any help?

Does this issue occur when all extensions are disabled?: Yes/No (I've got a fresh install i think there is no pre-installed extensions)

**Comment by sandy081** [comment]
Please follow these steps

- Help -> Toggle Developer Tools -> Network
- Then check for any network failed requests while browsing and installing the extensions if found all requests fails then its probably a proxy or DNS issue at your end.
- To confirm its a DNS issue check if you can access this page https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default, if you cannot please try configuring your DNS like pointing to 1.1.1.1 as suggested here? https://1.1.1.1/dns/. Otherwise please contact your network administrator.
- If it is not a network issue, please share the logs from the following locations
    - Help -> Toggle Developer Tools -> Console
    - View -> Command Pallette... -> Toggle Shared Process -> Console
    - View -> Open View… -> Log (Shared)
    - View -> Open View… -> Log (Window)

**Comment by daffa-db5** [comment]
after i cleared my DNS cache through cmd using `ipconfig /flushdns` command and forget the network and then restarted my laptop, it finally works, thanks for the info
