### ISSUE TITLE
Add flag to vscode.workspace.applyEdit to save after applying edits

### ISSUE THREAD

**Issue by alyssajotice** [microsoft/vscode#112109]
We have an [issue](https://github.com/MicrosoftDocs/live-share/issues/3775) with Live Share where any coediting from users results in all of the edited files opening for all users in a session. To apply our edits during coediting, we use the VS Code API vscode.workspace.applyEdit. This can lead to large amounts of files being opened in sessions with multiple participants. 

We're requesting a feature to add a flag to vscode.workspace.applyEdit that could designate not opening the file when applying the edit. That way, we can apply edits while not cluttering user workspaces. 

cc @Daytonellwanger

**Comment by jrieken** [comment]
Not convinced that applyEdit is the right place. Adding @bpasero to explain the logic behind opening editor tabs

**Comment by bpasero** [comment]
We have some [generic code](https://github.com/microsoft/vscode/blob/8fcf778ba251131780f2a110d311161f39b97b03/src/vs/workbench/contrib/files/browser/editors/textFileEditorTracker.ts#L49-L72) that observes text models getting dirty. If the model remains dirty and is not auto saved or saved directly, we open it as editor to indicate this to the user. 

The UX motivation behind this is that if a user sees dirty indicators in the UI (e.g. in the explorer), it would be weird to not see associated dirty editors as well. In the end, without an open editor with the dirty file, you as a user cannot make a decision to save or discard the change, nor are you getting aware of what has changed.

I am not involved into what the workspace edit code is doing in the end, but I just tried a large "Search & Replace" operation that changes 1400+ models and saves them. Since I see no editor opening, I think there is maybe something that Liveshare or the `applyEdit` API is doing differently?

![recording](https://user-images.githubusercontent.com/900690/101617107-83cbee80-3a10-11eb-8f59-e7af4eb254ab.gif)

**Comment by jrieken** [comment]
Search & replace and applyEdit are using the same underpinnings. I guess this depends on you using auto-save, right?

**Comment by bpasero** [comment]
No, this was a insiders session specifically with a fresh user data dir to rule that out. 

@sandy081 might have more insights how `applyEdit` is used in search + replace.

**Comment by jrieken** [comment]
Well, both use [`IBulkEditService#apply`](https://github.com/microsoft/vscode/blob/2e3236827e58c58c91917cffd17d3ab88e772ee7/src%2Fvs%2Feditor%2Fbrowser%2Fservices%2FbulkEditService.ts#L92)

**Comment by sandy081** [comment]
Yes, I use `IBulkEditService#apply` and save all files after

https://github.com/microsoft/vscode/blob/6643750275a7c3503efeb4a3e259fc8a2aa22222/src/vs/workbench/contrib/search/browser/replaceService.ts#L106-L109

**Comment by alyssajotice** [comment]
Is there some other difference between the `replaceService` and `applyEdit` that would change the behavior of opening (or not opening) the edited files?

**Comment by bpasero** [comment]
I can only guess timing: if the edits apply but are only saved `>50ms` because this is triggered from the extension host, the editors would still open. In that regard, having a flag for the `applyEdit` to save after changing would probably be needed still.

**Comment by alyssajotice** [comment]
Just tested - turning on auto save with a delay of 50 ms doesn't open the editors when in a Live Share session.

**Comment by bpasero** [comment]
Yes, that is a workaround for the user. Having auto save enabled with a delay <1s will also not open any editor.

**Comment by alyssajotice** [comment]
I will provide the workaround to the user and keep investigating. What are your thoughts on adding the flag?

**Comment by daytonellwanger** [comment]
We could also call `save` on the document after the `applyEdit` `Thenable` resolves. I think that would work, and not require any changes on the VS Code side?

**Comment by alyssajotice** [comment]
@daytonellwanger I'll give that a try!

**Comment by bpasero** [comment]
Let us know how that went.

**Comment by alyssajotice** [comment]
Unfortunately, the workaround did not work. The low auto-save delay caused errors when hot reloading for other Live Share session participants. 

Dayton's idea did not work either. If both users have a file open, the dirty state must match. That approach won't work because upon a coediting event, we can only take action on the receiver's side and we can't match the states.

**Comment by bpasero** [comment]
@alyssajotice ok. is the guest actually having write access or are the editors readonly? maybe I can relax this logic a bit and don't open editors that are dirty but readonly...

**Comment by alyssajotice** [comment]
The scenario the user filed the issue about was for a session where guests have read/write access. Does this affect the fix?

**Comment by daytonellwanger** [comment]
@alyssajotice , if we're able to prevent the file from opening after applying an edit by saving the file, then I don't think there's anything for VS Code to address, since as @bpasero noted, there's good UX motivation for having open editor tabs for dirty documents.

It seems to me that it would be an extension's responsibility to handle anything else.

**Comment by bpasero** [comment]
I think having a flag and then saving all from the renderer somewhere here should prevent the editors from opening (given what Sandeep does in https://github.com/microsoft/vscode/issues/112109#issuecomment-741800718):

https://github.com/microsoft/vscode/blob/a029dda2fe73994e5ff6e64e51b9ce66544560bc/src/vs/workbench/api/browser/mainThreadBulkEdits.ts#L22-L22

> The scenario the user filed the issue about was for a session where guests have read/write access. Does this affect the fix?

I think readonly editors are a bit different because the user cannot save them anyway, so we should then maybe not open them. However it seems this would not solve all the cases you have.

**Comment by a-stewart** [comment]
Hi,

Just joining in with this as we are seeing similar issues.

One option that might be worth considering is that there is an option `respectAutoSaveConfig` that is passed into the bulkEditService that specifies whether the config around automatically saving bulk edits is honoured.

This is currently not defined (as far as I can see) when called by an extension, so the user preference is not respected. Perhaps we should either set it to true, or allow the extension to define it?

**Comment by jrieken** [comment]
API feedback: have `WorkspaceEditMetadata` object instead of simple boolean, figure out if this needs to be done for FileWillXYZ-events too

**Comment by jrieken** [comment]
To verify

* make sure the [`applyEdit`](https://github.com/microsoft/vscode/blob/6de5257b642a24b7cffbb146f691d65b015b2323/src/vscode-dts/vscode.d.ts#L12194)-function accept metadata that allow to mark edits as being part of a refactoring
