### ISSUE TITLE
Marketplace

### ISSUE THREAD

**Issue by mcornelius3** [microsoft/vscode#112115]
Issue Type: <b>Bug</b>

Can't install extensions from marketplace

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A4-6300 APU with Radeon(tm) HD Graphics     (2 x 3693)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.69GB (2.07GB free)|
|Process Argv|--crash-reporter-id bccba7cc-8193-4b68-9ad2-481d646e7779|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.2.0
dart-code|Dar|3.17.0
flutter|Dar|3.17.0
vscode-markdownlint|Dav|0.38.0
githistory|don|0.6.14
es7-react-js-snippets|dsz|3.0.0
prettier-vscode|esb|5.8.0
auto-rename-tag|for|0.1.5
kite|kit|0.135.0
python|ms-|2020.11.371526539
jupyter|ms-|2020.11.399280825
debugger-for-chrome|msj|4.12.11

(1 theme extensions excluded)

</details>

**Comment by sandy081** [comment]
Please follow these steps

- Help -> Toggle Developer Tools -> Network
- Then check for any network failed requests while browsing and installing the extensions if found all requests fails then its probably a proxy or DNS issue at your end.
- To confirm its a DNS issue check if you can access this page https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default, if you cannot please try configuring your DNS like pointing to 1.1.1.1 as suggested here? https://1.1.1.1/dns/. Otherwise please contact your network administrator.
- If it is not a network issue, please share the logs from the following locations
    - Help -> Toggle Developer Tools -> Console
    - View -> Command Pallette... -> Toggle Shared Process -> Console
    - View -> Open View… -> Log (Shared)
    - View -> Open View… -> Log (Window)

**Comment by mcornelius3** [comment]
> Please follow these steps
> 
> * Help -> Toggle Developer Tools -> Network
> * Then check for any network failed requests while browsing and installing the extensions if found all requests fails then its probably a proxy or DNS issue at your end.
> * To confirm its a DNS issue check if you can access this page https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default, if you cannot please try configuring your DNS like pointing to 1.1.1.1 as suggested here? https://1.1.1.1/dns/. Otherwise please contact your network administrator.
> * If it is not a network issue, please share the logs from the following locations
>   
>   * Help -> Toggle Developer Tools -> Console
>   * View -> Command Pallette... -> Toggle Shared Process -> Console
>   * View -> Open View… -> Log (Shared)
>   * View -> Open View… -> Log (Window)

Thank you.
❤❤❤
