### ISSUE TITLE
Improve CI reliability, traceability and performance

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#112273]
We've been having a rough last couple of weeks wrt CI and we want to improve our hygiene there.

**Comment by lszomoru** [comment]
I would also like us to review the build timeline, to see if there is something that we can do to reduce the end-to-end time.

**Comment by alexdima** [comment]
I have started to look again into gh ci. To learn more about it, I am tweaking the `monaco` build https://github.com/microsoft/vscode/blob/master/.github/workflows/ci.yml#L120 to try and optimize it and see how fast that can get.

I plan to also look into such things as not using `gulp` if I can :D .

**Comment by joaomoreno** [comment]
Yeah getting out of gulp is good. We've started doing that for other tasks liek hygiene and electron.

**Comment by lszomoru** [comment]
Another aspect that we should consider is to run our test suites for the various platforms in parallel rather than sequentially.

**Comment by alexdima** [comment]
Ok, it looks like github actions can be quite fast, after tweaking just the build definition, (and adding `yarn` caching), the monaco build is down from 9m37s to 4m50, out of which 12s are wasted on compiling the `/build` folder because we don't check in our `.js` for that...

**Comment by alexdima** [comment]
I can look to resurrect some of the continuous (commented out) steps in that file, since it looks like the infrastructure is a lot healthier than last time we tried it.

**Comment by joaomoreno** [comment]
Just spent some time to parallelize our hygiene step and our basic compilation step:

https://github.com/microsoft/vscode/compare/joao/build-perf#diff-f62d991d10c7f60468f8e7130446eef2a8299cd5fd9545c99287a795d57f1381L110-L138.

Both these steps are clearly parallelizable on multi-core machines. But it seems our machines just aren't so:

- Hygiene went from 5:17 to 4:47, not exciting
- Compilation went from 15m32s to >18m, ok what

That was an afternoon badly spent.

**Comment by lszomoru** [comment]
I am looking at running the test suites in parallel in their own job. I am using the public `VSCode` as that is pretty straightforward and can be used to test the hypothesis. The potential challenge will be to find the "minimum" set of files that are required to run out unit/browser unit/integration tests a these will have to be shared (publish/download) between jobs.

**Comment by alexdima** [comment]
@lszomoru I like your idea of having a build per check. Combined with the `yarn cache`, I agree that it could be feasible. I am looking to implement that idea in the GH actions.

**Comment by joaomoreno** [comment]
Currently our product build takes ~1h40m. Our continuous build takes ~23m, but lacks a lot of the checks and tests that the product build stumbles upon. Most of the checks which fail most often are given a chance to run usually only once a day, when the product build runs, so it is a pain to figure out which commits actually started causing the issues. The current continuous build is just too simple and out of reality with the product that we're shipping.

[I was able to add a new `VSCODE_PUBLISH` variable](https://github.com/microsoft/vscode/tree/joao/one-build) to the product build which, when set to `false`, will make the build skip over everything which isn't related to actually publishing any assets. With it, we can run through all the checks and tests the product build runs through, but in a much faster way. I was able to get it down to 46m, running all our test suites across our 3 main platforms using the actual product bits. Note that despite the fact that it takes double the time of the current continuous build, half of that time is spent on a single compile agent, while the other half is run by 3 parallel agents. This means that agent contention doesn't suffer too much. Yes, we will wait longer for build results, but we shouldn't see a much higher backlog queue of builds than what we see today (cc @bpasero). We can even enable the batching of builds, like @lszomoru suggested. Being faster is certainly a goal, but a better one is to run the real production build bits more often, giving us better accuracy at knowing where the problems are. It's not like people are usually idle waiting for this build to finish.

I plan to make this new build mode run continuously on every of our branches, becoming our main quality gatekeeper. I'll enable that next week.

My next steps will be to make that same build definition succeed even when no secrets are available: it should skip over the mixin step and remote tests. Once that works, we'll simply use that build definition as our public build for untrusted pull request quality control.

In the end, we'll be able to delete the current continous build, thus ending this dual build maintenance nonsense, and increase the run frequency of the checks which have caused more trouble in the past, by running them continuously.

Let me know if you have any thoughts. @alexdima @lszomoru

**Comment by alexdima** [comment]
- I have worked on the github actions `ci.yml` and have managed to make faster variants (from 19m to 8m) of our current Azure continuous builds. Also, after triggering many builds, I have never seen flakiness. 
- I have also created a build definition which minifies vscode, similar to the production build (but does not do the mixin) and that one took around 20m IIRC. I would like to proceed further, but I don't think I will do the mixin on a public GH action (due to potential leakage).
- I know we had some bad experience with GitHub Actions at the beginning, but it feels rock solid to me now.

**Comment by lszomoru** [comment]
Awesome progress! ❤️

@alexdima, GitHub Actions have improved significantly, however one thing that we should consider is that there are a set of tasks that are needed for our production build (ex: signing) that might not be available as a GitHub Actions step. Something to investigate. 

I have spent some time yesterday, experimenting with extracting "test suite execution" into its own job so that we can execute test suites in parallel and not sequentially. Looking at a recent build we spend about 14 minutes running our tests suites, with the longest test suite taking 4 minutes. If I can pull off running test suites in parallel we could save about 10 minutes from the end to end build time.

+1 on meeting early next week, discuss our findings, and come up with a plan forward.

**Comment by joaomoreno** [comment]
I really like the progress. I will take some of those ideas into the product build, like moving hygiene to a separate job. Though it needs to be better connected since a failing hygiene should not only fail the build altogether but also stop platform dependent builds from even starting. Doable and it shaves off 4 minutes. I suspect sparse checkout isn't really possible since we call `git merge` from distro... but needs confirmation.

But I think we're missing the target here. The duration of the continuous build was never the problem. It's not like today people are often idle waiting for that build to turn green or red. It's the fact that the build doesn't catch everything.

IMO, the frustrations are:

1. Most of the problems are only caught once every 24h in the product build.
2. Build jobs are too coarse, so retriggering them can take upwards of 1h.

The more continuously we run the product build, the better. I was never satisfied with maintaining two builds, especially considering that all our pain comes from the one that runs once a day only. Once we decide to go for a single product build, we should invest all we have into making it faster, like we always have done. This is aligned with @alexdima's optimization explorations.

Then, there is the unavoidable truth that errors will happen: be that npm, terrapin, cosmosdb, storage, codesign, notarization, tests, etc. Currently, a retrigger is really costly: you might have to wait another hour or so. We should look into chopping up jobs, even if at the added overhead cost, which is real. This is aligned with @lszomoru's exploration into splitting up the tests.

Finally there is (the unrelated) DevOps vs GitHub Actions situation. I would not like this to muddle our vision. I am not convinced that moving to GA will address anything we've discussed so far. I haven't seen any indication that running builds on GA is more performant or reliable that DevOps... so I wonder if moving the GA is really critical right now. Is it something that's coming our way? Yes. Is it something that will address our current issues? I don't think so. Besides, there's what @lszomoru just mentioned: not all tasks that we depend on are currently available on GA.

**Comment by lszomoru** [comment]
>But I think we're missing the target here. The duration of the continuous build was never the problem. It's not like today people are often idle waiting for that build to turn green or red. It's the fact that the build doesn't catch everything.
>
>IMO, the frustrations are:
>
>1. Most of the problems are only caught once every 24h in the product build.
>2. Build jobs are too coarse, so retriggering them can take upwards of 1h.
>
>The more continuously we run the product build, the better. 

I do not think that our explorations are missing the target. In order to be able to run the production build continuously (arguably on each commit, or on a batch of commits), we need to make sure that the build completes in reasonable time otherwise we will just build up a queue that we will never be able to clear.

As far as the overhead of running tests suites in their own jobs, I was able to run the browser unit tests in a separate job and the overhead was roughly 60 seconds. This is how much it took to check out the repository, download the build artifacts and install the node modules needed to run the tests.

**Comment by joaomoreno** [comment]
Let's close this!
