### ISSUE TITLE
Visual Studio Codespaces extensions is installed but doesn't show up in extension view

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#112201]
RE: https://github.com/microsoft/vscode/issues/112200#issue-760957030

> I also for some reason seem to have 2 Codespaces items in the dropdown:
>
> ![image](https://user-images.githubusercontent.com/641685/101730498-1eb3df80-3a88-11eb-8bd7-6947e8640189.png)
>
>The GitHub Codespaces one works, while the other wants me to sign in via the Azure account extension (which isn't installed)

I searched the "Local - Installed" extensions view for the "Visual Studio Codespaces" extension, but it doesn't show up 

![image](https://user-images.githubusercontent.com/641685/101730853-c16c5e00-3a88-11eb-870e-56e6add77a84.png)

Nor does it show up in the "Codespaces - Installed" extension view:

![image](https://user-images.githubusercontent.com/641685/101730976-f1b3fc80-3a88-11eb-9313-608792c896f7.png)

But if I search for "Codespace" I see:

![image](https://user-images.githubusercontent.com/641685/101731066-10b28e80-3a89-11eb-89a6-d8c55002ab56.png)

And I can't uninstall it

![image](https://user-images.githubusercontent.com/641685/101731165-38095b80-3a89-11eb-98d1-88353b464fb5.png)

**Comment by sandy081** [comment]
This is because, Codespaces installed this extension in remote (codespace server) as a built in extension. So you should
 see this in your builtin extensions view and hence it cannot be uninstalled. Since you connected to this Codepsace from desktop this extension has to be installed locally to run.

**Comment by eamodio** [comment]
@sandy081 so is this because that codespaces was older or something - that the old Visual Studio Codespaces extension was installed and not GitHub Codespaces? That still seems like a bug or something wrong to me

**Comment by sandy081** [comment]
I do not think this is anything to do with older/newer codespaces extension. 

- You might have created this codespace from web.
- Codespaces installs default extensions (Codespaces extension is one of these) as builtin extensions in web.
- These extensions are unzipped on the sever's extensions folder. 
- When you connected to this codepsace from desktop all server installed extensions will be available/enabled.
- Since Codespace extension that is installed on server is UI and builtin extension
  - This is not enabled on Desktop
  - This is shown in builtin extensions view
  - Since it is builtin extension, you cannot uninstall it.
