### ISSUE TITLE
Web: Merge main menu and home menu into one

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#112237]
## Summary
This is to capture the ideas around improving the web navigation menu (i.e. Codespaces). Currently, we have two navigation menu items: 

One to navigate going back (and open in VS code soon) and another to navigate the VS Code menu:

<img height="300" src="https://user-images.githubusercontent.com/35271042/101813957-43cd4000-3ad2-11eb-8f30-c05db37e0ad5.png"> <img height="300" src="https://user-images.githubusercontent.com/35271042/101813974-4a5bb780-3ad2-11eb-881d-90c7def07506.png">

The problem that this introduces is the user has to stop and think which menu to use and it also adds more items to the activity (which adds visual noise).

## Exploration

One idea is to combine these two items into a single menu. We also discussed showing an indicator on the main menu item to better indicate that a menu would appear.

<img height="700" src="https://user-images.githubusercontent.com/35271042/101814637-454b3800-3ad3-11eb-8d6c-9eab6dcc9571.gif">

## Open Questions
- Should the `>` indicator appear for settings + accounts?
- Should the `>` indicator appear on hover for the activity bar or only when you hover over the item?

**Comment by bpasero** [comment]
One thing worth mentioning is that I think we allow the "compact" menu also in VSCode native:

![image](https://user-images.githubusercontent.com/900690/101876347-8fdcbb00-3b8c-11eb-8dc3-c19c228380ae.png)

So I wonder if this change should be web only and we need to preserve the current behaviour for desktop.

//cc @sbatten

**Comment by sbatten** [comment]
yes I know there are some users who like this option everywhere but I don't know the magnitude

**Comment by eamodio** [comment]
I'm not a fan of the _Go Home_ action being at the end of the menu -- I think at least that item should be at the top, above the other menu items. Or maybe all 3 should be in a top level _Codespaces_ menu before file? Like the application menu on a mac? Or keep the the _Go Home_ first, and then have a _Codespaces_ top level menu for any additional options.

> Should the > indicator appear for settings + accounts?

My vote would be yes, but only if it only showed when you hovered over the item.

> Should the > indicator appear on hover for the activity bar or only when you hover over the item?

My vote would be to only over the item

**Comment by bpasero** [comment]
Just fyi, our current stable CS experience has "Go Home" already in the main menu as last entry:

![image](https://user-images.githubusercontent.com/900690/101978149-39867f80-3c53-11eb-90ab-c2464918f474.png)

**Comment by bpasero** [comment]
I extracted the piece about the hover feedback into https://github.com/microsoft/vscode/issues/112458 to keep this issue around merging the 2 menus.

**Comment by bpasero** [comment]
After 1on1 with @egamma there is a bit more to it depending on web vs desktop but also depending on the menu being fully visible in web or not.

**Desktop**
We currently do not really have a good product icon for the home indicator on desktop because that was not a use case so far. So I wonder if on desktop we should keep the current hamburger icon and only change this for web. I am fine either way.

**Web**
As a user you can decide to fully show the menu above the editor or not, currently the default is to show the menu in the activity bar but we might conduct an experiment with users to test our experience and decide on the default.

If the menu is inside activity bar:
* the hamburger menu and home menu merge into one
* the hamburger menu get's the icon of the home indicator
* the home indicator menu entries (Go Home, Open in VSCode...) appear after the last entry of the main menu

If the menu is on top of editor:
* the home indicator should appear to the left of the "File" menu with the entries (Go Home, Open in VSCode...)

@sbatten since this touches a lot on the menu code, I feel you are the right owner of this task, as such assigning you as well.
