### ISSUE TITLE
Define Launch.json based on file type

### ISSUE THREAD

**Issue by dimkk** [Microsoft/vscode#1122]
For single file, or, may be auto add settings based on files in project
Like:
if js - node
if ps1 - powershell

and so on

**Comment by egamma** [comment]
@weinand fyi

**Comment by weinand** [comment]
@dimkk I would love to hear more details about the scenario behind your suggestion.
Thanks!

**Comment by dimkk** [comment]
@weinand @egamma  Hello, I will consider scenarios a bit later, thanks for fast reply and thank you for your amazing job!

**Comment by wgjohnson** [comment]
I was about to create a new issue, but I think it's better to piggy back on this one.

As a scenario, I have multiple projects in Go, and instead of rewriting my launch.json every time I open Debug for the first time , I'd like to reuse the same or similar settings between workspaces (whereas a 'project' or a 'workspace' is the relative top level directory open in VS Code).

**Comment by weinand** [comment]
If no launch.json exists, VS Code let's user select a "debug environment" and creates initial launch configs based on this. In addition it is possible to add more launch configurations (for different debug environments) to this launch.json.

Since this feature request is rather old and the promised additional info was never provided, I'll close it.
