### ISSUE TITLE
Ctrl-E doesn't work as expected once you resize the window

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#11236]
Testing #11127

VSCode Version: 1.5.0-Insiders
OS Version: OSX
Steps to Reproduce:

1. Open a file whose content is more than 1 page long
2. Run ctrl-e on the second line. It works as charm.
3. Use mouse to resize the window.
4. Repeat Step 2. The line does scrolling downwards but less than 1 line.

**Comment by sandy081** [comment]
@rebornix Please see the attached video, I run ctrl-e multiple times after resizing the window multiple times and it works as expected. Is there a specific scenario which is not working?

![aug-30-2016 21-01-44](https://cloud.githubusercontent.com/assets/10746682/18103006/1dbbd636-6ef5-11e6-9c73-52b3c4877165.gif)

**Comment by rebornix** [comment]
@sandy081 this is really uneasy to repro. Please take a look at below gif, first time `ctrl-e` on second line works perfectly, but next time I move the cursor to second line again, `ctrl-e` will only move the cursor slightly.

![ctrle](https://cloud.githubusercontent.com/assets/876920/18106146/3ef033c6-6eb7-11e6-866b-64017c9781cf.gif)

I'm launching the debugger from master bits of the sample.

**Comment by rebornix** [comment]
Another thing that blocks me is `ctrl-e` doesn't scroll one full line each time with VSCodeVim even though I disable any possible (IMO) side effect, which makes the numeric prefix not reliable right now.

**Comment by rebornix** [comment]
@sandy081 I've created a fresh new extension to call those commands you provide and they work well. Then I think most failing issues should be caused by the design or implementation of VSCodeVim.

These two issues I opened here are all tested against your example code.

**Comment by sandy081** [comment]
@rebornix Scroll up or down by one line reveals the top or bottom line completely if they are partially visible (=> even if one pixel of the line is hidden). This is good because, user want to see the complete border lines while scrolling. Hence, you are seeing this only some times.

 Internally, we get the view port with completely visible lines and scroll to the next line. Hence, you might see a very little to small movement in those cases where border lines are partially visible. This sets the screen top/bottom to completely visible lines. After that, scroll up or down moves window one complete line. (If this is not the case, then this is an issue. Let me know.)

This is as expected.
