### ISSUE TITLE
Build: Linux, avoid rebuilding node modules

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#112320]
https://github.com/microsoft/vscode/blob/d819caf1d27650eb1171657339ffe68726c7a5af/build/azure-pipelines/linux/product-build-linux.yml#L112-L120

Is there any way we can avoid rebuilding these, as we're looking into cutting down build times? Can we try to compile them correctly the first time around? What's the issue here?

**Comment by deepak1556** [comment]
This is based on the GLIBCXX support difference between desktop and remote.

Our linux x64 production build container is now based on ubuntu-18.04, previously it was ubuntu-14.04. In 18.04 the default gcc version is 7 and when our native modules are compiled against this version they will require a minimum 3.4.22 GLIBCXX abi, this broke some remote scenarios where users were using Ubuntu 16 or Centos 7 or debian jessie.

After multiple solution attempts, the final version I have landed is to use gcc 4.8 for compiling remote native modules which will require 3.4.19 as minimum abi requirement and will run on the above distros.

The reason I can't use older gcc for desktop is that, v8 version in desktop 8.7 uses c++14 or c++17 standards that are not supported by gcc-4.8. While in remote environment the v8 version is 7.8 which only uses c++11 standards, hence the fix was possible. I was able to go down to gcc-5 for desktop which should keep support for ubuntu-16 and similar distros but definitely not Centos 7 and jessie on desktop.

So for now I am using gcc-5 for desktop and gcc-4.8 in remote hence this rebuild step had to done because our yarn is one single step for all folders.

**Comment by joaomoreno** [comment]
Could we maybe inject this environment somewhere around here?

https://github.com/microsoft/vscode/blob/908503ee891757c8f46e4528657c740249df49ff/build/npm/postinstall.js#L37-L37

That way we avoid compiling the `remote` dependencies twice.

**Comment by joaomoreno** [comment]
PR: https://github.com/microsoft/vscode/pull/112644

Waiting for the build results.
