### ISSUE TITLE
Flaky integration test: Terminal window.onDidWriteTerminalData should listen to all future terminal data events

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#112446]
See https://github.com/microsoft/vscode/runs/1548949834#step:10:392

```
  1) vscode API - terminal Terminal window.onDidWriteTerminalData should listen to all future terminal data events:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
      at listOnTimeout (internal/timers.js:549:17)
      at processTimers (internal/timers.js:492:7)
```

**Comment by alexr00** [comment]
Hit again: https://dev.azure.com/vscode/VSCode/_build/results?buildId=59984&view=logs&j=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&t=3bac50a7-8823-5ee7-170b-03223d1bbab7

**Comment by jramsay** [comment]
@Tyriar, @meganrogge: 

Live Share's Shared Terminal is no longer working on MacOS Big Sur (using VS Code stable 1.52.1)
https://github.com/MicrosoftDocs/live-share/issues/4035

The issue occurs when sharing an existing terminal window, one that the host creates by clicking on New Terminal (+) from the VS Code's Terminal pane. 

I've debugged and can see onDidWriteTerminalData isn't raised when input is typed in the newly created terminal. It appears to only pick up the events in the first terminal. Every time a new host terminal is created Live Share listens for input from this terminal and forwards it to the guest:

vscode.window.onDidWriteTerminalData((e) => {
                                if (e.terminal === terminal) {
                                    const s = e.data;
                                    writeDataQueue = writeDataQueue.then(
                                        async () => {
                                            await socket.write(s);
                                        });
                                }
                            }, 
                            null /* this */, 
                            registrations); 

Do you think this is due to the same issue filed above? Or would you rather I create a new issue to track this?

Note: everything is working as expected on Windows so this appears to only be an issue on MacOS (Big Sur)

FYI: @lostintangent

**Comment by alexdima** [comment]
Just saw these tests fail again today, on Windows: https://dev.azure.com/vscode/VSCode/_build/results?buildId=61153&view=logs&j=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&t=e5339641-12bd-5520-314f-0b8fa6bdcd9f&l=366

**Comment by alexdima** [comment]
Just happened again on Windows: https://dev.azure.com/vscode/VSCode/_build/results?buildId=61188&view=logs&j=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&t=e5339641-12bd-5520-314f-0b8fa6bdcd9f&l=360

```
173 passing (48s)
14 pending
11 failing
  1) vscode API - terminal
  2) vscode API - terminal
  3) vscode API - terminal
  4) vscode API - terminal
  5) vscode API - terminal
  6) vscode API - terminal
  7) vscode API - terminal
  8) vscode API - terminal
  9) vscode API - terminal
  10) vscode API - terminal
  11) vscode API - terminal
```

**Comment by alexdima** [comment]
Happened again on Windows: https://dev.azure.com/monacotools/Monaco/_build/results?buildId=99439&view=logs&j=672276a2-8d3a-5fab-615d-090c51352f92&t=821d316a-2fa3-581f-c34c-57a961b8e328&l=1625

**Comment by alexdima** [comment]
And again on Windows: https://dev.azure.com/vscode/VSCode/_build/results?buildId=61397&view=logs&j=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&t=e5339641-12bd-5520-314f-0b8fa6bdcd9f&l=1466
