### ISSUE TITLE
GUI color is too bright and contrast

### ISSUE THREAD

**Issue by bao007fei** [microsoft/vscode#112462]
Issue Type: <b>Bug</b>

All themes are too bright and contrast compare to their official presentation. Especially dark themes. Texts are too bright and backgrounds are too dark. Which causes eye strain.

*left is mine, right is official page*
![image](https://user-images.githubusercontent.com/24863266/102078204-7ade8100-3e45-11eb-92be-3169589cfcc2.png)

VS Code version: Code 1.52.0 (940b5f4bb5fa47866a54529ed759d95d09ee80be, 2020-12-10T22:45:11.850Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 1700 Eight-Core Processor           (16 x 2994)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (6.37GB free)|
|Process Argv|--crash-reporter-id 3041e817-c138-4619-b4c0-4f53cfecac83|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2020.11.371526539
vscode-pylance|ms-|2020.12.2
jupyter|ms-|2020.12.414227025

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492cf:30211402
wsl2prompt:30224612
pythonvsdeb440:30233463
unusedprompt:30224610
folderexplorer:30224614
openfilemenu:30224647
pythonvsded773cf:30233462
vsjup459cf:30229594

```

</details>

**Comment by misolori** [comment]
The website uses a screenshot of the product, so it's not going to look identical to the one on your computer due to a variety of factors (monitor, color profile, etc.). You can [browse through the marketplace](https://marketplace.visualstudio.com/search?target=VSCode&category=Themes&sortBy=Installs) to find a theme that best suits your preference or you can try tweaking the [color theme](https://code.visualstudio.com/api/references/theme-color). 

I will close this as as-designed since this is intended.
