### ISSUE TITLE
Make an option of disabling v1.52 new feature - little menu that appears during selection.

### ISSUE THREAD

**Issue by oltodosel** [microsoft/vscode#112471]
In the v1.52 when selecting a word with enabled highlighting of the same ones, this little menu (screenshot below) appears for a few seconds. I want an option of not having it appear at all. It is distracting.

It appears only when there was selected one of the options in find (regex/match case/match whole word).

![2020-12-14-151453_1920x1080_scrot](https://user-images.githubusercontent.com/10230453/102085616-9040b480-3e1f-11eb-9407-3ea05a01dabe.png)

**Comment by ArturoDent** [comment]
I was going to ask to have the time it stays on-screen longer.   The highlighting of find matches is affected by those settings.  If you are not aware of the current settings - whole word/case - because the Find Widget is not open, then you might get highlighting matches that you don't expect.  So I see that little menu as a reminder and chance to change those Find options. 

  In your text, highlighting `his` or `His` could give different results if the match case option was/was not selected.  I don't think another setting just to eliminate that pop-up is worth it - and what would the default be, `off`?  Most people probably would never discover the setting.

**Comment by johndiiorio** [comment]
I also find this little menu distracting. Selection is very common, so the menu is constantly appearing and disappearing. When selecting a word in vscode, I view other highlighted matches as more of a "hint". To actually step through the matches, I'd use the find widget. A setting to hide this and always use the find widget settings would be great. Alternatively, perhaps this menu could be moved somewhere else like the bottom status bar?

**Comment by oltodosel** [comment]
@ArturoDent, it can be `on` by default. I don't care as long as there's going to be an option of turning it off. The menu flickering each time I select something grits on my nerves and I personally don't need it at all. As @johndiiorio said, highlighting of a selection is more of a hint. Otherwise I'd use find-widget.

**Comment by ArturoDent** [comment]
I have no problem with it `on` by default.  Otherwise, if the options don't show, I don't know that anyone would go looking for a setting to make them show.
