### ISSUE TITLE
Integrated Terminal: After clearing screen, scroll up shows previous output

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#11249]
Testing #11134

- VSCode Version: 1.5.0-insider
- OS Version: Windows 10

Steps to Reproduce:

1. Open an integrated terminal and execute a command that gives an output. Example: `dir`
2. Now clear the screen using `cls`

Expected: The screen clears up and you can't scroll up anymore
Actual:     The screen does clear up. But you can scroll up to find the previous output

In an external terminal, there is no scrolling up after `cls`

**Comment by rmunn** [comment]
Note that on Linux, the expected behavior is that you *can* scroll up after clearing the terminal screen. (I believe it's the same on OS X, though I don't have a Mac handy to check this). So if you change the Integrated Terminal behavior to match Windows, you'll be breaking the expectations of Linux users (and, I think, OS X users as well).

Since the two operating systems work differently, perhaps a configuration option is necessary so that both sets of users (Windows and Linux/OS X) can have their "normal" expectations met.

**Comment by Tyriar** [comment]
The clear behavior is to be revised upstream, tracking that in https://github.com/sourcelair/xterm.js/issues/106
