### ISSUE TITLE
TreeView extension no longer shows the horizontal scrolling blue bar at the top of the screen when busy

### ISSUE THREAD

**Issue by davidkjackson54** [microsoft/vscode#112592]
I have a Treeview Explorer extension. Previously VSCode would display the scrolling blue bar at the top of the screen when activity is taking place - plus the icon down the left side would show a small blue clock. 
The small blue clock remains over the icon  but I have noticed this past couple of days that the scrolling blue bar at the top is no longer visible. Is this as a result of the new VSCode 1.52.0?  

- VSCode Version:  1.52.0
- OS Version: Windows 10

**Comment by alexr00** [comment]
I'm not able to repro this. This is version 1.52, and it shows an extension contributed view (the "Loading..." is coming from the extension). The loading bar starts and stops a couple times because of actions the extension is taking, but the bar is still there.
![recording (32)](https://user-images.githubusercontent.com/38270282/102328387-4c68bf00-3f87-11eb-91cd-8f2969dbcd97.gif)

**Comment by davidkjackson54** [comment]
How is the blue bar enabled?  It is not under control of the extension. So how might it have now stopped being displayed?    If it is not under control of the extension, then I can't fix it!

**Comment by davidkjackson54** [comment]
I can recreate this at will and I have recreated it using another Tree Explorer extension (not mine).
Here is my screen print of my recreation.
![test](https://user-images.githubusercontent.com/46171060/102376730-c3e32200-3f78-11eb-8444-15629243b5f7.gif)
