### ISSUE TITLE
Setting to disable collapsing identical lines in Debug Console

### ISSUE THREAD

**Issue by papyjoe** [microsoft/vscode#112540]
I think it would be useful to be able to toggle off the collapsing of identical lines in the Debug Console .
[Here is my problem](https://stackoverflow.com/questions/65297142/output-troubles-in-debug-console-of-visual-studio-code/65297242)

**Comment by isidorn** [comment]
This is a fair feature request to add a setting, however for now I would wait for more user feedback.

Is there something common for these lines that should not be collapsed? Maybe we should collapse only line which are longer than 1 character...
I am open for ideas.

**Comment by papyjoe** [comment]
The output was a drawing. So collapsing identical lines was not a good idea to see the result of it !

**Comment by z1c0** [comment]
I'm generating ASCII art. The default behavior is quite annoying there. A setting would definitely be appreciated.

**Comment by cjandrasits** [comment]
Hi, I saw that you just recently added this feature, but I agree a toggle would be nice. 
I am also drawing some shapes in my debug output and this collapsing completely messes up the output.

I think a simple toggle would be enough - collapsing duplicate lines like introduced here #104162 or not at all - no extra rules required... 
Thanks!

**Comment by StewBC** [comment]
A big issue for me is that when you right-click Copy All in the Debug Console, it copies the collapsed line only once - the collapsed lines (i.e. the counts) are "lost" when you paste and that's very undesirable, and I would go so far as to say just wrong, since it makes no mention of the number of times a line was writtent to the console - so that information after the paste is truly lost/missing.

A toggle to turn off collapsing repeated lines would of course solve this issue and is probably easier/more desirable than unrolling the copied lines into the paste buffer or adding the count into the paste buffer.

I rely on all lines being present after paste (I can run the application in a terminal and catch the output but it was much nicer before when I could do it all in the VS Code UI).

**Comment by isidorn** [comment]
I pushed a fix for the Copy All.
As for the setting I am open to add it in the future. However waiting for more user feedback right now.

**Comment by cjandrasits** [comment]
So are these comments the user feedback you are waiting for or do I need to give this feedback somewhere else? :)

**Comment by naletups** [comment]
In most cases, the collapsing is helpful. However, my unit test outputs get collapsed strangely with the new feature. Without it, I was quickly able to determine what part of my code base caused a failing unit test (instead of a "." I see an "F"). Now it's just some unintelligible output and I have to go through the details to find the culprit.

**Comment by musiKk** [comment]
I don't like it. Please add an option to disable it.

To me it makes the output visually harder to scan. ("I expected three lines here, why is it only... oh right.")

Plus in the current implementation the collapsed lines are shifted to the right (by three full character widths) which messes up all sorts of outputs that rely on correct placement of characters. We use constant width characters in terminals for a reason. But even if there were a margin I still would like to have the option to disable it.

**Comment by isidorn** [comment]
I have added the following setting `debug.console.collapseIdenticalLines` with the default value `true`.
Try it out with VS Code insiders starting on Friday and let me know how it works for you.
This will only be available in VS Code stable in 5 weeks.

**Comment by weinand** [comment]
@isidorn what happens for those users that don't have the new `debug.console.collapseIdenticalLines` setting?

If (for backward compatibility) a missing setting means "do collapse lines", that would break our rule that missing settings should have the same meaning as the value `false`.
In this case I suggest to invert the setting to `debug.console.doNotCollapseIdenticalLines` or `debug.console.ExpandIdenticalLines` or `debug.console.keepIdenticalLines` or `debug.console.showIdenticalLines`.

**Comment by isidorn** [comment]
@weinand thanks for the suggestion.
I went with the current approach because our rule of "missing settings should have the same meaning as false" is only applied in the debug adapter protocol. This is actually not true for VS Code configurations, where we have many settings which have the value `true` even if not present. I guess the motivation for this is implementaion detail since the `configurationService` nicely handles all this and give the correct default value always.

With that in mind I have absolutely no problem inverting the setting name.
From your proposals, I like the `debug.console.expandIdenticalLines` the most.

Let me know what you prefer. Thanks

**Comment by weinand** [comment]
No, I don't want to change the name unnecessarily.
I just wanted to make sure that we do not break users.

**Comment by isidorn** [comment]
Okey. We will not break users, so we are good. Let's stick with the `debug.console.collapseIdenticalLines` setting name then.

**Comment by atom0s** [comment]
> Try it out with VS Code insiders starting on Friday and let me know how it works for you.

Looks to be working good for me, just came here to look for the same suggestion as I needed it disabled.
