### ISSUE TITLE
vscode.Uri.parse does not work for urls with %2F

### ISSUE THREAD

**Issue by alonstern** [microsoft/vscode#112577]
- VSCode Version: 1.51.1
- OS Version: Mac

I am using `vscode.env.openExternal` and `vscode.Uri.parse` to open external URL in the browser.
My problem is that my URL contains '%2F' (which is the escaped value of '/') in its path (e.g., something like https://aaa/bbb%2Fccc).
It seems the Uri.parse unescapes the URL and than escape it again in openExternal, however:
```
unescape('https://aaa/bbb%2Fccc') // https://aaa/bbb/ccc
escape('https://aaa/bbb/ccc') // https://aaa/bbb/ccc
```
(Assuming the builtins unescape and escape are used)
And thus, it removed the escaping of '%2F' and opening the wrong page in the browser.

Thanks

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment]
Yes, this is the unfortunate truth. You will find some duplicates of this issue and honest, good attempts in fixing them which we all had to revert because too many extensions depends on the current, broken behaviour. It is a mess and unfortunately too late to properly fix. The current strategy is to allow string in addition to `Uri` in some places. See https://github.com/microsoft/vscode/issues/85930 and issues linked from there

**Comment by alonstern** [comment]
@jrieken thanks for the answer.
I think even adding an "escape" flag to the parse function which its default is true, or creating a new fixed URI type, to avoid breaking to current behavior would be a major improvement.
