### ISSUE TITLE
Emmet abbreviations are not working in .scss files

### ISSUE THREAD

**Issue by yuvalsabar** [microsoft/vscode#112675]
Emmet abbreviations are not showing in SCSS (it works and regular css files).

- VSCode Version: 1.52.0, portable version
- OS Version: Windows 10

Steps to Reproduce:

1. Open scss file
2. type m:a (for example) - there is no emmet abbreviation (should be margin: auto)

Does this issue occur when all extensions are disabled?: Yes

**Comment by rzhao271** [comment]
I noticed when typing `m:` in a CSS file, there's _no_ suggestions after the `:` is typed, and then typing `a` allows for `margin: auto;` to be recommended by Emmet.

But for SCSS, for `m:a`, after the `:` is typed, several suggestions show up, and then typing `a` results in filtering down those suggestions to `abs()` and `append()`.

This might have to do with the CompletionItemProvider

**Comment by cpmsmith** [comment]
This happens in Less as well. 

> However, if one presses backspace and then types a again, the Emmet abbreviation is suggested.

Interestingly, I haven't found this. If I hit <kbd>esc</kbd>, clearing the typeahead suggestions, and start typing again, the Emmet suggestion will be included when it shows up again. Similarly, if I type a second `a` and get `m:aa`, filtering out `abs()` and `append()` from the suggestions so that none remain, and backspace, Emmet is included when the suggestions show up again.

**Comment by abhijeet75** [comment]
I am looking into this issue. I have been able to repro this in less and scss files.

**Comment by abhijeet75** [comment]
Update:
`defaultCompletionProvider::provideCompletionItems` from `emmet\src` is returning correct emmet abbreviations when we enter `m:a` in less and scss files as well.
But `provideCompletionItems` from `css-language-features\node-modules\vscode-languageclient\lib\common\client.js` also returns suggestions such as `abs()` and `append()` for less and scss files, while it does not return any suggestions for css files.

**Comment by abhijeet75** [comment]
Looks like this is an issue with `css-language-features` extension. When I disable that extension, emmet abbreviations start showing-up. Need to debug `css-language-service` to understand more.

**Comment by rzhao271** [comment]
@aeschli any ideas on what a workaround could be here? While typing `m:a` into an SCSS file, typing the `:` results in suggestions already, but I want that when a user types `a`, more suggestions are added on. Right now, the `a` only acts as a filter.

**Comment by aeschli** [comment]
@rzhao271 Your completion processor is called every time (as it's marked as 'incomplete'), so that works., It returns a proposal every time

![image](https://user-images.githubusercontent.com/6461412/109487344-61cc9000-7a84-11eb-8e7d-e6c50a9e7291.png)

But after the ':', the proposal is filtered our as the filter string `m1` does not match against the current word prefix `m1:`

-> You need to set the filter to `m1:` for the proposal to be visible

**Comment by jeanp413** [comment]
Created https://github.com/microsoft/vscode-emmet-helper/pull/61 and https://github.com/microsoft/vscode/pull/118666 fixing this
