### ISSUE TITLE
suggest insert mode: enter for insert, tab for replace

### ISSUE THREAD

**Issue by ryenus** [microsoft/vscode#112613]
Currently `editor.suggest.insertMode` allows one to choose one of `insert` or `replace`. 

What about having both, like using enter for insert, and tab for replace.

**Comment by ryenus** [comment]
Related issues:
* https://github.com/microsoft/vscode/issues/4878
* https://github.com/microsoft/vscode/issues/91657

**Comment by jrieken** [comment]
This feature already exists, the `editor.suggest.insertMode` only defines the default but you choose between insert/replace (assuming the completion supports both ways). 

<img width="531" alt="Screenshot 2020-12-16 at 09 09 49" src="https://user-images.githubusercontent.com/1794099/102321935-a2853480-3f7e-11eb-86bd-1eed4381d16a.png">

**Comment by ryenus** [comment]
Hi, @jrieken,

The current implementation, per my understanding, is that `Tab` and `Enter` would do the same thing, whether they're configured to insert or replace, then you use `Shift + Enter` for the non-default action.

The proposed behavior, or the way how this is implemented in other popular tools, such as JetBrains IDE(s), is that `Tab` and `Enter` have **different** behaviors, with default settings, `Tab` performs **replace**, and `Enter` performs **insert**.

It's a bit surprising that vscode just implemented this a bit differently, but apparently the two can co-exist.

**Comment by jrieken** [comment]
> It's a bit surprising that vscode just implemented this a bit differently, but apparently the two can co-exist.

Well, we didn't have insert modes for the longest time but since ever `Tab` and `Enter` do the same thing. When I implemented insert modes I didn't want to change the default behaviour for our 10MM+ users because such changes usually cause massive backslashes. That's why there is the `Shift` variant for the non-default action. 

I can understand how that is confusing or expected when coming from another IDE. I think our answer to that is to 

1. customise your keybindings 
2. get a keymap extension (https://marketplace.visualstudio.com/search?target=VSCode&category=Keymaps&sortBy=Installs)

**Comment by ryenus** [comment]
Thanks for the tip @jrieken, I figured that adding the following to my **keybindings.json** worked:

```json
  {
    "key": "tab",
    "command": "acceptSelectedSuggestion",
    "when": "suggestWidgetVisible && textInputFocus"
  },
  {
    "key": "enter",
    "command": "acceptAlternativeSelectedSuggestion",
    "when": "suggestWidgetVisible && textInputFocus"
  },
```
