### ISSUE TITLE
Git conflict terminology

### ISSUE THREAD

**Issue by john-aws** [microsoft/vscode#112600]
Request: I'd like to propose that VS Code change the merge terminology from  'Accept Current Change' and 'Accept Incoming Change'. The terminology is confusing and can easily be read backwards. I know that you have grayed hints alongside the chevrons (possibly for exactly this reason).

Problem: After a `git pull --rebase --autostash`, VS Code may show merge conflicts. These conflicts appear in VS Code with a helpful banner offering 'Accept Current Change' and 'Accept Incoming Change'. An 'incoming' change is actually the change that you have made locally (which you might think of as _current_), and the 'current' change is the one that has just been pulled from the repo onto your local working copy (which you might think of as _incoming_). Neither is a very good description of what's going to happen.

**Comment by chrmarti** [comment]
I think with rebase it ends up being reversed because Git reapplies your "current" changes (therefore labelling them as incoming) on top of the "incoming" changes on the branch that it just fast-forwarded to (therefore labelling them as current).

When you merge, the labels should make more sense. We don't know the context of the merge conflict, so we can't change the labels case by case.
