### ISSUE TITLE
Add command to reveal current cursor in center

### ISSUE THREAD

**Issue by dwilliamson** [microsoft/vscode#112665]
Please see the original #95866 which was closed with a commit that did not fix the request.

As of November 2020 initial build, this still does not work:

```json
{
    "key": "ctrl+l",
    "when": "editorTextFocus",
    "command": "revealLine",
    "args": {
        "lineNumber": "${lineNumber}",
        "at": "center",
    }
}
```

To be clear: I am trying to center the view on the current cursor line, similar to the Vim `zz` command, without having to write an extension.

**Comment by alexr00** [comment]
@dwilliamson that's a keyboard shortcut, not tasks.json, so I've renamed the issue.

**Comment by alexr00** [comment]
@alexdima I don't know if keyboard shortcuts support variable resolving by default, but individual commands certainly can if they want. 

I see a couple feature requests:
- Support variable resolving in all keyboard shortcuts.
- or, support variable resolving in the `revealLine` command
- Allow the `lineNumber` argument to be a string, since variable resolving can only produce strings.

**Comment by marblewraith** [comment]
@dwilliamson I ran into the same problem. Trying to replicate vim viewport scroll (`zz`, `zt`, `zb`) without installing an entire *vim keymap.

For now my workaround is to use the [Commands extension](https://marketplace.visualstudio.com/items?itemName=usernamehw.commands), and put the following in `settings.json`:

```JSONC
"editor.cursorSurroundingLines": 2,
"commands.variableSubstitutionEnabled": true,
"commands.commands": {
  "Viewport.scrollTop": {
    "command": "revealLine",
    "args": {
      "lineNumber": "${lineNumber}",
      "at": "top",
    }
  },
  "Viewport.scrollCenter": {
    "command": "revealLine",
    "args": {
      "lineNumber": "${lineNumber}",
      "at": "center",
    }
  },
  "Viewport.scrollBottom": {
    "command": "revealLine",
    "args": {
      "lineNumber": "${lineNumber}",
      "at": "bottom",
    }
  },
},
```

You can then bind it to whatever keys you want like this:

```JSON
{
    "key": "alt+t",
    "command": "Viewport.scrollTop",
    "when": "editorTextFocus"
  },
  {
    "key": "alt+m",
    "command": "Viewport.scrollCenter",
    "when": "editorTextFocus"
  },
  {
    "key": "alt+b",
    "command": "Viewport.scrollBottom",
    "when": "editorTextFocus"
  }
```

_Note: `"editor.cursorSurroundingLines"` should be set to at least 1 (default value 0) because otherwise the cursor will scroll off the screen_
