### ISSUE TITLE
Format Code issue

### ISSUE THREAD

**Issue by horne3754sg** [Microsoft/vscode#11267]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 10.0.14393

Steps to Reproduce:

1. I have some HTML in a form like this.

```
<form action="">
    <div class="form-group"><label for="firstName">First Name</label><input id="firstName" type="text" class="form-control"></div>
</form>
```

2. When I press **Alt** + **Shift** + **F** I would expect it to become.

```
<form action="">
    <div class="form-group">
        <label for="firstName">First Name</label>
        <input id="firstName" type="text" class="form-control">
    </div>
</form>
```

However nothing seems to happen.

If I have 

`<div><div><div><span></span></div></div></div>`

and do the same thing it will format as expected.

```
<div>
    <div>
        <div><span></span></div>
    </div>
</div>
```

My settings are default.

Its a minor issue, but it does break workflow slightly when Zen coding since Zen coding doesn't format the code. 

Regards

**Comment by aeschli** [comment]
You have to check out the '"html.format.unformatted"' setting.
`label` and `input` are part of the 'unformatted' list That's why they are not put on separate lines.

BTW, we use the html formatter from https://github.com/beautify-web/js-beautify. Please file issues there if you find bugs in the formatter.
