### ISSUE TITLE
Enable copying of individual stack frames in "Call Stack" view

### ISSUE THREAD

**Issue by mnovakovic** [microsoft/vscode#112688]
Currently I can "Copy Call Stack" when I right-click on a frame or anywhere in the "Call Stack" view. It'd be great to add an ability to copy an individual stack frame, or even a function name/file name corresponding to the selected frame.

**Comment by isidorn** [comment]
This request makes sense however we have no immediate plans to add it since I think an extension can add this as well, here's how it would work:
1) CALL STACK view can be contributed to, thus an extension needs to add an action "Copy Stack Frame" to `debug/callstack/context`
2) The extension would get as an argument a context which would idenity the stack frame
3) Bases on that context the extension can write into the clipboard

This is a rough sketch, there might be things missing...
