### ISSUE TITLE
Show a "Reveal in Sidebar" command in the context menu of an editor

### ISSUE THREAD

**Issue by kenken023** [Microsoft/vscode#11273]
- VSCode Version: Version 1.4.0 (1.4.0)
- OS Version: OS X El Capitan 10.11.4

Steps to Reproduce:
1. Open a file
2. Right click on the file content and select "reveal in sidebar" (file explorer)

**Comment by bpasero** [comment]
File: Show Active File in Explorer (from the command palette)

**Comment by kenken023** [comment]
Is it possible to add it to the right click options?

**Comment by bpasero** [comment]
@kenken023 right click where? on a tab?

**Comment by kenken023** [comment]
![screen shot 2016-08-31 at 4 43 35 pm](https://cloud.githubusercontent.com/assets/3609248/18122058/34de1720-6f9a-11e6-814c-29f03b3a3c0f.png)

Please see attached screenshot. :)
I find it very useful especially from find results. Thank you very much 👍

**Comment by bpasero** [comment]
Good candidate for an extension 👍

**Comment by alefragnani** [comment]
@bpasero I don't know if this was intentional, but there is some _limitation_ about what you can add as Context Menu items.

If you try to define new Context Menu items based on commands defined outside your extension, like in this case the _core_ command `workbench.files.action.showActiveFileInExplorer`, an error occurs and the context menu is not displayed anymore. The `Console` says `_TypeError: Cannot read property 'title' of undefined at e._compareMenuItems`_

The _Intellisense_ warns you while coding in `package.json` file, but the documentation in [Contribution Points](http://code.visualstudio.com/docs/extensionAPI/extension-points#_contributescommands) isn't clear about that. So, a new extension will be forced to _duplicate_ core commands, in order to do that.

Should this _limitation_ be updated, in order to allow this kind of customization?

**Comment by bpasero** [comment]
@alefragnani I suggest you report this as issue so that we can look into it

**Comment by alefragnani** [comment]
@bpasero wouldn't https://github.com/Microsoft/vscode/issues/9285 be a better solution in this case? I mean, the commands _already exists_ so the user should only configure where/how it is presented.

**Comment by bpasero** [comment]
Yes, also a possible solution 👍

**Comment by bpasero** [comment]
For January I pushed "Reveal in Explorer / Side Bar" to the context menu of editors (tabs).

**Comment by neoramos** [comment]
Hello,  I am making the switch to VSCode and found you can add `{
        "key": "cmd+]",
        "command": "workbench.files.action.showActiveFileInExplorer",
        "when": "editorTextFocus"
    }` to your keybindings.json.  In my case, pressing cmd+] will reveal the currently opened file in the explorer folder tree, exactly what Sublime Text does when right+click on currently opened file and clicking on "reveal in sidebar".  Hope this helps.  Neo

**Comment by monkindey** [comment]
hi, @neoramos .Thanks for your sharing.  But the `cmd+]` shortcut binding would conflict with the **Indent Line**. Maybe we can change it with `cmd+ctrl+[`?

**Comment by isidorn** [comment]
This feature request will not be considered in the next 6-12 months roadmap and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
