### ISSUE TITLE
Slow Startup Performance

### ISSUE THREAD

**Issue by douglasparker** [microsoft/vscode#112766]
VSCode has had really slow startup performance for many months now and I am not sure why.

I opened issue #111328 with full system information as well as profiling information and it was closed as a duplicate of issue #22087. However, I completely disabled Windows Defender and this is not the cause of the performance issues.

I've since completely uninstalled VSCode and deleted all directories in AppData for a fresh install. The problem still persists.

I tried reaching out to @jrieken as he was the one to close my previous issue, and I haven't heard anything in almost a month.

Hopefully this issue will help get my previous issue reopened so that this can be addressed. I know I am not the only one seeing these startup performance issues.

**Comment by jrieken** [comment]
> However, I completely disabled Windows Defender and this is not the cause of the performance issues.

We aren't that defender or other AV software is the only reason for slow startup but a potential cause. The past has shown that it is often AV software but also other software can be responsible for this. The slowness is due to a delayed appReady event. VS Code must await this event before it can do anything
