### ISSUE TITLE
Prompt before destructive Explorer undo

### ISSUE THREAD

**Issue by chindathorn** [microsoft/vscode#112706]
Issue Type: <b>Feature Request</b>

Please remove "Undo feature" (Ctrl+z) in file explorer side. I have created lots of files and when I tab from text editor to the file explorer tab side, by accidentally press Ctrl+z it undoes all my created files. so I lost a lot of codes. Sad with Ctrl+z feature in file explorer VSCode.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.18363

**Comment by isidorn** [comment]
Thanks for feedback. We will not remove it, but we might introduce a prompt.
Let's leave this open for now so other users can also chime in with their opinion.

**Comment by johnchurchill** [comment]
This (combined with #111640) is the most dangerous behavior of VS Code that I have encountered (actually, of any IDE, ever). I lost hours of uncommitted work by pressing Cmd-Z just 4 times when I thought the editor had context. It's baffling that the explorer pane has its own memoization queue so it will delete files created days earlier after numerous changes in  the editor pane. Worse, I can't even reproduce it with a fresh run, which tells me that VS code is getting its undo stack confused after hundreds of edits.

My suggestion is that the explorer pane not have any undo functionality (or make it an opt-in settings). It doesn't make sense to even try when the majority of files appear and disappear though external means (e.g. ng generate or git branch operations).

**Comment by isidorn** [comment]
Thanks to work with @alexdima we have now changed that we prompt when undoing a creation operation
We can change this to prompt in more cases if needed.
Try it out and let us know how it goes. We can also add an option "Do not show again", but let's not do this yet (since we can only nicely reset this if we introduce a setting).

fyi @jrieken in case you are interested in changes https://github.com/microsoft/vscode/commit/d427deac7800a4a6d053f1b406e3c2355630b4d6
I think it was pretty straight forward.

**Comment by isidorn** [comment]
To verify:

1. Creat a file or folder in Explorer
2. Make sure focus is in Explorer
3. Undo. Make sure you are Prompted
4. Do a bit more of undo, and make sure you are always prompted exactly once when doing a destructive undo
