### ISSUE TITLE
Move debug console icon into ... menu

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#112755]
We are moving the Debug Console action from the top of the debug viewlet to the ... actions. Reasons beings:
1. It fits there with other views
2. Not very useful while you are not debugging, and to save horizontal space
3. Debug console gets opened automatically when debugging starts
4. It is the least popular debug action from the Debug Title area.

![image](https://user-images.githubusercontent.com/1926584/102517952-f41de400-4090-11eb-92cf-6ab1d8bc0ec7.png)

**Comment by lszomoru** [comment]
I think that I have found an issue:
- Open the `microsoft\vscode` repo, and switch to the debug viewlet and confirm that the `Debug Console` is not ticked
- Press `F5` to start debugging. This gesture will automatically show the `Debug Console`, and the item in the context menu will get ticked
- Open the context menu and click on `Debug Console`.
  - `Debug Console` should get hidden and the item in the context menu is unticked. Instead nothing happens.
  - Opening the context menu, and clicking on `Debug Console` again will result in the expected behavior

**Comment by isidorn** [comment]
@lszomoru thanks. However let's close this one since we did indeed move the debug console in the `...` menu, and for your issue I have created a new one https://github.com/microsoft/vscode/issues/115110

**Comment by jeanp413** [comment]
After this change now the `Debug Console` entry in the view menu shows a check icon when the repl is visible, is this expected?
This is inconsistent compared to the other entries in the same group (Output, Terminal and Problems)
cc @isidorn 

![image](https://user-images.githubusercontent.com/25115070/106226982-661c3980-61b6-11eb-971c-0b5ade40b27d.png)

**Comment by isidorn** [comment]
@jeanp413 good catch.
We have two options, either we do not do it for Debug Console, or we do it for all the views.
I think doing it for all the views makes sense.
@sbatten @sandy081 @bpasero thoughts?

Either way what we do we should do next milestone.

**Comment by bpasero** [comment]
Sorry, someone explain the issue to me like I don't understand the context.

**Comment by isidorn** [comment]
Sorry: Debug Console shows the checkmark in the main menu. All other views do not show the checkmark when shown.

**Comment by bpasero** [comment]
@isidorn that looks inconsistent to me but also note that when I click "Explorer" 2 times, it does not show and hide. So how can it show a checkmark then?

**Comment by sandy081** [comment]
>  but also note that when I click "Explorer" 2 times, it does not show and hide. So how can it show a checkmark then?

Yes, not all view containers have same toggling action, like explorer, all other sidebar view containers and also problems view container in panel has same 3 state toggling behaviour. 

So my recommendation would be to remove the check mark and align it with others

**Comment by isidorn** [comment]
Okey, I'll remove the checkmark then, thanks

**Comment by sandy081** [comment]
@isidorn I still see the checkmark 

![image](https://user-images.githubusercontent.com/10746682/106434663-26817600-6472-11eb-9053-9cfd190e7a0c.png)

It is also causing inconsistency - Console view is visible even if checkmark is not there

![image](https://user-images.githubusercontent.com/10746682/106434773-47e26200-6472-11eb-830d-b579354cf55b.png)

**Comment by isidorn** [comment]
Yes, I planned to fix the checkmark business next milestone.
Created a new issue for that https://github.com/microsoft/vscode/issues/115521

**Comment by sandy081** [comment]
@isidorn IMO we shall be fixing this in this milestone, because

I see following buggy behaviour:

- Checkmark action is not working as checkmark action:
  - Open Debug Console
  - Focus in Editor
  - Try View > Debug Console 
  - 🐛 Checkmark is gone, but Debug console is still visible

Also it adds inconsistency in View menu actions - which we tried to fix in this milestone.

**Comment by isidorn** [comment]
Makes sense, I can look into it. Thanks

**Comment by isidorn** [comment]
Has been fixed via https://github.com/microsoft/vscode/pull/115536
