### ISSUE TITLE
feature : changes can be made in the way of uncommenting multiple comments together

### ISSUE THREAD

**Issue by Vishal19111999** [microsoft/vscode#112826]
After commenting multiple lines in react, if we try to uncomment all of them together, vs code removes the first {* and last *}, which is not ideal behavior
(check the video for reference)

<b>We can either:</b>
1> have it do nothing, or
2> uncomment all the code

https://user-images.githubusercontent.com/29145212/102638873-33762e80-417e-11eb-82d3-8d9c1203d74d.mov

**Comment by jrieken** [comment]
You can use multiple cursors for that

**Comment by ArturoDent** [comment]
See the extension [Toggle Line Comments](https://marketplace.visualstudio.com/items?itemName=ArturoDent.toggle-comments) which I recently made. I think it'll work for you.

![toggleCommentsJSX](https://user-images.githubusercontent.com/31813701/102662218-9692a180-413b-11eb-8718-82f4810e089d.gif)

I made it for this: https://stackoverflow.com/questions/60334430/reverse-toggle-commented-and-uncommented-code-at-the-same-time/65334947#65334947 but since it is toggling line-by-line it looks like it works in your case.
