### ISSUE TITLE
syntax highlighting of powershell (ps1) files

### ISSUE THREAD

**Issue by dhcgn** [Microsoft/vscode#11289]
The syntax highlighting of powershell has not working correct
- VSCode Version: 1.4.0
- OS Version: Win7Pro

Steps to Reproduce:
1.  Paste this code in vscode and save it as *.ps1

```
Add-type -assembly "Microsoft.Office.Interop.Outlook" | out-null
$olFolders = "Microsoft.Office.Interop.Outlook.olDefaultFolders" -as [type]
$outlook = new-object -comobject outlook.application
$namespace = $outlook.GetNameSpace("MAPI")
$folder = $namespace.getDefaultFolder($olFolders::olFolderInBox)
$folder.items | ?{$_.Subject -like "Lorem Ipsum*"} | 
 %{
    $regexResult = $_.HTMLBody | Select-String -Pattern "Lorem Ipsum: <b>(\d{1,})<\/b>" -AllMatches
    $numVirus =  $regexResult.Matches.Groups[1].Value

    $properties = @{
      'NumberVirus'=$numVirus;
      'Date'= $_.CreationTime
      }
    $object = New-Object –TypeName PSObject –Prop $properties
    $object
  } | Tee-Object -Variable result

  $result | Out-GridView
```
1.  You will see a few statements with none syntax highlighting. (e.g.   `} | Tee-Object -Variable result`)
   ![image](https://cloud.githubusercontent.com/assets/6566207/18122181/88a4a95a-6f68-11e6-98e4-2503b25d68b8.png)

**Comment by Bill-Stewart** [comment]
Have you tried the PowerShell extension:?

**Comment by KeeperB5** [comment]
I would like to [demonstrate difference](https://www.dropbox.com/sh/t9qppvd7smwbsg1/AABNM1dtW6cxTob-WkI8Engva?dl=0) in PowerShell syntax coloring between various editors. VS Code is by far the worst of the bunch. And this is with VSCode version 1.5.3 and PowerShell extension 0.7.2.

**Comment by daviwil** [comment]
Hey @KeeperB5, we'd love to hear your thoughts over at the https://github.com/PowerShell/EditorSyntax repo where we're trying to work on improving the syntax highlighting grammar for VS Code and Atom.

One suggestion though: If you aren't currently using the "Dark+" theme in VS Code, try that out.  It improves the syntax colorization somewhat because the theme has more colors than the default "Dark" theme.

The ISE and Visual Studio both have better PowerShell syntax highlighting than VS Code because they use the PowerShell engine's tokenizer instead of a regex-based colorizer as VS Code and Atom do.

**Comment by KeeperB5** [comment]
@daviwil VS Code is already using Dark+ theme in the VS Code image. I can certainly give more specific feedback if there is something in particular you want me to elaborate on. Looks like most common issues have already been reported in EditorSyntax issues, so I have nothing much to add there. I use PowerShell Studio at work and Visual Studio Community  at home, so VS Code doesn't get much attention from me, sorry.

**Comment by aeschli** [comment]
This issue was moved to PowerShell/EditorSyntax#63
