### ISSUE TITLE
Add "Check for Extension Updates" action/command

### ISSUE THREAD

**Issue by leaxoy** [Microsoft/vscode#11295]
In current version, you can't find ext update info or notice before vscode restart. 
And there is no such button to check extension update manually.

So it would be better to add such button to do it.

**Comment by mrmlnc** [comment]
Please, provide more details.

**Comment by joaomoreno** [comment]
Extensions are not required to publish information on their own updates, so there's not much we can show.

**Comment by jmmk** [comment]
@joaomoreno 
The way I interpret this (because I just ran into the same issue) is that it would be nice to have an option to "check for extension updates" which would see if any newer versions had been uploaded to the marketplace (I assume this is what happens on restarting VSCode?). In this case, I _knew_ that a new version was there, but VSCode did not indicate to me that I could update the extension until I closed and reopened it.

**Comment by joaomoreno** [comment]
Thanks @jmmk, I did misunderstand this at first.

**Comment by joaomoreno** [comment]
Fixed.
