### ISSUE TITLE
API for opening files in registered custom editors

### ISSUE THREAD

**Issue by donaldoakes** [microsoft/vscode#113173]
When an extension registers a custom editor, vscode automatically opens in the appropriate editor based on viewtype. However, other extensions currently have no way of doing this. It would be great if there were an API to determine the registered viewtype associated with a filename, so that it could be passed to the `vscode.openWith` command. Or another alternative would be to provide a command or API to open a file in the registered custom editor automatically (something like `workspace.openTextDocument()`, but which honors registered custom editors).

The use case for this is to open a file programmatically in the appropriate custom editor, which comes from a different extension.

**Comment by mjbvz** [comment]
You can use the `vscode.openWith` command with the id of the custom editor registered by other extensions.

No plans to expose a public api for getting all ids for a file since you usually interested in a specific editor type, not a list of all valid editors (which would only be meaningful if you know what each of the corresponding editors do)

**Comment by donaldoakes** [comment]
How about a public API to open a file with whatever custom editor happens to be registered (the same behavior as when a user opens a file by double-clicking on it)? My example is the Test Explorer extension, which opens Ply .flow files in a text editor only because it has no way of allowing it to open in the Ply custom editor.
