### ISSUE TITLE
Crashes and makes to reopen the windows when worked for over 5 hours and terminal is becoming black. (Working with CLI on terminal of VSCode).

### ISSUE THREAD

**Issue by otabekoff** [microsoft/vscode#113162]
- VSCode Version: Latest
- OS Version: Windows 10 latest enterprisee

Steps to Reproduce:

1. I opened the VSCode and begin working
2. After approximately 5 hours, the terminal of VSCode become black. Then when I tried to delete that terminal, the VSCode shows me an alert box about reopening the window. I was working VSCode inner terminal and was running a CLI. VueJS.

Does this issue occur when all extensions are disabled?: No

**Comment by meganrogge** [comment]
> Does this issue occur when all extensions are disabled?: No

Seems like an extension might be causing your issue per the above answer you provided. Can you pls run extension bisect?

**Comment by OtabekSadiridinov** [comment]
Oh yes, it was happening because of one of my extensions. IDK which extension is causing... So, I disabled all extensions. Then, I just enabled the ones I know only. And deleted the others. It was working. But, after some time it again begin to freeze and ask to reopen. I couldn't believe and even I didn't know what to do... So then, when I looked up my RAM usage VSCode was getting so much of it. 4.5GB of my 8GB RAM. Is it normal?

**Comment by OtabekSadiridinov** [comment]
![image](https://user-images.githubusercontent.com/60849894/103064118-10f87100-45d5-11eb-8ff3-8d556fd87fac.png)

**Comment by OtabekSadiridinov** [comment]
![image](https://user-images.githubusercontent.com/60849894/103064234-6b91cd00-45d5-11eb-9e11-d9326d1f3e69.png)

**Comment by deepak1556** [comment]
If you are still experiencing this issue with latest insiders, please follow these steps https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-and-symbolicating-local-crash-reports and attach the crash dump. Thanks!
