### ISSUE TITLE
Message service show action buttons in reverse order

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#11311]
- VSCode Version: 1.5

Steps:

- show a message with actions.

Observe: the actions appear in reverse order in which they are provided. We should respect the order in which the actions are passed into the function.

**Comment by dbaeumer** [comment]
@bpasero as discussed we should look into the early September.

@jrieken FYI.

**Comment by bpasero** [comment]
@dbaeumer pushed the fix and adopted all places in the workbench but each extension needs to adopt this change too now.

**Comment by jrieken** [comment]
@bpasero How about us handling that instead of asking all extensions to update?

**Comment by bpasero** [comment]
@jrieken good idea. but how can I know that an extension relied on the old way of sorting actions?

When I discussed this with @dbaeumer I raised the concern of this being a somewhat breaking change (at least breaking existing behaviour) however we then thought that the way it used to work was already broken and so with this fix the behaviour is correct (even though this means extensions with buttons > 1 show in different sorting order).

**Comment by jrieken** [comment]
> extension relied on the old way of sorting actions?

I believe it was always broken so for extensions there is no 'old way of sorting'. I believe that made me unshift the default [close action](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/node/mainThreadMessageService.ts#L52) instead of pushing - actually not really paying attention to this. So, we can do two things

* reverse actions [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/node/mainThreadMessageService.ts#L57) such that we don't introduce behavioural breakage
* push the close action such that the default close commands come last (as today)

**Comment by bpasero** [comment]
@jrieken yes, I took care of pushing the close action so that it comes last as before (see https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/node/mainThreadMessageService.ts#L52)

I can add the reverse code so that we do not end up with behavioural change but @dbaeumer filed this bug exactly for this reason. I think the API should show the buttons in the order they are being passed to the message service and this is how it behaves now. I would say the "old way of sorting" was unintuitive and forced extension writers to reverse the order on their end.

**Comment by dbaeumer** [comment]
Created bug for TS.
