### ISSUE TITLE
debug console: broken spacing

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#11321]
- VSCode Version: 1.5 insiders
- OS Version: macOS

The line spacing has changed in the latest:

![2016-08-31_17-50-21](https://cloud.githubusercontent.com/assets/1898161/18135865/a91db24a-6fa3-11e6-9722-ca2c82b944cc.png)

Here is the spacing in stable:
![2016-08-31_17-53-19](https://cloud.githubusercontent.com/assets/1898161/18135910/d1ac93b6-6fa3-11e6-96bc-acd45f0d5776.png)

**Comment by isidorn** [comment]
@roblourens this was probably introduced by your PR. Do you want to look into to (I can also fix it tomorrow morning)? I think it is not a big issue, we just need to ignore the last '\n' when spliting lines

To repro:
* clone https://github.com/Microsoft/vscode-node-debug 
* npm install 
* run tests via debug viewlet

**Comment by roblourens** [comment]
I debugged this and I see that every console.log in node produces an extra line - but the problem is that since the node adapter is listening to logs from stdout, there will be an extra newline at the end. e.g. -

`console.log('test')` produces an OutputEvent with value `'test\n'`. And `console.log('test\n')` -> `'test\n\n'`.

So I assume we should just remove the last newline here https://github.com/Microsoft/vscode-node-debug/blob/master/src/node/nodeDebug.ts#L913 but I also see [this line](https://github.com/Microsoft/vscode-node-debug/blob/master/src/node/nodeDebug.ts#L3145) that explicitly adds a newline - do you want all OutputEvents to be newline-terminated?

**Comment by isidorn** [comment]
@roblourens @weinand since we are wrapping up the release I am fine with also filtering the last new line on the vscode since we were doing that previously. Though the right fix seems to be to handle this on the node debug side imho. Since 'hello' and 'hello\n' should produce different results on the vscode side. 
@weinand let me know what you think, maybe I am missing something specified in the protocol

**Comment by weinand** [comment]
`console.log('test')` produces a '\n' at the end by definition of log():
```js
Console.prototype.log = function() {
  this._stdout.write(util.format.apply(this, arguments) + '\n');
};
```
It is **not** node-debug that introduces any characters. 

VS Code should not modify the data received through the OutputEvents in any way.
If a node program decides to use `process.stdout.write("test")` (which does not append a newline), VS Code should not add a newline on itself.

**Comment by weinand** [comment]
Here is an example that shows the difference:
```js
process.stdout.write("hello");
process.stderr.write("world");
```

Expected output from Integrated Terminal:
![2016-09-01_11-16-33](https://cloud.githubusercontent.com/assets/1898161/18162194/8dd849c2-7035-11e6-8787-dcbf3a485638.png)

Wrong output in Debug Console:
![2016-09-01_11-15-35](https://cloud.githubusercontent.com/assets/1898161/18162167/6ed80558-7035-11e6-93e0-c178bc57f7c3.png)

**Comment by isidorn** [comment]
That is not a regression so I have created a seperate issue to track this https://github.com/Microsoft/vscode/issues/11376

**Comment by roblourens** [comment]
Wanted to point this out in case you didn't notice it- I see the extra line fixed between logs, but not between logs and console input:
![image](https://cloud.githubusercontent.com/assets/323878/18182779/3cb77458-7046-11e6-9f24-69850157a552.png)

**Comment by octref** [comment]
Verified fix by building the latest from master. Here is the output for running tests in `vscode-node-debug`:

![image](https://cloud.githubusercontent.com/assets/4033249/18182955/f36093a6-7046-11e6-8909-d6c6fcc42457.png)

However, it's producing empty lines for strings much shorter than one line length, like for this line:

`✓ should stop on a breakpoint in source (all files top level, missing sourceMappingURL) (424ms)`

When the window is resized the problem is more severe.

![image](https://cloud.githubusercontent.com/assets/4033249/18183174/fefbbbe0-7047-11e6-9289-4b9e563d43e7.png)

My guess is color code like `\033[0;31m` are taken into account for counting line-width.

@isidorn 

Should I add `verified` and open this bug as a new issue?

**Comment by isidorn** [comment]
@octref yes, please add the `verified` and open the new issue. Good guess, color codes are probably the root cause fo the height measuring issue!

**Comment by joaomoreno** [comment]
@octref Good guess

**Comment by isidorn** [comment]
Adding verified instead of @octref just to get this out of our 'to-verify' query today

**Comment by octref** [comment]
Sorry just see it here. Thanks for adding it. I'll open an issue when I'm in office.
