### ISSUE TITLE
Decorations and labels are not aligned

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#113223]
I find this more obvious now that decorations appear next to the tab label, much close compared to how decorations appear in lists or trees for example:

![image](https://user-images.githubusercontent.com/900690/102764362-50c41c00-437b-11eb-8d91-8e1f8e4c1a99.png)

(this sample fakes the decoration to be the same as the last letter of the description part of a tab which has the same `0.9em` sizing to make it more obvious)

I think this is probably due to the `:after` element with `content` use and not sure there is a CSS trick to change it.

**Comment by misolori** [comment]
I think we've always had this issue and think it's due to using `%` in font-sizes in conjunction w/ line-height adjustments:

<img width="527" alt="image" src="https://user-images.githubusercontent.com/35271042/102804148-32a3ef00-436e-11eb-8bf9-99b3543d7162.png">

<img width="428" alt="image" src="https://user-images.githubusercontent.com/35271042/102804170-39cafd00-436e-11eb-8783-a9de2e6c5c05.png">

I think these will still be off by ~1px because the base font is 13px and the decorators are ~11px while the tab heights are 35px. I can get these aligned via flexbox and tweaking line heights but they carry across to all labels so not a great fix.

**Comment by bpasero** [comment]
@misolori tabs can render the path as with a smaller font size and that seems to be aligned well, so I think this is just a problem with using `:after` where the browser will not understand how the element should be positioned relative to other elements that have text.

**Comment by bpasero** [comment]
Interestingly, adding a `margin-top: auto` to [`.monaco-icon-label::after`](https://github.com/microsoft/vscode/blob/78fc9abd92e25677cbe1fd996164a8f73e6cffc0/src/vs/base/browser/ui/iconLabel/iconlabel.css#L77-L77) makes it a lot better for me:

**Before:**
![image](https://user-images.githubusercontent.com/900690/103529245-9c032200-4e85-11eb-999b-a11a1097a19b.png)

**After:**
![image](https://user-images.githubusercontent.com/900690/103529275-a9b8a780-4e85-11eb-998c-e1f2ca6d0410.png)

**Comment by misolori** [comment]
Hmm...that didn't do anything for me. Not sure if anything has changed recently but this is looking good to me?

![image](https://user-images.githubusercontent.com/35271042/104254386-85cc0780-542b-11eb-86d2-cb8277443932.png)

**Comment by jrieken** [comment]
@bpasero is that because you are zoomed in or with zoom level zero?

**Comment by bpasero** [comment]
Yes, without zoom it seems better. Still, `margin-auto` seems to "correct" it when zooming is enabled. This is funky, I would not expect that rule to make any difference to the rendering depending on the zoom level...

**Comment by bpasero** [comment]
I pushed the suggested change via https://github.com/microsoft/vscode/commit/adee8fa29ad3635418ff995b235c4b08a40c8434#diff-93ac308d9370d907e287adb9c39b7ed81f8cc28502bf5a060cf4c4bcbe1dfffeR90 and can confirm it fixes the issue for me.

**Comment by rchiodo** [comment]
Does this depend upon the file type? Looks good for most files, but for html it looks off to me:

![image](https://user-images.githubusercontent.com/19672699/135358095-c09a292a-65df-431a-b4ca-0ac860f48139.png)

**Comment by misolori** [comment]
@rchiodo this issue is about the decorators that appear on the right, which only appear if you open a file that is part of a git repo. But the file icons do vary in size/position so just ensuring that the decorators are vertically centered with the tab text is a good way to compare:

![image](https://user-images.githubusercontent.com/35271042/135359106-a723d946-b6af-4c46-b704-cc12dc02f863.png)

**Comment by rchiodo** [comment]
Thanks @misolori. It looks like it's off by 1 pixel? Is that the intent (because it was off by more than that before?)

![image](https://user-images.githubusercontent.com/19672699/135359756-6d6c2e7f-e50e-4f4e-9862-4a28bb2107e6.png)
![image](https://user-images.githubusercontent.com/19672699/135359864-de4fc187-2007-40a0-b5fb-8bcd07ac812f.png)

**Comment by bpasero** [comment]
Keep in mind that the font size of decorations is smaller so I wouldn't expect both things to be on the exact same line. 

I was only able to see a benefit when having a zoom level of +1 (which I am using), not with default window zoom.
