### ISSUE TITLE
Smart (stage before) pull support

### ISSUE THREAD

**Issue by Kingwl** [microsoft/vscode#113271]
As https://github.com/microsoft/vscode/pull/97525. We have 'force' and 'smart' checkout.
I think it's better to support too when we `git pull` and has some unstaged changes in workspace .

**Comment by pelumiojebode** [comment]
Smart checkout

**Comment by eamodio** [comment]
You can enable this behavior today in git, by setting `merge.autoStash` or `rebase.autoStash` in your git config.

If we were to add this explicitly to `git pull` we should use the `--autoStash` option to provide the behavior, rather than implementing it ourselves.

I also, related to https://github.com/microsoft/vscode/pull/97525 I think we should adopt [`--discard-changes`](https://www.git-scm.com/docs/git-switch#Documentation/git-switch.txt---discard-changes) for force, and maybe also use [`--merge`](https://www.git-scm.com/docs/git-switch#Documentation/git-switch.txt---merge) for smart (although `--merge` would probably have a slightly different behavior in the case where the stash pop fails).
