### ISSUE TITLE
Emmet: Provide Intellisense for emmet settings that use a language Id

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#11329]
Testing #11139

- VSCode Version: 1.5.0-insiders (dated 8/31)
- OS Version: Windows

Steps to Reproduce:

1. Associate `js` with `html` syntax profile in user settings
```json
{
    "emmet.syntaxProfiles": {
        "js": "html"
    }
}
```
2. Open a .js file and try to use any of the `html` abbreviations 

Observe that the abbreviations do not work

**Comment by ramya-rao-a** [comment]
Should use "javascript" and not "js" in the settings. Closing the issue

**Comment by mrmlnc** [comment]
@egamma, IMO, this is the first user experience. Perhaps need to write about this in the documentation? :panda_face:

**Comment by egamma** [comment]
@mrmlnc agreed I'll mention this in the doc. 

The best solution would be to provide Intellisense for the languages.

**Comment by mrmlnc** [comment]
@egamma,

Well, we must provide a Intellisense for the languages or do something to improve the UX...

For example, I want to use [Riot](https://github.com/crisward/riot-tag) extension. This extension has two syntaxes (`jade` + `html`) for one language (`riot`). Because of this VS Code defines the MIME types: `jadetag` + `htmltag`. And... :boom: 

![image](https://cloud.githubusercontent.com/assets/7034281/18284017/d4d95d68-7470-11e6-93e3-97ed271ad56e.png)

In order to use Emmet I should write preferences, but how can I know the language ID without `console.log` in sources :smile_cat:?

```json
"emmet.preferences": {
  "htmltag": "html",
  "jadetag": "jade"
}
```

For more understanding, I recorded a video: [click me for watch](https://cloud.githubusercontent.com/assets/7034281/18284279/135cc9ca-7472-11e6-8a2d-96b8bcf4ef5a.gif)

**Comment by egamma** [comment]
@mrmlnc we can show Intellisense in settings. We do this for `languages` for the `file associations` settings:

![image](https://cloud.githubusercontent.com/assets/172399/18304242/8d9fdf82-74e1-11e6-9991-ca8e66ac28e3.png)

We should do the same for the emmet settings. 

I was reluctant to do this since this requires a change to JSON worker and will make extracting emmet into an extension harder.

**Comment by mrmlnc** [comment]
@egamma, crazy idea: 

![image](https://cloud.githubusercontent.com/assets/7034281/18305885/2046e460-74f2-11e6-8294-897060a443be.png)

**Comment by ramya-rao-a** [comment]
Re-opening this issue as clearly we will be working on this

**Comment by mrmlnc** [comment]
Hello, @egamma,

I want to clarify one question: Why do we have the `syntax !== thisLanguage` condition in [editorAccessor.ts#L176](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/emmet/node/editorAccessor.ts#L176)?

Refers to languages (packages):

  * Elixir
  * Riot

**Comment by egamma** [comment]
@mrmlnc this was purely defensive programming. The check can be removed, can we have unit tests for elixir and riot that specify the desired outcome?

**Comment by egamma** [comment]
Closing, Thanks to PR #12031 we now show the language ID in the language picker.
