### ISSUE TITLE
Language configuration: `notIn` in `autoClosingPairs` doesn't consider semantic tokens

### ISSUE THREAD

**Issue by WPMGPRoSToTeMa** [microsoft/vscode#113254]
- VSCode Version: 1.52.1
- OS Version: Windows 10 20H2 19042.685

Steps to Reproduce:

1. Put the following in `language-configuration.json`:
```json
"autoClosingPairs": [
  {"open": "\"", "close": "\"", "notIn": ["comment"]}
]
```
2. Type `/*  */` and put the cursor in the comment, e.g. `/* | */`.
3. Wait until semantic tokens are applied.
4. Type `"`.
5. It gets auto-closed, though the cursor was inside the comment.

**Comment by alexdima** [comment]
By design, semantic tokens cannot define the token type (string, comment, regex, other).

This was an intentional design decision because semantic tokens get computed lazily, while the token types must sometimes be computed synchronously via TextMate. The reason token types must sometimes be computed synchronously is exactly use-cases like this, typing.

For example, when typing `"` in a certain file state at a certain position, it is paramount that the editor behaves the same way at all times. If semantic tokens would influence token types, they would then influence typing. Then pressing `"` would behave differently based on the semantic tokens having been computed or not. Thus the effect of typing `"` would depend on timings, sometimes it would behave in a certain way, sometimes in another way, even with the same file state and the same position. This would make typing unpredictable for end users, and we do not want to have that.
