### ISSUE TITLE
Rename symbol in single file only

### ISSUE THREAD

**Issue by ffxsam** [Microsoft/vscode#11348]
- VSCode Version: 1.4.0
- OS Version: Mac OS 10.11.6

Steps to Reproduce:
1. Select a symbol
2. Hit F2 to rename

The symbol is renamed across my entire project. Is there a way to just rename it in the current file only?

**Comment by dbaeumer** [comment]
Ctrl+F2 (Change all occurrences) change all textual occurrences. A refactor rename limit to the single file is not available.

**Comment by ffxsam** [comment]
So Cmd/Ctrl+F2 renames just in the file, it seems, and F2 renames/refactors everywhere?

**Comment by dbaeumer** [comment]
Yes, but Ctrl+F2 renames the 'symbol' in comments as well since it is a textual rename.

**Comment by ffxsam** [comment]
Good to know! So yeah, having F2 ask whether the refactor should be global or not would be extremely useful.

**Comment by dbaeumer** [comment]
That is why I kept the issue open :-)

**Comment by LeoLozes** [comment]
`F2 ` just renamed a symbol in a file that was in `node_modules`. I spent roughly one hour before understanding what was going on (because of course, the changes made in `node_modules` don't show in the git log). Is that the desired functionality? 

Also, I think a small toast / hint saying "24 occurrences replaced in 10 files" would be extremely useful to ensure that you're not destroying half the project ...

**Comment by mjbvz** [comment]
It sounds like the root problem here is that sometimes unexpected renames happen, such as renaming things in `node_modules`. If you are seeing this, please open a new issue

I don't think creating an option to restrict renaming to a single file is the correct approach. We should fix the bad renames first and possible investigate improving the rename ux to show the users which renames will take place and ask for their confirmation 

Closing this issue out
