### ISSUE TITLE
Setting to notify user when TS server crashes

### ISSUE THREAD

**Issue by OliverJAsh** [microsoft/vscode#113559]
I frequently run into issues with the TS server, e.g. stale errors when switching branches or [renames not working properly](https://github.com/microsoft/TypeScript/issues/40386#issuecomment-726054257). It's not always obvious whether these issues are just slowness or whether the TS server has crashed.

As I understand it, if the TS server crashes, the user will _not_ be informed, and VS Code will restart the TS server.

I would like to be notified when the TS server crashes, so I can investigate and file an issue with steps to reproduce.

I appreciate it doesn't make sense for this to be the default behaviour, but a setting would be very useful for users like me who do want to help investigate issues in TS server, or provide feedback when an issue occurs.

I understand this behaviour [already exists in insiders](https://twitter.com/OliverJAsh/status/1326869727164174337), however I do not want to use insiders—I want to remain on the stable version.

**Comment by mjbvz** [comment]
Yes as you note this is the default on insiders. I'd prefer to get users to test on insiders, which we know has the latest code fixes, instead of adding a setting to standard VS Code (which realistically would not be widely used but has the potential to produce more notifications/bug reports for issues that have already been fixed)
