### ISSUE TITLE
why close the issue when it happening to almost everybody this day

### ISSUE THREAD

**Issue by Abubakargithub** [microsoft/vscode#113582]
why close the issue when it happening to almost everybody this day

_Originally posted by @Maduflavins in https://github.com/microsoft/vscode/issues/67013#issuecomment-582667425_

solved
press control+C, then press "i" to get in the "insert" status, you could edit your file now.

**Comment by yume-chan** [comment]
This issue has been closed automatically because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!

_Originally posted by @vscodebot[bot] in https://github.com/microsoft/vscode/issues/67013#issuecomment-574725490_

**Comment by yume-chan** [comment]
And your issue was related to the [Vim](https://marketplace.visualstudio.com/items?itemName=vscodevim.vim) extension, not Code itself.

I don't understand why you installed it without knowing how VI works first.
