### ISSUE TITLE
Debug console tree twistie is misaligned

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#11352]
![image](https://cloud.githubusercontent.com/assets/323878/18149470/16d78aea-6f95-11e6-99fc-faf92a4094fd.png)

Master, not insiders at the moment.

**Comment by isidorn** [comment]
I also see this on out of source, will investigate soon. Probably some theming broke this fyi @bpasero

**Comment by bpasero** [comment]
@isidorn oh yeah 🎅

**Comment by joaomoreno** [comment]
Sorry @isidorn! I went around through most trees, but neglected this one... You might wanna review [your overrides](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/browser/media/repl.css#L75).

**Comment by isidorn** [comment]
@joaomoreno np, also the debug hover was broken. Please code review and see that I am no longer ussing `paddingOnRow: false` flag, since now it was behaving differently - namely the twistie was being moved too much to the left. Now it seems to behave fine, but I can not remember why I was using that flag in the first place.
