### ISSUE TITLE
Subproject adds don't always show up in the git pane

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#11356]
After looking dumb in bf77eac, I noticed that subprojects can be silently committed from the git pane. I had cloned those repos there so they would light up in the built version of VS Code.
1. Open a folder containing a git repo in VS Code
2. Clone another repo into that folder
3. Click the refresh button in the git pane - nothing shows up
4. Make a change in another file
5. Commit that change (without first staging the file)

Examine the actual commit, and see that it also contained the second repo added as a subproject.

If you stage the new file first, then the subprojects aren't added.

Deleted subprojects are shown in the git pane.

**Comment by joaomoreno** [comment]
I don't understand what you mean with _subproject_.

Putting a git repository inside another one isn't supported by git, unless it is a submodule.

Whatever steps you did with Code, just do them in the command line. If Code behaves differently, it is a bug. Otherwise, it's just how git works.

Step 5 runs `git add -a . ; git commit -m 'message'`.

**Comment by roblourens** [comment]
The commit item shows 'subproject', apparently [includes 'submodule' and other terms](https://git.wiki.kernel.org/index.php/SubprojectSupport).

But if the pane should show everything that `git status` shows, then that's the bug.
![image](https://cloud.githubusercontent.com/assets/323878/18171732/d546be10-7017-11e6-9f46-0ac6e525bbbf.png)

If I commit through Code, those are silently committed. Through the command line, it's as visible as anything else.

**Comment by joaomoreno** [comment]
Got it. I'll take a peek.
