### ISSUE TITLE
Intellisense stops working randomly

### ISSUE THREAD

**Issue by Amiico** [microsoft/vscode#113612]
Issue Type: <b>Bug</b>

Open file, type down things, intellisense not showing all option from things like extensions. Will have to restart vscode.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3700X 8-Core Processor              (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (8.03GB free)|
|Process Argv|D:/Games/Horror game -g D:\\Games\\Horror game\\Assets\\Scripts\\CameraLook.cs:1:0 --crash-reporter-id 0236c40e-88fd-45a3-b42d-010c1545a6da|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
unity-code-snippets|kle|1.3.0
csharp|ms-|1.23.8
jupyter|ms-|2020.12.414227025
material-icon-theme|PKi|4.4.0
unity-tools|Tob|1.2.12
unity-debug|Uni|3.0.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492:30211401
wsl2prompt:30224612
pythonvsdeb440:30237827
unusedprompt:30224610
folderexplorercf:30224615
openfilemenu:30224647
pythonvsded773cf:30236630
pythonvspyt875:30239451
vsjup459cf:30237188

```

</details>

**Comment by rbkrebs** [comment]
Hi,

I'm having the same issue. I've noticed since I updated to the last version of VSCode, code_1.52.1-1608136922_amd64, it started happening. Today I reinstalled code_1.46.1-1592428892_amd64 and everything works fine!!

This is the repo I'm developing with VSCode:

https://github.com/rbkrebs/portfolio


With code_1.46.1-1592428892_amd64:
![1_46](https://user-images.githubusercontent.com/17108676/103948878-4ba3f280-5119-11eb-832e-a98fae875d76.png)



With code_1.52.1-1608136922_amd64:
![1_52](https://user-images.githubusercontent.com/17108676/103949515-24015a00-511a-11eb-98a4-fd15002c6dd0.png)


CPUs | Intel(R) Core(TM) i7-3610QM CPU @ 2.30GHz (8 x 2587)
-- | --
GPU Status | 2d_canvas: enabledflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmultiple_raster_threads: enabled_onoop_rasterization: disabled_offprotected_video_decode: unavailable_offrasterization: disabled_softwareskia_renderer: disabled_off_okvideo_decode: unavailable_offviz_display_compositor: enabled_onviz_hit_test_surface_layer: disabled_off_okwebgl: enabledwebgl2: enabled
Load (avg) | 2, 3, 2
Memory (System) | 7.66GB (0.39GB free)
Process Argv | --no-sandbox --unity-launch
Screen Reader | no
VM | 0%



Extension | Author (truncated) | Version
-- | -- | --
vscode-typescript-next | ms- | 4.2.20210106

**Comment by jrieken** [comment]
@rbkrebs what you see is this: https://github.com/microsoft/vscode/issues/110554#issuecomment-726624206 and likely unrelated to this issue

**Comment by jrieken** [comment]
@Amiico I still need more info here
