### ISSUE TITLE
Enabling scss syntax coloring and intellisense/language support for <style lang="scss"> tag

### ISSUE THREAD

**Issue by fehmi** [microsoft/vscode#113696]
Vscode has a built-in scss extension and works great with files with .scss extensions. Is it impossible to enable it for <style> tag in a HTML file something like this.

```html
<template>
  <p>
    Hello {{data.name}}!
    <a href="#">This is invisible</a>
  </p>
</template>

<style lang="scss">
  p {
    color: red;
    a {
      display: none;
    }
  }
</style>

<script>
  class {
    data = {
      name: "fehmi",
    };
  }
</script>
```

Unfortunately the result is similar to this in Vscode right now.

![image](https://user-images.githubusercontent.com/1026084/103460259-eff6f500-4d25-11eb-926e-b761148adad4.png)

I could not find a way for days now.

**Comment by marblewraith** [comment]
This shouldn't be for `scss`, you should be able to do `<style lang="postcss">`, `<style lang="less">`, etc.

**Comment by guilmarc** [comment]
Having a problem with this feature.  Nested classes always shows in white.

![Screen Shot 2021-10-01 at 1 42 35 PM](https://user-images.githubusercontent.com/1008570/135664148-db17e052-6ec6-44b0-a4f9-1c7d4904299d.png)

**Comment by fehmi** [comment]
This feature is not implemented as far as I know, isn't it?

**Comment by guilmarc** [comment]
This feature was working last year !

Envoyé de mon iPhone

Le 3 oct. 2021 à 05:05, Fehmi Özüseven ***@***.***> a écrit :

﻿

This feature is not implemented as far as I know, isn't it?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fvscode%2Fissues%2F113696%23issuecomment-932893294&data=04%7C01%7Cmguilmette%40cshawi.ca%7C1ab5b5beb4274ab63f3908d9864ceaf8%7Cb03caa02c79845ada2bd41c7e4851423%7C0%7C0%7C637688487187233101%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=2zc%2F3%2BGbkJ8MkWAuvxyosMVtV4TSCnfQuJ3dkGnlaSo%3D&reserved=0>, or unsubscribe<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAHWHOWTQVIN45NJ2DWLIMLUFAMEPANCNFSM4VRD24JQ&data=04%7C01%7Cmguilmette%40cshawi.ca%7C1ab5b5beb4274ab63f3908d9864ceaf8%7Cb03caa02c79845ada2bd41c7e4851423%7C0%7C0%7C637688487187243056%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=uZoti4AP5zzvBrAYoeYaFx2E0WdmRSbHRLeeHoz3jeI%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cmguilmette%40cshawi.ca%7C1ab5b5beb4274ab63f3908d9864ceaf8%7Cb03caa02c79845ada2bd41c7e4851423%7C0%7C0%7C637688487187243056%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=AhNNCX4ebzdbQ01A1QavHgjPDyt4h%2FDYfxVUxHqsOc4%3D&reserved=0> or Android<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cmguilmette%40cshawi.ca%7C1ab5b5beb4274ab63f3908d9864ceaf8%7Cb03caa02c79845ada2bd41c7e4851423%7C0%7C0%7C637688487187253016%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=UxWM1XQOGXWhMLnVodStlx%2BMHtlSqZAzN6C8gO%2FwDts%3D&reserved=0>.

**Comment by alexr00** [comment]
We should try to find a new SCSS grammar: https://github.com/microsoft/vscode/issues/81038
