### ISSUE TITLE
Slow editor resize when settings editor is opened to the side

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#113748]
Steps to Reproduce:

1. open some editors in group 1
2. open a group 2 to the side with settings editor (UI)
3. resize the groups via the sash

I get bad visual performance when doing so and profiling seems to hint at `probeDynamicHeight` accounting for 50% of the time spend.

[CPU-20210104T120633.cpuprofile.zip](https://github.com/microsoft/vscode/files/5764332/CPU-20210104T120633.cpuprofile.zip)

![image](https://user-images.githubusercontent.com/900690/103529106-5b0b0d80-4e85-11eb-8846-84122a568af2.png)

**Comment by joaomoreno** [comment]
This is known. The list option `supportDynamicHeights` is a feature which has serious performance impact since it needs to call `probeDynamicHeight` when rendering. It was introduced specifically for the settings editor. It is slow because it needs to render in order to calculate heights. It is necessary because the settings editor wraps text. Yet, it's still better than not having a virtualized widget and placing all rows in the DOM.
