### ISSUE TITLE
Debug console appends output from different channels to seperate lines

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#11376]
```
process.stdout.write("hello");
process.stderr.write("world");
```

Debug console prints these in two lines which is unexpected

**Comment by isidorn** [comment]
@weinand this works as expected for me, since these writes are sent to different streams - first is stdout second is stderr. We seperate the writes based on severity - e.g first is info, second is error (which is in colored red). The following snippets prints everything in one line as expected

```
process.stdout.write("hello");
process.stdout.write("world");
```

**Comment by weinand** [comment]
@isidorn your example prints everything in one line because you only get one OutputEvent, correct? The node runtime buffers writes. So your example doesn't prove that no additional newline is appended.

The purpose of my example from above was to prevent the buffering by using different streams and prove that an additional newline is appended.
In the integrated terminal or the external terminal both strings appear concatenated in one line.
In the debug console I see a newline after the first string, so the strings appear in two lines.

A terminal or debug console is a single linear stream of characters (as can be seen in the integrated or external terminals). Whether the characters come from stdout or stderr should not have an influence on how the characters are distributed on different lines, only the used color is affected.

Why do you have to start a new line when OutputEvents change their channel?

**Comment by isidorn** [comment]
@weinand this example also writes everything in one line. I am getting two output events
```
process.stdout.write("hello");
setTimeout(() => process.stdout.write("world"), 5000);
```

We do not have to start a new line when OutputEvents change their channel. But we do it because we color the output channels differently. And currently we do not have support to color parts of the line red. Also imho we should somehow indicate to the user that the output differs.
Let me know if you would prefer that everything goes to one line and I can make that change.

Also FYI @bpasero since he was invovled in that code also

**Comment by weinand** [comment]
@isidorn we should show different colours for different channels and we should render in the same way as the integrated or external terminals.
If we do not yet have support to color parts of a line, we can wait until debug-console@next supports this.
