### ISSUE TITLE
Inserting snippet that starts with `-` inserts two `--`

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#113754]
- Clone https://github.com/dbaeumer/vscode-snippet-insert.git
- start the extension
- open a text file
- type `-r` 
- this should bring up code compete with one entry `-record ....`
- select that item
- you get

```
--record(name, {field = Value :: Type()}).
```

Observe the two `--` at the beginning.

**Comment by dbaeumer** [comment]
@jrieken is this cased by word delimiters (e.g. `-` treated as such)

**Comment by jrieken** [comment]
Yeah, likely caused by the word definition. There is no `range` defined for [the item](https://github.com/dbaeumer/vscode-snippet-insert/blob/main/src/extension.ts#L14) and it's likely that `-` isn't part of a word or a word start. You can tell by the highlights, I guess it only highlights `r`, not `-r`

**Comment by dbaeumer** [comment]
Yes, only `r` is highlighted. Thanks for the clarification.
