### ISSUE TITLE
powershell.exe" terminated with exit code: 259.

### ISSUE THREAD

**Issue by chghulamnabi** [microsoft/vscode#113738]
I am getting this error.
![Screenshot_8](https://user-images.githubusercontent.com/58205463/103510178-7a566a80-4e86-11eb-97cd-ba13888bd46e.png)
@mojodna @doudou @threeve @AArnott @kaiwood 

OS: Windows:8.1
Version: 1.52.1 (user setup)
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:34:46.910Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 6.3.9600

**Comment by Tyriar** [comment]
Did you opening help and try following that?

**Comment by chghulamnabi** [comment]
Yes, i have tried all methods

**Comment by TylerLeonhardt** [comment]
What version of PowerShell is this? (open a PowerShell console and type `$PSVersionTable`)
Do you have any antivirus software on your machine that could be blocking PowerShell?
Did this just start happening recently? (did this work before?)
Are you opening a folder? Is that folder a network drive/UNC path?

**Comment by chghulamnabi** [comment]
> A few questions:
> 
> * What version of PowerShell is this? (open a PowerShell console and type `$PSVersionTable`)
> * Do you have any antivirus software on your machine that could be blocking PowerShell?
> * Did this just start happening recently? (did this work before?)
> * Are you opening a folder? Is that folder a network drive/UNC path?

1> PowerShell Version is 4.0
2> I have not any Antivirus on my System.
3>It was working fine but from 3-4 days this is happening.
4>No, I am opening a recent project, which on I was working recently.

**Comment by TylerLeonhardt** [comment]
If you change your default shell in VS Code to CMD, does that work at least? (I'm just trying to understand if this is scoped to when you use PowerShell)
If CMD does work, can you run `powershell.exe` within CMD? Does that properly start PowerShell?

Is there a reason you are using PowerShell v4? It's very old... You can update to Windows PowerShell 5.1 using WMF5.1: https://www.microsoft.com/en-us/download/details.aspx?id=54616

Or you can get the latest and greatest PowerShell (PowerShell 7) based on .NET Core from the Microsoft Store. Please note that due to https://github.com/microsoft/vscode/issues/110828 the Store install won't automatically show up when you choose your shell... but that is actively being worked on (by me 😄)
