### ISSUE TITLE
Alt+ command key performs unintended text overwrite

### ISSUE THREAD

**Issue by hwooo** [microsoft/vscode#113791]
- VSCode Version: 1.52.1
- OS Version: Windows 10 19042.685

Steps to Reproduce:
![vscode-korean-bug](https://user-images.githubusercontent.com/46282492/103606539-fc639380-4f59-11eb-9824-43277ed0d4de.gif)

1. Reassign cursor up/left/down/right as Alt+i/j/k/l keys.
2. Write comments with Korean. Focus is on the last Korean word.
3. Move cursor with Alt+ command keys.
4. Press another key. (In here, I pressed arrow key on the keyboard)

Then the focused word overwrites the original word on the new line where the cursor is moved.

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexdima** [comment]
When you rebind cursor up/left/down/right to alt+i/j/k/l, this does not have any effect on the composition which is done by the OS. 

So when you are composing Korean, pressing alt+k will move "our" cursor down (that is why the glyph on line 3 becomes highlighted), but the OS remains in composition mode because Windows itself does not know that you want composition to stop when pressing alt+k.

Then, when you actually finish composition by pressing arrow down, we receive the composition ended event from the OS and update the text at the current cursor location because we think you have finished composition.

I don't think any other software on your machine would support this scenario, since the OS composition remains in composition mode when you press alt+k.

**Comment by hwooo** [comment]
> I don't think any other software on your machine would support this scenario, since the OS composition remains in composition mode when you press alt+k.

I tested same key composition on IntelliJ IDEA and Visual Studio, but there is no problem like this.

**Comment by alexdima** [comment]
Thank you for trying that. So when you press alt+k in those the composition mode stops or can you still compose?

**Comment by hwooo** [comment]
In IntelliJ, the focus on last-entered Korean word is released when pressing alt key. In Visual Studio, the caret always goes behind the text after typing and focus doesn't catch the last word.
