### ISSUE TITLE
Revisit how activity bar items and status bar items can be hidden by the user

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#113757]
Currently hiding an activity bar item is different than hiding a status bar item.

Activity bar:
![image](https://user-images.githubusercontent.com/172399/103543055-2bb4ca80-4e9e-11eb-894b-3f99c49e0ce0.png)

Status bar:
![image](https://user-images.githubusercontent.com/172399/103543085-3bccaa00-4e9e-11eb-8f62-192e945671c4.png)

Hiding the selected item is the top most item in the activity bar and the bottom most item in the status bar.

Do we need support for hiding the selected item at all? The user can already hide any item from the menu. 

As part of this effort should also investigate how to guide users about how to restore a hidden item.

**Comment by bpasero** [comment]
@egamma there is a specific reason why "Hide" is the last entry in the status bar and not to the top. Since the menu opens from the bottom to the top, it felt more natural to have the "Hide" entry closer to the mouse and not all the way up.

As for consistency, I think the "Hide" entry in the activity bar could spell out the name of the view to hide.

What is the push for removing "Hide" entirely?

//cc @sandy081 @kieferrm

**Comment by bpasero** [comment]
Added the names to:

![image](https://user-images.githubusercontent.com/900690/103776791-43bc5380-5030-11eb-878f-3e8f650d9dd2.png)

![image](https://user-images.githubusercontent.com/900690/103776809-49199e00-5030-11eb-8855-e03c5668e0be.png)

**Comment by kieferrm** [comment]
The starting point of the conversation was the home indicator in a Codespace. When I click on the home indicator, the context menu opens. The context menu has an hide action and it doesn't make sense there. 

<img width="296" alt="image" src="https://user-images.githubusercontent.com/4674940/103934845-8d617880-50da-11eb-88b9-2e58af2931ac.png">

This leads to a more general discussion about the hide actions in the activity bar. On the status bar we have one way to configure the visibility of status bar items. I always get the same context menu no matter whether the click happens on a status bar item or not:

<img width="408" alt="image" src="https://user-images.githubusercontent.com/4674940/103934523-f7c5e900-50d9-11eb-9c0f-f6e7c3b82c25.png">

On the activity bar however I get a different menu depending on where I click:

On the activity bar (not a particular view icon):
<img width="260" alt="image" src="https://user-images.githubusercontent.com/4674940/103934627-25129700-50da-11eb-9de7-9cb9355f1f0d.png">

On the activity bar (on a particular view icon):
<img width="248" alt="image" src="https://user-images.githubusercontent.com/4674940/103934723-4c696400-50da-11eb-94bc-6fbbae0c7b29.png">

On the account icon on the activity bar:
<img width="407" alt="image" src="https://user-images.githubusercontent.com/4674940/103934763-6145f780-50da-11eb-9e30-fa8e448a66e3.png">

On the home indicator in a Codespace:
<img width="296" alt="image" src="https://user-images.githubusercontent.com/4674940/103934845-8d617880-50da-11eb-88b9-2e58af2931ac.png">

On the compact menu (in a Codespace):
<img width="285" alt="image" src="https://user-images.githubusercontent.com/4674940/103934980-c26dcb00-50da-11eb-81d0-ddfbc4e3d972.png">

It seems that we should 
- separate the context menu from the menu I get when clicking on home indicator, account, gear.
- have one context menu for the activity bar no matter where I open it, that lets me configure visibility of contributions.

**Comment by sbatten** [comment]
I'm probably restating a bit here, but just for ensuring we are on the same page:

The viewlet icons in the activity might have specific actions such as Reset Location. These will still have to be appended to the context menu depending on click location.
![image](https://user-images.githubusercontent.com/6561887/103939664-f77d1c00-50e0-11eb-8f95-a2744d1faf1e.png)

We are inconsistent about right-click on icons in the activity bar. We should always open the context menu on right-click anywhere in the activity bar and no hide actions should be shown in the left click menus.

**Comment by bpasero** [comment]
@kieferrm 

> The starting point of the conversation was the home indicator in a Codespace. 

Since the home indicator will go away, I think it is fair to say that we have these things in the activity bar:
* menu (mostly web only)
* views
* accounts
* settings

> On the status bar we have one way to configure the visibility of status bar items. I always get the same context menu no matter whether the click happens on a status bar item or not:

That is not true, the right-click menu on a status entry allows to quickly "Hide" it, while the click outside shows a menu without that entry. See the following video to proof that:

![recording](https://user-images.githubusercontent.com/900690/103986707-80509200-518b-11eb-965f-3f1e1c288b5f.gif)

> On the activity bar however I get a different menu depending on where I click:

That is consistent with the status bar: if you click on a specific icon the menu may be different from the menu you get when you click somewhere outside any item.

> We are inconsistent about right-click on icons in the activity bar. We should always open the context menu on right-click anywhere in the activity bar and no hide actions should be shown in the left click menus.

I think the real challenge here is that some of the entries in the activity bar have a left-click menu that is the same when you right-click. If we remove "Hide" actions from the left-click menu, would we show them when you right click?

Maybe it is easier we setup a call to discuss this item.

**Comment by sandy081** [comment]
> We are inconsistent about right-click on icons in the activity bar. We should always open the context menu on right-click anywhere in the activity bar and no hide actions should be shown in the left click menus.

Agree that we shall not show `Hide` Action in the left click menu and always show Hide actions in right click menu. I think we follow this every where (status bar, views).

![image](https://user-images.githubusercontent.com/10746682/103995381-b34d5280-5198-11eb-80cd-98df14609825.png)

![image](https://user-images.githubusercontent.com/10746682/103995396-b9433380-5198-11eb-87fa-7b1469ad8cdc.png)

We shall also use check mark for showing/hiding Accounts icon to make it consistent. Having a separator between top entries and bottom entries in activity bar is also inconsistent with left and right entries in status bar. Either we shall have the separator in both or not. Personally I feel separator makes sense.

![image](https://user-images.githubusercontent.com/10746682/103995756-2fe03100-5199-11eb-99a6-2b1ea5fe1d03.png)

![image](https://user-images.githubusercontent.com/10746682/103995822-46868800-5199-11eb-90ee-9a6965a3866b.png)

Summarizing my suggestions:

- Do not show hide actions on left click on activity bar icons
- Use check mark to toggle Accounts icon in activity bar
- Use separator between left/right status bar items toggling actions
- Show `Move Sidebar Right` & `Hide Sidebar` actions also when right clicked on view

**Comment by bpasero** [comment]
@sandy081 I like your suggestions, but the status bar one is not so straight forward. Given https://github.com/microsoft/vscode/issues/74972 is still proposed API and needs adoption, the status bar will group every entry from extensions under a single name. So you can end up having left and right side entries under 1 name, so we cannot visually group them properly. 

Also, when you have many entries in the status bar it maybe less obvious that there are left and right entries.

To conclude: I think the separators make a lot of sense in the activity bar because they separate views from other things like menu and accounts, but in the status bar I do not see a lot of value doing so.

**Comment by bpasero** [comment]
After meeting we decided to:
* remove "Hide" from all left click menus (home indicator, accounts)
* consistently show the same right click menu for all entries in the activity bar
* consistently show "Hide <xyz>" when right clicking on something that can be hidden
* consistently use checkboxes when toggling something (home indicator, menu, accounts)
* reflect the order of entries in the right click menu according to what is visible (e.g. home and menu first) and use separators
* do not show any entry for "Menu" when the user configured the menu to be fully visible outside the activity bar

**Comment by bpasero** [comment]
@sbatten @sandy081 I pushed the changes as discussed, please let me know how it works for you.

**Comment by bpasero** [comment]
One thing I was not able to do is showing a "Hide Menu" on the right click menu of the main menu in the activity bar. It looks like the main menu is not using our `MenuActivityActionViewItem` helper, which somewhat makes sense because the main menu does not open a context menu but our custom menu. Leaving it up to SteVen to decide if he still wants to push that.

**Comment by sandy081** [comment]
Thanks @bpasero for the changes and they look good.

FYI I also made following changes 

- Aligned `Reset Location` to show always after `Hide ${View}` action everywhere (sidebar and panel views)
- Aligned context menu actions on Panel views to show Move/Hide panel actions always

### Sidebar

<img width="371" alt="image" src="https://user-images.githubusercontent.com/10746682/104355439-f6962100-550a-11eb-9eeb-81bf589b6ef0.png">

<img width="364" alt="image" src="https://user-images.githubusercontent.com/10746682/104355126-84254100-550a-11eb-90a4-8e398528b4f2.png">

<img width="292" alt="image" src="https://user-images.githubusercontent.com/10746682/104355517-162d4980-550b-11eb-8675-d01fe65b37e4.png">

### Panel

<img width="459" alt="image" src="https://user-images.githubusercontent.com/10746682/104355257-b171ef00-550a-11eb-945e-806d6043398c.png">

<img width="433" alt="image" src="https://user-images.githubusercontent.com/10746682/104355193-9c955b80-550a-11eb-8f57-e6475aabf7a4.png">

<img width="415" alt="image" src="https://user-images.githubusercontent.com/10746682/104355582-30672780-550b-11eb-853e-7814a9dd4427.png">
