### ISSUE TITLE
Debug console is shown when launching Node application with integratedTerminal

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#11372]
OS: OSX

Steps to Reproduce:
1. Clone [VS Code Smoke Test](https://github.com/Microsoft/vscode-smoketest-express) application
2. Create a Node debug launch to run the application
3. Use `integratedTerminal` as console in the launch
4. Reload the window
5. Start the launch

Expected: Integrated terminal should remain after starting
Observed: Debug console is shown.
![sep-01-2016 10-49-59](https://cloud.githubusercontent.com/assets/10746682/18161353/deb1bf62-7031-11e6-9c85-54aff01bbc52.gif)

**Comment by isidorn** [comment]
The `console` attribute is contributed by the node debug adapter and thus vscode is unware fo this attribute.
I am not sure how to fix this on my side. There is a workaround, just set `"internalConsoleOptions": "neverOpen"` in your `launch.json`

**Comment by weinand** [comment]
@isidorn why is the integrated terminal panel (?) not reopened after the reload? This should be automatic behavior?

**Comment by isidorn** [comment]
@weinand if you have the integrated terminal panel open and reload vscode it remains open, as we try to preserve all UI state on vscode restart. Do you see different behavior?

**Comment by weinand** [comment]
@isidorn I think @sandy081 sees different behaviour: the debug console opens instead of the integrated terminal panel

**Comment by sandy081** [comment]
Yes, Integrated terminal panel is shown when commands are executed. It goes off and Debug console comes back after.

**Comment by isidorn** [comment]
@weinand yes, I was commenting on your previous comment, Sandeep's behavior I have commented in my first comment.

**Comment by weinand** [comment]
This is an unfortunate event ordering problem:
- first the debug adapter calls 'runInTerminal' which brings the integrated terminal to front, and then
- some output of the debug target makes VS Code open the debug console which then hides the integrated terminal.

As a workaround we could remember that 'runInTerminal' was used and then avoid bringing the debug console to front.

**Comment by isidorn** [comment]
Setting to september to experiment with showing the console on first output recieved

**Comment by isidorn** [comment]
After experimenting with this I am against opening the repl once first output appears due to:
* The current `'openOnSessionStart'` has possible values `'neverOpen', 'openOnSessionStart', 'openOnFirstSessionStart'`. And this does not comply with opening it based on output, so we would have to create new names for these options and still support old values
* When the session starts we also show the debug viewlet, now it is part of one experience showing the viewlet and the console. It would become disconnected if we show the viewlet and then a console appears some time afterwards

Let me know what you think. I am also open for more suggestions

**Comment by isidorn** [comment]
Closing as we do not plan to adress this in the near future.
No user complained about this behavior. Also there is a workaround specified above
