### ISSUE TITLE
live server not working

### ISSUE THREAD

**Issue by malav064** [microsoft/vscode#113770]
Issue Type: <b>Feature Request</b>

installed live server but not working , what should i do, and half of the features
are not working.
also on the top middle where visual studio code is written [unsupported] is written next to that.

is there any problem in downloading or some feature i need to activate or deactivate on my desktop. 
 please get back as soon as possible.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.18363

**Comment by RMacfarlane** [comment]
Since this is an issue with live server, please open it in the repository for that extension.

I'm not sure exactly where you mean "[unsupported]" is written, but this could mean that you have installed an extension that has changed part of VSCode on disk. You could try uninstalling your other extensions.
