### ISSUE TITLE
WARN Settings pattern "settingsSync.*" doesn't match any setting

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#113747]
![image](https://user-images.githubusercontent.com/900690/103528792-dae4a800-4e84-11eb-81a1-4d9aabf96983.png)

Seeing this opening settings editor (UI) running out of sources.

**Comment by sandy081** [comment]
Settings sync settings are registered only when settings sync is configured which is not the case by default. Hence this warning is shown. I do not think there is a way to configure settings editor `tocData` based on if settings sync is configured or not. Only option is to register these settings always. If it is ok, I will close this without any action?

@roblourens FYI

**Comment by roblourens** [comment]
I really thought I had something already for dynamically registered configuration, because that was an issue for the bing settings service where some settings couldn't be indexed because they were only registered on windows, and that process runs on mac. So I thought there was a flag that would allow it to be registered but "invisible". But I can't find anything like that.

@bpasero can you think of a setting that is only registered on Windows?

**Comment by roblourens** [comment]
Probably I will just hardcode it to not show the warning for that pattern. It's not a big deal.

**Comment by bpasero** [comment]
@roblourens you mean `included` like here?

https://github.com/microsoft/vscode/blob/c03bc427cf71dae7766cd6e451c492b12e87e544/src/vs/workbench/electron-sandbox/desktop.contribution.ts#L281-L281

**Comment by roblourens** [comment]
Oh, there it is. What that does isn't exactly what I want here, so I'll do another workaround.
