### ISSUE TITLE
Add option to exclude unsaved Untitled-n files from processing

### ISSUE THREAD

**Issue by ackvf** [microsoft/vscode#113822]
I very often create new `Untitled` tabs that I **never** save and name for:
- notes
- temp snippet storage
- text manipulation
- `File: Compare Active File With...`
- etc.

And it bothers me that those files raise tons of various errors.

![image](https://user-images.githubusercontent.com/2313018/103654374-16a36e80-4f66-11eb-8e46-5a9aec0ae792.png)
Real workspace problems: 0
Unrelevant problems: 23
![image](https://user-images.githubusercontent.com/2313018/103654433-2458f400-4f66-11eb-84fa-931e75d325e1.png)

Since the file is not part of my workspace, I wouldn't expect it to pick up my workspace's
- lint rules
- language engine settings
- code formatting settings
- .editorconfig, .gitignore, etc.
- or simply just about anything that is related just to the files under the workspace's top directory

I believe that would be similar to when I open a physical file from a different workspace or from no workspace altogether.

If I care about the file and I want editor's feedback, I would start by giving the file a name and a place (i.e. save it to the workspace).
Only at that point it starts making sense to me, that the file starts reporting lint errors or missing imports, etc.
I would appreciate if this was the default or at least if it could be turned off by a setting.

**Comment by mjbvz** [comment]
My view is that untitled files are conceptually belong to the workspace.

If you are using them to start a new file, you almost always are going to save the file into the workspace. Therefore applying the workspace language settings makes sense.

If you are just using them as a scratchpad, treating them as part of the workspace lets you adjust settings/config for them. I don't think you can configure them otherwise

Ultimately languages/extensions are free to determine this for themselves, but defaulting them to be conceptually in the workspace (although perhaps not in the project) makes the most sense to me. This is what our JS/TS support does

**Comment by ackvf** [comment]
I guess I will have to live with that. Thank you for the answer.
