### ISSUE TITLE
SCM repo view: often all entries are selected

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#113803]
I was not yet able to pin down the issue but every once in a while I see the SCM repo view select all repos, even though it should just be one. Most often I see the view state restore properly but sometimes not.

![image](https://user-images.githubusercontent.com/900690/103621256-35d5d800-4f35-11eb-96a8-47e0c4e0042f.png)

Filing this issue to see if someone else is seeing this too and to maybe add some logging when this happens to nail it down?

**PS:** I am using the web version, but not sure if that matters. When is this state persisted? On shutdown maybe long running?

**Comment by bpasero** [comment]
I figured out this seems to happen consistently when an update is applied. So somehow that UI state is not preserved when we restart from an update (macOS). Is this state computed long running in an extension or all in workbench?

**Comment by joaomoreno** [comment]
State is persisted on `onWillSaveState`:

https://github.com/microsoft/vscode/blob/016655c546779fd1420ea3f688465d39b6f43b02/src/vs/workbench/contrib/scm/browser/scmViewService.ts#L238-L248

Restoring the state is tricky since SCM providers come delayed, and the SCM world must have timeouts to consider when no more SCM providers are expected to load. It's filled with heuristics, which might fail in that case. One of those heuristics is: _if we go 2 seconds without any providers being loaded, we stop considering any more providers, in order to restore view state_:

https://github.com/microsoft/vscode/blob/016655c546779fd1420ea3f688465d39b6f43b02/src/vs/workbench/contrib/scm/browser/scmViewService.ts#L250-L250

**Comment by bpasero** [comment]
@joaomoreno ah ok, just to know what is going on, can you `logService.warn` when that timeout is hit so that I can see if I am hitting this case? I would think the `onWillSaveState` is handled properly because otherwise I would loose all my UI state after an update is applied.

**Comment by joaomoreno** [comment]
Added `trace` logs 👍

**Comment by joaomoreno** [comment]
Optimistically closing this with the fix from https://github.com/microsoft/vscode/issues/120089. @bpasero Let me know if you still see it after taht.

**Comment by heartacker** [comment]
![git-repos](https://user-images.githubusercontent.com/1876302/142874850-0725d773-36c3-4d88-9427-63357e971e44.gif)

**Comment by lszomoru** [comment]
Optimistically closing this with https://github.com/microsoft/vscode/commit/5c65b189c9210324376c9851900c55d4e1b031c6. 
@bpasero, let me know if you will still experience this issue. Thanks!

**Comment by bpasero** [comment]
So far so good, will report back if I ever see this again.

**Comment by heartacker** [comment]
when reload

**Comment by lszomoru** [comment]
@heartacker, you have to be a little more specific. 
What steps do you follow and what is the behaviour that you are seeing?
Are you clicking on any of the repositories while the repositories are being discovered?

**Comment by heartacker** [comment]
1. reload windows which has multi repos
2. all repos are selected while repos are being discovered
