### ISSUE TITLE
Block comment highlighting doesn't work properly for some doxygen files

### ISSUE THREAD

**Issue by myeongbo** [microsoft/vscode#113865]
Moved from https://github.com/microsoft/vscode-cpptools/issues/6738

There are open source projects requiring doxygen format as a default comment format such as [tvm](https://github.com/apache/tvm).
In this project, `/*!` is used to block comment beginners but it doesn't seem to be recognized by VSCode now.
The tag `\file` is regarded as a symbol.
![image](https://user-images.githubusercontent.com/5017662/103715351-be22ae80-5003-11eb-8136-d6939af1fc34.png)

I wonder if this happens because `/*!` is not a defined comment beginner here?
https://macromates.com/manual/en/language_grammars#naming_conventions
Is there any workaround you can provide or should I fix it from the source code?

**Comment by alexr00** [comment]
@myeongbo the **coloring** of `\file` is handled by VS Code, that is correct. It looks like it getting the correct language scope though. If you want to change the color, you can install another theme, or modify your existing theme (use command Developer: Inspect Editor Tokens and Scopes + the [customization docs](https://code.visualstudio.com/docs/getstarted/themes#_editor-syntax-highlighting). It also looks like `/*!` is correctly recognized as a comment start. So everything is working well from a colorizing perspective.

The hover you get over `\file` is probably coming from the C++ extension that you have installed, since VS Code doesn't provide that on its own. You can test this by disabling that extension and seeing if the hover is still there. I'm sorry for the repository ping-pong, but for that you should file in issue in that extension's repo.
