### ISSUE TITLE
Space does not enable / disable breakpoint

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#113815]
found by @jvesouza

**Comment by jvesouza** [comment]
The problem seems to be fixed but orca does not announce the new status of the chek when I press space bar.
I need to navigate in the list of breakpoints to confirm that the check is checked or not.

**Comment by isidorn** [comment]
@jvesouza thanks for trying it out, thus adding verified label.

I also tried it with Voice Over and Voice Over nicely reads the status of the checkmark once it is changed.
Maybe @joanmarie has an idea why Orca is not announcing.
On the VS Code side we properly update the `aria-checked` attribute on the element.

**Comment by joanmarie** [comment]
@isidorn My guess is that there is a missing state-change event (which would likely be a chromium bug since you are properly updating the `aria-checked` attribute). I'll take a look. But where exactly is this checkbox? Orca announces the state changes for the checkboxes I find when I search settings for "breakpoint."

**Comment by isidorn** [comment]
@joanmarie add a breakpoint in any file, for example a `.js` file by clicking on the gutter, or pressing `F9`.
Press `Ctrl + Shift + D` to open the Debug Viewlet on the left. Notice the BREAKPOINTS view, in the breakpoints view every breakpoint has a checkbox. You can click on the brekapoint for it to get focus and press `space` to toggle the checkbox.

**Comment by joanmarie** [comment]
Hmmmm. I think I'm still confused. :(

@isidorn: *Now* I see BREAKPOINTS at the bottom of the Viewlet on the left. And the breakpoints there have a checkbox as you've described. (Thanks for telling me where to look!) The thing is.... Orca presents them (which I'll detail in a moment). But @jvesouza stated "I need to navigate in the list of breakpoints to confirm that the check is checked or not." This suggests to me that perhaps @jvesouza is not in that list of breakpoints when he is pressing space, and that he is navigating to that list in order to verify what he had done before. So.... Where are you José when you are pressing space?

In the meantime.... In order to capture a less noisy debug.out, I gave the breakpoint in the list focus, then quit and restarted Orca. Some observations:

1. When I first Alt+Tabbed into VSCode (where the breakpoint I wanted to toggle was already focused), the "Breakpoints" list claimed focus; the item with the checkbox did not. As a result, Orca just said "Breakpoints."
2. The first time I pressed space, I got a state-changed:focused for the checkbox. That caused Orca to present the name and state of the checkbox:
 ```
foo.py 1, Disabled Breakpoint
check box not checked.
```
3. The second time I pressed space, I got a children-changed:add event for a section (a div with class monaco-list-rows). The section was adding a checkbox. Orca noticed that the currently-focused (according to Orca) object had been destroyed and that the newly-added child checkbox happens to be focused. So Orca updates the focus and presents it to the user:
```
foo.py 1, ~/foo.py
check box checked.
```
4. Orca then gets a state-changed:focused event for the newly-added checkbox, which it ignores because it had already figured that out from the children-changed:add event.

So I fear I still don't know how to reproduce this problem. Perhaps @jvesouza could give me a full debug.out, along with some steps to reproduce the problem so that I can figure out where he is pressing Space?

@isidorn Are you able to reproduce this issue yourself?

Also, independent of this bug, when the list first claims focus, would it make sense to instead have the currently-selected item claim focus instead? Screen readers typically announce the changed context/ancestry, so I would think they'd all announce the "breakpoints" list if focus moved from outside the list to an item inside the list.

**Comment by jvesouza** [comment]
Testing more closely, I noticed something very interesting. I have in the breakpoint view three breakpoints, one being placed by me and two placed probably by java extension.
If I press the space bar on the breakpoint I put, orca behaves as expected, but if I press the space bar on one of the breakpoints placed by the extension, orca does not announce the change in status.

@joanmarie Can I send the debugfile in pvt?
Thanks.

**Comment by jvesouza** [comment]
> Hmmmm. I think I'm still confused. :(
> 
> @isidorn: _Now_ I see BREAKPOINTS at the bottom of the Viewlet on the left. And the breakpoints there have a checkbox as you've described. (Thanks for telling me where to look!) The thing is.... Orca presents them (which I'll detail in a moment). But @jvesouza stated "I need to navigate in the list of breakpoints to confirm that the check is checked or not." This suggests to me that perhaps @jvesouza is not in that list of breakpoints when he is pressing space, and that he is navigating to that list in order to verify what he had done before. So.... Where are you José when you are pressing space?

I believe in the list of breakpoints because I press the space bar right after hearing the state of the breakpoint.
Anyway, I think that you will not be able to reproduce the problem in the face of what was reported in my previous comment.
I am debugging a java application and the breakpoints that do not have the status reported when I press the space bar were not placed by me but by some extension.

**Comment by joanmarie** [comment]
> @joanmarie Can I send the debugfile in pvt?

Of course! You know where to find me. :smile: 

> Thanks.

Thank you!!

**Comment by isidorn** [comment]
@jvesouza Those might be exception breakpoints that are added my the java extension? Anyways I just checked and all works fine for me also for exception breakpoints with Voice over.

**Comment by joanmarie** [comment]
So... When things work in this particular set of objects, they work because Orca is treating the children-changed:add event as an event for a "context replicant" (The context is where Orca thinks you are; the replicant is the replacement object when the browser or web app sees fit to destroy the object you're on which, alas, happens surprisingly often. But I digress....)

For some reason, in the case of the failing checkboxes, Orca doesn't treat the children-changed:add event as an event for a "context replicant". Not sure what the point of rejection is, so I just added debugging output to Orca to spew out its decision-making process for this condition. @jvesouza: Sorry, but I'm afraid I have to ask you for a new debug.out after you pull Orca master. Thanks!
