### ISSUE TITLE
`Unable to resolve your shell environment` notification after VS Code restored during MacOS restart

### ISSUE THREAD

**Issue by mattbierner** [microsoft/vscode#113869]
Issue Type: <b>Bug</b>

**Repro**
1. Restart MacOS so that a VS Code window is restored
1. See a notification: `Unable to resolve your shell environment in a reasonable time. Please review your shell configuration.`

VS Code version: Code - Insiders 1.53.0-insider (a48ef56fbf7767f55a193d7d5687addd1fc9239c, 2021-01-05T05:22:22.983Z)
OS version: Darwin x64 20.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|141, 41, 16|
|Memory (System)|40.00GB (26.72GB free)|
|Process Argv|--crash-reporter-id cefe23df-690f-4b1b-9ce9-e004d3be2745|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
spellright|ban|3.0.52
color-info|bie|0.5.1
comment-tagged-templates|bie|0.3.1
docs-view|bie|0.0.8
emojisense|bie|0.8.0
gif-player|bie|0.0.2
speech|bie|0.0.3
vscode-eslint|dba|2.1.14
gitlens|eam|11.1.3
vscode-pull-request-github|Git|0.22.0
vscode-azurefunctions|ms-|1.1.0
vscode-docker|ms-|1.9.0
python|ms-|2020.12.424452561
vscode-pylance|ms-|2020.12.2
jupyter|ms-|2020.12.414227025
remote-containers|ms-|0.154.2
azure-account|ms-|0.9.4
cpptools|ms-|1.1.3
wordcount|ms-|0.1.0
debugger-for-chrome|msj|4.12.11
language-liquid|nei|0.1.1
polacode|pnp|0.3.4
shader|sle|1.1.4
code-spell-checker|str|1.10.2
sort-lines|Tyr|1.9.0
sourcekit-lsp|unp|0.0.1
material-theme|zhu|3.9.12

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221882
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30208929
wsl2prompt:30219162
vstry244:30230484
pythonvsdeb440:30224570
unusedprompt:30219164
folderexplorer:30219166
openfilemenucf:30219169
pythonvsded773:30223139
pythonvspyt600:30241727
core-portspanel:30233467

```

</details>

**Comment by Chartieer** [comment]
When VS Code is launched from a terminal (for example, via code .), it has access to environment settings defined in your .bashrc or .zshrc files. This means features like tasks or debug targets also have access to those settings.

However, when launching from your platform's user interface (for example, the VS Code icon in the macOS dock), you normally are not running in the context of a shell and you don't have access to those environment settings. This means that depending on how you launch VS Code, you may not have the same environment.
See here https://code.visualstudio.com/docs/supporting/faq#_resolving-shell-environment-is-slow-error-warning

**Comment by cheuksing** [comment]
As a Linux (Debian Sid) user, I have the same issue.
I checked my `.bashrc .zshrc .profile` rwx permission and even comment out all content within this file, but the issue presist.
Could someone mind providing some extra information? e.g which exact config files are being sourced, for easier debugging.
Thanks.

**Comment by prof7bit** [comment]
I'm having the same problem on my Linux KDE desktop.

When started from the Starter menu it will display this error after 10 seconds,
when started from the command line it will block indefinitely and not start at all.

There are no "potentially long running" commands in my .bashrc, it runs just fine when starting a bash session and never gave me any problems, this FAQ is not helpful at all.

How can I debug this issue? How can I disable this .bashrc scanning entirely, it doesn't need my bashrc, its just a frickin text editor!? VScode used to work extremely well, I regarded it as the best editor on this planet and recommended it to everyone. And suddenly it starts to go downwards very fast, you are destroying a perfect product by adding useless stuff and fixing things that aren't broken out of pure boredom. Is this a Microsoft specific behaviour?

**Comment by wbollock** [comment]
Same issue with i3 on Arch. I would like to tell vs code to not resolve my shell environment.

**Comment by valentinocossar** [comment]
I have the same issue, the startup time of my shell seems not so bad. But I'm experiencing the slow shell notification. I'm using this snippet to benchmark my shell startup time.

```sh
timezsh() {
  shell=${1-$SHELL}
  for i in $(seq 1 10); do /usr/bin/time $shell -i -c exit; done
}
```

![image](https://user-images.githubusercontent.com/4087384/106333099-448b8280-6288-11eb-9857-18d03998baec.png)

**Comment by luozhouyang** [comment]
Same issue!

**Comment by yaseenshaik** [comment]
An option to disable this would be great.

**Comment by cooljeanius** [comment]
Does VS Code define any environment variables I could test for in the relevant files to have it ignore the slow parts that are making it take too long to resolve? e.g.:
```
if [ "x${VSCODE}" = "xYES" ]; then
    # (skip doing anything)
else
    # (run slow code) 
fi
```
or something

**Comment by corentin-gautier** [comment]
Same issue : Happens every time that vscode is open after a reboot of the system. The notification appear AND anything in the terminal will fail ("npm not found" if I try to start a task from the package.json). I have to quit then restart vscode and then for some reason everything is ok. What's the difference between the first launch and the second ? (I don't use the command line, only the dock icon)

On macos, I use nvm (because node on mac is a nightmare), everything's up to date.

**Comment by ssssct** [comment]
> I have to quit then restart vscode and then for some reason everything is ok. What's the difference between the first launch and the second ?

TheSecondTimeIsDifferent™

**Comment by dimaj** [comment]
> Does VS Code define any environment variables I could test for in the relevant files to have it ignore the slow parts that are making it take too long to resolve? e.g.:
> 
> ```
> if [ "x${VSCODE}" = "xYES" ]; then
>     # (skip doing anything)
> else
>     # (run slow code) 
> fi
> ```
> 
> or something

I ran `env | sort > ~/vscode.env` from VSCode's shell and `env | sort > ~/iterm.env` and found some differences:
| Env Var | VSCode | iTerm | Terminal | 
| ------- | ------ | ----- | --- | 
| TERM_PROGRAM | vscode | iTerm.app | Apple_Terminal |
| TERM_SESSION_ID | | _some guid_ | _some guid_ |
| VSCODE_GIT_ASKPASS_MAIN | /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass-main.js | | | 
| VSCODE_GIT_ASKPASS_NODE | /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) | | |
| VSCODE_GIT_IPC_HANDLE | /var/folders/gh/gg7_2g452cggs0pbxq_4vryr0000gp/T/vscode-git-6eaef43673.sock | | |
| ORIGINAL_XDG_CURRENT_DESKTOP | undefined | | |
| ITERM_PROFILE | | _my profile name_ | |
| GIT_ASKPASS | /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass.sh | | |

I am not sure if this is helpful, but might be an avenue worth exploring. If I'll have some time to dedicate to this, I'll post my findings.

**Comment by cooljeanius** [comment]
> > Does VS Code define any environment variables I could test for in the relevant files to have it ignore the slow parts that are making it take too long to resolve? e.g.:
> > ```
> > if [ "x${VSCODE}" = "xYES" ]; then
> >     # (skip doing anything)
> > else
> >     # (run slow code) 
> > fi
> > ```
> > 
> > 
> > or something
> 
> I ran `env | sort > ~/vscode.env` from VSCode's shell and `env | sort > ~/iterm.env` and found some differences:
> Env Var 	VSCode 	iTerm 	Terminal
> TERM_PROGRAM 	vscode 	iTerm.app 	Apple_Terminal
> TERM_SESSION_ID 		_some guid_ 	_some guid_
> VSCODE_GIT_ASKPASS_MAIN 	/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass-main.js 		
> VSCODE_GIT_ASKPASS_NODE 	/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) 		
> VSCODE_GIT_IPC_HANDLE 	/var/folders/gh/gg7_2g452cggs0pbxq_4vryr0000gp/T/vscode-git-6eaef43673.sock 		
> ORIGINAL_XDG_CURRENT_DESKTOP 	undefined 		
> ITERM_PROFILE 		_my profile name_ 	
> GIT_ASKPASS 	/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass.sh 		
> 
> I am not sure if this is helpful, but might be an avenue worth exploring. If I'll have some time to dedicate to this, I'll post my findings.

ok I tried adding

```
if [ "x${TERM_PROGRAM}" = "xvscode" ]; then
	return
fi
```

early in my `.bashrc` but I still get the shell environment warning from VS Code...

**Comment by dimaj** [comment]
dumb question...
is your default shell `bash`?

i think you need to use `[[ ]]` to test string equality in bash:
```
bash-3.2$ if [[ "x${TERM_PROGRAM}" = "xvscode" ]]; then echo true; else echo false; fi
false
bash-3.2$ echo $TERM_PROGRAM
iTerm.app
bash-3.2$ if [[ "x${TERM_PROGRAM}" = "xiTerm.app" ]]; then echo true; else echo false; fi
true
```

**Comment by cooljeanius** [comment]
> dumb question...
> is your default shell `bash`?
> 

Yes.

> i think you need to use `[[ ]]` to test string equality in bash:
> 
> ```
> bash-3.2$ if [[ "x${TERM_PROGRAM}" = "xvscode" ]]; then echo true; else echo false; fi
> false
> bash-3.2$ echo $TERM_PROGRAM
> iTerm.app
> bash-3.2$ if [[ "x${TERM_PROGRAM}" = "xiTerm.app" ]]; then echo true; else echo false; fi
> true
> ```

OK I tried changing it to that; it doesn't help.

**Comment by dimaj** [comment]
@cooljeanius, 
What would happen if your first line of your `.bashrc` was: 
```
mkdir -p envdebug && env | sort > ~/envdebug/bashrc.`date +%s`
```
and to the same for `.profile`:
```
mkdir -p envdebug && env | sort > ~/envdebug/profile.`date +%s`
```

then launch your vscode and see what file(s) get created... just as a way to debug this.

**Comment by tejas-2232** [comment]
What to do with this issue? seriously, man, I am freaking out due to this behavior. 
I am using Ubuntu 16.04 and I am launching it through desktop Icon. 
Yesterday I tried the following method to fix my error.

> preferences ->settings -> search for _git.terminalAuthenticaiton_ -> uncheck that checkbox-> restart VScode

It worked for that moment. But it's not working today. The same problem of shell environment.

## If you have any solution then please tell me or give any useful link/reference

###  I am working on some main projects and I need to resolve this problem as soon as possible.

Thank you in advance 💯 🤝

**Comment by wbollock** [comment]
> What to do with this issue? seriously, man, I am freaking out due to this behavior.
> I am using Ubuntu 16.04 and I am launching it through desktop Icon.
> Yesterday I tried the following method to fix my error.
> 
> > preferences ->settings -> search for _git.terminalAuthenticaiton_ -> uncheck that checkbox-> restart VScode
> 
> It worked for that moment. But it's not working today. The same problem of shell environment.
> 
> ## If you have any solution then please tell me or give any useful link/reference
> ### I am working on some main projects and I need to resolve this problem as soon as possible.
> Thank you in advance

As far as I know, the solution is to open vscode through a terminal window.

`code`

I wouldn't freak out over this behavior...

**Comment by gusandrianos** [comment]
Same thing happens to me on Pop! OS. Happens with VS Code and VS Codium, too.

**Comment by tejas-2232** [comment]
**Thank you @wbollock** 

I will try this.

**Comment by tejas-2232** [comment]
> Same thing happens to me on Pop! OS. Happens with VS Code and VS Codium, too.

ok

How long you have been using Pop OS?

**Comment by yonatan8070** [comment]
This is how I was able to solve it using KDE Plasma

1. Create a bash script `vscode.sh`:
```bash
code --no-sandbox --unity-launch
```
(I don't know why these launch arguments are there, but they were there in the original shortcut)

2. Find VSCode in the Application Launcher, right click > Edit Application > Application Tab
3. Set "Command" to `bash ~/path/to/vscode.sh`

Success! I can now launch VS Code from my shell without getting this error, and the integrated terminal works as usual.

I have to say this is the most Windowsy workaround I think I've seen since moving to Linux last week.

**Comment by Support-Green-IT-Solutions** [comment]
Probably a workaround, but i found this while launching from my terminal
launch with `/usr/bin/codium --no-sandbox --unity-launch %F` is working
where `/usr/bin/codium` is a symlink to` /usr/share/codium/bin/codium`
Change your Application launcher to resolve the problem.

**Comment by Tyriar** [comment]
This looks related to the vscode launch shell environment fetching, rather than the terminal.

**Comment by joaomoreno** [comment]
Have you followed up on the [`Learn More`](https://code.visualstudio.com/docs/supporting/faq#_resolving-shell-environment-is-slow-error-warning) link, which appears in that notification? It explains the problem and explores solutions.

If you do not want to debug your shell scripts, there are two workarounds:

1. Ignore the notification and know that features will break (eg can't debug NodeJS apps due to using nvm)
2. Launch Code from a shell

**Comment by lazarillo** [comment]
@joaomoreno , I have looked at the "Learn More", but it just tells me about things to look for to speed it up.

I actually *do not care* that it takes longer.  I am just not sure if this causes any further problems.  I would like to simply give a longer time that it is allowed to wait to resolve.  I can wait 30 seconds or even a minute:  It's not as if I am doing something that needs my environment immediately upon opening VS code.

Can I alter the setting so that it does not complain about this?  Is there any real *problem* with this "error"?  I don't care that my `.zshrc` file is slow... I have a lot of things to launch and I am OK with that.

**Comment by joaomoreno** [comment]
@lazarillo The real fix for this is #108804

We already wait for more than 3 seconds. The notification simply shows up as a warning.

**Comment by CyborgEddie** [comment]
I realize this issue is a bit outstanding but I came across it recently while trying to run demo scripts on my MacOS Mojave 10.14.6 .  (Blarg!)

I tried installing Scrapy utilizing CONDA inside the VSCode Terminal.

So... possible contributors are:
1) My current Python version is 3.9... though a few other installs are available...
   
2) I got the following returned - as condensed as I can make it - but it points to conflicts being discussed while installing Scrapy:
---
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: | 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                  
---
So the diagnostic here is the "frozen solve" appears to indicate a hardwired setup config as discussed above.
The "flexible solve" is then integrated and has some success, but not enough.

3) This all points out that there are likely too many variables which leads to the system being too vulnerable to certain instabilities without solid fixes in place for VSCode to handle "Robust" versions of Python that are reliant on other components to integrate and execute seamlessly.

4) True tech or not - things like this in tech occur far too often - but with this specific type of configuration, the eventual real solution should be viewed as a "Full Version Portal Solution" essentially handling all this issues with one component / script that can handle all of the various exceptions and compatibility issues involved while also eliminating "env shell conflicts" that appear virtually unavoidable.

5) "env shell conflicts" - case & point:
---
UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - scrapy -> python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.8,<3.9.0a0|>=3.7,<3.8.0a0|>=3.5,<3.6.0a0|3.4.*']

Your python: python=3.9

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.


Note that strict channel priority may have removed packages required for satisfiability.
---

It's all still a young technology so it's understandable on some level - but it certainly ought to be stronger without all the combinations that lead to system failure.

There likely needs to be greater steps taken to ensure a more stable system, even if it means delaying newer versions of Python, tools, etc..

In my case, I may need to revert to Python3.6 and hope for the best.
---
Final words from Eddie and The Boyz:

{RETROGRADE SUBMISSION:  Stardate:  09.29.1986}
{FUTURECAST SUBMISSION:  All Future Stardates}

"DO NOT WASTE YOUR TIME SEARCHING FOR THOSE WASTED YEARS"

{END SUBMISSION}

**Comment by lazarillo** [comment]
@CyborgEddie 

From the output you provided, it looks like this is a different issue.  It looks like you have true package versioning conflicts within Conda itself.

Dependency conflicts are challenging to resolve, and I will assume that you understand the concept.  Otherwise, I am happy to explain what is happening if you would like.

But you _should_ be able to fix this most of the time by creating environments often.  I prefer to have one Conda (or pyenv or whatever) virtual environment for each app/project/task that I am working on.  I also prefer to use _not-quite-the-latest_ version of Python.  The reason I do this is because dependency conflicts are often due to one of the following:
- Multiple packages _which aren't actually needed for the thing you are working on_ are conflicting with each other, or
- The packages you need have not had a chance to test themselves against the latest and greatest shiny new version of Python yet.
    - It is very likely the packages will work just fine.  But the package author(s) are playing it safe by saying it is not yet ready until they have been able to test and verify.

Lastly, I will say that Conda is awesome for what it is: a package manager for data science that spans multiple languages and dependencies, including compiled languages.  But it is a Ferrari and sometimes you want the Volkswagen because it is easier to maintain.  ;-p
