### ISSUE TITLE
Wrapping tabs: editor toolbar bleeds into tab when space is limited

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#113926]
As you can see here:

![image](https://user-images.githubusercontent.com/900690/103798683-56dc1d00-504a-11eb-9408-17674be9e12d.png)

//cc @SneakyFish5

**Comment by SneakyFish5** [comment]
I can't seem to reproduce this issue when decreasing the window size (or did you mean something else by "space is limited"?)

When I decrease the window size, the editor toolbar is just covered up:

![f9b5cd9fb3f802fa1dee3afbda0efa94](https://user-images.githubusercontent.com/32284796/103819210-98130380-502f-11eb-9c60-b31ea610c897.png)

**Comment by bpasero** [comment]
Easy for me to reproduce, I also see flickering:

![recording](https://user-images.githubusercontent.com/900690/103868965-f1c80c00-50c9-11eb-95da-d7a7a5767a0c.gif)

**Comment by bpasero** [comment]
I pushed a workaround, but it is a bit ugly, I would prefer https://github.com/microsoft/vscode/issues/113801#issuecomment-756034441

**Comment by DynDux** [comment]
If the editor actions are just a tab, this would be much easier and won't require hacks and absolute positioning! :-)
I created a new fiddle and tried to use the original class names and structure. I also commented the relevant css parts for the layout. Hope it is clear - otherwise please let me know what else you need:

https://jsfiddle.net/seywr7m9/
