### ISSUE TITLE
Can't download any extensions

### ISSUE THREAD

**Issue by KateAlferova** [microsoft/vscode#113995]
After migrating from Windows to MacOS and installing VCS, I can't download python (or any other) extension. The bar on the left is just empty.
![Senza nome](https://user-images.githubusercontent.com/70326953/103918323-f2cf5c80-510e-11eb-89b4-b12441922a0d.jpg)

**Comment by sandy081** [comment]
Please follow these steps

- Help -> Toggle Developer Tools -> Network
- Then check for any network failed requests while browsing and installing the extensions if found all requests fails then its probably a proxy or DNS issue at your end.
- To confirm its a DNS issue check if you can access this page https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default, if you cannot please try configuring your DNS like pointing to 1.1.1.1 as suggested here? https://1.1.1.1/dns/. Otherwise please contact your network administrator.
- If it is not a network issue, please share the logs from the following locations
    - Help -> Toggle Developer Tools -> Console
    - View -> Command Pallette... -> Toggle Shared Process -> Console
    - View -> Open View… -> Log (Shared)
    - View -> Open View… -> Log (Window)

**Comment by KateAlferova** [comment]
ok,
so here are the screens:
1. seems like no failed requests
2. all good with dns, the page opened up
3. see logs attached
(the last 2 didn't open anything)
![1](https://user-images.githubusercontent.com/70326953/104280275-f0bd2300-54ab-11eb-8782-c36d60645ad5.jpg)
![2](https://user-images.githubusercontent.com/70326953/104280284-f3b81380-54ab-11eb-8039-6284e069eb8f.jpg)
![3](https://user-images.githubusercontent.com/70326953/104280285-f4e94080-54ab-11eb-9229-a0de299bc2c8.jpg)

**Comment by sandy081** [comment]
Seems shared process related error

**Comment by KateAlferova** [comment]
so what should I do?

**Comment by joaomoreno** [comment]
@KateAlferova Can you reproduce if you restart your machine?

**Comment by KateAlferova** [comment]
yayyy! it works! thanx!
