### ISSUE TITLE
Poor highlighting of typescript code

### ISSUE THREAD

**Issue by whitecolor** [Microsoft/vscode#11398]
- VSCode Version: insiders
- OS Version: windows 10

Most of the code of my TS files are one colored:
![image](https://cloud.githubusercontent.com/assets/736697/18171997/559ddc96-707d-11e6-9572-f9375bc8131f.png)

![image](https://cloud.githubusercontent.com/assets/736697/18172011/6438a812-707d-11e6-886e-0c6fbe76c948.png)

Here is full code of the file: https://gist.github.com/whitecolor/1e31f9b33ec5c9de3ba6bec34eefb32f

**Comment by whitecolor** [comment]
See this thing because of method `switch`, comment is not higlighted:
![image](https://cloud.githubusercontent.com/assets/736697/18232601/3f0007a4-72ec-11e6-865c-6ca09c203dda.png)


``ts`
HTTP.select()
    .map(success).switch()
   // .map(r => r.body)

```

**Comment by whitecolor** [comment]
It is there more info needed? Did you check this. I just wonder if everybody experience the same poor highlighting or I have some strange specifics in may code/settings?

**Comment by emzero** [comment]
I'm pretty sure this will be fixed once the next VSCode version is released with the updated TextMate grammar files.

See this PR: https://github.com/Microsoft/TypeScript-TmLanguage/pull/270

**Comment by whitecolor** [comment]
Hope to see it soon in insiders.

**Comment by mjbvz** [comment]
I believe this is fixed by the new TS grammar in VSCode 1.7+:

![screen shot 2016-11-21 at 2 34 22 pm](https://cloud.githubusercontent.com/assets/12821956/20503470/7e8950a4-aff7-11e6-9013-6b08b515f54f.png)
![screen shot 2016-11-21 at 2 34 09 pm](https://cloud.githubusercontent.com/assets/12821956/20503471/7eaf2c66-aff7-11e6-9b03-fcfda1dba1f7.png)

Please give VSCode 1.7+ a try and let me know if you still notice any issues for TypeScript syntax highlighting. Thanks.
