### ISSUE TITLE
Blank lines in Hovers are removed

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#11409]
- VSCode Version: 1.5 (Insiders)
- OS Version: Windows 10

This was previously raised and fixed (#10311) in Insiders, but in the last few days it appears to have come back.

Here's the text I'm sending (note: I believe list item spacing is another known issue, so ignore those):

```text
_italic_ **bold**.

And some \`inline code\`.
```

Here's a screenshot from Insiders last week (good) vs Insiders yesterday (same as Stable)

![Hover spacing](https://cloud.githubusercontent.com/assets/1078012/18178855/f04a997e-7077-11e6-959a-2e7412d3269c.png)

**Comment by dbaeumer** [comment]
@alexandrudima looks like you did some fixing in hover.css

**Comment by alexandrudima** [comment]
@jrieken This was caused by c4f3544a66e45f3c4e62e46a46c5da48d76f1dbc -- I did that because I noticed TypeScript hovers were looking pretty ugly in the monaco editor.

I will refine the CSS to apply only to the monaco-editor.

## BEFORE MY CHANGE
![image](https://cloud.githubusercontent.com/assets/5047891/18200497/653d8e5c-7105-11e6-9f50-dc4e6535491d.png)

## MONACO-EDITOR NPM VERSION
![image](https://cloud.githubusercontent.com/assets/5047891/18200522/83219724-7105-11e6-95df-6c53d13a3e07.png)
