### ISSUE TITLE
go to definition gray out

### ISSUE THREAD

**Issue by game-xiaoxuesheng** [microsoft/vscode#114071]
Issue Type: <b>Bug</b>

The go to definition within the go option on the menu bar gray out and I simply cannot click it with a mouse. However, the right click -> go to definition still works, also the shortcut F12 works.
I just installed the vim extension as well as the matchit extension, so they might be the sources of this issue. However, even if I uninstalled both of them, the issue is still present.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19042

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.
