### ISSUE TITLE
Feature Request: Prominently show last commit date in Extension Marketplace

### ISSUE THREAD

**Issue by ChadBailey** [microsoft/vscode#114092]
> I have read the code of conduct

> I have searched for similar feature requests, and have not found any duplicate

Within the Extensions Marketplace interface in VS Code, I would like a way to easily and unambiguously see the last commit. This is shown on the extension page itself, but not within the VS Code interface (where I would imagine most people get there extensions).

~~The purpose for my request is a plugin, [Pytest IntelliSense](https://marketplace.visualstudio.com/items?itemName=Cameron.vscode-pytest), has 20k downloads and looks fairly legit from the description but when you see that the last commit was 2 years ago, it clearly is a dead project. Normally, I would say that's not a huge deal, but this plugin has damaged my installation of VS Code and now it has permanently caused an unresolved bug to occur within VS Code that I will have to wait who knows how long before It's resolved, given that it's been open for more than 6 months now [#12403 Running test fails trying to access non-existing file](https://github.com/microsoft/vscode-python/issues/12403).~~

Update: Turns out I was mistaken and jumped to conclusions. I definitely put lots of time in before posting, but I guess sometimes the timing is just very unfortunate. Although the issue I had was is likely unrelated to the plugin, I still would love to see this functionality added.

**Comment by sandy081** [comment]
An extension has last updated timestamp which is shown in the extension web page in Marketplace. Last commit timestamp is not supported by Marketplace.

@prashantvc FYI

**Comment by prashantvc** [comment]
@ChadBailey This is something we are considering to support in the future, but not a priority right now unfortunately

**Comment by minig0d** [comment]
> @ChadBailey This is something we are considering to support in the future, but not a priority right now unfortunately

@prashantvc curious why you don't think this should be a high priority.  Since VSCode is now getting to be a few years old, there are many many extensions that show up in the store that are abandoned and haven't been updated in years.

These extensions often:
1) incorporate old libraries that have security vulnerabilities
2) don't function correctly with many of the newer VSCode features (ex. multi-root workspaces and remote filesystems) and related issues caused by new/deprecated API's
3) are unlikely to be updated in the future at some point

Consider the average user workflow... for example, I was just looking for an extension to run Google Translate on code, typically sort by number of installs to find the more popular ones, click on one to check it out, and wind up on this screen.  Seems to look ok, but what does V0.1.5 tell me (even if we assume it follows SEMVER) I still can't tell that this extension hasn't been updated since 2018.  I can click to the repo and see it on some, but does this really seem like the best solution to what appears to be a pretty glaring issue that affects all users?

There may be alternative routes to solve it (ex. if the code is crawled and ones using deprecated things are filtered out, or maybe requiring an extension to "re-register" after a period of time so stale ones fall out... but I definitely see this as a pretty easy to fix - high importance issue.  Thoughts?
 
![2021-02-21_15h00_26](https://user-images.githubusercontent.com/54046315/108638591-95406680-7455-11eb-8c73-79c79d764522.png)

**Comment by ChadBailey** [comment]
I don't know much about the plugin writing side of things, but perhaps another solution would be to require plugins specify the versions of VS Code they work in? This would mean that extensions not kept up to date would disappear organically.

**Comment by prashantvc** [comment]
@minig0d 

> curious why you don't think this should be a high priority.

The last commit date is not an attribute of an extension. Extension author can make several commits to the source but may not update the extension in the marketplace. The activity on the GitHub does not always reflect in an extension; the last updated timestamp makes more sense in the details page compared to last commit timestamp

**Comment by minig0d** [comment]
That works.  Never looked into what populated from where.   That time stamp sounds good to me.  Seemingly accomplishes the goals and solves the problems.

**Comment by minig0d** [comment]
That could work too I guess.  Would probably be harder to implement than just grabbing a time stamp.  But sounds kind of like what Wordpress does where authors attest to it working with a specific version of Wordpress and the “store” tells you that it hasn’t been confirmed to work with the current version, etc.

**Comment by Sharkgamedev** [comment]
I was just about to open a feature request, it's invaluable for me to know whether or not an extension has been updated recently when I'm browsing it in the extension tab. I know I can just switch to a web browser but that's often sluggish.

**Comment by isidorn** [comment]
We now render the last updated info in the extensions details view
No more changes are planned here, thus closing

![Screenshot 2021-08-19 at 15 59 11](https://user-images.githubusercontent.com/1926584/130081877-c8847eba-7d5a-4f82-9e43-76fbcbe3aabc.png)
