### ISSUE TITLE
Diff Editor > Open File: Opens wrong file

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#114192]
Issue Type: <b>Bug</b>

- Have two or more files with local changes (staged or unstaged).
- Show SCM viewlet, close all files, reload window.
- Click first file in SCM viewlet to open diff editor.
- Click second file in SCM viewlet to open diff editor.
- Click 'Open File' in second diff editor's toolbar (top-right corner in editor).
-> First file opens instead of second. :bug:

VS Code version: Code - Insiders 1.53.0-insider (6dc779565e1e4a26104002fde340b68c157c3bc5, 2021-01-12T06:35:35.239Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|32.00GB (3.12GB free)|
|Process Argv|-psn_0_3851180 --crash-reporter-id 7aad610c-0e6b-48aa-ba87-b704b1b543cf|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
unique-lines|bib|1.0.0
persona|chr|0.0.3
regex|chr|0.2.0
vscode-eslint|dba|2.1.14
ghlink|dt|1.2.0
remotehub|eam|0.5.0
tsl-problem-matcher|eam|0.3.1
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.13
codespaces|Git|0.5.1
vscode-pull-request-github|Git|0.22.0
vscode-mocha-test-adapter|hbe|2.8.1
vscode-test-explorer|hbe|2.19.4
rest-client|hum|0.24.4
graphql-for-vscode|kum|1.15.3
template-string-converter|meg|0.4.5
git-graph|mhu|1.28.0
vscode-azureappservice|ms-|0.20.0
vscode-docker|ms-|1.9.0
vscode-kubernetes-tools|ms-|1.2.1
remote-containers|ms-|0.154.2
remote-ssh|ms-|0.62.0
remote-ssh-edit|ms-|0.62.0
remote-wsl|ms-|0.52.0
azure-account|ms-|0.9.4
azurecli|ms-|0.5.0
hexeditor|ms-|1.3.0
vscode-github-issue-notebooks|ms-|0.0.58
debugger-for-chrome|msj|4.12.11
vscode-versionlens|pfl|1.0.9
vscode-yaml|red|0.13.0
music-time|sof|2.0.24
vscode-open-in-github|sys|1.14.0
vscodeintellicode|Vis|1.2.10
vscode-test-resolver|vsc|0.0.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221882
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30208930
wsl2prompt:30219162
vstry244:30230484
pythonvsdeb440:30224570
unusedpromptcf:30219165
folderexplorer:30219166
openfilemenucf:30219169
pythonvsded773:30223139
pythonvspyt600:30241727
core-portspanelcf:30233468

```

</details>

**Comment by eamodio** [comment]
@bpasero 

I've tracked this down to "diffing" in here:
https://github.com/microsoft/vscode/blob/11ac71b27220a2354b6bb28966ed3ead183cc495/src/vs/workbench/browser/parts/editor/titleControl.ts#L198-L218

We are embedding the resource uri in the `MenuItemAction` options, but since we are only comparing menu ids (and none of the menu items are an instance of `ExecuteCommandAction`) we aren't updating the item with the new ones.

I'm not sure of the first here (nor am I sure why this is a new issue), as I assume we don't want to remove the diff checking altogether, and otherwise we would need to do something to account for the args when saving off the ids (a hash or something?)

**Comment by bpasero** [comment]
@eamodio something must have changed though with these actions because this was working fine a few days before and this diffing also did not change. You are right that the check for `ExecuteCommandAction` is specifically there to catch extension commands.

@jrieken @sandy081 @sbatten  maybe know more about these menu actions changing? Possibly as part of the https://github.com/microsoft/vscode/issues/92038 efford?

**Comment by eamodio** [comment]
Yeah #92038 was my guess as to what might have caused it, but still not sure what. Nothing changed with how that command it registered from the SCM side -- it is a normal extension command contribution.

**Comment by jrieken** [comment]
> We are embedding the resource uri in the MenuItemAction options, but since we are only comparing menu ids (and none of the menu items are an instance of ExecuteCommandAction) we aren't updating the item with the new ones.

The `MenuItemAction` is not extending `ExecuteCommandAction` anymore (because the latter extends from Action and is therefore disposable and comes with a lot of unneeded overhead). That change cause this breakage but I'd say checking for `ExecuteCommandAction` is wrong because that's nowhere mentioned in the menu service api, it only talks about `MenuItemAction` and `SubmenuItemAction`

**Comment by bpasero** [comment]
I removed all that code that tried to be smart for updating the toolbar. The toolbar will now update all actions whenever the menu indicates this through change event.

**Comment by jrieken** [comment]
Thanks. Way to go, the menu should really not fire unless a real change happended

**Comment by bpasero** [comment]
@jrieken so that listener is here and seems legit:

https://github.com/microsoft/vscode/blob/526f826ac14cb91c85ccdd13f3b62042dd0201fc/src/vs/workbench/browser/parts/editor/titleControl.ts#L238-L240

However we have more places, such as updating it when an extension is registered:

https://github.com/microsoft/vscode/blob/526f826ac14cb91c85ccdd13f3b62042dd0201fc/src/vs/workbench/browser/parts/editor/titleControl.ts#L111-L111

Should that not be needed given we already listen for the event?

**Comment by jrieken** [comment]
> Should that not be needed given we already listen for the event?

No, unless you populate the action bar with anything which isn't inside the menu service.

**Comment by bpasero** [comment]
No, everything is coming from the menu since a long time when I dropped our old style primary/secondary action thing. Will see if I can remove it then 👍

**Comment by jrieken** [comment]
Great. Things should just work then, a menu listens for changes to its registry and for changes of context keys. https://github.com/microsoft/vscode/blob/31a53bb2427e3eef915a965c87cb636104ed819f/src/vs/platform/actions/common/menuService.ts#L51-L67
