### ISSUE TITLE
Make Open Folder (Ctrl + O on Windows) function respect terminal.integrated.cwd setting

### ISSUE THREAD

**Issue by eodeluga** [microsoft/vscode#114119]
The setting **terminal.integrated.cwd** in **.config/Code/User/settings.json** is convenient in setting the current directory (pwd) to the path specified, for any new terminal that is opened.

Can we please have the **Open Folder** and **Open Workspace** menu items respect the **terminal.integrated.cwd** setting and open up the folder browser window at the path specified at that setting also.

Currently, when using these menu options, they always default to the user's home directory.

Can we have a dedicated setting to allow this if it is not possible / within guidelines to share the terminal setting.

Thank you.

**Comment by Sleavely** [comment]
I agree that the user folder is troublesome. I'm pretty sure this behavior changed recently, because I could have sworn it used to open up my projects folder.

I created a PR (referenced above) that doesn't _exactly_ use `terminal.integrated.cwd` because I thought that would be problematic when you have no workspace opened and that setting uses variables such as `${workspaceFolder}`. Instead it uses the CWD from when the editor was launched. On Windows this would correspond to "Start in:". Would that cover your usecase?

![Shortcut settings dialog on Windows](https://i.imgur.com/6oSUoV2.png)

**Comment by eodeluga** [comment]
@Sleavely I'm using 1.53.2 and the behaviour appears to have changed. File dialogs now seem to open from the last used location. This may be an improvement for some but it's still an inconsistent experience for me.

I think the desired behaviour should just be for dialogs to just follow the current working directory, as seen when an integrated terminal is opened.

**Comment by Sleavely** [comment]
Hmm, that's odd. The behavior for me is a bit different: https://youtu.be/_0er24zBUDI

Version info:
```
Version: 1.53.2 (user setup)
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:48:04.245Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19041
```

**Comment by eodeluga** [comment]
@Sleavely Hmm...Yes, that's how it used to behave in a prior version.

Perhaps the difference might be because my OS is Linux
