### ISSUE TITLE
Native Notebooks - navigation through notebook subtle 

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode#114219]
## Steps to reproduce:
1. Open notebook outline
2. Click through the cell headings and see where the selected cell is

When I click through the outline I have a tough time finding where I actually am in the notebook. 
1. If the cell I would like to go to is out of view, when I click it on the outline it doesn't auto-scroll such that the cell is at the top of the notebook canvas. It is somewhere in the middle of the canvas. 
2. When I look for where it is in the canvas, it took me a long time to realize the only indicator was the run button showing up. Even after realizing that was what to look for, it is a bit small and subtle. I was expecting to see the selected state (two blue lines around the cell)

**Comment by misolori** [comment]
@rebornix this is because we use `focus-within` here:

https://github.com/microsoft/vscode/blob/69a6e6ac93745990b1e5f41ca0718228efdc7918/src/vs/workbench/contrib/notebook/browser/media/notebook.css#L244-L248

So we either should show an alternate inactive selection or always show the focus (we do this in the editor with outline in other files).

**Comment by misolori** [comment]
We've introduced a new color token, `notebook.inactiveFocus`, that will appear when a cell is focused but then focus moves away from the notebook. Helpful especially around navigating via the outline view. This color currently defaults to the notebook selected cell border color.

https://user-images.githubusercontent.com/35271042/106056203-45af8a80-60a3-11eb-87d0-fc3f30c95c40.mov
