### ISSUE TITLE
Get TextDocument silently.

### ISSUE THREAD

**Issue by kantlove** [Microsoft/vscode#11424]
- VSCode Version: 1.4.0
- OS Version: Windows 10

I'm developing an extension that read the *content* and get the *languageId* of files in the project. To do that, I use this API to get a TextDocument object:
```typescript
workspace.openTextDocument(uri)
```
However, as I see, this also triggers other extensions related to the file (e.g. linters). 
Is there any way to get a TextDocument object (i.e. file content + languageId) only?

**Comment by jrieken** [comment]
`onTextDocument` will trigger the `onDidOpenTextDocument` event and we cannot change that because documents are cached and we would be at risk of never sending events to those that are interested. 

You can either read files using the nodejs API or (and that seems more appropriate) the consumer of the open event should be prepared for this
