### ISSUE TITLE
Test: terminal flow control

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#114377]
Refs #113827

- [x] wsl @sana-ajani
- [x] ssh @roblourens
- [x] web @deepak1556

Complexity: 3

Authors: @tyriar, @meganrogge 

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23114377%0A%0A)

---
**Background**
When the terminal produces a lot of data, the flow control mechanism is designed to prevent node-pty and its process from getting too far ahead of xterm.js. 

**Action:** 

> For web test in a Codespace

To verify flow control is working you can set the log level to trace and then view the log file, server or remote ext host for serverSpawn true and false respectively.

Test the following:

- Test with `terminal.integrated.serverSpawn` on and off
- Run programs in the terminal that produce a lot of data, for example:
   ```
   yes
   while true; do echo test; done
   base64 /dev/urandom
   tree
   ls -lR ~
   ```
   Be creative, try to break it if you can think of something else.
- Turn off the flow control setting `terminal.integrated.flowControl`, recreate the terminal and make sure flow control is disabled (by checking logs)

**Expectation:**
The terminal doesn't disconnect, UI remains responsive and ctrl+c is relatively responsive within the terminal.

**Comment by roblourens** [comment]
The `ctrl+c` responsiveness is awesome, but I can tell it has a large impact on the perf and smoothness of writing to the terminal. Is there any continuing work here, like changing the parameters based on latency or letting me customize the parameters?

**Comment by Tyriar** [comment]
@roblourens it only kicks in when > 100k characters are written, my thinking is if that happens and flow control makes the command take a long time, why not ctrl+c and add `| grep something`. I wasn't planning on more configuration or smarts here as it seems overkill given that when printing 100k characters, most are immediately trimmed from the top of the terminal anyway which only supports 1000 lines of scrollback by default.

If this is common feedback, if/when we get xterm.js running on the server we could theoretically run heavy commands like this in the remote xterm.js only and then synchronize xterm.js' state instead of the data events until the heavy data slows down.

**Comment by roblourens** [comment]
I think that running a giant `ls` is not a common usecase but I'd be worrie about cases like a large npm install, or a build that produces tons of output.

**Comment by Tyriar** [comment]
@roblouren I doubt npm would be approaching the levels where this would get hit, but I'm open to tweaking if we get that feedback.

**Comment by roblourens** [comment]
Well something is going to hit it, otherwise we wouldn't have added the feature 😁
