### ISSUE TITLE
Inconsistency in Selection Highlight after pressing Delete key

### ISSUE THREAD

**Issue by Eldaw** [microsoft/vscode#114464]
When pressing the Delete key to cause a line to move up, the highlighting of text doesn't work properly, according to where the caret/cursor is.

Steps to Reproduce:

1. Start with a few lines of text, with the keyboard caret on Line 1, as per the screenshot below:
![image](https://user-images.githubusercontent.com/3789849/104812976-fa24f300-57fd-11eb-9de6-b6351f50b610.png)

2. Hit the Delete key, which causes all the lines of text to shift up by one. Now, the keyboard caret is still on Line 1, as per the screenshot below. Note that nothing is highlighted.
![image](https://user-images.githubusercontent.com/3789849/104813046-79b2c200-57fe-11eb-8c53-dc31c8427e4c.png)

3. Press the down arrow and then the up arrow, so that the keyboard caret is back on Line 1 again. Now, notice that the text "3.3" is highlighted. This highlighting is expected but it is inconsistent with what happens at the end of Step 2, where nothing is highlighted despite the keyboard caret being in exactly the same place.
![image](https://user-images.githubusercontent.com/3789849/104813052-81726680-57fe-11eb-8d89-bd175ad597ea.png)

This is with version 1.52.1 on Windows 10.

**Comment by alexdima** [comment]
This is intentional. The selection highlight only wants to kick in when the cursor change reason is something we internally call "explicit". "explicit" cursor changes can be created by clicking or by arrow movements. Editing (like typing or deleting) do not result in "explicit" cursor changes so that is why the deletion does not lead to the selection highlighted to highlight. We have found this categorization useful because otherwise there would be a lot of selection highlighting as people edit their code.
