### ISSUE TITLE
VS Code opens folders instead of the file manager on some Linux distros

### ISSUE THREAD

**Issue by ishfaqfariq** [microsoft/vscode#114425]
I'm using kali linux latest version.And after installing VSC, the drive paths on my desktop are opening in VSC. The paths for drives on my desktop opens just as if its a text file. Its just happing on desktop. I can access my drives from toolbar though. But still its quite strange and uncomfortable. After talking with team, they suggested me to use VSC insider. And due to some reasons, i wasn't able to reply to them for a week. And today i checked and its doing same on both. Kindly Check it out.

https://user-images.githubusercontent.com/30369065/104754725-60b4fd00-577b-11eb-9ad9-6943c8fc3500.mp4

**Comment by ishfaqfariq** [comment]
https://user-images.githubusercontent.com/30369065/104754906-9659e600-577b-11eb-97cb-9f1fe84ec73c.mp4

**Comment by ishfaqfariq** [comment]
[Screencast 2021-01-15 21:47:28.mp4.tar.gz](https://github.com/microsoft/vscode/files/5821880/Screencast.2021-01-15.21.47.28.mp4.tar.gz)

**Comment by ishfaqfariq** [comment]
In case, if you aren't able to see the recording. kindly check this link out:
https://drive.google.com/file/d/1Lr9rsWXRHYwd_SNdRdcOY8TbLjepQ5Zu/view?usp=sharing
I've recorded the issue in it.

**Comment by Tyriar** [comment]
Last I looked into this, distros do all sorts of things when you register a mime type handler in a desktop file. Here is the responsible line, but AFAIK this is how we're meant to do it:

https://github.com/microsoft/vscode/blob/36929d3b59e37cd0f831b5db91c0b29e199143e9/resources/linux/code.desktop#L11

**Comment by ishfaqfariq** [comment]
I'm not much technical, I'm new to this distro too. Can you please explain it more. How can i fix this issue? Or you guys will fix it in new update ?

**Comment by Tyriar** [comment]
Ideally an expert who knows about this will show up to tell us what we're doing wrong. Right now we register as a handler of directories with `inode/directory` above, the question is why are we taking priority over the builtin file manager.

**Comment by ishfaqfariq** [comment]
So things are beyond my league. Sorry I wasn't much of a help.

**Comment by palexdev** [comment]
This must be fixed as a top priority
I can't open folders because VSCode opens instead, this is kinda ridicolous

**Comment by rzhao271** [comment]
Hi @palexdev, which Linux distro and desktop environment (DE) do you use?

**Comment by palexdev** [comment]
> Hi @palexdev, which Linux distro and desktop environment (DE) do you use?

I'm using Garuda Linux (Arch), GNOME edition

**Comment by rzhao271** [comment]
Did you install the `code` package using pacman, or did you download it from the website? The Arch `code` package already removes the `inode/directory` handler https://github.com/archlinux/svntogit-community/blob/packages/code/trunk/PKGBUILD#L84, so I don't think this issue should occur using that package.

On Ubuntu, when I type `xdg-mime query default inode/directory` I get `nautilus-folder-handler.desktop`. I'm wondering whether you can verify and/or reassociate the mime type following https://wiki.archlinux.org/title/XDG_MIME_Applications?

**Comment by palexdev** [comment]
I installed visual-studio-code-bin from Chaotic AUR, version 1.74.2-1

If I execute `xdg-mime query default inode/directory` the output is `code.desktop`

**Comment by Schmensch** [comment]
This is incredibly infuriating. Just installing VSCode is enough to make my complete computer almost unusable until I find the right xdg-mime command. Please fix this ASAP!

**Comment by RokeJulianLockhart** [comment]
https://github.com/microsoft/vscode/issues/114425#issuecomment-1366917481

cpe:/o:opensuse:tumbleweed:20230921 with KDE Plasma 5.

**Comment by TDuffinNTU** [comment]
KDE-Neon 5.27 here. Got this issue using the Snap and Deb versions. Note that the below workaround only works for the Deb installation method, likely because the `mimeinfo.cache` file I modified is sandboxed under snap (and possibly flatpak too).

Solution (workaround) for me was the following:

1. Open mimecache.info with your preferred editor
`kate /usr/share/applications/mimeinfo.cache ` 

2. Move code.desktop to the end of the list of applications under inode/directory:
```
-- inode/directory=code.desktop;org.kde.dolphin.desktop;org.kde.gwenview.desktop;org.kde.kate.desktop;
++ inode/directory=org.kde.dolphin.desktop;org.kde.gwenview.desktop;org.kde.kate.desktop;code.desktop;
```

3. Save the file (NB: You need to open/save the file as root!)

The fix should work immediately.

***

I'm not too sure who's responsible for fixing this. It seems that this could happen for any app that wants to assign itself as a potential candidate for opening folders. The fact it only happens on certain distros (namely KDE) suggests that KDE parses the `mimeinfo.cache` file differently to other environments such as GNOME. In which case, I'll open a bug report on their end.

**Comment by RokeJulianLockhart** [comment]
> The fact it only happens on certain distros (namely KDE) suggests that KDE parses the mimeinfo.cache file differently to other environments such as GNOME. In which case, I'll open a bug report on their end.

Please link the bugs.kde.org bug here when you do, @TDuffinNTU.

**Comment by TDuffinNTU** [comment]
https://bugs.kde.org/show_bug.cgi?id=474920

Here's the bug I've filed with KDE's xdg-desktop-portal-kde project :)

**Comment by TDuffinNTU** [comment]
> On Ubuntu, when I type `xdg-mime query default inode/directory` I get `nautilus-folder-handler.desktop`. I'm wondering whether you can verify and/or reassociate the mime type following https://wiki.archlinux.org/title/XDG_MIME_Applications?

Ubuntu has a preference of Snap packages over debs (especially as the former is suggested via the graphical store/CLI but the latter requires manual installation). In which case, it's likely modifications to `mimeinfo.cache` are being made within a sandbox (or some other location) over the host location (/usr/share/applications/mimeinfo.cache).

That _may_ be why `xdg-mime query inode/directory` may return Dolphin/Thunarr but in practice VScode still attempts to open when xdg-open is invoked from some other sandboxed apps. I noticed this manifested as "nothing happening" but using `journalctl -f` I quickly found that xdg portal was simply failing to invoke vscode:

```
[...] xdg-desktop-por[8898]: Error registering file:///[...] for com.visualstudio.code: GDBus.Error:org.freedesktop.portal.Error.InvalidArgument: Invalid fd passed
```

Whereas using the deb version, VScode launched when attempting to open Dolphin via the same button on the app I was using.

**Comment by Ammar64** [comment]
> Ideally an expert who knows about this will show up to tell us what we're doing wrong. Right now we register as a handler of directories with `inode/directory` above, the question is why are we taking priority over the builtin file manager.

Because this file specify these privileges `/usr/share/applications/mimeinfo.cache`
open it with VS Code using this command 'code /usr/share/applications/mimeinfo.cache'
press `ctrl + f` to search
search for `directory`
you will find this line
![image](https://github.com/microsoft/vscode/assets/134169730/683d2c6a-daa6-4f6b-843e-521a57ad9b49)
notice that
`inode/directory=code.desktop;org.gnome.Nautilus.desktop;`

`code.desktop` is before `org.gnome.Nautilus.desktop` that's my file manager on gnome Idk what is it on on kali XFCE
simply edit this line to look like this
`inode/directory=org.gnome.Nautilus.desktop;code.desktop;`
press `ctrl + s` to save and click on retry as sudo type your password and done

**Comment by rzhao271** [comment]
Potential upstream issues:
- https://gitlab.freedesktop.org/xdg/desktop-file-utils/-/issues/3 suggests that the order of the entries after running update-desktop-database used to be inconsistent
- https://gitlab.freedesktop.org/xdg/desktop-file-utils/-/commit/448ebe8825a9f9be6f3278fc1ca415cd26dd96d9 fixes the orders of the entries after running update-desktop-database to be sorted by name. Because code comes before org, that could be why code ends up showing up first.

**Comment by crazyboycjr** [comment]
For those who want to take a look why xdg chooses vscode over your file manager. This command could be useful.
```
XDG_UTILS_DEBUG_LEVEL=2 xdg-mime query default inode/directory
```

**Comment by Pointedstick** [comment]
Hello! I'm a KDE developer. I can confirm that VSCode should be added to the *end* of the `inode/directory=` list, not the beginning. The first entry there gets used as the default app for handling that mimetype, and this should always be a file manager, not VSCode. :)

**Comment by bzm3r** [comment]
@Pointedstick So, is this an issue on VS Code's end (i.e. is VS Code adding itself first)?

**Comment by rzhao271** [comment]
@bzm3r It's likely not an issue on our end. Here's a link to a previous comment that suggests some other issues that could be happening https://github.com/microsoft/vscode/issues/114425#issuecomment-1737681668.

I'll have to see whether there's any way code can add itself to the end of the list rather than the beginning of the list with the update-desktop-database command.

**Comment by Pointedstick** [comment]
It's complicated. There are unfortunately competing standards for how default apps are determined in the Linux world. The problem is that VSCode conforms to none of them.

**Comment by ravihlb** [comment]
@Ammar64 's solution worked for me, thanks a lot
