### ISSUE TITLE
Create folder from empty explorer

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#114402]
We should improve the flow for creating a folder from the empty explorer. The action should after creating a folder automatically open it..

Where should the action be placed?
I suggest Empty Explorer title area and command palette?
Does it deserve a large blue button in Explorer area, I think not?

**Comment by isidorn** [comment]
Missing piece is I think there is no native dialog that would give us a nice flow for creation and then Open. 
The closest thing is the already present Open dialog, which always gives the create folder button when opened.

fyi @bpasero

**Comment by bpasero** [comment]
What is the problem with first showing a native dialog for creating the folder and then simply opening it, is something missing?

**Comment by isidorn** [comment]
Seems like not. I was just not sure if there is a native dialog just for creating the folder...

**Comment by bpasero** [comment]
@isidorn oh I see what you mean. Well we basically expose all of Electron's dialog API via services iirc, so it would probably be easy to show such a dialog and then open the folder.

**Comment by bpasero** [comment]
Hm, I think there is only the "Open" one, the other for saving is for files: https://github.com/electron/electron/blob/11-x-y/docs/api/dialog.md#dialogshowopendialogbrowserwindow-options

**Comment by isidorn** [comment]
@bpasero aha, that is what I expected. So it is missing....

**Comment by gjsjohnmurray** [comment]
> The closest thing is the already present Open dialog, which always gives the create folder button when opened.

@isidorn for me on Windows it seems OK that the existing large blue button "Open Folder" gives a native dialog that includes a "New Folder" button. I can create the new folder wherever I want it, then close the native dialog by selecting it.

**Comment by isidorn** [comment]
@gjsjohnmurray yeah it seems like that is the best dialog we have in this case
Maybe there is nothing better to do...

**Comment by burkeholland** [comment]
I figured this might be restricted by the system (or in this case electron).

I suppose in an ideal scenario, there would be a "Create New Folder" button in the explorer under the "Open Folder". That action would open a dialog in VS Code asking for a location and would then re-open the editor.

@gjsjohnmurray I completely agree that having the "New Folder" button in the system dialog is acceptable. The problem is that there is an entire generation of users now who have had the file system abstracted away from them by their primary computing device. They expect VS Code to do it for them and when it can't, they don't know what to do.

Thanks for investigating!

**Comment by bpasero** [comment]
> there is an entire generation of users now who have had the file system abstracted away from them

If that assumption is true, how does it help to ask the user to create a "Folder"? Wouldn't it make more sense that you start VSCode and everything is setup, folders and files are just there in the background but not so important to start?

**Comment by isidorn** [comment]
I do not think there is anything smart to do this milestone, thus moving to backlog.
If somebody has a good suggestion I am listening...
