### ISSUE TITLE
Keyboard Shortcut prompts

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode#1144]
Provide keyboard shortcut prompts. 

Example, right click on file browser to create a new file. Show a popup explaining the key binding for that action. 

This could be turned off / on. 
Could potentially be included in the onboarding process. 
This is likely a good extension, although I am not sure if the extension API would support the operations it would need.

**Comment by alexandrudima** [comment]
To keep the number of issues in our inbox at a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: we look at the number of votes the issue has received and the number of duplicate issues filed. Thank you for your time and understanding.

P.S. If you disagree and feel that this issue is crucial: we're happy to listen and to reconsider.
