### ISSUE TITLE
New API to determine the currently focused window

### ISSUE THREAD

**Issue by hanct** [microsoft/vscode#114482]
Hi,
I would like to suggest providing an API to allow us to determine which window is currently on focus, e.g  If i have a text editor and terminal both opened at same time, they are considered to be both active.  But i need to know which one is currently on focus, so that my extensions can do the appropriate action.
*My definition of focus mean the one with the cursor currently blinking

**Comment by hanct** [comment]
If anyone find this feature useful, pls help to upvote. Thanks

**Comment by xpe** [comment]
Upvoted. I like this kind of issue because it can open up a lot of functionality to *any* extension that needs it.

@hanct Would you have time to look at the code?

1. You can get a sense for how much effort is required. 
2. You might uncover some unforeseen complications.

I think both will increase the chances that this issue gets resolved.

Finally, do you know of 2 or 3 popular extensions that would benefit from this? If so, reach out to those projects and ask for their upvotes.

**Comment by hanct** [comment]
> Upvoted. I like this kind of issue because it can open up a lot of functionality to _any_ extension that needs it.
> 
> @hanct Would you have time to look at the code?
> 
> 1. You can get a sense for how much effort is required.
> 2. You might uncover some unforeseen complications.
> 
> I think both will increase the chances that this issue gets resolved.
> 
> Finally, do you know of 2 or 3 popular extensions that would benefit from this? If so, reach out to those projects and ask for their upvotes.

Thanks. I am not aware of any extensions that would benefit from this.  I am just trying to achieve something for my own private extension, and wanted to leverage on the ability to determine the current focused window, when i encounter the above mentioned extension. 
I currently do not have spare time to look at the code to access the 2 points raised, but just curious, why would achieving both will increase the chance of getting the issue resolved?
