### ISSUE TITLE
Define variables in launch.json as if using debug console

### ISSUE THREAD

**Issue by GenHive** [microsoft/vscode#114539]
Hi, 

I want to suggest an option in the launch.json for adding variables at startup, which don't have to be parsed by boilerplate CLI.
The idea comes from the observation that I can add/overwrite variables in a running debug session by using the debug console. Depending on the number of variables, this quickly becomes tedious and time consuming, so I thought it would be nice to have an option to automate this.

I tried to find a method to do this via the launch.json, but it seems that there are only options to either define environment variables (env) or command line arguments (args).

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog and we might add this in the future. Thanks

fyi @weinand

**Comment by weinand** [comment]
@GenHive thanks for this feature request.

Passing variables from a launch config into a program via the debug console in a **generic way** (for all debuggers) is difficult (and IMO not worth the effort):
- setting variables via a DAP `evaluate` request (that's what the debug console is using) only works if the debugger is stopped. What happens if the debugger does not "break on entry" and is not stopped initially?
- Since the "set variable" syntax supported in the debug console depends on the underlying debugger, using generic key/value pairs (e.g. `{ "foo": "bar", "abc": 123 }`) in the launch config would require a translation step. An alternative would be to allow evaluate expression strings with debugger specific syntax, e.g. `"let foo = \"bar\"; let abc = 123;"`.

Supporting such a feature for a specific debugger is much simpler because the evaluation syntax and the debugger's other capabilities are well known. E.g. for node.js debugging you can use this launch config to define two variables "a" and "b"  from outside:
```js
		{
			"type": "node",
			"request": "launch",
			"name": "Launch Program",
			"runtimeArgs": [
				"-e", "let a = \"hello\"; let b = \"world\"; require(process.argv[1])"
			],
			"program": "${workspaceFolder}/hello.js"
		}
```
and use them in this "hello.js" program:
```js
console.log(`${a} ${b}`);
```

I suggest that you file the feature against a specific debugger.

VS Code will not implement this feature generically.

**Comment by GenHive** [comment]
Thank you for the explanation. I'll write a feature request on the respective debugger repo. 

Just out of curiosity, wouldn't it be possible to add this feature to something like the Language Server Protocol to make it easier to implement in a standardized way for multiple languages? Would this be feasible, or is the debugging completely separate from the LSP?

**Comment by weinand** [comment]
Yes, for the problem of translating generic key/value pairs into a "variable creation" syntax, we could employ LSP. But "variable creation" is not really a "big enough" feature. And the alternative approach of using "evaluate expression strings" in the launch.json is an acceptable workaround...  

The bigger problem is really the fuzzy semantics of the feature. And that's more a problem on the debugging/execution side. E.g. in C++ I don't think that it is even possible to introduce a new variable in the debugger's debug console.
