### ISSUE TITLE
Text color marking due to comments is inconsistent with wrap lines

### ISSUE THREAD

**Issue by jmoraispk** [microsoft/vscode#114538]
We have written the needed data into1- Write a big line that does not fit the width of your current editor window:

---------(editor width)---------------
This is supposed to be a line longer than editors width.

2- Comment line in two places, one in the beginning, one after the end of the editor width. In LaTeX commenting is with a percentage sign:

---------(editor width)---------------
%This is supposed to be a line longer than %editors width.

3- By now everything is the color of a comment. Now wrap text with Alt + Z.

---------(editor width)---------------
%This is supposed to be a line            -> this is color of a comment
longer than %editors width.                -> this is color of a comment too

4- Then take out the first percentage sign and see that only the first line gets reverted back to the original color, instead of the whole text until the next percentage sign:

---------(editor width)---------------
This is supposed to be a line          -> this line is now color of normal text
longer than %editors width.           -> this line is still color of a comment

To be clear, the problem is that the words 'longer than' are kept at the color of commented text when the comment has been removed.

I am unsure whether this due to VS code or an extension.

**Comment by alexdima** [comment]
@jmoraispk Out of the box, VS Code does not provide colorization for LaTeX. I have installed "LaTeX Workshop" to get coloring for `.tex` files and I cannot reproduce what you describe:

![TO_UPLOAD](https://user-images.githubusercontent.com/5047891/105194583-08df1300-5b3a-11eb-9f16-a9b9c6bb4ca8.gif)

I therefore believe this is caused by one of your installed extensions. In order to narrow down the possible problematic extension, please try the following:
* run `F1 > Help: Start Extension Bisect`
* (this will restart VS Code with half of your extensions disabled)
* try to do the steps which reproduce the problem
* if the problem reproduces, click "This is bad" (this narrows down the problematic extension to the half which was enabled)
* if the problem does not reproduce, click "Good now" (this narrows down the problematic extension to the half which was disabled)
* these steps will repeat until the problematic extension is found

| initial | step | final |
|---|---|---|
| ![image](https://user-images.githubusercontent.com/5047891/101918658-e9170f80-3bc9-11eb-9977-857baa291937.png) | ![image](https://user-images.githubusercontent.com/5047891/101918683-ef0cf080-3bc9-11eb-9f9e-98b0177991b2.png) | ![image](https://user-images.githubusercontent.com/5047891/101918706-f502d180-3bc9-11eb-8c86-e56355958bd4.png) |
