### ISSUE TITLE
Allow to open a diff editor even if passing more than 2 editors

### ISSUE THREAD

**Issue by YakoYakoYokuYoku** [microsoft/vscode#114568]
The CLI launcher seems to be ignoring the `--diff` flag when extra filenames are passed.

- VSCode Version: 1.52.1
- OS Version: Linux 5.10.7

Steps to Reproduce:

1. Replicate a three-way merge with `code-oss --wait --diff $LOCAL $REMOTE $MERGED`.
2. See no diff editor open, instead all files opened as if `code-oss --wait $LOCAL $REMOTE $MERGED`.
3. Try another multiple diff with `code-oss --diff a.txt b.txt --diff c.txt d.txt`.
4. Same as 2.

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
Fair request, as such -> Backlog. I am currently not having time to look into this but can revisit this once we do issue grooming iteration 👍

**Comment by YakoYakoYokuYoku** [comment]
Gotcha :ok_hand: and thanks for noticing this out

**Comment by bpasero** [comment]
To clarify, you can now open a diff from a command such as `code-insiders --diff a.txt b.txt c.txt d.txt` and it will diff `a.txt` and `b.txt` but ignore `c.txt` and `d.txt`. That is because a command line works like this:
* you have a list of files
* you set the modifier `diff´ to be true
* as such the command line is interpreted as opening a diff
* we only allow to open 1 diff

I think it would be somewhat confusing to behave any different here. An alternative would have been to throw an error back to the console, but I think this is nicer.

**Comment by YakoYakoYokuYoku** [comment]
I think I'll test this from either the CI build (nightly or maybe similar) or in the next stable release. But I do appreciate the work on this issue.

**Comment by bpasero** [comment]
Thanks, the fix will be out once we resume insider builds, likely this Friday.

**Comment by YakoYakoYokuYoku** [comment]
I've verified that if I open two C sources with the `--diff` option it works. After that I close the Insiders instance and launch it again alongside adding another C source, and the latter gets ignored as expected.

```sh
./code-insiders --diff a.c b.c # Works as expected
./code-insiders --diff a.c b.c c.c # Ignores the extra file as expected
./code-insiders c.c --diff a.c b.c # Same as above
```

Well, if I'd like to open another file in the same editor I'd just launch VSCode again but with the file in question. Anyways thank you so much for solving this issue.
