### ISSUE TITLE
Debugger doesn't recognize `konsole` as a terminal on Kubuntu

### ISSUE THREAD

**Issue by nholthaus** [Microsoft/vscode#11451]
- VSCode Version: 1.4.0
- OS Version: Kubuntu 14.04

The debugger can't start due to the following error:

> Error: unable to start debugging. No terminal is available to launch the debugger. Please install Gnome Terminal or XTerm.

IMHO, it's not a good idea to mix KDE and gnome (especially low level things like terminals), so many KDE users wouldn't have one of those two installed. Instead, vscode should recognize `konsole` as a terminal application.

Interestingly, the integrated terminal works just fine.

Steps to Reproduce:

1. Make a c++ project 
2. Configure a launch
3. Press the green triangle

**Comment by Tyriar** [comment]
There is a PR out for this from @nholthaus #11452.

@weinand are there any debug implications when adding this as a default terminal to `parts/execution`?

**Comment by weinand** [comment]
Currently every debug extension is using their own implementation of extern terminal support (if any). So this issue is a problem of the C++ debugger and I will move the issue. 

However, in the August milestone we've introduced new debug protocol API that helps debug extensions to use the integrated terminal of VS Code without having to deal with the complexity of supporting terminals on different platforms. In the future we will even support an external terminal through the same API. I suggest that debug extensions use the new 'runInTerminal' API and remove their terminal support code.

@Tyriar the terminal support in `parts/execution` is not used for the debugger. @jrieken would know best where it is used.

**Comment by weinand** [comment]
This issue was moved to Microsoft/vscode-cpptools#200
