### ISSUE TITLE
deactivate not wait event it returns a promise

### ISSUE THREAD

**Issue by 928PJY** [microsoft/vscode#114688]
Version: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:34:50.160Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT ia32 10.0.19042

Steps to Reproduce:

Using the helloworld-test-sample: https://github.com/microsoft/vscode-extension-samples/tree/master/helloworld-test-sample
1. Change the activationEvents to '*'
2. add the following changes:
```ts
export async function deactivate(): Promise<void> {
	fs.appendFileSync("D:/test.txt", "start");
	await delay(10000);
	fs.appendFileSync("D:/test.txt", "end");
}

function delay(timeout: number): Promise<void> {
	return new Promise((resolve, reject) => {
		setTimeout(() => {
			resolve();
		}, timeout);
	})
}
```

expected behavior: get the `start` and `end` in the file `D:/test.txt`.
actual behavior: only `start` in the file `D:/test.txt`

Does this issue occur when all extensions are disabled?: Yes

**Comment by 928PJY** [comment]
@alexdima Is there any update about this issue? please let me know if I can provide more information

**Comment by alexdima** [comment]
@928PJY This is expected. Extensions have at most 5 seconds to clean up after themselves. When the returned promises resolve (from all the extensions deactivate methods) or 5 seconds ellapse, the extension host process will go down. You can compare this to shutting down an OS. We have decided to give extensions time to do criticial clean up tasks, but we limit that to 5 seconds because we want users to be in control and we don't find it reasonable that 5s after clicking the x button there is still criticial cleanup tasks to do. Critical cleanup tasks examples: making a http request to stop other services that burn up money if they stay running, releasing OS locks and resources (child processes).

If you really really really need to clean up for longer than 5 seconds, you can spawn an orhpaned child process to do the cleanup for you. 5 seconds is sufficient time to spawn it. In the past, when I received such complaints about the time limit, it always turned out that people have a misunderstanding about what an extension should do in its `deactivate` method. What exactly are you trying to do that would take such a long time?

**Comment by 928PJY** [comment]
@alexdima OK, if that is by-designed, I accept that, the workarounds you mention is worth trying.

But before that, there is another problem with the deactivate function, it never got called on the mac. You may be able to repro that with the sample I mentioned above, on the mac the `start` and `end` both not output. with that, the `runTest` function will never finish on the mac.
let me know if I should create a new bug for this.

**Comment by alexdima** [comment]
>there is another problem with the deactivate function, it never got called on the mac when it runs inside the test

Let's track in #96090
