### ISSUE TITLE
Cursor jumps to end of the line when typing before a # in the command palette

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#114680]
![image](https://user-images.githubusercontent.com/641685/105276327-1fec2800-5b6f-11eb-82b9-ba6de238c451.png)

Trying to type before the `#` in the command palette causes the cursor to jump to the end of the line.

**Comment by bpasero** [comment]
Weird, only seems to be happening for the first character, not subsequent ones. Haven't fully looked into this but might be a bug.

**Comment by hbibkrim** [comment]
After some investigation, the cause of this seems to be due to the `quickAccesProvider` changing here - https://github.com/microsoft/vscode/blob/master/src/vs/platform/quickinput/browser/quickAccess.ts#L146

In this scenario, it is switching from `GotoSymbolQuickAccessProvider` to `AnythingQuickAccessProvider` which updates the value selection and jumps the cursor to the end of the line.

It's also replicable when using any other PREFIX such as `>` or `@`

**Comment by bpasero** [comment]
Yeah thanks for finding, that code is there for a reason, specifically to allow to cycle through different quick access providers and always having the cursor at the end. Changing it there would probably break other features, so I am inclined to keep this as is.

**Comment by eamodio** [comment]
How do you "cycle through" the providers? The experience here is not good, especially if you are trying to switch between >, @, #, etc

**Comment by bpasero** [comment]
@eamodio via commands, it is possible to configure commands that fill in text to the picker and if the picker is opened, this will just replace the text inside the picker and move the cursor to the end. We currently do not distinguish between the user typing and this happening through a command.
