### ISSUE TITLE
onDidChangeBreakpoints event not triggered by adding function breakpoints

### ISSUE THREAD

**Issue by kevingty** [microsoft/vscode#114607]
- VSCode Version: 1.49
- OS Version:

Steps to Reproduce:

1. add function breakpoint in BREAKPOINTS section by entering the function name
2. **onDidChangeBreakpoints** event not triggered, no log printed under test code

Does this issue occur when all extensions are disabled?: Yes

Hi, I'm developing my own debug extensions. I'd like to use **onDidChangeBreakpoints** event to show breakpoint info message on screen. Seems it works well with source breakpoints when clicking on editor, but the event doesn't work when it comes to Function breakpoints cases. [VSCode debugging docs](https://code.visualstudio.com/docs/editor/debugging) shows the only way to add function breakpoints is by using BREAKPOINTS section. Would you please take a look at this? Or is there any other event triggered by adding function breakpoints in the section? Or any workaround?  Thank you. @weinand @isidorn

**Comment by mih30vip** [comment]
it's a issue

**Comment by isidorn** [comment]
@weinand let me know if you would like to investigate this.
I just quickly checked, and we are sending a `onDidChangeBreakpoints` when a new function breakpoint is added.
Technically we send a `onDidChangeBreakpoints` first when a new function breakpoint is added without a name, once user enters the name in the input box we send another event.

**Comment by weinand** [comment]
@isidorn yes please, it would be great if you could investigate. Thanks!

**Comment by isidorn** [comment]
Since adding a function breakpoint for VS Code is a two step process, first the empty input is created and then the name gets set.
Thus VS Code first sents an BreakpointUpdate event with the `added` for the new function breakpoint, and then another event with the `updated` once the name gets set.
I have just made sure this works, and have also removed an error being thrown (since it was checking if the functionName is truthfull, which is not true since exception breakpoints are first set with an empty `""` name)

@kevingty please get latest vscode insiders from tomorrow and try it out
@weinand if we want to change this two event being sent out than the `mainThreadDebugService` would need to have a bit of smartness to not sent the first added event, and the next update to transform to add. Though I did not do this for now as I am not sure it is really necessery

**Comment by kevingty** [comment]
@isidorn Thanks a lot.  Which branch or commit did you push the fix to ? Can it be viewed ?

**Comment by isidorn** [comment]
The commit is traced in this issue, it is pushed on master.
Here's the commit https://github.com/microsoft/vscode/commit/543af670531f1b1c13e30c840c233d14602f5da4

**Comment by kevingty** [comment]
It works. Thanks. @isidorn

**Comment by isidorn** [comment]
Lovely thanks, adding verified label.
