### ISSUE TITLE
'Resolving your shell environement is taking very long' shown in every window

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#114622]
Suggest to show the warning only in the active window and not in every window

![image](https://user-images.githubusercontent.com/172399/105151527-5cd00480-5b06-11eb-8516-4919a2b0515f.png)

**Comment by bpasero** [comment]
It will now be shown in the active window and also only ever once per session.

Note that there is also an error notification that shows when we give up to resolve the shell environment (after 10s). That one will still show in each window because it basically means the window has no shell environment to use which can result in all kinds of issues.
