### ISSUE TITLE
Improve UX For Resizing Editor Suggestions Box

### ISSUE THREAD

**Issue by miketromba** [microsoft/vscode#114636]
Hello, thank you for your great contributions to VS Code!

Recently in the /r/vscode subreddit, [a post was made](https://www.reddit.com/r/vscode/comments/l0gxhk/vs_code_showing_only_one_axample_as_in_picture/) by a user who was only getting a single editor suggestion while typing. The problem was that the the user must have inadvertently minimized the box in the past, and now had no idea how to restore it to its original size. This happened to me too a while ago, and I went a while without having a good solution to the problem. 

Image from reddit post: 

![image](https://user-images.githubusercontent.com/25141252/105192260-e8956100-5b05-11eb-80ad-fa0a14eb67c3.png)

Judging by the amount of upvotes on the post (50+ at the time of writing this) I imagine that this is an issue that many VS Code users experience and are confused about at some point. Its also easy for the user to assume that there is just a single suggestion, and decide to disable the box altogether since it's not as useful as it once was.

Is there some simple way to improve the UX without too much trouble? Maybe something like the drag handle UI that shows in the bottom right corner of HTML text areas?

![image](https://user-images.githubusercontent.com/25141252/105192304-f34ff600-5b05-11eb-8c74-ffe4f0f9eaf2.png)

**Comment by jrieken** [comment]
Thanks for reaching out. Yeah, somehow folks run into the "resized to single line" case and I do agree that this is a problem. What I very very keen on knowing is how folks get into this state. Is there a bug in my persist/resize logic or do people unknowingly resize stuff?

Tho, for the next release I have pushed a poor mans fix which is so that sizes below a minimum height aren't persisted anymore. I have used 4.3 - a fraction on purpose so that you can see a little bit of the next item. 

What also helps, is to make the resize-sash visible on hover. Our theme don't have a color defined so that are "invisible" but this is what I use and how it looks (mouse not captured, but resizing the width)

```
"workbench.colorCustomizations": {
	"sash.hoverBorder": "#5a505042"
}
```

<img width="550" alt="Screenshot 2021-01-20 at 18 16 29" src="https://user-images.githubusercontent.com/1794099/105211086-274e0a00-5b4c-11eb-943c-61caefd631e4.png">


Adding @misolori for the proposed drag handle UX. I actually like it and I think it makes sense to have something like that. Too many user have been confused

**Comment by aktoriukas** [comment]
Hi,
<-- that's actually me who created a post on Reddit.
I believe that happened ( at least in my case) with one of the extensions, it's difficult to say, which one as I was ok with a single line of example for a long time. And even though that it's an extension 'feature'.  Never the less, resizing with a mouse never even came to my mind. As mentioned above some indication for the option to do it would be an improvement.

**Comment by misolori** [comment]
The drag handle is typically used for text inputs, not sure if that would work well here. I'd be in favor of adding a sash hover color for our default themes but I think @joaomoreno wasn't a fan of this. I'd say we need to make sure that the resizing indicators match the rest (sidebar, panels, editors, etc.) and the sash color is one that spans all of those.

**Comment by joaomoreno** [comment]
> I'd be in favor of adding a sash hover color for our default themes but I think @joaomoreno wasn't a fan of this.

Might just be me! Let's experiment!

**Comment by jrieken** [comment]
Another thing that we could try to experiment with is to highlight all sash when they are connected. E.g in the suggest widget when hovering over the horizontal sash also highlight the veritical sash and vice versa

**Comment by misolori** [comment]
So here's one thing we can try, I played around with setting the sash hover color using an existing color and `focusBorder` seemed to be the best color that other themes also included. Here's what that looks like:

![image](https://user-images.githubusercontent.com/35271042/105427881-fbda2680-5c02-11eb-9707-604654109203.png)

![image](https://user-images.githubusercontent.com/35271042/105427897-0399cb00-5c03-11eb-83b3-30a36d9c8d48.png)

And then how it applies for the rest of the workbench:


https://user-images.githubusercontent.com/35271042/105428063-6b501600-5c03-11eb-9528-322cddbb8f0f.mov

Since we're at the end of the iteration I think we should wait until the next milestone to try this out.

**Comment by aktoriukas** [comment]
Looks good and consistent.

**Comment by misolori** [comment]
Alright, I just enabled this for all themes. Let's try it out and see how it feels.

**Comment by jrieken** [comment]
This happened with @joaomoreno's changes. Thanks
