### ISSUE TITLE
Settings Sync: extensions enhancement

### ISSUE THREAD

**Issue by af4jm** [microsoft/vscode#114693]
I would like the ability to sync extensions but NOT sync their enabled state...

I have one underpowered PC that I use as my tablet, and with dozens of unneeded extensions loaded typing is slow on that machine... but if I disable extensions there, they disable on my dev machines where I need them... if I exclude extensions from syncing, then I have to manually keep them in sync between my 2 dev boxes (personal & employer's)

**Comment by xpe** [comment]
@af4jm I think I understand your use case. Would you be able to suggest one or two concrete ways you would like this to be implemented?

**Comment by af4jm** [comment]
2 ways I can think of...

have an additional option to "sync which extensions are disabled" (and that option would only be enabled if "sync which extensions are installed" is turned on)

the extension settings menu menu, in addition to "Disable" and "Disable (Workspace)", could have another option "Disable (don't sync)" (or "Disable (this machine only)"... I can't really think of a great way to phrase that)

**Comment by xpe** [comment]
To start, without going into *how* we should label the settings, I wanted to make sure I understand the complexity involved.

As a first-level approximation, does this table represent the possible interactions in a sync group containing machines X, Y, and Z? Let's say X is the upstream (the one making changes) and Y and Z are downstream.

| Machine X             | Machines Y & Z    |
| --------------------- | ----------------- |
| install extension     | install extension |
| remove extension      | remove extension  | 
| enable extension      | depends           | 
| disable extension     | depends           | 

I write "depends" because the depends on *local* settings on machines Y and Z.

Please let me know if this is accurate or needs changing.
