### ISSUE TITLE
Smoke Test: Text inside suggestions is not highlighted (Windows)

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#11466]
![intellisense-highlight](https://cloud.githubusercontent.com/assets/5047891/18209712/3ce528e0-7135-11e6-997c-fe1ea8ec3056.gif)

**Comment by jrieken** [comment]
We always try to compute highlights based on the label [first](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/suggest/common/completionModel.ts#L136) and then fallback to the [filterText](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/suggest/common/completionModel.ts#L141). 

It seems that the JSON mode always replaces the leading quote character meaning the label differs the portion we filter against. Since we only match against the filterText we can't really compute highlight for the other string (label)

**Comment by jrieken** [comment]
@aeschli Insight why JSON replaces the quote? Do you have ideas how else this should work?

**Comment by aeschli** [comment]
The string literal starts with the quote and I just always replace from the start of the token. If it were replaced by a number, boolean, null or what ever, it's what needs to be replaced (not in this example, obviously).
I understand that the replaced string is not a prefix of the the label, but there are substrings matches. Don't we highlight these as well?

**Comment by jrieken** [comment]
related to #11423
