### ISSUE TITLE
Reload required before tasks schema picks up new extension task types

### ISSUE THREAD

**Issue by ucheNkadiCode** [microsoft/vscode#114793]
- VSCode Version:
- OS Version:

Steps to Reproduce:
I am in VS Code spaces on the browser.
1. Create a new Codespace using https://github.com/ucheNkadiCode/codespaces-docker-python
2. Make sure Docker extension and Python Extension is installed
3. `Ctrl + Shift + P` Add Docker files to workspace
4. Select any random file (it doesn't matter) but manage.py is preferred
5. Take a look at the tasks.json and there are plenty of  yellow warnings
![image](https://user-images.githubusercontent.com/20650058/105538162-dbb07300-5ca7-11eb-821a-7b6581d88d0c.png)

Has the schema for 2.0.0 tasks.json been changed or something? I wonder why this is the case

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by alexr00** [comment]
If I add this setting then the issue does not occur:
```
	"remote.extensionKind": {
		"ms-azuretools.vscode-docker": [
			"workspace"
		]
	}
```
@sandy081 is this something that the Docker extension can do?

**Comment by ucheNkadiCode** [comment]
@bwatersmsft Is this a change our extension would need to make?

**Comment by bwateratmsft** [comment]
We intentionally stopped specifying the extension kind in our package.json, so that way it would default to workspace _and_ act disabled unless it was installed in the remote, but could still be forced into UI mode with a setting. https://github.com/microsoft/vscode-docker/pull/2422 / https://github.com/microsoft/vscode-docker/issues/2356. We found that if the setting was specified with workspace and UI, even if workspace was first, it would automatically "work" in UI mode within a remote session but that was almost never what users actually wanted.

**Comment by sandy081** [comment]
@alexr00 I do not understand how changing the extension kind has fixed it.. Seems I am missing something here.

**Comment by alexr00** [comment]
Looks like the extension kind was a red herring. The issue is that tasks currently requires a reload before updating the json schema to include the newly installed extension provided task types.

This is not Codespaces or even remote specific.
