### ISSUE TITLE
Native Notebooks - Cell Toolbar Covering Markdown Content

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode#114730]
When cell toolbar is on the left it covers the markdown content. 

![image](https://user-images.githubusercontent.com/19276747/105424816-ed890c00-5bfc-11eb-97fe-fd4333724099.png)

**Comment by misolori** [comment]
This is one of the downsides of having it on the left, which is why we default it to the right where it is less likely to happen. But this is also one of the offsets of making the toolbar overlap the cell so this is inevitable:

![image](https://user-images.githubusercontent.com/35271042/108085789-8d825b80-702a-11eb-93f8-cf746378c978.png)

Closing as `won't-fix` as we knew this would come up with the design of the cell toolbar. We didn't want to add more vertical height to the entire notebook and show less content so the overlap was the compromise.

**Comment by claudiaregio** [comment]
Won't users have to scroll either way (with additional vertical height or without) unless their entire notebook's content fits on their screen?

**Comment by misolori** [comment]
Yes, since the toolbar appears on hover + focus you'll need to move your cursor to see that portion. This is one of the trade offs for keeping the vertical height compact.

**Comment by claudiaregio** [comment]
What I'm hoping to understand is how vertical height being compact was decided to be more important than content being covered. 

My first thought was since users have to scroll either way (it is pretty unlikely their entire notebook's content fits on their screen height) then adding additional vertical height would be less of a negative impact than covering content that makes the notebook look broken/glitchy (for both the left and right cell toolbar situations). Also as the cell toolbar contributions become longer it will cover more content in the markdown cell making it even harder to process the content.

**Comment by misolori** [comment]
Density is very important to the overall product aesthetic, this isn't specific to notebooks. When we were exploring the position of the toolbar, we tried increasing the vertical padding of the cells, moving the toolbar above the cell, and in every area we attempted to move it made the overall notebook look unpolished. Additionally, when the toolbar is farther from the content it starts to overlap with the cells around it and can be confusing, like so:

![image](https://user-images.githubusercontent.com/35271042/108247399-71a0b780-7107-11eb-91fc-00deea09e44a.png)

With the toolbar being on the right as a default, there was a less chance of content being covered. And in the code cells, we have an additional padding inside that prevents this from overlapping where there are more actions likely to appear, as opposed to rendered markdown text:

![image](https://user-images.githubusercontent.com/35271042/108247646-c5130580-7107-11eb-8feb-eef45d9cbc99.png)

**Comment by greazer** [comment]
In my experience, density and polished-ness of a UI presentation are both highly subjective measures. This is fine to won't fix for now; however, I suspect that this will be a common complaint from our customers. If so, we will likely need to revisit. If not, then all is good.

**Comment by ronglums** [comment]
@misolori Totally agree with the vertical density being super important. I wonder if there's a way for us to satisfy both needs - perhaps by moving the floating menu up / down by a few pixels, just enough so it doesn't cover up the content. 

for example, how do we feel about moving the menu vertically to the red rectangle below? This seems enough to reveal the markdown text without having to increase vertical space in the notebook editor.
![image](https://user-images.githubusercontent.com/26419852/108271827-411c4600-7126-11eb-809c-9d10023708ef.png)

**Comment by misolori** [comment]
I can move it up about 4px but it still won't cover most the areas without needing to make further adjustments:

![image](https://user-images.githubusercontent.com/35271042/108282171-facee300-7135-11eb-9d2e-1e58b64ddd44.png)

And just to clarify: this overlap has been part of the notebook design from the beginning so this is not a new change and users have already been seeing this.

**Comment by ronglums** [comment]
Thanks @misolori. Moving 4px up definitely helps. Curious how it will look like on LaTex. We can revisit when LaTex support is in. 

Understand we have shipped the design this way to customers, however the number of users who have seen this might still be very small given left isn't the default.

**Comment by misolori** [comment]
I took another look and was able to slightly tweak the padding of the cells, move the toolbar, and shorten the bottom cell toolbar to accommodate the changes. I think this will slightly improve the overlap, though at this point we can't really go any taller or move the toolbar. The tricky part here is that if you move the toolbar higher for markdown cells, it looks out of place for code cells. And because they both share the same position, any change affects both. Here's an example of the change:

![Kapture 2021-02-17 at 22 47 52](https://user-images.githubusercontent.com/35271042/108316864-528b3f80-7172-11eb-95f4-bf282df6b13b.gif)
