### ISSUE TITLE
Revisit resolveRemoteUri vs resolveRemotePath

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#114752]
I recently came across spaghetti-code in `windowsMainService` around opening/handling remote paths and or URIs. I tried to cleanup and extract the remote handling and the local handling.

Then I noticed that we also distinguish between `URI` and `string` paths on startup. We even support `remoteAuthority` when you have a `string`, which I do not fully understand how that is possible (can you provide a path as CLI argument and a remote authority to use?)

Anyway, what is fishy is that both methods seem to massage remote URIs but different:

https://github.com/microsoft/vscode/blob/4c0a4179e6e170a2f45526adfff434a5a7e00a07/src/vs/platform/windows/electron-main/windowsMainService.ts#L844-L851

and

https://github.com/microsoft/vscode/blob/4c0a4179e6e170a2f45526adfff434a5a7e00a07/src/vs/platform/windows/electron-main/windowsMainService.ts#L920-L945

I wonder if both should align and share the same logic.

**Comment by aeschli** [comment]
We support the following:
`code --remote wsl+Ubuntu /home/jim/projects/c` : The path is a path on the remote and because we can not stat it, we need to  'guess' if it is a folder, workspace or file

That's what the second code snippet is about (line 921)

Also supported is
`code --folder-uri vscode-remote://wsl+Ubuntu/home/jim/projects/c`

**Comment by aeschli** [comment]
I did some more polishing of the open the code when I added `remoteAuthority` as argument for `WindowsMainService.open`.

There's admittedly lots of spaghetti left, but I think it's in a ok state. No further refactoring planned from my side.
