### ISSUE TITLE
files.exclude with a subdirectory in the workspace behaves inconsistently in the explorer

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#114869]
On the latest insiders:

1. Clone [this repo](https://github.com/connor4312/vscode-114869) and open the workspace
2. Open b/c.txt
3. The "b" subdirectory appears under the first folder and the the "b" workspace folder collapses
4. Open a.txt. The b subdirectory disappears

Video: https://memes.peet.io/img/21-01-0a7e7e40-4762-482d-a3f3-ada86dee68c6.mp4

**Comment by isidorn** [comment]
This is an older bug, however let's assign to this milestone since you provided great repro steps and I might have time during endgame to fix.

**Comment by isidorn** [comment]
@connor4312 thanks for great steps!

We have the following heuristics:
1) It is not possible to hide a workspace root using `files.exclude`. And due to that the B folder is initially shown
2) Once a file is open, we show it's parent path in the explorer (even if they are hidden)

Due to those two facts you see this weird behavior in the repo.
I am open to change any of these two. However 2) is a nice feature imho. And 1) we could potentialy just stop doing

I think the biggest problem is the auto collapses - expands which are unintuitive. We can also look into fixing just that part.

Let me know what you think

**Comment by connor4312** [comment]
I agree (2) is usually nice, e.g. if I'm looking at something in my node_modules. (1) sounds fixable.

**Comment by isidorn** [comment]
@connor4312 thanks for feedback. For now I have changed that the root can also be hidden.

There is still some corner cases with expand / collapse but there is a seperate issue tracking that when there is a MR workspace with one folder being a subfolder of another root.
