### ISSUE TITLE
Running an untitled (unsaved) file, prompt to save each time

### ISSUE THREAD

**Issue by KristofStroobants** [microsoft/vscode#114890]
Issue Type: <b>Bug</b>

Hi,

I've been using VScode Insiders & exploration versions for about 2 years.
Only had one issue with them in the past, but now since a week or 2-3, each time i try to run some Powershell code without saving it, VScode prompts me for a 'save as'. I can get passed it by pressing escape but that gets old real quick.

See my gif for a visual representation of this issue.

![VScode_saveAS](https://user-images.githubusercontent.com/27337260/105681194-178a4900-5ef1-11eb-8a85-1843decae45a.gif)

I have thse in both versions of Insiders & Exploration.

I do not have it in the up-to-date vanilla version so far.

VS Code version: Code - Exploration 1.53.0-exploration (0c9e2dadd986d0bc085f1c5352245531eef65e84, 2021-01-07T06:32:42.179Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (5.75GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
gitlens|eam|11.1.3
notepadplusplus-keybindings|ms-|1.0.5
powershell-preview|ms-|2020.9.0
hide-gitignored|npx|1.1.0
material-icon-theme|PKi|4.5.0
gitblame|wad|6.0.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221882
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30208929
wsl2promptcf:30219163
vstry914:30244316
pythonvsdeb440:30224570
unusedprompt:30219164
folderexplorer:30219166
openfilemenucf:30219169
pythonvsded773:30223139
pythonvspyt875:30247033
core-portspanel:30233467

```

</details>

**Comment by isidorn** [comment]
@KristofStroobants thanks for letting us know, but this is designed behavior now. More details here https://github.com/microsoft/vscode/issues/111850

What I do not understand is how was this working before? The powershell extension can not reach any unsaved files?
Are you saying that F5 an unsaved file works with VS Code stable?
@TylerLeonhardt is the powershell extension doing something special here?

**Comment by TylerLeonhardt** [comment]
@isidorn yes the PowerShell extension is able to debug untitled files. This is because the language server and debug adapter come from the same process: the PowerShell integrated console which is a special instance of PowerShell that can handle user input via the integrated terminal and LSP/DAP messages at the same time.

We did we enable untitled file debugging?

1. People could do similar things in the PowerShell ISE editor
2. Untitled files, the concept, can be confusing to the user

**Comment by isidorn** [comment]
Okey, I was not aware of this fancy capability. Thanks for explaining.

No we did not enable untitled file debuging, since no other debug adapter supports this other than powershell, so we changed that when you start debugging if you have an untitled file we prompt the user to save the untitled file. So the debugger could actually debug it.
I understand that this does not really work for powershell, but imho this is the right behavior in general.
So for now I would not change this. If we see that a lot of users use this debug untitled powershell file feature, then we can introduce some capability "canDebugUntitled" which the powershell can set to true, and if that is the case we would not prompt

**Comment by TylerLeonhardt** [comment]
@isidorn an untitled file is just a file with `untitled:` uri scheme. DAP doesn't specify that `Uri`s need to _not be_ `untitled:` or that it has to be `file:`.

It would have been nice to have a mechanism to opt in for this behavior or something as it gives folks more friction to switch from ISE to VS Code.

**Comment by isidorn** [comment]
@TylerLeonhardt good points. 
As mentioned we can introduce a mechanism to opt out of this. I am not sure if it would be a setting or a capability or something else.
@weinand for thoughts

**Comment by KristofStroobants** [comment]
Hi guys,

Thanks for getting back to me on this!

**would have been nice to have a mechanism to opt out for this behavior or something as it gives folks more friction to switch from ISE to VS Code.**

Yes indeed. I really miss this feature. Half of the time I write code, i run it and throw it away. Like you said, just like you'd do in ISE.
I script almost daily so this is a daily annoyance. Luckily the vanilla version still works with unsaved files but i'm guessing it'll only be a matter of time before that goes away too :( . 

Isn't there a way to find middle ground? Opt-in or Out via a user-setting? Pretty 🙏🙏

**Comment by isidorn** [comment]
Let's do something about this in February since more users are complaining. Thus assinging to February

Implementation wise when I save I have not yet started debugging so I am not even sure what adapter I will use.
So from my side the simplest would be to introduce a setting so users would disable this.
Even though I think the nicest would be that the powershell extension is just able to set this and users would not worry about this

@TylerLeonhardt @weinand let me know what you think.

**Comment by TylerLeonhardt** [comment]
Could `vscode.debug.registerDebugAdapterDescriptorFactory` have an optionial parameter to set `supportsUntitledFiles?: boolean`?

**Comment by weinand** [comment]
@TylerLeonhardt how is PowerShell's "debugging untitled files" feature implemented? Is it using the `debug.startDebugging` API? If yes, we could introduce a new flag on the option bag.
@isidorn or is this too late fro preventing the save operation on untitled files?

Alternatively we could introduce a new property `supportsDebuggingUntitledFiles` on the `Debuggers` contribution point.

**Comment by isidorn** [comment]
@weinand `debug.startDebugging` is not too late, an option there would work nicely.
A static contribution point would also work, but at the moment I save I am not 100% sure what debugger I would use. So if there is one `Debugger` installed that has `supportsDebuggingUntitledFiles` then I would treat it as every installed debugger has it. I could look intro resutrcturing the code, but might prove to not be easy, since based on an active file we choose which debug to use, and in order to have an active file we first save....

**Comment by TylerLeonhardt** [comment]
> how is PowerShell's "debugging untitled files" feature implemented? Is it using the debug.startDebugging API? If yes, we could introduce a new flag on the option bag.

I don't think so. The "untitled file" has the language set to PowerShell so striking F5 just goes through the normal debugging flow AFAIK.

> Alternatively we could introduce a new property supportsDebuggingUntitledFiles on the Debuggers contribution point. IMO this feature is really static and does not need a dynamic (i.e. extension) API.

Yeah this would be nice.

**Comment by weinand** [comment]
@TylerLeonhardt thanks for this info.

This probably means that the PowerShell extension handles the "run current file" via the `resolveDebugConfiguration` method of a `DebugConfigurationProvider`. Within that method, it is too late to prevent the "Save untitled files" from happening. Even the suggested `vscode.debug.registerDebugAdapterDescriptorFactory` is too late for this.

If we do not want to introduce a new setting for this feature, the only way to solve this is by delaying the "Save untitled files" operation until we have determined what debugger to use (and then could look for a `supportsDebuggingUntitledFiles` property in the associated debugger contribution from the package.json).

**Comment by KristofStroobants** [comment]
If you guys needs someone to test something, just give me a buzz.

**Comment by isidorn** [comment]
Since only 2 users complained thus far I suggest we introduce a setting:
```
debug.saveBeforeStart: allEditorsInActiveGroup | nonUntitledEditorsInActiveGroup
```
Then the Powershell extension could even change this setting for the user.
Let me know what you think and if you have better naming suggestions. Thanks!

**Comment by zrbrc** [comment]
This is an annoying new feature. Running some quick throw away code, I don't want to or need to save it. An option to disable this would be great.

Thanks.

**Comment by pjaden** [comment]
For system admins using PowerShell, being able to load generic script from a file, make modification that do not need to be saved, then execute that changed code is very useful. 
Otherwise, the admin/user would need to start managing many versions of the code or add logic to the code for the changes.
An option to keep the old behavior, i.e. run the code without saving the file, would be great.

**Comment by isidorn** [comment]
We have introduced a setting `debug.saveBeforeStart`.
To verify: make sure this setting behaves as expected

Also would be great if somebody from the Powershell community can try it out with VS Code insiders from tomorrow
fyi @TylerLeonhardt

**Comment by KristofStroobants** [comment]
I'm not seeing the option just yet. I'll check tomorrow and report back.

**Comment by KristofStroobants** [comment]
Confirmed that this works on the following version:

![image](https://user-images.githubusercontent.com/27337260/108829281-4404b400-75c8-11eb-8fef-b0420c5d15ec.png)

Version: 1.54.0-insider (system setup)
Commit: bd74308b5abbbb2f5a5df0f0d8a3bef606652d36
Date: 2021-02-23T05:16:26.487Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.18363

Thanks a bunch guys!!! 🙏🙏🙏🙏

**Comment by isidorn** [comment]
@KristofStroobants lovely thanks! Adding verified based on your comment.
@weinand @TylerLeonhardt let me know if you have better setting name suggestions
