### ISSUE TITLE
Test hover lacks padding

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#114925]
![image](https://user-images.githubusercontent.com/2193314/105738624-1571bb80-5eec-11eb-91f4-9259a5a12609.png)

**Comment by connor4312** [comment]
This is the `glyphMarginHoverMessage`, cc alex

**Comment by goldst** [comment]
It looks like this happens because the hover label doesn't contain a node with `.hover-contents`, which effectively would add padding. Adding that class to all `.hover-row` nodes [here](https://github.com/microsoft/vscode/blob/f21a3b95e6a92f59d1264432fce4dcb2af43e080/src/vs/editor/contrib/hover/modesGlyphHover.ts#L174) solves that issue. Can I make a PR?

**Comment by alexdima** [comment]
@goldst Thank you for figuring that out! There is some debt in this area that I would like to refactor. `GlyphHoverWidget` should be collapsed into `ModesGlyphHoverWidget` and the outcome of that needs to be refactored to reuse the `HoverWidget` from `src/vs/base/browser/ui/hover/hoverWidget.ts`. It would not be good to add class names to a widget that refer to CSS defined in other files. Given the needed refactorings, and the high chance of conflicts, I would say please hold off on a PR in this area, I plan to tackle this probably next week.

**Comment by rchiodo** [comment]
/verified

![image](https://user-images.githubusercontent.com/19672699/135539659-f76edf92-c2c6-4a3a-ac4a-b6c9ca666820.png)
