### ISSUE TITLE
Ctrl/Cmd+Z command hijacked by webview contrib in notebook

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#114959]
Issue Type: <b>Bug</b>

* Open GitHub Issue Notebook
* Make some changes, put focus on the list view (not in any editor)
* CMD+Z, nothing happens

From debugging, the webview /vs/workbench/contrib/webview/browser/webview.contribution.ts#L15-L21 steals it.

VS Code version: Code - OSS Dev 1.53.0 (Commit unknown, Date unknown)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (17.06GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
codespaces|Git|0.3.1
dotnet-interactive-vscode|ms-|1.0.160901
vscode-dotnet-runtime|ms-|1.0.0
jupyter|ms-|2020.12.406427339-dev
notebook-renderers|ms-|0.0.1
remote-ssh|ms-|0.58.0
remote-ssh-edit|ms-|0.58.0
remote-wsl|ms-|0.52.0
vscode-github-issue-notebooks|ms-|0.0.58
vscode-markdown-notebook|ms-|0.0.13
jupyter-notebook-renderer-geojson|reb|0.0.1

</details>

**Comment by mjbvz** [comment]
If notebooks always want to handle the undo, I believe they just need to set their [command override priority](https://github.com/microsoft/vscode/blob/9bd54c15ae0c2017f4ea251e9eb9a88fb38d62c9/src/vs/workbench/contrib/notebook/electron-browser/notebook.contribution.ts#L40) higher than the webview's priority (100)

Simply changing the priority seems to work, although I am assigning this back to you @rebornix since I am not sure if there are cases where the backing webview itself needs to get the undo/redo events (such as when focused on a text input inside the webview)
