### ISSUE TITLE
UI state not preserved when reloading window after deleting folder

### ISSUE THREAD

**Issue by stevencl** [microsoft/vscode#115030]
Testing #114826

Started out with this state:

![image](https://user-images.githubusercontent.com/1704059/105841557-b20b8a80-5fcc-11eb-859e-ea90b0ace332.png)

Deleted folder on disk while keeping VS Code Insiders open

Reloaded window:

![image](https://user-images.githubusercontent.com/1704059/105841679-e8e1a080-5fcc-11eb-8e29-d37725e06e9f.png)

**Comment by stevencl** [comment]
State also isn't preserved when closing and restarting insiders after deleting folder on disk (rather than just doing reload window)

**Comment by bpasero** [comment]
Sorry I was not putting the correct steps into that part of the test item. In fact, when the folder is deleted or the workspace, we do not restore the UI state. The reason is that the UI state is still associated with the identifier of the workspace before it was deleted. However, dirty files should appear.

I have updated the test plan item, let me know how it goes.
