### ISSUE TITLE
Extensions viewlet: 'Check for Extension Updates' should us a modal dialog to confirm

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#115039]
Testing #114922

Since the user initiated the action to check for extension update, the confirmation that no extension needs to be updated should be shown in a modal dialog (same as when you check for an update of VS Code).
 
<img width="471" alt="image" src="https://user-images.githubusercontent.com/172399/105850830-8bf0e500-5fe2-11eb-9e6a-31a430f19d7b.png">

**Comment by sandy081** [comment]
@egamma It used to be dialog before and changed to notification because to be consistent with all other extensions update information messages which are shown as notifications - https://github.com/microsoft/vscode/issues/98761

**Comment by sandy081** [comment]
I heard that this brought up in our stand up and want to revisit.

As said, this was made a notification because to be consistent with this action's behavior - to always show a notification to inform about updates.

I would like to change this behaviour as follows:

- If there are updates, show the outdated extensions in the extensions view otherwise show a dialog that there are no updates
