### ISSUE TITLE
Allow tests to be loaded asynchronously

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#115089]
- @OmarTawfik in https://github.com/microsoft/vscode/issues/107467#issuecomment-763938766
- @matepek in https://github.com/microsoft/vscode/issues/107467#issuecomment-765946025
- @jdneo in https://github.com/microsoft/vscode/issues/107467#issuecomment-757693222

Going this route I would most likely want to copy the existing TreeDataProvider interface (or even use it directly). It serves the same purpose and can be reused.

https://github.com/microsoft/vscode/blob/b7e87c1bf2780f6b9338721369e422dcb398224d/src/vs/vscode.d.ts#L8899

**Comment by hbenl** [comment]
Actually since a TestProvider can add Tests at any time, the existing API seems already well suited for asynchronous loading. All that seems missing is a way for the TestProvider to signal that a test's children haven't been loaded yet (maybe a flag on the TestItem interface or a special value for its `children` property) and a way for VS Code (or a TestObserver) to tell the TestProvider that it should start loading the children (perhaps a new method `loadChildren(parent: TestItem)` on the TestHierarchy interface).

> Going this route I would most likely want to copy the existing TreeDataProvider interface

I have very mixed feelings about the TreeDataProvider interface: to update an item you need to tell VS Code that it has changed and then wait for it to pick up the changes. That can lead to subtle timing issues and an implementation of this interface that's guaranteed not to have timing issues and is performant is not straightforward. I like how simple it is to implement the current TestHierarchy interface and that is very important: TestProvider extension authors often have little or no experience with Typescript projects and should be able to focus on interfacing with their test framework as much as possible.

**Comment by OmarTawfik** [comment]
A tree provider API would work for use cases I've seen so far, since changes can be signaled on both the root and the children (thus updating only parts of the tree). For large codebases, it is impossible to calculate all contents of a tree in one time, and it is impossible to know beforehand what tests exist in a large repository. So we need a way to only calculate children of a node when the user specifically asks.

Also, the tree provider API is an established pattern that all extension developers know and are familiar with. There is a ton of documentation/questions around it, and people can create more advanced observers on top of it. So if someone has a simpler test runner, a simple wrapper around it will suffice (there are already many examples online).

**Comment by matepek** [comment]
Simplicity is preferred, if we have to implement the TreeDataProvider we are almost there to write our whole UI.

I said: 
> Okay this is not good enough, if it's a leaf we wanna know without triggering the init. :S
hasChildren?:boolean.?

But I've realized that `hasChildren` is not necessary.

Only 
```
children?: TestItem[] | Thenable<TestItem[]>
```
seem sufficient to me  since `x.children?.then !== undefined` can be checked. F
rom vscode side it's pretty easy (ex.):
- if `children === undefined` -> its a leaf
- else if `children.length > 0` -> has loaded children
- else if `children.then` -> assuming there are unloaded children which should be lazy loaded. (vscode should not trigger `then` until the user click on the expand.)

And here is an extreme example how I could use to prioritize lazy loads (Because even the user does not trigger with expand I still want to load it slowly):
```ts
class TestItem /*implements vscode.TestItem*/ {
  private _hasLoaded = false;
  private _hasLoadStarted = false;
  private _children: TestItem[] = [];
  private _childrenPResolver?: (ts: TestItem[]) => void;
  private _childrenP: Promise<TestItem[]> = new Promise(r => (this._childrenPResolver = r));

  public get children(): TestItem[] | Thenable<TestItem[]> {
    if (this._hasLoaded) {
      return this._children;
    } else if (this._hasLoaded) {
      return this._childrenP;
    } else {
      const item = this;
      return {
        then: function (...args: any[]): Thenable<TestItem[]> {
          item.triggerLoadChildren();
          return item._childrenP.then(...args);
        },
      };
    }
  }

  private triggerLoadChildren(): void {
    // prioritizing the load
  }
}
```

It's an incomplete, buggy example just for the sake of the argument.

**Comment by matepek** [comment]
Another example if you want to provide a way to us to write a nicer code:

```ts
interface TestItem {
  children?: TestItem[];
  loadChildrenAsync?(): Thenable<void>;
}
```

Yeah, this is much more intuitive and results cleaner logic on both sides. Forget my previous hack :)

It's seems quite straight forward how would it work but for sure I write a short summary:

### If `TestItem` has no `loadChildrenAsync`:

The current logic is perfect.

### If `children` is undefined or empty but has `loadChildrenAsync`:

There are unloaded children. UI (icon) should indicate that there are unloaded children.
If user clicks on expand then `loadChildrenAsync` should be called. The Promise should be resolved (by the adapter) when the enumeration has finished. UI can indicate the loading and the loaded state also.

### If `children.length > 0` and has `loadChildrenAsync`:

There are loaded and unloaded children. UI (icon) should indicate that there are unloaded children but also it should be expandable meanwhile the UI can show the current children.

### Notes

It might seems at first that `loadChildrenAsync` is present only at the beginning of lifetime of the object but it's not necessarily true and I don't see any reason why after an `onDidChangeTest` the wouldn't have `loadChildrenAsync` again.

**Comment by OmarTawfik** [comment]
@matepek thanks for the examples. Reading through them, I think your first suggestion would work better on both ends:

* On the platform side: `.children()` can be used for both purposes, async and sync loading. Using `Thennable` also makes it consistent with other parts of the API.
* On the extension side: this means a more consistent API, and no need for an explicit implementation of `loadChildrenAsync`, since this makes the code less readable, and makes noth modeling the state and testing it harder.

This is of course assuming that any `TestItem` can raise an event to let the platform know that its children have changed, and the UI needs to be updated. IMO, this is the most useful feature of the `TreeDataProvider` API, that we can update smaller parts of the tree when needed, without needing to fetch entire tree.

@connor4312 can you please tell me if this feature would make it for the spring timeline? or is it unplanned yet?

**Comment by matepek** [comment]
> "Run all" requires a full enumeration

I'm not sure that this is a good approach. For example GoogleTest C++ (again): If I run the executable without specifying the test it will run all the tests (except the skipped ones). Enumeration and run happens at the same time.

This is also true for running a child which is not expanded.

**Comment by connor4312** [comment]
I should have said, it requires discovering a test before a result is set. That's not the same as the other cases I mentioned.

The challenge with the drated is that, if getChildren is called lazily, there's no "push" of tests into vscode -- the extension can't signal that children _should_ be loaded at this instant. This is needed for us to be able to recognize them in the results.

There are a few ways around this:

- have some manual loadChildren event. I don't like this.
- require tests to reference their parent. This would let us automatically build the results even without enumeration. Being able to skip enumeration for test runs in general would be fantastic.
  - If we go this route, do we need children in the test item at all? We could have flat test items and new ones can come in on events. This would be closer to the TreeDataProvider, or we could literally use a TreeDataProvider in this case.
- Go with something like your second proposal where there's both an array and a load method. I don't like splitting the state like this.

**Comment by connor4312** [comment]
The approach I'm working with now is having the getChildren _and_ a getParent method on the test hierarchy. This means tests themselves are simple, flat objects. The presence of getParent means that we can use this in results without enumerating everything ahead of time.

https://github.com/microsoft/vscode/blob/52cb0a5564e3fc41b0430ebd92acdc8dbd9d70c4/src/vs/vscode.proposed.d.ts#L2273-L2294

This branch is kind of working but still needs quite a bit of polish and updates (tomorrow)

**Comment by jrieken** [comment]
(without knowing too much detail and without the intention to randomly throw everything over)

From the perspective of the API guardian, a birds eye view and some general brain dump. In the API we have two main concepts for how extensions get data into the renderer: 

1. The "pull model" - the renderer asks extensions for data. This is implemented with providers, like the `CompletionItemProvider`. An important characteristic of the pull model is that we consider the data to be "dead". Similar to a XHR request we read the data once and send if off to the renderer. We do not observe state changes or anything like that. The pull-model works really well whenever we know when to ask for data, like "User presses Ctrl+Space, we _pull_ completions into the renderer". Sometimes it isn't so clear. For instance, for code lenses we know to ask for data when a file opens or when it is being changed but there might be external triggers, like a configuration change. For that we allow providers to implement an `onDidChangeXYZ`-event. This signals to us that we should, again, ask for data. Sometimes we know little to nothing about when to ask for data and that motivated the next concept.
2. The "push model" - the extension sends unsolicited data to the renderer. This is implemented with interfaces and factory-functions, like `DiagnosticCollection` and `createDiagnosticCollection`. This defines a contract and allows us to "spy" on these objects, e.g we know when a diagnostics collection is modified and can update the renderer accordingly. We generally prefer the pull model model because it gives more control but when it's unknown when to pull we use push. Samples are diagnostics that have various triggers (e.g. changes in file A cause errors in file B), the source control API, or the comments API etc.  One characteristic of the push model is that the renderer never knows when things are done (it lacks the "transaction" of calling a provide-function), e.g we don't know when the "last" diagnostic was computed. This makes it hard to offer "apply to all XYZ" features, because you always operate on a snapshot. 


Now, the question is what concept fits best for testing? We want features like "Run All Test" or "Run Tests for File" which hints towards the pull model. On the other hand test discovery and management is really "hard" - it is different per language and framework. Is it worth to model all those different worlds into a pull model or should tests just appear and be updated on extensions own schedule?

It seems that the current proposal implements a "push model" but uses "pull language". For instance there is the TestProvider but it returns alive objects that send events (which is in conflict with the provider rules). Using "push language" it could become `createTestHierarchy(): TestHierarchy`. This type would have functions to add and relate test items, like `addTestItem(item, parent?)`. This would be similar to diagnostics or the `createSourceControl`-function. The UI would still need some signal to know whether test discovery is done or (re)running. That could be achieved with some mutable property of the test hierarchy. 

Assuming test discovery and result reporting is decoupled, the same can be done for results. An extension can create some kind of result collections which it manages so that the UI updates. 

Excuses for being late to the party and likely missing out on some things but I hope I could position this in the (current) API universe. I try hard to use little concept as possible so that each API feels similar, fighting to [Conway's Law](https://en.wikipedia.org/wiki/Conway%27s_law)

**Comment by connor4312** [comment]
Thanks for the insight! As we touched on in our discussion Tuesday, there's difficulty here in that testing--with this async loading ask--is kind of a hybrid model. We don't want the test extension to push _everything_ to us, in a "push" model, but we also want to observe live data. If files change, inside or outside of VS Code, that can result in the test tree changing. I don't like to be the person who comes in and immediately assumes their thing is an exceptional special snowflake, but I don't think there's really anything like this in the current VS Code APIs. The closest is the TreeDataProvider, which is what I've modeled the latest API proposal after, with the changes that:

1. `getParent` is required for reasons stated earlier
2. There's no need for `getTreeItem` or `resolveTreeItem`

I think test running can definitely be push model.

---

However, after just saying that tests are like the TreeDataProvider, I find a point of divergence. In the current proposal tests are returned as an array, or in a promise containing an array. This is okay but doesn't work so well for discovery that can take several seconds, because you don't see anything at all until all children are discovered.

The obvious approach is to allow returning a `Iterable<TestItem> | AsyncIterable<TestItem>`. This is very nice and idiomatic, at least as far as JS goes. However, there arises an awkward case where a change event is fired while we're still discovering children. In the current implementation we would request cancellation and then call getChildren again. However, this then requires the test extension to be smart about caching their previous items and "progress", and is pretty challenging to implement correctly.

One alternative is to change it to a `loadChildren(): ProviderResult<void>` method, and then add an `onDidRemoveTest` method. This is like @matepek's second proposal. When call this method, we would expect the extension to fire `onDidChangeTest` for each child, which would cause us to upsert (rather than today only update) the elements. The promise should resolve when events have been fired for all the current children. Because the hierarchy now has `getParent`, we can do this, and I think it streamlines implementations significantly and lets them be less stateful.

**Comment by connor4312** [comment]
My latest thinking is the "Hybrid Managed" proposal in https://gist.github.com/connor4312/73f1883d720654834b7fd40550d3b6e0#hybrid-managed

I've also updated our selfhost test provider with the proposed API change in https://github.com/microsoft/vscode-selfhost-test-provider/commit/672bc473536fa2110285bdcba1a9aeaae0eb4c1a (negative diff!)

**Comment by jdneo** [comment]
Hi @connor4312, I just tried the new async version API. So far so good.

While I just noticed in the new API, the `Location` is separated to `uri` and `range`. This is good since sometimes, the test item might be indicating a folder. But I got an error when I'm expanding a test item which only has the `uri`:

![test](https://user-images.githubusercontent.com/6193897/113093668-ed237780-9222-11eb-9736-2feab780580e.gif)

And I also found that **only** un-expandable item can be navigated to source by clicking it. Is it possible to do the navigate action for those items who have both `uri` and `range` set? Or like the custom tree API, user can bind a custom command to each node?

**Comment by connor4312** [comment]
> But I got an error when I'm expanding a test item which only has the uri

This is fixed in https://github.com/microsoft/vscode/issues/119649

> And I also found that only un-expandable item can be navigated to source by clicking it

That's also fixed in the same commit. Unexpandable items are only navigated to on click, but you can right click and "Go to Test". That'll take you to the file -- a specific range, if present -- or reveal the folder in the file explorer view if the `uri` points to a directory

**Comment by jdneo** [comment]
Thanks @connor4312. Looking forward to playing with it 😃
