### ISSUE TITLE
Watch: allow to set value of expressions

### ISSUE THREAD

**Issue by yannickowow** [microsoft/vscode#115063]
Related to : https://github.com/microsoft/vscode/issues/45621 ?

Hi, 
I create this request to implement setExpression in VS Code. Since it already supports well "evaluateName", it would be easy to support this in "Watch" view.
In my mind, if debuggee supports setExpression, you could set a value by double-clicking in current one, or by a "Set Expression..." action. 
Regards.

**Comment by isidorn** [comment]
If I understand this correctly: this is a feature request to add a "Set Value"  context menu action to the Watch view.
I do not really see a user scenario needd for this. Though I do not mind having this open so we gather more user feedback, thus assigning to backlog

**Comment by yannickowow** [comment]
Yes, it is correct.
For some debuggers, it can make sense if your expression is, for example, an address or a register which can't be shown in a Variables pane. 
GDB for example supports `set <variable> <expression>`, which <variable> can be:
- A register (example: $pc)
- An array (example: t)
- An address(example *0x400000)
(For reference: https://ftp.gnu.org/old-gnu/Manuals/gdb/html_node/gdb_111.html#SEC116)

**Comment by weinand** [comment]
I've quickly checked what VS is doing:

<img width="680" alt="2021-06-28_12-05-30" src="https://user-images.githubusercontent.com/1898161/123619387-696d2d00-d809-11eb-889c-0a5614bf7bc1.png">

more to come...

**Comment by isidorn** [comment]
I started investigating into this and created this PR which proves it is possible https://github.com/microsoft/vscode/pull/127162

Some open questions:
1. If the debugger does not support `setExpression` should we show the action as disabled or not in the menu
2. For variables that are children of watch expressions should we send the `setVariable` or `setExpression`

I am not aware of a debug adapter that supports the `setExpression` so I was not able to test this end to end right now. Also I am not super happy with the code thus I would prefer to not do this end of milestone. Thus moving to August since in July I am on vacation. If somebody is passionate about this feel free to continue the work on my PR.

Edit: C# supports setExpression

![Screenshot 2021-06-25 at 17 53 27](https://user-images.githubusercontent.com/1926584/123451971-427ee300-d5de-11eb-8796-708cc32dd996.png)

**Comment by weinand** [comment]
@isidorn thanks for prototyping this!

IMO we should not show the "Set Value" command if the DA does not implement it. It would be confusing for a user to understand why "Set Value" is disabled. When coming from VS that typically means that the expression is not assignable. But here it only means the DA does not yet support this.

**Comment by yannickowow** [comment]
As a reference, here is how Eclipse does to determine if an expression is editable (using GDB)

> 84-var-show-attributes var4
> 84^done,attr="editable"

If "attributes" contains `editable`, Eclipse GUI allows to set expression.

![image](https://user-images.githubusercontent.com/45362067/123625687-4abe6480-d810-11eb-9c8e-f6481b59ad79.png)

Here, for example, expressions 2, 3, and expression's child of `&i` is editable

Might we need to return a `isEditable` boolean in `evaluateRequest` response ?

**Comment by isidorn** [comment]
Great, thanks for feedback!
@weinand it would be cool if mock debug supported set expression, to make it easier to try this out end to end (without the need to install C#)

**Comment by weinand** [comment]
@isidorn sure, I will do this!

**Comment by gregg-miskelly** [comment]
@weinand In case it isn't obvious, VS knows if something is an l-value or not by looking at the [`readOnly` attribute in VariablePresentationHint](https://github.com/microsoft/debug-adapter-protocol/blob/e7c1c851cc423b33211e31bba48fecb582d3bfac/debugAdapterProtocol.json#L3422).

**Comment by weinand** [comment]
@isidorn I have reimplemented variables in Mock Debug. See https://github.com/microsoft/vscode-mock-debug/tree/main/sampleWorkspace#variables for details.
Both `setVariable` and `setExpression` are implemented but only `setVariable` is enabled through the capability. But I was not yet able to make VS Code call `setVariable`....

**Comment by isidorn** [comment]
Same as https://github.com/microsoft/vscode/issues/124679#issuecomment-893319402
Will be merged later today, thus closing this

**Comment by weinand** [comment]
@isidorn I've finished the implementation of `setExpression` for Mock Debug and published a new version 0.46.2 to the Marketplace. In addition I've set the `supportsSetVariable`capability to false, so that only `setExpression` is used in all cases.

Here is a demo:

![2021-08-05_17-49-52 (1)](https://user-images.githubusercontent.com/1898161/128382301-dd415efa-a373-4f8e-b51c-04e9d457093c.gif)

I 'm seeing one issue: when setting a new value for a watch, the watch isn't updated in the WATCHES view.

**Comment by isidorn** [comment]
@weinand good catches. Thanks!

The watches `setExpression` issue I have handled via 19eb720cf07 however it seems like `mockDebug` is not returning `body` for the `setExpression response`. And that seems to be the reason why this is now not working. Can you double check if the `body` object is properly returned?

`Set Value` is now disabled for `readOnly` variables via ba5054e5247

**Comment by weinand** [comment]
@isidorn I've verified that I'm returning a correct body from `setExpression`:

<img width="919" alt="2021-08-09_12-22-43" src="https://user-images.githubusercontent.com/1898161/128694162-75b2cc4c-ede4-4ab0-8d53-463241815b4b.png">

And this body is correctly received in VS Code:

<img width="904" alt="2021-08-09_12-45-41" src="https://user-images.githubusercontent.com/1898161/128695172-ef1db449-047e-4ec0-a1ad-7e5556976ae3.png">

**Comment by isidorn** [comment]
@weinand thanks, I have tackled this via c00e89d9aee
So I think we are now good.

**Comment by weinand** [comment]
BTW, error handling works nicely:

![2021-08-09_15-27-43 (1)](https://user-images.githubusercontent.com/1898161/128713981-a4a470f1-87a8-44d0-b5b5-1d64c5e11429.gif)
