### ISSUE TITLE
Tab wrap - removing right border when tab takes full width

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#115046]
Testing #114827

When a tab is taking up the full row the right hand border seems to have one extra pixel. Unless this is intended, I think that it would be great to remove it so that all four borders of the tab have a consistent size. 

![image](https://user-images.githubusercontent.com/3372902/105855004-de80d000-5fe7-11eb-9217-cde1a706037a.png)

**Comment by bpasero** [comment]
Good catch, I was waiting for this issue. Unfortunately I was not able to figure out a way to do so because there is no CSS rule that I can use to figure out if a tab is the last one in a row or not. I would probably have to inspect each tab during a layout call and dynamically update the border based on the position of the tab which I found a bit overkill. 

//cc @SneakyFish5 @DynDux

**Comment by DynDux** [comment]
@bpasero I don't know of any CSS rule to identify the last tab in a row, but if it can get a little dirty, you can apply the border not to the right side of a tab, but to the left side. Then - for the "dirty" part - move the tabs 1px to the left to move the border out of the way on the left side.

So, instead of: `border-right: 1px solid yellow;`

use: `border-left: 1px solid yellow; margin-left: -1px;`

Maybe there are some side effects I didn't think of (scrollbar? icons?), but it's worth a try.

**Comment by bpasero** [comment]
@DynDux thanks for that suggestion, can we not simply keep the current `border-right` and have a `margin-right: -1px` to fix it the same way?

**Comment by DynDux** [comment]
@bpasero Unfortunately not because the border would be overlaid by the following tab and would therefore not be visible.
You would then have to inverse the z-index for each tab which is way more complicated than changing the border position. :-(

**Comment by bpasero** [comment]
I ended up adding code into the layout to actually know when a tab is the last in a row or not. This means I have to access the `tab.offsetTop` property but in my profiling I did not notice a slowdown because a layout is likely already triggered from asking for `offsetHeight` of the tabs container. 

There is now a new CSS rule to disable the right border for any tab that is last in row.

https://github.com/microsoft/vscode/blob/3c62a8f898b79dfe2ce384d3c333fb06486119db/src/vs/workbench/browser/parts/editor/tabsTitleControl.ts#L1491-L1524
