### ISSUE TITLE
`menuBarVisibility` `toggle` and `default` behave like `hidden`

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#115055]
Testing #114949

* on macOS
* open https://vscode-web-test-playground.azurewebsites.net/?enter=true
* set the configuration option to `toggle` 
* press `alt`
* the menu does not show

Similarly, set the configuration option to `default`. The menu is not visible.

**Comment by sbatten** [comment]
linking to https://github.com/microsoft/vscode/issues/114200

**Comment by yume-chan** [comment]
I think this is a separate issue.

Setting `window.menuBarVisibility` directly to `toggle` does nothing, but setting it to `visible` (now the "window" has a title bar), then `toggle`, now it correctly toggles when pressing <kbd>Alt</kbd>

So the problem here is setting it to `toggle` directly in web doesn't bring up the title bar. Or maybe the title bar should appear only when <kbd>Alt</kbd> was pressed.

**Comment by sbatten** [comment]
`toggle` is working when the app is in pwa or fullscreen mode, otherwise alt-mnemonics and such are intercepted by the browser menu. the linked issue intends to review the behavior of each and both update the names/descriptions, but also behavior if necessary

**Comment by yume-chan** [comment]
@sbatten Looks like my browser is super kind that it allows a normal tab to intercept <kbd>Alt</kbd> keys. It's Code's fault to not toggle its menu when <kbd>Alt</kbd> was pressed

![GIF](https://user-images.githubusercontent.com/1330321/105921305-a626d380-6073-11eb-98c5-ee8e3bb1ccbc.gif)

**Comment by sbatten** [comment]
yes it seems alt itself no longer goes directly to the browser menu, but alt+<letter> does. will investigate this as well across browsers/platforms
