### ISSUE TITLE
debug toolbar not reflecting running state

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#115069]
Testing #110226

Have a node program:
```
setInterval(() => {
    console.log('x');
} , 1000);
```
- set breakpoint on console
- launch the propgram 2 times (see #110226)
- the call stack shows both launched programs and shows that the programs are sitting on breakpoint
- use the process switcher in the debug toolbar
 -> from the toolbar it appears the programs are running, but in fact they are paused and the 'continue' button should show

![debug-toolbar](https://user-images.githubusercontent.com/6461412/105871965-2577c100-5ffa-11eb-9d78-9f6559a5ccb0.gif)

**Comment by isidorn** [comment]
@aeschli good catch, this is due to the fact that js-debug encapsuletes a child session with a parent session, and from that dropdown we are not smart enough so we focus the session wrapper
There was already an issue for this, but I can not find it.
Assigning to february to investigate then into fixing it.

fyi @connor4312
