### ISSUE TITLE
It's not possible to use `(` for accepting completion suggestions

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#11516]
This is really a dupe of #11016 but that's been closed but the provided solution doesn't work.

If you do this (as provided as an example):

``` text
"key": ".",
"command": "^acceptSelectedSuggestion",
"when": "editorTextFocus && suggestWidgetVisible && editorLangId == 'typescript' && suggestionSupportsAcceptOnKey"
```

then pressing `.` will automatically commit the selected item in the completion. However, if you try to use `(` instead of `.` then it doesn't work.

Probably related, the [Accepted Keys](https://code.visualstudio.com/docs/customization/keybindings#_accepted-keys) section of the docs don't list `(` and `)` as valid keys.

I'm not sure whether there's a deliberate reason for this but it seems strange; Visual Studio commits on `(` so it's something that many developers are used to; it would be good to support here.

(Apologies if I shouldn't have created a new case, but I was told not to comment on closed cases, so I'm a little unsure of what to do in a case like this - if someone can clarify I can make sure to do the preferred thing in future!).

**Comment by jrieken** [comment]
> Probably related, the Accepted Keys section of the docs don't list ( and ) as valid keys.

Yes, that's because each keyboard puts `(` and `)` somewhere else (compare german, english, swiss, french etc keyboard). On my keyboard `(` happens when I press `shift+9`, on yours it might different.

You can use the help widget in the `define keybindings command` to figure out what key sequence produces what character for your keyboard layout


 
![screen shot 2016-09-05 at 11 16 51](https://cloud.githubusercontent.com/assets/1794099/18243206/5d61fc5c-735a-11e6-8ed8-894b6de33bb7.png)

**Comment by DanTup** [comment]
@jrieken Apologies, I think this case is a bit confused. I think this is a really valid feature request despite the technical complications with how it would currently need ot be done.

I would like (as an extension author) for `(` to complete - in the same way that in TypeScript you decided to make `.` complete. Currently the only way to do that is via keybindings, and it turns out we can't use `(` in keybindings.

So, is it not valid to have another mechanism for this? It seems strange that we can have a language allow `.` to complete but not `(` just because of keyboard layouts - when thinking about the character being typed into the editor rather than the keybinding, then these seems a rather strange decision/limitation.

**Comment by jrieken** [comment]
That's how it is. @alexandrudima can fill in the details

**Comment by alexandrudima** [comment]
@jrieken's description of how it works today is correct.

@DanTup what you want can be achieved only through a different implementation, one where [`ISuggestSupport`](https://github.com/Microsoft/vscode/blob/25805c14a5252e595307db9da365756dfc0de245/src/vs/editor/common/modes.ts#L369) would also contain a list of `acceptCharacters`, besides the current list of `triggerCharacters`.

This would need to be wired up correctly to the vscode API and then it could be used in the suggest contribution similar to how [`triggerCharacters` are used](https://github.com/Microsoft/vscode/blob/7a517bbd7354a6d633954806b8df010fafaa7e56/src/vs/editor/contrib/suggest/common/suggestModel.ts#L242), but instead of triggering it would accept the focused suggestion.

**Comment by DanTup** [comment]
@alexandrudima Is that something we can do today, or do you mean it'd need work in Code? Is this not a reasonable feature request, or would you not wish to do it? (If you don't want to do it, I'll close https://github.com/Dart-Code/Dart-Code/issues/131 off; but it's a little unclear)

**Comment by alexandrudima** [comment]
I think it is a reasonable feature request.

**Comment by mjbvz** [comment]
We now treat `(` as a commit character for JS and TS functions/methods. There should be no need to setup a keybinding for this any more
