### ISSUE TITLE
Line breakpoints don't show same info as Function breakpoints

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#115109]
Testing #114345

If I add an expression and hit count to a line breakpoint, shouldn't that also show here?

![image](https://user-images.githubusercontent.com/2644648/105884439-d495a780-5fbc-11eb-8231-232950b2a5e3.png)

**Comment by isidorn** [comment]
For line brekapoints we use that space to show its relative workspace path. In this particualar case you have a file which is in the root so the path is empty.

In theory we coudl show the condition if the path is empty - which I find bad and inconsistent.
A better alternative is to show a path only if the breakpoint has no condition. Otherwise show the conditions since it is more important. And show path on hover.
Currently we do it the other way around - path inline and condition on hover.

For now I would not change anything here, but I am open for ideas..

**Comment by TylerLeonhardt** [comment]
I think that makes sense. I'm fine with that answer. Feel free to close.

**Comment by isidorn** [comment]
Okey. Let's close as designed
