### ISSUE TITLE
Have automatic overflow behaviour of tool bars

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#115198]
* install latest jupyter extensions
* use tabs
* look at the editor title and see that most space is consumed by commands
* we should automatically move some commands into the `...` menu

<img width="827" alt="image" src="https://user-images.githubusercontent.com/1794099/105963633-84cce400-6081-11eb-8c11-6a5671537c2e.png">

**Comment by jrieken** [comment]
fyi - for https://github.com/microsoft/vscode/issues/114123 we are planning to add a "run" sub menu to editor titles, that would be a good place for all run related things.

**Comment by bpasero** [comment]
Originally we had somewhat of a rule that there should only be up to 3 primary actions and the rest moves into the "...". But we never enforced it and probably even in our core have some offenders.

I wonder if we could have a design for toolbars that primary actions automatically move into the "..." based on a fixed maximum width we give it.

**Comment by Tyriar** [comment]
Note that adding enforcement here will cause problems for extensions like https://marketplace.visualstudio.com/items?itemName=jerrygoyal.shortcut-menu-bar

An alternative proposal: Can we bring the right click toggle behavior here which would move them to the overflow?

**Comment by jrieken** [comment]
>  Can we bring the right click toggle behavior here which would move them to the overflow?

Sorry, what is "right click toggle"?

**Comment by Tyriar** [comment]
@jrieken 

![image](https://user-images.githubusercontent.com/2193314/106152328-2b70bd80-6132-11eb-96ae-83b62afcc63b.png)
![image](https://user-images.githubusercontent.com/2193314/106152350-3297cb80-6132-11eb-8e97-c95a2a459a70.png)

**Comment by jrieken** [comment]
Ah, thanks for clarifying. Yeah, that's like user configurable menus: https://github.com/microsoft/vscode/issues/9285. That's something we should invest in but the challenge of editor title command competing with tabs will remain

**Comment by Tyriar** [comment]
I'm kind of in favor of enforcement here, but I'm not sure doing it now is a good idea because of breakages it would cause. For Jupyter specifically, I'm assuming the API allows putting actions into the overflow. We could work with them to make sure the extension fits the guidelines. The current recommendation in the [ext guidelines for editor actions](https://code.visualstudio.com/api/references/extension-guidelines#editor-actions) is:

> Don't Add more than one icon

**Comment by stevencl** [comment]
@bpasero is right - our original thinking was that the ellipsis would be used for overflow actions whenever there were more than three. Our intent was to prevent the UI from having icons and actions littered all over the place.

I really think we should stick with the idea that this is an overflow and not a place where the user can go to configure what they see. In most other places we allow the user to right click blank space (in the activity bar or viewlet title bar for example) to configure additional views (the explorer viewlet uses an ellipsis to do the same but this is inconsistent with how we use ellipses elsewhere). I would suggest we do that for the editor actions instead of combining it with the overflow.

**Comment by misolori** [comment]
Overflowing actions into the ellipsis is also a common behavior in Browsers and in other web apps like Outlook. I also think a user can decide when to show/hide each action as they may not want certain actions visible or prioritize others.

![Kapture 2021-01-28 at 07 39 08](https://user-images.githubusercontent.com/35271042/106161701-2a448e00-613c-11eb-82a4-a98efdbbff38.gif)

**Comment by isidorn** [comment]
We already do something like this in the Panel title area

![recording](https://user-images.githubusercontent.com/1926584/106737989-ab59c480-6617-11eb-9996-98b98e090b88.gif)

**Comment by stevencl** [comment]
That's right. We also use the ellipsis for overflow in the activity bar.  It's used inconsistently in the viewlet title bar though. There the ellipses are used for selecting the visible views inside the viewlet and actions don't overflow.

**Comment by misolori** [comment]
This is what I would expect, as you resize the actions hide from left to right and get added to the ellipsis menu near the bottom (in order to keep the menu order consistent)

https://user-images.githubusercontent.com/35271042/106772040-75efaf80-65f4-11eb-96b3-507200572ee3.mov

**Comment by rchiodo** [comment]
For our users I'd be worried about what gets put in the overlow menu. How does VS code decide which it shows? Last used? Order in the full toolbar?

**Comment by jrieken** [comment]
> Order in the full toolbar?

Yes. The more to right an action is more likely it will "flow" into the menu

**Comment by jrieken** [comment]
I have pushed a commit to limit the number of primary actions to seven. Starting with a fixed number so that the UI is also more static and not moving/hiding-showing actions as sizes change

**Comment by claudiaregio** [comment]
What happens if an extension adds a feature/icon using the notebook toolbar as an entry point and there are already items in the overflow menu? Does it get propped up the front? Automatically placed in overflow menu?

**Comment by greazer** [comment]
Right, as a followup to Claudia's and Rich's question, what we will need is an ability to ensure that some toolbar actions aren't ever hidden or are much less likely to be hidden. For example, many Jupyter users rely on the play button in the toolbar to run a single cell. Note: The run cell button on the cell itself is problematic for many because the user has to click play, then move the mouse to the next cell at minimum. Of course for longer notebooks, scrolling would often be involved too.

So, I would think some kind of notion to allow extensions to "prioritize" some buttons from being hidden could solve this. Or, we could let the users decide what buttons should not be hidden (ala Tyriar's suggestion above). 

Additionally, perhaps there could be a notion of allowing extensions to define collapsible groups of buttons such that when space is limited the extension has control over what button remains, and the remaining in the group appear as a dropdown underneath.

For example, if the run cell, run above, run below buttons belonged in such a group, then if the user has enough space to show all buttons, then they all appear. But if the window is sized smaller, those run buttons get grouped into one run cell button. The run above and run below would be selectable under that button.

This wouldn't completely eliminate the need for having some hardcoded overflow algorithm as extensions may play poorly. But it would help ensure that buttons that extensions feel are most critical for their users' workflow are mostly always available.

**Comment by claudiaregio** [comment]
Would it be possible to get a summary or some documentation on what the overflow pattern looks like for a multi-extension experience? What happens when a user has multiple extensions that are contributing to the toolbar and they're all "visible"

**Comment by jrieken** [comment]
> What happens when a user has multiple extensions that are contributing to the toolbar and they're all "visible"

All extensions are equal and no extension can make its contributions to VS Code more important than those of other extensions. 

> Would it be possible to get a summary or some documentation on what the overflow pattern looks like for a multi-extension experience?

The overflow logic is quite simple as the first 7 items are shown prominently and all others overflow into the `...` menu. The ordering works exactly how it already works today. Extensions contribute commands to groups of menus, e.g the `navigation`-group of the `editor/title`-menu, see https://code.visualstudio.com/api/references/contribution-points#contributes.menus) and from that information the order is derived. 

> So, I would think some kind of notion to allow extensions to "prioritize" some buttons from being hidden could solve this. Or, we could let the users decide what buttons should not be hidden (ala Tyriar's suggestion above).

We want to  keep user configurable menus out of this issue but it is on our plan. I assume that will address many pain points. I am not a fan of allowing extensions to "prioritize" command because extensions authors are naturally inclined to prioritize their commands and that would leave us at same spot at which we are today. 

> Additionally, perhaps there could be a notion of allowing extensions to define collapsible groups of buttons such that when space is limited the extension has control over what button remains, and the remaining in the group appear as a dropdown underneath.

I like that! In February, I will work on dynamic submenus but with a focus of turning them into a simple actions when having only one entry. Tho, I can image that being extended into "spreading" larger submenus too (given all items fit). Btw - already today you can contribute normal submenus into the editor title if you like. 

Last but not least this is also a call for action. Space in the editor title is naturally limited and extensions should be very considerate about what commands they place there. Our [guidelines](https://code.visualstudio.com/api/references/extension-guidelines#editor-actions) recommend no more than 1 item per extension and while that sounds extreme in some ears it should be taken as a reminder that this is a shared space.

**Comment by heartacker** [comment]
Frankly I don't think the action bar icon should be on the tabs-line at all
:smile:
