### ISSUE TITLE
Editing logpoint condition results in editing logpoint message

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#115114]
Testing #114345

1. Create logpoint
2. In breakpoints viewlet, Right click > Edit condition...
3. The logpoint message editor comes up.

**Comment by isidorn** [comment]
Yeah that is expected behavior.
For breakpoints that are tied to a source location clicking on Edit Condition -> we open the breakpoint widget in the source location.

I guess you would expect that the Edit Condition would automatically set the dropdown to condition for logpoints which I think makes sense. I can leave this open for now to get more user feedback.

**Comment by rzhao271** [comment]
Well, when I right-click the logpoint in the editor itself it says 'Edit Logpoint...', and then to me it makes sense that the message editor shows up.
I'm wondering if for the breakpoint viewlet, right-clicking logpoints should also bring up 'Edit Logpoint...' or something along the lines of 'Edit message...' instead of 'Edit Condition...'

**Comment by isidorn** [comment]
Yes, I like that idea! Let me assign to this week to look into fixing that
Thanks for feedback

**Comment by isidorn** [comment]
We currently do not allow commands with generic titles, so I would have to introduce a new command just for a different title "Edit Logpoint". It makes sense but is a bit clunky. Thus pushing out of this milestone for now.
