### ISSUE TITLE
"Default external uri opener" no-ops

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#115141]
Testing #114962

1. Contribute a link opener with a Default priority
2. Click on a link
3. Select the `Default external uri opener`
4. Nothing happens 🐛

**Comment by rebornix** [comment]
Followed the same steps and now the url is opened directly in browsers, even though my default url opener only does `console.log`.

**Comment by mjbvz** [comment]
@rebornix The bug was that the default VS Code url opener was no opening links in the browser. Instead selecting it did nothing.

I just tested this in the latest insiders and it seems to work now. @connor4312 Could you confirm?

PS: I also renamed the default opener. It is now labeled as: `Open in default browser`:

<img width="942" alt="Screen Shot 2021-01-28 at 7 25 59 PM" src="https://user-images.githubusercontent.com/12821956/106227800-c69f7c80-619e-11eb-8608-194464786802.png">

**Comment by mjbvz** [comment]
Closing for verification
