### ISSUE TITLE
Hex Editor command name suggestions

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#115178]
Testing #114952

I was initially confused by the two Hex Editor commands: Hex Editor: Open File and View: Show Hex Editor. I thought Hex Editor: Open File would bring up a file picker of some sort and I thought Show Hex Editor would show the Hex Editor (just brings up the File Explorer if no file open in the Hex Editor)

Suggestions:
Hex Editor: Open File -> Hex Editor: Open Active File in Hex Editor
View: Show Hex Editor -> View: Show Hex Editor Data Inspector

**Comment by lramos15** [comment]
I think part of the confusion come from VS Code itself because I only contribute that hex panel when the hex editor is open. The view command should not show if the hex editor isn't open. I'm a little hesitant to rename the show hex editor to include the word data inspector as in the future there might be more than just the data inspector there. How does `View: Show Hex Panel` sound?

@mjbvz Would you consider it a bug that the view command is contributed when the view container isn't contributed yet due to the context key?
```
			"activitybar": [
				{
					"id": "hexExplorer",
					"title": "Hex Editor Data Inspector",
					"icon": "icon.png",
					"when": "hexEditor:openEditor"
				}
			]
```

**Comment by lramos15** [comment]
I have updated the names https://github.com/microsoft/vscode-hexeditor/commit/f8e4c8aca6864e9252c2cb36cf4df73d688f4b8b
I will wait for feedback from Matt about my comment above.

**Comment by mjbvz** [comment]
@lramos15  For the command, do you have a `commandPalette` contribution point that limits when the command shows. For example: https://github.com/microsoft/vscode/blob/b565c422aa3a9e789d4c6beeec61269350ab6231/extensions/typescript-language-features/package.json#L973

**Comment by lramos15** [comment]
> @lramos15 For the command, do you have a `commandPalette` contribution point that limits when the command shows. For example:
> 
> https://github.com/microsoft/vscode/blob/b565c422aa3a9e789d4c6beeec61269350ab6231/extensions/typescript-language-features/package.json#L973

This is the view command, I don't contribute this command. It comes straight from VS Code

**Comment by mjbvz** [comment]
Try following up with @sandy081 or @sbatten on that then

**Comment by sbatten** [comment]
@lramos15 I don't believe that when clause does anything for the view container. Looking at your extension repo, you have the "when clause" in both the container and the view. only the view one will be read. the command that is shown is for the view container, not the view. the reason it is not shown is because it is "hidden when empty" and your view has a "when clause" that we do honor. we should probably have some kind of "when clause" internally on those commands.

**Comment by lramos15** [comment]
@sbatten It might also be interesting to support a when clause on the container so that you don't need one on each individual view

**Comment by sbatten** [comment]
given that users can move other views into the containers, i don't they we would introduce that. the containers are just meant to be holders for views with icons

**Comment by lramos15** [comment]
Makes sense. I definitely agree that we shouldn't show the view command for empty views.

**Comment by sandy081** [comment]
One take away I would take from this discussion is that - We shall not show `View: Show ${View Container}` commands when those view containers are disabled (implies no views in that view container are enabled). Currently such commands open explorer view container - https://github.com/microsoft/vscode/issues/115289

**Comment by sandy081** [comment]
@lramos15 I already created separate issue for that #115289 and fixed that. Not sure if you meant something else.
