### ISSUE TITLE
Support for file links

### ISSUE THREAD

**Issue by pankleks** [Microsoft/vscode#11518]
- VSCode Version: 1.4
- OS Version: Windows 10

It would be nice addition to add files as links from outside workspace (I think it's possible in standard VS).

I wish to reuse some files between two workspaces in following dir sturcture:
- workspace 1
  - files
  - links to files from ../shared
- workspace 2
 - files
 - links to files from ../shared
- shared
  - files

**Comment by dbaeumer** [comment]
@pankleks since VS Code is file system based normal file system links should do the trick. Is there something you are missing?

**Comment by bpasero** [comment]
A number of days has past without answer on the questions asked. I am thereby going to close this issue to clean up our backlog of issues. Once you can answer on the questions, the issue can be reopened again. Thanks for understanding this process!

**Comment by pankleks** [comment]
File links at system level works fine for me.
Thanks for the idea.

**Comment by fbehrens** [comment]
Yes, file system level files works  fine. 

When I write documentation in markdown, I can link between documents in the following way 
```
from /doc/documentation.md
* [back](../README.md)
* [back absolute](/README.md)
```

here are working examples on [github](https://github.com/fbehrens/doc-example/blob/master/doc/documentation.md) and [gitlab](https://gitlab.com/fbehrens/doc-example/blob/master/doc/documentation.md)

It would be very useful, if those links would also work in VSCODE, because this would make it possible to set and follow the links while writing the documentation in the editor.
