### ISSUE TITLE
An api to open non integrated terminal

### ISSUE THREAD

**Issue by alor-pretatma** [microsoft/vscode#115162]
I would like to have a way to open non integrated terminal from vscode extension and run commands on that just as integrated terminal.
Actually i need this. Its like you have an api `Terminal.sendText()` for running commands in the integrated terminal. 
It's same but in non integrated..
Might be an option in `vscode.window.createTerminal` to specify whether or not to open integrated...
It doesn't matter how, but a way..

And a callback on current `Terminal.sendText` method to know if the command execution has ended..

**Comment by Tyriar** [comment]
@alor-pretatma you can do this using node.js in the extension yourself. We're not planning on adding an API to control the external terminal, one of the benefits of the integrated terminal is that it's easier to control. If we expanded this to external terminals we would need to support all terminals, some support would be patchy because of different feature sets, etc.

> And a callback on current Terminal.sendText method to know if the command execution has ended

We do not know this unfortunately. Some extensions poll the child processes of `Terminal.processId` to do this but that may not work depending on what you're trying to accomplish (eg. running a shell script). I don't see a robust, reliable and generalized way forward for that idea.
