### ISSUE TITLE
Store version of PS7 not recognized

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#115113]
Testing #114930

I have PS and PS Preview from the store installed. Neither are recognized. Also, nothing here
![image](https://user-images.githubusercontent.com/6561887/105886752-a1084c80-5fbf-11eb-8208-32bb0d8611c7.png)

**Comment by TylerLeonhardt** [comment]
This has stopped working because this commit https://github.com/microsoft/vscode/commit/da0a04fffb90b0f4365b038c39c9e78d97d64e6b fixing https://github.com/microsoft/vscode/issues/111621

which got rid of:

```ts
// This catch will be called on some symbolic links on Windows (AppExecLink for example).
// So we try our best to see if it's a Directory.
try {
    const fileStat = await stat(await readlink(path));
    return fileStat.isDirectory();
} catch {
    return false;
}
```

@bpasero

**Comment by bpasero** [comment]
Sorry for breaking this, I should have looked at who added this code. To clarify: I want [`statLink`](https://github.com/microsoft/vscode/blob/bf93e45b9c64c2713209c7b97c48148922c30119/src/vs/base/node/pfs.ts#L205-L205) to be the only method that handles symlinks and not have different methods in `pfs` doing smarts around symbolic links. If there is another case that `statLink` does not handle well around resolving a symbolic link, we should add the fix into that method because this also means everyone else benefits (e.g. the explorer uses this call as well).

Here is what `statLink` does in a nutshell:
* always use `lstat` instead of `stat` to first find out if the file is a symlink or not
* quickly return with that if not a symlink (`lstat´=== `stat` for non symlinks)
* otherwise do a `stat` to get the actual metadata of the target
* if that fails with `ENOENT` it means the symlink is pointing to a non existing file (=dangling)

One of the main pitfalls with symlinks that `statLink` tries to solve is this pattern:
* you iterate over children of a folder
* you call `stat` on each child to resolve metadata
* you will be surprised to get a `ENOENT` error if you are doing so for a symlink that points to an invalid target (=dangling)

**Comment by bpasero** [comment]
Pushed a fix to add the logic to detect reparse points on Windows into `statLink`. This also means, folders opened in VSCode that have such links now show these properly in the explorer:

![image](https://user-images.githubusercontent.com/900690/105957634-d4a7ad00-6079-11eb-8b6e-997633bb1ed3.png)
