### ISSUE TITLE
Tab wrap - wrapping when too small behaves differently depending on the editor focused

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#115135]
Testing #114827

Here you can see the split JSON editor doesn't wrap when it's too small the sidebar just overlaps, while a webview continues to wrap, and a normal editor stops wrapping alltogether.

![tab-wrapping](https://user-images.githubusercontent.com/641685/105896057-564cfb80-5fe4-11eb-8d32-4f276822308f.gif)

**Comment by bpasero** [comment]
@eamodio I think what you see here is intentional: you are making the window size small enough that the minimal width of the split editor can no longer be met and as such the entire workbench window will become scrollable. This is imho something that @joaomoreno added a few milestones ago where splitviews now can show scrollbars when they get too little.

Proof of what I said is this video:

![Uploading recording (3).gif…]()

See how horizontal scrollbars appear.

**Comment by joaomoreno** [comment]
Each editor can define minimum size constraints: I bet split JSON has double minimum width to a regular editor or webview.

**Comment by eamodio** [comment]
The scrollbar works for the editor part, but not the tabs. Though in today's insiders it behaves a bit differently with the split JSON view, than in my video -- the tabs no longer seem to also slide under the sidebar (which is good). But I still don't understand why, when the active tab is a normal/diff editor, when it gets too small the tabs go back to a single line, but with the split JSON and webviews, it never does.

**Comment by bpasero** [comment]
@eamodio it all depends on what the editor declares as minimal width. We will switch back to non-wrapping mode if wrapping would make the editor get smaller than what it needs. It is quite possible that diff editors have larger size constraints compared to normal editors.
