### ISSUE TITLE
Rethink author verification

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#115274]
A few things:
- Should this be enabled by default?
- How do we work when a closing commit cant be found? Right now it's disabled until we know the commit haas been released, but this can cause some friction. https://github.com/microsoft/vscode/issues/114449#issuecomment-768000659

**Comment by bpasero** [comment]
Yes it should be enabled by default and set the "verified" label instead of the other.

**Comment by JacksonKearl** [comment]
Speaking with @kieferrm opted to not enable by default, though open to removing `z-author-verified` in favor of just `verified`. 

Removed friction for closing commits being not found by relying on the `insiders-released` label -- it will be added automatically if a closing commit can be found, but if it's added manually the bot wont fight with you.

**Comment by bpasero** [comment]
This seems like a weird decision to me:
* some of us asks authors to verify issues
* I for example exchange the `z-author-verified` label with `verified` right away and it looks like we might even make that the default
* at the same time we say here that we do not trust author verification generally

So now we have an inconsistent state where we don't know anymore which issues are properly verified?

Btw one thing I like about author verification is that I get immediate feedback that a fix was not proper, whereas in endgame week I end up with lots of verification found on the last day.

**Comment by kieferrm** [comment]
About 
> opted to not enable by default

Here's the reasoning that went into that after discussing this back and forth:
- Authors do us a great favor when submitting issues. So, let the burden be low on them in return.
- If we're sure we fixed it, we also know how to verify it. 
- If we verify it in endgame week, we know and can rely on the level of diligence that went into verification.
- If we are not sure whether or not we fixed it because we can't repro it for any reason, then it makes good sense to ask the author for help.
