### ISSUE TITLE
Remove keytar shim

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#115215]
Testing #115160

Given that we now have a secrets API we should remove the keytar polyfill

**Comment by gjsjohnmurray** [comment]
What will the migration timetable be for extension authors who currently leverage the keytar bundled with VS Code?

**Comment by RMacfarlane** [comment]
@jrieken Are you saying we re-expose keytar in some way to extensions? The secrets API itself uses keytar, so we can't remove it as a dependency of vscode

**Comment by jrieken** [comment]
Yes - we have [MainThreadKeytar](https://github.com/microsoft/vscode/blob/0299fd433f7f10a003ff3e1428b785c84958c86a/src/vs/workbench/api/browser/mainThreadKeytar.ts#L11-L11) and friends and there is [magic](https://github.com/microsoft/vscode/blob/cba1d1b184883f437cf3777030d4a94ba43b7ee2/src/vs/workbench/api/common/extHostRequireInterceptor.ts#L140) to make use of "our" keytar whenever an extension calls `require('keytar')`. That was done to ensure extensions running remotely use the right keychain (the one with the renderer). All of that is now obsolete and the proper API should be used

**Comment by jrieken** [comment]
A first step could be implement the magic against the new API and nuke the keytar-mainthread stuff etc (iff that's possible)

**Comment by TylerLeonhardt** [comment]
Two problems with doing this:
* Extensions currently depend on this behavior. I've had issues about it because they want to use more advanced secret APIs
* The SecretStorage API has an extra layer of encryption (vscode-encrypt) before storing in keytar... and this means that if an extension wants to share secrets with another application, it can't do that with our API.

Since there's basically no maintenance here, I suggest we keep it around.

**Comment by TylerLeonhardt** [comment]
Now that keytar is dead, we should do this.

**Comment by TylerLeonhardt** [comment]
Based on telemetry, I think this will need to get pushed out one month.
