### ISSUE TITLE
Debug stuck on pause in callback?

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#115254]
Testing #115160

![debug-stuck-on-pause](https://user-images.githubusercontent.com/7199958/106043764-b77fd800-6093-11eb-8518-1ac938031351.PNG)

I can hit the callback, but I can't press the resume button.
If I go to the call stack viewlet and hover over the `Attach to Extension Host` part, I notice that I can press the resume button from there and continue debugging (_just_ learned about this feature while typing up this issue).

I'm guessing it's a glitch in the debugger?

**Comment by RMacfarlane** [comment]
I saw the same thing yesterday: https://github.com/microsoft/vscode/issues/115275

**Comment by isidorn** [comment]
Same as my comment in that issue  - unlucky the only piece of information that I am interested in is collapsed here - the CALL STACK view :)


Thanks for creating this issue.
I have fixed a "somewhat" similar bug 30 minutes ago. In order to know if it is the same bug: does you application have some deemphasized stack frames (they appear grayed out in the CALL STACK)? If answer is yes -> please wait for next Insiders and it should be fixed, if not let me know.

If your application does not have any "grayed out" stack frames, then is it possible that I just clonse the repo and try to reproduce on my own?
If not, we can also involve Connor. But maybe you first answer the first question.

**Comment by rzhao271** [comment]
It's fixed now, thanks!

**Comment by isidorn** [comment]
Thank you!
