### ISSUE TITLE
ctrl c and ctrl x not working

### ISSUE THREAD

**Issue by najjariheb6** [microsoft/vscode#115382]
Issue Type: <b>Bug</b>

 

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (3.76GB free)|
|Process Argv|--crash-reporter-id 5fe78f18-f4d9-4a63-91cc-4386c7b39acd|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
php-intellisense|fel|2.3.14
vim|vsc|1.18.5

</details>

**Comment by gjsjohnmurray** [comment]
Maybe because you have the Vim extension installed? Try using the Extension Bisect command in Command Palette to investigate.

If this doesn't resolve your issue, look at https://github.com/microsoft/vscode/wiki/Keybinding-Issues and if you need more help please provide exact repro steps. See https://github.com/microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions
