### ISSUE TITLE
Git SSH remotes work in terminal, but not in VS Code (in remote mode)

### ISSUE THREAD

**Issue by strogonoff** [microsoft/vscode#115371]
- VSCode Version: 1.53.0-insider (5a52bc29d5e9bc419077552d336ea26d904299fa)
- OS Version: macOS 11.1

Steps to Reproduce:

1. Set up new SSH keys both on local machine and on remote machine [using GitHub’s tutorial](https://docs.github.com/en/github/authenticating-to-github/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent), add both keys to GitHub and make sure they work (`git pull`/`git push` from terminal succeeds both on local and on remote machine)
2. Clone a Git repo from GitHub using VS Code’s command palette
3. VS Code uses HTTPS remote; change it to SSH (to simplify pull/push from outside VS Code) using `git remote set-url origin <SSH URL>`
4. `git pull`/`git push` works from terminal, but using source code panel in VS Code results in `git@github.com: Permission denied (publickey).`

Does this issue occur when all extensions are disabled?: Don’t know how to disable extensions in VS Code Insiders on macOS; there is no `code` utility to be found.

**Comment by strogonoff** [comment]
Happens regardless of `remote.SSH.enableAgentForwarding` value, and it shouldn’t matter anyway since both local and remote machines have SSH keys configured and added to GitHub.

**Comment by eamodio** [comment]
@roblourens Do you have any ideas on this one?

**Comment by roblourens** [comment]
It doesn't sound like Remote-SSH is important here, and SSH forwarding is not involved. 

There might be some other open issues, it sounds like if the key has a passphrase, that won't work - https://github.com/microsoft/vscode/issues/13680

Otherwise, how does git find your key, through an ssh agent, an ssh config, or does it have a default key name/location (like `~/.ssh/id_rsa`)? And seeing the log from git's output channel might be helpful

**Comment by strogonoff** [comment]
I believe Git finds my keys through SSH agent. Will provide more info when I am working in that environment again.
