### ISSUE TITLE
Search in open editors on windows: only files opened this session searched

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#115315]
Open a few files from a workspace (including files not at the root of the workspace). Search in open editors for the regex `.*`. See full set of results. Now reload, search again. Only the opened editors are searched.

**Comment by JacksonKearl** [comment]
\closedWith 660d6b82f85fdf438c01f152a77a1d3d4cf85722

**Comment by ArturoDent** [comment]
Was about to report this too.  Still a file like `<someWorkspaceFolderName>.code-snippets` isn't searched until it is opened.

Path: `C:\Users\Mark\OneDrive\Test Bed\.vscode\test-bed-snippets.code-snippets` or
`C:\Users\Mark\AppData\Roaming\Code - Insiders\User\snippets\insiders.code-snippets`

need to be opened current session to be searched.

Appears to work otherwise.  Should a separate issue be filed?

Not sure if the below version has your recent fix:

Version: 1.53.0-insider (user setup)
Commit: 2ce26643d85bf985d3d3ce6ce0ff5d78866f9b5f
Date: 2021-01-28T13:54:01.170Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.21296

**Comment by JacksonKearl** [comment]
fix is still not out, it should handle that case.

**Comment by ArturoDent** [comment]
Here is a demo immediately following a reload.  All 4 files contain the search query:
  
![searchAll2](https://user-images.githubusercontent.com/31813701/106322911-cac9a980-6233-11eb-96f1-ece7d367f7b4.gif)

Note that `test-bed-snippets.code-snippets` in in the workspace and is found without first touching the file.
`    C:\Users\Mark\OneDrive\Test Bed\.vscode\test-bed-snippets.code-snippets`

The other two global snippets files are NOT in the workspace and are not found via `Search Only in Open Files`.  Their paths:

`    C:\Users\Mark\AppData\Roaming\Code - Insiders\User\snippets\global.code-snippets`

`    C:\Users\Mark\AppData\Roaming\Code - Insiders\User\snippets\insiders.code-snippets`

Admittedly an edge case, doing a search for a term in these global snippets files without having touched them first.

Version: 1.53.0-insider (user setup)
Commit: 5a52bc29d5e9bc419077552d336ea26d904299fa
Date: 2021-01-29T05:13:48.533Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.21301

**Comment by JacksonKearl** [comment]
That's interesting, does this only apply for .code-snippets files or or any out-of-workspace files?

**Comment by ArturoDent** [comment]
I think just the `.code-snippets` files.  At least no problem for these files:

`    C: \Users\Mark\test.js`                                             <= no workspace
`    C: \Users\Mark\folder - operations\extension.js`    <= a different workspace

**Comment by JacksonKearl** [comment]
How bizarre. Created an issue.
