### ISSUE TITLE
Native Notebooks - Right click drop down option for cut/copy/paste text

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode#115443]
Feature Request from Survey Monkey Feedback: 

"There is no cut, copy, or paste for code editing within a cell on the right click popup menu. PLEASE add those! Right slider in insiders version very difficult to grab and disappears when mouse goes away. "

Only options are for cut, copying, pasting entire cell content not text within cell 
![image](https://user-images.githubusercontent.com/19276747/106337800-fe61ff00-6246-11eb-93e9-0f3c9fbc6f25.png)

**Comment by roblourens** [comment]
This is what you should see if you right click on the editor, not the rest of the cell, but the screenshot makes it look like the right place was clicked

![image](https://user-images.githubusercontent.com/323878/112564232-2168e500-8d98-11eb-8dcf-4003cd853d20.png)

Do you repro this @rebornix?

**Comment by roblourens** [comment]
Oh, I am indeed getting the wrong context menu on Windows...

**Comment by roblourens** [comment]
Basically the editor handles this first and shows the context menu, then the contextmenu event bubbles up to the list, which tries to show its context menu. I think that when a native context menu is visible, we ignore the next showContextMenu call, but with the custom one, we don't do that.

I don't know what the right fix is:

- Custom context menu should say the first call takes precedence instead of the second, like native? @sbatten ?
- Editor should call stopPropagation when it handles a contextmenu event? @rebornix ?

**Comment by sbatten** [comment]
I wasn't aware of the native case ignoring the next showContextMenu call, but it seems fishy. stop propagation seems like the more natural way to do this.

**Comment by roblourens** [comment]
Maybe that's something that the OS does

**Comment by roblourens** [comment]
Let me know if that's ok @rebornix
