### ISSUE TITLE
Rephrase slow shell warning message

### ISSUE THREAD

**Issue by haydenjeune** [microsoft/vscode#115444]
The warning message that appears when your shell is slow to start currently reads

> Resolving your shell environment is taking very long. Please review your shell configuration.

I think the phrasing could be improved here, as I don't believe the "taking very long" bit is correct English. 

Not a big deal at all, but I thought I would raise an issue and corresponding PR if you're interested in minor fixes like this. 😄

**Comment by andronocean** [comment]
Yes please! This grammar error annoys me too often. I'd suggest simply saying "Resolving your shell environment is taking a long time" (since this warning appears after [just 3 seconds](https://code.visualstudio.com/docs/supporting/faq#_resolving-shell-environment-is-slow-error-warning)... I don't think that merits a _"very"_.)

**Comment by smallsaucepan** [comment]
Hi @meganrogge. Would you consider reopening this and accepting a pull request of @andronocean 's wording? It is only a little thing. However, VSCode is otherwise so polished it sticks out like a sore thumb. Thanks :)
