### ISSUE TITLE
node.js: Debug console always displays some internal line number for every console.log message.

### ISSUE THREAD

**Issue by mplwork** [microsoft/vscode#115408]
- VSCode Version: 1.52.1
- OS Version: Windows 10 Enterprise 1909 

Steps to Reproduce:

Whenever I issue a `console.log` statement in a nodejs program the Debug console in vscode displays as line number `node_modules/diagnostic-channel-publishers/dist/src/console.pub.js:42` instead of the location where my `console.log` statement occurs.  I am pretty sure this was not the case earlier.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by connor4312** [comment]
This is because [diagnostic-channel-publishers](https://www.npmjs.com/package/diagnostic-channel-publishers) overwrites your console.log message with its own method and calls the real console method internally.

You can add the package to your [skipFiles](https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_skipping-uninteresting-code) to avoid this.
