### ISSUE TITLE
[json] Error with accessing schemaservice://combinedschema

### ISSUE THREAD

**Issue by nvmker** [microsoft/vscode#115419]
- VSCode Version: 1.52.1
- OS Version: macOS 11.1

Steps to Reproduce:

1. Install following two extensions: https://github.com/42Crunch/vscode-openapi and https://github.com/microsoft/vscode-cpptools
2. Create .vscode/c_cpp_properties.json in a root of workspace with following content:
```
{
  "configurations": [
    {
      "name": "macOS",
      "includePath": [
        "${workspaceFolder}/**",
        "${workspaceFolder}/../../Daisy/libDaisy/**",
        "${workspaceFolder}/../../Daisy/DaisySP/**"
      ],
      "defines": [
        "_DEBUG",
        "UNICODE",
        "_UNICODE"
      ],
      "compilerPath": "/usr/local/bin/arm-none-eabi-g++",
      "cStandard": "c11",
      "cppStandard": "c++17"
    }
  ],
  "version": 4
}
```

Does this issue occur when all extensions are disabled?: No

Looks like there is a bug related to JSON schema validation, as result of above steps I'm getting a following error in "Problems" tab:
```
{
	"resource": "/Volumes/Main/Dropbox/code/personal/DaisyMy/FM/.vscode/c_cpp_properties.json",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": "768",
	"severity": 4,
	"message": "Problems loading reference 'schemaservice://combinedschema/cpptools-schema%3A/c_cpp_properties.schema.json': Unable to load schema from 'schemaservice://combinedschema/cpptools-schema%3A/c_cpp_properties.schema.json': cannot open schemaservice://combinedschema/cpptools-schema%3A/c_cpp_properties.schema.json. Detail: Unable to resolve resource schemaservice://combinedschema/cpptools-schema%3A/c_cpp_properties.schema.json.",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 2
}
```
There is a detailed explanation of this issue:
https://github.com/42Crunch/vscode-openapi/issues/107#issuecomment-769876948

**Comment by TBBle** [comment]
Just to be clear this isn't just a conflict with vscode-openapi, the same problem can be caused by https://marketplace.visualstudio.com/items?itemName=Arjun.swagger-viewer, or _any_ extension that claims '*.json', as noted in the linked comment by @ak1394:
> To illustrate the issue I have created a minimal extension which simply contributes a schema for "*.json" files, and doesn't do much besides it. If you install this extension along with CPP one you'll see the same problem as with vscode-openapi. The extension is here: https://github.com/42Crunch/vscode-minimal-issue-107

<details>

----

<summary> A different, future problem </summary>

I suspect the problem lies in https://github.com/microsoft/vscode-json-languageservice, as [`createCombinedSchema`](https://github.com/microsoft/vscode-json-languageservice/blob/07fec3faafa3f32915dcd6fcc6999a91ad113f88/src/services/jsonSchemaService.ts#L573-L583) is trying to populate `'schemaservice://combinedSchema/' + encodeURIComponent(resource);` as an `allOf` for each matching schema but in the case we're hitting here (i.e. register a _potential_ schema for any JSON file), that would need to be `anyOf`, since if the OpenAPI schema matches, it's unlikely to _also_ be some other kind of JSON file, and vice-versa.

```typescript
	private createCombinedSchema(resource: string, schemaIds: string[]): ISchemaHandle {
		if (schemaIds.length === 1) {
			return this.getOrAddSchemaHandle(schemaIds[0]);
		} else {
			const combinedSchemaId = 'schemaservice://combinedSchema/' + encodeURIComponent(resource);
			const combinedSchema: JSONSchema = {
				allOf: schemaIds.map(schemaId => ({ $ref: schemaId }))
			};
			return this.addSchemaHandle(combinedSchemaId, combinedSchema);
		}
	}
```

----

</details>

Hmm. Actually, the above is probably a future problem, not the current problem. I note that the cpp-tools schema contribution is `cpptools-schema:///c_cpp_properties.schema.json`.

So I wonder if this error is coming because something is trying to find a schema _for the _c_cpp_properties.schema.json_, not the c_cpp_properties.json we have opened, and _that_ lookup is miscreating the URL as `schemaservice://combinedschema/cpptools-schema%3A/c_cpp_properties.schema.json` instead of `schemaservice://combinedschema/cpptools-schema%3A///c_cpp_properties.schema.json`.

I'm not sure how to open `cpptools-schema:///c_cpp_properties.schema.json` in VSCode to verify this though. The C++ extension contributes an activation trigger `onFileSystem:cpptools-schema` but I don't know how to _use_ that.
