### ISSUE TITLE
Update CSS Language Syntax

### ISSUE THREAD

**Issue by cssinate** [microsoft/vscode#115480]
- VSCode Version: 1.52.1
- OS Version: Windows 10.0.18363

Steps to Reproduce:

1. Look at https://github.com/microsoft/vscode/blob/81ae94a9dc82197829717915db783e3b934db46a/extensions/css/syntaxes/css.tmLanguage.json#L1817
2. Compare to https://github.com/atom/language-css/blob/21cfdb766587c351ac9873ecce0075b8c05799c5/grammars/css.cson#L2035

Does this issue occur when all extensions are disabled?: Yes

There was a fix some time ago for this issue: atom/language-sass#226 where in SCSS, property names that shared a name with a tag name were colored incorrectly. That fix has not been ported over to VSCode. As per https://github.com/microsoft/vscode/blob/81ae94a9dc82197829717915db783e3b934db46a/extensions/css/syntaxes/css.tmLanguage.json#L3 I am requesting an update to this file. Thank you!

**Comment by alexr00** [comment]
We get our css grammar from https://github.com/octref/language-css, so changes to  https://github.com/atom/language-css would need to pulled into there.

@octref is https://github.com/octref/language-css being maintained?

**Comment by cssinate** [comment]
Ah! I'm *not* crazy. I first started looking into the bad highlighting in SASS a long time ago and gave up when I couldn't figure it out, and only started digging into it again recently. When I first looked into it, it was derived directly from atom's version of the language:

https://github.com/microsoft/vscode/commit/e62554e4b19a6bf4dc35273e84603d4b1cb22ef0#diff-41108266fb098e0fb5d4f0fbdab607f29ffc0143e1c4914c83fbdc28da29ab6fL7

I neglected to check that line to notice it had changed. I made a [PR](https://github.com/octref/language-css/pull/4) on the octoref version. Could we please leave this issue open until it's confirmed that it's either merged or won't be merged for some reason?

**Comment by cssinate** [comment]
@alexr00 - how long do we wait for a response? Does this issue *only* move forward with octref's help? Their blog says they're not even at Microsoft anymore. I don't want to bother them. It seems strange that it got moved away from Atom's grammar as reference anyway, for exactly this reason: Atom isn't going to stop being maintained anytime soon.

**Comment by alexr00** [comment]
Many of our grammars are maintained by non-Microsoft developers, so this is very normal. However, since this isn't the only css grammar related issue that hasn't gotten a response, I'm happy to change grammars to the one that is maintained (atom/language-css). 

Here are the bugs/missing features that we would be accepting by changing to atom/language-css. This may not be a complete list, but based on the diffs this is what I see:
https://github.com/microsoft/vscode/issues/54515
Maybe https://github.com/microsoft/vscode/issues/57407, would need to test.
Some of these properties may have been added in the other repo: https://github.com/octref/language-css/commit/6d3a2d01dd67ef062030f4520dd42a5424330a3b
https://github.com/octref/language-css/commit/ea1d7e3619966e47c57498913a5eabea0cce7538

**Comment by cssinate** [comment]
I'm just a bit confused by the second part; are there parts that are in octref's repo that aren't in Atom's? Do you need a hand comparing octo's to Atom's and/or making PRs to Atom's for discrepancies?

**Comment by alexr00** [comment]
> are there parts that are in octref's repo that aren't in Atom's? 

Yes.

> Do you need a hand comparing octo's to Atom's and/or making PRs to Atom's for discrepancies?

I already hand compared (which is how I came up with the list of bugs/missing features). We try not to be in the business of writing grammars since there are many languages and we aren't experts in many of them. This is why we get our grammars from OSS. If a member of the community wanted to take a close look at my list [here](https://github.com/microsoft/vscode/issues/115480#issuecomment-776008534) and make PRs for bugs and missing features in the atom/language-css grammar (or verify that the issue doesn't exist in the atom grammar), then I would have no reason _not_ to use that grammar 😉. 

That said, I'm inclined to adopt atom/language-css even if no one from the community wants to do that. A maintained grammar should be better on average.

**Comment by cssinate** [comment]
Cool! I've just about had it up to here with language grammars for a while, but I don't mind circling back in a month or two to take a deeper look at those changes and making PRs against atom if necessary. Thanks, Alex :smiley:

**Comment by cssinate** [comment]
As an update, I did some homework and made PRs for the things that made sense to. 
- #54515 references a deprecated feature. Although it would only be a small fix, it doesn't seem important/relevant.
- #57407 said near the end that it's [no longer an issue](https://github.com/microsoft/vscode/issues/57407#issuecomment-544638447). I did see if I could reproduce the error, and I was unable to.
- I've made PRs atom/language-css#173 and atom/language-css#174

**Comment by alexr00** [comment]
I've moved to March to give the folks over in atom/language-css time to look at @cssinate's PRs.

**Comment by cssinate** [comment]
You're welcome to of course, but I don't feel waiting is necessary. The PRs
on Atom just update Atom's dependency on version 0.44.5 of language-css.
The language file is sound. If you copy my changes that are in language-css
into the correct file in VSCode's extensions, it works as expected.

**Comment by alexr00** [comment]
It doesn't seem like those PRs are getting any attention. However, since the grammar is well maintained I will try switching over to it anyway. If there aren't any big concerns after switching, then I'll keep the change in.

**Comment by cssinate** [comment]
Ok. I'll keep an eye on the Atom PRs and open and mention you in a new
issue when they get merged.

**Comment by alexr00** [comment]
This can be verified by seeing that the integration tests pass (specifically the colorizer integration tests).
