### ISSUE TITLE
Remote-SSH when connecting to Windows machine: The terminal process failed to launch

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#115581]
I haven't tried SSH from this machine in a couple of weeks, but it used to work. Now each time I try to create a terminal I see:

![image](https://user-images.githubusercontent.com/641685/106554358-07b1cc80-64d0-11eb-8842-4a21caab0c25.png)

And this is in the console:
```
The terminal process failed to launch: A native exception occurred during launch (Unable to start terminal process: CreateProcess failed)```

**Comment by Tyriar** [comment]
Need more info about the remote setup, OS versions, etc.

**Comment by eamodio** [comment]
@Tyriar 

Using SSH
Host: Windows 10 Build 19042.789 (20H2) (Beta Insiders Channel)
Client: Windows 10 Build 21301 (ARM64) (Dev Insiders Channel)

What other info can I provide?

**Comment by eamodio** [comment]
I haven't proven this yet, but I think this might be because on the host I have PowerShell installed from the MS Store. Because if I try to ssh from the Windows Terminal, I can connect (to cmd), but if fails if I try to run `pwsh`.

**Comment by Tyriar** [comment]
Another thing with connecting to windows specifically is that winpty is forced. I think the reason for that was the hang bug that we should be fixing in Feb https://github.com/microsoft/vscode/issues/71966

**Comment by eamodio** [comment]
On my client machine (ARM64), it still worked with conpty disabled.

**Comment by eamodio** [comment]
@Tyriar So my suspicions about this being caused by the Store version of PowerShell turned out to be correct. I uninstalled the Store version, installed it directly from the MSI, and now everything works again.

/cc @TylerLeonhardt

**Comment by TylerLeonhardt** [comment]
Interesting... this must be a weird edge case of the MSIX's sandboxing?

cc @stevel-msft @bagajjal

**Comment by carlossanlop** [comment]
I can reproduce, and I have somewhat similar environment as @eamodio . 

I'm an employee, feel free to contact me on Teams for more info or to show you a repro. @Tyriar @TylerLeonhardt 

For me, it _seems_ the issue is that the remote PowerShell instance cannot be invoked. I can only make my remote shell work if I use a cmd shell.

## Environment

- Client machine:
    -  Arch: ARM64 (Surface Pro X)
    - OS: Windows 11 Version 21H2 (Build 22000.168)
    - VS Code About info:
```
Version: 1.59.1 (system setup)
Commit: 3866c3553be8b268c8a7f8c0482c0c0177aa8bfa
Date: 2021-08-19T11:56:07.791Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT ia32 10.0.22000
```

- Remote machine:
    - Arch: x64
    - OS: Windows 10 Version 21H1 (Build 19043.1110)
    - PowerShell: 7.1.4.0 installed via **Microsoft Store**
    - VS Code About info (not sure if relevant or if it affects this issue, but here it is): 
```
Version: 1.60.0-insider (system setup)
Commit: c08913337cb8b95493be8e99d62e0b3241563f6b
Date: 2021-08-19T05:15:46.693Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043
```


## What I tried

In my client machine (ARM64), I opened Settings -> Remote [SSH] -> Terminal, then opened the settings.json file. There are 3 settings items that I can configure:

- `terminal.integrated.automationShell.windows`
- `terminal.integrated.defaultProfile.windows`
- `terminal.integrated.profiles.windows`

The autocomplete offers 3 possible values for any of those 3 items: "PowerShell", "Command Prompt", "Git Bash".

The only one that does not work is PowerShell. I get the same error message:

> The terminal process failed to launch: A native exception occurred during launch (Unable to start terminal process: CreateProcess failed).

I am not sure if this is relevant, but as I mentioned in my environment info, the PowerShell I installed comes from the Microsoft Store, so it's not installed in `C:\Program Files\`, but rather in the folder where all the App Execution Aliases live: `%LOCALAPPDATA%\Microsoft\WindowsApps`.

With this info, I _also_ tried to create my own custom profile, like this:

```
"terminal.integrated.profiles.windows": {
     ... // Here are PowerShell, CommandPrompt and Git Bash defined
     ...,
        "Custom": {
            "path": "${Env:LOCALAPPDATA}\\Microsoft\\WindowsApps\\pwsh.exe",
            "icon": "terminal-powershell"
        }
```
But this did not work: When I try to create a new shell instance, the "Custom" option does not show up. I assume App Exec Aliases cannot be executed from VS Code.


## Workaround

Set `terminal.integrated.defaultProfile.windows` to "Command Prompt", and you should be able to connect remotely.

Unfortunately, Application Execution Aliases also can't be executed from within cmd (the pws.exe installed from Microsoft Store cannot be invoked). So you're stuck using cmd.

**Comment by davetapley** [comment]
Thanks for the _use MSI installer_ workaround @carlossanlop 🎉 

I'll just add that I also needed to do:
```
"terminal.integrated.defaultProfile.windows": "PowerShell",
```

Else I get:
```
The terminal process failed to launch: Path to shell executable "C:\Users\azureuser\AppData\Local\Microsoft\WindowsApps\Microsoft.PowerShell_8wekyb3d8bbwe\pwsh.exe" does not exist.
```

Not sure if that's some hangup of having had `pwsh.exe` installed with Microsoft Store (prior to uninstalling and reinstalling with MSI), and VS Code has somehow cached that `\WindowsApps\` path?

**Comment by carlossanlop** [comment]
> Unfortunately, Application Execution Aliases also can't be executed from within cmd

The issue does not seem to be related to VS Code. It's related to OpenSSH Server on Windows and its inability to handle Microsoft Store app exec links correctly.

I opened this issue to track it from the OpenSSH side: https://github.com/PowerShell/Win32-OpenSSH/issues/1862

**Comment by tanhakabir** [comment]
Seeing this issue on macOS as well.

**Comment by matty-r** [comment]
I'm getting this issue. On Linux with Remote-SSH into Windows Server 2016.

Running a batch file or powershell task just results in a failure.

Tasks.json:
```json
{
    "label": "Sync only",
    "type": "shell",
    "command": "C:/Users/dev/gitToProdSync.bat",
    "problemMatcher": []
},
{
    "label": "Sync Task ps1",
    "command": "powershell",
    "args": [
        "C:/Transfer/git/.vscode/runGitSyncTask.ps1"
    ],
    "type": "shell",
    "problemMatcher": []
}
```

```
> Executing task: powershell C:/Transfer/git/.vscode/runGitSyncTask.ps1 <

The terminal process failed to launch: A native exception occurred during launch (Unable to start terminal process: CreateProcess failed).

Terminal will be reused by tasks, press any key to close it.
```
