### ISSUE TITLE
Restoring debug view on startup is not smooth

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#115585]
I started VSCode out of sources via command line. Check out how many transitions the debug view goes through until ready:

![recording (1)](https://user-images.githubusercontent.com/900690/106564919-378fbd00-652e-11eb-8f01-6eb157bfb03e.gif)

I see:
* "Run" without twistie
* "Run" with twistie
* Title without "Run"
* "Run" moves to Title
* Other views appear

**Comment by sandy081** [comment]
@isidorn I see you have set when context for all debug views `CONTEXT_DEBUG_UX`. Because of this debug views are getting enabled at different timings. From the infrastructure side, we are trying to cache previous views count and trying to to merge/not merge the title on reload. But once extensions are loaded we revalidate and update view to merge/not merge. 

I think the root cause here is that Run (welcome) view is appearing for a short moment. So, I would recommend to cache the `CONTEXT_DEBUG_UX` state (at workspace scope) and set it before registering the views and revalidate the state later when you know the truth.

**Comment by bpasero** [comment]
@sandy081 @isidorn seeing something similar also in the explorer, check how the twistie only appears later:


https://user-images.githubusercontent.com/900690/106712642-88201c80-65f9-11eb-879c-49cec53961e6.mov

I am feel this was not the case before.

**Comment by sandy081** [comment]
@bpasero twisties is a different issue - I suspect this is because of codicons taking time to load. If I remember I noticed similar behaviour on activity bar too, if you have codicons and svgs - codicons are loaded later than svgs. I would recommend to file a separate issue for this.

**Comment by isidorn** [comment]
@sandy081 your suggestion makes sense and I have implemented it. With it I see reduced flashing. I still see the twisties appearing late, but there is a different issue for that
@bpasero let me know if this is now also better for you - it should be.

**Comment by bpasero** [comment]
Yeah looks better, I also only see the twisties.

**Comment by isidorn** [comment]
Adding VERIFIED label based on happy users comment :D
