### ISSUE TITLE
Extension host communication does not throw when process is gone

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#115588]
Steps to Reproduce:

1. follow https://github.com/microsoft/vscode/issues/115028#issuecomment-770997972

=> 🐛 we end up in calls to the extension host (backup, or saving) that never return

**Comment by alexdima** [comment]
@rebornix Looking at the steps... 

If an extension host crashes or shuts down, then `MainThreadNotebooks` has the responsibility to clean up absolutely all state in the workbench associated with that extension host. The class has a `dispose()` method that is called for this purpose.

So long story short, `MainThreadNotebooks` is effectively used after being disposed. I can see that the class has a member `_notebookProviders` that contains disposables which are not cleaned up from the `dispose()` method.

Another way that this bug manifests itself is if you manually kill the extension host process and then relaunch it. The workbench will have multiple notebook controllers.

**Comment by alexdima** [comment]
@rebornix I have extracted the problematic forgotten `IDisposable`s in `MainThreadNotebooks` in https://github.com/microsoft/vscode/issues/115698

After debugging this, `MainThreadNotebooks.dispose()` was not called in this case because the exit/crash handler in the extension service was behaving differently due to this being an extension development instance (`environmentService.isExtensionDevelopment` was set). I will push a fix to dispose extension host things before attempting to close the current window.

**Comment by rebornix** [comment]
@alexdima thanks!

**Comment by bpasero** [comment]
Verified that I can now close the debugger even when having dirty notebooks around in the target 👍
