### ISSUE TITLE
Custom editors have a hard time implementing isSaving()

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#115526]
We have [`EditorInput#isSaving`](https://github.com/microsoft/vscode/blob/1aa795f2ff13b91e45500cc4a04d6d549e095cd0/src/vs/workbench/common/editor.ts#L456-L456) and it is implemented across normal editors and custom editors (notebooks, search editor, custom editor).

The intent is to have a way to tell the workbench whether to treat the editor as dirty or not. The main use case is to NOT draw a dirty indicator for editors when auto save is configured by default (after delay of 1s).

As such, if `true` is returned from `isSaving`:
* no dirty indicator is being drawn
* you can close a dirty editor while it is being saved in the background
* you do not get any dialogs from these editors to save or revert

However there is a catch: you really need to take care implementing this method properly because of errors that can happen when saving (as e.g. indicated by https://github.com/microsoft/vscode/issues/115414 from @Tyriar). Imagine this:
* auto save is on
* user changes a custom editor
* auto save saves
* there is an error when saving

You will end up with:
* no dirty indication
* possible data loss because you can close the editor

Text editors solve this issue by:
* knowing when a save failed ([here](https://github.com/microsoft/vscode/blob/2feb009c8efce2ab0b6ac03d4e143854bf413d57/src/vs/workbench/contrib/files/common/editors/fileEditorInput.ts#L270-L270))
* always making sure that dirty editors are opened ([here](https://github.com/microsoft/vscode/blob/8fcf778ba251131780f2a110d311161f39b97b03/src/vs/workbench/contrib/files/browser/editors/textFileEditorTracker.ts#L49-L49))

For now I will remove the implementations of `isSaving` from:
* custom editors
* notebooks (cc @jrieken @rebornix)
* search editors (cc @JacksonKearl)

This means that those custom editors will show normal dirty indicators even when auto save is on.

I have no clear idea yet how to bring this back but ideally this would be something that the workbench implements in a generic way, though we would then need to know from each working copy if a save succeeded or not.

**Comment by bpasero** [comment]
@mjbvz I was wondering: is it even possible for an extension to implement saving for a custom editor in the background if most likely the model lives inside the `webview` anyway? Because with the editor closing, the `webview` is gone as well and so it is probably not possible to continue saving after the editor has closed?

**Comment by Tyriar** [comment]
@bpasero couldn't the custom editor shutting down delay closing and veto if necessary like regular editors?

**Comment by bpasero** [comment]
@Tyriar afaik there is currently no API for a custom editor to prevent or prolong closing of an editor. It is basically bound only to the `isDirty` and `isSaving` methods of the input:
* `isDirty: true`: prevent close unless `isSaving: true`

**Comment by Tyriar** [comment]
I guess I'm just not understanding what the issue is here as I haven't dealt with the code much. In https://github.com/microsoft/vscode/issues/115404 what I want is for a custom editor to be able to throw during a save, so an custom editor would:

1. Flag as isSaving
2. Call the save extension function
3. Catch the exception
4. Mark isSaving = false and isDirty = true, showing the dirty indicator

It could then continue to try auto saving and it may succeed in which case `isDirty` could be cleared.

Not sure why this would be different for shutting down, is it because we don't auto save _editors_ immediately but not the _documents_? If so could we change that logic for editors that rely on webviews to block closing while `isSaving` is true?

**Comment by bpasero** [comment]
@Tyriar maybe the name `isSaving` was not a very good pick and I can see some confusion with #115404 which seems unrelated to me.

The intent of `isSaving` is only this:
* do not draw a dirty indicator when auto save is configured after a delay of <= 1 seconds
* allow to close an editor even when it is not saved but dirty given it will be saved in <= 1 seconds
* trust the editor that it is capable of opening the editor again dirty when auto save fails
* trust the editor that it will return `false` from `isSaving` even when auto save is enabled but when the editor failed to save so that an editor can draw the dirty indication

As such, custom editors would have to implement all these cases which is likely harder when the `webview` goes away. 

It is not meant as a way to signal auto save capabilities at all. This is even more obvious when you see how this method only checks for when auto save is configured for a delay of <=1s.

**Comment by bpasero** [comment]
As for shutdown: if auto save is enabled (really any setting of auto save) we automatically trigger a save of all dirty editors before continuing on the shutdown:

https://github.com/microsoft/vscode/blob/4342faa67cf5858d175878abd1538ad822a1b170/src/vs/workbench/contrib/backup/electron-sandbox/backupTracker.ts#L91-L91

This is combined with the handling of backups because these two are tightly coupled.

**Comment by Tyriar** [comment]
This seems related to another one of my other requests (https://github.com/microsoft/vscode/issues/113705) where I want more control over the webview context so that I can dispose it when I want it to free up memory, but not the current behavior of `retainContextWhenHidden: false` where it gets shut down immediately when the tab changes since the backup may not have run yet. The reasons it may not have run are that the tab could be closed within the 1-2 seconds after an edit when the backup is performed, or I block backups explicitly because the image is too large to avoid locking up the webview's main thread.

Perhaps if `retainContextWhenHidden` is true or however we decide to handle https://github.com/microsoft/vscode/issues/113705, the webview could live even beyond when the editor closes as the extension has opted into controlling the context's lifespan? Once it's definitely saved or backed up and we dispose the document, it's safe to dispose the webview as well?

**Comment by bpasero** [comment]
With file working copies, it is now easier than before to take the file editor input [approach](https://github.com/microsoft/vscode/blob/11a7f9565ea8b3e1fa1791606d1410cf02f345b2/src/vs/workbench/contrib/files/common/editors/fileEditorInput.ts#L256-L267). Still, adoption has to happen in each input because only inputs know which underlying model they operate with.
