### ISSUE TITLE
Make peek view more discoverable

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#115770]
ideas:

- light bulb icon if cursor on the line
- open peek action from context menu / codelens?
- hover action

**Comment by RMacfarlane** [comment]
@connor4312 I think I'm testing the right thing here based on glancing at the commit, but just want to confirm:

1. Run a test that fails, a peek view gets shown over the portion that failed ✅  this is discoverable
2. Close peek view, hover again over the failing part, the error is shown in the hover ✅  this is discoverable

Having it in the hover instead of a peek view seemed a little bit weird to me, I think I prefer your idea of opening the view from a codelens. This feels very close to the references peek view - the reason I saw the hover is that I was looking for a codelens near the line of code
