### ISSUE TITLE
Jumping intelisense window when close to the bottom of window

### ISSUE THREAD

**Issue by normalser** [Microsoft/vscode#11579]
- VSCode Version: Code - Insiders 1.5.0-insider (538cd9ded5a471fbb20920f01eff9c8df4b83ee9, 2016-09-05T08:31:20.203Z)
- OS Version: Darwin x64 15.6.0

![3q0lwt5mzi](https://cloud.githubusercontent.com/assets/1723815/18273538/b85de088-740b-11e6-82aa-368669b05d4d.gif)

Happens on every keydown (even if you can see it 3 times on the gif - refresh rate of this gif is not high enough)

**Comment by alexandrudima** [comment]
The suggest widget asks to be rendered below the current line if possible, otherwise above the current line. 

AFAIK the suggest widget fetches the documentation label (the thing in red) lazily. 

So every time you move cursor up or down, it renders the widget without the documentation label (making it of height `h`) where `h` fits below the current line and pings the editor to render it. The editor renders it under the line because `h` fits below the current line.

It then fires an async request to fetch the documentation label, which it receives pretty quickly. It then renders the documentation label and renders the widget with the documentation label (making it of height `H` > `h`) where `H` no longer fits below the current line and pings the editor to render it. The editor renders it above the line because `H` does not fit below the current line.

**Comment by joaomoreno** [comment]
One way we could fix this would be to always include a line `no documentation` in items that lack it. Thoughts?

**Comment by alexandrudima** [comment]
:+1: Maybe an empty line that turns to "Loading..." after 100ms if no reply is received and then turns to `"no documentation"` if an empty reply is received

**Comment by joaomoreno** [comment]
#12632
