### ISSUE TITLE
Second vscode window is flashing/blanking

### ISSUE THREAD

**Issue by kolbma** [microsoft/vscode#115804]
Issue Type: <b>Bug</b>

After update to the latest version 1.53 I can only use a single vscode window. The 2nd window isn't working and flashing or blinking all over. 

VS Code version: Code 1.53.0 (8490d3dde47c57ba65ec40dd192d014fd2113496, 2021-02-03T15:56:04.185Z)
OS version: Linux x64 5.3.18-lp152.60-default

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU  N3700  @ 1.60GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.62GB (0.27GB free)|
|Process Argv|. --no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|xfce|
|XDG_CURRENT_DESKTOP|XFCE|
|XDG_SESSION_DESKTOP|xfce|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
better-toml|bun|0.3.2
EditorConfig|Edi|0.16.4
vscode-todo-plus|fab|4.18.2
rust-analyzer|mat|0.2.473
crates|ser|0.5.5
vscode-lldb|vad|1.6.1

</details>

**Comment by gjsjohnmurray** [comment]
Does the problem also happen after you run disable all of your extensions?

**Comment by kolbma** [comment]
I have not tested this.  
Need to work.  

But the enabled extensions are these from the attached image...
![vscode-Screenshot_2021-02-05_12-17-55](https://user-images.githubusercontent.com/5228369/107031291-3bcc0c80-67b2-11eb-9420-3d8a2e8f744f.png)

**Comment by kolbma** [comment]
Maybe I should also explain what I experience with blinking/flashing...

The window shows only a background, an empty sidebar and doesn't react to anything. So no window menu opens. When resizing the window, the status bar needs many seconds to adjust to the window size. It is also something from UI flickering around on the background, but this is not viewable and has only the effect of flickering.
No idea why an extension would be allowed to produce such a result, if it is an extension.

**Comment by gjsjohnmurray** [comment]
Extensions can contribute items to the status bar. With respect, you are best placed to run the test with all extensions disabled.

1. Close all VS Code windows.
2. Start one from the command line: `code --disable-extensions`
3. Look for the notification that all extensions are disabled.
4. Repeat 2 and 3 to start a second window.
5. If you can reproduce the problem then it's not being caused by an extension you added.

**Comment by kolbma** [comment]
I've done a screenrecording: https://youtu.be/8AjpdHyon4g

It is nearly the same with disabled extensions. First window works without problems and the 2nd has wrecked graphic and doesn't react as expected to input.

**Comment by stvvt** [comment]
I am experiencing exactly the same behavior as shown in the screen recording. 

I am using vscode under XFCE too. (XUbuntu 16.04)

Changed `window.titleBarStyle` from `custom` to `native` and the second window now is OK. However, now the menu items (both main menu and context menus) don't get highlighted on mouse hover, which is a bit annoying.

**Comment by isidorn** [comment]
From the recording looks like an Electron rendering issue, thus also assigning to @deepak1556

**Comment by deepak1556** [comment]
Does running with `code --disable-gpu` help ?

**Comment by migrc3** [comment]
In my case, it works fine when I run it with `code --disable-gpu`. In fact, it solves both this issue and also (#115868)

**Comment by deepak1556** [comment]
@migrc3 can you try the latest insiders and check if the issue is fixed https://code.visualstudio.com/insiders

**Comment by migrc3** [comment]
@deepak1556 I've tried the insider version (`1.54.0-insider`) and the behaviour is exactly the same. I think the problem is not to open a 2nd window per se, but to maximize it. So, I can resize the window and it works fine as long as I don't maximize it.



---

VS Code version: Code - Insiders 1.54.0-insider (9ecd3fc3022e8c154aff868f74bd5d77f7d4a2ea, 2021-02-23T10:46:17.855Z)
OS version: Linux x64 4.4.0-201-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 x 2609)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 2|
|Memory (System)|15.54GB (0.82GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 85235f11-ab3c-4bd2-beed-161559e26f7c|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details>Extensions: none

**Comment by deepak1556** [comment]
Thanks for testing, you can disable gpu acceleration https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration for now.

**Comment by migrc3** [comment]
Thank you

**Comment by kolbma** [comment]
This works now again out of the box
```
Version: 1.57.1
Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
Date: 2021-06-17T13:26:56.255Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Linux x64 5.3.18-lp152.78-default
```
