### ISSUE TITLE
Terminal displays Electron warning when using git bash commands

### ISSUE THREAD

**Issue by Trustp** [microsoft/vscode#115888]
Issue Type: <b>Bug</b>

I have set the terminal to the windows git bash terminal and code as editor in git.
When using comands such as:
>git commit -a --amend --date=now

The editor behaves as intended, however a warning from electron shows up in the terminal with the message :
>"(electron) Sending uncompressed crash reports is deprecated and will be removed in a future version of Electron. Set { compress: true } to opt-in to the new behavior. Crash reports will be uploaded gzipped, which most crash reporting servers support."

VS Code version: Code 1.53.0 (8490d3dde47c57ba65ec40dd192d014fd2113496, 2021-02-03T20:36:38.611Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-1270P CPU @ 3.80GHz (16 x 3792)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.72GB (8.29GB free)|
|Process Argv|--crash-reporter-id e223d324-a860-469c-bdcb-d27c1656af6d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2021.1.502429796
jupyter|ms-|2020.12.414227025
cpptools|ms-|1.2.0
vscode-icons|vsc|11.1.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30211402
vstry914:30250197
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30251590

```

</details>

**Comment by nikonso** [comment]
Just one more data point to confirm this report

Note that I'm using powershell, so it's not bash specific

![image](https://user-images.githubusercontent.com/16099035/107062300-113d7c00-67d1-11eb-9cc9-ffe98a571417.png)

**Comment by uwenayoallain** [comment]
I am facing that problem too,
![Screenshot (56)](https://user-images.githubusercontent.com/66881609/107144289-e6733500-6942-11eb-92d8-7c31265f5c4c.png)

**Comment by pkutaj** [comment]
Also Windows10 + Powershell Core — and not using git, just invoking `$profile`

![2021-02-13-169](https://user-images.githubusercontent.com/48290428/107846143-58cb9580-6dd9-11eb-9706-33577029c8d5.gif)

**Comment by ralish** [comment]
This is being caused by Electron's Crash Handler which VS Code uses. You can see the initialisation of it in [src/main.ts](https://github.com/microsoft/vscode/blob/main/src/main.js#L370-L375). In theory, fixing it is as easy as passing the `compress: true` parameter in the start options. What's unclear is if the backend server which receives crash reports supports GZip compression. If not, it'd need to be updated to support GZip'd crash reports, but it looks like that's going to be required at some point regardless.

A few other notes:
1. The issue occurs when invoking `Code.exe` from a console.
2. The issue impacts Git for Windows when VS Code is selected as the default editor during installation. This results in setting the `core.editor` setting in `.gitconfig` to point to `Code.exe`, so Git ends up hitting the above scenario.
3. If you instead call `bin\code.cmd` the issue does not occur, as this results in VS Code being launched slightly differently. Inspect the batch file for the full details. Note that configuring Git to launch VS Code via this method works, but can be slower.
4. You can suppress the errors by setting the `ELECTRON_NO_ATTACH_CONSOLE` environment variable to `true`, but I'm unclear if there's broader side-effects to this approach.

The output is ultimately benign, but it is annoying, so would nonetheless be good to if not fix it, at least suppress it somehow.

**Comment by deepak1556** [comment]
Please use the following to workaround if the log is intrusive, this is on our radar to get the backend tested for compressed reports.

```
* Open the Command Palette.
* Run the Preferences: Configure Runtime Arguments command.
This command will open a argv.json file to configure runtime arguments. You might see some default arguments there already.
* "enable-crash-reporter":  false
* Restart VS Code.
```

**Comment by ralish** [comment]
@deepak1556 Unfortunately the above doesn't work for me, but going off your commit to {{main}} this will be fixed in the next release, so can just wait for that to land instead of spending more time on this.

**Comment by pkutaj** [comment]
What does work, though is the 4) suggestion from @ralish post, i.e. setting `ELECTRON_NO_ATTACH_CONSOLE` environment variable to `true`.  Just run 🠋 

```
[System.Environment]::SetEnvironmentVariable('ELECTRON_NO_ATTACH_CONSOLE', 'true', [System.EnvironmentVariableTarget]::User)
```

... I have not seen any downsides / side-effect.
