### ISSUE TITLE
Missing info from the "Recent Workspaces and Folders" section in the taskbar context menu

### ISSUE THREAD

**Issue by syagev** [microsoft/vscode#115898]
Version: 1.53.0 (user setup)
Commit: 8490d3dde47c57ba65ec40dd192d014fd2113496
Date: 2021-02-03T20:36:38.611Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Have remote workspaces in your "Open Recent" list, specifically remote Dev Container workspaces that were launched on a remote host (via SSH).

2. In the "File">"Open Recent" menu, as well as the "Recent" section in the "Welcome" page, the entry for the remote Dev Container workspace has all the relevant information - SSH username, host, and project root dir. This is extremely useful when you have similarly named projects on different Dev Containers and hosts.

![image](https://user-images.githubusercontent.com/5247438/107061617-1276a500-67e1-11eb-886b-12ad3e81e227.png)

![image](https://user-images.githubusercontent.com/5247438/107061568-04288900-67e1-11eb-8367-5bdc1c70f5a7.png)

3. However, in the context menu that shows up by right clicking VSCode in the task bar (which I find also very very useful) some of this info is missing - specifically the Dev Container name and project root dir, even when hovering over the item for the tooltip. Unfortunately this makes it impossible to choose the specific intended workspace from this menu.

![image](https://user-images.githubusercontent.com/5247438/107061735-2fab7380-67e1-11eb-9835-791807d004f9.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
@aeschli didn't you add support for remotes in dock?

**Comment by aeschli** [comment]
There's less space available in the Windows recent menu, so we just take the last segment of the recent menu entry. The last segment also contains the remote host `[...][`
https://github.com/microsoft/vscode/blob/1e8edfea6ed7660f582b752e1587abcf264c32ed/src/vs/platform/workspaces/electron-main/workspacesHistoryMainService.ts#L353

@bpasero Nothing special for remote here, the same problem is for local paths when there's more than one recent folder with the same base name.

I think the fix is to improve the description shown in the hover. It should be taken from the recent label, not the path. It will then  show the same info as seen in the [Recent list](https://user-images.githubusercontent.com/5247438/107061568-04288900-67e1-11eb-8367-5bdc1c70f5a7.png).

**Comment by bpasero** [comment]
@aeschli isn't that what we are doing already? `description` is the tooltip iirc:

https://github.com/microsoft/vscode/blob/ffe7654a9f7dc0847e149feb87c6a63530b8f672/src/vs/platform/workspaces/electron-main/workspacesHistoryMainService.ts#L355-L364

**Comment by aeschli** [comment]
The recent.label has a nicer formatted label as provided by the remote extension. So if available it should be used also for the description.

I pushed a change that uses the `recent.label` also in the description.
I simplifies the code if there's no `recent.label` available. We have no `LabelService` in the main so the label for remote URIs can't be better than the URI.
