### ISSUE TITLE
Markdown links that are indented 2 lines in a list are not highlighted

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#11589]
- VSCode Version: Code - Insiders 1.5.0-insider (06d85431730fe33beff7c56b5ef6f4514ad326ba, 2016-08-09T16:02:06.523Z)
- OS Version: Darwin x64 14.5.0

Interestingly it only happens on the second line after a list.

<img width="643" alt="screen shot 2016-09-06 at 7 41 55 am" src="https://cloud.githubusercontent.com/assets/2193314/18278011/5cd3bd9c-7405-11e6-80f7-5c91facc3173.png">

**Comment by mjbvz** [comment]
Fixed by https://github.com/Microsoft/vscode-textmate/pull/24 which we took into vscode with 966e89535b2127cdbc285534171575b0d5b2841a

![screen shot 2016-09-21 at 11 59 07 am](https://cloud.githubusercontent.com/assets/12821956/18724882/e16392b4-7ff2-11e6-8792-fde2c62881e5.png)

(odd colorization differences are being tracked by #12344)
