### ISSUE TITLE
Reliability improvement proposals for local echo

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#115949]
The typeahead/local echo implementation we have now is more complex than it needs to be and supports a smaller subset of functionality that it could. This is because, in order to validate predictions, we manually parse input character-by-character and see how to process it and whether we need to roll predictions back. 

mosh handles typeahead differently: they keep an "overlay" buffer that hold predictions and is separate from the buffer that is made up of data from the pty. This allows them to simply apply incoming data unchanged, and then validate data in the overlay versus that in the real buffer. If a character in the overlay is now present in the real buffer, remove it from the overlay. If it's different, just clear the overlay. This removes a ton of complexity that we have now to deal with rolling back and rolling forwards and tracking style changes.

It also means that we would get support for more complex scenarios, like powershell which rewrites the entire line on each character, for 'free' -- no additional complexity in our algorithm, that is. @TylerLeonhardt's been working on getting powershell working with our current approach and is ending up in a series of edge cases and rabbit holes.

**Comment by TylerLeonhardt** [comment]
After a ton of discussion, we landed on 2 possible solutions to this:

* Maintain a separate instance of xtermjs and apply incoming data to that in order to verify predictions. This is similar to the mosh proposal above but instead of a separate "buffer" it's a separate instance of xtermjs.
* splitting a single incoming data into chunks and using `writeSync` so you can check the buffer contents/coordinates before and after they are written

Originally I was going to attempt the first option but we've decided to postpone this work until after Daniel and Megan's work on pulling out xtermjs to a subprocess.

**Comment by Tyriar** [comment]
Additionally disabling predictions based on the class of the prediction (cursor move, cursor word move, alphanumeric, backspace, etc.), not just outright. Backspace may always fail but alpha would work, so we could just give up on backspace and just do alpha instead.

**Comment by Tyriar** [comment]
Merging into https://github.com/microsoft/vscode/issues/126209
