### ISSUE TITLE
"workbench.editor.decorations.badges": true ignored if "workbench.editor.tabSizing": "shrink"

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#115908]
On 1.53

Set this:
```
"workbench.editor.tabSizing": "shrink"
"workbench.editor.decorations.badges": true
```

The decoration badges do not show on the tabs.

I think this is a bug. If not, the description of `workbench.editor.decorations.badges` should state that it is incompatible with shrink tabsizing.

_Originally posted by @gjsjohnmurray in https://github.com/microsoft/vscode/issues/115858#issuecomment-773974376_

**Comment by bpasero** [comment]
I can reproduce.

**Comment by jrieken** [comment]
This seems to be an issue with the shrink style. The decorations are there but somehow hidden

**Comment by bpasero** [comment]
The issue here is that the tabs control chooses to draw a gradient with a `::after` rule to indicate that the tab name is not entirely visible. Unfortunately this rule collides with the one used for badges which also puts a `::after` rule at the same location and you can only have one.

I have moved this `::after` rule into the `.monaco-icon-label-container` container now and that seems to help for the decoration. However, I also need to add some `padding-right` because it looks like we explicitly disable padding here:

https://github.com/microsoft/vscode/blob/b5ccd30c95dbe8f6119382a1cd15da05449a76f6/src/vs/workbench/browser/parts/editor/media/titlecontrol.css#L33-L36

Result:

![image](https://user-images.githubusercontent.com/900690/108492100-0856ab00-72a5-11eb-90b5-d73dea5cba28.png)

**Comment by bpasero** [comment]
The only sort of "bug" is that I cannot get the gradient to draw after the label when the badge is there...
