### ISSUE TITLE
UX meeting agenda 04 September 2016

### ISSUE THREAD

**Issue by bgashler1** [Microsoft/vscode#11601]
- Simplify and standardize theme selection colors #11354 @Tyriar @sandy081
- Refactoring extensibility feedback
- Debugging sidebar remains open #1931

@Microsoft/vscode team, please let me know if there are other issues we should discuss.  We will meet 8:00am Redmond time (5:00pm in Zürich).  Thanks!

**Comment by isidorn** [comment]
Close button for horizontal panel #9638

**Comment by bgashler1** [comment]
# Notes

### Close button for horizontal panel
We didn't have everyone needed to to discuss the button specifically, so we'll address that next time.

On a related note, we did demo some designs on how to make it easy to toggle open and closed the horizontal panel as well as switch to different panels without needing to go to the View menu each time, which has been a friction point for many users.

Here are three ideas:

1) Plain status bar icons with notifications
![notify-02](https://cloud.githubusercontent.com/assets/11839736/18329469/643e11a0-7508-11e6-9554-1018696b2ab8.png)

2) Sub-activity bar (plus what it looks like to resize)
![03-animation_notify](https://cloud.githubusercontent.com/assets/11839736/18330057/691821c2-750b-11e6-8007-d8391260fdf7.gif)

3) Dedicated status bar area, plus only one icon for errors/warnings
![drawer_4_animation](https://cloud.githubusercontent.com/assets/11839736/18331315/c9261b76-7512-11e6-9302-989bb228ad2f.gif)


Discussion about the designs:

- Design 3 was the favorite.
- We should show icons at all times in the status bar for each horizontal panel, even if there are zero notifications present; this will be the way to toggle between panels (thus we can lose the extra toggle button and save more on space... [I updated the designs for this]).
- We should only show 1 icon in the status bar for "Problems", since there are not separate panels for "Errors" and "Warnings."  [I updated Design 3 with this]
- Perhaps we don't need the tabs in the panel, since the status bar is enough to switch (but it might help to leave them for textual discoverability reasons—we need to validate this).
- Ben suggested making the tray of special panel icons appear centered horizontally in the status bar, but we agreed this may not scale.

@kieferrm FYI we would like to add implementing one of these designs to the iteration plan as an exploration.  Any objections or questions?

Next Steps:

- Should we leave the text tabs inside the panel or just have one panel label?  And if we want the tabs, should we also have notifications next to them?
- @stevencl we need to figure out what the overflow behavior should be for the status bar: what happens to this and other things at small screen sizes and/or when too many things are in the status bar (say from an extension)?

### Theme selection/match colors

Syntax colorization can be quite variable for any particular part of a text file, therefore it's difficult to define theme selection/match highlight colors that can work well in all situations.

A seemingly simple solution would be to allow themes to adjust the foreground selection color (the color of the text).  This would allow, for example, a yellow highlight to be used even on syntax that is colored yellow—we could simply change its text color to something like black or yellow's complementary color: purple.  Engineering needs to investigate if this is possible first, since it could potentially slow performance, since we would have to manipulate both the text layer and the highlight layer, instead of just the highlight layer like we do today.

The other more encompassing issue is that colors in VS Code's editor need some work so that they are simpler, consistent and more legible.

Action items:
@bgashler1 will look at editor colors this iteration and see what we can do to standardize and simplify ours.  For example, do we need "Strong highlight," and if so, what can we do to disambiguate it from a selection (as it's confusing today).

@sandy081 please let us know what you find out as to whether styling the foreground color could be possible.  This will help us know what is possible to work with while we design a solution.


---
## Postponed
### Debugging sidebar remains open
We will wait for @stevencl and @chrisdias to be able to attend before discussing this, since they have a different perspective that we don't want to miss.

### Refactoring extensibility feedback
We didn't have the right people to demo this, so we'll postpone for now.

**Comment by octref** [comment]
Just to add some **very personal** opinions. 

For the horizontal panel, I like design 2 better, and I'd like to raise some concerns about adding things to status bar in design 3. Currently, nothing in the status bar is useful to me and I wish I could disable it to get it out of my way when I'm focused on coding.

- Line/Col - I don't care.
- Tab Size - I know what I'm using, and I don't need it.
- Utf-8 - I've never had problems with file encoding. If I do, I probably wouldn't deal with it file by file in VSCode.
- JSON - I know what type of file I'm editing by file suffix.

- Git part - This might be useful to other people who are more accustomed to GUI Git client, but I use CLI all the time so I don't need it.

And currently in the Dark+ theme, status bar commands most attention because of the bright blue with the highly-contrasted white text (whiter than the white code). It's like the red notification count on my iPhone screens, and it annoys me.

## Here are my suggestions:

1. Consider allowing users to selectively display items in the status bar, no matter if you are going for design 3 or not. Also consider adding option to hide status bar, if user finds everything there unimportant.

2. Reconsider the status bar and horizontal panel from an Information Architecture perspective. I'm coding. Build errors screw me up. I spend most day debugging. I constantly need to run commands. These actions are as important as which file I'm working on, or what code I'm going to commit. Currently only design 2 gives enough visual significance to these panels. Design 3 is mixing important things and unimportant things together by giving them the same visual significance. 

3. Currently it's hard to tell which sidebar I'm on. (Git/Explorer/Debug). One possible solution could be making the active icon's background color same as the sidebar's background. We could do the same for design 2.

## An actionable item:

Do a usage research about how people are using the status bar & how they feel toward the current design.

## Some random rants:

- The first time I opened VSCode I immediately looked for the way to remove/hide/change-the-color-of the status bar. After 30 minutes futile research I turned back to Atom.

![image](https://cloud.githubusercontent.com/assets/4033249/18339205/11971988-7553-11e6-977c-127795ebbe38.png)

- Would be cool if one day we upgrade Electron and have VSCode with [frameless window](https://github.com/electron/electron/blob/master/docs/api/frameless-window.md).

**Comment by bpasero** [comment]
@octref did you ever try View > Toggle Status Bar?

**Comment by octref** [comment]
@bpasero 
I must tried VSCode before it's added...Oh my god. Thank you.

**Comment by bgashler1** [comment]
Thanks for the suggestions @octref.  I like your rationale for liking Design 2 better.  By the way, you're not the only user who doesn't like the bright blue of the status bar.  We have that color to be consistent with Visual Studio, and we currently don't support the thumbing of the GUI at this time.

**Comment by Tyriar** [comment]
@octref @bgashler1 fyi this is what I use the status bar for personally:

- Viewing language type (to confirm I need to change it via command palette)
- Viewing tab/space type (to confirm I need to change it via command palette)
- Viewing column (for example when finding a row/col referenced by a log)
- Whether I'm in a debug session (orange vs blue), though I'd be fine with going off the button panel that pops up
- Extensions

The right side of the status bar is no use to me, I get most of that information from the prompt on my terminal though.
