### ISSUE TITLE
Extension API: workspace folders vs git repositories not consistent regarding symlinks

### ISSUE THREAD

**Issue by letmaik** [microsoft/vscode#116064]
- VSCode Version: 1.53.0
- OS Version: Ubuntu 18.04

The paths in `workspace.workspaceFolders` do not have their symlinks resolved.
The paths in the git extension's `API.repositories` do have their symlinks resolved.
This seems inconsistent and makes life hard if you want to easily check the relation between the two paths.

It seems the git extension itself gets confused by this and shows the full path in the SCM view if the repo/workspace folder is in a symlinked folder. Notably, the file watcher also doesn't resolve symlinks.

I think the paths returned from the git extension should not have their symlinks resolved so that they can be easily compared with all the other paths from vs code.

**Comment by lszomoru** [comment]
@letmaik, thank you very much for reporting this issue and apologies for not getting back to you on this. The git extension  calls `git.exe` (ex: `git rev-parse --show-toplevel`) to determine the exact path of a repository. We are doing this so that we can handle scenarios in which the folder/workspace has been opened with incorrect casing of the path. At the moment `git rev-parse` resolves symbolic links and as far as I know, there are not plans to change this behaviour. So the git extension is limited to using the real path as the repository root. 

I am not really sure what can be done here given the current constrains but I am opened for suggestions. We do have an issue to better handle repositories with symbolic links but at the moment this work has not been planned - https://github.com/microsoft/vscode/issues/5970.
