### ISSUE TITLE
smoke tests time out

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#116156]
5 tests time out and [break the build](https://monacotools.visualstudio.com/DefaultCollection/Monaco/_build/results?buildId=103957&view=logs&j=3792f238-f35e-5f82-0dbc-272432d9a0fb&t=2912d057-d0f3-5270-1d09-777eeaba2eea&l=135)

commented them out [here](https://github.com/microsoft/vscode/commit/29844a0baf309a3fb4d07a8a63f1b61c39085622)

**Comment by roblourens** [comment]
- @meganrogge you identified @sandy081's commits https://github.com/microsoft/vscode/commit/15616c186929f1095992d49dcc7a753428c4ff61 and https://github.com/microsoft/vscode/commit/3334b1534c9a83a4894d7108903dbfd8eed6110d as likely related, so we can assign him instead of Joao
- You can use `.skip` on the tests instead of commenting them out, this is cleaner and will keep the test name in the output, I changed this in 0829608afbf699107ed25a64178f3b676e89c1fb
- We talked offline about how we should try to understand more before disabling the tests. I looked into it a little more and found that I couldn't repro the failures locally, which is odd. I manually checked some of the test scenarios and didn't see any issues, so I think it's fine to leave the tests disabled for the next release and investigate tomorrow.

**Comment by roblourens** [comment]
Oh hold on I think these first failed with https://github.com/microsoft/vscode/commit/7f1d17baca264e8e6b04bba22e3cc29015f40dd6 so you may be on the hook after all @joaomoreno

**Comment by sandy081** [comment]
/duplicate

This is related to https://github.com/microsoft/vscode/issues/116152. Hence making this duplicate.
