### ISSUE TITLE
Search and replace for optional chaining string

### ISSUE THREAD

**Issue by garymcm-r** [microsoft/vscode#116192]
With optional chaining, for an expression like `a?.b?.c`, when I want to search for everywhere I refer to `a.b.c` I must use regex like `a\??.b\??.c`. It would really helpful to have the searches be insensitive to paths with the optional chaining operator.

**Comment by gjsjohnmurray** [comment]
I don't think this is feasible. VS Code's search and replace needs to be language-agnostic.

**Comment by IllusionMH** [comment]
When you have "Use Regular Expression" enabled for search then select `a?.b?.c` and use <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>F</kbd> - field will be seeded with properly escaped regexp `a\?\.b\?\.c` (also not that your requested example lacks escapes for dots while VS Code have them).

It's up to you if you want to make `\?` optional for your use cases. For other users it would be strange to get RegExp that will match results different from their selection because of appeared optionality.

**Comment by JacksonKearl** [comment]
You can create an extension with a command to execute the `workbench.action.findInFiles` command with the `query` argument set to some value derived from your selection.
