### ISSUE TITLE
Allow to create new empty notebook from the command line

### ISSUE THREAD

**Issue by jzuhone** [microsoft/vscode#116259]
It would be great to be able to create an empty notebook from the command line, e.g.:

```
code stuff.ipynb
```

which would open a new Jupyter notebook in the same way that "Create New Blank Jupyter Notebook" does from the Command Palette. Currently, when you do this it only opens a blank text file.

**Comment by jrieken** [comment]
Adding @lramos15 who is looking into this for custom editors et al

**Comment by lramos15** [comment]
This isn't really a feature request. If the user has their editor associations set correctly then the untitled file will be passed to the custom editor / notebook. It is up to that specific editor what to do then. This workflow just works for the Hex Editor for example as I have handled untitled file URIs. Once https://github.com/microsoft/vscode/issues/115631 gets finalized there will be a better implementation path for all notebooks and custom editors to handle untitled files. Whether or not we want to add an additional command line argument to specify the editor type via an editor id is another thing that could be discussed @jrieken. That way the user wouldn't need their editor associations set correctly.

**Comment by jzuhone** [comment]
@lramos15

I don't understand your comment. The editor associations _are_ set the way as you describe and what happens is that you attempt to open the (previously nonexistent) file with the .ipynb suffix and it opens the file, but it doesn't automatically create a notebook with a single empty cell to start off with. It just creates a blank text file. And if you try to save, it's still just a text file.

**Comment by lramos15** [comment]
Ah thank you for the clarification. This is actually a notebook bug with notebooks not respecting editor associations for untitled files. This feature works for custom editors just not notebooks.

**Comment by jrieken** [comment]
This might be another thing for the custom editor drama/debt. I don't think notebook should be doing anything special for this and it should be handling with the "normal" code for open a file with the notebook editor type

**Comment by jrieken** [comment]
@lramos15 Is there anything I need to do here or do notebooks get this for free?

**Comment by lramos15** [comment]
@jrieken In theory once all the debt is worked out notebooks should receive this for free. If not I can take care of ensuring it works for both.

**Comment by bpasero** [comment]
I think supporting overrides in `openEditors` too makes sense to me. I don't think code should be duplicated but reused.

**Comment by lramos15** [comment]
After discussion with @jrieken this seems to be blocked by the amount of open editor debt that still exists between custom editors and notebooks. Ideally we want to unify those and remove a lot of the complexity as right now it's like 100+ lines just for notebooks to figure out what input they want to use and there are some issues in that logic preventing this from moving forward.

**Comment by lramos15** [comment]
@bpasero I think this is actually blocked on the fact that we do not await the extension host activation and therefore none of the contributions are registered at this time. That's the conclusion @rebornix and I came to, but I'm not sure if you have any suggestions or ideas.

**Comment by bpasero** [comment]
We do not really need to await the extension host activation but rather the contributed custom editors, no? Isn't it sufficient to know which extension contributes a pattern for custom editor to do the right thing? Do we need to wait for extension activation?

**Comment by jrieken** [comment]
> @bpasero I think this is actually blocked on the fact that we do not await the extension host activation and therefore none of the contributions are registered at this time.

A common workaround/trick is to remember that there was an extension that handles this kind of editor and than optimistically proceed with that assumption

**Comment by lramos15** [comment]
@bpasero The code you gave me seemed to do the trick. Feel free to check the commit if it's the wrong place for it.

**Comment by bpasero** [comment]
@lramos15 I think we cannot ship that change though, let me try to explain: we are typically very concerned how fast VSCode opens it's window, showing a text editor and a blinking cursor to the user, we call that the critical startup path and all our performance measurements measure against that goal because it is our goal to offer the fastest time from starting VSCode to blinking cursor in the editor.

Now, `openEditors` is on that startup path:

https://github.com/microsoft/vscode/blob/e1727abb4114388c7b126f22348b4c4149cf9a2b/src/vs/workbench/browser/layout.ts#L700-L700

Looking at the perf output (Startup Performance Editor), it seems like the extensions registration code triggers a lot later than the editor restore phase:

![image](https://user-images.githubusercontent.com/900690/115663377-aec03a80-a340-11eb-8d68-537111df5803.png)

That means with this change, the `code/didRestoreEditors` would only now fire after `code/didLoadExtensions`.

@jrieken please correct me if I am wrong, but I think the `whenInstalledExtensionsRegistered` only fires from here:

https://github.com/microsoft/vscode/blob/73c85159e72069f69db46fad178f37b5d015f5bc/src/vs/workbench/services/extensions/common/abstractExtensionService.ts#L431-L431

**Comment by bpasero** [comment]
I think this is confirmed now by the perf bot result from today:

![image](https://user-images.githubusercontent.com/900690/115684939-0fa73d00-a358-11eb-9656-8a12a62a205d.png)

**Comment by lramos15** [comment]
I've reverted this and will try @jrieken's approach of caching if there was an override for a specific resource type and then only waiting on the ext host for registrations in that case.

**Comment by jzuhone** [comment]
I tried this in the insiders build and it works! Thanks to all of you!
