### ISSUE TITLE
While waiting for a fix, a downgrade makes vscode functional again.

### ISSUE THREAD

**Issue by NevilleDNZ** [microsoft/vscode#116404]
Thank you for the workaround... 

It's important the know Centos8 has an EOL in [2021](https://phoenixnap.com/kb/centos-8-early-eol-in-2021).

Where as Centos7 has an EOL June 30th, [2024](https://wiki.centos.org/About/Product).

Similarly: also had to downgrade twice to get a working VSCode on Centos7

 # yum downgrade code.x86_64
Removed:  code.x86_64 0:1.53.1-1612827854.el7                                                                                               
Installed:  code.x86_64 0:1.53.0-1612368438.el7    
                                                                                           
 # yum downgrade code.x86_64
Removed:  code.x86_64 0:1.53.0-1612368438.el7                                                                                               
Installed:  code.x86_64 0:1.52.1-1608137084.el7 

_Originally posted by @Luisss in https://github.com/microsoft/vscode/issues/115784#issuecomment-777027983_

**Comment by deepak1556** [comment]
As mentioned here `1.53` and higher have dropped support for CentOS 7 due to runtime dependency https://github.com/microsoft/vscode/issues/115784#issuecomment-775364356 , the workarounds are also mentioned in the issue.

* Launch with a newer gcc toolchain on your system if possible
* Using snap package

We don't have plans to support CentOS7. Sorry about this change!

/duplicate https://github.com/microsoft/vscode/issues/115784
