### ISSUE TITLE
Wrong Italian translation on Undo create new folder

### ISSUE THREAD

**Issue by adrianptr** [microsoft/vscode#116548]
Issue Type: <b>Translation Bug</b>

Steps to reproduce:
- Create new folder with the button in top of File Explorer;
- Press Ctrl + Z to Undo the operation;

Result:
The confirm dialog show two "Annulla" buttons. In english we have "Cancel" and "Undo".

Proposal:
Translate "Undo" with "Elimina".

Screenshots:
![Schermata da 2021-02-12 14-02-12](https://user-images.githubusercontent.com/23382033/107772087-02f4e000-6d3c-11eb-8146-6b6566db1d9f.png)

![Schermata da 2021-02-12 14-01-24](https://user-images.githubusercontent.com/23382033/107772105-09835780-6d3c-11eb-957e-2a7d825cab41.png)

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:44.518Z)
OS version: Linux x64 5.4.0-65-generic snap (Elementary OS 5.1.7 Hera)

<details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-it|MS-|1.53.2
hexeditor|ms-|1.4.0

(1 theme extensions excluded)

</details>

**Comment by kowalski7cc** [comment]
Yeah, even when I want to undo a rename it's not really clear.
Undo could also be "ripristina". 
I'd keep "annulla" for the "cancel" button instead of "cancella" because the Italian translation means both abort and delete (mostly) so in this case, it could lead this too to confusion.

![image](https://user-images.githubusercontent.com/5065094/108910744-9379cd00-7626-11eb-92a3-1ad27925de01.png)

**Comment by v-mholloway** [comment]
bug opened [117239](https://dev.azure.com/GlobalCollaborationService/Global%20Collaboration%20Service%20Project/_workitems/edit/117239)

**Comment by v-mholloway** [comment]
bug 117239 resolved - closing
