### ISSUE TITLE
shellscript highlighting broken after <<< string with complex quoting

### ISSUE THREAD

**Issue by dchsueh** [microsoft/vscode#116509]
- VS Code Version: 1.50.0
- OS Version: Ubuntu 20.04.2 LTS

Steps to Reproduce:

create/edit bash script - this example parses the centos version numbers
```
#!/bin/bash
cat /etc/centos-release
IFS='.' read centos_major_version centos_minor_version centos_release_version <<< `grep -o '[0-9]\+\.[0-9]\+\.[0-9]\+' /etc/centos-release`
cat /etc/centos-release
```
every line after the read <<< line is highlighted incorrectly

if the last backquote on the read <<< line is removed, highlighting is correct on subsequent lines

(I've tried the same script with atom-1.54.0 on win10-2004 and highlighting is correct.)

Does this issue occur when all extensions are disabled?: Yes

**Comment by dchsueh** [comment]
![vscode-highlight](https://user-images.githubusercontent.com/2845811/107715535-7c89c100-6c9d-11eb-8f93-5c491a2213c1.png)
![atom-highlight](https://user-images.githubusercontent.com/2845811/107715578-97f4cc00-6c9d-11eb-9fbb-deaa425a7169.png)

**Comment by alexr00** [comment]
We get our shell script grammar from https://github.com/atom/language-shellscript, but they are no longer maintaining their grammar.

https://github.com/microsoft/vscode/issues/77675 is a feature request for VS Code to use a different shell script grammar. I'm closing this issue in favor of the other. If we adopt a new shell script grammar, then we should check if this bug is fixed.
