### ISSUE TITLE
package is invalid (checksum did not verify)

### ISSUE THREAD

**Issue by pedronfigueiredo** [microsoft/vscode#116557]
- VS Code Version: 1.53.2
- OS Version: macOS 11.2

Steps to Reproduce:

1. `$ brew install visual-studio-code`
2.
```
Error: SHA256 mismatch
Expected: acc708669db0d6b6057883283162d5cfae909968fd6970291a96a80c572eedea
  Actual: 0fceea3d2bdb390b7e91bba932b44e29598feaaa0a7f2247a38dc10a0296e5cf
```

or

1. Download the package via the website
2. `pkgutil --check-signature ~/Downloads/Visual\ Studio\ Code.app`
3. `Status: package is invalid (checksum did not verify)`

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
I'd say you should file this in https://github.com/Homebrew/brew instead, since they ship that.

BTW, I get `acc708669db0d6b6057883283162d5cfae909968fd6970291a96a80c572eedea`, so there must be something wrong in your network which modifies the file. I suggest reaching out to Homebrew and also Stack Overflow.
