### ISSUE TITLE
Codelenses not appearing during onDidChangeCodeLenses event

### ISSUE THREAD

**Issue by pflannery** [microsoft/vscode#116510]
- VS Code Version: 1.53.2
- OS Version: Windows 10

Steps to Reproduce:

1. Install VersionLens extension 
2. Ensure the V icon is off and no version info is shown.
3. Click the V Icon in the tool bar to show versions
2. Notice that the version info does not render unless you scroll or click

The ```provideCodeLenses``` function is called and succeeds but ```resolveCodeLens``` doesnt get executed.
This only occurs when using the ```onDidChangeCodeLenses``` event. 
If the V icon button is on and you reopen the document the codelenses are rendered correctly,

![image](https://user-images.githubusercontent.com/1727302/107715756-e15a1100-6cc7-11eb-82da-b372003b8663.png)

This used to work but Im not sure which previous version of vscode that was.

**Comment by pflannery** [comment]
V Icon line of code is [here](https://gitlab.com/versionlens/vscode-versionlens/-/blob/master/src/presentation.extension/src/commands/iconCommands.ts#L46)

onDidChangeCodeLenses event is fired [here](https://gitlab.com/versionlens/vscode-versionlens/-/blob/master/src/presentation.extension/src/lenses/versionLensProvider.ts#L69)

**Comment by gjsjohnmurray** [comment]
@pflannery you didn't say, but maybe you are the author of that extension. If so, I suggest you try to create a simple repro by forking https://github.com/microsoft/vscode-extension-samples, creating a branch, then amending codelens-sample to illustrate the problem. In my experience this strategy is more likely to get the problem investigated and hopefully resolved, rather than someone having to use the source of your extension.
