### ISSUE TITLE
file package name and directory inconsistencies， delete import 

### ISSUE THREAD

**Issue by rentiansheng** [Microsoft/vscode#11662]
- VSCode Version:1.4.0
- OS Version: OS X EI Capitan

Steps to Reproduce:

1.  create a new folder called test, create tow file called t1.go,t2.go
     t1.go file  content " package t1",  t2.go  file content "package t2"
2.  import test ,  use  package t1.var ,  save file vs code delete  import test.

**Comment by ramya-rao-a** [comment]
@rentiansheng Can you be more clear about what the issue here is?

What I could gather was that you 

- are using Go language
- created 2 packages "t1" and "t2" in files "t1.go" and "t2.go" respectively under folder "test"
- you did `import "test"` in another go file and used a function/variable from the package "t1"

I don't follow the rest of your steps

**Comment by rentiansheng** [comment]
I'm very sorry,  Yesterday, Error with my vs code configuration  environment, Thanks ver
