### ISSUE TITLE
Set user agent for Marketplace icon downloading

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#11673]
> Request for: Microsoft.VisualStudio.Services.Icons.Default seems to have useragent of type browser(safari etc for mac and similar for windows)

See [`session.setUserAgent`](https://github.com/electron/electron/blob/master/docs/api/session.md#sessetuseragentuseragent-acceptlanguages)

**Comment by bpasero** [comment]
Have to revert this because we have code in browser.ts that checks for very specific browsers in the user agent to enable or disable features.

I noticed that the user agent already includes our product name so that servers are able to find out if requests are being made from us or not:

`"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Code-Insiders/1.6.0-insider Chrome/52.0.2743.82 Electron/1.3.7 Safari/537.36"`

**Comment by joaomoreno** [comment]
Notified Marketplace guys.
