### ISSUE TITLE
Consider exposing WebUSB functionality in extensions

### ISSUE THREAD

**Issue by thegecko** [microsoft/vscode#116761]
I'd be interested to understand whether there is appetite to add control of enabling [WebUSB](https://wicg.github.io/webusb/) access in web extensions and webviews:

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Feature-Policy/usb

With VSCode going online through projects such as codespaces, there are strong use cases for accessing broader Web APIs and in this case, the ability to interact with devices attached to the user's machine.
This could enable scenarios such as debugging of connected devices, which is already possible in the desktop version of VSCode.

I'd be happy to implement the feature, but would be keen to understand whether it would be accepted.

**Comment by mjbvz** [comment]
We'd consider this policies on a case by case basis

**Comment by thegecko** [comment]
> We'd consider this policies on a case by case basis

Thanks, I've reworded the title and description of this request to focus on interest in exposing WebUSB in webviews.

**Comment by mjbvz** [comment]
Have you tested to see if this would work on the web? Webview contents are run inside iframes from a different origin than the main editor page. Even if we enable the policy on the iframe itself, I don't know that webUSB would work

**Comment by thegecko** [comment]
> Have you tested to see if this would work on the web? ...You can try this using a local build of VS Code

Many thanks for the pointers. I have tested this change locally as you describe and can confirm that updating the `allow` permissions as follows:

```typescript
element.setAttribute('allow', 'clipboard-read; clipboard-write; usb;');
```

Successfully enables webviews to invoke `WebUSB` features:

<img width="961" alt="Screenshot 2021-02-19 at 13 40 55" src="https://user-images.githubusercontent.com/61341/108511939-79ec2480-72b8-11eb-8652-907dbd6f5f9e.png">

I assume the feature to be implemented would be to control this setting from the `webviewView.webview.options` object?

**Comment by thegecko** [comment]
Perhaps `WebHID` and `WebSerial` should also be considered?

**Comment by 0Grit** [comment]
Yes please. WebHID, WebSerial would be excellent additions.

These are the final pieces of the puzzle to open up embedded development to the masses.

**Comment by 0Grit** [comment]
> It seems you can achieve it via web extensions, see [gitpod-io/gitpod#5814 (comment)](https://github.com/gitpod-io/gitpod/issues/5814#issuecomment-937526878)

https://github.com/gitpod-io/gitpod/issues/5814#issuecomment-938401052

**Comment by mjbvz** [comment]
#151795 introduces an experimental command that you can use on web to request USB access. This lets your extension code use the webUSB apis directly:

Here's how it works:

1. To get permissions to access a usb device ( this is `usb.requestDevice()`) your extension must call this command instead of trying to call `navigator.usb.requestDevice` directly

    This is needed because your extension is running in a worker thread which cannot request permissions itself

2. After the user selects some devices and finished the permissions flow, your extension code can then call `navigator.usb.getDevices` to access the selected devices

This command is only enabled on web and only works in Chrome/Edge. Please give it a try and let us know if you have any feedback

---

The new command relies on [Chrome's permission delegation feature](https://chromestatus.com/feature/5670617353289728). While implementing it, I also realized that permission delegation makes enabling webUSB inside of our webviews too risky without a lot more thought.

The root problem is that once one iframe (webview) on a page request usb access, all the other usb enable iframes embedded into that page can also access that device without showing any prompts. It also means that if our top level page gets access to a usb device, all usb enabled iframes on the page can then also access that device. Instead we want all webviews to have to request permissions individually and then only be able to access their own pool of devices

I've opened [a chromium issue](https://bugs.chromium.org/p/chromium/issues/detail?id=1335989) about this behavior

**Comment by thegecko** [comment]
Great news we have some progress on this!

I'll try it when I find some spare cycles, but have some initial questions:

- I assume further updates to this would include the ability to specify the filters so the developer can restrict devices being requested to those of interest?
- Using this model, how can a developer know which device the user selected? In a scenario where multiple devices are connected, it's common to select or highlight the one just requested

**Comment by thegecko** [comment]
Both of my concerns have been addressed in https://github.com/microsoft/vscode/pull/152257 👍

**Comment by thegecko** [comment]
Experimental support has now been added, I believe this issue can be closed.

**Comment by thegecko** [comment]
The Web-* interfaces are only enabled in the extensionHost web worker, so I wouldn't expect the navigator access to work directly in webviews.

You should be able to access devices in the normal extension code, I'll try to find some time to create a demo.

**Comment by thegecko** [comment]
BTW @connor4312 how are you testing on insiders.vscode.dev? it seems [the recommended approach](https://code.visualstudio.com/api/extension-guides/web-extensions#test-your-web-extension-in-on-vscode.dev) is not currently possible due to the [localtunnel server being unavailable](https://github.com/localtunnel/localtunnel/issues/503).

**Comment by thegecko** [comment]
Please see this repo for a demo web extension which can request device authorisation through a webview and also list authorised devices:

https://github.com/thegecko/webusb-web-extension

**Comment by connor4312** [comment]
The only reason localtunnel.me was used was to provide the extension over https, which I do locally with the [serve](https://www.npmjs.com/package/serve) CLI and a self-signed cert I made with [mkcert](https://github.com/FiloSottile/mkcert).
