### ISSUE TITLE
Consider listening for document close for tasks that have a problem matcher that applies only to closed documents

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#116760]
![image](https://user-images.githubusercontent.com/900690/108048616-8a499880-7047-11eb-8bcc-3c62dff24ec7.png)

**Comment by sandy081** [comment]
Not sure who shall own this, it seems corresponding task is not creating the diagnostics

**Comment by alexr00** [comment]
I will take a look.

**Comment by alexr00** [comment]
@bpasero I'm not able to repro this. Tested with both desktop and in web with a Codespace. My steps:

1. Open microsoft/vscode.
2. Make an edit in a file that will cause a compile error.
3. Close the file. This ensures that any errors that follow will come from the build task, not from the typescript extension.
4. Run the default build task.
5. See error show in problem view and in the status bar. ✔️ 

Is it possible that you had the file open, had the error, then closed the file? The tasks system has always had the behavior that for typescript that will cause the error to go away until there's a file change that causes the build task to print the error again. This is because the typescript extension and the problem matcher for our build task use the same error source to prevent duplicate errors.

**Comment by bpasero** [comment]
> Is it possible that you had the file open, had the error, then closed the file? The tasks system has always had the behavior that for typescript that will cause the error to go away until there's a file change that causes the build task to print the error again. This is because the typescript extension and the problem matcher for our build task use the same error source to prevent duplicate errors.

Yeah possibly. The reason this frustrated me is that I had pushed changes to our `master` branch that included compile errors. I typically expect an error from the git commit whenever I have compile errors and wasn't sure why I did not get it here this time.

**Comment by alexr00** [comment]
If you have `"typescript.validate.enable": true` (default), then this is unavoidable, since the problems from the task will conflict with the problems from typescript. You can set that setting to false, then change the build task to show errors for `"allDocuments"` instead of `"closedDocuments"`. Or, we can decide that we are happy to have errors get duplicated (once from the task, once from typescript). Typescript's errors only come from the open files, which is why we have this issue in the first place.

**Comment by alexr00** [comment]
I suppose the tasks system could listen for file changes then re-apply all of the last problems.
