### ISSUE TITLE
Commenting code is not all ways working

### ISSUE THREAD

**Issue by Improvingdev** [microsoft/vscode#116814]
- VS Code Version: 1.53.2
- OS Version: Ubuntu 20.04

Steps to Reproduce:

1. Try commenting some lines
2.

Does this issue occur when all extensions are disabled?: Yes/No
Yes
![Screenshot from 2021-02-17 00-46-49](https://user-images.githubusercontent.com/54870069/108132545-ac7cfe00-70bb-11eb-9b6d-a56adbe1bb40.png)
# Comparison of the same codebase in Atom and VS code
![Screenshot from 2021-02-17 00-55-22](https://user-images.githubusercontent.com/54870069/108132616-d3d3cb00-70bb-11eb-9d48-e32fefaf4ed7.png)

**Comment by mjbvz** [comment]
Does this reproduce with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by IllusionMH** [comment]
`//` looks like incorrect comment in JSX. Even Babel parses it as `'//'`  instead of comment [Playground example](https://babeljs.io/repl/#?browsers=ie%2011&build=&builtIns=false&spec=false&loose=false&code_lz=PTAEAEEMBtoewO4BECmBjakBOKBiBLFaAEwGcAofAWwAc4sAXUAJRUjSYDMs4rQByHOwb8A3OXIoAHnUahiKTpACu0LsoB2HfHA0AKAJSgA3uQCQOBsqwbQe8qEdOAPAEUEKAHwOnvkKGdSGkgNTwBHD2dgIJDvX0co9y8fXwNxAF8JaVl1LQYdWwBBQxNzS2tbe3iApLjqk1BgACpA4NCIlCiY0KawTOrEjzrUjKA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact&prettier=false&targets=&version=7.12.15&externalPlugins=)

Built-in TS should provide valid `{/* ... */}` comments.

Atom actually looks wrong here.

**Comment by mjbvz** [comment]
Good point @IllusionMH! Yes this is expected then

The normal line comment command should insert `{* *}` style comments. If it does not, it is possible an extension is causing problems

**Comment by Improvingdev** [comment]
> `//` looks like incorrect comment in JSX. Even Babel parses it as `'//'`(string) instead of comment [Playground example](https://babeljs.io/repl/#?browsers=ie%2011&build=&builtIns=false&spec=false&loose=false&code_lz=PTAEAEEMBtoewO4BECmBjakBOKBiBLFaAEwGcAofAWwAc4sAXUAJRUjSYDMs4rQByHOwb8A3OXIoAHnUahiKTpACu0LsoB2HfHA0AKAJSgA3uQCQOBsqwbQe8qEdOAPAEUEKAHwOnvkKGdSGkgNTwBHD2dgIJDvX0co9y8fXwNxAF8JaVl1LQYdWwBBQxNzS2tbe3iApLjqk1BgACpA4NCIlCiY0KawTOrEjzrUjKA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact&prettier=false&targets=&version=7.12.15&externalPlugins=)
> 
> Built-in TS should provide valid `{/* ... */}` comments.
> 
> Atom actually looks wrong here.

Thanks
