### ISSUE TITLE
TextEditor.edit / WorkspaceEdit.applyEdit do not resolve immediately

### ISSUE THREAD

**Issue by Gregoor** [microsoft/vscode#116945]
- VS Code Version: 1.53.2
- OS Version: macOS 11.1

Steps to Reproduce:

When creating an extension that uses either `TextEditor.edit` or `WorkspaceEdit.applyEdit` to make changes to a document, the returned promise does not resolve immediately after the change was applied. Thus the following code, which is supposed to set the selection to the appropriate position after a change was made, does not work as expected. Namely a keystroke can happen in-between the edit having been made and the new selection being set. Thus the code is changed in the wrong place.

```typescript
const didEdit = await editor.edit(
  (builder) => {
    builder.replace(
      new vscode.Range(0, 0, document.lineCount, 0),
      newSource
    );
  },
  { undoStopAfter: true, undoStopBefore: false }
);
if (didEdit) {
  const position = document.positionAt(newOffset);
  editor.selection = new vscode.Selection(position, position);
}
```

**Comment by jrieken** [comment]
> Namely a keystroke can happen in-between the edit having been made and the new selection being set.

Yes, that can happen. The edit/applyEdit functions resolve their promises as soon as they are done but while the reply is send to the extension host process (which is async by its nature) anything can happen. We have no timing guarantee for how long the reply to extension host will take and we do not block user interactions (like keystrokes) just because an extension is planning to do something. Tho, we do guarantee that the extension host (eventually) receives the new editor selection. Also, know that you can insert a snippet (via the editor) which allows you to place the cursor within the same operation

**Comment by Gregoor** [comment]
Thanks for the swift reply, that does make total sense. Snippets do seem like the closest thing I need, to put editing and selection change into a single "transaction". This is what I'm currently thinking of doing (though it does not work as expected yet):
```typescript
await editor.insertSnippet(
  new vscode.SnippetString(
    newCode.slice(0, newOffset) +
      "$0" +
      newCode.slice(newOffset)
  ),
  new vscode.Range(0, 0, document.lineCount, 0),
);
```

It does feel like I'm abusing the API a little here, but I imagine the larger sin is my replacing of the whole document anyway (which is an unfortunate necessity), so first things first.

Is there some level of interest in an API that allows selection changes to be bundled with editing in a single transaction, outside of snippets? The edit-builder would seem like a good fit for such an API.
