### ISSUE TITLE
Webviews incorrectly positioned when editors are scrolled horizontally

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#116946]
* small/narrow window
* open two _webview_ editors
* :bug: you can horizontally scroll the editors/headers

https://user-images.githubusercontent.com/1794099/108362852-89a23500-71f4-11eb-9c8c-862dd741a670.mov

**Comment by joaomoreno** [comment]
What a fantastic feature!

**Comment by joaomoreno** [comment]
This is actually webview related, since text editors work as expected:

![recording](https://user-images.githubusercontent.com/22350/109024141-491e3d80-7672-11eb-962a-38ed3c8ed58e.gif)

**Comment by joaomoreno** [comment]
Maybe @mjbvz knows why these webviews aren't moving when everything scrolls left?

**Comment by joaomoreno** [comment]
Oh wow, I had no idea:

![image](https://user-images.githubusercontent.com/22350/109024516-b500a600-7672-11eb-839c-9e0e92f0fcef.png)

@mjbvz Let me know what needs to be pinged for a relayout here.

**Comment by mjbvz** [comment]
Same root causes  as #110450

We'd need to be updated whenever the editor element's position on the screen changes. We may be able to use `IntersectionObserver` for this

In addition, we'd need to figure out the visible part to the editor element. Because webviews must be at the top level of the dom (in order to avoid being reparented), they will not be properly cropped if an editor is half on the screen and half hidden

**Comment by joaomoreno** [comment]
> We'd need to be updated whenever the editor element's position on the screen changes. We may be able to use IntersectionObserver for this

Where's _we_? No need for observers since it all happens in JS, we know exactly where the scroll happens, we just need to wire it up.

> In addition, we'd need to figure out the visible part to the editor element.

Yeah that's trickier!

**Comment by mjbvz** [comment]
The webview code needs to know where to absolutely position the webview. Here's the code that does this:

https://github.com/microsoft/vscode/blob/2e1166cb0c204c048de89eab009aaa8dec616ef2/src/vs/workbench/contrib/webview/browser/dynamicWebviewEditorOverlay.ts#L126

You can look through the codebase to see all the places where `layoutWebviewOverElement` is called today

**Comment by mjbvz** [comment]
@joaomoreno Can you suggest how I can hook into scrolling the editor area?

I think the fix here would be very similar to https://github.com/microsoft/vscode/commit/88c1322a82a2bdf3fe7e5543684b5a36251c87b7 but I can't track down where the scroll events are fired in this case

**Comment by joaomoreno** [comment]
This is the one:

https://github.com/microsoft/vscode/blob/dff33d73244acced865a2643a62126409cb541a7/src/vs/base/browser/ui/splitview/splitview.ts/#L240-L241

But you've seen this, since it's what eventually gets you here:

https://github.com/microsoft/vscode/blob/dff33d73244acced865a2643a62126409cb541a7/src/vs/base/browser/ui/splitview/splitview.ts/#L240-L241

But that is only at the splitview level. Since the grid is a tree of spltiviews, we probably should join all those splitviews' `onScroll` events into a global grid `onScroll` event, which would be the one you could listen to. I've done that here: https://github.com/microsoft/vscode/commit/0e3459b0b9facc5e7a1e95903955f870bc5a532c#diff-ffad104855d5ea285f8b470156736e7325b8892ae4336970a74b8bc9e8110803R215

So you now have that event as in `grid.onDidScroll`. I suggest to debounce it just a bit, cause it may fire many many times!

**Comment by mjbvz** [comment]
Note for testing: this should be fully fixed for webviews but notebooks have may still draw over the side bars when scrolling: #150490

**Comment by sandy081** [comment]
@mjbvz You are right that Notebooks are drawing over side bars as below. Is there an issue open for tracking this?

![image](https://user-images.githubusercontent.com/10746682/171836630-4a9ec745-86a2-4759-be08-7594d7dc00aa.png)
