### ISSUE TITLE
Throwing custom exceptions from contributed command execution shows cryptic error popup

### ISSUE THREAD

**Issue by ganni** [microsoft/vscode#116932]
- VS Code Version: 1.53.2
- OS Version: MacOS 11.2

Hi guys, 

Before `1.53`, throwing exception with custom error message used to show up as error message popup by default. However with new update it shows up some cryptic error message instead. 
`Running the contributed command: '_vscode_delegate_cmd_klan2ooe' failed.`

![image](https://user-images.githubusercontent.com/764750/108335292-1f9a8780-7216-11eb-9cac-c13484a988f9.png)

Is this new change by design? or a bug? 

Steps to Reproduce:

1. Throw exception (with custom error message) from any contributed command.
```JavaScript
throw new Error("Custom error message");
```
2. It now shows cryptic error message. 
It used to show the custom error message that I've provided with thrown exception. 
![image](https://user-images.githubusercontent.com/764750/108334100-f3cad200-7214-11eb-9013-fa6d156283a5.png)

Does this issue occur when all extensions are disabled?: N/a

Thank you.

**Comment by jrieken** [comment]
> Is this new change by design? or a bug?

This is not new and by design. The "cryptic" message is stand-in command identifier that we generate whenever the UI should execute an extension command that cannot be send to the renderer process. That's due to non primitive arguments being passed. So, instead of sending  complex arguments back and forth (which costs and likely breaks them), we keep the actual command and its arguments cached and invoke them via such indirection commands. 

Tho, I do agree the error message isn't very pretty but that actually hard to control at that level. What is your expectation? Do you want your error to show? Your command id to show? How do you trigger that command?

**Comment by ganni** [comment]
Well, it used to just show my custom error message that I passed in `new Error('custom message')`. 

I would like it if it kept the same behavior.

**Comment by hyangah** [comment]
In our case (#116953), the command is implemented in the language server, and triggered by user clicking a codelens created by the language server. The language server provides the error details.
 
Ideally I'd like to see the error details and the original command, but it looks like that's not available from VS Code API level.

**Comment by jrieken** [comment]
> I would like it if it kept the same behavior as before.

We didn't change anything, it has always been like that when invoking a command that is using non primitive arguments.


> Ideally I'd like to see the error details and the original command name, but it looks like that's not available from VS Code API level (?).

Wrt the details it's actually the same problem. There is no guarantee that we can actually send those details to the renderer. But I agree that we can try better

**Comment by jrieken** [comment]
This now shows the actual extension identifier, not the indirection command anymore. Tho, we don't show the actual error because it's unclear how/if it can be serialised

**Comment by jrieken** [comment]
To verify, 

* `yo code` an extension
* use the command and code lens provider from below
* run and press a codelens
* make sure the right error shows

```ts
vscode.commands.registerCommand('extension.helloWorld', async (args) => {
        throw new Error('hello world')
 });

vscode.languages.registerCodeLensProvider('plaintext', new class implements vscode.CodeLensProvider {


    async provideCodeLenses(document: vscode.TextDocument, token: vscode.CancellationToken) {

        return [new vscode.CodeLens(new vscode.Range(0, 0, 1, 0), { command: 'extension.helloWorld', title: 'Hello World' })]
    }
})
```

**Comment by CsCherrYY** [comment]
We have the same scenario in Java extension. The Java extension will contribute a command, which would be used by other extensions. The contributed command may throw some custom exceptions in specific format so that the caller of this contribute command can handle different situations by different exceptions. Before `1.53`, it's programmable for us to catch these exceptions and works well. Currently we can only get such as `Running the contributed command: xxx failed`, instead of actual custom exceptions. 

@jrieken It seems the actual exception is caught by VS Code during the executing process. Can extensions get the actual exceptions when calling the command programmatically like before, by `vscode.commands.executeCommand(...)`?

**Comment by ganni** [comment]
> We have the same scenario in Java extension. The Java extension will contribute a command, which would be used by other extensions. The contributed command may throw some custom exceptions in specific format so that the caller of this contribute command can handle different situations by different exceptions. Before `1.53`, it's programmable for us to catch these exceptions and works well. Currently we can only get such as `Running the contributed command: xxx failed`, instead of actual custom exceptions.
> 
> @jrieken It seems the actual exception is caught by VS Code during the executing process. Can extensions get the actual exceptions when calling the command programmatically like before, by `vscode.commands.executeCommand(...)`?

Yes. I totally agree with @CsCherrYY. 
Nested command execution and catching original exception is totally messed up now.
