### ISSUE TITLE
Make it possible to run `code` on a remote machine from a non-integrated terminal

### ISSUE THREAD

**Issue by ebluestein** [microsoft/vscode#117096]
Currently, VS Code provides a `code` script that can be invoked on a remote host to open a file in a connected VS Code client. This implementation relies on an ENV var, `VSCODE_IPC_HOOK_CLI` being set, and therefore only works in a VS Code integrated terminal.

It's common for users to also connect to the machine with SSH or something like Mosh, Eternal Terminal, etc - and still want to open files.

We'd love a mechanism where if invoked from those environments, the script still finds connected VS Code clients and still works.

**Comment by Tyriar** [comment]
I don't think we should do this because in the integrated terminal we can actually tell as you mention which _window_ client is connected via the environment variable. If some other terminal is connected, that's not possible; what if 2 windows are connected, what is the right one? What if 2 machines are connected? What if 2 machines owned by different people are connected?
