### ISSUE TITLE
Icon & indentation visual issues in file list after upgrading to 1.5 on OSX

### ISSUE THREAD

**Issue by andrewconnell** [Microsoft/vscode#11705]
- VSCode Version: 1.5.0
- OS Version: OSX 10.11.6

Steps to Reproduce:

1. Had the popular [vscode-icons](https://marketplace.visualstudio.com/items?itemName=robertohuertasm.vscode-icons) extension installed in version immediately prior to 1.5
2. Upgraded VSCode to 1.5.0
3. Now, once I select an icon theme like Seti it appears there are conflicts with the old icon set from the vscode-icons extension. I tried uninstalling the extension, terminating all instances of VSCode and restarting, but still see artifacts as you can see below:
  - The **Open Editors** window uses the old icons, but the actual project shows the new icon set from the included Seti theme
  - The colored folders still appear in the project view... the preview of the Seti them seemed to not have folders... this look to come from the old extension
  - Indentation of items seems off... the files in the root of the project are nested under folders
  - Indentation of items within folders seems to be extremely duped... for instance in below image, the file `build.ts` resides in `/build/gulp/tasks` while `buildBarrel.ts` resides in `/build/gulp`

![2016-09-08_15-41-32](https://cloud.githubusercontent.com/assets/2068657/18364157/5660e8b8-75db-11e6-888d-ae8749863474.png)

Tried finding a place where icons were cached, but can't find anything... searched the `/users/[]/.vscode/*` folder... ensuring the extension was really gone which it is.

**Comment by alexkrolick** [comment]
Had the same problem. The solution is to reinstall the extension, then run the "disable icons" command for the extension: https://marketplace.visualstudio.com/items?itemName=robertohuertasm.vscode-icons

It seems like the configuration for that extension isn't contained to the extensions folder so uninstalling it does not undo its effects.

**Comment by mdouglass** [comment]
The indentation of items within folders is not unique to having had the extension installed previously. I've never previously used the vscode-icons extension, but I am having the indentation issue. It seems to be happening because folders are not given icons by the Seti theme (the other two built-in themes do not exhibit this problem). 

The files listed in this screenshot are at the same level as the folders, but appear to be beneath them.
<img width="254" alt="screen shot 2016-09-08 at 1 56 56 pm" src="https://cloud.githubusercontent.com/assets/5410142/18366585/264c1242-75cc-11e6-894a-58bf142acfde.png">

**Comment by robertohuertasm** [comment]
@alexkrolick @andrewconnell, vscode-icons injects code into 2 core files so if you uninstall it without restoring the backups will still be working. As @alexkrolick points out you have to first run the `icons disable` command in order to restore those files and then uninstall the extension.

In case you're still interested in having the old icons I'm planning to support the official API soon so I would suggest you to keep it disabled instead of uninstalling it.

Best regards.

**Comment by ramya-rao-a** [comment]
@aeschli indentation issues are independent of the vscode-icons extension

**Comment by andrewconnell** [comment]
Thanks for the advice @robertohuertasm ... that did help me once I reinstalled your extension, disabled icons, then disabled the icons theme in VSCode... 

Looking forward to your icon set... much preferred over what's included in the 1.5 update. Nice work on your extension too!

**Comment by aeschli** [comment]
@mdouglass Can you create a separate issue? The Visual Studio Code Seti theme on purpose doesn't contain folder icons. That the indentation can be confusing is a something we already discussed in the team. If many users are confused by it we should look into tweaking the indents.

**Comment by aeschli** [comment]
Closing this issue. Please file all vscode-icons interoperability issues against https://github.com/robertohuertasm/vscode-icons.

**Comment by ramya-rao-a** [comment]
@andrewconnell @mdouglass you can upvote #11762 for the indentation problem
