### ISSUE TITLE
Intellisense in comments disrupts flow

### ISSUE THREAD

**Issue by geoffreyfloyd** [Microsoft/vscode#11704]
- VSCode Version: 1.5.0
- OS Version: Windows 10 Pro, Version 1511, Build 10586.545

Steps to Reproduce:

1. Start typing a comment (intellisense tries to predict code). When hitting enter to go to a new line the intellisense replaces the last word in your comment with its suggestion.

Expected behavior:
No intellisense in comments

**Comment by ramya-rao-a** [comment]
By @dbaeumer  from https://github.com/Microsoft/vscode/issues/5051#issuecomment-206747243 

> we always include textual completions in code complete (e.g words that are in the document). We find this useful in strings and comments. Are you proposing not to show them? They are marked with an icon 'abc' to indicate that they are textual completions only.

@dbaeumer Maybe we can have setting to not show textual completions in comments?

**Comment by dbaeumer** [comment]
There are a couple of settings to tweak this:

- one to disable textual completions. However then they are gone in no comments as well
- to not make enter a completion accept character. Then tab has to be used to accept a completion and enter will be enter again.

Not having textual completions in comments has drawbacks as well since a JSDoc comment for example will refer to variables and type names and bing able to complete them is nice.

I will keep the issue around, however we have no silver bullet right now to make all use cases happy.

@jrieken FYI.

**Comment by jrieken** [comment]
As said, there two configuration knobs and this issue: #10819. Closing as dup

**Comment by ramya-rao-a** [comment]
urgh! got.. to.. get.. better.. at.. finding.. duplicates !!

**Comment by ramya-rao-a** [comment]
@geoffreyfloyd Meanwhile you can try setting `editor.quickSuggestions: false` to not get the suggestions unless you `ctrl+space`
