### ISSUE TITLE
Emmet CSS: Doesn't expand when ! (!important) is included

### ISSUE THREAD

**Issue by babobski** [microsoft/vscode#117020]
I'm switching from Komodo Ide to vscode.
The biggest miss/frustration is that I can not use ! (important) in my emmet abbreviations.
I'm used that it can be done in one operation.
In vscode I a have to use two steps to accomplish the same.

Version: 1.53.2 (user setup)
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:48:04.245Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. Try to expand `bdbn!` (border-bottom: none !important;)
2. Nothing happens

Expected result:

It should expand to `border-bottom: none !important;`

Work around:

First expand `bdbn` and then `!`

**Comment by yume-chan** [comment]
I remember it used to work. Now it looks like because `!` is a separator character so IntelliSense automatically stops.

Anyway, two more workarounds before a proper fix:

1. Set `emmet.triggerExpansionOnTab` setting to `true`, although it doesn't show the suggest widget, hitting <kbd>Tab</kbd> still expands `bdbn!`
2. After typing `bdbn!`, hit <kbd>Ctrl</kbd> + <kbd>Space</kbd> (or <kbd>Ctrl</kbd>+<kbd>i</kbd>) then <kbd>Tab</kbd>/<kbd>Enter</kbd>

**Comment by babobski** [comment]
@yume-chan Thanks for the quick reply.
For me the second workaround is working better.
On the first it try's to autocomplete a comment:

![afbeelding](https://user-images.githubusercontent.com/3530262/108489453-dbed5f80-72a1-11eb-9da4-dbac8b682862.png)

Hitting tab will insert it.

**Comment by rzhao271** [comment]
More of a note to self, but I just confirmed that the expansion works in vscode-emmet-helper. Therefore, this issue is caused by something within this repo rather than upstream.
