### ISSUE TITLE
Terminal cannot input

### ISSUE THREAD

**Issue by lizhihaoerdaye** [microsoft/vscode#117123]
- VS Code Version:1.42.1
- OS Version:Windows 10

Steps to Reproduce:

1.Ctrl+Shift+` Open a terminal
2.The terminal does not display any content

Does this issue occur when all extensions are disabled?: Yes
![cuowude](https://user-images.githubusercontent.com/47618476/108593079-949fc580-73ac-11eb-884f-42f8f5d1a217.png)
![cuowude](https://user-images.githubusercontent.com/47618476/108593082-9c5f6a00-73ac-11eb-817f-1b7a218c0970.png)

**Comment by mcswell** [comment]
I'm seeing this same problem.  I believe it worked last week, which makes it rather mysterious--I have not seen any updates since that last login.  Version 1.53.2, dated 2021-02-11; Win10.  Logging into a remote Linux machine.  I verified that I can log into that machine using the MsTerminal, just not with the terminal in VSC.  

The terminal works ok when I have a VSC instance open editing a file on my local computer.

I've run it as `code --log trace` (as suggested in this long ago thread: 49488.  I tried the fixes there, to no avail.  Let me know if you want those log files.  One of the suggestions in that thread is to select the default shell, which is supposed to work from either the Command Palette or from the terminal itself, but neither one does anything: there is no drop-down menu.

A couple suggestions I've seen in this long ago thread [https://stackoverflow.com/questions/54092486/visual-studio-code-terminal-blank-screen](Stack Overflow) include setting "Terminal: Integrated" and "Inherit Env".  None seems to have any effect.

About a year ago, I (and others) was experiencing problems with the terminal.  It turned out s.t. was going wrong with the installation of VSC code into ~/.vscode-server .  I think maybe that's what's going on again.  I looked at my `~/.vscode-server/`, and it has a single subdirectory, `bin`.  I believe there should be 3 subdirectories there: `bin/`,  `data/` and `extensions/`.  My vague recollection from the previous problem was that VSC uploads a compressed file to the ~/.vscode-server/ dir on the remote machine, then extracts a bunch of files from it.  Last year, for some reason it was unable to extract those files, hence the failure.  The temp fix was to upload the compressed file and extract it by hand; not sure what the permanent fix was.  I'll see if I can find that thread...

**Comment by mcswell** [comment]
Found the thread: 2828.  And the work-around there works here too: log into the remote using an alternative terminal (like MsTerminal).  Go to `~/vscode-server` and delete `.*.log`.  Then log in using VSC, and suddenly you'll have a working terminal.

**Comment by mcswell** [comment]
The complete link to thread 2828: https://github.com/microsoft/vscode-remote-release/issues/2828

**Comment by wsmPanda** [comment]
I has faced same problem those day and found such erorr message in develop tool:
 ERR A system error occurred (ENOENT: no such file or directory, scandir 'C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps'): Error: ENOENT: no such file or directory, scandir 'C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps'

And I'm pretty sure that directory 'C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps' is exist

![image](https://user-images.githubusercontent.com/18100956/109154160-dfed1600-77a8-11eb-835d-c3cca7d69ca4.png)

**Comment by lizhihaoerdaye** [comment]
> 那天我也遇到了同样的问题，并在开发工具中发现了这样的错误消息：
> ERR发生系统错误（ENOENT：没有此类文件或目录，scandir'C：\ Users \ Administrator \ AppData \ Local \ Microsoft \ WindowsApps'）：错误：ENOENT：没有这样的文件或目录，scandir'C：\ Users \ Administrator \ AppData \ Local \ Microsoft \ WindowsApps'
> 
> 而且我很确定目录'C：\ Users \ Administrator \ AppData \ Local \ Microsoft \ WindowsApps'存在
> 
> ![图像](https://user-images.githubusercontent.com/18100956/109154160-dfed1600-77a8-11eb-835d-c3cca7d69ca4.png)

I'm in the same situation

**Comment by mcswell** [comment]
> I has faced same problem those day 

Does deleting ~/.vscode-server/*.log on the remote fix it?  (Notice the '.' before 'vscode', I omitted that in my posting above)

**Comment by wsmPanda** [comment]
> > I has faced same problem those day
> 
> Does deleting ~/.vscode-server/*.log on the remote fix it? (Notice the '.' before 'vscode', I omitted that in my posting above)

QAQ Regrettably, I doesn't found any file like .vscode-server or .vscode/*.log in  my user directory

**Comment by mcswell** [comment]
> QAQ Regrettably, I doesn't found any file like .vscode-server or .vscode/*.log in my user directory

These log files are on the machine you're trying to connect to, which I'm assuming is a Linux machine, not on the machine you're running from (like a PC at home or in your office).  The full path on the Linux machine would be something like
     /home/wsm/.vscode-server/3948a2097509c38490b238.log
where 'wsm' would be whatever your login name on the target machine is, and '39...' would be a long string of hexadecimal digits.  There might be more than one such .log file, which is why I used '*'.  So the command you'd run on the target machine is something like
      rm .vscode-server/*.log
assuming you run it from your home directory.  If you can't get a working terminal on the target machine, you'd need to log in some other way, like using Microsoft's terminal, or puTTy, or even cmd.exe (which should include an 'ssh' command).  Or if you're running on a Mac at home/office, I guess you could ssh into your target machine from 'bash'.

**Comment by wsmPanda** [comment]
> > QAQ Regrettably, I doesn't found any file like .vscode-server or .vscode/*.log in my user directory
> 
> These log files are on the machine you're trying to connect to, which I'm assuming is a Linux machine, not on the machine you're running from (like a PC at home or in your office). The full path on the Linux machine would be something like
> /home/wsm/.vscode-server/3948a2097509c38490b238.log
> where 'wsm' would be whatever your login name on the target machine is, and '39...' would be a long string of hexadecimal digits. There might be more than one such .log file, which is why I used '_'. So the command you'd run on the target machine is something like rm .vscode-server/_.log
> assuming you run it from your home directory. If you can't get a working terminal on the target machine, you'd need to log in some other way, like using Microsoft's terminal, or puTTy, or even cmd.exe (which should include an 'ssh' command). Or if you're running on a Mac at home/office, I guess you could ssh into your target machine from 'bash'.

I think I have never try to do something connect to remote  machine,I just open vscode normally.I mean that may not be one situation we talking about.

**Comment by mcswell** [comment]
Well, it's not the situation I was talking about.  But that may be a clue for the developer, if the terminal freezes both when the terminal is open on a remote machine (my situation) AND when it's open on the local machine (yours).

**Comment by meganrogge** [comment]
You are on a very old version of VS code. Can you try updating to a more recent build?

**Comment by mcswell** [comment]
I assume you're replying to the OP, right?  I commented that I had this problem with Version 1.53.2, which I believe is the most recent version.  I can't however reproduce the problem now, because deleting the *.log files fixed the problem.  (Maybe it will come back when there's a new version of VSC--that was my experience last year.)

**Comment by meganrogge** [comment]
Oh okay thanks for the info.

**Comment by wsmPanda** [comment]
I either in Version 1.53.2,and there are still problems.

**Comment by lizhihaoerdaye** [comment]
> 您使用的是VS代码的旧版本。您可以尝试更新到较新的版本吗？

I downloaded the latest vscode, but I still have this problem;

**Comment by TylerLeonhardt** [comment]
As a workaround, you should be able to set:

```
    "terminal.integrated.shell.windows": "pwsh.exe",
```
or
```
    "terminal.integrated.shell.windows": "powershell.exe",
```

in your settings.

**Comment by TylerLeonhardt** [comment]
@lizhihaoerdaye @wsmPanda are you running VS Code as administrator? Just curious.

**Comment by TylerLeonhardt** [comment]
I've merged in a fix that should catch this error better. It will be in the next release.

**Comment by TylerLeonhardt** [comment]
Verification steps:

Using Windows with PowerShell installed via Store

* open a terminal
* PowerShell installed via Store should show up

Using Windows without PowerShell installed via Store

* open a terminal
* PowerShell installed via Store should show up

Now so the same thing but with VS Code started as Administrator.

**Comment by wsmPanda** [comment]
> @lizhihaoerdaye @wsmPanda are you running VS Code as administrator? Just curious.

Of course.I did.Other things "terminal.integrated.shell.windows" in my setting.json editor seem like an unknown configuration setting  (font color is darker).

**Comment by TylerLeonhardt** [comment]
The latest version of VS Code went out today. @wsmPanda can you test it out and see if you're ok now?

**Comment by wsmPanda** [comment]
Yes,It's works well in latest version. @TylerLeonhardt

**Comment by blopez2010** [comment]
I have updated my vscode to the latest version, I opened the terminal settings and rolled back to PowerShell terminal, closed my vscode, and re-opened, the issue persists...

**Comment by TylerLeonhardt** [comment]
@blopez2010 can you send a screenshot of what you're seeing, what is in your settings, what OS you're using?

**Comment by blopez2010** [comment]
@TylerLeonhardt just noticed a bad setting regarding the integrated terminal config. Now, it is perfectly working!!!! sorry about the fake news  😄

**Comment by PiccoloYu** [comment]
> @TylerLeonhardt刚刚注意到有关集成终端配置的错误设置。现在，它工作正常！！！！对假消息感到抱歉 😄

I have the same problem. Can you tell me how to solve it? Thank you very much.

**Comment by PiccoloYu** [comment]
![Uploading image.png…]()
![Uploading image.png…]()
