### ISSUE TITLE
Typescript diagnosis is not work in the web

### ISSUE THREAD

**Issue by howel52** [microsoft/vscode#117195]
- VS Code Version: 1.54.0
- OS Version: macOS 11.0.1, Chrome 88

Steps to Reproduce:

1. clone the vscode repo and install dependencies
2. run `yarn web`, serve in local
3. open the `localhost:8081`

When we start the `VS Code Web` in local, the diagnosis is not work in TypeScript files

Like:
![VS Code Web](https://user-images.githubusercontent.com/9854818/108649457-56afb800-74f8-11eb-8293-b89d002891cf.png)

Same code in VS Code electron is correct
![VS Code Electron](https://user-images.githubusercontent.com/9854818/108649613-a9896f80-74f8-11eb-86d6-acec751dbc52.png)

Does this issue occur when all extensions are disabled?: No(maybe active the extensions which builtin)

**Comment by howel52** [comment]
Maybe this line of code did not work

https://github.com/microsoft/vscode/blob/8d9634abac32c67afabe51348a85973c93b97ebc/extensions/typescript-language-features/src/languageFeatures/diagnostics.ts#L160

**Comment by howel52** [comment]
I think the reason is that `event onLanguage:typescript` is later than `event *` active.

**Comment by mjbvz** [comment]
This is intentional. We do not support cross file diagnostics on the web since that would require loading all files that are part of the project into the current browser instance. We may enable simple, single file diagnostics in the future for syntax errors

Note that codespaces do fully support diagnostics because the TS Server is running on a VM, instead of in the user's browser
