### ISSUE TITLE
VSCode Editor is empty for all files

### ISSUE THREAD

**Issue by alanwright** [Microsoft/vscode#11715]
- VSCode Version: 1.5.0
- OS Version: Windows 10 Enterprise (Build 10586.545)

Microsoft internal alias: alanwri

Steps to Reproduce:

1. Open VSCode
2. When opening any file, nothing shows up in the text editor 
Happens for all types of files, VSCode is unusable. Tried fresh uninstall, and install from vscode website, still repros. No idea what to do. Feel free to ping me internally and I can share my screen, etc. 

![image](https://cloud.githubusercontent.com/assets/2292985/18366871/413c4774-75cd-11e6-812b-b0bb39133e07.png)

**Comment by alanwright** [comment]
Uninstalled all my extensions and restarted. Still no fix

**Comment by Tyriar** [comment]
This is happening due to a change that makes the editor respect `"editor.fontSize": 0`. The fix it to remove that setting value. To do that you can open your settings, select all, cut and save.

1. <kbd>ctrl</kbd>/<kbd>cmd</kbd>+<kbd>a</kbd>
2. <kbd>ctrl</kbd>/<kbd>cmd</kbd>+<kbd>x</kbd>
3. <kbd>ctrl</kbd>/<kbd>cmd</kbd>+<kbd>s</kbd>

Your old settings file can then be pasted into the editor.

If the above is not possible for whatever reason (your keybindings are unset or something?) then the `settings.json` file can be accessed in another editor at:

- Windows: `%APPDATA%/Code/User/settings.json`
- Linux: `~/.config/Code/User/settings.json`
- Mac: `~/Library/Application Support/Code/User/settings.json`

**Comment by alanwright** [comment]
This fixed it, thank you!

**Comment by kieferrm** [comment]
We released 1.5.1 as recovery build.

**Comment by ronanwize** [comment]
That is really impressive how quickly you guys pushed that out.

**Comment by deviprsd21** [comment]
Woah, way too fast. Impressive.

**Comment by xparabolax** [comment]
Kudos, VSCode team. Amazing job.

**Comment by RobertoMalatesta** [comment]
Astonished by the level of care and support your (really, really) distinguished team gives to this product.

--R

**Comment by vip3rousmango** [comment]
Ty for the quick fix! From one dev to another, it's really appreciated and why I continue to love using VS Code.
