### ISSUE TITLE
Test: install from winget

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#117222]
Refs: #105307

- [x] windows @bamurtaugh
- [x] windows @digitarald

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23117222%0A%0A)

---

* [Install](https://github.com/microsoft/winget-cli#installing-the-client) `winget` if necessary
* From the command line run a search for VSCode - `winget search vscode`. This will list the 8 packages that we publish.
* Install any of the packages using the moniker (ex: `winget install vscode-system-x64`)
* Sanity check the installation

**Comment by bamurtaugh** [comment]
I seem to have seen 8 packages rather than 6 - not sure if this was expected/if all of these are unique packages or not:

![image](https://user-images.githubusercontent.com/25310137/108880302-02b7d880-75b7-11eb-8edf-b303c605d4b1.png)

I installed the `vscode-system-x64` package, and things are working properly. 

@lszomoru I'm not sure if there are formal steps in a sanity check, and if so, I'd be happy to complete and verify them. I did things like opening/closing folders, clicking through viewlets, using the integrated terminal, and using extensions (i.e. Remote - Containers), and they all worked as I'd expect.

**Comment by lszomoru** [comment]
Thanks @bamurtaugh for testing.

>I seem to have seen 8 packages rather than 6 - not sure if this was expected/if all of these are unique packages or not:

My bad, we are publishing 8 total packages to `WinGet`. Corrected the description.

>@lszomoru I'm not sure if there are formal steps in a sanity check, and if so, I'd be happy to complete and verify them. I did things like opening/closing folders, clicking through viewlets, using the integrated terminal, and using extensions (i.e. Remote - Containers), and they all worked as I'd expect.

That covers it. Thank you very much!

**Comment by digitarald** [comment]
Worked without issues. Installed twice and did a bit of file browsing, editing, etc.
