### ISSUE TITLE
Goto declaration should store current cursor in navigation history

### ISSUE THREAD

**Issue by ihamer** [Microsoft/vscode#11727]
Steps to Reproduce:
1. Invoke editor.action.goToDeclaration
2. Invoke workbench.action.navigateBack
The cursor should go back to the exact spot where it was before the jump. Instead, it goes one sport further back...

**Comment by ramya-rao-a** [comment]
@ihamer Can you provide more details like VS Code version, OS type and version etc.
Also, sample code of what you are trying to do in your extension and a screencast/gif/video ?

**Comment by bpasero** [comment]
Likely https://github.com/Microsoft/vscode/issues/3736

**Comment by ihamer** [comment]
@ramya-rao-a There is no extension involved. This is vanilla behaviour. Using version 1.4 on Ubuntu 16.04.
@bpasero Related to #3736, but not the same. 

This is likely to be very easy to fix (jumpToDefinition event should push the current cursor position to the history).

**Comment by bpasero** [comment]
I agree we should record the current cursor position on certain actions like "Go to definition".

**Comment by bpasero** [comment]
Pushed a change to improve this situation for the following cases:
* goto definition will store the current cursor location as history entry so that when jumping back you end up in the same line number
* opening another editor will now also store the current cursor in the history so that going back puts you to the exact same line number too
