### ISSUE TITLE
Treat hyphen as part of word

### ISSUE THREAD

**Issue by qtxie** [Microsoft/vscode#11729]
- VSCode Version: 1.5.1
- OS Version: Windows 7 64 bit

In some programming languages, especially Lisp-like ones, the hyphen (`-`) is treat as part of a word.
Now when I click or double click a word in VSCode, it is highlighting like this:

![20160909074504](https://cloud.githubusercontent.com/assets/1673525/18370674/873349be-7661-11e6-81a8-7e0f5dc821ab.png)

What I expect is like this:

![rebol20160909074552](https://cloud.githubusercontent.com/assets/1673525/18370741/018336e8-7662-11e6-9381-190080dbd6d7.png)

How can I do this in VSCode ?

**Comment by indiejames** [comment]
Add this to your settings:

```
"editor.wordSeparators": " ()\"':,;~@#$%^&{}[]`"
```

**Comment by qtxie** [comment]
@indiejames Thanks! :+1: 
Is there a way to do it in the language plugin? So the setting can only apply to specify language rather than all.

**Comment by ramya-rao-a** [comment]
@qtxie You can add this setting in your workspace settings instead of user settings. This way it will be applied to certain workspaces instead of all workspaces. 

This is a setting for the editor and so cannot be applied to specific languages only out of the box.

An extension can update the settings based on file extension of the document in the active editor. So you can write an extension for that or make a feature request to the extension you currently use for lisp

**Comment by qtxie** [comment]
@ramya-rao-a Thanks a lot. :-)
