### ISSUE TITLE
Updating appending/updating output in Notebooks does not work as expected

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#117273]
- VS Code Version:OSS
- OS Version: Mac

Steps to Reproduce:

1. Use VSC API to add/replace outputs to create multiple does not work as expected
2. Sample code can be found here https://github.com/microsoft/vscode/pull/117272

**Requirement in Jupyter**
* We need to have two output items, one for stdout & another for stderr.
	* As we get new output for stderr, we'll update the stderr output by appending the corresponding output items to that output.
	* Similarly when we get new output for stdout, we'll append output items to that output.
* With the existing API, it doesn't seem to create multiple outputs.

@rebornix @jrieken /cc

Does this issue occur when all extensions are disabled?: N/A

**Comment by jrieken** [comment]
> Use VSC API to add/replace outputs to create multiple does not work as expected

Not sure I understand yet but (within one call) you have to decide between append or replace. Understand replace as "clear & append"

**Comment by DonJayamanne** [comment]
Hopefully the rest makes it clear, I cannot add multiple output items using either operation.

**Comment by jrieken** [comment]
I can reproduce... Not sure what's going on, the renderer is sending the wrong output object while the edit happens...

<img width="1047" alt="Screenshot 2021-02-24 at 11 31 05" src="https://user-images.githubusercontent.com/1794099/108987709-e2aa1700-7693-11eb-8782-dedd9227ee12.png">

**Comment by jrieken** [comment]
Oh, wait... This is specific to the mime type (see a very similar, but failing tests in `notebook.document.test.ts`). I know that there is some automagic merging happening (which is probably wrong)

**Comment by jrieken** [comment]
I have pushed a unit test and fixed version of your integration test and I am concluding that everything is in order, except for your sample. The second time you call `applyEdit` you do with the WorkspaceEdit-object for the first call, e.g `edit` NOT `edit2` and with that you aren't getting anywhere ;-)

https://github.com/microsoft/vscode/pull/117272/files#diff-2d8742a7e6c376054b3cad3281f0746399fdd4b6368ae71205a08e50553dd2aeR1276

**Comment by DonJayamanne** [comment]
Thanks, will try this in OSS

**Comment by DonJayamanne** [comment]
I was hoping for the UI to also have two separate output items.
One output for stdout & another output for stderr.
& if there's another stdout output, then that should be a 3rd item, see here for what Jupyter does today.

Based on what i can tell, the API doesn't support this today, it always appends everything into a single UI output item.

![Screen Shot 2021-02-24 at 13 14 48](https://user-images.githubusercontent.com/1948812/109066765-666b0000-76a2-11eb-8878-3684d8b13dcd.png)

**Comment by rebornix** [comment]
I think what @DonJayamanne was talking about is the "auto-merge" feature of `stream` output objects other than output items. The latter is working as expected and Jupyter extension is using that to handle streaming. However in Jupyter, you can have two types of stream, one is `stdout`, another is `stderr` (the raw outputs have different names) and Jupyter doesn't merge these two in the UI.

Right now in VS Code, below two are identical in the UI, both of them are rendered as `12ab`

```
// single output, multi items
new vscode.NotebookCellOutput([
  new vscode.NotebookCellOutputItem('application/x.notebook.stream', 12, { name: 'stdout' })
  new vscode.NotebookCellOutputItem('application/x.notebook.stream', 'ab', { name: 'stdout' })
])


new vscode.NotebookCellOutput([
  new vscode.NotebookCellOutputItem('application/x.notebook.stream', 12, { name: 'stdout' })
])
new vscode.NotebookCellOutput([
  new vscode.NotebookCellOutputItem('application/x.notebook.stream', 'ab', { name: 'stderr' })
])
```

but in Jupyter the second scenario is rendered as 

```
12

ab
```

simply because they are different streams.


Our current API doesn't know anything about multi-stream, as long as we see `x.notebook.stream` in sequence, we merge them in the UI --> https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/notebook/browser/view/renderers/cellOutput.ts#L101

Maybe we can turn this off for `NotebookCellOutput`s since we allow you to append output items, which extensions can always rely on to archive the UI merging.

**Comment by jrieken** [comment]
> Maybe we can turn this off for NotebookCellOutputs since we allow you to append output items, which extensions can always rely on to archive the UI merging.

That or use different mime types for stdout and stderr. With that could use a different rendering for error, like use error colors etc

**Comment by rebornix** [comment]
Agree, maybe we can have `application/x.notebook.error`, whose value would be `string | string[]`.
