### ISSUE TITLE
Custom menu disappears when hovering over disabled items

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#117223]
1. windows, code insiders new empty user data dir
2. Open for example the Search view
3. Open the File menu using the mouse
4. Hover with the mouse over all items down. Once you hover over a disabled item menu gets hidden

I am seeing this on my VM, so that might be the cause.
However adding important so this does not slip.

**Comment by isidorn** [comment]
I changed how the focus works in `ActionBar` this milestone, however that should not affect the mouse hover. But just fyi

**Comment by sbatten** [comment]
@isidorn changing how focus works would affect the menu bar mouse hover because the mouse moves focus in the custom menus. this is done to synchronize the keyboard focus state and mouse focus state which are not separate in menus. I may be able to move away from the implementation but not so late in the milestone. I will investigate today for a safe fix.

**Comment by isidorn** [comment]
@sbatten I probably broke this then, I am sorry.
What I changed is that disabled items can also be focusable. This might break some of your logic.
Anyways since menus is a special use case, let me know if you would like some flag for the menus so we go back to the old behaviour until we properly fix this in debt week.
Anyways let me know how I can help best :)

**Comment by sbatten** [comment]
@isidorn please review

**Comment by isidorn** [comment]
@sbatten code looks great, thanks for the fix.
