### ISSUE TITLE
Should disabled actions be focused?

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#117355]
Testing #116559

I wonder if disabled actions should get focus by default or wether the enabled action should focus by default:

![image](https://user-images.githubusercontent.com/900690/108829490-85955f00-75c8-11eb-996e-e62ab743c94b.png)

**Comment by isidorn** [comment]
Yeah they should, we did this change on purpose since it is recommended as this nice exmaple shows it https://www.w3.org/TR/wai-aria-practices-1.1/examples/toolbar/toolbar.html

Without that screen reader users could not figure out that there is a disabled action there and that they maybe need to change some state to enable it.
Thus closing as desinged, thanks for feedback!
