### ISSUE TITLE
Pressing cancel in auth dialog should show badge on auth icon

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#117357]
Testing #117290

* have the snippet below 
* select 'cancel' in the auth-allow-dialog (see screen shot)
* you are now lost. I didn't allow or deny auth and I would expect that the auth icon shows the badge to guide me to retrying this

<img width="1038" alt="Screenshot 2021-02-23 at 11 14 30" src="https://user-images.githubusercontent.com/1794099/108830062-3996ea00-75c9-11eb-86d5-7825eeb74365.png">
 

```ts
	let disposable = vscode.commands.registerCommand('extension.helloWorld', async () => {

		const session = await vscode.authentication.getSession(
			'microsoft',
			["https://management.core.windows.net/.default", "offline_access"],
			{ createIfNone: true }
		)

		console.log(session);
	});
```

**Comment by jrieken** [comment]
I still don't see the badge when pressing cancel

**Comment by RMacfarlane** [comment]
@jrieken I'm having trouble repro'ing, any additional steps?

![cancel_grant](https://user-images.githubusercontent.com/3672607/109195454-637a1900-774f-11eb-8fb3-fb408198afed.gif)

**Comment by jrieken** [comment]
This is what I am doing/having

* logged in to GH and allowed GHNB extension
* request auth from my test extension and press cancel
* now I don't see the "grant auth for test"

https://user-images.githubusercontent.com/1794099/109195839-4cf9af00-779b-11eb-862b-9a4273464e4d.mov

**Comment by jrieken** [comment]
```
 vscode.commands.registerCommand('extension.helloWorld', async (args) => {
        const session = await vscode.authentication.getSession('github', [],
            { createIfNone: true }
        )

        console.log(session);
    });
```

**Comment by TylerLeonhardt** [comment]
This is an interesting issue because I'm not sure I'd call this a bug completely. The model flow is suppose to be for "I can't do anything else unless you give me auth" scenarios and hitting cancel there says "no sorry you can't have it I don't care what functionality I'm missing out on".

I could see people saying that the opposite should be true "I don't want to see the badge for the modal auth flow because I said I didn't wanna auth".

So I'm more leaning on this being "by-design". The badge is really only for silent notification that auth'ing gives you extra features... not for if you explicitly say you don't want auth.

What do you think @jrieken?

**Comment by jrieken** [comment]
Fair enough.
