### ISSUE TITLE
Source Control action bar item order changed

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#117456]
- VS Code Version: 1.54.0 Insiders
- OS Version: Windows 10, macOS

Steps to Reproduce:

1. Open VS Code in a repo and make a pending change.
2. Hover over the changed file in the Source Control view

The order of the Source Control view file actions has changed with Discard being the leftmost.

![image](https://user-images.githubusercontent.com/12818376/108896141-5fbc8a00-75c9-11eb-9842-31666a882ea0.png)

The leftmost used to be Open File (1.53.2 Stable):

![image](https://user-images.githubusercontent.com/12818376/108896260-84186680-75c9-11eb-8938-332c59cd4824.png)

This change is risky since user's muscle memory to open a file will now start to discard the pending change.

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
This is so weird. I can't seem to bisect my way to a culprit. I can't find the login behind this having changed.

**Comment by joaomoreno** [comment]
OK sometimes A* works better than deterministic bisecting: 4941e47c025b3f00468fb6d210e2d7596aecd063 is the culprit. cc @jrieken

**Comment by jrieken** [comment]
The problem is that SCM has multiple primary menu groups and that the order of these groups has now changed (to the correct order btw). I have fixed this SCM contributions by using the `<group>@<weight>` syntax which allows to assign an item to a group and define it order. 

However, it seems that the loose check for a group being the primary group is also used in debug, editor-title (@isidorn), in testing (@connor4312)

https://github.com/microsoft/vscode/blob/5713f2880112260ef11f8fbe28e64c350402703e/src/vs/workbench/contrib/testing/browser/testingExplorerView.ts#L970

Checks like the one above are a little unexpected and know that the order of multiple primary groups in now not reversed anymore

**Comment by isidorn** [comment]
@jrieken it was a copy paste mistake for me. I will change in debt week to have a more precise check. I want only one primary group.

**Comment by connor4312** [comment]
The [code bunnies](https://humanwhocodes.com/blog/2015/05/14/the-bunny-theory-of-code/) strike again

**Comment by jrieken** [comment]
That 🐰 made my day. Thanks for sharing

**Comment by joaomoreno** [comment]
Definitely bookmarking it.
