### ISSUE TITLE
git-scm commit message inputbox can only be navigated to with shift+tab

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#117441]
Testing #116559

I have the sidebar open to the source control view. When I start pressing tab while focus is on the activity bar, the commit message inputbox gets skipped over.

However, if I first click in that viewlet using my mouse, there are then extra tabstops added that include the commit message inputbox as well as the whole viewlet. This behaviour seems to be the intended one.

**Comment by isidorn** [comment]
I can not reproduce this with latest vscode insiders. Here are my steps:

1. Have scm view open ,Reload VS Code
2. F1 > focus into activity bar
3. Press tab couple of times -> commit input box gets focused

Though my changes in the action bar should not have changed this, thus also assigning to @eamodio since he might have ideas what is going on here

**Comment by rzhao271** [comment]
Hm, this one also works fine after a reload. Not sure what happened.
