### ISSUE TITLE
Support reconnect in tasks

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#117408]
Terminals now reconnect when reloading local or remote windows. If a task is running at the time this will still reconnect the terminal but not restore the _task_, for example the VS Code core watch task results in this:

![image](https://user-images.githubusercontent.com/2193314/108858854-7ea72600-75a1-11eb-8e6f-bec88fa1efd6.png)

cc @meganrogge

**Comment by alexr00** [comment]
Yes, this would be great. I thought @alexdima had done some work to make sure that task terminals were not restored for now though? Since we cannot restore the task now, we decided this was the best behavior for now.

**Comment by alexdima** [comment]
@alexr00 I think what we did was for restored **remote** terminals, while this issue might be about restoring terminals with local windows.

**Comment by Tyriar** [comment]
Looks like the disabling in remote is here:

https://github.com/microsoft/vscode/blob/dda96b69bfc63f309e60cfc5f98cb863c46b32ac/src/vs/workbench/contrib/terminal/browser/remoteTerminalService.ts#L157

We don't have this for local atm, should we add it? Isn't it good that the task terminals still get restored, despite not being linked to the task system?

**Comment by alexr00** [comment]
I think having "orphaned" task terminals is not a good behavior, and it would be better if they simply didn't restore until we have a good story. For example, if a user has a task that runs automatically when a folder is opened and their terminal restored then they could get weird behavior because now they have the old orphaned task running and the new task running.

**Comment by Tyriar** [comment]
👍 disabling in https://github.com/microsoft/vscode/issues/117578

**Comment by Tyriar** [comment]
This would be really nice to have. Right now all I need to do to get back up and running after reloading the window is ctrl+shift+b. This isn't that big of a deal for the VS Code repo or other repos I work in as they're fairly small, but larger projects that don't have the daemon worker system it will mean no more rebuilding after reloads.

**Comment by bpasero** [comment]
> This would be really nice to have. Right now all I need to do to get back up and running after reloading the window is ctrl+shift+b. This isn't that big of a deal for the VS Code repo or other repos I work in as they're fairly small, but larger projects that don't have the daemon worker system it will mean no more rebuilding after reloads.

Same here, would be great to have for a nice reload/restart experience. I. keep many local checkouts of VSCode to try out different things and switch branches and I often forget in which workspace I have background compile tasks running.

**Comment by Tyriar** [comment]
We want to explore this to try to gauge how much effort it will take to do, reconnection reliability is the priority for June https://github.com/microsoft/vscode/issues/151936

**Comment by meganrogge** [comment]
explored this on `origin/merogge/task-reconnection`. some questions:

1. `TerminalTaskSystem` is lazily created ATM, but to reconnect to tasks, we'll need it to be created when the window is loaded so it re-runs tasks when `TerminalService` has reconnected to terminals and fires `_onDidRequestTasksReconnection`
2. `AbstractTaskSystem` is aware / the source of the `ITaskResolver` that is needed to run each task. `AbstractTaskSystem` is unaware of `ITerminalService` currently, so doesn't seem like the right place for reconnection. Does this mean we need to store the `resolver` for the last task run in each terminal in `TerminalTaskSystem`? Had some trouble doing this via `lastTask.resolver`.

**Comment by alexr00** [comment]
@meganrogge I'm looking at your work so far now, but I've been thinking about your points/questions. Did you consider having `AbstractTaskService` save which tasks are running, then upon reload "restart" (in quotes because they never actually stopped) them by calling into the `TerminalTaskSystem`? The `TerminalTaskSystem` then would check if there are already terminals running that "match" the task based on some property that is set on the terminal? 

For saving the tasks, I think you can use the tasks recently used key.
