### ISSUE TITLE
fullscreen x hidden in linux results in inaccessible menu

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#117450]
Testing #117275

With

```
    "window.menuBarVisibility": "hidden",
    "window.titleBarStyle": "custom",
```

Regardless of `customMenuBarAltFocus`, the menu is not accessible in full screen under Xubuntu. In windowed mode I can still access the menu by hitting `alt+f` for example, but this isn't the case in fullscreen.

**Comment by sbatten** [comment]
this is really a quirk between the two versions. IMO the mnemonics should not work at all when the menubar is hidden (that's why we have 2 settings hidden vs toggle), we also have less control over the activation of the native version. In the interest of consistency, I can look into getting mnemonics to pull the menu up in fullscreen when hidden.

**Comment by sbatten** [comment]
after evaluation, no change here would be safe this milestone and honestly, this is the point of the toggle setting so I am just going to close this one.
