### ISSUE TITLE
Single custom editor does not split 

### ISSUE THREAD

**Issue by sana-ajani** [microsoft/vscode#117541]
Testing #117279

Open a single .png file using the Hex Editor. In the command palette, enter "view: split editor" and choose any of the options. Nothing happens when I try to split the editor using the command palette or using the split icon in the top right. I compare this to the experience using the text editor or custom notebook editor, where running this command on a single file opens up the same file in the split mode.

**Comment by lramos15** [comment]
This actually isn't fixed by that PR. The issue here is when you hit the split icon on an editor that doesn't support splitting and it's the only one in the editor group, then what should happen? You see nothing happen because it's creating a new group moving the editor to the new group and deleting the old group all in that moment. Should we hide the commands in this case, is nothing expected, should we show a notification?

**Comment by lramos15** [comment]
Discussed during the UX sync. This will be fixed by #120263 so closing now as we have a similar issue tracking the weird split behavior.
