### ISSUE TITLE
Restarting the pty-host (because it was unresponsive) doesn't reconnect terminals

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#117548]
Testing #117265 on Windows

Steps:
1. Open 2 terminals
2. Start a lot of output `ls -r` in one
3. Kill the terminal outputting lots of data
4. The other terminal is unresponsive
5. Restart the pty-host when prompted
6. Expect that either the unresponsive terminal is reconnected (which I'm assuming is not possible), or it would just be closed.

It seems odd to leave it open in a "disconnected" state -- as it makes it seem like it can be re-connected.

Also on a couple of occasions, the terminal didn't get `(disconnected)` in the name, though most of the time it did.

**Comment by Tyriar** [comment]
I thought it was best to leave it in the disconnected state in case it had important data in it. Do you think we should instead write disconnected + relaunching and relaunch without clearing it maybe?

**Comment by pvogel1967** [comment]
Hitting restart Pty Host has the current effect of *doing nothing useful* so yeah, I think you should self repair here, ideally without me having to click a dialog, but if I have to click, fine.  Don't leave me with a hung terminal even if I take the recommended action.

**Comment by Tyriar** [comment]
Thanks for the suggestions, here's the new experience:

![recording (13)](https://user-images.githubusercontent.com/2193314/111826795-5b248200-88a6-11eb-89bd-96c4b0800139.gif)

Also no notification shows up anymore for when the pty host _shuts down_, only when it's _unresponsive_ which happens when the proc hangs or restart failed several times. The reason for this is because it's possible to recover to unresponsiveness. Hopefully https://github.com/microsoft/vscode/issues/71966 will be fixed soon so it very rarely happens and we're left with a really resilient pty host.
