### ISSUE TITLE
Open with to the side does nothing 

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#117580]
Testing #117279

Probably same as https://github.com/microsoft/vscode/issues/117541

1. Open a file with the Hex Editor
2. <kbd>F1</kbd>, Reopen Editor With... and pick Hex Editor while holding <kbd>Alt</kbd> in order to open to the side

🐛 Nothing happens. It works if I pick Text Editor, or if I have the Text Editor focused.

**Comment by lramos15** [comment]
This is a hard to fix as the Hex Editor has a flag called `supportsMultipleEditorsPerDocument` which explicitly disallows splitting. Do you feel it would be broken if we closed the current text editor replaced it with a hex editor and then split into an empty group? Right now what happens when you split the hex editor for example is it creates and empty group in whatever direction the split happens.

**Comment by joaomoreno** [comment]
Oh I see, hex explicity disables this. It's fine to close this then.
