### ISSUE TITLE
Support editor overrides in quick open editor history

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#117579]
Testing #117279

1. Close all editors
2. Open a file with the Hex editors
3. Close all editors
4. <kbd>Ctrl P</kbd> to open the file again

🐛 File opens with text editor.

**Comment by lramos15** [comment]
This is by design, in my opinion. Since the hex editor is only opened in the first place due to you explicitly stating you want it. If you open the file again via the file picker I don't think it's expected that we remember your last editor choice. This happens with all custom editors and notebooks.

**Comment by joaomoreno** [comment]
Yeah that's the thing I think it's broken. I think we should remember what preferred editor was last used, per file.

**Comment by lramos15** [comment]
Hmm, ok. I think we might want to have a discussion about best behavior here. As often times the user finds it difficult to leave a custom editor for example so sometimes it's nice just to close and reopen it to get back to the text editor. I feel as if remembering is a bit strange. Maybe some notebook / custom editor / editor folks such as @jrieken @rebornix  @mjbvz and @bpasero can chime in and give their thoughts.

**Comment by rebornix** [comment]
if we are going to make it remember the last choice (per file), I would recommend we consider following at the same time

* A file can only be opened in one editor view type in a single editor group. Having two editor tabs for the same resource is weird. We enforce this for all *custom editors
* When you open a resource from the file explorer, it always opens with the last used view type, no matter if it's during workbench startup or not. For example, an issue from @joaomoreno https://github.com/microsoft/vscode/issues/99369 that we will open files in text editor when there is no `editoroverrides` registered yet

With above two, the file open/reopen is consistent: always open in the last picked editor view type.

**Comment by bpasero** [comment]
I am not convinced. IMHO an editor from quick open should open in the default editor that is associated with the file and if there are multiple, prompt the user and ask. If the user has configured the Hex editor to use with certain file types, we should respect that and it should just work from quick open.

Quick open history is not really a history of editors but more a history of files that were open in a previous session. I think it is weird to remember the editor that was used when an editor was opened with a non-default editor.

**Comment by joaomoreno** [comment]
> Quick open history is not really a history of editors but more a history of files that were open in a previous session. I think it is weird to remember the editor that was used when an editor was opened with a non-default editor.

My brain has always considered quick open to be a history of editors, not files. This is further cemented by the fact that diff editors appear in quick open:

![image](https://user-images.githubusercontent.com/22350/113684004-a813a100-9679-11eb-899f-d4edf9d8f2da.png)

**Comment by bpasero** [comment]
Yes and no. If you just open quick pick the "recently opened" includes all editors that were open. You can see for example how extension editors appear which are entirely not file based because they have no concept of a backing file.

However, when you start to type you get a mixed view of recently opened and search results and in that case, we only consider file based editors in the result so that the search results all talk about files and not editors. Otherwise you might end up finding extension editors in your search which is probably more confusing than helpful.

Expanding on this issue, now imagine we have an entry in the history per editor type for a resource, so you might have a picker looking like this:
* `package.json (text editor)`
* `package.json (hex editor)`
* `package.json (image editor)`

Would you expect to see 3 entries when you search for `package.json` or just one?

**Comment by joaomoreno** [comment]
> Would you expect to see 3 entries when you search for `package.json` or just one?

Just one: `package.json`. But I expect it to open in the previously chosen editor. The flow is:

1. Close the editor
2. <kbd>Ctrl P</kbd>, </kbd>Enter</kbd>

I expect to return to the same state. At least that's how Code has programmed my brain. 🙈

**Comment by lramos15** [comment]
@bpasero If we decide to go forward with this it sounds like I would at least need your help from a history perspective and you would then pass the "saved" override to the editorService which would trigger my service.

**Comment by bpasero** [comment]
@lramos15 from the history side of things, how would I be able to know which override was used in the end? Can I use `EditorInput.typeId` for that purpose? We somehow would need to encode the used editor into the history entry...

**Comment by lramos15** [comment]
@bpasero editorInput.viewType would have it for NotebookEditorInput and CustomEditorInput, else you would just reuse the passed in editor input I believe.

**Comment by bpasero** [comment]
@lramos15 to clarify, I am supposed to pass in `editorInput.viewType` as `override` option to restore that editor? What about `editorInput.typeId`, why do we have 2 concepts?

**Comment by lramos15** [comment]
@bpasero I think you could also preserve the entire editor input and that would be a more general solution although that might be a lot of data to serialize. viewType is not generically exposed from IEditorInput you are correct. `editorInput.typeID` is the type of editor input while `editorInput.viewType` is the ID of editor input as editor input types are not 1 : 1 mappings to editors

**Comment by bpasero** [comment]
@lramos15 I do not think that serialising the entire editor is an option. If I could get the `override` ID from the editor event that I need to use to bring the editor back to life, that would probably work.

I still have some UX concerns though because I see the quick open editor history as a history of files and not editors in most cases...

**Comment by lramos15** [comment]
@bpasero I agree that editorID should be enough although the editorInput doesn't always have an ID  (i.e, Keybindings). You might need a combination of type and editor id. Let's bring this up as the next UX meeting and then hold the issue until then.

**Comment by bpasero** [comment]
With https://github.com/microsoft/vscode/issues/126728 most of the work was done already because the history now keeps untyped editor inputs and not just resources and these untyped editor inputs come with the right override to use.

We still just keep 1 entry for the history, independent with how many editors you used for the same resource. Last one wins.

**Comment by bpasero** [comment]
Blocked until https://github.com/microsoft/vscode/issues/126923 is fixed.
