### ISSUE TITLE
Should `emmet.extensionsPath` merge snippet files?

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#117515]
Testing #117277

1. Try configuring `emmet.extensionsPath` with multiple valid paths `"emmet.extensionsPath": ["e1", "e2"]`
2. In an html file, try triggering emmet

**Bug**
The first valid snippet file is picked. This confused me as I expected to see snippets from all valid snippet files

**Comment by rzhao271** [comment]
Both me and @lancewl aren't really sure about this. Adding to backlog candidates.

@lancewl also mentioned that if the snippets do get merged, we'd have to figure out a way to handle conflicts.

If you want the snippets merged, 👍 this issue and comment on how the snippets should be merged in case of conflicts!
If you don't want the snippets merged, 👎 this issue!

**Comment by tjones50** [comment]
I would think if there are conflicts, warn the user that the snippet files are invalid through a warning. 

If that's not feasible, then I would say the clearest thing to do would be ignore both snippets, since that would more clearly communicate to the user that something was wrong in my opinion. If just one or the other was used, then I think it would be less clear that there was a conflict. 

This feature would be a big help, to allow different snippet files to be combined easily, which is a big need for my friend's company. They use Atom at this point because VS Code doesn't support combining emmet snippet files.
