### ISSUE TITLE
getSession scope

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#117512]
Testing #117299

I don't totally understand how the scope list passed to `getSession` works. If it ends up calling `createSession` then it passes the scope there, which makes sense. But if `clearSessionPreference` is not set, and there is already a session for this auth provider, then it is returned whether or not it has the scopes that `getSession` requested.

If `clearSessionPreference` is set, and there are multiple accounts, then I get to pick an account that may or may not have the scopes that the extension requested.

What is the extension supposed to do if it gets a session that doesn't have the scope it needs?

**Comment by RMacfarlane** [comment]
Ah, the scope list is intended to act as a filter, so the return of `getSessions` should be only sessions that match those scopes. I'll try to make that clearer in the docs, but that's what should ensure that a call to `getSession` returns something with the right scopes.

Internally, when some other extension calls `getSession`, VSCode requests sessions from the provider that match those scopes, and then decides what to do with those matching sessions. If there's already a user preference for one it gets returned automatically, otherwise the quickpick is shown. So if `clearSessionPreference` is set, the options there are meant to already be filtered to the correct scopes

**Comment by RMacfarlane** [comment]
Do you think changing the param name to `scopesFilter` would help?

**Comment by roblourens** [comment]
I didn't realize that `getSessions` takes a parameter, because it didn't show up when I used the TS quick fix "implement interface". Not sure what happened there... That makes sense now, and the doc makes sense.

**Comment by roblourens** [comment]
Ok I think that I used "implement interface" on an old version of the API, then updated vscode.d.ts, then patched it up manually, so I never saw the parameter. Anyway, it's all good.
