### ISSUE TITLE
Support JSON Schema for YAML files

### ISSUE THREAD

**Issue by mohsen1** [microsoft/vscode#1176]
It's getting more common to use YAML for configuration. For example `docker-compose.yml` or Swagger files are usually written in YAML. The JSON Schema based autocomplete for JSON files is a neat feature, please enable that for YAML files also.

**Comment by egamma** [comment]
@aeschli fyi

**Comment by mohsen1** [comment]
I'm eager to implement this. Can you point me to where can I start?

**Comment by aeschli** [comment]
Have a look at the JSON extension at (https://github.com/Microsoft/vscode/tree/master/extensions/json).
It's implemented as a [language server](https://code.visualstudio.com/docs/extensions/example-language-server)..
To try it out:
- open a VSCode window on the `extensions/json` folder, also run `npm install` in that folder, press the 'run' button in the debug viewlet
- a new VSCode window opens, where you can open a JSON file
- to debug the validation code, additionally open a VSCode window on the 'server' folder, and use the 'attach' option in the debug viewlet.
- Check out the JSONParser code that creates a AST out of the JSON document and contains the 'validate' functions that verify a node against the JSON schema.

**Comment by djabraham** [comment]
@mohsen1 Have you done any work in this regard yet?

**Comment by mohsen1** [comment]
@djabraham no. Never found the time to do this

**Comment by djabraham** [comment]
### I Friken Love YAML
..so I gave it a try.

https://github.com/djabraham/vscode-yaml-validation

https://marketplace.visualstudio.com/items?itemName=djabraham.vscode-yaml-validation

Uses the well known js-yaml parser with some TS types added, converts the returned structures to their JSON AST Equivalent, and then uses the standard JSON validation already built into VS Code. The excellent example cited above, is actually the source for that validation. 

This still needs some work, because the completions aren't being returned. But basic validation seems to be working. I will put some more time into it, when I can.

![screen shot 04-21-16 at 08 31 pm](https://cloud.githubusercontent.com/assets/4002604/14729716/65c94ee8-080e-11e6-8d6c-174ae252107d.PNG)

![screen shot 04-21-16 at 08 30 pm](https://cloud.githubusercontent.com/assets/4002604/14729711/5bda5576-080e-11e6-8f9f-192381259d35.PNG)

**Comment by aeschli** [comment]
@djabraham Awesome! Let me know if I can help!

**Comment by adamvoss** [comment]
@djabraham Thanks for showing this is possible!!

I wanted to add more functionality, but thought more good could come long-term with less forking.  The result was that I wrote [**vscode-yaml** (marketplace)](https://marketplace.visualstudio.com/items?itemName=adamvoss.yaml) [(GitHub)](https://github.com/adamvoss/vscode-yaml).

From the user perspective, I believe it provides all the functionality of **vscode-yaml-validation** plus:
  + better validation handling of null values
  + document symbol search (ctrl+shit+o)
  + _description_ hover information (when provided by schema)
  + document formating

I kept the same design decision to use the `json.schemas` setting key, so it should function as a drop-in replacement for **vscode-yaml-validator**.

Sadly, no completion in this extension either.  It was more-or-less working, but all the suggestions generated JSON.  While the JSON was valid YAML, it was not what anyone would want, so I disabled it.  My determination was that it would be best to write the suggestion code from scratch rather than trying to "patch" the code from **vscode-json-languageservice**.  I spent more time on this than I anticipated and I'm not sure I am not sure I will ever get around to completion. (PRs welcome of course).

Out of convenience it forks [**vscode-json**](https://github.com/Microsoft/vscode/tree/master/extensions/json), which is just the piece that wires the service to the VS Code client.  It takes a source-level dependency on [**vscode-json-languageservice**](https://github.com/Microsoft/vscode-json-languageservice/) to be access some internal types.  Otherwise, it doesn't fork its dependencies.  This caused submitting one upstream bug fix Microsoft/vscode-json-languageservice#7 and I have submitted the scalar classification code written for this to the upstream parser library possible future inclusion (mulesoft-labs/yaml-ast-parser#14).

**Comment by djabraham** [comment]
@adamvoss 

I like the fact that validation is integrated with completion and formatting. That makes perfect sense. It's good to see major progress, cause I love the YAML format. Especially for schema files and Kubernetes configs. 

One Q, do you plan to eventually add support for multiple yaml (concatenated) files? That seems to be a major pain point for advanced users. I started restructuring the repo in another branch, per the latest JSON validation project and the MS example for newer Language Server; but a new position currently demands focus and I kept putting it off. 

https://github.com/djabraham/vscode-yaml-validation/issues/2

Thanks regardless, and nice work!

**Comment by adamvoss** [comment]
@djabraham Thanks!  To avoid spamming this thread, I'll respond on your linked issue.

**Comment by purefan** [comment]
Good stuff! My use-case is however slightly different, Im looking for a serverless intellisense formatter, its basically yaml + keywords that start with `!Ref`, for example:
`Timeout: !Ref DefaultLambdaTimeout`

Is there a quick way to add this to the current yaml formatter?

**Comment by adamvoss** [comment]
@purefan see adamvoss/vscode-yaml#16, specifically [this comment](https://github.com/adamvoss/vscode-yaml/issues/16#issuecomment-337763279).

**Comment by Dominik-K** [comment]
FYI: Another option would be the [YAML Support by Red Hat](https://github.com/redhat-developer/vscode-yaml) extension. The underlying [yaml-language-server](https://github.com/redhat-developer/yaml-language-server) integrates all schemas from the [JSON Schema Store](http://schemastore.org/json/). Kubernetes schema is currently [included from a Gist](https://gist.github.com/JPinkney/ccaf3909ef811e5657ca2e2e1fa05d76#file-openshift_schema_all-json).

@adamvoss @djabraham You want to share forces with them, maybe?

**Comment by aeschli** [comment]
No plans on our side to add this functionality given that there are extensions implementing it already. I'll continue to open up the [vscode-json-languageservice](https://github.com/microsoft/vscode-json-languageservice) so it can also be used for other parsers that the JSON parser. If there's anything missing please file issues!
