### ISSUE TITLE
Cell toolbar is sometimes hard to click

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#117618]
The toolbar has been shifted up a bit and is half outside of the cell, but only shows up when the cursor is over the cell. So if I mouse down onto the cell to get to it, my cursor is in the bottom half of the toolbar by the time it shows up. And if I try to mouse up into it, I have to be careful that my cursor doesn't go outside of the toolbar to the left. 

We could fix it by shifting things so that the space between cells belongs to the cell below instead of the one above. But this would probably have weird effects for the insertion toolbar.

https://user-images.githubusercontent.com/323878/109055137-9fe83f00-7693-11eb-8e18-0149ebb72fb3.mp4

**Comment by misolori** [comment]
I wonder if could add some padding around the toolbar, while keeping the current dimensions/position, to increase the hit area?

**Comment by roblourens** [comment]
We still can't hover it while it's invisible, since it's visibility is based on hovering the cell, and it's outside of the cell.

**Comment by misolori** [comment]
yea, here you can see why we're running into the issue:

![image](https://user-images.githubusercontent.com/35271042/109205737-de493100-775b-11eb-8f62-1d997f4f5d28.png)

Green = bottom toolbar
Red = cell area

I think if we make the margins in between the cells part of the top cell, that might help here?

**Comment by roblourens** [comment]
Yeah, then if you hover the area between, you will get both the insertion toolbar and the cell toolbar, which is probably fine, if it's ok visually, but I don't know what happens when they run into each other. Currently when you hover a cell you get the cell toolbar on top and the insertion toolbar below, which is nice and symmetrical.

**Comment by misolori** [comment]
Let's try and tackle this next iteration because it will require more tweaking than we'd want to to introduce during endgame. 

## Current

Currently if you anywhere outside of the red area, the cell toolbar goes away because the next cell takes over

![image](https://user-images.githubusercontent.com/35271042/109231178-ef556a80-777a-11eb-834e-80486c13b42a.png)



## Goal

Could we add a ~6px buffer around the edges of this cell to add a bit more guard rails? This is the exact amount before it runs into the above bottom cell toolbar

![image](https://user-images.githubusercontent.com/35271042/109231194-f5e3e200-777a-11eb-926a-934892429059.png)

**Comment by roblourens** [comment]
This works better if I use opacity instead of visibility on the toolbar, so I can hover the invisible toolbar. Will wait for April though.
