### ISSUE TITLE
Max 100 files Push to GitHub - divide into segments if larger.

### ISSUE THREAD

**Issue by BryceMorrison** [microsoft/vscode#117625]
Issue Type: <b>Feature Request</b>

The GitHub uploads have a maximum of 100 files per upload.  This low-tech VSC platform does not (yet) adapt to that maximum.  I imported the files needed for a composer project for Facebook and Google Login, and the numbers were just over 11,000 files.  I needed to select a small segment at a time, with about 38 files per page, or twice as many if I scroll down and guessed at the <100 file mark.  This is a waste of time.  If I could select everything and upload all of the new files at once (even if 5,000 was the maximum that VSC could view at once), then it would make sense if Visual Studio Code could take that one "push" and automatically separate it into 100 files at a time, keeping the same push "description" for each of those uploads.

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.19041

**Comment by joaomoreno** [comment]
> The GitHub uploads have a maximum of 100 files per upload.

Can you show me where that limit is defined?

**Comment by BryceMorrison** [comment]
This issue is active. Please follow the steps I described before asking additional questions.
Step 1:  Try to upload 101 or more files using Github.com directly.  You should then see a warning that the maximum number of files has been reached.
Step 2: Use the VSCode application on Windows and try to "Commit" more then 100 files at once.  You would not see the warning at that particular stage. Do this for a few commits.  Then try to "Push" all of those commits.  You will then see an error.  You will be unable to go backwards, and the only solution is to remove that entire "source" (website) from your library and re-start the procedure for making a new connection to GitHub. ... and try not to screw that up ever again. 
This is frustrating. (Sorry - didn't mean to come out with subjective, emotional information, but I hope someone in GitHub and someone else with a VSCoder interface can solve that 100 file limit for pushes.)

**Comment by BryceMorrison** [comment]
This is an actual bug, and not a future-feature suggestion, so it's now on this ticket: https://github.com/microsoft/vscode/issues/118257

**Comment by joaomoreno** [comment]
@BryceMorrison says:

The GitHub uploads have a maximum of 100 files per upload. This low-tech VSC platform does not (yet) adapt to that maximum. I imported the files needed for a composer project for Facebook and Google Login, and the numbers were just over 11,000 files. I needed to select a small segment at a time, with about 38 files per page, or twice as many if I scroll down and guessed at the <100 file mark. This is a waste of time. If I could select everything and upload all of the new files at once (even if 5,000 was the maximum that VSC could view at once), then it would make sense if Visual Studio Code could take that one "push" and automatically separate it into 100 files at a time, keeping the same push "description" for each of those uploads.

Step 1: Try to upload 101 or more files using Github.com directly. You should then see a warning that the maximum number of files has been reached.  This problem (not a bug in this upload method) seems to be directly connected to the actual bug, which I'm reporting on for "Step 2."

Step 2: Use the VSCode application on Windows and try to "Commit" more then 100 files at once. You would not see the warning at that particular stage. Do this for a few commits. Then try to "Push" all of those commits. You will then see an error. You will be unable to go backwards, and the only solution is to remove that entire "source" (website) from your library and re-start the procedure for making a new connection to GitHub. ... and try not to screw that up ever again.

Side issue with 50% relation to this VSCode upload glitch (being unable to go backwards with cancelling commits from the push queue):  One of the pictures I'm attaching shows what happens when one of the files being uploaded via VSCode is larger than 100 megabytes.  That also throws a wrench in the push process, and there is no backing out of it.  I didn't take a screenshot of the commands that I followed regarding loading another version (or something like that wording... rolling back to a previous commit).

![2021-02-10_082655 delete file larger than 100 mb (no psd)](https://user-images.githubusercontent.com/77903570/110168507-285d9280-7dac-11eb-9914-fd1548f27ab9.png)

![2021-02-12_093107 first is git status](https://user-images.githubusercontent.com/77903570/110168437-0d8b1e00-7dac-11eb-8d50-3dc762a47705.png)
![2021-02-12_093041 git rebase --continue](https://user-images.githubusercontent.com/77903570/110168440-0e23b480-7dac-11eb-8380-fd416366fed2.png)

**Comment by joaomoreno** [comment]
This is not a limitation with VS Code, or even git. VS Code just uses whatever git you have installed in your system. And git is at the mercy of the server it uploads to, in your case GitHub.

Your issue is related to the specific use of LFS on GitHub: https://docs.github.com/en/github/managing-large-files/versioning-large-files. So I suggest you open a ticket against GitHub instead.

**Comment by BryceMorrison** [comment]
No, Joaomoreno.  The large file size is related to GitHub, but the upload crash is 50% to 100% VS Code related.
