### ISSUE TITLE
Custom markdown renderer: hidden cells are still rendered after workspace reload

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#117629]
- VS Code Version: 1.54-Insiders
- OS Version: macOS

<img width="2032" alt="image" src="https://user-images.githubusercontent.com/876920/109076337-4a219000-76af-11eb-9d4b-f29e6626c4ce.png">

1. Fold a markdown cell
2. Reload the window

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by mjbvz** [comment]
This is caused by the call to `initializeMarkdown`: 

https://github.com/microsoft/vscode/blob/a8c82939a7a9ab3ea1d44bf0d51bfc1a516c376f/src/vs/workbench/contrib/notebook/browser/notebookEditorWidget.ts#L1034

@rebornix `cell.metadata?.inputCollapsed` is false for all the cells when `initializeMarkdown` is called. Is there some other way to find out if the cell is visible here?

**Comment by rebornix** [comment]
`inputCollapse` is a different concept from folding, but good catch, it's not restored properly either.

I guess `initializeMarkdown` happens before we restore the view state. View state contains info about `inputCollapse` and also folding regions (or hidden regions), after seeing which we should send hide request to the webview to hide those no longer visible.

**Comment by rebornix** [comment]
Fixed via https://github.com/microsoft/vscode/pull/117723
