### ISSUE TITLE
Test failure peek view shows up at the same time as line decoration

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#117622]
Testing https://github.com/microsoft/vscode/issues/115769

Unfortunately I don't have really exact repro steps around this, but I've noticed that there's sometimes a line decoration that either pops up and disappears quickly, or remains there even when a peek view is already open:
![Screen Shot 2021-02-24 at 12 44 06 PM](https://user-images.githubusercontent.com/3672607/109063641-40436100-769e-11eb-86f6-bad69fb3ec4f.png)

**Comment by connor4312** [comment]
So, the line decoration should actually still be there. If the test runner providers an expected vs. output diff, we'll show that, otherwise we just show the same message.

However, gitlens' decorations overwrite the decoration it due to some css weirdness, so that could be causing the disappearence behavior.
