### ISSUE TITLE
[Feature Request] Feedback for contribution point "editor/title/run"

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode#117722]
_// This is a follow-up issue for https://github.com/microsoft/vscode/issues/114123_, cc @jrieken

Thanks to the team to provide a centralized contribution point for the `run` button. Here are some feedback for consideration.

- Show the keyboard shortcut in the dropdown menu?
- Considering another entry for `debug` (editor/title/debug)? In that case the user can just have one click if each contribution(run and debug) just has one entry.
- Just like what we have in the debug view, the title area can have a dropdown menu explicitly and VS Code can memorize the last choice. (But given the very limited area there, this might not be a good idea though)
  <img width="166" alt="Screen Shot 2021-02-26 at 8 41 08 AM" src="https://user-images.githubusercontent.com/6193897/109238388-6a1b9580-780e-11eb-8792-8b4c9408b87f.png">

**Comment by jrieken** [comment]
> Considering another entry for debug (editor/title/debug)?

Our idea is that the menu is used for run- and debug-commands

**Comment by jrieken** [comment]
//cc @weinand

**Comment by jabbalaci** [comment]
Now if I want to run my code, I need to click twice :( Previously one click was enough. Can you add a setting that sets a default behavior for the button? If you click on it once, "Run Code" should be the default. Clicking twice is a pain.

**Comment by jdneo** [comment]
The Java side also has a user mentioned about the [Clicking twice is a pain](https://github.com/microsoft/vscode-java-debug/pull/956#issuecomment-801577636)

**Comment by hisra015** [comment]
I'd love an option to revert back to the previous button. This new feature has not once worked properly for me because it closes just as fast as it opens by itself. Seems to be a bug that I have been tracking for the past few days.

**Comment by Parminder51** [comment]
Clicking twice really is a pain, would appreciate if a 'Select Default Option' was available for different languages.

**Comment by jabbalaci** [comment]
@Parminder51 "Happening in Python" : what do you mean? Do you have a link for more info?

**Comment by Parminder51** [comment]
@jabbalaci When I'm trying to click the run button, the context menu pops up. A few days back it would just run the file with the coderunner extension. Now I have to select again and again whether to run using the python extension or coderunner extension.
![Screenshot 2021-03-23 115059](https://user-images.githubusercontent.com/61777405/112102605-8670df00-8bce-11eb-90c5-3325d29bd92d.png)
![Screenshot 2021-03-23 115112](https://user-images.githubusercontent.com/61777405/112102611-88d33900-8bce-11eb-8b0e-a118fec20462.png)

**Comment by jabbalaci** [comment]
@Parminder51 OK, I misunderstood. When you wrote "Happening in Python", I thought a solution for Python was under way. Yes, I also noticed this double-click problem and it also bothers me. I hope there will be a solution for this soon.

**Comment by gjsjohnmurray** [comment]
For those of you with the problem, are those two contributions to the new `editor/title/run` menu coming from a single extension or two extensions? If two separate extensions, is it feasible to disable one for the workspace?

**Comment by codinginpython123** [comment]
I have the same problem with @Parminder51

**Comment by Parminder51** [comment]
@gjsjohnmurray Usually the Python extension's button is hidden if the Code Runner extension is enabled, and it was working fine. But now when you click on it, the context menu pops up. I hope to use the Code Runner extension but there is no way to remove the run button in the Python extension, I checked for it and found this. [https://github.com/microsoft/vscode-python/issues/6921](url).

**Comment by joaomoreno** [comment]
I suggest we agument toolbar submenu actions with some indicator that it's going to be a dropdown. This should help in the user's perception of what will happen when they click it.

For this specific toolbar submenu action, the Run, maybe it's best to further change it to behave like debug: a UI piece with two click zones, one for the default and another for the dropdown which, when selected, would run and change the default.

**Comment by lukepighetti** [comment]
This is ripe for a hotfix imho. I appreciate the forward looking ideas for how to improve this, but the consolidation is much worse than the previous version. I'd like the previous version back until the UX is ironed out.

**Comment by misolori** [comment]
Now that we have hover feedback on toolbar actions (via https://github.com/microsoft/vscode/issues/120226) I think it now makes sense to explore what adding affordances to split buttons could look like to improve their usability. Here are a few concepts:

<img width="500" src="https://user-images.githubusercontent.com/35271042/113203389-d845e480-9220-11eb-9c10-4c914fada2ef.gif">

<img width="500" src="https://user-images.githubusercontent.com/35271042/113203841-5f935800-9221-11eb-9371-0b95b156474d.gif">


![image](https://user-images.githubusercontent.com/22350/113105080-0e01b380-91b6-11eb-9448-f2f4f172fc88.png)

**Comment by lukepighetti** [comment]
Option 3

**Comment by jdneo** [comment]
Vote for option 3.

_The background color indicates that the `play` and `chevron-down` are in one group, while the different background color indicates that they have different functionalities._

**Comment by Tyriar** [comment]
I just pushed the new `DropdownWithPrimaryActionViewItem` to base:

https://github.com/microsoft/vscode/blob/main/src/vs/base/browser/ui/dropdown/dropdownWithPrimaryActionViewItem.ts

This powers the terminal's button in the same style:

![recording (31)](https://user-images.githubusercontent.com/2193314/115710102-d4404a80-a326-11eb-885f-58266e591c05.gif)

It's basically the 3rd option but with a negative left margin on the right button so that the 2 buttons are closer together like option 2, this is particularly important to help distinguish the related `v` icon for this case:

<img width="238" alt="Screen Shot 2021-04-22 at 4 55 39 AM" src="https://user-images.githubusercontent.com/2193314/115710253-fd60db00-a326-11eb-8a3b-2c2be6139657.png">

**Comment by weinand** [comment]
We might want to consider introducing a shortcut for the "default run action"; see #125401

**Comment by jrieken** [comment]
Not sure I understand... This is just a dynamic sub menu. Are you suggesting to add a keybinding to trigger a submenu (or its sole command if only one exists)?

**Comment by weinand** [comment]
Since the "split button" UI introduces the concept of a "default run action", it would be helpful if this "default action" would have a keybinding.

**Comment by weinand** [comment]
This feature request tries to improve the user experience for the recently added contribution point "editor/title/run".

![2021-06-15_16-34-59 (1)](https://user-images.githubusercontent.com/1898161/122072260-b27bb500-cdf7-11eb-8ef2-f53d9e3911f3.gif)

There are two pain points with the current UI of the contribution point:
- if there are more than two action contributions, two clicks are needed to trigger an action: the first click opens the drop down menu and the second selects the action from the menu.
- from the UI it is not obvious whether the "run" item is a single action or a dropdown with multiple actions. This makes the UI instable and requires close attention by the user in order to not forget the "second click".

The new split button (`DropdownWithPrimaryActionViewItem`) looks like a good way to address the pain points. 

![image](https://user-images.githubusercontent.com/22350/113105080-0e01b380-91b6-11eb-9448-f2f4f172fc88.png)

The split button has two click zones, one for the default (left) and another for the dropdown (right) which, when selected, would run and change the default.

Behavior:
- with a single action contribution the action would become the default and the drop down would be disabled.
- with two or more action contributions there are two option for the default:
  - no default and the user is required to open the drop down select and run an action
  - the first contributed action becomes the default automatically

**Comment by jrieken** [comment]
@weinand Please go ahead on this and let me know where I can help

**Comment by weinand** [comment]
@jrieken please provide code pointers

**Comment by weinand** [comment]
The split button in action:

![2021-06-30_18-10-21 (1)](https://user-images.githubusercontent.com/1898161/123995386-9159bd80-d9ce-11eb-8665-38e866a4536a.gif)

**Comment by weinand** [comment]
@isidorn raised the question whether selecting a drop down menu action should only select or select and execute the action. 
The former would again require two clicks. The latter only one but its behavior might be a bit surprising.

**Comment by isidorn** [comment]
I was just concerned if we have other places in our UI where selecting something also runs it.
Since the debug dropdown behaves different maybe I am just used to that selection only selects.

I would still slightly lean towards that selection should not run because:
* I think users will not often switch between the options
* It is cleaner and aligns better with the rest of our UI

**Comment by weinand** [comment]
Another thing to consider: if the actions in the drop down menu do not have different icons, then selecting them without executing them will not have any visual effect on the split button.

**Comment by misolori** [comment]
I think the dropdown in the debug view is visually different enough that it won't cause that confusion:

<img width="220" alt="CleanShot 2021-06-30 at 10 46 56@2x" src="https://user-images.githubusercontent.com/35271042/124007776-8bdd8280-d990-11eb-934a-4bb3485239ce.png">

Because we also use the same interaction of selecting a dropdown to perform an action in the terminal:

<img width="288" alt="CleanShot 2021-06-30 at 10 48 07@2x" src="https://user-images.githubusercontent.com/35271042/124007893-aca5d800-d990-11eb-8832-e5cb37f7f4d3.png">

**Comment by isidorn** [comment]
@misolori I was not aware that we also do this in the terminal.
Then I think we should go with this approach here also.

**Comment by weinand** [comment]
I've released the feature. Please try it in the next Insiders.

**Comment by jdneo** [comment]
@weinand 

Looks good! Just one bug I found, arrows are appended if user select through dropdown


https://user-images.githubusercontent.com/6193897/125407416-6e76d280-e3ec-11eb-913a-1527bf952a32.mp4

Version: 1.59.0-insider (user setup)
Commit: f6df685c62da50886f7540cbf768ed4333d58bea
Date: 2021-07-13T05:12:59.073Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19043

**Comment by weinand** [comment]
@jdneo interesting. I'm not seeing this on with Mock Debug... Will investigate with Java

**Comment by weinand** [comment]
Yes, I can reproduce with the Java extension.

**Comment by weinand** [comment]
@jdneo I've fixed the problem that you've spotted.
Please verify with next Insiders.

**Comment by andreamah** [comment]
I noticed some weird behavior with which title is shown on the button. To replicate:

1. Open the [webview sample](https://github.com/microsoft/vscode-extension-samples/tree/main/webview-sample) from `vscode-extension-samples` 
2. Edit `package.json` to use the contribution point:
```
"menus": {
    "editor/title/run": [
        {
	        "command": "catCoding.start"
        },
        {
	        "command": "catCoding.doRefactor"
        }
    ]
}
```
3. Launch the extension and ensure that the button is currently showing "Do some refactoring". Using the "start a cat coding session" option in the dropdown does not cause the button show the text for "start cat coding session", but it just stays the same instead. 🐛 
4. Also, if you click the "start cat coding session" option again with the window still open, it now shows the right text on the button 🐛

**Comment by jdneo** [comment]
Hi @weinand thank you for the fixing. Now the dropdown arrow works pretty well.

There is another problem though, after switching the active run action via the arrow, then the run/debug button itself becomes unclickable.

**Comment by weinand** [comment]
@andreamah I can reproduce the problem you are seeing. It only occurs if the command has no icon (which is not the typical scenario for a editor toolbar icon). I'll investigate...

**Comment by weinand** [comment]
@andreamah The issue is a cyclic context JSON that gets serialized over to the extension host via rpc.
@jdneo I've added a workaround and I could no longer reproduce the problem in the webview sample and in the Java extension.

**Comment by jdneo** [comment]
Thank you @weinand, I just played it in the newest insider, everything works great now!
