### ISSUE TITLE
Errors in compound config references

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#117785]
- Open an empty `.vscode/launch.json` file
- Paste this text into it:

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "pwa-node",
            "request": "attach",
            "name": "a",
            "port": 9229,
        },
        {
            "type": "pwa-node",
            "request": "attach",
            "name": "b",
            "port": 9230,
        },
        {
            "type": "pwa-node",
            "request": "attach",
            "name": "c",
            "port": 9231,
        },
    ],
    "compounds": [
        {
            "name": "Compound",
            "configurations": [
                "a",
                "b",
                "c"
            ]
        }
    ]
}
```

- Get errors in the compound config that those configs don't exist
- Close and reopen launch.json
- The errors are gone

From experimenting, seems like configs are only checked in compounds when the file opens, and not when it changes.

![image](https://user-images.githubusercontent.com/323878/109340502-f4b7c100-781d-11eb-865f-f7631aa76bb6.png)

**Comment by isidorn** [comment]
@roblourens after you paste I get the errors, but after I do any other change the errors go away.
I debugged and we do update the `jsonSchema` properly on each file change.
However the problem here seem to be that the `jsonSchema` does not re-validate the errors on `jsonSchema` re-registration.
@aeschli maybe this is an issue on your end? You should re-validate the errors on a `jsonSchema` gets re-registered

**Comment by roblourens** [comment]
I thought that when I was trying this, I was also making other changes and the errors did not go away. But I'm not sure. Sounds like you understand it though.
