### ISSUE TITLE
Bad debugger suggestions for pwa-node

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#117779]
I tried debugging the node sample app in Dev Containers without having js-debug activated and the following message showed up:
<img src="https://user-images.githubusercontent.com/7199958/109334031-0779c800-7815-11eb-9cbd-b987994fab53.PNG" alt="dialog saying no debugger for pwa-node installed" width=480>

However, when I click on the leftmost button to install extensions, I get the following query (`tag:debuggers @sort:installs`) and suggestions, none of them having to do with js or node debugging:
<img src="https://user-images.githubusercontent.com/7199958/109334030-06e13180-7815-11eb-9e6b-8e32bf838cc9.PNG" alt="bad query" height=600>

Searching just 'pwa' helped me realize that I forgot to activate js-debug, and searching 'pwa-node' yielded no results.

**Comment by connor4312** [comment]
This suggestion should not generally be relevant since js-debug is built-in, and built-in extensions do not show in results. @rzhao271 do you use the js-debug nightly?

I've seen this sometimes where js-debug is not installed in remotes, but I assumed this was because I use the nightly extension and have the built-in one disabled.

**Comment by rzhao271** [comment]
@connor4312 I don't remember the exact state I was in, but I had the nightly version installed by that point. It was likely that I had both the nightly and stable versions disabled by accident, though I still felt confused by the results under `tag: debuggers sort:@installs`. I'm wondering if there's any way to add an `OR` into that query so that it can also list relevant disabled installed extensions?

**Comment by connor4312** [comment]
It will usually list installed extensions (e.g. it shows the Debugger for Chrome in your screenshot), but not built-in extensions.

Giving to Sandeep who owns this but not sure it's worth fixing just for people using js-debug nightly.

**Comment by sandy081** [comment]
Query to market place shows all result extensions in Marketplace - we do not filter built in extensions if they are also available in Marketplace. For eg., searching for `pwa` shows both stable (which is builtin) and nightly js debugger extensions 

<img width="565" alt="image" src="https://user-images.githubusercontent.com/10746682/110107501-3eb71e80-7dab-11eb-8336-6267eb8e8d52.png">

It seems the query `tag:debuggers @sort:installs` is also showing both those extensions but they are not shown on the top but somewhere in the middle due to sorting criteria

<img width="525" alt="image" src="https://user-images.githubusercontent.com/10746682/110108151-1f6cc100-7dac-11eb-82c3-8cb75a8f3319.png">

<img width="521" alt="image" src="https://user-images.githubusercontent.com/10746682/110108216-2e537380-7dac-11eb-9d9e-b13cbde27203.png">

@connor4312 Moving this back to you if you would like to change the filter to get expected results

**Comment by connor4312** [comment]
Ideally we could have metadata for packages in the marketplace to show the run with the right debug type... but this is not currently possible.
