### ISSUE TITLE
Case-renamed file shows up twice in Search

### ISSUE THREAD

**Issue by sdegutis** [microsoft/vscode#117778]
Issue Type: <b>Bug</b>

1. Let VS Code extract class Work into Work.js
2. Rename Work.js to work.js
3. Search for something that's in work.js
4. Notice that both Work.js and work.js show up with identical results

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:45:54.515Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3740QM CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (4.18GB free)|
|Process Argv|-psn_0_6870669 --crash-reporter-id aa77e851-0fc5-45a8-b2b6-6d32c4e1f3ee|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244cf:30256637
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubset:30264244
pythontbcf:30260844

```

</details>

**Comment by roblourens** [comment]
@bpasero this seems to repro on mac, and not linux. Essentially getModels returns a model with a uri that has the old casing here: https://github.com/microsoft/vscode/blob/c41922bf4270bcc075850ead9148b64cd29b61fc/src/vs/workbench/services/search/common/searchService.ts#L426-L426

I think it's related to this check: https://github.com/microsoft/vscode/blob/763e089ae54efdc3e6382699e7391c6df8b6f2be/src/vs/workbench/services/editor/browser/editorService.ts#L332-L332

and depends on whether the fs is case sensitive. Is the model service wrong, or is there another way that I should be getting a list of open editors with up to date URIs?

**Comment by bpasero** [comment]
@roblourens this is a consequence of us introducing a canonical URI a couple of months ago to solve various issues where people were able to open the same file with different casing in different editors. Once a URI is introduced into the system e.g. as an editor, we keep the casing of that URI for as long as VSCode is running. As such, after renaming an editor, the model will still have the old casing and not change. Models have no way of changing their URI so if we didn't do this, you would loose the entire model including edit history etc. 

What we do on a rename is basically just updating the editor label, but nothing changes within, the model is still the same. For that reason we introduced the notion of an associated resource, so that we can distinguish between the canonical one and the associated one (see the [`EditorResourceAccessor`](https://github.com/microsoft/vscode/blob/763e089ae54efdc3e6382699e7391c6df8b6f2be/src/vs/workbench/common/editor.ts#L1332-L1332) for an explanation). 

I think the right fix in search land is to use the `IURIIdentityService` to de-dupe search results. You probably still want to prefer hits from an opened editor over what is on disk to support searching in dirty files.

**Comment by roblourens** [comment]
That works for deduping. It still shows the old name. Looks like we need to use `EditorResourceAccessor` for this. @isidorn search is just using a ResourceLabel here, does it need to be aware of this or do I need to use it differently?

**Comment by bpasero** [comment]
@roblourens resource label will not be able to help you because the `EditorInput` holds the associated resource. When search iterates over the opened models it would have to use the `EditorResourceAccessor` to get the associated resource. I think currently search is not iterating over the editors but over models.

**Comment by roblourens** [comment]
So should my process be to check the models, search for an open editor with that same URI, get its editor input, and run that through `EditorResourceAccessor`? Or should I go the other way (open editors -> find a model with that URI)?

**Comment by bpasero** [comment]
@roblourens wouldn't it be more user friendly if search was iterating over the opened editors to find models instead of going onto the raw models? Because in theory there could be model in memory that is not opened as an editor so you may show results for something that is not opened? Not sure wether this can happen today.

Here is an idea (1):
* iterate over all opened editors and collect a map of canonical + associated resources
* iterate over the editor models as you do today but only pick the ones that match the canonical resource
* use the associated resource as label

There is one gotcha to this approach: you will get `undefined` for diff editors because those do not have a `resource` at all since they are composed of 2 editors within.

Here is another idea (2):
* you keep doing what you do today by searching in any text model
* you also build a map of canonical resource => associated resource by iterating over all opened editors
* when deciding on the label you look into the map first

Note: even if you do this it is possible that the user has opened the same canonical resource with 2 different associated resources. So it is possible that you show the search results in one form and it does not match the editor in another group that uses a different form. The idea is that you can have many different associated resources for the same canonical resource. But I think that is fine and not a big deal.

**Comment by bpasero** [comment]
As a helper method, [`IEditorService#getEditors()`](https://github.com/microsoft/vscode/blob/bb8b693479b074d3a5eb9f36ab8ca69f25a5a29b/src/vs/workbench/services/editor/common/editorService.ts#L168-L168) provides you with access to all opened editors across all groups. If we think we should have another method to help search here, I am not opposed to adding one to the service.

**Comment by roblourens** [comment]
Am basically doing #1 now, thanks for the advice
