### ISSUE TITLE
Blurr problem

### ISSUE THREAD

**Issue by rsds8540** [microsoft/vscode#117772]
![Screenshot 2021-02-26 203309](https://user-images.githubusercontent.com/33702314/109316708-e85d5380-7871-11eb-8aee-33eaa46bbd69.png)
![Screenshot 2021-02-26 203309](https://user-images.githubusercontent.com/33702314/109316840-07f47c00-7872-11eb-84e3-16387c9e4bc9.png)
every text going blurred with out doing anything.
The problem is occurring right after installing.
Nothing is changed from settings or anywhere.
problem is only in my pc, in other pc its working fine.

**Comment by deepak1556** [comment]
Can you check if the issue persists when starting with `code --disable-gpu`

**Comment by rsds8540** [comment]
> Can you check if the issue persists when starting with `code --disable-gpu`

where to write this code(code --disable-gpu)?

**Comment by rsds8540** [comment]
hey I dont want to disable my high quality graphics for this stupid problem.
Just solve this problem. Make this app working in fine in every condition.

**Comment by deepak1556** [comment]
The rendering support comes from chromium runtime, if gpu based compositing doesn't work for a certain version of the runtime the switch `--disable-gpu` helps the application to fallback on software based compositing. There is not much we can do here, can check back once a newer version of the runtime is picked up. Instead of using the command line switch you can set the flag via settings following https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration.

>  I dont want to disable my high quality graphics

The switch doesn't disable anything on your gpu, it is only meant to tell vscode application what to use.

Can you try the flag and confirm if it helps, thanks!
