### ISSUE TITLE
not able to connect to the extention market place

### ISSUE THREAD

**Issue by himanshu1998-coder** [microsoft/vscode#117777]
Issue Type: <b>Bug</b>

not able to connect to the extension market place

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.87GB (1.82GB free)|
|Process Argv|--crash-reporter-id 5b0d72f9-a22d-4a8d-9938-c460c7fd27d9|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
simple-react-snippets|bur|1.2.3
bracket-pair-colorizer|Coe|1.0.61
javascript-ejs-support|Dig|1.3.1
vscode-html-css|ecm|1.10.2
vscode-toggle-column-selection|eri|1.0.6
file-icons|fil|1.0.28
auto-close-tag|for|0.5.9
stylelint-plus|hex|0.52.12
vscode-language-babel|mgm|0.0.30
jupyter|ms-|2021.2.576440691
color-highlight|nau|2.3.0
LiveServer|rit|5.6.1
JavaScriptSnippets|xab|1.8.0

</details>

**Comment by sandy081** [comment]
Please follow these steps

- Help -> Toggle Developer Tools -> Network
- Then check for any network failed requests while browsing and installing the extensions if found all requests fails then its probably a proxy or DNS issue at your end.
- To confirm its a DNS issue check if you can access this page https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default, if you cannot please try configuring your DNS like pointing to 1.1.1.1 as suggested here? https://1.1.1.1/dns/. Otherwise please contact your network administrator.
- If it is not a network issue, please share the logs from the following locations
    - Help -> Toggle Developer Tools -> Console
    - View -> Command Pallette... -> Toggle Shared Process -> Console
    - View -> Open View… -> Log (Shared)
    - View -> Open View… -> Log (Window)
