### ISSUE TITLE
registerSingleton should throw for registering under same identifier

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#117769]
We use `registerSingleton` more and more and it is quite easy to end up with registering the same service twice because we have a web and a desktop environment.

Quickly throwing an assertion into [`registerSingleton`](https://github.com/microsoft/vscode/blob/b2e68d70b8dd30b565e6b181fac6ec47b7e00f3d/src/vs/platform/instantiation/common/extensions.ts#L18-L18) to throw when a singleton has already been registered under a certain ID already indicates 2 offenders: `configurationResolverService` and `searchService`

This can have the negative side effect that you end up with the browser version of the service even though you run in desktop.

I would suggest to throw when we encounter this and fix the 2 instances from the owners.

**Comment by bpasero** [comment]
I have a change ready to fix the 2 offenders and will push in debt week.

**Comment by jrieken** [comment]
Started to look into this. While I am making the adoption for services in the web worker extension host I am actually not convinced anymore. For instance, we have `ExtHostOutputService` (defined in extHost.common.services.ts) and that service is perfectly fine and valid. However, in the node extension host we re-define it with a more specific service and that's how services are meant to work. Moving the registration of the generic output service into extHost.worker.services.ts is wrong because it isn't specific to the worker extension host. 

Maybe `registerSingleton` is a bad name and it should be more like 'registerGlobalService'. Also, you are only registering a constructor, so little harm is done if you do it N times. Other improvements could be to add a 'closed' state so that we bail out when services get registered after `getSingletonServiceDescriptors` has been called. Yet another check that we should enforce is that `createDecorator` is only be called once per id - because that's more wrong (we are actually graceful but maybe should be strict)

**Comment by bpasero** [comment]
@jrieken yeah I think it is totally fine if the one registration overwrites the other as long as you can ensure that the correct one wins  depending on context. I was more worried about the scenario that the more specialized implementation would get overwritten by a generic one (e.g. web overwriting native) but maybe that is not happening.

One of the reasons why I brought this up is a pattern that I am not a big fan of: in our main workbench dependency files we have a mix of imports:
* imports of a service that call `registerSingleton` top level (e.g. [here](https://github.com/microsoft/vscode/blob/3021226eefdfc149c0b7b7f3a4a162524ada01e6/src/vs/workbench/workbench.common.main.ts#L94-L94))
* imports of services that do not call `registerSingleton` where we have to do so (e.g. [here](https://github.com/microsoft/vscode/blob/3021226eefdfc149c0b7b7f3a4a162524ada01e6/src/vs/workbench/workbench.common.main.ts#L126-L126))

Typically all the services defined in `platform` do not call `registerSingleton` top level due to fear that they might end up in different contexts (e.g. shared process or main) where we do not call `getSingletonServiceDescriptors`). I would like to end up with a model where every service calls `registerSingleton` and we end up just importing them all from the entry files.

**Comment by jrieken** [comment]
closing without action
