### ISSUE TITLE
Notebook multiselect - no visual indicator on markdown headers

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#117706]
Verifying https://github.com/microsoft/vscode/issues/117449

1. Open `endgame.github-issues` in the vscode repo
2. Multiselect across some of the markdown headers

![Screen Shot 2021-02-25 at 1 03 48 PM](https://user-images.githubusercontent.com/3672607/109216891-f758de80-7769-11eb-97ef-301ac9c286b8.png)

If I put them into edit mode, then I see the background change on multiselect

**Comment by rebornix** [comment]
@RMacfarlane I guess you don't see this issue when commenting `"notebook.experimental.useMarkdownRenderer": true,` out from the workspace setting?

**Comment by RMacfarlane** [comment]
Yeah, that's correct!

**Comment by mjbvz** [comment]
The root cause is that the `monaco-list-row` for webview backed markdown cells has a height of zero. This element gets the correct background color during selection, but is not visible due to the height. We have zero height so that you can click through to the webview instead of to the cell

@rebornix I will prototype telling the cell in the webview if it is selected or not. Then we can add styling inside the webview to show selection state
