### ISSUE TITLE
Duplicated decoration ids

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#117881]
related to https://github.com/microsoft/vscode/issues/117769

We have places that create a service decorator, via `createDecorator`, for an identifier that has been used already. The problem with that is the the id is the actual identifier, not the object instance. This enables potential for service conflicts, esp. when different interfaces use the same name. Conflict I have found

* [x] `themeService` defined [here](https://github.com/microsoft/vscode/blob/082af46e6657da59c6df5a15eb40de2afb79cd46/src/vs/platform/theme/common/themeService.ts#L16) and [here](https://github.com/microsoft/vscode/blob/c6a1eda3315c3411fbc967aa9c72ecf9ece39cbb/src/vs/workbench/services/themes/common/workbenchThemeService.ts#L13), different interface is used
* [ ] `configurationService` defined [here](https://github.com/microsoft/vscode/blob/ab6a005750651e6132d54aabae2d2f2469a593aa/src/vs/platform/configuration/common/configuration.ts#L16) and [here](https://github.com/microsoft/vscode/blob/3835563e123aefda53337fce7b215cc81a535047/src/vs/workbench/services/configuration/common/configuration.ts#L48)
* [x] `layoutService` defined [here](https://github.com/microsoft/vscode/blob/763e089ae54efdc3e6382699e7391c6df8b6f2be/src/vs/workbench/services/layout/browser/layoutService.ts#L14) and [here](https://github.com/microsoft/vscode/blob/763e089ae54efdc3e6382699e7391c6df8b6f2be/src/vs/platform/layout/browser/layoutService.ts#L10)
* [x] `nativeEnvironmentService` defined [here](https://github.com/microsoft/vscode/blob/0593b3eb54b0c5a27836618a56c151de73814dc2/src/vs/workbench/services/environment/electron-sandbox/environmentService.ts#L11), [here](https://github.com/microsoft/vscode/blob/9de38fc9a8058f0b42057bb0076d989455b58edc/src/vs/platform/environment/electron-main/environmentMainService.ts#L14), and [here](https://github.com/microsoft/vscode/blob/8c8ab33b79d4d153e36e5e62364443fdca2b12e0/src/vs/platform/environment/common/environment.ts#L11)
* [x] `environmentService` defined [here](https://github.com/microsoft/vscode/blob/0593b3eb54b0c5a27836618a56c151de73814dc2/src/vs/workbench/services/environment/common/environmentService.ts#L12) and [here](https://github.com/microsoft/vscode/blob/8c8ab33b79d4d153e36e5e62364443fdca2b12e0/src/vs/platform/environment/common/environment.ts#L10) 
* [ ] `extensionManagementService` defined [here](https://github.com/microsoft/vscode/blob/afd102cbd2e17305a510701d7fd963ec2528e4ea/src/vs/workbench/services/extensionManagement/common/extensionManagement.ts#L27) and [here](https://github.com/microsoft/vscode/blob/22e02e008049622519e11041550c34774c71128d/src/vs/platform/extensionManagement/common/extensionManagement.ts#L207)

@bpasero start with you because it seems to be a pattern that you have been using, e.g have `XYZService` which is redefined as `IWorkbenchXYZService`. This needs explanation but seems fishy, e.g the first service interface should already be exhaustive and not rely on an extension that comes from the side

**Comment by bpasero** [comment]
@jrieken I am fine changing the identifier to a unique value (e.g. `layoutService` => `workbenchLayoutService`), but reality is that we have some services that are more powerful in certain contexts than others. For example, we need the simple layout service in monaco editor standalone as well as workbench, but need more methods only in workbench. Same goes for environment service which is used in almost all contexts but with different properties.

To clarify: it is still ok that 1 service implements 2 service interfaces (e.g. the layout service of the workbench implementing the simple one needed for monaco editor and the more complex one needed for workbench)?

**Comment by jrieken** [comment]
> To clarify: it is still ok that 1 service implements 2 service interfaces

I think it's fine as long as the relation between interface/type and decorator-id is 1 to 1. Personally, I am not the biggest fan of these inheritance solutions because it often feel kitchen-sink'ish, e.g what's the different between `ILayoutService#container` and `IWorkbenchLayoutService#getWorkbenchContainer` or why is `IWorkbenchLayoutService#onDidChangePanelPosition` not in the `IPanelService` but that's another topic. 

On the layout service specifically: I actually don't see how/where it used in monaco land. I see an implementation but not consumer.

**Comment by bpasero** [comment]
@jrieken yeah bad example, it is used for quick open and that is used in monaco editor.

**Comment by bpasero** [comment]
Layout service and environment service now have distinct service identifiers (also caught one in the remote server).

> e.g what's the different between ILayoutService#container and IWorkbenchLayoutService#getWorkbenchContainer

I got rid of `IWorkbenchLayoutService#getWorkbenchContainer`

> why is IWorkbenchLayoutService#onDidChangePanelPosition not in the IPanelService but that's another topic.

Because that is not the right layer of concerns. We have the layout service managing the containers of the big pieces and specific services to handle what is going on within these pieces. As such, panel service is for managing the content of the panel but not the panel itself. Similarly we have a viewlet service for the sidebar.

**Comment by aeschli** [comment]
There's only one `themeService` but with two interfaces. The basic `IThemeService` defined in platform covers color themes, and the `IWorkbenchThemeService` in workbench also includes icon support. The separation allows the editor to use the `IThemeService` and to have it's own service implementation for the standalone editor.

I find that to be clean design and proper use case for our layered system. The same service can have multiple interfaces.

The question is, is the id a decorator id or a service id?

I always thought it's a service id. In `ServiceCollection` it's called `ServiceIdentifier` and it's there to have only one service instance per service.

Maybe we need to separate the service id from decorator id. But I'm not sure what the decorator id is needed for,

@jrieken Is the concern that we have the same service id literal at multiple places? Would it make sense to allow the following:
Instead of
`export const IWorkbenchThemeService = createDecorator<IWorkbenchThemeService>('themeService');`
have
`export const IWorkbenchThemeService = createDecorator<IWorkbenchThemeService>(IThemeService);`

**Comment by jrieken** [comment]
> The same service can have multiple interfaces.


There is a 1 to 1 mapping between service interface and service decorator. In fact the decorator is "workaround" for not being able to reference an interface as runtime-type. So, "yes" it is perfectly fine to have two theme services but the decorator should represent that with their ids.

**Comment by aeschli** [comment]
So I assume I change to
`export const IWorkbenchThemeService = createDecorator<IWorkbenchThemeService>('workbenchThemeService');`

When I register my service I do `registerSingleton(IWorkbenchThemeService, WorkbenchThemeService);`
I want to register the same service instance for the interface `IThemeService`. How would I do that?

**Comment by jrieken** [comment]
That's a very good point @aeschli... You could in theory register an instance of the collection directly but you cannot achieve it with the registerSingleton (which is our preferred). 

I'd say that you have successfully changed my mind about this. I still don't like that we have this https://github.com/microsoft/vscode/blob/cadabab73fef89fe0c4bfe23b5a33cd58e39ea9c/src/vs/platform/instantiation/common/instantiation.ts#L139-L143

The `createDecorator` is actually a `getOrCreate`-function. So, maybe we change this so that an existing identifier can be "type refined". I understand your problem as being a typing problem, in one world `themeService` is an identifier for `IThemeService` and in the other world the same identifier stands for `IWorkbenchThemeService`. Since the `<T>` in service identifiers is for TS only we could add a function to refine the type of an existing service id. Something like this

```ts
export const IWorkbenchThemeService = refineServiceIdentifier<IWorkbenchThemeService>(themeService);
```

That refine-function would not do anything except for typing gymnastics

```ts
export function refineServiceIdentifier<T1, T2 extends T1>(serviceId: ServiceIdentifier<T1>): ServiceIdentifier<T2> {
	return <ServiceIdentifier<T2>>serviceId;
}
```

@aeschli Would that work for you?

@bpasero How did you do this? Are there now two instances for your services?

**Comment by bpasero** [comment]
@jrieken yeah I am actually just "lucky" that my 2 services (layout and environment) are instances that I set directly into the collection, e.g. here:

https://github.com/microsoft/vscode/blob/5510ee9c51d94a871626a61a1c944a70acc123ec/src/vs/workbench/browser/workbench.ts#L178-L180

and here:

https://github.com/microsoft/vscode/blob/8c1bfcb569acf3d6138a49bbba42c61cb34d0d0f/src/vs/workbench/electron-browser/desktop.main.ts#L165-L168

These are some of the few services we are not using `registerSingleton` for because they are needed very early.

**Comment by aeschli** [comment]
Yes, `refineServiceIdentifier` makes sense, it's like the createDecorator variant that [I suggested](https://github.com/microsoft/vscode/issues/117881#issuecomment-789604943)

**Comment by jrieken** [comment]
> it's like the createDecorator variant that I suggested

Sorry for missing that. I have pushed the `refineServiceDecorator`-function

**Comment by bpasero** [comment]
> Sorry for missing that. I have pushed the refineServiceDecorator-function

@jrieken is this something I should adopt as well for layout and environment service?

**Comment by jrieken** [comment]
Yeah, I think it make sense. Latest is when you start using registerSingleton

**Comment by sandy081** [comment]
I also liked `refineServiceIdentifier` 👍
