### ISSUE TITLE
Show currently running test in the test explorer

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#117893]
Testing #117305

When the test explorer is visible and when I run all tests, then it would be nice to see which test/suite is currently executing. This could be done by revealing the corresponding node in the tree.

**Comment by connor4312** [comment]
Hm, I don't really like moving around the scroll position automatically. If I have tests that run long I might kick those off and still be looking at the tree for other things and would not want to be distracted. Maybe a 'follow running test' setting would work for this. Probably safe to have it on by default since it would be less disruptive for the common case of smaller projects.

**Comment by egamma** [comment]
I can see the stability concern and it would be interesting to see how it feels. 

One idea to reduce the jumping could be to expand the currently running suite and then collapse it when it is done.

**Comment by connor4312** [comment]
If nothing else it is [very fun to watch](https://memes.peet.io/img/21-04-127d4170-e2b8-4fac-84b9-0548b9edf09b.mp4)

It can be toggled via the setting `testing.followRunningTest`, and is on by default.
