### ISSUE TITLE
Set different versions of an extension by workspaces.

### ISSUE THREAD

**Issue by Daeruun** [microsoft/vscode#117838]
I'd like to be able to set a fixed version for an extension to one workspace, and another version of the same extension to the next workspace. I'd like to have both installed and loaded as defined, so that I do not need to update/downgrade and reload VScode when opening one or the other workspace.

I imagine this beeing a new parameter in the extensions.json in a workspace(folder) or to work similar to disabeling an extension for a certain workspace.

**Comment by Daeruun** [comment]
Sorry, I didn't find that other one. That one goes into a similar direction, thats right, but I don't see anything about different versions per workspace.
I'll add a comment to extend the other issue.

**Comment by usernamehw** [comment]
Maybe it's not a duplicate of #40239 then. @sandy081

**Comment by sandy081** [comment]
Yeah this seems to be about enabling specific version of an extension per workspace. 

May I know the use case or requirement behind this?

**Comment by Daeruun** [comment]
Thanks for reconsidering this issue.

> Yeah this seems to be about enabling specific version of an extension per workspace.

Exactly.

> May I know the use case or requirement behind this?

Sure.

I'm using an extension that provides a debugger for developing extensions for an external program I use.
From time to time the external program gets updates to its API, that result in changes of the VS-Code extension.
Unfortunately I need to support more than one version of the external Program and thus I need to switch versions of the VS-Code extension, depending on the target I work with.
At the moment I load the corresponding workspace, install the correct version of the extension and reload the workspace.
It would be nice to simply configure the desired version of the extension and let VS-Code load the correct one.

Manually I can do that (for the used expansion) even if more than one workspace is open, as I quite frequently have more than one open, each using another version of the extension (open workspace -> install extension, reload -> repeat for next workspace).
Usually I start with one workspace, and after a while I need to check if I can port my patch to another version and thus open the next workspace, leaving the other(s) open...
Obviously each workspace uses a own instance of (each) extension, so this works out.
What I'm not aware of yet is if each workspace has its own set of settings, what might be necessary as well...

**Comment by justarandomgeek** [comment]
To add a little detail here, the extension @Daeruun is using that leads to this problem is my [Factorio Mod Debugger](https://marketplace.visualstudio.com/items?itemName=justarandomgeek.factoriomod-debug), which for practical reasons only supports a relatively narrow range of game versions near the current version. However, sometimes modders wish to support a wider range of versions than I do, and my advice has always been to just switch to the matching old version of the debugger when needed. I've also suggested to a few folks to use regular/insiders vscode installs to get two separate extension sets but that's obviously a less than perfect workaround too.
