### ISSUE TITLE
toLocaleString displaying time 00:00:00 as 24:00:00

### ISSUE THREAD

**Issue by bhughes339** [microsoft/vscode#117970]
- VS Code Version: 1.53.2 (user setup)
- OS Version: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Toggle Developer Tools in any VSCode editor
2. Go to Console tab, and enter `new Date(1612760400000).toLocaleString(undefined, {timeZone: 'America/New_York', hour12: false})`
3. Console will return "2/8/2021, 24:00:00" instead of "2/8/2021, 00:00:00"

Does this issue occur when all extensions are disabled?: Yes

The issue occurs in Developer Tools as well as any extensions that use the `toLocaleString` function. It can be reproduced with any timestamp that corresponds to times between 00:00:00 and 00:59:59. It only appears to occur when the `hour12: false` option is used--otherwise, the time correctly displays as 12:00:00AM.

This issue does not occur in pure JavaScript, nor in other TypeScript implementations (tested on https://www.typescriptlang.org/play)

**Comment by IllusionMH** [comment]
> This issue does not occur in pure JavaScript, nor in other TypeScript implementations

This is Chromium behavior which can be reproduced in Chromium 90 (Screenshot from Edge Version 90.0.803.0)
![image](https://user-images.githubusercontent.com/1312662/109695798-050cca80-7b95-11eb-8761-a5c40df0d18b.png)
And this behavior can heavily rely on ICU data that is provided by OS or during compilation.

Best option here is to use `hourCycle: 'h23'` instead of `hour12: false`

Also see https://github.com/moment/luxon/issues/675
