### ISSUE TITLE
"Focus on ..." commands for panel views that have been moved have an ugly category

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#117960]
![image](https://user-images.githubusercontent.com/38270282/109289768-fafe6b00-7826-11eb-825c-b538bb70140a.png)

**Comment by alexr00** [comment]
This also happens with the terminal view:
1. Move terminal into one of the sidebar view containers.
2. Move terminal back to the panel
3. Command Palette -> "Focus on terminal"
![image](https://user-images.githubusercontent.com/38270282/109634505-9b1b0380-7b49-11eb-8668-4a48c9d62e41.png)

**Comment by sbatten** [comment]
This also presents itself in the `Move View`  action

![image](https://user-images.githubusercontent.com/6561887/109683012-cabf1100-7b33-11eb-8a63-cc5905e6d716.png)

**Comment by sbatten** [comment]
@sandy081 This used to say `Custom Views` which was not a localized string, and it has been that way for 10 months implying this flow hasn't been used much. Since the name of the composite can change dynamically, we cannot use it in the `Focus on View` action without registering a ton of listeners and the category is not that important. The fix we chose is to use just `View:` when we have this case; however, I suggest we register all `Focus on X View` commands to the `View:` category. The category is not providing much and being consistent seems better.

**Comment by sandy081** [comment]
Sorry about this - I forgot that view container title is used as category for views commands. 

@sbatten Thanks for fixing it.
