### ISSUE TITLE
Ports view loses its badge after moving around

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#117904]
Steps to Repro:
1. Open a workspace with forwarded ports (Note the numerical badge next to ports tab)
2. Drag the ports container into the side bar
3. Right click > reset location on the ports view

:bug: => badge is lost

/cc @sandy081 as the Problems view does not have this issue and he may know why

**Comment by alexr00** [comment]
Also curious about @sandy081 response, since I just grab the view container to add the activity badge:

https://github.com/microsoft/vscode/blob/d3b97f07fcf39b08ebbc6a873f4d7d78c15119dc/src/vs/workbench/contrib/remote/browser/remoteExplorer.ts#L121-L122

Do I need to listen to some view container event and update the badge again?

**Comment by sandy081** [comment]
You shall be adding the activity to the view instead of view container which will make sure activity is associated always with the view 

```
https://github.com/microsoft/vscode/blob/e3612f789be075548dc4c28f04ac2769352f6606/src/vs/workbench/contrib/markers/browser/markers.ts#L50-L50
```
