### ISSUE TITLE
VSCode does not display debug adapter source code retrieved through a Source request for which sourceReference >0

### ISSUE THREAD

**Issue by adigeo10** [microsoft/vscode#118078]
Version:
- VS Code Version: 1.53.2 (user setup)
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:48:04.245Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
- OS Version:: Windows_NT x64 10.0.14393

Steps to Reproduce:
1. Working on a new debug adapter. For one of the stack frames corresponding to a breakpoint I return a Source for which sourceReference > 0, instructing the front end to get the source through a Source request. I do receive the Source request, and I retrieve the corresponding source code and return it to VSCode. All according to the DAP documentation so far.
2. VSCode opens a new document window with the name of my source, but it never displays the code. It appears that is waiting for something else as there is a moving progress bar just below the tab with the document name.
3. After I disconnect from the debug adapter the following message gets displayed in that document window: "Could not load source 'Test1': Canceled."

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by isidorn** [comment]
@adigeo10 thanks for filling this, however this works for all the other debug adapters out there.
If you would like me to investigate further it would be good if you could fork [`mock-debug`](https://github.com/microsoft/vscode-mock-debug) and do a change so I can clone it and reproduce the bug. Without this it is very hard for me to figure out what is going on. I can only tell you this is supposed to work.

Alternativly you can F1 > developer tools in VS Code and put a breakpoint [here](https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/debug/common/debugContentProvider.ts#L74) and investigate what is going on. Since that class is in charge of providing content for `Source` objects

**Comment by adigeo10** [comment]
Hello Isidor,

  Thank you for your answer and pointers regarding debugging of the source
code.
  It turns out that this was a problem with my code where I did not set the
*request_seq* properly to match the *seq* number of the request for the
source request. That fixed, everything works as expected.

Adrian

**Comment by adigeo10** [comment]
Not a bug. 
Problem caused by wrongly setting the _request_seq_ of the response to 0 rather than matching the sequence number of the source request.

**Comment by isidorn** [comment]
Thanks for letting us know.
