### ISSUE TITLE
Column selection cannot select first position of a line

### ISSUE THREAD

**Issue by MartinGC94** [microsoft/vscode#118062]
- VS Code Version: 1.54.0-insider
- OS Version: Windows 10 20H2

Steps to Reproduce:

1. Type in anything you want, for example "Hello World"
2. Place your cursor anywhere past the first column for example after "Hello" in "Hello World"
3. Use the column selection to select from the cursor to the start of the line using the default shortcut CTRL+Shift+Alt+Left arrow
4. Note how you cannot select the first character on the line (in this case "H")

This does not happen if you use the mouse (Shift+ Alt+ Left click drag) or if you use the "Shift + left arrow" shortcut for cursorColumnSelectLeft.

Does this issue occur when all extensions are disabled?: Yes

**Comment by ArturoDent** [comment]
I can reproduce this on Stable and Insiders:

Version: 1.53.2 (user setup)
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:48:04.245Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.21322

Version: 1.54.0-insider (user setup)
Commit: 42e27fe5cdc58539dad9867970326a297eb8cacf
Date: 2021-03-02T19:09:10.315Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.21322

**Comment by kshamil76** [comment]
Something similar is happening on Mac.  I have the same results on my M1 Mac.

Version: 1.53.2
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:45:54.515Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 18.7.0

The mouse cursor move seems to be going off of the center of the letter.  When you click in front of the halfway mark, it puts the cursor at the beginning, but when you click after the half way mark of a letter, it will put the cursor at the end of the letter instead of the beginning.
