### ISSUE TITLE
NPM Script Explorer icon

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#118019]
The NPM Script is currently using the following icon:

![image](https://user-images.githubusercontent.com/172399/109765636-6e242a80-7bf5-11eb-83e5-aaeadd5c8e93.png)

Inside the NPM Scripts Explorer scripts are shown with the '{ }' icon. 

Wouldn't it be more consistent to also use the '{ }' icon for the explorer?

**Comment by alexr00** [comment]
'{ }' is already a codicon, so I am happy to change to that. @sbatten I think you added the `code` icon here. Anything that would prevent us from switching to '{ }'?

**Comment by usernamehw** [comment]
Isn't this just a `.json` file icon that look different depending on the installed icon theme?

![Screenshot (446)](https://user-images.githubusercontent.com/9638156/109790629-aaba4b00-7c22-11eb-8afd-f7d7b2615464.png)

**Comment by alexr00** [comment]
@usernamehw good point. I'll wait for @misolori's thoughts too.

**Comment by misolori** [comment]
The `{ }` on the view is indeed a file icon that changes on the theme. If we wanted to keep the icons consistent we could opt to change the `{ }` on the view to the `code` icon that's used in the activity bar.

**Comment by alexr00** [comment]
If we change the `{ }` in the view, then we'd be breaking a different consistency. Since the view uses the resource for `package.json` it means that everywhere that the file `package.json` appears it get the same icon, which is great. If we change the icon just in the scripts view, then that view will be the odd one out. 

I think if we change away from the `code` icon then we should be changing it because have an icon that fits better. Perhaps an icon similar to the icon we use for the build in extension? 
![image](https://user-images.githubusercontent.com/38270282/109964744-5d0b1480-7cee-11eb-8b11-8d56497c03b7.png)

Of the existing codicons, I think `code` and `json` fit best. @misolori do you have a preference between `code`, `json`, and a new npm specific icon?

**Comment by misolori** [comment]
I don't have a preference, either works. We also have 'tools' that's used in tasks that is similar as well. But any of those work for me.

**Comment by alexr00** [comment]
Alrighty then.  Let's go with `json`, since it will nicely match the default file icon theme.

**Comment by Gilson401** [comment]
Im facing this issue. And I have package.json in all my projects root. Some apears others dont appears.
