### ISSUE TITLE
List: Support a different navigation mode where focus and selection move together

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#118045]
- When focus === selection && size 1
- Else, navigation should only move focus

**Comment by rebornix** [comment]
I found that some of the list/tree is already doing that, for example the Problems View, which is an `ObjectTree`, will move both focus and select down when arrow down key is pressed, even if we turn on `multipleSelectionSupport` for it.

This is because `focusDown` command already has a special logic for _tree_: pass in a fake keyboard event, to trigger the selection to align with focus

https://github.com/microsoft/vscode/blob/e9533c22fee544a58b06fd45d7ed0ee45dcbbc94/src/vs/workbench/browser/actions/listCommands.ts#L51

The problem with this special logic is, `shift+arrowdown` doesn't work anymore, even with `"multipleSelectionSupport": true`. It will move the focus down and then move the selection down as well.

---

As we discussed this morning, a new flag/option will be introduced for this behavior and we should get rid of `focused instanceof List || focused instanceof PagedList || focused instanceof Table` checks in the list commands, and use the new option to decide what's the expected behavior. And also make sure `shift+arrowdown` still works.

**Comment by roblourens** [comment]
I forgot that the `openOnFocus` flag exists, which opens and selects items when they become focused, so I already get this behavior. Any benefit to using both flags?

**Comment by joaomoreno** [comment]
Oh I forgot about that, that's exactly what search, problems, etc are using. Let me see if I can clean up that one, I do look at it more as a hack, and adopt the new one instead.

**Comment by joaomoreno** [comment]
This is now adopted in search, peek references, bulk edit, comments and markers. Thanks @roblourens for reminding me of `openOnFocus`. Watch out for issues. cc @jrieken @sandy081

**Comment by sandy081** [comment]
Thanks @joaomoreno

**Comment by roblourens** [comment]
Now search doesn't open on focus anymore. Is there something else I need to do?

**Comment by joaomoreno** [comment]
> Now search doesn't open on focus anymore.

What do you mean? How can I repro?

**Comment by roblourens** [comment]
Use the arrow keys to move focus around the search view tree

https://user-images.githubusercontent.com/323878/111356562-bad02280-8645-11eb-943a-45232eba7efd.mp4

**Comment by roblourens** [comment]
Oh I see, this only works if there is already a selection. If there is no selection then one is not added. I am getting here by starting with focus in the search input then pressing cmd+down to move focus to the tree.

**Comment by joaomoreno** [comment]
I think the tree should handle it, I can fix it!

**Comment by roblourens** [comment]
Thanks!

**Comment by roblourens** [comment]
I think this is basically the same case but test F4 navigation as well: https://github.com/microsoft/vscode/issues/119199

**Comment by joaomoreno** [comment]
Looking into the code, I ended up fixing it at search level.
