### ISSUE TITLE
Publish to GitHub: Use 'main' as default branch

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#118182]
GitHub is using 'main' as the default branch when creating a new repository.

**Comment by eamodio** [comment]
As far as I can tell, we just delegate to GitHub for that, so I would expect it to use your _Repository default branch_ setting on https://github.com/settings/repositories.

Do you see something different?

**Comment by chrmarti** [comment]
I haven't debugged it, but thought we might be using `git init` which presumably still uses `master`.

**Comment by eamodio** [comment]
Ah you might be right, but `git init` can now be controlled with it's own config setting: `git config --global init.defaultBranch main`

**Comment by chrmarti** [comment]
We could do that specifically for the GitHub case to align with GitHub. (The user doesn't necessarily know where that name originates from.)

**Comment by eamodio** [comment]
But both Git and GitHub have settings controlling that. If anything, I think we would want to lookup the GitHub setting and use that. But I'd wouldn't want to override someone's specific configuration either.

**Comment by shepazu** [comment]
For developers creating repositories with VSCode, especially the GUI, the safer option seems to be to override default config settings to use `main` instead of `master`. This would align with the most common git providers, like Github and GitLab, which use `main` as the default branch name. 

Less experienced developers may not notice that the default branch created with the `Initialize Repository` button is `master`, may be confused by the difference when they publish to a popular git service, and are not as equipped to learn how to change the default or rename the branch. 

More experienced developers are more likely using the CLI (rather than the GUI) to create a new repo, and can more easily reset their default branch if they want or need to continue creating new repos with a `master` branch.

_(I was very surprised when teaching my new devs how to create a git repo that the default was still `master`, and had to search out how to change this.)_

**Comment by mkx85** [comment]
@shepazu Can you please share how you go about renaming the branch from master to main in VS Code? I did this, but when I perform a push I get the following error:

`> git push terraform-demo main
To https://github.com/username/nameofgithib.git
 ! [rejected]        main -> main (non-fast-forward)
error: failed to push some refs to 'https://github.com/nameofgithub.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
`

**Comment by shepazu** [comment]
_Disclaimer: I'm not an expert at git. Anyone else on this thread would be better able to answer._

My guess is that your local is out of sync with your remote, so before you try to change from `master` to `main`, make sure your local is up to date with your remote, probably by using one of the rebase commands, like `git config pull.rebase false` or `git config pull.rebase true`. (First make sure that you don't have any local content you don't want to lose!) Then you'd do a git pull.

After that, you could try again to do `git config --global init.defaultBranch main`. That worked for me.

Again, **not an expert!** But I hope that helps.

> @shepazu Can you please share how you go about renaming the branch from master to main in VS Code? I did this, but when I perform a push I get the following error:
> 
> `> git push terraform-demo main To https://github.com/username/nameofgithib.git ! [rejected] main -> main (non-fast-forward) error: failed to push some refs to 'https://github.com/nameofgithub.git' hint: Updates were rejected because the tip of your current branch is behind hint: its remote counterpart. Integrate the remote changes (e.g. hint: 'git pull ...') before pushing again. hint: See the 'Note about fast-forwards' in 'git push --help' for details. `

**Comment by mkx85** [comment]
Yes, it was the initial pull that did the trick. Thanks. For anyone else that is interested from a beginners prospective, I have blogged the fix [here ](https://cloudcurve.co.uk/terraform/getting-started-with-visual-studio-code-and-github/)(using VS Code).

**Comment by shepazu** [comment]
> Yes, it was the initial pull that did the trick. Thanks. For anyone else that is interested from a beginner's perspective, I have blogged the fix [here ](https://cloudcurve.co.uk/terraform/getting-started-with-visual-studio-code-and-github/)(using VS Code).

Nice write-up. I'll point newbies to it. One suggestion: you might inform readers that they only need to do `git config --global init.defaultBranch main` once, for their first project, and all other projects will use `main` by default thereafter.

**Comment by mkx85** [comment]
> > Yes, it was the initial pull that did the trick. Thanks. For anyone else that is interested from a beginner's perspective, I have blogged the fix [here ](https://cloudcurve.co.uk/terraform/getting-started-with-visual-studio-code-and-github/)(using VS Code).
> 
> Nice write-up. I'll point newbies to it. One suggestion: you might inform readers that they only need to do `git config --global init.defaultBranch main` once, for their first project, and all other projects will use `main` by default thereafter.

Thanks for the suggestion, will update shortly :)

**Comment by lszomoru** [comment]
When running `git init` from the terminal, you are presented with the following "hint" if the repository is created with `master` as the default branch, with guidance on how to use the setting in order to control the default branch name:
<img width="571" alt="image" src="https://user-images.githubusercontent.com/3372902/148123332-c45a7a53-5b1a-4719-8f5a-b935843415ed.png">

There are couple of things that we can try to do in VS Code to make this easier:
1. Have a command in the command palette that allows a user to set the default branch name
2. Have a command in the command palette that allows a user to change the default branch for a repository
2. Detect that the repository was created with `master` as a default branch and let the user leverage the command from 2) to change the default branch name

I will try to look into this next milestone.

**Comment by lszomoru** [comment]
Related to https://github.com/microsoft/vscode/issues/179658

**Comment by lszomoru** [comment]
The latest Insiders release contains a new setting, `git.defaultBranchName` that is set to `main` and it can be used to control the default branch name of the git repositories that are created using VS Code. Setting the value of the setting to an empty string will defer to using the default name as configured in git. Please give it a try and let me know if you run into any issues. Thanks!

**Comment by lszomoru** [comment]
Verification steps:
* Create a new folder, and add some files to the folder
* Open the folder in VS Code Insiders, and ensure that you are signed in with your GitHub account
* From the command palette invoke the "Publish to GitHub" command
* Pick private/public repository in the quick pick widget
* Verify that the repository was published using the default branch name specified on GitHub (ex: `main`)
