### ISSUE TITLE
Killing the active terminal instance crashes when using PowerShell

### ISSUE THREAD

**Issue by revolter** [microsoft/vscode#118139]
Issue Type: <b>Bug</b>

- Install the official PowerShell extension
- Start editing a PowerShell script
- Click the "Kill the Active Terminal Instance" button

An error notification shows up, with the text:

> The PowerShell session has terminated due to an error, would you like to restart it?
> Source: PowerShell (Extension)
> Yes | No

VS Code version: Code 1.54.0 (42e27fe5cdc58539dad9867970326a297eb8cacf, 2021-03-03T02:17:59.499Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|32.00GB (2.89GB free)|
|Process Argv|--crash-reporter-id 155b0ce3-be01-4055-936a-2d654c76ce4e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tailwindcss|bra|0.5.9
vscode-eslint|dba|2.1.14
vscode-html-css|ecm|1.10.2
prettier-vscode|esb|5.9.2
rainbow-csv|mec|1.8.1
vscode-docker|ms-|1.10.0
remote-containers|ms-|0.163.0
cpptools|ms-|1.2.2
powershell|ms-|2021.2.2
vscode-typescript-tslint-plugin|ms-|1.3.3
vsliveshare|ms-|1.0.3784
vetur|oct|0.33.0
platformio-ide|pla|2.3.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30256638
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubsetcf:30265999
pythontb:30265425
vspre833cf:30267465

```

</details>

**Comment by TylerLeonhardt** [comment]
Thanks! The PowerShell extension's repo is over here: http://github.com/PowerShell/vscode-powershell so that'll be the best place going forward to open issues about the PowerShell extension.

Now for this issue, I do have context. You're killing the PowerShell _Integrated_ Console which provides all of the language features for the PowerShell language (intellisense, formatting, etc). By killing that, you kill the extension which is why you see this error.

There's a setting to hide it `"powershell.integratedConsole.showOnStartup": false,` if you want to hide it but still have language features, but it _will_ show up when you F8 a piece of script or F5 a script.
