### ISSUE TITLE
Themes no longer affect focused row in "Go to File" or "Show all commands" dropdowns

### ISSUE THREAD

**Issue by aminomancer** [microsoft/vscode#118198]
- VS Code Version: 1.54.1
- OS Version: Windows 10, 20H2

Steps to Reproduce:

1. hit ctrl+P or ctrl+shift+P
2. look at the selected row, it's blue instead of a themed color.
3. you can see it in the DOM inspector, it has an inline background-color rule:

```
.monaco-list.list_id_5 .monaco-list-row.focused {
    background-color: #062f4a;
}
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment]
This is releated to changes https://github.com/microsoft/vscode/commit/c4c044e20dba1434b61294b426712af47558e976 and https://github.com/microsoft/vscode/commit/6d9611747ea032060ec3733bc295e01a6f4b0ca7. The change added a new color for `quickInput.list.focusBackground`. Before it was `list.focusBackground`

@joaomoreno It would be good to have a backward compatible solution here as the change requires existing themes to adopt the new color id. I believe the change affects not only quick pick but also the suggest widget.

Instead of setting the defaults of the new color to specific colors, you can make it a derived color: `oneOf(listFocusBackground, '#062F4A')`

**Comment by joaomoreno** [comment]
The thing is, @aeschli, we want themes to go away from styling list focus background, since we now style only list focus outline. The problem here is that styling outline in quick pick is ugly, so I decided to introduce a new theme color and call out the adoption in the release notes. I expected some friction obviously, but once themes adopt the change, these issues should eventually stop.

I don't think there's a backward compatible solution for this change, right?

**Comment by aminomancer** [comment]
Thanks for the feedback, I will edit my theme accordingly
