### ISSUE TITLE
Method to resolve VS Code debug configuration

### ISSUE THREAD

**Issue by yannickowow** [microsoft/vscode#118120]
Related: #46471

Hi,
To provides IntelliSense for launch.json, my completion provider needs to be able to resolve built-in variables, such as ${workspaceFolders}.
It would permits to provide completion for files (for `program` argument), folders (for `cwd`) and so-on...
I know it might be a duplicate, but I wonder if, for launch.json, it can be easily fixed using `resolveDebugConfiguration`...

If duplicate, I can close this issue.

Thanks.

**Comment by weinand** [comment]
Extensions have already a way to access a debug configuration with all variables substituted ("resolved"). This includes interactive variables (e.g. user input variables).
 
We will not provide another general API for this.
One reason being that resolving interactive variables cannot be done at an arbitrary point in time.

In addition, providing completion for variables like `program` or `cwd` will be tricky, because they are introduced and owned by individual debugger extensions and you do not know their semantics and format.

**Comment by yannickowow** [comment]
Thanks for your answer. 
About variables, I was talking about built-ins one, not about `prompt`, `input`, nor `command`. 

And yes, I agree about your last point. It was only to provide completion for my own debug configuration.
Then I will document to not use variables at all for this ones in order to provide valid completion.
