### ISSUE TITLE
The connection to the terminal's pty host process is unresponsive, the terminals may stop working.

### ISSUE THREAD

**Issue by hui0613** [microsoft/vscode#118159]
![image](https://user-images.githubusercontent.com/45350664/110057393-7e760a00-7d9b-11eb-98d5-fd7f1d7f35dd.png)

I am developing a vscode extension program and need to use the terminal to start another exe process. When I execute the restart, it will execute `vscode.commands.executeCommand("workbench.action.terminal.kill")` and `vscode.window.createTerminal({})`, the above error will appear.
However, when I manually close the exe program and then execute  `vscode.window.createTerminal({})`, there is no problem.
I need help  
@mojodna 

![image](https://user-images.githubusercontent.com/45350664/110059800-eaf30800-7d9f-11eb-8360-99a29ea3feed.png)

**Comment by Annie-Johnson** [comment]
I'm also experiencing this issue after restarting my laptop.

**Comment by WORMSS** [comment]
I have just updated to `1.54.0` I've had the update for about 2 hours (give or take)
And I have seen this popup 3 times already.
All I had was the terminal open (I was down stairs getting lunch for the last one)
I came back up to find the error popup hui0613 had but my terminal just said ![image](https://user-images.githubusercontent.com/1384537/110116961-285f9180-7db0-11eb-8d86-bc270b26b9f7.png)

Been using VSCode for years, and this is the first time I have even seen this "disconnected" thing happen, but since it's 2 hours after the update, I am guessing `1.54.0` is the problem here.

Is there an easy way to roll back to my previous version of vscode?

**Comment by kaanguru** [comment]
![resim](https://user-images.githubusercontent.com/47606404/110122937-55706c00-7dd1-11eb-8442-7a4f184153e2.png)
I am using windows. I was using [ConEmu ](https://conemu.github.io/en/UpdateSpeedup.html)as my default terminal until this update. I have tried all of this list as default shell but VisualCode said:


> The connection to the terminal's pty host process is unresponsive, the terminals may stop working.

or 
> The terminal process "C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe '/k', '%CMDER_ROOT%\vendor\bin\vscode_init.cmd'" terminated with exit code: 1.

I think it's fixed after I reinstall **ConEmu**

**Comment by zinderic** [comment]
Looks this was not fixed in https://github.com/microsoft/vscode/issues/117542 

I've been hitting this issue with latest version:

```
Version: 1.54.1
Commit: f30a9b73e8ffc278e71575118b6bf568f04587c8
Date: 2021-03-04T22:42:18.719Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.3.0
```

I've also hit it with the latest insider version:

```
Version: 1.54.0-insider (Universal)
Commit: 42e27fe5cdc58539dad9867970326a297eb8cacf
Date: 2021-03-02T19:09:42.206Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.3.0
```

**Comment by nils-dehn** [comment]
Same here since 1.54.0. Release notes say "Terminal processes are now spawned under a new "pty host" process, instead of the window process." I am using the Python extension which in my installation has a long startup time. It always now kills the my gitbash shell terminal. A newly created terminal runs ok for some time, but also dies later. Also the shell seem less responsive. I sometimes also have visual artifacts when scrolling in the terminal window.

**Comment by RStadlmair** [comment]
Using VS-Code with PowerShell. In debugging sessions i see this also a few times a day

**Comment by Tyriar** [comment]
We're planning on fixing this with https://github.com/microsoft/vscode/issues/117956 and https://github.com/microsoft/vscode/issues/117990, which seems to be working well https://github.com/microsoft/vscode/issues/117542#issuecomment-792677188. If anyone could verify on Windows if you still hit the problem using the [Insiders build](https://code.visualstudio.com/insiders/) that would be helpful.

**Comment by yemi** [comment]
FYI just got this several times on a Mac as well
