### ISSUE TITLE
Only getting word-based suggestions at first 

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#118160]
Been noticing this often lately, did anything change?

- Type something, the suggest widget pops up automatically, but it only contains word-base suggestions
- Press esc to hide it. Press ctrl+space to show it manually
- Now it has the correct suggestions from TS

https://user-images.githubusercontent.com/323878/110058480-390ff900-7d17-11eb-811d-4c8b39d997df.mp4

**Comment by roblourens** [comment]
I turned on tsserver verbose mode and it stopped happening. Will try to get a log next time I see it.

**Comment by roblourens** [comment]
[tsserver2.log](https://github.com/microsoft/vscode/files/6087798/tsserver2.log)

I reproed it a couple times in the same spot at the end.

**Comment by mjbvz** [comment]
Thanks for the logs @roblourens. The logs don't show any obvious problems ( all the requests for `completionInfo` seem to succeed)

Could this be happening because the TS extension hasn't finished activation when you first trigger suggestions? In those cases, I believe we may just fallback to word based suggestions

**Comment by roblourens** [comment]
I don't remember seeing this lately
