### ISSUE TITLE
iframe based webview shares the same browsing context as workbench

### ISSUE THREAD

**Issue by tamuratak** [microsoft/vscode#118181]
Version: 1.55.0-insider
Commit: 567b82a0f9c31bd463af64997997730c5d0173cc
Date: 2021-03-05T05:22:04.953Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 18.7.0

Fail to load SVG files in webviews when `"webview.experimental.useIframes": true`. Related to  #83188.

Steps to Reproduce:

1. Set `"webview.experimental.useIframes": true`
1. Execute the following extension sample.
2. Fail to load a SVG file.

An error message in the console says:
```
GET https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/tiger.svg net::ERR_BLOCKED_BY_CLIENT
```

```ts
import * as vscode from 'vscode';

export function activate(context: vscode.ExtensionContext) {
  const rootUrl = vscode.Uri.file(context.extensionPath)
  const disposable = vscode.commands.registerCommand('extension.helloWorld', async () => {
    if (!vscode.window.activeTextEditor) {
      return;
    }
    
    const panel = vscode.window.createWebviewPanel(
      'catCoding',
      'Cat Coding',
      { viewColumn: vscode.ViewColumn.Beside },
      { enableScripts: true, localResourceRoots: [] }
    );
    panel.webview.html = getHtml();
  });
  context.subscriptions.push(disposable);
}

function getHtml() {
	return `
<!DOCTYPE html><html><head>

</head>
<img src="https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/tiger.svg" style="width: 100%">
`
}
// this method is called when your extension is deactivated
export function deactivate() {}
```

**Comment by deepak1556** [comment]
`net::ERR_BLOCKED_BY_CLIENT` means we are explicitly blocking the resource https://github.com/microsoft/vscode/blob/main/src/vs/platform/windows/electron-main/window.ts#L413-L452

Switching to iframes will cause the webview to use the same session as the workbench hence the above filter applies.

**Comment by mjbvz** [comment]
@deepak1556 Is there a way to force normal iframes into their own context? For `<webview>` I believe we use the `partition` attribute for this: https://github.com/microsoft/vscode/blob/a9087e9d0a9a2c0132b728ecdae543b3f2cccdfa/src/vs/workbench/contrib/webview/electron-browser/webviewElement.ts#L178

**Comment by bpasero** [comment]
PR https://github.com/microsoft/vscode/pull/120156 addresses this issue for locally referenced SVG files. The bigger issue which I could not find a way to fix is to address this for HTTP/HTTPS referenced SVG images. [From the filter](https://github.com/microsoft/vscode/blob/54c74c2af08c6954397cce3492744e10a1d810da/src/vs/platform/windows/electron-main/window.ts#L425-L425) I see no way to figure out that the request was made from a webview, printing the output from the `details` object returns:

```json
{
  id: 2072,
  url: 'https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/USStates.svg',
  method: 'GET',
  timestamp: 1617088241663.538,
  resourceType: 'image',
  webContentsId: 1,
  referrer: ''
}
```

I wonder if the `referrer` could potentially be used here, but it seems empty, maybe because we have another `iframe` inside the `iframe` that does not seem to have any origin?

![image](https://user-images.githubusercontent.com/900690/112948110-eff56e00-9137-11eb-8194-5ccc20170199.png)

**Comment by deepak1556** [comment]
https://github.com/electron/electron/pull/27078 will provide the ability to distinguish requests from a frame, depends on adopting electron 12

**Comment by Tyriar** [comment]
Luna Paint's paste command also breaks probably because of this.

**Comment by deepak1556** [comment]
Change has been reverted in https://github.com/microsoft/vscode/commit/a7e080af0278fcb002028fe637a8a1d432de27af

**Comment by deepak1556** [comment]
@mjbvz main is back on Electron 12.

**Comment by mjbvz** [comment]
Reverted the revert with a37a8c517a3482adea9ec9ba7b90ad19b1a275e3
