### ISSUE TITLE
Jupyter Extension cannot use Proposed API in Stable VS Code

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#118124]
- VS Code Version: 1.54
- OS Version: N/A

Steps to Reproduce:

1. Install Jupyter Extension
2. Add the following into your settings
```
"jupyter.experiments.optInto": ["__NativeNotebookEditor__"],
```
3. Extension fails to load

@rebornix /cc

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by kajuberdut** [comment]
The error does come up when extensions are disabled, but importantly, it also breaks the python extension.
This broke immediately after the Feb update for me (Windows 10 Pro, VS Code 1.54.0, jupyter v2021.3.619093157) I have never installed anything related to jupyter except the extension (and only because it's required by the Python extension.)

**Comment by DonJayamanne** [comment]
@sbatten @rebornix @Tyriar  Thanks for fixing this quickly and unblocking our users.

**Comment by noce2** [comment]
Hi, I'm aware this is closed but was this also supposed to fix a `spawn ENOTDIR` error that pops up when trying to run a Jupyter Notebook?

![image](https://user-images.githubusercontent.com/20339399/110073136-cafb1e80-7d76-11eb-85e8-42c0952dad91.png)

**Comment by patientzero** [comment]
> Hi, I'm aware this is closed but was this also supposed to fix a `spawn ENOTDIR` error that pops up when trying to run a Jupyter Notebook?
> 
> ![image](https://user-images.githubusercontent.com/20339399/110073136-cafb1e80-7d76-11eb-85e8-42c0952dad91.png)

I think this is stell broken

**Comment by naquiroz** [comment]
Hi, I'm getting this after this update.

<img width="498" alt="image" src="https://user-images.githubusercontent.com/29825816/110130902-50e38d80-7da8-11eb-8b9e-c3319bafbafe.png">

This is due to ms-python

<img width="530" alt="image" src="https://user-images.githubusercontent.com/29825816/110130984-6e185c00-7da8-11eb-9eb0-cd24a2c55893.png">

Any clues why might this be?

**Comment by IanMatthewHuff** [comment]
@noce2  and @patientzero . This may be related, but it looks like for you the extension is already loaded, and the issue happens when launching a notebook so it doesn't seem the same to me as this issue. I've open up this issue here in the Jupyter repo to investigate:
https://github.com/microsoft/vscode-jupyter/issues/5046
If you can provide some of the logging info that I've listed in that bug it would be very helpful to investigate.

**Comment by DonJayamanne** [comment]
@naquiroz Please could you try installing the latest Python Insiders extension.
Go into command palette and select `Python: Switch to Insiders Daily Channel`
Once the extension has been installed you might have to reload VS Code.

**Comment by naquiroz** [comment]
I will try tomorrow!

**Comment by naquiroz** [comment]
So I tried it, and it is still crashing. Apprently it is a problem with the vscode version since it works just fine with vscode 1.53
<img width="559" alt="image" src="https://user-images.githubusercontent.com/29825816/110216572-92e6ff00-7e8e-11eb-89bd-1b9f0c38b27d.png">

**Comment by Ketho** [comment]
I'm not completely sure but I have a similar issue where I have an `extensionDependencies` and my extension stopped working with VS Code 1.54.1 and according to the error showed needed to enable Proposed API.
```json
"extensionDependencies": [
	"sumneko.lua"
]
```
![image](https://user-images.githubusercontent.com/1073877/110218408-fb97a100-7eb9-11eb-9ed2-2d0398323018.png)

However once I reverted VS Code to 1.53 my extension worked again without any issues.
https://github.com/sumneko/lua-language-server/issues/444
