### ISSUE TITLE
Relax dependency on node spdlog for startDebugTextMate.ts

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#118202]
I noticed a `node.js` dependency from `startDebugTextMate.ts`:

https://github.com/microsoft/vscode/blob/cdc8628d55e72a9fd5238fb534dbab28f6520898/src/vs/workbench/contrib/codeEditor/electron-browser/startDebugTextMate.ts#L16-L16

Is this something we could change so that we do not depend on node directly?

**Comment by sandy081** [comment]
@alexdima You can use `ILoggerService` to create the logger instead of creating it using spdlog directly. It will make sure it creates proper logger in the given environment. 

https://github.com/microsoft/vscode/blob/692f1465a82d96b965530fb0c4b1d2cfb9b8f931/src/vs/platform/log/common/log.ts#L84-L84

See how it is being used by other components, for eg output channels:

https://github.com/microsoft/vscode/blob/065e82d8624f3050eed36eba242e6c951f301ee9/src/vs/workbench/contrib/output/electron-sandbox/outputChannelModelService.ts#L49-L49

**Comment by bpasero** [comment]
@sandy081 thanks, I opened a PR. Can you check if the logger creation is proper? It is my understanding I need to create the file first?

https://github.com/microsoft/vscode/pull/118219/files#diff-2e3e20c6c9e1fab2d99fcf21c95b98bc73ca1116e1fda0f76ffc509456568f06R65

**Comment by sandy081** [comment]
@bpasero 

I do not think creating the file is necessary - Underlying logger will take care of it.

**Comment by bpasero** [comment]
Ok I think I saw an unrelated error then because we seem to try to read from this file directly after starting to log.
