### ISSUE TITLE
Cmd+Q not works on macOS

### ISSUE THREAD

**Issue by dalisoft** [microsoft/vscode#118323]
- VS Code Version: v1.54.1
- OS Version: macOS Catalina 10.15.7

Steps to Reproduce:

1. Download last stable and run
2. Try quit by Cmd+Q

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by dalisoft** [comment]
After rebooting machine it worked itself. Seems some cache issues has been. Thanks for help
