### ISSUE TITLE
Dislike default toggled find in selection

### ISSUE THREAD

**Issue by garfieldbanks** [Microsoft/vscode#11840]
I would like this to either be turned off by default or to always allow the current selection to be cleared via clicking within the text body.

I do _not_ want to go click the little box to turn off _find in selection_ every time I select, copy, and paste something into find/replace.

Another solution for me would be to provide an option in the settings for one of the above solutions.

(Or let me know if there is already a setting available that I missed while searching.)

**Comment by whitecolor** [comment]
I like it.

**Comment by SK83RJOSH** [comment]
I dislike this as well.

I frequently find myself needing to move my cursor and pressing the find keybind again, or sometimes even needing to move my hand from my keyboard to my mouse to deselect find in selection. Which may seem like a minor gripe, but I have to do this so frequently it becomes tiresome as the time it takes can really begin to add up.

Honestly though, I think the main issue here is that having your cursor at the start of the line shouldn't automatically toggle the "find in selection" option, especially not if that line is completely empty, because technically there is no explicit selection being made.. at the very least this behavior should be optional and not default.

With all of that said, this definitely seems related to #12820 in that it's "unexpected" behavior for most people, and so I'm going to mention @isidorn in hopes that he might agree. 😄

**Comment by roblourens** [comment]
This was fixed for 1.7 in #12109 :)
