### ISSUE TITLE
Revisit debugHelperService in the context of sandbox

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#118424]
There is a `vs/workbench/contrib/debug/node/debugHelperService` that is node.js dependent and going forward when we enable `sandbox`, we need to revisit this.

I am not entirely sure about the purpose, so filing an issue here to discuss how we could make this sandbox enabled.

**Comment by weinand** [comment]
The name of the service is a bit confusing, because the only method it provides is the `createTelemetryService`.

IIRC, I've created the service for containing all the debug functionality that would differ between running debug adapters from the renderer versus running them from the extension host (or in other terms: to encapsulate all node dependencies as services).

At the end of this refactoring, only the method  `createTelemetryService` ended up in the service.

@isidorn can you shed some light on the [functionality of the `createTelemetryService` method](https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/debug/node/debugHelperService.ts)?

@bpasero could we access the telemetry service by other means so that this is compatible with the sandbox?

**Comment by isidorn** [comment]
I actually did not write that code, but from what I know this creates a custom telemetry service to be potentially used by debug extension since they can report custom telemetry events.
Here's where it is being used https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/debug/browser/debugSession.ts#L914

Who owns telemetry now?
@sbatten maybe? Do we have a better way to report custom telemtry now?

**Comment by bpasero** [comment]
It seems to me the gist of this is having a way for a debug app to spawn a `AppInsightsAppender` app that is fully configurable with regards to the end point it should send telemetry to:

https://github.com/microsoft/vscode/blob/ff9fbcb077b097d7ffb074f04f6301476578abc3/src/vs/workbench/contrib/debug/node/telemetryApp.ts#L10-L10

If we still need support for this, I think it should move closer to the place where telemetry is currently being emitted, namely the shared process service that sets up our main appender:

https://github.com/microsoft/vscode/blob/dbe9dd496753618e06159beb6c54c5159adb5e7b/src/vs/code/electron-browser/sharedProcess/sharedProcessMain.ts#L220-L222

I think we could easily extend the telemetry service to allow for creating new appenders as needed, or add a new service for this?

**Comment by weinand** [comment]
@bpasero that sounds like a good approach.

**Comment by isidorn** [comment]
@bpasero yes I think this makes sense and I can look into it, thus assigning to this milestone.

**Comment by bpasero** [comment]
Sounds good, I can also assist. Maybe overloading `ITelemetryService` with this is bad because the service is used in so many different contexts and here we only have one use case, but I think @sbatten should also chime in what he feels about it.

**Comment by sbatten** [comment]
Do I understand this correctly? Today, a new telemetry service is created per debug adapter and each has its own appender. If that is the case, why do we need to modify `ITelemetryService`? Don't we still need separate instances?

**Comment by bpasero** [comment]
@sbatten yeah I think `ITelemetryService` is probably already the service that operates with an appender so maybe another service needs to be added specifically to create a telemetry service with a fresh appender.

**Comment by sbatten** [comment]
i think so too

**Comment by isidorn** [comment]
I have cleaned up the debug usage of the helper service, so it boils down to this method

```	
async createPrivateTelemetryService(id: string, aiKey: string): Promise<TelemetryService>;
```

I will now move this to a `IPrivateTelemetryCreationService` and that service will leave in the shared process main.
Let me know your thoughts.

**Comment by weinand** [comment]
@isidorn LGTM, thanks!

**Comment by isidorn** [comment]
I have discussed a bit more with @bpasero and we will need a simpler signiture in order for it to be able to travel over the wire and be possible to work. Due to that I propose the following service:

```
export interface ICustomEndpointTelemetryService {
	publicLog(endpoint: ITelemetryEndpoint, eventName: string, data?: ITelemetryData): Promise<void>;
	publicLogError(endpoint: ITelemetryEndpoint, errorEventName: string, data?: ITelemetryData): Promise<void>;
}

export interface ITelemetryEndpoint {
	id: string;
	aiKey: string;
	sendErrorTelemetry: boolean;
}
```

This is the most elagant solution I could come up with. I am coding it up and should soon have something that works. Let me know what you think. Thanks!

**Comment by isidorn** [comment]
I have pushed the changes. I believe it is now much cleaner and I am happy with the change overall.

@bpasero @weinand @sbatten let me know if you have some suggestions and I can polish the code tomorrow.

@connor4312 does the js-debug extension send custom telemetry via the output telemetry event? If yes, when?
If not @weinand do you maybe know some debug extension that uses the custom telemetry? I just want to verify everything is still ok end to end. Thanks

**Comment by connor4312** [comment]
>  does the js-debug extension send custom telemetry via the output telemetry event? If yes, when?

Yes, pretty often. It'll send performance telemetry every few seconds whenever there's CDP or DAP calls

**Comment by isidorn** [comment]
@connor4312 great, I just checked on the vscode side that we the new changes there are no exceptions and everything seems to flow nicely.
Is there some easy way from the js-debug to just check if the telemetry is getting written to the database? Just to be sure...

**Comment by isidorn** [comment]
The thing which was already missing here is when running in the browser we were not reporting custom debug extension telemetry because we had this `noop` `BrowserDebugHelperService`.
I was wondering if we could also cover the browser case now @weinand 

@sbatten how does regular telemetry reporting work at the moment from the browser? Don't we have some node dependencies for this to work? Could we somehow piggy back on this mechanism so the customEndpoint telemetry is also reported from the browser?

**Comment by isidorn** [comment]
@sbatten cool, thanks for the pointer. 
@RMacfarlane might you know if it would be possible to create a custom `WebTelemetryAppander` that takes a passed `aiKey`?

**Comment by RMacfarlane** [comment]
All this appender is really doing is forwarding the telemetry information to the remote extension host agent service, which logs it with its own telemetry service:
https://github.com/microsoft/vscode-distro/blob/89f1579ed6a94b2dd7db7a8c29dddd48065cadc8/src/vs/server/remoteExtensionHostAgentServer.ts#L270-L287

https://github.com/microsoft/vscode-distro/commit/4553fb95f2fbb4382c38983f9b29ea2076ed1865

We could add another method here that also takes an `ITelemetryEndpoint` and creates appenders on the remote side

**Comment by isidorn** [comment]
Great, I have created this issue so we look into it together https://github.com/microsoft/vscode/issues/118808
