### ISSUE TITLE
Web smoke test: install and activate vscode-smoketest-check extension

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#118443]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=108012&view=logs&j=3792f238-f35e-5f82-0dbc-272432d9a0fb&t=bd1c96ef-8f6c-518c-1bd9-e87b3a72835d&l=108

```
1) VSCode Smoke Tests (Web)
       VSCode Smoke Tests (Web)
         Extensions
           install and activate vscode-smoketest-check extension:
     Error: Timeout: get text content 'footer[id="workbench.parts.statusbar"] .statusbar-item[title="smoke test"]' after 20 seconds.
      at poll (/Users/runner/work/1/s/test/automation/out/code.js:173:19)
      at async Code.waitForTextContent (/Users/runner/work/1/s/test/automation/out/code.js:234:16)
      at async StatusBar.waitForStatusbarText (/Users/runner/work/1/s/test/automation/out/statusbar.js:22:9)
      at async Context.<anonymous> (out/areas/extensions/extensions.test.js:22:13)

```

**Comment by bpasero** [comment]
Disabled via https://github.com/microsoft/vscode/commit/9c78fa40ca7ab6b58d0ab5cd33858a39a2b7102d

**Comment by sandy081** [comment]
This is failing because extension activation is taking some time and there is no finite time to know about this. I have removed the part that validates extension adding text to status bar because this test is mainly to validate extension installation and enablement. So, it is enough to check if extension is installed and enabled. Testing extension adding text to the status bar should be an api integration test that should be covered by corresponding status bar component owner.
