### ISSUE TITLE
Do not register keybindings for keys that are known to not work in the Browser

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#118435]
There are some keybindings (e.g. F10) that are registered in VS Code and that are shown to the user in menus and the command palette, but they are known to not work in the browser. To complicate matters, different browsers reserve different keybindings (e.g. `ctrl`+`shift`+`P` does not work in firefox).

These keybindings should not be registered.

**Comment by isidorn** [comment]
I plan to go through all the keybindings both in Exporer and Debug and check if they make sense in the browser.
If the keybindings does not work for "minor" commands we will just remove the default, however if it is an important command we will try to find an intuitive alternative that works in the browser.

**Comment by isidorn** [comment]
I checked Firefox, Safari and Chrome. And the only keybinding in Debug and Explorer land that does not work is `F10` for step over. All the others seem just fine on all browsers.
Due to that when we are in the browser I have changed the default keybinding for the step over to be `Alt/Option + F10`.
I was also thinking of `Shift + F10`, but the editor already takes this to show the context menu. I find the `Alt/Option + F10` an intuitive choice.
Tackled via https://github.com/microsoft/vscode/commit/f0cf34e073bd506334185273cd78e9a5cd368be5
