### ISSUE TITLE
VSCode should give better errors when failing to install extension dependencies.

### ISSUE THREAD

**Issue by TheFern2** [microsoft/vscode#118633]
I don't know if VSCode just handles all extension responsibilities to the extensions themselves, but I think extensions should be like any other package manager you name it APT, PIP, BREW, etc, if something fails, is the package manager responsibility to report a failure or error.

I've already ran into several issues installing vscode extensions offline that needed other stuff installed to work, but extensions vsix installed with zero warnings. This gives the impression everything is good.

Just to name a few:
- python, (this used to work before but then they added jupyter extension as a dep)
- remote ssh, (this one does give you some sensible warnings I'll admit)
- c++, (language tools)

So if an extension has a config where it lists all deps whether it is another extension or something else installed in X path. VSCode should check whether everything was installed, if not give errors/warnings.

**Comment by sandy081** [comment]
Are you installing a vsix or from Marketplace?

**Comment by TheFern2** [comment]
> Are you installing a vsix or from Marketplace?

Ah forgot that in the description, yes vsix, but in my opinion either install it should warn the user about failing deps installs, not just silently sort of install half way. Is Vscode fully dependent on extensions to do these warnings?

**Comment by sandy081** [comment]
Side loading using vsixs is a special case and it can be used for various purposes - like installing a vsix to test or installing while offline. It is expected by the user to make sure user installs all dependencies if installing by vsix. 

We try to install the deps if user is online and if offline we do not restrict because of above reasons. If you try to install from gallery then we make sure we install all dependencies like other package manager.
