### ISSUE TITLE
Terminal spawns in the wrong folder if the workspace folder name includes brackets

### ISSUE THREAD

**Issue by PichotM** [microsoft/vscode#118687]
- VS Code Version: Insiders 1.55.0
- OS Version: Windows 10 / Windows server 2019

Steps to Reproduce:

1. Create a workspace in a folder named [myworkspace] it is important to have the brackets.
2. Open the workspace / click on the "Terminal > New Terminal"
3. Instead of starting in your workspace you start at Powershell Path

Expected result: the terminal spawns at the root path of your workspace. It is caused by the [] brackets.

I haven't look at the code as it is a relatively big project but with PowerShell to navigate into a folder with brackets you need to format the destination path like this:
```ps1
# Does not work
cd E:\Projects\[Name]
# Works
cd 'E:\Projects\`[Name`]'
```
Good luck, thank you!

Does this issue occur when all extensions are disabled?: Yes

**Comment by benmccann** [comment]
`[...]` in file names are extremely common, so I hit this constantly

[SvelteKit uses `[...]` in file names such as `src/routes/[category]/[item].svelte` to denote parameters](https://kit.svelte.dev/docs#routing-advanced-rest-parameters) and [Next.js does as well](https://nextjs.org/docs/routing/dynamic-routes)

We have considered changing SvelteKit's syntax, but there are no good options that aren't otherwise broken on iTerm or Windows and it would also be a high migration cost for existing users

There are also other paths that are currently broken such as https://github.com/microsoft/vscode/issues/97941

I would expect the regex for matching a path segment could be improved to fix both these issues (perhaps something like `[^/\\]+`). Since this runs in the terminal it should run a very limited number of times since you can only display so many file paths at once, so there shouldn't be any performance concerns here either

**Comment by benmccann** [comment]
https://github.com/microsoft/vscode/blob/94c9ea46838a9a619aeafb7e8afd1170c967bb55/src/vs/workbench/contrib/terminal/browser/links/terminalValidatedLocalLinkProvider.ts#L23

**Comment by Tyriar** [comment]
> Bug is here:

@benmccann that's the place for [] not working in links, but not spawning in the wrong folder which is what this issue covers. See https://github.com/microsoft/vscode/issues/127138 for your issue

**Comment by Tyriar** [comment]
This works fine for both the integrated and external terminals.

![recording (43)](https://user-images.githubusercontent.com/2193314/126007120-085515a9-e715-44e3-8bfb-d73263e81d6e.gif)
