### ISSUE TITLE
Investigate how to avoid Safari's popup-blocker when opening browser windows and tabs asynchronously

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#118731]
When opening a new browser window or tab from a call back, Safari blocks that.

For details see https://stackoverflow.com/questions/20896507/why-does-browser-block-popup-windows-in-callback-but-not-otherwise and https://www.yaplex.com/blog/avoid-browser-pop-up-blockers and https://stackoverflow.com/questions/22007592/chrome-window-open-after-ajax-request-acts-like-popup

We probably need to use the suggested fix/workaound when opening the debuggee window in VS Code.

The tricky challenge is that for extension debugging the request for opening a new tab for the debuggee comes as a call back from the debug adapter/extension.
And the only user action (where the tab could be created without running into the popup blocker), is the "Start Debugging" (or "F5") action. But for this action VS Code does not really know upfront that a new tab will be needed...  

In theory we could always create a tab (without bringing it to front) when starting extension debugging. And if js-debug calls back into VS Code for launching the debuggee, we would populate the tab and bring it to front. And if no call back is received within some period of time we would close the unnecessary tab.

**Comment by isidorn** [comment]
@weinand thanks for compiling all the information there.
Here are my thoughts:
1) VS Code commands are always executed `async`, so even if we were to open the new window as soon as the `startDebugging` command is executed it would still be `async`. The call stack picture I attached shows this
2) We already have a `File > New Window` command which correctly opens a New Tab on Safari. And I do not think we are doing anything special for that action to work around pop up blockers, right @bpasero ?

So due to 2) it seems opening a window in an async call is fine, however there might be some timeout which the browsers have that we are hitting for the debug use case.

@weinand @bpasero is there a way to run `yarn web` and have some debug extension present so I could somehow start debugging? I need this in order to be able to experiment with this.

![Screenshot 2021-03-22 at 14 53 13](https://user-images.githubusercontent.com/1926584/112001365-31c25b00-8b1f-11eb-9365-36bdeb8c0594.png)

**Comment by isidorn** [comment]
@weinand @bpasero might the difference between the debug case of opening a new window and the `File > New Window` be that debug call `WorkspaceProvider.open` [here](https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/debug/browser/extensionHostDebugService.ts#L165) and the `New Window` command calls the `hostService` open [here](https://github.com/microsoft/vscode/blob/main/src/vs/workbench/browser/actions/windowActions.ts#L346)

Should we change the `extensionHostDebugService` to also use the `hostService`?

**Comment by bpasero** [comment]
In the end, the host service will be just delegating to the workspace provider, so it is the same:

https://github.com/microsoft/vscode/blob/97fde37887b6c90bb99f19f5c43c9d2ddb00ef4b/src/vs/workbench/services/host/browser/browserHostService.ts#L374-L383

**Comment by isidorn** [comment]
I have verified that we can open the new tab if we open it as soon as the user starts debugging.
Safari blocks our initial call due to timing, so the callback to `launchVSCode` comes a little bit too late.

@connor4312 is it possible that js-debug sends the `launchVSCode` request a bit sooner? I suspect Safari simple has a `ms` timeout and if we do this sooner it might just work.

If not, then we would have to try out @weinand suggestion. VS Code would need to open the new tab as soon as the user starts debugging. However the problem here is that we open a new tab with `args` and `env` coming from the `launchVSCode` request [here](https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/debug/browser/rawDebugSession.ts#L607). So I am not sure how to get that if we would to open a tab as soon as the user starts debugging.

Initial investigation has been done in March, thus assigning this to April to continue then.

**Comment by weinand** [comment]
@isidorn great, thanks for verifying our speculation.

I don't think we should rely on js-debug being able to call back "quickly". That doesn't sound like a robust solution...

If we would open a "placeholder" tab in advance (without knowing the args and env), could we later set the URL (with the args and env) like in the following snippet: 
  
```js
$('#a').on('click', function(e){
    e.preventDefault();
    var wi = window.open('about:blank', '_blank');

    setTimeout(function(){ // async
        wi.location.href = 'http://google.com';
    }, 500);
});
```

**Comment by connor4312** [comment]
Agreed. Especially in cases where js-debug hasn't been activated, depending on the speed of the VM it could take several seconds.

Opening a blank window ahead of time like Andre suggested is what I've done before in this situation. Alternately, you can detect if the popup is blocked and show a notification to the user, and re-open the window on click.

**Comment by isidorn** [comment]
Yes I think that approach makes sense. However currently the `hostService` does not allow this via its api. The `openWindow` returns an empty promise.
@bpasero is it possible to change the hostService change the `openWindow` such that it returns a window object.
I can look into this, if you think it makes sense overall.

If not possible, I also like @connor4312 suggestion. We show a modal dialog saying it was blocked, and have a button to reopen.

**Comment by weinand** [comment]
@connor4312 how can we detect that a popup is blocked?

**Comment by connor4312** [comment]
@weinand you can check whether the return from `window.open` is truthy

**Comment by isidorn** [comment]
I looked a bit into this and I like the is `window.open` truthy approach.

@bpasero I will change the [`WorkspaceProvider.open`](https://github.com/microsoft/vscode/blob/main/src/vs/workbench/services/host/browser/browserHostService.ts#L65) to return `boolean` which will indicate success.
If the window open is blocked I will show a model dialog with a warning:

"We could not start debugging due to a browser limitation"
"Start Debugging" "Cancel"

I would not mention opening of tabs / new windows in the dialog to not overcomplicate things. But let me know what you think, feedback on the wording is very welcome!

**Comment by bpasero** [comment]
When you change that, you need to also adopt Codespaces use of it, because the implementation is web API:

https://github.com/microsoft/vscode/blob/1f30107d9e64faad370732f2b77b8bec65577085/src/vs/workbench/workbench.web.api.ts#L299-L299

**Comment by isidorn** [comment]
@bpasero what is the process for that, should I just submit a PR for codespaces? If yes, are there docs how to do it (since I could not find the code location)?
Do you like my API suggestion? If we need to make this API stable then it might be better to return a `IOpenResult` option bag which would for now just have `success`, but in the future we could make this richer if needed.

**Comment by weinand** [comment]
@isidorn Yes, let's try to address this issue with the modal-dialog. If this UI becomes too painful, we can look into the more elegant solution.

**Comment by bpasero** [comment]
@isidorn yes a PR should work, please coordinate with @legomushroom

**Comment by isidorn** [comment]
I just verified that this flow works nicely. Here's how the dialog will look like. Once user presses Start Debugging a new tab properly opens.
Feedback welcome on the wording.

I have contacted @legomushroom on the PR for codespaces. Once I do that I will push this to master.

![Screenshot 2021-04-19 at 16 36 45](https://user-images.githubusercontent.com/1926584/115255723-d50e8c00-a12e-11eb-94aa-ef9f6d8a44ce.png)

**Comment by weinand** [comment]
@isidorn using the "Start debugging" both in the alert and the button action feels strange and is confusing for users.
In addition "browser limitation" sounds too negative for a security feature introduced for good intentions. 

I suggest to use a wording along the line of this:

> The debugger needs to open a new window for the debuggee. Due to a security feature of the browser, you must give permission to allow this.

**Comment by isidorn** [comment]
I really like your proposed wording. The only downside I see is "new window" since it is actually a new tab so it might be confusing.

And how would we call buttons, maybe
"Continue Debugging", "Cancel"

**Comment by weinand** [comment]
Just replace "new window" with "new tab" then ;-)

Button: "Continue in new tab" or "Open in new tab"

**Comment by weinand** [comment]
And the "Continue in new tab" does not really "start debugging" again (with prelaunch tasks etc.), right?

The alert just suspends the flow and pressing "Continue in new tab" resumes the flow, right?

**Comment by isidorn** [comment]
Yeah, let's go with "new tab" then.
And yes the alert suspends the flow and "continue in new tab" resumes the flow

**Comment by isidorn** [comment]
Voila
The cool thing is that "Continue in new tab" once pressed moves focus to the new tab. So I think the flow is good

![Screenshot 2021-04-19 at 17 57 44](https://user-images.githubusercontent.com/1926584/115266793-cb8a2180-a138-11eb-98f6-156d8265ca27.png)

**Comment by weinand** [comment]
In Safari you can configure "Tab vs. Window" here:

<img width="807" alt="2021-04-19_17-58-40" src="https://user-images.githubusercontent.com/1898161/115267043-08561880-a139-11eb-9b50-c5c9168cec65.png">

Is this possible in your scenario?

If we know whether the users is using tabs or windows we could use the correct term in the wording. If not, we could say "tab or window".

**Comment by isidorn** [comment]
Good catch, that setting indeed does affect it. And we do not know which one it is.
So I will update the wording to be "tab or window"

**Comment by connor4312** [comment]
@isidorn I get this running OSS on desktop

![](https://memes.peet.io/img/21-04-37812041-06bc-4d21-877d-8e99daf47908.png)

**Comment by weinand** [comment]
Yes, and it should only affect Safari (@connor4312 did you see this with Safari?)

@isidorn a "Continue" button would work for me too.

**Comment by connor4312** [comment]
This was running desktop vscode

**Comment by weinand** [comment]
@connor4312 oh sure (that was a stupid question... ;-)

**Comment by isidorn** [comment]
Pushed a fix, @connor4312 thanks a lot for letting me know.
@weinand I have changed the button to be called "Continue"

Also Codespaces have merged my PR which updates their use of API. So this whole flow should work nicely with Codespaces PPE already. I will try it out a bit later today.

**Comment by isidorn** [comment]
@jrieken @bpasero as mentioned in the standup I could adopt this in the [windowOpenNoOpener](https://github.com/microsoft/vscode/blob/main/src/vs/base/browser/dom.ts#L1196) and in the `OpenerService` and then it would be up to the clients to potentially respect the `success` flag or not.
However the `openerService` already returns a `boolean` and the clients seem to be ignoring it...

So in short, is there a client that would like the same experience I did for Debug?

**Comment by bpasero** [comment]
@isidorn we already provide a specific handler for opening links only in web and I think that location would be the right one to show a dialog if that fails:

https://github.com/microsoft/vscode/blob/65a9aa177689149ad0af6ed97d9c418180ea4ccd/src/vs/workbench/browser/window.ts#L138-L148

While I think it would be nice if each client would handle this, maybe it is more realistic to handle it there for all. As long as we can show the actual URL to open, I think that is sufficient context.

As for the `IWorkspaceProvider#open` API, I think a dialog would also make sense here, based on the returned result:

https://github.com/microsoft/vscode/blob/9dff5e0e0146656f534d61fe861afef0727415ca/src/vs/workbench/services/host/browser/browserHostService.ts#L385-L385

**Comment by isidorn** [comment]
@bpasero I did the changes as you suggested and this seems to work just fine in general. I verified that clicking on a link in Safari now shows the dialog I introduced. Feedback on the general wording is welcome.

Let's just keep our eyes open in case this dialog appears when it is not expected

![Screenshot 2021-04-20 at 15 47 00](https://user-images.githubusercontent.com/1926584/115406739-bcb27600-a1ef-11eb-8b6d-acaf3a51bb69.png)

**Comment by weinand** [comment]
@isidorn "The Browser..." or "Your Browser..."

**Comment by bpasero** [comment]
@isidorn thanks, would it make sense to show the URL in the dialog, or parts of it like the domain?

As inspiration, here is how our "Trusted Domains" dialog looks like when you ctrl-click on a link that is not trusted:

![image](https://user-images.githubusercontent.com/900690/115414820-ac51c980-a1f6-11eb-9390-899f126a9332.png)

**Comment by isidorn** [comment]
@bpasero makes sense. I made this change

![Screenshot 2021-04-20 at 16 48 23](https://user-images.githubusercontent.com/1926584/115416647-3d757000-a1f8-11eb-8932-f814e039745c.png)

**Comment by bpasero** [comment]
@isidorn thanks, if you write a test plan for this, please assign me so that I do some additional testing 👍

**Comment by isidorn** [comment]
@bpasero good point. There has been enough changes that deserve a test plan item. Will create later today and assign it to you.

**Comment by isidorn** [comment]
Created test plan item https://github.com/microsoft/vscode/issues/121763
