### ISSUE TITLE
Improve wording on "some keybindings are dispatched to the workbench by default" notification. 

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode#118749]
I'm running QPs today and one of the participants had never used VS Code before. He saw the following notification when he opened the terminal:

![image](https://user-images.githubusercontent.com/45497113/110832633-61847f80-8250-11eb-8aaa-65736fb9365c.png)

He was very confused by what it meant (and so am I tbh as English is not my first language 😅), and he mentioned this was one of the low points of his experience with VS Code. I was wondering if there's a way the wording there can be improved so that less experienced/advanced users understand what is happening?

Thanks!

**Comment by Tyriar** [comment]
Yeah "workbench" is kind of an advanced term. @luabud how about something like this?

> Some keybindings don't go to the terminal by default and are handled by <product> instead.

Suggestions welcome 🙂

**Comment by chocaloca** [comment]
I am commenting because I just saw this warning and was confused, so agree with @luabud. 

@Tyriar - How about going a step further - For the _**Configure Terminal Settings**_ piece, why not suggest/explain which setting addresses this keybinding issue? Even though Settings in this case offers two check boxes (one checked, one not checked in my case when opened), it is not 100% clear which of the two applies to this issue.

**Comment by Tyriar** [comment]
@chocaloca all 3 settings are relevant though, we try to keep notifications as small as possible as they're already annoying enough without a wall of text. The idea was to say "hey this is a thing btw" to allow users interested in configuring it to go to the right place, previously we did it by default and some users were confused by certain shell keybindings weren't working for them.

**Comment by luabud** [comment]
I do like your suggestion!

**Comment by Tyriar** [comment]
👍 

![image](https://user-images.githubusercontent.com/2193314/111384866-3c847800-8667-11eb-8fda-dfcd5b1d92ba.png)
