### ISSUE TITLE
Git Bash doesn't show up in select default terminal menu when already installed.

### ISSUE THREAD

**Issue by play4Tutorials** [microsoft/vscode#118705]
- VS Code Version: 1.54.1 (user setup)
- Commit: f30a9b7
- Date: 2021-03-04T22:40:57.714Z(4 days ago)
- Electron: 11.3.0
- Chrome: 87.0.4280.141
- Node.js: 12.18.3
- V8: 8.7.220.31-electron.0
- OS: Windows_NT ia32 6.1.7601
- OS Version: Windows 7 SP1(Service Pack 1)

Steps to Reproduce:(Make sure Git Bash is installed)
1. Open VS Code
2. Open a new terminal
3. Click on terminal name, a dropdown opens
4. Select "select default shell"
5. Git Bash not present

Does this issue occur when all extensions are disabled?: 

I have Git Bash installed(in E: drive). But when I try to configure it as default, the option isn't there. I can do it through the settings.json, but I think this should definitely be fixed.

I guess the problem is that VS Code doesn't look for Git Bash in any other place other than the default installation path

**Comment by play4Tutorials** [comment]
Screenshots: 
Select default shell menu:
![shot1](https://user-images.githubusercontent.com/67195650/110765102-d61fe400-8279-11eb-95bf-30a060279443.png)
Git Bash Installed Proof:
![shot2](https://user-images.githubusercontent.com/67195650/110765929-aae9c480-827a-11eb-8d06-f6f840faab8d.png)
![shot3](https://user-images.githubusercontent.com/67195650/110766230-f2705080-827a-11eb-9186-a272e7c4857c.png)

**Comment by Tyriar** [comment]
This is because it's in a non-standard install location, we don't attempt to search the system for it, only standard locations. You can configure it yourself using `terminal.integrated.windows.shell` and in the next version create a quick launch profile for it so it shows up here:

<img width="368" alt="Screen Shot 2021-03-19 at 10 56 52 AM" src="https://user-images.githubusercontent.com/2193314/111823132-d0da1f00-88a1-11eb-84bf-b8eba9d1cbd9.png">

**Comment by play4Tutorials** [comment]
alright thanks...
