### ISSUE TITLE
Inconsistent Toggling

### ISSUE THREAD

**Issue by garfieldbanks** [Microsoft/vscode#11871]
Ctrl+F doesn't toggle. Ctrl+H doesn't toggle. Ctrl+Shift+H doesn't toggle.

Why does Ctrl+Shift+F toggle?

Ctrl+F and Ctrl+H will switch from one to the other.

The same is not true for Ctrl+Shift+F and Ctrl+Shift+H.

Can you give me an option in settings to fix this?

I want to disable all toggling between the text editor and the find box. Ctrl+Shift+F should never move me to the text editor.

Ctrl+Shift+F and Ctrl+Shift+H should switch between one another.

**Comment by sandy081** [comment]
@garfieldbanks Ctrl+Shift+F toggles because it is a Show View action. All these actions toggle between the left view and the editor. I agree there is inconsistency between Find and Search. But removing this toggling causes inconsistency with other views. Also most of the users would have got used to this toggling behaviour between Views and Editors.

**Comment by garfieldbanks** [comment]
I'd honestly rather turn that view/editor toggle stuff off.

Would that be easier to implement a setting for?

**Comment by garfieldbanks** [comment]
In either case I'm only asking for a setting.

**Comment by sandy081** [comment]
@garfieldbanks A setting can be provided. Will think about it. Thanks

**Comment by sandy081** [comment]
@garfieldbanks Introduced a new action `workbench.action.findInFiles`. This action shows and focusses the Search input if it is not visible / focussed. This action is also bound to same key binding <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>f</kbd>

There is no change in behaviour in following
- `View -> Search` toggles.
- Typing <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>f</kbd> also toggles. Here also no change in behaviour.

Following changes in behaviour which is good:
- `Edit -> Find In Files` does not toggles. Since it uses the new action.
- Typing <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>f</kbd> when Search input widget is not in focus, focusses Search input widget. Eg: If replace widget is in focus typing this key binding will focus the search input widget.

To disable toggling behavior for <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>f</kbd> do the following
- Open `keybindings.json` and add
```
{ "key": "shift+ctrl+f", "command": "workbench.action.findInFiles" }
```

**Comment by garfieldbanks** [comment]
@sandy081 Do you want me to verify it? Do I need to be an insider?

**Comment by sandy081** [comment]
@garfieldbanks It would be great if you do so. 

Yes, this will be available in insider build and we have frozen the insiders builds for this week, so this will be available only after this week. 

I will let you know once this is available.

Thanks
