### ISSUE TITLE
Terminal input shows space characters when I have typed none

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#118804]
This started yesterday.

I am on Remote WSL.

![recording (7)](https://user-images.githubusercontent.com/22350/110917289-99320c80-82ce-11eb-8739-e184d3195eef.gif)

**Comment by joaomoreno** [comment]
Setting `terminal.integrated.localEchoLatencyThreshold` to -1 is a temporary workaround which works.

**Comment by Tyriar** [comment]
@connor4312 @TylerLeonhardt any ideas? Could adding the pty host process in remote have caused this somehow? Not sure what other changes could have caused it.

**Comment by Tyriar** [comment]
I can't look into this for a few hours, I'm guessing something that it expected was synchronous is now asynchronous.

**Comment by TylerLeonhardt** [comment]
I wonder... when you hit ENTER, does it run correctly? I wonder if this is more of a cosmetic issue than impacting what is actually run.

**Comment by Tyriar** [comment]
Yes it's cosmetic only

**Comment by connor4312** [comment]
Typeahead hasn't changed in several weeks, so I'm guessing pty in the remote is it. I was able to reproduce this in Insiders, but annoyingly could not do so in a dev setup from OSS -- anything that was fixed since the last Insiders?

Would any of the pty process work cause [flushOutput](https://github.com/microsoft/vscode/blob/a90759b5395e9bf4be99e508cdb8a01cd55942e4/src/vs/workbench/contrib/terminal/browser/terminalTypeAheadAddon.ts#L43) to no longer be synchronous? That would be a prime suspect.

It seems to only happen when typing somewhat rapidly, so the [physicalCursor](https://github.com/microsoft/vscode/blob/a90759b5395e9bf4be99e508cdb8a01cd55942e4/src/vs/workbench/contrib/terminal/browser/terminalTypeAheadAddon.ts#L903) is probably incorrect in these scenarios. I can try to debug Insiders off sourcemaps if we can't get an OSS repro...

**Comment by connor4312** [comment]
I don't repro this on Insiders today. Let me know if you do, or if it comes back

**Comment by Tyriar** [comment]
I could reproduce it the other day in WSL but not out of sources, but now can't 🤷. Good news I guess, @joaomoreno do you see it anymore?

**Comment by joaomoreno** [comment]
No more repro!
