### ISSUE TITLE
html cant find js function

### ISSUE THREAD

**Issue by itayazu** [microsoft/vscode#118915]
![html](https://user-images.githubusercontent.com/77123471/111070292-c8689980-84d9-11eb-8787-79eecf4e2279.jpg)
![js](https://user-images.githubusercontent.com/77123471/111070295-ca325d00-84d9-11eb-88fe-5353348fcd5d.jpg)
![web](https://user-images.githubusercontent.com/77123471/111070296-cacaf380-84d9-11eb-8551-7813d4ee29c1.jpg)

when i run the button on the html i get an error that the function is not defined but it is.. what can i do

**Comment by RPwnage** [comment]
This issue belongs on [stackoverflow](https://stackoverflow.com/questions/tagged/javascript) rather then the issue section of an IDE...
But heres the solution to fix your problems anyway;
- You can't just write HTML Tags inside a alert function without quotation. (I'm talking about your ```<br/>```)
   - replace your ```<br/>``` with ```"\n"``` if you want it to act as a linebreak in your alert.
- The HTML onClick tag can't find your ```show_prod()``` function, due to the previous exception.

**Comment by aeschli** [comment]
Thanks @RPwnage for the reply!
