### ISSUE TITLE
Distinct color for python "self" and "cls" in default themes with semantic highlighting.

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode#118946]
In python, the first parameter to a class method has a special meaning. It is usually denoted by the name `self` or `cls`. Pylance language server for the purpose of semantic highlighing marks it with the special semantic token type "selfParameter" or "clsParameter". Default themes should use this tokens to distinguish them by color from ordinary method parameters. For example:
```json
"[Default Dark+]": {
    "rules": {
        "selfParameter": "#569CD6",
        "clsParameter": "#569CD6"
    }
}
```

**Comment by gjsjohnmurray** [comment]
What is the case for making default themes handle custom semantic token types for one particular extension?

**Comment by helafumpek** [comment]
I would say to improve the comfort of writing code in Python just a little bit more. It is the second most used programming language among VS Code users. Python is the most popular extension in the marketplace with over 32M downloads. It seems to me that a small cosmetic change improving the comfort of writing code in such widely used language is not a bizarre idea.
Pylance is planned to become the default server for Python and is currently the only one supporting semantic highlighting. It's also a Microsoft project. So obviously I referred to it.

**Comment by aeschli** [comment]
We are very careful with changes to the default themes. There's a high potential of getting a lot of negative reactions as users are very sensitive to their colors.

**Comment by helafumpek** [comment]
It is not my intention to impose my taste on anyone. It is just that other popular editors for Python distinguish the words `self` and `cls` from rest of the variables. Even though these are not formally special names in Python, the practice is so firmly established that linters indicate a deviation from it as an error.
Even default theme distinguish between `self` and the rest of the code, although I'm not sure if it was intentional.
![nosem](https://user-images.githubusercontent.com/55078611/111186679-8744b800-85b3-11eb-9a81-0861a6bb341d.png)
But when the semantic highlighting is enabled (which is now default), all variables, properties and parameters are colored exactly the same. Sometimes it happens you get a whole block of code made of initial assignments and everything is exactly the same color. 
![block](https://user-images.githubusercontent.com/55078611/111186431-4d73b180-85b3-11eb-8449-17222c8a5c73.png)
I've peeked into default themes and it seems there are some rules there added to increase readability for a specific language - C++, Java, Go, Groovy. So it wouldn't be creating a precedence to add something for Python.
But I understand the need for carefulness.

**Comment by aeschli** [comment]
Without semantic highlighting, `self` get's the TextMate scope `variable.language`.  In our Default themes, that scope get's colored like a keyword.
```
		{
			"name": "this.self",
			"scope": "variable.language",
			"settings": {
				"foreground": "#569cd6"
			}
		}
```
![image](https://user-images.githubusercontent.com/6461412/111225464-1e276980-85e0-11eb-9759-fda15ff41aae.png)

I wasn't able to get the pylance semantic highlighting working, but I'm a Python/Pylance newbie. My guess is that the pylance extension defines a custom semantic token type `selfParameter` that extends `paremeter`. That would explain why `self` is now colored like the other parameters.
To find that out you can use the `Developer: Inspect Editor Tokens and Scopes` on `self`

Instead of inheriting from `parameter`, the extension could define a default a [fallback TextMate Scope](
https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide#semantic-token-scope-map)  `variable.language`  for `selfParameter`. That would preserve the current coloring where `self` is rather seen as a keywords than a parameter.

Can you file an issue against https://github.com/microsoft/pylance-release/issues. I'm happy to join the discussion there.

**Comment by helafumpek** [comment]
This is `selfParameter` and `clsParameter` scope:
![self](https://user-images.githubusercontent.com/55078611/111280914-a9cee380-863c-11eb-9eda-04cca62b8a94.png)
This is class `property` scope:
![property](https://user-images.githubusercontent.com/55078611/111280968-b94e2c80-863c-11eb-93e6-9cb26011443e.png)
And this is function `parameter` scope:
![parameter](https://user-images.githubusercontent.com/55078611/111281052-d08d1a00-863c-11eb-9641-4ef8c670537b.png)
It seems to me that each one should be visually different from the others, since they represent different types of entities in the code.
I'm not sure exactly what I would have to report in an issue to Pylance. Obviously you have a much better understanding of how themes work in VSC, so I believe you can certainly explain the issue better to the devs there.

**Comment by aeschli** [comment]
Can you file an issue against https://github.com/microsoft/pylance-release/issues. I'm happy to join the discussion there.
