### ISSUE TITLE
Notebook editor icons do not appear until you select a cell

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#118996]
- VS Code Version: 1.55.0-insiders
- OS Version: Mac

Steps to Reproduce:

1. Install GitHub issues notebook extension
2. Open an github issue notebook document
3. Notice how the `Lock` icon is not visible in editor title area
4. Select a cell, now the icon appears

We'd like the icon to appear when the document is open and not when user sets focus to the document.

@rebornix /cc

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by roblourens** [comment]
@rebornix the problem is that this doesn't fire when opening a notebook, even though it has a focused element: https://github.com/microsoft/vscode/blob/216bff5771527f67800b58cee745ed8217c07c9b/src/vs/workbench/contrib/notebook/browser/notebookEditorWidget.ts#L613-L613

Do you think this changed recently due to your changes? If not I can just make sure this code gets hit to initialize context keys.
