### ISSUE TITLE
HTML - Options inside data list tag with close tag & Unwanted spaces inside it.

### ISSUE THREAD

**Issue by pixieaka** [microsoft/vscode#118904]
- VS Code Version: 1.54.2
- OS Version: Windows 10 20H2 Build 19042.572

Steps to Reproduce:

1. Just `<datalist>` element

**Problems**
1. Unwanted option close tag.
2. Unwanted spaces before option tag when add multiple options without closing tag.

![12](https://user-images.githubusercontent.com/17777237/111056923-e4454e80-848b-11eb-9fbf-e54436caa9bb.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment]
Whether we add an indent or not depends whether the element is a [`void` element.](https://html.spec.whatwg.org/multipage/syntax.html#void-elements)

While [in some situations](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/option) the closing tag for option can be ommited, it's necessary for others, so that's why we add the ident.

The completion is an Emmet completion and I believe there's a way to configure the completion snippet. Assigning to @rzhao271

**Comment by rzhao271** [comment]
@pixieaka `datal` and `opt`/`option` are defined in [an upstream config file](https://github.com/emmetio/emmet/blob/master/snippets/html.json#L93).
Try adding a slash at the end, like `opt/` or `option/`.
If you think `option` should close by default, try adding [custom snippets](https://code.visualstudio.com/docs/editor/emmet#_using-custom-emmet-snippets).

**Comment by pixieaka** [comment]
@rzhao271 Yeah you can close this. But I notice that after `/` character suggestions disappear and user should `ctrl + space` to get suggestions back and after this press tab to insert element with self closed tag. Can this solve ?

**Comment by pixieaka** [comment]
@rzhao271 Yeah you can close this. But I notice that after `/` character suggestions has disappeared and user should press `ctrl + space` to get suggestions back and after this press tab to insert element with self closed tag. Can this solved ?
