### ISSUE TITLE
Extension host suddenly stopped working

### ISSUE THREAD

**Issue by hanchiang-cf** [microsoft/vscode#118939]
Issue Type: <b>Bug</b>

I am on macbook pro BigSur M1, 2020. VsCode's extensions crashed suddenly every few minutes.

These are the extensions I am using:
Pin up, ESLint, gitignore, GitLens, Jest Runner, Jupyter, Markdown All in one, OpenAPI preview, openapi-lint, Path intellisense, Prettier, Python, stylelint, TODO highlight, Trailing spaces, YAML

VS Code version: Code 1.54.2 (fd6f3bce6709b121a895d042d343d71f317d74e7, 2021-03-11T00:56:09.783Z)
OS version: Darwin x64 20.1.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|VirtualApple @ 2.50GHz processor (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.10GB free)|
|Process Argv|. --crash-reporter-id 180d1c39-dba0-44a5-82e3-16588e1c2987|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|2.3.0
gitignore|cod|0.6.0
vscode-eslint|dba|2.1.17
gitlens|eam|11.3.0
prettier-vscode|esb|6.2.0
vscode-jest-runner|fir|0.4.31
openapi-lint|mer|1.2.0
python|ms-|2021.2.636928669
jupyter|ms-|2021.3.619093157
vscode-yaml|red|0.16.0
pin-up|sae|1.4.1
trailing-spaces|sha|0.3.1
vscode-stylelint|sty|0.86.0
vscode-todo-highlight|way|1.0.4
markdown-all-in-one|yzh|3.4.0
openapi-preview|zoe|1.7.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubset:30270708
pythontb:30265425
vspre833:30267464
vsdfh931:30275552

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to try and pinpoint exactly which extension is crashing the EH.

**Comment by alexdima** [comment]
It looks like the issue is caused by one of your installed extensions. All extensions execute together on a single nodejs process, so in order to narrow down the possible problematic extension, please try the following:
* run `F1 > Help: Start Extension Bisect`
* (this will restart VS Code with half of your extensions disabled)
* try to do the steps which reproduce the problem
* if the problem reproduces, click "This is bad" (this narrows down the problematic extension to the half which was enabled)
* if the problem does not reproduce, click "Good now" (this narrows down the problematic extension to the half which was disabled)
* these steps will repeat until the problematic extension is found

| initial | step | final |
|---|---|---|
| ![image](https://user-images.githubusercontent.com/5047891/101918658-e9170f80-3bc9-11eb-9977-857baa291937.png) | ![image](https://user-images.githubusercontent.com/5047891/101918683-ef0cf080-3bc9-11eb-9f9e-98b0177991b2.png) | ![image](https://user-images.githubusercontent.com/5047891/101918706-f502d180-3bc9-11eb-8c86-e56355958bd4.png) |
