### ISSUE TITLE
IntelliSense not responsive after 'as' syntax in TypeScript  

### ISSUE THREAD

**Issue by pixieaka** [microsoft/vscode#118935]
- VS Code Version: 1.54.2
- OS Version: Windows 10 20H2 Build 19042.572

Steps to Reproduce:

1. The options not show after type `as` immediately. It show after close the menu and reopen it again with `ctrl + space` 

![12](https://user-images.githubusercontent.com/17777237/111093576-f71a5a80-8541-11eb-94fb-595e2b00644f.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
@jrieken This is happening because the two snippets match the text that has been typed: `as `.  It feels a little weird that typing after `as ` does not cause suggestions to be retriggered. On the other hand, retriggering suggestions would also feel weird if you were trying to filter down a list of snippet completions

Assigning you since this is a generic suggest issue, not TS specific

**Comment by jrieken** [comment]
@pixieaka I don't really understand what you expect. In your gif I see you typing `as` and then a space. We don't trigger suggestion on space, are you asking for that? Once you start tying word character, like `n`, we do ask for further completions

**Comment by pixieaka** [comment]
@jrieken  It's not trigger with first character for first time also, In example I must type first character and delete it and type it again to get suggestions.

![1](https://user-images.githubusercontent.com/17777237/111538142-ff0e1080-8774-11eb-8a53-7f54514b55d4.gif)

**Comment by pixieaka** [comment]
@jrieken Note: When I change language from TypeScript to JavaScript the suggestions shows from first character.

**Comment by jrieken** [comment]
@mjbvz See above comments - I believe TypeScript (rightfully or wrongly) doesn't return suggestions that match. I debugged and can confirm that we do retrigger completions after the typing a word character after the space

**Comment by mjbvz** [comment]
@jrieken Starting with `document.getElementById('x')`, if I type `as x`, I only see a single `provideCompletionItems` call. This call happens immediately when I start typing `as`. It does not trigger when I type `x`

**Comment by jrieken** [comment]
> @jrieken Starting with document.getElementById('x')

That's not how this issue is reported (see [gif](

![](https://user-images.githubusercontent.com/17777237/111093576-f71a5a80-8541-11eb-94fb-595e2b00644f.gif)
)). Steps:

* use TS language
* have `document.getElementById('x') ` (space at the end)
* type `as ` (space at the end)
* type another character
* 😢 no suggestions
* change language to JS, repeat steps
* suggestions

**Comment by mjbvz** [comment]
Those are the same steps I followed. Completions are only requested once: when you type `a`

**Comment by mjbvz** [comment]
@jrieken Here's the point where the suggest provide filters out the second call to `provideCompletionItems`. With the suggestions from `as` still showing, I typed space then `x`. The main TS completion provider is not called because of this code:

![Screen Shot 2021-03-22 at 2 28 20 PM](https://user-images.githubusercontent.com/12821956/112060807-e017d180-8b1a-11eb-952f-557f0bb29251.png)

TypeScript actually registered two completion providers: the main one for suggestions and a secondary one for JSDoc comments. The JSDoc comment one is called again, but the main one is not

**Comment by jrieken** [comment]
Thanks @mjbvz. I was only checking iff completions are requested, not for which providers they are requested. 

So, this is the problem: when typing the `a` of "as" we trigger completions and both snippets and TypeScript return suggestions. Now, while suggestions show we type into a new word ("as H") which retriggers suggestions. However, when re-triggering we ignore those providers that contributed to the existing result (we must do that to keep suggestions stable, e.g otherwise no TS suggestion can contain trigger characters like `.`). Now, the "contributed to the result" is the initial set of completions and the set after filtering against the prefix. In the sample you only see completions from the snippet provider but the unfiltered set also contains TypeScript completions. In order to get this right we would need to take the unfiltered set, not the initial completion. I believe that makes sense but this needs careful thinking first.
