### ISSUE TITLE
Theme

### ISSUE THREAD

**Issue by AgungBurhanudin** [microsoft/vscode#119045]
After update to version 1.54 , dark theme in visual studio code for python is bad

in 1.53 I can see error indent , and different color for Model / Object / function / class, but in this version all source code white 

![Screenshot from 2021-03-16 13-54-39](https://user-images.githubusercontent.com/25579220/111267897-2d013100-865f-11eb-9851-7b7a6f1de47f.png)

**Comment by aeschli** [comment]
![image](https://user-images.githubusercontent.com/6461412/111312366-7e112500-865f-11eb-874c-e517327c1d37.png)

I tested that in 1.51 and don't think the import colors have changed.

Can you add a small source sample and show what has changed?
Also, please test with all extensions disabled, in particular the Python extension.

If the change was caused by the Python extension (they added semantic coloring recently) please file an issue against that repo. 
https://github.com/Microsoft/vscode-python/issues
