### ISSUE TITLE
It's difficult to tell when the integrated terminal has keyboard focus

### ISSUE THREAD

**Issue by craxal** [microsoft/vscode#119193]
Issue Type: <b>Feature Request</b>

It's very difficult to tell at a glance which panel in VS Code has keyboard focus. I can't tell you how many times I started typing out a terminal command only to realize that the Explorer tree or an editor actually had focus.

There are two things I'd like to see:
1. A better visual indicator of which panel is the focused panel.
2. Change the appearance of the terminal cursor when the terminal doesn't have focus.

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T11:57:12.728Z)
OS version: Darwin x64 20.3.0

**Comment by isidorn** [comment]
No plans to do an explorer specific solution.
I believe this is a fair feature request against our laout, thus forwarding to @sbatten 
fyi @misolori

**Comment by dandavison** [comment]
> Change the appearance of the terminal cursor when the terminal doesn't have focus.

To expand on this, when `terminal.integrated.cursorStyle` is set to `block`, the terminal cursor does change appearance. However, when it is set to `line`, the cursor doesn't change at all when the terminal loses focus, and it is impossible to detect visually whether editor or terminal is focused.

I find that this goes strongly counter to expectations: since the terminal and the editor are tightly integrated in VS Code, switching between the two with keyboard shortcuts feels similar to switching between editor panes, or between panes in a terminal emulator, in which case one expects the cursor to be hidden in a pane that does not have input focus.
