### ISSUE TITLE
Remember workspace profile permissions choice

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#119141]

**Comment by rzhao271** [comment]
Any verification steps?

**Comment by meganrogge** [comment]
To verify, add a workspace profile (in workspace settings) and select it from the dropdown. Select allow. Alter the profile. Select it again. You shouldn't see the prompt.

**Comment by rzhao271** [comment]
It works, though I'm a bit confused what the purpose is.
For example, I can add a new profile with Git Bash as a source, and then the message asks whether I trust bash to open with the given args (like --login). Afterwards, I can change the source to PowerShell, and then I don't get the prompt anymore.

I wonder if there's a way to clarify to the user that it's more about marking all profiles in the workspace as safe, rather than marking just that one profile as safe? Additionally, even after accepting the workspace profiles as safe, I'm not sure how to tell apart a workspace profile from a non-workspace profile in the dropdown, without looking through my settings.
