### ISSUE TITLE
Icon overlay support

### ISSUE THREAD

**Issue by be5invis** [Microsoft/vscode#11911]
Give ability to assign multiple icons to some targets so that we can add overlay to existing icons.

Purposal:

``` js
"fileNames" : {
    ".editorconfig" : ["file", "overlay.config"], // Assign a multiple-layer icon
    ".test." : {"overlays" : "overlay.test"},     // Assign an overlay to existing icon
    ".tests." : {"overlays" : "overlay.test"},
}
```

**Comment by aeschli** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.
If you disagree and feel that this issue is crucial: We're happy to listen and to reconsider.
Maybe you want to give it a try yourself and provide the feature through an extension or a PR: We're happy to give advise and get you started.
Thanks for your understanding. Thanks for helping and happy coding!
