### ISSUE TITLE
Strange file input created when opening link from Markdown preview

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#119163]
On Windows:

1. Open a local empty folder
1. Create an empty `file.json`
2. Create a `file.md` with the following contents: `[Click Here](/file.json)`
3. Open the Markdown preview
4. Click the `Click Here` link

🐛 File opens with a strange input, as if its entire path is the file name. Also, if you open `file.json` from the Explorer, it now appears twice in Quick Open: once normally and another in the weird long format.

![image](https://user-images.githubusercontent.com/22350/111436248-feb33e00-86be-11eb-86e1-6fc6241bc7d1.png)

**Comment by bpasero** [comment]
@joaomoreno windows? local/wsl?

Doesn't repro on macOS so I suspect an issue with how URIs are being created from the markdown.

**Comment by joaomoreno** [comment]
This is local Windows.

**Comment by bpasero** [comment]
There is some weird encoding going on with that URL, here is what it should look like:

`file:///c%3A/Users/bpasero/Desktop/markdown-empty/file.json`

And here is what I get:

`file:///c%3A%5CUsers%5Cbpasero%5CDesktop%5Cmarkdown-empty%5Cfile.json`

**Comment by hantatsang** [comment]
I'm working on this issue. I've logged out how the Markdown Preview renders the paths to HTML with "Click Here Absolute Path" containing the same link as in the issue:

**Markdown:**

```md
[Click Here Absolute Path](/file.json)
[Click Here Relative Path](./file.json)
```

**HTML Output:**

```html
<p data-line="0" class="code-line">
    <a 
        href="/file///c:/path/to/markdown-preview-strange-file/file.json"
        data-href="/file///c:/path/to/markdown-preview-strange-file/file.json">
        Click Here Absolute Path
    </a>
    <a href="./file.json" data-href="./file.json">
        Click Here Relative Path
    </a>
</p>
```

The paths are correct though. Plus I think the link should be given as a relative path (ie. `[Click Here](./file.json)`) instead of an absolute path. Giving the absolute path here (`/file.json`) is not correct.

Btw, I've tried on other IDEs for comparison, they all don't open the absolute path link properly (or open nothing at all). The relative path link always works.

Not sure how would you want to tackle this now?

**Comment by jeanp413** [comment]
@hantatsang I have a hunch that maybe the issue is somewhat related to https://github.com/microsoft/vscode/commit/9f08368e92607e3603d8aa3e9583a2dcc5baa6cc#

**Comment by hantatsang** [comment]
Thanks, @jeanp413 for the pointer. I misunderstood the issue at first...
