### ISSUE TITLE
my project's config.json file empty 

### ISSUE THREAD

**Issue by frankorama** [Microsoft/vscode#11910]
- VSCode Version:1.5.2
- OS Version: OSX 10.11.6

Steps to Reproduce:

1. Open any project containing a config.json file
2. Click on config.json file to open it

Contents of config.json file is either empty, or VS Code displays the content of the previously viewed file

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by frankorama** [comment]
When I closed and re-openned  VSCode, the issue went away (should have tried that first, sorry)

**Comment by bpasero** [comment]
Ok let me know when this happens again, but we need some reproducible steps...
