### ISSUE TITLE
VSCode freezes when fed too much terminal output

### ISSUE THREAD

**Issue by bheadmaster** [microsoft/vscode#119178]
Issue Type: <b>Bug</b>

- open terminal emulator in VS Code (Ctrl+`)
- type "base64 -w0 < /dev/urandom"
- wait for 5-30 seconds for VSCode to freeze and become unresponsive

VS Code version: Code 1.54.1 (f30a9b73e8ffc278e71575118b6bf568f04587c8, 2021-03-04T22:38:50.094Z)
OS version: Linux x64 5.8.0-44-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 2558)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 2|
|Memory (System)|15.44GB (3.38GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id eeb342b8-f655-4d63-b7eb-fa200326d848|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
gitlens|eam|11.3.0
vsc-material-theme|Equ|33.2.0
vsc-material-theme-icons|equ|1.2.2
vscode-pull-request-github|Git|0.24.0
go|gol|0.23.2
dotenv|mik|1.0.1
vscode-docker|ms-|1.11.0
python|ms-|2021.3.658691958
vscode-pylance|ms-|2021.3.1
jupyter|ms-|2021.3.619093157
remote-containers|ms-|0.163.2
remote-ssh|ms-|0.65.1
remote-ssh-edit|ms-|0.65.1
cpptools|ms-|1.2.2
vsliveshare|ms-|1.0.3968
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
remote-vscode|raf|1.1.0
vscode-icons|vsc|11.2.0
vim|vsc|1.18.9

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubset:30270708
vspre833:30267464
vsfjg287:30275553
vshan820:30276952

```

</details>

**Comment by dmz38** [comment]
I can also reproduce this.  It's really bad because when this is the reason for the crash, when VSCode recovers it attempts to open the terminal again and can get stuck on the same terminal/issue.

Version: 1.54.3 (user setup)
Commit: 2b9aebd5354a3629c3aba0a5f5df49f43d6689f8
Date: 2021-03-15T10:55:45.459Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

Extension | Author (truncated) | Version
-- | -- | --
remote-containers | ms- | 0.163.2
remote-ssh | ms- | 0.65.1
remote-ssh-edit | ms- | 0.65.1
remote-wsl | ms- | 0.54.5
vscode-remote-extensionpack | ms- | 0.20.0
open-in-browser | tec | 2.0.0
vscode-intelephense-client | bme | 1.6.3
vscode-markdownlint | Dav | 0.39.0
prettier-vscode | esb | 6.3.1
php-intellisense | fel | 2.3.14
gitblame | wad | 6.0.2

No current experiments.

**Comment by jaques-sam** [comment]
Same for me. I'm using latest Windows 10 

>Version: 1.55.0 (system setup)
Commit: c185983a683d14c396952dd432459097bc7f757f
Date: 2021-03-30T16:01:55.261Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by timaelliott** [comment]
Happens to me all the time. I accidentally cat a large file or get too many results in a db cli and my terminal completely freezes. Have to close and restart VSCode entirely.

**Comment by jaques-sam** [comment]
You don’t need to restart you VSCode completely, just click on the delete icon of the terminal.

Next to the freeze issue, I also have weird multiline issues when e.g. typing a long git commit or scroll within a large git diff output.

**Comment by ezpuzz** [comment]
for me it's output of docker-compose logs

**Comment by jandem** [comment]
> Next to the freeze issue, I also have weird multiline issues when e.g. typing a long git commit or scroll within a large git diff output.

That's likely #120810.

**Comment by Tyriar** [comment]
I can't repro this.  Back in 1.53 flow control was added which protects against flooding the terminal was too much data, however it's probably still possible for lock ups to happen if rendering on your machine takes > 16ms. Try tweaking `terminal.integrated.gpuAcceleration` to see if that helps, if not I suspect just the UI is just always busy with rendering and hitting the bin icon will probably still work since flow control will prevent the terminal process from getting too far ahead.

**Comment by timaelliott** [comment]
This is still occurring fyi. Right now I have a frozen window because stdout was spammed.  version 1.58.1

**Comment by jaques-sam** [comment]
Did you try With the latest VSCode? I have not seen the issue any more, so this seems fixed.
