### ISSUE TITLE
Possible to bring up multiple dialogs on same dirty file when closing

### ISSUE THREAD

**Issue by mohsen1** [Microsoft/vscode#11928]
- VSCode Version: 1.5.2
- OS Version: OS X

Steps to Reproduce:
1.  Open a few files
2. Make a file dirty
3. Open a few more files
4. Hit Cmd+W multiple time very quickly 
5. When tabs close one by one and it reaches to the file that was dirty, it prompts you to save that file, choose the cancel option

VSCode will show you the save dialog again and again. Apparently it cached the close command to that file.

**Comment by bpasero** [comment]
Good catch 👍

**Comment by bpasero** [comment]
Bottom line of this problem is that when a dialog (such as the confirm dialog when closing a dirty editor) opens, for some reason it is still possible to execute commands via keyboard on macOS. These just pile up and execute after the dialog is dismissed. I have not found a solution that would not be a hack. If someone has ideas how to tackle this, jump on it.

**Comment by DHainzl** [comment]
Additionally, it seems that not only keyboard events, but also mouse events are piling up (in my concrete case, middle mouse click on a tab).
