### ISSUE TITLE
Do not prompt to terminate running task when closing VS Code

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#1194]
We only prompt for data loss. IMHO we should just terminate the task

![screen shot 2015-12-11 at 12 26 01](https://cloud.githubusercontent.com/assets/1926584/11742718/5e44994e-a002-11e5-81b5-e9aa44872e1b.png)

**Comment by dbaeumer** [comment]
@isidorn there are different camps here :-). I added this because users were complaining that I simply terminated the task (e.g. they had longer running background tasks activated).

I already proposed the following: watching tasks we terminate without asking as long as not specified different in the tasks.json. Non watching tasks we prompt unless specified different in the tasks.json.

**Comment by egamma** [comment]
The proposal to kill watching tasks automatically makes sense to me and it covers @isidorn's scenario.

**Comment by isidorn** [comment]
:+1: for killing watching tasks

**Comment by bpasero** [comment]
+ :100: for not showing this when a watch task is running. I think this would especially make the extension development case nicer.

**Comment by dbaeumer** [comment]
Implemented as proposed. The new flag to control this for a task is promptOnClose. For watching tasks this is false by default.

**Comment by bpasero** [comment]
:sunny:
