### ISSUE TITLE
Debug: hover is really huge and in my way at times

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#119487]
I often find the hover to be in my way, especially when it decides to take that much space:

![image](https://user-images.githubusercontent.com/900690/112026498-8fae6d00-8b36-11eb-957c-59ba435ed9ee.png)

**Comment by bpasero** [comment]
Devtools comparison:

![image](https://user-images.githubusercontent.com/900690/112026646-b2d91c80-8b36-11eb-9886-e6e8d3768594.png)

**Comment by isidorn** [comment]
@bpasero I agree this is a problem. However I think the devtools comparison is not fair, since they have a fixed size limit (as we did before) and that solution also does not work.
We need to have flexible size, however we should probably always default back to the smaller one, and only on explicit user expand increase
Assigning to this milestone to investigate, might push out to debt week.

**Comment by isidorn** [comment]
I have tried to make the debug hover less aggressive by:
* Decreasing width and height a bit
* Making it easier to hide - previously hiding was done with a timeout which I think was just wrong

Try it out and let me know if you think this is an improvement. Thanks!

**Comment by bpasero** [comment]
> Making it easier to hide - previously hiding was done with a timeout which I think was just wrong

I saw the change and how it was using `editor.hover.delay` which was probably wrong, but that made me wonder: why is the hover itself not supporting that option when appearing? E.g. when I set `editor.hover.delay: 3000`, I still see the debug hover appear immediately.

**Comment by isidorn** [comment]
@bpasero it respects the `editor.hover.delay`, just because of the `memoize` caching it will only pick up the updated value on reload.

It appears twice as slow as the editor hover because perviously it would appear the same speed and it was just too aggressive. Since it is larger then the editor hover, I decided to go twice as slow. So far nobody complained.

**Comment by bpasero** [comment]
Ah ok I was not doing a reload. I think this should work without reload though, since it works for the editor I think.
