### ISSUE TITLE
Enable extensions to contribute actions to the editor tab context menu

### ISSUE THREAD

**Issue by ZeroCrunch** [Microsoft/vscode#11942]
- VSCode Version: 1.5.2
- OS Version: 14393.105

Steps to Reproduce:
1. Open a file in the editor
2. Right click on the tab.
3. No option for Copy Full Path (like in regular Visual Studio).

**Comment by Bill-Stewart** [comment]
Default keybinding for this is `ctrl+k p` (`workbench.action.files.copyPathOfActiveFile`). You can also install the [ActiveFileInStatusBar](https://github.com/RoscoP/ActiveFileInStatusBar) extension.

**Comment by bpasero** [comment]
More suggestions: Copy Path, Reveal in Explorer, Open Containing Folder,

**Comment by bpasero** [comment]
@jrieken would you agree that we can add another ID to `MenuId` (https://github.com/Microsoft/vscode/blob/master/src/vs/platform/actions/common/actions.ts#L39) to allow for contributions to the editor tab? I think it would be nice to support these requests by enabling extensions to contribute to this menu (it shows when tabs are enabled but also when right click on the editor title when tabs are disabled). 

My understanding is that:
* we need to add another ID
* hook it up to the [parseMenuId](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/actions/browser/menusExtensionPoint.ts#L28)  method (e.g. as `editor/tab`)
* add the contributed actions to where we collect them (https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/parts/editor/titleControl.ts#L441)

One challenge is that I am not sure how the resource context is updated. E.g. when I right click on a tab that is not active, I suppose I would not get the actions contributed for the resource of that tab because this resource is currently not active.

**Comment by jrieken** [comment]
Correct - you need to add another menu id (maybe `editorTitleContext`) and ask for a *real* menu with [this call](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/actions/common/menuService.ts#L29). When doing so you pass in the `contextKeyService` (formerly aka `keybindingService`) which has the keys (like resource etc). You might be able to reuse the one from the tab title menu

**Comment by bpasero** [comment]
@jrieken how would you suggest to handle the `contextKeyService` properly for tabs. I can get the menu to work but I would like to have the right context for the tab: When you right click on any tab (even when not visible) the context should be determined by the resource that is shown within that tab. This is a bit tricky because unlike in the explorer, right clicking on any tab does not change focus or selection. Suggestions welcome.

**Comment by jrieken** [comment]
tricky - i'll ask my brain

**Comment by bpasero** [comment]
@jrieken would it make sense to allow me to pass in an explicit context key instead of the entire service? this operation is very short lived, basically the entire menu is being created upon right click, has a very specific context from that tab and then needs to be disposed again once the menu closes.

So it is a lot less dynamic compared to the editorTitle menu we have.

**Comment by jrieken** [comment]
Well, I wouldn't change the API from *context key service* to specific *context keys* but you can always create a new, scoped context key service and a new menu on right click. Not the most elegant but certainly easier to handle. 

In general context keys should be looked at like view model elements that update on events. So, there should be a resource context key per editor slot and it should update on various event (like right click, context menu close, focus change, input change, etc)

**Comment by bpasero** [comment]
@jrieken can you look at https://github.com/Microsoft/vscode/pull/13199 I think it is a workable solution. Since I do not want to temper with the resource context we have set, I restore it when the menu hides.

The only thing I am not able to get working is to make the action only show up under a certain condition (tried `"when": "editorLangId == markdown"`), maybe I am missing something?

**Comment by bpasero** [comment]
Solved my when clause issue by changing it to `"when": "resourceLangId == markdown"`

**Comment by jrieken** [comment]
Yeah - the `editorXYZ` context keys are only available when you have an editor in the same context. Since you can have a context menu without an editor (*inactive* tab) it's fair to only have the small set of context keys.

**Comment by bpasero** [comment]
I am hijacking this issue for the extension point and plan to provide an extension for this once 1.7.0 is out 👍
