### ISSUE TITLE
Show CHANGELOG.md if present in an extension

### ISSUE THREAD

**Issue by XVincentX** [Microsoft/vscode#11940]
Do you think would it be a good idea to display CHANGELOG.md in the extension marketplace, if this file is present in the extension package?

--

- [x] Display changes from an installed extension
- [x] Display changes from a Marketplace extension
 - [x] Create a new Changelog asset type: Microsoft/vscode-vsce#126

**Comment by joaomoreno** [comment]
It's a cool idea.

**Comment by mrmlnc** [comment]
(If possible) And releases section on GitHub? 🐱

**Comment by XVincentX** [comment]
Also - it does not really matter - I'm filling both but probably not everybody is on github.

**Comment by XVincentX** [comment]
@joaomoreno I was wondering whether you would be willing to accept an user contribution here. It does not seem a big task to do and it would help me getting started into vscode codebase. What do you think?

**Comment by joaomoreno** [comment]
@XVincentX Let's do it. It will need a bit of work on my side since this feature should also work for extensions that haven't been installed; and for that to happen we need changes in `vsce` and possibly the Marketplace.

But for now, if you want to get started, I suggest you focus on extensions that are already installed. I suggest we add a new section right there next to `Details` and `Contributions`. Call it `Change Log`... or `Changes`. Maybe.

![image](https://cloud.githubusercontent.com/assets/22350/18486923/83fd766c-79f3-11e6-98a6-4a2f850cd84d.png)

Great places to start:

- https://github.com/Microsoft/vscode/blob/master/src/vs/platform/extensionManagement/node/extensionManagementService.ts#L148
- https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/extensions/electron-browser/extensionsWorkbenchService.ts#L89
- https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/extensions/electron-browser/extensionEditor.ts#L259

**Comment by XVincentX** [comment]
That's so cool! I'll start looking here and see if I can come up with something!

**Comment by joaomoreno** [comment]
Almost there. We can now publish extensions which will contain the Changelog asset url with `vsce@1.13.0`. We just need to mimic what is done for the Readme in order to be able to display a change log section for Marketplace extensions.

**Comment by XVincentX** [comment]
@joaomoreno Ok - I'll try to prepare yet another PR for that.

**Comment by XVincentX** [comment]
@joaomoreno 
I think I need your help here.

Basically, for both `README` and `CHANGELOG` are being published like `Microsoft.VisualStudio.Services.Content.Details` - but the current code is not really able to handle that appropriately. If you have a look to [getAssetSource](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/extensionManagement/node/extensionGalleryService.ts#L178) - you can see that only the first element of the array is being taken.

That is kind of harmful.

So please tell me if 
1. I should create a new `Microsoft.VisualStudio.Services.Content.Something`
2. Modify the function so that `getAssetSource` can take an identifier string as well.

Thanks!

**Comment by joaomoreno** [comment]
Ah dang, I missed that from the code review. Yeah, we're supposed to create a new type: Microsoft/vscode-vsce#132

**Comment by XVincentX** [comment]
I think we can close this one. Thanks a lot!
Looking forward to contribute again.
