### ISSUE TITLE
Copy/Paste shortcuts often stop working in non-editor inputs

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#119528]
I've been seeing this happen more and more lately, but I can never reproduce it on demand, and a window reload always fixes it.

But trying to copy/paste from the quick pick, or other non-editor inputs, like the breakpoints exception filter, sometimes just stops working.

@rebornix suggested the _Toggle Keyboard Shortcuts Troubleshooting_ and I tried that and got the following when trying to paste into a quick pick:
```
[2021-03-22 18:52:44.928] [renderer10] [info] [KeybindingService]: \ From 5 keybinding entries, matched editor.action.clipboardPasteAction, when: no when condition, source: built-in.
[2021-03-22 18:52:45.136] [renderer10] [info] [KeybindingService]: / Received  keydown event - modifiers: [ctrl], code: KeyV, keyCode: 86, key: v
[2021-03-22 18:52:45.136] [renderer10] [info] [KeybindingService]: | Converted keydown event - modifiers: [ctrl], code: KeyV, keyCode: 52 ('V')
[2021-03-22 18:52:45.136] [renderer10] [info] [KeybindingService]: | Resolving ctrl+V
```

So it seems like something in `editor.action.clipboardPasteAction` is going wrong.

**Comment by mjbvz** [comment]
Are there some common steps that seem to cause this? For example, having a notebook or custom editor open?

**Comment by eamodio** [comment]
None that I can tell -- hadn't used either notebooks or custom editors the last few times I've seen this. I am very often starting and stopping debugging sessions.

**Comment by alexdima** [comment]
`editor.action.clipboardPasteAction` is a contributable/delegate based command. That means that it has multiple implementations. One of these implementations might be misbehaving and "stealing" paste:
* [x] [if a code editor is focused](https://github.com/microsoft/vscode/blob/9089e0cbd9f04d768e4d32ed65ad00b04e7b8908/src/vs/editor/contrib/clipboard/clipboard.ts#L204-L206), it executes `document.execCommand('paste')` or falls back to electron's clipboard API via the clipboard service. @alexdima this is correct
* [ ] [if the active editor pane is a webview editor](https://github.com/microsoft/vscode/blob/9089e0cbd9f04d768e4d32ed65ad00b04e7b8908/src/vs/workbench/contrib/extensions/browser/extensions.contribution.ts#L290-L292), it then delegates paste there. @mjbvz Is that code checking really for focus? I remember the workbench has a weird definition of `active editor`, which is unrelated to focus.
* [ ] [if the active focus is in a notebook](https://github.com/microsoft/vscode/blob/9089e0cbd9f04d768e4d32ed65ad00b04e7b8908/src/vs/workbench/contrib/notebook/browser/contrib/clipboard/notebookClipboard.ts#L84-L87) @rebornix can you please verify that this is bug-free? (it looks very complex)
* [ ] [there's another notebook one](https://github.com/microsoft/vscode/blob/9089e0cbd9f04d768e4d32ed65ad00b04e7b8908/src/vs/workbench/contrib/notebook/electron-browser/notebook.contribution.ts#L54-L56) @rebornix 
* [ ] [there's another webview one](https://github.com/microsoft/vscode/blob/9089e0cbd9f04d768e4d32ed65ad00b04e7b8908/src/vs/workbench/contrib/webview/browser/webview.contribution.ts#L29) @mjbvz 
* [ ] [finally, the default browser paste that would paste in quick open](https://github.com/microsoft/vscode/blob/9089e0cbd9f04d768e4d32ed65ad00b04e7b8908/src/vs/editor/contrib/clipboard/clipboard.ts#L238-L241) @mjbvz

Since this is such a prominent command, I will add trace logging to pinpoint the problem.

**Comment by alexdima** [comment]
I have pushed some tracing via afca44535df55707d5f0b1dd65098060b448c8a8 . This will help to track down which implementation is misbehaving in this case:

![image](https://user-images.githubusercontent.com/5047891/112142477-f08d8200-8bd6-11eb-8f2c-4bdbfc14d973.png)
