### ISSUE TITLE
Default profile missing from terminal menu

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#119592]
Testing #119427

macOS Catalina

Changing the default profile to ksh does not include it in the terminal's menu. I can add it using settings, but it would be nice if  I didn't have to do that.

**Comment by Tyriar** [comment]
It doesn't add it there by design because that's what the `+` button does. Next iteration it'll look something like this where the + is your primary/default and ^/v is the secondary/custom ones:

![image](https://user-images.githubusercontent.com/2193314/112199892-def2ad00-8bcb-11eb-9ba8-89f0d41ad32f.png)
