### ISSUE TITLE
Getting started - primary walkthrough not opening

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#119620]
Testing #119543

* Start VS Code and have "Getting Started" editor opened
* Set `"workbench.welcomePage.experimental.extensionContributions": "open"`
* Have another file opened (ex: `settings.json`) which is the focused tab.
* Install the `md-to-html` extension. 

**Expected:** Primary walkthrough should open. (this works as expected is the "Getting Started" editor is not opened)
**Actual:** Item is added under the "Getting Started" section but walkthrough is not opening.

**Comment by JacksonKearl** [comment]
Verify: `"workbench.welcomePage.experimental.extensionContributions"` is now boolean, the only (exposed) behaviour is when installing an extensions with a `"primary": true,` walkthrough:
- If there are any getting started pages which are not opened to any walkthrough (the index page), make one of them visible, and set it to show the newly added walkthrough
- Otherwise, open a new getting started page to this walkthrough

The main thing is that there should be a getting started page active, showing the walkthrough, and that no getting started page which had been showing a different walkthrough should be overwritten (though it may become hidden).

**Comment by andreamah** [comment]
For verification purposes, is `"workbench.welcomePage.experimental.extensionContributions"` now the `workbench.welcomePage.experimental.startEntryContributions` boolean?

**Comment by JacksonKearl** [comment]
Yep, thanks!

**Comment by MrSkittles1** [comment]
How do I get to that page to check that the workbench is true?

**Comment by JacksonKearl** [comment]
@MrSkittles1 I do not understand the question. You can open the page under question with `Help: Getting Started` in Stable or `Help: Welcome` in Insiders
