### ISSUE TITLE
Running x tests indicator is wrong

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#119667]
Testing #119545

I ran 2 tests and saw this:

![image](https://user-images.githubusercontent.com/2193314/112195737-891c0600-8bc7-11eb-94fb-5533a3dea4eb.png)

Waiting longer I think it said `Running 4 tests, 0/0 passed (0.00%)`

It should have said 2 tests and kept track of total (even if run test buttons were clicked multiple times)

**Comment by connor4312** [comment]
I'm not sure if/how this can be solved. We could the number of test items, we don't have a notion of what a single "test" is.

**Comment by Tyriar** [comment]
In mocha isn't it a single `it`/`test`? A `suite`/`describe` is a set of tests, but an empty suite is 0 tests. That's what I'd expect

So there's the inaccurate 8 above which turns to 4 which I didn't understand. But also the /0 and 0%, if we don't have the total maybe that should be hidden?

**Comment by connor4312** [comment]
Yea, in mocha this is easy. But in the API we only have a representation of the "TestItem" and don't assume what's technically a "test" or not, since this distinction can be blurry between languages. So far I haven't needed this distinction and I hesitate to add an API flag just for this bit of UI. Will think about it, and maybe other cases for having that flag will arise.

**Comment by connor4312** [comment]
I decided to just remove the total indicator. For async tests it can always be inaccurate since we won't know necessarily know about tests until the run happens
