### ISSUE TITLE
Consider using a terminal for test output

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#119642]
Testing #119545

You can create a terminal using `hideFromUser: true` so that it's not visible until the user opens it (notification on failure? button on test view?) and then use `waitOnExit: string` to reuse a terminal with a message like tasks does.

The main benefit here would be better sequence support like colors and moving the cursor (eg. animated loading bars).

**Comment by connor4312** [comment]
Test output is on my todo for next month. I would prefer to manage output centrally in the test APIs and would prefer that extensions don't go and create their own terminals, so that the test UI and settings can control visibility in a consistent way. (e.g. settings to show the terminal on test failure)

My initial thought has been to add some `output` method on the TestRun which would give data to VS Code to store. Then, on a reveal action, we would show the captured output in a terminal or an editor. A terminal is good for automatic handling of control sequences, but we also won't necessarily know its size.

**Comment by Tyriar** [comment]
@connor4312 yes the core would still manage the terminal, it's just used instead of an output channel.

> A terminal is good for automatic handling of control sequences, but we also won't necessarily know its size.

I don't think the size is much of an issue for tests, at least not on Windows as soft wraps are sent. For Windows we need https://github.com/microsoft/vscode/issues/91898 to behave better.

**Comment by roblourens** [comment]
How do I see this terminal?

**Comment by connor4312** [comment]
This button, or with the `Tests: Show Output` command

![](https://memes.peet.io/img/21-04-a23b5a7a-a85d-44c5-9933-b868ad92a932.png)

- The terminal should display the most recent test output
- If an output terminal is already open, it is shown and its contents updated
- If you start a new run while the terminal is open, output should be streamed live to it
