### ISSUE TITLE
Test explorer: I don't know how to unhide tests

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#119645]
Testing #119545

I expected refresh tests to do it but it didn't. I question the usefulness of hide tests, it feels like a dangerous/frustrating action to me because when I click it I have no idea how to bring it back.

**Comment by connor4312** [comment]
The filter menu on the input has options to show or unhide tests:

![](https://memes.peet.io/img/21-03-38bd262e-d0c6-4180-84d1-295b314534aa.png)

Hidden tests were requested by several people and can be quite useful, since hiding tests will also exclude them from test runs (given the test extension respects the exclusion).

**Comment by Tyriar** [comment]
Oh it shows a menu, I thought it was going to toggle some state like in find/search since it's inside the textbox. I guess problems works like this.
