### ISSUE TITLE
Debug view should show when a breakpoint is hit

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#119646]
Testing #119545

I don't think I have a setting that would influence this, I expected the debug pane to show on break so I could action the breakpoint.

Repro:

1. Create a breakpoint
2. Close file
3. Start debugging that test, on breakpoint hit the debug view won't be shown

![recording (6)](https://user-images.githubusercontent.com/2193314/112186416-58839e80-8bbe-11eb-9f36-ff62ba1b49e4.gif)

**Comment by connor4312** [comment]
@isidorn I think this is something that should happen if the has the debug toolbar inline.

**Comment by isidorn** [comment]
Yes, this feature makes sense.
We can open the debug view when a breakpoint is hit. Especially if the toolbar is docked

**Comment by weinand** [comment]
And with the new [DAP feature](https://github.com/microsoft/debug-adapter-protocol/issues/178) we can even highlight the breakpoint(s) causing the hit.

**Comment by isidorn** [comment]
We have a setting `debug.openDebug` which by default is `openOnFirstSessionStart`. I have changed the default to be `openOnDebugBreak` so that on every breakpoint hit we open the debug view. We will also open the debug view on first session start.

For the new DAP feature we can tackle that via https://github.com/microsoft/vscode/issues/118743

**Comment by isidorn** [comment]
@Tyriar can you please verify this one? Thanks!
