### ISSUE TITLE
Pause animated gifs in extension readmes

### ISSUE THREAD

**Issue by WilcoFiers** [microsoft/vscode#119785]
- VS Code Version: 1.54.2
- OS Version: MacOS 11.2

Steps to Reproduce:

1. Open the extensions panel
2. Search for comment-autocomplete (or any number of other extensions with animated gifs)

Does this issue occur when all extensions are disabled?: Yes

It is fairly common place for extensions to include animated gifs in their readme. These then show up on the marketplace page on visualstudio.com, as well as in VSCode itself. Animated gifs can be fairly distracting for people with certain cognitive disabilities such as autism. For quite a few people, animations are so distracting, it is essentially impossible for them to read the text. This is captured in the [pause, stop, hide](https://www.w3.org/WAI/WCAG21/Understanding/pause-stop-hide.html) requirement of Web Content Accessibility Guidelines.

One way this could be addressed is for VSC to wrap each animated gif in a little widget that adds a small pause / play toggle button in the bottom right (or left for RTL languages). There are some tools to do this out there, such as [freezeframe.js](https://ctrl-freaks.github.io/freezeframe.js/) The best solution would be only to animate when the user hovers / activates the image. Make sure to make the mechanism to start/pause keyboard accessible.

**Comment by geekley** [comment]
Not only because it's distracting.
It would also be REALLY useful to be able to pause/play GIFs in general (extension pages and Release Notes page) when they show a "how to use video" (screen recording). It's always playing too fast and you can't understand what it's supposed to be showing until you see it over and over again. And if you miss a step, you have to wait until it loops again and pay really close attention.
Video controls (like pause/play, slow motion) on a GIF would be VERY useful in this case.

If it's weird to show these controls on a GIF, you could just have a "Video Controls" option to toggle when you right click the GIF.
Or, at the bare minimum, just play/pause when you click the image; that would already help a lot.
