### ISSUE TITLE
https://vscode-update.azurewebsites.net does not resolve anymore

### ISSUE THREAD

**Issue by jkeech** [microsoft/vscode#119822]
- VS Code Version: N/A
- OS Version: N/A

Steps to Reproduce:

1. Try to open https://vscode-update.azurewebsites.net
2. DNS doesn't resolve

This is causing `node ./node_modules/vscode/bin/install` in our repo to fail, since the vscode.d.ts file seems to be downloaded on the fly from that domain: `Error installing vscode.d.ts: Error: getaddrinfo ENOTFOUND vscode-update.azurewebsites.net vscode-update.azurewebsites.net:443`

This started failing sometime between 4 PM PDT yesterday (Match 23) and 6:30 AM PDT today (March 24).

**Comment by JoeRobich** [comment]
Also, seeing this in the omnisharp-vscode repo.

**Comment by ThadHouse** [comment]
Can we finally use this as a case to get rid of the ridiculous redistribution license for VS Code? Normally we'd just create a mirror since we still have the old binaries, but the license doesn't allow it. If you're going to have regressive licensing, you need to make sure old builds stay available at their old URL's.

**Comment by joaomoreno** [comment]
`vscode-update.azurewebsites.net` was just a redirect to the actual `update.code.visualstudio.com` update server. Deleting it has been scheduled since years. It was just hard to know which clients were still hitting it.

There are two ways to get out of that situation:

- The latest `vscode` module already points to `update.code.visualstudio.com`. So the easy fix is to just update `vscode` to `1.1.37` in your dependencies.
- The `vscode` module has been [deprecated](https://github.com/Microsoft/vscode-extension-vscode#%EF%B8%8F-deprecated-use-typesvscode-and-vscode-test-instead-%EF%B8%8F) since about a year. So the right fix is to follow the [migration guide](https://code.visualstudio.com/api/working-with-extensions/testing-extension#migrating-from-vscode) and move out of that module.

> If you're going to have regressive licensing, you need to make sure old builds stay available at their old URL's.

All builds are still available in `update.code.visualstudio.com`, as `vscode-builds` was just a redirect to that service.

**Comment by collinwright** [comment]
This also impacts https://github.com/NixOS/nixpkgs, which uses the previous domain to reference VS Code downloads. This also means that previous versions of nixpkgs may fail to install VS Code.

I am working on a PR to fix the issue going forward with nixpkgs, but I figured it was worth noting here.

**Comment by SuperSandro2000** [comment]
> This also impacts [NixOS/nixpkgs](https://github.com/NixOS/nixpkgs), which uses the previous domain to reference VS Code downloads. This also means that previous versions of nixpkgs may fail to install VS Code.
> 
> I am working on a PR to fix the issue going forward with nixpkgs, but I figured it was worth noting here.

The download URLs of the actual packages already got updated for both supported versions.
