### ISSUE TITLE
https://vscode-update.azurewebsites.net/ is down

### ISSUE THREAD

**Issue by ThadHouse** [microsoft/vscode#119838]
Because of VS Code's license, we had our installer pointing to https://vscode-update.azurewebsites.net/ to get VS Code downloaded for our users. It seems like this website is currently down. Can we get that website back up?

**Comment by ThadHouse** [comment]
I posted this in the other one, but in case its missed, can this be a catalyst for restarting the license discussion. This wouldn't be a problem if we could host the binaries elsewhere, or include them in our offline installer.

**Comment by joaomoreno** [comment]
Simply change the domain to `update.code.visualstudio.com`. This does not affect any licensing rules at all.

**Comment by ThadHouse** [comment]
Our installer has been shipping for years using that site. So it's not as easy as just "update the url". Changing that url is a major breakage for us. And what about the future? What's stopping you from changing the current site to something else, and breaking again.

Issues like that could be avoided without that regressive license policy.

**Comment by joaomoreno** [comment]
> Our installer has been shipping for years using that site. So it's not as easy as just "update the url". It breaks all installers we have previously shipped to users. Changing that url is a major breakage for us. And what about the future? What's stopping you from changing the current site to something else, and breaking again.

Sorry that it turned out that way. I wish you would've reached to us when making that decision. On one hand we could've informed you that the correct domain is `update.code.visualstudio.com`, on the other we would've known some other product depends on this as API. We've long deprecated `vscode-update` and only use `update.code.visualstudio.com`. The former was just hanging around for a couple of years forwarding to the latter so people would have time to migrate off of. In any case, we're committed to keeping `update.code.visualstudio.com` running as API for the foreseeable future.

BTW, what installer are you referring to?

**Comment by ThadHouse** [comment]
https://github.com/wpilibsuite/allwpilib/releases/tag/v2021.2.2

We provide an integrated environment for high school robotics teams to learn and develop their code with. We can provide everything in a single installer, except for the actual copy of vs code.

We've been using that site since early 2018. Back then, I think it was the only site available. I didn't know a new site was made, it was never part of any release notes. Otherwise we would have switched.
