### ISSUE TITLE
Edit during debug missplaces breakpoints

### ISSUE THREAD

**Issue by Heniker** [microsoft/vscode#119809]
How to reproduce:

https://user-images.githubusercontent.com/22645200/112357292-6c272600-8ce0-11eb-8962-8644b0296048.mp4

Happens on `node` debugger and `pwa-node` (didn't test others).
Happens when all extension are disabled.
VSCode version: 1.53.2

**Comment by IllusionMH** [comment]
/needsMoreInfo

Please provide language, code sample and steps to reproduce this issue.

**Comment by Heniker** [comment]
Yea, sorry. Didn't expect vscode built - in issue reporter to create the issue right away.

**Comment by Heniker** [comment]
Possibly related issues:
#6930
#81804

#81804 - is actually almost the same, but it was closed with `as-designed` label. To my mind, this is not the expected behavior. I think this should either be mentioned in docs or resolved in some way (possibly by providing readonly editor for debug).

**Comment by connor4312** [comment]
As referenced, this is expected. Correcting breakpoint positions would require keeping some 'diff' of changes between what's in the runtime and what's on disk, but this is not practical because:

- The editor does not know what code is executing in the running. For example many runtimes will automatically reload the code when it's saved.
- Changes to the code can happen outside of the editor where diffs can't be made
- Even solving these, you're still in a position where the code you're debugging is different from the code that's running, which is likely to be confusing and not very useful.
