### ISSUE TITLE
`test` api namespace

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#119831]
Testing #119546

Here is the current definition of the `test` namespace
```ts
export namespace test {
	export function registerTestProvider<T extends TestItem>(testProvider: TestProvider<T>): Disposable;
	export function runTests<T extends TestItem>(run: TestRunOptions<T>, cancellationToken?: CancellationToken): Thenable<void>;

	export function createWorkspaceTestObserver(workspaceFolder: WorkspaceFolder): TestObserver;
	export function createDocumentTestObserver(document: TextDocument): TestObserver;
	export function publishTestResult(results: TestResults, persist?: boolean): void;

	export const testResults: ReadonlyArray<TestResults>;
	export const onDidChangeTestResults: Event<void>;
}
```

There are a few things that feel strange to me here. The first is that all of these methods are accessible by any extension, and some methods feel like they should be scoped only to the extension with the provider.

Instead, what if it was like:

```ts
export namespace test {
	export const onDidChangeTestResults: Event<void>; // should this take some kind of provider id? if there are multiple providers registered?
	export const testResults: ReadonlyArray<TestResults>;

	export function createTestRunner<T extends TestItem>(provider: TestProvider<T>): TestRunner<T>;
	export function runTests(options: { debug: boolean }, cancellationToken?: CancellationToken): Thenable<void>; // maybe even returns `ReadonlyArray<TestResults>`

	export function createTestsWatcher(documentOrFolder: WorkspaceFolder | TextDocument): TestsWatcher;
}

export class TestRunner<T extends TestItem> {
	export const onDidChangeTestResults: Event<void>; // if this is valuable to the implementing extension
	export const testResults: ReadonlyArray<TestResults>; // if this is valuable to the implementing extension

	runTests(options: TestRunOptions<T>, cancellationToken?: CancellationToken): Thenable<void>
	publishResults(results: TestResults, persist?: boolean): void
}
```

I don't know if `TestRunner` is the right term (probably not), but to have something akin to `TreeView/createTreeView`, where you not only register a provider, but also get a "rich" object back to manipulate. 

And then `runTests` is simplified, as another extension can't get at the tests, etc so just a simple `debug` flag

**Comment by eamodio** [comment]
```ts
	export interface TestObserver {
		/**
		 * List of tests returned by test provider for files in the workspace.
		 */
		readonly tests: ReadonlyArray<TestItem>;

		/**
		 * An event that fires when an existing test in the collection changes, or
		 * null if a top-level test was added or removed. When fired, the consumer
		 * should check the test item and all its children for changes.
		 */
		readonly onDidChangeTest: Event<TestChangeEvent>;

		/**
		 * An event that fires when all test providers have signalled that the tests
		 * the observer references have been discovered. Providers may continue to
		 * watch for changes and cause {@link onDidChangeTest} to fire as files
		 * change, until the observer is disposed.
		 *
		 * @todo as below
		 */
		readonly onDidDiscoverInitialTests: Event<void>;

		/**
		 * Dispose of the observer, allowing VS Code to eventually tell test
		 * providers that they no longer need to update tests.
		 */
		dispose(): void;
	}
```

to 

```ts
	export interface TestsWatcher {
		/**
		 * List of discovered tests returned by all test providers for the specified file or WorkspaceFolder.
		 */
		readonly tests: ReadonlyArray<TestItem>;

		/**
		 * An event that fires when tests in the specified file or WorkspaceFolder changes.
		 * When fired, a consumer can check each test item and all their children for changes.
		 */
		readonly onDidChangeTests: Event<TestsChangeEvent>;

		/**
		 * An event that fires when all test providers have signaled that all tests
		 * the have been discovered. Providers may continue to
		 * watch for changes and cause {@link onDidChangeTests} to fire as files
		 * change, until the watcher is disposed.
		 */
		readonly onDidCompleteDiscovery: Event<void>;

		/**
		 * Dispose of the watcher, allowing VS Code to eventually tell test
		 * providers that they no longer need to update tests.
		 */
		dispose(): void;
	}
```

**Comment by eamodio** [comment]
- `TestResults` -> `TestRunResult`

Updates below (including comments, etc)
```ts
	/**
	 * TestRunResult can be provided to VS Code, or read from it.
	 *
	 * The results are a 'snapshot' of the tests at the point when the test
	 * run was completed. Therefore, information such as {@link Location} instances
	 * may be out of date. If the test still exists in the workspace, consumers
	 * can use its `id` to correlate the result instance with the living test.
	 *
	 * @todo coverage and other info may eventually be provided here
	 */
	export interface TestRunResult {
		/**
		 * Unix milliseconds timestamp at which the tests run was completed.
		 */
		completedAt: number; // would `timestamp` good enough here? We also use `timestamp` for TimelineItems

		/**
		 * List of test results. The items in this array are the items that
		 * were passed in the {@link test.runTests} method.
		 */
		results: ReadonlyArray<Readonly<TestResult>>;
	}
```

> TestRunResult can be provided to VS Code, or read from it.

Feels strange, I get kind of what we are trying to say here, but I'm not sure it even needs to be said?

- `TestResultSnapshot -> `TestResult`

Updates below (including comments, etc)
```ts
	/**
	 * A {@link TestItem}-like interface with an associated result, which appear
	 * or can be provided in {@link TestResult} interfaces.
	 */
	export interface TestResult {
		/**
		 * Unique identifier that matches that of the associated TestItem.
		 * This is used to correlate test results and tests in the document with
		 * those in the workspace (test explorer).
		 */
		readonly id: string;

		/**
		 * URI this TestItem is associated with. May be a file or folder.
		 */
		readonly uri: Uri;

		/**
		 * Display name describing the test case.
		 */
		readonly label: string;

		/**
		 * Optional description that appears next to the label.
		 */
		readonly description?: string;

		/**
		 * Location of the test item in its `uri`. This is only meaningful if the
		 * `uri` points to a file.
		 */
		readonly range?: Range;

		/**
		 * Current result of the test.
		 */
		readonly result: TestState;

		/**
		 * Optional list of nested tests for this item.
		 */
		readonly children: Readonly<TestResult>[];
	}
```

Should `uri` and `range` be combined into a `location: Location`, or maybe the `uri` stays since that could be a file or folder, but the `location: Location` would always exist with the `uri` of the file the test was in and its range?

`children` doesn't feel like the right name to me, but I'm not sure I have a better alternative.

**Comment by eamodio** [comment]
### `TestProvider`/ `TestRun` / `TestRunOptions`

- It feels strange that the run options and the progress reporting are combined. And maybe we should re-use the existing `Progress<T>` class?
	```ts
  runTests(options: TestRunOptions<T>, progress: Progress<{ test: T, state: TestResultState }>)
	```

### `TestRunOptions`
- Maybe `tests` should be optional, and if not provided it defaults to the root(s)
- Maybe `tests` can be `T | T[]` to make it easier to pass in a single test/root?
- There is no `TestProvider.testRoot` as mentioned in the comment below
```ts
	export interface TestRunOptions<T extends TestItem = TestItem> {
		/**
		 * Array of specific tests to run. The {@link TestProvider.testRoot} may
		 * be provided as an indication to run all tests.
		 */
		tests: T[];
```

**Comment by eamodio** [comment]
### `TestItem`
- As mentioned above, the children concept feels odd to me here. Maybe nested? 
- It almost feels like there should be a difference between a `TestItem` that has children and one that doesn't. Can a `TestItem` that has children also be itself runnable? It seems like something is either a group or an item. And a group can contain tests, and can be a rollup of results, but not runnable itself.
- Like `TestResultSnapshot`, the `uri` says it can be a file or file (I assume it should be file or folder).
- Also like `TestResultSnapshot`, should `range?: Range` changed into `location: Location`, where the location would always be a uri of the file and range where the test lives?
- `discoverChildren` can multiple callers call this? If so, is it up to the implementor to handle not starting multiple discoveries?
  - Mentions "The item should continue watching for changes to the children and firing updates until the token is cancelled" -- how are the updates "fired"?
  - Should it return `void | Thenable<void>` to make it easier for implementors to use `async` even though we won't care about waiting?
  - The connection between `discoverChildren` and adding to the `children` property feels a bit strange. I would almost expect the `Progress<{ busy: boolean }>` to be `Progress<{ test: TestItem; done: boolean }>`, and instead of modifying the `children` property, vscode would do it based on the progress reporting.

### `TestHierarchy`
- remove?

**Comment by connor4312** [comment]
Thanks for the feedback, some notes --

> The first is that all of these methods are accessible by any extension, and some methods feel like they should be scoped only to the extension with the provider

This is intentional. Liveshare is the premier example of an extension that needs to drive UI. In this case they need to publish test results and observe changes to test results without being the ones necessarily providing the tests. In more general cases, you can imagine people can write extensions that send growl notifications when tests fail, or the Github extension could show test results from CI without needing to know about your testing framework. For these, they need to be able to read and write test results without being the ones publishing tests in the workspace.

> TestObserver

Yea, this is an outdated interface with the new async APIs, and will be subject to change. More discussion on this here https://github.com/microsoft/vscode/issues/117379 I'm not planning on stabilizing it for a decent time after the publishing portion of the API is stabilized.

> // would `timestamp` good enough here? We also use `timestamp` for TimelineItems

I think completedAt might be more clear, since there's actually two times with tests: the time they started, and the time they finished. If it's just `timestamp`, I need to check the docs to make sure I'm putting in the right value.

> Should uri and range be combined into a location: Location
> 
> Also like TestResultSnapshot, should range?: Range changed into location: Location, where the location would always be a uri of the file and range where the test lives?

They were in a location before this morning when I separated them. Now, all TestItems are required to have a readonly URI, since Sandeep made the point that all TestItems actually will have a URI (but not all TestItems will have a specific range, e.g. file nodes). This enables some scenarios with async handling things and makes our logic simpler. The range is mutable, but the uri is not.

> And maybe we should re-use the existing Progress<T> class? 

I don't want to do this yet since there _may_ be additional things coming to the `TestRun` interface that will require more imperative APIs, namely like coverage and output reporting. Moving to a `report`-only model closes the door on possible interactions here -- though it may turn out that none are needed, in which case using Progress is possible.

> TestRunOptions... Maybe tests should be optional, and if not provided it defaults to the root(s)

The are roots for the workspace and for documents. It's possible that a TestProvider will have multiple many roots active at any time. I don't think we gain anything by adding that bit of potential ambiguity here.

> Maybe tests can be T | T[] to make it easier to pass in a single test/root?

Personally I find it annoying when APIs do this 😛 If I want to special case for a single item given in an array, I can do that. If I don't want to special case then I need to bother converting the items to an array so I can process them. I haven't looked to see if we do this elsewhere in the extension host APIs.

> It almost feels like there should be a difference between a TestItem that has children and one that doesn't. Can a TestItem that has children also be itself runnable? It seems like something is either a group or an item. And a group can contain tests, and can be a rollup of results, but not runnable its

TestItems with children can and almost always are runnable. For example, mocha test suites are "runnable", meaning they can be passed to `runTests`. However, it's not the case that items are either a group or an item. Go and Python, for example, have subtests. These are children of test cases which are not individually runnable, but can only be run as part of that unit test.

There's variance here, so in the API I avoided using prescriptive language -- I just give the extension a catchall"TestItem" definition, and then they can subclass it in their extension/language to give it more meaning. [e.g.](https://github.com/microsoft/vscode-selfhost-test-provider/blob/main/src/testTree.ts#L235)

> discoverChildren can multiple callers call this? If so, is it up to the implementor to handle not starting multiple discoveries? 
>...

I mentioned in the comment:

```
* The editor will only call this method when it's interested in refreshing
* the children of the item, and will not call it again while there's an
* existing, uncancelled discovery for an item.
```

It can get called multiple times in the user hits the "refresh tests" command, but if we do so we'll always dispose of the previous discovery. Extensions _should not_ cache anything between calls to discoverChildren. I can make the language on that more clear, and more clear in general -- this was frankensteined from some old methods.

> The connection between discoverChildren and adding to the children property feels a bit strange. I would almost expect the Progress<{ busy: boolean }> to be Progress<{ test: TestItem; done: boolean }>, and instead of modifying the children property, vscode would do it based on the progress reporting.

I agree it feels a little strange, but so far it's been the nicest solution I've found.

The disadvantage of implementing it as some `Progress<{ add: TestItem; remove: TestItem; done: boolean }>` is that every TestItem is then required to implement `discoverChildren` if it possibly has children. One convenient effect of the current approach is that if I don't have a discovery mechanism for items, I don't need to worry about discovery. For example, in the selfhost test provider, the TestFile creates all the [TestSuites and TestCases](https://github.com/microsoft/vscode-selfhost-test-provider/blob/main/src/testTree.ts#L197-L233) and fills in their children; I don't need to re-implement `discoverChildren` in the TestSuite.
