### ISSUE TITLE
Suddenly getting weird notebook rendering

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#119865]
Not sure what the repro steps are here, but I was using the my-endgame notebook. Approximately what I did:
1. Run a cell.
2. Scroll down.
3. Repeat 1 and 2 a few more times. This included running cells that output no results.
4. At one point, I got this strange list rendering. So I scrolled up to see what already run cells looked like. Even cells that had already run and properly displayed results started having this weird list rendering:
![image](https://user-images.githubusercontent.com/38270282/112465824-6fb0c080-8d65-11eb-95ac-39228041a633.png)

**Comment by rebornix** [comment]
@alexr00 thanks for the detailed steps and screenshot, it gives me hints of how it happened.

It's very likely that a render request is sent to the webview to render an output, but the cell is then moved out of view. Another hide output request is then sent to the webview but it's either lost, or there is a race condition.

**Comment by rebornix** [comment]
This one is the same as https://github.com/microsoft/vscode/issues/119661 , while scrolling, since there are multiple `dimension` events coming from the webview, it triggers the list view render and dispose the same cell multiple times and then:

* an output height change event is sent from the webview, but it doesn't land in the main frame yet
* the cell which contains the output is moved out of the view, so no `onDidChangeLayout` event listener anymore. Thus the cell's height is not updated in the list view
* As the cell's height is still the old one, the output in the webview might overlap with other cells visually

**Comment by rebornix** [comment]
Fixed via https://github.com/microsoft/vscode/commit/e3d59bf3a5543c5f0c33f279ce808acc72d8c4d6 .
