### ISSUE TITLE
Optional time stamps for output view

### ISSUE THREAD

**Issue by shepazon** [microsoft/vscode#119916]
The Output view (the pane in the bottom box, accessed through View > Output) would benefit a lot from having the option to enable timestamps so you can more easily understand the temporal relevance of what you're looking at. Given how often the same or similar commands are executed and shown in this panel, they just blend together as it stands currently, making it hard to be sure that things are doing the right thing when expected.

**Comment by isidorn** [comment]
I think this makes sense, however each output client can append a timestamp.
Anyways, no plans to tackle this at the moment thus assigning to backlog.
Also assigning to @sandy081 for output and if he disagress he can update hte issue.

**Comment by Frulfump** [comment]
It would be nice not having to rely on each output client to support this and instead have native VS Code support for it since it already has the system time.

Also this issue is closed but I don't see it ever being closed based on the history?
Could it at least be open so others find it more easily?
