### ISSUE TITLE
Mx master 3 horizontal scroll in VSCode not working

### ISSUE THREAD

**Issue by Cornel777** [microsoft/vscode#119900]
VSCode 1.54.3
Windows_NT x64 10.0.19042 ( 20H2)

Mx Master 3
I have read all the previous issues on this matter and none did it for me.
Therefore I am opening one myself, maybe I'll have some luck.
No, minimizing and maximizing VSCode does not fix it.

Horizontal scroll wheel not causing any horizontal scroll. Shift + vertical scroll works, scrolling from my touchpad works.
My scroll wheel is functional as it works in other apps, including JetBrains IDE's.

I appreciate any help but please no old solutions as none works.

**Comment by alexdima** [comment]
@Cornel777 Does the horizontal scroll work for you in Chrome at https://vscode-web-test-playground.azurewebsites.net/ ?

**Comment by Cornel777** [comment]
@alexdima Yup, it does

**Comment by PrincetonPoh** [comment]
In logitech's software, I've set the horizontal scroll to be activated on VSCode. Unsure if the issue is on the logitech or VSCode's implementation. Horizontal scroll works on chrome for me. I'm working on Windows.

**Comment by Cornel777** [comment]
Yes, I also did that in Logi Options. Does not help at all. It works for me also in chrome, but not in the VSCode desktop app.

**Comment by alexdima** [comment]
Something very ugly that [I have seen in the past](https://github.com/microsoft/vscode/issues/84879#issuecomment-555554222) is that driver manufacturers sometime look at the current focused window and the process name, and based on that decide to behave differently, i.e. send different UI events.

Could you please try this experiment:
* close all instances of vscode
* go to the vscode installation folder and rename `Code.exe` to `chrome.exe`
* launch vscode using the new name
* attempt to use the mouse

**Comment by Cornel777** [comment]
That actually worked, to my surprise! Weird that everything works with JetBrains IDE's without me even thinking about it and VS Code, created by Microsoft is the only one that has this issue.
Thank you for your solution. Are there any possible issues that may arise from renaming the .exe? So I know what to expect

**Comment by Cornel777** [comment]
So this is an issue with logi options rather that VS Code, right?

**Comment by alexdima** [comment]
VS Code is built with Electron, which is built with Chromium. Chrome is also built with Chromium. Two things might be going on, either the driver never sends this scroll event to VS Code at all or it sends it in a format that is misunderstood by the Chromium event handling code. But in any case, since it is built with the same technology, we would need the same kind of handling from the driver as Chrome.exe.

It would be good if you could also reach out to the driver manufacturer and let them know of the problem. Maybe they can ship a driver update where they treat `Code.exe` and `Code - Insiders.exe` similar to `Chrome.exe`. I am not aware of any negative side-effects of renaming the executable.

**Comment by Cornel777** [comment]
I got it. I think the issue can be closed now.
