### ISSUE TITLE
Appending JSON to notebook output re-stringifies content

### ISSUE THREAD

**Issue by firelizzard18** [microsoft/vscode#119936]
VS Code version: Code - Insiders 1.55.0-insider (2b66dfe0218cc18333ba92429218b33802b186bc, 2021-03-24T05:13:27.970Z)
OS version: Darwin x64 20.2.0

If I add JSON to a `NotebookCellExecutionTask`:

```javascript
task.appendOutput([ 
    new vscode.NotebookCellOutput([
        new vscode.NotebookCellOutputItem('application/json', `{\n\t"foo": "bar"\n}`)
    ])
])
```

I expect to see:

```json
{
    "foo": "bar"
}
```

But what I actually get is:

```json
"{\n\t\"foo\": \"bar\"\n}"
```

Evidently, the output value is getting passed through `JSON.stringify(value)`.

**Comment by jrieken** [comment]
I guess this is because of https://nbformat.readthedocs.io/en/latest/format_description.html#display-data. It says "application/json output is no longer double-serialized into a string." It looks like that has bled into the API and I am not 100% sure how to proceed. There is some merit in sending objects around but I also have the feeling that data should be `string | Error | Unit8Array`

**Comment by jrieken** [comment]
This has been fixed with https://github.com/microsoft/vscode/issues/123884. All data must now be presented as bytes (Uint8Array)
