### ISSUE TITLE
Emmet in template literals

### ISSUE THREAD

**Issue by dandevs** [Microsoft/vscode#12005]
Emmet in template literals, especially within something like Angular's Component would be real useful.
```ts
@Component({
    selector : "emmetpls",
    template : `<h1>Emmet here please</h1>`
}) ...
```

**Comment by egamma** [comment]
@dandevs did you try to associate the emmet html syntax profile with TS? 
You could add a setting like this:
```json
    "emmet.syntaxProfiles": {
        "typescript": "html"
     }
```

**Comment by dandevs** [comment]
@egamma that works perfect, thanks.

**Comment by egamma** [comment]
great, then I'll close the issue

**Comment by ramya-rao-a** [comment]
@dandevs,

From VS Code 1.15 onwards, please use `emmet.includeLanguages` instead of `emmet.syntaxProfiles` to get Emmet abbreviation expansion features in your language of choice.

We are making this move because of the confusion around what `emmet.syntaxProfiles` setting was originally meant for i.e [Customizing final output](https://docs.emmet.io/customization/syntax-profiles/) and what it became i.e enabling emmet in new languages.

Please read more on this at [Emmet 2.0](https://code.visualstudio.com/blogs/2017/08/07/emmet-2.0)
