### ISSUE TITLE
Extension marketplace caching issues

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#12011]
1. Have an extension installed in version 1
2. Publish an update (version 2)
3. Uninstall the extension
4. Search for it, confirm that version 2 shows up
5. Install it

Version 1 appears installed

@egamma @dbaeumer please confirm whether the steps approximate what you experienced

**Comment by dbaeumer** [comment]
@joaomoreno this is exactly what I saw yesterday and couldn't reproduce when I dragged you in.

**Comment by joaomoreno** [comment]
@modigrv @hamenon

Is it possible that the Marketplace goes in a faster pace than what is available in the CDN? That the CDN caches these URLs and takes a while to update them?

**Comment by vishalkiri** [comment]
@joaomoreno This is because QueryExtensions for VSCode gets served from cache which is refreshed every 30 mins.
As a work around, if installation is done by searching, the extension and clicking install there, latest version should get installed

**Comment by joaomoreno** [comment]
@vishalkiri That doesn't explain it.

The QueryExtensions call is returning _fresh_ results. It shows the latest version as soon as a publisher publishes it. But when downloading its asset, users are getting the old version.

**Comment by octref** [comment]
@vishalkiri Just tried that. Didn't work even if it's result of a search.

**Comment by vishalkiri** [comment]
@joaomoreno @octref my bad, while extension installation, latest version is only installed if VSCode version is supported(no bad cache issue).
I was able to repro one scenario locally not sure if this is the same scenario or not. The version displayed(and compared with) in VSCode for installed extension is the version mentioned in package.json of the extension where as the version which is used by marketplace and compared with is the version in vsix manifest. If these versions differ, VSCode always shows an update available even on installing the latest verison from marketplace. This situation can happen in case of manual update of vsix package or in case there is some bug in tool.
Please suggest if you have some extension where the issue is repro - this would help investigate the issue.

**Comment by octref** [comment]
@vishalkiri 

I made an extension, marked is as 0.1.0, and ran `vsce package` and installed the vsix package.

Then I deleted the extension. Published it. Found it in marketplace and extension search in VSCode. Tried installing and didn't work.

So I made some changes and published 0.1.1. Published again. See the new version in VSCode extension search. Install failed again.

Waited for 10 min and tried again. Everything worked.

**Comment by vishalkiri** [comment]
@octref That seems to be because of the QueryExtensions cache.
First call where VSCode gets data is from the cache. When install is clicked, VSCode make a queryextenison call with the extension id(which it gets from the first call) which does not exist in marketplace anymore.
Can you please try two scenarios for me:
1. Delete the extension, publish a new version and try installing as soon as the new version is available on VSCode.
2. Delete the extension, publish the same version, wait for max 30 mins(worst case cache expiry scenario) and try installing.

This will help make sure this is as designed and not a issue.

**Comment by joaomoreno** [comment]
@vishalkiri @modigrv @hamenon While I can't reproduce the problem in the first post, there is something definitely wrong with the Marketplace and caching.

The following recording was done right after publishing version 0.0.4 of my `banana` extension. It shows how, when querying for the extension ID, the marketplace returns the old version (0.0.3) while when searching for its name (`banana`) it returns the new version (0.0.4).

![bug](https://cloud.githubusercontent.com/assets/22350/18877599/0065b248-84ce-11e6-9be7-0f558d4c6f4d.gif)

**Comment by vishalkiri** [comment]
@joaomoreno this is because of the QueryExtensions caching. In first case, the result is coming from the cache where as the second result comes from search where we use no cache.
The cache earlier was for 5 mins which was increased to 30 mins recently. We are working on reducing this to 5 mins in next couple of days.

**Comment by joaomoreno** [comment]
But even 5 minutes results in bugs on our side...

**Comment by joaomoreno** [comment]
#12592

**Comment by joaomoreno** [comment]
@atian25 could reproduce the issue described in the first post of this issue in #12592.

@vishalkiri How do you explain this one? The Marketplace clearly returns the metadata for an updated version, but when Code asks for the VSIX asset URI, it seems to get an old one.

**Comment by vishalkiri** [comment]
@joaomoreno It was 5 mins till last week starting, post which issues seem to be arising. Let me try to look into the issue and get back

**Comment by vishalkiri** [comment]
Also request @atian25 please confirm that both the vsix packages were created by the tool rather and none was manually updated.

**Comment by atian25** [comment]
yes, both of them is created by tool.
some more detail:
- when I publish the first version at 9.28 23:00 (china time), I can found `copy syntax` in `vscode extendsions tab`, but click `install` will throw error : `plugin not found`.
- when update my plugin at 9.29, publish 2 version at 1 hours, it act like https://github.com/Microsoft/vscode/issues/12592.
- then the next day, the update tip is gone  <== must be some cache somewhere.
- when set `extensions.autoUpdate` to true, then after 2 times restart,  the update tip is gone.(don't need to pass a day ^_^)

**Comment by vishalkiri** [comment]
@atian25 Thanks for the information

@joaomoreno I was able to repro the issue on my local setup and confirm that the issue is indeed due to cache timeout increased from 5 mins to 30 mins. All the QueryExtensions in vscode are served from cache and search are served from DB which is causing the inconsistencies. When a extension is updated, cache is not updated where as search is, so when update is clicked after search, VSCode makes another call for QueryExtension which returns the older version and that older version is installed again thus again giving update on search.
We are working on reducing the cache expiry time and should be done in a day. Let me confirm back on this thread when it is done.

**Comment by joaomoreno** [comment]
@vishalkiri Keep us posted.

**Comment by rebornix** [comment]
Below is what I'm running into

* Update extension
* Marketplace is showing the latest version
* Check updates in Insiders. No update
* Install from Code stable, it gets the latest version

**Comment by joaomoreno** [comment]
@vishalkiri Any updates?

**Comment by joaomoreno** [comment]
Closing as this seems fixed.
