### ISSUE TITLE
Staging changes in source control moves cursor-focus (it's back)

### ISSUE THREAD

**Issue by sebastianvitterso** [microsoft/vscode#120162]
Issue Type: <b>Bug</b>

0. Have a sub-repo in your repo.
1. Stage a change
2. Quickly begin to write a message in the main repo's commit-message-input
3. Observe that focus is shifted to the second repo's commit-input

https://user-images.githubusercontent.com/37065184/112963768-fa1f6880-9147-11eb-8090-decfef1f4cfb.mp4

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:45.459Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.68GB (2.65GB free)|
|Process Argv|--crash-reporter-id 7ee3133f-3bba-415e-93fd-736c3a18e9cf|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
atlascode|atl|2.8.6
vscode-intelephense-client|bme|1.6.3
vscode-tailwindcss|bra|0.5.9
netcore-snippets|dog|3.15.1
gitlens|eam|11.3.0
csharp|ms-|1.23.9
python|ms-|2021.3.680753044
jupyter|ms-|2021.3.684299474
vscode-typescript-tslint-plugin|ms-|1.3.3
vsliveshare|ms-|1.0.4018
vetur|oct|0.33.1
laravel-blade|one|1.25.0
java|red|0.76.0
vscode-yaml|red|0.17.0
msbuild-project-tools|tin|0.3.15
material-theme|zhu|3.9.15
vscode-proto3|zxh|0.5.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythontb:30265425
pythonvspyt943cf:30280190
vsget980:30279783
vspre833:30267464
pythonptprofiler:30281270
vshan820cf:30276953

```

</details>

**Comment by sebastianvitterso** [comment]
I know this has been an issue many times before, and I suspect that this time it is the result of a remediation where it just takes "a random" commit-message input field and focuses it, which might work for projects with only one repo, but if one has multiple repositories, it sure doesn't work properly.

**Comment by tonypags** [comment]
I have almost the same exact issue. There are several repos in my list and if I perform any action with git (fetch, pull, add, etc) it usually takes a couple seconds for git to finish and the UI to return to idle. During this non-idle time, anything I type in any of the fields for any repo will be randomly moved around so that my sentence is in many places in bits and pieces. 

When I open the git shell to investigate, there are no issues. 

I have reinstalled/upgraded vscode, git, and disabled all extensions. Issue remains. Started a couple weeks ago maybe. 

Furthermore, the current branch displayed for any of my repos starts changing. Most of my repos have the same branch schema, but a few of them are unique and I see them popping up under other repos. It's almost like the repos (from vscode POV) are swapping identities. In the GIF below, the branch name does not exist under the 2nd repo, but there it is. It also happens when I start vscode and the repos load. 

![vscode-issue120162](https://user-images.githubusercontent.com/19650592/137002715-7c98fb53-313a-4aa4-8a88-71a886c9ec78.gif)

**Comment by radix** [comment]
I was also getting this behavior and it was because I had some out-of-date `.gitmodules` that were referring to non-existent paths. regular commands like `git fetch` and so on weren't failing so I didn't notice this, but it seems however vscode was interacting with my git repository was causing it to break. So I guess the actual bug here is that the focus gets moved to the last commit box whenever any automated git command fails??

**Comment by kangalioo** [comment]
This happens almost every time I try to commit. VSCode particularly likes to jump focus to this particular project, whose input field looks like this by now
![Screenshot_20211217_221415](https://user-images.githubusercontent.com/21220820/146608825-087a7e8f-2a2e-4c74-8450-f248391cca0f.png)

As a workaround I've started creating a new tab, typing the commit message there and then copy-pasting it back into the input field

**Comment by jonnyyu** [comment]
I met a similar issue when I finish a commit and set focus to command window, and the focus is always set back to the git commit message text box, this is quite annoying.

**Comment by sebastianvitterso** [comment]
I no longer use git submodules, so I can't attest to whether this problem still exists.
