### ISSUE TITLE
define the debuggers in package.json as conditional to the platform

### ISSUE THREAD

**Issue by elahehrashedi** [microsoft/vscode#120280]
Currently, Vs Code is creating a directory of the extension debuggers by picking them from the packages.json. 
In C/C++ extension, we have defined two debuggers for windows and non-windows platforms. 
Therefore, when VS Code is showing debugging options from our packages.json, it will show windows-specific debuggers for mac and Linux users as well. 

1. click on Run and Debug
![image](https://user-images.githubusercontent.com/16143955/113226396-ef96c900-9244-11eb-8653-0f4a1588f3a0.png)
2. both debug options will be shown:
![image](https://user-images.githubusercontent.com/16143955/113226434-09d0a700-9245-11eb-80df-cb81100b79b3.png)

```
    "debuggers": [
      {
        "type": "cppdbg",
        "label": "C++ (GDB/LLDB)",
        ...
      },
      {
        "type": "cppvsdbg",
        "label": "C++ (Windows)",
        ...
      }
    ]
```

I was wondering if there already is a way to define our debuggers' relevant platform in package.json? Or if the Vs Code can possibily add this feature?

**Comment by weinand** [comment]
This feature request sounds reasonable, but when going into the details, there are reasons why we have no plans to support this:
- VS Code runs on all platforms and we do not want to promote the notion of platform specific extensions. 
- Projects (workspaces) should work transparently on all platforms. If a project uses a platform specific debug extension, the project will not work if it is opened on another platforms. 
- if there is conceptually one C/C++ debugger extension, why is this extension split into multiple extensions with different debug types (as in your example from above)?  
- when using VS Code's "Remote Development" extension, an installed extension like C/C++ should be transparently available in the remote setup (which most likely runs on a different platform). With the proposed feature a previously available debugger would disappear in the remote case.

Why do you have two C++ extensions? Does this help users?

**Comment by Colengms** [comment]
@weinand I don't think this scenario was fully understood before it was closed.  The C/C++ Extension is platform agnostic (for now.  ​Though, regardless of this particular issue, we have a long-standing request for the ability to provide platform-specific vsix's, as we have native components that need to be distributed only for the intended platform).

This specific issue is about multiple debuggers that the C/C++ Extension registers.  Since it's platform agnostic, it registers debugger for multiple platforms.  However, without some way to indicate (i.e. a "when" field) that a debugger applies only to a particular platform, VS Code is offering invalid options to the user.  i.e. It is offering our Windows debugger as an option on non-Windows platforms.  We're looking for a way to remedy this.  There doesn't appear to be a way to constrain the registration of a debugger to a particular platform in package.json, and VS Code doesn't seem to be querying us for debug configurations before presenting that list.  It's possible there is a way to do this properly that we missed.

**Comment by weinand** [comment]
@Colengms It would be great if could you provide a github link to the long-standing request for the ability to provide platform-specific vsixs. Thanks.

In addition it would help if you could comment on the reasons from above why we do not plan to support platform specific debug extensions. Why do you think are they not valid?

In particular I still don't understand why you register different debuggers for multiple platforms instead of registering a single debugger that tries to load only the needed "native components" for a specific platform and hides this implementation detail from end users.

**Comment by Colengms** [comment]
@weinand I believe that is tracked with this issue: https://github.com/microsoft/vscode/issues/23251

I'm not sure I understand your questions.  We provide the option of using GDB/LLDB or the VS debugger on Windows.  On Windows, both are possible.  On other platforms, use of the VS debugger is not possible.

If we registered only a single debugger, it would still be necessary to present multiple options to the user, on Windows.  Are you suggesting that we register a single debugger entry (to avoid the debugger selection that we are currently seeing), and provide 
 a superset of options that apply to the current platform, from our DebugConfigurationProvider?

@WardenGnaw , could you comment?  He is our debugger dev.

**Comment by weinand** [comment]
@

**Comment by weinand** [comment]
Yes, I'm suggesting that you register a single debugger and "GDB/LLDB" and "VS debugger" are configuration options in launch.json, user settings or workspace settings.

The benefit of this approach:
- users can use a single debug configuration in their projects instead of having to switch between two debug configurations,
- working on a project on different platforms works transparently because the debug configuration is always valid. If a "VS debugger" would be used, the corresponding debug configuration would be invalid as soon as the project is checked out on a non-Windows platform. This becomes especially evident in remote scenarios like WLS: a project developed in Windows would use the "VS debugger". Opening the same project in WSL (which is only a single click away in VS Code), will result in an invalid debug configuration because the "VS debugger" is no longer available on linux. If there is only a single debug configuration with a single "GDB/LLDB"/"VS debugger" configuration property, the implementation could easily fall back to "GDB/LLDB" in WSL.

**Comment by WardenGnaw** [comment]
I believe it was decided to have two different configurations since `"GDB/LLDB"` is a 3rd party debugger that speaks `MI` (Machine Interface and we utilize a DebugAdapter to convert `MI` into DAP `(Debug Adapter Protocol)`. `VS Debugger` is one that we actually develop and speaks directly to VS Code via DAP. 

Combining their configurations into one will be a mess since there are a bunch of fields that do not correlate to the other.
E.g. 
`miDebuggerServerAddress` is only applicable to the `GDB/LLDB` debugger and not the `VS Debugger`.

`GDB/LLDB` debugger and `VS Debugger` both work on windows while `GDB/LLDB` is the only debugger the C++ Extension should enable for macOS/Linux.

**Comment by weinand** [comment]
@WardenGnaw thanks for the explanation.

As already explained above, we cannot easily disable debuggers on platforms where the debugger is not supported because there are scenarios where users configure extensions or debug configurations for remote setups. In these cases the local platform and the remote platform differ, and a platform specific debugger extension would be invisible (or disabled) on one or the other. This would break the scenarios or would make them confusing for end users.

So in debug land we do not plan to introduce platform specific debugger extensions.
However, if VS Code will support platform specific extensions (via #23251) then this feature will certainly apply to debugger extensions as well.

For the time being I suggest to change the name of the windows only C++ debugger to "C++ (Windows only)" so that the limitations and consequences become more obvious.

**Comment by isidorn** [comment]
Covered by https://github.com/microsoft/vscode/issues/133146
