### ISSUE TITLE
Use Shadow DOM for notebook outputs?

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#120276]
#120137 uses Shadow DOM to isolate rendered markdown cells in notebooks.I propose we also adopt Shadow DOM for the output renderers.

The main benefit is isolation: Shadow DOMs should prevent css from one output rendered leaking over into another output renderer. It should also help prevent css from an output renderer leaking into the rest of the back layer webview. This isolation would not be perfect, but I think using a Shadow DOM would steer output renderers in the correct direction

**This would be a breaking change for the output renderer API**. Specifically, it would break renderers that insert global styles/scripts into the back layer webview. Code [like this](https://github.com/microsoft/vscode-github-issue-notebooks/blob/bcb13e010c73d99682aaa0e4348fca79f27bc0b2/src/renderer/index.tsx#L11) from the GitHub issue notebook would no longer work (although the workaround is pretty simple: just insert the link tag into the Shadow DOM instead)

**Comment by connor4312** [comment]
I think the only breaking part is that the CSS would need to be injected differently. We already provide the container that the renderer should operate within to the render method -- that would just be in a shadow DOM.

For styles, I think we should pass in a convenience method in the renderer API, since most off-the-shelf tools (like webpack's css-loader) will not work. For example, methods `addCssStyles` and/or `loadStylesheet` that would place styles inside that output's shadow DOM.

My only concern would be around people who use 3rd parties libraries and frameworks. The web being what it is, there isn't a standard way for libraries to load CSS. Some use inline styles which would work great, but, others load or inject global styles -- not always in a configurable way. This might be a stumbling block for users.

**Comment by rebornix** [comment]
Loop in @DonJayamanne , not sure what potential issues we may run into adopting this with nteract.

**Comment by DonJayamanne** [comment]
Today we load the styles for widgets as part of the preloads for the kernel.
Thus when rendering ipywidgets, the expectation is the styles have already been loaded into the DOM.
We'd need to re-apply the styles into the shadow DOM.

So yet, based on my understanding of shadow DOM this would be an issue.
We'd need to re-package the styles with webkack so that it can be applied into the output, would be an interesting packaging problem/challenge, as may controls pull in styles as part of the js/ts code.

**Comment by mjbvz** [comment]
@DonJayamanne Yes you'd have to inject the styles in the Shadow DOM element. You can simply clone an existing node into the Shadow DOM for this. Here's what we do for markdown renderers for example:

https://github.com/microsoft/vscode/blob/d4412e708ae4fc9042caf0e425d9f7ee00629411/extensions/markdown-language-features/notebook/index.ts#L29


Browsers optimize for this use case so it should not result in the style or its linked resources being downloaded multiple times.

I don't think you'd have to change your packaging unless your packaging, you'd just need to make sure the existing styles end up under the Shadow DOM too

**Comment by DonJayamanne** [comment]
One of the problem is I don't know what styles are injected by the widgets.
Its more about something that'll have to be experimented with.
I cannot provide a definitive answer.

Basically this could be a breaking change for ipywidgets (which as it stands is very complext with a lot of moving parts). If we have the ability to move back to non-shadow dom then its ok.
Right now the only benefit is preventing styles leaking around. 
This might not be much of an issue for Jupyter notebooks as we do most of the rendering work.

**Comment by mjbvz** [comment]
Thanks for the background. The main concerns on the VS Code side:

- It will be difficult to change this after finalizing our notebook api (ipywidgets may have already forced our hand here however since they already have been written)

- It's quite easy for new notebook extension authors to add styles that could break other outputs without realizing it.

- Style leaking, not just between multiple different types of outputs but also with parts of the backlayer webview UI that VS Code controls.

- Encapsulation would give us more flexibility when changing the backlayer webview's structure/style in the future

**Comment by DonJayamanne** [comment]
I would love to use the DOM simply because of the benefits (its just cleaner, simple as that).
Its pretty much a no brainer.

Is it possible to add support for this and provide a backdoor for Jupyter extension, so that we have time to identify the issues and fix any resulting issues.

Perhaps this could be something for the weekly sync meeting - discuss on a path forward (@rebornix /cc)

**Comment by connor4312** [comment]
While I like the idea and concepts behind it, I think ultimately I would agree with Don that we either should not do it, or provide a backdoor out of it.

Style loading in JS, particularly dealing with libraries, is always a pain and there seemingly are as many strategies to load styles as libraries that use them. Getting them to load into the shadow DOM is likely to be challenging, and in some cases would require having a custom build of the library if it's hardcoded to inject styles in the head (e.g. anything using the webpack `style-loader`). Then any library that injects things outside its root (common for tooltips and other overlays) will need its styles injected globally, which is another hurdle.

**Comment by DonJayamanne** [comment]
Or how about running an experiment for this like the one that has been running for a while in vscode - iframe in place of webviews.

In insiders we use shadow DOM and slowly identify the issues with the plan of someday (eventually) using shadow DOM, and have all new notebooks always use the new shadow DOM.
This provides a way to force extension authors to use the new approach, and those who've already built extenions end up using the old approach.

I'm just trying to find middle ground here, and find a way forward. Though I know it will take a while for IpyWidgets to move to shadow DOM, and its possible that it might never work out (all dependends on the 3rd party widgets out there in the wild).

**Comment by mjbvz** [comment]
@DonJayamanne I don't think this is something we could easily experiment with since it requires code changes in the renderers (typically to copy the styles into the shadow dom) 

Perhaps the most pragmatic solution here is to keep the existing, non-isolated DOM structure but still encourage custom renderers to create a shadow dom in their `render` implementation (while also updating the custom renderer extension sample to use one)

**Comment by DonJayamanne** [comment]
> implementation (while also updating the custom renderer extension sample to use one)

Yes that works, as we update the sample extensions, kusto, GitHub issues, etc, then the likelyhood if users creating the other way (non shadow don) is less likely

**Comment by mjbvz** [comment]
@connor4312 Any concerns about also adopting shadow dom in the `yo code` renderer template? I see we already have CSS modules set up which is good for making sure our css doesn't effect other renderers, but I believe another renderer's css could still leak into our renderer

**Comment by connor4312** [comment]
No concerns, we should just make sure that the CSS works out of the box with it too

**Comment by mjbvz** [comment]
Update the sample extension to use this too

@connor4312 or @tanhakabir It looks like you've been publishing the generator. Could you please take a quick look  at the changes and publish if everything looks good?

**Comment by tanhakabir** [comment]
@mjbvz will do!
