### ISSUE TITLE
I added correct syntax highlight for `-ms-viewport` and `-o-viewport`.

### ISSUE THREAD

**Issue by george-tr6** [microsoft/vscode#120374]
I added correct syntax highlight for `-ms-viewport` and `-o-viewport`.

_Originally posted by @octref in https://github.com/microsoft/vscode/issues/54515#issuecomment-409044792_

**Comment by george-tr6** [comment]
I see the same issue after the latest update Version: 1.55.0. 
Previous issue related to this bug was #54515

**Comment by alexr00** [comment]
We recently moved to a different CSS grammar for providing syntax highlighting. The old one was unmaintained, and the new one has good fixes in it. You can see the full discussion here: https://github.com/Microsoft/vscode/issues/115480

Specifically, see https://github.com/Microsoft/vscode/issues/115480#issuecomment-776376851, which references `viewport` as a deprecated feature (details https://developer.mozilla.org/en-US/docs/Web/CSS/@viewport). Even though the new grammar is missing `ms-viewport`, we decided to go with it because the benefits of having a maintained grammar outweighed the negative of missing the deprecated `ms-viewport`. 

If you feel strongly that this is essential for the grammar, I recommend going to https://github.com/atom/language-css/, the repo that we pull our css grammar from, and filing an issue there to ask for `ms-viewport` to be supported in their textmate grammar.

**Comment by george-tr6** [comment]
Thank you for the detailed explanation Alex! 
I was using this feature for emails and as we know the email coding is kind of stuck in the past :)
I will work on retiring this deprecated feature in my code as it seems that it is not essential anymore. 

Thanks again and have a great day!
