### ISSUE TITLE
[extension api] vscode.workspace.onDidOpenTextDocument can't be triggered

### ISSUE THREAD

**Issue by f111fei** [Microsoft/vscode#1203]
My extension is activated when code startup.

	"activationEvents": [
		"*"
	]

and the activate function like this 

	export function activate() {
		vscode.workspace.onDidOpenTextDocument((d)=>{
			vscode.window.showInformationMessage("[Document Opened]:" + path.basename(d.fileName));
		});
	}

But vscode never showInformationMessage when startup although there are a document opened at first.

I try to  use the `-logPluginHostCommunication` command line argument.

I find that `_acceptModelAdd` be called before `$activatePluginInPluginHost`

![1](https://cloud.githubusercontent.com/assets/7069719/11749753/884b301e-a06a-11e5-89e7-b09a2bc4b469.png)

so it's too late to listen `onDidOpenTextDocument` when my extension is activated.

**Comment by alexandrudima** [comment]
@f111fei we do not block the opening of the file until all "eager" (`*`) extensions are activated because we want the user to get to see/edit the file as soon as possible.

So there is no guarantee that extensions will get loaded before anything happens in the system.

That's why we have the api: `vscode.workspace.textDocuments` that shows all current opened text documents - this can be used to check if anything happened before the extension was loaded.

**Comment by f111fei** [comment]
@alexandrudima yes，I see

**Comment by jrieken** [comment]
At one point we could add something like `trackTextDocument(callback)` and it would mean invoke `callback` with all current text documents and for the future invoke `callback` on open.

**Comment by f111fei** [comment]
@jrieken  OK, I will try it as you said. Thanks
