### ISSUE TITLE
Hang and listener leak in workspace trust manager

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#120491]
- Open workspace trust manager and scroll down
- A couple times, the window stopped responding to input
- After 30 seconds, it starts responding again and prints a lot of listener leak warnings
- Sometimes it disconnects from the remote

![image](https://user-images.githubusercontent.com/323878/113497291-84086200-94b7-11eb-9ed7-07f0d960a24e.png)

**Comment by lszomoru** [comment]
@sbatten I believe that these are related to the changes that you have made to the extensions list as I am able to reproduce the same behaviour if I open the extensions viewlet.

**Comment by sbatten** [comment]
https://github.com/microsoft/vscode/commit/04d8568000be8eaab79fcf851499b9d58633adfb

**Comment by sbatten** [comment]
The rendering of the editor, being async would cleanup the widgets then re-render them multiple times due to events firing. So that was one problem. Aside from that, there was an existing issue with the listener leak being triggered by the fact that we just have a lot of extension widgets rendered. this wasn't a leak but I've bumped the warning threshold for the complaining emitters
