### ISSUE TITLE
Format on save for a notebook

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode#120432]
Formatting with 'Format Cell' and 'Format Notebook' works but saving a notebook does not apply the formatters to each cell like a normal file would.

Example notebook cell that would be formatted if it was python:

```python
\





print("hello, world")

# output


print("hello, world")
```

**Comment by rebornix** [comment]
I'm wondering if it's something we can benefit from the file/workingCopy service.

**Comment by jucor** [comment]
If that makes it easier, `black` now supports formatting `.ipynb` files natively, like it supports `.py` files.

**Comment by NickCrews** [comment]
I'd also love format on save for notebooks. As mentioned above, I can use `black **/*.ipynb` and it works great (you need to install black with the jupyter extra, eg as `python -m pip install black[jupyter]`), but I'm now just banging my head against the wall trying to get this to run automatically...

**Comment by alanwilter** [comment]
> I'd also love format on save for notebooks. As mentioned above, I can use `black **/*.ipynb` and it works great (you need to install black with the jupyter extra, eg as `python -m pip install black[jupyter]`), but I'm now just banging my head against the wall trying to get this to run automatically...

I really wish it could automatically format on save for jupyter notebooks.

**Comment by waydegg** [comment]
Any update on this?

**Comment by janosh** [comment]
@NickCrews There is `"editor.codeActionsOnSave"` but it doesn't allow running arbitrary shell commands (for security reasons?) so you'd need to install an extension like [Run On Save](https://marketplace.visualstudio.com/items?itemName=emeraldwalk.RunOnSave) and get it call to `black path/to/file.ipynb` on save events.

Sadly even that doesn't work atm since VS Code does not yet expose lifecycle events for notebooks. The issues to upvote for that are

- https://github.com/emeraldwalk/vscode-runonsave/issues/57
- https://github.com/microsoft/vscode/issues/130799

If both get implemented, you should be able to add this to your settings to auto-format Jupyter notebooks:

```json5
"emeraldwalk.runonsave": {
  "commands": [
    {
      "match": "\\.ipynb$",
      "cmd": "black ${file}"
    }
  ]
}
```

**Comment by jrieken** [comment]
same/related to https://github.com/microsoft/vscode/issues/130799

**Comment by rebornix** [comment]
This can now be turned on by setting `"notebook.formatOnSave.enabled": true`.
