### ISSUE TITLE
How to update a single child node from a list of hundreds of child nodes under a TreeItem parent

### ISSUE THREAD

**Issue by davidkjackson54** [microsoft/vscode#120437]
I have an Explorer Treeview and a parent in the tree can have hundreds of child nodes.  Each child node then has right click options to perform specific tasks.  
A right click option can change the state of the child node and so I need to refresh that child node in order toe re-establish the current state and refresh the right click options.
Currently, I am having to perform a refresh on the parent node which is then triggerts onDidChangeTreeData  which then in turn triggers getChildren to go  rebuild that entire child structure below the parent. This all works but it is very  inefficient and takes time to go through and rebuild as there can be hundreds of child nodes and each is refreshed by issuing a REST api to another platform.

 I can find no documentation on how I can get access to just the specific child node from the array of child nodes that was originally created in getChildren too allow me to update just that single child entry..
 
 Is there the ability to update a single child node ? I have not found any example of suggestions in this area.
 
 Same question for deleting one single child node ?? Without having to rebuild the entire parent structure? 
 
 Thanks

**Comment by boltex** [comment]
@davidkjackson54 The api states that you can refresh a node: 

onDidChangeTreeData?: Event<T | undefined | null | void>

An optional event to signal that an element or root has changed. This will trigger the view to update the changed element/root and its children recursively (if shown). To signal that root has changed, do not pass any argument or pass undefined or null.

(The 'T' in the typing  of this event is the type of the node of your custom treeview, meaning that it can accepts a particular node to refresh - and will refresh its children if expanded.)

Just grab a reference of the clocked node in your handler method of your application. (commands on nodes receive the node as parameter) and use it to pass on through when calling onDidChangeTreeData with the actual node (instead of its parent, or root or whatever)

I do so in my extension if you want to look at it.  https://github.com/boltex/leointeg

Have a good day! :)
