### ISSUE TITLE
Sync error with PAT

### ISSUE THREAD

**Issue by petrxpx** [microsoft/vscode#120416]
- VS Code Version:  1.55 insiders
- OS Version:  win10 corporate

Steps to Reproduce:
This issue is part of  #118675
1. Error syncing with PAT in VSCode insiders
2. 1.56 same error(
![vscode](https://user-images.githubusercontent.com/51874890/113405074-e1b28680-93b1-11eb-8945-199ab1014776.PNG)

)

**Comment by sandy081** [comment]
This is expected because we do not support PAT due to the security reasons.

**Comment by altokarev** [comment]
+1

@sandy081 so how can I achieve settings sync + PAT login at the same time?

Anyway, this used to work and by any large, is a frequently used scenario - having settings sync alongside with ability to push to internal repos of your organization.

Maybe there are any alternatives?

**Comment by sandy081** [comment]
@lszomoru @Tyriar FYI

**Comment by altokarev** [comment]
Hey @sandy081 @Tyriar 👋 

![image](https://user-images.githubusercontent.com/28726429/115928883-84c95e00-a48f-11eb-8403-d8bdd5a049c9.png)

Any news?

**Comment by altokarev** [comment]
Hey! @sandy081 @Tyriar @lszomoru 👋 

I've updated my PAT to the new format and started to get an error even on Mac:

![Screenshot 2021-05-21 at 01 48 48](https://user-images.githubusercontent.com/28726429/119058344-e4efe900-b9d6-11eb-9271-80d41f0b77de.gif)

macOS 11.3.1 (20E241)
VSCode 1.56.2

And must highlight the answer still has no answer - how can I use my corporate login with PAT alongside with settings sync enabled?

**Comment by Tyriar** [comment]
Settings sync does not support PATs by design as it's a requirement that we use and verify an app-issued token to prevent security issues. To support GH enterprise we would need to do one of:

- Allow both GH and GH enterprise to be signed in such that settings sync can be used with a regular account
- Setup a separate vscode auth app for GH enterprise so we have another app to verify against (this would likely end up involving the Live Share + Codespaces team)
