### ISSUE TITLE
Support more ANSI sequences to the integrated terminal

### ISSUE THREAD

**Issue by MCWertGaming** [microsoft/vscode#120572]
Hello,
it would be nice if the visual studio code integrated terminal could render more ansi characters. Some (probably the most important ones) are already supported but many are missing.

This is supported:
- bold (\033[1m)
- dim (\033[2m)
- italic (\033[3m)
- conceal (\033[8m)

Not supported:
- underline (\033[4m)
- blinking (\033[5m)
- rapid blinking (\033[6m)
- crossed (\033[9m)
- overline(\033[53m)
- double underline (\033[21m)
- framed (\033[51m)
- encircled (\033[52m)
- proportional spaced (\033[26m)
- colored underlining (\033[58;Xm) or (\033[58;R;G;Bm)
-> X means an 8 bit color code and R / G / B color values of the 24bit / true color / RGB color space

Broken:
- reversed (\033[7m)
-> output is not reversed but has white background

More info on that on it's wikipedia page:
https://en.wikipedia.org/wiki/ANSI_escape_sequence

Cheers!

**Comment by mill1000** [comment]
Underline was supported and working until very recently. I don't know if it's removal was a conscious decision or regression.

**Comment by mill1000** [comment]
Switching the integrated terminal renderer type from "auto" to "canvas" brings back the underline for me on 1.55. #120682
i.e.
```
"terminal.integrated.rendererType": "canvas"
```

**Comment by meganrogge** [comment]
@Tyriar is this not supported by the webgl renderer?

**Comment by Tyriar** [comment]
Underline doesn't work in the webgl renderer, this is tracked in https://github.com/microsoft/vscode/issues/121023

For dim it is supported, but I don't think it is in the native Windows Console API so it falls apart there. To tell whether it's an issue on our end or the backend you could test it in Windows Terminal, but I'm pretty sure dim works fine.

As for the others, we made an explicit decision not to support blink because it's an accessibility nightmare and it's rarely used. I haven't actually seen a lot of the other suggestions, we typically work off https://invisible-island.net/xterm/ctlseqs/ctlseqs.html when implementing this stuff and only implement when multiple popular terminals already support them like iTerm/Terminal.app/Windows Terminal/VTE(gnome terminal, konsole, etc.)

If you're really keen on some of those then https://github.com/xtermjs/xterm.js would be the place to request and discuss.

**Comment by GCSBOSS** [comment]
Just to note. On my tests in Windows 10, VSCode 1.56.
- PowerShell window doesn't have dim.
- Windows Terminal with PowerShell backend: **Does have dim**.
- VSCode Terminal with PowerShell backend: Does **not** have dim.

**Comment by Tyriar** [comment]
xterm.js definitely implements dim:

<img width="221" alt="Screen Shot 2021-05-07 at 7 26 41 AM" src="https://user-images.githubusercontent.com/2193314/117464501-92f29200-af05-11eb-810e-d22e8d5a0f83.png">

They may have fixed it in conpty recently as we lag behind significantly since we use the version that's shipped with Windows itself, they bundle it.
