### ISSUE TITLE
VS code removes unreachable code when fix on save enabled

### ISSUE THREAD

**Issue by Gentlee** [microsoft/vscode#120582]
- VS Code Version: 1.55.0
- OS Version: macOS 11.2.3

Steps to Reproduce:

1. Have fix on save enabled
2. Have unreachable code (for example while refactoring)
3. Press save while refactoring.
4. Surprisingly notice that after refactoring half of your code was removed.

How it should be:

1. This particular issue shouldn't be auto fixed on save, or there should be setting to disable such behavior (but who ever wants his code to be silently removed while refactoring? i guess no one).

I know this is a duplicate, but issue still exists while all similar issues were closed.

Does this issue occur when all extensions are disabled?: Yes

**Comment by Hadakajime** [comment]
CORRECT! Work-in-progress should not be actively deleted by vscode when saving.

Maybe I don't have time to finish everything at the current time; or perhaps I'm writing down some notes or ideas; or perhaps I'm just depositing something valuable from my clipboard contents which I want to save for later.

MAYBE MY LAPTOP IS ABOUT TO RUN OUT OF BATTERY AND I JUST NEED TO SAVE WHATEVER I HAVE WITHOUT FEARING IT WILL DELETE HALF THE FILE!!!

**Comment by jbfm** [comment]
This has bitten me so many times it's absurd

**Comment by incompl** [comment]
I have autosave on close. I closed a file, it deleted 99% of the file and saved it without prompting me. When re-opening there is no undo. That file was just gone.

It is a good practice to save frequently. In the course of normal development, the code will go through various invalid states before arriving at a valid state. It is unwise to defer saving your work because your editor will delete your progress.

Is there any way to disable this functionality? It should not be the default, but at the very last there should be a way to opt out.

I insist that my 1 vote count for 15 votes because of my superior confidence that this behavior is unacceptable.

**Comment by jbfm** [comment]
@incompl you can disable it by adding `"allowUnreachableCode": true,` to your `tsconfig.json`

**Comment by jbfm** [comment]
@mjbvz any change of getting this re-opened and possibly not viewed as a straight up feature request? I'm convinced there are lots of users very confused by this behavior, but just figuring out that it's the unreachable code setting that's causing this is a process in itself.
