### ISSUE TITLE
Wrong git indicators of scroll position

### ISSUE THREAD

**Issue by KaduAmaral** [microsoft/vscode#120553]
- VS Code Version: 1.55.0
- OS Version: Ubuntu 20 (Linux x64 5.4.0-70-generic)

Steps to Reproduce:

1. Open a huge file (1000 lines more) already commited
2. Insert 20 lines or more at the middle of file
3. Scroll until the new lines almost disapear from screen
4. Check if the painted git indicators and scroll position are corresponding with screen

Does this issue occur when all extensions are disabled?: Yes

Check this print, the new lines is above the screen, but on scroll indicator the "green" paint is at the middle-bottom. My guess is that the size of scroll indicator is bigger than should be.

![image](https://user-images.githubusercontent.com/4316607/113580747-86c09f80-95fc-11eb-8331-ad243cd29c8b.png)

PS.: If you check the minimap it's correct both postion and size.

**Comment by alexdima** [comment]
This happens because the scrollbar slider has a minimum height. The idea is that the slider would become too small if it would respect the viewport/file height ratio in large files and it would become too difficult to click on it. So the slider is artificially kept at a minimum of 20px height. This makes it that it becomes imprecise.

**Comment by KaduAmaral** [comment]
Ok.
