### ISSUE TITLE
Untrusted indicator on workspaces disappears

### ISSUE THREAD

**Issue by tamuratak** [microsoft/vscode#120500]
`Untrusted` indicator on workspaces disappears. Related to #106488.

Version: 1.56.0-insider
Commit: 550035808407c15252e581e8abe1b820b9d311ee
Date: 2021-04-02T05:13:17.592Z
Electron: 11.4.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 18.7.0
Steps to Reproduce:

1. Set `"workspace.trustEnabled": true` in the global `settings.json`
2. Open a directory.
3. Select `Don't Trust`
2. `Untrusted` indicator is displayed in the bottom left.
3. Open a new window. Go back to the previous window.
4. `Untrusted` indicator has disappeared.

![スクリーンショット 2021-04-04 17 49 28](https://user-images.githubusercontent.com/10665499/113503757-baed7f00-956e-11eb-955a-b6eef7c9b29d.png)

![スクリーンショット 2021-04-04 17 49 42](https://user-images.githubusercontent.com/10665499/113503764-cb9df500-956e-11eb-9c0b-c5f6ce6d7637.png)

**Comment by sbatten** [comment]
@bpasero just noticing that visibility of a status bar entry is not workspace scoped. do you know how do we handle this for extensions?

**Comment by bpasero** [comment]
If the user decides to hide a status bar entry, we persist this globally assuming that this is an explicit choice for each window. I for example decide to hide the notifications and feedback icons in the lower right corner. Asking me to hide this in each workspace would be brutal.

I do not really understand how this applies to extensions.

**Comment by sbatten** [comment]
This is not a user decision. The user can hide the indicator if they like but the default behavior we are trying to support is:

If the workspace is trusted: hide the indicator since the user should not be concerned with it
If the workspace is untrusted: show the indicator to remind the user that they are in a limited environment
If the workspace is unspecified: show the indicator if trust has been requested, otherwise hide it

Unfortunately, it seem once we show or hide it in one window, the other windows get the same visibility.

Some extensions show some status bar items, are they forced to show it in every open window? How does it work if the extension is not active in one of the windows?

**Comment by bpasero** [comment]
I don't think extensions should be using the storage API but just our `show` / `hide` commands to decide wether to show it. E.g. our typescript indicator only appears when a TS file is open.

**Comment by sbatten** [comment]
we are doing this from core calling `updateEntryVisibility` but it affects all open windows, how do we only apply to the current workspace. or are using the wrong core api? https://github.com/microsoft/vscode/blob/d3d7966f8cf1b66d24b40fb235685f8f75679d23/src/vs/workbench/contrib/workspace/browser/workspace.contribution.ts#L246

**Comment by bpasero** [comment]
I think we never had API in the workbench to show/hide and this is how the extension host does it:

https://github.com/microsoft/vscode/blob/376716d1aeef7f64002068308ea45a91fab25a96/src/vs/workbench/api/common/extHostStatusBar.ts#L145-L154

As you can see, `dispose` is called to hide and when the item should get visible after being disposed it would need to be recreated. 

I think I only added `updateEntryVisibility` for one case: to have a checkbox in the "Send a smile" widget to disable the entry:

![image](https://user-images.githubusercontent.com/900690/113813774-d32cec00-9770-11eb-8c10-6b29ad70e1dd.png)
