### ISSUE TITLE
[API] Wrong "textDocument.languageId" on SCM

### ISSUE THREAD

**Issue by TobiasSekan** [microsoft/vscode#120537]
Version: 1.55.0 (user setup)
Commit: c185983a683d14c396952dd432459097bc7f757f
Date: 2021-03-30T16:01:55.261Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

Problem:
I currently working on my plugin for Visual Studio solution files (*.sln)
(https://github.com/TobiasSekan/SolutionExtension)

And I was wonder why a merge was not show any diagnostic.
So after a little debug I have found that when I open a solution file via the SCM the `textDocument.languageId` is set to `plaintext` and not to `sln`.
I think the Problem is that the `fsPath` of the document end with `sln.git`  and not with `.sln`.
vscode itself understand this and show the correct language in the language selector (bottom right).

my current workaround for this is (`src\RegisterEvents.ts`)
```
       // this.languageId = "sln"

        // My normal way
        if(textDocument && textDocument.languageId === this.languageId)
        {
            this.diagnostic.UpdateDiagnostics(textDocument);
            return;
        }

        // My workaround 
        if(textDocument
        && textDocument.languageId === 'plaintext'
        && textDocument.uri.fsPath.endsWith(`${this.languageId}.git`))
        {
            this.diagnostic.UpdateDiagnostics(textDocument);
            return;
        }
```

Steps to Reproduce:

1. Open a supported file on scm
2. Check the `languageId` of the current visible document

Does this issue occur when all extensions are disabled?: No

**Comment by lszomoru** [comment]
@TobiasSekan, thank you very much for reposting this issue and apologies for not getting back to you on this issue. At the moment we are not planning on making investments in this area or the product, and since you already have a workaround in place that mitigates the issue, I will go ahead and close this issue as part of our [housekeeping milestone](https://github.com/microsoft/vscode/wiki/Issue-Grooming). In case you have any further questions or concerns please feel free to reopen the issue. Thanks!
