### ISSUE TITLE
formatOnType does not work when you navigate away from the edited line

### ISSUE THREAD

**Issue by tnikodym** [Microsoft/vscode#12064]
- VSCode Version: 1.5.2 
- OS Version: OSX 10.11.6

I have `"editor.formatOnType": true` in my settings.json. It works fine when I press enter or closing bracket, but when I navigate away from the edited line (e.g. press UP/DOWN arrow, mouse-click, ...) it does not format the edited line. 

Steps to Reproduce:

1. Type `let a = 1;`
2. Press enter
3. Navigate back to the line and add some whitespace before the number 1
4. Press DOWN arrow
5. Notice that the line stays incorrectly formated

**Comment by jrieken** [comment]
Yes - format on type only works on certain trigger characters. Extension define what those characters are, for instance TypeScript uses `\n`, `;`, and `}`. 

Assuming your sample is TypeScript/JavaScript this is what happens

* press enter on well formatted `let a = 1;` triggered format on type (`\n`)
* format on type returns without edits
* go back to line, miss-format, go back -> No change because arrow keys don't trigger format on type
