### ISSUE TITLE
It doesn't delete the matching close bracket when deleting the open bracket

### ISSUE THREAD

**Issue by leadream** [microsoft/vscode#120778]
- VS Code Version and OS Version:
Version: 1.55.0
Commit: c185983a683d14c396952dd432459097bc7f757f
Date: 2021-03-30T16:01:05.981Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 19.6.0

Steps to Reproduce:

1. point at a bracket with nothing in it
2. delete open bracket, the close bracket is not deleted automatically

![Apr-08-2021 11-07-06](https://user-images.githubusercontent.com/12868055/113962924-3d21c000-985b-11eb-8716-ebe1bdd9a637.gif)

Does this issue occur when all extensions are disabled?: Yes/No
No

**Comment by dkaste** [comment]
I think the `editor.autoClosingDelete` setting was either added or its default value was changed silently. You can change it from `auto` to `always` to get the old behavior.

Changes like this have silently happened multiple times in the past. I really wish there was a way to lock all settings so they can't be changed and break peoples' workflow. At least there should be some kind of prompt to ask the user if they want different behavior instead of doing it silently.

**Comment by leadream** [comment]
@dkaste Thanks Dkaste, it worked. Yes, silent changing just confused us.

**Comment by alexdima** [comment]
I am sorry about that. I have documented it in the meantime at https://code.visualstudio.com/updates/v1_55#_new-auto-closing-pair-deletion , but it was late, after the release went out. As folks have noted, the old behavior can be achieved using `editor.autoClosingDelete: always`. This change aligns the default behavior of backspace with the default behavior of overtyping, i.e. the editor will by default remove or overtype only the matching brackets or matching quotes that it auto-inserted.

Again, sorry about the breakage :heart: !
