### ISSUE TITLE
Notebook: Need a way to unload preload scripts (or an event to indicate an unload)

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode#120747]
If you have a notebook rendering ipywidgets and then change the kernel, the ipywidgets preload scripts will be loaded twice. 

This will break the connection to the kernel with the ipywidgets scripts. See this bug here:
https://github.com/microsoft/vscode-jupyter/issues/5424#issuecomment-815079081

**Comment by rchiodo** [comment]
We could do this ourselves, but it seems like it might be generic enough to warrant something in the API?

**Comment by connor4312** [comment]
There is not a way to 'unload' JavaScript sources. Once executed the script will continue to exist and any side effects will continue unless manually/individually disposed of.

However it could be useful to provide an event to the preloads that they can listen to when a switch happens in order to do so.

**Comment by rchiodo** [comment]
For unload I was thinking that the entire IFrame should be removed? The kernel is different, all state is invalid.

**Comment by jrieken** [comment]
> For unload I was thinking that the entire IFrame should be removed? The kernel is different, all state is invalid.

Yeah, I think when we change kernels and the current kernel had preloads we need to refresh the whole iframe
