### ISSUE TITLE
Register `workbench.action.files.openFolder` / `workbench.action.files.openFile` command even on macOS

### ISSUE THREAD

**Issue by bwateratmsft** [microsoft/vscode#120752]
- VS Code Version: 1.55.0
- OS Version: OS X

Steps to Reproduce:

1. Open command palette
2. Search for "File: Open Folder"

It's not there 😨

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by bwateratmsft** [comment]
Screenshot:
![image](https://user-images.githubusercontent.com/36966225/113918073-fcb93800-97af-11eb-8fed-efa42e2fe775.png)

**Comment by isidorn** [comment]
I think on the macOS we always only had `Open...`. However forwarding to @bpasero so he can close as designed

**Comment by bpasero** [comment]
macOS is the only OS that allows to combine file and folder picker into one so we did that.

**Comment by bwateratmsft** [comment]
Huh, I'm a dummy. I guess I never noticed that. @bpasero is there an argument I can pass to the Open command to indicate that it should only allow opening folders (not files)?

**Comment by bpasero** [comment]
It looks like we actually do not even register the command on macOS:

https://github.com/microsoft/vscode/blob/ef1f94d969bde185aa0fcc2bd801f33deb3d32eb/src/vs/workbench/contrib/files/browser/fileActions.contribution.ts#L50-L55

Reopening as feature request, I think we could probably still register the command so that extensions could trigger it?
