### ISSUE TITLE
Scorer is not very good for matching on filenames

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#12095]
- VSCode Version: 1.5.2
- OS Version: OS X 10.11.6

![image](https://cloud.githubusercontent.com/assets/4033249/18561000/dc20d4e8-7b32-11e6-8a17-4ba7dd48ac11.png)

The repo is Microsoft/vscode.

**Comment by bpasero** [comment]
This is actually a corner case where our scoring is bad: Parts of the filename (`explorerview.ts`) end up matching on the folder instead of the file name. It is just bad luck that in this case `explorerView.ts` has parent folders that match more on the query compared to `explorerViewModel.ts`. 

Overall we need to revisit our scoring functions and improve it to work better with files.

**Comment by bpasero** [comment]
Fixed via https://github.com/Microsoft/vscode/commit/9d40f0c647bf1de0aaa813e6519b85a24e98da14
