### ISSUE TITLE
Extension activation errors not showing for VSIX installs

### ISSUE THREAD

**Issue by clovis-dugue** [microsoft/vscode#120932]
- VS Code Version:1.55.1
- OS Version:Ubuntu LTS

Steps to Reproduce:

Repository with detailed information and a base bugged project available [here](https://github.com/clovis-dugue/vscode-extension-issue)
1. Generate an extension that errors on activation
2. Package this extension and install it via VSIX
3. The error message does not appear

Does this issue occur when all extensions are disabled?: Can not be applied

**Comment by alexdima** [comment]
> However nothing is shown to the user about the failing activation

We have decided to not show this class of errors to end-users. Activation errors or errors caused by invalid information in the `package.json` of extensions are only displayed in a notification when doing extension development. IIRC the problem was that very many users considered errors popping up to be a problem caused by VS Code. But the error is always shown in the developer tools (`Help > Toggle Developer Tools`) and is recorded in the window logs (`F1 > Developer: Show Logs ... > Window`).
