### ISSUE TITLE
Trusted workspaces restart prompt shows up and immediately goes away when changing the current folder

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#120950]
Repro:

1. Open workspace trust
2. Add the current folder
3. Scroll down
4. Change the current folder to its parent (eg. `/dev/microsoft` to `/dev`)

A native modal will appear briefly.

**Comment by sbatten** [comment]
@Tyriar cannot repro, i see the dialog but it does not flash

**Comment by Tyriar** [comment]
It was on Mac and happened every time I switched between them

**Comment by sbatten** [comment]
I blame macOS, they seem to be taking the keyup event of enter even though it was pressed before the dialog was shown. This is fixed by using custom dialogs, which we will be using for all trust dialogs moving forward. Not sure if that should apply to this one since we don't need to show more data here
