### ISSUE TITLE
Failed to connect to the remote extension host server (Error: WebSocket close with status code 1006)

### ISSUE THREAD

**Issue by tomchon** [microsoft/vscode#120919]
- VS Code Version: Version: 1.55.1 (Universal)
- OS Version: mac os 10.15.7 (19H524)

Steps to Reproduce:
dont know how tp produce，doubt that i  use vpn to view github. 
1. connect to my linux server
2. input twice password 
3. The error is thrown
```
Could not fetch remote environment
Failed to connect to the remote extension host server (Error: WebSocket close with status code 1006)
```
4. terminal  promote：
`channel 2: open failed: administratively prohibited: open failed。`

Does this issue occur when all extensions are disabled?: Yes
i can't disable some extensions, when i disable remote-ssh, it metioned that WebSocket close with status code 1006

**Comment by tomchon** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [Failed to connect to the remote extension host server (Error: WebSocket close with status code 1006) (#115818)](https://www.github.com/microsoft/vscode/issues/115818)

i can't find way to solve this problem from this issue

**Comment by tomchon** [comment]
i use CleanMyMac X to uninstall vscode , reinstall vscode， i can connect remote server successfully。

**Comment by Reyshawn** [comment]
I encountered the same issue and solved it by the following steps:
1. call `Remote-SSH: Uninstall VS Code Server from Host...` to uninstall the vscode server;
2. Then connect the host. The `Remote-SSH` will re-download the `VS Code Server` to the host, and it will take some time; 

I don't know why but it works for me.

**Comment by codepainting** [comment]
In my case the problem was with disc compression activated in Windows (Compress or Encrypt attributes).

For some reason the “Advanced attributes” for the disk/folder were set to “Compress contents to save disk space”.

Unfortunately this seems to break VS Code extensions functioning with WSL2. After turning this off and decompressing previously compressed files (and reinstalling VS Code in my case) everything went back to normal again.

Previously compressed files can be decompressed again by running CMD, CD to your user folder and running:

`compact /s /u /I
`
e.g.: `C:\Users\{user-name}>compact /s /u /i
`

Disabling disk compression completely can be achieved by running CMD in administrator mode and executing the following command:

`fsutil behavior set DisableCompression 1
`

**Comment by tomchon** [comment]
> > channel 2: open failed: administratively prohibited: open failed。
> 
> This means that your ssh server refused to forward a port, usually because tcp forwarding is disabled. I can't tell you why reinstalling vscode or the server would change that, sorry. Glad it's working now.

emmmmmm reboot or reinstall is the best way when u want to solve as soon as possible 。 but i really want to know  the reason

**Comment by tomchon** [comment]
> I encountered the same issue and solved it by the following steps:
> 
> 1. call `Remote-SSH: Uninstall VS Code Server from Host...` to uninstall the vscode server;
> 2. Then connect the host. The `Remote-SSH` will re-download the `VS Code Server` to the host, and it will take some time;
> 
> I don't know why but it works for me.

I think ur problem is that  sshd server can't work. so this way should  respair ssh'connection.
