### ISSUE TITLE
[Apple M1] Changing a User Setting causes the renderer to crash

### ISSUE THREAD

**Issue by abettadapur** [microsoft/vscode#120975]
- VS Code Version: 1.54.3
- OS Version: Mac OS 11.2.3 (ARM64)

On Apple M1 machines, changing the user configuration causes the renderer to crash

Steps to Reproduce:

1. Build VS Code for ARM64
2. Either via an extension, or through the User Settings UI, try to change a setting
3. The window immediately crashes

Does this issue occur when all extensions are disabled?: Yes

https://user-images.githubusercontent.com/2415669/114242097-2ce31100-993f-11eb-8126-55c37d927185.mov

The crash dump is here: 
[1e9c31a0-2d60-4595-bfdf-1e4c7af88f84.dmp.zip](https://github.com/microsoft/vscode/files/6288321/1e9c31a0-2d60-4595-bfdf-1e4c7af88f84.dmp.zip)

**Comment by deepak1556** [comment]
/duplicate https://github.com/microsoft/vscode/issues/113835

Tl:dr; if app is not code signed it will crash with OOM when loading wasm. Underlying issue is related to the memory allocators used in Electron 11 https://github.com/electron/electron/issues/27497. This is now fixed in main branch, please try again.
