### ISSUE TITLE
Support for tri-state boolean in settings UI

### ISSUE THREAD

**Issue by bobbrow** [microsoft/vscode#120991]
Our extensions have a few settings that we'd like to use booleans for, but we also want to have a third "automatic" value that selects true or false at runtime based on some criteria (e.g. if VS Code stable vs insiders is being used, or if a certain file is present in the workspace)

Our current approach has been to make the setting an enum, but if you pick values such as [ 'true', 'false', 'auto' ] this looks weird in the settings.json file when compared with the true boolean settings:
```json
{
  "ext.setting1": true,
  "ext.setting2": "true"
}
```
so we end up using synonyms like 'enabled', 'disabled', 'default' which is less than ideal.

Another approach would be to use "oneOf" and have the choices be type: boolean and type:string with a single enum value.  This gets the desired effect when editing the JSON directly, but unfortunately, we don't get Settings UI support when we try that.

Could we get a new type for configurations, or maybe some kind of UI support for tri-state bools? We'd be fine with whatever syntax would be required for package.json.

Thanks!

**Comment by roblourens** [comment]
I think there are two patterns we use for this - a `boolean | null` style, or the enum style that you mention. I actually prefer the enum for this scenario because it's explicit, it works well in JSON and a GUI, and is extensible. Have seen "default" or "auto" or something else more explicit.

I just don't know what a `boolean | string` type would look like in the GUI, same for a tri-state bool, this is not a normal sort of form thing. What are you expecting it to look like?

**Comment by bobbrow** [comment]
I didn't have any preconceived notion of what it should look like, but I think a dropdown with "true", "false", and "auto" as the options would be acceptable.  So from the UI point of view it would behave like an enum but the backing type would be `boolean | string`.

**Comment by roblourens** [comment]
Actually, we do support this. Here's an example

![image](https://user-images.githubusercontent.com/323878/114441865-c2211800-9b80-11eb-973f-4724d6cb68d4.png)
