### ISSUE TITLE
Add Python support

### ISSUE THREAD

**Issue by kennethreitz** [Microsoft/vscode#121]

**Comment by Tyriar** [comment]
What support are you after specifically? [Syntax highlighting is in](https://github.com/Microsoft/vscode/tree/master/extensions/python/syntaxes).

**Comment by zkanda** [comment]
I would love this feature as well, something on the level of https://github.com/microsoft/vscode-go

**Comment by cecilphillip** [comment]
python debugging would be nice ..

**Comment by xqliu** [comment]
+1 for python support, those might be expected 

 - Python / Django/ Flask debug
 - OmniComplete for method, class, functions etc.
 - On the fly syntax check for missing definition
 - Import of module suggestion.

**Comment by tytodorov** [comment]
+1 for @xqliu's list of features

**Comment by egamma** [comment]
pls see this comment on hacker news: https://news.ycombinator.com/item?id=10589451

**Comment by cecilphillip** [comment]
Fantastic. Guess we can close this issue

**Comment by zooba** [comment]
Or someone can assign it to me - my team will be working on Python support over the next 12 months to bring as much from https://github.com/Microsoft/PTVS as possible and also to give VS Code its own unique spin (since the needs and uses are different from VS).

Incidentally, if you're _really_ keen to see this happen and like the sound of living in Washington (state), drop me an email (on my profile) with a resume and let's chat.

**Comment by egamma** [comment]
Since the work on Python will happen in another repository than `vscode` I will close this issue.
