### ISSUE TITLE
VS code is acting slow

### ISSUE THREAD

**Issue by SR-22** [microsoft/vscode#121005]
-Version: 1.55.0 (user setup)
-OS: Windows_NT x64 10.0.19042

Hello there👋,
I have been using vs code for quite a long time. VS code is now really slow. Could it be because pf having so many extensions and themes enabled and installed. Please help me with this

Does this issue occur when all extensions are disabled?: Yes

**Comment by vu-dinh-hung** [comment]
Currently, there isn't enough info to determine what your problem might be exactly. How is VS Code slow? It is an issue with Intellisense? What language are you using? Does it only occur in a project you are working on, or it is also slow with a new empty file?

I recently encountered problems with Intellisense being very slow with JS in a node project. Turns out it was some issue with the built-in TS-JS language with large projects. I turned the extension off by going into Extensions -> type '@builtin' -> turn off 'TypeScript and JavaScript Language Features', and everything flies again. If your problem is similar (contained to a single language), try turning the language support off.

**Comment by SR-22** [comment]
I code in python c++ css html svgs js react
could it be because of my themes and extensions

**Comment by dziku86** [comment]
It is slow for some time now, I can confirm that. Did some digging in the issues and my conclusion is that it is related to one of the electron updates (that's the main reason, I think). Which one I can't tell. I don't remember when the slowdown started. 
Tested latest VSCodium and it runs smoothly with and without extensions.

**Comment by gjsjohnmurray** [comment]
See https://github.com/microsoft/vscode/wiki/Performance-Issues for advice

**Comment by SR-22** [comment]
thanks @gjsjohnmurray
