### ISSUE TITLE
@-ms-viewport is STILL an error

### ISSUE THREAD

**Issue by ctro99** [microsoft/vscode#121138]
- VS Code Version: 1.55.1 (Universal)
- OS Version: macOS Big Sur 11.2.3 (20D91)

Steps to Reproduce:

1. Create an HTML file with a CSS style block in the head 
2. Add this code within your style
@-ms-viewport {
      width: device-width;
    }
3. Now VS Code will not display your theme colors properly.

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexr00** [comment]
We recently moved to a different CSS grammar for providing syntax highlighting. The old one was unmaintained, and the new one has good fixes in it. You can see the full discussion here: https://github.com/Microsoft/vscode/issues/115480

Specifically, see https://github.com/Microsoft/vscode/issues/115480#issuecomment-776376851, which references `viewport` as a deprecated feature (details https://developer.mozilla.org/en-US/docs/Web/CSS/@viewport). Even though the new grammar is missing `ms-viewport`, we decided to go with it because the benefits of having a maintained grammar outweighed the negative of missing the deprecated `ms-viewport`. 

If you feel strongly that this is essential for the grammar, I recommend going to https://github.com/atom/language-css/, the repo that we pull our css grammar from, and filing an issue there to ask for `ms-viewport` to be supported in their textmate grammar.
