### ISSUE TITLE
Update TS language target/libs

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#121144]
Currently in our builds we target a subset of ES2017. However, now that Electron is on Node 14 we [should](https://github.com/microsoft/TypeScript/wiki/Node-Target-Mapping), and not supporting IE, be able to update as far as ES2020. This gets us helpful new features like flatMap.

Matt mentioned there may be concerns about Monaco compatibility as well.

**Comment by jrieken** [comment]
I believe we dropped support for leagcy edge and IE  and we should be good to go /cc @alexdima

**Comment by alexdima** [comment]
:+1: The editor has the same supported browsers as vscode web, so nothing special from that side. But whatever new ES feature we decide to use, we need to check that it works in Firefox, Safari, Chrome and Edge.

**Comment by mjbvz** [comment]
We are blocked on updating the target for our extensions until we upgrade to webpack 5: #121145

**Comment by jrieken** [comment]
Many, many checks on mdn later I was able to compile a long list of supported libs. There is a surprising large amount of new API that can be used in Chrome, Edge, and Safari. Noteworthy: `Promise.any`, `Promise.settled`, `Array.flapMap`, `String.replaceAll`, `WeakRef` (scary), `BigInt`, `Regex.dotAll` etc

https://github.com/microsoft/vscode/blob/fbe33fe21e093cd5d99ad6bda4d2425c9d11054f/src/tsconfig.base.json#L20-L46

This is almost all of es2021 minus Atomics and SharedMem for Safari (that's why the list spells out so many individual things)

**Comment by jrieken** [comment]
I have also set the (compile) target to `es2020`. As an extra: this reduced the output size of `workbench.main.desktop.min.js` by roughly 1%
