### ISSUE TITLE
Could views within the Explorer, SCM or Debug containers be allowed to be expanded by default?

### ISSUE THREAD

**Issue by a-stewart** [microsoft/vscode#121189]
When creating an extension that adds views to the SCM contribution point, all views are collapsed by default, even if you set `'visibility': 'visible'` in package.json.

I was wondering if perhaps it would be possible to update this so that rather than views in the Explorer, SCM or Debug containers always being collapsed by default, if the extension provides a visibility flag it is honoured (and if not it returns to the current behaviour).

**Comment by alexr00** [comment]
@a-stewart thank you for the issue, but this is actually by design. Since these are important built-in view containers in VS Code, we want to give them a curated experience that isn't too full of open views. We also have noticed that many extension want to contribute views to these view containers, and they can get quite crowded.
