### ISSUE TITLE
Change or remove Keymaps keybinding?

### ISSUE THREAD

**Issue by sana-ajani** [microsoft/vscode#121131]
We are running an A/B/C experiment where we show a text or button to encourage users to choose a language mode in an untitled file. 

![image](https://user-images.githubusercontent.com/9721254/114428775-9c990c00-9b8a-11eb-8c13-592418fc8ab1.png)

One thing we've seen so far, is a lot of users end up accidentally using the wrong keybinding. The hint contains the keybinding `cmd K M` which opens the language mode quick pick, but users often end up pressing `cmd K cmd M` which is the default keybinding for opening up the extensions view to search for keymaps. To avoid the confusion this creates for the user, I wonder if we can change or remove the keymaps keybinding. 

I wonder how discoverable this keybinding is and if it really needs a default keybinding. Especially as it is so similar to this language mode quick pick, which we would be showing to users in an untitled file.

I agree that removing a keybinding can break many users, but the usage of this keymaps one is quite low. Over the last 28 days, we've seen about ~23K users use the Keymaps keybinding (have a hunch that many of these might also be accidental):

![image](https://user-images.githubusercontent.com/9721254/114439771-5b5b2900-9b97-11eb-9064-08302836bc1a.png)

and about 869K use the language mode keybinding:

![image](https://user-images.githubusercontent.com/9721254/114440191-d4f31700-9b97-11eb-9053-b2cbd959f9ff.png)

Want to open this for discussion and see others' thoughts.

cc @isidorn @digitarald @chrisdias

**Comment by chrisdias** [comment]
I don't think we can remove the key binding, even 23K is a lot.  Either we remove it from the hint text so that people end up clicking instead of getting the wrong thing, or maybe we can we can be more verbose, something like "press CMD+K, then press M" to teach people how to read it?

**Comment by isidorn** [comment]
Assigning to @sandy081 since he owns the Keybindings editor.

While I do see @sana-ajani point in the keybindings being too similar and thus confusing, I am always defensive when it comes to removing existing keybindings since it simply breaks users muscle memory.

Ideally we would just remove it for new users, however we probably do not have the capability to do that right now.

@chrisdias we already removed it from the hint text in insiders.

**Comment by sandy081** [comment]
Yeah not a fan of removing existing keybindings unless there is a strong reason and I do not think the current use case is.

**Comment by digitarald** [comment]
So the current alternative to not removing the shortcut is [not showing it in the UI](https://github.com/microsoft/vscode/issues/114307#issuecomment-823325581), because we saw that users like to try out the shortcut (which was the intent and is a win), but are likely to hit the wrong shortcut. This seems wrong.

> I am always defensive when it comes to removing existing keybindings since it simply breaks users muscle memory.

Agreed, this would be a blocker for most shortcuts, but I would argue that "muscle memory" does not apply to a one-and-done task like "searching keymap extensions". We could query for that to verify.

- [ ] Kusto: How often does a single user install a keymap extension

> I don't think we can remove the key binding, even 23K is a lot.

I'd wonder how many of those are accidental.

- [ ] We could query the install-conversion numbers from users using using keyboard shortcut vs menu.

> unless there is a strong reason and I do not think the current use case is.

I would not frame this as a new use case, but rather an accidental discovery that a potentially known problem (switching modifiers in chained shortcuts) is bigger than we expected.

**Comment by isidorn** [comment]
@sandy081 is it ok for you if I remove the keybinding per the reasons stated above by @digitarald which I agree with. And if you get users complaining just assign those issues to me? 🤝 ?

**Comment by sandy081** [comment]
Fine with me.

**Comment by isidorn** [comment]
I have also changed the title of the command to make it more explicit, since for new users it is not clear what keymaps are. Here's the before / after

![Screenshot 2021-09-06 at 16 23 07](https://user-images.githubusercontent.com/1926584/132232794-77a16cd6-93b4-45eb-be79-582c44e090d2.png)

![Screenshot 2021-09-06 at 16 30 59](https://user-images.githubusercontent.com/1926584/132232799-bc167237-c8b1-4eb9-aa57-253f4749528c.png)

**Comment by isidorn** [comment]
We should also have a more prominent button from the `Keyboard Shorctus` UI to "Import Keyboard Shorcuts from".
Though I think @digitarald planned to create an issue for this.

@daviddossett this might be something to think about.

**Comment by daviddossett** [comment]
@isidorn @digitarald is the issue low discoverability of the import functionality?

**Comment by isidorn** [comment]
@daviddossett exactly. Also I feel like it deserves a spot in the `Keyboard Shortcuts` UI and there is enough space.

**Comment by daviddossett** [comment]
Ok, makes sense. @digitarald have you created an issue for this one yet?

**Comment by digitarald** [comment]
@daviddossett good call, created https://github.com/microsoft/vscode/issues/132677
