### ISSUE TITLE
Don't run codeActionsOnSave on focus changes

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#121155]
**Repro**
1. Enable `"files.autoSave": "onWindowChange"`
2. Enable `"editor.codeActionsOnSave": {"source.organizeImports": true}`
3. Create a JS file with an unused import
4. Now alt+tab to a different window

**Bug**
This ends up running `organize imports` which deletes the unused import

**Comment by mjbvz** [comment]
The feature is doing what it was designed to, but this UX is pretty bad

I think we should consider disabling codeActionsOnSave and formatOnSave for auto saves. We already seem to do this when the user configures `autoSave: "delay"`. Not sure why we don't have the same logic for auto saves caused by focus change

**Comment by mjbvz** [comment]
cc @andrewbranch

**Comment by jportner** [comment]
I was just trying to track down why my ESLint formatting workflow recently broke, and it seems to be because of this fix!

Just to clarify, here is my config that no longer fixes ESLint errors automatically on focus change:

```json
"files.autoSave": "onFocusChange",
"editor.codeActionsOnSave": { "source.fixAll.eslint": true }
```

> The feature is doing what it was designed to, but this UX is pretty bad
> 
> I think we should consider disabling codeActionsOnSave and formatOnSave for auto saves. We already seem to do this when the user configures `autoSave: "delay"`. Not sure why we don't have the same logic for auto saves caused by focus change

As an alternative point of view: the current behavior is a bit confusing, in that "codeActionsOnSave" are only applied _sometimes_, without informing users that a manual save is not equivalent to an auto save, or allowing them to change that behavior.

IMO, auto saving on focus change isn't the same thing as auto saving after a short delay. A focus change is a user signifying they are done with what they're currently working on and have moved on to something else. A short delay can happen for any number of reasons, and applying code actions after every short delay could be hugely disruptive.

I'm not sure how common a linter-auto-fix-on-focus-change workflow like mine is, but I just wanted to share my 2 cents in case anyone else who's affected is searching why, and/or stumbles across this and wants to chime in. Perhaps if enough users are affected, it may be worth adding an option to change whether code actions are applied on auto-save.

**Comment by richardsimko** [comment]
@jportner I opened #123875 for this reason, however there doesn't seem to be much love for this standpoint. I personally also find it confusing that an action called `onSave` only triggers for certain types of saves and it's frustrating that there is now no longer an option for always triggering on save.
