### ISSUE TITLE
Changing the case of a file then reloading VS Code provides the old casing in the API

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#121106]
This seems similar to #102627, but I can't tell if it's intended to have been fixed or not by the last few entries on that issue.

I made a VS Code extension that just logs the open files like this:

```ts
export function activate(context: vscode.ExtensionContext) {
	context.subscriptions.push(vscode.workspace.onDidOpenTextDocument((doc) => {
		console.log(`${doc.uri.fsPath} opened!`);
		console.log(`Open files:\n${vscode.workspace.textDocuments.map((d) => `    ${d.uri.fsPath}`).join('\n')}`);
	}));
	console.log(`Open files:\n${vscode.workspace.textDocuments.map((d) => `    ${d.uri.fsPath}`).join('\n')}`);
}
```

- Opened an empty folder and created `foo.txt`.
- Renamed `foo.txt` to `Foo.txt`
- Ran the **Reload Window** command

The file is still reported as `foo.txt` despite reloading the window, and the file not being named `foo.txt` anymore:

![Screenshot 2021-04-12 at 15 32 18](https://user-images.githubusercontent.com/1078012/114411822-6ff1ee00-9ba4-11eb-84ff-3458be3be29a.png)

Even closing the file and re-opening it keeps the old casing around:

![Screenshot 2021-04-12 at 15 32 28](https://user-images.githubusercontent.com/1078012/114411836-73857500-9ba4-11eb-9a5e-60606b256472.png)

This causes issues because this path is sent to the language server, which believes this casing is correct. If the user has a lint enabled about the file casing, this causes it to trigger saying the file casing is wrong, even though they've fixed it, reloaded VS Code, and also closed and re-opened it.

I'm not sure why the old path is hanging around even after the initial rename, but certainly after the reload and close/open it seems incorrect.

**Comment by bpasero** [comment]
This is "by design", when you rename a file case we actually keep everything around, including the model because all models are stored with the canonical URI. For that purpose the workbench exposes a `preferredResource` that should be used when it comes to displaying the resource to the user:

https://github.com/microsoft/vscode/blob/5b4ee563a1de7425c511057d805069244fa14eb1/src/vs/workbench/common/editor.ts#L682-L682

I am not sure how this should be surfaced to extensions and whether it makes sense for the `TextDocument` to expose the `preferredResource` too?

**Comment by DanTup** [comment]
> when you rename a file case we actually keep everything around, including the model because all models are stored with the canonical URI

If this is for internal VS Code models, does this need to leak out to extensions? As an extension I'd expect to see the real path of a file - if the user renames the case, it should reflect that. It seems strange to mess with that for the convenience of VS Code's internal APIs.

> and whether it makes sense for the `TextDocument` to expose the preferredResource too?

I think it needs to be exposed somewhere. Extensions need to use the paths for all sorts of things, and if the user has changed the casing (and closed/opened the file, and reloaded VS Code) it looks buggy if the extension/language server continue to use the old casing.

It still feels a little weird to mess with `uri` though.. Could the "original" URI not have been the new property, or the models updated when the file is renamed? (I presume that happens if you make non-casing changes anyway?).

**Comment by bpasero** [comment]
There is no support for "renaming" a model, that is just given currently. It would always need to be disposed and recreated. We used to do that before we introduced canonical URIs.

What you propose here is not possible to accomplish: a user can have the same model opened in multiple editors with different path casing. The API provides access to the URI of the `TextDocument` (= model). It seems to me you want the casing as the editor was instructed to open and not the model casing, so that would require some new API to enumerate the opened tabs.

**Comment by DanTup** [comment]
> I also feel, that what you propose here is not possible to accomplish: a user can have the same model opened in multiple editors with different path casing. The API provides access to the URI of the `TextDocument` (= model).

Ah, got it. But in that case, why does closing/re-opening the file not fix it?

The reason I need it here is that I need to keep my language server updated with the file buffers for open files, so they have to be driven by the open editors. Telling the server "fileA.dart is open with contexts X" if the file is actually "filea.dart" leads to issues (since as far as the server knows, this is a different file to the one it sees on disk, so there are now two files).

**Comment by bpasero** [comment]
> Ah, got it. But in that case, why does closing/re-opening the file not fix it?

Canonical URIs are persisted in memory, they have no lifecycle. And they do survive even a window reload because the editor is restored exactly how it was including the original (canonical) resource and the preferred one.

**Comment by DanTup** [comment]
@bpasero so there is no solution to this? It's causing bugs and it doesn't seem like there's any way for an extension to work around it. Renaming a file changing more than the case works fine (it does not return the old name) so I don't understand why this works differently.

**Comment by bpasero** [comment]
Yes, there is currently no solution planned from VSCode. If your language service depends on file name casing but the underlying file system is case preserving but case insensitive, then I suggest to compare file paths the same way (case insensitive). We do that in many cases as well by checking for the platform being Linux (case sensitive) or Windows/macOS (case preserving, case insensitive).

**Comment by DanTup** [comment]
It sounds like I'm going to have to add a lot of fs access everywhere I read the URI of a document to ensure I get the actual case the user has renamed to. If VS Code is already doing this, why can't it expose expose it rather than each extension do it (or more likely, for many extensions to just have subtle bugs)? I'm sure it never used to work this way, this seems like a breaking change.

**Comment by MooNag** [comment]
This should not be closed. Extensions need to be able to query the live documents. There is NO reason that should not be exposed to extensions because it is what people would expect as behavior. Case sensitivity does not matter. An extension should be able to query the current document names with native case sensitivity. All this is going to do is cause bugs.

As a developer having to completely reinstall VS Code every time I change a file name to a different case otherwise my code editing extension for dart cannot know the difference between the files is frustrating to say the least. At a MINIMUM case correct file names should be exposed and the behavior documented to extension developers.

**Comment by DanTup** [comment]
I think this may also cause issues with Virtual Workspaces where the server has no idea whether the underlying filesystem should be case-sensitive or not. It seems like we'll have to treat them all as case-insensitive even though that's not accurate?

**Comment by dbaeumer** [comment]
I think we need to differentiate between a URI we use to identify a document and how we denote the document in the UI. For the identity I agree it should be kept stable as long as possible, even if the file renames. For presenting a document in the UI I think it should always use the latest name given to the document. So if a file `aaa.txt` gets renamed to `AAA.txt` an extension should be able to talk about the document as `AAA.txt` in the UI. IMO this is currently not possible and it might be confusing for a user if a notification still refers to the document as `aaa.txt` since this is still the URI used for the document.

**Comment by DanTup** [comment]
> I think we need to differentiate between a URI we use to identify a document and how we denote the document in the UI.

I think the issue goes much further than just the URI. For example, if VS Code sends the old casing to the language server, then the user invokes a fix/completion to import that file - an edit may be produced that imports the file with the "old" casing. This is very confusing to users (especially when it persists across a reload).

If extensions/servers should be treating every URI that comes from VS Code as "potentially not the casing the user expects" then I think this needs to be clearly documented with some guidelines. With LSP, the goal is to allow single servers to service multiple editors, but that's very difficult to do when cases like this are not well defined (casing has been the source of many bugs for VS Code and servers alike).

**Comment by dbaeumer** [comment]
I think a library can never expect a certain/correct casing in a case insensitive file system due to the pure fact that the whole FS world is async and no locks can be taken (e.g. a file can even be renamed outside of VS Code). So libraries have to deal with the fact that `AAA.txt` === `aaa.txt`. 

I do agree that this should be made more clear in the documentation.

**Comment by DanTup** [comment]
> I do agree that this should be made more clear in the documentation.

Could this be re-opened and used for documenting it? I'm reluctant to start extension/server changes until it's clear what the behaviour should be (including for non-file URIs where the server doesn't have access to the underlying filesystem) in case it changes again.

**Comment by DanTup** [comment]
I did some more testing of this, but VS Code seems to be treating even case-sensitive filesystems as insensitive - I've filed https://github.com/microsoft/vscode/issues/123660 with an example. I don't think language servers can account for that, so it seems like we're currently in a bit of an impossible situation unless the rule is "all filesystems should be treated insensitively").
