### ISSUE TITLE
Unbounded breakpoints when debugging Javascript

### ISSUE THREAD

**Issue by exextoc** [microsoft/vscode#121136]
- VS Code Version: 1.55
- OS Version: 20H2 (Build 19042.867)

Steps to Reproduce:

1. Attach debugger to JS code to debug an Outlook Addin.
2. Breakpoints are unbounded however call stack frames populate correctly. The stack frames pick correct function names and line numbers, but display UnknownSource next to it. You can still debug however the current line is not highlighted in view either.

![image](https://user-images.githubusercontent.com/28549921/114453802-bc323380-9b8e-11eb-88c3-ff5dff55ab2b.png)

This issue doesn't happen when rolling back to the Feb 2021 update (1.54.x).

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by exextoc** [comment]
Please find the log attached.

[vscode-debugadapter-e433416d.json.gz](https://github.com/microsoft/vscode/files/6300083/vscode-debugadapter-e433416d.json.gz)

**Comment by connor4312** [comment]
It looks like Outlook CDP implementation does not create execution contexts, so we are missing the frame of reference in which to track sources and evaluate scripts. Please open an issue on the Outlook team for this.

**Comment by akrantz** [comment]
@connor4312 This is [React Native Windows](https://github.com/microsoft/react-native-windows) using the ChakraCore javascript engine, and [ChakraCore-Debugger](https://github.com/microsoft/ChakraCore-Debugger) library which provides support for Chrome DevTools Protocol for debugging.

What was the change which allowed this to work in VS Code 1.54 but not work in version 1.55?

Could you provide more detail about the CDP message where the context is not provided?

**Comment by connor4312** [comment]
It looks like it's missing the notion of [runtime executioncontexts](https://chromedevtools.github.io/devtools-protocol/tot/Runtime/#event-executionContextCreated). I'm a little surprised the debugger worked well without them previously.

The issue in the last release is caused by https://github.com/microsoft/vscode-js-debug/commit/fb32aab6692acc385ccc707c880e7138c74b3a50. I put in a slightly less nice patch here in https://github.com/microsoft/vscode-js-debug/commit/e30f2580fb27e8fb2d45b8585dd6d8379c72c17a, which'll be in the next [nightly build](https://github.com/microsoft/vscode-js-debug#nightly-extension) and the VS Code release next month.
