### ISSUE TITLE
Pressing `esc` with a notebook cell in command mode should preserve current cell selection

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#121129]
- VS Code Version: Version: 1.56.0-insider (user setup)
- OS Version: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Create a new notebook
2. Add a cell
3. Put it into command mode (cursor should not be visible in the editor)
4. Press escape key. Focus moves from the selected cell to the entire document
5. Executing Notebook: Insert Code Cell Above causes cells to be inserted at the top of the document instead of above the selected cell

More info: A Jupyter extension user complained about this because they often press `esc` more than once and the current behavior causes them to lose their active notebook cell context. Classic Jupyter preserves the current cell in command mode even when the escape key is repeatedly pressed.

_Originally reported in https://github.com/microsoft/vscode-jupyter/issues/5483_

Does this issue occur when all extensions are disabled?: Yes

**Comment by rebornix** [comment]
@joaomoreno is this something we ever consider in the general list view? cc File Explorer and A11y owner @isidorn

**Comment by isidorn** [comment]
The `esc` to focus out to parent is a generally loved feature by the a11y community. I like that Notebooks are consistent with what we do in the rest of VS Code. IMHO I would not change anything here atm

**Comment by claudiaregio** [comment]
+1 
![image](https://user-images.githubusercontent.com/19276747/124711141-8f05d080-deb2-11eb-81d8-d4ddaec540e8.png)

**Comment by sfo** [comment]
A workaround could be to redefine the `Escape` Keybinding for Command `Notebook: Stop Editing Cell` to ignore the `inputFocus` condition. This way, even if already in Control mode, pressing `Escape`  goes to Control mode again instead of focusing to parent.

So far this works for me, I did not encounter any side effects, yet.

I added this to my `keybindings.json`:
```
{
    "key": "escape",
    "command": "notebook.cell.quitEdit",
    "when": "notebookEditorFocused && !editorHasMultipleSelections && !editorHasSelection && !editorHoverVisible"
}
```

**Comment by kretes** [comment]
For me it started to be a blocker for further using vs code notebooks instead of standalone jupyter.
My intuition is that this should work the same as in standard jupyter, as this is what people are used to.

@sfo keybinding works well, thanks!
I've actually fixed that to be even more compatible with jupyter mode, by removing `!editorHasMultipleSelections && !editorHasSelection` from the condition. In standard jupyter you can have selection, but hiting `escape` exits edit mode, and this was another thing that I bumped in VS, as here I needed to hit `escape` more times.

**Comment by isidorn** [comment]
On the other hand I see how we should maybe behave like we do in the editor -> if there are multiple editor groups pressing Esc would still keep focus in the editor.

So after giving it some more thought I think this request makes good sense.
And we can introduce a keybinding chord of `esc esc` that would move focus out of the notebook editor

**Comment by thomasaarholt** [comment]
Could the keybinding that @sfo suggested be used as inspiration for a fix for this? What would be a negative consequence of that keybinding becoming default in notebooks?

**Comment by lancelotzty** [comment]
> 

this would disable the escape function for exit the hover windows, i.e. command + f

**Comment by carbocation** [comment]
I am commenting in this issue only because I was going to file this as a new problem until I discovered this thread. I think it's a big enough blocker to using Notebooks in VS Code that it's worth formalizing this as an option - possibly even the default for notebooks.
