### ISSUE TITLE
gutterIconPath is not loading correctly in Insider release

### ISSUE THREAD

**Issue by alefragnani** [Microsoft/vscode#12111]
- VSCode Version: 1.6.0 Insider
- OS Version: Windows 10

Steps to Reproduce:

1. Define a `pathIcon` variable using `context.asAbsolutePath('images\\bookmark.png')` 
```typescript
let pathIcon: string = context.asAbsolutePath('images\\bookmark.png');
```
2. Create a decorator and use the `pathIcon` variable as `gutterIconPath`.
```typescript
let bookmarkDecorationType = vscode.window.createTextEditorDecorationType({
        gutterIconPath: pathIcon,
        overviewRulerLane: vscode.OverviewRulerLane.Full,
        overviewRulerColor: 'rgba(21, 126, 251, 0.7)'
    });
```
3. The image will not be loaded, and it will output an error in `Developer Tools` console
```
GET file:///C:/%5CUsers%5Calefr%5C.vscode-insiders%5Cextensions%5Calefragnani.Bookmarks-0.9.1%5Cimages%5Cbookmark.png net::ERR_FILE_NOT_FOUND
```

Unfortunattely, I'm also not able to debug in Insider release ([this issue](https://github.com/Microsoft/vscode/issues/12078)). Maybe something in `gutterIconPath` or `Uri` has changed and now the file is not being located?

Thanks in advance

**Comment by ArtemGovorov** [comment]
We have hit the exact same issue. Works ok on OSX.
The workaround we use for now in our extension is replacing backslashes with slashes:
```javascript
gutterIconPath: pathIcon.split('\\').join('/'),
```
What's interesting is that the resource URIs didn't seem to change, so perhaps it's moving the newer electron/v8 had broken it and URIs with encoded slashes don't work anymore.

**Comment by alefragnani** [comment]
Hi @ArtemGovorov , that was my first attempt, with no success 😢 . Good to know that at least it fixes for OS X (and probably Linux). Thanks 👍 

`Uri.ts` had some changes last month, but since I don't have a _debugabble source of VS Code` available, I can't check where is the problem. 

I hope it to be fixed soon, or at least new tips for adapting to any new API.

**Comment by ArtemGovorov** [comment]
>  that was my first attempt, with no success 😢 . Good to know that at least it fixes for OS X (and probably Linux). 

That's not what I meant. I mean the original issue doesn't affect OS X at all.

And the workaround that I suggested (`gutterIconPath: pathIcon.split('\\').join('/'),`) fixed it for us for all platforms, including Windows. Perhaps your case is different from ours if it doesn't work for you.

Also, as I said, the URI generation in our case didn't change, so I doubt it is the `Uri` issue. You may check it in your extension in Dev Tools:

<img width="753" alt="screen shot 2016-09-17 at 12 06 30 pm" src="https://cloud.githubusercontent.com/assets/979966/18612069/a3c4f82e-7d92-11e6-990d-c78660b351a9.png">

In our case the icon URI on Windows in both cases (working in 1.5.2 and non-working in 1.6.0) is the same.

**Comment by alefragnani** [comment]
Ops, I _read_ you tip but didn't _see_ your tip 😞 . 

I replaced `\\` by `/` in the code below, and id didn't work: 

```typescript
let pathIcon: string = context.asAbsolutePath('images\\bookmark.png');
// replaced by
let pathIcon: string = context.asAbsolutePath('images/bookmark.png');
```

BUT, updating the code _as you suggested_, really worked!!! The difference? Your tip replaced the backslashes _from the entire path_, and not only _the added piece_. So, I have to add this line, right after that:

```typescript
pathIcon = pathIcon.replace(/\\/g, "/");
``` 

Something related to _path separator_  has changed internally (Uri, Decorator, I don't know), and now it's forced to use `/`, even `context` returning `\\`. 

Thanks again 👍

**Comment by alexandrudima** [comment]
I believe the new electron version drags in a new node version where something changed with casing drive letters. We are seeing issues regarding this change everywhere.

fyi @jrieken @bpasero @joaomoreno -- I'm not sure where we ended up with a systematic workaround the drive letter casing change?

This used to work fine before the new electron version:

```
let pathIcon: string = context.asAbsolutePath('images\\bookmark.png');

let bookmarkDecorationType = vscode.window.createTextEditorDecorationType({
     gutterIconPath: pathIcon
});
```

On the main side I do:
```
cssTextArr.push(strings.format('background:url(\'{0}\') center center no-repeat;', URI.parse(opts.gutterIconPath).toString()));
```

**Comment by bpasero** [comment]
@alexandrudima @jrieken Joao pushed https://github.com/Microsoft/vscode/commit/dcc36a8f02acd503dcd03f89583b31f9e170dfbb so that `paths.relative` ignores the casing of paths in the same way `isEqualOrParent` does. Bottom line is that the drive letter on Windows can now be either upper case or lower case depending on if the process was started (or forked) with an upper case cwd or lowercase.

**Comment by jrieken** [comment]
@bpasero Unsure how https://github.com/Microsoft/vscode/issues/12111#issuecomment-248237521 relates to this. 

@alexandrudima Since we sit in the extension host we should maybe adopt the actual nodejs `path` module instead of our homegrown. Also I wonder about this

> cssTextArr.push(strings.format('background:url(\'{0}\') center center no-repeat;', URI.parse(opts.gutterIconPath).toString()));

If `gutterIconPath` isn't an actual uri but a file path (as returned by `context.asAbsolutePath`) I am not so sure that's the right thing to do.

**Comment by bpasero** [comment]
@jrieken it relates to @alexandrudima question:

> I'm not sure where we ended up with a systematic workaround the drive letter casing change?

**Comment by jrieken** [comment]
Unsure if that should be handled by relative at all. From my pain with `join` I have learnt the drive letter is part of the *path root* and I don't think nodejs touches those. Having said that we should try to use the natives whenever possible

**Comment by jrieken** [comment]
@bpasero This is not about lower-case but about the fact that you should not compare `C:` with `c:` because that's not part of the path. The *reference* does [this](https://github.com/nodejs/node/blob/master/lib/path.js#L571) which I believe is starting after the first `\` in a path like `c:\foo\bar`

**Comment by alefragnani** [comment]
I'm curious, but the path itself, mixing `/` and `\` is ok? I mean, as you can see, the path displayed in the _error message_ is `file:///C:/\Users\alefr...`. Or is the _combination_ `/\` itself?

And if I use any other _case_ in the filename, like `bookmark.PNG`, it does not present any problem (at least in Windows).

```
GET file:///C:/%5CUsers%5Calefr%5C.vscode-insiders%5Cextensions%5Calefragnani.Bookmarks-0.9.2%5Cimages%5Cbookmark.png net::ERR_FILE_NOT_FOUND
```

Thanks in advance

**Comment by bpasero** [comment]
Fyi we investigate to update electron which comes with the original fs.realpath impl.

**Comment by jrieken** [comment]
This is actually unrelated to the infamous realpath challenge but it boils down to a regression from #6553 which only shows with the version of chromium we have adopted lately. 

Because we use `Uri.parse` instead of `Uri.file` we at the end create a css-rule like so (`%5C` is an escaped backspace)

```css
.monaco-editor.vs-dark .ced-TextEditorDecorationType1-2 {
    background: url("c:%5CUsers%5Cjrieken%5Ccode%5Cvscode-bookmarks%5Cimages%5Cbookmark.png") 50% 50% no-repeat;
}
```

With chrome 49 that didn't seems to be a problem whereas chrome 52 isn't that relaxed anymore (which makes sense to me):

![screen shot 2016-09-27 at 15 37 01](https://cloud.githubusercontent.com/assets/1794099/18876117/bd485a2e-84c8-11e6-9fba-5e5eb60537fe.png)

![screen shot 2016-09-27 at 15 37 39](https://cloud.githubusercontent.com/assets/1794099/18876161/e3874a9c-84c8-11e6-8326-e467d4a6149a.png)

**Comment by jrieken** [comment]
I plan to make the following changes:

* `ThemableDecorationRenderOptions#gutterIconPath` and `ThemableDecorationAttachmentRenderOptions#contentIconPath` with become of type `string | Uri`
* string values are being interpreted via `Uri#file` - this will break @kisstkondoros extensions
* Uri values are being interpreted as is - this will enable @kisstkondoros to fix his extension

@alexandrudima @kisstkondoros objections?

**Comment by alexandrudima** [comment]
@jrieken 👍

**Comment by kisstkondoros** [comment]
👍

**Comment by alexandrudima** [comment]
@jrieken Thanks for following through with this one, I will unassign myself for now

**Comment by jrieken** [comment]
@bpasero btw - This is an `electron-update` issue

**Comment by bpasero** [comment]
@jrieken ah yeah sorry, will add the label back 👍
