### ISSUE TITLE
'Do you trust files in this folder' dialog should be provide more context.

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#121183]
The Java extension has adopted the trust model for the Maven extension. The extension has `requiresTrust` set to `onDemand`, it will allow user to see the tasks in the pom file, but as soon as the user tries to run a task then the requires trust dialog is shown. 

In the screenshot below the user clicked the 'run' inline action for the 'clean' task:

![image](https://user-images.githubusercontent.com/172399/114566502-a302b300-9c72-11eb-927a-dfb4a5fb9c7a.png)

The dialog that is then shown lacks context on why it is shown and I was surprised. Suggestions:

- In the dialog title, repeat that the context is an 'untrusted workspace', for example 'Untrusted Workspace - Do you trust the files and folders?
- The 1st paragraph in the dialog is vague and talks about 'A feature you are trying to use', make this more specific and allow an extension to say what the feature is, e.g., 'You are running "a maven task". This may be a security risk if you do not trust the sources of the files you have currently open'

**Comment by lszomoru** [comment]
> In the dialog title, repeat that the context is an 'untrusted workspace', for example 'Untrusted Workspace - Do you trust the files and folders?

Makes sense. I would like to take this even further and add some "branding" (ex: add the `shield` icon, etc.) to all the dialogs that are related to the workspace trust feature. As a first step, we should be switching these dialogs to use the custom dialog instead of the native ones in order to be able to provide a more rich experience.

> The 1st paragraph in the dialog is vague and talks about 'A feature you are trying to use', make this more specific and allow an extension to say what the feature is, e.g., 'You are running "a maven task". This may be a security risk if you do not trust the sources of the files you have currently open'

The messaging in the dialog is something that we have been thinking a lot. The challenge that we are facing is that we need to provide context to the user about the action that resulted in the dialog to be shown, yet explain that the decision that is being made is not limited to the action only but it has a larger impact. We will continue to iterate on this.

**Comment by lszomoru** [comment]
As discussed offline we will do two things to try to address this:
1. Enable extension authors to provide an optional message describing the action.
2. Author a better `default message` that focuses on the action being performed

**Comment by egamma** [comment]
closing/obsolete
