### ISSUE TITLE
Terminal turns black and crashes VSCode after long tern using(reposted)

### ISSUE THREAD

**Issue by sspleo** [microsoft/vscode#121244]
This happens to me as well. In my case, @Tyriar 's solution does not help.
The only way that I can make the windows to show up again is open a new terminal.

Version : VS Code 1.54.3
OS : Linux x64 5.4.0-65-generic

![Screenshot from 2021-04-14 09-13-40](https://user-images.githubusercontent.com/17273719/114636350-bad54800-9d01-11eb-917c-b0475d871a42.png)

The black issue is fixed in Insiders, as for the weird viewport problem that's https://github.com/Microsoft/vscode/issues/57803

_Originally posted by @Tyriar in https://github.com/microsoft/vscode/issues/65958#issuecomment-451981428_

**Comment by antialize** [comment]
I am seeing the same issue. 
![image](https://user-images.githubusercontent.com/84282/120979452-ea3e8900-c775-11eb-94fb-e3e9a6eef753.png)

Version: 1.56.2
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T16:45:26.313Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Linux x64 5.4.0-66-generic

**Comment by Tyriar** [comment]
Does this only happen when a terminal is reconnected or only on the first terminal created? Does setting `terminal.integrated.gpuAcceleration` to false fix it?

**Comment by antialize** [comment]
It happens when vs code has been running for some time, not when the terminal is first created. It happens to all vscode windows at the same time. I can still type into the terminals, and the white box moves, but no text appears. I have tried to disable GPU acceleration, i will report back if it still fails.

My graphics are 
00:02.0 VGA compatible controller: Intel Corporation HD Graphics 530 (rev 06)
the driver is i915 from 5.4.0-66.
The mesa version is OpenGL version string: 4.6 (Compatibility Profile) Mesa 20.2.6
X.Org version: 1.20.9
Everything is running on an up to date Ubuntu 20.04.2 LTS

**Comment by Tyriar** [comment]
@meganrogge maybe a problem with webgl context loss?

<img width="683" alt="Screen Shot 2021-06-08 at 4 59 27 AM" src="https://user-images.githubusercontent.com/2193314/121181064-743e2e80-c816-11eb-9666-e783ea5a19fb.png">
<img width="447" alt="Screen Shot 2021-06-08 at 4 59 29 AM" src="https://user-images.githubusercontent.com/2193314/121181075-76a08880-c816-11eb-83e5-043f3ad2503d.png">

**Comment by meganrogge** [comment]
@Tyriar did you see `Webgl could not be loaded. Falling back to the canvas renderer type.` as a warning?

**Comment by sspleo** [comment]
> Does this only happen when a terminal is reconnected or only on the first terminal created? Does setting `terminal.integrated.gpuAcceleration` to false fix it?

After setting 'terminal.integrated.gpuAcceleration' as 'Off', all terminals show up again. It's like miracle. Thank you.
