### ISSUE TITLE
Code refactor not working in Mac M1

### ISSUE THREAD

**Issue by ngohungphuc** [microsoft/vscode#121387]
- VS Code Version: 1.55
- OS Version: Mac

Steps to Reproduce:

1. Click on the name you want to refactor
2. Press F2 then type the name

<img width="764" alt="Bildschirmfoto 2021-04-15 um 19 54 44" src="https://user-images.githubusercontent.com/13591213/114872593-afc70880-9e24-11eb-8127-f334cf4e3100.png">

3. Enter the name is not apply but instead it add the new line

<img width="482" alt="Bildschirmfoto 2021-04-15 um 19 56 01" src="https://user-images.githubusercontent.com/13591213/114872618-b35a8f80-9e24-11eb-9ed2-cecf70bbcc8c.png">

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Have you configured a custom keybinding for `enter`?

**Comment by ngohungphuc** [comment]
@mjbvz no it's work fine on my Window machine but in Mac it's not.

**Comment by jrieken** [comment]
Please do the following: select "F1 > Set Log level > Trace" and then "F1 > Show Logs > Window". Then try to rename again and share the logs of around the time you tried to rename

**Comment by ngohungphuc** [comment]
@jrieken Sure. Will do that when I get home. Thank you

**Comment by jrieken** [comment]
Maybe the issue is caused by one of your installed extensions. All extensions execute together on a single nodejs process, so in order to narrow down the possible problematic extension, please try the following:
* run `F1 > Help: Start Extension Bisect`
* (this will restart VS Code with half of your extensions disabled)
* try to do the steps which reproduce the problem
* if the problem reproduces, click "This is bad" (this narrows down the problematic extension to the half which was enabled)
* if the problem does not reproduce, click "Good now" (this narrows down the problematic extension to the half which was disabled)
* these steps will repeat until the problematic extension is found

| initial | step | final |
|---|---|---|
| ![image](https://user-images.githubusercontent.com/5047891/101918658-e9170f80-3bc9-11eb-9977-857baa291937.png) | ![image](https://user-images.githubusercontent.com/5047891/101918683-ef0cf080-3bc9-11eb-9f9e-98b0177991b2.png) | ![image](https://user-images.githubusercontent.com/5047891/101918706-f502d180-3bc9-11eb-8c86-e56355958bd4.png) |

**Comment by ngohungphuc** [comment]
@jrieken Thanks you I will try it

**Comment by ngohungphuc** [comment]
@jrieken Tried it and I only get this 
```
The bisection of extensions has been completed, but no extension has been identified. Possible cause of the problem: code.
```

**Comment by ngohungphuc** [comment]
Any update on this ?

**Comment by jrieken** [comment]
No update. I can still not reproduce. Can you try this with [VS Code Insiders](https://code.visualstudio.com/insiders/)?
