### ISSUE TITLE
extension host crash

### ISSUE THREAD

**Issue by kerolosemad** [microsoft/vscode#121360]
We have written th
Issue Type: <b>Bug</b>

from two updates vscode become less stable, the most annoying thing is extension host needs to restart, and if my extensions conflicting we need a tool to show that and warn us

tell me if you more information my major use (that cause crashing) is python

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:35:57.887Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.87GB (1.98GB free)|
|Process Argv|I:\\programming_projects\\AYEN\\monday mission --crash-reporter-id a388a017-b415-449e-b6dc-5f2bb6b98069|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (55)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
vscode-color|ans|0.4.5
vsc-export|asl|1.2.0
vscode-django|bat|1.6.0
django-html|bib|1.3.0
django|big|1.0.2
vscode-importmagic|bra|0.2.5
simple-react-snippets|bur|1.2.3
path-intellisense|chr|2.3.0
bracket-pair-colorizer-2|Coe|0.2.0
vscode-svgviewer|css|2.0.0
jshint|dba|0.11.0
vscode-eslint|dba|2.1.20
githistory|don|0.6.16
jquerysnippets|don|0.0.1
python-extension-pack|don|1.6.0
es7-react-js-snippets|dsz|3.1.1
vscode-babel-coloring|dza|0.0.4
vscode-html-css|ecm|1.10.2
prettier-vscode|esb|6.3.2
auto-close-tag|for|0.5.10
auto-rename-tag|for|0.1.6
vscode-google-translate|fun|1.4.13
todo-tree|Gru|0.0.211
beautify|Hoo|1.5.0
google-search|kam|0.0.1
vsc-python-indent|Kev|1.14.0
MagicPython|mag|1.1.0
vscode-language-babel|mgm|0.0.31
git-graph|mhu|1.30.0
vscode-docker|ms-|1.12.1
anaconda-extension-pack|ms-|1.0.1
python|ms-|2021.5.746022950-dev
vscode-pylance|ms-|2021.4.1
jupyter|ms-|2021.5.745244803
remote-containers|ms-|0.166.1
remote-wsl|ms-|0.54.6
debugger-for-chrome|msj|4.12.12
autodocstring|njp|0.5.4
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
jinjahtml|sam|0.16.0
django-intellisense|sha|0.0.2
autoimport|ste|1.5.3
code-spell-checker|str|1.10.2
ayu|tea|0.20.1
open-in-browser|tec|2.0.0
vscode-djaneiro|the|1.4.2
python|tht|0.2.3
bracket-padder|via|0.3.0
vscodeintellicode|Vis|1.2.12
vscode-icons|vsc|11.4.0
jinja|who|0.0.8
eno|Wsc|2.3.53
JavaScriptSnippets|xab|1.8.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvsnew554:30281908
pythontb:30283811
openwsldoc:30282072
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30276952
pythondataviewer:30285071
vscus158cf:30286554

```

</details>

e needed data into your clipboard because it was too large to send. Please paste.

**Comment by alexdima** [comment]
It looks like the issue is caused by one of your installed extensions. All extensions execute together on a single nodejs process, so in order to narrow down the possible problematic extension, please try the following:
* run `F1 > Help: Start Extension Bisect`
* (this will restart VS Code with half of your extensions disabled)
* try to do the steps which reproduce the problem
* if the problem reproduces, click "This is bad" (this narrows down the problematic extension to the half which was enabled)
* if the problem does not reproduce, click "Good now" (this narrows down the problematic extension to the half which was disabled)
* these steps will repeat until the problematic extension is found

| initial | step | final |
|---|---|---|
| ![image](https://user-images.githubusercontent.com/5047891/101918658-e9170f80-3bc9-11eb-9977-857baa291937.png) | ![image](https://user-images.githubusercontent.com/5047891/101918683-ef0cf080-3bc9-11eb-9f9e-98b0177991b2.png) | ![image](https://user-images.githubusercontent.com/5047891/101918706-f502d180-3bc9-11eb-8c86-e56355958bd4.png) |
