### ISSUE TITLE
Add letterIsCodicon to DecorationData

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#121483]
Add `letterIsCodicon?: boolean` to this

https://github.com/microsoft/vscode/blob/77d2469a5004df7f4a9c3f15ff00046c49defdc7/src/vs/workbench/services/decorations/browser/decorations.ts#L15-L21

And create a PR for Jo

so that in here

https://github.com/microsoft/vscode/blob/38a200c746b3953b741a272986bbb6f4018f90ac/src/vs/workbench/services/decorations/browser/decorationsService.ts#L67-L75

`font-family: codicon; ` can be added so codicons show up for the terminal status icons

**Comment by Tyriar** [comment]
Maybe even better: `letter?: string | Codicon`

**Comment by eamodio** [comment]
I think it should be `letter?: string | ThemeIcon` as `ThemeIcon` is already out class for accepting codicons.

**Comment by Tyriar** [comment]
@jrieken any opinions here on `ThemeIcon` vs `Codicon`? `ThemeIcon` seems to just have a color which is already in `IDecorationData`. Also let us know if we're doing something wrong, decorations didn't seem to have the capability to use an arbitrary codicon.

**Comment by jrieken** [comment]
> Also let us know if we're doing something wrong, decorations didn't seem to have the capability to use an arbitrary codicon.

Yeah, I was wrong in thinking this already works. The roll-up dot uses a codicon that there is a [special-case for that](https://github.com/microsoft/vscode/blob/38a200c746b3953b741a272986bbb6f4018f90ac/src/vs/workbench/services/decorations/browser/decorationsService.ts#L92)

>  any opinions here on ThemeIcon vs Codicon?

Yeah, I think it should be `string | ThemeIcon` but we should ignore the colour because that would conflict with the overall color
