### ISSUE TITLE
Can no longer git pull existing repository in devcontainer from Azure DevOps Repos

### ISSUE THREAD

**Issue by mauve** [microsoft/vscode#121420]
- VS Code Version: 1.55.2
- OS Version: Win10 21359 (Insider Preview) / WSL2 / devcontainer

Steps to Reproduce:

1. open windows terminal
2. enter WSL2 ubuntu 20.04 dist
3. open existing repository with devcontainer.json
4. reopen in devcontainer
5. open terminal
6. git pull

```
08:54:49 root@611b0f84fa45 backend ±|master|→ git push
fatal: Cannot determine the organization name for this 'dev.azure.com' remote URL. Ensure the `credential.useHttpPath` configuration value is set, or set the organization name as the user in the remote URL '{org}@dev.azure.com'.
fatal: Cannot determine the organization name for this 'dev.azure.com' remote URL. Ensure the `credential.useHttpPath` configuration value is set, or set the organization name as the user in the remote URL '{org}@dev.azure.com'.
fatal: Authentication failed for 'https://dev.azure.com/<ORG>/<PROJ>/_git/<REPO>/'
```

however the remote contains the organization:

```
09:00:48 root@611b0f84fa45 backend ±|master|→ git remote -v
origin  https://<ORG>@dev.azure.com/<ORG>/<PROJ>/_git/<REPO>(fetch)
origin  https://<ORG>@dev.azure.com/<ORG>/<PROJ>/_git/<REPO>(push)
```

Editing `/etc/gitconfig` and adding the setting `credential.useHttpPath = true` fixes it.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by skyline9002** [comment]
Hi community, 

I have the similar problem here, I thought initially the git working in devcontainer, however now the devcontainer side always ask me to input some credential and cannot doing anything with remote repository. I only can do it in windows system side. BTW, how you edit /etc/gitconfig, it's showing no permission to do that

**Comment by mauve** [comment]
@skyline9002 I am root in my devcontainer, but you should be able to add the setting to any gitconfig, e.g. `$HOME/.gitconfig`, or `$REPO/.git/config` should also work

**Comment by ThomasPiskol** [comment]
I face a similar issue. Neither fetch, pull or push is working with an Azure DevOps repository inside a VS Code development container. Outside the container everything is working as expected.

**1. `git fetch`**
A HTTPS request is made to `https://dev.azure.com/<org>`
After enabling `GIT_CURL_VERBOSE=1`,  I can see that this request fails with status code **401** and this error message:

```
< x-tfs-soapexception: %3C%3Fxml%20version%3D%221.0%22%20encoding%3D%22utf-8%22%3F%3E%3Csoap%3AEnvelope%20xmlns%3Asoap%3D%22http%3A%2F%2Fwww.w3.org%2F2003%2F05%2Fsoap-envelope%22%3E%3Csoap%3ABody%3E%3Csoap%3AFault%3E%3Csoap%3ACode%3E%3Csoap%3AValue%3Esoap%3AReceiver%3C%2Fsoap%3AValue%3E%3Csoap%3ASubcode%3E%3Csoap%3AValue%3EUnauthorizedRequestException%3C%2Fsoap%3AValue%3E%3C%2Fsoap%3ASubcode%3E%3C%2Fsoap%3ACode%3E%3Csoap%3AReason%3E%3Csoap%3AText%20xml%3Alang%3D%22en%22%3ETF400813%3A%20The%20user%20%27%27%20is%20not%20authorized%20to%20access%20this%20resource.%3C%2Fsoap%3AText%3E%3C%2Fsoap%3AReason%3E%3C%2Fsoap%3AFault%3E%3C%2Fsoap%3ABody%3E%3C%2Fsoap%3AEnvelope%3E
< x-tfs-serviceerror: TF400813%3A%20The%20user%20%27%27%20is%20not%20authorized%20to%20access%20this%20resource.
```

The `x-tfs-soapexception` in a more human-readable form (URL decoded):
```xml
<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope">
    <soap:Body>
        <soap:Fault>
            <soap:Code>
                <soap:Value>soap:Receiver</soap:Value>
                <soap:Subcode>
                    <soap:Value>UnauthorizedRequestException</soap:Value>
                </soap:Subcode>
            </soap:Code>
            <soap:Reason>
                <soap:Text xml:lang="en">TF400813: The user '' is not authorized to access this resource.</soap:Text>
            </soap:Reason>
        </soap:Fault>
    </soap:Body>
</soap:Envelope>
```

**2. Then VS Code brings up this message box:**
![image](https://user-images.githubusercontent.com/38790465/124506589-42e06080-ddcc-11eb-98be-74989594aadf.png)

and tries to do a basic authentication. But this won't work, because [Azure DevOps doesn't support this anymore](https://docs.microsoft.com/en-us/azure/devops/repos/git/auth-overview?view=azure-devops).

Enabling `credential.useHttpPath = true` doesn't work for me.

It seems strange, that there's no pop-up of the Git Credential Manager.


My system:
Windows 10 20H2 Enterprise
VS Code 1.57.1
Docker using WSL2 for Linux Container
Dev-Container: [typescript-node](https://github.com/microsoft/vscode-dev-containers/tree/main/containers/typescript-node)
Git version on Windows Host: `2.32.0.windows.1`
Git version inside dev-container: `2.20.1`

**Comment by AHaryanto** [comment]
Solution that worked for me:

1. Open Command Prompt
2. Run `git config --global credential.useHttpPath true` (the `--global` parameter is optional)

[Git-Credential-Manager-for-Windows docs](http://microsoft.github.io/Git-Credential-Manager-for-Windows/Docs/Configuration.html)
![useHttpPath](https://user-images.githubusercontent.com/41604701/145130064-4d8b8659-5705-4723-aa22-838bc1d7cccb.png)

**Comment by shadowano** [comment]
Running `git config credential.useHttpPath true` solved it for me as well

**Comment by lszomoru** [comment]
@mauve, is this issue still relevant? I am seeing that most people resolved the issue by setting `git config credential.useHttpPath true`.

**Comment by mauve** [comment]
No, feel free to close.
