### ISSUE TITLE
Notebook: read-only mode

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#121447]
Notebooks are incredibly powerful. Even more so as a presentational tool. When consuming them or using them as a presentational tool, the user doesn't need to create cells, go into input mode, etc. This hits me often: I get overwhelmed by the amount of hover UI and buttons to click when I'm simply browsing a notebook. I also fear modifying it to the point of no return. This makes me anxious to use a notebook, I think I might not be alone in this camp.

Also, I find that I'm more often consuming a notebook rather than editing it, after the initial creation. Take our GH Issues notebooks as a clear example.

We should have a mode that removes all the noise from a notebook editor so the user can consume it without anxiety. IMO this should even be the default mode in which a notebook editor always opens and there should also be a very clear UI piece that allows the user to toggle _edit_ mode, promoting the editor into today's experience.

cc @misolori @jrieken for thoughts

**Comment by jrieken** [comment]
> I also fear modifying it to the point of no return. This makes me anxious to use a notebook, I think I might not be alone in this camp.

I can relate to that but by now we have more features to help: undo/redo and a notebook diff editor. Nevertheless, you are right and that's the reason we had (removed yesterday) various locking mechanisms. This is what we have and why we removed it

* set a _notebook_ to non-editable -> cannot delete/add/rearrange cells via UI gestures
* set a _cell_ to non-editable -> cannot type in its code editor

We didn't like that too much because the split was somewhat arbitrary and extensions had to enable this. We are more in favour of a simple, central "read/view-mode" that applies the while editor, not just some cells. The question is just what it should do?

* ❔ prevent cells deletion/addition/moving - probably yes
* ❔ prevent typing in cells - probably yes
* ❔ prevent execution - maybe no, e.g GitHub issue notebooks would all be empty otherwise...

**Comment by rebornix** [comment]
> We are more in favour of a simple, central "read/view-mode" that applies the while editor, not just some cells

I think what @joaomoreno described above is close to "read/view-mode". I'm wondering though if this is something controlled by the content provider, or more or less an UI feature. But either way, having a single setting/option/metadata to control the whole editor would be less confusing to understand.

> prevent execution - maybe no, e.g GitHub issue notebooks would all be empty otherwise

"no" IMO too. What I'm not sure about is if you want "outputs" to be transient when the document is in View Mode. GH Notebook might not be a good case, but say Kusto notebook, I want to open a Kusto notebook in view mode but I don't ever want to make the document dirty when I run cells.

**Comment by joaomoreno** [comment]
I would simply prevent structural changes to the notebook: creating, deleting, moving cells, etc. I would further prevent toggling cells between view and edit mode (should not be possible to edit a Markdown cell). I would still allow editing code cells, executing them and clearing their output. That's the mode I'l love to have.

**Comment by misolori** [comment]
Here's a simple idea taking inspiration from the browser "reader mode":

## Safari
![image](https://user-images.githubusercontent.com/35271042/116581040-cb242000-a8c8-11eb-8b49-d033d9895dbf.png)
![image](https://user-images.githubusercontent.com/35271042/116581074-d2e3c480-a8c8-11eb-8b8a-7a42d89394b6.png)

## Notebook
![Kapture 2021-04-28 at 12 48 24](https://user-images.githubusercontent.com/35271042/116581180-ebec7580-a8c8-11eb-866b-5483e9fb559a.gif)

**Comment by rebornix** [comment]
<img width="933" alt="Image" src="https://github.com/user-attachments/assets/0ebc43e0-316a-47cb-8165-2f61f4872f0c" />

Toggle Active Editor Readonly in Session already offers a very close experience.
