### ISSUE TITLE
Feature fequest for applying CSS styles in console.log

### ISSUE THREAD

**Issue by GeekLad** [Microsoft/vscode#12150]
**Feature Request**

Chrome and Firefox both support applying CSS styles to console output.  For example, you can do something like `console.log("%cThis text should be green", "color: green");` and in Chrome and Firefox you get "_This text should be green_" in green text.

In the VSC console log you get "_color: greenThis text should be green_" and the output is styled the same as any other console.log output.  VSC should apply CSS styles to console.log in the same way as Chrome and Firefox.

**Comment by rozzzly** [comment]
I've been working on a vscode extension and have actually resorted to using the chrome developer console in the instance of vscode I'm debugging to view console output/inspect some object/read stacktraces because the vscode side of is a bit rough around the edges (every log messages gets a jumble of css Infront of it.)

Would also be cool for js objects if vscode could display some of the content when the object is collapsed, like a truncated preview. To see what I mean open your devtools and make some object literal with a lot of keys then try expanding/collapsing it.
