### ISSUE TITLE
SCM input has unclickable areas

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#121543]
When hovering over them cursor changes to `pointer` and clicking doesn't activate the input.

![Screenshot (478)](https://user-images.githubusercontent.com/9638156/115107253-5ff65780-9f72-11eb-905e-7810ffc0e6e7.png)

VS Code version: Code - Insiders 1.56.0-insider (ce791d27dc9889a392f4d29abefe9c53eb0b5129, 2021-04-16T11:25:09.662Z)
OS version: Windows_NT x64 10.0.18363

**Comment by lszomoru** [comment]
@usernamehw, apologies for not getting back to you on this until now. Using the latest version of VS Code, clicking on the red area on the right edge of the input field will focus the input field. The area on the left hand side is by design as it represents the left-hand margin of the editor (this is actually a Monaco editor and not a plain input filed). Also note that clicking anywhere outside the editor on the row will focus the input field.

In case you have any further questions or concerns please feel free to reopen the issue. Thanks!
