### ISSUE TITLE
Color appended to preview html not properly theme dependent

### ISSUE THREAD

**Issue by anthonydresser** [Microsoft/vscode#12164]
- VSCode Version: 1.5.1
- OS Version: OSX 10.11.6

The styles appended to the preview html by vscode properly capture the background color of the current theme, but seem to be a constant rbg(204, 204, 204) for dark theme or rbg(108, 108, 108) for light theme for the color style option rather than using what the current theme has set.

The most obvious example is using the "Monokai" theme. The default text color (using file type of Plain Text) has the value rgb(248, 248, 242). However, vscode still appends the style rbg(204, 204, 204) to the html.

Is this intended? It would be nice if VSCode appended the proper color so that the preview html can look as much as part of VSCode as a text editor.

Steps to Reproduce:
1. Open any preview html with a variety of themes

**Comment by jrieken** [comment]
We use the editor-background [element](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/html/browser/htmlPreviewPart.ts#L80) and retrieve its [styles](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/html/browser/webview.ts#L137). Whatever is used there is what we use in the web view and I believe that's reasonable. 

@anthonydresser What is the bug here? Are the background colors different? Should they be different?

**Comment by anthonydresser** [comment]
I was referring to specifically text-color (the "color" css attribute). The background-color works great. It appends the exact color that the color theme is currently using. However, the text-color seems to be just vscode-dark (rgb(204,204,204) or vscode-light (rgb(108,108,108)) where as I would expect it to be the exact color of the Plain Text color in the editor.

**Comment by jrieken** [comment]
Thanks - understood. I'll see if I can find a different element to probe for colors

**Comment by anthonydresser** [comment]
I just noticed that fontweight, fontsize, and fontfamily all have the same problem. Most likely a related problem I imagine.

**Comment by mjbvz** [comment]
We should now set the `:root { color: ... }` to `editorForeground` from the active theme
