### ISSUE TITLE
Does vscode work on ipad pro support?

### ISSUE THREAD

**Issue by baoyachi** [microsoft/vscode#121782]
With ipad pro 2021 use m1 cpu. Does vscode work on ipad pro support? if possible,so great!

**Comment by PoonKinWang** [comment]
VSCode runs on Electron, but Apple doesn't approve of the application using Electron.

**Comment by PoonKinWang** [comment]
Apple Is Trying to Kill Web Technology

**Comment by baoyachi** [comment]
Apple claims that the iPad is a huge productivity tool, but for developers, it's like an AK47 that can't fire bullets. So sad.

**Comment by RA80533** [comment]
Electron is a product of a time wherein built-in support for various web technologies was severely splintered. It was mid-2013—Microsoft would go on to release Internet Explorer 11 merely three months later. It was much easier to bundle up Chromium with your application than to require users to download a different browser to run the application *because it provided a better user experience*.

**Comment by baoyachi** [comment]
So? Browser programming is the trend of future development? @RA80533

**Comment by isidorn** [comment]
Dup of https://www.github.com/microsoft/vscode/issues/70764
