### ISSUE TITLE
PowerShell Progress Bar Stutter 

### ISSUE THREAD

**Issue by dmraymond** [microsoft/vscode#121848]
Issue Type: <b>Performance Issue</b>

When running the Write-Progress command and writing to the console host the progress bar will stutter after so many lines.

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:35:57.887Z)
OS version: Windows_NT x64 10.0.18363

[Video](https://1drv.ms/v/s!AseyBTu66xMxqz-Yx47Wq61-OiUZ?e=r1niKw)

**Comment by dmraymond** [comment]
It is noticeable at 14% and 24% in the progress bar in the video.

**Comment by TylerLeonhardt** [comment]
Looks like it's because the buffer is scrolling.

2 questions:

1. I see you're running this in the PowerShell Integrated Console. That is provided by the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) not vscode proper.
  
  Can you run this in a normal PowerShell terminal in VS Code? All you have to do is hit the `+` button next to where it says "PowerShell Integrated Console".
  
  Just make sure you're also running PowerShell 7 for that like you are in the PS Integrated Console.
2. Can you also run this outside of VS Code
