### ISSUE TITLE
Toolbar navigation should also be possible with up / down

### ISSUE THREAD

**Issue by RichCaloggero** [microsoft/vscode#121846]
@isidorn 

More of a suggestion:
When navigating within toolbars, left / right move among items. However, if the item is a text input (like a filter box), arrow keys suddenly navigate within that item's text as they should. This makes context a bit difficult to discern and how to get back to the toolbar in which you were navigating.

Perhaps up / down should navigate toolbars since they have no special meaning within text input fields (unless the text input is multiline which is probably not too often encountered in a toolbar context).

This may confuse some users, so perhaps make it a setting?

Also might want to consider a separate screen reader or a11y or accessibility settings category?

**Comment by isidorn** [comment]
Using up/down to navigate toolbars was already discussed, however there were some issues since some toolbars already use up/down for other functionality, so we could not do it in a consistent way.

Regarding left/right that gets trapped in input fields, that was also discussed and we landed on the `tab` has to be used to focus out.

So for now I would not change anything here, however keeping this open for discussion.

We try not to introduce any a11y settings unless they are really needed, in case we introduce enough we will definitely have a category for this.

For reference here are accessibility docs for vscode https://code.visualstudio.com/docs/editor/accessibility
