### ISSUE TITLE
Please 🙏 move the terminal +⌄ button back to the tabs bar

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#121893]
I **really** dislike how far the terminal `+` button is now from the tab bar -- it feels much harder to discover imo too as it is disconnected. Before, I felt it worked great -- it was connected -- you hit the plus and :boom: a terminal showed up right there where my mouse was.

![image](https://user-images.githubusercontent.com/641685/115655272-f626d680-a300-11eb-9c4c-79c98faf687a.png)

Please 🙏 ❤️

**Comment by gjsjohnmurray** [comment]
I guess it's placed there with "right-tabbers" in mind:

![image](https://user-images.githubusercontent.com/6726799/115660451-f1c7e100-a333-11eb-9816-f04318762de0.png)

In that location it **does** mean I have to take care to pick the correct down-arrow when panel has been maximized

![image](https://user-images.githubusercontent.com/6726799/115661023-c42f6780-a334-11eb-87d1-a80c07ccd2a0.png)

**Comment by gjsjohnmurray** [comment]
@Tyriar @meganrogge any plans for an Alt-modifier altering the behaviour of a click over an existing tab? Maybe this gesture could create a new instance of the same type as the tab I do it on.

**Comment by Tyriar** [comment]
I'd really prefer to not go back on this change because it simplifies so much about the tabs view and will make dnd feedback nicer. Additionally this is where the + was before and it's where actions global to any panel view go already.

It's also always been the plan to enable double click in the empty area which will solve your issue https://github.com/microsoft/vscode/issues/121933, as for the far `v` button you should set up a keybinding if you use it a lot and it bothers you.
