### ISSUE TITLE
Allow to open binary files in the text editor as explicit user gesture

### ISSUE THREAD

**Issue by freezestudio** [Microsoft/vscode#1218]
When I install GitHub Windows client, it generates an error, error details recorded in the

**X: \ Users \ xxx \ AppData / Local \ Temp \ VSD75A.tmp \ install.log**

File, I use vscode open it, but to give tips:

**The file can not be dispalyed in the editor because it is either binary, very large or uses an unsupported text encoding.**

Another: Use sublime text or notepad turns on properly.
Shall not, with a hex editor to open were compared and found need to start BOM information (FF EF or EF FF) vscode open file required documents, but did not use UTF8 encoding BOM information can also be opened.

Another: The install.log encoding format to Unicode text files, the file size is 9kb.

**Comment by bpasero** [comment]
@freezestudio can you attach the file please?

**Comment by freezestudio** [comment]
GitHub Setup error log file:
this rename .log to .txt:
[install.txt](https://github.com/Microsoft/vscode/files/60307/install.txt)

**Comment by bpasero** [comment]
The file is containing null bytes which we then detect as binary type. However the file seems to use UTF 16 as encoding. We only support that if the file has a BOM in the beginning. I think other editors just try to open the file with UTF 16 if they detect null bytes but this can also fail. 

I think we should allow to change the encoding from the editor in all cases even if we think the file is binary.

**Comment by iffy** [comment]
This one feature prevents us from using VS Code here at work.  We often have Markdown files with embedded null bytes (and other non-printable characters).

**Comment by bpasero** [comment]
@iffy may I ask why your markdown files contain 0 bytes?

**Comment by iffy** [comment]
That's a fair question :) We produce reports about network protocols, some
of which contain non printable characters. We strip, hide or convert the
unprintables (using some custom markup) before producing PDFs, but want to
retain the original binary data within the source.

On Apr 12, 2017 11:42 AM, "Benjamin Pasero" <notifications@github.com>
wrote:

@iffy <https://github.com/iffy> may I ask why your markdown files contain 0
bytes?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Microsoft/vscode/issues/1218#issuecomment-293654245>,
or mute the thread

**Comment by bpasero** [comment]
Ok, I think having a way to force open a file that we think is binary is still valid. E.g. similar how for large images we ask you to open them externally there could be a link to force open them inside the editor:

![image](https://cloud.githubusercontent.com/assets/900690/24972502/ee8413b0-1fbb-11e7-9407-0373eb6d4714.png)

**Comment by iffy** [comment]
I tried... I changed it to add a button labeled "Open anyway" but since this code base is enormous and unfamiliar, I have no idea what function to call to open a file, let alone with an explicit encoding :)  Somewhere down the `openFileFolderPicker` -> `open(IOpenConfiguration)` chain....

**Comment by bpasero** [comment]
Yeah sorry, the code is quite complex. You could start to debug through how editors open e.g. by adding a breakpoint to `editorPart.openEditor()`. I think for this to work we need a way to "force" open a binary file as text, even if our check returns that it is a binary file ([here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/files/node/fileService.ts#L217)).

**Comment by zaus** [comment]
@bpasero what about a couple lines up `options.acceptTextOnly`?  How can we turn that off?

**Comment by bpasero** [comment]
There should probably be a way to control this when opening that file to override.

**Comment by zaus** [comment]
Could we just have a setting to always open whatever we tell it to open?  Don't worry about protecting me from myself... ;)

**Comment by conioh** [comment]
> The file is containing null bytes which we then detect as binary type. However the file seems to use UTF 16 as encoding. We only support that if the file has a BOM in the beginning. I think other editors just try to open the file with UTF 16 if they detect null bytes but this can also fail.

That's insane and has to be fixed. I just tried to open a couple of files WER generated and... no go.

Not only it is unreasonable not no open UTF-16 encoded text files without a BOM since there too many of those files out there, it is completely ridiculous when Microsoft itself generates such files all over the place.

> I think we should allow to change the encoding from the editor in all cases even if we think the file is binary.

I agree.

But... Two years and still nothing? ☹️ I don't blame you personally, Benjamin, but I certainly blame Microsoft.

-"The file will not be displayed because is it either binary, very large or an unsupported text encoding."
-"WAT? That's UTF-16!"
-"Sorry, bro. I only support ASCII and EBCDIC."

That's how it sounds.

Being able to open text files is the first requirement from a source code editor, or an advanced text editor, or any text editor...

**Comment by bpasero** [comment]
There is now a new action to force open a file that we think is binary into the editor. You can then change the encoding accordingly.

![image](https://user-images.githubusercontent.com/900690/38248724-b307ad3c-3749-11e8-982d-34bffcfa370e.png)
