### ISSUE TITLE
Code folding

### ISSUE THREAD

**Issue by RichCaloggero** [microsoft/vscode#121967]
@isidorn 

The accessibility docs at https://code.visualstudio.com/docs/editor/accessibility seem to suggest that code folding isn't useful for screen reader users:

>Certain features such as folding, minimap (code overview), and word wrap are disabled when in screen reader mode. 

IMO, folding can be a great help when trying to read through large amounts of code, especially someone else's code!!

My editor is in screen reader mode and folding commands like control+k control+0 to fold all, and control+k control+j to unfold all seem to work for me.

Only suggestion I have is to somehow indicate that code is folded. I assume sighted users have such indication.

One way would be to use elipses or "...", perhaps a setting to change folding indication to something like:

>while (true) {...
}

or even

>while (true) {...}

or some way of indicating the start of a fold via live region message when the line at the start / end of the fold is reached.

**Comment by isidorn** [comment]
@RichCaloggero thanks for your feedback. Maybe the docs are not 100% precise, we are aware the code folding is useful, however due to limitation we disable it
More details can be found here https://github.com/microsoft/vscode/issues/43262
So let's close as duplicate and continue the discussion there
