### ISSUE TITLE
First debug with task in an untrusted workspace fails

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#121959]
1. Have an untrusted workspace with a debug configuration and a preLaunchTask
2. F5
3. Allow trust in the workspace
4. You can an error saying `${defaultBuildTask}` was not found 🐛 
5. F5 again and it works

**Comment by isidorn** [comment]
I can repro easily with our start TS extension sample. So the issue seems to be that even though the trust is granted this [`getTask`](https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/debug/browser/debugTaskRunner.ts#L156) does not return anything, and thus we throw.

Assigning to @alexr00 to investigate further, since it seems the `tasksService` is not properly fetching tasks even though trust has just been granted.

**Comment by alexr00** [comment]
This should come before the call to the task service. I expect that debug calls the configuration resolver service to resolve the prelaunch task.

**Comment by alexr00** [comment]
@isidorn I put breakpoints in the configuration resolver service but didn't see any of them get hit. Can you point me to where debug tries to resolve variables in the launch configuration?

**Comment by alexr00** [comment]
Found where debug tries to resolve variables: https://github.com/Microsoft/vscode/blob/0f6d7c41eb52e113d4aa61e44a8073c7f18f4b74/src/vs/workbench/contrib/debug/common/debugger.ts#L111-L112

**Comment by isidorn** [comment]
@alexr00 thanks a lot for finding the issue. After some discussion with you in chat we have come to find that after the user grants trust debug extensions are not yet activated since they are awaiting on trust.

@lszomoru @sbatten what is the suggested flow for vscode core if
1. User triggers an action that requires trust
2. User grants trust
3. We need extensions that were awaiting on trust, however the extensions are not yet there and the `requestWorkspaceTrust` has returned

I think the `requestWorkspaceTrust` should await for all extension to be activated before it returns.
If we do not do this then each user of `requestWorkspaceTrust` would have to come up with a custom solution which is weird.
Let me know what you think

fyi @weinand

**Comment by weinand** [comment]
I don't quite understand this.
- with the trust "never" setting builtin debug extension are not blocked from activating.
- "startDebugging" checks for trust and trust is given for the workspace
- "startDebugging" then uses the configuration resolver service to resolve `${defaultBuildTask}`.

Why should that fail?

**Comment by lszomoru** [comment]
@weinand might be correct as @sbatten recently updated the built-in extensions based on the updated schema. If you have extensions that are currently using `never` you should update them to the new schema. Apologies for the churn. 

```
"capabilities": {
    "untrustedWorkspaces": {
      "supported": true
    }
},
```

@isidorn, makes sense on waiting for the extensions to be activated. Will chat with @sbatten and @sandy081.

**Comment by isidorn** [comment]
@weinand @connor4312 can you please update the extensions to use the new schema?
@lszomoru great, let me know how the discussion goes.

**Comment by weinand** [comment]
@sandy081 created PRs yesterday and I've already pushed a new version of node-debug to the Marketplace.

**Comment by isidorn** [comment]
I believe there are no actionable items on this issue, so closing
