### ISSUE TITLE
Erratic debug value hover preview

### ISSUE THREAD

**Issue by pankleks** [Microsoft/vscode#12200]
- VSCode Version: 1.5.2
- OS Version: Win 10

When breakpoint hit (either node or chrome) - you can hover mouse over the variable (in code editor) and it shows popup with current value.
Very often it stops working - I could not find specific case, same code, same place sometimes works sometimes not.

**Comment by isidorn** [comment]
Debug hover currently has a lot of limitations since it is language agnostic and it has no understanding of the language AST. There are quite some issues open regarding the debug hvoer, please search the issues in this repo if it they do not cover your specific case please file a new bug with exact reproducable steps so we can investigate furhter - thanks!
