### ISSUE TITLE
Allow renaming terminal tabs inside the tab view

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#122023]
Terminal now:

<img width="390" alt="Screen Shot 2021-04-23 at 7 02 49 AM" src="https://user-images.githubusercontent.com/2193314/115882790-f3f87100-a401-11eb-9326-c9943b7b1ecd.png">

What we want:

<img width="229" alt="Screen Shot 2021-04-23 at 7 03 19 AM" src="https://user-images.githubusercontent.com/2193314/115882826-fe1a6f80-a401-11eb-8a4b-81e99d20fb94.png">

**Comment by Tyriar** [comment]
How explorer does it:

https://github.com/Microsoft/vscode/blob/731402dce225ce25d42a7b173361650a54bf52ad/src/vs/workbench/contrib/files/browser/fileActions.ts#L891-L922

**Comment by meganrogge** [comment]
The label becomes editable to receive text input here for the explorer
https://github.com/microsoft/vscode/blob/ef569a6e08c7cdc7fc3755a0efbc92232ea8b9dd/src/vs/base/browser/ui/tree/asyncDataTree.ts#L934-L952

**Comment by meganrogge** [comment]
Started work on branch ` merogge/edit-tab-item `

**Comment by isidorn** [comment]
I actually wanted to  create this identical issue, but then I remembered how many issues I got in my life because I used in the inline input box and decided that using a quick pick is actually not the worst :)
The problems with the inline quick pick is auto closing it when it loses focus, that code tends to be funky as the `blur` event sometimes comes a bit late. Another corner case is if you scroll out if it in the list and so on. Another corner case if you click on the + and the input box is already shown...
The UX would be nicer if the input was inline, but just be aware that I am not happy with the code looks in the explorer.

Without further ado, here are the code pointer in how the Explorer does it:
When the + action is clicked we create a fake `NewExplorerItem` [here](https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/files/browser/fileActions.ts#L815)
It is inserted in the model / service making everybody aware that element is in the editable mode using [this method](https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/files/browser/files.ts#L81)

And once the viewer detects that a item is in edit mode it actually renders the input box [here](https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/files/browser/views/explorerViewer.ts#L382)
You can notice how the input box listens on all the various events on how it could possibly be closed.

So when a + is clicked the refresh of the list is necessary due to a new element. Same as when the input box is closed.

**Comment by Tyriar** [comment]
Thanks for the tips/warning
