### ISSUE TITLE
variables pane went dim seemingly randomly during debug session, persisted until vscode reopend

### ISSUE THREAD

**Issue by cdaringe** [Microsoft/vscode#12203]
- VSCode Version: 1.5.2
- OS Version: osx 10.11.x

Steps to Reproduce:

i am unable to reproduce, however i can say the following:

- i was debugging some python code
- i stepped between multiple files
- i inspected content from the variables pane

<img width="759" alt="screen shot 2016-09-17 at 3 28 33 pm" src="https://cloud.githubusercontent.com/assets/1003261/18611381/f6ddbf2a-7ceb-11e6-8ce6-afeea5bc997a.png">

^^ content is much dimmer than on fresh boot.

<img width="606" alt="screen shot 2016-09-17 at 4 31 14 pm" src="https://cloud.githubusercontent.com/assets/1003261/18611629/2e270b00-7cf4-11e6-8193-39d4f3193337.png">

**Comment by isidorn** [comment]
@cdaringe might it be that you double clicked on some variable in order to change its value (gif attached)? And that for some reason the variables pane was left in a blurred state?

Unfortunetly we would need reproducable steps to investigate into this further.

![variablesblur](https://cloud.githubusercontent.com/assets/1926584/18624953/859d4b62-7e4b-11e6-811b-7ed72df45143.gif)

**Comment by cdaringe** [comment]
@isidorn good call. could have been. i am skeptical however, because it persisted across runs.
...and boom, there it is!

steps to reproduce:

- enter variable pane whilst debugging
- double click var for live editing (as shown above)
- immediately click "play" such that execution ends

on next run, all variables will be dimmed. :bug:

editing and exiting the edit context will restore the colors.

**Comment by cdaringe** [comment]
Yahoo!  Thanks
