### ISSUE TITLE
File not saving with AWS WorkDocs folder

### ISSUE THREAD

**Issue by misaxi** [microsoft/vscode#122078]
Issue Type: <b>Bug</b>

File is not saving when i'm making changes in AWS WorkDocs folder. changes flushes to the disk only after I exit VSCode instance.

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:36:32.643Z)
OS version: Darwin x64 19.6.0

**Comment by misaxi** [comment]
It happens only to newly created file, the file does not save to the disk. But changes made to existing files flushes properly.

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.
