### ISSUE TITLE
Introduce cursor history navigation

### ISSUE THREAD

**Issue by guy-kdm** [Microsoft/vscode#12219]
Hi guys, love the product!
Would be great to have a command to put the cursor back where the previous edit was made. This is similar to VS history navigation only, I think, better. :)

**Comment by alexandrudima** [comment]
To keep the number of issues in our inbox at a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: we look at the number of votes the issue has received and the number of duplicate issues filed. Thank you for your time and understanding.

If you disagree and feel that this issue is crucial: we're happy to listen and to reconsider.
