### ISSUE TITLE
When autocompleting import, it does not remove the already typed chars.

### ISSUE THREAD

**Issue by leon** [microsoft/vscode#122168]
- VS Code Version: March 2021 (version 1.55)
- OS Version: Mac OS Big Sur

Steps to Reproduce:
1. start typing an import
`import { MyThing } from '@app/admin/som`
2. the list is now short enough so you can pick the item with arrows and enter
3. The import will now be wrong
`import { MyThing } from '@app/admin/som@app/admin/something`

When writing the path in an import statement (typescript) you start to get autocompletion for it, usually when you have typed 10-20 chars.
when you have filtered out enough you start to step with the arrows on the keyboard and then select an item with enter.
When doing so it inserts the path, but it does not remove your already typed chars, so you end up with the search + the autocompleted path.

I hope this is an easy fix, because it's been bugging me for months :)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by mjbvz** [comment]
Can you please share a small project that demonstrates this issue?

**Comment by fedderw** [comment]
> Can you please share a small project that demonstrates this issue?

What do you mean by share a project? This is a problem that is happening in notebooks, which you can't upload here. 
Is there some vscode share feature?

 I've had it before, although it went away after an update. But now it's back. Super annoying, I basically stop using vscode whenever this problem comes up. 

`
import pandas as pd
import numpy as np
df = pd.DataFrame(np.random.randint(0,100,size=(100, 4)), columns=list('ABCD'))

# when I choose the autocompletion for 'nunique()', it returns the entire mathod chain
df.B.df.B.nunique()
`

**Comment by mjbvz** [comment]
@fedderw You are working in Python so it is not the same issue. File your issue against the python extension
