### ISSUE TITLE
command S doesn't save the first time

### ISSUE THREAD

**Issue by dreed47** [Microsoft/vscode#12216]
- VSCode Version: Code 1.5.2 (66f37fd2a99eb9d628dd374d81d78835b410c39b, 2016-09-12T13:05:12.065Z)
- OS Version: Darwin x64 15.6.0

Steps to Reproduce:

1. change any file
2. hit CMD - S to save

The indicator on the tab still shows a dot.  Need to hit CMD - S a second time to have it save

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by dreed47** [comment]
yep,  its an extension,  here is the link to an issue in the extension project 
https://github.com/Lonefy/vscode-JS-CSS-HTML-formatter/issues/20
 thx for your help
