### ISSUE TITLE
add keyboard shortcuts to collapse and open sub indent lines, move collapesed lines

### ISSUE THREAD

**Issue by idealsu** [Microsoft/vscode#12213]
new feature request: 
1, add keyboard shortcuts to collapse and expand sub indent lines and move collapesed line
2, add keyboard shortcuts to select a block area, e.g, alt+shift+↑↓←→ in visual studio.net

**Comment by alexandrudima** [comment]
To keep the number of issues in our inbox at a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: we look at the number of votes the issue has received and the number of duplicate issues filed. Thank you for your time and understanding.

If you disagree and feel that this issue is crucial: we're happy to listen and to reconsider.
