### ISSUE TITLE
boosfail to save file  i am trying to save file but it does nt work  3 options retry , save as , discard were show on screen when i click on save as vs code said ur index.html file already existtrap

### ISSUE THREAD

**Issue by amnasadiq194** [microsoft/vscode#122105]
file doesnt save
i am trying to save file but it does nt work 
3 options retry , save as , discard were show on screen when i click on save as vs code said ur index.html file already existta into your clipboard because it was too large to send. Please paste.

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.
