### ISSUE TITLE
Configuration variables `relativeFile` and `relativeFileDirname` are absolute when using remote

### ISSUE THREAD

**Issue by yohan-pg** [microsoft/vscode#122212]
- VS Code Version: 1.55.1
- OS Version: MacOS 10.15.6 (19G2021)

Steps to Reproduce:

1. Open any remote project.
2. Use any command that accesses the `relativeFile` configuration variable.
For instance, adding the following command to keyboard shortcuts and pressing alt+e (with a remote file opened and active) should reproduce the issue:
```
{
        "key": "alt+e",
        "command": "workbench.action.terminal.sendSequence",
        "args": {
            "text": "echo ${relativeFile}\u000D"
        }
}
```

The echoed path will be relative rather than absolue if in a remote project, although the expected behavior is obtained when working locally.

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexr00** [comment]
@Tyriar it looks like terminal is passing `undefined` as the first argument to `resolveAsync` here:

https://github.com/Microsoft/vscode/blob/c95aaf71a8ce48d626f4e7afc50f60dd9b26cb63/src/vs/workbench/contrib/terminal/browser/terminalActions.ts#L95-L96

Because a workspace folder isn't passed into `reolsveAsync`, the configuration resolver service falls back to using the absolute path.

**Comment by Tyriar** [comment]
Should be fixed now
