### ISSUE TITLE
Notebook controller: `interruptHandler` not fully clear to me

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#122376]
Testing #122216

I see that `interruptHandler` can be used when I stop execution of a cell. But wouldn't it make more sense to do this through a `CancellationToken` that gets passed into my execution handler?

**Comment by jrieken** [comment]
> But wouldn't it make more sense to do this through a CancellationToken that gets passed into my execution handler?

Yes - the cancellation tokens to "fire" when a cell is being cancelled. The problem is that they only fire once - in cancellation tokens there is only the transition from not-canceled to canceled, not canceled to canceled. Now, some kernels don't support granular cancellation and only the equivalent of hitting `Ctrl+C` until everything stops. That's what interrupt is for.

**Comment by bpasero** [comment]
Maybe that explanation could go into the API docs to make that clearer.

**Comment by roblourens** [comment]
Did you mean to remove the `NotebookInterruptHandler` type helper @jrieken? You also added a link to it from the description, and it's used by extHostNotebookKernels so wasn't sure if that was intentional

**Comment by jrieken** [comment]
Sorry, there some compiler carnage... Removed the type on purpose to define everything in place (and also to make it a little less prominent)
