### ISSUE TITLE
Terminal.integrated.tabs setting review

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#122338]
Testing #122242

`terminal.integrated.tabs.enabled` and  `terminal.integrated.tabs.location` could be handled in one setting:
`terminal.integrated.tabs.location: 'left', 'right', 'hidden'`

I would also recommend removing the setting     `"terminal.integrated.tabs.hideForSingle"`, I am convinced this is a great default and would only introduce this setting if users ask for this. Which I think will never happen.

For example in the CALLSTACK view for Debug we do not show debug threads, sessions if there is exactly 1. And never has anyone requested that we make this configurable.

**Comment by Tyriar** [comment]
> terminal.integrated.tabs.enabled and terminal.integrated.tabs.location could be handled in one setting:
terminal.integrated.tabs.location: 'left', 'right', 'hidden'

I worry about it being more difficult to find how to disable it if this is all wrapped into the location setting, that's not intuitively where I'd think to disable it.

> I would also recommend removing the setting "terminal.integrated.tabs.hideForSingle"

I've actually already got feedback suggesting users want this setting, I added for people who are bugged by the layout shifting in the terminal panel and the fact that resizing terminals can sometimes be disruptive. We'll likely add https://github.com/microsoft/vscode/issues/122217 to help with this, but I'd probably prefer to eventually always show the tabs for example since I almost always have more than one tab (but am testing the single tab feature atm).

@meganrogge thoughts?

**Comment by isidorn** [comment]
I believe that most people for disabling will discover the context menu action. Also the merged setting does not have to be called location but something better, not sure what, maybe `mode`?

If multiple users already want it feel free to keep it. My point is we can easily add it next milestone if it is really needed, I do not think there will be an outrage if it is missing from day one.

**Comment by meganrogge** [comment]
>I worry about it being more difficult to find how to disable it if this is all wrapped into the location setting, that's not intuitively where I'd think to disable it.

I feel the same way about this and would find it illogical/confusing to wrap view state (visible, hidden) and location (right, left) into one setting. 

Re removing `hideForSingle`, I think we need to see what the feedback is before removing options.

**Comment by Tyriar** [comment]
Closing this out as enabled is the common pattern for this, we may also want to add smarts to settings editor one day that would leverage this and hide settings in a namespace where enabled is false (have spoken with @eamodio about this idea).

<img width="449" alt="Screen Shot 2021-04-27 at 10 12 51 AM" src="https://user-images.githubusercontent.com/2193314/116283859-465aca00-a741-11eb-854e-84f3c6ab51ab.png">
<img width="490" alt="Screen Shot 2021-04-27 at 10 13 08 AM" src="https://user-images.githubusercontent.com/2193314/116283870-4955ba80-a741-11eb-9f6b-4ad4d459922f.png">

For hideForSingle we'll change this to a string and maybe expand it in https://github.com/microsoft/vscode/issues/122348
