### ISSUE TITLE
Enabling an extension via setting should not always require a reload

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#122337]
Testing #122230

* find an extension that's disabled because it doesn't specify its trust capability (for me its `kisstkondoros.vscode-codemetrics`)
* add that extension to the `extensions.supportUntrustedWorkspaces` setting and say `supported: true`
* 😕 extension stays disabled

**Comment by lszomoru** [comment]
Making changes to the `extensions.supportUntrustedWorkspaces` requires a window reload. Will make sure to show the dialog.

**Comment by jrieken** [comment]
> Making changes to the extensions.supportUntrustedWorkspaces requires a window reload.

Why? Enabling an extension theoretically doesn't require a reload, right?

**Comment by lszomoru** [comment]
That is correct. But you could also use this setting to forcefully disable an extension in restricted mode. If that is the case, since we cannot unload an extension that has already been loaded (please correct me if I am wrong), we would either have to reload the window, or restart the extension host.

**Comment by jrieken** [comment]
> If that is the case, since we cannot unload an extension that has already been loaded

Sure, but I filed this issue explicitly for the enable-only case. Yes, as soon as one extension gets disabled you need to reload but for enable-only, which I believe is more frequent, this isn't needed and it would make the flow more pleasant to use
