### ISSUE TITLE
Should text editor be offered as an option when it's an image file?

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#122388]
Testing #122030

![recording - 2021-04-27T093011 294](https://user-images.githubusercontent.com/29464607/116278222-26c0a300-a73b-11eb-9aa6-92162ae09038.gif)

**Comment by lramos15** [comment]
What you see in the gif is a bug that Ben pointed out to me and will be fixed in the next insiders. The short answer is the text editor should always be an option. There's nothing preventing me from being silly and naming all my text files .png, etc. We want there to always be an available editor to open something even if it's in a garbled mess. I would be happy to discuss it further if you disagree.
