### ISSUE TITLE
Separator in remote indicator can appear/disappear

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#122309]
Testing #122101

The separator between categories can sometimes disappear and the quick pick jumps a little

After typing 'Rem'
![image](https://user-images.githubusercontent.com/172399/116227885-e837e200-a754-11eb-9bf4-22da5f3cd6c4.png)

After typing 'Remo'
![image](https://user-images.githubusercontent.com/172399/116227671-b0c93580-a754-11eb-8793-d46fef8f0068.png)

It looks like the separator appears/disappears after each typed character

**Comment by aeschli** [comment]
I've also seen the group line disappear and appear again. Looks like a issue with the quick pick rendering

**Comment by aeschli** [comment]
I see it a lot (admittedly because I work on the remote menu) and the missing separator really bugs me :-)

- install the codespaces extension
- open a new local window
- open the remote menu right away (click on the remote indicator in the status bar)
- after a second you see the menu being refreshed (the codespaces commands are coming in)
- check out all the group, some group will not have a separator line e.g.  `Install Additional Extensions...`

When debugging from source I got this:
The 'New Test Resolver' menu has no separator line on top.
![image](https://user-images.githubusercontent.com/6461412/120483098-1216a100-c3b2-11eb-806d-2483b964e24f.png)

But the border line is turned off
```
.quick-input-list .monaco-list-row:first-child .quick-input-list-entry.quick-input-list-separator-border {
    border-top-style: none;
}
```

But because the list view reuses entries (my guess), the `monaco-list-row` divs in the dom don't necessarily have the same order as seen in the UI.
![image](https://user-images.githubusercontent.com/6461412/120482424-6a00d800-c3b1-11eb-99b0-b7d65a413907.png)

-> ` .monaco-list-row:first-child` doesn't work here

**Comment by aeschli** [comment]
Pushed a fix that uses `.quick-input-list .monaco-list-row[data-index="0"]` instead.
