### ISSUE TITLE
Terminal status rendering

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#122432]
Testing #122241

It looks like there is too much space between the trash and the warning icon.

Also the warning icon appears blurred when selected

![image](https://user-images.githubusercontent.com/172399/116299277-c44cbe80-a79d-11eb-8c18-2d2ac8466b0f.png)

**Comment by Tyriar** [comment]
The gap is intentional because it's the standard decoration padding:

![image](https://user-images.githubusercontent.com/2193314/116306184-9d6c9900-a759-11eb-9681-790287d074ef.png)
![image](https://user-images.githubusercontent.com/2193314/116306271-b5441d00-a759-11eb-928b-ef0195c561c6.png)

Blurring might be because the icon's font size is 14px not 16px

**Comment by Tyriar** [comment]
It may be 0.5px too high 🤔 
![image](https://user-images.githubusercontent.com/2193314/116307539-4f589500-a75b-11eb-96e1-ad5b839ff54f.png)
