### ISSUE TITLE
Terminal tabs: cannot shift click into tabs

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#122402]
I wanted to start a multi selection but when no tab is selected I cannot even Shift+Click into a terminal tab.

![recording (3)](https://user-images.githubusercontent.com/900690/116281926-7ed2c600-a78a-11eb-8d5f-64d59838ef9a.gif)

**Comment by Tyriar** [comment]
Repro:

1. Click in empty area
2. Shift click on a tab

**Comment by Tyriar** [comment]
That repro actually happens in the explorer too. You can get into this state though where the terminal is selected but the list is focused, when the list is focused I don't think shift+click is meant to work.

<img width="256" alt="Screen Shot 2021-04-28 at 7 15 42 AM" src="https://user-images.githubusercontent.com/2193314/116419074-8c6f6680-a7f1-11eb-91dd-ef746fa05036.png">

**Comment by Tyriar** [comment]
Actual bug repro:

1. Open some terminals
2. Click in the empty area
3. Focus a terminal by clicking into the actual terminal
4. Shift click another terminal tab

**Comment by Tyriar** [comment]
Managed to reproduce this in the explorer:

1. Open explorer
2. Open a file
3. Click in empty area
4. Run reveal active editor in sidebar command
5. Shift click in explorer

The issue is happening because anchor is undefined so it doesn't enter either condition, it should be the selected item in this case though.

https://github.com/Microsoft/vscode/blob/20784c13a10c28bfa5cb8d79dd9e7084824f06dd/src/vs/base/browser/ui/list/listWidget.ts#L663-L663

cc @isidorn

**Comment by faizjamil** [comment]
This issue being worked on by anyone? If not I'm willing to take a crack at it

**Comment by khoaleanhvn** [comment]
@faizjamil you're working on it? If you are, I will work with another issue.

**Comment by faizjamil** [comment]
@khoaleanhvn I'll take a crack at this issue, will probably be posting on this issue a bit to clarify some things as i start looking through the code base and the relevant code.
