### ISSUE TITLE
Closing a dirty notebook and re-opening via the cmd does not restore dirty state

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#122467]
Testing #122033

https://user-images.githubusercontent.com/35271042/116320106-808d9100-a76c-11eb-9f8a-d0e54053fe58.mov

> dirty notebooks restore properly when you run code-insiders <path to folder> <path to file in folder> provided the folder you point to has dirty notebooks in it (this way of launching is special because we do not restore the previous editors and only open the ones from the command line + any editor with backup)

1. make changes
2. quite application
3. open vs code with the same file
4. :bug: dirty state is not restored

If I open the same workspace again, the dirty state is preserved

**Comment by jrieken** [comment]
Doesn't reproduce for me. Adding @bpasero for insights when this could happen

**Comment by bpasero** [comment]
We only restore backups if you open the same workspace, in this case opening just the file will open an empty workspace.

**Comment by jrieken** [comment]
> in this case opening just the file will open an empty workspace and open the file as it is stored on disk.

What? So we accept this as data loss case?

**Comment by bpasero** [comment]
This is not data loss. You can always get back to the contents when you open the workspace again.

**Comment by jrieken** [comment]
Ah, now I see. I leave a file from workspace A dirty and if open workspace A the dirty-state is restored, but if I only open that file it isn't.

**Comment by bpasero** [comment]
Yeah, so a bit more background: a long time ago we used to aggressively restore every workspace that had dirty files in them as a way to ensure you always see these workspaces. Then due to some changes we broke this and stopped restoring these workspaces for like 6 months. We then wanted to bring this back but it resulted in lots of users getting hundreds of windows to open that accumulated so we decided to not restore workspaces aggressively anymore.

To make this a bit easier to discover, we added this "dot" annotation to the recently opened menu:

![image](https://user-images.githubusercontent.com/900690/116515105-286da080-a8cc-11eb-838b-ad9a0970a3c9.png)

Refs:
* https://github.com/microsoft/vscode/issues/92318
* https://github.com/microsoft/vscode/issues/90949
