### ISSUE TITLE
No tooltip shown when hovering over a terminal status

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#122427]
Testing #122241

There is no tooltip over the terminal status e.g. , the other items have a tooltip. The tooltip could say 'Relaunch Needed'. 

There also is no tooltip on the bell icon.

![image](https://user-images.githubusercontent.com/172399/116298151-623f8980-a79c-11eb-87a2-bd5a2c18ee3f.png)

**Comment by Tyriar** [comment]
This also happens in SCM and explorer decorations, looks like it happens because the hover listener is on `.monaco-icon-label-container` and not `.monaco-icon-label` 
![image](https://user-images.githubusercontent.com/2193314/116320618-6bfdc880-a76d-11eb-99c0-9cd8b480100a.png)

Changing the container to its parent will end up breaking the actions:

![image](https://user-images.githubusercontent.com/2193314/116320762-b3845480-a76d-11eb-9561-4e626f7e36bc.png)

https://github.com/microsoft/vscode/blob/61364b049268df5d4fc01b32602e7b7fd7d67203/src/vs/base/browser/ui/iconLabel/iconLabel.ts#L155-L155

**Comment by luluyuzhi** [comment]
I want to know how toggle  attach.😢

**Comment by khoaleanhvn** [comment]
Anybody's working on this? If not, I will try.

**Comment by luluyuzhi** [comment]
> Anybody's working on this? If not, I will try.
@khoaleanhvn  may not

**Comment by Ashray123** [comment]
Hello @jrieken, I would love to work on this issue if no one is working on it, could you provide a guide on what is to be done.

**Comment by Manish-Giri** [comment]
I would be happy to take this up. Looks like @Ashray123 has already requested to take up #124419, so this one should be available.

**Comment by timfenney** [comment]
> This also happens in SCM and explorer decorations, looks like it happens because the hover listener is on `.monaco-icon-label-container` and not `.monaco-icon-label`
> ![image](https://user-images.githubusercontent.com/2193314/116320618-6bfdc880-a76d-11eb-99c0-9cd8b480100a.png)
> 
> Changing the container to its parent will end up breaking the actions:
> 
> ![image](https://user-images.githubusercontent.com/2193314/116320762-b3845480-a76d-11eb-9561-4e626f7e36bc.png)
> 
> https://github.com/microsoft/vscode/blob/61364b049268df5d4fc01b32602e7b7fd7d67203/src/vs/base/browser/ui/iconLabel/iconLabel.ts#L155-L155

Hey @Tyriar, I created the PR above, and didn't notice any broken actions on my branch. Do you mean that the other buttons won't work, e.g. for a Terminal session the :wastebasket: ?

**Comment by bpasero** [comment]
I forgot why we added that for quick input, probably to avoid a hover when hovering over the label of a quick pick item but still show it when hovering over description which can be cropped.

Can we not put the hover over the entire thing if there is no description title otherwise?

**Comment by alexr00** [comment]
> Should the title be set up for the whole element when there is no description or no description title?

This seems reasonable to me.
