### ISSUE TITLE
Allow dragging to hide the terminal tabs

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#122420]
Testing #122242

With the terminal tabs, I expect to be able to hide them by clicking on the sash and dragging. This similar to what we support for the sidebar and panel

**Comment by Tyriar** [comment]
This isn't particularly discoverable and it seems somewhat harmful where a user could accidentally hide the tabs this way and not know how to bring them back, plus this has a special narrow tabs view when "minimized", similar to other views:

![image](https://user-images.githubusercontent.com/2193314/116297398-149d2f80-a750-11eb-830c-6ee910750fa1.png)

These are less of a problem for the sidebar and panel because of the amount of ways to get it back, hiding tabs is changing a setting to say you don't want to see them anymore.
