### ISSUE TITLE
Trust workspace dialog does not go away after the trusted folders setting is updated

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#122450]
Testing #122252

* Open two workspaces A and B, trust A but not B
* Workspace B then has a modal dialog
* Add workspace B into trusted setting from workspace A
* In workspace B, all components related to trust are updated, but the modal dialog is still there.

**Comment by sbatten** [comment]
After discussion, dialogs don't really have dismissal concept because it would be weird to have a dialog appear and flicker away. Also, most scenarios where this presents itself are artificial from a testing mindset. The mainstream scenario is after an update/restart, restoring multiple windows. To address this, I will only show the dialog once the window is focused. This means trust will be evaluated at focus time, not restart time and if you trust B before navigating to it, the dialog will not show.
