### ISSUE TITLE
Should I get a Trusted Workspace prompt when browsing a remote GH repo?

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#122559]
1) Open a GH repo through remote hub:

![image](https://user-images.githubusercontent.com/4674940/116429235-8df15c80-a7fa-11eb-927c-35e40ca38714.png)

**Comment by sbatten** [comment]
Thanks for creating the issue. This is the new question I have been mulling over since we changed to prompt on startup. Our original thinking was, since we were using the ask ondemand approach that a user would never notice restricted mode. Now that we don't have that but likely have no "trust-requiring" functionality, there are 2 questions:

1. Should you prompt?
2. If so, should the language change?

**Comment by sbatten** [comment]
My first take on this is that we could just treat virtual workspaces the same way we treat the empty workspace because they are very similar in behavior, the files are exposed to extensions via our document models but we aren't aware of any features being vulnerable through them so we treat it as trusted.

**Comment by sbatten** [comment]
closing in favor of https://github.com/microsoft/vscode/issues/126913
