### ISSUE TITLE
Hard to see active tab after latest update

### ISSUE THREAD

**Issue by sauverma16** [microsoft/vscode#122588]
Issue Type: <b>Feature Request</b>

Hi

After the latest updates, it is very hard to see which is the current tab on the top in all of the dark themes and I keep making mistakes and editing wrong tabs. 

Can you please restore the previous dark themes which had better contrast
Saurabh

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:35:57.887Z)
OS version: Windows_NT x64 10.0.19041

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.
