### ISSUE TITLE
Receiving an error for preloads when I had no preloads set or needed

### ISSUE THREAD

**Issue by tanhakabir** [microsoft/vscode#122672]
- VS Code Version: 1.56.0-insider (Universal)
- OS Version: Darwin x64 19.6.0

Steps to Reproduce:
1. Using a freshly scaffolded Notebook from `yo code --insiders` which is supposed to just take in JSON and print a stylized version of that JSON in the output renderer.
2. Everything build and runs fine in the extension host but when you go to actually execute one of these cells you get a generic error about preloads.
3. I believe no preloads are required for this controller so this error shouldn't pop up and it didn't in previous versions of Insiders.

![image](https://user-images.githubusercontent.com/12758612/116580292-1558d180-a8c8-11eb-993d-16e75fd8af45.png)

Here's a link to the controller code: [sampleProvider.ts in the templates](https://github.com/microsoft/vscode-generator-code/blob/main/generators/app/templates/ext-notebook-renderer/src/extension/sampleProvider.ts)

**Comment by jrieken** [comment]
@tanhakabir I that by chance a 3rd party renderer?

**Comment by jrieken** [comment]
That error message seems to come from webpack but the string doesn't appear anywhere in our sources, so I do believe it must be something that's installed on top

**Comment by tanhakabir** [comment]
Huh I'm not sure what changed to break the webpack stuff. @connor4312 do you have an idea of what would cause this?

**Comment by connor4312** [comment]
I think this can be fixed by setting the `publicPath` to an empty string or `/`, on this line https://github.com/microsoft/vscode-generator-code/blob/main/generators/app/templates/ext-notebook-renderer/webpack.config.js#L15

It should not actually matter since we override it here https://github.com/microsoft/vscode-generator-code/blob/main/generators/app/templates/ext-notebook-renderer/src/client/index.ts#L14

**Comment by tanhakabir** [comment]
cool thanks it worked! I'll update the template
