### ISSUE TITLE
Debug and run flutter app on a phone(android / ios) wireless

### ISSUE THREAD

**Issue by hupo376787** [microsoft/vscode#122640]
Is it possible to debug and run the flutter app on a phone(android / ios) wireless, currently I have to connect via a USB cable.

Thanks.

**Comment by isidorn** [comment]
Please file against the durt / flutter extension
@dantup

**Comment by DanTup** [comment]
@hupo376787 for Android, this is possible if you enable remote access to ADB on your phone (note: there are security implications of this - only do it on a secure network and turn it off when not using it):

https://medium.com/what-the-flutter/flutter-app-testing-over-network-sans-usb-connection-a6e472c8ac42

For iOS, it's not currently supported (this is a limitation of Flutter tooling rather than VS Code or the VS Code extension) but there's an open issue tracking it at https://github.com/flutter/flutter/issues/15072 that you can 👍  / subscribe to. Thanks!

**Comment by hupo376787** [comment]
@DanTup @isidorn Thx, guys.
