### ISSUE TITLE
Regression: wait (--wait) with custom editors seems to be broken

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#122699]
Not sure when this started, but in recent Insiders versions, custom editors opened with `--wait` seem to no longer stop waiting when they are closed.

You can reproduce this using GitLens and its rebase editor.

- Install GitLens and make sure you haven't disabled the rebase editor
- Set VS Code as your default Git editor: `git config --global core.editor "code-insiders --wait --reuse-window"` 
- Start an interactive rebase: `git rebase -i HEAD~5` or something along those lines
- Once the GitLens interactive rebase editor opens, either start or abort the rebase
- :bug: Git will still continue to wait even though the editor has been closed

**Comment by lramos15** [comment]
@bpasero I'm not sure how to investigate this to be honest. I see the issue that @eamodio is experiencing, but I can't find a simple repro with other custom editors so I'm not sure what's special about the git case.

**Comment by bpasero** [comment]
I did push a change this milestone to a method that is used for `--wait`: some code that observes all opened editors for a resource to close (the one `--wait` is waiting on). I thought that code should only track file editors and not custom editors but I did not realise that we also want to support custom editors.

I still think the code is fishy because we should not track the resource for closing but the editor that is being used to edit the file being waited on and that could be either a file editor or a custom editor.

Anyway, I pretty much reverted the code to how it was before.
