### ISSUE TITLE
Can't make out filename/folder with color theme Light+

### ISSUE THREAD

**Issue by 2lach** [microsoft/vscode#122670]
- VS Code Version: Version: 1.55.2
- OS Version: macOS Big Sur, 11.3

Steps to Reproduce:

1. open up VS code <cmd> + <shift> + <P>
2. select color theme: Light+
3. Select file or folder in sidebar
![vs code light+ theme issue with selected sidebar item](https://user-images.githubusercontent.com/11457600/116573960-8f5f7980-a90d-11eb-9398-dca35d804ddd.jpg)

So i would like a fix of course cause i love the theme light+ but will happily settle for knowing a solution i can apply in my settings.json file 
like in "workbench.colorCustomizations" or where the property for sidebars selected items background color might live 😄 

Have a good one!
 

Does this issue occur when all extensions are disabled?: Yes

**Comment by misolori** [comment]
@2lach I believe you are looking for the `list.activeSelectionForeground` color token for the text in the active state. I'll close this issue since it's not an issue. Next time please be sure to read through the [theme color reference guide](https://code.visualstudio.com/api/references/theme-color).

**Comment by 2lach** [comment]
Why, thank you kindly good sir 😏
The best of day to you.
