### ISSUE TITLE
Trusting `/` doesn't work for codespaces

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#122651]
* have `/` as trusted path for Codespaces host
* open a codespace
* :bug: you get the trust dialog

<img width="1263" alt="Screenshot 2021-04-29 at 14 45 38" src="https://user-images.githubusercontent.com/1794099/116552717-9e3c3100-a8f9-11eb-94f0-05bdd5c47168.png">

**Comment by sbatten** [comment]
@jrieken codespaces are kinda special right now in that you trust the codespace instance, not the repo since the uri encodes the machine... so if you open a different codespace it has to be trusted separately. There is a separate issue to improve this via resolver api that would give us a better URI to use in trust calculations.

**Comment by sbatten** [comment]
codespaces will use the isTrusted flag, which makes this issue obsolete.
