### ISSUE TITLE
Launch config name shows up twice

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#122687]
- Open this repo https://github.com/sinapis/vscode-118282
- See a double attach config, only one is defined

![image](https://user-images.githubusercontent.com/323878/116607617-13523b00-a8e7-11eb-8b41-2db46e8bb8ea.png)

**Comment by isidorn** [comment]
This is fixed for me in latest insiders (I actually pushed a fix a couple of days ago)
@roblourens can you reproduce with a fresh user data dir?
Have you opened this repository some time before this week (when the bug was still present)?
More details here https://github.com/microsoft/vscode/issues/121148

For now closing as duplicate, but if you still see this let me know and I will reopen

![Screenshot 2021-04-30 at 09 54 29](https://user-images.githubusercontent.com/1926584/116665473-1c501480-a99a-11eb-9ac3-884bab3ee06b.png)
