### ISSUE TITLE
Trust dialog wording suggestions

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#122655]
> Code - Insiders provides advanced editing features that may automatically execute files in this folder.

In the name of [Plain English](https://en.wikipedia.org/wiki/Plain_English) is would remove "advanced" and also "editing" from the sentence above. Also, I'd make it clear that files "from" the workspace/folder are executed, "in" might suggest they are executed in the context of this folder

"Code - Insiders provides ~~advanced editing~~ features that may automatically execute files ~~in~~ _from_ this folder."

Maybe also mention the consequences/threat. All together, this is my suggestion

"Code - Insiders provides features that may automatically execute files from this folder. Executing untrusted files is a security risk."

**Comment by sbatten** [comment]
"advanced editing" was intended as a signal that the features are for more development focused work. I like the simplification you suggest but feel we lose that signal. Any suggestions?

I like the "from" change, makes sense to me.

In order to align the various dialogs the first line has been used to talk about the requirements and the second line remains the same mentioning risk, recommendations, and docs. I think adding risk to the first line is redundant and makes the dialog more scary.

**Comment by jrieken** [comment]
> "advanced editing" was intended as a signal that the features are for more development focused work. 

I understand but for me it makes the sentence complex and slightly misleading. I might think I am fine because I don't use "advanced" features or because I don't "edit", I only read files. Also, "advanced" sounds a little like bragging and strictly "editing" is false because the tsdk setting can own you without typing a letter. 

> I think adding risk to the first line is redundant and makes the dialog more scary.

Yeah, makes sense

**Comment by lszomoru** [comment]
+1 on removing the "advanced editing" terminology, for the reasons described above.

I am also not sure about "Code" and "Code - Insiders". The dialog clearly appears in VS Code so do we need to include that in the dialog? Do we include the product name in any other dialogs that we display? If we do intend to include the product name, should it be "Visual Studio Code" instead of just "Code"? 

If we were to remove that, could we simplify the dialog into one paragraph? 

"Features may automatically execute files from this folder. If you don't trust the authors of these files, we recommend to continue in restricted mode as the files may be malicious. See [our docs](https://aka.ms/vscode-workspace-trust) to learn more."
