### ISSUE TITLE
Incorrect definition ordering for TypeScript

### ISSUE THREAD

**Issue by godomainz** [microsoft/vscode#122773]
*TS Template added by @mjbvz*

**TypeScript Version**: 4.3.0-dev.20210427

**Search Terms**
- go to definition
- react
- functional component

---

- VS Code Version: 1.55.2
- OS Version: Windows 10 Pro

Steps to Reproduce:
1. npx create-react-app my-app --template typescript
2. Open src/App.tsx and convert App function to a const with FC type definition.
```
import React, { FC } from 'react';
import classes from  './App.module.css';

export const App:FC = () =>  (
    <div className={classes.App}>
        Hello
    </div>
);

export default App;
```

3. Go to index.tsx and CTRL + CLICK on `<App />`
4. Expected App.tsx to open NEW WINDOW. 
5. IF I just change   `export const App:FC` to `export const App` it does open App.tsx in NEW WINDOW

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
@jrieken Adding you since this seems like a generic thing with 'go to symbol'. 

TS returns two definitions here:

1. The actual definition in the code `const x = ...`
2. The definition of the type from `node_modules/@types/...`

TS always returns the results in that order.

In VS Code itself, we [have code that then always resorts the definitions](https://github.com/microsoft/vscode/blob/ac35a5b937e73b8f59154c02cba4a5cc96ba02cd/src/vs/editor/contrib/gotoSymbol/referencesModel.ts#L296)

This results in the primary definition either being displayed first or second depending on its name (basically does the file name come before or after `node_modules`)

I think TS should investigate if we should really have two definitions at all, but it also feels broken that there's no way for an extension to always display the most interesting definition first

**Comment by RyanCavanaugh** [comment]
> As users, the general feedback is that it's confusing that there are two definitions in the first place

We get too much feedback that we miss some definitions and that it's "always better" to return more relevant definitions rather than fewer. I'm happy to take sort-order bugs on this, though, since I definitely agree that some definitions are more equal than others.

**Comment by jrieken** [comment]
> In VS Code itself, we have code that then always resorts the definitions

We do sort but we also remember the [provider's first element](https://github.com/microsoft/vscode/blob/ac35a5b937e73b8f59154c02cba4a5cc96ba02cd/src/vs/editor/contrib/gotoSymbol/referencesModel.ts#L288) and we should always start with that and then proceed with the remaining elements...

**Comment by jrieken** [comment]
Hm... When running out of source I cannot reproduce, neither with 4.3.0 nor with 4.1.4

**Comment by jrieken** [comment]
Also not reproducable with 4.5
