### ISSUE TITLE
Backup tracker should not allow for more changes when shutdown takes a long time

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#122774]
Repro:

1. Install Luna Paint
2. Set `"luna.retainContextWhenHidden": false,`
3. Open new image via command, make it fairly large for example 2000x2000
4. Open another file so the image is in the background
5. Try close the window, you will see the below notification
6. Open the image and close it, without saving changes, the notification doesn't go away

![image](https://user-images.githubusercontent.com/2193314/116767172-411caa00-a9e3-11eb-93b1-01539d682e5c.png)

This has been happening I think since @bpasero made this change which made it much better than before https://github.com/microsoft/vscode/issues/115028#issuecomment-771444544.  Behind the scenes Luna is throwing because a backup is not possible because the context is gone so I think the notification is warranted, just it should be listened not just for backups but also for when the document gets disposed.

**Comment by bpasero** [comment]
@Tyriar I actually think that picking a notification was the wrong decision right from the beginning because when shutdown has started and some operation (like backup) takes a long time, we should not allow the user to mess with editors because at that time we risk to loose data if the user manages to accumulate it during shutdown, i.e. think about:
* shutdown triggered
* an extension takes a long time to backup
* user meanwhile opens more editors and makes them dirty
* backup eventually finishes
* 🐛 we just shutdown potentially without waiting for the new editors to backup

As such I suggest to switch to a modal dialog and I have 2 options:

**With Details**
![recording](https://user-images.githubusercontent.com/900690/117114885-aaf2d600-ad8c-11eb-85bf-b823fdb53a6c.gif)

**Without Details**
![recording (1)](https://user-images.githubusercontent.com/900690/117115021-d5449380-ad8c-11eb-8590-a6ba2f8f4af8.gif)

This dialog can also show on other situations:
* a save that takes long
* a revert that takes long

Happy for feedback on the experience and wording (cc @misolori )

**Comment by bpasero** [comment]
I pushed this wording now:

![recording (2)](https://user-images.githubusercontent.com/900690/117116744-04f49b00-ad8f-11eb-8d8b-8afcbd7c9cd2.gif)

**Comment by Tyriar** [comment]
Looks much better!

**Comment by misolori** [comment]
This matches our guidance on when to use a modal dialog vs a toast notification and looks good to me! The only thing that is odd is the wording as I'm not sure if users would know what "dirty editors to backup" means? I don't know if going with "Backing up dirty files is taking longer than expected..." would improve it? It's a hard concept to communicate to the user.

**Comment by bpasero** [comment]
@misolori yeah so currently there are 3 possibilities:
* `Waiting for dirty editors to backup...`
* `Waiting for dirty editors to save...`
* `Waiting for dirty editors to revert...`

And the only time a user would ever see this is when an extension is installed that provides custom editors and where one of backup, save or revert is taking more than 800ms. 

I agree that the wording pretty much maps to the actual "thing" that the workbench is waiting on shutdown and is not very user friendly. 

I wonder if we actually need to call out the operation (backup, save, revert) or if we can show the same message in all cases? Open for suggestions on the wording.

**Comment by bpasero** [comment]
I went with this wording now:

**Backup**
![image](https://user-images.githubusercontent.com/900690/117252510-5ad84a00-ae46-11eb-9ff0-68f724342c78.png)

**Save**
![image](https://user-images.githubusercontent.com/900690/117252953-f073d980-ae46-11eb-94c3-97268a393adf.png)

**Revert**
![image](https://user-images.githubusercontent.com/900690/117252978-f8cc1480-ae46-11eb-8b53-15827ae79f4c.png)

**Comment by bpasero** [comment]
@Tyriar maybe you could verify this given your initial steps

**Comment by Tyriar** [comment]
So much better 👍
