### ISSUE TITLE
Not indenting label and option tags in HTML5

### ISSUE THREAD

**Issue by andreshg112** [Microsoft/vscode#12273]
- VSCode Version: Code 1.5.2 (66f37fd2a99eb9d628dd374d81d78835b410c39b, 2016-09-12T13:22:54.636Z)
- OS Version: Linux x64 4.4.0-36-generic

Steps to Reproduce:
1. Ctrl + Shift + I is not indenting labels or select options in HTML.

**Comment by chrmarti** [comment]
Could you provide an example and tell me what command you have bound to that key combination?

**Comment by andreshg112** [comment]
For example, this is my code:
![before indenting](https://cloud.githubusercontent.com/assets/15859884/18673007/e091dc44-7f0f-11e6-88c7-9e5cf30b1e22.png)

After indenting by Ctrl + Shift + I or Rigth Click/Format:
![after indenting](https://cloud.githubusercontent.com/assets/15859884/18673016/e565d1e4-7f0f-11e6-96a3-2d28e0e78ed6.png)

It can be seen that opening "label" tag takes its position, but the closing one does not.
Opening "option" tag doesn't take its good position.

**Comment by chrmarti** [comment]
Reproduced with the following html:
```
<html>
<body>
<label>
Some text.
</label>
</body>
</html>
```

**Comment by aeschli** [comment]
It's because 'label' is on the list of tags that should not be reformatted.
(see setting `html.format.unformatted`).
It hapens t be on that list as changing the content can result in change to the rendering of the HTML page (depends of course on the applied styles as well).
You can remove the element from the settings if you want.
