### ISSUE TITLE
Preferred kernel not selected by default

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#122860]
- VS Code Version: Insiders 
- OS Version: Mac

Steps to Reproduce:

1. Install latest insiders 
2. Install VS Code Jupyter extension
3. Open an empty workspace
4. Select Python interpreter and set to `xyz`
5. Create a blank jupyter notebook,
6. The kernel should be set to `xyz`

However its set to `Select Kernel` & when running a cell, user gets prompted to select a kernel.
User should not get prompted to select a kernel in this case (there are no other kernel providers, VS Code should just use the preferred kernel)

FYI - This is a regression & i understand you are in the end game

@jrieken @rebornix /cc

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by DonJayamanne** [comment]
Note: This doesn't just apply to new notebooks, but existing notebooks as well.
Hence existing users will now have to always select a kernel (whether its a new or existing notebook)

**Comment by IanMatthewHuff** [comment]
Going back to read the old thread here. I believe this change is intentional based on this comment here:
https://github.com/microsoft/vscode/issues/122415#issuecomment-829109276

It's actually good here that there is a distinction now between VS Code's selection and what items might be set as preferred. In that comment there are two cases listed:
1. Only one kernel available, none selected. Implicit selection happens so that kernel shows in the UI and 
2. Multiple kernels available, none selected. No kernel selected in status bar. Kernel picker is shown on execute. Preferred items get bumped to top of picker list

I believe our request to discuss here is the following:
3. Multiple kernels available, none selected, one preferred. Implicit selection happens so that the one preferred kernel is shown in the UI and is launched automatically without selection.
4. Multiple kernels available, none selected, > 1 preferred. No kernel selected in status bar. Kernel picker is shown on execute. Preferred items get bumped to top of picker list

This way if Jupyter does what we discussed (we always set just one preferred controller for documents) we get the behavior that we want where a customer can open a new blank notebook or pull a notebook from the internet and be able to click launch right away with our best guess as to a correct kernel. But it's still fair to the multiple extension cases where we don't get special priority if another extension is also setting a preferred controller.

I do get that from an API perspective this might be thorny. As extensions can add affinities on the fly. So having a UI difference between one preferred and many preferred might be difficult.

**Comment by DonJayamanne** [comment]
> 3. Multiple kernels available, none selected, one preferred. Implicit selection happens so that the one preferred kernel is shown in the UI and is launched automatically without selection.

Yes this is desired behavior.

> 4. Multiple kernels available, none selected, > 1 preferred. No kernel selected in status bar. Kernel picker is shown on execute. Preferred items get bumped to top of picker list

Yes this is desired behavior.

**Comment by jrieken** [comment]
> But it's still fair to the multiple extension cases where we don't get special priority if another extension is also setting a preferred controller.

Yeah, maybe fair but it likely encourages extensions to always mark their controllers a preferred. 

What concerns me most is the UX - how do users learn that there is a difference between multiple kernels and 1 preferred vs multiple kernels and 0 or 2+ preferred? Today the model is very simple: 1 kernel -> that's suggested, 2+ kernels -> pick one.

**Comment by DonJayamanne** [comment]
> Today the model is very simple: 1 kernel -> that's suggested, 2+ kernels -> pick one

Shouldn't it be 2+  from multiple extensions then pick one. 
Ie if only one extension is providing multiple, why should the user pick one when that extension is in control of all kernels.

It makes sense if there are multiple from multiple extensions, else to me preferred has very little value (just sorts stuff).

**Comment by DonJayamanne** [comment]
On a side note, I'm not sure how we're supposed to run any test at this stage.
We have > 2 kernels on our machines (& CI) & now all of them hang because of this prompt.

**Comment by jrieken** [comment]
>  else to me preferred has very little value (just sorts stuff).

Yes - that is exactly the only thing it is designed to do. 

I do hear you, having only 1 extension and only 1 preferred kernel with multiple other kernels makes sense but my worry is that it makes the UI confusing. How would users know that there are more kernels?

**Comment by DonJayamanne** [comment]
> Yes - that is exactly the only thing it is designed to do.

Not sure what needs to happen at this stage. We have a ux/workflow/functionslal (call it what you want) requirement and the api (from my point) should be designed to fit those needs. At least thats my opinion. Fyi, the product worked as expected for us for a few months as well, and now because or api change (which I would have thought is a change in code/names/structure were going back to square one)

 I'm getting the impression that you are designing an api and forcing us to change the ux to fit a technical limitation that you might feel is right. Or perhaps I'm mistaken here.

> How would users know that there are more kernels?

Isn't this a UX issue...
How do users know what they gave multiple git branches, might be a vet very poor analogy. But someone who doesn't know git at all and doesn't ever use the terminal weekend be in the same position. Why should main be the default. Because it's a convention.
Similarly when you share a notebook of you have that same kernel you don't need to pick it, just open and run. Again could be a very very poor analogy.

**Comment by DonJayamanne** [comment]
I think another example for this ux is languages picker, users don't know they can change this. To my knowledge this is a problem that's being (was) looked at in vscode. It's a ux issue.
I don't think we should give users to pick one even when the preferred is the right choice, 

eg when copying and pasting contents into a new untitled editor the language is auto selected. Should we force the user to select a language then)
I don't think so. Same here in Jupyter.

Again could be a very very poor analogy.

**Comment by DonJayamanne** [comment]
Another challenge we have today is with testing.
We have a lot of kernels on CI servers, generally around 4 , sometimes more , and we end up with prompts in each test when we run cells (with new temporary notebook files). The current work around (hack) is to executes the command that forces vscode to use the defined kernel Id. That had it's own problems, to be expected, as they are workarounds (that's what one gets with hacks).

This would  be a problem for other extension authors too, testing with multiple kernels. 

Changing our tests to have a single kernel, is going to take a lot of effort.

**Comment by DonJayamanne** [comment]
@jrieken after having seen some of the issues users ran into in diary study, i think the current behaviour is the right UX (discussed with @claudiaregio).

I'm closing this issue for now, as there's no point leaving this open.
