### ISSUE TITLE
Manage special defaults of the `virtualWorkspaces` property

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#122836]
Extensions have started to adopt the new Virtual Workspace capability: [Guide](https://github.com/microsoft/vscode/wiki/Virtual-Workspaces), [Tracking Issue](https://github.com/microsoft/vscode/issues/123115)

Until extensions have adopted the new capability, we came up with an internal list of extensions that we think should be disabled in virtual workspaces. The list that is reflected in product's project.json.

The issue is used to keep the list updated. We can remove extensions as a soon as they adopted the `virtualWorkspaces` property.

- [x] ms-python.python
- [x] ms-vscode.cpptools
- [x] dbaeumer.vscode-eslint
- [ ] esbenp.prettier-vscode
- [ ] msjsdiag.debugger-for-chrome
- [ ] redhat.java
- [x] eamodio.gitlens
- [ ] HookyQR.beautify
- [ ] ritwickdey.LiveServer
- [ ] VisualStudioExptTeam.vscodeintellicode
- [x] vscjava.vscode-java-debug
- [ ] octref.vetur
- [x] ms-azuretools.vscode-docker
- [x] vscjava.vscode-maven
- [x] vscjava.vscode-java-test
- [x] vscjava.vscode-java-pack
- [ ] formulahendry.code-runner
- [ ] felixfbecker.php-intellisense
- [x] vscjava.vscode-java-dependency
- [x] redhat.vscode-yaml
- [ ] felixfbecker.php-debug
- [ ] ms-mssql.mssql
- [ ] christian-kohler.path-intellisense
- [ ] eg2.tslint
- [ ] eg2.vscode-npm-script
- [ ] donjayamanne.githistory
- [ ] Zignd.html-css-class-completion
- [ ] christian-kohler.npm-intellisense
- [ ] EditorConfig.EditorConfig
- [ ] austin.code-gnu-global
- [x] ms-vscode-remote.remote-wsl
- [ ] johnpapa.Angular2
- [ ] ms-vscode.vscode-typescript-tslint-plugin
- [ ] DotJoshJohnson.xml
- [ ] techer.open-in-browser
- [x] DavidAnson.vscode-markdownlint
- [ ] tht13.python
- [ ] bmewburn.vscode-intelephense-client
- [ ] Angular.ng-template
- [ ] felixfbecker.php-pack
- [ ] dbaeumer.jshint
- [x] msjsdiag.vscode-react-native
- [x] Dart-Code.dart-code
- [ ] yzhang.markdown-all-in-one
- [ ] Dart-Code.flutter
- [ ] streetsidesoftware.code-spell-checker
- [ ] rebornix.Ruby
- [ ] ms-vscode.sublime-keybindings
- [x] batisteo.vscode-django
- [x] alefragnani.project-manager
- [ ] mitaki28.vscode-clang
- [ ] steoates.autoimport
- [ ] donjayamanne.python-extension-pack
- [ ] shd101wyy.markdown-preview-enhanced
- [ ] mikestead.dotenv
- [x] GrapeCity.gc-excelviewer
- [ ] pranaygp.vscode-css-peek
- [ ] ikappas.phpcs
- [ ] platformio.platformio-ide
- [ ] jchannon.csharpextensions
- [ ] gruntfuggly.todo-tree

**Comment by egamma** [comment]
Closing in favour of filing issues against the extension repositories //CC @aeschli

**Comment by rebornix** [comment]
@aeschli from the release note that it seems we generated list by checking if an extension is using `fs`. Do you have an idea how this will impact Vim. Vim's desktop version uses `fs` but it can work with a virtual file (`textDocument)

**Comment by egamma** [comment]
@rebornix @aeschli has started to update the guide https://github.com/microsoft/vscode/wiki/Virtual-Workspaces and there is more info available.

Just to share what I've found when I did the initial checking of the Vim extension. I found that it works OK, but I haven't tested all the features of Vim. From reviewing the code the extension already abstracts `fs` access in `src/platform/node/fs.ts` and uses `vscode.workspace.fs` where possible 👍 . However, `vscode.workspace.fs` is not used everywhere and it would be good investigate the impact of this in a virtual workspace setup and to handle it gracefully. For example, unlink is using `fs` directly.

**Comment by cyrilletuzi** [comment]
My [Angular Schematics extension](https://marketplace.visualstudio.com/items?itemName=cyrilletuzi.angular-schematics) is doing a lot of files/paths management, and trying to comply with the virtual workspaces guide made appear many things (being forced to use `Node` APIs because of missing methods on `Uri`, being forced to use `fsPath` in some place because of an issue with `path` in some scenarios, etc.). Where should I report these things?

**Comment by aeschli** [comment]
@cyrilletuzi You can find path like utilities in the `vscode-uri` node module: 
See https://www.npmjs.com/package/vscode-uri, section Usage: Util

**Comment by cyrilletuzi** [comment]
@aeschli Thanks, `vscode-uri` solved some of my issues.

1. Is there a reason some methods (like `joinPath()`) are directly available in `@types/vscode` while some others (like `dirname()` and `basename()`) require `vscode-uri`? Now that you explicitly require to not use Node APIs directly, it would make sense to include everything directly in `@types/vscode`.

Also, there is still some issues and missing features so I'm able to get rid of all Node APIs:

2. I need `path.relative()` a lot, and it doesn't exist in `vscode-uri`. Can it be added? It would work the same (2 `Uri`s as params, and returns a string representing the relative `path`).

3. #116298, which was not taken into account properly, should be reopened and fixed (otherwise I'm forced to use `.fsPath` in some places, as `.path` is buggy in some scenarios explained in the issue).

4. `vscode.workspace.createFileSystemWatcher()` only accepts a `fsPath` string, and not a `Uri` as all other VS Code APIs. Do you confirm it's intended and it can't be done with schemes other than `file`, and thus that extensions require a manual check (`if (uri.scheme === 'file')`)?

**Comment by aeschli** [comment]
Only one more adoption since July.  My guess is that given we provide the default, the listed extensions don't have any pressure to adopt.

I'll close this issue now and will make changes to our default on request.
