### ISSUE TITLE
Error when trying to open HTML file

### ISSUE THREAD

**Issue by apasternack** [Microsoft/vscode#12284]
- VSCode Version: 
- OS Version: El Capitan 10.11.6 (15G1004)

Steps to Reproduce:

1.  cloned this project from github: https://github.com/training4developers/intro-to-react
2. open the directory "intro-to-react" in VSCode
3. open "src" folder
4. open "www" folder
5. open "index.html" file, Error appears at the top "Unable to open 'index.html': An unknown error occurred. Please consult the log for more details.."

I cant find the error logs to help diagnose problem

**Comment by bpasero** [comment]
@apasternack I cannot reproduce.

I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by apasternack** [comment]
Thanks, When I restarted VSCode today the problem was not there.

**Comment by bpasero** [comment]
Ok please report back when it happens again and we reopen this issue 👍
