### ISSUE TITLE
typescript.tsserver.trace ignores typescript.tsserver.enableTracing

### ISSUE THREAD

**Issue by jscheel** [microsoft/vscode#122946]
- VS Code Version: 1.55.2
- OS Version: macOS 10.15.7

Steps to Reproduce:

1. Set `typescript.tsserver.trace` to `verbose` in settings.json
2. Set `typescript.tsserver.enableTracing` to `false` in settings.json
3. Edit a ts/js file. Tracing will still continue. This is problematic because `typescript.tsserver.enableTracing` is exposed as a checkbox in the settings editor, but `typescript.tsserver.trace` is not exposed in any meaningful way. This gives the impression that tracing is turned off, when in reality, it could be running. This primarily only affects users who have been told to set `typescript.tsserver.trace` for debugging purposes, but it's an important omission because verbose tracing can be a hidden resource drain.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
These two settings are unclearly named but are for difference things:

- `trace` — log all communications with TS Server to an output window
- `enableTracing` — Enables tracing on the TS Server side

I'd take a PR to rename them but as you note it's not a priority  since these settings aren't intended for users
