### ISSUE TITLE
Automatically open containing folder when opening a file

### ISSUE THREAD

**Issue by songhuadan88** [Microsoft/vscode#12297]
- VSCode Version: 1.5.2
- OS Version: Win 10

If I open a file by simply double click it, then the folder containing it will not be considered my workspace. Consequently, the configure file of some extensions for this folder does not work.

For example, I use spell check extension and add some ignore words to it. If I do not open folder, then the ignore words list does not work.

Do I have any method to open VS Code with folder mode as a default way, by simply double click the file?

**Comment by bpasero** [comment]
@songhuadan88 no currently not.

**Comment by songhuadan88** [comment]
@bpasero many thanks!

**Comment by hawkerm** [comment]
Yeah, it'd be great if there was a quicker way to open the containing folder, by either clicking on the folder shown next to the file name, right-clicking the file and having it as an option, or making the containing folder the default for the open folder dialog.

**Comment by sajaysurya** [comment]
I agree. It would be great if this feature could be added.

**Comment by songhuadan88** [comment]
@sajaysurya This feature has already been added. At least, I have been using it for months.
See the links below,
http://thisdavej.com/right-click-on-windows-folder-and-open-with-visual-studio-code/
https://github.com/Microsoft/vscode/issues/12147

**Comment by hawkerm** [comment]
@songhuadan88 yes you can start vscode into a folder, but the title and what is missing still is the ability to do this if you've opened a file instead from within VS Code.  I don't want to close VS Code and have to open the directory elsewhere, I may have changed my location since then.

It just needs to be easier to given the context of a file within the vscode editor, open vscode folder navigation to that location (either within the current instance or a new instance).

**Comment by bpasero** [comment]
We do this in some cases when we detect that a file is from a workspace that is VSCode specific (e.g. has a .vscode folder). No further work is planned though for it.
