### ISSUE TITLE
Borken color in typescirpt decorator, use token ":"

### ISSUE THREAD

**Issue by leaxoy** [Microsoft/vscode#12307]
- VSCode Version: Code - Insiders 1.6.0-insider (0a0bfedbc64ba8fd0c3e6f42befb200a0b36ffb0, 2016-09-20T06:05:07.843Z)
- OS Version: Darwin x64 16.0.0

Bad colorize in typescript.
1. use decorator. and use `:` in decorator values.
2. then color render will be broken
![](http://o8z0dg641.bkt.clouddn.com/QQ20160920-4@2x.png)

**Comment by chrmarti** [comment]
Will need to check if fixed by Microsoft/TypeScript-TmLanguage#257. @aeschli can I assign these to you? That larger fix seems to take some time before it will be available in a release.

**Comment by sheetalkamat** [comment]
decorator support is added in Microsoft/TypeScript-TmLanguage#257

**Comment by mjbvz** [comment]
This seems to have been fixed by the new TS grammar

![screen shot 2016-11-21 at 2 26 57 pm](https://cloud.githubusercontent.com/assets/12821956/20503198/7513b510-aff6-11e6-9f7d-2f19a8bfa75c.png)

@leaxoy please give vscode 1.7+ a try and let me know if you still see any syntax highlighting issues around decorators. Thanks.
