### ISSUE TITLE
IntelliSense does not work for object property functions

### ISSUE THREAD

**Issue by ishuvalov** [Microsoft/vscode#12306]
- VSCode Version: Code 1.5.2 (66f37fd2a99eb9d628dd374d81d78835b410c39b, 2016-09-12T13:05:12.065Z)
- OS Version: Darwin x64 15.6.0

Steps to Reproduce:

1. Consider the following code:
```js
(function(undefined) {
    MyView = Backbone.View.extend({
        secondFunc: function () {
            return;
        },

        mainFunc: function() {
            this.secondFunc()
        }
    });
})();
```

2. The Goto Definition, Peek Definition and other IntelliSense features are not working for ```this.secondFunc()``` call.

**Comment by joaomoreno** [comment]
@ishuvalov This is going to be **very** hard to get from the language service, because `this` isn't really bound to anything by semantically analysing the code. It's only due to the implicit knowledge of how `Backbone.View.extend` works.

You could try [using TypeScript](https://github.com/tastejs/todomvc/blob/gh-pages/examples/typescript-backbone/js/app.ts), you'd get those language features all the way.

**Comment by ishuvalov** [comment]
@joaomoreno Thank you for your comment! Let's omit Backbone
```js
(function(undefined) {
    var myObj = {
        secondFunc: function () {
            return;
        },

        mainFunc: function() {
            this.secondFunc()
        }
    };
})();
```

Still not working. I understand the difficulties of ```this``` context, but the feature could work just finding all symbolic definitions in the workspace (or even just a current file) and allowing user to choose from. This how Sublime Text 3 works.
Unfortunately the TypeScript is not an option for my project.

**Comment by waderyan** [comment]
@ishuvalov thank you for opening this issue. I have repo'd this with JavaScript language service 2.0.2. 

Sending this to the TypeScript team as they provide the JavaScript language service.

**Comment by waderyan** [comment]
This issue was moved to Microsoft/TypeScript#11072
