### ISSUE TITLE
Debug stopped working - getting Unbound Breakpoint -VSCode  1.56

### ISSUE THREAD

**Issue by davidkjackson54** [microsoft/vscode#123148]
I have a node.js app that runs as a command line.  
This has worked fine for some months and starting a "Javascript Debug Terminal" and setting breakpoints all worked fine.

Now, I run the "Javascript Debug Terminal" , set breakpoints and run the app and it displays  "Debugger attached" but all the breakpoints are showing "Unbound Breakpoint". and the app finishes and debugger disconnects.

The only recent change is that a new version of VSCode 1,56 went in a day or two ago. May or may not be related?

**Comment by connor4312** [comment]
You can apply `"trace": true` in the `debug.javascript.terminalOptions` user setting

**Comment by davidkjackson54** [comment]
Trace file has been emailed..

**Comment by connor4312** [comment]
It looks like Node.js is loading files from a different place (`~/.zowe/plugins/...`) than where you have written them (`D:/source/...`). This is an issue because TypeScript creates relative paths to source files, which we follow. To fix this you can:

- Use symlinks and the appropriate [nodejs flags](https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_can-i-debug-if-im-using-symlinks)
- Set the [`sourceRoot`](https://www.typescriptlang.org/tsconfig) in your tsconfig to an absolute path (the file:/// uri of your working or source directory most likely) so that these can be referenced.

**Comment by davidkjackson54** [comment]
Thanks for the quick response.   
Why might this now be required  as this has worked fine for the past number of months.    Iam pretty sure that I have done niothing in the past few days that may have introduced this (other than the upgrade to VSCode 1.56 that happened)
I have never previously had to specify sourceRoot.  
Has something recently changed in VSCode that has made this now necessary?

**Comment by connor4312** [comment]
I've not changed anything relating to source path resolution in the last release, and this fundamental mechanism (and potential problem 🙂) is quite old. More likely something else in your environment changed or updated.

**Comment by davidkjackson54** [comment]
I tried adding this:
"sourceRoot": "./src"
and then thiss:
 "sourceRoot": "file:///d:/source/zmf-cli-plugin/src"

recompiled and reran but it has made no difference. I still see Debugger attached the app finishes and debugger disconnect.  and in betwen the red breakpoint dot goes to "Unbound Breakpoint".

**Comment by connor4312** [comment]
You can use the `Diagnose Breakpoint Problems` to inspect further. Maybe you need to drop the `src`, or point to your `lib` folder.

**Comment by davidkjackson54** [comment]
I tried the inclusion of sourceRoot and recompiled and it made no difference. I see the sourceRoot location in the .js.map files. 

I do not know what Diagnose Breakpoint Problems is referring to nor can I find any references to it.

 I am going to wait and see if anybody else reports a similar issue as there seems to have been a host of reports of  "Unbound Breakpoints" in the past and this has been working for many months before now.

**Comment by connor4312** [comment]
`Diagnose Breakpoint Problems` is a command available in the Command Palette (F1) when a debug session is running. It has a helper tool and also lets you see all the paths js-debug knows about/is aware of.

Oh, also, you will probably want to set your `outFiles` in the launch.json to that `~/.zowe/plugins/` so that they resolve.

I wouldn't suggest waiting for other reports; currently there are not known issues with unbound breakpoints, past issues are either fix or were misconfigurations.

**Comment by davidkjackson54** [comment]
I tried using the `Diagnose Breakpoint` but it hasn't really helped:  I had already set sourceRoot to point to "D:/source/zmf-cli-plugin/src/" Yet it reports being unable to find the source file in the sub folder below src  in   /api/ComponentBrowse.ts 

✅ This breakpoint was initially set in:

D:\source\zmf-cli-plugin\src\api\ComponentBrowse.ts line 21 column 1

❓ We couldn't find a corresponding source location, and didn't find any source with the name ComponentBrowse.ts.

How did you expect this file to be loaded? (If you have a compilation step, you should pick 'sourcemap')
Loaded in directlyBe parsed from a sourcemap
Here's some hints that might help you:

**Comment by connor4312** [comment]
Can you grab a trace log with the outFiles set? Setting `resolveSourceMapLocations: null` will also have the same effect (allow the debugger to look at sourcemaps everywhere on the disk)
