### ISSUE TITLE
Improve settings UI for creating/deleting profiles

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#123169]
Should include a dropdown populated from the profileNames of the `terminal.integrated.profiles.platform`

**Comment by Tyriar** [comment]
Also proper controls for adding profiles would be cool

**Comment by Tyriar** [comment]
This is much more involved than anticipated, we basically need to create an "everything settings renderer" since there are no component-specific settings renderers by design, they're all general. So we'd need one that works with all the schema features profiles use (anyOf, inner `env` objects, etc.).

Closing this as we'll get it for free when it the settings ui feature is added.
