### ISSUE TITLE
Quick open / suggest foreground color messes up 3rd party themes

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#123113]
Probably broken by https://github.com/microsoft/vscode/pull/122893

My GitHub Sharp theme now looks like this:

![image](https://user-images.githubusercontent.com/22350/117294164-315bf600-ae27-11eb-886b-4b7b4dcb620c.png)

This is stable:

![image](https://user-images.githubusercontent.com/22350/117294378-7122dd80-ae27-11eb-9d93-4ce420b6c42c.png)

Does the change from the PR requires all 3rd party themes to adopt something?

**Comment by joaomoreno** [comment]
Same in suggest: 
![image](https://user-images.githubusercontent.com/22350/117298769-97974780-ae2c-11eb-9dba-c8f9cccf742b.png)

**Comment by misolori** [comment]
So we did introduce a couple of new color themes:
  - `list.focusHighlightForeground` which defaults to the current highlight color
  - `quickInputList.focusForeground` which defaults to `list.activeSelectionForeground`
  - `editorSuggestWidget.selectedForeground` which also defaults to `list.activeSelectionForeground`

I tested this in all of the top 50 themes and didn't see any clashes as most themes only theme the list widget colors (which is what the quick pick inherits from now). So in your theme because you have set colors for the quick pick & suggest widget you'll need to add a new color for `quickInputList.focusForeground` and `editorSuggestWidget.selectedForeground`. 

As an alternative, you can remove the `quickInput.list.focusBackground` and `editorSuggestWidget.selectedBackground` so that it will look just like the list focus state:

<img width="400" src="https://user-images.githubusercontent.com/35271042/117324065-4bf09800-ae44-11eb-8976-302bbe5ca299.png">

<img width="400" src="https://user-images.githubusercontent.com/35271042/117324212-704c7480-ae44-11eb-92c8-cf7038cf370f.png">

Let me know if that helps out.

**Comment by joaomoreno** [comment]
Thanks for double checking! I have updated GH Sharp.
