### ISSUE TITLE
Rename debug terminals if a second `runInTerminal` request comes in with a different name

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#123189]
See https://github.com/microsoft/vscode-js-debug/issues/990#issuecomment-833809419

I think the best way for this would be for VS Code core to rename the terminal if gets a new `runInTerminal` request with a different name -- opened an issue for that https://github.com/microsoft/vscode/issues/123189. Or, at least, try to use a terminal of the same name if one exists (which would be easier and probably more feasible since the `name` is not writable.) 

Code pointer: https://github.com/microsoft/vscode/blob/de4e9067e80f079f092006929dab05516e27c70e/src/vs/workbench/api/node/extHostDebugService.ts#L74

**Comment by isidorn** [comment]
Also fyi @weinand

**Comment by danielgary** [comment]
I'm going to take a swing at this.  Here is my current understanding of the problem and I would appreciate any feedback or comments.

The issue - Launching debug sessions in integrated terminal will open duplicate terminals.
Solution - Once microsoft/vscode-js-debug#991 is merged, code can attempt to find a terminal instance that has the same name and is not currently in use.  If located, it can reuse that instance, otherwise it can use the existing logic to create a new instance.


I believe this should also address the concerns in #63813 as Code will stop spawning new terminal instances for repeat debug sessions.

Please let me know if I have any misunderstandings on the issue.

**Comment by connor4312** [comment]
Sounds good to me

**Comment by danielgary** [comment]
I'm looking over the current code for checking out an integrated terminal and came across the minUseDelay for determining which of the terminals is available for use.  It was a fix for #71850.

As I understand it, when compound node tasks were run, they would all try to grab the same terminal instance so only the first one to run would actually get the terminal, the others would fail to run.  By introducing the minUseDelay, it insured that all of the launch tasks would get a new terminal instance.

Once microsoft/vscode-js-debug#991 is merged, each Node launch task will most likely have a unique name and therefore a dedicated terminal instance (ideally) which would mean we could always return the first terminal without a child process that has the same title and get rid of minUseDelay.  Right?

**Comment by danielgary** [comment]
Obviously if someone had two launch configurations with the same name (why?) this would fall apart.

**Comment by connor4312** [comment]
We could even enforce name-matching and reopen the terminal if nothing's running in it and the name mismatches
