### ISSUE TITLE
(node:20120) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues

### ISSUE THREAD

**Issue by kanlukasz** [microsoft/vscode#123180]
```
Version: 1.56.0
Commit: cfa2e218100323074ac1948c885448fdf4de2a7f
Date: 2021-05-04T22:09:06.405Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19042
```

Steps to Reproduce:

1. Open VSCode
2. Open Toggle Dev Tools

3.
```
[Extension Host] (node:6096) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.(Use `Code --trace-deprecation ...` to show where the warning was created) 
S @ console.ts:137
_logExtensionHostMessage @ localProcessExtensionHost.ts:514
(anonymous) @ localProcessExtensionHost.ts:282
emit @ events.js:315
emit @ internal/child_process.js:903
processTicksAndRejections @ internal/process/task_queues.js:81

```
screenshot version: 
![obraz](https://user-images.githubusercontent.com/30685349/117348755-de2b8700-aeaa-11eb-9d0e-8fb6c6b7b71d.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by JacksonKearl** [comment]
This does not appear to be a bug as much as an internal warning message.

**Comment by pedro-w** [comment]
@JacksonKearl I have also seen this when running `vscode-test` on an extension I'm developing. Are you saying for sure this is coming from VSCode itself? If so, I don't need to worry - otherwise if it's in my extension I need to find out how to pass that `--trace-deprecation` flag so I can track it down. Thanks!

**Comment by JacksonKearl** [comment]
@pedro-w you can try starting an empty extension to verify the source, I can't say for sure that it's VS Code in your case.

**Comment by kanlukasz** [comment]
This warning is from VSCode. Just run a clean and fresh portable instance to check it out

**Comment by supperchong** [comment]
The reason is that VSCode has dependency `vscode-proxy-agent`-> `get-uri`->`ftp`. [https://github.com/microsoft/vscode/blob/main/yarn.lock](https://github.com/microsoft/vscode/blob/main/yarn.lock) 
The [ftp](https://github.com/mscdex/node-ftp) is too old, it use new buffer() in [this line](https://github.com/mscdex/node-ftp/blob/master/lib/connection.js#L53) .Maybe it's better to change to other Module.
In addition，I add the code in bootstrap-fork.js to find out the warning position .
```js
process.on('warning', (warning) => {
    console.log(warning.stack);
});
```

**Comment by pedro-w** [comment]
Note there is already an issue filed on `ftp` for this: https://github.com/mscdex/node-ftp/issues/255 and a PR to fix it.

**Comment by supperchong** [comment]
@pedro-w yeah, but it hasn't been merged yet.
