### ISSUE TITLE
"Cannot back up in this state" hides underlying reason

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#123297]
I noticed that with Luna paint (cc @Tyriar) I was sometimes not able to quit with dirty state because Luna paint throws an error for backups of large images.

But this error never surfaces me, it is completely ignored here:

https://github.com/microsoft/vscode/blob/7d5b672eb7c0a1a6a95ae44194c333d20c7305c8/src/vs/workbench/api/browser/mainThreadCustomEditors.ts#L646-L646

The actual error there gives good information: `Error: Could not backup file as it's too large`

At the very minimum I suggest to print this error or add it to this one:

https://github.com/microsoft/vscode/blob/7d5b672eb7c0a1a6a95ae44194c333d20c7305c8/src/vs/workbench/api/browser/mainThreadCustomEditors.ts#L662-L662

**Comment by lramos15** [comment]
Ideally I also think the error surfaced to the user could be nicer, but this at least adds the error message to the throws.

**Comment by Tyriar** [comment]
Nice change, I'd prefer if it logged a warning instead of threw an error though. The giant stack trace makes using the console for debugging much harder.

> Ideally I also think the error surfaced to the user could be nicer, but this at least adds the error message to the throws.

Please no, it rejects backups by design as they block the main thread which makes for either a frozen webview or laggy mouse input. I created a few backup/auto save-related issues which will make this nicer already: https://github.com/microsoft/vscode/issues/113507, https://github.com/microsoft/vscode/issues/113705, https://github.com/microsoft/vscode/issues/115404, https://github.com/microsoft/vscode/issues/87282

**Comment by lramos15** [comment]
@Tyriar I just meant the wording. It gives the user no reason as to why we can't backup, just tells them to get rid of their dirty changes. Which I guess is fine and the solution.

**Comment by Tyriar** [comment]
I don't think the user should be informed, I guess unless it's something really subtle like an icon in the status bar
