### ISSUE TITLE
Replace WMIC call with a supported solution

### ISSUE THREAD

**Issue by danielgary** [microsoft/vscode#123296]
WMIC is deprecated and has been for some time.  Currently it is used for determining if any integrated terminal instances have any child processes.

https://github.com/microsoft/vscode/blob/25d1c0b0eba587f9f4e6bf825770b547c6703e52/src/vs/workbench/contrib/debug/node/terminals.ts#L55

There are PowerShell commands that can return the count of child processes given a parent process ID, but I'm not sure what the performance hit for using PowerShell would be.

**Comment by riverar** [comment]
Windows doesn't maintain strong parent/child process relationships, so the design here needs some more thinking.

If you're feeling gangster, you can call `NtQueryInformationProcess` with `PROCESS_BASIC_INFORMATION` and dig out the undocumented `InheritedFromUniqueProcessId` member.

But I wouldn't bother, because you then need to consider [the process ID can be recycled](https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-getprocessid?redirectedfrom=MSDN&WT.mc_id=WD-MVP-5002756#remarks) at any time.

**Comment by danielgary** [comment]
Thanks for all the help @riverar !
