### ISSUE TITLE
Numbers in Select Window dialog

### ISSUE THREAD

**Issue by Axatchaudhary** [microsoft/vscode#123236]
It would be helpful to see the numbers in the select window dialog. That way I'd be able to enter the number easily without having to select window by pressing arrow keys. It'd be helpful especially someone is working with many projects opened.

**Comment by sbatten** [comment]
I think this is more a general request for navigating the quick input

**Comment by TylerLeonhardt** [comment]
Can you send a screenshot of what you mean by "select window dialog" so I know for sure?

**Comment by Axatchaudhary** [comment]
@TylerLeonhardt here it is
<img width="1406" alt="Screen Shot 2021-10-04 at 4 06 12 PM" src="https://user-images.githubusercontent.com/7285865/135936304-890bafce-5446-48df-8eb5-dfc7655ca528.png">

**Comment by TylerLeonhardt** [comment]
Ah I see ok. I'm wondering if the description (the gray-er text like "Current Window") could include a number sorted by most recently used.

That way you can type `5` and the item that has the number 5 would be the only one left and you could hit ENTER.

The only challenge I see is that if a window has a number in it, then this entire experience breaks down...

We could skip any number that is contained in the names of the windows... but then what happens if we run out of those numbers? Start using special characters? I'm not sure it works.

Like imagine if I had a folder called `1234567890`. If I number the windows, then that folder will always show up.

We could _prefix_ the items but that just don't seem like it's in the spirit of the command palette.

Cc @bpasero in case you have come across asks like this in the past.

**Comment by Axatchaudhary** [comment]
> but then what happens if we run out of those numbers? Start using special characters? I'm not sure it works.

I think numbers could continue beyond 9 if that's the concern 🤔
