### ISSUE TITLE
Multi-byte entry crashes code

### ISSUE THREAD

**Issue by seanmcbreen** [Microsoft/vscode#12329]
- VSCode Version: ?
- OS Version: OS X

Steps to Reproduce:
See this tweet...
https://twitter.com/matt_porter_/status/778019210806951936

**Comment by M-Porter** [comment]
@seanmcbreen oh hey.

VSCode Version: 1.5.2 (66f37fd2a99eb9d628dd374d81d78835b410c39b)
OS Version: 10.11.5 (15F34)

**Comment by alexandrudima** [comment]
Sorry about the crash, it occurs because we end up splitting a high surrogate - low surrogate pair, thus having on our hands an invalid UTF16 string, which we then pass to `oniguruma`, which also contains a bug that I introduced in the cached UTF16 - UTF8 conversion where I ignore high surrogates that are lacking a low surrogate, whereas v8's handling of the conversion interprets it as a code point.

Ref: atom/node-oniguruma#56 . A PR is on its way, I'm looking forward to getting it reviewed, otherwise we might proceed to fork the project.

**Comment by M-Porter** [comment]
Awesome. Thanks for the explanation. Looking forward to being able to use vscode again.

**Comment by alexandrudima** [comment]
@M-Porter the PR just got accepted, as soon as there will be a new npm package, we will pick it up and the following day's insiders build will contain the fix.

**Comment by roblourens** [comment]
I verified that it's not crashing, although there are other issues like #12950
