### ISSUE TITLE
git stash clear

### ISSUE THREAD

**Issue by niem94** [microsoft/vscode#123375]
It would be nice if an option to clear all stashes could be exposed in the command palette, as it is really slow to do it in the command palette if there is more than one.

I suggest something like this utilizing the `git stash clear` command

![image](https://user-images.githubusercontent.com/26203420/117556727-437aa600-b06c-11eb-9db6-ed80896b12f6.png)

**Comment by niem94** [comment]
Happy to see this is something you decided to revisit. It is a small quality of life addition I most definitely will appreciate so I can use the command palette more consistently! :-)

**Comment by lszomoru** [comment]
Added with 302c41cf4e4c3de5afa8583f6da68248cea0ae86. Should be in next week's Insiders release.

**Comment by lszomoru** [comment]
Verification steps:
1. Open a folder/workspace that contains a git repository the does not have any stashes
2. Invoke the `Git:  Drop All Stashes...` command from the command palette
    - Confirm that a notification is displayed that there are not stashes in the repository
2. Change a set of files and create a new stash using the `Git: Stash` command
3. Repeat Step 2) couple of more times in order to have multiple stashes on the repository
4. Invoke the `Git:  Drop All Stashes...` command from the command palette
    - Review the warning message that is being displayed
    - Confirm that dismissing the dialog (Esc, or the `x`) will not result in the stashes being deleted
5. Invoke the `Git:  Drop All Stashes...` command from the command palette
    - Press the Yes button
    - Confirm that all stashes have been deleted
