### ISSUE TITLE
Bash script with embedded control M characters in strings becomes corrupted

### ISSUE THREAD

**Issue by tcobbs** [microsoft/vscode#123373]
- VS Code Version: 1.56.0
- OS Version: macOS 11.3

Steps to Reproduce:

1. Edit a bash shell script in Unix format (LF line endings) that contains CR characters embedded in strings.
2. Save the file.
3. Notice that the CR characters have been replaced with LF characters, thus corrupting the script and causing it to no longer function.

Does this issue occur when all extensions are disabled?: Yes

Edit the attached build_parts_catalog.txt in VS Code, then simply save without doing anything else. Then compare to the original file, and notice that the file is now different in ways that cause it to no longer function. (I doubt you can run the shell script, but if you just look at the result, you will be able to see that it will no longer function.)

[build_parts_catalog.txt](https://github.com/microsoft/vscode/files/6446694/build_parts_catalog.txt)

I understand that VS Code tries to fix line endings in files. However, a lone CR character in a string in a shell script is not intended to be a line ending, and is (correctly) not treated as a line ending by vim (for example).

**Comment by alexdima** [comment]
I acknowledge the problem. This was an intentional design choice in order to cover as many files on as many Operating Systems as possible, while having also happy lives :). The problem comes from using a multi-process architecture, with language servers written in other programming languages or by 3rd parties and with desiring to ship on multiple OS's.

VS Code often communicates with language servers using (line;char) based positions, so for example when triggering jump to definition on a symbol, the language server will typically return the URI of the file to jump to and the line number and character where the symbol is defined. The file to jump to is oftentimes not even loaded by VS Code until the actual jump occurs. But what exactly is a line? Well, sometimes even staying on the same platform can be problematic, as programming languages don't quite agree on what should be a line terminator, see https://github.com/microsoft/vscode/issues/96142 .

Although with serious drawbacks (like the one you run into of not being able to have a CR in a file/language where CR is not a line terminator), we have opted to recognize CRLF, CR and LF as line terminators indiscriminately in all files, irrespective of programming language and irrespective of OS. We do this in all processes and we have specified that to be our behavior such that language servers can build on our definition of what a line is and return consistent positions.

Again, this is not 100% correct and I am sorry about that, but this is not something we would want to address.
