### ISSUE TITLE
GWT extension not loading anymore

### ISSUE THREAD

**Issue by e01306821** [microsoft/vscode#123411]
- VS Code Version: 1.56.0
- OS Version: Linux

Steps to Reproduce:

1. Install extension: https://marketplace.visualstudio.com/items?itemName=TheUMLetTeam.umlet
2. Command palette -> "UMLet: Create new diagram" (or create file with file ending ".uxf")
3. Open file with VS Code
4. Result: Blank window

The extension is using [GWT](http://www.gwtproject.org/) which basically transpiles Java code to JavaScript. During the build process the GWT compiler creates a base script file which (among other things) eventually loads the actual application script. The base script file is embedded into the WebView as seen [here](https://github.com/e01306821/umlet/blob/vscode-fix/umlet-vscode/src/UmletEditorProvider.ts#L537). On load of the WebView we now get: "Failed to load resource: the server responded with a status of 404 ()" for the actual application script (the error is thrown inside the base script on the position where it appends a "script" node to the DOM with something like the following src: https://ee889b18-99bc-4576-9009-94ff5e68ae1a.vscode-webview-test.com/vscode-resource/file///(ommitted-repository-path)/umlet-vscode/target/umlet-vscode-14.4.0-SNAPSHOT/DA40FC4152E4DEE2669DCA0CA6C5BC6B.cache.js. It seems it is not able to retrieve it anymore although the path seems to be correct). For reference you can find the application running on the web [here](http://www.umletino.com/umletino.html).

**Comment by AllanOricil** [comment]
@e01306821 My extension also stopped to work on 1.56.0. But In my case it is not a problem loading resources. When I open the extension, the panel is blank. If I wait a random amount of time, the webview renders.

https://github.com/microsoft/vscode/issues/123281

**Comment by mjbvz** [comment]
@e01306821 The script that fails to load is being loaded inside an iframe without a `src`:

![Screen Shot 2021-05-10 at 4 18 31 PM](https://user-images.githubusercontent.com/12821956/117735953-6a8bc180-b1ab-11eb-80f9-c9c054b68bb9.png)

This seems to prevent it from being picked up by the service worker we use to load resources (and likely means it never worked with VS Code web)

My understanding is that service workers should work in this case (https://github.com/w3c/ServiceWorker/issues/612) but there may be bugs in browser implementations around it (or I may be misreading the spec)

Closing since I don't think we can fix this on the VS Code side. You can also try working around this by giving the iframe an explicit src such as `.` to force it into the same origin as the webview

**Comment by mjbvz** [comment]
Looks like it may be https://bugs.chromium.org/p/chromium/issues/detail?id=880768

**Comment by e01306821** [comment]
Thanks for the information. Unfortunately the proposed workaround of adding `.` as src to the iframe did not work, the issue remained.
