### ISSUE TITLE
Can not copy in File using Ctrl + C

### ISSUE THREAD

**Issue by TrangNguyen1004** [microsoft/vscode#123414]
Issue Type: <b>Bug</b>

I can not copy or cut in editor File using Ctrl + C or Ctrl + X. I don't know why this problem happened.

VS Code version: Code 1.56.0 (cfa2e218100323074ac1948c885448fdf4de2a7f, 2021-05-04T22:09:06.405Z)
OS version: Windows_NT x64 10.0.10240
Remote OS version: Linux x64 5.4.0-70-generic
Remote OS version: Linux x64 3.10.0-1160.15.2.el7.x86_64

**Comment by JacksonKearl** [comment]
Can you try running `Developer: Toggle Keyboard Shortcuts Troubleshooting` in the command palette and including the results? Also, try seeing if the issue reproduces when all extension are disabled (`Developer: Reload with Extensions Disabled`). If it does not, the problem is likely with an extensions, and you can narrow it down with `Help: Start Extension Bisect`
