### ISSUE TITLE
Wrong Token color when instantiating a new class

### ISSUE THREAD

**Issue by giulianoSev** [microsoft/vscode#123670]
- VS Code Version: 1.56.0
- OS Version: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Open a typescript file. 
2. Declare a class and create new instance like in the image below
3. Notice that "Example" takes a new color (yellow). Before this update it would keep the green color, just as the class declaration.
4. Theme Dark+ 
5. Semantic highlighting off

Does this issue occur when all extensions are disabled?: Yes

![image](https://user-images.githubusercontent.com/13419428/117971169-e5fe8780-b2ff-11eb-8ac8-3249e5bb2158.png)

**Comment by mjbvz** [comment]
This is because you disabled semantic highlighting, which is how we know that `Example` in `new Example` is a class

This is what is looks like with semantic highlighting enabled:

![Screen Shot 2021-05-19 at 12 26 01 PM](https://user-images.githubusercontent.com/12821956/118872421-693e5100-b89d-11eb-9c5a-5e48610ba190.png)

**Comment by giulianoSev** [comment]
@mjbvz yeah I know that with semantic highlighting it is green but this was working with it disabled in previous versions
