### ISSUE TITLE
Pop up for `Developer: Inspect Editor Tokens and Scopes` doesn't exit.

### ISSUE THREAD

**Issue by tej1996nitrr** [microsoft/vscode#123610]
- VS Code Version:  1.55.2
- OS Version: MacOs  Catalina version 10.15.7

Steps to Reproduce:

1. I have added a  keyboard shortcut  for `Developer: Inspect Editor Tokens and Scopes`
2. Open a jupyter notebook. Use the shortcut for above. 
3. On hitting `esc` or switching to different files doesn't make the popup go away.
4. Even on opening settings etc. it remains as it is.
5. Maybe related to python extension- not sure.

<img width="1036" alt="image" src="https://user-images.githubusercontent.com/27068830/117884726-99e52000-b2ca-11eb-8fc1-a52771bc1555.png">
<img width="1036" alt="image" src="https://user-images.githubusercontent.com/27068830/117884760-a5d0e200-b2ca-11eb-90ae-189688c00d35.png">

<img width="1036" alt="image" src="https://user-images.githubusercontent.com/27068830/117884645-820d9c00-b2ca-11eb-8273-9ebdf2c84d23.png">

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by rebornix** [comment]
The tokenizer inspector listens to keyup of escape to hide the token view, while in the notebook, escape is bind to a command, which is invoked and blurs the code editor.

**Comment by greazer** [comment]
I'm unable to view the tokens/scopes window at all in a Juptyter notebook (ipynb). I do see the window if I open a regular text file. Perhaps the fix for this broke the ability to see the window at all? 

Version: 1.61.0-insider (system setup)
Commit: 83b7d33abba1fbc9ba6dbf25b53b47821086b22f
Date: 2021-09-30T19:00:07.102Z
Electron: 13.5.0
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22468

**Comment by alexdima** [comment]
The fix was to disable the Tokens inspector inside Notebooks. The Tokens inspector is mainly used by authors of language grammars or authors of themes, or users that want to fine-tune their color definitions for a certain language. They can all continue using regular full-page editors to inspect tokens. This was not a scenario meant for Notebook editors.
