### ISSUE TITLE
Implement Hit Condition UI for breakpoints

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#12373]
`SourceBreakpoints` and `FunctionBreakpoints` support an optional `hitCondition` attribute which controls how many time a breakpoint has to be hit in order to 'break' execution.
Since a debug adapter is free to decide what kind of hit expressions to accept, the `hitCondition` is of type string.
This makes the attribute very similar to the already existing `condition` attribute of the breakpoint types and suggests that the UI for editing this new attribute aligns with the UI for editing breakpoint conditions.

The corresponding debug protocol addition:  https://github.com/Microsoft/vscode-debugadapter-node/issues/37
And the implementation for node-debug: https://github.com/Microsoft/vscode/issues/12374

**Comment by isidorn** [comment]
Fixed via 134a1ec

![breakpoint](https://cloud.githubusercontent.com/assets/1926584/19069475/69fd0ff4-8a27-11e6-9ceb-408a46f4f0d1.gif)

**Comment by isidorn** [comment]
@weinand This is done for regular breakpoints. We have an open question on what to do for function breakpoints - since they do not have a representation in the editor. So far we have also not exposed in the ui how to add a regular condition for function breakpoints.
There are a couple of options:
* somehow we start representing function breakpoints in the editor gutter - thus specifying the condition / hit count is the same as for regular breakpoints
* we add context menu actions in the breakpoints pane for editing a function breakpoint, this actions could then trigger the same experience as for regular breakpoints - though where to render the widget now - since function breakpoints have no line number
* add context menu acitons in breakpoint pane which would just open a native electron input box for specifying the condition, and another one for specifying the hit count

Let me know what you think
