### ISSUE TITLE
Interrupt button missing from running cell when toggling between notebook and another file

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#123830]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Insiders
- OS Version: Mac

Steps to Reproduce:

1. Install Jupyter extension
2. Run a cell (long running cell, e.g. a loop)
3. Watch the cell execution & output
4. Open another file
5. Go back to the notebook
You'll notice the `interrrupt` button is missing (so is the execution time in statusbar).

@rebornix @roblourens /cc

![running](https://user-images.githubusercontent.com/1948812/118199234-7378cf00-b407-11eb-9c31-ab48681eb64f.gif)

**Comment by roblourens** [comment]
I can't repro this. Can you try again in the latest Insiders?

**Comment by DonJayamanne** [comment]
Yup, I can still see this, the `Interrupt` button is missing, the `Run` button appears against the cell instead of `interrupt`.

**Comment by roblourens** [comment]
Can we debug together some time? Still can't see it.

**Comment by grudloff** [comment]
Hello @roblourens , I believe I am experiencing the same issue on Windows (more info on issue #5877). For me, this happens only when switching/opening files under the open directory and also when switching between terminal tabs (Terminal, Debug, output, problems, etc).

If you look closely to @DonJayamanne gif, all the executing cell animations are missing (stop cell button, cell running time, cell running icon (circulating arrows), and the blue bar sliding on top), the cell running icon shows just because of the printing, otherwise, it would show no sign of it running. 

Please let me know if I can provide more info that could help you solve this in any way.

**Comment by DonJayamanne** [comment]
Bug in the Jupyter extension, I'll fix it there.
