### ISSUE TITLE
Native Notebooks - Outline selection does not go to top

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode#123828]
**Steps to Reproduce:**

1. Open notebook
2. Select a cell in the notebook outline

**Actual Behavior:** 

Cell selected ends up ~middle of the window/notebook + doesn't have any selection on the cell that was picked so it's hard to identify where it is. 

**Expected Behavior:**

Cell to be at the top + selected mode indicator

**Comment by claudiaregio** [comment]
Couldn't find the original issue and thought that I forgot to file it but turns out it was closed. https://github.com/microsoft/vscode/issues/123175

Received customer feedback (4/4) in interviews that they expected selecting a cell in the table of contents would bring the cell to the top and currently they have a hard time identifying where the cell is. 

(I have also struggled with this same issue, when I click on a cell in the outline I find my eyes scattering to figure out where the cell actually is)

**Comment by rebornix** [comment]
@jrieken not sure if we want a different experience in notebook.

**Comment by greazer** [comment]
Some thoughts here:
- Markdown is typically used in a notebook to separate logical blocks of cells. It would seem to make sense to be able to see as much of that logical set of cells as possible when navigating to it. With a regular text editor seeing code context around the navigation point can make more sense.
- Jupyter's behavior is to scroll markdown to the top.
- It's unclear what would be appropriate if Show Code Cells for outline view is on and the user clicks on a piece of code in the outline view. Scrolling to the middle or top of the screen doesn't necessarily seem right. What about scrolling such that the cell that contains the piece of code is set at the top of the workbench window and the selected piece of code is highlighted temporarily? Of course we'd have to deal with large cells where the selected line appears below the bottom of the editor window. In that case, scrolling the code to the middle of the screen makes more sense (now you're more in the editor mode in this situation). Most notebooks do not contain large cells; however.

**Comment by greazer** [comment]
I'd also point out that the current behavior is quite buggy, which doesn't help. If you open this notebook and use breadcrumbs or the outline view to navigate the markdown, you'll easily run across them. I.e. sometimes the selected markdown is up off the top of the viewport (possibly because a cell is large below it), you'll also sometimes see headers getting rendered and then erased.

https://github.com/greazer/covid-19-data/blob/master/SampleNbsAndScripts/my-analysis-plotly.ipynb

**Comment by greazer** [comment]
This is still bothersome. And I also noticed that the scroll position for notebooks when clicking on one of the outline items is further down vertically than even regular code:

<img width="761" alt="image" src="https://user-images.githubusercontent.com/11685408/154859611-d5a00f30-1065-452d-bac4-37cd30f4ba1f.png">

<img width="761" alt="image" src="https://user-images.githubusercontent.com/11685408/154859541-9f06f0e9-d109-4340-96fb-b0d22eaa0c23.png">

I still think that when any item is clicked in a notebook outline it should be scrolled to the top as it's not likely that prior code/cells will be interesting to see in context. But barring that, the scroll position should at least be identical to that of pure code.

**Comment by claudiaregio** [comment]
I know I filed this issue but just wanted to add this is actually why I don't use the TOC in the notebook. It doesn't actually help me find where I am in the notebook, my eyes end up scattering all over the page to find where I am anyway

**Comment by rebornix** [comment]
From all feedbacks above, there seem to be three issues:

* Hard to find the focused/selected cell. We have added the focus indicator on the gutter since the original issue was created. 
* Cell top is revealed to the viewport center. Instead we should try to reveal the middle of the cell to the viewport center. I have pushed a fix for it, see below screen recording
* Lastly, if we should always reveal focused/selected cell into the top of the viewport. The reasoning behind this can be that notebook cells are richer and the focused cell is less noticeable compared to active line in a text editor (especially when there are outputs in the view). It's not just TOC as you get the same behavior when clicking on cells on problems panel, debug view, etc. It makes sense to me but I'd love to wait a bit for more feedback before making this significant change.


https://user-images.githubusercontent.com/876920/160461022-24373dc0-59a6-48c6-8275-9ce0cc29d9a3.mov

**Comment by claudiaregio** [comment]
@rebornix Thanks for the update! I can't tell in your recording if the gutter indicator is...passive or active? (I'm probably labeling that wrong) 

What I call passive (gray):
![image](https://user-images.githubusercontent.com/19276747/160462986-41c5c8b4-e4d5-4e0d-bf01-eca032165229.png)

vs.

What I call active (blue): 
![image](https://user-images.githubusercontent.com/19276747/160463087-66c9531b-f48b-4cae-a55d-070c3af91e8b.png)

I was really hoping to see "active" since there is so much more gray on the canvas and it is so delicate I don't end up seeing the gutter indicator, the blue has enough contrast to where I can see it clearly and quickly

**Comment by rebornix** [comment]
@claudiaregio passive colors are meant to the "passive" but you can always update the color to something stands out by tweaking `notebook.inactiveFocusedCellBorder`

**Comment by claudiaregio** [comment]
Oh perfect, thanks! I'll go ahead and update that

**Comment by greazer** [comment]
Please note that Google Colab also scrolls to the top. Note that I'm not sure why the "Setup" navigation at the beginning of this animation does NOT scroll to the top. I couldn't repro the behavior. May just be some bug.

![Recording 2022-04-15 at 13 27 03](https://user-images.githubusercontent.com/11685408/163629050-43880f8b-2ea6-482e-87ef-d70c7faa2c91.gif)

**Comment by kieferrm** [comment]
The behavior across our different editor types should be the same.

**Comment by greazer** [comment]
IMHO, perusing notebooks is a different workflow than perusing code. Code does not have markdown headers that signify the beginning of a new "investigation" or "section". There's much less need to be able to see prior context when perusing a notebook than there is with code.

**Comment by roblourens** [comment]
Verification steps - clicking a cell in the outline that is out of the view should reveal that cell at the top 5th of the viewport. If already in the viewport, it just focuses the cell. Same behavior as the text editor outline.

**Comment by lramos15** [comment]
![Recording 2022-06-01 at 12 23 03](https://user-images.githubusercontent.com/4544166/171453026-f2dbe7be-1d07-42e4-a962-6794381ed0c6.gif)
See gif. When I select feature request missing labels I would expect it to scroll so the entire cell is in view. Only a very small sliver of the header is showing I wouldn't call that in the viewport. You can see when I scroll away it does what is expected.

**Comment by roblourens** [comment]
Thanks. I think I just want to compare elementBottom to wrapperBottom here: https://github.com/microsoft/vscode/blob/3e8d674698b814e2d65bc206b9c19926655e4519/src/vs/workbench/contrib/notebook/browser/view/notebookCellList.ts#L1244

but I will fix in June since that will affect many reveal scenarios.

**Comment by roblourens** [comment]
Maybe it's not a big deal
