### ISSUE TITLE
A subst drive is now ignored

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#12385]
- VSCode Version: 1.6.0
- OS Version: Windows

Steps to Reproduce:

1. subst a drive (e.g. subst p: c:\users\xxxx\Projects)
2. open code from the subst drive

Observe: all paths shown in the UI are 'real' paths not the one from the subst drive.

**Comment by bpasero** [comment]
Ever since we updated node.js with our electron update it seems that fs.realpath is now returning the path as it is pointing to and ignoring the subst portion of it.

I am not sure we can fix this though because even if we do not realpath inside the workbench, an extension might still decide to realpath and we would end up with inconsistent paths travelling in and out.

**Comment by bpasero** [comment]
This is https://github.com/nodejs/node/pull/7559

**Comment by bpasero** [comment]
Unfortunately it does not look like Electron will be releasing a version with the newer node.js version because node.js chose to also pick up a newer V8.

**Comment by bpasero** [comment]
Should be fixed since I pushed the electron update, please verify.
