### ISSUE TITLE
Default delay for custom hovers

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#123851]
I find the new custom hover over activity icons appearing too fast. Compared to e.g. Slack.

![recording](https://user-images.githubusercontent.com/900690/118229415-40c4ea00-b48c-11eb-8a27-7fbed1afa412.gif)

**Comment by misolori** [comment]
It seems slack has a ~2s delay vs ours being instant? I'm impartial but would assume we'd want a setting to allow others to control this?

**Comment by bpasero** [comment]
How about picking the delay that the OS has for native hovers?

**Comment by misolori** [comment]
I think one of the reasons we wanted to use custom hovers here was that the native ones appeared too slowly, so that would defeat that purpose. I think a slight delay like other web apps, ~2s, is a great default to start with.

**Comment by sandy081** [comment]
It was an ask from PM (@digitarald) team to make it instant. Current delay is 150ms but if it is too aggressive, I do not mind changing it to a bigger number.

**Comment by digitarald** [comment]
@sandy081 I had a similar conversation with @kieferrm. One idea was to make it appear slower, but combine it with #122226 to ease exploration of icon sets. The result would be that new users can hover briefly to trigger the tooltip and then get an instant tooltip when moving from one to the next icon. Experienced users will not trigger any tooltip as they don't hover longer.

What that timing could be: Nielsen has some practical research on [timings for exposing content] (under _Timing Guidelines_)(https://www.nngroup.com/articles/timing-exposing-content/) and recommends 300-500ms for revealing content on hover. Should we go with 500ms and see how it feels?

**Comment by sandy081** [comment]
Changed the delay to 500ms. Lets see how it goes.

**Comment by misolori** [comment]
Seems like the latest default change to 500ms has been a little slow (see #128672). IMO, the reason why we wanted to go with custom hovers here was because they would appear faster than native hovers and it seems like now we've gone back to that native timing, which I think defeats the purpose of the hovers. We know from user studies that many people don't wait around for tooltips to appear.

**Comment by digitarald** [comment]
> I've personally been using 300ms (which feels like a good amount) so I never noticed the change to the default

Same issue here. I had mine set to 500, which is why I didn't notice the 1500 that was applied for OSX. Following native does defeat the purpose to give snappier feedback.

Testing `300` vs `500`, `300` would also be my preference but I'd be also fine with 500 if we want to be more defensive.

**Comment by sandy081** [comment]
At present it follows the default workbench hover delay setting workbench.hover.delay which defaults to 1500ms. We also have editor hover delay setting editor.hover.delay that defaults to 300ms. I do not want to introduce another setting for activity bar/panel hover delay. IMO it shall be consistent across workbench, and not like some hovers appear faster and some slower.

**Comment by Tyriar** [comment]
The whole point of these hovers imo was to make them unobtrusive (mouse over is always disabled) and show up quickly to help discoverability, similar to the pattern used in others apps. Also not everything needs to be configurable.

See https://github.com/microsoft/vscode/issues/118077

> I think one of the areas that could benefit from quicker tooltips/custom hovers is the activity bar as it is a frequently used area and **the native tooltip takes too long to load**. We've seen this in user studies where new users are not sure what these items are and don't click on them.

**Comment by misolori** [comment]
Seems like we should at least have all of our hover delays match at the minimum:

<img width="447" alt="CleanShot 2021-07-16 at 08 14 30@2x" src="https://user-images.githubusercontent.com/35271042/125970098-7a055780-fd40-4bab-a6c9-edc201915a6b.png">

**Comment by sandy081** [comment]
Let me know if there are any objections to use the min delay `300ms` for all above hovers?

**Comment by Tyriar** [comment]
Doesn't mac's delay of 1500 align with platform conventions and we have a lower number for the others for discoverability (sash) and consistency within the editor?

**Comment by digitarald** [comment]
> Doesn't mac's delay of 1500 align with platform conventions

I'd argue that context matters for picking the right delay (vs OS default). Even macOS has variations for critical UI elements, like tooltips on the dock or the screenshot hovers in Safari.

**Comment by sandy081** [comment]
Changed the title to reflect the discussion and assigned to @Tyriar as he owns the custom hovers

**Comment by Tyriar** [comment]
The status bar should probably also be shown faster than the general hovers like activity bar/panel.

**Comment by theterminator92** [comment]
I have been using VS Code since the `"window.titleBarStyle": "native",` was implemented. The reason why I have it enabled is because I don't want the custom titlebar, the custom context menu, and the custom hovers. 

I specifically hate these new hovers because they are doing exactly what the native hover are for, with the time the native hovers have, they all behave exactly the same, and all the apps on my computer will behave exactly the same. 

Even if you think you desperately want to have buttons and images in the some of these hovers so that you could put cool things, or experiment on users, I don't want these. I want simple native tooltip hovers that work exactly the same in all the apps that I use. 

I have signaled that by putting `"window.titleBarStyle": "native",`, meaning, give me a way to disable everything non-native. 
I would like to request the vscode team provide a backward compatible hover, so that the parts that only have simple text showing up, will use the native hover, and all the other parts that desperately need the custom hover for whatever reason, can be turned off. I don't need the fancy stuff, I just want the hover to be like it was before. 

I especially hate the sidebar and the terminal hovers. I don't know how to explain why, I simply hate it. I would like to keep vs code updated because of bugfixes, but the hover will forever make me stick the last version that they were working. 

I don't need to have the new features, just keep the old native hover with simple text and allow users to turn the new ones off if they want! Please give choice!

**Comment by Tyriar** [comment]
@theterminator92 a relevant comment for you https://github.com/microsoft/vscode/issues/129307#issuecomment-888563155

For the terminal hover do mean the link one?

![image](https://user-images.githubusercontent.com/2193314/127384521-d761ef49-a12d-4b34-8f32-d80c2f79bcdd.png)

This aligns with the editor's hover:

![image](https://user-images.githubusercontent.com/2193314/127384583-c430f7ca-ec9d-4646-8180-27a13880f963.png)

**Comment by misolori** [comment]
@Tyriar are we still keeping the `1500ms` default delay for this release?

**Comment by Tyriar** [comment]
@misolori yeah I think this needs more discussion. It's not as bad now that you just have to wait for the initial hover and then there's no delay moving between the headers/icons

**Comment by frederikhors** [comment]
Please 300 is too speedy and annoying, can you please use a default of 600?

**Comment by PEZ** [comment]
@sandy081 

> Let me know if there are any objections to use the min delay `300ms` for all above hovers?

The 300 ms for `editor.hover.delay` is way too short, IMO. As someone who screen share a lot with VS Code users, I know this is a common frustration. Letting them know that it can be changed in settings always render massive amounts of gratitude. I suggest 1300 as the default there, which is what I have been using for a long time. It's like having hovers on demand.

**Comment by legomushroom** [comment]
I've tested this today on stable 1.95.3(f1a4fb) Windows 11 and the delay feels very similar to the one that Slack uses now(based on the attached gif), so closing as fixed. Please reopen if you think that the issue still exists 🤗
