### ISSUE TITLE
extension test runner swallows error thrown by the tests entry point (e.g. test/suite/index.js) run() method

### ISSUE THREAD

**Issue by viktomas-gitlab** [microsoft/vscode#123882]
Does this issue occur when all extensions are disabled?:  No (it's extension development related)

- VS Code Version: starting with 1.48.0
- OS Version: Happens on both MaOS (v10.15.7 (19H1030)) and Linux

This issue seems to be discussed and closed over a year ago https://github.com/microsoft/vscode/issues/80757

Steps to Reproduce:

1. generate a new extension `npx yo generator-code`
2. replace the `src/test/suite/index.ts` with:

    ```ts
    export function run(): Promise<void> {
        return Promise.reject(new Error('issue'));
    }
    ```
3. when you run the tests (`npm run compile && npm test`) you see tests failing, but not the reason.

    ```
    Exit code:   1
    Done
    ```

4. It's incredibly hard to find where the problem is

I found this issue when my test code had incorrect require paths. The tests were failing, but because the issue wasn't `mocha` test issue, it didn't get reported to console and was returned as rejected promise in the `run()` method.

This issue was introduced in 1.48.0. The 1.47.3 version reports the error message (`issue` from the example above).

This is a change that has been introduced in `1.48.0` and is my personal tip on what causes the issue: https://github.com/microsoft/vscode/commit/a5d3d4fae61816937d4a14ea911bb24c011e518c?branch=a5d3d4fae61816937d4a14ea911bb24c011e518c&diff=split#diff-e0655f05d92d765070825b29075ea3abdfca206019cd490d8ef63d81b034913eR588-R593

I see that the original fix for the issue was to add `console.log` to each newly generated extension: https://github.com/microsoft/vscode-generator-code/commit/f846ab539aac2677224cf90d991661e2a7ed6e24

Ignoring errors thrown by the test code should be opt-in. The current state is "ignore by default" which makes for really tricky debugging, especially if your extension didn't use the generator to create its test suite.

I'd be keen on trying to fix it if the core team is interested and if someone can point me to documentation that explains how to run 3rd party extension tests using the VS Code build from source in debugging mode.

**Comment by alexdima** [comment]
@viktomas-gitlab IMHO this has nothing to do with https://github.com/microsoft/vscode/commit/a5d3d4fae61816937d4a14ea911bb24c011e518c?branch=a5d3d4fae61816937d4a14ea911bb24c011e518c&diff=split#diff-e0655f05d92d765070825b29075ea3abdfca206019cd490d8ef63d81b034913eR588-R593

@aeschli Here is what I see:
* `npm run test` executes `runTest.ts`
* `runTest.ts` contains a big catch block that does not log the error anywhere:
* 
![image](https://user-images.githubusercontent.com/5047891/121195391-d7a87a80-c86f-11eb-8c90-55af12606667.png)
* the console output from the `catch` block appears in the terminal:
* 
<img width="650" alt="Screen Shot 2021-06-08 at 15 40 53" src="https://user-images.githubusercontent.com/5047891/121195527-f6a70c80-c86f-11eb-9878-b91f85ff60c0.png">

I think the error caught in `runTest.ts` should not be swallowed.

**Comment by gitlab-vscode** [comment]
@alexdima Thanks so much for looking into this issue!

The code in `runTest.ts` can't be (AFAIK) responsible for swallowing the exception, because the `runTests` method from `vscode-test' only spawns a new VS Code process and this newly spawned process swallows the exception as described in this issue description.

In other words, if I'd add `console.error(err)` to the code from your screenshot, the output will change to

```
Exit code:   1
Done

Failed
Failed to run tests
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

where the line containing only "Failed" is the result of the `console.error()` call.

I created an example repo: https://gitlab.com/viktomas/tmp-extension-test/-/commits/master/

1. first commit ([init](https://gitlab.com/viktomas/tmp-extension-test/-/commit/c808f5300005467fcf9ea6ecc641b319893ee55a)) commits the extension as created by `npx yo generator-code`
2. second commit ([Create an error outside of test code](https://gitlab.com/viktomas/tmp-extension-test/-/commit/46fa8ff924095170f15ca4808144650fd5a5f908)) creates an exception that doesn't get reported (this is the bug described in the issue description)
3. thrid commit ([Adding console.error to the runTest doesn't help](https://gitlab.com/viktomas/tmp-extension-test/-/commit/26d1773f91d4e6b3dda215cb760802cb1ce3cd81)) adds the `console.error()` statement as explained above.

**Comment by viktomas-gitlab** [comment]
@alexdima Thanks so much for looking into this issue!

_(and sorry for double message, I used a wrong account)_

The code in `runTest.ts` can't be (AFAIK) responsible for swallowing the exception, because the `runTests` method from `vscode-test' only spawns a new VS Code process and this newly spawned process swallows the exception as described in this issue description.

In other words, if I'd add `console.error(err)` to the code from your screenshot, the output will change to

```
Exit code:   1
Done

Failed
Failed to run tests
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

where the line containing only "Failed" is the result of the `console.error()` call.

I created an example repo: https://gitlab.com/viktomas/tmp-extension-test/-/commits/master/

1. first commit ([init](https://gitlab.com/viktomas/tmp-extension-test/-/commit/c808f5300005467fcf9ea6ecc641b319893ee55a)) commits the extension as created by `npx yo generator-code`
2. second commit ([Create an error outside of test code](https://gitlab.com/viktomas/tmp-extension-test/-/commit/46fa8ff924095170f15ca4808144650fd5a5f908)) creates an exception that doesn't get reported (this is the bug described in the issue description)
3. thrid commit ([Adding console.error to the runTest doesn't help](https://gitlab.com/viktomas/tmp-extension-test/-/commit/26d1773f91d4e6b3dda215cb760802cb1ce3cd81)) adds the `console.error()` statement as explained above.

**Comment by alexdima** [comment]
> the runTests method from `vscode-test' only spawns a new VS Code process and this newly spawned process swallows the exception as described in this issue description.

You're right! Sorry, I forgot what `vscode-test` is doing.

**Comment by viktomas-gitlab** [comment]
Thank you @alexdima for fixing the issue 🙏👏

**Comment by aeschli** [comment]
The error is still not printed on `npm run compile && npm test`.
The problem is that the `console.error` at
https://github.com/microsoft/vscode/blob/5aa157097611d79d47fb0d557e9875ec372353e1/src/vs/workbench/api/common/extHostExtensionService.ts#L558
and
https://github.com/microsoft/vscode/blob/a3d47b0b3decb6c7faaac1d7a82310bf9ab76728/src/vs/workbench/services/extensions/common/abstractExtensionService.ts#L521 
don't make it to the main console.

Works when running from sources, but there's all a bit differently wired.

I also tried if adding a `this._logService.error(error);` makes a difference, but also not.

What might be bes, is to pass the error along with `_onExtensionHostExit`

**Comment by aeschli** [comment]
Sorry, all is good, I ran against stable, not insiders.
