### ISSUE TITLE
Add settings to ignore keywords for auto import

### ISSUE THREAD

**Issue by egucciar** [microsoft/vscode#123832]
When I am writing Jest and Cypress tests I am having the following variables get auto imported from other, random , libraries:

```
describe
it
cy
```

Want to be able to disable auto import just for some keywords and not globally. This is a very frustrating dev experience that has unknowingly cost hours of debugging time since auto imports happen to quickly with these 2 character ones especially.

**Comment by mjbvz** [comment]
The solution is to let VS Code know that globals called `describe`, `it`, ... exist so that it doesn't show these.

To do this, you can either import `jest` in the file or add an explicit reference to the jest types. see https://stackoverflow.com/questions/42024526/vscode-automatic-type-acquisition-for-jest as a starting point a
