### ISSUE TITLE
Improve "always debugging" experience

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#123873]
Some users like @hediet are always debugging while they are using VS Code. So when making edits, they do not stop the debugger. I think this flow makes good sense and we should think about how to improve this.

Let me list some limitations and @hediet can add more:
- [ ] debug hover too aggressive when just editing files in the editor
- [ ] breakpoints get easily unbound when doing edits in a file.

fyi @connor4312 @weinand for thoughts on limitations and how we could improve them

**Comment by weinand** [comment]
just two replies for the listed limitations from above:
- we are only showing the debug hover when the editor contents matches the source referenced in the stack frame (and the regular hover otherwise). So the debug hover gets into the way when editing the code where debugging has stopped. Since this is probably a common situation, I understand that the debug hover appears to be "aggressive". One way to address this would be to introduce a setting that reverts the semantics of the keyboard modifier that switches between "debug hover" and "regular hover". With this the "regular hover" is shown even when debugging and the "debug hover" only appears when pressing the modifier. 
- VS Code's strategy for "always on debugging" (or "hot code replacement") is to rely on the debug extension to do the right thing (e.g. tracking changes in generated code and reloading code as required). So tracking source changes that affect breakpoints needs to be done in debug extensions.

**Comment by isidorn** [comment]
@weinand yeah that's a good idea for reverting the keyboard modifier based on setting.
Another cool thing which we already do: if you are in a file which is not in the call stack we show the language hover nicely.

@hediet I would be interested if you have some ideas on how we could improve your flow or if there are other issues you are hitting

**Comment by isidorn** [comment]
Seems like there are no action items to be done on the VS Code UI side. Thus closing this.
I think the best follow up would be creating separate issues. I am not sure if you have exact pain points regarding this that we could improve @hediet

**Comment by hediet** [comment]
I will do that! My pain points with "always debugging" VS Code are currently the frequent crashing/freezing of Code OSS and no support for hot reload, so I was not really inspired to think more about this.
