### ISSUE TITLE
Command Palette search with `+` character (like "C++") doesn't behave as expected

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#123915]
Steps to Reproduce:

1. Install the C++ extension, which has all all its commands prefixed with `C/C++:`
2. Search for "C++" commands 

AR: The `+` seems to be handled differently

![image](https://user-images.githubusercontent.com/8599/118308836-48db5480-b4a1-11eb-8918-a1d37434e942.png)

ER: Search should match `C/C++: …` commands.

**Comment by bpasero** [comment]
@TylerLeonhardt let me know if you are interested to work on this issue. I gave it a brief look and think that the change from @roblourens in https://github.com/microsoft/vscode/commit/7b657e3692fc1460a5a463ce3a6d973f8ac77b3a (for https://github.com/microsoft/vscode/issues/27636) could have an impact here because `wordSeparators` seems to be treating `+` (and others) as word separators. I think that is probably still fine to keep but there should be logic to sort identical matches higher imho.

A similar issue was reported in https://github.com/microsoft/vscode/issues/118469

**Comment by TylerLeonhardt** [comment]
@bpasero I won't be able to get to it this iteration due to some time sensitive work items.

If you think you can get to it, I say go for it, otherwise I can probably take it on in June.

**Comment by bpasero** [comment]
Yeah sure, no rush needed.

**Comment by TylerLeonhardt** [comment]
Likely need to push this out again.

**Comment by TylerLeonhardt** [comment]
One more time...

**Comment by TylerLeonhardt** [comment]
verification: steps provided are good enough
