### ISSUE TITLE
Running tests is very hectic

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#124083]
The tree jumps up and down, ideally should be more stable:

![recording](https://user-images.githubusercontent.com/900690/118602575-2a33d100-b7b3-11eb-8c1d-b0ad35dad4bc.gif)

**Comment by connor4312** [comment]
I added this in https://github.com/microsoft/vscode/issues/117893 and it's toggleable via `testing.followRunningTest`. It is pretty noisy, open to feedback on improvements (or pushback if it should not be a default behavior)

**Comment by bpasero** [comment]
I think following the active test is fine and I like that, but I am sure we can make this smoother?

**Comment by connor4312** [comment]
The best way would be to have tests in the view shown in list of execution order. However we don't really have a concept of order in the API aside from the lexographic sort order and order of tests within a file. I think for our VS Code tests we just load all the files in parallel and they get executed in whatever order they happen to be included in -- which could be fixed by adding a sorting step.

**Comment by connor4312** [comment]
So, we now have _some_ concept of order in that `TestItemCollection.replace` takes an array of items (although you can still individually .add and .delete items). However, I also am not sure I want to make "order by extension order" something in the UI, since usually that won't be meaningful to users. Ultimately for Mocha execution is determined by evaluation order of each module (i.e. when `suite()` and `test()` is called).

I'll post this in #ux to see if others have feedback or ideas.

**Comment by connor4312** [comment]
I'm not sure there's any changes I want to make here.
