### ISSUE TITLE
[Insiders] Debugger kept in invalid state after process exits

### ISSUE THREAD

**Issue by a0viedo** [microsoft/vscode#124045]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: `1.57.0-insider`
- OS Version: Windows 10

I've tested this with all extensions disabled.

Steps to Reproduce:

1. Start a node process with `--inspect-brk` that uses worker threads
2. Attach the debugger
3. Send a `SIGINT` signal to the process to terminate it
![image](https://user-images.githubusercontent.com/2440935/118516080-5f391880-b70c-11eb-88c1-d4ac6dd321da.png)

Even if I click on disconnect nothing happens and the debugger still will be on screen. The only solution I've found is to force a "Reload Window".

I've uploaded a [video](https://www.youtube.com/watch?v=0z-vXP3UH2Y) of the reproduction too.

Code:
```js
setInterval(() => {
    console.log('hi there')
}, 1000);

const { Worker } = require('worker_threads');
new Worker(``, { eval: true });
```

**Comment by weinand** [comment]
Does the node process terminate properly if you send a SIGINT signal but have no debugger attached?

**Comment by a0viedo** [comment]
Yes, I would have to disable Auto Attach but it does exit properly.

**Comment by connor4312** [comment]
Thanks for the issue. This is because you're debugging twice using both auto attach _and_ a launch config. The 'target IDs' are set by process ID, so the first debug session steals the target for the second session, causing an error to be thrown. This prevents the second session from initializing (and being able to be torn down).

A workaround is to remove the duplicate session, either:

- Don't use auto attach and only Attach using a launch config
- Use auto attach (with --inspect instead of --inspect-brk) instead of the launch config

**Comment by connor4312** [comment]
no problem, it should be fixed [on nightly](https://github.com/microsoft/vscode-js-debug#nightly-extension)

**Comment by rzhao271** [comment]
@a0viedo has the issue been resolved for you (without having to use a workaround)?

**Comment by a0viedo** [comment]
@rzhao271 yes, when I managed to get two debuggers attached I had to restart VS Code and disable auto attach to get it working as expected.
