### ISSUE TITLE
continue shortcut not disabled when program is running when debugging

### ISSUE THREAD

**Issue by zt1106** [microsoft/vscode#124085]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: latest
- OS Version: any

Description:
When debugging and the program is running (not stopped by breakpoint or stepping), the "continue" button disappeared correctly, but the shortcut for "continue" ("F5") still sends a "continue" DAP protocol request to the debug adapter. 

Expectation:
When program is running, "F5" button should not send any request to debug adapter.

Steps to Reproduce:

1. open any existing open source debug extension project
2. add a protocol message tracker
3. launch a long running program without breakpoint
4. press "F5"

**Comment by shilky777** [comment]
yes， This problem has bothered me for a long time.

**Comment by isidorn** [comment]
I can look into this, it sounds like the command is not properly disabled when triggered via keybinding

**Comment by isidorn** [comment]
The reason why the command is not disabled when program is running is because otherwise multiple fast F5 presses, could potentially start a new debug session because one of them would be send to debug start command which has the same shortcut.

I have now fixed this that the continue is enabled only when stopped, and f5 to start a session is only enabled when no debugging is going on.
