### ISSUE TITLE
Task statuses and narrow tabs

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#124063]
I love the terminal task statuses, but I don't get to see them (except for warnings/errors) because I always have my tabs set narrow.

Maybe the narrow mode could be slightly less narrow to add in a status icon? Or maybe we could use color for certain status indicators -- green/red?

Additionally I think it would be great to show the codicon for the status in the hover in addition to the text -- to better associate the two.
![image](https://user-images.githubusercontent.com/641685/118561604-3aa76580-b739-11eb-800b-426e30bdf332.png)

**Comment by Tyriar** [comment]
> I love the terminal task statuses, but I don't get to see them (except for warnings/errors) because I always have my tabs set narrow.

There's an existing feature where the terminal's icon will get replaces with the status:

<img width="61" alt="Screen Shot 2021-05-18 at 4 38 44 AM" src="https://user-images.githubusercontent.com/2193314/118644704-ef21a580-b792-11eb-95ea-1366865c7a62.png">

Right now this only works for warning and above severities but I think we can change this as the only reason it wasn't covered for the `Severity.Info` is because I was thinking eventually we would add the (i) icon here as a status:

<img width="93" alt="Screen Shot 2021-05-18 at 4 39 33 AM" src="https://user-images.githubusercontent.com/2193314/118644816-0bbddd80-b793-11eb-8ce6-09c9d97363c2.png">

If we ever do that, it could use `Severity.Ignore` so it's shown as a lower priority status.

> Maybe the narrow mode could be slightly less narrow to add in a status icon? Or maybe we could use color for certain status indicators -- green/red?

Created https://github.com/microsoft/vscode/issues/124098 so themes can have green if they want.

> Additionally I think it would be great to show the codicon for the status in the hover in addition to the text -- to better associate the two.

Good idea!

**Comment by Tyriar** [comment]
<img width="166" alt="Screen Shot 2021-05-18 at 5 07 18 AM" src="https://user-images.githubusercontent.com/2193314/118648108-ed59e100-b796-11eb-8635-bd112b909e43.png">
