### ISSUE TITLE
profile.ps1 cannot be loaded

### ISSUE THREAD

**Issue by peter197321** [microsoft/vscode#124105]
After vs-code is stared and there is an error, how should it be fixed?

```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

. : File C:\Users\Documents\WindowsPowerShell\profile.ps1 cannot be loaded because running scripts is disabled on this system. For more information, see about_Execution_Policies at       
https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:3
+ . 'C:\Users\Documents\WindowsPowerShell\profile.ps1'
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess
```

**Comment by TylerLeonhardt** [comment]
@peter197321 did you try opening the link that's in the error? That should give you information about execution policy and commands that you need to run to set the execution policy to something that will allow you to run scripts. I won't tell you what to set it to because it's a security related feature and you should set it to what you feel comfortable setting it to.

This isn't a VS Code issue, so I will close this now.
