### ISSUE TITLE
[json] show which scheme is used to validate the current document

### ISSUE THREAD

**Issue by SamB** [microsoft/vscode#124139]
Issue Type: <b>Feature Request</b>

When I open/create a JSON file of a reasonably common type, with a somewhat recognizable name or structure, I tend to wonder if the JSON language features found a good schema for it or not, so I go to the command palette and search for commands with "JSON" in the name, and then commands with "schema" in the name.

I'm basically looking for the moral equivalent of nxml-mode's rng-what-schema command, which displays a message specifying the path to the schema file for the current document. It's very useful to see if you've got a good schema active.

VS Code version: VSCodium 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-14T00:21:57.363Z)
OS version: Windows_NT x64 10.0.19043

Since this is about the bundled JSON language features, it shouldn't matter that this is an unofficial build using a different extension gallery.

**Comment by Delapouite** [comment]
Hello @SamB 

It looks like this feature is kind of already supported. For example, when I open a `.gitlab-ci.yml` file in one of my project, at the very top there's a small faded link which opens the associated JSON Schema when clicked: 

![image](https://user-images.githubusercontent.com/39315/155735986-5c5fea95-a854-490a-8502-1b57b47e1d62.png)

Things to consider:

- I have the GitLab extension installed so it may be because of that.
- In this case it's a YAML file, so I'm unsure if it also applies to regular JSON files. (YAML is supposed to be a superset of JSON)
- When I open other kinds of "well-known" files, like `package.json` in a Node.js project, it does not work.

**Comment by aeschli** [comment]
I added this a while back. Hoover over `{ }` in the language indicator and click on the `Show schemas` link.
