### ISSUE TITLE
Try to not indent the active debugging line

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#124169]
This is a screenshot of a debugging session in VS Code insiders:
![image](https://user-images.githubusercontent.com/2931520/118798476-f97c9600-b89d-11eb-856f-309182e827c9.png)

It would be nice if a source code line does not move if it becomes active - this would make tracking the execution path easier.
Currently, it is indented by the yellow inline decorator.

The yellow arrow could be rendered before the line:
![image](https://user-images.githubusercontent.com/2931520/118799037-94757000-b89e-11eb-9a6b-7e79888dee0b.png)

In the special cases where the yellow arrow is in the middle of the line, this does not work. However, this does not happen very often so it is not that annoying.

What do you think @isidorn, @connor4312, @weinand?

**Comment by weinand** [comment]
Yes, I agree, shifting a line in order to show the arrow is annoying.
But I don't think that there is an easy way to avoid that...
@isidorn ?

**Comment by isidorn** [comment]
Good idea. The thing with decorations is that they always push the text and as far as I know there is no option for the decoration to not push.
So we would need to do some css tricks in order to make this working.
Maybe @alexdima has a good suggestion on a nice way to make decorations not push?

**Comment by hediet** [comment]
Maybe something similar to what liveshare uses to show the cursor name can be used:

![image](https://user-images.githubusercontent.com/2931520/118811292-1ec4d080-b8ad-11eb-95be-00d07989dee9.png)

**Comment by bpasero** [comment]
💯 ^💯 

I recently thought what makes me still uncomfortable using debug in VSCode and think this is it. I think devtools do this really really well, they never shift a line when debugging, rather:
* when a breakpoint is added, the line shifts only (and only) if there are multiple debug breakpoints possible in the line
* when you just step over code, no breakpoint is shown, rather the current stopped statement is highlighted
* when a breakpoint is added and there are multiple breakpoints possible, each one appears "ghosted" to indicate you can add breakpoints and to reduce the line indentation to just one



![recording (1)](https://user-images.githubusercontent.com/900690/118811762-aad6f800-b8ad-11eb-906f-951e471d8ca8.gif)

**Comment by alexdima** [comment]
> Maybe @alexdima has a good suggestion on a nice way to make decorations not push?

I think the LiveShare cursor also uses a `::before` decoration. I think there are some CSS properties that you could set on the decoration to make it not push the content. Maybe you could try to inspect element on the LiveShare cursor.

**Comment by jdemeule** [comment]
I also face difficulties to follow the execution path when the code I am looking is constantly shifting with this yellow decorator appearing in the middle of a line.
Could I suggest to make this behavior optional as "Show Inline Breakpoint Candidates"?

**Comment by isidorn** [comment]
@alexdima thanks for the idea, I took a liveshare approach to use `position: absolute` and not push.

To make this nice, I am not pushing when there is space on the left for me to put my decoration. if the decoration is on the middle of the line I will push as before which I think is expected.
You can see it in this gif:

![recording (1)](https://user-images.githubusercontent.com/1926584/123975599-c1e52b80-d9bd-11eb-9a09-a1174f4bf4f4.gif)

**Comment by isidorn** [comment]
Since this came in pretty late in the endgame and since next 3 weeks I am on vacation, I would need 2 volunteers to test this out for 20-30 minutes, today (out of source) or tomorrow.
Let me know if somebody has time to try it out, would really appreciate it.

**Comment by weinand** [comment]
@isidorn pls count me in!

**Comment by bpasero** [comment]
I can do tomorrow.

**Comment by isidorn** [comment]
Sold to the two gentlemen from North Germany...

**Comment by bpasero** [comment]
Some testing (only possible out of sources because we have no build today):

I guess here, we cannot prevent the indentation because the breakpoint is in the middle of the line. Imho the only way to make this scenario nicer is to use a different way of indicating the current statement, e.g. like Devtools does with using background color:
![image](https://user-images.githubusercontent.com/900690/124126370-e81cd100-da7a-11eb-9b1d-f8fb6e3ddfd0.png)

What I like about Devtools approach is that they clearly distinguish between a line where I added breakpoints to and a line I am just stepping through:

![image](https://user-images.githubusercontent.com/900690/124126943-785b1600-da7b-11eb-8325-696f1fc7aeee.png)

Here I feel the 2 indicators are not pixel perfectly aligned (I am running with zoom: 1 btw):
![image](https://user-images.githubusercontent.com/900690/124126592-1e5a5080-da7b-11eb-9055-9345e56ab717.png)

Even without zoom I think they are 1px off:

![image](https://user-images.githubusercontent.com/900690/124127160-b2c4b300-da7b-11eb-986e-d26e7257eb65.png)

Not sure the padding could be every so slightly greater here in this case:

![image](https://user-images.githubusercontent.com/900690/124127229-c4a65600-da7b-11eb-9763-7cbce5153a86.png)


Didn't find any major issues so far!

**Comment by hediet** [comment]
>  like Devtools does with using background color

I think this also helps to see what expression is being evaluated (range vs position).

**Comment by bpasero** [comment]
Yeah especially when you are reaching the end of a function, they do not highlight anything.

**Comment by isidorn** [comment]
@bpasero thanks for testing this out!
Yes I agree that the background color is a better solution because it does not push. I have created this issue so we consider this in the future https://github.com/microsoft/vscode/issues/127776
And as you said they do a great job of: add a breakpoint on a line -> we show you inline breakpoint candidates on that line

I can not get the pixel perfect vertical alignment. I currenty put 2px on top, if I do 3px it looks worse on my machine. So I will stick with the current one.

As for more padding for the cursor at the start of the line I have added 1 px now so it should breathe better.

**Comment by weinand** [comment]
I tested this for various debuggers and did not find any other problems than this minor nit:
for small indents the arrow gets clipped

<img width="918" alt="2021-07-01_17-08-58" src="https://user-images.githubusercontent.com/1898161/124147856-5d929c80-da8f-11eb-9615-4547d33b554b.png">

**Comment by weinand** [comment]
BTW, on my LG 5k retina display the vertical alignment of gutter and inline arrows is correct:

<img width="1185" alt="2021-07-01_15-19-41" src="https://user-images.githubusercontent.com/1898161/124149864-48b70880-da91-11eb-9c59-42603a471162.png">

**Comment by isidorn** [comment]
@weinand good catch for not enough leading whitespace. We could fix that, but I would not do it now.
As for smaller icon, that makes sense, however let's first try the background approach and if it does not work then we can involve Miguel for a smaller icon.

Also since Retina 5K screen says it is good then I guess it is good :)

**Comment by weinand** [comment]
BTW, my testing was done with Insiders, so I do not have your latest alignment changes.
And I'm using default fonts and sizes.

**Comment by weinand** [comment]
@rzhao271 Isi's changes addressed Ben's feedback (https://github.com/microsoft/vscode/issues/124169#issuecomment-872219638)
I've verified that alignment and space between arrow and caret are good:
<img width="367" alt="2021-07-07_14-54-59" src="https://user-images.githubusercontent.com/1898161/124762630-683bae80-df33-11eb-8348-ee978a8965e2.png">

**Comment by connor4312** [comment]
The vertical alignment is still off for non-default line heights. For an exaggerated height, for instance:

![](https://memes.peet.io/img/21-07-0d78652d-b331-4c7f-a3e0-932eaa03ec95.png)

**Comment by connor4312** [comment]
I will actually move to a new issue, I think what we have is fine for release but we should fix this in July.
