### ISSUE TITLE
Trusting a .code-workspace adds not only the folders, but also the .code-workspace path as well

### ISSUE THREAD

**Issue by alefragnani** [microsoft/vscode#124151]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Insiders 1.57
- OS Version: MacOS Big Sur

Steps to Reproduce:

1. Open an _untrusted_ multi-root workspace (`.code-workspace` file)
2. Click the `Trust` button when required
3. Look at the `Manage Workspace Trust` for the trusted folders that were added. 
4. You will see not only the folders contained in the multi-root workspace, but also the `.code-workspace` file as well

Based on this documentation https://github.com/microsoft/vscode/issues/106488, it appears only **folders** should be accepted, not **files**.

Thank you

**Comment by lszomoru** [comment]
This behaviour is by design. In case of a multi-root workspace, [the workspace settings](https://code.visualstudio.com/docs/editor/workspaces#_multiroot-workspace-settings) are being stored in the workspace file, so if the user does choose to trust each folder, and the workspace file. In order to avoid confusion we could update the naming of the list to "Trusted Workspaces". We should also limit the picker when adding a path to folders, and `.code-workspace` files only.

**Comment by alefragnani** [comment]
That's great, I thought that would be the case (also support `.code-workspace`).

Thank you

**Comment by sbatten** [comment]
As I mention in another issue, Windows/Linux does not allow folders and files to be selected by a picker (at least through electron apis), but adding a code-workspace file manually does not gain you much from being able to add it there vs opening and trusting the workspace directly. We could it add it as a separate button, but its not as important as the folder button imo.
