### ISSUE TITLE
inverted text selection color like vim text selection

### ISSUE THREAD

**Issue by alexzanderr** [microsoft/vscode#124241]
hello.

i dont know if there is any request or question for this topic.
i search the internet, didnt find anything.
if there is already, sorry.

[good example of what i want](https://imgur.com/a/uSibcZu)

![image](https://user-images.githubusercontent.com/5047891/121215102-ff074380-c87f-11eb-88c9-4a55ad19bb61.png)

**Comment by dkrnic-git** [comment]
> 
> 
> hello.
> 
> i dont know if there is any request or question for this topic.
> i search the internet, didnt find anything.
> if there is already, sorry.
> 
> [good example of what i want](https://imgur.com/a/uSibcZu)
> 
> ![image](https://user-images.githubusercontent.com/5047891/121215102-ff074380-c87f-11eb-88c9-4a55ad19bb61.png)
Had the same problem, but the thread closed before there was any answer.
By comparing the settings (the output of the command ":set") between how it is set up in the edited text, in which all characters except numerics and punctuations (including blanks)  are displayed inverted, and the text in the HELP window, where they are not inverted, I found out that the setting of "filetype" is different - it is "vim" for the HELP window instead of "json"
Apparently, by copying text from non-Vim sources (e.g. from browsers, or MS Office documents) the "filetype" setting is carried forward to the Vim editor as "json" instead of remaining "vim".
So just execute the following command:
:set filetype=vim
and the world will be OK again.
