### ISSUE TITLE
Activity view hover comes and goes without moving mouse

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#124254]
When I click on the GH view (when it has not yet loaded in the session), I get the hover come and go many times:

![recording (2)](https://user-images.githubusercontent.com/900690/118981983-408c8900-b97b-11eb-98e8-1c2c7e8e0d42.gif)

//cc @Tyriar

**Comment by sandy081** [comment]
Seems the activity on the entry is causing the problem here.

**Comment by sandy081** [comment]
It is because, I am listening to mouse leave event on the container and hiding it. But when there is activity on the container, we update the activity by hiding and showing it. This is causing the mouse leave event whenever badge is hidden and mouse hover event whenever badge is shown. 

Fixed it, by hiding the hover only when mouse leave event target is the container. This fixes the flickering of the hover when the activity is getting updated.

One loose end which is not covered in this fix is following:

https://user-images.githubusercontent.com/10746682/209936043-a86f7617-a401-4d0e-bb00-df918ff03b3b.mp4

Hover appears at the end because the badge is shown that triggers mouse over event. It seems the root cause here is hover getting hidden by the hover widget when clicking on the activity bar icon.

**Comment by bpasero** [comment]
So the original issue still reproduces for me, what was fixed?

**Comment by Tyriar** [comment]
On Windows it's hiding on click for me which seems fine.

**Comment by sandy081** [comment]
Before, the hover keeps reappearing whenever the activity is updated. So before as soon as you click the hover disappear and appear because activity is updated and it might also flickers if the activity keeps updating.

This is fixed now. But due to the following limitation hover reappear at the end. 

> Hover appears at the end because the badge is shown that triggers mouse over event. It seems the root cause here is hover getting hidden by the hover widget when clicking on the activity bar icon.

**Comment by bpasero** [comment]
Ok, I think it is better from what I recall compared to how it was.
