### ISSUE TITLE
"Do you want to open it anyway?" in diff editor no-ops

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#124222]
![recording (15)](https://user-images.githubusercontent.com/8586769/118917153-0f617980-b8e5-11eb-8b00-37b44d8261b5.gif)

**Comment by lramos15** [comment]
Could be clearer to not show them in the picker here, but what is happening is that the hex editor can't handle diff views and therefore we are doing nothing and you continue to see the text view.

**Comment by JacksonKearl** [comment]
The text view should be able to try to render the binary data, if you open it in a non-diff view it does show text.

**Comment by lramos15** [comment]
@bpasero I don't think this is an override bug. What's happening is I'm calling `replaceEditors` with an input with `setForceOpenAsText`. However, it doesn't seem replaceEditors supports replacing in a diff. Maybe we should always `setForceOpenAsText` on `FileEditorInputs` belonging to diff editors.

**Comment by bpasero** [comment]
To clarify, we want to replace a diff editor with a normal editor right? Or should this action reopen as diff editor?

**Comment by lramos15** [comment]
It has to do with replacing a side of a diff editor input.

There's two possible solutions here. 

1. Support replacing sides of a diff editor input (probably over complex) so that the user will see the binary message and then can click open anyways
2. Always open text diffs as files even if binary.

**Comment by bpasero** [comment]
I think I would expect the diff editor to reopen where both sides pick the editor I selected from the quick pick.

**Comment by lramos15** [comment]
The quickpick only knows about one side of the editor at a time. We explicitly disable reopen with in diffs for this reason. Just the binary case is a special case as the user can trigger the quickpick from the link

**Comment by bpasero** [comment]
I see, I probably then would expect that it opens the editor where I selected the link from. If that is too complex, maybe we open the editor as a new editor, and not as diff?

**Comment by lramos15** [comment]
What I don't understand is why we have this idea of a binary diff editor? It's of no use and both sides just show that they're binary and request to be opened as something else. Wouldn't it make more sense to just show the text representation of the file if opened in the diff view. Any useful binary representations will get delegated to an extension anyways which is supported.

**Comment by bpasero** [comment]
@lramos15 for consistency reasons and for performance reasons. 
* consistency: if you get the binary editor by clicking on the binary file, I would expect the same when diffing
* performance: binary files can easily be gigabytes in data, just opening them as text for the diff case would potentially bring down the window

**Comment by bpasero** [comment]
This is really tricky to fix, the issue is here:

https://github.com/microsoft/vscode/blob/f2b1f78ad45d5b19fe220e4533356efb31f4dcc1/src/vs/workbench/contrib/files/browser/editors/binaryFileEditor.ts#L53-L60

We try to replace the editor, but the editor is actually not opened as a single editor, it is opened as a diff editor on the one side. 

I would also argue that this line is fishy:

https://github.com/microsoft/vscode/blob/f2b1f78ad45d5b19fe220e4533356efb31f4dcc1/src/vs/workbench/contrib/files/browser/editors/binaryFileEditor.ts#L47-L47

Because that only makes sense if the editor that is picked is a text editor, not when it is a custom editor.

I think we need to revisit that code entirely, since it originates from a time where we did not have overrides either.

**Comment by bpasero** [comment]
Maybe this could work:
* since this can only be triggered by the user from the active editor, check if `group.activeEditor` is a side by side editor and then tweak the call to `replaceEditors` accordingly
* only call `setForceOpenAsText` if the picked editor is a text editor

**Comment by connor4312** [comment]
Diffing two random exe's from the vscode repo, it looks like nothing is shown in the diff view. We should at least have some message here


https://user-images.githubusercontent.com/2230985/124199962-0db0d700-da89-11eb-88a4-da5d30698e0e.mp4

**Comment by bpasero** [comment]
This now seems to be opening a monaco text diff editor and not a binary diff editor anymore which seems like a regression from our work in the editor service (most likely):

![image](https://user-images.githubusercontent.com/900690/124230337-22d04900-db0f-11eb-871c-7947c574ac74.png)

**Comment by bpasero** [comment]
@lramos15 this is a regression from comparing untyped based in `matches` for typed editor inputs:

https://github.com/microsoft/vscode/blob/5b29adfa24daf111d35367e9e23ddd4557ec363a/src/vs/workbench/common/editor/diffEditorInput.ts#L157-L159

The `isResourceDiffEditorInput` unfortunately will be `true` even for `DiffEditorInput`.

I will open a PR to make our various functions that check for untyped editors more robust.
