### ISSUE TITLE
[Accessibility] Icon tooltips are not hoverable 

### ISSUE THREAD

**Issue by setaskin** [microsoft/vscode#124205]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.56.1
- OS Version: Windows

Steps to Reproduce:

1. Go to file explorer view 
2. Hover over any icon  ( Add file, Toggle editor layout etc.)
2. When you see  button tooltip, try to hover over to the tooltip

Expected : Users should be able to hover over tooltip via mouse 

Actual : Users cannot hover over tool tip 

![button hover](https://user-images.githubusercontent.com/37163639/118884725-b2959d00-b8ab-11eb-9d62-82c33137bf72.gif)

**Comment by setaskin** [comment]
@isidorn , this is another issue that accessibility test team found and assigned to Live Share team.

**Comment by setaskin** [comment]
sorry for opening the same issue again. it is a dupe of #[52016](https://github.com/microsoft/vscode/issues/52016). C

**Comment by isidorn** [comment]
Actually it might not be a duplicate of that. 
This is how native hovers behave in Chrome and we can not change that. However we do have custom hovers and those we can control. And this issue is already captured here https://github.com/microsoft/vscode/issues/115034
So please comment there or upvote it. Thanks!
