### ISSUE TITLE
Native Notebooks - Inconsistent behavior with cell join

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode#124281]
## Steps to Reproduce:

1. Open notebook with 2 cells that both have output
2. Put cursor somewhere in the first cell and join with next cell (using keyboard shortcuts or menu item from cell toolbar) 

The cursor will end up in the second cell at the end of the line

1. Join the same two cells, but this time from the second. Put cursor in second cell and join with previous cell (using keyboard shortcuts or menu items from cell toolbar)

The cursor disappears 

## Expected Behavior:
For the cursor to be in the same location, regardless of the "direction" of join

**Comment by stuartleeks** [comment]
Tested on Windows
Joining from the first cell results in the cursor at the end of the merged cell
Joining from the second cell results in the cursor at the start of the merged cell.

The cursor doesn't disappear for me as described in the issue, but the "Expected Behaviour" in the description is for the cursor position to be consistent regardless of the direction of merging.

Do you want me to mark this as `verified` and create an issue to track making the cursor location consistent?

**Comment by rebornix** [comment]
They should be doing the same now.
