### ISSUE TITLE
adding '&' while running python script via the run button on top left

### ISSUE THREAD

**Issue by bhatiaharshit07** [microsoft/vscode#124387]
Issue Type: <b>Bug</b>

Ideally it should run it like this 
`C:/Users/bhati/anaconda3/python.exe "c:/Users/bhati/OneDrive - Maharaja Surajmal Institute Of Technology/Desktop/JAVA/duplicate.py" `
but instead it is running it like this 
`& C:/Users/bhati/anaconda3/python.exe "c:/Users/bhati/OneDrive - Maharaja Surajmal Institute Of Technology/Desktop/JAVA/duplicate.py"`
This causes the script to fail.

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.85GB (2.35GB free)|
|Process Argv|--crash-reporter-id db2e837e-445b-44e7-9e40-401347523fc2|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by bhatiaharshit07** [comment]
Edit: It works with power shell but incase of command promt in shows this error.

**Comment by msourada** [comment]
I have this problem as well and in the environment I use VS Code + Python (High School) I cannot use PowerShell (python is blocked in power shell by our org. antivirus). It also breaks debug, because it does not respect the setting a tries to run in PowerShell.

I noticed that when using deprecated method to switch to CMD (because initially it didn't happen to me, who had it set for a long time now, but only to my students, who are freshly out of corona lockdown) **it starts to work again**, just add to **settings.json**:
`"terminal.integrated.shell.windows": "${env:windir}\\System32\\cmd.exe"`
