### ISSUE TITLE
The automatic Imports of vscode behaves differently in different folders

### ISSUE THREAD

**Issue by 643104191** [microsoft/vscode#124332]
I have disabled all the vscode extensions.

### This is my jsconfig configuration:
```json
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@/gulp/*": ["script/gulp/*"],
      "@/script/*": ["script/*"],
      "@/src/*": ["src/*"]
    }
  },
  "exclude": ["node_modules", "dist"]
}
```

### This is my project directory structure
```
├── script
│   ├── gulp
│   │   ├── task
│   │   │   ├── components
│   │   │   │   └── index.js
│   │   │   └── ...
│   │   └── ...
│   │
│   ├── utils
│   │   ├── yaml.js <-- I expect the automatic import behavior in this file
│   │   └── ...
│   └── ...
│
├── src
│   ├── app.js <-- I don't expect the automatic import behavior in this file
│   └── ...
│
├── jsconfig.json
├── gulpfile.babel.js
└── ...
```

### When I use the automatic import in the script directory(The behavior I want)

![script directory](https://i.stack.imgur.com/HudET.gif)

### When I use the automatic import in the src directory(Behavior I don't want)

![src directory](https://i.stack.imgur.com/XZX76.gif)

I don’t know what I have configured wrong or other errors

anybody can help me?

**Comment by mjbvz** [comment]
The difference is because you have a file with imports vs an empty file

In empty files, VS Code tries to use the import style that best matches what is configured in your `jsconfig` (the default is `module`). If you set something like `"module": "es2020",`, `import` should be used

In a file with existing imports, we try to match the style of existing imports
