### ISSUE TITLE
Format on Save

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#12449]
Given the infrastructure we have built for #239 we can offer something like `files.formatOnSave` whichs mean format a document whenever we are about to save it.

**Comment by jrieken** [comment]
cc @ramya-rao-a , @mattetti, @lukehoban I see that vscode-go has [this](https://github.com/Microsoft/vscode-go/blob/master/src/goMain.ts#L188) which won't be needed much longer. With #239 we will add the `onWillSaveTextDocument` event and with this isse we will utilise our new infrastructure to format on save.

I wanna poke your brains wrt to format on save and auto save. This is obviously a hot topic because auto-save happens while typing meaning formatting might kick in unpleasantly. Did you get feedback in that direction? Do you have ideas - like not formatting when it's auto-save and messing for your cursors?

**Comment by jrieken** [comment]
re https://github.com/Microsoft/vscode/issues/12449#issuecomment-248910194

@HookyQR same question. How do people react to auto-save and format on save?

**Comment by jrieken** [comment]
Proposal is to ignore formatting when auto-save happens in an focused editor and when the edits overlap with any of the cursors - https://github.com/Microsoft/vscode/blob/joh/formatOnSave/src/vs/workbench/api/node/mainThreadSaveParticipant.ts#L124

**Comment by ramya-rao-a** [comment]
@jrieken Below is an excerpt from the README for the Go extension

> If you do turn `Auto Save` on, you may also want to turn `format-on-save` off ("go.formatOnSave": "false"), so that it is not triggered while typing

It is suggested to not use both together.

There have been a few instances (https://github.com/Microsoft/vscode-go/issues/368, https://github.com/Microsoft/vscode-go/issues/447) which left users baffled when their code kept disappearing which was Auto Save triggering formatting that deleted unused imports or multiple new lines.
Long time users of the extension do not use this combination due to the exact same issue.

Since `files.autosave` is off by default, it was safe for `go.formatOnSave` to be on by default as per https://github.com/Microsoft/vscode-go/issues/253. The same issue has some feedback about this combination of settings.

**Comment by ramya-rao-a** [comment]
@jrieken Would the new `files.formatOnSave` format all files during `Save All` ? There is a feature ask for the same in Go extension https://github.com/Microsoft/vscode-go/issues/279

**Comment by jrieken** [comment]
re https://github.com/Microsoft/vscode/issues/12449#issuecomment-249021021 - yes `formatOnSave` will work together with `Save All`

**Comment by jrieken** [comment]
re https://github.com/Microsoft/vscode/issues/12449#issuecomment-249012323 - we now don't format on *auto* save

**Comment by jrieken** [comment]
@bpasero Can you make sure the participant is called when auto-save is true but when the user pressed `cmd+s` explicitly? In would be good if that doesn't count as *auto save* but explicit save.

**Comment by bpasero** [comment]
@jrieken today all save attempts are ignored if the model is not dirty. though for this milestone I fixed another feature request where people wanted the save to go to disk even when the model is not dirty so that external file watchers get triggered (e.g. nodemon). My solution is not going through the model, but now that we have a use case for this, I can revisit that solution and make sure we go through the model even if the model is saved. This would then also count as a normal save and not auto save.

**Comment by jrieken** [comment]
I see - I was assuming cmd+s is off when auto save is on. Reality is already a lot better then I assumed.

**Comment by bpasero** [comment]
@jrieken yup, if auto save is on but the file is still dirty (because it was not auto saved yet), the save will still happen.

So the question is: do we want format on save even when the file is not dirty and the user saves manually.

**Comment by jrieken** [comment]
stretch - let's wait for that request.

**Comment by HookyQR** [comment]
@jrieken I don't recall any issues being raised with auto save and format on save both being set for my extensions. I guess most users would recognise it as a problem pretty quick and turn one of them off.

**Comment by daviwil** [comment]
Sorry for asking here, I didn't find this information elsewhere.  How does an extension register a formatting provider for a language?  I don't see it in the list of [contribution points](https://code.visualstudio.com/docs/extensionAPI/extension-points).  Thanks!

**Comment by jrieken** [comment]
It happens in code using the [`registerXYZFormattingEditProvider`](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L4067)-functions. That's more or less how you get into the `Format Code` action and we invoke that when saving

**Comment by Lonefy** [comment]
@jrieken Sorry for reply late. i'm really busy for this several months and i'll try to fix the problem soon.
