### ISSUE TITLE
Explorer: should not offer drop feedback in multi-root case when last folder readonly

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#124495]
Steps to Reproduce:

1. be in a multi root workspace
2. let the last folder be a readonly one
3. drag and drop files into the empty space after the last folder
4. you get visual feedback that you can drop

=> 🐛 this is not true because by default we seem to be dropping into the last folder when dropping into empty space

I am not even sure we can do this properly because obviously we do want to allow to drop folders since the user may want to add to the workspace. Alternatively if we cannot disable the drop feedback, maybe a dialog should appear.

**Comment by isidorn** [comment]
As you say we can not disable the drop feedback since the user might want to drop another root folder.
Probably the right experience would be to polish the dialog which asks the user does he want to Copy / Paste or Add a Root folder. That dialog should probably say, you can only add a root folder since root R is readonly.
