### ISSUE TITLE
New keyboard shortcuts CTRL+N and CTRL+ALT+N with condition for explorer

### ISSUE THREAD

**Issue by CoderCH62** [microsoft/vscode#124401]
I suggest those two new keybindings when a folder in explorer is in focus, to create a new folder or file:

```
[
    {
        "key": "ctrl+alt+n",
        "command": "explorer.newFile",
        "when": "explorerResourceIsFolder && explorerViewletVisible && filesExplorerFocus && !inputFocus"
    },
    {
        "key": "ctrl+n",
        "command": "explorer.newFolder",
        "when": "explorerResourceIsFolder && explorerViewletVisible && filesExplorerFocus && !inputFocus"
    }
]
```
Since there is a condition, it has no conflict with the existing CTRL+N to open a new file in editor.

**Comment by isidorn** [comment]
Some of the current users are used to Ctrl+N always opening a new untitiled file, even in the explorer.
Because of that I would change nothing here atm. However we can leave this open to gather more user feedback

**Comment by zardoy** [comment]
I suggest to change CTRL+N to **always** create new file in explorer. Im using this shortcut more than for an year and can say that it provides coolest possible UX:

1. User first need to think about the file name and only then about the code
2. It solves the problem with syntax highlighting, because user gives an extension to the filename

Again, in this case user will have already saved file, no more select language prompts or saving dialogs. There is only one downside: to be productive, user must know how to use ctrl+shift+e shortcut with up/down arrow keys to quickly navigate through the levels.

but i fully understand that someone still use ctrl+n to open hundreds of blank files to save then only one.

thoughts? Hope to hear feedback here.
