### ISSUE TITLE
Native Notebooks - Drag and drop line in wrong spot

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode#124408]
Indicator for drag and drop movement in cells doesn't end up between cells when the insert cell items (+Code +Markdown) are in the notebook toolbar. 

![drag and drop indicator](https://user-images.githubusercontent.com/19276747/119215523-10c8a880-ba83-11eb-808f-c8e13a1a7b56.gif)

**Comment by roblourens** [comment]
@rebornix this is a tricky one. This is due to the extra 18px of padding that we put at the top of the editor for the top insertion toolbar (and it makes space so cell toolbars can overflow a little). Normally this is part of the height of each cell. Here, it should just be part of the height of the top cell. But, the cell VM doesn't know its index and I don't know a nice way to just change the height of the first cell for this. But here you have the cell toolbar overflow the previous cell, so the first one does need to be special. Any idea how to handle it?

**Comment by DonJayamanne** [comment]
Closing this as no one else has reported this issue, also would be a papercut.
