### ISSUE TITLE
Support dragging from custom webview into a view

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#124593]
Luna Paint has several windows inside the webview, I've wanted since adding them to allow pulling them into a sidebar where possible if the user wants it. Originally I was thinking to just do this via a command but it's not particularly intuitive. I discovered after terminal tabs got added that it's possible for dnd events that originate from a custom webview to be handled in the workbench.

![recording (12)](https://user-images.githubusercontent.com/2193314/119532613-e3595480-bd39-11eb-913f-dcdadc87d91d.gif)

How I see this working is to indicate somewhere on the event that it's of type view where the content is the ID, a command may need to be run to handle the drop on the other side.

The hex editor could also use this to drag and drop the data inspector to/from the webview/sidebar.

**Comment by mjbvz** [comment]
I'm closing this for now due to lack of additional feedback

However I did consider this and here are some notes if we revisit this in the future:

- Letting drag register a command to run is likely not safe. This would let any scripts injected into the webview to run arbitrary commands on drop. It's also not clear how we'd pass the drop location to the command

- On drag, we could instead let webview code set something like `vnd-vscode/view == myFancyViewId` type on the `DataTransfer`. Then we would make VS Code understand this drop type
