### ISSUE TITLE
Offer to reload modified document when changed on disk

### ISSUE THREAD

**Issue by remss** [Microsoft/vscode#12452]
- VSCode Version: 1.5.2
- OS Version: Windows10

Steps to Reproduce:

1. Open a .js file with VSC
2. Makes some changes but do not save
3. Open the same .js file with an other editor and change something
4. Back to VSC, nothing happend but it should prompt to reload yes/no the file because it has changed.

**Comment by bpasero** [comment]
@remss we follow a different model compared to what other editors do: instead of forcing you to make the decision of taking the change on disk, we do this when you actually save. and then we offer you a way to see your changes compared to the changes on disk in a side by side editor and decide either to overwrite the file on disk or take the contents from disk.

**Comment by remss** [comment]
The feature that shows a diff to take changes is very nice but why at save ? Having this when change is made with a FS watcher would prevent to continue writing code that will conflict with external changes.

**Comment by bpasero** [comment]
@remss yup, this might need an option in the end in settings. from my feeling as a user of the editor I find it very frustrating to get a prompt constantly when something changes on disk and prefer this model where I do not have to make a decision until I save. 

Btw we also have auto save enabled in the team which very likely has a great impact on this because I do see the warning popup as soon as it happens and can deal with it. The warning is not modal though so I can continue if I want.

**Comment by remss** [comment]
Thanks for the anwser.
Please reopen this issue the day you want to implement this settings option.
