### ISSUE TITLE
Debugger gets detached 

### ISSUE THREAD

**Issue by Hmachalani** [Microsoft/vscode#12468]
- VSCode Version: 1.5.3
- OS Version: Mac OS Sierra

Steps to Reproduce:

1) Create break points in Node.js
2) Run/debug app and make sure breakpoints are triggered
3) Stop app
4) run again and try triggering breakpoints again

Expected: App stops on breakpoints
Actual: App stops / debugger detached.

**Comment by chrmarti** [comment]
Could not reproduce.
- What version of node are you using?
- Please paste your launch config here
- What does the debug console show when the problem occurs?

**Comment by Hmachalani** [comment]
When the problem occurs, the debug console shows nothing - the app just dies with no error messages (same as if you clicked the Stop button).

Node version 0.12.14. I know it's ancient, but it's a requirement since Amazon Beanstalk + DynamoDB is not stable with more recent versions.


LAUNCH CONFIG:

{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch",
            "type": "node",
            "request": "launch",
            "program": "${workspaceRoot}/main.js",
            "stopOnEntry": false,
            "args": [],
            "cwd": "${workspaceRoot}",
            "preLaunchTask": null,
            "runtimeExecutable": null,
            "runtimeArgs": [
                "--nolazy"
            ],
            "env": {
                "NODE_ENV": "development"
            },
            "externalConsole": false,
            "sourceMaps": false,
            "outDir": null
        },
        {
            "name": "Attach",
            "type": "node",
            "request": "attach",
            "port": 5858,
            "address": "localhost",
            "restart": false,
            "sourceMaps": false,
            "outDir": null,
            "localRoot": "${workspaceRoot}",
            "remoteRoot": null
        },
        {
            "name": "Attach to Process",
            "type": "node",
            "request": "attach",
            "processId": "${command.PickProcess}",
            "port": 5858,
            "sourceMaps": false,
            "outDir": null
        }
    ]
}

**Comment by chrmarti** [comment]
Looks good to me, yet I cannot reproduce with 0.12.14. @weinand Any idea what could go wrong here?

**Comment by chrmarti** [comment]
@Hmachalani One more thing to check: What does the Debug Console show when this occurs?

**Comment by Hmachalani** [comment]
@chrmarti unfortunately it shows no error messages. As I mentioned above, the app just stops with no additional debug console messages :\ It's still happening to me frequently. The fix is to remove all breakpoints and create them again.

**Comment by michaelfamarques** [comment]
Similar thing happen to me:
Steps:
1 - Start visual studio
2 - Start app
3 - Begin placing breakpoints, when 4  breakpoints is used my app stops and debugger stops to, no log message.

And when i start my app with 4 or more breakpoints selected its start and die instantly.

Tested on 2 others computers and on them it didnt happen.

Using: Visual Studio Insiders 1.6.0 Commit 782e3ad7e504c308a5f1592ca6ae2574a13b0e73
Node Version: Tested using 6.2.2, 6.4.0 and 6.5.0

My launch config:
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch",
            "type": "node",
            "request": "launch",
            "program": "${workspaceRoot}/server/server.js",
            "stopOnEntry": false,
            "args": [],
            "cwd": "${workspaceRoot}",
            "preLaunchTask": null,
            "runtimeExecutable": null,
            "runtimeArgs": [
                "--nolazy"
            ],
            "env": {
                "NODE_ENV": "development"
            },
            "externalConsole": false,
            "sourceMaps": false,
            "outDir": null
        },
        {
            "name": "Attach",
            "type": "node",
            "request": "attach",
            "port": 5858,
            "address": "localhost",
            "restart": false,
            "sourceMaps": false,
            "outDir": null,
            "localRoot": "${workspaceRoot}",
            "remoteRoot": null
        },
        {
            "name": "Attach to Process",
            "type": "node",
            "request": "attach",
            "processId": "${command.PickProcess}",
            "port": 5858,
            "sourceMaps": false,
            "outDir": null
        }
    ]
}

**Comment by Hmachalani** [comment]
@weinand this is happening constantly for me. Is there anything I can do to help you guys fix this? The debugger's getting constantly detached in v1.6.1 with Node 4.4.6

**Comment by weinand** [comment]
@Hmachalani please add `"trace": "all"` to your launch config and try to reproduce the problem. You should see lots of trace output in the debug console. Try to spot anything that hints to the problem (or share the trace output here and I will investigate).

**Comment by michaelfamarques** [comment]
Here are my log after trace: all:

node --debug-brk=47361 --nolazy server/server.js 
20157: _attach: address: 127.0.0.1 port: 47361
Debugger listening on [::]:47361
20157: _attach: retry socket.connect
20157: _attach: connected
20157: _stopped: got break event from node
20157: _stopped: new ref cache
20157: _analyzeBreak: suppressed stop-on-entry event
20157: _initialize: got process id 20173 from node
20157: _injectDebuggerExtensions: frame based code injection successful
20157: _startInitialize: stopped: true
20157: _startInitialize: got break on entry event after 0 retries
20157: _startInitialize2: fire initialized event
20157: _startInitialize2: remember to do a 'Continue' later
20157: setBreakPointsRequest: {"path":"pathtofile/cliente.js","name":"cliente.js"} [{"line":213},{"line":220},{"line":217}]
20157: _setBreakpoint: {"type":"scriptRegExp","target":"^(.*[\\/\\\\])?\\/pathtofile\\/cliente\\.js$","line":212,"column":0}
20157: _terminated: socket end
20157: _terminated: node v8protocol close
20157: shutdown: kill debugee and sub-processes
20157: disconnectRequest: send response
20157: _terminated: target exited
20157: _terminated: target closed

In this log it happens right after i run my application (with 3 or more breakpoints), but the same happens when i set a third breakpoint with the application running.

**Comment by weinand** [comment]
@michaelfamarques you've mentioned "Tested on 2 others computers and on them it didnt happen."
Since neither you nor myself can reproduce the problem on a different computer, this sounds like a problem specific to your computer or your VS Code installation.

Please install the "VS Code Insider" on the computer where you experience the problem and try to reproduce the problem (this will not affect your installation of the stable "VS Code" in any way).
If the problem doesn't occur, then it is an issue with your stable "VS Code" install.
If it does occur, then it is a problem of your system.

**Comment by Hmachalani** [comment]
@weinand here's my trace all: 

57771: _stopped: got break event from node
57771: _stopped: new ref cache
57771: stackTraceRequest: vscode_backtrace 0 20
57771: NodeV8Protocol hook: ref cache size: 91
57771: __readFile: /Users/henrim/Documents/projects/mistplay/coinpwn/routes/tango.js
57771: _loadScript: 877
57771: __readFile: /Users/henrim/Documents/projects/mistplay/coinpwn/services/TangoService.js
57771: _loadScript: 878
57771: __readFile: /Users/henrim/Documents/projects/mistplay/coinpwn/node_modules/request/request.js
57771: _loadScript: 170
57771: scopesRequest: scope 0
57771: _terminated: socket end
57771: _terminated: node v8protocol close
57771: shutdown: kill debugee and sub-processes
57771: disconnectRequest: send response
57771: _terminated: target exited
57771: _terminated: target closed

**Comment by michaelfamarques** [comment]
@weinand the same thing happens on both VS Code and VS Code Insider (both updated too)

**Comment by Hmachalani** [comment]
@weinand this is still happening daily. I'm a huge fan of Code and don't want to have to switch back to Atom :( Let me know if you guys have any idea of what might be happening.

**Comment by michaelfamarques** [comment]
@Hmachalani im using the debugger command till i get vscode to debug correctly again, you can try it too.

**Comment by Hmachalani** [comment]
@michaelchiche debugger command? node_debugger in Atom?

**Comment by michaelfamarques** [comment]
@Hmachalani just put the "debugger;" on a line, vscode debugger will stop at that line the same way you select a breakpoint.

**Comment by weinand** [comment]
Are you using any tools that transpile on the fly? E.g. babel/register, babel/require, or systemJS?

**Comment by weinand** [comment]
@Hmachalani @michaelfamarques I've read the whole issue again and again and I'm pretty sure that both problems are unrelated.
So I will try to investigate the original issue by @Hmachalani.
(@michaelfamarques I suggest that you create a new issue with your problem.) 

@Hmachalani Since I cannot reproduce your problem, it is very difficult to investigate this...

In your steps from above you "stop" the app (step 3). Could it be that the app persists some state that prevents that the app can be started again? You said "App stops / debugger detached." This can just mean that the app has terminated (for instance because it "chokes" on some corrupted state).

In your launch config please set the "stopOnEntry" to true and start your app again. Does the debugger stop on the entry point of your app?

**Comment by Hmachalani** [comment]
@weinand good news for me - I tried VS Code Insider and it fixed the issue :)

It might be an issue with the stable version of VS Code. I'll try the configs you recommended and will post the results here shortly.

**Comment by Hmachalani** [comment]
@weinand the breakpoint triggers, I can see VS Code pointing to the breakpoint and then the app silently crashes and I get no message unless trace all is turned on. Also, it happens in random code paths - code paths that are in production and work perfectly. The fact that this doesn't happen in Insider means it's probably something with VS Code stable - maybe it's in a bad state, so I reinstalled it but it's still happening.

**Comment by weinand** [comment]
@Hmachalani It is possible that this issue is caused by an installed extension. Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions` and try your steps again to see if it reproduces.
