### ISSUE TITLE
Setting workbench.startupEditor=readme|newUntitledFile doesn't work in Workspace Settings

### ISSUE THREAD

**Issue by eyk** [microsoft/vscode#124689]
Issue Type: <b>Bug</b>

Save an empty workspace with a README.md file.
Set "workbench.startupEditor": "readme" in the workspace.code-workspace file.
Close all tabs and restart VS Code.

VS Code should open the README.md preview on startup, but it doesn't. The workspace setting is ignored.

As a User Setting workbench.startupEditor=readme works as expected. The preview ist shown on startup. 

The setting value newUntitledFile behaves the same: doesn't work as workspace settings, works as user setting.

IIRC the settings none|welcomePage|gettingStarted work correctly

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19042

<details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|11.4.1
auto-close-tag|for|0.5.10
path-autocomplete|ion|1.17.1
svn-scm|joh|2.13.5
vscode-cfml|Kam|0.5.3
VS-code-vagrantfile|mar|0.0.7
vscode-apache|mrm|1.2.0
vscode-language-pack-de|MS-|1.56.2
mssql|ms-|1.10.1
remote-ssh|ms-|0.65.4
remote-ssh-edit|ms-|0.65.6
pdf|tom|1.1.0
highlight-matching-tag|vin|0.10.0
vscode-icons|vsc|11.4.0
markdown-pdf|yza|1.4.4
markdown-all-in-one|yzh|3.4.0

</details>

**Comment by sandy081** [comment]
Assigning to @JacksonKearl who owns this setting for initial investigation. Please assign it back if the config service is not working as expected.

**Comment by JacksonKearl** [comment]
This is `as-designed`, unfortunately. The goal is to not allow tracking via images/etc requested from the readme, so the `readme` configuration value of `workbench.startupEditor` can not be set at a resource level (workspace settings, folder settings). I've updated the documentation to reflect this. 

`newUntitledFile` is documented to only apply in an empty workbench, so it would not make sense to set in a folder's settings. 

I tested `none`, `welcome`, and `gettingStarted` to work correctly, if you see otherwise that's a bug.
