### ISSUE TITLE
Suspend background windows to save memory

### ISSUE THREAD

**Issue by xgdgsc** [microsoft/vscode#124658]
Is it possible to implement an option to be able to suspend background windows (that haven' t been used for 2 days) to save memory. Something like the [Edge browser can do](https://www.howtogeek.com/712570/how-to-save-memory-with-sleeping-tabs-in-microsoft-edge/) . Would be useful for people with a lot of system workspaces and windows open that might be used once a week, and put to some background system workspace most times.

**Comment by deepak1556** [comment]
This is best achieved in the runtime and not at the application level. Also, we already get this resource management for free from the various optimizations chromium and v8 does for background tabs, for ex:
https://blog.chromium.org/2021/03/advanced-memory-management-and-more.html 
https://blog.chromium.org/2020/11/tab-throttling-and-more-performance.html

We have disabled the occlusion tracker on windows due to https://github.com/microsoft/vscode/issues/123257 but we are working to enable it back. There are places in the application code that can be adjusted to better work with visibility apis to conserve resources, any PR to fix that is welcome. But explicit option to suspend specific windows cannot be done without support from the runtime.
