### ISSUE TITLE
Open in new restricted window fails to support `--wait`, `--diff` and `--goto` CLI options

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#124618]
Steps to Reproduce:

1. Set up vs code as git commit message editor with `git config --global core.editor "code-insiders --wait"`
2. Attempt to commit from integrated terminal in a trusted empty window where the repo of the commit is not trusted
3. Choose open in new window

🐛 => command line will never return

**Comment by lszomoru** [comment]
Adding @bpasero as this seems to be related to the `--wait` CLI flag.

**Comment by lszomoru** [comment]
When using VSCode as the commit message editor, we try to reuse an already opened VSCode window. We either use the VSCode window that has the workspace to which we commit opened, or the last active window. In the case above, the 🐛 occurs only if 1) the workspace representing the repository to which we commit is not opened (if it were opened, the window would be in restricted mode so there would not be a prompt), and 2) the last active window is trusted.

A workaround for this scenario would be to use `git config --global core.editor "code-insiders --new-window --wait"`

**Comment by sbatten** [comment]
@gregvanl fyi for docs

**Comment by bpasero** [comment]
This is tough, hard to fix. The gist is that we are being asked to open editors and then may decide to open them in a new window and not the same window here:

https://github.com/microsoft/vscode/blob/541a5d4fa70ab3095f23b28b88914e1f6a8f65c4/src/vs/workbench/services/editor/browser/editorService.ts#L756

However, we fail to forward some of the environment that the original window is in:
* `waitMarkerFileURI`: this is a file that the command line process is waiting for to be deleted to return back to the process that triggered the `--wait` call (e.g. `git`) and it needs to be forwarded to the new window somehow
* `gotoLineMode`: this would be needed to properly open a file on a certain line if the user used `--goto` from the CLI
* `diffMode`: this would be needed to properly open a diff in the target window if the user used `--diff` from the CLI

I think this issue needs fixing somehow, otherwise the 3 scenarios are not working.

**Comment by bpasero** [comment]
I cannot fix this, sorry. We should document it maybe. 

I pushed a fix to support `--diff` at least.

**Comment by lszomoru** [comment]
Tagging @gregvanl to make sure that this is added to the docs.
