### ISSUE TITLE
how did it get so bloated?

### ISSUE THREAD

**Issue by edwardmeshuris** [Microsoft/vscode#12470]
leave it to microsoft to have it install helpers and all kinds of other junk. thanks, off to atom i go.

**Comment by Bill-Stewart** [comment]
Can you be more specific about your question?

**Comment by gertcuykens** [comment]
Can you be more specific please because currently vscode is used by a large audience and therefore your system can be very different then others. On my osx 10.11.6 vscode 1.5.3 i need 5 times less resources than chrome for example and i use allot of plugins

![image](https://cloud.githubusercontent.com/assets/863731/18759855/d5b1279e-80fe-11e6-9fed-529f553115c4.png)

![image](https://cloud.githubusercontent.com/assets/863731/18759910/0f15fdc0-80ff-11e6-95ca-148ff9dfdb2c.png)

![image](https://cloud.githubusercontent.com/assets/863731/18759939/2ef2b3cc-80ff-11e6-8122-aa444c4cc8b4.png)

**Comment by chrmarti** [comment]
A number of days has past without answer on the questions asked. I am thereby going to close this issue to clean up our backlog of issues. Once you can answer on the questions, the issue can be reopened again. Thanks for understanding this process!
