### ISSUE TITLE
Cannot launch multiple Java classes

### ISSUE THREAD

**Issue by curlyblueeagle** [microsoft/vscode#124711]
Does this issue occur when all extensions are disabled?: Yes/No
I need Java based extensions for my development, therefore have not tried this. 

I am still seeing the issue discussed in https://github.com/microsoft/vscode/issues/37589 which I thought was fixed
- VS Code Version: 1.56.2
- OS Version: macOS Mojave

Steps to Reproduce:

1. Run long running Java class 1 
2. Run Java class 2
3. The launch command for the second class will be executed in the same terminal rather spawning off a new one.

**Comment by testforstephen** [comment]
This only happens when the user is using "Run without Debugging" feature. Debugging multiple Java applications in terminal work well.

This is because Java debugger has special support for "Run" feature. If the user triggers a "Run" feature, the debugger generates a command line to the terminal in launch request, and then immediately terminates the debug session. Because when the user's application runs in terminal, the debugger loses control over the lifecycle of this application and keeping the debug session alive is meaningless. It seems that the VS Code client assumes that the previous session has ended and keep reusing the terminal for the subsequent session. That's not true for "noDebug" feature.

// @weinand

**Comment by isidorn** [comment]
Thanks for letting us know. So the gist is: "VS Code should not reuse terminals when Run Without Debugging session ends"

**Comment by testforstephen** [comment]
This is a solution. But I wonder if it is possible to detect that there is some process still running in the terminal and decide whether to reuse it or not. Since "Run" is more popular than "Debug" from Java debugger extension, I would still like to reuse the terminal as much as possible.

**Comment by isidorn** [comment]
@tyriar and @weinand would know better since they are the owners of the original code for terminal reuse from debug.

**Comment by weinand** [comment]
@testforstephen we are already trying to detect whether a process is running in the integrated terminal. If it is we are using a new integrated terminal.

**Comment by roblourens** [comment]
I tried this and it seems to work fine now. Let me know if you still see issues.
