### ISSUE TITLE
Type Definitions don't work in some Node.js Projects

### ISSUE THREAD

**Issue by WickedWizard3588** [microsoft/vscode#124753]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.56.2
- OS Version: Windows 10 21H1 Home Single Language

Global Type Definitions do not work when there is no `require` in a CommonJS File.
![image](https://user-images.githubusercontent.com/67627239/119827632-fd03c300-bf16-11eb-9de4-4e55adc1cbde.png)

But they when a module is `require`d. Does not work when a file is `require`d.
![image](https://user-images.githubusercontent.com/67627239/119827974-5bc93c80-bf17-11eb-9ba8-84c4e004c018.png)

Both the projects are dependency-less (no external dependency from npm has been installed)

Steps to Reproduce:

1. Create a new project with only package.json
2. Paste this script 
```js
const options = [
    'Option1',
    'Option2',
    'Option3',
];

const args = process.argv;
args.splice(0, 2);
``` 
3. See that there are no type definitions for `process`

**Comment by IllusionMH** [comment]
This works as expected - typings for node are provided by `@types/node` package and otherwise there is no global object `process`.

Without call to `require` VS Code doesn't know this is Node.js project and won't trigger [Automatic Type Acquisition (ATA)](https://code.visualstudio.com/docs/nodejs/working-with-javascript#_typings-and-automatic-type-acquisition) for `@types/node` package.

You either should have `require` (to implicitly trigger ATA) or better create `jsconfig.json` to explicitly include typings for node (and other TS/JS config options related to node settings - see example base files e.g. [node12.json](https://github.com/tsconfig/bases/blob/master/bases/node12.json))

**Comment by mjbvz** [comment]
Thanks for answering this @IllusionMH!

**Comment by WickedWizard3588** [comment]
Ok, Thank you
