### ISSUE TITLE
[Help] Mapping custom color definition into vscode color definition

### ISSUE THREAD

**Issue by backermanbd** [microsoft/vscode#124981]
I am using [this night owl theme](https://github.com/sdras/night-owl-vscode-theme) & want to map this custom color definition into vscode night owl color definition
but I don't know how to map these into vscode settings.json
Hope that you lot can help me
```
 {
    id: "night-owl",
    name: "Night Owl",
    highlights: {
      background: "#011627",
      text: "#abb2bf",
      variable: "#82AAFF",
      attribute: "#F78C6C",
      definition: "#82AAFF",
      keyword: "#c792ea",
      operator: "#c792ea",
      property: "#fff",
      number: "#F78C6C",
      string: "#ecc48d",
      comment: "#717a8a",
      meta: "#7fdbca",
      tag: "#7fdbca",
    },
  },
```

**Comment by IllusionMH** [comment]
/questions

You need to use `editor.tokenColorCustomizations`. See https://code.visualstudio.com/docs/getstarted/themes#_editor-syntax-highlighting for details

**Comment by IllusionMH** [comment]
/question

You need to use `editor.tokenColorCustomizations`. See https://code.visualstudio.com/docs/getstarted/themes#_editor-syntax-highlighting for details

**Comment by backermanbd** [comment]
@IllusionMH @vscode-triage-bot 
yes, I have checked these already before I made an issue here
here's my StackOverflow question https://stackoverflow.com/q/67775320/15770124

I don't know the correct syntax. therefore, I can't put the code (mentioned above) in my user settings.json
It just shows error.. vscode intellisense underlines them & shows they are unrecognized commands etcetera etcetera

**Comment by IllusionMH** [comment]
There is example in linked docs
![image](https://user-images.githubusercontent.com/1312662/120222818-3c991a80-c249-11eb-814e-55ddf38d39cd.png)

you just need to replace theme name inside of `[]` and put colors inside of object.

**Comment by backermanbd** [comment]
> @IllusionMH @vscode-triage-bot
> yes, I have checked these already, had asked a question in stackoverflow before I made an issue here
> here's my StackOverflow question https://stackoverflow.com/q/67775320/15770124
> 
> I don't know the correct syntax. therefore, I can't put the code (mentioned above) in my user settings.json
> It just shows error.. vscode intellisense underlines them & shows they are unrecognized commands etcetera etcetera

As i said

![Screenshot 2021-05-31 225700](https://user-images.githubusercontent.com/84121715/120223567-94447f80-c263-11eb-9791-df3b48507407.jpg)

**Comment by IllusionMH** [comment]
Where did you get this object with definitions? Doesn't looks like anything used in VSCode

It looks like list of simple color tokens (simple object with `key: value` map) but this simple form supports only `comments`, `strings`, `keywords`, `numbers`, `types`, `functions`, `variables` keys.

Looks like you should use `textMateRules` instead of simple map or even Semantic Highlighting,

TextMate rules can be overridden like
```json
"editor.tokenColorCustomizations": {
    "[Default Dark+]": {
        "textMateRules": [{
            "scope": ["constant.numeric"],
            "settings": {
                "foreground": "#FF0000",
                "fontStyle": "bold"
            }
        }]
    }
}
```
To get corresponding scope check out scopes used in extension (check `tokenColors` block) to better align with theme e.g. for `number` it can be ["constant.numeric", "constant.character.numeric"](https://github.com/sdras/night-owl-vscode-theme/blob/33ef8e835fde5df592dddeec63bc0c80d073bc24/themes/Night%20Owl-color-theme.json#L281-L288)

For other you should use [Scope Inspector](https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide#scope-inspector) (`textmate scopes` section)

However your case may be more related to Semantic highlights, although it has more complex definitions and not just plain object wit `key: value` structure. Moreover `definition`  is token modifier, not token type.

For sematic highlights check https://github.com/microsoft/vscode-extension-samples/tree/main/semantic-tokens-sample for example and https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide#theming for details

Background probably should be `editor.background` in `workbench.colorCustomizations`, not in `editor.tokenColorCustomizations`

**Comment by backermanbd** [comment]
I got this color definition from a developer who created the playground https://www.monolisa.dev/playground
