### ISSUE TITLE
Enable full-screen mode on iOS

### ISSUE THREAD

**Issue by tianzerun** [microsoft/vscode#124973]
Would you consider enabling the [full-screen mode](https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariHTMLRef/Articles/MetaTags.html) for vscode on iOS Safari? This can be done by adding the meta tag `<meta name="apple-mobile-web-app-capable" content="yes">`. It gets rid of the browser's user interface so more screen space is available for users.

Moreover, adding the [`shrink-to-fit=no`](https://developer.apple.com/library/archive/releasenotes/General/WhatsNewInSafari/Articles/Safari_9_0.html#//apple_ref/doc/uid/TP40014305-CH9-SW36) viewport attribute prevents the default scaling down behavior when content overflows.
https://github.com/microsoft/vscode/blob/427f48b8d17ff1e987918f04eec7f6e03a3f23d5/src/vs/code/browser/workbench/workbench.html#L11

Github Codespaces looks pretty good by having them on.
![11a9d6be23284cb0e0c554a9ff3334f0](https://user-images.githubusercontent.com/23252886/120181473-b1ffed80-c23f-11eb-845b-c00e21754dee.jpg)

**Comment by isidorn** [comment]
@tianzerun thanks for the suggestion. This makes sense and I plan to try it out.

**Comment by isidorn** [comment]
Did not have time unfortunetly, pushing out to August, since in July I am on vacation.

**Comment by isidorn** [comment]
@tianzerun I apologise for the slow response, I was on summer vacation.
First of all, we definitely want to enable full screen. Similar discussion https://github.com/microsoft/vscode/issues/106972

However I just tried the changes you propose and I could not see any change in behaviour.
I also tried Codespaces with what they have and I could not get into full-screen mode on my iPad. Is this something only for mobile?
If yes what are the exact changes that you see?

@bpasero I am not sure if we are open to these changes that might potentially only improve the phone experience. I am in general ok with this, since users might use the phone for some simple browsing.

fyi @alefragnani

**Comment by isidorn** [comment]
Once more info is provided I would open this issue. Thanks!

**Comment by LeuisKen** [comment]
I test this meta view port on iPad that works:

```html
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, minimal-ui"/>
<meta name="apple-mobile-web-app-capable" content="yes" />
```

It since that `minimal-ui` makes this feature work.

**Comment by hkhking** [comment]
i get it 😄

![IMG_06A1EE9671A8-1](https://user-images.githubusercontent.com/12771728/133418836-25b3908a-0591-4cee-a1f2-c652b30a78ff.jpeg)


os： ipados 15
device：ipad pro 2021 

step：
1、 pin icon to desktop
2、open & reload

**Comment by isidorn** [comment]
@LeuisKen I just tried your suggestion and it still does not work for me.
