### ISSUE TITLE
Ever time I reload the window extensions viewlet shows @workspaceUnsupported filter

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#125047]
I got into a state that whenever I reload the VS Code window the extensions viewlet filters item by the `@workspaceUnsupported` filter

Even if I search for something in that view and reload my search term is not preserved but the `@workspaceUnsupported` filter is still there

![Screenshot 2021-06-01 at 11 16 00](https://user-images.githubusercontent.com/1926584/120298897-c210df00-c2ca-11eb-8917-3d6cdff2456a.png)

**Comment by sandy081** [comment]
Seems to be coming from here 

https://github.com/microsoft/vscode/blob/dae2a9d4ebcb2673ad21da0ab15b116558ba8653/src/vs/workbench/contrib/extensions/browser/extensionsViewlet.ts#L532-L532

**Comment by isidorn** [comment]
Looks like a big issue imho, adding to this milestone...

**Comment by sandy081** [comment]
@sbatten May I know the reasoning behind showing this as default view in untrusted workspaces. Is not it too opinionated? I would expect an action somewhere to guide user to go that view.

**Comment by sandy081** [comment]
I see this still occurs on latest insiders

![Kapture 2021-06-03 at 17 03 45](https://user-images.githubusercontent.com/10746682/120667409-c1747600-c48d-11eb-90ff-7dc3027a82df.gif)

**Comment by sbatten** [comment]
This happens only when you reload a window with the extensions viewlet open. There is a short duration that needs to be awaited before the trust state is correct. Since the viewlet code is all sync, I cannot reliably get the right state.

We added this to make it easier for users to discover that they are in restricted mode. As they may not be aware of restricted mode but they may look in the extension viewlet to see what's going on.

**Comment by sbatten** [comment]
@sandy081 let me know if you want to bring this back into the milestone

**Comment by sandy081** [comment]
I have to say it is very annoying to me when I reload and I do not see installed extensions. As you see it shows empty view in trusted workspace which gives me broken experience. In an untrsuted workspace if I clear the `@workspaceUnsupported` filter text and reload and these views come back 🐛 . So I think we shall consider this in current milestone.

> We added this to make it easier for users to discover that they are in restricted mode. As they may not be aware of restricted mode but they may look in the extension viewlet to see what's going on.

I do not think current solution is the efficient way to achieve this. I think the banner on the top serves better to discover about the restricted mode and guide user to see what features (extensions and settings) are restricted. Showing unsupported extensions by default does not give much context of restricted workspace without going to the workspace trust editor. Settings editor does not show restricted settings by default and we guide user from Manage Workspace Trust editor which I think is good flow. I think the less aggressive/annoying way is to show a message in the top of the view with a link to show restricted extensions. If we would like to show unsupported extensions as default views then I would recommend to implement them as default views like other default views (installed, enabled...). Basically we need to revisit this in terms of UX and implementation.

Since we are too late in this milestone, I would suggest to revert this feature and track it in next milestone.

**Comment by isidorn** [comment]
I agree with @sandy081 
I thought we would not like the trusted UI to spill across the workbench and that is the point of the banner, as a replacement for that.

**Comment by sbatten** [comment]
reverted with https://github.com/microsoft/vscode/commit/0e6d07052c82dbafb4e387e7e0d5b9d565895491

**Comment by sbatten** [comment]
will revisit UX next milestone with https://github.com/microsoft/vscode/issues/125529

**Comment by meganrogge** [comment]
I can't get this to happen, so am verifying it.

**Comment by isidorn** [comment]
Yup, it is no longer happening. @meganrogge thanks for verifying
