### ISSUE TITLE
Improve Github Login

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#125074]
When logging in to Github in VS Code (Desktop), this website is shown:

![image](https://user-images.githubusercontent.com/2931520/120321830-0c528a00-c2e4-11eb-922c-2b9d1aa84e53.png)

Chrome prompts to launch VS Code Insiders and then VS Code Insiders prompts to call into the extension.
I think this could be improved.

When logging in to Facebook in Spotify, they don't do that.
Instead, they show this page:

![image](https://user-images.githubusercontent.com/2931520/120322951-45d7c500-c2e5-11eb-8da4-b9228e6bb507.png)

And when clicking on "Continue to the App", I'm magically signed in in Spotify.
Behind the scenes, spotify opens an http server and when clicking on "Continue to the App", they send a request to `http://127.0.0.1:4382/login?code=...`. This works nicely and without ugly prompts.

Also, I think the design of the github page in the screenshot could use some love.
The authorization token could be hidden by default and only shown when the user clicks on some "Didn't work?" button - for me, it works all the time.

**Comment by TylerLeonhardt** [comment]
> Chrome prompts to launch VS Code Insiders and then VS Code Insiders prompts to call into the extension.

I think a good first step of this issue is to get rid of VS Code prompting to call into the extension. We're in complete control of this flow so I don't see why we need to notify here.

**Comment by trusktr** [comment]
Sign in to GitHub doesn't even work for me at all on Ubuntu 20.04 with latest Firefox.

1. It takes me to that page screenshotted above.
2. When I click the browser prompt to continue to VS Code, nothing happens in VS Code except that the palette shows "Error" without any message.
3. I can not paste my auth code manually, because in VS Code there is no such message "Signing into github.com..." to click on. Nothing.
4. Atempting to do this over and over simply leads to the same result, never being able to log in.

**Comment by TylerLeonhardt** [comment]
I think we can close this now. The flow is quite different. We _do_ still use the Chrome redirection, but only because that is the best option. Using the http server is hard because in Remote scenarios, the GitHub Authentication extension may be running on the remote side.

We _do_ fallback to the http server if the Chrome redirection doesn't work ... and we fallback to Device Code flow if _that_ doesn't work... and there are notifications to get you through this.
