### ISSUE TITLE
No console output in edge dev tools

### ISSUE THREAD

**Issue by stevencl** [microsoft/vscode#125071]
Testing #125017

Create a launch config to launch edge. Start debugging. 
I see the following when I select the DevTools console:
![image](https://user-images.githubusercontent.com/1704059/120317008-02298f00-c2d6-11eb-81a3-1c370bc2e049.png)

But when I open the dev tools in the browser that was launched I see this:
![image](https://user-images.githubusercontent.com/1704059/120317152-30a76a00-c2d6-11eb-83e1-f7be5a8b07de.png)

**Comment by stevencl** [comment]
Note that I see this: 
![image](https://user-images.githubusercontent.com/1704059/120319703-33f02500-c2d9-11eb-9f85-b39a84c9ece2.png)

If I launch from the extension viewlet and launch an instance from there. But when I create a launch.json as described in the test description, I don't see the output.

**Comment by stevencl** [comment]
See my first comment.

**Comment by connor4312** [comment]
Where do you make the selection for the "Devtools Console"?

For a debug session you should generally use the Debug Console associated with that debug session. There should not be / you should not use one give by the Edge DevTools extension, and I'm not sure how you got to that state since there doesn't seem to be a similar console for me.

**Comment by stevencl** [comment]
From the drop down in the output panel.

**Comment by connor4312** [comment]
Oh, yea, I see that. I'll make an issue for them to hide that when attached to a debug session.
