### ISSUE TITLE
Why is createNotebookCellExecution on NotebookController

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#125056]
Testing #124993

If I understand the model correctly `createNotebookCellExecution` should only be called from a `NotebookExecuteHandler`. Would it make more sense to remove the method from the controller and pass something special into the handler?

**Comment by jrieken** [comment]
Good observation. We have done it that way so that a controller can create execution outsides of the normal execute-flow. One sample is cells depending on other cells. E.g to run cell B, cell A needs to be run. (you can observe that GH issue notebooks can cells that use a variable). Other samples is connecting to a kernel which already runs a certain cell or LiveShare scenarios. 

In fact, I thinking of taking this further and make the `executeHandler` optional. Think of a execute-cell-as-you-type scenario which doesn't need "run" button. 

@dbaeumer I would go ahead and close this but I am open to tweak the wording of this: https://github.com/microsoft/vscode/blob/6a02e8333c172e9f4433b13835bf58dd0533dd63/src/vs/vscode.d.ts#L11953-L11956

**Comment by dbaeumer** [comment]
The explanation make sense to me. Feel free to close.
