### ISSUE TITLE
Pin the Last Line of Text to the Bottom of the Terminal Pane

### ISSUE THREAD

**Issue by jorzech** [microsoft/vscode#125184]
Frequently I have the Terminal pane very small so I can see more code in the Editor. If I then execute a command in the Terminal, most of the output scrolls off the top of the Terminal pane.

To see more of the output, I grab the "sash" (?) and drag it upwards to resize the Terminal pane larger. But rather than exposing more of the command output, the bottom line of text (with the current command-prompt), is dragged upwards, too. It seems the last line of text is pinned to the top of the Terminal pane rather than to the bottom of the Terminal pane. In order to see the text that scrolled off the top of the pane, I have to first resize the pane, and then scroll the text.

This makes no sense to me. 
I would log this as a bug, but I suppose it may be desired functionality for some people, so I am making this feature request to allow me to pin the last line of text to the bottom of the Terminal pane.

I am using VS Code version 1.56.2 (user setup)

**Comment by Tyriar** [comment]
This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to our code. As such, I will go ahead and close it. Please try to reproduce in [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal-preview/9n0dx20hk701) and report to [microsoft/terminal](https://github.com/microsoft/terminal) with repro steps.

Thanks for understanding.

/label upstream terminal terminal-conpty
