### ISSUE TITLE
Confusing error message when dragging and dropping a git file

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#125193]
Testing #124848

1. With a changed file
2. Open the file from the SCM view (so that it is labeled `working tree`)
3. Now try dragging and dropping this editor to another window

**Bug**

![Screen Shot 2021-06-01 at 2 42 42 PM](https://user-images.githubusercontent.com/12821956/120394146-df07db00-c2e7-11eb-9716-682e9045f919.png)

We show an error message about not being able to read the `git:` file. I understand why this happens but think we could provide a nicer experience here. If we can't read the file, could we fall back to opening the on disk version of the file instead?

**Comment by bpasero** [comment]
> could we fall back to opening the on disk version of the file instead

Well, as far as the editor goes, there is a resource being dropped onto it that actually has a valid associated file system provider (`git`) but we will only figure out if the drop operation can work when doing the actual work of opening the editor, there is no fast way to check that before dropping (it would require an `async` stat call).

This file system provider is somewhat special in that it is actually only valid in the current window but likely not in other windows, but we currently have no notion of figuring this out.

Open for ideas how to improve this further, otherwise closing as designed.
