### ISSUE TITLE
Show a confirmation notification when installing/uninstalling shell commands

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#125145]
Testing #124841

While it's nice that this automatically works in the background, there was no confirmation in the tool that told me whether it succeeded or failed so I had to manually check. It would be nice if there was a toast that confirmed this. Similar to the settings editor that shows this on your first edit:

![image](https://user-images.githubusercontent.com/35271042/120371892-5418e780-c2cb-11eb-96d5-9d2ae658adc0.png)

**Comment by bpasero** [comment]
We are actually in the process of removing that notification: https://github.com/microsoft/vscode/pull/125083

I intentionally didn't want to show a notification, given this decision tree: https://github.com/microsoft/vscode/issues/119463#issuecomment-825663289

**Comment by misolori** [comment]
🤔  Hmm...I guess in the decision tree, `Does the user really need to be alerted?` you could make an argument for both sides. My issue is I ran an action and I don't know whether it worked or not and have to go check. So my confidence in it working is really low.

**Comment by bpasero** [comment]
I restored the previous message we used to show for both commands but I am using a modal dialog instead of a notification given it originates from a user action.

I think the decision tree should account for this actually, imho being blocked or not should not be the only criteria for deciding on using notifications vs a dialog. I would add that a dialog should be used when triggered by a user action such as a command.
