### ISSUE TITLE
Flicker on the ... menu next to a cell output

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#125109]
Testing #124995 on Windows

Here's what's happening in the following gif:
1. Click on another cell (not the one who's ... I'm about to click.
2. Click on the ... of the output cell.
3. The menu shows for a split second then goes away.
4. Click on the same ...
5. The menu now shows properly.

![recording (56)](https://user-images.githubusercontent.com/38270282/120338947-f8fbea80-c2f4-11eb-9f62-1afc756ac2cd.gif)

**Comment by rebornix** [comment]
The mouse click on the `...` should not change the editor focus, like the run button.

**Comment by roblourens** [comment]
I think we have a workaround for this on the cell toolbar, but I didn't think it would be necessary here because none of those actions depend on focus.

Also maybe it should respect `notebook.cellToolbarVisibility`

**Comment by alexr00** [comment]
Still repros for me

**Comment by roblourens** [comment]
Only on Windows it seems...

**Comment by roblourens** [comment]
This is like #103926 but it seems that issue can have an impact outside of just focus-related context keys. Basically, a context key (cell type, "cell has outputs", etc) changes in the parent CKS, but is overridden in the scoped CKS. So the effective value in the scoped CKS did not change, but the menu still tries to refresh itself and closes.

We have a hacky workaround for the original focus issue for the cell title toolbar

https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/notebook/browser/view/renderers/cellRenderer.ts#L212-L242

But actually this can impact any toolbar.

I can copy the workaround for the output toolbar for now. Or we can disable the consolidated output toolbar by default.

I still have no clue why it works on Linux but not Windows, since they should be using the same custom toolbar.

**Comment by roblourens** [comment]
In the sync today, the vote was to leave this alone since it isn't totally blocking and wasn't noticed in the past 2 or 3 weeks. I think we should either leave it for next month or disable `notebook.consolidatedOutputButton`.

**Comment by roblourens** [comment]
The issue is described in https://github.com/microsoft/vscode/issues/125109#issuecomment-854945097 and is really about menus in general. It's really annoying and there are some things I can do to fix it. Any one of these would be fine.

- Child CKS fires an onDidChange event when a value changes in its parent, even when that key is overridden by the child
  - I think we could check for this and not fire the event in this case at https://github.com/microsoft/vscode/blob/2297ad5c546b455421e942743e117a3c7c9a873a/src/vs/platform/contextkey/browser/contextKeyService.ts#L442. Would probably reduce a lot of noise/unnecessary updating in the workbench
- The Menu fires its onDidChange because some context keys were updated, but it doesn't check whether the actual list of menu items changed
  - Seems like it could diff the list of menu items to avoid this
- Calling setActions on the toolbar with an identical list of actions still causes it to hide
  - We could diff the actions to check that here, but that seems too late for that sort of check

**Comment by jrieken** [comment]
> Would probably reduce a lot of noise/unnecessary updating in the workbench. Would take a little refactoring - the onDidChangeContext doesn't contain enough info to do this.

I like that. Also, I do believe the `onDidChangeContext` knows enough, the child CKS service would need to know its keys and ask the event if any of those are affected. Otherwise the CKS should have access to all possible implementations of `IContextKeyChangeEvent`

> The Menu fires its onDidChange because some context keys were updated, but it doesn't check whether the actual list of menu items changed

Careful - context keys for menus control not just inclusion into the menu but also enablement and toggle-states. See how `_fillInKbExprKeys` is used [here](https://github.com/microsoft/vscode/blob/dafc40bca5439520d7e8b1c4a5c15c744bf69c10/src/vs/platform/actions/common/menuService.ts#L126)

**Comment by roblourens** [comment]
> the child CKS service would need to know its keys and ask the event if any of those are affected

I'm thinking the check has to be, whether _all_ of the keys in the event are contained within the child CKS, not _some_. The `affectsSome` method isn't enough for that but I think you are pointing out that I can just check all the implementations, and for example I can see the full list of keys on `ArrayContextKeyChangeEvent`.
