### ISSUE TITLE
"Create new github issue notebook" fails

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#125211]
Testing #124844

I do several iterations of randomly

- Run "Create new github issue notebook"
- Reload the window
- Save it
- Or run the create command and close it without saving

At some point, I get a notification that the command failed and see this error:

```
ERR NO notebook document for 'untitled:Untitled-1.github-issues?github-issues': Error: NO notebook document for 'untitled:Untitled-1.github-issues?github-issues'
at u.getNotebookDocument (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:84:202965)
at u.$acceptDirtyStateChanged (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:84:208771)
at d._doInvokeHandler (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:88:12797)
at d._invokeHandler (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:88:12489)
at d._receiveRequest (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:88:11145)
at d._receiveOneMessage (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:88:9945)
at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:88:8049
at a.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1835)
at _.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:15632)
at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:103:29788
at a.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1835)
at _.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:15632)
at t._receiveMessage (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:20890)
at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:17776
at a.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1835)
at c.acceptChunk (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:12993)
at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:12341
at Socket.E (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:103:13267)
at Socket.emit (events.js:315:20)
at addChunk (internal/streams/readable.js:309:12)
at readableAddChunk (internal/streams/readable.js:284:9)
at Socket.Readable.push (internal/streams/readable.js:223:10)
at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

I have hit it a couple times. I can't get good repro steps though.

**Comment by roblourens** [comment]
I think just this:

- Run the create command, don't save the notebook
- Reload the window
- The Untitled:1 notebook is still open
- Close it without saving
- Run the create command again, it fails

**Comment by jrieken** [comment]
@roblourens I cannot reproduce with those steps... Do you have anything else that needed for this to reproduce?

**Comment by bpasero** [comment]
Same, cannot repro.

**Comment by roblourens** [comment]
Still reproes for me with the steps in the comment. I can set a breakpoint somewhere, let me know.

**Comment by jrieken** [comment]
@roblourens do you have any special auto-save setting?

**Comment by roblourens** [comment]
Just `"files.autoSave": "afterDelay"` and nothing weird as far as I'm aware

**Comment by jrieken** [comment]
Still needs repo steps

**Comment by DonJayamanne** [comment]
I'm running into this locally and on CI (our tests in Jupyter Extension are failing as a result of this - when adopting the Notebook Serializer)

**Comment by roblourens** [comment]
I can still repro it with https://github.com/microsoft/vscode/issues/125211#issuecomment-852648515. What other steps do you need? Tell me where to set a breakpoint

**Comment by jrieken** [comment]
> Tell me where to set a breakpoint

I don't know. Start at the place of the error and than go backwards until you reach the caller

**Comment by DonJayamanne** [comment]
I've tried to debug this at my end and just when I know this are about to fail, thats when VSCode completely shuts down & crahes (FYI -I'm debugging using the chrome dev tools).
Will merge my changes into our main branch so that its easier for others to debug this.

**Comment by roblourens** [comment]
I don't really understand what's going on - following the steps in https://github.com/microsoft/vscode/issues/125211#issuecomment-852648515, after I reload the window and close the untitled editor, it seems like we remove the document in the EH side (via `$acceptDocumentAndEditorsDelta`), but don't release the model on the frontend. When I create a new untitled editor, it gets the old model (at https://github.com/Microsoft/vscode/blob/9bb711d3b6a56de77fa41e6b556d2e24ebe50463/src/vs/workbench/contrib/notebook/common/notebookEditorModelResolverServiceImpl.ts#L183 we don't create a new model).

I suppose something has a reference to it that isn't being released, but I don't know why we remove the document on the EH side if that's the case, and I don't know which reference isn't released.

**Comment by bpasero** [comment]
The fact that history uses the editor input serializer is debt and @Tyriar @meganrogge already brought this up for terminals. The history is the thing that drives the list of recently opened editors:

![image](https://user-images.githubusercontent.com/900690/122633108-26a7a880-d0d7-11eb-96e4-1d124bce7fe1.png)

It is not bound to any opened editor, and as such when you close all editors and restart, you still see e.g. the notebooks appearing in that list and you would expect you can click that entry to restore it.

In most cases this works fine because for a list of well known schemes we simply store just the resource:

https://github.com/microsoft/vscode/blob/3b4d9757e246dd924b792fbab90c41c00ec1cbec/src/vs/workbench/services/history/browser/history.ts#L574-L578

But in the case of untitled notebooks, we would indeed serialize the input and then restore it later. As such you might end up with 2 editor inputs.

With the work @lramos15 is doing to eventually drop any usage of `EditorInput` outside of the actual editor we will be able to address that issue and no longer require to call `serialize`.

PS: there is a second use-case for calling `serialize` which I think currently does not result in issues. When you close a notebook and hit `Cmd+Shift+T` we allow you to reopen that editor. For that we keep up to 10 serialized editors in an array for the user to restore from.

**Comment by jrieken** [comment]
> Assuming it's intended to be safe to call multiple times, I noticed that the same pattern exists in some other editor input files.

@bpasero please clarify. My assumption is that this isn't reentrant and that the caller of resolve sequentializes calls to `resolve`. I believe that otherwise the same issue happens [here](https://github.com/microsoft/vscode/blob/3b4d9757e246dd924b792fbab90c41c00ec1cbec/src/vs/workbench/contrib/files/browser/editors/fileEditorInput.ts#L341)

**Comment by bpasero** [comment]
@jrieken yeah everything should be fine from the moment we talk about working copies. No matter how many editor inputs you have and how parallel you call `resolve`, there is no issue with that.

But you might end up with multiple editor inputs (one from history, one from editor area) that could make things harder on you. Once #126728 is tackled, only editor area should deal with editor inputs.

**Comment by jrieken** [comment]
What I see is that these inputs are never disposed but they do get resolved. That's quite bad and I don't understand yet if the issue you are linked fixes this or not

https://github.com/microsoft/vscode/blob/c4f3f8f9bea635a0bd7d1aff29c55382597922fa/src/vs/workbench/services/workingCopy/common/workingCopyBackupTracker.ts#L285

**Comment by jrieken** [comment]
Oh, and many thanks to @roblourens for drilling into this. Idk what has changed but I am able to reproduce this now and @roblourens did find all the weak spots. The problems with the ref-counting is that we have references to disposable-models.  That disposable-model should only be disposed when the last reference is disposed but there are holes in the story and that means we end-up with cached references to models that are disposed...

**Comment by bpasero** [comment]
Those calls into editor input `resolve` from backup tracker are there to bring editors alive that have backups after a restart. Since you can have many editors open we want all those editors to show dirty indicators when they have backups.

Agree though that instead of calling into the `resolve` method of the input, it should probably be driven by something else. Though there really is no central place where working copies can be resolved in a generic way, as such it goes through the editor input resolver...

**Comment by jrieken** [comment]
> Those calls into editor input resolve from backup tracker are there to bring editors alive that have backups after a restart. Since you can have many editors open we want all those editors to show dirty indicators when they have backups.

I understand that but why does `workingCopyBackupTracker` call resolve on the input and not set input on the editor service? With the latter the normal "clean-up after editor close" flow would happen but today there is just a dangling, resolved input around

**Comment by jrieken** [comment]
> how parallel you call resolve, there should be no issue with that, and otherwise needs a fix if we know what goes south.

In my and your code you cannot call resolve in parallel because two or more calls might be waiting [here](https://github.com/microsoft/vscode/blob/3b4d9757e246dd924b792fbab90c41c00ec1cbec/src/vs/workbench/contrib/notebook/common/notebookEditorInput.ts#L213) (or [here](https://github.com/microsoft/vscode/blob/3b4d9757e246dd924b792fbab90c41c00ec1cbec/src/vs/workbench/contrib/files/browser/editors/fileEditorInput.ts#L342)) and the last await'ed code will overwrite the disposable property. So, you might be assigning [`this.cachedTextFileModelReference`](https://github.com/microsoft/vscode/blob/3b4d9757e246dd924b792fbab90c41c00ec1cbec/src/vs/workbench/contrib/files/browser/editors/fileEditorInput.ts#L342-L342) multiple times without disposing it multiple times

**Comment by bpasero** [comment]
There is a bit of overload on the term `resolve`. I was referring to the actual resolving of the working copy that goes into the manager, not the `resolve` of the editor input. The editor input `resolve` is very likely not fit for the way it is used now in some places.

**Comment by jrieken** [comment]
>  but there are holes in the story and that means we end-up with cached references to models that are disposed...

Talking about these holes... The problem roots here: https://github.com/microsoft/vscode/blob/285673fd5cf70012c7ad1353c789d2e51dedc3e4/src/vs/workbench/contrib/notebook/common/notebookEditorModel.ts#L512

The working copy model is going to be disposed (which disposes the underlying notebook and updates the extension host) despite its owning reference not being disposed yet (there is still one reference from the backup tracker). @bpasero I am now confused and don't remember why that code is the way it is. Who is holding the "truth"? Ideally it is the references that triggered the creation of the working copy but it seems that disposing (of untitled) happens on a side channel

<img width="1524" alt="Screen Shot 2021-06-21 at 12 19 27" src="https://user-images.githubusercontent.com/1794099/122747527-716a2180-d28b-11eb-9b4a-5757f23503a1.png">

**Comment by bpasero** [comment]
@jrieken could it be this:

https://github.com/microsoft/vscode/blob/64bf8ca93f56958652721bc4cf0827956840f5a7/src/vs/workbench/services/workingCopy/common/untitledFileWorkingCopy.ts#L284-L284

I `dispose` the untitled working copy upon `revert` which maybe is not clever. This seems to be the only place in working copy land where a working copy is disposed from within.

Can you comment out that line to see what it brings? One downside is that it might then require you as consumer of untitled working copy to dispose the working copy when it is reverted...

**Comment by jrieken** [comment]
Yes - when I uncomment that line the first untitled notebook isn't disposed* and the second time the create command is run it will create `Untitled-2`. 

*) The notebook isn't disposed because `workingCopyBackupTracker` is leaking references

**Comment by bpasero** [comment]
@jrieken in https://github.com/microsoft/vscode/tree/ben/125211 I have a change where the `resolve` now has to be implemented by the provider of the working copies. For notebooks there is 2 places (simple / complex):

https://github.com/microsoft/vscode/blob/c64a443ccf57f6abbe96a8c2bc99ffe05dce8bac/src/vs/workbench/contrib/notebook/browser/notebook.contribution.ts#L503-L503

https://github.com/microsoft/vscode/blob/c64a443ccf57f6abbe96a8c2bc99ffe05dce8bac/src/vs/workbench/contrib/notebook/browser/notebook.contribution.ts#L545-L545

This method will be called when after startup all editors with backups have either been restored or opened (in case not yet opened) in order to bring the backups to live within these editors.

Is there some method we can use instead of the current `NotebookEditorInput.resolve` to get the right ref counting?

**Comment by jrieken** [comment]
I am sure how that helps? Someone creates and resolves an editor input but doesn't dispose that input. Isn't that the problem and that should be solved?

**Comment by bpasero** [comment]
@jrieken let me tell you what happens in order of events:
- the user in a window has multiple editors (doesnt matter which type) open in 1 group over many tabs and all are dirty
- now the user reloads window or restarts
- the backup tracker sees that backups exist and wants to restore them
- the tracker will first figure out if the associated editors for the backups are open and if not create them (doesnt apply here)
- now the tracker needs to make sure the working copies are actually resolved from the backup so that the user sees the same number of dirty tabs as before

That last requirement is where I dont know what else I can do other than asking the notebook component to resolve that editor? Whats the alternative here, I could go over each editor and call openEditor on it but that is stupid because we dont want to make editors active?

**Comment by bpasero** [comment]
Here is the scenario, which btw already applies today to stored notebooks:

![recording](https://user-images.githubusercontent.com/900690/122804068-b613ae00-d2c7-11eb-93fd-c7db0a45d1ea.gif)

If we were to not `resolve` the editors that are not active, they would not load their backups and not report dirty.

We need some way for the tracker to trigger the resolve, it is almost like a `openEditor` call but without making the editor active.

**Comment by rebornix** [comment]
If I didn't have a chat with Rob today I wouldn't know there is already a discussion about how backup and historyService handles non-file editor inputs ;( Spent a day on this and ended up with same findings:

* https://github.com/microsoft/vscode/issues/126855
* https://github.com/microsoft/vscode/issues/126853

**Comment by jrieken** [comment]
> If we were to not resolve the editors that are not active, they would not load their backups and not report dirty.

I am not against calling `resolve` but the problem is that the caller doesn't dispose the inputs and thereby leaks. If there is a way for the backup tracker to know that the input isn't needed anymore than it can just clean-up, e.g why doesn't the backup tracker listen to `EditorInput#onDidChangeDirty` and dispose inputs when they turn non-dirty?

**Comment by bpasero** [comment]
@jrieken yeah I think that could work. I think the `resolveEditor` method that I added should return a `IDisposable`. But the backup tracker would really just do this:

```ts
const disposable = await resolveEditor(...
disposable.dispose();
```

Because as far as the tracker is concerned, the job is done after the editor got resolved. And since the editor is opened by then anyway, the dispose call should not do anything bad, just reduce the ref counter?

**Comment by jrieken** [comment]
> And since the editor is opened by then anyway, the dispose call should not do anything bad, just reduce the ref counter?

Yes, I believe so. There is [_openMissingDirtyNotebookEditors](https://github.com/microsoft/vscode/blob/e7ed3023f06adb2e3ffdb23ec511eaa480db5030/src/vs/workbench/contrib/notebook/browser/notebook.contribution.ts#L468-L468) which ensures there is an editor for each dirty notebook model... Tho, that is being used via debouncing and I don't know if that's a problem or not (the debounce is also not really needed esp not if it's a problem). 

What I don't understand is the `resolveEditor` abstraction. There is already an editor input with resolve and dispose and I don't see the extra benefit of this new indirection.

**Comment by bpasero** [comment]
@jrieken well, `EditorInput#resolve()` does not return a `IDisposable` and I cannot dispose the `EditorInput` itself because that one was restored as a tab and is proper.

**Comment by jrieken** [comment]
> @jrieken well, EditorInput#resolve() does not return a IDisposable and I cannot dispose the EditorInput itself because that one was restored as a tab and is proper.

That's the problem of the backup tracker: editor inputs are heavy objects that must be disposed or handed off to someone that takes ownership to dispose them.

**Comment by bpasero** [comment]
@jrieken yeah that's the thing, the editor input is already owned by the notebook component because that one originally created it and now it was just restored after window reload. 

I am not sure this call the backup tracker has to make should be disposable because in the same way, `openEditor` is also not disposable, the lifecycle is bound to the editor tab that opens.

Here the backup tracker already has the editor input in hand but wants to resolve it. As I mentioned before, the workaround for the tracker would be to call `openEditor` on each editor that has a backup so that the associated editor control can take proper ownership. The downside is that this would make each editor with backup briefly visible because only a visible editor will resolve an editor input.

**Comment by jrieken** [comment]
> @jrieken yeah that's the thing, the editor input is already owned by the notebook component because that one originally created it and now it was just restored after window reload.

🤔 that's a fun definition of object ownership... Com'on, you call the constructor, you call dispose. That's how it's done. Why are we arguing about that?

**Comment by bpasero** [comment]
Lot's of things went wrong here but it should be fine now:
* the history is no longer instantiating editor inputs, but only keeping "untyped" inputs around, as such the truth of editor inputs lives in the editor area and not elsewhere (via https://github.com/microsoft/vscode/commit/97d770d4edf9d8ed44d02ab2b1cef284e6d1dc29)
* because of that, we no longer "side load" a notebook model into the history input that leaks (file editors never suffered from this because they are implemented in a way that only 1 input exists for any given resource)
* turns out the implementation of the working copy editor handler actually [had a bug](https://github.com/microsoft/vscode/commit/1cbe2eb70bb2b9343f974cf24b0236c7bb04d126#diff-526c9917a850212febfac51bc2e8e64da14477f791d315cb134624a8941f4d8fR502) where I missed a `isEqual` check

I tested this now with 1 untitled notebook (the original steps from Rob), but also multiple untitled notebooks and can no longer reproduce.

---

The backup tracker remains unchanged and I also cannot reproduce https://github.com/microsoft/vscode/issues/126853 with the changes that went in. If someone still wants to learn more about why the tracker has to `resolve` editor inputs, I suggest to do that in a call and not in this issue because I seem unable to explain the intent.

**Comment by jrieken** [comment]
Pushed another change to ensure `NotebookEditorInput#resolve` is safe for re-entrant calls. The backup tracker and the editor tab restoring would happen at the same time (esp when things are slow) and than https://github.com/microsoft/vscode/issues/126853 would show.

**Comment by bpasero** [comment]
Pushed a change that the backup tracker will no longer call `resolve` on editors that are active already. This prevents a race condition between the tracker calling `resolve` and the actual editor calling `resolve`.

@jrieken looking at your change, maybe it needs to be changed because I think you are caching too aggressively now. In the end, the notebook editor [will call](https://github.com/microsoft/vscode/blob/903e219ccb8f8a0bccf8ffce33b79cb66bd9a4f4/src/vs/workbench/contrib/notebook/browser/notebookEditor.ts#L196-L196) `resolve` anytime `setInput` is called on it. This can happen for example when a user clicks through tabs and thus makes notebook editors active.

With the change of caching the promise, `resolve` is a no-op when the promise already exists, however there is one case in the `resolve` method where we still want to forward the request:

https://github.com/microsoft/vscode/blob/62db4e23d4e744742368088284bb2bba804d4963/src/vs/workbench/contrib/notebook/common/notebookEditorInput.ts#L235-L235

This instructs the model to `load`, which ends up somewhere in the working copy stack where we protect against multiple re-entrant calls.

**tl;dr:** either drop the caching of the promise now that I fixed the backup tracker, or preserve the behaviour that any call to `resolve` will trigger `this._editorModelReference.object.load` 👍

**Comment by jrieken** [comment]
Thanks for pointing that out. I have pushed a better fix for the re-entrant case which allows/detects reentrance and simply disposes extra references (in that case it also skips the extra load because the model has just been loaded...)

This does raise the question iff my `load` is proper: https://github.com/microsoft/vscode/blob/79ab6d7988334b0a66836c569a9f02f11331ad42/src/vs/workbench/contrib/notebook/common/notebookEditorModel.ts#L515

It's a no-op when I have a working copy already and I wonder if `resolve` must be called on the (existing) working copy?

**Comment by bpasero** [comment]
@jrieken hm good point, maybe part of the complication is that the input can resolve both simple and complex notebook models. I am actually surprised this isn't causing any issues, though in most cases this helps for updating the content in case a file event is missed which is maybe not happening that often.

The idea is, that every call to `EditorInput.resolve` should end up in a call to `IFileWorkingCopyManager.resolve`. The manager makes sure to only create 1 working copy and is also fit for re-entrant calls.

For example, the file editor input (who is not yet using file working copy, but the code is the same), forwards every resolve into the manager:

https://github.com/microsoft/vscode/blob/9b984212c3eec1d97404dcd946ad8f77d7a961d9/src/vs/workbench/contrib/files/browser/editors/fileEditorInput.ts#L332-L332

Maybe we discuss this again in a call and I can show what happens for file editors. I have a feeling that there is something missing to bridge between the ref counted world and the file working copy manager.

**Comment by bpasero** [comment]
To clarify: calling `IFileWorkingCopyManager#resolve` is maybe misleading. Not every call results in a working copy being created, only the first one does. Subsequent calls will just trigger updates or reload it. I didn't want to introduce 2 methods (`create` + `reload`) to make the calling side simpler, but don't have strong feelings either.
