### ISSUE TITLE
Support intellisense in workbench.editorAssociations

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#125205]
<img width="539" alt="Screen Shot 2021-06-01 at 5 02 58 PM" src="https://user-images.githubusercontent.com/2193314/120404447-3a8f9400-c2fb-11eb-950b-3613464ef4e7.png">

**Comment by lramos15** [comment]
@mjbvz Do you mind linking the codepointer you had for this again? I lost it from when it was posted awhile ago. If not I'll just go hunting for more samples :)

**Comment by mjbvz** [comment]
Yes this used to work but I think [this change](https://github.com/microsoft/vscode/commit/f3bb41a804b941fcddd079c67417146ee88c7461) deleted the code

The key part was where it was `updateEditorAssociationsSchema` and the original schema definition using `anyOf`. The same general approach should work with an object literal instead of the array, but you'll have to update the schema structure

**Comment by lramos15** [comment]
Thanks! While yes this is a regression, the thought process behind removing it came due to three parts.
1. No other unspecified key -> value settings that I know of have intellisense such as `files.associations` which is very similar.
2. The intellisense provided in the old case would suggest all editors and not take into account what would work with a given file extension
3. The configuration of this setting is most likely do through the notification about conflicting defaults or the reopen with picker.

**Comment by Tyriar** [comment]
@lramos15 sounds like this was behaving better than other settings and it's good to show all editors imo.

**Comment by bpasero** [comment]
> There is a command to get a list of all registered editors for auto-locking

You mean I can use the resolver service to get all registered editors right? Would that account for custom editors from extensions (like Hex editor) too?

**Comment by lramos15** [comment]
> You mean I can use the resolver service to get all registered editors right? Would that account for custom editors from extensions (like Hex editor) too?

Yeah, I don't know why I called it a command it's just a method on the editor resolver service. This function in particular https://github.com/microsoft/vscode/blob/ed3cf121498c6ce57ffbadf831e5d7b9f8222a6e/src/vs/workbench/services/editor/common/editorResolverService.ts#L153-L158 although would need to add a flag for all editors as we ignore exclusive editors since this function is primarily there to know when to show the open with context menu

**Comment by lramos15** [comment]
Nothing crazy but I feel anything crazier might be annoying. We just now suggest editor Ids for whatever key you choose.
