### ISSUE TITLE
Cannot push newly created branch without pushing it from the command line

### ISSUE THREAD

**Issue by technicalpickles** [microsoft/vscode#125297]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.56.2, VS Code Insiders 1.57.0-insider

- OS Version: macOS 11.2.3

Steps to Reproduce:

1. Open a directory that is version controlled with git
2. Use `git checkout -b <branch>` in the terminal to start a new branch
3.  Make some changes, use Source Control pane to commit them
4. Try to use Source Control pane to push
5. See an error:

![CleanShot 2021-06-02 at 10 26 35](https://user-images.githubusercontent.com/159/120498253-154b6600-c38d-11eb-8293-af643305c5c4.png)

Workaround:

1. Use `git push -u <remote> <branch>` at least once first

**Comment by lramos15** [comment]
The cloud icon in the status bar doesn't work for you?

**Comment by lszomoru** [comment]
@technicalpickles, apologies for not getting back to you on this until now. I see that the issue was originally file for VS Code 1.56, and given that there have been quite some changes in the source control area I was wondering if you could check if you are able to reproduce the issue with the latest `Insiders` release. 

Using the latest `Insiders` release here is what I am seeing using the default settings:
1. After running `git checkout -b test` I am seeing the `Publish Branch` button in the SCM viewlet. Pressing the button successfully pushes the branch to the remote. 
    <img width="412" alt="image" src="https://user-images.githubusercontent.com/3372902/151400682-c1fbb8a6-69cd-4303-8216-ff015fe36f93.png">

2. After running  `git commit -m "test" --allow-empty` I am seeing a `Sync Changes` button in the SCM viewlet.  Pressing the button successfully pushed the commit to the remote.
    <img width="415" alt="image" src="https://user-images.githubusercontent.com/3372902/151400924-be058b74-0e69-418d-bae2-2771a4860b07.png">

**Comment by aeschli** [comment]
I tried the steps from https://github.com/microsoft/vscode/issues/125297#issuecomment-950939130 and they publishing/pushing from the UI worked for me

Version: 1.66.0-insider
Commit: 2eebd2a0159af379057a58c8bcb519f95bfd6328
Date: 2022-03-23T05:16:17.528Z
Electron: 17.1.2
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Linux x64 5.14.0-1029-oem
