### ISSUE TITLE
Getting started - narrow horizontal space - step preview appears on top which is confusing

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#125249]
Testing #125014

Pls see the screenshot below. Showing the step details at the bottom could be more natural

![image](https://user-images.githubusercontent.com/172399/120455528-226c5300-c395-11eb-87b2-93243c2398e9.png)

**Comment by eamodio** [comment]
Yeah, having it stacked like this -- makes it quite hard to understand what you are doing -- because the context of the top part if below it.

![image](https://user-images.githubusercontent.com/641685/120562433-6468b980-c3d4-11eb-9535-8d6a76b0c292.png)

Maybe that section should always have some text saying that you should select a layout?

**Comment by misolori** [comment]
@JacksonKearl already made the change to move this to the bottom:

<img width="748" alt="CleanShot 2021-06-04 at 09 56 34@2x" src="https://user-images.githubusercontent.com/35271042/120837097-2924d280-c51b-11eb-806b-9ed89016b0c8.png">
