### ISSUE TITLE
iPad: lack of ESC makes is hard to dismiss Quickpicks

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#125284]
- select "Open file" action
- try to dismiss the Quickpick

Observe: there is no intuitive way to dismiss the Quickpick

It would be helpful if the Quickpick always had a "Cancel" or "X" (Close) affordance.
Alternatively (or in addition) a "tap" outside the Quickpick area should also close it.
 
Workaround: reload page

**Comment by isidorn** [comment]
I agree this is a good point. There should be some X affordance.

Also assigning to @TylerLeonhardt as the QuickPick owner to get his thoughts

**Comment by TylerLeonhardt** [comment]
If a quickpick has a title bar, I like the idea of adding an X affordance to it...however, I can't visualize a good looking X affordance when the title bar is not visible.

**Comment by misolori** [comment]
I noticed that there are specific quick picks that will disable the esc/tapping outside to dismiss the quick pick. The opening remote quick pick does this but others like the command palette work just as fine. 

As an alternative we could add an `x` to the right side of the input box like:


![image](https://user-images.githubusercontent.com/35271042/120520776-0d89c280-c389-11eb-95ec-214d41fa2980.png)

**Comment by TylerLeonhardt** [comment]
> As an alternative we could add an x to the right side of the input box like:

kinda makes me feel like it will clear the text in the quick pick, not close it entirely.

> Or something more iOS-like:

I'm concerned about having a Cancel button and including it in the buttons that authors can contribute like so:

https://github.com/microsoft/vscode/issues/125051

**Comment by misolori** [comment]
I think there's a way to have all of these live together, I can mockup some combinations and then discuss them in our ux channel. Slack does something similar:

<img width="541" alt="CleanShot 2021-06-02 at 10 26 32@2x" src="https://user-images.githubusercontent.com/35271042/120525573-1bd9dd80-c38d-11eb-907f-03c23296b5c1.png">

**Comment by isidorn** [comment]
@misolori great sketches. I would prefer the text, as it aligns better with other iOS apps. Though "Close" might be better than "Cancel"...
@TylerLeonhardt is it ok if I assign this to June so we discuss this in one of the UX meetings and try to figure this out.

**Comment by TylerLeonhardt** [comment]
Sounds good!

**Comment by alefragnani** [comment]
I’m not sure everyone is aware but, even without an ESC key on Apple Keyboards, you can use the _undocumented_ system-wide `Cmd .` (Command-period) keyboard shortcut. 

BTW, the VS Code QuickPick works perfectly with it 😬

**Comment by isidorn** [comment]
@alefragnani thanks for the tip, I was not aware of it.
However I still think we need something to make this more discoverable...

**Comment by alefragnani** [comment]
Glad to help!

Sure, I totally agree it should be more discoverable... I liked the Slack like mockup provided above (which I guess appears on browser version). But I'm not entirely sure if you would add that on tooltips / placeholders / messages, because it isn't officially documented. 

I would like to have that, but I understand if you don't do.

**Comment by misolori** [comment]
Here's two ideas that I drew up, either we try to do something inside of the input box (icons) or we add text on the outside. I also added a "Clear" action as we do that in the Settings search and would help distinguish between close and clear. Let me know what everyone thinks.

<img width="2020" alt="CleanShot 2021-06-04 at 08 18 20@2x" src="https://user-images.githubusercontent.com/35271042/120824743-96316b80-c50d-11eb-8f44-fef7c0c52690.png">

**Comment by isidorn** [comment]
I think both are great. Slight personal preference towards `Text` approach since I feel that is more iPad like...

**Comment by misolori** [comment]
The other question we need to answer: is this for all quick picks (meaning for Desktop) or just scoped for iPad? My gut tells me to have this applied to all.

**Comment by isidorn** [comment]
I would not mind having it always for consistency and to make it easier for users that do not use the keyboard (but only the mouse). Though let's bring it up in a UX meeting and see what do people think

fyi @bpasero since he might be interested

**Comment by alefragnani** [comment]
I agree with @isidorn , and prefer the `Text` approach too. 

I'm not sure it is on iOS guidelines (it's been a while I don't look at them), but it seems iOS uses `Cancel` instead of `Close` in this case, just like @misolori mocked above. At least, this is what I could see while playing a little with a few native and non native apps.

**Comment by TylerLeonhardt** [comment]
Personally I prefer the `x`... 😅 

Another detail I wanted to bring up... We could also only show the `x`/`close` only when the quick pick has `ignoreFocusOut` set since if `ignoreFocusOut` isn't set, then the user just has to tap anywhere else in the window to close the quick pick which, if we're catering to the tapping users with this work, is more ideal than an `x`/`close` button.

**Comment by alefragnani** [comment]
@TylerLeonhardt Being the new owner of the Quick Pick API, does gives you double point while voting? 😂

**Comment by bpasero** [comment]
Sorry for being a bit late to this issue and thanks Isi for pinging me, I would like to give my thoughts on it. 

André observed that some (not all) quick pickers cannot be dismissed. It is true that we have an internal option for quick pick to keep it open even when focus is lost. The motivation for this is that quick pick is maybe asking for some input (like a password) that the user needs to copy to clipboard from another application so we want to avoid that the picker closes when the user jumps to another application and then back into VSCode. The only way to close quick pick in this case is to press ESC.

To be honest, I am not a big fan of making quick pick anymore complex with how it looks and would not be a big fan of seeing another control to close quick pick, but I do acknowledge that without a keyboard attached, the picker is too sticky.

Some ideas:
* we simply disable the support for keeping quick pick open on iPad and if no keyboard is attached (the scenario for keeping it open on focus lost is probably more a scenario on the desktop than on iPad)
* if we really want to keep the support for this on iPad, limit the close button to pickers that do not close on focus lost

I would prefer the first solution and see how it goes.

**Comment by isidorn** [comment]
@bpasero Thanks for jumping in. I think a form of this idea was also proposed by @weinand in his initial comment
> Alternatively (or in addition) a "tap" outside the Quickpick area should also close it.

I like this approach a lot since as you suggested having a stable QuickPick is more for being able to change windows and come back and it is still there. And this scenario might not be so common on the iPad.

Since this is low hanging fruit, and might just work intuitvily I suggest that we just start with that.
We could do it start of the milestone so we have enough time to gather feedback

@TylerLeonhardt what do you think?

**Comment by TylerLeonhardt** [comment]
^ That commit makes it so even if a quick pick has `ignoreFocusOut` set, on iPad it will still hide the quick pick on Focus Out.

Verification:
* Select "Open file" action
* Tap outside of the quickpick anywhere

**Comment by isidorn** [comment]
Great, thanks!
Adding bug label so I get this verified.
