### ISSUE TITLE
Inline Completions Are Interrupted By The Suggest Widget

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#125298]
Feedback from @isidorn:

If the inline completion is being shown, and the user is typing something that is being matched nicely with the inline completion the suggest widget should not auto pop out and ruin the party.
Same for the other way around (which already works): if the user has the suggest widget and is typing some good match I would not expect the inline completion to show automatically.

**Comment by eamodio** [comment]
I feel like the inline completion should in some way mix with the suggest widget rather than be an either or. Like if there is an inline completion, the suggest widget can show, but it doesn't auto-select anything, so you'd have to arrow down to the first time (to break out of the inline one). Or something like that.

**Comment by isidorn** [comment]
@eamodio I provided very similar feedback in https://github.com/microsoft/vscode-internalbacklog/issues/2154

**Comment by hediet** [comment]
Fixed by https://github.com/microsoft/vscode/pull/126413.

Sorry for not addressing this earlier. I'm still not 100% convinced this gives the best user experience.

**Comment by hediet** [comment]
Verification steps:
Type a suggestion as suggested by Copilot (yeay, we can finally mention it publically).
Notice that the autocompletion should not pop up.
