### ISSUE TITLE
Why does notebook.cellToolbarVisibility setting does not have hide option?

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#125223]
Testing #125013

cell tool bar visibility can be configured using `notebook.cellToolbarLocation` setting but there is another setting `notebook.cellToolbarVisibility` that can be confused with visibility of cell toolbar

**Comment by roblourens** [comment]
Should we move "hidden" to the "visibility" setting? cc @rebornix @misolori

**Comment by misolori** [comment]
Ah i do think the name here is confusing, this is essentially what controls HOW the toolbar appears, so maybe another name would be better? `notebook.cellToolbarInteraction`? I also don't know whether we shouldn't broadcast this settings and just go with a default and remove the setting, so far we haven't seen any complaints since the default was changed.

**Comment by roblourens** [comment]
I think the jupyter team might not like it, since they don't want to have to click twice to get the run above/below actions

**Comment by rebornix** [comment]
> and our run button is always visible on hover (actually that difference feels weird too)

The output action is always visible, no matter if the cell has focus or not, or if it has hover. It's weird that the cell toolbar, run button and output button have different interaction behavior.
