### ISSUE TITLE
No IntelliSense/AutoComplete when insert snippet `<div></div>` in tsx/jsx.

### ISSUE THREAD

**Issue by heroboy** [microsoft/vscode#125357]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.56.2
- OS Version: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. create a user key binding:
```json
{
		"key": "alt+w",
		"command": "editor.action.insertSnippet",
		"when": "editorTextFocus && editorLangId==typescriptreact || editorTextFocus && editorLangId==javascriptreact",
		"args": {
			"snippet": "<${1:div}${0}>$TM_SELECTED_TEXT</${1:div}>"
		}
}
```
When press `alt+w`, it will insert `<div></div>` and select both `div`.

2. create a tsx file, and input `let x = ` , press `alt+w`

3. Try to input `span`, there no any autocomplete list showing.

But if you manualy input `<div></div>`,
place the cursor at the first `div`,
then use `alt+click` to select the two `div`, 
the autocomplete will show. 
And if the cursor is not firstly placed at the first `div`, for example at the second `div`, the autocomplet will not show.

**Comment by jrieken** [comment]
When a snippet is active, IntelliSense as you type (aka quick suggestions) is disabled. That is because there is a conflict between the <kbd>Tab</kbd>-key which moves to the next placeholder but also accepts a completion. You wouldn't be able to type in a placeholder and then move to the next placeholder as you would accept a suggestion then. You have the following options

* change the default via the `editor.suggest.snippetsPreventQuickSuggestions`-setting
* in snippets trigger suggestions manually (via Ctrl+Space, Alt+ESC (macOS), or `ctrl/cmd+i`)
