### ISSUE TITLE
Don't ask for opening the workspace file when restoring a window

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#125315]
Testing #124837

I opened `microsoft/vscode-jupyter` as a Remote Repository. Every time the window is restored I get the notification. It's OK to show it when I open the folder, but when restoring we know the user's decision.

![image](https://user-images.githubusercontent.com/4674940/120525389-f1882000-c38c-11eb-8874-d8d1e4bc24d7.png)

**Comment by bpasero** [comment]
Unfortunately we currently do not know whether the window was restored or opened newly. One thing we could do is show this notification only once and then never again?

//cc @isidorn who earlier expressed that this notification should not be so spammy

**Comment by isidorn** [comment]
Here's the other issue for reference https://github.com/microsoft/vscode/issues/121805

**Comment by bpasero** [comment]
Since we are working towards reducing notification spam, especially on startup, I have decided to make the notification a silent one (only appearing in notification center) when you open a workspace you had opened before. Via https://github.com/microsoft/vscode/commit/4f3f43190820d687786df37c9bb9b64c735c338b

**Comment by isidorn** [comment]
Awesome, thanks a lot!
I can verify this.
