### ISSUE TITLE
Locked out of dev container after distrusting it

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#125342]
- Open dev container in trusted workspace
- Open trust management window
- "Don't Trust" the container, because I wanted to test something in an untrusted window
- The window reloads, says "Opening Remote" forever and never connects

Is something else supposed to happen? Should I get the trust dialog again instead? I can work around it by opening the trust manager in another window and adding the container folder. I can't open it in this window that is trying to open the container.

**Comment by sbatten** [comment]
Essentially, the extension was trying to make a request to trust the workspace but since the resolver wasn't done, the handler had not been registered yet. 

For now, I've split that out from the workbench contribution into a separate one. Since the trust request service is separate now from the management service, we could probably just move this dialog logic into the service itself.
