### ISSUE TITLE
Odd terminal scrolling behaviour

### ISSUE THREAD

**Issue by SetTrend** [microsoft/vscode#125434]
### Issue Description

I am experiencing a problem with the terminal scrolling behaviour when switching from side panel view to full panel view:

![Strange scrolling behaviour](https://user-images.githubusercontent.com/9283914/117493211-f8309c80-af72-11eb-8db7-365aae3850e9.gif)

/ref: [vscode-powershell#3344](/PowerShell/vscode-powershell/issues/3344)
/ref: [PSReadLine#2450](/PowerShell/PSReadLine/issues/2450)

#### Expected Behaviour

When I hit the `ARROW UP` key, I would expect to see different versions of my execution history, but I don't expect a scrolling behaviour.

#### Actual Behaviour

When I hit the `ARROW UP` key after having switched the PowerShell terminal from side panel to full panel, scrolling is performed that's mimicking the previous side panel layout.
<hr/>

- VS Code/OS Version:
   ```
   Version: 1.56.2 (user setup)
   Commit: 054a9295330880ed74ceaedda236253b4f39a335
   Datum: 2021-05-12T17:13:13.157Z
   Electron: 12.0.4
   Chrome: 89.0.4389.114
   Node.js: 14.16.0
   V8: 8.9.255.24-electron.0
   Betriebssystem: Windows_NT x64 10.0.19042
   ```

**Comment by Tyriar** [comment]
This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to our code. As such, I will go ahead and close it. Please try to reproduce in [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal-preview/9n0dx20hk701) and report to [microsoft/terminal](https://github.com/microsoft/terminal) with repro steps.

Thanks for understanding.

/label upstream terminal terminal-conpty

**Comment by SetTrend** [comment]
Thank you, @Tyriar. Following your suggestion I opened a corresponding sibling issue [here](/microsoft/terminal/issues/10332).
