### ISSUE TITLE
Unclear message when all extensions are already updated

### ISSUE THREAD

**Issue by dilijev** [Microsoft/vscode#12546]
- VSCode Version: Code - Insiders 1.6.0-insider (0a0bfedbc64ba8fd0c3e6f42befb200a0b36ffb0, 2016-09-20T06:11:03.267Z)
- OS Version: Windows_NT ia32 10.0.14915

Steps to Reproduce:
1. Ensure no extensions need an update.
2. Try to activate command "Extentions: Update All Extensions".
3. See the following "error":

![image](https://cloud.githubusercontent.com/assets/494055/18798085/923f209c-8185-11e6-9aeb-9de9ce85c995.png)

The text of this info is not clear and appears to be an error. It would be better if it said something along the lines of "No extensions need updating" or simply not display an error since trying to update and finding nothing to update isn't really an error condition.

The text suggests that something has gone wrong or I am not allowed to try to issue that command in the current "context" -- which might mean e.g. when I have a code editor selected or some other mysterious circumstances which might constitute a "context".

**Comment by joaomoreno** [comment]
@alexandrudima @bpasero What can I do here?

I use the same action for the viewlet dropdown and for the global command. That action has enablement properly implemented since I want it to be reflected in the dropdown:

![image](https://cloud.githubusercontent.com/assets/22350/18866734/8a1ae9f4-84a1-11e6-9c7c-49324af053da.png)

But because of this, I get this generic message when using the action as a global command.

Could we come up with a way to show a specific contextual message when a command is run with a disabled action?

**Comment by bpasero** [comment]
We could allow an action to return the message when we detect for enablement. Should be easy enough to add to https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/quickopen/browser/commandsHandler.ts#L127

**Comment by joaomoreno** [comment]
Won't fix any time soon.
