### ISSUE TITLE
iPad: do not focus the editor when clicking on tab via touch

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#125470]
At least when no external keyboard is attached I wonder whether we should never automatically focus the editor to prevent the large keyboard from appearing. 

A case where I find it quite annoying:
* open a couple of editors
* click on another editor via tabs
* keyboard opens

**Comment by Tekh-ops** [comment]
Ummm you mean we need to port VScode for Ipad 14

**Comment by isidorn** [comment]
@bpasero we alrady tried to do this and we tackled most of the cases via https://github.com/microsoft/vscode/issues/122044
So you are also arguing that pressing on the tab should not focus the editor.
I absolutely agree. Let's assign to june to look into it then.
Also assigning to you just in case if you feel like jumping on this

**Comment by bpasero** [comment]
@isidorn there might be more places where this happens. I would argue that the majority of code that opens editors from trees/lists is probably fine because we do set `preserveFocus` when you single click (or touch).

So the places to look for are calls to `openEditor` without `preserveFocus: true`.

**Comment by isidorn** [comment]
@bpasero yeah good point. I can do a pass and create a check list.
And yes, most of the lists should be good.

**Comment by bpasero** [comment]
Not sure this is brutal, but we could entirely disable focussing the editor in one place given it will most often open the keyboard anyway.

**Comment by isidorn** [comment]
@bpasero I actually like that idea. That way we will not have an `isIOS` check everywhere across the code.

**Comment by bpasero** [comment]
I think that location would be:

https://github.com/microsoft/vscode/blob/f2b1f78ad45d5b19fe220e4533356efb31f4dcc1/src/vs/workbench/browser/parts/editor/editorControl.ts#L200-L200

and

https://github.com/microsoft/vscode/blob/f2b1f78ad45d5b19fe220e4533356efb31f4dcc1/src/vs/workbench/browser/parts/editor/editorControl.ts#L219-L219

**Comment by isidorn** [comment]
Yeah, we can add a master check there start of next week, and remove the specific checks in multiple clients...
Thanks!

**Comment by bpasero** [comment]
I see a couple of `isIOS` checks that have been added to not focus input fields, e.g. 

https://github.com/microsoft/vscode/blob/f29bd6f18ddefbb7f2cfca3e7e84e6b0a308c95c/src/vs/workbench/contrib/search/browser/searchView.ts#L905-L905

Shouldn't we rather try to detect if an external keyboard is attached or not to drive this because I think an iPad with attached keyboard should put focus as usual (even for editors).

If we cannot detect this properly then I think a change such as this one might be very frustrating for dedicated iPad users that always work with attached keyboard.

**Comment by isidorn** [comment]
@bpasero this is a good point and I was thinking the same. However I could not find a way to detect if a bluetooth keyboard is used on an iPad.
The only workaround we can do is if we detect a `RESIZE` event that reduces the size of the workbench we can assume a keyboard has been shown below the workbench and thus the external keyboard is not connected.

I checked what some other apps do on the iPad, for example Twitter and they never automatically pass focus to the input field even when the keyboard is connected.

Even though I hate settings, this might be the way to go. We introduce a new VS Code setting in the likes of:
`workbench.editor.passFocus` this would be default `true` on all devices, except `false` on the iPad

fyi @alefragnani for ideas on detecting external keyboard on iPad

**Comment by bpasero** [comment]
> I checked what some other apps do on the iPad, for example Twitter and they never automatically pass focus to the input field even when the keyboard is connected.

Would be maybe better to check with apps that are really optimized for being used with a keyboard, e.g. like Word or other apps where you can write a lot (OneNote?).

**Comment by isidorn** [comment]
Word and OneNote are truly beautiful apps. I plan to create a separate issue with some impressions I got from them and how those we could maybe use to improve our UX.

It seems like the general philosophy on the iPad apps is "leave this to the user and the OS". Because if the user has a external keyboard connected the internal one will not pop out thus making a nice experience. If the user has no external keyboard than the internal one will popup all the time, and it is actually hard to get rid of it. Thus we only need to improve the experience for touch only users.

OneNote has an explorer like structure and it behaves same as our Explorer. Clicking on the files does not pass focus. But opening a new file auto passes focus to the editor.
Both OneNote and Word do not have visual tabs on the iPad.

My impression is if somebody has an external keyboard he or she will also have an external mouse. Since the work flow of external keyboard + touching the screen is a bit clunky.
So how about the following heuristic:
* If the action is invoked via a Touch gesture do not auto pass focus

Plan B:
* Figure this out case by case basis. Do not pass focus where there is a high chance that the user is just reading: SCM, Extensions, Output, Tabs

**Comment by bpasero** [comment]
> Thus we only need to improve the experience for touch only users.

Yes, my thinking as well. If I use VSCode on iPad with mouse and keyboard I would find it very odd if clicking with the mouse on an editor tab requires another click into the editor to be able to start typing. So I think we should only change this once we found a way to detect external mouse/keyboard and/or provide a setting as you suggested.

Being able to detect a touch gesture for figuring out if focus should be passed or not sounds like a good idea conceptually but would probably require us to implement this check in each location where editors are being opened. This is a bit similar actually to the list service code that already figures out lots of things to make them work consistently, so maybe it should go somewhere here:

https://github.com/microsoft/vscode/blob/a8a71273d9203918391471b40a1cd1b5410cd91f/src/vs/platform/list/browser/listService.ts#L581-L586

It wouldn't help for the tab-click though which then needs a custom solution I guess.

**Comment by isidorn** [comment]
@bpasero yeah that's a good place to solve this in theory. However in practice I am not sure what is the use case which is using the list that we want to fix. All lists by default only pass focus on double click and that can not achieved via touch. So I think for lists we are already good.

Maybe instead we do it for the `actionBar`? Since the activity bar is using the `actionBar`, are you also using the `actionBar` for the tabs? Where is the actual code for the tabs that handle the touch event?

Hack approach which would solve all: `editorControl` could reach out to `Gesture.ts` and just ask if there was a touch event recently, if yes do not auto focus.

**Comment by bpasero** [comment]
True you are right, it does not apply to lists at all...

Maybe indeed we just solve it for the case I had originally reported, namely clicking on tabs? See this code that already seems to be dealing with touch or click:

https://github.com/microsoft/vscode/blob/903e219ccb8f8a0bccf8ffce33b79cb66bd9a4f4/src/vs/workbench/browser/parts/editor/tabsTitleControl.ts#L650-L672

I suggest somewhere there to preserve focus if touch is used.

**Comment by isidorn** [comment]
@bpasero I agree. Ok, I will do the change and once I have something will let you know.
As for the original changes done in https://github.com/microsoft/vscode/issues/122044 I will check if it is possible to wire down if triggered via touch or mouse

**Comment by bpasero** [comment]
Sounds good 👍

**Comment by isidorn** [comment]
I have pushed this and I actually like the approach. On tap we do not pass focus.
I have also adopted this approach for all viewlet opening

Try it out and let me know what you think :)
