### ISSUE TITLE
Clarity about User Installer and System Installer for Windows

### ISSUE THREAD

**Issue by ADTC** [microsoft/vscode#125590]
While we're deciding whether or not to implement #122698 I think we should first make it easier for people visiting via Windows to understand that there are two installers and know they have a choice. I just wasted 76.3 MB of mobile data downloading a User Installer then realized I was expected to get the System Installer. I also remember having to re-download the correct installer the last time I had visited the same site.

Ideally, a single installer could simply change the behavior depending on whether it is run as a user or as an administrator (with helpful alerts about which mode it is in). But when we have two installers, the [README](https://github.com/microsoft/vscode#readme) needs to have explanations:

- Why are there two installers?
- When should I choose User Installer? (What are the drawbacks if I do?)
- When should I choose System Installer? (What are the drawbacks if I do?)
- Why can't there be a single installer? (Or when will there be one?)
- Is the version in the .zip download closer to the User Installer on the System Installer?

Moreover, the download site https://code.visualstudio.com/ should make it clearer for Windows user what they're getting and also easier to get the alternative (without having to click "Other Downloads" — similar to the two options in Linux). At least, the blue button should say **"Stable Build (User Installer)" or "Stable (x64 User Installer)"** as a reminder.

![image](https://user-images.githubusercontent.com/6047296/120895168-532ae180-c64e-11eb-9ade-cb3fc9d7a9d5.png)

**Comment by joaomoreno** [comment]
Sorry that you wasted all that data on mobile.

I have created this issue to add the additional links: https://github.com/microsoft/vscode-docs/issues/4593

Instead of README, we have official documentation: https://code.visualstudio.com/docs/setup/windows. I have clarified some points in https://github.com/microsoft/vscode-docs/commit/752d9390718d1db145c4e5f6df974fc108415a24

> Why can't there be a single installer? (Or when will there be one?)

There can. But we haven't done it yet. There's no time committement for now.

> Is the version in the .zip download closer to the User Installer on the System Installer?

It's closer to none: it's an extractable, double-clickable app.
