### ISSUE TITLE
Pressing Enter after func opening brace should not trigger autocomplete

### ISSUE THREAD

**Issue by distinctdan** [microsoft/vscode#125557]
Issue Type: <b>Bug</b>

In a Go file, if I type the following and then press enter:
```
go func(){
```
Then VSCode autocompletes to a garbage completion like
```
go func(tt assert.TestingT, b bool, i ...interface{}) bool {}
```

This is not ever going to be the desired behavior, autocomplete should not be triggering here. Instead, it should enter a newline like normal. If this is actually an issue with the Go tooling, I can refile the issue somewhere else.

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:44:30.902Z)
OS version: Darwin x64 20.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (2.85GB free)|
|Process Argv|--crash-reporter-id 656c6348-b102-4b6b-8ade-e7f56a3faa5f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.20
go|gol|0.25.1
vscode-scss|mrm|0.10.0
vscode-docker|ms-|1.13.0
vscode-kubernetes-tools|ms-|1.3.3
remote-containers|ms-|0.177.2
cpptools|ms-|1.4.0
vscode-commons|red|0.0.6
vscode-yaml|red|0.19.2
vscode-proto3|zxh|0.5.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
vscgsv2:30307504
vscorehov:30309549
bridgeflight:30312182
vscod805:30301674

```

</details>

**Comment by jrieken** [comment]
It looks like the issue is caused by one of your installed extensions. All extensions execute together on a single nodejs process, so in order to narrow down the possible problematic extension, please try the following:
* run `F1 > Help: Start Extension Bisect`
* (this will restart VS Code with half of your extensions disabled)
* try to do the steps which reproduce the problem
* if the problem reproduces, click "This is bad" (this narrows down the problematic extension to the half which was enabled)
* if the problem does not reproduce, click "Good now" (this narrows down the problematic extension to the half which was disabled)
* these steps will repeat until the problematic extension is found

| initial | step | final |
|---|---|---|
| ![image](https://user-images.githubusercontent.com/5047891/101918658-e9170f80-3bc9-11eb-9977-857baa291937.png) | ![image](https://user-images.githubusercontent.com/5047891/101918683-ef0cf080-3bc9-11eb-9f9e-98b0177991b2.png) | ![image](https://user-images.githubusercontent.com/5047891/101918706-f502d180-3bc9-11eb-8c86-e56355958bd4.png) |
