### ISSUE TITLE
vscode has unlimited resource hunger on large machines

### ISSUE THREAD

**Issue by grandrew** [microsoft/vscode#125637]
Does this issue occur when all extensions are disabled?: No

- VS Code Version:  1.56.2
- OS Version: Linux x64 5.4

Steps to Reproduce:

1. Own a 16+ core 100+GB RAM machine and develop e.g. Python project
2. Observe VScode use insane amount of resources, like 80+GB VRAM per process, hundreds of processes, multiple cores full-load doing who knows what.

There needs to be implemented some kind of limiting mechanism that would set reasonable consumption. Like use no more than 50GB RAM / 300GB VRAM, no more than 50 processes, etc...

![image](https://user-images.githubusercontent.com/243218/120942796-0d1e5e00-c6e0-11eb-9b63-f5c6fbeb827c.png)

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/
