### ISSUE TITLE
Feature: CompletionItems can have promises as additionalEdits

### ISSUE THREAD

**Issue by buehler** [Microsoft/vscode#12560]
It would be a really nice feature, if the `CompletionItem` can actually return promises as their `additionalTextEdits`.

I'm imaging the following feature:
You are autocompleting something (in my example it's an import that is added to the programmers file) and there are other imports that have the same class name. Now it would be cool if I can add a Promise to the additionalTextEdits to ask the user with a `showInputBox` for an alias name.

Example:
```typescript
import {Foobar} from 'whatever';

let foo = new Foobar();
```

Now if I autocomplete another `Foobar` class from the library `foobaz`, I want to ask the developer for an aliased name to generate the following code:

```typescript
import {Foobar} from 'whatever';
import {Foobar as MyFoobar} from 'foobaz';

let foo = new Foobar();
/*...*/
```

To do so, the additionalTextEdit should have the possibility to be a promise like so:
```typescript
completionItem.additionalTextEdits = [
    vscode.window.showInputBox(/*...*/).then(name => {
        //prepare the text edit with the given name (if any)
        return TextEdit;
});
]
```

What do you guys think?
Cheers

**Comment by jrieken** [comment]
Not convinced - that fact that `provideCompletionItems` and `resolveCompletionItem` can return thenables allows for enough asynchronous work to happen with the completion lifecycle. 

You seem to tackle a very specific problem and instead of adding more complexity (async edits from async completions), you should use [`CompletionItem#command`](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L2322) that allows you to do what you want

**Comment by buehler** [comment]
Alright :-) After thinking it through, I'd say, the command way is the way I'll go.
It even does not seem to be a workaround, it's actually a pretty nice way to achieve my goal.

So feel free to close this issue!
Cheers

**Comment by jrieken** [comment]
K. Thanks for getting back with this
