### ISSUE TITLE
Deserialize function doesn't have uri parameter

### ISSUE THREAD

**Issue by alyssajotice** [microsoft/vscode#125757]
I am working on getting Live Share notebooks functional again after recent API changes. We want Live Share notebooks to be running on stable APIs, which means using serializers rather than content providers. 

However, serializers do not work for the guest scenario. Previously, the guest's content provider would have an openNotebook function with a uri parameter for the document being opened. We proxied that request to the host, where we could use `vscode.notebook.openNotebookDocument` with the uri. Now, deserialize only includes the document's content. I can add the serializer's view type to proxied request, but the only information we can give the host is content and viewtype. We need it to return NotebookData, but we cannot identify which notebook document to deserialize. 

Could  `vscode.commands.executeCommand('_resolveNotebookContentProvider');` return serializers that have callable deserialize functions? 

cc @jrieken @rebornix @davsterl

**Comment by alyssajotice** [comment]
Thanks @gregvanl, it was in the wrong repo.

**Comment by Downchuck** [comment]
There are 72 upvotes for this particular feature - https://github.com/MicrosoftDocs/live-share/issues/3301

**Comment by alyssajotice** [comment]
Hey @jrieken, can we reopen the conversation about migrating Live Share to serializers? We have a new suggestion for what we need to move away from content providers. Can we get an API to get a reference to a serializer and call deserializeNotebook on it? Then, we could keep a 1:1 mapping of serializers from the host to the guest. We can include the notebook type in our RPC request and then from the notebook type, get the reference to the serializer and call it. 

Would this work?

**Comment by jrieken** [comment]
I have pushed changes to make sure the `vscode.resolveNotebookContentProviders` works (it was broken since https://github.com/microsoft/vscode/commit/579e0a39c21596e4ebda00b0497c788235330efb), I ensures that it does include all kinds of notebook data providers. 

I have also pushed to new commands that allow to "execute" a notebook serializer: `vscode.executeDataToNotebook` and `vscode.executeNotebookToData`. Both need to be called with a notebook type and the respective data. This is a sample:

https://github.com/microsoft/vscode/blob/d58ff261d44ea7120a4305f75ef274c1cbbbf894/extensions/vscode-api-tests/src/singlefolder-tests/notebook.test.ts#L1026-L1041

**Comment by jrieken** [comment]
These changes should allow LiveShare to migrate onto the notebook serializer API. Please let me know how that goes

**Comment by alyssajotice** [comment]
@jrieken things are working with the serializers for most files. I have one test file that this command does not work with and I get the following error: 
<img width="315" alt="image" src="https://user-images.githubusercontent.com/22576531/163885572-40d66aed-6ee3-447f-9d38-9dc3d716c4e1.png">
Other .ipynb files work as expected, and other notebook types work as expected.

To repro, I set up a serializer that deserializes the content of the file with this command using the jupyter serializer. 

<details>
  <summary>extension.ts</summary>

  ```
import { TextEncoder } from 'util';
import * as vscode from 'vscode';

export async function activate(context: vscode.ExtensionContext) {
	context.subscriptions.push(vscode.workspace.registerNotebookSerializer('vsls-testing', new class implements vscode.NotebookSerializer {
		deserializeNotebook(content: Uint8Array, _token: vscode.CancellationToken): vscode.NotebookData | Thenable<vscode.NotebookData> {
			return vscode.commands.executeCommand<vscode.NotebookData>('vscode.executeDataToNotebook', 'jupyter-notebook', content); 
		}
		serializeNotebook(data: vscode.NotebookData, _token: vscode.CancellationToken): Uint8Array | Thenable<Uint8Array> {
			return new TextEncoder().encode(data.cells[0].value);
		}
	}, {}, {
		displayName: 'LS',
		filenamePattern: ['*'],
		exclusive: true
	}));
}

```
</details>


With this extension activated, open this file:

<details>
  <summary>nb.ipynb</summary>

```
{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {
    "dotnet_interactive": {
     "language": "html"
    }
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Hello world\n"
     ]
    }
   ],
   "source": [
    "print(\"Hello world\")\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": []
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "dotnet_interactive": {
     "language": "csharp"
    }
   },
   "source": [
    "## Hello W  "
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": []
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "dotnet_interactive": {
     "language": "csharp"
    }
   },
   "outputs": [],
   "source": [
    "Console.WriteLine(\"hello\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "dotnet_interactive": {
     "language": "csharp"
    }
   },
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "dotnet_interactive": {
     "language": "csharp"
    }
   },
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "dotnet_interactive": {
     "language": "csharp"
    }
   },
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "dotnet_interactive": {
     "language": "csharp"
    }
   },
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "Print()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "interpreter": {
   "hash": "70adf7d9d67fce19c0d10a40853929ab78ed9880e9ec63b083cd87fcc27327e6"
  },
  "kernelspec": {
   "display_name": ".NET (C#)",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.9"
  },
  "metadata": {
   "interpreter": {
    "hash": "0a6456904a4e417f6aca58f6dd6b4feac7b82dab23c8ff870c0b8bcfafad0149"
   }
  },
  "orig_nbformat": 3
 },
 "nbformat": 4,
 "nbformat_minor": 2
}


```
</details>



Two other issues I'm working on to remove content providers:
1. We previously used the openNotebook (the function the guest calls with the notebook data to be deserialized) call on the host to block excluded files from being opened. We need the filename to do this.
2. We create our cell managers in openNotebook on the host. These managers coordinate coediting and cell operations between the guest and host. These edits and operations are tracked via filename. 

cc @daytonellwanger for visibility on these two issues.

**Comment by jrieken** [comment]
>  call on the host to block excluded files from being opened.

Not sure what excluded means in this in this context?

>We create our cell managers in openNotebook on the host. These managers coordinate coediting and cell operations between the guest and host. These edits and operations are tracked via filename.

Would the `onDidOpenNotebook` and `onDidCloseNotebook` events be an alternative for that?

**Comment by alyssajotice** [comment]
For the excluded scenario, the host can have a list of files that they do not want to show to guests. When the guest requests an open, we check the list of excluded files and do not return the notebook data if the requested notebook is marked as excluded.

For the cell managers, I think we can use the `onDidOpenNotebook` call on the guest, send an RPC notification to the host, and create the cell managers there.

Do you have any updates about the cause of the error I mentioned?

**Comment by jrieken** [comment]
> Do you have any updates about the cause of the error I mentioned?

Please file a new, dedicated issue for that. 

> When the guest requests an open, we check the list of excluded files and do not return the notebook data if the requested notebook is marked as excluded.

Wouldn't it make more sense to do the check in the layer that implements the file system? E.g I assume the guest has a virtual file system which is implemented by the host. To me that looks like a better place for such checks, otherwise the guest can always workaround those protections, e.g have an extension snippet doing the equivalent of `vscode.workspace.fs.readFile(vscode.Uri.parse('vsls:///some/excluded/file.nb'))`

**Comment by alyssajotice** [comment]
New issue here: https://github.com/microsoft/vscode/issues/147711#issue-1208647505.

**Comment by jrieken** [comment]
> I can explain the cell id situation in greater detail if that would be helpful.

Yeah, that would be great because I believe I am missing the bigger picture. 

Adding the uri-parameter to these calls _might_ be possible but there is no guarantee that we always have this information. Internally this is just a context-free transform operation from bytes to structured data (similar to how text encoding/decoding works) and that can occur without a file/uri at hands. I also want to make sure that we are on the same page wrt lifecycle: Serializing and deserializing a notebook can occur multiple times "per notebook", e.g we deserialize for the initial open but it can happen again without the notebook having been closed/opened. In short: taking the deserialize call as signal to install something is likely wrong and error prone. The open/close events should be used instead. I also want to learn about the cell ids and how it drives coediting, I thought LS build upon the fact that every notebook cell is also a text document.
