### ISSUE TITLE
Allow for details in message options

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#125750]
The [MessageOptions](https://github.com/microsoft/vscode/blob/f207b3830717f2c354ea12ead37baff21f33a680/src/vs/vscode.d.ts#L1855-L1855)-type allows to tweak the behavior `showInformationMessage` and friends. We should also allow for a `details` property which are then rendered nicer for modal dialogs.

**Comment by jrieken** [comment]
@bpasero I am also looking into supporting detail for non-modal messages. I was planning to concat the detail to the message, separated by a new line. However, it seems that newline are being stripped from notifications. Is that on purpose? Any other ideas?

**Comment by bpasero** [comment]
@jrieken this was mainly to prevent extensions from abusing notifications from showing rich content in notifications. I do not think that notifications are the right widget to show lots of text, specifically because the area to show content is so small.

Why not limit `detail` to dialogs only? There it makes a lot more sense to me because visually details look different from the message text.

**Comment by jrieken** [comment]
> Why not limit detail to dialogs only? 

My worry is that extensions, that want detail, will now use modal dialogs instead of notifications... But I am also fine to wait for that to happen

**Comment by bpasero** [comment]
Yup, also fine for me. My rationale is that a misbehaving extension that pops up many modal dialogs will get either uninstalled or will start to see lots of issues reported by users as a consequence.

Btw if it makes the API any easier, we could still allow `details` in notifications but simply append that content to the message so that it is still presented, just visually a bit different compared to dialogs, which I think is fine.

**Comment by jrieken** [comment]
> but simply append that content to the message so that it is still presented, just visually a bit different compared to dialogs, which I think is fine.

Append how? I tried the newline separation which didn't work. I don't think that we can use dot or something else

**Comment by bpasero** [comment]
Yeah just literally on the extension host even, concatenating the message + detail. It needs some heuristics I guess, e.g. if message does not end with a `.`, append one and then put details, something like: `message` + `.` + `detail`?

**Comment by jrieken** [comment]
Based on @mjbvz suggestion: showing "More" which shows details in a modal 

https://user-images.githubusercontent.com/1794099/122224912-dc46e180-ceb4-11eb-8d48-17925e9ea859.mov

**Comment by bpasero** [comment]
Interesting idea, should probably discuss in a UX call. I am not sure how obvious it is what "More" means in the context alongside the other buttons (because they are all in the same hierarchy). And then in the modal dialog it maybe less obvious that only the details are showing.

cc @misolori

**Comment by jrieken** [comment]
Decision is to not support `detail` for notification messages for now.

**Comment by jrieken** [comment]
Use the yeoman extension sample and add `MessageOptions` with `detail` (and `modal`)
