### ISSUE TITLE
Required extensions not bundled on Linux

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#12570]
- VSCode Version: 	d81ee41c51cae93a5cac967e42a28660a3a7e005 & 31ceb1112602e005150c8ab481c8e38069da1cca
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. F5
2. Get error "Configured debug type 'extensionHost' is not supported."

I needed to revert to version 25b370a3ebe800ac1fedc551a47b7689aa2a5c5b to debug my extension.

**Comment by isidorn** [comment]
The reason for this is that the required node extensions is not bundled in our linux package. You can see this by going to the extensions viewlet and trying to install node-debug (it is possible to do that since it is missing). Once you install it - everything works fine.
Not sure if this has something to do with how our ubuntu deb package is built and maybe that process did not pick up our new required extensions thing.

On win and osx it works fine.

Forwarding to @sandy081 and @joaomoreno the extension people.

**Comment by joaomoreno** [comment]
@weinand It turns out we are hitting the race condition at build time in which the placeholder `package.json` files are overwriting the real ones.

**Comment by weinand** [comment]
We could drop the placeholder folders and move the two OSSREADMEs into another spot that is not considered an extension location.

**Comment by joaomoreno** [comment]
True. For now I was thinking of simply filtering them out of the build.

**Comment by JonasT** [comment]
I just cloned the VSCode repo and executed `scripts/npm.sh install` and then launched it, and pressing F5 I still get this error. Is this a bug, or am I supposed to still do something to get this working?

**Comment by isidorn** [comment]
This is as designed, when you run vscode out of source the node debug is not packaged as an extension - it only gets packaged once you build the full vscode.
What you need to do is copy the node-debug from your vscode stable installation folder inside your user .vscode-oss-dev/extensions folder. That way the out of source vscode will pick up the built in node debug extension
