### ISSUE TITLE
Native Notebooks - Scrolling Slow/Buggy 

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode#125874]
Getting an influx of customer feedback from our experiment surveys that scrolling in notebooks is slow/buggy 

*One user explicitly mentioned that it appears to be worse if cells are currently running

**Comment by claudiaregio** [comment]
![image](https://user-images.githubusercontent.com/19276747/121625582-96a79600-ca28-11eb-9e3e-463a48820de9.png)

**Comment by claudiaregio** [comment]
![image](https://user-images.githubusercontent.com/19276747/121625675-c22a8080-ca28-11eb-82a7-628a82052f44.png)

**Comment by claudiaregio** [comment]
![image](https://user-images.githubusercontent.com/19276747/121627941-2b13f780-ca2d-11eb-9f13-18734d67db1e.png)

**Comment by rebornix** [comment]
@claudiaregio since one mentioned it's slow even when scrolling on markdown cells, I wonder if it has anything to do with GPU optimization so I would love to reach out and see if they can 

* reproduce with `code-insiders --disable-gpu` 
* follow https://github.com/microsoft/vscode/wiki/Performance-Issues to provide more details

if anyone can provide more details of above two items it would be really helpful

**Comment by rebornix** [comment]
let's track this in https://github.com/microsoft/vscode/issues/126880
