### ISSUE TITLE
Keybinding picker should not dismiss on enter

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#1258]
I suggest to use another trigger character like Ctrl+Enter, otherwise I cannot pick the "Enter" key.

**Comment by alexandrudima** [comment]
@bpasero I would prefer to leave them to <kbd>Enter</kbd> and <kbd>Escape</kbd> as these are the expected keybindings used for accepting and canceling throughout VSCode.

Since <kbd>Enter</kbd> and <kbd>Escape</kbd> do not change in any keyboard layout, it is reasonable that you must type them in by hand.

Otherwise, a workaround is always to create a rule for <kbd>Ctrl</kbd>+<kbd>Enter</kbd> for example and then remove the `"ctrl"`
