### ISSUE TITLE
Send output item data as VSBuffer

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#125819]
Currently output items send data as number array. That's not ideal and use send things a VSBuffer for which the IPC layer is fast. This is a bigger change because it requires to stop using `IOutputItemDto` from `extHost.protocol.ts`

**Comment by jrieken** [comment]
kinda blocked by https://github.com/microsoft/vscode/issues/125668

**Comment by RandomFractals** [comment]
@jrieken even the current output data array is chopped off: https://github.com/RandomFractals/vscode-data-table/issues/30#issuecomment-886771648

would be nice to be able to read raw binary data from cell output.

![data-array-loading-error](https://user-images.githubusercontent.com/656833/127013539-15c336bb-1ca1-46eb-a0cf-1b3a18ba9b4b.png)

**Comment by mjbvz** [comment]
I looked into this a little since I'd done something similar for webviews. I think there are two potential approaches to optimize `NotebookOutputItemDto`: 

### Pass the the output data buffers as top level arguments to ipc calls

For any ipc call that deals with an cell output, pass the list of output VSBuffers as top level arguments:

```
$tryApplyEdits(editorId: string, modelVersionId: number, cellEdits: ICellEditOperationDto[], ...outputBuffers: VSBuffer[]): Promise<boolean>
```

This ensures that they are efficiently serialized by our existing ipc implementation

Then for `NotebookOutputItemDto`, we use a reference to tell us which output buffer from the list of buffers to use:

```ts
export interface NotebookOutputItemDto {
	readonly mime: string;
	readonly bufferIndex: number;
}
```

Making this change is sort of a pain because it requires updating a lot of to/from conversation functions to take an array of output buffers


### Add ipc support for efficiently serializing VSBuffers inside of objects 

First  update `NotebookOutputItemDto` to use a VS Buffer

```ts
export interface NotebookOutputItemDto {
	readonly mime: string;
	readonly buffer: VSBuffer;
}
```

On its own, this would result in the buffer being very inefficiently serialized. So we'd also need update our IPC implementation to deeply detect and VSBuffers inside of passed in arguments and then serialize them more efficiently

This efficiently serialization would likely be similar to what we do for webviews:

- While serializing the arguments, walk each object to extract all buffers and replace them with references (just indexes into the list of extracted buffers)
- The write the serialized object and buffers to the wire
- On the receiving side while deserializing objects, walk though them again and replace all buffer references with the corresponding buffer

I feel this approach is probably better since it not specific to notebooks. However I'm not sure if it would significantly degrade performance for all ipc calls. I believe we already walk objects during serialization/deserialization to handle URIs so it may be ok. We could also make the behavior opt-in and only enable it for specific calls that need it

**Comment by RandomFractals** [comment]
I have not looked at what constitutes a VSBuffer. Would it be possible to instead use `application/octet-stream` mime type for cell outputs with binary data, and allow renderers to read them with a standard [ReadableStream](https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream/getReader)? See [Using Readable Streams](https://developer.mozilla.org/en-US/docs/Web/API/Streams_API/Using_readable_streams)

I liked that current cell output API exposes `blob()`, but I was not able to read the whole data blob either in my tests.
