### ISSUE TITLE
Windows locale only picked up on second launch

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#125863]
Testing #119415

Version : 1.57.0-insider (user setup)
Commit : b4c1bd0a9b03c749ea011b06c6d2676c8091a70c
Date : 2021-06-09T11:49:36.076Z
Electron : 12.0.9
Chrome : 89.0.4389.128
Node.js : 14.16.0
V8 : 8.9.255.25-electron.0
OS : Windows_NT x64 10.0.19043

Steps to Reproduce:

1. Set Windows language to something other than English, such as French.
2. Launch VS Code with fresh user data dir.
3. 🐛 VS Code displays in English. If one closes VS Code now, and then launches it with the same user data dir again, _then_ VS Code shows the correct language.

**Comment by dbaeumer** [comment]
This is happening since the new user data dir doesn't contain a `languagepacks.json` configuration file on startup. As a result the nls loader which we need to inject very early in the startup process assumes that no language package are installed, hence it doesn't load the German language pack. 

When VS Code is running the user data dir is populated by the services and a `languagepacks.json` file is written which will be honored on next startup.

@sandy081 why are we writing that file into the user data dir. It is solely extension specific. Couldn't we write that file into the directory where we install extensions?

**Comment by sandy081** [comment]
All caches go into user data directory also same with this. Agreed it can be stored in extensions dir but extensions directory is also change-able. How practical is this scenario anyways?

**Comment by rzhao271** [comment]
I think this scenario only really matters for first-time users. If there is already a separate process for first-time users, who might not be able to read English well, to get a language pack installed, then there's no problem.

**Comment by dbaeumer** [comment]
For first time users that process is different and indeed works. You install a language pack and we prompt you to change the display language to that language pack. Since everything goes into the already `open` user data dir everything works.

So I tend to close the issue. Objections?

**Comment by rzhao271** [comment]
No objections. Closing!
