### ISSUE TITLE
Inlay hints schedule improve

### ISSUE THREAD

**Issue by Kingwl** [microsoft/vscode#125995]
Currently, the inlay hints will clean and shows again as scheduler's strategy.

It's might not friendly if you are editing some line who has many hints.

I have an idea: 
Clean all hints where the cursor’s line when we are editing the code and append new hints by the scheduler.

I think It's might improve the experience about inlay hints.

**Comment by Kingwl** [comment]
![Uploading hints_exp.gif…]()

**Comment by hediet** [comment]
I think inlay hints should disappear immediately if the surrounding text is deleted.
Afaik, currently, when text gets deleted, decorations inside of that text get collapsed but are not deleted.

**Comment by jrieken** [comment]
Yes, I agree that hints should disappear immediately when their "anchor" position is removed. Maybe it's not so easy to know what remove actually means in this case. Arguably this is an editor bug as I was expecting this to work?

**Comment by hediet** [comment]
> Arguably this is an editor bug as I was expecting this to work?

I wouldn't call this a bug - decorations are never removed automatically.

Alex suggests (I asked him before his vacation):
> yes, the inlay hints could listen to change events and remove them if they become collapsed

I also suggest to extend the inlay hints API so that a hint refers to a range. The hint itself then can either be after or before the range.
The range allows to better predict what should happen with the hint if the text changes.

**Comment by jrieken** [comment]
> I also suggest to extend the inlay hints API so that a hint refers to a range. The hint itself then can either be after or before the range. The range allows to better predict what should happen with the hint if the text changes.

This is how we started, mostly to optionally support _overlay_ hints, and everyone was confused about ranges for inlay hints. Using a range with before/after screams "position" and I don't want to leak an implementation detail into the API. We would also still have the case of empty ranges... I'd rather create "fake ranges" from positions so that I can use the notion of collapsed ranges.

**Comment by jrieken** [comment]
I have pushed a change to expand positions (as provided by the API) to ranges given those ranges are of touching words. That generates more non-empty ranges but I still see the bug described above...

**Comment by jrieken** [comment]
I have pushed a change (00d20b9)  to use the range of touching words of inlay positions (when possible). In that case `showIfCollapsed` will be `false` and my expectation was that decorations hide/disappear when removing all their text.. @alexdima @hediet is that a bug in decorations land or am I using this wrong? Should I listen to decoration changes and "manually" remove them?

**Comment by hediet** [comment]
> Should I listen to decoration changes and "manually" remove them?

I think so, decorations are not removed automatically.

**Comment by jrieken** [comment]
But what does `showIfCollapsed` mean then?

**Comment by hediet** [comment]
Ah, maybe I forgot to consider that flag for injected text, I'll look into it tomorrow.
