### ISSUE TITLE
Workspace Trust Enabled, prevents adding workspace directories when using VSCode with WSL2

### ISSUE THREAD

**Issue by mbwhite** [microsoft/vscode#126015]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.57.0
- OS Version: Windows 10 Pro, with Ubuntu 18 in WSL2

Steps to Reproduce:

1. I'm running with VSCode in the recommended setup for using with WSL2
2. From a shell in WSL2, I issue `code .` to start the editor in the current directory. I need to say I trust this directory
3. Right click in the navigator to add another workspace folder.
4. The 'trust this directory' pop upappears, but then the vscode window reloads, and the new directory is not added

Disabling the 'trust' settings in permits this to work.

**Comment by lszomoru** [comment]
There are two other workarounds that you could consider in order to "build" your multi-root workspace:
1. When opening the directory in "Step 2", choose to stay in restricted mode. Staying in restricted mode will allow you to add additional directories independent whether they are trusted or not to the workspace without any workspace trust related prompts. After you have added all the directories to the workspace, save the workspace file, and then trust the workspace.
2. Ensure that the folder that you are adding in "Step 3" is already trusted. If the folder is trusted. you should not be seeing any prompts.

The challenge here is that in WSL, performing "Step 3" will transition the workspace state from "folder" to "workspace" causes a window reload which is unrelated to the new workspace trust feature. We will investigate possible options to make this a smoother experience.

**Comment by mbwhite** [comment]
thanks @lszomoru I can see how the other options can work. 

In my case I trust all the directories in question - so for me disabling the feature should not increase any risk. Admit that I tend to be 'fluid' in what directories are added to a workspace. i.e. I'll add what I need at point, so may well end up with what really should be two (or more) workspaces for short spells. But that's just me being lazy really :-)

**Comment by lszomoru** [comment]
Got it! Are all the directories that you are using to "build" these workspaces in a common parent directory? You could use the [workspace trust editor](https://code.visualstudio.com/docs/editor/workspace-trust#_selecting-folders) to add the parent directory to the list of trusted folders. By doing so, all children will be trusted and you should not be seeing any workspace trust related prompts.

**Comment by AndreHorst** [comment]
Thanks! had the same issue when working via remote SSH. Adding the folders to the trust editor works like a charm :-) It would be cool to have a blacklist feature, let's say that I trust my home directory but exclude the `download/` folder (because this is where internet code goes into.

**Comment by lszomoru** [comment]
Quick update on this issue.I have tracked down and fixed the root cause of the unexpected window reload, which happens while the workspace trust dialog is being shown.
