### ISSUE TITLE
repl doesn't show all text

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#1260]
Take this code snippet

```
var value = ''
var i = 10000;
while (i-- > 0) {
    value += Math.random().toString(16);
    value += '\n';
}
value += 'END';
console.log(value)
```

* break on the last line
* type _value_ in the debug console
* :arrow_forward: last bits are not shown :cry:

**Comment by jrieken** [comment]
<img width="1034" alt="screen shot 2015-12-14 at 14 25 31" src="https://cloud.githubusercontent.com/assets/1794099/11782062/c950089a-a26e-11e5-8e63-7f497d73676e.png">

**Comment by isidorn** [comment]
Only happens for very long strings when the repl has a specific size. Resizing the repl should show the value -> backlog
The issue is that I am measuring the width of the outer div not the span itself and this produces a difference in a couple of pixels. I would restructure the dome nodes for output elements but not for endgame week.
