### ISSUE TITLE
Display registered settings groups by extension

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#126089]
The `"configuration"` extension contribution point can take a single object of setting keys -> definitions or an array of these, each with their own title. Currently the Extensions node in the settings editor TOC shows extension settings by config section with the registered title, mixed up globally and sorted alphabetically. A couple issues with this:

- Config section titles can be generic and duplicate other sections
![image](https://user-images.githubusercontent.com/323878/121735233-ae276300-caaa-11eb-8520-fc97277db8c8.png)
- There is a LESS section that comes from the builtin css-language-features extension, but there is no way to know which extension it came from
- If an extension registers multiple sections, they are not grouped together and the specified order is ignored. The split json editor handled this correctly.

So I'm thinking we should actually have the extension name as the top node, put the extension sections under that with their given titles and order. This actually makes extension sections much more useful. This is a good start towards giving extensions more control over the presentation of their settings, like discussed in #70589, and we don't have to extend JSON schema to do it.

**Comment by roblourens** [comment]
cc @eamodio, may be interesting to you

**Comment by eamodio** [comment]
I definitely think this makes a lot of sense -- keeping the extension settings contain with in its own "space"

**Comment by rzhao271** [comment]
WIP

Here's how a single level of grouping looks:

![singlevel](https://user-images.githubusercontent.com/7199958/122843298-fb2de500-d2b3-11eb-8469-b75b68509513.PNG)

**Comment by rzhao271** [comment]
\closedWith 22c0c2c

**Comment by alefragnani** [comment]
I was playing with the released API to organize one of my extension's settings, and if I understand correctly, once I decide to use groups (adding two or more `configuration` entry), the Settings UI will add each entry inside my extension top node. 

I mean, suppose I have something like this:

```json
"configuration": [
        {
            "title": "%projectManager.configuration.title%",
            "properties": {
                "projectManager.removeCurrentProjectFromList": {
                    "type": "boolean",
                    ...
        },
        {
            "title": "Status Bar",
            "properties": {
                "projectManager.showProjectNameInStatusBar": {
                    "type": "boolean",
                    ...
        // and so on...
```

The Settings view will display:
![Screen Shot 2021-10-08 at 01 21 14](https://user-images.githubusercontent.com/3781424/136498373-c4aaaf1c-4376-4708-afcc-e6d69cf71093.png)

The first thing I noticed is the double **Project Manager** nodes. Reading this issue I understood this is the expected behavior, but I was expecting something similar to how the core settings works, like **Text Editor**. When you expand it, you see **Cursor** as the first child node, but there are settings for **Text Editor** alone, and you have to scroll a lot before entering **Cursor**. I mean, I would like to have _basic settings_ and _grouped settings_. What do you think?

Secondly, and I guess this is an issue, you may notice my extension entry is the first one inside **Extensions** node. But this is not alphabetically sorted anymore, and this is happening because one of my groups is called **Any** (starts with `A`). If I remove it, the extension moves down, right after **Git** (because I have a group called Git).

Let me know if you need more details, or if you would that I create separate issues.

Thank you

**Comment by rzhao271** [comment]
@alefragnani @AlbertoFabbri93 those issues should be fixed in the next Insiders, and are being tracked in https://github.com/microsoft/vscode/issues/137257 and https://github.com/microsoft/vscode/issues/137259.
