### ISSUE TITLE
integrated terminal not showing after update 

### ISSUE THREAD

**Issue by RELNO** [microsoft/vscode#126055]
Upon updating to ver 1.57.0, the new terminal tab menu returns only blank window, without terminal functionality. I've attempted changing settings (from bash to zsh to csh etc) but nothing works. 

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.57.0 
- OS Version: macOS 11.4

Steps to Reproduce:

1. go to terminal menu and start click `New Terminal` (this will yield the error note attached)
2. if using a shortcut to start the terminal (cmd+j in my case) the error note is not showing, but the issue is the same   

![Screen Shot 2021-06-11 at 10 38 50 AM](https://user-images.githubusercontent.com/14296774/121704423-c3e45a80-caa1-11eb-9483-86ed974f60c6.png)

Dev tools error when starting the terminal:

![Screen Shot 2021-06-11 at 1 47 49 PM](https://user-images.githubusercontent.com/14296774/121728828-c3f15400-cabb-11eb-87b7-db9e170086a7.png)

**Comment by NicholasTaylor** [comment]
Same thing is happening to me on 1.57. Also happened to me on 1.56. Had to downgrade to 1.55 to regain integrated terminal functionality. Running VSCode via WSL 2 with "Remote - WSL" extension. Integrated terminal works when "Remote - WSL" not being used (Powershell will load successfully in this case)

VS Code Version: 1.57.0
OS Version (from cmd.exe ver): Microsoft Windows [Version 10.0.19043.1052]
WSL Version: 2
Linux Distro (and version): Ubuntu 20.04.2 LTS

With Remote-WSL:
![Remote-WSL](https://user-images.githubusercontent.com/5090924/121708814-74b12080-cac7-11eb-840c-0ea7f9d580b6.png)

Without Remote-WSL:
![No-Remote-WSL](https://user-images.githubusercontent.com/5090924/121708862-8266a600-cac7-11eb-9dbe-e6a1ab23b57b.png)

Current settings.json:
`{
    "editor.wordWrap": "on",
    "files.associations": {
        "*.sass": "scss"
    },
    "[php]": {
        "editor.defaultFormatter": "bmewburn.vscode-intelephense-client"
    },
    "explorer.confirmDragAndDrop": false,
    "[javascript]": {
        "editor.defaultFormatter": "karye.prettier-php"
    },
    "[html]": {
        "editor.defaultFormatter": "karye.prettier-php"
    },
    "typescript.updateImportsOnFileMove.enabled": "always",
    "[json]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "workbench.editorAssociations": {
        "*.ipynb": "jupyter.notebook.ipynb"
    },
    "workbench.colorTheme": "Ariake Dark",
    "terminal.integrated.tabs.enabled": false,
    "terminal.integrated.automationShell.linux": ""
}`

**Comment by meganrogge** [comment]
any errors in the dev tools console?

**Comment by NicholasTaylor** [comment]
@meganrogge At the time I made the comment this morning, nothing. Tried again just now. Found a few.

![log](https://user-images.githubusercontent.com/5090924/121726091-9a472580-cad9-11eb-96c0-6810443a0a92.png)

`
electron/js2c/renderer_init.js:65 The vm module of Node.js is deprecated in the renderer process and will be removed.
t._load @ electron/js2c/renderer_init.js:65
console.ts:137 [Extension Host] (node:17848) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.(Use `Code --trace-deprecation ...` to show where the warning was created)
S @ console.ts:137
log.ts:284  INFO [remote-connection][ExtensionHost][e7bfb…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
log.ts:284  INFO [remote-connection][ExtensionHost][e7bfb…][reconnect] resolving connection...
log.ts:284  INFO [remote-connection][ExtensionHost][e7bfb…][reconnect] connecting to 172.27.245.103:36915...
log.ts:284  INFO [remote-connection][ExtensionHost][e7bfb…][reconnect] reconnected!
log.ts:284  INFO [remote-connection][ExtensionHost][e7bfb…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
log.ts:284  INFO [remote-connection][ExtensionHost][e7bfb…][reconnect] resolving connection...
log.ts:284  INFO [remote-connection][ExtensionHost][e7bfb…][reconnect] connecting to 172.27.245.103:36915...
log.ts:284  INFO [remote-connection][ExtensionHost][e7bfb…][reconnect] reconnected!
extensionHostManager.ts:75 Error received from starting extension host (kind: 2)
(anonymous) @ extensionHostManager.ts:75
extensionHostManager.ts:76 timeout
(anonymous) @ extensionHostManager.ts:76
`

**Comment by RELNO** [comment]
@meganrogge yes, updated issue to reflect.

**Comment by Tyriar** [comment]
Can you open devtools and get the console log for the `Cannot read property 'length' of null` error?

**Comment by RELNO** [comment]
@Tyriar sure, see updated issue. Here it is in text:  

```
ERR Cannot read property 'length' of null: TypeError: Cannot read property 'length' of null
    at Object.r [as parseHex] (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6:7644)
    at Function.fromHex (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6:3903)
    at Y._getArgs (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1212:8827)
    at Y.onUpdate (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1212:8366)
    at new Y (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1212:6920)
    at j.activate (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1212:9699)
    at e.loadAddon (/Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar/xterm/lib/xterm.js:1:76959)
    at e.loadAddon (/Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar/xterm/lib/xterm.js:1:308917)
    at hi._createXterm (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2851:108694)
```

**Comment by RELNO** [comment]
@Tyriar @madskristensen any update? do you still need more info?

**Comment by RELNO** [comment]
Update: I've removed my local installation (as described here: https://stackoverflow.com/questions/42603103/how-to-completely-uninstall-vscode-on-mac) and then only synced settings that **were not** containing `terminal`. This is a crud solution, but for now I regain terminal functionality.

**Comment by Adrian3PG** [comment]
After updating to version 1.57.0, I am experiencing almost the same issue. The difference is I am not getting any error pop-ups, and besides the terminal, none of the extensions start either.

The fix for me was starting the Terminal.app process from the Dock. The second the terminal application starts, VSCode starts working normally.

**Comment by ashgti** [comment]
I recently came across this issue as well. I think this is due to this line:

https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/terminal/browser/terminalTypeAheadAddon.ts#L1257

Returning null here https://github.com/microsoft/vscode/blob/1dae051c56961b868cfaaeb8db9d1893ebaafd6c/src/vs/base/common/color.ts#L587

Causing this `||` https://github.com/microsoft/vscode/blob/1dae051c56961b868cfaaeb8db9d1893ebaafd6c/src/vs/base/common/color.ts#L259 to evaulate incorrectly.

That should be a `??`

**Comment by meganrogge** [comment]
@connor4312 thoughts?

**Comment by connor4312** [comment]
I'm not sure why that would be null, https://github.com/microsoft/vscode/issues/126055#issuecomment-859652485 doesn't have anything configured. But I think a try/catch around the color parsing is reasonable in case the user has an invalid setting.

**Comment by connor4312** [comment]
Pushed a fix for that.
