### ISSUE TITLE
A UX design recommendation for the Workspace Trust feature

### ISSUE THREAD

**Issue by KLszTsu** [microsoft/vscode#126010]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.57.0
- OS Version: Mac OS

The Workspace Trust added in this version is really useful, but the problem is that it interrupts the users' original thought.  

(**What has happened**)  
I open the folder, because I want to do some edit. The primany thing in my mind at that moment is that I want to edit the file, but the modal dialog is preventing me from doing so, that I need to stop what I'm doing right now, to think, and to choose whether I want to trust this folder.  

(**What should happen**)  
So why not make it a pop-up (like the recommendation to install a linter) and keep the folder restricted by default. The user can do things as they will, until finally <small>①</small>  they notice the pop-up, <small>②</small> they click on it, and <small>③</small> the modal dialog is shown (because it is important and a modal dialog will likely make user thinks more carefully) and <small>④</small> they confirm whether they want to enable all features or keep it restricted.  

Yours sincerely.

**Comment by KLszTsu** [comment]
I have just noticed there is a bar of workspace trust when I opened a random file instead of opening a folder, and I think that works pretty well. Although I think there are two problem with it.

## Problem 1. You don't need to open a new window to trust the current file

Unlike Microsoft Office, there is a simple button called "Enable editing". It is very straightforward. You click the button, so you can edit, or you would better stay in the protected view.  
![screenshot](https://user-images.githubusercontent.com/12217600/121660544-e3c05200-ca92-11eb-84ef-cd47faa047e5.PNG)  
(in English, `❗ PROTECTED VIEW: Be careful - files from the Internet can contain viruses. Unless you need to edit, it's safer to stay in Protected View. [Enable Editing]`)

(**What has happened**)  
And for our situation, I think it could be more straight forward. You don't need to open a new window to Manage.  
<img width="1440" alt="Screenshot 2021-06-11 at 9 05 10" src="https://user-images.githubusercontent.com/12217600/121661817-233b6e00-ca94-11eb-99d0-2126950440d5.png">

(**What should happen**)  
Instead You should be able to trust the windows right in place, like `Restricted Mode is blah-blah. Trust this window to enable linting, debugging and other features. [Trust] [Learn More]`, while the `Trust` button just trust the window, and the `Learn More` button is linked to the Workspace Trust page in the picture above.

## Problem 2. You don't need such a bright bar to grab people's attention.

Again, let's compare Microsoft Office with our situation.  

In Microsoft Office, the Protected View has a bright bar becuase it takes a crucial function of TextBox away - editing. Editing a such a crucial function of a TextBox, that designers will let it greyed out when it is not editable. But in Microsoft Office, greying out will affect browsing the document, so it has to find a workaround and chooses the bright bar to grab people's attention.  

(**What has happened**)  
But in our case, we can still edit the code and see code highlighting. Things like Markdown preview is working as well. That's enough for code browsing.  
Only when you want to write and run code, i.e., to work on the document, would you need to trust the document, but I think most people would like to run the code once to confirm their environment setup is okay before they work on the document, and they will need to confirm their trusting the document there.  
(**What should happen**)  
It is not necessary to use a bright top bar to grab people's attention that much when they just opened the file, and I think a pop-up to let people notice when they want will be just enough.  

Yours sincerely.

**Comment by sbatten** [comment]
@KLszTsu Thanks for your feedback. Since this issue is primarily a list of recommendations, I will close it but take your feedback into consideration as we smooth out this experience going forward.

For the initial post, I think you might find this setting useful: `security.workspace.trust.startupPrompt` which will allow you to disable the prompt and stick to restricted mode until you say otherwise. There are other settings you might finde useful under "security.workspace.trust" as well.

For "Problem 1", as this feature is very new, we want to make sure users understand what it means to trust a workspace before they take such an action. Because of this, we try to guide users to the editor when there isn't a lot of room to explain. After this becomes more of a mainstream feature, that could change.

For "Problem 2", restricted mode can have a large impact on some users workflows, such as many extensions not working. In testing, we found that it is easy to forget that your window is restricted without a prominent indication. As for how bright it is, you can change this with your theme.
