### ISSUE TITLE
Messages from extensions do not close automatically

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#12615]
This was reported first by @dbaeumer and I can reproduce: 

`vscode.window.showInformationMessage('Hello World!');`

Does not close automatically after 10 seconds like other messages from the workbench do that are just infos or warnings.

The reason is that https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/node/mainThreadMessageService.ts#L52 always adds a close action to the message even if no other actions are defined. That is not needed, a close action shows up automatically. However, when you pass in actions to message service, it will not automatically close the message assuming that user input is required.

I suggest to check if actions are provided and if so, just show the message like this:

``` typescript
if (!actions.length) {
    return this._messageService.show(severity, message);
}
```

This will cause the message to close according to the rules of the workbench message service. Only errors will stay.

**Comment by jrieken** [comment]
This was done on purpose because I don't want extensions authors to (ab-)use the information/warning/error messages as lightweight status messages (which the API also offers). My reasoning is that the messages atop are quite disruptive and should be used with consideration and iff used make the user do something to acknowledge the presented information. 

I would argue that the workbench behaviour is bogus because that 10sec delay is often leaving me puzzled what information was shown and if that was important? Also, I never know if I can wait-out a message or have to do something. 

@stevencl and @bgashler1 for more input and feedback

**Comment by bpasero** [comment]
The message UI deserves a facelift since years...

**Comment by dbaeumer** [comment]
I am all in for a facelift. The thing that is confusing right now for me as a dev and as a user that message sometimes auto close and sometimes not. So for pure consistency that has to change.
