### ISSUE TITLE
Ligature with space are disabled

### ISSUE THREAD

**Issue by fabrizioschiavi** [microsoft/vscode#126143]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.57.0
- OS Version: Mac OS 10.15.7

Steps to Reproduce:

1. Install [PragmataPro](https://fsd.it/shop/fonts/pragmatapro/) font
2. Open VS Code
2. Digit `|\ \ \` or `[INFO ]`

I relased a new version of PragmataPro typeface and now I'm sure that ligatures with `space` character like `|\ \ \ ` `/ / /|` `[INFO ]` `[PASS ]` are ignored in VS Code. 
Could you let me know how `space` character in ligatures is handled in VS Code please? 
Is there a way to enable ligatures with space inside?

![PragmataPro ligatures VS Code issue](https://user-images.githubusercontent.com/1576663/121786770-57ad4800-cbc2-11eb-9b2f-50c269b5a81c.png)
At left VS Code issue at right the correct view of these ligatures  in TextEdit

**Comment by alexdima** [comment]
@fabrizioschiavi All font rendering in the VS Code editor is delegated to the underlying browser. In the VS Code desktop case, which is built with Electron, font rendering is handled by Chromium.

There is one aspect of rendering whitespace that we do. In VSCode, all `<space>` characters are rendered as `&nbsp;`. We are doing this because otherwise the HTML rendering engine would squash two consecutive `<space>` characters into one.

Here is an approximation of what we are rendering. You can try opening this in Chrome/Edge to check what is going on: https://jsfiddle.net/v2z65q03/

**Comment by fabrizioschiavi** [comment]
@alexdima thank you very much for this correct hint!
Indeed now [PragmataPro](https://fsd.it/shop/fonts/pragmatapro/) works perfectly also in VS Code!

![Pragmatapro in VS Code git tree](https://user-images.githubusercontent.com/1576663/121905724-c0173900-cd2a-11eb-93c2-0fffd6b6ddea.png)
