### ISSUE TITLE
There is no way to assign an hotkey to the new command "hide tabs" (Or even better assign a key for toggling that option)

### ISSUE THREAD

**Issue by Aminadav** [microsoft/vscode#126208]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:  1.57.0
- OS Version: MacOS Big Sur

Steps to Reproduce:

There is not command for hiding tabs only for showing tabs.
Personally I think it will  be better to also have toggle. So same hotkey can be assigned to hide and show tabs.
Currently I can't assign any hottkey for showing tabs

![image](https://user-images.githubusercontent.com/3584317/121853974-3f404900-ccfa-11eb-86ca-fed2c94c2aed.png)

**Comment by Aminadav** [comment]
Do you need any more info for understand the issue?

**Comment by Tyriar** [comment]
The show tabs command was intended to be an internal only command which is why it doesn't show up in the command palette. Tabs are meant to be a set once and done type setting but if you really want to toggle them on and off I'd recommend making an extension and using an existing extension like https://marketplace.visualstudio.com/items?itemName=rebornix.toggle that toggles the `terminal.integrated.tabs.enabled` setting.
