### ISSUE TITLE
typescript decorator not color

### ISSUE THREAD

**Issue by kgtkr** [Microsoft/vscode#12621]
japanese title:typescriptのデコレーターで色が付かない
- VSCode Version:1.5.3
- OS Version:win10

![vscode](https://cloud.githubusercontent.com/assets/17868838/18830734/f4952db0-841c-11e6-8c70-8661820527cc.png)

**Comment by waderyan** [comment]
@kgtkr thank you for opening this issue. This is working with the latest bits for me. Can you try this with [Insiders](http://code.visualstudio.com/insiders) to confirm it works for you? 

Also, try installing this [extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) that was released today to solve grammar issues.

**Comment by kgtkr** [comment]
thank

**Comment by waderyan** [comment]
@kgtkr did this work for you then?

**Comment by mjbvz** [comment]
Looks like this is fixed by the new TypeScript grammar in VSCode 1.7+ 

![screen shot 2016-11-21 at 2 31 29 pm](https://cloud.githubusercontent.com/assets/12821956/20503375/16842218-aff7-11e6-95cb-71f4af45d27a.png)

@kgtkr please give this a try and let me know if you still see any issues around decorator syntax highlighting. Thanks.
