### ISSUE TITLE
Braces, Parens, Brackets do not autocomplete in HTML when next to an opening or closing tag. 

### ISSUE THREAD

**Issue by liangjacky** [Microsoft/vscode#12629]
- VSCode Version: 1.5.3 (5be4091987a98e3870d89d630eb87be6d9bafd27)
- OS Version: OSX El Capitan 10.11.6

Steps to Reproduce:
1. put your cursor to the immediate left or right of an html tag: <sometag> or </sometag>
2. type { or ( or [, and it will not autoclose. 

Expect the { to give {}

This makes coding in angular or any other templating language hard.

**Comment by Nikki1993** [comment]
Affected as well. A bit of a pain indeed to use interpolation in HTML with Angular 2.

**Comment by abgivant** [comment]
I've noticed this happens when working in plain JS files as well. 

I've run into it when trying to add a new method to a method chain. I will try to insert a new method in front of the closing semicolon and do not get the parenthesis or brace auto completion. It works fine if I remove the semicolon before adding the method.

![image](https://cloud.githubusercontent.com/assets/3431954/19194085/22e401c0-8c72-11e6-96ab-ff588a7c4614.png)

**Comment by Nikki1993** [comment]
Any news on this one? Kinda a deal breaker when you code with Angular on a daily basis :(

**Comment by Nikki1993** [comment]
@joaomoreno any chance this could make into 1.12 bug fixing release?

**Comment by rebornix** [comment]
our current implementation will look at the after character to decide whether to insert the closing bracket/paren or not, same issue as https://github.com/Microsoft/vscode/issues/9482 . Sorry for the late triaging, let's track it in https://github.com/Microsoft/vscode/issues/9482 .
