### ISSUE TITLE
Markdown text size too small by default. Would like ability to change font size of markdown rendering

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode#126294]
Was playing around a bit, and didn't see a way to set this. Both Editor Font Size and Markdown Preview Font Size didn't look to change it. Per chat with @rebornix this might be a few feature to add.

![image](https://user-images.githubusercontent.com/812783/121958337-6e65b300-cd18-11eb-8baf-3ca4b8a1f92b.png)

Note: "this is a normal line" is the markdown cell.

**Comment by misolori** [comment]
I would consider this a "bug" since the `markdown.preview.fontSize` setting says:

> Controls the font size in pixels used in the Markdown preview.

**Comment by DonJayamanne** [comment]
See related issue https://github.com/microsoft/vscode/issues/123149

**Comment by mjbvz** [comment]
Not in favor of reusing that setting for notebooks. I believe we should add a new setting for notebook markup/outputs

What do people want this setting to do? Scale everything? Or just the body text?

**Comment by misolori** [comment]
I think the same way the current setting scales everything. I think having separate settings is fine, same for output as long as it inherits from the notebook default.

**Comment by aschoettler** [comment]
@mjbvz 
> What do people want this setting to do? Scale everything? Or just the body text?

It would be nice to have a setting to scale everything (headers/text/etc) so that when `editor.fontSize` is larger for visibility, all the rendered markdown can be independently scaled up so that the markdown & code cells look proportional. For example, this would allow scaling the markdown so that rendered code blocks / inline code match the scale of actual code cells.

**Comment by snoop2head** [comment]
I am desperately waiting for an update for this feature. I changed "Markdown > Preview: Font Size" to be same as "Editor: Font Size" but it seems like it's not the feature that I expected. 

I think making independent settings will be better for users to make things customizable.

**Comment by wenkangmq** [comment]
If it's not this small people would not have noticed it. Just make it larger before adding customization feature for this.

**Comment by ezk84** [comment]
I'd like to add that as well as it being too small relative to the code and output text by default, in cases where I've deliberately set the editor's font size larger (to accommodate a small screen without also scaling the UI) the Markdown output then also looks completely out of place.

So it's not enough to set the default to a larger font size, but that size should either change in proportion to the current editor font size, or there should be a setting that allows for tweaking the two independently of each other.

**Comment by greazer** [comment]
Note that while there isn't the ability to change the notebook markdown font size separately, the current vscode-insider builds have increased the default size. For many of you this may be sufficient. However, keeping this issue open for possibly adding a the separate setting.

**Comment by FedericoDM** [comment]
I would just like to make a comparison with Databrick's Python Notebooks Markdown Feature:

![image](https://user-images.githubusercontent.com/67844597/137099042-ad91d01b-1231-477d-9be1-2385c469defb.png)

With VSCode's Jupyter Notebook Markdown Feature:

![image](https://user-images.githubusercontent.com/67844597/137099601-ba2899d5-089a-4802-9758-effb89e89330.png)

I do think a separate setting would be best for users who would like to have a bigger Markdown font size (which, in my case, is much better for my eyesight and helps me a lot in commenting the code) and separating it in blocks.

**Comment by tilohauke** [comment]
![image](https://user-images.githubusercontent.com/3463419/137617266-adb6124f-76c9-40fd-a9a3-2d274bc12f0b.png)
H1. In my case, the font size is way too small (13px). I have a high resolution tablet display. As far as I can see, this comes from the default font size of the editor. See screenshot.

**Comment by ZijianWang1995** [comment]
Please consider changing the font size in the next version.  Now it is too small for reading.

**Comment by greazer** [comment]
Thanks for all the feedback here. We do understand that having a separate setting to adjust the size of markdown text in a cell would be ideal. However, our resourcing situation is such that it's not as high priority of a work item to get done. PR's are welcome! :)

However, an in-the-meantime fix is to simply change the default size of the text as we did earlier. Given the following screenshot you can see the size of the VS Code font is pretty close to that of Jupyter Notebook. Both use font a font height that's similar to that of the code block fonts. 

It does look like the font kerning and family may be different between VS Code and Jupyter because VS Code's text appears a bit more "squished". It's also gray by default vs black. That certainly doesn't help the situation. 

![image](https://user-images.githubusercontent.com/11685408/139756371-43b18d69-0480-4f26-ba56-a41c8b0f1f40.png)

But then there's Google Colab. It is obviously using a much larger default font size. In fact, it's markdown text size is significantly larger than the code itself. 

All this said, we can certainly bump the default size a bit more to make it similar to that of Colab. However, that wouldn't likely fix the problem that @tilohauke screen-shotted above where the markdown text is significantly smaller than that of the code. @tilohauke, what is the code behind your screenshot?

**Comment by Nufflee** [comment]
The tiny Markdown font size makes Jupyter Notebooks in VS Code pretty much unusable, especially on 2K or even 4K displays. As pointed out in [this](https://github.com/microsoft/vscode/issues/126294#issuecomment-945068214) comment, the font size uses a CSS variable that is not possible to change in the settings. 

The only possible workaround I found was using the DevTools to change the variable every time I start up VS Code but that is not sustainable. Example screenshot attached.

![image](https://user-images.githubusercontent.com/19150550/140622306-69b1a014-8a8b-47f8-bcf8-21b3dadf6257.png)

**Comment by LiangChen3519** [comment]
Hi, I found a good to adjust the rendered markdown text. 
- Normal text

**Comment by LiangChen3519** [comment]
Hi, I found the good way to adjust the font related problems is using inline CSS command. For example:
- Normal text (e.g. some explanations or your conclusions)
before applying css:
![image](https://user-images.githubusercontent.com/61409749/140658226-10fdcc3a-4736-4154-89e0-e4b6a093c798.png)
after applying css:
![image](https://user-images.githubusercontent.com/61409749/140658318-e23a4825-0605-45b9-8dfc-3f90596101ea.png)
it is easy that you can adjust the font family, font size , font color or other formats. yes indeed, you may learn some about css, but you only need to focus on few common html elements, for example, a, p, h1~4.
- Latex symbols and math formulas
original:
![image](https://user-images.githubusercontent.com/61409749/140658552-e29abc19-f58c-4da1-9c86-0c9c6d8a97be.png)

u just need  '\huge' or '\large' or '\Huge' command:

![image](https://user-images.githubusercontent.com/61409749/140658695-8e5fac46-b957-41e5-b90f-29d2bd169b99.png)

Hopefully, it is useful.

**Comment by mjbvz** [comment]
The next insiders build adds a new `notebook.markup.fontSize` setting which controls the size of rendered markdown

It defaults to 120% of your editor font size (so 12px editor font size == 14.4px). We may adjust the default value based on feedback
