### ISSUE TITLE
Flaky smoke test

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#126213]
See https://dev.azure.com/monacotools/Monaco/_build/results?buildId=123056&view=logs&j=4d2898ab-dfbe-557e-92e7-aaac158fdd2f&t=0a31a1a1-76c6-5f31-444a-2b6049ed7294&l=69 on Linux

```
  22 passing (2m)
  4 pending
  1 failing

  1) VSCode Smoke Tests (Electron)
       VSCode Smoke Tests (Electron)
         Localization
           starts with 'DE' locale and verifies title and viewlets text is in German:
     Error: Timeout: get text content '.monaco-workbench .part.sidebar > .title > .title-label > h2' after 20 seconds.
      at poll (/__w/1/s/test/automation/out/code.js:176:19)
      at async Code.waitForTextContent (/__w/1/s/test/automation/out/code.js:237:16)
      at async Search.waitForTitle (/__w/1/s/test/automation/out/viewlet.js:13:9)
      at async Context.<anonymous> (out/areas/workbench/localization.test.js:31:13)
```

**Comment by dbaeumer** [comment]
I ran the test locally and the did pass for me. This is very frustrating since failures like this are almost never a consequence of the localization smoke test.

I will keep the item open to see how it goes in the next smoke tests. I have a debt item here https://github.com/microsoft/vscode/issues/93462 to think about what can be changed in general.

@TylerLeonhardt adding you as well. May be we can think about a different way of testing this now that we have control over the pipeline. I know we have a pseudo language pack published.

**Comment by alexdima** [comment]
@dbaeumer maybe this test was a casualty of these recent test problems that @joaomoreno and @bpasero have been fixing. 

Regarding the failure rate, this particular test looks pretty unhealthy recently https://dev.azure.com/monacotools/Monaco/_test/analytics?definitionId=111&contextType=build

![image](https://user-images.githubusercontent.com/5047891/122297054-6c0f7e80-cefb-11eb-8936-d303d912c1ee.png)

I agree that there isn't any clear action to do. Maybe we can revisit the stats in 1-2 weeks or maybe you can change the order that your test is not the first one / the last one. Also worth considering is if the test is self-contained and executes OK regardless of marketplace availability.

**Comment by bpasero** [comment]
To clarify: my changes addressed an issue in web smoke tests where the welcome editor would always appear first. I had fixed this for desktop based smoke tests already 2 weeks ago.

**Comment by dbaeumer** [comment]
Agree, that the test was unhealthy lately since it depends on reading translated strings from the UI. These failures would also occur with a pseudo language pack since it was not a translation issue.

@jrieken would I be able to add a psuedo command to the core that allows me to simply return three strings. Where would I do that best?

**Comment by TylerLeonhardt** [comment]
> adding you as well. May be we can think about a different way of testing this now that we have control over the pipeline. I know we have a pseudo language pack published.

If possible, we could install the language pack on the fly from the marketplace? Though I'm not sure that's a good idea for these tests.

**Comment by dbaeumer** [comment]
@TylerLeonhardt that is what we do. The flakiness doesn't come from that part. It comes from the fact that we try to grab strings from the DOM and that periodically fails to mostly unknown reasons (e.g. timeouts).

So the idea is to read the strings using commands and not the DOM.

**Comment by TylerLeonhardt** [comment]
> So the idea is to read the strings using commands and not the DOM.

Gotcha. I don't know too much about the smoke tests. Is it common practice for us to run commands and check the results in the smoke tests? Also for Localization tests I would guess we need to find a command that has a localized result.

**Comment by dbaeumer** [comment]
@TylerLeonhardt the idea is to have a `fake` command that we only use to get a handful of localized strings

@jrieken can you please comment on my question here: https://github.com/microsoft/vscode/issues/126213#issuecomment-862989259

**Comment by alexdima** [comment]
@dbaeumer I have seen this done before e.g. for the colorize integration tests: https://github.com/microsoft/vscode/blob/4f222a873074b8051b274c1d9a5343b009f9d50d/src/vs/workbench/contrib/themes/browser/themes.test.contribution.ts#L235

**Comment by dbaeumer** [comment]
I added support to the smoke test driver to fetch translated strings. No need for a command anymore.

**Comment by joaomoreno** [comment]
@dbaeumer and I finnaly figured out the root cause of this:

The DE extension gets installed properly. But there's a `onDidInstallExtension` listener which sets up a cache for localization extensions. If we quit Code before that listener gets to run (happens not so often), a relaunch of the app won't make it in German. A consecutive relaunch will actually work since the cache is recomputed.

The fix here is to make sure that when the workbench reports a localization extension has been installed, that means that the cache has also been properly setup.

**Comment by TylerLeonhardt** [comment]
@joaomoreno do you think it's possible to install extensions via CLI instead? It's something I wanna figure out anyway because for the vscode-loc repo I'd like to try installing a VSIX of the extension packs in CI.

I don't really have much context on how to do this.

**Comment by TylerLeonhardt** [comment]
Just to clarify, I meant install an extension via the CLI in the smoke tests.
