### ISSUE TITLE
IMenu must be disposed after use

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#126365]
When calling `createMenu` you are being returned a menu-instance that is listening to menu registry changes and context key changes. The latter is a really hot event and listeners for that should never be leaked.

The usage pattern is often (1) create menu, (2) extract actions for rendering, (3) done. During that last "done" the menu must be disposed. We can also think about making this less error prone and add something like `getMenuSnapshot` which only returns the menu structure without ever updating it.

I composed the following list of leaking menu using call hierarchy and review

---

- [x]  @hediet https://github.com/microsoft/vscode/blob/7cd9352928885ea05fae6d65b6b95163d44c24b6/src/vs/editor/contrib/inlineCompletions/inlineCompletionsHoverParticipant.ts#L84
- [x] @sbatten maybe? https://github.com/microsoft/vscode/blob/61f3ac6e07bf2aa4c5b0470d7afa70f48c328275/src/vs/workbench/electron-sandbox/parts/titlebar/menubarControl.ts#L118 
- [x] @joaomoreno @eamodio https://github.com/microsoft/vscode/blob/c88888aa9bcc76b05779edb21c19eb8c7ebac787/src/vs/workbench/contrib/scm/browser/menus.ts#L109 
- [x] @joaomoreno @eamodio https://github.com/microsoft/vscode/blob/c88888aa9bcc76b05779edb21c19eb8c7ebac787/src/vs/workbench/contrib/scm/browser/menus.ts#L92 
- [x] @joaomoreno @eamodio https://github.com/microsoft/vscode/blob/c88888aa9bcc76b05779edb21c19eb8c7ebac787/src/vs/workbench/contrib/scm/browser/menus.ts#L83 
- [x] @sbatten maybe? https://github.com/microsoft/vscode/blob/2aa5ce1adeda154e1ed346ff65f0ca3e3d7cc09a/src/vs/workbench/browser/parts/titlebar/menubarControl.ts#L696 
- [x] @joaomoreno https://github.com/microsoft/vscode/blob/043b9fbeb60da6ccfd52132f99f07e59baf465b9/src/vs/workbench/contrib/scm/browser/dirtydiffDecorator.ts#L190 
- [x]  @roblourens https://github.com/microsoft/vscode/blob/e1c8da5b7275738cc3905dc484248254a6c2ad0c/src/vs/workbench/contrib/notebook/browser/view/renderers/cellOutput.ts#L344
- [x] @roblourens https://github.com/microsoft/vscode/blob/a198d712f111ddf8379419b5036a89d378071cb3/src/vs/workbench/contrib/notebook/browser/view/renderers/cellRenderer.ts#L845 
- [x] @roblourens https://github.com/microsoft/vscode/blob/a198d712f111ddf8379419b5036a89d378071cb3/src/vs/workbench/contrib/notebook/browser/view/renderers/cellRenderer.ts#L880 
- [x] @roblourens https://github.com/microsoft/vscode/blob/a198d712f111ddf8379419b5036a89d378071cb3/src/vs/workbench/contrib/notebook/browser/view/renderers/cellRenderer.ts#L883

**Comment by joaomoreno** [comment]
> The usage pattern is often (1) create menu, (2) extract actions for rendering, (3) done.

The fact that the menu has an `onDidChange` event tells me that is exactly not the usage pattern. The menu should stay alive as long as changes to it would directly affect rendered UI. As soon as that UI piece goes away, the menu must be disposed.

I have reviewed all usages where my name is and I confirmed that the menu is alive only for the right amount of time. That is, as long as there is rendered UI which might change as actions get added/removed from the menu, the menu instance is alive and its `onDidChange` is being listened to. As soon as that UI goes away, the menu instances are disposed correctly.

Let's look at the `DirtyDiffWidget` example. It's a UI component which opens when clicking on the gutter diff decoration. It shows a menu with contributed actions. These actions can always get registered after the widget itself appears, due to slow activations for example, so it must listen to the `menu.onDidChange` event, which means the menu must not be disposed as long as the `DirtyDiffWidget` is open.

**Comment by jrieken** [comment]
> The fact that the menu has an onDidChange event tells me that is exactly not the usage pattern. The menu should stay alive as long as changes to it would directly affect rendered UI. As soon as that UI piece goes away, the menu must be disposed.

Yes, of course. That's how the menu is designed but it is often not used like that, e.g for context menu it is never used like that. 

> Let's look at the DirtyDiffWidget example. It's a UI component which opens when clicking on the gutter diff decoration. 

I might be missing something but I don't see a `dispose`-call or anything like that in `DirtyDiffWidget#menu`

**Comment by joaomoreno** [comment]
Holy cow, you're right! 🙈 I could've sworn... The widget completely lacks a `dispose`, thanks for that!

**Comment by sbatten** [comment]
my code pointers refer to menu instances that are created once and used to update the application menu. they should not be disposed until everything the menu bar control is disposed. I've wrapped them with `_register` since that was missing.
