### ISSUE TITLE
Smoke Test quick outline failure

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#126438]
```
  1) VSCode Smoke Tests (Electron)
       VSCode Smoke Tests (Electron)
         Language Features
           "before all" hook for "verifies quick outline":
     Error: connect ENOENT /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmp-9152eDE5SvxLn0GJ
      at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)

```

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=123375&view=logs&jobId=4d2898ab-dfbe-557e-92e7-aaac158fdd2f&j=3792f238-f35e-5f82-0dbc-272432d9a0fb&t=07088cf7-fede-5f74-0d50-155edd53af7d macOS CI

**Comment by bpasero** [comment]
This sounds more like a driver / connection problem to me than related to the quick outline test specifically.

**Comment by joaomoreno** [comment]
I'll keep an eye out for this specific error. If it comes again we should definitely tackle it.

**Comment by lszomoru** [comment]
I've seen this in the past, and my hypothesis is that this happens if for some reason `connectDriver` takes more than 5 second to complete. We retry 50 times and we wait 100 milliseconds between retries. One thing worth to try would be to either increase the retry count, or the wait between retries.

https://github.com/microsoft/vscode/blob/6afedfdad59d1f1ba4b614341d21c67775e158a9/test/automation/src/code.ts#L71
