### ISSUE TITLE
Add notebook webview css variable for editor padding

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#126436]
We removed the padding around cell outputs, which is great, but I propose that we add a CSS variable that represents the left padding of the editor. Then an output like github issues could line up its text with the text in the editor, which might look nice. The hover highlight on rows will still take the full output width.

![image](https://user-images.githubusercontent.com/323878/122152964-eca87f00-ce16-11eb-9f32-15ef010c53a0.png)

**Comment by connor4312** [comment]
The margin here is the Monaco editor margin (or `contentLeft` in the `EditorOption.layoutInfo`). We can get this if an editor is available, but there may not be. I think it's also slightly wrong to base information in the entire renderer webview based on a particular editor, since options might vary between types/languages in the editors. I don't think this is worth adding at the moment unless someone else knows a way to get at this information more readily.
