### ISSUE TITLE
Something around `list.activeSelectionIconForeground` broke for me

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#126498]
I think we recently introduced `list.activeSelectionIconForeground`. My default settings are this:

```json
"workbench.colorTheme": "Default Light+",
"workbench.colorCustomizations": {
    "focusBorder": "#F3F3F3",
    "inputOption.activeBackground": "#007acc1f",
    "editorLineNumber.activeForeground": "#2b91af",
    "list.activeSelectionBackground": "#3399FF",
    "list.focusHighlightForeground": "#0066bf",
    "activityBar.activeBorder": "#2c2c2c",
    "sideBarSectionHeader.border": "#0000",
    "quickInputList.focusBackground": "#d6ebff",
    "quickInputList.focusForeground": "#616161"
}
```

And this means my suggest widget looks like that now:

![image](https://user-images.githubusercontent.com/900690/122255246-3bfdb680-cece-11eb-829a-d53974d6b87c.png)

Then I added `"list.activeSelectionIconForeground": "#616161"` as Miguel suggested which fixes the issue for suggest, but the SCM view no longer shows the icons in white color when selected (even though the decoration is still white):

![image](https://user-images.githubusercontent.com/900690/122255346-5041b380-cece-11eb-9b59-2b98cc1e3f4f.png)

Can I resolve this somehow?

**Comment by misolori** [comment]
This is by design because we intend to have a single focus state that is the same across list/quick pick/suggest:

<img width="348" alt="CleanShot 2021-06-16 at 12 33 13@2x" src="https://user-images.githubusercontent.com/35271042/122281371-0beaef00-ce9f-11eb-874e-d15a84869bac.png">

<img width="631" alt="CleanShot 2021-06-16 at 12 33 28@2x" src="https://user-images.githubusercontent.com/35271042/122281395-10afa300-ce9f-11eb-940a-746b305c1abf.png">

<img width="481" alt="CleanShot 2021-06-16 at 12 33 39@2x" src="https://user-images.githubusercontent.com/35271042/122281414-16a58400-ce9f-11eb-82f3-5bd3d87561cd.png">

<hr>

The suggestion would be the adjust your colors so that your focus states are one like:

```json
    "workbench.colorCustomizations": {
        "list.activeSelectionBackground": "#3399FF",
        "list.activeSelectionIconForeground": "#fff",
        "quickInputList.focusBackground": "#3399FF",
        "quickInputList.focusForeground": "#fff",
    },
```

<img width="336" alt="CleanShot 2021-06-16 at 12 35 31@2x" src="https://user-images.githubusercontent.com/35271042/122281670-608e6a00-ce9f-11eb-92b4-72442d03f65c.png">

<img width="653" alt="CleanShot 2021-06-16 at 12 35 49@2x" src="https://user-images.githubusercontent.com/35271042/122281687-64ba8780-ce9f-11eb-991f-c44cd49bf425.png">

<img width="476" alt="CleanShot 2021-06-16 at 12 36 00@2x" src="https://user-images.githubusercontent.com/35271042/122281702-6a17d200-ce9f-11eb-8ee9-6fc91868e753.png">

**Comment by bpasero** [comment]
@misolori thanks, I got it to working better now. Meanwhile I also changed `"list.focusHighlightForeground": "#fff"` because I feel our highlight color is not very visible for the focussed item and I think this works really well, should it maybe be the default?

![image](https://user-images.githubusercontent.com/900690/122346135-e9adab80-cf48-11eb-99b4-5ef08ac17d01.png)

**Comment by misolori** [comment]
I did originally suggest to use white for the highlight label but for feedback that it needed to stand out more https://github.com/microsoft/vscode/pull/122893

**Comment by bpasero** [comment]
Yeah up to you, I think the current default highlight for the active focused item is a bit hard for me see.
