### ISSUE TITLE
vscode.env.openExternal in VS Code 1.57 does no longer spawn the associated process as external

### ISSUE THREAD

**Issue by yhatt** [microsoft/vscode#126502]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.57.0
- OS Version: Darwin arm64 20.5.0 (macOS Big Sur 11.4)

Steps to Reproduce:

```javascript
vscode.env.openExternal(Uri.file('/home/xxx/test.pdf'))
```

VS Code tries to open the PDF document in the editor as binary. The previous 1.56 have been opened the PDF file with desktop-associated viewer.

According to the guide described in https://code.visualstudio.com/api/advanced-topics/remote-extensions#opening-something-in-a-local-browser-or-application, VS Code looks like recommends using `openExternal()` to spawn the external process than using `opn` (`open`) module.

I felt this change about spawning might become to have been restricted by some security reason or proposed API change, but anyway it may break existing workflow provided by extensions.

Affected:

- https://github.com/rvanbekkum/vsc-xliff-sync/issues/89

**Comment by jrieken** [comment]
@joaomoreno I believe this is because of your changes in external uri land. A breakpoint [here](https://github.com/microsoft/vscode/blob/a6f7aa5e4c5832c3d788ab9a8146ac69a6e5a77f/src/vs/editor/browser/services/openerService.ts#L213) shows that the uri has been turned into `code-oss:workspace?file%3A%2F%2F%2FUsers%2Fjrieken%2FDocuments%2FCOMPUTER_GRAPHICS_AND_ART_May1976.pdf` (from `file:///...`)

**Comment by joaomoreno** [comment]
@jrieken Yeah could be. Does that transformation happen here?

https://github.com/microsoft/vscode/blob/a6f7aa5e4c5832c3d788ab9a8146ac69a6e5a77f/src/vs/editor/browser/services/openerService.ts#L217
