### ISSUE TITLE
Process stop buttons in Call Stack pane always stop first process in list

### ISSUE THREAD

**Issue by JordanLongstaff** [microsoft/vscode#126541]
I have several processes running and they are all listed in the Call Stack pane of the Run and Debug view. If I click the Stop button for the third process in the list, I would expect the third process to be stopped; the first one always gets stopped instead, no matter which stop button I click.

**Comment by weinand** [comment]
@JordanLongstaff with "Stop button" you mean the stop button on the item in the Call Stack pane, not the "Stop button" in the debug bar, right?

![2021-06-17_11-30-36](https://user-images.githubusercontent.com/1898161/122370984-cd693900-cf5f-11eb-8c40-bd4f87e6f36c.png)

**Comment by JordanLongstaff** [comment]
@weinand Correct. And upon further experimentation, it's not simply the first process in the list that gets killed, it's the one selected in the debug bar.

**Comment by gjsjohnmurray** [comment]
/confirm

@weinand here's how I reproduced this with vscode-mock-debug

1. Run the 'Debug test.md' configuration.
2. 'Step Over' once.
3. Use the '...' menu at the right-hand end of the 'RUN AND DEBUG' view header to 'Start Additional Session' and pick 'Debug test.md'. The CALL STACK pane should look like this:

![image](https://user-images.githubusercontent.com/6726799/123529977-9e845d00-d6ed-11eb-8f8b-7516057f31d6.png)

4. Hover over the first session in CALL STACK. When the action buttons appear, use Step Over with the expectation that the first session will advance by one line.
5. :bug: the Step Over gets applied to the second session.

As @JordanLongstaff wrote, the action buttons on every session row of CALL STACK seem to act on the session currently selected in the Debug Tool Bar (which in my screenshot is docked rather than floating).

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/125327
fixed in insiders
