### ISSUE TITLE
Fine-grained Workspace Trust configuration

### ISSUE THREAD

**Issue by karimmac** [microsoft/vscode#126568]
I like the new workspace trust feature. At the moment it seems to be opt-in on every new untrusted project.
Can the configuration be extended to deny as well as allow trust on folders (and their children)? This lets me:
1. safely clone any third-party project I like into an 'untrusted' folder without needing an extra trust/don't-trust confirmation.
2. trust my own folder of repos but then selectively untrust specific sub-folders that may contain third-party code.

**Comment by sbatten** [comment]
Thanks for the positive feedback and suggestions. We already support adding parent directories so that you don't get asked so frequently about workspace trust. Check out https://code.visualstudio.com/docs/editor/workspace-trust#_selecting-folders for how to add your own repos.

As for the ability to deny trust with an exemption list, see https://github.com/microsoft/vscode/issues/126311
