### ISSUE TITLE
1.57.0 May 2021 (Ubuntu 16.04): Cannot enter superusermode

### ISSUE THREAD

**Issue by hansenquadros** [microsoft/vscode#126519]
After the latest May 2021 update there is no way to start vs code in superuser mode which could be previously done using
sudo code --user-data-dir 
or
sudo code --user-data-dir="~/.vscode-root"

**Comment by bpasero** [comment]
Note that we will eventually not allow you to use `sudo` anymore in VSCode due to our work of enabling the secure sandbox (see
https://github.com/microsoft/vscode/issues/92164).

For now this will be fixed with https://github.com/microsoft/vscode/issues/126027 but please consider to stop using `sudo`.
