### ISSUE TITLE
Test: Inform user about TS 2.0 in the product

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#12657]
Test for #12091

**Comment by octref** [comment]
Just so that you know, when I click "Use Workspace" here:

![image](https://cloud.githubusercontent.com/assets/4033249/18844463/2d3f7210-83d2-11e6-85f6-06b3a80e1623.png)

It made settings.json badly formatted.

![image](https://cloud.githubusercontent.com/assets/4033249/18844491/4ae130a6-83d2-11e6-9ca5-4c486338316a.png)

**Comment by dbaeumer** [comment]
@octref: can you please file an issue against vscode and assign it to Ben you was working on that feature.

**Comment by dbaeumer** [comment]
Closing this item. It is already covered by https://github.com/Microsoft/vscode/issues/12633
