### ISSUE TITLE
[New test UI] When a top-level test is running, update the status of all items in the subtree to running as well 

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode#126629]
Hi there! We're plugging into the new test explorer API and one thing we just noticed is that when a top-level item is running, we don't update the status of the "children" tests to be running as well:

![image](https://user-images.githubusercontent.com/45497113/122474978-cf8bc180-cf78-11eb-9d23-a5fd1141ac40.png)

In the image above (sorry for the bad resolution! but I hope it's enough to give an idea) I was expecting to see the status for test_patterns.py,  test_timeline.py and test_vendoring.py to be "running" as well, i.e. with the loading icon. 

cc @karthiknadig @brettcannon

**Comment by connor4312** [comment]
The approach the explorer takes now is to assume that state is set on the individual tests, like "test_patterns.py". The "computed state" displayed for for parents in the tree is the highest-priority state of any of their children, so if test_patterns.py is set to be "running" then the two `tests` nodes will automatically be marked as running too.

Does that makes sense for your model?

**Comment by karthiknadig** [comment]
@connor4312 In the case above, we ran the node that says `test_patterns.py`, since we can directly run that node we `setState` for that node. What we expected was all the node under it to automatically have computed state as running. I understand that the parent node will have computed state as running.

So my question is, should we be setting the run state for each of the child nodes manually or should that be computed as well.

**Comment by connor4312** [comment]
> should we be setting the run state for each of the child nodes manually 

You should (and only need to) set the run state for the child nodes.
