### ISSUE TITLE
Trust feature -- issues

### ISSUE THREAD

**Issue by irvnriir** [microsoft/vscode#126631]
Issue Type: <b>Bug</b>

Related: #126310 ;.

### Definitions

A "known" function is an one of which, an enabling (even {on 1st start / by default}) is explicit, and which is fully (in relation to security and privacy) described .

### Issues and description

When **any** file is opened in Text Editor, Hex Editor or other, or a folder or save is opened as workspace . Without enabled relevant known functions, or installed harmful extensions . Must be 0 bits of the file/-s content executed (processing to : in certain way modify the rendered output ; is not an execution of the file/-s) .

1. Excessive permitting/-ssions

    By selecting something like "i Trust the file/folder/workspace", or disabling the Trust feature, i do not give any permission to : execute the file/-s in other ways than by enabled known functions ;.

    Counting that user wouldn't enable known function if he wouldn't want it, the Trust feature seems as an attempt to make a responsibility backdoor .
    
    The whole feature just should be merged into the functions in the system and Extensions API, maybe with : ~enhanced access or Android alike ; permission/-s for Extensions .

2. Security misleading

    Only for **known functions** that really need relevant access and is important, a way to disable certain either all, for certain folders, may be useful, including include of potential folders by using whitelist as a main one, but obviously additional blacklist is required (even minimally large storage, #126273, and other) .

    The issue is that for the functions development it may seem that this feature provides any user protection, what is completely not true -- obviously, with enough load, no one: can, will either should be concerned about opening file system entities as workspace items ;. So the known functions need to be prominent and always controllable/{disable-able} .

### System info

VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.354Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

**Comment by sbatten** [comment]
Hi @irvnriir, thank you for the write up. A couple points I want to clarify.

1) Before version 1.57, properly implemented extensions were able to run code on startup to provide *expected* features. e.g. It is expected that when you open a workspace in VS Code with the ESLint extension installed that you get proper linting. Saying that you trust a folder with workspace trust puts you at no more risk in 1.57 than in 1.56.2.

2) In order for ESlint to provide you proper linting, it tries to use the eslint module from your workspace (otherwise you will have version mismatches). This is, itself, the vulnerability if the repo you have clone has a malicious version of eslint.

3) Prior to workspace trust, multiple extensions in the marketplace were having to add their own dialogs/notifications to ask the same question that workspace trust asks: Do you trust where this source came from because eslint cannot answer that for you. Workspace trust is intended to prevent you from having to answer that for every extension that wants to do the right thing.

4) So, in order to provide you with *expected* features without excessive prompting, we have decided to ask you on start because testing showed that if we were "safe by default" without prompting, users would not easily discern why *expected* features were not working. The trust question is not about eslint, it is about the workspace. If you prefer to disable *expected* features in the name of safety, you can use restricted mode. You can then use our provided settings to avoid excessive prompting: https://code.visualstudio.com/docs/editor/workspace-trust#_settings

**Comment by irvnriir** [comment]
Another clarification --

* the issue 1. is about certainty/scope of the controls (this shortly/temporally can be improved even by changing texts),
* and 2. is about that the security is negated due to inconsistency -- one of all possible harmful items can easily get inserted or not searched-for in a Trusted workspace, while the user is not provided resources to determine what items that may be and all given options is: disable all features that may have risk, or enable all risky features to get even only 1. that is needed .

**Comment by Shfty** [comment]
Hi @sbatten, can you provide more details on the heuristic used by VSCode to determine when a plugin `wants to do the right thing`?

Being able to determine programmer intent through static analysis of their code sounds like an extremely powerful piece of tooling, so I'd be interested to learn more.

Given the complexity of the problem space, I assume it must be using some sort of ML solution to 'fill in the gaps'? - similar to upscaling an image, or making a static portrait of a popular influencer sing along to trendy 'meme content' for social media.

This sounds like an innovation that could greatly benefit the wider DevOps industry. I see great potential in a git extension that can analyze my employees' code as it's committed, and output an inferred list of potential bugs, malicious behavior, and future crimes against the state that can be archived for use in review meetings or dealings with local law enforcement.

Looking forward to hearing back!

Cheers,

---
Josh Palmer
VP, Tired Devs LLC

**Comment by irvnriir** [comment]
@Shfty . no need to add junk to the Issue .

**Comment by sbatten** [comment]
@irvnriir Thanks for all of the feedback. You can see more information about our development process in this recent blog post https://code.visualstudio.com/blogs/2021/07/06/workspace-trust

**Comment by irvnriir** [comment]
@sbatten  [[link]](https://code.visualstudio.com/blogs/2021/07/06/workspace-trust#_but-that-dialog) refer to separating actions that require dangerous access, but says that this was removed .

Beyond that, i see no relation to solving the subject issues .
