### ISSUE TITLE
VSCode marks file as modified after undo

### ISSUE THREAD

**Issue by vidhu** [microsoft/vscode#126795]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.57.1
- OS Version:

Steps to Reproduce:

1. Open any file
2. Make any change (1 character for example)
3. Undo it (Edit -> Undo) or manually so that the file is exactly the same as step 1
4. VSCode marks this file as modified and prompts to save it when closing the file

This should not happen since the file is exactly the same as it is on disk

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by vidhu** [comment]
@bpasero Yes this happens when launched with extensions disabled.

(Edit -> Undo) does removes the modified marker. I was mistaken in my original post

However manually undoing a changes doesn't remove the modified marker.

I've attached a video of me demonstrating this with extensions disabled


https://user-images.githubusercontent.com/1566265/123200555-f6695c80-d47e-11eb-9c71-723844852e1d.mp4

**Comment by vidhu** [comment]
@bpasero Why is this expected behavior?

There aren't any changes to the file in my example. 

However VScode prompts me to save it and claims that "there are unsaved changes".

What would the unsaved changes be in this case?

**Comment by bpasero** [comment]
Picked the wrong action, meant to mark as duplicate of https://github.com/microsoft/vscode/issues/919
