### ISSUE TITLE
Missing the document.uri.query field when running extension in Codespaces

### ISSUE THREAD

**Issue by tianzerun** [microsoft/vscode#126894]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.57.1
- OS Version: Darwin x64 19.6.0
- Codespaces Version: 1.57.1

We come across a behavioral inconsistency on VSCode v.s CodeSpaces when developing our extension. We have a class that implements the `vscode.CommentingRangeProvider`. In its `provideCommentingRanges(document: vscode.TextDocument)` method, we are trying to access the`document.uri.query` field, but it is missed if the uri scheme is `file` and when we are in CodeSpaces. This never happened when we are developing in VSCode. Is it a bug or an intended behavior? 

For your convenience, here is an extension we prepared to demo this issue: 
https://github.com/tianzerun/vscode-extension-helloworld/tree/main

### VSCode:
<img width="1526" alt="vscode-document-uri" src="https://user-images.githubusercontent.com/23252886/122908730-0a319780-d387-11eb-9917-9872a417ec83.png">
Notes: there is a query field

### Codespaces:
![codespaces-document-uri](https://user-images.githubusercontent.com/23252886/122908688-00a82f80-d387-11eb-8965-edb3de6a189c.png)
Notes: there is no query field

**Comment by jrieken** [comment]
> we are trying to access thedocument.uri.query field, but it is missed if the uri scheme is file and when we are in CodeSpaces.

Query parameters for `file` uris are bogous because the file system doesn't define any meaning for those, e.g `file:///foo/bar.txt?aaa` is the same as `file:///foo/bar.txt?bbb`. For custom schemes that's a different story and up to the implementor of the file system. 

@bpasero for failing/checking in the file system provider when this happens and @alexdima for why this is different in codespaces. Maybe due to uri transforming?

**Comment by alexdima** [comment]
Let's track in https://github.com/microsoft/vscode/issues/110377
