### ISSUE TITLE
File Extension appears to not populate // when run is clicked

### ISSUE THREAD

**Issue by Bourqu** [microsoft/vscode#126865]
User@DESKTOP-4MFQ21B MINGW64 ~/Desktop/C_C++
$ cd "c:\Users\User\Desktop\C_C++\" && gcc riddle.c -o riddle && "c:\Users\User\Desktop\C_C++\"riddle
bash: cd: c:\Users\User\Desktop\C_C++" && gcc riddle.c -o riddle && c:UsersUserDesktopC_C++"riddle: No such file or directory

**Comment by Colengms** [comment]
Although the command line refers to C++, I don't see any information here that would suggest it has to do with the C/C++ Extension.

@Bourqu Since one of the paths in your command line appears to be missing backslashes, is it possible that you have an incorrect path in a json file somewhere?  Because json strings use backslashes for escape sequences, you would need to escape any intentional use of backslash.  i.e.: `c:\\Users\\User\\Desktop\\C_C++`

**Comment by Bourqu** [comment]
hHey Colen, not sure where I would fix that? I had submitted this issue on
the vscode repository and they ahd suggest it was related ot the extension,
i had seen a user have a similar issue where again the response was caused
by an extension
