### ISSUE TITLE
Explorer: consider to refresh contents more aggressively based on events?

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#126817]
Given issues such as https://github.com/microsoft/vscode/issues/28432 I wonder if a pragmatic solution could be to simply refresh the explorer in some cases based on patterns we do else where. To give examples:
* all active text editors reload when focus goes into the window (assuming files got changed externally)
* a text editor reloads when switching between one and another editor (i.e. clicking on a tab that is hidden)
* git changes view refreshes on window focus

These pragmatic solutions to file watcher issues have improved the situation quite a bit I would say. I almost have not gotten any file watcher related issue for a long time.

Some ideas for the explorer:
* refresh (but do not reveal) when window gains focus (see [example](https://github.com/microsoft/vscode/blob/c4f3f8f9bea635a0bd7d1aff29c55382597922fa/src/vs/workbench/contrib/files/browser/editors/textFileEditorTracker.ts#L46-L46))
* refresh when the explorer becomes visible (e.g. you click on the explorer when another view is visible)

One thing to keep in mind is that these operations are typically without side effects if nothing changes. For example, text editors return quickly if the file on disk has not changed and there is absolutely no UI flicker when reloading and nothing changed. I am not sure how the explorer deals with [`IExplorerService#refresh`](https://github.com/microsoft/vscode/blob/a0a9141869093495444eb4c107da6f5c173d456d/src/vs/workbench/contrib/files/browser/explorerService.ts#L261-L261) and how efficient it is. If it is not super efficient, I would limit this to running when window gains focus only.

**Comment by gjsjohnmurray** [comment]
When Explorer is displaying a workspace with folders sourced from a FileSystemProvider extension, having automatic refresh may be a problem if the nature of the FSP means that the refresh could be expensive.

**Comment by isidorn** [comment]
@bpasero thanks for opening this issue.
As @gjsjohnmurray points out this might depend on the nature of the FSP, however since our main local file system provider seems to handle this case well I am open to experiment with this.

Explorer itself does not do any heavy lifting on refresh, the only thing that is done is `tree.refresh` and I think tree can handle this nicely since we are already calling refresh very aggressively in the Debug Console.

So I suggest to try this out and see how it goes.
I would like to do it start of milestone to have enough time to get feedback, so assigning to July, however since in July I am almost the whole month out this will probably happen start of August.

**Comment by isidorn** [comment]
Decided to refresh both when the window gets focus, and when the explorer becomes visible.
The tree refresh should be pretty fast. Though I am doing this start of milestone so we see how it goes, I am optimistic about the change.

**Comment by bpasero** [comment]
👏
