### ISSUE TITLE
Staging a line causes the whole block to be replaced

### ISSUE THREAD

**Issue by lainets** [microsoft/vscode#126989]
Issue Type: <b>Bug</b>

### Problem:

1. Modify multiple consecutive lines
2. Apply "Stage selected ranges" to some of them, e.g. one of them

Actual result:
All of the modified lines are removed and replaced with only the selected lines.

Expected result:
Only the selected lines are removed and replaced with only the selected lines.

### Example:

Stage only the first line of
![image](https://user-images.githubusercontent.com/49596400/123082611-e2464080-d427-11eb-940e-1354dd9482cb.png)
Actual result:
![image](https://user-images.githubusercontent.com/49596400/123082653-eeca9900-d427-11eb-81cf-50a89fef37a0.png)
Expected result:
![image](https://user-images.githubusercontent.com/49596400/123082713-ff7b0f00-d427-11eb-906f-53eb21e1df8f.png)

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No
Remote OS version: Linux x64 5.4.0-39-generic
Remote OS version: Linux x64 5.4.0-39-generic

**Comment by lszomoru** [comment]
@lainets, apologies for not getting back to you on this issue. Could you please try to see if you are able to reproduce the problem in the latest `Insiders` release (2022-01-27)? I have tried to reproduce the issue and it looks like it might have been fixed already. Thank you!

**Comment by lszomoru** [comment]
Do you mind recording a gif (you can use https://gifcap.dev/) while reproducing the issue as that would help me a lot. Thanks!

**Comment by lainets** [comment]
https://user-images.githubusercontent.com/49596400/151402758-2e67f7f3-4d31-4bf7-9d19-ae3f71b31829.mp4

**Comment by joaomoreno** [comment]
This happens because our range staging algorithm always applies the selected lines over the entire removal of the original lines. It treats the entire range as a single element. So, that single line will replace the 3 lines.

We could potentially implement the following heuristic: if the diff refers to the name number of lines on both original and modified documents, then we can map line by line.

- Today: we replace the 3 original lines with the 1 selected modified line
- Future: we understand that the line count didn't change at all and we replace the 1 original line with the 1 selected modified line

**Comment by lainets** [comment]
Yes, that is a great change. Would it be possible to get a merging feature for when the number of lines is different? Right now, if I want to make a partial change to a block, I need to manually merge the old version and the new version (which is in the working file) to the state I want to stage in the working file, stage the changes, and then undo until I get back the new version I had earlier. While this works, it is a little annoying and terrifiying because there is a chance I might lose the new version.
