### ISSUE TITLE
Consider making editorInput copy async

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#126941]
@lramos15 @bpasero would it be possible to make `copy` return an optional `Promise`? This is needed to get the `terminal.integrated.splitCwd` setting working here since we only query the shell's current cwd when requested to avoid polling.

_Originally posted by @Tyriar in https://github.com/microsoft/vscode/pull/126850#discussion_r655745568_

**Comment by bpasero** [comment]
I think that is fine, I suggest a PR for Logan and me to look into.

**Comment by Tyriar** [comment]
This is more involved than I'm comfortable with in particular making `EditorGroupView.copyEditor`/`moveEditor` async. Instead of doing this I think we should wrap up the fix for this in the solution for https://github.com/microsoft/vscode/issues/129183 which would allow us to defer evaluating the cwd until when the input gets created which can then be async before creating the instance.
