### ISSUE TITLE
formatOnSave not working properly

### ISSUE THREAD

**Issue by youssefazriouil** [microsoft/vscode#126969]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.57.1
- OS Version: MacOS Big Sur 11.3.1

Since I updated my VSCode this morning my VSCode is not properly formatting on save, it seems to ignore my prettierrc. Which is really annoying because I have to wait for the pipeline to break to notice that there is some linting issue. What can I do?

**Comment by xqacmer** [comment]
l have the same problem. When l just update my vscode,l can't formatOnSave , l also can't code completion when l code C++. l want to know what can l do?

**Comment by clieee** [comment]
Same for me, prettier stopped working in latest version. Tried to check "Default formatter" but seems to be correct.

**Comment by jrieken** [comment]
> Same for me, prettier stopped working in latest version.

Maybe this is a problem with prettier?

**Comment by CrimpCity** [comment]
Double check that VS code is using the correct python interpreter. 

For some reason after the latest VS code update my python interpreter was downgraded to python 2.7 which caused me numerous issues since my environment is really set up for python 3.7. Once I fixed this format on save functionality was restored (along with resolving many of my other issues).

**Comment by daniel-seitz** [comment]
I see 2 issues here which might be related:
settings:

    "editor.formatOnSave": true,
    "[typescript]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
      },
    "html.format.wrapAttributes": "force-expand-multiline",
    "html.format.wrapLineLength": 220,

As far as I understand, prettier is hence only used for ts files otherwise use the default.

**Issue 1:** On Save .html-files: The formatting behaves differently from before the update. Maybe due to bugfixes, i.e. formatting of tag attributes now complies to the setting: "html.format.wrapAttributes" before it didn't in my project.
Also all tags now get a new line... why? did something change in the default "html.format.extraLiners" (a setting that we dont use)?

**Issue 2:** On Save .ts-files I get the message "Extension 'Prettier - Code formatter' - cannot format ..." before this worked. Should not be an issue with Prettier because this worked before.

**Comment by codetent** [comment]
I have the same problem with Python. After updating to the latest version, auto formatting does not work anymore with the settings that worked before.

It seems to execute the formatter executable correctly, at least it works when executing it manually, but the output is not leading to any change to the source code.

**Comment by jrieken** [comment]
Can everyone in this issue make sure that they operate inside a "trusted workspace". Iff untrusted extensions will be disabled and symptom of that will be features like "format on save" or IntelliSense not working anymore. 

Read me here: https://code.visualstudio.com/docs/editor/workspace-trust or try with this setting `"security.workspace.trust.enabled": false`

**Comment by daniel-seitz** [comment]
Hi @jrieken thank you.

I tried and it was set to true initially, when setting to false VS Code prompted for a restart and it seems to work now, even if I set it to true again. Looks like the additional restart might have fixed my 'not working'-issue (Issues 2 and 3 that I mentioned above) *grrrr... I'm going to monitor this for a while.

Issue 1 formatting html still behaves differently than before.
