### ISSUE TITLE
Remove custom allSettled-utils

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#126992]
Looks like all browsers that we care about support `allSettled`:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/allSettled#browser_compatibility

We should use that instead of our custom solution

**Comment by bpasero** [comment]
The thing I pushed is to remove our shim but:
* `lib.d.ts` does not provide types for `allSettled` so I keep my thing to forward with right types
* `Promise.settled` is actually used most and is a better replacement for `Promise.all`

**Comment by jrieken** [comment]
> lib.d.ts does not provide types for allSettled so I keep my thing to forward with right types

This is a matter of compiler options.

**Comment by bpasero** [comment]
Maybe @mjbvz knows how to add the types and then I can remove my types.

**Comment by jrieken** [comment]
I think that's just `es2020.promise`. I'll give it a try

**Comment by jrieken** [comment]
> I think that's just es2020.promise. I'll give it a try

Yeah, that was it. @bpasero can you also spell out what the different between  `Promises.settled` and `Promise.allSettled` is?

**Comment by bpasero** [comment]
@jrieken thanks, this allows me to remove my types.

`Promise.allSettled` has quite a complicated return type that you need to check on for an error, e.g. from MDN it can look like this:

```
[
   {status: "fulfilled", value: 33},
   {status: "fulfilled", value: 66},
   {status: "fulfilled", value: 99},
   {status: "rejected",  reason: Error: an error}
 ]
```

But in most cases we want the `Promise.all` behaviour that throws on the first error but otherwise just returns the values as array.

The main difference between `Promise.all` and `Promises.settled` is that our implementation waits for all promises to finish before returning, while `Promise.all` will return upon first error that happens leaving all other running promises in limbo.

I think with `Promise.all` you can easily shoot yourself into the foot if you believe that all promises have finished, when they actually might have not.

**Comment by jrieken** [comment]
I see, so settled is kind like this 

```
Promise.allSettled([Promise.resolve(1), Promise.reject(2)]).then(value => {
		const good: any[] = [];
		for (let result of value) {
			if (result.status === 'rejected') {
				return Promise.reject(result.reason);
			}
			good.push(result.value);
		}
		return good;
	});
```

**Comment by bpasero** [comment]
Yeah though since all the old usages were using `Promise.all` I didn't want to use `Promise.allSettled` since I wasn't sure if this changes any runtime behaviour. So I ended up implementing the same thing via `Promise.all`:

https://github.com/microsoft/vscode/blob/eef4c4c07104a6917d722a9519df96cca6aad83f/src/vs/base/common/async.ts#L1272-L1286
