### ISSUE TITLE
Support brace highlight in template strings

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#127005]
Would be cool to have brace highlighting in template strings  `text${var}text`

**Comment by mjbvz** [comment]
@alexdima Adding you since I believe bracket matching is disabled in strings. Let me know if there's a way to re-enable it in specific strings

**Comment by dbaeumer** [comment]
We discussed that also in the VS LSP meeting and there we tended to support an `in` / `notIn` property for braces to specify if highlighting should also work in strings and comments.

**Comment by alexdima** [comment]
@mjbvz Currently, `${` is considered to be of standard token type string by the editor. This is because the textmate scopes generated by the TS grammar contains `string.template.ts`. IMHO this is slightly incorrect, as `${` is a template expression start token, not really part of the string.

> ![image](https://user-images.githubusercontent.com/5047891/123958149-00261f00-d9ad-11eb-96d2-feb1af71db2e.png)

After tweaking the following:

```patch
diff --git a/extensions/typescript-basics/package.json b/extensions/typescript-basics/package.json
index 65a5326dae6..5acafadbdf9 100644
--- a/extensions/typescript-basics/package.json
+++ b/extensions/typescript-basics/package.json
@@ -57,6 +57,7 @@
         "scopeName": "source.ts",
         "path": "./syntaxes/TypeScript.tmLanguage.json",
         "tokenTypes": {
+          "meta.template.expression.ts": "other",
           "entity.name.type.instance.jsdoc": "other",
           "entity.name.function.tagged-template": "other",
           "meta.import string.quoted": "other",
```

I get bracket matching for these template expression begin tokens:

![image](https://user-images.githubusercontent.com/5047891/123959099-141e5080-d9ae-11eb-898c-62907ac8960e.png)

But I would leave it up to you @mjbvz to do that change or not.
