### ISSUE TITLE
Color codes in git extension pane and `COMMIT_EDITMSG` tab do not match together

### ISSUE THREAD

**Issue by LinqLover** [microsoft/vscode#127021]
- VS Code Version: 1.57.1
- OS Version: Win 20H1

Consider this:

![image](https://user-images.githubusercontent.com/38782922/123161810-2826f700-d470-11eb-974b-5e2e7c9b0e83.png)

- On the left, you can see the usual git commit pane after modifying and moving a few files.
- On the right, you can see the result of `git config core.editor "code --wait" && git commit`

Unfortunately, the colors don't match together. I have no idea who would be to blame for this, but it would be nice if this could be unified, i.e., in the `COMMIT_EDITMSG` tab, renamed files should appear in the same green color as in the git pane.

**Comment by lszomoru** [comment]
@misolori, do you have context of the theme colours that are used here?

**Comment by d-mahard** [comment]
The right and the left are different because they are controlled by two different settings.
For the text on the right, it is controlled by syntax coloring in the following scope (see the `markup.inserted`. The other are for deleted and modified, respectively):

```json
                {
			"scope": "markup.inserted",
			"settings": {
				"foreground": "#7BD88F"
			}
		},
		{
			"scope": "markup.deleted",
			"settings": {
				"foreground": "#FC618D"
			}
		},
		{
			"scope": "markup.changed",
			"settings": {
				"foreground": "#FCE566"
			}
		},
```

while the text on the side bar is controlled by workbench color 

```json
                "gitDecoration.addedResourceForeground": "#81b88b",
		"gitDecoration.deletedResourceForeground": "#c74e39",
		"gitDecoration.modifiedResourceForeground": "#e2c08d",
```

And the settings are separated for a good reason. The background of side bar and editor can be different like the one below, therefore to achieve good contrast (or aesthetic) for both, the foreground decorator should allow different value as well.

![image](https://github.com/microsoft/vscode/assets/146386738/50e5ef0e-6fad-4ed4-ad8b-fab981a58813)

If you want them to be the same, you can add the setting, such as the following:

```json
 "workbench.colorCustomizations": {
        "gitDecoration.addedResourceForeground": "#00840b", 
  },
"editor.tokenColorCustomizations":

{"textMateRules": [
     {
        "scope": "markup.inserted",
        "settings": {
            "foreground": "#00840b"
        }
    }
]},
```

_(disclaimer: I am not part of Microsoft, I just maintain a theme of my own, so I learned along the way about the above stuff...)_
