### ISSUE TITLE
javacript code formatting not working after typescript v2.x update

### ISSUE THREAD

**Issue by mlakmal** [Microsoft/vscode#12705]
- VSCode Version: 1.6.0 insider
- OS Version: Windows 7 64

Steps to Reproduce:

1. update to latest VS Code insider v1.6.0 and update typescript to v2.0.x
2. format the javascript code with below workspace settings.
	"editor.tabSize": 2,
	"javascript.format.insertSpaceAfterKeywordsInControlFlowStatements": true,
	"javascript.format.insertSpaceAfterFunctionKeywordForAnonymousFunctions": true,
	"javascript.format.insertSpaceAfterOpeningAndBeforeClosingNonemptyParenthesis": false,
	"javascript.format.insertSpaceAfterOpeningAndBeforeClosingNonemptyBrackets": false,
3. above formatting settings are not adhered after typescript v2.0x update

tabsize is 4 and not using above override and spaces are not getting added after function keyword and parenthesis/brackets.

**Comment by dbaeumer** [comment]
@mlakmal there is a real issue here that the formatter also told otherwise replaces tabs with spaces. 

Regarding the tabSize: the file is always formatted using the tab size detected by the editor and shown in the status line. So if the status line says Tab Size: 4 in the lower right corner then we use tabSize: 4 during formatting even with the setting "editor.tabSize": 2.

I will follow up in the TS bug https://github.com/Microsoft/TypeScript/issues/11199 since the fix for this has to come from the TS team.

Keeping the issue open to make sure we have a fix for this for September.

**Comment by dbaeumer** [comment]
Got fixed for the next update:

![cast](https://cloud.githubusercontent.com/assets/1931590/18912409/879835a6-8582-11e6-9026-be6e80f9bda0.gif)

**Comment by mlakmal** [comment]
Thanks @dbaeumer.

**Comment by dbaeumer** [comment]
Closing.

**Comment by IgorNovozhilov** [comment]
Repeats for html, the spaces are replaced with tabs, regardless of the settings.

**Comment by dbaeumer** [comment]
@IgorNovozhilov can you please open a separate issue describing the problem you have with HTML. This was about TS and replacing tabs with spaces :-)
