### ISSUE TITLE
Error while trying to install an extension: TypeError: Parameter "url" must be a string, not undefined

### ISSUE THREAD

**Issue by brettcannon** [microsoft/vscode#127022]
### Discussed in https://github.com/microsoft/vscode-python/discussions/16513

Originally posted by @gellettc.

Details are in the discussion, but the key issue seems to be:
```
messageService.ts:128Parameter "url" must be a string, not undefined: TypeError: Parameter "url" must be a string, not undefined
```

**Comment by sandy081** [comment]
@gellettc Can you please let us know the version of VS Code you are using?

Also provide us following logs while you are reproducing the issue

Please follow these steps

    - Help -> Toggle Developer Tools -> Console
    - View -> Command Pallette... -> Toggle Shared Process -> Console
    - View -> Open View… -> Log (Shared)
    - View -> Open View… -> Log (Window)

**Comment by gellettc** [comment]
HI Sandy, 

I am using Virtual studio code version 1.7.2 

I was able to do the first of your instructions, (the help line). However, unfortunately i could do any of the other 3 commands because i dont have Toggle Shared Process or  Open view as options when following the steps.

Perhaps i am using an old version of VS code?


![Picture12](https://user-images.githubusercontent.com/86071992/123339289-35acb180-d542-11eb-91d3-38e9b7513eb7.png)

**Comment by sandy081** [comment]
1.7.2 is pretty old.

Can you please update your VS Code and see if you can still reproduce it
