### ISSUE TITLE
Use const enums for terminal context keys

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#127157]
Similar to how settings/commands work for the terminal, this would prevent typos from breaking things

**Comment by Tyriar** [comment]
Let's use the const enums here and also include all of them:

https://github.com/microsoft/vscode/blob/a446cd5ecd009cdb265cdcb3f2c9304dd518263b/src/vs/workbench/contrib/terminal/common/terminal.ts#L19-L70

These should also live in contrib/terminal/common not platform since context keys aren't needed that low.
