### ISSUE TITLE
Difficulty Reading Error Message Text in New Notebook Output Rendering

### ISSUE THREAD

**Issue by mtsitzer** [microsoft/vscode#127110]
The rendering of error messages when running code cells is difficult to read (using new Jupyter Notebook extension update) than it used to be.

Note that I am using VSCode default Light Theme (Light+).

Interactive Python:
![image](https://user-images.githubusercontent.com/28517224/122485510-f8698200-cf8b-11eb-9648-dbf99acedbc4.png)

Notebook:
![image](https://user-images.githubusercontent.com/28517224/122485532-06b79e00-cf8c-11eb-9526-0d7a571a05e7.png)

Is there currently a way to make this a bit easier on the eyes? (the green is not great in either the interactive view or the notebook, but in the notebook the green is unreadable). In addition, the yellow "+" is also very hard to see.

_Originally posted by @mtsitzer in https://github.com/microsoft/vscode-jupyter/issues/6045#issuecomment-863631721_

**Comment by rebornix** [comment]
@misolori didn't we remove the default background color for the outputs?

**Comment by misolori** [comment]
Yes, we no longer show the output background color by default.

**Comment by misolori** [comment]
This is no longer an issue since we added a background color to code cells (see https://github.com/microsoft/vscode/issues/128885#issuecomment-882897697). This should be out in the July release.

<img width="683" alt="CleanShot 2021-07-27 at 09 21 47@2x" src="https://user-images.githubusercontent.com/35271042/127190906-f3806b45-97e5-49a3-94f4-2d3a7e8a188a.png">
