### ISSUE TITLE
XHR Failed

### ISSUE THREAD

**Issue by ElBlasco69** [microsoft/vscode#127214]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:- VS Code Version: Version: 1.57.1 (user setup)
                                Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
                                Date: 2021-06-17T13:28:07.755Z
                                Electron: 12.0.7
                                Chrome: 89.0.4389.128
                                Node.js: 14.16.0
                                V8: 8.9.255.25-electron.0
                                OS: Windows_NT x64 10.0.19043
- OS Version: Windows 10 Home version 21H1

Steps to Reproduce:
I cannot dowload and open any extension from marketplace. I'm not under any proxy and my dns are 1.1.1.1 and 8.8.8.8. VsCode gives me XHR Failed
![Immagine 2021-06-26 092341](https://user-images.githubusercontent.com/64553614/123505642-903c2f80-d660-11eb-8344-4394cf464b87.png)

**Comment by ElBlasco69** [comment]
![Immagine 2021-06-28 173019](https://user-images.githubusercontent.com/64553614/123663286-8835e880-d836-11eb-9900-5789ef5a6aab.png)

**Comment by ElBlasco69** [comment]
![Immagine 2021-06-28 173707](https://user-images.githubusercontent.com/64553614/123664270-7a349780-d837-11eb-8713-360610910728.png)

**Comment by sandy081** [comment]
It seems you have network issues, not sure if it is VS Code related or not.

**Comment by ElBlasco69** [comment]
I do not think is related to my network because i use vs code in the same computer under ubuntu and it works perfectly.

**Comment by traxx10** [comment]
Same issue here

**Comment by deepak1556** [comment]
Can you follow the steps below and attach the `netlog.json` file,

* launch vscode with `code --log-net-log=<some-absolute-path>/netlog.json`
* Perform the steps that create the xhr timeout issue
* Quit the application

Also can you clarify if you are running vscode as administrator ?

**Comment by ElBlasco69** [comment]
I have to converto from .json to .txt because github does't support .json.
Yes I'm running code as administrator
[netlog.txt](https://github.com/microsoft/vscode/files/6799635/netlog.txt)

**Comment by deepak1556** [comment]
Thanks for log, can you try running with `code --no-sandbox` or not run as administrator and see if the issue happens.

**Comment by ElBlasco69** [comment]
Yes, the issue still remains

**Comment by MileanCo** [comment]
I also hit this issue. My VM doesnt have internet access, and so it will never be able to do this XMLHttpRequest. Earlier version of ms-python worked and didnt need internet access, such as ms-python.python-2021.3.658691958

**Comment by MileanCo** [comment]
I was able to get past this error with the following versions. Its very difficult to figure out manually which versions are compatible without spending 2 hours Googline and guessing and trying. This workflow should be easier :)

1. Install
   jupyter-2021.8.1195043623.vsix - https://www.vsixhub.com/vsix/67262/ 
2. Install ms-python v2021.4.765268190

This is for vscode-1.59.1

**Comment by IAOldman** [comment]
I am trying to offline install a plugin in VS Code. During installation, the error "XHR failed" occurs. Internet access is limited, so there is no need to talk about network settings.

What have you tried?

Copied the .vsix file to C:\Users\User_tst\AppData\Local\Programs\Microsoft VS Code\bin, then on the command line: `code --install-extension ms-python.python-2021.8.1159798656.vsix`

The output was the following:

`C:\Users\User_tst\AppData\Local\Programs\Microsoft VS Code\bin>code --install-extension ms-python.python-2021.8.1159798656.vsix
Installing extensions...
(node:10564) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code --trace-deprecation ...` to show where the warning was created)
getaddrinfo ENOTFOUND marketplace.visualstudio.com
Failed Installing Extensions: file:///c%3A/Users/User_tst/AppData/Local/Programs/Microsoft%20VS%20Code/bin/ms-python.python-2021.8.1159798656.vsix
(node:10564) UnhandledPromiseRejectionWarning: Canceled: Canceled
    at D (C:\Users\User_tst\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:5:1157)
    at C:\Users\User_tst\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:9:60398
    at U.fire (C:\Users\User_tst\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:8:1712)
    at F.cancel (C:\Users\User_tst\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:8:5928)
    at R.cancel (C:\Users\User_tst\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:8:6469)
    at Object.cancel (C:\Users\User_tst\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:9:60531)
    at ie.cancel (C:\Users\User_tst\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\cliProcessMain.js:15:25392)
    at C:\Users\User_tst\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\cliProcessMain.js:15:16154
    at Array.forEach (<anonymous>)
    at x.installExtension (C:\Users\User_tst\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\cliProcessMain.js:15:16132)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async b.installVSIX (C:\Users\User_tst\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\cliProcessMain.js:10:260)
    at async C:\Users\User_tst\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\cliProcessMain.js:9:10268
    at async Promise.all (index 0)
    at async b.installExtensions (C:\Users\User_tst\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\cliProcessMain.js:9:10222)
    at async C:\Users\User_tst\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\cliProcessMain.js:17:35192
    at async Object.M [as main] (C:\Users\User_tst\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\cliProcessMain.js:17:38625)
    at async N (C:\Users\User_tst\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:12:13842)
(node:10564) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)`

Can you please tell me if there are any other installation methods?

**Comment by deepak1556** [comment]
Does the issue persist with latest stable `1.73` ?

**Comment by ElBlasco69** [comment]
I don't have the access to that machine anymore, sorry.

**Comment by deepak1556** [comment]
Thanks for confirming.
