### ISSUE TITLE
Info message about `typescript.tsdk` is a bit too much

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#12721]
I see the current conundrum about TS 2.0, but the current product state shows a bit too much of info popups and notifications.

I understand the need for showing a popup asking the user to choose between the workspace and the shipped version of TypeScript, if different.

But the following preemptive one is too much in your face. Users that already use TypeScript very likely already have it in their `node_modules`, and will get the aforementioned popup. And brand new VS Code users will be greeted with this popup on their first TypeScript experience.

![image](https://cloud.githubusercontent.com/assets/22350/18864734/eb16df92-8497-11e6-80d0-3e0c7ca23769.png)

**Comment by dbaeumer** [comment]
Just for clarification: you should not see that message if you have a tsdk setting. Then I will not inform you. The message is only presented if you used 1.8.10 in the box with 1.5.x and now get 2.0.3 in the box with 1.6. However I am open to fold the message in the Release notes message since the More Information button takes you to the release notes as well.

**Comment by dbaeumer** [comment]
@egamma any take on this. Should we try to fold this into the initial release notes message. Would make sense IMO.

**Comment by egamma** [comment]
@dbaeumer I agree let's fold this message into the release notes.

**Comment by dbaeumer** [comment]
OK. Will work with @joaomoreno tomorrow to fold that together.

**Comment by dbaeumer** [comment]
OK. To not make the message for the release notes any longer @egamma and I decided to simply remove the version check.
