### ISSUE TITLE
Create a discord server

### ISSUE THREAD

**Issue by Milo123459** [microsoft/vscode#127371]
Gitter is a bit chaotic, and I personally think creating a Discord server instead of using Gitter would be beneficial. You could spread it out into different channels, for example `extension-development`, `help`, `development` etc. Also, lots of communities are moving from Gitter to Discord, so I think VSCode should as well.

**Comment by backermanbd** [comment]
I also support @Milo123459 
discord will be the better choice than Gitter

**Comment by Milo123459** [comment]
@zareami10 May I ask why you think there shouldn't be a discord server? Is there something you like about Gitter? I asked a question about a month ago and still haven't gotten a response.

**Comment by zareami10** [comment]
> @zareami10 May I ask why you think there shouldn't be a discord server? Is there something you like about Gitter? I asked a question about a month ago and still haven't gotten a response.

Well I personally don't think projects should change their communication platforms that easily unless there is a very strong reasoning, because then we would have to change platforms every other week.

But besides that Gitter is moving to Matrix, an open standard protocol with a much better future. Thus I would never understand any moves towards a closed and proprietary platform such as Discord.

**Comment by Milo123459** [comment]
Okay. Maybe a way of linking Matrix & Discord? A matrix bridge?

**Comment by byehack** [comment]
Telegram also can be good choice.

**Comment by Milo123459** [comment]
Issue's dead, and I doubt it's happening. There will probably be a community one
