### ISSUE TITLE
Similar Workspace Trust commands

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#127303]
![image](https://user-images.githubusercontent.com/22350/123617133-39bd2580-d807-11eb-98fb-edb5aa0c41c2.png)

After running both commands, I understand why we need them both, but we probably call them a bit more differently so we understand what each is about. Also, we could probably drop the `Configure` one from Command Palette, since you can easily get there from the `Manage` one.

**Comment by sbatten** [comment]
Well if we drop it from the command palette, I think the name is not important since it doesn't show anywhere else besides keybindings and I doubt that's a common keybind. 

But I do see value in the command palette since we are trying to enhance discovery of the settings for advanced users and an extra entry point doesn't hurt usually if its a command.

I could see `Show Workspace Trust Settings` to be very explicit

**Comment by isidorn** [comment]
I filled exactly the same issue https://github.com/microsoft/vscode/issues/127618

**Comment by sbatten** [comment]
We use "settings" at the end to highlight that it goes to the settings editor
