### ISSUE TITLE
startEntries `category` isn't required

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#127403]
Testing #127383

The only required properties for an item in `startEntries` are `title` and `command`. However, if I leave out a category I can't find my entry anywhere. Should `category` be a required property? If not, can some description be added so that I can understand what leaving the `category` undefined actually does?

**Comment by gjsjohnmurray** [comment]
Seems that a `startEntries` without a `category` appears in the quickpick of the `Welcome: New...` command from the palette.

![image](https://user-images.githubusercontent.com/6726799/123880215-16df5e00-d93a-11eb-9e1d-49775bc3d672.png)

@tanhakabir maybe REST Book should set `"category": "notebook"` rather than omitting it:

https://github.com/tanhakabir/rest-book/blob/d4c2ee4eca74b89d3867a27ed9e657f7b8ecc2b3/package.json#L37-L42

Doing that might make it appear in a quickpick from this Welcome page link:

![image](https://user-images.githubusercontent.com/6726799/123880661-0a0f3a00-d93b-11eb-8f5c-4c2e79768974.png)

@JacksonKearl my first screenshot also shows the entries not being grouped by category.

**Comment by JacksonKearl** [comment]
@tanhakabir yes sorry the `category` field did not yet exist when you adopted this, but it should be set to `notebook` now.

**Comment by JacksonKearl** [comment]
> @JacksonKearl my first screenshot also shows the entries not being grouped by category.

Are you referring to how the `Folder` contributions are not all in one place? I agree, it should be sorted by category.
