### ISSUE TITLE
Mismatch between setting and menu entry

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#127489]
Testing #127331

Change test resolver code to

```
		return {
			localAddress,
			remoteAddress: tunnelOptions.remoteAddress,
			public: !!vscode.workspace.getConfiguration('testresolver').get('supportPublicPorts') && tunnelOptions.public,
			protocol: 'https',
			onDidDispose: onDidDispose.event,
			dispose: () => {
				if (!isDisposed) {
					isDisposed = true;
					onDidDispose.fire();
				}
			}
		};

```

And then  played with the setting and the menu entry. Got into a state where both didn't allign

<img width="534" alt="capture" src="https://user-images.githubusercontent.com/1931590/123817575-92202000-d8f8-11eb-8c0a-e4d1b35c68db.png">

**Comment by alexr00** [comment]
This is by design (and something I wanted to make sure was tested, so thank you!). Since the tunnel is returned from the resolver with `https`, we reflect that in the UI even if the setting says otherwise. The setting is telling VS Code + the resolver what the protocol should be, but the resolver is ignoring that by returning with `https`.
