### ISSUE TITLE
Getting started: see more opens a quick pick with duplicated entries

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#127428]
Clicking on the See More opens the quick pick, which is a very strange experience since there are duplicates from what is already displayed, everything should be inlined and clicking on the See More should just open more boxes below the button. If we plan to have just one more option I think it should just be there, and not have a see more at all. But I guess we might introduce more things...

Bonus bug: do not call these castion "See More", some users do not "see"  so it might not be a good choice. I would instead name it "More..."

![Screenshot 2021-06-29 at 13 04 31](https://user-images.githubusercontent.com/1926584/123786969-976e7200-d8da-11eb-95f2-1dee0b41af2b.png)

**Comment by JacksonKearl** [comment]
Updated wording to "Show All", because you are correct that all we can do is show the items, we have no control over whether the user sees them. 

Also using "All" does not imply that the items will not be duplicated (as "More" might), as I do want to keep using the quick pick to both be consistant with what happens when there's no items at all showing (link at bottom of page to open the same quick pick), and the `Welcome: Open Getting Started Page...` command, which also uses the same quick pick. Also quick pick provides some nice filtering capabilities.
