### ISSUE TITLE
Native Notebooks - Allow extensions to customize cell status tip 

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode#127555]
VS Code Stable + Insiders have the shortcut hint in the cell status bar set to Ctrl + Alt + Enter to run. For Jupyter the shortcut to run is Ctrl + Enter so it would be nice if we could update it. 

![image](https://user-images.githubusercontent.com/19276747/123859379-6c375300-d8d9-11eb-8557-b24f503bb327.png)

Related to: https://github.com/microsoft/vscode/issues/121558

**Comment by roblourens** [comment]
Works for me: 
![image](https://user-images.githubusercontent.com/323878/124200430-2ff72480-da8a-11eb-8971-6cc49b843f0e.png)

What OS?

**Comment by claudiaregio** [comment]
I'm on windows

**Comment by roblourens** [comment]
The jupyter extension used to contribute a keybinding for this command, but it doesn't anymore: https://github.com/microsoft/vscode-jupyter/commit/f05fedf399d34684b408245ba27bc29aa25c13f6 cc @joyceerhl

**Comment by joyceerhl** [comment]
Good point. We contributed a keybinding to override the default ctrl+enter behavior and take the cell out of edit mode (discussed with @rebornix and we decided not to change it in core because some users actually like being able to run and tweak code without having to put the cell back into edit mode). This means the cell status tip no longer reflects the Jupyter keybinding.

We've had a number of discussions recently re: whether we can hide this cell status tip. Is that still on the table as an alternative resolution for this issue? Jupyter users know what keybinding to use to run cells (ctrl+enter), so for them the tooltip would be clutter.

**Comment by rebornix** [comment]
As @roblourens suggested before, we can remove it :)

**Comment by claudiaregio** [comment]
+1 the suggestion to remove it, didn't think it was an option 😆 Agree with Joyce that Jupyter users know their run shortcuts well

**Comment by roblourens** [comment]
I'm also not really convinced that registering a totally new command is the right solution for this. You'll see the different keybinding if you hover the run button, and in the command palette. Seems like you're relying on people to "just know" that ctrl+enter is what they want?
