### ISSUE TITLE
Extension viewlet doesn't refresh filter list on workspace trust action

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode#127513]
Testing #127352

Might just be a minor UI quibble here, but wanted to file this as it wasn't quite what I expected.

Steps:
1. Open untrusted workspace
2. From workspace trust editor, view the unsupported extensions (@workspaceUnsupported filter)
3. From the trust editor trust the workspace
4. In the viewlet the extensions are now enabled (correctly) but they are still visible in the workspaceUnsupported filter

Feels like an odd UI state here. The extensions are listed as enabled (correctly) but still showing in the "Disabled in Restricted Mode" section. I would have expected that trust action would do a refresh on the extension filters so that list would be empty after the trust action.

![image](https://user-images.githubusercontent.com/812783/123840909-cdecc280-d8c3-11eb-82ce-ca18f55f1981.png)

**Comment by sbatten** [comment]
@IanMatthewHuff we actually just switched back to this behavior after having that viewlet be empty when in a trusted workspace. The reason is that this filter is the landing point for the link in the trusted editor regardless of your trust state. So, if you click a link that says *16 extensions will be disabled in restricted mode*, the viewlet should show those extensions. The title of the views, *disabled in restricted mode* are intended to be the indicators that their enablement can change based on trust but doesn't mean they are disabled now.

**Comment by IanMatthewHuff** [comment]
@sbatten That's legit. My brain parsed that more as "Currently disabled due to restricted mode" I can see the meaning that you mention now though.
