### ISSUE TITLE
No bracket matching and auto indent in CSS (HTML, Handlebars)

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#12757]
Testing #12100

Have a style block with some CSS in either a HTML or Handlebars file. Notice that:
* bracket matching does not work
* auto indent does not work

Since this works in CSHTML, I wonder if this is something easy to configure?

Marking important because I think this is a very common thing to do for our users.

@alexandrudima fyi since @aeschli is out

**Comment by alexandrudima** [comment]
@bpasero I suggest tweaking the language configuration of HTML. Due to the migration to TextMate, the editor core is no longer aware that there is a mode switch occuring in HTML and will therefore consider everything as HTML, and will use the brackets defined in HTML:

![image](https://cloud.githubusercontent.com/assets/5047891/18886362/4152b15a-84f8-11e6-8f9d-6e06fcefb733.png)

**Comment by alexandrudima** [comment]
@jrieken I'm also gonna be out :)

**Comment by bpasero** [comment]
@alexandrudima thanks!

@aeschli I did was Alex suggest and add more brackets to the HTML and Handlebars config (https://github.com/Microsoft/vscode/commit/f6d0cc164585abc90a16ff698f2e9997648075f3)

I noticed another difference: Handlebars and Razor define surroundingPairs with `{ "open": "<", "close": ">" }` while HTML does not. Not sure what the impact is of that.
