### ISSUE TITLE
Adding new ports in the ports view does not update machine settings

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#127577]
Testing #127331

<img width="911" alt="CleanShot 2021-06-29 at 14 58 24@2x" src="https://user-images.githubusercontent.com/35271042/123872873-84639e00-d8ea-11eb-86c7-2dc406f42ef1.png">

Not sure if this is expected, so filling an issue just in case.

1. Set `protocol: 'http',`
2. Launch test resolver
3. Forward a port
4. :bug: See that port is not in machine settings

when i change the protocol to `https`, then it adds the port to the settings:

<img width="612" alt="CleanShot 2021-06-29 at 14 59 18@2x" src="https://user-images.githubusercontent.com/35271042/123872954-9a715e80-d8ea-11eb-836e-b77e7f4276f6.png">

**Comment by alexr00** [comment]
Hmm. Since the default is http, we don't add the setting for it as the port is unconfigured. I think this is consistent with how we handle all settings (i.e., we only set them if they are changed from default). We don't know that the resolver is going to behave badly (always return http, even when it shouldn't). Thanks for filing the issue to check, but I think this is ok!

Some additional info in case you're interested: Later, we may support resolvers providing additional protocols besides http and https. At that time, we'll also probably introduce a way for the resolver to indicate what the default protocol is.
