### ISSUE TITLE
Adding a way to change editor terminal color/icon

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#127502]
Testing #127192

I was thinking that the context menu from the terminal tab would have options to change the icon/color of the terminal since it is customizable in the panel. To change these, I need to move the terminal back to the panel first.
![image](https://user-images.githubusercontent.com/31675041/123832896-0f30a280-d8c3-11eb-825d-612cf2e32a9e.png)

**Comment by Tyriar** [comment]
I guess we could add those plus rename to mirror the normal tab context menu:

<img width="219" alt="Screen Shot 2021-06-29 at 9 19 28 AM" src="https://user-images.githubusercontent.com/2193314/123833337-1c499380-d8bb-11eb-9e16-d65c7c3d4574.png">

Since text files have several entries:

<img width="276" alt="Screen Shot 2021-06-29 at 9 19 40 AM" src="https://user-images.githubusercontent.com/2193314/123833386-22d80b00-d8bb-11eb-9beb-10da7739ab7a.png">
