### ISSUE TITLE
Test tree fails to expand items when tests are run too fast

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#127655]
Testing #127386

When I remove the random timeouts from the testing sample extension, the test tree fails to expand the test runs when I run them all with `Run All Tests`. This doesn't happen when the timeout is there.

![image](https://user-images.githubusercontent.com/22350/123981361-1fa25500-d977-11eb-9df2-261339891ed9.png)

**Comment by connor4312** [comment]
The expansion is as a side effect of the "follow running test" setting. We throttle changes to the test tree for performance, so if everything is run instantaneously then there'll be no running test to follow.

I'm not sure whether the "expand on run" is something that we should intentionally add otherwise, thoughts?

**Comment by joaomoreno** [comment]
I see! The explanation makes sense, I doubt this would cause an issue in the real world. Feel free to close it.

**Comment by connor4312** [comment]
Ok. We can reopen it depending on what users think in the real world.
