### ISSUE TITLE
For keymaps, "editor" should mean "editor-like environments"

### ISSUE THREAD

**Issue by tigerhawkvok** [microsoft/vscode#127606]
The easiest way to understand this is to think of the debug console. It code completes like the editor, uses the same syntax highlighter, etc, yet bafflingly the keymaps are different.

I use emacs keymaps, for example. Want to escape out of a suggestion? Well, my reflexive `Ctrl+g` isn't going to do it. Hop to the beginning or end of a line? `Ctrl+a` or `Ctrl+e` won't work, and I certainly can't kill a line with `Ctrl+k`.

Even if this isn't OK by default, having it as a boolean setting would be fine. 

Alternatively, a string setting for basically, 

- "editor" means "editor" you fool
- "any place that I get syntax highlighting"
- "any place with a navigatable insert point"
- "any text entry at all"

What's _not_ an acceptable replacement is going through and editing every keymap every time I add or change an extension to add all the locations logic in.

**Comment by alexdima** [comment]
> The easiest way to understand this is to think of the debug console. It code completes like the editor, uses the same syntax highlighter, etc, yet bafflingly the keymaps are different.

Regarding default keybindings: this is intentional and has to do with explicit feedback we've received from vim users. vim users do not want vim keybindings in the debug console or other places where an editor is used as an implementation detail (e.g. SCM input). So they need to be able to target them differently in keybindings.

So there are two context keys: `textInputFocus` and `editorTextFocus`. `textInputFocus` holds true for both editors and simple inputs built using the editor, while `editorTextFocus` holds true only for editors where source code would be loaded from disk.

I think you should reach out to the emacs keymap extension and make the case that they should use `textInputFocus` instead of `editorTextFocus`.
