### ISSUE TITLE
Remote: save workspace as opens a local dialog

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#127647]
Version: 1.58.0-insider (user setup)
Commit: 57930758db9e2c83f59b9ee1851400bd16192d32
Date: 2021-06-30T05:14:00.370Z

- open a new WSL window
- run `Save as Workspace..` command
- a local save file dialog opens.  Should be remote file save dialog (with a `local` option)

**Comment by gjsjohnmurray** [comment]
Related to #126476? Personally I am pleased that `File\Save Workspace As...` no longer brings up that remote file save dialog for workspaces whose root(s) have uri(s) that use the scheme implemented by my FileSystemProvider extension. For us it makes no sense for a user to save such a workspace remotely because until they open the workspace there's no way of accessing the correct remote filesystem.

But though the https://github.com/microsoft/vscode/commit/3802161550e23b64b607666bbcd5bf27610759c0 change @alexr00 has made me happy it's still the case that when I use `File\Open Workspace...` when I already have a workspace open that uses my FSP's scheme, the remote file open dialog opens. And if my remote is now unavailable this dialog hangs for a long time before allowing me to "Show Local".

**Comment by aeschli** [comment]
We need to distinguish between virtual workspace and remote windows.
For virtual workspace, the fix made sense. But for remote windows, having a workspace on the remote side is useful, e.g. when you work on remote-ssh.
