### ISSUE TITLE
Debug hover is very small (vertically)

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#127669]
Testing https://github.com/microsoft/vscode/issues/127362

To be honest, I believe this is a VS Code core issue, but the TPI asks to create all issues here 🤷‍♂️ .

Notice how much space I have, but the debug hover renders very small (with only 2-3 lines fitting)

https://user-images.githubusercontent.com/5047891/123930642-3bfebb80-d990-11eb-8f5d-8eee6a5957b6.mp4

**Comment by roblourens** [comment]
What determines the size of this @isidorn?

**Comment by isidorn** [comment]
@roblourens the size of the debug hover is determined by the editor size. And because of the small notebook editor the hover is even smaller.
https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/debug/browser/debugHover.ts#L314

I will introduce some minimum size for it so this case is also covered.
