### ISSUE TITLE
"Screencast mode" should survive window reloads

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#127610]
When trying to make a screencast of an [issue involving typing across a window reload](https://github.com/microsoft/vscode/issues/127527#issuecomment-871179000), I noticed that "Screencast mode" doesn't survive a window reload.

**Comment by joaomoreno** [comment]
Hm... tricky since it shouldn't survive an app restart, so we shouldn't store that enablement state.

**Comment by charles-allen** [comment]
This has caught me out pretty much every class since I discovered the feature!

Why can't it survive app restart? Put it in settings. Then I can set a default in my user settings and override it in my workspace settings (either disable in each non-teaching project, or enable in each teaching project, depending on which I decide to be the default).

**Comment by weinand** [comment]
@joaomoreno why exactly shouldn't Screencast mode survive an app restart?

**Comment by joaomoreno** [comment]
Great question! Should it? 😆

**Comment by weinand** [comment]
of course not ;-)

**Comment by charles-allen** [comment]
I think it should follow a setting like everything else in VSCode. If I want to disable it, I can toggle again. Like most things, if you toggle a lot you will learn the shortcut.

I see 2 main use cases:
- temporary toggle for a meeting => toggle again & continue coding seems more intuitive than closing & reopening
- always on for teaching/training/videos => set it in workspace settings
