### ISSUE TITLE
Visual Studio Code shows file modified when it's not

### ISSUE THREAD

**Issue by BarishSarac** [microsoft/vscode#127706]
Does this issue occur when all extensions are disabled?: Yes/No
Yes

VS Code Version:
Version: 1.57.1 (user setup)
Commit: 507ce72
Date: 2021-06-17T13:28:07.755Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19043
Steps to Reproduce:
This time, I opened folder "b" which has about 13 repos. I run the prettier --write . command, to format all files in all repos here. Now some files formatted and changed so I see the update. Some files are not updated though, and those are still listed and when I click to see different left and right is identical.

Also some other times I have a folder called reports. There are about 40 or so reports. Let's say we update 3 reports out of all of them. If I copy from source where I updated 3 and update all 40 in the repo, visual code registers as all 40 has been updated, but in fact 3 have been updated only.

![image](https://user-images.githubusercontent.com/2792881/124025246-d3c2d080-d9b5-11eb-8755-ccdcdfe02635.png)

**Comment by epreston** [comment]
Line ending normalisation ?

**Comment by joaomoreno** [comment]
The file probably has whitespace differences.

**Comment by BarishSarac** [comment]
I also created this, https://stackoverflow.com/questions/68163991/visual-studio-code-shows-file-modified-when-its-not

Tried all this
```
git config core.filemode false  
git config --global core.filemode false
git config --global core.autocrlf false
```

Still same, How can I prevent?

**Comment by epreston** [comment]
You say you are using prettier to format the files: I would look there.  It may trim trailing whitespace.  It may add trailing newlines at the end of the file as required by git.  Without a proper diff or screen shot of a diff I can only guess.

I use an .editorconfig file with entries like the one below to protect files where trailing whitespace is part of the syntax.  
```
[*.md]
trim_trailing_whitespace = false
```
I think prettier respects editorconfigs (like most tools) and vscode can be made to with a plugin.  Since you are formatting many repositories at once, I am not sure which files would apply and when.

Next I would look at your vscode settings.  Here is a partial `settings.json` which serves the same purpose as the example above.  Just about each setting has an equivalent in the interface.  Look up each setting or search the "command palette" to find them quickly.

```json
// Place your settings in this file to overwrite default and user settings.
{
  "files.trimTrailingWhitespace": true,
  "files.insertFinalNewline": true,
  "[plaintext]": {
    "files.insertFinalNewline": false
  },
  "[markdown]": {
    "files.trimTrailingWhitespace": false
  }
}
```

These vscode settings in particular are important for me to avoid unexpected issues like the one your having.

Lastly, check your .gitattributes files in the root of each repository.  They will override your global git settings on a per project basis.  Important entries for me are:

```.gitignore
# Auto detect text files and perform LF normalization
* text=auto

# Special files
LICENSE.txt eol=crlf

# Reasonable Defaults
*.bat eol=crlf
*.cmd eol=crlf
*.ps1 eol=lf
*.sh eol=lf
*.rtf -text
```

You may be able to side step these issues by instructing git on how you want things handled.  Personally, I have similar issues with PDF files in my repos from different platforms.  This creates a few problems in git itself (where files are marked modified but changes can't be discarded.)

**Comment by lramos15** [comment]
Closing this as there hasn't been many reports of this or any updates in awhile
