### ISSUE TITLE
Step over and Step in are quite slow

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#127720]
Testing https://github.com/microsoft/vscode/issues/127362
1. Start debugging jupyter notebook
2. Step over a variable definition
3. 🐛 The entire watch variables flashes and it takes a solid second before the next line is hit

**Comment by roblourens** [comment]
Hey @isidorn, I have this code to update some notebook metadata based on the current debug state, but it slows things down by generating too many callstack requests, and I don't know how to do this the right way

https://github.com/microsoft/vscode/blob/0a3b4bd9134f434a1cc262dc8a60c383d14a0b18/src/vs/workbench/contrib/notebook/browser/contrib/breakpoints/notebookBreakpoints.ts#L115

I think one problem is that we might call `fetchCallStack` when a request has already been sent by CallStackView. If a request is already in flight, I want to wait on that request instead of triggering a new one. 

And I have to call fetch, because otherwise the callstack is empty when the `onDidChangeCallStack`  is fired. If I don't call fetch, then I get the event 3 times for each step with an empty callstack. But I think this generates a lot of load. I guess it is faster in the callstack because it debounces updates and requests just one frame first?

![image](https://user-images.githubusercontent.com/323878/124044804-13dc8000-d9c3-11eb-9dee-8d12006ab09e.png)

(There are 4 frames)

So it's not clear to me how to do this efficiently.

**Comment by isidorn** [comment]
@roblourens so you just want to be called every time the call stack changes, but that the stackFrames are all fetched correct?
So if we fetch stackFrames by first getting the top one, and only then the rest, you just want to be called one time once everything is fetched?
Let's first clarify that.

We might need to introduce a new event `onDidReceiveCallStack` or something like that

You should not need to call `fetchCallStack` that is a bit internal.

**Comment by roblourens** [comment]
I don't think I want to ask for all stackframes every time, because currently you don't actually request all stackframes unless the callstack is visible and the user clicks "Load more", right? And I don't want to cause more load. I think I just want to be notified when the top 20 frames are available.

**Comment by isidorn** [comment]
Yeah, we only request all the stack frames once the user clicks on the "Load more".
I think we should introduce a new event for this, as there does not seem to be the exact one you need. New event could maybe live somewhere here https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/debug/browser/debugSession.ts#L859
`onDidFetchThreadCallStack` and would send out a `thread`

Alternatively maybe you could listen on `debugService` change `state`, and when you see that it is `stopped` you can ask for the full stack frame and this should work I think. However state changes also when the user focuses other sessions so it would not be completely precise.

**Comment by roblourens** [comment]
I just disabled the whole thing for now. To verify, stepping in a notebook cell should not feel extremely slow.

**Comment by lramos15** [comment]
Still much slower than say a typescript file, but faster than before.
