### ISSUE TITLE
Allow keyboard to search through properties (within Breakpoint Hover)

### ISSUE THREAD

**Issue by jasonwilliams** [microsoft/vscode#127716]
When hovering over an object (while the breakpoint is triggered) you can get a list of properties. Sometimes that list is very long. Is it possible to have a similar experience to the Explorer (in the side bar), where typing a letter moves the focus to that property?

For example in the gif below i would expect to type "me" and be taken down to "memoizedProps"
![popUp](https://user-images.githubusercontent.com/936006/124037097-ed383c80-d9f6-11eb-88f3-3838f4177b9a.gif)

When the hover has focus the keyboard doesn't change content in the editor anyway so this should be safe to add without changing people's workflow.

**Comment by isidorn** [comment]
@jasonwilliams good catch, thanks for opening this issue. Now we support that you can click in the debug hover and type the name of the variables to be navigated to them. This already works in the variables view.

To verify: open debug hover, click on it, start typing the name of the variable from the hover and make sure that variable gets focused

**Comment by connor4312** [comment]
This is great to see, but I think we might need a little polish here when dealing with sorting. We should not make the hover smaller when filtering down to a smaller tree, otherwise if your mouse it outside of it this can happen:

![](https://memes.peet.io/img/21-07-02de51c8-6787-4eeb-b063-5ba5ccea7ced.gif)

**Comment by jasonwilliams** [comment]
I agree, my expectation would be moving towards the target but keeping the hover window the same size

**Comment by isidorn** [comment]
@jasonwilliams yeah that is the default behaviour
@connor4312 we should just disable filtering in the debug hover. I have now done that, and we are only supporting the "simple keyboard navigation" = no filter, focus just jumps based on pressed keybingind.

**Comment by jasonwilliams** [comment]
@isidorn can you go straight to top straight to bottom via the keyboard? (Sorry this may need to be a separate request if not)

**Comment by rzhao271** [comment]
@jasonwilliams is the rest of the implementation working ok right now?
If so, I think we can set this issue to verified (or z-author-verified), since a new Stable is shipping soon, and we'd like to get various issues verified before then.
Meanwhile, I think you can write https://github.com/microsoft/vscode/issues/127716#issuecomment-873220290 onto a new feature request, and link it back to this issue.

**Comment by connor4312** [comment]
I can verify

**Comment by jasonwilliams** [comment]
I won’t be at my machine for a few days so would need to delegate verifying to @connor4312

**Comment by isidorn** [comment]
@jasonwilliams yeah, `home` or `cmd + left` for first element, `end` or `cmd+right` for last element.
