### ISSUE TITLE
Test results can make the SQLite DB explode in size

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#127801]
A workspace storage DB I got from @egamma was 30 MB in size and the culprit is a single key called `testResults`. I can only speculate that we store all test results as workspace state? 

I think we need to be careful and use a file based approach if the data can potentially be very large.

The data looks like this:

```
[{\"id\":\"38ac242f-c375-4837-9651-f66b148964b2\",\"completedAt\":1614615858564,\"items\":[{\"parent\":\"ms-vscode.vscode-selfhost-test-provider/Arrays\",\"providerId\":\"fc829c73-72f1-44c3-8714-382253696c7e\",\"item\.........
```

**Comment by connor4312** [comment]
I think this is some old data -- I noticed the problem a while ago and since then have only stored ID and size in sqlite, with results stored in separate file:

https://github.com/microsoft/vscode/blob/da144f6280c47e908fd9f57099a6de1f5380fc39/src/vs/workbench/contrib/testing/common/testResultStorage.ts#L49-L53

**Comment by bpasero** [comment]
Oh cool thanks!
