### ISSUE TITLE
[Bug] Multiple selections aren't rendered correctly

### ISSUE THREAD

**Issue by wenfangdu** [microsoft/vscode#127948]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: v1.57.1
- OS Version: Windows 10

Steps to Reproduce:

1. Install [Dracula Official](https://marketplace.visualstudio.com/items?itemName=dracula-theme.theme-dracula).

2. Add setting:

```json
{
  "workbench.colorCustomizations": {
    "[Dracula]": {
      "editor.selectionBackground": "#bd93f980"
    }
  }
}
```

3. The first selection is rendered correctly, the subsequent selections aren't:

![2021-07-04 10_11_25](https://user-images.githubusercontent.com/28700378/124371018-4b437900-dcb0-11eb-87d9-a17d8343293d.gif)

**Comment by ArturoDent** [comment]
I see this too.  It happens with any theme I think and doesn't need to be in a theme-restricted `colorCustomization`.  The interesting thing is if I switch editors and come back it is corrected.  

It seems to stay at `"editor.selectionHighlightBackground"` until I switch editors, so the color is not updating immediately.

BTW, I am using <kbd>Ctrl</kbd>+<kbd>D</kbd> to do the next selections.  Something like <kbd>Alt</kbd>+click updates immediately.

**Comment by alexdima** [comment]
The problem is that the Dracula theme defines the following color:
```
"editor.selectionHighlightBackground": "#424450",
```

This color is not using transparency, so the selection highlights are being rendered on top of the selection. This is an oversight with the theme. Please open an issue against the theme at https://github.com/dracula/visual-studio-code.

A workaround would be to customize that color to add some transparency to it:
```
"workbench.colorCustomizations": {
        "[Dracula]": {
            "editor.selectionBackground": "#bd93f980",
            "editor.selectionHighlightBackground": "#59595e88"
        }
    },
```

![image](https://user-images.githubusercontent.com/5047891/130207242-f70359ab-ae48-49ea-bd4c-d82a5a584280.png)
