### ISSUE TITLE
switch terminal action breaks (and creates...?) terminal editors when switching between terminal editors in different groups

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#127901]
Open latest insiders
Create new terminal editor
Split it using editor split button on top right.
Switch from one terminal to the other (several times) using CMD+P term listing.
I hope that my message is clear enough. If not don't hesitate to tell me, and I'll do a video for you on Monday.

from https://github.com/microsoft/vscode/issues/10546#issuecomment-873168851

**Comment by meganrogge** [comment]
for the same reason as https://github.com/microsoft/vscode/issues/126469

sharing the terminal editor input between groups does not work. I think we need a terminal editor for each editor group so the setInput call/detaching of the instance does not break terminal editors in other groups

**Comment by meganrogge** [comment]
I believe this is caused by us not tracking the group index to which the editor input belongs

**Comment by rzhao271** [comment]
Switching from terminal A to terminal B results in terminal A's group picking up a new terminal, and terminal B breaking.

**Comment by Tyriar** [comment]
Can repro:

![image](https://user-images.githubusercontent.com/2193314/124809815-66fb8900-df15-11eb-8c2c-246c465f3c28.png)

It actually breaks the left side but only because it gets moved to the side. I suspect this is related to the recent SIDE_GROUP change. I don't think this meets the bar to push the release back as it can only happen when changing groups via ctrl/cmd+p and the fragility of that code.

**Comment by meganrogge** [comment]
FWIW, the SIDE_GROUP change was reverted.
