### ISSUE TITLE
More features of an IDE.

Like the Apache NetBeans IDE 12 can we have those Panels, Forms, Textfields, Labels, Containers etc. in VS Code. So that Java Programming and application development becomes much easy and friendly. I know Android Studio is there for Java but it would be fun to even create the design of the app i.e. background and input fields etc. from scratch or raw just like NetBeans. 

### ISSUE THREAD

**Issue by flux0806** [microsoft/vscode#127982]

**Comment by elbowdonkey** [comment]
Normally I'd recommend making your issue title more concise, with a detail description in the description, but in this case I'd recommend simply closing this. Even if you were to do that I'd still predict that it'd get little consideration. There are IDEs already for pretty much every language and framework. I suspect most people who use vscode aren't using it because they like IDEs.

**Comment by sbatten** [comment]
This issues is fairly vague, please see our [contributing guidelines](https://github.com/microsoft/vscode/blob/a45761ede37cd12e78e5066a10319896b08f6ad4/CONTRIBUTING.md). Additionally many of the features you request might make great extensions.
