### ISSUE TITLE
Show a prompt before reverting file

### ISSUE THREAD

**Issue by Bill-Stewart** [Microsoft/vscode#12806]
It would be nice if we could get a "You will lose all changes. Are you sure you want to revert this file?" when using the `workbench.action.files.revert` command. My rationale is that this is a bit like closing a file, do not save, and open it again. (Perhaps this could be an option?)

**Comment by GuardRex** [comment]
*BIG PING!* on this one. I just accidentally clicked on this trying to hit a *Save*. Look at the position of *Revert File* and *Save* in the menu ...

![capture](https://user-images.githubusercontent.com/1622880/27255697-c345b226-5369-11e7-8504-a87573d19048.PNG)

You (apparently) can't `Ctrl-Z`/Undo/Redo your way out of it. I lost ten minutes of work due to this.

Yes, :pray: PLEASE :pray: add a confirmation dialog box for the *Revert File* command, and it couldn't hurt to move the command a little bit away from the *Save* command, too. Perhaps, you could draw another horizontal line there. After all, *Close*/*Close All* are separated, and as @Bill-Stewart pointed out, this command is *not* anything like a *Save* command execution.

**Comment by nexional** [comment]
Requesting a confirmation dialog for revert if any edits are made in the file.

**Comment by bpasero** [comment]
I am closing this, you can just "Undo" and get your previous changes back.
