### ISSUE TITLE
Can not use Command-ArrowDown to open an editor from a search match

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#12804]
While testing  #12519.

- VSCode Version: 1.6.0 insiders
- OS Version: MacOS

Steps to Reproduce:

1. open a folder
2. Shift+Command+F
3. type a search expression with guaranteed matches
4. Tab to the search results view
5. Use ArrowDown and ArrowRight to navigate to a match
6. Use Command-ArrowDown to open the match in an editor
-> no editor opens

**Comment by sandy081** [comment]
@kieferrm Command-ArrowDown is specific to open a file from the Explorer. I think it was used because `Enter` on a file is take for rename in general in Mac.

In other views like Search & Problems following is supported
- <kdb>Enter</kbd> opens and pins the file and highlights the result
- <kdb>Space</kbd> opens the file without pinning and highlights the result

Also results displayed in these views are files, instead Search Matches or Problems.
