### ISSUE TITLE
Enable `contextIsolation` for all windows

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#128099]
We should explore to enable `contextIsolation` for all windows and ensure:
* there are no critical performance regressions doing so
  * we could explore to implement message port based communication from renderer to main process to bypass the context bridge hop
* there are no issues from the `contextBridge` when using the exposed API from our preload script

**Comment by bpasero** [comment]
Looks like there is a native crash when running from my macOS ARM device out of sources (https://github.com/microsoft/vscode/tree/ben/contextIsolation): 
[03644fe8-2020-4c3f-8ec7-fc8f10755d5d.dmp.zip](https://github.com/microsoft/vscode/files/6778446/03644fe8-2020-4c3f-8ec7-fc8f10755d5d.dmp.zip)

**Comment by deepak1556** [comment]
Its a crash when trying to proxy `process.env`  https://github.com/microsoft/vscode/blob/9006cc826898bd5692b645a059c72617f9b20c39/src/vs/base/parts/sandbox/electron-browser/preload.js#L284 . Specifically, node environment object has a custom property interceptor which gets called when accessing enumerable properties https://github.com/nodejs/node/blob/394fdecc9141aa4c6a8ea7f1aecaf5fcaaaf5c72/src/node_env_var.cc#L368-L376, for whatever reason the v8 context passed to this interceptor is of the main world instead of the isolated world hence leading to `EXC_BAD_ACCESS` crash.

Temporary workaround until further investigation is to avoid hitting the custom interceptor by 
`get env() { return { ...process.env }; },`

**Comment by bpasero** [comment]
Thanks, pushed a fix for that.

We still cannot launch with `contextIsolation: true`, there are things we depend on that will not work. I wonder if `sandbox: true` has to happen first because some of these things seem node.js dependent.

```
enableASARSupport() is only available in node.js environments
Uncaught (in promise) TypeError: require.__$__nodeRequire is not a function
Uncaught TypeError: Cannot read property '__$__isRecorded' of undefined
```

**Comment by bpasero** [comment]
I came to the conclusion that we can just go for sandbox: https://github.com/microsoft/vscode/issues/154006
