### ISSUE TITLE
Regression in fix for python/pylance installation race condition

### ISSUE THREAD

**Issue by jakebailey** [microsoft/vscode#128088]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1. Install VS Code insiders
2. Install Python from the marketplace
3. Note the popups in the corner, as the Python extension was activated before any of its dependencies had the chance to start installing.

The Python extension checks for the existence of the Pylance extension at various stages, at startup to know if it should use the LS, then later to see if it was installed (to detect if the user installs it later to prompt for a setting change).

Previously, this worked well, but had a race condition (hence #124870). Now, it seems as though the race has been shifted elsewhere, with the Python extension starting up before its pack deps are even listed in the extensions API.

There's no way to tell if the Pylance extension is going to be installed in the future (maybe it's in milliseconds, maybe days), so when the Python extension starts up, we can't simply wait to see if maybe Pylance is going to appear, so there's not really a good workaround as far as I can tell.

Python + Pylance via extension pack is our main install flow; it's how Pylance can be optional but preinstalled and working on first install. The bugfix seems to break that in all testing I've done, so all new users will get the prompts and have to reload (as we start with the wrong LS).

See:

- https://github.com/microsoft/vscode-python/issues/16614
- https://github.com/microsoft/vscode/issues/124870

**Comment by sandy081** [comment]
I do not agree that this is a regression from the fix #124870. Previously, VS Code is not handling installing extensions with dependencies in the right order, because of it, Pylance is getting installed and activated before Python is. By fixing #124870, we make sure extensions are installed and activated in correct order. 

The issue that is surfaced now shows the cyclic dependencies between Python and Pylance extensions, ie., they depend on each other. As mentioned by @jakebailey, they want these two extensions to be treated as one unit and get activated together. Generally, we recommend to have single extension in such a case. Otherwise, this is a new concept in VS Code. Extensions installation in VS Code always considered extension as a single unit and therefore each installed extension is activated individually. We need to introduce bulk installation support in VS Code to handle this which is a big feature by itself.

We do not implement any features at the end of the milestone. So after discussing in our Zurich stand up, @alexdima and myself decided to come up with a temporary, low risk fix that is scoped only to Python & Pylance extensions which is to support bulk install concept only for python and pylance extensions and activate them together. **Note** that this is supported only when installing python or pylance extensions directly but not when installing the packs that includes them.

This is the best safe changes we can do given that we are end of the milestone . Going forward we would add support for bulk install in the core in general.

**Comment by sandy081** [comment]
Follow up feature request - https://github.com/microsoft/vscode/issues/128114

**Comment by sandy081** [comment]
To verify:

1. Open VS Code and open a sample python file
2. Install Python extension. 
3. Make sure you do not see any prompts from Python extension asking to reload window because Pylance is installed. Also make sure python, pylance an jupyter extensions are shown installed in the extensions viewlet.
4. Uninstall Python extension and now install Pylance extension and verify step 4
5. Install some other extensions and extension packs (not python related) and make sure extension viewlet gets updated correctly and these newly extensions are activated correctly.

**Comment by IanMatthewHuff** [comment]
Validated on current insiders bits using the above steps. Didn't see prompts to reload when either installing Python or Pylance. Also installing either Python or Pylance installed the full set of Python + Pylance + Jupyter.

**Comment by luabud** [comment]
@sandy081 Thank you so so much for addressing this so fast!
