### ISSUE TITLE
Mention backtick for Watermark Commands Toggle Terminal

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#12800]
- VSCode Version:1.6.0 insiders
- OS Version:Windows 7

Customer verbatim suggests that with the Toggle Terminal keyboard shortcut Ctrl+` it isn't obvious that a backtick character is used.

Consider added text to call out the backtick.
Something like:
"Toggle Terminal    Ctrl+`(using the backtick character)"
or more simply:
"Toggle Terminal     Ctrl+` (backtick)

**Comment by bgashler1** [comment]
Not sure if we can squeeze this in, but putting it on September just for reference.  @gregvanl is this a common problem in verbatim?  Are they confusing it with an apostrophe `'`?  I only ask because spelling out the key `(backtick)` seems kind of ugly to me and inconsistent with the other keys we're showing.

**Comment by gregvanl** [comment]
Yes, I've seen people confusing backtick with apostrophe a couple of times in doc feedback verbatim.  I added mention of backtick to the doc pages (https://code.visualstudio.com/docs/editor/integrated-terminal).

**Comment by gregvanl** [comment]
Doesn't seem to be a problem and haven't heard any customer complaints.
