### ISSUE TITLE
Format on Save not working when auto save is enabled

### ISSUE THREAD

**Issue by s-khan-net** [microsoft/vscode#128090]
After enabling format on save from settings (editor.formatOnSave) and having auto save (files.autoSave) enabled as well, 
Expected the code to be formatted automatically after some delay, but it formats the code after saving the file explicitlt again (pressing ctrl+s)
A small (really small) issue there Please paste.

**Comment by jrieken** [comment]
That is done on purpose because auto save lacks a clear signal at which you would expect changes to your underlaying document. E.g formatting can significantly change your text, your cursor might jump, the scroll position changes and we don't want to do that "randomly", meaning without a clear user signal that that is OK now.
