### ISSUE TITLE
Explore adding 'toggle inlay hints' keybinding

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#128162]
Right now inlay hints are either on or off. However I believe VS lets you keep hints disabled normally and then peek at them as needed by holding down a key (`ctrl + alt` I believe): https://github.com/dotnet/roslyn/pull/48479

We should explore something similar for VS Code

**Comment by jrieken** [comment]
> then peek at them as needed by holding down a key

Afaik there is two modes: inline hints that always show in-between characters and overlay hints which are ephemeral and on top of characters. Extensions/providers would need to know what they are supposed to return and the current API design would need a separate provider for that

**Comment by Tyriar** [comment]
I'd like overlay hints specifically so I don't need to reorient myself when all the code shifts around.

**Comment by misolori** [comment]
I like that second option, though I'd expect it to closely follow hovers instead (for consistency)?

**Comment by Tyriar** [comment]
@misolori I just moved the inlays to above and then added a border, so it fits fine imo. We wouldn't want the regular hover's border/shadow here anyway since we want them to be compact.

**Comment by Kingwl** [comment]
I'm happy to work on this. But I might need some suggestions.

> are ephemeral and on top of characters 

@jrieken 

What should we do if the hints text is longer/shorter than the original code who has been overlay?

And we may still need a key binding for editor that just toggle the inlay hints feature event there's overlay hints?

**Comment by hd321kbps** [comment]
It would be nice to have hotkeys to temporarily disable hints. I often work in an editor with a small window width and they sometimes get in the way.

**Comment by jrieken** [comment]
Exploring some ephemeral mode which shows inlay hints only while pressing and holding <kbd>Crl+Alt</kbd>. Tho, using two buttons make the link and context menu gesture quite hard... 

https://user-images.githubusercontent.com/1794099/149188169-068b9bf9-0f86-4743-8901-3176a6408498.mov

@Tyriar I am not convinced that the overlay-inlay is a good solution. What do you do when those overlap source that you want to see. Think of two function calls with argument - the lower hints will overlay the upper functions arguments

**Comment by misolori** [comment]
@jrieken would we ever have an option where holding the keyboard shortcut for +3s would do this ephemeral mode and if you were to quickly press them then they would just toggle them on/off normally?

**Comment by Tyriar** [comment]
@jrieken I think there's 2 overlap problems:

- Overlapping code: The smaller text size was one way of combating hiding relevant code, but since it's so easy to show/hide you could release and hit ctrl+alt or whatever it is to view read them if you need to.
- Overlapping other hints: I'm not sure how much of a problem this would be in practice, at least using the inlay config in vscode right now there aren't that many hints. This could also not be that bad as generally my variable names are fairly verbose. One idea is to ensure the symbol the cursor is on is in the foreground, and hovering another one would cause it to go to the foreground.

The main problem that idea was meant to solve was to prevent code jumping around so much. Consider the amount your eyes need to move to see the type for the third `foo` and back again:

![image](https://user-images.githubusercontent.com/2193314/149199120-83b1e5a2-b4cf-4e61-8a89-0da88a495ff6.png)

**Comment by jdneo** [comment]
+1 for this.

Showing Inlay hint everywhere will make the code line so long and annoy the users. So the language extensions have to expose several settings to let users turn off the hint when they don't want then for some scenarios.

If there is a easy way to toggle the inlay hints, no matter for a key binding or a UI button, etc... , it will mitigate the issue a lot.

**Comment by sam-mccall** [comment]
We got enough requests that we added a "toggle inlay hints" command to vscode-clangd, so people can easily bind it to a key.
It's a bit odd because this is toggling `editor.inlayHints.enabled` which we don't own. It'd be nice if VSCode offered this command itself. 

(Overlay hints sound really interesting, but inlay hints are here now and a convenient toggle seems useful regardless)

**Comment by jrieken** [comment]
I have pushed a change that add a new `editor.inlayHints.toggle` options. When set to `show` inlay hints are hidden by default and they only show when holding `ctrl+alt`. When set to `hide` inlay hints are shown by default and they hide when holding `ctrl+alt`. When unset inlay hints show as they do today

**Comment by texastoland** [comment]
> So long as I can change its keybinding, I use `ctrl+alt` chords for sub-word navigation and it would be annoying if the inlay hints kept popping up when I did.

@jrieken Did you see this? See implementation in https://github.com/microsoft/vscode/pull/48023/files. Is there any limitation to making it a keybinding? I think ReSharper just uses `Ctrl` if you're open to an alternative.

**Comment by jrieken** [comment]
>  Is there any limitation to making this a keybinding? I think ReSharper just uses Ctrl if you're open to an alternative.

Yeah, there are actually limitations that prevent us from making this freely configurable. Tho, this isn't a conflict in the classic sense and normal keybindings still work. Inlay hints just observe the pressed/held state but don't consume a key event meaning you can still use `ctrl+alt` for sub-word navigation - tho with the annoyance that inlay hints toggle

**Comment by texastoland** [comment]
> tho with the annoyance that inlay hints toggle

Precisely. It's either a deterrent from using subword navigation or your toggle. Advocating because they're both useful features! <kbd>Ctrl</kbd> alone is reserved for context changing (switching spaces, Mission Control, etc. on Mac). I guess it'd need debounced or maybe there's another free combo.
