### ISSUE TITLE
Name debug console automatically using launch.json file

### ISSUE THREAD

**Issue by alon710** [microsoft/vscode#128108]
Today users can change consoles names manually after executing their code

![image](https://user-images.githubusercontent.com/35544532/124729436-1d14a200-df19-11eb-9915-75014b0b15c6.png)

I want to be able to change to console name before I launch my application using to `launch.json` configuration file
for example:

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Module Name",
            "type": "python",
            "request": "launch",
            "module": "path.to.module",
            "consoleName": "My Console Name",
        }
    ]
}
```

More info [here](https://stackoverflow.com/questions/67761990/vscode-change-debug-console-name-automatically)

**Comment by NescobarAlopLop** [comment]
Great idea!

**Comment by Gagam9** [comment]
Pro!

**Comment by W3Dojo** [comment]
[I answered this question on "Stack Overflow", which was  a post also created by Alon,](https://stackoverflow.com/questions/67761990/vscode-change-debug-console-name-automatically/68232767?noredirect=1#comment120685147_68232767)  and initially I though I had offered up a solution that would work for him (solution is below).  I wrote two tasks, the first task changed the name using an `input`(defined in tasks.json), and then I wrote another nearly identical task that used a second `tasks.json` input. I coupled the two tasks with the `launch.json` _"hooks"_ in such a way that, one task would be set to __`"preLaunchTask"`__, and it would change the name of the console while debugging, and the other would be set to __`"postDebugTask"`__, and it would change the name back when the debugger finished debugging. At the time I was writing a VSCode extension, in VSCode (obviously), and I used that debugger to test the tasks I wrote for Alon. __It worked__ beautifully! Often I try writing these wild little solutions to offer something new, and more times than not, they don't work out. My joy was short lived, as it turns out, the solution works for some cases, and not others. In this case, it worked for VSCode extension debugging, but not for Alon's Python Debugger. The reason for this, is because the preLaunch hook in `launch.json` is exactly that (**Pre** **Launch**); meaning, the debugger runs the task's code, then in, most cases, it attaches the debugger to a new console. 

The tool to do this is already supported by VSCode. The VSCode command `"workbench.action.terminal.renameWithArg"` works perfectly, and the inputs that are defined in the tasks.json file, gives VSCode users the ability to set the argument. The only thing that is missing is a...

### Post-launch hook 

...which is needed for running a task after the Debugger runs. It would be nice if we could have, pre & post tasks, sorta like what NPM offers with `package.json` scripts. In a nutshell, launch.json would have the following properties for running tasks i the launch.json file: 

* preLaunchTask
* postLaunchTask
* preDebugCloseTask
* postDebugTask

A lot more could be done with tasks & debugging if this were the case.


```

{
    // .../.vscode/launch.json

    "configurations": [
        {
            "args": ["--extensionDevelopmentPath=${workspaceFolder}"],
            "name": "Launch Extension",
            "outFiles": ["${workspaceFolder}/out/**/*.js"],
            "request": "launch",
            "type": "pwa-extensionHost",
            "preLaunchTask": "task|renameConsolePre",
            "postDebugTask": "task|renameConsolePost"
        }
    ]
}

{
  // .../.vscode/tasks.json
 
   "version": "2.0.0",

    "tasks": [
        {
            "label": "task|renameConsolePre",
            "command": "${input:renameConsolePre}"
        },

        {
            "label": "task|renameConsolePost",
            "command": "${input:renameConsolePost}"
        }
    ],

    "inputs": [
        {
            "id": "renameConsolePre",
            "type": "command",
            "command": "workbench.action.terminal.renameWithArg",
            "args": {
                "name": "DEBUGGING" // Changes console name to this value
            }
        },
        {
            "id": "renameConsolePost",
            "type": "command",
            "command": "workbench.action.terminal.renameWithArg",
            "args": {
                "name": "BASH" // Resets console name to this value
            }
        }
    ]
}


```

**Comment by alon710** [comment]
> [I answered this question on "Stack Overflow", which was  a post also created by Alon,](https://stackoverflow.com/questions/67761990/vscode-change-debug-console-name-automatically/68232767?noredirect=1#comment120685147_68232767)  and initially I though I had offered up a solution that would work for him (solution is below).  I wrote two tasks, the first task changed the name using an `input`(defined in tasks.json), and then I wrote another nearly identical task that used a second `tasks.json` input. I coupled the two tasks with the `launch.json` _"hooks"_ in such a way that, one task would be set to __`"preLaunchTask"`__, and it would change the name of the console while debugging, and the other would be set to __`"postDebugTask"`__, and it would change the name back when the debugger finished debugging. At the time I was writing a VSCode extension, in VSCode (obviously), and I used that debugger to test the tasks I wrote for Alon. __It worked__ beautifully! Often I try writing these wild little solutions to offer something new, and more times than not, they don't work out. My joy was short lived, as it turns out, the solution works for some cases, and not others. In this case, it worked for VSCode extension debugging, but not for Alon's Python Debugger. The reason for this, is because the preLaunch hook in `launch.json` is exactly that (**Pre** **Launch**); meaning, the debugger runs the task's code, then in, most cases, it attaches the debugger to a new console. 
> 
> The tool to do this is already supported by VSCode. The VSCode command `"workbench.action.terminal.renameWithArg"` works perfectly, and the inputs that are defined in the tasks.json file, gives VSCode users the ability to set the argument. The only thing that is missing is a...
> 
> ### Post-launch hook 
> 
> ...which is needed for running a task after the Debugger runs. It would be nice if we could have, pre & post tasks, sorta like what NPM offers with `package.json` scripts. In a nutshell, launch.json would have the following properties for running tasks i the launch.json file: 
> 
> * preLaunchTask
> * postLaunchTask
> * preDebugCloseTask
> * postDebugTask
> 
> A lot more could be done with tasks & debugging if this were the case.
> 
> 
> ```
> 
> {
>     // .../.vscode/launch.json
> 
>     "configurations": [
>         {
>             "args": ["--extensionDevelopmentPath=${workspaceFolder}"],
>             "name": "Launch Extension",
>             "outFiles": ["${workspaceFolder}/out/**/*.js"],
>             "request": "launch",
>             "type": "pwa-extensionHost",
>             "preLaunchTask": "task|renameConsolePre",
>             "postDebugTask": "task|renameConsolePost"
>         }
>     ]
> }
> 
> {
>   // .../.vscode/tasks.json
>  
>    "version": "2.0.0",
> 
>     "tasks": [
>         {
>             "label": "task|renameConsolePre",
>             "command": "${input:renameConsolePre}"
>         },
> 
>         {
>             "label": "task|renameConsolePost",
>             "command": "${input:renameConsolePost}"
>         }
>     ],
> 
>     "inputs": [
>         {
>             "id": "renameConsolePre",
>             "type": "command",
>             "command": "workbench.action.terminal.renameWithArg",
>             "args": {
>                 "name": "DEBUGGING" // Changes console name to this value
>             }
>         },
>         {
>             "id": "renameConsolePost",
>             "type": "command",
>             "command": "workbench.action.terminal.renameWithArg",
>             "args": {
>                 "name": "BASH" // Resets console name to this value
>             }
>         }
>     ]
> }
> 
> 
> ```

I think your solution is not intuitive enough.

**Comment by cyrlop** [comment]
I would love to see this feature implemented!
If this happens, I guess it won't hurt to add the color and icon change as well since these three commands go together ([see here](https://code.visualstudio.com/docs/editor/integrated-terminal#_customizing-tabs))

```
workbench.action.terminal.rename
workbench.action.terminal.changeIcon
workbench.action.terminal.changeColor
```

**Comment by isidorn** [comment]
This should be handled by the run in external terminal logic. Thus assigning to @weinand

**Comment by weinand** [comment]
No, this request asks for automatic naming of "debug consoles".
Doing this for integrated and external terminals is more difficult because they are controlled by individual debug extensions and not by VS Code core.

**Comment by connor4312** [comment]
We now automatically name the terminal based on the launch config that created it, e.g.

<img width="215" alt="image" src="https://user-images.githubusercontent.com/2230985/206801433-7b153bea-98fa-4b3b-9cd9-034dfa31e42c.png">

**Comment by johnbendi** [comment]
> We now automatically name the terminal based on the launch config that created it, e.g.
> 
> <img alt="image" width="215" src="https://user-images.githubusercontent.com/2230985/206801433-7b153bea-98fa-4b3b-9cd9-034dfa31e42c.png">

@connor4312 that is not my experience even with `code-insiders`. The terminal is still name `Python Debug Console`

**Comment by connor4312** [comment]
That is because that's what the Python extension provides when it issues a `runInTerminal` request. Please file an issue on them if you think that should be changed.
