### ISSUE TITLE
Binary diff editor UX is confusing

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#128145]
Testing #124222 

The messages now show up on both sides. When I click one of the messages, the quickpick comes up. I expected both sides of the diff to then use the option I picked, but instead:

If I select the text editor, a new untitled file opens.
If I select the hex editor, a new hex editor shows a blank file with an empty title.

I think the new editor should be opening the binary file, but even then, the fact that the operation results in leaving the diff editor still confuses me.

Therefore, I think that either binary diffs should be supported somehow e.g. using the hex editor (difficult), or a notification should pop up stating the user is trying to diff two binary files, which is not supported. I'd rather see that I'm doing something unsupported, than be led down the path of seeing the diff editors -> seeing the message with the link -> selecting an option in the quickpick -> going back out of the diff view and wondering why I got the diff view in the first place.

**Comment by lramos15** [comment]
What you describe sounds like a bug. You should be able to get a binary text diff

**Comment by bpasero** [comment]
@lramos15 fix was a bit more involved, maybe you review it. Bottom line: the call to `editorResolverService.resolveEditor` always passed in `undefined` when using `editor.resource` because the editor is the diff editor without resource. We need to pass in the proper untyped editor form that accounts for diff editors.

All in all I find the code quite ugly, it would be nicer if we could simply do everything from the `replaceEditors` call. I think the only piece missing is the awkward `setForceOpenAsText` we still need to do...

I tested the following cases:
* open zip, select to open as text
* open a zip, select to open as hex
* compare 2 zips, select to open as text
* compare 2 zips, select to open as hex

**Comment by lramos15** [comment]
Yeah I think binary / force open as text is something we need to add to the untyped input as we have a few cases that require that

**Comment by rchiodo** [comment]
@bpasero can you describe how to verify this? 

It looks like I can open with the hex editor, but I can't diff?
![hexdiff](https://user-images.githubusercontent.com/19672699/127531439-759a23c9-c6c3-46c5-a025-98d7a42ecb76.gif)

**Comment by lramos15** [comment]
The hex editor is different. Just wanted to make sure that you would get a text editor if you clicked open anyways and selected text. This was broken before

**Comment by rchiodo** [comment]
So the bug is fixed if the text editor opens?

**Comment by lramos15** [comment]
> So the bug is fixed if the text editor opens?

The bug is fixed if the quickpick opens and lets you pick text editor. Not hex editor as hex editor is an extension
