### ISSUE TITLE
debug focus automatically switches to newly created debug session

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#128132]
Steps:
- unpack and open attached [Cluster.zip](https://github.com/microsoft/vscode/files/6777880/Cluster.zip) project in VS Code 
- set breakpoint in test.js line 15
- start debugging by running the "Cluster" launch config
- after hitting breakpoint press Continue button on debug toolbar

Observe: a new debug session starts and the corresponding node in the CALL STACK gets selected. As a consequence the debug focus switches to the new session and the debug toolbar no longer shows the "Continue" button. In order to continue stepping, a stopped debug session must be selected in the CALL STACK view. 
This happens for every new child process of the cluster...

![2021-07-07_16-05-26 (1)](https://user-images.githubusercontent.com/1898161/124774725-514e8980-df3e-11eb-9d83-087108d92c4a.gif)

A new debug session should never change the selected session in the CALL STACK view (at least if there is already a stopped debug session.

**Comment by isidorn** [comment]
I checked last two stables (1.58 and 1.57) and we were already behaving like this.
Whenever there is a new session it would steal focus, even if there is already a session that is stopped and focused.
I would prefer not to change this as part of endgame -> August. Especially since the js-debug sort of relies on this that the child session which comes after the parent session would take the focus away.

also fyi @connor4312 to get his thoughts

**Comment by connor4312** [comment]
Yea I think if a debug session is paused, focus should not be automatically moved away

**Comment by weinand** [comment]
If this is not a regression, I'm fine with not fixing this for July. But we should fix this at the beginning of the August cycle.

**Comment by gjsjohnmurray** [comment]
Maybe #121898 is related.

**Comment by isidorn** [comment]
I pushed a similar fix for https://github.com/microsoft/vscode/issues/128400
However the problem with this issue is the following:
* once a user presses `continue` we do not know that the Session 1 will be stopped again in a couple of ms. I have basically mentioned this problem here https://github.com/microsoft/vscode/issues/125144#issuecomment-869641057

So the only way to solve this that I see is to auto focus only after a timeout. Which Visual Studio does not do.
Let me know your thoughts.

**Comment by baybal** [comment]
Given this is a _very_ rare opportunity to catch people who work on VScode JS debugger, I have a small offtopic question

How does the debugger know the line number on which `console.log` was called, and how a wrapper for it can pass it along to the real console.log while preserving object inspectability, formatting, colours, etc?

It's important for logger packages like https://github.com/winstonjs/winston

**Comment by connor4312** [comment]
@baybal you can file issues here or [on js-debug](https://github.com/microsoft/vscode-js-debug) and I usually respond within 24 😉  The debugger knows the line console.log is called on since the call stack reported by V8. The first non-skipped location in the stack will be shown, which you can adjust using [skipFiles patterns](https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_skipping-uninteresting-code).

**Comment by weinand** [comment]
@isidorn above you said:
> once a user presses `continue` we do not know that the Session 1 will be stopped again in a couple of ms. I have basically mentioned this problem here https://github.com/microsoft/vscode/issues/125144#issuecomment-869641057

I do not understand how your statement is related to the issue at hand:

my ask was: A new debug session should never change the selected session in the CALL STACK view because the new session is **running** and there is nothing that needs to be shown by focusing on it.

Only if the new session stops, we should focus on it.

**Comment by weinand** [comment]
I cannot verify this.
Please see:

![2021-08-30_12-44-30 (1)](https://user-images.githubusercontent.com/1898161/131327969-b1f0b5e5-32b5-494d-aed0-e4b7a695f0d7.gif)

**Comment by isidorn** [comment]
The fix I did, did not cover the case when all sessions are siblings.

Before we would always focus on a new child session if the parent session was focused. This does not really make sense in general, and would only make sense for `js-debug`. I have removed this behaviour and this indeed fixes the issue.
So in theory now when a user starts a `js-debug` session which does not hit any breakpoints the parent session will remain focused until the child gets stopped. I think this makes sense in general.

I suggest to do this for the September milestone, since we have always behaved like this and to give some time to catch potential regressions.  I have pushed a fix for this to `main`, if somebody would like to have this as part of the release please let me know and I can create a PR against the `release` branch.

fyi @roblourens

**Comment by weinand** [comment]
This works now for my [Cluster.zip](https://github.com/microsoft/vscode/files/6777880/Cluster.zip) sample.
