### ISSUE TITLE
spawn rg fails with EACCES error

### ISSUE THREAD

**Issue by montyvesselinov** [microsoft/vscode#128178]
spawn /Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar.unpacked/vscode-ripgrep/bin/rg

produces EACCES error.

I use the version:

Version: 1.58.0-insider (Universal)
Commit: 2d23c42a936db1c7b3b06f918cde29561cc47cd6
Date: 2021-07-07T12:08:00.172Z (12 hrs ago)
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 20.5.0

the same error is reported under coder here:

https://github.com/cdr/code-server/issues/1666

**Comment by roblourens** [comment]
There are other reports in https://github.com/microsoft/vscode/issues/123276, but I have no idea what the cause is. You can  check that the folders you are searching in do exist, and that you do have permission to access them. Check the permissions on the binary in the path above. Check whether you are using antivirus. And do you also only see this with multi-root workspaces, as the other users report?
