### ISSUE TITLE
Split terminal error

### ISSUE THREAD

**Issue by damianoazzolini** [microsoft/vscode#128277]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
```
Version: 1.58.0-insider (user setup)
Commit: 2d23c42a936db1c7b3b06f918cde29561cc47cd6
Date: 2021-07-07T12:09:55.219Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19042
```
- OS Version: `Windows 10 version 20H2 build 19042.1052`

I'm connected with ssh into a server with installed `CentOS Linux release 7.7.1908`

Steps to Reproduce:
1. Open integrated terminal
2. Split terminal
3. Create new terminal (with the +) and move into this new terminal
4. Split terminal

At step 4 I get an error ''The terminal process failed to launch: Starting directory (cwd) "\home\userrname\test" does not exist''. It seems that the second terminal tries to open a folder but with the path specified with `\` instead of `/` (the first split operation, step 2, works well). /home/userrname/test does exists, and it is the default location of a new terminal

**Comment by damianoazzolini** [comment]
#127633 states that nothing happens
#123361 states that the layout is messy

**Comment by ranshalit** [comment]
I also observe the same error after recent update

**Comment by meganrogge** [comment]
I can't reproduce this @Tyriar any thoughts?

**Comment by spasche** [comment]
Hello,

I'm also affected, here are some steps to reproduce.
I could see that it only happens when you have a workspace with multiple folders.

Pre-conditions:
- vscode running on Windows, tested with version 1.58.2
- linux server accessible from ssh

1. Prepare the linux server
```
ssh user@ubu-dev
mkdir /tmp/folder0 /tmp/folder1
cat << EOF > /tmp/myworkspace.code-workspace
{
        "folders": [
                {
                        "path": "folder1"
                },
                {
                        "path": "folder2"
                }
        ]
}
EOF
exit
```
2. From Windows, open the remote workspace
```
code --user-data-dir=c:\tmp\clean_profile --file-uri vscode-remote://ssh-remote+user@ubu-dev/tmp/myworkspace.code-workspace
```
3. Open a terminal, select folder1
4. Run command: Terminal: Split terminal

Video: https://1drv.ms/v/s!AloPbwYP-ZZVhYEtHc8CDxXT7yU38g?e=FoI6dc

**Comment by lithsin** [comment]
I also have the same problem for Workspaces with multiple folders. The first terminal can be opened without any problem, but a subsequent split terminal at the same location will result in the error message below. I can confirm that the folder does exist (otherwise the first terminal wouldn't have been opened!) and Workspaces with only one folder do not suffer from this problem.

![image](https://user-images.githubusercontent.com/85101401/126023799-b17124fc-9a7c-4f6c-808c-58eb34eccae1.png)

**Comment by jchang10** [comment]
https://github.com/microsoft/vscode/issues/127811 is the same. Bummer no solution yet.

**Comment by Tyriar** [comment]
@jchang10 thanks for the link, that one makes it pretty clear the is splitCwd problem is

/duplicate

**Comment by cj-l** [comment]
Also facing this issue, I can start new terminals but they cannot be split

**Comment by Melirius** [comment]
More mystery to the topic: 1) if I set `sh` as default terminal, it can be split, and even `bash` terminal can be split, providing another `sh` terminal; 2) if I set `sh` as default terminal, start `bash` terminal, change default to `bash`, this already started `bash` terminal provides another `bash` terminal without problem; 3) if I set `bash` as default terminal and start `bash` terminal, it cannot be split.
