### ISSUE TITLE
Inline Completions

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#128200]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=126793&view=logs&j=3792f238-f35e-5f82-0dbc-272432d9a0fb&t=0d55b56b-c0b2-5f64-1c6a-62c9163a0d5b&l=8495

```
1) Inline Completions
       Backspace is debounced:

      Error: Aborting after running 1000 timers, assuming an infinite loop!
      + expected - actual


      at Immediate.<anonymous> (/Users/runner/work/1/s/node_modules/@sinonjs/fake-timers/src/fake-timers-src.js:1203:37)
      at processImmediate (internal/timers.js:461:21)

```

**Comment by joaomoreno** [comment]
@jrieken I used blame to find the owner of inline completions. 🤔 Who should this be assigned to?

**Comment by jrieken** [comment]
> @jrieken I used blame to find the owner of inline completions. 🤔 Who should this be assigned to?

Looks like you did that wrong

<img width="826" alt="Screen Shot 2021-07-12 at 12 53 21" src="https://user-images.githubusercontent.com/1794099/125276127-25515080-e310-11eb-991b-d77a5f210ff3.png">

**Comment by hediet** [comment]
From slack:

I found the real issue of the flaky unit test.
Apparently, some test that runs before the inline suggestion test (which fakes `setTimeout`/`setInterval`) calls `PersistentProtocol._sendKeepAliveCheck`. `sendKeepAliveCheck` spawns a `setTimeout` (5 seconds) that calls itself (basically an endless loop over time).

When the time is faked, my inline completion test waits for all scheduled timers to finish until the queue of scheduled timers is empty (assuming I am in control of all scheduled timers when my test is run). However, the `setTimeout` loop in `sendKeepAliveCheck` then causes an endless loop. My test gives up after running 1000 scheduled timers and I guess then things are in an inconsistent state.

This only happens when my tests are run right before `sendKeepAliveCheck` is about to run. If my tests a run in the 5s interval in which `sendKeepAliveCheck` is not called, nothing bad happens.
As a quick fix, I will change my tests to not wait for the timer queue to get empty. As a long term fix, I think tests should be isolated better - at least they should make really sure they clean up everything (such as disposables/timers/global handlers/etc.).

Joh tracked this down to this leaking disposable: https://github.com/microsoft/vscode/blob/990906a16554f59318e6c1fb65b45ea0c62d5ce0/src/vs/base/parts/ipc/test/node/ipc.net.test.ts#L178.
