### ISSUE TITLE
Investigate merging `EditorPane` and `EditorInput` registration into one

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#128207]
Continuation of https://github.com/microsoft/vscode/issues/126603.

We have a way to register an editor pane and a way to register an editor input. It might be clever to have one registration which pipes through the other one to the proper service. I'm not sure if Panes 1:1 to inputs though.

**Comment by bpasero** [comment]
Typical editor pane registration code is simply mapping a typed editor input class onto the pane (1 to many):

```ts
Registry.as<IEditorPaneRegistry>(EditorExtensions.EditorPane)
.registerEditorPane(
	EditorPaneDescriptor.create(
		WebviewEditor,
		WebviewEditor.ID,
		'Webview Editor',
	), [
	new SyncDescriptor(CustomEditorInput)
]);
```

When I register an editor, maybe I can also register the associated pane for the editors.

The only worry I have is that the code to register the pane today executes when code is loading because it is static and would load at a later point if used via service...

**Comment by bpasero** [comment]
Given issue grooming, I tend to think this issue is out of scope. At least I am not planning to work on this anytime soon, leaving up to you if you want to look into it.

**Comment by lramos15** [comment]
Yeah I agree. I think there's a lot more debt issues that we gain a larger value from and we could always revisit this if we find it limiting ourselves.
