### ISSUE TITLE
When no kernel is selected, `notebook.cell.executeAndSelectBelow` cell insertion dismisses kernel picker

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode#128244]
## Environment data

-   VS Code version: 1.58.0-insider
-   Jupyter Extension version (available under the Extensions sidebar): v2021.8.993044620
-   Python Extension version (available under the Extensions sidebar): v2021.6.944021595
-   OS (Windows | Mac | Linux distro) and version: Windows

## Steps to Reproduce: 
1. Create new notebook 
2. Put something in first cell 
3. Use Shift + Enter shortcut to run

## Expected behavior 
To be prompted for a kernel and run after selection, then focus moves to next cell 

## Actual behavior
Focus moves to the next cell, I am not prompted to pick a kernel as none is selected for a new notebook. 
Have to put focus back on the first cell and try shift + enter again 

_*Note: This does not occur if I open an existing notebook that has not been seen by VS Code before_

![shift+enter first cell ](https://user-images.githubusercontent.com/19276747/124343056-81341080-db7d-11eb-83f4-22b0f4f19b8f.gif)

**Comment by joyceerhl** [comment]
@claudiaregio I believe what's happening here is that the kernel picker comes up and then immediately disappears because the inserting a new cell into the notebook steals focus from the kernel picker. Can you confirm if that's what you're seeing too?

shift+enter keybinding maps directly to `notebook.cell.executeAndSelectBelow`, and if no kernel is selected the kernel picker should be appearing:

https://github.com/microsoft/vscode/blob/3c9e29fa75fa9dcfcfc849d098f21a8cf34b0f70/src/vs/workbench/contrib/notebook/browser/notebookEditorKernelManager.ts#L38-L42

**Comment by joyceerhl** [comment]
The workspace edit to insert a new cell if the executed cell was the last one in the notebook dismisses the kernel picker. If there is already a cell below, focusing that cell doesn't dismiss the kernel picker. 

That is why it looks like shift+enter doesn't work the first time: on first shift+enter, there is no cell below, so we insert a cell; if you set focus back to the first cell and try again, there's already a cell below, so it just focuses that one.

**Comment by joyceerhl** [comment]
@roblourens I see that we intentionally

**Comment by joyceerhl** [comment]
@roblourens I see that we intentionally defer evaluating `runCell` until after the next cell has been inserted (if necessary) and focused: https://github.com/microsoft/vscode/issues/99156 Is there a way to ensure that inserting a notebook cell doesn't dismiss the kernel picker?

**Comment by claudiaregio** [comment]
@joyceerhl Yes, I see a really fast flash
