### ISSUE TITLE
Vscode doesn't start on Kali Linux

### ISSUE THREAD

**Issue by DaniKonoplya** [microsoft/vscode#128331]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1. In terminal run : code
2. dmegs error:  traps: code[16850] trap int3 ip:55e6a70db4f8 sp:7ffc2c62aff0 error:0 in code[55e6a6eaa000+5dfb000]
code version : 1.58.0-1625728071

**Comment by DaniKonoplya** [comment]
Os version: Linux kali 5.10.0-kali3-amd64 #1 SMP Debian 5.10.13-1kali1 (2021-02-08) x86_64 GNU/Linux

**Comment by DaniKonoplya** [comment]
By downgrading to:

Version: 1.57.1
Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
Date: 2021-06-17T13:26:56.255Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Linux x64 5.10.0-kali3-amd64

The application started successfully. Some problem with the newest version.

**Comment by alkorang** [comment]
Similar issue on Debian 10.10.0 with code 1.58.1

dmesg:
```
[  140.140970] traps: code[4817] trap int3 ip:562271ff44f8 sp:7ffc89039180 error:0 in code[562271dc3000+5dfb000]
```

**Comment by deepak1556** [comment]
Please attach the output of `code --verbose`, thanks!

**Comment by alkorang** [comment]
> Please attach the output of `code --verbose`, thanks!

I downloaded `.tar.gz` version for 64-bit Linux. Here is the output of `./code --verbose`
```
[21270:0715/063631.517955:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /home/alkorang/.local/opt/VSCode/1.58.1/chrome-sandbox is owned by root and has mode 4755.
```

After I ran `sudo chown root:root ./chrome-sandbox && sudo chmod 4755 ./chrome-sandbox`, then `./code` works fine.

**Comment by deepak1556** [comment]
It is expected that setuid bits are not set for the tar package, can you provide the output `--verbose` from the rpm installation.

**Comment by alkorang** [comment]
> It is expected that setuid bits are not set for the tar package,

If this is an expected behavior, then printing the error message without `--verbose` would be very helpful.


> can you provide the output `--verbose` from the rpm installation.

Debian uses `.deb` file. I installed `./code_1.58.1-1626158276_amd64.deb` and it worked fine.

**Comment by deepak1556** [comment]
We don't have an easy way to warn about this issue as the runtime does the relevant checks. For now I will document the behavior and solution in the release notes.

**Comment by alkorang** [comment]
I thought it would be easy because it is checking whether the owner and permission of `chrome-sandbox` file is root and 4755. If not, `code` can simply print the link to this issue or the relase notes to warn it. Please let me know if I missed something.

**Comment by deepak1556** [comment]
Yeah the problem is that runtime will not always use the setuid helper, it is only fallback when the runtime cannot use namespace sandbox https://source.chromium.org/chromium/chromium/src/+/main:content/browser/zygote_host/zygote_host_impl_linux.cc;l=102-125 . So we don't want to print the warning based on the permission, I think it is fine just documenting this behavior in release notes and troubleshooting docs.

**Comment by alkorang** [comment]
I see. I thought about adding an option in configuration to enable/disable sandbox so that I don't need to use '--no-sandbox' option. But it may cause more issues, too, for example, sandbox is disabled in workspace configuration but enabled in global configuration, etc.

I agree that it'll be fine putting this in release notes and docs so that who download `.tar.gz` can find the solution.

**Comment by deepak1556** [comment]
Release notes have been updated and will be reflected in `1.59` notes.
