### ISSUE TITLE
Auto format on save doesn't work when quitting VS Code (and saving changes)

### ISSUE THREAD

**Issue by bgashler1** [Microsoft/vscode#12834]
- VSCode Version: Insiders
- OS Version: Mac OS X El Capitan

![problem - quit doesnt save](https://cloud.githubusercontent.com/assets/11839736/18894404/9ded7872-84c7-11e6-9b04-f12a25f3160d.gif)

Steps to Reproduce:

1. Have a file with unformatted code in a dirty state
2. Try to quit VS Code
3. Click save changes when prompted
4. Open VS Code and the previous file that had unformatted code.

Note that the code is still unformatted.

**Comment by jrieken** [comment]
We do that on purpose and it's documented here: https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L3795. The reasoning is that saving on close is critical since the OS might not gives us much time to shutdown. Therefore no save participant is being called here

**Comment by jrieken** [comment]
@bpasero On a second though this is also a change wrt trim whitespace. Before we would run that despite save on shutdown

**Comment by bpasero** [comment]
Yeah, tricky. Instead of me checking for shutdown and not running the participants, we could move this into the save participant to only run the main-side participants but not the extension host ones (https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/common/editors/textFileEditorModel.ts#L450)
