### ISSUE TITLE
Settings editor for enums should handle `undefined` for `default`

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#128367]
//cc @rzhao271 maybe this is a bug for the settings editor: if a setting is a `enum` without a `default`, shouldn't the dropdown indicate this by not showing the setting?

_Originally posted by @bpasero in https://github.com/microsoft/vscode/issues/128345#issuecomment-877578431_

**Comment by rzhao271** [comment]
It turns out there are quite a few features that fall under this category:

```
editor.gotoLocation.alternativeImplementationCommand
editor.gotoLocation.alternativeReferenceCommand
editor.defaultFormatter
editor.gotoLocation.alternativeImplementationCommand
editor.gotoLocation.alternativeReferenceCommand
editor.defaultFormatter
typescript.locale
terminal.integrated.defaultProfile.windows
git.autofetch
gitlens.fileAnnotations.command
gitlens.advanced.commitOrdering
jupyter.jupyterServerType
```

What I can do is create a default stand-in setting in this case.

**Comment by roblourens** [comment]
I don't understand, either the setting should be of type `string|undefined`, or the empty string should be part of the enum. Seems like the registration is wrong otherwise.

**Comment by rzhao271** [comment]
Turns out my filtering is wrong. I'll see what the other settings are doing. It seems `jupyter.jupyterServerType` might be within the scope of this issue, though.

**Comment by rzhao271** [comment]
`jupyter.jupyterServerType` is the only other setting within the scope of this issue. 

https://github.com/microsoft/vscode-jupyter/blob/33af7d138cd9763a684c735fcccb6fd35c811a8d/package.json#L1592

The `explorer.copyRelativePathSeparator` setting has been fixed separately, and the other settings declare default values, even if those default values are empty strings.

I can push in a fix that adds the default value to the options to select from, assuming that default value isn't currently one of the valid enum options, and that it is undefined. One advantage is that instead of having to ping extension authors who might forget to leave out the value, we can add in the fix on our side. But, that scenario brings up the following question:

Why can I create the following setting without a warning, and actually set `"emmet.hmm": "c"` in the OSS setting JSON file? @aeschli 
```json
"emmet.hmm": {
  "type": "string",
  "enum": ["a", "b"],
  "default": "c"
}
```

**Comment by roblourens** [comment]
I think that an empty item in a dropdown looks weird, but it's better than picking an arbitrary item when we don't know the default. We should fix this in any core settings or first party extension settings (like jupyter)
