### ISSUE TITLE
Remote extension will not work if it depends on a local UI one

### ISSUE THREAD

**Issue by tgodzik** [microsoft/vscode#128375]
Does this issue occur when all extensions are disabled?: No

- VS Code Version:  1.58.0
- OS Version: Windows + WSL2

Steps to Reproduce:

1. Install Metals extension.
2. Open a WSL workspace
3. Metals will be disabled because Scala syntax extension is disabled.

It seems that if we have a remote extension and it depends on one declared as `UI`, VS Code will now make it disabled. 
This basically, makes declaring `extensionKind` useless, since only workspace without it will work currently.

Any chance it can be fixed, or should we just make PR to remove `extensionKind ` from the Scala syntax extension?

Based on discussion in https://github.com/microsoft/vscode/issues/127067

**Comment by aeschli** [comment]
Yes, you can't have a (runtime) dependency from a workspace to a UI extension.

I assume you added the dependency so that when installing Metal, the user also gets `scala-lang.scala`.
For that you better use `"extensionPack": [ "scala-lang.scala" ]`

While we're at it. Yes, it would be better if `scala-lang.scala` doesn't define `extensionKind` and instead rely on our default behavior. The current setting (`ui`, `web`) will make it impossible to run it to `workspace` if necessary.

**Comment by tgodzik** [comment]
Any chance that this can be validated by `vsce` or at least have a better error? Something like `The extension depends on an UI extension, which will not work on a remote machine.`

**Comment by sandy081** [comment]
To confirm, this started happening after adding following support in VS Code in 1.58 - [Auto disable extensions if their dependencies are disabled](https://github.com/microsoft/vscode/issues/122448). It assumes that cross extension host dependencies are not supported and if extension is disabled (for eg., by extensionKind) on the host, then its dependents are too. So in this case, on wsl, since Scala extension is disabled (because it is UI kind), Metal extension is also disabled.

@aeschli Lets also get confirmation from @alexdima if the extensions can have cross host dependencies like this. As far as I remember we do not support this given that we do no support any cross ext host API to access other extensions API. So, it would be interesting to know how come the Metal extension got activated on remote (wsl) even when its dependency (Scala) is not enabled on the same host?

**Comment by sandy081** [comment]
@alexdima confirmed that we support cross host dependencies on following special conditions

- If the dependency is descriptive
- If the dependency supports `"api": "none"`

So, I think this dependency has to be supported. 

Hence tagging this as a candidate.
