### ISSUE TITLE
Search by file should show terminal tabs in the list

### ISSUE THREAD

**Issue by jarshwah** [microsoft/vscode#128445]
The recent feature of allowing terminal tabs to appear in the main editor window area is awesome! What I'd like to be able to do is activate those editor windows using the Search By File command prompt.

The `recently opened files` displays the terminal in the list:

![image](https://user-images.githubusercontent.com/541083/125214600-465b7680-e2fb-11eb-9f96-c9d01a9ca9b5.png)

But if I try to search by the terminal name, nothing shows up:

![image](https://user-images.githubusercontent.com/541083/125214616-5f642780-e2fb-11eb-9dfe-16e67228ec5b.png)

I often have around 5 or 6 terminals going at any one time for running tasks and debug sessions. Being able to find them with the file search tool will make navigating them so much easier.

**Comment by sandeshgit** [comment]
I wanted to create a similar issue but since you have already, I am adding some comments for clarification.

The issue title seems a bit misleading because Search By File command prompt  (**Ctrl + P**) already shows the open terminals in the list. The problem(unexpected behavior) occurs when you start typing the name of your terminal. The expected behavior is to be able to access our terminal by typing its name, just like we access other files.

Currently, the workout is to use arrow keys to access your terminal that is already shown in the list.

1. Activate Search By File command prompt with **Ctrl + P**.
2. Use the down arrow key to reach your _terminal opened in the editor area_.
3. Press Enter.

![Screenshot from 2021-07-13 00-55-12](https://user-images.githubusercontent.com/1939148/125343343-aee73980-e375-11eb-9dd0-3c39b4a28bfd.png)

But indeed, it would be great if we could also access the terminal by typing its name. That would be useful when too many fiels and too many terminals are open.

**Comment by roblourens** [comment]
And cc @TylerLeonhardt do you own this now?

**Comment by TylerLeonhardt** [comment]
This seems to happen for a few other custom editors. For example, if I open the markdown preview of a file, that doesn't show up when I search for files (only the normal text editor shows up).

So I'm wondering if something needs to be set up on the terminal editor side to make it show up in search results.

@Tyriar's Luna Paint files seem to show up in files (presumably because the files have some kind of associated file path) but yeah. @roblourens, I guess I technically own it but if you or @bpasero have any thoughts I'm all ears!

**Comment by Tyriar** [comment]
I noticed this too, it might be originally by design?

![image](https://user-images.githubusercontent.com/2193314/125457587-93f2c7f1-eaff-4ce8-8f2b-8e1be63b568d.png)

**Comment by roblourens** [comment]
Well originally there only were files really. I don't know whether it's really expected or not, but it feels weird that I see a list with open editors, but can't type to filter that list.

**Comment by TylerLeonhardt** [comment]
Agreed. Terminal tabs seem to be quite different than say... a custom editor.. like Luna Paint which does seem to show up just fine. @Tyriar could they fit the model of whatever custom editors do to show up in the picker? I'd rather not do something special in quick open just for terminals.

**Comment by roblourens** [comment]
I don't think this works for custom editors either

**Comment by TylerLeonhardt** [comment]
@roblourens it works for Luna Paint files though.

**Comment by Tyriar** [comment]
@TylerLeonhardt it's probably filtered based on scheme, the terminals are special and use `vscode-terminal://`

**Comment by TylerLeonhardt** [comment]
verification steps:

* have a terminal editor
* ctrl+p/cmd+p
* verify your terminal editor is there in recently opened
* try to search for your terminal editor by typing a character or two
* verify your terminal editor is still there in recently opened
