### ISSUE TITLE
Cmd+W keeps closing the window when no editor opens

### ISSUE THREAD

**Issue by herberthobregon** [microsoft/vscode#128409]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.57.1 and 1.58.0
Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
Date: 2021-06-17T13:28:32.912Z (3 wks ago)
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 20.4.0

Steps to Reproduce:

1. Open 3 editors 
2. `cmd+w` + `cmd+w` + `cmd+w` + `cmd+w` -> The instance is closed....

**Comment by Muchiachio** [comment]
You can remove close window shortcut, it's named `workbench.action.closeWindow`.

**Comment by herberthobregon** [comment]
@Muchiachio The problem is that it was a new feature that doesn't work in mac vscode

**Comment by vinniec** [comment]
This also happens when you close the last tab with the mouse (and not only with ctrl+w).
So maybe it is not related to the shortcut, but to an automatic closing behavior when closing the last tab.
It's really frustrating for me, because I often empty the editor of each tab before I start editing a new file, but then the editor closes and I have to open it again.

**Comment by bpasero** [comment]
This was an intentional revert: https://github.com/microsoft/vscode/commit/86262d37713432c3cc4366cc35304fd3632f8863#diff-1a994a7e09f68560e4dd9bc320aaf81e634d1611c69e2715b267f5e9050ec01b

**Comment by herberthobregon** [comment]
You are wrong, according to version v1.57 this behavior has changed, but it does not work when one puts it into practice

Check Release Notes:
https://code.visualstudio.com/updates/v1_57#_removed-cmdw-ctrlw-keybinding-to-close-window-when-no-editor-is-opened
