### ISSUE TITLE
Method call gets removed when apply suggestions 

### ISSUE THREAD

**Issue by Rishabhraghwendra18** [microsoft/vscode#128468]
Does this issue occur when all extensions are disabled?: No ( I don't think extensions have to do something with it )

- VS Code Version: 1.58.0
- OS Version: Ubuntu 20.04 LTS

Steps to Reproduce:

1. Make a recursive function in c++ . For eg inorder traversal of tree
2. Take a look at this:
![bug](https://user-images.githubusercontent.com/43534227/125280109-55a9e680-e332-11eb-84ec-105cdf418192.gif)
As I applied `left` from suggestions the recursive call to function `traverse` , function name gets deleted . So I have to rewrite the function name.

Suggestion :
It will be great if we apply suggestions on that place - where cursor is pointing without deleting the next word.

**Comment by jrieken** [comment]
You can configure your default behavior for that with `"editor.suggest.insertMode"`. Tho, extensions can also customize this. Still, `Tab/Enter` will run the default and `Shift+Tab/Enter` the alternative (assuming there is any). I would suggest to turn on this setting `editor.suggest.showStatusBar` because the suggest widget will then show the available options, like so

<img width="409" alt="Screen Shot 2021-07-12 at 14 16 04" src="https://user-images.githubusercontent.com/1794099/125286151-bed22f80-e31b-11eb-9f88-299e5bd3e0e3.png">

**Comment by Rishabhraghwendra18** [comment]
@jrieken ok..Thanks alot
