### ISSUE TITLE
Multiline setting inputbox doesn't update during sudden resizes

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#128563]
On Insiders (Windows):

Steps to Reproduce:

1. Add the following test setting to the Emmet extension
```json
        "emmet.multiline": {
          "type": "string",
          "editPresentation": "multilineText",
          "default": ""
        }
```
2. Navigate to the setting editor, and type `emmet` in the search box
3. Scroll down until you see the new multiline setting
4. Press enter a few times and immediately press F11 afterwards
5. 🐛 The setting editor layout glitches

![glitch](https://user-images.githubusercontent.com/7199958/125501304-0aa1b4d6-ed40-4c56-bd50-e7fdc3c654b3.png)

I notice that if I add the following code into the multiline text setting renderer, the resize is eventually handled, but there is a flicker in between:

```ts
this._layoutService.onDidLayout(() => {
	if (this.cachedHeight) {
		setTimeout(() => {
			this.reportHeight(dataElement, this.cachedHeight); // calls updateElementHeight in another listener
		}, 200);
	}
}));
```

I think it either has to do with 

https://github.com/microsoft/vscode/blob/6f9483bab6b95396cf58ff188b48d22ae18f7da6/src/vs/base/browser/ui/list/listView.ts#L1293

or with 

https://github.com/microsoft/vscode/blob/6f9483bab6b95396cf58ff188b48d22ae18f7da6/src/vs/base/browser/ui/inputbox/inputBox.ts#L593

In particular, for the input box, I'm not sure how the two cached heights interact in that method.

**Comment by joaomoreno** [comment]
I suggest @roblourens looks into it. If you find there's a problem with the list itself let me know. 👌

**Comment by roblourens** [comment]
Here's what's happening:

1. I type newlines in the text control and change its height
  1a. At some point, we commit the edit and write to the config service, which will eventually update the element's value
2. The multiline renderer fires an event that results in calling `updateElementHeight`
3. Switch to fullscreen
4. The list rerenders everything and probes the height of the multiline element. But at this point, the element value has not yet been updated so the list gets the height with the wrong value
5. The value changes, the list is rerendered, but it thinks it doesn't have to probe the element height again at this point

**Comment by roblourens** [comment]
This will get fixed when we call `setChildren` again, but we delay that until the control is not focused anymore to avoid losing focus on the editable control. We can't call rerender at this point to reset the cached last render width for the same reason. We just have to make sure that the element value is actually correct. I think that is the right fix. Will just do it for string settings now since I'm not sure that the data type will be correct at this point for other setting types.

Another thing is that we should probably not be measuring the setting and calling `updateElementHeight` because then the setting's height is measured by the list and also by the settings code. This isn't causing an issue as far as I can tell but the delegate has an incorrect cached height so it seems like it could. It would help if we could call `updateElementHeight` with `undefined` to prompt the list to reprobe the height, does that make sense @joaomoreno? 

And also, I think I shouldn't be relying on list refreshing to rerender settings when their values change. Have been thinking about this for a long time, but I think that I should only call `setChildren` when the config schema changes, but when setting values change, just have rendered items listen to those changes directly and update themselves without involving the list, which causes it to lose focus and leads to issues.

**Comment by joaomoreno** [comment]
> Another thing is that we should probably not be measuring the setting and calling `updateElementHeight` because then the setting's height is measured by the list and also by the settings code. This isn't causing an issue as far as I can tell but the delegate has an incorrect cached height so it seems like it could. It would help if we could call `updateElementHeight` with `undefined` to prompt the list to reprobe the height, does that make sense @joaomoreno?

Yeah I think that makes sense, given dynamic heights are enabled.
