### ISSUE TITLE
Programmatically call debugger ?

### ISSUE THREAD

**Issue by arafato** [Microsoft/vscode#1286]
Hello everybody, 

is it possible to programmatically call the debugger, i.e., is the node-debug adapter exposed as via an API? Thanks!

Best regards
--Oliver.

**Comment by weinand** [comment]
@arafato it is possible to programmatically call the debugger but we do not (yet) have an official client library for this (because VS Code is the only client). But you can find the code for talking to debug adapters in VS Code. See rawDebugSession.ts. [Here](https://code.visualstudio.com/docs/extensionAPI/api-debugging) is an overview of the API from an implementer's perspective.
