### ISSUE TITLE
Fails to start when VSCode installation is symlinked from a different drive

### ISSUE THREAD

**Issue by ZEDCWT** [microsoft/vscode#128725]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.58.1
- OS Version: Windows 10.0.19043.1083

Steps to Reproduce:

1. On Windows, prepare folders with the following structure (or similar)
```txt
C:\
|---- Playground
      |---- Root
D:\
|---- Root <JUNCTION/SYMLINKD> [C:\Playground\Root]
      |---- VSCode
```
To make a junction link, use this command `mklink /J D:\Root C:\Playground\Root`, or change `/J` to `/D` to create symlink
And VSCode is installed/unpacked at D:\Root\VSCode
2. Start VSCode with image path `D:\Root\VSCode\Code.exe`, and it stuck on the blank page forever. And if start with image path 
`C:\Playground\Root\VSCode\Code.exe`, it runs normally

By using `Process Monitor`, I noticed the following activities
![PathNotFound](https://user-images.githubusercontent.com/7867810/125747014-9ef44b6a-4866-4d1c-bdb0-9e9c788f4e44.png)
It seems that it has trouble dealing with symlink paths that producing a wrong one `D:\Playground\Root\VSCode\resources\app\node\modules.asar`

Also, this symlink environment works on 1.57.1 and before but not on 1.58.0/1

**Comment by leoniDEV** [comment]
Same issue here with this environment.

Version: 1.59.0-insider (user setup)
Commit: 50b3811fdc5b5c80ca516a2edfffedcbd464b033
Date: 2021-07-15T05:13:58.348Z
Electron: 13.1.6
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT x64 10.0.22000

**Comment by deepak1556** [comment]
Thanks for the repro steps, this is a variation of https://github.com/microsoft/vscode/issues/126533 but only when the symlinks are on different drives. Will look into it.

**Comment by deepak1556** [comment]
The problem here is that node_modules path are messed up because of https://github.com/microsoft/vscode/blob/14de627cf237d4c6d9375fa8d411432eae63858a/src/bootstrap.js#L58-L61

The above condition should normally work fine even for symlinks from different drives but if `__dirname` is incorrect then things could go wrong horribly. That exactly what happened, electron does not set the correct value of `__dirname` if the renderer protocol is not `file` https://github.com/electron/electron/blob/c5ad7ed0cd05fe46aefedd0c3dbed580d6a5ce20/lib/renderer/init.ts#L118-L147

**Comment by deepak1556** [comment]
As temporary workaround affected users can do the following steps,

1) Open `%USERPROFILE%\.vscode-insiders\argv.json` or `%USERPROFILE%\.vscode\argv.json` depending on the insiders or stable version.
2) Add `"enable-browser-code-loading": false` in the json structure
3) Restart vscode.

**Comment by bpasero** [comment]
I wonder if a pragmatic fix here could be to put both the lowercase and uppercase variant of the drive letter into the array and not rely on `__dirname` at all.

**Comment by bpasero** [comment]
Hm, so the code using `__dirname` came in from @alexdima via https://github.com/microsoft/vscode/commit/c9dc040ad77ebedc10e815ed9fb5fcc3ae92d630 but unfortunately it lacks a description as to why this change was made. 

I can only speculate that the intent is to ensure the drive letter casing matches the one node.js uses internally (as obtained from `__dirname`). But if that is true, my suggestion of simply pushing both case variants into the paths array seems dangerous because we end up potentially using the "wrong" casing in the paths array as we did before.

As for loading files from disk I would assume that it really doesn't matter for node.js whether the drive letter casing is uppercase or lowercase, both should work.

I conclude that we should wait for Alex to come back and comment on this before making changes. Users that are suffering from this issue will have to remain on the stable version until we figured this out properly.

**Comment by bpasero** [comment]
As a mitigation I will push a change such as this:

```ts
if (process.platform === 'win32') {
	const nodejsDriveLetter = __dirname.substr(0, 1);
	const vscodeDriveLetter = appRoot.substr(0, 1);
	if (nodejsDriveLetter.toLowerCase() === vscodeDriveLetter.toLowerCase()) {
		NODE_MODULES_PATH = nodejsDriveLetter + NODE_MODULES_PATH.substr(1);
	}
}
```

To ensure we are not accidentally picking the wrong drive letter.

**Comment by deepak1556** [comment]
I believe `module.paths` generated in the renderer by https://github.com/electron/electron/blob/c5ad7ed0cd05fe46aefedd0c3dbed580d6a5ce20/lib/renderer/init.ts#L118-L138 contained drive letters with mixed cases because of this very old bug https://github.com/electron/electron/issues/1289#issuecomment-85535247 and I think @alexdima wanted to fix the drive casing based on `__dirname` so that we are able to match here https://github.com/microsoft/vscode/blob/edee5caf4fd67d960512852489d959587994d831/src/bootstrap.js#L83-L87

Lets wait on @alexdima for confirmation and I think we might be able to remove that condition all together as we always add asar path for `vscode-file` and also I am no longer able to repro the mixed cases from that very old nodejs bug. So it might be a completely different issue that was addressed in https://github.com/microsoft/vscode/commit/c9dc040ad77ebedc10e815ed9fb5fcc3ae92d630
