### ISSUE TITLE
enablePreviewFromQuickOpen not working as expected—Quick Open files ALWAYS open in preview

### ISSUE THREAD

**Issue by ZLevine** [microsoft/vscode#128755]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.58.1
- OS Version: Darwin x64 20.5.0

Steps to Reproduce:

1. Specify the following config values for User and workspace:

```json
{
    "workbench.editor.enablePreview": true,
    "workbench.editor.enablePreviewFromQuickOpen": false,
    "workbench.editor.enablePreviewFromCodeNavigation": false
}
```

2. Press CMD-P (Mac) or CTRL-P (Windows) to launch Quick Open
3. Search for a file, highlight it with your arrow keys, and press Enter
4. Observe that the file opens in Preview Mode (it's italicized and closes when you open another file). Instead, it should open in Edit mode.
5. Note: If you edit a Preview file or double-click its tab, it exits Preview mode and enters Edit mode.

Unfortunately, this problem is extremely disruptive. In order to keep multiple files open with Preview enabled, I have to edit each file or use my mouse to double-click. This is majorly disruptive to a keyboard-centric workflow.

I _think_ this behavior started happening with the most recent release.

**Comment by garyking** [comment]
I can confirm that this started with the 1.58. I've been experiencing this since it was released. So I downgraded for now. I'm on a Mac too.

Cmd-P to Quick Open a file. For me, it depends on the project; in some, it opens in preview mode, and in others, in edit mode (as it should). Or perhaps it also is affected by the file? So, in any case, about half the time, it works correctly (opening in edit mode).

**Comment by levymetal** [comment]
I've observed that if you leave the search box blank it behaves as expected. However, if you type into the search box the files then open in preview instead of becoming pinned.

Looking at the diff between 1.57.1 and 1.58 there appear to have been some changes to `anythingQuickAccess.ts`. I have a feeling it has something to do with this commit: https://github.com/microsoft/vscode/commit/9b984212c3eec1d97404dcd946ad8f77d7a961d9#diff-956698454aff9655b3fd776c230ac7a7471b6a23cf01f64f1f817ad2d8d894f8

`editorOptions` isn't respected within the `URI.isUri(resourceOrEditor)` condition.

**Comment by aindr** [comment]
VS Code version: 1.58.2
OS version: Microsoft Windows [Version 10.0.19043.1110]

In my case files are also opened in Preview mode, even though for Quick Open this is disabled by default.

![preview](https://user-images.githubusercontent.com/86878338/126037768-df830281-cfe6-4e13-8213-c4ee196da0eb.gif)

**Comment by ZLevine** [comment]
Can confirm this issue still exists in the latest 1.58.2

**Comment by TylerLeonhardt** [comment]
Nice catch @levymetal! This appears to have been a typo and should have been `options: editorOptions` instead of just `options`. I've fixed that now. @bpasero lmk if that was not correct but I'm pretty sure it is.

And if you all can help confirm the fix in Insiders tomorrow that would be great 🙏

**Comment by bpasero** [comment]
Thanks for the fix, LGTM 👍
