### ISSUE TITLE
`vscode.open` doesn't resolve override anymore

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#128756]
@connor4312 Pointed out that given a resource which has custom editor `vscode.open` no longer resolves to that custom editor. This is because of the recent work in #124498 which involved disabling overrides in the `codeEditorService`. vscode.open just happens to use that exact service leading to only text editors being opened now. The current workaround for extensions that know what editor they want to open is to use `vscode.commands.executeCommand('vscode.openWith', resource, 'ID_OF_WANTED_EDITOR');` to open the specific editor. However, a solution to tell VS code to resolve an editor without knowing which one is wanted is needed. I'm hesitant to revert my above change as this would just be trading one bug for another.

**Comment by bpasero** [comment]
Arguably, `vscode.open` should really not be using `ICodeEditorService`. The idea behind this service was to use it only for code editor contributions for some corner cases (e.g. to prevent opening a new editor when invoking some control in a diff editor).

It might be too late now though to change this because if an extension triggers `vscode.open` from within a diff editor somehow, the behaviour would regress.

**Comment by lramos15** [comment]
@bpasero Unfortunately it using the `ICodeEditorService` which makes fixing https://github.com/microsoft/vscode/issues/124498 a lot harder because I can't blatantly disable overrides in that service to fix things like the outline.

**Comment by bpasero** [comment]
Yeah I understand. The intent of that service was to be used only from within code that knows it executes from within an opened editor.
