### ISSUE TITLE
[Regression] extensionDependencies broken in WSL mode

### ISSUE THREAD

**Issue by Stanzilla** [microsoft/vscode#128888]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.58.2
- OS Version: Windows 10 21H2

Steps to Reproduce:

1. Install https://marketplace.visualstudio.com/items?itemName=ManticoreGames.vscode-core
2. Open a Lua file

My extension depends on another extension (https://marketplace.visualstudio.com/items?itemName=sumneko.lua) and used to load it just fine, after the update to 1.58.2 it only works in Windows mode but not in WSL. In WSL I get the following error 

![image](https://user-images.githubusercontent.com/75278/126018786-3a349a73-050e-43ef-a37a-004f2842100b.png)

Looks like this regressed in https://github.com/microsoft/vscode/issues/128375

**Comment by sandy081** [comment]
I doubt this used to work ever when `ManticoreGames.vscode-core` is installed in Windows and its dependency `sumneko.lua` is installed on WSL. You have to have both extensions installed on WSL to work. But, since you tagged your `ManticoreGames.vscode-core` extension as string ui extension kind in `package.json` eg:

```json
"extensionKind": [
		"ui"
	],
```

one cannot install `ManticoreGames.vscode-core` extension on WSL - See https://code.visualstudio.com/api/advanced-topics/remote-extensions#architecture-and-extension-kinds for more information.

Any reason why this extension is tagged only `ui` kind?

**Comment by Stanzilla** [comment]
No reason, I was of the opinion that that was correct. And it did work..but I can change it.

**Comment by Stanzilla** [comment]
Updated my extension to `["workspace", "ui"]` and it works again now.
