### ISSUE TITLE
Improve dirty terminal editor wording

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#128880]
I think we need hooks in editor land for this. Save should not be shown as an option.

![image](https://user-images.githubusercontent.com/2193314/126008632-ec516f1e-abaa-434e-bdef-91a438e711d2.png)

**Comment by Tyriar** [comment]
The area owners probably need to help here as it's not the easiest UX problem to work through; what do we do with the save button? What if there are editors and terminals?

**Comment by Tyriar** [comment]
Feedback from UX sync:

- It's not a dirty file, so don't mark it as dirty - opinions are somewhat split on this
- Maybe have a different type of indicator, but probably not needed. I don't think other terminals have indicators for child processes
- Have a totally separate close dialog for terminals in parts/terminal

**Comment by lramos15** [comment]
> * Have a totally separate close dialog for terminals in parts/terminal

Probably better to just have a separate part for terminal editors as we don't want to double dialog people.

Also I'm going to move this work to August as Ben is out and I don't want to make any large changes to editor closing without him around to review.

**Comment by Tyriar** [comment]
@lramos15 well there is already a terminal-specific shutdown veto that may show up as well if you opt into the setting. We could consider somehow merging those two if possible but closing a single terminal would never double prompt

**Comment by bpasero** [comment]
> It's not a dirty file, so don't mark it as dirty - opinions are somewhat split on this

At first I felt the same, we shouldn't use the same dirty indication as for file based editors, especially since on macOS we mark a window as "edited" for dirty editors, but then I noticed how macOS does the same for terminals when a process is running:

![image](https://user-images.githubusercontent.com/900690/127865149-006a0d6d-9c78-40de-9a41-a0c694d98940.png)

And closing that tab shows a dialog:

![image](https://user-images.githubusercontent.com/900690/127865211-aaefb2bd-0760-442d-9ec7-7f5fdad25ff7.png)

So maybe using the same dirty indication is not so bad after all.

However I think showing a combined dialog might not be so user friendly, so I would probably go for another modal dialog after having dealt with dirty editors. 

I think having a UX discussion with some proposals would help to move forward before we make a decision and implement this.
