### ISSUE TITLE
Remove "Toggle Tab Key Moves Focus" 

### ISSUE THREAD

**Issue by strowk** [microsoft/vscode#128858]
I would like that feature that enables moving focus using Tab key would be disabled by default. Every couple weeks I accidentally press ctrl+m and have to google how to make Tab button working again. This feature is useless, I am 100 percent sure everyone is using Tab in both editor and Terminal for completely different purpose. This have to be disabled by default to improve overall usability VSCode.

**Comment by Tyriar** [comment]
It's a very important accessibility feature, so we can't remove it by default.

You can just remove the keybinding if you accidentally hit it:

```
{ "key": "ctrl+m", "command": "-editor.action.toggleTabFocusMode" }
```

**Comment by James-Livesey** [comment]
Tab Moves Focus is a feature implemented for accessibility reasons, and allows keyboard users to navigate VSCode's various UI elements by using the <kbd>Tab</kbd> key to move onto the next item (<kbd>Shift</kbd> + <kbd>Tab</kbd> goes to the last item). Otherwise, keyboard focus would be trapped in the editor until <kbd>Ctrl</kbd> + <kbd>M</kbd> is pressed.

Removing this option entirely could break the workflow of those who use it. However, I agree that the accidental pressing of <kbd>Ctrl</kbd> + <kbd>M</kbd> is an issue for many (even myself, sometimes); but luckily there is a way to disable it entirely.

Go to **File** > **Preferences** > **Keyboard Shortcuts**, then search for "Tab Moves Focus", and right-click the shown entry for the keyboard shortcut. Then press **Remove Keybinding**. You should then no longer have this issue.
