### ISSUE TITLE
vs CODE Starting issue ...not compete start

### ISSUE THREAD

**Issue by Parveenparta** [microsoft/vscode#128837]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1.
2.

**Comment by Parveenparta** [comment]
Vs code not complete start

**Comment by James-Livesey** [comment]
@Parveenparta Please edit your issue to fill in the templated details, otherwise we won't know how to help you.

If you have already fixed this issue, please let us know what went wrong and how you fixed it, and then close the issue. This is to help others who may have the same problem as you.

'not complete start' is too vague and there could be a variety of reasons as to why this is happening. Please be more specific as to
* what happens when you try to launch VSCode, and also include the version number of VSCode you're running; in addition to 
* the operating system you use.

Additionally,
* try launching VSCode from the terminal and showing us your logs here so we can more easily diagnose the problem; or
* reinstall VSCode to see if the issue still persists.

Thanks for the report, though!
