### ISSUE TITLE
Code keeps auto-attaching debugger

### ISSUE THREAD

**Issue by appix-CH** [microsoft/vscode#128846]
Issue Type: <b>Bug</b>

The debugger suddenly keeps automatically attaching itself to **every single** npm script making it impossible to work! The "Debug: Toggle Auto Attach" is set to "Disabled" but it makes no difference. Rebooting doesn't help. Updating doesn't help.

The scripts run extremely slowly, detaching works sometimes but sometimes it just kills the process.

VS Code version: Code 1.58.1 (2aeda6b18e13c4f4f9edf6667158a6b8d408874b, 2021-07-13T06:58:28.115Z)
OS version: Windows_NT x64 10.0.16299
Restricted Mode: No

**Comment by appix-CH** [comment]
Sorry about that, thought it might have been previously reported.

Here's a recording of me first confirming that the "Toggle Auto Attach" feature (which I **assume** might be the cause) is set to "Disabled" and then running an NPM task.

I've already tried commenting out all configurations in `./vscode/launch.json`, updating, restarting, rebooting etc. (all the standard stuff).
![recording](https://user-images.githubusercontent.com/24225096/125979098-fa427bce-e36a-4d1a-849e-ba0c0dc134b9.gif)

**Comment by connor4312** [comment]
Thanks, please try:

1. Toggling auto attach to any thing other than disabled
2. Toggle it back to disabled
3. There should be a ⚠️ icon in the top right of the terminal asking you to relaunch it (if you've interacted with it, otherwise it'll relaunch automatically). Do so.
4. If the issue still happens, run the `Developer: Toggle Developer Tools` command and check the console for any errors that might have happened
