### ISSUE TITLE
The git extension takes a long time to launch on my Windows machine

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#129073]
Version: 1.59.0
Commit: Unknown
Date: Unknown
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT x64 10.0.19042

![image](https://user-images.githubusercontent.com/2193314/126392501-2e569d3f-aea9-4de4-943e-4d1dcfe85560.png)

![image](https://user-images.githubusercontent.com/2193314/126392263-d8813c27-d443-4ed9-9e59-8946fbd40c4c.png)

[exthost-8cfb4e.zip](https://github.com/microsoft/vscode/files/6851092/exthost-8cfb4e.zip)

**Comment by misolori** [comment]
FWIW, I've also experienced a slowness with git when I open a folder. It takes at least 5-10s to initialize and then load. And this is on the Mac (M1). What's the best way to provide logs?

**Comment by joaomoreno** [comment]
This should alleviate: https://github.com/microsoft/vscode/issues/120089

But the fact that spawn is slow on Electron/Node.JS is old old old. I'll leave that for @deepak1556

**Comment by joaomoreno** [comment]
Also cc @eamodio

**Comment by deepak1556** [comment]
@tyriar please download the latest version of https://github.com/google/UIforETW/releases and follow the steps in the recording to capture an event trace. Couple of gotchas:

* Make sure to change the name of the `Heap-profiled processes` in the settings based on the application (code.exe or code-insiders.exe or Code - OSS.exe)
* If the steps to repro the issue are not reliable, you can just start the trace app and leave it running in the background. It uses circular buffers to store data, so you can save trace when the issue is encountered.
* The final trace file will contain sensitive data (key logging if used in full trace mode), so please send it to Deepak.Mohan@microsoft.com instead of attaching here.

Recording: https://slack-files.com/T0HLXG4VA-F028QMM5LTX-959db0e39d

**Comment by deepak1556** [comment]
@misolori are you seeing the issue with OSS or bundled application ?

**Comment by misolori** [comment]
I'm seeing this on the Mac w/ our bundled application. Here's a screen recording that shows git not kicking it until about ~10s


https://user-images.githubusercontent.com/35271042/126570430-26f81a65-ada9-4633-91bb-66d4bdb1fce7.mp4

**Comment by deepak1556** [comment]
@misolori can you follow https://github.com/microsoft/vscode/wiki/Performance-Issues#profile-the-running-extensions to get a profile of the git extension.
