### ISSUE TITLE
Override gitDecoration.modifiedResourceForeground for active tab

### ISSUE THREAD

**Issue by SergeyBeloglazovRL** [microsoft/vscode#129033]
If a file is modified and **workbench.editor.decorations.colors** is true (it's true by default since some release), the color of the file name in editor tab doesn't change for active tab. It's confusing. 
I can hardly differ an active file from modified file in my Dark+ theme. The active file name is white, a changed file name is orange.
![изображение](https://user-images.githubusercontent.com/67962205/126290160-25729126-bcc7-4cc6-a0c3-ba9c9d34ae4c.png)

I tried to set **gitDecoration.modifiedResourceForeground** to a less contrast value, but the active tab keeps this color. It doesn't become white.
![изображение](https://user-images.githubusercontent.com/67962205/126290215-2aad2424-3cd4-49b5-aa10-fb6b17e642dc.png)
So I can hardly find an active file too.

I suggest a separate option for active modified file color or active tab color have to override **gitDecoration.modifiedResourceForeground** value.

**Comment by misolori** [comment]
This is because the git decorators have a higher precedence over the active file color (we also do this in the explorer). I don't think we'd want to introduce a "active modified foreground" that has git variations as that would get complicated. Have you tried using the `tab.activeBorderTop` color token to make the active tab stand out?

<img width="403" alt="CleanShot 2021-09-15 at 15 45 59@2x" src="https://user-images.githubusercontent.com/35271042/133519665-5374f96d-05aa-4342-8b0b-4847d632666b.png">

cc @bpasero for feedback on active tab text color vs git colors

**Comment by SergeyBeloglazovRL** [comment]
Thank you @misolori! I've set `tab.activeBorderTop` value. It seems to be helpful. I will try using it.
