### ISSUE TITLE
Crashing worker  in web extension host brings down the entire extension host

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#129194]
Steps to Reproduce:

1. `yo code --insiders` and create a web extension
2. In the main `extension.ts`, spawn a worker:

```ts
declare const Worker: any;

export function activate(context: vscode.ExtensionContext) {
    const workWorkWork = new Worker(vscode.Uri.joinPath(context.extensionUri, 'crashy-worker.js'));
}
```

3. Create `crashy-worker.js` at the top level of the extension:

```js
throw new Error('Worker error') 
```

4. F5 and then activate the extension

**Bug**
The worker exception brings down the entire extension host. While debugging with F5, this causes the entire window to close without any useful error logs

**Comment by jrieken** [comment]
Something similar happens even without a dedicated worker, e.g have the snippet below and see the extension host terminate

```ts
vscode.commands.registerCommand('web-ext.helloWorld', () => {
	setTimeout(() => { throw new Error('RANDOM'); });
	console.log('WAIT for it');
});
```

This is because the onerror-handler is very strict simply triggers an exit, see https://github.com/microsoft/vscode/blob/d18e54f820f87df1fa9f9bdd658b7f824c756f8d/src/vs/workbench/services/extensions/browser/webWorkerExtensionHost.ts#L287-L290

I will push a change to only terminate the web extension host when uncaught errors happen during worker-start
