### ISSUE TITLE
Overview ruler slightly shifted

### ISSUE THREAD

**Issue by sadSader** [microsoft/vscode#129122]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.58.2
c3f126316369cd610563c75b1b1725e0679adfb3
x64

- OS Version: Linux  5.8.0-2.g9bc0044-default

Steps to Reproduce:

1. Large file (I tested with 3000 lines)
2. Some colored marks on overview ruler are slightly shifted relatively to editor

Colored text at the very top of editor
![image](https://user-images.githubusercontent.com/49253162/126532120-b0fe76e8-21f5-4b8f-a9ab-9055d19a5cdb.png)
Ruler renders it as partially seen
![image](https://user-images.githubusercontent.com/49253162/126532343-a9fd453a-184e-40f8-88c6-a8a3335382f0.png)

Text at the end 
![image](https://user-images.githubusercontent.com/49253162/126533031-bef2d8dd-ae9a-47ed-8205-f18cdc6c6a5d.png)

Ruler shows in middle of seen area
![image](https://user-images.githubusercontent.com/49253162/126533551-bd33c6a4-9f44-4e35-9330-d482a0618250.png)

Text not seen
![image](https://user-images.githubusercontent.com/49253162/126533146-0a68f7e6-fd21-4946-a0bd-b2165e6a6931.png)
Ruler still shows in seen area
![image](https://user-images.githubusercontent.com/49253162/126533427-3ad6da69-3a2d-49bb-843a-ed000b62616e.png)

**Comment by alexdima** [comment]
Yes, this is by design. The scrollbar slider is artificially increased to allow to be gripped with the mouse. This is pretty standard behavior of scrollbars... all the scrollbars I have seen, native or otherwise have a min height (vertical ones) / min width (horizontal ones)... I agree this becomes confusing for very large files, but the only alternative I can think of is to remove this minimum size. 

To further explain why the viewport is not always in the center of the enlarged slider. The enlargement works like this in order to make mouse operations smooth:
* the current viewport is at the top of the slider when the slider is at the top of the file
* the current viewport is at the center of the slider when the slider is at the center of the file
* the current viewport is at the bottom of the slider when the slider is at the bottom of the file

If you have ideas about how to improve this, I am happy to hear about them.
