### ISSUE TITLE
Provide extension authors with a better way to ask for donations than using notification toasts

### ISSUE THREAD

**Issue by karai17** [microsoft/vscode#129199]
Today when I launched vscode I was greeted by a solicitation for donation from an extension. Now, this in and of itself is no cause for alarm, but the method in which this was done is. The extension is exploiting error notifications to force users to see and interact with a message window that does not go away on its own, that begs for money. He has even created a library for other extension developers to follow suit.

https://github.com/fabiospampinato/vscode-beggar

I find this behaviour from an extension to be incredibly intrusive and flat out unacceptable. This is clearly an exploit of an important feature of vscode. I quite frankly do not want to see ads or solicitations inside my productivity software. Below is a link to the extension in question, and a bit of back and forth I had with the developer in the reviews.

https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-todo-plus&ssr=false#review-details

I believe this behaviour to be an exploit and hope that it can be fixed so this kind of thing does not spread.

**Comment by fabiospampinato** [comment]
Author of the notification thing here. I'm happy to switch to an info notification if the maintainers would prefer that, I explicitly picked the error notification because the other ones disappear pretty quickly without giving you enough of a chance to interact with them, and the message displayed in those notifications is kind of long already, so I don't think you really want to show it to people multiple times if at all possible, like if somebody starts reading it, and doesn't manage to interact with the notification in time and the thing disappears in my opinion that's a terrible user experience.

I'd like to note also that vscode itself uses permanent info notifications when updates are available, but they don't seem to be exposed to extensions, so clearly the maintainers see some usefulness in sticky notifications, so perhaps that capability should just be exposed to extensions.

> He has even created a library for other extension developers to follow suit.

I'm not sure what's your point, open-source is my default, unless there's a reason not to open-source the code that I write I do it. Maybe you don't like open-source or you think that's harmful somehow, I'm not sure.

**Comment by karai17** [comment]
I don't understand how you can come to the conclusion that I don't like open source after I've already explicitly told you I am also an open source developer. The entire point of my concern here isn't that your code is open source, nor is it that you would like to recieve donations for it. It is, and has been, specifically that you are hijacking features inside of vscode and using them for unintended purposes. The ONLY thing that should generate an error notification is an error. If this is not obvious, I cannot simplify any further. Your use of error notifications is expoitative. The reason why info notifications disappear is because they should. Errors should be sticky because errors are significant and should demand your attention. Info such as soliciting donations (which I am not against in and of itself!!!) should *request* your attention. If you want to sell your addons, then sell them. If you want to request donations, *request* them. You're mixing two concepts here and it's distasteful, to say the least.

**Comment by bpasero** [comment]
Thanks for bringing this up. I have changed the title and labels a bit and would like to ask some more people for input:
* @misolori who is our UX lead and who is exploring more ways for extensions to signal things like updates or release notes (also a notification decision tree: https://github.com/microsoft/vscode/issues/119463#issuecomment-825663289)
* @eamodio as author of GitLens who might have some insights how GitLens is dealing with this
* @chrisdias @digitarald @isidorn fyi

**Comment by misolori** [comment]
We also have https://github.com/microsoft/vscode/issues/107482 for integrating with GitHub Sponsors

**Comment by fabiospampinato** [comment]
> We also have #107482 for integrating with GitHub Sponsors

That's a no brainer IMO, but also kind of orthogonal: a sponsor button there is important but will most probably be ignored, while asking people for a donation after they have been using an extension for a long time is a completely different value proposition in my opinion. 

It'd be cool if vscode monitored this kind of stuff and nudged people to contribute more smartly, like maybe twice a year or something vscode could tell the user: "Hey you've called commands provided by these extensions X times, and the extensions are asking for donations, would you like to contribute"? 

It'd be super cool also if one could donate once or in a subscription and vscode could redistribute that money based on the usage somebody does of each extension. Kinda like [SetApp](https://setapp.com/) but for vscode extensions rather than macOS apps.

**Comment by ithinkandicode** [comment]
I had one of these notifications today and it derailed my focus. I can't see a way to disable them, without disabling the extension (which I did, nobody likes popups).

> It'd be cool if vscode monitored this kind of stuff and nudged people to contribute more smartly [...]

As long as there's an option to disable them, with an option available from the popup itself. If I'm coding, I would like to focus on the code. There are enough things in life grabbing for attention already.

**Comment by fabiospampinato** [comment]
> I can't see a way to disable them, without disabling the extension (which I did, nobody likes popups).

Clicking on either button should tell the extension to never show that notification again. I should probably add some kind of limit in case a notification is dismissed more than some threshold amount of times, it gets trickier when considering multiple windows though.

**Comment by ithinkandicode** [comment]
> Clicking on either button should tell the extension to never show that notification again. I should probably add some kind of limit in case a notification is dismissed [...]

I think we're best keeping the focus on VS Code, rather than individual extensions.

As @misolori said, there's an active proposal for a non-intrusive approach:

> We also have #107482 for integrating with GitHub Sponsors

But if extension developers still want to show intrusive notices, then @karai17 's proposal in the title of this issue is a good one.

Personally, I don't want more notifications in my code editor, but I especially don't want extensions to hijack error notices to show donations begs, regardless of the justification. If extension developers have started to take this approach, it's worthwhile providing an official implementation that can give control back to users and allow them to hide the notices globally.

**Comment by manifestinteractive** [comment]
You can add this to your settings.json file to disabled `vscode-beggar` in ALL extensions according to their https://github.com/fabiospampinato/vscode-beggar#usage docs

```
"donations.disablePrompt": true
```

**Comment by isidorn** [comment]
We have launched support for sponsors. I suggest you try that out. More details in this announcement. Thank you
https://github.com/microsoft/vscode-discussions/discussions/14
