### ISSUE TITLE
VS Code is not displaying correct italic font.

### ISSUE THREAD

**Issue by nisarg-ujjainkar** [microsoft/vscode#129111]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.58.2
- OS Version: Windows 11 build 22000.71

Steps to Reproduce:

1. Use Cascadia Code (or any other font that has a separate italic font) as your default font.
2. Check of it displays the font correctly.

Comment: Earlier, VS Code was displaying the italic font correctly. Either it's a bug in the VS Code itself or maybe it's a windows 11 thing.

**Comment by IllusionMH** [comment]
/needsMoreInfo

Is it in editor or it terminal?

Please provide values of `editor.fontFamily` and `terminal.integrated.fontFamily`?
How was Cascadia Code installed (manually or with Windows Terminal, do you have WT installed)? It doesn't have "separate" italic font, it's merged with regular if both installed.
Also note that Cascadia Code in latest release has separate display features for italics and cursive.

**Comment by nisarg-ujjainkar** [comment]
editor.fontFamily : "Cascadia Code"
terminal.integrated.fontFamily: "Meslo LGS NF"

However, I am only concerned with the editor font. I have the latest version of Cascadia Code that came with WT. Earlier I had manually 2105.24, which showed the cursive letters for the italic variant. I have removed this version, and I can see that the WT version does not have cursive letters. 

I thought that this is a VS Code issue and opened the issue. I am closing it now. 

Although it would be good to know how to switch to the cursive version.

**Comment by IllusionMH** [comment]
If you have latest Cascadia Code version (personally I use Cascadia Code PL installed manually to avoid conflicts with WT) you can use Font features https://github.com/microsoft/cascadia-code#font-features to control display of font.
I guess that you want to [enable cursive from](https://github.com/microsoft/cascadia-code/tree/v2106.17#to-enable-the-cursive-form-of-the-italic-heres-the-code-you-should-use) (instead of more "toned-down" italics) and in this case `"editor.fontLigatures": "'calt', 'ss01'"` should help

**Comment by nisarg-ujjainkar** [comment]
Ok, Thanks.
