### ISSUE TITLE
Disable Popup Notifications Appearing at the Bottom Right Corner

### ISSUE THREAD

**Issue by Adam-Antios** [microsoft/vscode#129170]
I would like a way to disable all popup notifications/suggestions/errors that appear at the bottom right corner. This became a big issue while writing LaTeX where I got a lot of times two or more consecutive notifications which needed a click to be dismissed.

**Comment by ArturoDent** [comment]
It appears that notifications can be silenced in zen mode only.

**Comment by karai17** [comment]
I want to include an emerging and very unacceptable practice in this issue. Recently a popular extension has added new code that abuses the error notifications to solicit donations for his extension. In a brief back and forth with the developer on the review page, he noted that he chose to abuse the error notifications because they don't time out and disappear on their own, so it forces users of his extension to interact with his solicitation, including a small guilt trip for declining to give him money for a tool he chose to create and offer as free an open source.

This kind of behaviour *must* be stopped before it gains traction.

https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-todo-plus&ssr=false#review-details
