### ISSUE TITLE
Console/Output don't maintain their scroll position when hide/show panel, terminal does

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#12937]
- Have some output in the Debug Console or Output pane.
- Scroll up
- Hide the panel
- Show the panel
- Now they are scrolled all the way down

That might be ok, but if you repeat the same steps for the terminal, it maintains its scroll position across show/hide. I like that behavior better. Either way, I think it should be consistent.

**Comment by isidorn** [comment]
We should maintain scroll position

**Comment by Tyriar** [comment]
So the terminal had an issue with this recently where hiding and displaying was keeping the viewport where it was but the scroll bar was being pushed to the top. The reason this happens is because the element is detached and re-attached to the DOM which does not maintain the `scrollTop` position.

Might be useful in finding a fix: https://github.com/Microsoft/vscode/issues/12574, https://github.com/sourcelair/xterm.js/issues/291
