### ISSUE TITLE
allow to pass windowName to openExternal

### ISSUE THREAD

**Issue by akosyakov** [microsoft/vscode#129481]
In my case I would like to reuse the same window.

**Comment by bpasero** [comment]
Example code?

**Comment by akosyakov** [comment]
Something like:
```
vscode.env.openExternal(url, { windowName: 'my-window-name' })
```

`windowName` has the same semantics as in https://developer.mozilla.org/en-US/docs/Web/API/Window/open

**Comment by bpasero** [comment]
If you want to open a workspace on a path, why not use `vscode.openFolder` instead which has options to reuse the same window? Or does this have to go through the URL link handling?

**Comment by akosyakov** [comment]
I would like to open a known website in the browser window and reuse the page if it exists instead of opening a new one. Not a workspace on a path.

**Comment by bpasero** [comment]
I see, this is specifically for indicating the browser window to open in.

//cc @joaomoreno

**Comment by akosyakov** [comment]
@bpasero @joaomoreno I won't mind to file a PR if you are generally opened to it.

**Comment by bpasero** [comment]
To be honest, I am not entirely sure how this API would look like because `openExternal` is not being used for browsers only but can open any kind of application where a "name" might not make a lot of sense.

Besides, it is very likely that we cannot even control the opening when the code executes from a Electron app. I doubt you can set the window to open a link in when opening from Electron APIs.
