### ISSUE TITLE
Feature Request: Distraction free (zen) mode

### ISSUE THREAD

**Issue by ihorskyi** [Microsoft/vscode#12940]
Would be most useful to have it in vscode. IDE/Editors that have it
- IntelliJ idea/Webstorm
- Eclipse
- Atom
- Sublime Text

**Comment by smuuf** [comment]
Do you mean something like when you press `F11`?
That works for me, with version *1.5.3*.

**Comment by bpasero** [comment]
@ihorskyi you can hide the sidebar and set the window to full screen (from the view menu). You can even hide the status bar too.

**Comment by bpasero** [comment]
@ihorskyi you could disable tabs but not hide them. you can also not hide the activity bar to the far left currently, but we are thinking about a zen mode because other users asked for it too.

**Comment by alefragnani** [comment]
What a coincidence! Last week I decided to create an extension do to exactly that 😄 . But unfortunately I had to pause, because it would be necessary some API improvements. I was thinking/searching the source show to accomplish it.

There are 3 commands that should be updated, to accept a `boolean` parameter (today are only a _toggle_ mechanism:

```typescript
        'workbench.action.toggleStatusbarVisibility'
        'workbench.action.toggleSidebarVisibility'
        'workbench.action.toggleFullScreen'
```

If it is not possible to update the commands to accept parameters, another idea is to add this attributes as **User Settings**. So, with the new API to update user settings (September release). The same API could be used to hide/show Tabs, Line Numbers, and other _distractions_.

And also, the possibility to hide the Activity Bar, which already is reported (https://github.com/Microsoft/vscode/issues/1105)

I would be happy to help, if needed

**Comment by bpasero** [comment]
I like that 👍

**Comment by TheColorRed** [comment]
Here is how I think it should look (and possibly without line numbers):

![vscode-zen](https://cloud.githubusercontent.com/assets/1571806/19126322/0d876f7e-8b00-11e6-96cf-7aae809df1c5.png)

**Comment by panKt** [comment]
@TheColorRed, sorry, but you provided a super lame example, please have your own experience on how the real zen mode works in various apps.
* No line number (but could be toggled using hotkeys)
* Git diffs should be visible (but could be toggled using hotkeys)
* Code errors/warnings should be visible (but could be toggled using hotkeys)
* No status bar (but could be toggled using hotkeys)
* No Scrollbars visible until user scrolls
* No those menu bar (File, Edit, View) - because app is fullscreen by default in zen mode
* Margin is absolutely essential there. And It automatically adapts to multiple editors
etc...

**Comment by TheColorRed** [comment]
Sorry... Maybe it is called something else then...

**Comment by dilijev** [comment]
@ihorskyi re: auto-hide scrollbars: VS Code's scrollbar is actually transparent so you can see code under it. I agree that auto-hide when not searching might be nice as an option because it would remove the mild distraction, but there are some reasons to show the scrollbar at all times is that it does at times contain useful information, like indicators to show you where matches to Find queries are, and which lines of source have changed according to version control.

If the ability to auto-hide the scrollbar were added, I'd recommend a three-way configurable option:

editor.showScrollbar: { "always", "whenScrolling", "whenMatching", "never" }

Although, hotkeys/commands/APIs should be able to override the behavior because a user might want to change these quickly and temporarily, like for instance when entering or leaving zen mode.

I think "never" could work because we have the status bar and some editors like VIM work perfectly well without showing a scrollbar by showing percentage through the file your cursor is located at, or showing current and total lines in the status bar. Someone using zen mode might appreciate the ability to hide the scrollbar entirely and navigate through other means (would also help with the VIM plugin, incidentally).

**Comment by isidorn** [comment]
We pushed a first version of zen mode which will be available in tomorrow's insiders.
Currently it is possible to enter the zen mode via view menu action or via command pallete - "Toggle Zen Mode":

- Hides all parts: sidebar, activity bar, status bar, panel
- Goes into full screen mode

You can get out of full screen by toggling that action again or by going outside of fullscreen mode or by pressing Esc when no other context using escape is there (e.g. no find widget).

Since some users do not want to go into fullScreen mode when going into zen we have provided the setting `workbench.fullScreenZenMode` which by default is `true`.

Currently zen mode is not adding any margin to the editor or hiding tabs. For this feel free to open new feature requests where we can debate on the usefulness of this.
Default keybinding is `cmd + K + Z`.

You can try it out and provide feedback - please note that we prefer new issues for additional feature requests in this area.

**Comment by bpasero** [comment]
![untitled](https://cloud.githubusercontent.com/assets/900690/20356118/dba972a0-ac23-11e6-9aa5-2c0deffae53c.gif)

**Comment by ihorskyi** [comment]
@isidorn is it possible to hide tab title?

**Comment by isidorn** [comment]
@ihorskyi currently not but I am thinking about disabling tabs when in zen mode. So the title would still be there - it would just not be cluttered

**Comment by bpasero** [comment]
That is actually an interesting idea 👍

**Comment by asg-mojtaba** [comment]
It's possible to add feature for add start margin to centering text in zen mode, like Intellij ?
