### ISSUE TITLE
Support Drag and Dropping From OSX Emoji and Symbols Panel

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#12953]
- VSCode Version: 1.6 Insiders
- OS Version: OSX 10.11

Using the OSX Emoji & Symbol panel, some applications support dragging and dropping symbols directly from the panel into a text field insert them. Apps that with support this behavior include: TextMate, Text Edit, Safari, and Chrome.

![sep-28-2016 15-51-23](https://cloud.githubusercontent.com/assets/12821956/18935306/fab20cd6-8593-11e6-99dc-e100191a115a.gif)

**Comment by alexandrudima** [comment]
To keep the number of issues in our inbox at a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: we look at the number of votes the issue has received and the number of duplicate issues filed. Thank you for your time and understanding.

If you disagree and feel that this issue is crucial: we're happy to listen and to reconsider.

**Comment by mjbvz** [comment]
I just accidentally fixed this while working on the drop into editor api :)

Marking for April for verification
