### ISSUE TITLE
"Continue" does not work on the disassembly view

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#129541]
Testing #129161

@yuehuang010, @xisui-MSFT

1. Open disassembly view, press the `Step Over` notice how it nicely works on the disassembly view
2. Now press the `Continue` notice how it does not work the disassembly view, instead it continue the whole program

Same problem for `reverse continue`.

**Comment by yuehuang010** [comment]
Continue is supposed to resume the whole program until breakpoint.  Did you
expect differently?

**Comment by isidorn** [comment]
I was expecting that continue behaves the same as the Step Over, Step Into, Step Out that it respects if the focus is in the disassembly view. Why would continue be different than these commands?

**Comment by weinand** [comment]
@isidorn DAP's `continue` request does not take a "stepping granularity" argument as the stepping requests because it does not make sense. That means that `continue` in the disassembly view is not different than `continue`  anywhere else: it just continues the program. Only if a subsequent stop is a "instruction stop", will the location be shown in the disassembly view. If it is a regular stop, it will end up in normal source.
Try `continue` in Mock Debug: set a breakpoint in the disassembly view and one outside in the Markdown source.
Hitting `continue` once lands in the disassembly view, hitting it again ends up in normal source.

**Comment by isidorn** [comment]
@weinand thanks for the explanation, but here's what I would expect:

1. If I am in a disassembly view and press step over, the next line in the disassembly view is focused - great!
2. If I am in a disassembly view and the next line has a breakpoint if I press continue I would expect the next line to get hit. This did not happen. Now I tried it again and it seems to work. So I must have had something off...

**Comment by weinand** [comment]
@isidorn yes, I fully agree with your expectation (but I thought that Mock Debug works like that ;-)
If not, this is a Mock Debug problem and not a VS Code problem.

**Comment by yuehuang010** [comment]
FYI. MSVC DAP has a bug where it returns "breakpoint" instead of "instruction breakpoint" when instruction BP is hit.  This will "flip" the focus back to the source code.
