### ISSUE TITLE
hide stash drop confirm, when stash push etc.

### ISSUE THREAD

**Issue by Benno-Wu** [microsoft/vscode#129542]
- VS Code Version: 1.58.2

Steps to Reproduce:
1. stash list, length 1(may doesn't matter)
1. in the menu of git, try drop one stash, a confirm with message showed on the bottom-right corner
2. now stash push
3. click 'yes' to confirm in step2
4. wrong stash was dropped

Expectation:
I run into this situation today, and it takes me a while to rollback by git fsck
so please hide that wrong stash drop confirm

**Comment by lszomoru** [comment]
@Benno-Wu, apologies for not getting back to you on this until now. I have tried to reproduce this issue locally using the latest version of VS Code Insiders and I am unable to do so as when deleting a stash we now show a modal dialog instead of a notification in the lower right hand corner. I will optimistically close this issue as resolved, but please feel free to reopen in case you are still able to reproduce this problem. Thank you!

**Comment by alexr00** [comment]
Verified that a modal shows when a stash is dropped.
