### ISSUE TITLE
No warning when a custom editor doesn't activate or register.

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#129589]
Does this issue occur when all extensions are disabled?: Yes/No

While @mjbvz and I were debugging the hex editor extension we realized that it wasn't activating or registering a custom editor despite the package.json saying otherwise. It would be nice if we could notify the user as to what is going on in these scenarios. The fix ended up being that web extensions expect the commonjs format.

**Comment by mjbvz** [comment]
@lramos15 I don't think this is a custom editor specific issue: the extension's `activate` function was never called so nothing worked

My suggestion is that if an extension defines a `main`/`browser` in  its `package.json`, we show an error if it does not export an `activate` function

**Comment by lramos15** [comment]
I'm not sure I'm the best person for this as I don't really know too much about the extension activation process. I did test a hello world extension without an activate function and executing the "hello world" command leads to an extension not found error.

**Comment by mjbvz** [comment]
I think @alexdima maybe?

**Comment by alexdima** [comment]
It is not mandatory for an extension to export an `activate` function. This is intentional. If an extension doesn't export an `activate` function, then the exports of the commonjs module is considered to be its API. The entire `vscode` API is available outside/before `activate()` is called and it is possible to write an extension without using `activate()`. The only thing an extension would miss out on would be the `ctx` passed into `activate()`.

So I would not do anything here.
