### ISSUE TITLE
search.fuzzyFilePicker might not be a good name

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#1295]
In our `vscode.d.ts` we call it quick pick, not file picker.
So I would call the setting `search.fuzzyQuickPick`

**Comment by bpasero** [comment]
I am also not 100% sure about the name, but the setting has no impact on the picker that extenson writers can use. 

@egamma @chrisdias @stevencl maybe you have an idea how to call this setting and describe it better. It enables alternate scoring and matching for the file picker. 

![image](https://cloud.githubusercontent.com/assets/900690/11786785/c5a1ede8-a288-11e5-93e8-79e898d278fb.png)

Interestingly Atom calls it like this:

![image](https://cloud.githubusercontent.com/assets/900690/11786795/d7e5fdaa-a288-11e5-86e9-db69f375538b.png)

**Comment by chrisdias** [comment]
Why is it under the `search` category? The other search option(s) apply to the search viewlet (`search.exclude`).  Perhaps we need the `quickPick` category? If so I suggest: 

``` json
"quickPick.useFuzzySearch": boolean
```
or
``` json
"quickPick.useAlternateScoring": boolean
```

**Comment by bpasero** [comment]
Yes, we can introduce a new category. Note though that the search.exclude setting has an impact on quick open too.

**Comment by egamma** [comment]
`"quickPick.useFuzzySearch": boolean` works for me.

**Comment by bpasero** [comment]
@egamma @chrisdias would people not expect that fuzzy search is then applied to all of quick pick, where today it is only applied to the file search and nothing else? I also think "fuzzy" might be a bad name because we are not matching as crazy fuzzy as sublime does. I have a feeling that in sublime the typed characters are matched anywhere in the file and path, whereas for us (and Atom I think) at least the characters must be in the same order as in the string.

`search.alternateFilePickerMatching`
`Changes the file picker to use an alternate matching and scoring approach that will produce more results based on the query`

**Comment by egamma** [comment]
The description should mention `experimental` then we set the expectation. 

Suggest the following description, I would still use fuzzy this was also the term used in #968.

>Experimental support for fuzzy matching of file names in the file picker

how about this option name to make it clear it applies to the file picker only:

>filePicker.alternateFileNameMatching

**Comment by bpasero** [comment]
:+1:
