### ISSUE TITLE
Hovering over argument with same name as outer variable produces nothing

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#12952]
_From @mousetraps on September 27, 2016 21:0_

Testing Microsoft/vscode#12600

Using the following code and a breakpoint at the location specified location
```js
var screenName = 'hello';

setTimeout(function() {
    console.log('done');
    a(screenName);
    
    process.exit();
},1000)

function a(screenName) {
    console.log(screenName); // SET BREAKPOINT HERE
}
````

hovering over screenName at this position should produce the string `"hello"`, instead, no hover appears. Changing the name of the argument resolves the issue.

_Copied from original issue: Microsoft/vscode-node-debug2#34_

**Comment by roblourens** [comment]
Hover doesn't work at that point, using either debug adapter. Seems like that's a case where it should?

**Comment by isidorn** [comment]
There are multiple variables names screenName (in mulitple scopes). Due to the lack of language knowledge we decide to now show anything since we can not be sure over which hover the user is hovering over.
Closing as duplicate - as there are other issues like this which we plan to fix by introducing language knowledge to the hover
