### ISSUE TITLE
Keybinding when clause resolving slows down workbench startup

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#129625]
Originally found by @alexr00 and @roblourens that a complex when clause with `or` operator can slow down the startup by 10 seconds https://github.com/microsoft/vscode/commit/1066e2c6a14649a52514b04bf92405cb2dd66033.

<img width="520" alt="image" src="https://user-images.githubusercontent.com/876920/127225780-b05f8c59-4061-437c-82da-29f00bd63379.png">

**Comment by rebornix** [comment]
wait, it's actually pretty bad on my machine. I have seen slowness recently in OSS but never really dig into it but this might be root cause

<img width="1648" alt="image" src="https://user-images.githubusercontent.com/876920/127226812-3c2b320d-c0f8-48e0-a5b3-4e836b3a1ec0.png">

**Comment by rebornix** [comment]
Currently the resolving time is fine (I had a mistake with the compiling the main branch so with a clean pull the data is okay)

<img width="476" alt="image" src="https://user-images.githubusercontent.com/876920/127227536-1f6f3b94-ac13-4b90-bb8d-f56db0136374.png">

**Comment by roblourens** [comment]
This came from the way our context key expressions handle a `(A | B) & (C | D)` pattern by distributing it to just be an OR pattern https://github.com/microsoft/vscode/blob/5b73c885890e95af601df0f968194efeab1b70cd/src/vs/platform/contextkey/common/contextkey.ts#L1240-L1240 

If you create a slightly complex expression with some nested ORs as in the original commit linked above, and negate it as happens here, https://github.com/microsoft/vscode/blob/87d09c2e939aac5d8ae6c938b2bd4e750431a214/src/vs/platform/keybinding/common/keybindingResolver.ts#L200-L200

then you can easily end up creating expressions with 10s of thousands of elements, and these take a long time to create and process.

I don't really understand why we have to process expressions with OR that way, why can't we leave it in its original format?

**Comment by alexdima** [comment]
> I don't really understand why we have to process expressions with OR that way, why can't we leave it in its original format?

OR expressions are distributed because the language does not support parenthesis and therefore needs to bring the expressions to the normal form (just && and ||).

There is also a piece of code in the keybinding resolver that looks for colliding keybindings and determines if one shadows the other with all possible context values. For two such colliding keybindings, it evaluates if the context key `p` of one of them shadows the other's context key `q`. So it basically looks if `p implies q` i.e. it evaluates `!p || q` and tries to check if that is `true`. 

@roblourens I'd still like to understand why this would take 3s. What is the diff I need to do in order to reproduce the slowdown?

**Comment by roblourens** [comment]
The text language doesn't, but the object model form essentially could, right?

**Comment by alexdima** [comment]
Yes, that is why you're able to express such an expression. But the expression is normalized to a form without paranthesis such that it can be serialized in e.g. the default keybindings JSON file or UI. I am working on improving things to avoid term explosions.

**Comment by roblourens** [comment]
> such that it can be serialized in e.g. the default keybindings JSON file or UI

I see. Maybe it could be normalized only for serialization but we keep a more efficient form in memory.
