### ISSUE TITLE
.NET Interactive install flow is a little silly...

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#129652]
Testing #129463

1. Open an ipynb using .NET Interactive languages in it. There are some in https://github.com/TylerLeonhardt/JupyterNotebooks
2. "Select kernel"
3. Install Jupyter extension
4. Open ipynb again
5. Get 2 notifications:
![image](https://user-images.githubusercontent.com/2644648/127238591-c001036a-3c00-4c17-804e-2dafa7508e74.png)
6. Install .NET Interactive extension since this notebook is PowerShell
7. open ipynb again
8. Get 3 notifications:
![image](https://user-images.githubusercontent.com/2644648/127238738-b797499c-9585-45bf-9748-01bc2bf9f7e1.png)

And I don't want to manually install the .NET SDK on this machine so I'm stopping here. Maybe that error is expected, but is the Python extension also needed?

cc @colombod @jonsequitur

**Comment by roblourens** [comment]
I think this would be included in the getting started flow that @misolori has been looking into

**Comment by jonsequitur** [comment]
I haven't seen this type of bug in a while. @TylerLeonhardt, are you able to repro this with notebooks created more recently?

I think that part of the issue here might be that the older .ipynb files created for .NET Interactive didn't contain kernel and language metadata that could be used to select the correct kernel, so Python is assumed. 

/cc @brettfo

**Comment by joyceerhl** [comment]
@jonsequitur FYI just in case, this is coming up because VS Code is shipping built-in support for ipynb files, i.e. the `jupyter-notebook` serializer for ipynb files that used to be in the Jupyter extension has moved into a builtin extension in VS Code that can be disabled but not uninstalled.

**Comment by joyceerhl** [comment]
@TylerLeonhardt Do you happen to have the dev log? Am specifically interested in "Failed to set document metadata for ..."

**Comment by TylerLeonhardt** [comment]
> @TylerLeonhardt Do you happen to have the dev log? Am specifically interested in "Failed to set document metadata for ..."

Unfortunately, that one doesn't show up anymore but I remember it was just complaining about "Unable to find appropriate .NET SDK." as well.

**Comment by TylerLeonhardt** [comment]
@jonsequitur it's very likely the cause then. It's a pretty old ipynb:
https://github.com/TylerLeonhardt/JupyterNotebooks/blob/master/notebooks/Samples/Managing-Azure.ipynb

**Comment by misolori** [comment]
If I create a new .NET Interactive (C#) blank notebook and only having the Jupyter + .NET Interactive extensions installed, I still get prompted to install the Python extension. Is this still correct?

<img width="783" alt="CleanShot 2021-07-28 at 09 56 43@2x" src="https://user-images.githubusercontent.com/35271042/127364620-03a91d6e-3476-448d-b55b-d2fa0f1268a1.png">

And then choosing ".NET Interactive" as the kernel I get the same messages:

<img width="831" alt="CleanShot 2021-07-28 at 09 57 52@2x" src="https://user-images.githubusercontent.com/35271042/127364743-13274101-29ab-49c4-9f63-fb1fbb6c93b4.png">

<img width="1238" alt="CleanShot 2021-07-28 at 09 59 08@2x" src="https://user-images.githubusercontent.com/35271042/127364906-4b081d71-21f0-4489-9477-981f168f7c34.png">


I don't have any .NET SDKs installed

**Comment by DonJayamanne** [comment]
> get prompted to install the Python extension. Is this still correct?

That's not correct.

**Comment by misolori** [comment]
I assessed the install flow for .NET notebooks and there certainly a lot of room for improvement that overlaps across VS Code + .NET:

1. When opening a .NET notebook for the first time, the "Select a Kernel" only shows the Jupyter extension. We should detect to see if other languages are used in the notebook (C#, F#, etc.) and then show the applicable extensions
2. The .NET Interactive Notebook extension should use the progress notification for installing .NET because this is happening in the background and there's now way for the user to know that unless you carefully read the text
3. After .NET is installed, when clicking Run, I now get the correct kernel but then after selecting it the notebook does not run. This appears to be a bug.

https://user-images.githubusercontent.com/35271042/135929628-21320177-a40a-4350-9976-9e121aebc7a3.mp4


Not sure whether these issues should live in the Jupyter or .NET extension or in VS Code. Anyone have any thoughts?

**Comment by misolori** [comment]
I've separated out the various issues into their respective repositories so will be closing this issue in favor of those.
