### ISSUE TITLE
Untitled editor hint should be hidden by default or the message should be fine tuned

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#129601]
Testing #129436

I am quite happy how the auto detection works. I think next milestone we should look into removing the untitled hint, we can just change the setting so it is hidden by default, and people that miss it can bring it back.
Alternatively we should tune the message so users know we will auto detect

fyi @sana-ajani 

![Screenshot 2021-07-27 at 20 59 53](https://user-images.githubusercontent.com/1926584/127212337-6ea920cd-17cf-4d30-b12c-0544009ee27b.png)

**Comment by TylerLeonhardt** [comment]
To be honest, I still like the hint. It doesn't seem to disruptive/a huge burden to keep in its current form.

**Comment by sana-ajani** [comment]
I do think the text is helpful, but I wonder if we can re-work this text as a way to let people know about the detection feature? It could be a good way to draw attention to it from within the product. Also because for some languages (like Java), once it auto detects, the Java extension start page pops up, which could be a bit jarring if the user doesn't realize what's happening. 

Will this be enabled out of box in the next release? If so, perhaps re-worked to be something like: "Start typing to [detect a language] or [select one](language mode picker) to get started. [Don't show](change untitled hint setting) this again."

**Comment by TylerLeonhardt** [comment]
> Will this be enabled out of box in the next release?

It won't be in the release happening next week. It'll be the one after that so 1.60.

**Comment by isidorn** [comment]
Yeah, then let's just fine tune the message.

**Comment by TylerLeonhardt** [comment]
Here's what this might look like:

![image](https://user-images.githubusercontent.com/2644648/127376241-27c5eed1-8ed2-461e-9194-18c7b8db7a76.png)

Notice the lack of `(Auto)` on the bottom. The thinking is that this change to the hint is a good enough advertisement for the feature.

**Comment by sana-ajani** [comment]
Actually, I think we can remove the "select a language" and just draw attention to the new feature. "Start typing for VS Code to detect your language, or don't show this again"

**Comment by TylerLeonhardt** [comment]
@meganrogge said: "I wonder if we should use a new word in that hint so people pick up on the change - "begin" instead of "start" even. Otherwise, people like me, who are familiar with the old hint language, might not notice the change."

@digitarald said: "One concern about the copy change: "start typing to detect" sounds a very active, like the user is detecting language or that detection requires some additional action by the user."

I said: "Begin typing and we'll detect a language or [select a language] to get started. [Don't show] this again."

@Tyriar said: "we'll" sounds wrong there to me, it's too casual imo

@meganrogge said:
"
Begin typing to enable language detection?

Begin typing for automatic language detection?

what about "type or paste (code?) for automatic language detection" bc begin and start aren't really informative
"

**Comment by TylerLeonhardt** [comment]
I like the inclusion of "paste" just because that's gonna be the most successful way to see language detection in action

**Comment by isidorn** [comment]
After discussion in the UX meeting I agree with @stevencl 100%
I think we should not change the hint.

**Comment by TylerLeonhardt** [comment]
Yeah it seems like the consensus was to leave it as is which I think is nice. Closing this. Great discussion everyone!
