### ISSUE TITLE
Disassembly View: instruction address is not the same as a memory reference.

### ISSUE THREAD

**Issue by vadimcn** [microsoft/vscode#129655]
Version: 1.59.0-insider
Commit: c3b4df8f5d9c14aa4cfddb587231d0d52e72e5a2
Date: 2021-07-27T15:07:54.419Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Linux x64 5.8.0-63-generic

As mentioned [here](https://github.com/microsoft/vscode/pull/125737#issuecomment-886012354), Disassembly View uses instruction addresses interchangeably with memory references.    I do not think this is a valid assumption.

**Comment by rzhao271** [comment]
What are some verification steps for this issue?
I've attached a pic of what I'm seeing in case that verifies the issue immediately.
![Disassembly view showing some instructions](https://github.com/microsoft/vscode/assets/7199958/55fc4f54-5438-47b8-9749-a1a0f5159849)

**Comment by connor4312** [comment]
You can try disassembly in [mock-debug](https://github.com/microsoft/vscode-mock-debug) where I [made a change](https://github.com/microsoft/vscode-mock-debug/commit/b8d3d3a436e94f73ca193bf0bfa7c5c416a8aa8c#diff-a5084a6369857a870a66194d07e804149f4aa012e2c1fe95ea9c733cae6d123dR901) so that references no longer parse as addresses
