### ISSUE TITLE
Reloading twice loses changes

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode#129629]
Testing microsoft/vscode-jupyter#6813

Open editor with custom editor
Make changes
Put custom editor on background tab
Reload VS code twice

Changes are lost

**Comment by rebornix** [comment]
What happened:

* First reload, we found a custom editor backup, and then create a notebook editor input
* Before the notebook editor input resolves the backup and save it with working copy, another reload happens
* Workbench reopens the notebook editor input, but it doesn't know where to find the backup

The fix is attaching the backup info the notebook editor input until we resolves it.
