### ISSUE TITLE
Strange formatting for Razor

### ISSUE THREAD

**Issue by bgashler1** [Microsoft/vscode#12978]
- VSCode Version: Insiders
- OS Version: Windows 10

Regarding test item #12100 

Steps to Reproduce:

1. This may not be a problem and might just be me.  Open a large .cshtml file (try the one I link to below) and select everything.
2. Press Shift + Tab several times to collapse all the hierarchy and mess up its formatting.
3. Now Format the file
4. Notice that the file formats weird as pictured below (maybe it's just [my file](https://github.com/Microsoft/vscode-website/blob/3cfa8213681f680418997c7671fa1b8c452ac2af/website/Views/Docs/extensions/example-word-count.cshtml)).

**Original file before I used Shift+Tab several times**
<img width="1440" alt="screen shot 2016-09-28 at 11 09 18 pm" src="https://cloud.githubusercontent.com/assets/11839736/18942905/1500a31c-85d1-11e6-9961-b795550bca44.png">

**After format**
What's with the white space in the middle of the code?  Maybe this file uses spaces, maybe it has mixed tabs and spaces and this had something to do with it?
<img width="1440" alt="screen shot 2016-09-28 at 11 08 44 pm" src="https://cloud.githubusercontent.com/assets/11839736/18942911/24d53794-85d1-11e6-8fbd-c8c84524cf5b.png">

Notice how some of the tags that are nested are all linline still.  I would expect a more opinionated format of nesting these more in a block way.
<img width="1440" alt="screen shot 2016-09-28 at 11 08 29 pm" src="https://cloud.githubusercontent.com/assets/11839736/18942915/28b489f0-85d1-11e6-8bef-206ccd8fe8a3.png">

Please feel free to close if it's just me :)

**Comment by aeschli** [comment]
We're using JSBeautify to format html. JSBeautify has the concept of tags that should not be formatted, as making any change to the content of these tags potentially results in differently rendered html.
This list of tags that should not be formatted is listed in the default settings and can also be changed there:
`"html.format.unformatted": "a, abbr, acronym, b, bdo, big, br, button, cite, code, dfn, em, i, img, input, kbd, label, map, object, q, samp, script, select, small, span, strong, sub, sup, textarea, tt, var"`
But that's IMO what you see in your example. 
From what I see there hasn't been any changes due to moving Razor to an extension, so this is not a regression.
