### ISSUE TITLE
Debug inline values shows values twice

### ISSUE THREAD

**Issue by enkeyz** [microsoft/vscode#129770]
Does this issue occur when all extensions are disabled?: Yes/No
Yes.

- VS Code Version: 1.58.2
- OS Version: latest Manjaro
- Latest stable Python/Pylance version

Steps to Reproduce:

1. Enable Debug: Inline values
2. Start debugging

![image](https://user-images.githubusercontent.com/17646853/127484962-6b9d7e87-d1eb-4ed5-8386-8286ab3347f0.png)

**Comment by weinand** [comment]
What language is that?

**Comment by enkeyz** [comment]
Python.

**Comment by weinand** [comment]
@isidorn I've debugged this and found the following:
- Python(lance) does not use the new `InlineValuesProvider`, so the problem is in our built-in code (that's the reason why I assign this to you),
- I can only reproduce this for Python, not for JS/TS. 

When running out of source just copy these tow extensions from vscode-insiders into vscode-oss-dev:
<img width="289" alt="2021-08-02_20-32-28" src="https://user-images.githubusercontent.com/1898161/127907626-f870a378-84d2-4453-9da5-c85b61ba3e4c.png">

**Comment by isidorn** [comment]
I can nicely reproduce this. The issue is that we are collecting variables across different scopes and for each variable we try to create an inline decoration. For the python example variables are duplicated, as they are both in the `Locals` and in the `Globals` scope. So each variable is found twice, and thus inline decorations are created twice.

As the most simple fix I am now de-duplicating all inline decorations based on content and line number.

**Comment by weinand** [comment]
@isidorn great find, thanks for investigating and fixing this.

But I wonder why Python has variables both in a local **and** a global scope? I'll ask in https://github.com/microsoft/vscode-python/issues/16829

**Comment by isidorn** [comment]
Welcome. Yeah, that is interesting. I added some details in that thread in case they would like to investigate further.

**Comment by stuartleeks** [comment]
Verified on Windows 👍 

![image](https://user-images.githubusercontent.com/1824461/130776829-388ddc12-4c88-423e-b789-15bb2b4aecc2.png)

**Comment by enkeyz** [comment]
@stuartleeks looks like according to the picture, it works as expected. Where do you see that it shows it twice?

**Comment by weinand** [comment]
@enkeyz Stuart has verified the fix for the problem, not the problem.

**Comment by stuartleeks** [comment]
Ah - apologies for the confusion!
