### ISSUE TITLE
Picked mime type renderer is not respected

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#129750]
Issue Type: <b>Bug</b>

For a multi-mimetype output, e.g., svg, the Jupyter renderer always wins. Even if I pick the builtin one, after closing and reopening the file, it's still rendered by the Jupyter renderer.

VS Code version: Code - OSS Dev 1.59.0 (Commit unknown, Date unknown)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

**Comment by roblourens** [comment]
>  after closing and reopening the file, it's still rendered by the Jupyter renderer.

I think I would expect that, are you expecting that we remember the selection per cell?

**Comment by connor4312** [comment]
I think this duplicates/relates to discussion in https://github.com/microsoft/vscode/issues/125876

**Comment by connor4312** [comment]
There's discussion on when/how this should be applied in the linked issue, which is something I do want to address next month. Although I'm not a heavy user of Jupyter notebooks myself I don't think this is candidate-worthy.

If I have a custom renderer for a built-in type and I want to use the built-in renderer, that choice is not persisted: is that a common use case, am I just using the built-in renderer because there's a bug with a specific output or custom renderer or do I actually want it to be persisted?
