### ISSUE TITLE
Select text + Shift/Ctrl + Scroll behaviour

### ISSUE THREAD

**Issue by ranjan-ranjan** [Microsoft/vscode#12981]
- VSCode Version: 1.5.3
- OS Version: Windows 10 Version 1607 OS Build: 14393.187

Steps to Reproduce:
1. Select some text in a file.
2. Shift/Ctrl + scroll behaviour should be same as in Visual Studio.

**Comment by alexandrudima** [comment]
To keep the number of issues in our inbox at a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: we look at the number of votes the issue has received and the number of duplicate issues filed. Thank you for your time and understanding.

If you disagree and feel that this issue is crucial: we're happy to listen and to reconsider.
