### ISSUE TITLE
Make launch.json lanuage aware

### ISSUE THREAD

**Issue by Coderx7** [microsoft/vscode#129892]
Currently, if you have several applications in a project, e.g. a C++ and a Python for example, if you configure launch.json for the C++, Whenever you try to execute the Python scripts, you'd fail, as the launch.json treats the python script as a C++ file. 
You can create different configurations in the launch.json file, but each time you have to manually choose the right config and this is cumbersome, to say the least. 
IMHO, it'd be a much better idea, if the launch file gets activated based on the currently selected file, if thats a C++, then the C++ related config is used, and if it's a Python script, the Pythons is used.

**Comment by weinand** [comment]
You cannot configure a launch.json "for the C++" or any other debugger and launch.json never treats a python script as a C++ file. A launch.json is language/debugger agnostic.
The "type" attribute of a launch configuration determines what debug extension is used.

**Comment by Coderx7** [comment]
Then this must be a bug that I'm facing? Here is where launch.json treats a python script as a C++ one : 
As you can see I dont use a launch.json file by default and my python script just runs fine. 
I also use CMakeTools to debug and build my C++. 
As you can see, after trying to running my C++ app using a launch.json file, I can no longer execute my Python script, looking at the logs, you can clearly see  that the python script is being sent to the g++ and this is whats causing the issue. 
![vscode_debug_issue](https://user-images.githubusercontent.com/5382892/127757756-6aa15377-d006-472f-a6df-8e3be10479da.gif)

**Comment by weinand** [comment]
If you have a launch.json, "Start debugging" (F5) runs the **selected** debug configuration from the launch.json. The selected debug configuration is the configuration shown in the debug view's dropdown:

<img width="519" alt="2021-08-01_15-34-51" src="https://user-images.githubusercontent.com/1898161/127772836-13128b0e-5092-4fed-aad2-af3ae69f5001.png">

If that debug configuration happens to refer to the currently open editor by using a `${file}` variable, then the debug configuration might start debugging on a file that the debugger cannot use.

**Comment by Coderx7** [comment]
Thank you , but this is exactly my point. The launch.json does not act in a language/debugger agnostic way here. if it were solely based on the type specified in the launch.json that would be ideal as it removes the need to switch between different configurations manually each time (at least for each language). 
Also please note that Initially, I do not use any launch.json file, I only went on to show that if I were to use launch.json I'd face an issue here.

**Comment by weinand** [comment]
VS Code has the notion of a "selected" launch/debug configuration but it does not know the semantics (e.g. what languages are handled) of the configuration because all properties of the individual configurations are contributed by a debug extension. So VS Code cannot know how to switch between different configurations automatically.

In addition, launch configurations that take the editor contents as input (by using a `${file}` variable) make only sense in the few cases where single files can be executed, e.g. Python. In bigger projects launch configuration are tied to a project and have a fixed entry point ("main") which is independent from the current contents of the editor. As an example consider the case where you are reading the readme.md file of a bigger project. Pressing F5 should not work on the readme.md but should run/debug the projects's target.

So for single file run/debug use the run/debug button in the editor (which is independent from the launch.json).
