### ISSUE TITLE
"Unsupported" in title.

### ISSUE THREAD

**Issue by byehack** [microsoft/vscode#129847]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.58.2
- OS Version: win10 20h2

Steps to Reproduce:
1. try to change background.
2. reload to take effect.
![image](https://user-images.githubusercontent.com/26390254/127696693-2e6fdd57-de4e-4630-acab-aab4048b738b.png)

**Comment by gjsjohnmurray** [comment]
As designed. The extension you are using probably alters product files, causing the startup integrity check to detect this.

**Comment by byehack** [comment]
> As designed. The extension you are using probably alters product files, causing the startup integrity check to detect this.

there is no way to ignore it?

**Comment by ajs256** [comment]
> there is no way to ignore it?
If an extension changes the VS Code core files, it will display `[Unsupported]` in the title bar. This is because it can cause hard-to-reproduce issues.

<details>
<summary>psst...want to get rid of it?</summary>
check out <a href=https://marketplace.visualstudio.com/items?itemName=lehni.vscode-fix-checksums>this extension</a>
</details>

**Comment by byehack** [comment]
> [](https://code.visualstudio.com/Docs/supporting/FAQ#_installation-appears-to-be-corrupt-unsupported)
> 
> psst...want to get rid of it?
> check out [this extension](https://marketplace.visualstudio.com/items?itemName=lehni.vscode-fix-checksums)

Thanks, it Worked.
