### ISSUE TITLE
datalist popup isn't positioned correctly when used within a webview

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#129999]
Trying to make a lightweight combo box using `input` and `datalist`. I have the following HTML:

![image](https://user-images.githubusercontent.com/2193314/127923384-0bc4fc0b-6856-479d-885a-612de82733f0.png)

It shows up correctly in the input element:

![image](https://user-images.githubusercontent.com/2193314/127923441-a6bd6aac-8abe-45b2-9542-cc7a84d2fc89.png)

But when I hit the arrow it's positioned wrong:

![image](https://user-images.githubusercontent.com/2193314/127923482-7441ea2f-3a01-44ba-8b93-873de6f12adf.png)

It should show right below the `input`.

**Comment by mjbvz** [comment]
@Tyriar Do you also see this on web?

**Comment by Tyriar** [comment]
Luna Paint is broken in Edge due to Codespaces not sending the required headers for SAB currently.

**Comment by mjbvz** [comment]
This doesn't happen on web in my testing. I believe this is possibly a chromium bug, possibly: https://bugs.chromium.org/p/chromium/issues/detail?id=1218131

Either that or it's something electron specific. Copying @deepak1556 just in case he's aware of anything but closing this issue since it's upstream

**Comment by Tyriar** [comment]
Still happens:

![image](https://user-images.githubusercontent.com/2193314/146830196-491132fb-ca38-4709-b39e-f7fae6f154c7.png)

**Comment by robstryker** [comment]
I've replicated this bug. 

I'm using the following vscode installation:
`Version: 1.62.3
Commit: ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
Date: 2021-11-17T08:00:36.721Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.8.18-100.fc31.x86_64`

The HTML I'm using is extremely basic:
`<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Hello World!</title>
  </head>
  <body>

    <label for="ice-cream-choice">Choose a flavor:</label>
    <input list="ice-cream-flavors" id="ice-cream-choice" name="ice-cream-choice" />
    
    <datalist id="ice-cream-flavors">
        <option value="Chocolate">
        <option value="Coconut">
        <option value="Mint">
        <option value="Strawberry">
        <option value="Vanilla">
    </datalist>

  </body>
</html>`

Since my vscode is using electron 13.5.2, I attempted to run the same very simple html in electron 13.5.2. It worked fine in electron directly. 

![image](https://user-images.githubusercontent.com/630383/159055298-83ef937c-8e72-457c-ac7a-581787c53c4b.png)

Unfortunately, in vscode webview, it behaves very differently. 
![image](https://user-images.githubusercontent.com/630383/159055482-3a3587e5-70ad-4cba-9426-6a97f15b955b.png)

**Comment by robstryker** [comment]
Another extender writing vscode-tekton had the following screenshot as well:
![image](https://user-images.githubusercontent.com/630383/159055765-4a80a591-2b91-4541-8ba9-fb61be2b8434.png)

**Comment by robstryker** [comment]
This issue is also replicatable in vscode-insiders:

![image](https://user-images.githubusercontent.com/630383/159056417-5e634d63-4c56-46f9-9af1-0fd9aba4c76a.png)

```
Version: 1.66.0-insider
Commit: d572d6e9d1282b352227916cb8f95bb2b03ddcaa
Date: 2022-03-18T05:16:28.002Z
Electron: 17.1.2
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Linux x64 5.8.18-100.fc31.x86_64
```

**Comment by code-withAshish** [comment]
any solution or workaround to this issue has been found yet?

**Comment by movy** [comment]
As mentioned in https://github.com/microsoft/vscode-jupyter/issues/14779, pasting into the textfield attached to combobox also does not work.

**Comment by likui1123** [comment]
excuse me, @Tyriar ,Is this problem still unresolved now?I really hope this problem can be solved

**Comment by ehassaan** [comment]
Facing the same issue, any workarounds?

![Image](https://github.com/user-attachments/assets/ce16dcc8-2c4f-4f65-a932-52207d09e8b4)

**Comment by rkeahey** [comment]
Has this problem been fixed? If not, is there some sort of workaround? I've tried all sorts of CSS styling but it has no effect.

Thanks.
