### ISSUE TITLE
`LanguageDetectionService` could benefit from some unit tests

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#129965]
I couldn't find unit or integration tests for covering the functionality. Especially since we seem to be accessing files from the build here in rather complicated way:

https://github.com/microsoft/vscode/blob/3d50b42ebed214dc6533295400a44a5452d744ef/src/vs/workbench/services/languageDetection/browser/languageDetectionService.ts#L66-L84

We otherwise have no way of detecting breakage of this feature.

**Comment by bpasero** [comment]
Slightly related: I think instead of reaching into the node module wouldn't it be easier if the module itself provides a method to get the contents of that file?

**Comment by TylerLeonhardt** [comment]
I've mostly been accumulating unit tests over in this because it's easier:
https://github.com/microsoft/vscode-languagedetection

But I totally agree that we should have some in Core because of how it's created.

**Comment by TylerLeonhardt** [comment]
> I think instead of reaching into the node module wouldn't it be easier if the module itself provides a method to get the contents of that file?

I'd love ideas on how to do this while both working on Desktop and Web...

Today we reach in using:
https://github.com/microsoft/vscode/blob/main/src/vs/workbench/services/languageDetection/browser/languageDetectionService.ts#L68

And I didn't want to have logic specific to VS Code in vscode-languagedetection because theoretically other projects could use it.

**Comment by bpasero** [comment]
I do not really think such an API would be VS Code specific, in the end this module is very VSCode specific because it is used only for VS Code right?

**Comment by TylerLeonhardt** [comment]
Well as it stands anyone running in Node could use this package (leveraging `fs`).

Eventually I wanted to allow it to work in browsers using `fetch` instead.

The problem is that VS Code is much more complicated. Just leveraging `fs` won't work since it's a browser component and `fetch` could work but I think we'd still need to pass in the path to where the model files end up since they get placed in odd locations (like the asar, or at specific routes in web).

It's possible I'm overthinking this though...

**Comment by bpasero** [comment]
Yeah agree, if you want to build the module in a node.js agnostic way (aka support web too), it needs to deal with both environments, but I am quite sure that this is possible from within the module.

If it helps, we use a encoding detection library `jschardet` which is also supported in browsers: https://github.com/aadsm/jschardet

Same as `iconv-lite` which I think can load files (encoding tables) dynamically: https://github.com/ashtuchkin/iconv-lite

**Comment by TylerLeonhardt** [comment]
@bpasero so I did a quick skim over those packages and it seems like the first is entirely JS and the second includes some JSON files (the tables).

The JS files would then get bundled and I think our bundler will embed the JSON files as well so I don't think anything is truly dynamically loaded from a file system in those cases. I could be wrong.

For the model, we have a JSON file (which could be bundled) but we also have a binary (.bin) file that contains all of the weights of the model. This is the challenging one.

The closest example of this that I found was how we load the WASM of oniguruma: 

https://github.com/microsoft/vscode/blob/ea2778063405633fb87c911ef5f580cc0a1d32c8/src/vs/workbench/services/textMate/electron-sandbox/textMateService.ts#L185

**Comment by bpasero** [comment]
Yeah good point about bundling. Agree the text mate example is very similar.

**Comment by TylerLeonhardt** [comment]
I can try to move over to soley using `fetch` or at least allow some option and then pass in the file Uri's as options so that the API in the npm module is simpler.

But yeah, ideally we can allow reuse of vscode-languagedetection because an npm/web friendly package of this particular model could be useful for others.

**Comment by TylerLeonhardt** [comment]
Added an integration test for this. I'll add more to cover more languages but the test makes sure the model loads correctly and that's the most important part in my eyes.
