### ISSUE TITLE
Double language in Preferences

### ISSUE THREAD

**Issue by peter31990** [microsoft/vscode#129946]
![obraz](https://user-images.githubusercontent.com/11589305/127813568-894f10f0-ddc2-4270-b4cf-fd0b4b549fdc.png)

**Comment by TylerLeonhardt** [comment]
I can reproduce this and this is by design. Here's an example...

I don't speak Polish, but you are experiencing an issue...
so I ask you to open the dev tools: `ctrl+shift+p` -> `Toggle Dev Tools`

If we didn't have the English one in there, you'd have to translate what I said first before being able to find it in the command palette.

The English text is there so that regardless of the language you speak, you can paste in "foo" into the command palette and will find the "foo" command.
