### ISSUE TITLE
Explorer: allow to paste files from the clipboard into target folder

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#130036]
Looks like Chrome 91 (the same version we now use in Electron 13) provides read access to files in the clipboard:

https://www.chromestatus.com/feature/5671807392677888

```js
async function onPaste(e) {
  let file = e.clipboardData.files[0];
  let contents = await file.text();  
}
```

This would open the door to allowing a user to copy files from a local folder and paste into the explorer to copy (desktop) or upload (web) them there. 

I think we already have a handler for pasting but it is scoped to operations within the file explorer only.

**Comment by isidorn** [comment]
I think this would be a great addition to the explorer and a good start for somebody to get introduced to the Explorer. Let's assign to on-desk.

**Comment by hanmala123** [comment]
I really need this feature

**Comment by pingren** [comment]
I tried to implement the API. I feel it is more complex than it looks. Some analysis for who interested:

#### Paste Event Capture
the `onPaste` event only fires on editable context(`contenteditable="true`) or `body` element (Tested on Chromium: 100.0.4896.160), which means we have two options:

- add a hidden editable div into file browser and capture the event when file browser focused. 
- listening paste event on the document and check if file browser get focused.

#### Conflicts with current`filesExplorer.paste`

the `onPaste` event could only be triggered by system paste (cmd+V on macOS). Users could change `filesExplorer.paste` command to any keybindings. So we need to consider how to merge native paste from clipboard and VSCode explorer paste. 

1. Register and listen to `paste` event as described above.
2. Set `kbOpts` for  `filesExplorer.paste` (similar to `editor.action.clipboardPasteAction`), so that it works even user change `filesExplorer.paste` keybindings. 
3. Use some mechanism to determine to paste clipboard file or in-explorer file. (I didn't come up a good solution. Need some advises)

**Comment by starball5** [comment]
Related Stack Overflow question: [Is it possible to paste files copied to the clipboard from other applications in VS Code?](https://stackoverflow.com/q/75406572/11107541)

**Comment by meganrogge** [comment]
This is an accessibility bug, could we pls look into it in the next few iterations?

**Comment by SimonSiefke** [comment]
I made a PR here https://github.com/microsoft/vscode/pull/195730

Please let me know if you have any feedback! :)

**Comment by mdrobisch** [comment]
Thanks for your effort. This feature will help a lot :-)
Could this approach also used to copy images into markdown or asciidoc in the future?

**Comment by isidorn** [comment]
@lramos15 thanks for fixing this. I just tried and it does not work as Copy from my Mac Finder to Paste into the VS Code Explroer. Does this work on Windows only?

**Comment by lramos15** [comment]
> @lramos15 thanks for fixing this. I just tried and it does not work as Copy from my Mac Finder to Paste into the VS Code Explroer. Does this work on Windows only?

All credit goes to @SimonSiefke for the amazing community contribution here.

I just tested on Mac from Finder and it worked as expected for me
