### ISSUE TITLE
empty terminals on ipados 15

### ISSUE THREAD

**Issue by akosyakov** [microsoft/vscode#130017]
It was reported by Gitpod users: https://github.com/gitpod-io/gitpod/issues/5040

**Comment by meganrogge** [comment]
Pushed a workaround for this yesterday - turning off terminal.integrated.gpuAcceleartion

**Comment by meganrogge** [comment]
Mitigated for now, but we should figure out why this is happening

**Comment by Tyriar** [comment]
I believe the ipados beta enabled webgl2 in safari is causing this, I saw an issue reported on the xterm repo for desktop safari. We need to look into what's causing it, I don't have an ipad though

**Comment by Tyriar** [comment]
Upstream https://github.com/xtermjs/xterm.js/issues/3357

**Comment by Chuxel** [comment]
FYI - This may also affect Safari in macOS 12.

**Comment by ghuntley** [comment]
With iPadOS15b7 this is reproducible on Gitpod.

https://github.com/gitpod-io/gitpod/issues/5040#issuecomment-908826541

Setting `"terminal.integrated.gpuAcceleration": "off"` "resolves".

Also reported in Visual Studio Codespaces on Twitter https://twitter.com/code/status/1433498719492710408

**Comment by Tyriar** [comment]
We've handled this properly for a while now, gpuAcceleration auto will not try the webgl renderer on safari.

https://github.com/microsoft/vscode/blob/f4605eca1c21552dfdae5fa636a94bbc0ee81a56/src/vs/workbench/contrib/terminal/browser/terminalInstance.ts#L1568

If you explicitly set `gpuAcceleration` to `on` though, this forces the use of the webgl renderer and you will have problems. This is by design to allow the user to workaround failures in the fallback mechanism and force the use of the webgl renderer. In the end I believe this is an issue in Safari's webgl implementation but I haven't looked into it; it works fine in Firefox and Chromium-based browsers, just not Safari's brand new impl.

**Comment by Tyriar** [comment]
To verify:

1. With Safari 15
2. Open codespaces and make sure the default `terminal.integrated.gpuAcceleration` = `auto` correctly renders the terminal
3. Make sure all values of `terminal.integrated.gpuAcceleration` work except for `on` which is expected to fail
