### ISSUE TITLE
Keyword 'new' as object property access and TypeScript highlighting

### ISSUE THREAD

**Issue by artaommahe** [Microsoft/vscode#13018]
- VSCode Version:
```
Version 1.5.1
Commit 07d663dc1bd848161edf4cd4ce30cce410d3d877
Date 2016-09-08T21:34:58.760Z
Shell 0.37.6
Renderer 49.0.2623.75
Node 5.10.0
```
- OS Version:
Ubuntu 14.04.4 LTS

Steps to Reproduce:

1. in TS file create some object with `new` property
2. write some code to access this property
3. see wrong highlighting after this line (look at `public isReview` color)
![_864](https://cloud.githubusercontent.com/assets/1944061/18961665/6f9f8cc0-8676-11e6-893d-8648fcfe1e9b.png)

**Comment by waderyan** [comment]
@artaommahe thank you for opening this issue. This should be fixed with the new grammar. We have released the new grammar as a beta extension for testing. Can you install [this extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) and let me know if it solves your issue?

**Comment by artaommahe** [comment]
@waderyan yep, it solves issue, thx
