### ISSUE TITLE
option to swap "stop" and "disconnect" in the debug toolbar when running from javascript debug console

### ISSUE THREAD

**Issue by DetachHead** [microsoft/vscode#130180]
it's far more common in my opinion to want to stop the process than it is to want to detach the debugger. it would be nice if there was an option to swap these two behaviors such that it stops by default and disconnects when holding alt
![image](https://user-images.githubusercontent.com/57028336/128348223-3239f6b7-b6eb-40f2-9054-bd08c1e152a0.png)

it should be consistent with the toolbar in the "run and debug" tab:
![image](https://user-images.githubusercontent.com/57028336/128349560-fa7cb241-ff4d-4550-88e1-75b49fb64b98.png)

**Comment by weinand** [comment]
@DetachHead You said:
> it's far more common in my opinion to want to stop the process than it is to want to detach the debugger. 

That might be true, but VS Code can only stop a process if it knows about it.

Attaching a debugger to a debug target typically means that the target was not launched by VS Code and that VS Code does not know how to stop the debug target. For that reason we show the "disconnect" command because that is guaranteed to always work in the "Attach" case. "Stop" will fail in most cases because VS Code knows nothing about the process. 

In the "Launch" case VS Code is in control of the debug target and knows how to stop it. In that case we show the "Stop" command.

Flipping the

**Comment by DetachHead** [comment]
@weinand it also happens when clicking debug on scripts in `package.json`. aren't those launched by vscode as well?

**Comment by weinand** [comment]
@connor4312 "clicking debug on scripts in package.json" launches scripts, so VS Code should know how to stop them. Then we should show "Stop", right?

**Comment by connor4312** [comment]
The way the package.json "debug" button works right now is just by creating a JavaScript Debug Terminal and writing the command to it, which is technically an attach. The argument could be made that they should be treated as one-offs and be a "launch" type instead; the usage of the debug terminal was mostly done since it was a minimal way to get it to work.
