### ISSUE TITLE
Win7: CPU usage at 100% when opening huge files

### ISSUE THREAD

**Issue by fibric** [Microsoft/vscode#13024]
- VSCode Version: 1.5.3 (1.5.3)
- OS Version: Win7 64 Enterprise

Steps to Reproduce:

1. I opened a file rollup.js has transpiled just now. The file was about 16000+ LoC. Syntax coloring was active.
2. Then VScode became very unresponsive. It took me 2 minutes to close the file. I don't saw the typical 'keep waiting or close' message.
3. In Process Explorer saw that a VScode process consumed 100% of a single CPU core.

![64f82052-864e-11e6-9b93-06bc3837872e](https://cloud.githubusercontent.com/assets/623932/18965017/add5851c-867b-11e6-9e0a-3371d1dc231f.png)

**Comment by alexandrudima** [comment]
@fibric Can you please share with us the contents of the file that produces this problem or perhaps a very similar file that also produces the same freeze?

**Comment by fibric** [comment]
Sorry for the late answer.

I experimented with some Rollup.js plugins, and I wanted to know why some native modules such as `fs`, `http`, etc. have gotten baked into the bundle even though I excluded them.
On opening the 782KB file, VScode became super unresponsive.
[bundle.cjs.zip](https://github.com/Microsoft/vscode/files/521230/bundle.cjs.zip)

I tried the newest Insiders build today, and this time, everything hangs except the menu bar. 
![image](https://cloud.githubusercontent.com/assets/623932/19263213/80f5080a-8f9b-11e6-980c-aff3e30cca0d.png)

It has become worse. Maybe VScode should warn on open big files until VScode can handle big files.

**Comment by joaomoreno** [comment]
I can open that file without any problems in the latest insiders release. Let's try to figure out what makes your setup different.

- Do you have any extensions installed? If so, can you reproduce using `--disable-extensions`?
- Do you open the file alone in VS Code, or as part of opening a folder?
- Does VS Code still work, but just very unresponsive? If so, can you send us a CPU profile?

--

To create a CPU profile using developer tools in VS Code:
* select Help > Toggle Developer Tools
* click on Profiles
* click the start button
* do whatever you need to do to get the CPU spin high
* wait for some time (10-20 seconds should be enough)
* stop the profiling 
* click the save button and attach the output file to this issue

**Comment by fibric** [comment]
With enabled extensions, I see these two messages in the developer console.

>Handling of 'mousewheel' input event was delayed for 392 ms due to main thread being busy. Consider marking event handler as 'passive' to make the page more responive.

>Failed to clear temp storage: It was determined that certain files are unsafe for access within a Web application, or that too many calls are being made on file resources. SecurityError

When I save the file, it's about 0 bytes. But in the developer tools, I see a huge list of captured data.
![image](https://cloud.githubusercontent.com/assets/623932/19267621/1093b92a-8fb0-11e6-8e75-902106891927.png)
![image](https://cloud.githubusercontent.com/assets/623932/19267674/5681da0c-8fb0-11e6-85e2-5542b567aaae.png)

With disabled extensions, I see only this message in the developer console.
>Failed to clear temp storage: It was determined that certain files are unsafe for access within a Web application, or that too many calls are being made on file resources. SecurityError

And again, the saved file is about 0 bytes.
![image](https://cloud.githubusercontent.com/assets/623932/19267732/b5a64126-8fb0-11e6-91b6-bdc8c3d1d0c4.png)
![image](https://cloud.githubusercontent.com/assets/623932/19267726/ae1d72f8-8fb0-11e6-96a3-05f163d5271b.png)

**Comment by fibric** [comment]
And here is what I've captured in VSCode Insiders.

With extensions enabled
![image](https://cloud.githubusercontent.com/assets/623932/19267870/6e05b0b2-8fb1-11e6-89a0-6ce4f378e955.png)
![image](https://cloud.githubusercontent.com/assets/623932/19267873/742c4b4a-8fb1-11e6-9718-5c20ebc8b8be.png)

Without extensions
![image](https://cloud.githubusercontent.com/assets/623932/19267802/0d5c5536-8fb1-11e6-8a23-37482731a7b1.png)
![image](https://cloud.githubusercontent.com/assets/623932/19267807/1932ce80-8fb1-11e6-847e-dee1f463c684.png)

Again the saved file is about 0 bytes.

**Comment by fibric** [comment]
I also took some screenshots about the CPU consuming threads when the huge file is being opened.

![image](https://cloud.githubusercontent.com/assets/623932/19267915/c00e1ff2-8fb1-11e6-9e40-5e1df0fbac4d.png)
![image](https://cloud.githubusercontent.com/assets/623932/19267930/ce06689e-8fb1-11e6-8b25-6cdabe45df24.png)
![image](https://cloud.githubusercontent.com/assets/623932/19267936/d318a982-8fb1-11e6-9fb1-4aef7e545dd8.png)

**Comment by joaomoreno** [comment]
The screenshots are good, but it would be so much more helpful if you could export the CPU profile and attach that to the GitHub issue. Thanks!

**Comment by alexandrudima** [comment]
@fibric 

Thank you for the information, here is my interpretation of the screenshots

## Stable

### Screenshot 1 and 2 - Stable with extensions enabled

Total time spent tokenizing (`_updateTokensUntilLine`): 6.8 seconds
Time spent with decorations: ~**40 seconds**

You most likely have an extension that operates on `.js` files and decides to add editor decorations (as in hundreds of thousands of decorations).

### Screenshot 3 and 4 - Stable with extensions disabled

Total time spent tokenizing (`_updateTokensUntilLine`): 3.8 seconds
Time spent with decorations: ~**76ms**

I cannot really explain why tokenization would be faster with disabled extensions (it should be the same), unless perhaps you have an extension that contributes a different grammar for JavaScript and by disabling extensions we end up using the default grammar we ship with.

> Note: It is ok for tokenization to take 7 seconds. Tokenization yields every 20ms and will not make VSCode unresponsive (i.e. you can scroll and type while tokenization runs).

---

## Insiders

### Screenshot 5 and 6 - Insiders with extensions enabled

Total time spent tokenizing  (`_updateTokensUntilLine`): 8.5 seconds
Time spent with decorations: ~ **3-4seconds**

Again there is someone adding a lot of extensions

### Screenshot 7 and 8 - Insiders with extensions disabled

Total time spent tokenizing  (`_updateTokensUntilLine`): 4.4 seconds
Time spent with decorations: I don't event see it

More or less the exact same conclusions as the Stable.

### CPU screenshots

In the first screenshot there is the renderer thread consuming high CPU -- this is captured in detail in the profiles you've taken and I explained the reasons for the usage. 

The other process that consumes high CPU looks to be like some sort of language server, most likely tsserver (that gives language smarts such as suggestions, formatting, etc.). There is some way through `jsconfig.json` I believe to disable the `tsserver` smarts for specific `.js` files (i.e. give up completions, squiggles, etc.). That will cause this process to not consume CPU.

### Conclusions

All in all, there is nothing actionable for me here. There is an extension that adds lots of API and it does so on a somewhat-large file. The JavaScript language server consumes CPU (I'm guessing it is parsing the file to build an AST). There is additional CPU consumption if you are on a system with a touchscreen (#12036)

p.s. @joaomoreno at least on Windows, saving cpu profiles no longer works since updating Electron.
