### ISSUE TITLE
[Status bar: rich hover] Still hard to mouseover

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#130248]
Same as #126888

When moving the cursor diagonally it closes too eagerly.

<img width="500" src="https://user-images.githubusercontent.com/9638156/128492637-261f3617-16ee-4082-b611-3f1cf5549b6f.gif" alt="demo" />

**Comment by misolori** [comment]
I do wonder if we can either set a bit of a delay before the mouse hover goes away or have an extra buffer around the tooltip. 

I believe this happens because you moved your cursor around the item:

<img width="187" alt="CleanShot 2021-08-06 at 08 03 15@2x" src="https://user-images.githubusercontent.com/35271042/128531087-82e6c169-ad7e-4588-bb95-c076dcaee2a9.png">

Definitely not a great experience

**Comment by Tyriar** [comment]
Some more details in https://github.com/microsoft/vscode/issues/138291
![144300401-6587400d-617b-4178-b29c-312424a39d0c](https://user-images.githubusercontent.com/2193314/144860054-3e7c79e7-e194-4d87-ba0d-9839d0efbaf3.gif)

**Comment by bpasero** [comment]
My 2 ideas:
* increase the delay for this particular case
* do not hide the hover when the hover is visible and mouse moves into the neighbour status item

**Comment by bhavyaus** [comment]
Please use: https://github.com/microsoft/vscode/issues/95816

Closing as duplicate.
