### ISSUE TITLE
Run dropdown arrow disappear when multiple extension contributes to it

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode#130389]
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.59.0 (user setup)
Commit: 379476f0e13988d90fab105c5c19e7abc8b1dea8
Date: 2021-08-04T23:13:12.822Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT x64 10.0.19043

Steps to Reproduce:

1. Install at least two extensions which contribute to `editor/title/run"`. For example, [Java Debugger](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-debug) & [Code Runner](https://marketplace.visualstudio.com/items?itemName=formulahendry.code-runner)
2. The dropdown arrow in editor run button disappear

When only one extension contributes to it
![image](https://user-images.githubusercontent.com/6193897/128669496-4ea80c72-2d8c-47fb-8b35-a4d060440e50.png)

When multiple
![image](https://user-images.githubusercontent.com/6193897/128669561-0fc8d5f5-752f-4461-8d25-33b893301a34.png)

_// cc @weinand_

**Comment by weinand** [comment]
/duplicate #129599

@jdneo Code Runner does not use theme icons but SVGs and we were not covering that case in the new split button dropdown item in VS Code 1.59 and automatically fall back to the previous version (just a dropmenu). The fall back is used whenever a contributed command uses an an SVG.

This has been fixed in Insiders.

**Comment by jdneo** [comment]
Thank you for the information @weinand
