### ISSUE TITLE
[themes] Customize file icon theme in settings

### ISSUE THREAD

**Issue by tuan-lm97** [microsoft/vscode#130334]
We already have `Developer: Generate Color Theme From Current Settings`, `workbench.colorCustomizations` and `editor.tokenColorCustomizationsn` to easily **customize** the theme we are using.
Why not did the same thing with `File Icon Theme` ?
For example, there are 2 theme that come with vscode: `Minimal` and `Seti`. `Seti` is much better of course but **I also want my folder to have the icon that Minimal had**, it would be nice if I can set it on top of `Seti` with some setting.

**Comment by aeschli** [comment]
We don't have customization settings for icon theme. It's not easy to make such settings easy to use. Icons and icon fonts are resources on disk. So the setting would consist of a set of paths to icons and icon fonts. a. editing paths is not much fun. b. the paths are likely machine specific paths and could not be shared across machines.  c. loading a resource from a path in the settings is considered a security risk (svg scripting).
Maybe you have a good idea how such a setting would look like so that it would be as easy to use as the color settings.

**Comment by tuan-lm97** [comment]
Right now, I can do this by directly go to my vscode folder location at my machine and go to `resources\app\extension\theme-seti\icons` and modify directly the `vs-seti-icon-theme.json`. Add some icon in the  **extension** folder, then add some field in `foldericonDefinitions` and add `folder` or `folderExpanded` in the json file.
I see that Material Icon theme doing something similar. Can we place some custom icon inside our vscode directory at `resources\app\extension` and then do something like

    "workbench.iconCustomizations": {
        "[Seti]": {
            "light.folder": "../../icons/folder-light.svg",
            "light.folderExpanded": "../../icons/folderExpaned-light.svg",
        },
    },

**Comment by SethFalco** [comment]
This would also allow users to address issues with icons themselves, such as:
* https://github.com/microsoft/vscode/issues/131466

The icons that contain `_` in the icon are also making me think file names are starting with an underscore.

Would be wonderful to have a setting where we could override particular icons in the theme.
If it'd make it easier or more user-friendly, it'd at least be nice to be allowed to override them with other icons in the same icon theme or installed icon themes rather than paths.
