### ISSUE TITLE
Open extension marketplace links inside VSCode

### ISSUE THREAD

**Issue by zardoy** [microsoft/vscode#130330]
Imagine in *Extension view* we have links to another extensions (e.g. demo below). And they always open in browser instead of spawning another tab **inside of VSCode**, but I think it would be better to not throw user away from the VSCode and leave him in place.
![demo](https://user-images.githubusercontent.com/46503702/128607334-8063b97b-584e-4c52-8d08-bdbd1257a725.png)

**Comment by mjbvz** [comment]
@sandy081 I'm reassigning you because I don't believe this is a generic webview issue and is instead something the extensions page can implement

To support this, we likely need override the behavior when a user clicks a link:

https://github.com/microsoft/vscode/blob/b88a5c3286ecd3bf0cfec222b6d18fcc23464ce1/src/vs/workbench/contrib/extensions/browser/extensionEditor.ts#L623
