### ISSUE TITLE
Format cell command should be better integrated in UI

### ISSUE THREAD

**Issue by timoklimmer** [microsoft/vscode#130429]
The format cell feature is great but it is hard to discover. A button in the cell toolbar or at least a command in the context menu would help customers to better find and benefit from it.

**Comment by rebornix** [comment]
Good suggestion, it makes sense to have it in the context menu.

**Comment by roblourens** [comment]
It is in the cell editor context menu. But, you might not have seen this because I just fixed a bug where the wrong context menu is sometimes shown here

![image](https://user-images.githubusercontent.com/323878/128779817-712ccf03-c132-4963-b95c-a8cfd3e74a39.png)

I will leave it there, I don't want to promote it to the toolbar or toolbar overflow menu.

**Comment by timoklimmer** [comment]
@roblourens Ok agree - the context menu entry is sufficient. However, I noticed that the format command does not sort the imports. It would be good to have an automatic sort of the imports as part of the format command as well. Or at least a separate sort imports command like there is when a Python script is edited.

**Comment by roblourens** [comment]
It sounds like the Python extension has a command for this: https://code.visualstudio.com/docs/python/editing#_sort-imports

**Comment by timoklimmer** [comment]
@roblourens Oh thanks a lot for sharing - I was not aware of it. Can you add the sort imports command to the context menu, too, similar to what we have when editing Python scripts? Even better would be if could completely get rid of the sort imports command and have it integrated in the format commands. (Just an idea...)

**Comment by roblourens** [comment]
That is all up to the python extension
