### ISSUE TITLE
Issue report can not be activated/focused once hidden

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#130497]
* Open a window, maximize it
* Open issue reporter
* Click on the previous window
* There is no way to bring back the issue reporter (ctrl+tab doens't work) unless run Report Issue again.

**Comment by ewerybody** [comment]
Well you can **un-maximize** the VS Code window and push it to the side to reveal the Issue Reporter or: yeah click **Help > Report Issue** again. <kbd>Alt+H</kbd> <kbd>i</kbd>

After all its pretty weird that this is detached from the main window at all, AND not appear in <kbd>Alt+Tab</kbd> or <kbd>Win+Tab</kbd> or the taskbar. Really strange when you actually click the _-minimize button! Which is actually there!!

### possible solutions:
* **make it a "real" window** - so that it appears in <kbd>Alt+Tab</kbd> or <kbd>Win+Tab</kbd> or the taskbar
* **make it Always On Top** - that's pretty cheap and effective. But might promote using **minimize** which makes it impossible to recover without hitting **Report Issue** again
* **make it modal** - so that it sticks to the main window its called from.
