### ISSUE TITLE
Explore Installer for the New Windows Store

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#130410]
Update issue for progress on new Windows Store install mechanism.

**Comment by chrisdias** [comment]
[Tutorial for submitting Win32 apps](https://developer.microsoft.com/en-us/microsoft-store)

[Documentation to submit your MSI or EXE app to the Microsoft Store](https://docs.microsoft.com/en-us/windows/uwp/publish/msiexe/overview)

**Comment by sbatten** [comment]
We will need the following information to fill out the store submission https://docs.microsoft.com/en-us/windows/uwp/publish/msiexe/create-app-store-listings#add-and-edit-store-listing-info

**Comment by devinvalenciano** [comment]
OK, I created first draft content needed for the Store listing based on the guidelines [here](https://docs.microsoft.com/en-us/windows/uwp/publish/msiexe/create-app-store-listings#add-and-edit-store-listing-info), couple open questions for @gregvanl / @ItalyPaleAle -

- [ ] Can you both review the content below and make sure it's in line with our website and branding guidelines?
- [ ] I took a screenshot from the website, but we're allowed up to 10 images.  Are there other shots we'd like to include here?
- [ ] Do we have a set of Store logos already?  Preferably that fit these guidelines - https://docs.microsoft.com/en-us/windows/uwp/publish/app-screenshots-and-images.  If we don't have the exact images, I can do some editing on existing assets!
- [ ] What keywords do we use for website SEO? Would like to use the same here.
- [ ] What is the Copyright and Trademark info for our product?
- [ ] [Low Priority] The Store supports multiple languages - is this something we offer on our website as well?


And here's the draft content:

**Product Name:** Visual Studio Code

**Description:** Visual Studio Code is a lightweight but powerful source code editor which runs on your desktop and is available for Windows, macOS and Linux. It comes with built-in support for JavaScript, TypeScript and Node.js and has a rich ecosystem of extensions for other languages (such as C++, C#, Java, Python, PHP, Go) and runtimes (such as .NET and Unity).

**Product Features:**
- Intelligent Code Completion - Code smarter with IntelliSense - completions for variables, methods, and imported modules.
- Streamlined Debugging - Print debugging is a thing of the past. Debug in VS Code with your terminal tools.
- Fast, Powerful Editing - Linting, multi-cursor editing, parameter hints, and other powerful editing features.
- Code Navigation and Refactoring - Browse your source code quickly using peek and navigate to definition.
- In-Product Source Control - Speed up your release cycle with SCM support inside your editor, including rich Git integration.
- Diverse Extension Ecosystem - Enable additional languages, themes, debuggers, commands, and more. VS Code's growing community shares their secret sauce to improve your workflow.

**Screenshot:**
![image](https://user-images.githubusercontent.com/1389808/129772574-d861af9d-1216-4681-94fc-2bfafa2a74f6.png)

**Store Logos:** (see question above)

**Sort Title:** Visual Studio Code

**Short Description:** Visual Studio Code is a lightweight but powerful source code editor which runs on your desktop and is available for Windows, macOS and Linux.

**Additional System Requirements:** None

**Search Terms:** (see question above)

**Copyright and Trademark Info:** (see question above)

**Additional License Terms:** By using VS Code, you agree to its [license and privacy statement](https://code.visualstudio.com/#home-terms).

**Developed By:** Microsoft

**Comment by ItalyPaleAle** [comment]
Thanks for looping me in.

Because this is for the Windows Store, I think it's safe to remove mentions that this works on any OS and it's for the desktop. Also, we should avoid putting too much focus on .NET. I'm making a few more tweaks below.

**Product name**: Should we say "Microsoft Visual Studio Code" in the name at the top?

**Description:** 

> Visual Studio Code is a free, lightweight and extensible code editor for building web, desktop and mobile applications, using any programming language and framework.
> 
> Visual Studio Code has built-in support for Git source control management and powerful integrations with GitHub, an integrated debugger, and smart code completion with IntelliSense and with AI-driven IntelliCode. With over 30,000 extensions and themes in the Visual Studio Code Marketplace, you can customize the features and the look of Visual Studio Code to fit your needs, preferences, and style.
>
> You can use Visual Studio Code to build any kind of app, for web, desktop, and mobile. Visual Studio Code supports JavaScript and TypeScript natively, and offers extensions for coding in languages such as Python, Java, C/C++, C#, Go, Rust, PHP, and many more.

I even wonder if it's worth highlight at the beginning some user reviews/feedback. Maybe starting with "#1 most popular code editor (StackOverflow 2021)"? I know we don't like touting our successes, but this seems to be a popular (and accepted) move in app stores

**Product Features:**

> - Fast, Powerful Editing - Linting, multi-cursor editing, parameter hints, and other powerful editing features.
> - Over 30,000 extensions, and growing - Enable additional languages, themes, debuggers, commands, and more. VS Code's growing community shares their secret sauce to improve your workflow.
> - Build any app type, using any programming language and framework, including JavaScript and TypeScript, Python, Java, C/C++, C#, Go, Rust, PHP, and many more, as well as many popular technologies including Node.js, .NET, React, etc.
> - Support for notebooks including Jupyter, for data science and AI development.
> - Built-in support for Git source control management and integrations with GitHub for managing issues and pull requests.
> - Intelligent Code Completion - IntelliSense and AI-driven IntelliCode offer completions for variables, methods, and imported modules.
> - Integrated Debugging - Print debugging is a thing of the past. Debug in VS Code with your terminal tools.
> - Code from anywhere with the Visual Studio Code Remote extensions and support for GitHub Codespaces.

**Short title**: Should this be just "VS Code"?

**Short Description** (<270 chars):  Free, lightweight, extensible code editor for building web, desktop and mobile applications, using any programming language and framework.

**Search terms** (limit: 7): programming, coding, code, vscode, vs, editor

**Copyright and trademark info**: Not sure if we want to link to https://code.visualstudio.com/brand or just leave empty

**Comment by gregvanl** [comment]
Alessandro's copy looks good.
Couple of nits:
- stick with Oxford comma so "Visual Studio Code is a free, lightweight, and extensible code editor for building web, desktop and, mobile applications..." There are a few other places where we should add a comma.
- First sentence of the third paragraph seems unnecessary since we already mention "web, deskop, and mobile applications" in the first paragraph.
- Maybe: "Rich debugging - Print debugging is a thing of the past. Use debugging tools directly in VS Code."
- "Write code from anywhere..." 

For the last question, code.visualstudio.com doesn't support localized content so only displays in English.

**Comment by ItalyPaleAle** [comment]
Updated my text per @gregvanl 's comments. Except his 2nd point, because sometimes *repetita iuvant* (repeating helps) :)

**Comment by sbatten** [comment]
Reopening to add Insiders to Store as well

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
> http://github.com/microsoft/vscode/issues/130410#issuecomment-900682664

For "Rich debugging - Print debugging is a thing of the past. Use debugging tools directly in VS Code", use one en dash rather than one hyphen for "debugging – Print".

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
@sbatten, what is the result of that discussion?

**Comment by sbatten** [comment]
<img width="933" alt="image" src="https://user-images.githubusercontent.com/6561887/150909433-7ddc285f-e90c-44f2-801a-58cbfa6103df.png">

**Comment by hello-smile6** [comment]
> <img alt="image" width="933" src="https://user-images.githubusercontent.com/6561887/150909433-7ddc285f-e90c-44f2-801a-58cbfa6103df.png">

I'm going to try it now that I know about it.
