### ISSUE TITLE
TypeScript debugger (Watch) incorrectly gives "Uncaught ReferenceError: <class> is not defined" for extern classes in another file

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode#130517]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.59.0
- OS Version: Windows.

Steps to Reproduce:

1. Use test.ts with
```
import {
    Task, TaskProvider
} from 'vscode';

export class CppBuildTaskProvider2 implements TaskProvider {
    static CppBuildScriptType: string = 'cppbuild';

    public async provideTasks(): Promise<Task[] | undefined> {
        return undefined;
    }

    public resolveTask(_task: Task): Task | undefined {
        return undefined;
    }
}
```
2. Debug an existing extension that references the CppBuildTaskProvider2.CppBuildScriptType and add that to the Watch window, e.g.
```
import { CppBuildTaskProvider2 } from './test';

export function activate(context: vscode.ExtensionContext) {
    let errMsg: string = CppBuildTaskProvider2.CppBuildScriptType;
}
```

Bug: See the screenshot: The debugger (Watch window) gives `Uncaught ReferenceError: CppBuildTaskProvider2 is not defined`.

![image](https://user-images.githubusercontent.com/19859882/128936673-adbd8ead-4dd4-48ae-af89-0e02e26e1a77.png)

Note that the value can be seen via assigning it to a local variable.

**Comment by connor4312** [comment]
This is because TypeScript doesn't expose that as a local and instead rewrites the import, for instance if you look at the compiled code:

<img width="694" alt="image" src="https://user-images.githubusercontent.com/2230985/129240479-b99ba663-8ee9-4f41-9780-b42a594afbbf.png">

It's a feature request on TS to emit a `names` mapping for imports https://github.com/microsoft/TypeScript/issues/9627
