### ISSUE TITLE
Feature Request - Vertical selection for multiple lines

### ISSUE THREAD

**Issue by csanctis** [microsoft/vscode#130544]
In Visual Studio you can make a vertical selection using ALT + Down (or up).
This selects a "column", instead of a line. 
It would be very nice to have this feature in Vs Code as well.
Thank you.

**Comment by yume-chan** [comment]
In my Visual Studio, press <kbd>Alt</kbd>+<kbd>Down Arrow</kbd> also moves the current line downward.

Column selection is <kbd>Shift</kbd>+<kbd>Alt</kbd>+<kbd>Down Arrow</kbd> for Visual Studio and <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>Down Arrow</kbd> for Code.

**Comment by csanctis** [comment]
Ctrl+Alt+Down Arrow does move the cursor down. Thank you for that.
But I still can't select things. What am I missing?

**Comment by ArturoDent** [comment]
It isn't clear to me exactly what you are trying to do.  Ctrl+Alt+Down Arrow  puts another cursor in the line below.  How are you trying to select from there?

Perhaps `Menu/Selection/Column Selection Mode` is what you are looking for?

**Comment by wayneschwebel** [comment]
Not sure if I am talking about the same thing here but I often use column selection with the mouse. It is really useful for bulk editing long lists of properties etc. The column selection mode in VSCode is not quite the same as the column/block selection in most other editors. Hence I find myself having to copy out code, fixing it then copying back.

Eg. In Visual Studio, Notepad++, SSMS, etc. you can hold Alt and draw a rectangular selection with the mouse i.e. a column and insert text there. This works whether there is text there currently or not. VSCode kind of does a similar thing but puts the multiline cursors at the end of each line so that they are not in a column which is much less useful.

Here is an example of what I mean - apologies if it not what was originally meant:
https://imgur.com/a/W7fDi77

**Comment by alexdima** [comment]
We support quite a few of the basic gestures of column selection. There are multiple ways to get into that:
* toggle the mode on using `Selection > Column Selection Mode` and then use the mouse to create column selections
* use the middle mouse button to create column selections
* use the column selection commands (bound on Windows) at `ctrl+shift+alt+arrows`.
