### ISSUE TITLE
[Test API] Add command for running tests by ID

### ISSUE THREAD

**Issue by TimWebb** [microsoft/vscode#130525]
Currently there are commands to run a test at the current cursor (`testing.runAtCursor`) and all tests in the current file (`testing.runCurrentFile`). For advanced integrations, it would be superb to have exposed the ability to run tests by ID (`testing.runTestsByID`) with an ID array and Run/Debug argument passed in.

The implementation of the command ([`testing.contribution.ts`](https://github.com/microsoft/vscode/blob/9125758184ff189d4277f6ff700fe863d01389a2/src/vs/workbench/contrib/testing/browser/testing.contribution.ts#L195)) appears to already be available in the render layer but it is not exposed currently to extensions - trying to use it results in no error, but also no tests being invoked.

**Comment by connor4312** [comment]
Due to the architecture of testing I don't think this command would be useful. Test items are only locally-unique, multiple test extensions can have the same test by ID. You'd need to pass the test run item to identify what test to run... and if you have that, you're the extension providing the test, so you can just create your own `TestRunRequest` and call `TestController.createTestRun` directly and not bother with going through a command.
