### ISSUE TITLE
'Developer: Inspect Editor Tokens and Scopes' doesn't seem to work

### ISSUE THREAD

**Issue by berlunt** [microsoft/vscode#130582]
Issue Type: <b>Bug</b>

Syntax highlighting seems to be broken for a project I am working on. When I try to use 'Developer: Inspect Editor Tokens and Scopes' to debug the issue, it either displays a 'Loading...' box indefinitely or flashes up a loading box which immediately disappears. I have tried forcing a retokenize but that didn't seem to fix the issue

VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:12.822Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD FX(tm)-8350 Eight-Core Processor            (8 x 4018)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.98GB (10.10GB free)|
|Process Argv|. --crash-reporter-id 88d64c34-a0f1-4e14-b0a1-34fcca6e9972|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
cppincludeguard|aki|1.5.0
todo-tree|Gru|0.0.213
output-colorizer|IBM|0.1.2
better-cpp-syntax|jef|1.15.6
python|ms-|2021.8.1105858891
vscode-pylance|ms-|2021.8.0
jupyter|ms-|2021.8.1195043623
cpptools|ms-|1.5.1
code-settings-sync|Sha|3.4.3
go-to-method|tri|0.2.0
cmake|twx|0.0.17

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30322571
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
vstre464:30350172
bridge0723:30350414

```

</details>

**Comment by FireCubez** [comment]
I'm getting this aswell, with a custom extension.

**Comment by FireCubez** [comment]
Nevermind, the extension tmLanguage was invalid.

**Comment by alexdima** [comment]
It looks like the issue is caused by one of your installed extensions. In order to narrow down the possible problematic extension, please try the following:
* run `F1 > Help: Start Extension Bisect`
* (this will restart VS Code with half of your extensions disabled)
* try to do the steps which reproduce the problem
* if the problem reproduces, click "This is bad" (this narrows down the problematic extension to the half which was enabled)
* if the problem does not reproduce, click "Good now" (this narrows down the problematic extension to the half which was disabled)
* these steps will repeat until the problematic extension is found

| initial | step | final |
|---|---|---|
| ![image](https://user-images.githubusercontent.com/5047891/101918658-e9170f80-3bc9-11eb-9977-857baa291937.png) | ![image](https://user-images.githubusercontent.com/5047891/101918683-ef0cf080-3bc9-11eb-9f9e-98b0177991b2.png) | ![image](https://user-images.githubusercontent.com/5047891/101918706-f502d180-3bc9-11eb-8c86-e56355958bd4.png) |
