### ISSUE TITLE
Can't install some extensions on remote - ssh server -> "self signed certificate in certificate chain"

### ISSUE THREAD

**Issue by afaul** [microsoft/vscode#130651]
- VS Code Version: 1.59 and newer
- OS Version: Windows 10 20H2 and Linux on remote server (Archlinux and Ubuntu 20.04)

Steps to Reproduce:

I am using vscode behind a company proxy with man-in-the-middle functionality. The company own root-ca-certificate is installed (and trusted) on the windows PC and on the Linux servers. Also the environment variables HTTP_PROXY and HTTPS_PROXY are set correctly.

1. connect to a remote server using the Remote - SSH extension (ms-vscode-remote.remote-ssh) with a ssh-key
2. try to install the Python extension (ms-python.python) or the Docker extension (ms-azuretools.vscode-docker) on the remote server.

Result:
You get the error message "self signed certificate in certificate chain" and the extension is not installed.
Interestingly the error occurs not on all extensions. For example the extension markdownlint (davidanson.vscode-markdownlint) can be installed without a problem.

The setup is working flawlessly up to (and including) the vscode version 1.58.2.

![2021-08-12_08-58-57](https://user-images.githubusercontent.com/2780574/129152006-2c4581e6-9ef3-46c5-a2c6-bd2c2158f157.png)

![2021-08-12_08-40-11](https://user-images.githubusercontent.com/2780574/129151129-a71ab5a9-7da7-40ab-9092-191e62f26790.png)

**Comment by chrmarti** [comment]
@sandy081 Did anything change with extension downloading between 1.58.2 and 1.59? There were no changes in the certificates support.

**Comment by J0F3** [comment]
I have exactly the same problem but connected to WSL instead of a SSH Host.
But I have the same error when trying to install the python extension and as well with the docker extension for example. However the installation of markdownlint (davidanson.vscode-markdownlint), for example, work also for me without any problems. 

So I is very strage because it affects only certain extensions and other can still installed without any issues. 

![image](https://user-images.githubusercontent.com/12759579/129704677-31bc22a8-6c50-455b-be0d-f1028f6a9fc8.png)


I am also behind  a company proxy resp. firewall with TLS-Inspections (man-in-the-middle) functionality and have set the `NODE_EXTRA_CA_CERTS` environment variable in WSL which points to CA Certs of the internal CA used by the firewall. So it look almost as have the variable no effect for VS Code which then leads to the cert errors. 

I have also tried to install the docker extension manually via VSIX file but I get the same error.

Furthermore, both, the docker and python extension can be installed in Windows without any problem but just not in a WSL Window.

**Comment by afaul** [comment]
I have also tested to set the environment variable `NODE_EXTRA_CA_CERT` on the SSH Host. The variable didn't change the behavior of VS Code.

**Comment by sandy081** [comment]
> Did anything change with extension downloading between 1.58.2 and 1.59?

I do not think so.

**Comment by J0F3** [comment]
@chrmarti @sandy081 FYI: I have opened an issue in the vscode-remote-release repo with more information and logs because, after some more troubleshooting, I think it is more an issue with the remote-server than with VS Code itself.
https://github.com/microsoft/vscode-remote-release/issues/5482

**Comment by afaul** [comment]
I have tested it now with the published version 1.60.0 and it works again.
Thank you
