### ISSUE TITLE
nao tem saida logica

### ISSUE THREAD

**Issue by romuant** [microsoft/vscode#130689]
Nós escrevemos os dados necessários em sua área de transferência porque era muito grande para ser enviado. Por favor, Cole.

**Comment by rzhao271** [comment]
@romuant It looks like you forgot to paste. Can you provide more information on the issue?

**Comment by heynan0** [comment]
Translation from Portuguese:
Title: "there isnt logical exit"
Description: "We wrote the necessary data in your (copy) clipboard because it was too big to be sent. Please, paste"

---

I don't think there is anything actionable here. The text does not make sense, unless the person actually misplaced the text.

**Comment by rzhao271** [comment]
Closing until we get more info.
