### ISSUE TITLE
Notebook is not rendered if file is created through File > New File > Save as...

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode#130697]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.60.0-insider
- OS Version: Windows 10

If you create a new file from the file explorer called "hello1.ipynb", the new notebook file is rendered as expected. However, if you do File > New File... and save the file as "hello.ipynb", it won't render it properly

Steps to Reproduce:

1. Open a folder
1. Go through File > New File... > Ctrl + S > save as "hello.ipynb"

![image](https://user-images.githubusercontent.com/45497113/129236188-f9ed463f-f31f-4b91-b945-40942035e2a9.png)

I'd expect it to render like this (same as if I had clicked on the file icon in the file explorer)

![image](https://user-images.githubusercontent.com/45497113/129236396-fc52e9a7-c4ee-4584-aab0-beb4ceac0e5f.png)

**Comment by rebornix** [comment]
@lramos15 I guess this code path is not reading editor override.

**Comment by lramos15** [comment]
This sounds a lot like https://github.com/microsoft/vscode/issues/81832 which didn't really have plans around getting fixed but I understand the use case and will investigate it. 

@bpasero Do you think it's best if we always call replace editors here? It's already an editor input which is why we don't see the resolver being called

**Comment by bpasero** [comment]
@lramos15 we do call `replaceEditors`:

https://github.com/microsoft/vscode/blob/64081da3c8c12eddc28eaff05672fe9515e7e502/src/vs/workbench/services/editor/browser/editorService.ts#L1100-L1100

The flow is this:
* all editor inputs implement `save` and `saveAs` method
* they can return a different `IEditorInput` to signal that the editor should replace (this happens when you save untitled)
* unfortunately that bypasses our override logic because the input is typed

Even if we where to change `IEditorInput.save/saveAs` to return `IUntypedEditorInput`, we would probably still have an issue because most `toUntyped` implementations in editors set the `override` so that the editor override logic is disabled too.

I guess we have to decide what to do here: you begin with a text editor and so the resulting editor after saving is a text editor too, which imho is consistent. If you really want to create an untitled notebook, I would rather suggest to use the associated command for opening an untitled notebook?

For example GitHub issues notebook provides this:

![recording](https://user-images.githubusercontent.com/900690/129437322-7912882f-94c1-48f7-b693-ab3ce823332d.gif)

**Comment by luabud** [comment]
@bpasero I agree ideally users would trigger the "new notebook" command, but it's not very discoverable for new users 🤔 I think the most intuitive thing to do is to create a new file from File > New File... (or at least it's what we see new users doing the most on user studies). 
I agree that if you started with a text file, keeping it as a text file is consistent. But I think that people who save a file as ipynb specifically would not expect it to be rendered as a text file, simply due to the nature and expectations of what a notebook file should look like in VS Code. But I guess special-casing it for notebooks might be tricky?

**Comment by bpasero** [comment]
I agree and I would think we need a solution for the discoverability issue. I think https://github.com/microsoft/vscode/issues/114958 is for that.

**Comment by luabud** [comment]
Oh good point, https://github.com/microsoft/vscode/issues/114958 would be a great solution for this. 

Closing this in favour of #114958 and https://github.com/microsoft/vscode/issues/81832.
