### ISSUE TITLE
Use language guessing when opening files without extensions

### ISSUE THREAD

**Issue by AlexDev2020** [microsoft/vscode#130642]
I would like the language to be automatically detected when opening the C ++ library header file without an extension (for example, vector). It is not very convenient to use association files.

https://github.com/microsoft/vscode-cpptools/issues/7934

**Comment by TylerLeonhardt** [comment]
I like this idea. I think initially, we should have the "Auto Detect" option in the Language Picker run through our ML model just like Untitled files:
![image](https://user-images.githubusercontent.com/2644648/129260151-1178d909-75b5-425a-9a91-9cd66f674b29.png)

Or have the detected languages show up in the picker:
![image](https://user-images.githubusercontent.com/2644648/129260101-9ee5b58b-217a-4dc9-8bcd-73f6ecfdb467.png)

I'm partial to the former because it makes the quick pick load faster...

**Comment by TylerLeonhardt** [comment]
This is in insiders already :)
