### ISSUE TITLE
No warning on quit if running code

### ISSUE THREAD

**Issue by Yodude120** [microsoft/vscode#130664]
Issue Type: <b>Feature Request</b>

Hello,

I've noticed multiple times the following issue on Visual code studio. 

Namely, when quitting the app or closing a window on macOS, there is no warning given by the app in case code is currently running (whether normally or in debug mode). This should not be so -- sometimes accidentally quitting the app or accidentally closing the window can cause loss of running experiments etc.

A warning should be given if quitting the app or closing a window when a code is running / being debugged.

Thank you

VS Code version: Code 1.59.0 (Universal) (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:14:40.191Z)
OS version: Darwin arm64 20.6.0
Restricted Mode: No

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog for now to gather more feedback. Thanks

In order to implement I suggest that the `debugService` listens to `lifecycleService` and reacts on shutdown.
Example how this is done in other places https://github.com/microsoft/vscode/blob/main/src/vs/workbench/services/workspaces/electron-sandbox/workspaceEditingService.ts#L67

**Comment by roblourens** [comment]
Seems similar to `terminal.integrated.confirmOnExit`

**Comment by isidorn** [comment]
Assigning to August since I think you already added it.

**Comment by bpasero** [comment]
Shouldn't this be a boolean setting, why is it a enum with 2 choices: `always` and `never`?

**Comment by isidorn** [comment]
Maybe for future smartness? In case we want to fine tune this later.

**Comment by roblourens** [comment]
Yeah, the terminal version has 3 options, and it's easy to imagine adding something extra for debug too.
