### ISSUE TITLE
[folding] Expand folded section when entering text on first line

### ISSUE THREAD

**Issue by fronteed** [Microsoft/vscode#13073]
- VSCode Version: 1.5.3
- OS Version: OS X

Steps to reproduce shown on video.
Code folding is considered buggy, expected behavior is attached (SublimeText).
Video: http://take.ms/C3V2H

**Comment by joaomoreno** [comment]
Thanks for the video!

**Comment by fronteed** [comment]
@joaomoreno you're welcome!

**Comment by aeschli** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.
If you disagree and feel that this issue is crucial: We're happy to listen and to reconsider.
Maybe you want to give it a try yourself and provide the feature through an extension or a PR: We're happy to give advise and get you started.
Thanks for your understanding. Thanks for helping and happy coding!
