### ISSUE TITLE
Notebook Cell Output not generated 

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#130789]
**Steps to repro**
* Latest VS Code Insiders
* Custom branch of Jupyter extension (se below)
	PR in Jupyter extension https://github.com/microsoft/vscode-jupyter/pull/7100
	* Use the VSIX generated in the above PR (one of the assets in the CI is the Jupyter VSIX)
	* Or use the corresponding branch of the above PR

**Please note:**
As we're no longer awaiting on the promises, any errors thrown will be ignored completely.
We don't even await on `<Execution Task>.end`

**Steps to repro**
Run the following cell, the expected outupt is `999\n Done: xxxx`
Sometimes, we don't get anything in the cell output.
If you are unable to repro, please change the counter from `1000` to `10000` or `3000` or other.
No idea what the magic number is, for some reason `1000` repros the bug, but `10,000` does not!
```python
from timeit import default_timer as timer
from IPython import display

start = timer()

for i in range(1000):
    display.clear_output()
    print(i)

end = timer()
print(f"Done: {end - start}")
```

@roblourens /cc

**Comment by roblourens** [comment]
First, the `assertIndex` check for an output item edit is not quite right because it's valid for an extension to be editing an output that was removed, when this has happened in the main process but is not synced back to the EH. 

@rebornix I'm just making this not throw. It doesn't necessarily indicate a bug, but could still be useful for troubleshooting, do you think it should be logged somewhere?

Second, sometimes the EH process gets stuck processing lots of edits when it is supposed to send an update every 10ms. Then the renderer is stuck processing a huge update. Fixing to guarantee that an update will be sent from the EH every x ms.

Then the rendering is still slow on the frontend.

**Comment by roblourens** [comment]
Realized that this is not what I thought it was. What @rebornix said this morning made me realize that this should happen much more often than it does. Debugged more and realized that the extension does have special handling for this case, which is working. But sometimes the message gets split where the newline comes in a second update.

```
Info Jupyter Extension: 2021-08-18 15:50:03: KernelMessage = CleanOutput
Info Jupyter Extension: 2021-08-18 15:50:03: KernelMessage = StreamMessage Cell Index 0, Stream 'stdout 659

Info Jupyter Extension: 2021-08-18 15:50:03: KernelMessage = CleanOutput
Info Jupyter Extension: 2021-08-18 15:50:03: KernelMessage = StreamMessage Cell Index 0, Stream 'stdout 660

Info Jupyter Extension: 2021-08-18 15:50:03: KernelMessage = CleanOutput
Info Jupyter Extension: 2021-08-18 15:50:03: KernelMessage = StreamMessage Cell Index 0, Stream 'stdout 661
Info Jupyter Extension: 2021-08-18 15:50:03: KernelMessage = StreamMessage Cell Index 0, Stream 'stdout 

Info Jupyter Extension: 2021-08-18 15:50:09: KernelMessage = CleanOutput
Info Jupyter Extension: 2021-08-18 15:50:09: KernelMessage = StreamMessage Cell Index 0, Stream 'stdout 662

Info Jupyter Extension: 2021-08-18 15:50:09: KernelMessage = CleanOutput
Info Jupyter Extension: 2021-08-18 15:50:09: KernelMessage = StreamMessage Cell Index 0, Stream 'stdout 663
```

When that happens, the extension sends an appendOutput, then a replaceOutputItems. NotebookTextModel can't handle getting those two in the same batch because it looks for a cell with the given output id, before the append has been processed.

**Comment by roblourens** [comment]
This morning I mentioned another issue with getting outputs with an undefined `data`. I can't repro that today.
