### ISSUE TITLE
Unable to update a config value with this syntax

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#13071]
I would like to update a config value by first getting it and then calling update:

```typescript
const config = vscode.workspace.getConfiguration('files.autoSave');
config.update('', 'afterDelay', true);
```

First of all, it seems weird that I have to provide a key in the update method because all I want is to update the config value I received previously. So I would assume the key to be optional in that case.

Second, it does not work at all and I always end up with: `Unable to write to the configuration file (Unknown Key)`

The only thing that does work is:

```typescript
const config = vscode.workspace.getConfiguration('files');
config.update('autoSave', 'value', true);
```

**Comment by jrieken** [comment]
Unhappy but the way it is since day one - `getConfiguration` can only be used to get a node but not a leaf. You should be able to call `getConfiguration('').update('files.autoSave')` or `getConfiguration('files').update('autoSave')`. The same is true for `get` and `has`.

I think for extension writers this isn't too alien because they usually scope their configuration to their extension. You'd writing something like `const config = getConfiguration('myExtension')` and the work with that object.

**Comment by shanalikhan** [comment]
i have tried with this syntax getting error as : `Unable to write to the configuration file (Unknown Key)` - code 0
```
 const config = vscode.workspace.getConfiguration('sync');
        config.update('token', 'value', true).then(function(a){
            debugger;
        },function (b) {
            debugger;
        });
```
