### ISSUE TITLE
Notebook UI not updated with changes to the model

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#130790]
**Please use**
* Latest VS Code Insiders
* Custom branch of Jupyter extension (se below)
	PR in Jupyter extension https://github.com/microsoft/vscode-jupyter/pull/7100
	* Use the VSIX generated in the above PR (one of the assets in the CI is the Jupyter VSIX)
	* Or use the corresponding branch of the above PR

**Please note:**
As we're no longer awaiting on the promises, any errors thrown will be ignored completely.
We don't even await on `<Execution Task>.end`

**Steps to repro**
Create first cell with the following code:
```python
from IPython.display import Markdown
dh = display(display_id=True)
```
Run the above cell, then run the following cell:
```python
dh.update(Markdown("foo"))
```

After you run the second cell, the first cell should have an output `foo`.
Collapse the first cell & expand it, and you'll see `foo` appear, basically its a refresh issue.

**Comment by roblourens** [comment]
@rebornix This one I don't really understand. Seems like if you create an empty output, then append items to it, the items won't be rendered because of https://github.com/microsoft/vscode/blob/a00ac538b31ceb2cda329100239339d4e5ecbd2e/src/vs/workbench/contrib/notebook/browser/view/renderers/cellOutput.ts#L141
