### ISSUE TITLE
Surround a text/word with special characters

### ISSUE THREAD

**Issue by danielschmitz** [Microsoft/vscode#1307]
Surround a text/word with special characters by selecting it and pressing the special character.

**example:**

![](http://i.imgur.com/HO1jUEz.gif)

**Comment by hashhar** [comment]
Woah!!! We need this, but this looks to be better suited as an extension really. It should some kind of modifier key though because I sometimes would like to replace a word with a special character.

Maybe `Alt + special character`?

**Comment by dbaeumer** [comment]
@bpasero Ben, start with you here since this sounds like a mark down feature. I think there is no underlying support needed in the editor to make this happen.

**Comment by danielschmitz** [comment]
Hello guys, its a mark down "native" feature.

Thanks

**Comment by OceanAirdrop** [comment]
Yes, this is similar to the plugin for the brackets IDE. 

Very useful for wrapping html elements around selected text.

http://www.granneman.com/webdev/editors/brackets/extensions/surround/
https://github.com/pedelman/brackets-surround

+1 from me!

**Comment by JVimes** [comment]
Great in any language for quotes/brackets/parens. User expects to be able to overwrite text by highlighting and typing, so @hashhar's suggestion is on the right track. Alt might not work right on Mac, since it's already used by the system to insert special characters (like ÷«“‘ªº). But other modifier(s) should.

**Comment by jorgeas80** [comment]
Need this!

**Comment by hashhar** [comment]
Maybe someone can take a look at how they implemented the surround with quotes to get an idea to extend it. I think after v1.6 we could select text and press `"` or `'` and that surrounded the text.

**Comment by M-Zuber** [comment]
What I would want is full `surround with` like exists in Visual Studio [see here for super quick intro](https://msdn.microsoft.com/en-us/library/6hf704tz.aspx) which would let me use any snippet in addition to punctuation.
It is very handy for things like moving code into an `if` or `try/catch`. 

The far dream would have us be able to declare an arbitrary punctuation pair and use that like we can now with `()`, `[]`, ect.

Most of this functionality could be hidden behind a shortcut like `ctrl+k, s` for those who are worried about it interfering with basic typing.

**Comment by stannynuytkens** [comment]
Was suprised to see the behaviour for markdown files concerning surrounding selected text with the typed character is different from say js, html, css, ... files. Was this by design intended to exclude md files?

**Comment by sethlivingston** [comment]
Parity with Visual Studio would be great here. I know it _can_ be an extension, but IMHO this should be built in or a pre-installed extension.

**Comment by spacegoing** [comment]
How can I enable this feature in markdown files? Which command implements this?

**Comment by mjbvz** [comment]
I just pushed 8fbad6e which adds the for markdown using snippets. To use it, select some text in markdown and trigger the `insert snippet` command. The bold, Italic, and inline code snippets for markdown all have this enabled now.

Here's a quick explanation on why this approach was selected and how other extensions/languages can implement this sort of functionality:

For basic surround logic, extensions can use the `surroundWith` language configuration option. Adding `*` for the `surroundWith` in the [markdown language configuration](https://github.com/Microsoft/vscode/blob/master/extensions/markdown/language-configuration.json) allows the behavior that @danielschmitz originally described. `surroundWith` can also be configured separately from `autoClosingPairs`.

However, in testing, I was concerned that `surroundWith` for `*` and other special characters may get in the way of too many users. That's why I went with a more explicit snippet based approach. This makes use of the `TM_SELECTED_TEXT` value present in snippets:

```json
	"Insert bold text": {
		"prefix": "bold",
		"body": "**${1:${TM_SELECTED_TEXT}}**$0",
		"description": "Insert bold text"
	},
```

Any extension can contribute snippets that make use of this pattern. Feel free to submit a PR if you would like any of the [other markdown snippets](https://github.com/Microsoft/vscode/blob/master/extensions/markdown/snippets/markdown.json) to use  the surround logic as well

---

Please let me know if you have any questions or concerns about the current approach
