### ISSUE TITLE
Error: "File system provider for vsls:/ is not available". This error is showing up whenever I try to open a folder in Visual Studio Code

### ISSUE THREAD

**Issue by ThatGenZGamer48** [microsoft/vscode#130853]
Dear developers of Visual Studio Code,

Error: "File system provider for vsls:/ is not available". This error is showing up whenever I try to open a folder in Visual Studio Code. This problem has been persisting since I had installed Visual Studio Code Live Share Extension. I have tried disabling and uninstalling the extension but it doesn't seem to solve the problem. It would be much appreciated if developers of VSC could fix this... Please find the screenshot of the error attached below.

Error:
![image](https://user-images.githubusercontent.com/78960084/129472628-9d0bf6cf-b60f-4a6e-9a04-cac5f72777bb.png)

Thank you!
Regards,
That GenZ Gamer

**Comment by jrieken** [comment]
Looks like hanging workspace folder or file that wants to be resolved

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.
