### ISSUE TITLE
Code OSS Dev Language pack

### ISSUE THREAD

**Issue by NightRaidGamer** [microsoft/vscode#130861]
I tried to install several different language pack extensions and it didn't work, why? in the official code vs works normally

(the extensions install I restart the oss code, but it has no effect)

**Comment by dbaeumer** [comment]
Language Packs are not supported when running out of source. They only work in a built version. This is by design.

**Comment by NightRaidGamer** [comment]
> Language Packs are not supported when running out of source. They only work in a built version. This is by design.

so how do i make it work manually?

**Comment by dbaeumer** [comment]
You can't when running out of source.

**Comment by NightRaidGamer** [comment]
> You can't when running out of source.

but so, where are the files responsible for OSS-DEV coming in english by default then?

**Comment by TylerLeonhardt** [comment]
> but so, where are the files responsible for OSS-DEV coming in english by default then?

The gist is, when we build VS Code for releases (insiders or stable) it rewrites the `localize(...)` you see in our sources with a totally different function that is able to handle language packs. This is done during our bundling but for OSS we don't do any bundling because that would increase the build time by a significant amount.

That's why Language Packs don't work in OSS. The default `localize()` function (non-bundled) simply uses the strings in the source which all happen to be English because that's the language we decided would be the default for the source since everyone on the team speaks English.
