### ISSUE TITLE
Explorer file paste forgets source directory structure

### ISSUE THREAD

**Issue by shoffmeister** [microsoft/vscode#130814]
Issue Type: <b>Bug</b>

When doing a copy&paste of files inside the Explorer view, with the source set of files containing a directory structure, the pasted files do not follow this directory structure any more.

```
mkdir repro
mkdir repro/sub1
mkdir repro/sub1/sub2
touch repro/sub1/file1
touch repro/sub1/sub2/file2

mkdir repro/my-target
```
* Open `repro` directory as a folder in vscode
* Select `sub1/file1` and `sub1/sub2/file2`
* Copy
* Paste -> `target`

//exp - alternative 1 (easier to implement)
target/file1
target/sub2/file1

//exp - alternative 2 (my preference)
target/sub1/file1
target/sub1/sub2/file1

//act:
target/file1
target/file2

The defect here is that the "sub2" directory is getting lost; this is quite annoying if file1 has relative path addressing into sub2, e.g. as in "include conf.d/*"

VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:20.182Z)
OS version: Linux x64 5.13.8-200.fc34.x86_64
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2903)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|31.31GB (19.33GB free)|
|Process Argv|--unity-launch --crash-reporter-id 80e0ae97-0bc4-4a76-8337-f435f2ec1554|
|Screen Reader|no|
|VM|100%|
|DESKTOP_SESSION|/usr/share/xsessions/plasmax11|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.5.1
gitlens|eam|11.6.0
vscode-drawio|hed|1.6.1
rust-analyzer|mat|0.2.702
vscode-docker|ms-|1.15.0
python|ms-|2021.8.1105858891
vscode-pylance|ms-|2021.8.1
jupyter|ms-|2021.8.1195043623
remote-containers|ms-|0.191.0
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.58.2
vscode-remote-extensionpack|ms-|0.21.0
powershell|ms-|2021.8.0
fabric8-analytics|red|0.3.3
vscode-commons|red|0.0.6
vscode-xml|red|0.18.0
vscode-yaml|red|0.22.0
even-better-toml|tam|0.14.2
vscode-lldb|vad|1.6.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
vstre464cf:30350173
bridge0723:30351747
javagetstartedc:30351792

```

</details>

**Comment by JacksonKearl** [comment]
Thanks for the request! I do like this idea but I will be marking this as an issue solvable via an extension. 

Extensions can contribute commands to the Explorer's context menu, an extension could contribute a "Copy (preserve relative paths)" and "Paste (preserve relative paths)" command set to accomplish this. We wouldn't want to change the default behavior in core as folks have already been using this for a while, and there are simply too many different nuances to the problem to provide options in core that meet an individual's expectations. 

See here for more info https://code.visualstudio.com/api/references/contribution-points#contributes.menus

This issue: https://github.com/microsoft/vscode/issues/3553 would allo the command to be triggered by a keybinding rather than context menu.
