### ISSUE TITLE
Feature: Close multiple git submodules/repositories at the same time

### ISSUE THREAD

**Issue by irgendwr** [microsoft/vscode#130923]
At work we use a lot of git submodules. I often want to close multiple submodules/repositories in vscode, which is not possible at the moment - I have to right-click and close them one by one.

To solve this I'd suggest implementing at least one of the following:
- A) Close all repositories that are selected instead of just the one right-clicked.
- B) Add an option to close all other repositories (similar to how browsers provide an option to "close other tabs")
  #130931

  !["Close Other Repositories" in git scm menu](https://user-images.githubusercontent.com/17804578/129612304-d7236243-cdc4-4fb6-a84c-f76c62e235a3.png)

**Comment by irgendwr** [comment]
Hey @lszomoru, considering that this has been open for almost a year now, would it be possible to merge #130931 in the meantime?

The PR only implements one part of the suggested solutions but would already be very beneficial for the described use-case and the code changes are kept to a minimum. Let me know if there is something that I can do to resolve this issue.

**Comment by narimiran** [comment]
>  I often want to close multiple submodules/repositories in vscode, which is not possible at the moment - I have to right-click and close them one by one.

The option to close multiple repositories would be really welcome.

It's been almost two years since this issue was open.... :'(

**Comment by fschuh** [comment]
+1 on being able to close multiple selected repositories.  

This would be very useful for dealing with dozens of repositories and being able to quickly hide the ones we're not currently making any changes to.  

It's disappointing that, despite selecting multiple repositories, the _Close Repository_ right-click action will only close the one under the mouse cursor. To close them all we have to spam the action multiple times.  

Reopening closed repositories is very easy, so I don't see any UX downsides to just plain closing all selected repositories.
If this is still a concern, a separate action like _Close All Selected Repositories_ could also be an option.

**Comment by Stabledog** [comment]
+1 to "close all repositories".  I suffer from this frequently...

**Comment by lszomoru** [comment]
@Stabledog, could you please elaborate on your scenario in which you would like to close all repositories?

**Comment by lszomoru** [comment]
@narimiran, thanks for the information. Given the information, do you really want to close **all** repositories, or would you like to just close all git-submodules? Also, have you considered setting `git.autoRepositoryDetection` to `subFolders`  so that repositories from open files are not being opened?

**Comment by Stabledog** [comment]
> @Stabledog, could you please elaborate on your scenario in which you would like to close all repositories?

I'm a teacher.  I have a bunch of repos which act as a host environment for repos that belong to students.  I have scripts that do things like "show me the server.py file for everything in students/*/project".   Each one of those is its own repo with student code.

So now I have 50 source files open, and I can page through them rapidly, comment on the code, etc.   But if I want to do anything specific with any one of the git working copies, I must do that from the command line because the VScode git plugin is a hopeless sea of open repo nodes, with no ability to filter or sort, no ability to hide or close in bulk... it's just useless in this situation.

Having a "close all" would allow me to at least clean the slate so I can pick individuals  to study more closely.

**Comment by lszomoru** [comment]
"Close Other Repositories" has been added to the context menu in https://github.com/microsoft/vscode/pull/200893.

**Comment by narimiran** [comment]
> Given the information, do you really want to close all repositories, or would you like to just close all git-submodules?

No, not _all_. There are two good options (and both should be available, IMO):

1. Close (all) other repositories (this is what https://github.com/microsoft/vscode/pull/200893 does, AFAICT)
2. Close (multiple) selected repositories. User manually selects (control+click or shift+click) multiple repositories that they would like to close.

**Comment by lszomoru** [comment]
Option 2. listed above is tracked here - https://github.com/microsoft/vscode/issues/176717

**Comment by irgendwr** [comment]
I implemented the second option in this PR: #201073
