### ISSUE TITLE
Blank space above integrated terminal for specific settings

### ISSUE THREAD

**Issue by valentjn** [microsoft/vscode#130995]
Issue Type: <b>Bug</b>

**Steps to reproduce:**

1. Install the [Ubuntu font family](https://design.ubuntu.com/font/) (download link is at the bottom of the page).
2. Start vanilla session of VS Code Insiders.
3. Open Command Palette, enter `Preferences: Open Settings (JSON)`, paste the following settings, and save:

```json
{
    "editor.fontFamily": "Ubuntu Mono",
    "telemetry.enableTelemetry": false,
    "telemetry.enableCrashReporter": false,
    "terminal.integrated.fontSize": 16,
    "window.zoomLevel": 0.4
}
```

4. Open Command Palette and enter `View: Toggle Terminal`.
5. Drag the Terminal tab to the Activity Bar and click on it.

**Actual result:** There is blank space above the terminal contents (you can see the effect better when filling the terminal by repeatedly pressing Enter and examining the size of the scrollbar; there is blank space above the scrollbar slider even when scrolled all the way to the top).

**Expected result:** There is little to no space above the terminal contents (the height of the blank space should not exceed the height of one terminal line).

**Additional information:**
- The blank space vanishes when using `0.3` or `0.5` for `window.zoomLevel`.
- The developer tools indicate that the `terminal-split-pane` `div` has the correct height, but the height of the `xterm-screen` `div` is too small.
- Due to firewall restrictions, I'm currently not able to provide screenshots.

VS Code version: Code - Insiders 1.60.0-insider (f0913d7718bbc4a805cd3a051335b4df60ca5d77, 2021-08-17T05:15:18.727Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.59GB (15.51GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by valentjn** [comment]
Here are some screenshots, taken on a different computer with regular VS Code, not Insiders. In the first one, the bug occurs; in the second one, it doesn't due to a different `window.zoomLevel`. I'm not able to always trigger it, it also seems to depend on the window size and the previous settings. If you can't reproduce it right away, try a different `window.zoomLevel` and/or resize the window.

<details>

![blankSpace](https://user-images.githubusercontent.com/19839841/129952043-d511f72c-073d-47de-a8b6-a592cd2cc17c.png)

![noBlankSpace](https://user-images.githubusercontent.com/19839841/129952055-b8b7b790-38b5-45f2-80a1-3bd9a5449e75.png)

</details>

**Comment by meganrogge** [comment]
Thanks for all of the info

**Comment by valentjn** [comment]
@meganrogge Did you perform step 1 of the repro steps correctly? The terminal in your GIF doesn't use Ubuntu Mono as configured, but some other font.

(The editor should be in the same font, but it's Times New Roman or something similar, which strongly suggests that Ubuntu Mono has not been installed correctly.)

**Comment by rafaeldtinoco** [comment]
Happened to me on linux. Changing console font size fixed the issue. I believe its because of the font family being used and availables sizes and miss calculation on terminal cols and rows.

**Comment by rafaeldtinoco** [comment]
![image](https://github.com/microsoft/vscode/assets/7395852/da9a2768-a87f-488c-875b-ddfbc0a75c8f)

Then changing font size:
![image](https://github.com/microsoft/vscode/assets/7395852/203a8170-528b-49fd-b7e2-0177d5a37b20)

**Comment by rnln** [comment]
I've got this peculiar behavior with the integrated terminal on macOS with extensions disabled and default settings. In my screencast, you can see how adjusting the "window.zoomLevel" setting impacts the positioning of the first line in the terminal either raising or lowering it. I guess this occurs when triggering a re-render at specific zoom levels.

Interestingly, I've pinpointed the minimum positive number that triggers this behavior in my setup. It appears that any slight increase in the zoom level, enough to exceed a particular threshold in 64-bit floating point representation, can cause this issue. This smallest triggering value in my tests is 0.000000326920437485165902734277260967277189962487682350911200046539306640625 which is 0011111010010101111100000111001101001010000111000000100000010010, so any number at least one bit greater starting with ...011 causes the padding shift.

Additionally, adjusting the font size also introduces a noticeable top padding either smaller or bigger, though I found the changes due to invisible zoom level adjustments more striking.

https://github.com/microsoft/vscode/assets/41355752/0826f734-5d16-42fc-ad05-5b4ecf20b6d7

**Comment by rafaeldtinoco** [comment]
Yep, pretty much the same thing I'm experiencing. My "workaround" was to set a zoom level and font size compatible with my fixed window size and live with it. But that is the same thing as IM experiencing for sure.

**Comment by vampirefan** [comment]
I got the same problem when I set window.zoomLevel to 1, or terminal.integrated.lineHeight to 1.2. And finally I get it right when I set zoomLevel to 1.05 and terminal.integrated.lineHeight to default 1.

**Comment by rafaeldtinoco** [comment]
Yep, its a mix of setting zoomlevel and fontsize and praying.
