### ISSUE TITLE
Files changing...

### ISSUE THREAD

**Issue by Firefly4266** [Microsoft/vscode#13099]
- VSCode Version: Code 1.5.3 (5be4091987a98e3870d89d630eb87be6d9bafd27, 2016-09-22T08:40:08.699Z)
- OS Version: Linux x64 4.4.0-38-generic

I haven't really found a pattern to it yet but sometimes when I change focus to a different tab, the code in the new tab copies to the tab I just left.  This is a real problem as you can imagine.  All of the sudden my code/servers just crash because vscode replaced chunks of code it wasn't supposed to.  What's worse is it doesn't always change the entire file, sometimes just parts of it are changed which means time wasted on debugging.  Usually Ctrl z can reverse this pretty quickly but the file changes are very disturbing.  I may have to go back to vim...but I'd rather use this tool.

Regards, Jp Gaines

**Comment by mrmlnc** [comment]
Caused by extensions that have the ability to apply formatting when saving a file.

In VS Code 1.6.0 added new API that corrects this problem. See https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/v1_6.md#new-apis (onWillSaveTextDocument). The extension author should to use this API instead of currently solution, but after release 1.6.0.

**Comment by Tyriar** [comment]
@mrmlnc is likely correct. Try tweaking your extensions, please let us know if you can reproduce when launching vscode via `code --disable-extensions`

**Comment by Firefly4266** [comment]
Fyi, if I use the replace all tool built into the side bar and the go to the menu bar file - save all, new code will appear on what ever screen I'm currently on.  Just happened...
