### ISSUE TITLE
The underscore is not displayed at the BOTTOM of terminal

### ISSUE THREAD

**Issue by zzeitt** [microsoft/vscode#130967]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.59.0
- Commit: 379476f0e13988d90fab105c5c19e7abc8b1dea8
- Date: 2021-08-04T23:13:20.182Z
- Electron: 13.1.7
- Chrome: 91.0.4472.124
- Node.js: 14.16.0
- V8: 9.1.269.36-electron.0
- OS: Linux x64 5.4.0-70-generic

Steps to Reproduce:

1. Turn on vscode, open an internal terminal.
2. Enter and enter... until the cursor reach the bottom line.
3. Type in the underscore character '_', it will disappear.

As the screenshot shows, the external terminal display fine.
![image](https://user-images.githubusercontent.com/30381410/129671627-ed2adca0-34db-44a8-93c2-71846eba6c81.png)

**Comment by meganrogge** [comment]
works for me 
![_](https://user-images.githubusercontent.com/29464607/129797238-f875932e-8af1-43a5-8c41-82199e2ff99d.PNG)

**Comment by zzeitt** [comment]
Does this issue occur when all extensions are disabled?: Yes

    VS Code Version: 1.59.0
    Commit: 379476f
    Date: 2021-08-04T23:13:20.182Z
    Electron: 13.1.7
    Chrome: 91.0.4472.124
    Node.js: 14.16.0
    V8: 9.1.269.36-electron.0
    OS: Linux x64 5.4.0-70-generic

--- 

Environment information is shown above. 

I saw your working case, seems like you've tested on Windows, but my problem occurs on Ubuntu OS. Could you debug on Ubuntu too?

**Comment by alkorang** [comment]
@meganrogge 

> let me know of any special settings you have or how I can reproduce the issue

I saw many issues opened because underscore in terminal is not displayed correctly on **Linux**. You had closed all issues except https://github.com/microsoft/vscode/issues/123077, saying they are duplicated. Now, you closed that issue, too, saying that you cannot reproduce it anymore.

Many reported that out-of-the-box vscode terminal cannot display underscores correctly **(1) on Linux**, **(2) at the last line**. You must try to reproduce this issue on Linux as these issues described so. You showed that you cannot reproduce the same issue on Windows and it is unclear whether you reached the last line in the terminal.

This is how you can reproduce this issue:
1. Install any Linux distribution that vscode can run. (I recommend Ubuntu Desktop.)
2. Install vscode and open vscode, open terminal.
3. Press Etner key until the cursor reaches the last line in the terminal
4. Type texts with underscores

I can still reproduce the same rendering error on Debian 10 using out-of-the-box vscode 1.59.0.
![image](https://user-images.githubusercontent.com/11420879/130041688-ddc38da3-c2f7-4bed-84fc-258cb3ad164e.png)

**Comment by Tyriar** [comment]
So this actually appears to be a separate issue than https://github.com/microsoft/vscode/issues/123077, you will notice that in your font the underscore is abnormally low which causes it to get cut off since it's below the cell. This image shows the dimensions of what the cells would be, since the underscore appears below the cell, for the last row it ends up below the terminal.

![image](https://user-images.githubusercontent.com/2193314/130064609-88627f00-a810-4911-8ddc-5d2737f67a4d.png)

The bottom 2 pixels are padding that separates the terminal canvas from the status bar.

It's also worth mentioning that https://github.com/microsoft/vscode/issues/123077 is about the canvas renderer which the underscore issue is now an issue we're not planning on fixing, but you're definitely using the webgl renderer because the underscore is printing beyond its own cell.

I have an idea on fixing this, perhaps we should measure the underscore character in particular and measure if it would get cut off from the line and if so we would draw it custom (this could even be rolled into the upcoming [custom box drawing/block element glyph setting](https://github.com/microsoft/vscode/issues/130406)). This custom drawing could be maybe 1 pixel higher than the underline style such that links and underscore styles can still be differentiated from underscores.

Tracking upstream in https://github.com/xtermjs/xterm.js/issues/3423

**Comment by Tyriar** [comment]
If anyone seeing this issue could let me know which font they're using that would be helpful (`terminal.integrated.fontFamily`, which falls back to `editor.fontFamily`).

**Comment by zzeitt** [comment]
> If anyone seeing this issue could let me know which font they're using that would be helpful (`terminal.integrated.fontFamily`, which falls back to `editor.fontFamily`).

```
"editor.fontFamily": "'Droid Sans Mono', 'monospace', monospace, 'Droid Sans Fallback'"
```
This is my config in vscode.
