### ISSUE TITLE
Pass the activation event to activate function

### ISSUE THREAD

**Issue by kallookoo** [microsoft/vscode#131064]
Hi,
When there are multiple events defined within the "activationEvents", the activate function does not distinguish between them.
It would be a good option that you can know what is the event that started it to do different things and not do everything every time.

**Comment by alexdima** [comment]
> It would be a good option that you can know what is the event that started it to do different things and not do everything every time.

Extensions can activate for multiple reasons, activation events being one of them. Although not very well known, extensions can also activate if another extension depends on an extension or if another extension explicitly activates others via our `vscode.extensions` API. Another use-case is when the extension host process crashes and we re-activate all previously activated extensions. Having an extension behave differently due to the activation event would be a cause of bugs, as in all these less known cases the extension would behave differently. It is therefore intentional that the activation event is not passed in.
