### ISSUE TITLE
Missing localizations in 1.6

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#13103]
- VSCode Version: 1.6 insiders
- OS Version: doesn't matter

**In Menu Items:**

1. Help -> Search (Mac OS X)
2. View -> Toggle Render Whitespace
3. Edit -> Start Dictation (Mac OS X)

**In Settings:**

1. The below is not localized in **User Settings**, but is localized in Workspace Settings
`// Place your settings in this file to overwrite the default settings`

2. The below is not localized in **Keyboard Shortcut settings**
`// Place your key bindings in this file to overwrite the defaults`

**In Launch.json**
Tooltips for all properties except the below are not localized in launch.json

- name
- type
- request
- preLaunch task

**while debugging**

1. The title for the Debug Console in German appears as "DebugKonsole". There should be a space between the "Debug" and the "Console"
2. Add watch for a symbol. When it is not available, the value says "not available" in English

**while closing unsaved files**
The dialog box that appears has text that is not localized

**Comment by Tyriar** [comment]
Not sure translations are meant to be in yet, @dbaeumer should know the story on this.

**Comment by dbaeumer** [comment]
@Tyriar @ramya-rao-a  currently we only ensure full translation for special builds. One of those was 1.5.3. Other builds will always contain a small set of English UI since translation is always 1 - 2 weeks behind. I will close this issue since there is nothing we can do.

**Comment by ramya-rao-a** [comment]
@dbaeumer Almost none of the issues listed here are new features, they should have been translated a long time ago. Do we still expect 1.6 insiders to not have these translated?

**Comment by dbaeumer** [comment]
@ramya-rao-a a good test then is to see if they are translated in 1.5.3. At least View -> Toggle Render Whitespace is. They others are Mac specific.

There is one additional thing to note: restructuring code will 'break' translations. Is if you move code from one location to another then strings will be untranslated for 1  - 2 weeks. The reason is that moving code around doesn't restructure the i18n database. This is done in the translation DB owned by the translation team. We will get 'updated' locations with the next translation.

A save way to find out if strings are translated is to look into the code if the strings has a localize call around it. If so there is nothing a dev can do to fix it. However this checking is best done by the dev who owns the code.

**Comment by ramya-rao-a** [comment]
@dbaeumer Thanks. Got it
