### ISSUE TITLE
The generated getter and setter checkboxes are very inconvenient to use on the left and hope to improve.

### ISSUE THREAD

**Issue by zhouxinghong** [microsoft/vscode#131054]
Issue Type: <b>Bug</b>

The generated getter and setter checkboxes are very inconvenient to use on the left and hope to improve.
![2021-08-15_082147-003](https://user-images.githubusercontent.com/54253524/129831449-60435932-1af5-4e43-b265-68ca84ebb200.png)

VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:12.822Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2494)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|9.59GB (3.09GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details>

**Comment by TylerLeonhardt** [comment]
Granted I come from a LTR world but I've always seen checkboxes on the left side.

At best, I think we could offer a configuration for having the checkboxes on the right side... but I'd only do that work if it's heavily requested because I personally don't think it provides a ton of value. I'll give this feature-request and we'll see how others feel about it.
