### ISSUE TITLE
Add ways to scope access to proposed API

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#131165]
We have a problem currently that if a first party wants to use one of our "forever proposed APIs" like `window.onDidWriteTerminalData`, they need to be added to our enable proposed API list which could lead them to accidentally use other proposed API which is likely to change.

This proposal is about adding a new API type which is stable but not accessible to anyone but close friends because of various concerns we have in making the API public. This would help these trusted parties not accidentally jump on proposed API and also help the general public from not trying out these APIs, I still get the occasional issue every now about someone who has tried `onDidWriteTerminalData` and asking about it being stabilized.

**Comment by jrieken** [comment]
> This proposal is about adding a new API type which is stable but not accessible to anyone but close friends because of various concerns we have in making the API public.

I think this is how much of our proposed API is actually being used. I am not a fan of adding a third mechanism of restricted API or so. It will complicate things IMO.

**Comment by mjbvz** [comment]
One idea we previously discussed was a `vscode.never.d.ts` that tracks apis that we never plan on finalizing

**Comment by Tyriar** [comment]
Sure it will complicate things a little more on our side but it will save first party extensions from mistakenly using proposed API and breaking as a result. I can see how it would be tough to avoid this if your project includes `vscode.proposed.d.ts`.

**Comment by SNDST00M** [comment]
It is a bit of a shame to hear that `onDidWriteTerminalData` will be 'forever' proposed, I am using it in CI and would prefer to not opt into the proposed API in order to use it 😅

**Comment by xiaoice** [comment]
use --enable-proposed-api vscode-samples.proposed-api-sample and enableProposedApi:true
window.onDidWriteTerminalData was not work，help me

**Comment by SNDST00M** [comment]
Did you uninstall `@types/vscode`, install `vscode-dts` and run the dts tasks from the documentation?

**Comment by jrieken** [comment]
> Sure it will complicate things a little more on our side but it will save first party extensions

This is not just about complexity but also about not being able to always cleanly separate things between N `vscode.xyz.d.ts`-files. We have seen that in the past and taken pragmatic approaches but that won't work for another stable/permanent d.ts-file. 

> This would help these trusted parties not accidentally jump on proposed API and also help the general public from not trying out these APIs

This reminds of something that has been discussed previously - instead of giving extensions access to all proposed API they should have access to individual proposals only. This will help us manage the list extensions with access to proposed API and prevent accidental/unwanted API usage.

**Comment by Tyriar** [comment]
:+1: opting into only a single API (or list) would fix the problem as well.

**Comment by jrieken** [comment]
(exploring ideas for september)

**Comment by gjsjohnmurray** [comment]
I like the proposal. Maybe also add telemetry on which proposed APIs are getting enabled. I'm hoping this would provide evidence to get some stalled ones finalized (see #59921 and #73524 for example, though those are the finalisation numbers, not the API ones). 🙏

**Comment by jrieken** [comment]
Moving out for actual implementation

**Comment by jrieken** [comment]
Plan of action

1. break up `vscode.proposed.d.ts` into a file per proposal, like `vscode.proposed.languageStatus.d.ts` and `vscode.proposed.remoteResolver.d.ts` (_Note_ that proposals use names instead of numbers)
1. change the `enableProposedApi`-property to be a list of proposal names. For a grace period interpret `true` as "all proposal names". 
1. adjust our [`checkProposedApiEnabled`](https://github.com/microsoft/vscode/blob/27753407604003e199b270bb0ba504eef8c4beff/src/vs/workbench/services/extensions/common/extensions.ts#L322)-checks to accept a proposal name
1. update the `vscode-dts` command line tool to fetch individual proposals
1. add tooling to generate a list of proposal names (similar to how we generate `monaco.d.ts`). This will help to type-check `checkProposedApiEnabled`-calls and to provide good JSON-schema for `enableProposedAPI`

**Comment by jrieken** [comment]
Pushed https://github.com/microsoft/vscode/commit/799d82fcc3c92933a8bce04cd4178c0cd8f10b3e to ensure `checkProposedApiEnabled` and (new) `isProposedApiEnabled` utils are used

**Comment by mjbvz** [comment]
c20b2c9589fa7374741ffc8383cd529248ef4087 adds unique names to most proposals and added an eslint rule to enforce this. If you own one of these proposals, please update the name if you feel the current one is not accurate 

Skipped a few proposals that wen't clear:

- [ ] @roblourens https://github.com/microsoft/vscode/blob/c20b2c9589fa7374741ffc8383cd529248ef4087/src/vs/vscode.proposed.d.ts#L755

- [ ] @weinand  https://github.com/microsoft/vscode/blob/c20b2c9589fa7374741ffc8383cd529248ef4087/src/vs/vscode.proposed.d.ts#L778

- [ ]  @connor4312  https://github.com/microsoft/vscode/blob/c20b2c9589fa7374741ffc8383cd529248ef4087/src/vs/vscode.proposed.d.ts#L1883 (please make sure there is one proposal per region)

**Comment by weinand** [comment]
@mjbvz I've removed the two DAP "stand-in" types because they would only be used if command arguments were typed. 

For details see https://github.com/microsoft/vscode/issues/70377#issuecomment-682429485

**Comment by connor4312** [comment]
> For a grace period interpret true as "all proposal names".

We can instead snapshot the current list of proposals treat `true` as that list so that extensions are forced to upgrade if they want to use new proposals. Also slightly easier to program 😛

**Comment by jrieken** [comment]
> Currently we cannot publish the vscode-dts npm package, I will get on recovering that.

Perfect - I have https://github.com/microsoft/vscode-dts/pull/9 for the first round of adoption changes

**Comment by jrieken** [comment]
Merged the removal of `enableProposedApi` - it is all `enabledApiProposals` from now on but extensions listed in product.json are still treated special

**Comment by CodeCasterNL** [comment]
@jrieken documentation like [Inline Completions Sample](https://github.com/microsoft/vscode-extension-samples/tree/main/inline-completions) still links to the old file locations (https://github.com/microsoft/vscode/commit/a4d426a1c2ece4222f1343459d31fe948098b2f6).

**Comment by GusSand** [comment]
There's a bunch of things that seem to need to change in the samples that reference the new API:

Documentation - already mentioned
package.json - how to modify it to add the proposed API
post install script - needs to be updated to download the correct file.
thanks!
