### ISSUE TITLE
Bundled icon theme should be a Visual Studio icon theme

### ISSUE THREAD

**Issue by felixfbecker** [Microsoft/vscode#13114]
VS Code shares a lot of design with Visual Studio, which looks awesome. I think the default, bundled icon theme should be a Visual Studio icon theme. The nomo theme comes pretty close: https://marketplace.visualstudio.com/items?itemName=be5invis.vscode-icontheme-nomo-dark

**Comment by felixfbecker** [comment]
This theme does it perfectly: https://marketplace.visualstudio.com/items?itemName=jtlowe.vscode-icon-theme

Just bundle it, it fits so much better with the rest of the design than the currently bundled theme.

**Comment by aeschli** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.
If you disagree and feel that this issue is crucial: We're happy to listen and to reconsider.
Maybe you want to give it a try yourself and provide the feature through an extension or a PR: We're happy to give advise and get you started.
Thanks for your understanding. Thanks for helping and happy coding!
