### ISSUE TITLE
Only show restricted mode banner once user acts outside of restricted mode

### ISSUE THREAD

**Issue by JVimes** [microsoft/vscode#131191]
I think the restricted mode banner shows up so often that users will tune it out or disable it.

Can you wait to show the banner until the user tries to do something outside of restricted mode?

**Comment by sbatten** [comment]
This is a nice thought but deciding what that signal should be is not so trivial. e.g. if an extension that would provide errors in a file they have opened is not working, then they must be notified but they have not taken any explicit action. In practice, a lot of non-user actions would trigger the banner at the start because they provide those enhancements that don't require the user to do anything.
