### ISSUE TITLE
Heavy RAM Usage

### ISSUE THREAD

**Issue by yashraj-n** [microsoft/vscode#131167]
Issue Type: <b>Performance Issue</b>

Lately, My Visual Studio Code (Insiders) is consuming 2GB of ram and 70% CPU usage causing me to close my vs code
![pic1](https://cosi.is-inside.me/TUxFzTaK.png)
![pic2](https://cosi.is-inside.me/QjSd3guE.png)

VS Code version: Code - Insiders 1.60.0-insider (c08913337cb8b95493be8e99d62e0b3241563f6b, 2021-08-19T05:15:46.693Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3500 6-Core Processor               (6 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (9.60GB free)|
|Process Argv|. --crash-reporter-id 16ae216b-58d2-47af-adf7-2d4d738a9456|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    87	 10464	code-insiders main
    0	    25	  3336	   crashpad-handler
    1	    81	  3808	   window (Issue Reporter)
    0	   117	  4340	   gpu-process
    0	    37	  4480	   utility
    0	    87	  5056	   shared-process
    0	    65	  9640	     ptyHost
    0	   198	  6644	   window (index.ts - game_theif - Visual Studio Code - Insiders [Administrator])
    0	    15	  7124	     watcherService 
    0	    10	  6348	       console-window-host (Windows internal process)
   70	  1432	  7364	     extensionHost
    0	    70	  5448	       "F:\Microsoft VS Code Insiders\Code - Insiders.exe" "f:\Microsoft VS Code Insiders\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=7364
    0	   109	  8496	       electron_node tsserver.js 
    0	   137	 10604	       electron_node tsserver.js 
    0	    84	  7324	         electron_node typingsInstaller.js typesMap.js 
    0	    70	  8156	     searchService
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (index.ts - game_theif - Visual Studio Code - Insiders [Administrator])
|    Folder (game_theif): 7 files
|      File types: json(2) ts(1) lock(1)
|      Conf files: package.json(1) tsconfig.json(1);
```

</details>
<details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
turbo-console-log|Cha|2.1.6
npm-intellisense|chr|1.4.0
path-intellisense|chr|2.4.0
gitignore|cod|0.7.0
bracket-pair-colorizer-2|Coe|0.2.1
dart-code|Dar|3.25.1
es7-react-js-snippets|dsz|3.1.1
vscode-html-css|ecm|1.10.2
vscode-npm-script|eg2|0.3.22
prettier-vscode|esb|8.1.0
copilot|Git|1.3.2425
go|gol|0.27.1
rest-client|hum|0.24.5
theme-monokai-pro-vscode|mon|1.1.19
python|ms-|2021.8.1105858891
vscode-pylance|ms-|2021.8.1
jupyter|ms-|2021.8.2028630014
cpptools|ms-|1.5.1
vsliveshare|ms-|1.0.4673
material-icon-theme|PKi|4.9.0
remove-comments|pli|1.2.2
LiveServer|rit|5.6.1
vscode-fileutils|sle|3.4.5
vscodeintellicode|Vis|1.2.14

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
pythonvsuse255:30319630
vscod805cf:30301675
pythonvspyt200:30323110
vsccppwt:30312692
pythonvssor306:30340298
bridge0708:30335490
pygetstartedt2:30353727
dockerwalkthrucf:30348714
bridge0723:30353136
pythonrunftest32:30353181
pythonf5test824cf:30353184
javagetstartedt:30350119

```

</details>

**Comment by jrieken** [comment]
It looks like the issue is caused by one of your installed extensions. All extensions execute together on a single nodejs process, so in order to narrow down the possible problematic extension, please try the following:
* run `F1 > Help: Start Extension Bisect`
* (this will restart VS Code with half of your extensions disabled)
* try to do the steps which reproduce the problem
* if the problem reproduces, click "This is bad" (this narrows down the problematic extension to the half which was enabled)
* if the problem does not reproduce, click "Good now" (this narrows down the problematic extension to the half which was disabled)
* these steps will repeat until the problematic extension is found

| initial | step | final |
|---|---|---|
| ![image](https://user-images.githubusercontent.com/5047891/101918658-e9170f80-3bc9-11eb-9977-857baa291937.png) | ![image](https://user-images.githubusercontent.com/5047891/101918683-ef0cf080-3bc9-11eb-9f9e-98b0177991b2.png) | ![image](https://user-images.githubusercontent.com/5047891/101918706-f502d180-3bc9-11eb-8c86-e56355958bd4.png) |

**Comment by yashraj-n** [comment]
Ok thanks, it was live share extension which was causing issues
