### ISSUE TITLE
Show recent projects in Explorer when no folder is open

### ISSUE THREAD

**Issue by cbrnr** [microsoft/vscode#131245]
Currently, the Explorer shows two suggestions when no folder is open ("Open Folder" and "Clone Repository"). I think it would be helpful if it also listed some recent projects, which would make it unnecessary to go into the nested menu File -> Open Recent.

**Comment by gjsjohnmurray** [comment]
@cbrnr aren't you seeing the Welcome page when in that state? This page already has a Recent section:

![image](https://user-images.githubusercontent.com/6726799/130213102-8a149ec8-4600-45c7-8a3c-46563f0b524d.png)

**Comment by cbrnr** [comment]
I know. I don't see the Welcome page because I've set the option to start with an empty document. I thought for those people it might be helpful to list recent projects in the Explorer sidebar. But I'm fine with switching back to the Welcome page if you think this doesn't make sense.

**Comment by gjsjohnmurray** [comment]
I recently saw a proposal for the `viewsWelcome` contribution point to let extensions contribute multiple commands in such a way that they'd display as a blue button with a dropdown widget to give access to the second, third etc commands. With that available it'd be less controversial to add the command which appears on Command Palette as `File: Quick Open Recent...`, since it wouldn't consume any extra vertical space.

I wouldn't like a list of recent folder/workspace links here, as that **would** eat up vertical space which other extensions might need for their own viewsWelcome contribution to Explorer.

**Comment by JacksonKearl** [comment]
An extension can contribute a button to that view which runs the Open Recent command.

See how the builtin git extension does it here: 
https://github.com/microsoft/vscode/blob/da7d76d2ece2e073be8be7d9b972f82b98e43ce3/extensions/git/package.json#L2326-L2331
