### ISSUE TITLE
github.dev notebook png images/outputs not rendering 

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode#131279]
Steps to Reproduce:

1. Go to any github repo with a notebook with images/outputs
2. Press . 
3. Open python notebook
4. Open R notebook

For the python notebook, the image does not render but renders fine in desktop version of VSC. The default is png but I am able to switch to svg+xml and then it works in the browser. 

![image](https://user-images.githubusercontent.com/19276747/130286589-d154173d-c7d6-4eb8-835c-cddb5b9375c6.png)

For an R notebook, the image does not render and there are no other rendering options.

**Comment by mjbvz** [comment]
Can you please share an example notebook that demonstrates this issue?

**Comment by IanMatthewHuff** [comment]
@claudiaregio in the mime type selection do the images not render for both the built in image renderer and for the Jupyter renderer? We do some extra work in the Jupyter renderer for images, could possibly be something up with that if the built in renderer works ok.

**Comment by mjbvz** [comment]
I just tested this on GitHub.dev using insiders with the file https://github.com/microsoft/vscode-jupyter/blob/463d74ff643fd6f73faa4e4bec4ddee8fa4d234d/src/test/datascience/sub/test.ipynb

Here's what I see: 

![Screen Shot 2021-09-14 at 2 42 08 PM](https://user-images.githubusercontent.com/12821956/133337877-eadd0cd7-a6cb-45ea-9483-3db4b38148be.png)

This matches what I see on desktop when the Jupyter extension is disabled (it looks a bit weird because the labels are black text on a dark blue background)

Are you still seeing this issue on insiders GitHub.dev? If so, please share a file that demonstrates the problem
