### ISSUE TITLE
VS Code Insiders doesn't load an extension's modified package.json on disk after Reload if another version of the extension was previously installed

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode#131208]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:Version: 1.60.0-insider (user setup)
Commit: c08913337cb8b95493be8e99d62e0b3241563f6b
Date: 2021-08-19T05:15:46.693Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043

Steps to Reproduce:

1. Use VS Code Insiders (it also repros with VS Code 1.59.0 if we use a [modified vsix](https://github.com/microsoft/vscode-cpptools/commit/6c3d043c79005fac1737ebbe5554c814d5e58a88) that modifies updateChannel for non-Insiders VS Code).
1.5: You may want to set extensions.autoUpdate to "None" or else you may hit additional issues caused by this bug.
2. Open some folder with a .cpp file open so our extension can correctly activate.
3. Make sure the C/C++ extension is uninstalled and is not cached on disk (i.e. close/reopen VS Code Insiders).
4. Open the settings UI and type "updateChannel" to view the value (when it's available later).
5. Install the C/C++ extension (latest 1.5.1 is fine).
6. You should see the updateChannel be Default (assuming you haven't explicitly set it).
7. Open the extension's package.json on disk and search for updateChannel.

Bug#1 (minor bug): The package.json on disk has the default updateChannel setting changed to "Insiders" but there was no prompt to reload window from the change (it's supposed to show a message "Extensions have been modified on disk. Please reload the window."). This is a minor issue and doesn't matter, but it could be related to the main bug below.

8. Do a reload window. You should see the updateChannel correctly show "Insiders" now (i.e. bug#2 below doesn't not occur unless you had another version of the extension on disk).
9. Install any other C/C++ vsix version, e.g. 1.5.0 via Install Another Version or manually install a vsix such as from https://github.com/microsoft/vscode-cpptools/releases/tag/1.6.0-insiders3 .
10. Reload window to use the new version -- you should see bug#1 again.
11. Reload window again (to use the modified package.json).

Bug#2 (main bug): The updateChannel is incorrectly "Default" -- the package.json on disk is not used. It seems to use some cached package.json that doesn't have the modified values on disk. This can cause our extension to enter an upgrade/downgrade "loop" if extensions.autoUpdate is not "None". However, you'll finally see "Extensions have been modified on disk. Please reload the window.", so it will then start using the correct package.json (until you install a new vsix version).

**Comment by alexdima** [comment]
@sean-mcmanus Let me clarify what is going on on our side.

VS Code is not installing file watchers on the `package.json` files of extensions. So if you edit the `package.json` of an extension, there will be no "Extensions have been modified on disk. Please reload the window" popping up automatically. Such a notification would pop up at the next window reload under certain conditions (read below).

---

Here is the caching feature we have implemented for perf reasons (since many years unchanged):
1. When a VS Code window starts up, it scans for all `package.json` files in the user's extensions directory.
2. It then proceeds to cache the result as an amalgamation and uses some information as cache key.
3. On a subsequent window start up, if the cache file exists, and the cache key matches, it proceeds to start up vscode with the cached `package.json` amalgamation.
4. Once vscode has started up, it also launches, in the background, a scanner for all `package.json` files in the user's extension directory.
5. If the scanner disagrees with the cache (with which vscode was started), it pops up the message "Extensions have been modified on disk. Please reload the window".
6. When a user installs/uninstalls an extension using our UI, we delete the cache file.

---

IIRC we have discussed in the past about the C++ extension editing its own `package.json` and I personally continue to believe that is the wrong approach to whatever you are trying to do. But if you continue to edit your own `package.json` file, then please `touch` the extensions directory. Please issue an fs operation that ends up changing the `mtime` of the user `extensions` directory. The `mtime` of the user `extensions` directory is used as a cache key and will cause the cache to be ignored when vscode subsequently starts up.

**Comment by sean-mcmanus** [comment]
Cool thanks a lot. It turns out we used to have code that modified the mtime of the extensions folder, but we removed it to avoid showing the the "Reload window" message box when it wasn't really necessary, but then we made another change that did actually require it. Fixed by https://github.com/microsoft/vscode-cpptools/pull/8032 .

I'm not aware of an alternative approach until the platform specific marketplace is available (which would eliminate our need for our activationEvents rewrite), but for our VS Code Insider installations we'd also need the ability the have different default settings (see https://github.com/microsoft/vscode/issues/131433 ).
