### ISSUE TITLE
[Bug] `markdownPreviewFocus` is `true` even if the markdown preview isn't focused

### ISSUE THREAD

**Issue by wenfangdu** [microsoft/vscode#131289]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: v1.60.0-insider
- OS Version: Windows 10

Steps to Reproduce:

1. Change `markdown.showSource`'s when condition to `markdownPreviewFocus`.
2. Keep a markdown preview open.
3. Focus integrated terminal.
4. Use the bound shortcut to trigger `markdown.showSource`.
5. Markdown source code file is opened.

**Comment by Suven-p** [comment]
@mjbvz Should onDidChangeViewState have fired when focus is moved or should there another event for focus like onBlur https://github.com/microsoft/vscode/blob/aacd8438ca6b649830341d91a333240b0c73d2f5/extensions/markdown-language-features/src/features/previewManager.ts#L244

**Comment by Suven-p** [comment]
The event

**Comment by mjbvz** [comment]
`onDidChangeViewState` should be fired both when the view becomes active and when the user clicks away from it

If `onDidChangeViewState` is not getting fired when focusing on the terminal, then there is a bug in its implementation

**Comment by Suven-p** [comment]
Here's my progress:
https://github.com/microsoft/vscode/blob/2f574828e5bb4609ce762899e65df52df88186cf/src/vs/workbench/contrib/webview/browser/webviewElement.ts#L214-L216
didBlur doesn't fire when switching to terminal immediately after opening a markdown preview. Have no idea why. Maybe due to this? https://github.com/microsoft/vscode/blob/2f574828e5bb4609ce762899e65df52df88186cf/src/vs/workbench/contrib/webview/browser/webviewElement.ts#L105-L108

didBlur event does fire if user clicks on editor area after switching to preview and then switches to terminal. However, `this._editorService.activeEditor` still points to webview and the issue persists. This is probably easy to solve by checking if webview is focused as in above pr.
https://github.com/microsoft/vscode/blob/2f574828e5bb4609ce762899e65df52df88186cf/src/vs/workbench/contrib/webviewPanel/browser/webviewWorkbenchService.ts#L202

**Comment by juliombb** [comment]
would this PR be an appropriate way to fix the bug?

**Comment by mjbvz** [comment]
Yes, please submit a PR

**Comment by juliombb** [comment]
https://github.com/microsoft/vscode/pull/139050 is this way ok? Or should I submit it differently?

**Comment by mjbvz** [comment]
Possibly, but try testing it more to confirm. I also don't think we should need to use `setInterval` so try looking for a different approach to that part

**Comment by Binly42** [comment]
Just FYI, seems a little strange that some command might work as expected...

an example with no extensions installed:
1. with these in `keybindings.json`
```json
    {
        "key": "i",
        "when": "markdownPreviewFocus",
        "command": "workbench.action.terminal.sendSequence",
        "args": {
            "text": "test"
        }
    },
```
2. Keep both a markdown preview and its source open.
3. Focus the preview, then type `i`
4. "test" would be sent to terminal
5. Focus the source, then type `i`
6. "i" would be added at the cursor

**Comment by mjbvz** [comment]
This context key has since been replaced with one from core. See #156942
