### ISSUE TITLE
Execute "default:*" command for non-"type" commands

### ISSUE THREAD

**Issue by Gregoor** [microsoft/vscode#131362]
Wo we can currently do

```ts
vscode.commands.registerCommand("type", async (...args) =>
  someCondition
    ? someCallback(...args)
    : vscode.commands.executeCommand("default:type", args)
 );
```

but that does not seem to work for other commands. e.g. for `default:deleteLeft` I am getting `command X not found`. My use case is that I am working on an extension which would enrich certain actions, but fallback onto VSCode's actions if it can't do anything more useful.

**Comment by alexdima** [comment]
@Gregoor It is unforeseen for an extension to overwrite `deleteLeft`. That is because `deleteLeft` does not need to be overwritten because it is dispatched using keybindings. So your extension can define a keybinding e.g.:
```
{ "key": "backspace", "command": "mySpecialDeleteLeft", "when": "textInputFocus" },
```
Then, from the implementation of `mySpecialDeleteLeft`, `deleteLeft` can be invoked if necessary. 

The `type` command is a bit special, since it is not dispatched via keybindings, it is just executed by the input handling code when a keybinding is not matched and the underlying DOM textarea gets new content. That is why `type` can be overwritten, and has a `default:type`, while the others do not.
