### ISSUE TITLE
Make an option to shift the terminal pannel to vertical.

### ISSUE THREAD

**Issue by tymsai** [microsoft/vscode#131312]
I want this pannel to be popout from right side not from bottom, is there any way to do it ?
![image](https://user-images.githubusercontent.com/76956612/130321809-490c1784-a39c-4767-bac9-739c40f84d22.png)

**Comment by gjsjohnmurray** [comment]
Since 1.58 you have been able to move terminals into the editor area.

https://code.visualstudio.com/updates/v1_58#_terminals-in-the-editor-area

Create a new editor group to the right (one way is to run `View: New Editor Group to the Right` from Command Palette), then drag your terminal into the new group (grab it here)

![image](https://user-images.githubusercontent.com/6726799/130325502-26e0041e-79fe-4f74-bad2-21e607120303.png)

**Comment by tymsai** [comment]
thanks :-)
But is there any way to pop it from right side by default

**Comment by Tyriar** [comment]
A few options:

- You can move the panel to the right by right clicking the panel title
- Use `"terminal.integrated.defaultLocation": "editor"` to always use editors by default
- Run or add a keybinding for this command: 
   ![image](https://user-images.githubusercontent.com/2193314/130451442-0dfe13fe-32ac-4b50-a2d3-3936a264c400.png)
