### ISSUE TITLE
Swallow execution time during run by line

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode#131373]
Change execution code to not output execution time during debugging

**Comment by DonJayamanne** [comment]
@roblourens did we add a new metadata into the cell to indicate whether its paused.
I personally think its even simpler for Jupyter extension to not display the times at all.
For instance if the timer is ticking over and we send a command to stop it, it will take a few milli-seconds for that to stop, hence its already inaccurate.

Was looking into this as I too have a debug experience for a personal notebook extension and I feel I could just not display the timer, instead of relying on such an API.

**Comment by roblourens** [comment]
This isn't an extension API, it's private metadata for the feature which is driven by vscode. I think this should be driven by vscode, not the extension, since it makes sense for any notebook type.
