### ISSUE TITLE
[web] does not open on android in chromium based browsers

### ISSUE THREAD

**Issue by akosyakov** [microsoft/vscode#131382]
Originally reported in Gitpod: https://github.com/gitpod-io/gitpod/issues/4537#issuecomment-903104166

**Comment by bpasero** [comment]
Can you open https://vscode-web-test-playground.azurewebsites.net/?enter=true and see if there is anything logged to devtools that could help diagnose the problem further?

**Comment by akosyakov** [comment]
@shaal Could you try above please? 🙏

**Comment by bpasero** [comment]
This issue is caused by an extension, please file it with the repository (or contact) the extension has linked in its overview in VS Code or the [marketplace](https://aka.ms/vscodemarketplace) for VS Code. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!

**Comment by shaal** [comment]
Hi @bpasero & @akosyakov, sorry for the long delay.
I didn't have a chance to add information to this issue before.

The title is of this issue is not accurate, because the problem I encountered is specifically when these 3 conditions are met:
* Using Edge Chromium
* On an Android mobile device (I tested it on various Android mobile phones and on Amazon Fire tablet)
* Open any version of vscode-in-the-browser

I don't think it's related to any specific extension.

Here are the errors in devtools, using remote debugging -

Testing with the link you suggested:
![image](https://user-images.githubusercontent.com/22901/132355004-7f449c45-a2f9-459f-a3aa-776424144479.png)

Testing with `github.dev`:
![image](https://user-images.githubusercontent.com/22901/132355321-c4090852-077a-41aa-aca9-5f5b6946600d.png)

Testing with `github1s.com`:
![image](https://user-images.githubusercontent.com/22901/132355527-7e5dfd9d-a379-47a6-b2d8-a563ed670dc8.png)

---

But when testing with Chrome (NOT Edge Chromium) on the same device, vscode in browser is working as expected:
![image](https://user-images.githubusercontent.com/22901/132356061-d9bf1a05-0882-4b85-8b01-e87777a71faf.png)

**Comment by bpasero** [comment]
Ok then please file a bug against Edge on Android, they probably do something wrong.

**Comment by eamodio** [comment]
FYI, I tested github.dev on my Android device (Pixel 3 XL) in both Edge and Edge Canary and it loaded and worked for me.

**Comment by shaal** [comment]
Thank you @eamodio 
I tested with Edge Canary on my onePlus 7T Android phone, and it works! No errors like in standard Edge Chromium.

Should I just assume Edge Chromium will catch up with Edge Chromium Canary and soon it's not going to be a problem?
