### ISSUE TITLE
TerminalStateChangeEvent not used

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#131496]
Testing #130775

We have a [`TerminalStateChangeEvent`](https://github.com/microsoft/vscode/blob/main/src/vs/vscode.proposed.d.ts#L959) but it is not used anywhere. We send a `Terminal` as part of the state change event

**Comment by isidorn** [comment]
To be more aligned with the `onDidChangeTerminalDimensions` I suggest to actually do not send the terminal but the actual `TerminalStateChangeEvent`

**Comment by Tyriar** [comment]
Thanks, I removed this in the latest iteration but I guess I didn't get rid of the interface. Since `Terminal.state` exists we don't need the special event as `Terminal` has all the information needed already.

I think this is an existing pattern in the API but I can bring it up again in the API sync, added a note to https://github.com/microsoft/vscode/issues/127717
