### ISSUE TITLE
Unable to connect to a Codespace in VS Code Insiders

### ISSUE THREAD

**Issue by joshmgross** [microsoft/vscode#131438]
Issue Type: <b>Bug</b>

1. Create a Codespace either via the Codespaces extension or https://github.com/codespaces
2. Attempt to connect to the Codespace from VS Code Insiders
3. Observe that VS Code will be stuck on "Opening remote..."

VS Code version: Code - Insiders 1.60.0-insider (44568e5947efa4811419e529e80fb14b7554cf61, 2021-08-23T10:42:53.526Z)
OS version: Darwin x64 19.6.0
Restricted Mode: No

<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256198
pythonvspyt639:30291487
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
pythonvsuse255:30319630
vscod805:30301674
pythonvspyt200:30323110
vsccppwt:30312692
pythonvssor306:30340298
bridge0708:30335490
pygetstartedt2:30353727
dockerwalkthru:30348713
bridge0723:30353136
pythonrunftest32cf:30353182
pythonf5test824cf:30353184
javagetstartedt:30350119
pythonvspyt187:30356034

```

</details>

**Comment by jkeech** [comment]
It looks like something changed with auth in the recent Insiders build where the GitHub Codespaces extension is not able to get the auth token from the GitHub Authentication extension which is built in to VS Code. `await vscode.authentication.getSession(...)` is hanging and not returning even when the client is already signed in.

**Comment by jshorty** [comment]
Confirming I'm also seeing this with the same version

**Comment by iBhavesh** [comment]
I am facing the same issue in insiders

**Comment by TylerLeonhardt** [comment]
I think this might have been caused by enabling the web worker extension host in https://github.com/microsoft/vscode/pull/131181 cc @alexdima 

I believe as a workaround you can set this setting: `"extensions.webWorker": false`

it works for me. Can you all give it a try?

**Comment by jkeech** [comment]
> Also, @jkeech can you share what the extension kind is for the GitHub Codespaces extension?

This is what the package.json for GitHub Codespaces contains:

```
"extensionKind": [
    "ui",
    "workspace",
    "web"
],
```

**Comment by TylerLeonhardt** [comment]
also adding @sandy081 just in case.

**Comment by adaex** [comment]
> I believe as a workaround you can set this setting: `"extensions.webWorker": false`
> 
> it works for me. Can you all give it a try?

Works for me.

**Comment by alexdima** [comment]
I'm sorry about this. We ended up with a deadlock. The problem was the following:

* the codespace extension uses `vscode.authentication.getSession(...)` to do resolving
* to implement that API call, the auth service sends out an activation event `onAuthenticationRequest:github`
* the activation event is sent out to all extension hosts and the promises are joined
* the nodejs ui extension host processes the activation event quickly and activates the built-in github auth extension
* but the web worker extension host (now being configured for auto start which means it will start if it needs to host any extension) will block the activation event, waiting for start to be called to know if it needs to start or not
* start will never be called because the resolver doesn't finish

That creates a deadlock.

**Comment by TylerLeonhardt** [comment]
Thank you for this @alexdima!
