### ISSUE TITLE
Adding more info about the launch.json file in vs code

### ISSUE THREAD

**Issue by Xediox-zex** [microsoft/vscode#131493]
I would like you to add more briefing as to how to set up the launch.json file in the vs code documentation... 
it's really a pain for someone with no coding knowledge and skill and is a freshie... 
I can't get my debug program running, it shows up errors like launch.json took too long to respond.
please fix your documentation as fast as possible and if you can make the configuration a default feature so users won't have to struggle for different things, and for pros add a feature for them so they can modify to their hearts content

**Comment by weinand** [comment]
@Xediox-zex most of the contents of the launch.json is contributed by debugger extensions and the corresponding documentation is owned by the authors of the debugger extension.

What debugger are you using?

**Comment by leolcao** [comment]
I am also looking for the schema definition for the attributes in launch.json file because I want to know the available values for each attribute, and I am confused about what if I don't set some attributes, it still works for the debugging.

for example, to debug the current typescript(.ts) file, I set 2 different configuration in the below launch.json.

my confusions are:
- what is the meaning about 'pwa-node' and 'node' ?
- what as protocol values? effect?

Actually, the content in https://code.visualstudio.com/docs/typescript/typescript-debugging is quite simple. and I cannot find any clue for the schema definition for the launch.json.

BTW, the 2 different configuration have same good result, obviously, the second one is more simple to use.

```json
{
  {
    "name": "Current TypeScript file(../tsconfig.dev.json)",
    "type": "node",
    "request": "launch",
    "runtimeArgs": [
      "--nolazy",
      "-r",
      "ts-node/register"
    ],
    "env": {
      "TS_NODE_PROJECT": "${workspaceFolder}/${relativeFileDirname}/../tsconfig.dev.json"
    },
    "args": [
      "${relativeFile}"
    ],
    "sourceMaps": true,
    "protocol": "inspector"
  },
 {
    "name": "Current TypeScript file",
    "type": "pwa-node",
    "request": "launch",
    "program": "${workspaceRoot}/node_modules/ts-node/dist/bin",
    "args": [
      "${relativeFile}"
    ]
  }
}
```

**Comment by weinand** [comment]
@leolcao `node` and `pwa-node` were referring to different node debuggers until the August release. Now there is only one node debugger, and `node` and `pwa-node` refer to the same thing. 
I recommend to use `node`.
It is no longer necessary to set "sourceMaps" to true because that's the default anyway.
Same is true for "protocol".

In order to get information about the various attributes and their value sets, you can use Intellisense:

![2021-09-03_10-57-14 (1)](https://user-images.githubusercontent.com/1898161/131979311-44b11cd8-cdfc-43f3-99e0-e5e910a150c9.gif)

**Comment by leolcao** [comment]
Thanks, it is a better way to check attributes.
