### ISSUE TITLE
Allow to resolve buttons on QuickPickItems lazy

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#131401]
I need to resolve the buttons for QuickPickItems lazily (e.g. I need to make service requests). Currently I need to set the `items` on the quick pick which can lead to strange behavior if the user types, moves the mouse or otherwise interacts with the quick pick.

Would it be possible to support a style where setting the `buttons` property updates the item in the UI?

**Comment by TylerLeonhardt** [comment]
This is interesting and not currently supported even in Core atm. I wonder though if this issue would be almost fixed with addressing this:
https://github.com/microsoft/vscode/issues/109969

The idea being that if the same ids are present when you set `.items` then the cursorTop won't change but the UI will still update if a button was added or something.

**Comment by dbaeumer** [comment]
That would definitely help. Do you know why we decided that QuickPickItems are not live at least in the case where I create a quick pick list using the API?

**Comment by TylerLeonhardt** [comment]
It's a good question. Historically it seemed like we didn't want to complicate the API too much:

> The assumption so far was that items would not change and that we need to read their properties only once when they are set on the picker object. That has kept the API simple. The scrollTop and splice() (replace the changed items) suggestions are preserving this assumption.
> 
> If we wanted to support mutable items, we would need an extension-supplied event. That would in my view mix two distinct approaches in the same API.

from @chrmarti in #109969

It would get a bit complicated because the user is responsible for creating the QP items...

for most cases, simply preserving the cursor top when the QP items have the same ids and order is enough of a fix and the user just needs to add an `id`

(this again is theoretical since today there's no concept of an `id` in the extension QP items)

**Comment by TylerLeonhardt** [comment]
I just added the proposed API for a property that you can set that will allow you to control when the scroll position should be kept. That's being tracked here:
https://github.com/microsoft/vscode/issues/132068

It's not quite as elegant as enabling "live objects" in the quick pick but it should be enough to fix your issue without having to break the previous assumption that the items were static.

**Comment by TylerLeonhardt** [comment]
Closing this to use that ^
