### ISSUE TITLE
Locked groups: splitting a group with a terminal can lead to unexpected locked group

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#131556]
Testing #131196

Since the setting applies only when its the first editor in the group and there is more than one group, results can be confusing.

1. Open some file in the opened workspace as the first file in the only editor group.
2. Create a terminal editor which will show in the current group
3. Split the group after deciding you want to work with 2 groups

Both groups have terminals as the active editor but only the second group is locked. In this case I was not really trying to make a second group with a terminal but rather a second group for other files. And I kind of wanted the first group to be locked automatically. I can see this is a difficult case of trying to guess the users expectations, but I essentially tricked by both the setting and the split (duplication) behaviour.

**Comment by bpasero** [comment]
@misolori @Tyriar @meganrogge thoughts on this?

One idea would be that splitting a group inherits the locked state of the group you split from. I.e. the setting would not apply in that case.

**Comment by misolori** [comment]
Agreed, some feedback would be great here. I was at least expecting the first group to also be locked since any terminal group would get locked automatically (at least that was my interpretation). I think often times people use the split action as a "i want to move this to the other side" and then have to go back and close the duplicate.

**Comment by bpasero** [comment]
> I was at least expecting the first group to also be locked since any terminal group would get locked automatically

No, not in this case:
* the terminal is not the first editor in the group, so the setting does not apply at all
* locking does not apply to a single editor group overall [1]

[1] we feel that allowing to lock groups when just one is open can be frustrating for this scenario:
* you open a file
* you open a terminal to the side
* you are done working and start to close all editor groups and editors but you start with the file first and then terminal
* the empty single editor group is now still locked because you had a terminal in it that locked it
* opening any file from the explorer will cause a new group to be created which is very likely not what the user expects

Thus pragmatic approach was to clear up any locked state once you are back to 1 group.

**Comment by misolori** [comment]
Ah, ok in that scenario that does make sense even though my brain was thinking about it in simple terms of terminal editor = locked  group.

**Comment by sbatten** [comment]
I think we've gone down this thinking before but, its almost as if you don't want the group locked but rather a specific tab, when active, locks its group. e.g. if a terminal is opened to the side in a group, it should not be replaced, but as soon as it is closed, if they are just text editors, the group would be unlocked.

similarly for a markdown or browser preview.
