### ISSUE TITLE
Feedback regarding `onDidTriggerItemButton`/`onDidTriggerButton`

### ISSUE THREAD

**Issue by karrtikr** [microsoft/vscode#131588]
Testing #131454

`onDidTriggerItemButton` is very similar to
```typescript
/**
 * An event signaling when a button was triggered.
 */
readonly onDidTriggerButton: Event<QuickInputButton>;
```
We should probably edit the doc comment to signal this is not for item buttons, or maybe even combine the two events? `item` property can be `undefined` in the case of button without items.

**Comment by TylerLeonhardt** [comment]
The only problem with using the same event is that the typing would change because instead of:

```
readonly onDidTriggerButton: Event<QuickInputButton>;
```
it would have to be:

```
readonly onDidTriggerButton: Event<QuickInputButton | QuickPickItemButtonEvent>;
```

and the extension authors have to change their code.

Additionally, the way it is now keeps the API identical to the internal Core API which means there's less overhead of maintenance there which is something I really like.

With all that said, I am happy to update the comments on these types to be more clear. Thanks!
