### ISSUE TITLE
Editors toolbar briefly shows actions from editor of other group

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#131584]
Testing #131196

After moving from a code editor to a terminal editor, the editor actions are first the same as from the code editor and then change to the terminal editor actions
![recording (2)](https://user-images.githubusercontent.com/6561887/130700576-e17bf46a-7554-4e7e-a065-adec97a3f595.gif)

**Comment by bpasero** [comment]
That seems unrelated to the locked editor group feature. Maybe terminals have a way of setting the context keys delayed?

**Comment by bpasero** [comment]
Hm, I can reproduce the same with normal editors and it seems to depend on whether I click on a tab vs. making the group active by clicking on empty space.

**Comment by bpasero** [comment]
I realised that there is a 50ms delay through a `RunOnceScheduler` from the menu service that is likely the cause here. When I remove it, I see no flicker:

https://github.com/microsoft/vscode/blob/ee1655a82ebdfd38bf8792088a6602c69f7bbd94/src/vs/platform/actions/common/menuService.ts#L59-L62

and

https://github.com/microsoft/vscode/blob/ee1655a82ebdfd38bf8792088a6602c69f7bbd94/src/vs/platform/actions/common/menuService.ts#L75-L75

@jrieken this is probably for a good reason and perf related, maybe you could comment. I don't think the editor control can do something about it downstream.

**Comment by jrieken** [comment]
Unlikely that you are suffering from the first debounce since that's when menus are added/removed but the latter is to reduce processing and events when context keys change. It's worth to try with a value of `0`. May that results in the same amount of events

**Comment by bpasero** [comment]
@jrieken yeah it is this one that has an impact:

https://github.com/microsoft/vscode/blob/ee1655a82ebdfd38bf8792088a6602c69f7bbd94/src/vs/platform/actions/common/menuService.ts#L75-L75

Flicker is not visible with a value of `0` but I wonder the cost of that change...

**Comment by jrieken** [comment]
>  I wonder the cost of that change...

Can you count and compare the number of events that are emitted with `0` and `50`?

**Comment by bpasero** [comment]
@jrieken when I count the number of calls to `_onDidChange` with `50ms` vs `0ms` delay over a period of 5s jumping between editors I get only few more events (`5` vs `8`), but I am not sure if there are other actions that can trigger potentially more events.

Maybe this is becomes a option to change this only for the editor menu, here?

https://github.com/microsoft/vscode/blob/e909ece93a75d6e053c916b792f8b8b4a96a4bbe/src/vs/platform/actions/common/actions.ts#L211-L211

**Comment by jrieken** [comment]
fyi - I have pushed a change that allows to change the debounce delay per menu instance

**Comment by bpasero** [comment]
Thanks 🥂
