### ISSUE TITLE
Markdown Syntax Highlighting - Strings are not always recognized

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#131532]
```markdown
* [x]
* [ ]
```

![image](https://user-images.githubusercontent.com/2931520/130643900-0d829f73-13f3-41d1-ac28-dae2436d78e6.png)

![image](https://user-images.githubusercontent.com/2931520/130643937-3d4f51f4-25f4-4b3a-8495-cddbe53c0dc5.png)

Why is the first one a string, but not the second one?

(This confuses bracket pair colorization)

**Comment by mjbvz** [comment]
`* [x]` is using link shorthand. In markdown, `[link]` is equivalent to `[link][link]`. The second case `* [ ]` isn't a valid link since there is no link destination

One other thing to note is that although these example look like task lists, task lists are not part of the markdown standard so we don't include support for them out of the box

One thing I'm not entirely sure of is why links are being marked as strings, but it looks like we do that for all links in markdown and have been doing that for a long time

**Comment by hediet** [comment]
Makes sense. I guess the strange bracket pair colorization just points out that task lists are not supported by the default highlighting.

Feel free to close this issue if you don't think there is something actionable.

**Comment by mjbvz** [comment]
Ok, closing since the current behavior seems correct to me and could be improved by an extension
