### ISSUE TITLE
Web: welcome icons are not balanced

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#131765]
Somehow I feel the "Open Folder" icon is more shifted to the left:

![image](https://user-images.githubusercontent.com/900690/131079615-7159d86a-45bf-4d38-a44b-74d3eaeae9ac.png)

**Comment by misolori** [comment]
Yes, this is intentional to avoid pixelation and because the arrow is on the left (while new file has a plus in the bottom right)

![image](https://user-images.githubusercontent.com/35271042/131404067-34cd905b-16bc-45cc-8e6d-5e1b8cef5687.png)


It was anchored to top right to align with the split icon that also appears in the editor toolbar:

<img width="98" alt="CleanShot 2021-08-30 at 13 53 24@2x" src="https://user-images.githubusercontent.com/35271042/131404048-250ee4b9-9454-4695-84ef-761e292b4475.png">
