### ISSUE TITLE
Feedback on test results

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#131730]
Sorry for the multi-feedback issue, but I can create new ones for each that you think is worth fixing.

![image](https://user-images.githubusercontent.com/6561887/131003696-4c90b75c-d8b1-4cf3-b734-25ca1d5984b5.png)

1. The colors are inconsistent between the hover widget and the peek view.
2. The `:` after "Expected values...", "Expected", and "Actual" seem unnecessary and out of place even.
3. The "Expected Values..." being appended after the git blame info feels awkward. Especially, since the red is striking next to the muted grey.

**Comment by alexdima** [comment]
@connor4312 You could switch to use the new `IModelDecorationOptions.after` option to use injected text instead of the current CSS based solution you are using.

by the way @hediet it would be good for us to try to find all users of the old CSS based approach and help them migrate to the new injected text based solution.

**Comment by hediet** [comment]
Notice that injected text will have cursor stops around it. Maybe we can make this configurable.

**Comment by connor4312** [comment]
I've adopted 3 but noticed weirdness when the range gets selected:

![](https://memes.peet.io/img/21-08-bdc6c69c-2b28-4abb-8141-903b4c3ff956.gif)

I'll push this to Insiders, let me know if you would like an issue tracking that ^

**Comment by alexdima** [comment]
> I'll push this for Insiders, let me know if you would like an issue tracking that ^

Definitely, please make an issue for that.
