### ISSUE TITLE
Cannot open file as UTF-8 with BOM when Windows global unicode is turned on.

### ISSUE THREAD

**Issue by Gateswong** [microsoft/vscode#131860]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.57.1
- OS Version: Windows 10.0.19041

![image](https://user-images.githubusercontent.com/2586057/131248166-23d41d66-a0c0-47b8-b768-790b5f7f79e4.png)

**Comment by bpasero** [comment]
What is the problem?

**Comment by bpasero** [comment]
This issue is caused by an extension, please file it with the repository (or contact) the extension has linked in its overview in VS Code or the [marketplace](https://aka.ms/vscodemarketplace) for VS Code. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
