### ISSUE TITLE
[Vscode Insider 1.60] Cannot Change Default Terminal Settings.

### ISSUE THREAD

**Issue by chiawei-chien** [microsoft/vscode#131876]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.60 Insider
- OS Version: 1909

Steps to Reproduce:

1. Change default terminal to "Command Prompt"
2. Re-start VSCODE and open the last folder that you used before.
3. VSCODE 1.6 will still use "Powershell" as default terminal.

**Comment by TarunavBA** [comment]
Hey @chiawei-chien it's an _insider_ build dude, it is know to have some **bugs**. So what I recommend is stop using the integrated terminal of vscode and use any external one. 🙂 I use Git Bash.

**Comment by chiawei-chien** [comment]
Hi @TarunavBA , 

Yes, I understand _insider build_ have some bugs, but just want to help reporting this issue after I updated to version 1.60, or should I report this at the other place?

And for some reasons, we have to use integrated terminal, thank you for your suggestion.

Regards.

**Comment by TarunavBA** [comment]
@chiawei-chien you can use the stable version! 😃

**Comment by shakedc** [comment]
I too encountered this issue.
I was under the impression that the whole purpose of participating in the insider program is so I will encounter and report bugs to contribute to the quality of the product. Is that not the case? I see @chiawei-chien was discouraged from reporting this bug here.
Where would be appropriate to report this bug?

I am not interested in a workaround or immediate solution, there is a very easy workaround. I'd like to report this bug so it would be resolved prior to release.

**Comment by TarunavBA** [comment]
@chiawei-chien and  @shakedc You can make a new issue with the tag `bug`.
