### ISSUE TITLE
Git - The clone repository error tool tip is misleading if git isn't installed.

### ISSUE THREAD

**Issue by MayurMDeshpande** [microsoft/vscode#131812]
Does this issue occur when all extensions are disabled?: Yes/No

Problem Description:

I did not have Git installed and was attempting to clone a repository. The clone repository button was grayed out and when I hovered over how to fix it the tool tip given was to "wait for git extension to be activated". This is misleading because the git extension doesn't resolve the issue. Instead the tool tip should have been to install git which is much more clear and correct.

![GitHUb issue](https://user-images.githubusercontent.com/65038941/131176022-7e73462d-6a3c-4b4c-8ad1-fa93f682fde6.png)

- VS Code Version: 1.59.1
- OS Version: 

Steps to Reproduce:

1. Delete git or ensure git is not installed
2. Launch VSCode
3. Click on explorer tab
4. Hover over clone repository (which should be grayed out)
5. Read misleading tool tip

**Comment by lszomoru** [comment]
Agreed. Couple of changes that I think we should be making:
1) Remove the tooltip from the button as that is just confusing
2) Remove this section if git is not installed and display better content suggesting to install git

@digitarald let me know if you disagree with this proposal.

**Comment by digitarald** [comment]
+1 on confusing tooltip.

Alternatively to removing it, the button could be activated and open the SCM view which will have Git installation steps. wdyt, @lszomoru?

**Comment by lszomoru** [comment]
This must have been fixed since the issue has been filed. Here is the Explorer view in the latest VS Code Insiders:

<img width="381" alt="Image" src="https://github.com/user-attachments/assets/4a1b780a-e501-48eb-97fa-95397c57fcd3" />


Source Control view also correctly shows the installation welcome view:

<img width="381" alt="Image" src="https://github.com/user-attachments/assets/4790a0c4-ef88-43e4-b0b6-c0cf27d92068" />
