### ISSUE TITLE
Language detection is happening even when I explicitly set the default language

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#131912]
Set `"files.defaultLanguage": "markdown"`

Run lorem ipsum extension's insert several paragraphs into an untitled file:

![recording (77)](https://user-images.githubusercontent.com/2193314/131365699-e78a9379-6f54-4168-9cc6-40256d048ca9.gif)

Since I set it explicitly, I don't want to use auto detection.

**Comment by Tyriar** [comment]
DM discussion tldr:

I'm not in the target audience (beginners) and a good indicator of that is the default language setting which most beginners wouldn't set.

**Comment by TylerLeonhardt** [comment]
I don't really agree with making this change. The reason being is because pasting "a bunch of lorem text":

1. shouldn't change the language to anything because it shouldn't be representative of any language
2. I see `files.defaultLanguage` as a starting point where you start in markdown, for example, and then get switched to whatever if there is large enough confidence. You won't always want to be on markdown.

If we work with the assumption that the model will always be right, then this issue shouldn't exist.

With that said, because the model is wrong in this scenario and I don't want to up the confidence required because that will make an already hard to see feature happen less, and I'm not sure how soon I'll have a fix for this, I will make this change.
