### ISSUE TITLE
Is it possible to have setting to allow loading suggestion in background

### ISSUE THREAD

**Issue by Thaina** [microsoft/vscode#131980]
Sometimes the suggestion in large project and/or large framework might take a while more than 5 seconds and we might take times focus on other windows instead of pause and wait vscode to finish loading

So I think the suggestion should have setting property to allow sticky floating box that will continue loading in background

Is it possible?

**Comment by IllusionMH** [comment]
/needsMoreInfo

What language? And what is current behavior and expected next behavior?

e.g. TS/JS already has partial functionality for single file scope available while whole project is processed(and has "Initializing JS/TS language features" in status bar). Controlled by `typescript.tsserver.useSyntaxServer`

**Comment by Thaina** [comment]
@IllusionMH As for me is C# but I think this behaviour is affect every language isn't it?

Currently when suggestion box is opened, such as `ctrl+space` to force it up. It will be "loading" like this or showing a list of suggestion

![image](https://user-images.githubusercontent.com/1042507/131549557-6b72cc75-7fd5-4165-9c01-aa84f26b9ac2.png)

But in any case and any language, if we leave focus out of that vscode window instance, such as switch to other windows, that box will just disappear isn't it?

I want a setting so this box will not disappear on just leave focus. But must be clicking somewhere else in that vscode windows or press `esc`

**Comment by jrieken** [comment]
> @IllusionMH As for me is C# but I think this behaviour is affect every language isn't it?

Please file this against the C# extension. It should never take so long to compute IntelliSense. 

Also check if this is caused by another extension: All extensions execute together on a single nodejs process, so in order to narrow down the possible problematic extension, please try the following:
* run `F1 > Help: Start Extension Bisect`
* (this will restart VS Code with half of your extensions disabled)
* try to do the steps which reproduce the problem
* if the problem reproduces, click "This is bad" (this narrows down the problematic extension to the half which was enabled)
* if the problem does not reproduce, click "Good now" (this narrows down the problematic extension to the half which was disabled)
* these steps will repeat until the problematic extension is found

| initial | step | final |
|---|---|---|
| ![image](https://user-images.githubusercontent.com/5047891/101918658-e9170f80-3bc9-11eb-9977-857baa291937.png) | ![image](https://user-images.githubusercontent.com/5047891/101918683-ef0cf080-3bc9-11eb-9f9e-98b0177991b2.png) | ![image](https://user-images.githubusercontent.com/5047891/101918706-f502d180-3bc9-11eb-8c86-e56355958bd4.png) |

**Comment by Thaina** [comment]
> > @IllusionMH As for me is C# but I think this behaviour is affect every language isn't it?
> 
> Please file this against the C# extension. It should never take so long to compute IntelliSense.

I don't mind it took so long, and even it faster then this I still wish it could still running in background and still open the suggestion box even the vscode windows was not focused

Actually maybe my original request is not really straigtforward, I wish I could switching vscode windows while the floating suggestion box (and the loading box of the suggestion box) are not closing, which I think this was a default behaviour of every language, or I am not correct?

The point is maybe we would like to swap to browser to find more information about the option in suggestion box, and still came back to vscode to watch the option back and forth, something like that

**Comment by jrieken** [comment]
> still wish it could still running in background and still open the suggestion box even the vscode windows was not focused

Sorry, but that's nothing we strive for. The suggest box disappears automatically be to out of the way, e.g when switching to another window or editor. I admire your patience and willingness to wait so long for suggestions but the essence of this feature is to be fast (therefore the transient, non stable, UI). For the extension, any initial setup/bootstrap operation should be done only once and not depend on the suggest box state, once init is done suggest should be fast. Iff not it's an issue with the extension, just like slow startup
