### ISSUE TITLE
context.extensionUri is wrong in web ext host

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#131902]
* Run an extension in the web extension host
* The `context.extensionUri` uses the `file`-scheme, not `vscode-file`

**Comment by bpasero** [comment]
Hm, how is this property being used? Isn't it for extensions to be able to access files in their extension via node.js? If so, `file` scheme is fine because you cannot do anything with `vscode-file` scheme from the extension host.

**Comment by bpasero** [comment]
Oh, this is for web extension host...

**Comment by jrieken** [comment]
>  If so, file scheme is fine because you cannot do anything with vscode-file scheme from the extension host.

Yeah, I load a wasm-file and when running on desktop the URI doesn't work, e.g this is what I do in anycode: 
https://github.com/microsoft/vscode-anycode/blob/1a6b8818177635cb911e8f085ccf03219992a320/src/extension.ts#L19-L23

**Comment by bpasero** [comment]
I have a feeling this `URI` is coming from here:

https://github.com/microsoft/vscode/blame/12a1d1f9cb0c4e2b7894466e1878e6f3899408d9/src/vs/workbench/services/extensions/node/extensionPoints.ts#L344-L344

Added via https://github.com/microsoft/vscode/commit/0252ac49bc39cef7b31baeb86e7ff9eece13c8b4

One thing to keep in mind is that `vscode-file` only works in native, not in web. Since I guess we run the web worker extension host in both contexts, we need to be careful what the value is then.

**Comment by jrieken** [comment]
> Since I guess we run the web worker extension host in both contexts, we need to be careful what the value is then.

Doesn't [`asBrowserUri`](https://github.com/microsoft/vscode/blob/494cbbd02d67e87727ec885f98d19551aa33aad1/src/vs/base/common/network.ts#L160-L160) account for that?

**Comment by bpasero** [comment]
This will work fine whenever it is called from renderer or even web-worker extension host, but if you use this method in the node.js context (not renderer) you end up with a `vscode-file` URI that cannot be dealt with because this scheme is only supported from the electron renderer.

One thing we could add is another check in `asBrowserUri` to keep the URL as is when called from a process context that is not Electron renderer.

**Comment by jrieken** [comment]
maybe candidate, adding labels for discussion

**Comment by jrieken** [comment]
Turns out this isn't just `extensionUri` but also [logUri](https://github.com/microsoft/vscode-anycode/blob/babe511bfb186ce075108fa601a3e2d93dfa35b2/src/vscode.d.ts#L6189-L6189), [storageUri](https://github.com/microsoft/vscode-anycode/blob/babe511bfb186ce075108fa601a3e2d93dfa35b2/src/vscode.d.ts#L6144-L6144), and [globalStorageUri](https://github.com/microsoft/vscode-anycode/blob/babe511bfb186ce075108fa601a3e2d93dfa35b2/src/vscode.d.ts#L6168-L6168). They all use the `file` protocol which `fetch` and friends cannot handle. 

There are now two options

1. Use the `vscode-file` scheme for said uris. With that they are "dom uri" and compatible with browser function **however** such uris cannot be loaded with the `vscode.workspace.fs` API. This leads to 
2. Treat the `vscode-file` scheme as an implementation detail and enable fetch and friends to work for that scheme. This sounds more reasonable to me and @alexdima because technically  `file` is the right/trus scheme. 

Now, how can fetch and friends be enabled? Either by patching or by relaxing the check for the `file` scheme usage (@bpasero might now more for the latter). For the former approach (patching) this is list of things that need to be patched (likely incomplete)

* `fetch`
* `XMLHttpRequest`
* `new Worker`
* ~~`importScript`~~ in theory yes but already [blocked by us](https://github.com/microsoft/vscode/blob/28f4bd6ef8fc932716d4ce66253d21432b956a14/src/vs/workbench/services/extensions/worker/extensionHostWorker.ts#L43)
* ~~`import`~~ in theory yes but ESM isn't enabled (yet)

**Comment by bpasero** [comment]
Yes, I like the approach to keep `vscode-file` an implementation detail and use it only in those places where we know that we use the browser to do a request. Since `file` protocols are supported just fine even in web worker (at least that is my understanding - the request goes over to the renderer), we are good.

Blocking `file` scheme was done as a way to tighten the security of a renderer:

https://github.com/microsoft/vscode/blob/ee1655a82ebdfd38bf8792088a6602c69f7bbd94/src/vs/platform/protocol/electron-main/protocolMainService.ts#L74-L80

The `file` protocol is handled very specially in Chrome internals (@deepak1556 could tell more about it). It does not at all behave like a normal secure scheme. So I would rather like to keep `file` access disabled if possible.

**Comment by jrieken** [comment]
Merged #131967 and most cases should be fixed now. Using `fetch` with a `Request` object using a file-uri won't work but I leave that ignored for now

**Comment by sandy081** [comment]
Closing it as it is merged.

**Comment by rzhao271** [comment]
@jrieken what are some verification steps for this issue? I noticed that we're still using the `file` scheme.
I tried doing `fetch('file:///Users/raymondzhao/work/endgame/vscode-mock-debug')` (fetching `context.extensionUri.toString()`) in the devtools of the running web extension host, but I get 

`VM334:1 Refused to connect to 'file:///Users/raymondzhao/work/endgame/vscode-mock-debug' because it violates the following Content Security Policy directive: "connect-src 'self' https: ws:".`

**Comment by deepak1556** [comment]
I agree that any local resource that is requested by the electron renderer should only rely on `vscode-file` this includes extension resources that are loaded in the web worker host. The reason we deprecated `file` scheme is because of its opaque origin (`file://`) and privileged access to web apis in electron. Origin of a page plays a crucial role in the web api security policies as well as process isolation. Couple of ex: 

1) If multiple windows load pages over `file` then they would all be put in the same process under the [process per site modal](https://source.chromium.org/chromium/chromium/src/+/main:content/public/browser/site_instance.h;l=25-93) of chromium, but with `vscode-file` we can control the isolation per unique origin.

2) `vscode-file` also has the benefits of letting the application control where a resource can be loaded from the local filesystem and also allows leveraging native code caching because of origin isolation.

3) `File` schemes are disallowed to read other `file` resources by default but electron allows it using https://source.chromium.org/chromium/chromium/src/+/main:content/public/common/content_switches.cc;l=13-15

> Treat the vscode-file scheme as an implementation detail and enable fetch and friends to work for that scheme. This sounds more reasonable to me and @alexdima because technically file is the right/trus scheme.

Agree with this approach, `vscode-file` acts an alternative to client-server modal on the web where the main process acts as the server implementing the resource loading policies, so its purely an implementation detail that should be hidden to extensions.

Btw fetch should already work with `vscode-file` resources https://github.com/microsoft/vscode/blob/48dce61ec3430e9c430b606c824b6bf005db11a2/src/main.js#L81, can you expand what doesn't work today ?

**Comment by deepak1556** [comment]
@rzhao271 are you testing with the latest insiders ?

1) If you try fetch with a file scheme resource inside web worker extension host, it will now use `vscode-file` internally.
2) Issue request and inspect the url in developer tools

```
// For ex: evaluate the following in web worker context
async function f() {
   await fetch('file:///Users/demohan/github/vscode-extension-samples/helloworld-minimal-sample/package.json');
} 
f()

// developer tools 
fetch("vscode-file://vscode-app/Users/demohan/github/vscode-extension-samples/helloworld-minimal-sample/package.json", {
  "referrer": "",
  "referrerPolicy": "strict-origin-when-cross-origin",
  "body": null,
  "method": "GET",
  "mode": "cors",
  "credentials": "omit"
});
```
