### ISSUE TITLE
Filter debug variables

### ISSUE THREAD

**Issue by omid3098** [microsoft/vscode#13201]
Feature Request:

It would be very handy if you are able to search and filter debug variable.
just by having a searchbox in debug sidebar.
# editor #feature-request

**Comment by lebnic** [comment]
Would be very useful indeed. VSCode search / global_search are some of my favorite feature of the IDE. Now that I am finally using the debugger for my project, I wish a search would be available for the Debug variables

**Comment by isidorn** [comment]
This actually works now. Just start typing in the VARIABLES view and the tree will nicely filter it
Please note that we lazily expand all variables, so if the variable is not expanded yet the tree will not find it. That is just by design, otherwise this operation would have to expand all variables infinetely which the debug adapter might not be able to handle

![hello](https://user-images.githubusercontent.com/1926584/66384609-58d6ac80-e9bf-11e9-9ad0-1bb4c194e31a.gif)
