### ISSUE TITLE
Inline suggestions are shown in solid color instead of grey

### ISSUE THREAD

**Issue by juihanamshet1** [microsoft/vscode#132017]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:
I've attached the source code. The bug shows up sometimes in the last but one line of the file. 
[snake-game.zip](https://github.com/microsoft/vscode/files/7087304/snake-game.zip)

https://user-images.githubusercontent.com/86270736/131589755-e025b97d-e817-4d34-a516-8c3dab981661.mp4

Note: One theory is that the inline suggestion is rendered more than once and if text is shown in grey by modifying opacity, it could be overlapping and causing it to be white.

**Comment by hediet** [comment]
The problem is that show-unused/unnecessary interfers with the ghost-text-decoration styles (the code after the while true loop is unreachable). Because it overrides opacity, but not color, it appears lighter.

![image](https://user-images.githubusercontent.com/2931520/132833592-8622f273-40f2-4dd1-92c8-ec1e99099eb2.png)

**Comment by hediet** [comment]
I added some `!important`s which should resolve the conflict.
Please verify this issue in Monday's insiders build!
