### ISSUE TITLE
Can’t edit my code

### ISSUE THREAD

**Issue by Vinniethatguy** [microsoft/vscode#132067]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1.
2.

**Comment by Vinniethatguy** [comment]
Whenever I leave a Python file idle or open for too long the file becomes unresponsive. I can't edit my code at all. My keyboard works, but it don't backspace, tab or anything like that. It more so "hovers" over the letter instead of adding a space, tab, delete a word.

**Comment by banani720** [comment]
The VSCode version and OS version are there to help people really clamp down on where the bug is easily. In this new age of CI/CD an undetailed bug report like this is really hard to track down. Could you provide that information at the very least?

If you don't know how to find your VSCode version on MacOS see below instructions:

1. Open VSCode
2. After VSCode has been opened, click 'Code' in the top left corner of your screen
3. Click `About VSCode`

![image](https://user-images.githubusercontent.com/56979512/131712437-b0d0d2e8-8f15-4d5c-a773-0d4b4bf044b3.png)

To find your MacOS version see instructions below:

1. Click the apple logo in the top left corner of your screen
2. Click "About this Mac"
3. Your OS version should be available to you in the "Overview" tab in the window that opens

A gif or screengrab of the observed behavior might also be helpful to help grasp what's going on

**Comment by tkohli** [comment]
Can you make sure that you are using updated versions for VSCode and OS, I was having same issue but was resolved after updating

**Comment by lramos15** [comment]
Closing due to lack of update.
