### ISSUE TITLE
Debugging in VSCode is significantly slower than using command line #4514

### ISSUE THREAD

**Issue by Celthi** [microsoft/vscode#132025]
- VS Code Version:
      Version: 1.58.2 (user setup)
      Commit: c3f126316369cd610563c75b1b1725e0679adfb3
      Date: 2021-07-14T22:10:15.214Z
      Electron: 12.0.13
      Chrome: 89.0.4389.128
      Node.js: 14.16.0
      V8: 8.9.255.25-electron.0
      OS: Windows_NT x64 10.0.18363
- 
- OS Version:

Steps to Reproduce:

1. Debug a C++program with more than 10 threads. See also in https://github.com/microsoft/vscode-cpptools/issues/4514

**Comment by Celthi** [comment]
The conclusion in https://github.com/microsoft/vscode-cpptools/issues/4514#issuecomment-548068597 is to let vscode request less data or be able to configure data the user is interested in.

**Comment by bence42** [comment]
There's the same issue when the debugger has to load many dlls, even if the application is single threaded. Command line gdb is fast, but the same from vscode is slow. The debug console is filled with "=library-unloaded,id=.." messages.

**Comment by weinand** [comment]
@bence42 please file the issue with too many "=library-unloaded,id=.." messages on the debug console against the debugger extension you are using.

**Comment by jusid** [comment]
I am developing a C application with 150+ threads and debug it remotely via gdbserver. When the first breakpoint is hit, vscode requests detailed information about every thread in the application and it takes about 3 minutes to complete. The debugging is very painful due to this.
It would be great if vscode requests information about the current thread only and query other thread on-demand.

**Comment by reneparis** [comment]
Same issue here, when trying to debug our project.
Might also relate to the (prematurely) close issue of cpp-tools https://github.com/microsoft/vscode-cpptools/issues/2901

**Comment by jusid** [comment]
Here is what happens when a break point is hit and why it takes so long.
The break point is hit:
```
1: (20384) ->=thread-created,id="2",group-id="i1"
1: (20384) ->~"[New Thread 1800]\n"
1: (20385) <-1023-thread-info 2
[New Thread 1800]
1: (20389) ->=breakpoint-modified,bkpt={number="3",type="breakpoint",disp="keep",enabled="y",addr="0x00b5efb4",func="x",file="x.c",fullname="x.c",line="568",times="1",original-location="x.c:568"}
1: (20390) ->~"[Switching to Thread 1800]\n"
[Switching to Thread 1800]
1: (20466) ->*stopped,reason="breakpoint-hit",disp="keep",bkptno="3",frame={addr="0x00b5efb4",func="x",args=[],file="x.c",fullname="x.c",line="568"},thread-id="2",stopped-threads="all",core="0"
```
Information about all(!) threads is requested:
```
1: (20467) <-1024-thread-info
```
While GDB executes the request above, it reports availability of new threads (158 in my case):
```
1: (20509) ->=thread-created,id="3",group-id="i1"
1: (20509) ->~"[New Thread 1639]\n"
1: (20509) ->=thread-created,id="4",group-id="i1"
1: (20509) ->~"[New Thread 1640]\n"
1: (20509) ->=thread-created,id="5",group-id="i1"
1: (20510) ->~"[New Thread 1641]\n"
```
vscode starts to request info about each reported thread. Even though information about all threads has been requested earlier:
```
1: (20510) <-1025-thread-info 3
1: (20510) ->=thread-created,id="6",group-id="i1"
1: (20510) ->~"[New Thread 1642]\n"
[New Thread 1639]
1: (20510) ->=thread-created,id="7",group-id="i1"
1: (20510) ->~"[New Thread 1649]\n"
1: (20510) ->=thread-created,id="8",group-id="i1"
...
```
```
...
1: (20528) <-1178-thread-info 156
[New Thread 1798]
1: (20528) <-1179-thread-info 157
[New Thread 1799]
1: (20528) <-1180-thread-info 158
[New Thread 1801]
1: (20528) 1023: elapsed time 143
1: (20528) Send Event AD7ThreadCreateEvent
...
```
Information about all 158 threads has been requested.
After 11 seconds GDB returns response to request ```1024-thread-info``` and starts to slowly return responses for individual thread info requests:
```
...
1: (31603) ->1024^done,threads=[{id="158",target-id="Thread 1801",frame={level="0",addr="0xb6e97798",func="??",args=[]},state="stopped",core="0"},{id="157",target-id="Thread 1799",frame={level="0",addr="0xb6fa7ce4",func="??",args=[]},state="stopped",core="0"}, ...
1: (31604) ->(gdb)
1: (31606) 1024: elapsed time 11138
1: (32457) ->1025^done,threads=[{id="3",target-id="Thread 1639",frame={level="0",addr="0xb6e91e7c",func="??",args=[]},state="stopped",core="0"}]
1: (32458) ->(gdb)
1: (32458) 1025: elapsed time 11948
1: (33343) ->1026^done,threads=[{id="4",target-id="Thread 1640",frame={level="0",addr="0xb6e97798",func="??",args=[]},state="stopped",core="0"}]
...
```
After 151 (!) seconds GDB responds to the last thread info request and is almost ready to inform a user about the break point:
```
...
1: (171843) ->1180^done,threads=[{id="158",target-id="Thread 1801",frame={level="0",addr="0xb6e97798",func="??",args=[]},state="stopped",core="0"}]
1: (171843) ->(gdb)
1: (171844) 1180: elapsed time 151315
1: (171845) <-1181-stack-list-frames 0 1000
```
Conclusion: it is not needed to request individual thread info since all thread info is requested anyway and such combined request is executed much much faster compared to many individual requests.

**Comment by EstebanDugueperoux2** [comment]
I have the same issue with official cpp debug extension, but not with https://marketplace.visualstudio.com/items?itemName=webfreak.debug extension which seems to interact direct with GDB.

**Comment by olgapshen** [comment]
It was very slow for me to debug Qt, **but** now it is also very slow on Java.
When I put breakpoint and start the debuger it hits the breakpoint almost rapidly, but if I put breakpoint some lines before and try to hit previous point step by step, it is extrimly slow.

* Operating System: openSUSE Leap 15.3
* JDK version: openjdk version "11.0.13" 2021-10-19
* Visual Studio Code version: 1.71.2
* Java extension version: v1.10.0

**Comment by weinand** [comment]
As reported [above](https://github.com/microsoft/vscode/issues/132025#issuecomment-1214756022), the ["Native Debug" extension](https://marketplace.visualstudio.com/items?itemName=webfreak.debug) does not suffer from this problem which is evidence, that VS Code is not the problem. 
I suggest that you file issues against the debug extensions you are using.

**Comment by reneparis** [comment]
Please don't close that issue prematurely. In my opinion, the Native Debug extension is not comparable.

**Comment by reneparis** [comment]
For me, https://github.com/microsoft/vscode/issues/132025#issuecomment-909792995, https://github.com/microsoft/vscode/issues/132025#issuecomment-909792995,  and https://github.com/microsoft/vscode/issues/132025#issuecomment-1132866384 point to the right direction where to tackle that issue actually.

**Comment by jusid** [comment]
Please re-open this issue. The problem exists when using VS Code with the C/C++ extension (both from Microsoft and both are great). The suggestion to use the Native Debug extension is not a good option, since it is very limited compared to the excellent debugger in the MS C/C++ extension.
Here https://github.com/microsoft/vscode/issues/132025#issuecomment-1132866384 I provided the exact reason of the slowdown. I can't say which party (VS Code or C++ extensions) requests unneeded information from gdb when the first breakpoint is hit. It is needed to investigate this by looking at source code before closing the issue.
Thanks.

**Comment by weinand** [comment]
Since I'm not aware of reports that debugging in VS Code is slow across all debug extension, I suggest that you first file the issue against the debug extension you are using.

All the trace logs from above show the traffic between the debug extension and the backend debugger. Since they don't show the traffic between VS Code and the debug extension, the VS Code debugger team cannot start the investigation. 

By filing the issue against the debug extension first, the extension authors can analyse the excessive traffic you are observing and can either try to address the problem in their extension, or can create issues against VS Code (or the Debug Adapter Protocol).
