### ISSUE TITLE
API: Improved Output Channel rendering capability for extension developers - Way to replace/update the content

### ISSUE THREAD

**Issue by smcenlly** [microsoft/vscode#132183]
Our extensions use the Output window extensively to show custom output. We use custom grammars and other mechanisms supported by the API (e.g. Code Lens) to create a nice interactive output (example below):

<img width="1177" alt="image" src="https://user-images.githubusercontent.com/2074089/131934832-fdc1478f-9ef9-4865-8e9c-f98c9f2f09b4.png">

We (and our users) have been frustrated by by Output window delays (it can take a second or so to update) as well as flickering when we update our Output window content (see below).

![quokka-output-flickering](https://user-images.githubusercontent.com/2074089/131936218-84a66793-5450-4131-8208-c78ca079ec25.gif)

We were planning on submitting a PR to fix the flickering/re-render problems but after investigating how the Output window is implemented, it seems the delays and flickering are a result of the output being buffered to a file and the output window loading from there (keeping track of start/end offsets when `clear` is called on the output window). This implementation makes sense for the generic use case of the Output window but in our case, we have a limited output and as a result we `clear` the entire content and re-render everything for each update that our extensions provide.

Given the implementation of the Output window, we thought that maybe it's more correct to extend the output channel rendering capabilities to align with out TextEditor rendering capabilities (since that's what is used for the output channel) and have created this feature request instead. We were thinking that adding support for the `CustomReadonlyEditorProvider` and `CustomTextEditorProvider` mechanisms for the Output channel would provide the flexibility we need to render the Output channel the way we need.

Is this a valid way of improving Output channel flexibility for extension developers? Or is there a better approach? Ideally we want instant update + no flickering but understand this probably does not fit with the existing implementation.

**Comment by jrieken** [comment]
> how the Output window is implemented, it seems the delays and flickering are a result of the output being buffered to a file and the output window loading from there

Yeah, that was a very conscious design decision because output channels are meant to be used for logging purposes. Logging often generates much data at high frequency. Therefore we don't send log message via IPC - it would block the connection for other messages like the ones for IntelliSense etc. 

Leaving this open and assigning to @sandy081 because I believe we do something special for visible output channels. However, don't expect too much here as the usage of rich output channels is bit off the beaten/expected path

**Comment by smcenlly** [comment]
@jrieken - thanks for the fast reply.

I completely understand why you would make that design decision. As I said, this is why I thought this is more of an enhancement to the UI than a bug fix.

We have thought about some alternatives, namely adding a web view that can be docked at the bottom of the screen. If we were to go down that path, we'd be mostly reimplementing parts of the text editor, messing around with styling and the result would be a much worse user experience (extra section in bottom dock, not actually the extension output). Right now, output is semantically correct, we'd just like a way to extend it a little (or take control of the delayed rendering for our specific use case).

I understand that rich output channels may be off the beaten path a little bit but you never know what people will do with the API once it becomes available (I am sure it would see use - especially the web view concept). 

If the VS Code team agree on an approach to extend this, if the scope is not too large and the result aligns with what we need, I am happy to provide some PRs.

**Comment by sandy081** [comment]
We treat visible channels specially to make sure they are as interactive as possible. For eg., if you append to the visible channel, output channel is updated instantly (of course, time to pass text from ext host to renderer shall be taken into consideration). It seems you want output channel to behave similar to normal text editor which I do not think is not the intention of the output channels. So, I am sorry that we cannot make such enhancements and duplicate/complicate output channel. 

Looking at above gif, it seems you are clearing the output channel and adding the same text again. Have you thought about maintaining the model in the extension and append the text only when needed?

**Comment by smcenlly** [comment]
> Have you thought about maintaining the model in the extension and append the text only when needed?

Yes - we have thought about this and it makes sense for us to do this if there is no alternative. Having said that, in our case it won't fix the problem most of the time. For example, we show output similar to:

```
Output Channel:

Variable A - Line 1: <VALUE A>

Variable B - Line 2: <VALUE B>
```

In this case, the variable values may be ephemeral (time based) or else they may be sourced from a separate system (file read, API call, etc.).

**Most** of the channel actually doesn't change, but obviously some of it does. Because of how the output channel works (and the API - `clear` followed by `append`) we're forcing a full reload all the time.

As an alternative, what about a `replaceAll` function (or similar) which would allow the Output window renderer to be a little smarter about what it's doing?

**Comment by ArtemGovorov** [comment]
@jrieken @sandy081 

Right now visible output channels work great when some content is **appended**, however many extensions (including ours) do need to display some output that:
- has a fairly limited size,
- changes over time, but not dramatically (so needs to be **replaced** rather than **appended**).

Essentially, I'm talking about **various textual reports/summaries** type of output (that do change over time, and can be displayed while user is modifying their code that may affect the output).

When such type of output is displayed in an output channel and needs to be updated, the only way to refresh it is to `clear`& `append`. This is causing the output flickering; the buffering is not an issue here because it's totally fine to have the output refresh delayed if required, however the unnecessary flickering makes the output look distracting.

Since text editor is used for the output, it should be possible to re-render the output without flickering. We are using `TextDocumentContentProvider` in our other extension and when we update the content, it gets updated without any flickering. Unfortunately it's not always possible to use `TextDocumentContentProvider` for such forms of output due to the limitations on where an editor can be displayed/docked in VS Code. 

Perhaps, as @smcenlly is suggesting, a `replaceAll` function (or `update(fullContent: string)`) could be added to output channel API to allow a non-flickering alternative to `clear`/`append`? It can obviously have all required buffering and necessary delays between its call and the output refresh, the important bit is that the transition from the previous to the new output is as smooth as possible.

**Comment by sandy081** [comment]
I see the concerns and it makes sense to me to add an API that replaces the existing content with new content.

**Comment by smcenlly** [comment]
> I see the concerns and it makes sense to me to add an API that replaces the existing content with new content.

@sandy081, @jrieken: I have created a [pull request](https://github.com/microsoft/vscode/pull/136402) with a proposed new API method that fixes the output channel rendering behavior for our scenario.

**Comment by smcenlly** [comment]
You can see the difference between the old method `clear` and `append` vs. `replaceAll` below:

### `clear` and `append`
![quokka-output-flickering](https://user-images.githubusercontent.com/2074089/140259582-59abc4af-9336-4739-81b6-1c77d9e1f780.gif)

### `replaceAll`
![quokka-output-not-flickering](https://user-images.githubusercontent.com/2074089/140259595-1c295666-480c-43cc-808a-aa1dd5ab8c77.gif)

**Comment by sandy081** [comment]
Added following Output api (proposed) to replace the existing contents with the given value
```ts
		/*
		 * Replaces the existing contents of the channel with the given value.
		 */
		replaceAll(value: string): void;
```

**Comment by jrieken** [comment]
Keeping this open to track the API work

**Comment by smcenlly** [comment]
Thank you so much. I look forward to trying it out in the insider's build. 😀

**Comment by ArtemGovorov** [comment]
Thanks a lot @sandy081 @jrieken! The new API unlocks so much in terms of UX improvements for our extensions, it's truly a game changer for quite a few of our features (already released and planned).
