### ISSUE TITLE
Feature-request for a gutter display option.

### ISSUE THREAD

**Issue by brashaw** [Microsoft/vscode#13212]
With everything gutter-related turned off (line numbers, code folding, etc.) there's still significant padding between the code and the edge of the editor: http://imgur.com/MT41OKD

Sublime Text has an option to completely hide the gutter leaving only a few pixels of padding: http://imgur.com/a/1Dsp3

So, an `"editor.gutter": true/false` option that mimics Sublime Text would be great.

**Comment by alexandrudima** [comment]
We also have `editor.glyphMargin` but that is hard-coded to be true by the workbench for breakpoint setting reasons. You can also disable `editor.folding` to gain even more space.

**Comment by isidorn** [comment]
I think it is fair to be able to disalbe glyphMargin for people that do not care about debugging.
So I would bring back this option - but would make it explicit in the comment of that configuraiton that the glyph margin is used for breakpoint managment and disabling it will make the debugging experince worse.

Let me know what others think
ping @weinand

**Comment by alexandrudima** [comment]
@isidorn We could assign defaultConfig.glyphMargin to true somewhere statically such that it is true by default, and remove the hard coding (when it would be disabled, one could define breakpoints only with F9). We could be more fancy and try to do something like: if there is a breakpoint set in a file the glyphMargin is forcefully set to true, otherwise the user setting is respected.

**Comment by brashaw** [comment]
@alexandrudima `"editor.folding": false` is set in my screenshot above.

**Comment by isidorn** [comment]
@alexandrudima nice idea for automatically revelaing glyph maring if there is a breakpoint - however currently I have an issue that I can not depend from BaseTextEditor to the DebugService - it does not get injected. Will add this smartness if I sort this out with @bpasero

**Comment by alexandrudima** [comment]
@isidorn Please be aware that any change you do to the editor default options result in a change in the standalone editor too. In the standalone editor, since the first release the glyph margin has been off by default.

I have corrected the error via 27c2cf41923ad8b7a71a13c221c7c27490c00fea

![image](https://cloud.githubusercontent.com/assets/5047891/19655480/6068773a-9a1c-11e6-858e-835070bfcb29.png)

**Comment by isidorn** [comment]
@alexandrudima thanks a lot! Will be aware in the future.
