### ISSUE TITLE
editor.bracketPairColorization.enabled working not correctly in this case with html template (vue 3.2) 

### ISSUE THREAD

**Issue by natuan62** [microsoft/vscode#132175]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.60.0
- OS Version: MacOs 11.5.2 (mac mini m1)

Steps to Reproduce:

1. enable bracketPairColorization: **"editor.bracketPairColorization.enabled": true**
2. In template vue
![Screen Shot 2021-09-03 at 06 20 57](https://user-images.githubusercontent.com/10808157/131928078-d8e027e7-d800-4464-8334-3de17ce5b5cf.png)

**Comment by nerdondon** [comment]
This also occurs in rust in situations where you create an arrow `=>` (e.g. match statements):

```rust
match an_optional {
    Some(inner) => node = inner,
    _ => break,
}
```

**Comment by HoTKreeZy** [comment]
There is an error with the colorization like in Ruby string interpolation where the opening curly bracket is attach to the number sign (#). The opening curly bracket does not get the colorization but the closing bracket get it

![ruby-string-interpolation-error-colorization](https://user-images.githubusercontent.com/42871753/131978586-a50bc4f0-0c94-43be-b3c7-55166a52831a.png)

**Comment by ioticos** [comment]
Html too?

![image](https://user-images.githubusercontent.com/32907893/132099500-1ac05581-78e2-4e9c-835b-192f6b08e107.png)

**Comment by runxel** [comment]
I am experiencing the same issue.
For most languages it doesn't even makes sense to colorize angled brackets... 🤦‍♂️
I think this feature request would solve this problem! https://github.com/microsoft/vscode/issues/132336

**Comment by hediet** [comment]
[Every language extension can configure which brackets should be highlighted](https://github.com/microsoft/vscode/blob/997228d528d687fd17cbf3ba117a0d4f668c1393/extensions/javascript/tags-language-configuration.json#L11).
By default, the language brackets are highlighted.
If there `colorizedBracketPairs` propery, only those bracket pairs are highlighted.

The documentation for this new property is still missing.
Please reach out to the extension authors to configure this propery, if the default has issues!

@HoTKreeZy The underlying problem is [this](https://github.com/microsoft/vscode/issues/131092). Unfortunately, this seems to be a restriction by chrome/electron (and even firefox). If you disable ligatures, it should work.

**Comment by nerdondon** [comment]
I'm a little confused. this was not happening with the bracket pair colorizer extension. even if the extension had a per-language config, it has been working out of the box for me just fine without having to touch such a config.

**Comment by hediet** [comment]
> this was not happening with the bracket pair colorizer extension

Because the bracket pair colorizer extension explicitly does not colorize `<` and `>` - this exception is baked into the extension and even languages that want to colorize these brackets cannot do so.

We introduced a per language config (rather than assuming that `<` ... `>` is the only problematic pair and not colorizing it for any language).

If a language does not configure which brackets to colorize, VS Code colorizes all configured brackets. If you think we should, by default, remove `<`...`>` from this list when using it as default for colorized bracket pairs, please open a separate issue. While it would fix the issues mentioned here, it would only do so because `<`...`>` should not be colorized in *most* languages. That's why I'm unsure if this is a good default.

**Comment by lorand-horvath** [comment]
@hediet Not really a good default to have angled brackets `< >` colorized in all languages, it probably generates more problems than it solves. I opened a new issue for this #132476
