### ISSUE TITLE
Add user setting to swap sides for the diffEditor when viewing git changes

### ISSUE THREAD

**Issue by j-h-a** [Microsoft/vscode#13225]
When viewing your local changes in the changes view / diff editor, the read-only HEAD is shown on the left and the local file on the right. This seems very unnatural to me, especially when editing the local file in this view. I want to see the local file on the left and the HEAD on the right for reference.

I propose adding a user setting to swap these panes, or a toggle/swap button `<->` between the panes. The settings option would be something like:

```
"diffEditor.localChangesOnLeft": true,
```

**Comment by alexandrudima** [comment]
To keep the number of issues in our inbox at a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: we look at the number of votes the issue has received and the number of duplicate issues filed. Thank you for your time and understanding.

If you disagree and feel that this issue is crucial: we're happy to listen and to reconsider.
