### ISSUE TITLE
Issue with terminal and git bash

### ISSUE THREAD

**Issue by x-garcia** [microsoft/vscode#132262]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.60.0
- OS Version: Windows_NT x64 10.0.19043

Steps to Reproduce:

1. Open terminal (git bash)
2. Type a git command that requires authentication (git fetch with passcode)
3. Press CTRL + C
4. Every command that you try to type now will be invisible

Here is a gif with a example:
<a href="https://giphy.com/gifs/PLG5XTD3qCeNpWVhAI">via GIPHY</a>

**Comment by x-garcia** [comment]
> Does this issue occur when all extensions are disabled?: Yes/No
> 
> * VS Code Version: 1.60.0
> * OS Version: Windows_NT x64 10.0.19043
> 
> Steps to Reproduce:
> 
> 1. Open terminal (git bash)
> 2. Type a git command that requires authentication (git fetch with passcode)
> 3. Press CTRL + C
> 4. Every command that you try to type now will be invisible
> 
> Here is a gif with a example:
> [via GIPHY](https://giphy.com/gifs/PLG5XTD3qCeNpWVhAI)

**Comment by x-garcia** [comment]
Closed by accident

**Comment by x-garcia** [comment]
@meganrogge I can't see the relationship between this issue and the one you referenced.

**Comment by Tyriar** [comment]
Here's the right link: https://github.com/microsoft/vscode/issues/89222

I believe this is happening due to conpty which is baked into Windows. You can test on [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701), if you can repro there it's an issue for https://github.com/microsoft/terminal, if it's fixed it will likely come to VS Code in a Windows update.
