### ISSUE TITLE
When opening two editors with medium size projects the disk usage is too high

### ISSUE THREAD

**Issue by tcpip4000** [Microsoft/vscode#13228]
- VSCode Version: 1.5.3
- OS Version: Linux debian 8

Steps to Reproduce:

1. Open two editors with different projects (in my case typescript and java).
2. Working to 3-6 hours the linux machine (virtual machine with 3GB Ram) hangs with unusual disk operations.

As an additional note when only opening one editor there is no problem.

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by tcpip4000** [comment]
I'll try that.

**Comment by tcpip4000** [comment]
Hi,

Yesterday I worked with no problem, seems that the python extension was the culprit.

Thank you for your kind help.

**Comment by bpasero** [comment]
Ok you should report it to the python extension then 👍
