### ISSUE TITLE
Limit the new bracket pair colorization to certain types

### ISSUE THREAD

**Issue by runxel** [microsoft/vscode#132336]
The native bracket pair color highlighting is great, but I miss an option to exclude certain types of brackets.
I'm coding in a (somewhat niche) language that uses square brackets `[]` for arrays. Arrays in this language can't be nested, so there is just no need to have them colorized. In fact, it's rather adding visual clutter.

So maybe there could be a new setting where you can toggle for each bracket type if it should be highlighted or not.

**Comment by oaahmad** [comment]
@runxel You say you don't want "[ ]" to be colored because those types of brackets are never nested. There is another way to achieve what you want. See https://github.com/microsoft/vscode/issues/131027 and my comments there. If that feature is implemented and you set the first bracket pair color to black (white if you use a dark theme) then all top-level brackets of each type would not be colored. Only nested brackets of the same type would be colored. The result is a little different because it applies to all bracket types. You may like that less, or you may like that more. It's just a different way to achieve what you want.

**Comment by runxel** [comment]
@oaahmad To have only the nested brackets of the same type to have color would be nice choice, too!
This would also solve my case, I guess.
Most times the outermost bracket also doesn't need to be in a different color than it would be normally anyway.

**Comment by HoTKreeZy** [comment]
Personally, I like to have brackets colored even though they are not nested.
So I think that there is some settings about this feature that are missing like the possibility to set new colors and force iteration ([this issue](https://github.com/microsoft/vscode/issues/131027) requests this last setting)

**Comment by hediet** [comment]
You can [configure supported bracket pairs](https://github.com/microsoft/vscode/blob/997228d528d687fd17cbf3ba117a0d4f668c1393/extensions/javascript/tags-language-configuration.json#L11).

**Comment by runxel** [comment]
@hediet 
This should not necessarily live in the extension alone!
I think the user should have the power to overwrite this in his personal settings.

**Comment by hediet** [comment]
I think you might be looking for https://github.com/microsoft/vscode/issues/131412.
