### ISSUE TITLE
Some info about extension now not shown in Extensions any more

### ISSUE THREAD

**Issue by cateyes99** [microsoft/vscode#132497]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: **_1.60.0 x64 zip_**
- OS Version: **_Windows 10 Enterprise_**

Steps to Reproduce:

1. Open the Extensions panel, observed that in the Enabled view & Disabled view, _version info_, _download counts_, & _stars_ are missing.
![image](https://user-images.githubusercontent.com/19678455/132265103-12b605b4-d1a2-4e63-8381-a5c9b0e30bbb.png)

Compare to a previous version (**_1.57.1_**):
![image](https://user-images.githubusercontent.com/19678455/132265195-1d9f36e7-2e0a-4935-ab38-45cea205c013.png)

**Comment by sandy081** [comment]
Yes it was intentional. It is reduce the clutter and make it simpler by only showing the necessary information. As a regular user - install count and rating are necessary only while installing. After installing it is more important to know how extension is running. Also version is of least concerned to the user. You can see the version by hovering on the extension.
