### ISSUE TITLE
Inline completions that replace indentation not consistently showing

### ISSUE THREAD

**Issue by hsenag** [microsoft/vscode#132438]
Issue Type: <b>Bug</b>

Some Ghost Text completions returned by Copilot aren't showing up in the UI. We discussed this a bit already with @hediet, I'll try to create a minimal extension to demonstrate it without Copilot.

VS Code version: Code 1.60.0 (Universal) (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:54:53.442Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

**Comment by hsenag** [comment]
[Here's a small repro](https://github.com/microsoft/vscode/files/7116599/issue-961.zip). Only significant files are `src/extension.ts` and `package.json`. I reduced the problem to the difference between the completion containing a space after the initial text or not:

```
async function provideInlineCompletions(document: vscode.TextDocument,
                                        position: vscode.Position,
                                        context: vscode.InlineCompletionContext,
                                        token: vscode.CancellationToken):
   Promise<vscode.InlineCompletionItem[]> {
	let res : vscode.InlineCompletionItem =
		{
			// Start a new file and start pressing space. After the first space,
                        // the inline completion is shown. After the second space, it disappears.
			text: " r ",
			// but if we use this completion instead, i.e. without the trailing space,
                        // then the inline completion remains.
			// text: " r",
			range: new vscode.Range(new vscode.Position(position.line, 0),
                                                new vscode.Position(position.line, position.character)),
		};
	return [res];
}
```

**Comment by hediet** [comment]
This is actually by design.

When configuring `"editor.inlineSuggest.mode": "subword"`, you'll see this:

![image](https://user-images.githubusercontent.com/2931520/132836197-a8d87014-e8e6-4f1c-825b-3a35707c07f9.png)

Internally, `··` (`·` for a single whitespace) is matched with `·r·`.
The diffing yields that the inline suggestion wants to insert `r` in the middle.

However, when the cursor is after the two dots (`··|`), that would show ghost text before the cursor ( `·[r]·|`). But since the default value of `editor.inlineSuggest.mode` is `subwordSmart`, any ghost text before the cursor is not shown.

---

Cannot you just trim trailing whitespace?

**Comment by hsenag** [comment]
It's not just about trailing whitespace, I just ended up with a minimal example that had it. You can replace `" r "` with `" return x"` and it still happens.

**Comment by hediet** [comment]
Thanks for the example. It makes sense and I'll think about how to fix this.

**Comment by hediet** [comment]
Please verify the bugfix in Mondays insider release of VS Code!

The fix was quite complex, as there are quite a few cases how suggestions can change indentation.

**Comment by hsenag** [comment]
`/verified`

Looks good, at least with the example we had.
