### ISSUE TITLE
Inform users when some extensions from an extension pack cannot be installed since they are not web extensions

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#132549]
If you install an extension pack in web which contains non web extensions, those extensions will silently fail to be installed. This is confusing and there should be indication that some extensions are not installed

**Comment by sandy081** [comment]
Following dialog is shown while installing an extension pack in web and if it has extensions not supporting web

![image](https://user-images.githubusercontent.com/10746682/133994360-05030914-aad8-41b4-9b0a-4393fe48792f.png)

**Comment by sandy081** [comment]
To verify:

- Open github.dev on a repo
- Go to extensions view
- Look for extension packs - Filter > Categories > Extension Packs
- Install an extension pack that has all extensions supported in web say bierner.github-markdown-preview. Make sure extension pack with all extensions are installed without any prompts.
- Install an extension pack with extensions not supported in web say `Python Extension Pack` and make sure you see above dialog. 
- Make sure the actions in the dialog are working as expected

**Comment by isidorn** [comment]
> We do not have upfront information to know if all extensions are supported or not unless we get all extensions. Hence the install action is not disabled.

But you do seem to have the information since you render the extensions as disabled in the `Details` Extension Pack page before user installed it? Though you probably get that in Step 2, only once the user has clicked on the extension.

The current experience with the dialog is fine, but it would be much better if we could just not render the Install button at all. There are not a lot of extension packs in general, could we fetch all the sub extensions when rendering the extension pack in the extension view list? If that would introduce an ugly code path I am fine not doing it.

**Comment by sandy081** [comment]
Yes, I know if an extension can be installed or not only when I query MP, because MP has info that if an extension is a web extension or not. Its not performant to do it in extensions list view and also not trivial. This might also introduce some inconsistencies and buggy. Hence I would prefer not to do and live with the dialog.
