### ISSUE TITLE
Provide an option to cancel language auto detection

### ISSUE THREAD

**Issue by duxingzhe** [microsoft/vscode#132505]
Issue Type: <b>Feature Request</b>

I like visual studio code very much. I have used it since it was first public released. I like to use it as a light editor when it was run in plain text mode. However, the auto detection for programming language let me feel inconvenient when I input the plain texts. It always change into auto detection mode. Please provide an option to set plain text as default.

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:54:53.442Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

**Comment by WayneLambert** [comment]
Additionally to this, I suspect it can actually get in the way of some issues.

I have always had the following snippet within my `.gitconfig` and `settings.json` files respectively which enables me to use VS Code to craft my git commit messages using the editor.

```toml
[commit]
  template = ~/.gitmessage
```

```json
    ...
    "files.associations": {
        ".gitmessage": "git-commit",
    }
    ...
```

Following the update to VS Code 1.60, when I run `git commit` from the command line, the editor still opens up and now the language that is assigned to the commit message starts out by being `Coffescript`. Following some more typing, it changes to `YAML`. I suspect this is to do with the automatic language detection features and VS Code not recognising the `.gitmessage` file as having a file association.

Can't we just have a setting where we can disable language detection entirely? I didn't see such a setting the docs and I have tried to type in various settings from previous months' documentation within `settings.json` because I thought that there might be.

**Comment by gjsjohnmurray** [comment]
@WayneLambert see https://github.com/microsoft/vscode/issues/132173#issuecomment-912450835

**Comment by WayneLambert** [comment]
@gjsjohnmurray Perfect, thank you so much for this! 😄  I feel like I've got my editor back. 👍🏼

**Comment by TylerLeonhardt** [comment]
@WayneLambert yes I think for you, you want to turn of the language detection feature which you can do with:

```
"workbench.editor.languageDetection": false
```

this will stop the auto-detection but still allow you to click on the language picker in the bottom right and hit "Auto Detect" when you want.

Since we have a setting to do this already, I'll close this issue.
