### ISSUE TITLE
Can't report an issue via "Report Issue" interface

### ISSUE THREAD

**Issue by u84six** [microsoft/vscode#132648]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:
- OS Version:

Steps to Reproduce:

1. Select "Report Issue"
2. Fill out the form (selected Extension)
3. Select "Preview on GitHub" -- oddly, this is the only button available
4. Takes you to the GitHub  

Nothing else happens. The only option is to use the "Report an Issue" interface on GitHub and nothing about the form that has been filled out is used. Also, you can't alt-tab to this form page on Windows 10, which makes it really annoying.

5. I changed "File on" to Visual Studio Code, then clicked "Preview on GitHub" and got an error message that there's too much data in the form and that it was copied to the clipboard. This form has hardly any text. It a very brief form (less info than this form).

The design of this form is difficult to understand. What is Preview on GitHub supposed to do? Also, the window that's used for the form is probably some type of modal, so you can find it in alt-tab, which makes it really annoying to use.

**Comment by TylerLeonhardt** [comment]
We use GitHub for tracking issues so that's why Report Issue talks about GitHub.

> and got an error message that there's too much data in the form and that it was copied to the clipboard

The way that the issue filer works is that it opens this in your browser where ISSUETEXT is generated from your form input:

https://github.com/microsoft/vscode/issues/new?body=ISSUETEXT

Unfortunately, browsers have a limit as to how much text can be shoved into the address bar and so when we detect that the form content has too much text, we store the text into the clipboard and ask you to paste it in to the page that opens in your browser.

> What is Preview on GitHub supposed to do?

The idea is that you are previewing what your issue will look like on GitHub before you hit "Create issue" on GitHub.

>  so you can find it in alt-tab

This is captured in https://github.com/microsoft/vscode/issues/130497

I hope this helps understand what this flow is about! Here are the current active issues on the issue reporter if you wanna "plus one" any of them:
https://github.com/microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+label%3Aissue-reporter+
