### ISSUE TITLE
“Match Whole Word” not working properly in Global Search

### ISSUE THREAD

**Issue by xianghongai** [microsoft/vscode#132730]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.60.0
- OS Version: Windows NT x64 10.0.19043

```
Version: 1.60.0 (user setup)
Commit: e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff
Date: 2021-09-01T10:41:52.311Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043
```

Steps to Reproduce:

1. save

```
const LICENSE_ACTION_TYPE_LIST = {}
const LICENSE_ACTION_TYPE = {}
const LICENSE_ACTION = {}
```

2.  `ctrl+shift+f` global search, like this: 

![VSCode-Issue-1](https://user-images.githubusercontent.com/2075006/132644160-9d6ed146-fea8-4af1-b8ab-99121d629bcc.png)

**Comment by ArturoDent** [comment]
Since an underscore `_` is a word separator in javascript, the search should find all three of your examples.  I.e., the `_` is at a word boundary.  You can test this by removing the underscore from the setting:

`Editor: Word Separators` 

and re-running your search and then you would get your expected single `License_Action` find.

**Comment by xianghongai** [comment]
It is normal to search in the current document and turn on "Match Whole Word".

Search should not be affected by settings.

**Comment by roblourens** [comment]
I actually can't repro this. Is it possible that you have changed the wordSeparators setting to include underscore?

**Comment by ArturoDent** [comment]
That's funny.  I did add the underscore to my wordSeparators (long forgotten) and so I can reproduce what I think @xianghongai doesn't like.  If I remove the underscore, there is only the one find result: `LICENSE_ACTION`.    So that does appear to be the issue...

Is it possible an extension changed that setting?

**Comment by xianghongai** [comment]
@roblourens @ArturoDent 
Yes, the ‘wordSeparators’ setting contains underscores~😂
![VSCode-Issue-132730](https://user-images.githubusercontent.com/2075006/133009553-ceb8b335-05b7-4107-9f6d-0919d4005c75.png)
