### ISSUE TITLE
[folding] Newlines created by Insert Line Above command get sucked into previous code fold

### ISSUE THREAD

**Issue by acls** [microsoft/vscode#132784]
Issue Type: <b>Bug</b>

I'm using pug, but this happens with other indention based languages like python.

Using the following code block, fold the first `ul` and put the cursor in front of the second `ul`.
If you press enter a newline is added outside the fold, but if you use the Insert Line Above command(ctrl+shift+enter) the newline gets sucked into the fold.
```Pug
ul
  li 
ul
  li 
```

VS Code version: Code - Insiders 1.61.0-insider (aec6ee09fa1021cb59c7f4f4d000b027febc967d, 2021-09-03T05:15:18.823Z)
OS version: Linux x64 4.15.0-154-generic
Restricted Mode: No

Extensions: none

**Comment by aeschli** [comment]
We currently only expand when the selection(cursor) enters a folder range. That's not happening with insert line above.

Not sure what the expectation is...

**Comment by acls** [comment]
The newline should go under the fold and not into the fold. It is completely pointless to put the cursor into the fold where you can't even see what you are typing.

**Comment by acls** [comment]
This is a bug. Not a feature request.

**Comment by acls** [comment]
@aeschli This is not a feature request

**Comment by acls** [comment]
So you agree that it is a bug? "By design we only unfold when the cursor enters a fold"
The cursor is definitely entering the fold. But it shouldn't. The cursor should go under/outside the fold and the fold should stay folded.

**Comment by acls** [comment]
It is either a bug because:

1. the cursor enters the fold, but the fold doesn't unfold.
2. the cursor enters the fold, but should actually go outside the fold and the fold should stay folded.

It sounds like you're saying number 1.
I'm saying number 2.

**Comment by aeschli** [comment]
There's a bug when updating the hidden ranges after the new line is added
- initially, line 1 is hidden
- new line is added after line 1. The editor enlarges the hidden ranges by one line (line 1 and 2 hidden)
- the folding provider recompute the hidden lines and because it is Python (offside mode) the new line is not part of the folded range.
- he folding provider sets [line 1 to hidden]. Because this matches what we set the last time and skip the update (:bug: )

I pushed a fix to listen to document changes and always update the hidden ranges if there are line changes (additions/removals)

Now it turns out the editor also has a bug when optimizing updates: https://github.com/microsoft/vscode/issues/136867

**Comment by aeschli** [comment]
Full fix depends on fix for #136867.
