### ISSUE TITLE
Template literals brackets in build in Brackets colorizer

### ISSUE THREAD

**Issue by Muhammad-Arsalan31** [microsoft/vscode#132847]
Issue Type: <b>Feature Request</b>

It is great that vs code now supports built-in brackets colorizer. one issue that I found with this is that it also colorizes the template literals variables with the sequence. I should not colorize it with the sequence

for example 
```
    const res = await axios.get(
        `http://url.com/${id}`
      );
```

the template literal variable changes its color on the sequence it is 

my request is that the template literal variables should have only one color.

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

**Comment by lorand-horvath** [comment]
For template literals, it should, in fact colorize ${ and } in the same color, not $ in blue and the curly brackets in yellow/magenta/blue.

This is just one of the many issues with the new bracket pair colorization implementation, which frankly, seems to be low quality work overall, or at least the implications haven't been thought out properly. See https://github.com/microsoft/vscode/issues/132476 and https://github.com/microsoft/vscode/issues/132175 and https://github.com/rust-analyzer/rust-analyzer/pull/10186 and https://github.com/microsoft/vscode/issues/132762 and https://github.com/microsoft/vscode/issues/132432 and ... ok, need I go on?

**Comment by Muhammad-Arsalan31** [comment]
>

**Comment by lorand-horvath** [comment]
@hediet Is there any progress on this? `${ }` should have the same color in JS template literals.

**Comment by hediet** [comment]
Unfortunately, there is no easy fix for this.

The bracket pair colorizer algorithm cannot distinguish the following usages of `{`...`}`:
```
if (true) ${

}
```
vs
```
const str = `${myValue}`;
```

For some reason, the original bracket pair colorizer extension does not see template literals (and thus does not colorize such brackets), maybe that is due to the extension using an older version of the tokenization library.

We could add `${` ... `}` as colorized bracket pair though, which would cause `$` in both examples to be highlighted.

---

> This is just one of the many issues with the new bracket pair colorization implementation, which frankly, seems to be low quality work overall, or at least the implications haven't been thought out properly.

I'm sorry you feel like that. Please keep in mind that we iterate quickly and that the core priority has been the performant algorithm.

**Comment by lorand-horvath** [comment]
Thanks @hediet for https://github.com/microsoft/vscode/commit/d6b2e78477e9ac881278b838993f1f9b2900464f

**Comment by hediet** [comment]
What is the issue in HTML templates?
I think d6b2e78 solves this issue.

**Comment by rchiodo** [comment]
/verified

![image](https://user-images.githubusercontent.com/19672699/135330321-636c923e-a31b-467d-aa0c-41dcb2a274bc.png)
