### ISSUE TITLE
[design bug] Make the search filter of debug console more protruding/visible

### ISSUE THREAD

**Issue by tomasbaran** [microsoft/vscode#132995]
There was I stuck in the VSCode because I didn't realize I had the search filter on for a few weeks. Had the filter been more catchy, it wouldn't happen. See more here: https://github.com/Dart-Code/Dart-Code/issues/3536#issuecomment-918262945 

For instance, make the `Showing 4 of 404` button in a different — highlighted (i.e. yellow) color. Currently that grey "button" blends with its background.
<img width="1319" alt="Captura de pantalla 2021-09-13 a las 15 22 31" src="https://user-images.githubusercontent.com/25743901/133100980-6bd87e83-b15f-448e-8306-97b04c3a4e3d.png">

**Comment by roblourens** [comment]
I would hesitate to use a different color because this isn't a warning or problem, but I can see how the filter could be far away from the actual text that you are looking at

**Comment by tomasbaran** [comment]
It's not a warning, it's a search highlight, which is always a different color. Try to filter search in any browser: it will highlight it with yellow color. What about the good old paper, we also use yellow color for highlighting the keywords. But up to you, my friend. Just my 2 cents from the design standpoint.

**Comment by roblourens** [comment]
I just noticed that the Problems view shows this when there are no matches. The debug console is only empty. Would it have helped in your case, or was there pretty much always some match, as in your screenshot?

![image](https://user-images.githubusercontent.com/323878/133155650-bcae674b-8c6f-475f-9970-c41ce07ba4d6.png)

**Comment by tomasbaran** [comment]
Nope, that would have helped. Since, it always matched something.

**Comment by misolori** [comment]
Would it also help if there was a badge on the debug console (like in the problems title)?

**Comment by roblourens** [comment]
I wouldn't do that, I don't think the number of console items is something that the user needs to be alerted too like that

**Comment by lydiayschung** [comment]
I've been thinking about a couple of ideas, let me know what you all think!

The first idea was that we could be consistent with how the filtering shows up in the Problems view. The filtered text is bolded and highlighted.
![Frame 4](https://user-images.githubusercontent.com/60596156/137221220-b9cfe646-d9b2-4b70-9be8-802aa8dfeee0.png)


The second idea was that we could bring the search down to its own row, taking up the whole width, similar to what we see in Keyboard shortcuts and the sidebar search. It could also be helpful when the window is wider since the search won't be all the way to the right while the results are left-aligned.
![Frame 5](https://user-images.githubusercontent.com/60596156/137221512-c3bf7219-cdc9-4ac5-b5e5-99e34a48a862.png)

**Comment by roblourens** [comment]
Merging into https://github.com/microsoft/vscode/issues/142922
