### ISSUE TITLE
Bracket Pair Colorization Settings

### ISSUE THREAD

**Issue by KrOstir** [microsoft/vscode#132910]
The settings text for Bracket Pair Colorization Settings is not intuitive.

```
Editor > Bracket Pair Colorization: Enabled
```

Even if it is not enabled. Checkmark bellow tells everything and the `:Enabled` text can be omitted.

![Code_210911_110908](https://user-images.githubusercontent.com/13023733/132942759-8ce40275-afcb-4590-979d-75b970f0040e.png)

Additionally, the default value could be Enabled.

**Comment by IllusionMH** [comment]
It's common pattern ho have separate `enabled` flag in settings and also reflect it to setting name
![image](https://user-images.githubusercontent.com/1312662/133061740-75869ee0-0be8-4a41-b9d8-8355f5a8eb08.png)
*(Not all of linked has `.enabled` in ID but most have)*

> Additionally, the default value could be Enabled.

It's debatable. People created issues because "syntax highlighting for brackets is broken" when Insiders builds has it enabled by default for testing purposes. So at this moment I doubt that it can be enabled by default for everyone.

/assign @hediet

**Comment by hediet** [comment]
> It's debatable. People created issues because "syntax highlighting for brackets is broken" when Insiders builds has it enabled by default for testing purposes. So at this moment I doubt that it can be enabled by default for everyone.

Currently, we do not intend to enable it by default. Not only are there some bugs left to fix, some people find the colors distracting. Also, for some programming languages (such as Lean), it cannot work reliably: The assumption that brackets can be analyzed separately from the syntactical structure by just looking at tokens does not hold for all languages.

> It's common pattern ho have separate enabled flag in settings and also reflect it to setting name

Yes. As such, this issue will not be fixed for bracket pair colorization alone.

However, you could open another issue to discuss changing the general pattern for all enableable features.

**Comment by KrOstir** [comment]
I agree that it should not be fixed for bracket pair colorization alone.

An issue to make enableable features settings consistent and intuitive has been opened: #132986
