### ISSUE TITLE
 Syntax Highlighting and Opening Link error in Markdown file

### ISSUE THREAD

**Issue by ntnyq** [microsoft/vscode#132974]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.60.0
- OS Version: MacOS 10.14.3

Steps to Reproduce:

1. Copy & paste `[foo-bar](<https://foo-bar.com/foo-bar(foo-bar).ext>)` into markdown file
2. Press <kbd>⌘</kbd> and click the link

[Click here, It works with GitHub's markdown syntax](<https://foo-bar.com/foo-bar(foo-bar).ext>)

**Comment by codingLogan** [comment]
This is my first go at launching into the vscode code, but hopefully this information may be useful.

## Suggestion
Perhaps we could update the parsing of the URI schemes in general to strip out the angle brackets when editing markdown?

See my findings below for why I'm suggesting this, but I'm also unsure of what problems and side effects doing that may cause.


## Summary of findings

Main points of interest
- While the Command + Click doesn't follow the web link when you're `editing` a Markdown file, it does follow the link in the `preview` of the Markdown file.  So I think markdown syntax is actually ok
- In debugging the project a little bit, I found that the link you try to follow that has angle brackets may be trying to `open a file` or something similar (instead of open a web browser)

## Bad and Good Link Examples

```
[Bad - Opens file](<https://foo-bar.com/foo-bar(foo-bar).ext>)

[Bad - Opens file](<http://google.com>)

[Good - Opens browser Link](https://foo-bar.com/foo-bar(foo-bar).ext)

[Good - Opens browser Link](http://google.com)
```

## Code Areas

In the function `parseLink`, I think the scheme of http(s) isn't recognized because of the < > brackets in the link portion.  See `extensions\markdown-language-features\src\features\documentLinkProvider.ts` around line 18, where it tries to recognize the scheme, but doesn't recognize it when it tries calling `getUriForLinkWithKnownExternalScheme`

In the file `extensions\markdown-language-features\src\util\links.ts` you can add a few new schemes, and then you're able to follow the link just fine.  Though, this is probably not the final way the issue should be fixed

```
export const Schemes = {
	...

	http: 'http:',
	https: 'https:',
	httpb: '<http:',
	httpsb: '<https:',

	...
};
```
