### ISSUE TITLE
Support ArrayBuffers in commands

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#133032]
Currently when using `executeCommand`, ArrayBuffers just turn into an empty object. We should support these for efficient data transfer between extensions/extension hosts. We recently added support for them on a protocol level, so support here should not be terribly hard...

**Comment by mjbvz** [comment]
@connor4312  I see two possible approaches to support this:

1. Add this logic specifically for commands (or even just for a specific command). This is what we do for webviews:

https://github.com/microsoft/vscode/blob/18a986bef59989f18164905636cdcc0284ea8196/src/vs/workbench/api/common/extHostWebviewMessaging.ts#L22


2. Make our `rpc` implementation aware of array buffers instead of only supporting VSBuffers. Take a look at how `SerializableObjectWithBuffers` is used in our rpc code as a starting point:

https://github.com/microsoft/vscode/blob/c3f0f3f15692f94e23a249b777ff2285b994f3ce/src/vs/workbench/services/extensions/common/rpcProtocol.ts#L842

The webview serialization logic I linked to above would probably be a good starting point for this
