### ISSUE TITLE
Automatic closing brackets are not working

### ISSUE THREAD

**Issue by markel-official** [microsoft/vscode#133068]
Hi, I have problem with auto closing brackets - it's not closing, I've already checked this option in the settings "Auto Closing Brackets" is set to "always" but it still doesn't work in my JS files. Neither "(" or "{" brackets are closing. That's is pretty annoying. But expect that thank you for your help and amazing product VS Code ;D

**Comment by alexdima** [comment]
This looks like it might be an environmental problem caused by:
* user settings, workspace settings or folder settings
* user installed extensions (or disabled built-in extensions).

Does the issue reproduce when disabling all extensions? Does the issue reproduce when commenting all out settings.json files? Does the issue reproduce when using e.g. our insiders channel (which just gives you a fresh install without any customization) -- https://code.visualstudio.com/insiders/

**Comment by Parajulibkrm** [comment]
Maybe you have enabled Github copilot? Try disabling it and see if the issue persists.

**Comment by markel-official** [comment]
> This looks like it might be an environmental problem caused by:
> 
> * user settings, workspace settings or folder settings
> * user installed extensions (or disabled built-in extensions).
> 
> Does the issue reproduce when disabling all extensions? Does the issue reproduce when commenting all out settings.json files? Does the issue reproduce when using e.g. our insiders channel (which just gives you a fresh install without any customization) -- https://code.visualstudio.com/insiders/

**Comment by markel-official** [comment]
> Maybe you have enabled Github copilot? Try disabling it and see if the issue persists.

Tried. Didn't help

**Comment by alexdima** [comment]
@markel-official Does the issue reproduce when using our insiders channel https://code.visualstudio.com/insiders/ ?
