### ISSUE TITLE
workspaceFolder isn't working correctly

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#133103]

**Comment by Tyriar** [comment]
- workspaceFolder should always show the workspace folder that the terminal was launched from (terminal.integrated.cwd should not affect this).
- cwdFolder should always show the basename of cwd in multi-root workspaces. In single root it should be hidden if the cwd is equal to the the workspaces default initialCwd (terminal.integrated.cwd if set, otherwise workspace folder).
