### ISSUE TITLE
Moving an editor tab to a new group causes `--wait` to be released

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#133124]
I was just in an interactive rebase editing a commit message (`COMMIT_EDITMSG` file), and I moved it to a new group (so I could look more closely at the changes to write a better commit message) and it released the `--wait` on that file. Which caused the wrong commit message to be accepted and the rebase to continue.

**Comment by bpasero** [comment]
I have no idea how to fix this though. Mainly driven by this ugly piece of code:

https://github.com/microsoft/vscode/blob/46f433cdf90a05137b9d2e32721dced9ea9c7735/src/vs/workbench/browser/editor.ts#L174-L174

The ugly part is that we are observing all opened editors for the resource but don't actually know which editor is the one to observe for the `--wait` files.

**Comment by lramos15** [comment]
> I have no idea how to fix this though. Mainly driven by this ugly piece of code:
> 
> https://github.com/microsoft/vscode/blob/46f433cdf90a05137b9d2e32721dced9ea9c7735/src/vs/workbench/browser/editor.ts#L174-L174
> 
> The ugly part is that we are observing all opened editors for the resource but don't actually know which editor is the one to observe for the `--wait` files.

I wonder if something like the Microtask emitter would help in this case since you'll have an open and close fired at roughly the same time. Although that's still really ugly

**Comment by bpasero** [comment]
![image](https://user-images.githubusercontent.com/900690/133442091-aee97fad-f9d7-434c-845d-19e8a95de35d.png)

But yeah, that idea crossed my mind ;)

**Comment by bpasero** [comment]
@lramos15 the `IEditorService.onDidCloseEditor` event now has a `EditorCloseContext` property that conveys more information why an editor was closed:

https://github.com/microsoft/vscode/blob/a6bd8dd06ccdc6a142e3c4efddb08537178a9d9a/src/vs/workbench/common/editor.ts#L736-L758

Maybe this is actually useful for the tabs model work too. The context bubbles up all the way from the model:

https://github.com/microsoft/vscode/blob/a6bd8dd06ccdc6a142e3c4efddb08537178a9d9a/src/vs/workbench/common/editor/editorGroupModel.ts#L393-L393

The fix is to ignore the close event when the context indicates a move:

https://github.com/microsoft/vscode/blob/a6bd8dd06ccdc6a142e3c4efddb08537178a9d9a/src/vs/workbench/browser/editor.ts#L175-L177

**Comment by lramos15** [comment]
I'm not sure if this helps the tab model just because it will receive an open and then close event from two separate groups which is fine. Although we may fire two change events in that case.
