### ISSUE TITLE
Change Run By Line button to next arrow when running

### ISSUE THREAD

**Issue by tanhakabir** [microsoft/vscode#133101]
14:45 of [video log](https://msit.microsoftstream.com/video/71920840-98dc-ae72-3a43-f1ec149ab77a)

I was confused as to how to go to the next line in run by line mode. I would've liked the run by line icon to change to the next line arrow like in the debug toolbar

**Comment by tanhakabir** [comment]
Slow due to screensharing

**Comment by tanhakabir** [comment]
Mistakenly closed

**Comment by roblourens** [comment]
I don't think we should reuse that button, because it is doing something different. Would rather just get people used to clicking the special RBL button to do RBL. Also, we are about to add a "continue" button which is the continue icon from the debug toolbar and don't want to get confused with that.
