### ISSUE TITLE
No feedback from run button with no kernel selected?

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#133271]
Issue Type: <b>Bug</b>

Wasn't sure who to file this issue on so please redirect as needed.

I open an existing python notebook and click run, nothing happens.
I can see, by perusing around the UI that I probably need to select a kernel, but I get no feedback from the run button.

In the gif below I am clicking run, but I did not click select kernel.

![recording (6)](https://user-images.githubusercontent.com/6561887/133659465-1f14d521-32f5-4a65-8af0-c76a831e4a18.gif)

VS Code version: Code - Insiders 1.61.0-insider (da10782b86bd9d895ccb20be4514b19728036951, 2021-09-16T08:31:28.161Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3900X 12-Core Processor             (24 x 3800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.95GB (15.37GB free)|
|Process Argv|--crash-reporter-id 3434a1e9-60b7-446b-986c-27c6457bc73d|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by roblourens** [comment]
Hey @joyceerhl it looks like you changed the kernel select command, now it doesn't work in this scenario, can you check? It is called from here https://github.com/microsoft/vscode/blob/3ca5df67ea1c833493f73dc5d92c696636eacb3f/src/vs/workbench/contrib/notebook/browser/notebookEditorKernelManager.ts#L40-L40 I think the problem is not calling it with a context. Actually I don't know why we call this with `executeCommand` rather than just putting the real work in some method somewhere.

**Comment by joyceerhl** [comment]
Sorry, this was me, looking into a fix
