### ISSUE TITLE
Discord server

### ISSUE THREAD

**Issue by AngeloCore** [microsoft/vscode#133244]
A [discord](https://discord.com) server where you can ask question(s) and you will get a response from someone who understands more than you in up to about 30 minutes (As typscript have done in the [typescript discord server](https://discord.gg/typescript)) 

It's going to be a lot easier and quicker for questions than the github issues. 

Can I get permission to make an official discord server and bot for visual studio, or at least you to do the server? 

It will be very convenient for issues such as `How can I download theme for vsc`

\- thanks

**Comment by isidorn** [comment]
This is a fair request, however we already have some communities:
Slack for extension authors aka.ms/vscode-dev-community
Gitter for accessibility users https://gitter.im/Microsoft/vscode-a11y

Currently we would not like to have another channel open.
Though I suggest that we leave this open so we can receive more feedback about this in the future and then potentially add it.
fyi @digitarald since I think you mentioned discord.
