### ISSUE TITLE
Review actions that should persist their state into settings

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#13328]
- [x] zoom - setting
- [x] sidebar location - setting
- [x] status bar visibility - setting
- toggle whitespace - not a setting
- toggle wordwrap - not a setting
- toggle control charactes - not a setting

**Comment by bpasero** [comment]
I pushed:
* sidebar location (https://github.com/Microsoft/vscode/issues/13338)
* zoom (https://github.com/Microsoft/vscode/issues/13334)

**Comment by bpasero** [comment]
I am not 100% convinced we should blindly write to settings for word wrap, white space etc. because other editors seem to apply this only for the current file and not all files. If I have 2 files side by side open and I click on word wrap for the left file (because it could be a markdown file), I would NOT expect word wrap to be enabled for the other file which could be any source file where word wrap does not make sense.

**Comment by egamma** [comment]
Make sense to distinguish settings that are temporary and per buffer only. 

To me toggle status bar falls into the same category as the sidebar location.

Let's have an inventory at the top in the description.

**Comment by jrieken** [comment]
I'd like to add

* [ ] diff editor, show leading/trailing whitespace changes
* [ ] diff editor, sideBySide vs inline diff

**Comment by glen-84** [comment]
Please persist toggle whitespace, and toggle indent guides (#13385).

**Comment by Bill-Stewart** [comment]
Yes, it is very helpful to have different settings per buffer (preferably by file type).

**Comment by egamma** [comment]
Reopening to track the work on the diff editor related commands.

**Comment by bpasero** [comment]
I added test plan and release notes for zoom, status bar visibility and sidebar location.

**Comment by ramya-rao-a** [comment]
@bpasero Can this be closed or is there anything pending to be done?
