### ISSUE TITLE
Cannot test Markdown extension for web with `--extensionDevelopmentKind=web`

### ISSUE THREAD

**Issue by yhatt** [microsoft/vscode#133399]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.61.0-insider
- OS Version: macOS Big Sur 11.6 (Darwin arm64 20.6.0)

Steps to Reproduce:

1. Create a new extension based on https://github.com/microsoft/vscode-extension-samples/tree/main/helloworld-web-sample.
2. Add `"markdown.markdownItPlugins": true` to `contributes` field on `package.json`.
3. Change `activate` function of `src/web/extension.ts`, to return an object with `extendMarkdownIt` contribution point:
    
    ```js
    return {
      extendMarkdownIt(md: any) {
        return md.use(() => {
          console.log('contributed!')
        })
      },
    }
    ```
4. Launch "Run Web Extension in VS Code" from Run and Debug. (contains `--extensionDevelopmentKind=web` to args)
5. Open Markdown preview in a new VS Code instance. It should be outputted "contribtued!" to the debug console, but there are no outputs.

It works correctly in the case of a regular extension worked on Node.js, and works on github.dev if published the extension to marketplace too. So I think it may be specific to the development environment.

I've confirmed this bug while the time of creating [my extension](https://github.com/marp-team/marp-vscode), but it seems to be able to say the same thing to other Markdown extensions that are supported Web extension, such as https://github.com/mjbvz/vscode-markdown-emoji.

**Comment by mjbvz** [comment]
I believe this is because with `extensionDevelopmentKind`, the built-in markdown extension is running in the normal desktop extension host while your extension is running in the pseudo web extension host. @alexdima any suggestions on how to work around this? Can you still force a specific built-in extension to be run in the web extension host?

Markdown extensions should works properly when actually run on the web

**Comment by alexdima** [comment]
@mjbvz It is unfortunately currently not possible to support this scenario in VS Code for Desktop. VS Code for Desktop ships the markdown extension bundled and packaged for desktop. VS Code for Desktop does not ship the web variant of the markdown extension (notice how `"./dist/browser/extension.js"`, the `"browser"` entry point is missing):

![image](https://user-images.githubusercontent.com/5047891/135090751-310c90d7-94d4-4011-8e1c-afb09f324c06.png)

In order to support this, we would need to either ship for all builtin extensions the web bits as well, which would increase our distribution size for a feature which is never used by end-users of VS Code, or to be able to somehow install the markdown extension with the web bits. I don't think any of these solutions are particularly fitting or straight-forward.

@aeschli Do you have any thoughts?

**Comment by aeschli** [comment]
You'll have to test this with the [@vscode/test-web runner](https://code.visualstudio.com/api/extension-guides/web-extensions#test-your-web-extension-in-a-browser-using-vscodetestweb) where everything runs in the web ext host.

Some extensions need to run in the same extension host as an extension they depend on. Given the various ext host locations we now support, we will such issues more often. We probably have to look into some mechanisms how contributions can be done across extension hosts.

**Comment by mjbvz** [comment]
Thanks @aeschli! I'm going to close this issue since it sounds like using `test-web-runner` is the correct solution

Markdown-it plugins are the only markdown extension point where the extension host matters. It doesn't matter for custom styles or scripts
