### ISSUE TITLE
Saving new file takes a few seconds

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#133311]
1. Open a new window
2. Create a new files
3. Save it to the Desktop

🐛 File only gets saved after 2-3 seconds.

Note that I have `"files.autoSave": "afterDelay"`, might be relevant.

![recording](https://user-images.githubusercontent.com/22350/133742021-7c5450cc-d396-4efd-873e-ddf2953dbfa0.gif)

**Comment by joaomoreno** [comment]
Just found another basic feature which has a similar delay and shouldn't:

1. New window
2. File > Open File...
3. Pick a .txt file from the Desktop

🐛 Same delay happens before the trust dialog pops up

![recording (1)](https://user-images.githubusercontent.com/22350/133742747-360a5c3e-cb4d-4343-a9c2-9e50bf8e76b9.gif)

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by joaomoreno** [comment]
It does seem extension related! Will bisect and update.

**Comment by bpasero** [comment]
And?

**Comment by joaomoreno** [comment]
Can't repro today. 😢
