### ISSUE TITLE
Syntax highlighting broken in hover widget

### ISSUE THREAD

**Issue by Wosi** [Microsoft/vscode#13339]
Syntax highlighting inside the hover widget seems to work differently compared to the highlighting inside the code editor.

Here's an example of how a Pascal function is shown in the editor with the OmniPascal plugin installed:

![correct](https://cloud.githubusercontent.com/assets/3448684/19184429/62d79e3a-8c7d-11e6-968c-81c8078ae782.png)

The hover widget displays the same code with different colors:

In version 1.5.3:
![wrong_stable](https://cloud.githubusercontent.com/assets/3448684/19184469/95abb13e-8c7d-11e6-8458-db53edb926ea.png)

In version 1.6.0-insiders:
![wrong_insiders](https://cloud.githubusercontent.com/assets/3448684/19184482/a23c40e4-8c7d-11e6-97c6-693636c91343.png)

As you can see there are different colors used in the parameter list. That's just one of many examples where highlighting is inconsistent.

I'm the developer of OmniPascal, so I'd like to know whether this is can be a bug within my plugin or not? Or is it a bug in VSCode? When it's my fault: Do you have any ideas what might be wrong?

**Comment by Tyriar** [comment]
It might be pointing to a different grammar?

**Comment by aeschli** [comment]
Code blocks in hovers (e.g. { value: 'function RunScript()', language: 'pascal' }) use the TextMate grammar for the given language. The result depends on the grammar and the selected color theme.
We are aware that this is slightly hackish as not every code block represents a valid program code.

**Comment by jrieken** [comment]
As @aeschli said - we render the code snippet using the language the extension announced using the [`MarkedString`](https://github.com/Microsoft/vscode/blob/joh/fmtprio/src/vs/vscode.d.ts#L1632). Usually they pick *their* language enough it's just a snippet and the grammar is somewhat contextual. There are a few ways to fix this but both a up to the extension

* instead of an incomplete snippet return proper code that renders correctly
* make the grammar less contextual
* contribute a special snippet grammar that renders properly

On the VS Code it will be always the same as that we render a piece of code using a given grammar. Not much we can do about.
