### ISSUE TITLE
VS Code connects to education.github.com despite Telemetry being disabled

### ISSUE THREAD

**Issue by zulaica** [microsoft/vscode#133493]
Does this issue occur when all extensions are disabled?: Yes/No

Yes

Version: 1.60.1
OS: macOS 11.6

Steps to Reproduce:

1. Disable telemetry:
```settings.json
"telemetry.enableCrashReporter": false,
"telemetry.enableTelemetry": false,
```
2. Disable experiments:
```
"workbench.enableExperiments": false,
```
3. Restart VS Code

Despite the setting being disabled, the application connects to `education.github.com` (which itself begs more questions, but that's a whole other thing). This is (presumably) [the offending code](https://github.com/microsoft/vscode/blob/main/extensions/github-authentication/src/githubServer.ts#L293-L328) which doesn't appear to check whether the appropriate settings are enabled.

**Comment by lramos15** [comment]
Thanks for the report. I will definitely look into fixing this as we don't need to make this request, but to ease some concerns the telemetry doesn't get sent to Microsoft. We initiate the connection to `education.github.com` to see if you're a student or faculty using VS Code so we can better gauge how to make VS Code accessible to those in a classroom setting. However, the `this._telemetryReporter.sendTelemetryEvent` no-ops because it goes to check your telemetry setting and realizes it is disabled. You can find that NPM module here https://github.com/microsoft/vscode-extension-telemetry

**Comment by TylerLeonhardt** [comment]
Thanks for this @lramos15 !
