### ISSUE TITLE
accessibility: the labels for the top-level tree nodes in find references all just read "true"

### ISSUE THREAD

**Issue by ahicks92** [microsoft/vscode#133567]
Does this issue occur when all extensions are disabled?: No, because if you do that you can't find references.

- VS Code Version: 1.60.1
- OS Version: Windows 10

Steps to Reproduce:

With NVDA 2021.1, use alt+shift+f12 to find references.  It'll read the references fine, but all the top-level labels are "true".  I'm pretty sure these are supposed to be filenames or something like that instead.

I didn't bisect extensions but it's happening on two different machines against both rust-analyzer and C/C++.  I can bisect extensions if we need me to as well, but pretty sure this one will be easy to duplicate once in front of the right people.

**Comment by jrieken** [comment]
I believe this is a general issue with custom trees because the references view doesn't define any accessibility information. In this case it's [a resource URI](https://github.com/microsoft/vscode-references-view/blob/dcf0d7c94598eb7b28ce482ec11e955684d99a99/src/references/model.ts#L269) which might become "true" along the way

**Comment by alexr00** [comment]
Yes, this is a bug with custom tree + resource URI. Thanks for reporting this @ahicks92!

**Comment by ahicks92** [comment]
Yep, looks good.  Thanks.
