### ISSUE TITLE
Popular extensions based on web usage

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode#133570]
Currently, the popular extensions list in github.dev only shows extensions that work in the web (which is good). However, we'd like to take it a step further and show popular extensions based on web usage, rather than VS Code in general.

**Comment by isidorn** [comment]
This is a fair request, but I think a tough one as it needs changes from the Marketplace side.
The current `popular` list is just extensions sorted by their download count.
So for `github.dev` popular you would want a list sorted by download count from `github.dev`. 
The problem is that the Marketplace does not distinguish if a download is coming from `github.dev` or VS Code client or if the extension got downloaded from the MP site. 
The proper solution would be if the MP would add a new field to the extension which would reflect its download count from `github.dev`.
