### ISSUE TITLE
Git .NET error

### ISSUE THREAD

**Issue by codewithpom** [microsoft/vscode#133675]
# Git  .NET error
Respectful Reader
I am Padmashree, and the feature I want to request is that when I use a JetBrains IDE to push a git repository I do not get the .NET version error but while doing it by vs-code I face this issue. Kindly check this issue.
Thank you for reading till end
Padmashree :slightly_smiling_face:

**Comment by IllusionMH** [comment]
/needsMoreInfo

Provide more info about versions, OS and especially what error is it.

**Comment by codewithpom** [comment]
@IllusionMH ok sir
# OS
Windows 7 professional 64 bit

# VS code
VS code user version 1.60.2

# Git
Git version 2.32.0.windows.2

**Comment by IllusionMH** [comment]
You've omitted most important part - what error do you see when you perform the action?

**Comment by codewithpom** [comment]
oh sorry

**Comment by codewithpom** [comment]
![image](https://user-images.githubusercontent.com/79435304/134642908-65ee2f83-711e-47b1-bff5-074c3418873b.png)

**Comment by Lemmingh** [comment]
The error comes from [GCM](https://github.com/microsoft/Git-Credential-Manager-Core), which is bundled with and used by **Git for Windows** for authentication by default.

The problem is irrelevant to VS Code. It's likely that your .NET runtime version is too low, since GCM on Windows requires .NET Framework 4.7.2 or higher. <https://github.com/microsoft/Git-Credential-Manager-Core/pull/283>

Installing the latest [.NET Framework](https://dotnet.microsoft.com/download/dotnet-framework) and [.NET Runtime](https://dotnet.microsoft.com/download) should solve your problem.

**Comment by codewithpom** [comment]
Ok sir but when I push a repo by a JetBrains product like Pycharm I do not
see this error.

**Comment by Lemmingh** [comment]
If I recall correctly, JetBrains products have their own credential manager which may override the default one (GCM Core).

VS Code's built-in Git integration simply calls the Git client. "Push" in VS Code should be equal to invoking `git push` in a terminal.

---

To inspect configured credential manager:

```shell
git config --show-origin --show-scope --get-all credential.helper
```

Since [**Git for Windows**](https://github.com/git-for-windows/git) 2.29, the output should contain a line that looks like:

```log
system  file:C:/Program Files/Git/etc/gitconfig manager-core
```

This should be the only one, if you didn't change the config.

**Comment by codewithpom** [comment]
oh that is why I see the error Thank you for your time and implement it if you have time and if you can Thank you.
**With Regards and Thanks*
Padmashree
