### ISSUE TITLE
Can't run two RBL sessions in two editors

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#133646]
- Start a RBL session in one jupyter notebook
- Open a second notebook, start a RBL session
- Click the RBL button again to step once in the second editor
- The yellow highlight doesn't show up

We update decorations on a stackframe focus change, and `onDidChangeCallStack`
https://github.com/microsoft/vscode/blob/c2119a4740b6a2a20da18c774016180383c53d36/src/vs/workbench/contrib/debug/browser/callStackEditorContribution.ts#L115-L115

`onDidChangeCallStack` is only fired when the bottom of the callstack changes. @isidorn this is something I've been meaning to ask about, I don't totally understand the idea behind that event. Is there no way to listen to a change in the top frame? There are two cases where I want to do that:

- Here, a session with `isSimpleUI` will never be focused in the callstack view (if it is not the only session), but I always want to render its current line decoration
- And also where I try to hide the cell timer when a cell is being run and debugged. I was able to work around it but would rather just be notified immediately when a step happens in a cell.

**Comment by isidorn** [comment]
@roblourens `onDidChangeCallStack` should fire any time the call stack changes. So if we are fetching the call stack by first fetching the top `stackFrame` and then the rest this event will fire first time when the top `stackFrame` is returned and optionally the second time when the rest of the call stack returns. I say optionally because if the bottom of the callStack is the same as it was previously we will not fire the second event (as an optimisation).

Though I do not like optimisations on the model level in general (I prefer to put them on the UI level), so I think it should be fine to simplify this that this always fires twice, once when the top frame returns, and another time once the full stack frame is there.

If the event is not fired as I explained above then this is a bug. Looking at the code I am not sure why this [fire](https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/debug/common/debugModel.ts#L1128) is not inside the `then`. So I would just double check the exact timing of event fires.

If you want, you can add a property to that event `topChanged: boolean` and then the listeners of that event would know if the top of the `stackFrame` changed or not.

**Comment by roblourens** [comment]
> Looking at the code I am not sure why this fire is not inside the then

Ok, yeah that is exactly what has been confusing me. If I move it to fire after the first frame is fetched, I think that makes sense.

**Comment by isidorn** [comment]
@roblourens correct.
However changes like this I usually prefer to do in debt week to have the full milestone to self host on it. Though I think we still have the full endgame ahead of us, so feel free to change right now.

**Comment by roblourens** [comment]
Fixed by https://github.com/microsoft/vscode/commit/3d102bbf3ea771aa172620c7623e89b1a795b708, checked all the event listeners and tested a little, seems fine
