### ISSUE TITLE
Add an option to turn brackets matching on or off

### ISSUE THREAD

**Issue by fantaclaus** [Microsoft/vscode#13379]
- VSCode Version: Code 1.5.3 (5be4091987a98e3870d89d630eb87be6d9bafd27, 2016-09-22T08:50:42.185Z)
- OS Version: Windows_NT ia32 6.1.7601

I would like to have an option in preferences file to turn bracket matching on or off.

Sometimes, when typing it is hard to detect where the caret is. For example:

![image](https://cloud.githubusercontent.com/assets/7231941/19213322/f08dedac-8d71-11e6-8d55-8626ce23ff06.png)

In this case it is better to hide bracket markers altogether.

When I need to locate a matching brace I could use key-bound command "Go to bracket".

**Comment by jsumners** [comment]
I'd really like to see theme support for brackets matching so that:

1. the very annoying boxes can be turned off
2. matching brackets can be highlighted by color (foreground, background, or both)

**Comment by bpasero** [comment]
You can set `"editor.matchBrackets": false`

**Comment by jsumners** [comment]
@bpasero turning off bracket matching is _not_ the same thing. I don't appreciate the issue being closed without actually being addressed. I want bracket matching; I just want it with color instead of this legibility killing outline.

**Comment by bpasero** [comment]
@jsumners please follow our [bug guidelines](https://github.com/Microsoft/vscode/blob/master/CONTRIBUTING.md#writing-good-bug-reports-and-feature-requests) when reporting issues, we do not want different issues in one issue exactly for this reason. I closed this item because the things described by @fantaclaus were solved. 

As for theming of bracket matching, you can set the following setting to tune the experience:

```json
"workbench.colorCustomizations": {
	"editorBracketMatch.background": "",
	"editorBracketMatch.border": ""
}
```

This is only available yet in our insiders build. You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by MagnusOxlund** [comment]
@bpasero is that setting scheduled for the next release?
