### ISSUE TITLE
Relative paths and paths without columns not linked in debug console

### ISSUE THREAD

**Issue by felixfbecker** [Microsoft/vscode#13370]
- VSCode Version: 1.5, 1.6 insider
- OS Version: Windows 10

![image](https://cloud.githubusercontent.com/assets/10532611/19205758/ad480cea-8ce4-11e6-9bc9-e896cb73b94e.png)

Paths from the stack trace are not clickable

**Comment by felixfbecker** [comment]
Btw this also affects relative paths:

![image](https://cloud.githubusercontent.com/assets/10532611/20076546/1975b126-a539-11e6-8f89-6a0a9260bb7d.png)

I would consider this more of a bug than a feature request, as it works correctly on the other OS. This is really slowing down productivity, please please consider this for the next iteration. I imagine it is just a wrong regexp somewhere.

**Comment by isidorn** [comment]
Here is a [code pointer](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/replViewer.ts#L101)
PRs that fix this are welcome. If it turns out to be too complex I can look into fixing this in the future

**Comment by felixfbecker** [comment]
Thanks @isidorn I will take a look at this! Are there tests for this?

**Comment by isidorn** [comment]
@felixfbecker no but adding tests would be even more super awesome. 
It should be possible to create a ReplExpressionsRenderer with a MockEditorService and test out the link detection. If this seems unintersting I can look into adding tests in one of our debt weeks.

**Comment by isidorn** [comment]
Also a bit related https://github.com/Microsoft/vscode/issues/6301

**Comment by felixfbecker** [comment]
Fixed the regexp so that
 - relative paths are matched (the "root" path is optional now)
 - paths without a column are matched ("column" path is optional now, as PHP only reports line numbers)
 - no line breaks are allowed inside the path (otherwise change 2 would cause unintended matches)

![image](https://cloud.githubusercontent.com/assets/10532611/20099192/9630e216-a5b7-11e6-9776-4717933534d3.png)

**Comment by felixfbecker** [comment]
I also noticed only group 1, 3 and 4 are used. Can I remove capturing of group 2 (root component)?

**Comment by isidorn** [comment]
@felixfbecker I believe that group is there for a reason. Though @bpasero originally added it
Since you are now being less strict about link detection try to verify if you introduced false positives.
Once your change is in a good shape just create a PR and ping me on it

**Comment by felixfbecker** [comment]
Well I checked this with Find all references and the regexp is only used in a single place, where only the capture groups I mentioned are used. But I'm gonna leave it out for now.

**Comment by bpasero** [comment]
These regexes are literally taken from our Azure version I think and super old. Feel free to revisit them, but make sure to see the test cases and update them as well 👍

**Comment by roblourens** [comment]
This is now not working in Insiders on MacOS, maybe from this change?

Stable, links underlined and clickable:
![image](https://cloud.githubusercontent.com/assets/323878/21058394/9b07e35e-bdf2-11e6-8698-e7cb500ccee2.png)

Insiders, highlighted in the error message but not the stack trace, and that one link tries to open as a path relative to the workspace, then shows an error message because it can't find the file:
![image](https://cloud.githubusercontent.com/assets/323878/21058428/c238bda4-bdf2-11e6-8844-270b8e7f64c7.png)

**Comment by roblourens** [comment]
Actually I see the same thing in Windows. I think it's just highlighting the first link it finds instead of all of them. On Windows the link is still clickable though.

**Comment by aeschli** [comment]
Also no success for me. Shouldn't this work? No links for me (Windows 10)
```
console.error('C:\\Users\\aeschli\\workspaces\\samples\\main.js:1');
console.error('C:/Users/aeschli/workspaces/samples/main.js:1');
process.exit();
```

![image](https://cloud.githubusercontent.com/assets/6461412/21059305/125dce56-be42-11e6-8826-7192505217e4.png)

**Comment by roblourens** [comment]
It seems like it's only supposed to work with paths in parens and with `:#:#` like you'd find in a stack trace

**Comment by felixfbecker** [comment]
Yes, or line start / line end should work too. I have no idea though why only the first link is highlighted and don't have time currently to investigate

**Comment by roblourens** [comment]
Investigated, and there are sort of two problems:
- Clicking on an underlined link doesn't work in MacOS
  - https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/replViewer.ts#L384
  - The link detection regex isn't capturing the leading '/', so that line sends it to `toResource` which concatenates it to the workspace root. I'm not sure what's wrong with the regex.
- Only the first link in a log message is shown
  - I can't figure out where this came in, but I know it was introduced somewhere between
  - 62ed382fad3b22dad2738d9d85f3b29bb969d4e9 (merging #15464)
  - and d2a4e2eace586dfacf8c13347e110904bcfb31cf (binary searching is getting too time-consuming)
  - But somewhere, we started parsing an entire message at a time for a link, instead of just one line at a time

**Comment by isidorn** [comment]
Thanks @roblourens for a great investigation. The first issue is introduced by the last PR. The second issue is introduced by a refactoring on my end where we try to handle new lines in the debug console better.

I have pushed a safest fix that takes care of those two problems - reverted only the last PR and disabled the grouping together of the output. This should now bring us to the same behavior of the last stable release (with potentialy some improvements by the first two PRs).

Our link handling has many flaws and I plan to tackle this in the January release.

**Comment by isidorn** [comment]
After testing this out it seems we have regressed a bit. Namely when there is one large output event we only detect the first link. This is practice means when a stack trace is printed that only the top stack trace element can be clicked.
If there are mutliple stack traces printed to the console then the first link in each stack trace will be detected.

I am not sure how big of a regression this is. This was working before becuase we were actually not handling the output events properly and we were separting them in new lines wrongly.

@weinand can decide if it is ok to ship with this limitation. If it is not ok to ship with this then I propose we go back to the old spliting each output per line.
In any case I plan to revisit how we do this whole link detection in January

**Comment by felixfbecker** [comment]
Why not split it at the time the regexp is applied?

**Comment by isidorn** [comment]
@felixfbecker yeah that is also an option. But when there are multiple links detected on one element than the formating / newlines get screwed up. So there would some additional changes required which are never smart to do in last minue fixes such as this one :)

**Comment by isidorn** [comment]
@felixfbecker unforuntetly had to revert all your prs because we decided to go back to the behavior we had in vscode stable.

Since we have polluted the history of this bug I have created a new one and assigned it to January so we can properly fix this in the next release. Here is the issue https://github.com/Microsoft/vscode/issues/17085

**Comment by isidorn** [comment]
For verification:

Verify vscode insiders is handling links in the repl the same way vscode stable is doing right now

**Comment by roblourens** [comment]
Thanks, looks good to me on MacOS in master (needs verification in a real build)
