### ISSUE TITLE
Saving notebook files with Ctrl+S in a Codespace is unresponsive or doesn't work

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode#133898]
Repro Steps:
1. Open a notebook file in a new codespace.
2. Make an edit to the notebook file.
3. Try and save the notebook file using the shorthand (Ctrl + S)

The following was shown after many attempts of saving:
![image](https://user-images.githubusercontent.com/6413608/134596523-00e08eed-079f-499a-ac19-acd269f064c4.png)

![image](https://user-images.githubusercontent.com/6413608/134596533-7dfa9329-9978-4bbf-a396-d7cceb0b41f1.png)

It could be an intermittent connection issue with the Codespace.

**Comment by rchiodo** [comment]
Saving isn't handled by the jupyter extension, but by VS code itself

**Comment by alexdima** [comment]
The file cannot be saved due to a Canceled error. The Canceled error is thrown when the connection to the remote server is lost. So in this case, the root problem is the fact that you became disconnected. There are multiple reasons why you would become disconnected: wifi lost, a tab was left open for a very long time, etc. 

Do you encounter often that you get disconnected? Do you have some repro steps?

**Comment by SiddhanthUnnithan** [comment]
This was a brand new Codespace I'd created. I waited for the initial environment setup to complete before opening the notebook file and attempting an edit. My tab wasn't open for very long and I wasn't aware that I was in a disconnected state (no feedback) when I tried to save the file.

**Comment by alexdima** [comment]
> My tab wasn't open for very long and I wasn't aware that I was in a disconnected state (no feedback) when I tried to save the file.

Disconnection can take up to 40-50s to be detected. We send pings every few seconds from the client to the server and if 20s elapse without a server message we begin reconnecting. We have received feedback that for many people prompting after 20s with a blocking dialog is too son (e.g. people using 4G in a train). So we have decided that when we first realize we have lost connectivity (20s elapse without a server message), we will reconnect silently. Only a small status bar message will say "Reconnecting...". If a further 20-30s elapse without being able to reconnect, then we show the blocking dialog. If reconnection succeeds, we don't interrupt the user further. So it is by design that it is possible to save a file (press ctrl+s) when being disconnected, but before the blocking dialog appears. 

But in your case, it was even worse: reconnection did not work at all and you got prompted to Reload the window. This might indicate that the codespace went down, or the server process went down inside the codespace. Are you able to reproduce this?
