### ISSUE TITLE
Allow to right click on File to Open in New VSCode Window

### ISSUE THREAD

**Issue by name2name2** [Microsoft/vscode#13380]
- VSCode Version: 1.5.3
- OS Version: win 10

It's a feature request :

I hope when right click on the file tab, the context menu will contains the function "**Open this file to a new vscode window**",

so I can do it easily which I orginally have to
 **click File > New Window > and drag one of the two files from the previous window to the new opened window** 

to let two files show in two different window separately when using two screen. 
## 

Img below just shows right click on file tab:
## 

![image](https://cloud.githubusercontent.com/assets/10517310/19213917/470c297c-8daa-11e6-87d7-f36e06bbc7a0.png)

**Comment by crstnbr** [comment]
Would love to see this, too. Any plans to realize this?

**Comment by Speins** [comment]
If you drag a tab outside of the window it should also open in a new window.

**Comment by imyellow** [comment]
@richtems not work, it will copy the file to desktop

**Comment by ambroselittle** [comment]
My specific use case, for what it's worth. As a user who...

- Is working on a "smallish" screen (13", but I think it applies to any laptop-sized screen).
- Has multiple files open and split tabs (horizontally). 

Wants to view the diff on a file in the git changes list in a new/popover window so that he/she can leverage the full screen width for the diff.

In these conditions, the diff is virtually unusable as it wants to show in an already-split horizontal area (split 3 ways due to the two tabs plus side panel). 

It'd be cool(est) to have like a shortcut and/or right-click "View Full Screen" that'd temporarily open the selected file in a full screen modal. BUT, I'd happily settle for a simple "Open in New Window."

Come to think of it, if Zen Mode would just open current file full screen rather than the whole editor port, that'd work--maybe there's just another Zen mode option for this, like CMD+K CMD+Z or sth. I'd find that generally useful--sometimes you don't want to lose your place amongst your tabs but just want to focus on one..

**Comment by bpasero** [comment]
We have this in the command palette and it also comes with a keybinding:

![image](https://user-images.githubusercontent.com/900690/31230494-8088c906-a9e4-11e7-8396-1603e2577c98.png)

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
