### ISSUE TITLE
Notebook diffs not showing when triggered from GHPR extension

### ISSUE THREAD

**Issue by dynamicwebpaige** [microsoft/vscode#133892]
When viewing changes I make to a `.ipynb` file while using github.dev, the diffs render as expected (nicely, with red and green highlighting to indicate changes in code or state):

![Screen Shot 2021-09-25 at 8 48 16 AM](https://user-images.githubusercontent.com/3712347/134777599-f0b5b561-6554-457d-ad11-c8de83e5bc86.png)

When reviewing changes that other users have made to `.ipynb` files, the pull requests still render as JSON blobs:

![Screen Shot 2021-09-25 at 8 47 55 AM](https://user-images.githubusercontent.com/3712347/134777592-eec4a21b-5cd2-4cae-8e07-e074930f97e8.png)

**Browser**: Microsoft Edge Version 94.0.992.31 (Official build) (x86_64)
**OS**: MacOS Big Sur v11.6
**Repro link**: https://github.dev/ageron/handson-ml2/pull/408

**Comment by roblourens** [comment]
This is about opening notebooks through the GHPR extension vs SCM view. 

@lramos15 how is that route different, how do we get it to open in the notebook editor?

**Comment by lramos15** [comment]
I assume they're both using the `vscode.diff` command?

**Comment by roblourens** [comment]
Yeah. Main difference at `openEditor` is that the GHPR case has an editor with scheme `pr:`, we should still be picking the notebook editor and opening it there in the same way.

**Comment by lramos15** [comment]
Yeah file scheme shouldn't matter. I'll investigate this as I assume it's a resolver issue. We match on the extension using a glob. Will reassign to notebook folks if it turns out to be a notebook problem.

**Comment by bpasero** [comment]
This is the culprit:

https://github.com/microsoft/vscode/blob/bfc47075381995d15a31bb93e69a4f50c9557756/src/vs/workbench/contrib/notebook/browser/notebookServiceImpl.ts#L164

If you check for `canHandleResource` you might wrongly assume it cannot be handled because the file system provider extension has not been activated yet. I suggest that the editor resolver calls `fileService.activateProvider` when in a `Promise` context.

**Comment by lramos15** [comment]
Now I feel like we're moving in circles 😅 .

`canHandleResource` was added because we wanted to make sure editors were only called for schemes which they could support. The original bug was filed because notebooks couldn't support the PR scheme?

See
https://github.com/microsoft/vscode/issues/122627

**Comment by bpasero** [comment]
Its OK to use that method but you need to call the other one too.

**Comment by lramos15** [comment]
@bpasero Can I activate all providers similar to how we wait for extensions to register before proceeding with the lookup

**Comment by bpasero** [comment]
@lramos15 I do not think there is a way to activate all extensions file system providers. File system provider registration is dynamic (from code) and not declarative. 

Awaiting the activation for a particular scheme and then proceeding should be good enough in this case.

//cc @jrieken

**Comment by lramos15** [comment]
@bpasero I added the activation of the provider. Was this just being done deeper in the stack before?

@jrieken Do you know if we still need `canSupportResource`. It due to the fact that notebook diffs checked against the filesystem prior to create an input that we had this issue. I'm not sure if that's still something we need and what cases we would run into trying to open a file not supported by the file service. Wouldn't that then be an issue which plagues everyone?

**Comment by bpasero** [comment]
@lramos15 we only activate providers when you call activate (and it returns a `Promise` so you need to `await`) or when the file service is used. So yeah, it was happening as part of loading the file contents.

**Comment by IanMatthewHuff** [comment]
@lramos15  Hmm, I'm still seeing this:
![image](https://user-images.githubusercontent.com/812783/135682712-6e1c287e-e544-42d2-994e-189ec5670aaa.png)
I'm in insiders version of github.dev.

**Comment by TylerLeonhardt** [comment]
reopening and adding label based on what @IanMatthewHuff said

**Comment by jrieken** [comment]
A `TextDocumentContentProvider` is not sufficient when opening/comparing notebooks is desired (https://github.com/microsoft/vscode/issues/133892#issuecomment-951238545). This leaves the question if notebook-lands handle this properly. I assume it does because there is no failed attempt in opening a notebook editor but text-diff is shown. Also [`canSupportResource`](https://github.com/microsoft/vscode/blob/12d38b20b17dfdeae974701da39664a04f04bc16/src/vs/workbench/contrib/notebook/browser/notebookServiceImpl.ts#L165) looks like it is doing the right thing. 

Still, the observed experience isn't good (just like it isn't good for image editors and other non-text editors) and we should drag @alexr00 into this discussion so see if GHPR can replace its text document content provider with a fs implementation.

**Comment by rebornix** [comment]
When we started the GHPRI extension we don't seem to have stable fs api yet so we went with text document provider. @alexr00 let me know if you this makes sense to you.

**Comment by alexr00** [comment]
@rebornix makes sense, thank you.

**Comment by rebornix** [comment]
@alexr00 just sent a PR https://github.com/microsoft/vscode-pull-request-github/pull/3091;)
