### ISSUE TITLE
Codespaces: better handle invalid workspaces when opening

### ISSUE THREAD

**Issue by GideonCheruiyot** [microsoft/vscode#133872]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Insiders
- OS Version: Mac OS
- 
**Repro Steps:**
1. Create a codespace
2. Open a subdirectory using `File -> Open...`, which will cause future connections to connect to that folder by default
3. Delete/rename the subdirectory so that it doesn't exist anymore
4. Disconnect and try to reconnect to the codespace
  
**Expected:**
 The connection succeeds, ideally to the repo root as the fallback, or instead by recreating the missing folder and connecting to the empty folder.
 
**Actual:**
 Connection fails

![DeletedFolder](https://user-images.githubusercontent.com/36052056/134942238-2fa4a132-f563-4371-9e4a-b3e368e58df6.png)

Issue reported to codespaces: https://github.com/microsoft/vssaas-planning/issues/5354

**Comment by GideonCheruiyot** [comment]
In the local case, if the directory is deleted, vscode redirects the user to an empty window because there we can check if the workspace exists before attempting to open it. However, in codespaces, if a folder is deleted, the codespace automatically goes into a bad state. On reload, the vscode workbench throws an error since the workbench cannot be mounted. For the remote, Is it possible to resolve to the root folder  _~/_ if the workspace is deleted? cc. @bpasero

**Comment by bpasero** [comment]
I really like the idea of going back into the "root" of the Codespace when the workspace does not exist. Opening an empty window probably does not make a lot of sense when you are in a Codespace.

**Comment by bpasero** [comment]
@GideonCheruiyot thinking more about it, I wonder if we should change the behaviour of Codespaces. You say:

> Open a subdirectory using File -> Open..., which will cause future connections to connect to that folder by default

I wonder why we decided to do so. I think it would be better if the default URL (e.g. https://bpasero-test-ts-r76wjw9fwppx.github.dev/) would always end up opening the repository root and not the previous folder I had opened. If my intent is to open a specific folder, wouldn't it make more sense to bookmark the URL that has the folder included and open that directly?

**Comment by bpasero** [comment]
Another thought: Codespaces is the one asking to construct the workbench through API with a workspace such as this one:

![image](https://user-images.githubusercontent.com/900690/135035356-fb7df122-5f0c-45d5-ae3b-b0949a1c2233.png)

If you had a way to figure out beforehand if the folder actually exists in the repository, you could redirect to the root otherwise. 

For VSCode to figure this out we cannot do much until the resolver is there and that would result in flicker because the workbench would first happily load assuming the folder is there. And even if we then were to redirect, this needs some new embedder API to know the "default" workspace.

All in al, a much nicer solution would be if the embedder could drive this before even creating the workbench...

**Comment by jkeech** [comment]
For performance, we don't want to put an additional blocking RPC call in front of every workbench initialization. My initial thought was to optimistically load the requested folder, and if it doesn't exist (or we don't have permission to read it, etc), then VS Code could throw an error that the resolver can catch and then perform an RPC call in the error handler to find the best alternative location. At that point, we would reload the window with the new folder path. This would result in a one-time flicker, but the new folder is then saved at the front of the MRU list and so it wouldn't happen on subsequent loads any more.

Another approach would be for VS Code to internally handle the fallback, and it could even be a generic heuristic without an embedder API like "walk up the directory tree to the nearest reachable/valid folder". This approach would also only result in a flicker the first time after an error occurred since the same MRU update would apply in this case after the Codespaces extension activates and updates the MRU list.

**Comment by jkeech** [comment]
We also need a solution for the desktop resolver case as well, and in the desktop case, the folder to open is passed into VS Code prior to the connection being established to the remote side so we cannot verify existence in advance.

**Comment by bpasero** [comment]
@jkeech well, VSCode has the same interest actually to not block the startup. I remember we used to have code in the workbench itself that would validate whether the workspace to open exists or not, but we removed that code a while ago.

@sandy081 I believe you are the first to get asked to resolve the workspace to figure out the configuration. Is that also true in the remote case or are we delaying that resolution until a later point (resolved workspace vs. unresolved workspace - was never really clear to me...)

Maybe that workspace resolution could somehow signal back that the workspace could not be resolved and then we trigger a flow to open an empty instance instead. I feel that arbitrary walking up parent folders is a bit weird. An empty instance would indicate much better that the folder could not be opened and it matches our behaviour when a local folder does not exist.

**Comment by sandy081** [comment]
@bpasero Please check this comment for resolving a workspace

https://github.com/microsoft/vscode/blob/a0a448f344bc8c068deb1202708dfc1e7c17ef89/src/vs/workbench/services/configuration/browser/configurationService.ts#L382-L395

In case of remote, I do not wait for resolving workspace configuration. In order to provide seamless behavior I cache it.

**Comment by bpasero** [comment]
@sandy081 yeah this is a normal folder that simply does not exist. This likely results in some exception in your code when resolving the folder, at least for the configuration I would assume?

**Comment by sandy081** [comment]
@bpasero Yes, I validate the folder and silently ignore and let the explorer handle it. See below 

https://github.com/microsoft/vscode/blob/a0a448f344bc8c068deb1202708dfc1e7c17ef89/src/vs/workbench/services/configuration/browser/configurationService.ts#L836-L852

**Comment by bpasero** [comment]
@sandy081 it would be somewhat helpful if that status could be transported all the way up to here:

https://github.com/microsoft/vscode/blob/31152fd902cf50ea37c2667ed4c6d57000c771d0/src/vs/workbench/electron-sandbox/shared.desktop.main.ts#L318

and (for web):

https://github.com/microsoft/vscode/blob/41a3633034726b79fcaec11a37a9cb9b16c8796e/src/vs/workbench/browser/web.main.ts#L362

If there I had a way to know that the workspace is actually invalid (folder cannot be resolved or workspace config file cannot be resolved), I could implement different handling. 

Do you ever recover from that? I am wondering if there could be the case of a workspace folder failing to resolve once but then being healthy later (remote file systems). Asking, because it could also be frustrating to automatically load the user into a different workspace upon the first error that happens.

@jkeech unsure how it would work in desktop where we have no embedder API. In that case we either need to move user into empty workspace or walk up the folders.

**Comment by sandy081** [comment]
yeah I can roll up the status, but not sure if want to do anything while start up itself. Hence I leave it up to the explorer so that it can decide the best that can be done given that we have complete workbench started and all services available then.

**Comment by bpasero** [comment]
@sandy081 just some status is fine, no need to block anything. I can take it from there then and maybe show a dialog to the user how to proceed.

**Comment by sandy081** [comment]
> yeah I can roll up the status, but not sure if want to do anything while start up itself

@bpasero I take back this and I do not think following call can return the status

https://github.com/microsoft/vscode/blob/31152fd902cf50ea37c2667ed4c6d57000c771d0/src/vs/workbench/electron-sandbox/shared.desktop.main.ts#L318

because, `initialize` will not wait always for the workspace folders to be resolved especially when these folders are remote. Otherwise this will cause deadlock. 

If you would like to validate, I would recommend to resolve the workspace folders outside and take appropriate action.

**Comment by bpasero** [comment]
@jkeech @GideonCheruiyot this makes it unfortunately a bit harder for us to resolve this on startup. I do not like the idea of blocking the startup to resolve the presence of the workspace folder because that will make the overall startup slower.

We could in theory try to resolve the folder in the background (like the explorer does) and then inform the user about the workspace being somewhat invalid, but then what should happen?

A couple of ideas and thoughts:
* automatically changing the workspace will result in ugly flicker and might be unexpected to the user
* showing a modal dialog could be helpful to inform the user in a nice way and offering options to change the workspace or stay in the workspace
* the explorer could indicate more pleasantly that the workspace is invalid and maybe offer actions similar to the dialog

Again: how much sense does it make that a user is entering the previously entered folder when opening the direct codespace URL? should that change rather?

**Comment by jkeech** [comment]
> Again: how much sense does it make that a user is entering the previously entered folder when opening the direct codespace URL? should that change rather?

Just to clarify: the feature where Codespaces remembers the last folder is not the only way this can happen. We've seen reports from users where they've deleted/renamed the repo directory as well, so always opening that one can have a similar problem. The product team does not want to change the behavior of Codespaces remembering the last folder/workspace you used either, since most people want to pick up right where they left off.

>* showing a modal dialog could be helpful to inform the user in a nice way and offering options to change the workspace or stay in the workspace
> * the explorer could indicate more pleasantly that the workspace is invalid and maybe offer actions similar to the dialog

I really like this idea. Could you open the folder picker from `File: Open..` with a message to the user saying that the requested folder/workspace doesn't exist and ask them to pick from one of the places that does exist? It seems like this solution would work for both web and desktop as well.

If we did this, we can always start the VS Code server and complete the connection from the resolver side, and then internally VS Code can guide the user down the path of picking a good folder if the requested one is invalid. Once the user picks, the window would likely reload into that folder.

**Comment by bpasero** [comment]
@jkeech @GideonCheruiyot can I get some UI thoughts on this flow:

**Desktop**
![remote-desktop-recording](https://user-images.githubusercontent.com/900690/136151546-3e695f07-6674-46d2-b706-218f93bf9c68.gif)




**Web**
![remote-web-recording](https://user-images.githubusercontent.com/900690/136151554-0050c45f-aca2-4a30-af29-3690052624ae.gif)

**Comment by GideonCheruiyot** [comment]
LGTM. cc. @2percentsilk

**Comment by 2percentsilk** [comment]
LGTM! A big improvement :)

**Comment by GideonCheruiyot** [comment]
@bpasero , when would this be shipped? Tried testing on the latest Insiders with no luck.

**Comment by bpasero** [comment]
It shipped to insiders, I just verified it on web and it seems to work. It should work equally well on desktop.

**Comment by GideonCheruiyot** [comment]
Looks like I missed this [fix](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/Cascade/pullrequest/354493) to recreate a deleted workspace folder which is why I couldn't repro by deleting the workspace folder. Verified the fix in both Web and Desktop by trying to delete and connect to non-workspace folders. Thanks! @bpasero.
