### ISSUE TITLE
Terminal revive setting feedback

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#133969]
Testing #133516

I find our setting description and name a bit confusing. Here is macOS for example:

![image](https://user-images.githubusercontent.com/900690/135057786-7e6d8eea-9b6d-4df5-b6cc-08aa97c37fe6.png)

Some obersvations:
* there is a setting to configure whether a marker should be printed 👍 
* the setting does not talk about "persistent session" but "restore text" which I like because that is my understanding of the feature
* our setting talks about "processes being recreated" but my understanding is that we only restore the lines and not the running processes

**Comment by Tyriar** [comment]
"Persistent sessions" was the existing feature that enabled "process reconnection", the intent in putting it under the same prefix was  because they are similar concepts (reconnection to processes across reloads, save the buffer+re-create the processes across restarts).

Let's keep the setting the same for now as the description is fairly descriptive and that will be searched as well when using the settings UI.

> our setting talks about "processes being recreated" but my understanding is that we only restore the lines and not the running processes

The processes to get recreated using the same properties as the previous process, except the current working directory that may change depending on the shell/OS.
