### ISSUE TITLE
Allow markdown links rendering in modal dialogs

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#133936]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.61-insider
- OS Version: Windows 10

Steps to Reproduce:
1. Build Remote Repositories extension from source and create a PR

Without `modal: true`:
![image](https://user-images.githubusercontent.com/30305945/135023334-66ef5294-bdb1-4ffb-b558-aae307b2ad14.png)

With `modal: true`:
![image](https://user-images.githubusercontent.com/30305945/135023431-2ce7c47f-efcc-49ae-a172-366f40d8c73c.png)

**Comment by bpasero** [comment]
Unlikely that there is standard API across platforms to render links in native dialogs because typically the main actions are provided via buttons. 

Though we could switch to using our custom dialogs if we detect markdown links. 

For now I suggest you remove any markdown styling when using modal dialogs.

//cc @sbatten

**Comment by sbatten** [comment]
I am not seeing any standardization of links in messages from electron. I agree with @bpasero and recommend using buttons in dialogs for link actions.
