### ISSUE TITLE
Terminal: revive makes the terminal very slow to start

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#133964]
Testing #133516

When having the setting enabled to revive terminals, I feel like the terminal needs seconds to open after a restart, vs. otherwise when not enabled.

**Comment by bpasero** [comment]
![recording (1)](https://user-images.githubusercontent.com/900690/135057158-0cbd54d9-687c-4050-98e0-3744c9a43534.gif)

**Comment by Tyriar** [comment]
I wonder how much of this is due to the shared process launching slowly, as opposed to reconnection which doesn't need to wait for that.

**Comment by Tyriar** [comment]
Revive does indeed take a lot longer than a regular reconnect.

Revive:

![image](https://user-images.githubusercontent.com/2193314/141747152-b64d21c6-3e53-4070-9b9d-9d79ad961d8c.png)

Reconnect:

![image](https://user-images.githubusercontent.com/2193314/141747232-ba9ce426-3b9e-4a8b-bd5e-0141e2ad50f2.png)

**Comment by Tyriar** [comment]
Found the main cause, before attach to a pty happens there's a check for whether it's orphaned:

https://github.com/microsoft/vscode/blob/4a7cd9416f37e8f7095e714fdcbc4f16cff114fc/src/vs/platform/terminal/node/ptyService.ts#L363

For freshly revived processes, there is no window to respond to the parent request so it waits for the barrier's 4000ms before resolving:

https://github.com/microsoft/vscode/blob/4a7cd9416f37e8f7095e714fdcbc4f16cff114fc/src/vs/platform/terminal/node/ptyService.ts#L662

So, the fix for this this should trim off about 4 seconds of revive time.
