### ISSUE TITLE
Disabled debugger offered in Select environment quick pick

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#133957]
Found by @karrtikr in https://github.com/microsoft/vscode-python/issues/17493#issuecomment-928526136

We offer disabled debuggers in the "Select environment" quick pick.
The problem is that [in this method](https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/debug/browser/debugAdapterManager.ts#L294) we are not checking if the candidates are actually enabled.
I think a simple fix would be that in the `filter` calls we also check if adapters are enabled.

**Comment by karrtikr** [comment]
> Are you seeing any other UI contribution which should not be there?

I get the following message that I get when attempting to launch the debugger:

<img src="https://user-images.githubusercontent.com/13199757/135362511-74c154cc-46d2-4228-afc5-1cdc5c7dc719.png" width=600 />

But other than this, I don't see any UI disabled or changed.
- Should intellisense in `launch.json` still be the same/valid? Perhaps `when` clause can come up with a `description` of why "python is not supported in this environment"?
<img src="https://user-images.githubusercontent.com/13199757/135363040-d5d4d3b7-eb03-4a12-aef7-d37a168ba1f2.png" width=600 />

- All 3 hyperlinks in `Run and debug` explorer have the same issue I described in https://github.com/microsoft/vscode-python/issues/17493#issuecomment-928526136.

Rather than disabling each UI separately, is it possible to simply ignore the debugger contribution when `"when"` clause is evaluated to `false`? i.e simply consider it empty:
<img src="https://user-images.githubusercontent.com/13199757/135003866-675dfb45-08e8-4701-a670-bc001f69cc84.png" width=250 />

**Comment by roblourens** [comment]
> Rather than disabling each UI separately, is it possible to simply ignore the debugger contribution when "when" clause is evaluated to false? i.e simply consider it empty:

No, we need to know whether it is installed but disabled, so we can do things like offer to install it when it's missing.

I don't think we should disable intellisense in launch.json.

**Comment by karrtikr** [comment]
I see, yeah.

> Perhaps when clause can come up with a description of why "python is not supported in this environment", which can also be used for intellisense?

I would prefer that if each intellisense description is appended with this `when` clause description and comes with a squiggly warning, I agree we should not be removing it.

**Comment by karrtikr** [comment]
Something like this: 
![image](https://user-images.githubusercontent.com/13199757/135365702-f6749dbf-6f16-4991-ab0b-a523b0d26185.png)

**Comment by roblourens** [comment]
That's reasonable. Filed https://github.com/microsoft/vscode/issues/134173
