### ISSUE TITLE
Test: Exploratory Testing of Second Panel (opposite side bar)

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#133919]
Refs: #132893

- [x] anyOS @lszomoru
- [x] anyOS @luabud
- [x] anyOS @brettcannon

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23133919%0A%0A&assignees=sbatten)

---

This milestone, we started to explore a second side bar or side panel. An initial idea has been checked in behind the flag `workbench.experimental.sidePanel.enabled`. To try it out, enable the setting and reload for good measure.

The goal of this test plan item is to have more eyes on it. It is not limited to finding bugs but improving the experience going forward in future milestones.

For that reason, there is not much guidance on what to test, but the basics are:

1) Enable it and open it
2) Drag and drop some views or view containers into it
3) Try using a variety of layout changing commands such as toggle side bar position
4) Use it throughout the remainder of your testing and beyond

Some potential use-cases to try:
1) Having file-specific views on the side panel (e.g. outline, timeline)
2) Having SCM and Explorer visible as the same time
3) An always visible search or references view

**Comment by sbatten** [comment]
@brettcannon thanks for this feedback. The icon is no longer in the activity bar, because the activity bar is the "tab set" for the side bar. The side panel has its own textual tabs. This is the same as if you were to drag the test explorer the bottom panel. the side panel is not an extension of the side bar, but an alternative. 

Does that information impact your view at all?

**Comment by brettcannon** [comment]
It shows you how often I drag anything out of the side bar to the bottom panel 😉. That's why my brain views the activity bar as the global list of views I have available, it just so happens they all live in the side bar. 😁 That's also why my brain gravitated to the icons highlighting where to look on the screen for the view.

But I think I can adjust to having two places to go hunting for a view that I know I have which isn't shown as an icon in the activity bar (assuming I didn't actively choose to hide it).

**Comment by luabud** [comment]
Love this new feature 🥳 will be using it going forward 😊
