### ISSUE TITLE
Terminal tab titles - Empty string versus no entry handled differently

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode#134025]
Testing #133549

1. Delete terminal tab title, notice terminal icon by + is removed:

![image](https://user-images.githubusercontent.com/25310137/135120472-809bcaab-e0c7-4cc5-a959-d2a6f2131115.png)

Didn't initially realize there is a small dot I can click that appears on hover:

![image](https://user-images.githubusercontent.com/25310137/135121028-286cc963-5374-486c-835d-9515b08f5a88.png)

3. If I include a space rather than no title, icon returns:

![image](https://user-images.githubusercontent.com/25310137/135120617-de6c57d5-cb23-47da-a3fd-460b571f85a5.png)

Seems similar to https://github.com/microsoft/vscode/issues/134020

**Comment by meganrogge** [comment]
good catch, should trim that as we want to be sure title is set to processName instead of `' '`

**Comment by joyceerhl** [comment]
Not sure if this is expected behavior, but it seems like an empty string is still handled differently vs no entry, and also the title is now duplicated?

No entry:

![image](https://user-images.githubusercontent.com/30305945/135574786-c93264ca-6ae1-4af0-b5d1-8b1558b1afaf.png)

Space:

![image](https://user-images.githubusercontent.com/30305945/135574822-f2b0ebc6-2962-4621-a9a6-fead83d379f9.png)
