### ISSUE TITLE
[Linux] Set maximum file watchers too low and VS Code won't launch

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#134034]
Testing #133753
1. Set your maximum file watchers to something low like 100. Following the instructions here https://code.visualstudio.com/docs/setup/linux#_visual-studio-code-is-unable-to-watch-for-file-changes-in-this-large-workspace-error-enospc
2. Try to launch code or code-insiders
3. 🐛 They no-op. Maybe we could at least provide some sort of warning saying what is happening. When launching via the console this no output it just exits

**Comment by bpasero** [comment]
I cannot reproduce, nor do I think it is a good idea to change the value.

Besides it looks like more recent kernel versions have a dynamic number based on RAM usage, so I would believe that Linux users are actually seeing this notification at lot less often since then: https://github.com/torvalds/linux/commit/92890123749bafc317bbfacbe0a62ce08d78efb7
