### ISSUE TITLE
Cannot exit VSCode if unable to save remote dirty file(s)

### ISSUE THREAD

**Issue by BahJiy** [microsoft/vscode#134180]
Does this issue occur when all extensions are disabled?: No

Version: 1.60.2 (user setup)
Commit: 7f6ab5485bbc008386c4386d08766667e155244e
Date: 2021-09-22T12:00:31.514Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22463

With the SSH Remote extension installed, when the connection to the server is broken **and cannot reconnect and the editor state is dirty**, VSCode cannot save and is in an infinite loop of reconnecting and saving. This state prevents the user from exiting VSCode unless killed from Task Manager. 

Trying to reload the window or editor (from the message box or command palette) does not do anything. Canceling the save only dismiss the message box. It will appear again if trying to exit.

It also appears that all commands from the command palette doesn't work, selecting them only closes the palette; the command(s) might be queued up behind the saving/reconnecting tasking?

Steps to Reproduce:

1. Connect to a server via the SSH Remote Extension
2. Open a file and make changes to the file
3. Shutdown the server while VSCode is **trying to save the file**. _It is very important that VSCode cannot reconnect to the server_ (so that means either the network is down, the sshd service is shutdown, etc)
4. Wait a minute for VSCode to recognize that the connection is broken
5. You cannot exit, reload, or reconnect and VSCode is in an infinite loop of trying to reconnect and saving. 

![image](https://user-images.githubusercontent.com/91649280/135386296-73c9ba0b-7b25-4900-aba1-8b15a5953bab.png)

Fun fact, trying to close the editor repeatedly via the "X" button when the editor is in this state will stack the message box and the black transparent background. It will eventually make VSCode pure black save for the icon on the top.
![image](https://user-images.githubusercontent.com/91649280/135386365-48783432-f18f-481c-946e-492a0ec32372.png)

**Comment by BahJiy** [comment]
It appears that this was reported a while back, but was closed: #132203

**Comment by bpasero** [comment]
I think the connection is never throwing an error here and thus promises hang infinitly. I think this is something the resolver needs to fix, not sure if from the SSH extension or core.

**Comment by alexdima** [comment]
This is not a recent regression, I could also reproduce in `1.60.2`. There are two distinct problems:
1. reconnection cannot be aborted. i.e. the user cannot express "I am done trying to attempt to reconnect". In this case, reconnection fails, but it fails due to what we consider a temporary reason (e.g. the server cannot be contacted, the network is down). This causes us to retry in 20s, in 30s, etc. We don't have a button for the user to express: "Stop trying to reconnect". This is something new that needs to be added, it was never there.
2. The Cancel button on the dialog "Saving dirty editors is taking longer than expected..." is not canceling the previous, still pending save operation, and the "Don't save" option in the native prompt also does not cancel the previous, still pending save operation (it's like there are multiple pending saves and only the last one can be canceled, the initial one still is executing):

https://user-images.githubusercontent.com/5047891/135622682-ade9b0e0-0586-4ae6-abb1-e43d49f2200b.mp4

**Comment by bpasero** [comment]
I just see a lot of discussion happened in https://github.com/microsoft/vscode/issues/112278 that lead to me bringing up the dialog with cancellation support. 

There is a cancellation token but it is not wired into the save/revert:

https://github.com/microsoft/vscode/blob/6b9d5150dc004dd96d52ec12ba73f766bd391a6c/src/vs/workbench/services/workingCopy/electron-sandbox/workingCopyBackupTracker.ts#L303

and here

https://github.com/microsoft/vscode/blob/6b9d5150dc004dd96d52ec12ba73f766bd391a6c/src/vs/workbench/services/workingCopy/electron-sandbox/workingCopyBackupTracker.ts#L282

I think one challenge here is that file IO operations are not really cancelable. I can pass on the token down into the save operation, but eventually there is a IPC call going out that I think will hang for as long as the connection is not throwing an error.

**Comment by alexdima** [comment]
I analysed a recent build (got the raw logs) and could no longer find `404` http errors nor the string  `webWorkerExtensionHostIframe.html`. I will assume that this is fixed.

**Comment by bpasero** [comment]
@alexdima ok, can you extract the steps for me to reproduce this exactly?

**Comment by alexdima** [comment]
Here are the steps:
* connect using remote SSH to a VM in Parallels or a machine
* disable auto-save
* disable the network connection inside the VM or the wireless in case of using a machine
* (quickly) press cmd+s
* press `x`
* choose "Don't save"
* the window does not close

I spent some time to simulate this using memfs but I could not.

**Comment by alexdima** [comment]
Steps to reproduce from source:
* `scripts/code.sh`
* `New TestResolver Window`
* disable auto-save
* make a change to a file
* run `Remote-TestResolver: Pause connection (Test Reconnect)`
* (quickly) press cmd+s
* press `x`
* choose "Don't save"
* the window does not close

**Comment by bpasero** [comment]
There is save promises pending and we await them to finish:

https://github.com/microsoft/vscode/blob/4a130c40ed876644ed8af2943809d08221375408/src/vs/workbench/services/textfile/electron-sandbox/nativeTextFileService.ts#L76-L78

Unfortunately, pressing `Don't save` does not travel down to the utility that collects save requests, so above loop will never finish unless the underlying file system throws an error.

I think when a text file model is being reverted (that will happen when you press `Don't save`, the `saveSequentializer` somehow needs to drop all save operations, even though I am not so sure about the consequences to be honest. A safer fix might be to improve how above loop tracks pending saves and also account for reverts, but its also ugly...

**Comment by hello-smile6** [comment]
Could you extend AbortController and pass a modified AbortController to every file write which can be aborted normally _or_ by aborting all file AbortControllers at once, then add a way to abort file I/O operations using the UI? Sorry if I'm mistaken, but it sounds like you just need to stop writing to files. I once was downloading thousands of files and ran out of space on my SSD, then my script was hanging until I stopped it. Maybe that might help for you.

**Comment by bpasero** [comment]
I think `AbortController` is elegant but not sure it would help here because the IO operation is not really hanging writing to disk, it is hanging in the IPC connection to the remote (at least that is my understanding). 

The best solution imho would be to throw errors on each waiting IPC calls when the reconnection is cancelled / dismissed. Upstream components can then deal with this accordingly. For example, a failing save call in the text file model land causes the editor to turn dirty and preserve the backup, so you can even quit VSCode without having to make a choice whether to save the editor or not.

**Comment by bpasero** [comment]
Users can now choose to force unload of the window:

![Recording 2022-02-24 at 09 51 29](https://user-images.githubusercontent.com/900690/155490820-80480c74-7d5c-4b5f-893b-d86859fbbfc7.gif)

We had discussed whether we should add a timeout when we know that the file system is connected to a remote, but that is an arbitrary guess that can be right or wrong. Putting the user in charge at least allows for the user to reason depending on the circumstances (e.g. maybe network connection is down, can be fixed and reconnection works). 

A different exploration to consult in March is whether we can improve file handling specifically for remote file systems:
* if files are small, assume that the write operation is atomic and do not wait
* if files are large, implement atomic write support (covered in https://github.com/microsoft/vscode/issues/98063)
