### ISSUE TITLE
Assert that registered editors provide a matching `editorId`

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#134184]
I think when an editor registers to the resolver, we should assert that it's input has a matching `editorId` property.

**Comment by lramos15** [comment]
The only downside here is we don't have the editor input. I could pass an arbitrary resource in and create an editor input then dispose of it so that we can check that the registered id matches the `editorId` but that might be a lot. Otherwise, we could thrown on resolution when the user tries to open it.

**Comment by bpasero** [comment]
Yeah throwing on resolution or printing a warning makes sense to me.
