### ISSUE TITLE
"Deleted" double message in hover

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#134115]
Testing #133743

1. VS Code insiders, open `vscode` repo, open `debug.ts`. Delete it from outside of vscode
2. Hover over Editor title (happens both for shown and hidden tabs)
3. Notice the hover has the word "Deleted" 2 times 🐛 

![Screenshot 2021-09-29 at 13 30 36](https://user-images.githubusercontent.com/1926584/135260350-da38e976-21ee-46ad-92b6-87db84577001.png)

**Comment by bpasero** [comment]
Yeah because there are 2 sources of this decoration:
* git: indicating the file is deleted
* editor: indicating the file is deleted

Not sure whether we should normalize the hover when the same decoration appears twice, but I think what you see is actually expected. 

@jrieken for decorations. Maybe we need some kind of source to indicate which component added the decoration to be able to distinguish?
