### ISSUE TITLE
Dragging Docker view to the side panel caused it to be merged with Output 

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode#134150]
Testing #133919

This one is hard to explain, but I hope the GIF gives a good idea of what happened:

![sidepaneloutputdockerbug](https://user-images.githubusercontent.com/45497113/135321558-07547f73-9c7e-4bb2-ba91-60b5fa985587.gif)

I dragged the Output to the side panel and then the Docker view, and now it seems they're merged together and I can't get the docker view separated again? It seems the only way to unmerge them is to drag each item of the docker view individually and drop them on the activity bar again.  I was expecting it'd just create a new tab for the Docker view instead of merging it in the Output  tab.

**Comment by sbatten** [comment]
this is actually by design, its how drag and drop works in the other panel/side bar as well. if you want a new tab, you must drop it in the tab area. otherwise it moves all views in the container you drag into the existing panel. this is a feature to allow quickly merging view containers. (e.g. gitlens and scm or various test-related views)

**Comment by sbatten** [comment]
you can also right click each view (e.g. docker: volumes) and `Reset location` to put it in its original location.
