### ISSUE TITLE
Code editor

### ISSUE THREAD

**Issue by koushik-c** [microsoft/vscode#134182]
Issue Type: <b>Bug</b>

When ever i create a new file. When i start typing initially to a new file it is going into vim like version not able to copy paste anything. After typing some random keys then i'm able to write code and copy paste thing. 

VS Code version: Code 1.60.1 (83bd43bc519d15e50c4272c6cf5c1479df196a4d, 2021-09-10T17:06:57.931Z)
OS version: Linux x64 5.4.0-88-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-7020U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 0|
|Memory (System)|7.69GB (1.44GB free)|
|Process Argv|--unity-launch --crash-reporter-id 15ecc501-ab28-4e44-9fe1-c30c28f4dd46|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
code-gnu-global|aus|0.2.2
doxdocgen|csc|1.3.2
prettier-vscode|esb|9.0.0
code-runner|for|0.11.5
vscode-pull-request-github|Git|0.30.0
check-npm-updates|iak|1.7.7
better-cpp-syntax|jef|1.15.10
python|ms-|2021.9.1246542782
vscode-pylance|ms-|2021.9.4
jupyter|ms-|2021.8.2041215044
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.194.3
remote-ssh|ms-|0.65.8
remote-ssh-edit|ms-|0.65.8
remote-wsl|ms-|0.58.2
cmake-tools|ms-|1.8.1
cpptools|ms-|1.7.0-insiders
cpptools-extension-pack|ms-|1.0.0
vsliveshare|ms-|1.0.4836
vsliveshare-audio|ms-|0.1.91
live-server-preview|neg|0.1.4
vscode-css-peek|pra|4.2.0
LiveServer|rit|5.6.1
cmake|twx|0.0.17

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30364497
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30371810
dockerwalkthru:30370836
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedc:30364665
pythonvspyt187:30373474
pydsgsc2:30361791
vsqsis400:30374798

```

</details>

**Comment by alexdima** [comment]
It looks like the issue is caused by one of your installed extensions. In order to narrow down the possible problematic extension, please try the following:
* run `F1 > Help: Start Extension Bisect`
* (this will restart VS Code with half of your extensions disabled)
* try to do the steps which reproduce the problem
* if the problem reproduces, click "This is bad" (this narrows down the problematic extension to the half which was enabled)
* if the problem does not reproduce, click "Good now" (this narrows down the problematic extension to the half which was disabled)
* these steps will repeat until the problematic extension is found

| initial | step | final |
|---|---|---|
| ![image](https://user-images.githubusercontent.com/5047891/101918658-e9170f80-3bc9-11eb-9977-857baa291937.png) | ![image](https://user-images.githubusercontent.com/5047891/101918683-ef0cf080-3bc9-11eb-9f9e-98b0177991b2.png) | ![image](https://user-images.githubusercontent.com/5047891/101918706-f502d180-3bc9-11eb-8c86-e56355958bd4.png) |
