### ISSUE TITLE
Change extension recommendations to be dynamic

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#13415]
Recommendations currently come from two curated lists. The first is one we want to keep, we call them **important recommendations** and only essential extensions exist within; these recommendations appear as popus to the user. The second one is an ever growing list of _not-so-important_ extensions, which appear only in the `@recommended` list. We want to replace curation by dynamically querying the Marketplace.

cc @seanmcbreen @waderyan 

--

We still have to look into whether the tagging currently in place gives us acceptable results. The tagging currently running by [`vsce`](https://github.com/Microsoft/vscode-vsce/blob/master/src/package.ts#L213) and run as a background task in the Marketplace creates hidden tags `__ext_${EXTENSION}` for extensions. We can then [query for them ](https://marketplace.visualstudio.com/search?term=tag%3A__ext_md&target=VSCode&sortBy=Relevance)as users open said files. Eg: if the user opens a `.js` file, we'd search for extensions tagged with the `__ext_js` keyword.

Let's take our current curated suggestions and see whether they would show up given this strategy. Make sure you scroll right to see the full data.

| Recommendation                 | Files                                                                     | Current | Next |
|--------------------------------|---------------------------------------------------------------------------|------------|--------|
| ms-vscode.csharp               | `**/*.cs,**/project.json,**/global.json,**/*.csproj,**/*.sln`               | 5          | 1      |
| ms-vscode.mono-debug           | `**/*.cs,**/*.csproj,**/*.sln`                                              | 3          | 0      |
| msjsdiag.debugger-for-chrome   | `**/*.ts,**/*.tsx**/*.js,**/*.jsx,**/*.es6`                                 | 5          | 0      |
| lukehoban.Go                   | `**/*.go`                                                                   | 1          | 1      |
| ms-vscode.PowerShell           | `**/*.ps,**/*.ps1`                                                          | 2          | 0      |
| austin.code-gnu-global         | `**/*.c,**/*.cpp,**/*.h`                                                    | 3          | 0      |
| Ionide.Ionide-fsharp           | `**/*.fsx,**/*.fsi,**/*.fs,**/*.ml,**/*.mli`                                | 5          | 3      |
| dbaeumer.vscode-eslint         | `**/*.js,**/*.jsx,**/*.es6`                                                 | 3          | 0      |
| eg2.tslint                     | `**/*.ts,**/*.tsx`                                                          | 2          | 0      |
| Kasik96.format-indent          | `**/*.php`                                                                  | 1          | 0      |
| felixfbecker.php-debug         | `**/*.php`                                                                  | 1          | 0      |
| linyang95.phpmd                | `**/*.php`                                                                  | 1          | 0      |
| ikappas.phpcs                  | `**/*.php`                                                                  | 1          | 0      |
| tht13.python                   | `**/*.py`                                                                   | 1          | 1      |
| donjayamanne.python            | `**/*.py`                                                                   | 1          | 0      |
| magicstack.MagicPython         | `**/*.py`                                                                   | 1          | 1      |
| saviorisdead.RustyCode         | `**/*.rs,**/*.rslib`                                                        | 2          | 1      |
| hars.CppSnippets               | `**/*.cpp,**/*.cc,**/*.h`                                                   | 3          | 0      |
| mitaki28.vscode-clang          | `**/*.cpp,**/*.cc,**/*.h`                                                   | 3          | 0      |
| ms-vscode.cpptools             | `**/*.c,**/*.cpp,**/*.cc,**/.cxx,**/*.hh,**/*.hpp,**/*.hxx,**/*.h`          | 8          | 0      |
| seanmcbreen.Spell              | `**/*.md`                                                                   | 1          | 0      |
| ms-vscode.Theme-MarkdownKit    | `**/*.md`                                                                   | 1          | 0      |
| DavidAnson.vscode-markdownlint | `**/*.md`                                                                   | 1          | 0      |
| PeterJausovec.vscode-docker    | `**/dockerfile,**/Dockerfile,**/docker-compose.yml,**/docker-compose.*.yml` | 5          | 0      |
|                                |                                                                           | 60         | 8      |

In the third column you'll find the number of triggers per recommended extension. A trigger is a file name/extension which we currently use to recommend that extension. For example, `foo.js` triggers the extension `dbaeumer.vscode-eslint`. There are a total of 60 triggers in our current curated list.

Using the `__ext_` keywords, only 8 of those would actually work. That's 13%. This happens because most of these extensions are not tagged with the corresponding keywords based on the file extensions we recommend them from. For example, `msjsdiag.debugger-for-chrome` doesn't specify anything about `.js` files in its manifest.

Then there's the additional problem of queries returning too many extensions. The query for the `__ext_h` keyword alone returns 359 results. Sorting that query by [downloads](https://marketplace.visualstudio.com/search?term=tag%3A__ext_h&target=VSCode&category=All%20categories&sortBy=Downloads) or by [rating](https://marketplace.visualstudio.com/search?term=tag%3A__ext_h&target=VSCode&category=All%20categories&sortBy=Rating) doesn't seem to help much in narrowing which extensions really are _recommendable_.

Finally, imagining that the `__ext_` keyword queries return a healthy collection of extensions, we need to figure out how to sort that collection and where is the cut-off point between a recommended extension and simply a popular one.

**Comment by joaomoreno** [comment]
@seanmcbreen @waderyan I've distilled the problems with this plan item in the first comment. You guys should figure out whether this is still a viable solution and, if not, how it can be improved.

**Comment by waderyan** [comment]
@joaomoreno thank you for looking into this. Initially, I thought (and told Sean) we should look into improving our manual curation processes and abandon the automatic curation approach. Looking into this in detail though has led me to change my opinion. 

## Not enough trigger coverage

In the table below I comment on each extension. We can achieve 59 / 60 (98%) triggers with some tweaks and fixes to the current algorithm. I have summarized the fixes in the second table below. 

| Recommendation | Comments | Fixable with automation | 
| ------ | --------- | ------ |
| ms-vscode.csharp | To fix add `project.json`, `global.json`, `.csproj, `.sln` as hidden tag outputs for C#. | Yes | 
| ms-vscode.mono-debug | To fix, collect language ids from `contributions.breakpoints`. | Yes |
| msjsdiag.debugger-for-chrome | We did not identify this as a JavaScript extension. To fix, look at `keywords` and `contributions.breakpoints` | Yes | 
| ms-vscode.PowerShell | To fix, look at `keywords`, `contributions.breakpoints`, or `contributions.snippets.languages` | Yes |
| austin.code-gnu-global | Bug. Fixable with `activationEvents.onLanguage`. | Yes | 
| Ionide.Ionide-fsharp | Missing file extensions for fsharp. Add `**/*.ml,**/*.mli`. | Yes |
| dbaeumer.vscode-eslint | Bug. Fixable with `activationEvents.onLanguage` | Yes | 
| eg2.tslint | This is a tough one. I would say we could search the string for TS but that will be too common.  | No |
| Kasik96.format-indent | I cannot access `package.json` (as an aside we should likely remove this from our list because of its low ratings). We can fix this by looking at `keywords` | Yes |
| felixfbecker.php-debug | Fixable by looking at `contributers.debuggers.type` | Yes |
| linyang95.phpmd | Bug. Should have worked with `activationEvents.onLanguage`. Also fixable with `keywords`. | Yes | 
| ikappas.phpcs | Bug. Fixable with `activationEvents.onLanguage` and `keywords` | Yes |
| donjayamanne.python | Bug. Fixable with `activationEvents.onLanguage` and `keywords` | Yes | 
| saviorisdead.RustyCode | Add `**/*.rslib` to list of associated file extensions to `rust` | Yes | 
| hars.CppSnippets | Fixable with `keywords` and `contributions.snippets.languages` | Yes | 
| mitaki28.vscode-clang | Bug. Fixable with `activationEvents.onLanguage` | Yes | 
| ms-vscode.cpptools | Cannot see `package.json`. Fixable with `keywords` | Yes |
| seanmcbreen.Spell | Bug. Fixable with `activationEvents.onLanguage` | Yes |
| ms-vscode.Theme-MarkdownKit | Nothing in `package.json` to help us here. We could look at the text in the title / description. | Yes | 
| DavidAnson.vscode-markdownlint | Bug. Fixable with `activationEvents.onLanguage` and `keywords` | Yes | 
| PeterJausovec.vscode-docker | Bug. Fixable with `activationEvents.onLanguage` and `keywords` | Yes | 

This table summarizes the table above when looking at the fixes we could apply. 

| Fixable Option | # of Extensions |
| ------- | ----- |
| `activationEvents.onLanguage` | 10 |
| `keywords` | 11 | 
| `contributions.snippets.languages` | 2 | 
| `contributions.breakpoints` | 3 | 
| `contributers.debuggers.type` | 1 |
| Associate more file extensions | 3 | 
| Search title / description for text | 1 | 
| Unfixable | 1 |

## Too many extensions

> Then there's the additional problem of queries returning too many extensions. The query for the __ext_h keyword alone returns 359 results. Sorting that query by downloads or by rating doesn't seem to help much in narrowing which extensions really are recommendable.

To answer this I looked at the results for many of our hidden tags. The table below summarizes what I found. 

| Tag | # of Search Results | Language Intent | Useful? | 
| ---- | ------------------- | ---------------- | ------- |
| ext_h | 373 | C, C++ | No | 
| ext_c | 373 | C | No |
| ext_cpp | 0 | C++ | No |
| ext_php | 1 | PHP | No |
| ext_py | 3 | Python | Somewhat |
| ext_rb | 4 | Ruby | Yes |
| ext_js | 10 | JavaScript | Yes | 
| ext_jsx | 2 | JavaScript | Somewhat |
| ext_es6 | 1 | JavaScript | Somewhat |
| ext_ts | 3 | TypeScript | Somewhat | 
| ext_go | 4 | Go | Yes |
| ext_ps | 3 | Powershell | No | 
| ext_md | 1 | Markdown | No |
| ext_markdown | 0 | Markdown | No |
| ext_yaml | 2 | Yaml | No |
| ext_sln | 0 | C# | No |
| ext_fs | 1 | F# | Yes |
| ext_fsi | 1 | F# | Yes | 
| ext_dockerfile | 0 | Dockerfile | No | 

From the results above, it looks like the problem of "too many results" is an outlier for C and C++. Most of the queries are not useful because of a lack of results. 

I do not know right now how to solve for C and C++. Open to suggestions. 

## Summary

I am in favor of making the tagging algorithm changes and then figuring out a fix for C and C++. Please advise on what you would like me to do after syncing with @seanmcbreen (since he's in Zurich I'm assuming you two can connect on this). 


**Resources**
- [draft of tag seeding algorithm](https://github.com/Microsoft/vscode-marketplace/blob/master/tag-seeding-algorithm.js) sent to MP team. 
- You can see hidden tags with `&showHiddenTags=true` on the URL.

**Comment by seanmcbreen** [comment]
Hi,

@joaomoreno and I managed to catch up today and have the following suggestions, we:

* Should update the manually curated list this iteration for missing items
* Need to address a few issues in the tag search in the marketplace
* Will add a gesture to the file type picker to search for related extensions

We will see how that goes and then we may...

* Introduce a more visible hint in the case of no existing extension.

Here is a little more on each item...

# Update Curated List
We should add items for known gaps e.g. 
- .babltrc
- .eslint
- .tslint
- .editorconfig
- DOCKERFILE
- .gitignore
- ...

# Marketplace Fixes
We found two quick issues:

**1. Tag Match:** - high priority
Currently the tag query does a match on the start of the extension so a search for `c` will yield all sorts of results e.g. `cs` - `csharp`, `cgi` = `ruby`, `cpy` = `magicpython`, ...  it should be a strict match to avoid this. 

**2. Missing Tags:** - more investigation
When we processed tags it looks like we did not manage to catch extension only extensions e.g. we should look into this.  At the same time I think of these guys the curated list may be the best approach as for instance Editor config activates on `*` not the config file.  This is true for many where the file is simply `.json`.

# New item in file type picker
We will add a new option in the file type picker for `Search for `.js` marketplace items` [final string TBC] and this will do an extension based search and sort by download count.  For this to work well we need the marketplace search fix mentioned above.

![image](https://cloud.githubusercontent.com/assets/1051190/19563127/2b397f5e-96df-11e6-9f53-e2ce38d0d79d.png)

# Visible Hint for Unknown Files
the scenario here is that the user adds a new file say `foo.tex` we don;t out of the box know what `.tex` is so we render as plaintext.  We could do a check in the background to see if the marketplace understands `.tex` since it does we would notify the user and let them review the marketplace for results.

There is some concern that this could be annoying for some users who look at lots of files with random extensions - so we need to go here carefully.  We would for instance need to offer the ability to stop the nag permanently for some file types.

Ok thats my notes...

@waderyan - do you want to work w/ the marketplace on the HiPri item and also update the curated list?  I can also update the list if you would prefer.

**Comment by joaomoreno** [comment]
Added the new item:

![image](https://cloud.githubusercontent.com/assets/22350/19602049/f8354836-97ab-11e6-8b17-f36ff0f29a97.png)

**Comment by seanmcbreen** [comment]
Nice work add to release notes :)

@waderyan @gregvanl

**Comment by joaomoreno** [comment]
Created #14347. Closing this one.
