### ISSUE TITLE
"View: Toggle Integrated Terminal" not found

### ISSUE THREAD

**Issue by Amandawonglokyiu** [microsoft/vscode#134274]
Issue Type: <b>Bug</b>

"View: Toggle Integrated Terminal" not found in Command Palette. I can only find "View: Toggle Terminal", but when I click it, an error message shows. It says "The terminal process failed to launch: A native exception occurred during launch (Cannot launch conpty)."

VS Code version: Code 1.60.2 (7f6ab5485bbc008386c4386d08766667e155244e, 2021-09-22T12:00:31.514Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.86GB (2.65GB free)|
|Process Argv|--crash-reporter-id 63569861-a830-4256-a614-bbd715bb1f4f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|33.2.2
vsc-material-theme-icons|equ|2.2.0
beautify|Hoo|1.5.0
vscode-liquid-snippets|kil|2.0.3
language-liquid|nei|0.1.1
LiveServer|rit|5.6.1
highlight-matching-tag|vin|0.10.1

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30364497
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30371810
dockerwalkthru:30370836
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30364666
pythonvspyt187:30373474
pydsgsc2:30361791
vsqsis200:30374795

```

</details>

**Comment by meganrogge** [comment]
This seems like an issue with ConPTY. Please report it to https://github.com/Microsoft/console (the team who owns ConPTY) or this repo (if you think it's an integration issue). You can opt out of conpty by adding this setting:

"terminal.integrated.windowsEnableConpty": false

Otherwise, it's related to an anti-virus blocking the library we use to launch the process. If you do have anti-virus software you can try allow the files by following these instructions: https://code.visualstudio.com/docs/supporting/troubleshoot-terminal-launch#_error-connectnamedpipe-failed-windows-error-232

**Comment by rosshjb** [comment]
@meganrogge The setting doesn't work.

- macOS version: 11.6
- vscode version: 1.60.2

---

+1. `View: Toggle Integrated Terminal` is not shown in command palette. But `View: Toggle Terminal` works to me. Currently, the workaround is to use one of these:

- Use keyboard shortcut.
- Use the **View** > **Terminal** menu command.

**Comment by DarkLite1** [comment]
Same issue since updating to version:
```
Version: 1.61.0 (system setup)
Commit: ee8c7def80afc00dd6e593ef12f37756d8f504ea
Date: 2021-10-07T18:13:09.652Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.14393
```
When the cursor is in the editor somewhere while editing a file, then going to the `View > Terminal` does not bring the cursor to the terminal anymore. Same issue when using the `Command palette` or the keyboard shortcut `CTRL + `` as described [here](https://code.visualstudio.com/docs/editor/integrated-terminal).

**Comment by Tyriar** [comment]
@DarkLite1 you're on an older version of Windows which uses winpty that we don't work on anymore, updating Windows will bring you onto the new terminal backend "conpty" which is developed by the Windows console team.

**Comment by DarkLite1** [comment]
@Tyriar so Windows Server 2016 is not using the newer backend? That's only 5 years old...
