### ISSUE TITLE
Please consider expanding the number of configurable colors in new bracket pair colorization feature

### ISSUE THREAD

**Issue by edtz** [microsoft/vscode#134200]
Hello, I've been a user of vs code for quite some time and it's a stellar piece of software, thank you for making it!
As to the request at hand, I've been a fan of "Bracket Pair Colorizer" extension ever since I found it, and very happy it is now integrated into the core with a significant performance boost. Unfortunately, my config for the extension doesn't seem to be compatible with the native feature due to a maximum of 6 colors being supported, in my case I've been using a set of 8 colors that I feel have a distinct enough difference in hue to be useful:

`["rgb(110, 64, 170)","rgb(65, 125, 224)","rgb(26, 199, 194)","rgb(64, 243, 115)","rgb(175, 240, 91)","rgb(239, 167, 47)","rgb(255, 94, 99)","rgb(210, 62, 167)"]`

I would appreciate it if you considered increasing the limit, as to a concrete number I'm not sure what would be the optimal number, but I think 6 is too limiting.

**Comment by valtism** [comment]
I wanted to piggyback this issue because it is related, and I'm not sure it's worth opening a new issue for it. 

I like the bracket colourisation, but I feel like using the default colours from the original extension (pink, yellow, blue) really clash with the default theme and I wish the default colours were more subdued. Customising the colours can absolutely do this for me, but I feel like the defaults should be nice enough that most people won't need to change them.
