### ISSUE TITLE
Add support for restarting the remote extension host

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#134236]

**Comment by alexdima** [comment]
Done via https://github.com/microsoft/vscode/pull/145569

**Comment by bpasero** [comment]
@alexdima would this allow us to remove the following 2 cases where we reload the window instead of restarting the extension host when connected to a remote:

https://github.com/microsoft/vscode/blob/ef70f99af7c90bb37f6dbb797c36de76a51ba73b/src/vs/workbench/contrib/relauncher/browser/relauncher.contribution.ts#L150-L154

https://github.com/microsoft/vscode/blob/99ef89977578a3b799f95fedf697590f7280a4ee/src/vs/workbench/services/workspaces/electron-sandbox/workspaceEditingService.ts#L176-L185

//cc @aeschli

**Comment by alexdima** [comment]
This is a bit trickier than that TODO comment indicates. In a remote VS Code session, it is now possible to restart the **remote** extension host. It is not possible to restart the **local** extension host because the local extension host is keeping alive the tunnel to the remote machine where the vscode server is running.

**Comment by bpasero** [comment]
Yeah thanks, I noticed that when testing too.
