### ISSUE TITLE
Opening a file through breadcrumbs does not add it to recent files

### ISSUE THREAD

**Issue by kertzer** [microsoft/vscode#134313]
Issue Type: <b>Bug</b>

Pretty much the title. It's a very handy feature to open files in current folder through Ctrl+Shift+. shortcut (Focus Breadcrumbs), but unfortunately the files opened in this manner are not added to the list of recently opened files (File: Open Recent...) , so you'll have to open it in some other way to have it quickly accessible there.

VS Code version: Code 1.60.1 (83bd43bc519d15e50c4272c6cf5c1479df196a4d, 2021-09-10T17:07:10.714Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by bpasero** [comment]
That works as intended. The list of recently opened in the file menu is only updated when you go through "File > Open File..." or drop an external file into the window, it is not meant as a list to track each file you have opened because that would make the list grow large really quickly.

If you want a scalable list of recently opened files in a picker, use quick pick for files.
