### ISSUE TITLE
Allow * wildcard in activationEvents

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#134373]
Not sure if this is captured in another issue already.

The larger extensions get the more activation events they get and it can lead to accidentally leaving one off. It's typically just a nuisance typically to remember to add them, for example gitlens has over 130 onCommand items:

https://github.com/eamodio/vscode-gitlens/blob/acde02b4a10252300f1dcd61f6bd68b4042d0474/package.json#L48

This could be replaced for example with `onCommand:gitlens.*` or `onExtensionCommand:gitlens`. The same could be applied to other types are well (`onView:gitlens.views.*`) but the main problem here is handling commands.

cc @eamodio

**Comment by isidorn** [comment]
A use case for Copilot extension is `onLanguage:*`

**Comment by rzhao271** [comment]
Emmet also could use `onLanguage:*`

**Comment by gjsjohnmurray** [comment]
See https://github.com/microsoft/vscode/issues/16045#issuecomment-263826915 for previous code pointer and guidance from @alexdima

**Comment by Tyriar** [comment]
https://github.com/microsoft/vscode/issues/167358 covers my issue, should we close this one now that we have implicit events?

**Comment by joyceerhl** [comment]
I think Emmet still misses a way to activate on any language (Copilot appears to be activated onStartupFinished now, maybe they would prefer onLanguage too). If this is the only usecase for wildcard support, rather than implementing wildcard support which could be tricky to do in a performant way, I wonder if it suffices to add support for a simple unqualified `onLanguage` event here, similar to the unqualified [`onDebug`](https://code.visualstudio.com/api/references/activation-events#onDebug) or [`onUri`](https://code.visualstudio.com/api/references/activation-events#onUri) events? cc @rzhao271

**Comment by alexdima** [comment]
> I wonder if it suffices to add support for a simple unqualified onLanguage event here, similar to the unqualified [onDebug](https://code.visualstudio.com/api/references/activation-events#onDebug) or [onUri](https://code.visualstudio.com/api/references/activation-events#onUri) events?

Great idea! This would be a one liner here --> https://github.com/microsoft/vscode/blob/33b2e923921b749170e58ff1e1bb22d72b6b7629/src/vs/workbench/services/language/common/languageService.ts

**Comment by joyceerhl** [comment]
Closing this issue in favor of https://github.com/microsoft/vscode/issues/167866
