### ISSUE TITLE
API Access to "Open Editors": events fired multiple times on open and close

### ISSUE THREAD

**Issue by ArturoDent** [microsoft/vscode#134359]
Does this issue occur when all extensions are disabled?: Yes/No  Unable to test in extension host environment.

@lramos15 

With this code:

```js
vscode.window.onDidChangeActiveTab(tab => {
  console.log(`tab : ${tab}`);
});

vscode.window.onDidChangeTabs(tabs => {
  console.log(`tabs : ${tabs}`);
})
```

1.  Open a new file in preview and each listener is triggered two times.  

2.  Open a new file not in preview and each listener is triggered three times.  

3.  Close a file (preview or not) that is focused and each listener is triggered two times.  

4.  Close a file (preview or not) that is NOT focused and each listener is triggered one time.   

I assume #4 is the correct behaviour and the others are incorrect.  

-----------------

Version: 1.61.0-insider (user setup)
Commit: c9e8266ee24f34107ff52d836a4e8f533afb93c5
Date: 2021-10-01T14:45:54.159Z
Electron: 13.5.0
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

**Comment by lramos15** [comment]
It's not clear what is happening here but the additional triggers are from the group activating too. So for example 
The Group gets focused (causing trigger 1) and then the tab gets focused (causing trigger 2). This is a tough one because we do group the events together per event loop. I'll investigate it more, thanks for testing :)
