### ISSUE TITLE
Remember the setting for wordwrap

### ISSUE THREAD

**Issue by claell** [microsoft/vscode#134486]
When activating word wrap with `Alt + Z`, it does not get remembered. Neither for a document nor for the whole application. I suggest to remember this setting, so I don't have to activate it every time (or have to change the global setting for this).

**Comment by alexdima** [comment]
`Alt + Z` will toggle word wrap intentionally only **for the current file**.

Would the following alternative ways of configuring word wrap work for you:

* edit your `settings.json` and turn on word wrap globally for all files using `"editor.wordWrap": "on"`
* edit your `settings.json` and turn on word wrap for a certain language using e.g. `[typescript]: { "editor.wordWrap": "on" }`.

**Comment by alexdima** [comment]
Most of the toggle menu items like `View > Show Minimap` or others affect all editors and all files. They are implemented by writing to user settings and that is why they become "persistent". Basically, those menu items open `settings.json`, toggle the global e.g. `editor.minimap.enabled` and then the UI reacts to the settings change and show/hide the minimap based on the settings value.

But for `View > Word Wrap`, we have found that many people don't want that they word wrap all files, but only the current focused file. This has to do with how you sometimes open a file that has really long lines, or maybe view a diff and you want to "quickly toggle word wrap for this file to see something". So `View > Word Wrap` is somewhat different than the other menu items, because it affects only the current file. 

This is not persistent because our `settings.json` cannot yet express resource based settings (it supports either global or per language settings, but not per individual file).

**Comment by alexdima** [comment]
I would leave the menu item as is. Creating an action that writes to user settings and toggles word wrap globally or for the current language is very easy to implement using our extension API. The settings feature request is at https://github.com/microsoft/vscode/issues/112280 .

Regarding LaTeX, I don't think we have any built-in support for that, you most likely are using an extension. You can reach out to the extension and let them know that they can contribute language specific defaults like markdown does e.g. [here](https://github.com/microsoft/vscode/blob/258f6783233d950566696329c3e3714819eaadaf/extensions/markdown-language-features/package.json#L312-L317).

**Comment by claell** [comment]
Alright, thanks for your advice!

Do you want to leave this issue open as dependency of #112280 to make the setting persistent per file after that functionality is available?

I'll also try to contact the extension author for LaTeX!
