### ISSUE TITLE
[decorations] allow positioning of images

### ISSUE THREAD

**Issue by wmaurer** [Microsoft/vscode#13443]
- VSCode Version: 1.5.3
- OS Version: Windows 10

I have released an alpha of extension `vscode-jumpy` [(marketplace)](https://marketplace.visualstudio.com/items?itemName=wmaurer.vscode-jumpy) [(repo)](https://github.com/wmaurer/vscode-jumpy).

I am using `DecorationOption` with `contentIconPath` to display an SVG decoration. However I am unable to have it display below the _baseline_ of the text, as seen here:

![image](https://cloud.githubusercontent.com/assets/2899448/19248999/6b9cf5c0-8f33-11e6-87f1-2caa526f21ac.png)

I have tried many combinations of top and bottom margins and height, but the decoration is never displayed below the baseline, whereas I would like to to extend to the bottom of the _descender_. 

Would it be possible to have this fixed for a future release of VSCode?

**Comment by aeschli** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.
If you disagree and feel that this issue is crucial: We're happy to listen and to reconsider.
Maybe you want to give it a try yourself and provide the feature through an extension or a PR: We're happy to give advise and get you started.
Thanks for your understanding. Thanks for helping and happy coding!
