### ISSUE TITLE
Support "Feature Preview" rollout of settings/defaults.

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#134684]
A few times now we've done "Phased Rollouts" of new feature (welcome, native notebooks, etc.), default setting values. It'd be nice to have some sort of standardized way both for 
- VS Code core to have phased roll-out of a change in default setting values (including new feature flags)
- Users to have a way to view a list of the "experimental" changes currently available/enabled, ideally with a link to a tracking issue on GH

Perhaps an `@experiments` tag in settings editor could help here? Or something new, maybe taking inspi from GitHub's "Feature Preview" modal.

cc @roblourens  @digitarald @luabud

**Comment by sbatten** [comment]
Some thoughts on this from the experiment service (now called workbench assignment service) side...

@JacksonKearl had already made all the technical changes to override experiment values (explicitly on or off).

The configuration service cannot rely on the assignment because it needs to rely on settings for overrides, so the settings editor should do the merging logic.  Right now, overrides are hidden settings with fixed names based on the treatment variables. I would expect this could be done by adding explicit settings that would allow you to describe the experiment. The settings editor would then need to handle the different states (am i opted in or out by choice or by the treatment group).

**Comment by digitarald** [comment]
Love this for many reasons, as it naturally allows the rollout both via outreach leading to manual opt-in and experiments leading to opting in a random set of users.

To support this for extensions, I'd love to see this `'@experiment'` tag supported in settings contributed by package.json as well.

**Comment by sandy081** [comment]
@JacksonKearl @sbatten Can you please shed some light here - what is expected from configuration land?

**Comment by sbatten** [comment]
It seems to me that from configuration perspective, we need to establish some model of doing this, but configuration land itself cannot own calculation since it should not depend on the experiment service. So we need a model where settings can be registered as "default-based-on-experiment" and the settings editor displays that information properly. Secondly, consumers of settings need to have a uniform way of querying for the value of the setting based on the experiment.

**Comment by sandy081** [comment]
@digitarald @rzhao271 

Added support for overriding default values of experimental settings through experiments service. This works in the following way:

- A setting can be tagged experimental using `experimental` tag
- Workbench gets default values for these settings through experiments service (workbench assignment service) by passing the key `config.${setting}`. Eg: `config.workbench.welcomePage.preferReducedMotion`
- Workbench overrides these defaults values for these settings.

@JacksonKearl - You can adopt your setting `workbench.welcomePage.preferReducedMotion` by adding `experimental` tag and workbench will update the default value.

**Comment by sandy081** [comment]
Let me know if there is any thing needs to be done here. Otherwise we are good to close it.

**Comment by sandy081** [comment]
@JacksonKearl / @digitarald Can you please verify this?

**Comment by luabud** [comment]
Thanks a lot for working on this, @sandy081! I verified it works 🥳 I added `"tags": ["experimental"]` to the [python.formatting.provider](https://github.com/microsoft/vscode-python/blob/bd20f1f41eecf24af6649245bb64cbb8633b025a/package.json#L544) setting in the Python extension. Then I set up the experiment in the control tower for my machine only with `config.python.formatting.provider` set to `black`, and it correctly enabled black as my default formatter:


![image](https://user-images.githubusercontent.com/45497113/143962946-f6eeb8c5-5787-4699-baff-cc7774c2cbb0.png)


It also shows correctly when auto completing the setting:

![image](https://user-images.githubusercontent.com/45497113/143963187-42186fab-85da-4b48-8982-50e1ceb09440.png)

**Comment by digitarald** [comment]
Also 👍 from me. I verified with @sbatten who added the experimental flag to `workbench.experimental.layoutControl.enabled`.
