### ISSUE TITLE
Cursor is not moved by arrow keys of keyboard in output panel

### ISSUE THREAD

**Issue by takecy** [Microsoft/vscode#13463]
- VSCode Version: 1.6.0
- OS Version: Mac 10.11.6

Steps to Reproduce:

1.  open output panel (cmd+shift+U).
2. focus at the panel.
3. press the arrow keys on the keyboard.
4. cursor is not moved.

It is very inconvenient 😢

**Comment by isidorn** [comment]
October to investigate

**Comment by takecy** [comment]
Thank you for investigation!
This is not new feature request.
This feature is possible less than 1.6.0, but It became impossible at 1.6.0.

**Comment by isidorn** [comment]
The bottom line issue is that `editorTextFocus` is not set as a context key when output panel is focused. Thus none of the actions that require `editorTextFocus` are triggered in the output. There are different ways to solve this:
* go back to the old behavior that 'editorTextFocus' is fullfiled if output has focus. Currently 'editorTextFocus' is set for a `CodeEditorWidget` and since the output is just a `StringEditor` it does not set this context key nicely any more
* just add the or in the `when` clause for the missing actions so they are also triggered if 'inOutput'

@alexandrudima @jrieken @bpasero  does it intutivly make sense that 'editorTextFocus' is fullfiled if output is focused. If yes we should go with the first soltuion, if not we should go with the second. Though this might break some people - but apperantly not a lot since this is the only complaint thus far.

@takecy as a workaround please add to your `keybindings.json` (preferences > keyboard shortcuts)

```json
{ "key": "up",                    "command": "cursorUp", "when": "inOutput"},
{ "key": "down",                    "command": "cursorDown", "when": "inOutput"}
```

**Comment by takecy** [comment]
@isidorn 
Thank you for investigation and show workaround.
I have obtained the desired behavior after i added below to `keybindings.json`  😄 
```
{
    "key": "up",
    "command": "cursorUp",
    "when": "inOutput"
},
{
    "key": "down",
    "command": "cursorDown",
    "when": "inOutput"
},
{
    "key": "shift+up",
    "command": "cursorUpSelect",
    "when": "inOutput"
},
{
    "key": "shift+down",
    "command": "cursorDownSelect",
    "when": "inOutput"
},
{
    "key": "left",
    "command": "cursorLeft",
    "when": "inOutput"
},
{
    "key": "right",
    "command": "cursorRight",
    "when": "inOutput"
},
{
    "key": "shift+left",
    "command": "cursorLeftSelect",
    "when": "inOutput"
},
{
    "key": "shift+right",
    "command": "cursorRightSelect",
    "when": "inOutput"
},
{
    "key": "shift+alt+left",
    "command": "cursorWordStartLeftSelect",
    "when": "inOutput"
},
{
    "key": "shift+alt+right",
    "command": "cursorWordStartRightSelect",
    "when": "inOutput"
}
```

**Comment by jrieken** [comment]
@isidorn The `editorTextFocus` should be set by the code editor widget as soon as it has focus. I'd wait for @alexandrudima to comment

**Comment by isidorn** [comment]
@jrieken and it is properly set right now. But what changed is that this moved to the code editor widget and output is not a code editor widget.

**Comment by jrieken** [comment]
>  output is not a code editor widget

What? We both talk about this?

<img width="935" alt="screen shot 2016-10-13 at 10 21 10" src="https://cloud.githubusercontent.com/assets/1794099/19341685/c90548aa-912e-11e6-8a0c-21e4a467b012.png">

**Comment by isidorn** [comment]
Yeah. `OutputPanel` is a `StringEditor` which is a `BaseTextEditor` which is a`BaseEditor`.
I do not see the `CodeEditorWidget` class in the hierarchy

**Comment by jrieken** [comment]
It is never in those hierarchies but the BaseEditor just used it

**Comment by isidorn** [comment]
@alexandrudima a gentle reminder to comment once you find time. If not will set this for november since there is a workaround

**Comment by alexandrudima** [comment]
I haven't done anything specific for the output editor, it is AFAIK a regular `CodeEditorWidget`, which sets the `editorTextFocus` key as usual on the passed in `IContextKeyService`. Perhaps something is wrong with the passed in `IContextKeyService`?

**Comment by isidorn** [comment]
Thanks, I will investigate.

**Comment by alexandrudima** [comment]
I've just logged the context and the output editor has no editor context, only the global context.

**Comment by alexandrudima** [comment]
I think the culprit is 08d96455950f917521665a8fff8019f5a49142a8

Easier test-case: `Ctrl+F` followed by `Escape`

![image](https://cloud.githubusercontent.com/assets/5047891/19694093/3e90aaf2-9ade-11e6-9a26-bab27681a952.png)

**Comment by isidorn** [comment]
@alexandrudima thanks a lot - yes that is the root cause. I was not aware that by adding a scopedContextKeyService I would overwrite the original one. The reason why I did that is that I wanted a context key that is true when only output is focussed.
I can not bind that context key to the editorContextKey since that one will be true whenever any editor is focussed.
And there is no other HTML element I can bind it to. 

This particular issue we can easily fix by just reverting my commit - but is there a way for me to also add the key for output that I want.

**Comment by isidorn** [comment]
@alexandrudima if time permits do a code review.
I am doing the same as in repl now and it works just fine. I create the scoped instantiation service and I create the editor using that service. Though I still put my context key on the editor html element but they seem to get somehow nicely merged

**Comment by bpasero** [comment]
Verified that I can use arrow keys in output panel to move up and down.

**Comment by takecy** [comment]
Thank you for fixing this issue.
works fine!
