### ISSUE TITLE
Search editor stopped showing partial results

### ISSUE THREAD

**Issue by JasonWHowell** [microsoft/vscode#134680]
Issue Type: <b>Bug</b>

Recently when I do a large (many GB of files) text search from the Search sidebar, it shows almost instant results as the results accumulate across those files. 

However, when I click the link from search to "Open in editor" the search behavior has changed. The Search: tab shows a spinning progress indicator for a long time, until all results are ready then it suddenly populates the results.

I think we need to revert since this is a regression. It should show partial results as they are discovered, and not show a blank page for a long time. It makes it feel like search is hanging, and I become impatient waiting for nothing to appear.

For example clone http://github.com/MicrosoftDocs/azure-docs/ and search for string: https://azuremarketplace.microsoft.com/marketplace/apps

VS Code version: Code 1.61.0 (ee8c7def80afc00dd6e593ef12f37756d8f504ea, 2021-10-07T18:13:09.652Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (4.04GB free)|
|Process Argv|--crash-reporter-id a79d1c81-fab0-47ee-be85-209d21b1bf06|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (42)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sidebar|Acr|1.2.0
LinkCheckMD|bla|0.3.1
docs-toc|cil|1.5.0
markdown-table-prettify|dar|3.5.0
vscode-markdownlint|Dav|0.44.4
docs-article-templates|doc|0.2.11
docs-authoring-pack|doc|0.1.15
docs-build|doc|0.3.7
docs-images|doc|0.0.9
docs-linting|doc|0.0.7
docs-markdown|doc|0.2.100
docs-metadata|doc|1.0.7
docs-preview|doc|0.3.57
docs-scaffolding|doc|0.0.11
docs-visual-areas|doc|0.2.1
docs-yaml|doc|0.2.7
vscode-pandoc|Dou|0.0.8
gitlens|eam|11.6.1
markdown-table-formatter|fcr|2.2.3
sort-json-array|fvc|3.0.1
vscode-pull-request-github|Git|0.31.0
json-compact-prettifier|ina|1.1.0
json2csv|kha|0.0.1
wordcounter|kir|2.3.0
prettify-json|moh|0.0.3
csharp|ms-|1.23.15
python|ms-|2021.10.1317843341
vscode-pylance|ms-|2021.10.0
jupyter|ms-|2021.9.1001312534
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
azure-account|ms-|0.9.9
azurecli|ms-|0.5.0
github-issues-prs|ms-|0.9.3
powershell|ms-|2021.10.0
vscode-commons|red|0.0.6
vscode-yaml|red|0.23.0
code-spell-checker|str|2.0.9
Poplink|ted|0.3.2
vscode-markdown-table-format|Tom|1.0.1
vscode-asa|usq|0.0.2
markdown-pdf|yza|1.4.4

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vshan820:30294714
vscod805:30301674
vsccppwt:30377799
bridge0708:30335490
bridge0723:30353136
vsqsis300:30374797
vsaa593:30376534

```

</details>

**Comment by JacksonKearl** [comment]
The search editor has always not provided partial results, though what you may be experiencing here is that we sometimes directly copy the results over from the search view (for instance when the set of results has been modified), which should be instant; whereas at other times recompute the entire result set in order to provide context lines, which would take some time in larger repos. 

Additionally, we did recently add the `search.maxResults` setting and change the default limit from 10,000 to 20,000, which could be a cause for some of the slowness.

**Comment by JacksonKearl** [comment]
Ah, yes that repo is absolutely massive... I recommend using workspaces to only open a subset of the folders, or perhaps configuring search.exclude to better filter out the sections you don't want to wait for. The search editor itself has never shown partial results due to problems related to maintaining a consistent ordering of the results as they stream.
