### ISSUE TITLE
Unable to modify same user setting from two different extensions without overriding each other

### ISSUE THREAD

**Issue by gotschmarcel-ni** [microsoft/vscode#134803]
Issue Type: <b>Bug</b>

I have two custom extensions which want to add entries to the same global setting (type: array). It seems that both extensions are activated at the same time which leads to a problem. Both extensions get the current value of this setting, which initially is an empty array. Then both add one entry to this array and update the setting via a WorkspaceConfiguration.update("my_setting", array_of_entries, true) call. This leads to the problem that they override each others update. The last extension basically wins and overrides the update of the previous. How can this be fixed?

VS Code version: Code 1.60.2 (Universal) (7f6ab5485bbc008386c4386d08766667e155244e, 2021-09-22T11:59:27.195Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (0.46GB free)|
|Process Argv|--crash-reporter-id eb77ed79-adb4-4816-a6fc-b11bb06dcc57|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by sandy081** [comment]
Generally the extension that owns that setting should be doing that. Not sure why both of your extensions are writing the setting and would be interested to know who owns that setting. 

Configuration updates go in a queue and hence the last update overrides previous updates. I would recommend to have your own global locking mechanism or extract common code into another extension and two extensions depend on it.

**Comment by Lemmingh** [comment]
It's not about which method is available. It's race condition.

> I have two custom extensions which want to add entries to the same global setting
>
> Every extension providing such meta files needs to basically add their path to the meta files into the setting provided by the Lua extension (which is not owned by us).

You create an obvious **race condition**, and your data is doomed to **corruption**.

---

A simple solution:

Make your other extensions only expose APIs (via `activate()`) and not do things proactively, so that they look like libraries. Then, create a new extension which acts as an orchestrator and invokes them. You can further declare the relationship by `extensionDependencies` and `extensionPack`, but be careful about deadlock.

If you're not familiar with [VS Code API](https://code.visualstudio.com/api/references/vscode-api#extensions), here are examples:

* <https://github.com/microsoft/vscode/blob/a946f9e643d44e9b2cebfb99ab5c0cc53bca3448/extensions/markdown-language-features/src/markdownExtensions.ts#L90-L93>

* <https://github.com/microsoft/vscode/blob/a946f9e643d44e9b2cebfb99ab5c0cc53bca3448/extensions/git/src/main.ts#L207-L213>
