### ISSUE TITLE
[Feature Request] Open file command with arguments

### ISSUE THREAD

**Issue by lonix1** [microsoft/vscode#134949]
Please allow us to set a keybinding to open a specific file (relative to project's root directory).

There are commands like `vscode.open`, `vscode.window.showTextDocument` and `workbench.action.files.openFile` but I can't seem to use them as keybindings.

**Comment by depascalis** [comment]
I've seen people suggest using [vscode.open](https://code.visualstudio.com/api/references/commands) in different ways but I can not get it to work. I have tried it both in `tasks.json` and `keybindings.json`.

The reason I wanted to be able to have a keybinding to open a specific file is because I want keybindings for "Open Settings UI", "Open Settings JSON Editor", and "Open settings.json".

<details>
  <summary>
    <strong>These are some of the arguments I have tested with `vscode.open` in keybindings.json</strong>
  </summary>

```jsonc
    "key": "ctrl+alt+f1",
    "command": "vscode.open",

    "args": "readme.md"
// -> Unable to open '': Unable to resolve resource readme.md

    "args": "/readme.md"
    "args": "./readme.md"
    "args": "${pathSeparator}readme.md"
    "args": "file://readme.md"
    "args": "file:///readme.md"
    "args": "file:////readme.md"
    "args": "file://c:/readme.md"
    "args": "file:///c:/readme.md"
    "args": "file:////c:/readme.md"
    "args": "file://c:\\readme.md"
    "args": "file:///c:\\readme.md"
    "args": "file:////c:\\readme.md"
// -> Error: [UriError]: Scheme contains illegal characters.

    "args": ["readme.md"]
    "args": {"uri": "readme.md"}
    "args": {"uri": "/readme.md"}
    "args": {"uri": "./readme.md"}
    "args": {"uri": "file://readme.md"}
    "args": {"uri": "file:///readme.md"}
    "args": {"uri": "file:////readme.md"}
// -> Unable to open '': An unknown error occurred. Please consult the log for more details..
```

</details>

---
In the meantime you could use the [Commands](https://marketplace.visualstudio.com/items?itemName=usernamehw.commands) extension which opens up for many possibilities.  To add a keybinding for opening a file use this in keybindings.json
```jsonc
{
    "key": "ctrl+alt+f1",
    "command": "commands.openFolder",
    "args": "C:\\readme.md"
}

**Comment by lonix1** [comment]
That is exactly the same reason I wanted this feature, to open the various settings files! :laughing:

I've tried all the various extensions and none work the way I hoped for, including that one which doesn't allow relative paths. The one that gave me the best result [is this](https://marketplace.visualstudio.com/items?itemName=rioj7.html-related-links#open-a-file) although it's also just a workaround and a heavy way to solve such a simple problem.

Agreed this should be built in.

**Comment by depascalis** [comment]
Even though I have solved this using extensions, I agree it would be better to have it built in. It would be properly maintained, it would reduce the risk of it breaking, and the settings would look cleaner. It looks like the API for it is almost there already if I'm not mistaken, so I don't see how this implementation would pollute the codebase, or make it less "lean". 

This has cleaned up my sessions since I constantly had different setting tabs open. With relative URIs I have shortcuts to different project settings and files that I often use. 

```jsonc
  { "key": "ctrl+alt+f1", "command": "someCommand", "args": "${workspaceFolder}${pathSeparator}readme.md" }, 
```
