### ISSUE TITLE
I am having issues with autocomplete

### ISSUE THREAD

**Issue by yashoswalyo** [microsoft/vscode#135088]
Does this issue occur when all extensions are disabled?: Yes

- Version: 1.62.0-insider
- Commit: 0dae77d06e33eaf1616cc1a53d77e717b284a626
- Date: 2021-10-08T05:16:12.022Z
- Electron: 13.5.1
- Chrome: 91.0.4472.164
- Node.js: 14.16.0
- V8: 9.1.269.39-electron.0
- OS: Linux x64 5.14.0-2parrot1-amd64

Not a bug I would say, I dont find any toggle to turn off this:
The after autocomplete of **join** method there is a highlighted colour surrounding the variable(_dirname_) I want to use, and its not showing correctly
I need to press 2 tabs to complete snippet then the next code snippet works
![Kazam_screenshot_00003](https://user-images.githubusercontent.com/42431299/137332908-cfa7717e-2276-4da2-a80a-27fdc0ba2386.png)

**Comment by yashoswalyo** [comment]
> What programming language are you using?

javascript

**Comment by yashoswalyo** [comment]
When I type any **method/variable/function** in **TabStop** of previous autocomplete, then autocomplete doesnt work until,
I press tabs to end that snippet and then go back in braces to write next variable

**Comment by jrieken** [comment]
When a snippet is active, IntelliSense as you type (aka quick suggestions) is disabled. That is because there is a conflict between the <kbd>Tab</kbd>-key which moves to the next placeholder but also accepts a completion. You wouldn't be able to type in a placeholder and then move to the next placeholder as you would accept a suggestion then. You have the following options

* change the default via the `editor.suggest.snippetsPreventQuickSuggestions`-setting
* in snippets trigger suggestions manually (via Ctrl+Space, Alt+ESC (macOS), or `ctrl/cmd+i`)
