### ISSUE TITLE
Update path when renaming the parent of a dirty file

### ISSUE THREAD

**Issue by loganhuskins** [Microsoft/vscode#1350]
When you rename any parent directory of a file you are currently editing, you lose access to the file. You can regain access to it by changing the name of the directory back to what it was before the rename.

I would expect VS Code to move the file you are editing to the new folder even if it is not saved.

I am on version 0.10.3.

**Comment by dbaeumer** [comment]
@bpasero is this something to consider for the December Update

**Comment by bpasero** [comment]
You can always find your dirty files in the working files section. You are not loosing data.

**Comment by jrieken** [comment]
@bpasero How can I verify this? Is that with parent folders outside of the VS Code scope?

**Comment by bpasero** [comment]
Make a file dirty and rename its parent from the explorer inside VS Code. I have actually not checked with a folder outside the workspace, but that should not make a difference.

**Comment by jrieken** [comment]
Ok, understood. Tho I believe this bug is valid, cos it's hardly ever wanted behaviour:

* have a dirty
* rename parent folder
* the changes aren't moved onto the new model but sit on the old
* saving the old file restores the old folder. 

We should either not allow to rename or just know what happens and make the changes on the 'new' file.

**Comment by bpasero** [comment]
:+1: , also think we can be smarter about the parent chain and update it, but it is not data loss.

**Comment by bpasero** [comment]
Opting for prompting the user as outlined in https://github.com/Microsoft/vscode/issues/9313
