### ISSUE TITLE
When reviewing a PR in a container then the GHPR extension is not activated and requires a reload

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#135025]
**Edit: Added steps to Repro**

- Add following setting `"extensions.webWorker": true` to user settings file
- Have GHPR extension installed locally
- Clone the repository https://github.com/egamma/vscode-remote-try-node.git into a container volume
🐛 GHPR extension is enabled locally (web worker)

When a PR is opened in a container the extension install the GHPR extension automatically, when it isn't already installed. The extension is installed in the same way as the other extensions defined in the devcontainer.json.

To reproduce, open a PR in a container, e.g., `https://github.com/egamma/hello-extension2/pull/2`.

Open the extensions viewlet, notice that the extension is installed but now requires a reload to be activated.
Also notice that when in the 'requires reload state' the activity bar shows the GHPR view container contribution (cached?). You can select the contribution and the view container opens but in some undefined state (see the 2nd screenshot below).

![image](https://user-images.githubusercontent.com/172399/105525284-2a2e3380-5ce1-11eb-94cb-27291b4c72ec.png)

<img width="463" alt="image" src="https://user-images.githubusercontent.com/172399/105574386-825a4980-5d64-11eb-86ad-820634963658.png">

**Comment by sandy081** [comment]
Dev containers previously was installing the extensions first and starting the server after. With my changes (to improve perf), it is starting the server and installing the extensions in parallel. This triggered this issue as the client starts loading extensions before all extensions are installed on the server.  I think asking Dev containers to go back to first approach is not a good idea because it blocks starting the server until extensions are installed. So, I think this has to be fixed on client side while reading and loading extensions.

Since we disallow extensions to include `web` extension kind and we do not add `web` extension kind automatically in desktop, I think we can close this as we might not encounter this scenario in desktop.
