### ISSUE TITLE
Animations making VS Code feel slow

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#13529]
The empty document well animations (infinity icon motion, text fade in) make the tool feel slow, as if it can't keep up with me resizing the window.  If i make the windows smaller, the text disappears and then the icon catches up with me.  When i make the window larger, the icon motion is behind my resizing gesture, and eventually the text fades in.

All of these visuals happen after i make a resize gesture, which makes me feel like the tool can't keep up, like something is happening in the background, and I should wait for it.  it is distracting too, it always catches my eye and then I lose my context.

VS Code is lightweight and fast. The UI should feel snappy, not delayed. We don't animate in search results or when we open a file.  Quick Open is instantaneous.  Async queries in the Extensions viewlet show me a progress bar immediately.   Why then does our desktop resize animate behind my gestures?

CC @bgashler1 @seanmcbreen @stevencl @chrmarti @joaomoreno

**Comment by joaomoreno** [comment]
I have exactly the same feeling.

**Comment by bgashler1** [comment]
### Possible explorations I could try

- Remove animation completely (make it snap in/out instantly with no transition)
- Reduce the latency and duration of the animation by say 75% (.25 seconds vs. 1 second)
- Make the tips dismissible with an affordance for people who don't like it (thus animation would not apply)

One other thing we discussed in UX sync today was  that the tips seem more important than the logo (function over form).  So why are we hiding the tips and not the logo at small window heights?

Since we don't want to invalidate Sean's experiment, we will not attempt to change anything in product for the time being, but we can figure out what our next move is.

**Comment by bgashler1** [comment]
Removed all animations/transitions in my PR linked above.
