### ISSUE TITLE
"Workspace does not exist" when failing to connect to ssh remote

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#135331]
- SSH "Connect to host"
- Type some random host name that doesn't exist
- Get the first dialog that I couldn't attach to that host
- Get a second dialog, "workspace does not exist"

![image](https://user-images.githubusercontent.com/323878/137807557-b7a13a84-4165-4265-96dd-97486313150c.png)

**Comment by bpasero** [comment]
@roblourens this was an intentional change to help Codespaces users. If you manage to open a folder in your Codespace and later delete that folder, you would always end up in that folder (because we restore the last opened folder when you just open that Codespace). 

Locally, we have a way to check if a local folder still exists and then fallback to an empty window before even opening the workbench but we cannot do that with remote.

What in particular is the issue here? The 2 dialogs?

**Comment by bpasero** [comment]
🤔  should this be limited to web only?

@jkeech @GideonCheruiyot thoughts?

**Comment by jkeech** [comment]
> 🤔 should this be limited to web only?
> 
> @jkeech @GideonCheruiyot thoughts?

For Codespaces, we want the behavior in both web and desktop. The same scenario is applicable to both: the user is connected to a folder in their codespace, and then the folder is renamed/deleted while they are connected (either intentionally or accidentally or by doing a `git pull` which includes a commit that renames the folder, etc). After the user disconnects and reconnect, we don't want VS Code to fail to connect which sort of locks them out of the codespace without a clear path to get back in.
