### ISSUE TITLE
Match case is always enabled when initially pressing Ctrl+d, regardless of the state of the last Ctrl+f search

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#135367]
![recording](https://user-images.githubusercontent.com/2931520/137876898-7982ee71-649c-43ff-97a1-5ead619625ab.gif)

As you can see in the recording, "match case" is always enabled the first time Ctrl+d is pressed.
This is the case even though "match case" is disabled in the search widget.

Unrelated question: What is the function of the regex option here?

**Comment by alexdima** [comment]
@hediet match case and whole word get turned on when pressing `Ctrl+d` without a selection because the initial `Ctrl+d` expands the selection to the current word. The assumption is that starting without a selection means you're looking for case sensitive matches of the current word. From chat:

> * if you begin with a collapsed selection and press ctrl+d, then the selection expands to the current word and for as long as you continue pressing ctrl+d, whole word and match case will be on
> * if you begin with a non-collapsed selection and press ctrl+d, then the modifiers are taken from the last state of the find widget

The same reproduces with the find widget open, hiding the find widget does not influence this:

https://user-images.githubusercontent.com/5047891/137884162-4f86f468-2d9e-48f0-84de-3fb39f535ed6.mp4
