### ISSUE TITLE
Expose cancellation token on onWill-events

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#135391]
continues https://github.com/microsoft/vscode/issues/135036#issuecomment-946739628

Timeout and user-cancellation applies when calling `onWill`-events. However, we don't expose that in the API and silently stop async-event delivery and ignore results. We could let extension know via `XYZEvent#token`

**Comment by heejaechang** [comment]
For some big repo, it is possible for LS to parse more then hundreds files (which takes long time), right now, this can't be cancelled since we don't get any cancellation token (hence, no cancellation request). vscode side acts like it is cancelled, but only front end (vscode) is cancelled, all the backends (LSP and LS) that are actually doing the work are not cancelled. so even if vscode code send new requests (since vscode side is cancelled), LSP/LS won't be able to respond (not all LS is designed to process concurrent requests especially requests that have potential to change LS states). so only front end cancellation won't help much overall experiences.

**Comment by jrieken** [comment]
fyi @dbaeumer - this is now a thing and ready for LSP adoption

**Comment by DanTup** [comment]
Neat, thanks @jrieken! 🙂

**Comment by alexr00** [comment]
I verified that the token is available on the events, but it wasn't clear to me how to cause a user cancellation of the save/rename/delete. Can this only be done if there's slow file system provider?

**Comment by jrieken** [comment]
You can call `waitUntil` of the event with a promise that never or slowly resolves. Eventually the UI shows a progress notification which allows to cancel. That cancel will propagate to the extension.

**Comment by alexr00** [comment]
👍 I have now also verified that the token properly reflects the cancel status.

**Comment by jrieken** [comment]
Thanks!
