### ISSUE TITLE
Smoke test failure: Quick Access  > quick access search produces correct result:

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#135470]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=139549&view=logs&j=3792f238-f35e-5f82-0dbc-272432d9a0fb&t=00d0ae10-f5a4-5438-a3b8-c58076933cab

**Comment by roblourens** [comment]
It looks like we were slow to connect, we see this 
![image](https://user-images.githubusercontent.com/323878/138168370-d4095f5a-0e1c-4f6e-9d3d-d37155f41e76.png)
 for a bit after the quick open opens. Search is _supposed_ to wait until the remote is connected and a search provider is registered, and in my testing that still works but it could be the issue here. I guess I can look for a way to delay the tests starting until the server is connected.

**Comment by bpasero** [comment]
Many changes have gone in around quick access and trend looks good:

![image](https://user-images.githubusercontent.com/900690/146527049-f16e8e72-0494-40ad-87d2-af7fe2e11ca0.png)
