### ISSUE TITLE
Debug API: startDebugging should return either the DebugSession or the Id the new debug session

### ISSUE THREAD

**Issue by JustinGrote** [microsoft/vscode#135407]
`startDebugging` only returns true/false from the promise when the session is started, but no indication of the `debugSession` itself. A hacky workaround using `activeDebugSession` is required that is not completely safe as the active session may change between starting and capturing (though unlikely), this is required to wire via `onDidTerminateDebugSession` to a specific debug session, since multiple debug sessions can now be run simultaneously.

Obviously this would probably be a pretty breaking change so a new method (e.g. `startDebuggingSession`) for this behavior would be ideal.

# Existing Workaround
```ts
const debugStarted = await debug.startDebugging(
  debugConfig.cwd,
  debugConfig
)
const thisDebugSession = debug.activeDebugSession

const stopDebugEvent = debug.onDidTerminateDebugSession(debugSession => {
    if (debugSession.id !== thisDebugSession.id) {
		return
    }
	...
}
```

# Requested Behavior
```ts
const thisDebugSession = await debug.startDebuggingSession(
  debugConfig.cwd,
  debugConfig
)

const stopDebugEvent = debug.onDidTerminateDebugSession(debugSession => {
    if (debugSession.id !== thisDebugSession.id) {
		return
    }
	...
}
```

**Comment by weinand** [comment]
I understand the need to have `startDebugging` return something more useful than a boolean.
But this is tricky for the following complications: 
- for composite launch configurations, `startDebugging` will start more than one debug session so it needs to return a set of debug sessions and callers will have to figure out what they get...
- some debug extensions create a "dummy" or "fake" debug session which doesn't do any debugging but just prepares for a real debug session that gets created asynchronously.

Since both complications can be easily solved by using a `onDidStartDebugSession`, we have decided not to return sessions from `startDebugging`.
