### ISSUE TITLE
Language settings: support live code snippets to reflect formatter settings

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode#135436]
## Context

Language extensions like Java and C/C++ have expressed the need to show users a preview of how their code will be formatted as they configure the language formatter settings.

Today, some extensions have built custom webview UI with which users can change settings and see a code snippet update dynamically. This is problematic for two reasons: 
- Users need to interact with yet another settings UI
- Any extension that wants similar functionality will need to roll their own version (or lift the custom UI from another extension)

## Proposal

Expose native support for dynamic code snippet previews in the Settings UI to show users how the code would change as they adjust settings. This could look something like:

![CleanShot 2021-10-19 at 16 00 02](https://user-images.githubusercontent.com/25163139/138002095-3c21d61c-e235-4f7f-b17e-1e2d6c06f7ac.gif)

Additionally, there could be value in having a roll-up preview of all settings applied to a single example file. This could look something like:

<img width="955" alt="CleanShot 2021-10-19 at 16 01 43@2x" src="https://user-images.githubusercontent.com/25163139/138002177-b5b3ea70-b8db-4267-afbd-0e2f29c39d64.png">

## Prior art 

GitLens Settings 

![CleanShot 2021-10-19 at 15 25 05 2](https://user-images.githubusercontent.com/25163139/138000408-70a8004e-1c33-482b-b440-6f14a1e27beb.gif)

TS/JS (static images)

![CleanShot 2021-10-19 at 15 28 10@2x](https://user-images.githubusercontent.com/25163139/138000488-4874bde1-b9c4-4580-b047-3ca565999f11.png)

cc @jureid @misolori

**Comment by daviddossett** [comment]
> Had a conversation with the C++ extension folks and they may be planning on implementing their own version of this

Yep, @jureid from that team was the one who pitched the idea to me 👍 I think the secondary goal here would be so that the various language extensions don't need to each roll their own version.

**Comment by misolori** [comment]
cc @eamodio

**Comment by isidorn** [comment]
I agree that this should be handled in VS Code core, and not that every language / formatter has their solution.
I like @daviddossett first proposal: once formatting is enabled the code snippet just updates and that is all.

Now let's discuss how this would technically work. I see that some settings already provide code snippets, for example `javascript.inlayHints.enumMemberValues.enabled`. What would be different in this case is that we would need a way for clients to provide snippet for disabled state and snippet for enabled state. @sandy081 @rzhao271 is this how this would work in theory, or am I missing something?

@jrieken what do you think about this proposal? Would this also benefit other formatters?

**Comment by rzhao271** [comment]
The only options I currently see are:
1. The extension author provides different sample snippets showing what happens to the code text, and we send that through the markdown parser/syntax highlighter.
2. We add in mini read-only Monaco editors that apply all the effects. This covers cases like syntax highlighting, codelens, inlay hints (where the user actually gets to see the hints rather than just a comment about where they will be placed). I'm not sure how perf will be when it comes to this, though. The extension author will only have to provide a single example snippet.
3. The extension author provides different images for the different cases.

**Comment by isidorn** [comment]
Aha, so you are saying that the `javascript.inlayHints.enumMemberValues.enabled` provides an image currently? How does this work wrt themes. This just works, so I think it is not an image, or am I missing something?

I think we should just keep on doing what we are doing for `javascript.inlayHints.enumMemberValues.enabled` but we just need to double it for 2 states (enabled / disabled).

**Comment by rzhao271** [comment]
No. That setting currently provides a snippet, but the snippet is of the form `function fun(/* content: */ value)`, where there is a comment instead of an actual image of an inlay hint:
![Example inlay hint](https://user-images.githubusercontent.com/7199958/155748190-c5d29ee9-0fb3-4e08-bf34-dcaeafd868c7.PNG)

**Comment by daviddossett** [comment]
@jureid let us know if you have any other thoughts here now that the idea has baked for a bit!
