### ISSUE TITLE
README.MD preview text is not updated when the README.MD file is replaced within the VSCODE explorer

### ISSUE THREAD

**Issue by pa0694** [microsoft/vscode#135568]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.61.2
- OS Version: Windows 10

Steps to Reproduce:

1. Add a README.MD file with some text to the root folder
2. Preview the file in VSCode and close the preview
3. Create an other README.MD inside an other folder, and then drag & drop it to the Explorer tab in VSCode in order to erase the previous README.MD (it's important to do drag and drop it from the explorer in VSCode and not in Windows Explorer)
4. Preview the README.MD in VSCode : it's the previous README.MD which is showed, and not the current one (bug)
![capture](https://user-images.githubusercontent.com/70905569/138300542-cb37ef68-78f3-4aaf-a886-8096a7538ab2.png)

**Comment by rzhao271** [comment]
Closing the second file before dragging it over sometimes results in the first file just closing, too.
I can repro this case fairly consistently, though I did hit the correct/expected behaviour once.

![Recording](https://user-images.githubusercontent.com/7199958/144308466-4504333a-4f60-45f1-b184-bc1c7f36284c.gif)

**Comment by mjbvz** [comment]
@bpasero Can you please take a look at this? Following @rzhao271's comment, I confirmed this is not a markdown specific problem
