### ISSUE TITLE
CMake Tools extension activating too soon

### ISSUE THREAD

**Issue by jeffbi** [microsoft/vscode#135673]
Does this issue occur when all extensions are disabled?: Yes/No

N/A

- VS Code Version: 1.61.2
- OS Version: linux 5.4.0-88-generic (Mint) running on a VM.

Steps to Reproduce:

1. Open a non-CMake folder
2. CMake Tools extension activates.

I know this seems to be a CMake Tools extension issue but I have already hashed this out with them (CMake Tools issue microsoft/vscode-cmake-tools#2127) and they recommended opening an issue here.

When opening a folder with no `CMakeLists.txt` file, the CMake Tools extension activates and prompts me to configure the project, then notifies me that no `CMakeLists.txt` file could be found. The folks at the CMake Tools repository are saying that the search for the `CMakeLists.txt` is timing out and that VS Code is activating the extension for that reason. The folder in question contains only eight files and no sub-directories.

If it helps, the thread of the referenced issue contains the output from running `Developer: Startup Performance`.

**Comment by bobbrow** [comment]
@roblourens 
It would be really nice if you could prioritize #44711 or give us an API that we could call into to learn the activation reason. We just got another report of this and also found the telemetry on it which seems to indicate that our recent change to scope the search is actually slower than the full workspace search.

These are our top activation reasons and the number of unique machines hitting them:
reason|dcount_VSCodeMachineId
---|---
|workspaceContains:\*\*/CMakeLists.txt	|235468|
|workspaceContainsTimeout:\*/CMakeLists.txt,\*/\*/CMakeLists.txt,\*/\*/\*/CMakeLists.txt	|226206|
|workspaceContains:CMakeLists.txt	|181075|
|workspaceContains:*/CMakeLists.txt,\*/\*/CMakeLists.txt,\*/\*/\*/CMakeLists.txt	|167803|
|workspaceContainsTimeout:\*\*/CMakeLists.txt	|139369|
|workspaceContains:CMakeLists.txt,\*/CMakeLists.txt,\*/\*/CMakeLists.txt,\*/\*/\*/CMakeLists.txt,.vscode/cmake-kits.json	|30658|
|workspaceContains:\*\*/CMakeLists.txt,.vscode/cmake-kits.json	|17273|

**Comment by bobbrow** [comment]
Did VS Code release an update around November 8?  It looks like we're getting significantly more activations than before and I suspect they are all timeouts because we're seeing more frequent feedback about it.  It may indicate a regression in the timeout logic.

![image](https://user-images.githubusercontent.com/12818240/142499875-3a1de940-0f7c-45a2-92d8-f1235ec45518.png)

**Comment by roblourens** [comment]
Actually around that time, I noticed that the logic for limiting the workspaceContains time was not working correctly, and I fixed it. So you will probably see more `workspaceContainsTimeout` now that previously would have left a search running for a long time. That will probably make it hard to tell whether the new glob patterns are more efficient. 

But I also realized that `*/CMakeLists.txt` will not actually limit the search to one folder deep. ripgrep by itself doesn't do an optimization like that. But, we are actually doing something in vscode to make text searches like that faster, but it doesn't apply to these workspaceContains searches. Just opened https://github.com/microsoft/vscode/issues/137484 and I will look into improving that.

**Comment by bobbrow** [comment]
Thank you @roblourens.  If there is any way we can get information about whether the extension activated due to a timeout condition, that would probably help us the most because then we'd just keep the extension dormant until some other command activated it "for real."  We have a "partially activated" state that we can use for this.

**Comment by bobbrow** [comment]
Also it would allow us to ship a patch release before the next version of VS Code as I'm sure we're going to get a lot of feedback about this.

**Comment by roblourens** [comment]
That probably isn't something we want to do, but cc @alexdima

**Comment by alexdima** [comment]
@bobbrow We have heard similar complaints before e.g. in https://github.com/microsoft/vscode/issues/73656 . I wanted to clarify what you would expect. The current behavior is that if the `workspaceContains` times out, then we activate the extension. But in #73656 the expressed desire is that if `workspaceContains` times out, then the extension should not be activated, because if a user opens a file, then the extension will activate anyways. What would you expect to happen in the `workspaceContains` time-out? I'm willing to change the behavior.

**Comment by bobbrow** [comment]
> **EDIT**: I've changed the behavior to no longer activate the extension if `workspaceContains` times out. We have received more complaints recently about this.

@alexdima that solution sounds great to me.

**Comment by roblourens** [comment]
I didn't know you were getting new complaints about workspaceContainsTimeout. I think the change makes sense, extensions should be able to fall back on another activation event, I can mention this in release notes.
