### ISSUE TITLE
notebook file open perf marks are broken

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#135834]
Whenever using notebooks for a non-trivial period of time I see this warning: `notebook file open perf marks are broken`

**Comment by rebornix** [comment]
@jrieken can you share the log next time you see it, I updated the error message to give me better hints of what goes wrong.

**Comment by Lillian-Oostrom** [comment]
Don't know if it's the exact same issue but I get this:

`notebook file open perf marks are broken: startTime 1651577074041, extensionActiviated 1651577074076, inputLoaded 1651577074080, customMarkdownLoaded undefined, editorLoaded 1651577074097
setInput @ notebookEditor.ts:278
await in setInput (async)
doSetInput @ editorPanes.ts:281
doOpenEditor @ editorPanes.ts:150
openEditor @ editorPanes.ts:118
(anonymous) @ editorGroupView.ts:1096
doShowEditor @ editorGroupView.ts:1120
doOpenEditor @ editorGroupView.ts:1078
doCloseActiveEditor @ editorGroupView.ts:1504
doCloseEditor @ editorGroupView.ts:1435
doCloseEditorWithDirtyHandling @ editorGroupView.ts:1425
await in doCloseEditorWithDirtyHandling (async)
closeEditor @ editorGroupView.ts:1410
run @ editorActions.ts:462
runAction @ actions.ts:190
run @ actions.ts:181
run @ titleControl.ts:84
onClick @ actionViewItems.ts:168
(anonymous) @ actionViewItems.ts:148`

**Comment by jrieken** [comment]
This (or same root cause messages) also happen when running integration tests

```
[44512:0707/143850.406603:INFO:CONSOLE(19)] "Skipping overwrite of notebook perf value: extensionActivated", source: vscode-file://vscode-app/Users/jrieken/Code/vscode/out/vs/workbench/contrib/notebook/common/notebookPerformance.js (19)
[44512:0707/143850.506597:INFO:CONSOLE(19)] "Skipping overwrite of notebook perf value: customMarkdownLoaded", source: vscode-file://vscode-app/Users/jrieken/Code/vscode/out/vs/workbench/contrib/notebook/common/notebookPerformance.js (19)
```

**Comment by jrieken** [comment]
I am not really sure what's going wrong here but the fact that [perfMarks](https://github.com/microsoft/vscode/blob/6cf558d7a0bf13ef6726bb5fe91219633a042094/src/vs/workbench/contrib/notebook/common/notebookPerformance.ts#L12) is a global which is used by instances seems fishy. I believe the usage of a global assumes one resources is only opened in one editor at a time (which doesn't hold)

**Comment by jrieken** [comment]
Steps

* open a notebook (no preview tab)
* split it
* in any split, open another notebook
* close it
* 🐛 perf marker are broken

https://user-images.githubusercontent.com/1794099/177779809-bca73bb6-5cfb-4bcc-ac5e-fa251a8fa591.mov

**Comment by roblourens** [comment]
I was looking at refactoring this so the perf marks correspond to editors, not resources. Easiest thing to do would be to make the perf marks owned by NotebookEditorWidget. One is in NotebookEditor, it can be moved. The weird one is the one on the editor input https://github.com/microsoft/vscode/blob/4dc272701b0a6e5cf59cfc38d1e08f8862604b05/src/vs/workbench/contrib/notebook/common/notebookEditorInput.ts#L239. Not sure how to handle this since an editor input doesn't know which editor it is being resolved for. Also you are logging one time for extensionActivation, then subsequent calls will log something short because the extension is already activated. Are we more concerned about the actual extension activation time or the typical time that this phase takes, whether or not the extension was already activated?

**Comment by jrieken** [comment]
> Are we more concerned about the actual extension activation time or the typical time that this phase takes, 

For the former there is also dedicated extension activation telemetry which should help with insights about this

**Comment by roblourens** [comment]
Yeah, I feel like in this case we care about the typical time to open a notebook. I want to know what the typical experience is but that phase seems less interesting if it's mostly out of our control.

**Comment by jrieken** [comment]
Still seeing this or see this again

**Comment by jrieken** [comment]
<img width="2893" alt="Screenshot 2022-10-26 at 14 17 31" src="https://user-images.githubusercontent.com/1794099/198023936-553f71ae-1cad-4ae8-b0df-f2cd463aa79c.png">

**Comment by jrieken** [comment]
reproduces with these steps: https://github.com/microsoft/vscode/issues/135834#issuecomment-1177577742

**Comment by roblourens** [comment]
This fails when reopening the same notebook that was previously open in a NotebookEditorWidget. I think the fix is to ignore the customMarkdownLoaded mark here because that step didn't happen on this open. However this means that the telemetry event is now fired in a case where it was not previously fired. I could also add a new event besides `notebook/editorOpenPerf` to cover that case, if that event should only cover a fresh editor open.
