### ISSUE TITLE
Does not work vscode-icons!

### ISSUE THREAD

**Issue by DumanBi** [Microsoft/vscode#13588]
- VSCode Version: Code 1.6.0 (e52fb0bc87e6f5c8f144e172639891d8d8c9aa55, 2016-10-10T18:37:40.189Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: abusaidm.html-snippets-0.0.16, dbaeumer.vscode-eslint-1.0.7, gerane.Theme-Monokai-0.0.2, HookyQR.beautify-0.4.0, mohsen1.prettify-json-0.0.3, ms-vscode.PowerShell-0.7.2, msjsdiag.debugger-for-chrome-1.1.0, robertohuertasm.vscode-icons-3.0.3, vsmobile.vscode-react-native-0.2.0, waderyan.gitblame-1.3.0, xabikos.JavaScriptSnippets-1.2.0

Steps to Reproduce:

1. Install vscode-icons
2. Enable vscode-icons, does not work!

**Comment by isidorn** [comment]
Please do not use vscode-icons extension, vscode now supports icons out of the box.
 More details http://code.visualstudio.com/updates#_workbench
vscode-icons extension modifies the source of vscode leading to unpredicted behavior

**Comment by robertohuertasm** [comment]
@isidorn sorry but that's not true. 

@DumanBi in fact vscode-icons supports the official theme api, that's why `icons enable` command does not work anymore. Please, take a look at the [readme](https://github.com/robertohuertasm/vscode-icons/blob/master/README.md), specifically [here](https://github.com/robertohuertasm/vscode-icons/blob/master/README.md#wanting-to-use-the-official-api-and-get-rid-of-the-custom-functionality) if you were using the custom functionality.

**Comment by isidorn** [comment]
@robertohuertasm thanks for pointing this out, was unware of the new version - my appologies.
