### ISSUE TITLE
Format javascript code with shift+alt+f adds new blank lines

### ISSUE THREAD

**Issue by DennisAhaus** [Microsoft/vscode#13591]
- VSCode Version: Code 1.6.0 (e52fb0bc87e6f5c8f144e172639891d8d8c9aa55, 2016-10-10T18:37:40.189Z)
- OS Version: Windows_NT ia32 10.0.10586
- Extensions: alefragnani.project-manager-0.10.0, dbaeumer.vscode-eslint-1.0.7, donjayamanne.githistory-0.1.0, DotJoshJohnson.xml-1.6.0, eg2.vscode-npm-script-0.0.20, HookyQR.beautify-0.4.0, humao.rest-client-0.8.5, ms-vscode.cpptools-0.9.2, msjsdiag.debugger-for-chrome-1.1.0, sandy081.todotasks-0.4.0, waderyan.gitblame-1.3.0

Steps to Reproduce:

1. Open vs code
2. Open javascript file
3. Press format code (shift+alt+f)

In my vs code editor each line (LF) will have additional blank line after pressing these buttons. If i have 10 lines before, i have 20 lines after

**Comment by jrieken** [comment]
@DennisAhaus Please try to repro without extensions enabled (`code --disableExtensions`). If that still shows the behaviour it is our TypeScript/JavaScript formatter - else my suspect is the beautify-extension you have installed

**Comment by DennisAhaus** [comment]
Yes @jrieken you are right. I disabled the beautify extension and now it works correctly. Thank you for that hint.

**Comment by jrieken** [comment]
Great - please report to them such they know and can fix

**Comment by HookyQR** [comment]
@DennisAhaus: This is happening because of a mismatch of settings. The default setting for line endings on windows is CRLF, but you've set your file line ending to LF. beautify is using the default setting to format the code, and when the edit is applied, VS Code is changing the CRLF to LFLF, giving you double line endings. (It only does this on Windows)

If you're using a `.jsbeautifyrc` file, add `"eol": "\n"`.
If you're using editorconfig, add `end_of_line = lf`.
If you're not using any of these, add a workspace (or user global) setting of `"files.eol": "\n"`.

@jrieken: This doesn't happen on MacOS. Having beautify return with "\r\n" line ends while the editor is set to LF works fine. (CRLF is correctly converted to LF in the editor) Back on to you for that one.

**Comment by hubbergit** [comment]
@HookyQR: However setting "files.eol": "\n" obviously has the effect that all new files created will have now the none-standard line endings "\n" instead of "\r\n". If you have already a lot of files with that default line endings, you end with mixed line endings between the files in your project.

Why can't beautify just detect which line endings are used in a file and act accordingly. VS Code seems to do exactly that.
![unbenannt1](https://cloud.githubusercontent.com/assets/19938289/19535096/c0a3a1ee-9646-11e6-90ef-42a2f6a77fe4.png)
![unbenannt2](https://cloud.githubusercontent.com/assets/19938289/19535248/30fe8be8-9647-11e6-9457-4c99a224cc55.png)

**Comment by HookyQR** [comment]
@hubbergit, I'm happy to continue the discussion on how the extension handles line endings on the issue you logged there.

The miss handling of CRLF to LFLF conversion, specific to the windows platform can stay here though, because that's a VS Code issue.

**Comment by hubbergit** [comment]
@HookyQR Agreed, let's continue the discussion related to the extension there.

But are you sure that the miss handling of CRLF to LFLF conversion (on Windows) ist caused by VS Code?

As far as I can tell the problem does not occur, if the beautify extension is not installed. So the first impression was that it is caused by the extension.

Could you please clearify that a bit?

Thanks in advance!
