### ISSUE TITLE
Very frequently getting this error: Failed to save '....': The content on disk is newer. Click on Compare to compare your version with the one on disk.

### ISSUE THREAD

**Issue by MuhsinFatih** [Microsoft/vscode#13592]
- VSCode Version: Code 1.6.0 (e52fb0bc87e6f5c8f144e172639891d8d8c9aa55, 2016-10-10T18:28:55.412Z)
- OS Version: Darwin x64 16.0.0

Steps to Reproduce:

1. Open vscode
2. Open a folder on a samba shared folder
3. Edit a file and save

I am getting this error about %70 percent of time when I try editing a file on my samba shared drive (drive is on a Raspberry Pi). No one else is using my drive, content on disk cannot be newer. How do I get rid of this error?

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/12232

**Comment by bpasero** [comment]
We should probably introduce a setting for this eventually.

**Comment by nrgiroux** [comment]
I think the setting should be to bypass the 'file changed' check before saving.

Thanks

**Comment by jsecademy** [comment]
+1 for adding the flag to disable file changed dialog.

**Comment by MuhsinFatih** [comment]
guyz please do it already. this is getting frustrating

**Comment by andrewdigitalchaosca** [comment]
get this message every single day at least 10 times, very annoying

**Comment by Bluejay47** [comment]
I am seeing this behaviors as well when I am accessing files on a Samba share (but it's never happened locally). When I compare the files, the file on disk is exactly the same except for the changes that I am attempting to save.

**Comment by apobekiaris** [comment]
any progress here same annoying message

**Comment by mdarif** [comment]
+1

**Comment by mikedoth** [comment]
I'm seeing this behavior on a windows share, and i'm on a windows machine.

**Comment by danjambur** [comment]
Has this been solved yet? Any updates?

**Comment by mjbradford89** [comment]
I'm seeing this issue consistently working on local disk.  Probably every 3 to 4 saves.

Ubuntu 16.04

**Comment by nwayve** [comment]
This issue just started happening to me recently as well after installing the extension Node TDD to try out its features.  After a couple days of this frustration I put two and two together, and uninstalled the Node TDD extension.  Doesn't seem to be having issues anymore.

As much of a pain as it will be, I recommend resetting User/Project settings to their defaults and disabling vscode extensions to see if this is an issue with vscode or a specific extension.  If doing this fixes the issue, try turning on the extensions one at a time and configuring the User/Project settings to what they were until the culprit is revealed.
