### ISSUE TITLE
Watching Private Fields look bad when unavailable

### ISSUE THREAD

**Issue by robpalme** [microsoft/vscode#135945]
Issue Type: <b>Bug</b>

1.  Debug a program with ES2022 `#` private fields.
2.  Manually create a Watch Variable for a field.
3.  Step into a call stack frame that intentionally does **not** have access to the field.

VS Code shows the field value as `Uncaught SyntaxError: Private field '#foo' must be declared in an enclosing class` which is kinda messy and possibly misleading given a Watch Variable is ambient and has no declaration site.  Whereas Chrome DevTools is neat and informs the user that the variable is simply `<not available>` right now.

**VS Code experience**
![private-watch-not-available-vscode](https://user-images.githubusercontent.com/6939381/139050585-a3d5fad8-d90b-43fb-b88a-30071105a74a.PNG)

**Chrome DevTools experience**
![private-not-available-chrome](https://user-images.githubusercontent.com/6939381/139050604-32de931e-5c35-46a7-9f70-114afbca957d.PNG)

VS Code version: Code - Insiders 1.62.0-insider (0f7f6e338a4e86306474d4d01bdea9b8fe798017, 2021-10-27T05:15:07.768Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

**Comment by connor4312** [comment]
After further thought, I don't want to do this. `this.#foo` is obviously valid if the enclosing class contains a field called `#foo`. However, we still want to report errors if the user typo'd `this.#fop` instead of `#this.foo`. It's impossible to distinguish between the two cases. We also don't really know from the debugger point of view whether `this` points to the enclosing class (or if there's an enclosing class at all). Despite all the debugger's smartness, we actually never parse the program's source code.

The chrome devtools just show `<not available>` if there _any_ error raised from the watch expression at all. While this is cleaner, I dislike it because the error might be something I'm interested in -- or at least, if there's a syntax error in my expression I'll want to know about it.

So it does not seem in scope to point fix the property case, and I don't want to follow devtools' lead and hide all errors.
