### ISSUE TITLE
Does Code support the engine `>= 1.0.0` syntax?

### ISSUE THREAD

**Issue by 13xforever** [Microsoft/vscode#13590]
- VSCode Version: 1.6.0
- OS Version: Windows 10 1607, Arch Linux

Steps to Reproduce:
1. Try to install any extension with older dependency string (i.e. [x86 and x86_64 Assembly](https://marketplace.visualstudio.com/items/13xforever.language-x86-64-assembly) before 2.2.7) ([package.json](https://github.com/13xforever/x86_64-assembly-vscode/blob/master/package.json#L9))

Observations:
- Everything worked before updating VS Code to 1.6.0
- Installing local .vsix works just fine
- Only changing the engine dependency from `'>=1.0.0` to `^1.0.0` seem to work; this is not intuitive or obvious in any way
- [Linked issue for my package](https://github.com/13xforever/x86-assembly-textmate-bundle/issues/5#issuecomment-253168729)

**Comment by joaomoreno** [comment]
Sorry about the breakage; before 1.6 that field wasn't being checked.

The syntax is in our docs: http://code.visualstudio.com/docs/extensionAPI/extension-manifest. It only supports `^`.

**Comment by 13xforever** [comment]
The problem is it was generated with `yo code`, so I expect there to be quite a few such extensions. The bad thing is that there's no diagnostic anywhere to point you in the right direction to fix the issue: not in the gui, not on the command line with debug enabled.

**Comment by joaomoreno** [comment]
Thanks for letting me know, that is BAD.

**Comment by joaomoreno** [comment]
@bpasero The generator seems to generate `>=` syntax which

@alexandrudima the version checking algorithm doesn't seem to support.

**Comment by 13xforever** [comment]
Just to clarify: current version of `yo code` generates a new version dependency (`^1.5.0`), but for older extensions it generated `>=`.

**Comment by joaomoreno** [comment]
Got it, thanks for letting me know.

**Comment by bpasero** [comment]
You must have had a generator installed from 2015, we updated to the right version in January 2016. Fix is to `npm install -g generator-code`

**Comment by 13xforever** [comment]
@bpasero that is the point, you're breaking the backwards compatibility and do not provide any diagnostic info on what exactly you've broken. I've spent half a day yesterday guessing what went wrong, gave up and finally had to re-import everything. This is not what I expect from a stable project.

**Comment by joaomoreno** [comment]
Sorry about that @13xforever! Let's leave this open so we print out a message if the engine version is not in the shape we expect it to.

**Comment by alexandrudima** [comment]
@joaomoreno there is code in there that does that -- https://github.com/Microsoft/vscode/blob/master/src/vs/platform/extensions/node/extensionValidator.ts#L204

In case of extensions that don't have a `main` field, the engine version is not checked. Because the extensions don't have code, therefore it doesn't matter what's the API version of `vscode`.

Perhaps we have some **other** piece of code somewhere that decides to validate `engines.vscode` even for declarative-only extensions? Because that would be a breaking change.

**Comment by joaomoreno** [comment]
It's not about whether extensions have that value of not. It's rather about the syntax of the value.

`node-semver`, and thus `npm`, supports the `>=1.0.0` syntax, which we do not. For some reason, `generator-code` use to generate extensions with the `>=1.0.0` syntax. This seems to have occurred due to some miscommunication between @bpasero and @alexandrudima.

We recently added the version check in more places, namely at the install phase on an extension, which made Code break earlier or more often in case a extension came with the `>=1.0.0` syntax.
