### ISSUE TITLE
Option for window.showOpenDialog to always use SimpleFileDialog (not just in browser)

### ISSUE THREAD

**Issue by alexweininger** [microsoft/vscode#135904]
Hi, the team and I working on the Azure extensions for VS Code have a lot of scenarios we would like be able to use this file picker through the window.showOpenDialog API. 

![image](https://user-images.githubusercontent.com/12476526/138958222-b1e0d4b3-2ecf-4b9c-bd8c-1aa52a8779b9.png)

Currently, afaik this is the file picker that is used in browser environments, and is called the SimpleFileDialog in the codebase. What we would love is if a property like `useSimpleDialog?: boolean` could be added to the `OpenDialogOptions` interface, that when `true` would force `window.showOpenDialog` to use the `SimpleFileDialog` instead of the native file dialog in all environments. We would also like to be able to control the title of the quick pick.

https://github.com/microsoft/vscode/blob/1bbe9cfd599ccb1bc1fa220ee05201add6d7c9db/src/vs/workbench/services/dialogs/browser/simpleFileDialog.ts#L103

The main reason we like the simple dialog over the native dialog is that no context or prompt can be given to the user with the native dialog. For example, we can't tell the user "Select the folder you'd like to deploy" while the dialog is shown. But we think this could be possible by using the SimpleFileDialog and the title of the quick pick.

Other things we like more about the simple dialog is that it is less disruptive when using it in a wizard. And it's the same across all operating systems. 

cc: @isidorn

**Comment by isidorn** [comment]
After discussing with @alexr00 we think this is not something we would like to expose to extensions because:
* It would provide an inconsistent open dialog experience to the user
* there is already a setting that lets the user decide if they want to use the simple file picker. If we let extensions choose which dialog to appear then we would sometimes not respect the setting.

So instead I suggest that we try to tackle your primary concern with the native dialog.
@alexweininger is the main problem that you can not control the title of the native dialog?

Your other two concerns:
* Less disruptive when using as a wizard: for wizards you should use the quick pick API diractly and not the openDialog
* Same across all operating systems: I think actually a native dialog is preferred since the app feels more native then and it is not like users are looking for consistency across OS. This is just how some VS Code UI behaves and is expected IMHO

@bpasero there is no Electron API to control title of Native File Dialog? Do you maybe have some ideas for workarounds such that the extension could give more context when opening the file dialog?

**Comment by bpasero** [comment]
@isidorn there is a `title` option for native dialogs in Electron API but we have been setting this to the product name, for example:

https://github.com/microsoft/vscode/blob/02d4cb5383cc863f5c8aa496e107baf31f4da8d9/src/vs/code/electron-main/app.ts#L1057

**Comment by isidorn** [comment]
@bpasero great thanks. The only problem I see is that on macOS the title of the native dialog is not even rendered anywhere. On Windows I see the title area of the open dialog though.

So a more fitting request might be to allow extensions to customise the `title` of the open dialog.

**Comment by isidorn** [comment]
ping @alexweininger for my question
