### ISSUE TITLE
Extension Debugging Not Working , Breakpoint not hitting on right line

### ISSUE THREAD

**Issue by shanalikhan** [Microsoft/vscode#13609]
- VSCode Version: 1.6
- OS Version: Win 10

I cant debug my extension "code-settings-sync". The breakpoints doenst seems to hit on the right time and some times when they do hit, they hit on empty line.
Other problem is for example :
When i place breakpoint on https://github.com/shanalikhan/code-settings-sync/blob/master/src/extension.ts#L75

It shows the variables are undefined but when i run the above line again that variables gets initialized and works in the console, but at the time of debug when the breakpoint hits variables shows undefined when mouse hover and debug console.

**Comment by Alanz2223** [comment]
+1, having the same issue, however I am using babel instead of typescript... Still use source maps though, so I am unsure whether this is an issue with the debugger or the source map.

**Comment by shanalikhan** [comment]
What i did was i generated the new extension and copied the launch.json and tsconfig.json and pasted in my extension file 
also copied the new precompile and post compile json values to package.json

Its working now at my end but this should be covered in editor debugger not allowing such type of behaviour.

**Comment by weinand** [comment]
@shanalikhan so you are saying that after upgrading to VS Code 1.6 your breakpoints were no longer hitting the correct line?

If breakpoints were not hitting the correct line this typically means that your TypeScript source has become out of sync with the generated JavaScript. Did you rebuild your extension after upgrading to VS Code 1.6?
Did you verify that building (transpiling) your extension actually worked after the upgrading to VS Code 1.6? 

Since upgrading "tsconfig.json" and "launch.json" seems to have fixed the issue, can you give us the changes of those two files that seem to have fixed the issue?

Thanks a lot!

**Comment by weinand** [comment]
no response -> closing

**Comment by sryze** [comment]
I have the same problem. Attempted to debug an vscode-cordova to find out why breakpoints are not working there and failed because breakpoints don't work when debugging extensions either.

VS Code 1.8.1
