### ISSUE TITLE
Auto imports not working for Angular project

### ISSUE THREAD

**Issue by davidjpfeiffer** [microsoft/vscode#136130]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.61.2 (Universal)
- OS Version: MacOS Big Sur 11.6

Steps to Reproduce:

1. Create a new Angular 11 project using the Angular CLI
2. Attempt to include the [BrowserAnimationsModule](https://angular.io/api/platform-browser/animations/BrowserAnimationsModule) in the app module
3. VSCode fails to locate the BrowserAnimationsModule
<img width="806" alt="Screen Shot 2021-10-29 at 1 46 45 PM" src="https://user-images.githubusercontent.com/8846738/139499733-6875b5bb-1b5e-4c04-9982-e82377457694.png">

**Comment by emtei** [comment]
I'm able to recreate this issue also with latest @angular/cli (version 12.2.12).
Correct import statement should be:

```typescript
import { BrowserAnimationsModule } from '@angular/platform-browser/animations'
```

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

You can also try upgrading your workspace to use `typescript@next` by installing [this extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next) to see if that fixes the problem

If you still see the issue after trying both of those, please share a minimal example project that demonstrates the issue so that we can investigate

**Comment by davidjpfeiffer** [comment]
@mjbvz Yes, I get the same behavior in the latest VS Code insiders build with all extensions disabled. Installing the JavaScript and TypeScript Nightly extension did not solve the problem.

**Comment by mjbvz** [comment]
Please share a minimal example project that demonstrates the issue so that we can investigate

**Comment by MultipledMe** [comment]
Maybe you can upgrade your functools?Pile them in the location of Visual Catalogue

**Comment by mjbvz** [comment]
Closing as we need more information to investigate this
