### ISSUE TITLE
Using vs code to create uwp apps

### ISSUE THREAD

**Issue by disklosr** [Microsoft/vscode#13629]
Any plans on having vs code support the UWP platform so we can use it as a lightweight IDE for developing / debugging apps?

**Comment by zeroskyx** [comment]
Now that the new iteration of UWP works with .NET Standard 2.0 -- do you have any news on the topic?

**Comment by chrisdias** [comment]
Hi -

Sorry, we don't have anything on our roadmap for building UWP apps with VS Code. The Visual Studio IDE is certainly the best tool for building these types of applications today.

**Comment by MikeKovarik** [comment]
Please add this to the roadmap, because the big Visual Studio is clearly built around C# and JS is not a first class citizen. The debugger and development tools are pain to use (compared to lets say Chrome Dev tools) and the JS console takes a good second to attach itself into he app, which causes loss of the important logs and errors that occur before VS starts listening to them. Its awful. I wonder why noone wants to develop UWP apps.

**Comment by disklosr** [comment]
VS is certainly the best tool for developing .net core apps, but you can still do it in vs code. If we can have the same for other .net platforms that would be very welcomed.
