### ISSUE TITLE
onDidCloseTextDocument for preview pane has significant delay

### ISSUE THREAD

**Issue by anthonydresser** [Microsoft/vscode#13623]
- VSCode Version: 1.6.0
- OS Version: Mac 10.11.6

The onDidCloseTextDocument event seems to not fire for minutes after the closing of a preview pane, where as it works perfectly for normal text documents. Last time I tried, I timed it at taking 2 minutes and 30 seconds to fire after closing a preview pane. In my application I am dependent on this to clean up data that was being held for the preview pane.

Is this a bug? or is there a different way to detect when a preview pane specifically is closed to clean up data (a handler specific for content providers maybe)?

Repro located at https://github.com/anthonydresser/vscodeRedirectTest

Steps to Reproduce:

1. Open a document and use the `Test Redirect` command to open a preview pane
2. Put a breakpoint on the ondidclose handler in the testProvider
3. Close the preview pane

**Comment by jrieken** [comment]
That is intentional - for virtual document we run a cleanup every [3 minutes](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/node/mainThreadDocuments.ts#L80). If we don't find it to be shown in any editor anymore we dispose the model. 

So, the event will come but it is a document close event, not a preview pane closed event (which we track in #6941).
