### ISSUE TITLE
Turn off the cmd+click feature in terminal

### ISSUE THREAD

**Issue by zhaiyi000** [microsoft/vscode#136202]
Hello everyone, is there a way to turn off this feature now?
https://github.com/microsoft/vscode/issues/99924#issuecomment-648832402

![image](https://user-images.githubusercontent.com/3723951/85568408-547c1d80-b63a-11ea-9bcc-f4ddb12c55dc.gif)

**Comment by Tyriar** [comment]
You can disable the link hover with `"terminal.integrated.showLinkHover": false`, we don't plan on allowing disabling of cmd+click to activate links, just don't press cmd if you don't want to use it? Cmd+click doesn't conflict with any other feature.

**Comment by zhaiyi000** [comment]
@Tyriar Thank you for your reply.
It is not the problem about link hover. I select a path in the terminal, and then copy it with cmd+c, but often execute cmd+click by mistake to open the path directly.

**Comment by Tyriar** [comment]
@zhaiyi000 I guess just be a little more careful or slow down when you click. This would be like requesting to disable symbol navigation in the editor which would end up getting used by maybe a handful of people but everyone ends up seeing a new setting in the settings editor, it also takes effort to maintain settings and it's not worth it because of that.
