### ISSUE TITLE
Show "implementations" code lens for TypeScript interface methods

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#136282]
The code lens feature shows both "references" and "implementations" for interfaces.
However, it only shows "references" for its methods.

It would be awesome if next to method "references" there was also "implementations".

![image](https://user-images.githubusercontent.com/2931520/139829851-4e496123-6199-46d7-a626-f219987a9db4.png)

This would be very useful for interfaces that have many methods and many references.

**Comment by alefragnani** [comment]
Hi @hediet ,
I have asked the exact same feature to the C# extension (https://github.com/OmniSharp/omnisharp-vscode/issues/4826) a couple of weeks ago.

In the meantime I decided to play with the APIs and ended up realizing that a single extension could probably work for any language, _with a few tweaks_. At least my proof-of-concept extension already supports TypeScript, C# and a few others 😬 .

In the end, I think those `References` and `Implementations` CodeLens should be a _basic_ VS Code feature (just like `Go to Symbol`/`Outline` is), instead of provided by each language extension. I mean, the language extension already provides the data, so VS Code could simply read it and translate.

Thank you

**Comment by mjbvz** [comment]
This is how we originally implemented the feature. However it adds a lot of noise so I changed the lens to only show on the parent type

**Comment by hediet** [comment]
@mjbvz is there a setting for this? I think that being able to directly jump to implementations by just using the mouse is very useful.

**Comment by hediet** [comment]
I think about the missing implementations code-lens almost every other day.
Can I convince you to reconsider adding a setting to show the implementations code-lens for interface methods/abstract methods?

**Comment by mjbvz** [comment]
@hediet Yes as long as it's behind a setting
