### ISSUE TITLE
Load snippets dynamically

### ISSUE THREAD

**Issue by juli1** [microsoft/vscode#136394]
As of today, snippets should be specified as a contribution point in the `package.json` file. What I would need is to have the ability to dynamically load snippets based on the user context. Have the ability to add/remove snippets for a given user would be really helpful.

I did not see the ability to add them (but implement quickpick), it would be awesome to also load them directly to use the `prefix` functionality and suggest the snippet as the user writes the code.

If that feature already exists, apologies for creating this issue and would love to know how to proceed.

Thanks,

**Comment by jrieken** [comment]
For that you should implement a `CompletionItemProvider` - that will give you the ability to dynamically suggest snippets as the user types. Tho, you aren't part of the "Insert Snippet" quick pick and the snippet tab completion because that requires sync computation. See https://github.com/microsoft/vscode-extension-samples/tree/main/completions-sample for a completions sample
