### ISSUE TITLE
Install specific version of extension using workbench.extensions.installExtension

### ISSUE THREAD

**Issue by jeanp413** [microsoft/vscode#136313]
Would be great if we can install a specific version of an extension using `workbench.extensions.installExtension`
```
vscode.commands.executeCommand('workbench.extensions.installExtension', 'publisher.my-extension@0.1.0');
```

**Comment by sandy081** [comment]
May I know the use case? And what happens if user has auto update enabled?

**Comment by jeanp413** [comment]
@sandy081 I have an extension that reads a file where the user can specify extensions id (maybe with version specified) required for his workspace. My extension provides diagnostics and a quick action to install missing extensions using `workbench.extensions.installExtension` command.
If the user has auto update enabled, then sure the extension will be updated, but this could be easily detected and show a notification teling the user if he's installing a specific version of an extension, he would want to disable auto update.
Also, the cli already supports installing a specific version of an extension with `--install-extension` argument, so it would be good to have the same behavior for `workbench.extensions.installExtension`

**Comment by sandy081** [comment]
Yes, one can install a specific version using CLI. But there is an open issue - that extension gets auto updated - this is due to the current limitation that storage is not accessible in CLI. We shall not surface the same here. So can you please update the PR to disable auto update when version is passed to the above command?

Here is the method that does that

https://github.com/microsoft/vscode/blob/45fdad3a10d437fb0a45cc008eecca7c35021fb2/src/vs/workbench/contrib/extensions/browser/extensionsWorkbenchService.ts#L1391

You can make this as a service method that can be accessible from above command invocation.

**Comment by TylerLeonhardt** [comment]
```
vscode.commands.executeCommand('workbench.extensions.installExtension', 'christian-kohler.npm-intellisense@1.3.1');
```
works as expected!

<img width="772" alt="image" src="https://user-images.githubusercontent.com/2644648/151622383-0eaf1604-92f3-456c-bf61-f407f9bc1e94.png">
