### ISSUE TITLE
로그인 동기화

### ISSUE THREAD

**Issue by janghochoi** [microsoft/vscode#136320]
로그인 했는데
자꾸 로그인하여 설정 동기화 하라고 해요
![Untitled-2](https://user-images.githubusercontent.com/3489897/139970664-81a62027-187d-4860-b028-2c31e4f28757.png)

**Comment by JacksonKearl** [comment]
이 문제를 만들어 주셔서 감사합니다!

그러나 설명은 영어로되어 있지 않기 때문에 우리가 그것을 작업하기가 어렵습니다. 당신이 할 수있는 경우, 영어로이 문제를 편집하시기 바랍니다. 새 주석을 추가하거나 새 문제를 만들지 말고 기존 문제를 편집하십시오.

안타깝게도 자동 번역 서비스는 소프트웨어 문제에 대해 효과적으로 전달하는 데 필요한 기술 언어를 처리할 수 없으므로 번역을 위해 당사의 기술에 익숙한 인간 번역기를 찾는 것이 좋습니다.

그렇지 않으면 이 문제는 번역이 필요한 것으로 표시되었으며 커뮤니티 구성원이 번역을 도울 수 있습니다.

---
Thanks for creating this issue!

Unfortunately, as the description is not in English, it's hard for us to work on. If possible, please edit the original issue to be in English.

In our experience, automatic translation services are not able to handle the technical language needed to effectively communicate about software issues, so we recommend finding a human translator who is familiar with our technology to help.

Otherwise, we have marked this as needing translation and a community member may be able to help out.

**Comment by CodeCrazy-ywt** [comment]
Google Translate:
I logged in, but it keeps telling me to log in and sync settings￼

**Comment by vuppalaprasanth** [comment]
Settings sync issue is coming up again. 
it is happened again from 1.61 for me.
