### ISSUE TITLE
vscode shows how to move inline content through the keyboard when hovering

### ISSUE THREAD

**Issue by askfiy** [microsoft/vscode#136494]
I used neovim plugin in vscode to improve my work efficiency, but I encountered a problem. For example, when I type gh to show hovering, I cannot move the scroll bar of this inline window through the keyboard

![](https://images-1302522496.cos.ap-nanjing.myqcloud.com/img/er.gif)

As shown in the picture above, for the first time I use the mouse to move the inline scroll bar is so easy. But the second time I use the keyboard, I don't know how to move the inline scroll bar. Please tell me what to do, thank you very much

Or I want to know what the vscode keyboard command is to change the inline window, so that I can use this command to move the scroll bar of the small window by myself

**Comment by Tyriar** [comment]
Can run the show definition preview hover command to get keyboard focus in the hover but up/down/page up/page down don't seem to work in it currently.

**Comment by aiday-mar** [comment]
Hi thank you for filing this issue. You can now use the `Show or Focus Hover` action in order to show a hover the first time it is called and on second call, focus it. Once the hover is focused you can scroll the hover horizontally and vertically if there are scrollbars using the arrow keys. The default keybindings for this command are `cmd + k, cmd+ i`. To do this you need to trigger though the keybindings (not through the command palette because the hover will disappear when the command palette appears).
