### ISSUE TITLE
Autosave overrides currently open file

### ISSUE THREAD

**Issue by Nighthawk22** [Microsoft/vscode#13646]
- VSCode Version: 1.6
- OS Version: macOS Sierra 10.12

Steps to Reproduce:

1. Enable autosave with 10sec delay
2. Open a file and change something
3. Switch to another file without saving
4. On auto save the open / active file gets overriden by the file which is currently saving.

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by Nighthawk22** [comment]
Ohh it seems to be coming from the js-css-html formatter extension. After uninstalling the extension it does not happen anymore. I will open a ticket there.
