### ISSUE TITLE
Problem with unexpected token with many exstensions vscode

### ISSUE THREAD

**Issue by pierre1590** [microsoft/vscode#136537]
Does this issue occur when all extensions are disabled?: Yes/No
No

- VS Code Version: 1.62 
- OS Version: Windows 11

Steps to Reproduce:
I I can't install many extensions because I have a problem like this: "Unexpexted token".   
mainThreadExtensionService.ts:95
Activating extension 'eamodio.gitlens' failed: c:/Users/Piero/.vscode/extensions/eamodio.gitlens-11.6.1/dist/gitlens.js: Unexpected token (1:11986)

([img]https://i.ibb.co/WtBQRvx/console-errors.jpg[/img])
1.
2.

**Comment by pierre1590** [comment]
How can I solve the problem?

**Comment by alexdima** [comment]
@pierre1590 It looks to me that you have installed an extension which breaks all other extensions (possibly by setting up a babel `requirejs` interceptor). All extensions execute together on a single nodejs process, so in order to narrow down the possible problematic extension, please try the following:
* run `F1 > Help: Start Extension Bisect`
* (this will restart VS Code with half of your extensions disabled)
* try to do the steps which reproduce the problem
* if the problem reproduces, click "This is bad" (this narrows down the problematic extension to the half which was enabled)
* if the problem does not reproduce, click "Good now" (this narrows down the problematic extension to the half which was disabled)
* these steps will repeat until the problematic extension is found

| initial | step | final |
|---|---|---|
| ![image](https://user-images.githubusercontent.com/5047891/101918658-e9170f80-3bc9-11eb-9977-857baa291937.png) | ![image](https://user-images.githubusercontent.com/5047891/101918683-ef0cf080-3bc9-11eb-9f9e-98b0177991b2.png) | ![image](https://user-images.githubusercontent.com/5047891/101918706-f502d180-3bc9-11eb-8c86-e56355958bd4.png) |

**Comment by pierre1590** [comment]
When I press the F1 key I don't see the suggested command

**Comment by pierre1590** [comment]
![VSCode F1](https://user-images.githubusercontent.com/3288682/140712990-f5d1080e-e8d2-47e2-a6df-ec7d0ebc1b54.jpg)

**Comment by pierre1590** [comment]
Now it functions
![Error VSCode](https://user-images.githubusercontent.com/3288682/140713685-3ed39f59-b005-4588-b773-48f235d4fa74.jpg)
t

**Comment by pierre1590** [comment]
What should I do now?

**Comment by pierre1590** [comment]
Nothing works, every time I repeat the loop with bisect it shows me an error at the end, every time it is a different extension.

**Comment by pierre1590** [comment]
@alexdima I've solved.

**Comment by alexdima** [comment]
@pierre1590 Thank you for following up. Can you please leave a note here regarding what the root cause was, such that others that run into this can benefit?

**Comment by pierre1590** [comment]
@alexdima  I uninstalled all extensions, restarted VSCode and then installed only the extensions I need.
