### ISSUE TITLE
Suggest to convert eslintrc to ES6 module, which doesn't work

### ISSUE THREAD

**Issue by thany** [microsoft/vscode#136513]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.62
- OS Version: Windows 10

Steps to Reproduce:

1. Make a new project with eslint. Anything at all will do fine.
2. Making sure any other eslint configs don't already exist, make an `.eslint.js` file, like so:

```javascript
module.exports = {
  // ...
};
```

3. Observe the warning on the very first character of this file:

> File is a CommonJS module; it may be converted to an ES6 module.

No, it may not be. This warning is incorrect. ESlint doesn't parse ES6 modules:

```
Oops! Something went wrong! :(

ESLint: 7.32.0

C:\[...]\.eslintrc.js:1
(function (exports, require, module, __filename, __dirname) { export default {
                                                              ^^^^^^

SyntaxError: Unexpected token 'export'
```

Please note that:

* I do not want to disable javascript validation
* I do not want to completely disable this particular hint for all files.

I know of the existence of #47299 which suggests the above, disabling this warning for *every* CommonJS file, but it should only be disabled on files that cannot be supported as ES6, such as `.eslint.js`. Possibly others as well.

**Comment by mjbvz** [comment]
I think the suggestion from #47299  is still correct. We can't tell how the file will be used and don't want to try guessing this based on filenames, so we ultimately leave it up to users to decide if they use the suggestion or not (or if they want to hide it)

I suspect eslint will start supporting native modules at some point in the future as well since the ecosystem seems to be moving in that direction
