### ISSUE TITLE
[icon-themes] Support for folder / directory names in file associations (Icon themes)

### ISSUE THREAD

**Issue by SNDST00M** [microsoft/vscode#136656]
#12493 specifies globs in file associations, but I'd really like to match based on folder name as well.

For example, Ember uses `config/environment.js` which in a perfect world the File Icon API would consume into:
```html
<div class="monaco-icon-label file-icon environment.js-name-file-icon js-ext-file-icon ext-file-icon config-dir-file-icon javascript-lang-file-icon file-icon">
<!-- ::before -->
</div>
```
File icon packs would then just do this: `{ "config/environment.js": "../icons/ember.svg" }`.

**Comment by aeschli** [comment]
Good suggestion. Happy to take a PR.

**Comment by SNDST00M** [comment]
I can start work on this STAT, which files need updating?

**Comment by aeschli** [comment]
Yes that one hopeful is used by everyone.
The css rules are created in https://github.com/microsoft/vscode/blob/main/src/vs/workbench/services/themes/browser/fileIconThemeData.ts

**Comment by SNDST00M** [comment]
We do need to agree for a syntax on this - is `<directory>/` prefix okay for all cases - folderNames folderNamesExpanded fileExtensions fileNames?

**Comment by aeschli** [comment]
I'm fine with allowing it for all. 
One thing to pay attention to is what happens if there are multiple associations that match a resource name/ path.
The current rule is:
A file name match is preferred over a file extension match which is preferred over a language match.
This is implemented by the number of css classes that are matched.

The question is how folder matches are treated:
- `folder/name` is stronger than just `name`
- `folder/extension` is stronger that `extension`, but does it beat `name`?

**Comment by SNDST00M** [comment]
I also do want to propose a "./" prefix for root files like Heroku's `./app.json`. Is there a way to implement that?
