### ISSUE TITLE
Option To Disable Extension Pack Recommendations

### ISSUE THREAD

**Issue by atom0s** [microsoft/vscode#136644]
When opening certain file types (ie. C++ > .cpp) VSCode is now recommending extension packs. I do not want this or need this. I don't mind VSCode offering suggestions for a file type I don't have an extension for currently, but these packs are overkill and unwanted. Every time I open VSCode and open a .cpp file, as an example, I get recommended a C++ pack with a handful of Microsoft-specific things.

**Comment by gjsjohnmurray** [comment]
See https://github.com/microsoft/vscode/issues/136301#issuecomment-958201119

**Comment by atom0s** [comment]
I am asking for the option to never see said popup to begin with. Having to do this every time it wants to pop up is not ideal. 

Having a setting to just disable pack recommendations altogether is the goal.

**Comment by gjsjohnmurray** [comment]
Looks like it may already be possible to disable all recommendations:

```json
"extensions.ignoreRecommendations": true
```

**Comment by atom0s** [comment]
As I said in the main post, I don't mind VSCode recommending extensions for unknown/unhandled file types, that is fine. I just don't want 'extension pack' recommendations. Especially if I have something handling the file already.

**Comment by sandy081** [comment]
>  Especially if I have something handling the file already.

Can you please mention which extensions you already installed for the file type VS Code is recommending extensions?

**Comment by atom0s** [comment]
So far the two I've noticed have been:

  - .cs (C#)
    - Gets recommended the C/C++ pack at random. Does not seem to have any consistent reason but is what is suggested.
  - .h, .hpp, .c, .cpp
    - Gets recommended the C/C++ pack.

In both cases, I already have extensions installed to handle these file types. Both of which are the Microsoft offered language support said languages. 

  - C# -- https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.csharp
  - C/C++ -- https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools

Along with some other additional helper extensions for each language.

**Comment by sandy081** [comment]
Thats bizarre. The extension pack `ms-vscode.cpptools-extension-pack` that we recommend for C/C++ includes 13 extensions. It seems, we check for the existence of this extension pack and if it does not exist, we recommend this pack even if user has `ms-vscode.cpptools` extension installed. There are two problems here:

1. IMO this extension pack includes too many extensions for language recommendations
2. If we want to recommend an extension pack then it shall be configured with a primary extension and we shall not recommend the pack if user has this primary extension installed.

CC @isidorn @chrisdias

**Comment by isidorn** [comment]
@WardenGnaw @bobbrow might you have more context why the C++ extension pack has so many off topic extensions. LiveShare? Doxygen documentation generator?

@sandy081 we could also just say we do not recommend an extension pack if at least one of the extensions from the pack is installed. That would also motivate extension packs to be lean.

**Comment by WardenGnaw** [comment]
Adding @sean-mcmanus @michelleangela who helped published the `cpptools-extension-pack` and might know why each extension is included in the extension pack.

**Comment by jureid** [comment]
In the C++ extension pack, these are the C++-specific extensions:
- "ms-vscode.cpptools",
- "ms-vscode.cpptools-themes",
- "twxs.cmake",
- "ms-vscode.cmake-tools"
- "cschlosser.doxdocgen" (addresses a common feature ask for C++: https://github.com/microsoft/vscode-cpptools/issues/5683)
 - "jeff-hykin.better-cpp-syntax"

These are the extensions that aren't specific to C++ (Remote Development, GitHub PR & Issues, LiveShare)
- "ms-vscode-remote.remote-wsl",
- "ms-vscode-remote.remote-containers",
- "ms-vscode-remote.remote-ssh",
- "github.vscode-pull-request-github",
- "ms-vsonline.vsonline",
- "ms-vsliveshare.vsliveshare",
- "ms-vsliveshare.vsliveshare-audio"

The reason we included the remote development pack is that most C++ developers are targeting multiple platforms, and many C++ customers we talk to are drawn to VS Code over other C++ IDEs/editors specifically for the remote capabilities.

We included GitHub PR & Issues and LiveShare to support collaborative C++ development scenarios. 

FWIW, I've been monitoring how many customers uninstall each of the extensions in the extension pack. The numbers are pretty consistent across the board -- i.e. there aren't more customers uninstalling LiveShare than cpptools. There are actually slightly more customers uninstalling cpptools than LiveShare (after installing the C++ extension pack).

That being said, I'm open to removing some of the non-C++ specific extensions based on this feedback and two reviews we've gotten for the extension pack complaining about LiveShare. My vote would be to keep the remote development extensions because I think they're super relevant for C++ developers.

I also agree that we should not recommend the C++ extension pack if cpptools is already installed!

**Comment by atom0s** [comment]
I'm happy to see this is being discussed, but we're kind of moving away from my actual point/intent with this feature request.

I'd like the option to disable VSCode from recommending 'extension packs'. I don't want these packs.

I do not mind if VSCode recommends me a specific individual extension for an unhandled file type like it worked before, but I do not want packs recommended.

**Comment by isidorn** [comment]
@jureid thanks for providing more details. My feeling is that users are not motivated enough to uninstall extensions, they are also not sure if something will stop working. Thus the uninstall numbers are not strong.
Since VS Code tries to be minimalistic in nature, I suggest that we also try to keep our extension packs lighter weight.
If you would like to keep the remote development since they are relevant for C++ devs that makes perfect sense for me. However as you suggest I would remove the the non C++ specific extensions.

@sandy081 removing extensions from an extension pack will have no effect on the users that already installed the extension pack in the past (those extensions will not get uninstalled right)? Just double checking.

And as I mentioned above I think this simple heuristic "we do not recommend an extension pack if at least one of the extensions from the pack is installed" would solve @atom0s problems since we do not want to stop recommending extension packs in general.

Thanks

**Comment by atom0s** [comment]
> since we do not want to stop recommending extension packs in general.

I am having a hard time understanding why this is such a problem to request that this be able to be turned off. I am not saying this needs to be removed, and I'm not saying this feature request needs to be default-on. Add the option, leave it off by default, let me manually opt into it. Just like how the setting for recommended extensions is already.

It's odd to me that there is an option for general extension recommendations, but it's for some reason a big deal to add another (or even extend the existing option) to have the choice to disable pack recommendations.

So again, my suggestion is:

  - Add an additional settings option to 'ignore extension pack recommendations'.

This can be off by default. This can be fully manually opt-in. I don't mind. 
I just would like to have the ability to not get recommended things I don't want.

You could even make the existing option have multiple choice options such as:

  - Disable all extension recommendations. _(Which would disable single and pack recommendations.)_
  - Disable pack recommendations. _(Leaves single per-file-type recommendations enabled. Disables packs.)_
  - Disable non-pack recommendations. _(Leaves pack recommendations on, disables individual recommendations.)_

**Comment by isidorn** [comment]
@atom0s this is a fair request, but not something we would do immediately until we get more user feedback.
We will first fix the issue we outlined above before adding this.
Thanks for your feedback!

**Comment by Shirk** [comment]
Well here's your user feedback from a fellow VSCode user with the same issue: please allow us to disable the recommendations. 

No-one has an issue with how Extension-Packs for right now (except for the whole VSCode developer team internally it seems). But please try to be a tiny bit enduser-first here - all we ask for is a checkbox (which would be off by default) reading "don't show recommended extensions" and done. 

Doesn't need a gigantic redesign of your whole Extension ecosystem. 
You completely blew the OPs issue out of context and created a different issue from it that should rightfully be tracked in a separate issue while the original request is being dealt with.

**Comment by gjsjohnmurray** [comment]
> all we ask for is a checkbox (which would be off by default) reading "don't show recommended extensions" and done.

@Shirk this already exists as a setting:

```json
"extensions.ignoreRecommendations": true
```

Or did you mean to write that you want to have **extension** recommendations but not **extension pack** recommendations?

**Comment by sandy081** [comment]
> removing extensions from an extension pack will have no effect on the users that already installed the extension pack in the past (those extensions will not get uninstalled right)? Just double checking.

Yes, we do not uninstall extensions if they are removed from the pack.
