### ISSUE TITLE
Error while registering log channel

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#136732]
Seen this often in integration tests and also locally when running them. It is hard to tell if this is an error that is critical to the system or not.

```
Error while registering log channel file:///Users/bpasero/Development/Microsoft/vscode-electron-13.x/.build/logs/integration-tests/renderer1.log Timed out while waiting for file to be created
```

/cc @alexdima

**Comment by sandy081** [comment]
This error is a valid error if workbench is active otherwise I suspect that I am polling for log file existence even after workbench is disposed. Fixing that case.

**Comment by bpasero** [comment]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=142168&view=logs&j=4d2898ab-dfbe-557e-92e7-aaac158fdd2f&t=dccbe8b6-2cf2-56ce-ca99-720e7791a9c0&l=1174

**Comment by sandy081** [comment]
This seems to be a valid error because the renderer log is not created. I also checked in the logs folder (artifacts) of above build, and it seems renderer log does not exist at all. 

It seems we are not creating the renderer log when running tests:

https://github.com/microsoft/vscode/blob/e33c0c34cc9eb5e6a35391ef3d13f042b855c929/src/vs/workbench/services/log/electron-sandbox/logService.ts#L17-L29

It seems you have added this, May I know why? Can we enable the renderer log in tests?

https://github.com/microsoft/vscode/commit/7ecb5821cdc3035a54280265dee4ccc8ef1cdfd4

**Comment by bpasero** [comment]
@sandy081 when running extension tests in CI we want the output of the run printed directly to the console the tests are running in to get nice output with colorization.

Nevertheless, this is a great catch and indeed I see no renderer log being created in CI runs on Azure. If we bring it back we have to be careful to only log into the file but not log into devtools, otherwise all output is duplicated. Can we do that?

**Comment by sandy081** [comment]
> If we bring it back we have to be careful to only log into the file but not log into devtools, otherwise all output is duplicated. Can we do that?

Sure its simple & done - please check the last commit.

**Comment by bpasero** [comment]
👏
