### ISSUE TITLE
Hover on the "Source Action" menu item can also reveal the sub-menu (similar to "Peek")

### ISSUE THREAD

**Issue by nickzhums** [microsoft/vscode#136735]
Based on past survey customer feedback, Java developers have constantly mentioned that 
- Getting to the sub-menu in source-action takes too many clicks
- The sub-menu is hard to find

Many Java developers come from traditional IDE background and they like the menu with straightforward options.

By examining the current VS code menu, we see that hovering on "peek" can reveal the next-level menu, we propose that "Source Action" can also support the same - thanks!

![image](https://user-images.githubusercontent.com/56864335/140887623-71b99b64-1954-4652-848d-a0e75e563b74.png)

**Comment by egamma** [comment]
Actually the same should be done for the 'Refactor...' menu.

**Comment by jrieken** [comment]
It is more tricky than "Peek" because source actions and refactorings are computed dynamically, e.g at the point of clicking "Source Action..." we don't know them yet. So, this would require some kind of dynamic submenu with first shows "Loading..." and finally shows the actual items (or none). Adding @sbatten to check if update-while-showing is possible, esp. for native menus

**Comment by mjbvz** [comment]
Thanks for the info @sbatten!

This is already being tracked by #48589
