### ISSUE TITLE
Track highlights across multiple split editors

### ISSUE THREAD

**Issue by SailorMax** [Microsoft/vscode#13673]
Can you add mode to Split Editor when highlighted selection of one half also highlights on another?
For example, on left half you can have list of some special words. You can just select them one by one and quickly find all places where they are on right half.

thank you.

**Comment by alexandrudima** [comment]
To keep the number of issues in our inbox at a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: we look at the number of votes the issue has received and the number of duplicate issues filed. Thank you for your time and understanding.

If you disagree and feel that this issue is crucial: we're happy to listen and to reconsider.
