### ISSUE TITLE
`window.showInputBox` should show which extension triggered it

### ISSUE THREAD

**Issue by Merlin2001** [microsoft/vscode#136856]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:
Version: 1.62.1 (user setup)
Commit: f4af3cbf5a99787542e2a30fe1fd37cd644cc31f
Date: 2021-11-05T10:57:55.946Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0

- OS Version:
OS: Windows_NT x64 10.0.19043

### Steps to Reproduce

1. Install @ankitbko's [Azure DevOps Pull Requests](https://marketplace.visualstudio.com/items?itemName=ankitbko.vscode-pull-request-azdo) extension
2. Don't follow the guide to login, instead close VS Code
3. Start VS Code

VS Code will now show the following Input Box: 

![`Please provide PAT (Press 'Enter' to confirm or 'Escape' to cancel)` ](https://user-images.githubusercontent.com/13134791/141114540-cf043b42-e47d-4add-a7cd-d2ce173f9931.png)

The problem is that there is _no hint whatsoever_ which extension opened that input box, so in my case it took me ages to find out (by accident) that this was due to the AZDO extension. I have filed a [PR for the extension](https://github.com/ankitbko/vscode-pull-request-azdo/pull/62) to have the extension name be prepended to the input box message in the meantime.

But I think a better and more general solution would be to **append the extension name in square brackets after the prompt**:
`Please provide PAT (Press 'Enter' to confirm or 'Escape' to cancel) [Azure DevOps Pull Requests]`

**Comment by gjsjohnmurray** [comment]
Instead of appending text to every prompt, maybe add an Info codicon somewhere which the user can hover over or click to discover the originating extension.

**Comment by TylerLeonhardt** [comment]
Couple things:

1. This extension (and really any extension) shouldn't prompt out of the blue. You should have taken an explicit action to get this quick pick and thus this feature request wouldn't be needed.
2. For this particular case, this extension should be using our Authentication APIs which would ensure ^^^^ this happens.

I do like the info codicon idea though... because I'm sure there are plenty of extensions that are doing similar things. I'll assign it to the Backlog Candidates to see if other folks feel the same way about quick picks.
