### ISSUE TITLE
[1.6] Extensions can not be installed with File | Open File...

### ISSUE THREAD

**Issue by jeffyoung** [Microsoft/vscode#13684]
- VSCode Version: 1.6
- OS Version: Win 10

Steps to Reproduce:

1. With an existing extension VSIX file, try to 'install it' with File | Open File...
2. The "The file will not be displayed in the editor because it is either binary, very large or uses an unsupported text encoding" error is displayed in VS Code instead of the extension being installed.

![file-vsix](https://cloud.githubusercontent.com/assets/2796865/19353116/4b71c344-9130-11e6-8f9c-5a9dbb9e9b5e.png)

Works as expected in 1.5.3.

**Comment by isidorn** [comment]
Somebody seems to have broken this, I remember it was working the last time I touched it :)

**Comment by joaomoreno** [comment]
This is deprecated.

You can use the context menu in the extensions view:

![image](https://cloud.githubusercontent.com/assets/22350/19377537/433282d8-91e7-11e6-94c4-4e8ce21c9c9c.png)

Or the global command:

![image](https://cloud.githubusercontent.com/assets/22350/19377540/48a47ffa-91e7-11e6-89a7-53005b1f0b1b.png)

**Comment by tbombach** [comment]
@joaomoreno Appreciate the info for this issue. In the future, could this kind of change be added to release notes? I know that the gallery is the main scenario for installing extensions, but it would be nice to know about changes to the sideloading process too. It's especially important, since an extension developer typically writes instructions for a sideload install process and is the first one that users ask if those instructions get out of date.
