### ISSUE TITLE
Fail to launch VS Code as a terminal process with env variables `ELECTRON_NO_ASAR`, `ELECTRON_RUN_AS_NODE`

### ISSUE THREAD

**Issue by wwlorey** [microsoft/vscode#136987]
Does this issue occur when all extensions are disabled?: Yes/No (I'm not sure how to disable extensions when launching VS Code this way)

- VS Code Version: 1.62.1 (repros for >=1.62)
- OS Version: MacOS 12.0.1

<details>
  <summary>More VS Code details</summary>

```
Version: 1.62.1
Commit: f4af3cbf5a99787542e2a30fe1fd37cd644cc31f
Date: 2021-11-05T09:23:14.144Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.1.0
```
</details>

Steps to Reproduce:

1. Launch VS Code from the command line with the following environment variables as shown: 
    ```
    ELECTRON_NO_ASAR=1 ELECTRON_RUN_AS_NODE=1 '/some/path/Visual Studio Code 1.62.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer)'
    ```
2. The terminal process ends without producing any output and exits with error code 1.

Expected Behavior:

1. Launch an earlier VS Code version (I used v1.61.2 here) in the same way as above: 
    ```
    ELECTRON_NO_ASAR=1 ELECTRON_RUN_AS_NODE=1 '/some/path/Visual Studio Code 1.61.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer)'
    ```
2. The node interpreter is successfully launched:
    ```
    Welcome to Node.js v14.16.0.
    Type ".help" for more information.
    > 
    ```

**Comment by alexdima** [comment]
@wwlorey I am sorry about the breakage, but this was necessary to address an elevation of privilege vulnerability. This is something we had to change for https://github.com/microsoft/vscode/issues/136771 (in order to address [CVE-2021-42322](https://msrc.microsoft.com/update-guide/vulnerability/CVE-2021-42322)). Starting with `1.62.1`, you need to also use a command line argument `--ms-enable-electron-run-as-node` together with `ELECTRON_RUN_AS_NODE`.
