### ISSUE TITLE
Live Share duplicates my existing MS account with a long email alias 

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#136984]
Steps to Reproduce:

1. Log into Settings Sync with Microsoft account
2. Login into Live Share with Microsoft account

Expected: Live Share uses existing email account.

Actual: Live Share adds a new account entry using my long email alias (*firstname.lastname@…*).

**Comment by TylerLeonhardt** [comment]
This is likely because the LiveShare extension doesn't provide the `profile` scope... but I'm wondering what other options there are in your JWT claims... maybe we can have a better fallback ordering here:
https://github.com/microsoft/vscode/blob/f8b17200c1318f0b58090445cc1a6338da426e4e/extensions/microsoft-authentication/src/AADHelper.ts#L572

**Comment by TylerLeonhardt** [comment]
This should be fixed now because we force having the `profile` scope.
