### ISSUE TITLE
In Visual Studio Code a folder with files are getting deleted after some time

### ISSUE THREAD

**Issue by pathfinder91** [microsoft/vscode#137026]
I am a new user of Visual Studio Code. The problem is when I create a folder for files, it gets deleted after a while. I have had this problem 5 times. Tried to solve it by resetting VSCode, but the issue persists. This problem, as i noticed, appears when on the left bottom side button "manage" gets notification "new code update available". after restarting  Visual Studio Code all work get deleted.
Here is an example and screenshot:
Unable to open 'lesson_5.html': Unable to read file 'd:\Microsoft VS Code\study\lesson_5.html' (Error: Unable to resolve nonexistent file 'd:\Microsoft VS Code\study\lesson_5.html').
![scr_1](https://user-images.githubusercontent.com/94166975/141438104-546da775-9720-47ff-86bd-2b6f3cbfb600.png)

**Comment by gjsjohnmurray** [comment]
Are you storing your files and folders within the same folder you install VS Code in? If yes, please don't do this. See #128634

**Comment by djmisterjon** [comment]
Also just a tips, if you always want to be sure vscode open the correct folder and workspace associate.
Always go to your folder first, and right click in folder and open **from your context menu.**
![image](https://user-images.githubusercontent.com/24865815/141464186-3d8ada48-9bce-4ce0-9007-69d40394c5da.png)

Because if you work will multiple project and you open vscode from shortcut icon, you will get hard time !

**Comment by pathfinder91** [comment]
> Are you storing your files and folders within the same folder you install VS Code in? If yes, please don't do this. See #128634

following your rrecommendations, i've reinstalled vs code, and put in different folders workspace and vscode itself. May be the problem will gone.
Thank you very much!
