### ISSUE TITLE
GitHub auth: Unable to paste auth token into status bar

### ISSUE THREAD

**Issue by tshmit** [microsoft/vscode#137134]
Issue Type: <b>Bug</b>

When signing in to Sync Settings I am taken to GitHub auth page, which redirects back to VSCode, but I find no way to paste the auth token into the status bar. 

See also [96363](https://github.com/microsoft/vscode/issues/96363), [96350](https://github.com/microsoft/vscode/issues/96350), [96313](https://github.com/microsoft/vscode/issues/96313)

<img width="1132" alt="Screen Shot 2021-11-13 at 2 12 54 PM" src="https://user-images.githubusercontent.com/1653258/141656761-3157fe8a-c4f0-4ff6-ba44-160c88ef17db.png">

VS Code version: Code 1.62.2 (Universal) (3a6960b964327f0e3882ce18fcebd07ed191b316, 2021-11-11T20:59:05.913Z)
OS version: Darwin x64 21.1.0
Restricted Mode: No

**Comment by tshmit** [comment]
I might add that when I attempt to clone my repo using VSC/PlatformIO the git log reports:
`> git clone https://github.com/tshmit/oled3.git /Users/ts/Documents/PlatformIO/Projects/oled3 --progress
Cloning into '/Users/ts/Documents/PlatformIO/Projects/oled3'...
remote: Repository not found.
fatal: Authentication failed for 'https://github.com/tshmit/oled3.git/'`

(p.s. when replicating the same clone attempt on a Windows machine I encountered no issues)

**Comment by TylerLeonhardt** [comment]
@tshmit yes we no longer have that because the redirecting back to VS Code should handle that for you. Is Settings Sync not working for you when it redirects back to VS Code?

You can see the accounts you're currently signed in to and if Settings Sync is on here in the bottom left:
![image](https://user-images.githubusercontent.com/2644648/141660846-d6425955-0c40-4b93-b850-44b440ad0a7a.png)

> using VSC/PlatformIO

What is this? Can you show me how you're cloning the repo? I don't think it's related to you logging in to github for settings sync...

**Comment by tshmit** [comment]
Yes, I'd have expected that it should work via the redirect back to VSC, and not require the manual token (which is what happens when I try the same thing from a Windows machine).
And yes, Settings Sync seems to be working:

<img width="184" alt="Screen Shot 2021-11-13 at 6 39 28 PM" src="https://user-images.githubusercontent.com/1653258/141662659-a11b0555-300d-41a0-ac84-c039abeba6a7.png">

PlatformIO is an extension used for embedded systems development. (My impression is it's quite popular among people doing such things) It provides a menu option to clone a repo:

<img width="172" alt="Screen Shot 2021-11-13 at 6 47 09 PM" src="https://user-images.githubusercontent.com/1653258/141662675-f8c5f93b-6dd9-40bc-bfa7-8a7f00675fb0.png">

 which then asks for the url of the GitHub repo. It then fails, reporting the authentication error indicated above.

That error message is why I assumed it was a problem related to the VSC/GH auth handoff, but based on your reaction it seems the problem may lie elsewhere.

Please let me know if you have any thoughts. If not, I'll continue to try...

Thanks very much!

**Comment by TylerLeonhardt** [comment]
Yeah based on the error message, I don't think that's related to VS Code's auth flow and since Settings Sync is on, the auth flow appears to be working.

I'd recommend opening an issue with that specific error message over in:
https://github.com/platformio/platformio-vscode-ide

I'm gonna close this since it appears to be an extension issue.
