### ISSUE TITLE
When VSC has no open folder, please have "Integrated Terminal" open in same default folder

### ISSUE THREAD

**Issue by kumueric** [Microsoft/vscode#13718]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T16:21:53.542Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: abusaidm.html-snippets-0.0.17, donjayamanne.python-0.4.2

Steps to Reproduce:

1.  File --> "Close Folder"
2. Push "Open Folder" & notice that VSC opens in a "default" folder [Now push CANCEL]
3.  View --> "Integrated Terminal" & notice that VSC opens "way up" in the user's home folder.

Please update VSC so that #3 opens into the same folder as #2 WHEN THERE IS NO OPEN FOLDER!

NOTE:  If you have specified "Open Folder," then View --> "Integrated Terminal" opens in the folder that you "Opened."  My request is for the case when there is NO OPEN FOLDER.

**Comment by Tyriar** [comment]
I'd prefer not to bring this in due to the fact that it makes the path that launches inconsistent depending on whether the workspace is empty or has a folder. I recommend installing the [Terminal Here](https://marketplace.visualstudio.com/items?itemName=Tyriar.vscode-terminal-here) extension to open the folder of the current file. If you need this to apply only when the workspace is empty I'd be glad to add it as an option on that extension, in which case file an issue [here](https://github.com/Tyriar/vscode-terminal-here/issues/new).
