### ISSUE TITLE
why the intellisense won't detect npm linked package?is this intentional

### ISSUE THREAD

**Issue by sdb7** [Microsoft/vscode#13710]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T16:21:53.542Z)
- OS Version: Windows_NT ia32 10.0.10240
- Extensions: abusaidm.html-snippets-0.0.17, akamud.vscode-javascript-snippet-pack-0.1.5, AndersEAndersen.html-class-suggestions-1.0.1, christian-kohler.npm-intellisense-0.1.3, danibram.theme-flatui-2.0.0, danwahlin.angular2-snippets-0.10.15, donjayamanne.python-0.4.2, ecmel.vscode-html-css-0.0.28, felixfbecker.php-debug-1.9.6, HvyIndustries.crane-0.2.1, mrmlnc.vscode-jade-snippets-1.0.1, mrmlnc.vscode-pugbeautify-1.0.2, mrmlnc.vscode-puglint-2.3.0, ms-vscode.csharp-1.4.1, ms-vscode.typescript-javascript-grammar-0.0.4, PeterJausovec.vscode-docker-0.0.6, robertohuertasm.vscode-icons-3.0.4, tushortz.theme-wildlife-0.0.3, Unity.unity-debug-1.0.4, UVBrain.Angular2-0.3.5

Steps to Reproduce:

1.
2.

**Comment by waderyan** [comment]
@sdb7 thank you for opening this issue. Can you do the following? 

Share the code where you are seeing this problem.  
Describe in a step by step process exactly how you see your problem. 
Describe what you expect to see. 
Share relevant screenshots and animations. 

Because of the amount of issues we receive we will need to close this issue until more info is provided.
