### ISSUE TITLE
Extension activated with MemFS despite capabilities flag when virtualWorkspaces is defined as false

### ISSUE THREAD

**Issue by tamuratak** [microsoft/vscode#137152]
Version: 1.63.0-insider (Universal)
Commit: 3bd29c1d6c6ef5b6265614def99b7257b671ae19
Date: 2021-11-12T12:39:26.447Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin arm64 20.6.0

Steps to Reproduce:

1. Install LaTeX Workshop https://marketplace.visualstudio.com/items?itemName=James-Yu.latex-workshop
2. Install MemFS https://github.com/microsoft/vscode-extension-samples/tree/main/fsprovider-sample
3. Execute `MemFS: Setup Workspace`
4. Open a file `t.tex`
5. LaTeX Workshop is activated despite capabilities flag when virtualWorkspaces is defined as false https://github.com/James-Yu/LaTeX-Workshop/blob/bce7c0bd57556ed860ba20afa7db1cab64167f10/package.json#L55-L60

Similar to #124594. However, my issue is not on debug sessions.

**Comment by tamuratak** [comment]
I have found that after the step `3. Execute MemFS: Setup Workspace`, if we reload the windows, then LaTeX Workshop is disabled.

**Comment by jrieken** [comment]
> virtualWorkspaces is defined as false

I am unsure if that has an effect on activation or not

**Comment by sandy081** [comment]
I assume you are running this command in a folder workspace where LaTeX extension is already enabled. After running the `MemFS: Setup Workspace` command, workspace enters into multi folder and virtual workspace mode without reloading the window. During this transition, we are restarting the extension host with the same set of extensions. 

Workspace trust feature handles it properly - during the transition it stops the extension host, update the enabled extensions and start the extension host.

https://github.com/microsoft/vscode/blob/31152fd902cf50ea37c2667ed4c6d57000c771d0/src/vs/workbench/contrib/extensions/browser/extensionEnablementWorkspaceTrustTransitionParticipant.ts#L41-L43

@aeschli you can also do the same while transitioning from normal workspace to virtual workspace and vice-versa.

Personally, I think it is not an often scenario to support. I would leave it up to you.

**Comment by tamuratak** [comment]
> I assume you are running this command in a folder workspace where LaTeX extension is already enabled.

I can reproduce the issue even after closing the current workspace and starting with no workspace. I think closing the current workspace and opening a new workspace is a typical scenario.


1. `Close Workspace`
2. Execute `MemFS: Setup Workspace`
3. Open a file `t.tex`
4. LaTeX Workshop is activated despite capabilities flag when virtualWorkspaces is defined

**Comment by aeschli** [comment]
With untrusted workspaces it's important to reload the extension host and restart all extensions for security reasons.

With virtual workspaces this is not crucial, that's why it is not done. It can happen that an extension is enabled when the extension host is started first on a non-virtual workspace.
When it is enabled, all contribution points including grammar, themes, commands are registered. 
In the steps above the extension is activated after we switch to a virtual workspace. We can't block the activation at that point as all contributions are already registered and these might depend on the activation (e.g. commands) 

Extensions should always check and listen for workspace/folder changes and disable functionality when there's a workspace/folder they cannot work with.

**Comment by aeschli** [comment]
Needs to be fixed in the extension: see https://github.com/microsoft/vscode/issues/137152#issuecomment-974045485
