### ISSUE TITLE
Show breakpoint data from multiple debug sessions

### ISSUE THREAD

**Issue by HampusAdolfsson** [microsoft/vscode#137435]
I am running two debug sessions at the same time for the same program (one in a simulator and one on hardware). When I set a breakpoint, the debug adapters return different results for it (different messages, and sometimes one of them fails to verify the breakpoint). Currently, only the message from one of the sessions/adapters is shown when I hover a breakpoint (no matter which session I have selected), and the breakpoint is shown as verified as long as it is verified in at least one session.

In my opinion, the hover message should depend on which session I have selected, like the variables and console views do. Also, when I select a session, I'd prefer if any breakpoints not verified for that session were shown as unverified.

**Comment by weinand** [comment]
related issue #126608

**Comment by hyangah** [comment]
I was about to file the exactly same issue in the context of https://github.com/microsoft/vscode/issues/135105#issuecomment-1007718607.
If this issue is addressed and VSCode can separate different debug sessions in the breakpoint pane like other UI components (stack, variables, debug console), we will be closer to the solution to communicate clearly about unverified breakpoints.

cc @suzmue @polinasok
