### ISSUE TITLE
Cannot initialize repository in source control

### ISSUE THREAD

**Issue by lorainemanlutac** [microsoft/vscode#137490]
Issue Type: <b>Bug</b>

It says that there is no git repository in the workspace although there is one. It should automatically be initialized, but even though I click the initialize repository button, it still does not work.

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T07:59:13.865Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

**Comment by lszomoru** [comment]
@lorainemanlutac, could you please share a bit more information about the folder structure?
What is the workspace folder that you are opening, and where exactly is the `.git` folder relative to the workspace folder?

**Comment by nedwors** [comment]
Seeing the same issue today. The integrated terminal (and external terminals) picks up on the git repository and allows for all git interactions.

This issue is happening across all of my folders - which are either Laravel installs or Laravel packages. For all folders, the `.git` folder is at the root.

I ran `brew update` earlier today, that's one factor I think might be playing into this somehow, but not sure how?

Version: 1.62.3
Commit: ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
Date: 2021-11-17T07:59:13.865Z (5 days ago)
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.1.0

**Comment by lorainemanlutac** [comment]
@lszomoru .git is in the root of the workspace folder which is an npm package. If it helps, this error shows from time to time, and I have to click the Restart Extension Host button to initialize the repository:
<img width="452" alt="Screen Shot 2021-11-24 at 12 07 21 PM" src="https://user-images.githubusercontent.com/34016309/143173199-9ec055da-b539-4965-aa88-b2042022b004.png">

**Comment by lszomoru** [comment]
@lorainemanlutac, thanks for the additional information. Does this error always occur when the git repository fails to initialise? Next time this occurs, can you please click on the "Open Developer Tools" button and share the error that you are seeing there? Thank you!
