### ISSUE TITLE
Unidentified update request

### ISSUE THREAD

**Issue by Joymaker** [microsoft/vscode#137438]
Does this issue occur when all extensions are disabled?: Unknown, I can't trigger it.

- VS Code Version: 1.62.0
- OS Version:  MacOS Big Sur 11.6

Issue: daily or so, Code pops up this message asking for my password: "An update is ready to install.  Code is trying to add a new helper tool."

This feels to me like a scary security hole. What helper tool? Is this an update to one of the extensions that I have already installed? If so, please name it!

I do not understand what I am giving my password to and I am very uninclined to do it. If in fact this is a worthy action, I feel that it really needs more explanation.

Steps to Reproduce: No action required

**Comment by TarunavBA** [comment]
@Joymaker Any [gifs](https://gifcap.dev) would be helpful

**Comment by Ludoohh** [comment]
<img width="370" alt="image" src="https://user-images.githubusercontent.com/94221849/143677121-9d1dff52-cd36-421e-8949-147d9b73d531.png">

I think that is the message received by the OP.

**Comment by deepak1556** [comment]
You are seeing the dialog because either the Application `Visual Studio Code.app` or the folder `~/Library/Caches/com.microsoft.VSCode.ShipIt` which is responsible for holding updates is not owned by your current user. Please make sure both these folders are owned correctly. An example of how to fix the ownership https://github.com/microsoft/vscode/issues/95534#issuecomment-620635814
