### ISSUE TITLE
"format document" tool insert space at wrong pos when using latin characters

### ISSUE THREAD

**Issue by smarq8** [microsoft/vscode#137617]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:Version: 1.62.3 (user setup)
Commit: ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
Date: 2021-11-17T08:11:14.551Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043
- OS Version: windows 10 home x64

Steps to Reproduce:
Using latin character somehow affect where to put space, its omited during character count or something else happen for buildin formating tool. After some investigation I found 2 options at .editorconfig cause this problem "cpp_indent_braces" and "cpp_space_within_parameter_list_parentheses" ( there might be similar issue with other but I do not test all of them).

In my example as in string is "błąd" then it ("format document" shift+alt+f) put space in the middle of strLen and right after \n
More in example below, at the left before formating and after at the right, in comment used parameters.

```
somefile.cpp
LOGF("błąd drukowania: %i\n",strLen); -> LOGF("błąd drukowania: %i\n ",strLen); // cpp_indent_braces=false only
LOGF("błąd drukowania: %i\n",strLen); -> LOGF( "błąd drukowania: %i\n ",strL en); // cpp_space_within_parameter_list_parentheses=true only and both
LOGF("bład drukowania: %i\n",strLen); -> LOGF( "bład drukowania: %i\n" ,strLe n); // both
LOGF("blad drukowania: %i\n",strLen); -> LOGF( "blad drukowania: %i\n", strLen ); // both

.editorconfig
cpp_indent_braces=false
cpp_space_within_parameter_list_parentheses=true
```

**Comment by jrieken** [comment]
It looks like the issue is caused by one of your installed extensions. All extensions execute together on a single nodejs process, so in order to narrow down the possible problematic extension, please try the following:
* run `F1 > Help: Start Extension Bisect`
* (this will restart VS Code with half of your extensions disabled)
* try to do the steps which reproduce the problem
* if the problem reproduces, click "This is bad" (this narrows down the problematic extension to the half which was enabled)
* if the problem does not reproduce, click "Good now" (this narrows down the problematic extension to the half which was disabled)
* these steps will repeat until the problematic extension is found

| initial | step | final |
|---|---|---|
| ![image](https://user-images.githubusercontent.com/5047891/101918658-e9170f80-3bc9-11eb-9977-857baa291937.png) | ![image](https://user-images.githubusercontent.com/5047891/101918683-ef0cf080-3bc9-11eb-9f9e-98b0177991b2.png) | ![image](https://user-images.githubusercontent.com/5047891/101918706-f502d180-3bc9-11eb-8c86-e56355958bd4.png) |

**Comment by smarq8** [comment]
during this process there was 2 behaviors, "there is no formater for "cpp" file installed" or corrupted formating

```
CPUs | Intel(R) Core(TM) i5-4460 CPU @ 3.20GHz (4 x 3193)
-- | --
GPU Status | 2d_canvas: enabled gpu_compositing: enabled multiple_raster_threads: enabled_on oop_rasterization: enabled opengl: enabled_on rasterization: enabled skia_renderer: enabled_on video_decode: enabled vulkan: disabled_off webgl: enabled webgl2: enabled
Load (avg) |  
Memory (System) | 11.85GB (7.32GB free)
Process Argv | --crash-reporter-id 49cb8ad2-84d3-4aed-8376-e46174a6dfb1
Screen Reader | no
VM | 0%
```

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200:30402083
vsaa593:30376534
vssld246cf:30401891
```

![screenshot 1637593618](https://user-images.githubusercontent.com/5141045/142885589-7f164dd4-b750-4a9e-841a-c9e51bfe05c1.png)
