### ISSUE TITLE
Extension in-app page width

### ISSUE THREAD

**Issue by regs01** [microsoft/vscode#137770]
New extension page within the app is way too narrow. This extremely tunneling view brings headache and nausea. It needs to be full width and without large fixed elements.
<img width="1920" alt="Code_2021-11-24_04-53-31" src="https://user-images.githubusercontent.com/10468217/143157805-b59be852-6f9c-4653-b341-1a814a7b450a.png">

**Comment by gjsjohnmurray** [comment]
https://github.com/microsoft/vscode/commit/d2ed4c8213f26306b5c7b7dbe693e2ca1b854d55 seems to have added this:

https://github.com/microsoft/vscode/blob/cdd975671e18fe63b9747b2a506baffd624637dc/src/vs/workbench/contrib/extensions/browser/media/extensionEditor.css#L12

On my 2560x1440 125%-scaled display using current Insiders:

![image](https://user-images.githubusercontent.com/6726799/143183512-9b7fbc3c-957d-47ed-91de-53664c954ac1.png)

/confirm

After using Devtools to disable that, then swapping to Changelog tab and back to Details (to redraw the webview):

![image](https://user-images.githubusercontent.com/6726799/143183697-5ce872b4-2a32-44e3-a3ad-1c13a14a88c0.png)

This reinstates the 882px max-width that the body of the webview has apparently had since 1.44 (https://github.com/microsoft/vscode/commit/10a794185481c6f4fa0e16145bc5048c6ef652c7)

Between 1.41 and 1.44 it was 780px (https://github.com/microsoft/vscode/commit/b5959b356c5a0fa7d410b70ed26a49fc4619121f)

**Comment by gjsjohnmurray** [comment]
Removing the 882px constraint I get this:

![image](https://user-images.githubusercontent.com/6726799/143185977-100ef55b-c2f5-4d27-b77e-949143cb4452.png)

**Comment by sandy081** [comment]
This change was intentional to align the contents in the center just like other editors like settings editor, markdown preview.,

@misolori any suggestions for max-width for extension editor?

**Comment by misolori** [comment]
We use `1200px` on the main welcome/getting started page but I think I'd be open to increase that for larger screens.

**Comment by sandy081** [comment]
Changed max-width it to 80% of the editor width, so bigger the screen bigger the width will be.

**Comment by regs01** [comment]
the more, the better
