### ISSUE TITLE
Terminal Tabs Are Centered And Don't Align

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#137710]
The buttons don't align anymore. (Todays Insider Build)

![recording](https://user-images.githubusercontent.com/2931520/143011266-1ad6bb80-0d96-439f-ada1-e9e3721449d5.gif)

**Comment by Tyriar** [comment]
Going to need some more repro steps, works fine for me and I don't think we've changed that:

![image](https://user-images.githubusercontent.com/2193314/143053774-53cf3d3a-0f3d-4602-894e-2e836fa5c8c9.png)

**Comment by Tyriar** [comment]
Actually I see this when running the web terminal smoke tests, some issue with initial layout of tabs UI?
<img width="269" alt="Screen Shot 2021-11-23 at 3 44 23 pm" src="https://user-images.githubusercontent.com/2193314/143146325-9c7bab8e-6b72-498a-9d92-ce2f7ace8517.png">

**Comment by Tyriar** [comment]
Saw this again:

![image](https://user-images.githubusercontent.com/2193314/143888756-a93bd6ee-5783-4ee0-b44a-41d1fc748031.png)

Resizing tabs list fixed it as expected

![image](https://user-images.githubusercontent.com/2193314/143888789-1589ec69-e059-4eda-a6ea-e5bbcacf44bf.png)

Probably caused by removal of rerender tabs - update class but don't replace list's contents
