### ISSUE TITLE
Regression - QuickInput created by `createInputBox` may show value of previous one created by `showInputBox`

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#137750]
Issue Type: <b>Bug</b>

Have an extension which prompts using `window.showInputBox`, then prompts again using one created by `window.createInputBox` and shown without having set its `value` property.

On today's Insider the second QuickInput initially displays whatever value the user entered into the first one, but if Enter is pressed the `onDidAccept` reports that `value` is blank.

On 1.62.3 the second QuickInput displays empty.

VS Code version: Code - Insiders 1.63.0-insider (ed3018f4310e906daa0a9119d997e75b8a38b879, 2021-11-23T05:33:39.595Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by gjsjohnmurray** [comment]
To reproduce, use quickinput-sample from https://github.com/gjsjohnmurray/vscode-extension-samples/tree/show-137750, invoke the 'Quick Input Samples' command, and choose 'showThenCreateInputBoxes' which this branch added.

![junk](https://user-images.githubusercontent.com/6726799/143145041-07bb5946-129d-4b41-bcea-beea683d34e5.gif)

**Comment by TylerLeonhardt** [comment]
This was caused by my fix to https://github.com/microsoft/vscode/issues/137279

in these commits:
https://github.com/microsoft/vscode/compare/59c53002de27a34712d72ec56ad29c8d9f92f1b7...bdc6162b1d40bfa5220490ddbc8369d2abc74481

I'm gonna try to get to the root of this tomorrow but if it's more involved, I may just revert that change so that this regression doesn't ship.

**Comment by TylerLeonhardt** [comment]
Reverted the 2 bad comments: 26fe37ca3d9dcc934ffcacd82443a38c9b192dd0 60c59ff641b2d0a378aafab55dc311eafb751008
