### ISSUE TITLE
There's no a way to close an editor tab with a shortcut in a browser based version

### ISSUE THREAD

**Issue by solomatov** [microsoft/vscode#137767]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.62.3
- OS Version: Google Chrome

Steps to Reproduce:
1. Open a browser vscode, i.e. https://github.dev/microsoft/vscode
2. Open README.md
3. Press Cmd+W
4. Instead of closing editor tab, it's prompted to close a browser window

**Comment by egamma** [comment]
This is the native browser behaviour, nothing VS Code can do against, sry.

**Comment by solomatov** [comment]
@egamma But what is your plan for dealing with it? Obviously, people in a browser would want to close editor tabs with a shortcuts. Did you try influencing Edge or Chrome to enable this shortcut?

**Comment by bolinfest** [comment]
@egamma I concede that it is unlikely that Google Chrome will allow a web page to override `cmd+w`. Incidentally, the feature request filed against Chrome in 2010 to allow this (https://bugs.chromium.org/p/chromium/issues/detail?id=33056) appeals to this use case in Comment 6: "I'm developing a completely web-based web IDE..."

That said, we have been experimenting with creating a Chrome extension for VS Code Web that would let users opt-in to a behavior where the background page of the extension would intercept `cmd+w` as follows:

- On a site like vscode.dev or github.dev, the background page of the Chrome extension would do something like the following to pump the keyboard event to the host page where it could be handled "naturally:"

```js
// useMacShortcuts is determined via `chrome.runtime.getPlatformInfo()`
const modifierKeys = {[useMacShortcuts ? 'metaKey' : 'ctrlKey']: true};
document.body.dispatchEvent(
    new KeyboardEvent('keydown', {
    ...modifierKeys,
    key: 'w',
    code: 'KeyW',
    keyCode: 87,
  }),
);
```

It appears there was a point in time where VS Code Web would not even acknowledge `cmd+w` under those circumstances, but that has long since been fixed: https://github.com/microsoft/vscode/issues/108788.

- On all other sites, the extension would call `chrome.tabs.remove()` to remove the tab, emulating the native Google Chrome behavior.

The extension has generally been working well for us so far, with two exceptions:

- It is a pain to set up. As best we can tell, the user has to manually configure the keybinding in `chrome://extensions/shortcuts` to be able to take advantage of it. This will become more tedious if we support overrides for more Chrome shortcuts, such as `cmd+t` and `cmd+shift+t`.
- Users may be confused when `cmd+w` no longer closes a VS Code Web browser tab: they must click on the X in the Chrome tab with their mouse to do so (arguably an accessibility issue, to boot).

If you have any ideas about other workarounds to make VS Code Web feel more like the desktop version [with respect to keyboard shortcuts], we are certainly interested to help out! The Chrome extension is the best we have come up with thus far.

**Comment by egamma** [comment]
@bolinfest thanks for chiming in with your insights. I've extracted them into a separate issue https://github.com/microsoft/vscode/issues/137972

**Comment by bpasero** [comment]
Things you can do to prevent the browser from "eating" Ctrl+W:
* install the URL as PWA app ("..." > More Tools > Create Shortcut...)
* set the website into fullscreen mode
