### ISSUE TITLE
Command line tool on OS X could be faster

### ISSUE THREAD

**Issue by wmertens** [Microsoft/vscode#13784]
- VSCode Version: 1.5.3
- OS Version: 10.11.6

Before I found out that you could install `code` in the path, I made this little shell script:
```bash
#!/bin/sh
open -a 'visual studio code' "$@"
```

It tells VSCode to open the given files. It turns out that it is faster to run than the `code` command.

Steps to Test:

1. copy the above script into the path somewhere
2. run it with a file, note the speed
3. run `code` with the same file, note the speed

So… not sure if that means there should be anything done here.

**Comment by joaomoreno** [comment]
Not that it's *slow* on my machine, but for sure that is faster. We do it because there are some command line arguments that will not launch the whole Code but rather just return something to the command line. For example: `--help`, `--version`, `--list-extensions`, etc. These need to be processed before, and they are done so in a Node process. Once that process figures out it should spawn Code, it does so.

Here's what happens on my machine:

```
time code-insiders .
code-insiders .  0.12s user 0.05s system 97% cpu 0.172 total
```

I see Code's window in under half a second.

What is your experience? Is is really that much slower than 0.5 seconds?
