### ISSUE TITLE
git integration

### ISSUE THREAD

**Issue by aquillavdberg** [microsoft/vscode#137874]
i'd like to have a visual interface for git integrated in the IDE. I'd like to see a graph with all its' branches and would like to be able to click on the different commits to see what files were changed and when clicked on the file, to see the changes within them

**Comment by lszomoru** [comment]
Have you tried [the GitLens extension](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens)?
I would recommend that you give that a try and it has a lot of git related functionality on top of what is built in to VS Code.

**Comment by heartacker** [comment]
recommend : https://marketplace.visualstudio.com/items?itemName=mhutchie.git-graph

![](https://raw.githubusercontent.com/mhutchie/vscode-git-graph/master/resources/demo.gif)

**Comment by yay** [comment]
> Have you tried [the GitLens extension](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens)? I would recommend that you give that a try and it has a lot of git related functionality on top of what is built in to VS Code.

@lszomoru GitLens cramms everything into the Source Control side panel. Because GitLens is a third-party extension, it's trying to achieve what it can with the tools it is given, rather than having the freedom to consider how the best git GUI would look like if there were no contraints. I don't think it would look like an [accordion](https://component.gallery/components/accordion/) with a bunch of items.

**Comment by lszomoru** [comment]
The feature request described here is covered by the new "Source Control Graph" view.
