### ISSUE TITLE
Let's notify Mac Silicon users who are running VS Code Intel build

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#137814]
Based on https://twitter.com/irreverentmike/status/1463532471614681105 I think we should make our Apple Silicon builds more discoverable.

I hate notifications but I think for Mac Silicon users that are running VS Code Intel we should show a notification in the sense "We noticed you are running an intel build while you are on a sillicon machine, consider switching to sillicon..."

If we do not want to use a barbaric notification on startup I suggest to show a dialog box once the user clicks on the Update button - that means the user is "in the zone" to switch builds.

fyi @bpasero @joaomoreno

**Comment by ItalyPaleAle** [comment]
Another option I could think of is doing the update transparently to the user. This would also cause less confusion for those who are not that familiar with architectures. 

Next time there's a new VS Code release, we could fetch the Apple Silicon build rather than the Intel build and automatically install that. (We can then show a notification saying "we updated your app to take advantage of the performance optimizations for Apple Silicon" or something like that).

**Comment by mbifulco** [comment]
Thanks for [sharing my article](https://mikebifulco.com/posts/make-vs-code-load-faster-mac-apple-silicon) @isidorn, this is a great idea for an improvement. I wonder if there might be an opportunity to work this into [electron](https://github.com/electron/electron) as well - I'm going to do some spelunking in their issues to see if anyone has brought up a similar notion in the past.
