### ISSUE TITLE
Investigate more stable worker extension host origin

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#137866]
Today, on each load the iframe that owns the web worker extension host gets a new origin. The separate origin ensures that extensions cannot access the same resources (localStorage, indexeddb, etc pp) as the renderer. However, the ever changing origin also mean that extensions cannot use web worker API that are origin scoped, like indexeddb. This is further complicated because the dev setup (desktop worker exthost, yarn web) doesn't reflect this limitation. 

I wonder if we can have more stable origins while still maintaining the separation correctly. I am not very knowledgable in the area but maybe generate an origin once and store it the same way as secrets are stored/cleared

**Comment by alexdima** [comment]
@joaomoreno has done an investigation yesterday where we tried to bring dynamic origins when running locally. That would at least resolve part of the problem, that the prod env is different than the dev env. 

:+1: on storing the origin in local storage. It doesn't have to be encrypted, because it's not a secret.
