### ISSUE TITLE
Web - consider a chrome extension to avoid the CTRL+W issue

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#137972]
Suggestions from @bolinfest on how to tackle the CTRL+W issue https://github.com/microsoft/vscode/issues/137767#issuecomment-978544329

**Comment by bpasero** [comment]
@egamma but is that the right solution, given the concerns in https://github.com/microsoft/vscode/issues/137767#issuecomment-978544329? When I read that comment I feel that this is not the right direction going forward because it was proven to have issues and side effects.

If people were to keep their main vscode.dev workspaces as PWA (https://github.com/microsoft/vscode/issues/135553), I think the situation would improve. Even setting the tab to fullscreen helps.

**Comment by bolinfest** [comment]
@bpasero I don't feel like there is a clear "best solution" here. Switching to fullscreen mode is a great option when you want to focus on VS Code Web, but it is a fairly significant context switch if you are bouncing back and forth between your VS Code Web Chrome tab and your other tabs.

In terms of discoverability, the Chrome extension could be presented as an "upsell" of sorts when the user hits `cmd+w` the first time and hits the `onbeforeunload` handler. I'm not saying that's necessarily what *should* happen, just that there are options.

**Comment by bpasero** [comment]
I agree, and would always prefer a PWA over fullscreen mode, especially because that has the added value that you can use the OS window manager to manage the VSCode web application and not have your development environment buried in other tabs of the browser.

Another possible alternative would be to run all VS Code web instances with one user profile and the normal web development tabs with a different user profile.

Unfortunately the browser does not really allow you to do lots of things from the `beforeunload` handler, i.e. the dialog that you can let the browser open is not configurable at all.
