### ISSUE TITLE
Diagnostics appear in read-only half of diff editor

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#137952]
Issue Type: <b>Bug</b>

1. Open an SCM-controlled file that contains a problem which results in a diagnostic appearing on the PROBLEMS panel.
2. Fix the problem and save the change. The diagnostic correctly disappears.
3. From the SCM view, open the diff editor for the changed file.
4. Confusingly, the diagnostic reappears.

Example:

![image](https://user-images.githubusercontent.com/6726799/143614616-01938fea-80bf-4f3e-a49d-ec297f5937c6.png)

VS Code version: Code - Insiders 1.63.0-insider (d18d093403b12a65350c58a7b0d5771cc1f42aba, 2021-11-26T08:21:30.810Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

**Comment by alexdima** [comment]
All read only editors render diagnostics since https://github.com/microsoft/vscode/blob/db95d3c179ed6cff7e56605ff226b49257942afd/src/vs/workbench/browser/parts/editor/textEditor.ts#L123 . I think that is OK, but the root problem is that the `git:` resource is getting validated by JSON or by our configuration editing extension.

**Comment by aeschli** [comment]
The warning is correct as such, `enableProposedAPI` is deprecated. 
Are you saying the user doesn't want to not have such information on read-only documents?

The JSON server can deal with all types of resources. Virtual, non virtual. Being able to work on virtual resources is essential for the web and virtual workspaces. The server only sees text documents that are being opened, so it's difficult to know how they are used and if validation is wanted or not.  `git` resources are just one type of contributed virtual resources, and the language extensions shouldn't have to hardcode it.

If we agree that we don't want diagnostic in readonly documents or file system providers, then this is something I can work on, ideally as part of the LSP.  @dbaeumer 
But then the first easy fix is to turn off validation decorations on the left hand side of diff editors. @alexdima

**Comment by alexdima** [comment]
@aeschli The change to show diagnostics in read only editors was done via https://github.com/microsoft/vscode/commit/982a71938c38d3ba93609aba3358165f7ccb5874 (cc @bpasero). I don't remember all the discussions around #89057, but I think we felt that code editors should reflect the problems panel. i.e. if an error is shown in the problems panel, we want that it is also rendered in the editors. There is no reason to hide them only in the editor if they appear in the status bar and in the problems panel. So IMHO going back to having read-only editors hide problems is not a good approach, as we arrived here because we want that editors are in sync with the problems panel.

**Comment by gjsjohnmurray** [comment]
Even without adding anything to LSP, I think VS Code could implement in its core an option to not show diagnostics for read-only resources. They wouldn't show in the Problems panel or in the editor.

Perhaps make it configurable per scheme. Now we have #46851 an extension implementing a FileSystemProvider for a custom scheme could default that setting appropriately.

If I had to do this as an extension developer I'd probably first check `vscode.workspace.fs.isWiritableFileSystem(scheme)`. If it returned true I'd then `await vscode.workspace.fs.stat(uri)` to see if `permissions` was returned and signalled `FilePermission.Readonly`

**Comment by dbaeumer** [comment]
Showing problems in read only documents makes sense to me, especially since fixing such an error could be done by changing another non read-only file.

I am not against a filter to filter them from the UI.

**Comment by aeschli** [comment]
I agree that the problem view and the editor should be consistent.

It seems we want diagnostics for read-only documents. I guess we keep things as they are.

We don't have any metadata that would allow the language services to know for which schemas (or documents) are of interest or not. If we had such meta data I could instruct the language servers which diagnostics to push.

**Comment by aeschli** [comment]
We want diagnostics for read-only documents. We keep things as they are. -> Closing the issue


Note: The JSON language server changed from *push* to *pull* diagnostics, which means it only creates diagnostics it was asked for.
The decision which for which models to get diagnostics is currently in the LSP client (based on open editor tabs and documents). That's for the next time if we decide to change which documents should not get diagnostics or not.
