### ISSUE TITLE
Highlights of selection in editor, minimap and scroll

### ISSUE THREAD

**Issue by alandema** [microsoft/vscode#137948]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:  1.62.3
- OS Version: W10 20H2

About #104937 #101552 and [ #205](https://github.com/microsoft/pylance-release/issues/205)

Steps to Reproduce:
1. set "editor.occurrencesHighlight": true
2. select text to highlight

![image](https://user-images.githubusercontent.com/68517641/143593099-6de12575-18fc-4f8d-97e6-b5c049c68417.png)

When only placing cursor in a word it highlight other words with the same semantics in editor, minimap and scrollbar.

When **selecting** a piece of text it highlight all other texts **BUT ONLY IN EDITOR**, in the minimap and scrollbar it still taking in account the semantics and does not get highlighted.

I was expecting that when "editor.occurrencesHighlight": true, and select the text (not only placing the cursor) the highlights matches in the editor, in the minimap and in the scroll bar. For all text without semantics.

This can be achieved with "editor.occurrencesHighlight": false, but then I lose the feature of placing the cursor on word to see only the same semantics.

**Comment by alexdima** [comment]
This behavior is [intentional](https://github.com/microsoft/vscode/blob/01a4170028fb6e7b9079942fadb7d4398fc4013c/src/vs/editor/contrib/multicursor/multicursor.ts#L1040-L1046). IIRC the idea was that if a language supports semantic highlights, then semantic highlights should own the overview ruler. The reason is that in the editor we can render both selection highlights and semantic highlights (with various different colors such that they are all visible), but in the overview ruler things simply get very crowded and undistinguishable.
