### ISSUE TITLE
git - git push takes too long and forever

### ISSUE THREAD

**Issue by azlisamshudin** [Microsoft/vscode#13795]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T15:27:10.246Z)
- OS Version: Darwin x64 14.3.0
- Extensions: 

Steps to Reproduce:

1.
2.

**Comment by obok** [comment]
Same problem for me.

By the way, there is workaround mentioned on https://code.visualstudio.com/Docs/editor/versioncontrol:

Q: Why do the Pull, Push and Sync actions never finish?

This usually means there is no credential management configured in Git and you're not getting credential prompts for some reason.

You can always set up a credential helper (https://help.github.com/articles/caching-your-github-password-in-git/) in order to pull and push from a remote server without having VS Code prompt for your credentials each time.

**Comment by joaomoreno** [comment]
Does it work from the command line? Can you show me a screenshot?

**Comment by obok** [comment]
@joaomoreno Yes, command line git commands worked properly. In my case prompt for credentials did not show up when I had that problem.
Right now prompt shows up again and Push works properly.
