### ISSUE TITLE
extension Host crashed

### ISSUE THREAD

**Issue by kissstudio** [microsoft/vscode#138025]
Issue Type: <b>Bug</b>

occurs when update vscode last week.  2021/11/26
working on a vue project(dir) opened in vscode,  a few minutes later it shows a "extension Host crashed" tips there.
when im working on the project like usually. restart vscode can be fixed temp and will re-crashed again like before.

dev console output:
[doggy8088.angular-extension-pack]: "contributes.angular-extension-pack.language" 中包含未知语言。提供的值: NGINX
_logMessageInConsole @ workbench.desktop.main.js:2967
workbench.desktop.main.js:77 [Extension Host] Shutting off webserver...
workbench.desktop.main.js:2967 Extension Host
workbench.desktop.main.js:2967 <--- Last few GCs --->[13768:000038DB00000000]  1322042 ms: Scavenge 1661.8 (2061.0) -> 1658.3 (2062.5) MB, 3.1 / 0.0 ms  (average mu = 0.272, current mu = 0.275) task [13768:000038DB00000000]  1322099 ms: Scavenge 1664.0 (2062.7) -> 1660.0 (2064.2) MB, 2.9 / 0.0 ms  (average mu = 0.272, current mu = 0.275) task [13768:000038DB00000000]  1322146 ms: Scavenge 1664.8 (2064.2) -> 1661.3 (2065.5) MB, 4.0 / 0.0 ms  (average mu = 0.272, current mu = 0.275) task <--- JS stacktrace --->FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory 1: 00007FF67FBBD696 node::Buffer::New+45638 2: 00007FF67FBBD8A0 node::OnFatalError+464 3: 00007FF6825494F3 v8::CFunctionInfo::ArgumentInfo+803 4: 00007FF68254944C v8::CFunctionInfo::ArgumentInfo+636 5: 00007FF68261DEE3 v8::JSHeapConsistency::CheckWrapper+65107 6: 00007FF682620A56 v8::JSHeapConsistency::CheckWrapper+76230 7: 00007FF68261E283 v8::JSHeapConsistency::CheckWrapper+66035 8: 00007FF68261C60D v8::JSHeapConsistency::CheckWrapper+58749 9: 00007FF67F1FDD9E cppgc::ProcessHeapStatistics::TotalAllocatedSpace+31671810: 00007FF67FBCDA3D node::OnFatalError+6641311: 00007FF67FBCC6A3 node::OnFatalError+6139512: 00007FF67FBD8C8C uv_run+49213: 00007FF67E7804D2 v8::internal::OSROptimizedCodeCache::OSROptimizedCodeCache+6576214: 00007FF67E5EE82D cppgc::NameProvider::HideInternalNames+3702115: 00007FF681AC44D2 Cr_z_crc32+439779416: 00007FFBE0327034 BaseThreadInitThunk+2017: 00007FFBE0B02651 RtlUserThreadStart+33
workbench.desktop.main.js:602  INFO Extension host with pid 13768 exited with code: 134, signal: null.
workbench.desktop.main.js:2967 Extension host (LocalProcess) terminated unexpectedly. Code: 134, Signal: null
_onExtensionHostCrashed @ workbench.desktop.main.js:2967
workbench.desktop.main.js:602   ERR Extension host (LocalProcess) terminated unexpectedly. The following extensions were running: vscode.microsoft-authentication, GrapeCity.gc-excelviewer, vscode.emmet, Wscats.vue, vscode.debug-auto-launch, vscode.git, cweijan.vscode-mysql-client2, donjayamanne.githistory, EditorConfig.EditorConfig, formulahendry.auto-rename-tag, infinity1207.angular2-switcher, ms-mssql.mssql, mtxr.sqltools, nhoizey.gremlins, oouo-diogo-perdigao.docthis, peakchen90.vue-beautify, wayou.vscode-todo-highlight, vscode.npm, pranaygp.vscode-css-peek, vscode.github-authentication, vscode.configuration-editing, vscode.json-language-features, vscode.typescript-language-features, vscode.github, ms-mssql.data-workspace-vscode, mtxr.sqltools-driver-pg, ms-mssql.sql-database-projects-vscode, vscode.merge-conflict, ms-vscode-remote.remote-wsl-recommender, Gruntfuggly.todo-tree, ms-vscode-remote.remote-containers, ms-vscode-remote.remote-wsl, SonarSource.sonarlint-vscode
workbench.desktop.main.js:788 扩展宿主意外终止。
onDidChangeNotification @ workbench.desktop.main.js:788

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:11:14.551Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 4800H with Radeon Graphics          (16 x 2894)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.37GB (7.83GB free)|
|Process Argv|--crash-reporter-id 15c92c7d-3b73-4873-9f5f-b2918baef29e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (69)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.2
ng-template|Ang|13.0.0
vscode-mysql-client2|cwe|4.3.0
angular-schematics|cyr|5.1.0
vscode-simpler-icons|dav|1.6.5
jshint|dba|0.11.0
angular-extension-pack|dog|12.2.1
quicktype-refresh|dog|0.1.1
githistory|don|0.6.18
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.23
auto-rename-tag|for|0.1.9
docker-explorer|for|0.1.7
docker-extension-pack|for|0.0.1
vscode-lombok|Gab|1.0.1
gc-excelviewer|Gra|3.0.44
todo-tree|Gru|0.0.214
angular2-switcher|inf|0.3.4
Angular2|joh|12.0.0
refactorix|kri|0.3.6
json-to-ts|Mar|1.7.5
Angular-BeastCode|Mik|10.0.3
vscode-docker|ms-|1.18.0
vscode-language-pack-zh-hans|MS-|1.62.4
csharp|ms-|1.23.16
data-workspace-vscode|ms-|0.1.0
mssql|ms-|1.11.1
sql-database-projects-vscode|ms-|0.13.1
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.11.2
jupyter|ms-|2021.10.1101450599
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
remote-containers|ms-|0.205.2
remote-ssh-edit-nightly|ms-|2021.11.35460
remote-ssh-nightly|ms-|2021.11.35460
remote-wsl|ms-|0.58.5
cpptools|ms-|1.7.1
typescript-javascript-grammar|ms-|0.0.55
vscode-typescript-tslint-plugin|ms-|1.3.3
sqltools|mtx|0.23.0
sqltools-driver-pg|mtx|0.2.0
gremlins|nho|0.26.0
arrr|obe|0.1.3
docthis|oou|0.8.2
vue-beautify|pea|2.0.4
vscode-boot-dev-pack|Piv|0.1.0
vscode-concourse|Piv|1.28.0
vscode-manifest-yaml|Piv|1.28.0
vscode-spring-boot|Piv|1.28.0
vscode-css-peek|pra|4.2.0
quicktype|qui|12.0.46
java|red|1.1.0
vscode-commons|red|0.0.6
vscode-xml|red|0.18.1
sonarlint-vscode|Son|3.1.0
autoimport|ste|1.5.4
move-ts|str|1.12.0
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.37.0
vscode-java-dependency|vsc|0.18.8
vscode-java-pack|vsc|0.18.7
vscode-java-test|vsc|0.33.0
vscode-maven|vsc|0.34.1
vscode-spring-boot-dashboard|vsc|0.2.0
vscode-spring-initializr|vsc|0.8.0
vscode-todo-highlight|way|1.0.5
vue|Wsc|1.0.26
JavaScriptSnippets|xab|1.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200:30402083
vsaa593:30376534
vssld246:30401890
vscop804:30404766
vscop453:30404998

```

</details>

**Comment by alexdima** [comment]
@kissstudio It looks like the extension host process crashed due to an Out-Of-Memory error. When the crash occurred, the following extensions were loaded in the extension host process:
- `vscode.microsoft-authentication`
- `GrapeCity.gc-excelviewer`
- `vscode.emmet`
- `Wscats.vue`
- `vscode.debug-auto-launch`
- `vscode.git`
- `cweijan.vscode-mysql-client2`
- `donjayamanne.githistory`
- `EditorConfig.EditorConfig`
- `formulahendry.auto-rename-tag`
- `infinity1207.angular2-switcher`
- `ms-mssql.mssql`
- `mtxr.sqltools`
- `nhoizey.gremlins`
- `oouo-diogo-perdigao.docthis`
- `peakchen90.vue-beautify`
- `wayou.vscode-todo-highlight`
- `vscode.npm`
- `pranaygp.vscode-css-peek`
- `vscode.github-authentication`
- `vscode.configuration-editing`
- `vscode.json-language-features`
- `vscode.typescript-language-features`
- `vscode.github`
- `ms-mssql.data-workspace-vscode`
- `mtxr.sqltools-driver-pg`
- `ms-mssql.sql-database-projects-vscode`
- `vscode.merge-conflict`
- `ms-vscode-remote.remote-wsl-recommender`
- `Gruntfuggly.todo-tree`
- `ms-vscode-remote.remote-containers`
- `ms-vscode-remote.remote-wsl`
- `SonarSource.sonarlint-vscode`

Any one of the above extensions could have a bug that might lead to an Out-Of-Memory crash (e.g. endless loop). In order to narrow down the possible problematic extension, please try the following:
* run `F1 > Help: Start Extension Bisect`
* (this will restart VS Code with half of your extensions disabled)
* try to do the steps which reproduce the problem
* if the problem reproduces, click "This is bad" (this narrows down the problematic extension to the half which was enabled)
* if the problem does not reproduce, click "Good now" (this narrows down the problematic extension to the half which was disabled)
* these steps will repeat until the problematic extension is found

| initial | step | final |
|---|---|---|
| ![image](https://user-images.githubusercontent.com/5047891/101918658-e9170f80-3bc9-11eb-9977-857baa291937.png) | ![image](https://user-images.githubusercontent.com/5047891/101918683-ef0cf080-3bc9-11eb-9f9e-98b0177991b2.png) | ![image](https://user-images.githubusercontent.com/5047891/101918706-f502d180-3bc9-11eb-8c86-e56355958bd4.png) |

**Comment by kissstudio** [comment]
@alexdima found it. Jupyter Notebook Renderers
v1.0.4 makes vscode crashed.

**Comment by kissstudio** [comment]
the Extension Bisect told the result.

**Comment by alexdima** [comment]
@kissstudio Please report this crash directly to the extension at https://github.com/microsoft/vscode-notebook-renderers

cc @DonJayamanne
