### ISSUE TITLE
I want to open it directly when I right-click it, Can you help me?

### ISSUE THREAD

**Issue by sixhj** [microsoft/vscode#138008]
I  want to open it directly  when I right-click it, Can you help me?

**Comment by gjsjohnmurray** [comment]
Open what? Right-click where?

/needsMoreInfo

**Comment by sean8102** [comment]
I'm assuming they mean they want the open with VS Code option. I'm thinking of installing VS Code and possibly using it as a replacement for Notepad++. Mainly because I like the auto updating that the store offers. 

But I read in many of the store reviews that there is no "open with VS code" option when you right click a file, and apparently there used to be (or maybe it's only missing from the MS Store version).

**Comment by gjsjohnmurray** [comment]
@sean8102 #134743 it related and links to a few others.
