### ISSUE TITLE
Test multiple language specific settings

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#138076]
Ref #51935

- [x] Mac @lramos15
- [x] Win @karrtikr
- [x] Linux @isidorn

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23138076%0A%0A&assignees=sandy081)

---

You can now configure editor settings for multiple languages once as follows (in your settings): 

```json
"[cpp][c]":{
    "editor.formatOnSave": true
}
```

- Test that these settings are applied to all configured languages
- Test that settings are merged for a language, when the language is configured multiple times with different languages. Eg:
```json
"[cpp][c]":{
    "editor.formatOnSave": true
},
"[java][c]":{
    "editor.lineHeight": 2.5
}
```
In the above example, `c` language shall have following overrides after merging
```
{
    "editor.formatOnSave": true,
      "editor.lineHeight": 2.5
}
```

- Test that settings configured with single language only are preferred when the language is configured multiple times with different languages. Eg:
```json
"[c]":{
   "editor.formatOnSave": false
},
"[cpp][c]":{
    "editor.formatOnSave": true
},
"[java][c]":{
    "editor.lineHeight": 2.5
},
```
In the above example, `c` language shall have following overrides after merging
```
{
    "editor.formatOnSave": false,
      "editor.lineHeight": 2.5
}
```
- Explore and test various other scenarios which you can try

**Comment by isidorn** [comment]
We now support language specific settings and we also support to specify multiple languages. This is nice, but is hard to be discovered by the users because this is not available in the Settings UI.

I think we should drive settings feature the other way around, starting from the Settings UI. Because if the settings UI does not support it 95% of our users will simply not find the feature.

@rzhao271 that is why I think we should work on https://github.com/microsoft/vscode/issues/74195 and https://github.com/microsoft/vscode/issues/58995
