### ISSUE TITLE
Test browsing themes from marketplace

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#138084]
Refs: #137289

- [x] anyOS @kimadeline
- [x] anyOS @isidorn
- [x] web @karthiknadig

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23138084%0A%0A&assignees=aeschli)

---

The theme picker dialog now has an option to preview new themes directly from the marketplace

- open the `Preferences: Color Theme` command which opens a quick pick with the installed themes
- The first option is "Browse Additional Color Themes...`, choose it
- this brings you to a quick pick that show themes from the marketplace
- If no input text is given that shows the themes from the most popular theme extensions
- Use cursor up/down to look at the themes
- Use sesrch test to search in the name, descrition or the theme author name
- Press enter to install the extension

Test the same for the file and product icon themes:
Known issue: https://github.com/microsoft/vscode/issues/138082

- use the configure button to configure the extension in the extensions viewlet

**Comment by ArturoDent** [comment]
Probably no way to avoid it but many theme previews render the theme picker dialog current selection unreadable for me because of the `colorCustomizations` I have implemented.  So I might get white text on a white background for example, so I can't read the current highlighted theme name.  Although I can read it when it is next in line so not a big deal.

**Comment by ArturoDent** [comment]
A note for the ultimate introduction of this new functionality:  pressing `enter` installs **and applies** the theme.  

I know this is expected behaviour I just think when the feature is introduced it should be reiterated - any pre-exisiting `"workbench.colorTheme"` will be overwritten and the chosen theme will be applied (as well as installed) - for no surprises.

**Comment by karthiknadig** [comment]
@aeschli Can you give me instructions on accessing insiders vscode.dev for my part of the test plan?

**Comment by karthiknadig** [comment]
@aeschli Clicking on the gear icon opens the extensions tab with that extension. Bur it does not select it. Should it be selecting it?
![image](https://user-images.githubusercontent.com/3840081/143984068-9fb66c34-48ef-46d7-a7ad-47db7f70b16b.png)

As you can see the cursor is in the search box and the extension itself is not selected for configuration.

**Comment by ArturoDent** [comment]
For others: https://insiders.vscode.dev/azurerepos/mseng/AzureDevOps/AzureDevOps

To install and apply a color theme from the quick pick just hit <kbd>Enter</kbd> on your selected theme.  Don't click its little Gear Icon to the right.

**Comment by karthiknadig** [comment]
@ArturoDent thanks for the link. I was able to get a theme installed and verified that behavior. I was particularly looking at how clicking on gear icon should behave. 

I was expecting clicking on this:
![image](https://user-images.githubusercontent.com/3840081/143985922-4f8b2089-df4b-48c6-9c34-258495f680b0.png)

To open this view:
![image](https://user-images.githubusercontent.com/3840081/143985792-ce2b8c53-59fe-4822-bf90-8e5fb51badcb.png)

**Comment by isidorn** [comment]
Works great, I like this flow a lot 👏
