### ISSUE TITLE
Global variables in require() call

### ISSUE THREAD

**Issue by bpaczkowski** [Microsoft/vscode#13810]
It would be nice if IntelliSense loaded files referenced by a global variable, ie. `const config = require(`${rootPath}/config`)`, where `rootPath` is a global variable declared in the main project file for example like this `global.rootPath = __dirname`.

**Comment by waderyan** [comment]
@bpaczkowski thank you for your feature request. This is a good idea and we will consider it.

**Comment by mjbvz** [comment]
Thank you for the suggestion, however this is out of scope. 

To accomplish something similar to your example, try configuring a [`tsconfig.json` or `jsconfig.json`](http://www.typescriptlang.org/docs/handbook/tsconfig-json.html) file to specify the root path. 

The path in `require`  itself must be a string literal though, and `import` statements even codify this in order to support proper code analysis
