### ISSUE TITLE
case insensitive de-duplication

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#138197]
Testing #137668

with two settings - `a setting` and `A setting`, `a setting` does not show up. I'd expect it to be shown before the upper case one. 

![case](https://user-images.githubusercontent.com/29464607/144107440-a27a007c-e538-48ef-920c-0a0b1d549707.PNG)

**Comment by meganrogge** [comment]
this happens even if they're differentiated via an `order` property

**Comment by rzhao271** [comment]
I'm unable to repro. For me, I get two settings that say "A setting".

**Comment by lszomoru** [comment]
I am also getting two settings that say "A setting", though I am wondering if that is expected? 
If I define two settings both called "A setting" then I get an warning that there is already a registered setting. 
But in case they are using different cases "A setting", and "a setting" both are registered though they look the same.

**Comment by meganrogge** [comment]
Here's exactly what I'm doing to repro:
![repro](https://user-images.githubusercontent.com/29464607/144270392-3852199a-ace2-4699-8031-a6df537b50e3.PNG)

**Comment by rzhao271** [comment]
TODO:

- [ ] Figure out where in the code the setting labels are being capitalized. I have a feeling it's at the same place that settings are being wordified in general, so I'm not sure if we want to do anything there. Even if the Settings editor is able to de-dup the setting, the `settings.json` file would still allow the user to edit the different settings, leading to an inconsistency.
- [ ] Since there's already an "A setting" under the "B configuration", the "A setting" under the "A configuration" isn't registered, since to the extension, both settings have the same name. Therefore, extension authors should make sure to give their settings a namespace. I plan on placing that recommendation in a doc update. The editor also warns the extension author though: for me at least, when debugging the extension with the repeated settings, I get a notification that says "[undefined_publisher.settings-editor-tocsort]: Cannot register 'A setting'. This property is already registered."

**Comment by meganrogge** [comment]
interesting - I don't a notification, but I do see that warning in the console.

```
abstractExtensionService.ts:927 [meganrogge.settings-editor-tocsort]: Cannot register 'A setting'. This property is already registered.
_logMessageInConsole @ abstractExtensionService.ts:927
abstractExtensionService.ts:927 [meganrogge.settings-editor-tocsort]: Cannot register 'a setting'. This property is already registered.
_logMessageInConsole @ abstractExtensionService.ts:927
abstractExtensionService.ts:927 [meganrogge.settings-editor-tocsort]: Cannot register 'A setting'. This property is already registered.
```

**Comment by rzhao271** [comment]
If it's a warning, I expect that the notificationService would've logged it, too. https://github.com/microsoft/vscode/blob/e9c1057fbcdd37803e85ffc7e92b2c1379ef75a6/src/vs/workbench/services/extensions/common/abstractExtensionService.ts#L916-L917

Other than the docs change in vscode-docs above, I don't plan on adding any other changes.
