### ISSUE TITLE
Perf regression due to config default changes

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#138154]
Over the last weeks we have seen startup performance regressing by ~250ms (on the perf bot). This has been traced down to changes in the configuration service, sending more/new events which processing takes time.

[slow-b9cf83f70bb6b4697b544a97c7056dfd28fccc5f.cpuprofile.txt](https://github.com/microsoft/vscode/files/7626084/slow-b9cf83f70bb6b4697b544a97c7056dfd28fccc5f.cpuprofile.txt)

[fast-c1f2f40bcd81380bf2e286af64becddada57db88.cpuprofile.txt](https://github.com/microsoft/vscode/files/7626085/fast-c1f2f40bcd81380bf2e286af64becddada57db88.cpuprofile.txt)

**Comment by jrieken** [comment]
Investigating this also revealed https://github.com/microsoft/vscode/issues/138153 (bad, but not a regression)

**Comment by sandy081** [comment]
With help of @jrieken (thanks for bisecting), I figured out the root cause for the perf slow down of this 100ms . This is happening at two places

1. Comparing and updating defaults
2. Updating schema for default configurations

Fixed both.

1. Reverted to old way of comparing and updating defaults
2. Moved registering the schema to a workbench contribution that happens on Restored phase where other schemas are registered too.

This gets back 100ms from my local computations
