### ISSUE TITLE
Dangerous use of `href=#` without preventing

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#138175]
Setting a `a href="#"` without preventing default will trigger navigation.

Found:
* https://github.com/microsoft/vscode/blob/212deea1ccf107e9e1a167b7b26ceac6f270f448/src/vs/workbench/contrib/preferences/browser/settingsTree.ts#L1900
* https://github.com/microsoft/vscode/blob/e38fbdae27d350d764b92a431f1b5430b8ec856f/src/vs/base/browser/markdownRenderer.ts#L155 (not sure)
* https://github.com/microsoft/vscode/blob/8065e352656bb5ca6231d6cded7dd467e1cc174a/src/vs/base/browser/formattedTextRenderer.ts#L103

See https://github.com/microsoft/vscode/issues/137512 for details of what can happen and associated fix.

**Comment by rzhao271** [comment]
Some code pointers:

Electron has an `ElectronNavigationThrottle` that emits the `will-navigate` event: https://github.com/electron/electron/blob/b1e2185c5ef7692765a3044d366f3c00409ee784/shell/browser/electron_navigation_throttle.cc#L41

On the Chromium side, there is also a `WillStartRequest` function:
https://source.chromium.org/chromium/chromium/src/+/main:content/browser/renderer_host/navigation_request.cc;l=5438;drc=1f996e51b95348aecf84a2568e059d49b0943986;bpv=1;bpt=1

Same-document navigations don't actually seem to call `WillStartRequest` (it returns at line 2036 instead of 2053), though I have only visually inspected the code for now:
https://source.chromium.org/chromium/chromium/src/+/main:content/browser/renderer_host/navigation_request.cc;l=2011;drc=1f996e51b95348aecf84a2568e059d49b0943986;bpv=1;bpt=1

**Comment by rzhao271** [comment]
Upstream: https://github.com/electron/electron/issues/32371

**Comment by rzhao271** [comment]
Closing as wontfix since upstream essentially closed the issue as as-designed.
There are some new links I found where preventDefault can be called, though. I'll make a PR for those.
