### ISSUE TITLE
Side Panel should preserve state globally (not sync'd)

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#138179]
Testing #138101

I spent some time configuring a panel/side bar/side panel layout that I was happy with in one workspace. Then I opened a different workspace and found that my layout wasn't preserved ☹️:

1. The side panel was initially collapsed even though I had it open in my first workspace. I would expect that panel's visibility to be preserved
2. Not sure how this happened, but the contents of the Explorer view in the side bar got reordered (the file tree view and the source control view managed to swap positions)

https://user-images.githubusercontent.com/30305945/144093942-3b1df48c-4d19-4afb-adf0-d5bf6a3b5064.mp4

**Comment by joyceerhl** [comment]
Maybe there is some existing view state that is remembered per workspace? I assumed that layout changes were global for all workspaces because the source control view correctly showed up as a child of the explorer, it just was in the wrong order (it should have been beneath the file tree view)

**Comment by sbatten** [comment]
This is all fair feedback but I don't think any of it doing something unexpected. View visibility and order tend to be workspace state while location tends to be global. The first issue you mention about the side panel not being visible in a different workspace is because we default to panel-like behavior, but I can see an argument for treating it like the side bar in this case. I will try setting it to visible when a new workspace is opened (the side bar default)

**Comment by abflow** [comment]
I suggested in (#138263) that it would be useful to be able to store, retrieve and sync different layouts that could be synced too.
