### ISSUE TITLE
Python function annotation syntax highlight is not working 

### ISSUE THREAD

**Issue by doantranthanh** [microsoft/vscode#138156]
Hi there, 

My VSCode does not work well on highlight syntax with python function annotation. Details are following:

* **Editor name and version**: VSCode version 1.62.3
* **Platform**: Windows 10
* **MacicPython**: v1.1.0
* **Python version**: Python v3.7.8
* **Color scheme**: Any (primary using Tokyo Night theme)
* **A sreenshot**:
![image](https://user-images.githubusercontent.com/9557564/144058735-ca88bb6e-4325-4513-9e48-f1d8b7de7c34.png)

* **5-10 lines of surrounding code**:
````python
def gcd(a: int, b: int) -> int:
    if a == b:
        return a
    else:
        if a > b:
            return gcd(a-b, b)
        else:
            return gcd(a, b-a)


def gcd2(a: int, b: int):
    if b == 0:
        return a
    else:
        return gcd2(b, a % b)
````
Any ideas?

Thanks

**Comment by alexr00** [comment]
@doantranthanh I'm not able to reproduce this issue. The problem is likely caused by either the theme you're using or another extension you have installed. If you want to find which extension is causing the problem, you can try the command "Help: Start Extension Bisect", which will disable extensions for you to narrow down the culprit.

**Comment by doantranthanh** [comment]
@alexr00 thank you so much. It is working now after I ran the command and uninstall corrupt extensions.
