### ISSUE TITLE
Test: Panel Alignment Setting

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#138101]
Refs: #132893
- [x] anyOS @weinand
- [x] anyOS @joyceerhl

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23138101%0A%0A&assignees=sbatten)

---

This milestone, we added an experimental setting that is available in insiders that determines how the panel spreads underneath the editor and side panels.

*Setup*
Enable the side panel feature with `workbench.experimental.sidePanel.enabled` and reload the window. Drag some view (e.g. Outline) into the side panel to keep it visible while testing.

Test by:
1) Reading the setting options and descriptions.
2) Try each option and verify it functions properly and does what you expect.
3) Try across reloads.

**Comment by weinand** [comment]
Since I was a bit confused, here are some clarifications:
- the setting to test is `workbench.experimental.panel.alignment`.
- in order to test the `right` and `justified` alignments it is necessary to enable a "sidePanel" on the right via the `workbench.experimental.sidePanel.enabled`.
- the `workbench.experimental.panel.alignment` setting does not require to have `workbench.experimental.sidePanel.enabled` set to true (the settings are independent)

**Comment by sbatten** [comment]
@weinand @joyceerhl sorry for not adding the setting id, wrote the tpi out of order and forgot some key info it seems
