### ISSUE TITLE
Green dot for pre-release feels random

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#138128]
Testing #138086

I have a hard time making sense of the green dot at the right of pre-release extensions. It is not self-explaining and there is no hover for it. Also, there is another light dot within a triangle on the other side. Intuitively I would have said that the green dot mean "on", "loaded", or "running"

<img width="357" alt="Screen Shot 2021-11-30 at 10 50 52" src="https://user-images.githubusercontent.com/1794099/144024649-f675f1dc-1fb2-4adb-94e3-013170dfe06e.png">

**Comment by gjsjohnmurray** [comment]
Would a bell symbol improve this?

**Comment by jrieken** [comment]
> Intention of green dot is to represent the current version shown is a pre-release version.

Doesn't the install button convey the same information? Since it's labeled "Install Pre-Release"

**Comment by isidorn** [comment]
I agree that in this particular case I agree the green dot does not bring any value. 
I think the green dot brings value when an extension is installed so you know if you have the pre-release or the release version.

**Comment by gjsjohnmurray** [comment]
How about using the 'eye' instead, to represent looking ahead at what's coming next? It is \ea70 instead of \ea71 which gives the dot.

![image](https://user-images.githubusercontent.com/6726799/144091226-4795cc7c-4e7f-472c-ac28-9402117d239f.png)

**Comment by misolori** [comment]
@sandy081 I thought there would only ever be one green dot? The one on the left is when it's available and the one on the right is when it is installed. There should also be a description in the hover otherwise users have no idea what the dot means (as pointed out by this issue)

**Comment by JacksonKearl** [comment]
IMO the only indication should be the button's text, at least for extensions I haven't installed. If the extension is installed, then the green dot makes sense. I don't think the badge is ever needed, and it conflicts with the recommended extension UI in a non-intuitive way (can an extension both have a pre-release version and be recommended?)

**Comment by sandy081** [comment]
The badge/bookmark on the left is to indicate that the extension has a pre-release version. This will help users to discover that there is a pre-release available. I intended to show it always because of consistency.

Green dot on the right indicates that the extension shown is pre-release version - This will help users that they are on pre-release version.

I agree that showing the green dot when extension is not installed does not makes sense. So making this change.

After discussing with @isidorn, we decided to wait for more user feedback to see if we want to change the green dot with another icon or not.

**Comment by sandy081** [comment]
To verify - Make sure the green dot is shown only when the installed extension is a pre-release version.

**Comment by misolori** [comment]
@sandy081 why are we showing two green dots though? We don't do this in recommendations and it feels unnecessary here, why would you want to know that a pre-release is available AND that you are on the pre-release? It makes the view look unpolished.

**Comment by sandy081** [comment]
Makes sense. Removed the bookmark / left dot when extension is installed and on pre-release version.

**Comment by sandy081** [comment]
Comment from @bpasero:

 > The green dot to indicate a pre-release version is imho not very intuitive. Given it appears close to the perf-time, to me it looks like an indicator that the extension is running, rather than being pre-release:

![image (1)](https://user-images.githubusercontent.com/10746682/149895098-f21c3a0b-95bd-4a5c-8c46-0c303e1c6674.png)

We have following indicators in the extensions view for pre-release extensions:

1. Following badge represents the extension has a pre-release version

![image](https://user-images.githubusercontent.com/10746682/149895334-bf19a9f5-fab8-4eee-99f5-5ef79a033a8d.png)

2. Following dot represents extension is running pre-release version
 
![image (1)](https://user-images.githubusercontent.com/10746682/149895098-f21c3a0b-95bd-4a5c-8c46-0c303e1c6674.png)

@misolori How about having another icon to represent a pre-release ?

**Comment by misolori** [comment]
@TylerLeonhardt suggested a label overlay like in other apps:

<img width="300" src="https://user-images.githubusercontent.com/35271042/150066132-b592256e-3550-4a13-98bb-89aea564524b.png">

but unfortunately our extension views are quite complicated as these are the existing decorators we deal with, here's an example:

<img width="660" alt="CleanShot 2022-01-18 at 21 02 43@2x" src="https://user-images.githubusercontent.com/35271042/150067385-969c274e-ba8d-4fdc-95b8-c1b008e78904.png">

Here's a few alternatives for an icon to swap out, with the hope that the icon helps add more distinction:

## Rocket

<img width="641" alt="CleanShot 2022-01-18 at 21 03 52@2x" src="https://user-images.githubusercontent.com/35271042/150067450-94c4c2a3-c5b6-42c3-9c96-b33b5559160b.png">

<img width="293" src="https://user-images.githubusercontent.com/35271042/150067711-f6a4154c-4b7c-46cf-8a01-7e0b18d7ad8c.png">

## Package

<img width="666" alt="CleanShot 2022-01-18 at 21 12 47@2x" src="https://user-images.githubusercontent.com/35271042/150068199-8cfd7828-e32d-4ed0-8816-b523ab216122.png">

<img width="293" src="https://user-images.githubusercontent.com/35271042/150068215-7d484a23-fa81-4c6a-9a19-2303ad53d51c.png">

## Bookmark

<img width="657" alt="CleanShot 2022-01-18 at 21 19 00@2x" src="https://user-images.githubusercontent.com/35271042/150068815-e12f62e7-fad8-4c46-8a69-703301ac9676.png">

<img width="293" src="https://user-images.githubusercontent.com/35271042/150068833-1f4a244a-eede-4da8-aaaf-e4bd8e5f71e4.png">

**Comment by bpasero** [comment]
Hm, I wonder if we need this kind of icon at all? Wouldn't it make more sense for an extension to change the icon for pre releases? Similar to what we do in VSCode, use blue for released and green for pre-release?

Besides, an extension could also decide to draw a little "Beta" label on top of the icon if it wanted to.

**Comment by sandy081** [comment]
> Wouldn't it make more sense for an extension to change the icon for pre releases?

This icon is for more the user than for the extension. So, I do not think it will be intuitive and consistent if we let extension authors provide the icon. IMO an extension shall have a single icon and the platform represent the pre-release badge/icon/color.

**Comment by gjsjohnmurray** [comment]
I previously suggested:

> How about using the 'eye' instead, to represent looking ahead at what's coming next? It is \ea70 instead of \ea71 which gives the dot.

Another idea I've had is the 'beaker' (\ea79), to convey the experimental status of a pre-release:

![image](https://user-images.githubusercontent.com/6726799/150118496-6edf1671-0797-4700-bef5-84655aafa830.png)

**Comment by isidorn** [comment]
I like @gjsjohnmurray icon suggestion. The only problem is that we use the same icon for the testing view.
Rocket suggestion from @misolori also correlates with me - because it is more often updated - "launched".

-1 for different extension icon depending on pre-release or not, I would like to have a consistent experience across all extensions.

**Comment by gjsjohnmurray** [comment]
@isidorn I had the same doubt about 'beaker'. So how about 'telescope' (\eb68) instead?

![image](https://user-images.githubusercontent.com/6726799/150170580-69d2c0e6-a537-48ed-9ca5-2eda806220be.png)

**Comment by gjsjohnmurray** [comment]
Also, I used DevTools to add a title attribute so a hover explains what that icon represents:

![image](https://user-images.githubusercontent.com/6726799/150171913-bd8d98ed-0dfe-4de7-aa46-fad4e07388e5.png)

**Comment by misolori** [comment]
Appreciate the other options @gjsjohnmurray but I think in order to solve this "what does this icon mean" we'll need to use a label.

Last option for changing the location of the pre-release icon and adding a label next to the gear where you can also change the versions:

<img width="655" alt="CleanShot 2022-01-19 at 15 36 06@2x" src="https://user-images.githubusercontent.com/35271042/150235577-93532236-0877-4235-9686-121da5f66453.png">

<img width="288" alt="CleanShot 2022-01-19 at 15 38 18@2x" src="https://user-images.githubusercontent.com/35271042/150235710-f82fc867-e541-452c-96b7-c81f1e7b6427.png">

**Comment by misolori** [comment]
I also think we need to make sure the extension hovers are consistent, when you are on the pre-release the description is gone and a tag is added:

<img width="640" alt="CleanShot 2022-01-19 at 15 39 12@2x" src="https://user-images.githubusercontent.com/35271042/150235864-4ac7bf86-c429-481d-ad68-b3f8e474e50a.png">
<img width="728" alt="CleanShot 2022-01-19 at 15 40 21@2x" src="https://user-images.githubusercontent.com/35271042/150235890-54c57455-4315-4af4-bcd8-2a0c47d15dad.png">

**Comment by sandy081** [comment]
In Extensions View, for the installed pre-release extension, I would go with either icon or label but not both given the real estate constraints there. If the reason for adding label is that the icon is not conveying, then it also applies for an uninstalled extension that has a pre-release. 

My preference is to show only icon in the extensions view and label in the hover and extension editor.

If the icons are not expressive enough, how about a green badge with letter `P` indicating it is a pre-release?

**Comment by sandy081** [comment]
![image](https://user-images.githubusercontent.com/10746682/150311537-d146dccb-fc24-4fd4-ac37-cef1100bcf5a.png)

![image](https://user-images.githubusercontent.com/10746682/150312467-c60836fe-30cf-4814-ab13-bb6d83af6206.png)

**Comment by isidorn** [comment]
Love the creative ideas! Thanks all!

@sandy081 the problem with the letter P is that it is not clear that it stands for pre-release, and P is in this world associated with "parking space"

@misolori problem with codicons is that it is not super clear what they mean, and none of the codicons really conveys pre-release meaning. I went now through the codicon set and I could not find any great options
 
@gjsjohnmurray we can not have a hover over the exact icon, since we already have a custom hover over the whole extension element

Having said all that I think the best option is to go with the design @misolori proposed in https://github.com/microsoft/vscode/issues/138128#issuecomment-1016971182 but to not use the icon. Just the label.

If we really want to use the icon I think the best fit is tools icon - because that means dev and work in progress

![Screenshot 2022-01-20 at 11 39 24](https://user-images.githubusercontent.com/1926584/150323053-fcab5331-2864-404d-9c74-6c431a747bd5.png)

**Comment by misolori** [comment]
The tools icon is used by tasks, so it might be a little confusing:

![image](https://user-images.githubusercontent.com/35271042/150394961-9768fa10-79c6-4de4-8cff-89c93d78e846.png)

It's been clear that no icon has really identified as "pre-release" worthy as it's a hard concept to represent in a single icon. I also don't think that just changing the icon is going to solve the original issue of "what is this icon".

**Comment by sandy081** [comment]
Out of all options, I think `version` icon seems to be the better option for me, as it represents versions. I would try with this icon and wait for feedback again?

**Comment by isidorn** [comment]
@sandy081 I definitely think the version icon is better than the green dot. So we can try that of course.

**Comment by sandy081** [comment]
Pushed versions icon

![image](https://user-images.githubusercontent.com/10746682/150322932-99175d4e-9d31-44ef-afce-67992654cee0.png)
