### ISSUE TITLE
Difficult hit target for partial language support notification

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode#138291]
- VS Code Version: 1.62.3
- OS Version: macOS Monterey 12.0.1

Ran into this while testing this item for python extension: https://github.com/microsoft/vscode-python/issues/18091. I feel this might be a VS Code issue, but could be moved if it's something the Python extension can fix. 

Steps are same as the python issue linked.

1. Install the build of the python extension linked here  https://pvsc.blob.core.windows.net/extension-builds/ms-python-insiders.vsix
2. Select pylance as the language server for python
3. Open a python file in an untrusted folder
4. See the indicator that there is currently partial language support only
![image](https://user-images.githubusercontent.com/812783/144299810-84e3acd5-0e9c-4e7d-bbf0-b21eb1444ba8.png)

From the screen above you want to move your mouse to the "Learn More" link. But that hover goes away if you scrape just a bit of the "Python" language mode selector since that has a different hover. So you have to route straight up and over to get there.  Not a huge deal, but a bit of a minor annoyance if there was some way to tweak this here. Part of this issue might be that "{ } Python" are all part of the same status item, so you don't expect to lose the hover moving from one part of the button to another.
![LangHitTarget](https://user-images.githubusercontent.com/812783/144300401-6587400d-617b-4178-b29c-312424a39d0c.gif)

**Comment by bpasero** [comment]
I think we had previous discussions around how stable the language status indicator should be (e.g. hover vs. fixed like the notifications center).

@jrieken @misolori was there more discussion around how this should be solved? Since the language status indicator has its own hitzone for bringing up the hover and the "Python" label is another hover provider, you can easily loose the status indicator. Maybe as a workaround the language status indicator should be configured in a way that the hover will stay open longer compared to the others?

**Comment by bpasero** [comment]
@aeschli since you own the logic in [`setupCustomHover` ](https://github.com/microsoft/vscode/blob/5240d97cf3e5e9e71a9bd9deec4f6541e9e1d4dd/src/vs/base/browser/ui/iconLabel/iconLabelHover.ts#L133), 2 ideas come to my mind:
* introduce a `delay` option that makes the hover a bit more stable, so that rich hovers do not disappear so quickly
* introduce a `friends` option where I can pass more `HTMLElement` that we consider as keeping the hover open even though the hover is not originating from that element
