### ISSUE TITLE
Pre-release info is shown in two locations

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#138262]
Testing #138068

The existence of a pre-release version is shown in two locations:

![image](https://user-images.githubusercontent.com/1898161/144250660-48ebfecb-8584-4394-82cf-a71be5ab015f.png)

IMO moving the "Switch to.." button down to the "This extension has a Pre-Release version" message would simplify the UI (and would make the "pre-release" become more prominent in the UI)

**Comment by sandy081** [comment]
Here is the latest UI 

<img width="801" alt="image" src="https://user-images.githubusercontent.com/10746682/144324482-72ee4791-1e28-4ba4-a0a5-d978b9810cbe.png">

This is as per our initial UX design and I like that the buttons are all together like in the tool bar. Another option would be to remove the message `The extension has Pre-Release version available` because `Switch to Pre-Release Version` button is obvious that the extension has a pre-release.

CC @isidorn @misolori

**Comment by weinand** [comment]
If we want to keep the "sea of buttons" then lets drop the additional message.

**Comment by sandy081** [comment]
Removed the pre-release text in the editor given that the button conveys the message and also reduces the clutter of messages in the editor.

**Comment by isidorn** [comment]
Thanks @sandy081 
Makes sense to remove the duplication. I like keeping the 3 buttons, there is enough space and the clutter is not that bad.
