### ISSUE TITLE
Undo (Ctrl + z) not working

### ISSUE THREAD

**Issue by Sokol-ua** [Microsoft/vscode#13827]
- VSCode Version: 1.6.1
- OS Version: Windows 10

Steps to Reproduce:

1.  Ctrl + Z not undoing changes

Checked in keybindings, settings set as expected: { "key": "ctrl+z",  "command": "undo" }

**Comment by gideondsouza** [comment]
Somehow I've been having this SAME issue.

I'd just been busy and constantly for a while have gotten accustomed to using the Menu Edit>Undo.

I do occasionally use a german keyboard layout that switches the z and y. But I tested specifically my English layout on several applications.

Somehow, vscode ONLY does nothing at all when I press `CTRL + Z`. I checked the keybinds also and it says Ctrl + Z is undo.

@Sokol-ua  could I please know why this was closed, also if I can add any more detail?

I'm on VS Code 1.13.0
On  Fedora 25 
I just updated to 1.13 but this issue has been on my machine since 1.10 or earlier.

I also tried using a different keyboard layout in my fedora settings. I have English(India) with Rupee Sign. English(US) and German. If I open the keyboard layout app and press Ctrl + Z the right keys light up, so the keyboard and drivers are working.

**Comment by gideondsouza** [comment]
@stevencl sorry I'm mentioning you here but I'm hoping this doesn't get unnoticed. 

Let me know any information you need me to provide.

**Comment by stevencl** [comment]
Sorry to hear thay ctrl-z isn't working for you @gideondsouza 

Could you take a look at this issue https://github.com/Microsoft/vscode/issues/24057 and see if there is any information there that could help?

cc @alexandrudima

**Comment by gideondsouza** [comment]
Hey thanks @stevencl sorry I didn't look hard enough to find that issue.

ok wow! From this comment : https://github.com/Microsoft/vscode/issues/24057#issuecomment-292318899

When I open the `Define Keybindings` window and press `z` it reads it as `y`. This is so weird! This should only happen if I'm on the German keyboard, every where else I press z and it's z but on vscode z is a y ?

What is going on?

**Comment by alexandrudima** [comment]
@gideondsouza Could you have a look at our Keybinding Troubleshooting guide -- https://github.com/Microsoft/vscode/wiki/Keybindings -- does anything in there resolve the problem for you ?

**Comment by TryingToFindALoginWhichIsNotRegistered** [comment]
I don't understand, while this case is closed, but not fixed. I use Debian Buster (pre-release) and the latest vs-code 1.17.2, German layout.
- when I open vs-code [Strg][Y] is undo.
- once open "Datei" "Einstellungen" "Tastaturkombinationen"
- after closing keybindings (without changing or saving) undo switches to [Strg][Z]
Short: open and close keybindings will correct the settings. Mayby a hint for bug-fixing.
