### ISSUE TITLE
Theme search text not always highlighted in author name

### ISSUE THREAD

**Issue by kimadeline** [microsoft/vscode#138203]
Testing #138084

Steps:
1. Browse for additional color themes
2. Type "tea"
3. Note that most instances of "tea" are highlighted, but the TeaEyes theme author doesn't (see last theme in the screenshot below):

![Screen Shot 2021-11-30 at 10 53 28 AM](https://user-images.githubusercontent.com/51720070/144112263-b0a37db2-9363-4599-8e15-b1ad3c4c4511.png)

**Comment by aeschli** [comment]
That's done by the  quick pick dialog.

**Comment by TylerLeonhardt** [comment]
@aeschli can you point me to your usage of the quick pick so I can get a better understanding why this is behaving this way?

**Comment by aeschli** [comment]
Here's how the quick pick is created: https://github.com/microsoft/vscode/blob/ff970e88e5240b8a3bb28fe5ce105ef44ffcd4ca/src/vs/workbench/contrib/themes/browser/themes.contribution.ts#L143

The items are created here: https://github.com/microsoft/vscode/blob/ff970e88e5240b8a3bb28fe5ce105ef44ffcd4ca/src/vs/workbench/contrib/themes/browser/themes.contribution.ts#L121

**Comment by TylerLeonhardt** [comment]
Oh this is because it just finds the first `tea` instance in the label and the first `tea` instance in the description. The highlight is telling you why it matched the filter not every instance of the filter.

This is working by design in my book. This behavior is more apparent if the quick pick supports fuzzy results.

**Comment by TylerLeonhardt** [comment]
cc @bpasero @chrmarti in case you don't agree
