### ISSUE TITLE
Canvas element is created every time I click into the editor

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#138240]
**Steps:**
* add a breakpoint into `WindowManager.getPixelRatio`
* click into the editor
* => breakpoint is hit

Not sure how expensive that is? Should it be cached?

//cc @alexdima

**Comment by hediet** [comment]
Can the pixel ratio change? If not, we should just cache it.

Just did some performance profiling of 6 seconds of usage. In sum, it just took 7ms:

![image](https://user-images.githubusercontent.com/2931520/148562035-3b751f4e-8bbc-4c54-b938-d0101519d2a3.png)

The function is called often, but it does not have an impact on performance:

![image](https://user-images.githubusercontent.com/2931520/148562225-c2a787fa-7a85-4377-bcd7-3df2ac0e1104.png)

**Comment by yume-chan** [comment]
Yes, pixel ratio can change when a user moves Code window between multiple monitors with different DPI settings, or rarely, when user changes their DPI settings. 

But it's possible to detect when that happens, see https://developer.mozilla.org/en-US/docs/Web/API/Window/devicePixelRatio#monitoring_screen_resolution_or_zoom_level_changes

I think get pixel ratio is very cheap, but re-create canvas as the title says can be expensive. Ideally it should also only happens when pixel ratio changes.

**Comment by alexdima** [comment]
@yume-chan Thank you for the pointer!
