### ISSUE TITLE
Editor enters a `U+00A0` unicode character when I type 

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#138393]
Steps to Reproduce:

0. on macOS ARM
1. `git co ben/dec` 
2. open https://github.com/microsoft/vscode/blob/e8117a08fa8cc5302e647f04f55bde2b76d5a273/test/smoke/src/areas/workbench/data-migration.test.ts#L49
3. change the signature from `async function testHotExit(restartDelay: number | undefined)` to `async function testHotExit(restartDelay: number | undefined, autoSave: boolean | undefined)`
4. => 🐛  a unicode character is entered

![recording](https://user-images.githubusercontent.com/900690/144577676-733ccfd6-900c-4824-8467-85ca4b59975c.gif)

**Comment by hediet** [comment]
I think this is due to Mac inserting a non-breaking space on alt+space (see [here](https://youtrack.jetbrains.com/issue/IDEA-181742#:~:text=Using%20ALT%20SPACE%20on%20Mac,often%20problematic%20in%20source%20code.&text=On%20many%20keyboard%20layouts%20(e.g.,breaking%20spaces%20while%20typing%20fast)).

**Comment by bpasero** [comment]
Yes!

Fixed via:

```json
{ 
    "key": "alt+space", 
    "command": "type", 
    "when": "editorTextFocus",
    "args": { "text": " " } 
}
```
