### ISSUE TITLE
Build spits out seemingly harmless warning

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#138361]
Let's fix the issue or not warn at all, if it isn't one.

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=145209&view=logs&j=4d2898ab-dfbe-557e-92e7-aaac158fdd2f&t=bf591f68-b11f-58a5-2795-b482f67ba1e7&l=14

https://github.com/microsoft/vscode/blob/0573777298ff29b19606818635752c7a702321a3/build/lib/util.ts/#L355

**Comment by lramos15** [comment]
I wouldn't say it's a harmless warning. jschardet doesn't provide a main or browser entrypoint in their package.json which means we have no idea where to load it from. I assume there's a dist/*.min.js file but don't actually check just because I knew there was one for jschardet. This is extremely flaky in that if we add additional packages in the future without the same file structure they won't load if they don't provide an entrypoint. The real fix is this PR being merged https://github.com/aadsm/jschardet/pull/73

**Comment by joaomoreno** [comment]
The maybe let's log it for any package other than the ones we hardcode assumptions to: for now that's jschardet only.

**Comment by lramos15** [comment]
I've suppressed the jschardet warning. Ideally when that PR is added we can warn or even error out on all non entrypoint packages because it is really something to be careful of since the loader has no way of knowing.
