### ISSUE TITLE
List globals first in IntelliSense

### ISSUE THREAD

**Issue by thernstig** [microsoft/vscode#138399]
When using VS Code Intellisense, I always get module-specific completions first. I would rather like to get the globals first.

What I get at the top:
![image](https://user-images.githubusercontent.com/30827238/144598700-308e344b-554d-468d-99b5-b58f8e6525ef.png)

What I see at the bottom of the list:
![image](https://user-images.githubusercontent.com/30827238/144598781-3c41eb90-26cb-4d4f-992b-7fb1776ede4f.png)

Is this something that would make sense?

Or rather, I'd like to configure a sane way to decide what is and what is not shown first in IntelliSense in a more deterministic way.

**Comment by jrieken** [comment]
Sorting of completions is two fold: there is the sorting as extensions define it and than there is sorting based on the current word or word-prefix. There is no sorting based on types like global vs import. The prefix is applied "relaxed", e.g if you want `setInterval` you can type `sInter` and it will be sorted atop etc. The `set` prefix will match those suggestions that are exactly the same word best and are therefore sorter higher. 

We have no plans to introduce type based sorting rules because we believe "type to select" is the fasted way. Also, there is asks for "page by type" and you can configure suggestion to not show certain types
