### ISSUE TITLE
extract TerminalInstanceDragAndDropController into separate file

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#138374]
and add tests?

https://github.com/microsoft/vscode/blob/f86e5d14afe60ceddb339ebc73bbd501f5029312/src/vs/workbench/contrib/terminal/browser/terminalInstance.ts#L1852-L1980

**Comment by Tyriar** [comment]
I like that this one is internal to terminalInstance.ts since we don't export it, it's just organizing things that are internal to TerminalInstance by using a class instead of making it inline. Moving it into another file would mean we need to export it so it will show up in auto import when we never want it outside `TerminalInstance`
