### ISSUE TITLE
The vscode.dev match whole word invalid

### ISSUE THREAD

**Issue by btea** [microsoft/vscode#138309]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version: win10

Steps to Reproduce:

1. Open https://vscode.dev/github/vuejs/vue-next 
2. Select search icon, match the whole word 'patch'. The results are shown in the figure.
![image](https://user-images.githubusercontent.com/24516654/144354959-003323a6-b115-47d8-a66e-321a00f51b36.png)

**Comment by JacksonKearl** [comment]
Thanks for reporting this. Similar to #139063, it appears you are using the github API search rather than the indexed search. The github API search does not support word boundaries so this is expected. What's not expected is that you have no feedback as to why things aren't working. When I run this same search I see this:
![image](https://user-images.githubusercontent.com/8586769/146470223-5d099e65-8b17-46fa-b3c6-eb254fbef245.png)
Do you remember seeing anything like that?

**Comment by btea** [comment]
Hmm, you mean the search results shown in the picture are correct?  How does indexed search work? 😕

**Comment by JacksonKearl** [comment]
Yes, we get the results from the github code search API, and that API does not know about word matching, so the results don't respect the word matching filter. While we could do something like a filter on the client side, it has the potential to get into even more confusing situations (no results appear because all of the subset that got sent were filtered out)

The indexed code search downloads a tarball of the repo to your browser's local storage and searches within it. It supports all search functionality.

**Comment by btea** [comment]
Ok, thank you very much for the answer.
