### ISSUE TITLE
Intellisense is incorrect for `editor.actions.findWithArgs`

### ISSUE THREAD

**Issue by ArturoDent** [microsoft/vscode#138365]
Does this issue occur when all extensions are disabled?: Yes

In `keybindings.json` make a new keybinding:

```jsonc
{
  "key": "alt+p",
  "command": "editor.actions.findWithArgs",
  "args": {
    "|"           // test intellisense at the caret
  }
},
```

Intellisense shows many arg keys that are inaccurate or not implemented.  Here is what I get for intellisense:

```
"findInSelection": false,
"matchCase": true,            // should be isCaseSensitiv
"matchCaseOverride": 0,       // appears to not be implemented
"preserveCase": true,        
"preserveCaseOverride": 0,    // appears to not be implemented
"regex": true,                // should be isRegex
"regexOverride": 0,           // appears to not be implemented
"replaceString": "asdasd",
"searchString": "qweqwe",
"wholeWord": true,            // should be matchWholeWord
"wholeWordOverride": 0        // appears to not be implemented
```

These appear to be the correct and implemented args to this command:

```
searchString?: string;
replaceString?: string;
isRegex?: boolean;
matchWholeWord?: boolean;
isCaseSensitive?: boolean;
preserveCase?: boolean;
findInSelection?: boolean;
```

---------------------
Version: 1.63.0-insider (user setup)
Commit: 68a1e2f872f8869b004eec284917782474730e0b
Date: 2021-12-02T05:15:40.605Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

**Comment by ArturoDent** [comment]
Related: https://github.com/microsoft/vscode/issues/138366

**Comment by dimateos** [comment]
This issue persists as of vscode `1.78.2`

I was going to open an bug issue mentioning that some params were not working... ***when in fact I was using the ones suggested by the intellisense e.g. `"regex"` instead of `"isRegex"`.***

A while back I opened: #180835 about how the command does not resolve variables whereas `workbench.action.findInFiles` does. Also related https://github.com/microsoft/vscode/issues/151311.

I guess `editor.actions.findWithArgs` needs some love to be more consistent feature-wise with `workbench.action.findInFiles`.
