### ISSUE TITLE
Custom modal no longer renders markdown links

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#138363]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.63.0-insider (user setup) 68a1e2f872f8869b004eec284917782474730e0b
- OS Version: Windows 11

Steps to Reproduce:

1. Install this extension https://github.com/joyceerhl/vscode-custom-modal-repro/blob/main/vscode-custom-modal-repro-0.0.1.vsix (or build it yourself from https://github.com/joyceerhl/vscode-custom-modal-repro)
2. Command Palette > Hello World
3. 🐛 Dialog that appears is created with `useCustom` but displays unformatted markdown links

This used to work, in fact `useCustom` was how RemoteHub worked around https://github.com/microsoft/vscode/issues/133936 and was verified in the September milestone (pinged you on Slack with the RemoteHub issue link)

![image](https://user-images.githubusercontent.com/30305945/144491294-7c7362a7-b8c1-44bd-9cad-0d5036864bca.png)

**Comment by alexdima** [comment]
@joyceerhl I have tried with the linked repro extensions the following versions:
* main - doesn't render markdown
* release/1.62 - doesn't render markdown
* release/1.61 - doesn't render markdown
* release/1.60 - doesn't render markdown
* release/1.59 - doesn't render markdown

I consistently get:
![image](https://user-images.githubusercontent.com/5047891/144573707-353e4944-8562-4293-9863-c702ce536ee6.png)

I cannot run a bisect to identify the problematic commit because I cannot find any commit where this ever worked. My understanding from the issue #133936 is that modal dialogs did not render markdown links and it looks like now they continue to not render modal links. I believe the issue #133936 was closed by the robot without having been implemented.

**Comment by joyceerhl** [comment]
Hm, based on this comment from @bpasero https://github.com/microsoft/vscode/issues/133936#issuecomment-928911834 my understanding was that rendering markdown links isn't supported in native modals, but they are supported for the custom modals. I must have misunderstood:

> Unlikely that there is standard API across platforms to render links in native dialogs because typically the main actions are provided via buttons.

> Though we could switch to using our custom dialogs if we detect markdown links.

**Comment by bpasero** [comment]
That comment was meant to indicate that we could make markdown links work in our custom dialog, I did not want to indicate that they are supported today.

**Comment by sbatten** [comment]
this is not possible today in custom dialogs with extension dialogs
