### ISSUE TITLE
VSC debug issue

### ISSUE THREAD

**Issue by MsMacDaddy** [microsoft/vscode#138568]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1.no steps to reproduce, it was working on run and then wasn't the next. I have no idea what happened. 

I keep getting a error when I debug and run my HTML doc. I don't know how to fix it, so I just want to factory reset everything and start over fresh. Apparently uninstalling and reinstalling doesn't help as I tried...and am still getting the same issue.

This is the error I'm getting:

crbug/1173575, non-JS module files deprecated.
chromewebdata/(index)꞉6545:22:6770

I have no idea how to fix this or even what the direct issue is. I've looked online and tried the 'clear out the launch.json', but that didn't work. I have an HTML assignment due in 3 days. I hope someone out there can help me 

![Capture](https://user-images.githubusercontent.com/95665193/144956173-63b92844-1d65-45d6-ba4b-79eae34c5e49.PNG)

**Comment by connor4312** [comment]
It looks like you have your launch config set up to hit a server running on `localhost:8080`, but there's nothing running. You likely either want to:

1. Run the server, if this is correct
2. Instead of `url`, use a `file` and point to the `html` file you want to open.

Here's the relevant docs on setting this up: https://code.visualstudio.com/docs/nodejs/browser-debugging#_launching-browsers
