### ISSUE TITLE
Web: extension API does not work on Web

### ISSUE THREAD

**Issue by AgentofSpyral** [microsoft/vscode#138550]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

According to the [docs](https://code.visualstudio.com/api/extension-guides/web-extensions) I am expecting `vscode.extensions.getExtension('vscode.git')` to work on web as "web extensions still have access to the full VS Code API".  I am getting an error saying `Git` extension is not loaded instead. For context, I am trying to get git info of the currently opened file on vscode.dev / github.dev. 

Steps to Reproduce:

1. Add `vscode.extensions.getExtension('vscode.git')` & `"extensionDependencies": ["vscode.git"]` to web extension
2. Run Web Extension
3. Receive following error:
```
Cannot activate the 'test' extension because it depends on the 'Git' extension, which is not loaded. Would you like to reload the window to load the extension?
```

**Comment by alexdima** [comment]
@AgentofSpyral 

The builtin extension `vscode.git` executes only on a nodejs extension host. The reason is because the builtin `vscode.git` extension needs to spawn `git.exe` and that is possible only on the nodejs extension host.

Extension dependencies are fulfiled across extensions only when extensions execute on the same extension host. 

So if your extension has a dependency on the `vscode.git` extension, your extension cannot run on the web worker extension host, since the `vscode.git` extension runs only on the nodejs extension host.

You can, however relax your dependency into an optional dependency. To do so, you no longer need to declare `"extensionDependencies": ["vscode.git"]` in your `package.json` and, at runtime, simply probe the presence of `vscode.git` on the same extension host using `vscode.extensions.getExtension('vscode.git')`. If that returns `undefined`, it means `vscode.git` is either not running at all or running on a different extension host. If that returns a real object, it means that `vscode.git` is running on the same extension host as your extension.

**Comment by AgentofSpyral** [comment]
@alexdima Thanks for the explanation Alex that was really helpful. 

In this case, what would be the recommended way to get the name of the branch of the currently opened file on VS Code Web? Is there a VS Code Web API for that?

**Comment by alexdima** [comment]
> In this case, what would be the recommended way to get the name of the branch of the currently opened file on VS Code Web? Is there a VS Code Web API for that?

Do you mean at `vscode.dev` / `github.dev` or when running locally? When running locally you can probe for `vscode.git` and use it when available.

**Comment by AgentofSpyral** [comment]
Sorry for the confusion, I was referring to when running on `vscode.dev / github.dev`

**Comment by alexdima** [comment]
That is a good question, I also don't know. cc @joaomoreno @joyceerhl for insights.

**Comment by joyceerhl** [comment]
Do these two do what you want? 
![image](https://user-images.githubusercontent.com/30305945/145099042-d8b60200-9366-45c6-8793-df0fd3ca34e5.png)

If you're looking for the branch name specifically, that is always tracked in the branch picker status bar item in the bottom left

![image](https://user-images.githubusercontent.com/30305945/145099266-bd4bb3a7-7cc0-4d55-9c8f-62da49e4830a.png)

**Comment by AgentofSpyral** [comment]
@joyceerhl Since I won't be able to run `vscode.extensions.getExtension('vscode.git')` in my extension on `vscode.dev / github.dev` I don't think this would work for me. Is there an API where I can retrieve the branch name from the branch picker status bar?

**Comment by joyceerhl** [comment]
@AgentofSpyral there's currently no api for this. cc @lszomoru who owns the git-base extension that is web-enabled

**Comment by lszomoru** [comment]
@AgentofSpyral, as stated by @joyceerhl, at the moment there is no mechanism for an extension to get the git repository details on the web but this is something that we are looking into in the near future.

**Comment by AgentofSpyral** [comment]
@lszomoru @joyceerhl @alexdima Thank you for the help! I will file a feature request for this instead.
