### ISSUE TITLE
Breakpoints Moving to Different Lines Node.js Debugger (TypeScript & Jest)

### ISSUE THREAD

**Issue by fishcharlie** [microsoft/vscode#138560]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.62.3 (Universal) Commit: ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
- OS Version: macOS 12.1 Beta (21C5045a)

Steps to Reproduce:

1. `git clone https://github.com/dynamoose/dynamoose.git`
2. `cd dynamoose`
3. `git checkout debuggingBreakpointFix`
4. `npm i`
5. Open project in VS Code
6. Set breakpoints on lines 15 & 18 of `lib/index.ts`
7. Open Run and Debug tab of VS Code
8. Run `Debug Jest Tests`
9. Notice that breakpoints move to lines 6 & 10

Expected behavior:

Breakpoints to not move to different lines

Current behavior:

Breakpoints move to different lines

---

Other Information:

- [Stack Overflow question](https://stackoverflow.com/q/70252650/894067)
- Video recording: attached below
- This also occurs in GitHub Codespaces

https://user-images.githubusercontent.com/860375/144931675-c24f3f1e-8a89-41ea-8f1b-10512f9de275.mp4

**Comment by connor4312** [comment]
This is because Babel is transforming the script and rewriting its sourcemaps, whereas we already see the compiled file on disk and set sourcemaps from that, both files (the virtual transformed version, and the one on disk) existing at the same path. Therefore we set breakpoints at all the candidate positions, which results in the behavior you see.

I would recommend adjusting your test setup. This is the recommended way to use TypeScript with Jest, which works without any extra configuration: https://jestjs.io/docs/getting-started#using-typescript

Alternately, to avoid transforming the already-compiled code and fix this issue, you can add this to your jest.config.js:

```
	"transformIgnorePatterns": ["/dist/.+\\.js"]
```

**Comment by fishcharlie** [comment]
Adding `transformIgnorePatterns` worked perfectly. Jest's documentation is pretty bad in this regard.

I can't thank you enough @connor4312! I realize now this isn't a VS Code issue, so I **truly** appreciate you answering and pointing me in the right direction regardless. Thank you again!!
