### ISSUE TITLE
Sideload web extension onto vscode.dev results in Content Security Policy error

### ISSUE THREAD

**Issue by AgentofSpyral** [microsoft/vscode#138623]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: Latest
- OS Version: VS Code Web

Steps to Reproduce:

1. Sideload extension  onto vscode.dev  following the [docs](https://code.visualstudio.com/api/extension-guides/web-extensions#test-your-web-extension-in-on-vscode.dev)
2. Get the following errors:
```
Refused to connect to 'http://localhost:50000/dist/extension.js' because it violates the following Content Security Policy directive: "connect-src https: wss:".
Refused to connect to 'http://localhost:50000/dist/extension.js' because it violates the document's Content Security Policy.
```

Solution: Using URL provided by `localtunnel` works

**Comment by AgentofSpyral** [comment]
Solution: Using URL provided by localtunnel works

**Comment by devhawk** [comment]
I hit this same issue. Seems like the docs should not suggest an approach that basically never works

**Comment by AgentofSpyral** [comment]
@devhawk I agree. Also using URL provided by localtunnel works on vscode.dev but not on github.dev. Will reopen issue to get some input from the vscode team

**Comment by JacksonKearl** [comment]
Are you using a chromium based browser? The docs mention that in non-chromium browsers a tunnel is needed and provide steps on how to use one.

**Comment by JacksonKearl** [comment]
Assigning @orta as the author of https://github.com/Microsoft/vscode-docs/commit/35d12911a3103fe61c226037ae33e54d8f874b02

**Comment by devhawk** [comment]
I am using a chromium based browser: Microsoft Edge Version 96.0.1054.62 (Official build) (64-bit).

According to dev tools, it's a content security policy issue. 

* `Mixed Content: The page at 'https://vscode.dev/' was loaded over HTTPS, but requested an insecure element 'http://localhost:5000/resources/n3-logo.png'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html`
* `Refused to connect to 'http://localhost:5000/dist/web/extension.js' because it violates the following Content Security Policy directive: "connect-src https: wss:".`

**Comment by alefragnani** [comment]
Same here. 

Chromium based browsers (Edge and Chrome itself), running on macOS Big Sur. The localtunnel approach, on the other hand, doesn't work for me. The `Click to Continue` button doesn't _continue_ 😞

**Comment by orta** [comment]
Might be better to just revert it then, the technique worked fine for me with the  Playground but I perhaps I was holding It differently
