### ISSUE TITLE
Smoke test failure: Data Loss (insiders -> insiders) verifies that "hot exit" works for dirty files (without delay)

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#138614]
```
  1) VSCode Smoke Tests (Electron)
       Data Loss (insiders -> insiders)
         verifies that "hot exit" works for dirty files (without delay):
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/__w/1/s/test/smoke/out/main.js)
      at listOnTimeout (internal/timers.js:557:17)
      at processTimers (internal/timers.js:500:7)
```

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=145836&view=logs&j=4d2898ab-dfbe-557e-92e7-aaac158fdd2f&t=aaa04083-6c0b-5a33-e907-3d845b07f0b5&l=91.

[Wiki: Dealing with Test Flakiness](https://github.com/microsoft/vscode/wiki/Dealing-with-Test-Flakiness)

**Comment by bpasero** [comment]
🤷 , needs my new logging infrastructure which I just pushed. I suspect that VSCode is not starting properly and/or does not provide the driver hook, which would hint to https://github.com/microsoft/vscode/issues/137731

Will monitor failing tests over the next days and tweak the logging to hunt this down, but for now this is not actionable in code.

**Comment by Tyriar** [comment]
https://dev.azure.com/monacotools/a6d41577-0fa3-498e-af22-257312ff0545/_build/results?buildId=146894

**Comment by bpasero** [comment]
@Tyriar both errors indicate that the `readme.md` file cannot be opened.

```
setValue .quick-input-widget .quick-input-box input readme.md
Error: Timeout: get elements '.quick-input-widget .quick-input-list .monaco-list-row .label-name' after 20 seconds.
```

We set a value into quick pick and after 20 seconds the picker did not show any results.

```
Error: Timeout: get element '.tabs-container div.tab.active[aria-selected="true"][data-resource-name$="readme.md"]' after 20 seconds.
      at poll (/Users/runner/work/1/s/test/automation/out/code.js:65:19)
      at async Code.waitForElement (/Users/runner/work/1/s/test/automation/out/code.js:188:16)
      at async Editors.waitForActiveTab (/Users/runner/work/1/s/test/automation/out/editors.js:33:9)
      at async QuickAccess.openFile (/Users/runner/work/1/s/test/automation/out/quickaccess.js:76:9)
```

Similar, `QuickAccess.openFile` is triggered, but the file somehow not opening. This one is interesting because it looks like the search result was there but the file didn't open. As you can see from the screenshot:

![image](https://user-images.githubusercontent.com/900690/146246794-bdc44b95-d2fe-410f-a0c9-d35cb23c3701.png)

**Comment by Tyriar** [comment]
@TylerLeonhardt the above screenshot shows the quick access util to open a file is failing, any ideas how this could happen?

https://github.com/microsoft/vscode/blob/224701f74d0f275bbe814f3689729ec323499478/test/automation/src/quickaccess.ts#L82-L88

Enter might be getting triggered before the result is ready for the enter?

**Comment by Tyriar** [comment]
Oh, this is being tracked in https://github.com/microsoft/vscode/issues/139230

**Comment by bpasero** [comment]
Oh, I figured out that my retry logic for quick open was flawed because waiting for quick pick elements will actually throw on timeout, pushed https://github.com/microsoft/vscode/commit/fdc4b7101da7d677339e32eee74bb2f6b5c51ab4.

Still, https://github.com/microsoft/vscode/issues/139230 remains flaky and needs a fix.
