### ISSUE TITLE
Terminal breaks when dragging to a different group, only when created in editor area via command

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#138603]
Repro is to run create new terminal in editor area command and drag and drop terminal to right group:

![image](https://user-images.githubusercontent.com/2193314/145053464-ff50eef2-41bf-4b30-b034-c66429a7ab6a.png)

@lramos15 spotted this in https://github.com/microsoft/vscode/issues/138452#issuecomment-987181581

**Comment by Tyriar** [comment]
Reverted in 8605d7a

**Comment by bpasero** [comment]
@Tyriar @meganrogge @lramos15 fyi with my fix for https://github.com/microsoft/vscode/issues/138452 I noticed how `terminalEditorInput` was not providing the `EditorInputCapabilities.Singleton`, which I now added:

https://github.com/microsoft/vscode/blob/6c89a38cfcc8d6ae4b4804302b709f5256e4a02b/src/vs/workbench/contrib/terminal/browser/terminalEditorInput.ts#L58-L60

This is an important hint to the workbench that the editor input cannot be opened multiple times across editor groups. With this capability I can no longer reproduce the original issue, or maybe it was fixed otherwise?

**Comment by meganrogge** [comment]
Yes it was fixed with https://github.com/microsoft/vscode/pull/139019

**Comment by meganrogge** [comment]
merged into the release branch

**Comment by goodspark** [comment]
I'm on 1.63.2 and this doesn't seem to be fixed.

Version: 1.63.2 (user setup)
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:40:02.816Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by goodspark** [comment]
FWIW, moving around terminals works for local workspaces but fails in the same manner as described in the all the linked issues when connected to a remote workspace with the remote SSH extension. Something in the 1.63.* release broke this, as 1.62.3 seems OK.

**Comment by meganrogge** [comment]
discovered a few more bugs, will be fixed soon

https://github.com/microsoft/vscode/pull/139388
