### ISSUE TITLE
Bug while commenting the code

### ISSUE THREAD

**Issue by sarangkkl** [microsoft/vscode#138652]
Issue Type: <b>Bug</b>

Hey vs code team i am using vs code editor it is very powerful i am proud to use it but here is an issue where if its get fixed i will happy when we have big lines of code in which many are are already commented then it uncomment the previous one what should happen is all should get commented

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:11:14.551Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.77GB (6.45GB free)|
|Process Argv|. --crash-reporter-id 0e49e413-8ffc-438b-bad3-1e28baaae2cb|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.14.0
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.2.2
javascript-ejs-support|Dig|1.3.1
es7-react-js-snippets|dsz|3.1.1
prettier-vscode|esb|9.0.0
auto-close-tag|for|0.5.13
auto-rename-tag|for|0.1.9
stylelint-plus|hex|0.56.6
unity-code-snippets|kle|1.3.0
csharp|ms-|1.23.17
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.12.0
jupyter|ms-|2021.10.1101450599
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
vsliveshare|ms-|1.0.5090
vscode-react-native|msj|1.8.1
color-highlight|nau|2.5.0
live-sass|rit|3.0.0
LiveServer|rit|5.6.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsaa593:30376534
pythonvs932cf:30408637
vscop804:30404766
vs360cf:30404996
vsrem710cf:30405999
vscexrecpromp3c:30407761

```

</details>

**Comment by IllusionMH** [comment]
/gifPlease

Please provide recording of a problem or at least language and code before and after.

**Comment by sarangkkl** [comment]
OK let me write again while editing html code or any kind of code when we had to comment a lot of lines what we do we select that portion and press control forward / this way we comment the thing but what issue occur here if we some code which is already comment by us and lies with in the selected region then after pressing control forward slash will uncomment the comment and comment the code what i am requesting is that while writing code we dont want come code to be executed so what we do simple comment it but isssue occuur while commenting that if there is some line of code which is already commented is uncomment and become executable code.. 



Can you separate the comment part and make a term so that instead of saying this is comment we say we dont this code to be executed it seems same but it is not same at deeper level comment means why giving information of program so in future i get to know not wanting the code to be executed means i want the code to be here but want not to be executed the code is there for the refrence of copy paste

**Comment by ArturoDent** [comment]
Not sure I know exactly what you are requesting, but are you asking to **toggle** existing comments so 

```js
aasdasd
// asdasd
asdasd
```

becomes 

```js
// adasd
asdasd
// asdsd
```

If so, there is an extension https://marketplace.visualstudio.com/items?itemName=ArturoDent.toggle-comments&ssr=false#overview that would do that.

Otherwise could you make a gif that shows what you want?

**Comment by aeschli** [comment]
I think I know what you mean. But to be sure, the best would be if you added a concrete code example

Here is my sample:
```html
<html>
    <head>
        <!-- comment-->
    </head>
</html>
```
- select all inside the `<html>` body, press ctrl + '/'
- the result is
```html
<html>
    <!-- <head>
        <!-- comment-->
    </head> -->
</html>
```
which is not valid html, as you can't have `-->` in the comment

This is in fact the expected behavior. The comment command is purely textual and just adds or removes the languages comment tokens. It does not modify the content inside the comment. If it were to modify the content, it would need much more language knowledge, e.g. it could encode `>` with `&gt`. Or just remove the `<!--`  and `-->`. As there are many ways to do that, it is left to the user.
HTML is a bit special too as it doesn't have a single line comment like `//`. There things are much simpler.

We currently have no plans to provide a more sophisticated, language ware comment command.

**Comment by aeschli** [comment]
@sarangkkl If this is not what you meant, please add a sample code with steps and I'm happy to reopen if you found a bug.
