### ISSUE TITLE
Evil Privacy Invasive Proprietary Annoying prompt

### ISSUE THREAD

**Issue by pklamp** [microsoft/vscode#138752]
![evil-privacy-invasive-proprietary-anoying](https://user-images.githubusercontent.com/95860303/145397277-e8096007-0269-4b67-ae89-07dc3837869e.png)

Version: 1.63.0 (user setup)
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

I fucking hate the massive pile of garbage that vscode has become. Instead of being an open source tool, microsoft filled it with proprietary closed source protocols, extensions, and code. 

Vscode long ago stopped being an open source tool, and became a microsoft proprietary product designed to push azure cloud services and other microsoft products. This is awful. 

Today it feels like vscode users are the product, in the sense that microsoft uses the users to futher only it's own products and offerings even when they are inferior, in a very evil and opaque manner. 

The worst example of this is settings sync, whose name was stolen, and then implemented in a proprietary way by microsoft, with all commands designed to confuse users, and then microsoft started disabling the settings sync extension. 

Where before people would think that they're configuring VSCODE with settings.json, microsoft instead keeps a lot of privacy invasive hidden data within the product's internal database, and collects a lot of data and state that should never been collected. 

I hate this extension pop-up. The mere fact that it even showed up with the recommender extension disabled, and after I uninstalled the powershell extension, it is fucking annoying. 

My feelings are: 
![81917194](https://user-images.githubusercontent.com/95860303/145397968-18861dd8-0725-4683-ad42-ba3b95b727b6.jpg)

**Comment by pklamp** [comment]
Same feeling as: https://github.com/shanalikhan/code-settings-sync/issues/1322

**Comment by gjsjohnmurray** [comment]
`"extensions.ignoreRecommendations": false`

**Comment by isidorn** [comment]
Thanks for your feedback.
As @gjsjohnmurray already pointed out you can disable extension recommendations using the following setting:
`"extensions.ignoreRecommendations": true`.
You can also disable telemetry and any collection of data using
`"telemetry.telemetryLevel": "off"`

As for the settings sync extension / built in - this was done in collaboration with the author of the settings sync extension. More details can be found here https://github.com/microsoft/vscode/issues/78966

Since there are no actions planned here I will close this issue. I will also have to lock it since it is using inappropriate language that violates our [Code of Conduct](https://github.com/microsoft/vscode#code-of-conduct).

Thank you for your understanding
