### ISSUE TITLE
Japanese IME doesn't work well on macOS and Linux

### ISSUE THREAD

**Issue by tamuratak** [microsoft/vscode#138704]
Version: 1.63.0-insider
Commit: 7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e
Date: 2021-12-06T21:53:07.969Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0

Steps to Reproduce:

1. Open a new file
2. Choose Hiragana in the menu bar https://github.com/microsoft/vscode/wiki/IME-Test#windowsmac-japanese
3. Copy a text:
```
先生
```
4. Start writing right after the text.
5. Type the left cursor.

https://user-images.githubusercontent.com/10665499/145342541-251264a8-03f3-4855-a760-0023c4537208.mov

**Comment by yuuho** [comment]
I have similar symptoms in my ubuntu18.04 environment.
I updated the VSCode version of my environment today. ( VSCode 1.63.0 )

If I convert some Japanese word and then type in the next word without confirming with Enter, the conversion result of the previous word will be displayed at the beginning of the place where the conversion result of the current word should be displayed.
Generally, in Japanese IME, it is not necessary to confirm with Enter if you want to input a new word after converting some word.

I think this is a bug and needs to be fixed.

**Comment by alexdima** [comment]
I think I understand the problem of the OP, related to pressing arrow left.

@yuuho Could you please show a concrete example, like pressing `s`, `e`, etc. and what should happen vs. what happens. This is the kind of detail I am looking for -- https://github.com/microsoft/vscode/wiki/IME-Test#windowsmac-japanese

**Comment by tamuratak** [comment]
I have a similar problems with @yuuho too. I have reported a problem whose reproducible steps are easy.

**Comment by alexdima** [comment]
@tamuratak Thank you, I can reproduce what you describe. I just wanted to make sure @yuuho has the exact same problem because @yuuho did not mention pressing arrow left.

**Comment by yuuho** [comment]
@alexdima 
It's not exactly the same symptoms as the first video of @tamuratak.
The left arrow keys do not duplicate the 「先生」 in large numbers.

I haven't been able to record the key press due to a screen recording environment problem, but at the beginning of the video below, I press the same key as the first video of @tamuratak.

https://user-images.githubusercontent.com/26864683/145372570-bd582e0b-6169-4a63-bf2a-f5a97b1b62b5.mp4

**Comment by alexdima** [comment]
Mainly as notes for myself:

### Scenario 1 (macOS arrow keys)
* (I have tested this on VS Code 1.62.3 so this is **not a 1.63.x regression**)
* using Japanese - Kana / Hiragana
* place cursor at the end of a line with the content `先生`
* press <kbd>A</kbd>, <kbd>A</kbd>, <kbd>A</kbd>, <kbd>A</kbd>
* press <kbd>LeftArrow</kbd>, <kbd>LeftArrow</kbd>, <kbd>LeftArrow</kbd>, <kbd>LeftArrow</kbd>
* expected outcome: arrow keys can be used to "select" to `先生` and back:

https://user-images.githubusercontent.com/5047891/145405299-6a22573e-9d0a-457e-a86d-36ea306036f2.mp4


### Scenario 2 (macOS two words + space key)
* I am having some trouble getting the IME to behave 100% as in your recording, but I also don't think this is a **1.63.x regression**
* using Japanese - Romanji / Hiragana
* place cursor at the end of a line with the content `先生`
* type `konnnitiha`, `konnnitiha` and <kbd>Space</kbd> many times
* expected outcome: the spacebar can go and "select" various parts of the composition and the choses a suggestion:


https://user-images.githubusercontent.com/5047891/145410463-731d7201-3ddf-4c94-9257-9558a0ebcc07.mp4


@tamuratak Did I get the two macOS scenarios correct? What precise input method are you using (since I didn't quite get the same behavior as you)? I have tried with both "Japanese - Kana" and "Japanese - Romaji"

@yuuho I am about to set up a xubuntu 20.04 vm for testing. How did you set up the input? Are you using `fcitx`. If yes, which input method are you using from the following:
![image](https://user-images.githubusercontent.com/5047891/145411382-f39f2aec-6a2f-4ae6-ae22-09e042299a8e.png)

**Comment by tamuratak** [comment]
> Did I get the two macOS scenarios correct? 

Yes.
> What precise input method are you using (since I didn't quite get the same behavior as you)? I have tried with both "Japanese - Kana" and "Japanese - Romaji"

"Japanese - Romaji". I have set "Live Conversion" off.

![Screen Shot 2021-12-10 at 7 38 43](https://user-images.githubusercontent.com/10665499/145488407-a3de2912-802b-4ad4-93eb-5350a5e97201.png)

**Comment by yuuho** [comment]
> @yuuho I am about to set up a xubuntu 20.04 vm for testing. How did you set up the input? Are you using `fcitx`. If yes, which input method are you using from the following: ![image](https://user-images.githubusercontent.com/5047891/145411382-f39f2aec-6a2f-4ae6-ae22-09e042299a8e.png)

@alexdima
I'm not using fcitx. I am using ibus.
And the IME I'm using is mozc.

| name | ver |
| --- | --- |
| ibus       | 1.5.17-3ubuntu5.3                    |
| ibus-mozc  | 2.20.2673.102+dfsg-2ubuntu0.18.04.1  |

**Comment by kahsa** [comment]
Same issue on ArchLinux

**Comment by yume-chan** [comment]
In #139257, pressing <kbd>Left Arrow</kbd> also reveals content before when using Traditional Chinese IME.

I personally can also reproduce this issue with Pinyin IME on macOS

https://user-images.githubusercontent.com/1330321/146311173-e8395f68-cbcb-48d4-97df-6e9fa0d2967b.mov

Version: 1.64.0-insider (Universal)
Commit: b823936907f86ded04a152a4af202d0fc8423522
Date: 2021-12-15T05:13:30.794Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0

**Comment by sewege11** [comment]
I have a similar problem in VSCode version 1.63.1 on Windows 10 Pro.
In my case I had a problem when using ATOK as Japanese input method.
There was no problem with Microsoft IME and Google IME.

https://user-images.githubusercontent.com/85084148/146316254-f723eecc-0fec-4047-b001-47342b2bbfc1.mp4

**Comment by sarashinanikki** [comment]
Is any update?

I tried binary-search for commit log between tag: 1.62.3 and tag: 1.63.0, finally I found commits which make this bug.
In my search, until `18c66923161ec2735858cc3973c849aaf7567a1d`, there has not been such a bug. This bug has appeared since `337d661e61c65580777a7dd1b579c0bb718ecb82`.

In fact, there are two commits between `18c66923161ec2735858cc3973c849aaf7567a1d` and `337d661e61c65580777a7dd1b579c0bb718ecb82 `. But I cannot confirm this bug because both of them build failed.

**Comment by sarashinanikki** [comment]
(Sorry, I deleted my previous comment because it was wrong)

@alexdima 

## Scenario 1 (macOS arrow keys)

This bug appears 1.59.0 or earlier.

## Scenario 2 (macOS two words + space key)

I tried binary-search for commit log between tag: 1.62.3 and tag: 1.63.0, finally I found commits which make this bug.
In my search, this bug caused at 31fff5074d286d845d6de9e1bbc09aafa266a062.
Reviving deleted row at `src/vs/editor/browser/controller/textAreaInput.ts: 292`, I got the expected outcome (at least, in my environment).

pls confirm.

**Comment by alexdima** [comment]
@sarashinanikki https://github.com/microsoft/vscode/commit/31fff5074d286d845d6de9e1bbc09aafa266a062 fixes composition for Korean by avoiding clearing the `<textarea>` we use for input when we receive the `compositionstart` event. Typing Korean results in multiple `compositionstart`/`compositionend` events and clearing the `<textarea>` during `compositionstart` breaks internal IME state, it prevents Korean composition from working correctly. 

That being said, the change in 31fff5074d286d845d6de9e1bbc09aafa266a062 is effectively keeping some content from the same line in the `<textarea>` we use for input. This leads to two classes of issues:
* editing wise, it looks like now it is possible to interact in unexpected ways with the previous content (like pressing arrow keys and then changing some previous content).
* display wise, the previous content on the line from the `<textarea>` is now visible and by using arrow keys or space the `<textarea>` might end up revealing it. I think we might be better off rendering the `<textarea>` wider, over the entire current line, such that it covers the editor's text completely.

**Comment by alexdima** [comment]
The PR https://github.com/microsoft/vscode/pull/139394 fixes the display problem where the conversion result of previous words are rendered when converting. I believe it covers the problems reported by @yuuho, @yume-chan and @sewege11 and the macOS [scenario 2](https://github.com/microsoft/vscode/issues/138704#issuecomment-989885734) from @tamuratak, so only [scenario 1](https://github.com/microsoft/vscode/issues/138704#issuecomment-989885734) remains.

**Comment by alexdima** [comment]
Finally, regarding scenario 1 (repeating steps here):
* on macOS, using Japanese - Romaji / Hiragana
* toggle on Live Conversion
* place cursor at the end of a line with the content `先生`
* press <kbd>A</kbd>, <kbd>A</kbd>, <kbd>A</kbd>, <kbd>A</kbd>
* press <kbd>LeftArrow</kbd>, <kbd>LeftArrow</kbd>, <kbd>LeftArrow</kbd>, <kbd>LeftArrow</kbd>
* observe that `先生` gets duplicated

I can reproduce this directly in a `<textarea>` in Chrome, like the one I'm typing this comment in or the one at https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea . I would like to ask that you please create an issue upstream regarding this:

https://user-images.githubusercontent.com/5047891/146614598-ed581ea4-aa1e-4a6a-8509-810040c5e307.mp4
