### ISSUE TITLE
Behavior of "back" in the browser

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode#138864]
We received user feedback that they were anticipating the "back" button on the mouse to navigate to the previous thing in the web editor, rather than back to the browser homepage.

@bpasero - In chatting with @joaomoreno, he mentioned you have likely given this much thought in the past, so we wanted to start an issue for a discussion on the space, i.e. history, problems, and best practices.

**Comment by bpasero** [comment]
I am not a big fan of bringing that behaviour back (we had it in the very beginning). Because you end up messing with the browser history ([`pushState`](https://developer.mozilla.org/en-US/docs/Web/API/History/pushState)). And you always have to ensure that you can restore whatever there is in history when the user goes back, or make sure to clean up stale state (which I am not even sure is possible).

I remember that I was super happy when I was able to drop our use of the DOM API for history and have everything under our control. 

Btw one thing that goes hand in hand is indicating the current file in the URL so that the navigation becomes a bit more obvious. This would require us to identify every possible editor with a URL too.

**Comment by bamurtaugh** [comment]
The reasoning you provide makes a lot of sense. 

> Would it make more sense to find a way to bind the "back" mouse button to a command we own to provide this functionality?

That could be interesting  - sounds like allowing users to configure their mouse to go back in the editor if they want, but not providing this by default to avoid issues mentioned above. Is there an existing command we own that'd provide this functionality? Something like this https://github.com/microsoft/vscode/issues/8641, but perhaps even more generalized to going back to any previous state, not just navigating history?

**Comment by bpasero** [comment]
Yeah we have official commands for this:
* `workbench.action.navigateBack`
* `workbench.action.navigateForward`

This is likely as hard to get from browsers as it is hard to get browser reserved keybindings like `Cmd+T` or `Cmd+W`. I think that was my original reason why I had to use the browsers history API.
