### ISSUE TITLE
Ctrl+K S to save all files stops working randomly

### ISSUE THREAD

**Issue by panyann** [microsoft/vscode#138839]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.63
- OS Version: Windows 10 Enterprise 10.0.19042 N/A Build 19042

Steps to Reproduce:

1. Try to save all files using the shortcut ctrl+K S

What's interesting is that it sometimes works, but more often it just doesn't, depends on a day. I was using that shortcut for last few years and it started to stop working recently and after hitting ctrl+K and then S, it just writes "s" in my file. Today it doesn't work at all, even after the update and disabling extensions.
If I'll try to save all files via the File > Save All, then it saves correctly.

**Comment by bpasero** [comment]
Any chance we can rule out a keybinding issue from the save issue. Can you assign a different keybinding and see if that helps?

**Comment by alexdima** [comment]
Here are the steps to troubleshoot the keybinding. Could you please [try the following](https://github.com/microsoft/vscode/wiki/Keybinding-Issues#basic-troubleshooting):

* Run the command `F1 > Developer: Toggle Keyboard Shortcuts Troubleshooting`
* This will activate logging of dispatched keyboard shortcuts and will open an output panel with the corresponding log file.
* Press exactly the keybinding you desire.
* check what VS Code detects and what command is invoked.

If you are having trouble understanding the output, please feel free to paste here and I can try to help.

**Comment by panyann** [comment]
Thanks for replies, but today it works... I will come back and inform you, as soon as the issue will occur again.

**Comment by bpasero** [comment]
k

**Comment by panyann** [comment]
![image](https://user-images.githubusercontent.com/22815508/146160572-47f1fb3a-233d-49fd-8539-5adff81f7eb4.png)
This is what happens when ctrl+K S doesn't work and only "s" is written... I'm pretty sure that it happens because the PC was hibernated with VSC opened.

**Comment by bpasero** [comment]
So it looks like the keybinding resolves to `S` even though you typed `Ctrl+K S`.

**Comment by alexdima** [comment]
@panyann Thank you for the trace. This indicates that `Ctrl+K` in the `Ctrl+K S` that you are pressing is not reaching VS Code. From the keypress `Ctrl+K`, only the `Ctrl` reaches us. There is nothing we can do on our side if we don't receive the keydown event from the OS. I have seen many similar issues in the past (but with different keypresses), and they are always caused by something local to the machine:
* some Windows setting which results in the OS consuming the keypress and not dispatching it to the active window
* some 3rd party software which intercepts the keypress and prevents the OS from dispatching it to the active window
* (only once it happened) there was a defective keyboard (bad hardware).

Thanks again for the trace, but there is no possible code change we can do. If the OS doesn't dispatch the keypress to our window, then we cannot react to it.
