### ISSUE TITLE
never scroll terminal window more than terminal height minus a few lines (per wheel click)

### ISSUE THREAD

**Issue by mark-hahn** [microsoft/vscode#138891]
I often set my terminal height to 4 or 5 lines.  When I do this one click of my scroll wheel shoots over and I miss lines.  This means I can't use the wheel.  So my request is to never scroll the terminal window more than terminal height minus a few lines on each click.  I've never seen this behavior before but that doesn't mean it should be rejected out-of-hand.

This request should actually apply to all scroll windows which is most of the UI.  This would be nice to enforce in the web browser and everywhere else on the web, but that request would be kind of out-of-scope for this forum.  :-)

**Comment by yume-chan** [comment]
Agree. I always have `"terminal.integrated.mouseWheelScrollSensitivity": 0.5` or the terminal is unusable.

**Comment by Tyriar** [comment]
The current workaround for this is to set `terminal.integrated.mouseWheelScrollSensitivity` as @yume-chan said.

The reason it's like this is because scroll events are a mess to deal with, they don't respect platform defaults and all browsers handle them differently, it's even very difficult to tell what is a trackpad and what is a physical mouse event. VS Code uses monaco for the editor which contains some logic that tries to align closer to what the OS wants for default (which a lot of guessing) whereas xterm.js in the terminal respects more what the browsers gives it which can lead to more sensitivity. We're not planning on making any changes here currently.
