### ISSUE TITLE
Expose OS locale

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#138975]
Currently, `vs/base/common/platform` has both the exported variables `language` and `locale`.

It would be really useful for the unicode highlight feature to have an exported variable `osLocale` that reflects the locale of the operating system (or alternatively a different mechanism).

Many people use the english language pack in VS Code but have a russian windows locale, thus relying on `locale` is not sufficient (see #138767).

What do you suggest?

**Comment by dbaeumer** [comment]
I think we should simply use app.getLocale() like here: https://github.com/microsoft/vscode/blob/db217ba0de90692f82d823dd41353ac0a24fc4e6/src/main.js#L567

Storing it into the NLS configuration will slow down startup since we can only call app.getLocale() after the app ready event as been fired. And in many cases we don't need to wait so long.

@hediet would that work for you?

**Comment by hediet** [comment]
I will try that out, thank you!

**Comment by hediet** [comment]
Unfortunately ,I cannot import "electron" where I would like to use the current OS locale.

However, `new Intl.NumberFormat().resolvedOptions().locale` does the trick and seems to work on Windows (it reports `ru` if the windows language is set to russian).

**Comment by dbaeumer** [comment]
Cool, didn't know that code path!
