### ISSUE TITLE
Markdown KaTeX Highlighting: Percent symbol (%) not escaped

### ISSUE THREAD

**Issue by AryanBeezadhur** [microsoft/vscode#138921]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.63.0
- OS Version: Windows 11

---

Steps to Reproduce:

Create new markdown file and write the following markdown:

```md
$$ \leftarrow \text{percent sign} $$
$$ \% \leftarrow \text{percent sign} $$
```

Notice how the second line with the percent (`%`) symbol is not syntax highlighted after this symbol. This is because the percent symbol in KaTeX creates a comment, but I have escaped the symbol with a backslash (`\`).

If you open markdown preview, the second line renders, so VS Code's markdown KaTeX renderer sees that I have escaped the symbol, but the highlighter does not.

**Comment by PSNAppz** [comment]
@mjbvz I would like to work on this issue. Could you assign it to me?

**Comment by KhaledSamir** [comment]
Thanks for reporting this bug! Since this is my first bug to work on, I wanna clarify couple of things:

1- It seems VS is using markdown-it library to render the markdown file, is that correct?

2- If #1 is correct, am assuming that here are the folders that handle that:

![image](https://user-images.githubusercontent.com/4302544/146356054-d6c87730-e297-4ca6-a03f-3c91b99fba55.png)

These folder under extensions. Please confirm.

**Comment by KhaledSamir** [comment]
I'm working on it!

**Comment by AryanBeezadhur** [comment]
@KhaledSamir the `%` character is the comment character in KaTeX and LaTeX (VS Code uses KaTeX).

So anything after the `%` should *not* appear in the markdown preview, and VS Code should highlight it grey in the markdown file. This works.

But if I escape the `%` character with a `\`, the `%` character and anything that comes after it *should* now appear in the markdown preview. This works. But the text after the escaped `%` symbol should no longer be grey and should be coloured as usual, but the bug is that it is still grey.

![image](https://user-images.githubusercontent.com/34424160/146370361-9ad30a4a-09ff-4204-8a9b-c101f3cca307.png)

**Comment by KhaledSamir** [comment]
@AryanBeezadhur Got it! I'll look into it and get back to you.

**Comment by mjbvz** [comment]
Here's the relevant text mate grammar that handles highlighting: https://github.com/microsoft/vscode/blob/41df0673f81f5e70d17dd1b07116e56ea3eed25f/extensions/markdown-math/syntaxes/md-math.tmLanguage.json#L16

Also make sure to add a test in the text colorization tests: https://github.com/microsoft/vscode/blob/b614fb5db84b3ac07fc3e8b12c69c1dd581924ce/extensions/vscode-colorize-tests/test/colorize-fixtures/md-math.md#L0-L1

**Comment by Nopec** [comment]
Hello,

I made a research and modified this line (locally my HEAD is 6ecf45d4876ef14dbdd4a2a98fd28fbb0ce97fd9):
https://github.com/microsoft/vscode/blob/c635a395496a0699e6c6748d37b974fb4fba18cc/extensions/markdown-math/syntaxes/md-math.tmLanguage.json#L17
To this: `"match": "((?<!\\\\)%)(.+)$", `

Now I have the desired behavior. Unfortunately, I don't know yet how to extend and run the colorization tests but wanted to share it with you anyways.

**Explanation of the regex modification:**
`(?<!...)` is just a negative lookbehind (more information)
`\\\\` Four backslashes are needed because escaping in regex and the typescript string contains also two backslashes for escaping purposes.
`((?<!\\\\)%)` the surrounding brackets may be omitted but to keep the current regex grouping I kept it.
Refer this online regex example regarding the problem: ​https://regex101.com/r/N09KZx/

**Same procedure is used here:**
https://github.com/microsoft/vscode/blob/c635a395496a0699e6c6748d37b974fb4fba18cc/extensions/markdown-math/syntaxes/md-math.tmLanguage.json#L81

@KhaledSamir Hopefully that is a good starting point for you.

**Comment by KhaledSamir** [comment]
@Nopec Thank you very much Andre for sharing! This is very helpful! 

I will share my findings tomorrow with you.

**Comment by Nopec** [comment]
@KhaledSamir My plan was not to hijack your issue. I just wanted to check how far I will get. Feel free to get inspired by my commit.

**Comment by KhaledSamir** [comment]
@Nopec Thank you very much, bro for the insights! Absolutely I needed your help, I'm still familiarizing myself with the codebase since i't my first time :) 

@mjbvz @AryanBeezadhur  Please review the PR and let me know if there are any comments :)

**Comment by JODIN1727** [comment]
should be getting fixed
