### ISSUE TITLE
Toggle maximize panel should go to its previous state when the editor is focused

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#13906]
- VSCode Version: Code - Insiders 1.7.0-insider (c613e1bddce6a544fdf7fcfe2fc0a59626d8195d, 2016-10-17T06:06:36.370Z)
- OS Version: Linux x64 4.4.0-43-generic, Ubuntu 16.04
- Extensions: EditorConfig.EditorConfig-0.3.3, Tyriar.lorem-ipsum-1.0.0, Tyriar.sort-lines-1.1.0, Tyriar.terminal-tabs-0.0.6, Tyriar.theme-glacier-0.0.10, be5invis.vscode-icontheme-nomo-dark-1.1.4, cssho.vscode-svgviewer-1.2.0, dbaeumer.vscode-eslint-1.0.8, felipecaputo.git-project-manager-0.1.15, gerane.Theme-Wombat-0.0.2, ms-vscode.csharp-1.4.1, ms-vscode.typescript-javascript-grammar-0.0.4, rebornix.nova-0.0.5, robinbentley.sass-indented-1.1.0, ryu1kn.annotator-0.10.1

I don't think anyone would expect otherwise since a 20% height editor is unusable. If necessary to implement this it may make sense to have the command focus the panel when maximized?

Steps to Reproduce:
1. Show terminal panel
2. Toggle maximize panel
3. Click editor, the panel remains maximized

Related: https://github.com/Microsoft/vscode/issues/13898

**Comment by carlsmith** [comment]
Can this be reopened please?

There should be some way to maximize the terminal, then switch between the editor panes and the maximized terminal, without the terminal shrinking because it lost focus. As has been mentioned already, there's no benefit to having a one inch gap above the terminal, and the user can easily drag the divider there if they really want a little gap there.

Thanks.

**Comment by isidorn** [comment]
@carlsmith  Please first try vscode insiders since we have a new layouting logic.
If this still repros please file a new issue. Thanks
