### ISSUE TITLE
Command palette no longer detects match in middle of multiple words

### ISSUE THREAD

**Issue by ssigwart** [microsoft/vscode#139037]
Does this issue occur when all extensions are disabled?: No, since the command is from an extension.

- VS Code Version: 1.63.0
- OS Version: MacOS 10.15.7

Steps to Reproduce:

1.  Add an extension with command `Convert PHPDoc @var to @param`.
2. Try to run a command with `var par`.

This used to find the command.  Now it doesn't and I need to use `@var @par`.

**Comment by ssigwart** [comment]
I think this is from 45e8ea48867d67d50b6419c91d91c2d50a3a92f9.

**Comment by TylerLeonhardt** [comment]
Unfortunately, I need to mark this as by-design.

It worked before entirely on accident. The `@` was being treated as a space character, but it's not. It's part of the word `@var` so it should be included in the search.

There are some other issues open around improving general fuzzy search of commands and filenames that could improve this case, but I would make a change specifically for this since we chose a specific direction. I appreciate you bringing this up. It's very good for us to have this context.

**Comment by ssigwart** [comment]
Thanks for the response, @TylerLeonhardt.

**Comment by ssigwart** [comment]
When adding a command, is there any way to set an alternative title or a list of keywords that will also bring up the command?

**Comment by TylerLeonhardt** [comment]
Not at this time. See this:
https://github.com/microsoft/vscode/issues/50836

If you're the extension author you could contribute a new command that does the same thing.

**Comment by ssigwart** [comment]
Thank you.

It's a personal extension, so it's not a problem for me to rename the commands.  I just liked seeing the @ symbol in the command, but that's not a big deal.  I may see if I can tackle #50836 at some point.

**Comment by ssigwart** [comment]
I got something working for #50836 in #139670.  If it gets merged, it would be useful here too.
