### ISSUE TITLE
Show results from completion providers incrementally

### ISSUE THREAD

**Issue by Eskibear** [microsoft/vscode#139047]
In v1.63, the incremental rendering of multiple hover providers is great! Similar to #137714 , can we have the same experience for completion providers? 

That would benefit multiple use cases, e.g.:
- multiple completion providers registered by different extensions, they won't block each other.
- more room to optimize completion smartness/performance, i.e., provide simple and fast suggestions first, and append slow but smart suggestions later.
- ...

**Comment by testforstephen** [comment]
This can benefit Java extension a lot.

In Java extension, we let the client side register a completion provider for code snippet and the language server side registers the completion capability for normal completion. Since the server side must resolve projects and dependencies, it takes longer to make the completion feature available. Based on VS Code's current behavior, it will wait for all completion providers to return results before displaying suggestions, while the slower provider on the server side will block the entire completion experience. If incremental rendering is supported, we can provide client-side snippets in advance before the server is ready.

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3A"suggest"

**Comment by jrieken** [comment]
https://github.com/microsoft/vscode/issues/107343
