### ISSUE TITLE
New update causes textmate scope + semantic token issues

### ISSUE THREAD

**Issue by TamirCode** [microsoft/vscode#139220]
Does this issue occur when all extensions are disabled?: Yes/No
yes

VS Code Version: 1.63.1 (user setup)
Commit: fe719cd3e5825bf14e14182fddeb88ee8daf044f
Date: 2021-12-14T02:13:54.292Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS Version: Windows_NT x64 10.0.19042

Steps to Reproduce:

after updating vscode, my params/args inside functions are no longer the color of the argument itself because the textmate scope for them was removed perhaps? in the screenshot you can see the arguments in the function are colored properly (in magenta) since they have textmate scope of variable.parameter.js, but inside the function they are no longer considered params like in last version
![image](https://user-images.githubusercontent.com/66864667/146226687-f5e75beb-8282-4fba-9ce0-b61dbde6847a.png)

**Comment by TamirCode** [comment]
Also the the semantic token section (turned on if "semanticHighlighting": true,) no longer shows for me in the inspect tool, and consequently its set colors no longer work either

**Comment by tuhin3220** [comment]
139220 Sent from Mail for Windows From: TamirCodeSent: Wednesday, December 15, 2021 10:48 PMTo: microsoft/vscodeCc: SubscribedSubject: Re: [microsoft/vscode] New VSCode doesnt recognize textmate scope for params/args inside the function (Issue #139220) Also the the semantic token section (turned on if "semanticHighlighting": true,) no longer shows for me in the inspect tool, and consequently its set colors no longer work either—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by TamirCode** [comment]
![image](https://user-images.githubusercontent.com/66864667/146235071-38af0ddf-b159-424c-af62-03a58891fffe.png)
even worse, here it colors a normal variable as a parameter

**Comment by TamirCode** [comment]
after restarting vscode it seems to have fixed all the above issues however it still has bugs for example the `else` keyword is sometimes not giving the proper scope. but ill give it a few more days of playing around to see if i still have issues
![image](https://user-images.githubusercontent.com/66864667/146242424-461ff21a-8bca-48ac-8bc2-1d57d526ed88.png)
