### ISSUE TITLE
Format Code should be Format Document and Format Selection

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#13939]
Today the Format Code action is either or. When there is a selection *and* a selection formatter we use that, when there is no selection we format the document. We should be more explicit about this.

**Comment by basarat** [comment]
Is there a simple way I can get the old format auto action into monaco? 

This https://github.com/Microsoft/vscode/blob/8d042191dbe3fee47d0af7fbac6cd937723d3835/src/vs/editor/contrib/format/common/formatActions.ts#L227-L239 seems tied to vscode and not monaco (i.e. not registered as an `editorAction`). 

/cc @alexandrudima :rose:

**Comment by alexandrudima** [comment]
@basarat how do you mean?

I don't think it is possible to get it as an action showing up in the context menu and bound to `ctrl+alt+f` unless you use `editor.addAction` and add an action on your side with the old title, the old keybinding, etc.

**Comment by basarat** [comment]
It doesn't show up in `editor.getActions` which is what I use in alm : https://github.com/alm-tools/alm/blob/7354b7caeb562f5d4c9c6756dd4af035aa5b3bf2/src/app/commands/monacoActionLoader.ts#L69

**Comment by alexandrudima** [comment]
Yeah, it is now "demoted" to a command living in the commands registry. The unofficial hierarchy:
* command
* editor command (command that runs on an editor)
* editor action (command that runs on an editor and has a human readable title)

I guess it was left behind, as the comment suggests to catch leftover keybindings in vscode (i.e. the migration story since those are defined in `keybindings.json` by the end user). If you want the old functionality back, you can use `editor.addAction` to implement a format editor action on your side.

**Comment by basarat** [comment]
> implement a format editor action on your side that uses the selection or the document.

Cheers 🍻. Is it okay if I trigger another action from an action essentially https://github.com/Microsoft/vscode/blob/8d042191dbe3fee47d0af7fbac6cd937723d3835/src/vs/editor/contrib/format/common/formatActions.ts#L233-L237 block but calling other actions instead of the functions local to that file :rose:
