### ISSUE TITLE
"Control+." shortcut doesn't work

### ISSUE THREAD

**Issue by JalinWang** [microsoft/vscode#139354]
Does this issue occur when all extensions are disabled?: Yes

- VS Code & OS  Version:

![image](https://user-images.githubusercontent.com/20621784/146505062-5c2e84c8-6e10-4f6a-91a2-d5afd39d0992.png)

`Control+.` keystroke seems to be ignored on my VSCode. (But `ctrl` with the period on the Numpad works, i.e., `Ctrl +NumPad Decimal`)
I never modify the key mappings.

Here is the output for `Toggle Keyboard Shortcuts Troubleshooting`:
![image](https://user-images.githubusercontent.com/20621784/146505488-cb65b71d-23ae-4b58-bd11-397df43b7871.png)

Any suggestion on how to debug further?

Updated: This keystroke can be detected in PowerToy. Does it prove this problem has nothing to do with the global hotkey?
![image](https://user-images.githubusercontent.com/20621784/146507370-dbf1629d-78a6-4630-b8c7-2eacdb5972e0.png)

**Comment by alexdima** [comment]
@JalinWang Thank you for your detailed issue. This looks like the keypress `ctrl+.` does not reach our window. If the keypress `ctrl+.` is not dispatched by the OS to our window, there is nothing we can do on our side. I have seen very many similar issues in the past and they have always been caused by one of the following:
* there is an OS level setting or specific OS usage (like a keyboard input method) that ends up consuming the keypress
* there is another software installed on the machine which ends up consuming the keypress
* (only happened once) there was a bad keyboard (hardware problem).

**Comment by drmirk** [comment]
For people who came here from Linux; "ibus" sets emoji annotation keyboard shortcut to "Ctrl + Period". From ibus preference change it to something else to fix this problem.
