### ISSUE TITLE
Terminal editors don't get their icon set sometimes

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#139329]
Using ctrl+shift+`

![recording (6)](https://user-images.githubusercontent.com/2193314/146448127-a0c8db46-87ae-4c57-85bd-c8d1ac88bc23.gif)

Also, I notice the other editor bug here, when the icon shows above it seems like that's because it's duplicating the terminal created afterwards

**Comment by meganrogge** [comment]
| Creation method  | Result  |
| ------------- | ------------- |
| Created in panel and dragged to editor  | 👍🏼   |
| Create new terminal command with default location of 'editor'  | 👎🏼 shows default icon  |
| Create new terminal with profile command with default location of 'editor'  | 👎🏼 shows no icon then correct one when you click off of that tab  |

**Comment by Tyriar** [comment]
> Create new terminal command with default location of 'editor'

FWIW mine picks up the pwsh icon for this case

**Comment by meganrogge** [comment]
that's because the active editor doesn't change when it's dragged and dropped

https://github.com/microsoft/vscode/blob/aa33d06f0ddf002f7843cf8b21ac1a46c678b17d/src/vs/workbench/contrib/terminal/browser/terminalService.ts#L1107-L1111

we probably need to updateStyles on `this._editorService.onDidEditorsChange` too - assuming that gets fired when one is dragged and dropped
