### ISSUE TITLE
Show keybinding IntelliSense

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode#13946]
I am working on keymap extensions. One of the thing that I am missing is IntelliSense for the key attribute and its derivatives (in the context of creating an extension those derivatives are `"mac"`, `"linux"`, and `"win"`. 

In the image below I would like to see all the possible completions for `"win"`. This is important when I try to find how to indicate the context menu key on Windows. 

![image](https://cloud.githubusercontent.com/assets/2449568/19486611/f2837f74-9513-11e6-85c5-fecea742fcb1.png)

Additionally, this sort of IntelliSense is not found in the `keybindings.json` file. 

![image](https://cloud.githubusercontent.com/assets/2449568/19486642/12057794-9514-11e6-94f8-09603f059ef1.png)

Note - I am seeing only symbol completion scoped by the file I am in in both of the images below.

**Comment by jrieken** [comment]
This is not me. Maybe @alexandrudima but shouldn't this be covered by a schema?

**Comment by jrieken** [comment]
@aeschli Stop assigning this to me without answering my question

**Comment by alexandrudima** [comment]
Maybe we can do it with a schema, but should we then register a "oneOf" that contains all possible combos of `ctrl+`, `alt+`, `shift+`, `win+` and all accepted key codes?

**Comment by aeschli** [comment]
@jrieken Where is your question?

**Comment by alexandrudima** [comment]
@aeschli So I should do it with a schema? Ship with 1600 more strings in the core?

**Comment by aeschli** [comment]
@alexandrudima No of course not. IMO, this should go in the configuration-editing extension where @jrieken already added some completion smartness for keybindings.

**Comment by aeschli** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.
If you disagree and feel that this issue is crucial: We're happy to listen and to reconsider.
Maybe you want to give it a try yourself and provide the feature through an extension or a PR: We're happy to give advise and get you started.
Thanks for your understanding. Thanks for helping and happy coding!
