### ISSUE TITLE
Ini-file highlight bug

### ISSUE THREAD

**Issue by 22c-proxima** [microsoft/vscode#139531]
### VS Code version

Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)

### Extension version

2021.12.1559732655

### OS type

Windows

### OS version

Windows_NT x64 10.0.19042

### Python distribution

python.org

### Python version

python 3.9.12

### Language server

Pylance

### Expected behaviour

comment symbols # or ; marks comment only when it's in the beginning of the line (possibly indented) as default read behavior of config parser:
https://docs.python.org/3/library/configparser.html#supported-ini-file-structure
![image](https://user-images.githubusercontent.com/1910683/146636971-76e3c4d6-939b-478a-965b-c8b9603be403.png)

### Actual behaviour

![image](https://user-images.githubusercontent.com/1910683/146636851-a6d6ec71-1870-4242-8ddd-6f5b0c8344db.png)

### Steps to reproduce

create and open ini-file like on screenshot

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by alexr00** [comment]
We get our ini syntax highlighting grammar from https://github.com/textmate/ini.tmbundle. Upstream issue: https://github.com/textmate/ini.tmbundle/issues/2

**Comment by ALIENQuake** [comment]
> We get our ini syntax highlighting grammar from [textmate/ini.tmbundle](https://github.com/textmate/ini.tmbundle). Upstream issue: [textmate/ini.tmbundle#2](https://github.com/textmate/ini.tmbundle/issues/2)

@alexr00 

Hello,
since I'm also facing this issue constantly (also with `'` char) I've checked the linked repository and it seems that is completely abandoned - the last commit is from 9 years ago and none of the submitted PR's was merged. This indicates that the problem/bug might persist forever. 

If the ini syntax highlighting grammar was taken from this repo a long time ago then why it can't be fixed/updated by VSCode team? Can you re-open this issue and suggest a new approach how to fix it?

**Comment by alexr00** [comment]
Opened an issue for adopting a new ini grammar. More info here: https://github.com/microsoft/vscode/issues/141632#issuecomment-1023035195
