### ISSUE TITLE
Provide a way to add a timestamp to a comment

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#139524]
Example of where this could be used: https://github.com/microsoft/vscode-pull-request-github/issues/121

Some ideas for how this could look:

![image](https://user-images.githubusercontent.com/38270282/146794941-7ed4c079-de89-4441-8c6b-4691264890f6.png)

**Comment by alexr00** [comment]
FYI @laurentlb, I'm planning to start work on this soon.

**Comment by laurentlb** [comment]
To get a UX consistent with GitHub, I think we'll need two fields:
- one for display (e.g. `2 hours ago` or `on Aug, 1 2018`)
- one for hover (on GitHub, it's used for the full date with timezone). Other extensions could use it to show multiple timezones.

**Comment by hermannloose** [comment]
I just discussed another idea with @laurentlb:

- have a single timestamp field on `Comment` objects (most likely a `Date`)
- allow registering a formatter in `CommentController`, which when provided, is called with these timestamps and returns a `string` or optionally a more complex object, e.g. `{ label: string, tooltip?: string, ...}` or `{editorLabel: string, editorTooltip?: string, panelLabel: string, panelTooltip?: string}`
- provide reasonable default formatting if no formatter was registered

This seems the most flexible with regards to to tailoring an extension (e.g. "our company is in these three timezones, which should be available from the tooltip") as well as allowing a user to easily configure this (e.g. "I want this exact format string for long dates" or "I never want relative dates"), in the settings of an extension, or the settings of core VS Code itself (for the default formatting when no formatter was registered).

**Comment by alexr00** [comment]
Current proposal:

https://github.com/microsoft/vscode/blob/96189e4d14477af1df63b26bbaba74743c7a8afe/src/vscode-dts/vscode.proposed.commentTimestamp.d.ts#L6-L14

**Comment by alexr00** [comment]
Note from early discussions: We usually leave display decisions up to the users. Instead of having `useRelativeTime` be part of the API, we could have a setting. If extensions disagree they can always change the default value of the setting.

**Comment by alexr00** [comment]
For flexibility, we're now looking at using `detail` instead:

https://github.com/Microsoft/vscode/blob/7e586e7a7e67aa7862311a181ab43104a80240c0/src/vscode-dts/vscode.proposed.commentTimestamp.d.ts#L7-L9

To align with the timeline API proposal, should `Date` be `number`?

**Comment by alexr00** [comment]
After further discussing, we are keeping `Date`. The proposal is now in main:

https://github.com/microsoft/vscode/blob/b978d7150cae0f2fdd46d79f0c286cbd46158eae/src/vscode-dts/vscode.proposed.commentTimestamp.d.ts#L7-L14

Whether relative or precise time used for display is controlled by the setting `comments.useRelativeTime` (name will likely change). 

I have not tested other locales, but VS Code should handle displaying `Date`s correctly depending on locale. I will test this in the next couple days.

And finally, I didn't add anything to update the relative time yet. It will be updated every time the comment is rendered, so switching files will cause it to update. If this doesn't feel responsive enough then we can add some periodic updating. 

@laurentlb and @hermannloose please let me know what you think of this proposal.

**Comment by laurentlb** [comment]
That's great, thanks!
I like this proposal more than the previous one.

**Comment by alexr00** [comment]
API proposal is back in main today.

**Comment by alexr00** [comment]
An idea of what this could look like in the comments panel:

![image](https://user-images.githubusercontent.com/38270282/150157439-c5b8e3e6-f2c7-4098-8e0b-e7eebfe1b265.png)

Changes in that image include:
- File icons
- Timestamp
- Long comment text gets truncated.

**Comment by isidorn** [comment]
@alexr00 maybe allow a bit more characters before truncate.
It would be cool if each part would show different things on hover. So ideally hover on snippet would show the full comment.

**Comment by alexr00** [comment]
@isidorn that's exactly how it works :)

![Recording 2022-01-19 at 16 13 48](https://user-images.githubusercontent.com/38270282/150159307-3062f62d-9cc7-4357-94eb-edf469a097e0.gif)

I will make the length before truncate longer.

**Comment by albertelo** [comment]
Thanks for screenshot, and the progress on this issue!
I have a thought around the layout: the examples in the screenshot are a short, but what happens when the comments are longer? Would it make sense to keep the username and timestamp one row and the comment beneath it? I know this adds to vertical density, but you gain horizontal screen real estate for the comment and thus you can view more context before having to click on it. Having a full line for the username and timestamp also allows you to display the date and time without shortening the length of the comment.

**Comment by isidorn** [comment]
@albertelo @alexr00 and me discussed this, and we thought that showing a comment "snippet" would be the best to make this view function as a good "bird's eye perspective" of what is going on. Problem with making it multi line is that it adds visual complexity - especially if there is a parent child comment relationship.
I definitely think we can iterate here, and would be willing to hear feedback from users on your side.

**Comment by albertelo** [comment]
At a high level what we found from our users was some trouble distinguishing the information that is shown. Username, time stamp and comment look similar and discerning that info might be hard. Adding a single node for the comment could help, and it would be done without having to add additional visual elements (e.g. username profile image or icons). That said, I recognize that if you have many nodes then the information density increases and so does the visual complexity. 
Keeping in mind the "bird's eye perspective" idea, and going back to the first screenshot. What do you think on rather using only the time stamp and line code information to provide a "bird's eye perspective"? This reduces the visual complexity and provides context. Reading the comments would happen within the code, which is where it's likely going to happen even if we use short previews in the nodes.

**Comment by isidorn** [comment]
@albertelo thanks for feedback. I agree that your proposed design in the first screen shot reduces visual complexity since it does not show comment snippets. However then the items would look too similar and it would be hard for the user to discern which item in the comments view to click on - especially in the case when all the comments are from the same team mate. This seems to align with what you heard from your users.

Can you maybe provide a sketch for how the single node comment idea would look? How would that work if there are replies which are already children?

**Comment by alexr00** [comment]
The proposal keeps getting smaller:

https://github.com/microsoft/vscode/blob/8b27820fb29ec3d96923afca3cbe09a151f4bf93/src/vscode-dts/vscode.proposed.commentTimestamp.d.ts#L7-L13

Moved away from detail and now we're all in on calling it a timestamp that can only be a date. `detail` originally was intended to provide more freedom, but in reality this should only ever be a timestamp.

**Comment by laurentlb** [comment]
Thanks, the API proposal looks good!

> we thought that showing a comment "snippet" would be the best to make this view function as a good "bird's eye perspective" of what is going on. Problem with making it multi line is that it adds visual complexity - especially if there is a parent child comment relationship.

I also like the comment snippet, it lets me find discussions quickly. Have you considered showing only the last comment of each thread? I think hiding the intermediate comments removes the visual complexity, and that would let us use two lines per thread (instead of one line per reply).

Quick mock to show the idea (3 distinct threads are visible):
![image](https://user-images.githubusercontent.com/485572/150587757-36269f0a-25b8-437b-bfe9-4ebcf9b43668.png)

The icon shows the status of each thread (e.g. resolved / unresolved). If needed, intermediate replies could be as child notes (but collapsed by default).

**Comment by isidorn** [comment]
@laurentlb Thanks for the sketch. I personally like the idea of showing the snippet of the latest comment in the thread. Maybe we should have some simple `...` affordance so user understands that there is more context before it.
As for showing the comment on multiple lines. I am not sure if this will work because the panel has more horizontal than vertical space. And I think we should be careful with introducing multi line elements.

However I think it is work trying out both approaches and @alexr00 and me will consider these ideas and once we try them out we will know more. Thanks!

**Comment by isidorn** [comment]
@laurentlb @albertelo please try it out with VS Code insiders from tomorrow and let us know what you think. We are looking forward to the feedback. Thanks!

**Comment by isidorn** [comment]
Great - thanks for letting us know. Adding verified label.
