### ISSUE TITLE
连接扩展商店出现XHR failed

### ISSUE THREAD

**Issue by zjdns** [microsoft/vscode#139618]
XHR failed 这个问题没有办法解决, 能不能提示的时候准确的找到问题所在

**Comment by zjdns** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "microsoft/vscode"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月22日(星期三) 下午2:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [microsoft/vscode] 连接扩展商店出现XHR failed (Issue #139618)





 
感谢您创建此问题！
 
然而，由于您没有使用英语，我们很难进行处理。如果可能，请您将此问题描述修改为英文。请您直接编辑此问题，不要提交回复或新问题。
 
请注意，机器翻译服务通常无法处理用于讨论软件问题所需的技术性语言，所以我们推荐您寻找一位熟悉相关技术的人来协助翻译。
 
如果您无法做到，没有关系。此问题已经被标记为需要翻译，等待社区成员志愿进行翻译。
 
 
Thanks for creating this issue!
 
Unfortunately, as the description is not in English, it's hard for us to work on. If possible, please edit the original issue to be in English.
 
In our experience, automatic translation services are not able to handle the technical language needed to effectively communicate about software issues, so we recommend finding a human translator who is familiar with our technology to help.
 
Otherwise, we have marked this as needing translation and a community member may be able to help out.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Lemmingh** [comment]
@zjdns

"XHR failed" here means "network failure", which is usually caused by poor connectivity, wrong proxy, and unexpected routing, and is even related to Chromium and OS. However, no one can know the real reason unless debugging the network stack on your machine, though the DevTools might reveal some details of the failure.

Please see if similar issues can help you:
<https://github.com/microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+XHR+failed>

BTW, please leave your comment directly on `GitHub.com`, avoiding "email reply" which only supports plain text with broken formatting.

---

"XHR failed" 就是“网络异常”。一般来说，连通性不佳、错误的代理配置、异常的路由都可以导致它。有时候，问题甚至发生在 Chromium 或者操作系统内部。除非调试你的机器，没有办法知道原因。DevTools 偶尔能报告部分有用的信息。

类似 issue 中的讨论或许会对你有帮助：
<https://github.com/microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+XHR+failed>

另外，请尽量在 GitHub 网页上回复，不要使用 "email reply"。因为 "email reply" 仅支持纯文本，而且排版非常糟糕。

**Comment by deepak1556** [comment]
Can you check if the issue still persists with latest insiders https://code.visualstudio.com/insiders ?
