### ISSUE TITLE
vscode not loading correct env

### ISSUE THREAD

**Issue by scorpion35** [microsoft/vscode#139639]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: `1.63.2` / Commit: `899d46d82c4c95423fb7e10e68eba52050e30ba3`
- OS Version: `OS: Darwin arm64 21.2.0`

Steps to Reproduce:

1. Debug an extension (I used [`rubocop`](https://github.com/misogi/vscode-ruby-rubocop)) and place a breakpoint anywhere and break there.
2. In the debug console, look at `process.env` and observe the `PATH` variable is different than what's configured in `~/.zshrc` (or whichever terminal settings files you use)

I was debugging an extension (`rubocop`) for errors it was throwing and found out vscode is not loading the `env` properly. Please see this thread for more details - https://github.com/misogi/vscode-ruby-rubocop/issues/148#issuecomment-999648216

**Comment by denik1981** [comment]
Well, I have the same problem but with the automated terminal, the one used to launch your Custom Tasks and the one that use some of the extensions. 

My entire bashrc isn't read. I think this might be a vscode code problem with linux users. One of my extensions use the automated terminal and make call to yarn (js package manager) which makes the terminal exists becaue of command not found. The problem is that the PATH env isn't being built properly to make this command run well. If I provided the PATH within the `terminal.integrated.automationProfile.linux` setting I can see that it runs well but this is highly inconvenient cause I would have to update this setting everytime my PATH changes.

**Comment by coffenbacher** [comment]
I also have this problem when running automated terminal. I've tried every combination of profiles, shell etc, I can think of and I can't get the automated terminal to read my zshrc file. My main effort is focused on this, and it doesn't work:
```
    "zsh": {
      "path": "zsh",
      "args": ["--login"]
    },
```

```Version: 1.63.2 (Universal)
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:37:28.172Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin arm64 21.2.0
```

**Comment by weinand** [comment]
@scorpion35 Does it make a difference if you launch VS Code from a terminal instead of running it from the Finder or Dock?
