### ISSUE TITLE
Binary file not displayed message should suggest the hex editor

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#139600]
![image](https://user-images.githubusercontent.com/2230985/146997499-79ee6c49-5bb3-4252-a79c-7acfb379e872.png)

This could say, "Do you want to `open it anyway` or `open it in a hex editor`?"

**Comment by bpasero** [comment]
> open it in a hex editor

And what would that do specifically? I do not think we can really hard code to use our Hex editor here because there are other editors. 

@lramos15 help me, didn't we tweak this experience once to ask the user to reopen with? Did we maybe loose this capability?

**Comment by lramos15** [comment]
Yeah we don't want to favor a specific editor here because 
1. We want to be fair to all custom binary editors
2. The hex editor isn't always the choice the user wants. For example I rarely want the hex editor for images and much prefer the image preview or Lunda paint

The current experience gives you an editor to open it with if you have one installed

![recording](https://user-images.githubusercontent.com/4544166/147107557-b06c446a-ccd3-4fd7-9f4f-756e0e9e2852.gif)

**Comment by bpasero** [comment]
Ah yeah true, I had forgotten that we open a picker when you click it 👍
