### ISSUE TITLE
Markdown preview: links to unicode headings are broken

### ISSUE THREAD

**Issue by dlyz** [microsoft/vscode#139718]
Issue Type: <b>Bug</b>

Example markdown:

```md
# Page

[heading](#heading)

[заголовок](#заголовок)

[επίκεφαλής](#επίκεφαλής)

## Heading

## Заголовок

## Επίκεφαλής

```

Click to the link navigates to the proper heading in the editor in all 3 cases.
But in the rendered preview window only `#heading` works.

Reproduces since 1.62.0, was OK in 1.61.2.

VS Code version: Code - Insiders 1.64.0-insider (7b9e5c32a053669d4e72f998e4fa217090c32f59, 2021-12-22T05:15:28.225Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30258533
vsc_aa:30263845
pythonvspyt551:30291412
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
vscop804cf:30404767
vs360cf:30404996
vsclayoutctrt:30405800
py55gd98cf:30408622
vscexrecpromp3t1:30407758
azactmsal:30409287

```

</details>

**Comment by Lemmingh** [comment]
## Direct cause

```markdown
## Заголовок
```

gets `id="%D0%B7%D0%B0%D0%B3%D0%BE%D0%BB%D0%BE%D0%B2%D0%BE%D0%BA"`. (<https://github.com/microsoft/vscode/blob/a06afb22ce06dbd4f01d3bb5bf946e08bff55180/extensions/markdown-language-features/src/slugify.ts>)

```markdown
[заголовок](#заголовок)
```

gets `href="#%D0%B7%D0%B0%D0%B3%D0%BE%D0%BB%D0%BE%D0%B2%D0%BE%D0%BA"`. (<https://github.com/markdown-it/markdown-it/blob/6e2de08a0b03d3d0dcc524b89710ce05f83a0283/lib/index.js#L47>)

Here, only

```javascript
getElementById("%D0%B7%D0%B0%D0%B3%D0%BE%D0%BB%D0%BE%D0%B2%D0%BE%D0%BA")
```

can find the `<h2>` element successfully.

However, the webview

<https://github.com/microsoft/vscode/blob/a06afb22ce06dbd4f01d3bb5bf946e08bff55180/src/vs/workbench/contrib/webview/browser/pre/main.js#L437>

and fails.

## Behind the scene

[HTML Standard](https://html.spec.whatwg.org/multipage/dom.html#the-id-attribute):

> When specified on HTML elements, the `id` attribute value must be unique amongst all the IDs in the element's tree and must contain at least one character. **The value must not contain any ASCII whitespace.**
>
> **Identifiers are opaque strings.** Particular meanings should not be derived from the value of the `id` attribute.

---

[DOM Standard](https://dom.spec.whatwg.org/#dom-nonelementparentnode-getelementbyid):

> The `getElementById(elementId)` method steps are to return the first element, in tree order, within this’s descendants, whose ID **is** `elementId`; otherwise, if there is no such element, `null`.

---

[HTML Standard](https://html.spec.whatwg.org/multipage/browsing-the-web.html#scroll-to-the-fragment-identifier)

> **The indicated part of the document** is the one that the `fragment`, if any, identifies.
>
> For HTML documents
>
> ...
>
> If **find a potential indicated element** with `fragment` returns non-null, then the return value is **the indicated part of the document**; return.
>
> ...
>
> If **find a potential indicated element** with `decodedFragment` returns non-null, then the return value is **the indicated part of the document**; return.
>
> ...
>
> To **find a potential indicated element** given a string `fragment`, run these steps:
>
> If there is an element in the document tree that has an ID **equal to** `fragment`, then return the first such element in tree order.
>
> ...

---

Thus,

The `getElementById()` method uses **ordinal comparison**.

---

Thus,

The example in #134286 by @ddu6 is indeed **invalid HTML**.

How an invalid `id` attribute is handled [depends on web browsers](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/id).

---

Thus,

The webview neither before nor after the commit d96ced4f2f3cd1e031cbf41105786853c930c183 reflected the standard correctly.

A possible solution is:

```javascript
const fragment = node.hash.slice(1);
const scrollTarget = event.view.document.getElementById(fragment) ?? event.view.document.getElementById(decodeURIComponent(fragment));
scrollTarget?.scrollIntoView();
```

Note that the code above omits `a[name]` elements, because I think it's not worth handling them.
