### ISSUE TITLE
Option to only have a single instance running

### ISSUE THREAD

**Issue by reidmaker** [Microsoft/vscode#13970]
- VSCode Version: 1.6.0
- OS Version: Windows 8.1

I really like VS Code, but the only thing preventing me from doing a full switch from Textpad as my multi-purpose and fast text editor is being able to have all file opens use the same VS Code window with tabs.  In Textpad, it’s not default, but it has:

![vscode_tpref](https://cloud.githubusercontent.com/assets/6612225/19499306/91c19e5a-954a-11e6-8257-68421bd52a4c.png)

When unselected, ensures that any file opened via double click or via the right click file menu:

![vscode_tcontext](https://cloud.githubusercontent.com/assets/6612225/19499328/b7376bec-954a-11e6-8d22-87fde733a948.png)

Opens in my same instance of Textpad.  I find it much easier to navigate the document selector or tabs than multiple instances of Textpad through windows:

![vscode_tdocs](https://cloud.githubusercontent.com/assets/6612225/19499340/d1d625a6-954a-11e6-9884-06d3d6815575.png)

Is just easier to see and switch back and forth than:

![vscode_twin](https://cloud.githubusercontent.com/assets/6612225/19499351/df031374-954a-11e6-8307-020d0bd37924.png) 

Thanks for an awesome editor!

**Comment by bpasero** [comment]
@reidmaker does this setting help you?

`"window.openFilesInNewWindow": false`

**Comment by bpasero** [comment]
We introduced new settings to control how files and folders open for our next release. You can then set:
* `"window.openFilesInNewWindow": "off"`
* `"window.openFilesInNewWindow": "off"`

To avoid multiple instances. Note that when opening multiple folders we still open multiple windows because currently we cannot show multiple folders in the same instance.
