### ISSUE TITLE
Images loaded using <img/> in iframe in Notebook cell output don't appear

### ISSUE THREAD

**Issue by andrewtacon** [microsoft/vscode#139741]
I am writing an extension for VSCode that require images to be able to be loaded into a separate iframe that is being rendered in the output cell out note.

The images don't show up.

When I do the same line of code as direct HTML output into a similiar cell, not in an iframe, images appear

Both cells use the normal HTML renderer  'text/html'

It could just be me not understanding how things are supposed to work.

![bug](https://user-images.githubusercontent.com/55533023/147379630-f1a65fe6-9b79-40fa-a885-fdeda176b25b.png)
.

**Comment by rebornix** [comment]
@mjbvz can you please help? I don't recall we did anything special to disable iframe.

**Comment by andrewtacon** [comment]
Hi thanks for looking into my issue.

I can (now) get an iframe to show an image only if I
(1) assign the contents of the iframe using the srcdoc attribute and
(2) if the image is hosted on the web
See attached images for examples.

The extension that I am using is called "Digital Solutions". This is not a huge issue, but the behaviour of being able to load a local image in the main document and then not being able to using the iframe is inconsistent.

![image1](https://user-images.githubusercontent.com/55533023/149442311-dda7e438-cf19-4b6b-b0fe-d63d02a9504f.png)
![image2](https://user-images.githubusercontent.com/55533023/149442325-5ce9784c-b750-458f-a1b5-0fd74019d742.png)

Many thanks

Andrew

**Comment by mjbvz** [comment]
We don't disable iframes but we also can't provide the same level of support inside of them. I feel that loading images from the workspace inside of an iframe is out of scope since iframes are their own little documents. 

However iframes definitely should be able to load images from `https` urls. The reason your second example using https doesn't work is because I'm pretty sure it's not valid html: you have to use `src` or `srcdoc` to set the content of an iframe
