### ISSUE TITLE
VSCode keeps logging out of sync account in macOS 12 Monterey

### ISSUE THREAD

**Issue by GorvGoyl** [microsoft/vscode#139766]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.63.2 
- OS Version: M1 MBP, MacOS 12.1 Monterey (Darwin arm64 21.2.0)

Steps to Reproduce:

I recently switched from Windows 10 to MacOS and trying to sync settings to my new macOS. However, after half an hour or so, I'm getting logged out, and VSCode is asking again to sign in.

1. Sign in to sync settings using Github.
2. Quit VSCode and wait for 15-20 mins.
3. Open VSCode and it would be in the logged-out state and asking to sign in again.

![image](https://user-images.githubusercontent.com/7106086/147405924-166d72b9-6e44-420b-8a1b-9c0d1f0c736e.png)

**Comment by jimcroft** [comment]
Possibly related to https://github.com/microsoft/vscode/issues/139563

**Comment by GorvGoyl** [comment]
fyi I'm not facing this issue on my Windows 10 machine.

**Comment by TylerLeonhardt** [comment]
Can you follow these steps so that we can get more information on what's going on?

* Open the Command Palette
* Run the `Developer: Set Log Level...` command
* Choose `Trace`
* _Wait for the issue to happen..._
* Open the Output pane (it's next to Terminal)
* drop in this issue he contents of the following:
  * `GotHub Authentication` Output channel
  * `Log (Settings Sync)` Output channel
  * `Log (Window)` Output channel

**Comment by GorvGoyl** [comment]
It seems the issue got fixed after the most recent patch update.
