### ISSUE TITLE
problem matcher that clears only for changed files

### ISSUE THREAD

**Issue by nevir** [microsoft/vscode#1397]
I have a watch task that runs various per-file checks (lint, appropriate tests, etc). When it starts up, it runs those checks for all files in the project.  Thereafter, it only runs checks on files that change.

For the most part, it works great; but the one limitation I'm running into is that _all_ problems for a particular matcher are cleared on a run.

For example:
1. I boot up the watch task, and there are problems on `foo.js` and `bar.js`.  The problem matcher picks up on all of these.
2. I make a change to `foo.js`:
   
   a. The watch task re-runs checks for just `foo.js`.
   b. The problem matcher notices that a re-run has occurred, and blows away all problems of that type
   c. Only problems for `foo.js` are listed, even though `bar.js` still has issues.

I'd like to avoid building a language server or plugin for this if I can (the watch task is very useful to non VS code users on the team; and problem matchers are wonderfully simple).

Or maybe we could have an option for only clearing problems for files that have changed (or that match a particular expression?)

**Comment by Ciantic** [comment]
I'm seeing this behavior:

When I have problem watcher in watching task, it clears all warnings when I change editor (not save it), so each time I edit file all warnings disappear, but as soon as I save (the watching task lists the warnings again) they re-appear.

This makes working with problem matcher view difficult, because the warnings / errors disappear all the time as I edit the file even though the output has not been re-run because I have not saved. 

In my opinion on watching task the warnings should cleared only when the console output changes. Right now it's easier me to look at the output console than to problem matcher view because it clears itself out all the time.

**Comment by dbaeumer** [comment]
@nevir how did you configure the task. Is if configured as a watching task then this should not happened (e.g does it have a "watching" property). If not the task framework always assume that all files are validated and all valid errors are rereported. Otherwise errors would never be cleared in cases where you have inter file dependencies.

@Ciantic I assume that your problem is different. If I look at your task configuration here #8304 then you use "typescript" as the problem owner. So as soon as you type in a TS file your errors will be overridden since the typescript language server uses "typescript" as an owner as well. Have you tried to give them a different owner.

**Comment by Ciantic** [comment]
If you have problem with problem matcher clearing itself out every time editor changes, remember to put a unique string in the "owner" property of all problem matchers, e.g. 

```
"problemMatcher": [
	{
		"owner": "SOMEUNIQUESTRING",
		// ...
	}
]
```

Forgetting this, can cause weird problems with multiple matchers.

**Comment by nevir** [comment]
> @nevir how did you configure the task. Is if configured as a watching task then this should not happened (e.g does it have a "watching" property). If not the task framework always assume that all files are validated and all valid errors are rereported. Otherwise errors would never be cleared in cases where you have inter file dependencies.

Yeah, I had `watch: true` enabled.  The difference here, I think, is that the task itself only ran for files that changed

**Comment by dbaeumer** [comment]
Keeping as a feature request to allow watching patterns on a per file bases.

**Comment by meganrogge** [comment]
🙁 In the last 60 days, this feature request has received less than 20 community upvotes and we closed it. Still a big Thank You to you for taking the time to create this issue! To learn more about how we handle feature requests, please see our [documentation](https://aka.ms/vscode-issue-lifecycle).

Happy Coding!
