### ISSUE TITLE
Toggle activity bar affects other opened vscode window

### ISSUE THREAD

**Issue by leira** [microsoft/vscode#139899]
This bug is actually the same as #134614. But #134614 is closed, so I can only start a new bug to discuss the issue. Currently the open/close state change of the Activity Bar applies to all the open vscode windows. This behavior is inconsistent, comparing to the Side Bar. The open/close state of Side Bar is to the current window only, while the Activity Bar is to all the open windows.

Why are they inconsistent? What is the criteria to determine weather a bar should be toggled within the current window or across all windows?

I think the Activity Bar behavior should be consistent with the Side Bar, that the open/close state should only apply to the current window.

Steps To Reproduce:
1. Open 2 vscode windows.
2. Make sure Activity Bars are shown in both vscode windows.
3. Within window 1, Uncheck Menu -> View -> Appearance -> Show Activity Bar, to hide the Activity Bar.

Actual:
* The Activity Bar in both vscode windows are hideen.

Expected:
* Only the Activity Bar in window 1 should be hidden.

**Comment by sbatten** [comment]
This has long been the behaviour of VS Code. While I can see the point that this feels inconsistent, the side bar and activity bar are very different in terms of functionality. One would much more frequently want to show and the side bar based on the current activity in the window, much like the panel. However, the activity bar is a more permanent fixture, that some people can live without by using keyboard shortcuts.

Since we have not received much feedback requesting this behaviour be changed, we have had no plans to change it. However, I will leave this one open for a bit to see what others think. Would you also agree that the status bar should only hide per window?
