### ISSUE TITLE
text editor bug

### ISSUE THREAD

**Issue by hDado** [microsoft/vscode#139898]
the text editor on any project may freeze / keyboards entry won't work after certain time, i have tried many time, can't figure out the issue, keyboard entry won't work, i don't know if it my mistake (new to macOS) or it just the python interpreter 

system : macbook m1 chip 2020

**Comment by rzhao271** [comment]
1. Does the problem occur with extensions disabled? Also, what version of VS Code are you on?
2. See https://github.com/microsoft/vscode/wiki/Native-Crash-Issues for how to collect a crash dump. If you can obtain one, then it'll be easier to figure out where the issue is coming from.
3. Attaching a screencap can help. You can record one at https://gifcap.dev.
