### ISSUE TITLE
Selecting text has become real annoying

### ISSUE THREAD

**Issue by DustinTracy** [microsoft/vscode#139818]
Ever since my last update selcting text has becoming annoying AF.    I try to highlight or double click to replace some text and instead of succeeding in that I get an uninformative popup

**Comment by brandon942** [comment]
I alleviated this via [Ctrl+Shift+P] -> ">settings" -> "Preferences: Open Settings (JSON)"
Then add `"editor.hover.sticky": false`.
This makes the popup invisible to mouse events. So you can no longer click on it.
It's not optimal. Sometimes you want to select and copy some names and types from the popup. So I suggest making the popup mouse-visible by, for example, holding [Alt] + clicking on it. But that will never happen ofc.

**Comment by DustinTracy** [comment]
Brandon,

Thank you for the reply.  I'll try that.

Best,
Dustin

**Comment by jespertheend** [comment]
It seems the value of the `editor.hover.delay` setting is now half of what you actually set it to

**Comment by jespertheend** [comment]
I did a bisect and this seems to have regressed in ade68869b89b9fee7ea20d22af6546fb2a4f7cc1
@alexdima do you know what's going on? I tried to debug the issue but I can't get breakpoints to work.

**Comment by alexdima** [comment]
Sorry about that. I acknowledge this. I also noticed the regression and fixed it while doing a refactoring in the area via https://github.com/microsoft/vscode/commit/275b0c05eee77438976fb48a346f4a43d5abb894 . The portion that fixes the problem is https://github.com/microsoft/vscode/blob/6851b106e0a5714fd68038f0c1930fb6b38e856e/src/vs/editor/contrib/hover/hoverOperation.ts#L154-L157

**Comment by alexdima** [comment]
To verify, you can use the very good steps from @gjsjohnmurray in https://github.com/microsoft/vscode/issues/140212

1. Set `editor.hover.delay` to 2000
2. Hover, and observe that the hover appears after 1 second rather than 2 :bug:
3. Set `editor.hover.delay` to 10000 which is the undocumented clamped maximum for this setting.
4. Hover, and observe that the hover appears after 5 seconds rather than 10  :bug:
