### ISSUE TITLE
Calling `reveal()` on the webview editor doesn't show it when the workbench panel is maximized

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#139919]
1. Open a webview from the webview sample https://github.com/microsoft/vscode-extension-samples/tree/main/webview-sample
2. Open a workbench panel (Output view, for instance)
3. Maximize the workbench panel `workbench.action.toggleMaximizedPanel`
4. Call reveal from the extension to show the webview

```ts
// If we already have a panel, show it.
if (CatCodingPanel.currentPanel) {
    CatCodingPanel.currentPanel._panel.reveal(column);
    return;
}
```

5. It's not revealed

It only fails if the webview is already open.

---

Version: 1.63.2 (user setup)
OS: Windows_NT x64 10.0.19043

**Comment by MachineMitch21** [comment]
@usernamehw I'm on the following setup:

Version: 1.71.2 (user setup)
OS: Windows_NT x64 10.0.19.044

And, I'm unable to reproduce this behavior.  When I maximize any workbench panel, then call the "webview-sample" extension's "catCoding.start" command, the webview reveals without issue.  Can you confirm if the issue is still occurring for you?

**Comment by usernamehw** [comment]
Yeah, it seems to be working now.
