### ISSUE TITLE
Redo bug

### ISSUE THREAD

**Issue by rapanui** [Microsoft/vscode#13994]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T16:21:53.542Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: dbaeumer.vscode-eslint-1.0.8, mkaufman.HTMLHint-0.0.3, mrmlnc.vscode-puglint-2.3.0, QassimFarid.ejs-language-support-0.0.1, silverlakesoftware.searchdocsets-vscode-0.5.2

Steps to Reproduce:
1. ctrl+z
2. ctrl+c
3. ctrl+y <-- dont work

**Comment by roblourens** [comment]
Does it happen every time? Does it repro if you launch with extensions disabled (`--disable-extensions` from command line)?

**Comment by alexandrudima** [comment]
I cannot reproduce. @rapanui Is there something more to it? (do you have an auto-formatting extension that would decide to modify the text between step 1 and step 3?)

**Comment by scorphus** [comment]
Referencing tht13/Python-vscode#18.

**Comment by alexandrudima** [comment]
@scorphus That is a good find. If it only reproduces in python files and only when that extension is activated, I can only guess the extension is submitting some text edits that causes the "future" part of undo-redo to be discarded (similar if you undo, type something, there is nothing to redo since the redo stack got discarded when you typed). I suggest to track this issue with the extension.
