### ISSUE TITLE
日本語変換の異常？

### ISSUE THREAD

**Issue by DrBobT** [microsoft/vscode#139956]
バージョン1.63.2にバージョンアップした後に日本語変換時に以下の異常が発生している。1.62.3に戻すと異常は発生しない。
使用環境：macOS 11.6, Mac mini(M1, 2020)

(異常？例)
「今日は大晦日。明日は正月。」の後に、「雪が降り続いています。」と入力し、変換をかけると、「今日は大晦日。明日は正月。晦日。明日は正月。雪が」と表示され、右カーソルを１回ずつ押すと変換候補が確認される。入力後の一括確認、確定ができないのが非常に不便。

**Comment by DrBobT** [comment]
I apologize very much for the lack of detailed English explanation.

The normal screen for Japanese conversion in the previous version (1.62.3) is as follows.
![Normal-Screen](https://user-images.githubusercontent.com/87902849/147811101-8eb2a94e-4ec2-480e-b75a-ebb80470d3ea.png)
The third input sentence will be displayed in its complete form.

The abnormal screen of the latest version (1.63.2) for Japanese conversion is as follows.
![Abnormal-Screen](https://user-images.githubusercontent.com/87902849/147811116-96048318-5a34-4f6d-9240-c4d862f12165.png)
The third input text will be displayed in an incomplete (overlapping) form.

If there is anything unclear, please check.
Thank you.

**Comment by CodeCrazy-ywt** [comment]
Maybe related to #138704

**Comment by NaokiTakahashiRad** [comment]
I have exactly the same issue. I think this is different from #138704. 
This happens when I try to insert a phrase in a sentence.
When I hit space (convert to Chinese character), the phrase I tried to convert is only partially shown, and there is overlapping and wrapping of the originally present characters. See .mov below for VSCode and MS Word.

MacBookPro Catalina, VSCode 1.63.2 with Google Japanese Input.

This is abnormal behavior on VSCode.
https://user-images.githubusercontent.com/77553912/148668328-fbb8fe00-945b-481e-a80d-de584f3b6538.mov

This is normal behavior on MS Word.
https://user-images.githubusercontent.com/77553912/148668333-389ea996-eb49-4b66-9e25-cd43faaee6f0.mov

**Comment by nakaba-yono** [comment]
I had the same issue on VSCode v1.63.2 and this doesn't appear when I use VSCode v1.62.3.
So I think this is specific to v1.63.
https://user-images.githubusercontent.com/2138807/148685655-9a662c68-3a99-48c1-ad98-c08cd2c9b041.mp4

And then, this occurs when there are multiple strings to be converted.
Following is a single string to be converted, this didn't occur.
https://user-images.githubusercontent.com/2138807/148685681-2e5666af-9559-4d4e-a20f-60f677676a78.mp4

**Comment by alexdima** [comment]
This has been addressed via https://github.com/microsoft/vscode/pull/139394 and the fix is available in our latest [insiders](https://code.visualstudio.com/insiders/).
