### ISSUE TITLE
синхронизация

### ISSUE THREAD

**Issue by Pavels123095** [microsoft/vscode#140049]
Issue Type: <b>Feature Request</b>

Error visual studio code this sync then github

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:39:46.686Z)
OS version: Linux x64 5.4.0-91-generic
Restricted Mode: No

**Comment by Pavels123095** [comment]
Error visual studio code this sync then github

**Comment by TylerLeonhardt** [comment]
Can you follow these steps so that we can get more information on what's going on?

* Open the Command Palette
* Run the `Developer: Set Log Level...` command
* Choose `Trace`
* _Wait for the issue to happen..._
* Open the Output pane (ctrl+shift+u I think on Windows)
* drop in this issue he contents of the following:
  * `GitHub Authentication` Output channel
  * `Log (Settings Sync)` Output channel
  * `Log (Window)` Output channel
