### ISSUE TITLE
Built-in web browser

### ISSUE THREAD

**Issue by v4vendeta** [microsoft/vscode#140037]
A built-in web browser in vscode may be a cool feature, you don't have to switch to your system browser to check StackOverflow, browse documentation, ...

**Comment by bmitc** [comment]
I found this issue while searching to see if this was possible. :)

My argument for this is due to the increasing presence of large monitors, in particular ultrawide monitors. Since VSCode is limited to only a single window, it means that if one wants a browser window to view a PDF, documentation, a web-based notebook implementation (such as Elixir Livebook), forums, etc., then the browser window must be all the way to the side rather wherever one might want it. If I could put the browser window closer to the middle and something like the terminal all the wide to the side, since I am only briefly there rather than reading a document like in the browser, that would be ideal.

However, it's two limitations of VSCode prevention this: (1) VSCode is limited to a single window, (2) VSCode doesn't have an embedded browser that could be a tab. Having one or the other might solve this.

**Comment by hello-smile6** [comment]
You could always create an extension which would show a webview, or even put a fullscreen `<iframe>` in a Markdown file and enable unsafe content execution for the file.
