### ISSUE TITLE
Notebook shows dirty indicator with autosave on

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#140069]
- Set auto save: afterDelay
- Edit a notebook
- See the dirty indicator briefly appear after editing

**Comment by roblourens** [comment]
I guess this is https://github.com/microsoft/vscode/issues/96400

**Comment by bpasero** [comment]
We never did that for custom editors because it requires code to ensure that an editor that is closed but pending to be saved via auto save is really waited upon on shutdown. To further explain:
* the behaviour is driven by `EditorInput#isSaving` method
* if you return `true` from that method no dirty indicator will show up
* this means a user can close an editor with dirty changes
* as such, components have to ensure that the save continues in the background and even on shutdown

Files implement this here:

https://github.com/microsoft/vscode/blob/4cd32948551642e6898057f4fc8a4590cf876f43/src/vs/workbench/contrib/files/browser/editors/fileEditorInput.ts#L279-L294

I think the reason we never adopted this for notebooks as that notebooks have a dual model: complex and simple. With simple (which is based on file working copies), we can probably implement this now similar to what files do, but it needs careful testing what happens when you close a notebook quickly enough before auto save finished.

**Comment by rebornix** [comment]
We could revisit this once we remove complex notebook model and friends  https://github.com/microsoft/vscode/issues/144810 but the saving of notebooks is more complex than files and I wonder if it's worth it to implement this. Also the dirty indicator is also an indicator that saving is not done yet, which is valuable as saving notebooks is not necessarily instant. what do you think @roblourens ?

**Comment by roblourens** [comment]
I think it's ok to close if this is complicated. It's also a bit odd that if I edit and immediately close the tab, it asks me whether I want to save, when I've enabled autosave.

**Comment by bpasero** [comment]
@amunger with your recent changes in https://github.com/microsoft/vscode/pull/187304 and https://github.com/microsoft/vscode/pull/187302 please take note of https://github.com/microsoft/vscode/issues/140069#issuecomment-1004567802. 

Specifically: being able to close an editor that is now not dirty because of auto-save may result in data loss if closing the editor disposes state that is needed for saving.
