### ISSUE TITLE
Support migrating storage for extensions adopting pre-release

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#140088]
Support migrating storage for extensions adopting pre-release

Migration includes following:

- Uninstall the nightly/insiders extension
- Install (with optional storage migration) the Pre-release extension only if
  - it is not installed
  - or it is a release version and the nightly/insiders extension is enabled.

**Comment by sandy081** [comment]
@joyceerhl added following embedder API to support extension storage migration

```ts
type MarketplaceExtension = ExtensionId | { readonly id: ExtensionId, preRelease?: boolean, migrateStorageFrom?: ExtensionId };
```

**Comment by joyceerhl** [comment]
Tested `migrateStorageFrom` API in Code-OSS + vscode.dev + RemoteHub, migration works like a charm and uncommitted changes are preserved. Here's what I did to verify that the API works as expected:
1. Reset VS Code web storage (since storage migration is only done once and skipped thereafter)
2. Start Code-OSS web out of sources
3. Start vscode.dev out of sources bundling GitHub.remotehub-insiders
4. Make a change to a file in the microsoft/vscode repo using GitHub.remotehub-insiders 
5. Apply change to vscode.dev to bundle prerelease GitHub.remotehub and `migrateStorageFrom` GitHub.remotehub-insiders
6. Reload vscode.dev
7. Verify that the change made in step 4 is still there
8. Verify that pre-release of GitHub.remotehub is installed, not GitHub.remotehub-insiders

Will repeat this tomorrow with the Insiders build, but so far looking good. Thanks for the quick turnaround on this!

**Comment by joyceerhl** [comment]
API is looking good in Insiders with the following steps:

1. Start vscode.dev out of sources bundling GitHub.remotehub-insiders
2. Access vscode.dev/github/microsoft/vscode?vscode-quality=insiders
3. Make a change to a file (and repeat steps 2 and 3 with a couple more repos for completeness)
4. Apply change to vscode.dev to bundle prerelease GitHub.remotehub and `migrateStorageFrom` GitHub.remotehub-insiders
5. Reload vscode.dev 
6. Verify that the change made in step 3 is still there and that all other changes are accessible from Remote Explorer
7. Verify that pre-release of GitHub.remotehub is installed, not GitHub.remotehub-insiders

**Comment by sandy081** [comment]
@joyceerhl Can you please verify this or mark this verified as you adopted this?
