### ISSUE TITLE
Unable to open terminal with Zsh Shell

### ISSUE THREAD

**Issue by geekshen8521** [microsoft/vscode#140015]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.63.2
- OS Version: Gentoo Linux x86_64 5.15.12-gentoo-dist

Steps to Reproduce:
I have a fresh install of vscode.

1. have a `settings.json` exactly like below
```
{
    "workbench.colorTheme": "Visual Studio Light",
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "editor.fontSize": 16,
    "terminal.integrated.defaultProfile.linux": "zsh",
    "terminal.external.linuxExec": "/usr/bin/kitty",
    "terminal.explorerKind": "external",
}
```
2. Try to open the terminal by click `Terminal` then `New Terminal`. Prompt error message "The terminal process failed to launch: Path to shell executable "zsh" is not a file or a symlink."
3. Change the `settings.json` to 
```
{
    "workbench.colorTheme": "Visual Studio Light",
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "editor.fontSize": 16,
    "terminal.integrated.defaultProfile.linux": "zzsh",
    "terminal.external.linuxExec": "/usr/bin/kitty",
    "terminal.integrated.profiles.linux": {
        "zzsh": {
            "path": "/bin/zsh"
        }
    },
    "terminal.explorerKind": "external",
}
```
Then open the terminal works.

Extra info:
1. zsh location
```
zsh: /bin/zsh 
```
2. some info from `strace -f vscode`
```
[pid  8063] statx(AT_FDCWD, "/bin/zsh", AT_STATX_SYNC_AS_STAT|AT_SYMLINK_NOFOLLOW, STATX_ALL,  <unfinished ...>
[pid  8063] <... statx resumed>{stx_mask=STATX_ALL|STATX_MNT_ID, stx_attributes=0, stx_mode=S_IFREG|0755, stx_size=834504, ...}) = 0
```
3. create symlink by `ln -s /bin/zsh /usr/bin/zsh` does not work either.

**Comment by Tyriar** [comment]
This was reported in https://github.com/microsoft/vscode/issues/124866 which I thought (at the time) was https://github.com/microsoft/vscode/issues/124968. I'll keep this open to investigate and try repro again.

**Comment by Tyriar** [comment]
Historically had problems reproducing this.

I just tried installing zsh via `brew install zsh`, changing `/etc/shells` to point at the new symlink `/usr/local/bin/zsh` and it works.

**Comment by Tyriar** [comment]
Still works when `"terminal.integrated.defaultProfile.osx": "zsh"` is set and Terminal -> New Terminal is how it's launched. Also after quitting VS Code with no terminal open and opening fresh.

Note that the original bug https://github.com/microsoft/vscode/issues/124866 was created on a mac which is why I'm testing on mac.

**Comment by Tyriar** [comment]
The code where the exception happens:

https://github.com/Microsoft/vscode/blob/e7b3724e0cdc9095d73a06b47203baa2c1777ea8/src/vs/platform/terminal/node/terminalProcess.ts#L224-L227

Maybe `/usr/local/bin` isn't on `$PATH` when this reproduced 🤔

**Comment by Tyriar** [comment]
Next try:

```sh
ln -s /usr/local/bin/zsh ~/my-fake-bin/zsh
sudo vim /etc/shells # point zsh line to ~/my-fake-bin/zsh 
chsh -s ~/my-fake-bin/zsh
```

Restarted OS. Still happens, although I did notice that `/bin/zsh` is actually the executable being launched behind the scenes:

<img width="429" alt="Screen Shot 2022-01-05 at 3 13 25 pm" src="https://user-images.githubusercontent.com/2193314/148303049-886743b6-0f1e-4bda-9565-faf69f36c831.png">

I guess this is most correct when it says the default profile is running `zsh -l`, but it's not as expected.

**Comment by Tyriar** [comment]
Since it seems dangerous to delete `/bin/zsh` now that it's builtin, I tried renaming the fake shell instead:

```sh
mv ~/my-fake-bin/zsh ~/my-fake-bin/zsh2
sudo vim /etc/shells # change to zsh2
chsh -s ~/my-fake-bin/zsh2
```

Restarted OS. This still worked and the executable is explicitly set as `/Users/daimms/my-fake-bin/zsh2` in the logs.

This seems to be an issue with the profile picked up from `/etc/shells` getting overridden by the one from the default configuration here:

https://github.com/microsoft/vscode/blob/2c22ffe6ae0d8d7cf38a511c3375dd68fd151595/src/vs/platform/terminal/node/terminalProfiles.ts#L330-L333

Then _somehow_ the profile gets validated via `findExecutable`:

https://github.com/microsoft/vscode/blob/2c22ffe6ae0d8d7cf38a511c3375dd68fd151595/src/vs/platform/terminal/node/terminalProfiles.ts#L350-L356

Then that validation fails when the profile gets launched which uses some very similar logic with `findExecutable`:

https://github.com/microsoft/vscode/blob/e7b3724e0cdc9095d73a06b47203baa2c1777ea8/src/vs/platform/terminal/node/terminalProcess.ts#L233-L234

The environment when the profile is being validate is `process.env` on the pty host:

https://github.com/microsoft/vscode/blob/2c22ffe6ae0d8d7cf38a511c3375dd68fd151595/src/vs/platform/terminal/node/terminalProfiles.ts#L148

The environment when the profile seems to be based on the shell launch config if it has an `env` entry, perhaps this only reproduces if the shell launch config has its `env` set?

https://github.com/microsoft/vscode/blob/e7b3724e0cdc9095d73a06b47203baa2c1777ea8/src/vs/platform/terminal/node/terminalProcess.ts#L233

I'm still issing a piece in the puzzle but the more I think about this the solution is certainly to be that the profile from the configuration (ie. `zsh`) should be transformed into the validated path when it gets returned. That way it should definitely work when loaded as it doesn't need to call `findExecutable` again (unless the shell is deleted which is an edge case not worth worrying about).

A complication here is what to do with the `/etc/shells` path, we should probably only fallback to that if the shell isn't on the PATH, that will keep the string meaning of the settin, ie:

```ts
"zsh": {
	// This will get it off the $PATH, if not present it will essentially fallback to the detected
	// entry in the below image, just that we will continue to show it in the dropdown by default as
	// it's a high priority shell.
	"path": "zsh"
}
```

<img width="728" alt="Screen Shot 2022-01-05 at 3 47 25 pm" src="https://user-images.githubusercontent.com/2193314/148305851-e3a7e8f9-53c3-4c24-baf3-629a72fea85a.png">

Additionally, I think we will need an internal flag in the profile to indicate that the profile was fetched from the PATH via findExecutable. That way we can omit the absolute path so it's nice an concise still from the create new with profile UI still which is really bad in particular for pwsh via the Microsoft Store:

![image](https://user-images.githubusercontent.com/2193314/148306100-f1295382-4e32-4689-8796-8c8131546e78.png)

Alternatively we could truncate the path only when it's long?

**Comment by geekshen8521** [comment]
I am currently trying to compile the git version at commit 6ef041e33856f453b5afb49746a7304124776704
But I failed on both Arch(nodejs >=17) and Gentoo (yarn hang). So I think I need to setup a debian based machine and try again.

**Comment by Tyriar** [comment]
@geekshen8521 oh sorry, our bot will comment when it's released to insiders so you shouldn't need to build it yourself. I'd be very happy to hear if it's fixed though as I wasn't able to reproduce it in the end.

**Comment by geekshen8521** [comment]
@Tyriar 
Now I think I find out a way to stably reproduce the error. 
1. have a fresh installed vscode 
2. open a terminal and cd to `/etc`, then run `vscode` in the terminal
3. try to open the terminal and failed

I am not sure if that is Gentoo specific. So I download both `1.63.2 vscode` and `insider` deb package from the official website and then extract it and run the /<extract location>/usr/share/code/bin/code (and code-insiders respectively). With then above 3 steps, the insider works each time, and 1.63.2 failed each time. Although I don't know what is the real cause of it, the problem seems to be sovled.

Also, I have noticed something interesting. When running the vscode under etc, by using `vscode --log trace`, the log will report that 
```
[renderer1] [trace] CommandService#executeCommand workbench.action.terminal.new
[renderer1] [trace] terminalInstance#ctor (instanceId: 1) {}
[renderer1] [debug] Terminal process exit (instanceId: 1) with code undefined
[renderer1] [debug] Terminal process exit (instanceId: 1) state 2
[renderer1] [trace] terminalInstance#dispose (instanceId: 1)
```
I produced this with a empty `settings.json`.
