### ISSUE TITLE
Completion list disappears after dash character

### ISSUE THREAD

**Issue by kasperekt** [Microsoft/vscode#14005]
- VSCode Version: 1.6.1
- OS Version: macOS 10.12

I'm working on [extension](https://github.com/ChristianKohler/NpmIntellisense) that autocompletes node package name in _import/require_ strings. There is a problem that inside package class that implements `CompletionItemProvider`, `provideCompletionItems` method doesn't fire when I type `-` inside _import/require_ string and this results in empty completion list. When you type next letter e.g. `d` it filters completion items JUST by this letter. It should still take the whole string into account.

This issue somehow references this [issue](https://github.com/ChristianKohler/NpmIntellisense/issues/10) from NpmIntellisense package.

**Steps to Reproduce:**

Install [NpmIntellisense](https://github.com/ChristianKohler/NpmIntellisense) package. Prepare project with `package.json` that have `react` and `react-dom` extension installed (and saved!!!).

1. Create some JS file.
2. Type `import React from 'react-'`
3. As soon as you type dash character `-`, completion list disappears.
4. After you type `import React from 'react-d'`, it filters text by letter `d` that is after dash character.

**Comment by jrieken** [comment]
By default, completions work with the word definition of your language and most languages don't include `-` as a word character. 

You can overcome that by not relying on the word-definition and by assigned a `TextEdit` to your completion items. A `TextEdit` is a range/selection and newText and iff available we will use that to filter and sort individual completions

**Comment by freebroccolo** [comment]
@jrieken it seems to me that even if the `textEdit` field is used, if a completion item has non-word characters in it (determined by the language word regex),  like `-` or `*`, the suggestions widget will still close if those characters are typed unless the language word settings are changed to include them. Can you confirm that this is indeed the intended behavior?

Is there any way to override this behavior?

My intended use case is an implementation of an emacs style LaTeX input method for unicode characters where sometimes the completion label does not consist of words but might look like `\<=>n` and insert ⇎. Since this completion provider is intended to be used globally, I'm not sure how to work around the fact that for most languages the suggestion widget will close after typing `\<`. I can get it to work without closing early for some more flexible languages with patterns like `wordPattern: /[^\\\s\d(){}#][^\s(){}]*/` but this is not the common case. 

One possibility might be to associate a command with potential non-word entries in order to retrigger the suggestion widget immediately. But this probably wouldn't handle the replacement properly without doing further `TextEdit`s and would probably look bad.

**Comment by jrieken** [comment]
@freebroccolo Can you attach a small code snippet? Then I'll debug into it
