### ISSUE TITLE
Not Able click on Trust Project while opening a new Project/Solution

### ISSUE THREAD

**Issue by TapanKumarBarik** [microsoft/vscode#140031]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1. Downloaded a next js code from github
2. Unzip it and try to open it on vs code
3. the trust button was not visible at all .

**Comment by joeljose350** [comment]
Did you trust a folder that contains the folder with the extracted files? If you did, then you will not be asked if you want to trust the extracted folder because it is already assumed to be trusted. For example, if you trust `/home/users`, then all folders inside that directory will automatically be trusted by VS Code.

**Comment by sbatten** [comment]
as @joeljose350 says, can you share more information about where you unzipped the folder and what folders you have already trusted on your machine?
