### ISSUE TITLE
Error With Automatic Formatting Code 

### ISSUE THREAD

**Issue by Goldenboyy01** [microsoft/vscode#140197]
Issue Type: <b>Bug</b>

The code automatically reformats and changes. 

When I try to write the code 
<div></div> 

It automatiacly fromats too 
<div >
<
/div>

Please fix this error and correct it or I will have to go to another code editor. 

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.85GB (0.66GB free)|
|Process Argv|--crash-reporter-id 01ee414f-a371-41b4-86a7-b8bd38cad9d5|
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (58)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
cypress-snippets|and|1.2.0
babel-compile-on-save|asv|1.0.6
tailwind-docs|aus|1.4.0
markdown-emoji|bie|0.2.1
tailwindshades|bou|0.0.5
vscode-tailwindcss|bra|0.7.4
solargraph|cas|0.23.0
glsl-canvas|cir|0.2.14
postcss|css|1.0.9
svg-gallery|dev|2.1.0
docs-images|doc|0.0.9
es7-react-js-snippets|dsz|3.1.1
vscode-glsllint|dto|1.6.0
vscode-babel-coloring|dza|0.0.4
Solidity|Ele|0.0.58
magick-image-reader|ely|0.5.0
react-native-react-redux|EQu|2.0.6
vscode-nupkg|eri|1.0.1
prettier-vscode|esb|9.1.0
docker-explorer|for|0.1.7
vscode-lombok|Gab|1.0.1
vscode-yarn|gam|2.0.0
copilot|Git|1.7.4421
vscode-graphql|Gra|0.3.41
vscode-nuget-package-manager|jmr|1.1.6
solidity|Jua|0.0.136
vscode-JS-CSS-HTML-formatter|lon|0.2.3
vscode-language-babel|mgm|0.0.35
dotenv|mik|1.0.1
graphql|mqu|0.1.2
vscode-docker|ms-|1.18.0
csharp|ms-|1.23.17
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2022.1.0
jupyter|ms-|2021.11.1001550889
remote-containers|ms-|0.209.6
remote-ssh|ms-|0.70.0
remote-ssh-edit|ms-|0.70.0
remote-wsl|ms-|0.63.13
vscode-remote-extensionpack|ms-|0.21.0
vsliveshare|ms-|1.0.5201
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
tailwind-styled-snippets|muh|0.2.1
emoji|Per|1.0.1
material-icon-theme|PKi|4.11.0
prettier-now|rem|1.4.9
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
prettier-vscode|Sim|2.0.7
shader|sle|1.1.5
tailwindcss-transpiler|sud|0.0.8
openvms-syntax|tom|0.1.0
emoji|tom|0.2.2
material-ui-snippets|vsc|3.3.8
babel|wmo|1.6.0
eno|Wsc|2.3.53

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vscop804:30404766
vscop940:30404999
vsrem710:30416614
py55gd98:30419165
vscexrecpromp3t3:30407764

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

**Comment by jrieken** [comment]
It looks like the issue is caused by one of your installed extensions. All extensions execute together on a single nodejs process, so in order to narrow down the possible problematic extension, please try the following:
* run `F1 > Help: Start Extension Bisect`
* (this will restart VS Code with half of your extensions disabled)
* try to do the steps which reproduce the problem
* if the problem reproduces, click "This is bad" (this narrows down the problematic extension to the half which was enabled)
* if the problem does not reproduce, click "Good now" (this narrows down the problematic extension to the half which was disabled)
* these steps will repeat until the problematic extension is found

| initial | step | final |
|---|---|---|
| ![image](https://user-images.githubusercontent.com/5047891/101918658-e9170f80-3bc9-11eb-9977-857baa291937.png) | ![image](https://user-images.githubusercontent.com/5047891/101918683-ef0cf080-3bc9-11eb-9f9e-98b0177991b2.png) | ![image](https://user-images.githubusercontent.com/5047891/101918706-f502d180-3bc9-11eb-8c86-e56355958bd4.png) |
