### ISSUE TITLE
RTL Word Wrapping Issue

### ISSUE THREAD

**Issue by AmshegaR** [microsoft/vscode#14019]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T16:21:53.542Z)
- OS Version: Windows_NT ia32 10.0.10586

I like this editor cause of its RTL support!
All working nice except this little annoying bug with word wrap...

![image](https://cloud.githubusercontent.com/assets/6332931/19537537/083d93ae-9659-11e6-832c-5a22e5eeb595.png)

**Comment by alexandrudima** [comment]
@amshegar Could you please share the file contents in textual form.

**Comment by amshegar** [comment]
It's not about text ...
[example.txt](https://github.com/Microsoft/vscode/files/559861/example.txt)

**Comment by alexandrudima** [comment]
Indeed, this is caused by the word wrapping logic. The word wrapping logic does not layout text (we leave that to the browser), the code simply counts characters and it does not take into account combining characters or variable character width fonts.

For example, in this case it has determined that the maximum count of chars it should allow on a line is 99. This is the case for both Latin, Hebrew and Arabic:

![image](https://cloud.githubusercontent.com/assets/5047891/19850670/f3a86e28-9f59-11e6-9a60-fa8312ddc7e0.png)

![image](https://cloud.githubusercontent.com/assets/5047891/19850683/09746388-9f5a-11e6-926f-27911c8514d2.png)

In this case, Hebrew text runs into both limitation of the code:
* the code does not take into account combining characters, nor does it look at high-low surrogate pairs
* the code does not take into account variable width fonts.

The second bullet point can be aleviated by using a monospace font, such as Inconsolata, but this also makes more proeminent the limitations of the first point (i.e. combining characters, high-low surrogate pairs).

I can look into making the word wrapping code at least high-low surrogate pairs aware.

**Comment by alexdima** [comment]
Let's track in #2654
