### ISSUE TITLE
Cursor is rendered inside some emojis

### ISSUE THREAD

**Issue by HaoboGu** [microsoft/vscode#140149]
Does this issue occur when all extensions are disabled?: No

With VSCode Vim

- VS Code Version: 1.63.2
- OS Version: MacOS 12.0.1

Steps to Reproduce:

1. Paste this emoji to a new editor 👨‍👩‍👧‍👦
2. The cursor is rendered inside it
![image](https://user-images.githubusercontent.com/8640918/148181531-d4fe887b-5060-46a2-868e-5768b2482c30.png)

3. If you turn on VSCode Vim, you can even see this:
![123](https://user-images.githubusercontent.com/8640918/148181951-0efea3ea-6fd5-4a4e-abff-ba810e79c61a.gif)

**Comment by alexdima** [comment]
Here is how to reproduce without `VSCode Vim`:
* create a new file with the contents 👨‍👩‍👧‍👦
* configure `"editor.cursorStyle": "block"`
* run `F1 > Go to Line/Column... > 1,6`

This doesn't reproduce with regular cursor movements (like arrow left / right / up) because the built-in cursor movements commands are grapheme aware and they only set the cursor position in between graphemes. I think VSCode Vim is not grapheme aware and simply asks us to set the selection e.g. at (1;6), which we will honor, because it is technically a valid position (i.e. even if it is inside a grapheme, it is outside surrogate pairs and therefore valid).

I'm not sure what the best way forward is, I think we shouldn't try to move the selection off (1;6) to the grapheme boundaries, but rather just improve the rendering in this (bad) case.

**Comment by alexdima** [comment]
To the verifier: the fix is to continue allowing placing the cursor inside a grapheme, it is just that the rendering now always renders a grapheme together in the cursor block case. In other words, after going to `(1,6)` it is possible to break up the emoji by typing `x`, e.g. : `👨‍👩xxx‍👧‍👦`. This is done in order to not break in any way vim editing logic.
