### ISSUE TITLE
Search function: design of the function lacks efficiency

### ISSUE THREAD

**Issue by eclipse-like** [microsoft/vscode#140272]
I have put another ticket for the same topic a while ago and I received a reply with "this is the search function and we are not going to change it". However I consider it an important feature and honestly this implementation is the worst I have worked with. 
The problem appears when you want to open more than one search window. Instead of opening a new window near the existing one in the bottom menu tab, this is done in the  code section. I have created two windows to split the search from the code, but the problem is there is not enough space in horizontal to see clear both the search window and the code one.
![image](https://user-images.githubusercontent.com/91057769/148539536-de50798c-a3d8-45bd-8da8-b931ecceb098.png)

You need all the time to increase/decrease the size of the windows and navigate between the code and the search.

Check how this is done in eclipse:
![image](https://user-images.githubusercontent.com/91057769/148539641-dfe9abf5-47df-409b-9931-37d0c5f68473.png)

You can open several search windows and the search content is displayed on the entire screen width.  Also the code is on the entire screen. 

In your case, this entire section remains unused:
![image](https://user-images.githubusercontent.com/91057769/148539759-1859a4e1-cac6-4bb2-9c5a-1f67f4309157.png)

It is absolutely obvious this function can be improved. Just because it was a bad design form the beginning does not mean it has to stay like this.
Regards,
Catalin.

**Comment by gjsjohnmurray** [comment]
Meanwhile, here are some workarounds:

Are you aware that you can split down instead of splitting right? By doing that you will get the full width.

Optionally, first go to the `workbench.editor.autoLockGroups` setting and set a checkmark against 'Search Editor'. This helps with the next step.

Run the `View: Move Editor into Group Below` command after opening your first search editor. It moves to the new group below, and if you performed the previous step the new group gets locked automatically so other types of editor won't open there by default even if you are focused in it.

The next search editor you open from the search view will go there if a previous search editor in the group is still active. If it isn't, the new search editor can be dragged down into the group.

**Comment by gjsjohnmurray** [comment]
See also #115899

For reference, your previous issue was #133437

**Comment by gjsjohnmurray** [comment]
And #134698 (Add settings to open certain editor types in specific locked editor groups) would have helped streamline the procedure I described above, but it didn't get enough support to move onto the Backlog.

**Comment by roblourens** [comment]
Thanks for the response @gjsjohnmurray, I agree with those observations. Not planning any changes here currently.
