### ISSUE TITLE
Fuzzy matching for intellisense

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#14027]
- VSCode Version: 1.7 Insider
- OS Version: OS X 10.11.6

![foobar](https://cloud.githubusercontent.com/assets/4033249/19541304/1f9df2c6-961a-11e6-9d55-18a7bf72c5f9.gif)

**Comment by roblourens** [comment]
I've wanted this too.

**Comment by csalv5** [comment]
This is the first bad thing i've noticed during the switch from sublime/other modern editor

Actually, matching is not completely fuzzy, so take it into account :+1:

**Comment by jrieken** [comment]
Since @octref doesn't really state what we wants and since I have made some improvements in that area for #14583 and #14446 I take the freedom to close this issue with another attached gif. This is what you see on *master*

![oct-27-2016 17-54-22](https://cloud.githubusercontent.com/assets/1794099/19774803/91bd7e08-9c6e-11e6-9e3f-d8827c3c7a24.gif)

**Comment by octref** [comment]
@jrieken Thanks a lot. This looks good. I'll try it out and report issue with more description next time.
