### ISSUE TITLE
Missing Sublime command - Go to word

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode#14028]
While building this [extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.sublime-keybindings) I found that VS Code is missing feature parity with Sublime Text. The feature is go to word. 

![goto_word](https://cloud.githubusercontent.com/assets/2449568/19541623/7baea090-961c-11e6-929b-92fba7a52003.gif)

Default keyboard shortcut is <kbd>ctrl+j</kbd> on Windows. Sublime Text does not define a keyboard shortcut on Mac for this by default.

**Comment by alexandrudima** [comment]
To keep the number of issues in our inbox at a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: we look at the number of votes the issue has received and the number of duplicate issues filed. Thank you for your time and understanding.

If you disagree and feel that this issue is crucial: we're happy to listen and to reconsider.
