### ISSUE TITLE
Fix dirty tab indicator after hot exit restore

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#14038]
Introduced in https://github.com/Microsoft/vscode/pull/12400, the (inactive) tabs being restored do not get their dirty indicator until the files are made active.

**Comment by Tyriar** [comment]
A side effect of this is if the file is opened from the explorer before it is switched to then it's not restored.

**Comment by Tyriar** [comment]
@bpasero I see the code for this is in tabsTitleControl. Not too familiar with this code though, any advice where/how I should make the tabs refresh their dirty states after startup?

**Comment by bpasero** [comment]
@Tyriar can you give me a code snippet for me to reproduce this (without introducing all of hot exit)? Maybe I can fix this independent from hot exit 👍

**Comment by bpasero** [comment]
Actually I think this applies to a lot more than just tabs. We have listeners for dirty files everywhere in the workbench (e.g. opened editors view too).

**Comment by Tyriar** [comment]
@bpasero I assume this is related to assumptions made in the model initialization code that they will never be created as dirty.

**Comment by bpasero** [comment]
I think it already works fine for untitled files as you can see by starting code.sh with a file that does not exist (it will open right as dirty). And the related code seems to be https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/common/editor/untitledEditorModel.ts#L133

So what is missing is firing the event right after loading the model. I think the timeout is needed to actually wait until other listeners are in place.

**Comment by Tyriar** [comment]
@bpasero a timeout as in x seconds? Do you have a recommended number of ms to (hopefully) guarentee it won't be flaky?

**Comment by bpasero** [comment]
I think all it needs is a timeout of 0 so that the workbench parts have a chance to create and show the dirty indication.

**Comment by Tyriar** [comment]
It actually seems to be happening because `load` is only called when the editor is focused so I need to evaluate whether there is a backup or not outside of `load`.

**Comment by Tyriar** [comment]
Hmm... The TextFileEditorModel is only constructed when the tab is focused.

**Comment by bpasero** [comment]
Wow, this is a bug:

![image](https://cloud.githubusercontent.com/assets/900690/19917857/2b18cdd0-a0c7-11e6-9f61-de1a281dd465.png)

https://github.com/Microsoft/vscode/issues/14835

**Comment by Tyriar** [comment]
The `UntitledEditorModel` constructor is also only called into when focusing the tab, not sure there is any way of getting a dirty untitled file currently though so it might be by design and can be covered as part of this issue.

**Comment by bpasero** [comment]
I pushed a [change](https://github.com/Microsoft/vscode/commit/43f86ea354a4eec862437b52bc6c46a9efc445ce) that improves this. Basically `IEditorInput.isDirty()` has to return true even if the file is not opened yet and an untitled file is always dirty if it has an associated path. I left the timeout of 0 in because I think there is still a race condition where we create the untitled input and some components might not yet be ready for listening. 

I would think that the backup service needs to carry this information to the untitled files and files: if there is a backup, they are dirty in the same way as an untitled file is dirty when it has an associated file path.

**Comment by Tyriar** [comment]
For text files which this is also need for, I'm having difficulty seeing how this can be done without making either `FileEditorInput.isDirty` asynchronous which will force a bunch of other changes.

My thinking was that before loading the files I could prime the BackupFileService and get it to cache whether some resources have backups associated with them. This doesn't work though as on launch the `FIleEditorInput`s are created through the `Workbench` which also initializes `BackupFIleService` so it can't/shouldn't AFAIK be used as a dependency there. A similar situation applies to `WorkbenchEditorService` which is the other place that assists in the creation of the `FileEditorInput`s since there can't be a circular dependency (`BackupFileService` -> `FileService` -> `WorkbenchEditorService`).

So that leaves the backup logic having to be done in `FileEditorInput` somewhere which from what I can see can't do anything async in between the ctor and `isDirty` calls. Thoughts?

**Comment by bpasero** [comment]
This one is tough. We cannot make `isDirty()` async, that is not an option. Can we leave this problem for later? I do not have a good answer right now without introducing more debt. Maybe I need to revisit how the dirty state is determined to make this work properly.

**Comment by Tyriar** [comment]
Yep let's leave it for later, ideally it would get looked at sometime in November though as the feature feels pretty buggy without it.

**Comment by bpasero** [comment]
@Tyriar yes, I agree. but I also think that we should team up once the major pieces are pushed to master and then maybe I can look into this particular issue.

**Comment by bpasero** [comment]
@Tyriar is there any possibility to make `IBackupFileService` run from an in-memory model? Related issue: https://github.com/Microsoft/vscode/issues/15515

Asking because a sync `hasBackupFile()` method would fix this issue easily from the `isDirty()` check of the file editor input.

**Comment by Tyriar** [comment]
Running in-memory will break the crash recovery case, no?

What about checking on the main process and passing the 'intiial state' over to the renderer process to be used only in workbench initialization?

**Comment by bpasero** [comment]
@Tyriar Hm hm, yeah then we are basically back to the "restore resource" that you had, for files.

There is one thing I just realised which worries me a bit: Initially I thought just having the boolean on `EditorInput.isDirty()` would be enough for this scenario, but that is totally wrong. Many places in the UI actually go to the `ITextFileService` to find  out if there are dirty files and not to the inputs. 

Imagine the "Save All" action: This action could be invoked right after startup without opening individual tabs. Since the tabs are not loaded, the save would be pretty useless and nothing would happen.

I wonder if we should do something else, though a bit ugly: right after startup we have a workbench contribution that goes over all files with backups and loads them into memory. This would trigger all related events and put the services into the right state.

**Comment by Tyriar** [comment]
@bpasero could that have an impact on start up time though? Hot exit will probably be the default eventually so we need to make sure it's still snappy.

**Comment by bpasero** [comment]
I think it would be ok because all `fs` access happens async and will not block any UI updating. It is still not ideal and ugly compared to what we do today where you can have as many editors open as you want and that does not cause any additional work.

The alternative is to carry over the state of backup files to the workbench to be able to answer for the `isDirty()` quickly and then rewrite the text file service to account for this. This is a bigger change because today the text file service is under the assumption that a dirty file has a editor model in memory.
