### ISSUE TITLE
sometimes terminal tab titles disappear

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#140302]
I'm not sure the repro case yet, but I have seen it a few times daily for the past week

![Screen Shot 2022-01-07 at 1 26 33 PM](https://user-images.githubusercontent.com/29464607/148596544-183f89c0-0bfc-477b-b8e0-0f05e8732b23.png)

**Comment by Tyriar** [comment]
I've seen this once, I think I closed a terminal and it fixed it

**Comment by haneefdm** [comment]
Happens to me very frequently, but cannot duplicate it at will. In my case, the tab list area is totally empty (no icons). If I resize the terminal/tab-list area by shrinking/expanding the vertical separator, everything comes back. 

I can still select a terminal since I know there is something there even if I can't see it. Then it seems to partially render. I will keep a closer eye. This started with 1.63.1/2 I think
