### ISSUE TITLE
Remember target directory when downloading files

### ISSUE THREAD

**Issue by DanielSWolf** [microsoft/vscode#140358]
When VS code is connected to a remote server, I can right-click a file, then choose "Download..." to download it to my local machine. Sadly, the "Save as" dialog doesn't remember the directory I select. So when I perform a second download, I have to select the same directory all over again. It would be convenient if the previously-selected directory was remembered.

**Note:** The similar issue #119272 was recently closed as a duplicate. Unfortunately, the duplicated issue wasn't linked, so it's unclear to me where the existing issue is. I did my best to search for it, but couldn't find it.

**Comment by gjsjohnmurray** [comment]
Maybe #115730

**Comment by DanielSWolf** [comment]
Thanks @gjsjohnmurray, but that doesn't seem to be quite the same. #115730 is about changing the default target directory; this issue is about remembering the last used target directory.

**Comment by DanielSWolf** [comment]
@thernstig You might want to upvote this issue, since you created a very similar one which was closed.

**Comment by bpasero** [comment]
For the "Download" command we now remember the path where to download and restore that. This information is stored globally (i.e. applies to all windows) but will not roam via settings sync, because paths are typically machine local.

Previously we did a questionable computation of a default path that typically always ended up in the user home directory, which imho does not make a lot of sense for the download operation.

**Verification:**
* connect desktop to any remote
* right click from the explorer "Download"
* pick a destination
* repeat and verify the destination restores even across restarts
