### ISSUE TITLE
Missing Sublime command - find and select all occurrences of a symbol

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode#14030]
While building this [extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.sublime-keybindings) I found that VS Code is missing feature parity with Sublime Text. The feature is find and select all occurrences. 

This is what I see in Sublime Text. 

![find_and_select_all](https://cloud.githubusercontent.com/assets/2449568/19541692/0867dede-961d-11e6-9b48-036ce8d762c5.gif)

As far as I can tell an equivalent feature does not exist in VS Code. 

The keyboard shortcut for this feature in Sublime Text is <kbd>alt+f3</kbd> on Windows / Linux and <kbd>ctrl+cmd+g</kbd> on Mac.

**Comment by roblourens** [comment]
VS Code has something very similar - cmd+f, do a search, then press alt+enter to select all matches. But I just found that I have some extension installed that overrides that keyboard shortcut and throws an error, which is extremely annoying, and now I have to figure out which one it is. And it would be nice to have something that works exactly like sublime, with one step instead of two. I guess an extension could cover this though.

**Comment by Swiiip** [comment]
There is a shortcut is VSCode for this : `cmd + L` (cmd + shift + l) on mac. I guess its `ctrl + L` on PC

**Comment by waderyan** [comment]
@Swiiip awesome! That is what I was looking for. Thanks!

**Comment by jonayreyes** [comment]
The selection is limited only to the first 1000 occurrences :(

**Comment by xgqfrms-GitHub** [comment]
# VScode  & SublimeText

> both have its advances!

```md
VScode `Ctrl + F & Alt + Enter`

=== 

SublimeText Alt + F3
```
