### ISSUE TITLE
Terminal tabs shows as narrow view even when very wide

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#140547]
I'm unfortunately not able to reproduce this reliably, but I see it happen at least once per day... I go to the terminal pane, and the tabs section is very large, but only the icons show. The second I resize the tabs container either way, the full labels appear.

![image](https://user-images.githubusercontent.com/8586769/149069833-d29f4fe9-5bf6-488a-94b5-67620c50cdd6.png)

**Comment by JacksonKearl** [comment]
Ah ha, steps: 

1. In vscode repo, have some terminals open, with a wide tab container
1. Switch to problems pane. 
2. Start build task (Cmd+Shift+B)
3. switch back to terminal, see the tab container still wide, but rendering as if it were narrow.

![Recording 2022-01-11 at 21 42 37](https://user-images.githubusercontent.com/8586769/149070640-d864c3d7-fb15-4d01-b86d-cd53ccedf003.gif)

**Comment by Tyriar** [comment]
Woo, repro steps! @meganrogge and I both have seen this but had no idea how to repro 🎉

**Comment by Tyriar** [comment]
Important part of tasks.json if not testing in vscode repo:

```
"presentation": {
        "reveal": "never",
        "focus": false,
},
```

**Comment by Tyriar** [comment]
This is happening because `hasText` checks the container's width when determining whether to display the text:

https://github.com/Microsoft/vscode/blob/00b535ca43cc93f43b9599cd5f6e62a20569af0e/src/vs/workbench/contrib/terminal/browser/terminalTabsList.ts#L277

Easy fix should be to force a re-render when the list is displayed.
