### ISSUE TITLE
Inlay hints should show problems for the range in the hover

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#140517]
Hovering inlay hints should show problems "underneath":

![Recording 2022-01-11 at 12 42 26](https://user-images.githubusercontent.com/2193314/149018527-784893a2-d76f-477a-94e0-2224ac697934.gif)

**Comment by jjspace** [comment]
Came here to report the same thing

https://user-images.githubusercontent.com/8007967/165316556-6e10bcb9-3737-448f-bc73-09a88cb92773.mp4

**Comment by alexdima** [comment]
@jrieken The `HoverForeignElementAnchor` is used both by inlay hints (via `InlayHintsHoverAnchor`) and ghost text (directly instantiates it). I think in the case of inlay hints you want that markers appear, but perhaps ghost text wouldn't want that markers appears because the might want to show only these actions:

<img width="598" alt="image" src="https://user-images.githubusercontent.com/5047891/206478653-96cd1111-4439-4732-89e0-cd1976e8dba1.png">

My suggestion would be to add something to `HoverForeignElementAnchor` to be able to distinguish the two cases.

**Comment by lramos15** [comment]
Can still repro this

**Comment by jrieken** [comment]
@Tyriar Please update this issue with a real code snippet that allows to reproduce this, @lramos15 please update this issue with what you have tried. Thanks

**Comment by lramos15** [comment]
> @Tyriar Please update this issue with a real code snippet that allows to reproduce this, @lramos15 please update this issue with what you have tried. Thanks

I just found a reduce function in VS Code sources such as `return this.viewItems.reduce((r, item) => r + item.minimumSize, 0);` and replace the returned value with the void keyword such as
`return this.viewItems.reduce((r, item) => void, 0);`

**Comment by jrieken** [comment]
Something like this only gives a squiggle for the return value, not the arguments or anything with inline hints. To clarify, this will only work for squiggles that spawn across inline hints

```
return this.viewItems.reduce((r, item) => void, 0);
```

<img width="699" alt="Screenshot 2023-01-26 at 14 49 07" src="https://user-images.githubusercontent.com/1794099/214852122-f532f22a-a486-4f54-979f-0be2ab64df00.png">

**Comment by jrieken** [comment]
Thanks for updating

**Comment by aeschli** [comment]
Looks good to me.

Version: 1.75.0-insider
Commit: acbbdaa41a459aab86072e8d97255cd2ea1d9529

![image](https://user-images.githubusercontent.com/6461412/215049524-f52e4624-dc7e-4d12-ae41-205eb593fcbd.png)
