### ISSUE TITLE
Collapsed cells retaining their states during cell arrangement

### ISSUE THREAD

**Issue by teddywaweru** [microsoft/vscode#140670]
When moving cells in the notebook using the shortcut "Alt + Up/Down Arrow", collapsed cell outputs are automatically reopened. Would it be desirable feature for the cells to **retain** their state during rearranging? Especially helpful in cases where outputs are large,. Similar situation for collapsed input cells as well.

**Comment by greazer** [comment]
Maintaining cell state (collapsed) is something the core needs to address.

**Comment by rebornix** [comment]
@roblourens we might need to carry over the view state of collapse when moving cells since now it's not part of cell metadata I guess.

**Comment by roblourens** [comment]
Collapse state needs to be stored on the cell text model, not the view model

**Comment by roblourens** [comment]
I don't think storing collapse state on the text model is the right solution... really we need to be able to transfer view state from one cell VM to another, but there is no mechanism to do that.

@rebornix any ideas about where that should happen? We move the cell text model then recreate the cell VMs. I guess here we know that this is a move, and should move the old cell VMs instead of recreating them:

https://github.com/microsoft/vscode/blob/09d3d16f98c5f8bcb538d4b5be50f79c1f874707/src/vs/workbench/contrib/notebook/browser/viewModel/notebookViewModelImpl.ts#L277

**Comment by DonJayamanne** [comment]
Thank you for filing this issue, unfortunately we do not have any plans on resolving this issue.
