### ISSUE TITLE
Allow to place tabs at the bottom

### ISSUE THREAD

**Issue by Pingear** [microsoft/vscode#140674]
I don't understand why [this](https://github.com/Microsoft/vscode/issues/50318) feature request was closed, it's really a useful feature for mac users. 
So, would it be possible to have an option to move tabs to the bottom of the screen?

**Comment by nodgear** [comment]
upvoting to the limits

**Comment by mmcgraw73** [comment]
i just upvoted so hard

**Comment by bpasero** [comment]
Please see #167999 for our plan this month to clean up and "groom" all opened issues. This issue was closed as part of that initiative.

**Comment by zalimitless** [comment]
As someone who uses Virtual Machines on Hyper-V, this feature would make a big difference to quality of life.
This gets frustrating when the top of the screen gets touched, unintentionally, and the Hyper-V's settings appear.

Unfortunately the "Customize UI", [which was previously suggested](https://github.com/microsoft/vscode/issues/140674#issuecomment-1339407051), has been deprecated as it is not maintained anymore.

**Comment by webuniverseio** [comment]
Customize UI will crash VSCode if you try to use it
This is one of the features I'm missing while I compare VSCode to JetBrains

**Comment by mmcgraw73** [comment]
solved _sorta_
im sure ms is gonna love this post

1. get [cursor](https://www.cursor.com/) its built on top of vscode 
2. Open Settings:
3. Press Cmd+, (Mac) or Ctrl+, (Windows)
4. Or click the gear icon
5. Search for "tab position"
6. Change the "Tab Position" setting to "bottom"
7. Note: If you don't see this option immediately, you may need to:
8. Update Cursor to the latest version
9. Look under the "Workbench" or "Editor" settings sections

The tabs should now appear at the bottom of your editor window instead of the top.

**Comment by SheepDomination** [comment]
@mmcgraw73 You want everyone to use A.I. 

I'm surprised that Microsoft hasn't granted this option to move the tabs to the bottom. Now considering that's it an A.I code editor, you'd think it would come now.
