### ISSUE TITLE
Hot Exit: Restore untitled files from within UntitledEditorModel

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#14067]
I see the motivation for this but it goes through so many layers that we should NOT have this at all. Both untitled and text file world in the end have a good place where you should check for backups and get the contents from there: `TextEditorModel.load()`. That is the only safe place to know if a backup is present and to restore it, everything else is just fragile.

**Comment by bpasero** [comment]
Please see more traces of this issue:

![image](https://cloud.githubusercontent.com/assets/900690/19588344/4bc9acc2-9765-11e6-818f-5cd6e24051db.png)

**Comment by Tyriar** [comment]
Nice find. I just did https://github.com/Microsoft/vscode/pull/14115/commits/6a10eeb30f2a9fbba0859a5bde0e2287ba46ffd0 to remove it all from the text file side. I don't have plans to remove it from untitled as I don't see a way of restoring untitled from the model, I did remove the `setResource` function in favor of the constructor earlier though.

![image](https://cloud.githubusercontent.com/assets/2193314/19590359/505b4af0-9726-11e6-9501-4d29933868a4.png)

**Comment by bpasero** [comment]
@Tyriar why can it not be removed from untitled world? I would assume that on startup of the workbench there is a list of untitled resource URIs to open since they were dirty. This information should be enough to ask the backup service for its contents. The backup service is aware of the contents for the untitled files from the previous sessions and I do not see why the same check for backups as in files land cannot happen here?

Reopening for discussion on this topic.

**Comment by bpasero** [comment]
Yes I see the issue and I am wondering if we can just leverage the power of `URI` here: as far as I know we can add to the `query` portion of the `URI` and so you could use the normal `Untitled-1`, `Untitled-2` resource URIs and maybe add the backup resource as a query portion to the `URI`. The model would check for it and use it to restore from the other resource and then remove the query portion once done.

**Comment by Tyriar** [comment]
I'm not sure the use of `Uri.query` for something it was not intended for would be better?

**Comment by bpasero** [comment]
@Tyriar yup it's a hack. Can you clarify why we can not go to the backup service and ask for a backup for an untitled resource URI? Is the problem that you could have Untitled-2, Untitled-3 but not Untitled-1 as a dirty untitled backup? If so, I would expect if the workbench is instructed to open Untitled-2, Untitled-3 it would just work?

**Comment by Tyriar** [comment]
I think that should work actually, instead of using a `null` resource it will create potentially several `Untitled-x` based on a asking the `BackupFileService`, something like this:

1. `UntitledEditorService` asks `BackupFileService` for all untitled resource names
2. `UntitledEditorService` creates an `UntitledEditorInput` with that resource
3. When the model is created `BackupFileService` is asked if there are backups for that untitled file (which we can cache after `workspaces.json` is split up in https://github.com/Microsoft/vscode/issues/14064

One of the main things I was worried about was untitled files getting restored multiple times, but this should never happen if the resource is used as the resource's `fsPath` is guaranteed to be unique and the backup is discarded when saved/closed.

**Comment by bpasero** [comment]
Ah yes, I was always expecting the backup service to also have untitled resources as URI for untitled backup files. I think this is a clean model and aligns with what you do for files already.

**Comment by bpasero** [comment]
This is a potential requirement for https://github.com/Microsoft/vscode/issues/15498
