### ISSUE TITLE
Allow to open a side by side page on the right side 

### ISSUE THREAD

**Issue by jaeyonglee8687** [microsoft/vscode#140609]
![ezgif com-gif-maker](https://user-images.githubusercontent.com/87626977/149273205-bfa16d21-877e-486d-9621-dd402df9a6d8.gif)

The default behavior opening a side-by-side window always goes to the left side when a single window is opened (right -> left). 
This might be less intuitive / feel comfortable due to the human instinct;  left to right, top to bottom feels more natural, e.g., reading, opening a new tab on a browser, etc, except some very unique cultural contexts, e.g., Japanese cartoon books start from right to the left, and some traditional Japanese/Chinese books are written top to bottom and the flow goes right to the left. But I believe that most people might follow the left to the right idea as a directional convention.

Maybe this is set in VSC because the left side catches more attention than the right side as people normally ready left to the right, and the content on the new left window might need more attention than the right side one. Or maybe it's to cover some other scenarios. 

However, even though it's not directly a usability issue, I believe that it will feel more 'natural' to pop up the side-by-side window on the right side. In case the side-by-side window is already enabled (two windows are open) and a trigger is from the right side, opening a new window on top of the opened left side window. 

Maybe we can allow the flexibility?

**Comment by jaeyonglee8687** [comment]
@zihong

**Comment by bpasero** [comment]
Please provide a minimal reproducible sample code to show this limitation.

**Comment by jaeyonglee8687** [comment]
@1openwindow
Please take the issue and provide the reproducible sample code for this issue.

**Comment by 1openwindow** [comment]
@bpasero , please check this code: https://github.com/microsoft/vscode-java-pack/blob/78fcf334bbf585e8519130827b6afde1337c3a89/package.nls.json#L4

in the walk through experience, vs code support command like this: "**command:toSide**:java.installJdk.fromWalkthrough". toSide means when user click the button in walk through, it will open a new tab on the left side. This might be less intuitive / feel comfortable due to the human instinct.

It will be great if vs code can allow extension to decide either open on the left side or right side.

**Comment by JacksonKearl** [comment]
I'd consider a setting to change the open direction if you're very passionate about this, but I generally don't think there is a strong need.
