### ISSUE TITLE
Inlay-hints: Allow to make them case insensitive and look within variable names

### ISSUE THREAD

**Issue by Johnhersh** [microsoft/vscode#140793]
Inlay hint suppression should be smarter. For example, just having the option to make it case insensitive would go a long way. I have lots of these:
![image](https://user-images.githubusercontent.com/20746719/149641846-c3252031-3acd-4834-a53e-6e6ef27e0506.png)

But also sometimes the name is contained within the name of the variable:
![image](https://user-images.githubusercontent.com/20746719/149641867-12cdaa5e-97ec-493d-88b1-bca3731af850.png)

**Comment by jrieken** [comment]
This is specific to TypeScript

**Comment by mjbvz** [comment]
This feature is powered by the TypeScript project. Please [file a feature request upstream](https://github.com/microsoft/TypeScript/issues/new?template=Feature_request.md)

But also note that today suppression only applies to parameters and function calls. That means we will never hide anything in your first example because the inlay hint isn't redundant in the same way: `client` is the var name while `Client` is its type
