### ISSUE TITLE
Stack frame highlight is on top of selection highlights

### ISSUE THREAD

**Issue by f-sky** [microsoft/vscode#140763]
Does this issue occur when all extensions are disabled?: Yes/No

The selected words are not highlighted when I customize the stackFrameHightlightBackground in settings.
- VS Code Version:
- 1.63.2
- OS Version:
OS: Darwin x64 20.6.0 or MacOS 11.6.2
Steps to Reproduce:

1. Input "editor.stackFrameHighlightBackground": "#ffffff" in settings.json under "workbench.colorCustomizations".
2. Debug one python script, pause on one line and select the words in this line.
![Kapture 2022-01-15 at 14 15 35](https://user-images.githubusercontent.com/24546823/149611480-251af83b-5739-44e9-b780-d953b5feefb9.gif)

**Comment by roblourens** [comment]
I don't think the editor gives us a way to draw the stackframe highlight decoration "under" the editor selection. I played with it a bit, setting zIndex on the decoration doesn't help, it's always on top of the editor selection.

I think it would make sense to be able to do something like that. I don't know whether that makes sense with how the selection editorPart works.

**Comment by alexdima** [comment]
The selection is always rendered first and all decorations go on top. This is because of our support for rounded selection. The root problem here is that the defined color does not use transparency. It therefore renders on top of everything else. The solution is to use transparency in the defined color e.g. `"editor.stackFrameHighlightBackground": "#ffffff80"`
