### ISSUE TITLE
problems console has warnings/errors of HEAD-file

### ISSUE THREAD

**Issue by SailorMax** [Microsoft/vscode#14084]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T16:21:53.542Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: donjayamanne.githistory-0.1.0, formulahendry.code-runner-0.4.1, slevesque.vscode-hexdump-1.0.1, waderyan.gitblame-1.3.0

Steps to Reproduce:
1. open any css file with warnings/errors in code
2. modify file
3. open git / diff-view
4. open Problems console

Expected: Problems console has errors/warnings of modified file

Actual: Problems console has errors/warnings of modified file + HEAD-file

**Comment by roblourens** [comment]
I see this too, it's showing errors for the original file when the diff is open.

**Comment by sandy081** [comment]
This is as designed. Extensions generate errors/warnings for all resources.

**Comment by SailorMax** [comment]
But this is useless and duplicate information. Why it was so designed?

**Comment by sandy081** [comment]
@SailorMax Agreed. Reason I closed this because There'd been a long discussion on this on coming up with a good strategy for this issue and decided to keep it like it. See #7773. 

But, there is another issue which is similar #16674 where I am kinda re-initiate the discussion. I think, I ld have made it dup of #16674 .
