### ISSUE TITLE
How to extend existing debugger?

### ISSUE THREAD

**Issue by f-sky** [microsoft/vscode#140849]
I want to add some features for the existing Python debugger for vscode. Following docs, I find the class "MockRuntime" along with the comments "When implementing your own debugger extension for VS Code, you probably don't need this
 class because you can rely on some existing debugger or runtime." However, there is no documentation describing how to find an existing debugger or runtime, their names, and the functions I need to implement or override. Please add more descriptions in the documentation or provide some links here. Thanks a lot!

**Comment by weinand** [comment]
@f-sky sorry, but VS Code does not really support extending an existing debugger because its implementation is typically a "black-box" that might even be implemented in a different language than Javascript or Typescript.

The "Mock Debug" extension is an example for implementing a **new** debug extension - it is not an example for extending an existing debug extension. The sentence "...you can rely on some existing debugger or runtime" does not refer to another VS Code debug extension but it means that your new debug extension does not have to implement a full debugger from scratch but that it can leverage an existing debugger like "pdb" for Python or "gdb" for C/C++. Bottom line: you cannot use "Mock Debug" to extend existing debuggers.

However, VS Code provides debug API for intercepting the [Debug Adapter Protocol](https://microsoft.github.io/debug-adapter-protocol/) that is used between VS Code and a Debug Adapter.
See https://stackoverflow.com/questions/56012353/how-to-get-vs-code-debug-data-like-breakpoints-steps-line-code
With that API you can get access to the communication protocol between VS Code and and a Debug Adapter.
