### ISSUE TITLE
Support additional styling in stylesContributions

### ISSUE THREAD

**Issue by octplane** [Microsoft/vscode#14083]
- VSCode Version: all
- OS Version: all

Hello,

I'd like to know if it could be possible to add support for other CSS properties in the styleContributions code. Namely:
- text-transform
- text-decoration

(and why not all the ones mentionned in http://www.w3schools.com/css/css_text.asp , but that might be overkill).

For example, I'd like to have support for capitalization via style in order to develop a syntax style that looks like the PICO-8 UI:

![pico-8-code-300x298](https://cloud.githubusercontent.com/assets/22177/19560911/b06c5466-96d6-11e6-8dd7-7dc4713e989a.png)

(note that in the usual code, all text is actually typed as lowercase and displays as uppercase.)

However the actual idea lies in the idea of supporting a slightly more extended set of css properties that could be customized via styles. This breaks the backward compatibility, though.

I can provide a PR, if required.

https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/themes/electron-browser/stylesContributions.ts#L120

**Comment by roblourens** [comment]
I think you could have to do that with the font at the moment.

**Comment by aeschli** [comment]
What about editing? How would the user get to enter the correct case for a case-sensitive language like JavaScript?

**Comment by aeschli** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.
If you disagree and feel that this issue is crucial: We're happy to listen and to reconsider.
Maybe you want to give it a try yourself and provide the feature through an extension or a PR: We're happy to give advise and get you started.
Thanks for your understanding. Thanks for helping and happy coding!
