### ISSUE TITLE
vscode.open command can't open HTTP URL with hash (#) in it [extension development]

### ISSUE THREAD

**Issue by viktomas-gitlab** [microsoft/vscode#140907]
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.64.0-insider
Commit: 7ae7f9d40b82a0f1a49d8ad180d27e16812ad95e
Date: 2022-01-18T05:25:31.041Z (8 hrs ago)
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin arm64 21.2.0

This issue relates to extension development, not the normal use of VS Code.

Steps to Reproduce:

1. Have a URL with an encoded hash in it (it must be encoded otherwise it would be the start of the Uri fragment)
2. call

    ```js
    vscode.commands.executeCommand(
      'vscode.open',
      vscode.Uri.parse('https://gitlab.com/viktomas/test-project/-/tree/test-%23-hash'),
    );
    ```

3. VS Code tries to open `https://gitlab.com/viktomas/test-project/-/tree/test-%2523-hash` in the browser (it escaped the `%` character from `%23`) (I tried to set both Firefox and Safari as the default browser and the issue happens for both)
4. The same issue happens if the escaped hash is in the `query` part of the Uri

Running `vscode.Uri.parse('https://gitlab.com/viktomas/test-project/-/tree/test-%23-hash').toString()` returns `https://gitlab.com/viktomas/test-project/-/tree/test-%23-hash` **which is correct** so there must be some additional double-escaping in the VS Code opener.

---

From the normal user perspective:

When the hash-encoded URL is somewhere in the text editor and you command-click on it, it works well

https://user-images.githubusercontent.com/78416057/149952902-013ecb11-7f97-4242-a1f1-9ac085bc516e.mp4

**Comment by jrieken** [comment]
maybe https://github.com/microsoft/vscode/issues/85930

**Comment by viktomas-gitlab** [comment]
The strange thing is that the `vscode.open` doesn't escape the `%` for some other escaped characters

e.g.

```js
vscode.commands.executeCommand(
  'vscode.open',
  vscode.Uri.parse('https://gitlab.com/viktomas/test-project/merge_requests/new?merge_request%5Bsource_branch%5D=test-%23-hash'),
);
```

Opens `https://gitlab.com/viktomas/test-project/-/merge_requests/new?merge_request%5Bsource_branch%5D=test-%2523-hash` in the browser. It doesn't escape `%5B` (`[`) and `%5D` (`]`), but it escapes `%23` (`#`). 

The Uri logic (`vscode.Uri.parse().toString()`) doesn't do this double escaping:

```js
vscode.Uri.parse("https://gitlab.com/viktomas/test-project/merge_requests/new?merge_request%5Bsource_branch%5D=test-%23-hash").toString()
'https://gitlab.com/viktomas/test-project/merge_requests/new?merge_request%5Bsource_branch%5D%3Dtest-%23-hash'
```

which makes me think that the VS Code Opener has a special logic to handle/escape `#` character.

**Comment by jrieken** [comment]
The problem is calling `encodeUri` here: https://github.com/microsoft/vscode/blob/9b455176e9a3b7364caeae9f8f466bf2ad0bbb14/src/vs/editor/browser/services/openerService.ts#L228. We stringify the passed `Uri` with minimal encoding and `encodeUri` then encodes the `%` character

**Comment by viktomas-gitlab** [comment]
Thanks so much for looking into this @jrieken 🙏  I'm looking forward to when the change makes it to Insiders 🎉 🚀

**Comment by jrieken** [comment]
Very sorry but the change had to be reverted because it has caused regressions. This is not to say that the fix is bad but some extension rely on the broken behaviour and have adopted to it with workarounds. Those are now broken... This is a tricky situation because the fix is still a good fix. Maybe we need to tackle https://github.com/microsoft/vscode/issues/85930 so that extensions can use the native `URL` object which allows us to establish better handling in those places

**Comment by jrieken** [comment]
Internally, we do support to call the opener service with an `URI` instance or a plan string. Strings are handled correctly and we should see to support string for the open-command

**Comment by jrieken** [comment]
The MSFT auth provider failed with the changes - while we also had a fix for that in hand we decided to revert because there might be an unknown number of other extensions that are going to fail. Back to a safe spot... 

I just did merge #141944 which enables to call `vscode.open` with a string (instead of URI). When using "external links" like http/https we treat the string as-is and no encoding issues should happen
