### ISSUE TITLE
Support optional params in remote authority URLs

### ISSUE THREAD

**Issue by sevillal** [microsoft/vscode#140943]
Azure Machine Learning Remote is implementing a remote resolver but customers have complained about the following.

### Customers issue reported:
Trusted workspace prompt is show on subsequent connections to the same Compute Instance and same folder/workspace.

### Expectation:
Customer sees "Trusted workspace" prompt only the first time it tries to connect to the Compute Instance, after it is approved, subsequent connections to the same Compute Instance in the same folder should not prompt to trust the workspace.

### Issue:
Azure ML Remote authority url format includes some unique ids to track each connection and identify it in telemetry, these values does not affect the **ResolvedAuthority** and are merely to uniquely identify each remote connection. Since those values change on each connection and result on a different URL each time, it seems that vscode couldn't not match it with any previously trusted workspace thus it prompts the user to trust it. Here is the format used:

vscode-remote://amlext+_**{PARAMS_TO_GET_RESOLVED_AUTHORITY}**_+telemetryTrackingId=_**{GUID}**_+sessionId=**_{GUID}_**/home/azureuser/cloudfiles/code

Notes:
**_PARAMS_TO_GET_RESOLVED_AUTHORITY_**: Includes a websocket server endpoint that will be used to reach the VS Code Server on the remote (this part affects the ResolvedAuthority)
**_TELEMETRY_TRACKER_GUID_**: Unique id to track the telemetry of a remote connection
**_SESSION_GUID_**: Unique id to track an user coming from Azure ML studio

### Proposal
We need a way to pass optional params or params that does not affect the **ResolvedAuthority** on a remote url.

Could we achieve this using URL query parameters?
1. URL without query params will identify the workspace. Trusted workspace component uses this to check if a workspace was previously trusted.
2. Query params will hold data that does not affect the ResolvedAuthority.
3. resolve() method in remote resolver receives not only the authority but also the query 

For our use case the format of the remote URL would be:
vscode-remote://amlext+**_{PARAMS_TO_GET_RESOLVED_AUTHORITY}_**/home/azureuser/cloudfiles/code?telemetryTrackingId=**_{GUID}_**&sessionId=**_{GUID}_**

Please let us know your thoughts.

cc: @SiddhanthUnnithan

**Comment by alexdima** [comment]
@sevillal The `vscode-remote` URI needs to go through an [uri transformer](https://github.com/microsoft/vscode/blob/12f9c5fc6d5329bfb0c4402b9fbc6013ed9be0da/src/vs/server/uriTransformer.js#L23). For example, if there is an URI on the UI side `vscode-remote://[authority]/Users/alex/src/file.txt`, on the remote extension host side it is transformed to `file:///Users/alex/src/file.txt` and then when it leaves the remote extension host side it is transformed back.

The uri transformer maps identically the path, query and fragment portions of an URI. We have had numerous problems when we didn't do that. The problems appeared from extensions which were using the query or fragment portions of URIs and if we would remove those or interfere with them, extensions would break. We don't get to know what extensions do with those URI parts. In the meantime, we have added some core features like notebook cells which AFAIK also use these URI parts.

Let's get together and discuss, I think you have a valid need for a unique ID, but it looks like something is missing in some setup steps (for example we usually have a daemon process if state across windows needs to be maintained, or we ask extensions to use `vscode://{extensionId}` URIs and then redirect to `vscode-remote://` as necessary. These kind of unique IDs should not be in the `vscode-remote://` URI, because for example the `vscode-remote://` URI gets serialized to disk in a recent list and they can be reopened by users using that. The workspace trust is just the tip of the iceberg, probably the most visible feature not playing well with these unique IDs.

In any case, for workspace trust specifically there is a `getCanonicalURI` that a resolver can implement, but that would just be a workaround. The `vscode-remote` URI needs to be conceptionally like a `file` URI, i.e. without a unique session ID in it.

**Comment by alexdima** [comment]
Closing since we discussed.

Here is what I mentioned, vscode can also be opened from the command line e.g. `code --folder-uri=vscode-remote://ssh+myserver/path/to/folder`.
