### ISSUE TITLE
ExternalTerminalService tests rely on side effect

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#140901]
* run `./scripts/test.sh`, ✅ all tests pass
* run `./scripts/test.sh --glob "**/ext*.test.js"`
* 👎 tests in `ExternalTerminalService` fails which means the test or feature rely on something happening "by chance", e.g it doesn't seem to load its true dependencies that are needed to pass

**Comment by meganrogge** [comment]
It looks like we're not passing in the ExternalTerminalService with `getDefaultTerminalForPlatforms`

https://github.com/microsoft/vscode/blob/bb7d9597f5def37f629cb8cb498da75c399c8e2f/src/vs/platform/externalTerminal/node/externalTerminalService.ts#L22-L28

but that shouldn't matter because it looks like the tests pass in configuration

https://github.com/microsoft/vscode/blob/ee1655a82ebdfd38bf8792088a6602c69f7bbd94/src/vs/platform/externalTerminal/electron-main/externalTerminalService.test.ts#L104-L122

so that part of the or statement shouldn't be reached

https://github.com/microsoft/vscode/blob/bb7d9597f5def37f629cb8cb498da75c399c8e2f/src/vs/platform/externalTerminal/node/externalTerminalService.ts#L40

**Comment by meganrogge** [comment]
any ideas @Tyriar about which tests might influence or set up what's needed for these to pass when all get run?

**Comment by meganrogge** [comment]
not sure where to find the order they are run in

**Comment by Tyriar** [comment]
@meganrogge let's have a look at this tomorrow
