### ISSUE TITLE
Pre-release to stable upgrade is confusing and has UX issues

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#141103]
While I don't want to rehash prior arguments about this, but there are UX issues and expectation/experience issues with the current model. 

IMO once you are on the "Pre-Release" channel that you should *NEVER* get upgrade to a "Release" version. As automatic switching could easily break user expectations and functionality. For example, if the "Pre-Release" version ships with some experimental features that are ONLY available to the "limited" pre-release users, and then an auto-upgrade happens (and that experimental feature hasn't yet landed) the user will all of a sudden lose access to those features.

Granted, extension devs and use an alternative versioning scheme to ensure pre-release versions are always higher than release ones (using data-style versioning), but I still feel the out of box experience with this could lead to issues.

Additionally, the UX of has a few current issues:
- If you opt-in to the "pre-release" channel of an extension (e.g. GitHub Repositories), and then get auto-upgraded to a release version (because that is latest), the UI completely hides the fact that you are on a pre-release channel.
  - So you can't tell that you will get future pre-release version, nor can you opt-out of future pre-releases
- If the latest version of an extension is a "Release" version, then user's can't opt-in to future pre-release versions (until one becomes the latest available).
  - This also makes pre-release discovery hit or miss depending on your timing

The first issue, should in-theory be pure UX/UI -- to show the user their current "channel" and allow them to opt-out (though without the 2nd issue fixed, they can't opt back in).

For the 2nd issue, we could just allow opt-ins to the "pre-release" channel anytime there is any pre-release version in the extension version history. Although to my original point, I would love to see that opt-in actually roll you back to the latest pre-release version.

I should also mention that I ran into the issues above with the GitHub Repositories extension -- where I thought I was opt-ed in to get pre-releases (and I think I am), but when I went to the extension view to check, all those options were missing. I actually reached out to @joyceerhl about it because I thought maybe there was some bug or the pre-release stuff go pulled or something.

/cc @sandy081 @isidorn @misolori

**Comment by sandy081** [comment]
@eamodio I understand your points, but I would like to mention that this feature is to support pre-release part of SemVer and not separate channels or tags like in npm. Since MP does not support SemVer completely, we have this intermediate workaround to use `--pre-release` flag with `major.minor.patch` version semantics. Once Marketplace supports SemVer extensions can use complete SemVer ranges. Since `pre-release` versions are not stable we do not want to install these automatically. Hence users are given an options to install pre-releases by sticking to our decision that we always install latest compatible version. If there is a release version newer than a pre-release, user shall get the latest release version by default. 

It is up to extension authors how they want to roll out their pre-releases and we are not constraining that. If your pre-release extension is always feature rich than release version, you can have a pre-release version always bigger than the release version. 

Following scenario of yours is totally valid and I extracted this into a separate issue: https://github.com/microsoft/vscode/issues/141282

> If you opt-in to the "pre-release" channel of an extension (e.g. GitHub Repositories), and then get auto-upgraded to a release version (because that is latest), the UI completely hides the fact that you are on a pre-release channel.
So you can't tell that you will get future pre-release version, nor can you opt-out of future pre-releases


About following scenario:

> If the latest version of an extension is a "Release" version, then user's can't opt-in to future pre-release versions (until one becomes the latest available). This also makes pre-release discovery hit or miss depending on your timing

For this purpose, we are showing an indicator (pre-release bookmark) in extension view and **Switch to Pre-Release Version** button in the extension editor. The hover also shows information about pre-release availability.

![image](https://user-images.githubusercontent.com/10746682/150798653-2a4a28ee-49e3-4227-8bb2-21c9b7c02dcc.png)

> For the 2nd issue, we could just allow opt-ins to the "pre-release" channel anytime there is any pre-release version in the extension version history. Although to my original point, I would love to see that opt-in actually roll you back to the latest pre-release version.

What if an extension does not roll out any pre-releases later. This might be true for pure release extensions right?

> I should also mention that I ran into the issues above with the GitHub Repositories extension -- where I thought I was opt-ed in to get pre-releases (and I think I am), but when I went to the extension view to check, all those options were missing. I actually reached out to @joyceerhl about it because I thought maybe there was some bug or the pre-release stuff go pulled or something.

This is same as this issue - https://github.com/microsoft/vscode/issues/141282

**Comment by eamodio** [comment]
@sandy081 thanks for your detailed reply.

> For this purpose, we are showing an indicator (pre-release bookmark) in extension view and Switch to Pre-Release Version button in the extension editor. The hover also shows information about pre-release availability.

I'm not sure I'm understanding this or it's not working how I'd expect. I only see that "bookmark" and _Switch to Pre-Release Version_ button *if* the latest version is a Pre-Release. If not then nothing shows. Which makes logical sense (since there is no Pre-Release available to opt-in to) but makes it a very unreliable experience.

To me this is basically the other side of the same coin (issue) that you split out from this.

**Comment by sandy081** [comment]
> I'm not sure I'm understanding this or it's not working how I'd expect. I only see that "bookmark" and Switch to Pre-Release Version button if the latest version is a Pre-Release. If not then nothing shows. 

That's correct. Showing these indicators if the latest version is not a pre-release does not makes sense to me. Because switching to pre-release action installing the latest release version or lesser pre-release version is more confusing to me.

**Comment by eamodio** [comment]
I agree it makes sense, but it makes it hard to opt-in -- because sometimes you might see the option and other times you might not. And as a user, it won't be apparent as to why you can opt-in for some things and not others.

I think the whole issue stems from the fact that we are straddling the line between a pre-release "channel" and a one-off upgrade to a pre-release version.

Because if it's a "channel", I should be able to opt-in/out at anytime. If it's a one-off upgrade, then it makes sense, but I also wouldn't expect to get auto-upgraded (at least after the next stable).

IMO, the behavior today is more "channel" than one-off, but the UX isn't making that clear enough.

**Comment by misolori** [comment]
IMO, if the user opts into the pre-release then that should only ever be the version the user sees. If the extensions flips between release and pre-release that would be very confusing. This maps to how browser + apps do nightly versions and you don't ever get flipped to a release version, even if they are the same/different versions.

**Comment by eamodio** [comment]
@misolori 💯 but that's not how it works today

**Comment by sandy081** [comment]
@misolori That's true if the package manager (Marketplace) supports multiple channels and in this case, versions of same extension can overlap and cannot be co-related to each other. We are trying to allign what Marketplace is going to have in near future, that is to support SemVer and not something orthogonal. In order to have efficient implementation, Marketplace support is very much necessary. Moreover, this was thoroughly discussed during the design and we agreed upon only supporting SemVer and not channels/tags.

I think if we improve our UX for the confusing scenarios, especially this issue - #141282, we can be in a good shape.

CC @isidorn

**Comment by isidorn** [comment]
Closing this issue and we still have #141282 as follow-up
