### ISSUE TITLE
User-data file watching is broken in shared process

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#141176]
Steps to Reproduce (Running from sources):

1. Open Shared Process window
2. Keep break point in the following line at column - 140
https://github.com/microsoft/vscode/blob/4ee3ed1ff239dd9b51cd07ed8a35e29ca9d441c2/src/vs/platform/configuration/common/configurationModels.ts#L442
3. Open user settings file and do some changes and save the file

🐛 Break point is not hit.

I can confirm that the fsp on main is not propagating changes by keeping the breakpoint here

https://github.com/microsoft/vscode/blob/591c6f9b62911e339de89b30bd15dc4f7f327624/src/vs/platform/userData/common/fileUserDataProvider.ts#L96

Above breakpoint is hit, if you change the user data resources scheme to `file` (comment following line to do this)

https://github.com/microsoft/vscode/blob/f69f6eaddf8a73a904bdec39c5dd3d70213e06dd/src/vs/platform/sharedProcess/node/sharedProcessEnvironmentService.ts#L14

**Comment by sandy081** [comment]
This commit https://github.com/microsoft/vscode/commit/5d6872f1548d0074e998d5bbae26313d4f51061c broke this.

It seems changes are listening from file service in which `DiskFileSystemProviderClient` is not registered.

**Comment by bpasero** [comment]
I have reverted https://github.com/microsoft/vscode/commit/5d6872f1548d0074e998d5bbae26313d4f51061c. I have since moved the spam detection for file events all the way down on the level of the provider, so that you will get spam throttled when you watch via the provider.

Previously the spam protection was done in the file service but that had the negative side effect that we would still be sending tons of file changes event over the wire.
