### ISSUE TITLE
Untitled files are not restored to their previous groups

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#14116]
After https://github.com/Microsoft/vscode/issues/14100, text files are restored to their previous groups and positions but untitled files are not.

**Comment by Tyriar** [comment]
I'm thinking the best way to approach this and #14690 is to keep track of untitled files as part of the restore logic and only respect it if hotExit is enabled. I don't see another nice way of restoring the editors to their correct groups. Thoughts @bpasero?

**Comment by bpasero** [comment]
The [editor tabs model](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/common/editor/editorStacksModel.ts#L620) relies on the `EditorInputFactory` to serialize and restore editor inputs properly between restarts. We should utilise this for hot exit probably. Today there is no factory for untitled inputs but we could make it conditional for when hot exit is enabled or not. Once you do that I think everything should restore nicely in the right groups. 

This is another good reason for moving the logic for restoring the right backup content into the model because this ensures that the backup is loaded once the tab is being made active.

I guess what is missing here is to draw the inactive tab with a dirty indicator, but we discuss this in another issue.

**Comment by Tyriar** [comment]
Pushed a fix for https://github.com/Microsoft/vscode/issues/14330 which restored untitled files on reload. If this issue is resolved that commit can likely be reverted.

**Comment by bpasero** [comment]
This can be fixed once we have https://github.com/Microsoft/vscode/issues/15498

**Comment by Tyriar** [comment]
Test plan https://github.com/Microsoft/vscode/issues/16544
