### ISSUE TITLE
Unable to fold/unfold sections of code in VS code

### ISSUE THREAD

**Issue by abhi910** [microsoft/vscode#141242]
Off late, I am not able to fold/unfold segments of  python code. The icon similar to 'v' does not appear on the left. The strange thing is that I see this on json files. 
There are no specific steps to reproduce this issue. It occurs randomly.

**Comment by tacosontitan** [comment]
Can you provide screenshots?

**Comment by abhi910** [comment]
<img width="168" alt="Screenshot 2022-01-25 at 11 47 20 AM" src="https://user-images.githubusercontent.com/21169892/150921932-1ebd3498-bc8a-4a24-89fd-9c39fa1b6be5.png">

**Comment by abhi910** [comment]
This happens randomly after no specific trigger. How can I collect logs ?

**Comment by abhi910** [comment]
<img width="228" alt="Screenshot 2022-01-25 at 11 51 40 AM" src="https://user-images.githubusercontent.com/21169892/150922190-a7ce0ebb-97f1-4cf2-8c7e-0356d1bc0890.png">

For JSON files, I don't see this issue.

**Comment by Hansander** [comment]
I used to be able to fold comments, but now that seems impossible.  This was a way for me to format large sets of code.  I also tried the #region but still no folding.  I would hate to lose the ability to fold on comments.

![image](https://user-images.githubusercontent.com/29998695/153249532-2aa21265-ab12-49a9-8467-65a9da89d707.png)

**Comment by PieterBranderhorst** [comment]
@abhi910 and @Hansander, are you perhaps using the Pylance vscode extension? I see that it added its own support for folding ranges recently. See the end of [this thread](https://github.com/microsoft/pylance-release/issues/372). If you are using Pylance then I think that's why things have changed. In that case please post about the issue(s) [at the Pylance repository.](https://github.com/microsoft/pylance-release/issues/new/choose).
