### ISSUE TITLE
Double prompted for trust (workspace and terminal)

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#141258]
I created a brand new VM and attached remote-ssh to it, then opened my `~` folder on it. I clicked to trust the folder, then immediately after I was prompted by the terminal to trust the folder again.

Every time I open a new folder thereafter I'm again double prompted for trust.

**Comment by Tyriar** [comment]
@lszomoru @sbatten this is how we use the API, is promise for the original prompt not being shared with successive requests or something?

https://github.com/microsoft/vscode/blob/5eda2ba35cbb380d4b486d26a3d17f5c5883e36e/src/vs/workbench/contrib/terminal/browser/terminalInstance.ts#L1477-L1482

**Comment by lszomoru** [comment]
All callers of `requestWorkspaceTrust()` should be sharing the same promise.
I will try to set up a repro today and see if I can reproduce the problem locally.

**Comment by lszomoru** [comment]
Here is what is happening:
1. The initial workspace trust modal dialog is being displayed
2. Underneath there is another workspace trust dialog displayed due to the `requestWorkspaceTrust()` call 
3. Trusting the workspace will actually resolve the promise and in the background you can see the terminal is initiated

The workspace trust request dialog is not being dismissed. I do have couple of ideas that I will discuss with @sbatten.

**Comment by lszomoru** [comment]
The fix will be available in Friday's Insiders release.
