### ISSUE TITLE
Port forwarding only works with this /usr/sbin/sshd listener 0 of 10-100 startups running

### ISSUE THREAD

**Issue by dinushkaherath** [microsoft/vscode#141284]
ADD ISSUE DESCRIPTION HERE
So I have hausra graphql running on hasura:8080

I cannot access it through my rails server sending requests to it without this running:
/usr/sbin/sshd listener 0 of 10-100 startups

Sometimes it does not startup with my codespaces leaving it with connection refused to the server

Currently even with that running, now my codespaces is stuck loading. (wont even load the extensions)
and the graphql request is stuck in fetch pending...

Version: 1.63.2
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36
Embedder: codespaces

**Comment by alexr00** [comment]
@dinushkaherath can you share a screenshot of where you're stuck loading? Can you also share the console output from the devtools?

**Comment by dinushkaherath** [comment]
@alexr00 
one issue - workspace stuck loading
<img width="1669" alt="1" src="https://user-images.githubusercontent.com/43975628/150816173-4b211e8b-67a4-4e61-b51d-15e5c5651830.png">
<img width="1012" alt="2" src="https://user-images.githubusercontent.com/43975628/150816181-96639de7-6ecc-4734-8bcc-8d6accf364fb.png">
<img width="1112" alt="3" src="https://user-images.githubusercontent.com/43975628/150816187-007f60fc-1d02-4265-a86d-7f79b86ff87b.png">
other issue - main issue cannot send requests to my hasura server
<img width="1613" alt="4" src="https://user-images.githubusercontent.com/43975628/150816942-0b3c0006-bfd8-4041-acd1-4da7b9097b14.png">
<img width="1218" alt="5" src="https://user-images.githubusercontent.com/43975628/150816964-c8322f42-44d9-4f0f-8d93-f0fce9253463.png">
<img width="1040" alt="6" src="https://user-images.githubusercontent.com/43975628/150816971-b9f523aa-84d8-49ee-bf2a-bda1162cbcf5.png">

**Comment by alexr00** [comment]
Thanks @dinushkaherath. Because your forwarded ports are private, you need to provide GitHub authentication in order to access them at the https://dinushkaherath-oak-atlantic-.... url. This is expected and just how private forwarded ports work. A few things you can try:

- You can make your ports public (right-click on the port in the "Ports" view and "Change privacy"). This means that anyone can access your forwarded port, so of course use at your own discretion. This gets rid of the authentication requirement.
- If you're trying to access the port from a service that is running on the same Codespace, you can try using `localhost:8080` instead of the whole https://dinushkaherath-oak-atlantic-.... url in your POST. 

Please let me know if either of those works for you as it will confirm the issue!

I'm not sure about the workspace not loading issue. @cmbrose in case you have an idea.

**Comment by dinushkaherath** [comment]
@alexr00 I have been trying to use localhost:8080, and placing all containers on the same shared network - my postgres container, with no luck as to the localhost usage (maybe this is because it's from a client side javascript post?)
How can I provide github authentication, I really wouldnt want to rewrite all my requests to include it...
Is it possible for any requests from github run services (my rails server) attach the auth token along with it when I'm in the browser?

**Comment by alexr00** [comment]
> (maybe this is because it's from a client side javascript post?)

If it's client side then you are correct: using localhost will not work.

> How can I provide github authentication, I really wouldnt want to rewrite all my requests to include it...
Is it possible for any requests from github run services (my rails server) attach the auth token along with it when I'm in the browser?

@cmbrose might be able to answer this.

**Comment by dinushkaherath** [comment]
Also any way to automatically set a port to public?

**Comment by alexr00** [comment]
There is currently no way to automatically set a port to be public.

**Comment by cmbrose** [comment]
:wave: @dinushkaherath it looks like you are using the codespace in the browser - is it possible to use the vscode extension instead? That will allow PF to run directly on `localhost` of your machine rather than through `githubpreview.dev`. That should allow you to bypass authentication, although it will only work with private ports. If you change the port to public it will go back to the `gitbhubpreview.dev` url and you may run into this again.

**Comment by dinushkaherath** [comment]
Is there a default ENV var like CODESPACES that shows whether its running in the browser or in VSCode?

**Comment by cmbrose** [comment]
I mean are you using the codespace in a browser - chrome/safari/edge/firefox - or are you using it in the desktop vscode application? My recommendation is using the desktop application.

**Comment by dinushkaherath** [comment]
Mainly using it in the browser

**Comment by cmbrose** [comment]
Yeah, so could you try it in desktop? That will use `localhost` as the port forwarding address instead of `githubpreview.dev` which might make this work better.

**Comment by dinushkaherath** [comment]
it works in desktop with localhost. Is there a way I can programmatically distinguish if its running in browser vs in desktop?

**Comment by cmbrose** [comment]
I'm not aware of any way to determine that programmatically. The issue is that it's the same machine which you connect to whether you are in desktop or browser (you could even connect from both at the same time) and so even if there was a method, we would probably run into a lot of confusing scenarios.

That said, I don't think your scenario will work at all in browser right? In that case, what is the benefit of knowing that you are in a browser?

**Comment by dinushkaherath** [comment]
Well currently I have a ENV var https://#{ENV['CODESPACE_NAME']}-8080.githubpreview.dev/ for if CODESPACES true
and put the port to Public so it works in browser, but not desktop (which would be localhost instead)

**Comment by dinushkaherath** [comment]
So it would be nice to see maybe like if I'm running in desktop version I can use localhost

**Comment by alexr00** [comment]
Thanks for replies @cmbrose!

@dinushkaherath how are you setting that env var? Depending on where you're setting it there might be a way to determine browser vs. desktop.

**Comment by dinushkaherath** [comment]
Hmmmm I'm setting it from my Rails App, maybe I could do a javascript check for window url...

**Comment by dinushkaherath** [comment]
Thanks
