### ISSUE TITLE
Panel is not restored

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#141372]
Testing #141357

* fresh workspace open stable code
* move panel left
* move side bar right
* have a 2x2 grid editor layout
* start with latest insiders

=> 🐛  panel is not restored and when showing appears at bottom

**Comment by rchiodo** [comment]
+1. Repros for me too using 1.63 insiders.

**Comment by rchiodo** [comment]
However it does remember if I open in the side panel with latest, then restart.

**Comment by sbatten** [comment]
The issue here was that I added extra prefix to the layout state keys. `workbench.` to `workbench.state.` ... since `state` is redundant in this context, I've opted to go back to the old key. this will mess up insiders state overnight, but I think this is better than messing up a lot of stable users state.
