### ISSUE TITLE
Hot Exit: properly restore dirty editors

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#14131]
Feedback for https://github.com/Microsoft/vscode/commit/b23229f65dd68c594915650e0e2aed722cdaa401

I think you will run quickly into an issue where dirty files will not get restored in the way it works now because a user can decide to start code with a specific file to open or folder and you would not run into the `restoreEditor()` case and not reopen dirty files. 

I agree though that we should try to restore as much of the previous session state as possible to keep the user happy. 

There are two cases:

1.) the user just opens Code without passing in arguments. In that case the restoreEditors() call will restore all files and you are adding the untitled ones to have the complete picture.

2.) the user opens code with a specific file in mind like so: `code.sh ~/Desktop/test-js/ ~/Desktop/test-js/package.json`. In this case we will not `restoreEditors() `. You will still need to massage the `filesToOpen` to include the backup files and you will also need to add the untitled files that contain dirty changes.

**Comment by Tyriar** [comment]
Case 2 actually works just fine, it opens the file in the workspace that is restored. If it is a file with a backup the backup is applied. Using this command in the workspace I've been testing the following new files are added to the restored workspace:

`❯ ./scripts/code.sh ../vscode-wiki/Smoke-Test.md ../vscode-wiki/Submitting-Bugs-and-Suggestions.md`

![image](https://cloud.githubusercontent.com/assets/2193314/19589630/4483a758-9722-11e6-8e93-9a5d2eddcf77.png)

**Comment by bpasero** [comment]
@Tyriar hm, so are you adding the files to open explicitly on the main side?

If I look at https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/electron-browser/workbench.ts#L275 it seems we only restore editors if there are no files to open otherwise.

Note that we explicitly NOT load the editor stacks model if we see that there are files to open or diff (follow the `this.hasFilesToCreateOpenOrDiff` trace):

`this.editorPart = this.instantiationService.createInstance(EditorPart, Identifiers.EDITOR_PART, !this.hasFilesToCreateOpenOrDiff);` in https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/electron-browser/workbench.ts#L405

**Comment by Tyriar** [comment]
The backup restore window open requests are handled before any of the others [here](https://github.com/Microsoft/vscode/blob/bcbc6dcb8f6ad28d4765307a9847cbbbeddd5e18/src/vs/code/electron-main/windows.ts#L653). So I think the open file request goes via [this](https://github.com/Microsoft/vscode/blob/bcbc6dcb8f6ad28d4765307a9847cbbbeddd5e18/src/vs/code/electron-main/windows.ts#L707) which is why it works.

**Comment by bpasero** [comment]
@Tyriar hm, not sure that is working. This code is typically only used when opening files into an existing window. I think your case is that you are the one to bring up that window.

I think the cleanest solution is to send files and untitled files to open (because they contain backups) to the window as part of all the other config data on startup. Thinking more about it I think we need to distinguish files to open from the command line from those that should be restored for backups because there can be 2 cases:
* user just opens code: I expect all files/untitled with backups to open as well as all the other editors I had open restored
* user opens code with a specific path to open: I expect this specific path to open but also all the editors with backups

**Comment by Tyriar** [comment]
@bpasero what makes you think it's not working? Whenever I try it out it works just fine, it also makes sense why it would:

1. Load all backup restore windows
2. Perform regular window launch logic, knowing that window(s) already exist so open file(s) in existing windows where necessary

I actually just removed the workspace files list from `workspace(s).json` in https://github.com/Microsoft/vscode/issues/14064#issuecomment-257116302 because this seems fine and we now rely completely on the regular restore logic restoring the editors and the models themselves handling fetching the backups.

I think this issue is done, please reopen if I'm missing something :smiley:

**Comment by bpasero** [comment]
Sounds good, I will play with it after debt week.
