### ISSUE TITLE
Layout menu appears in wrong location

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#141388]
Testing #141357

With the window split in half:
![Recording 2022-01-25 at 11 44 09](https://user-images.githubusercontent.com/900690/150962308-0072e76e-20dc-4fa1-a641-599540a17872.gif)

**Comment by sbatten** [comment]
This one is pretty weird. I need to revisit next milestone unless I come up with a fix I'm less worried about. The summary is that native menus with dropdowns calculate x and y accounting for the zoom level. In this case, the zoom level doesn't need to apply because the title bar is special cased to not be zoomed like the rest of the window. So, if you have any zoom level, we miscalculate. Unfortunately this knowledge isn't shared down the line, so I have to come up with something to handle it in all cases and I don't want to risk breaking all the other dropdowns.

**Comment by sbatten** [comment]
cc @misolori
