### ISSUE TITLE
New move to side panel behavior - commands feedback

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#141426]
Testing #141356

Some feedback on the new command names:
  - Since the current commands are tailored to move *all* views, would it make sense to make this explicit in the command name? Ex: "Move All Views from Panel To Side Panel"?
  - Should there be commands to move a single view? As far as I can tell, the only way to achieve this right now is though drag'n'drop.

**Comment by sbatten** [comment]
there is a "Move View" command that allows moving views with the keyboard, but this issue reminds me that it is not aware of the new panel. will update.

**Comment by stevencl** [comment]
I think Move Views from Side Panel to Panel is so similar to Move View that it makes me feel like I should see a prompt asking me which view I want to move.  Changing this to Move All Views would be an improvement I think as Lad suggests.  

Another alternative could be to change it to "Move panel to side panel" and "Move side panel to panel" since the command effectively closes the panel/side panel.

**Comment by sbatten** [comment]
@stevencl funny enough that's what the commands were initially but the feedback was
> These commands confuse me very much. For example "Move Panel to Side Panel". Is "Panel" a location or a thing I can move? Is "Side Panel" the same type of thing as "Panel"?

with the suggestion of the current names

**Comment by sbatten** [comment]
Since this item contains more feedback, I haven't closed the issue, but would either of you mind verifying the command `Move Views` works with the side panel views? It's a pretty beefy command that lets you select any moveable view and move it anywhere with the keyboard. It now supports the side panel views

**Comment by stevencl** [comment]
Confirmed in Version: 1.64.0-insider (user setup)
Commit: 4af3e141defad7b6b96aa1e831f4b50f78abbe6d
Date: 2022-01-28T05:15:27.497Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

Maybe the command should be Move Panel Views To Side Panel and vice versa? That way it makes the command more about moving the views rather than moving the panel?
