### ISSUE TITLE
Opening a terminal in an empty restricted window

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#141463]
It's an edge case but worthwhile considering

1) Ensure that all new windows are in restricted mode by default
2) Open a new empty window (no open files at all, no open folder)
3) Use <kbd>Cmd</kbd>+<kbd>`</kbd>
-> prompt for trusting the workspace, but there is nothing there to be trusted

**Comment by sbatten** [comment]
In this case, it definitely gets in the way that we ask about trust, and also doesn't make too much to limit access to the terminal. However, what considerations should be in place for when someone decides to bring in untrusted content into the workspace after the terminal is opened? Does this matter for empty workspaces @Tyriar?

**Comment by Tyriar** [comment]
@sbatten it's only useful for the terminal if the folder is of a potentially foreign origin. I could special case this since it's going to open in the home directory anyway, but should it even be possible to have an empty window in restricted mode? Might need to handle this special case in multiple places if it's not handled by the trust request service?

**Comment by sbatten** [comment]
we have settings to configure the empty window experience... this allows empty windows to bring in untrusted content easily without prompting.

**Comment by Tyriar** [comment]
Ok, let's allow opening the terminal if the active workspace root is undefined then as it's safe in that case.

**Comment by meganrogge** [comment]
Isn't launching a process something that should require trust though?
