### ISSUE TITLE
Duplicate view label

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#141402]
Testing #141357

![image](https://user-images.githubusercontent.com/900690/150970138-d26733f6-d9c8-4939-bd54-ea7a15068d62.png)

In this case could we not show "Debug" instead, since we know the original container?

**Comment by sbatten** [comment]
I misread this issue the first time through. I no longer believe this is a bug but by design. That doesn't mean we can't improve the naming mechanism of containers, but I don't think auto-naming this debug is what we want to do.

The identity of the container you have created has to be automatically determined since it is a custom container (not debug since debug cannot be moved as a unit). therefore if you were to move watch to a panel and then put variables in a separate panel, we currently call them watch and variables, but this suggestion would make duplicate panels called debug. We already have a feature request to allow renaming of containers and I think that is more likely to address this type of issue.
