### ISSUE TITLE
Layout splash is not aware of new capabilities

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#141407]
Testing #141357
![Recording 2022-01-25 at 12 56 00](https://user-images.githubusercontent.com/900690/150972721-1a8da388-d7ea-4f1b-b3c1-4d97c35a53f3.gif)

Would be nice if the layout splashscreen shows the grid as it is. I think today it is entirely disconnected from latest layout developments.

//cc @jrieken

**Comment by sbatten** [comment]
was looking into this and the current behavior ignores the panel I assume to keep things simple since it could be moved all over the place. bringing in the panel and the side panel essentially makes us reimplement quite a bit of the layout code on the rapid render side.

I think removing the side bar from the mix will help ease the jarring nature of the current experience when the panel is in a non-centered alignment.

we could then possibly allow the layout code to handle a phased rendering of the additional elements in the future. thoughts?

**Comment by bpasero** [comment]
I always felt that ideally the grid widget itself would have a method that could return a lightweight representation of its state to be used for the splash. I.e. the splits and box sizes of all grids to be used as simple HTML structure in the splash, including colors.

**Comment by jrieken** [comment]
The bottom panel wasn't a prominent thing when I did the first version of rapid render. By now this has changed, also the new side panel has been added. It feels lame to tackle this issue by removing the sidebar. Yes, there is some real work to be done but it greatly helps with perceived performance. Agreeing with @bpasero that it would be nice to have more support from the underlying services to make this simpler

**Comment by sbatten** [comment]
I don't really agree that the panel was not prominent at the release of rapid render in mid-2018. We had already introduced panel movement by then. But I agree that we should end in a place with a "complete" render and ideally no duplication of grid logic. Looks like the parts splash has direct access to the layout service so it should be possible to leverage the grid widget
