### ISSUE TITLE
Explorer still prompts for undo operation even with explorer.undo set to never

### ISSUE THREAD

**Issue by stevencl** [microsoft/vscode#141557]
Testing #141351
I set explorer.undo to never but still get prompted when I try to undo a file creation action from the explorer.
![Recording 2022-01-26 at 12 44 22](https://user-images.githubusercontent.com/1704059/151165194-6de640d3-f116-47bc-a331-ef8da3e7df9b.gif)

**Comment by JacksonKearl** [comment]
Sorry about that, I provided a faulty description. The real setting is: `"explorer.enableUndo": "disable"`, and it should be a registered setting.

**Comment by stevencl** [comment]
I tried to set enableUndo to disable but I got an error message saying that a boolean was expected. I trued setting it to false and to disable but I still see the prompt.

**Comment by JacksonKearl** [comment]
Ah, this is a good catch, thanks. 

Turns out that once explorer undo is disabled, the undo ends up being handled by the active editor. In your case, that editor was the same resource that the explorer undo would have handled, so the behaviour was the same, despite the explorer not actually participating in the undo... the fix for this is trickier.

Pushing this out as the original issue is mainly for prompting and disabling undo in "unexpected" circumstances, if the editor is open there is at least some amount of expectation.

**Comment by JacksonKearl** [comment]
Closing as-designed because the UNDO isn't handled by explorer, and more importantly this only applies to empty files where the data-loss risk is negligible.
