### ISSUE TITLE
Support Variable debugger with a variable reference without a value

### ISSUE THREAD

**Issue by apupier** [microsoft/vscode#141544]
When a Debugger Variable from a Debug Adapter Server is provided, currently, if the value is not specific, the UI displays an "Invalid variable attributes" message. 
In case, the variable is a structured one with children, this value is not used anyway so we should not have the need to set it.

**Comment by weinand** [comment]
Since the [Debug Adapter Protocol specifies](https://microsoft.github.io/debug-adapter-protocol/specification#Types_Variable) that `value` is a mandatory attribute of a `Variable`, debug adapters are not allowed to omit the `value` attribute. But they can simply return an empty string (`""`) that will result in "nothing" to be shown.

In order to protect against mis-behaving debug adapters, VS Code shows the "Invalid variable attributes" message.
So VS Code does the correct thing. If you want to change the DAP spec in order to make the `value` attribute optional, please file a feature request [here](https://github.com/microsoft/debug-adapter-protocol/issues).
