### ISSUE TITLE
Badge layout on side panel doesn't follow conventions of the editor

### ISSUE THREAD

**Issue by devinvalenciano** [microsoft/vscode#141518]
Testing #141355

Version: 1.64.0-insider (user setup)
Commit: f93c696
Date: 2022-01-25T08:42:41.055Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

Steps to Reproduce:

1. Add multiple items to the side panel
2. You see the situation below - the side panel "tabs" are on the same level as the badges unique to the selected tab.  This UX suggests (to me) that the badges would all affect the same part of the editor, but the one's on the left affect the side panel, and the one's on the right affect the selected item in the side panel.

<img width="148" alt="image" src="https://user-images.githubusercontent.com/1389808/151095182-f9199647-c895-40e4-a00c-c74f4b3652f3.png">

See below how we do it for notebooks - clear distinction between editor-level and notebook-level settings:

<img width="556" alt="image" src="https://user-images.githubusercontent.com/1389808/151095381-0466a482-3c9d-48f0-9e44-0350f2400274.png">

**Comment by sbatten** [comment]
@devinvalenciano not sure how this is different than how the existing panel has operated forever.

**Comment by sbatten** [comment]
while this isn't new assigning to @misolori in case he has any thoughts

**Comment by misolori** [comment]
I would say this isn't far from what the panel shows, only that the panel shows title names as opposed to icons (which I think add to the problem as view icons + action icons are treated nearly the same just positioned differently):

<img width="393" alt="CleanShot 2022-02-03 at 09 56 33@2x" src="https://user-images.githubusercontent.com/35271042/152401025-c3ab846f-eddc-4c5e-bc19-7d06c0316abe.png">

In notebooks, you can disabled the global toolbar and it'll show up in the editor toolbar, so that's not too different:
<img width="604" alt="CleanShot 2022-02-03 at 09 58 46@2x" src="https://user-images.githubusercontent.com/35271042/152401242-d9d3f96b-c074-49c3-a035-5045df7d0e44.png">
