### ISSUE TITLE
Alternative text for panel default location setting

### ISSUE THREAD

**Issue by stevencl** [microsoft/vscode#141552]
Testing #141356

I think the deprecation message for the workbench.panel.defaultLocation could be clearer.

Assuming that there isn't a corresponding setting to set the default location of views and that instead we want to direct users to the commands instead how about something like:

"This setting has been deprecated with the addition of the new side panel. Instead of setting the location for the whole panel, you now use the Move Views commands to set the location of the individual view containers within the panels."

**Comment by theabhayprajapati** [comment]
Hey, I was using shortcut Ctrl + J on my window 11 vscode which, help me in showing the current terminal session and I also used this shortcut for closing the terminal too, but today it's not working, it's showing me this error "This setting has been deprecated with the addition of the new side panel. Instead of setting the location for the panel, you now use the "Move Views" commands to set the location of the individual view containers within the panels."


How to get terminal pannel and close  it's with keyboard shortcut

**Comment by sbatten** [comment]
@theabhayprajapati the error you are seeing comes from these commands,
<img width="491" alt="image" src="https://user-images.githubusercontent.com/6561887/152548423-60df3c72-422b-4ca1-b09d-9357be3ea6d8.png">

please verify ctrl+J is not mapped to one of them

**Comment by theabhayprajapati** [comment]
thank you 😊, for concern and reply, yahh the problem is solved right now.

**Comment by zuzuuu321** [comment]
> thank you 😊, for concern and reply, yahh the problem is solved right now.
How did you solved it?
I moved my terminal to the right side but today out of no where it is giving the same error message as yours.
Please reply.

**Comment by zuzuuu321** [comment]
> thank you 😊, for concern and reply, yahh the problem is solved right now.

How did you solved it?
I moved my terminal to the right side but today out of no where it is giving the same error message as yours.
Please reply.
