### ISSUE TITLE
Invalid Marker Service State issue after compile task

### ISSUE THREAD

**Issue by DeRoquefeuille** [Microsoft/vscode#14158]
- VSCode Version: 1.6.1
- OS Version: Microsoft Windows 10 Pro N, 64bit, anniversary update

Im using VS Code for c++ development. I am compiling with a simple makefile using the visual studio command line tool. 
Since the last update, from time to time when executing my build task, I get the error message "Invalid Marker Service State" and the little spinning bar, indicating that a task is in progress, wont stop spinning. As far as I can tell the build task completes normally and my problem matchers seem to catch all problems. Unfortunately I cant tell what exactly triggers this problem, but it happens quite frequently, about every 15 compilations, which has me restarting VS Code to reset the task in progress indicator.

![taskfile](https://cloud.githubusercontent.com/assets/7150993/19600172/19a7dbda-97a4-11e6-8e98-412fa7007404.png)

![error](https://cloud.githubusercontent.com/assets/7150993/19600183/292df6fc-97a4-11e6-8e50-331f37004d4a.png)

**Comment by hbenl** [comment]
I have the same problem in a Typescript project.
I can reliably trigger it like this:
- set `strictNullChecks` in `tsconfig.json` to `true`
- compile the project
- set `strictNullChecks` in `tsconfig.json` to `false`
- compile the project
The second compilation throws the "Invalid Marker Service State" error and I have to restart vscode in order to compile again.
Note that I get a lot of compiler errors from the first compilation (which is correct, since my project isn't compatible with `strictNullChecks` yet) and none from the second. Maybe the bug is somehow triggered by the disappearance of the compiler errors in the second compilation run.

**Comment by skogsbaer** [comment]
Of which issues is this one a duplicate? I'm having the same problem and would like to find out when it is fixen.

**Comment by jrieken** [comment]
https://github.com/Microsoft/vscode/issues/13548
