### ISSUE TITLE
Hide individual extensions in pack

### ISSUE THREAD

**Issue by j-marcon** [microsoft/vscode#141611]
Some extension packs I commonly install in my VSCode installations have a large number of extensions in them. In the "installed" tab, I can see both the extension pack and each individual extension. It would be very nice to be able to hide individual extensions when they are already part of an installed extension pack.

**Comment by sandy081** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
