### ISSUE TITLE
Error when replacing text quickly

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/vscode#14167]
- VSCode Version: 1.6.1
- OS Version: Windows 10 Enterprise version 1607

Steps to Reproduce:
- Open a new file.
- Write "I like fine wine."
- Open search.
  - Search for "i".
  - Replace with "aye".
  - Leave other options blank.
- Hit enter.
- Open the "foo.txt" section that appears below.
- Click on the first result. (There are 4, one for each "i" in the source text.)
- Hover over the "replace" button that appears.
- Click twice quickly.

Expected: "aye layeke fine wine."; got: "ayeayelike fine wine."
The error does not happen if clicking slowly.

**Comment by roblourens** [comment]
So it did the replace twice on one entry? I can't repro this, clicking very quickly.

**Comment by andy-ms** [comment]
I forgot to mention: Open search in the *left* pane. Meaning, ctrl-shift-f, not just ctrl-f.

**Comment by roblourens** [comment]
Right, I was trying that

**Comment by roblourens** [comment]
Actually @sandy081 I can repro by pressing ctrl+shift+1 quickly. And if I press it several times, I get more 'aye's inserted in the wrong places.

**Comment by sandy081** [comment]
@andy-ms, @roblourens good catch.

**Comment by sandy081** [comment]
Root cause of the problem is that Search results are not getting updated immediately after replace. There is a time delay between replacing and updating model. I am also removing the current search result (that is replaced) immediately before updating the model. This is giving the user a time frame to do replace on a next result which is not updated after replace that is causing this erroneous results.

There are multiple parts to the fix:
- Do not remove the search result that is asked to replace. Model update does that anyway. 
- Trigger the model update immediately
- Disable the replace action on the selected result once it is invoked.

There is also another corner case issue which was seen with this issue: Navigating (keyboard) the results while replacing does not focus the next element (if next match is in the same line). Focus gets lost to root of the Tree. I will fix this as a separate commit in this issue.
