### ISSUE TITLE
First attempted execution of new notebook does nothing

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#141676]
Issue Type: <b>Bug</b>

1. create a new notebook
2. type print('hello') in the first cell and shift+enter to execute

expected: user is prompted for kernel selection (this happens when retrying execution)

actual: a new cell is created and given focus. nothing is executed.

repro's in stable and insiders

Extension version: 2022.1.1001749921
VS Code version: Code - Insiders 1.64.0-insider (45060913204279d4ecfe0575ca69d68211fb3798, 2022-01-26T05:17:50.284Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.59GB (16.04GB free)|
|Process Argv|--crash-reporter-id 1202dc88-403d-4ebc-8393-af3551a8bd5b|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
wslgetstartedc:30421358
vscop804:30404766
vs360cf:30404996
vsclayoutctrc:30405799
azactmsalcf:30409288
pythonvspyt640:30426300
vsbas813:30426126

```

</details>

**Comment by roblourens** [comment]
I can't reproduce this. How did you create the file? Does it still happen in Insiders?

**Comment by greazer** [comment]
1. File->New File... -> Jupyter Notebook.
2. Enter ```print('hello')``` in the first cell
3. Shift-enter to run the cell

**Comment by roblourens** [comment]
Still not seeing it. Maybe I can debug with someone who sees this later

**Comment by greazer** [comment]
Hm... strange. Yeah I can repro consistently. Windows? That's what I'm using.

**Comment by roblourens** [comment]
I figured out how to repro it. I had `workbench.quickOpen.closeOnFocusLost: false`

**Comment by roblourens** [comment]
Has been broken at least since 1.63, probably longer

Basically

- Show kernel picker and focus it
- Insert cell
- Check whether it is safe to focus the new cell by checking whether the editor has focus
- It doesn't, but this code means that the focus tracker hasn't reported the blur yet

https://github.com/microsoft/vscode/blob/4a130c40ed876644ed8af2943809d08221375408/src/vs/base/browser/dom.ts#L974-L985

I have seen this before but still don't really understand the purpose. @rebornix I know you added this `refreshState` stuff, any ideas? If onBlur has to be async, maybe it and `refreshState` can return a promise that lets us wait for the focus state to settle.

**Comment by roblourens** [comment]
Or on the outside, make `updateEditorFocus` async
