### ISSUE TITLE
Workbench fails to connect to extension host

### ISSUE THREAD

**Issue by TwisterMc** [microsoft/vscode#141612]
Issue Type: <b>Bug</b>

I'm having all sorts of issues with Visual Studio Code and I'm unable to find the issue.

1. Git doesn't detect the repository even though a `.git` folder does exist.
2. If I run a search it never completes. It looks like it's trying, but never returns anything. 
3. If I open the Terminal, it closes immediately.
4. If I have an extension that adds something to the status bar, those don't show.

I've tried:

1. Re-installing Visual Studio Code.
2. Using AppCleaner to remove all the Visual Studio Code files it could so I start fresh.
3. Removing the `.vscode` folder from my project.
4. Tried opening different repos.
5. Tried restarting my Mac.
6. Tried running Visual Studio Code  with extensions diabled.
7. Tried putting any settings back to their default values.

Typically the only thing that works is a Mac restart. Then on initial launch it typically works fine, but any launch after that it's back to broken.

In the Developer Tools it says

`ERR Error received from starting extension host (kind: LocalProcess)`

```
ERR Error: listen EADDRINUSE: address already in use /var/folders/2g/wjwbbs397xv7grs6070l2l540000gp/T/com.apple.WorkflowKit.BackgroundShortcutRunner/vscode-ipc-dad0e606-eb7c-41a7-9adb-41aceb20ada6.sock
    at Server.setupListenHandle [as _listen2] (net.js:1301)
    at listenInCluster (net.js:1366)
    at Server.listen (net.js:1463)
    at workbench.desktop.main.js:2984
    at new Promise (<anonymous>)
    at q._tryListenOnPipe (workbench.desktop.main.js:2984)
    at q.start (workbench.desktop.main.js:2984)
    at new es (workbench.desktop.main.js:1557)
    at y._createInstance (workbench.desktop.main.js:574)
    at y.createInstance (workbench.desktop.main.js:574)
    at d (workbench.desktop.main.js:1557)
    at workbench.desktop.main.js:2982
    at Array.forEach (<anonymous>)
    at jl._startExtensionHosts (workbench.desktop.main.js:2982)
    at jl._initialize (workbench.desktop.main.js:2982)
    at workbench.desktop.main.js:2985
```
`ERR undefined`

All errors map to `log.ts:313`

I also see warnings.

`WARNING: IPC handle "/var/folders/2g/wjwbbs397xv7grs6070l2l540000gp/T/com.apple.WorkflowKit.BackgroundShortcutRunner/vscode-ipc-dad0e606-eb7c-41a7-9adb-41aceb20ada6.sock" is longer than 103 chars, try a shorter --user-data-dir` `ipc.net.ts:753 `

`WARN Settings Sync: Accounts are not initialized`
`log.ts:313`

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:37:28.172Z)
OS version: Darwin x64 21.2.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.31GB free)|
|Process Argv|--crash-reporter-id e3482bcd-f302-46d4-afba-cecee3442a64|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392cf:30425750
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30428979
pythonvs932:30410667
wslgetstarted:30426333
vscop804:30404766
vscop453:30404998
vsrem710:30416614
vscop841:30429141
vsbas813:30426126

```

</details>

**Comment by joaomoreno** [comment]
The root cause is this being your extension host IPC handle: `/var/folders/2g/wjwbbs397xv7grs6070l2l540000gp/T/com.apple.WorkflowKit.BackgroundShortcutRunner/vscode-ipc-dad0e606-eb7c-41a7-9adb-41aceb20ada6.sock`.

Two things here:

1. We should not be using [UUIDs here](https://github.com/microsoft/vscode/blob/7b3474abff37d9ebbe11e48ed8aa38bd077bdf2e/src/vs/base/parts/ipc/node/ipc.net.ts#L703), especially on *nix where there's a hardcoded limit on the size of these files. I suggest to come up with a shorter random string generator.
2. The user's TEMP dir appears to be `/var/folders/2g/wjwbbs397xv7grs6070l2l540000gp/T/com.apple.WorkflowKit.BackgroundShortcutRunner`. I wonder why.

**Comment by jrieken** [comment]
> We should not be using UUIDs here, especially on *nix where there's a hardcoded limit on the size of these files. I suggest to come up with a shorter random string generator, as it used to be. cc @jrieken

Well, before it was 21 bytes as hex and a uuid is 16 bytes as hex (plus a few formatting dashes). So, I would say it used to be worst. Also, we made this change because of really bad observed performance of the old solution. 

Overall, the approach of tweaking the length of the random portion seems pretty arbitrary. Not saying it shouldn't be shorter but the overall length needs to be taken into account and we should stop when it's too long.

**Comment by joaomoreno** [comment]
UUID is 36 characters long. 😕

> Overall, the approach of tweaking the length of the random portion seems pretty arbitrary. Not saying it shouldn't be shorter but the overall length needs to be taken into account and we should stop when it's too long.

Correct. But given that we don't know how long the TMP folder is going to be (on some systems it depends on the username... and some people have pretty long usernames), we should do anything we can to minimize the file name. And I don't see us changing the default location from TMP, since that will open up a brand new door of issues. I'm certainly not brave enough to do that. I've been in this fight for years, ever since we had our first IPC implementation. There's only one way to win: minimize the socket file name.

**Comment by jrieken** [comment]
> UUID is 36 characters long. 😕

Yes, and `require('crypto').randomBytes(21).toString('hex').length` is 42 characters long

**Comment by joaomoreno** [comment]
Ah so! Yeah that makes sense. I'm fine with dropping crypto, we know it's slow. But instead of taking the entire UUID, we could just take the first 8 chars and call it enough, or?

**Comment by jrieken** [comment]
Sure, sure. We can use 8 or 12 or 4 characters but it is a band aid because the total length is important. I looks like we already check the overall value but maybe more than console.warn is needed? https://github.com/microsoft/vscode/blob/7b3474abff37d9ebbe11e48ed8aa38bd077bdf2e/src/vs/base/parts/ipc/node/ipc.net.ts#L749

**Comment by joaomoreno** [comment]
Yeah... maybe something more dramatically is called for here. But it needs to strike a good balance since it's still possible to open, save and close files.
