### ISSUE TITLE
input Chinese comment flash when enable semantic highlighting

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#141725]
https://user-images.githubusercontent.com/41773861/150691182-41664249-8c7d-4934-9d76-a1fd04c0e8ef.mov

VSCode info:

```
Version: 1.64.0-insider (Universal)
Commit: 23664355e61f3fb614932a5cb16613b4d987cfb7
Date: 2022-01-21T13:27:12.081Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.2.0
```

**rust-analyzer version**: (eg. output of "Rust Analyzer: Show RA Version" command)

```
rust-analyzer version: baa5cd952 2022-01-23 nightly
```

**rustc version**: (eg. output of `rustc -V`)

```
rustc 1.58.0 (02072b482 2022-01-11)
```

@alexdima ref: https://github.com/rust-analyzer/rust-analyzer/issues/11335

**Comment by tjx666** [comment]
This issue is really annoying, hope to be fixed soon. @alexdima

**Comment by tjx666** [comment]
In today build insoder version, the comment seems to toggle italic and normal when input Chinese.


https://user-images.githubusercontent.com/41773861/154636685-4fc6aa6e-7ce1-4579-b35f-f6a051f51281.mov

**Comment by tjx666** [comment]
@alexdima 
I find that problem still exists when My typing word is head of line.


https://user-images.githubusercontent.com/41773861/155179097-ce05734a-c272-4d04-a394-6b3c905eb199.mov

**Comment by tjx666** [comment]
@alexdima

I find that the words would left-right shake when I inputing Chinese if line prefix with space.

https://user-images.githubusercontent.com/41773861/155385073-3f810b70-a303-45e2-94f2-a75161c7087b.mov

**Comment by alexdima** [comment]
@tjx666 I am now confident that the initial reported problem with flashing, which was caused by us changing the color of the text, has been fixed. I consider this issue to be fixed now.

Regarding your latest recording, I see that there is some "tremor", but unfortunately I am unable to reproduce:

https://user-images.githubusercontent.com/5047891/155564321-80dc92b2-77e7-492f-8b26-10485b84b9b6.mp4


https://user-images.githubusercontent.com/5047891/155564613-3158da38-90bf-4d33-8fd7-600a2cfd9c9a.mp4

**Comment by tjx666** [comment]
@alexdima I need to create another issue?

**Comment by tjx666** [comment]
@alexdima 
Try using this popular font: https://github.com/tonsky/FiraCode. After I unset this font to editor, the "tremor" disappear.

**Comment by alexdima** [comment]
@tjx666 Thank you, I could reproduce with FiraCode and have pushed a fix.
