### ISSUE TITLE
AIX support as Linux

### ISSUE THREAD

**Issue by Aabderahim** [microsoft/vscode#141795]
i have updated one issue if you can help plz.
https://github.com/microsoft/vscode-remote-release/issues/3059 
We need that remote SSH support AIX Operating Systems. I know a lot of client that are using this OS.

**Comment by tanhakabir** [comment]
Sorry unfortunately you can't modify the list of supported OS for the Remote SSH extension and the reason why don't support it yet is most likely because how we install and start the VS Code server doesn't work currently on AIX machines.

That request is in backlog and if I have some time this upcoming iteration I could take a look at it. Sorry!
