### ISSUE TITLE
Webview changes broke `Beside` ViewColumn behavior

### ISSUE THREAD

**Issue by mikestopcontinues** [microsoft/vscode#141876]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.63.2
- OS Version: Darwin x64 21.2.0

Steps to Reproduce:

1. Install the [Git Graph](https://github.com/mhutchie/vscode-git-graph) plugin.
2. Configure the setting `Open New Tab Editor Group: Beside`.
3. Click on a few files in the graph view. The plugin passes this setting directly through to VSCode.

A whole bunch of new panes open instead of one. The issue is described [here](https://github.com/mhutchie/vscode-git-graph/issues/609), along with the owner's explanation. He suspects there's a race condition between the click event handler assigning the "current" editor, and that same click action opening a new editor tab.

![](https://user-images.githubusercontent.com/3448684/151701285-a6bc1ee9-a8b1-42c1-8446-0b0426fb57d0.gif)

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) ?

**Comment by Wosi** [comment]
@mjbvz 
Yes, it does.
Tested with 1.64.0-insider
Commit: a853963

**Comment by mjbvz** [comment]
After dcb4759870d0ef1fc5799d0b67aa18a0da525323,  `beside` should always means beside the active editor group. However as noted, in this specific case the webview doesn't have time to become active on from anyone's point of view before the click handler is fired

I'm not sure this problem is possible to fix since an extension's view of the editor states can always be temporarily out of sync with reality. For example, it's possible that between gitgraph handling the click and VS Code receiving the command, the editor layout shifts around due to some other user/extension action. That also would result in the wrong behavior
 
Instead of us trying to patch this for all webviews, I think a safer fix is for gitgraph to not use `ViewColumn.Beside` and instead treat the `beside` setting as meaning: always open beside the gitgraph view. You should be able to do that by adding 1 to the gitgraph webview's view column
