### ISSUE TITLE
Dissasembly view: inline source does not resolve when using remote extensions

### ISSUE THREAD

**Issue by HampusAdolfsson** [microsoft/vscode#141875]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.64.0-insider
- OS Version: Windows 10.0.19042

Steps to Reproduce:

1. Open a folder with a remote extension (e.g. remote SSH or remote WSL)
2. Start a debug session with a debugger supporting inline disassembly source (e.g. vscode-mock-debug)
3. Open the disassembly view and observe that the inline source is just empty lines:
![bild](https://user-images.githubusercontent.com/15944368/151803526-9888ec98-1abe-42f9-afe6-a89e5949c75b.png)
Also, the `Log (Window)` output shows an error message:
```
[2022-01-31 14:35:08.570] [renderer5] [error] Unable to read file '\mnt\e\repos\VSCode\vscode-mock-debug\sampleWorkspace\readme.md' (Error: Unable to resolve nonexistent file '\mnt\e\repos\VSCode\vscode-mock-debug\sampleWorkspace\readme.md')
```
I'm pretty sure this is a bug in VS Code (and not in mock-debug), since the adapter returns an identical `Source` for the stack frames, and VS Code is able to resolve that `Source`.

**Comment by weinand** [comment]
@HampusAdolfsson great find, thanks for reporting this.

This is fixed now (and will be available in the next Insiders).

<img width="784" alt="CleanShot 2022-02-01 at 11 08 55@2x" src="https://user-images.githubusercontent.com/1898161/151949617-340e690f-ef2f-4b35-a199-8eeb7f801a04.png">


@connor4312 and @roblourens
The issue was a DAP `Source` object used in the response of the `disassemble` request. In order to translate `Source` objects correctly in "remote" scenarios, they have to get "massaged" in the [bottleneck function `convertPaths`](https://github.com/microsoft/vscode/blob/01b9db71c0a22afc28f4db527ce849fa69170ffb/src/vs/workbench/contrib/debug/common/debugUtils.ts#L198-L275). I had forgotten to include `disassemble` in the bottleneck when adding the "disassembly" support to DAP.
Whenever a `Source` type occurs in a new DAP addition, make sure to include it in the `convertPaths` bottleneck.
