### ISSUE TITLE
Broken math formulae on vscode web

### ISSUE THREAD

**Issue by tani** [microsoft/vscode#141863]
Does this issue occur when all extensions are disabled?: Yes, except built-in extension, md-math

- VS Code Version: 1.63.0 
- OS Version: Windows

Steps to Reproduce:

1. Access VSCode Web instance (github.dev, vscode.dev) by a web browser such as google chrome
2. Open Markdown file and write math formulae
3. Open markdown preview

Note:

VSCode Web sets strict Content Security Policy (CSP) by default configuration. CSP prevents loading inline style sheet appended by markdown-math. So, the limitation breaks math formulae in the preview panel.
I suggest two options as follows.

- Set Loose CSP as default (not recommended)
- Render equation without CSS

Absolutely, I do not recommend the first option. Then, I suppose to choose the second option.
KaTeX, however, renders the formula by HTML elements (div and span) with CSS stylesheet for typesettings.
My suggestion is to use the MathJax instead of KaTeX to render math formulae because it can render them as SVG elements. As a Proof of Concept, I created [an extension](https://marketplace.visualstudio.com/items?itemName=taniguchi.mathjax-for-markdown) and [a fork](https://github.com/tani/vscode/tree/mathjax) of this repository. The extension especially works fine in github.dev. Please try it.

Thanks for the great software, I would like to help with the improvement by creating a new pull request,
Please do not hesitate to ask me to create it from [my fork](https://github.com/tani/vscode/tree/mathjax).

**Comment by Lemmingh** [comment]
First,

> CSP prevents loading inline style sheet appended by `markdown-math`.

Are you sure?

Even the default policy allows resources over HTTPS:

<https://github.com/microsoft/vscode/blob/c6e58d126f6b5676242e32b34180b2a595f29b51/extensions/markdown-language-features/src/features/previewContentProvider.ts#L238>

---

Second, I don't know what happened to you, since I see everything is fine.

![Visual Studio Code Web 1.63.2, Microsoft Edge 97.0.1072.76](https://user-images.githubusercontent.com/43396014/151840418-b2905981-2d11-4c9e-a74a-24e09b9330e5.png)

```yaml
Version: 1.63.2
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:36:48.576Z
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36 Edg/97.0.1072.76
```

---

Third, I don't think MathJax will be a better solution. The biggest problem is semantics and behavior.

KaTeX, by default, tries its best to follow TeX and LaTeX. But MathJax deliberately diverges in a number of ways. MathJax may surprise users although it's powerful.

**Comment by tani** [comment]
@Lemmingh Thank you for inspecting my issue in your environment. I can see this problem in chromium without chrome/ vscode extensions in private/ incognito mode. Further, I read a similar issue in https://github.com/asciidoctor/asciidoctor-vscode/pull/473#issuecomment-1013783915 , perhaps, this issue may not be related directly because Markdown is not Asciidoctor obviously.

![wslhost exe 2022_02_01 3_43_30](https://user-images.githubusercontent.com/5019902/151853612-94922db1-3480-41c3-bfcf-3b3f54b0ea95.png)

> Third, I don't think MathJax will be a better solution. The biggest problem is semantics and behavior.
>
> KaTeX, by default, tries its best to follow TeX and LaTeX. But MathJax deliberately diverges in a number of ways. MathJax may surprise users although it's powerful.

I agree with your opinion. We, of course, should take care of the difference between the two renderers.
However, the broken math equation surprises the user than the difference, doesn't it?

The best solution is fixing this issue by KaTeX, but I could not do it and have succeeded with MathJax.

Please try it `npx @vscode/test-web` to launch complete vanilla vscode. Cheers.

**Comment by mjbvz** [comment]
Seems to work for me on vscode.dev:

<img width="1215" alt="Screen Shot 2022-01-31 at 5 31 44 PM" src="https://user-images.githubusercontent.com/12821956/151900179-19762a3e-3880-4877-be79-3277df3307c1.png">

If it's not working for you, please share an example formula that doesn't render properly 

The equations not working when running out of localhost is a browser specific problem. They render fine for me with Chrome, but not in Safari (seemingly because of the https vs http mismatch

**Comment by tani** [comment]
@mjbvz I have just get it same result as yours in vscode.dev. I mean that it works fine.

So, last night, I misunderstood my problem. It is not a problem of KaTeX.

As you said, this is a problem of mismatch of http and https, I think so. This is a problem of browser policy. 

Then, I guess we can solve this mismatch by replace header 'https://exple.com' by just '://example.com'. As you minght know, the browser can use the same protocol, i.e., http(s) used in the current page.

Would you mind to tell me your comment about this  idea. In my mind, this is should be fixed in upstream.

**Comment by mjbvz** [comment]
I believe the error occurs because the VS Code's webview always come from https due to how they are served. As this is only a problem for development and not a problem across all browsers, I don't think it's worth addressing at this time
