### ISSUE TITLE
Many undos + Many redos freezes VS Code

### ISSUE THREAD

**Issue by hoovercj** [Microsoft/vscode#14191]
- VSCode Version: 1.6.1
- OS Version: Win 10

Steps to Reproduce:

1.  Use VS Code for hours
2.  Realize you accidentally deleted something, undo (ctrl+z) a lot to try and find it (probably a few dozen undos)
3.  Redo (ctrl+y) a lot to get back to the present

Expected: Everything is fine
Actual: VSCode stalled and had to be restarted

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by alexandrudima** [comment]
@hoovercj Would be very nice to get a repro for this! :heart:

**Comment by hoovercj** [comment]
Feel free to ignore and/or close it for now. It very well could have been an extension issue. Unfortunately I can only give vscode heavy use for personal projects and I don't know the next chance I'll get to really stress this.

I was trying to "undo" hours worth of work which is really hard to try and fake :-)

I'll give it a try next time I have the chance to dive into my project.
