### ISSUE TITLE
Comments panel redesign

### ISSUE THREAD

**Issue by laurentlb** [microsoft/vscode#142081]
This is a followup to the discussion in #139524. Planned API changes means that more information can be surfaced on the UI (in particular, timestamp and thread status). At the same time, we want to reduce visual complexity; it can already be difficult to navigate through the set of comments and find which ones are relevant.

I'd  like to explore here designs that remove intermediate replies in a discussion thread. Rationale: reading a full discussion in the comments panel is not really feasible (because comment snippets are truncated and lack styling). If someone wants to read the discussion, they should open it. We need to show enough context so that a user can find the thread they are interested in.

Design 1.
![image](https://user-images.githubusercontent.com/485572/152359744-7df89fe6-ce30-4c17-bd3d-9b84609271a2.png)

Here, we show only the first and the last messages in each thread. The first message is useful for the context. The last message helps the user know what is the state of the thread, and if there was a message since they last read it.

We could add "..." somewhere to make it clearer that intermediate messages are not shown.

Design 2.
![image](https://user-images.githubusercontent.com/485572/152360182-22da77bf-47d6-4f06-86a4-6d44409ad0a0.png)

Here, we don't show the first message and we focus on the last update. We give information about hidden messages: how many messages are not shown and who where the authors. This design makes it more obvious that the full thread is not shown.

Other thoughts:
- Being able to hide the resolved threads would be very useful. This would be similar to the filter we already have in the Problems panel (e.g. `Show warnings` can be unchecked).
- It would also help if we had control on which thread is expanded. The API only lets us expand/collapse a thread in the editor view; maybe we could have the same for the Comments panel? This feature is important IMO if we keep a design that lists all intermediate replies.

(mocks designed by @albertelo)
cc @alexr00 and @isidorn

**Comment by alexr00** [comment]
@laurentlb thank you for opening this issue, you have read my mind.  We have been discussing a design similar to design 2. I think we will leave the twistie/expander off of each comment thread though. 

Regarding hiding resolved threads: I want to add a menu contribution point to the comments panel `comments/view/title` which would allow actions to be contributed to the comment panel in this area:
![image](https://user-images.githubusercontent.com/38270282/152365389-4e5886e0-396d-405c-aecb-8615b2dc68d2.png)

**Comment by laurentlb** [comment]
This feature already exists. We have been able to add icons there in our extension using:

```jsonc
      "view/title": [
        {
          "command": "critique.publishComments",
          "group": "navigation",
          "when": "view == workbench.panel.comments && config.critique.enableComments"
        },
        // ...
      ],
```

**Comment by alexr00** [comment]
One less thing to do then!

**Comment by alexr00** [comment]
Work in progress update:

![image](https://user-images.githubusercontent.com/38270282/153409148-b80b0424-ccf4-4b5b-bf2b-a21f4d32572e.png)

Any feedback is welcome!

**Comment by albertelo** [comment]
Thanks! A couple of questions:

- which comment under the main thread? The middle row suggests it's a second reply from a thread of three comments. 
- are threads expandable? There is no chevron, but the first two nodes have a nested comment
- when multiple users have replied to a thread, will their names be displayed?
- To make content easier to parse, would it make sense to make the time stamp and the description smaller? Like how the directory ".github" is displayed?

**Comment by alexr00** [comment]
> which comment is displayed under the main thread? The middle row suggests it's a second reply from a thread of three comments.

It's the most recent comment on the thread.

> are threads expandable? There is no chevron, but the first two nodes have a nested comment

Threads are not expandable. There was a bug that caused the third node to be missing it's comment snippet line.

> To make content easier to parse, would it make sense to make the time stamp and the description smaller? Like how the directory ".github" is displayed?

Here it is with everything but the usernames in the smaller font:

![image](https://user-images.githubusercontent.com/38270282/153433065-1cdfee78-96fe-4bc3-aa87-8b15b1aef619.png)

And here it is with just the timestamps and the comment counts in the smaller font:

![image](https://user-images.githubusercontent.com/38270282/153433265-f07ac5b1-3ea7-4fa0-90ec-5ec54e5c723f.png)

Not sure which I prefer.

**Comment by albertelo** [comment]
I like the idea of the timestamp as supplementary information because the nodes can become complex depending on the comment. A smaller font supports rather than compete for attention. Something along the lines of the second image alexr00 posted aligns with what I was imagining, but I agree it looks a bit odd when the nested node has the username and timestamp in a smaller font. Perhaps the timestamp in a smaller font could work. That said, if this treatment is not used anywhere else besides the file nodes (file name is bigger than the directory), I'd side with consistency. 

I'm happy to keep discussing this proposal: 
![image](https://user-images.githubusercontent.com/26898237/153452320-b260d7d9-2376-41a7-9451-084440f73531.png)
Might we worth exploring how it looks with more usernames. Likely we'll need a treatment for collapsing or limiting how many usernames are displayed. 

One thing we've discussed within the team is that it's not easy to understand that the comment shown is the last one posted in the thread. In one thread we had discussed using "..." I don't have a great solution in mind, I thought about an icon like this one:
![image](https://user-images.githubusercontent.com/26898237/153454902-f47a9e36-88ba-4cf3-a83c-716375712d8a.png)
but that feels too abstract. A tooltip could alleviate this a bit, but has discoverability shortcomings.

**Comment by misolori** [comment]
Did a few design variations on the panel here to (hopefully) make the threads a little more clear. I think showing the preview gets a bit in the way of just parsing the number of threads and some social platforms will try and summarize the number of comments:

<img width="878" alt="CleanShot 2022-02-10 at 11 47 23@2x" src="https://user-images.githubusercontent.com/35271042/153485074-d3ef7693-2e70-4255-b2c7-cb991ed23181.png">

<img width="864" alt="CleanShot 2022-02-10 at 11 47 29@2x" src="https://user-images.githubusercontent.com/35271042/153485088-bc3138d2-dc88-47fe-87bb-f6b733df73d8.png">

<img width="870" alt="CleanShot 2022-02-10 at 11 47 34@2x" src="https://user-images.githubusercontent.com/35271042/153485095-4f813aca-688c-45f2-a549-79a5848d7791.png">

**Comment by laurentlb** [comment]
I'm afraid it will be difficult to distinguish the threads. It's common for a single person to leave a bunch of comments; if all the lines are similar, it can be confusing.

When I see the last comment, I can more easily know the state of a thread and what I need to do: Is there a question? Is there a suggestion to apply? Did someone add a response since my last comment?

**Comment by alexr00** [comment]
> This could also inform filtering options mentioned by @laurentlb in the original post, e.g. showing only threads where the last reply is not from me.

Yes, let's start a new issue for this. It's a good feature request, and we should make sure the UX changes we make here don't prevent us from adding it later, but it should be added separately to facilitate our API process.

**Comment by alexr00** [comment]
Here's where we're at so far. The arrows will instead be the nice "reply" icon from @misolori's mocks instead of the current icon.

![image](https://user-images.githubusercontent.com/38270282/153840581-d2496e94-0584-41c8-95ee-8e0f3260290f.png)

- The comment preview is the original comment in the thread.
- If a comment thread only has one comment then it only gets one line.
- The icon helps distinguish a thread with multiple comments. When we add resolved/unresolved this may no longer be true, but its ok to use different icons in that case.
- We show the original timestamp of the thread and the timestamp of the last reply.

**Comment by albertelo** [comment]
One nit: 
The icons used in this proposal feel ideal for the task: 
![image](https://user-images.githubusercontent.com/26898237/153857567-2bde2412-e9d4-471d-9a9b-6a746260bc69.png)
Are they implemented already? I couldn't find them and the latest image uses the straight arrow. If they're not, perhaps design + implementation is needed?

**Comment by hermannloose** [comment]
> Yes, let's start a new issue for this. It's a good feature request, and we should make sure the UX changes we make here don't prevent us from adding it later, but it should be added separately to facilitate our API process.

I opened #143005.

**Comment by alexr00** [comment]
The arrows will instead be the nice "reply" icon from @misolori's mocks instead of the current icon.

**Comment by laurentlb** [comment]
In the last screenshot, I think it would be useful to add the username of the last comment, e.g.

> 4 comments Last reply from albertelo, 1 hour ago

I often want to know if someone else has responded after me.
Apart from that, I think it looks good!

**Comment by misolori** [comment]
@alexr00 added the new icon as `indent` since we already had a `reply`

**Comment by alexr00** [comment]
Here's what I merged:

![image](https://user-images.githubusercontent.com/38270282/154037851-a6a0fc7e-787e-4a44-90cf-12b2e3fcc9df.png)
