### ISSUE TITLE
Allow to publish extensions that use proposedApi when using pre-release publication mode

### ISSUE THREAD

**Issue by benoitf** [microsoft/vscode#142090]
# Context

## Proposed API
There is a way to allow extensions to use proposed API by using Insiders.
At first there was like a global opt-in for the extension and now it's a per-feature switch with `enabledApiProposals` product.json property that is now mapping dedicated API after https://github.com/microsoft/vscode/issues/131165

But we can't publish extensions (except Microsoft and some partners) on the marketplace that are using proposedApi
https://github.com/microsoft/vscode-vsce/blob/f4a82648f91c0667ec2c23d0250013ed20daeb57/src/publish.ts#L106-L108

## Pre-Release extensions
https://code.visualstudio.com/updates/v1_63#_pre-release-extensions

With November/1.63 release there is now a way to publish prerelease of a given extension.

# Feature wanted

Proposed API goal is to let developers experiment stuff that may or not come in upcoming versions of VSCode into the stable API.
And then developers can provide early feedback.
And pre-release allow to get users testing upcoming feature.

I think it's a perfect match and then I would like to be able to use proposedApi in pre-release builds.

Then, users are aware that some stuff can be broken anytime as they're using a pre-release and not a final version of an extension.

**Comment by jrieken** [comment]
I do understand the desire but this is something we currently have not planned. 

Proposed API is a way for extension authors to give feedback to us. I do see that there is (little) value in gathering that feedback through users of extensions that use proposed API but I don't believe it out-weights the downsides: There is no guarantee that a pre-release extension cannot be popular and widely successful (either because a proposal hasn't changed in a long time or simply because a popular extension goes pre-release for the sake of using a particular proposal). Having a popular extension that uses proposed API is a huge burden on us: proposed API will change and said extension will break. Such breakage is bad and users generally don't differentiate on why something broke - the extension doesn't work usually means that vscode doesn't work (that's like a bad display driver that crashes your OS). Now, the alternative to breakage is coordination on proposed API changes. This is the model that we use for our internal and MSFT extensions and it comes with massive overhead. Coordinating that with an even larger group isn't feasible.

**Comment by gjsjohnmurray** [comment]
A sad consequence of this (from an extension author's perspective) is that "blessed" MSFT extensions can benefit indefinitely from proposed API while other extensions are hamstrung. In some cases proposed APIs that IMO are essential have made absolutely no progress towards finalization for **years**. It is both frustrating and dispiriting.

Maybe the team could set a time limit on proposed APIs, after which they must either be finalized or else removed (and no longer available for "blessed" extensions either).
