### ISSUE TITLE
Resizing terminal inside side panel no longer works

### ISSUE THREAD

**Issue by dwelle** [microsoft/vscode#142176]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:  1.64.0 (user setup)
- OS Version: Windows_NT x64 10.0.19043

Steps to Reproduce:

1. Put terminal into the side panel
2. Execute `workbench.action.terminal.resizePaneLeft` or `workbench.action.terminal.resizePaneRight`
3. Does not work anymore

The commands actually incorrectly resize other non-terminal panels, e.g. the Debug console, if it's currently open at the bottom (not the side panel).

**Comment by carlfriedrich** [comment]
I can confirm this behaviour with v1.65.0-insider on Windows 10.

**Comment by carlfriedrich** [comment]
FYI: I [proposed a general flexible solution](https://github.com/microsoft/vscode/issues/141349#issuecomment-1029952188) to this in #141349.

**Comment by Tyriar** [comment]
FWIW I have wanted to get rid of those terminal commands for a while in favor of the `increase current view size` and `decrease current view size` commands. Do they work as we could consider transitioning the terminal command keybindings over to them instead?

**Comment by dwelle** [comment]
> FWIW I have wanted to get rid of those terminal commands for a while in favor of the `increase current view size` and `decrease current view size` commands. Do they work as we could consider transitioning the terminal command keybindings over to them instead?

Didn't know! They do work indeed. I'm wondering though, going forward are these guaranteed to not change the left-side panel (which would be undesirable to me personally)?

I'll just mention for others that there's also `workbench.action.increaseViewWidth` (and decrease) that will not touch the bottom panel if one is open as well.

**Comment by jsbrain** [comment]
For me personally, I having something like `workbench.action.sidePanel.resizePaneLeft` would be great I guess.

**Comment by carlfriedrich** [comment]
> FWIW I have wanted to get rid of those terminal commands for a while in favor of the `increase current view size` and `decrease current view size` commands. Do they work as we could consider transitioning the terminal command keybindings over to them instead?

Those commands do indeed work. However, they are context-sensitive, which is not exactly the same as `workbench.action.terminal.resizePaneLeft`. The latter always has the same result, no matter where the cursor currently is.

E.g. I have bound `Ctrl`+`Shift`+`🠔` to `workbench.action.terminal.resizePaneLeft` and `Ctrl`+`Shift`+`🠖` to `workbench.action.terminal.resizePaneRight`, so that I can move the border between my editor and my vertical panel, no matter which I find very intuitive. With the context sensitive commands this would not be possible.

Generally speaking: while a context-sensitive command would reduce the overall number commands (which might seem like a good thing), it would definitely slow down peoples workflows, because certain use-cases would require running one or more additional commands for getting the same result (which is not a good thing). That's why I would not prefer a context-sensitive command.

**Comment by carlfriedrich** [comment]
Having said this, I realize that using `when` conditions for my keybindings, I indeed could achieve the same behaviour like before. It's just a bit more configuration, but that's fine. So I'm revoking my previous comment: `increase current view size` and `decrease current view size` can indeed supersede `workbench.action.terminal.resizePaneLeft` and `workbench.action.terminal.resizePaneRight`.

**Comment by Tyriar** [comment]
@sbatten perhaps we should allow setting a view ID with `workbench.action.increaseViewWidth` to allow the terminal commands to be removed? This is a longer term fix though, not as part of the candidate.

**Comment by davidkuda** [comment]
> FWIW I have wanted to get rid of those terminal commands for a while in favor of the `increase current view size` and `decrease current view size` commands. Do they work as we could consider transitioning the terminal command keybindings over to them instead?

`increase current view size` and `decrease current view size` work perfectly for me. I prefer these two now that I know them. That way I can easily resize the panel and also resize the side panel or the active text editor. Perfect, that's what I wanted anyways.
