### ISSUE TITLE
Recommendations regarding audio cues

### ISSUE THREAD

**Issue by sine-w** [microsoft/vscode#142251]
• VS Code Version: 1.64.0
• OS Version: Windows 10 home 21h1

I am happy that the latest vs code has a new function audio cues.
As I am a screen reader user, having audio cues, instead of a spoken message or tooltip, it will not conflict with the speech of screen reader.

Regarding audio cues, I have the following recommendations:
1. adding a preference to configure loudness of audio cues

- like a slide switcher or something we can adjust the sound volume of the cues 

2. adding a preference to control the duration of audio cues

- add a text box or something we can enter the duration of the audio cues, because I find that some of the audio cues are a bit too long
- say we can configure the duration of aduio cues in micro secs.

3. adding a preference to control the type of audio in audio cues
- we can configure which audio to be played for each condition
- we can choose whether it is a sound file, or simply a beep sound 
- if it is a beep sound, we can set the number of times, pitch, etc.

Thanks.

**Comment by isidorn** [comment]
@sine-w thanks a lot for your feedback. We are glad you are happy with the new audio cues feature. We are currently planning to do some improvements this milestone, more details can be found here https://github.com/microsoft/vscode/issues/141635

Let me reply to your feeback
1) Makes sense and we are considering this. We would like to avoid this setting but to leave it to the OS volume control per app. We might add it in the future
2) I would prefer if we polish the audio cues so the length is just right, instead of making this configurable. Which audio cues are too long in your opinion?
3) Similar as a previous I would prefer if we get the sound right instead of allowing any sound to be loaded.

So all of this requests make sense but I would like to hear more user feedback first.

fyi @hediet @gino-scarpino

**Comment by sine-w** [comment]
Thanks for your reply.

Well current I think that the sound for the errors is a bit long in my personal opinion.

If user is allowed to to customize the audio cues based on each condition, say if you have implemented audio cues for Indentation as suggested in #141635 
we can turn off the Indentation audio cue in vs code and stick to the audio cue of nvda screen reader.

**Comment by steverep** [comment]
I am a screen reader user as well and really appreciate the new audio cues.  Of the recommendations listed above, the most important for me would be the ability to select the sound for each cue type.  Trying to meet everyone's personal preference with a single sound for each cue is just never going to happen.  Moreover, it makes it that much harder to change in a newer release.  For example, I already got used to the folding sound, and now it's changed in 1.65 and I hate the new one... 🙉

**Comment by hediet** [comment]
Thanks for the feedback! We iterate quickly on this new feature to gather feedback exactly like this, so we can find a local optimum.

Sorry if you already got used to the audio cue sounds, we will probably continue tweaking them in the following milestones.

**Comment by isidorn** [comment]
Created this issue for the volume control setting https://github.com/microsoft/vscode/issues/144771

**Comment by isidorn** [comment]
@jonic thanks for your comment, I have commented on the other issue.
