### ISSUE TITLE
`settings.json` conflicts when there aren't any changes

### ISSUE THREAD

**Issue by DillonB07** [microsoft/vscode#142342]
Issue Type: <b>Bug</b>

I don't know how to reproduce it.

After leaving VSC open, I get an error saying:
```
Failed to save 'settings.jsons': The content of the file is newer.
Please compare your version with the file contents or overwrite the content of the file with your changes.
```
When comparing, they're both the same.

If I overwrite it, the notification just comes back a few hours later and the `settings.json` file gets opened.

VS Code version: Code 1.64.0 (5554b12acf27056905806867f251c859323ff7e9, 2022-02-03T04:20:17.224Z)
OS version: Darwin x64 19.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5775R CPU @ 3.30GHz (8 x 3300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|16.00GB (0.72GB free)|
|Process Argv|-psn_0_2388551 --crash-reporter-id 133c6f3a-b0f2-4e27-b9c4-5186fbde6fa8|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (62)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
formatter-pug|ale|0.0.1
vscode-sqlite|ale|0.14.0
vscode-django|bat|1.8.0
procfile|ben|1.1.7
django-html|bib|1.3.0
better-toml|bun|0.3.2
npm-intellisense|chr|1.4.0
bootstrap-5-snippets-by-coder-foundry|Cod|1.2.1
flask-snippets|cst|0.1.2
dart-code|Dar|3.34.0
flutter|Dar|3.34.0
pep8-asm|dea|0.0.1
python-environment-manager|don|1.0.3
python-extension-pack|don|1.7.0
xml|Dot|2.5.1
es7-react-js-snippets|dsz|4.1.0
vscode-html-css|ecm|1.11.0
vscode-npm-script|eg2|0.3.24
prettier-vscode|esb|9.2.0
copilot|Git|1.7.4812
remotehub|Git|0.24.0
vscode-pull-request-github|Git|0.36.0
gitpod-desktop|git|0.0.28
vscode-env|Iro|0.1.0
vscode-heroku|iva|1.2.6
vsc-python-indent|Kev|1.14.2
kite|kit|0.147.0
MagicPython|mag|1.1.0
heroku-vscode|man|0.3.0
identical-sublime-monokai-csharp-theme-colorizer|max|1.1.0
replit|mir|0.9.0
vscode-docker|ms-|1.19.0
python|ms-|2022.0.1786462952
vscode-pylance|ms-|2022.2.0
jupyter|ms-|2022.1.1001775990
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-containers|ms-|0.217.1
remote-ssh|ms-|0.70.0
remote-wsl|ms-|0.64.2
vscode-remote-extensionpack|ms-|0.21.0
cpptools|ms-|1.8.2
vsliveshare|ms-|1.0.5330
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
autodocstring|njp|0.5.4
itunes-vscode|Psy|0.16.5
LiveServer|rit|5.7.4
jinjahtml|sam|0.16.0
vscode-spotify|shy|3.2.1
slacksnippets|Sla|0.0.4
vscode-3dviewer|sle|0.2.2
snyk-vulnerability-scanner|sny|1.2.7
tabnine-vscode|Tab|3.5.19
python|tht|0.2.3
simple-rst|tro|1.5.1
vscodeintellicode|Vis|1.2.16
jinja|who|0.0.8
JavaScriptSnippets|xab|1.8.0
pyqt-integration|zho|0.2.0
html-css-class-completion|Zig|1.20.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30425749
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dsc:30433058
pythonvs932:30410667
wslgetstarted:30433507
vscop940:30404999
vsrem710:30416614
vscscmwlcmt:30433761

```

</details>

**Comment by sandy081** [comment]
I suspect this is caused by an extension. Can you please bisect your extensions and see which extension is causing it? Please follow this doc - https://code.visualstudio.com/blogs/2021/02/16/extension-bisect for doing extension bisect.

**Comment by harshavamsi** [comment]
Just to add here, I'm having the same issue and I see it happening when the system theme changes during automatic mode. The theme changes to either dark or light and this causes vscode to add the `workbench.colorTheme` attribute in light mode and then brings the unsaved changes popup.

**Comment by farmerpaul** [comment]
This issue has been affecting me as well as of the last 10 days or so, which also happens to be the age of this reported issue. And indeed, it coincides with when my system switches from light mode to dark mode and vice versa: suddenly I'm asked to confirm changes to `settings.json` (which I haven't touched), and when I click to compare what the changes are, there are none.

**Comment by acaf-github** [comment]
I have exactly the same experience reported buy others - it seems to happen when the system switches from light to dark mode automatically.

**Comment by henrahmagix** [comment]
I had the exact same problem, and somehow I fixed it whilst replicating it for a screen recording to post here.

I didn't want to screen record any sensitive code, so I was opening a new vs code window to show it happening, but it didn't happen. So I created a workspace to see if that's why, and now it's fixed in all my other opened workspaces too!

I had three other workspaces open, and when I was replicating the bug, it was occurring in all three workspaces. I'm on the latest VS Code as of writing.

<details><summary>Version details</summary><p>
```
Version: 1.64.2
Commit: f80445acd5a3dadef24aa209168452a3d97cc326
Date: 2022-02-09T22:00:56.651Z (1 wk ago)
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin arm64 21.3.0
```
</p></details>

<details><summary>Here's what I did (in macOS), hopefully it helps someone!</summary><p>

1. opened a new vs code window
2. saved as a workspace in my home folder
3. opened the file explorer sidebar
4. it was empty because I hadn't added any folders yet
5. clicked "Open Folder"
6. in the file dialog, I created a new folder in my home directory, and chose it
7. vs code popped up to ask "Do you trust the authors of the files in this folder?" even though it was empty
8. I clicked yes
9. then I saved a new workspace (same as step 2) but in the folder I just created
10. hit issue [#122293](https://github.com/microsoft/vscode/issues/122293) where the `Running 'File Create' participants...` dialog shows and the file isn't created yet
11. waited 60s for the file to be created (the `.code-workspace` file from step 9 in the folder from step 6)
12. created a text file in the folder via vs code `File: New File`
13. again waited 60s (again because of issue #122293)
13. opened my settings json
14. opened my macOS General settings window above the vs code window
15. switched theme from Light to Dark
16. 💥 the settings json switched theme and saved without the conflicts popup!

</p></details>

Absolutely no idea why any of that is related, but my issue is gone! I was seeing this issue for the past few days, since I would lock my macbook, then in the evening, macOS Night Shift would turn on, which would cause Dark appearance to be applied. Over the winter, this was occurring during my working hours, so I was seeing VS Code shift automatically to my dark theme (it was great!). So it must've been doing this now whilst the macbook was locked, because it's getting dark later in the evening. I'd unlock in the morning and see this exact issue on all of my open workspaces, with unsaved changes to my settings json, but no discernible differences, presumably because it had already switched back to Light theme in the morning.

Anyway, issue gone, and I'm so thankful! I hope the above is helpful to someone, whether they're another user who gets to fix it on their side too, or a VS Code dev who's able to make a connection and find the affected code. Sorry I can't screen record to replicate it!

**Comment by evanw** [comment]
This is really annoying. I can reproduce this with all extensions disabled and with workspace trust disabled. Repro instructions:

1. Open VSCode on macOS
2. Configure a different light and dark theme (I left `Preferred Dark Color Theme` and `Preferred Light Color Theme` as their default values, which are `Dark+ (default dark)` and `Light+ (default light)`)
3. Open some directory in one window
4. Open some other directory in a different window
5. Change the system appearance in System Preferences back and forth a few times

Unexpected: One of the two windows will show `Failed to save 'settings.json': The content of the file is newer. Please compare your version with the file contents or overwrite the content of the file with your changes`. This is extremely annoying with more than two VSCode windows open (I typically have 10+ for different projects) as all but one window will have the `settings.json` file open and dirty. I then have to dismiss the alert, undo the edit, and close `settings.json` in each window. It means theme switching in VSCode is barely usable.

Here's a screen recording that shows how annoying it is:

https://user-images.githubusercontent.com/406394/154816941-1d87f4e2-f639-4e15-8315-27e8953aec22.mov

**Comment by kevin-he-01** [comment]
This happened to be on Windows 10 as well, though it does not trigger every time I do the theme switch via "Setting -> Personalization -> Colors -> Light/Dark", and only in one workspace.

I guess fewer people are affected on Windows as the system does not provide an option to auto-switch theme when the time of day changes, but the issue is there. I get for macOS it can be annoying with the "Auto" switch theme option.

**Comment by rzhao271** [comment]
I think I saw this issue before, but I'm unable to repro it now, even with Stable. Is anyone here able to confirm whether or not the issue has been fixed on the latest [Insiders](https://code.visualstudio.com/insiders/)?

**Comment by sandy081** [comment]
@rzhao271 I can reproduce it in stable (I am on Mac) Please follow these steps:

- Use fresh user data directory
- Open multiple VS Code windows (around 4)
- Set auto detect color scheme setting to true `"window.autoDetectColorScheme": true`
- Open System Preferences > General and toggle appearance between Light and Dark
- Stable shows conflicts error and Insiders should not

**Comment by rzhao271** [comment]
Ok, it was most likely because I had that setting off, but I got the issue confirmed and verified now 🚀

**Comment by devatrox** [comment]
I have the same issue here on Mac since 2 weeks or so.

**Comment by rzhao271** [comment]
@devatrox are you on the Insiders release? If you're on Stable, a new version with the fix should be out this week.

**Comment by devatrox** [comment]
@rzhao271 Thanks for the info. I'm on stable

**Comment by DillonB07** [comment]
Thanks! I'm using the latest Insiders build and this seems to fixed now!

**Comment by farmerpaul** [comment]
I'll chime in, too. It seems to be mostly fixed for me, but I'm still at times getting my `settings.json` file randomly showing as open, and edited, in my project window when I return to VS Code after leaving my computer asleep for the night. Not as bad as before but seems worth mentioning.
