### ISSUE TITLE
Select all occurences of find match doesn't respect selection scope column

### ISSUE THREAD

**Issue by ShafinKhadem** [microsoft/vscode#142309]
This is an extension of #59961

It's caused by only checking lineNumber in: https://github.com/microsoft/vscode/blob/8d584a55949e1501003e436a91c767359b751bd1/src/vs/editor/contrib/multicursor/browser/multicursor.ts#L633-L644

Steps to reproduce:

1. Have the following text in your editor:
   ```
   abc
   abc
   abc
   abc
   abc
   ```
2. Select from 2nd abc to last a
3. Enable find in selection, possibly by pressing <kbd>Alt</kbd><kbd>l</kbd>
4. Press :arrow_left:. Now the cursor is before 2nd a.
5. Trigger 'Select all occurences of find match'.

Notice that it selects 2nd to 5th abc, instead of 2nd to 4th:

![before](https://user-images.githubusercontent.com/26321479/152671933-12ddd03c-4187-430a-8fce-943938adb14e.gif)

Does this issue occur when all extensions are disabled?: Yes

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:39:46.686Z)
OS version: Linux x64 5.13.0-22-generic snap
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 3 5300U with Radeon Graphics (8 x 2842)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|2, 1, 1|
|Memory (System)|7.12GB (1.21GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id f9ef0483-9e99-46a3-9f8c-1e6a71b29e0e|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
vscorecescf:30384386
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vscop804:30404766
vs360:30404995
vsrem710:30416614
py55gd98:30411514
vscexrecpromp3t1:30407762

```

</details>

**Comment by ArturoDent** [comment]
When you do 

4. Press ⬅️. Now the cursor is before 2nd a.

don't you **lose the selection**?  Then what is the expected result of `Select all occurences of find match`
if there is no selection but the `Find In Selection` option is still selected??  

I think it should really select all 5 occurrences of `abc`.

And very oddly, when I do the `Select all occurences of find match` command (via <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>L</kbd>) it is auto-enabling the `Match Case` and `Match Whole Word` options become enabled.  

And then, since there is no selection, `Select all occurences of find match` does select those last four occurrences of `abc` - as I think it should - the question is why doesn't it select the first `abc`.

It is as if the setting `Editor> Find: Loop` is not respected when there is no selection but the `Find In Selection` option is enabled.  [Of course, there really is a selection, but it is empty.]

**Comment by alexdima** [comment]
@ShafinKhadem The feature #59961 (select all occurences of find match in search scope) only works when the find widget is made visible.

**Comment by ShafinKhadem** [comment]
@alexdima unfortunately the issue still persists even when find widget is visible. Find scope never respects selection column, only line. It seems like it was designed to be that way:
https://github.com/microsoft/vscode/blob/fcd551f9d10b264c9c96eb48600634ebb402f418/src/vs/editor/contrib/find/findModel.ts#L183-L184
