### ISSUE TITLE
KeybindingResolver#_addKeyPress: relax check for conflicting keys

### ISSUE THREAD

**Issue by mbana** [Microsoft/vscode#14232]
It seems at times that conflicting keys are not reported. Stepping through the code and adding some logs, I see the below.

**Command:**
Conflicts with `editor.action.selectHighlights` (https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/find/common/findController.ts#L720).

```javascript
registerCommand(new CoreCommand({
	id: H.TextLowerCase,
	precondition: ContextKeyExpr.and(EditorContextKeys.Writable, EditorContextKeys.HasNonEmptySelection),
	kbOpts: {
		weight: CORE_WEIGHT,
		// kbExpr: EditorContextKeys.TextFocus,
		kbExpr: null,
		primary: KeyMod.CtrlCmd | KeyMod.Shift | KeyCode.KEY_L
	}
}));
```

**findController.ts:**
```javascript
@editorAction
export class SelectHighlightsAction extends AbstractSelectHighlightsAction {
	constructor() {
		super({
			id: 'editor.action.selectHighlights',
			label: nls.localize('selectAllOccurencesOfFindMatch', "Select All Occurences of Find Match"),
			alias: 'Select All Occurences of Find Match',
			precondition: null,
			kbOpts: {
				kbExpr: EditorContextKeys.Focus,
				primary: KeyMod.CtrlCmd | KeyMod.Shift | KeyCode.KEY_L
			}
		});
	}
}
```

**Debugging:**
1. It seems like this, https://github.com/Microsoft/vscode/blob/master/src/vs/platform/keybinding/common/keybindingResolver.ts#L187, condition needs to be relaxed a bit. In the new command above, `kbExpr` is not present so this check fails resulting in no warning.
2. I haven't got to the reason why on a clean build the warning is issued, whilst at other times it isn't.

**Comment by alexandrudima** [comment]
@mbana it depends heavily on the order.

`KeybindingResolver.whenIsEntirelyIncluded` is a trivial SMT solver working with boolean expression containing only `&` so I think it is correct. One of the reasons I'm not a big fan of adding `|` expressions in the `when` rule is due to the very high difficulty in ever implementing that method :).

There are two keybinding items:
* `A (ctrl+shift+L, null, "TextLowerCase")`
* `B (ctrl+shift+L, "focus", "selectHighlights")`

Assume we give the last one the highest priority, sort of like in the default keybindings the last one in the file gets the highest priority.

### If the keybinding items end up being sorted like `[A, B]`
There is a case where `A` can be triggered via `ctrl+shift+L`, that case is `"!focus"`

### If the keybinding items end up being sorted like `[B, A]`
There is no case where `B` can be triggered via `ctrl+shift+L`, because `kbExpr:null` means effectively always (no check).

The load order of scripts is non-deterministic, so except for a topological sort where you are certain modules you depend on load before you, there is no deterministic sorting (alphabetic or what-not) of the scripts we load.

Therefore, internally (not exposed to `keybindings.json`) we have the `weight` field. That is used to sort the keybinding items in a deterministic fashion or at least it tries to. In this case, both keybinding items have the same weight, therefore they will sometimes end up sorted in different ways each time `sort()` executes with a different script load order.

That being said, it is not mandatory that each new command gets a keybinding out of the box, so it is perfectly fine to leave it without a keybinding

**Comment by mbana** [comment]
:)

Nice write-up!
