### ISSUE TITLE
onDidChange does not report anything useful

### ISSUE THREAD

**Issue by Serhioromano** [microsoft/vscode#142313]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.64.0
- OS Version: Win 11

I am creating an extension and I want to use git API. Basically I need to hook to events and find when the branch is changed. Here is my test.

    const gitExtension = extensions.getExtension<GitExtension>("vscode.git")!.exports;
    const git = gitExtension.getAPI(1);

    const gitBaseExtension = extensions.getExtension<GitBaseExtension>("vscode.git-base")!.exports;
    const gitbase = gitExtension.getAPI(1);

    gitbase.onDidChangeState((e) => {
        if (e.toString().toLowerCase() === "initialized") {
            console.log(git.repositories);
            git.onDidChangeState((e) => {
                console.log("state", e);
            });
            git.repositories[0].state.onDidChange((e) => {
                console.log("repo", e);
            });
        }
        console.log("base", e);
    });

Only this works when I change branch

    git.repositories[0].state.onDidChange((e) => {
        console.log("repo", e);
    });

But `e` is always `undefined` and I cannot get what happens either there was a commit, stage or new changed found. Is it a bug or a feature? Possible to get there type of event like I get `e === 'initialized'` on change state?

**Comment by lszomoru** [comment]
At the moment this is by design. The [onDidChange](https://github.com/microsoft/vscode/blob/2f782a35c54a2262893cda88bb2fc3a6e70c2a8e/extensions/git/src/api/api1.ts#L44) event of the `RepositoryState` object is declared as `Event<void>` and it forwards the `onDidRunGitStatus` event of the `Repository` object. This is why the `e` argument is always `undefined`.

If your extension only implements functionality when the branch changes, you will have to listen to the `onDidChange` event and inspect the properties of the `Repository` object to see whether the branch has been changed.
