### ISSUE TITLE
Need error message when tasks.json is missing

### ISSUE THREAD

**Issue by eostermueller** [microsoft/vscode#142415]
**Is your feature request related to a problem? Please describe.**

I spend 40-ish hours trying to get vscode to stop at a breakpoint.
I created an angular 13 app that demonstrates the problem and documented it all here:

https://stackoverflow.com/questions/71011211/vscode-breakpoint-is-not-triggering-in-simple-angular-13-app/71011457#71011457

**Describe the feature you'd like**
Enhance vscode to inform the user when the .vscode/tasks.json file is missing to help others avoid this pain.
If launch.json references non-existent tasks or other info in tasks.json, it would be helpful to have an error message in that case, as well....hopefully this could help someone avoid the 40 hours of pain I went thru.

**Comment by roblourens** [comment]
This isn't an error case, your preLaunchTask is `npm: start` so it's referencing the npm start task in your package.json. I'm guessing that what's missing is the extra `background` configuration in the tasks.json that tells us when the task is done.

We can't show a warning for this because it is a valid use to have preLaunchTask configured this way without a tasks.json
