### ISSUE TITLE
`WorkspaceFolder.raw` is weird

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#142418]
See:

https://github.com/microsoft/vscode/blob/2f17858a38ff9ab34f2013d1dbce06b6e5b34d55/src/vs/platform/workspace/common/workspace.ts#L334-L337

There seems to be 2 competing parameters for what the folder is. 

I found this while trying to untangle dependencies from `workspace` to `workspaces` and had to inline this one.

**Comment by sandy081** [comment]
Its stored data and used proper typings

**Comment by sandy081** [comment]
Ah ok, I did not know about that.

**Comment by sandy081** [comment]
It seems workspace related types shall be defined in workspace file. So moved `raw` types to workspace file to remove cyclic dependencies. Feel free to move all other workspace related types to workspace file.

**Comment by bpasero** [comment]
@sandy081 I still do not understand why a `WorkspaceFolder` has:
* `IWorkspaceFolderData` which has a `uri`, `name` and `index`
* `raw` which has `uri`, `name` and `path`

This sounds like 2 kinds of sources for what a workspace folder is? Why is that?

**Comment by sandy081** [comment]
`IWorkspaceFolderData` is the normalized data computed from `IRawFileWorkspaceFolder | IRawUriWorkspaceFolder`. Please see this:

https://github.com/microsoft/vscode/blob/1d79533ab670d4750bdc594ca2a954d9e761cf7e/src/vs/platform/workspaces/common/workspaces.ts#L197
 
I need raw data (truth) while updating the workspace configuration file, for eg when updating/adding/removing a workspace folder so that the update is not changing any underlying semantics of that specific workspace folder. 

Otherwise, I would have to create another class extending WorkspaceFolder to store this info. I can do it but may not worth.

**Comment by bpasero** [comment]
The only client seems to be this code:

https://github.com/microsoft/vscode/blob/1d79533ab670d4750bdc594ca2a954d9e761cf7e/src/vs/workbench/services/configuration/browser/configurationService.ts#L223-L229

Can it a) move into the `WorkspaceFolder` somehow as a method to keep access to the raw data private or be done with the other data from the workspace?

**Comment by sandy081** [comment]
Not both options are possible. As said the better option would be to have a `_WorkspaceFolder` class that extends `WorkspaceFolder` in ConfigurationService and wrap this information. May I know what's the harm in leaving it there?

**Comment by bpasero** [comment]
The part that imho is debt is around the fact that creating `WorkspaceFolder` asks to pass in:
* `data: IWorkspaceFolderData`
* `raw?: IRawFileWorkspaceFolder | IRawUriWorkspaceFolder`

I would have expected here that we only asks to pass in the `IWorkspaceFolderData` to know what the folder is about. Because if I pass in both things, how does the `WorkspaceFolder` pick its meta data from? Does it use `data` or does it use `raw`?

And similar, when I am using the `WorkspaceFolder`, should I get the meta data from `raw` or not?

If we somehow need to signal that the `WorkspaceFolder` was constructed from a stored representation then maybe that should be a subclass which is then only created from the raw data and not asking to pass in `IWorkspaceFolderData`

**Comment by sandy081** [comment]
`WorkspaceFolder` populate its metadata using `IWorkspaceFolderData` and exposes its raw/source information `IStoredWorkspaceFolder` for those who need it (like workspace editing). I do not see this as a major debt that has to be restructured .

FYI `WorkspaceFolder` cannot be constructed itself from `IStoredWorkspaceFolder` because it needs additional info like Workspace config path. Hence we are computing it outside. Please see  
https://github.com/microsoft/vscode/blob/1d79533ab670d4750bdc594ca2a954d9e761cf7e/src/vs/platform/workspaces/common/workspaces.ts#L197

If you think you are not sure what's `raw` property is, then I would rename it to `source` and probably add a comment instead of doing a refactoring. I am sorry that I would not do more than that.

**Comment by bpasero** [comment]
@sandy081 why do we need access to the raw data to begin with? Is there any property in `raw` that cannot be figured out from the properties of `WorkspaceFolder`? Isn't this typically true:

```ts
workspaceFolder.name === workspaceFolder.raw.name
workspaceFolder.uri.toString() === workspaceFolder.raw.uri
workspaceFolder.uri.path === workspaceFolder.raw.path
```

?

**Comment by sandy081** [comment]
raw paths are not same as the computed uri path, because the raw path can be relative and we also normalize the URIs. Name is also optional and we compute it. Please refer this code


[IStoredWorkspaceFolder](https://github.com/microsoft/vscode/blob/99cfdd57ad919d48c75914de93f570556fe72486/src/vs/platform/workspaces/common/workspaces.ts#L197-L233)

**Comment by bpasero** [comment]
That is something we should document, pushed it:

https://github.com/microsoft/vscode/blob/7141d2a581b9e7573bbc0ea4fb58e8e059a006eb/src/vs/platform/workspace/common/workspace.ts#L385-L392
