### ISSUE TITLE
Change emacs option for "Migrate Keyboard Shortcuts from..."

### ISSUE THREAD

**Issue by jethas-bennettjones** [microsoft/vscode#142654]
Please replace 
https://marketplace.visualstudio.com/items?itemName=hiro-sun.vscode-emacs
with
https://marketplace.visualstudio.com/items?itemName=lfs.vscode-emacs-friendly

As the project by hiro-sun has not been updated since 2016.

**Comment by isidorn** [comment]
@jethas-bennettjones thank you for your feedback. But we can not just replace extensions on the MP. Extension authors have the right to not update their extension.

Now I noticed we have hiro-sun.vscode-emacs as an extension recommendation from VS Code. That one we can replace with `vscode-emacs-friendly`. Is that what you were trying to convey here?

I also see that the `vscode-emacs-friendly` has not been updated since 2019. Can you clarify why you think this is a better extension?

**Comment by isidorn** [comment]
Thanks for the feedback. I think what you are proposing makes sense.
Let's leave this open for another couple of weeks and if nobody objects I will change the recommended extension start of March.

fyi @digitarald since he added some keymap shortcuts in the past and might have an opinion here.

**Comment by isidorn** [comment]
I have updated to use the https://marketplace.visualstudio.com/items?itemName=lfs.vscode-emacs-friendly now

Thank you for your suggestion @jethas-bennettjones
