### ISSUE TITLE
Displaying same formatting options multiple times

### ISSUE THREAD

**Issue by pcarapic-vegait** [microsoft/vscode#142725]
Issue Type: <b>Bug</b>

When clicking on option Format Document With
Then dropdown of all options for formatting is opened

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No
Remote OS version: Linux x64 5.10.16.3-microsoft-standard-WSL2

**Comment by pcarapic-vegait** [comment]
![image](https://user-images.githubusercontent.com/92083419/153412293-b50b29a5-6761-4f29-9a04-07dabbe52587.png)

**Comment by jrieken** [comment]
Looks like eslint registers itself as formatter repeatedly...

**Comment by dbaeumer** [comment]
Yes I do, but with distinct document selectors (basically using the path of the document). This is necessary since I can't decide on the language mode whether ESLint can format something or not. @jrieken is doing this invalid?

I tried to reproduce this by opening n TS files for which I register formatters separately but I couldn't. I only get one ESLint formatter 

<img width="752" alt="capture" src="https://user-images.githubusercontent.com/1931590/153562790-598b86a5-6a07-46b8-913f-fafaff122668.png">


@pcarapic-vegait can you provide me with a GitHUb repository I can clone that demos this?

**Comment by pcarapic-vegait** [comment]
This is a private repo. Also to mention, this error is showing conditionally. To be honest, it is hard to reproduce, but if I get the process, I will write it here.

**Comment by jrieken** [comment]
>  language mode whether ESLint can format something or not. @jrieken is doing this invalid?

Yeah, that's fair. The formatter picker only shows applicable formatters wrt the current file/editor

**Comment by dbaeumer** [comment]
@pcarapic-vegait ping if something is available.
