### ISSUE TITLE
Bring isDirty closer to editor model (onDidChangeTextDocument Api timing issue)

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#14275]
To fix https://github.com/Microsoft/vscode/issues/11339 I had to make ugly changes because the knowledge if a document is dirty or not isn't kept in the editor model but somewhere outside. That makes it very hard to provide a consistent picture of the world.

Use case
1. Enter some text in an editor window

<img width="551" alt="screen shot 2016-09-01 at 12 46 01 am" src="https://cloud.githubusercontent.com/assets/2920178/18144809/c8e231ca-6fdd-11e6-90d9-af9a6274a2b5.png">

**Comment by bpasero** [comment]
@jrieken @alexandrudima if the editor model exposes API for me to tell that it is dirty, I can call it. Not sure if that is the suggested solution here though. 

Simplified, I am basically setting my model to dirty when I receive a model content change event in the editor model and set it back when the file is saved. There are some corner cases to keep in mind, e.g. a file turns non-dirty when you undo it often enough to reach the beginning of editing time. A user can also decide to revert a dirty file, this will replace the contents with the version on disk and mark it non-dirty.

**Comment by jrieken** [comment]
If only model knowledge drives the isDirty-state when it should maybe solely come from there and the workbench layer should just be a consumer of that.

**Comment by jrieken** [comment]
I wonder if `inmemory`-models et al are considered dirty (they cannot be saved) or not?

**Comment by bpasero** [comment]
@jrieken no, the only models in workbench that have a dirty property are editable files (URI scheme `file://`) and untitled (URI scheme `untitled://`). 

So the motivation for this change is to help the extension API to correctly return true for `isDirty()` as soon as a model is changed, right? Today there is a delay until the model knows it is dirty because the changes moves to main and back to extension host.

We would have to be careful when the editor model decides to indicate it is dirty. E.g. it is not always just by changing the content: A file could have changed on disk and I update the content in the opened editor, this should obviously not result in the model showing up as dirty.

**Comment by alexandrudima** [comment]
I don't think it is a layering problem, the `isDirty` makes sense where it is (on the workbench editor model). But the challenge is:
* the editor's model emits change events
* the workbench editor model emits isDirty events
* now, how to get a good picture out of both event emitters...

somehow, the code that syncs stuff to the ext host gets called before the workbench change listener and the order of events sent over to the extension host is:
* 1. accept text document content changed.
* 2. accept text document is dirty.

so when being an extension and writing code inside a listener for document content changed, the document will say it is not dirty.

**Comment by bpasero** [comment]
Imho if we provide API like `isDirty` it should be synchronised on whatever goes on in the main side. That said, the `onDidChangeTextDocument` should only fire when all state on the main side is synchronised to the renderer side including the dirty state.
