### ISSUE TITLE
Two restarts required to install Insiders update

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#142743]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.64.0-insider
- OS Version: Windows 11

Steps to Reproduce:

1. Click 'Restart to Update' in VS Code Insiders
2. VS Code Insiders closes and reopens
3. :bug: click on Help menu, see that VS Code is still 'Downloading update' and 'Installing update'. Then I get to 'Restart to update' again

![image](https://user-images.githubusercontent.com/30305945/153449643-a7dbcfc5-0cf6-4a2c-85e8-a944bc7a14f7.png)

(@joaomoreno the working areas document says you own install/update--please accept my apologies if I got the assignment wrong)

**Comment by joaomoreno** [comment]
This happens if a second update becomes available after you already have a notification for a first update. It's a known long standing issue that we decide to to address due to its challenges. Whent he notification shows up for your first update, it is already partially applied, so giving it up is really not an option. So, we force you to update to that. Then, you'll get the notification for the second one. 😢
