### ISSUE TITLE
Github Repositories: Allow me to stage all changes in a folder

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#142877]
In the following scenario I'd like to have a simple way to stage all changes in folder A:

1) have a workspace with folders A and B
2) in folder A make changes in many files
3) in folder B make one change
4) in the SCM view, choose the directory presentation
-> allow me to select A and stage all changes below

**Comment by kieferrm** [comment]
Just realized that I was in GitHub repos and not local. Locally this works as expected.

**Comment by joyceerhl** [comment]
This is mostly low hanging fruit, since we recently already added support for multiple selection, RemoteHub now only needs to contribute the stage/unstage/discard actions to the `scm/resourceFolder/context` menu in package.json: https://code.visualstudio.com/api/extension-guides/scm-provider#menus.

Though in desktop, the SCM tree presentation has these very nice 'Contains emphasized items' badges (check out the dots on the resource folder list items in the RHS of the screenshot below). Not sure why they are not appearing for RemoteHub.

----------------------------------------

Separately, while testing this I noticed that RemoteHub contributes extra inline commands inconsistently from desktop git:
![image](https://user-images.githubusercontent.com/30305945/153691672-4743a00a-9e43-4ed8-a9fb-2782ae95f935.png)

Just to document the differences:
- In desktop the Changes and Staged Changes resource groups have an option to Stash Changes or Stash All Changes. RemoteHub doesn't support stashing.
- RemoteHub contributes an extra Discard Changes command to the staged resource state and group menus. I'm a bit worried that the icon is too similar to stash changes and is in the same position that the stash button is in desktop. Will users accidentally discard changes when they expect to stash?
- There's no + option in RemoteHub for the Merge Conflicts resource group, and there's no discard option in desktop for the Merge Changes resource group
- RemoteHub's + means 'Keep Changes' in the Merge Conflicts resource group. But in desktop, + means 'Stage Changes'. 'Keep Changes' also doesn't do anything in the new merge conflict flow, tracking that in https://github.com/microsoft/vscode-remote-repositories-github/issues/125

**Comment by lszomoru** [comment]
> In desktop the Changes and Staged Changes resource groups have an option to *Stash Changes* or *Stash All Changes*. RemoteHub doesn't support *stashing*.

Did you mean "In desktop the Changes and Staged Changes resource groups have an option to *Staging Changes* or *Stage All Changes*. RemoteHub doesn't support *staging*."

**Comment by joyceerhl** [comment]
@lszomoru no, RemoteHub doesn't support stashing. RemoteHub _does_ support a simplified staging experience. We don't have support for staging files in the merge conflict resource group, which is tracked in https://github.com/microsoft/vscode-remote-repositories-github/issues/125
