### ISSUE TITLE
CSP violations in Firefox for VS Code Web

### ISSUE THREAD

**Issue by filiptronicek** [microsoft/vscode#142817]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.65.0-insiders
- OS Version: macOS 12.1

Prerequisites:
1. Firefox (Chrome has a less strict [CSP](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP))
2. VS Code Insiders (stable does not apply)

Steps to Reproduce:
1. Open any version of VS Code web (github.dev, vscode.dev, gitpod.io, Codespaces)
2. Open a webview (for example the simple browser: <kbd>F1</kbd>, then `Simple Browser: Show`)
3. Observe the resources fail to load because of a CSP added in https://github.com/microsoft/vscode/commit/db79f4c.

**Comment by yuyichao** [comment]
I was just testing my own extension today and observed the same.

**Comment by mjbvz** [comment]
This will probably effect stable too. We added this CSP to harden the security of webviews so we do not want to revert the fix for everyone (and for what I see with this bug, I don't think simply relaxing the CSP is viable)

Ultimately I think this is a FF bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1754872 Unfortunately though I don't see an easy way to work around it short of removing the CSP, although I'll keep testing and am open to suggestion

I'll push an update that should hit insiders early next week that reverts this change just for Firefox users. The is unfortunate but I think acceptable since the fix was to harden webviews instead of fixing a specific exploit

**Comment by mjbvz** [comment]
Actual fixing commit 0d43a2f5a36a6a51759c664ed731dd1a624ae59d (VS Code somehow generated an empty commit on my first attempt)
