### ISSUE TITLE
Allow debug extensions to show diagnostic information in the breakpoints view

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#142870]
js-debug has a breakpoint helper to diagnose issues. It's there and there's some heuristics for when we show a notification, but notifications are disruptive, thus the heuristics are conservative, and thus not many people know about the tool. Something that could be helpful is a contribution point that would show markdown text below the breakpoints in the **BREAKPOINTS** view. js-debug could embed a command link there to open the diagnostic tool, and use a `when` clause to show it at appropriate times.

**Comment by rebornix** [comment]
👍 

I was bugging @connor4312 for unbound breakpoints in a project which has a wrong webpack output config. Due to the misconfig, the source maps are wrong. It would be helpful the unbound breakpoint has some tooltip/hover as suggested above and send to me a diagnostic/troubleshooting view.

**Comment by roblourens** [comment]
I think a link in the breakpoint hover message would be more discoverable

**Comment by rebornix** [comment]
The hover message of breakpoint is markdown, we can double check if it's `command` enabled.

**Comment by roblourens** [comment]
Is it ok to just allow command links in the markdown hover? I think that's discoverable, I hardly ever look at the breakpoints view in the debug pane.

**Comment by weinand** [comment]
The initial comment proposed to "show markdown text below the breakpoints in the BREAKPOINTS view" which seems to be discoverable.

Having the additional information in the breakpoint hover makes sense too, but that approach is not very discoverable.
Are users really hovering over unbound (=grey) breakpoints to read their hover message?
If we go this route we should use a visual cue (e.g. a small 'i' in one corner of the grey breakpount) to make users aware of the additional info.

**Comment by weinand** [comment]
I'm not saying that we should show the additional information in the breakpoints view only. I'd like the additional info in the breakpoint hover.
 
My point was that most VS Code debugger users won't hover over grey breakpoints in the gutter because they already know that it means "unbound" and they do not expect to find more information there. This is different to problem icons where only the hover reveals the real info.  

An 'i' badge on the breakpoint icon could help here.

**Comment by roblourens** [comment]
If we want info in the breakpoint hover, we should add a flag to Breakpoint in DAP to indicate whether the message is markdown. Can look at `MarkdownString` in vscode.d.ts

<img width="252" alt="image" src="https://user-images.githubusercontent.com/323878/157998040-f86ccf59-ea0c-402b-944e-66dec2b60d93.png">

The message also shows up in a native tooltip in the breakpoints view, so I'd want to switch to the custom hover for that tree, I guess.

**Comment by roblourens** [comment]
Here's a mockup of some text in the breakpoints view.

<img width="301" alt="image" src="https://user-images.githubusercontent.com/323878/157999310-25ad0a3a-53d4-4c8e-b907-3a5f20c6d56d.png">

I think this would have to be a new contribution point, with js-debug contributing a static message and turning it on and off with a context key. It doesn't fit into `viewsWelcome`. It doesn't make sense to do this as a one-off just for the breakpoint view, so does anyone know of an API or API proposal that is similar to this?

**Comment by weinand** [comment]
some questions/comments:
- @connor4312 do you envision the "diagnostic information" in the future become specific for individual breakpoints ("fix this breakpoint") or will it continue to be just a link that points to a single web page or tool? The answer to this question determines whether we should focus on showing "diagnostic information" per breakpoint or for the breakpoints view as a whole.
- @roblourens I assume that the message is shown in the breakpoints view when a debug session starts and if at least one breakpoint can not be validated. And the message will disappear when the sessions end. This will result in flicker because all the breakpoint options ("Caught Exceptions" etc.) and the list of breakpoints will shift down/up. If we would address issue [#126608](https://github.com/microsoft/vscode/issues/126608), then even more flicker will occur when switching between debug sessions. 
- @roblourens Showing at the top of the breakpoints view has the (minor) problem that the message is shown above the breakpoint options but it applies to breakpoints listed below the breakpoint options. This might be confusing.


BTW, here is the [original discussion](https://github.com/microsoft/vscode/issues/57590) for "Improving discoverability of js-debug diagnostic tool" and the [corresponding js-debug feature](https://github.com/microsoft/vscode-js-debug/issues/260) "diagnostic tool".

**Comment by connor4312** [comment]
> do you envision the "diagnostic information" in the future become specific for individual breakpoints ("fix this breakpoint") or will it continue to be just a link that points to a single web page or tool? The answer to this question determines whether we should focus on showing "diagnostic information" per breakpoint or for the breakpoints view as a whole.

The latter.

Re previous discussion: I also have never intentionally hovered over an unbound breakpoint, but maybe that's just me. I was invisioning text in the view like what Rob has in his screenshots.

> I assume that the message is shown in the breakpoints view when a debug session starts and if at least one breakpoint can not be validated. And the message will disappear when the sessions end. This will result in flicker because all the breakpoint options ("Caught Exceptions" etc.) and the list of breakpoints will shift down/up. If we would address issue https://github.com/microsoft/vscode/issues/126608, then even more flicker will occur when switching between debug sessions.

I think this should be a package.json contribution with visibility driven by a `when` clause. That would avoid flicker and would let debuggers do their best to show the text only when they 'know' there's something wrong.

**Comment by roblourens** [comment]
Thanks for pointing out that other issue. 

A dynamic `showMessage` API feels better to me than an entire contribution point, if it doesn't generalize more. Maybe on `DebugSession`. Or would it make any sense to have this in DAP? There could be a `message` on the `SetBreakpointsResponse`.

**Comment by connor4312** [comment]
Option 1 is actually _okay_ for js-debug. I would just show the same message for every breakpoint, though, inviting users to use the diagnostic tool. While I can try to diagnose why a single breakpoint isn't working, doing so at runtime when the breakpoint is initially set is expensive and I would not do so without the second level action of opening the tool. However, the message could not be interpreted as command-link-capable markdown, so this would not be a particularly good experience.

I think an API works for this.

**Comment by connor4312** [comment]
The common way for DA's to communicate is to use a custom DAP call and then `onDidReceiveDebugSessionCustomEvent` in the EH.

going on a debug session makes the most sense to me. Probably one message per session.

**Comment by roblourens** [comment]
And @connor4312 said that we should make it clear that only the extension that owns the DebugSession should use this API. I won't try to restrict any other extension from calling it and possibly wiping out the message that the DA extension set, but that would basically be misuse of the API, any API can be misused.

**Comment by roblourens** [comment]
Another suggestion from Kai:

Instead of showing the message outright, we could show some icon indicator like a lightbulb, or warning icon like the Terminal uses. When you hover or click it, we show a box with the message. This wouldn't take up vertical space, so you wouldn't have any resize flashing from the message appearing/hiding or switching DebugSessions like mentioned above. And in case we did want to enable showing multiple messages, this would be a nicer format for that. 

I was wondering how much flickering there might be. When will this message be shown? Anytime there is an unbound breakpoint? If I set a breakpoint and press F5, will it be shown until the sourcemaps are loaded and the breakpoint is bound?

**Comment by weinand** [comment]
I very much like Kai's suggestion because it would result in a more stable UI.
And it would draw the attention without being annoying (and as consequence there would be no need to have a setting to turn off the information message).

**Comment by roblourens** [comment]
A place where we have a custom icon in a viewpane header is for extensions:
![image](https://user-images.githubusercontent.com/323878/161883336-356768de-aad6-4ec4-8a39-1b25f1dcddbc.png)

I can add a hover icon in the same place, and it looks like this
![Recording 2022-04-05 at 19 24 37](https://user-images.githubusercontent.com/323878/161883304-6f58e3c3-dd97-4f4c-8ee0-88bc02e1d4bf.gif)

I think this looks ok, any thoughts?

I talked with @sbatten about doing this today, we decided to try to fit something in the body of the viewpane rather than customizing the header. I tried a floating icon that would overlap the breakpoints list, but I just don't think that is going to look good, and it might block a button or detail on a breakpoint row. And anything else in the view body is going to change the height, which we don't want to do.

**Comment by gjsjohnmurray** [comment]
> think this looks ok, any thoughts?

I like how it looks.

**Comment by weinand** [comment]
I like this too!
and if we want to make this stand out a bit more, we could append it to the header's label. IMO this makes sense because the icon is always visible like the label, and not only on hover.

**Comment by connor4312** [comment]
Looks great!

**Comment by roblourens** [comment]
We will try using a static message declared in the `debugger` contribution. Example:

```
"uiMessages": {
  "unverifiedBreakpoints": "There was a problem configuring your breakpoints. Click [here](command:js-debug.showTroubleshootingView) to troubleshoot your launch configuration."
}
```

In this case, vscode is in control of when and where to show this message.

**Comment by roblourens** [comment]
Code for the basic feature is in main. More code to add this message to the breakpoint hover, and to filter breakpoints by the debugger's supported language, is in a pending PR. Since the PR in js-debug will be shipped in june, and this isn't actually exposed anywhere for May, I will move this to June for testing.
