### ISSUE TITLE
No update of environment variables in restored terminals.

### ISSUE THREAD

**Issue by entlicher** [microsoft/vscode#142826]
Does this issue occur when all extensions are disabled?: Yes (Only one extension that reproduces this issue is active)

- VS Code Version: 1.65.0-insider
- OS Version: 
Version: 1.65.0-insider
Commit: bb221a61d29deabd99ee9431736d04f2175cb596
Date: 2022-02-11T05:18:07.499Z
Electron: 16.0.8
Chromium: 96.0.4664.110
Node.js: 16.9.1
V8: 9.6.180.21-electron.0
OS: Linux x64 5.11.0-49-generic

Steps to Reproduce:

1. Have a simple extension that changes `context.environmentVariableCollection`, where `context` is `vscode.ExtensionContext`.
2. Open a terminal, a triangle that allows to relaunch the terminal is correctly displayed on the change of `environmentVariableCollection`.
3. Close VSCode and launch it again.
4. The terminal is restored with "Session contents restored from ..." message.
5. No triangle that allows to relaunch the terminal is ever displayed for this restored terminal when the `environmentVariableCollection` changes.
6. Open a new terminal
7. When the `environmentVariableCollection` changes, the relaunch triangle is displayed for the newly opened terminals only. I do not see a way how to reload environment variables in the restored terminals.
8. Screenshot that illustrates the issue:
![image](https://user-images.githubusercontent.com/5479271/153575331-c161eef8-b03c-464d-b42f-929e5329cd91.png)

**Comment by mbacarella** [comment]
Restoring environment variables is important for switched and sandboxed build-and-tool environments, including but not limited to OCaml.

**Comment by Tyriar** [comment]
I'm aware of some issue here where the environment variable mechanism doesn't kick in fully for reconnected/revived terminals. I don't think the problem was tracked anywhere

**Comment by seppestas** [comment]
I'm also seeing this issue in Windows 10 with the cmd, powershell and MinGW shells. It seems like any terminal started before the extensions are loaded do not receive the updates.

Reloading the window can be used instead of step 3 in the original issue description.

On a related note, the message on the environment being out of date is only updated on the warning icon of the terminal.

![image](https://user-images.githubusercontent.com/1408377/158255581-e55b969d-a046-45bf-a102-ed11cfe83c6f.png)

It is not updated in the message that shows when hovering over the warning icon next to the terminal tabs:

![image](https://user-images.githubusercontent.com/1408377/158255829-cf388625-8008-49d6-9c5c-a41ef6907f88.png)

Also, changing the environment after starting a new terminal causes the new terminal to crash if no text was sent to the new terminal. This also causes the warning not show on any terminal.

This + #143512 makes the whole environmentVariableCollection feature quite flaky, borderline unusable.

Version: 1.65.1 (system setup)
Commit: 8908a9ca0f221f36507231afb39d2d8d1e182702
Date: 2022-03-08T02:06:27.846Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19042
