### ISSUE TITLE
SCM input doesn't wrap lines anymore

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#142844]
* todays insiders
* type a long commit message
* the message doesn't wrap but horizontal scrolling happens

<img width="441" alt="Screen Shot 2022-02-11 at 14 59 56" src="https://user-images.githubusercontent.com/1794099/153604729-2ff97b05-ea00-4ed7-86a9-0cdf8d8b824c.png">

**Comment by gjsjohnmurray** [comment]
Similar report in #142440 with 1.64 but a restart fixed it for that user.

**Comment by lszomoru** [comment]
I am unable to repro this on Mac. @jrieken, could you please ping me if you still have a repro so that I can take a look?

**Comment by jrieken** [comment]
Looks like view-lines is growing as I type

<img width="1187" alt="Screen Shot 2022-02-23 at 18 28 05" src="https://user-images.githubusercontent.com/1794099/155373861-3c4b39f3-bc8a-4264-8e57-156a7339e0ec.png">


---

Debugging into this editor instance shows that word wrap (`118`) is still `on`

<img width="734" alt="Screen Shot 2022-02-23 at 18 29 36" src="https://user-images.githubusercontent.com/1794099/155373991-66dacaae-d37a-49a9-834b-bf9ba8c20f39.png">

**Comment by blakek** [comment]
Noting I had the same issue, but had `"editor.accessibilitySupport": "off"`. I don't remember changing that, so I wonder if it was set from a prompt 🤔. About a month ago, I remember toggling some accessibility features in macOS and seeing some notifications in vscode about this.

Anyway, I resolved the issue as [mentioned above](https://github.com/microsoft/vscode/issues/142844#issuecomment-1049123931) by setting the value for `editor.accessibilitySupport` to `auto` and did a **Reload Window** to resolve this issue. `off` wasn't an issue since changing back to `off` retained the expected wrapping behavior.

Thought it was worth noting here because it seems something else may also cause the unexpected behavior, but that setting alone fixes the issue (with a reload).

**Comment by blakek** [comment]
I found why `"editor.accessibilitySupport": "off"` still showed the problem for me.

Whenever some accessibility settings are enabled in macOS, SCM doesn't wrap lines regardless of the `editor.accessibilitySupport` setting. Reloading the window only fixes the issue temporarily: focusing on another app and switching back stops line wrapping again.

Example:

![](https://cdn.zappy.app/f65670080d403b2b2fb61c404d0c5ecf.gif)

Not sure where the best place to mention this is (maybe #95428). This seems like a bug where `"editor.accessibilitySupport": "off"` still uses the system's accessibility settings to determine if line wrapping is enabled. Also, I would think "auto" would change when settings like "Voice Over" or "Voice Control" are turned on but not change for "Zoom".
