### ISSUE TITLE
Go to Running Cell is great... but... could be improved to "Go to Last Run Cell".

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode#142898]
1. Open a notebook that has a good number of cells (20+) that will take a few minutes to run.
2. Modify one of the cells in the middle (but won't take long to get to) to contain an error.
3. Run All, making sure that the cell with the error isn't visible on the screen.

When execution ends due to the error it encounters, it's confusing what happened. Did the notebook complete? Why isn't it running? There's no indication that an error occurred that stopped execution.

Another approach here would be to automatically scroll to the cell that errors out, but I think that would be a pretty rude behavior.

This happened to me in a real-life situation, so marking as nb-golden.

**Comment by rebornix** [comment]
This is a nice command to have but I'm not sure if I want to see all the time on the toolbar.

**Comment by greazer** [comment]
Referenced in https://github.com/microsoft/vscode-jupyter/discussions/9572.

**Comment by andreaschiappacasse** [comment]
+1 

I would love to have this feature!
The use case mentioned by greazer is the main one, and it happens quite frequently to me and my colleagues.

Another use case would be something like:

- Have a notebook with multiple cells
- Run some computation-heavy cells which take some time to finish
- Do some work somewhere else in the notebook
- See from the status bar that the previously running cell finished
- Quickly jump to the output by pressing "Go to Last Executed Cell" without scrolling

**Comment by smcateer** [comment]
Great feature req, I reckon.

The real issue here is "failing silently". Where one of the cells throws an error, the person running the code needs to be made aware of it - if it was up to me, you'd get a beep and jump to the error (so the traceback in the output is on the screen).

Not sure about:

- What do you do when you are just running one (or a couple of) cells? Jumping in this scenario could get annoying.
- What do you do if the cell is partially in view?
- What do you do for warnings?
