### ISSUE TITLE
Change in behavior in how diagnostic squiggle is shown between v1.61 and 1.62+

### ISSUE THREAD

**Issue by DetachHead** [microsoft/vscode#142810]
### VS Code version

1.62.1

### Extension version

2021.11.1422169775

### OS type

Windows

### OS version

10

### Python distribution

python.org

### Python version

3.10

### Language server

Pylance

### Expected behaviour

![image](https://user-images.githubusercontent.com/57028336/141023099-2368711a-3510-4dbc-9d81-588096d88bcc.png)

### Actual behaviour

![image](https://user-images.githubusercontent.com/57028336/141022916-8cb75639-2c77-4df0-b3fc-f0f55f307053.png)

### Steps to reproduce

1. use this config in `settings.json`:
    ```json
    {
        "python.linting.mypyArgs": [
            "--show-column-numbers"
        ],
        "python.linting.mypyEnabled": true,
        "python.analysis.typeCheckingMode": "off"
    }
    ```
2. cause a type error, eg:
    ```py
    def foo(value: int) -> None:
            ...


    foo("asasdf")

    ```

### Logs

```
> ~\proj\.venv\Scripts\python.exe -m mypy --show-column-numbers ~\proj\Sandpit\foo.py
cwd: ~\proj
> "~\proj\.venv\Scripts\activate.bat && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python c:\Users\user\.vscode\extensions\ms-python.python-2021.11.1422169775\pythonFiles\printEnvVariables.py"
##########Linting Output - flake8##########
##########Linting Output - mypy##########
Sandpit\foo.py:5:5: error: Argument 1 to "foo" has incompatible type "str"; expected "int"
Found 1 error in 1 file (checked 1 source file)
> ~\proj\.venv\Scripts\python.exe ~\.vscode\extensions\ms-python.python-2021.11.1422169775\pythonFiles\testing_tools\unittest_discovery.py . *.py
cwd: ~\proj
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by alexdima** [comment]
You're right, I forgot about this change. The editor used to artificially expand zero width diagnostics (empty ranges) on the word next to the diagnostic.

I changed this for https://github.com/microsoft/vscode/issues/66482 where there were examples where expanding to the word next to the diagnostic is not desirable (e.g. missing semicolon at end of line).

**Comment by moto-ctrl** [comment]
Thank you for picking this up. I'm not sure if I properly understand the original issue from the ticket you mentioned where change of this behaviour was implemented, but I hope there's no conflict in resolution. I'm looking forward to testing the fixed version!

**Comment by alexdima** [comment]
Reverted 51e883793d162727c0e50427ddb0e7f12251c37c and pushed ae7bdc119fca3c34eddf18ec3945da19a55848e2 as an alternative fix for #66482

**Comment by DevilXD** [comment]
@alexdima Which version will this fix be included in? `v1.65`?

**Comment by alexdima** [comment]
Yes, `v1.65`.

**Comment by joyceerhl** [comment]
Still seems to repro for me in 1.65-insider: 
![image](https://user-images.githubusercontent.com/30305945/155798869-687cd0c4-5688-4766-b384-cdfdbddee84d.png)

**Comment by joyceerhl** [comment]
Verified based on new steps: 
![image](https://user-images.githubusercontent.com/30305945/156034412-cc557eb4-93d1-44b1-8c33-50bc6ded6d42.png)

**Comment by karthiknadig** [comment]
@alexdima This is the diagnostic object we get back after parsing `mypy` output:
```
{
    "severity":"Error","message":"Argument 1 to \"foo\" has incompatible type \"str\"; expected \"int\"",
    "range": {
        "start"{"line":3,"character":4}, 
        "end": {"line":3,"character":4}
    },
    "source":"mypy",
    "code":"error"
}
```
I believe since the diagnostic is falling on `"` it is treating it as a non-word character, hence not highlighting the entire word. I verified that `mypy` returns the same bit of information from previous versions.

**Comment by alexdima** [comment]
@karthiknadig Then this issue was always there, because the current behavior matches that of 1.61. If a zero-width error lands in a non-word character, it is rendered with the width of 1ch. You can also try 1.61 or older versions of VS Code using the download links at the top e.g. https://code.visualstudio.com/updates/v1_61

**Comment by DevilXD** [comment]
@karthiknadig At this point, VSCode has "fixed" the issue on this side, which ultimately ends up in a breaking change. Now it's time for the Python extension to alter how the MyPy and Flake8 output is parsed, so that the "parsed diagnostic object" you get will actually span the entire argument. Given your example code as `test.py`:

```py
def foo(v:int):
    pass

foo("something")
```

..., this is the raw MyPy output (with `--show-column-numbers`) for it:

```
test.py:4:5: error: Argument 1 to "foo" has incompatible type "str"; expected "int"
```

..., which should result in a diagnostic object along the lines of:

```
{
    "severity":"Error","message":"Argument 1 to \"foo\" has incompatible type \"str\"; expected \"int\"",
    "range": {
        "start"{"line":4,"character":5}, 
        "end": {"line":4,"character":15}
    },
    "source":"mypy",
    "code":"error"
}
```

Note that I've included the exact range here. Alternatively, the existing solution with the `5`th column could be moved 1 character to the right so that it lands on `s`, and then the resulting 0-width range would expand to either `something` or `"something"`. Not sure which one of the two it'd do, so it'd need some testing.

Also, I've installed `v1.61.2` and downgraded the Python extension solely to see what would happen, and this is the result:

![Image](https://i.imgur.com/CEBnNGt.png)

And the same from `v1.60.2`:

![Image](https://i.imgur.com/0KCyjXN.png)

I even tried `v1.53.2` (January 2021, from a year ago), but it looks like you can't go too far back in time without everything collapsing (the Python extension didn't even start because Jupyther crashed), so I'll leave it at that.

**Comment by karthiknadig** [comment]
@DevilXD where is the end part of the range coming from? From the raw output that you have from mypy I see the start 4:5 but not the end range. Without the tool telling us the exact range, how do we know where to stop?
```
test.py:4:5: error: Argument 1 to "foo" has incompatible type "str"; expected "int"
```
I don't see how we can take this (without knowing what exact issue that the linter might be talking about) and translate it to range 4:5 and 4:15. What if the linter as complaining about the type of quote (literal character) that was used vs the entire string. If we for some reason squiggle the entire string it might be wrong. For the best experience here we need the range from the tool.

An interim solution could be:
- [Option 1]: Change the logic @alexdima quoted here https://github.com/microsoft/vscode/issues/142810#issuecomment-1054311122 to special case `"`. Include the full range of the quoted string.
- [Option 2]: From the extension, parse the python content and figure out which token marker that the diagnostic lands on. Doing this from the python extension right now is going to be very expensive. We will have to run two separate scripts to get this answer. First to get the raw linting, and again to parse python and get full ranges. We can do this, but this is a massive change and probably not the way we want to go. 
- [Option 3]: We do have a prototype extension for that wraps linters into their own extension and does this entirely over LSP. https://github.com/python/mypy/issues/12168 . We have lot more freedom there to parse python and send back better ranges. This would be the best interim solution (until tools provide full ranges), but again might take some time to develop. Also, depends on where the ownership of that lands.
- [Option 4]: A way to do this without domain specific info on the range is to get this from the language server. This means that it would be a feature to add on to the LSP.

@alexdima I feel Option 1 might be something we could do now. If that is not the route we want to take, then the next best option is [option 3] for the individual linting extensions to be ready. If you have another recommendation, let me know.

Neiter of the above options provide the best experience, ideally this range should come from the tools themselves. `pylint` recently added start and end ranges to their lint output. Hopefully, other tools also adopt this.

/cc @luabud @brettcannon

**Comment by DevilXD** [comment]
> where is the end part of the range coming from?

Yes, this is the part where I'm not familiar with how the internals of the extension work, so it'd be "up to figure out". I can see that you've already listed several options, neither of which are trivial. What about the shifting approach then? Still using the 0-width range, but placing it 1 character further to the right, so that it lands on the initial `s` in `something` and expands to the whole word automatically? Feels a little bit hacky, but should generally work for most cases I'd think. Only case I can think of where it could not work properly, would probably be an empty string, where it'd underline the second quote only. Still, I think it'd be simple and good enough for now.

**Comment by alexdima** [comment]
@karthiknadig Adding a special case for `"` is not an option. 
* The logic of expanding a zero-width diagnostic to the word it touches is driven by the word definition for the current language, which is defined via language configuration. Going outside of the configured word definition and giving special meaning to `"` as the beginning of a string is not something we can do in the core of the editor. There are languages we must support where `"` is not the beginning of a string, e.g. `"` can be the beginning of a line comment, etc.
* Even adding something special for `"` does not solve the underlying problem. I think the first argument could be an expression which results in a string, so the `"` heuristic would not fly for `foo(("a"+"b"))`.

I suggest that either the extension which can understand the underlying python syntax tries to massage the error or otherwise I suggest that you reach out to the maintainers of `mypy` and ask them for a special CLI flag or something that would output the errors in a format which contains a range, not just a position.

**Comment by moto-ctrl** [comment]
I just had a go at 1.65.0-insiders to see what's changed.
I should stress that the issue with underscoring the right element I could see in all linters that I use simultaneously, that is: pylint, flake8 and mypy which is quite apparent when I browse larger codebase.
For our test case I compared results of 1.65 to 1.64.2 and 1.60.2  stable and my observations are as follow:
- mypy seems to be indeed just one char underscore for this error
- flake8 reporting is now fixed - I can see whole words rather than characters underscored (red squiggles on valu**e**: , **f**oo call or pass indentation)
- there's still something off comparing to 1.60.2 that seems to be related to pylint
  - the newer vscode versions underscore whole function definition with blue squiggle rather than just **def** word like before - in this case it is 'disallowed foo name' and missing docstring
  - unused argument 'value' yellow squiggle got expanded to **value:int** rather than just **value** (again I considered that cleaner in the earlier version)

1.65.0-insider:
<img width="288" alt="image" src="https://user-images.githubusercontent.com/67516823/156581138-4aa34177-309f-4c51-b0d3-33b0200f892d.png">
1.64.2
<img width="234" alt="image" src="https://user-images.githubusercontent.com/67516823/156581241-399fc833-9e22-44cc-ba3d-30896e6bed5e.png">
1.60.2
<img width="279" alt="image" src="https://user-images.githubusercontent.com/67516823/156582552-094a63f7-7506-4f72-b93a-01c2e32f50e3.png">

**Comment by cdce8p** [comment]
@moto-ctrl Regarding pylint. We recently added support for error ranges. Those aren't perfect yet, but we (the pylint team) are working on improving them for the next release. Please take a look at https://github.com/PyCQA/pylint/issues/5466

Like others have mentioned already, this is different to `mypy` and `flake` which both only report a `position`, not a `range`, which VS Code then has to interpret. What is being discussed here is how that behavior has changed / should be changed going forward.

**Comment by moto-ctrl** [comment]
ah I see, so the old version of vscode didn't understand ranges therefore even with latest pylint it still just highlights only the first word (**def** in this case) whereas new vscode parses ranges and the highlight of the whole function comes from the pylint itself - which is being discussed in the issue you linked. Thanks for clarifying that.
I'm going to stand by my earlier statement - old style looks the best :-)

**Comment by cdce8p** [comment]
> ah I see, so the old version of vscode didn't understand ranges therefore even with latest pylint

Correct, we had to add range support to pylint first, after which I contributed a patch to the VSC Python to actually use them.

> I'm going to stand by my earlier statement - old style looks the best :-)

We, the pylint team, would appreciate feedback about specific issues with ranges (in the pylint repo). Probably best after the next update though since that will already address a lot of issues.

Another point, I've seen discussions about custom language server extensions for Python linters the VSC Python team is working on. A switch to select positions or ranges for highlighting might be a good suggestion.

**Comment by moto-ctrl** [comment]
And something else occurred to me - sorry this was perhaps obvious but I'll write it down for benefit of everyone
  - blue squiggle that covers all function - comes from pylint and how it reports error ranges. Will be fixed in pylint.
  - red squiggles from mypy and flake8 - don't report ranges yet, vscode used to handle it by underscoring whole words and that feature has been brought back and is fixed in this ticket
  - however in some edge situations - like error pointing special character as in mypy example - this is not currently expanded due to more complex algorithm required for detection

Here's my example with mypy and flake8 (switched off pylint to get better picture)
I changed foo definition to take **string** rather than **int** and can confirm the fix is working pretty much as expected
(**value, pass, foo** errors come from flake8, **12345** comes from mypy)

1.65-insiders
<img width="257" alt="image" src="https://user-images.githubusercontent.com/67516823/156805644-1ff2466b-e580-4055-b226-5ee788b60ba0.png">

1.64.2
<img width="290" alt="image" src="https://user-images.githubusercontent.com/67516823/156805698-1489d435-6b04-43a0-b283-8a871c767045.png">

**Comment by DetachHead** [comment]
so as this is issue is still not resolved, can it be re-opened and transferred back to the vscode-python repo? or should i re-raise it there?

**Comment by karthiknadig** [comment]
@DetachHead I think this issue is addressed from VS Code.

There are now two issues:
1.  On `mypy`, to provide ranges on the reported items. This will resolve the problem in all scenarios.
2. On `vscode-python`, to detect and expand the squiggle, for the `"` case, temporarily only for `mypy`, until `mypy` provides ranges.
