### ISSUE TITLE
Always open editor even in error cases

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#142875]
1) open a not empty repo folder
2) open a file in an editor (not preview mode)
3) create a new untitled file
4) add a couple of new lines
5) save it as an `ipynb` file
6) close the saved file
7) right click the ipynb file in the explorer and select "Open with..." > Jupyter
-> error notification 
-> the explorer immediately selects the file from step 2. In a small workspace this is not an issue but in a larger on it is. The `ipynb` file might scroll out of the view port.

For me, the error notification here is the wrong tool. This should be a modal dialog. 

Recording of step 7 and the consequences:

![CleanShot 2022-02-11 at 11 45 01](https://user-images.githubusercontent.com/4674940/153659314-688c6513-8c48-4694-a343-11f8aab57a06.gif)

**Comment by bpasero** [comment]
Any customer of `IEditorService.openEditor` is able to pass in `context: EditorOpenContext.USER` as part of the options for opening to signal that the action to open an editor was done as a user action. If you do so, the notification will instead be a modal dialog:

![image](https://user-images.githubusercontent.com/900690/153814141-acb5f938-2516-4f15-a4b4-253cede246c1.png)

As such, moving to respective component owners whether this option should apply or not. 

It is currently used only in a very few selected places because it is quite a heavy interrupt of the user flow, but may make sense in certain contexts.

**Comment by bpasero** [comment]
To clarify: I assigned Jackson for whether any normal click on an entry in the explorer should trigger this and Logan for the "Open with.." flow.

**Comment by lramos15** [comment]
I went ahead and added the modal flow for `Open With...` but this applies to `Reopen with...` too. I believe @rebornix plans to work on better error handling for Jupyter so it's not an issue but this seems like a bad solution for failed editors in general. @bpasero Is there a reason we can't render a lightweight "error editor" like we do when we cannot open a file on disk. Or maybe even just gracefully fallback to the text editor? The reason for the workbench hop is because it opens and closes so quickly that the next editor in the group gets workbench focus.

**Comment by JacksonKearl** [comment]
Makes good sense to me that opening from the explorer would show a blocking error.

**Comment by bpasero** [comment]
> @bpasero Is there a reason we can't render a lightweight "error editor" like we do when we cannot open a file on disk

The error editor only appears for editors that have been opened before and are thus restored in order to preserve the users view state:

https://github.com/microsoft/vscode/blob/4a130c40ed876644ed8af2943809d08221375408/src/vs/workbench/browser/parts/editor/editorPanes.ts#L120

I am not entirely convinced we should change this condition to always open an error editor, I would actually prefer the modal dialog in this case.

Nevertheless, the more I think about it the more we are getting slightly inconsistent:
* sometimes we show a modal dialog on error
* sometimes we show a notification on error
* sometimes we show an error editor

The original reason for having `EditorOpenContext.USER` was for this case where the user would retry to open an editor from an error editor where it felt somewhat bad to show a notification instead of a modal dialog given the explicit intent:
![Recording 2022-02-16 at 08 19 13](https://user-images.githubusercontent.com/900690/154215274-51ee432b-078a-4229-a09f-60b172c26b5f.gif)



@misolori @daviddossett maybe you have thoughts. https://github.com/microsoft/vscode/issues/130971 is slightly related.

**Comment by lramos15** [comment]
> I am not entirely convinced we should change this condition to always open an error editor, I would actually prefer the modal dialog in this case.

I'm fine with the modal but it doesn't fix the problem of your explorer position getting messed up as Kai demonstrates in the recording above.

**Comment by bpasero** [comment]
I think the explorer just automatically reveals the editor when it changes and in this case the editor changes briefly to the faulty one and then back.

**Comment by rebornix** [comment]
For notebooks, especially a Jupyter notebook, common errors during file opening is corrupted JSON. Showing a modal dialog in this case is better than a notification but users still have no way out until they learn about "Reopen editor with ..." from the context menu to open it in text editor and fix the corruption.

I'm wondering if we can open it in text editor when resolving notebook model fails, show the error to users then they can get it resolved.

<img width="1192" alt="image" src="https://user-images.githubusercontent.com/876920/154366352-8e153885-5967-4a4d-a4c3-8dc74abbc999.png">

**Comment by daviddossett** [comment]
> Should we add "Try another editor" in the warning text or modal dialog so users can find a way out to get the data fixed?

I like this idea. Could also reuse the "Reopen editor with..." text as the button text to be consistent with the context menu option?

**Comment by lramos15** [comment]
> Considering this, a "Retry" on the error editor doesn't help too much as it retries with the same editor type and mostly you get the same error message. Should we add "Try another editor" in the warning text or modal dialog so users can find a way out to get the data fixed?

The downside is most editor errors are issues regardless of error type. This is just a special case it seems

**Comment by rebornix** [comment]
> The downside is most editor errors are issues regardless of error type. This is just a special case it seems

@lramos15 we can offer different warning text and buttons based on scenarios, in notebook opening in a text editor is a good way out but we don't want to build our own modal dialog or error editor, instead this should be the same error dialog/editor users see, but with different context.

For example, we can try catch in notebook land and return 

```
{
  error: Error,
  suggestion: 'ReopenWithAnother'
}
```

**Comment by bpasero** [comment]
You can actually control the buttons shown in the error dialog when opening, we do that to offer a "Create File" action in case you open a missing file and text editor does this by creating a `IErrorWithActions`:

https://github.com/microsoft/vscode/blob/ddf1226995307c1d8db3cfafa7f96173c8b023de/src/vs/workbench/contrib/files/browser/editors/textFileEditor.ts#L193-L209

Maybe worth exploring this for notebooks?

**Comment by misolori** [comment]
@rebornix opening a notebook file with errors shows the right dialog:

<img width="1259" alt="CleanShot 2022-03-23 at 13 40 01@2x" src="https://user-images.githubusercontent.com/35271042/159791681-4c12890e-eab9-4651-8923-2e55aa501a26.png">

but using the same repro steps from the original issue still repros:

https://user-images.githubusercontent.com/35271042/159793503-66f798b2-1618-4a03-b904-dc70b3321152.mp4

I assume we want to change this last toast to the same modal dialog?

**Comment by rebornix** [comment]
@misolori good catch, we handle the exception and actions (`Open in Text Editor`) to workbench and it decides how it renders it: notification or modal dialog. @lramos15 we might want to make the consistent.

**Comment by lramos15** [comment]
@bpasero What's your thoughts here? This case involves a call to `replaceEditors` failing because we cannot open a notebook with bad JSON. Replace doesn't currently accept option options though and therefore we cannot define the cases where we would want a modal. I'm not sure if we should default to a modal for all saveAs cases either.

**Comment by bpasero** [comment]
Yeah not really possible today. Should we just make all errors from opening an editor modal and stop using notifications for this?

🤷

**Comment by lramos15** [comment]
I'm anti everything modal but I did like those error panels that would render in place of the editor instead if it couldn't work. That's more in your face than a notification but not blocking like a modal

**Comment by dbaeumer** [comment]
Moving to April.

**Comment by misolori** [comment]
We can always try out the editor error for now, since we already use a similar pattern, and then if it's not enough we can move to trying out the modal dialog.

**Comment by bpasero** [comment]
Will see if I can get to it, otherwise Backlog or out of scope.

**Comment by bpasero** [comment]
Exploring this a bit, the change is pretty straight forward: instead of showing the error pane only when restoring an editor, also show it in all other cases, such as opening an editor.

The example below demonstrates the flow, assuming there is a link to a file that does not exist. This would normally only bring up a modal dialog asking to create the file, but would now open the error pane.

Unclear to me though what to do with the error toast or even error dialog:
* should we only show error message and actions in the error editor pane
* should we still support modal dialogs but avoid notifications?

![Recording 2022-04-01 at 12 46 42](https://user-images.githubusercontent.com/900690/161249415-a82e0f9b-7181-4c32-abe0-a06e56e1cc18.gif)

**Comment by lramos15** [comment]
> * should we only show error message and actions in the error editor pane

I vote for this one. It will prevent the error from blocking the user and then I think in the future when the error pane is cleaned up a bit more with @misolori's mockups it will be even easier for the user to take action within the pain. For now I would just expect `Create File` or `Try again` to be links within the pane.

**Comment by bpasero** [comment]
I actually find the flow for "Create File" specifically quite nice because I heard from users that work like this:
* create a HTML file
* add links to CSS, JS etc. even though the files don't exist
* follow the links
* just hit enter to create the missing files

If we stop showing the dialog, this flow becomes harder. 

My vote would be: show modal dialog in selected cases where we have meaningful actions but never show the notification toast error that only conveys the error message but no action other than retry.

**Comment by bpasero** [comment]
This landed and will be tweaked.

**Comment by sbatten** [comment]
@bpasero in the demo case that you show (creating a file from a link to a non-existent file), why do we show the editor area error message if they cancel? We are now showing a modal dialog and they have been told the error and opted to cancel.

**Comment by bpasero** [comment]
I think we still do the right thing showing the placeholder, because the user cancelled the dialog that asks for creating the file. The dialog is not asking about the error placeholder.

**Comment by sbatten** [comment]
I'm just not sure what I'm ever going to do with the placeholder in this case. After clicking cancel, I've already chosen not to take the only action that the placeholder provides.

**Comment by bpasero** [comment]
The original motivation for having an editor visible is coming from Kai's original steps: when you carefully select a file in the explorer in some deep hierarchy and an editor opens but then closes due to error, we by default select the previous file in the explorer so you lost your selection. The error editor placeholder tries to help for that case mainly, preserve UI state and stability.
