### ISSUE TITLE
VS Code should not source the shell files that are meant only for _interactive_ shells.

### ISSUE THREAD

**Issue by brandondrew** [microsoft/vscode#142802]
Issue Type: <b>Bug</b>

To reproduce this issue, put the following in your .zshrc:

```
 say "v s code should not source this file"
```

(or the equivalent for your OS if you're not on macOS).  Then restart VS Code and hear the words read to you.  

The .zshrc file is only for interactive shells.  It is not meant to be sourced for other shells:

https://zsh.sourceforge.io/Intro/intro_3.html

VS Code is not a terminal emulator, and using VS Code is not the same as using an interactive shell in a terminal emulator.  (Yes it _has_ a terminal emulator built-in, but that sources the .zshrc file separately, only once it opened, which is what it should do.  That is separate from what I'm talking about here.)

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:00:58.347Z)
OS version: Darwin x64 19.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz (4 x 2900)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|12, 16, 17|
|Memory (System)|16.00GB (3.34GB free)|
|Process Argv|--disable-extensions --crash-reporter-id a9ed9f64-0a5b-47b2-bd31-5dae1735f2df|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstes627:30244334
pythonvspyl392:30425749
pythontb:30283811
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30433059
pythonvs932:30410667
wslgetstartedc:30433508
vsrem710:30416614
vsbas813:30436447

```

</details>

**Comment by meganrogge** [comment]
Thanks for the issue. Do you have the experimental setting `terminal.integrated.enableShellIntegration` enabled?

**Comment by Tyriar** [comment]
VS Code creates an interactive shell and runs `env` in it on startup to source a "development environment", this has been how it's worked since the very beginning and changing this would break all sorts of tools. Here's the code:

https://github.com/microsoft/vscode/blob/62dc317056408a1044a3631aec83b930226cb48b/src/vs/platform/terminal/node/shellEnv.ts#L136-L142

**Comment by Tyriar** [comment]
Note that this doesn't happen if you launch via the CLI so maybe that's a fix if it's causing a problem for some reason.

**Comment by brandondrew** [comment]
Why would you need the shell to be interactive?  

Can you tell me which tools would break?

**Comment by Tyriar** [comment]
@brandondrew it needs to be interactive because we execute `env` in it. Why do we do it this way? Not sure it's how it's always been done and there would need to be a good argument to investigate changing it because of the potential negative impacts a change like this could have on our users. Correct me if I'm wrong, but it seems like your argument is more from a purist's perspective rather than actually causing a real problem for you.
