### ISSUE TITLE
QuickPick active item is reset to first item on programmatically update value

### ISSUE THREAD

**Issue by millerdev** [microsoft/vscode#142941]
- VS Code Version: 1.64.2
- OS Version: Ubuntu 21.10

https://github.com/microsoft/vscode/pull/137857 appears to have broken my extension. Before v1.64 it was possible to set/update the QuickPick value without affecting the active item in the list. Since 1.64 the first item is re-selected immediately after pressing Up or Down Arrow key, which fires `onDidChangeActive`, which programmatically updates `quickpick.value`. I believe the problem is caused by line 502, which calls `this.trySelectFirst()`:

https://github.com/microsoft/vscode/blob/6739b4fd7c434d35a243ce92a2c9ff0e4ee06fdd/src/vs/base/parts/quickinput/browser/quickInput.ts#L500-L503

### Observed: broken in VS Code 1.64.2
Value remains empty when arrow keys are pressed, active item does not change (or rather, changes and is quickly reset). This GIF was recorded with a higher frame rate to show brief flashes of active item changes.
![vscode-1 64 2-bad-update-value2](https://user-images.githubusercontent.com/464726/153734197-b5e70cd0-15ed-4a2d-9a22-1c63cf8021d5.gif)

### Expected: works as in VS Code 1.63.2
Value changes when arrow keys are used to change the active item.
![vscode-1 63 2-good-update-value2](https://user-images.githubusercontent.com/464726/153734473-6bff9857-f1e5-492e-ac19-5627ee939cb1.gif)

The relevant extension code can be found [here](https://github.com/millerdev/pyxt/blob/64034dd17b47a81ebfd0160102919e1f84299a6d/client/commander.js#L169-L203).

**Comment by bpasero** [comment]
Is there a minimal repro sample extension and explanation of what happens and what you would expect?

**Comment by millerdev** [comment]
I don't have a minimal extension, but I can easily give an expected/actual explanation.

**Expected**: programmatic change of QuickPick value does not change the active item in the list.

**Actual**: programmatic change of QuickPick value resets active item to the first item in the list.

**Comment by bpasero** [comment]
Ok understood, I think the origin is this:

https://github.com/microsoft/vscode/blob/4a130c40ed876644ed8af2943809d08221375408/src/vs/base/parts/quickinput/browser/quickInput.ts#L502

And it seems to make no difference whether the value is changed by the user or via API, the value change triggers filtering of the picker and thus we automatically select the first item.

**Comment by TylerLeonhardt** [comment]
>  it seems to make no difference whether the value is changed by the user or via API, the value change triggers filtering of the picker and thus we automatically select the first item.

Yeah this was done intentionally because we had issues about the fact that the event wasn't being triggered when the value was programmatically updated which made the API seem broken. I think we should keep the behavior as it is today so that it doesn't feel broken in that regard (at the end of the day, we have issues opened on either side of the coin)... but I would like to come up with some workaround for you that would involve essentially ignoring the event when you set the value. Today, you have full control over which item is the activeItem... I'm wondering if you can:

* store the active item
* programmatically update the value
* reset the active item

**Comment by millerdev** [comment]
@bpasero thanks for looking into this issue. I think you are correct that `trySelectFirst()` is the culprit. I came to the same conclusion.

>  I'm wondering if you can: store the active item ...

@TylerLeonhardt I'll give that a try, although there is a cascade of events that fire when the value is updated programmatically (see https://github.com/microsoft/vscode/issues/122939#issuecomment-839172774 and https://github.com/microsoft/vscode/issues/135971). I am already attempting to work around that [here](https://github.com/millerdev/pyxt/blob/64034dd17b47a81ebfd0160102919e1f84299a6d/client/commander.js#L187-L191), although that doesn't work anymore on 1.64.

Are you suggesting that I use something like a timeout to wait until after the event cascade ends to reset the active item?

My preference would be to have an API to programmatically set the value without triggering any events, and obviously without changing the active item.

**Comment by TylerLeonhardt** [comment]
One of the APIs we planned on opening up is the ability to allow you to control what is filtered out if the filter is applied. In your case you would essentially say that nothing gets filtered out. 
https://github.com/microsoft/vscode/issues/90521 I wonder if your scenario would work with that proposal...

**Comment by millerdev** [comment]
Does that mean that in this logic
https://github.com/microsoft/vscode/blob/6739b4fd7c434d35a243ce92a2c9ff0e4ee06fdd/src/vs/base/parts/quickinput/browser/quickInput.ts#L500-L503

`didFilter` would be `false` and therefore `trySelectFirst()` would not be called?

If yes, then that seems like it might work. It wasn't clear from the issue linked if that is something I can play with now, or if the feature is still waiting to be implemented. Are we waiting on https://github.com/microsoft/vscode/issues/83425?

**Comment by millerdev** [comment]
Confirmed, it would work if there was a way to skip the filter (and also skip `trySelectFirst()`).

**Comment by TylerLeonhardt** [comment]
I would much prefer to expose a way to skip the filter & selection than to expose a special way to set the value without triggering events (which feels more hacky).

Because of this, I'm going to dupe this to https://github.com/microsoft/vscode/issues/90521 so that we can solve the problem of "having input completion" using custom filter logic.

Yes #83425 is part of it. In short, what you want to do should be doable already if your extension was a part of the core product... but we take the approach of only exposing things to API one at a time so that we don't undertake a hard-to-maintain API surface area.

The _good_ news is.... since it's possible in core already, exposing that to API isn't a huge undertaking... but it does require API review.
