### ISSUE TITLE
Jupyter cookie crumb trail showing entire cell content

### ISSUE THREAD

**Issue by david-waterworth** [microsoft/vscode#143063]
Hard to describe so I've posted an image. You can see after the `notebooks > notebook name` part of the path it's displaying the entire cell contents (code) with an end of line character. Not sure what it's supposed to be displaying but at best it's not overly useful.

![image](https://user-images.githubusercontent.com/5028974/153502274-7c1af38b-573b-4e37-83da-55292176228c.png)

## Environment data

Version: 1.64.1
Commit: d6ee99e4c045a6716e5c653d7da8e9ae6f5a8b03
Date: 2022-02-07T17:17:47.733Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.4.0-99-generic

**Comment by greazer** [comment]
Breadcrumbs are handled by core VS Code.

**Comment by roblourens** [comment]
I find this annoying too, we could just show the first line, or a max number of characters.

**Comment by rebornix** [comment]
The comment does say it should only show the first non empty line https://github.com/microsoft/vscode/blob/4a130c40ed876644ed8af2943809d08221375408/src/vs/workbench/contrib/notebook/browser/contrib/outline/notebookOutline.ts#L430-L432 but the code doesn't reflect that.

I'm going to fix this since it needs to use some proper text buffer api.
