### ISSUE TITLE
The dialog pops up repeatedly after clicking a button

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode#143002]
**VS Code Version:** 1.64.2
**OS Version:** Win 10
**Tye extension version:** 20220211.2

**Steps to Reproduce:**

1. Make sure the C# extension isn't installed in the VS Code
1. Install **Tye** extension in VS Code.
2. Download the application by the command "git clone https://github.com/pratiksanglikar/tye-demo" -> Open the application in VS Code.
3. F1 -> Tasks: Run Task -> Tye run.
4. Debug with "Ddebug with Tye" -> Click a button in the popped up dialog, e,g. "Cancle". 
    ![MicrosoftTeams-image (8)](https://user-images.githubusercontent.com/62053665/153832223-fd1e5664-30f8-4e6f-91ff-9481a111f7af.png)
5. Check whether the dialog doesn't pop up anymore.

**Expect:**
The dialog doesn't pop up anymore after clicking a button.

**Actual:**
The dialog pops up repeatedly after clicking a button. It loops four times in total.

**Comment by philliphoff** [comment]
This is on [`microsoft/vscode-tye`](https://github.com/microsoft/vscode-tye). The extension sets up a watch task to auto-attach when processes are restarted. When the initial failures to attach occur, the extension still sets up the watch task, which notices that the processes aren't attached (because that failed) so it tries to attach again, resulting in the additional failures.

**Comment by philliphoff** [comment]
Feel free to close this issue; a copy exists in our repo.

**Comment by weinand** [comment]
@philliphoff thanks for lettings us know
