### ISSUE TITLE
Despues de actualizar a la version 1.6.1 ya no puedo guardar cambios en ninguno de mis archivos ! ! !

### ISSUE THREAD

**Issue by sconsa** [Microsoft/vscode#14306]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T16:21:53.542Z)
- OS Version: Windows_NT ia32 10.0.10586
- Extensions: HvyIndustries.crane-0.2.1, Kasik96.format-indent-1.3.0

Steps to Reproduce:

1.
2.

**Comment by weinand** [comment]
automatic translation:
"After updating wing version 1.6.1 and I can not save changes to any of my files"

**Comment by bpasero** [comment]
@sconsa 
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by sconsa** [comment]
@bpasero Efectivamente, al parecer si era un conflicto con una extensión que instale enseguida de terminar la actualización automática. Muchas gracias ! ! !

**Comment by weinand** [comment]
translation:
Indeed, it seems if it was a conflict with an extension to install immediately to end the automatic update. Thank you very much ! ! !
