### ISSUE TITLE
Compare files: switches behaviour from line to words without apparent reason.

### ISSUE THREAD

**Issue by MagTun** [microsoft/vscode#143092]
Issue Type: <b>Bug</b>

When I compare 2 simple text files, just adding a character (like `-`) on an empty line totally change the behaviour: it switches from comparing whole line to comparing words within the lines.

Without the character added (cf. empty second line): 
![image](https://user-images.githubusercontent.com/15843700/154040316-fc07aa6c-7207-4ba3-a778-4634b589d2f7.png)

With a character added (cf. second line): 
![image](https://user-images.githubusercontent.com/15843700/154040307-57612231-d424-4809-9b3a-bbddb76348bd.png)

 

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2760QM CPU @ 2.40GHz (8 x 2395)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|15.90GB (8.90GB free)|
|Process Argv|--crash-reporter-id bdf5af44-fcbb-4933-8392-2eb4d06e29a5|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.2.3
project-manager|ale|12.5.0
All-Autocomplete|Ati|0.0.23
vscode-custom-css|be5|6.0.2
replacerules|bhu|0.4.1
vscode-autohotkey-plus|cwe|2.6.2
transformer|dak|1.12.0
xml|Dot|2.5.1
vscode-install-vsix|fab|1.4.0
auto-close-tag|for|0.5.14
macros|ged|1.2.1
copilot|Git|1.7.5003
beautify|Hoo|1.5.0
vscode-favorites|how|1.10.2
reg|ion|1.0.3
vscode-edit-csv|jan|0.6.5
vscode-opn|lfu|1.1.2
rainbow-csv|mec|2.0.0
python|ms-|2022.0.1814523869
vscode-pylance|ms-|2022.2.1
jupyter|ms-|2022.1.1201831736
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
cpptools|ms-|1.8.4
powershell|ms-|2021.12.0
codemap|ole|1.16.2
subtitles-editor|pep|1.1.6
code-settings-sync|Sha|3.4.3
vscode-fileutils|sle|3.5.0
html-preview-vscode|tht|0.2.5
luna-paint|Tyr|0.13.1
local-history|xyz|1.8.1
json-helper|zho|1.3.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30425749
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30438341
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstartedc:30433508
vsclayoutctrc:30437038
vsrem710:30416614
pythonvsnew555cf:30436485
vsbas813:30436447
vscscmwlcmc:30436992
helixcf:30438276

```

</details>

**Comment by MagTun** [comment]
Strangely on another PC, the behaviour is kind of reversed: 

![Dimmer_2022-02-15_11-22-39](https://user-images.githubusercontent.com/15843700/154042702-9bf0fa1d-894c-445a-8d3a-e2da32b1ea52.png)
![Dimmer_2022-02-15_11-22-18](https://user-images.githubusercontent.com/15843700/154042707-2c09029f-7c3c-4c79-9762-54f2f8516ed6.png)


VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-2370M CPU @ 2.40GHz (4 x 2395)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>rasterization: unavailable_off<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|7.87GB (2.36GB free)|
|Process Argv|C:\\Users\\Me\\Desktop\\speech to text to do with Azur\\US Inside Wuhans coronavirus lab.txt --crash-reporter-id 3b7d0aba-be06-4816-bed1-a2fb96231eb9|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
macros|ged|1.2.1
copilot|Git|1.7.5003
beautify|Hoo|1.5.0
vscode-favorites|how|1.10.2
wordcounter|kir|2.3.0
vscode-opn|lfu|1.1.2
rainbow-csv|mec|2.0.0
python|ms-|2022.0.1814523869
vscode-pylance|ms-|2022.2.1
jupyter|ms-|2022.1.1201831736
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
cpptools|ms-|1.8.4
gremlins|nho|0.26.0
subtitles-editor|pep|1.1.6
csv-to-table|php|1.3.0
vscode-fileutils|sle|3.5.0
vscode-autohotkey|sle|0.2.2
html-preview-vscode|tht|0.2.5
local-history|xyz|1.8.1


</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392cf:30425750
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30438340
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstartedc:30433508
vsclayoutctrc:30437038
vsrem710cf:30416617
vsbas813:30436447
vscscmwlcmc:30436992
helixcf:30438276
cppdebug:30437093

```

</details>

**Comment by alexdima** [comment]
The diff algorithm runs in two phases. In the first phase, each line is considered to be a sequence element. So for example given the files:

* original:
```
Line1
Line2
Line3
```
* modified:
```
Line11
Another
Line2
Line33
```

In the first pass, individual characters in lines are not relevant, and lines are treated as a unit. Giving a notation to each unique line: the original becomes the sequence `ABC` and the modified becomes the sequence `DEBF`. Notice how `Line2` is assigned `B` on both sides because the line appears on both sides.

In the first pass line 2 from the original file is found to be identical with line 3 from the modified file (`B`).

In the second pass, each diff region is revisited (A<->D,E, C<->F) and if the diff region is small enough (under 20 lines), character level diff is computed:
 * for the first diff region the compared sequences are `Line1` and `Line11\nAnother`
 * for the second diff region the compared sequences are `Line3` and `Line33`

For example, adding a single character on line 2 would have a large effect on the first phase, since then the sequences would be completely distinct e.g. `ABC` vs `DEFG`. This initial line based approach makes a lot of sense for code where usually each line contains a statement. I agree that this two-phase approach is not ideal for prose, where each line contains usually an entire paragraph and perhaps diffing should first run over sentences. However, we have optimized our diff algorithm for code.

I can leave the issue open for now to see if we have some ideas about implementing an alternative diff strategy.

**Comment by daevski** [comment]
I would like to add this as evidence for something being a little off about the algorithm... I will also upvote. Thank you.

![notepad++vs-vscode-compare](https://user-images.githubusercontent.com/26718996/155344737-a26075e1-ef5d-4a1c-a5b3-b87f23c9cbf5.png)
