### ISSUE TITLE
"Cut and paste" not working if cell is deleted between "cut" and "paste"

### ISSUE THREAD

**Issue by andreaschiappacasse** [microsoft/vscode#143123]
Cutting and pasting from a cell which is deleted before pasting doesn't seem to work.

## Environment data

-   VS Code version: 1.64.2
-   Jupyter Extension version: v2022.1.1201831736
-   Python Extension version: v2022.0.1814523869
-   OS: Windows 10
-   Python version: 3.8
-   Type of virtual environment used: N/A
-   Jupyter server running: Local

## Expected behaviour

Cut text from a cell which is deleted should be pasted.

## Actual behaviour

Nothing is pasted.

## Steps to reproduce:

1. Create an empty notebook
2. Create two code cells
3. Write something in the first cell
4. Cut (ctrl+x) the text written in the same cell
5. Delete the first cell (select cell + x)
6. Try to paste the cut text on the second (now unique) cell

**Comment by greazer** [comment]
This is another data loss issue. As mentioned is at least related to #144102

**Comment by hello-smile6** [comment]
Shouldn't this use system clipboard functionality?

**Comment by IanMatthewHuff** [comment]
@rebornix Mind if I poach this bug from you? It's in the same area related to my previous change. Felt I could at a minimum investigate at the same time.

**Comment by rebornix** [comment]
@IanMatthewHuff that would be really nice if you can look into this, thanks in advance!

**Comment by IanMatthewHuff** [comment]
Yeah it's interesting, unlike the other issue I'm not sure if there is a quick / easy fix here. If there is a per cell undo / redo stack then we don't want to keep it around if the cell is deleted, each cell is essentially a document and I wouldn't expect a deleted document to somehow save off an undo redo stack just in case it was restored. But I'm pretty new to the code here, so that might be an over simplification on my part. I'll know more soon.

**Comment by rebornix** [comment]
Root cause is https://github.com/microsoft/vscode/issues/122462
