### ISSUE TITLE
Link terminal detection behaves differently running from source from latest Insiders build

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#143100]
I was looking at trying to fix #108660, but while doing so I noticed that behaviour in the latest code is different to what I see in Insiders and I can't track down why (but it makes me wonder if fixing source would actually fix released VS Codes)... Links with line and col information appear to not be detected when running from source:

![hover](https://user-images.githubusercontent.com/1078012/154059501-2b8f63c3-77fb-4377-b940-ca6c49b7dc06.png)

Changing this index from `0` to `1` (to stop the line/col number being included in the request to resolve the URI) seems to resolve it, but I don't know if that's the correct fix:

https://github.com/microsoft/vscode/blob/ce46f445c0f1c3992b78a0e401c6125f1aac7bf9/src/vs/workbench/contrib/terminal/browser/links/terminalLocalLinkDetector.ts#L96

@Tyriar FWIw, it seems like there have been some regressions in this area. I had an old version of Insiders on this PC and it correctly handled `file:///C:/foo:1:1` when I opened it, but when I updated to latest, it does not (eg. for `file:///C:/foo` the link detector producers links with text `C:/foo` but with the path set to `/C:/foo`, but then it highlights only `/foo` in the terminal).

I started a PR to try to handle `file:///` paths better (https://github.com/DanTup/vscode/commit/cb1dcfc0c995e3741533197aee174a57206f872e), but the differences between Insides/Source (despite no apparent changes in this area for 6 days), and the test using it's own `resolve` method have complicated things a little (I have passing tests, but things still don't work when I run VS Code from source).

I'd really like to resolve #108660 as it results in VS Code sending bad paths to LSP servers (paths without drive letters) that the Dart LSP server rejects, causing users to see a large number of "LSP request has failed" messages after clicking one of these links (even though VS Code _appears_ to open the file fine).

**Comment by DanTup** [comment]
Without the `file:///`, the links _are_ detected when running from source even with the line/col. Note: I've reverted my changes locally while testing this, so I don't believe I've caused it :-)

**Comment by Tyriar** [comment]
@DanTup Both OSS and Insiders behave the same for me. I notice your commit adds `file://` support to the "local links detector" but this was intentionally avoided. Links in that form are all handled by monaco's link detector, here's the adapter that we hand off to xterm.js: 

https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/terminal/browser/links/terminalUriLinkDetector.ts

We behave basically the same as the editor wrt file URIs, but the URI detector just throws away the link beforehand if it doesn't exist:

![image](https://user-images.githubusercontent.com/2193314/154078619-9965070e-6128-49ae-aef5-57fa8683a9b9.png)
![image](https://user-images.githubusercontent.com/2193314/154078656-513905ed-3370-4e02-ab86-bf590fe3c650.png)

In the terminal, this hover and the underline without holding ctrl means it's detected correctly:

![image](https://user-images.githubusercontent.com/2193314/154078827-33898110-aff5-4190-a5e7-4f5d8c59b6b4.png)

Adding the line/col to the end shows the link start at `/Github` like in your example, I think this link is detected by the local link detector since `:` isn't allowed. It's basically just a coincidence that this works.

![image](https://user-images.githubusercontent.com/2193314/154078959-def8c9dc-410f-4504-bed9-98070fcd2487.png)

I guess we could improve handling of file URIs within the local link detector as in your commit. I think the reason that `match[1]` fixes the problem is because you add another capture group to the regex, this stuff's all pretty fragile so maybe try put the fix together without adding another pair of parens and instead add the `file://` check inside `pathPrefix`/`winPathPrefix`. We then also need to make sure we handle `file://` correctly when creating the URI here:

https://github.com/microsoft/vscode/blob/9f32b2cc85167f6c7900397b401c4c4febd9d6de/src/vs/workbench/contrib/terminal/browser/links/terminalLinkManager.ts#L420-L429

---

When I use 1.64 I don't actually see a regression but an improvement in Insiders as both cases create the `/Github` uri:

![image](https://user-images.githubusercontent.com/2193314/154080947-55a75ffe-0fd2-4eec-a6fe-3131d9db700b.png)
![image](https://user-images.githubusercontent.com/2193314/154081023-b4859864-8eeb-4058-93fb-3755d1586cd8.png)

**Comment by DanTup** [comment]
@Tyriar to clarify, I see the difference _without_ my change, and the `match[1]` fix seemed to fix that there. I'm not certain that the built version doesn't still have bits of my change in (I had reverted it when I started seeing this), but I'm not sure how to verify. Should `yarn watch` cause everything to rebuild if it's changed? Is there a way to force a clean?

> terminalUriLinkDetector.ts

I did wonder if it should be there, but I think part of the issue might be that LocalLinkDetector is detecting these too. What should/will happen if both of them detect overlapping links, who wins?

> without adding another pair of parens and instead add the file:// check inside pathPrefix/winPathPrefix

The parens here are a non-matching group `(?: ... )` so I don't think they should be affecting things here. I think `match[0]` is the entire match (not the first group), so includes any line/col part also captured by the regex. I don't know if that's intended/allowed though - it gets sent to a file service for resolving, and I wasn't sure where that lived (since the test has its own fake one), so I don't know if it's allowed to have line/col info on the end (but since there are many different formats, I would have expected not).

**Comment by Tyriar** [comment]
> Should yarn watch cause everything to rebuild if it's changed? Is there a way to force a clean?

To make sure you can delete `out` and the run `yarn watch` again.

> What should/will happen if both of them detect overlapping links, who wins?

The uri one wins as it was registered first:

https://github.com/microsoft/vscode/blob/9f32b2cc85167f6c7900397b401c4c4febd9d6de/src/vs/workbench/contrib/terminal/browser/links/terminalLinkManager.ts#L73-L79

>  it gets sent to a file service for resolving, and I wasn't sure where that lived

The link is extracted from the regex here:

https://github.com/microsoft/vscode/blob/9f32b2cc85167f6c7900397b401c4c4febd9d6de/src/vs/workbench/contrib/terminal/browser/links/terminalLinkManager.ts#L413

Not the happiest with how the regex gets shared outside local link detector but I had already made so many changes in the area.

**Comment by DanTup** [comment]
@Tyriar thanks - I'll try cleaning and have another go soon.

Do you know why sometimes underlines show up only when holding `ctrl`, and sometimes without? I thought maybe not needing to press `ctrl` was only for local links, and `ctrl` was required for others, but I'm not sure that's accurate?

**Comment by Tyriar** [comment]
@DanTup whenever underlines don't show without ctrl it means it's a "low confidence" search/word link (from `TerminalWordLinkDetector`). The main reason for this was since essentially everything is a link, it was very noisy having underlines on everything, when some links are much more likely to be clicked than others.

**Comment by DanTup** [comment]
Aha, that makes more sense now - thanks!

**Comment by DanTup** [comment]
@Tyriar I managaed to get the tests working, but if I add the following to `src\vs\workbench\contrib\terminal\test\browser\links\terminalUriLinkDetector.test.ts` it passes:

```ts
test('danny', async () => {
	await assertLink(TerminalBuiltinLinkType.Url, 'file:///c:/foo.bar file:///c:/foo.bar:1:2', [
		{ range: [[1, 1], [18, 1]], text: 'file:///c:/foo.bar' },
		{ range: [[20, 1], [41, 1]], text: 'file:///c:/foo.bar:1:2' }
	]);
});
```

So I think these links are being detected fine by `terminalUriLinkDetector`, but I don't know where things from there. I can still repro things being broken in latest insiders by running the following in a Terminal:

```
$null >> C:\src\foo.txt; echo file:///C:/src/foo.txt:1:1; $null >> M:\src\foo.txt; echo file:///M:/src/foo.txt:1:1
```

Links are detect without their drive letters and open incorrectly:

![image](https://user-images.githubusercontent.com/1078012/161989317-36bf8d1e-a761-48ff-be64-e380161b5a23.png)

![image](https://user-images.githubusercontent.com/1078012/161989368-d64e3896-dfbc-460b-b760-8e182bf51aa8.png)

If `TerminalUriLinkDetector` is not the right place to fix/test this, where is?

**Comment by Alizter** [comment]
Is there any work around for this? Apart from being annoying that we have to press Ctrl now (with 1.66) the actual link detection is completely borked:
```
File "test-suite/tools/gen_rules/gen_rules.ml", line 161, characters 10-24:
```
I can only select the file, number and `line` separately. It jused to be that the entire line was highlighted, how can I fix this?

**Comment by DanTup** [comment]
I don't know of a workaround. I have tried to look at fixing it multiple times, but each time I spend some hours trying to get things working (I still can't run VS Code from source, only the tests.. running the editor just spews errors about sqlite) and then can't track down where the issue is (the tests that seem to relate to this work fine with the `file:///` URLs that are broken in the actual terminal - although I see that part of the functionality is being shortcut through some `resolveUriForTests` or similar function, that presumably is not the one used by the real functionality).

**Comment by DanTup** [comment]
I don't know what the cause of the original issue was (a difference in Insiders vs stable), but I think the underlying issue here is really just #108660 (where the built-in link providers don't work correctly), so I'll close this.

As a workaround, I've just implemented my own TerminalLinkProvider that parses `file:///` URIs for `.dart` files.
