### ISSUE TITLE
vscode.dev cell languages not working properly

### ISSUE THREAD

**Issue by alyssajotice** [microsoft/vscode#143315]
Version: 1.64.2
Commit: f80445acd5a3dadef24aa209168452a3d97cc326
Date: 2022-02-09T22:00:24.333Z
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36 Edg/98.0.1108.50
OS Version: Windows 11

I am working on Live Share notebook support in vscode.dev. Notebook cell language modes are not working properly on web. When the guest opens a cell, the language identifier is displayed rather than the language itself. No language services are present and the cell is not able to be run. Changing the cell to a built-in language type solves the problem. We do not have this issue on the desktop client.

This gif shows the language showing up as the incorrect name and not being able to run it. The host is able to run the cell: 
![language-wrong-name](https://user-images.githubusercontent.com/22576531/154570887-2b4e4151-ee19-43ca-9cf1-2f6bb0cc81be.gif)

This gif shows that when you change the language to CSS, the cell becomes enabled and you can run it:
![change-language-run](https://user-images.githubusercontent.com/22576531/154571210-a651db8d-c5bd-41dd-b208-76231cb1b3e6.gif)

When the guest opens the notebook, we return an object that has `NotebookData`. Each cell in the list has a languageId that would be `dotnet-interactive.csharp` in this example. How can we get these cell types to show up properly on web?

cc @rebornix

**Comment by rebornix** [comment]
@alyssajotice I think this happens when there is no such language defined on the guest client/machine, the `dotnet-interactive.csharp` is contributed by the .NET notebook extension, which is not mirrored in on the guest client. I wonder if we need a plugin model for Live Share, with which the .NET notebook can tell Live Share what language configurations should be synced to the guest.

**Comment by alyssajotice** [comment]
I see. Why don't we see this issue with the desktop extension?

**Comment by roblourens** [comment]
I'm assuming the .NET interactive extension is not installed in the browser, because it's not web enabled. So to get the same behavior, Live Share would have to contribute this language configuration in a browser client, that's what @rebornix is suggesting. Or it would be even better if the .NET interactive extension could be installed in a browser.

**Comment by alyssajotice** [comment]
Thanks @roblourens. I will see if .NET has plans to be browser-friendly any time soon. Can you explain more how I could contribute the language configuration?

**Comment by roblourens** [comment]
Not a notebook-specific concept - what happens when a host opens a file with some custom language from an extension, and the guest does not have that language extension installed?

**Comment by alyssajotice** [comment]
@roblourens, I am investigating this further. I understand why syntax highlighting wouldn't work for custom cell types. However, why can't they be executed? Live Share registers a notebook controller for notebooks  with extension `*`. But, when I try to execute a custom cell type, the controller handler is not called as it is for other cells. Do you know why this is?

**Comment by roblourens** [comment]
I wouldn't expect a difference there, I'll try it

**Comment by roblourens** [comment]
Here is the problem:

https://github.com/microsoft/vscode/blob/02e8bd149ca3fb68e7f26ebec33f920ba0feef96/src/vscode-dts/vscode.d.ts#L12941

The NotebookController has to declare which languages it supports, and the Live Share Controller's doesn't include the unknown one. There's something tricky here. The comment says `Any language identifier from languages.getLanguages is possible`. I'm guessing you pull from that because your kernel supports all languages. But when you give vscode a cell with a language ID that is not actually registered as a language, then that comment won't be true anymore. But I'd say that's on the Live Share extension to handle - your kernel should be registered for the all the language IDs that exist in the document.

**Comment by roblourens** [comment]
> that's on the Live Share extension to handle - your kernel should be registered for the all the language IDs that exist in the document.

I think this is true
