### ISSUE TITLE
VsCode tries to resolve workspaceFolder when no folder is open

### ISSUE THREAD

**Issue by elahehrashedi** [microsoft/vscode#143322]
if you open a single .cpp file in VsCode without opening a folder, and hit "Run and Debug" button, VsCode will be trying to resolve `workspaceFolder`. The C/C++ extension is not sending this variable in `debug configuration` or `build configuration` to Vs Code to be resolved. 

![image](https://user-images.githubusercontent.com/16143955/154580437-82c45d2f-beff-49cf-b034-d6d4aa120b5c.png)

https://github.com/microsoft/vscode/blob/1a17c0f2ef5765c5555a9435f1740daef90c385f/src/vs/workbench/services/configurationResolver/common/variableResolver.ts#L214

This is not a situation that requires an open folder.

**Comment by weinand** [comment]
Using the "Mock Debug" extension instead of the "C/C++" extension for the same scenario does not result in this problem. This is a strong indication that this is not a VS Code issue.

I suggest that you find all occurrences of `${workspaceFolder}` in your extension's code and package.json and replace them with `${foobar}`. Then try your scenario again. If the alert still shows `${workspaceFolder}` then VS Code could be the culprit and I will investigate.

**Comment by elahehrashedi** [comment]
Thank you for your response, it turns out to be the extension issue.
