### ISSUE TITLE
Strange line sorting

### ISSUE THREAD

**Issue by Alessar** [microsoft/vscode#143399]
Let's imagine that there is a simple package config file for example with two packages:
```
<package id="Package" />
<package id="Package.Extension" />
```
When `VScode` runs the `Sort Lines Ascending` command it reorders these lines in reverse order.
Expected that "Package" will be before "Package.Extension"
It is not a very huge issue but like improvements.
Expected that all editors use the same rules of sorting.

VS Code version: Code 1.64.1

**Comment by alexdima** [comment]
VS Code uses [`Intl.Collator.compare`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Collator) and compares entire lines. The line sorting commands are language agnostic and work with entire lines, so the complete strings `<package id="Package" />` and  `<package id="Package.Extension" />` are compared. There is no AST based comparison that could compare only `Package` and `Package.Extension`.

Because the commands compare entire lines, the following explains the sorting:

```js
console.log(['"', '.'].sort(new Intl.Collator().compare));
// evaluates to ['.', '"']
```

I agree that this is not the ideal sorting for this xml example, but our comparison is not AST based, just textual, and I have to be honest, we have no plans to implement custom comparators and deviate from the comparator shipped with JavaScript, which is based on Unicode's spec.
