### ISSUE TITLE
Folding with AL Language doesn't works as expected with #pragma warning statements

### ISSUE THREAD

**Issue by JavierFuentes** [microsoft/vscode#143424]
When you need introduce a `#pragma warning` statement in a Business Central AL file to avoid some compiler warning, the folding/unfolding actions stop at this statement and doesn't works as expected.

<img width="527" alt="image" src="https://user-images.githubusercontent.com/5801847/154773264-2b483fa4-da25-486f-875e-bb7864f38283.png">

- VS Code Version:
Versión: 1.64.2 (system setup)
Commit: f80445acd5a3dadef24aa209168452a3d97cc326
Fecha: 2022-02-09T22:02:28.252Z
Electrón: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

Steps to Reproduce:

1. For example: create a tableExtension AL file with some new fields
2. Add a `#pragma warning` statement in one of them
3. Try to fold the entire `fields { ... }` block

**Comment by PieterBranderhorst** [comment]
The AL language extension for vscode does not seem to provide code folding information. So vscode is using its default approach which is based on indentation. It sets up foldable regions so that they start where indentation increases in the text and end when the indentation is the same or less than where a region started. Since the #pragma line starts in the first column it is taken to be the end of any foldable region above it.

The only fix for this behaviour will be if someone writes language-specific folding range code for the AL language, in the AL language extension or in another extension.

**Comment by aeschli** [comment]
Closing the issue. As explained by Pieter, the folding markers need to be provided by the AL language extension.
