### ISSUE TITLE
`workbench.action.navigate*` hotkeys no longer work with terminal.

### ISSUE THREAD

**Issue by patrick-motard** [microsoft/vscode#143409]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
```
1.64.1
d6ee99e4c045a6716e5c653d7da8e9ae6f5a8b03
x64
```

- OS Version:
```
osx 11.6.1
```

Steps to Reproduce:

Prior to a recent update of vscode, I was able to switch cursor focus back and forth between the terminal, the editor, the file tree / search explorer, using the following keyboard shortcuts:

```
    {
        "key": "ctrl+h",
        "command": "workbench.action.navigateLeft"
    },
    {
        "key": "ctrl+l",
        "command": "workbench.action.navigateRight"
    },
    {
        "key": "ctrl+k",
        "command": "workbench.action.navigateUp"
    },
    {
        "key": "ctrl+j",
        "command": "workbench.action.navigateDown"
    },
```

These commands now only allow moving cursor focus between all panels except for the terminal. I can't navigate to or from it. I'm constantly switching back and forth between my vs code terminal and editor. I want to be able to navigate to it using the same navigation keys i use to navigate to/from every other panel. This is a recent regression.

**Comment by ArturoDent** [comment]
What is your Panel Alignment setting: left/right/center/justify?

That seems to affect these commands.  For instance, I have the Panel set to `justify` so that's the full width.  Then `workbench.action.navigateLeft` or `workbench.action.navigateRight` don't do anything.  Should it?  The Panel is **below** the Side Bar and Side Panel so there is no view container *technically* to its left or right, *only* above it.

If I set the Panel alignment to `center` then all your commands work as you would expect.

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?

I can't repro there

**Comment by patrick-motard** [comment]
As of the latest update today (not insiders build) I am no longer able to replicate this bug.

```
1.64.2
f80445acd5a3dadef24aa209168452a3d97cc326
x64
```

We can probably close this issue. I can re-open if it resurfaces.
