### ISSUE TITLE
connect ETIMEDOUT 191.238.172.191:443

### ISSUE THREAD

**Issue by ydcoming** [Microsoft/vscode#14343]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. connect ETIMEDOUT 191.238.172.191:443
2.

**Comment by weinand** [comment]
@ydcoming please explain in what context the ETIMEDOUT occurred or what you did before it occurred. A screenshot showing the error would help too.

**Comment by onewhitey** [comment]
For me, I get this message after upgrading to the latest version (1.6.1).
I get the error message after starting VS Code.

**Note:**  I am behind a firewall, and am not able to get through due to work requirements. I therefore use VS Code just as a plain text editor.

Error message screenshot is below:

![image](https://cloud.githubusercontent.com/assets/17079068/19713770/687ea830-9b94-11e6-8047-529db27887e7.png)

**Comment by antonywong** [comment]
我想是因为在中国的缘故

**Comment by youys** [comment]
+1

**Comment by youys** [comment]
![image](https://cloud.githubusercontent.com/assets/1190107/20203205/44919f90-a800-11e6-98bd-b2b25908a84b.png)

**Comment by camilobg** [comment]
Another one... 
I think this error is relationed with firewall politics.
In corporate webs the download always presents this error.
At my home this error don't appear

![vscode_error_download_extensions](https://cloud.githubusercontent.com/assets/25792561/22972693/e832d4aa-f361-11e6-95e1-9931ccea512a.png)
