### ISSUE TITLE
contributes.configuration items respects "order" attribute in views only if search box empty

### ISSUE THREAD

**Issue by tuck1s** [microsoft/vscode#143513]
Tested on Insiders Build 1.65.0 and Build 1.64.2.

If an extension's settings are viewed, the presentation order is respected, but _only if the "Search settings" bar is empty.

If the search bar contains anything, including the name of the extension (matching all settings for that extension), the presentation order is alphabetical.

Given that the presentation can still be controlled by the selected extension name in the left menu, it would seem logically possible to respect the sort ordering within an extension settings group.

Examples:
Following ordering (search area blank):
![Screenshot 2022-02-20 at 21 45 19](https://user-images.githubusercontent.com/11942927/154865693-1cb059a9-9045-49e6-8b0b-395d0a08e324.png)

Not following ordering:

![Screenshot 2022-02-20 at 21 44 58](https://user-images.githubusercontent.com/11942927/154865719-7c2390df-5ccd-41b6-9e97-74f6ec1bfd8b.png)

**Comment by rzhao271** [comment]
Verification steps:
1. Modify or write an extension with settings where the settings group and the individual settings use `order` fields to determine the order. An example is at https://github.com/microsoft/vscode-extension-samples/blob/main/configuration-sample/package.json#L33-L70. Also make the setting keys similar so that they can show up under the same search query.
2. Launch the extension, navigate to the Settings editor, and clear the search widget.
3. Confirm that the settings for that extension are displayed in the expected order.
4. Add a query to the search widget such that those extension settings still show up.
5. Confirm that the filtered settings for that extension show up in the same order as in step 3.

**Comment by tuck1s** [comment]
Tested just now on

> Version: 1.66.0-insider (Universal)
> Commit: 45999664ef626d6d665cb585104efdcab383a3cd

LGTM
