### ISSUE TITLE
Relative dimension of TOC is not preserved when window is resized

### ISSUE THREAD

**Issue by stevencl** [microsoft/vscode#143690]
Testing #143138

Maximize the VS Code window
Resize the TOC so that it is approximately a quarter of available screen real estate
Unmaximize the VS Code window
Reduce the width of the VS Code window until the TOC disappears
Increase the width of the VS Code window until it is the same width as before the previous step
Expected: TOC should be the same width (quarter of available screen real estate)
Actual: TOC is set to narrowest possible width

![Recording 2022-02-23 at 10 24 40](https://user-images.githubusercontent.com/1704059/155301716-3900871a-e7f7-4263-92df-8a23d99d176f.gif)

**Comment by rzhao271** [comment]
An issue is the Settings editor remembers that the last width was the min width.
I'll change the proportional layout to true for now, so that when you widen the window, both sides of the splitview widen.

**Comment by rzhao271** [comment]
Verification steps:
1. Widen the VS Code window while looking at the Settings editor so that the table of contents is visible. While widening the window more, both the table of contents on the left and the settings list on the right should grow in width proportionally.
2. Shrink the VS Code window in width so that the table of contents goes away. Then, slowly widen the window again. When the table of contents shows up, the table of contents shouldn't be at its most narrow possible width by default, and the vertical sash should have around 100px of movability.
