### ISSUE TITLE
Suggest to slightly dim the layout control button

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#143671]
Testing #143581

See attached screen shot. The layout control button is "stronger" than those for find, scm, etc and I believe it isn't the important to justify that

<img width="109" alt="Screen Shot 2022-02-23 at 09 39 48" src="https://user-images.githubusercontent.com/1794099/155285530-f9f0943c-150e-4ff6-8766-099553014491.png">

**Comment by sbatten** [comment]
this is highly theme dependent. the icon does not belong to the activity bar, but rather the titlebar so its theme color comes from the title bar.

**Comment by jrieken** [comment]
> but rather the titlebar so its theme color comes from the title bar.

Maybe that's the problem and that a title bar button foreground color needs to be defined. It would default to a slighly dimmed version of the titlebar foreground

**Comment by daviddossett** [comment]
Closing since IMO the foreground color should be aligned across the menu bar, command center icons + text, and the layout icons to reduce the variation amongst elements. Dimming a non-disabled element could also introduce an accessibility issue. Here's roughly what it would look like in context:

<img width="881" alt="CleanShot 2022-12-06 at 11 28 33@2x" src="https://user-images.githubusercontent.com/25163139/206004398-c5f9663d-81f1-42bf-b046-aea2270796f6.png">


If you feel strongly about this one, feel free to reopen and we can explore.
