### ISSUE TITLE
Quick Open (Ctrl+P) should not show the current file at the top

### ISSUE THREAD

**Issue by codecoll** [microsoft/vscode#143660]
Ctrl+P is useful to quckly open files, but it's not useful to show the current file at the top, since you are in that file already, so when you want to open an other recent file, like the previous recent file or one of the more recent files below it then you have to press an extra down arrow key in the list to get there.

Quick open should not show the current file on the top of the list, it should at most put it at the bottom, since the current file is the most unlikely file you want to "open".

Alternatively, if it is shown at the top then it should not be selected by default, the file below it should be the one selected by default when Quick Open is invoked.

**Comment by bpasero** [comment]
You can bind `Ctrl+P` to `workbench.action.quickOpenPreviousEditor` to select the second entry by default in the file/editor picker.

**Comment by codecoll** [comment]
Thanks, but I meant the built in default. Putting the current file to the top selected by default is pretty useless, isn't it?

**Comment by gjsjohnmurray** [comment]
@codecoll it allows a user to dismiss the picker by simply pressing Enter instead of reaching for Esc. Changing the default behaviour will break this.

**Comment by codecoll** [comment]
ESC is the general dismiss key, why should Enter be used here for this? Selecting the previous file by default is much more useful.

**Comment by bpasero** [comment]
If you care about selecting a previous entry quickly via quick pick, there is an alternative that I am using since day 1: it allows to operate quick pick without the input field and just by keybindings and in that mode the second item will be selected by default. It works a bit like Alt-Tab for switching applications and can be accessed when you press `Ctrl+Tab`:
![Recording 2022-02-23 at 20 09 46](https://user-images.githubusercontent.com/900690/155390230-c0efee85-d463-4dc1-b85c-e1b72eda55e2.gif)

**Comment by TylerLeonhardt** [comment]
@codecoll in situations like this where we have a very straightforward way of configuring a different behavior, we are wary to change so that we don't mess with the muscle memory of users.

Since there's a simple alternative in this case, I'm gonna close this as as-designed.
