### ISSUE TITLE
attach debug node.js wrong

### ISSUE THREAD

**Issue by wlof202** [microsoft/vscode#143682]
Issue Type: <b>Bug</b>

1.attch debug one node.js progress
2.attch debug other node.js progress, the target was last progress

debug config:
{
            "name": "Attach to node",
            "type": "node",
            "request": "attach",
            "processId": "${command:PickProcess}"
}

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz (6 x 2808)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (8.70GB free)|
|Process Argv|--folder-uri file:///f%3A/Workspace/subgame/GameServer --crash-reporter-id 55d14156-e8c0-4fa3-bc84-a6541b7e069f|
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
lua-debug|act|1.53.0
Bookmarks|ale|13.2.3
highlight-line-vscode|cli|0.0.1
bracket-pair-colorizer-2|Coe|0.2.2
skynet-debugger|col|1.0.1
vscode-eslint|dba|2.2.2
code-runner|for|0.11.7
remotehub|Git|0.24.0
vue|jcb|0.1.5
svn-scm|joh|2.15.3
protobuf|kan|1.1.6
unity-code-snippets|kle|1.3.0
vscode-language-pack-zh-hans|MS-|1.64.7
csharp|ms-|1.24.0
data-workspace-vscode|ms-|0.1.1
remote-ssh|ms-|0.74.0
remote-ssh-edit|ms-|0.74.0
cpptools|ms-|1.8.0-insiders2
view-in-browser|qin|0.0.5
markdown-preview-enhanced|shd|0.6.1
luapanda|stu|3.2.0
unity-tools|Tob|1.2.12
unity-debug|Uni|3.0.2
vscode-icons|vsc|11.10.0
luaide-lite|wel|0.2.9
markdown-all-in-one|yzh|3.4.0
vscode-proto3|zxh|0.5.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392cf:30425750
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30442554
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstartedc:30433508
vsclayoutctrc:30437038
vsrem710cf:30416617
dsvsc009:30440023
pythonvspyt640:30442238
vsbas813:30436447
vscscmwlcmt:30438805
helix:30440343

```

</details>

**Comment by wlof202** [comment]
when i attach the other progress, show some error logs:
Starting inspector on 127.0.0.1:9229 failed: address already in use

**Comment by weinand** [comment]
After "attaching" the VS Code debugger to a node.js process, the node.js process is not automatically terminated when ending the debug session. The VS Code debugger just disconnects from node.js and lets it running.

If you then start another node.js process in debug mode, it will complain because the debug port is still open in the first node.js process.

In order to terminate the node.js process, you must press the "Alt" key when clicking on the Disconnect button:

![CleanShot 2022-02-23 at 11 57 35](https://user-images.githubusercontent.com/1898161/155306296-e79708c9-8d36-4472-ac61-57b6d7a5d8f5.gif)

**Comment by wlof202** [comment]
> 
I stopped(press the "Alt" key when clicking on the Disconnect button) the attach,
but it didn't work

**Comment by weinand** [comment]
@wlof202 and the "disconnect" icon is turning into a "stop" icon while pressing the Alt key?

**Comment by wlof202** [comment]
> 

yes, press "alt" is "stop" and release is "disconnect"

**Comment by wlof202** [comment]
@weinand i record a video
[https://www.aliyundrive.com/s/p7E2vo2AwGL](url)

**Comment by weinand** [comment]
@wlof202 the link does not work.
Please copy the video into the comment which makes github upload the video with a valid link.

**Comment by wlof202** [comment]
https://user-images.githubusercontent.com/8343782/155493701-e0bf4c1c-baf4-4096-bffd-59b0b5889b66.mp4

@weinand

**Comment by connor4312** [comment]
This is because we use `process._debugProcess` to force a process, by ID, to enter debug mode. We [cannot specify](https://github.com/nodejs/node/blob/7724e78e472b4462b75c6172d3fea7eed3a9b8c1/src/node_process_methods.cc#L335-L349) a port for this, so the first process you attempt to debug listens on the default port 9229. We try to signal the second process to enter debug mode, but port 9229 is in use, so it cannot and instead we attach to the process already listening on that port.

To avoid this, please launch processes on explicit different ports using `--inspect=<port number>`
