### ISSUE TITLE
Layout picker looks like a wrongly positioned dialog

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#143670]
Testing #143581

* F1 > Customize Layout

The picker sits at the quick pick position (I assume it's the same/similar code) but it looks like a dialog. It has title with string background and close command. That make it feel like it can be rearranged to a better location (which it cannot). Maybe its better to move the confirm/close button to the bottom

<img width="798" alt="Screen Shot 2022-02-23 at 09 30 03" src="https://user-images.githubusercontent.com/1794099/155284349-5d5aad01-c54a-4034-ab17-fd4a8cf71d19.png">

---

move Ok/Accept/Done to the bottom

<img width="798" alt="Screen Shot 2022-02-23 at 09 30 03" src="https://user-images.githubusercontent.com/1794099/155285049-5572a465-70a9-4a07-a8dc-e55e85730ba3.png">

**Comment by sbatten** [comment]
this is 100% using the quick pick api so we aren't trying to be different here. adding @TylerLeonhardt since this is more feedback about the quick pick options.

**Comment by TylerLeonhardt** [comment]
@jrieken would you feel differently if the input box (filter) was shown?

<img width="939" alt="image" src="https://user-images.githubusercontent.com/2644648/155368607-5cc3e0da-1560-40ef-8a0a-4f714201e32d.png">

(I'm not saying we should show the input box here, I'm just curious if the input box influences how you perceive the UI)

**Comment by jrieken** [comment]
Yeah, I guess it would make it look more familiar and better align with "normal" quick pick. I believe it's the `X` icon that's giving me dialog thoughts. The button combined with the double title bar style might be too much for me

**Comment by TylerLeonhardt** [comment]
Settings Sync dialog is another that doesn't use the input:
<img width="926" alt="image" src="https://user-images.githubusercontent.com/2644648/155377545-2692d465-84f4-4f6a-b498-8dd39eeb7c22.png">

**Comment by jrieken** [comment]
Tho, settings sync uses a different button, not the `X`

**Comment by TylerLeonhardt** [comment]
I actually really like the picker without the input box. It turns quick pick into a complete form replacer.

Settings Sync has the sign in & Turn off button. @sbatten, you _could_ follow what Settings Sync has done here and use a `Close` button with some helper text to the left.

thought, tbh, I like the simplicity of what we have today... we could get rid of the `x` but then the only way to get rid of the dialog is to hit ESC...

**Comment by sbatten** [comment]
I think some form of close is essential here. If others would prefer a big button with text, I'm open to it, but I also like the simplicity.

**Comment by misolori** [comment]
Is there anyway to allow the user to close the dialog by clicking outside of the quick pick? Or is that needed to keep the quick pick open when clicking around the layout configuration? I agree that the close button on here feels weird since it's not a dialog so trying to stick to the usual quick patterns feel better IMO.

**Comment by gjsjohnmurray** [comment]
> Is there anyway to allow the user to close the dialog by clicking outside of the quick pick?

I think that's intentional, and good. It allows me to interact with the rest of the window without losing the Customize Layout "dialog".

The X button doesn't bother me, but perhaps its tip should mention the <kbd>Esc</kbd> keyboard alternative:

![image](https://user-images.githubusercontent.com/6726799/155690582-961e012b-6a30-489f-ab99-199616209b83.png)

**Comment by jrieken** [comment]
In dialogs `X` usually does the same as the cancel option. This doesn't apply here and a labeled button saying something like "Ok" or "Done" is IMO the better fit

**Comment by TylerLeonhardt** [comment]
Maybe we need to spin up @daviddossett on this one now. The feedback is that this `Customize Layout`, which uses a quick pick under the hood, looks more like a dialog and it's positioned weirdly (to the top of the editor) and undraggable.

**Comment by TylerLeonhardt** [comment]
I think there was also a limitation where show/hiding something caused it to gain focus and that would dismiss the quickpick

**Comment by sbatten** [comment]
@gjsjohnmurray is pointing out the use case of the customize layout quick pick. The quick pick is an implementation detail of the the customize layout UX but the goal is to have something where you can play around with the layout and it is entirely mouse driven.

**Comment by daviddossett** [comment]
> but the goal is to have something where you can play around with the layout and it is entirely mouse driven.

I get that—my question is more around whether there is a real need to be interacting with both layers (workbench, layout quick pick) at the same time w/o dismissing the quick pick.

**Comment by sbatten** [comment]
yes, no, maybe -- focus is already being stolen from the quick pick by using any of the options. it would be very difficult to prevent this when toggling workbench parts. but, even if we could, its layout so you might decide to resize and such

**Comment by hbons** [comment]
Tried to use this and it's very confusing to me:

* Some rows act as radio buttons, some don't
  * Radio button rows use a checkmark and look too much like checkboxes
* When hovering rows in the first section, some get a "Show" icon, and some a "Hide" icon
* The blue right-aligned "group" label is being used as if it's a table column header
  * The "Visibility" group header moves aside on hover to show the hide/show icon
* Your eyes need to move between the far left and right sides of the picker to make sense of the logic. Specially here:
<img width="276" alt="image" src="https://github.com/microsoft/vscode/assets/103326/188cdeb7-dfcb-46aa-9fc9-a42cb43073c7">

This feature needs a rethink, and not be constraint by the features of a QuickPick list mode.

Back to the original issue:

Since the rows have mixed use that don't always make sense on their own, and the list is a fixed number, I don't think putting back the Filter bar makes sense. 

Not a fan of putting an OK button at the bottom. But putting one at the top right like @TylerLeonhardt suggests would make this look less like a window and it's an existing pattern. This also allows us to keep the "Reset to Defaults" button there.

**Comment by benibenj** [comment]
Closing as there is no plans to change this for the time being. Maybe we reconsider if there are changes to the quick pick API at some point
