### ISSUE TITLE
Markup cells invisibile when reopening files

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#143792]
Issue Type: <b>Bug</b>

* Open my endgame notebook
* Scroll to bottom
* Close the editor
* Open through quick pick again

<img width="2032" alt="image" src="https://user-images.githubusercontent.com/876920/155386223-30825838-fbdf-4e87-a9f2-1536c9317f91.png">

VS Code version: Code - Insiders 1.65.0-insider (Universal) (32456dc9e7d3194a94dd3ee0322ccf47e461d09c, 2022-02-23T05:27:54.628Z)
OS version: Darwin x64 21.3.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (0.09GB free)|
|Process Argv|--enable-proposed-api ms-vscode.vscode-notebook-history --enable-proposed-api vscode.notebook-editing --enable-proposed-api vscode.vscode-test-resolver --enable-proposed-api donjayamanne.kusto --enable-proposed-api donjayamanne.jupyterpowertools --enable-proposed-api rebornix.better-jupyter-errors --enable-proposed-api rchiodo.jupyter-tools --crash-reporter-id 1a907bbd-fa02-4595-81e0-63e1648afb31|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by mjbvz** [comment]
These items are not actually hidden but have the wrong top offset in this case

**Comment by mjbvz** [comment]
This seems to be caused by `createMarkupPreview` being invoked when the hidden cell is scrolled into view:

https://github.com/microsoft/vscode/blob/1d618b2df1cf08f0e3ab706353f0a8f6f1424795/src/vs/workbench/contrib/notebook/browser/notebookEditorWidget.ts#L2522

For some reason, `this._list.getAbsoluteTopOfElement` returns a wrong cell offset. In the case here, it returns a offset of something like 2600 while the actual offset is closer to `6600`

**Comment by mjbvz** [comment]
I think this code has always been computing the wrong offset. We just don't always see it as `showMarkupPreview` skips sending an update if the cell was already visible:

https://github.com/microsoft/vscode/blob/6db11fbf331e16eb59a7d81ec5905705331ab433/src/vs/workbench/contrib/notebook/browser/view/renderers/backLayerWebView.ts#L1035

@rebornix I pushed a potential fix copied from some other code. Can you please take a quick look and let me know if this looks ok? I think we should try consolidating this logic instead of having it copied in multiple places but I don't know enough about this area of the code  to say how to do this
