### ISSUE TITLE
Light HC theme missing watermark and keybindings hints

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#143765]
Testing #143425

- Close all editors
- The logo watermark and keyboard shortcuts are missing, this is what it looks like in HC dark:
<img width="493" alt="image" src="https://user-images.githubusercontent.com/323878/155372323-1f913537-3498-4e21-884e-326bffed21c5.png">

**Comment by daviddossett** [comment]
Dug into this a bit. It looks like there are two issues here:

First, we render different versions of the letterpress SVG depending on the theme type.
https://github.com/microsoft/vscode/blob/48010db276accb3e68d9be9bdc3d2c4220a69c43/src/vs/workbench/browser/parts/editor/editorGroupView.ts#L1805

Second, our theme types are limited to `dark`, `light`, and `hc`.
https://github.com/microsoft/vscode/blob/e102191a6ffdc4bfc572c538913f292314092e48/src/vs/platform/theme/common/theme.ts#L9-L13

@aeschli what do you think about splitting the hc types into something like `hc-dark` and `hc-light`? I can see how this could create problems elsewhere since we probably rely on that broad `hc` type for all sorts of overrides.

Another option could be to rely on on a different field like `theme.label`, although that has other drawbacks.

cc @isidorn @misolori for awareness on the type splitting question above.

**Comment by daviddossett** [comment]
In the meantime I think can get by with using token vars e.g. `fill:var(--vscode-foreground);` in place of the hardcoded `fill:white;` in `letterpress-hc.svg`.

**Comment by daviddossett** [comment]
Fixed missing keybinding hints and updated the HC letterpress color to use a fixed hex value since it doesn't look like we can dynamically update the SVG's theme vars when the theme is changed.

<img width="521" alt="CleanShot 2022-02-23 at 13 37 58@2x" src="https://user-images.githubusercontent.com/25163139/155412877-f27105e5-5e98-45b3-8eb7-e74d29585750.png">

**Comment by misolori** [comment]
@daviddossett don't forget the same file on distro for the branded icon versions if you haven't already gotten to it

**Comment by daviddossett** [comment]
Closing as fixed. Will create a separate issue for the theme type discussion.

**Comment by isidorn** [comment]
@daviddossett please ping me on that other issue. I think it makes `hc-light`, and `hc-dark` thought it might be quite some debt work. @aeschli would know best I think.
