### ISSUE TITLE
Enabling extensions in untrusted workspace

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode#143754]
As of now, to enable extension in  untrusted workspace, one needs to add extension id to the `extensions.supportUntrustedWorkspaces` user setting.

I wonder if this setting can be decomposed, so instead of listing every extension with their `supported` attribute, I just write extension ids into separate settings, like `extensions.supportedUntrustedWorkspaces`, `extensions.notsupportedUntrustedWorkspaces` and `extensions.limittedSupportUntrustedWorkspaces`.

Of course, I'd be simpler if extensions were updated to work with workspace trust, but I don't see much progress there.

**Comment by lszomoru** [comment]
Thank you very much for your feedback and apologies for not getting back to you on this until now. The setting was created as a "last resort" mechanism to empower users to add support for an extension in untrusted workspace due to the extension not being updated. We are not planning any changes to the schema of the setting at this point in time.
