### ISSUE TITLE
Terminal command decorations: Same command repeated gets no decoration

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#143707]
Testing #143433

1. Enable `terminal.integrated.shellIntegration.enabled`
1. Type a command, hit Enter
2. Type the same command, hit Enter

🐛 Every repeated execution after the first gets no decoration

<img width="251" alt="image" src="https://user-images.githubusercontent.com/22350/155307728-8f0f12ea-f48d-41a0-b82d-2452a14f5fb3.png">

**Comment by joaomoreno** [comment]
Bash, straight out of a fresh Ubuntu 18.04 installation.

**Comment by Tyriar** [comment]
This is happening because bash's `history` on Linux seems to behave differently and merge entries unlike on macOS.

bash v5.1.4 on wsl:

![image](https://user-images.githubusercontent.com/2193314/155364685-e3eb530f-25f3-4285-92fd-58906ccd31d9.png)

bash v5.1.8 on macOS:

<img width="386" alt="Screen Shot 2022-02-23 at 8 40 14 am" src="https://user-images.githubusercontent.com/2193314/155365081-8e1f85aa-df5f-42d4-b2f5-95f722c448ff.png">

**Comment by Tyriar** [comment]
I worked around the issue so it should be fixed, it will still fail when the exit code changes which should be a very rare occurrence. That's a more invasive change which we'll handle next month as the shell scripts are quite fragile.
