### ISSUE TITLE
UX of extensions menu

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#14384]
Testing #14288

IMHO this menu has turned into a monster and as a user I cannot work with it anymore. There are all the concepts cramped into a single menu.

IMHO working with extensions involves two operating modes (similar how developing (editing files) and SCM (git) are different operating modes)
1. Finding & installing extensions
2. Managing installed extensions

IMHO these two are distinct activities and they should be treated distinctly in designing the experience.

![image](https://cloud.githubusercontent.com/assets/5047891/19680686/062178ea-9aa7-11e6-89dd-7b2305963ee7.png)

**Comment by octref** [comment]
I agree. Atom does this very well by separating Install from Packages

![image](https://cloud.githubusercontent.com/assets/4033249/19697692/38a030e6-9aa1-11e6-8c99-c3aa89eb5a44.png)

Also not allowing user to sort their installed extensions feels weird. Feel more natural if this option is not shown at all instead of disabled.

**Comment by joaomoreno** [comment]
Global Enable and Disable actions should leave the menu and only exist as global commands, since they actually refer to the whole set of installed extensions, and not just the visible ones, as it appears to be.
