### ISSUE TITLE
Markdown baseURI doesn't seem right when baseUri is a https link and not a file

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#143813]
Testing #143647

Using the markdown string below it drops the `1_64`.
```ts
const md = new vscode.MarkdownString(`[Cell fold hint](./cell-fold-hint.png)`);
md.baseUri = vscode.Uri.parse("https://github.com/microsoft/vscode-docs/tree/main/release-notes/images/1_64");
```

Using the markdown string below it drops everything but `https://github.com`.
```ts
const md = new vscode.MarkdownString(`[Cell fold hint](/cell-fold-hint.png)`);
md.baseUri = vscode.Uri.parse("https://github.com/microsoft/vscode-docs/tree/main/release-notes/images/1_64");
```

**Comment by mjbvz** [comment]
I believe this is the expected behavior in both cases. 

In the first one, we consider the `1_64` to be a file name. You can fix this by instead ending the baseUri with a `/`

In the second case, the uri starts with  `/` so it is not a relative link . baseUri only applies to relative paths

I used the following html to test and believe we align with the html behavior in both cases:

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <base href="https://github.com/microsoft/vscode-docs/tree/main/release-notes/images/1_64">
</head>
<body>
    <a href="/abs-example">abs</a>
    <a href="./rel-example">rel</a>
</body>
</html>
```

Let me know if you think the docs could make these points more clear
