### ISSUE TITLE
TypeScript / JavaScript hover provider are enabled even though validate.enable is set to `false`

### ISSUE THREAD

**Issue by christianvuerings** [microsoft/vscode#143842]
- VS Code Version: 1.64.2
- OS Version: Mac OS X

**Steps to Reproduce**:

1. Set `javascript.validate.enable` to `false` and `typescript.validate.enable` to `false`
2. Create a file with a `.ts` or `.js` extension
3. Save the file with the following contents:

    ```ts
    const foo: string = 'bar';
    ```
4. Hover over `foo`

**Expected outcome**:
No hover gets shown

**Current behavior**:
Hover shows

<img width="227" alt="Screen Shot 2022-02-23 at 6 07 32 PM" src="https://user-images.githubusercontent.com/127199/155443981-6ed37eac-84ce-45b4-9716-0bf3f296bfcf.png">

#### What is the current workaround?

The only way we have found to disable the hover provider is to disable the built-in `vscode.typescript-language-features` extension

#### What's the issue with the workaround?

We use Flow instead of TypeScript for our projects and it's confusing for developers to manually have to disable a built-in extension to not see double type information on hover:

<img width="387" alt="Screen Shot 2022-02-23 at 6 15 41 PM" src="https://user-images.githubusercontent.com/127199/155444553-6ac2bda2-3a7e-4cb8-b66c-b8a53772aff3.png">

The top one is from TypeScript, the bottom one from the Flow VSCode extension: https://github.com/flow/flow-for-vscode

**Comment by mjbvz** [comment]
The validate settings control error reporting. I don't having them control hovers too makes sense

If you're using flow, our suggestion is to disable the built-in js/ts extension entirely because we cannot guarantee any intellisense features will work with Flow. The flow extension needs to provide its own replacement functionality built specifically for Flow code

**Comment by christianvuerings** [comment]
> If you're using flow, our suggestion is to disable the built-in js/ts extension entirely because we cannot guarantee any intellisense features will work with Flow. The flow extension needs to provide its own replacement functionality built specifically for Flow code

@mjbvz is there a way to do disable the js/ts extension programmatically? We already recommend to turn disable the extension but that's a manual step which is often forgotten.

**Comment by mjbvz** [comment]
Not that I'm aware of

And yes the experience is unfortunate but the root cause is Flow using the standard `.js` file extension for code that is not standard javascript. If the Flow extensions for VS Code contribute their own language mode, you could instead try mapping all `js` files to that with the `files.associations` setting, however I don't think either of the two main Flow extensions actually do this

**Comment by christianvuerings** [comment]
@mjbvz good to know - thank you.
