### ISSUE TITLE
Too many editor group layout actions

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#14382]
Refs #14016

1. Command pallete > editor layout
2. Notice there are 3 actions for this simple thing!

I understand that you did that because of some limitations we have with updating the label of an action. But I do not think that is enough motivation to have 3 actions when I only see a use scenario with the toggle action.

My suggestions is just to have a single action with the following name:
'Toggle Editor Vertical/Horizontal Layout'
That title I would also use in the view menu

![screen shot 2016-10-25 at 11 26 49](https://cloud.githubusercontent.com/assets/1926584/19680547/69c4472a-9aa6-11e6-8de3-5b6002529321.png)

**Comment by bpasero** [comment]
@isidorn the motivation is not to have a workaround for the issue that I cannot update the label, it is because some people might want to assign a keybinding to the one or the other action and I still want to support that.

Also we need this for the SQL team that wants to switch to horizontal layout.

**Comment by isidorn** [comment]
@bpasero I am not convinced that people actually want a keybinding just to go to vertical even if they are in the vertical. IMHO people just want a keybinding to change the layout - otherwise why would they be intrested in that action

I understand that the SQL team wants to use this programmatically - that makes sense. Though you could also pimp up your toggle action to take an argument, so the API could pass horizontal or veritcal and if nothing is passed it toggles. Just an idea.

**Comment by bpasero** [comment]
![image](https://cloud.githubusercontent.com/assets/900690/19681594/405ee242-9aaa-11e6-9bac-d538bfb33194.png)

**Comment by octref** [comment]
@gregvanl , can you update the release note accordingly?

The following are no longer accurate because of this change.

---

To enable horizontal layout, set the new workbench.editor.sideBySideLayout setting to horizontal.

There are more places where you can quickly enable this layout:

The View menu Horizonatal/Vertical Editor Layout.
The Command Palette Toggle Vertical/Horizontal Layout
An action in the header of the OPEN EDITORS view
There is also a keybinding (kb(workbench.action.toggleEditorLayout)) to quickly switch between the two layouts.

**Comment by octref** [comment]
@gregvanl And btw it should be editor **group** layout, not editor layout.

**Comment by bpasero** [comment]
I just did, sorry forgot the docs!
