### ISSUE TITLE
Terminal: run recent command order is flipped with multiple windows

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/vscode#143847]
Testing #143430

Session where commands got added to the history:

![image](https://user-images.githubusercontent.com/3840081/155451877-d1c05348-6b46-4abb-98b4-17dc3f6ad145.png)

Later session:
![image](https://user-images.githubusercontent.com/3840081/155452040-de0fdf39-bfcd-45f4-95a9-78b2c11dea61.png)

The `tree` command was run in two different locations and was last run. But in the previous session list it does not have it at the top. The order is not the same.

**Comment by Tyriar** [comment]
Previous session missing cwd is by design, we may choose to add it later when looking into autocomplete but for now it's meant to act more like an alternative to ctrl+r which doesn't track cwd on any shell. Additionally, if we tracked it we'd need to worry about keeping track of every cwd we track as only tracking the last cwd for a command feels a bit odd.

Will look into the order.

**Comment by rzhao271** [comment]
Step 7 fails for me. For step 5, I tried both opening a completely new window, and simply creating a new tab:
![Screencap](https://user-images.githubusercontent.com/7199958/160010353-49847427-0b8f-47c9-8f45-b58bf2518ffd.gif)

**Comment by Tyriar** [comment]
@rzhao271 I can repro but only if I open run recent very quickly, too quickly for the terminal to get classified as a pwsh which is a prerequisite to pulling in the history as it's segregated by shell type. Making as verified again, remove if I misunderstood.
