### ISSUE TITLE
Introducing a default workspace when opening a single folder may be confusing

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#143856]
Testing #143456

It took me a while to notice that opening a folder on insiders.vscode.dev was actually adding the folder to a default workspace. As a VS Code desktop user, I would not have expected the folder to be parented to a workspace.

I was also surprised that opening another folder adds the new folder to the workspace instead of closing the previous folder and opening just the new folder.

The difference in behavior and introducing the workspace concept when opening a single folder may be confusing for current VS Code desktop users.

I also looked around for a Close Folder command and finally realized I needed to right-click on the folder node and run Remove Folder from Workspace to close the folder

**Comment by bpasero** [comment]
This is unfortunately a technical limitation we had to workaround with the approach we use now. The issue is:
* opening a folder currently requires a window reload in both desktop and web (in other words, opening a workspace is not possible without a reload)
* opening a local folder from the web needs explicit user intent, so we cannot ask the user to open a folder and then reload the window
