### ISSUE TITLE
Open Remote Repository button shown twice in insiders.vscode.dev

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#143858]
Testing #143456

This has probably already been logged but there are two "Open Remote Repository" buttons displayed on the empty File Explorer

![image](https://user-images.githubusercontent.com/12818376/155468739-cb1b0ed1-89b5-4e6f-827b-fc1dbaa3324e.png)

This might be related to GitHub Repositories (Insiders) since if you click either one of the buttons, there is a notification displayed once:

![image](https://user-images.githubusercontent.com/12818376/155468896-0e065978-2a1c-48d3-97b5-15478d821202.png)

**Comment by joyceerhl** [comment]
@gregvanl Did you ever install RemoteHub Insiders on desktop at some point? That extension has been deprecated and is no longer bundled with insiders.vscode.dev since the January release. Instead we now bundle the pre-release edition of the GitHub Repositories extension.

You should be able to fix this issue by going into the extensions panel and uninstalling the GitHub Repositories (Insiders): extension `github.remotehub-insiders`.

**Comment by gregvanl** [comment]
@joyceerhl Yep, that was it. Once I uninstalled `github.remotehub-insiders`, my Explorer was tidy again. Thanks

**Comment by sandy081** [comment]
Yes, settings sync will auto install it because we do not know included this extension in our pre-release migration list.

**Comment by joyceerhl** [comment]
Closing since uninstalling RemoteHub Insiders resolves the issue and we have deprecated the RemoteHub Insiders extension in favor of RemoteHub pre-releases. A few releases from now we will unpublish RemoteHub Insiders from the marketplace.
