### ISSUE TITLE
Undo/Redo of cell edits is difficult to reason about, if not broken.

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode#144102]
This video shows text in another cell being undone even though focus is in a different cell. Doesn't seem to matter whether "Notebook: Undo Redo Per Cell" is enabled or not
 
![Recording 2022-02-28 at 08 41 07](https://user-images.githubusercontent.com/11685408/156022750-689cf703-423d-4f2c-a4a8-2a2c81388393.gif)

This video shows that after a cell as been added and text has been added to it, Ctrl-Z can be used to remove it, but it cannot be redone. You've lost anything typed in that cell permanently.

![Recording 2022-02-28 at 08 48 09](https://user-images.githubusercontent.com/11685408/156023639-c379aeef-601f-4f56-ac27-f56c6e04ae35.gif)

**Comment by greazer** [comment]
Marking as regression as I can't seem to figure out whether the "per-cell" setting is working the way it's intended or not. Suspecting a bug.

**Comment by greazer** [comment]
Actually it appears that I may have disabled the "per-cell" setting a long time ago and didn't realize it. This may explain both behaviors above. I didn't realize that after changing that setting VS Code must be reloaded for the setting to take effect.

**Comment by greazer** [comment]
So removing "important" and "regression" for now. Let's just review what the behavior is that we want. It does seem problematic that if you have the setting off, that it doesn't seem possible to restore a cell you may have accidentally deleted. When the setting is on, Ctrl+z seems to work as expected.

**Comment by greazer** [comment]
After internal discussion, re-marking as important. It's a data loss scenario if you have cell-level undo off.

**Comment by IanMatthewHuff** [comment]
With Cell Undo / Redo on (this is the default):

- Undoing and redoing text per cell works as expected
  - Yes, with my testing
- Undoing and redoing add / remove of cell works as expected
  - No, see bug 3
- Undoing remove of cell via delete button
  - No, see bug 4

With Cell Undo / Redo off: 

- Undoing and redoing text per document works as expected
  - No, see bug 1
- Undoing and redoing add / remove of cell works as expected
  - No, see bug 2
- Undoing remove of cell via delete button
  - No, see bug 4

Bugs:

- 1 Two cells in document. Changed from per cell to document mode. Typed in Cell A. Moved to the second cell, hit Undo. Instead of undoing the text, it blew away the second cell. Typing Redo did bring it back. I expected the typing in Cell A to be undone. 
  - Note, this bug I don't see after reloading the window. Might be that the setting change mid flow got the stack into a funny state?
- 2 Two cells in document. Shift-enter to run and add a new cell. Type in new cell. Ctrl-Z makes the typing go away and eventually the cell. When the cell is fully removed, redo will not restore it, so the typing is lost.
  - Note, I can only replicate this will per cell turned off. With per cell turned on I first need to not be on the current cell to make it go away via Undo. But in that case I can make it go away with Undo and the text is restored with Redo.
  - 3 However with per Cell on the cell + text does come back, but when it comes back it comes back without the per cell undo redo stack with per cell turned on: https://github.com/microsoft/vscode/issues/143123
- 4 When removing cell with the delete button, it cannot be restored with undo. This is true with either setting on.

This is what I saw in my first pass. My personal ranking in importance would be like so

1. Bug 4 - Clear data loss. In both modes a cell is deleted and I can't get it back and the info in it. Easy to do and damaging. Effects both modes.
2. Bug 2 - Also clear data loss. I find this as a bit less important as I can only repro it with perCell off and I need to Ctrl-Z through the cell to get to the cell loss case so I've already removed what I typed in to the cell to get here.
4. Bug 3 (#143123) - Data loss here, but the data loss is not the actual code just the undo redo stack. So I'd vote for less important.
5. Bug 1 - I only reproed this when changing the perCell setting without a reload so an issue, but lesser importance.

**Comment by IanMatthewHuff** [comment]
Some related issues:
#133026
#143123

**Comment by IanMatthewHuff** [comment]
Note I'm going to use this issue specifically to resolve the issue where with perCell mode turned off you cannot restore a cell that was deleted with undo.

The only specific scenarios in this fix are as follows:
1. Open a notebook document
2. Create a new cell (type something in it if you want)
3. Delete the cell using the delete button in the toolbar
4. Cmd+Z (Run Undo) from a previous cell in the file
5. Previously the cell would not be restored, now it will be

Scenario 2:
1. From the last cell in a notebook document shift-enter to run the cell and create a new cell
2. Type some word in the new cell
3. Start using Undo in that cell, it should walk back the words typed and eventually delete the cell
4. Now start pressing Redo, it should restore the cell to the document then restore the words typed
5. Previously the cell would not be restored.

**Comment by rebornix** [comment]
@IanMatthewHuff thanks for the detailed investigation, they are insightful! 

For bug 1, you are correct that flipping the setting messed up with the undo/redo state. We register `registerUriComparisonKeyComputer` based on the setting https://github.com/ianmatthewhuff/vscode/blob/afcebfa6ae642564d43165e1e72375361e2338ed/src/vs/workbench/contrib/notebook/browser/notebook.contribution.ts#L217-L218 which is not updated when we flip the setting. We might want to dispose it and register a new one when the setting changes.

For bug 2, with your fix in, I can't reproduce it with the per cell setting off. Not sure if it's similar to bug 1.

For bug 3, your comment https://github.com/microsoft/vscode/issues/143123#issuecomment-1071790324 is accurate. It's like a document and we don't persist them usually when a resource is gone. I wonder if we should fetch and "save" the undo/redo stack for the cell on the cell deletion element in the undo stack.

**Comment by IanMatthewHuff** [comment]
Reopening to cover the issues with flipping the setting. I'll close after that fix and #143123 will cover the bigger issue on persisting undo / redo per cell after delete.

**Comment by rchiodo** [comment]
/verified?

Still not sure this is working. Is per cell undo supposed to allow undo to affect other cells?

Repro:
1. Switch to per cell undo
2. Type in first cell
3. Type in second cell
4. CTRL+Z

Expected it to only affect the current cell with focus.
Actually it removes the typing in the first cell.

**Comment by rchiodo** [comment]
Otherwise seems to behave more like I'd expect.
