### ISSUE TITLE
after running terminal: clear, the first decoration isn't rendered

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#144142]
1. run some commands
2. run `terminal: clear`
3. 🐛  no placeholder decoration for first command/prompt line

**Comment by meganrogge** [comment]
this is because command started doesn't get fired after the clear happens

**Comment by mjbvz** [comment]
Hm I think I'm still seeing this issue on MacOS and zsh and bash with the latest insiders:

<img width="420" alt="Screen Shot 2022-03-23 at 5 17 45 PM" src="https://user-images.githubusercontent.com/12821956/159817334-58c4cf90-9f77-46d6-a34f-044e62deef4c.png">

Here I'd expect an error icon on the first line since the command does not exist

**Comment by Tyriar** [comment]
@mjbvz we're tracking this specific one where the completed decoration doesn't end up showing up in https://github.com/microsoft/vscode/issues/145148
