### ISSUE TITLE
input typed during a buffer clear is incorrectly positioned and sometimes duplicated

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#144292]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.65-insider
- OS Version: Windows 11

Steps to Reproduce:

1. Ctrl+K to clear terminal
2. Start typing
3. :bug: a newline gets inserted (seemingly always after the first two characters typed), and the two characters typed so far gets partially rendered twice, but the buffer seems to contain the right contents (not duplicated):

![image](https://user-images.githubusercontent.com/30305945/156475503-806c9320-91ac-4e74-ae1a-f446f9dd7d5c.png)

![image](https://user-images.githubusercontent.com/30305945/156476032-cf908ee5-78df-41ce-88e9-8d214990c760.png)

I have shell integration enabled and am using pwsh. This happens very frequently for me now that I use Terminal: Clear.

**Comment by meganrogge** [comment]
**with or without shell integration enabled**

On macOS/pwsh, If I type immediately after running `Terminal:Clear`, then I can reproduce multiple new lines getting added before the input appears. I don't see duplicated contents though. 

![Screen Shot 2022-03-02 at 8 30 10 PM](https://user-images.githubusercontent.com/29464607/156484787-4fefa862-5559-451e-8034-c7eb63d8bf16.png)

I suspect this is because `Terminal: Clear` refreshes all of the rows in the buffer, so if you interrupt that with input before the cursor position has been reset, the data will be written at that position. 

Perhaps input handler parsing should be paused while a clear/refresh is happening?

**Comment by meganrogge** [comment]
Can repro the duplicate commands in the xterm demo by writing to the terminal within the clear call here 

https://github.com/meganrogge/xterm.js/blob/e75b47ca015addc198ee194aa52306903a42d0b8/src/browser/Terminal.ts#L1310-L1314

**Comment by meganrogge** [comment]
upstream issue:

https://github.com/xtermjs/xterm.js/issues/3672

**Comment by Tyriar** [comment]
This is actually due to conpty and there's nothing we can do about it: https://github.com/microsoft/vscode/issues/75141
