### ISSUE TITLE
Can't save everything, and Can't close vscode application

### ISSUE THREAD

**Issue by biduone** [Microsoft/vscode#14436]
- VSCode Version: Code - Insiders 1.7.0-insider (5bafcdb3d67b29b1f4667a3f497ac05a41dde667, 2016-10-25T06:11:16.069Z)
- OS Version: Windows_NT ia32 10.0.14931
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.0.18|
|vscode-javascript-snippet-pack|akamud|0.1.5|
|path-intellisense|christian-kohler|1.1.0|
|vscode-icons|robertohuertasm|3.0.6|
|html-css-class-completion|Zignd|1.0.3|

---

Steps to Reproduce:
unknow, just can't save ,can't close when edit some file

Problem:

0. With banner tip "Error: canceled"
1. Can't save everything
2. Can't close vscode application

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by tungvn** [comment]
I have this bug on my VSCode 1.6.1.
Sometime I edit my CSS file and I can not save anything until I restart VSCode.

**Comment by jrieken** [comment]
@tungvn Same question for you: https://github.com/Microsoft/vscode/issues/14436#issuecomment-256041483

**Comment by biduone** [comment]
Ok, I will try to disable extensions

**Comment by tungvn** [comment]
This situation happens occasionally, especially when editing the CSS file. It's hard to describe each step to reproduce.
I currently disable extensions and let you know more info later.

**Comment by bpasero** [comment]
@jrieken are we understanding how it is possible for an extension to break saving? can we add more safe guards to prevent this from happening in the future?

**Comment by jrieken** [comment]
@bpasero From the comments I don't read that this is caused by an extension or not showing without extensions enabled. It seems to be a sporadic issue according to https://github.com/Microsoft/vscode/issues/14436#issuecomment-256228361. 

Also, to my knowledge none of the extensions listed [here](https://github.com/Microsoft/vscode/issues/14436#issue-185115254) run anything on save. There is vscode-icons which has the potential to wreck everything but unsure if that is the issue.

**Comment by bpasero** [comment]
Got it. The fix for people seeing this is to disable extensions.

**Comment by tungvn** [comment]
Hmm, I tried to disable extensions and this situation still happened.

Step to reproduce:
- Open CSS file (I didnt try with other format)
- Constantly edit, delete text and save it
- Bug found =.=

**Comment by biduone** [comment]
I  uninstalled all extensions  of VScode, but  this situation still happened when edit css file. At this moment,I cant't shut down VScode application in any way , only destroy it in windows task manager.
![err1](https://cloud.githubusercontent.com/assets/2018001/19797596/bb8f0b74-9d1e-11e6-8c97-1980b6b8f86f.png)
