### ISSUE TITLE
keychain failed with error 'Encryption failed'

### ISSUE THREAD

**Issue by C-distin** [microsoft/vscode#144323]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.64.2
- OS Version: Windows 11

Steps to Reproduce:

1. Tried logging into github account for settings sync
![Get Started - Visual Studio Code 3_3_2022 4_11_03 PM (1)](https://user-images.githubusercontent.com/83829844/156607810-0f122632-a1ba-4c67-93b6-50eb1071de65.png)

**Comment by TylerLeonhardt** [comment]
Can you provide the contents of the GitHub Authentication output pane:
![image](https://user-images.githubusercontent.com/2644648/128087382-c706864f-7005-4a2e-878b-662c69c4457e.png)
(like the picture, except GitHub instead of Microsoft)

And also anything that shows up in Dev Tools:

* ctrl + shift + P
* "Dev Tools"

**Comment by C-distin** [comment]
![Get Started - AirBnB_clone_v2 - Visual Studio Code 3_10_2022 11_09_49 AM](https://user-images.githubusercontent.com/83829844/157650794-cc729884-dd84-4948-95c3-9183c21f975b.png)
![Get Started - AirBnB_clone_v2 - Visual Studio Code 3_10_2022 11_13_16 AM](https://user-images.githubusercontent.com/83829844/157650801-7e36e45d-b853-48bc-9877-0815dcdba398.png)

**Comment by C-distin** [comment]
I have been able to solve it

**Comment by C-distin** [comment]
There was a credential manager error

**Comment by TylerLeonhardt** [comment]
@C-distin could you give me some more details so I can help future folks who end up in this state?
