### ISSUE TITLE
VSCode overrides/hijacks git credential manager configuration

### ISSUE THREAD

**Issue by johnterickson** [microsoft/vscode#144420]
Issue Type: <b>Bug</b>

I am running WSL2 and I have Git configured to use Windows GCM:
```
john@jerick-surface:~/jray$ git config -l | grep -i cred
credential.helper=/mnt/c/Program\ Files/Git/mingw64/libexec/git-core/git-credential-manager-core.exe
```

When using a normal terminal window everything works fine.  However, in the VS Code terminal, `git push` causes a VS Code popup asking me to auth? 

1. The terminal should work as the terminal.
2. VSCode should leverage GCM to authenticate and no thave its own sideband auth mechanism.

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Remote OS version: Linux x64 5.10.60.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (4.75GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/home/john/jray --remote=wsl+Ubuntu --crash-reporter-id 1428ac7b-4063-474a-857e-fc96f3453788|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.60.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2111)|
|Memory (System)|7.73GB (4.17GB free)|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-wsl|ms-|0.64.2
svg-preview|Sim|2.8.3
pestfile|xor|0.2.0
rust-analyzer|mat|0.2.948
java|red|1.3.0
vscode-lldb|vad|1.6.10
vscodeintellicode|Vis|1.2.17
vscode-java-debug|vsc|0.38.0
vscode-java-dependency|vsc|0.19.0
vscode-java-pack|vsc|0.21.0
vscode-java-test|vsc|0.34.0
vscode-maven|vsc|0.35.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392cf:30425750
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30433507
vsclayoutctrc:30437038
vsrem710:30416614
dsvsc009:30440023
vsbas813:30436447
vscscmwlcmt:30438805
helix:30440343
vscaat:30438848

```

</details>

**Comment by vtbassmatt** [comment]
👋 hi VS Code team. I'm the product manager for [GCM](https://github.com/GitCredentialManager/git-credential-manager) over at GitHub. We'd be happy to work with you to find a way to make this a better experience for GCM users. GCM covers a very wide variety of auth scenarios for Git users, and it seems silly to make you to replicate all those behaviors.

**Comment by mjcheetham** [comment]
It looks like this integration can be disabled in VS Code's config:

```json
{
    "github.gitAuthentication": false,
    "git.terminalAuthentication": false
}
```

The first setting being for GitHub account integration specifically, and the second being for integration with the integrated terminal window.

What is wrong with the default experience that means `true` is the default option? I can imagine there'd be a problem if someone was not using the default Git credential helper (GCM) on Windows, or on Mac/Linux where there's typically no default with an enhanced UX like GCM.

Is there a way to either recommend GCM when it's not configured, or otherwise only set this default to `true` if GCM is not set as the credential helper?

FWIW GCM also supports Azure DevOps, Bitbucket & onprem/DC, GitHub & GHES, (and soon) GitLab. It also has experimental support for things like WAM/Windows broker integration, and some amount of token cache sharing with tools like "full-fat" VS and Azure PowerShell.

**Comment by betamos** [comment]
Spent a couple of hours triaging this for my own purposes, on OSX in my case, and I'm a bit frustrated simply because this was so obscure and implicit. Apologies if this frustration shines through – I'm genuinely trying to help finding a better solution for everyone here, including all the people who like the existing flow.

I do **not** want my IDE to implicitly hijack my git configuration, especially not authentication and especially not terminal-based authentication. I've explicitly set up git to work with public key SSH using the SSH agent of my OS (my git config contains `credential.helper=osxkeychain`). Unless I'm mistaken, VSCode _overrides_ my preference without telling me, asking to sign in with Github. It took me a while to track down that VSCode was the culprit (in my case because git was invoked implicitly by `npm`), and judging by the Stack Overflow posts around this issue, I'm not alone.

Now, even if I was sold on this credential manager, _I'd still want this to be explicit_. VSCode only injects their credential manager within VSCode's own terminal. What happens when you switch to a regular terminal? Auth would suddenly stop working or work differently. Now I have to figure out how I make the credential manager work outside of VSCode. Wouldn't it be much less confusing to just offer to install it in the first place?

It was easy to disable, (see comment above), but the point here is that VSCode never tells me about it, so I have to do the work to triage it. At the very minimum, please provide documentation (or a link to it) during this hijacked flow. These docs should include how to disable it.

**Comment by lszomoru** [comment]
The git authentication mechanism implemented in VS Code is done [by overriding](https://github.com/microsoft/vscode/blob/35fe695c8029fde64ffe6b9341a48d934865f262/extensions/git/src/askpass.ts#L78-L79) the `GIT_ASKPASS` environment variable. Based on [the git credentials documentation](https://git-scm.com/docs/gitcredentials), credential helpers (ex: Git Credential Manager) takes precedence over the `GIT_ASKPASS` environment variables. 

I have been able to validate this by installing Git for Windows (default installation options) and running `git clone` from a terminal, the VS Code integrated terminal, and executed the `Git: Clone` command in VS Code. I all these three scenarios, the authentication dialog from GCM was shown confirming that a configured credential managers take precedence over the built-in git authentication mechanism. Having said that, last milestone we taken a pull request to add a new setting, `git.useIntegratedAskPass` to completely disable the git authentication mechanism in VS Code.

@johnterickson, I have tried to reproduce the issue that you are describing with WSL without any luck. In my case, GCM was always invoked independent whether I ran the command from the a WSL terminal or from the VS Code integrated terminal. My hypothesis is that when you run `git push` from the integrated terminal, there is a failure to invoke GCM and we fallback to using the built-in git authentication mechanism. Could you please run the following steps both in the terminal as well as in the VS Code integrated terminal and share the output (feel free to redact sensitive information):
1. Set the `GIT_TRACE` environment variable to `"1"`
2. Execute a `git push` command, and save the produced log

@betamos, I would love to learn more about the issue that you are running into. Given the fact that you have explicitly set the `credential.helper` setting, I would not expect git authentication related code path within VS Code to be executed. Could you please share more about your configuration, as well as the steps that you have performed to resolve the issue?

**Comment by johnterickson** [comment]
@lszomoru good news is that I can no longer repro! Either some was fixed or something had been misconfigured on my side.

[Defaults](https://code.visualstudio.com/docs/getstarted/settings#_default-settings):
```
  // Controls whether to enable VS Code to be the authentication handler for git processes spawned in the integrated terminal. Note: terminals need to be restarted to pick up a change in this setting.
  "git.terminalAuthentication": true,
  // Controls whether GIT_ASKPASS should be overwritten to use the integrated version.
  "git.useIntegratedAskPass": true,
  // Controls whether to enable automatic GitHub authentication for git commands within VS Code.
  "github.gitAuthentication": true,
```

With above 3 default values:
```
john@jerick-hpz440:~/jray$ git config -l | grep -i cred
credential.https://dev.azure.com.usehttppath=true
credential.helper=/mnt/c/Program\ Files/Git/mingw64/libexec/git-core/git-credential-manager-core.exe
john@jerick-hpz440:~/jray$ export GIT_TRACE=1
john@jerick-hpz440:~/jray$ echo $GIT_ASKPASS 
/home/john/.vscode-server/bin/dfd34e8260c270da74b5c2d86d61aee4b6d56977/extensions/git/dist/askpass.sh
john@jerick-hpz440:~/jray$ git push
15:10:56.722315 git.c:439               trace: built-in: git push
15:10:56.722592 run-command.c:663       trace: run_command: GIT_DIR=.git git-remote-https origin https://github.com/johnterickson/jray.git
15:10:56.982191 run-command.c:663       trace: run_command: '/mnt/c/Program\ Files/Git/mingw64/libexec/git-core/git-credential-manager-core.exe get'
```

**Comment by lszomoru** [comment]
@johnterickson, thank for the update. Glad to hear that the issue has been resolved.
