### ISSUE TITLE
Code formatting for multiple languages in one file

### ISSUE THREAD

**Issue by rjgamer** [Microsoft/vscode#14447]
Hi,

this is a feature request and not an issue.

Please give code formatting for multiple languages in one file. As example: If you are having HTML and PHP code in a php-file, then you won't get formatted HTML code and you have to format your HTML code manually. 

As solution, it would be nice to associate a extension to multiple languages in the settings:
`"files.associations": {
   "*.php": ["php", "html"]
}`

Thanks and best regards!

**Comment by jrieken** [comment]
This is the nested mode story - unsure where @aeschli and @alexandrudima will eventually land on this but work has already started

**Comment by aeschli** [comment]
The current story is that for a PHP file, the PHP formatter has to deal with the html content and format it.
Generic solutions are difficult and will result in bugs due to lack of understanding on how the two languages play together. Can the embedded content be indented? Can new lines be added? Most of the time only the main language has an understanding of that.

So if you miss html formatting in PHP, file an issue against the provider of the PHP formatter.
