### ISSUE TITLE
Extension is in odd disabled / enabled state when trying to enable an extension on a VS Code version that does not support it

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode#144444]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.66-insiders
- OS Version: macOS monterey

This is a bit tricky as I'm not sure how to re-engineer this situation for the repro. But the repro is as follows.

1. VS Code Insiders 1.65
2. Install the .NET Interactive extension (version 310011 targets 1.65-insiders)
3. Disable the extension
4. VS Code Insiders updated to 1.66
5. Attempt to enable the .NET Interactive extension (note at this point there is no version that targets 1.66-insiders on the market)
6. Extension is now in a state where it cannot be enabled or disabled and I don't see an indication that the reason it's disabled is the engine version mismatch

<img width="962" alt="image" src="https://user-images.githubusercontent.com/812783/156849327-e46fe6d5-46df-44cb-8b4a-238b306294e6.png">

<img width="994" alt="image" src="https://user-images.githubusercontent.com/812783/156849348-41dc698e-a343-4621-a3fc-6977aae862d4.png">

**Comment by sandy081** [comment]
It seems the enabled extension is not compatible with the current VSCode engine and hence it is not loaded. Enablement actions are disabled because none of these actions are useful in this context. I think it would be useful to inform user that this extension cannot be enabled/disabled because it is not compatible.

**Comment by sandy081** [comment]
After further investigation, the root cause of this issue is that Extension UI and Extension Host (Runtime Extensions) are not in sync. UI expects that this extension is enabled and supposed to be running and Extension Host is correctly not running this extension because of engine compatibility. There are more such scenarios where these two components do not agree with each other.

From Day 1, these components are not aligned and each scan extensions in its own way. I am planning to align these by unifying extension scanning. This will make UI in sync with Runtime.

CC @alexdima
