### ISSUE TITLE
Auto-Complete not working in snippets

### ISSUE THREAD

**Issue by Nobody-loses-like-trump** [microsoft/vscode#144496]
Issue Type: <b>Feature Request</b>

if you make a snippet then Auto-Completion does not work in a snippet, and it is very annoying

and also an Auto-Completion for the snippets should be added EXAMPLE: if the snippet is named "print" then I do not need to write the whole "print" I can just write "pr" and a suggestion for "print" should pop up

---
If you can fix this issue You can also enable the old snippets https://github.com/microsoft/vscode-python/blob/2020.12.424452561/snippets/python.json

---
and 1 more Feature Request is to make the (Ctrl + F) in VS code more like that of Atom
in VS code the search box is very small, and I like Atom's search box more

VS Code version: Code 1.65.0 (b5205cc8eb4fbaa726835538cd82372cc0222d43, 2022-03-02T11:12:08.962Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

**Comment by gjsjohnmurray** [comment]
Try setting `"editor.suggest.snippetsPreventQuickSuggestions": false`

**Comment by jrieken** [comment]
When a snippet is active, IntelliSense as you type (aka quick suggestions) is disabled. That is because there is a conflict between the <kbd>Tab</kbd>-key which moves to the next placeholder but also accepts a completion. You wouldn't be able to type in a placeholder and then move to the next placeholder as you would accept a suggestion then. You have the following options

* change the default via the `editor.suggest.snippetsPreventQuickSuggestions`-setting
* in snippets trigger suggestions manually (via Ctrl+Space, Alt+ESC (macOS), or `ctrl/cmd+i`)
