### ISSUE TITLE
Reconsider editor group layout keybindings

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#14456]
Testing #14016

I'm not sure this is the best use of these keybindings for the following reasons:

- They don't use the fact that the keys 1, 2, 3 are being used, it might be better to keep them on hand for something that takes advantage of this?
- Really only toggle needs to be bound
- It's strange that <kbd>shift</kbd>+<kbd>alt</kbd> is being used when currently this combination is used exclusively for commands inside the editor

As an alternative, I'm not sure on it's usage but I suggest taking `editor.action.jumpToBracket`'s keybinding <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>\\</kbd> for `workbench.action.toggleEditorGroupLayout` as <kbd>ctrl</kbd>+<kbd>\\</kbd> is used to split the editor.

**Comment by bpasero** [comment]
@Tyriar I took it because Sublime is assigning them for changing layouts:

![image](https://cloud.githubusercontent.com/assets/900690/19713291/0d7bacd4-9b45-11e6-9685-72c8a596cb33.png)

Once we have support for empty groups we can actually do the same as sublime and expand these keybindings to have the same set (minus the grid). That was my intention here.

**Comment by bpasero** [comment]
Let's see how it goes.
