### ISSUE TITLE
Allow to use middle mouse click to open from viewlets pinned

### ISSUE THREAD

**Issue by isvaljek** [Microsoft/vscode#14453]
- VSCode Version:1.6.1
- OS Version:Windows 10 Pro x64

Steps to Reproduce:
1. open left sidebar
2. click on file item with middle mouse button

...would be nice if it opened those files in new tabs

**Comment by bpasero** [comment]
@isvaljek I just tried this with Sublime and it just seems to open the file like a normal left click. Would you expect in this case to not open the file in preview mode but pinned as real tab? Is that the difference to normal left click?

**Comment by isvaljek** [comment]
@bpasero in my case when I click on a file in sidebar in most cases the file that opens reuses the active tab, that's what I'd like to avoid, if possible with middle click.

**Comment by bpasero** [comment]
@isvaljek right, you know that you can configure this via `"workbench.editor.enablePreview": false`

**Comment by isvaljek** [comment]
didm't know that, thanks, and sorry for the noise

**Comment by bpasero** [comment]
I still think we should do something on middle mouse, even if we just open a file. Currently we seem to do nothing.

**Comment by bpasero** [comment]
This actually applies to all our trees, not just the explorer. I think we should be consistent and support this for any tree. I like the idea of pinning the file when opening like that. This is something where contributors could chime in for a PR 👍

**Comment by hun1ahpu** [comment]
@bpasero I would like to work on this issue.

As I am new to the project would appreciate any help. Here are some questions to start with:
- I've noticed that Search and Changes viewlets use 'selection' event instead of 'click','mousedown' events used by Debug, Explorer to open editor. Is it intented choice or we should try to be consistent across all the Trees?
- I would expect Expand/Collapse to still happen on middle mouse click. What do you think?
- Extensions seems to not support pin at all. Don't know if it's only on my version/environment. Opened an issue #10748
- I've seen a comment in treeDefaults.ts where we do not handle middle button event: "Give contents of the item a chance to handle this (e.g. open link in new tab)". I wonder if it's still a valid comment.
- I'm on Windows and i'm wondering if we expect the same behavior on Mac or we should have some Mac-specific treatment of middle button (Command button or smth?)

Thanks.

**Comment by bpasero** [comment]
> - I've noticed that Search and Changes viewlets use 'selection' event instead of 'click','mousedown' events used by Debug, Explorer to open editor. Is it intented choice or we should try to be consistent across all the Trees?

I think middle-click should be translated into a selection event from the tree so that down stream components do not have to do anything special. I also think middle click should not opened pinned, but just normal.

> - I would expect Expand/Collapse to still happen on middle mouse click. What do you think?

👍 

> - Extensions seems to not support pin at all. Don't know if it's only on my version/environment. Opened an issue #10748

Can you explain?

> - I've seen a comment in treeDefaults.ts where we do not handle middle button event: "Give contents of the item a chance to handle this (e.g. open link in new tab)". I wonder if it's still a valid comment.

I would try to convert it to a selection event and see how that behaves.

> - I'm on Windows and i'm wondering if we expect the same behavior on Mac or we should have some Mac-specific treatment of middle button (Command button or smth?)

I am fine with making this work the same on all OS.

**Comment by hun1ahpu** [comment]
@bpasero : Sorry my comment about Extensions was actually referring #17048. Specifically you cannot open more than one editor tab with extension.

Submitter a PR fix for this issue.
Thanks.
