### ISSUE TITLE
What scenarios is workbench.editor.defaultEditorGroupLayout designed to cover?

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#14468]
Testing #14016

I was assuming there would be no setting that drives this and that it would just pick up the last layout used. I'm curious what the thinking was around this setting.

Consider the user that works exclusively on a vertical monitor. Whenever they open a new workspace they would have to switch the editor group layout every time, or seek out a settings that drives it. I would guess it's a pretty small number that would go and discover the setting and instead just brew in their frustration.

Given this, a more sensible default imo would be either:

- No setting, just use the last used layout
- `"workbench.editor.defaultEditorGroupLayout": "most_recent"` as the default which uses the last used layout

**Comment by bpasero** [comment]
@Tyriar the use case is really only to have a default when the user has not made a choice of the layout yet. This applies to:
* new workspaces that were not opened before
* all cases of opening empty workspaces

The idea is that a user might always want to work in horizontal layout due to the monitor on. My idea was to give the user a way to set the layout to vertical or horizontal by default and then once the user changes it from the toggle action, of course this choice is persisted for the workspace.

**Comment by bpasero** [comment]
Adding @stevencl @chrisdias @seanmcbreen @egamma @bgashler1 to this discussion because we had an internal discussion on this already.

Erich suggested to just remove this setting and I am fine doing so.

**Comment by stevencl** [comment]
That sounds fine to me too.

**Comment by bgashler1** [comment]
@bpasero I'm fine removing it, too.  We should listen to feedback to see how users respond, particularly ones with portrait-oriented monitors.

**Comment by bpasero** [comment]
I took out the setting for now 👍
