### ISSUE TITLE
Visual Studio Code is sluggish

### ISSUE THREAD

**Issue by Vickyvk14** [microsoft/vscode#144606]
Its is very slow and i have tried all the possible methods

**Comment by SibiSiddharthan** [comment]
Hey there,
I am also facing the same issue on Windows 10.

Opening _any_ file with VSCode is quite slow when compared to the previous versions. This happens even when you drag and drop a file to an already open window.

Browsing files/directories in workspaces (VSCode open directory) is not slow (same as previous versions).

Thanks

**Comment by deepak1556** [comment]
@SibiSiddharthan IIUC you are only seeing degraded performance when opening file from the explorer or drag/drop from explorer ? Can you share a video demonstrating the issue so that its easier for us to understand.

Also can you check if the issue persists with our [exploration build](https://az764295.vo.msecnd.net/exploration/b056e68d8ddb4036ac8453a67c63f559589850fc/VSCodeUserSetup-x64-1.66.0-exploration.exe) that ship with a newer runtime, thanks!

**Comment by SibiSiddharthan** [comment]
> Also can you check if the issue persists with our [exploration build](https://az764295.vo.msecnd.net/exploration/b056e68d8ddb4036ac8453a67c63f559589850fc/VSCodeUserSetup-x64-1.66.0-exploration.exe) that ship with a newer runtime, thanks!

The exploration build does not seem to have this issue.

**Comment by deepak1556** [comment]
Thanks for confirming, https://code.visualstudio.com/insiders is now on the same runtime and will be pushed to stable for the March 2022 release.
