### ISSUE TITLE
Mac: mtime is not a good test for checking if a file is modified or not when updating <1s

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#14471]
Testing https://github.com/Microsoft/vscode/issues/14015

Repro steps:
1. Open users settings
2. Press `Command +` to increase the zoom
3. The window zooms out every time you press `command +`. Let's say we press `cmd +` five times, the window zooms out correctly five times but take a look at the value in `settings.json`, the `window.zoom` value each time is likely `1 2 2 4 5`.
4. However, whether the value you see in the editor is correct or not, when you reload the window, Code remembers the zoom level correctly and the value in `settings.json` is correct as well. For example, after you run `cmd +` three times, the value you see in editor changes from `1` to `2` and then to `2` again, reload the window, `window.zoomLevel` is now `3`, which is correct.

It seems the only thing we don't handle perfectly is the buffer/ textDocument.

**Comment by bpasero** [comment]
The issue here is that we use the mtime + content length as a finger print of the file to find out if it changed on disk or not. Since you manage to change the file faster than the minimal resolution of mtime (1s) and the content length does not change (you just increase a single length number), we think the file did not change on disk and thus refuse to load it.

The only better approach here is to use a content hash for finding out if the file changed or not.

**Comment by bpasero** [comment]
This has been fixed with the new apple file system.
