### ISSUE TITLE
html jsdoc for global functions is not highlighted

### ISSUE THREAD

**Issue by fuxichen** [microsoft/vscode#144726]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:1.65.1
- OS Version: window 11

Steps to Reproduce:

1. Create HTML file and template
2. add `<script>` label
3. add function and jsdoc
![image](https://user-images.githubusercontent.com/17411462/157391130-d6ac70b9-283c-4b79-bc78-8393e636d707.png)

**Comment by aeschli** [comment]
```
<html>
	<body>
		<script>

			/**
			 * @param {string} msg
			 */
			function foo() {
				console.log(e);
			}
			(
			/**
			 * @param {string} msg
			 */
			 function foo() {
				console.log(e);
			})();
		</script>


	</body>
</html>
```

**Comment by fuxichen** [comment]
> ```
> <html>
> 	<body>
> 		<script>
> 
> 			/**
> 			 * @param {string} msg
> 			 */
> 			function foo() {
> 				console.log(e);
> 			}
> 			(
> 			/**
> 			 * @param {string} msg
> 			 */
> 			 function foo() {
> 				console.log(e);
> 			})();
> 		</script>
> 
> 
> 	</body>
> </html>
> ```
still so
![image](https://user-images.githubusercontent.com/17411462/157407426-55a5307c-3492-42cd-8ac9-6fe5ceebf4a3.png)

**Comment by aeschli** [comment]
I can reproduce the problem with the code sample (please always paste the code sample along with the screenshot)

The problem comes from here: https://github.com/microsoft/vscode/blob/0a138fbe26e6147392867fb7df8c794d8ef37777/extensions/html/syntaxes/html.tmLanguage.json#L1925

That rule wins over the rule provided by the TypeScript grammar.

We use the [textmate html grammar](https://github.com/textmate/html.tmbundle/blob/master/Syntaxes/HTML.plist) here, but they use a different js grammar that (I assume) has no doc comments.

**Comment by aeschli** [comment]
This can by fixed by customizing the html grammar, but IMO this is a minor issue not justifying the work (the customization can easily break on the next import of the HTML grammar)

No fix planed.
