### ISSUE TITLE
File nesting: support for multiple levels

### ISSUE THREAD

**Issue by uecasm** [microsoft/vscode#144814]
It would be nice if the file nesting feature supported multiple levels of nesting.  Currently, a pattern set such as this:

```
"*.razor": "$(capture).razor.css, $(capture).resx",
"*.resx": "$(capture).*.resx"
```

Results in a flat list:
* Index.razor
    * Index.es.resx
    * Index.razor.css
    * Index.resx

Instead of, as intended:
* Index.razor
    * Index.razor.css
    * Index.resx
        * Index.es.resx

VS Code version: Code 1.65.1 (https://github.com/microsoft/vscode/commit/8908a9ca0f221f36507231afb39d2d8d1e182702, 2022-03-08T02:06:27.846Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

**Comment by adam-coster** [comment]
I've posted[ a related issue](https://github.com/microsoft/vscode/issues/144867), where there is no way to use multiple overlapping patterns -- the most general pattern always wins. The multiple-level-nesting feature could help to resolve that one, though the concept of specificity/priority would be required in either case.

**Comment by uecasm** [comment]
It would also be nice if it automatically picked up `DependentUpon` metadata in the project like Visual Studio does.  Although I think that only supported one level of nesting too.

**Comment by JacksonKearl** [comment]
Flattening is intentional, the code responsible is around here: https://github.com/microsoft/vscode/blob/e00873bcf6eb489bad3bd02369ce2eda34bd6832/src/vs/workbench/contrib/files/common/explorerFileNestingTrie.ts#L48-L62

The basic line of reasoning is that the nested files are considered to have a `"derived from"` relationship with their parent, which is a transitive relation.

This mirrors how some other editors handle nesting, though it is different from Visual Studio. I'll leave this open as a candidate feature request.

**Comment by uecasm** [comment]
Speaking of VS, it seems that has an entirely separate file that controls nesting settings (`.filenesting.json`), and that this one does support hierarchical nesting as expected.  Shouldn't the two use the same settings?
