### ISSUE TITLE
not defined shortcut contains `option` key will input strange character

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#144847]
Test under disable all extension and reset all the settings:
 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/157712079-9b3eb8bc-83e8-4a6d-af1b-76c646c990fe.png">

- VS Code Version: 1.66.0-insider
- OS Version: MacOS 12.2.1

@alexdima @hediet

May be this is a feature of MacOS? I can be sure of this is not feature of my Chinese input method, because this issue still exits when I toggle to builtin English input method.

The inputed character is `¬` when I trigger shortcut `option` + `l`.

**Comment by tjx666** [comment]
> They are Alt Code Shortcuts on macOS:
> 
> https://www.webnots.com/option-or-alt-key-shortcuts-to-insert-symbols-in-mac-os-x/

Any way to disable this in VSCode?

**Comment by Lemmingh** [comment]
[They are built into macOS.](https://support.apple.com/guide/mac-help/use-the-keyboard-viewer-on-mac-mchlp1015/mac)

Defining them as key bindings in VS Code is a straightforward solution.

Otherwise, you have to hack into the system to remap them. Common practices are:

* Modify the [`DefaultKeyBinding.dict`](https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/EventOverview/TextDefaultsBindings/TextDefaultsBindings.html) file.

* Create a custom keyboard layout with the help of tools like [Ukelele](https://software.sil.org/ukelele/).

**Comment by Lemmingh** [comment]
VS Code and even Chromium cannot intercept all Alt shortcuts according to #41024 and <https://crbug.com/887519>

So, remapping at OS-level might be the only reliable solution.
