### ISSUE TITLE
Terminal.sendText seems to strip unicode/emoji

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#144807]
GitLens uses `Terminal.sendText` to execute certain git commands, e.g. creating branches, and if the branch name you choose contains an emoji, the emoji never makes it into the terminal.

For example, I was trying to create a branch with an emoji in it:
GitLens is calling `Terminal.sendText('git branch ✨foo main', true)` and I only see `git branch foo main` in the terminal and the branch gets created without the emoji, e.g. `foo` in this case.

/cc @Tyriar @meganrogge

**Comment by meganrogge** [comment]
`Terminal: run selected text in active terminal` is not stripping unicode for me. I wonder if that's because we get the line content from the editor and it's handled specially there

https://github.com/microsoft/vscode/blob/ca85585881108598d2d13c4a1f43e0205937aec3/src/vs/workbench/contrib/terminal/browser/terminalActions.ts#L533-L551

![Recording 2022-03-11 at 00 49 42 (1)](https://user-images.githubusercontent.com/29464607/157810117-bfbaf309-5440-4205-bbd8-bd629e8a52a4.gif)

**Comment by eamodio** [comment]
Hrm, doesn't work for me when I try the same. I'm on Windows tho.
![terminal](https://user-images.githubusercontent.com/641685/157818043-36a2d9f3-0569-44fe-aae4-7a018e6795b8.gif)

**Comment by meganrogge** [comment]
Looks like that issue is documented for windows https://github.com/microsoft/vscode/issues/35266

**Comment by eamodio** [comment]
Ah ouch. It's odd that I can copy/paste them into the terminal and its fine, but `sendText` strips them completely and using the Emoji picker on windows inserts odd unicode characters (not the correct emoji).
