### ISSUE TITLE
Too many expand/collapse icons in problems

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#144919]
This doesn't look right:

![image](https://user-images.githubusercontent.com/2193314/157905515-32a50ad6-2edd-4c18-b3cd-7206ddb4a39d.png)

Version: 1.66.0-insider (user setup)
Commit: 6b7453421201c888b81eae5c04ec822a6423608f
Date: 2022-03-11T05:17:19.559Z
Electron: 17.1.1
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Windows_NT x64 10.0.22000

**Comment by misolori** [comment]
Agreed that this doesn't look great, seems like the third expander should just be part of the second? I haven't been able to get into a state like that yet:

<img width="829" alt="CleanShot 2022-03-11 at 08 53 41@2x" src="https://user-images.githubusercontent.com/35271042/157912094-ae4ba932-f9be-4f45-9641-7d9afacdcca4.png">

**Comment by sandy081** [comment]
What @Tyriar seeing is a multiline problem that has related information. @misolori 's screenshot has simple (single line) problem with related information. 

Currently related information is a separate entry that can selected so that user can open it. Hence it is rendered as child of the problem. For multiline message problem, only first line is shown and with an expand icon so that user can expand it to see the complete message. All lines are part of the problem and shall be selected when clicking on the problem entry.

I am not sure if we can merge multiline and related information into single twisty. 

@misolori Is it possible to use a different icon for showing and hiding a multiline message?

**Comment by sandy081** [comment]
![Recording 2022-03-21 at 23 57 24](https://user-images.githubusercontent.com/10746682/159339935-d0593887-ea5b-4d29-b75b-6f3ee124ea5c.gif)
