### ISSUE TITLE
Provide Memory Profiling and Snapshots tooling

### ISSUE THREAD

**Issue by vasumahesh1** [microsoft/vscode#1451]
Possible to get Memory profiling and snapshots in the near future?

**Comment by bpasero** [comment]
Not on our backlog yet, but now it is :)

**Comment by renewooller** [comment]
Other than Chrome Dev Tools? Help -> Toggle Developer Tools while debugging?

**Comment by renewooller** [comment]
Actually it's unclear if the above is attaching to VS Code itself, or my application. The size of memory and the size of the snapshot doesn't seem to add up.

**Comment by AnthonyJacob** [comment]
I would love to have built-in memory and performance profiling.

There are not many IDEs that support this feature and that bothers me, because a lot of today software uses excessive number of RAM and / or CPU (electron, I am looking at you). One of the reasons is obviously cheaper hardware, thus you can afford to be a little ineffective. But the other reason is that profiling is much harder than it has to be...

In my honest opinion, good profiling support, would be a huge competitive advantage and leap forward (utility wise) for vscode.
