### ISSUE TITLE
Timeline: revisit merging sources from all providers

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#145160]
I am a timeline consumer for local history entries. I respect the decision to show all timeline sources merged together by default. I do not agree with that decision though and think a dropdown to switch between individual providers makes more sense.

My changes are on `main` and it works like this:
* anytime you save a working copy, a new entry is added
* the entries appear as timeline entries in the "Timeline" view as "Local History"
* clicking an entry diffs to the current file

**Demo:**

![Recording 2022-03-15 at 20 21 26](https://user-images.githubusercontent.com/900690/158455051-a1e907d1-34e5-436e-9f29-7bf8b000f611.gif)

Imagine existing users that are used to seeing the git history. They will soon see their timeline spammed with entries that have nothing to do with git (that is my main worry actually).

**Alternate Design**

Imagine a dropdown that allows to switch between the sources:

![Recording 2022-03-15 at 20 23 53](https://user-images.githubusercontent.com/900690/158455488-0c78abd8-cd28-46b8-a281-cadf7d6a6d8d.gif)

//cc @kieferrm @egamma

**Comment by bpasero** [comment]
Closing in favour of a model where multiple entries of a source can collapse into one. I can see whether I get that working before we ship stable.

**Comment by IllusionMH** [comment]
> clicking an entry diffs to the current file

This looks unexpected. Moreover it differs from what user gets for git commits (diff for commit) and I think it differs from WebStorm (which is mentioned in initial request and more in comments).

Moreover latest File Saved entry shows empty diff and first one (that might change 1 line) shows all that changes. And to guess what actually change was saved first I need to "calculate" diff between fist and second saves.

At least my expectation was to see exact diff caused by save. Are there plans to make it actual "diff by that save"?

**Comment by bpasero** [comment]
@IllusionMH I looked at IntelliJ and Eclipse which both diff to the latest file. Nevertheless, there is options now to diff the exact change:

![image](https://user-images.githubusercontent.com/900690/158653465-2eed675b-7a07-4a8e-9622-d8c4ae33df71.png)

The major advantage of diffing to the current file is that the right hand side is editable, so you can selectively take over changes. And you will also see what you get when you restore the entry.

Imho diffing to the previous local history is quite meaningless, especially since entries appear when auto save is enabled. This is different from git commits that always group a logical change unit under 1 label.

**Comment by IllusionMH** [comment]
Looks like it was long time ago when I used WS (and local history), because I think I restored some parts (not recent) but most likely I just copied.

Thanks for context menu entry, already had a chance to used it to get adequate diff (especially with removals). My case was several experiments to get thing working and "find" what I did in the middle of this process.
