### ISSUE TITLE
an option for more compact inlay hints

### ISSUE THREAD

**Issue by jhgg** [microsoft/vscode#145191]
rust-analyzer recently switched to using LSP inlay hints, which render using vscode's inlay hint renderer. with this involves a change in design,  and most notably, an introduction of some slight padding around the inlay hint. 

in rust-analyzer, inlay hints where it make sense try to look like the actual inferred type definition in many cases, for example:

```rust
let i = String::from("hello");
````

Might insert the following inlay hint:

```rust
let i: String = String::from("hello");
     ^^^^^^^^
```

In vscode today, however, there is some awkward padding around this:

![image](https://user-images.githubusercontent.com/5489149/158539230-53a57016-dd53-461f-9620-04aca4069097.png)

In an older rust-analyzer build, this used to look like (taken from r-a's github page which still shows the old style.)

![image](https://user-images.githubusercontent.com/5489149/158539509-a8af4051-c3c9-4537-a530-42bcc6f6dbc6.png)

An effort can be made to try to reduce the visual impact of the inlay hints by setting `editorInlayHint.background` and `editorInlayHint.foreground` - however, this still does not solve the issue of the awkward padding box that is now hidden:

![image](https://user-images.githubusercontent.com/5489149/158539760-3e374642-9e3a-4522-9436-b54fa0e1526c.png)

This suffers from odd padding on the left/right side, and the bottom. 

It would be really much appreciated if vscode could support a "compact" display style option which would remove the padding, border radius and vertical alignment.

The "compact" version might look like this (still probably a pixel or two off, crafted in mspaint..., but should be enough to show the idea)

![image](https://user-images.githubusercontent.com/5489149/158541187-72230a08-5556-4522-bcec-2ea9459a99fe.png)

I would be happy to implement this feature too if pointed in the right direction!

**Comment by jrieken** [comment]
Paddings are computes [here](https://github.com/microsoft/vscode/blob/778b74a2159983ba09568d069ef9c9ecd858f783/src/vs/editor/contrib/inlayHints/browser/inlayHintsController.ts#L455-L468). Happy to receive a PR but we should first agree and what's supposed to happen. The padding is mostly because inlay have a background colour and rounded corners. Remove all padding with that looks slightly odd... I like the idea of subtle inlay hints! What would be the best way to enable that? I know that extension authors gravitate towards an API that enables this for all users of their language but there is also an argument for making this a user setting. That puts user into control and allows them to have uniform inlay hints across languages.

**Comment by misolori** [comment]
I think the problem with the background is this will interfere with inline suggestions that almost use the same styling:

<img width="198" alt="CleanShot 2022-03-16 at 10 32 45@2x" src="https://user-images.githubusercontent.com/35271042/158651927-3e4c3450-46e6-4fa2-80be-fef8808af82f.png">

I'm down for adding more space from between the inlay hint and text to allow it to breathe more but the older rust-analyzer build example doesn't look good IMO (which can be subjective).

**Comment by jhgg** [comment]
> I think the problem with removing the background is this will interfere with inline suggestions that almost use the same styling:

I think this is fair, however, by changing the font contrast or color, it'd meet my needs in an unambiguous way. I actually do not use the inline suggestions feature at all, and find it very annoying (gave GH copilot a shot, found it way too distracting.) 

> but the older rust-analyzer build example doesn't look good IMO (which can be subjective).

Definitely subjective. I find r-a's legacy inlay hint style to be "best in class" - it's not too visually distracting, and actually is for the most part for type hints, valid rust syntax, which makes it flow really well when I'm reading code.

--- 

My proposal is to add this as an option, where one can toggle, that will turn off the background for inlay hints, and disable the background color. This will make the inlay hints more subtle and reduce the visual noise on the editor when hints are displayed.   This should be a user level setting that you can set, additionally, within language blocks in the user config, so for example, if I just wanted to apply this to rust, I could do `{ "[rust]": { "editor.inlayHints.style": "subtle" } }` for example.

**Comment by TheV360** [comment]
I'm using Rust Analyzer in VS Code and I feel inlay hints would greatly benefit from an option to disable padding. I opened the editor today to find the inlay hints looking like this by default:

![2022-03-16_20-40-27_Code](https://user-images.githubusercontent.com/25177071/158714055-b0b68b5f-0121-4ce8-b29a-cd567637e44c.png)

(using the theme Gruvbox Dark Hard)

The font is misaligned from the character grid due to two factors:
- the hints' font size is a percentage smaller than the editor's font size by default (able to be fixed with `"editor.inlayHints.fontSize"`)
- the hints have padding that bumps them off the character grid (not able to be fixed without inspect-element style modifications)

After changing my color customization settings, I got the hints to look somewhat like the old Rust Analyzer hints:

![2022-03-16_20-37-16_Code](https://user-images.githubusercontent.com/25177071/158714505-e307edc8-27f3-4d33-a903-2ea97dab9697.png)

And after removing these three CSS rules...

![2022-03-16_20-37-46_Code](https://user-images.githubusercontent.com/25177071/158714529-938197c2-5cc1-4c73-af44-c4e95653e033.png)

...I got it to look how it was before:

![2022-03-16_20-37-54_Code](https://user-images.githubusercontent.com/25177071/158714558-55b5c8a4-d9a6-436a-92cc-0dd9978458e3.png)

My current configuration doesn't use background colors (they're just set to transparent) but if there was the option to remove the padding and set a background color, I'd expect the result to look like TODO Highlight's... highlighted TODO comments:

![2022-03-16_20-45-31_Code](https://user-images.githubusercontent.com/25177071/158714728-5b3f36d5-b7c6-443e-9b17-a137d945df89.png)

**Comment by jhgg** [comment]
Thinking about this more, and in response to the above feedback, perhaps it should be a "compact" mode for inlay hints which disable those 3 CSS properties. Users can decide if they want to change the background color or not.

**Comment by misolori** [comment]
>  perhaps it should be a "compact" mode for inlay hints which disable those 3 CSS properties

I think that makes a lot more sense, though we'd need to make sure the defaults here are visually different from inline suggestions (likely just using a different foreground color).

**Comment by jhgg** [comment]
Took a stab at implementing this in #145470 - this is my first vscode contribution so no idea if I did it right haha.

**Comment by jrieken** [comment]
Thanks for far. We are nearing endgame so the PR won't get much attention until after that. Tho, I am unsure if compact inlay hints are user setting or a property of selected hints themselves. Like, do you want some hints to be compact and others not at the same time?

**Comment by safasofuoglu** [comment]
I arrived here because I got fairly distracted by the inlay hint backgrounds. Thanks for your consideration.

**Comment by jhgg** [comment]
The current PR decouples the removal of the background from the setting. 

> Tho, I am unsure if compact inlay hints are user setting or a property of selected hints themselves. Like, do you want some hints to be compact and others not at the same time?

Personally, no. I'd prefer *all* hints to be compact. But I can't speak for others!

**Comment by jasonwilliams** [comment]
I found the inline hint spacing and padding quite jarring, i raised an [issue](https://github.com/microsoft/vscode/issues/146575) but it may be related to this one

**Comment by jrieken** [comment]
FYI - I have removed the setting again, the `compact` mode is the default for everyone. For now this is a settings-description/schema-only change but so far feedback is positive and I am ready to make "compact" the only possible mode
