### ISSUE TITLE
Typescript 2.0.6 breaks formatter

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#14519]
Builds fail with:

```
/Users/travis/build/Microsoft/vscode/extensions/configuration-editing/src/extension.ts is not formatted
/Users/travis/build/Microsoft/vscode/extensions/extension-editing/src/extension.ts is not formatted
/Users/travis/build/Microsoft/vscode/extensions/javascript/src/javascriptMain.ts is not formatted
/Users/travis/build/Microsoft/vscode/extensions/markdown/src/extension.ts is not formatted
...
```

This occurs on all our files.

Additionally, the `monaco.d.ts` that gets generated and formatted by the TypeScript version we have installed has no whitespace indentation at all.

**Comment by mhegazy** [comment]
Consider using https://github.com/vvakame/typescript-formatter instead.

**Comment by joaomoreno** [comment]
cc @jrieken

**Comment by jrieken** [comment]
that's the one we use - it's just being used from within a gulp plugin

**Comment by jez9999** [comment]
This is a very strange bug, and it caused the exact same problem for me.

Note that if you've already installed a version of typescript later than 2.0.3, even after updating `package.json` you'll have to run `npm install typescript` and you should see `-- typescript@2.0.3`.  Later versions may exhibit this bug and git will refuse to commit because the commit hook claims that a bunch of modified files "are not formatted".

**Comment by jez9999** [comment]
@jrieken @sverrirs @joaomoreno Do any of you happen to know whether there's a bug in the Typescript project on Github for fixing this?  It looks like a bug in Typescript, and a pretty bad one since it was introduced during a new *patch release*, which should only be for bug fixes and no changes to functionality.

**Comment by joaomoreno** [comment]
Microsoft/TypeScript#11852
