### ISSUE TITLE
Extension API - Determining the reason that debugging was terminated 

### ISSUE THREAD

**Issue by jimasp** [microsoft/vscode#145159]
Context - I'm writing a vs code extension.

The callback for `onDidTerminateDebugSession` provides a `DebugSession` object, but that object does not indicate the reason that the debug session was terminated, or at least I can't find it in there.

I'd like to determine whether the debug session was either:
a) stopped by the user (clicking the stop button), or
b) the debug session reached conclusion (no more code to run) and the thread exited automatically.

At the moment I'm using this horrible hack as a workaround:

```
vscode.debug.registerDebugAdapterTrackerFactory('*', {
  createDebugAdapterTracker() {
    return {
      onDidSendMessage: m => {
        // 247 = magic number exit code that indicates user clicked stop
        if(m.event === "exited" && m.body?.exitCode === 247) {  
          debugStopClicked = true;
        }
      }
    };
  }
});
```

Unless an alternative method is available (please advise) then I'd like to request that `onDidTerminateDebugSession` either:
a. calls back with a `DebugSession` object that contains a property that indicates the reason for termination, or
b. calls back with a second parameter that contains the reason.

**Comment by roblourens** [comment]
I don't think this concept really exists. The user clicks stop, the debug adapter does any number of things to get the program to stop, depending on the particular runtime or context for running the program, and then the program terminates some time later for a reason that may or may not be due to whatever the debug adapter just did.

I'm guessing the 247 exit code will just work for one type of debug adapter and run context - you could use your tracker to track whether the user ever clicked the stop button. That might work, depending on what you are trying to do.

**Comment by jimasp** [comment]
Just to help anyone else looking at this issue.
The solution to finding out if the user clicked debug stop is that you can subscribe to an _existing_ command:
```
context.subscriptions.push(vscode.commands.registerCommand("workbench.action.debug.stop", debugStopHandler));
```

**Comment by roblourens** [comment]
Please don't take over builtin commands, this could prevent debug stop from working correctly.
