### ISSUE TITLE
Zooming Out Keyboard Databinding Issue

### ISSUE THREAD

**Issue by MaherJendoubi** [Microsoft/vscode#14522]
- VSCode Version: 1.6.1
- OS Version: Windows 10 Enterprise [version 10.0.14393]
- AZERTY French Keyboard

Steps to Reproduce:

1. Open any file text with Visual Studio Code
2. Do the shortcut Ctrl+- 
3. The shortcut doesn't work

I enclose below the problem in settings of the binding and many other developers on Windows are facing the same issue like me.

Best Regards,
Maher
![2016-10-26_08-48-59](https://cloud.githubusercontent.com/assets/1798510/19721705/c34e619a-9b73-11e6-85fc-e718fe24694d.png)

**Comment by alexandrudima** [comment]
@MaherJendoubi Please hover over the red x and read the message.

**Comment by MaherJendoubi** [comment]
![image](https://cloud.githubusercontent.com/assets/1798510/19744859/8df5218a-9bcf-11e6-8d7d-4dd134f2d3d3.png)

**Comment by alexandrudima** [comment]
So this means that zoomOut is not bound out of the box for your keyboard layout. The reason is simple:

`"ctrl+-"` is simply a UI representation for `"ctrl+VK_OEM_MINUS"`, where `VK_OEM_MINUS` is a key code as defined [here](https://msdn.microsoft.com/en-us/library/windows/desktop/dd375731(v=vs.85).aspx). For your current keyboard layout, no single key is mapped to that key code. Meaning regardless what you press on your keyboard, the OS will never generate the key code `VK_OEM_MINUS`.

Therefore, please go to File > Preferences > Keyboard Shortcuts and define a new keybindings for those commands as you would want them. Here I am doing it:

![zoomoutrebinding](https://cloud.githubusercontent.com/assets/5047891/19745050/5922af08-9bd0-11e6-8cfc-68620d6e9d89.gif)

**Comment by MaherJendoubi** [comment]
@alexandrudima Awesome! Thank you for the answer! Which tool are you using please to take such a screenshot?

**Comment by alexandrudima** [comment]
I'm using [LiceCap](http://www.cockos.com/licecap/)

**Comment by MaherJendoubi** [comment]
Thanks a lot!

**Comment by MaherJendoubi** [comment]
👍 👍 👍
