### ISSUE TITLE
Timeline: allow to group multiple entries of same kind into a single node that can expand

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#145294]
This is to explore whether the timeline view could aggregate multiple entries of the same source under a single node to reduce the spam from local history.

Examples from other products:

![image](https://user-images.githubusercontent.com/900690/158754914-2f888035-6289-4083-80ad-056dc051ce68.png)

![image](https://user-images.githubusercontent.com/900690/158754929-6057bd71-614d-4a2f-a56d-3e13c2f04b9f.png)

**Notes**
* entries should still be sorted from newest to oldest even when under a parent node
* relative time should be visible as with top level entries
* parent node should show most recent entries time

//cc @JacksonKearl @daviddossett @misolori

**Comment by bpasero** [comment]
This turned out to be a surprisingly small change so I pushed for it:

![Recording 2022-03-20 at 10 09 45](https://user-images.githubusercontent.com/900690/159155655-06f78c6a-b9d0-489c-b470-37acbd280f69.gif)

@daviddossett @misolori fyi, happy for feedback:
* I ended up using the same icon because in most cases the user will see the aggregated version and not a single entry and I quite like that icon already
* number of aggregated entries is shown as part of the label
* there is no tooltip and no command other than expand/collapse on such an entry, but we could enrich this

//cc @JacksonKearl this works by making `Timeline` allow to return `children`:

https://github.com/microsoft/vscode/blob/b53e5236f83df4eb570613dd69c09f6c386ff0da/src/vs/workbench/contrib/timeline/common/timeline.ts#L56-L61

**Comment by bpasero** [comment]
Oh, I had to revert that change, I forgot that the aggregation should not happen at the level of the provider but needs to happen inside the timeline view because we want to aggregate over all items from all sources and not within source. Otherwise the timeline would no longer show a real timeline with entries one after the other...

**Comment by daviddossett** [comment]
Looking good! Is it possible to use an explicit tree parent with open/close? If I didn't know what the behavior was, I wouldn't know it was clickable to show the actual entries. E.g.

<img width="606" alt="CleanShot 2022-03-22 at 11 27 51@2x" src="https://user-images.githubusercontent.com/25163139/159550523-ab744d56-675e-4391-9d6a-d11efae7bf5b.png">

> number of aggregated entries is shown as part of the label

I wonder if a badge a la SCM could also work for here. The plain text in brackets is clear, but feels somewhat bespoke here since we have similar patterns for counting children elsewhere:

<img width="235" alt="CleanShot 2022-03-22 at 11 25 17@2x" src="https://user-images.githubusercontent.com/25163139/159550083-4338ec52-cc64-4f14-9e95-1e8ed1ef1959.png">

It could look like:

<img width="594" alt="CleanShot 2022-03-22 at 11 28 58@2x" src="https://user-images.githubusercontent.com/25163139/159550721-c660b446-72c6-473b-b3c4-d8c63b2cdfa9.png">

**Comment by bpasero** [comment]
👍  for both suggestions

**Comment by monstajoe2002** [comment]
Can anyone assign me this issue please?
