### ISSUE TITLE
Support passing extension packs as `additionalBuiltinExtensions` in VS Code Web

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#145295]
Support passing extension packs as `additionalBuiltinExtensions` in VS Code Web

**Comment by jrieken** [comment]
@sandy081 Once this is in insiders we can update/publish our extension-packs as long as we use an engine field that requires current insiders. No need to wait for stable, right?

**Comment by sandy081** [comment]
Unfortunately not, because I discovered following bugs in Web while implementing this

- Compatibility check is not done for additional built in extensions
- Compatibility is not checked while loading web extensions into Web worker extension host.

**Comment by joyceerhl** [comment]
What is the expected behavior for installing pre-release extensions that are also extension packs or have extension dependencies? Ideally I'd want the pre-release version of them all to be installed but perhaps this should be configurable by the extensions via package.json entries.

For context on my use case: `GitHub.remotehub` and `ms-vscode.azure-repos` will pull in a new extension `ms-vscode.remote-repositories` as an extension pack (I have a PR in progress to make this an extension dependency relationship instead). I've published a pre-release of `ms-vscode.remote-repositories` but when installing the other two extensions, it seems that the dependency doesn't get resolved:

```
Cannot install packed extensions of extension: ms-vscode.azure-repos Can't install release version of 'ms-vscode.remote-repositories' extension because it has no release version.
```

I can work around this by also bundling `ms-vscode.remote-repositories` in insiders.vscode.dev, but I would like to avoid having to update the embedders if necessary.

**Comment by sandy081** [comment]
If you chose to install pre-release version of the pack then pre-release versions of included or dependency extensions are installed. 

> Cannot install packed extensions of extension: ms-vscode.azure-repos Can't install release version of 'ms-vscode.remote-repositories' extension because it has no release version.

This is expected. It seems there is no release version of `ms-vscode.remote-repositories` extension. It seems you are trying to install a release version of `GitHub.remotehub` extension that depends on `ms-vscode.remote-repositories` extension. But the `ms-vscode.remote-repositories` extension has no release version. I would recommend to publish a release version of it to fix.
