### ISSUE TITLE
Add support for SnippetString in TextEdit and WorkspaceEdit

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#145374]
The `TextEdit` and `WorkspaceEdit` APIs are used to apply refactorings. Those will benefit from being able to place the cursor and add placeholders, like add a placeholder for the suggested name of an extracted vairable

**Comment by jrieken** [comment]
For April I have enabled this (for editor dnd) and for May we can make this more prominent. Questions

* how to handle N snippet edits
* where to allow snippets edits
* how do snippet edits fit into workspace edits

**Comment by zardoy** [comment]
Hey! Thank you so much for planning this feature! I'd use it in my extension to replace some typed text into snippet.
Currently, in order to achieve that I need to a hack with `onDidChangeTextDocument` to track deletion before inserting snippet.

I checked it insiders and IMO the current implementation is just *ideal* as it works with multiple different snippets!
Is there a plan to finally release in it August update?

**Comment by jrieken** [comment]
Plan to finalize this API for September

**Comment by jrieken** [comment]
This is now done via the [`SnippetTextEdit`](https://github.com/microsoft/vscode/blob/2ad3d68d9b42dfe761b3ce98d8936c766585cf2c/src/vscode-dts/vscode.d.ts#L3449)

**Comment by jrieken** [comment]
fyi @matklad

**Comment by zardoy** [comment]
@jrieken as I understand, [`CompletionItem.additionalTextEdits`](https://github.com/microsoft/vscode/blob/2ad3d68d9b42dfe761b3ce98d8936c766585cf2c/src/vscode-dts/vscode.d.ts#L4940) won't receive snippets support, right?

Inserting/replacing content with snippets would require additional command execution for these cases. I can imagine cases, where it could be handly to replace a few lines with some snippet on completion accepted.

**Comment by jrieken** [comment]
> @jrieken as I understand, [CompletionItem.additionalTextEdits](https://github.com/microsoft/vscode/blob/2ad3d68d9b42dfe761b3ce98d8936c766585cf2c/src/vscode-dts/vscode.d.ts#L4940) won't receive snippets support, right?

As for this issue no and it needs thinking if it can be done, esp since they can come late and since the main edit can already be a snippet

**Comment by zardoy** [comment]
@jrieken I also want to ask you about white space normalization. It'd much easier to describe the issue with the following code:

```ts
const insertString = '1\n\t1\n1'
const snippetString = new vscode.SnippetString(insertString)
const editor = vscode.window.activeTextEditor!
const insertPos = editor.selection.active
// 1
const edit = new vscode.WorkspaceEdit()
edit.set(editor.document.uri, [vscode.SnippetTextEdit.insert(insertPos, snippetString)])
void vscode.workspace.applyEdit(edit)
// 2
void editor.insertSnippet(snippetString, insertPos)
```

For me, these approaches to insert snippet seemed equal, but they actually insert different text (`vscode.SnippetTextEdit.insert` doesn't do space adjusting like `editor.insertSnippet`).

Is that also by design?

**Comment by jrieken** [comment]
> Is that also by design?

Fair question and something I didn't consider yet. Don't know yet what the design should be but looking at the sources they should behave the same: both should default to adjusting whitespace. I will investigate
