### ISSUE TITLE
Clarify purpose of `superType` under `semanticTokenTypes`

### ISSUE THREAD

**Issue by radeksimko** [microsoft/vscode#145312]
I am not sure if this should be filed as a bug or a feature, so to begin I'd like docs to be updated to clarify what `superType` is meant to be used for and what implications do the values have.

Currently the docs seem very vague on this topic:
https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide#custom-token-types-and-modifiers

https://github.com/microsoft/vscode/blob/94c9ea46838a9a619aeafb7e8afd1170c967bb55/src/vs/workbench/services/themes/common/tokenClassificationExtensionPoint.ts#L42-L47

My assumption was that `superType` would be used as an alternative/fallback token type if the theme doesn't support the custom token type.

```json
"semanticTokenTypes": [
      {"id": "hcl-attrName", "superType": "property"},
      {"id": "hcl-blockType", "superType": "type"},
      {"id": "hcl-blockLabel", "superType": "enumMember"}
]
```
In the example above I expected VSCode to use e.g. `hcl-blockType` if the theme supports it or `type` if it doesn't. Instead it just always assigns the custom types regardless of whether themes support it or not.

Instead I had to reverse engineer the token type mapping to TM scopes from here
https://github.com/microsoft/vscode/blob/02e8bd149ca3fb68e7f26ebec33f920ba0feef96/src/vs/platform/theme/common/tokenClassificationRegistry.ts#L541-L582
and then re-declare this mapping within `semanticTokenScope` to achieve this.

```json
"semanticTokenScopes": [
      {
        "scopes": {
          "hcl-attrName": ["variable.other.property"],
          "hcl-blockType": ["entity.name.type"],
          "hcl-blockLabel": ["variable.other.enummember"],
        }
      }
]
```

If this is not how it was meant to work - what is the purpose of that field? If this _is_ how it's meant to work - I guess we can turn this into a bug.

--- 

This may be related to https://github.com/microsoft/vscode/issues/103109 although I feel like I may be asking/expecting the exact opposite - that is for VSCode to figure out what the right token to use, and both extensions and themes to stay as simple as possible.

**Comment by aeschli** [comment]
Yes, you still have to provide token scopes for your custom token type, even if you have a super type. Typically, you don't take exactly the same scopes, but a more specific scopes. e.g. instead of `variable.other.property` you will have `vaiable.other.property.attr`. 
To see the scopes that the built-in types use, see https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide#predefined-textmate-scope-mappings

What the super type will help you with is when the theme has rules for semanticTokenColors.
E.g. https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide#semantic-coloring-in-color-themes
```
{
  "name": "Red Theme",
  "semanticTokenColors": {
    "property.readonly:java": "#ff0011"
  }
}
```
So here also your custom property `hcl-attrName` will be matched.

Does that make sense?

I guess we could change the behavior, but I'm a bit afraid of breaking existing users.

So I would prefer to just update the docs.
