### ISSUE TITLE
If multiple `registerDocumentSemanticTokensProvider` matches the same score, which will be used?

### ISSUE THREAD

**Issue by XadillaX** [microsoft/vscode#145530]
If two extensions both `registerDocumentSemanticTokensProvider()`, and the selector matches the same score, which one will be used?

Is there any way to use them both, or specify a certain one?

Related issue: https://github.com/microsoft/vscode-python/issues/18723

**Comment by jrieken** [comment]
The tie breaker will be the order in which the corresponding extension has registered the provider: the last one will win. There is no support for multiple semantic token providers, we rarely see conflicts with this and ideally extensions have the ability to enable/disable their token provider if there are conflicts. Adding such a setting in VS Code itself isn't as simple as it sounds because providers are dynamic and we don't know under what circumstances a provider appears/disappears. That's why we consider we recommend to add settings to conflicting extensions which makes this a user-choice

**Comment by jrieken** [comment]
cc @alexdima

**Comment by XadillaX** [comment]
My extension is to implement gyp's features. e.g. semantic highlighting.

And gyp is a type of python file. So python extension will do the semantic highlighting while my gyp one will loose effect.

I can't control the register order. Or is there any way to control the order?
