### ISSUE TITLE
Settings box can overlap setting

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#145572]
See here:

<img width="863" alt="image" src="https://user-images.githubusercontent.com/900690/159301275-40074bff-e3c3-4497-8953-bdd89b7ff459.png">

I have zoomed in a bit to reproduce.

//cc @joaomoreno

**Comment by joaomoreno** [comment]
@bpasero Maybe steps? I can't repro on Windows.

**Comment by bpasero** [comment]
Yes it involves having the TOC visible, does not repro without. And having an editor to the side so that settings editor width is limited. I had zoomed in 3 times.

**Comment by joaomoreno** [comment]
Repro:

1. Resize the TOC sash

🐛 The list doesn't get properly laid out.

![Recording 2022-03-25 at 16 40 44](https://user-images.githubusercontent.com/22350/160153600-fc4baef2-7299-4357-9e9b-5307332ff9d8.gif)

@rzhao271 This is not `polish`.

**Comment by joaomoreno** [comment]
This got broken by: https://github.com/microsoft/vscode/commit/670039b0f17743bbfc489d32530e61656f8c84a3

Especially [this](https://github.com/microsoft/vscode/blob/f32692912fdd0d1785c2dd7c8ddd97f0f308f541/src/vs/workbench/contrib/preferences/browser/settingsEditor2.ts#L724-L726) feels very broken. When using the SplitView, you should rely on it to propagate layout. That is, (1) your container gets layout, (2) the splitview gets layout and (3) each view gets layout; that is the right chain of layout calls. This adoption of SplitView is incorrect since step 3 is not working correctly:

- Each view should be layout inside each splitview layout call:
    - https://github.com/microsoft/vscode/blob/f32692912fdd0d1785c2dd7c8ddd97f0f308f541/src/vs/workbench/contrib/preferences/browser/settingsEditor2.ts#L716
    - https://github.com/microsoft/vscode/blob/f32692912fdd0d1785c2dd7c8ddd97f0f308f541/src/vs/workbench/contrib/preferences/browser/settingsEditor2.ts#L725
- So none of this code should exist here: https://github.com/microsoft/vscode/blob/f32692912fdd0d1785c2dd7c8ddd97f0f308f541/src/vs/workbench/contrib/preferences/browser/settingsEditor2.ts#L1538-L1546
