### ISSUE TITLE
Add `VSCODE_SHELL_INTEGRATION` variable

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#145582]
> A special variable that signifies that VSCode is attempting to enable shell integration. For example, VSCODE_SHELL_INTEGRATION=1. It has to be set at the very beginning so that user rc files can see it.

_Originally posted by @romkatv in https://github.com/microsoft/vscode/issues/142004#issuecomment-1073263418_

**Comment by Tyriar** [comment]
We want to warn via the log service if possible or not at all otherwise, not the shell as per https://github.com/microsoft/vscode/pull/145610#issuecomment-1076229419

**Comment by Tyriar** [comment]
To verify on mac or linux:

1. Enable shell integration
2. Open a bash terminal, ensure the shell integration message appears
3. Add `unset VSCODE_SHELL_INTEGRATION` to your `~/.bashrc`
4. Open a bash terminal, ensure the shell integration message does not appear
5. Repeat 2-4 but with zsh and `~/.zshrc`

**Comment by Tyriar** [comment]
Fixed in https://github.com/microsoft/vscode/pull/145884

**Comment by JacksonKearl** [comment]
Bash doesn't execute `.bashrc` for login shells, which is the default bash profile on MacOS. Verified after changing the profile to not be a login shell, also verified with default profile but in `.bash_profile` instead of `.bashrc`. One note, bash displays a message when integration is disabled zsh does not: 
<img width="1082" alt="image" src="https://user-images.githubusercontent.com/8586769/160032657-815f51e1-5258-4c2f-b299-bfa012377f88.png">

**Comment by Tyriar** [comment]
@JacksonKearl good observation, created a bug for April: https://github.com/microsoft/vscode/issues/146057
