### ISSUE TITLE
Test tabs API

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#145585]
Refs: https://github.com/microsoft/vscode/issues/133532

- [x] anyOS @bpasero
- [x] anyOS @joyceerhl
- [x] anyOS @JacksonKearl

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23145585%0A%0A&assignees=lramos15)

---

We are finalizing the shape of the tabs API and want feedback alongside bug testing .

* [Create an extension using this guide](https://code.visualstudio.com/api/get-started/your-first-extension)
* Add the proposed API:
  * First add the proposed API to the `package.json` (see below)
  * Then run `npx vscode-dts dev` to get the typings
```json
	"enabledApiProposals": [
		"tabs"
	],
```

Some things to test 
- All the functions work as expected
- Names and comments make sense
- API feels easy to use and there are no major pain points

Additionally any general feedback regarding the API is greatly appreciated.!

**Comment by bpasero** [comment]
If someone has the energy: would be nice to validate the API with an extension sample (https://github.com/microsoft/vscode-extension-samples), e.g. a custom tree view that re-implements the "Open Editors" view.

I could go on with testing because the API is quite complex and there are a lot of corner cases.

**Comment by lramos15** [comment]
@bpasero Thanks for the testing :). I'll suggest it to Kai and SteVen as a possible candidate for the sample I do next iteration
