### ISSUE TITLE
Source Control Repositories View cannot be re-sized

### ISSUE THREAD

**Issue by lmapii** [microsoft/vscode#145662]
The size of the view "Source Control Repositories" can no longer be adjusted.

- Open a folder/workspace that has multiple git repositories.
- Switch to the SCM viewlet and make sure that both "Source Control Repositories" and "Source Control" views are visible.
- Try to re-size the "Source Control Repositories" view.

This is a bug in the current insider build:

Version: 1.66.0-insider (user setup)
Commit: b0966eddca8cc86d3051213b6bf8327ef67ecf6d
Date: 2022-03-22T07:31:08.410Z
Electron: 17.1.2
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Windows_NT x64 10.0.19044

**Comment by lszomoru** [comment]
By design the "Source Control Repositories" view will have the maximum height to show 10 repositories. You can modify this using the `scm.repositories.visible` setting. If you would like for the "Source Control Repositories" to take up all the available space and to have the ability to resize it manually, set the `scm.repositories.visible` setting to `0`.

**Comment by lmapii** [comment]
Had `scm.repositories.visible:0` in my user settings but not in the insiders, sorry.
