### ISSUE TITLE
UI scrolls when tabbing around in narrow window

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#14565]
- Enable 'tab moves focus'. You can't see it in this gif because of #12941, but it's enabled.
- Make the window narrow enough so that the editor buttons in the top right are off the page
- When you tab to them, the whole page scrolls to them so the sidebar is hidden.

Reproes in both 1.7-insiders and 1.6.

![oct-26-2016 18-00-00](https://cloud.githubusercontent.com/assets/323878/19750456/12b4f4ce-9ba6-11e6-9834-b948b373a712.gif)

**Comment by bpasero** [comment]
I think this is the still issue as https://github.com/Microsoft/vscode/issues/6810

Underlying problem is that Chrome wants to reveal the item that you tab to (or that has focus) and it will try so no matter what is needed (e.g. by setting `scrollLeft`). Not sure how to prevent that, if someone has ideas, lets continue in #6810
