### ISSUE TITLE
`workbench.editor.openSideBySideDirection` not respected

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#145693]
Testing #145585

When moving an editor to `ViewColumn.Beside`, we should respect the user's `workbench.editor.openSideBySideDirection` setting. Currently the group always opens to the right hand side.

**Comment by lramos15** [comment]
@rchiodo You might need to have `"workbench.editor.closeEmptyGroups": false` in your settings because if you move the last tab in a group to a new group the old group gets closed due to being empty and it looks like nothing happened.

Here's the code I used to verify but would appreciate others verification since I wrote the code:

```ts
	const disposable = vscode.commands.registerCommand('extension.helloWorld', () => {
		const activeTab = vscode.window.tabGroups.activeTabGroup?.activeTab;
		if (activeTab) {
			vscode.window.tabGroups.move(activeTab, vscode.ViewColumn.Beside, 0, false);
			vscode.window.showInformationMessage(`Moving: ${activeTab.label}`);
		}
	});
```

**Comment by rchiodo** [comment]
@lramos15 your code works for me but my event handler doesn't. Is there a scenario where I'm not allowed to move a tab? Or maybe it doesn't work during a tab change event?

**Comment by rchiodo** [comment]
Nevermind, my fault. The console log was crashing trying to stringify the tab.
