### ISSUE TITLE
`onDidChangeActiveTabGroup` stops firing eventually for 2 empty groups

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#145692]
Testing #145585

Steps:
* have 2 empty groups
* disable `workbench.editor.closeEmptyGroups`
* open editor in group 2
* close editor in group 2
* click left group
* click right group

`onDidChangeActiveTabGroup` stops firing

**Comment by lramos15** [comment]
This is because we don't have a GROUP_CLOSE event therefore I treat the last closed tab in a group as the group itself closing at the moment. This of course causes issues depending on which way the model updates.

We somehow need a GROUP_CLOSE event here
https://github.com/microsoft/vscode/blob/9a7cb26c1146f5fc7b92248219d61163a0e4279b/src/vs/workbench/common/editor.ts#L955-L973

**Comment by bpasero** [comment]
> I treat the last closed tab in a group as the group itself closing at the moment

Ok that will account for lots of issues.

**Comment by bpasero** [comment]
Please use these events from the `IEditorGroupService` to properly track added and removed groups:

https://github.com/microsoft/vscode/blob/e0528579bff02ccef321c0bee31185db7b711a26/src/vs/workbench/services/editor/common/editorGroupsService.ts#L160-L168

I am not sure we really need to add `GROUP_CLOSE` event if you can use above.
