### ISSUE TITLE
Discard Changes button is not necessary

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#145695]
Testing #145525

<img width="658" alt="image" src="https://user-images.githubusercontent.com/10746682/159488555-852724c4-3620-4aa8-a196-0f0a5392a09b.png">

I do not see the reasoning behind **Discard Changes** button - The dialog mainly talks about syncing changes. Dialog will be simple for me to understand if it asks me to Sync or Not to Sync. To discard, I would always choose not to sync and discard changes going to SCM view.

I would not discard changes without looking at them.

**Comment by joyceerhl** [comment]
The Discard Changes option is motivated by the scenario where the user revisits a PR where they have uncommitted changes that were made from so long ago that they have no interest in keeping them. I think @rzhao271 described this scenario at the UX sync.

**Comment by sandy081** [comment]
If user does not want to keep them, user can always discard them from SCM view where user can see what files got changed and is more comfortable/easy to take decision. But where as in the dialog, user does not have any of this info and not be in a good position to choose this option.

**Comment by joyceerhl** [comment]
That's fair feedback and I think @lszomoru had the same reaction. I tried out removing the Discard Changes option and I don't think this change detracts from the utility of the dialog since we already recommend to sync. Closing as I've pushed this change.

![image](https://user-images.githubusercontent.com/30305945/160174502-725ebdc3-f806-4e76-99a6-60a4dec4fe2f.png)
