### ISSUE TITLE
File nesting patterns should use ${ not $(

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#145663]
Testing #145640

`explorer.fileNesting.patterns` should use `${` for patterns, and not `$(`.
That way it will align with `window.title` setting and the `configurationResolverService` thus `launch.json` and `tasks.json`

fyi @alexr00 @bpasero 

![Screenshot 2022-03-22 at 11 20 41](https://user-images.githubusercontent.com/1926584/159459074-d5652365-bf68-43fe-9461-1e4bc06f9bc7.png)

**Comment by JacksonKearl** [comment]
But files.exclude and search.exclude use `$(basename)`... I don't think there's a way to be fully consistent here.

**Comment by isidorn** [comment]
@JacksonKearl weirdly `files.exclude` and `search.exclude` do not mention this anywhere in their docs.
I leave this up to you, what you think is best :)

**Comment by JacksonKearl** [comment]
They try to, but it get's swallowed by the codicon matcher... I use` $\u200b$(basename)` (nonbreaking space) in the docstrings for this reason
<img width="918" alt="image" src="https://user-images.githubusercontent.com/8586769/159530623-27ee1e8f-9e92-40f6-a64b-93171c385411.png">

<img width="711" alt="image" src="https://user-images.githubusercontent.com/8586769/159530720-15e52dfc-2bb4-46d2-9ad3-0b423218f355.png">

**Comment by JacksonKearl** [comment]
I'll probably move over to `${..}`, it seems to be pretty widely adopted in Core and gets out of the weird hacks I've needed to implement to avoid being treated as a codicon. 

We've used `$(basename)` for `search.exclude` since the beginning of time... https://github.com/microsoft/vscode/blame/21d1c6249b900acf1e511f6b6d5c6022c787d51b/src/vs/base/common/glob.ts#L298
