### ISSUE TITLE
Extensions: use a real dialog to confirm uninstall

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#14578]
We should try to avoid the message service as much as possible for asking the user for confirmation. I suggest to open a real dialog after the user clicks on "Uninstall" instead of using message service.

We do the very same for all other UX interactions that require confirmation (e.g. deleting a file, undoing all changes).

@sandy081 can we do this for October?

**Comment by sandy081** [comment]
@bpasero It was removed in favour of using single prompt to user while uninstalling independent extensions or extensions with dependencies. 

I am ok to revert back to old behaviour, but this could lead to bad user experience when uninstalling extensions with dependencies.

It cannot be merged in the renderer to show a single real dialog because
- The second prompt (uninstall only, with dependencies, cancel) comes from Shared process
- I am not sure if we can use real dialog to show more than two options

**Comment by sandy081** [comment]
Moving this to November after discussing in the stand up

- Leave the current experience
- Allow to show a real dialog from shared process.

**Comment by bpasero** [comment]
No, the dialog can only be used from either the Electron browser process or render process, not from the electron node integration. You can show as many buttons as you like in native dialogs.

**Comment by sandy081** [comment]
Right, it can only be shown from renderer. Even the message prompt is shown by the renderer. Idea is that shared process ask the renderer to open a dialog rather than a message prompt. 

Shared process driving this confirmation / message helps when user does the same from CLI
