### ISSUE TITLE
Settings editor: current UI does not clearly show that the setting is actually changed for language

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#145716]
Testing #145588

I thought @lychung7 had some mocks for more clearly showing that a setting has been modified for a particular language.
Currently we just show the blue line as seen in the example below. I think it is not prominent enough, and it is not quite clear that this setting is overriden for markdown.

Sorry if there is work planned already for next milestone and this issue is duplication.

fyi @sandy081 

![Screenshot 2022-03-22 at 15 02 17](https://user-images.githubusercontent.com/1926584/159499382-ade95ede-5d45-4955-ad88-9f6f140f922f.png)

**Comment by rzhao271** [comment]
Verification steps:
1. In the Settings editor, add a language filter using the funnel button.
2. Notice that the scope tabs (that say User, Workspace, etc.) change to indicate that a language filter has been added. These indicators are useful because it clarifies which language filter has been applied. If a user tries adding two or more language filters, it should only indicate that the first language filter is being applied.

Known issues:
1. Long language names don't look so good, and sometimes they don't display at all.
2. The language filter gets cut off easily for the Remote tab in a remote container, due to how long the remote container name is. I might rearrange that text so that the language override comes first.
