### ISSUE TITLE
$(mark-github) in notification

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#145722]
Happens during GitHub sign in.

![image](https://user-images.githubusercontent.com/2931520/159503473-9f1526ac-ba93-41cf-a743-69dea5eeabdc.png)

Not sure who provides the GitHub auth provider.

**Comment by TylerLeonhardt** [comment]
@bpasero I tried moving from a status bar item that handled progress to the `withProgress` API. This was the result of that:

1. spinny icon and GitHub icon are too close together
2. `$(mark-github)` gets displayed in notification.

I don't think I have any control over this since I'm just using the `withProgress` API but let me know if there's a way.

If not, I can remove the `$(mark-github)` from the title for now.

**Comment by bpasero** [comment]
I think we made the decision at one point to not allow icons in notifications to avoid abuse.

> spinny icon and GitHub icon are too close together

You mean in the status bar?

**Comment by TylerLeonhardt** [comment]
> I think we made the decision at one point to not allow icons in notifications to avoid abuse.

In this case, can you strip out any icons in notifications?

> You mean in the status bar?

Yeah. They're like right next to each other in the screenshot

**Comment by bpasero** [comment]
Yeah not sure why we don't do that.

As for icons in the status bar: not sure what to do here, if we just add margins we might break it for existing extensions that have worked around it.

**Comment by TylerLeonhardt** [comment]
> not sure what to do here, if we just add margins we might break it for existing extensions that have worked around it.

@bpasero So one of the ways I tried to work around this was adding a space in front of the icon: 

https://github.com/microsoft/vscode/blob/39c6779828ffd46db840b6f0d6d1fc9e5156207c/extensions/github-authentication/src/githubServer.ts#L181

but I didn't see any noticeable change. Locally I tried adding like 100 spaces and still get:

![image](https://user-images.githubusercontent.com/2644648/159567385-07b3bc7b-0c55-4927-84d9-442ff000fca6.png)

**Comment by bpasero** [comment]
I have extracted the status bar issue into https://github.com/microsoft/vscode/issues/145852

**Comment by jrieken** [comment]
> In this case, can you strip out any icons in notifications?

The API doc should spell out when a label supports theme icons, like [here](https://github.com/microsoft/vscode/blob/4cb502497e9745b63c443e6bc9ea939b9402da4e/src/vscode-dts/vscode.d.ts#L7300-L7301). 

@bpasero I not sure that simply stripping out `$(abc)` is valid. This means that messages have changed their behaviour and that escaping is needed - despite us not supporting theme icon rendering here

**Comment by bpasero** [comment]
Yeah thanks for reopen, the fix was not clever. Instead I am now stripping the icon only for this particular case, where a progress starts in the status bar where icons are supported and then moves to be a notification by the user clicking it. Since this is not something the extension can control, we have to strip the codicons there.

But we should not strip them from all notification messages 👍

**Comment by bpasero** [comment]
@TylerLeonhardt to clarify:
* use `ProgressLocation.Window` and you can use codicons, the progress will show in the status bar and when shown in notifications have the icon removed
* use `ProgressLocation.Notification` and you cannot use codicons, so please remove from message

I will update our JSDoc too to make that clear.

**Comment by TylerLeonhardt** [comment]
@bpasero I only use `ProgressLocation.Window` so I don't think I need to do anything here.

https://github.com/microsoft/vscode/blob/39c6779828ffd46db840b6f0d6d1fc9e5156207c/extensions/github-authentication/src/githubServer.ts#L181

Thanks for jumping on this!

**Comment by bpasero** [comment]
Yeah you are all set.
