### ISSUE TITLE
Explorer file nesting settings should be resource scope where possible

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#145782]
Settings from explorer file nesting that can be made resource aware really should be made as such, otherwise this setting will not work so well for multi root workspaces where you have multiple folders opened.

**Comment by rchiodo** [comment]
@JacksonKearl do you have any good repro steps? Thanks.

**Comment by JacksonKearl** [comment]
Open a multiroot workspace with vscode as one of the roots (or just set "explorer.experimental.fileNesting.enabled": true in the settings.json of a different folder). Verify that nesting is enabled for that folder in the root, but not other folders in the workspace.

**Comment by rchiodo** [comment]
Maybe I'm misunderstanding, but this doesn't seem to be supported?

I get this in a multifolder workspace:

![image](https://user-images.githubusercontent.com/19672699/159998202-845262a3-109d-49a1-a4b9-2268cfb3fc25.png)

I thought this issue was to allow that specifically? Cause it works in I just open the folder.

**Comment by JacksonKearl** [comment]
Good catch, I missed updating the registration. Fixed: 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/8586769/159999149-c4398cb5-ed63-46f1-8ac0-37fd47840545.png">
