### ISSUE TITLE
Uncommitted changes needs a different icon

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#145781]
<img width="300" src="https://user-images.githubusercontent.com/35271042/159553092-3bf37341-1e83-468a-90b7-c20aedfc8131.png">

It seems that uncommitted changes are not commits yet, so wonder if they should have different icons? cc @daviddossett @lychung7

**Comment by bpasero** [comment]
@lszomoru that icon reminded @isidorn of the 1980s, so we had to change it.

**Comment by daviddossett** [comment]
Agreed. Also, the circle used for local history changes has a different stroke width and size anyway so I've been meaning to tune these up. 

Will take a crack at this 👍

**Comment by lszomoru** [comment]
what's so bad about the 1980s? 😄 When the "circle" will be adjusted to match the stroke and size, the difference between the two icons will be extremely subtle. I would advocate for using icons that are easily distinguishable.

**Comment by bpasero** [comment]
Fyi "Uncommitted changes" are gone from timeline view.

**Comment by lsp1138** [comment]
Can I add my two cents - i am sorely missing the "uncommitted" changes from the timeline - it was integral to my workflow. I dont care so much about local changes at all - but need the uncommitted to see what has changed before i commit it. Basically the "uncomitted" is the visual for doing a "git diff" .. am a bit upset that such a good feature of visual code was taken away. Lets progress not regress:) would appreciate if this can be added back or at least be configurable. cheers Lars

**Comment by bpasero** [comment]
@lsp1138 the same information is always accessible from the SCM changes view, no? There is even a badge indicator over the view to see that you have uncommitted changes.

**Comment by lsp1138** [comment]
Sure i can find it also using git diff. However, it was really useful to see the uncommitted changes in the timeline since it sits inside the file explorer tree view - which is the only view i usually use - and because that tree view is usually open i had a quick way of seeing if there were any uncommitted changes and also to see them by clicking on that change. So it was faster than clicking on the git scm or doing a git diff.

I try to avoid using the context menus too much it is too much clicking, usually the tree view is open with the timeline. I really only use git from the command line (as I suspect most people do as it is platform/editor independent). 

My two cents - sad to see this go and I wanted to ask if possible to at least make it configurable as it was one of the most useful features i was using all the time. 

cheers
Lars

**Comment by bpasero** [comment]
Fair, please upvote https://github.com/microsoft/vscode/issues/147278 then.

**Comment by bpasero** [comment]
@daviddossett any thoughts on a different icon? If there is a way to bring the uncommitted changes back then I think it would make sense to show a different icon to distinguish a git commit from uncommitted changes.

**Comment by daviddossett** [comment]
We could consider using a new icon similar to `circle-outline` (but with identical stroke width/size) for uncommitted changes since it looks more like a formal change that isn't yet on a git timeline. That would mean we would need to re-think the icon used for local history.

<img width="970" alt="CleanShot 2022-04-20 at 10 12 46@2x" src="https://user-images.githubusercontent.com/25163139/164286103-8060458d-c3eb-4ed6-a4ca-6488a4b05b14.png">

Alternatively, we could be to give a nod to the filled circle pattern we use for unsaved editors using `circle-filled` if uncommitted changes was viewed as a sort of dirty state. Other ideas from existing icons could be `edit` or `diff`:

<img width="884" alt="CleanShot 2022-04-20 at 10 08 16@2x" src="https://user-images.githubusercontent.com/25163139/164285361-3875de2f-dabb-4898-9495-2af4442e4771.png">

**Comment by daviddossett** [comment]
I think it's ok to use it for both IMO. They aren't worlds apart conceptually in that they are both representing some sort of isolated change, not yet included on a formal timeline.

In any case, I've [proposed a new icon](https://github.com/microsoft/vscode-codicons/pull/106) in the codicons library to align with the specific metrics of these other git icons:

### Before
<img width="184" alt="CleanShot 2022-04-22 at 12 03 41@2x" src="https://user-images.githubusercontent.com/25163139/164778060-85643037-8596-441c-b11b-07b4da505dc5.png">

### After
<img width="197" alt="CleanShot 2022-04-22 at 11 58 13@2x" src="https://user-images.githubusercontent.com/25163139/164777481-09da43a3-e89c-4619-82f6-7a179bb256d1.png">

**Comment by bpasero** [comment]
Pushed that: ![image](https://user-images.githubusercontent.com/900690/164885423-5cc3d3c2-4f63-4b24-a192-696d327e773f.png)

**Comment by lszomoru** [comment]
Would it make sense to use the "full circle" icon that we are using in the editor tab when a file has unsaved changes?

**Comment by bpasero** [comment]
I like how now the icon looks very similar to the git commit icon, with the exception of not being "connected" yet to the others via a commit.

**Comment by lszomoru** [comment]
No strong feeling about it. Just wanted to bring it up.

**Comment by daviddossett** [comment]
Updated `git-commit` to visually align with `circle-outline` in https://github.com/microsoft/vscode/commit/dc58d4e2d0abde25dd55f588c3fd6e09a67e54b5

<img width="223" alt="git-commit-circle-outline" src="https://user-images.githubusercontent.com/25163139/165362021-5969e2f6-cb63-4d67-9704-61fddbc8c337.png">
