### ISSUE TITLE
Edit settings for language should preserve settings search input

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#145711]
Testing #145588

1. Open settings ui. Type `editor.wordwrap`
2. Click on the "Edit settings for markdown" button
3. Search is now `@lang:markdown`
4. It should be `@lang:markdown editor.wordwrap`. Thus my input should be preserved

fyi @sandy081

**Comment by rzhao271** [comment]
For step 2, I assume you ran the `workbench.action.configureLanguageBasedSettings` command and then selected "markdown" from the quickpick?

**Comment by rzhao271** [comment]
Verification steps: https://github.com/microsoft/vscode/issues/145711#issue-1176830868
Also see https://github.com/microsoft/vscode/issues/145711#issuecomment-1102660239

I also confirmed that the markdown setting shows up there in the first place because an extension has contributed a markdown-specific default override for the `editor.wordwrap` setting. After clicking on the "Edit settings for markdown" link, we currently don't show the default override indicator, which is a known issue that is being tracked separately.
