### ISSUE TITLE
Dialog when there are no incoming changes is confusing

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#145700]
Testing #145525

<img width="601" alt="image" src="https://user-images.githubusercontent.com/10746682/159490433-664392c4-89ef-4b95-9bee-168758d18bb5.png">

Above dialog when there are local changes and no remote changes and setting is set to `promptAlways` is confusing to me and seems not necessary. I would simply not show any dialog in this case. This will simplify the setting. I am not sure how this dialog helps me.

**Comment by joyceerhl** [comment]
:+1: I thought this might be helpful as a reminder that auto syncing would be paused due to the uncommitted changes, but it's not right to use the modal dialog in this scenario because user input isn't immediately required (they're not in an outdated state yet). Closing as I've pushed a change to drop the `promptAlways` option.
