### ISSUE TITLE
After signing out of GitHub, opening a file just hangs

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode#145796]
Testing #145623, not sure if it is related.

- go to https://insiders.vscode.dev
- sign into GitHub to access a remote repository
- click on the Account icon in the Activity Bar
- Sign out of GitHub
- Click on a file in the explorer (one that may have not been already opened/cached in the Browser)
- Say `Cancel` when prompted to sign in to GitHub again
- Click on a file that has never been opened

Result: Hangs, just get the progress indicator moving across the top of the editor

![image](https://user-images.githubusercontent.com/1487073/159566080-af81cf30-4c1a-4a09-8f4c-d342c00234cd.png)

Ideally there is another notification that says "You are not signed into GitHub, please Sign In to access this repository" with a button that lets you sign in.

**Comment by TylerLeonhardt** [comment]
@joyceerhl I think this is you? When you cancel auth, an error is thrown by getSession. I think RemoteHub just needs to handle this case better.

**Comment by joyceerhl** [comment]
As soon as you sign in through the accounts menu the file contents will resolve. The reason the editor progress indicator shows up is because when the user hits cancel, we catch the error, trigger the silent auth flow, and wait for the user to authenticate.

Several ideas:
- Do `createIfNone: true` even after the user clicks cancel. That feels a bit aggressive to me if the user already said they don't wait to sign in here.
- Display an error message saying something like 'You must sign in to GitHub to view <filename>' with options to 'Reauthenticate' and 'Cancel'. Hitting 'Cancel' will close the open editor with the unresolved contents
- When the user hits cancel, close the editor for them. The user can retry opening the file and we'll restart the auth prompt flow

**Comment by TylerLeonhardt** [comment]
I like the 3rd one the most - the modal appears when the user takes an explicit action.

And I think I like 1 slightly more than 2 just because Auth is really required for this to work and modal speaks to that "requiredness" more than a notification does......... even though it is jarring.

**Comment by joyceerhl** [comment]
Ah in option 2 I meant a modal error message, btw. I think that might be better than 1, which would put the user into a loop where they click cancel and we keep putting up the auth modal.

**Comment by TylerLeonhardt** [comment]
Gotcha! I still like option 3 over all of them because it feels less jarring IMO.

**Comment by bhavyaus** [comment]
Verified that we now see an dialog asking us to sign in when we sign out of GitHub when trying to open a file after having signed out. Hitting `cancel` causes an error dialog asking to sign in for access to repo.
