### ISSUE TITLE
`onDidChangeTabGroup` needs to tell about the group

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#145737]
Testing #145585

There is no info what changed nor which group changed. how should I use this event?

**Comment by lramos15** [comment]
@jrieken I wonder if we should have a general on change event too. The main reason for me having this void to start with is currently the following events lead to full model rebuilds `GROUP_CLOSE, GROUP_ADD, GROUP_MOVE, EDITOR_OPEN, EDITOR_CLOSE`. So for full rebuilds we don't actually know what group has a change and I wouldn't want to fire a dumby event for all groups unless we should due to their references no longer being stable. Seems like full patching might be necessary to enable this case 🤔

**Comment by lramos15** [comment]
Fixed by https://github.com/microsoft/vscode/commit/381a22e1ae44ccf60f5e54a6a23b1acb4901f5c9


To Verify:
Ensure `onDidchangeTabGroups` returns an array of changed groups. Note in cases of rebuild you will get all groups.
