### ISSUE TITLE
Allow signature help has no active parameter.

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode#145851]
Currently, VS Code will always highlight the first parameter even when the active parameter is null in the [SignatureHelp](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#signatureHelp).

Considering this case:

![image](https://user-images.githubusercontent.com/6193897/159647130-30f25ba9-7b22-4bbd-a2fa-6ddb7d2a8d21.png)

In this case, the cursor is out side of the arguments' brackets. But the first argument is highlighted, which is confusing.

The ideal behavior should be at first the arguments are grey, once the cursor enters into the bracket, the first argument becomes blue.

This is very helpful since signature help is not only used for hint the argument on completion. It's also a useful tool to quickly peek all the overload versions of the method. (without it, user has to go to the definition and find all the overload method from editor or outline view).

**Comment by jrieken** [comment]
> The ideal behavior should be at first the arguments are grey, once the cursor enters into the bracket, the first argument becomes blue.

Unsure about that. I'd say it is questionable that signature help shows while on the name of a method, not on the arguments. Its idea is to only when typing arguments and not to serve as a stick hover.

**Comment by jdneo** [comment]
Understand the purpose is of signature help is only to hint the argument.

I have this idea because I saw the behavior in other IDE:

![hint](https://user-images.githubusercontent.com/6193897/159666026-4d788d88-c210-45f6-98b1-783a4f85c356.gif)

**Comment by jdneo** [comment]
@jrieken

I found that I can set the active parameter to `-1`, then no parameter will be highlighted. But I guess this is not recommended way?

**Comment by jrieken** [comment]
🙉 oh, please don't tell me these tricks... I guess it's OK for now but definitely not recommended.

**Comment by jdneo** [comment]
@jrieken Could we just make the `-1` value as a part of the spec? This won't introduce any breakings, and it's exactly how it works now.

**Comment by mjbvz** [comment]
Closing since there appears to be a reasonable (if somewhat ugly) workaround and we have not seem much follow up interest in this issue since it was opened

**Comment by DanTup** [comment]
@mjbvz if this workaround is going to be the fix, can it be added to the docs? LSP servers that are trying to support multiple editors need to behave to a spec and undocumented VS Code behaviour makes this difficult because when bugs are raised we often have to say "you should ask your editor to do the same as this undocumented VS Code behaviour" which is rather odd 😞

There are other cases where there is no active item besides the one above - it could be that the call has more arguments than the definition has:

```
void foo(int a) {}

foo(1, 2, 3^); // invoked at ^
```

Or that there are named arguments and this one doesn't exist:

```
void foo({ int a }) {}

foo(a: 1, b^: 3); // invoked at ^
```

In both of those cases, it doesn't make sense for any parameter to be highlighted.

**Comment by DanTup** [comment]
@dbaeumer would you accept a PR that specifies this `-1` behaviour in LSP (even if VS Code doesn't document it)? Or accept `null` in LSP and map it to -1 in the VS Code LSP client?

**Comment by dbaeumer** [comment]
We can only add this to LSP if we do the following:

- add a client capability signaling that this is support
- change the spec to support `-1`

**Comment by DanTup** [comment]
@dbaeumer would it be better to use `null` in the spec even if it's mapped to -1 in the LSP client? (using -1 seems like a hack and `null` feels more natural, although it does mean a change in the LSP client that wouldn't otherwise be necessary).

(I don't know if I'll get to it immediately but I'm happy to look at this if you'd accept it - the Dart server is already sending -1's and it'd be nice to be better aligned with the spec)

**Comment by dbaeumer** [comment]
I would definitely accept a PR. We can sort out whether we use `null` or `-1` to make this work. I am open for using `null` as well.

**Comment by DanTup** [comment]
I've opened a PR at https://github.com/microsoft/language-server-protocol/pull/1597 for the spec, and if the names/etc. look good I can make the VS Code LSP client changes to pass the capability and map the `null` to ` -1` for VS Code.
