### ISSUE TITLE
Add a line number parameter for NotebookEditor.revealRange

### ISSUE THREAD

**Issue by alyssajotice** [microsoft/vscode#145800]
I am working on improving the Live Share follow feature. Right now, we use `NotebookEditor.revealRange` to let one guest follow another throughout the workspace. However, this does not work if a cell is larger than the screen. When this happens, we reveal the range, but the viewport goes to the top of the cell, which may not be where the other guest is editing. To fix this, we need to add the line number to the reveal range function, so we can reveal the specific part of the cell that we need to, rather than just the top of the cell. Also, we need the `onDidChangeNotebookEditorSelection` to include the line number of the cell so we can track this. 

cc @rebornix @fubaduba

**Comment by rebornix** [comment]
cc @mjbvz

**Comment by fubaduba** [comment]
Hey @mjbvz and @rebornix!
We're looking at the E2E flow of collaborating Python and Jupyter notebooks for the Build 2022 keynote demo (timelines for which are late April). For those reasons, we would love to be able to prioritize this flow- where a user following another user during a Live Share session, is 'sent' to the 'right' place in the cell being edited, rather than the current default. 

Could either of you provide us an estimate of when this work will be scheduled, and how if our team can provide any further clarity here to move it along?

**Comment by mjbvz** [comment]
@fubaduba We'd take a PR for this. The change would be adding an optional `editorRange` parameter to `NotebookEditor.revealRange`:

https://github.com/microsoft/vscode/blob/111b58221cbba5c9e3c2a6795f62aa85c2022bce/src/vscode-dts/vscode.proposed.notebookEditor.d.ts#L64

**Comment by rebornix** [comment]
@mjbvz do you know if this is still needed for Live Share?

**Comment by mjbvz** [comment]
Closing for now. If live share still needs this, we can revisit
