### ISSUE TITLE
Support cloning via SSH by default when picking a repository using the GitHub extension

### ISSUE THREAD

**Issue by holazz** [microsoft/vscode#145850]
I would like to be able to clone with an SSH URL.

**Comment by joaomoreno** [comment]
@holazz This is already possible today, just paste the SSH URL into the Clone input:

![Recording 2022-03-28 at 14 26 51](https://user-images.githubusercontent.com/22350/160397731-10084690-12d3-4397-8a96-c1edc69f4bb0.gif)

---

With that being said, there's the feature from the GitHub extension which lets you clone repositories without pasting their URL. That's what you're addressing in https://github.com/microsoft/vscode/pull/146124. By default, the feature uses what GitHub defines to be the `clone_url`, which happens to always be HTTPS. We also happen to have automatic authentication against GitHub, making the clone via HTTPS really compelling, since the user never has to worry about auth.

Still, if pasting the URL isn't enough for you and if you'd still like a setting to change the default to SSH, I can happily review the PR. Let me know.

**Comment by holazz** [comment]
@joaomoreno Yes, I would still like a setting to change the default to SSH because of the following points: 

1. In most cases, I will select an item in the list to clone.

![clone-repo](https://user-images.githubusercontent.com/23100055/160515157-31f7ac8c-55d1-48c1-8840-3e3e0dcdef0a.gif)

2. When I initialize a project locally, I want to publish it to GitHub, which is also cloned using HTTPS by default.

![publish-to-github](https://user-images.githubusercontent.com/23100055/160515230-48dcd7ba-5f6d-4eaf-8d84-894c63648449.gif)

**Comment by holazz** [comment]
🙁 When I use HTTPS it always gives this error, SSH doesn't.

<img width="1552" alt="error" src="https://user-images.githubusercontent.com/23100055/160518680-e29adc74-283d-4ff6-bd08-57c6415941e0.png">

**Comment by joaomoreno** [comment]
Oh that's very interesting! Is that error the only reason you'd want this?

It seems that your system is using LibreSSL to connect to https... did you configure this on purpose?

**Comment by holazz** [comment]
@joaomoreno Not just because of this, I do prefer to clone via ssh, would like you to consider this feature if possible. Thanks!

P.S. This error has been resolved, It is my configuration problem. 🙈

**Comment by DonJayamanne** [comment]
@joaomoreno I've changed the setting `github.gitProtocol` to `ssh` and tried cloning a repo (git@github.com:microsoft/vscode-jupyter-lsp-middleware.git), but nothing seems to happen. All I have is a progress indicator at the bottom which does nothing.

FYI - I'm using WSL 2 .

![image](https://user-images.githubusercontent.com/1948812/165393643-22536874-3531-4f25-a90f-c4321a615124.png)

**Comment by joaomoreno** [comment]
@DonJayamanne Can you check `ps ax` to see what's up? It's possible that ssh.exe is pending on a passphrase input? Before attempting this, make sure you can run the same clone command from the WSL 2 command line (eg `git clone git@github...`).

**Comment by connor4312** [comment]
Verified this works on my macbook
