### ISSUE TITLE
feat: add seperate theme for different vs windows

### ISSUE THREAD

**Issue by ykhedher** [microsoft/vscode#145878]
I am not sure if this does exist in VS Code, but when I change the theme for one window it does change for every window I have.
So in my case (the screenshot), I have 3 vs code windows open which I do navigates between them. The problem is that it's hard to know which window is unless you read the name below it. So I think that creating a feature that makes each window have its own theme will make it super easy to know which one you want to go to. 

Thanks :) 

![Screen Shot 2022-03-23 at 12 07 28 PM](https://user-images.githubusercontent.com/47088512/159686553-540f22a7-f9b4-4cd4-b775-fd9e45567d44.png)

**Comment by IllusionMH** [comment]
/question 

You already can change `workbench.colorTheme` in Workspace settings instead of User settings.

You can also apply Workspace specific overrides for UI elements with `workbench.colorCustomizations` and [Peacock](https://marketplace.visualstudio.com/items?itemName=johnpapa.vscode-peacock) extension can help there.
