### ISSUE TITLE
vscode.window.tabGroups.move: support Tab[]?

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#145830]
Testing #145585

if close supports taking a `Tab[]` in addition to a `Tab`, why not `move`?

**Comment by lramos15** [comment]
I think this is a bit different due to how move modifies the model while keeping the tabs valid. Each move has an effect on the index argument that is passed into the model. This means if you wanted to move 3 tabs all to the same view column and index (like a move with Tab[] would do) the end model is probably not what you would expect since the tabs get shifted as things move around. I believe it is best to leave it up to the extension author to loop through the tabs and call move so they can provide different arguments for each move request and better understand how each operation affects the model.

**Comment by lramos15** [comment]
After API discussion this is difficult to get correct as it doesn't have native editor service support. Best to let the extension just loop over the tabs and see how each changes the model since all applied at once can cause unforeseen issues.
