### ISSUE TITLE
Please join to us #standwithukraine

### ISSUE THREAD

**Issue by id-dan** [microsoft/vscode#145999]
Please support Ukraine, more infos here: https://github.com/vshymanskyy/StandWithUkraine

**Comment by id-dan** [comment]
@chrisdias please have a look, and please add banner fast as possible. It is important for Ukrainians.

**Comment by chrisdias** [comment]
Hi –

Thanks for submitting this issue, sorry for not responding sooner. We spent quite some time discussing what we should do here.
 
Microsoft and the VS Code team stand with Ukraine calling for peace, respect for their sovereignty, and the protection of its people. We are horrified by the images and news coming from Ukraine.

We believe the most effective way to help those affected by the conflict is through Microsoft coordinated responses and donations since these can take advantage of existing relationships with aid organizations and help raise visibility to the conflict given its wide coverage, particularly when compared to a technical forum or product repository like this one. You can read more about what Microsoft has done so far here:
 
[https://blogs.microsoft.com/on-the-issues/2022/03/04/microsoft-suspends-russia-sales-ukraine-conflict/](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fblogs.microsoft.com%2Fon-the-issues%2F2022%2F03%2F04%2Fmicrosoft-suspends-russia-sales-ukraine-conflict%2F&data=04%7C01%7CChris.Dias%40microsoft.com%7Cd7849959325b48dd5ab008da0eb1df5e%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637838454376797382%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=5%2FFtDoxkDbUOF05FsE%2B4hBaTpOxcd4kjCKKt7GtfVtc%3D&reserved=0)

https://blogs.microsoft.com/on-the-issues/2022/02/28/ukraine-russia-digital-war-cyberattacks/.
 
I hope this makes sense, thanks again.
 
Chris
