### ISSUE TITLE
Current document icons do not conform to Apple HIG

### ISSUE THREAD

**Issue by Zabriskije** [microsoft/vscode#145942]
Hi folks,
the current document icons are not in line with the [Apple's HIG](https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/document-icons/) ― at least in Big Sur and Monterey.
They also use low-quality / unpolished assets.

<img width="128" src="https://user-images.githubusercontent.com/101254295/159825970-bb914a6f-a16e-460b-afbb-4b548cb8ee47.png"> <img width="128" src="https://user-images.githubusercontent.com/101254295/159830607-5e341424-eaa2-4f9d-9bdc-a5ad5993e102.png"> <img width="128" src="https://user-images.githubusercontent.com/101254295/160016609-67a180b6-ea69-41ee-be19-5d2c364371d8.png">

The first on the left (click on the preview to see it full-size) is the current Java document icon; as you can see the Java logo lines are jagged and the icon uses the Catalina (and previous) document icon layout. The second and third ones are made by me, to recreate the current HIG.
It should be also considered to remove the VSCode logo, which is not displaying at lower resolution anyway.

I can make them and provide already baked .icns, or individual graphic assets if you prefer.

**Comment by misolori** [comment]
Appreciate the issue but these file icons are using out default file icons, [seti](https://github.com/jesseweed/seti-ui), so we are not actually using the real logo but the icon from the file icon library. And while the newer file icons have different assets, we can't specify file icons per platform. These file icons live in a different repository since these contain our branded icons so we unfortunately can't accept a PR. 

Will close as-designed since this is expected for now and if we hear more users wanting an updated file icon we can look at revisiting. Thanks!
