### ISSUE TITLE
What is the purpose of dragMimeTypes?

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#145907]
Testing #145577

It seems like I am able to ignore this and specify any arbitrary mime type in the data transfer item in handleDrag. As long as the mime type exists in the dropMimeTypes, I get feedback and the drop goes through.

**Comment by alexr00** [comment]
Drag and drop in the dom is sync, but we must make it async to work with extensions. Because of that, we can run into the following situation:
1. User drag and drops an item from Tree A to Tree B, or Tree A to the editor.
2. VS Code must immediately process the drop, but we don't yet know what the extension that contributes Tree A is going to add to the drag and drop data transfer in `handleDrag`. This means that the drop target (Tree B or the editor in this example) doesn't know if it will accept the drop.
3. This is where `dragMimeTypes` comes in. By specifying the drag mime types upfront, we can let the drop target know what mime types are coming so that it can provide correct drop feedback.

**Comment by sbatten** [comment]
ah okay, this makes sense. should a warning be logged if the dragMimeTypes array doesn't include the mimetype of the items added in handleDrag?

**Comment by alexr00** [comment]
A warning is a good idea, I'll add it!

**Comment by alexr00** [comment]
No, it will just be in the dev tools.
