### ISSUE TITLE
View height does not update when adjacent container's height changes

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#145996]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.66-insider
- OS Version: Windows 11

Steps to Reproduce:

1. Drag outline section into the search activity bar view container 
2. Run a search with the outline section expanded
3. Collapse the outline search
4. :bug: results appear truncated because the list height isn't updated

![Recording 2022-03-24 at 10 24 11](https://user-images.githubusercontent.com/30305945/159974653-f9225bad-d3cb-47ee-8ec2-0fc5cb129bf0.gif)

**Comment by JacksonKearl** [comment]
Able to hit this consistently on my Windows vm but have never seen it on Mac. Perhaps a timing bug where we're measuring the container too early.

**Comment by JacksonKearl** [comment]
Ah, doesn't repro when motion is disabled. So the search tree tries to measure its height right when it gets the `layoutBody` call, but at that moment the animation hasn't finished so it measures the old height instead of the new one. @sbatten could you signal when the animation is over? `layoutBody` does get passed height information, but search view prefers to let the tree view measure its container because there can be a lot of other elements taking up differing amounts of space in it (whether includes are expanded, replace, search messages, etc).

**Comment by JacksonKearl** [comment]
Ended up just measuring element height, ended up with a but of a fuzz factor I rolled into "margin".

**Comment by roblourens** [comment]
I think this is basically what it used to do, which apparently had an issue: https://github.com/microsoft/vscode/issues/116182

I'm not sure why measuring the height outside the tree had this issue with scaling but the measurement inside the tree was ok. But could you test it with a zoom factor like in that issue?

**Comment by JacksonKearl** [comment]
And I even verified it back then. 

But testing now on MacOS with some different scaling settings and my Windows VM across a variety of resolutions (100,125,150,175,200,225,250), I haven't been able to spot that coming up.

Worth noting my eyes aren't the excelling at distinguishing nearby horizontal lines at the moment.

**Comment by joaomoreno** [comment]
Seems OK to me on Insiders today.

**Comment by joaomoreno** [comment]
Nope, can't scroll more here, despite there being obvious tree rows in there:

![image](https://user-images.githubusercontent.com/22350/163182779-7a6288ad-9ca8-4544-bc52-e4c6e507b12c.png)

Repro:

- Search for `new Promise<void>(resolve`, no search flags active

**Comment by bpasero** [comment]
Marking important as I lost search results to work on because of this.
