### ISSUE TITLE
Can't compute SHA256

### ISSUE THREAD

**Issue by RedstoneWizard08** [microsoft/vscode#146045]
Hi! I was trying to develop a new web extension when this error popped up in the web VS Code log. Can you help me fix it? Thanks!

`[window] [error] Can't compute sha-256: Error: Can't compute sha-256`

**Comment by aeschli** [comment]
This comes from here: https://github.com/microsoft/vscode/blob/main/src/vs/workbench/browser/webview.ts#L11

I suspect you are on Safari and the running on http://localhost: https://developer.mozilla.org/en-US/docs/Web/API/Crypto/subtle#browser_compatibility

@alexdima Can we use a fall back for that scenario? E.g. like here: https://github.com/microsoft/vscode/blob/main/src/vs/base/browser/hash.ts#L27

**Comment by alexdima** [comment]
@RedstoneWizard08 Can you please describe the specific setup you're using?

**Comment by DanielBaumert** [comment]
[chromium ](https://www.chromium.org/blink/webcrypto/)
> Access to the WebCrypto API is restricted to [secure origins](http://www.chromium.org/Home/chromium-security/security-faq#TOC-Which-origins-are-secure-) (which is to say https:// pages).

**Comment by alexdima** [comment]
> Ok to reopen and add a fall back?

@aeschli When running on localhost, the web worker extension host iframe does not use sha256 because it isn't served from our CDN, but directly from the server running on localhost. I would really like to understand the use-case before us implementing by hand sha256.

@RedstoneWizard08 What are the steps to reproduce?
