### ISSUE TITLE
💢💢Suggestion problem💢💢

### ISSUE THREAD

**Issue by smithliam** [microsoft/vscode#146088]
I'm not sure why this is happening but as far as I checked, this happens with all suggestion extensions.

An explanation of why it happens:

- https://github.com/tailwindlabs/tailwindcss-intellisense/issues/458#issuecomment-1013118943

Video:

https://user-images.githubusercontent.com/101414008/160208711-73e7d0d3-922f-40e3-a66f-12a1bf39393b.mp4

My active class suggestion extension at the time that I was recording the video:

![Screenshot 2022-03-25 151055](https://user-images.githubusercontent.com/101414008/160208938-c11aa4c4-7cc3-42cc-864c-e958d4228fff.png)

---

![Screenshot 2022-03-25 151649](https://user-images.githubusercontent.com/101414008/160209385-4955e1f6-b813-49fb-96ce-15c707e02a3f.png)

![Screenshot 2022-03-25 151639](https://user-images.githubusercontent.com/101414008/160209394-0ad3fed1-6319-4d8c-a30c-5d6c8921ca74.png)

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc009:30452663
pythonvsnew555:30457759
vscscmwlcmc:30438804
vscgsvid1:30447480
cppdebug:30451566
pynewfile477cf:30450039
```

**Comment by Lemmingh** [comment]
Please disable "Snippets Prevent Quick Suggestions":

```json
"editor.suggest.snippetsPreventQuickSuggestions": false
```

---

An alternative solution is manually triggering suggestion when in a snippet.

**Comment by smithliam** [comment]
> Please disable "Snippets Prevent Quick Suggestions":
> 
> ```json
> "editor.suggest.snippetsPreventQuickSuggestions": false
> ```

Thank you so much @Lemmingh, this☝️ works.

---

Is this going to get fixed eventually? It makes suggestion plugins limited/broken because you don't always get the suggestion...

**Comment by Lemmingh** [comment]
Not sure what do you mean.

The `snippetsPreventQuickSuggestions` setting was introduced to solve the interference between snippet and quick suggestion: #50776

So, it depends on your workflow. If it's safe to always enable quick suggestion, turning `snippetsPreventQuickSuggestions` to `false` works best for you. Otherwise, manual triggering is the right choice.

---

In case you don't know why I talk about snippet:

The [Emmet in VS Code](https://code.visualstudio.com/docs/editor/emmet) is powered by [snippet](https://code.visualstudio.com/docs/editor/userdefinedsnippets).
