### ISSUE TITLE
Inline suggestions aren't multicursor aware

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#146041]
* enable inline suggest via `editor.quickSuggestions` and `inline`
* have multiple cursors and type `con`
* accept the inline completion
* only the primary cursor is completed

**Comment by emanuelescarabattoli** [comment]
I confirm this behavior, as you can see from the following screenshots.

Before to hit `tab`:

![Screenshot 2022-05-06 at 12 01 52](https://user-images.githubusercontent.com/38425260/167111312-220b6da8-992e-4aff-89f4-a70e7068f8b8.png)

After hitting `tab`:

![Screenshot 2022-05-06 at 12 01 58](https://user-images.githubusercontent.com/38425260/167111354-7ce8b1cc-6661-4ee7-b3db-3e66a33558da.png)

Expected behavior:

![Screenshot 2022-05-06 at 12 02 11](https://user-images.githubusercontent.com/38425260/167111390-0ce10d79-1060-4e4e-9cae-f9c4e36aafdc.png)

**Comment by riskoviv** [comment]
The workaround I use for now is press `Ctrl + Space` and select suggested variant by `Tab`/`Enter`, but selecting it just by `Tab` would be a lot better of course.

**Comment by Semesse** [comment]
Hello, team~ I'd like to fix this issue, but I'm not sure if there's any case the `completion` item would be so complicated that we need to calculate how many characters we should overwrite before each cursor. Or I guess we can insert ghost text for any existing cursor as an intuitive fix?

**Comment by hediet** [comment]
@Semesse unfortunately the code is not very straight forward.

**Comment by Entwaze** [comment]
This and triple line click? Absolutely Pathetic. What do these Microsoft developers must give  BJs to complete lines of code instead? 
"Hey man we can just take out triple-click line select and multi-cursor autofill, i know even the shi*iest editors have these things, but i just realized i can give a BJ to the guy in the other room and then hell select my code for me, so now noone needs these features."

**Comment by Tomaqa** [comment]
I guess that showing the ghost text only at the first cursor as it is now (i.e. not at all cursors) is not ideal but quite OK, while the priority is accepting the suggestion at all cursors?

**Comment by riskoviv** [comment]
@Tomaqa, yes, you're right. Showing the ghost text is not so important, main issue is lack of inserting of suggested text to positions of all cursors.

**Comment by hediet** [comment]
We have this for a while now 🥳  https://github.com/microsoft/vscode/issues/205562
