### ISSUE TITLE
Settings: some links between settings are broken

### ISSUE THREAD

**Issue by Spongman** [microsoft/vscode#146084]
Issue Type: <b>Bug</b>

- open settings
- search for 'font'
- in the settings nav tree, choose 'Features/Terminal'
- the help text for "Terminal > Integrated: Font Family" says "this defaults to _Edtiro: Font Family_'s value" with a link.
- click the link.

it should navigate to that setting. it doesn't.

This also repos in 1.65.2 (release).

VS Code version: Code - Insiders 1.66.0-insider (c63ed49b4b164210301f4f8a09079aa4de53b870, 2022-03-25T14:30:54.397Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No
Remote OS version: Linux x64 5.10.60.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz (6 x 2904)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|47.66GB (3.38GB free)|
|Process Argv|--crash-reporter-id e6e8bf0f-8ff2-4e01-a3ad-6aaeed8c91cc|
|Screen Reader|no|
|VM|33%|

|Item|Value|
|---|---|
|Remote|WSL: CentOS7|
|OS|Linux x64 5.10.60.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz (6 x 2904)|
|Memory (System)|37.34GB (16.90GB free)|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
better-cpp-syntax|jef|1.15.13
remote-containers|ms-|0.230.0
remote-ssh|ms-|0.77.2022032415
remote-ssh-edit|ms-|0.77.2022032415
remote-wsl|ms-|0.66.0
doxdocgen|csc|1.4.0
better-cpp-syntax|jef|1.15.13
cmake-tools|ms-|1.10.5
cpptools|ms-|1.9.7
cpptools-extension-pack|ms-|1.1.0
cmake|twx|0.0.17

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
wslgetstarted:30449409
vsclayoutctrc:30405799
pythonvspyt640:30438691
vscscmwlcmc:30428972
vscgsvid2:30433758
pynewfile477:30451556

```

</details>

**Comment by Spongman** [comment]
there's a bunch of links that are broken, including, but not limited to ones in:
- Features/Search: Exclude
- Features/SCM: Input Font Family
- Text Editor/Editor: Format On Save Mode

**Comment by rzhao271** [comment]
This issue occurs because the behaviour when there is a search query is different than the behaviour when there isn't one.
When there is a search query, we apply a filter such that clicking on a table of contents (ToC) entry on the left side of the Settings editor only shows settings that fall within that group.
When there is no search query, clicking on a ToC entry scrolls the Settings list on the right side to show the group setting (which appears in the list as a header), but it doesn't filter out settings.
Therefore, clicking on a settings link while there is a search query results in a situation where the Settings list is unable to scroll itself to a linked setting that is in another group within the same search result.

Relevant code pointers: https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/preferences/browser/settingsEditor2.ts#L780-L789
https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/preferences/browser/settingsEditor2.ts#L619

![Screencap demo](https://user-images.githubusercontent.com/7199958/160937791-e4a719a5-2b7a-4cb6-ae6b-52dfc4e3a300.gif)
