### ISSUE TITLE
Escape button does not close context menu nor it closes Search Box

### ISSUE THREAD

**Issue by rockycastaneda** [microsoft/vscode#146159]
I have searched all existing issues.  This had similar ones in other submissions but this one totally does not Exit the context and the Search box no matter how many times you click the Escape key.

**Comment by gjsjohnmurray** [comment]
I suggest you use the guidance at https://github.com/microsoft/vscode/wiki/Keybinding-Issues to investigate where the Escape keypress is being routed to on your system.

Also try the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

Tip for opening future issues is to use Report Issue from the Help menu. That will include the basic version and platform information which you forgot to provide here.
