### ISSUE TITLE
Revert Source Control Count Change

### ISSUE THREAD

**Issue by samchungy** [microsoft/vscode#146238]
This has been annoying me since one of the later updates. Previously the number on the left represented how many pending changes I have but now the Icon Number is shared with the total number of problems in the code

Right after I commit something, it will show that I have 27 problems but to me it looks like I still have pending changes which is super frustrating as I always click on it and then see now files changed in that tab. It is a very poor user experience.

![image](https://user-images.githubusercontent.com/18017094/160571492-ec48b11b-a62d-4089-b23c-a61b71253873.png)

Only show the count for pending changes for the source control icon. This number should only reflect anything related to source control, not issues with the code.

**Comment by lszomoru** [comment]
That seems like a bug to me. Couple of questions to ry to track down the issue:
* What version of VS Code are you running?
* Are you able to reproduce the problem in VS Code Insiders?
* Are you able to reproduce the problem when starting code with `--disable-extensions` flag?
* Have you moved the SCM viewlet around? Are you able to reproduce the problem after invoking the `View: Reset View Locations` command?

**Comment by samchungy** [comment]
Sorry for the delayed reply! You responded wayyyy quicker than I thought you would 🤩 👏 

1. Version: 1.66.0
2. Not sure
3. Yes. - Video here https://drive.google.com/file/d/1EpxoDpkCT5IB5z78U8ej6QFrFAy90jMa/view?usp=sharing
4. That looks like it did it! Not sure how problem ended up under the source control icon. Thanks!

**Comment by lszomoru** [comment]
@samchungy, thank for the update. While I am glad that resetting the view locations resolved the problem, I still think that there is a bug here that I would like to get to the bottom of. @sbatten, could you please look at these steps and let me know if this is an issue with the SCM viewlet or with the Problems view.
1. Reset the view locations
2. Modify a file in order to introduce some problems
3. Drag the SCM viewlet into the bottom panel
4. Drag each SCM view back onto the activity bar
5. Drag Problems view into the SCM viewlet
    * SCM viewlet shows a badge for the number of problems
7. Drag the Problems view back into the bottom panel
    * SCM viewlet shows a badge for the number of problems

**Comment by sbatten** [comment]
related https://github.com/microsoft/vscode/issues/135918... I tried repro-ing but I did not get the persisted badge after moving the problems view back. that said we do not handle multiple views with badges in the same container well, as seen in the linked issue.

**Comment by lszomoru** [comment]
Closing this issue in favour of https://github.com/microsoft/vscode/issues/135918.
