### ISSUE TITLE
Missing documentation for Webview.postMessage

### ISSUE THREAD

**Issue by m-paternostro** [microsoft/vscode#146253]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.65.2 (Universal) (Commit: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1)
- OS Version: Mac OS

Steps to Reproduce:

1. Easy: F12 anywhere _Webview_ is used

I created this as bug because I sincerely believe the questions below should be explicitly answered right in the the code documentation. But, to be honest, I spent a few seconds wondering if this should be just a question.

What I am trying to find out is how to handle the return of _Webview.postMessage_. In particular:
1. Does the return resolves to true if sending the message worked and false otherwise? If this is correct, what are examples of issues that the method can detect? For example, is false returned due to a timeout?
2. If the return is a promise, should we "await" on it before sending another message? Using different words, can we invoke _postMessage_ multiple times without waiting for the result of the previous one to resolve? Even if we can, would this be a good practice?  

Btw, it would be great if these question could be answered here so we don't need to wait for this to make into the code. ;-)

Thank you so much for all the hard work. VSCode rocks.

**Comment by mjbvz** [comment]
First the easy part: no you don't need to await anything. The messages will always be delivered sequentially and it's entirely up to your extension to decide what makes sense

As to what the result return value of `postMessage`, though? I wouldn't rely on it (see the next part for an explanation). If you want to confirm that a message is received inside the webview, you can instead have your webview post acknowledgement messages back to your extension. This guarantees that the message has been handled.

---

Looking into this, the response and behavior of `postMessage` is kind of a mess at the moment tbqh

Right now `postMessage` always returns `true`. The promise also resolves as soon as the main VS Code process receives the message, not when we actually try posting it to the webview

A few issues with this:

1. Posts to webviews in the background end up getting queued until the webview becomes visible again. This can result in a large number of messages being dumped from the queue into the webview once the webview becomes live again.

   In this case, even though messages are queued the `postMessage` promise still resolves right away.

2. There is no way to tell that the message is dropped (such as a queued message for a webview that is then destroyed)

I'm going to try fixing this so that `postMessage` does what you'd expect, but there's a fair chance this will end up breaking extensions that rely on the existing behavior so I may need to revert it again

**Comment by m-paternostro** [comment]
Thank you so much! Great insight.
