### ISSUE TITLE
Provide option to disable scm decorator pattern

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#146220]
Refs #142809

From @joaomoreno:

> it this optional, even if enabled by default? I'm finding it quite distracting

**Comment by ojvribeiro** [comment]
It is nice to have such a feature for a11y, but making it optional for who doesn't need it (and don't want it) would be nicer.

**Comment by infinnie** [comment]
Different widths might break the layout.

**Comment by mkalvas** [comment]
Since my issue got closed as a duplicate I'm cross-posting some of the conversation from there:

My initial feature request:

> Following [the update to source control decorators in 1.66](https://code.visualstudio.com/updates/v1_66#_updated-source-control-decorators), users are forced to have striping over their modified lines.
> 
> I believe that the VS Code team has made such an effort to allow even the smallest of customizations to our environments that this is a bit of a miss. Users should be able to customize whether they see stripes or not.
> 
> There are two ways that I see to do this
> 
> 1. Create a setting for `editorGutter.modifiedForeground` that can be set for the stripe color, transparently keeping striping as an option but allowing people to set this and `editorGutter.modifiedBackground` to the same color and making it appear solid.
> 2. Create a setting that disables striping, though this would likely be more work under the hood to use different CSS based on that.
> 
> One other thing to note. The current striping color is set to `editor.background` instead of `editorGutter.background` which I find odd. If I have a white editor background, a black gutter, and a yellow setting for my `editorGutter.modifiedBackground`, my stripes are now yellow and white on a black background. If anything, it should use the same color as the gutter for the background to ensure this weird (highly inaccessible) situation won't happen and it would always appear "transparent" to the gutter.

Some more discussion and a workaround from @tycode

> In my case, the striping pattern messes with my eyes to the point I can't concentrate on coding. This is probably partially due to the fact that the stripes don't line up from one line to the next - there's a duplicate line of pixels between lines of text (see image).
> ![image](https://user-images.githubusercontent.com/683985/161103822-94f11f30-68c1-48e3-a6b1-84a03f9b3bf7.png)
>But even if the pattern was correct, I imagine I'd still have a problem with it. So there is an accessibility reason to make this optional.
> 
> I had to spend the next half hour constructing a monkey-patch to effectively revert this before I could do anything else. In case anyone else is interested, i.e. has a similar problem and needs something to work with before there's an update to properly address this, I'm providing it here. You'll need to use "Help > Toggle Developer Tools" and paste this in the console on each new/reloaded window.
> 
> **Standard warning: pasting random code from the internet in the console is dangerous if you don't know what the code does.** This is a benign CSS addition, but I encourage you to check that for yourself if you wish to use it :)
> 
> ```
> (function(){var x = document.createElement('style');
> x.innerText = ('.monaco-editor .dirty-diff-modified'+
> '{background: none; border-left: 3px solid #71b9e3;}'+
> '.monaco-editor .dirty-diff-modified:before'+
> '{transform: none; background-image: none; background-color: #71b9e3;}');
> document.head.appendChild(x);})();
> ```

Additionally, just using developer tools to change the `background-image` linear gradient colors to all be the same on the `div` and `::before` elements is a temporary way to adjust this until you close the app.

I'm in favor of the foreground/background approach so the stripes are available to those who like them and can be removed by those who don't by making them the same color.

**Comment by anthroid** [comment]
These decorations also ignore existing user settings: #146574

**Comment by Z-E-D** [comment]
I am sorry for a newbie question. If someone could tell me, are these decorations visible only with the source control?

What if I don't use source control and I just want to see these decorations for modified/added lines with normally opened files. Is that even possible in VSCode? I had that thing in the previous text editor and I like it.

**Comment by i007c** [comment]
@Z-E-D no! you need to use somthing like git

**Comment by Z-E-D** [comment]
[i007c](https://github.com/i007c) Thanks for the reply.

I just opened a new issue with the request for this (#146626). It is funny that 20 MB text editor could do that out of box. To much hassle with that Git thing if I want just to edit a simple shopping list or something like that.

**Comment by i007c** [comment]
@Z-E-D what editor you used to use?

**Comment by anthroid** [comment]
> @Z-E-D no! you need to use somthing like git

Isn't this what [Local History](https://code.visualstudio.com/updates/v1_66#_local-history) does?

**Comment by Z-E-D** [comment]
@[anthroid](https://github.com/anthroid)

I am not sure if that question is for me since you quoted @[i007c](https://github.com/i007c).

Supposing that the question is for me. If you look at my mentioned request, you will see the screenshots of two editors that have similar option. You just open any file from disk, even for the first time without any previous saving, and right when you start modifying it you get decorators for modified/added lines.

Besides, I cannot get Timeline and Local History to show me these decorators no matter what I tried. The animated screenshot for Local History on that link is not very informative and maybe I am doing something wrong.

**Comment by anthroid** [comment]
@Z-E-D Both actually. For you to take a look at the Local History feature if you hadn't already seen it, and for @i007c for the same reason given their response.

It appears that this is _supposed_ to be how it works, but I just did some testing, and I also can't get it to work like it shows in the screenshot. According to the release notes, that's what it's supposed to do (make any file act like it's using SCM by storing revisions in a local database for restore/comparison).

**Comment by gjsjohnmurray** [comment]
@anthroid @Z-E-D with Local History you can perform comparisons, but you don't get the quickdiff margin markers of what has changed.

**Comment by Z-E-D** [comment]
I am really sorry for hijacking this thread since my request is not directly in regard with this issue. Although, I too would like to see these decorators configurable, with the option to switch them off completely. Both editors that I mentioned have the option to make them disappear.

I just need to repeat if that was not already obvious. With the mentioned editors you don't need to have saved anything or to do any comparison to be able to get these decorators - you just open any file, start modifying it and you get these decorators immediately. Both editors that I mentioned also have Auto-Save option similar to the Local History, but it is unrelated to decorators in them, i.e. you get decorators even when Auto-Save is switched off.

If you want to replay to me, please continue in #146626, to stop hijacking this thread further.

**Comment by mcanepa** [comment]
please allow an option to remove the stripes!!

I want a solid color just like before

**Comment by Anatoly-IVANOV** [comment]
Yes, please, allow us to override / customize the striped VS Code UI Git gutter indicators. Adding this comment for SEO (I've spent a while to track anything through Google after unsuccessfully trying to find the settings for this). 🙏🏻

A solid color was fine.

**Comment by misolori** [comment]
Just to provide an update here: @lszomoru and myself have been actively investigating at the various options to try and 1) make the vertical lines line up as much as possible and 2) allow users to enable/disable the pattern for either added/modified. Once we have an update we'll update this issue, so thanks for your patience.

> Adding this comment for SEO (I've spent a while to track anything through Google after unsuccessfully trying to find the settings for this)

This was in our [latest release from last week](https://code.visualstudio.com/updates/v1_66#_updated-source-control-decorators) so it might be a while before search bots pick it up

**Comment by pdrgnclvs** [comment]
Thanks for the heads-up @misolori 👍 

Just allowing us to enable/disable the pattern would be great for everyone: I prefer the solid style with no pattern at all since I'm used to it, but if anyone that needs or wants a pattern on the decorators they could simply toggle it 🤔

And as I said, if each decorator could have a different pattern that would allow for a little bit more of customization that would be awesome: that way, even I would change my mind and apply a different pattern to the added/modified lines 😁

Also, shouldn't the minimap and the scrollbar decorators for those lines follow the same styling? 🤔

But anyway, thanks for the heads-up and we'll be waiting for an update 😉

**Comment by lszomoru** [comment]
Today's Insiders release (2022-04-06) contains a new setting that allows users to toggle the diff decorator pattern for added/modified lines. As @misolori mentioned we are also still looking to address misaligned patterns for some combinations of user settings (gutter width, editor line height).

![image](https://user-images.githubusercontent.com/3372902/161953791-192fd167-a668-4700-a45c-bf58c36f7668.png)

**Comment by Z-E-D** [comment]
Is this new setting applied only with SCM? I am told that these decorators are visible with Timeline as well, if I understood it correctly.

By the way, you haven't replaced that "SCM" text with "Source Control" as it was suggested in #146723.

**Comment by gjsjohnmurray** [comment]
> By the way, you haven't replaced that "SCM" text with "Source Control" as it was suggested

@Z-E-D in this context the term "SCM" comes from the first part of the setting name. I think it would be unwise to rename all of the settings.

**Comment by anthroid** [comment]
> ![image](https://user-images.githubusercontent.com/3372902/161953791-192fd167-a668-4700-a45c-bf58c36f7668.png)

Might I suggest making this language more concise?
```diff
- Use pattern for the diff decorations in gutter for added lines. (added)
- Use pattern for the diff decorations in gutter for modified lines. (modified)
+ Use a pattern for diff decorations in the gutter (added lines)
+ Use a pattern for diff decorations in the gutter (modified lines)
```

In the future, if this becomes a non-Boolean setting, it could then read something like:
```diff
+ Pattern for diff decorations in the gutter: [solid|striped|dotted]
```

**Comment by gjsjohnmurray** [comment]
@anthroid the `(added)` and `(modified)` suffixes come from the Settings Editor UI (see #146902) so the contributor of the two settings won't be able to change them in the way you propose.

**Comment by lszomoru** [comment]
@Z-E-D, we certainly do not want to rename the settings. Having said that, as far as I can tell, the first segment of a setting (ex: `scm`) is only getting displayed when you search for settings and there are hits from multiple categories. 

Here is the setting when you click on "Features -> Source Control":

![image](https://user-images.githubusercontent.com/3372902/162134052-ea7357fe-5044-421e-91ba-0eaeb1646b2c.png)

And here is the setting when you search for "gutter pattern":

![image](https://user-images.githubusercontent.com/3372902/162134107-86d54c5d-53ac-4799-9b15-616272d65248.png)

**Comment by Z-E-D** [comment]
@[lszomoru](https://github.com/lszomoru) I don't care about that SCM thing since I am not using it. I just think that inconsistencies confuse people and I am sure there are many of them like me using VSCode who are unfamiliar with that SCM abbreviation.

Anyway, the main question remains unanswered. Why are you putting these settings in the "Features -> Source Control" if these decorators could be seen in other places of the program that are unrelated to the SCM? What if someone is not using SCM, but is using Local History? If that someone wants to change those settings, maybe he/she couldn't find it because not looking into that SCM part of Settings.

**Comment by lszomoru** [comment]
> Anyway, the main question remains unanswered. Why are you putting these settings in the "Features -> Source Control" if these decorators could be seen in other places of the program that are unrelated to the SCM? 

The new setting has been placed under "Features -> Source Control", because all other settings related to the diff decorations are there. There is absolutely no value of having diff decoration settings sprinkled across multiple features in the settings editor. 

> What if someone is not using SCM, but is using Local History? If that someone wants to change those settings, maybe he/she couldn't find it because not looking into that SCM part of Settings.

Local History is a brand new feature that has shipped in the most recent stable release. If you feel that *all* diff decoration settings should be moved out of the "Features -> Source Control" section because diff decorations are available when using location history, I would suggest that you file a separate issue as that should be tracked separately. Thanks!

**Comment by Ark-kun** [comment]
The decorator pattern looks corrupted: 

![image](https://user-images.githubusercontent.com/1829149/162543702-6d48ad25-1686-447b-a17c-a6d0685bde06.png)

**Comment by mitsukuri** [comment]
I think that instead of presuming that _all_ users need accessibility tweaks, a global setting should be introduced - something along the lines of `Enable accessibility-related UI tweaks globally` - which should always be consulted before enabling those by default without an option to revert.

**Comment by mitsukuri** [comment]
> I am confident that options to control this behaviour are coming. Check recent PRs if interested.

New features should not arrive _before_ the options that disable them.

**Comment by AndrianD** [comment]
I'm facing the same problem too under VSCode 1.66.1, striped vertical line

![striped-vertical-gutter](https://user-images.githubusercontent.com/6118385/162640983-d43f1874-bcbf-40c0-9781-9956205f75fc.jpg)

**Comment by lszomoru** [comment]
@Ark-kun, @AndrianD it is known that for combinations of the `scm.diffDecorationsGutterWidth` and `editor.lineHeight` settings, the pattern can appear misaligned. Could you please share the values of these settings that you are using? Thank you!

**Comment by lszomoru** [comment]
Verification steps:
- Launch VS Code and open a folder/workspace containing a git repository
- Open a file, and add new lines, edit existing lines so that both add/edit diff decorators appear in the editor gutter
- Open settings and change the `scm.diffDecorationsGutterPattern` setting and confirm that the changes are reflected in the editor

**Comment by mitsukuri** [comment]
Tranquility restored in 1.67.0, yay!
