### ISSUE TITLE
Can I restore to the previous SCM decorator style?

### ISSUE THREAD

**Issue by infinnie** [microsoft/vscode#146378]
I want a convenient way to change SCM decoration styles, for example restoring to the previous version, or changing its color and stripe pattern. Can that be done?

**Comment by lszomoru** [comment]
@infinnie, thank you very much for your feedback. The colours were slightly adjusted in order to meet the colour contrast accessibility requirements. We also have [an issue](https://github.com/microsoft/vscode/issues/146220) tracking disabling the pattern for the lines that have been modified. I will be closing this issue in favour of https://github.com/microsoft/vscode/issues/146220.
