### ISSUE TITLE
problem in html right to left around whitespace

### ISSUE THREAD

**Issue by hmbmirzaei** [microsoft/vscode#146354]
in version 1.65 every things is ok. but in version 1.66 codes has been messed up.

version 1.65: OK
![ok](https://user-images.githubusercontent.com/27133795/160919149-a4250034-b14c-406c-8720-da399b5d776e.png)

version 1.66: bad
![bad](https://user-images.githubusercontent.com/27133795/160919143-67d5b693-c397-4b97-b1ec-d263b427aa08.png)

**Comment by hmbmirzaei** [comment]
original text:


<b>
	9- هزینه کاهش ارزش دریافتنی‌ها
</b>
<p>
	در سال مورد گزارش مبلغ ................................. میلیون ریال از مطالبات در نتیجه ورشکستگی یکی از مشتریان عمده،
	مشکوک الوصول شده و کاهش ارزش برای آنها در نظر گرفته شده است.
</p>
-------------------
in version 1.65 displays correct:
![1_66](https://user-images.githubusercontent.com/27133795/161199020-3489334d-fb1c-4a1b-a836-0e79005992eb.png)

but in version 1.66:
![1_65](https://user-images.githubusercontent.com/27133795/161199065-2e6db2bb-6202-4f54-92c5-b19cca55257b.png)

**Comment by HirbodBehnam** [comment]
I'd also like to add two gifs related to this bug when selecting text. Here is vscode version 1.65.2:
![ok](https://user-images.githubusercontent.com/11520090/161215213-bc0c9405-84e2-4163-af2c-c02f30d1ff66.gif)
Now here is version 1.66.0:
![bad](https://user-images.githubusercontent.com/11520090/161215267-52418cfb-f783-4ce0-b160-0c9c932e619f.gif)

**Comment by AradAlvand** [comment]
Same here. Since the last update RTL texts are all screwed up! In the following screenshot, there's a tab before the "سلام", but it's all incorrectly aligned.

![image](https://user-images.githubusercontent.com/26527405/161387980-eef469ad-30e7-49d7-96d2-b19135bb6f25.png)

The old behavior was the right one. Please revert back this change.

**Comment by Aaron2321d** [comment]
Why did you guys mess this up?! RTL texsts aren't working properly.

This GIF illustrates the issue:
![Untitled Project](https://user-images.githubusercontent.com/96596709/161388263-9e56d243-403a-46d2-9446-10e3a4f81ee5.gif)

**Comment by aahmadi458** [comment]
@alexdima Can you please take a look at this again? I think the [needs more info](https://github.com/microsoft/vscode/labels/needs%20more%20info) label is no longer necessary.

**Comment by alexdima** [comment]
Thank you for the extra information. Let's track in https://github.com/microsoft/vscode/issues/99589 . This is a problem that is caused by the way whitespace is rendered (inline with the actual text) and is triggered when using `editor.renderWhitespace` : `all` or `selection`. The workaround is to configure `editor.renderWhitespace` : `boundary`, `trailing` or `none`.

**Comment by alexdima** [comment]
To verify, paste the following in a HTML file:
```html
<b>
	9- هزینه کاهش ارزش دریافتنی‌ها
</b>
```
It should be rendered with the leading whitespace before the text:

<img width="264" alt="image" src="https://user-images.githubusercontent.com/5047891/161772165-52d615c7-3da1-4c6c-b140-67bdf5f780f3.png">
