### ISSUE TITLE
save failure

### ISSUE THREAD

**Issue by ylqhust** [Microsoft/vscode#14635]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T15:27:10.246Z)
- OS Version: Darwin x64 16.0.0
- Extensions: donjayamanne.python-0.5.0, luniclynx.lex-0.1.0, ms-vscode.cpptools-0.9.2, se2dev.vscode-yacc-1.0.1, slevesque.shader-0.2.2, tht13.python-0.2.3, tushortz.python-extended-snippets-0.0.1, vscodevim.vim-0.4.0

Steps to Reproduce:
编辑一个文件并且保存后，然后去编辑别的文件，过了一会在回来看，原来的文件保存失效，文件内容是上一次的内容，这个bug很严重啊，我的电脑上已经发生了好几次了，这个不解决只能投入atom的怀抱了

**Comment by bpasero** [comment]
@ylqhust can you try to provide the issue description in english?

**Comment by ylqhust** [comment]
I edit a file and save edit then I to edit another file . after sometimes ,I come back to see the first file .I find the first file's content is not I saved. this problem have happend many times

**Comment by bpasero** [comment]
@ylqhust 
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by jrieken** [comment]
Taking this back. @ylqhust As mentioned earlier, please try without extension. 

I have added telemetry about saving participant times, most interesting is how long format on save takes (upper bound 750ms) and how long the on-will-save-event takes (upper bound 1500ms). Turns that the are extensions host that are more or less dead. Looking at the data for 'format on save' is happy (since we enforce the timeout in the main process). However, the 'will save event' is dispatched and monitored on the extension host, meaning a dead/heavy loaded extension host might run its event listeners timely but it takes a long before that happens. During the last days in more than 10000 saves we have participated and some (~450) it took longer that 1500ms.

**Comment by jrieken** [comment]
I will put another defence mechanism in place that recovers from a dead extension host

**Comment by bpasero** [comment]
Verified that if I make the extension host not reply in 1750ms the save proceeds after at least 1750ms.

The save participant on the extension is not canceled so there is still a chance that it eventually triggers (not sure if this is a problem @jrieken).

**Comment by jrieken** [comment]
Shouldn't be a problem because the extension host cancels itself after 1500ms - the additional check is there to protect from a dead/unresponsive extension host. Even when the operation gets through in time at worst it will trigger another dirty/save cycle

**Comment by alecmce** [comment]
I have started to have this problem yesterday. I reinstalled Version 1.12.1 (1.12.1) and can reproduce. I open a file and edit it, but VS Code does not recognize it as edited. When I save nothing happens. VSCode remembers my edits but if I view the file from another editor, the edits have not been saved.

**Comment by bpasero** [comment]
@alecmce I suggest to open a new issue on it.
