### ISSUE TITLE
Double click a word and move with one finger will select other words and lines.

### ISSUE THREAD

**Issue by zealoussnow** [microsoft/vscode#146486]
Does this issue occur when all extensions are disabled?: No

- VS Code Version:   1.66.0 (e18005f0f1b33c29e81d732535d8c0e47cafb0b5)
- OS Version: macOS 12.1 (21C52)

Steps to Reproduce:

1. Double Click with one finger, select a word
2. Move the cursor with one finger, will select other words and lines (Similar to three-finger dragging)

![vscode](https://user-images.githubusercontent.com/2801287/161180809-a037a8b8-a384-4f0d-b12a-4e23416a5e94.gif)

**Comment by linct96** [comment]
it trouble me too

**Comment by jsupa** [comment]
same problem

**Comment by greeze** [comment]
Same issue here. It only happens with tap-to-click, not with a true "click". Also happens when selecting a line of text in the gutter. Text selection will remain "locked" as though the mouse button is pressed. Clicking again or using the keyboard will unlock the selection.

Disabling all extensions does not help. Only rolling back to the previous release fixes the issue.

![locked_text_selection](https://user-images.githubusercontent.com/285741/161390952-a1d2f111-01e5-4204-9bed-38498bd961fe.gif)

> Version: 1.66.0 (Universal)
Commit: e18005f0f1b33c29e81d732535d8c0e47cafb0b5
Date: 2022-03-30T05:50:04.419Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Darwin arm64 21.4.0

**Comment by alexdima** [comment]
I can reproduce after configuring "Tap to click" in the Trackpad settings.

**Comment by omBratteng** [comment]
Oh god, I thought I was going crazy, thinking my shift key or something was getting stuck.
Downgrading to 1.65.2 fixed it, so I'll stick to it in the meanwhile.

**Comment by zealoussnow** [comment]
> Downgrading to 1.65.2 fixed it

Yes, It's really a big problem for me when I upgrade to 1.66.0. When I downgrading to 1.65.2, everything is well.

**Comment by greeze** [comment]
Thank you for fixing this! Is there any way to get a prerelease with this fix in it, or do we need to wait for next month's release?

**Comment by alexdima** [comment]
@greeze The fix is available in [VS Code Insiders](https://code.visualstudio.com/insiders/) and we expect to roll this out with our recovery build 1.66.1, expected to be released today.
