### ISSUE TITLE
Powerline symbols in the terminal get wrong colors

### ISSUE THREAD

**Issue by oleq** [microsoft/vscode#146406]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.66.0
- OS Version: macOS Monterey 12.3 (21E230)

Steps to Reproduce:

1. Use a [powerline-friendly prompt](https://www.google.com/search?q=powerline+prompt) with fancy triangles (`\ue0b0`) in the terminal.
2. Open the terminal.

## Expected

How this should look (before 1.66.0)

<img width="412" alt="image" src="https://user-images.githubusercontent.com/1099479/161019524-d5015775-d801-44ab-8156-8e1081dc95db.png">

## Actual

<img width="378" alt="image" src="https://user-images.githubusercontent.com/1099479/161019577-d3eff382-fcd9-46fb-82d6-6a243d9195a1.png">

The triangles got some mixed colors.

## Info

* The prompt works correctly in iTerm, Terminal, etc. (so this is VSCode),
* This fails in all shells in VSCode: bash, zsh, or fish.
* This fails with or without customizations to `workbench.colorCustomizations` like `terminal.ansi*`.

**Comment by yume-chan** [comment]
`"terminal.integrated.minimumContrastRatio": 1`

**Comment by oleq** [comment]
> `"terminal.integrated.minimumContrastRatio": 1`

Works like a charm, thanks. This could be mentioned in [https://code.visualstudio.com/api/references/theme-color,](https://code.visualstudio.com/api/references/theme-color,) though.

**Comment by rewrking** [comment]
> `"terminal.integrated.minimumContrastRatio": 1`

Thanks. Would love to know why this isn't the default.

**Comment by oleq** [comment]
> > `"terminal.integrated.minimumContrastRatio": 1`
> 
> Thanks. Would love to know why this isn't the default.

WCAG accessibility guidelines. To make colorful terminal applications look at least okayish no matter the user theme. Makes sense. Mentioned in https://code.visualstudio.com/updates/v1_41#_minimum-contrast-ratio.

I wonder why this affected my setup now since this has been implemented since 1.41 in 2019? What changed in the recent 1.66 update? 🤔

**Comment by rewrking** [comment]
> WCAG accessibility guidelines. To make colorful terminal applications look at least okayish no matter the user theme. Makes sense. Mentioned in https://code.visualstudio.com/updates/v1_41#_minimum-contrast-ratio.

Yeah, but IMO 4.5 shouldn't be the default because suddenly the ansi terminal colors requested aren't the ones requested. It's another layer of confusion on top of something already confusing. This change isn't really a net benefit.

**Comment by levrik** [comment]
I'm also confused why it changes the color of the powerline rectangles? This doesn't seem to be correct or am I missing something here?

**Comment by jaminthorns** [comment]
My prompt uses Powerline symbols, so I had this issue after upgrading to 1.66 as well. I think making the terminal accessible by default is a good call, but it also presents a problem for prompts that switch between using the same color for background and foreground to create the illusion of shaped blocks (like Powerline). I'm sure this affects heavily-customized vim and Emacs setups that do similar things, too.

If a user still wanted to have the contrast ratio functionality, it might be nice to have a setting like `terminal.integrated.excludeContrastRatioAdjustment` that would be a string of characters to exclude from contrast ratio adjustment.

**Comment by Tyriar** [comment]
This feature has been around for a long time but we changed the default in 1.66 as we're trying to make VS Code the most accessible code editor out there. You can see some of the background on the change here: https://github.com/microsoft/vscode/issues/144411, I know this might cause an inconvenience but the net benefit is quite large:

- Themes/shells with incompatible colors (#144411) will no longer be invisible or super low contrast
- The terminal should be accessible regardless of your shell and operating system - accessibility is very important to our team
- It's trivial to disable by setting `"terminal.integrated.minimumContrastRatio": 1`, you could argue that it's hard to discover this but it's equally hard for users where this makes the terminal unusable to discover it for the inverse problem.

FYI @isidorn about feedback

> Works like a charm, thanks. This could be mentioned in https://code.visualstudio.com/api/references/theme-color, though.

@oleq good idea!

> I'm also confused why it changes the color of the powerline rectangles? This doesn't seem to be correct or am I missing something here?

@levrik yes it's because how powerlines works is a bit of a hack; for the triangle character, it inverts the background/foreground color so the shape on the left is the foreground and the negative space on the right is the background.

> If a user still wanted to have the contrast ratio functionality, it might be nice to have a setting like terminal.integrated.excludeContrastRatioAdjustment that would be a string of characters to exclude from contrast ratio adjustment.

@jaminthorns I like the idea of excluding at the least the triangle powerline char from minimum contrast ratio :+1:, this character will almost always be used to simulate the background color so it's a nice compromise. This also comes with the nice benefit of still retaining min contrast ratio in the prompt when a powerline is used.

**Comment by chtenb** [comment]
> This feature has been around for a long time but we changed the default in 1.66 

Why was this not mentioned in the release notes? Control-F on "contrast" or "terminal" don't find this change.

**Comment by Tyriar** [comment]
@chtenb I stand corrected, it wasn't mentioned in the release notes. No reason other than we just missed including it. Added it in https://github.com/microsoft/vscode-docs/commit/c4320f6377dcda99fbe72e99f39378114ed5074a, it will be updated when we next publish the website.

**Comment by fisheva** [comment]
Hi, @Tyriar, I'm a theme maker. I have customized various terminal colors in my theme. This feature makes these colors not match my theme anymore...
![20220403-173137@2x](https://user-images.githubusercontent.com/17448419/161421345-224e124d-37f7-4bd4-acb2-dcebc1c8d8e9.png)

How do I set up in my theme file to make `"terminal.integrated.minimumContrastRatio": 1` as the default setting for my theme? Then my theme users don't have to set it up themselves. I tried to write it in my theme's JSON file or Package.json, but it doesn't work. 
![20220403-171035@2x (1)](https://user-images.githubusercontent.com/17448419/161421510-1d6d3d5b-e677-4bfc-82af-4385f71b0618.png)

I am looking forward to your solution. Very Thanks!

**Comment by rmarinbe** [comment]
I have the same issue as @fisheva, I am using also zsh:
I tried to change it in the settings.json:

"workbench.colorCustomizations": {
    "terminal.integrated.minimumContrastRatio": 1,
    "terminal.foreground":"#bbbbbb",
    "terminal.ansiBrightBlue":"#56B6C2",
....

but the minimunContrastRatio is not fixing anything with the terminal colors, seems that the gamut of available colors has been drastically reduced, for example, some dark colors like #303030 now look like bright gray in the console.

**Comment by rmarinbe** [comment]
> Hi, @Tyriar, I'm a theme maker. I have customized various terminal colors in my theme. This feature makes these colors not match my theme anymore... ![20220403-173137@2x](https://user-images.githubusercontent.com/17448419/161421345-224e124d-37f7-4bd4-acb2-dcebc1c8d8e9.png)
> 
> How do I set up in my theme file to make `"terminal.integrated.minimumContrastRatio": 1` as the default setting for my theme? Then my theme users don't have to set it up themselves. I tried to write it in my theme's JSON file or Package.json, but it doesn't work. ![20220403-171035@2x (1)](https://user-images.githubusercontent.com/17448419/161421510-1d6d3d5b-e677-4bfc-82af-4385f71b0618.png)
> 
> I am looking forward to your solution. Very Thanks!

![image](https://user-images.githubusercontent.com/50396949/161605483-ddd5ad0e-a7d7-4bbe-8a6d-3e990c001ab2.png)

**Comment by rmarinbe** [comment]
@fisheva, I guess you can set it here:
![image](https://user-images.githubusercontent.com/50396949/161605695-8afa34aa-7318-4824-b8e4-68496554d065.png)

**Comment by fisheva** [comment]
@rmarinbe Sorry, that's not the point. I know how to set it on my own VSCode. I want to know how to set it for all my theme users.

**Comment by rmarinbe** [comment]
> @rmarinbe emmm, I know how to set it on my own VSCode. I want to know how to set it for all my theme users.

ok got it, sorry for the confusion, I also tried from the JSON but it is not working for me.

**Comment by JanDeDobbeleer** [comment]
The amount of additional work (issues, Twitter replies) this change has brought to maintainers across the globe is not sustainable. I understand the need for accessibility, yet this introduces unwanted side effects for a majority of people. Can we think about how to solve this challenge differently?

**Comment by SiJiL82** [comment]
I agree - IMO if you're changing something for any reason so it doesn't display how settings say it should (in this instance, changing the colours of things from what the colour is set to), that should be an option that a user enables by choice if they require it.
So default it back to 1 in the settings, then do a proper release annoucement about it, so if people who want/need it on know about it and can choose to enable the compliance settings.

**Comment by meganrogge** [comment]
Right now it's only fixed for `terminal.integrated.gpuAcceleration: canvas`

**Comment by meganrogge** [comment]
to verify:

- install a powerline font 
- verify that changing the `terminal.integrated.minimumContrastRatio` does not alter the color of the powerline glyphs for all values of the `terminal.integrated.gpuAcceleration` setting

**Comment by JanDeDobbeleer** [comment]
@meganrogge awesome work! I'll validate it in the morning (evening here).

**Comment by Tyriar** [comment]
@jstm88 we obviously value accessibility more that you 🤷

This issue is closed with a fix that should work for everyone. If the extra contrast still bothers you you can switch it off by tweaking `terminal.integrated.minimumContrastRatio`, I trust that you can set up your computer the way you want 😉

**Comment by jstm88** [comment]
> @jstm88 we obviously value accessibility more that you 🤷
> 
> This issue is closed with a fix that should work for everyone. If the extra contrast still bothers you you can switch it off by tweaking `terminal.integrated.minimumContrastRatio`, I trust that you can set up your computer the way you want 😉

There are two basic types of accessibility that are relevant here:

1. Designing the parts of the application you control to have good accessibility properties
2. Options that *modify* expected behavior

1 is obviously good, but 2 is a problem if enabled by default. We don't ship computers with high-contrast mode, large type, and text-to-speech enabled by default, do we? It would be silly.

The way I understand the fix that's been proposed is that it will make an exception for specific fonts, but it will still modify the colors displayed. This is still bad - you're making edge cases that have to be maintained, and you're opening the door for *more* of those edge cases as people inevitably discover all of the additional places where it breaks.

I'll further propose that, perhaps, this setting doesn't really make a lot of sense in the context of a terminal. There's a very simple solution that *doesn't* require these modifications - just add additional themes for the Terminal with an accessible color palette. Simple and it doesn't introduce edge cases.

I'm glad this is being thought of, but I just think this implementation (specifically making it the default) was ill-advised.

**Comment by Tyriar** [comment]
> 1 is obviously good, but 2 is a problem if enabled by default. We don't ship computers with high-contrast mode, large type, and text-to-speech enabled by default, do we? It would be silly.

@jstm88 Yes it would be silly, but this is a special case where we cannot guarantee contrast between the theme and the application/shell running in the terminal and many users would run into contrast issues because of this where characters were invisible. Plus the default isn't "high contrast", it's to shift the colors towards the minimum recommended contrast as recommended by WCAG AA (4.5) which is not particularly high.

Bottom line is we have requirements we need to meet around accessibility and this is one of those. You could argue this goes above and beyond what is required, but the tradeoff here after the fix is a good and worth it as contrast will be guaranteed regardless of theme, it only modifies the foreground color so shouldn't be particularly noticeable to most users and it can be easily disabled if it's bothersome.

> I'll further propose that, perhaps, this setting doesn't really make a lot of sense in the context of a terminal.

The feature was inspired [by iTerm2](https://iterm2.com/documentation-preferences-profiles-colors.html), so we're not the only ones that think it's a good idea. The "just change your theme" approach doesn't work for all background/foreground combinations as that's impossible and we also don't have distinct editor/terminal themes (like Atom), so you'd be forcing those users who want _reasonable_ contrast to use the few (and ugly) _high_ contrast themes.

**Comment by jstm88** [comment]
@Tyriar Those are some good points, and I do see where the setting could still make sense even if there was theme support.

Still, though, if the option is going to be enabled by default, there absolutely needs to be a notification. There's an established UI paradigm for exactly this case - a panel in the corner, informing the user that the option was automatically changed, with a choice to disable it or accept the change. The notification could appear the first time the Terminal feature is used.

**Comment by Tyriar** [comment]
@jstm88 we've been fighting "notification fatigue" for a long time, adding a notification for such a minor thing would annoy people. Adding notifications to VS Code core are all heavy scrutinized to protect the user experience and keep VS Code feeling "lightweight".
