### ISSUE TITLE
Bug on Gpu rendering on Ubuntu 21

### ISSUE THREAD

**Issue by goashir** [microsoft/vscode#146445]
For over three months my first choice has been vscode
 and I always run it through `sudo code --user-data-dir="~/.vscode-root" `
but from today, I had a problem that after running the program, the gray screen appears ,It does not seem to be rendered 
![Screenshot from 2022-03-31 20-17-23](https://user-images.githubusercontent.com/18716709/161096509-51b7f4d3-b3cc-43b4-b36a-28803af1ee1e.png)

project name even appears and even can be changed curser mouse by moving mouse(hand or select text) and the text can be copied!

this is my log folder from `/home/mahdi/~/.vscode-root` :
[logs.zip](https://github.com/microsoft/vscode/files/8391130/logs.zip)

**Comment by deepak1556** [comment]
Why is the application run as sudo ? Can you provide the output of `code --verbose`

**Comment by goashir** [comment]
yes command `code --verbose` or 'code' and vscode on ui runs beautifully.
![Screenshot from 2022-03-31 22-20-33](https://user-images.githubusercontent.com/18716709/161118794-ca7b6e22-09fa-4c45-abd2-c5504ebe27dd.png)

**Comment by goashir** [comment]
I even deleted all `/home/mahdi/~/.vscode-root` and I see this picture in disbelief (get Started page and file menu!)

![Uploading Screenshot from 2022-03-31 22-41-49.png…]()

**Comment by deepak1556** [comment]
> Is there a way to restore the sudo environment to default?

why do you need to run the application in sudo ? VSCode does not support it.

**Comment by goashir** [comment]
> VSCode does not support it

Aha! but I used `sudo mode` for html & css coding and in `vscode normal mode` I was writing to php and used a lot of packages that are not necessary in html & css environment

**Comment by deepak1556** [comment]
I am not sure I completely understand your use case, but it looks are you are trying to force two different user data dirs for these projects. But it feels you can use workspaces https://code.visualstudio.com/docs/editor/workspaces instead.

As for the root issue, VSCode cannot support sudo mode due to the sandbox nature of the runtime, so closing as won't fix.

**Comment by josehcif** [comment]
I already worked around the problem by modifying permissions. But for reference, the use case was opening the VSCode workspace over the currently running filesystem for an Apache server running a PHP website in a VM. The filesystem was owned by user www-data and my logged in user account had no write permissions to it. As this filesystem was for development purposes only, I was not concerned with proper practices and went the simpler way of just running VSCode under sudo.

**Comment by aleks-f** [comment]
@deepak1556 I agree with @josehcif - this is very annoying. Here's my use case - I am developing for two versions of a library. I have one version in a container, the other on the host machine, and my sources in a directory shared between host and container; the simplest way to deal with it is to edit and build as root and I do not care for sandboxing and security because this is a local machine, not visible from anywhere. 

Yes, vscode will ask for credentials on file save and build, but having to type the password (there's no "remember" check box, either) for every edit is not what I would call a productive working mode.  Can we please get the capability to run as root back?
