### ISSUE TITLE
Github Login Failure, a new instance is opened

### ISSUE THREAD

**Issue by guilherme-sr** [microsoft/vscode#146408]
Issue Type: <b>Bug</b>

When I try to login to Github, I am sent to the website to authorize and a box appears to select the Vscode URL handler, but instead of simply going back to the vscode that was already open, a new instance of vscode starts and the login doesn't happen.

VS Code version: Code 1.66.0 (e18005f0f1b33c29e81d732535d8c0e47cafb0b5, 2022-03-30T05:50:41.156Z)
OS version: Linux x64 5.17.0-1-MANJARO
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4170 CPU @ 3.70GHz (4 x 3698)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|7.70GB (0.40GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id b55b4971-776c-4e47-b1dd-67e8c7289a58|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
turbo-console-log|Cha|2.1.7
prettier-vscode|esb|9.5.0
auto-close-tag|for|0.5.14
code-runner|for|0.11.7
copilot|Git|1.10.5413
vscode-jumpy-plus|joh|0.3.1
vscode-language-pack-pt-BR|MS-|1.66.1
material-icon-theme|PKi|4.15.0
vscode-apielements|vnc|0.6.7

(2 theme extensions excluded)

</details>

**Comment by tusharsadhwani** [comment]
I'm facing the same issue.

For me, originally just nothing would open (the browser thinks that `vscode.dev` is the correct application to open). I tried adding a mimetype of `x-scheme-handler/vscode`, and that caused this behaviour to occur.

**Comment by TylerLeonhardt** [comment]
How are you all installing VS Code?

**Comment by tusharsadhwani** [comment]
I have a script that downloads the latest version and copies the binary to the right place. Is that an issue?

**Comment by TylerLeonhardt** [comment]
Where do you download it from?

cc @deepak1556 in case you have thoughts on why the `UriHandler` isn't firing correctly.

**Comment by tusharsadhwani** [comment]
@TylerLeonhardt direct download from https://code.visualstudio.com/updates

**Comment by TylerLeonhardt** [comment]
@tusharsadhwani what OS are you on?

**Comment by tusharsadhwani** [comment]
@TylerLeonhardt Linux, pop os 21.10

**Comment by TylerLeonhardt** [comment]
@tusharsadhwani have you tried installing the DEB or SNAP of VS Code? I just wanna rule out your installation method.

**Comment by deepak1556** [comment]
Do you have `code-url-handler.desktop` installed ?

Tl:dr; the runtime sets up url handler via `xdg-settings set default-url-scheme-handler <protocol> <desktop-file>` and vscode provides https://github.com/microsoft/vscode/blob/main/resources/linux/code-url-handler.desktop as the target which has the right set of arguments to make the newly launched instance from the OS to reuse the existing vscode window.

**Comment by anddam** [comment]
> Do you have `code-url-handler.desktop` installed ?
> 
> Tl:dr; the runtime sets up url handler via `xdg-settings set default-url-scheme-handler <protocol> <desktop-file>` and vscode provides https://github.com/microsoft/vscode/blob/main/resources/linux/code-url-handler.desktop as the target which has the right set of [arguments](https://github.com/microsoft/vscode/blob/main/resources/linux/code-url-handler.desktop#L5) to make the newly launched instance from the OS to reuse the existing vscode window.

This issue has been bot-closed without a solution, but following this advice I (opener of #147915) was able to to correctly sign-in via Github on my non-systemd Void Linux setup: 
1. adding `code-url-handler.desktop` to `$XDG_DATA_HOME/.applications`
2. edit the file adjusting the Exec and Icon placeholders (resp. `$HOME/Applications/VSCode-linux-x64/bin/code` and `code-oss` since I haven't figured yet how icon works, probably full path to ~/Applications one would work as well)
3. run `xdg-settings set default-url-scheme-handler vscode code-url-handler.desktop`
4. watch amused at the xdg-mime error that popped
5. source xdg-settings to track the failing xdg-mime invocation
6. run `xdg-mime default code-url-handler.desktop x-scheme-handler/vscode` to complete the steps (I cannot even be bothered to track what's wrong at this point)
7. open VSCode (MS build)
8. turn on Settings Sync
9. select "github" as method
10. Chrome displays the usual xdg-open alert dialog **but**
11. letting xdg-open run this time makes Chrome display the .desktop entry we just downloaded
12. VSCode asks for permissions to open the URL
13. voilà settings sync is working

🎉🎊

Thx @deepak1556
