### ISSUE TITLE
RTL text is reversed when selected

### ISSUE THREAD

**Issue by AhmedElTabarani** [microsoft/vscode#146537]
- VS Code Version: 1.66.0 & 167.0-insider 
- OS Version: Windows_NT x64 10.0.17763

Since the VS Code not good with RTL text, although it's hard, I was used to it
But in this current update, the things getting worse when selecting the text

The text like: `مرحبًا بكم جميعًا` it becomes `جميعًا بكم مرحبًا` when selected **(the text is reversed)**

it likes that: `Hello to everyone`  it becomes `everyone to Hello` when selected 

Steps to Reproduce:
This video from 167.0-insider without any extension
https://www.awesomescreenshot.com/video/8185117?key=18ef594285daa2d7de3c488a34799011

**Comment by alexdima** [comment]
Let's track in https://github.com/microsoft/vscode/issues/99589 . This is a problem that is caused by the way whitespace is rendered (inline with the actual text) and is triggered when using `editor.renderWhitespace` : `all` or `selection`. The workaround is to configure `editor.renderWhitespace` : `boundary`, `trailing` or `none`.
