### ISSUE TITLE
Inline suggestion disappears when typing it

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#146523]
```
Version: 1.67.0-insider
Commit: 909602cf04e0fa42528d692676d0d4e15e67bba2
```

I'm looking for `createModelServices`, which shows up as soon as I type `c`, which is great! But when I type `create` it disappears and then it comes back when I type `createM`:

> Note: This also happens with `DisposableStore` and `Disposable`.

https://user-images.githubusercontent.com/5047891/161236766-344e54b7-a946-4d3e-8344-fbbe43f57ac9.mp4

**Comment by jrieken** [comment]
Didn't debug but it's very likely because completions reward full matches, e.g there is `create` and `createModelServices` as well as `Disposable` and `DisposableStore`. When typing `creat` both match equally well and the provider order is used. However, as soon as the full word is typed, `create` wins over `createModelServices`. This logic is geared towards the suggest list and I can see if/how this can be tweak for inline completions
