### ISSUE TITLE
Code Runner does not work

### ISSUE THREAD

**Issue by gerardofisch** [microsoft/vscode#146555]
When I click Ctrl+alt+N the integrated terminal does not open, neither the code runs
I was programing on python

**Comment by Lemmingh** [comment]
Are you talking about "Code Runner" (`formulahendry.code-runner`)?

Please troubleshoot first to see whether the problem is related to VS Code or is caused by the extension itself.

* Check key bindings: <https://code.visualstudio.com/docs/getstarted/keybindings#_detecting-keybinding-conflicts>

* Check Runtime Status : <https://code.visualstudio.com/updates/v1_59#_extensions>
