### ISSUE TITLE
Custom keybinding for `workbench.action.quickOpenRecent` command also closes current workspace and reopens previous workspace

### ISSUE THREAD

**Issue by chaoz-dev** [microsoft/vscode#146661]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:
```
Version: 1.66.0
Commit: e18005f0f1b33c29e81d732535d8c0e47cafb0b5
Date: 2022-03-30T05:50:41.156Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Linux x64 5.13.0-37-generic
```
- OS Version: Ubuntu 21.10

Steps to Reproduce:

1. Add following keybinding to `keybindings.json`:
```
+     {    
+         "key": "ctrl+m",    
+         "command": "workbench.action.quickOpenRecent"    
+     },    
```
2. Use keybinding in VSCode
3. VSCode will try to quick open recent files, then will try to close current workspace and open previously opened workspace.

Attempted to repro the issue with a different command (ie. changed command to `"command": "workbench.action.quickOpen"`); the issue does not repro in this situation and I can use the keybinding as intended to quick open. 

Also note that in checking the keybindings page, I do not currently have any other (custom) keybindings bound to `ctrl+m`, besides what's given by VSCode by default.

**Comment by TylerLeonhardt** [comment]
This is because the behavior of `workbench.action.quickOpenRecent` is similar to that of `workbench.action.quickOpenPreviousRecentlyUsedEditorInGroup` (aka ctrl + tab) in that once you lift up holding down TAB, you will be taken to that window.

@bpasero was this always the intended behavior of `workbench.action.quickOpenRecent`?

If not, then I can look into getting the behavior back to what it was intended to be.
If so, it's odd to me that that quick pick has a an input box.

**Comment by TylerLeonhardt** [comment]
Ah... @chaoz-dev use `workbench.action.openRecent`. That's the one you want. `workbench.action.quickOpenRecent` is behaving as expected (although it's odd there's an input box)

**Comment by bpasero** [comment]
@TylerLeonhardt good catch, opened https://github.com/microsoft/vscode/pull/147493

**Comment by chaoz-dev** [comment]
Ah gotcha gotcha. Thanks for looking into this!
