### ISSUE TITLE
having problem with persian words ( farsi )

### ISSUE THREAD

**Issue by AlirezaGhadyani** [microsoft/vscode#146698]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.66.0
- OS Version: Ubuntu 20.04.4 LTS

Steps to Reproduce:

1. All Persian words are stuck to the left of the editor and there is no empty space
2. When Persian words are selected, all words are reverted

![Screenshot from 2022-04-04 10-46-47](https://user-images.githubusercontent.com/81858771/161484474-659a1d69-7bc7-411b-9475-572a5929776f.png)

**Comment by AlirezaGhadyani** [comment]
> Does this issue occur when all extensions are disabled?: Yes
> 
> * VS Code Version: 1.66.0
> * OS Version: Ubuntu 20.04.4 LTS
> 
> Steps to Reproduce:
> 
> 1. All Persian words are stuck to the left of the editor and there is no empty space
> 2. When Persian words are selected, all words are reverted
> 
> ![Screenshot from 2022-04-04 10-46-47](https://user-images.githubusercontent.com/81858771/161484474-659a1d69-7bc7-411b-9475-572a5929776f.png)

### **in last version there was no problem with farsi words.**

**Comment by alexdima** [comment]
Let's track in https://github.com/microsoft/vscode/issues/99589 . This is a problem that is caused by the way whitespace is rendered (inline with the actual text) and is triggered when using `editor.renderWhitespace` : `all` or `selection`. The workaround is to configure `editor.renderWhitespace` : `boundary`, `trailing` or `none`.
