### ISSUE TITLE
Better validation warnings for notebook document URIs in extension API

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#146690]
See https://github.com/microsoft/vscode/issues/146353 3rd point

**Comment by jrieken** [comment]
Re-opening due to https://github.com/microsoft/vscode/pull/169481/files#r1051895656

**Comment by jrieken** [comment]
>  but I don't really understand why that's better

Mostly because it doesn't break existing extensions (breaking in the sense of now throwing errors) but also to be aligned with other checks and the current behaviour (returning `false` and logging messages). 

Also, for this specific case we could just be graceful and infer the notebook uri from the cell uri
