### ISSUE TITLE
Running notebook cells uses all available memory

### ISSUE THREAD

**Issue by jjnurminen** [microsoft/vscode#146768]
Hi,

since about 1-2 months ago, I cannot run many of my notebooks inside VS Code any more. When running certain cells, memory usage increases massively, eventually causing Windows to hang or terminate VS Code when all available RAM is taken.

Unfortunately I cannot share code due to IP issues and haven't yet came up with a minimal reproducible example. However, the issue seems to be quite often triggered by code that generates a bunch of matplotlib or plotly plots. I've seen it happen with other kinds of code too.

The issue occurs in both Insiders and regular VS Code. From Jupyter Lab the same code runs fine, no memory issues.

Running Windows 10 and latest VS Code releases.

**Comment by roblourens** [comment]
This is the classic issue of the jupyter extension concatenating all streaming output and calling `replaceOutputItems` with the result, which gets larger and larger. The EH messages get way ahead of the renderer process.

And we can't use 'append' just because the jupyter extension has to process possible terminal ansi codes, is that right? https://github.com/microsoft/vscode-jupyter/blob/d4aa4ea7855a8c148e91f10805da2a8402466694/src/kernels/execution/cellExecutionMessageHandler.ts#L849

There has to be a better way to do this

**Comment by DonJayamanne** [comment]
`ut and calling replaceOutputItems with`

@roblourens can you let me know what's the perf impact of calling this too many times. I.e. what's the underlying issue that blows up the memory usage.

**Comment by roblourens** [comment]
That method is called 10000 times with a payload that gets very large. vscode has to do a bunch of work to render an output from scratch on each iteration. It can't keep up and messages are written much faster than they are read by the renderer process. I was thinking this is basically the use-case that appendOutputItems was invented for.

**Comment by DonJayamanne** [comment]
> was thinking this is basically the use-case that appendOutputItems was invented for.

let's sync up tomorrow or debt week.
part time we worked on this together, i didn't use the weekends items, as we need to process the data, and need to delete lines from a previous output.

i guess we can use a mix of both to optimize this scenario.
also, silly question, what about throttling the update.

let's sync during debt week

**Comment by DonJayamanne** [comment]
Should be fixed with https://github.com/microsoft/vscode/issues/161023

**Comment by DonJayamanne** [comment]
Steps to validate
* Run the following python code
```python

# %% let's crash
import logging

for k in range(10_000):
    logging.warning(k)
```

https://github.com/microsoft/vscode/issues/146768#issuecomment-1087989764

**Comment by AndrewRocky** [comment]
Was this fixed?
On my machine https://github.com/microsoft/vscode/issues/146768#issuecomment-1087989764 still causes VSCode to go unresponsive and eventually almost freezes the whole machine (by consuming all RAM and loading system SSD on 100% (because it's a swap disk)).

Windows 10 21H2
VSCode 1.73.1

**Comment by DonJayamanne** [comment]
the fix will be in there next release, some time this week
