### ISSUE TITLE
No discoverable way to turn off a task in vscode once its started

### ISSUE THREAD

**Issue by nojvek** [Microsoft/vscode#14677]
Version 1.6.1
Commit 9e4e44c19e393803e2b05fe2323cf4ed7e36880e
Date 2016-10-13T16:21:53.542Z
Shell 1.3.7
Renderer 52.0.2743.82
Node 6.5.0

Steps to Reproduce:
1. Start task with Ctrl+Shift+B
2. How to turn it off. After an hour of searching. Kill VSCode, Restart it. 

This is a terrible user experience. Ctrl+Shift+B that turned off the task before worked totally fine.

There should be a big fat button in tasks window to kill the current task and restart it. Tooltips should show appropriate keyboard shortcut.

Also the info message shown when an already running task is run is not very useful. It should contain actions for remedies.

![image](https://cloud.githubusercontent.com/assets/1018196/19822633/549303c6-9d19-11e6-8096-a182f1254815.png)

**Comment by dbaeumer** [comment]
F1 > Terminate Task. Adding a message to let the user know how to terminate it makes sense. At the end this can only be made user configurable since I had lots of people complaining about the old behavior since they had to dismiss the message box when they pressed Ctrl+Shift+B by accident.

I do have an item to make the behavior of pressing Ctrl+Shift+B for this case configurable.

**Comment by use-strict** [comment]
@dbaeumer , I may be missing the point, but how is the current behavior any different? From what I can see, there is still a message box that has to be dismissed, the only difference being that it no longer has a terminate button. The solution feels like a workaround and, to be honest, is a real pain. F1 -> Terminate is way to slow for a very common task. Ideally, there should be a keyboard shortcut that runs a fresh build, terminating the old task automatically, or at least a fast keyboard confirmation like ctrl+shift+b, enter. Someone also made a plugin that adds a terminate button in the status bar, but it doesn't know if there is actually something running or not and you get no feedback when pressing it. But it's still faster IMHO than typing "f1 -> terminate -> enter".

**Comment by dbaeumer** [comment]
@use-strict the difference is that the message dialog now auto closes after a period of time since it has no other actions.

As said I have a feature request to make it user configurable what should happen if the user presses Ctrl+Shift+B and a task is already running. Thinks to keep in mind here are:

- watch tasks are very likely not to be restarted (it this the main purpose of a watch task to react correct on file changes). This was one argument why we made the change since most of the people pressed Ctrl+Shift+B with a watch task already running and terminating that task is mostly not what they want.
- non watch tasks are likely to be restarted if the same task is requested. If a different task is requested it is unclear what the best strategy is.

**Comment by use-strict** [comment]
>  message dialog now auto closes after a period of time 
I see. I never had the patience to actually wait and see if it closes. I always clicked close myself immediately.

> watch tasks are very likely not to be restarted
You have a good point. I guess the problem is with the actual task that I'm using (webpack) which doesn't react well on switching branches (changing many files at once). It shouldn't be generalized. In the end I wouldn't want to terminate the task by accident either.
