### ISSUE TITLE
Polish: uneven lines in high contrast theme

### ISSUE THREAD

**Issue by sana-ajani** [microsoft/vscode#146856]
Version: 1.67.0-insider
OS: Mac

This a nit, but noticed a few places in the high contrast theme where some of the lines are not totally even, specifically in the terminal.

The underline under the word bleeds outside the box around it on the sides a bit.  
<img width="529" alt="image" src="https://user-images.githubusercontent.com/9721254/161854858-4d3cf92d-c636-4591-8bcc-bd7c57460919.png">

The terminal box is a bit underneath the dividing line between the list of all open terminals.
<img width="544" alt="image" src="https://user-images.githubusercontent.com/9721254/161854996-efbeaf8b-feb9-4038-8cb8-0b648795249f.png">

**Comment by Z-E-D** [comment]
Is there any reason why high contrast themes have that underline displayed in the active tab of bottom panel at all since they already have border line around the active tab? I found it visually quite odd.

The underline lines under editor tabs ("tab.activeBorder") are outside the border lines i.e. they are actually under them, and more visually appealing to me then that of bottom panel.
