### ISSUE TITLE
No space between time and afternoon in source control hover

### ISSUE THREAD

**Issue by garychen2002** [microsoft/vscode#146846]
Issue Type: <b>Bug</b>

Hovering over a commit in source control shows a time in the format of "1:19in the afternoon" where there should be a space.
![image](https://user-images.githubusercontent.com/88006497/161832238-f0691fc7-9cb3-42a3-bb55-68388328d6d0.png)

VS Code version: Code 1.66.0 (e18005f0f1b33c29e81d732535d8c0e47cafb0b5, 2022-03-30T05:50:14.623Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

**Comment by lszomoru** [comment]
@garychen2002, apologies for not getting back to you on this until now. There have been some improvements in the Timeline view in the last couple of months so I am wondering if you are still able to reproduce this issue. If so, do you mind sharing a larger screenshot so that I can see the view. Thanks!

**Comment by garychen2002** [comment]
Hello. I cannot reproduce the issue currently. The time format of the source control view seems to be different now. 
![image](https://user-images.githubusercontent.com/88006497/207101594-d3853cd2-67cb-4625-96f2-a6c6764263f0.png)

**Comment by lszomoru** [comment]
@garychen2002, thanks for the update. Closing the issue for now.
