### ISSUE TITLE
Feature request: lock ranges of the TextEditor

### ISSUE THREAD

**Issue by siegebell** [Microsoft/vscode#14699]
Request: provide API support to lock arbitrary ranges in the editor; i.e. make them read-only so the user and extensions cannot change the text within the region. This feature is supported by emacs (see [inhibit-read-only](https://www.gnu.org/software/emacs/manual/html_node/elisp/Read-Only-Buffers.html) and [this](http://unix.stackexchange.com/questions/76531/emacs-make-portion-of-buffer-readonly)). And it is useful for the extension I am writing for the Coq Proof Assistant: where editing a line that has already been interpreted causes the interpreter to roll back its state (potentially losing many minutes, sometimes an hour or so, of processing).

Now that I've made the request, I do have reservations about it being abused by extensions. So I think it would be prudent to also give the user the option to manually unlock any region and to globally disable the feature.

**Comment by CoenraadS** [comment]
I think this would also be nice to prevent changes to files when in debug mode.

**Comment by alexandrudima** [comment]
To keep the number of issues in our inbox at a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: we look at the number of votes the issue has received and the number of duplicate issues filed. Thank you for your time and understanding.

If you disagree and feel that this issue is crucial: we're happy to listen and to reconsider.
