### ISSUE TITLE
Developer Tools: node.js api error

### ISSUE THREAD

**Issue by hellopao** [Microsoft/vscode#147]
![vsc](https://cloud.githubusercontent.com/assets/5064875/11263530/7c7b489c-8ec6-11e5-8f8b-256393615126.png)

some node.js modules are not supported in vs code.

![atom](http://sfault-image.b0.upaiyun.com/235/097/235097771-564d697c10ea7_articlex)

it's ok in atom, i was used to check node.js apis by this way.

**Comment by alexandrudima** [comment]
@hellopao The global require you are hitting is the require defined in src/vs/loader.js (an AMD require function). Our code is compiled to AMD and not commonjs because compiling to AMD allows us to bundle multiple modules to one file, giving perf improvements in a built version... Therefore the global AMD require.

If you want to get from the Developer Tools to node's require you can use `require.__$__nodeRequire('util')`
