### ISSUE TITLE
Source Control does not refresh status automatically when working on WSL, v 1.66.x

### ISSUE THREAD

**Issue by ps2goat** [microsoft/vscode#147098]
Does this issue occur when all extensions are disabled?: Yes/No
Yes, the only extension I have installed is the remote WSL extension.

Version: 1.66.1 (system setup)
Commit: 8dfae7a5cd50421d10cd99cb873990460525a898
Date: 2022-04-06T14:50:12.141Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0 (using node 12.22.x in the project)
V8: 9.8.177.11-electron.0
OS: Windows_NT x64 10.0.19044

Remote:
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20.04
Codename:       focal

Steps to Reproduce:

1. pull code
2. make a change to a file, save it.
3. The source control panel does not show any changes. Clicking refresh causes the panel to update.
4. remove changes and save.
3. The source control panel does not show the now-unchanged file. Clicking refresh causes the panel to update.

There are a few related, closed tickets. This one is most relevant: [#133510](https://github.com/microsoft/vscode/issues/133510). Others still have this problem, but were asked to create a new issue.

That ticket refers to another that says changing `git.autofetch=false` helps, but it does not. I did have this off by default in my WSL remote instance; it was enabled in my local settings. I disabled it in my local settings and still have the same issue. (It is now set to `false` in local, remote, and workspace settings.)

I updated my VS Code to the latest today, but it was also a problem with the previous version for me.

**Comment by lszomoru** [comment]
@ps2goat, where is the folder/workspace located that you are opening in WSL?
Is it located in the Linux or Windows file system (ex: `/mnt/c...`)? Thank you!

**Comment by ps2goat** [comment]
I'm in the linux file system, `~/development/`...

**Comment by lszomoru** [comment]
Thanks! Could you please try the following in order to collect further information to troubleshoot the issue:
1. Open the git repository in VS Code
2. Before making a change to the file please do the following:
  - Invoke the `Git: Set Log Level` command from the command palette, and set the level to `Trace`
  - Enable logging (Remote scenario) as described in [this wiki page](https://github.com/microsoft/vscode/wiki/File-Watcher-Issues)
3. Make a change to a file, and save the file
4. Share the file system watcher and git output logs

Also, did you customised the `files.watcherExclude` setting in your user settings or workspace settings?

**Comment by ps2goat** [comment]
I got through setting up the logging, then became distracted with something else. Today, it works!

I think the only thing I changed (besides log setup) was enabling my docker socket. I don't know if that's relevant or not.
`sudo chmod 666 /var/run/docker.sock`

**Comment by lszomoru** [comment]
Thanks for the update. In case you will be able to reproduce the issue again, please feel free to open this issue.
