### ISSUE TITLE
KeyBinding warning

### ISSUE THREAD

**Issue by CodeGenTeam** [Microsoft/vscode#14707]
1. 1.6.1
2. Windows 10

Conflict detected, command `workbench.action.terminal.openNativeConsole` cannot be triggered by ctrl+shift+c due to console.open

Conflict detected, command `workbench.action.terminal.copySelection` cannot be triggered by ctrl+shift+c due to console.open
![image](https://cloud.githubusercontent.com/assets/11016041/19833768/e6e5525c-9e67-11e6-91a0-bd93071bfb9a.png)

**Comment by Tyriar** [comment]
This is strange, there should be no warning unless these have been overridden since they have mutually exclusive `when` clauses:

```json
{ "key": "ctrl+shift+c",          "command": "workbench.action.terminal.copySelection",
                                     "when": "terminalFocus" },
{ "key": "ctrl+shift+c",          "command": "workbench.action.terminal.openNativeConsole",
                                     "when": "!terminalFocus" },
```

Can you confirm you don't have any keybindings that override them?

**Comment by Tyriar** [comment]
It looks like you have this extension installed https://marketplace.visualstudio.com/items?itemName=vilicvane.console which intentionally overrides the keybindings.

I created https://github.com/vilic/vscode-console/issues/1 to follow this up on that side.

**Comment by Tyriar** [comment]
PR to fix copying within integrated terminal if you install this extension: https://github.com/vilic/vscode-console/pull/2

**Comment by CodeGenTeam** [comment]
Yes, I have this extension.  https://marketplace.visualstudio.com/items?itemName=vilicvane.console

**Comment by CodeGenTeam** [comment]
@Tyriar but I have left one problem:
Conflict detected, command `workbench.action.terminal.openNativeConsole` cannot be triggered by ctrl+shift+c due to console.open

**Comment by Tyriar** [comment]
@CodeGenTeam that extension intentionally replaces the native VS Code behavior (the `workbench.action.terminal.openNativeConsole` command). If you remove the extension you can still launch a terminal of your choosing with by setting `"terminal.external.windowsExec"` in your settings.json file.

Note that these warnings are perfectly fine to see if the keybinding override was intentional. If you happen to need both then you should choose another keybinding for `workbench.action.terminal.openNativeConsole`.

**Comment by CodeGenTeam** [comment]
Clear. But now I don't need this extension, bcz it's integrated
