### ISSUE TITLE
GitHub Codepaces on iPad limitations

### ISSUE THREAD

**Issue by CodeFromAnywhere** [microsoft/vscode#147134]
I’ve tried Codespaces on my iPad Air 2022 but unfortunately I can’t work with it productively. Here are some limitations that I can’t find a solution for that are currently holding me back to do my day to day job on my iPad:

* It keeps disconnecting whenever I switch to a different app and back to the code editor. Every time I come back I have to wait 10 seconds or longer to do anything again
* Wen you go away a bit longer it says “disconnected, attempting to reconnect”. This will last a minute before it says “can’t reconnect. Reload”. 
* Sometimes it kills the processes in the terminal, for example when building. I even had this with a machine with 8GB memory. It never happens on my MacBook Air with 8GB memory. Maybe you should enable swap memory on the codespaces machines?
* Most of my clients have their own organisation with hundreds of developers and they don’t have GitHub teams because they don’t need it. If I want Codespaces to work they would have to purchase teams for everyone in the organisation which they will never do for just 1 dev. This makes it impossible to use codespaces for most of my work. It would be great if there was an individual subscription to Codespaces a instead of just for organisations so you can use all your repo’s you have access to as an individual in all organisations you have access to. I don’t see/understand why this has to be organisation/team based.

If these issues would be resolved it would be a fantastic way to code from my iPad and code from anywhere. I would literally drive to a forest and have my meetings there while walking (I bought a neck mount for that). When I need to code I’d just take my chair out of my backpack and sit down and code. Work from nature! Code From Anywhere!

If I can help with making codespaces better in any way (especially for iPad, the main reason why I would use it) I would love to connect with the people working on it. Please contact me at wijnand AT karsens DOT com. For now I will stop using codespaces and cancel my teams subscription and I’ll just do my meetings from the forest/mountains.

**Comment by Lemmingh** [comment]
> It would be great if there was an individual subscription to Codespaces

GitHub decided to **defer** rolling out individual plans.

* <https://github.com/features/codespaces>
* <https://github.com/github/feedback/discussions/5038#discussioncomment-1230049>

> When can I use Codespaces on my personal repos?
>
> We’ll share more information about how individuals will be able to use Codespaces in the future. Individuals in the existing beta will continue to have access to Codespaces and will not be charged.

**Comment by msob** [comment]
I agree completely with this issues and want to add one more.

The on screen touch keyboard does not work reliably, when using a Home Screen Shortcut to a Codespace, I even cannot log into Github, because the keyboard is missing.

**Comment by TylerLeonhardt** [comment]
@jkeech this feedback all seems on the Codespaces side, do you think you can assist here?

**Comment by jkeech** [comment]
Thanks for taking the time to provide this feedback! For future reference, https://github.com/github/feedback/discussions/categories/codespaces-feedback is a great place to connect more directly with the Codespaces team at GitHub to ask questions and provide feedback.

>It keeps disconnecting whenever I switch to a different app and back to the code editor. Every time I come back I have to wait 10 seconds or longer to do anything again

Mobile Safari seems to be fairly aggressive about killing background connections when tabs are not in the foreground, likely to help with battery life. I don't think there's much we can do about that from the Codespaces side, and we shouldn't try to circumvent browser policies around lifetime management of websocket connections.

When you switch back to the codespace tab, it should detect that it's disconnected and automatically start reconnecting. Our goal is to make that as fast and seamless as possible, but it does take a couple seconds today to re-establish the secure tunnel to the codespace. We're continuing to look into how to optimize the connection process further to make it faster.

>Wen you go away a bit longer it says “disconnected, attempting to reconnect”. This will last a minute before it says “can’t reconnect. Reload”.

This is not expected. Most likely the VS Code server on the remote side has stopped by the time you return and the client side is not handling that properly to spin up a new server process. We'll investigate this.

>Sometimes it kills the processes in the terminal, for example when building. I even had this with a machine with 8GB memory. It never happens on my MacBook Air with 8GB memory. Maybe you should enable swap memory on the codespaces machines?

Thanks for the suggestion. It's true that swap space is not enabled on Codespaces machines today in order to provide consistent performance for the remote machine, but I understand it's a tradeoff that some people would want to make. We will consider adding this as a feature. Another solution is to use a larger machine type with more memory to avoid getting into an out-of-memory situation where you would need to swap to disk. Codespaces supports several machine type configurations up to 32-core, 64 GB RAM. Please contact GitHub Support if you'd like to enable the larger machine types to try out.

>It would be great if there was an individual subscription to Codespaces a instead of just for organisations so you can use all your repo’s you have access to as an individual in all organisations you have access to.

I don't have anything specific to share here for now, but we are evaluating how to make Codespaces available to more people.

**Comment by TylerLeonhardt** [comment]
Thanks for answering @jkeech! I'm gonna close this in favor of having folks follow up on https://github.com/github/feedback/discussions/categories/codespaces-feedback
