### ISSUE TITLE
Terminal stealing focus from editor on Safari

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#147180]
https://user-images.githubusercontent.com/876920/162631931-5b424abf-4ee6-4587-a5d4-e7520c895000.mov

As shown in the recording, when I tried to paste in the editor

* 🐛  The terminal paste command is matched, meaning that the terminal is still "focused" based on the context keys
* 👎  The terminal shows a context menu for paste. We are not seeing this in the editor, the terminal should handle in the same way

**Comment by rebornix** [comment]
As long as the terminal is opened once, I have to reload the window to get it fixed.

**Comment by meganrogge** [comment]
I think this means that this isn't happening on safari for some reason
https://github.com/microsoft/vscode/blob/5cc4bc671b8889e6b06d9ba9ab9b12bc820c3cd1/src/vs/workbench/contrib/terminal/browser/terminalInstance.ts#L1109-L1113

**Comment by meganrogge** [comment]
This gets hit even when I click in the editor area
![Screen Shot 2022-04-21 at 5 27 53 PM](https://user-images.githubusercontent.com/29464607/164573419-e645c10a-a94c-43d2-87d6-036dd3c2a09c.png)

**Comment by rebornix** [comment]
Still reproduced on latest codespace with VS Code insider bits.

**Comment by Tyriar** [comment]
Had a call, we believe it's happening because we set `display: none` when hiding the panel which caused the blur/focusout events to not fire. We also noticed this happens in terminal editors as well. So to fix we need to reset or refresh the state of the `terminalFocus` context key when the terminal panel/view is hidden as well as when the terminal editor is hidden.

Something to verify when these changes are made is to make sure if you have a single terminal editor and a single terminal in the panel, toggling the panel should still keep `terminalFocus` because the terminal editor will now be focused (ie. the panel hide context key reset should happen before the terminal editor focus is handled).
