### ISSUE TITLE
Add 'open settings.json' option to configuration menu (gear in bottom left)

### ISSUE THREAD

**Issue by Robonics** [microsoft/vscode#147194]
It's rather annoying to have to open settings, then scroll all the way down just to change one field in settings.json. Quite simply I think having an 'open settings.json' button would be very convenient.

**Comment by gjsjohnmurray** [comment]
Have you already found the button on the Settings Editor toolbar (top right) which does this?

**Comment by rzhao271** [comment]
Sharing a screenshot because I didn't know about it for a while either (I used the `workbench.action.openSettingsJson` command in the command prompt instead).
![A screenshot showing the open settings.json button to the right of the open editor tabs when one is in the Settings editor](https://user-images.githubusercontent.com/7199958/162768959-5d5c5b80-8d64-4948-a48a-77c515743246.PNG)
