### ISSUE TITLE
virtual keyboard not shown

### ISSUE THREAD

**Issue by teobugslayer** [microsoft/vscode#1472]
Consider this scenario. I am running Code on 8" Windows 10 tablet. Code is version 0.10.5, Windows is 10.0.10586. When I start Code, the on screen keyboard is never shown and I cannot enter any text.

Other programs behave as expected.

**Comment by bpasero** [comment]
I think we used to have an explicit action to trigger this.

**Comment by felixfbecker** [comment]
+1. I'm often working on my Surface Pro 3. While scrolling with touch is working great, this is kind of annoying. But please, please, please, if you implement something for this, make it so that the keyboard does _not_ pop up when I am _not_ in tablet mode on Windows 10.

**Comment by lw-schick** [comment]
Why is this still in backlog? When will this be fixed?

**Comment by alexandrudima** [comment]
@lw-schick Because there is no w3c API to pop up an on screen keyboard.

**Comment by felixfbecker** [comment]
@alexandrudima In Chrome the on-screen keyboard pops up correctly when you tap an input field, so why not in VS Code?

**Comment by alexandrudima** [comment]
@felixfbecker Because the editor is not a native input field like the find widget (1) (a textarea is used for input, but the touch gesture occurs on some different dom node). From the touch handler we call `textarea.focus()`, but that is not a sufficient hint for Chromium to decide to pop up the on-screen keyboard. Hence, there is an API lack that we can inform the browser that the tap was meant for the textarea. We have experimented with some hacks to overlay the textarea on top of the editor, but that doesn't work, because the editor does not contain only text, it might contain trees, widgets or even other editors (2):

(1)
![image](https://cloud.githubusercontent.com/assets/5047891/19855668/0c447ed8-9f76-11e6-9123-aec284800812.png)

(2)
![image](https://cloud.githubusercontent.com/assets/5047891/19855748/7b06baca-9f76-11e6-8470-199b1f23a0dd.png)

**Comment by felixfbecker** [comment]
Is it not possible to have an invisible `<textarea>` that you `click()` programmatically whenever the editor is focused?

**Comment by alexandrudima** [comment]
@felixfbecker I haven't tried that, that would make a great PR. Here is how to get the shared code we use also running in Firefox and in IE for testing purposes -- https://github.com/Microsoft/monaco-editor/blob/master/CONTRIBUTING.md
