### ISSUE TITLE
Allow multiline eval results in debug console

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#14729]
I'd prefer to see a multiline result instead of escaped newlines
![image](https://cloud.githubusercontent.com/assets/323878/19842437/4df4f510-9ed6-11e6-947b-89ef5e51c9ba.png)

**Comment by isidorn** [comment]
This is up to the debug adapter. Since each evaluten passes a context 'hover' or 'repl'. And vscode should not be in the position of massaging strings for all languages IMHO

fyi @weinand

**Comment by roblourens** [comment]
It seems like vscode is escaping the strings somewhere (the debug adapter also was, but when I force it to not do that...) I'll investigate some more.

**Comment by isidorn** [comment]
Did a full text search inside debug folder, found some interesting candidates
Forgot what is the exact purpose of this https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/common/debugModel.ts#L25 but might be a starting point

**Comment by roblourens** [comment]
Yeah that's it... I'm not sure how to handle this though - at first I wanted to skip `massageValue` for eval results in the console, but it seems like strings in an object preview like `["a\nb"]` should stay on one line. We could leave the logic up to the debug adapter like you say, but other debugger authors are assuming that their strings will be escaped for them. Is that too big of a breaking change?

**Comment by isidorn** [comment]
I do not think that is a big breaking change. 
@weinand thoughts?

**Comment by weinand** [comment]
Since this is a breaking change we need to offer opt-in for clients.
Debug protocol changes: 
- a document change for the debug protocol,
- a new capability `supportsEscapedNewlines`

The VS Code must only implement Rob's change from above if the debug adapter returns `true` for `supportsEscapedNewlines`.

**Comment by weinand** [comment]
@isidorn please make sure that the `supportsEscapedNewlines` controls *all* newline massaging. 
We want to avoid that we have to introduce another capability for this in the future.

**Comment by roblourens** [comment]
@weinand Good point, even though we don't render multiline strings very well in the variables pane, there might be another client that does, and we should try to treat all the strings from the debug adapter consistently.

**Comment by roblourens** [comment]
I'm still thinking about the capability name though, since an adapter might specifically set this option to avoid escaping newlines.

**Comment by roblourens** [comment]
Would you be ok with `disableValueEscaping`? 'value' to encompass variables and eval results, but not all the other string labels and things that can be returned.

**Comment by weinand** [comment]
@roblourens I agree that 'ValueEscaping' is more precise than 'EscapedNewlines'.
But I don't like the 'disable' because it changes the subject (and the direction) of the capability: in all other capabilities of the 'supports\*' form the debug adapter is the subject. With the 'disable\*' form a debug adapter would make the client the subject.  

Since I do not see the a big enough benefit of this change, I suggest that we use `supportsValueEscaping`.

If this is OK for you please update your https://github.com/Microsoft/vscode-debugadapter-node/pull/83.

**Comment by weinand** [comment]
Merged  PR Microsoft/vscode-debugadapter-node#83. `supportsValueEscaping` is now available in the latest.

**Comment by weinand** [comment]
I've reverted the PR https://github.com/Microsoft/vscode-debugadapter-node/pull/83
