### ISSUE TITLE
Finalize suppressSaveBeforeStart API

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#147263]
Added in https://github.com/microsoft/vscode-jupyter/issues/6898

This lets an extension starting a debug session forcibly override the user's setting about saving files before debugging.

The jupyter debug adapter may be trying to debug an untitled notebook. This makes sense for notebooks but doesn't make sense for other debug adapters.

I was looking at how it's used and wondering whether this should actually be a property of the debug adapter. The debugger contribution could declare that it is able to debug unsaved/untitled files.

cc @weinand @isidorn any thoughts about that?

**Comment by weinand** [comment]
@roblourens let me first try to recapitulate the problem:

In https://github.com/microsoft/vscode-jupyter/issues/6898 we agreed on a new flag `DebugSessionOptions.suppressSaveBeforeStart` that can be passed to `vscode.debug.startDebugging()` in order to suppress the "Save unsaved/untitled file" dialog when debugging notebook cells.

The implementation of this API needs the information whether the underlying debugger is actually able to debug unsaved/untitled files or not (as you have pointed out in your proposal). If the debugger:
- supports debugging unsaved files the "Save" dialog can be suppressed,
- does not support debugging unsaved files the "Save" dialog must be shown.

A consequence of this behavior is that the `DebugSessionOptions.suppressSaveBeforeStart` API can only be a "hint": the the "Save" dialog can only be suppressed if the debugger supports it. I think that's OK but maybe the naming should reflect this.

More to come...

**Comment by roblourens** [comment]
When you say 

> and cannot be used for a "dynamic" debug extension that "forwards" debugging generically to some other component, e.g. a debugger in a notebook kernel.

and also

> In one of my samples I was implementing a generic notebook debugger in the extension alone that could deal with unsaved/untitled files and the underlying DAs were unaware of this.

you are talking about an extension that calls startDebugging to invoke a debug adapter from a different unrelated extension, right? And I think in your sample, your extension is reading the notebook, writing to some file, and telling the DA to debug that file? So in that case, the DA is not actually debugging the unsaved file, but by default we would trigger a save on it. 

That shows what makes this messy - we don't know which files are involved in the new debug session, so we save everything. We also have the question of unsaved changes in the notebook vs in other files. If your notebook imports a local .py file, that file would actually need to be saved to have its changes loaded in the new debug session.

The jupyter debug adapter is single-purpose and always can debug without triggering a save, but probably there are other cases where a simple boolean flag in the contribution is too limited. So then we could have

> a string is a command ID that can be used to return a dynamic value for the property...

What context does it get, the rest of the launch config?

Thinking through everything, it seems like the simplest option would be to just keep the debug session option, make it the responsibility of the caller of startDebugging, since we have all this flexibility and it's probably hard to decide what is "supported" by which DA or extension.
