### ISSUE TITLE
Breakpoint decorations go to wrong place

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#147329]
- Open menuService.ts
- Set some breakpoints
- They show in the wrong place and cover a character, but seemingly get fixed when setting a breakpoint on the next line

![Recording 2022-04-12 at 16 31 15](https://user-images.githubusercontent.com/323878/163071018-1265f8bc-ec1f-40af-9962-6695e14b2ad7.gif)

**Comment by hediet** [comment]
It is non-deterministic:

![recording](https://user-images.githubusercontent.com/2931520/163138317-1bc7e4bc-716e-457d-a12b-6c876188574c.gif)

Maybe that depends on the timing of the debugger.

If I add `true || (...)` to this statement (effectively removing the condition), I cannot reproduce anymore:
https://github.com/microsoft/vscode/blob/fa8d1063f6ab829e848575cf402d8bca74bcc2d4/src/vs/workbench/contrib/debug/browser/breakpointEditorContribution.ts#L614

Unfortunately that might cause performance problems.

I think this is because `layoutContentWidget` needs to be called when injected text is inserted before it.

**Comment by roblourens** [comment]
I am currently still reproing it here: 
<img width="445" alt="image" src="https://user-images.githubusercontent.com/323878/180102963-df29c6f2-588d-4556-b83f-4460135bebd1.png">

https://github.com/microsoft/vscode/blob/eaeb3a74ab80384a3cd2c924d73721a290bb0f99/src/vs/platform/externalTerminal/node/externalTerminalService.ts#L166

btw @hediet make sure you add labels and a milestone to issues for verification and tracking

**Comment by roblourens** [comment]
Any chance this could be looked at soon? It comes up pretty often

<img width="1018" alt="image" src="https://user-images.githubusercontent.com/323878/193931039-48a4a786-d8fb-4265-8369-cc8fe1f1c66d.png">

**Comment by roblourens** [comment]
Thanks @alexdima!
