### ISSUE TITLE
Git - Stage Selected Ranges broken again?

### ISSUE THREAD

**Issue by jhillert-dmg** [microsoft/vscode#147373]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.66.2
- OS Version: 11.6 (Big Sur)

Steps to Reproduce:

1. Make some changes in a file at two different places ("1st changes" and "2nd changes")
2. Open Source Control Sidebar and select file you just changed to see the diffs for 1st & 2nd changes in the editor.
3. Select the red and green diff of 1st changes, right click the selection, and choose "Stage selected ranges".  RESULT: As expected, the diff of 1st changes will disappear from the editor, the current file will appear under Staged Changes in the sidebar, and the diff of 1st changes will be visible in "Staged Changes" editor. 
4. Go back to the "Changes" editor and repeat step 3 for 2nd changes. 
EXPECTED RESULT: The same thing should happen for 2nd changes.
ACTUAL RESULT: The same thing does happen for 2nd changes, but 1st changes are reverted and move from Stage Changes to Changes (i.e., 2nd changes are staged, 1st changes are unstaged.).

![image](https://user-images.githubusercontent.com/85570613/163171180-a5d7095f-7f2c-452a-9d82-6150ecfba9f1.png)
![image](https://user-images.githubusercontent.com/85570613/163171518-11ae4d96-4ee9-45c5-96cd-7114cdf6e3b9.png)
![image](https://user-images.githubusercontent.com/85570613/163170408-44634318-23d4-4bb2-8543-ae45abee807f.png)
![image](https://user-images.githubusercontent.com/85570613/163172075-d1e49908-ad3f-432c-95bc-9e501d52edcf.png)
![image](https://user-images.githubusercontent.com/85570613/163170826-728b8884-766e-4136-935a-df1defd9ee83.png)

**Comment by darkvertex** [comment]
Just chiming in to say I'm having extremely erratic "selected ranges" staging behaviour as well. Usually it works great.

```
Version: 1.66.2 (user setup)
Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977
Date: 2022-04-11T07:46:01.075Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Windows_NT x64 10.0.19044
```

**Comment by DevilXD** [comment]
I am experiencing the same issue, although I usually use the green (addition) and blue (change) colored ribbon-thingies (and red triangles for deletion) that appear on the left side of the code after changes. Clicking on them lets me interactively stage a single change from a file, but sometimes trying to stage more than one change, causes the previously staged changes to unstage. It's really annoying. [I thought it could be a GitLens issue (since I also use it as well), but I've been told this feature comes from VSCode itself.](https://github.com/gitkraken/vscode-gitlens/issues/2191)

**Comment by guanzo** [comment]
I'm seeing this issue on WSL mode.

**Comment by eldar** [comment]
This one is still broken. Here is a screen recording demonstrating the bug: https://imgur.com/a/ma7I0pj

Also no visual feedback is provided when staging individual changes.

**Comment by bandtank** [comment]
If you navigate away from the file after staging a selected range, it works. The issue needs to be fixed, but this crappy workaround helps in the interim.

**Comment by phoenixeliot** [comment]
I don't know if this is related yet but I'm finding that "stage selected changes" is ignoring deletions, only staging additions

**Comment by chiholai-sanasofthk** [comment]
bump, still an issue in 1.77

**Comment by account-sxf** [comment]
> bump, still an issue in 1.77

It should be noted that in the working tree split view it works only on the right pane or end result side. For some reason I was trying to stage my changes by selecting the change on original side which doesn't work. Maybe this will help anyone who googled this issue.

**Comment by Pulseczar1** [comment]
This is also happening to me in version 1.77.3, Linux x64. I'm not attempting to stage changes on the left pane -- only on the right pane. It was such a nice feature in the previous version I was using, when it worked. Some notes about it:
- To get VS Code to "accept" the staging -- react at all and no longer show the change, you have to switch to another tab and back. I like to switch to the `Staged Changes` version of the file and then back to the `Changes` version, in the `Source Control` file selector. Doing that gets it to behave similar to the way it did when there wasn't a problem.
- However, if you stage multiple selections, only the last one staged actually gets staged. So, you have to get it to update after every staging, in order to get it to accept every staging.
- Another alternative is to use the line staging functionality in the "main" file tab, available in the file `Explorer`. Click the colored lines that show up to the left of the changed lines and to the right of the line numbers (if those are turned on). Use the plus sign button to stage the change in the line. That functionality still works (but I prefer the side-by-side diff view. I hate that it's not working).

**Comment by virtualdj** [comment]
> If you navigate away from the file after staging a selected range, it works.

Same here, this is the only workaround that works!
VS Code version 1.83.1, Windows 10 22H2.

**Comment by rgbmrc** [comment]
Bump. For me the issue manifested recently, possibly after I disabled `git.autofetch`. I am not sure if it is related though, because I do not see how it should and because I re-enabled autofetch and the problem did not disappear.
```
Version: 1.84.2 (user setup)
Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
Date: 2023-11-09T10:51:52.184Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621
```

**Comment by darkvertex** [comment]
I commented in 2022 and I'm back now in 2024 to say I'm still regularly experiencing troubles staging additional lines after staging some. Sometimes it forgets what I staged and instead of staging _additional_ lines on top of what was previously staged, the selective staging overrides the currently staged contents for that file entirely, making it kinda pointless for complicated staging operations.

I've also noticed it gets confused by multiple cursors if you try to stage lines from many places/selections/cursors and only stages the first selection properly, if at all.

I'm so annoyed at this point if I have anything complicated to stage I just open the Terminal and run [gitui](https://github.com/extrawurst/gitui) instead. :/

```
Version: 1.85.1 (user setup)
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Date: 2023-12-13T09:49:37.021Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621
```

**Comment by dongseok0** [comment]
Same issue here - it doesn't work at all
```
Version: 1.85.2 (Universal)
Commit: 8b3775030ed1a69b13e4f4c628c612102e30a681
Date: 2024-01-18T06:40:32.531Z
Electron: 25.9.7
ElectronBuildId: 26354273
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 22.5.0
```

**Comment by jankap** [comment]
Still broken

![image](https://github.com/microsoft/vscode/assets/12893844/4203bace-de5f-4360-ad40-2169a74b257b)

I'm pretty sure this *has worked* back in time. Now I just can't add multiple chunks and need to go the reverse way - git add the whole file and then unstage chunk by chunk. I'll test the unfocus workaround, too.

**Comment by cartok** [comment]
Feature broken

**Comment by goshaaz** [comment]
Still an issue for me

**Comment by spencermathews** [comment]
Something is still very buggy with "Stage Selected Changes".

I'm observing that the first block chosen does get staged, but subsequent changes do not get staged unless the diff editor is exited and re-entered.

**Comment by yassine-safraoui** [comment]
I just had this issue with Stage Selected Changes, when I try to run it after having selected some text it does not do anything, the work-arround I found was to first stage the whole block of the selection and then unstage the unwanted lines by selecting them and choosing Unstage Selected Ranges, at least that's somewhat acceptable if you only have a contiguous block to commit.

Note: I was facing issue when using VS code to write latex, maybe the LaTeX Workshop extension is related because I have it enabled but I really don't think so

**Comment by sudoandros** [comment]
Still having the issue with 1.96.0, at least with WSL Remote. Sometimes changes are staging all right, sometimes some changes are staying unstaged. I'm not even sure what logic it follows, seems completely chaotic to me.

**Comment by lszomoru** [comment]
Thank you all for commenting on this issue and apologies for not getting back to you on this until now. In recent days I have pushed some changes that address some of the issues with the "stage selected ranges" command. I would really appreciate if you could try the latest VS Code Insiders release (version information below) and would let me know if that resolves the problem. In case you are still able to reproduce the issues I would really appreciate if you could:
1. See if you are able to reproduce in a simple repository which you could share
2. Share a recording (https://gifcap.dev) assuming that you are able to consistently reproduce the issue
3. Let me know if you are invoking the command from a text editor or a diff editor
4. If you are using a diff editor see if you can reproduce the problem when using the "Stage Selection" command available in the editor gutter. 

```
Version: 1.97.0-insider
Commit: cf2ebd91b8e42e3bc5ab0e85e3323c886a977ffe
Date: 2024-12-18T06:50:13.779Z
Electron: 32.2.6
ElectronBuildId: 10629634
Chromium: 128.0.6613.186
Node.js: 20.18.1
V8: 12.8.374.38-electron.0
OS: Darwin arm64 24.2.0
```
