### ISSUE TITLE
Git 2.35.2, Windows 10, VS Code doesn't work anymore with Git

### ISSUE THREAD

**Issue by frederikhors** [microsoft/vscode#147358]
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.67.0-insider (user setup)
Commit: e3f21a18e2727ac37c78159ba81f2c6ee4a982cc
Date: 2022-04-13T05:15:45.536Z
Electron: 17.4.0
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.19044

- OS Version: Windows 10

Steps to Reproduce:

1. new dir
2. initialize
3. doesn't work

With Git 2.35.1.2 everything good!

**Comment by IllusionMH** [comment]
/needsMoreInfo

Cannot reproduce. Have you tried to restart VS Code. What error do you see in Output for Git extension ?


My steps: Opened new folder with some files but without `.git`, opened SCM panel and clicked on Initialize repo.

Version: 1.67.0-insider (user setup)
Commit: e3f21a18e2727ac37c78159ba81f2c6ee4a982cc
Date: 2022-04-13T05:15:45.536Z
Electron: 17.4.0
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.19043

git version 2.35.2.windows.1

**Comment by frederikhors** [comment]
> opened SCM panel and clicked on Initialize repo

Create a file, save it. The git panel is not working anymore.

I'll read output in a few minutes... I downgrade to 2.35.1.2.

**Comment by lszomoru** [comment]
@frederikhors, maybe I ask you to do the following in order for us to track down the issue:
1. Open the folder in VS Code
2. Invoke the `Git: Set Log Level` command and set the command level to 'Trace`
3. Modify the a file and save it
4. Share the Git output which you can access using the `Git: Show Git Output` command

**Comment by AlexDanault** [comment]
I have the same thing ahappening on my machine. One key element : repos installed *locally* on my machine (C:, D:) work in vscode. Repos installed in WSL (Ubuntu 20) don't (vscode doesn't see the repo, and can't init it). 

Here's the git trace log for the WSL projet I'm opening:

```
[2022-04-13T15:15:41.739Z] Validating found git in: C:\Program Files\Git\cmd\git.exe
[2022-04-13T15:15:41.795Z] Using git 2.35.2.windows.1 from C:\Program Files\Git\cmd\git.exe
[2022-04-13T15:15:49.136Z] > git init [177ms]
```

Beyond this, nothing happens, neither in the log and in vscode's git panel.

**Comment by AlexDanault** [comment]
One more piece of information: For me, the problem is Git itself. When in WSL (bash) `bit status` works. But in a windows command prompt, Git doesn't : 

```
error: failed to get owner for '//wsl$/Ubuntu20.04LTS/home/alex/Code/vtcloud' (1)
fatal: unsafe repository ('//wsl$/Ubuntu20.04LTS/home/alex/Code/vtcloud' is owned by someone else)
To add an exception for this directory, call:

        git config --global --add safe.directory '//wsl$/Ubuntu20.04LTS/home/alex/Code/vtcloud'
```

Trying to run the suggested command yields `error: failed to get owner for '//wsl$/Ubuntu20.04LTS/home/alex/Code/vtcloud' (1)`

As this seems to be a Git problem, I suggest this issue shoudl be closed if the other reporter @frederikhors canconfirm they're on WSL too.

**Comment by kganguly-vertex** [comment]
Hi all. This is due to the fix for the first security vulnerability mentioned here:
https://github.blog/2022-04-12-git-security-vulnerability-announced/
and similar to the Git for Windows issue reported here:
https://github.com/git-for-windows/git/issues/3787

Basically, the folder needs to be owned by the user or explicitly configured as a [safe directory](https://git-scm.com/docs/git-config/2.35.2#Documentation/git-config.txt-safedirectory):
![image](https://user-images.githubusercontent.com/61993264/163223909-bc4c0e52-9a1a-49e6-9022-d0f32066f91d.png)
Looks like this comes up with WSL, but it's more general to any folders not owned by the user.

I tend to run my terminal as admin, but not my VSCode.  I usually clone repos from my terminal within in a shared directory at the root of my C drive (e.g. `C:/shared`).  After updating to Git for Windows 2.35.2, VS Code saw my existing repo folders as not having git initialized.  Default extension log levels showed nothing.  My terminal running as admin worked fine, but running a non-admin terminal shows the same message as mentioned in the Git for Windows issue above.
![image](https://user-images.githubusercontent.com/61993264/163220642-5852b57e-b61f-41a7-b360-3eceadb4a8fe.png)
Running the suggested command immediately fixed the VS Code issue. From https://github.com/microsoft/vscode/issues/147358#issuecomment-1098205331 , sounds like it's not so straightforward with WSL. 

Currently, there's no way to mark multiple directories as safe in one command, but they're working on a way to opt out of this safety check completely.
https://github.com/gitgitgadget/git/pull/1215

**Comment by frederikhors** [comment]
I'm on Windows 10, all default, VS Code setup too.

I think this will affect all users in the future if we close this as is.

**Comment by lszomoru** [comment]
> I think this will affect all users in the future if we close this as is.

VS Code will use the version of `git` that is installed on the machine. If `git` has been upgraded to version `2.35.2` or later, there will be a change in behaviour when it come's to VS Code's ability to detect a git repository as a result of the change in behaviour in `git`.

**Comment by mrleemon** [comment]
I'm on Windows 10 and I'm having the same problem.
Even though .git folders are present in all of my projects, VSCode doesn't detect any local repositories.

VSCode: 1.66.2
Git: 2.35.3

**Comment by AlexDanault** [comment]
@mrleemon I had the same problem, upgrading to Git 2.35.3 didn't fix the issue, running the commands suggested by git (to add the directory as safe) didn't work either.

After some research I found that the command contained single quotes and they got stored in my global `.gitconfig` and they were the culprits.

In the end I just edited my global `.gitconfig` so that the `[safe]` section looks lie this:

```
[safe]
	directory = %(prefix)///wsl$/Ubuntu20.04LTS/home/alex/Code/vtcloud
	directory = ///wsl$/Ubuntu20.04LTS/home/alex/Code/vtcloud
```

Yes, there are two copies. The Git command line respects the one with `%(prefix)` while Github Desktop likes the second one.

This isn't really a VSCode issue, but I think VSCoode needs to be able to detect the unsafe directory instead of saying the repo isn't initialized.

**Comment by lszomoru** [comment]
Please note that `git 2.36` added support for specifying `*` for the `safe.directory` option as documented [here](https://github.blog/2022-04-18-highlights-from-git-2-36/).

**Comment by joglr** [comment]
I also experienced this issue. The issue disappeared after deleting the repository and cloning it again. I agree that VS Code could be more helpful in this situation. There was no indication of why it didn't detect my repository and clicking the initialize repository button did nothing.

**Comment by frederikhors** [comment]
With git `2.35.3` it works doing `git config --global safe.directory *`.
