### ISSUE TITLE
When using mouse navigation buttons on a view zone, text selection mode is activated

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#147306]
I selected the `delete` function using the left mouse-button.
Then I clicked on `constructor` and use the backwards mouse button to navigate back. This works as expected:
![recording](https://user-images.githubusercontent.com/2931520/162987055-415bbb8a-2b10-4f78-a9fa-34ad5ee93063.gif)

However, this does not work anymore when the cursor is one a view zone, e.g. code lens:

![recording](https://user-images.githubusercontent.com/2931520/162987598-71fe71aa-017f-4c9a-a486-9cece97a2467.gif)

When the mouse cursor is on a view zone, pressing the backwards button behaves as pressing the left button. This often breaks the flow.

**Comment by alexdima** [comment]
I think this is caused by the `mouseHandler` suppressing mouse down on this particular view zone [here](https://github.com/microsoft/vscode/blob/21ca44d35b0291a677188c70c70950aec47cb3ce/src/vs/editor/browser/controller/mouseHandler.ts#L293-L297). The code lens view zone opts into it via `suppressMouseDown` [here](https://github.com/microsoft/vscode/blob/21ca44d35b0291a677188c70c70950aec47cb3ce/src/vs/editor/contrib/codelens/browser/codelensWidget.ts#L38)

**Comment by hediet** [comment]
Weird, I already fixed this. Probably I just forgot to close this issue.

**Comment by hediet** [comment]
Nevermind, I didn't fix it, it still happens.
