### ISSUE TITLE
Annoying UI with easy(?) fix

### ISSUE THREAD

**Issue by bjornallvin** [microsoft/vscode#147403]
Issue Type: <b>Feature Request</b>

When you hover over some underlined problem and a popup appears with options. I tend to move my mouse in a straight line towards the option I'd like to click on. But since this takes the mouse outside the popup box for a fraction of a second, the option disapears just when the pointer reaches the option. Please add a timer of roughly 200ms before you hide the popup. In the old jQuery days this effect was called 'hoverIntent'. Would be a huge improvment on this UX.

<img width="685" alt="image" src="https://user-images.githubusercontent.com/2735574/163244179-f0f7fc63-60c7-482f-9b97-6616f9603a9d.png">

VS Code version: Code 1.66.0 (e18005f0f1b33c29e81d732535d8c0e47cafb0b5, 2022-03-30T05:50:04.419Z)
OS version: Darwin x64 21.4.0
Restricted Mode: No

**Comment by gjsjohnmurray** [comment]
See also #120016

**Comment by PositiveUser** [comment]
Include `"editor.hover.sticky": true` in **Settings.json** and see if your issue fixes. I had the same issue.

**Comment by bjornallvin** [comment]
> Include `"editor.hover.sticky": true` in **Settings.json** and see if your issue fixes. I had the same issue.

Thanks @PositiveUser but does not adress the issue. That setting (which I have turned on) says to keep the popup open as long as you hover over it. The issue is that the popup dissapears while I move from the underlined section towards an link inside the popup. And on the way there the mouse cursor is not on top of either the underlined section or the popup. If there was a small delay when hiding the popup it would allow the mouse cursor time to "bridge" the gap.

**Comment by clenemt** [comment]
This is the most annoying thing so far with vscode hover. Gitlens uses them extensively when in blame mode, and it takes me sometime 5 interaction to be able to click some of those buttons inside the hover. I understand this is a vscode issue hence this comment. Pinging @eamodio just in case. It became event worst since the last May update. 
![image](https://user-images.githubusercontent.com/447956/173060151-344d1b35-398b-468c-a08f-b8e6f803a5d5.png)
