### ISSUE TITLE
Peek references doesn't reveal peek

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#147448]
* invoke peek references for a symbol at the bottom the view port
* :bug: no scrolling, peek is barely visible 

https://user-images.githubusercontent.com/1794099/163386619-6c83a5b3-114b-4e9e-9fc4-5cd1d647d606.mov

**Comment by jrieken** [comment]
@alexdima @hediet I could only achieve this with an ugly `setTimeout`, e.g calling "reveal" after "super.show(...)" has no effect. Is it that the view zone is created async and that at the time of calling reveal the knowledge about that isn't there yet?

**Comment by jrieken** [comment]
ping @hediet @alexdima

**Comment by alexdima** [comment]
@jrieken (without debugging) I guess that `super.show(...)` is the call that adds the view zone. So in this case the `revealRangeInCenterIfOutsideViewport` call done before `super.show(...)` is probably a no-op because the range that is passed in is already in the viewport, so it will not be revealed in the center, as the method name hints.

**Comment by jrieken** [comment]
@alexdima it doesn't matter if the reveal-call happens before or after - it won't work either way. Also running with next microtask or animation frame didn't work, only setTimeout...
