### ISSUE TITLE
[typescript-language-features] Add command and editor context menu contribution for Find Source Definition

### ISSUE THREAD

**Issue by andrewbranch** [microsoft/vscode#147532]
I was overconfident in my ability to figure out how to expose https://github.com/microsoft/TypeScript/pull/48264 in VS Code 😅, calling on @mjbvz for help. I started copying some relevant stuff about commands and contexts from Find File References, but then I realized the UI behavior I want is identical to definitions/implementations, and I didn’t know how to reconcile those two things.

**Comment by mjbvz** [comment]
@andrewbranch Can you share the VS Code branch you've been using for testing?

**Comment by andrewbranch** [comment]
When I was developing https://github.com/microsoft/TypeScript/pull/48264, I just tested with VS Code Insiders by temporarily replacing the implementation of Go To Definition with the implementation of Find Source Definition since the response shape was the same. Now that https://github.com/microsoft/TypeScript/pull/48264 is merged, I don’t have a VS Code branch capable of testing it yet.

**Comment by mjbvz** [comment]
@andrewbranch Thanks! Just pushed a fix that should enable this command in two places:

- Right click in the editor context menu
- Through the command palette

Notes for testers:

- Verify that the command only shows up when using TS 4.7+
- The command should jump to the definition directly if there is a single source definition. Otherwise it should show a list of references
- If no references are found, we show an error notification. This UX is not ideal. In the future we hope to show an inline notification like `find all references` does

**Comment by IllusionMH** [comment]
Worked well so far for my "weird" cases:
1) JS project that has separate `types` folder with `declare module 'path/to/js/file' {...}` for key files. Correctly navigated to actual JS file (even for exports that are (intentionally) not exported in type declarations).
2) JS project where `jsconfig.json` and `node_modules` are in one folder, however `node_modules` with corresponding `@types` packages are couple of levels above. Navigated to correct JS source in `node_modules`.

**Comment by andrewbranch** [comment]
Thanks for testing!

**Comment by alexr00** [comment]
Works great, very useful!
