### ISSUE TITLE
Possibility to retrieve only "visible" text / lines

### ISSUE THREAD

**Issue by lucax88x** [Microsoft/vscode#14756]
Add an API method to retrieve only the "visible" text of the document in the editor, something like editor.GetVisibleRange() would be sufficient.

**Comment by alexandrudima** [comment]
This has been implemented via `TextEditor.visibleRanges`

**Comment by alexandrudima** [comment]
@lucax88x The API is in stable since quite a while.

If you are using an extension that you have generated a while ago, be sure to double check the vscode engine you have declared you support in your `package.json` i.e. bump that version.

Then run npm install again and that will bring you an updated version of `vscode.d.ts`, which will bring in all the new APIs that were added in the meantime.

**Comment by lucax88x** [comment]
Sorry, I did not know I had to upgrade the "engine", which would generate a new .d.ts, I had upgraded only the package version.

Thanks again.

**Comment by lucax88x** [comment]
For future reference, you all need to have engine at least from 1.22 for this api.

cheers @alexandrudima
