### ISSUE TITLE
Panel border hidden when in Notebook editor

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#147534]
Enable high contrast light mode. When the active editor is a normal editor, the panel has a distinct border. When it is a notebook, there's no border. When it's split, it's split.

<img width="1416" alt="image" src="https://user-images.githubusercontent.com/8586769/163652412-b6c6cef4-cffc-42f3-849a-51a5dd539dea.png">

**Comment by rebornix** [comment]
Looks like a zindex issue.

**Comment by rebornix** [comment]
It's related to zindex, but not the root cause. The grid system did a wrong math of title and editor group.

<img width="515" alt="image" src="https://user-images.githubusercontent.com/876920/166074858-81c18840-1fdd-4052-b54f-16930e4536e8.png">

In this screen shot, the `editor-group-container` has height `989px`. Its title is `58px` but the editor container is `932px`. It seems we didn't take top border's height into account.

**Comment by sbatten** [comment]
I see what @rebornix is talking about where we return 35px for the title tabs area height, but as a matter of testing, I hard-coded 36. This doesn't actually fix the issue, because the notebook is still rendered 1px too low and too far to the right. subtracting from its top and left value correctly aligned it with the editor grid.

**Comment by bpasero** [comment]
Yeah not good. I have a fix I think, we typically do not want explicit CSS borders but rather `::after` elements to draw the border that do not push the title control >35px.
