### ISSUE TITLE
Why is the following expression failing for TextMate grammars in VS Code?

### ISSUE THREAD

**Issue by mihaiconstantin** [microsoft/vscode#147574]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.66.2
- OS Version: Darwin arm64 21.4.0

Steps to Reproduce:

This is a cross-post from the [StackOverflow question here](https://stackoverflow.com/q/71895384/5252007) and I apologize for that, however, the comments I received point to a *peculiarity* in how VS Code handles regular expressions for TextMate grammars. I am trying to use VS Code's tokenization engine for grammar injections and I don't understand why some regular expressions fail. 

For example, suppose I have the following text.

```text
VS Code, TextMate grammars, and Oniguruma regular expressions. 
```

Then, I want to match `Oniguruma` using the following `regex` (i.e., [see demo](https://regex101.com/r/7svfsq/2)):

```regex
(?=and\s+(Oniguruma)\s+regular)
```

Based on the demo above, the regular expression seems to match (capture?) what I want (i.e., see below).

[![demo matching][1]][1]

However, when trying this in the context of VS Code grammars, it fails. More specifically, the `./syntaxes/some.test.injection.json` file contains:

```jsonc
{
    "scopeName": "some.test.injection",
    "injectionSelector": "L:text.html.markdown",
    "patterns": [
        { "include": "#test" }
    ],
    "repository": {
        "test": {
            "match": "(?=and\\s+(Oniguruma)\\s+regular)",
            "captures": {
                "1": { "name" : "some.test" }
            }
        }
    }
}
```

Then, in `package.json` I have:

```jsonc
{
    // ...
    "contributes": {
        "grammars": [
            {
                "scopeName": "some.test.injection",
                "path": "./syntaxes/some.test.injection.json",
                "injectTo": ["text.html.markdown"]
            }
        ]
    },
    // ...
}
```

Finally, the token color rule in `settings.json` looks like this:

```jsonc
{
    "editor.tokenColorCustomizations": {
        "textMateRules": [
            { "scope": "some.test", "settings": { "foreground": "#dfd43b" } },
        ]
    }
}
```

As you can see below, the token is not parsed:

[![enter image description here][2]][2]

However, the token gets parsed when I use the following `regex` (i.e., [see demo](https://regex101.com/r/7svfsq/3)) instead:

```regex
(?<=and\s)(Oniguruma)(?=\s+regular)
```

As seen during the inspection of the editor token and scopes:

[![enter image description here][3]][3]

From the [VS Code documentation](https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide#textmate-grammars) (i.e., see below) I understand that I need to use `Oniguruma` regular expressions:

> TextMate grammars rely on Oniguruma regular expressions and are typically written as a plist or JSON. You can find a good introduction to TextMate grammars here, and you can take a look at existing TextMate grammars to learn more about how they work.

Why does the first expression fail? Is it not a valid `Oniguruma` regular expression? I noticed the same with other expressions as well.

  [1]: https://i.stack.imgur.com/SbSWs.png
  [2]: https://i.stack.imgur.com/9BFrq.png
  [3]: https://i.stack.imgur.com/YFStL.png

**Comment by PieterBranderhorst** [comment]
I think the problem here may be a misunderstanding of the distinction between "capturing" and "matching". The parser is probably only looking for "matching" strings. Most uses of regular expressions are that way. Using "captured" strings, of which there can be many inside one regular expression, is mostly of interest to situation-specific code.

The first regular expression: `(?=and\s+(Oniguruma)\s+regular)` is purely a look-ahead expression. Because the entire expression is inside a (?-...). It checks for the existence of the entire expression after each position. It captures "Oniguruma" as the first and only "capture group" because "Onigurama" is itself inside parentheses. But it matches a null string, the non-existent character between "grammars, " and "and Oniguruma". I.e. it matches the (null) position which is followed by the look-ahead expression.

The second regular expression, `(?<=and\s)(Oniguruma)(?=\s+regular)` uses look-behind and look-ahead around the "(Oniguruma)" string. So as well as capturing "Oniguruma" it also matches "Onigurama". The returned match is "" in the first case, "Oniguruma" in the second case.

**Comment by hediet** [comment]
You can even see that the tool reports that the first regex `(?=and\s+(Oniguruma)\s+regular)` only matches a string of length 0.

Even though it might create matching groups (which I even didn't know was supported), we cannot create tokens out of it, as the regex doesn't consume that text.

**Comment by mihaiconstantin** [comment]
@PieterBranderhorst, @hediet, this makes sense. Thank you for clarifying.
