### ISSUE TITLE
Scrolling a notebook can be jarring and disorienting

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode#147527]
Scrolling through cells with the keyboard exhibits jarring behavior. I frequently find myself not sure what happened as I'm scrolling. When you scroll off the bottom or over the top of the cell, the caret should remain in a very similar place to where it was just at. 

An animated gif is needed here.
![Recording 2022-04-15 at 13 15 20](https://user-images.githubusercontent.com/11685408/163627850-a9d499d9-41f4-42d1-bf2f-48b0a4530d1c.gif)

Whereas Google Colab (and probably Jupyter) does this:
![Recording 2022-04-15 at 13 17 53](https://user-images.githubusercontent.com/11685408/163628038-0588b1e6-0bca-4dd3-a23d-3f3a042c57a7.gif)

**Comment by roblourens** [comment]
All I changed here was where the code cell is revealed when moving the cursor from one code cell editor to another. It should reveal the cell at the top or bottom of the viewport to try to keep the cursor close to the same place on the screen. There are other issues that might contribute to "jumpiness", can you give more details?

**Comment by lramos15** [comment]
Here's a gif where all I do is press <kbd>↑</kbd> and <kbd>↓</kbd>.
![Recording 2022-06-02 at 13 55 44](https://user-images.githubusercontent.com/4544166/171695920-60e6ec49-4192-48bc-b811-e36e621951e2.gif)

Two problems you can see
1. Even with the cursors at the start of the line when pressing down it doesn't always enter the cell at the start of the line. This can be seen at the very start of the gif
2. When scrolling up towards the end of the gif it appears to just skip some cells and jump as the cursor moves over them rather than enters the cell

Let me know if there's more info I can provide

**Comment by roblourens** [comment]
Ok yeah,

1. Seems like sometimes when moving from a markdown to code cell in this mode, the cursor goes to the first line but not the first column
2. When hitting a markdown cell, that cell is still revealed in the middle
3. Also noticed that we don't always reveal a line in a code cell editor if it's partially within the viewport

<img width="245" alt="image" src="https://user-images.githubusercontent.com/323878/171911088-c2c28880-af9e-4f4a-8e08-dd68ad22ad20.png">

**Comment by roblourens** [comment]
Yeah, I want to do this differently for moving from and to markdown cells in this mode. I'd forgot that uses a different command than with code cells. Will fix it up in debt week.
