### ISSUE TITLE
Only report as being offline if a request fails

### ISSUE THREAD

**Issue by Schamper** [microsoft/vscode#147510]
In response to https://github.com/microsoft/vscode/issues/141762, I think this error should only be raised when a request actually fails. I have a network setup where my host operating system reports it doesn't have network connectivity, but it can actually reach the internet just fine through a configured proxy.

I believe moving the online check to the `onerror` would result in a more accurate error flow: 
https://github.com/microsoft/vscode/blob/a9288be67bab4e9c4dbe62207f01fafc2bdaadcb/src/vs/base/parts/request/browser/request.ts#L12-L14
https://github.com/microsoft/vscode/blob/a9288be67bab4e9c4dbe62207f01fafc2bdaadcb/src/vs/base/parts/request/browser/request.ts#L30

Obligatory xkcd for my unique situation: https://xkcd.com/1172/

**Comment by sandy081** [comment]
As mentioned by @deepak1556 [here](https://github.com/microsoft/vscode/issues/141762#issuecomment-1025645738) I expect `navigator.onLine` shall provide right info whether VS Code can connect to internet or not. 

@deepak1556 Is it possible to get this info from the error instead of `navigator.onLine` ?
