### ISSUE TITLE
Suggestion: show the number of matches when running a search

### ISSUE THREAD

**Issue by ricmed205** [Microsoft/vscode#1476]

**Comment by bpasero** [comment]
@ricmed205 can you clarify what you want?

**Comment by ricmed205** [comment]
Yes! I wast just editing. When using the find in file feature (ctrl+f), show the number of matches when running a search.

**Comment by bpasero** [comment]
Ok thanks.

**Comment by bpasero** [comment]
@alexandrudima fyi

**Comment by rhbecker** [comment]
+1

... and along those same lines, it would be useful to see the "index" of the currently highlighted match; e.g. if there are 20 matches and the 14th is highlighted, I'd see 14/20, and find next / find previous would increment / decrement the index, respectively.

**Comment by alexandrudima** [comment]
@rhbecker I've just pushed a few days ago a match counter, but it doesn't show at this time X of Y, it just shows Y:

![image](https://cloud.githubusercontent.com/assets/5047891/12321305/a3bf564c-baad-11e5-9893-3b6c12c6d941.png)

**Comment by stevencl** [comment]
I would consider putting the label x of y next to the next and previous arrows rather than next to the search options. For example (without and with a border around the x of y label below)

![xofy](https://cloud.githubusercontent.com/assets/1704059/12322291/ffe2bd22-baaa-11e5-9d23-e09b51b95366.png)

Just to check though, what is the UX problem that we are trying to solve with this? Is it that without this, the user is unaware when they have reviewed all of the search results? Or is this solving another UX problem? That could help determine how important it is to show an x of y label.

How should search results be indexed? I think I would expect, if I wanted to be aware when I have reviewed all of the search results, that the result labeled 1 of y should be the first result found after the current insertion point, rather than the first item in the file.

**Comment by alexandrudima** [comment]
@stevencl Wow that looks so much better and makes a lot of sense to put them next to the prev/next buttons :+1:

How should the replace buttons be aligned then?:
![image](https://cloud.githubusercontent.com/assets/5047891/12322675/d6d6df0c-bab5-11e5-9778-ace0a5d29d76.png)

I personally would expect them to be always indexed from the top and then you'd start at "5 of 14" if that would be the next match. That is what Chrome's find does for example.

I am not sure what the underlying UX problem is, we have always been asked to show some numbers in there. Maybe @chrisdias and @ricmed205 can add more details.

**Comment by stevencl** [comment]
Starting at 5 of 14 would work too I think, that sounds good.
I would continue to align the replace buttons next to the right edge of the replace text box. Fortuitously, this also means that the replace button sits underneath the index and the replace all button sits underneath the count :-).
![xofyreplace](https://cloud.githubusercontent.com/assets/1704059/12322981/c2915e60-baaf-11e5-938e-433ae91f142c.png)

**Comment by ricmed205** [comment]
I don't think the X coordinate is necessary (highlighting the current match in the doc you can clearly see where it is). "5 of 50" just like Chrome is perfect -where the index starts at the top of the doc.

@stevencl :+1: UX
" Is it that without this, the user is unaware when they have reviewed all of the search results?" this

**Comment by rhbecker** [comment]
@alexandrudima 

Your responsiveness to our suggestions is very much appreciated!

@stevencl 

> what is the UX problem that we are trying to solve with this?

In addition to what's already been stated ...

#### I find y useful in determining whether to add more detail to my query.

I type "dog" on my way to "doggy". I'm lazy, so as soon as typing "dog" gets me to a small y, I'll start tabbing through results. Maybe I was inconsistent in my usage of the "gy" suffix, and it's handy to see that some of my matches are like "dogYears". But maybe "dog" didn't get my y small enough, because someone else used "doge" like 40 times, so I'll keep typing to distinguish, in order to get y smaller - to a quantity that's easier to deal with.

#### I find x useful as a [wayfinding](https://en.wikipedia.org/wiki/Wayfinding) mechanism.

I'm the sort of person who gets confused if I'm not starting at either the beginning or end of a document. If I start in the middle, I'll forget where in the middle, and won't know when I've arrived back at where I started. If I run a search and my x is closer to 1 than y, I'll scroll backward to get to 1 before I start dealing with my matches, while if my x is closer to y, I'll scroll forward to get to y (or will go one more "forward" to circle back to 1) before I start dealing with my matches.

The matches visualization in the scroll bar is nice, but it's also a bit ambiguous. I can't always tell at a glance whether I'm really on the first or last match.

If I'm reviewing / discussing a document with someone else, it's handy to say "go to the 8th match".

**Comment by alexandrudima** [comment]
Had some time today to work on this. Given the UX sketch, here's what I could come up with:

## A. variable width widget

![find-matches-variable](https://cloud.githubusercontent.com/assets/5047891/12514674/2d317b28-c12d-11e5-8b69-d9b71b5fb8a3.gif)

## B. fixed width widget, variable width label

![find-matches-variable-label](https://cloud.githubusercontent.com/assets/5047891/12514687/394dfba2-c12d-11e5-9c4d-33c84f101552.gif)


## C. fixed width widget, fixed width label

![find-matches-stable](https://cloud.githubusercontent.com/assets/5047891/12514698/421c3212-c12d-11e5-9f46-5f51c013b4aa.gif)

My personal favorite is C, since in A and B things float around, which draws attention for no good reason and it feels wierd.

@stevencl  Thoughts?

**Comment by stevencl** [comment]
C looks good I think.

Nice work!

**Comment by chrisdias** [comment]
:+1:

**Comment by ricmed205** [comment]
@alexandrudima awesome.

Have you tried tried placing the "X of X" inside the label (on the right part), replacing it with caps and regex options? the whole thing would be fixed width 

Similar to chrome

**Comment by stereokai** [comment]
+1 for C. At least until someone comes up with something aesthetically superior - because the quirky jumpiness of A and B is distractive and impairs the user experience. Great work @alexandrudima
