### ISSUE TITLE
Connection (account)

### ISSUE THREAD

**Issue by hanako-eo** [microsoft/vscode#147600]
When a try to click on the button account nothing open, I can't connect my github account 
and in the 
![image](https://user-images.githubusercontent.com/53426441/163722780-91b62a97-b79f-4425-834b-3dcbc62cd25f.png)

**Comment by hanako-eo** [comment]
My vscode version is 1.66.2 (normally the last version) and I'm on linux (manjaro with KDE) and I also issue with everything related to github in my vscode.

thank you for taking the time to read me

**Comment by TylerLeonhardt** [comment]
@hanako-eo you should have gotten a notification that leads you to the troubleshooting steps found here: https://code.visualstudio.com/docs/editor/settings-sync?msclkid=d1cb89a9bf2d11ecb8fb2c79796ea3ac#_troubleshooting-keychain-issues

If you install `gnome-keyring` on your OS, this should make it work for you. Keep an eye on this thread for alternatives to gnome-keyring: https://github.com/microsoft/vscode/issues/104319#issuecomment-1057588052

I'm gonna close this since it's a well-known issue that's documented and workarounds are given.
