### ISSUE TITLE
Refactor alpine stage to be built as part of LinuxServerDependencies pipeline

### ISSUE THREAD

**Issue by deepak1556** [microsoft/vscode#147681]
With https://github.com/microsoft/vscode/pull/147676 , [product-build-linux-server.yml](https://github.com/microsoft/vscode/blob/main/build/azure-pipelines/linux/product-build-linux-server.yml) has the necessary bits to build native modules with alpine container. `product-build-alpine.yml` can be extracted into `product-build-linux-server.yml` and `product-build-linux-client.yml` which would allow for lesser entry points.

**Comment by TylerLeonhardt** [comment]
How much would this impact the build time? I ask because `product-build-alpine.yml` is usually one of the first builds to be done so it doesn't impact the build time at all (just the compute amount I guess).

By moving what it is doing into these other places, I wonder if that will make the overall time higher which is something we try to avoid.

The added complexity may be worth the perf.

cc @joaomoreno

**Comment by deepak1556** [comment]
`LinuxServerDependencies` happens in parallel to the initial compile stage so this is before the current Alpine stage that happens as part of `Linux` stage, this would not add negatively to the perf but rather keep the same time since we are moving one parallel run from a stage to another earlier stage that will also run it in parallel. Additionally this would make one less config file. I suggest we make a branch and get actual numbers with the change to understand the impact better here.

<img width="1013" alt="Screenshot 2022-12-07 at 10 46 08 AM" src="https://user-images.githubusercontent.com/964386/206067852-b1658bb5-188b-413c-84c1-b7682b49c8fa.png">
