### ISSUE TITLE
editor.action.jumpToBracket does not match in plaintext scope

### ISSUE THREAD

**Issue by atombender** [Microsoft/vscode#14777]
- VSCode Version: 1.6.1

Steps to Reproduce:

Consider a plaintext file:

```
text (with parantheses).
```

If you navigate to one of the parantheses, `editor.action.jumpToBracket` does not work. Brackets are completely ignored there.

Similarly, here's a YAML file with a string:

```yaml
foo: "text (with parantheses)."
```

Same behaviour.

Is this because there's no grammar associated with the text block? If so, why? This works fine in Atom, where brackets seem to match irrespective of grammar. Bracket matching is useful no matter if the editor knows what the content is.

**Comment by alexandrudima** [comment]
Regarding yaml: in all languages, we ignore strings for bracket matching. e.g.:

```js
if (true) {
  return '}';
}
```

Regarding plain-text, indeed it has no brackets configuration out-of-the-box.

**Comment by atombender** [comment]
There are other related cases which I'm not sure you support, which might need separate issues to support. For example, in a Ruby string, strings need to be their own bracket scopes: An interpolated string such as `hello #{get_name(user)}` has two grammars. One is the string itself, where `#{}` must support bracket matching. The other is `get_name(user)`, which is embedded Ruby syntax. I notice that bracket matching is done for neither.  This also applies to any language that embeds contextual syntaxes.

**Comment by atombender** [comment]
...though I just realized that particular case could be a weakness in `vscode-ruby`, which lacks a lot of features.

**Comment by atombender** [comment]
@alexandrudima Thoughts?  It looks like VSCode has its own Ruby syntax built in. I don't know this plist format, so I'm not sure if the above issue is a weakness in that file.

**Comment by alexandrudima** [comment]
@atombender You are correct, bracket matching is not semantic. i.e. it is not computed via an AST. The only information we have in the editor that is low-hanging (i.e. easy to get into the editor) are scopes. These scopes come from the Text Mate grammars.

We've implemented bracket matching in such a way that we ignore brackets found in tokens that contain any of the scopes "regex", "comment" or "string", the reason being that those, mostly since they don't play a syntactical role (i.e. on all ASTs they would probably be a leaf), would probably cause invalid matches.

Of course, there are cases which might not be covered, such as `(` in `)` comments. Oftentimes, in natural language, in comments, parens are balanced. 

Another example is the one you have brought up, where strings can contain interpolated source code. If the grammar marks the entire string with a scope called "string", we will ignore everything from a bracket matching point of view. And yes, this could be corrected by the grammar such as not emitting the "string" scope for the interpolated section. But it is hard to ask a grammar that is shared between multiple editors to tweak its scopes because one editor (us) uses the scopes as hints for bracket matching.

IMHO, the way we implement bracket matching is a fair trade-off, and bracket matching works pretty well given the low hanging nature of its implementation. The only way to make it work 100% correctly, IMHO is to use an AST and not even attempt to bracket match if there is a syntactical (parse) error since the wrong brackets will be probably matched.

If you want to follow through and make brackets inside interpolated code inside ruby strings match, then we need to find the owner of that grammar. -- https://github.com/Microsoft/vscode/tree/master/extensions/ruby

It is (from the OSSREADME.json file) coming from https://github.com/textmate/ruby.tmbundle

You can create an issue on that repository or submit a PR that tackles this case.

**Comment by atombender** [comment]
Thanks for the explanation.

I think not matching brackets on syntactically invalid code (if I understand you correctly) might be a mistake without really solid, high-visibility support for showing mismatched brackets in the editor. I typically use bracket matching to find the _cause_ of mismatched brackets. Linters are typically bad at figuring out and visualizing that stuff.

I'm not super familiar with the Ruby syntax, but its interpolated string definition looks fine to me. It defines the contents of an embedded expression as Ruby. So every Ruby rule should work within that scope.
