### ISSUE TITLE
while upgrading vscode, Error: Cannot find module 'C:\Program Files\Microsoft VS Code\resources\app\out\cli.js'

### ISSUE THREAD

**Issue by tamusjroyce** [microsoft/vscode#147763]
Does this issue occur when all extensions are disabled?: Dunno

- VS Code Version: 1.66.0 -> 1.66.2
- OS Version: Windows 10
System-wide install

Steps to Reproduce:

1. Have a bunch of vscode's running
2. Maybe I installed a plugin while the upgrade is in progress?

Solution:  Re-install vscode

![image](https://user-images.githubusercontent.com/6413071/164232800-7410fbc1-3171-4e3d-86c3-51c3809aa5ca.png)
![image](https://user-images.githubusercontent.com/6413071/164232920-f4de08ee-d5bf-46dd-ba16-30949b3140cd.png)

note: `Help: Start Extension Bisect` results in a blank window as well

3rd or 4th time over a few years this has happened. Always during an upgrade.

This comes up a lot. And the work-around of reinstalled vscode is an easy fix. Most upgrades this works flawlessly. I will be sure to have just 1 vscode open when I upgrade next time.

**Comment by tamusjroyce** [comment]
Issue Type: <b>Bug</b>

I ran bisect while vscode failed installing. After reinstalling vscode, bicect opened & this is the output.
It said something about chis arcadia was the issue? mb an extension?

Reported here - https://github.com/microsoft/vscode/issues/147763

Extension version: 1.3.8
VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:46:01.075Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (2.76GB free)|
|Process Argv|--crash-reporter-id f198f09b-d0bf-4c3b-832a-d61863b2b492|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebugcf:30475217

```

</details>



Again. Feel free to close with no changes.

**Comment by joaomoreno** [comment]
Can you uninstall and reinstall VS Code?

**Comment by RussKie** [comment]
I get the same issue - VS Code fails to upgrade and essentially corrupts the existing install, leaving no option but to completely reinstall.

My workstation is running for weeks without restarts. I also have multiple instances of VS and Code running for days (if not weeks). I am almost convinced that Code tries to sneakily and _forcefully_ update itself in a background, and because I have running instances it fails and leaves me with a completely broken app.

**Comment by joaomoreno** [comment]
> I also have multiple instances of VS and Code running for days

Do they share the same user data dir?

**Comment by RussKie** [comment]
> Do they share the same user data dir?

No. I mentioned VS, because it often gets upset while updating itself and finding running Code instances (likely because of OmniSharp and dotnet). And that's when I sometimes find that Code install is corrupted (like happened yesterday).

**Comment by joaomoreno** [comment]
I meant: do the multiple instances of VS Code (not VS) share the same user data dir?

**Comment by RussKie** [comment]
I have a single installation of Code, installed via Chocolatey.

When I say "multiple instances" I mean multiple buttons on the task bar - because for me as a user these are different instances:
![image](https://user-images.githubusercontent.com/4403806/165869333-649dbdcc-2619-456d-b4b2-ed1115d5aebc.png)

As far as the "process instances" - looks like the Code is run in a single process:
![image](https://user-images.githubusercontent.com/4403806/165869446-e41a677c-4bd4-493c-b9b6-73347e449826.png)

I do, however, occasionally run Code as "admin", and that often coincides with running the non-elevated instance. Whether both of these processes use the same user data dir - I have no idea.
Though now thinking about it, it may be that the elevated process instance tries to update itself on exit, and that screws the running non-elevated instance up.

**Comment by RussKie** [comment]
Sounds like a good plan 👍

**Comment by tamusjroyce** [comment]
Admin mode wasn't in play for me. I think my situation was purely installing extensions while vscode was updating. Could disabling extensions while the update happens be a solution?

**Comment by joaomoreno** [comment]
@tamusjroyce I'd still be interested in whether re-installing the user install would also fix it for you. System level access isn't required for that one.

**Comment by benallred** [comment]
> > Though now thinking about it, it may be that the elevated process instance tries to update itself on exit, and that screws the running non-elevated instance up.
> 
> It's definitely possible. 🤔 We might want to disable update in sessions started as Admin, when in the user setup. What do you think?

@joaomoreno: Just thought I should mention that running VS Code as admin is what enabled my VS Code to actually update in a user setup. https://github.com/microsoft/vscode/issues/147408#issuecomment-1155987859
