### ISSUE TITLE
Could you add a plus on your tabs bar to create a new file?

### ISSUE THREAD

**Issue by soljohnston777** [Microsoft/vscode#14775]
Could you add a [+] icon next to the tabs to create  a new file?  It should be easy to do I would think, kind of like pressing ctrl+n.

**Comment by TheColorRed** [comment]
There is a new file button:

![new-file](https://cloud.githubusercontent.com/assets/1571806/19868909/15111d80-9f78-11e6-85b6-5368b346ccf8.png)

**Comment by rebornix** [comment]
Thanks @TheColorRed for the help, it's a good way to create a new file.

Besides, you can still double click on the empty space of the tab bar and a new file will be created as well.

**Comment by mika76** [comment]
@rebornix This is a good comment of double clicking on the empty space - but that only exists if there IS a tab bar which only exists if there is at least one file open. And the new file button that @TheColorRed mentioned is only there if a folder has been opened. So there is still a condition where you have an empty window and now you have to go into a menu... ugh 😷 

I suggest you go with the norm of having a new file tab button since everyone is quite used to that - it could be switched off for people who don't like it, but it would bring benefits to some people for sure...
