### ISSUE TITLE
Document how to debug extensionHost using other debuggers

### ISSUE THREAD

**Issue by cnshenj** [microsoft/vscode#147720]
I use VSCode and JetBrains Rider equally. When debugging JS/TS I prefer Rider because it gives me more information. Could you please document the following:
- How to start extensionHost outside of VSCode
- What debugging protocol does extensionHost support

I know it is kinda ironic that I develop/debug VSCode extension using Rider (while I don't have any intention to develop extensions for JetBrains IDEs because I don't use Java). But JetBrains's JS/TS experience is still better than VSCode.

**Comment by weinand** [comment]
Real extension debugging is only possible in VS Code because js-debug and VS Code have built-in knowledge about extension host specific workflows like "reload window".

But you can try to attach your debugger to the extension host process after launching VS Code with the `--inspect-extensions` and `--extensionDevelopmentPath` flags.

**Comment by cnshenj** [comment]
Thanks. What should I attach to? Is this the correct target to attach to (once I launch Code with the proper flags):

![image](https://user-images.githubusercontent.com/8441956/164113996-f635a529-b733-4118-9410-36cd9449d860.png)

**Comment by weinand** [comment]
pls see CLI:
![CleanShot 2022-04-20 at 01 02 24@2x](https://user-images.githubusercontent.com/1898161/164115222-d876d182-d671-4473-9a36-284eacf18329.png)
