### ISSUE TITLE
Github.dev -- Notebook Continue Working On... doesn't do anything.

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode#147870]
This may be somehow machine specific as I'm not able to reproduce it on a second Windows machine.

This repo is based on a "start-from-nothing-on-Windows" exercise, so maybe that has something to do with the inconsistency of being able to repro. 

0) On a new Windows machine, install Git, Python (from python.org), and then navigate to https://github.com/greazer/covid-19-data.
1) Press . to open github.dev.
2) Open SampleNbsAndScripts/myanalysis_plotly.ipynb.
3) Run the first cell
4) Choose to Continue Working On... > Clone repository...

Nothing at all happens.

**Comment by joyceerhl** [comment]
Do you have VS Code installed locally on your Windows machine? When you select 'Clone repository' we execute the registered protocol handler for `vscode://` URLs, which should open the VS Code app on your desktop machine. If there's no local VS Code install, there's no protocol handler, so we can't launch your local instance of VS Code.

Ideally we'd check if there's a local install of VS Code in the first place, but I'm not sure if we can do that from the browser.

**Comment by joyceerhl** [comment]
We delegate handling of the `vscode://` protocol url to the browser and it doesn't look like webpages can see what apps are installed (which makes sense):
 https://github.com/microsoft/vscode/blob/7e86d63f29392acc8c3710773ddf0549cf9833bc/src/vs/workbench/browser/window.ts#L188-L193

There's some hacky ways that VS Code could detect that the protocol handler wasn't successfully invoked e.g. after a timeout elapses, we could instead redirect the user to code.visualstudio.com/download, but this would be error prone. cc @bpasero have we discussed how to gracefully handle protocol urls when the handler hasn't been installed?

Also realizing that we should disable the Clone Locally and Open On Desktop option when viewing vscode.dev/github.dev on mobile... the user can still Continue Working On a Codespace since that's perfectly valid in mobile browsers

**Comment by bpasero** [comment]
I believe there is no way to detect if the link works or not but I remember that Office for web immediately shows a dialog when you select to open in Word for desktop:

![image](https://user-images.githubusercontent.com/900690/164610148-0bc4f253-5dba-40b0-a0d9-c6da632c177e.png)

We could do the same and show a custom dialog right when you select to open VSCode for desktop.

//cc @misolori @daviddossett

**Comment by daviddossett** [comment]
@bpasero is that dialog basically saying Word desktop isn't installed? Google translate isn't doing a great job with this one 😉

In any case, a dialog or notification seems reasonable here. I like the idea of nudging towards a download too.

**Comment by joyceerhl** [comment]
Just to call out that we would _always_ display this dialog, not just when VS Code isn't installed on desktop, when a `vscode://` uri is opened from within VS Code for the web. "All done. You can close this tab now. We tried opening VS Code on your computer." and options to "Install VS Code" and "Try again" (exact verbiage can be wordsmithed). From github.dev/vscode.dev we cannot know whether opening the desktop VS Code app succeeded, so we can't conditionally display this dialog.

The other dialog about "This site is trying to open ..." is displayed by the browser and we don't control the text there.

This means that users who already have VS Code installed will just happen to see a dialog, they don't have to acknowledge it. But for users who don't have VS Code installed, this dialog provides a path forward (currently they are stuck and there's no indication that anything went wrong).

**Comment by misolori** [comment]
The pattern of showing a screen/dialog that acts as a backup for when it's not available locally is very common in products that have both a web + desktop version. +1 to showing a dialog that allows them to try again or points to our download page.
