### ISSUE TITLE
Inspect Editor Tokens and Scopes isn't showing "Semantic token type" section

### ISSUE THREAD

**Issue by MetalSlime0** [microsoft/vscode#147907]
I'm adding semantic token types to my language server, and they're definitely causing tokens to change color in the expected places when I connect my server, but when I use the "Developer: Inspect Editor Tokens and Scopes" feature, no matter where I put the cursor it just shows the two sections that start with "language" and "textmate scopes" and doesn't show the "semantic token type" section as shown in https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide .

That guide says "The semantic token section is shown when a semantic token provider is available for the current language and when the current theme supports semantic highlighting." I assume these are both the case, or else I wouldn't be seeing the colors change when I connect my language server, but I am. I tried adding a "editor.semanticTokenColorCustomizations" section to my settings with "enabled": true for my current theme, but that doesn't seem to fix this.

Am I missing something?

**Comment by alexdima** [comment]
@MetalSlime0 From what you describe, it looks like you're doing everything correctly. Implementing semantic tokens is quite tricky, given their number encoded representation, custom semantic token types, etc. Most problems in this area were caused by some sort of invalid result. Could you provide a sample that shows the problem, or maybe you could add logging to the values you are returning and then extend the https://github.com/microsoft/vscode-extension-samples/tree/main/semantic-tokens-sample to help reproduce the problem.

**Comment by MetalSlime0** [comment]
Gah, it's working now. I haven't even changed my semantic tokens code since I posted this and I have no idea what else I could have changed that could have been relevant. Sorry to waste your time. I'll update if I find a repro.
