### ISSUE TITLE
Feature request: Debug Console command history suggestions in chronolological order instead of alphabetical order

### ISSUE THREAD

**Issue by ssavary** [microsoft/vscode#148072]
When I start to type a command in the Debug Console, it suggests matching entries from my command history, which is great. However, the suggestions are presented in alphabetical order, instead of chronological order, which would be more intuitive. Most of the time, the debug console history is full of mistyped commands or iterations over the same function calls, and alphabetical order does not make sense here. Moreover, since the display of the preview of the command is shortened in the suggestion list, it is difficult (or impossible) to distinguish between many similar-looking commands. Having them listed from the newest to the oldest would clearly improve usability.

**Comment by roblourens** [comment]
I don't have total control over the order of the filtered contents of the suggest widget currently, so we can't put history in a separate section and set the order. Because of this I find console history to be not that useful and I generally disable it: `"debug.console.historySuggestions": false`. 

However, it seems when commands are otherwise a tie in fuzzy filtering, I can change the order of the tie-breaking. For example, I evaluated in this order

1. `evaluated1`
2. `evaluated2`
3. `evaluated3`
4. `zEvaluated3`

the first 3 that tie are sorted in recency order but the last is forced to the bottom due to being a worse match. Does this help at all?


<img width="173" alt="image" src="https://user-images.githubusercontent.com/323878/200060513-943aa9b5-4945-4280-90c3-4c5181ca45ca.png">

If not what you had in mind, maybe give an example
