### ISSUE TITLE
Recently opened workspaces is not shown in all windows

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#148155]
Testing #148063

I have opened couple of remote repositories. In the window where remote repository is opened, picker from remote indicator shows recently opened repositories. Open a window (empty or local folder), picker from remote indicator does not show recently opened repositories

<img width="1507" alt="image" src="https://user-images.githubusercontent.com/10746682/165317442-a4c9902f-3001-467e-9e5b-9f1cf64b8115.png">

**Comment by joyceerhl** [comment]
This works for me with the latest pre-release I just published. It wouldn't have worked in an earlier version of Remote Repos--would you mind ensuring that you are on the latest of everything and try again please?
 
![image](https://user-images.githubusercontent.com/30305945/165328489-18c84823-f80d-404f-af01-82196823a37a.png)

**Comment by sandy081** [comment]
I can still repro it with this version

<img width="145" alt="image" src="https://user-images.githubusercontent.com/10746682/165436120-23723b4a-df63-46bd-910f-693fd6f439f8.png">

BTW I am testing it on Desktop

**Comment by joyceerhl** [comment]
This happens because the built-in GitHub extension already registers a remote source provider, and to avoid duplicates, I avoided registering a GitHub remote source provider in RemoteHub if the GitHub extension was active. However, since that provider was also providing the recent sources, this led to desktop having the builtin GitHub extension's remote source provider (which of course doesn't know anything about recent sources).

I think the recent sources should continue to be provided by Remote Repositories, since that isn't something the builtin GitHub extension knows about, but we should deduplicate the GitHub remote source provider by bringing the builtin GitHub extension's remote source provider up to parity with the Remote Repositories provider, and then removing the latter. This would require a change in the git-base extension to allow a provider to contribute recent sources but not implement `getSources`, and this provider would also not get a quickpick item in the list of remote sources. This might require us to introduce the notion of a `RecentRemoteProvider` after all. What do you think @lszomoru?
