### ISSUE TITLE
Find references should work on link

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#148119]
Testing #147730

When I have a markdown link referencing another markdown file, I would have expected "Find References" to also work from the editor when my mouse is inside the link path.

**Comment by mjbvz** [comment]
Can you please share some markdown code that demonstrates this issue? This should work but I need more detailed repo steps to confirm

**Comment by bpasero** [comment]
![Recording 2022-05-01 at 07 51 51](https://user-images.githubusercontent.com/900690/166134035-f299c086-ba62-4be2-bdd7-2401ef9297d6.gif)

**Comment by mjbvz** [comment]
Thanks. In this case, there is just a single reference to the file (you can confirm this by running `find all references` on it instead of `go to references`)

This means that you are already on the reference, so `go to references` appears to do nothing

/cc @jrieken If we want to make this behavior more clear in core
