### ISSUE TITLE
Settings editor funnel button: How does it source extensions?

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode#148192]
Testing #147935

- Open Settings editor, select funnel -> `Extension ID...`
- See several extension suggestions:

![image](https://user-images.githubusercontent.com/25310137/165361765-459b6378-495e-430b-8091-ae53f12e1492.png)

- I want to view Remote-Containers settings, so I start searching `containers`
- No results, so I'd need to find and paste the Remote-Containers ID myself

![image](https://user-images.githubusercontent.com/25310137/165362031-c89abe0c-cbe2-4e4e-bd20-ab452752ec98.png)

How do these suggestions get populated? I thought it would've been all extensions installed, or all installed extensions with settings, but that doesn't appear to be the case (in the latter scenario, there are extensions populated that don't have any settings to show).

**Comment by rzhao271** [comment]
Verification steps:
In the Settings editor, press the funnel button on the right side of the search widget, and then select the "Extensions" option. The list of extensions that show up should include both built-in extensions such as Emmet, and user-installed extensions such as Remote Containers. Note that the extension IDs will show instead of the extension names themselves.

**Comment by bamurtaugh** [comment]
LGTM, thanks @rzhao271!
