### ISSUE TITLE
Extension pre-release vs stable-release is confusing to me

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#148117]
In my day to day use and esp. now that I am doing testing, I find how we distinguish pre-release from stable-release extensions confusing.

To clarify: we show a badge to the left when an extension can be installed as pre-release and a badge to the right when it is pre-release installed:

![image](https://user-images.githubusercontent.com/900690/165257266-b7116351-4422-49d3-a524-c285b1afe5e5.png)

![image](https://user-images.githubusercontent.com/900690/165257278-41c57a61-c74a-4adf-aaa0-3e4897df102e.png)

In my mental model - given VSCode and insiders - I map a blue logo to stable and a green logo to insiders. Maybe we can use something similar for extensions as well?

//cc @isidorn

**Comment by isidorn** [comment]
This is good feedback
When you compare it like that side by side I think the top left green thing deserves to be in both cases.
And maybe in the first case it is blue.

**Comment by bpasero** [comment]
Actually why do I need this badge on the left at all when the button strongly indicates I can install pre-release?

![image](https://user-images.githubusercontent.com/900690/165258108-4117ba4a-19f7-4a2c-99c6-079518450a2a.png)

Here is my suggestion:
- remove the left hand badge
- remove the right hand badge
- clearly spell out "Pre-release" as label next to the blue mark

🚀

**Comment by isidorn** [comment]
@bpasero overall I like your suggestion since it simplifies things and the "Install Pre-Release" button is there by default. However pre-release next to the author name feels like it does not belong there.

**Comment by bpasero** [comment]
Right, my point I guess is to have it spelled out somewhere and not convey the info just through a badge or icon.

**Comment by sandy081** [comment]
> Actually why do I need this badge on the left at all when the button strongly indicates I can install pre-release?

This is true for not installed extensions. But what about installed extensions? How to indicate that an extension has pre-release or not?

**Comment by gjsjohnmurray** [comment]
@bpasero look out for extra confusion if you ever need to install pre-release extensions direct from VSIX (e.g. if you need to use proposed APIs in them).

See #141869 and the discussion in the issue it was spun off from.

**Comment by sandy081** [comment]
> have we seen similar feedback, overall, from other users?

Not yet.

Badge on the left is to indicate that the extension has a pre-release version, otherwise stable user does not know unless user clicks on the Install dropdown. If extension is already installed, user has to open extension editor or context menu to know there is a pre-release.

> Show the same button to switch to pre-release?

This adds more noise to the UI. This button is more annoying to me if I opted to install release version.

> I find how we distinguish pre-release from stable-release extensions confusing.

Indicator on the right is meant to distinguish if an extension is running pre-release or not. 

Summarising the states we represent:

1. VS Code Stable: Extension has Pre-release

<img width="356" alt="image" src="https://user-images.githubusercontent.com/10746682/165438341-bc042ad8-ae57-4d60-bb46-92a5fd93761c.png">

2. VS Code Insider: Extension has Pre-release

<img width="371" alt="image" src="https://user-images.githubusercontent.com/10746682/165438401-98ce2e44-8723-4cf1-862a-5185c406db0d.png">

3. Extension has Pre-release but release version is installed

<img width="364" alt="image" src="https://user-images.githubusercontent.com/10746682/165463518-2fd95a03-001e-483f-8b1e-ecec24c56329.png">

4. Extension has Pre-release and pre-release is installed

<img width="357" alt="image" src="https://user-images.githubusercontent.com/10746682/165463656-a4a0e03b-83f9-40cd-af94-e66c1c05a10d.png">

- Badge on the left indicates that the extension has a pre-release
- Indicator on the right indicates that extension is running pre-release

How about having badge on the left always - indicating that this extension has pre-release, even though the pre-release is installed?

**Comment by bpasero** [comment]
I was not even aware that we show different buttons depending on being in Code stable vs insiders.

I like the idea of reducing this to 1 badge that is always at the same location, but then we are at risk imho of subtle differences, because if the badge shows it can mean both that pre-release is installed as well as that pre-release is available.

As such, why not just:
* drop the badge and purely rely on the install button for picking pre-release
* show the badge exclusively for when you have pre-release installed

**Comment by sandy081** [comment]
It seems, I am not clear - I do not want to reduce or remove any. I am recommending to have the badge on the left always for an extension that has pre-release and the indicator on the right is shown only when pre-release version is installed. This was how it was before.

> drop the badge and purely rely on the install button for picking pre-release

This might be unintuitive because user has to click on the dropdown to see if the extension has a pre-release or not. 

> show the badge exclusively for when you have pre-release installed

The indicator on the right is meant for this purpose.

**Comment by bpasero** [comment]
Fair enough, I think that is worth a try 👍

**Comment by gjsjohnmurray** [comment]
I wish these badges showed a brief explanatory tooltip when hovered over.

**Comment by isidorn** [comment]
@gjsjohnmurray there is no tooltip per html element in the extensions view, only one big tooltip for the whole tree element.

I agree with the proposed change:
>to have the badge on the left always for an extension that has pre-release and the indicator on the right is shown only when pre-release version is installed

IMHO indicator on the might be too opaque. It either needs to be stronger or to be changed with text if possible.

**Comment by lychung7** [comment]
Yes, on the single tooltip for the entire element we show whether the prerelease version is installed or available. 
I agree the icon itself on the right is a bit subtle especially as I'm scrolling through my list of installed extensions. There have been past explorations of including text with the icon. Maybe we could show icon + 'pre-release' on the right side when the sidebar is wide enough to fit it, and as the view gets narrower we only show the icon.

**Comment by bpasero** [comment]
So this is actually a nice badge:

![image](https://user-images.githubusercontent.com/900690/165691613-a54975a5-09c9-489a-9f8c-0d1d9d6127cf.png)

**Comment by isidorn** [comment]
Yeah but in the Extension Details View we have more space. I am not sure if that would fit in the viewlet. We could be smart - when there is not enough space “Pre-Release“ text gets hidden and only the icon is left. We might be able to do that using `flex`.

**Comment by sandy081** [comment]
Even if it fits in the viewlet, I would think this adds more noise in the UI.

![image](https://user-images.githubusercontent.com/10746682/166449695-42d8c691-da36-43f9-bc81-348ce723a115.png)

I think the root problem here is that the badge on the left is confused between whether extension is a pre-release version or extension has a pre-release version. I have tried following to make it clear:

![image](https://user-images.githubusercontent.com/10746682/166477527-a8da2d24-0dff-41e6-876f-416a29a8d13f.png)

- I have removed the indicator on the right
- Badge on the left indicates that this is a pre-release version
- If a release extension is installed and it has a pre-release version, added an icon action before gear icon for switching to pre-release version

Feedback?

**Comment by misolori** [comment]
@sandy081 can you show an example with all of the various states?

**Comment by sandy081** [comment]
1. VS Code Stable: Extension has Pre-release

<img width="356" alt="image" src="https://user-images.githubusercontent.com/10746682/166517807-0a0b589c-8409-4257-b092-3ac72f6e9c57.png">

2. VS Code Insider: Extension has Pre-release

<img width="360" alt="image" src="https://user-images.githubusercontent.com/10746682/166517574-10578025-006a-4009-bfaf-26969d79178e.png">

3. Extension has Pre-release and pre-release is installed

<img width="355" alt="image" src="https://user-images.githubusercontent.com/10746682/166517634-5800cffb-64bd-41b0-ace2-2dc53000935d.png">

4. Extension has Pre-release but release version is installed

<img width="359" alt="image" src="https://user-images.githubusercontent.com/10746682/166517708-68af9127-b719-4c25-92ae-291ff7523283.png">

**Comment by sandy081** [comment]
@isidorn @lychung7 @misolori @bpasero let me know what you think about above changes?

**Comment by isidorn** [comment]
@sandy081 great work. I like this changes and they make sense to me.
Once they are in insiders I can try them out and provide more feedback.
