### ISSUE TITLE
Some `files.watcherExclude` patterns cause flat watcher to not include certain events

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#148177]
Testing #147703

You can see here that logs only happen from the extension when it's not an excluded file.

https://user-images.githubusercontent.com/29464607/165354327-a8a98ace-803a-4917-8dfd-a76ed363a993.mov

**Comment by meganrogge** [comment]
```

const writeEmitter = new vscode.EventEmitter<string>();
	const watcher = vscode.workspace.createFileSystemWatcher(new vscode.RelativePattern(vscode.workspace.workspaceFolders![0], '*.ts'));
		watcher.onDidChange(uri => {
			console.log('changed');
			console.log(uri.toString());
		});
		watcher.onDidCreate(uri => {
			console.log('created');
			console.log(uri.toString());
		});
		watcher.onDidDelete(uri => {
			console.log('deleted');
			console.log(uri.toString());
		});
```

**Comment by meganrogge** [comment]
![Screen Shot 2022-04-26 at 11 13 36 AM](https://user-images.githubusercontent.com/29464607/165365240-145603e1-1b36-4b67-a120-4be701454c6b.png)

**Comment by bpasero** [comment]
This was a good catch in the end but the fix is a bit more involved: when dealing with patterns that are neither an absolute path, nor have a leading `**`, we failed to convert them to patterns that match on absolute paths, because that is what file events emit.

Added a new method to convert these relative patterns:

https://github.com/microsoft/vscode/blob/2d9dccaddd7b1ec2f63e5edd172572f94b9d9866/src/vs/platform/files/common/watcher.ts#L284-L302

**Comment by meganrogge** [comment]
I am still not seeing events for `hi.ts` when that's included in the files exclude. Do I have to do something to pull in this change? @bpasero

**Comment by bpasero** [comment]
It works fine for me with todays insider, see video proof:
![Recording 2022-04-29 at 17 49 59](https://user-images.githubusercontent.com/900690/165979620-b315f180-1897-47c8-af74-2b8827987eac.gif)

**Comment by meganrogge** [comment]
yes I hadn't updated. working for me 👍🏼
