### ISSUE TITLE
Provide shell fallbacks for common patterns used to disable shell

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#14817]
See https://github.com/Microsoft/vscode/issues/9087#issuecomment-257626140

A fallback may make sense when shells like `/bin/false`, `/sbin/nologin`, `/usr/sbin/nologin`, etc. are detected. For the actual fallback probably reading `/etc/shells` and grabbing `/bin/bash` if it exists otherwise using the first (or /bin/sh`) in the list.

**Comment by kaiwood** [comment]
Hmm, as far as I understood the problem in #9087 the common solution for this use case is introducing a simple setting where one can set a custom shell. Every configurable terminal emulator on *nix systems I know has some kind of "Execute this program instead of the login shell" setting. 

That would be useful if someone wants to run a different shell just for the sake of running a different one too

I didn't check how xterm.js  or Code handles the shell spawn, but if I currently start the Editor via `SHELL="/bin/bash" code .` it uses Bash anyways - although /bin/zsh is my login shell. Might be worth an "effort-easy" label :)

**Comment by Tyriar** [comment]
The setting already exists in your settings.json as `terminal.integrated.shell.(platform)`, this was just a suggestion from #9087 but I think the improved error message for that should give enough context for how to fix.
