### ISSUE TITLE
No confirmation dialog when selecting "Quit" from the context menu from macOS dock when no windows open

### ISSUE THREAD

**Issue by tanhakabir** [microsoft/vscode#148209]
Testing #147704

> ensure this works even when no window is opened by closing the last window without quitting the app and then selecting "Quit" from the main menu

Did not see any confirmation dialog when I selected "Quit" from the context menu from the dock when I had no VS Code windows open. Not sure if interpreted the expectation properly though and if the behavior I saw was expected.

**Comment by bpasero** [comment]
Yeah thanks for testing thoroughly, unfortunately I could not find an easy way to show a dialog then because the "Quit" action is different from "File > Quit" in that we do not have full control over how the application quits in that case. That "Quit" action is provided by the OS.

I would think that we can probably leave this behaviour as is because quit from the dock is an operation that needs at least 2 clicks (not like using a keybinding by accident where chances are higher to hit it by accident).

If there is overwhelming feedback to address this, I will reconsider.

**Comment by bpasero** [comment]
Actually I opened https://github.com/electron/electron/issues/33939 because I feel this is something Electron could do better.
