### ISSUE TITLE
Figuring out how to leave multi line comments.

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/vscode#148214]
Testing #148048

I was trying to drag the + sign to select the lines I wanted to comment on.
![image](https://user-images.githubusercontent.com/3840081/165387174-65d37cff-4649-431b-b208-00564a933260.png)

I later realized that you had to select the text you wanted to comment on to get multi-line comments. Why not support both? If yo drag the + sign I would expect it to just select the whole line.

**Comment by IllusionMH** [comment]
Had similar experience - tried to drag along gutter decoration - similar how it's done on GitHub - no luck.

Then tried to do multiline selection, open Command Palette and search for "Comment" - no luck GHPR extension only provides commands to collapse/expand comments.

---

This was a bit confusing for me because selection and click on + on GitHub - adds single line comment while drag of + required to do multiline. 
Disclaimer: GH is only place where I've added multiline comments before this
