### ISSUE TITLE
Add folder icon for Seti icon theme

### ISSUE THREAD

**Issue by svipas** [microsoft/vscode#148270]
Please, add folder icon for Seti icon theme with 2 states (open & closed)

As an example:
- closed state: <img width="43" alt="Screenshot 2022-04-27 at 05 10 27 PM" src="https://user-images.githubusercontent.com/10441177/165538219-1f0cf515-5074-4bf7-a5df-bfca9e758ec2.png">
- open state: <img width="41" alt="Screenshot 2022-04-27 at 05 10 46 PM" src="https://user-images.githubusercontent.com/10441177/165538273-f7d07e73-75e5-4d59-947e-354c3b8e11c5.png">
 
I'm not saying it should look like above, but it is an example how different folder state could look like. In my opinion, that's the one missing piece in Seti icon theme is folder icon.

**Comment by aeschli** [comment]
The built-in Seti theme uses twisties at the places of folder icons. That's one of the characteristics of it and we don't want to change that.
However, new icon themes can easly be created and loaded from the Marketplace.

E.g. https://marketplace.visualstudio.com/items?itemName=qinjia.seti-icons looks like what you want.

Closing as we don't want to change  built-in Seti theme as suggested.

**Comment by noinkling** [comment]
@aeschli Unfortunately the alternative seti-icons extension that you linked hasn't had an update in a long time. While it does have folder icons, it has some other undesirable differences compared to the built-in version - for instance the icons are blurrier and it doesn't give .test.js files a different colour from other .js files. In general I'd much rather use the version that's built-in and maintained, so it's a very unfortunate tradeoff.

Looking at the original repo from where the built-in version is derived, there are folder icons in the (Atom) screenshots:

![](https://raw.githubusercontent.com/jesseweed/seti-ui/master/screenshot-search.png)

So calling no folder icons a "characteristic" seems pretty arbitrary/subjective.

Maybe it would be possible to make an option so that users can choose what they like?

**Comment by aeschli** [comment]
Sorry, we have not plans for adding customisation to the built-in themes.
Please file an issue of help the author of the other theme.
