### ISSUE TITLE
What should happen when on a read-only filesystem?

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#148304]
Testing #147706

using an untitled html file:
```html
<a href="/doesnotexit.txt"></a>
```
![image](https://user-images.githubusercontent.com/2644648/165597473-dca59ba5-69fa-4937-93ee-073ca63080db.png)

I think this makes sense because it's trying to save to the root of the file system at `/doesnotexist.txt` but I wanted to open this anyway just in case because it throws that error and then closes the editor in the background which is maybe not as consistent of this new "error when not exist" flow.

**Comment by bpasero** [comment]
We have no real way to figure out if the

**Comment by bpasero** [comment]
From `no` to `aye` in 5 minutes!

**Comment by bpasero** [comment]
Oh, had to revert, not easy to fix: as part of the action flow, the action may decide to open another editor (that actually happens as part of the create file flow). If we await that action, we fail to open that editor because we still think we are in an error case.

So I am actually proceeding in the background to open the place holder without waiting for the action to finish and thus I cannot detect whether the action results in an error or not. As such, I simply always consider the action to have succeeded in a way that I do not need to show the place holder:

https://github.com/microsoft/vscode/blob/0290856f68184955843fd706eecdfe840f4553ed/src/vs/workbench/browser/parts/editor/editorPanes.ts#L189-L194
