### ISSUE TITLE
Codelens Showing while editor.codeLens is set to false

### ISSUE THREAD

**Issue by jvcmarcenes** [microsoft/vscode#148380]
Does this issue occur when all extensions are disabled?: Yes (The extension for the given language server needs to be enabled, however. The issue doesn't seem to be with the language server extension since the issue persists across different languages)

- VS Code Version: 1.66.2
- OS Version: Windows 11 21H2

Steps to Reproduce:

1. Open vscode on a file that would have code lens
2. Disable code lens

**Comment by jrieken** [comment]
> Disable code lens

How do you do that? Do you have a workspace setting that enables this?

**Comment by jvcmarcenes** [comment]
> How do you do that? Do you have a workspace setting that enables this?

I've set the setting `editor.codeLens` to `false`, as is said in the issue title

**Comment by jrieken** [comment]
There is user settings _and_ workspace settings. The latter are overrule the former. So: How do you do that? Do you have a workspace setting that enables this?

**Comment by jvcmarcenes** [comment]
> There is user settings _and_ workspace settings. The latter are overrule the former. So: How do you do that? Do you have a workspace setting that enables this?

That's akward, the code lens just showed up without me having changed any settings. I've checked the workspace settings and code lens was enabled, the issue is solved.

**Comment by jvcmarcenes** [comment]
> There is user settings _and_ workspace settings. The latter are overrule the former. So: How do you do that? Do you have a workspace setting that enables this?

Both are set to false, code lens is still showing

**Comment by jrieken** [comment]
It looks like the issue is caused by one of your installed extensions. All extensions execute together on a single nodejs process, so in order to narrow down the possible problematic extension, please try the following:
* run `F1 > Help: Start Extension Bisect`
* (this will restart VS Code with half of your extensions disabled)
* try to do the steps which reproduce the problem
* if the problem reproduces, click "This is bad" (this narrows down the problematic extension to the half which was enabled)
* if the problem does not reproduce, click "Good now" (this narrows down the problematic extension to the half which was disabled)
* these steps will repeat until the problematic extension is found

| initial | step | final |
|---|---|---|
| ![image](https://user-images.githubusercontent.com/5047891/101918658-e9170f80-3bc9-11eb-9977-857baa291937.png) | ![image](https://user-images.githubusercontent.com/5047891/101918683-ef0cf080-3bc9-11eb-9f9e-98b0177991b2.png) | ![image](https://user-images.githubusercontent.com/5047891/101918706-f502d180-3bc9-11eb-8c86-e56355958bd4.png) |

**Comment by jvcmarcenes** [comment]
I've done this procedure, indepedent of the language it claim that the extension providing the language server is the one causing the issue (I believe this is because without the langauge server there wouldn't be the data for the code lens). I've actually said this in the issue.

I mostly use rust, and the rust-analyzer extension (and it's specific code lens setting is also disabled). But code lens also shows up with different languages such as Java. Therefore I believe this is an issue from vscode and not from an extension.

**Comment by jvcmarcenes** [comment]
Update: Turns out I was confused thinking what I was looking at was _code lens_, turns out it was actually _inlay hints_. (In my defense, I couldn't tell the difference between those names just by reading them, they're too similar).

Sorry for the needless issue (also, weird that inlay hints showed out of nowhere considering I've been using vscode without seeing it forever).
