### ISSUE TITLE
matches (x of n) info is not shown

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#148335]
Ref: https://github.com/microsoft/vscode/issues/147685

1. Change the terminal scrollback to 30'000
2. execute `for i in {0..20000}; do echo "absdj bkwefkl wqdoqwdjadcnbyx ncbahjsgf7zr92834rjpowef0sdjfisdnjfbsjdf"; done`
3. Search for abs

<img width="917" alt="image" src="https://user-images.githubusercontent.com/10746682/165709709-cd4360c3-5965-45f8-a07d-c3e0a0711f6a.png">

**Comment by meganrogge** [comment]
This is by design because finding out the count when the result is large is very slow. We plan to revamp search such that decorations are drawn to the canvas rather than inserted to the dom so will be able to report the count and draw decorations for a large volume of search results without tanking performance.
