### ISSUE TITLE
C# syntax error hints disappear after a few seconds

### ISSUE THREAD

**Issue by zeyangl** [Microsoft/vscode#14844]
- VSCode Version: 1.6.1
- OS Version: macOS 10.11.6 (15G1108

C# syntax error hint disappears after a few seconds.

Steps to Reproduce:

1. make a C# file
2. install C# plugin (1.4.1)
3. write a simple C# class
4. intentionally cause a syntax error.
5. observe red hints on the syntax error.
6. wait a couple of seconds, error hints disappear.

I expect this to be a VSCode issue instead of OmniSharp, since the syntax hints did show up correctly, only to disappear in a couple of seconds.

**Comment by rebornix** [comment]
@zeyangl I'll say let's start with OmniSharp as we don't know yet whether OmniSharp regards it as no longer an error after `a couple of seconds`.

**Comment by zeyangl** [comment]
It appears to be fixed in 1.7.1 release. OmniSharp version remains the same though, so probably a nice side effect of some other fix in vscode.

**Comment by marcelush** [comment]
I am still having same issue on **Ubuntu 14.04,**  insiders and stable Version **1.7.1.**
Maybe is because of big projects, the problem doesn't occur when testing a small project.

Initially i was suspecting the auto save feature to have something to do about it, but i tested with all possible options.

Warnings and info remain, but errors disappear about 1.5 seconds after file change (saved or not).

**Comment by aeschli** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#883

**Comment by HawkenKing** [comment]
I get this same issue on mac, using with unity
