### ISSUE TITLE
multi debug: productise 'composite' launch config

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#14842]
TBD

related issues:
https://github.com/Microsoft/vscode/issues/14335
https://github.com/Microsoft/vscode/issues/14481
https://github.com/Microsoft/vscode/issues/14486

**Comment by isidorn** [comment]
I think we should also consider putting `'composites'` as an additional secition as a sibbling to `'configurations'` in `launch.json`. Since doing it the current way we might hit some limitations because required fields for configuraitons are not required for composites and in essence they are different.

I do not plan to work on composites this week so we can also discuss on Monday once I am back in Zh :)

**Comment by weinand** [comment]
In a ZRH team discussion concerns were raised that 'composite' launch configs have too much overlap with 'tasks' and we decided not to release our implementation but to wait for task support for this.

So this feature is blocked now.

/cc @kieferrm @egamma @dbaeumer

**Comment by dbaeumer** [comment]
I think task is not the right place to solve this either. I do have similar requests. To make this scripting approach work I think we need the following :

- a scripting interface to VS Code (I have these requests in tasks since people want to talk back to VS Code from their tasks)
- if we want to use the OS scripts engines we need to have executables to talk to VS Code
- we could also say scripting happens in JS. Then we would provide a node module which we automatically inject into the started node engine to allow a script to talk back to VS Code.

**Comment by joshgav** [comment]
I just set myself up to step debug through Node.js server-side code and browser-side JavaScript from the same VS Code session and smiled in wonderment as a single request hit breakpoints on both sides in succession. I'd like to begin attaching to multiple Node processes at once too so I can follow requests through multiple services. So I was sad to find this no longer works in v1.8, and to discover this issue.

Multi-target takes step debugging to what might be the new normal in our highly-componentized microservices world, where work often traverses process and system boundaries. It would be ideal to focus on the experience specifically for step debugging, independently of Tasks work. Please reconsider including this as a debugging-specific feature. Thanks!

/cc @auchenberg

**Comment by weinand** [comment]
Multi session debugging is in the product since last milestone (1.7) and it will stay in VS Code.
 
The only thing that has changed is the UI.
 
In the October release we had no real UI and the only way to launch multiple sessions was by using a ‘composite launch configuration’.
This was a simple hack that we introduced to surface multi session debugging and make it testable.
 
In the November milestone we’ve added real UI.
With this a user can launch a new session even if other debug sessions are still running.
As soon as a second session starts the UI changes and shows multiple sessions in the CALL STACK view and the debug action bar:

![2016-11-23_12-46-58](https://cloud.githubusercontent.com/assets/1898161/20593064/24a7c642-b231-11e6-8648-890a6a889b2b.png)

This multi session UI will ship in November (and it is already available in the Insiders release).

The 'composite' launch config is considered a secondary UI and it will be made available in the November release after some polish.

**Comment by joshgav** [comment]
Thanks for the clarification @weinand! And thanks for this great feature!

**Comment by auchenberg** [comment]
Great. I've hereby updated my blog post with the new launch config. https://medium.com/@auchenberg/introducing-simultaneous-nirvana-javascript-debugging-for-node-js-and-chrome-in-vs-code-d898a4011ab1#.bgkqbh54p

**Comment by isidorn** [comment]
@auchenberg great - thanks!

**Comment by weinand** [comment]
@auchenberg thanks for updating. Just be aware that the new syntax is only available in the Insiders release. The Stable November release will become available in about two weeks from now.

**Comment by auchenberg** [comment]
@weinand Good point!

**Comment by darkyen** [comment]
Say I have my server and client both compiling using webpack in watch mode. In this scenario I'll need two separate tasks. If I do this right now it throws me the error 

> There is a task server running. Can not run pre launch task client.

Will this be handled gracefully in future?

**Comment by weinand** [comment]
@dbaeumer could you please comment?

**Comment by dbaeumer** [comment]
Currently the task framework can only execute one task at the time. Since the watching task takes the slot the prelaunch task can't be started. This is a known limitation. We are working on supporting more than one task to run in parallel.

**Comment by darkyen** [comment]
Thanks for your reply! 


I work around the problem to a certain extent by creating 3 npm tasks, 2 standalone and 1 merged. And then 4 launch configs [1 specifically for Server Client] basically two are in launch mode which start the process while 2 are in attach mode and then a final multi target debugger which uses the ones in attach mode that way I can run the tasks almost together. It works as a workaround :)

**Comment by weinand** [comment]
@darkyen great to hear that you were able to work around this limitation.

**Comment by DanTup** [comment]
@weinand Is there an example anywhere of being able to debug a debug adapter? I've been reading through all these issues, but they mostly seem to be launching multiple processes to debug at once, but since the debug adapter is started later when I hit F5 in my extension, I'm not sure how to get the debugger attached to it (and early enough to actually debug it).

**Comment by weinand** [comment]
@DanTup just run your debug adapter in server mode from VS Code (if it is a clone of mock-debug there should be a launch config "Server" for this). In another VS Code window add `"debugServer": 4711"` to you launch config. If you now launch this debug session, VS Code will connect to your debug adapter server.
This is explained here: https://code.visualstudio.com/docs/extensions/example-debuggers#_development-setup-for-mock-debug

**Comment by DanTup** [comment]
@weinand cool; I'll try diffing against that one, I must be missing something (I don't seem to have an option to launch it). Will it still call the start session command and use the info from launch.json in the project loaded in the extension host so my debugger gets the correct config?

**Comment by weinand** [comment]
If you are using the npm module "vscode-debugadapter" then your debug adapter automatically gets a server mode option `--server=4711`. In this mode the adapter creates a server socket and uses socket based communication (instead of the stdin/stdout based-communication). In addition the server doesn't shut down between sessions.

Yes, the start session command is supported as well. You should not see a difference here.

**Comment by weinand** [comment]
BTW, mock-debug has a composite launch config: "Extension + Server". If you use this you can debug you debug extension and you debug adapter simultaneously.

**Comment by DanTup** [comment]
@weinand Finally got around to trying this, my `launch.json` for the debug adapter was really old (no server option), but I've updated it and everything works perfectly. Thanks!

**Comment by weinand** [comment]
@DanTup great to hear!

**Comment by hexa00** [comment]
I just tried this with vscode Version 1.13.0

And I have the following problem:

Breakpoints are working in my nodejs debug app and when I start a chrome debug session the chrome debug breakpoins work, but the nodejs breakpoints go away.

I get Breakpoints ignored because generated code not found.

Any ideas on what is going on ? is the sourceMap beeing overriden globally with the ones found in chrome ? or ?
