### ISSUE TITLE
Don't use roaming profile on Windows for cache files

### ISSUE THREAD

**Issue by littleli** [microsoft/vscode#148489]
Hi VSCode team,

Unfortunately VSCode uses user roaming profile for storing cache. It's this location:

```c:\Users\USER\AppData\Roaming\Code\```

I don't think this is in general a good idea as roaming profile really can be synchronized over the network to user's other computer profile. And it's quite a significant amount of data that can be transfered and also it has to be also inspected / compared for changes slowing down computer operation significantly.

Please consider using different location for cache, I'd suggest 

```c:\Users\USER\AppData\Local\Code\```

I think for example extensions use of roaming profile could be ok, but for caching this leads to file system attrocities.
Thank you for your consideration.

**Comment by Zdendys79** [comment]
Thank you for this post.
We use roaming profiles on a domain with more than 20,000 users, also often use remote VPN connections.
When you log on or log off to Windows (roaming profile synchronization), a large number of small files significantly slows down the loading of a user profile. In general, this load cannot be skipped unless you are a domain administrator. (Then it is possible to set skipping of some listed folders.)

For example, my folder: **_`%appdata%\Code`_** contains 3,447 files (size ~1 GB),
of which there are 2,482 files in the folders **_`%appdata%\Code\Cache*`_** and **_`%appdata%\Code\Code Cache`_** (size ~678 MB).

Following the previous post, please change the storage of temporary files in the folder:
**_`%LOCALAPPDATA%\Code`_** instead of **_`%APPDATA%\Code`_**

Thank you politely and have a nice day.

**Comment by IllusionMH** [comment]
Looks like duplicate/part of #3884
