### ISSUE TITLE
No response for 'evaluate' request when program is running

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#14843]
Steps to Reproduce:

```javascript
var t = 5;
debugger;
```

1. Once you hit the breakpoint add `t` to a watch expression -> it is nicely evaluated
2. Continue the program -> notice how `t` does not update to `not available`. This is due to the fact that evalute request is not sending a response
3. I would expect the evalute to always give a response no matter the state of the program

**Comment by weinand** [comment]
@isidorn with "hit breakpoint" you mean "stopping on the debugger statement", right?

If I press continue, the program comes to an end (but does not correctly terminate because of this long standing [node issue](https://github.com/nodejs/node/issues/1788)) and the watch expression runs into a timeout after 10 seconds (which is the correct behaviour).

If I modify the program by adding some "waiting code" at the end, the "continue" triggers the watch expression results in a (expected) "not available" error.
