### ISSUE TITLE
Why So LagVisual studio code version 1.66

### ISSUE THREAD

**Issue by ManekaInduwara** [microsoft/vscode#148518]
https://user-images.githubusercontent.com/87568827/166157514-621f84a4-db0d-41f6-bd4a-5d829a69eb2e.mp4

**Comment by IllusionMH** [comment]
/needsMoreInfo

You have better chance to see issue fixed if you follow guidelines for issue reporting performance issues https://github.com/microsoft/vscode/wiki/Performance-Issues instead of picking edgy titles without useful system info(video shows problem, but not something that helps to diagnose it).
