### ISSUE TITLE
Snippet is not inserted inside of another snippet

### ISSUE THREAD

**Issue by oiiiiiiii** [microsoft/vscode#148523]
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version: 1.66.2
- OS Version: Fedora Linux 35

Steps to Reproduce:

Currently I have the problem, that snippets only containing only non-letter characters ('>', '-', ..) are not suggested in the suggestion menu (menu not showing up automatically). I can still insert them however with the command "insertSnippet" which I can map to a custom keybinding. However, this command doesn't work when inside another snippet.

1. Create a snippet with multiple tab stops
2. Create another snippet
3. Map a keybinding to the command "insertSnippet"
4. Insert snippet 1
5. type the prefix of snippet 2
6. press the "insertSnippet" keybinding

-> the second snippet is not inserted when in a tabstop of another snippet. In normal mode this is no problem but as soon as I'm inside another snippet the "insertSnippet" command does not work (even if this keybinding is not used for anything else). However I expect the command "insertSnippet" to always work.

**Comment by jrieken** [comment]
When a snippet is active, IntelliSense as you type (aka quick suggestions) is disabled. That is because there is a conflict between the <kbd>Tab</kbd>-key which moves to the next placeholder but also accepts a completion. You wouldn't be able to type in a placeholder and then move to the next placeholder as you would accept a suggestion then. You have the following options

* change the default via the `editor.suggest.snippetsPreventQuickSuggestions`-setting
* in snippets trigger suggestions manually (via Ctrl+Space, Alt+ESC (macOS), or `ctrl/cmd+i`)
