### ISSUE TITLE
Unbound breakpoint for TypeScript files

### ISSUE THREAD

**Issue by seb-mtl** [microsoft/vscode#148864]
Does this issue occur when all extensions are disabled?: Yes

I am building an Electron app, and the latest version of VScode stops binding breakpoints in TypeScript files. It is reproducible by switching between versions of VScode.

I also checked the latest Insider Build, with no success. Once I switch back to `v1.66.2` it works.

## Broken Version
Version: 1.67.0 (user setup)
Commit: 57fd6d0195bb9b9d1b49f6da5db789060795de47
Date: 2022-05-04T12:06:02.889Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.22610

![image](https://user-images.githubusercontent.com/12844423/167053262-d0778f73-8f36-4d87-9740-f6f3db3fed8a.png)

## Last Working Version 
Version: 1.66.2 (user setup)
Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977
Date: 2022-04-11T07:46:01.075Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Windows_NT x64 10.0.22610

![image](https://user-images.githubusercontent.com/12844423/167053074-2ccb540c-1e2a-4e9f-bf1c-25e4a57d6a8e.png)

The content of the `launch.json` is as follows:

```
    {
      "name": "Electron: Renderer",
      "type": "chrome",
      "request": "attach",
      "port": 9223,
      "sourceMaps": true,
      "webRoot": "${workspaceRoot}",
      "sourceMapPathOverrides": {
        "webpack:///./~/*": "${workspaceFolder}/node_modules/*",
        "webpack://?:*/*": "${workspaceFolder}/*"
      },
      "timeout": 300000
    },
```

**Comment by connor4312** [comment]
Please grab some log files!

/jsDebugLogs

**Comment by connor4312** [comment]
It doesn't look like I received anything, can you make sure it didn't bounce?

**Comment by seb-mtl** [comment]
Email sent.

**Comment by connor4312** [comment]
Thanks for your help!

Over email we figured out it was because we [made a change](https://github.com/microsoft/vscode-js-debug/pull/1241) that added support for `pathMapping` sourcemaps. In this change, we preferentially loaded sourcemaps from the mapped URI, which is a file URI on disk. In this case, there actually was a file URI of the same name on disk, which was not the version we would have preferred to load from the webpack-dev-server.

I will put in a PR to change the ordering back, which I think is fine, `pathMapping` of sourcemaps is only really useful if they don't exist at the original/intended location.

This issue may be candidate-worthy depending on whether we get more reports of it.

**Comment by seb-mtl** [comment]
Spot on help, thanks so much!
