### ISSUE TITLE
Title bar text can overlap the new layout buttons

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#148824]
![image](https://user-images.githubusercontent.com/2193314/166986082-f8e81678-3073-4c5e-9dfd-3a3e86e49be0.png)

Version: 1.67.0-insider (user setup)
Commit: 57fd6d0195bb9b9d1b49f6da5db789060795de47
Date: 2022-05-04T12:03:42.454Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.22000

**Comment by Tyriar** [comment]
Happened while running the desktop smoke texts, zoom level 1, dpr 1

**Comment by sbatten** [comment]
Repro:
1. Have `window.title` setting as default
2. Open a folder with 2 files, one with a really short name and one with a long name.
3. Select the short named file to open an editor and set the width of the window so that the title is centered on the window (not between the menu and controls)
4. Select the really long name editor.

short file name: 
![image](https://user-images.githubusercontent.com/6561887/167025474-4672c9d0-f5db-4194-a0bd-9bedeb07b9d9.png)
long file name:
![image](https://user-images.githubusercontent.com/6561887/167025505-25307dc0-09a8-402d-91aa-318f6c27c329.png)
