### ISSUE TITLE
Inlay hints appearance is different in 1.67.0

### ISSUE THREAD

**Issue by Drakota** [microsoft/vscode#148868]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.67.0
- OS Version: Windows 11 21H2 22000.613

Steps to Reproduce:

1. Enable inlay hints with options like `typescript.inlayHints.variableTypes.enabled`
2. Notice that the appearance of the inlay hints has changed

For comparison:
 1.66.2:
![image](https://user-images.githubusercontent.com/22665836/167062590-25e337b1-648b-4b8b-a8de-ddefd58de7a3.png)
1.67.0:
![image](https://user-images.githubusercontent.com/22665836/167062605-e497baa2-52c3-413f-9f33-c24ba27c572c.png)

I haven't seen any mention of this in the changelog

**Comment by gjsjohnmurray** [comment]
Do you have a value set for `editor.inlayHints.fontSize`?

**Comment by gjsjohnmurray** [comment]
https://github.com/microsoft/vscode/commit/6b5f78e4ff09b0c34c45946ba73298802a66326c apparently changed the default from 90% of editor font size to 100%.

**Comment by jrieken** [comment]
Yeah, that was done on purpose and with the goal to make inlay hints render more like source code. As already pointed out you can still change the size via the setting. 

This is "as designed" but leaving this issue open to await more feedback

**Comment by jrieken** [comment]
See https://github.com/microsoft/vscode/issues/145191 for me context on the padding. There was an effort to make inlay hint more compact, there was a setting but because many folks preferred compact we disabled the setting and went with compact only. We can bring back the setting but again awaiting more feedback

**Comment by Lyu-Zhaojie** [comment]
As a user of clangd, I do NOT think it's a good idea to make inlay hints like source code, because C++ has no corresponding syntax.

**Comment by BobbyJonas** [comment]
The inlay hints in Intellij are displayed with system UI fonts (such as Helvetica or sth) rather than code fonts, which makes sense for me. 
However, that's not what vscode does. It'll be so great to add this feature.

**Comment by lnicola** [comment]
Since we're bikeshedding, I kinda' liked the padding, since now the edge of the background is too close to the text and looks ugly (cut off) IMO. It doesn't even have to be a lot of padding, maybe 1px would be enough. Look at this variant of the "Comment" button on GitHub:

![image](https://user-images.githubusercontent.com/308347/167242355-3f64bac5-e815-4981-8414-6ec235358de0.png)

As for the font size, I prefer hints to be slightly smaller. I can set it, but in a way it would be nice to be able to use a percentage, since I sometimes change my editor font size. But this isn't that important.

It also a bit weird that the commit that switched to the "compact" mode also increased the font size, making them less compact.

**Comment by Lyu-Zhaojie** [comment]
> The inlay hints in Intellij are displayed with system UI fonts (such as Helvetica or sth) rather than code fonts, which makes sense for me. However, that's not what vscode does. It'll be so great to add this feature.

Emmm... There is `editor.inlayHints.fontFamily`

**Comment by BobbyJonas** [comment]
> > The inlay hints in Intellij are displayed with system UI fonts (such as Helvetica or sth) rather than code fonts, which makes sense for me. However, that's not what vscode does. It'll be so great to add this feature.
> 
> @BobbyJonas Emmm... There is `editor.inlayHints.fontFamily`

idk about that, thanks a lot haha. 
Then the padding style will be the only difference

**Comment by Souk21** [comment]
If that's possible, I too would like to be able to switch back to padding + rounded corners for inlay hints

**Comment by RobertOstermann** [comment]
I also prefer the old look with rounded corners and think an option to set the preferred style, such as  `editor.inlayHints.style` that others have mentioned, would allow users the flexibility of choosing the style that best suits them.

**Comment by hammypants** [comment]
This absolutely needs to be configurable on more axes than is available.

**Comment by NoahELE** [comment]
I think it's really a bad idea to make inlay hints looks just like source code. As inlay hints are 'hints' instead of actual 'code', it's quite important to make them distinguishable by default.

Also, I really want the rounded corner style back. The rectangle one now looks kind of awful.

**Comment by pksunkara** [comment]
FWIW, I think the `vertical-align: middle` needs to be enabled no matter what the inlay style is (`standard` or `compact`). Because if we use different font sizes for code and inlay hints, not having that rule messes up the line alignment.

@jrieken Do you mind if a make a PR for this?

* I will bring back the `standard` option (maybe name it `padded` or `rounded`)?
* Fix the alignment issue with different font sizes.

**Comment by jrieken** [comment]
@pksunkara Sure - it should be only about uncommenting a few lines [here](https://github.com/microsoft/vscode/blob/116c10e0eeed56dc9b0801d079e2a2374b6ccf98/src/vs/editor/common/config/editorOptions.ts#L2567-L2576). I'll be OOF soon'ish and will wait till Tuesday for your PR. Thanks!

**Comment by jrieken** [comment]
Maybe renaming the options is needed too. Today there is `standard` and `compact` - it should be less biased (no standard) and maybe 'likeCode' and 'likeWidget' 🤷 ?

**Comment by jrieken** [comment]
Next (tomorrows) insiders build will have this option: `editor.inlayHints.padding`

**Comment by tarberd** [comment]
> FWIW, I think the `vertical-align: middle` needs to be enabled no matter what the inlay style is (`standard` or `compact`). Because if we use different font sizes for code and inlay hints, not having that rule messes up the line alignment.
> 
> @jrieken Do you mind if a make a PR for this?
> 
>     * I will bring back the `standard` option (maybe name it `padded` or `rounded`)?
> 
>     * Fix the alignment issue with different font sizes.

@pksunkara I am getting conflicting results. With `vertical-align: middle` I get misaligned lines even when using the same font for both code and inlay hints:

![image](https://user-images.githubusercontent.com/3838509/172966987-e3ae3076-a6e4-4342-b924-4a360705e38c.png)

but, when I disable the css I get properly aligned text:

![image](https://user-images.githubusercontent.com/3838509/172967152-ab63cfb0-9a17-4558-93ba-bfacfd9dc97e.png)

![image](https://user-images.githubusercontent.com/3838509/172967117-f5a2c6c4-7e05-4df6-a1b3-09b2cd1b09b6.png)

This happens with or without padding being enabled.

Do you have any ideas on what could be causing this? Or if this behavior is intended?
