### ISSUE TITLE
Trying to stop auto-expand when there is a syntax error

### ISSUE THREAD

**Issue by miles-1** [microsoft/vscode#148947]
Does this issue occur when all extensions are disabled?: No

**I know that there are procedures for extension-caused issues, but please read on, as I believe this may still be a VSCode problem and not an extension problem.**

When I type a syntax error midway through a document, all previously-collapsed functions/methods from that point forward auto-expand. When there are potentially 20+ functions in a document, and I want the currently-unimportant ones collapsed, I hate having to go and re-collapse every method  when there is a syntax error, even just for a split second (e.g., when I type an open parenthesis and have not yet typed the close parenthesis).

When I used `code --disable-extensions`, this issue did not occur. However, none of the steps during the extension bisect caused the issue to reappear either, and multiple attempts of the extension bisect conclude different results, so I am not sure if the results reported here are accurate, but by golly I'd really like to figure this out.

Steps to reproduce (python example):
1. Make a new python document.
2. Type out three or four function definitions. For simplicity, you can put "pass" as the only line in each function definition.
3. Mouse over to the line numbers and click the carrot to minimize/collapse each of the function definitions.
4. Re-expand one of them (any is fine as long as it isn't the last function).
5. For that function, make some kind of syntax error in the body of the function, e.g., type a single parenthesis.

On my end, when extensions are not disabled, this causes all the function definitions from this point forward to expand, and they can only be collapsed by hand again after that.

Extension version: 1.9.8
VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:46:01.075Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-11400 @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.73GB (6.34GB free)|
|Process Argv|--crash-reporter-id 32d6ede4-adef-4e29-8898-09d0283014ef|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebugcf:30475217
vscaat:30438848

```

</details>

**Comment by PieterBranderhorst** [comment]
Thanks for the detailed report. This matches a known problem which happens when a folding range provider extension stops indicating foldable regions which correspond to currently hidden regions. In that case those regions automatically unfold.

This can be reproduced in many languages by entering a begin-comment (e.g. /* in Typescript) above some currently folded blocks without adding a corresponding end-comment. It sounds like the Python extension isn't identifying foldable regions following some syntax errors such as an unmatched opening parenthesis.

We have a fix in the works which got delayed a bit but is now expected to be in the end of May release. With the fix, when a folding range provider for a language stops returning foldable range indications for blocks which are currently hidden, vscode will keep those blocks hidden but mark them slightly differently on the display. If later on the provider starts identifying those ranges again they will continue to be hidden but will return to the normal visual indication.

**Comment by miles-1** [comment]
Thank you very much for you thorough reply. Glad to hear that it's being worked on. I'll close this issue since it's already on the docket.
