### ISSUE TITLE
Git clone protocol handler

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#149177]
https://msrc.microsoft.com/update-guide/vulnerability/CVE-2022-30129

**Comment by jlk** [comment]
@joyceerhl It really would be great to see more details in an issue that's linked to from the vscode release notes with the mention of a security fix. I mean - in general you should be giving details to a security fix in an OSS context. I'll add notes for others:

A security researcher with Sonar discovered that by providing a maliciously-crafted "URL" of a "git repository" to clone to vscode, a malicious user would be able to get vscode to execute commands locally. This scenario would require the attacker to get the vscode user to click on the URL to perform command execution.

Due to the nature of this vulnerability, this scores as an [8.8 on the CVSS v3 calculator](https://nvd.nist.gov/vuln-metrics/cvss/v3-calculator?vector=AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H&version=3.1). 

This has been mitigated in PR #149180 by performing input filtering on the URL to the supposed git repository to be cloned.

Also - would be nice if msft used the security disclosure tab/feature that's built into GitHub.

Also - why is there not a `security` issue label on this project??

**Comment by alexdima** [comment]
Thank you for the feedback! We've discussed this within the team and we will pretty much implement the majority of your suggestions!
