### ISSUE TITLE
gutter icon for resolved/unresolved comments

### ISSUE THREAD

**Issue by laurentlb** [microsoft/vscode#149162]
Comments in the editor have a different color based on their resolved status. We could do something similar for the icon in the gutter, and make obvious which comment is resolved even when comments are folded.

Maybe change the icon color? Or use a different icon?

(also related to https://github.com/microsoft/vscode/issues/149085)

**Comment by a-stewart** [comment]
Example of how it currently looks:  
![image](https://user-images.githubusercontent.com/150152/167638124-aa6647d6-b55e-422e-8f41-5d173cd5a67b.png)

Example with adjusted colours:  
![image](https://user-images.githubusercontent.com/150152/167638270-c371f7a0-dfbc-4e43-a685-da6a929126c3.png)

Note that colour alone is not a full solution since it is not that accessible, but I think it should be included in the final solution.

**Comment by alexr00** [comment]
A different icon/unicode character for resolved would be good here.

**Comment by alexr00** [comment]
Let's get https://github.com/microsoft/vscode/issues/115808 done first.
