### ISSUE TITLE
Creating Folders but Preventing Trailing Space in Non-Windows

### ISSUE THREAD

**Issue by gateslm** [microsoft/vscode#149382]
Related Issues / Feature Requests:
- #1579
- #59850
- #68555

The best scenario to describe this is with introductory programmers. In Visual Studio Code on Macs (and I believe Linux), you are able to add a trailing space at the end of folder names. 

A nice feature would be able to disable that in a VSC setting, as new learners don't realize they are typing a space or think that it is okay. (You can tell them not to do it but that doesn't stop them). 

**Why this is a problem?**:
- In project collaboration, if another person tries pulling from GitHub, a Windows computer can't get that path. 
- Harder for grading, hard to change on the computer that is doing the changes, especially for new programmers. 

The problems do relate to GitHub, but the ability to create them in VSC does start the problem. 

I know not all features can be addressed or implemented, but it looks like this was looked at earlier. 

Let me know if  need to clarify or if I missed a setting to handle that.

**Comment by lramos15** [comment]
Closing this as a user error for now. We may explore rendering the trailing whitespace in the explorer in the future, but do not want to introduce a new setting or handicap other users because of this. This can still occur outside VSC so it sounds like git really needs a solution here for all cross platform work and we do our best to warn people towards the right direction without forcing them.
