### ISSUE TITLE
Extension fails activation when installing extensions from cli that have a common dependency

### ISSUE THREAD

**Issue by jeanp413** [microsoft/vscode#149309]
- VS Code Version: stable and from sources

When launching the server and installing extensions using `--install-extension` that have a common dependency, one of the extensions will fail activating, prompting to reload VS Code.
For example installing, `vscjava.vscode-java-pack` and `pivotal.vscode-spring-boot`
- `vscjava.vscode-java-pack` contains `vscjava.vscode-java-test` which depends on `redhat.java`
- `pivotal.vscode-spring-boot` also depends on `redhat.java`
- `vscjava.vscode-java-pack` installation task finishes first and then trying to activate `vscjava.vscode-java-test` fails as [it doesn't await](https://github.com/microsoft/vscode/blob/93d046904eb3376017e9458105e2511c6122cd35/src/vs/platform/extensionManagement/common/abstractExtensionManagementService.ts#L169) for `redhat.java` installation which is part of `pivotal.vscode-spring-boot` installation task

Steps to Reproduce:

1. Open this branch https://github.com/gitpod-io/spring-petclinic/tree/jp/temp in gitpod or codespaces
2. Observe `vscjava.vscode-java-test` will fail activating and a notification shows prompting to reload vscode 
    <img width="448" alt="error_iamge" src="https://user-images.githubusercontent.com/25115070/167968496-839b6284-bef2-4bf5-978b-e935d91a99c5.png">

cc @sandy081

**Comment by jeanp413** [comment]
@sandy081 would you accept a PR fixing this? I took a look but it doesn't look something trivial to fix properly, I [tried some changes](https://github.com/gitpod-io/openvscode-server/blob/f35c6436559ed00e407879ac5af4c28264817a6b/src/vs/platform/extensionManagement/common/abstractExtensionManagementService.ts#L245-L247) but I don't think is a good fix

**Comment by sandy081** [comment]
@jeanp413 PR would be always welcome. Agreed it is not trivial. Let's see if there is a simple fix that fixes this and won't cause any regressions.

**Comment by jeanp413** [comment]
Created a PR https://github.com/microsoft/vscode/pull/150333 with a possible fix

**Comment by akosyakov** [comment]
@sandy081 ping, by any chance for July 🙏

**Comment by sandy081** [comment]
@akosyakov I am sorry that I am on vacation so cannot be looked in July.

**Comment by dlastrazeneca** [comment]
I was following this other [issue](https://github.com/microsoft/vscode-remote-release/issues/7347), but it was marked as a duplicate and was therefore closed.

This isse seems to be closed as well, although the issue persists.

Specifically, it seems that VS Code Dev Containers installs extensions in alphabetical order, so that if an extension that comes later in the order is a pre-requisite for another that is earlier, then the installations will not behave as expected. Example, `python` is a pre-requisite for `pylance`, but comes later in alphabetical order. Thus, `pylance` requires a VS Code Session restart after building the Dev Container.

Is this issue fixed in VS Code Insiders, but not released yet?

**Comment by sandy081** [comment]
@dlastrazeneca The issue you reported is using the build 1.71.* and this fix was pushed in 1.72.*. So please update your VS Code and try.
