### ISSUE TITLE
Setting for toggling the visibility of the sub sections in the Explore panel

### ISSUE THREAD

**Issue by avanderhoorn** [microsoft/vscode#149379]
I haven't found a way of being able to do this currently, but assuming its not... wondering if settings can be added from toggling the visibility of the sub panels in the Explore panel. I found this previous issue, but doesn't allow us to configure this when setting up the web workbench - https://github.com/microsoft/vscode/issues/73694.

**Comment by sbatten** [comment]
@sandy081 after chatting with @avanderhoorn, it sounds like the request is similar to being able to apply a profile as an embedder. essentially being able to hide certain views that are shown by default (clearly a subset of a profile). But exposing UI state to the embedder separately from profiles seems like duplication of effort to me. Thoughts?

**Comment by avanderhoorn** [comment]
@sbatten Regardless of profiles though, wouldn't having this as a basic setting be of benefit?

**Comment by sbatten** [comment]
I'm not sure what you mean by "a basic setting". This would be a very specific setting that we don't have precedent for. UI state is stored in local storage and there are currently 2 ways to set UI state outside of user interaction: 1) settings sync 2) new profile feature that is in the works. Introducing settings to control this would add another source of truth which is not ideal.

**Comment by avanderhoorn** [comment]
Currently I can use `"workbench.activityBar.visible": false` to hide the activity bar... maybe something like `"workbench.explorer.outline.visible": false`. Doesn't seem that difficult, I must me missing something.

**Comment by avanderhoorn** [comment]
@sbatten Any thoughts?

**Comment by sbatten** [comment]
Sorry, went out sick at the end of last week. There are 2 issues with using activity bar as our prior art. 

The first issue is that I'm actually trying to remove those settings in favor of having consistent UI state storage. There are 3 settings that should not exist but do for historical reasons. Obviously, this is a heavily used setting so it needs to be done right.

The second issue that is more important since the above may never happen is that the activity bar is a workbench part. There are a fixed set of parts that VS Code's workbench is made of and a setting per part is scalable since it has an upper limit. Outline is a view, the number of views in the workbench can be large as these are contributed by extensions. For this reason, introducing a setting per view is not scalable.

**Comment by sandy081** [comment]
May I know the use case behind this request? Why do you want this as a setting?
