### ISSUE TITLE
Incorrect position of references count fo *.cs  

### ISSUE THREAD

**Issue by philipp-kolesnikov** [Microsoft/vscode#14949]
- VSCode Version: 1.7.1
- OS Version: Windows 10 1607.14393.351

Steps to Reproduce:

1. Open any *.cs file and see that references counts are displayed at wrong position.

Sidebar is placed on left and closed
![sidebarclosedleft](https://cloud.githubusercontent.com/assets/10916232/19990855/b5ee1c56-a27c-11e6-92de-4f06dd5df48e.png)

Sidebar is placed on right and closed
![sidebarclosedright](https://cloud.githubusercontent.com/assets/10916232/19990856/b5ef9a5e-a27c-11e6-971c-06b3bf200c9a.png)

Sidebar is placed on left and opened
![sidebaropenedleft](https://cloud.githubusercontent.com/assets/10916232/19990857/b5f00c46-a27c-11e6-8b55-860d2f311041.png)

My user setting:
  "editor.fontFamily": "Fira Mono",
  "window.zoomLevel": 3,

**Comment by joelharkes** [comment]
I can agree, it happens on zoom:

![image](https://cloud.githubusercontent.com/assets/2960938/20008607/93b2f2fe-a2a1-11e6-87af-c0760c480bb1.png)


When i go to normal zoom it is fine:

![image](https://cloud.githubusercontent.com/assets/2960938/20008638/a3b48212-a2a1-11e6-8fd8-64835be889e2.png)

**Comment by stuartleeks** [comment]
Same here, only on zoom (in or out)

**Comment by alexandrudima** [comment]
I can reproduce also with `pflannery.vscode-versionlens` (any code lens)

@joaomoreno This was first introduced with ea8e2792723f8cc84507a877fd37420e6123139d

I think the issue is in [`contentWidgets.addWidget`](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/browser/viewParts/contentWidgets/contentWidgets.ts#L157):

I believe the new logic needs to be better guarded. i.e. a content widget should get the new `fixed` treatment when:
* `configuration.editor.viewInfo.fixedOverflowWidgets` is true
* **and** the content widget must allow of overflow (`widgetData.allowEditorOverflow`).

**Comment by joaomoreno** [comment]
Absolutely right, @alexandrudima !

**Comment by joaomoreno** [comment]
cc @egamma @chrisdias @kieferrm
