### ISSUE TITLE
Users hitting "Learn more link about JS/TS refactoring" by accident in Refactoring context menu

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#149415]
- VS Code Version: 1.67.1
- OS Version: Windows 11

Steps to Reproduce:

1. Place cursor on a line in TypeScript where there is no available refactoring
2. Ctrl+Shift+R to bring up the Refactoring context menu.
There should be no available refactorings and only the "Learn more about JS/TS refactoring" entry is enabled.
3. Hit Enter and you are taken to https://code.visualstudio.com/docs/languages/typescript#_refactoring via LearnMoreAboutRefactoringsCommand

Some users are reporting in doc feedback comments that they are going to the website by accident due to the Learn more item being the only command enabled.

Some comments:
"Why does this page come up whenever I try to refactor anything in VS Code?"
"This keeps coming up whenever I'm trying to use refactor."

The Learn more entry was added for discoverability to help users understand how generally refactoring works and what TS refactors are available.

One option would be to show the "Learn more" entry until the user selects it once or some number of times and then remove it from the list. 
Or after some number of hits, prompt the user to ask if they'd like to keep the entry in the Refactors list and call out a setting if they change their mind later.

**Comment by hfhchan** [comment]
This doesn't happen on macOS because if the first item in the context menu is disabled pressing enter has no effect. Windows could copy this behaviour.

Context menu on macOS:
![image](https://user-images.githubusercontent.com/8191296/168206765-a941a341-3c81-48d1-a7a0-8f35c10f3fda.png)

**Comment by gregvanl** [comment]
Still reproduces with the latest 1.70 insiders. 

The issue is that the documentation link has focus when there aren't any available refactorings.

If a user is typing quickly, they could easily have their cursor on a line without refactorings by mistake, and their muscle memory to apply the most recent refactoring Ctrl+Shift+R then Enter, sends them out of the editor to our website.

This doc feedback comment came in last week: "STOP PULLING UP THIS USELESS PAGE WHENEVER I TRY TO USE THE TS REFACTORING TOOL!!!"

**Comment by gregvanl** [comment]
I take it back, this is fixed!

**Comment by gregvanl** [comment]
I can get the issue to reproduce if I spend some time in a JavaScript file. 

![image](https://user-images.githubusercontent.com/12818376/181833627-c4ce2f27-da07-4f04-8b94-040d245fedc1.png)

I'm playing around in the gulpfile.js in the vscode-docs repo.

I'll try to find a consistent repro but initially I see the "No refactorings available" popup, then after moving the cursor around for a bit, I get the context menu with the "Learn more JS/TS refactoring" not selected, then after some time the doc command will be selected.

**Comment by gregvanl** [comment]
Here's an example on an empty line

![image](https://user-images.githubusercontent.com/12818376/181834223-57ad433f-b5a6-48b7-815c-622ab6a05288.png)

**Comment by justschen** [comment]
@gregvanl can you double check that the setting `editor.contrib.experimental.codeActionWidget.enabled` is set to true? Can also be found by going to Editor › Experimental: Use Custom Code Action Menu!

At the moment, the fix is only for the custom Code Action Widget (which will replace the quickfix menu, refactor menu, and source actions). It's currently disabled by default but should be enabled by default in insiders for this month.

**Comment by justschen** [comment]
Fixed with the new Code Action Widget - no longer selects via keyboard or on automatically opening the widget.

![Recording 2022-08-18 at 16 58 43](https://user-images.githubusercontent.com/54879025/185514851-37e584b9-9dc7-4d48-b482-89007d970264.gif)

Example when there are code actions available - hitting up will take the focus to the bottom of the list, instead of `Learn more about JS/TS Refactorings`

![Recording 2022-08-18 at 17 01 25](https://user-images.githubusercontent.com/54879025/185515062-0b7ef4f3-c043-482d-9972-2e51f485ca6a.gif)
