### ISSUE TITLE
Editor > Inlay Hints:Enabled: offUnlessPressed minimap error

### ISSUE THREAD

**Issue by AmelloAster** [microsoft/vscode#149572]
Does this issue occur when all extensions are disabled?: No

- VS Code Version:Version: 1.68.0-insider (Universal)
Electron: 17.4.3
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
- OS Version:Darwin arm64 21.4.0

Steps to Reproduce:

1.Editor > Inlay Hints:Enabled: offUnlessPressed
2.Ctrl+Alt show and hidden hint
3.minimap render error
<img width="683" alt="image" src="https://user-images.githubusercontent.com/26178326/168477338-30a82d68-a698-4ad9-bf4b-40e2132e5346.png">
<img width="181" alt="image" src="https://user-images.githubusercontent.com/26178326/168477350-87825c7f-234c-44c3-88be-4d0c92944daf.png">

**Comment by DropDemBits** [comment]
If I believe this is the same issue as what I'm having, this also manifests as performance degradation when clicking the cursor around likely due to hit-testing against (potentially thousands of) stale/duplicate inlay hints.

My issue was tested on insider release 2022-05-15 with the following repro steps:

1. Set "Inlay Hints" to `offUnlessPressed` 
2. With the rust-analyzer extension enabled, scroll down a reasonable-sized file (I think inlay hints are always sent on scroll, so this is equivalent to scrolling & then pressing Ctrl-Alt on an LSP client that doesn't send requests on scroll).
3. Press Ctrl-Alt a few dozen times to accumulate stale/duplicate inlay hints (this should also appear in the minimap as lines growing longer)
4. Click around in the text view (there should be a noticeable delay, if not then keep repeating step 2)

From checking the server trace from rust-analyzer, it appears to be sending inlay hints within a reasonable range of the text view, so it's likely not rust-analyzer's fault.
