### ISSUE TITLE
Page-down in notebook goes up

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#149502]
- Open https://github.dev/greazer/covid-19-data/blob/master/SampleNbsAndScripts/myanalysis_plotly.ipynb
- Select the top cell and page down a few times
- Focus hits a cell that is longer than the viewport, which is maybe important, then the next page down moves to a higher cell

**Comment by rebornix** [comment]
https://github.com/microsoft/vscode/blob/3381e7b20b96d27ea8ac4ee6aa1c065d7b47fa29/src/vs/base/browser/ui/list/listWidget.ts#L1599-L1600

When a list item is larger than the viewport, and it's also the only element in the viewport, pressing page down will reveal to the previous element, this is because we did a `lastPageIndex - 1` here.
