### ISSUE TITLE
`registerCompletionItemProvider` `triggerCharacters` is ignored

### ISSUE THREAD

**Issue by Real-Gecko** [microsoft/vscode#149584]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.67.1
- OS Version: Arch Linux

I was creating an extension for VSCode and when I was adding `CompletionItemProvider` I've noticed that provider that must be triggered with a dot (".") is triggered all the time which ever key I type in. I've cloned https://github.com/microsoft/vscode-extension-samples to see if I'm doing something wrong and it turns out it's a bug.

Steps to Reproduce:

1. Clone https://github.com/microsoft/vscode-extension-samples
2. Launch VSCode in cloned repo `completions-sample`
3. Put breakpoint in `extension.ts` line `58`
4. Run extension
5. In newly opened window create a new `txt` file
6. Type any character except dot
7. Notice the breakpoint being triggered, event though it's not supposed to

See the video for full demonstration:

https://user-images.githubusercontent.com/2231969/168491023-1ca2a424-8e77-4893-a653-a50248ebbb48.mp4

**Comment by jrieken** [comment]
> I've noticed that provider that must be triggered with a dot (".") is triggered all the time which ever key I type in.

That's by design and the "suggest as you type" feature. Whenever a word is being typed we trigger intellisense. This can be controlled with the `editor.quickSuggestions` setting. Trigger characters are additive to this and exclusive to the provider that registered that characters. Last, when writing a completion item provider it must be ready to be invoked anytime in any context, trigger characters are just hints to also invoke it
