### ISSUE TITLE
Lazy variable evaluation button causes problematic gaps and misalignments between nodes

### ISSUE THREAD

**Issue by capegreg** [microsoft/vscode#149638]
The new lazy variable evaluation button line-height or dimensions appear to be too large. The button creates frequent gaps in-between node items and creates unsightly misalignment. This is not a settings font issue because the issue appeared with the change to the lazy evaluation button in version 1.67.1. This new button does not improve JavaScript debugging. The ellipsis button did not do this.

Version: 1.67.1 (user setup)
Commit: da15b6fd3ef856477bf6f4fb29ba1b7af717770d
Date: 2022-05-06T12:37:03.389Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.19044

Does this issue occur when all extensions are disabled?: Yes

Steps to Reproduce:

1. Output JavaScript object to console window
2. Examine the gaps between expandable nodes
3. Click any collapsed variable to evaluate. The item will jump and become misaligned.

### Screenshot showing misaligned line heights caused by new lazy variable evaluation button
![image](https://user-images.githubusercontent.com/1051118/168591655-341e86c1-9693-4267-8d07-d9b08f36678f.png)

**Comment by isidorn** [comment]
@roblourens I think the idea is to make the debugHover tree smaller, while the other trees in views should be larger.

The problem here seems to be that the debugHover reuses the `variablesView` and by that the height of the hover items is 22. So the height should be configurable, and debugHover should be able to say to the variableDelagate that the height is 18 in this case.

**Comment by isidorn** [comment]
@roblourens okey. Thanks for fixing 👏

**Comment by roblourens** [comment]
This broke the alignment of the lazy button in the debug console because the text wraps there
