### ISSUE TITLE
npm tasks generated label when a label isn't specified is inconsistent with generated tasks

### ISSUE THREAD

**Issue by segevfiner** [microsoft/vscode#149676]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.67.1
- OS Version: macOS 12.3.1

Steps to Reproduce:

1. Create a new TypeScript extension using `yo code` and open it in VS Code.
2. Run Ctrl/Cmd+P and and type "task "
3. Notice that the task for watch is labeled "npm watch" (The task has no `label` in `tasks.json`), while if you were to add it by choosing to configure it, it would have been generated with a label of "npm: watch".

**Comment by alexr00** [comment]
A few years ago we improved the performance of the task quick pick by delaying going to extensions for tasks until a task actually needs to be run. This means that properties that aren't required to be in tasks.json, like `label`, are made up by the task system instead of fetched from the extension.

Here's how we make up a task label: 

https://github.com/microsoft/vscode/blob/20514b2dc39e9ea80d27a859130d2050450753cf/src/vs/workbench/contrib/tasks/common/taskConfiguration.ts#L1478-L1488

Here's where the npm extension provides the task name (label becomes <source>:<name> for extension provided tasks:

https://github.com/microsoft/vscode/blob/a576b4c066521fe52b248eac9b21e6a01e7d22bd/extensions/npm/src/tasks.ts#L330-L332

https://github.com/microsoft/vscode/blob/e19f09713b6d674a200b293fb66fda0908e8a971/src/vs/workbench/api/browser/mainThreadTask.ts#L367-L368

After the task has been run, then we'll save the actual task label and it will be shown in the quick pick next time.

@meganrogge, happy to discuss with you if you want!

**Comment by alexr00** [comment]
@meganrogge there isn't a perfect solution here. It was too expensive to fetch the actual task label from the extension which is why we're in this state. I think we could either:
- Change how we make up the task label in the hopes that we can get closer to what most tasks end up doing.
- Do nothing, the discrepancy resolves after first run and was the price we had to pay for better performance. 

I'm leaning slightly toward the first option since this this is one of the first things a new user of tasks might see. There's always the risk then that users might notice the change and be unhappy with it. Given that the change is just to add a `:` in an existing string it's probably worth doing.
