### ISSUE TITLE
Bind zoom actions also to numpad equivalents

### ISSUE THREAD

**Issue by drweb86** [Microsoft/vscode#14979]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T16:21:53.542Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: ms-vscode.csharp-1.4.1

Hello

I often needs zooming because of eyes and thats why i'm writing those wishes to your cool IDE...

1. Could you please make default ability in Visual Studio Code to increase and decrease font size with setting "editor.mouseWheelZoom": true. 
2. Also zomming via keyboard Ctrl + "-", "+", "0" (on numeric keyboard) does not work, but it works in browsers...

Thanks.

**Comment by ffes** [comment]
Just in case... you know that Ctrl+- and Ctrl+= do this?

**Comment by drweb86** [comment]
Yea, but its much more comfortable with mouse.... Also Ctrl+= seems doesn't work since both keys are located on the same physical key. I think it'd better be Ctrl + ++ and Ctrl + -- as in browsers + mouse wheel.

**Comment by Tekbr** [comment]
To use the mouse scroll: "editor.mouseWheelZoom": true

I know I have set up, but it would be interesting come by default also Ctrl + 0 (to reset the zoom), Ctrl + + (instead of =) and Ctrl + -, as in browsers.

By default the "-", "+", "0" of the numeric keypad does not work. This should work as in browsers.

**Comment by drweb86** [comment]
I updated issue with your comments, Tekbr.

**Comment by alexandrudima** [comment]
@drweb 

regarding 1. the option is not on by default because trackpads are very susceptible to zoom in/out like crazy. It has been reported multiple times that, at least under mac, this gets triggered accidentally very often. Since we listen to `mousewheel` events coming from Chromium, and we cannot distiguish trackpad gestures from mouse gestures, we cannot work around it and have opted to make the feature opt-in by making the flag off by default.

regarding 2. I can add more out-of-the-box keybindings for zooming, and I suggest this issue continues to track only point 2. (bind zoom actions also to ctrl + numpad keys)

**Comment by drweb86** [comment]
alexandrudima,

Thanks. I didn't know that you have take into account sooo much considerations behind the scene.  Also i thought you're coding it in wpf but as i see now IDE is most probably written in javascript itself.

**Comment by Tekbr** [comment]
@alexandrudima 

I guess that was not quite it.

1- Ctrl + +  It should zoom in on the editor, the file we're moving, not the zoom of the whole program.
2- Ctrl + -  You should zoom out within the editor, the file you are moving, not the zoom of the entire program.
3- Ctrl + 0  You should zoom back to the default, the file you are moving, not the zoom of the entire program.

4- Ctr + +, Ctr + - should work the same way when we use "editor.mouseWheelZoom", by only zooming the file. And using Ctrl + 0 returns to the default.


5- Ctr + = You should do nothing. The zoom continues. You must unlink this function.
6- Ctrl + 0 of the non-numeric keyboard does not reset the zoom.

Can you check it please?

**Comment by Tekbr** [comment]
@alexandrudima ????

**Comment by Tekbr** [comment]
@alexandrudima Can you check this, please? Or say one why not do this?

**Comment by drweb86** [comment]
Thanks guys

**Comment by sandy081** [comment]
@alexandrudima Reset zoom is not working in Mac with <kbd>cmd</kbd>+<kbd>0</kbd>

**Comment by Tekbr** [comment]
@alexandrudima Please look at the other notes.

**Comment by alexandrudima** [comment]
@Tekbr please open a different issue, I agree with you that the zoom actions should be bound to increasing the font size of the editor, instead of zooming in the entire UI (which no other editor does AFAIK).

In fact I am 100% in favor of eliminating the entire UI zoom we're shipping with, it causes many issues with font anti-aliasing for example and I have to maintain extraneous code to work around it (i.e. not using `translate3d` when the UI zoom is not 100%)

This issue is about the binding of zooming actions to numpad keys (as the op wants) and after adding <kbd>cmd</kbd>+<kbd>0</kbd>, I will close it again.

**Comment by alexandrudima** [comment]
@sandy081 Are you pressing the <kbd>NUMPAD_0</kbd>? Because that works for me. I cannot bind <kbd>cmd</kbd>+<kbd>0</kbd> because that is used by another action.

**Comment by Tekbr** [comment]
@alexandrudima About what @sandy081  said, I have the problem with Windows. Ctrl + 0 on non-numeric keyboard does not work. See issue #15840. It is a feature request that has been spoken about here before but has not been placed.

> I know I have set up, but it would be interesting come by default also Ctrl + 0 (to reset the zoom), Ctrl + + (instead of =) and Ctrl + -, as in browsers.


I'm going to open a new issue about it as indicated.

> @Tekbr please open a different issue, I agree with you that the zoom actions should be bound to increasing the font size of the editor, instead of zooming in the entire UI (which no other editor does AFAIK).
In fact I am 100% in favor of eliminating the entire UI zoom we're shipping with, it causes many issues with font anti-aliasing for example and I have to maintain extraneous code to work around it (i.e. not using translate3d when the UI zoom is not 100%)
This issue is about the binding of zooming actions to numpad keys (as the op wants) and after adding cmd+0, I will close it again.


Thank you.

**Comment by sandy081** [comment]
@alexandrudima I tried with Numpad 0 on my keyboard with numpad. Still reset zoom on Mac does not work for me.
