### ISSUE TITLE
Feature request: allow disabling experimentalDecorators warnings from user settings

### ISSUE THREAD

**Issue by capaj** [Microsoft/vscode#14985]
I work primarily on JS projects, not typescript projects. I use decorators almost in all apps I work on, so it would be hard to add `tsconfig` to all of them. Could we have a user setting to surpress the warning globally?

**Comment by waderyan** [comment]
@capaj this is an interesting idea. We don't have support for something like this in our model currently. 

@dbaeumer can I get your thoughts here. Adding a setting to supress a warning may be something that would be helpful in multiple scenarios.

**Comment by dbaeumer** [comment]
@waderyan since 2.0.3 we can control this for virtual projects. But if users do have a `jsconfig.json` we can't. So what would be a need idea is to set some jsconfig defaults on startup which are merged with some real settings retrieved from a jsconfig.json or tsconfig.json. But his requires support from TS.

**Comment by mjbvz** [comment]
The most recent code insiders builds adds a new setting: `"javascript.implicitProjectConfig.experimentalDecorators"` to control this for implicit projects only. We do not attempt to set this when you already have a `jsconfig`.

When VS Code creates a `jsconfig.json` for you however, it will automatically set `experimentalDecorators` in the jsconfig  based on `javascript.implicitProjectConfig.experimentalDecorators`
