### ISSUE TITLE
[css] support @apply

### ISSUE THREAD

**Issue by rictic** [Microsoft/vscode#14999]
- VSCode Version: 1.7.1
- OS Version: macOS 10.12.1

#### Steps to Reproduce:

1. Save the following as `test.css`:

```css
body {
  --my-theme: {
    color: red;
    background: white;
  };
}

body div {
  @apply --my-theme;
}
```

2. Open it in VSCode, observe syntax errors.

#### More context

The new css features are really nice, a significant improvement in most development workflows. However, there is some legal CSS syntax (like css custom property values) that is flagged as a syntax error, and there are some emerging CSS features (like `@apply`) that extend the standard CSS grammar.

I'm on the Polymer team at Google, and we've recently shipped early versions of a language server and a plugin for VSCode to provide a high quality developer experience to our users. I've filed https://github.com/Microsoft/vscode-css-languageservice/issues/7 and https://github.com/Microsoft/vscode-css-languageservice/issues/8 but in the meantime is there anything our users can do – or that we can do in our plugin – to reduce the disruptiveness of these syntax errors to their development experience?

**Comment by rictic** [comment]
Copying over a comment from #15032, it looks like a workaround for now is to set this preference:

```json
"css.validate": false
```

**Comment by octref** [comment]
I'm not familiar with Polymer's CSS. Are you using PostCSS for transpiling?

If so maybe you can write some linter rules and disable CSS validation as @mrmlnc suggested. StyleLint seems to be popular and support experimental CSS features.

This is what we suggest for users who want to use proposed syntaxes like object spread:

https://code.visualstudio.com/Docs/languages/javascript#_common-questions

Q: How do I disable Syntax Validation when using non ES6 constructs?

A: Some users want to use syntax constructs like the proposed Object Rest/Spread Properties. However, these are currently not supported by VS Code's JavaScript language service and are flagged as errors. For users who still want to use these future features, we provide the `javascript.validate.enable` setting.

With `javascript.validate.enable: false`, you disable all built-in syntax checking. If you do this, we recommend that you use a linter like ESLint to validate your source code. Since VS Code's JavaScript support doesn't understand ES7 constructs, features like IntelliSense might not be fully accurate.

**Comment by rictic** [comment]
Yeah, definitely, we're working on our own linter, including CSS.

Is it possible for a plugin to modify an existing setting's default value? This would be useful in a couple of places. When you install the polymer plugin we could disable css validation, but we could also contribute some json schemas to "json.schemas" as well (e.g. for `polymer.json` and `elements.json`, and it would be great to get intellisense and validation and the rest as you get out of the box with `package.json` and `tsconfig.json`)

**Comment by octref** [comment]
> s it possible for a plugin to modify an existing setting's default value?

Can you open a new issue for it?

**Comment by rictic** [comment]
Sure thing! Filed as https://github.com/Microsoft/vscode/issues/15066

(Oh, and answering my own question above, it looks like there's [`contributes.jsonValidation`](https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributesjsonvalidation) for plugins to contribute json schemas)

**Comment by rictic** [comment]
I sent out PRs to the vscode-css-languageserver and they have now been merged:
 * https://github.com/Microsoft/vscode-css-languageservice/pull/11
 * https://github.com/Microsoft/vscode-css-languageservice/pull/10

So I think this bug is safe to close, as it should be fixed in the next release!
