### ISSUE TITLE
Buttons to disable / enable all extensions disappeared.

### ISSUE THREAD

**Issue by Tekbr** [Microsoft/vscode#14992]
- VSCode Version: 1.8.0 - insider (dbf3ba7)
- OS Version: Windows 10

-- Sorry for the English, I used Google Translator --

Steps to Reproduce:

1. Buttons to disable / enable all extensions disappeared.
![gif](https://cloud.githubusercontent.com/assets/19866231/20009782/e4aadf38-a28c-11e6-9061-81b825ed946e.gif)

**Comment by joaomoreno** [comment]
We'd decided to clean up the menu. That action is now available as a global command, reachable via <kbd>Cmd Shift P</kbd> or <kbd>F1</kbd>.

**Comment by Tekbr** [comment]
-- Sorry for the English, I used Google Translator --

@joaomoreno I think the other more intuitive, more direct. Perhaps the choice of Workspace could get through `F1`. But enable and disable general should get easier.

Add some menus, such Update, Enable All, All Disabled

Would be like this:
`"..."> More Settings> 1- Update All Extensions, 2- Enable All Extensions, 3- All Disabled Extensions`

If you are all disabled, only the button to enable becomes active. The same goes for the reverse.

**Comment by Tekbr** [comment]
@joaomoreno Did you get the idea?

**Comment by joaomoreno** [comment]
I did. We've decided not to add more menus, because that makes them more bloated. There is also additional confusion because the "Enable All Extensions" and "Disable Add Extensions" might be confused to only work with the extensions visible in the list, while in fact they will disable **all** your installed extensions. Finally, these actions are so rarely used that putting them in the menu would be overkill. Commands will do just fine.

**Comment by Tekbr** [comment]
@joaomoreno I did not understand this part. I did not see what could be confusing.

> There is also additional confusion because the "Enable All Extensions" and "Disable Add Extensions" might be confused to only work with the extensions visible in the list, while in fact they will disable all your installed extensions.

**Comment by joaomoreno** [comment]
For instance, you can search for extensions in the Marketplace. Let's say 3 come up that are locally installed. If you go into the action and select "Disable Add Extensions", would you expect that only those 3 to be disabled, or all your installed extensions?

Also, how often do you use these actions?

**Comment by Tekbr** [comment]
-- Sorry for the English, I used Google Translator --

What is "Disable Add Extensions"? Disable extension that I just installed? Only 3 (for example)?


Either I enable them all at once or disable them all at once. Regardless if I just installed it or not. If you want a specific one, I'll go with the extension option.

I agree that it is not often, only when it behaves strangely. But I said that it is more intuitive (being only the option to enable all and disable all). Enabling / Disabling workpace I agree it should not be there.

**Comment by joaomoreno** [comment]
I meant "Disable All Extensions".

**Comment by Tekbr** [comment]
Okay. So like I said, I'd rather disable everything.
I do not think this will change until some more people question.
But thanks for the comments.

**Comment by fehrenhuber** [comment]
I think the option to enable/disable all extension would be very helpful for the vscode support team, to find out if a strange behaviour is coming from an extension, or from vscode itsself. So I would strongly recommend, to add this option! A concrete example is, that I have a strange behaviour in the editor, where the cursor is automatically jumping at the end of the line, so that a fluent typing is no longer possible. As I have a lot of extensions installed it would last a very long time to disable every single extension.So please keep this in mind for your future plannings

**Comment by tamj0rd2** [comment]
It would also be really useful during extension development
