### ISSUE TITLE
Can't extract contents of trace logs (vscode-debugadapter-*.json.gz)

### ISSUE THREAD

**Issue by troncoso** [microsoft/vscode#150047]
Does this issue occur when all extensions are disabled?: **Yes**

- VS Code Version: **1.67.2**
- OS Version: macOS Monterey **12.3.1**

Steps to Reproduce:

1. Create a launch.json or modify one to include `"trace": true`
2. Run the launch config
3. In a terminal, navigate to where the *.json.gz file is saved
4. Attempt to extract the file with gunzip/gzip/tar/etc.

Here is my launch config:

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "pwa-chrome",
            "request": "attach",
            "name": "Debug Client",
	    "port": 9222,
	    "url": "http://localhost:300",
	    "webRoot": "${workspaceFolder}/src",
	    "trace": true
        }
    ]
}
```

Expected result: for the extraction to work

Actual results: extraction fails:

```
>> % gunzip -d vscode-debugadapter-2c6cf698.json.gz 
gunzip: vscode-debugadapter-2c6cf698.json.gz: unexpected end of file
gunzip: vscode-debugadapter-2c6cf698.json.gz: uncompress failed
```

```
>> % gzip -d vscode-debugadapter-2c6cf698.json.gz 
gzip: vscode-debugadapter-2c6cf698.json.gz: unexpected end of file
gzip: vscode-debugadapter-2c6cf698.json.gz: uncompress failed
```

```
>> % tar -xzvf vscode-debugadapter-2c6cf698.json.gz 
tar: Error opening archive: truncated gzip input
```
 
Here's an example file
[vscode-debugadapter-2c6cf698.json.gz](https://github.com/microsoft/vscode/files/8743324/vscode-debugadapter-2c6cf698.json.gz)

**Comment by janmonterrubio** [comment]
Also ran into this after trying to diagnose the UI just hanging up and not connecting (without any output forwarded anywhere). 

I ended up using [this article](https://blog.sqreen.com/remote-debugging-nodejs-runtime-code-injection/) as a reference for trying to attach with a different debugger. 

That ended up immediately giving me a socket-hangup on the remote process, so I knew the problem was with the process and not vscode. However, it would have been nice if VSCode had forwarded the error _somewhere_

**Comment by connor4312** [comment]
The complete log file will be written out when the debug session ends. If you try to read the log file before that point, you may get errors like you experienced. This is more on the side of the `gzip` CLI, since we do `Z_SYNC_FLUSH` each message which should render it readable. Often piping in via `cat log.json.gz | gunzip` will work better.

The only other option is to not compress log files at all. While this is doable, it would make logs many times bigger as we can be quite verbose.

**Comment by janmonterrubio** [comment]
> Often piping in via cat log.json.gz | gunzip will work better.

This worked great, thank you so much!
