### ISSUE TITLE
Close All working-tree files feature update causes unintended actions

### ISSUE THREAD

**Issue by smry-web** [microsoft/vscode#150195]
Issue Type: <b>Bug</b>

#81067 was fixed with #18651

When that option is enabled, if you have the Source Control -> Staged Changes files collection collapsed, it opens that closed carrot. 

If I add a file on **Changes** panel with this option enabled and **Stages Changes** collapsed it will open that panel 

VS Code version: Code 1.67.2 (c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5, 2022-05-17T18:15:52.058Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

**Comment by lszomoru** [comment]
@smry-web, sorry for not getting back to you on this until now. I believe that the issue that you are seeing is not due to the new functionality but it is related to the `scm.autoReveal`. Do you have this setting enabled? If so, when the active editor changes, the file would be revealed in the Source Control view, that can result in a collapsed resource group (Staged Changes, Changes) to be expanded. 

In case you have any further questions please don't hesitate to reopen this issue. Thanks!
