### ISSUE TITLE
Notebook suggest widget behind workbench

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#150238]
<img width="726" alt="image" src="https://user-images.githubusercontent.com/8586769/169928136-d2fb0e0c-a5f8-44fa-b2ab-8288d992c829.png">

**Comment by rebornix** [comment]
zindex ftw

**Comment by rebornix** [comment]
Actually not zindex, it was introduced via https://github.com/microsoft/vscode/commit/526505636e4d4f86a1ba1545e08a17f8b8d8140d 

@mjbvz is the `clip` necessary here and could we not enforce that for notebook editor? When we have clip, the widgets in code editor will be cut off on the boundries.

**Comment by mjbvz** [comment]
We do need the clip to fix #116946 for notebooks. Otherwise when you scroll the editor area, the notebook widget will render on top of the sidebars 

Not sure how the fix this though. We've want to clip everything except the editor widgets. Off the top of my head I'm not sure how to do that

@rebornix I think for now we should revert the clip since it's less important than widgets rendering properly. I'll create a PR that does that but also open a new issue tracking the notebook's overlaying incorrectly when the editor area is scrolled
