### ISSUE TITLE
HTML snippet will be chosen while typing CSS code in <style>

### ISSUE THREAD

**Issue by Reedo0910** [Microsoft/vscode#15030]
- VSCode Version:1.7.1
- OS Version:Windows 10 x64

Steps to Reproduce:
1. type "col" in html <style> tag
2. HTML snippet"<col>" will be chosen instead of CSS code "color"

![4fd0e0f6-a2b4-11e6-93fb-df0ee8bbdf4f](https://cloud.githubusercontent.com/assets/19267441/20028653/bd61ea7a-a372-11e6-9952-40fc187f9b5d.PNG)

**Comment by hamidufalke** [comment]
I disabled HTML Snippet, and reproduce the case, the behavior is correct. and since the extension overrides the default behavior, i think you should consider reporting the issue to HTML Snippet repository.

**Comment by Reedo0910** [comment]
@hamidufalke Yes,I have reported this issue to HTML Snippet repository (https://github.com/abusaidm/html-snippets/issues/17),and the author said maybe it's the vscode's intelisense algorithm caused this problem.

**Comment by jrieken** [comment]
@Reedo0910 Is this about `col` being selected or proposed? VS Code compares the text left of the cursor with the completions and picks the *best match*. One issue is that shouldn't be html snippets inside the CSS-part of the document. 

In your sample `col` is the best match but because snippets are sorted to the bottom and the rest is sorted alphabetically you don't see `color` yet (but it will match when continuing to type). You can change the sort-order (`"editor.snippetSuggestions": "inline"`) and/or continue typing

**Comment by Reedo0910** [comment]
@jrieken Thank you. `col` will be proposed in this sample. and yes, i mean that there shouldn't be html snippets inside the CSS-part of the document, that's really annoying.
