### ISSUE TITLE
Test merge editor

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#150389]
Refs: https://github.com/microsoft/vscode/issues/146091

- [x] anyOS @mjbvz
- [x] anyOS @karrtikr
- [x] anyOS @bpasero 

Complexity: 4

Authors: @hediet @jrieken 

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23150389%0A%0A&assignees=jrieken,hediet)

---

**I forgot to merge a reviewed PR on time that includes important bug-fixes. Please test this on Wednesday**

This milestone work on a merge editor has started. You are testing something very fresh, please be forgiving :-). The merge editor is an editor that takes a two conflicting version of one file, compares them against their common ancestor, and helps to create a conflict-free result. Before testing make sure

* enable the merge editor with `git.experimental.mergeEditor`
* have a merge a GIT conflict; you can use this sample repo: XYZ

---

The flow is: open the git viewlet, open a conflict from the "Merge Changes" group, use the editor to realise and resolve conflicts, use "Accept Merge" to stage the file and close the merge editor. In detail, test that

* the editor shows _yours_ and _theirs_  and below that shows the current _result_
* the editor layout can be toggled to a column mode from its toolbar (the _result_ editor is than in the middle)
* the editors for _yours_ and _theirs_ shows the branch names and commits
* you can type in the _result_ editor but not the other editors 
* when typing in the results editor, the merge editor becomes dirty
* you can reload the workbench and the merge editor is restored
* you can open the result-file in a "normal" editor and edit the file there as well
* you can select "Accept Merge" so that the file is staged and the merge editor is closed

**Comment by omermizr** [comment]
Hey, not sure if this is the place to give feedback for this but here's what I found so far:

1. My layout selection is not saved. 
2. Search doesn't work. 
3. "Go to next change" (I think it's option-F5 on a Mac) doesn't work. 
4. Undo behavior is weird. I have to click on the "resolved" editor and only then it works. Also, when I do that it loses its highlighting. 
5. In general, it would be great to have this view fully operational with a keyboard (for instance, right now I can't seem to switch between the editors, and I can't choose how to resolve a conflict). 

Other than that, this is a great addition!
Thanks!

**Comment by bpasero** [comment]
@omermizr thanks for testing, for best outcome of your feedback I suggest to file 1 issue per issue you found.

**Comment by bpasero** [comment]
Very cool ❤️

**Comment by mjbvz** [comment]
Very cool work!

As general feedback, I liked the feature but found a few things confusing:

1. Intuitively I expected the merge editor to not touch the file being merged until I hit `accept merge`. 

1. I also expected a way to reset the current merge so I could go back to the original state. This doesn't seem possible as the editor is changing the file being merged

1. I was confused by what the circles meant inside the checkboxes (these mean you've manually edited the result but I think we can explain these better)

1. I was confused by what happens when both checkboxes for a conflict are checked. I expected this to accept both but it never seemed to work as I expected
