### ISSUE TITLE
[theme] Monokai theme: parameters are not colored in Orange

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#1504]
Extracted from issue #1470.

I am using Monokai, where function parameters are displayed in orange, but with this update the parameters are displayed in gray although the Monokai.tmTheme clearly states that parameters should be orange (#FD971F).

**Comment by egamma** [comment]
The same problem occurs in TS.

**Comment by lcrespom** [comment]
I just installed version 0.10.6, commit a80232bb, and parameters are still gray.
Does commit a80232bb contain this fix?

I opened tokens.css in C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\languages\markdown\common and searched for ".token.meta.parameter", and it's not there, so it seems the fix is in this commit, but the monokai theme is still broken.

**Comment by aeschli** [comment]
0.10.6 is the December release. You will see this in te January release due January 29.
See https://github.com/Microsoft/vscode/issues/1826

**Comment by lcrespom** [comment]
Thank you, I eagerly wait for that release :-)
