### ISSUE TITLE
OUTLINE: No symbols found in document xyz.cs

### ISSUE THREAD

**Issue by rkb-ravi** [microsoft/vscode#150406]
Issue Type: <b>Bug</b>

Opening any C# file is not showing OUTLINE info but message: No symbols found in document xyz.cs
Also on editor window it is not showing code context menu like Go to Definition, Show References etc.

VS Code version: Code 1.67.2 (c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5, 2022-05-17T18:15:52.058Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|12.0.7
vscode-solution-explorer|fer|0.4.5
vscode-edit-csv|jan|0.6.10
docomment|k--|0.1.31
labeled-bookmarks|koa|1.1.10
mongodb-vscode|mon|0.9.3
vscode-dapr|ms-|0.6.0
vscode-docker|ms-|1.22.0
csharp|ms-|1.25.0
vscode-kubernetes-tools|ms-|1.3.9
hexeditor|ms-|1.9.6
back-n-forth|nic|3.1.1
vscode-yaml|red|1.7.0
vscode-taskexplorer|spm|2.9.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdf:30486550

```

</details>

**Comment by jrieken** [comment]
It looks like the issue is caused by one of your installed extensions. All extensions execute together on a single nodejs process, so in order to narrow down the possible problematic extension, please try the following:
* run `F1 > Help: Start Extension Bisect`
* (this will restart VS Code with half of your extensions disabled)
* try to do the steps which reproduce the problem
* if the problem reproduces, click "This is bad" (this narrows down the problematic extension to the half which was enabled)
* if the problem does not reproduce, click "Good now" (this narrows down the problematic extension to the half which was disabled)
* these steps will repeat until the problematic extension is found

| initial | step | final |
|---|---|---|
| ![image](https://user-images.githubusercontent.com/5047891/101918658-e9170f80-3bc9-11eb-9977-857baa291937.png) | ![image](https://user-images.githubusercontent.com/5047891/101918683-ef0cf080-3bc9-11eb-9f9e-98b0177991b2.png) | ![image](https://user-images.githubusercontent.com/5047891/101918706-f502d180-3bc9-11eb-8c86-e56355958bd4.png) |

**Comment by rkb-ravi** [comment]
Thanks for your suggestion @jrieken 
I did extension Bisect and in step 1 all extensions were disabled, but still problem persisted. 
![Capture](https://user-images.githubusercontent.com/12062275/170418100-56defe51-3cdc-44cf-b8c4-f2107a90b66b.PNG)
.
Bisect reported that there is problem in Code 
![VSCodeIssue2](https://user-images.githubusercontent.com/12062275/170418350-497a40cc-c7d8-4729-bc3c-9dde244622b5.PNG)

**Comment by ondesic** [comment]
I am having the same problem.  For me it Started with the latest VS Code.  Now all of my outlines are gone for each .cs file

**Comment by rkb-ravi** [comment]
Finally found the solution.
Downgrading C# extension to 1.24.4 worked.
Its a problem with C# 1.25.0 update that caused problems with outlines; which also caused problem with C# editing support, including Syntax Highlighting, IntelliSense, Go to Definition, Find All References, etc. Downgrading to previous version, solved these issues :)

**Comment by rkb-ravi** [comment]
Raised issue in omnisharp-vscode repo https://github.com/OmniSharp/omnisharp-vscode/issues/5245#issue-1252288868
