### ISSUE TITLE
Hitting CTRL + S to save a file wont change "dirty" icon in the file TAB.

### ISSUE THREAD

**Issue by cristianorvf** [Microsoft/vscode#15046]
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:46:00.226Z)
- OS Version: Darwin x64 15.5.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.1|

---

Steps to Reproduce:

1. Open any file (tested with HTML and JS , but dont think it matters)
2. Make any change
3. Hit CTRL + S, the file is saved (can be checked externally .. it really saves the content)
4. VS Code wont change the circle icon (dirty) of that file
5. Hit CTRL + S AGAIN, the icon backs to normal "x"

Also, if you try to close the file it keeps nagging "Its not saved, are you sure ..."

[vscode-bug-save.mov.zip](https://github.com/Microsoft/vscode/files/573357/vscode-bug-save.mov.zip)

**Comment by bpasero** [comment]
@cristianorvf 
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by cristianorvf** [comment]
@bpasero You are right. Its the JS-CSS-HTML Formatter 0.2.1 that is causing this, disabled it and worked gain.

The thing is, now i have no formatting working for JS (as the other issue opened #15010) :(

Thanks

**Comment by bpasero** [comment]
@cristianorvf this should be reported to them. would you mind filing it against them?

/cc @jrieken

**Comment by cristianorvf** [comment]
@bpasero yes, its already there (and for months ..) https://github.com/Lonefy/vscode-JS-CSS-HTML-formatter/issues/28

Thanks!
