### ISSUE TITLE
Shouldn't `files.excludeGitIgnore` hide a folder that contain a self-ignoring `.gitignore` file?

### ISSUE THREAD

**Issue by bersbersbers** [microsoft/vscode#150441]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Version: 1.68.0-insider (user setup), Commit: d891b49fc0f8fc5e00591657ca225975952b09ca

Follow-up to https://github.com/microsoft/vscode/issues/38878#issuecomment-1137348839, @lramos15

Steps to Reproduce:

1. Use `pytest` or `mypy` in your Python project.
2. Set `"files.excludeGitIgnore": true`
3. Notice that `.mypy_cache` and `.pytest_cache` folder are not hidden, although both of them have a `.gitignore` file which says to ignore everything in that folder, respectively.

![image](https://user-images.githubusercontent.com/12128514/170428787-a27594b0-4926-4124-a1ca-a740ddf77efa.png)

IMHO, these folders could/should be hidden completely.

**Comment by lramos15** [comment]
This appears expected to me
1. `.gitignore` files only trickle down meaning it effects what is in the directory + what is  in the sub directories below it. This means the parent folder wouldn't be hidden anyways
2. We decided not to hide the `.gitignore` file itself since it's really difficult to get back. 

If you move your `.gitignore` to the root and add `.mypy_cache` and `.pytest_cache` that should work.
