### ISSUE TITLE
Terminal links don't follow line numbers in nested directories on WSL

### ISSUE THREAD

**Issue by Dzejkop** [microsoft/vscode#150564]
Does this issue occur when all extensions are disabled?: Yes (but with Remote WSL enabled)

- VS Code Version: 1.67.2
- OS Version: Windows 10 (but running inside WSL2, WSL os is `Ubuntu 20.04.4 LTS on Windows 10 x86_64`)

Steps to Reproduce:

1. Open VSCode inside an empty directory
2. Create a nested directory `nested_dir`
3. Create a file inside that directory `nested_dir/file.txt` with content
  ```
Line 1
Line 2
Line 3
  ```
4. In terminal write `echo "file.txt:2"`
5. ctrl+click the terminal link
6. VSCode will open the file, but cursor will be at the beginning

If the terminal link is `nested_dir/file.txt:2` then terminal link follow will work fine.

The issue also doesn't occur if running outside of WSL.

**Comment by Dzejkop** [comment]
https://user-images.githubusercontent.com/5088647/170780242-0a3330ed-a25a-4355-8608-60c09070482f.mp4

**Comment by Dzejkop** [comment]
Also interestingly if I use the ctrl+p to go to a file with `some_file.txt:2` it'll go to the second line correctly

**Comment by Dzejkop** [comment]
I'm willing to try and fix this if you can give me some pointers

**Comment by Tyriar** [comment]
Some work has happened with links in the upcoming version so we need to verify if this can be reproduced on insiders.

@Dzejkop if you want to take a stab at it you can create a test resolver with this command when building Code - OSS ([instructions](https://github.com/microsoft/vscode/wiki/How-to-Contribute)):

![image](https://user-images.githubusercontent.com/2193314/171919033-d661842a-6e62-468c-a51b-6b0b23033196.png)

That window will be a similar environment to WSL, since the path doesn't contain any `/` or `\` it will probably happen there, ie. it's not in the class of problems that comes with a Linux connected window on a Windows front end.

Code pointers to the likely code that detects this link:

https://github.com/microsoft/vscode/blob/b118105bf28d773fbbce683f7230d058be2f89a7/src/vs/workbench/contrib/terminal/browser/links/terminalLocalLinkDetector.ts#L86
https://github.com/microsoft/vscode/blob/b118105bf28d773fbbce683f7230d058be2f89a7/src/vs/workbench/contrib/terminal/browser/links/terminalWordLinkDetector.ts#L38

This file contains where opening is handled:

https://github.com/microsoft/vscode/blob/aa511389cce561e4ef32e360d9073eea196f0395/src/vs/workbench/contrib/terminal/browser/links/terminalLinkOpeners.ts

**Comment by Tyriar** [comment]
This works for me now 🎉
