### ISSUE TITLE
PHP - MySQL syntax highlighting with leading line break

### ISSUE THREAD

**Issue by nrbrttth** [microsoft/vscode#150516]
MySQL syntax highlighting breaks in PHP when a leading line break is included.

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.67.2
- OS Version: macOS Monterey 12.3.1

Steps to Reproduce:
1. Write a MySQL string with a leading line break.

Working:
![Screenshot 2022-05-27 at 10 03 13](https://user-images.githubusercontent.com/23727847/170657852-7810f07a-0e34-4569-a8ae-01ef379dd284.png)
![Screenshot 2022-05-27 at 10 04 47](https://user-images.githubusercontent.com/23727847/170658077-10447249-eb0c-42e4-92e8-11914ec74caa.png)
![Screenshot 2022-05-27 at 10 05 13](https://user-images.githubusercontent.com/23727847/170658149-20e0e876-5c99-4a5f-8eaf-a67eeb0045aa.png)

Not working:
![Screenshot 2022-05-27 at 10 05 31](https://user-images.githubusercontent.com/23727847/170658194-31c73767-5aa1-4505-8496-536105030ee7.png)

**Comment by mauricekindermann** [comment]
I would love to see this fixed, I've come from Sublime which doesn't have this problem. All my code is setup so that the mysql is on a line break after the quote tag, so every single file I look at I need to first edit the quote tag and fiddle with the mysql indents before I can even see the highlighting.

**Comment by roblourens** [comment]
Closing for the upstream issue and https://github.com/microsoft/vscode/issues/162707
