### ISSUE TITLE
Code lens not working

### ISSUE THREAD

**Issue by dylanspin** [microsoft/vscode#150540]
Didn't change anything started up pc yesterday. Opened vs code and for some reason, I'm not getting code lense anymore. I tried a lot from turning it first on and of, restarting pc, Updating vs code, and Changing editor in unity back and forth. resetting all settings, Reinstalling vs code. Restarting pc again.

But nothing helped and I'm very dependent on code lens for unity development. I tried looking up a lot but nobody seems to have this with vs code only in vs studio. So I can't find anything that can help. 

It's strange that after 3 years of always having it worked out of nowhere it stopped.

**Comment by dylanspin** [comment]
I have been trying to fix it now for 2 days sadly nothing worked... Hope to get help with this.

**Comment by jrieken** [comment]
It looks like the issue is caused by one of your installed extensions. All extensions execute together on a single nodejs process, so in order to narrow down the possible problematic extension, please try the following:
* run `F1 > Help: Start Extension Bisect`
* (this will restart VS Code with half of your extensions disabled)
* try to do the steps which reproduce the problem
* if the problem reproduces, click "This is bad" (this narrows down the problematic extension to the half which was enabled)
* if the problem does not reproduce, click "Good now" (this narrows down the problematic extension to the half which was disabled)
* these steps will repeat until the problematic extension is found

| initial | step | final |
|---|---|---|
| ![image](https://user-images.githubusercontent.com/5047891/101918658-e9170f80-3bc9-11eb-9977-857baa291937.png) | ![image](https://user-images.githubusercontent.com/5047891/101918683-ef0cf080-3bc9-11eb-9f9e-98b0177991b2.png) | ![image](https://user-images.githubusercontent.com/5047891/101918706-f502d180-3bc9-11eb-8c86-e56355958bd4.png) |
