### ISSUE TITLE
Full auto indent not working

### ISSUE THREAD

**Issue by temocj** [microsoft/vscode#150639]
Issue Type: <b>Bug</b>

Full auto indent does not appear to work as described.

<img width="603" alt="full-auto-indent-enabled" src="https://user-images.githubusercontent.com/68073709/170870432-47351e5d-bfd9-4318-af95-7d5dbf68d42d.png">

https://user-images.githubusercontent.com/68073709/170870436-3e11a948-1601-4535-abaf-08a0846f82df.mov

The same code typed out by hand is automatically indented correctly.

The code is:

```swift
func f()
    // foo
}
```

and then copied and pasted inside of itself.

The result is:

```swift
func f()
    // foo
    func f()
    // foo
}
}
```

My expectation is:

```swift
func f()
    // foo
    func f()
        // foo
    }
}
```

Does this issue occur when all extensions are disabled?: Yes

VS Code version: Code 1.67.2 (Universal) (c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5, 2022-05-17T18:20:57.384Z)
OS version: Darwin arm64 21.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|16.00GB (1.95GB free)|
|Process Argv|--crash-reporter-id 1f16c0d1-50db-46da-9cdc-0eee94227323|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
swift-lang|ssw|0.5.3
vscode-lldb|vad|1.7.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdc:30486549

```

</details>

**Comment by lukaszpolowczyk** [comment]
I have the same problem.

I always have a confusion in my head.
I never know if the auto indent will work or not work this time.

---

The culprit is probably that it pastes into a line where there is already an indent.
At the same time, the pasted code has no indent in it.
And this combination is causing the strange behavior.

**Behavioral versions:**

Indent in the line to which you paste, no indent in the pasted code - bug:


https://user-images.githubusercontent.com/16800535/189414458-43d341fe-9e7f-42a2-b413-8fe63d98d0b2.mp4

But here:
* No intent in the line to which you paste, no indent in the pasted code - no bug:
* Indent in the line to which you paste, indent in the pasted code - no bug:

https://user-images.githubusercontent.com/16800535/189414693-28def7f2-b86b-49b1-8884-aeb3758720e9.mp4

This is definitely a bug, and it needs to be corrected.

**Comment by muchisx** [comment]
I have had this issue for forever too and do not know how to solve it !

**Comment by rebornix** [comment]
Currently the auto indent feature in VS Code is regex based, which doesn't really understand the scope (function, statement) etc. Formatting works more consistently in this scenario, so I would recommend to enable formatting on type or save. Closing this as we don't expect to get around it in the near future.
