### ISSUE TITLE
VSCode ThemeIcon no longer picking up an installed Iextension con theme pack for folder and file

### ISSUE THREAD

**Issue by davidkjackson54** [microsoft/vscode#150610]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.67.2
- OS Version: Windows 10

Steps to Reproduce:

I have a VSCode extension that has worked for over a year.  This extension displays a TreeView and I make use of the Material Icon Theme package.  I simply want to display an icon for Folders and Files - nothing particularly fancy.

My code simply contains this :
`this.iconPath = new vscode.ThemeIcon("folder");`

This has worked fine for well over the past year. The only change is to regular VSCode installs of new releases as they become available.

However, now the icons that are now being displayed in the tree appear to be the codicon icons for each of folder and file and not the icons from Material Icon Theme. 
VSCode itself is using the Material Icons theme - but my Treeview extension is  no longer displaying the Material Icons for folders and files,  
I added these 2 lines to show  that the Material Icon theme is active. 
```
const config = vscode.workspace.getConfiguration();
console.log(config.workbench.iconTheme); // Correctly displays => material-icon-theme
```

In the past simply specifying 
`this.iconPath = new vscode.ThemeIcon("folder");`
was sufficient to get the the theme icon to be presented.

I have searched recent VSCode documentation to see if something has changed in this area but I find nothing.

Can anybody offer any suggestions as to what may have changed?

**Comment by davidkjackson54** [comment]
I have found that adding this line
`this.resourceUri = Uri.parse('_.js');`
appears to resolve the problem but it was not previously necessary over the past 12+ months.
I have no clue as to what this line accomplishes and it seems any value - even a blank value between the ( ) works.

**Comment by alexr00** [comment]
@davidkjackson54 since Material Icon theme is a file icon theme, we only use the icons from the theme when the tree item looks like a file (has a `resourceUri`). 

This is a recent change that came about because we weren't showing folder icons in extension trees when the file icon theme showed no folders (https://github.com/microsoft/vscode/issues/146479) and we needed to come up with a consistent way to determine which icon to show. Does this seem like a reasonable approach to you?

**Comment by davidkjackson54** [comment]
I think that is reasonable. However, in my case the file 'extension' is pretty much meaningless. I simply use Material Icon theme to give me just plan folder and  a plain file icon. To get around thisI imply now do this:
```
this.iconPath = vscode.ThemeIcon.Folder;
this.resourceUri = vscode.Uri.parse("_.dummy")
```
or
```
this.iconPath = vscode.ThemeIcon.File;
this.resourceUri = vscode.Uri.parse("_.dummy")
```
I don't know if there is a more preferred option to accomplish this.

**Comment by alexr00** [comment]
@davidkjackson54 now that we only use the file icon theme for files/resources your workaround is the only way to force the file icon theme to be used instead of the codicon. 

Since we need a consistent way to explain when the file icon theme will be used and when it will not, I am inclined to keep things as they are (file icon theme will only be used when the tree item has a `resourceUri`). Changing the product icons (non-file icons) is  also now possible with https://github.com/microsoft/vscode/issues/119101.
