### ISSUE TITLE
Unmaintained Jinja extension

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#150743]
5yr old extensions with 3.7MM downloads: https://marketplace.visualstudio.com/items?itemName=wholroyd.jinja .

Seems like https://marketplace.visualstudio.com/items?itemName=samuelcolvin.jinjahtml could be a drop-in, but not 100% sure.

cc @luabud for python perspective

**Comment by isidorn** [comment]
@digitarald good catch. I have opened this issue https://github.com/wholroyd/vscode-jinja/issues/37 and this one https://github.com/samuelcolvin/jinjahtml-vscode/issues/108

Let's see what they say :)

**Comment by wholroyd** [comment]
I figured I would respond here as this is closer to where my issue is located. While I haven't touched it in a while, it's not because the Jinja parsing is problematic, but the integration with other languages has issues. You either have to choose Jinja or the other language - but using both is not supported anymore (but worked in early VScode versions).

The syntax files for Samuel's extension and mine for YAML are almost identical as an example.

https://github.com/samuelcolvin/jinjahtml-vscode/blob/master/syntaxes/jinja-yaml.tmLanguage.json
https://github.com/wholroyd/vscode-jinja/blob/master/syntaxes/jinja-yaml.json

If you notice with Samuel's extension, it implies in the README that people have to adapt to the extension by changing your file extensions for it to work, instead of just working. While his may work perfectly the way it is, I think it's an anti-pattern to the developer experience to change your file extensions, and for Samuel himself to have to maintain a separate file for every language someone wants to plop Jinja into seems cumbersome.

The VScode team has been challenging when it comes to extension authors that have to deal with multiple languages without having to reinvent a language syntax. As an example of what I mean, I've been following the PHP series of issues because it also needs to be embedded into other languages as well.

https://github.com/microsoft/vscode/issues/670
https://github.com/microsoft/vscode/issues/2915

One large difference is that PHP files will always be known as *.php and the other language is just noise around what needs to be processed. In the case of Jinja, the opposite is true where file extensions is from the other language and Jinja is along for the ride. The ability to detect and inject Jinja recognition into other languages regardless of file extension is the ideal scenario if there was a way for us to tell VScode when you see X used, then load me as it's most likely Jinja being used.

I can't tell you how often I've opened a file with a particular extension where VScode has suggested a marketplace extension that could help, why can we not do the same if we could provide a hint for VScode to detect a given language and suggest integration?

I paused development when I saw the suggestion at the time was to write a language server to handle the switching. I wouldn't mind picking it back up if there was a clearer path, otherwise it takes a lot of time and I know Samuel has called out time availability.

Let me know your thoughts, give me some insight into what has changed recently, and help me help developers.
