### ISSUE TITLE
Merge editor: cannot bring back merge markers when checking then unchecking box

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#150809]
Testing #150389

![Recording 2022-05-31 at 12 23 17](https://user-images.githubusercontent.com/900690/171152547-aef1d90e-9913-4115-abb0-9e4e99c520de.gif)

I think I would have expected to be able to get back to how it was.

**Comment by hediet** [comment]
You can use "undo" in the result editor.

The idea is that unchecking a checkbox removes the input 1/2 diff from the result and doesn't restore what has been there before.

When you try out on latest main (forgot to merge the PR yesterday), you can see a circle symbol instead of an unchecked checkbox to indicate that the diff is in conflicting state.
