### ISSUE TITLE
Wrong language detection

### ISSUE THREAD

**Issue by john-cj** [microsoft/vscode#150873]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.67.2
- OS Version: win7

Steps to Reproduce:

1. Create a new tab
2. Copy there the following text: `ренессанс страхование обращайтесь в автосалон`
3. For some reason, VS code thinks this is an INI file and changes the language accordingly.

**Comment by OdairRos** [comment]
Good afternoon.
I think that is a problem with the  extensions because here i teste with none extensions and no make this problem, please check you, desative all extensions and test again.

![2022-05-31_16h18_13](https://user-images.githubusercontent.com/84051161/171267813-8bfa21e1-816a-4e68-85da-0fdac6bfe708.png)

**Comment by TylerLeonhardt** [comment]
I can repro this. @OdairRos you need to use an untitled file not a file on disk. I am including this sample in the meta issue: https://github.com/microsoft/vscode/issues/131450 which is used to track these kinds of issues
