### ISSUE TITLE
`terminal.integrated.minimumContrastRatio` not applied to terminal decorations

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#150911]
Testing #150554

1. Set `"terminal.integrated.minimumContrastRatio": 21` in settings.json
2. Have no customizations for the color of the decorations (at least I don't see any customizations in my settings.json file)
3. All other text in the terminal has the contrast ratio applied, should the decorations match the cell foreground color too?

![image](https://user-images.githubusercontent.com/30305945/171284511-b95aa717-e514-4c90-9c60-f0167f4f1013.png)

**Comment by Tyriar** [comment]
Generally we should rely on themes to do the right thing here, for the terminal character grid there can be incompatibilities between the shell/pty/theme which makes text unreadable so we take some liberties there. We need to draw the line somewhere and since a theme fully controls the decoration color and its background it's safe to leave as is. This would also be a bit ugly in code and causes a layer issue in a sense as the contrast code is internal code in xterm.js but the decoration DOM element is in VS Code.
