### ISSUE TITLE
Unnecessary dialog when installing a language pack

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#150955]
Testing #150567

Things I would change:

- make it clear in the picker that selecting a language from the lower list will install it
- have a button in the picker that installs and syncs it.
- don't reveal the extension viewlet
- don't show that dialog

<img width="444" alt="capture" src="https://user-images.githubusercontent.com/1931590/171370281-6bb381be-1759-4b3b-9b05-23841bb3f663.png">

**Comment by TylerLeonhardt** [comment]
@dbaeumer 

> make it clear in the picker that selecting a language from the lower list will install it

How would you make this clearer? I figured since we had a section called `Installed languages` that will always be there on Desktop it's implied that `Available Languages` must not be installed.

> have a button in the picker that installs and syncs it.

What will the default behavior be then when you accept a quick pick item? That it will install but not sync? That's not what the default is for the `Install` button in the extension pane so that seems a bit odd to me.

> don't reveal the extension viewlet

This was to give a progress indication. We do the same thing for the Theme picker.

> don't show that dialog

👍 I would like to hide this dialog. I didn't see it locally because Settings Sync isn't available in `Code - OSS` but I asked Sandeep above.

**Comment by dbaeumer** [comment]
@TylerLeonhardt 

> How would you make this clearer? I figured since we had a section called Installed languages that will always be there on Desktop it's implied that Available Languages must not be installed.

I thought the main reason for the dialog was to inform the user that something is installed. I can easily live with only the picker

> What will the default behavior be then when you accept a quick pick item? That it will install but not sync? That's not what the default is for the Install button in the extension pane so that seems a bit odd to me.

Since the dialog offered the option, I thought it is important. I can live with the default without a choice. 

> This was to give a progress indication. We do the same thing for the Theme picker.

I found it disturbing. I could live without progress or some window progress.
