### ISSUE TITLE
Can the notebooks "run number" not flicker on run?

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#150924]
Testing https://github.com/microsoft/vscode-jupyter/issues/10170

A lot of flickering goes on when executing a cell, can the number in [] not get its text cleared and instead go from [5] to [6] for example to minimize flickering?

![Recording 2022-05-31 at 15 39 49](https://user-images.githubusercontent.com/2193314/171295711-f805ad9c-199c-4334-b665-4808022e1dee.gif)

**Comment by roblourens** [comment]
We clear the execution order when execution starts, and jupyter itself does not provide the new execution order until slightly after execution starts. All I can think of is doing something on the rendering side, like wait a bit to render a cleared execution order?

**Comment by sangnguyen696969** [comment]
``

**Comment by rebornix** [comment]
Found it annoying while testing https://github.com/microsoft/vscode-jupyter/issues/10598. Not that in the video, I was dragging an ipywidgets slider, which somehow is updating execution status. Though it didn't really increment the execution count, it kept flickering. 

https://user-images.githubusercontent.com/876920/176246736-3ed9921d-3cc1-44c1-ba8c-f5cee17d2b2c.mov

It's also annoying to see the spinner.

**Comment by roblourens** [comment]
I wonder if that is related to creating a fake execution to update an output

**Comment by roblourens** [comment]
To summarize since this goes on the plan, two related issues:

- Blinking when doing normal execution due to updating the execution count async
- Blinking and showing running state when updating outputs with the "fake" execution object. I'm not sure what we will be able to do about the running state - we even have code that specifically ensures that if the cell enters the running state, it should show the running indicator for some minimum amount of time

**Comment by roblourens** [comment]
So far I have

- Fixed an issue with the extension using temp executions unnecessarily, so for the original report it doesn't blink anymore
- Fixed some unnecessary blinking for normal executions

However, it's hard to avoid this for actual fake executions, because since this is a workaround for our API, it's not really clear how to detect this and treat them differently.

We've said that we want an execution to show the progress spinner for a minimum time, 500ms, so that you can definitely tell in the UI that an execution happened, even if it is very fast. So then even if an execution is created and completed within the same js task, we will still show the progress spinner. This is good for fast normal executions and not good for "fake" executions.

We could say that an execution that is completed immediately does not get the spinner at all, but I don't like that because it could hurt some simple kernel that doesn't need to do any async work as part of an execution.

**Comment by roblourens** [comment]
For future reference, here is a snippet that does a "fake" execution to update outputs outside of an execution.

```py
from ipywidgets import interact, interactive, fixed, interact_manual, widgets

caption = widgets.Label(value='The values of slider is : ')
slider = widgets.IntSlider(min=-5, max=5, value=0, description='Slider')

def handle_slider_change(change):
    print(change)
    caption.value = 'The values of slider is : ' + str(change.new)

slider.observe(handle_slider_change, names='value')

display(caption, slider)
```

**Comment by roblourens** [comment]
Interesting, I hadn't realize this - `print` in the snippet above in vscode adds outputs to the cell. In Jupyter lab, it actually writes to a different log instead of adding outputs to the cell.

To understand this usecase I'm looking for an example that updates the output in jupyter lab outside of an execution - I remember there was one which I think involved subprocess, but I can't find an example anywhere. Wondering whether you have one handy @DonJayamanne

**Comment by roblourens** [comment]
Verification steps:

- No flickering of the execution order or timer in a normal execution of a cell in a Jupyter notebook
- No flickering when changing the slider with this code:

```py
from ipywidgets import interact

def func1(x):
    return 5*x
interact(func1, x=10);
```

- Some other ipywidget scenarios will still produce flickering from "fake executions", this is probably not solvable without API changes. Discovered that it's actually not working as expected in some other cases and so it could get more investigation later.

**Comment by DonJayamanne** [comment]
Verified
