### ISSUE TITLE
Dendron extension fails to initialize

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#151012]
Testing #150753

[Dendron](https://marketplace.visualstudio.com/items?itemName=dendron.dendron)

<img width="348" alt="image" src="https://user-images.githubusercontent.com/6561887/171472581-bf096fb0-1b75-4e3b-8128-d338ae6a4913.png">

**Comment by deepak1556** [comment]
Extension fails to launch child_process during initialization

```
{"level":30,"time":1654688773177,"pid":37008,"hostname":"Deepaks-MacBook-Pro-2.local","name":"execServer","state":"enter"}
{"level":30,"time":1654688773180,"pid":37008,"hostname":"Deepaks-MacBook-Pro-2.local","name":"execServer","state":"post:exec.node"}
{"level":50,"time":1654688774157,"pid":37008,"hostname":"Deepaks-MacBook-Pro-2.local","name":"execServer","state":"disconnect"}
{"level":50,"time":1654688774163,"pid":37008,"hostname":"Deepaks-MacBook-Pro-2.local","name":"dendron","name":"DendronError","status":"unknown","payload":"{}","stack":"DendronError: disconnect\n\tat ChildProcess.<anonymous> (/Users/demohan/.vscode-insiders/extensions/dendron.dendron-0.98.0/dist/extension.js:2:98783)\n\tat ChildProcess.emit (node:events:390:28)\n\tat ChildProcess.emit (node:domain:475:12)\n\tat finish (node:internal/child_process:902:14)\n\tat processTicksAndRejections (node:internal/process/task_queues:78:11)","type":"Error","msg":"disconnect"}
{"level":50,"time":1654688774165,"pid":37008,"hostname":"Deepaks-MacBook-Pro-2.local","name":"dendron","ctx":"showInitProgress","msg":"issue initializing Dendron"}
{"level":50,"time":1654688774305,"pid":37008,"hostname":"Deepaks-MacBook-Pro-2.local","name":"execServer","state":"exit"}
{"level":50,"time":1654688778529,"pid":37008,"hostname":"Deepaks-MacBook-Pro-2.local","name":"execServer","state":"close"}
```

https://github.com/dendronhq/dendron/blob/66867fd693934afceced5e55932eeb80778eed53/packages/api-server/src/utils.ts#L191-L219

Will check if the issue is isolated to this extension with a minimal example using `execa` module

**Comment by deepak1556** [comment]
Was able to isolate the issue, firstly as pointed above the extension makes an attempt to launch a child process via the `execaNode` helper https://github.com/sindresorhus/execa/blob/071d0a282a14633493e9d8b4e5b686c43da64368/index.js#L237-L267 which basically emulates `child_process.fork` options and passes them eventually into `child_process.spawn` https://github.com/sindresorhus/execa/blob/071d0a282a14633493e9d8b4e5b686c43da64368/index.js#L84

Since `execaNode` variant relies on `process.execPath` when node executable path is not provided, this will default to use the Electron executable that is used to create the extension host. Now there are two problems with this usage,

(i) execa module will not add the `ELECTRON_RUN_AS_NODE` env variable, so the exectuable cannot be launched as intended.
(ii) We also disable calling Electron executable as `ELECTRON_RUN_AS_NODE` unless `--ms-enable-electron-run-as-node` flag is provided in the call site.

For the (ii) we automatically add the flag at both `child_process.spawn` and `child_process.fork` callsites internally in the runtime, so this should not be a concern for the extension authors.

As for (i), if the extension author used the vanilla `child_process.fork` then the env variable would be set internally by the runtime. But since the call is done via a 3rd party module, I think it is upto the extension authors to ensure the env variable is provided if they rely on the Electron executable.

I feel like there is no action required from runtime/VSCode core for this issue, but we should loop in the extension author to fix this on their end. Thoughts @alexdima @bpasero ?

**Comment by bpasero** [comment]
So what exactly is different in the utility process vs. child process today? I did not fully understand.

**Comment by deepak1556** [comment]
When extension host is created via `child_process.fork`, internally the runtime would launch the process with `ELECTRON_RUN_AS_NODE` env variable set and we never remove this variable explicitly in the extension host after launch (i-e) `delete process.env['ELECTRON_RUN_AS_NODE']`, this would indirectly help above scenarios since the env gets inherited by extensions. This is not the case with utility process since there is no runtime induced `ELECTRON_RUN_AS_NODE` env variable, the extensions have to explicitly add them if they rely on the electron executable. I would say the previous behavior was a hidden bug and is visible now with the utility process api.

**Comment by bpasero** [comment]
Oh yeah understood! I think I somewhat agree that we need to just document this to extension authors.

**Comment by deepak1556** [comment]
@kevinslin yup that is correct.

> set ELECTRON_RUN_AS_NODE when using the execa module

To clarify, only when `execa` ends up using `process.execPath` on the desktop extension host.

**Comment by kevinslin** [comment]
Got it. What's the timeline for us patching this? Is this already live in
insider?

**Comment by deepak1556** [comment]
@kevinslin after discussing with the team, we have decided to push a workaround in core to avoid breaking the extension community with the new process type for extension host. You don't need to make the adjustments outlined in https://github.com/microsoft/vscode/issues/151012#issuecomment-1156819920
