### ISSUE TITLE
Label provider memento

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#151067]
@connor4312 some feedback:
* `memento` was mainly introduced for workbench components to extend from, in most cases just using storage service directly should be fine
* what is the lifecycle of these cached formatters, are they cleaned up? do they update? what if I uninstall an extension?
* the `StorageTarget.User` means that this cache will sync with settings sync, it should probably not?
* I would have rather expected a boolean flag added to `registerFormatter` for deciding whether the formatter should be cached or not
* should all formatters be cached maybe?

@isidorn do you know who owns label service formatters these days? I think you had them in the beginning and then passed on?

_Originally posted by @bpasero in https://github.com/microsoft/vscode/issues/148850#issuecomment-1139318700_

**Comment by bpasero** [comment]
//cc @Tyriar

**Comment by Tyriar** [comment]
See https://github.com/microsoft/vscode/issues/150970, https://github.com/microsoft/vscode/pull/150987

**Comment by connor4312** [comment]
The use of a memento was fixed in https://github.com/microsoft/vscode/pull/151236

> should all formatters be cached maybe?

Yes, they should. Both open recent and workspace trust can show labels of remotes even when they aren't connected. Open recent sort of worked before by using the label formatter in (for example) SSH's package.json, but this was lower fidelity than the one registered programmatically when the extension was activated.

In the cases of vscode.dev's "anything" route, the tunneling extension isn't even known when not on the route. Later on, we might have it be built-in on vscode.dev, but it is still difficult to create a nice label without increasing complex format templates -- which was the approach I had initially started taking in https://github.com/microsoft/vscode/pull/148850.

It seemed that caching label formatters was a better all around approach. All remote extensions have formatters that precisely target a remote corresponding to a single machine, so my thinking is that a cache of the most recent 50 formatters is safe and sufficient.
