### ISSUE TITLE
Display breakpoints in scrollbar

### ISSUE THREAD

**Issue by jez9999** [microsoft/vscode#15104]
It would be nice to see at-a-glance where breakpoints have been set in a code file.  They could be displayed in red the scrollbar area, like "changed/added code lines" are currently shown in blue.

**Comment by isidorn** [comment]
This was already done a year ago and the team hated ti since the red was reminding them of errors. Assigning to @bgashler1 to consider this

I am -1 for this feature

**Comment by jez9999** [comment]
Well then make the colour configurable or something.  Visual Studio does it, and I regularly find myself wanting to quickly see where breakpoints are in a file.

**Comment by jez9999** [comment]
This is how regular Visual Studio shows things (it uses maroon for breakpoints, red for errors):

![vsscrollbar](https://cloud.githubusercontent.com/assets/793830/20067916/c48370c4-a50e-11e6-8fdc-6325dafcac97.png)

**Comment by bgashler1** [comment]
While I wouldn't use this feature, I'm not personally opposed to it being available behind a setting if a lot of the work for it is already done and if some might benefit from it.  If we do this, we would want to differentiate breakpoints from errors like VS does, as pictured above. @isidorn I'm not sure what our version of this looked like a year ago—maybe it didn't do that, and for that reason the team didn't like it?

**Comment by stefan505** [comment]
Very handy feature in Visual Studio and serves as way to navigate a large file during development. Any movement on this?

**Comment by isidorn** [comment]
fyi @misolori 
we could introduce this under a setting

**Comment by VErwin** [comment]
To add my two-cents as a N00b - it would be nice to add some discoverability to the "minimap".  I wasn't sure what it was called, which makes it hard to hide it.  It would be great if there were a tooltip on hover for "minimap" so that a user could know what it's named and could more easily find it in settings.  Also, as others mention improving navigation would be good.  Seeing a visual rendering of my code by itself in the minimap isn't really helpful.  Perhaps some type of semi-transparent color change in the editor and minimap on on-hover or gutter-markers denoting different areas would be more helpful.

**Comment by charlesg99** [comment]
Any progress on this? In Visual Studio, displaying breakpoints in the scrollbar is a must have feature that really helps navigating big files. Not sure why this isn't available in VSCode.

**Comment by jugges** [comment]
+1 on this feature, surprised it's not present already.

**Comment by isidorn** [comment]
We could introduce this as a setting. Which by default would be false.
Should be pretty simple, thus adding good-first-issue and I am open to PRs that tackle this.

**Comment by anirudhrb** [comment]
@isidorn I have attempted a PR (#82787) for this. Please have a look.
