### ISSUE TITLE
Allow refactorings to be previewed

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#151140]
## Feature request

When refactoring, it should be possible to preview the refactoring in the refactor menu, similar to how we support previews of renames

**Comment by justschen** [comment]
Added an additional command in the command palette that allows users to "Refactor with preview" - viewing refactorings in the refactor preview terminal instead of immediately applying refactor changes.

Normal Refactor vs Refactor with Preview (similar to the renaming preview):
![Recording 2022-06-09 at 11 43 51](https://user-images.githubusercontent.com/54879025/172921437-c39902e0-fdae-41cf-a974-de5f6170df38.gif)

Moving forward, we'll be modifying the refactoring menu and potentially adding additional refactoring preview options.

**Comment by sandy081** [comment]
This item is both in test plan and to be verified features list. 

@jrieken Since you verified this, I will add you to the testers list of the associated TPI so that we can see the coverage.
