### ISSUE TITLE
placeholder decoration is missing for cursor line on windows

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#151143]
1. create a terminal
2. press enter repeatedly
3. 🐛 the placeholder is always missing from the cursor line

![windows](https://user-images.githubusercontent.com/29464607/171701990-91edf031-8332-4df1-acb2-b43273ac74c8.PNG)

**Comment by Tyriar** [comment]
I wasn't sure where I mentioned this but I've been thinking of an idea to more aggressively check the contents of the line on Windows whenever a conpty reprint occurs to validate the command is in the right spot, similar to what is done on resize only right now. Not sure about perf implications

**Comment by Tyriar** [comment]
This is one of those issues that isn't really possible to fix without messing with other heuristics, unless conpty positions the sequence correctly. The latter should happen soonish in https://github.com/microsoft/terminal/issues/8698 and hopefully we'll be able to bundle a recent version of conpty instead of depending on the Windows release after that.
