### ISSUE TITLE
This test delays test execution by 500ms

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#15116]
Tests should run very fast such that we can develop on VSCode and run the tests often.

`mocha --run out\vs\editor\contrib\find\test\common\findController.test.js`

![image](https://cloud.githubusercontent.com/assets/5047891/20069847/7bce08b6-a51e-11e6-9843-8451c3a5a79e.png)

```
setTimeout(function () {
	assert.deepEqual(['3'], toArray(findController.getHistory()));
	done();
}, 500);
```

**Comment by sandy081** [comment]
@alexandrudima Thanks for bringing this.
I agree that having delays in tests is not good practice. In this case, it was put because to test history of find terms which are added to the history with a delay of 500ms. This is because `find` functionality is aggressive (starts finding immediately / on typing). Removing the delay will add each letter to the history while typing which is not good.

I would think if I can replace this delay with another better approach without any side affects.
