### ISSUE TITLE
SCM: Change the focus to the next file after staging a file

### ISSUE THREAD

**Issue by bcanzanella** [microsoft/vscode#15112]
- VSCode Version:

Version 1.7.1
Commit 02611b40b24c9df2726ad8b33f5ef5f67ac30b44
Date 2016-11-03T13:46:46.244Z
Shell 1.3.8
Renderer 52.0.2743.82
Node 6.5.0

- OS Version:
Ubuntu 16.04

After staging a file in the git view, focus the next file to be staged.

For my workflow, I'd want the next file in the list of stages to be the thing focused. Since I have a keyboard shortcut setup for staging a file, I could arrow up/down and use my shortcut to stage all files, without using a mouse or losing context. If the list of files to be staged creates a scrollbar, the context is lost after staging as it highlights/focuses the item that was just staged.

**Comment by marckassay** [comment]
How does this look?
![15112](https://user-images.githubusercontent.com/459665/36752117-1402e178-1bd0-11e8-97a5-ae6a5c7bf449.gif)

Here is the commit from my forked repo:
[github.com/marckassay/vscode/commit/408a9f1ab](https://github.com/marckassay/vscode/commit/408a9f1ab0ab3630419ffbd6f69cb3bcd3bc1bc3)

**Comment by bcanzanella** [comment]
@marckassay looks nice to me. I wonder about the `z.txt` case (or the last item case) -- should something still become focused? perhaps the previous item? (`y.txt`)

**Comment by marckassay** [comment]
@bcanzanella  Thanks!

I'm glad you mentioned about that last item as when I thought about it in development, I realized to continue with the API that I used would require changes that might of fall outside of scope for this request.

The API I'm referring to are public methods for List (listWidget.ts).  From what I recall, this class doesn't recognize groups (ISCMResourceGroup) which is used in scmViewlet.  This type makes a distinction between its elements such as 'Working Directory' and 'Staging'.  And since this class doesn't have this ability, referring to the demo above, from z.txt it loops to the 0 index, which is 'Staged Changes' item (which is in a different group).  It seems ideal to make a subclass of List that recognizes ISCMResourceGroup (generic) type.

**Comment by marckassay** [comment]
Ok, now I see how this can be done.  That is, to loop in the same group (ISCMResourceGroup).  I should have a commit to be proposed today.

**Comment by marckassay** [comment]
Ok, now take a look!
![15112](https://user-images.githubusercontent.com/459665/36821290-51d4a752-1cc0-11e8-83a5-e9f3fea36d12.gif)

**Comment by JerryGreen** [comment]
It definitely needs to be implemented!

> without using a mouse 

I wanted to create an issue just now, because of that. But found this one :) Subscribed.

**Comment by perat** [comment]
Why this issue is closed? Review of changes for commit still looks terribly uncomfortable.
Any extension to solve this?
