### ISSUE TITLE
Get Line Home with WordWrap

### ISSUE THREAD

**Issue by Alexhuszagh** [Microsoft/vscode#15121]
**Version**
- VSCode Version: 1.7.1
- OS Version: Fedora, 24

**Feature Request**

Enable home key to go to start of the line (column 0), even with word-wrapping.

**How To Reproduce**
1. Configure "settings.json" to use the following rules: `"editor.wordWrap": true`, and  `"editor.wrappingColumn": 80`
2. Add `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus sit amet semper erat, ut posuere.` as text to the editor, and ensure word wrap is active.
3. Set the cursor at the end of the line (Line 1, col 101).
4. Press `Home` key twice. First press has the expected behavior (cursor goes to start of the wrapped line, or col 77), second press does not move the cursor (when it should go to col 0).

**Comment by alexandrudima** [comment]
Since quite some time we have changed how <kbd>Home</kbd> works.

* on first press, it will go before the first character in the wrapped line
* on second press, it will go before the first non-whitespace character in the logical line
* on third press, it will go before the first character in the logical line

e.g.

![kapture 2018-04-17 at 12 07 39](https://user-images.githubusercontent.com/5047891/38863447-f157396a-4237-11e8-92f2-141d2c015181.gif)
