### ISSUE TITLE
Notebook's kernelspec metadata not updated when executing cells with a different kernel

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#151376]
create a notebook and save it.
Run a cell with a kernel.
Change the kernel and run another cell
reopen the notebook as plain text and note the kernel spec in the metadata.

metadata should specify the kernel that was most recently used, but it specifies the original.

Seems to repro with both local and remote kernels

**Comment by joaomoreno** [comment]
@rchiodo This should've been assigned to `May 2022 - Recovery 1` since we are adamant in verifying each issue that gets shipped in a recovery release individually. I found this out by looking into [commits that got pushed to the `release/1.68` branch](https://github.com/microsoft/vscode/compare/release/1.68).

Please find someone to verify this issue in the latest release candidate build.

**Comment by joaomoreno** [comment]
But there's still a recommendation: this should've been assigned to `May 2022` all along so people verify the issue was fixed. Can you find someone to verify and mark it as `verified`?

**Comment by amunger** [comment]
I had actually verified back when it was fixed, just didn't add the label since it wasn't marked verification needed. I'll do that now tho

**Comment by joaomoreno** [comment]
Thanks! 🙏
