### ISSUE TITLE
Closing the last window behaves inconsistently (hot-exit)

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#15136]
I think closing the last window should behave the same as closing a second-to-last window. Either they both preserve dirty editor states or both ask whether the dirty states should be saved or discarded.

Having mixed behavior is bound to confuse the user. (Same goes for exiting the app when there are multiple windows.)

Maybe there should be a setting for "preserve dirty editor state on close/exit" (better name TBD). Dirty editor state should always be preserved on: Reload Window, Restart to Update, crashes.

**Comment by Tyriar** [comment]
Closing this as designed for now but going to be tracking feedback on this when it goes out. It would be possible to have an option that essentially removed the confirm dialog for all windows and in order to restore backups there you would need to either:

a. open that folder explicitly
b. close all windows and relaunch vscode

My main issues are that it doesn't align with Sublime's behavior, it "hides" backups in the background and users could forget about them. Another problem with it is if the user closed many folders like this and then closed down vscode, the next launch will see a flood of windows being restored.
