### ISSUE TITLE
Pass full "Source" object to "setBrealpointsRequest"

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#1514]
In order to support breakpoints in inlined source maps, it is necessary that the "Source" object passed to the "setBrealpointsRequest" contains the same attributes that are returned from the "stackTraceRequest" (Setting breakpoints in inlined source maps is similar to setting breakpoints in internal modules). Currently only the "name" attribute is passed, but not the "sourceReference" attribute. Without the "sourceReference" attribute it is difficult for the backend to identify the correct inlined source.
I suggest that you pass the source object returned from stackTraceRequest unmodified to setBrealpointsRequest. Ideally even with attributes that are not specified in the debug protocol spec.

**Comment by isidorn** [comment]
The issue here is that the `setBreakpointsRequest` and the `stackTraceRequest` are 'disconnected'. I am sometimes sending the `setBreakpointsRequest` even though there has not been any stack traces yet.

Though what I can do, and what I will implement is that before sending the `setBreakpointsRequest`, I go through all the stack traces (if there are any) and try to search for the mathcing raw source. I will match only based on name of the raw source - since that is the only thing i can do. 
If I find I would send the complete data, otherwise I would contine sending what I send now. So this would work only if the user is in a stopped state and is adding a breakpoint - but if I understand correctly that is exactly the case that you want to cover here.

**Comment by weinand** [comment]
@isidorn thanks for this fix. The sourceReference is now returned correctly. However, the "path" attribute is bogus. If the following source object is returned in stackTraceRequest:
`
{
    "name": "classes.ts",
    "path": null,
    "sourceReferences": 1013
}
`
this source object is passed to setBreakPointsRequest:
`
{
    "name": "classes.ts",
    "path": "/classes.ts",
    "sourceReferences": 1013
}
`

The attribute "path" should be null.
