### ISSUE TITLE
PR Flow: Close the loop between committing and creating a PR

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#151589]
For our selfhosting PR flow purposes, today VS Code will automatically commit in a brand new randomly named branch, if the user's sitting on `main`. But there's still manual work required to go from there to having a PR created.

One suggestion would be to leverage the `git.postCommitCommand` setting and have GHPRI participate in there.

@alexr00 has suggested the following experience: it would be ideal if, right after committing something which caused VS Code to generate and switch to a new branch, the PR creation view would pop up, so ideally all the user has to do is click `Create PR`.

**Comment by lszomoru** [comment]
The running idea is to create a commit action button to which the PR extension would contribute a command:

<img width="429" alt="image" src="https://user-images.githubusercontent.com/3372902/175389896-fabeab3e-79d6-4121-8298-2136b9565159.png">

Since we are running out of time this milestone, this work will happen next milestone.

**Comment by lszomoru** [comment]
Git extension API is in place, and the GHPR extension now contributes a post-commit command:

<img width="437" alt="image" src="https://user-images.githubusercontent.com/3372902/179483190-bfcc9f1f-244f-4fe9-9d8c-b2f032375b40.png">
