### ISSUE TITLE
Debug Pause never makes it to DebugSession

### ISSUE THREAD

**Issue by GordonSmith** [Microsoft/vscode#15165]
- VSCode Version: 1.7.1
- OS Version: Windows 10

Steps to Reproduce:

1. Start debug session
2. Press continue
3. Press pause (event never makes it to DebugSession)

![image](https://cloud.githubusercontent.com/assets/966863/20097931/f422720e-a5a8-11e6-9b9a-7d57c55d5c14.png)

![image](https://cloud.githubusercontent.com/assets/966863/20097952/0e0655dc-a5a9-11e6-8b3e-bca88c713511.png)

As far as I can tell the request never makes it to the ```protocol._handleData```
![image](https://cloud.githubusercontent.com/assets/966863/20098058/b2e13676-a5a9-11e6-80bd-6e71cf6ea73b.png)

**Comment by weinand** [comment]
@GordonSmith please file this issue against the extension you are using.

**Comment by weinand** [comment]
@GordonSmith please ignore my previous comment.

@isidorn It seems that VS Code no longer sends a pause request.

**Comment by weinand** [comment]
I tried this with node-debug and see the same behavior.

**Comment by isidorn** [comment]
I acknowledge the bug - looking into the fix

**Comment by isidorn** [comment]
I suggest to push the fix to the october recovery branch.

**Comment by isidorn** [comment]
I pushed the fix to the relase 1.7 branch - this will need to be verified on the stable build.
There is one known limitation: -> if a program never stopped the pause command does not have any effect. This is fixed in the insder build but the change is a bit risky to be ported on the relase branch imho.

**Comment by weinand** [comment]
@isidorn 'known limitation': How do I stop a program for the first time if I can't use 'Pause'?
This limitation makes the 'fix' somewhat useless and I question whether it really makes sense to ship this in the October recovery build.

**Comment by GordonSmith** [comment]
@weinand Any debug session that has hit a breakpoint or starts in a "break" state, will have fired the StoppedEvent.

**Comment by isidorn** [comment]
Some more clarification: the known limitation is coming from the fact that the node adapter is not sending a [`'thread'` event](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/common/debugProtocol.d.ts#L128) when a new thread gets created. To capture this I have created issue #15176

So the bottom line is that other debug adapters might not be hitting this limitation. Due to that after discussing with @weinand we are leaning towards making this in the recovery release. Though we will still discuss inside the team

**Comment by weinand** [comment]
verified for node-debug and mono-debug.

@roblourens I tried to 'pause' the following server with node-debug2 but I couldn't get it to break:
```js
var http = require('http');

var i = 0;

http.createServer(function (req, res) {
	var j = i++;
	res.writeHead(200, { 'Content-Type': 'text/plain' });
	res.end('Hello World : ' + j + '\n');
	console.log("handled request: " + j);
}).listen(3000);

console.log('server running 1');
```

**Comment by roblourens** [comment]
node-debug2 breaks for me, in net.js. 

When I try with node-debug, I only ever get "No call stack because program paused outside of Javascript"

**Comment by weinand** [comment]
@roblourens the node-debug behavior is expected because the runtime waits in libuv which does not provide a JavaScript stacktrace.

**Comment by isidorn** [comment]
More info about the fix: at the end we decided to behave the same way as the previos vscode version behaves. That is: if a stop event happened we properly send the paused request, if it did not happen we send a paused request for `threadId: 0`. 

The proper fix is in the insiders build but we have choosen the previous approach for the recovery since even though it is wrong it is the way vscode behaved before and which works in practice and is low risk.
