### ISSUE TITLE
Node debug is not sending a 'thread' event when a new thread gets created

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#15176]
Node debug is currently not sending a ['thread' event](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/common/debugProtocol.d.ts#L128) when a new thread gets created. This is problematic for the vscode model since it is not aware of any threads unless a stopped event occurs. This leads to the limitation discussed in https://github.com/Microsoft/vscode/issues/15165

fyi @roblourens

**Comment by weinand** [comment]
from the [documentation](https://code.visualstudio.com/docs/extensionAPI/api-debugging):

"After a successful launch or attach VS Code requests the baseline of currently existing threads with the threads request and then starts to listen for thread events to detect new or terminated threads. Even if your debug adapter does not support multiple threads, it must implement the threads request and return a single (dummy) thread. The id of this thread must be used in all requests where a thread id is required, e.g. stacktrace, pause, continue, next, stepIn, and stepOut."

So instead of sending a thread event, we'll have to find a way that you can reliably call a threads request.

**Comment by isidorn** [comment]
It is just a time when this should be done. After the response from `initializing` request is recieved by vscode?

Though it feels cleaner to me that the adapter sends a thread event and we change the documentation. I understand this is a breaking change in a way but since this was never working in practice it will just be the change of docs.

**Comment by weinand** [comment]
Try to send the ThreadRequest after the ConfigurationDoneRequest (or SetExceptionBreakpointsRequest in legacy mode).

No, sending events for an old baseline state doesn't feel 'clean' because those events are basically sent out a second time (but at the first time no one was listening).

In addition we had long discussions about thread events vs. threadRequest and came to the conclusion that thread events are optional and that debugAdapters don't have to send them.  So I'm pretty sure that no existing debugAdapter sends out a threadEvent on connect.

**Comment by isidorn** [comment]
To verify make sure you can pause a debug session even if it did not stop prior
