### ISSUE TITLE
filePicker.alternateFileNameMatching doesn't seem to work

### ISSUE THREAD

**Issue by gwynjudd** [Microsoft/vscode#1518]
I have fuzzy file name matching enabled in my user settings:

![image](https://cloud.githubusercontent.com/assets/314188/11923137/1cdbda94-a804-11e5-8cd5-89f62fb04b32.png)

However, it doesn't appear to work as expected - here I have typed "ls", you can see a number of files in the list:

![image](https://cloud.githubusercontent.com/assets/314188/11923217/f8a9ae16-a804-11e5-8d3c-edd89ea097d6.png)

Now I type a t ("lst") - only "localstorage.js" is matched:

![image](https://cloud.githubusercontent.com/assets/314188/11923220/0a11c346-a805-11e5-8bfa-a09c687b1f84.png)

I expected that all of the files in the previous list would have still matched as they have got "t" in them after the previous match.

**Comment by gwynjudd** [comment]
This screenshot from the release notes suggests that it should work as I would have expected:

![image](https://cloud.githubusercontent.com/assets/314188/11923229/32650b6e-a805-11e5-9b27-982ee92ae40b.png)

**Comment by bpasero** [comment]
@gwynjudd this feature is currently limited to file matches only. what you see is the editor history which is  containing other editors too. We might expand this feature to other areas, but for now it is limited.

**Comment by gwynjudd** [comment]
@bpasero I don't really understand what you mean about the "editor history" as opposed to "file matches". Surely the things in my screenshots are files?

**Comment by bpasero** [comment]
@gwynjudd the editor history is a list of editors you opened in the past, persisted between sessions. If you just Ctrl+P you will see this list even without searching. Once you start searching results from the editor history are merged with results from a traditional file search. Currently the alternate scoring and matching is only enabled for the file search. If a result from editor history matches, it will not be repeated from the file search.

Since the editor history is persisted and does not require disk access, you can very quickly find files you worked on in the past and dont need to wait for the slower disk search to complete.

**Comment by bpasero** [comment]
So, anyway, you should get proper results from the slower disk search eventually. Improving performance of the file search is high on our plan.

**Comment by gwynjudd** [comment]
@bpasero oh thanks for the reply. If you are interested in feedback, it seems like the search history seems to be quite slow to populate compared to the editor history. Also I think it's probably a bit confusing that you have to do a search first (something I pretty much never do) before fuzzy file name matching would work.

**Comment by bpasero** [comment]
@gwynjudd if the file search was as fast as the editor history, would it make any difference?

**Comment by gwynjudd** [comment]
@bpasero yes that would be better, but it still seems weird that you have to do a search before fuzzy matching happens
