### ISSUE TITLE
confusing "pwa-node"

### ISSUE THREAD

**Issue by jasonjiwork** [microsoft/vscode#151910]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.68.0
- OS Version: macOS Monterey 12.4

Steps to Reproduce:

1. delete "launch.json" in ".vscode" directory
2. click "run and debug" button on the left
3. click "create launch.json"
4. choose "Node.js"
5. a configuration is created, with "type": "pwa-node"
6. click "add configuration"
7. choose any Node.js item
8. a configuration is create with "type": "node" or "type": "node-terminal"

So sometimes I get "pwa-node", sometimes I get "node", same debugger is chosen: "Node.js"

It confuses newcomers.
 previously, "pwa-node" indicates that a preview version of debugger will be used, but now there's no "Node.js(Preview)" to choose.
It seems to be a bug.

By the way, why we call it "pwa-node", why not "node-preview",  this name confused a lot of developers.

**Comment by connor4312** [comment]
We have `pwa-node` for historical reasons: the current [js-debug](https://github.com/microsoft/vscode-js-debug) used to be called the "pwa debugger" or something like that due to additional features it added to be able to debug PWAs. It then replaced the built-in debugger and took over prefix-free launch types (`node`, `chrome`, etc.). However, we can't remove the old configurations without breaking users who have them in their configs.

Maybe VS Code should support "hidden" launch types where the type doesn't show up as a completion suggestion in the package.json, but is valid.

**Comment by weinand** [comment]
@connor4312 yes, an hidden "alias" debug type makes sense.
But we should make sure that `"type": "pwa-node"` is no longer used in snippets.

**Comment by connor4312** [comment]
We removed them from snippets already, but it looks like they can still be returned from dynamic configurations. I pull put in a PR for that.

**Comment by jasonjiwork** [comment]
@connor4312 ，thanks for you explanation.
