### ISSUE TITLE
Terminal: change icon should use current color, if any

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#152092]
Also the inverse - Terminal: change color should use the current icon

<img width="635" alt="Screen Shot 2022-06-14 at 9 58 01 AM" src="https://user-images.githubusercontent.com/29464607/173634141-1792678c-40e7-4122-9df1-f1b41258223c.png">

**Comment by Tyriar** [comment]
As mentioned I have mixed feelings because of contrast when the theme has the panel dark and the editor light could lead to problems. What do you think @misolori?

**Comment by misolori** [comment]
Since this is a customization that users are making, we don't have to follow any color contrast guidelines like we normally do with default items. We could try it out, my only minor concern is the color could add another layer for the user to process, which could slow things down especially if the icons/color could change from terminal to terminal based on their config.

**Comment by meganrogge** [comment]
@Tyriar are you still opposed to this?
