### ISSUE TITLE
TS should use narrowed type when extracting method

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#152296]
See this example:
![Recording 2022-06-16 at 07 29 42](https://user-images.githubusercontent.com/900690/173998176-49e12b0e-9b08-44ba-9d5b-fc04aad13ff6.gif)

I would have wanted:

```ts
private async migrateWorkspace(to: IAnyWorkspaceIdentifier) {
```

**Comment by mjbvz** [comment]
@bpasero Can you share a link to code that demonstrates this problem?

**Comment by bpasero** [comment]
```ts
function migrate(foo: string | boolean) {
  if (typeof foo === `string`) {
    const bar = foo;
    console.log(bar);
  } else {
    console.log(foo);
  }
}
```

When you extract the block in `typeof foo === string`, it should put `foo: string` into the method signature.

**Comment by bpasero** [comment]
Hm, maybe this is a case of then the interfaces are identical in shape:

```ts
interface IFoo {
	id: string;
}

interface IBar {
	id: string;
}

function isFoo(obj: any): obj is IFoo {
	return typeof obj === 'string';
}

function migrate(foo: IBar | IFoo) {
	if (isFoo(foo)) {
		const bar = foo;
		console.log(bar);
	} else {
		console.log(foo);
	}
}
```

**Comment by mjbvz** [comment]
Thanks! Yes that appears the be the issue. I opened https://github.com/microsoft/TypeScript/issues/49576 yesterday based on this but could not reproduce the original issue you showed, so thank you for the more minimal repo. 

However I think this is expected since `isFoo` does not narrow the type as you'd expect in the example. If you hover over `bar`,  it's type is still `Foo | IBar`

As soon as you add a new property to `Foo`, then the type check works as expected
