### ISSUE TITLE
Explorer doesn't fit width when double clicking on the resize handler

### ISSUE THREAD

**Issue by vanthiyathevan** [Microsoft/vscode#15242]
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:46:46.244Z)
- OS Version: Linux x64 4.8.6-1-ARCH
- Extensions:

|Extension|Author|Version|
|---|---|---|
|rainbow-brackets|2gua|0.0.6|
|vscode-markdownlint|DavidAnson|0.5.0|
|EditorConfig|EditorConfig|0.3.4|
|material-icon-theme|PKief|1.1.3|
|vscode-docker|PeterJausovec|0.0.7|
|vscode-file-peek|abierbaum|1.0.1|
|theme-colorful-defaults|aeschli|0.1.10|
|path-intellisense|christian-kohler|1.1.0|
|vscode-eslint|dbaeumer|1.0.8|
|tslint|eg2|0.5.40|
|vscode-npm|fknop|3.3.0|
|flow-for-vscode|flowtype|0.3.3|
|Theme-MarkdownKit|ms-vscode|0.1.1|
|csharp|ms-vscode|1.4.1|
|debugger-for-chrome|msjsdiag|2.2.2|
|vscode-mssql|sanagama|0.0.4|
|whitespace|sandcastle|0.0.4|
|RustyCode|saviorisdead|0.19.1|
|theme-tesla|smlombardi|0.0.1|
|es6-mocha-snippets|spoonscen|0.0.1|
|guides|spywhere|0.5.1|
|change-case|wmaurer|1.0.0|
|JavaScriptSnippets|xabikos|1.2.0|
|ReactSnippets|xabikos|1.2.0|

---

Steps to Reproduce:

While on Explorer tab, when you double click  it used to collapse or expand to fixed width. But now if its expanded beyond the fixed with double clicking on the resize handler doesn't reduce the size it keeps expanding.

**Comment by bpasero** [comment]
Wow, good catch. No clue how we broke that...

**Comment by bpasero** [comment]
This seems to be caused by https://github.com/Microsoft/vscode/commit/42ec7da2ba58cfb7b25b930a54dd5bb038e5aba4 which was a fix for https://github.com/Microsoft/vscode/issues/13787

**Comment by bpasero** [comment]
@joaomoreno maybe something for you as CSS wizard :). When you double click on the explorer, we [compute](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/browser/views/explorerView.ts#L352) the optimal width of the DOM nodes that contain the label of the file. Since the label has [`flex: 1`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/browser/media/explorerviewlet.css#L31) set, somehow the optimal width is growing and growing each time you double click. 

Now, when I remove `flex: 1` it works again but then this happens:
* have a file with long text
* enable icons in the explorer (use minimal icon theme, not seti)
* resize the explorer
=> the label moves

![editors](https://cloud.githubusercontent.com/assets/900690/20166612/4b06e8de-a716-11e6-987b-e2e2e989b752.gif)
