### ISSUE TITLE
New macOS bar - intellisense issue

### ISSUE THREAD

**Issue by wallverb** [Microsoft/vscode#15258]
- VSCode Version: Code - Insiders 1.8.0-insider (ce6d57875ab53309204cf12dc54d74956221cfc1, 2016-11-09T08:41:36.673Z)
- OS Version: Darwin x64 16.1.0
- Extensions:

---

Steps to Reproduce:

![image](https://cloud.githubusercontent.com/assets/1723815/20150622/ca0c4a08-a684-11e6-9235-688f1eec532b.png)

Works ok in 1.7.1

**Comment by wallverb** [comment]
FYi - setting "window.titleBarStyle": "native" fixes the issue

**Comment by bpasero** [comment]
@wallverb can you share how this looks like in 1.7.1 for you? I just made the comparison myself and see it behaves the same:

Native Title
![image](https://cloud.githubusercontent.com/assets/900690/20166505/945cec82-a715-11e6-88a3-483a983f4115.png)

Custom Title
![image](https://cloud.githubusercontent.com/assets/900690/20166528/b2066358-a715-11e6-9678-70b2e918fefb.png)

**Comment by wallverb** [comment]
Custom Title:
![custom](https://cloud.githubusercontent.com/assets/1723815/20179907/3628f4d8-a726-11e6-9f11-cf52220c5305.gif)

Native Title:
![native](https://cloud.githubusercontent.com/assets/1723815/20179913/380dbdce-a726-11e6-8387-34b783fe1108.gif)

**Comment by bpasero** [comment]
@joaomoreno @alexandrudima I think the issue here is that the hover thinks the title area (when set to custom) is something to overlay because it is within the bounds of the workbench.

I see two options:
* reduce the z-index of the title so that the hover just overlaps
* tell the editor that there is a 22px area on top that widgets should not overlay

What do you think?

**Comment by joaomoreno** [comment]
IMO, the two points need to be addressed. 

The titlebar should not have a `z-index` at all, since no other element is placed in the same position, if our layout code is correct.

At the same time, I don't think we really benefit anything from letting overflowing widgets be rendered on that area, so maybe we should _crop_ the area a little bit. We already do that [_hack_](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/browser/viewParts/contentWidgets/contentWidgets.ts#L275) for the status bar, just create go along and create a `TOP_PADDING`.

**Comment by bpasero** [comment]
Makes sense. Pushed via https://github.com/Microsoft/vscode/commit/0a5a7b98d6a807bc71092b172b1dc5ee5b2d009d

I took out those `z-indexes`, I have no clue why we had them in the first place. Let's see what happens.
