### ISSUE TITLE
 I want to confirm that openTextdocument will open a new label correctly? What is the best way to create a textdocument without opening a new label？

### ISSUE THREAD

**Issue by SparkElf** [microsoft/vscode#152650]
I had try to create virtual document by `workspace.registerTextDocumentContentProvider`,but I can't  set the language of the `TextDocument` through this api.
My questions:
(1)Can I load the `TextDocument `directly from uri?
(2)Is the behavior that a new label opened after calling `openTextdocument` correctly?
(3)What is the best way to create a `TextDocument `without opening a new label？

**Comment by jrieken** [comment]
> but I can't set the language of the TextDocument through this api.

You can set a language via the [setTextDocumentLanguage](https://github.com/microsoft/vscode/blob/c8663870df8d51bb5a7629d695f2020330190ebe/src/vscode-dts/vscode.d.ts#L12290)-function but it is _better_ to use well-know fake-filename, like `sample.cpp` or `virtual.html`, so that VS Code selects the language based on that

> What is the best way to create a TextDocument without opening a new label？

Not sure what you mean by label?

**Comment by jrieken** [comment]
> My last question is how can I load the TextDocument created by workspace.registerTextDocumentContentProvider?

Simply use [openTextDocument](https://github.com/microsoft/vscode/blob/122528357821168f90ebbdb1ec485abdbb0a578e/src/vscode-dts/vscode.d.ts#L11940) for that. I will first ask the content provider for the text-value and then create a text document for it
