### ISSUE TITLE
Autocomplete for typescript string literal types not working in all cases

### ISSUE THREAD

**Issue by wmaurer** [Microsoft/vscode#15268]
- VSCode Version: 1.7.1
- OS Version: Windows 10
- Typescript Version: 2.0.8

When a typescript variable has a string literal type, autocomplete is working nicely, e.g.:
(as function parameter)
![image](https://cloud.githubusercontent.com/assets/2899448/20156993/05729086-a6d3-11e6-8db1-82d0d57da60d.png)

(as variable)
![image](https://cloud.githubusercontent.com/assets/2899448/20157040/37b82dda-a6d3-11e6-92a2-4db17dc9d6b0.png)

However when the string literal type is a property on an interface, I'm getting many irrelevant suggestions in the autocomplete list (here I would expect just `bar`, `ybay` and `zbarbaz`):
![image](https://cloud.githubusercontent.com/assets/2899448/20157085/7412338e-a6d3-11e6-9f02-9a53da930e14.png)

Having this fixed for objects / interfaces would greatly improve the VSCode+Typescript developer experience.

**Comment by waderyan** [comment]
@bowdenk7 Can I get your thoughts on this? Is this a situation we do not support or is this a bug?

**Comment by bowdenk7** [comment]
Looks like a bug to me. Filed: https://github.com/Microsoft/TypeScript/issues/12224

**Comment by mjbvz** [comment]
This has been fixed in TypeScript 2.2:

<img width="619" alt="screen shot 2017-01-26 at 12 01 42 am" src="https://cloud.githubusercontent.com/assets/12821956/22323910/a79a5808-e35a-11e6-802d-1facbb51b7b7.png">


You can try this today by installing a preview of typescript 2.2 in your workspace: `npm install typescript@next` and configuring vscode to use this version of TS : https://code.visualstudio.com/Docs/languages/typescript#_using-newer-typescript-versions

Let me know if you run into any issues

Thanks
