### ISSUE TITLE
Suggestion that adds a line - cursor goes to the wrong line

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#15267]
I'm sure there's an easier way to repro this, but I see it in the Go extension when I do an auto-import. 

In this case, I've run `go get github.com/golang/example/hello`, opened the 'example' folder, and I'm using the Go extension to get intellisense for `stringutil`. When I press tab or enter, it also adds a line above for the import, and the cursor ends up on the line above where it should be.
![nov-09-2016 14-28-09](https://cloud.githubusercontent.com/assets/323878/20157241/c90080d0-a688-11e6-9281-cf077738850d.gif)

**Comment by roblourens** [comment]
It reproes in Insiders, but not stable

**Comment by roblourens** [comment]
Ramya found this worse case
![nov-09-2016 15-00-31](https://cloud.githubusercontent.com/assets/323878/20158113/5c7208c6-a68d-11e6-8638-1b7c04e649fd.gif)

**Comment by ramya-rao-a** [comment]
Details on the Auto-import feature implementation:

- Auto-import a package after starting to type the package name (the first example Rob shows above)

The completion item for auto-importing packages uses the `command` property to point to a [command](https://github.com/Microsoft/vscode-go/blob/master/src/goImport.ts#L151) that inserts the line for the package

- Auto-import a package after selecting package members from the completion list (the second example Rob shows above)

The completion item in this case uses the `additionalTextEdits` property to add a text edit that inserts the line for the package.

Yes, I know what you are thinking.. why use 2 different approaches ??

Well, in the beginning, I used the `command` property in both cases. Then we had a bug where the tabs wouldnt work properly when `useCodeSnippetsOnFunctionSuggest` setting was enabled. So changed the second one to use `additionalTextEdits`. Didnt change the first one at the time due to "If it isnt broken, don't fix it" :)

Regardless, this is a regression.
Did anything change around `command`/`additionalTextEdits` in CompletionItems ?

**Comment by jrieken** [comment]
Hm.. I know that @alexandrudima has refactored the cursor. I have made no changes other than adding support for another snippet syntax. That shouldn't affect this.

**Comment by jrieken** [comment]
@alexandrudima is it possible that `this.editor.executeEdits` doesn't update the cursor anymore? I can see that we insert a new line above the cursor but that the cursor position isn't changed after that, e.g it is still on it's old value and therefore the primary edit happens on the wrong line
