### ISSUE TITLE
make creating tasks easier

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#152657]
I'd like to run a command that uses a multi-layered quickpick to configure tasks more easily. Typing in the `.json` feels cumbersome and clunky

**Comment by meganrogge** [comment]
Intellisense can work to identify what I can configure about a task, but that's not sufficient / a format I find very useful

**Comment by meganrogge** [comment]
My main issue is with having to work in a json file. So the configure task command bringing me there is not very helpful.

I was imagining you could select task type and then based on that, configure a lot of the properties.

What are the downsides of multi-step quickpicks?

**Comment by Tyriar** [comment]
@meganrogge they're not very nice as a complex UI with a bunch of options as it doesn't show where you came from, can hide when clicking away (option I think), etc. It's worth a discussion with UX before too much effort is put into this as there might be a better idea to improve it.

**Comment by alexr00** [comment]
This seems analogous to settings.json, for which we have a very nice custom editor. If we want to add tasks UX I would opt for something like that (maybe tracked by https://github.com/microsoft/vscode/issues/28235) rather than quick picks. I like the json file though and seldom use the settings editor.

**Comment by Tyriar** [comment]
Perhaps tasks/debug could integrate with or embed the settings editor 🤔
