### ISSUE TITLE
Unexpected request for permission to read personal user data from GitHub when syncing

### ISSUE THREAD

**Issue by callionica** [microsoft/vscode#152725]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.68.1
Commit: 30d9c6cd9483b2cc586687151bcbcd635f373630
Date: 2022-06-14T12:52:13.188Z
Electron: 17.4.7
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Darwin x64 17.7.0
- OS Version: Mac OS High Sierra 10.13.6

Steps to Reproduce:

1. Check in a code change locally
2. Click rotating icon to sync local change to GitHub
3. See unexpected request for extra permissions to private user data:
![unexpected-permission-request](https://user-images.githubusercontent.com/16260283/174778588-6a19b4a1-e503-4047-bf12-f59e5cd4eff1.png)

VS Code did not previously seek access to personal user data in order to sync a change with GitHub. Why now?
You can see that VS Code is already authorized with "Full control of private repositories". You didn't need more than that for syncing in the previous version of VS Code.

**Comment by callionica** [comment]
I worked around this issue, by canceling the web page permission request, and using the username/password flow with a personal access token that does not have the undesired email/profile permissions.

**Comment by lszomoru** [comment]
@TylerLeonhardt, was there a recent change to the scope of GitHub auth?

**Comment by TylerLeonhardt** [comment]
Yes we recently aligned the scopes used in:

* [GitHub Pull Request Extension](https://github.com/microsoft/vscode-pull-request-github/blob/10c4ba3a18f0b9c4b3be7aee92bab3c2c4f17edf/src/github/credentials.ts#L29)
* [GitHub Repositories Extension](https://marketplace.visualstudio.com/items?itemName=GitHub.remotehub)
* [GitHub Extension](https://github.com/microsoft/vscode/blob/main/extensions/github/src/auth.ts#L27) (this is the one @callionica is using here)

Our motivation was to help streamline logging in to these extensions. If you log in to one of them, then you don't need to log in to the others (this is especially helpful in vscode.dev). As a result, these extensions request some scopes that they don't use at all.

Unfortunately, GitHub doesn't have a better solution for us yet. We are waiting until GitHub Apps can handle our needs and they just can't at the moment... so unfortunately, this is the best we can do.

Since we need this streamline logging in experience, there is unfortunately nothing we can do about this right now... until GitHub works on supporting our needs for GitHub Apps (which they want to do, but it's not their priority at the moment)
