### ISSUE TITLE
Shortcut key for Git is inconsistent on Mac

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#15281]
- VSCode Version: 1.8.0 insiders
- OS Version: macOS

From https://github.com/Microsoft/vscode/blob/aff2353a3873f58f2436215c2827fafbcdad5eaa/src/vs/workbench/parts/git/browser/gitWorkbenchContributions.ts#L492 I saw

```
win: { primary: KeyMod.CtrlCmd | KeyMod.Shift | KeyCode.KEY_G },
linux: { primary: KeyMod.CtrlCmd | KeyMod.Shift | KeyCode.KEY_G },
mac: { primary: KeyMod.WinCtrl | KeyMod.Shift | KeyCode.KEY_G }
```

We are using `WinCtrl` on Mac while on Windows/Linux it's `CtrlCmd`, which makes Git the only that uses `Ctrl` instead of `Cmd` as modifier. Any catch behind it?

**Comment by kaiwood** [comment]
None of my business, but I'd guess it is because `cmd-shift-g` can't be used. `cmd+g` is a standard OS key for "next search result", `cmd+shift-g` is "previous search result" in all applications. Personally, from my experience as a user, I couldn't stand the current default. It was one of the first keys I remapped (to `cmd+shift+i` as a mnemonic, the ***i*** in g**i**t is a quite "prominent" character)

**Comment by joaomoreno** [comment]
That's the catch!
