### ISSUE TITLE
Investigate BackupService listening to ILifecycleService.onWillShutdown instead of being called from TextFileService

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#15280]
From https://github.com/Microsoft/vscode/pull/14115#discussion_r87145853

@bpasero 

> @Tyriar can you explain again why the backup service cannot participate in the shutdown and do its work there?

@Tyriar

> A few reasons:
>
> - `TextFileService` depends on `BackupService.cleanupBackupsBeforeShutdown` because it needs to clean up backups.
> - `BackupService` needs to trigger `TextFileService.confirmBeforeShutdown`.
> - Even if they were separate, there would need to be some communication between the 2 services. Depending on what `BackupService` does, it may need to not give a prompt even if there are dirty files for example.
>
> If you have any ideas how to get around this nicely that would be great :smiley:

**Comment by bpasero** [comment]
@Tyriar I pushed a series of changes to make the shutdown logic easier to understand. I settled on the idea that it is fine to let `ITextFileService` be the main controller of the shutdown and not add more eventing on it for the backup service. I think introducing more eventing is not possible because the shutdown handlers run in parallel  on shutdown.

https://github.com/Microsoft/vscode/commit/0cb26e1a29a1cd034e821f7160975b4e13856635 and https://github.com/Microsoft/vscode/commit/43d89f035d0bc05161ed07ead105f435d126eb64 are just polish.

In https://github.com/Microsoft/vscode/commit/48240f69f63d686265f6f57c4fa0dd5ce39117c7 I am actually taking out more control away from the backup service and into the text file service. Since the shutdown is handled from the text file service exclusively, I think it does not make sense to have the `boolean | TPromise<boolean>` signature in backup service. Instead, the backup service is now indicating if a backup happened so that we do not have to move the `confirmBeforeShutdown()` callback around to the backup service.

Finally, I changed the order of things a bit: If auto save is enabled, I think hot exit should not trigger. We always used to save all files on shutdown if auto save is enabled and I think we should keep this behaviour. If something goes wrong during save on shutdown, we leave the prompt as it was before assuming that the save failed for some reason.

Let me know what you think about my changes 👍
