### ISSUE TITLE
The dark red breakpoint does not disappear when the mouse quickly slides from the editor page to the left page

### ISSUE THREAD

**Issue by xiaguangbo** [microsoft/vscode#152933]
Does this issue occur when all extensions are disabled?: Yes/No.

- VS Code Version:
- OS Version:
版本: 1.68.1
提交: 30d9c6cd9483b2cc586687151bcbcd635f373630
日期: 2022-06-14T12:48:58.283Z
Electron: 17.4.7
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.22000

vscode itself has no debugging function for .c files, and there is no red dot on the left side of the editor's line number.
After installing the C/C++ extension, under normal circumstances, when the mouse moves to the left of the line number, a dark red dot will appear. When the mouse continues to move left beyond the editing page, the dark red dot will disappear, but when you quickly swipe across, there is a chance that the red dot will not disappear：
<img width="871" alt="image" src="https://user-images.githubusercontent.com/102402151/175192799-fc1244d4-028e-4c33-ae70-2dac2c75d0e0.png">

I mentioned this issue in the c/c++ extension "Discussions", this is related to the UI of vscode itself：
https://github.com/microsoft/vscode-cpptools/discussions/9492

**Comment by omkarshinge** [comment]
Hi, this is first time I'm debugging VS code source and I went through this issue and debugged the code for it

OS & Version: Debian GNU/Linux 11 (bullseye)
Version: 1.69.0
Electron: 18.3.4
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Linux x64 5.10.0-14-amd64

As per my understanding and going through various references regarding mouse events and debugging the code for **Breakpoint Hints** I came to following conslusions :
- The mouse movements are being recorded from time to time. (i.e. not pixel by pixel but frame by frame)
- When we move the mouse fast, it is possible that it skips some UI elements hence not triggering the mouse events for such elements.

For VS code editor section we have `mouseHandler.ts` file through which we check for mouse events and if any is recorded then further logic/code is executed. [the code checks for mouse events on editor part of UI]
- Showing **break point** hint is one such of functionality depending on mouse events. [Code responsible for the functionality can be found in File : `breakpointEditorContribution.ts` Method name : `ensureBreakpointHintDecoration()`]
- When cursor moves fast enough it is possible that as mentioned above the events may not be triggered.
This is the root cause for this issue where the breakpoint hint remains in place and is not removed even though the cursor has moved past the breakpoint display section.

**For reference :**
Check out the following example on w3schools website for mouse events and try to move cursor slowly and fast over the image.
- Link : [w3schools example for mouse events **mouseenter** and **mouseleave** events](https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_onmouseenter)
- One can see in above example that on slow movement of cursor the image size grows and shrinks but if we move the cursor fast enough then there's no change in image size

One of the solution to tackle above problem I could think of is that we can have the **break point hint code** being ran/checked for whole VS code window mouse events rather than editor part of mouse events.

**Comment by xiaguangbo** [comment]
@omkarshinge Hi, thanks for your answer
The effect in the link is very good, and there is no situation where the picture is still enlarged after the mouse leaves

Here are my thoughts on the Implementation principle：when checking the window where the mouse is located, you need to send 'here' once to the window cursor are in, and send a "left" to the previous window cursor are in

**Comment by roblourens** [comment]
I noticed this too and I'd guess it's the same as https://github.com/microsoft/vscode/issues/145928 @hediet

**Comment by alexdima** [comment]
Let's track in #138789
