### ISSUE TITLE
View state restoring is broken

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#153084]
* I consistently see SCM showing in the explorer (I never moved it there)
* Timeline keeps moving into the explorer (I have moved it to the bottom panel)

<img width="1521" alt="Screenshot 2022-06-24 at 10 23 55" src="https://user-images.githubusercontent.com/1794099/175495325-53467e48-e896-4f53-9643-39336ea344a4.png">

**Comment by sandy081** [comment]
@jrieken Is it possible to get value of following keys from your VS Code Profile Storage?

- `workbench.activity.pinnedViewlets2`
- `workbench.explorer.views.state.hidden`

Please use the command `Developer: Log Storage Database Contents` that prints the state in the console.

**Comment by sandy081** [comment]
This is due to the bug that recently got introduced in web (insiders) - which switched storage to a new DB and made state to be complete out of sync especially with settings sync enabled. This got fixed next day in web (insiders) that switched storage to original DB. This bug could be the result of this DB switching back and forth and settings sync being on that brought data from web to desktop that would have caused this inconsistency. 

With latest insiders, Desktop and Web are behaving as expected and consistent. So I would request to update/restore your changes from settings sync view and everything shall be back on smooth ride. 

Very much apologies for this breakage caused.
