### ISSUE TITLE
Copyright Symbol Not Encoding Properly in UTF-8

### ISSUE THREAD

**Issue by fallXone** [Microsoft/vscode#15303]
- VSCode Version: 1.7.1
- OS Version: Windows 8.1

Steps to Reproduce:

1.  Open an existing file that has the © symbol (this was tested on a .sql file)
2.  Notice that the symbol changes to � while in UTF-8

Assuming this is not correct, considering Notepad++ does not do this in UTF-8 encoding.
[testFile.txt](https://github.com/Microsoft/vscode/files/589485/testFile.txt)

**Comment by aeschli** [comment]
Can you attach a sample file whet you see this?

**Comment by fallXone** [comment]
I attached an example file. Notice that in the example file I provided, we even have a situation where a space is being converted to �. Notice that Notepad++ will render this file fine in the same encoding type of UTF-8

**Comment by ramya-rao-a** [comment]
I see this while adding emoji symbols from the virtual keyboard in Windows as well

**Comment by iSazonov** [comment]
Another example file [CoreAdapter.cs](https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/CoreAdapter.cs#L3145)

**Comment by rmunn** [comment]
The `testFile.txt` file attached to the issue description is encoded in ISO-8859-1 (a.k.a. "Latin-1"), not UTF-8 -- the © symbol in that file is represented by a single `0xA9` byte. This is, naturally, invalid UTF-8 and so the offending `0xA9` byte gets replaced by � (U+FFFD), as it should be according to spec. (There are also several `0xA0` byte in that file, which are apparently intended to be U+00A0 NO-BREAK SPACE).

The reason why Notepad++ doesn't do this is probably that it is auto-detecting the file encoding via some heuristic, and converting it to valid UTF-8, so you don't realize that your files are incorrectly encoded. ("Incorrectly" because you think they're UTF-8 but they're really ISO-8859-1). VS Code, on the other hand, doesn't silently fix the incorrect encoding for you, so you actually find out about the encoding mistake in your files and can fix it.

**Comment by fallXone** [comment]
How come Visual Studio Code shows that the encoding for these files are UTF-8 though? Seems like there is still an issue in that VSC isn't showing the proper encoding, and even after setting it back to UTF-8, it doesn't correct the file.

**Comment by bpasero** [comment]
Here is the story about encoding in VS Code:
* if your file as a UTF-8 or UTF-16 byte order mark (https://en.wikipedia.org/wiki/Byte_order_mark) we detect the encoding based on that
* if not, we pick the workspace or global configured encoding (see `files.encoding`)

**Comment by rmunn** [comment]
@fallXone - As bpasero mentioned, VS Code doesn't auto-detect file encoding. It reads the file in with whatever encoding you've defined, and *converts* any incorrect characters at the time it reads it in.

In other words, by the time VS Code is telling you that the encoding is UTF-8, it *is* UTF-8 (and any invalid bytes have already been replaced). Your comment that VS Code isn't showing the "proper" encoding is assuming that VS Code can figure out that those files are ISO-8859-1... but VS Code wasn't written that way. Notepad++ was written ages ago, when files encoded in non-Unicode encodings like ISO-8859-1 were still common, and it had to deal with whatever non-Unicode file you threw at it. But VS Code was written in the post-Unicode era, when UTF-8 has become the *de facto* standard. (Though not the *de jure* standard, as Microsoft still uses UTF-16 for a lot of its APIs. <a href="http://utf8everywhere.org/"I hope that someday that may change</a> and MS will create UTF-8 versions of their APIs, but given MS's immense concern for backwards compatibility, that will take a VERY long time).

And in my *firmly-held* opinion, the fact that you have a file that's not Unicode should be considered a ***bug*** in whatever software created that file. Latin-1 cannot encode more than 256 different characters (in practice that number is really 191). What if next year, you need to update that SQL file to deal with Japanese characters, because the company acquired a major client in Japan? You're going to have to update that to a fully-Unicode encoding at some point anyway -- so VS Code is really doing you a favor by pointing out the flawed file *before* it costs your company a major contract because it doesn't handle your Japanese clients' names correctly.

Really, all files these days should be in a Unicode encoding. And UTF-8 is the best encoding to use unless you have *very specific* reasons to use something else. So I'm glad that VS Code defaults to it, and refuses to use heuristics to "guess" the encoding of a file it opens.

**Comment by iSazonov** [comment]
Clear! Thanks!
