### ISSUE TITLE
Make 'testing.openTesting' effective when running tests via calling APIs

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode#153068]
Currently the setting `testing.openTesting` controls when testing view should be open. But I found that it's not take effect when the test is kicked of from calling the APIs - Create a `TestRunRequest` and pass it to `TestController.createTestRun()` in program.

It will be great if the setting will also take effect when running tests via calling APIs

**Comment by connor4312** [comment]
We intentionally don't do this right now

https://github.com/microsoft/vscode/blob/3862aa876e95b4fe76922349e8c440092dc4bf6c/src/vs/workbench/contrib/testing/browser/testingProgressUiService.ts#L61-L63

because currently test runners implement "auto run" using this API. I plan to aim to get https://github.com/microsoft/vscode/issues/134941 in this iteration which will let us remove that restriction.

**Comment by connor4312** [comment]
We now have a dedicated test results view, which will open instead of the explorer. I don't want to touch the aforementioned check because extensions have unfortunately implemented auto-run manually and depend on it, but this should be less disruptive.
