### ISSUE TITLE
[Meta] Avoid locking closed issues to reduce duplicates

### ISSUE THREAD

**Issue by qpwo** [microsoft/vscode#153046]
This is a meta-feature-request about this github repo itself. I think you should consider not locking closed issues, so that discussion and voting can continue after an issue is closed, instead of people having to re-open the same issue again and again and again [at least 20 times in this case](https://github.com/microsoft/vscode/issues/135175#issuecomment-962076244).

(The issue template's comment above says "Please search existing issues to avoid creating duplicates" but there's no way to add more information or anything to existing issues.)

I'm guessing the reason you lock issues is to avoid notification overload but surely there is some bot or something to unsubscribe all maintainers from closed issues? I hope I'm not wrong and therefore wasting your time here

**Comment by IllusionMH** [comment]
Unsubscribing devs from closed items would be receipt for 100% ignored comment. So what's the reason to allow them and later users would be complaining about being ignored?

Duplicates for recent(unlocked issues) are definitely bad, because in this case users can comment and provide new info, most likely versions will be same or adjacent.
Comments for old (theoretically unlocked) issues don't look more useful as new report from editor reporting tool with new version and more info. Reporter always can mention previous similar issues and add answers for questions that might be ignored in old closed issue.

The only instance where locked issue was a problem in recent years (I'm not on a Dev team so maybe they're were more) - new workaround was added later, but no comments with this info can be added to locked issue. This rare case doesn't look like reason to change existing behavior.

Probably not closing some low priority feature requests will be better option to solve actual request than disabling locking mechanism.

**Comment by qpwo** [comment]
Fair points, I'm sure you know better than I do what the difficulties and needs are in this repo, but wrt this:

> Unsubscribing devs from closed items would be receipt for 100% ignored comment. So what's the reason to allow them and later users would be complaining about being ignored?

I find the discussion among users often as helpful as whatever actual code change the devs end up making. If a closed issue is left unlocked and later becomes a very popular subject then the devs will probably hear about it eventually.

I also will often end up in a closed issue with hundreds of comments and find the solution for a problem by looking at the most upvoted comments. Typically most of the votes are cast long after the issue is closed.

---

Leaving some low priority feature requests open may be a better solution, as you said, if the stakeholders are interested...

**Comment by TylerLeonhardt** [comment]
Generally @IllusionMH hit the nail on the head. As much as I want to allow a place for folks to come back and say "hey I found this nice workaround now" for historical reasons, unlocking issues has plenty of downsides.

> The only instance where locked issue was a problem in recent years (I'm not on a Dev team so maybe they're were more) - new workaround was added later, but no comments with this info can be added to locked issue. This rare case doesn't look like reason to change existing behavior.

I'd even argue that you could open a new issue and say, "heres a workaround" and then someone on the team can just go and comment that workaround for documentation purposes. Not sure if this has happened but it's doable. 

@qpwo some of the things you call out can be solved with GitHub Discussions. It's something we are (slowly) playing around with to see if it has a space in our already constant feed of feedback. But in the absence of that, I think our process does generally a pretty good job of floating the top issues to the top to stay open, while having the lower pri ones that we likely won't get to in the next year or more stay closed so we don't have 100K open issues which would be impossible to manage.

Even that example you gave, there _is_ an open issue with 60 upvotes on it: https://github.com/microsoft/vscode/issues/62104

I'm going to close this because I think our process works pretty well today and with the statement that we do inwardly think about how to evolve this process. Right now, unlocking issues is not the direction we want to take.
