### ISSUE TITLE
Improve existing telemetry data

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#15321]

**Comment by bpasero** [comment]
@chrmarti re https://github.com/Microsoft/vscode/commit/c7f07d2490765d9531a56672defc8a8942297910

Instead of adding telemetry specific code to all the layers of editors, wouldn't it be better and more encapsulated to add a listener for editor open events and just do it from one place? I see you add a new event on editor open but it does not seem to be used anywhere. Though that could be used to log telemetry from an outside listener.

**Comment by chrmarti** [comment]
In general it might make more sense to keep the telemetry close to the code they are about because they often (will) need detailed information that we don't want to surface anywhere else.

I'm also not sure if there is a proper place in the layering for code that listens on events from the entire code base.

**Comment by bpasero** [comment]
@chrmarti can we maybe move it out of the stacks model into the guy who creates it? In this case `editorPart.ts`. This guy is already doing all kinds of telemetry logging and it could leverage your new listener to do the logging. My goal was actually to keep the stacks model very clean and simple and have sufficient events so that the outside world can react on changes to it.

I also noticed that you are using `any` in some places to mark the return value for the telemetry descriptor. I suggest to use `{ [key: string]: any; }` because that tells TypeScript that you expect an object and not a primitive type.

I also think that the type of `telemetryURIDescriptor` can be specified as `{ mimeType?: string; ext?: string; path?: string; }`

Overall we should try to avoid `any` as much as possible because if you explicitly say something is any, TypeScript will take it for granted. It would even be better to not put `any` and let TS infer it than putting it :).

**Comment by chrmarti** [comment]
@bpasero Sounds good. I admit I tend to use `any` in these edge cases where we send off the data and don't benefit much from the typing information. I'll take a look at doing what you suggest there too.

**Comment by bpasero** [comment]
@chrmarti yeah, I do think we have lots uses of any in cases where we talk about an object simply because that is what we used to do in the early days. I try to avoid it for newer code I write.

**Comment by chrmarti** [comment]
Also part of the outcome of #15383.
