### ISSUE TITLE
Test Debug Console Access from Quickpick

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#153344]
Refs #151771 , #152917 , #152400

- [x] macOS @paulacamargo25
- [x] linux @sadasant
- [x] windows @joaomoreno

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23153344%0A%0A&assignees=andreamah)

---
Testing for new ways to quickly view and access different debug consoles that are open.

## Set up:
Set up an environment that can launch multiple debug sessions (in `launch.json`, specify multiple launch configs and run them all at once). Ideally, each of them would print different text to the debug console. Ensure that this launches multiple debug consoles; ie:
![image](https://user-images.githubusercontent.com/31675041/175995679-447ee8ce-5113-4afb-90c4-c34b79a2628a.png)

### Testing Quick Access 
In the Quickpick menu, (`CTRL`+`P`), type `debug consoles `. This should show the list of debug consoles and an extra option to start a new debug session. 

Example:
![image](https://user-images.githubusercontent.com/31675041/175997020-0ec3d513-9de9-40e8-9922-276664ad2774.png)

- Clicking on a console name in this menu should focus the bottom debug console on that particular console.
- Clicking on the option to create a new debug session should bring you to the `debug ` quick access menu.
- Beside each debug console listing, it should have the status of the parent-most session that the debug console pertains to. Try changing the status (ie: stopping) these debug sessions to see if the status changes as expected.
- The list should look like the above screenshot, where only the option to `Start a New Debug Session` has an icon.

You should also be able to access the same menu by typing `?` in the Quickpick and selecting `debug consoles`.

![image](https://user-images.githubusercontent.com/31675041/176000101-71f21779-f82f-4c17-bcaf-7de34fbc2840.png)

### Testing Debug Console in View Menu
In the Quickpick menu, type `view ` to access the view menu. There should be a heading called `Panel / Debug Console` and it should list your debug consoles.

Example:
![image](https://user-images.githubusercontent.com/31675041/175999145-0763232b-983b-4f78-ad1f-c289100e344b.png)

Clicking on an entry should focus on that particular debug console (similar to what it does in its quick access).

**Comment by sadasant** [comment]
It works on Linux!

I first asked @andreamah for advice regarding how to create `an environment that can launch multiple debug sessions`, since I didn't have experience with that kind of scenarios. @andreamah so kindly guided me, I followed these steps:

- Created a new project in VSCode Insiders.
- Ran `git init` and `npm init`.
- Ran `npm i --save express`.
- Added file `app.js` (see below).
- Created `.vscode/launch.json` (also below).
  - I decided to use Firefox, since my linux machine only had Firefox. So, I installed the Firefox debugger extension.
- Ran the `Compound` task.
  - It worked, and I could switch the debug consoles.
- Verified that I could access the different debug consoles from:
  - Quickpick `CTRL`+`P`, then typing debug consoles.
  - With `?` on Quickpick.
  - With the View Menu.

So, I can attest the Linux test succeeded ✅

---

Files:

`app.js`

```js
const express = require('express');
const app = express();
const port = 8080

let num = 0;

function f() {
    setTimeout(() => {
        num++;
        console.log(app1 ${num});
        f();
    }, 1000);
}

f();

app.get('/', (req, res) => {
    res.send(app1 ${num});
});

app.listen(port, () => {
    console.log(Example app listening on port ${port});
});
```

`.vscode/launch.json`

```json
{
 "version": "0.2.0",
 "configurations": [
  {
   "name": "Launch Program",
   "program": "${workspaceFolder}/app.js",
   "request": "launch",
   "skipFiles": [
    "<node_internals>/**"
   ],
   "type": "node"
  },
  {
   "name": "Launch Firefox",
   "request": "launch",
   "type": "firefox",
   "url": "http://localhost:8080",
   "webRoot": "${workspaceFolder}"
  }
 ],
 "compounds": [
  {
   "name": "Compound",
   "stopAll": true,
   "configurations": [ "Launch Firefox", "Launch Program"],
   "presentation": {
    "group": "0_vscode",
    "order": 1
   }
  }
 ]
}
```
