### ISSUE TITLE
Code formatting settings

### ISSUE THREAD

**Issue by massimocode** [Microsoft/vscode#1533]
Hi

I was wondering if there's any option to change the JavaScript code formatting rules used?

I'm a big fan of code formatting but when VS code formats my code to insert spaces after my anonymous function keywords then it can really upset people that I work with who have OCD.

And thanks for the continued efforts guys!

**Comment by bpasero** [comment]
@jrieken @dbaeumer fyi

**Comment by dbaeumer** [comment]
@massimocode this is currently not possible.

**Comment by massimocode** [comment]
Just out of curiosity, how comes this one has the typescript label attached to it? Does the typescript language service provide the code formatting?

Also one thing I think I forgot to mention is that Visual Studio on Windows (i.e. the classic version) allows users to change some basic code formatting options like the one I mentioned above.

**Comment by dbaeumer** [comment]
Yes, the typescript language service provides the code formatting and the tsserver protocol has already options to control the formatting. However we haven't wired that up yet.

**Comment by karaxuna** [comment]
This behavior changed in version 0.10.10, now it removes space in anonymous function. This is very annoying.

**Comment by busfahren** [comment]
+1

**Comment by busfahren** [comment]
Worked for me in 10.9. and broke with 10.10.

Auto formatting throws an error with the ESLint configurations defined in our project (*space-before-function-paren*). As I rely heavily on auto formatting of trailing spaces and objects I had to downgrade Code. 

Though I couldn't find an option for the space in anonymous functions, is this due to the removal of the functionality behind `javascript.validate.lint.*`? In general, does/will Code's auto formatting derive rules from a workspace's `.eslintrc.js`/`.jshintrc`?
