### ISSUE TITLE
Title bar is too big on Windows 10 and Linux

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#153401]
> I can confirm what @ipsistak is seeing on Windows 10. On a 1080p external display with 100% scaling, VSCode is properly sized with zoom set to 0.
>
> When using an external 4K display scaled at 200%, native windows scale properly, but VSCode is generally oversized (this is not new). I used to set the zoom to -1, and this was leading to both the interface and menu bar being approximately correctly sized.
>
>On Linux, the issue is the same: when settings `xrandr --dpi 212` with a 4K display, the displaying in VSCode is way bigger than native apps. Setting the zoom to -1 helped to have both the interface and native title bar being sized approximately the same as native. Now, the title bar is quite big (see capture below).
>
>![2022-06-23_20-35-38](https://user-images.githubusercontent.com/6207605/175372907-8c5a3e21-00f2-45b4-9860-61d658fca4e6.png)

Originally posted here https://github.com/microsoft/vscode/issues/151803#issuecomment-1164746278

**Comment by deepak1556** [comment]
@sbatten is this issue still relevant, I don't have the setup to verify. Can you confirm ?

**Comment by sbatten** [comment]
I am not sure, I currently don't have Windows 10 on any machine. I can try to set that up, but perhaps @ipsistak can confirm faster?

**Comment by ipsistak** [comment]
Just tested on Windows 10 - I don't see a different behavior after updating to VSCode 1.74 (i.e. the "issue" remains, although I understand this is by design)

As of June, VSCode only makes the title bar bigger and never smaller than what is considered "OS standard size" - this means users have no fine-grain control over the size of the title bar font and height, especially in HiDPI screens with scaling. 
Also, in Windows 10 and several other OSes, the "Standard title bar height" is not respected among apps, leading to UI scaling issues. 


Here is a possible workaround:
The issue becomes apparent when the system preference "Make text bigger" is set to >100% and there is also screen scaling.  In Windows 10, some windows (including the Windows Explorer) do not respect the text scaling setting in their title bar.  Others scale the title bar text by the Text Scaling factor.

If your title bar is dis-proportionally large, consider setting the text scaling to 100%. You can find this setting in Settings -> Ease of Access -> Make text bigger. 


Ideally, VSCode could have a flag to enable scaling of <100% for the title bar, or maybe allow for a separate titlebar scaling factor. This would make the application user-friendly across different OSes and display densities, allowing users to customize their editor according to their preferences.

**Comment by sbatten** [comment]
@deepak1556 this is interesting, because at my level I'm just setting default sizes. Since everything we do works with pixel sizes, we have no clue what the users text size settings are. @ipsistak thanks for the info, but I'm thinking we may just have to live with the workaround.

**Comment by ipsistak** [comment]
I don't see how this is out of scope. VSCode was working great before the June update, across all platforms. After the update, the close button is, as you see, four times the size of all other windows. Since it was broke due to a VSCode update, how is this out of scope?

Ease of Access settings are important: many users cannot use a computer without making the text bigger. 

For all those users, this workaround is not a solution. Essentially this workaround demands that users with impaired vision sacrifice the usability of their entire computer, just so that the titlebar of vscode is not huge.

Please reconsider, keeping in mind that developers with vision impairment find it difficult to use VSCode after the June update.

**Comment by deepak1556** [comment]
@ipsistak with `1.74` the window controls are drawn natively by the runtime which adapts to the text settings, when trying a text scaling > 100% the following image shows the scaling of window controls on VSCode, MS Edge and File explorer. You can see similar behavior between both chromium applications. As @sbatten mentioned, since we don't know the text scaling values from the runtime, it is hard to control the behavior at the application level.
![Window_controls](https://user-images.githubusercontent.com/964386/208653891-d8306d26-5483-4671-b322-8b18651d6795.png)

**Comment by ipsistak** [comment]
I understand that the rendering system has been updated - what I find difficult to understand is why I can make the title bar even bigger (by zooming in, pressing ctrl+=), but never smaller. 

This behavior seems very inconsistent. Furthermore, there is really no case where a user would need an even bigger titlebar, but there are many cases where a users would need a thinner one.

My proposal is to allow the title bar to become smaller when zooming out   (ctrl + - ) , or introduce a separate zoom factor for the title bar.

**Comment by sbatten** [comment]
The window controls themselves are upstream and cannot be made smaller than the starting value.
