### ISSUE TITLE
keep profile when loading new workspace

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#153472]
@sandy081 I love the new profiles but I don't like that the profile resets to "default" if a new workspace is loaded.

A profile is a "mode" for me and I want to stay in that mode until I explicitly switch to another mode. I don't want to have VS Code decide what mode to use.

**Comment by sandy081** [comment]
Thanks for the feedback @weinand.

Yes this was discussed in our working group discussion and we are validating this and scenario.

IMO it might depend on the context from which I am opening a new workspace. A new workspace shall always use the profile from the current active workspace and if the workspace has already profile associated, it shall use it.

**Comment by weinand** [comment]
> A new workspace shall always use the profile from the current active workspace and if the workspace has already profile associated, it shall use it.

Yes, that would work for me. But today it's not working like this.

**Comment by sandy081** [comment]
Yup, it is not yet currently supported but we are planning to.

**Comment by sana-ajani** [comment]
We're getting mixed feedback on this. Some users have mentioned they would like to choose which profile to open the new workspace in, instead of opening the most recently used profile or the profile of the current window. I think there's a few options. We can have each workspace remember the profile it is associated with or last opened with, or we can have a setting to choose to open each new workspace in a default profile or the recently used profile.

**Comment by alefragnani** [comment]
Since you are getting mixed feedback, why not add a _setting_, and let the user decide?

I agree with @weinand, and see profile as a _mode_ which VS Code should remain active, until I open an _old_ workspace that used a different profile. But I also see people/scenarios that uses a _basic_ profile for any project (maybe a “light mode”) and would switch to a more complete profile only when necessary.
