### ISSUE TITLE
No custom hover for menu-only layout control

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#153429]
re https://github.com/microsoft/vscode/issues/150788

```
"workbench.layoutControl.enabled": true,
"workbench.layoutControl.type": "menu",
```

* use the config above
* hover over the layout control
* :bug: native hover
* (any other value for `.type` uses the custom hover)

**Comment by sbatten** [comment]
This is actually because the `SubmenuEntryActionViewItem` extends `BaseActionViewItem` whereas the `MenuEntryActionViewItem` extends `ActionViewItem`. 

`ActionViewItem` is what provides the custom hover capability.

Here is a quick summary of the ActionViewItem structure:
```
MenuEntryActionViewItem
ActionViewItem (handles hover delegate)
BaseActionViewItem (IActionViewItem)
Disposable

SubmenuEntryActionViewItem
DropdownMenuActionViewItem
BaseActionViewItem (IActionViewItem)
Disposable


**extends ActionViewItem**
ActionWithDropdownActionViewItem
MenuSeparatorActionViewItem
MenuEntryActionViewItem
ReactionActionViewItem
DropDownMenuActionViewItem
ToggleMultilineActionViewItem
QuickFixActionViewItem
NotebooKernelActionViewItem
StatusBarActionViewItem

**extends BaseActionViewItem**
ActionViewItem
SelectActionViewItem
DropdownMenuActionViewItem
BaseMenuActionViewItem
ToggleActionViewItem
DropdownWithPrimaryActionViewItem
DropdownWithDefaultActionViewItem
ActivityActionViewItem
StartDebugActionViewItem
ReplFilterActionViewItem
MarkersFilterActionViewItem
FolderSettingsActionViewItem
TestingExplorerFilter
```

There is no clear guidance on how to use these aside from the very recommended approach of using `createActionViewItem` when using a toolbar/actionbar. Ideally we could move to only one "BaseActionViewItem", then several reusable widgets that extend that.

![image](https://user-images.githubusercontent.com/6561887/176535816-ce6d53a7-61f1-4ed2-a8d7-accf91f63e9e.png)

**Comment by jrieken** [comment]
> ActionViewItem is what provides the custom hover capability.

I have changed that (which closed this issue) but I am also in for making this all simpler. Something tells me that we should have a higher level (workbench, platform) "toolbar controller" that you just create a for a menu (id). Internally it would use the lower level widgets but it would do all the lifting and glue that today various util-functions do

**Comment by sandy081** [comment]
I still see native hover. I assume this is not expected.

<img width="708" alt="image" src="https://user-images.githubusercontent.com/10746682/181456067-3f744304-9845-434a-80e1-751318faad77.png">
