### ISSUE TITLE
Is the SCM commit view action button redundant?

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#153514]
Testing #153366

There's the giant commit button just below, is the view action just causing clutter?

![image](https://user-images.githubusercontent.com/2193314/176211759-7357174e-dde3-42fa-b1db-73ff65cd87ea.png)

**Comment by lszomoru** [comment]
It is, and I would love to hide it in case the "Commit" action button is enabled.
@joaomoreno, do you think that would be too disruptive given that the "Commit" action button is enabled by default?

**Comment by lszomoru** [comment]
I think that in order for us to do this, we should also be doing https://github.com/microsoft/vscode/issues/153504

**Comment by joaomoreno** [comment]
I'm too scared to hide this action. You will _definitely_ get angry mobs.

Plus, what of the people who have entirely disabled the scm button altogether? Wouldn't you have to _understand_ this setting from the git world, in order to pull this off? Ie, the action still needs to be there, in case the button is disabled altogether.

I wouldn't lump this change together with the work you've done here.

**Comment by Tyriar** [comment]
Feel free to close off if it's not likely to happen

**Comment by lszomoru** [comment]
I will keep this issue opened, as long term I would like to hide that action.

**Comment by gjsjohnmurray** [comment]
Users can now choose to hide this button by right-clicking on it.

**Comment by lszomoru** [comment]
Given that users can now hide the button, I think that it is fine to close this issue.
