### ISSUE TITLE
Emmet - HTML coding: new line item is not inserted when combining elements with "+" 

### ISSUE THREAD

**Issue by alexkolt** [Microsoft/vscode#15358]
- VSCode Version: 1.7.1
- OS Version: Windows 10

Steps to Reproduce:

1. Open HTML file.
2. Type in "form>input+button" and press tab.
3. Expected output:
```
<form>
  <input/>
  <button/>
</form>
```
4. Actual result:
`<form><input/><button/><form/>`

Unfortunately this is a problem that doesn't get solved with automatic code formatting.

updated formatting

**Comment by mrmlnc** [comment]
Hellom @alexkolt,

I don't fullu understand your problem. You can give to community more detailed information?

I try your code example in official Emmet site and VS Code and get identical results:

![2016-11-11_17-06-43](https://cloud.githubusercontent.com/assets/7034281/20217532/4ab709ba-a831-11e6-8efa-a41754006c75.gif)

**Comment by alexkolt** [comment]
Sorry I didn't preview the post.

**Comment by mrmlnc** [comment]
Well, @alexkolt, maybe this is "language barrier", but I don't understand your problem.

Emmet by default (out-of-box, by Emmet author) creates single-line tags in one line.

**Comment by misterhtmlcss** [comment]
@mrmlnc I have one for you.

I add head+body>header>nav^main+footer and it doesn't work right. See attached. Then I tried an easier one; head+body>header>nav and it only extended the last one nav with <nav> </nav and left the rest intact in emmet format. Also see attached.

What do you think? Bug?

FYI. I can't even do a simple one in the official release 1.7.x, but in today's (didn't try it in yesterday's) Insiders I can do the second one at least.

Haven't tried Emmet in anything that isn't the latest, so can't say when this issue popped up. Found this post and since it looked resolved, but related I thought I'd keep it rolling with mine.
![screen shot 2016-11-11 at 10 45 37 pm](https://cloud.githubusercontent.com/assets/13112566/20235966/e2f3574a-a860-11e6-9286-2edf9c5441bf.png)
![screen shot 2016-11-11 at 10 45 51 pm](https://cloud.githubusercontent.com/assets/13112566/20235968/e2f3f1fa-a860-11e6-80d0-f13aa050ff93.png)
![screen shot 2016-11-11 at 10 46 21 pm](https://cloud.githubusercontent.com/assets/13112566/20235967/e2f3a29a-a860-11e6-9a21-4d98d7a489e3.png)

**Comment by mrmlnc** [comment]
@misterhtmlcss, thanks you for more detailed description, but I have bad news for you.

VS Code (as and other editors) use official Emmet package. Therefore, all editors have the same bug. You can always check it out using the official site: http://docs.emmet.io/

![2016-11-12_12-47-58](https://cloud.githubusercontent.com/assets/7034281/20236947/46eb91ac-a8d6-11e6-8194-95b60bcdc64d.gif)

If you see that when you press <kbd>Tab</kbd>, your expression expands incorrectly, the first thing you want to check it out on the official website of Emmet.

In your case, when the expression is revealed not fully - blame for code snippets. Just try to remove snippets for `footer`.

**Comment by misterhtmlcss** [comment]
I'm not sure what you are saying here 'In your case, when the expression is revealed not fully - blame for code snippets. Just try to remove snippets for footer.' 

However when I drop in my code to Emmet it works perfectly. That's the second image (whitebackground) which wasn't clear in my first post. So if you are using Emmet and it works on their site, whose issue is this? I'm wondering if there is a common plugin we (the general populace) is using that could be interfering since this seems to be popping up regularly. 

Additionally the bug if it was emmet would be consistent from Insiders to Code (General Release version) and yet it is not the case for me. I run both and one is not performing in a manner remotely consistent with the other.

I think this is worth pursuing as Emmet is a huge productivity tool for many. Let me know if there is more information I can provide, such as a complete list of my plugins, etc. I'm happy to do what is necessary to understand how this could be happening. It's an odd one for sure.

**Comment by alexkolt** [comment]
Thanks, confirmed as issue with Emmet and not VSCode.

**Comment by mrmlnc** [comment]
@misterhtmlcss,

I want to say that you should try to remove `HTML Snippets` extension.

**Comment by misterhtmlcss** [comment]
@mrmlnc you found the problem. Thanks I just removed it from both Insider and production versions of VSC and now they work the exact same way and interpret the Emmet code correctly. Thank you for your assistance dealing with this bug with the VSC ecosystem. 

See @alexkolt that's how you solve things ;)

**Comment by mrmlnc** [comment]
@misterhtmlcss,

Nope, this is related only to VS Code because:

> Yes - by default `tabCompletion` takes precedence over emmet
>
> @jrieken (https://github.com/Microsoft/vscode/issues/13508#issuecomment-252926869)
