### ISSUE TITLE
Diff editor character diff should use stronger colour

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#153563]
We have very smart character diffing algorithm done by @hediet
However our character level diff colours are not so strong, and they easily blend in with the rest of the green.

@misolori could we try to introduce some stronger colour to make this nice feature more prominent?

![Screenshot 2022-06-28 at 20 06 40](https://user-images.githubusercontent.com/1926584/176252307-de8aa4f7-6212-48a4-bfe8-394bbfb1c41e.png)

**Comment by isidorn** [comment]
fyi @daviddossett since Miguel is on vacation.
Though this is not urgent.

**Comment by misolori** [comment]
I wonder if we'd need to introduce another color token specifically used when diffing to be stronger when it's on a diffed line?

**Comment by gdh1995** [comment]
Hello, today my VS Code updated to v1.70 and I think the background color of `.char-insert` (`diffEditor.insertedTextBackground`) is a bit too "strong" for the theme of `Light+` on a TypeScript file, since the theme make some symbol names not black but colorful.

Here's what I saw:
![image](https://user-images.githubusercontent.com/5547703/183016160-3cab005f-e925-43f9-be26-5387c2334dfc.png)

I've reverted `diffEditor.insertedTextBackground` in my `settings.json`, and IMO it's enough. So here I want to suggest re-thinking about those colors and contrast ratios.

BTW, "diff colors" used by GitHub webpages look good enough, though they're not transparent
