### ISSUE TITLE
Edit Sessions: Unexpected Behavior for Resuming Last Session

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#153566]
Testing #153386

I was expecting that resuming the last session multiple times would do the same thing as doing it once, but it seems like it works sort of like a stack where it starts restoring old sessions.

Repro steps:
1. In either the GitHub repository or the local clone, in any file:
  a. type `"one"`
  b. save file 
  c. store the current edit session
2. repeat with `"two"` and `"three"`.
3. In the other repo location, resume the last session three times. You should see `"three"`, then `"two"`, then `"one"`. I expected calling this multiple times to just unload the change saying `"three"` all the times that you resume the last session.

If this isn't what edit sessions is supposed to do, feel free to ignore and close 😅. I just expected something like this to say `pop/push last session` or something instead of `store/resume last session`.

**Comment by joyceerhl** [comment]
Yeah, it is effectively a stack because each edit session is deleted from storage after being resumed, the intention being that while we allow keeping multiple edit sessions at once, we don't want to keep this data around forever. Closing as as-designed for now but we should revisit if we get additional feedback on this behavior.
