### ISSUE TITLE
Do not disturb icon should be an un-crossed bell when DND is off

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#153553]
Testing #153330

The "do not disturb" button in the notification center is always a crossed bell. I think when DND is off, it should be uncross. Similar to a volume icon which is 🔇 when muted or 🔈 when unmuted.

**Comment by daviddossett** [comment]
That was in the original design, and makes sense on paper, but I think it's somewhat confusing to have the normal bell as the indicator for a do not disturb mode. I wouldn't know what this bell does in this case:

<img width="163" alt="CleanShot 2022-06-28 at 10 28 40@2x" src="https://user-images.githubusercontent.com/25163139/176245595-874fbc0e-98ef-46de-9f5a-fd3d5397c1dd.png">

cc @rchiodo since I see you opened a similar issue.

**Comment by daviddossett** [comment]
Closing this as I haven't heard any other feedback on this and I'd prefer to avoid the strange icon duplication above. We can reopen if we hear more feedback that this is confusing.
