### ISSUE TITLE
Notebook scrolling out of sync

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#153708]
related https://github.com/microsoft/vscode/issues/148164

* have my-endgame-GHINB
* run all cell, scroll to the bottom, and run `touch <path>`
* scroll upwards
* 🧀 notice an occasional layout shift, the alignment of code and MD cells is getting out of sync

##### Recording of the recording

https://user-images.githubusercontent.com/1794099/176478910-74a1eb2f-a83e-4557-bf47-58931482a824.mov

##### Recording of the scroll

https://user-images.githubusercontent.com/1794099/176479002-7df7ca80-24ff-4676-8911-ffd0e76fbe5a.mov

**Comment by jrieken** [comment]
(what the heck... it seems GH confuses the default commenting command and I keep closing/re-opening issues)

**Comment by roblourens** [comment]
The first one shows an editor adding and removing the horizontal scroll bar, I have no idea why that would happen and can't repro it, any idea @rebornix?

The second is editors getting their scrollbars, we don't know whether they will overflow until they are rendered. I'm not sure whether that would be fixed by keeping view state across the model reload, like the other issue.

I'm not that motivated to work more on these specific cases because a model reload is probably not actually that common. The most common case would probably be doing a `git pull` with changes in that file.

**Comment by jrieken** [comment]
> I'm not that motivated to work more on these specific cases because a model reload is probably not actually that common. The most common case would probably be doing a git pull with changes in that file.

Can you explain to me why the handling of reload is different from clear all output (or an API notebook edit)?

**Comment by roblourens** [comment]
You are replacing all cells with a totally different set of cells, vs editing an existing cell. Or inserting some cells with a notebook edit that are probably actually new.

**Comment by rebornix** [comment]
In the first gif, the editor of the first visible code cell is always in the viewport, meaning there is no re-render while slightly scrolling up and down. However the horizontal bar hides sometimes, it feels wrong to me.

**Comment by connor4312** [comment]
When I follow the directions and run `touch .vscode/notebooks/my-endgame.github-issues`, I see the content jump and all outputs get cleared, which prevents verifying with the original steps. Is this a different bug or are there different steps now?

**Comment by roblourens** [comment]
The outputs are going to be cleared because they aren't saved. But when you scroll up after this model reload, there should be less jumping with the markdown cells
