### ISSUE TITLE
Simplify shell integration manual install by deferring to the code CLI

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#153921]
Currently install is a little cumbersome, for example:

> Add the following to your [PowerShell profile](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_profiles?view=powershell-7.2), replacing `<InstallDir>` with VS Code's installation directory. Run `code $Profile` in pwsh to open the file in VS Code.
>```pwsh
>if ($env:TERM_PROGRAM -eq "vscode") {
>  . "<InstallDir>\resources\app\out\vs\workbench\contrib\terminal\browser\media\shellIntegration.ps1"
>}
>```

It would be much nicer if this was encapsulated within the CLI, something like:

```
code shell-integration
```

We should also make sure these cases are covered:

- Remote development extensions - injection works currently but manual install doesn't talk about the server paths
- Regular SSH - it's not so easy to get the shell integration script to the remote machine

**Comment by FranklinYu** [comment]
Hi, I’m thinking about another way, in addition to the CLI mentioned above: how about creating a package (deb/rpm) with only https://github.com/microsoft/vscode/tree/main/src/vs/workbench/contrib/terminal/browser/media directory? This way I only need to install this on the server if I want to SSH to it without remote development (assuming that for some reason I don’t want remote development), since I don’t need the other part of VS Code. This can even go into Debian/Fedora because it is pure MIT, and the package doesn’t have any dependency.

I understand that this won’t serve all users (e.g. Windows Server users), so the CLI-way still works as a catch-all.

**Comment by felipecrs** [comment]
When inside Remote - WSL or Remote - SSH (probably Containers too), the Resources Dir can be found with:

```zsh
realpath "$(dirname "$(command -v code)")/../../resources"
```

- `command -v` vs `which`: https://www.shellcheck.net/wiki/SC2230

- calling `realpath` is better than `readlink -f` since it at least warns the user if the path can't be resolved.

- echo isn't required anymore

In such case, the latter snippet also needs to be adjusted:

```diff
if [ "$TERM_PROGRAM" == "vscode" ]; then
-   . <InstallDir>/app/out/vs/workbench/contrib/terminal/browser/media/shellIntegration-bash.sh
+   . <InstallDir>/out/vs/workbench/contrib/terminal/browser/media/shellIntegration-bash.sh
fi
```

And when not running through Remote, I wasn't able to find such a file in a Linux .deb installation. Even by following the original instructions, which would probably resolve to a path like: `/usr/bin/resources` which isn't valid too.

The correct path would be `/usr/share/code/resources` instead. And, in such case, the latter snippet would be correct.

**Comment by Tyriar** [comment]
@felipecrs thanks for the info, this is what we're planning for the improved experience in #155046:

```pwsh
# pwsh
if ($s=$(code --shell-integration pwsh)) { . $s }
```

```sh
# bash
. "$(code --shell-integration bash)"

# zsh
. "$(code --shell-integration zsh)"
```

This will also work on the server so the remote extensions will be covered the same.

**Comment by joaomoreno** [comment]
@Tyriar I'm actually worried about perf here. Running `code --shell-integration` will be slow in many systems, slow enough to notice lag when launching a shell.

Given that this always returns the same value every time we execute it... could we perhaps do something similar to [macOS's CLI install command](https://code.visualstudio.com/docs/setup/mac#_launching-from-the-command-line)?

**Comment by Tyriar** [comment]
@joaomoreno installing it directly like the command there isn't portable across system though. We are looking into having the `code` CLI redone in rust which will make it plenty fast enough as we won't need to launch node.

I also considered having it in the .sh file itself, but that wouldn't work unless the cli is sourced, not run, and it also wouldn't work at all in pwsh since our CLI is a batch script.
