### ISSUE TITLE
How to set Heap size

### ISSUE THREAD

**Issue by zhfnjust** [microsoft/vscode#153965]
my Extension is a debugger which implement DAP protocal. It loads a lot of data into memory at startup, which triggers **javascript heap out of memory error** .  

For this kind of error, we can usually solve it by adjusting the heap size `--max_old_space_size=4096`. But I didn't find any way to set this parameter for extension.

I found a type question but no fresh answer  #10149.

So how to set Heap size for my extension to avoid **javascript heap out of memory error** .

**Comment by weinand** [comment]
If your DAP implementation runs directly in an extension, then you share the extension host (node.js) with all other extensions und you cannot control things like heap size.
In order to work around this, I recommend to implement DAP in a separate process that you launch from the extension itself. In this case you in control of the node.js process and can pass whatever arguments you want.
