### ISSUE TITLE
Visual Studio implementation of "Home"/"End" keys

### ISSUE THREAD

**Issue by wkamir** [Microsoft/vscode#15401]
- VSCode Version: 1.7.1
- OS Version: Windows 10

Steps to Reproduce:

1.  select multiple lines of text so that the cursor is then at the first line of the selection (select from the bottom up)
2.  press the "End" key.

In regular Visual Studio, the cursor navigates to the end of the selection.
In VS Code the cursor navigates to the end of the current (first) line.

I think it should behave as in regular Visual Studio - when trying to copy/paste some CSS class definition I always end up pasting the code into the code I was copying from...

Is there maybe a key-binding command for "go to end of selection"?

**Comment by alexandrudima** [comment]
I had to roll this back due to too many complaints. See #17011

**Comment by alexandrudima** [comment]
To keep the number of issues in our inbox at a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: we look at the number of votes the issue has received and the number of duplicate issues filed. Thank you for your time and understanding.

If you disagree and feel that this issue is crucial: we're happy to listen and to reconsider.
