### ISSUE TITLE
Python code execution speed is slow out of VSCode

### ISSUE THREAD

**Issue by github-lwc** [Microsoft/vscode#15404]
hi,
It's very slow when I run the code of python, about 10 seconds to complete, but it is very fast on sublime, it's about 2 seconds to finish. If I set the value to 1000000, sublime can be completed within 10 seconds, but it is not response on vscode, you can try use the code on vscode ,and hope fix it.think.

![screenshot](https://cloud.githubusercontent.com/assets/23410231/20238344/d7ce42f8-a923-11e6-8c9e-dcc0be650aa4.jpg)

below is the python code:
for i in range(1,1000000,1):
    print i

**Comment by mrmlnc** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/15391?

**Comment by gertcuykens** [comment]
I don't use Python but can you do the following test please

1) screenshot extentions tab and disable all plugins
2) python test2.py in dos terminal
3) python test2.py in a vscode terminal manually

If for some weird reason it is still slower in the vscode terminal then in dos then it's a vscode bug.
If you are using a python extension that runs on the background, it's a extension bug.

The only other explanation I can think of is because sublime has python build in for its scripting it is doing some jit optimization?

**Comment by aeschli** [comment]
@github-lwc Do run your code using a VSCode task, or do you run it in the internal terminal?

Yes, as @gertcuykens writes, can you make measurements (add some console log with time information to your program) and compare it when run from a external (OS) terminal.

**Comment by jrieken** [comment]
I'd blame this on the slow output channel

**Comment by isidorn** [comment]
@jrieken and me improved the output channel -> closing
Users let me know if you still see the slowness with latest vscode releases
