### ISSUE TITLE
vim cursor not switching between extension profiles

### ISSUE THREAD

**Issue by Kevin-Delnoije** [microsoft/vscode#154285]
Testing #153384

one extension with vscodevim and one without, while switching cursor stays fat.

**Comment by alexdima** [comment]
The vscode editor API has a "set" cursor style API and once a certain cursor style is set for a particular editor instance, this is remembered for the lifecycle of the editor (until the editor is closed and reopened). When switching profiles, we do not close and reopen editors, so the previous cursor style remains.

@sandy081 Giving this to you in case you want to add that editors get reopened when switching profiles, otherwise I would close this as won't fix.

**Comment by sandy081** [comment]
Thanks for clarification. I would close this as won't fix then
