### ISSUE TITLE
PRINTING!  PRINTING!  PRINTING!

### ISSUE THREAD

**Issue by DyessGG** [microsoft/vscode#154304]
How many times does the community have to request the capability to PRINT our code, keeping the coloring and formatting?  None of the extensions work without major issues.

Why was it left off and why is MS refusing to acknowledge this request?

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode/issues/5953

**Comment by PeterWone** [comment]
@DyessGG 

> How many times does the community have to request the capability to PRINT our code, keeping the coloring and formatting? None of the extensions work without major issues.

There are exactly two extensions supporting printing, "Print" and "printCode"

Both support syntax colouring.

I went out of my way to preserve formatting, with sufficient success that one of the reviews comments on this even though my documentation never claims it as  a feature.

While it is true that printCode hasn't seen an update since 2018, speaking as the author of Print I'm calling you out on the claim that it has "major issues". The only outstanding issue on my repo relates to publication to OpenVSX, which is an alternate marketplace that competes with Microsoft's and is not a priority. All other issues have been resolved within a week, often within 24hrs, and _you_ have _never_ reported an issue. Print is actively maintained in every respect. It doesn't even have any known vulnerabilities in its dependencies.

If you are aware of an issue, major or minor, I suggest you report it so I can address it.

**Comment by DyessGG** [comment]
There are WAY more than "exactly 2" extensions claiming to support printing.  I have tried several.  None (I have tried) work without mangling the formatting, ignoring syntax coloring, forcing extremely large fonts/borders, outright ignores all settings for paper size.  Others, like yours, force using a browser to perform the actual printing!  

That is NOT integrated printing capability.
