### ISSUE TITLE
[VS Code extension API] CompletionItem sortText support numbers ?

### ISSUE THREAD

**Issue by shezhangzhang** [microsoft/vscode#154330]
Note that the `sortText` only support string. But in my case, I want to sort with the number like this:
```js
4, 8, 12, 24 // This is what I want
```
NOT
```js
12, 24, 4, 8 // Because sortText sort with string '12', '24', '4', '8'
```

DOCS HERE: https://code.visualstudio.com/api/references/vscode-api#CompletionItem

<img width="764" alt="image" src="https://user-images.githubusercontent.com/26793777/177681581-e4223d38-0c32-454d-9fd7-bacee615b76f.png">

**Comment by shezhangzhang** [comment]
### Be specific
I want the these CompletionItems to sort by number:

```js
item.sortText = `a-${value}-${key}`; // sort by value (number)
```

EXPECTED:

marginXXS: 4
marginXS: 8
marginSM: 12

NOT:
<img width="329" alt="image" src="https://user-images.githubusercontent.com/26793777/177707124-12d4b6a9-082c-42a6-a618-e7a963f219cc.png">

**Comment by jrieken** [comment]
Internally we compare all items from all providers (not just your extension) with each other. Because of that we cannot have two types (string and number) because we wouldn't know how to compare them. For your case it might be possible to pad the strings (`[1,2,3,11,12,13].map(n => String(n).padStart(3,'0')).sort()`) to find another order-preserving projection

**Comment by shezhangzhang** [comment]
Brilliant!!!! This is JS magic! Thanks! @jrieken
