### ISSUE TITLE
`workbench.startupEditor` should support opening a terminal in editor area

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode#154366]
I use VS Code as my primary terminal emulator. The first thing I do when opening it is usually to run the `workbench.action.createTerminalEditor` command so that I can start navigating around, and then using `code .` to open a project. It would be great if the `workbench.startupEditor` supported opening a terminal in the editor area.

**Comment by akiekintveld** [comment]
FWIW if this wouldn't be too involved I'd be happy to open a PR if you could provide a few pointers to the relevant parts of the code to wire together.

**Comment by Tyriar** [comment]
I think this makes sense, moving to @lramos15 as the owner of getting started

**Comment by Tyriar** [comment]
fyi @meganrogge

**Comment by lramos15** [comment]
@Tyriar Wouldn't you just add terminals to the New File... menu? semantically it might be weird so maybe it should be renamed to `New...`

**Comment by Tyriar** [comment]
Feels really weird to have in the New File menu and renaming that just for this would make that action more ambiguous

**Comment by lramos15** [comment]
> Feels really weird to have in the New File menu and renaming that just for this would make that action more ambiguous

Otherwise it becomes a completely separate entry no? 
- New File...
- New Terminal in Editor area.

Just feels very specific

**Comment by lramos15** [comment]
@Tyriar Sorry misread the issue and thought this was talking about the getting started startup editor that was default. Yes we can do this

**Comment by lramos15** [comment]
@Tyriar Going to need help from the terminal side of things here. I have created https://github.com/microsoft/vscode/commit/de17d3c02bcba93522be51ce575f2c8ce40ea6a2 but it does not open a terminal due to the fact that you cannot pass in a "untitled" terminal and have one created. I tried to make an arbitrary resource but no terminal is opened

**Comment by sagebind** [comment]
Just like to add that this would also be very useful to me as well. Makes opening a new window with a ready terminal just one click by launching VS Code with no workspace. Like the user who opened the issue, I tend to open workspaces using the `code` command from a terminal more often than any other method of opening workspaces, simply because I operate out of the terminal a lot just as a default.

Another benefit is that it seems like it just increases the consistency of `startupEditor` to support something like this.

**Comment by Tyriar** [comment]
> Going to need help from the terminal side of things here. I have created https://github.com/microsoft/vscode/commit/de17d3c02bcba93522be51ce575f2c8ce40ea6a2 but it does not open a terminal due to the fact that you cannot pass in a "untitled" terminal and have one created. I tried to make an arbitrary resource but no terminal is opened

I think this can be solved by deferring to the create terminal in editor area command instead of trying to create a URI. Adjusting assignees...
