### ISSUE TITLE
Web: Language extensions should not be installable

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#154461]
On the web, we just make NLS work without installing language extensions. But they still appear installable when listed in the extensions view. One idea: show a `Set Language` button, instead of the `Install` button, or similar.

cc @TylerLeonhardt

**Comment by TylerLeonhardt** [comment]
Personally I would prefer to hide them so we get closer to our long term vision of Language Pack _Extensions_ as an implementation detail.

**Comment by TylerLeonhardt** [comment]
Isn't this more in bug territory since today you get an "install on browser" button that, when clicked, actually does nothing whatsoever? That's confusing to the user.

**Comment by joaomoreno** [comment]
My 2c: I wouldn't go and hide them. There still might be value in showing them, for reviews, links, etc. Also it wouldn't match the desktop experience until that one also aligns with the long term vision. It would be confusing to see them in one environment and not in the other.

If resolving the bug involves simply hiding them, then yes, it's a bug. Otherwise, if we're planning on having a button to `Set Language`, I argue this is a feature request.

**Comment by sandy081** [comment]
Added **Set Display Language** button instead of **Install** button for language pack extensions in web. Please take a look at the following video:

https://user-images.githubusercontent.com/10746682/178490443-64d14377-9f65-4b8e-a153-5606167eb73f.mp4

If the language is already set, then no action is shown. Please see the German Language Pack extension

![image](https://user-images.githubusercontent.com/10746682/178490655-cd1052d0-d999-4b90-ba4d-066c2ab7a862.png)
