### ISSUE TITLE
Saving with "files.trimTrailingWhitespace": true clears the redo buffer if you have any trailing whitespaces.

### ISSUE THREAD

**Issue by geon** [Microsoft/vscode#15458]
- VSCode Version: 1.7.1 
- OS Version: Mac OS 10.12 

Steps to Reproduce:

1. Add a line with trailing whitespace.
2. Add another line.
2. Undo the added line.
3. Save.
4. Attempt to redo. (You can't.)

"files.trimTrailingWhitespace": true probably should not manipulate the open file, just the one being saved. Not being able to redo is unexpected and can lead to lost work.

**Comment by alexandrudima** [comment]
The problem is that we don't support "parallel" redo stacks. i.e.:
* once you undo the added line, the redo stack contains adding the line. 
* once you save, the save participant that trims trailing whitespace acts "on your behalf" and deletes the trailing whitespace
* this causes the redo stack to be cleared, similar as if you manually went in and deleted the trailing whitespace.

The same issue exists with format on save or the append newline on save save participants.

I see the concern, this could be mitigated by a local history feature, or would you expect a prompt/dialog in the case that a save participant attempts to edit a buffer with a redo stack? Do you know what other editors do in such cases?

**Comment by geon** [comment]
>  we don't support "parallel" redo stacks

You don't need full stacks. The trimmed version for saving would never be undone, just discarded.

One alternative is to trim trailing whitespace continuously.


> Do you know what other editors do in such cases?

Sublime 3 behaves just like this.
