### ISSUE TITLE
remapping keyboard shortcut for delete not working

### ISSUE THREAD

**Issue by Shayac** [Microsoft/vscode#15470]
- VSCode Version: 1.7.1
- OS Version: OS X el capitan

Steps to Reproduce:

1.  add ```{
        "key": "cmd+delete",
        "command": "editor.action.deleteLines",
        "when": "editorTextFocus && !editorReadonly"
    }``` to keybindings.json
2.  hit cmd+delete while editing. still triggers the original shortcut

I tried mapping the editor.action.deleteLines command to another key and it worked. 
I tried mapping cmd+delete to another command and it did not work.

**Comment by Shayac** [comment]
I played around w/ this a bit more and it seems I can't map a shortcut to any key combination containing `delete`

**Comment by Shayac** [comment]
So I just managed to figure this out. The `delete` key is called `backspace` in vscode, similar to what the key is called on Windows, even on Mac. 
Changing 
`
{
 "key": "cmd+delete",
  "command": "editor.action.deleteLines"
}
`
to 
`{
  "key": "cmd+backspace",
  "command": "editor.action.deleteLines"
}`
did the trick. 
Maybe it should be renamed `delete` when on mac?

**Comment by alexandrudima** [comment]
@Shayac sorry about that, but when one presses the key labeled as "delete" on Apple keyboards, the key code for the backspace key is generated.

We cannot "rename" all instances of the backspace key on the mac as "delete" because you could attach an external (non-Apple manufactured) keyboard that does contain both Backspace and Delete keys, and unfortunately we currently don't have that information (i.e. what physical keyboard you have plugged in).
