### ISSUE TITLE
Status bar can overflow when tabbing through entries

### ISSUE THREAD

**Issue by donald-ning** [microsoft/vscode#154708]
Does this issue occur when all extensions are disabled?: No

- VS Code Version:1.69.0
- OS Version:MacOS M1

Steps to Reproduce:

1. I found that in vscode's navigation bar, if the content is outside the scope of the presentation and arrow keys are used, the following image appears.
2. ![bug](https://user-images.githubusercontent.com/54016368/178153228-e6377334-549b-4b04-9d54-2c9071b8bd87.jpg)

**Comment by dbaeumer** [comment]
@donald-ning can you please describe what you would expect to see.

**Comment by donald-ning** [comment]
I think the navigation at the bottom is out of place, isn't that a bad design? I want to be able to scroll, not clutter

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by donald-ning** [comment]
For the preview version, I use the same method and it will still look like this.
![Snipaste_2022-07-15_15-10-11](https://user-images.githubusercontent.com/54016368/179171131-c794fc40-d1d5-4eaf-8db7-bd26a21ff0f4.jpg)

**Comment by bpasero** [comment]
I am curious what contents are there for you in the status bar, because I will probably have a hard time to reproduce. Can you follow these steps in the video and paste the contents here?
![Recording 2022-07-15 at 11 06 12](https://user-images.githubusercontent.com/900690/179192044-77c16c00-0285-4ff6-8a31-518f07be057b.gif)

**Comment by donald-ning** [comment]
I'm sorry, I'm just a beginner, I don't know the specific code content. I can only give you my specific operation in this case.

https://user-images.githubusercontent.com/54016368/179222858-b9cddbe5-bb67-4fba-8967-4de2e62f93e4.mov

**Comment by bpasero** [comment]
Yeah I can reproduce but I do not have a good idea how to solve this. https://github.com/microsoft/vscode/issues/84258 is related to use a different strategy and clip the entry instead of hiding it.

In general we miss a good overflow strategy for the status bar (related https://github.com/Microsoft/vscode/issues/6651). 

Is there someone with energy to investigate a solution? Maybe in CSS?

**Comment by nirabhromakhal** [comment]
Hi, what if the status bar becomes scrollable when it overflows, but no scrollbar is displayed? We can then scroll horizontally using the mouse wheel or using the left/right arrow keys.

Will this be a good enough solution? I can try to implement this with minimal changes.


https://user-images.githubusercontent.com/17908447/179563348-0d315dee-59d0-45cc-bce2-7d2ae252091a.mp4

**Comment by bpasero** [comment]
Yeah if we can somehow do this only when keyboard focus is in I am willing to take any solution that does not result in the multi line layout shift 👍 

Thanks!
