### ISSUE TITLE
support intellisense for `runTask` command

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#155087]
deferring from https://github.com/microsoft/vscode/pull/154854 as I spent more than an hour on it

**Comment by Tyriar** [comment]
This is a little different to how we do it in the terminal because the command palette entry:

https://github.com/microsoft/vscode/blob/665487a3c522ed333fdc6e0174fc6fd7d8e91861/src/vs/workbench/contrib/tasks/browser/task.contribution.ts#L269-L275

is registered separately to the command:

https://github.com/microsoft/vscode/blob/665487a3c522ed333fdc6e0174fc6fd7d8e91861/src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts#L374-L380

`runTask` also doesn't show up at all as a command anymore:

Insiders:

![image](https://user-images.githubusercontent.com/2193314/179605473-4ef01fb8-108e-4515-9b84-5f35ace05c9f.png)

Stable:

![image](https://user-images.githubusercontent.com/2193314/179605522-3d430e8c-b6a9-425a-a398-c35c14fd3dca.png)

**Comment by Tyriar** [comment]
Commenting out the schema fixes the problem for runTask and the commands below.

**Comment by meganrogge** [comment]
removed `bug` because the change was reverted so it doesn't work
