### ISSUE TITLE
Compact value is cut off

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#155142]
See `target`:

![image](https://user-images.githubusercontent.com/900690/178921843-8cf2bb12-8f94-4b6b-93b9-15ba1033a456.png)

**Comment by roblourens** [comment]
Where do you get a URI that shows that preview? Mine only show the object properties 

<img width="606" alt="image" src="https://user-images.githubusercontent.com/323878/214976025-c2fa0900-5832-4270-8df0-fa839f119bcf.png">

**Comment by connor4312** [comment]
Any object with a _pure_ custom `toString()` representation should do it. We evaluate custom object `toString()`'s, but tell V8 to throw if it would cause a side effect. It happens that the `.toString()` on VS Code extension host URI's caches the formatted representation on the object, so it is not pure.

You can test this with any custom object that has a toString() method. Or just call `uri.toString()` in the REPL, which will then refresh the variables view and display (without side effects) the cached value.

**Comment by roblourens** [comment]
I see it now but is there a difference between the EH and node debuggers?

Node ✅ 
<img width="181" alt="image" src="https://user-images.githubusercontent.com/323878/214979272-5bcc8096-fdab-411a-8f1d-6d379e2cf064.png">


EH 

<img width="190" alt="image" src="https://user-images.githubusercontent.com/323878/214979309-638dd357-efd1-4aa5-a28c-63ba5998e44b.png">
<img width="367" alt="image" src="https://user-images.githubusercontent.com/323878/214979325-c51d9526-c893-4f80-abd4-0634d14b72dc.png">

**Comment by connor4312** [comment]
I didn't really realize it before, but the presence of side-effect inducing toString() calls in the scope will prevent all toString() representations from working, since we evaluate them all in one go...

This is kind of unfortunate. V8 says they "throwOnSideEffects" but the "throw" is not catchable within the function doing the evaluation. What we could do is some kind of binary search on properties to try to evaluate ones with no side effects. I actually moved from doing individual calls on each property since that caused performance issues, but the binary search approach should mean that we're in `log N` for a single impure call, though a worst case of `N log N` if every call has side effects.
