### ISSUE TITLE
Default build task gets wrongly launched again, after reconnecting

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#155163]
1. Hit `Ctrl Shift B` to start the default build

🐛

![image](https://user-images.githubusercontent.com/22350/178948556-9df100b1-df63-444d-afbc-ae342094df79.png)

---

This happened right after something strange, which might be the underlying cause. I had the build running already, the one with two terminals open. But I still pressed `Ctrl Shift B` and noticed another two terminals showed up with the same build tasks! I closed them all. Then I pressed `Ctrl Shift B` and ended up where the screenshot above shows.

cc @alexr00 @Tyriar

**Comment by joaomoreno** [comment]
I reloaded, then pressed `Ctrl Shift B` before the workbench was done loading and got this:

![image](https://user-images.githubusercontent.com/22350/178949072-9fed3fe3-5786-4878-b4fa-62739ae0cd50.png)

I waited a bit more, pressed it again and it worked. This is very likely a separate issue, so feel free to treat it as such.

**Comment by Tyriar** [comment]
@meganrogge might be a bug with the new reconnect?

**Comment by meganrogge** [comment]
Yeah I think I saw this once

**Comment by joaomoreno** [comment]
@Tyriar That's exactly right. Steps:

1. Open selfhost setup
2. Ctrl Shift B, you now have 2 build commands running
3. Quit VS Code
4. Open VS Code, you still have 2 build commands running
5. Ctrl Shift B, 🐛 You now have 4 build commands running.

**Comment by meganrogge** [comment]
@joaomoreno it's not a new bug that you can launch tasks that are already running

**Comment by joaomoreno** [comment]
@meganrogge: If you press `Ctrl Shift B` you should get the default build tasks, which are long running. If you press it again, they shouldn't be launched again and they aren't. The bug is: restart Code (tasks now get restored) press `Ctrl Shift B` and you'll get the same build tasks running again. This shouldn't happen.

**Comment by meganrogge** [comment]
same root cause as #141774, which is not new

**Comment by joaomoreno** [comment]
@meganrogge This is my selfhost setup. I am 100% sure this is new.

**Comment by meganrogge** [comment]
the two bugs that you've identified here though are:
- the error about a terminal group
- command not found

**Comment by meganrogge** [comment]
in your old setup, run ctrl shift b, ctrl shift b again. you'll get 4

**Comment by meganrogge** [comment]
in stable
![Screen Shot 2022-07-14 at 1 41 53 PM](https://user-images.githubusercontent.com/29464607/179079527-b8d22e45-3c0a-4906-85f8-3d18275392a1.png)

**Comment by meganrogge** [comment]
I think you are correct @joaomoreno it's a different issue. I see what's going on now.

**Comment by meganrogge** [comment]
might still be the same root cause, but i'll try to investigate for a bit

**Comment by joaomoreno** [comment]
Thanks @meganrogge! 🥳

**Comment by joaomoreno** [comment]
Sorry for reopening @meganrogge, but I could still repro in today's build (1ccfe2bbe804a20a7c657ca42368987fd1adac58) very likely due to the [revert](https://github.com/microsoft/vscode/pull/155348#issuecomment-1186884528). 😞 

![image](https://user-images.githubusercontent.com/22350/179506737-3900bf08-761b-4fb6-b8ad-04364008bc74.png)

**Comment by Tyriar** [comment]
This is happening because this conditional is entered on ctrl+shift+b after reload:

https://github.com/microsoft/vscode/blob/9ba5ee22fa8c853841da5a91927b5a4c6e934fd1/src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts#L549-L554

Looks like `this._activeTasks` isn't restored on reconnect:

![image](https://user-images.githubusercontent.com/2193314/180500984-218fb66b-fc42-41a4-9832-d6bef961873d.png)

**Comment by Tyriar** [comment]
The `reconnect` task has the wrong id?

![image](https://user-images.githubusercontent.com/2193314/180501700-e7461de7-ee0b-4ea9-9557-5cd729e02ab4.png)

**Comment by Tyriar** [comment]
`task._id` is persisted as a guid, not the expected string?

![image](https://user-images.githubusercontent.com/2193314/180502679-13ae035a-dd22-4671-ac62-ee27ac68d8e6.png)

**Comment by Tyriar** [comment]
It's the custom task with the same label that gets the uuid:

https://github.com/microsoft/vscode/blob/9ba5ee22fa8c853841da5a91927b5a4c6e934fd1/src/vs/workbench/contrib/tasks/common/taskConfiguration.ts#L1560

**Comment by Tyriar** [comment]
`isCustomTask` ends up returning true, that's why _id ends up as a uuid:

https://github.com/microsoft/vscode/blob/9ba5ee22fa8c853841da5a91927b5a4c6e934fd1/src/vs/workbench/contrib/tasks/common/taskConfiguration.ts#L1733

https://github.com/microsoft/vscode/blob/9ba5ee22fa8c853841da5a91927b5a4c6e934fd1/src/vs/workbench/contrib/tasks/common/taskConfiguration.ts#L1690-L1694

The task's type is undefined after reconnection. It's mean to be `"npm"`, this is what it's meant to be:

![image](https://user-images.githubusercontent.com/2193314/180506641-28777160-155c-4f84-b654-08f39fa87853.png)

**Comment by Tyriar** [comment]
Note that this only reproduce for compound tasks.

**Comment by Tyriar** [comment]
That was a journey and I'm ready to throw in the towel for now. I believe the issue is either compound task state is not restored properly after reconnect here:

https://github.com/microsoft/vscode/blob/9ba5ee22fa8c853841da5a91927b5a4c6e934fd1/src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts#L285-L298

```ts
		if (this._tasksToReconnect.includes(task._id)) {
			// Handle regular tasks
			this._terminalForTask = terminals.find(t => t.shellLaunchConfig.attachPersistentProcess?.task?.id === task._id);
			if (this._terminalForTask) {
				// Need to restore active tasks
				this._activeTasks[task.getMapKey()] = {
					task,
					terminal: this._terminalForTask,
					promise: this.run(task, resolver, trigger).promise
				};
			} else {
				this.run(task, resolver, trigger);
			}
		} else {
			// Handle compound tasks?
		}
```

And/or the recently used tasks cached value does not contain all recently used tasks as I only see the compound and Core - Build, no Ext - Build.

**Comment by meganrogge** [comment]
@alexr00 any thoughts would be appreciated. I spent ~ 3 hours on this and Daniel did as well.

**Comment by alexr00** [comment]
👍I will take some time tomorrow to dig into it.

**Comment by alexr00** [comment]
Some notes from debugging:
- When comparing tasks that come out of the recently used task list, they must be compared by their recently used key as this is the only stable id value (map key and task id can change).
- Instead of having a separate code path for reconnect, which is what is causing some state to be lost (like the `_activeTasks`), if possible, it would be better to try the reconnect in the same place that we currently create a terminal. This would hook up all the needed state again and re-attach problem matchers. 

I've made an example PR here that starts to address the above points. Note that this is relatively untested, I just checked whether it fixes the problem described in this issue. https://github.com/microsoft/vscode/pull/156283

Other notes:
- Using the recent tasks from the task service for re-connecting is problematic since users can use `task.quickOpen.history` to entirely disable recent tasks. Instead, you will probably need a separate LRU that functions exactly like `_recentlyUsedTasks` but is only used for reconnection.
- Tangentially related: you also need to nudge/rerun problem matchers on terminal lines that have already been written so that they can find their start pattern and the task doesn't have a spinner forever.
