### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by Lucas56o** [microsoft/vscode#155199]
quando eu vou abrir no google chrome o meu arquivo css ou html não mostra a tela de fundo e nem as outras editações no css, mostra só o texto sem edição e acontece frequentemente. outro problema é a linguagem, está em portugês mas quando eu inicio o editor está em inglês mesmo com a extensão ''Portuguese (Brazil) Language Pack for Visual Studio Code''  ativada

**Comment by fgclue** [comment]
Uhh.... How do we replicate this bug?

**Comment by fgclue** [comment]
**_(Portuguese (Brazil))_**
Eu acho que a razão que o seu arquivo de CSS e HTML não autoliza automaticamente e provavelmente porque chrome (e qualquer outro navegador), não auto recarrega quando um arquivo e autolizado. Tente recarregando a pagina que o arquivo HTML esta aberto. Se você nao quer fazer isso, tente usando a extensão "Live Server".

**_(English)_**
I think that the reason that your CSS and HTML file doesn't update automatically is probally because chrome (and basically any other browser), doesn't auto-reload when a file is updated. Try reloading the page that the HTML file is open. If you don't wanna do this, try using the extension "Live Server".
