### ISSUE TITLE
Can't open code workspace file while in folder (Github Codespaces)

### ISSUE THREAD

**Issue by jonathanyeung** [microsoft/vscode#155258]
I can't seem to launch into a workspace while I have the *.code-workspace file in my currently opened folder.

## Repro Steps:

1. As an example, launch https://github.dev/dendronhq/dendron-site
2. Navigate to the `dendron.code-workspace` file, the 'Open Workspace' button appears in the bottom corner. Click on it.
3. I see a message 'The browser interrupted the opening of a new tab or window. Press 'Open' to open it anyway.'
4. When I click Open, nothing happens. 

I've also tried allowing popups for github.dev in edge settings, but it doesn't seem to help.

Version: 1.69.1
Commit: b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.114 Safari/537.36 Edg/103.0.1264.51
Embedder: github.dev

**Comment by jonathanyeung** [comment]
Screenshot:

<img width="811" alt="image" src="https://user-images.githubusercontent.com/3203268/179133360-8c2d0ea3-402e-408c-a569-6b7419b85fe1.png">

**Comment by bpasero** [comment]
@jkeech this is an issue with the workspace provider on GitHub, I can see an early "return false" here:

![image](https://user-images.githubusercontent.com/900690/179156539-0b5a8edb-b322-4de8-92ee-49f73d70a8f2.png)

How can I transfer this issue to you in a public repo?

**Comment by jonathanyeung** [comment]
Thanks @bpasero for the quick triage. 

A tangential follow up question - is it possible with Github Codespaces to launch directly into a workspace? 

With the `code` cli, I can type something like `$ code my-project.code-workspace` and it'll launch vscode with my workspace already opened.  It'd be nice if it were possible to do something similar within Github - for example if I use the `.` period shortcut while I'm browsing the `my-project.code-workspace` file, then it'll open Github Codespaces with my workspace already opened.  That way, I can share a URL to a colleague and with one-click, their environment is already setup.

**Comment by bpasero** [comment]
We are not providing support for Codespaces here, you should ask in https://github.com/github-community/community/discussions

**Comment by bpasero** [comment]
I think Codespaces has no public issue tracker other than https://github.com/github-community/community/discussions so please open it there.

**Comment by jkeech** [comment]
Hi from the GitHub Codespaces team! 👋

https://github.com/github-community/community/discussions is the best place to ask Codespaces or github.dev-related questions. It looks like this question is about `github.dev` which is not quite the same as GitHub Codespaces. github.dev does not currently support opening VS Code workspace (`.code-workspace`) files, but it's a good feature request. I'll add it to our backlog.

**Comment by jkeech** [comment]
Following up, we've deployed a change for `github.dev` to enable opening VS Code workspaces. The `Open Workspace` button when viewing a workspace file should now work. The default when using the `.` shortcut to switch from `github.com` to `github.dev` does not open the file in workspace mode, since we want to mirror the code browsing/editing experience on `github.com`.

Here's an example using the `dendron-site` repo:

* `https://github.com/dendronhq/dendron-site/blob/master/dendron.code-workspace` is the file viewer for the file on github.com
* `https://github.dev/dendronhq/dendron-site/blob/master/dendron.code-workspace` is the file viewer for the file on github.dev
* `https://github.dev/dendronhq/dendron-site/blob/master/dendron.code-workspace?workspace=true` will open that file as a VS Code workspace in `github.dev`. Clicking `Open Workspace` when viewing a `.code-workspace` file in `github.dev` will open a new tab on that file with the `?workspace=true` query parameter to open the file as a VS Code workspace instead of in a text editor.
