### ISSUE TITLE
Integrated terminal still leaks GPU memory

### ISSUE THREAD

**Issue by SvanT** [microsoft/vscode#155232]
Follow up on [#152300](https://github.com/microsoft/vscode/issues/152300)

Thanks for the fix, but I can still reproduce the issue in the insiders build I just downloaded:
![image](https://user-images.githubusercontent.com/3172483/179068005-a3d26896-247b-4574-8399-eef6265a374a.png)

I've opened lots of terminals which I have now closed again (only welcome screen opened now).

If vscode is visible in the background:
![image](https://user-images.githubusercontent.com/3172483/179068111-9a55ba6a-3534-49d9-832a-8bc6a2c6c044.png)

If vscode is either minimized or completely behind other windows:
![image](https://user-images.githubusercontent.com/3172483/179068273-d01ac6c2-5443-4c34-8428-81675fa54e14.png)

**Comment by Tyriar** [comment]
I feel like this is just Chromium perhaps batching the webgl calls or something, the GPU memory according to devtools jumps around a bit but always ends around the same value even after creating many terminals:

![Recording 2022-07-18 at 11 09 05](https://user-images.githubusercontent.com/2193314/179575239-d2a05cd5-2302-4376-a56d-b42e7c9dfa5a.gif)

The terminal is unique in VS Code wrt GPU as it's currently the only part that uses webgl, so that explains why GPU memory is affected primarily by the terminal and no other component. I'm not sure there is anything we can do here since we are now disposing of all the webgl objects that need to be manually freed in https://github.com/xtermjs/xterm.js/pull/3890

**Comment by SvanT** [comment]
This is very interesting, I get the same results as you with the frame rate performance overlay, one more clue I found but I guess that doesn't help too much is that this also is reflected in the gpu process memory usage. This is when many terminals has been opened and closed again:
![image](https://user-images.githubusercontent.com/3172483/179927718-35d603b9-6b76-4c40-a45b-3e8e7904b6b0.png)

Same instance minimized:
![image](https://user-images.githubusercontent.com/3172483/179927781-ed74d882-b194-41ae-b6c2-cd23878d7174.png)

I can make GPU process usage go beyond 4GB without any sign of stopping by just opening ~10 tabs, closing them again and doing it over again many times, so I guess it's something more than just Chrome doing batching or keeping memory for performance reasons etc.
