### ISSUE TITLE
New breakpoints are mapped to incorrect lines / sourcemap after webpack HMR in existing attached debugger.

### ISSUE THREAD

**Issue by shahmirn** [microsoft/vscode#155331]
I have an express server written in Typescript, using Webpack with hot module replacement, and sourcemaps in order to debug.

When I first attach the debugger to the running server, the breakpoints are mapped to the correct lines. However, after a few changes and HMR updating the files, any new breakpoints are mapped to the wrong line, until I disconnect the debugger, and then re-attach it to the process, at which point, new breakpoints are mapped to the correct line again.

https://user-images.githubusercontent.com/3029066/179275872-933349bc-2ad6-4011-87e1-bda3534b6392.mp4

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.69.1
- OS Version: OSX 12 and 13

Steps to Reproduce:

See video above, which shows the issue

**Comment by connor4312** [comment]
Failing that, this can most easily be tested by using `create-react-app`, adding some extra logic to the root component, and verifying that you can still set breakpoints at sensible places after repeatedly modifying and moving things around in the file.

**Comment by rzhao271** [comment]
I moved the logs around and saved the file, but I was unable to add a breakpoint to line 8 because it is where the end of a for loop (`}`) used to be.

![The breakpoint on line 8 cannot be active even though it is a console log call](https://user-images.githubusercontent.com/7199958/187953181-00f4c39b-9d2f-4322-b4e3-f170713b0274.png)

**Comment by JamesEarle** [comment]
I am having a similar or the same issue but not with react. I'm running a CLI command inside the `JavaScript Debug Terminal` and the breakpoints are not mapping to the line they indicate visually. Below you can see what's happening because even though we're breaking on the "correct" line, we haven't actually executed the previous line yet and `test` is still undefined.

![image](https://user-images.githubusercontent.com/5976499/200477822-c77bce66-15a7-46b9-bb63-11d15dda5794.png)

I'm running the latest build and there are no updates available.

Version: 1.73.0 (user setup)
Commit: 8fa188b2b301d36553cbc9ce1b0a146ccb93351f
Date: 2022-11-01T15:34:06.111Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No

I'm trying to run `yarn hardhat run file.ts` but I have seen this issue with other, unrelated code that makes me point to VS code directly.

**Comment by connor4312** [comment]
I'm not able to repro this issue, seems thing to work quite well from a UX and code perspective.

Note that you need to save the files for HMR to kick in, and there might be a slight delay before it does. If any issues are encountered, please add `trace: true` to the launch.json and share the log. Closing for re-verification.

**Comment by rzhao271** [comment]
Didn't get to it. Might try again later
