### ISSUE TITLE
Feature request - Keyboard binding for run tasks popup menu

### ISSUE THREAD

**Issue by meshula** [Microsoft/vscode#15549]
I have made a bunch of tasks in my tasks.json file.

Current behavior-
cmd-shift-p find Run Tasks, click, click my task

Desired behavior -
I would like to replace the cmd-shift-b key-binding (or any key-binding of course) with jumping directly to the tasks pop up menu so I can pick one of many tasks.

**Comment by ramya-rao-a** [comment]
You can add your own key-binding to the "Run Tasks" command so that the tasks pop up menu shows up.
The command for "Run Tasks" is "workbench.action.tasks.runTask".
For example, you can add the below in your key bindings json file

![image](https://cloud.githubusercontent.com/assets/16890566/20359346/4998a71c-abe4-11e6-905b-8e4bc7afcbde.png)

**Comment by meshula** [comment]
Perfect, thanks! I hadn't been able to find the runTask command. Is there a documentation page, or other way to discover command names?

**Comment by ramya-rao-a** [comment]
I usually search in the Default Keyboard Shortcuts files. If you scroll down, you will find the whole list.

![image](https://cloud.githubusercontent.com/assets/16890566/20402144/685cdc96-acb0-11e6-9e86-ca173d3abae8.png)

I have logged https://github.com/Microsoft/vscode-docs/issues/683 to see if we can get these in our docs

**Comment by meshula** [comment]
Thanks! TBH I didn't think to go to the bottom of the file.

**Comment by ramya-rao-a** [comment]
Don't worry, I found it by accident actually. One day I was wondering, "woah, this is a big file, do we really have these many keybindings??" and then I scrolled :)
