### ISSUE TITLE
Improve Typography of Markdown Preview

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#15545]
- VSCode Version: 1.7.1
- OS Version: macOS 10.11.6

Currently the text looks really cramped together and too light.

![image](https://cloud.githubusercontent.com/assets/4033249/20328749/46f0d50c-ab49-11e6-8658-d9cf57a3ef75.png)

Made a change to use `-apple-system` at 16px.

- Left: `-apple-system`, which is San Francisco. 16px.
- Right: `HelveticaNeue-Light`. What we are using. 14px.

![image](https://cloud.githubusercontent.com/assets/4033249/20328550/38251458-ab48-11e6-9329-150c15c0fbaa.png)

Maybe we should also add some `letter-spacing`.
.2px `letter-spacing`:

![image](https://cloud.githubusercontent.com/assets/4033249/20328885/04ebed6c-ab4a-11e6-9c14-fcefa4b559d9.png)

@bgashler1 Looking for some input.

**Comment by octref** [comment]
Think we should use extension browser's Markdown rule.

Left: Extension Browser
Right: Preview

![image](https://cloud.githubusercontent.com/assets/4033249/20400010/ec0525b6-aca7-11e6-88ce-75d333791e65.png)

**Comment by bgashler1** [comment]
Darn, I just wrote a long reply with lots of info on what we should do, then my computer crashed :(

In summary, yes, you're right that this typography inconsistency is a problem and we can certainly improve the legibility.

Extension view uses inherited styles from the shell and monaco-editor parts.  Thus, it uses the system font (vs. blindly using Segoe UI or Helvetica Neue) and the default shell font size of 13px that is used consistently throughout the UI.  In contrast, markdown.css is using its own font-family list, instead of inheriting from the shell; it does not use the improvements we made in the shell styles to use the native system font, and it also has a hard-coded font size of 14px.

We should make the markdown and extension view (i.e. webview) consistent.  They should inherit the common-sense typography changes we made to the shell, so we can keep the stylesheets DRY.  I'm also fine increasing it's font-size to 14px (which is a good minimum font-size for website accessibility).  I tried 16px, but it looked bad, in my opinion.

Lastly, as far as letter-spacing, let's hold on that.  I hesitate modifying default font-spacing globally.  I'd rather let the font choose and only override on a case-by-case basis for things that need it (like keybindings in Lucida Grande font that need breathing room).  We can revisit that later if these initial steps don't help.
