### ISSUE TITLE
api-command: vscode.open failing

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#155519]
```
  1 failing
  1) vscode API - commands
       api-command: vscode.open:

      AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: Expected values to be strictly equal:

2 !== 1

      + expected - actual

      -2
      +1
      
      at Context.<anonymous> (/Users/runner/work/1/s/extensions/vscode-api-tests/src/singlefolder-tests/commands.test.ts:122:10)

```

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=178446&view=logs&j=9833cdaa-2e92-5f8d-56a8-239fd18fd628&t=9fd0bccc-90ad-5118-165a-bb6fa0e94027&s=a56e7651-4213-56af-9488-c25fe636c10c

**Comment by lramos15** [comment]
<img width="1070" alt="image" src="https://user-images.githubusercontent.com/4544166/182211904-ae6e5683-d12f-4b5c-a148-1f116a470936.png">

Appears to just have been a fluke. Did investigate but couldn't see anything that stood out. Have been tracking the issue for two weeks and there has not been another failure. Feel free to reopen if the issue is seen again

**Comment by bpasero** [comment]
Came back just now as https://github.com/microsoft/vscode/issues/157824, and I had initially thought it could have been related to my changes in https://github.com/microsoft/vscode/commit/dced70bbf36d3c53c08e791da1791ac7fc42519b, but those changes came after this report, so then maybe this is something else.

I have https://github.com/microsoft/vscode/pull/157885 up because I noticed that we do not close all editors in the `teardown`. I also moved the tabs assertion up to see if this is maybe an issue only for the text documents that I think resolve a bit more async compared to the sync tabs model.

**Comment by lramos15** [comment]
> I have #157885 up because I noticed that we do not close all editors in the `teardown`. I also moved the tabs assertion up to see if this is maybe an issue only for the text documents that I think resolve a bit more async compared to the sync tabs model.

Thanks for the investigation. I will keep tracking if we see this failure more often. I cannot recall any changes (besides your recent one) which we have made in this area which might cause this test to be flaky.

**Comment by bpasero** [comment]
Again today:

**Comment by bpasero** [comment]
Not a failure in 10 days, lets close for now until we hit this again.
