### ISSUE TITLE
Editor hovers flicker/re-render when trying to click into them

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#155665]
I believe this is relatively new (since its not uncommon for me to copy text out of the hovers) -- but when trying to click into a hover to select text is often flickers/re-renders losing the selection and sometimes just disappears. FYI, it seems like it disappears more often if your mouse end up outside the editor area.

![hover-flicker](https://user-images.githubusercontent.com/641685/179862816-3c071b77-4ece-4c09-9314-6b21d0a2f01c.gif)

/cc @alexdima

**Comment by alexdima** [comment]
@eamodio You might have been running into https://github.com/microsoft/vscode/issues/154577 . That one was caused by a change in the markdown renderer which would emit an event 50ms too late, which would cause the hover to be layouted later by 2-3 frames (i.e. flicker). We pushed a fix for that yesterday via https://github.com/microsoft/vscode/pull/155629, so today's build (expected in ~1hr) would contain the fix. Could you please try out the fix?

**Comment by eamodio** [comment]
Will check it out and report back -- thanks!

**Comment by eamodio** [comment]
Looks like its fixed now, so will close this out. Thanks!
