### ISSUE TITLE
Commit split button looks odd on my theme

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#155684]
You can see in the image that the split part doesn't look right.

FYI my theme is [Amethyst Dark](https://marketplace.visualstudio.com/items?itemName=amodio.amethyst-theme)

![image](https://user-images.githubusercontent.com/641685/179894824-15423e82-7fad-47b8-92c0-ccf1e205d002.png)

/cc @lszomoru

**Comment by lszomoru** [comment]
//cc @misolori

**Comment by misolori** [comment]
I think this might be another style issue with the button border since the separator container use the full height:

<img width="430" alt="CleanShot 2022-07-20 at 10 56 10@2x" src="https://user-images.githubusercontent.com/35271042/180050211-8e107546-8728-4445-a921-51eeca7fe2f2.png">

If you don't set a border it looks normal:

<img width="237" alt="CleanShot 2022-07-20 at 10 54 13@2x" src="https://user-images.githubusercontent.com/35271042/180049896-e55dcd9c-e2b9-4f5f-b797-3d45a64de229.png">

**Comment by lszomoru** [comment]
@misolori, thanks for tracking this down. I will try to squeeze a fix in this week.
