### ISSUE TITLE
Test improved `New File...` experience

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#155731]
Refs #153860

- [x] macOS @lszomoru
- [x] linux @sadasant
- [x] windows @DonJayamanne, @rzhao271, @Yoyokrazy 
- [x] web @kieferrm

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23155731%0A%0A&assignees=lramos15)

---
In an effort to help users who get stuck creating a file via `File > New File...` and to enrich the file creation experience the input box now allows for creating files on disk by typing a file name.

Please test the following workflows via `File > New File...` or clicking `New File...` on the walkthrough.
1. Typing a file name and creating a file
2. Typing an invalid file name
3. Overwriting an existing file. Please ensure you are prompted before the overwrite happens!

General UX feedback is also always appreciated :)

**Comment by sadasant** [comment]
Here's creating a new file on linux:

https://user-images.githubusercontent.com/417016/181046701-0244bceb-b494-4dbf-a246-c30694b9f930.mov

Here's overwriting that file:

https://user-images.githubusercontent.com/417016/181046848-d5af440b-f71f-4913-9bae-0a58acd70b74.mov

Feedback appreciated! Is there anything else I should specifically try?

**Comment by lramos15** [comment]
Thanks @sadasant no need to make videos (although they are nice). Just testing the steps above and then filing any bugs / things you wouldn't expect while testing is more than enough. Thanks!

**Comment by rzhao271** [comment]
I like it 🎉

**Comment by Yoyokrazy** [comment]
Testing on windows, the behavior when typing an invalid file name wasn't necessarily wrong, but felt odd. I attempted to name my file ```lkdfjhg`~\|.txt``` just to force in some definitely invalid characters, and the OS prompted me to save the file as `|.txt` in a file explorer window (followed by an invalid character error if I try to save).

However, trying ```??*<>+#.txt``` gave me an OS file prompt with the same characters followed by an error upon clicking save saying it was invalid.

Not sure what the expected behavior should be here, but a message saying something along the lines of `This filename contains invalid characters` might be helpful for the user in the case that they use something they shouldn't. Maybe a prompt before the workflow takes the user into the OS file prompt?
