### ISSUE TITLE
Environment variables set on the Unix side of WSL not being exposed within the extension host

### ISSUE THREAD

**Issue by brettcannon** [microsoft/vscode#155980]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.70.0-insider
- OS Version: Windows 10.0.22000

Steps to Reproduce:

1. Launch VS Code from WSL with a set environment variable; `ENV_IS_SET=1 code`
2. Load the Developer Tools to inspect `process.env`
3. Notice the Unix environment variable isn't picked up

I'm assuming this is a WSL limitation, but I wanted to double-check.

**Comment by aeschli** [comment]
The environment variable is set in the Linux process, but dev tools are inspecting the renderer which runs in a Windows process.
But when running in the integrated terminal in the Remote Window, or when running extension in the extension host, you will see that the variable is applied there.
So that's as designed.

What problem do you want to solve? 
In a remote setup all tools/tasks/extensions run on the remote side, with the renderer only doing the 'rendering' ;-)

Closing the issue, but happy to continue the discussion.

**Comment by brettcannon** [comment]
As long as the extension host sees the expected environment variables that's all I care about (Kai wasn't sure if environment variables made it to the extensions and I was using the Developer Tools as a quick check to see if he was correct or not).

**Comment by aeschli** [comment]
Yes, that's a feature we added.
