### ISSUE TITLE
Deemphasize non-conflicting changes

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#155942]
> The biggest issue that I have is highlighting already merged code. Even if it was resolved automatically and didn’t require any actions from me, the merge editor will show these lines with highlight background and pre-checked checkboxes.
>
> I don’t need this highlighting and will not uncheck it. For example, in incoming changes, a file has a new import at the top. It has no conflict with my current changes, and git managed to resolve it automatically.
>
> ![](https://miro.medium.com/max/1225/1*zI2_litmglAAoOwPxVhtJA.png)
>
> In the old way, VS Code didn’t show at all what git resolved automatically. And Web Storm even doesn’t highlight manually fixed conflicts.

(from https://javascript.plainenglish.io/finally-released-3-column-merge-editor-in-vs-code-8490ef694b3a)

**Comment by bpasero** [comment]
Yeah similar concern, when I resolved a merge conflict today I was somewhat confused to see checkboxes for a merge conflict that was auto merged where both sides did the same edit.

**Comment by hediet** [comment]
> see checkboxes for a merge conflict that was auto merged where both sides did the same edit.

Technically, this might be a conflict though: Do you want to include both insertions or only a single one? Also, this is a separate issue.

**Comment by bpasero** [comment]
In this case both insertions where identical on the same line so I would not expect to pick either side or even being asked to pick one.

**Comment by hediet** [comment]
@bpasero See #155964 and #155965 for this.

**Comment by Golosay** [comment]
> > see checkboxes for a merge conflict that was auto merged where both sides did the same edit.
> 
> Technically, this might be a conflict though: Do you want to include both insertions or only a single one? Also, this is a separate issue.

There are no issues with checkboxes, and they can still exist even after resolving the conflict. But the color highlighting looks like it requires your attention. It would be clearer to see the result without highlighting)

**Comment by plwalsh** [comment]
It would also be nice if the "Go to next/prev conflict" arrows skipped all the non-conflicting changes. I just had a file where I couldn't even find where the conflicts were, neither via arrow buttons nor manually scrolling, and had to revert back to the old inline conflict editor view. There were just way too many boxes and lines and highlights all over the place. The old inline view was crystal clear.

**Comment by hediet** [comment]
@plwalsh This is implemented in the release that got out yesterday!

**Comment by plwalsh** [comment]
@hediet Ohh that's great -- thanks for letting me know!

**Comment by Golosay** [comment]
Thanks a lot!

**Comment by samuelShp97** [comment]
> It would also be nice if the "Go to next/prev conflict" arrows skipped all the non-conflicting changes. I just had a file where I couldn't even find where the conflicts were, neither via arrow buttons nor manually scrolling, and had to revert back to the old inline conflict editor view. There were just way too many boxes and lines and highlights all over the place, only worsened by the reduced editor real estate. The old single-editor inline view was crystal clear.

hi @plwalsh may i know how did you revert back to the old inline conflict editor view? i find this new 3-column merge editor very troublesome and confusing to use.

**Comment by zfrench** [comment]
> > It would also be nice if the "Go to next/prev conflict" arrows skipped all the non-conflicting changes. I just had a file where I couldn't even find where the conflicts were, neither via arrow buttons nor manually scrolling, and had to revert back to the old inline conflict editor view. There were just way too many boxes and lines and highlights all over the place, only worsened by the reduced editor real estate. The old single-editor inline view was crystal clear.
> 
> hi @plwalsh may i know how did you revert back to the old inline conflict editor view? i find this new 3-column merge editor very troublesome and confusing to use.

@samuelShp97 I was having the same issues as you. It was extremely difficult to work with after upgrading and kept running into issues with merges between multiple branches. It also was causing issues where the merge conflict became uneditable and for some items I could not select a left, right or both to retain. I included the instructions on how I reverted below.

To revert to the previous settings:
Go to Settings > Git: Merge Editor (Open the merge editor for files that are currently under conflict) > uncheck this checkbox.

**Comment by samuelShp97** [comment]
hi @zfrench thanks for you help! 
my gripe with the 3-column version is that all the auto-merged code blocks are highlighted as well, just like those with conflicts, causing me unable to differentiate which ones are to be resolved.
i find that the old version works perfectly fine :D

**Comment by hediet** [comment]
@zfrench @samuelShp97 It would be extremely helpful if you could share your merge editor state and what you find confusing, so we can look into this!
Our goal is to provide the best merge experience possible (and we clearly aren't there yet, but we need detailed feedback to improve).
Thanks!

**Comment by zfrench** [comment]
@hediet I added some additional details below for issues I have experienced with the current release related to the merge tool. Please let me know if you need any additional information or have more questions. I noticed these issues on the Windows version of the 1.70.0 release and do not know if these are present on mac.

1. The 3-way merge change between releases was kind of jarring and unexpected and believe others may be surprised by this feature as well. I am used to being able to do the line level changes which is my personal preference.  The 3-way merge tool takes up too much screen real estate to be helpful for the type of merges I was doing (multiple development teams in a repository). I prefer the single screen with line level conflicts especially on large files.
2. An XML file (not sure if this matters as I hadn't seen the issue presented with a different file type) was modified by two different teams where multiple tags had been added by different teams. In the 3-way merge view, the new fields were highlighted and blocked together which forces you to select a right, left or no checkboxes for the merge conflict. This is problematic as I need the ability to include individual lines vs a block of code. If there is need to include and/or exclude certain line level changes then this appeared to not be possible with version 1.70.0 unless I am missing how to do this. In the single merge screen, it has the options to use 'Accept Current Change', 'Accept Incoming Change', 'Accept Both Changes' and 'Compare Changes' options above the detected conflict.
3. The previous and next conflict buttons are no longer illuminated and would not move to the previous or next conflicts in the XML file when each button was clicked. I was forced to use the scroll bar to find the next conflict which did not work well on a large file. If I uncheck the 'Git:Merge Editor' checkbox, the previous and next buttons for the conflicts will work as expected but are not illuminated as seen in previous releases.
4. I like to compare the git blames if I need to review the changes between teams. I have a setting enabled that displays the line level blame (maybe Gitlens extension) that will show which use last modified a particular line on hover of the line. When I tried to hover over lines within the current or incoming panes the blame would not appear. The blame would only appear in the bottom level of the merged change which was not helpful because I want to see a blame before I actually decide what to do with a particular line.

**Comment by hediet** [comment]
Thanks a lot for your feedback @zfrench!

> I am used to being able to do the line level changes which is my personal preference

I understand this. We will investigate methods to offer both mechanisms.

> the new fields were highlighted and blocked together which forces you to select a right, left or no checkboxes for the merge conflict.

Can you share a screenshot if possible?

> The previous and next conflict buttons are no longer illuminated

If there are multiple conflicts in a file, these buttons should be active.

> If I uncheck the 'Git:Merge Editor' checkbox, the previous and next buttons for the conflicts will work as expected but are not illuminated as seen in previous releases.

Can you share a screenshot so I know exactly what you mean?

>  When I tried to hover over lines within the current or incoming panes the blame would not appear.

This should be a feature request for git lens, which provides these blames.

**Comment by zfrench** [comment]
@hediet I responded to your questions below and provided a couple of examples.

There are multiple conflicts in the file and the images no longer illuminate to indicate there are errors. Now that I think about it the Next and Previous conflict arrows may have never been highlighted and just disappear when all conflicts have been resolved. However, other icons are illuminated such as the 'changes' icons which are next and previous arrows in the screenshot.
![image](https://user-images.githubusercontent.com/4147537/183672476-33fc380d-bbff-4635-bfa5-a5a12d8bc60f.png)

The next set of images is displaying that there is not an in-line blame included on the 'Theirs' and 'Yours' panels but does exist in the 'Result' panel.

'Theirs' panel example
![image](https://user-images.githubusercontent.com/4147537/183673135-45dd4115-bc02-4389-a126-0a0dfca7c904.png)

'Result' panel example
![image](https://user-images.githubusercontent.com/4147537/183673286-ad1a5dd6-8d6b-42df-820b-b02d80b4d22f.png)

**Comment by plwalsh** [comment]
> 1. The 3-way merge change between releases was kind of jarring and unexpected and believe others may be surprised by this feature as well.

I definitely agree with this. New features that get enabled in vscode do tend to be quite jarring. And when they're still relatively new, they can often still be a bit buggy (to be expected, of course). But it's then difficult to know where to look for answers to questions like: Did I enable something by accident? Is this a new extension? Is this supposed to be like this? What is this view even called?

It might help if a little toast message popped up when it's the first time a user encounters a new feature. Something simple that says, "This is the new 'Merge Editor' view and it has been enabled by default in latest release. See the documentation [here] and report issues [here]."

**Comment by isidorn** [comment]
We have done some improvements in the 3-way merge editor that are already in VS Code insiders, and we are working on some improvements that will be in VS Code Insiders in the next couple of weeks.
Here's the full list https://github.com/microsoft/vscode/issues?q=is%3Aissue+label%3Amerge-editor+milestone%3A%22August+2022%22+

With this work I believe this issue has also been tackled and thus I will close this issue. So please tryout VS Code insiders, or if you only use stable give it another try in September when the experience will be much more polished. Thank you!
