### ISSUE TITLE
Provide `stdout` and `stderr` from utility process and adopt in extension host

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#155987]
* configure `"extensions.experimental.useUtilityProcess": true`
* run `Developer: Show Running Extensions”
* press the black circle icon in the editor title
* this should enable inspecting the extension host and start profiling
* this requires a restart because [this method](https://github.com/microsoft/vscode/blob/d7534854eb9290c19114d2f13c0950f42d61247b/src/vs/platform/extensions/electron-main/extensionHostStarter.ts#L371-L392) for UtilityProcess extension hosts is not working similarly to [this method](https://github.com/microsoft/vscode/blob/d7534854eb9290c19114d2f13c0950f42d61247b/src/vs/platform/extensions/electron-main/extensionHostStarter.ts#L239-L260) for regular nodejs extension host

**Comment by deepak1556** [comment]
Update:

I was able to confirm that `SIGUSR1` signal handlers are installed by Node.js inside the utility process via https://github.com/nodejs/node/blob/main/src/inspector_agent.cc#L92-L138 

Also, `process._debugProcess()` action is indeed invoked via https://github.com/microsoft/vscode/blob/main/src/vs/platform/extensions/electron-main/extensionHostStarter.ts#L371-L392, to confirm

* Make the following when running out of sources so that inspector does not get started on startup

```patch
diff --git a/src/vs/platform/environment/common/environmentService.ts b/src/vs/platform/environment/common/environmentService.ts
index d90cbc60fef..32ff30de6da 100644
--- a/src/vs/platform/environment/common/environmentService.ts
+++ b/src/vs/platform/environment/common/environmentService.ts
@@ -270,7 +270,7 @@ export function parsePtyHostPort(args: NativeParsedArgs, isBuild: boolean): IDeb
 
 function parseDebugParams(debugArg: string | undefined, debugBrkArg: string | undefined, defaultBuildPort: number, isBuild: boolean, debugId?: string, environmentString?: string): IExtensionHostDebugParams {
        const portStr = debugBrkArg || debugArg;
-       const port = Number(portStr) || (!isBuild ? defaultBuildPort : null);
+       const port = Number(portStr) || null;
        const brk = port ? Boolean(!!debugBrkArg) : false;
        let env: Record<string, string> | undefined;
        if (environmentString) {
```

* `.\scripts\code.sh`
* `Developer: Show running extensions` and click profile action
* Now see main process console output which will now print

```
Debugger listening on ws://127.0.0.1:61222/fa9f6ced-bf9b-49a1-ba32-30690c6ccbfc
For help, see: https://nodejs.org/en/docs/inspector
```

The problem is that we try to obtain the [inspector port](https://github.com/microsoft/vscode/blob/ef65ac1ba57f57f2a3961bfe94aa20481caca4c6/src/vs/workbench/services/extensions/electron-sandbox/localProcessExtensionHost.ts#L555) for the above action from the `stdout/stderr` of the extension host process in https://github.com/microsoft/vscode/blob/ef65ac1ba57f57f2a3961bfe94aa20481caca4c6/src/vs/workbench/services/extensions/electron-sandbox/localProcessExtensionHost.ts#L292-L295 

Since we current don't support stdout and stderr events for the utility process, we end up with empty inspector ports even though the inspector is started leading to failed profile action which ends up triggering the fallback. Maybe a temporary fix would be to read from the main process stdout. I will see if `UtilityProcess.stdout`, `UtilityProcess.stderr` can be implemented to make life easier.

**Comment by bpasero** [comment]
> I will see if UtilityProcess.stdout, UtilityProcess.stderr can be implemented to make life easier.

👍 . I had a brief look and it seems we listen to output and stderr not only for the purpose of obtaining the inspect port, but also to observe output and print it in general:

https://github.com/microsoft/vscode/blob/eebdf8174b087979ae6af103f6f2e2f6f9062056/src/vs/workbench/services/extensions/electron-sandbox/localProcessExtensionHost.ts#L271-L276

So I think we need this anyway, not just for debugging purposes. I wonder if this could also impact extension developers that want to log messages...
