### ISSUE TITLE
`Cmd+F` no longer goes to active editor

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#155924]
Rather now opens the find widget in the explorer. This is quite a shift and breaks muscle memory at least for me.

**Comment by joaomoreno** [comment]
Here's how you can disable <kbd>Ctrl F</kbd> in lists, defaulting to the previous behavior:

```
  {
    "key": "ctrl+f",
    "command": "-list.find",
    "when": "listFocus"
  }
```

**Comment by IllusionMH** [comment]
I am a bit surprised that this find widget doesn't open when I just start typing in list as is was with 
"filter on type" that was replaced by this find widget

**Comment by bpasero** [comment]
@IllusionMH I think the intent was to align with standard OS behaviour, you can still type to find (even more than one character) and it will highlight the matching entry, but for the more complex find widget, you need to explicitly bring it up.

**Comment by nikita-r** [comment]
@joaomoreno have you considered adopting a different shortcut that is commonly used for such feature e.g.`"key": "/"`?

The tricky thing about using "ctrl+f" for this feature is that it does not search (does not "find") anything — it does not really respect "Find" semantics — which may lead to some confusion.

E.g. it will not find a file if it is under a folder that has not been previously opened.
On the first screenshot here, I toggled "Filter", but it has not found a file that was just one-level deep.  It only finds this file if I open its parent folder first.

Only one file found:
![image](https://user-images.githubusercontent.com/53914057/183722197-57111df0-0542-4263-bf48-b82111cade91.png)

But there are actually two files:
![image](https://user-images.githubusercontent.com/53914057/183722307-72b85ae1-6bef-49ba-a79c-c4731658dfae.png)

**Comment by maribethb** [comment]
I don't mind if Ctrl + F opens find when the focus is on the file navigator, so removing the keyboard shortcut entirely feels like overkill. but if I click on a file to open it, the focus should go to that newly opened file imo so that ctrl+f works in the new file immediately instead of also needing to click in the editor first.

I will disable the shortcut for now but just focusing the editor when opening one would solve 99.9% of my headache with this and allow me to keep the feature.

**Comment by gjsjohnmurray** [comment]
By doubleclicking the file in the Explorer tree instead of using a single click, focus will shift to the opened editor and your Ctrl/Cmd+F will operate there. Yes, that action means you lose preview mode, but if after searching the file contents you conclude you don't want to keep it open you can use Ctrl/Cmd+F4 to close it.

**Comment by andy-imt** [comment]
Work-around for those on Mac, also the `&& listSupportsFind` might be necessary to add to the previous work-around:

```
 { 
    "key": "cmd+f",
    "command": "-list.find",
    "when": "listFocus && listSupportsFind"
 }
```

**Comment by gjsjohnmurray** [comment]
See also #166118 which is a new Backlog Candidate. If you want to support it, add a :+1: to the top of that issue.

**Comment by gjsjohnmurray** [comment]
@Scatterblak - which platform?

**Comment by Scatterblak** [comment]
Windows 11,

Version: 1.73.1 (system setup)
Commit: 6261075646f055b99068d3688932416f2346dd3b
Date: 2022-11-09T04:27:29.066Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: No



W. Sean Harrison
CTO, Principal

Hagimo LLC
p: 615.838.9289
e: ***@***.***

http://www.hagimo.com

The contents of this email message and any attachments are intended solely
for the addressee(s) and may contain confidential and/or privileged
information and may be legally protected from disclosure. If you are not
the intended recipient of this message or their agent, or if this message
has been addressed to you in error, please immediately alert the sender by
reply email and then delete this message and any attachments. If you are
not the intended recipient, you are hereby notified that any use,
dissemination, copying, or storage of this message or its attachments is
strictly prohibited.

**Comment by gjsjohnmurray** [comment]
On Windows you need to specify `ctrl`, not `cmd`.

**Comment by jewettg** [comment]
While not fixed, I have found a workaround and I have tested it, MacOS 14.1.2, external keyboard.

1.     Launch VS Code
2.     From the "Code" menu, choose "Settings" --> "Keyboard Shortcuts".
3.     In the window that appears, search for: "Command+F"
4.     Locate the "list.find" line and right-click and remove the keybinding.
5.     Test it for yourself. Click to make the focus the a file in the file list and hit "Command+F" and it will search in the editor, not the file list.

THIS MIGHT work the same for Windows.  Instead of "Command+F", look for "CTRL+F" or whatever the keybinding is for search in Windows.

**Comment by joaomoreno** [comment]
Closing this. Please follow the following workarounds:

**Windows, Linux**

```
  {
    "key": "cmd+f",
    "command": "-list.find",
    "when": "listFocus && listSupportsFind"
  }
```


**macOS**

```
  {
    "key": "cmd+f",
    "command": "-list.find",
    "when": "listFocus && listSupportsFind"
  }
```

**Comment by elcste** [comment]
> **Windows, Linux**
> 
> ```
>   {
>     "key": "cmd+f",
> ```

Should be `ctrl`, right?
