### ISSUE TITLE
Don't auto-forward port on url link click, if it's already statically forwarded

### ISSUE THREAD

**Issue by iAmMichaelConnor** [microsoft/vscode#156104]
I'm using the 'Remote - SSH' extension.

Suppose I set up static forwarding in my local `~/.ssh/config`:

```
Host my_remote
  HostName my_remote.com
  User mike
  ForwardAgent yes
  LocalForward 3000 1.2.3.4:3000
```

So port 3000 is statically forwarded to port 3000.

Now if I output a link `http://localhost:3000` to the terminal (from within the remote), when this link is 'Command + Clicked', vscode opens `http://localhost:3001` in the browser - *the wrong port*, because it's auto-forwarded to the next available port. 

It feels like if static forwarding for this port is already set up, it could always infer that no auto port forwarding is needed and hence open in the browser at port 3000.

The setting `"remote.autoForwardPorts": false,` does not help in this case.

Thanks :)

**Comment by roblourens** [comment]
Yes

**Comment by alexr00** [comment]
Thanks for confirming!

**Comment by alexr00** [comment]
This looks like it will be a larger change. Moving to September.

**Comment by Apreche** [comment]
Hi. Just encountered this problem today. I am using VSCode Docker remotes with Docker Desktop. One of my containers is running minio. There is a static port forward configured in devcontainer.json that looks like this:
```
"forwardPorts": [
     "minio:9000",
     ...
]
```
My application sometimes prints out a full URL to the integrated terminal that looks like `http://localhost:9000/bucket/directory/file.jpg` Clicking that link to open it in my web browser causes VSCode to dynamically forward a brand new port and rewrite the URL replacing the 9000 with something like 50063. I would actually be ok with that, but that URL with the new port number doesn't even work. The original one does work.

My situation sounds basically the same as OP, only using Docker remote instead of SSH remote. Just wanted to share my use case to verify it is actually the same issue and that whatever solution comes will solve it for both of us.

I also want to say this feature was very unexpected. Personally, I think it should be off by default. URLs should be opened exactly as they are written. Please provide at least a setting so I can always open URLs from integrated terminal exactly as they appear. 

The back of my mind also wonders if there could be any potential security implication of rewriting URLs this way.

Thanks.
