### ISSUE TITLE
Intellisense can follow user's case in case insensitive languages

### ISSUE THREAD

**Issue by scnwwu** [microsoft/vscode#156125]
I wrote an extension providing code completion for a custom programming language. The language is case insensitive. The language server provides all completion items in lowercase. But if a user typed uppercase prefix, they would like uppercased keywords committed with autocompletion.
It doesn't make sense to provide both lower and uppercase items to one list as they're same. The list can be requested by trigger character when there's no prefix yet. Parsing existing text may not work. The code can have mixed case. Take SQL as an example, some users would like `SELECT a FROM db`.
So I'm thinking it requires VS Code makes it when commiting the text. Please let me know if it can be achieved in extension itself. Thanks,

**Comment by jrieken** [comment]
I don't see this as a general usecase and usually extensions pick on style/flavour when offering language smarts. Anyways, you can solve this within your extension by marking the completion result as [isIncomplete](https://github.com/microsoft/vscode/blob/8e42bda5487a953d59fab7792eedd4ca209cabba/src/vscode-dts/vscode.d.ts#L4397) so that you get asked on each typed character for completions again. With that you can matching the casing

**Comment by jrieken** [comment]
Closing this as question
