### ISSUE TITLE
Support a better config language

### ISSUE THREAD

**Issue by metov** [microsoft/vscode#156201]
Much user configuration of VS code is done via `User/settings.json`. Unfortunately, JSON has some issues as a configuration language:

* No native comments (you have to use hacky approaches like creating "_comment" keys)
* Unpredictable handling of whitespace
* Overly strict (eg. commas required after every element, but not allowed after final element)
* No way to import or include other files
* Not very human-readable

Here is an article that goes into details about using JSON as a config language, as well as examining some alternatives: https://www.lucidchart.com/techblog/2018/07/16/why-json-isnt-a-good-configuration-language/

It's possible to find many more such discussions with a search: https://www.bing.com/search?q=why+not+json+configuration+language

Given the use case of VS code, it is likely that typical configurations will grow to be complex, and often edited by users, as well as tracked in VCS (dotfiles). JSON seems like an inappropriate choice. Is it possible to add the option of another, more appropriate language?

Some possible alternatives that come to mind:
* YAML has many of the features JSON is missing. It is also very widespread and likely familiar to most users. YAML is a superset of JSON so existing JSON configs would work as is.
* TOML is a popular config format which also has many features missing from JSON.
* Various JSON extensions would allow adding some of the missing features without breaking any existing configs.

Although I mention backwards compatibility above for the sake of completeness, this is probably not a big concern. If the switch is made to another language (rather than supporting a new language in addition to JSON) then it would be easy for VS code to detect a JSON config and automatically convert it to the new language.

**Comment by aeschli** [comment]
For our settings files we allow comments and tolerate trailing commas. We call it JSONC, which is our (internal) variant for all our config files.
What do you mean by 'unpredictable handling of whitespace'?

Each other language has their pro's and cons. One 'pro' for JSON is that we already have a rich JSON editing experience (code completions, hovers, validation).

Our main UI for editing settings is the settings UI with rich user controls. The JSON file is more of an expert mode.
That's why we have no plans to add another variant of our settings files.
