### ISSUE TITLE
Feature Request / Issue

### ISSUE THREAD

**Issue by MandarSant** [Microsoft/vscode#15634]
- VSCode Version:Latest
- OS Version:win 8.1

This might be issue or feature request 
i changed the integrated terminal  from **cmd** to **cmder** but when we open it  opens in separate window is it vscode problem (If problem please make it that it should be open within editor ) or cmder problem

**Comment by Tyriar** [comment]
cmder is a full-blown terminal emulator application which wraps a shell like cmd. VS Code's integrated terminal is also a terminal emulator so it can't run cmder inside it.

**Comment by MandarSant** [comment]
@Tyriar i didnt got what u mean...??

**Comment by Tyriar** [comment]
You can't run cmder inside vscode as its just a Windows application like vscode is. Cmd or powershell however are design to be talked to by "terminal emulators".

**Comment by emengjzs** [comment]
Since cmder can be intergrated with Atom through the plugin 'platformio-atom-ide-terminal', there is no reason to say that vscode can not run with cmder inside.
  
Inspired from [Atom Editor + Cmder](http://thebar.cc/atom-editor-cmder/),  we can also be able to use cmder inside vscode.
  
Create a file name `runCmder.cmd` in the dictinoary of cmder (or somewhere else, may add it to the PATH environment variable) , and put some commands as below:

```
@echo off 
SET CMDER_ROOT=C:\the\path\to\cmder
"%CMDER_ROOT%\vendor\init.bat"
```
`init.bat` may be `init.cmd` in some versions of cmder.
  
Then open the integrated terminal in vscode, and run the command `runCmder.cmd`. We can see cmder is running inside vscode.

![default](https://cloud.githubusercontent.com/assets/7304128/21890238/b547be8a-d907-11e6-9aed-023c61a10a57.png)

The last question is, is there any setting in whcih we can define the command we need to run after the integrated terminal started? It seems that the setting `terminal.integrated.shellArgs.windows` does not work well for this.

**Comment by Tyriar** [comment]
This is not "cmder" technically though, it's the shell that runs within cmder. I am interested in trying this out though and seeing how it compares with the version of bash that ships with Git.

**Comment by Tyriar** [comment]
Just got it working and it seems the main issue with git bash is still present; the on screen prompt gets out of sync with the actual prompt input.

One amendment I'd make to your instructions @emengjzs is to not bother adding the PATH and instead pointing to the file directly:

```js
"terminal.integrated.shellArgs.windows": [
  "/k", "C:\\Users\\<your user>\\Documents\\runCmder.cmd"
],
```
