### ISSUE TITLE
switched to a branch and profile changed back to default

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#156364]
Testing #156188

I used the scm view to create a new branch and the window reloaded and switched from my current profile to the default profile

**Comment by sandy081** [comment]
Will be fixed along with https://github.com/microsoft/vscode/issues/153472

**Comment by sandy081** [comment]
@joyceerhl May I know why different branches of same repository are treated as different workspaces. In Desktop, they are all same workspaces.

**Comment by joyceerhl** [comment]
I wasn't involved in that design decision, but there's a 1-1 mapping between the URI and the branch/tag/commit info, and this enables users to have multiple branches/refs for the same repo checked out in different github.dev tabs or RemoteHub VS Code instances at once (and separate uncommitted changes can be associated with each branch/tag/commit 'checkout').

**Comment by sandy081** [comment]
Ok that explains. I think URI path is treated as workspace ID and different branches of same repo have different URIs, each brach is treated as different workspace. May I know why branch/tag/commit info is not a query of URI instead of path? If it is part of the query then all of them will be treated as same workspace and aligns with Desktop.

**Comment by joyceerhl** [comment]
The branch/tag/commit info is in the URI authority rather than the path and the exact metadata packed into the authority is provider-specific, so decoding is delegated to the registered provider e.g. Azure Repos or GitHub. I believe we did not include this information in the path because once the workspace folder URI is set it becomes the root for relative filepaths like files in the repo. Also, I am surprised to learn that

> If it is part of the query then all of them will be treated as same workspace and aligns with Desktop

as I recall @bpasero saying in https://github.com/microsoft/vscode/issues/147183#issuecomment-1104761564 that even if the URI differs only in query it is still considered a different resource.

**Comment by bpasero** [comment]
Here is how we compute the workspace ID: 
https://github.com/microsoft/vscode/blob/5cf4a848f9d297f6708e6dbd27b2a48f03ac6595/src/vs/workbench/services/workspaces/browser/workspaces.ts#L32-L34

Desktop is slightly more complicated, but fundamentally the same.

**Comment by sandy081** [comment]
Interesting, we ignore query and fragment of a folder while getting the workspace folder of a resource 

https://github.com/microsoft/vscode/blob/c23afced7dc031ea5da246a40a49665d92523c25/src/vs/platform/workspace/common/workspace.ts#L297

Hence I thought workspace id also ignores query and fragment. This actual causes a bug that a resource can belong to multiple workspace folders and also that same folder can be added twice with different query and fragment paths.

Anyway this is not an issue here since branch/tag/commit uses authority.

I am closing this as won't fix because the branch/tag/commit are different workspaces in web and profiles are associated to workspaces. The experience was made better with the fix https://github.com/microsoft/vscode/issues/153472 because the new workspace gets the profile from the current workspace.
