### ISSUE TITLE
Why does each opened folder cause a change to workspaces.json?

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#15638]
I find that one reason for potential stale backups (that is, a backup workspace without backups) is that we add a workspace to the `workspaces.json `file as soon as we open a folder. Why is that? Wouldn't it make more sense to update `workspaces.json` as soon as the first backup is written?

Source: https://github.com/Microsoft/vscode/blob/master/src/vs/code/electron-main/windows.ts#L482

**Comment by Tyriar** [comment]
If we updated `workspaces.json` on the first backup we would need to send a message to the main process over IPC since it is the only one that can write to the file. If we do https://github.com/Microsoft/vscode/issues/15499 I don't think the way it's done now really hurts at all, writing it on window start is playing it safe; in the off chance that it's in `workspaces.json` and there is no backup (a crash), it will get handled on launch.

**Comment by bpasero** [comment]
Right, the current model is safer. We cannot rely on IPC to function on a crash scenario.
