### ISSUE TITLE
Not seeing SCM spelling mistake in Problems View

### ISSUE THREAD

**Issue by tanhakabir** [microsoft/vscode#156335]
Testing #156185

Not seeing my spelling mistake in Problems View:
<img width="1314" alt="image" src="https://user-images.githubusercontent.com/12758612/181079105-5e4cde5c-00c9-4abd-a6b4-8c13d66a780a.png">

**Comment by lszomoru** [comment]
My bad, now I see that I actually had a typo in the test plan item 🤦🏻‍♂️. Problem markers for the text document associated with the commit input are not shown in the "Problems view" by design. Based on conversations with others the makers in the "Problems view" are associated with resources that can be opened in an editor.
