### ISSUE TITLE
Testing drop-in-editor API: Extension sample doesn't correctly make list of filenames

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#156371]
Testing #156223

When I tried to extension sample, I tried dragging multiple files into the editor and it seemed to only have a list of one item. 

I found that the `urlList` that it gets here doesn't seem to have newlines between the links although the extension uses `\n` to separate the urls.
https://github.com/microsoft/vscode-extension-samples/blob/b296149e66db76f9a2f63c1d0828a3e3d365c260/drop-on-document/src/extension.ts#L63

Maybe this is just a windows thing? But regardless, the function inserts only one file for me.

**Comment by mjbvz** [comment]
This definitely seems like a chromium bug to me: https://bugs.chromium.org/p/chromium/issues/detail?id=1368361

It does not happen on firefox or on Mac in my testing

Instead of checking in another workaround for this (which I already did for copy/paste), I'm going to mark this bug as upstream so we can hopefully get the root cause addressed

**Comment by mjbvz** [comment]
We switched to use an internal uri-list type when dragging within VS Code. For external drags you may still hit this issue but I don't think we can work around it on our side. Will keep tracking the Chromium issue
