### ISSUE TITLE
IBackupFileService should not be aware of getWorkspaceBackupPaths

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#15642]
I am wondering why each `IBackupFileService` needs to be aware of `workspaces.json` and the contents. To me a backup file service is being created on exactly one backup workspace (determined by `IWorkspaceContextService`) and thats it. With a dependency to `workspaces.json`, this service steps into the territory of `IBackupMainService` and that smells of debt. 

I would like to understand why this is really needed?

The only use case seems to be the already very complicated `backupBeforeShutdown` conditions in https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/backup/node/backupService.ts#L135 which are impossible for me to understand quickly even with the comments.

**Comment by Tyriar** [comment]
Yes it's only used during shutdown, specifically to determine the number of windows that are opened and reacting to it. Hot exit will trigger on Linux and Windows when he window being closed it the last window. The main process remains active on Mac which is why it only applies on Linux and Windows.

This could be changed to pinging the main process for the window count over IPC, I can make that change if that's better (using `electron.ipcRenderer`?).

**Comment by bpasero** [comment]
@Tyriar if you need to know the number of windows open, please add this to the IWindowService, it uses Joaos IPC mechanism and it should be very easy to add. https://github.com/Microsoft/vscode/blob/master/src/vs/platform/windows/common/windows.ts#L14
