### ISSUE TITLE
.gitignore files are not working

### ISSUE THREAD

**Issue by JamesBewley** [Microsoft/vscode#15640]
- VSCode Version: 1.7.1
- OS Version: Windows 10 Pro 

Steps to Reproduce:

1.  Have a large project with multiple .gitignore files in sub-directories
2. See all ignored files in the changes list of Visual Studio Code

**Comment by JamesBewley** [comment]
All these files are showing up as untracked files

**Comment by joaomoreno** [comment]
Code just shows what git provides.

If you run `git status -u` and see the files listed, it means you have misconfigured those `.gitignore` files. Please refer to [git's documentation](https://git-scm.com/docs/gitignore) for help.

**Comment by JamesBewley** [comment]
This has been working previously and there have been no changes to the .gitignore files.  These files also don't appear in git when run from powershell.

Which version of git does visual studio code use?

**Comment by joaomoreno** [comment]
If you call `git status -u` from Powershell, you don't see those files? Can you share a screencast of this, alongside Code showing them?

Code picks up your globally installed git. You can overwrite this with the `git.path` configuration setting.

**Comment by tizoc** [comment]
@joaomoreno `git status -u` shows all untracked files, yes, but I would expect (like in other git UIs) for the changes tree to not care about files that the user has explicitly ignored through .gitignore (that is, for it to reflect the results of `git status` not `git status -u`).

**Comment by tizoc** [comment]
I just changed this line here: https://github.com/Microsoft/vscode/blob/6b1c9cd61df6666249d17efa33a35ea0e6af1e11/extensions/git/src/git.ts#L886

from

```javascript
const child = this.stream(['status', '-z', '-u']);
```

to

```javascript
const child = this.stream(['status', '-z', '-unormal']);
```

and got the behaviour I wanted. Shouldn't this be how it works by default?

**Comment by joaomoreno** [comment]
Code will ignore files listed in `.gitignore`, unless they actually have been added to the index and committed once before. Is that your case?

If a file was never staged and committed, is listed in `.gitignore` and has changes, Code should not show it. Do you mean that in your case, Code does show it?

**Comment by tizoc** [comment]
@joaomoreno sorry, what I mentioned in my previous comments is wrong. The answer to your question is **no, Code doesn't show it**.

What I thought was ignored files showing up, is actually the contents of untracked (but not ignored) directories not being collapsed into a single entry (like `git status` and `git status -unormal` do).

**Comment by joaomoreno** [comment]
Oh yeah. That's a purposeful behavior we set up, it seems to please most people. What would you prefer?

**Comment by tizoc** [comment]
The current behaviour is fine, it just happens that my current situation is a bit particular, and it makes Code reach the limit of 5000 files (and also, having so many files in the output of the non-collapsed version of `git status` makes things slower). But thats something I can fix easily by adding new entries to `.gitignore`.

But matching the default `git status` behaviour would be an improvement, because of the new more useful behaviour in itself, but also because it makes it less fragile to unexpected situations where you suddenly have a (not yet ignored) directory with a lot of files in it that "breaks" your `Source Control` panel.

But I understand this is a change more complicated than just filtering out results, as it involves some extra UI considerations -- right now the `Source Control` tab only cares about individual files, it has no sense of directories or hierarchy, collapsing untracked directories would mean that it now has to be able to navigate those? or expand them? I don't know.
