### ISSUE TITLE
Add proprietary codecs to FFmpeg

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#156558]
Add the following codecs to our FFmpeg version:

* H.264
* VP8
* VP9
* AAC
* WAV
* MP3
* Opus

This would fix https://github.com/microsoft/vscode/issues/118275 and https://github.com/microsoft/vscode/issues/147190

Work to be done (roughly):
- [x] Get legal review and approval
- [x] Create electron version with all the codecs
- [ ] Self host a full milestone on it

**Comment by isidorn** [comment]
We got approval to ship the following:
* Vorbis
* Flac
* H.264
* VP8
* WAV
* MP3

**Comment by dmalan** [comment]
Thank you for this! Especially helpful for educational use cases like embedding instructional videos in Markdown files!

**Comment by isidorn** [comment]
@dmalan welcome! Once you try it out do let us know how it works in practice. Since we do not support all the popular codecs we hope that the current list will give you enough flexibility.

**Comment by rajkundu** [comment]
This works great! It is a huge boon for computer vision applications such as mine, where I am continuously processing, analyzing, and re-rendering videos. The only hiccup I've encountered is the fact that OpenCV, a very popular library for computer vision, unfortunately doesn't support H.264 encoding due to some licensing issues. However, there are workarounds and other libraries.

Regardless, thank you very, very much for this! 😄
