### ISSUE TITLE
Terminal smoke test failure

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#156554]
```
  1) VSCode Smoke Tests (Web)
       Terminal
         Terminal Persistence
           detach/attach
             should persist buffer content:
     Error: Timeout: get terminal buffer '#terminal .terminal-wrapper' after 20 seconds.
      at Code.poll (/__w/1/s/test/automation/src/code.ts:256:11)
      at Code.waitForTerminalBuffer (/__w/1/s/test/automation/src/code.ts:225:3)
      at Terminal.waitForTerminalText (/__w/1/s/test/automation/src/terminal.ts:270:4)
      at Context.<anonymous> (src/areas/terminal/terminal-persistence.test.ts:78:5)
```

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=179605&view=logs&j=e5bbec05-0f06-558d-ebe9-5973d52063d2&t=a671546b-2469-5fb1-b2c9-08e628dcad6d

**Comment by meganrogge** [comment]
Also skipped the terminal profile tests bc they were failing and holding up PRs https://github.com/microsoft/vscode/pull/156906

**Comment by meganrogge** [comment]
in this particular run, the settings are saved then the quickpick opens and nothing is entered

**Comment by meganrogge** [comment]
so it appears that this step didn't work according to the trace viewer, since no input happens

https://github.com/microsoft/vscode/blob/93e7d91f6c36814bdc7f28837bc598f9511d7421/test/automation/src/quickaccess.ts#L166-L170

not sure why it didn't report a failure for 

https://github.com/microsoft/vscode/blob/93e7d91f6c36814bdc7f28837bc598f9511d7421/test/automation/src/code.ts#L218-L221

**Comment by meganrogge** [comment]
never mind - ignore the above - the image preview just doesn't work for some reason but going through the actions shows a terminal does get created

**Comment by meganrogge** [comment]
I investigated this and based on the actions log, this should be passing
