### ISSUE TITLE
Support External Diff

### ISSUE THREAD

**Issue by bc3tech** [Microsoft/vscode#15661]
- VSCode Version: 1.7.1
- OS Version: Windows 10.14965.1000

If I've configured an external diff program in my git repo/user/system settings, VS Code should enable the ability to diff with that program instead of only in the VS Code window.

and if it's possible today, it' very well hidden ;)

**Comment by joaomoreno** [comment]
You can write an extension that contributes global and menu commands which invoke external applications at will.

**Comment by bc3tech** [comment]
is our response to every feature request "write an extension yourself"? I suppose i _could_ file this as a bug for VSCode not respecting git settings... would that make more sense? i don't want to invoke any external app, i want to invoke the diff tool and command that is configured in the git repo for a project. as it is, VScode is disregarding these settings.

**Comment by joaomoreno** [comment]
Sorry, but this really seems like a very specific preference. Most people just want to see the diff within Code itself, when clicking on a changed file, regardless of what happens when they run `git difftool` in the command line.

My suggestion for _this specific feature request_ is to write an extension for it.
