### ISSUE TITLE
Extension is not compatible with Code 1.70.0-insider. Extension requires: 1.69.0

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#156745]
<img width="1051" alt="image" src="https://user-images.githubusercontent.com/41773861/182023949-d94db8a3-bc5c-4729-af62-db8bfb144369.png">

Reproduce:

1. git clone `git@github.com:tjx666/open-in-external-app.git`
2. open debug panel and click `dev`
3. open devtools in extension workspace

Versions:

```
Version: 1.70.0-insider (Universal)
Commit: 12b08be500f8a307f30e92cbc3ee39ba115eab69
Date: 2022-07-29T10:50:40.282Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin x64 21.6.0
```

**Comment by tjx666** [comment]
Any idea about this issue? I can't debug the extension in my vscode-insiders now?

**Comment by weinand** [comment]
@tjx666
the message "Extension is not compatible with Code 1.70.0-insider. Extension requires: 1.69.0" shows a problem of the "open-in-external-app" extension.

The package.json of the extension says that it is only compatible with **exactly** version 1.69.0:
https://github.com/tjx666/open-in-external-app/blob/2ed9a63f5e2f4a954e17ed66dda8c6bd0b43fd51/package.json#L36 

In order to make the extension compatible with **version 1.69.0 or newer** please use something like "^1.69.0".
