### ISSUE TITLE
Does Edit Sessions need a separate log?

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#156872]
<img width="1021" alt="image" src="https://user-images.githubusercontent.com/10746682/182325861-56b54c0f-49b3-4fa9-b7e0-71330cfedc20.png">

Can this be part of window log?

**Comment by joyceerhl** [comment]
I initially had it all go to the window log because I thought it would be overkill, and @lszomoru suggested creating a separate output channel to make it easier for users to find relevant logs (e.g. correlation id when requests fail) if we created a separate output channel. Having a separate output channel has made it easier for me to scan the log output personally as well when debugging issues so I would prefer to keep it this way.

**Comment by joyceerhl** [comment]
Closing for now but please let me know if you feel strongly about this and we can reopen and discuss.
