### ISSUE TITLE
Focus on __ View commands are improperly localized

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#157015]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.70-insider
- OS Version: Windows 11

Steps to Reproduce:

1. Configure display language
2. Search for 'Focus on' in the command palette (all views get a focus command auto-registered)
3. :bug: builtin views have the category and view title translated in the original version of the title being displayed
![image](https://user-images.githubusercontent.com/30305945/182657945-ea13b1f3-be3c-48d6-aa0e-d17aa7b66266.png)

We should probably support `ILocalizedString` for view titles and categories when registering these commands

**Comment by TylerLeonhardt** [comment]
This is because for the "original" text, the `viewDescriptor.name` is used:

https://github.com/microsoft/vscode/blob/2d502be79d044ed34fcea16eeb02cf98b789789c/src/vs/workbench/browser/parts/views/viewsService.ts#L491

That is just a `string`:
https://github.com/microsoft/vscode/blob/2d502be79d044ed34fcea16eeb02cf98b789789c/src/vs/workbench/common/views.ts#L267

and is always localized:
https://github.com/microsoft/vscode/blob/2d502be79d044ed34fcea16eeb02cf98b789789c/src/vs/workbench/contrib/bulkEdit/browser/preview/bulkEdit.contribution.ts#L341

To fix this, we need to change that `string` to an `ILocalizedString` and fix all compilation errors.
