### ISSUE TITLE
[fedora][gnome] slow rander? jumping cursour , lag keys, sometime black window

### ISSUE THREAD

**Issue by procolost** [microsoft/vscode#157016]
Issue Type: <b>Bug</b>

write python file and use auto complete 
introduce after update from 1.69.0 to 1.69.2  
VS Code version: Code 1.69.2 (3b889b090b5ad5793f524b5d1d39fda662b96a2a, 2022-07-18T16:14:10.636Z)
OS version: Linux x64 5.18.9-200.fc36.x86_64
Restricted Mode: No
Remote OS version: Linux arm64 5.15.32-v8+
Remote OS version: Linux arm64 5.15.32-v8+

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz (8 x 3491)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.49GB (4.23GB free)|
|Process Argv|--unity-launch --crash-reporter-id 0025d8e8-aeb2-43b0-91c2-ff0d7a0df4b1|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|wayland|

|Item|Value|
|---|---|
|Remote|SSH: superhost|
|OS|Linux arm64 5.15.32-v8+|
|CPUs|unknown (4 x 1500)|
|Memory (System)|3.71GB (0.56GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: superhost|
|OS|Linux arm64 5.15.32-v8+|
|CPUs|unknown (4 x 1500)|
|Memory (System)|3.71GB (0.56GB free)|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-ssh|ms-|0.84.0
remote-ssh-edit|ms-|0.80.0
go|gol|0.35.1
python|ms-|2022.10.1
vscode-pylance|ms-|2022.7.40
jupyter|ms-|2022.6.1201981810
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.9
vscode-proto3|zxh|0.5.5

</details>

**Comment by kinoher** [comment]
if you use nvidia with proprietary drivers, try 
```code --verbose --disable-gpu ```

**Comment by sysoev-dev** [comment]
> 

Isn't wayland faster on nvidia?

**Comment by sysoev-dev** [comment]
> code --verbose --disable-gpu

Isn't wayland faster on nvidia?

**Comment by kinoher** [comment]
The nvidia driver is a piece...
You can only work on wayland.
Since there are problems with reclock on x11, the video card is overclocked for every window change or menu opening. At x11, your graphics card is your personal BBQ workbanch
it's very old problem without any solvation 

https://forums.developer.nvidia.com/t/very-slow-ramp-down-from-high-to-low-clock-speeds-leading-to-a-significantly-increased-power-cons/49098/156

+ New chromium release a have problem with mesa dri context and can't correctly use videoaccel nvidia 
  
MESA-LOADER: failed to retrieve device information
MESA-LOADER: failed to open nvidia-drm: /usr/lib64/dri/nvidia-drm_dri.so: cannot open shared object file: Permission denied (search paths /usr/lib64/dri, suffix _dri)
failed to load driver: nvidia-drm

**Comment by procolost** [comment]
> if you use nvidia with proprietary drivers, try `code --verbose --disable-gpu `

thanks it's work
