### ISSUE TITLE
`workbench.action.next|previousEditor` does not work across empty groups

### ISSUE THREAD

**Issue by ngmariusz** [microsoft/vscode#157178]
`workbench.action.nextEditor` and `workbench.action.previousEditor` works only if next/previous editors group is not empty what is possible (and requested) when `workbench.editor.closeEmptyGroups` is set to `false`

**Comment by bpasero** [comment]
Good catch, I argue this is even a bug and I think I have a fix for it.

**Comment by meganrogge** [comment]
@bpasero what I expected to see with that set to false was focusing of the editor (even if empty) that I focused previously, but what I see instead is the last file I closed gets reopened in the empty editor group

**Comment by bpasero** [comment]
I am not sure I fully understand, what are the steps you do?

**Comment by meganrogge** [comment]
1. Create a few editor groups - 2 of which are empty
2. Focus empty group A then focus the non-empty group and go to previous editor

Expected: 

Focused group is empty group A

Actual:

Last editor I closed gets opened and focused in empty group A

**Comment by bpasero** [comment]
@meganrogge are you sure you really picked the "Open Previous Editor", because there are others:

<img width="742" alt="image" src="https://user-images.githubusercontent.com/900690/186827052-5cfdc577-9acb-4e94-82c1-054a75042c5d.png">

The command will not focus an empty editor group. The command is about editors, not editor groups.

**Comment by meganrogge** [comment]
Oh then the behavior works as-designed - sorry for the misunderstanding 👍🏼
