### ISSUE TITLE
 Container creation failed.

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode#157176]
ADD ISSUE DESCRIPTION HERE

Version: 1.70.0
Commit: da76f93349a72022ca4670c1b84860304616aaa2
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by wagdyh21** [comment]
This codespace is currently running in recovery mode due to a container error. Review the creation logs, update your devcontainer configuration as needed, and run the "Rebuild Container" command to retry. i just signed up for VS recently and now everytime i log in it shows me this message and i can't rebuild the container again.
