### ISSUE TITLE
Event Loop: Socket callback being ignored

### ISSUE THREAD

**Issue by mbana** [Microsoft/vscode#15726]
I guess this is might be an Electron isusue, not sure.
Any thoughts much appreciated.

My setup is:

* VSCode extension that setups a [WebSocket](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket) connection.
* I've added callbacks to the various events.
* I almost sure I am getting some timing related issue as when I am debugging, the socket connection is established.

**Misc:**

* I've got the exact same code, with matching deps, running as standalone nodejs app and it doesn't exhibit the same behaviour.
* I've tried two WebSocket implementations in nodejs and they both do *funny* things when run in VSCode; non-sensical errors. Yet, in pure nodejs they work fine. I am going to try one more just incase.

**Qs:**

1 - Is it possible to get debugging support to be on par with Chrome? E.g., in an extension that makes http requests, it would be nice to somehow see those requests.

 2 - How do I set env. variables in the `launch.json` of `extensionHost? I have to manually export before launching `code` at the moment - second shell script.

```json
"name": "Launch Extension",
"type": "extensionHost",
"request": "launch",
"runtimeExecutable": "${execPath}",
"args": [
	"--extensionDevelopmentPath=${workspaceRoot}",
	"--nolazy=true",
	"--verbose",
	"--wait",
	"--enable-logging",
	"--disable-http-cache",
	"--log-net-log=${workspaceRoot}/logs/net.log"
],
"sourceMaps": true,
"outFiles": [
	"${workspaceRoot}/out/**/*.js"
],
"preLaunchTask": "npm",
"stopOnEntry": true
```

```sh
NODE_DEBUG="cluster,net,http,fs,tls,module,timers node"
ELECTRON_ENABLE_LOGGING="true"
code -p --verbose --wait --nolazy=true .
```

3 - What's the recommended way of setting breakpoints when doing extension development. The debugger isn't respecting my breakpoints and I have to manually force - enabling then disable - to get it to work. I've tried `"debug.allowBreakpointsEverywhere": true`. Setup is:

```sh
-+= extension
 |-+= dep
 | |-+= dep
 |-+= dep
 | |-+= dep
```

all the `dep`s are TypeScript projects.  The debugger sees that I have set a breakpoint but doesn't stop at it.

**Comment by weinand** [comment]
@mbana first answers to your questions:

1. debugging http requests in a extension should be no problem at all. Almost all extension do something like this and this works for us and we have no reports that this doesn't work for others.
1. You cannot control the node process that runs your extension code. This process is launched by VS Code and it is shared between all extensions. So you can neither pass arguments to that process nor can you set env variables specifically for your code. All arguments that you pass in your launch config are passed to VS Code and not to the node process that runs your extension. In general it is sufficient to only use `"args": ["--extensionDevelopmentPath=${workspaceRoot}" ]`.
1. If breakpoints don't work, then either your `outFiles` does not cover all the generated code or your source maps are not correct. Setting `debug.allowBreakpointsEverywhere` will not help here because it solves a completely different problem.

I recommend to start extension development by using the yeoman generated "hello world" extension. Try to set and hit breakpoints there. Then add additional functionality like 'making a http request'. Try to make small incremental steps in the beginning and verify that your source maps are always correct and that you able to hit breakpoints.

**Comment by mbana** [comment]
@weinand,
Many thanks for the suggestions, I created a simple extension to reproduce the problem and I couldn't reproduce, better yet, I found my problem.

**Comment by weinand** [comment]
@mbana great to hear that you've found the problem.
