### ISSUE TITLE
Error.stack property is not a string in ipc.ts

### ISSUE THREAD

**Issue by stbfb** [microsoft/vscode#157335]
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version:
    Version: 1.69.2 (Universal)
    Commit: 3b889b090b5ad5793f524b5d1d39fda662b96a2a
    Date: 2022-07-18T16:12:57.074Z (2 wks ago)
    Electron: 18.3.5
    Chromium: 100.0.4896.160
    Node.js: 16.13.2
    V8: 10.0.139.17-electron.0
    OS: Darwin arm64 21.6.0

- OS Version:
macOS Monterey Version 12.5

Steps to Reproduce:

First noticed the problem when using `executeCommand` on the `ICommandService` service. If this command fails the `stack` property on the `Error` object that is returned is not a `string` as was expected. After digging deeper it seem that in [ipc.ts](https://github.com/microsoft/vscode/blob/main/src/vs/base/parts/ipc/common/ipc.ts) the `stack` property on an `Error` gets converted to a `string[]` on a failed call.

**Comment by alexdima** [comment]
Indeed, for errors we read the `.stack` property and convert it to a `string[]` [here](https://github.com/microsoft/vscode/blob/0bf34b13080a64dede61c655defadefe598196f8/src/vs/base/parts/ipc/common/ipc.ts#L397). On the other side, we then set the `.stack` property and it becomes a `string[]` instead of the usual `string` [here](https://github.com/microsoft/vscode/blob/0bf34b13080a64dede61c655defadefe598196f8/src/vs/base/parts/ipc/common/ipc.ts#L559).

**Comment by jrieken** [comment]
verified in sources
