### ISSUE TITLE
Error telemetry: always start to deminify stacks

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#15752]
I think there is no reason to click on an error in telemetry and not run the deminification, so why not just start it right when clicking on an error?

**Comment by ramya-rao-a** [comment]
The xflow jobs process the error telemetry data (# of times an error with unique call stack was logged against platform/date/version etc) and dumps this to a sql db.

The error telemetry website queries this table to show you the table for selected vscode version
Its only when you click on the `deminify` button, that we make a call to blob storage containing the source maps, and show the demagnified call stack.

I see the benefit of having a separate process that polls the db for errors, fetch the sourcemaps and store the demagnified call stack in sql db.

Good idea. It definitely can be done.

**Comment by ramya-rao-a** [comment]
True, for a given vscode version, there is only 1 call to make to get the source maps which we can do upfront.

**Comment by ramya-rao-a** [comment]
Fixed with https://monacotools.visualstudio.com/Monaco/_git/VSCodeInternal/commit/6a7215d271a6256ccb8d59a378e5fc03504967ef

Correction on https://github.com/Microsoft/vscode/issues/15752#issuecomment-261733914 :
Call to get sourcemaps is made once for each file in the callstack not once for each vscode version.
If the same file occurs in multiple error call stacks, then the call is not made again as long as you are in the same session
