### ISSUE TITLE
shell open vscode

### ISSUE THREAD

**Issue by liyi0215** [Microsoft/vscode#15757]
- VSCode Version:
- OS Version:

Steps to Reproduce:

让vscode可以从shell启动，例如atom的  `atom .` 代开当前目录代码

**Comment by ramya-rao-a** [comment]
This is the translation I got from your text:

>Let vscode start from the shell, such as the atom of the atom. Instead, open the current directory code

When you open from vscode from shell, it opens the current directory. That is by design.

What is your expectation?
- It should open empty window with no folder? You can do this by `code -n`
- It should open a particular file? You can do this by `code -g file path`
- It should open a particular folder? You can do this by `code folderpath`

Does this help?
