### ISSUE TITLE
Editor freezes when open `lib.dom.d.ts` with sticky scroll enabled

### ISSUE THREAD

**Issue by yume-chan** [microsoft/vscode#157614]
Type: <b>Bug</b>

1. In a TypeScript file, go to declaration on any DOM API (for example, type `window` and press F12 on it). It opens `lib.dom.d.ts`.
2. Open settings, enable `editor.experimental.stickyScroll.enabled`
3. The window immediately freezes.

VS Code version: Code - Insiders 1.71.0-insider (5cf4a848f9d297f6708e6dbd27b2a48f03ac6595, 2022-08-09T05:17:58.837Z)
OS version: Windows_NT x64 10.0.25174
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600X 6-Core Processor              (12 x 3700)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.91GB (12.78GB free)|
|Process Argv|--crash-reporter-id f37b47d6-d028-418b-b006-0d623e833af7|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by alexdima** [comment]
I can reproduce in the insiders b0895f9fcc5b49587a2b187a92bbe6d7efae35fa (one Insiders version before the issue was created), and I can see that executing is stuck inside creating the sticky scroll model from the outline model:

<img width="904" alt="image" src="https://user-images.githubusercontent.com/5047891/183918923-05732243-bcd2-4715-a8fc-011a92687a33.png">

However, I can no longer reproduce in today's insiders. I think the refactoring in 2ecea7fa70b94d44b8bd2bf9b5b25c00f213bc53 fixed it.

/closedWith 2ecea7fa70b94d44b8bd2bf9b5b25c00f213bc53
