### ISSUE TITLE
Sticky scrolling is broken on multiline function declarations in C

### ISSUE THREAD

**Issue by tristan957** [microsoft/vscode#157680]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.70.0
- OS Version: Windows 10

Steps to Reproduce:

1. Open a C file
2. Create a function declaration and definition that spans 2 lines like so

```c
static void
func(void)
{
  // ...
}
```

When you scroll through `func`, the sticky scrolling will use `static void` instead of `func`.

![image](https://user-images.githubusercontent.com/11936772/183718956-55ecfe44-8b59-418e-9bd5-ff483f6bb48a.png)

**Comment by niderhoff** [comment]
It is also "broken" for Python functions with decorators:

![image](https://user-images.githubusercontent.com/5991543/183869496-a57ee104-0be8-40f4-977b-b4323b9fa8ff.png)

**Comment by aiday-mar** [comment]
Thank you for your feedback. This should be fixed by https://github.com/microsoft/vscode/pull/157763.

New behavior:

![sticky-scroll-c](https://user-images.githubusercontent.com/61460952/183888544-b9ea478e-c955-47e9-9739-26bdde1c334c.gif)

And:

![sticky-scroll-python](https://user-images.githubusercontent.com/61460952/183888909-b156ae30-eddc-4fc4-8495-b69db5b1a7b8.gif)
