### ISSUE TITLE
Reopen files after a restart (same as for "window.reopenFolders")

### ISSUE THREAD

**Issue by wzup** [Microsoft/vscode#15779]
- VSCode Version: 1.7.1
- OS Version: Windows 10

Steps to Reproduce:

1. Open some files. Not a folder. Just some plain source code files (`Ctrl + O`)
2. Make some changes with them. Save. Don't close files. Close the editor.
3. Open the editor and observe one brand new `Untitled-1` tab only. But where are my previous files? Why were not they opened?

There is a `window.reopenFolders` option. Ok, it is not a bad option. But how about files? How about those devs who do not use folders? I never open folders. Lack of this feature in VSCode is annoying. ST3 has it so I'm compelled to use it.

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.

**Comment by wzup** [comment]
First off, don't tell me what to do. @bpasero 
Second, who are you? A developer of the IDE? Then first implement a search option and live search predictions in this window. You save yourself and your team a lot of time answering *issues that has already been reported*. Not to mention you save company's money. You did bad job, a half of the work, and now you tell others what to do. We post issues here and on Twitter using IDE's UI that you have created. Understand?

![visual studio code 2016-11-28 13 14 48](https://cloud.githubusercontent.com/assets/3880497/20657071/07d5f72e-b56e-11e6-9db3-32b3213f2254.png)

**Comment by bpasero** [comment]
@wzup since you seem to have missed it:

* click on "Submit a bug"
* notice this

![image](https://cloud.githubusercontent.com/assets/900690/20657840/5e9408ec-b539-11e6-913f-fd1e4bc09aa9.png)

* then this

![image](https://cloud.githubusercontent.com/assets/900690/20657851/69d181bc-b539-11e6-81ec-72390d5d0651.png)

* then you should do something like this:

![image](https://cloud.githubusercontent.com/assets/900690/20657874/9994f096-b539-11e6-8d9e-8f28f706f75c.png)

* and then one of the first issues you see is our duplicate: https://github.com/Microsoft/vscode/issues/207
