### ISSUE TITLE
Keyboard shortcuts for specific code actions

### ISSUE THREAD

**Issue by justschen** [microsoft/vscode#157719]
Some feedback from trying out `useCustomCodeActionMenu`: it's no longer possible to select a list item using the keyboard. For example, with the old version I was able to select "Unwrap function call" simply by typing `u`:

<img width="731" alt="image" src="https://user-images.githubusercontent.com/921609/183237750-d6e6806c-76c3-47c6-be18-93c840191039.png">

_Originally posted by @OliverJAsh in https://github.com/microsoft/vscode/issues/152913#issuecomment-1207160914_

**Comment by justschen** [comment]
At the moment, even the old context menu used to show the code action menu didn't support keybindings like this. Seems like this was something that was specific to the native macOS menu, but can also be implemented now in vs code with the custom list widget.

**Comment by zardoy** [comment]
If it will be implemented in the same way as workbench list tree works now, please ensure that typing second key won't reset the sequence. For example typing `s` and then `u` shouldn't select `Unwrap function call`, but `Surround With...`. Because I've seen in some other places such as menu selecting output channel on Windows it listens for first typed character only.

But I think it'd be ideal to use some kind of old widget from explorer area to highlight/filter actions gracefully.

**Comment by jibbers42** [comment]
I'd like to see this implemented as a filter where typing "widj" below would leave you with "Extract Widget" and "Wrap with widget...". This would make it easy to arrow to the desired item when there is more than one matching the filter.

![image](https://user-images.githubusercontent.com/797824/194201264-32a40124-879b-4f73-829d-9e5b04bcaf7f.png)

**Comment by alber70g** [comment]
Will this be fixed. My right hand cries when I have to do a "quick" fix... So much for it being _quick_

**Comment by justschen** [comment]
Revisiting this - may play around with something like this :
![Group 3](https://github.com/microsoft/vscode/assets/54879025/cac9dcae-6678-4988-9b50-43d00a0df2f2)

**Comment by justschen** [comment]
First iteration of this feature is now insiders-released. Continuing to fix and optimize as mentioned in https://github.com/microsoft/vscode/issues/190447
