### ISSUE TITLE
Accept @property jsdoc

### ISSUE THREAD

**Issue by barsdeveloper** [microsoft/vscode#157792]
Sometimes it is necessary to document classes with properties added dynamically (outside the class). The way I was documenting those before was the following way:
```JavaScript
// @ts-check
 class ClassName {
    constructor () {
        /** @type {String} */
        this.propName
    }
}
```

But a recent update of VS Code made this illegal (Property 'propName' is used before being assigned.ts(2565))
There might be a way to document it using [@property](https://jsdoc.app/tags-property.html) from JSDoc
```JavaScript
// @ts-check
/**
 * Class definition
 * @property {String} propName
 */
 class ClassName {
    constructor () {
    }
}
```

But unfortunately it seems to be unsupported by VSCode.

EDIT:
I am aware there is the following syntax
```JavaScript
 class ClassName {
    /** @type {String} */
    propName
    constructor () {
    }
}
```

This is not a satisfactory solution though because it will change the semantic of the code when you want to iterate over the properties of an object when its properties are defined in the super class (It changes the order of declaration)

**Comment by mjbvz** [comment]
Tracked upstream becausehttps://github.com/microsoft/TypeScript/issues/28730

You're seeing that error  because `this.propName` is just referencing the value without assigning it.  You can initialize the value to fix it (and this would be preferable to `@property` IMO as the `@property` example would mean the types are inaccurate until the external assignment takes place):

```ts
class ClassName {
    constructor () {
        this.propName = '';
    }
}
```
