### ISSUE TITLE
Separate out Typescript vs Javascript from builtin extension: "TypeScript and JavaScript Language Features"

### ISSUE THREAD

**Issue by pmeaney-sqrt** [microsoft/vscode#157808]
I would like the built-in extension called "TypeScript and JavaScript Language Features" to instead be broken out into two built-in extensions: "TypeScript Language Features" and "JavaScript Language Features", for these reasons:

- Out of respect for a "Separation of Concerns" philosophy of software development, I do not need or want two different languages features bundled together.
- Many Javascript developers do not use Typescript.  Please do not force us into having language features bundled together.
- I want to be able to use VS Code in a workflow which is purely Javascript based.  While working in a .js file, I do not want to see typescript suggestions.
- **I want "JavaScript Language Features".  I do not want "TypeScript Language Features"**

Why in a javascript format file, am I prompted with Typescript suggestions (screenshot below showing a huge mess of irrelevant-to-my-project Typescript interface suggestions)? This does not make sense.  I feel like Microsoft is trying to foist Typescript on me.

<img width="1269" alt="Screen Shot 2022-08-10 at 10 56 56 AM" src="https://user-images.githubusercontent.com/102547768/183956154-f7c05ac1-beac-4bcd-8db8-25676cf13872.png">

**Comment by mjbvz** [comment]
Sorry but I don't think you understand this area nearly well enough to make such a sweeping proposal. A few quick reasons why there's a single JS/TS extension:

- Both JS and TS use the same intellisense engine (powered by the TypeScript project)
- JS and TS files can reference each other and be part of the same projects
- 95% of the JS/TS extension code is shared between the two languages. It's not like we just shoved two separate stacks for JS and TS into a single extension. The same code handles both languages (because spoiler: besides types, they are the same)


BTW `DragEvent` is a class, not some weird TypeScript thing. Try it out in your browser:

![Screen Shot 2022-08-10 at 9 14 39 AM](https://user-images.githubusercontent.com/12821956/183960739-ce50f5c5-35d2-41be-9310-066af3378c2b.png)
