### ISSUE TITLE
Do no require restart when enabling/disabling mergeEditor

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#157904]

**Comment by jrieken** [comment]
@joaomoreno I guess the reload/refresh logic that we added isn't working...

**Comment by jrieken** [comment]
This is what I am reproducing

* enabled -> disabled: ✅ works
* disabled -> enabled: 🔴 fails

**Comment by jrieken** [comment]
@joaomoreno I will push a workaround, refresh the SCM view when the config changes, because re-setting the merge group (`this.mergeGroup.resourceStates = this.mergeGroup.resourceStates.map(r => r.clone());`) doesn't seem to work reliably. I debugged this in to [`_takeResourceStateSnapshot`](https://github.com/microsoft/vscode/blob/8512ce30382599edd682b6579aeb55a10e8e8fca/src/vs/workbench/api/common/extHostSCM.ts#L378) but wasn't able to get to the bottom of this. When calling the method it seems that `this._resourceSnapshot` is already updated with what I am expecting to be updating now... 😕 

fyi  @lszomoru
