### ISSUE TITLE
WCO buttons not zooming properly with titlebar

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#158026]
1. Enable windows control overlay feature and custom titlebar
2. Zoom in
3. The titlebar font becomes larger, but the WCO buttons stay the same size.

**Comment by sbatten** [comment]
I am making the assumption that this refers to the icons not increasing in size since the buttons do increase in height. In most cases, we don't want to increase the width of the buttons, so it makes sense to me that this does not increase the icon size. This is also controlled upstream. My opinion is to close as-designed.
