### ISSUE TITLE
[php] Provide a formatter that also handles HTML

### ISSUE THREAD

**Issue by kitwil** [Microsoft/vscode#15813]
1 doc = many code types.
why we build too much extentions for some code type??? 
it's doesnt work for every code in 1 doucument.
we need 1 click and apply for all code formatting.

please reply,
thanks.

**Comment by jrieken** [comment]
@kitwill I am sorry, but I do not understand what your issue is. Please clarify, ideally with steps and a small sample

**Comment by kitwill** [comment]
@jrieken we need extension for set different code type auto formatting in 1 click sir. Because nowaday we use PHP formatter for set formatting for PHP and we user HTML Formatter for set formatting for HTML. What if we have HTML and PHP in 1 file what would i use? The ploblem is when i use PHP formatter for reformatting PHP code. It's make HTML code fail format to 1 line. But when i use HTML formatter it's make PHP fail format. Did you understand? 

please reply,
thanks

**Comment by aeschli** [comment]
The PHP formatter should also be able to format HTML or any other embedded language.
VSCode doesn't contain a PHP formatter, this is left to extensions to be provided.
If you use a extension for formatting, and see a bug there, please file any issues against the PHP formatter that you use.

**Comment by norFarhan** [comment]
it will be much more better for vscode to support php formatter instead of using extensions which will cause multiple keybinding for multiple language,

**Comment by DannyMexen** [comment]
+1
