### ISSUE TITLE
Investigate return to open on mouse-down 

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#15819]
We used to open a file from the explorer on mouse down until end of August when https://github.com/Microsoft/vscode/commit/2980c2fcbd32dd5f2c5ecf1fc0fd4ee9b5e1c2d2 landed.

The change was motivated to fix https://github.com/Microsoft/vscode/issues/8267 and https://github.com/Microsoft/vscode/issues/10775

I am not sure how this became a plan item, other than seeing this note (from @waderyan ?) from the Compete Wish List:

![image](https://cloud.githubusercontent.com/assets/900690/20491835/f4864f6c-b012-11e6-89a1-a256fd575dc4.png)

/cc'ing some people like @waderyan and @egamma (who asked about this in the standup) and @stevencl (who filed one of the issues) to gather more input why we should suddenly change back to the old buggy behaviour. If this is just a theory that it will make people believe Code is faster, then I would not change anything until we get proof from our users.

**Comment by waderyan** [comment]
Ping @chrisdias 

@bpasero You are correct. It is a theory based on my competitive analysis. We can work on gathering more user feedback if there is a technical hurdle to changing the behavior.

**Comment by bpasero** [comment]
@waderyan do we have any user feedback from NPS that tells us this is a problem?

**Comment by chrisdias** [comment]
@bpasero this was a suggestion to improve the snappy-ness of the experience (related to NPS feedback), we didn't know that the behavior was changed to fix the referenced bugs.  

That said, because the [change](https://github.com/Microsoft/vscode/commit/2980c2fcbd32dd5f2c5ecf1fc0fd4ee9b5e1c2d2) that changed this behavior was so small, I reverted it (locally) so that the file is opened on mouse_down. I don't see the issues reported in the two referenced bugs and it does feel much faster to me. 

Maybe i'm missing something, or perhaps there were other fixes since then that make this possible now?

**Comment by bpasero** [comment]
@chrisdias it still reproduces. see how in this case I start with one file and I want to drag a second file to the side of the first one. It is not possible, I end up with 3 files open:

![editors](https://cloud.githubusercontent.com/assets/900690/20552394/b45f7b8c-b14a-11e6-9d03-d8e82eec8f96.gif)

**Comment by chrisdias** [comment]
weird, i don't see a third file being opened!  I do see the same file being opened 2 times though, once in preview and once in the 2nd column. 

(https://cloud.githubusercontent.com/assets/1487073/20579706/27cd3392-b183-11e6-9bee-00e4b70aed50.gif)

Given what you are seeing (3 files being opened) and a lack of user data that suggests this is a problem, it is hard to argue doing a bunch of work to try to nuance the scenario to get mouse_down to work properly.  

If we both saw what I see (file being opened 2 times), I would consider still going back to mouse_down because the perceived performance is compelling to me. It just feels faster.

I'll close this, but if folks in the community would like to comment, please do so.

**Comment by bpasero** [comment]
@chrisdias I am seeing the same as you do, the file you drag opens in Group 1 and also in Group 2. What I meant is that 3 files are now opened, even though 2 are the same in Group 1 and Group 2.

Attached is a demo of the other bug:

![editors](https://cloud.githubusercontent.com/assets/900690/20587907/57e5521a-b211-11e6-8487-51507556912e.gif)

Only works with opened editors enabled, once you click to start dragging, opened editors will add the entry and push the files down so you end up dragging the file above.
