### ISSUE TITLE
Trust dialog paths are not using label service

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#158168]
Drive letter on Windows are uppsercase:

<img width="393" alt="image" src="https://user-images.githubusercontent.com/900690/184640644-c7bb04e7-813e-4020-ae4c-a453d8869060.png">

**Comment by sbatten** [comment]
@bpasero we are not using the label service for the path portion because the path needs to be editable by the user. i.e. They should be able to edit the string directly and we should be able save that into our list. In the local case, the default behavior is to use the file picker, but if you are editing a remote path that you are not connected to, you need to be able to edit the string. I consider this change but I'm a little nervous that we might get some UI representation that is not safe for editing. 

<img width="720" alt="image" src="https://user-images.githubusercontent.com/6561887/194601037-4883dc9f-56b4-45f2-9294-bd6027b95440.png">

**Comment by bpasero** [comment]
Fair, we have methods to only fix the drive letter casing, so maybe safer to just do that.

**Comment by sbatten** [comment]
I believe I solved this a part of a separate issue.

**Comment by sbatten** [comment]
Assigning to Jan for verification

**Comment by bpasero** [comment]
I still see lowercase drive letters:

<img width="613" alt="image" src="https://user-images.githubusercontent.com/900690/214570962-4f1b0646-284b-4752-a111-625e09839064.png">
