### ISSUE TITLE
Error when opening TSX file: Cannot use JSX unless '--jsx' flag is provided

### ISSUE THREAD

**Issue by fzzzt** [Microsoft/vscode#15814]
- VSCode Version: 1.7.1
- OS Version: Windows 8.1

Steps to Reproduce:

1. Open a TSX file.

This seems kind of ridiculous, given that VSC comes with TS built in. It doesn't know what to do with TSX files? It should automatically add the flag to `tsc` if it's processing a TSX file.

**Comment by zeh** [comment]
I had this intermittently over the past few days (Windows 10 though).

I _think_ I solved it by adding...

```json
"include": [
  "./src/ts/**/*"
]
```

...to `tsconfig.json`. Your .ts locations may vary.

**Comment by fzzzt** [comment]
Well I worked around it by adding `"jsx": "react"` to `tsconfig.json`, as far as I can tell, but that is missing the point.

When you open a TSX _file_ (not a _directory_), you don't have a `tsconfig.json` file.

**Comment by mjbvz** [comment]
Ok, I believe the expected behavior would be:

* If a `jsconfig.json` or `tsconfig.json` exists, do nothing. You need to add a `"jsx"` setting in the config file in that case.
* For implicit projects, either opening a file directly or opening a directory without a `*config.json`, assume "jsx": "preserve" for tooling. You would still have to pass a `"jsx"` setting to actually compile any typescript code in that case, but our tools would work better for most scenarios. If you want to opt into using `"jsx": "react"`, you would need to create a `*config.json` project file.

Does that sound correct?

**Comment by zeh** [comment]
@mjbvz In my case, the problem was there even though I _did_ have `"jsx": "react"` inside `tsconfig.json` already. It was only adding the `include` parameter that fixed it, I believe*.

(* I say "I believe" because it was really intermittent, so I'm not 100% sure what solved it. Its gone now though)

**Comment by scriptmaster** [comment]
Setting tsconfig.json jsx: "preserve" or "react" corrected vscode --jsx defect.

{
  "compilerOptions": {
    // ...
    "jsx": "preserve",                     /* Specify JSX code generation: 'preserve', 'react-native', or 'react'. */
    // ...
    }
}

Tip: `tsconfig init` gives a big list of options where you can easily spot jsx and uncomment.
