### ISSUE TITLE
Add opening & closing parens in gutter (contextual)

### ISSUE THREAD

**Issue by alqatari** [Microsoft/vscode#15821]
Feature Request 

Have been using sublime for a while and wish if you can add the opening and closing brackets visuals on the gutter as sublime do:  
------ CASE ONE 
{|    { some code and CURSER here
 |    [ some code no curser here
 |    ]
}|   }
------ CASE TWO 
 |    { some code no curser here
[|    [ some code and CURSER here
]|   ]
 |   }  

it helps a lot in knowing where you are in code!

**Comment by alexandrudima** [comment]
To keep the number of issues in our inbox at a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: we look at the number of votes the issue has received and the number of duplicate issues filed. Thank you for your time and understanding.

If you disagree and feel that this issue is crucial: we're happy to listen and to reconsider.
