### ISSUE TITLE
macOS fullscreen window restore

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#158388]
Refs: 

- [x] macOS @IanMatthewHuff
- [x] macOS @mjbvz

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23158388%0A%0A&assignees=bpasero)

---

**Synopsis:**
On macOS, Electron does not allow us to restore multiple windows in fullscreen on the same display. Doing so results in ugly issues such as https://github.com/microsoft/vscode/issues/157605 and https://github.com/microsoft/vscode/issues/150790.

**Setup:**
* configure `"window.restoreFullscreen": true`
* prepare to have a second monitor ready

**Testing**
* open a window, make it fullscreen and ensure after restart the window appears fullscreen on the display you left it
* open multiple windows and make multiple windows fullscreen on the same display and verify that only the last active window restores fullscreen while the others restore but not as fullscreen
* open 1 window fullscreen on the one display and 1 window fullscreen on the other display and verify both appears as they were after restart
* briefly test that normal non-fullscreen windows restore as they are left, e.g. open 2 and size them so that you can remember on both displays

**Comment by IanMatthewHuff** [comment]
- [ ] open a window, make it fullscreen and ensure after restart the window appears fullscreen on the display you left it
- [ ] open multiple windows and make multiple windows fullscreen on the same display and verify that only the last active window restores fullscreen while the others restore but not as fullscreen
- [ ] open 1 window fullscreen on the one display and 1 window fullscreen on the other display and verify both appears as they were after restart
- [ ] briefly test that normal non-fullscreen windows restore as they are left, e.g. open 2 and size them so that you can remember on both displays
