### ISSUE TITLE
Improve drop feedback cursor when dragging from outside Code into Code

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode#15846]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:06:37.428Z)
- OS Version: Windows_NT ia32 10.0.14931

Dragging it into the editor should be an "Open" action, not a "Move" action. 
![image](https://cloud.githubusercontent.com/assets/762848/20507148/d29704be-b00d-11e6-9e97-c1dd9671e1b4.png)

Would expect it to be consistent w/ dragging from vscode file explorer, as shown below
![image](https://cloud.githubusercontent.com/assets/762848/20507209/1f4b611a-b00e-11e6-8faf-b1d60427a930.png)

**Comment by bpasero** [comment]
Really limited as to what HTML provides here. I can only set drop effects according to the HTML spec (https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer/dropEffect) and the one you see in the second picture is for drag and drop within the application.

It might be possible to set the same drag image even when starting outside, but I doubt it because it seems you need to set it on drag start (which obviously happens outside).

Looking at other apps, they seem to set the COPY drop feedback though, not the move.

**Comment by bpasero** [comment]
We are using the copy feedback now, closing.
