### ISSUE TITLE
Code-insiders can't be used multi user in linux

### ISSUE THREAD

**Issue by faqati** [microsoft/vscode#158647]
Does this issue occur when all extensions are disabled?: Yes/No
No

- VS Code Version: 
```
1.71.0-insider
28f604dec81b609dd7e69362585f7a99d4c48f88
x64
```
- OS Version:
```
Distributor ID:	Ubuntu
Description:	Linux Lite 5.6
Release:	20.04
Codename:	focal
```

Steps to Reproduce:

1. Install vscode-insiders under user A
2. create user B and run `code-insiders .` 

You'll get the following error:
![image](https://user-images.githubusercontent.com/107083836/185733473-c1cf4bd1-cbe9-4afc-bdc0-3b76ec88fa7a.png)

**Comment by bpasero** [comment]
fyi @joaomoreno since this is about our socket to control first vs second launch

@faqati to me this looks like you are not launching with a different user in your second launch but rather try to launch over the same user with different permissions. I would have expected the second user to get a different user directory that is not `/run/user/1000`

**Comment by joaomoreno** [comment]
Both users seem to be sharing the same `XDG_RUNTIME_DIR`. This is an OS misconfiguration that needs to be fixed on the user's system.
