### ISSUE TITLE
Doesn't autoupdate there is no option for manual update in Help

### ISSUE THREAD

**Issue by gruber123** [microsoft/vscode#158621]
Type: <b>Bug</b>

After version 1.70.1 vs code doesn't autoupdate there is no option for manual update in Help.
windows 7

VS Code version: Code 1.70.2 (e4503b30fc78200f846c62cf8091b76ff5547662, 2022-08-16T05:35:13.448Z)
OS version: Windows_NT x64 6.1.7601
Modes:

**Comment by gjsjohnmurray** [comment]
I'm guessing you either:

- installed the User Installer (which is the default Window download) but installed it with admin privileges (either explicitly, or because you have turned of Windows UAC protections).

or
- installed the User Installer unelevated (i.e. running it normally) but are now launching VS Code as administrator.

Either way, if you want to run VS Code as an administrator, use the System Installer. You should uninstall the previous installation first. You won't lose any data or settings unless you have stored your own projects within the install folder (in which case you'd lose them on an ordinary update anyway).

Also be aware that the next release (1.71) is reported not to run on Windows 7, which hasn't a supported platform for VS Code for several versions now.

**Comment by joaomoreno** [comment]
Given you installed as a user, updates will be disabled when running as Administrator.
