### ISSUE TITLE
Quick pick buttons are 1px taller than the input box

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#158606]
Device pixel ratio = 1, zoom level = 0 🕵️ 

![image](https://user-images.githubusercontent.com/2193314/185657785-6c5dd1b8-965a-46e2-81d6-ad633895d239.png)

Version: 1.71.0-insider (user setup)
Commit: 28f604dec81b609dd7e69362585f7a99d4c48f88
Date: 2022-08-19T05:17:14.894Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22000
Sandboxed: Yes

**Comment by weartist** [comment]
Can I work for this？

**Comment by TylerLeonhardt** [comment]
@weartist go for it

**Comment by weartist** [comment]
hi @TylerLeonhardt , this problem seems to be due to the fact that the button is set to 27.5 height, but the search input is 25 height, I also found in another function that the button will be a little bit down because of the height.

<img width="642" alt="image" src="https://user-images.githubusercontent.com/17105034/186050363-2639c7a4-09e4-4264-96a7-ce8b3aa73f4e.png">

<img width="367" alt="image" src="https://user-images.githubusercontent.com/17105034/186050428-be4b8b9e-b5cc-4193-a9f3-e322b4a30e17.png">


But according to the screenshot of @Tyriar , the difference is not as big as between 25 and 27.5, I didn't find the exact value of the input control to set the height, maybe it is set dynamically?

And I found a place where the height of the input might be updated, so I feel like I need to refresh the height of the button here too：
https://github.com/microsoft/vscode/blob/f51200c983f90a1ed46be19c65b9ca355d8a0b0f/src/vs/base/browser/ui/inputbox/inputBox.ts#L600-L602

**Comment by Tyriar** [comment]
The decimal height seems suspicious. The pixels in my screenshot are actually 28, so the 27.5 is getting rounded up.

**Comment by weartist** [comment]
> 十进制高度似乎很可疑。我截图中的像素实际上是28，所以27.5被四舍五入了。

I'll be checking out the code here over the next few days, and it looks like this component is used in several places

**Comment by weartist** [comment]
> The decimal height seems suspicious. The pixels in my screenshot are actually 28, so the 27.5 is getting rounded up.


I'll be checking out the code here over the next few days, and it looks like this component is used in several places

**Comment by TylerLeonhardt** [comment]
Introduced here:
https://github.com/microsoft/vscode/commit/a9ed4e9b0a42559b41e96ca894d1a5b9b47da33b

I think we can start with the tactical fix of just lowering that height to 26 or 27... whatever looks correct. I don't expect the input of the quick pick to change at all especially since it doesn't support multi-line.

@weartist wanna give it a go?

**Comment by weartist** [comment]
> Introduced here: [a9ed4e9](https://github.com/microsoft/vscode/commit/a9ed4e9b0a42559b41e96ca894d1a5b9b47da33b)
> 
> I think we can start with the tactical fix of just lowering that height to 26 or 27... whatever looks correct. I don't expect the input of the quick pick to change at all especially since it doesn't support multi-line.
> 
> @weartist wanna give it a go?

@TylerLeonhardt  I experimented with the result that setting it to 25 is appropriate, omewhat surprisingly, I initially also feel that maybe 26, 27 is about the same


This is with a setting of 26:
<img width="610" alt="image" src="https://user-images.githubusercontent.com/17105034/186920880-223fc93f-6279-4952-a179-80e5a9ca4e92.png">

The height of the input box is 26, but the height of the button, if set to 26, will look slightly more：
<img width="524" alt="image" src="https://user-images.githubusercontent.com/17105034/186921304-6dafd6bb-e05e-40c2-9d11-7027e992b122.png">


This is with a setting of 25:
<img width="630" alt="image" src="https://user-images.githubusercontent.com/17105034/186921571-618e79dd-f613-4b36-8207-4742e52471c3.png">
