### ISSUE TITLE
Avoid `gutterIconPath` to be re-rendered on _every_ wrapped line when `ThemableDecorationRenderOptions.isWholeLine = true`

### ISSUE THREAD

**Issue by alefragnani** [microsoft/vscode#158837]
I would like the `gutterIconPath` to be rendered only in the _first line_, no matter if `isWholeLine` is `true` or `false`. This is specially useful if the decoration is created in fact, mostly to have an icon in the gutter, not necessarily the line content, as I do in my Bookmarks extension.

## Current behavior when `isWholeLine = false`

1. Open the `decorator-sample` in `vscode-extensions-sample` repository
2. Add some `.svg` file, to be rendered in the gutter (you can use https://github.com/alefragnani/vscode-bookmarks/blob/3251fb0a00755121fe9e316e60cb14a50d9065ff/images/bookmark.svg)
3. Add `gutterIconPath: context.asAbsolutePath('/path-to-svg-file.svg'),` in the `smallNumberDecorationType` decorator creation
4. Run the sample
5. Follow the sample template to see the decorator, creating a line long enough to be wrapped
6. Turn wrap lines on
7. You will notice the icon in the gutter, in the same line as the _small number_ decoration 

![Screen Shot 2022-08-22 at 20 28 41](https://user-images.githubusercontent.com/3781424/186037947-ee676a76-1735-4bdb-9441-279afe9454a0.png)

## Current behavior when `isWholeLine = true`

1. Add `isWholeLine: true` in the same `smallNumberDecorationType` decorator creation
2. Run the sample again, with the same long line to be wrapped
3. You will notice the icon in the gutter will be displayed in each wrapped line, not only in the line where the _small number_ is, as the steps above.4. 

![Screen Shot 2022-08-22 at 20 29 05](https://user-images.githubusercontent.com/3781424/186037970-3895acc7-b79c-45bc-a3ce-02652eb58b01.png)

I understand the `isWholeLine` defines the decorator will be in the entire line, and the wrapped line is, in fact, the _whole line_. 

## Mixed behavior when `isWholeLine = false`

I'm not entirely sure this is the expected behavior, when when `isWholeLine` is off, but the `gutterIconPath` is rendered on each line that "contains" a _small number_ .

![Screen Shot 2022-08-22 at 20 30 50](https://user-images.githubusercontent.com/3781424/186037984-1b7cc875-43bb-41e6-b74c-8d78c0ebfeb6.png)

Thank you

**Comment by alexdima** [comment]
This is maybe not very intuitive, but let me try to clarify what's the thinking behind it:
* When a decoration sets `isWholeLine` to false (the default), it means it "affects" a specific character range. A range can contain only characters on a single line like in the above examples (e.g. `1,2-1,4`), but it could also be a range which spans multiple lines (e.g. `1,2-2,4`). But in any case, the idea is that the decoration can affect a specific range of characters in one or multiple lines.
  * When a line is wrapped, the decoration is present only on the wrapped lines which contain the characters in the range it targets.
* However, when a decoration sets `isWholeLine` to true, it means it "affects" entire lines. Such a decoration using the range `1,2-1,4` is effectively at render time a decoration on lines `1-1`. The character part of the range no longer plays a role. Similarly, a decoration using the range `1,2-2,4` effectively means a decoration on lines `1-2`.
  * When a line is wrapped, an `isWholeLine` decoration is present on all wrapped lines, because it is not bound to a specific character range.

So to explain the screenshots:
---
> ![Screen Shot 2022-08-22 at 20 28 41](https://user-images.githubusercontent.com/3781424/186037947-ee676a76-1735-4bdb-9441-279afe9454a0.png)

Here we have a single decoration that contains a single character and uses `isWholeLine: false`. This decoration is only present on the first line in the wrapped lines because only the first line contains the `3` this decoration targets.

---
> ![Screen Shot 2022-08-22 at 20 29 05](https://user-images.githubusercontent.com/3781424/186037970-3895acc7-b79c-45bc-a3ce-02652eb58b01.png)

Here we have a single decoration that uses `isWholeLine: true`. The decoration is present on all wrapped lines.

---
> ![Screen Shot 2022-08-22 at 20 30 50](https://user-images.githubusercontent.com/3781424/186037984-1b7cc875-43bb-41e6-b74c-8d78c0ebfeb6.png)

Here we have two decorations that use `isWholeLine: false`. The first decoration is present on the wrapped line which contains the first `3`, the second decoration is present on the wrapped line which contains the second `3`.

---

I hope that explains how things are working behind the scenes. Please let me know if you have specific suggestions.

**Comment by alefragnani** [comment]
Hi @alexdima ,

Thanks for the detailed explanation. It indeed explains how the things works behind the scenes, and in fact, it almost confirms my suspicions.

Based on your descriptions, the decorator seems to be working _as designed_, and I totally understand. But, based on that, I wonder what suggestions do you have for extension authors, if extensions need to **mimic breakpoints behavior**, which does not suffer of such issues.

I guess breakpoints does not follow the same rules, because it _probably_ doesn't use the Decorator API, as it supports mouse clicks, alt-mouse event, and so on. Is there any chance to update the Decorator API with things we see in Breakpoints? I remember something about the Test API also supporting clicks in the gutter, but it's been a long time I don't look that area.

Thanks for you help

**Comment by alefragnani** [comment]
`OnClick` event on Gutter (https://github.com/microsoft/vscode/issues/5455 ) is a fairly requested feature. But unfortunately, not planned yet. 

I wonder if this change in the Decorator API would require to use/interact with the same internal API used by the Testing API.

**Comment by alexdima** [comment]
>  But, based on that, I wonder what suggestions do you have for extension authors, if extensions need to mimic breakpoints behavior, which does not suffer of such issues.

Breakpoints are also built with decorations. They use `wholeLine: false`. There can be multiple breakpoints appearing in the glyph area for the same logical line in the case of column breakpoints. Here there are 2 column breakpoints on line 4:

<img width="277" alt="image" src="https://user-images.githubusercontent.com/5047891/195450309-b42cfaa8-1f9b-431e-89fb-26b2bb14004e.png">

If you'd like to always have at most one glyph margin icon per logical line, you could use 2 different decoration types, one which renders just the glyph margin icon, and another one which renders the highlight on the characters. Then, when computing decorations you would always add the one with the glyph margin at character 0. This will make it that even if there are multiple bookmarks on the same line, there will be a single glyph margin icon, at the logical line start.

> I guess breakpoints does not follow the same rules, because it probably doesn't use the Decorator API, as it supports mouse clicks, alt-mouse event, and so on. Is there any chance to update the Decorator API with things we see in Breakpoints?

The internal decorations API does not offer an onclick handler either. The debugging code runs on the same thread as the editor and can use internal editor APIs to listen to mouse move or mouse down events. It then inspects the target of those events and decides if something should happen or not. I realise that this isn't very helpful, IMHO the most difficult part here is to design a reasonable vscode API, since decorations are currently "set and forget", and having a click callback can be done either by having a single handler per decoration type, which implies some sort of object model, since then it would need to get as an argument the clicked decoration object (which doesn't exist as a concept today), or otherwise we could have multiple handlers, one per each decoration instance, but that would result in massive performance costs for those that create thousands of decorations... We can continue using #5455 to track this, I'm sorry that I don't have better answers. But I'm happy to help if you'd like to give it a try via a PR.

**Comment by alefragnani** [comment]
> If you'd like to always have at most one glyph margin icon per logical line, you could use 2 different decoration types, one which renders just the glyph margin icon, and another one which renders the highlight on the characters.

That's a fair solution. I'll give it a try. Thanks!

> We can continue using #5455 to track this, I'm sorry that I don't have better answers. But I'm happy to help if you'd like to give it a try via a PR.

No need to be sorry. Based on your description about the internals, it is totally reasonable that no API is available yet. Sure, we would like to have that available to be used on our extensions, but not with some performance cost attached. The idea needs to be fine tuned to deliver great result for both extensions and VS Code itself.

Thanks for your help

**Comment by alefragnani** [comment]
Just to let you know, using the _2 different decoration types_ approach works pretty well, and I'll be embracing it in the next release of the Bookmarks extension. 

Thank you!
