### ISSUE TITLE
Test: Experimental git bash shell integration

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#158829]
Refs: #143769

- [x] windows @aiday-mar

Complexity: 3

Authors: @meganrogge @Tyriar

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23158829%0A%0A&assignees=Tyriar,meganrogge)

---

Using the instructions to setup [here](https://github.com/microsoft/vscode-docs/pull/5559/files), test some of the functionality of shell integration in git bash on Windows. See https://code.visualstudio.com/docs/terminal/shell-integration#_features for a list of features.

It's a known issue that the prompt sometimes jumps around when a command is run (typically to a better position), this is due to a limitation in conpty shipped with Windows.

**Comment by aiday-mar** [comment]
Cool! I discovered a new feature of VSCode.

**Comment by IllusionMH** [comment]
Are there any requirements for minimum Windows version?
Because for
Version: 1.71.0-insider (user setup)
Commit: bd6107301dc9a6200bd8d4f64a9b198438b3f1d6
Date: 2022-08-23T05:17:01.943Z
OS: Windows_NT x64 10.0.19044
Sandboxed: Yes

I only see default decorator (gray circle) that always moves, but not success/error (left part of the screenshot) while WSL  machine shows all kinds of decorations.

![image](https://user-images.githubusercontent.com/1312662/186141421-614a68cd-7b3f-4166-9edf-8248402499c8.png)

Tried on other device with Win11 Insiders Dev Channel - and it works fine (except position of gray circle that jumps for default multiline `$PS1`)

**Comment by Tyriar** [comment]
@IllusionMH we depend on conpty that's shipped in Windows so the behavior will improve over time, Windows 11 dev would be the ideal version to test against as we typically can't do much about conpty bugs (and will hopefully move to shipping it with vscode eventually).
