### ISSUE TITLE
Define and apply guidance about quick pick titles and placeholders

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#158895]
Testing #158798 but actually noticeable across our whole UI. It is sad to see a mix of quick pick with and without title and placeholder. Worst, sometimes the title part is used like a placeholder and vice versa. This seems to be based off developer preference and not rules. We should define

* what to use as placeholder text and if it ever should be empty
* when and what for to use the title

Command picker

<img width="703" alt="Screenshot 2022-08-23 at 15 08 47" src="https://user-images.githubusercontent.com/1794099/186166095-af9481e4-cb96-48bf-b502-51e0423e0020.png">

ssh connection 

<img width="663" alt="Screenshot 2022-08-23 at 15 08 31" src="https://user-images.githubusercontent.com/1794099/186166047-4ba8b342-572f-4596-8bba-bab56166e1b8.png">

Continue on...

<img width="917" alt="Screenshot 2022-08-23 at 15 06 28" src="https://user-images.githubusercontent.com/1794099/186165644-6c350f0a-8de1-422f-af75-e4c2564f80c1.png">

**Comment by roblourens** [comment]
I've always liked the minimalism of the placeholder text but also sometimes get annoyed that it disappears while typing. But if something that I use 1000 times a day like the quickopen suddenly had a full title bar, that would be annoying and too "heavy" even though it might benefit new users.

Here and in the Continue On example, it seems like we are using the title as a dialog title and the placeholder as an extra detail.
<img width="666" alt="image" src="https://user-images.githubusercontent.com/323878/186203017-1424275d-5693-4524-bdb7-b8cefaa08456.png">

If we want to consider new designs at all, what if we had a right-aligned placeholder that didn't disappear until the text you are typing reached it?

This also intersects with the conversation about the quick access experience because we talked about a placeholder that will change based on the mode you are in (quickopen, `>`, `debug `, etc)

**Comment by jrieken** [comment]
IMO shortcomings or dislikes of the placeholder text aren't a reason to use the title, but are a reason to improve the placeholder UI. Tho, the placeholder should be mostly optional or encouraging and not be needed to orient myself. The title IMO should be used for context about what you are doing, esp in a multi QP flow. Maybe what's missing is the ability to show some more permanent hint - something that can explain what we are after, like the message of a modal dialog

**Comment by daviddossett** [comment]
Will work on guidance here in the next iteration as a continuation of the Command Center/Quick Pick work in #155458, #158638, and #158064

**Comment by bpasero** [comment]
(I refer to "**quick open**" as the thing that drives commands, file search, etc. pick via prefixes and "**quick pick**" as the widget and other usages)

The reasons for quick open to not use title are quite easy, at the time we added quick open, there was no support for title at all.

I think we have added title area to the quick pick when we started to turn them more into dialog-like, wizard style widgets (@chrmarti ?) that extensions were able to use via API to provide more context of the current step you are in.

My personal feeling is that adding a heavy title to the quick open is not desired, especially because once you type one of the quick open handlers such as `@` you change context and the title would either have to change or be removed entirely if it does not apply anymore.

**Comment by daviddossett** [comment]
My first thoughts:
- ❌ **Don't** use titles on the core keyboard-driven command center modes (e.g. go to file, command palette, @, debug, etc. etc.). These are more akin to the now-ubiquitous command palettes we see everywhere (GH, Vercel, Teams, etc.) and don’t need an explicit title.
- ✅ **Do** use titles on just about everything else since they are mostly functioning as dialogs asking for input or selection. Many of these are obvious, but many more rely on placeholder text to describe their purpose. They are also often opened from far away UI instead of a keybinding.
- Adjust placeholder text across the board to give hints as to the **purpose of the text input** (e.g. filtering, entering a url) and not to describe the purpose of the quick pick.
- Update title styling to make a smoother transition between title and no title

I totally get the concern w/ added visual weight if we are increasing the usage of titles. However, there are countless examples of quick picks without titles that are leaning on using placeholder text for a title (an anti-pattern IMO) which makes them hard to understand at a glance.

## Demo

https://user-images.githubusercontent.com/25163139/198360609-37fda365-c7fa-4f9b-9c54-b10e9dd328eb.mp4

## Prior art

I liked this example from Figma which shows three UI surfaces with different purposes/weight:
- Quick actions (like our command palette/center)
- Lightweight dialog-like UI to capture input (like many of our quick picks e.g. creating a settings profile)
- Full blocking dialog w/ destructive action (like our existing dialogs

https://user-images.githubusercontent.com/25163139/198362936-e1548392-2a2b-4223-8840-e0b32e130eae.mp4

**Comment by jrieken** [comment]
> Do use titles on just about everything else since they are mostly functioning as dialogs asking for input or selection. 

Unsure about that. To me it feels like repetition of the action that I just have clicked, like "Change Icon Theme" and then the title repeats just that. I would have not expected anything else TBH. There is also the confusion that these commands can be triggered from the command palette, meaning I open the command palette (no title), select "Change Icon Theme", and now see a title (which causes a visual shift)

**Comment by daviddossett** [comment]
> To me it feels like repetition of the action that I just have clicked, like "Change Icon Theme" and then the title repeats just that. I would have not expected anything else TBH

I hear you, but isn't that how a dialog or modal would work? To me we are using a CLI-like interface in a dialog-like way. It would be like macOS using Spotlight to capture input instead of a dialog. The two feel fundamentally different. Today we burden the placeholder with providing the title which _can_ work but often doesn't. 

> There is also the confusion that these commands can be triggered from the command palette, meaning I open the command palette (no title), select "Change Icon Theme", and now see a title (which causes a visual shift)

That happens today with many quick picks. E.g. `Open Remote Repository` -> `<quick pick with title>`. To me it's even more confusing to have this case-by-case logic applied to when we use titles vs. when we don't. That's why I'm trying to arrive at something much more deterministic. 

I'm open to other ideas. But I think I'd rather solve for the UI transition challenge rather than have a really inconsistent experience across various quick picks.

**Comment by daviddossett** [comment]
After hearing feedback here, standup, and the UX sync, I think I've arrived at defaulting to _not_ using titles unless there are good reasons to do so vs. the other way around. I have a few PRs going to reduce titles where they aren't needed and to polish or add missing placeholders across various core and extension-owned quick picks.

Boiling it down, this is where the conversations left off:

- ✅ Do use a title for multi-step quick picks
- ✅ Do use a title for quick picks w/o an input (e.g. `Customize Layout`)
- ✅ Do use a title for quick picks asking for text input (especially when the placeholder is giving a more detailed hint or example)
- ✅ Do use a title for quick picks featuring global buttons (e.g. `Refresh` on the python interpreter quick pick)
- ❌ Don't use a title for the command palette (search, commands, debug, etc.)
- ❌ Don't use a title when the placeholder can describe the purpose on its own (e.g. Select Color Theme)
- ❌ Don't use inputs without a placeholder

**Comment by bpasero** [comment]
> Don't use a title when the placeholder can describe the purpose on its own 

💯
