### ISSUE TITLE
Clicking on "N conflicts remaining" should navigate through all the conflicts

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#159027]
Currently we have the "N Conflict(s) Remaining" decoration on the right.
Whenever I see that as a user I want to understand what is that conflict that I am missing. So clicking on this should navigate me through all the conflicts (same as "Go To Next Conflict Action").

In case we do that, make sure to use the cursor hand pointer style.

![Screenshot 2022-08-24 at 11 01 32](https://user-images.githubusercontent.com/1926584/186377300-ebe033e9-a8af-464f-8284-682e359cbf26.png)

fyi @daviddossett

**Comment by hediet** [comment]
@jrieken?

I also had this idea that clicking on it should go to either the first or the next conflict (probably the next).

**Comment by jrieken** [comment]
I think that's weird because it's just a label, not a link nor a button and usually we cannot click text in our UI

**Comment by isidorn** [comment]
It could act like a link and we could make it look more like a link.
Though whatever we decide I think we should not do it this milestone :) It is fine if we do it as an improvement later.

**Comment by daviddossett** [comment]
I agree with this general idea and have it on my list as one obvious improvement we could make. However, we also feature this capability in the toolbar via the up/down arrows.

<img width="250" alt="CleanShot 2022-08-24 at 15 08 39@2x" src="https://user-images.githubusercontent.com/25163139/186532339-5f7eaa13-4718-4524-ba98-8370ed11503e.png">

We could consider removing the toolbar items and instead providing these buttons local to that Result toolbar since we have precedent with the "..." buttons in the Incoming/Current toolbars. Something like:

<img width="400" alt="CleanShot 2022-08-24 at 15 11 17@2x" src="https://user-images.githubusercontent.com/25163139/186532655-ce0a640f-2067-4177-817c-a0ffd67724fb.png">

The original design had the "conflicts remaining" as a text element placed near the pane title. I think having it right aligned makes it harder to locate on larger screens. So the location of the conflict counter is also something we could update at the same time.

**Comment by hediet** [comment]
Verification steps:
![Uploading Code_-_OSS_lOvFiTTE3J.gif…]()

**Comment by isidorn** [comment]
Great. Thanks for implementing this. Will verify.
Closing as this seems to have been done.
