### ISSUE TITLE
Seeing double dialog

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#159046]
Testing #158798

* use safari
* select continue on > desktop
* you see a safari-native modal and also one from us with "try again"

https://user-images.githubusercontent.com/1794099/186408113-fa3e1857-6231-4fa7-8a3a-d4b22945c700.mov

**Comment by joyceerhl** [comment]
We show our own dialog because in the case where the user does not have VS Code installed locally (which we cannot determine from the browser), opening the protocol URL will fail, so we need to provide the user with some fallback. Unfortunately we cannot conditionally show this dialog only when opening the protocol URL fails because we also cannot determine this from the browser.

This is the same behavior that other desktop apps with a browser component have e.g. Microsoft Word Online > Open in Desktop App, so I'm not sure we can do much more here.
