### ISSUE TITLE
Let's remove "Do you want to close with conflicts" dialog?

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#159024]
1. Open a conflict file in 3 way merge
2. Close the 3 way merge editor

Notice dialog
![Screenshot 2022-08-24 at 10 49 10](https://user-images.githubusercontent.com/1926584/186374656-b7e5c8b7-4568-4827-a72b-15568bcd5e9f.png)

I do not think we have a need for this dialog any more since we are no longer removing the conflict markers. Thus the user can just close this dialog, there is no data loss?

Similarly when the user closes the old editor with conflict markers we do not prompt.

fyi @daviddossett

**Comment by hediet** [comment]
I don't have an opinion about this.

**Comment by jrieken** [comment]
I would leave it for clarity it creates, however I am open a "don't ask again" option

**Comment by isidorn** [comment]
"Don't ask again" works for me, especially since I just noticed that when some conflicts get resolved the dialog is "smarter".

Would don't ask again write in storage or a setting? I am fine going loco and writing to storage (so users can not revert).
Though if all the other "don't ask again" write in settings then I guess I am fine with that.

**Comment by daviddossett** [comment]
+1 for "Don't ask again"

**Comment by bpasero** [comment]
Fyi there is a very practical use case for the dialog: if you run with `--wait` and use VSCode as Git merge editor, you may actually want to resolve the conflicts before closing the editor because Git somewhat expects you to do so.

On top of that, given https://github.com/microsoft/vscode/issues/157961, we currently cannot pass back an exit code to Git, so it helps showing a dialog to avoid returning back to Git with merge conflicts still in the file.

Besides, we show a similar dialog when you try to stage a file that has merge conflicts from the SCM view:

![image](https://user-images.githubusercontent.com/900690/186612014-f343215e-7a07-4960-83ff-f10b6794ddc9.png)

**Comment by isidorn** [comment]
@bpasero thanks for providing more info, I missed that case.
Though I think it does not conflict with our idea to add "Don't Ask Again".

**Comment by hediet** [comment]
Can we tell the merge editor if it was opened in a modal context (like with --wait)?

**Comment by bpasero** [comment]
Currently not, an editor has no knowledge that it is being utilised for `--wait`. There is plumbing around the editor where we observe the opened editor for being closed and then delete the wait marker file.

Can we get more user feedback on this before jumping onto a conclusion?

**Comment by jrieken** [comment]
Verify that

* there is an option to not be asked again
* there is a "Reset Choice for Close with Conflicts" commands in the F1 list

<img width="1405" alt="Screenshot 2022-11-25 at 15 24 27" src="https://user-images.githubusercontent.com/1794099/204005007-04675d62-d180-4ac1-a4ea-1757c9a7c83c.png">

**Comment by isidorn** [comment]
Adding verified since this works as expected.
Noticed one minor "glitch".

1. Check "Don't ask again"
2. Click Cancel

The "Don't ask again" choice will be preserved. It should probably be only preserved if I click on "Close with Conflicts".
I am not supper passionate about this, but let me know if you would like me to file an issue @jrieken
