### ISSUE TITLE
`windowImpl.profile` has side effects

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#159172]
Not a big fan of having a `getOrSetProfileForWorkspace` in the getter for `profile`:

https://github.com/microsoft/vscode/blob/57945a1416f02a6f74a7d7bf3be38454f2722b95/src/vs/platform/windows/electron-main/windowImpl.ts#L126

**Comment by sandy081** [comment]
New workspaces will not have profiles associated when they are opened for the first time. So `getProfileForWorkspace` returns `undefined` for them. All callers of `getOrSetProfileForWorkspace` have to associate a profile to the workspace in such a case. It can be a default profile or the profile of current window. So `windowImpl.profile` should set a profile for its workspace if there is no profile associated. I can rename the method to `getProfileForWorkspace` but it does not express this behaviour and hence I named it `getOrSetProfileForWorkspace` that will get the profile for the workspace if associated otherwise associate the passed profile to the workspace and returns it.

**Comment by sandy081** [comment]
@bpasero I am closing this in favour of above comment. Please let me know if you have other suggestions.

**Comment by bpasero** [comment]
I guess what I had expected is that everytime `config` changes, the profile is just set and then `get profile()` returns that or `undefined`.

**Comment by sandy081** [comment]
Yeah that would be the right way, but I see that config is getting updated at two different places based on whether the window was already loaded or not

https://github.com/microsoft/vscode/blob/a4dd83d69b931aa27030111eebc853b04ef716f0/src/vs/platform/windows/electron-main/windowImpl.ts#L862

https://github.com/microsoft/vscode/blob/a4dd83d69b931aa27030111eebc853b04ef716f0/src/vs/platform/windows/electron-main/windowImpl.ts#L546

**Comment by sandy081** [comment]
Also note that profile from the config can be outdated if the user changes the profile after opening the window.
