### ISSUE TITLE
If source control pane is small, you might not realize you're pushing

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#159243]
When it's small:

![image](https://user-images.githubusercontent.com/2644648/186786805-bd04e384-c7e7-4b3a-8de3-8d7f1d52475a.png)

When it's bigger: 
![image](https://user-images.githubusercontent.com/2644648/186786823-47e20b7e-74a6-4f19-ba90-17697f8daa5f.png)

I didn't realize this was also gonna sync since the `& Sync` part was hidden.

**Comment by lszomoru** [comment]
Thanks for the feedback. This is currently by design. We made a decision not to wrap the action button and that is why commands provide both a title and a description. The description (ex: Commit & Sync) is shown when there is enough space to render it, while the title (ex: Commit) is shown there there is not enough space. All commands have "Commit" as the title, and we use the icons (ex: sync) to convey additional information.  Happy to tweak things if we believe there is a better way to do this.

//cc @misolori, @daviddossett

**Comment by daviddossett** [comment]
We could also consider dropping the icon in favor of the text at these smallest widths. However we would lose the nice icon animation.

**Comment by misolori** [comment]
Is there a reason why there isn't an ellipsis in the text? That should be `Commit...` so it gives an indication that it's cut off

**Comment by lszomoru** [comment]
The current implementation was done based on feedback in the UX channel. I am happy for us to adopt a pattern across all buttons where we always have the labels on one line and use an ellipsis (`...`) in case there is not enough room to display the label.

**Comment by daviddossett** [comment]
Where did the proposal to drop the label altogether end up? E.g.

```
() Sync Changes 10 v 5 ^
() 10 v 5 ^
```

**Comment by lszomoru** [comment]
> Where did the proposal to drop the label altogether end up?

That is something that has been implemented for the "Sync Changes" button as that one is quite complex with multiple icons and text segments. For that particular button it does make sense to drop the label altogether when there is not enough room. 

As I said, I do think that in case of the dropdown button we adopt the pattern of have one single label and then using text overflow (`...`) in case there is not enough room. Here is a prototype of how that would look like. @daviddossett, should we go ahead with this?

<img width="197" alt="image" src="https://user-images.githubusercontent.com/3372902/189898960-5f58c400-4546-42fd-8ae6-4aa07e7cea32.png">
