### ISSUE TITLE
Toggling word wrap on markdown preview does nothing

### ISSUE THREAD

**Issue by erhhung** [Microsoft/vscode#15921]
- VSCode Version: 1.7.1
- OS Version: macOS 10.12.1

Steps to Reproduce:

I have a markdown file with a really long command (curl output piped to a long `jq` filter, but could be anything) within a triple back-ticked code block. I can press Option-Z (or select from menu) in the editor to toggle word wrap like any text file. However, in markdown preview, toggling word wrap does nothing--I always have to scroll that single line to view all content.

I understand that Github still does not implement this behavior by default but there has been
[an old issue](https://github.com/github/markup/issues/168) tracking it, and while markdown rendering behavior is up to individual applications, it would be nice if VS Code could match word wrap toggle modes in both editing and preview.

**Comment by rolodato** [comment]
This happens to me with long paragraphs as well, not just long lines inside code blocks. That seems like a bug though, since the Markdown preview is not wrapping long lines correctly.

**Comment by mjbvz** [comment]
@rolodato Can you please provide some example md that shows this for paragraphs? 

The non-wrapping behavior for code blocks and inline code is currently by design, but I think we should improve this. Until this is fixed, you can [use custom css in the markdown preview](https://code.visualstudio.com/Docs/languages/markdown#_using-your-own-css) to add a `white-space`, `word-wrap`, or `word-break` properties to get better wrapping.

**Comment by rolodato** [comment]
@mjbvz Oddly enough I can't reproduce this anymore on 1.8.0. Markdown preview is showing wrapped lines correctly, and the Markdown editor lets me toggle between wrap on/off as expected.

**Comment by Dominik-K** [comment]
@mjbvz Word wrap is not working again. I think it's because of the [word wrap settings redesign](https://code.visualstudio.com/updates/v1_10#_word-wrap-settings-redesign) in 1.10.

**Comment by mjbvz** [comment]
@Dominik-K I've opened https://github.com/Microsoft/vscode/issues/25357 to track this
