### ISSUE TITLE
Merge conflict line is larger than a normal line

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#159250]
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/900690/186823874-94ad0af5-2e2c-46c3-948d-3aeeccd37e93.png">

**Comment by hediet** [comment]
This is on purpose (FYI @jrieken).

Do you use the horizontal column layout?

**Comment by bpasero** [comment]
Yes 👍

**Comment by daviddossett** [comment]
Will do some UX explorations this upcoming iteration to see how we can make this more obvious.

**Comment by hediet** [comment]
@daviddossett we can also do some brainstorming together!

**Comment by daviddossett** [comment]
Of course! I'll reach out at the start of the next iteration unless I somehow can get a head start this week 👍

**Comment by daviddossett** [comment]
@hediet why show this indicator in the first place? Wouldn't it make more sense to just highlight the lines as they appear in the common ancestor to indicate that a conflict is still present. I know I'm a broken record bringing in VS Win examples, but it was intentional to follow their design as close as possible—unless there are good reasons to deviate.

I've felt that adding the marker and removing the code feels strange. Note how line 15 appears in this example:

![vs-win](https://user-images.githubusercontent.com/25163139/189025334-aa0fb44f-83ef-484b-bd5d-e7e4beac2b41.png)

**Comment by hediet** [comment]
@daviddosset This is exactly what we did in the previous iteration - with the cost to make the file dirty on open.

We can revisit that decision.
I also figured out how we can ask git to recompute the conflict markers, so we can check if the user made any edits to it prior to overwriting the file.

**Comment by hediet** [comment]
Since we don't show conflict markers anymore in the merge editor, this is irrelevant now.
