### ISSUE TITLE
Synchronize changes failed because the remote branch can not be fetched.

### ISSUE THREAD

**Issue by zuoez02** [Microsoft/vscode#15935]
- VSCode Version: 1.7.2
- OS Version: Ubuntu 14.04.3 LTS, Trusty Tahr
- Git Version: 2.10.1

Steps to Reproduce:

1. Push a new branch to remote successfully
2. Delete the remote branch
3. Edit something local and commit it.
4. Click sync button.
5. VSCode alert error "There was an issue running a git operation. Please review the output or use a console to check the state of your repository."

In output I can find "Your configuration specifies to merge with the ref 'refs/heads/bugfix'
from the remote, but no such ref was fetched.". To resolve the problem, I have to run git push in command line to create the remote branch.

Should it use git push automatically? Or change the button from sync to cloud upload in the status bar to tell user the remote branch is not existed?

![vscode-bug](https://cloud.githubusercontent.com/assets/4801955/20549785/6ccf5ed4-b16a-11e6-9769-33a363ef06a1.jpg)

**Comment by joaomoreno** [comment]
Sync will always run `pull` before `push`, and `pull` is the one complaining that your local branch should be merged with a remote branch which no longer exists. It's a good thing that you see that error message, so you are aware that something might be wrong on your remote, like someone else having deleted the branch.

The button can't change to the cloud upload one, because git isn't aware of it. Your local branch is still set to have an upstream configured, and you should take that out with:

```
git branch --unset-upstream BRANCH_NAME
```

**Comment by zuoez02** [comment]
@joaomoreno Thank you for your answer.
