### ISSUE TITLE
Continue working on: open in codespaces doesn't show changes

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#159336]
When trying to test #158384, I ran into this:

Steps:

1. open a repo on github.dev and make changes without committing.
2. Do `Continue working on` > `New Codespace`
3. New Codespace is created, but without the untracked changes.

**Comment by joyceerhl** [comment]
Sorry, the issue should have said insiders.vscode.dev not github.dev, because github.dev does not include pre-releases of Remote Repositories. You'll also temporarily need `"workbench.experimental.editSessions.enabled": true` in settings, because I disabled them in the latest Insiders and will reenable after we branch.

**Comment by andreamah** [comment]
oh ok! @joyceerhl do I need to store the edit session before continuing?

**Comment by joyceerhl** [comment]
Nope, it should be automatically stored for you when you invoke Continue Working On.

**Comment by andreamah** [comment]
ok, let me try and verify again :)

**Comment by andreamah** [comment]
works! :)
