### ISSUE TITLE
Window resized to fill 2 monitors can restore to be very large

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#159307]
1. Have two monitors with different scales. My setup: Left external monitor at 100%, right laptop monitor at 250%.
2. Open VS Code and snap it to the right (250%) monitor.
3. Grab the left edge of VS Code and drag it to fill the left monitor.
4. Grab the title bar of VS Code and shift it slightly to the left, so that it's partially off screen.
5. Close VS Code.
6. Open VS Code. The window will be extra wide and go far off screen _to the right_.

Found while verifying https://github.com/microsoft/vscode/issues/140305.

**Comment by alexr00** [comment]
Screenshot after step 3:
![image](https://user-images.githubusercontent.com/38270282/186922829-2bc6bc7f-d3c4-46c6-987f-d261a2d32d55.png)

Screenshot after step 4:
![image](https://user-images.githubusercontent.com/38270282/186922882-00fd23e4-d9af-41eb-bf31-886bea60307a.png)

Screen shot of step 6 (you can see that the window close button is not visible on the screen):
![image](https://user-images.githubusercontent.com/38270282/186923043-4dd98bd2-d1d1-4a5c-9fdc-cc12b35297cb.png)

**Comment by bpasero** [comment]
I cannot reproduce, though I am on latest Windows 11, maybe something is fixed there?

**Comment by alexr00** [comment]
I'm on Windows 11 Version 10.0.22000 Build 22000

**Comment by bpasero** [comment]
No matter what I try, I see no issue, even though I can reproduce that in certain cases the buttons are off screen because I left them off screen. But that is expected, we try to restore the window as it was even if it was in a somewhat inconvenient location. 

To clarify, did the location change or was it how you left it?

**Comment by alexr00** [comment]
The width of the window, and therefore the location of the buttons, changed.

**Comment by alexr00** [comment]
It happens 100% of the time for me.

**Comment by bpasero** [comment]
Ok lets debug together when we are both in the office, I will be there on Monday next week.

**Comment by alexr00** [comment]
This issue doesn't actually repro on my setup at the office. The major difference is that I have a have a high DPI external monitor at the office.

**Comment by bpasero** [comment]
Ok thanks, that will probably have an impact as outlined by upstream issues in electron:
* https://github.com/electron/electron/issues/10862
* https://github.com/electron/electron/issues/29605

I think @gjsjohnmurray originally wanted to tackle these shortcomings in his PR https://github.com/microsoft/vscode/pull/155589 and maybe this one case is not covered. 

Since this is depending on actual upstream fixes, let's close in favor of the upstream ones.
