### ISSUE TITLE
Deadlock when await startDebugging in resolveDebugConfiguration

### ISSUE THREAD

**Issue by xisui-MSFT** [microsoft/vscode#159498]
Does this issue occur when all extensions are disabled?: N/A

- VS Code Version: 1.71.0 - insider
- OS Version: N/A

This is likely caused by #158439...

**Comment by xisui-MSFT** [comment]
@roblourens FYI.

Looks like not waiting for startDebugging works around this, but since #158439 breaks the current behavior, I guess it still should be reverted?

**Comment by roblourens** [comment]
Do you need to do that? Is there an extension that does? I can pull it from the release this week if needed but I'm not sure whether that's a necessary scenario

**Comment by xisui-MSFT** [comment]
Yeah unfortunately we have an extension does that (since about 2 years ago), since it need to start several debug sessions at the same time with one launch config.

Can you please revert your change? Thanks!

**Comment by roblourens** [comment]
Can you tell me which extension and why you have to do that? Details are really helpful for understanding an issue that requires me to pull a fix 2 days before we release, thanks. Are you only doing this to avoid using a compound, because of https://github.com/microsoft/vscode/pull/158439? In order to support https://github.com/microsoft/vscode/issues/141514 and also this scenario, we might have to make changes to the quick pick api, and that will take longer.

**Comment by roblourens** [comment]
Deno does this, but doesn't await startDebugging

Blazor does, and does await startDebugging

In any case, I think that my change to start one debug session at a time needs to be backed out.

**Comment by roblourens** [comment]
Verification, test with an extension like this:

```
vscode.debug.registerDebugConfigurationProvider('pwa-node', {
		async resolveDebugConfiguration(folder, debugConfiguration): Promise<vscode.DebugConfiguration> {
			await vscode.debug.startDebugging(folder, { type: 'chrome', name: 'my chrome', request: 'launch' });
			return debugConfiguration;
		}
	});
```

Start a node launch config. A chrome config should also start. The bug was that it would hang forever here.

**Comment by xisui-MSFT** [comment]
>Can you tell me which extension and why you have to do that?
azure-sphere-tools. Unfortunately, a compound wouldn't solve our problem in this case, since we need to start OpenOCD for debugging. We can only start it once for all debug sessions we are going to start, and it will print out one port for each debugee. If we try to open multiple OpenOCD instances, they will fail due to conflict.

**Comment by roblourens** [comment]
The remaining issue is only about showing the quick pick from your extension, right? Can you work around this with a queue in your extension code?

**Comment by roblourens** [comment]
Oh, so for you it can still be a launch.json input (the variable resolver) vs a quickpick shown from resolveDebugConfiguration (the extension). I see.

You can open a new issue to continue trying to find a solution. https://github.com/microsoft/vscode/issues/158433 is one possibility, but that is the expensive option that won't be changed quickly. Is there a way for us to improve `inputs` support so that you don't have to show your own quickpick in a debug resolver? If there's any way to help you avoid having to do that, that would help. Any other way to avoid the problem entirely? Maybe you could give a little more background on what these things are use for.
