### ISSUE TITLE
Would it be possible for VS Code Insiders to get the release notes for the next version of VS Code?

### ISSUE THREAD

**Issue by xiaoxi-david** [microsoft/vscode#159527]
Four or five releases ago, VS Code Insiders could get the release notes as soon as they were written, but not anymore. 

This could help test new features and report bugs before the next release of VS Code.

> Version: 1.71.0-insider (system setup)
Commit: 16faaf4eb07424d5d7dba7d12bffd64309c283f7
Date: 2022-08-29T15:22:42.368Z
OS: Windows_NT x64 10.0.19044

**Comment by gjsjohnmurray** [comment]
FYI you can read them before publication by viewing the corresponding file at https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/

**Comment by xiaoxi-david** [comment]
Not only does the VS Code Insider not receive the release notes of the next stable release in advance, but also not when the VS Code is released. Therefore, VS Code Insiders unfortunately never lists new features.

**Comment by gregvanl** [comment]
We had been manually creating snapshots of the vnext release notes for Insiders but that practice dropped off several months back. We can bring back that practice, which watched for significant updates to the vnext release notes and ported them to main to go live and be available for Insiders.
Note that at the beginning of a release cycle, the vnext release notes are still just a placeholder until engineers start filling in the release notes towards the end of the milestone.

**Comment by gjsjohnmurray** [comment]
@gregvanl maybe add to the Insiders placeholder text a link to https://code.visualstudio.com/updates as a convenient way for Insiders users to get to the same information as they'd see in Help\Release Notes if they were using Stable.

**Comment by gregvanl** [comment]
Add link to website release notes in the latest placeholder with https://github.com/microsoft/vscode-docs/commit/9afb1a076b19734f442b863fc586153dd208c6cb
We did a snapshot for Insiders on Monday of this last release week and we'll try to be better at creating snapshots once the release notes are filled in. The VS Code team does a release notes read through on the Monday of the release week so that is when the release notes should be finally complete and available. 
As pointed out above, people can always read the release notes in the vscode-docs vnext branch independent of having them available in-product on Insiders.
