### ISSUE TITLE
One eager diagnostic provider can influence others negatively

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#159555]
I wonder why all of line 14 becomes gray (i.e. unused) after I remove line 13.
I guess this is because the decorations of line 13 get applied to line 14 which becomes line 13.
I think we can improve this by listening to text edits and updating the cache accordingly - when a line is deleted, its decorations should be deleted too and not just applied to whatever lines becomes the deleted line.

![recording](https://user-images.githubusercontent.com/2931520/187435772-249103ca-4c3c-4aeb-bf20-578217c6b3e3.gif)

Another example:
![Code_-_Insiders_DTmDeMLoVL](https://user-images.githubusercontent.com/2931520/187450246-370d901d-fd90-45b9-b539-b314b35d6506.gif)

**Comment by hediet** [comment]
This is for TypeScript:

![Code_-_Insiders_lwBcCUW9iB](https://user-images.githubusercontent.com/2931520/194877371-13e2e78a-0c90-4509-825b-2d16dc5369ba.gif)

And this for JSON:

![Code_-_Insiders_0JpxYxItKQ](https://user-images.githubusercontent.com/2931520/194877437-4de01cb6-3e8b-42ed-93f6-bbd8cc5597e9.gif)

This indicates that this is indeed a problem of TypeScript, and not diagnostics in general.

**Comment by jrieken** [comment]
@hediet how about a small TS repro sample?

**Comment by hediet** [comment]
```ts
console.log("" 


"test")
```

![Code_-_Insiders_IxsV6mV9B4](https://user-images.githubusercontent.com/2931520/194888991-9bdf09bb-a0b8-4489-b9f0-48826b78c335.gif)

**Comment by jrieken** [comment]
Looks pretty normal here. Also just checked with @mjbvz that TypeScript uses plain diagnostics. Can be because of another setting/feature that interfers here?

https://user-images.githubusercontent.com/1794099/194909307-f8271df1-f9c7-46d4-9a8d-c165ef7fb4d9.mov

**Comment by hediet** [comment]
Interesting. It also happens when I reset all my settings, but it only happens in the VS Code repository (but there every single time)...

**Comment by alexdima** [comment]
@jrieken I can't reproduce any problems when there is a single `ts` diagnostic present. Having a single `ts` diagnostic updates great:

Using the following sample in an untitled file in the `vscode` repo:
```ts
/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

const x = 3;
console.log('' 
                       + x + '' / 3);
```

https://user-images.githubusercontent.com/5047891/195127620-b63d1d2d-3089-4fec-bf91-b891037441d4.mp4

---

However, when removing the trailing `;` such that `eslint` also creates a diagnostic, I can see that the `ts` squiggle gets out of sync. I suspect that `eslint` is constantly updating its diagnostic, while `ts` is not. Most likely, the fact that `eslint` updates its diagnostic results in `IMarkerService.onMarkerChanged` firing and the `MarkerDecorationsService` re-reading the markers from it and re-applying them. The `eslint` marker goes to the right spot since it was newly refreshed by `eslint`, but the `ts` marker goes to its original spot since `ts` didn't update it:

https://user-images.githubusercontent.com/5047891/195128530-73134b6d-3917-40b6-8581-11494278533a.mp4

---

To tackle this and only update the decorations for a certain diagnostics provider, the `IMarkerService` events would need to be more fine-grained and then [this code](https://github.com/microsoft/vscode/blob/930c938aaf28b45773c2a1b53ce1fba916d8addc/src/vs/editor/common/services/markerDecorationsService.ts#L98-L105) could selectively update decorations by owner.

**Comment by jrieken** [comment]
That's a nice find!

**Comment by alexdima** [comment]
A cheap solution here would be for markers to record a model version id at the time they are set in the marker service. The `MarkerDecorationsService` could then read the markers and recreate squiggles only for the markers which are "fresh".

**Comment by jrieken** [comment]
Yeah, that will work but there is no guarantee for this - since markers can be pushed for any resource. Tho, in this case it will help

**Comment by jrieken** [comment]
https://github.com/microsoft/vscode/pull/164034 adds `IMarkerData#modelVersionId` (which can be undefined tho)

**Comment by jrieken** [comment]
Added the version to markers, un-assigning myself to leave the remaining work to @alexdima
