### ISSUE TITLE
Debug: cannot break in `main.js` or `app.ts` on startup

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#159684]
I am using the VSCode launch config and cannot stop in a breakpoint at either of these 2 locations:
* https://github.com/microsoft/vscode/blob/99a7f26b70fe1162c169ea652d447e14df303497/src/vs/code/electron-main/app.ts#L138
* https://github.com/microsoft/vscode/blob/99a7f26b70fe1162c169ea652d447e14df303497/src/main.js#L47

I am on macOS SI.

**Comment by bpasero** [comment]
I think `main.js` still does not work, but `app.ts` does.

**Comment by connor4312** [comment]
This is because it's a JS file, so it gets compiled without a sourcemap. We don't support pathMappings in Node.js, but if we did they could be used to fix this. This is an old PR that I might just try to 'rebuild' manually at some point: https://github.com/microsoft/vscode-js-debug/pull/1015

An okay workaround is setting breakpoints in `out/main.js`. Or we could make `main.js` a TypeScript file instead. What do you think?

**Comment by bpasero** [comment]
I think we cannot convert our CommonJS style files to TypeScript because our `tsconfig` declares to use AMD in the output. We have a few top level JS files for that reason but it would be great to use TS instead:

<img width="201" alt="image" src="https://user-images.githubusercontent.com/900690/200491743-bcf5e59e-0347-4e5e-bcf3-1a270bc2394c.png">

//cc @alexdima @mjbvz

**Comment by connor4312** [comment]
This was easier than I thought since js files bypass compilation. Will require a yarn watch restart

![](https://memes.peet.io/img/22-12-1cb508f3-ef31-4d91-912e-dc1fcec3cba3.png)

**Comment by bpasero** [comment]
👏
