### ISSUE TITLE
Cyclic service dependency: `ViewsService -> PaneCompositeParts -> CompositePart -> CompositeProgressIndicator -> ViewsService`

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#159755]

**Comment by jrieken** [comment]
marking as `important` because this blocks completion of https://github.com/microsoft/vscode/issues/159178

**Comment by sandy081** [comment]
Please note that the attached fix just fixes the cyclic dependency and does not enable `ViewsService` to be lazy because it registers viewlets and panels in the constructor. To make it lazy, it needs bigger refactoring that workbench layout shall use `ViewsService` instead of `PaneCompositeService`. Re https://github.com/microsoft/vscode/issues/90020
