### ISSUE TITLE
Inserting spaces after collapsing functions does not take effect

### ISSUE THREAD

**Issue by TeoChirileanu** [Microsoft/vscode#15975]
- VSCode Version: Code - Insiders 1.8.0-insider (731c1b034ed009991c29f9ccaf035c236458e3c6, 2016-11-23T07:09:34.296Z)
- OS Version: Windows_NT ia32 10.0.14965
- Extensions:

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.5.0|
|MagicPython|magicstack|0.5.17|
|cpptools|ms-vscode|0.9.2|
|python|tht13|0.2.3|

---

Steps to Reproduce:

1.
2.

**Comment by jrieken** [comment]
@TeoChirileanu Thanks of your bug. I have tried steps `1` and `2` as you have described. They leave some room for interpretation but I'd say it works for me.  

In case you actually want us to fix issues and implement features instead of us doing guess work, please read https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions and then update this bug. Thanks
