### ISSUE TITLE
Control Characters (LF, CR) are not shown in editor

### ISSUE THREAD

**Issue by BairDev** [Microsoft/vscode#16003]
At least on my Linux machine the rendering of (some) control characters does not work. I'm interested to see **LF or LFCR** at the end of each line.

Neither `Toggle Control Characters`, nor workspace settings `"editor.renderControlCharacters": true` change anything.

Here is a screenshot:
![vscode_control_characters](https://cloud.githubusercontent.com/assets/2767014/20590226/274b09c2-b222-11e6-98d1-7768c53021f4.png)

- VSCode Version: 1.7.2
- OS Version:  Ubuntu Gnome/Mutter 14.04, Kernel 4.4.0

This issue is somehow related to [this one](https://github.com/Microsoft/vscode/issues/12760), but has a different focus.

**Comment by alexandrudima** [comment]
VSCode (by design) normalizes line endings once a file is opened. IMHO this is a good thing probably 99.99% of the time.

#127 tracks that we add the option to opt out of it.

Until then, rendering LF or CRLF inline would be superfluous as the current line ending for the file can be always seen in the status bar:
![image](https://cloud.githubusercontent.com/assets/5047891/20747324/faf9fa8c-b6e9-11e6-9457-113acb874dd0.png)
