### ISSUE TITLE
Pressing "Start Debugging" button by focusing then hitting Enter launches twice

### ISSUE THREAD

**Issue by datho7561** [microsoft/vscode#160191]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:
```
1.71.0
784b0177c56c607789f9638da7b6bf3230d47a8c
x64
```
I was also able to reproduce the issue in the latest Insiders build as of 6 Sept 2022

- OS Version:
RHEL 8.6, kernel 4.18.0, using Gnome 3 with X11

Steps to Reproduce:

1. Open a folder with a VS Code debug configuration (I used redhat-developer/vscode-xml)
2. Hit Ctrl+Shift+D to focus the "Start Debugging" button
3. Hit Enter
4. The debug task is launched twice

In my case, I have a warning "no problem matchers defined" that I manually select "launch anyways" for. I know the debug task is being launched twice since the warning appears twice, and two instances of the `preLaunchTask` I've defined are started in the terminal.

**Comment by datho7561** [comment]
This should be reproducible on Windows as well

**Comment by roblourens** [comment]
Quick analysis - seems like the debug service status checks in https://github.com/microsoft/vscode/commit/8c3f5dd3fad92d55ab1fa534f1543ecad1cd3b87 are supposed to prevent this, but the keydown handlers must happen in a different order now. 

@isidorn do you know why the Enter handler in https://github.com/microsoft/vscode/blob/92ecdac13e8b955ce2069e95f47ac799e006c5d1/src/vs/workbench/contrib/debug/browser/debugActionViewItems.ts#L102-L104 is needed since the ActionBar handles enter? It all seems to work for me if I just delete that block 🤷

**Comment by isidorn** [comment]
@roblourens maybe in the past ActionBar did not handle enter for `ActionViewItems`. If it seems to work fine if we delete it then I suggest we just remove that code :) Thanks
