### ISSUE TITLE
Extension UI contributions: how to find out from which extension a contribution was made?

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#16010]
Extensions can write code to contribute UI pieces in various places, e.g.:
* status bar entries
* output channels
* upcoming: viewlets

We would like to allow e.g. on status bar entries and viewlets to right click -> manage extension so that people can enable/disable UI components.

Now, I am not seeing a way to find out which extension calls the methods to register. 

What is the strategy here? Should we add parameters to the methods so that an extension has to send its extension ID? Can we run the extension code in an environment where we know which extension we are talking to?

/cc @jrieken @alexandrudima

**Comment by jrieken** [comment]
The API is designed for this to be dynamic. Extensions can at any time add any number of status bar entries and output channels and also remove them again. The same is true for terminals. 

> Now, I am not seeing a way to find out which extension calls the methods to register.

That is easy because each extension gets a custom API instance which knows for which extension it was created. 

> What is the strategy here?

The question here is if it makes sense because the user configures something the extension controls. Because we cannot know how many and under what condition an extension will add UI elements we cannot create a static list that allows for configuration. We can only offer configuration for items the extension has already decided to show. But then the extension might decide to re-use that UI piece for something totally different in 10 minutes so that a user-choice like *hide this* doesn't make sense any more. For instance, the TypeScript extension creates a status bar entry that can show a hint to create a project.json-file OR it shows an error about a project being too large. Often it never shows that status bar item. How can a user make an informed decision?

The only thing that as worked so far is static lists in `package.json`. We do that for commands, menus, configuration etc. That puts us in control, we know all items statically without having to load code or being dependent on extension lifecycle state.

The easy and IMO also reasonable is to expose the status bar and activity as menu bars to which commands can be contributed. That's a proven pattern and works well in other areas. I believe for output channels, terminals, *rich (none-menu-item)* status bar items etc we have to life with the fact that they are dynamic. For once we would have to break API badly and it also seems like an artificial limitation to extension writers. 

Last, the user is already in control today by installing/un-installing extensions.

**Comment by bpasero** [comment]
@jrieken yeah I see the challenge of the dynamic API and was not proposing that you can individually enable disable UI contributions from one extension (that is not possible with that model). But rather, provide an action for the user so that it is possible to find out where a UI piece is coming from. 

I compare this with Chrome: I can right click on a toolbar entry to find out more about the action and where it comes from:

![image](https://cloud.githubusercontent.com/assets/900690/20598188/33f6f8b8-b248-11e6-9f88-af1b489c9894.png)

We could show similar entries:
* open the extension editor on the extension
* filter "Options" in the settings editor to settings from this extension
* hide the button

I think for now it would be enough to just have the link from UI to extension. A user can then decide to disable or uninstall the extension if the UI is too distracting.

**Comment by jrieken** [comment]
Ok - that makes sense. When it comes to code, we have the extension-descriptor when we create the extension API [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/node/extHost.api.impl.ts#L95). It's more or less a matter of forwarding the extension id here and there. Another part is menu items, keybindings etc which are read from package.json. In all places we lack a proper model how to drag that data along...

**Comment by bpasero** [comment]
Great, I will give it a try.
