### ISSUE TITLE
"Create Manual Folding Ranges from Selection" is not in Command Palette when use Chinese (Simplified)

### ISSUE THREAD

**Issue by AuroraTea** [microsoft/vscode#160363]
Chinese (Simplified) :
<img width="321" alt="image" src="https://user-images.githubusercontent.com/43649460/188156579-b192d7fc-7723-4a2f-882c-96aabbd25f4e.png">

English :
<img width="272" alt="image" src="https://user-images.githubusercontent.com/43649460/188156968-6378c35a-f58f-4a0b-bca4-c7ecd927c83e.png">

"Create Manual Folding Ranges from Selection" is not in Command Palette when use Chinese (Simplified)

VSCode Version: 1.71.0 (both macOS & Win10)
Chinese (Simplified) Version: 1.71.8310936

**Comment by TylerLeonhardt** [comment]
The problem is this label:
https://github.com/microsoft/vscode/blob/d39839d469145638223867f9c736ed9abf90fb85/src/vs/editor/contrib/folding/browser/folding.ts#L1068

should accept an [`ILocalizedString`](https://github.com/microsoft/vscode/blob/d39839d469145638223867f9c736ed9abf90fb85/src/vs/platform/action/common/action.ts#L10) but it only accepts a string.

deeper: https://github.com/microsoft/vscode/blob/d39839d469145638223867f9c736ed9abf90fb85/src/vs/editor/browser/editorExtensions.ts#L286
and deeper: https://github.com/microsoft/vscode/blob/d39839d469145638223867f9c736ed9abf90fb85/src/vs/editor/browser/editorExtensions.ts#L325

**Comment by TylerLeonhardt** [comment]
The workaround is to use [`根据所选内容创建手动折叠范围`](https://github.com/microsoft/vscode-loc/blob/main/i18n/vscode-language-pack-zh-hans/translations/main.i18n.json#L874) to find this item.
