### ISSUE TITLE
SvelteJS `{expression}` in svelte-markup in svelte file - the last item in `{expression}` behaves as if there is already AFTER `{expression}`, which there shouldn't be

### ISSUE THREAD

**Issue by lukaszpolowczyk** [microsoft/vscode#160549]
Version: 1.71.0
Commit: 784b0177c56c607789f9638da7b6bf3230d47a8c
Date: 2022-09-01T07:25:10.472Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 5.10.7-arch1-1
Sandboxed: No

**Steps to Reproduce:**

1. Create a file `~/.config/Code/User/snippets/ts-js-scope.code-snippets` with the contents:

```json
{
  "Console Log": {
    "scope": "javascript,typescript",
    "prefix": "cl",
    "body": [
      "console.log($1);"
    ],
    "description": "Console Log"
  },
}
```

2. Create a SvelteKit project and open any `*.svelte` file.

3. Do as shown in the video.

https://user-images.githubusercontent.com/16800535/189421564-a665ef38-7e5d-43d9-a11b-78c0d755d2f9.mp4

**Result:**

Without a space - it doesn't work.  
With space - it works.

**Cause:**

When the cursor is in front of the `}` character, it thinks it is already AFTER `{expression}`, although this is not true.

---

PS The same problem is in the last character, before `<script>`, in the `*.svelte` file.

**Comment by jasonlyu123** [comment]
This also happens in the HTML with `<button onclick="log|">` where `|` being cursor position. The problem seems to be because the position of the cursor is on the border of the embedded language. Maybe it could be changed to the previous character, when possible, instead of the next?

**Comment by jrieken** [comment]
Thanks @jasonlyu123 - I can reproduce what you are saying. @lukaszpolowczyk I don't really know what svelte kit is nor what extension you are using. So, I am focusing on html. Using "F1 > Inspect Editor Tokens and Scopes" shows me that the language at position is classified as html, not JavaScript. 

<img width="728" alt="Screenshot 2022-12-05 at 16 22 35" src="https://user-images.githubusercontent.com/1794099/205674658-d07300bc-7ff5-4c3f-a957-42718183a077.png">


Because of that no JS snippets are shown. Passing this on to @alexr00 who maintains the TextMate grammars for this. An easy workaround on your end would be to configure the snippet to also work for the "outer" language

**Comment by lukaszpolowczyk** [comment]
>  I don't really know what svelte kit is nor what extension you are using.

@jrieken SvelteKit:
https://kit.svelte.dev/
SvelteJS is the 4th most popular framework (behind ReactJS Vue Angular), and considered to have the best DX of all frameworks.

Extension for SvelteJS:
https://marketplace.visualstudio.com/items?itemName=svelte.svelte-vscode

---

But I hope that solving the problem in html/js, will also solve the problem in SvelteJS.

**Comment by alexr00** [comment]
@aeschli what do you think of modifying the solution to https://github.com/microsoft/vscode/issues/86998 so that we don't ignore strings? PR https://vscode.dev/github/microsoft/vscode/pull/168306.
