### ISSUE TITLE
Web: vscode.dev -  Cannot open a remote repository - 'Error: Cannot get metadata for Uri'

### ISSUE THREAD

**Issue by stall84** [microsoft/vscode#160547]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:  Web - vscode.dev
- OS Version:  OS Monterey 12.5.1 (21G83)

Steps to Reproduce:

1. Log in successfully to github on vscode.dev (shows in bottom left settings-sync)
2. Attempt to open any of my remote repositories.. all are public .. It will attempt to 'load' for about 30 seconds, then error with the following screen. The text of the error is "Error: Cannot get metadata for Uri(vscode..."
3. I've tried both going to vscode.dev by itself, then logging-in manually. And also tried going to my github repository, hitting period key (.) to open the web ide .. both error the same way after several seconds of 'loading'
4. I am on my work machine and we're behind a proxy.. but I'm unsure as to why that would have any effect considering the web-ide is loading fine, and allowing me to sign-in to my github fine (my work uses bit-bucket, so there shouldn't be any .gitconfig issue, even though that would be a local setting anyway).
![Screen Shot 2022-09-09 at 2 27 41 PM](https://user-images.githubusercontent.com/8472255/189420151-828b8332-9716-4aac-9e29-5abb88535b36.png)

**Comment by stall84** [comment]
I opened the network panel and re-requested the web ide (by pressing . from my repo) .. There are _**dozens**_ of these 'graphql CORS' errors.. the only other error I can find is this 404 highlighted 
![Screen Shot 2022-09-09 at 3 17 41 PM](https://user-images.githubusercontent.com/8472255/189427532-31d1188a-adc3-4bb4-aa27-b9747d390889.png)

**Comment by joyceerhl** [comment]
The GraphQL requests are the GitHub Repositories extension trying to request repository info (current SHA, filetree contents etc), so it makes sense that those requests failing would also cause github.dev and vscode.dev to fail to load.

Would you mind right-clicking on one of the GraphQL requests that fail due to CORS errors and providing the results of `Copy as fetch`? (You will want to delete the bearer token that is sent with the request before pasting the output here.)

The GitHub Repositories extension also makes requests to the REST API. Do you see only the GraphQL requests failing, and do all GraphQL requests fail?

Do you have details of how the proxy is configured (e.g. so I can try to reproduce the issue you're encountering)?
