### ISSUE TITLE
Saving a file inside .vscode folder toggles off the rendering of whitespace

### ISSUE THREAD

**Issue by adamralph** [Microsoft/vscode#16053]
- VSCode Version: 1.7.2
- OS Version: Windows 10

Steps to Reproduce:

1. Ensure whitespace is not being shown
2. Click View -> Toggle Render Whitespace
3. Observe that whitespace is being shown
4. Save the file
5. Observe that whitespace is no longer being shown

Saving the file should not toggle off the rendering of whitespace.

**Comment by jrieken** [comment]
@adamralph Are you running with a trim whitespace on save option enabled?

**Comment by adamralph** [comment]
No, but surely that is irrelevant? Whether I'm trimming whitespace or not, saving the file should not toggle the rendering of whitespace.

**Comment by adamralph** [comment]
E.g. (to prove it's not trimming of whitespace that is causing my whitespace to be removed when saving, rather than the toggling off of whitespace)

Before hitting "Save":

![image](https://cloud.githubusercontent.com/assets/677704/20621167/8da529a6-b2fd-11e6-9cb6-f895b399002d.png)

Immediately after hitting "Save":

![image](https://cloud.githubusercontent.com/assets/677704/20621198/ad93ac74-b2fd-11e6-9df8-31d0202edf61.png)

**Comment by jrieken** [comment]
Oh, wow - I was only thinking on trailing whitespace

**Comment by bpasero** [comment]
I cannot reproduce. @adamralph 
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by adamralph** [comment]
@bpasero I can reproduce it after launching Code using `code --disable-extensions`.

I've spotted a pattern: it seems to only happen when saving a `.json` file inside the `.vscode` folder.

(Saving a `.json` file outside that folder does not display the problem and neither does saving a file with a different extension in that folder.)

**Comment by bpasero** [comment]
Ok that makes more sense. We listen to changes in `vscode` folder because this is for settings and update all editors after the change is made. This means we also reset any view related setting. I do not think this is a big deal as it does not happen outside. If someone wants to chime in for a fix, feel free.

**Comment by kktam** [comment]
This bug can be reproduced in any environment, including OSX. The reproduce can simply be open .vscode/settings.json, turn on render whitespace function, and pretend to change settings.json file by typing a space in one of the settings, and then remove it with DEL key, and then save settings.json.  Now go to any editor and watch the whitespace marker disappears.

**Comment by bpasero** [comment]
Now that we store this setting inside settings.json it should be working OK now.
