### ISSUE TITLE
isStandalone() function does not recognise the new? window-controls-overlay display mode.

### ISSUE THREAD

**Issue by a-stewart** [microsoft/vscode#160695]
Recently Chrome has started reporting the display-mode of a PWA as `window-controls-overlay` instead of `standalone` if window controls overlay is specified in this manifest file.

This causes issues with the open in new window logic (and anything that relies on `isStandalone()`.

I think we can fix this with a slight adjustment to the matchMedia query.

![image](https://user-images.githubusercontent.com/150152/189650784-3e878840-5457-4979-87a3-b364387874ff.png)

**Comment by rzhao271** [comment]
@a-stewart I tried running the PWA in both Chrome Canary and Edge Stable, but `window.matchMedia` matched `standAlone` by itself in both cases. Is there another browser I can test the change on?

**Comment by rzhao271** [comment]
I haven't been able to verify this change. When I tried changing the display mode to `window-controls-overlay`, I got an error about how it was unsupported even in Chrome Canary. I also get a service worker error.
The second error remains even when I use [`display_override`](https://developer.mozilla.org/en-US/docs/Web/Manifest/display_override) instead to set the display mode to `window-controls-overlay` with the OSS PWA.

![image](https://user-images.githubusercontent.com/7199958/194193569-bf8e4255-6516-409c-9a00-16fe83a64c8a.png)

I'll have to figure out how to change around the service worker to verify this issue.

**Comment by rzhao271** [comment]
Verified!
1. Clone vscode-dev.
2. Remove the `display` key from `static\insider\code.webmanifest` and replace it with `"display_override": ["window-controls-overlay"]`.
3. Build and run the local vscode-dev on Edge and install and run the PWA.
4. Open devtools console.
5. Enter `window.matchMedia('(display-mode: window-controls-overlay)').matches`.
6. `true` is printed to the console.
7. In the Settings editor, search for the `window.confirmBeforeClose` setting.
8. The setting should have the value `never` but the description should talk about browsers closing tabs rather than quitting the application. See for reference https://github.com/microsoft/vscode/blob/6483e39fb7b0ae0aeae6bb00ff42dbed3ceb618b/src/vs/workbench/browser/workbench.contribution.ts#L621
