### ISSUE TITLE
`vscode.env.shell` might return empty string to extension if fetched very soon after startup

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#160694]
Type: <b>Bug</b>

Seems to be a timing issue. The following steps sometimes reproduce it for me, but success may depend on the performance of your workstation (mine is Windows) and which other extensions are enabled by default.

1. Clone https://github.com/gjsjohnmurray/vscode-extension-samples/tree/show-160694
2. Open the statusbar-sample folder in VS Code
3. Open a Terminal in that folder and run `npm install`
4. Switch to Debug view, choose the `ONLY Extension` configuration and run it. This launches with `--disable-extensions`
5. When Extension Host window appears, look on the right of the status bar. If the repro was successful it will look like this:

![image](https://user-images.githubusercontent.com/6726799/189645249-bc606af8-a1cc-4841-89e3-103c86203c83.png)

If this doesn't happen, try the next steps:

6. End debugging and launch the `Extension` configuration instead. This launches normally and probably won't trigger the problem:

![image](https://user-images.githubusercontent.com/6726799/189646610-59b3df11-5797-4572-9dc3-70427140001b.png)

7. From Command Palette of the EH window, run `Developer: Reload With Extensions Disabled`. With luck this will cause the problem to happen (see first screenshot).

The extension activates `"*"`, so immediately on startup. The first attempt to get `vscode.env.shell` happens from its `activate` method.

If the problem shows, click the status bar panel to get the value again. This time it should succeed.

VS Code version: Code - Insiders 1.72.0-insider (835ace5796cec0ed19a7eec119b26b57220b0f1a, 2022-09-12T05:16:16.290Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: Yes

**Comment by jrieken** [comment]
@Tyriar Looks like you should be using extension host init data for this, not a dynamic value that changes along the way

**Comment by jrieken** [comment]
yes - either block or make it clear that the value changes, e.g we need an event to signal changes. I am not familiar with how this works, does the shell-value change during a single session?

**Comment by Tyriar** [comment]
Changing the default shell (via settings or UI) will change the value. Let's track adding this API in this issue:

```ts
export namespace env {
	export const onDidChangeShell: Event<string>;
}
```

**Comment by gjsjohnmurray** [comment]
Would an early-activating extension expect to receive this event when the value of `env.shell` changes from its apparent initial value of emptystring to whatever shell is the initial default?

As I understand it, for some modes of VS Code operation `env.shell` will always be emptystring. So my extension would probably have to do other tests to check for those, otherwise it could wait forever for an event telling it that the initial shell is now known.

**Comment by Tyriar** [comment]
@gjsjohnmurray yes `env.shell` may be undefined, for example in vscode.dev. Not sure what you're doing exactly but you could listen on `env.onDidChangeShell` and enable the functionality at that point, or after some timeout? Our `AutoOpenBarrier` class in core would be handy to implement that https://github.com/microsoft/vscode/blob/9b80ed652434a6e82b3ac28c1a9a01132c8faea3/src/vs/base/common/async.ts#L438-L455

In the meantime I recommend you poll for the initial value and give up after some time, you may also want to re-check the value at a later point as well as it can change.

**Comment by jrieken** [comment]
Leaving this open for future finalization

**Comment by gjsjohnmurray** [comment]
> Not sure what you're doing exactly

@Tyriar from the activate method of the extension we call `window.createTerminal` and use its `sendText` method to run commands. When composing the command string we check `window.env.shell` to discover what shell we'll be interacting with.

We're working around the problem by retrying the `window.env.shell` call a few times. The proposed API should allow a different strategy in future, but we might just stay with what we're doing.

**Comment by gjsjohnmurray** [comment]
I think my job would have been easier if the `Terminal` returned by `window.createTerminal` had a `shell` property that told me what shell it was using. Currently it has a `creationOptions` property from which I can only discover the shell if `window.createTerminal` had specified `shellPath` explicitly.

**Comment by meganrogge** [comment]
since the `shell` type can change, perhaps having an `onDidSetShellType` listener might be better?

we do set this context key - doesn't look like there's a way to access context keys via api though atm

https://github.com/microsoft/vscode/blob/3f82b63376e4079320d448442d0f7f88039a59aa/src/vs/workbench/contrib/terminal/browser/terminalInstance.ts#L1878-L1883

**Comment by Tyriar** [comment]
@meganrogge since things can be achieved with this upcoming change (check `creationOptions` or `env.shell`/`onDidChangeShell`), I'm not sure we want to add more to the API just to handle this case.

**Comment by jrieken** [comment]
> We're working around the problem by retrying the window.env.shell call a few times

@Tyriar this still makes it sound like the current API is buggy and that the proposed event is also a band-aid for that. So, our ask is to explore how to be correct on start. 

* How long does it usually take to know what the default shell is
* How long does it take when configured by the user
* Can that value be cached (iff it's expensive) per session or across session?

**Comment by Tyriar** [comment]
@jrieken looks like it typically takes ~100ms on Windows but some reloads it was higher at 250ms. What I really think we shouldn't do is block the extension host init on the pty host process launching. Simple caching should work well though as it rarely changes once set 👍

**Comment by jrieken** [comment]
> What I really think we shouldn't do is block the extension host init on the pty host process launching.

I would agree but I wonder when does the pty-host launch? Is that with the first renderer? There might be all the time in world to get the value ready while we start the renderer, load its code, digest extension data, launch the extension host etc pp. I want us to know this

**Comment by Tyriar** [comment]
It starts up on shared process init:

https://github.com/microsoft/vscode/blob/430f212a16b1575e10a562b709f52399869401d7/src/vs/code/electron-browser/sharedProcess/sharedProcessMain.ts#L345-L354

Might be wrong, but I looked at init data and I don't think it's pulling anything from other processes right now?

The extension host service inits on `LifecyclePhase.Ready`, and while the shared process does start on workbench creation which is before then, blocking it on anything related to process communication feels like a bad idea to me. What if the process and/or IPC takes unusually long for whatever reason (Windows process overhead, remote with slow connection, etc.)? If anything we should be trying to get the extension host starting up faster.

**Comment by jrieken** [comment]
> If anything we should be trying to get the extension host starting up faster.

Of course. But as matter of fact we have the `env.shell` API. We either deprecate it because we cannot implement it correctly or we understand for real what a correct implementation will cost. 

This is the context (check F1 > Startup Performance)

The shared process runs in parallel, so it can do stuff while the renderer loads its code, gets stuff ready etc. For orientation: on my machine it takes ~420ms to reach the `Ready`-phase. We then start the extension host worker/processes which take another 293ms (web) or 364ms (nodejs) to get there init data. From starting the renderer that gives ~750ms. @Tyriar how do I figure out how long resolving the default shell takes on my machine so that I can put this in context?

<img width="574" alt="Screenshot 2022-09-26 at 16 38 00" src="https://user-images.githubusercontent.com/1794099/192305577-ba1c483b-3a1a-4301-8363-c795ec5d83ad.png">

<img width="543" alt="Screenshot 2022-09-26 at 16 37 46" src="https://user-images.githubusercontent.com/1794099/192305561-19055172-3046-4e67-8b7e-d9b73d0c75be.png">

**Comment by Tyriar** [comment]
@jrieken I was measuring the time it takes to run `TerminalProfileResolverService.getDefaultProfile` to see how long it takes:

https://github.com/microsoft/vscode/blob/816cd663e748fb78348bd09569345887e77704b4/src/vs/workbench/contrib/terminal/browser/terminalProfileResolverService.ts#L177-L179

The service is registered here for web:

https://github.com/microsoft/vscode/blob/816cd663e748fb78348bd09569345887e77704b4/src/vs/workbench/contrib/terminal/browser/terminal.web.contribution.ts#L13

Here for desktop:

https://github.com/microsoft/vscode/blob/816cd663e748fb78348bd09569345887e77704b4/src/vs/workbench/contrib/terminal/electron-sandbox/terminal.contribution.ts#L20

**Comment by Tyriar** [comment]
Update since this was last discussed: the pty host now doesn't necessarily start up, however profiles are now always detected on the main/server procs, not the pty host:

https://github.com/microsoft/vscode/blob/29d81344191f58f45d170b3a34c144fd67553970/src/vs/workbench/contrib/terminal/electron-sandbox/localTerminalBackend.ts#L294-L296

Needs a final decision whether we want to block the exthost startup on terminal profile resolving.

**Comment by Tyriar** [comment]
I measured the time it takes to `getProfiles` on the main process which is necessary in order to get the default shell and it came out to 55ms. Given this, I still think the impact is too great when doing this eagerly on the main process during startup and before the extension host is launched.

```
2023-08-22 04:30:18.840 [info] getProfiles start
2023-08-22 04:30:18.890 [trace] [File Watcher (node.js)] [raw] ["change"] globalStorage
2023-08-22 04:30:18.891 [trace] [File Watcher (node.js)] [CHANGED] c:\Users\Daniel\AppData\Roaming\code-oss-dev\User\globalStorage
2023-08-22 04:30:18.891 [trace] [File Watcher (node.js)] [raw] ["change"] globalStorage
2023-08-22 04:30:18.891 [trace] [File Watcher (node.js)] [CHANGED] c:\Users\Daniel\AppData\Roaming\code-oss-dev\User\globalStorage
2023-08-22 04:30:18.893 [trace] [File Watcher (node.js)] [raw] ["change"] globalStorage
2023-08-22 04:30:18.893 [trace] [File Watcher (node.js)] [CHANGED] c:\Users\Daniel\AppData\Roaming\code-oss-dev\User\globalStorage
2023-08-22 04:30:18.894 [trace] [File Watcher (node.js)] [raw] ["change"] globalStorage
2023-08-22 04:30:18.894 [trace] [File Watcher (node.js)] [CHANGED] c:\Users\Daniel\AppData\Roaming\code-oss-dev\User\globalStorage
2023-08-22 04:30:18.895 [info] getProfiles end
```

Caching it optimistically across sessions is a good idea though. Created https://github.com/microsoft/vscode/issues/190974 to track that separately from the event.

**Comment by jrieken** [comment]
Can we put these numbers in perspective, e.g how about setting perf-markers so that they make it into telemetry so that we have a better view. 50ms isn't slow because from main, we start the renderer, we load the renderer code which are all opportunities to run this in parallel so that the results from `getProfiles` are ready before we even attempt to start the EH process (which usually happens ~2sec after starting main)

**Comment by jrieken** [comment]
Let's leave this issue open because `shell` is still empty after startup but now we have the event which also serves as a workaround

**Comment by Tyriar** [comment]
I had a look at this and it's not as easy as I expected to get the profile in main as currently it depends upon the workspace and the renderer process evaluating parts of it before being handed off the the main process. I'm closing this as finalized because the issue where the initial value is an empty string is separate from the event API, plus it's tracked in the targeted issue https://github.com/microsoft/vscode/issues/190974
