### ISSUE TITLE
Feature Request: API to change individual line size

### ISSUE THREAD

**Issue by CoenraadS** [Microsoft/vscode#16078]
Hello

I would like the possibility to change individual line sizes

Use Case:
In Visual Studio I am running an extension that makes a line only containing a bracket smaller. 
I would like a similar extension for VSCode, but first it must be possible to shrink lines individually.

![image](https://cloud.githubusercontent.com/assets/5593825/20633784/622fb794-b34a-11e6-8045-fb653bf30872.png)

**Comment by jrieken** [comment]
We first need support from the editor for this

**Comment by alexandrudima** [comment]
To keep the number of issues in our inbox at a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: we look at the number of votes the issue has received and the number of duplicate issues filed. Thank you for your time and understanding.

If you disagree and feel that this issue is crucial: we're happy to listen and to reconsider.
