### ISSUE TITLE
Jungle of editor abstractions and services

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#1608]
We have many ways to talk about models and editors and while it might have made sense back then we should consider to consolidate them. Let's start by taking inventory:

On the service side we have:
1. IEditorService (in platform/editor/common)
2. IWorkbenchEditorService (in workbench/services/editor)
3. ICodeEditorService (in editor/common/services)
4. IModelService (in editor/common/services)

The latter two use editor types like `IModel`, `ICodeEditor` etc while the former two abstract them away, like `IEditor` and `ITextEditorModel`.  Tho, those abstractions are very weak and often you encounter code like this: `let editor = this.editorService.getActiveEditor(); this.lastKnownEditorViewState = (<IEditor>editor.getControl()).saveViewState();`

I think this needs simplification in the face of the challenge of building a simple API that hides all of this. Also, there are semantic differences, like `IWorkbenchEditorService` not knowing anything about inline-editors and `ICodeEditorService` not knowing anything about the _active_ editor etc. 

Let's collection more issues and let's discuss @alexandrudima @bpasero

**Comment by bpasero** [comment]
Well for the workbench editor service there is not just code editors. There are other editors like the markdown preview, so we cannot just say the workbench editor service is just about code editors.

**Comment by jrieken** [comment]
One proposal I would make is to ditch the `IEditorService` from `common` and have the functionality be defined in `editor`. Then we can get rid of the useless abstraction of editors.

**Comment by jrieken** [comment]
@bpasero That's what I want to discuss. A preview is not an editor at all, but sits in the space an editor usually takes. And those editor that toggle in-place could maybe be modelled like the diff editor is

**Comment by jrieken** [comment]
Another thing we should explore/disucss and I admit I know little about it is whether we can do more with just URI and less with editor inputs

**Comment by bpasero** [comment]
+1 for talking, but maybe in person also when Alex is back :)

**Comment by jrieken** [comment]
+1

**Comment by jrieken** [comment]
Another thing that made me sad today is that we have:  `IResourceInput`, `ITextInput`, `IEditorInput`, `IFileInput` which all equal but also different.

**Comment by alexandrudima** [comment]
:+1: for consolidation, but I'm not sure how.

I originally added `ICodeEditorService` because I needed a means to go from a global context (keybinding dispatching) to the code editor that should receive the command without sticking pointers in the DOM. Since then, I think we also use the `ICodeEditorService` for syncing text editors to the extension host.

The `IModelService` acts as the syncing hub for all text buffers which I think is a lot better than before when the text syncing happened through the modes.

Hard to say where to cut from. Perhaps we should look at the users of `IEditorService` in the `platform` and `editor` layer, I think most of the times `IEditorService` is used for opening things. Perhaps that should be done somehow differently or renamed (e.g. `IEditorService` sometimes opens a web browser and not an editor...). Also `getActiveEditor` is a bit misleading (implies there is always an active editor?) as the focus could be in a viewlet or no editors are opened, in which case I'm not sure what that method returns.

**Comment by bpasero** [comment]
As for the editor service: there is always an active text editor, independent from where focus is. Clicking into a viewlet does not make the current active editor inactive. The same would be true btw if we introduce a horizontal panel for output/repl.

**Comment by bpasero** [comment]
Some ideas from talking to Joh:

Most of the methods in `IEditorService` should move to `IPartService` and talk about the general concept of parts in the slots 1-3. Since a control in one of the slots can also be something else than a code editor, it would make sense to call these things more generally parts than editors.

The `IEditorService.resolve()` method could move into the `IModelService` or similar. It's use case is mainly only for code editor models, with few exceptions that we maybe can handle different.

There should be a service that allows to open a `URI` in the editor at a position.

**Comment by bpasero** [comment]
> Another thing that made me sad today is that we have: IResourceInput, ITextInput, IEditorInput, IFileInput which all equal but also different.

I got rid of ITextInput and IFileInput. The remaining difference between IResourceInput and IEditorInput is expected because the one is the lightweight URI only input and the other the more heavy typed EditorInput from the workbench.

**Comment by jrieken** [comment]
:+1:

**Comment by jrieken** [comment]
I added the concept of a `scheme -> ContentProvider` to the workbench layer such that we can now handle all sorts of scheme like any other uri - the [code](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/common/editor/resourceEditorInput.ts#L39) is compact but should maybe be in a service that we then craft out

**Comment by bpasero** [comment]
@jrieken thanks. I think this should move into a static registry similar to our other platform registries that we have. the concept of resolving content from a URI seems so low level to me that it could even live in platform. In theory we could beef this registry up later to implement other file service related methods once we want to support other protocols like ftp and then the file service could just be the implementation of the registry interface for the "file://" scheme.

**Comment by jrieken** [comment]
yes, but let's take baby steps given the march deadline

**Comment by bpasero** [comment]
Yes, supporting other protocols is way beyond March, also because we have code that just uses raw node.js fs APIs and not the file service in all cases.

**Comment by jrieken** [comment]
Maybe unrelated but another source of confusion is those two methods that are on `IQuckOpenService` and not on a editor service

```
/**
	 * Returns the sorted list of editor inputs that have been opened by the user.
	 */
	getEditorHistory(): IEditorInput[];

	/**
	 * Removes an editor history entry by the given input.
	 */
	removeEditorHistoryEntry(input: IEditorInput): void;
```

**Comment by bpasero** [comment]
Yes, no real reason to have it in quick open service. It is even being used outside of quick open in other areas already I think.

**Comment by bpasero** [comment]
Moved quick open history into the history service (https://github.com/Microsoft/vscode/issues/6544)

**Comment by bpasero** [comment]
With the grid work I revisited this and I think we are now in a pretty good spot:
* `IEditorService` (in `platform/editor/common`) no longer exists, instead a new method was added to `ICodeEditorService` ([`openCodeEditor`](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/browser/services/codeEditorService.ts#L47), [`getActiveCodeEditor`](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/browser/services/codeEditorService.ts#L46)) and this has been adopted through the code editor. That also means that the code editor no longer has to implement an ugly `SimpleEditorService`. 
* `IWorkbenchEditorService` was renamed to `IEditorService` and is now the only one named like that
* there is new convenience methods `IEditorService.activeTextEditorWidget` and `IEditorService.visibleTextEditorWidgets` that avoid the repeated calls to `editor.getControl()` we used to have before. This will return `IEditor` because it can either be a text editor or a diff editor. Clients will still have to call into `isCodeEditor` / `isDiffEditor` to get the proper type, but I think that is fair
* there are new overloads in `IEditorService.openEditor()` for opening `IResourceInput` or `IResourceDiffInput` that will return `ITextEditor` and `ITextDiffEditor` where the control property is of type `ICodeEditor` or `IDiffEditor`

I thought about renaming `IEditorService` (and all related things like `EditorInput`, `EditorModel`) to something else to reflect the fact that our editor part in the workbench can be the container of other things than editors (e.g. markdown preview, etc). I could not really come up with something better though that would reflect the place in the layout where these things open. Even though strictly speaking a markdown preview is not an editor, I like the fact that when talking about "editor", you can quickly think about where the thing should show up visually. If we start to talk about something else (panes? panel? view? container?) it becomes a lot harder to explain what that actually means.
