### ISSUE TITLE
Explore alternate interaction model for merge editor

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode#160829]
Based on the feedback, it's clear that the current checkbox interaction model is confusing to users. My working assumptions:
- An empty checkbox doesn't jump out as something that can be interacted with in this context
- The interaction for accepting both sides is confusing to users
- Hard to express other states

These are both naive sketches for now, but here are two quick ideas:

## CodeLens 

One idea would be to use something much more familiar to users who have already dealt with our existing merge conflict UI:

<img width="1268" alt="a" src="https://user-images.githubusercontent.com/25163139/189976771-f43213bb-c40d-4802-a940-a9b0648f6327.png">

## Icon buttons

A smaller deviation from the checkboxes today—we could use icon buttons that show the action to be taken (check me to accept) vs. representing the current state (like a checkbox).

<img width="1268" alt="b" src="https://user-images.githubusercontent.com/25163139/189978186-34df2ef7-9656-41b9-bf16-5a469ce9d0c7.png">

cc @isidorn @hediet

**Comment by daviddossett** [comment]
Here's how the CodeLens option could work
- Similar to inline decorations, we clear the colors and actions once a conflict has been acted upon
- We could opt-in to displaying "Accept Both" only where applicable
- Undo could be used to revert an "Accept" action

https://user-images.githubusercontent.com/25163139/190030389-4574b4b0-85b7-4e59-bfea-6ff2ab71d6cf.mp4

**Comment by stevencl** [comment]
I think the second exploration is getting closer to solving the problem we observed yesterday. The main problem was that the participants were unaware that they could accept both changes since that is why there is a conflict. Since these two changes conflict, the user isn't even aware of the possibility that parts of each change could be accepted. They were also very reluctant to try things out for fear of prematurely committing to one set of changes or another. The second alternative above suffers from this problem - that once you make a choice it looks very difficult to reverse that decision.

We need to find a way that explains very clearly the different options that users have for each set of changes (accept incoming, current or a mix of both) and in such a way that we encourage exploration. Is there a way we can list out all changes/conflicts and for each, visualise each of the options available to the user. Then have them click on the option that they want?

I imagine something like one editor that splits into two or three sections at the location of each change/conflict. Each section shows one possible state for that location (incoming, current or a mix of both). The user can look at each state and then select the one that they want. My hypothesis is that takes away a lot of the unpredictability that we saw yesterday which resulted in a lack of clarity and increased anxiety.

**Comment by daviddossett** [comment]
Great points @stevencl. 

> We need to find a way that explains very clearly the different options that users have for each set of changes (accept incoming, current or a mix of both) and in such a way that we encourage exploration. 

I think this challenge is part of why I'm betting on the CodeLens style actions being the best option here. We can show each conflict with positive actions like "Take Incoming Changes" or "Take Both Changes" right above the relevant code and they can see the preview in the "Result" view. They don't need to guess what some icon or checkbox state implies.

> Is there a way we can list out all changes/conflicts and for each, visualise each of the options available to the user. Then have them click on the option that they want?

I'm intrigued by this idea. The Result pane is trying to fill this role by acting as a preview, but it isn't showing _all_ possible outcomes for a user to scan and pick from a list. It's just representing the state of your actions above. I'd bet that such a preview would be equally valuable in the inline conflict view as well.

## Demo

In the meantime, I did another exploration this morning that addresses some of the issues were seeing. This new exploration...
- Shows CodeLens actions that persist/can be undone
- Shows an explicit "Keep Base" action instead of tracking some complex handled/unhandled state we have today
- Shows a "Combine Changes" action in the Result view to expose a smart merge on a situation where both changes were taken but we simply stacked them instead of trying to combine them. The idea here was to be late-bound and to put the user in control vs. us doing it automagically. 

There are still a handful of gotchas/corner cases not addressed here—just want to get the general idea across.

https://user-images.githubusercontent.com/25163139/191131993-59425554-08db-4bf1-9546-9fdb69da1547.mp4

**Comment by daviddossett** [comment]
Closing since we've now implemented the core of these changes.
