### ISSUE TITLE
Default Live Preview. HTML. Not updated at change a attached files

### ISSUE THREAD

**Issue by IgorNovozhilov** [Microsoft/vscode#16081]
Preview is not updated when you change the stylesheets, and scripts attached to the html file using the tags `link` and `script`.

- VSCode Version:
![image](https://cloud.githubusercontent.com/assets/3082812/20635340/07712d10-b36d-11e6-944b-8d88b161c2ae.png)

- OS Version: Linux Mint 18 x64

Steps to Reproduce:
Files from the example: [test-files.zip](https://github.com/Microsoft/vscode/files/613889/test-files.zip)

1. If I embed the styles and scripts directly in the html, when you change the code preview is updated.

![image](https://cloud.githubusercontent.com/assets/3082812/20635451/3bb93dfa-b36e-11e6-9249-5c69432d6924.png)

2. If I use the tags `link` and `script` code changes not covered in the preview.

sample html
![image](https://cloud.githubusercontent.com/assets/3082812/20635495/babb10ce-b36e-11e6-91dd-0482218ed8c2.png)

change code in file `test2.js`, the changes are not applied
![image](https://cloud.githubusercontent.com/assets/3082812/20635497/c0300334-b36e-11e6-8562-83f6bc9777a1.png)

**Comment by mjbvz** [comment]
I believe this was actually using the markdown preview, which used to allow viewing any file as markdown. Html content also happens to be valid markdown but previewing html was never a scenario we officially supported. We have since restricted the markdown preview to markdown files

#12080 tracks official support for a html live preview. There are a few extensions in the marketplace that you can try  that already add this, such as https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer
