### ISSUE TITLE
Perf: investigate parallel loading of non-async `script` tags

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#160800]
We load our bootstrap files via explicit hardcoded `script` tags:

https://github.com/microsoft/vscode/blob/f0fc8a0a63920ed34ccbd70ccb43e2048cad0780/src/vs/code/electron-sandbox/workbench/workbench.html#L12-L18

Looking at the network tab they seem to load in sequence and not in parallel:

![image](https://user-images.githubusercontent.com/900690/189916411-d2f3e638-8fba-42bc-adf3-cd193c1d3bf4.png)

My understanding is that Chrome can utilise up to 4 parallel requests for loading resources as shown on https://vscode.dev:

![image](https://user-images.githubusercontent.com/900690/189916708-a5c4a4f8-f9d7-467b-bc6b-87e5440ee93f.png)

It would be interesting to figure out if:
* the fact that we use custom protocol might prevent Chrome for parallel network request
* the fact that Electron is used in general prevents this
* whether this is actually an issue in Electron or just in general how non-async `script` tags work in Chrome

//cc @alexdima

**Comment by deepak1556** [comment]
Couple of differences between the web and Electron test to be noted,

1) On web, we are doing a network request via http(s) protocol and chromium internally has a socket pool that allows a maximum of 6 parallel connections to any given host, refs https://source.chromium.org/chromium/chromium/src/+/main:net/socket/client_socket_pool_manager.cc;l=42-53. The parallelization cap you see in the above test is due to that.

2) In the above screenshot for the web, the four parallel requests are done between a JS, CSS and some image resources. We **cannot** have parallel requests non-async classic JS resources. This is because the HTML spec says that when a `<script>` tag without async attribute is encountered it should block the parsing of rest of the HTML until the corresponding script resource is fetched and parsed, for ex:

```html
<head>
<script src="first.js"></script> // HTML parsing will stop here until this resource request finishes
<script src="second.js"></script>
...
```

3) For Electron, we are not performing a network request but rather file I/O using the custom protocol handler, so the network parallelization is not seen in this case. However, we do get fetch the resources using background threads so the async requests will process as expected even with custom protocols.

I think the idea to concatenate the 4 synchronous JS resources in the workbench is still a good idea as we will get some micro saving with reducing the number of requests in favor of faster file I/O, also it helps with code caching.

**Comment by bpasero** [comment]
👏 

> I think the idea to concatenate the 4 synchronous JS resources in the workbench is still a good idea as we will get some micro saving with reducing the number of requests in favor of faster file I/O, also it helps with code caching.

I will work on that.
