### ISSUE TITLE
No javascript intellisense

### ISSUE THREAD

**Issue by steveharoz** [Microsoft/vscode#16102]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:06:37.428Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.0.18|
|html-class-suggestions|AndersEAndersen|1.0.3|
|debugger-for-chrome|msjsdiag|2.2.2|
|Spell|seanmcbreen|0.8.6|
|shader|slevesque|0.2.2|
|iis-express|warren-buckley|0.0.5|
|bootstrap-3-snippets|wcwhitehead|0.0.8|
|JavaScriptSnippets|xabikos|1.2.0|
|html-css-class-completion|Zignd|1.0.3|

---

Steps to Reproduce:

1. include a javascript library in the directory (d3.js)
2. start typing a function name (d3.se...)
3. It should autocomplete (d3.select), but it doesn't

**Comment by mjbvz** [comment]
@steveharoz Can you please provide some additional information about what your project looks like or provide a basic set of steps to setup a similar project. A few questions that would help us:

* Where is d3 coming from? Npm? CDN? Local file?
* How is d3 being included? Html script tag? `require`?
* What file are you working in where autocomplete is missing? Is it a javascript file included in html? Something else?

Thanks

**Comment by sant123** [comment]
@mjbvz the problem comes when you don't specify the require method inside JS.

e.g:

``` javascript
var angular = require("angular");
angular.module(....) //It has intellisense!
```

``` javascript
angular.module(....) //There's no intellisense!
```

**Comment by steveharoz** [comment]
I don't use `require`. I just include the javascript file in the project.

Here is my directory structure:

    main_directory
    |
    +---- index.html (which includes <script src="libraries/d3.js"></script> and <script src="main.js"></script>
    +---- main.js (where I'm trying to get the intellisense working)
    +---- libraries
        |
        +---- d3.js (the latest non-minified version downloaded from d3js.org)

**Comment by sant123** [comment]
Exactly @steveharoz, but what I'm trying to explain is VS Code uses the `require` method in order to give you intellisense. However, it should exist other way to provide intellisense since javascript doesn't use CommonJS specification.

**Comment by mjbvz** [comment]
@sant123 If working only with JS, you do not need the `require` to get intellisense for `d3` because the library has a global symbol. Just have `d3` in your `package.json` and VSCode will use [automatic typings acquisition](https://code.visualstudio.com/updates/v1_7#_better-javascript-intellisense) for intellisense:

![dec-01-2016 10-39-23](https://cloud.githubusercontent.com/assets/12821956/20807152/9c069aca-b7b2-11e6-8a04-a5432fc8a5b4.gif)

But @steveharoz's case – without a `require` statement and without a `package.json`– we currently cannot detect that d3 is used so we cannot provide intellisense for it.

**Comment by steveharoz** [comment]
Thanks @mjbvz. Is there a guide somewhere for how to make a package.json file and where to put it? An empty file named pakcage.json in the root directory doesn't work.

Also, do I have to make one for every .js file in my project?

**Comment by sant123** [comment]
Got it @mjbvz, it seems there's some delay for loading the typings into the editor. I had to wait for a while for getting intellisense. But in some packages definitely there's no intellisense, for example moment can work around Node.js and Javascript. Please take a look:

![moment](https://cloud.githubusercontent.com/assets/7959437/20808675/7d7e1b68-b7d1-11e6-8ed9-60ace646fb56.gif)

¿Is that `d.ts` lagging the intellisense? Also I've seen that `@types` folder doesn't have any definition of moment. 

![image](https://cloud.githubusercontent.com/assets/7959437/20808743/baf2add8-b7d1-11e6-9449-6e5a0ea8f92f.png)

I have tested them on Windows and Ubuntu.

**Comment by sant123** [comment]
@steveharoz [here](https://docs.npmjs.com/getting-started/using-a-package.json) explains how to create a package.json and explains some of the values in it. You can create a package.json quick putting this line in your terminal.

> npm init -y

**Comment by steveharoz** [comment]
@sant123 I tried typing that into both the "command palette" (on top) and the "integrated terminal" (on bottom). Neither worked.
![image](https://cloud.githubusercontent.com/assets/2257540/20809312/5c8053c8-b7cb-11e6-8cc7-71c2d692f37b.png)

![image](https://cloud.githubusercontent.com/assets/2257540/20809395/83670db0-b7cb-11e6-8a27-ac798e095f8e.png)

**Comment by sant123** [comment]
It seems you don't have Node.js installed. You can get it [here](https://nodejs.org/en/) 😄

**Comment by steveharoz** [comment]
I appreciate the help, @sant123, but I'd rather not install a 3rd party app that I'm familiar with.

**Comment by waderyan** [comment]
@steveharoz we do provide IntelliSense without a package.json but for only the 400 or so most popular JavaScript modules. 

We do not have documentation on creating package.json. Package.json is an npm file. You can see the official docs [here](https://docs.npmjs.com/files/package.json). npm is for Node. If you do not want to install node then you can still create a package.json file like so:

```
{
  "name": "<name of your app>"
  "version": "<version of your app>"
  "dependencies": {
     "d3": "<version you are using>"
  }
}
```

Closing as this issue is for better documentation and I have created an issue here - https://github.com/Microsoft/vscode-docs/issues/693

**Comment by bowdenk7** [comment]
This might actually be a different issue. `d3` is listed in the top 400 packages and thus should get IntelliSense without a `package.json` or an import. 

In the case of moment, it isn't in the cache because they ship their own `.d.ts` file. You'll notice in your example that the `.d.ts` is inside `node_modules/moment`. We're working on a way to auto acquire moment when you get it from a source other than npm, but for the time being the only way you can get moment intellisense is if you use npm or manually add the types. Why the global moment functions aren't exposed before importing is likely related to the above issue.

**Comment by sant123** [comment]
So, for moment the only way I can get intellisense is from its own `d.ts` file? Not from definitely typed? I think in which type file would be the most recent. Thanks.
