### ISSUE TITLE
Perf issues with rendering of stderr/stdout outputs when they are regularly updated

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#161024]
```python
import logging
import sys
import os

for k in range(10_000):
    sys.stdout.write(f"{str(k)}{os.linesep}")
    sys.stdout.flush()

print('')
print('Completed')
```

Currently when we have a tight loop such as the above two samples in a Jupyter notebook (python kernel),
then things could slow down in Renderer process as we end up sending the same large output over & over.

**Possible alternatives:**
* Send the updates to the notebook renderer instead of sending the same large output every time.
* Debounce updates to the renderer
* Other

**Comment by rebornix** [comment]
Digging a bit into this and I found the perf difference is actually huge between Jupyter NB, Jupyter extension and UI

Jupyter NB: 7 seconds
Jupyter extension/kernel: 12 seconds
VS Code UI (our timer): 16 seconds

<img width="1002" alt="image" src="https://user-images.githubusercontent.com/876920/190700939-aa568a15-8a91-4c28-a282-5825b55d9cf7.png">

I wonder how Jupyter NB being much faster than us, maybe they have some proper debouncing.

**Comment by roblourens** [comment]
I was also looking at this, didn't see you were too @rebornix. Here's what I found. Using this code from the original issue

```py
# %% let's crash
import logging

for k in range(10_000):
    logging.warning(k)
```

I applied Don's PRs from vscode-jupyter and vscode, ran the code, checked the actual time to finish rendering and the real time that is reported when execution is done.

```
Results: actual total time, reported kernel time

No changes, both PRs
    28s, 9s
    31s, 9s

Modified VS Code to not send outputs to webview at all
    18s, 8s
    17s, 7s

Modified VS Code to skip the actual compression, rather only return one hardcoded buffer, and don't send outputs
    7s, 7s

Don't compress, do send outputs
    10s, 7s
```

I think the compression function can be optimized quite a bit, and my test shows that removing it from the equation makes a bigger impact than removing rendering. I'm just doing this because it seems like @DonJayamanne got much better results locally, and I want to check that it is possible to get to a performant place with this approach in general. For example if the bottleneck turned out to actually just be sending lots of small messages then we might have a  problem. But I don't think that's the case.

Profiler shows that lots of time is spent decoding/reencoding the buffer. I wonder whether we can do these operations on raw bytes instead of strings?
https://github.com/microsoft/vscode/blob/d3a86e9cba76f8e8dccf0d156eeb6af6d0a75ea1/src/vs/workbench/contrib/notebook/common/notebookCommon.ts#L978-L979

And this function is expensive, maybe we can do this with one regex instead of running multiple regexes on the same range of text.
https://github.com/microsoft/vscode/blob/d3a86e9cba76f8e8dccf0d156eeb6af6d0a75ea1/src/vs/workbench/contrib/notebook/common/notebookCommon.ts#L1025-L1030

Just a couple things that I noticed. And there is probably other micro-optimization we can do on the compression. I'm not saying we should stop and do that now, I'm just validating that there is room to make this approach performant, and I think there is.

**Comment by DonJayamanne** [comment]
> just validating that there is room to make this approach performant, and I think there is.

agreed. id prefer we just deal with the raw bytes.
the code your have highlighted that uses regexes doesn't work properly, it's a known issue in jupyter lab and notebook. hence trying to optimize that is only s stop gap solution as it will have to be fixed again. this is something i mentioned in a standup. that code deals with backspaces.
id personally prefer a proper terminal character handling code that deals with the bytes, bringing some of Daniels code. 

the original pr dealt with bytes, but handling backspaces proved more challenging and resorted to just converting to strings and copied code directly from jupyter ext.

again agreed there's room for improvement.

**Comment by DonJayamanne** [comment]
I think I can make some simple and quick improvements to look for the character in the bytes before converting the buffer to string.
We need to convert buffer to string only for processing of \r and \b characters. However if they don't exist, then there's no processing to be done.

**Comment by rebornix** [comment]
Closing this for now and we can revisit when users hit real perf issues.
