### ISSUE TITLE
Feature request: Call Hierarchy

### ISSUE THREAD

**Issue by svenefftinge** [Microsoft/vscode#16110]
A call hierarchy of a function invocation is a very useful tool to quickly navigate in code. In VSCode I find my self using "Find Reference" repeatedly to do what I do with a call hierarchy in IDEs (Eclipse, IntelliJ).

UI-wise I think it could fit nicely with how "Find References" is done, but of course we would need to have a tree on the right hand side and the labels need to display the reference containing function definitions.

Conceptually it is close to a type hierarchy, which is requested in #15533.

**Comment by hoffmael** [comment]
Adding my vote to this one. This would be my number 1 most important missing feature and use it daily in eclipse to navigate and understand the structure of a large code base. I can live without find all references feature and use global text search with whole word option instead.

**Comment by hualet** [comment]
This feature is really necessary for people like me who need to browse source code of multiple open source projects.

**Comment by sandipanbiswas** [comment]
It would be super beneficial especially for users coming from eclipse,intellij background.

**Comment by jrieken** [comment]
@hualet @sandipanbiswas FYI we ignore comments in the sprit of "+1", "me too", "This is needed" etc but go for up votes (:+1:) on the descriptions of this item. Please refrain from adding these comments because it generates a lot of noise to the project and we spend time reading these comments instead of getting actual coding work done. Thanks

**Comment by thernstig** [comment]
@jrieken Have you had any progress on this?

**Comment by iradiohead** [comment]
anynews

**Comment by thernstig** [comment]
For those in interested in this, I think we can stop asking for news on this for a while as I found this comment from **2018-08-06**:
https://github.com/Microsoft/vscode-cpptools/issues/16#issuecomment-

> No news. We haven't started working on this yet. We plan to implement IntelliSense-based Go to Definition and Find All References before a Call Hierarchy, all of which requires implementing a multi-translation unit IntelliSense (our currently one is only one translation unit at a time).

**Comment by svenefftinge** [comment]
@thernstig I think that comment is related to the c/c++ extension not generally to VS Code.

**Comment by tigerich** [comment]
I need it desperately now - call graph or call hierarchy!

**Comment by Alex-EEE** [comment]
I agree, this is desperately needed

**Comment by svenefftinge** [comment]
There now is a PR for this for the LSP 
https://github.com/Microsoft/vscode-languageserver-node/pull/420

**Comment by med1001** [comment]
this feature will make our life easier.

**Comment by jrieken** [comment]
I will explore this during the March milestone. Stay tuned.

**Comment by jrieken** [comment]
> UI-wise I think it could fit nicely with how "Find References" is done, but of course we would need to have a tree on the right hand side and the labels need to display the reference containing function definitions.

@svenefftinge The common UX for this seems to be a tree with a details pane on the side. Eclipse and IntelliJ are very similar, VS is a little different wrt calls/callers, e.g instead of the global direction toggle there is always nodes like 'Calls from "Foo"' and 'Calls to "Foo"'. That adds one more indent level for each symbol but it allows to see calls and callers at the same time. Something the Eclipse UI doesn't do: 

![multiplenodes](https://user-images.githubusercontent.com/1794099/54194186-e7cc2680-44bb-11e9-8136-3094e91214a5.png)

<img width="863" alt="Screenshot 2019-03-12 at 11 44 42" src="https://user-images.githubusercontent.com/1794099/54194329-42658280-44bc-11e9-8a2f-e935bbb27a97.png">

Comments, ideas, preferences? Embedding this information as peek and/or viewlet should be doable. I was also thinking about a breadcrumb'ish approach, similar to the columns view of the Mac Finder, where a column represents all calls of a function and where expanding a call adds a new column.

**Comment by iFarmGolems** [comment]
@jrieken I think graph would be useful as well - for a quick glance when refactoring. Something like [this](https://marketplace.visualstudio.com/items?itemName=YaobinOuyang.CodeAtlas) extension has

**Comment by mharris84** [comment]
@jrieken My preference would be for the Eclipse style of call hierarchy over the VS style.  The later, whilst more functional, I feel will get very noisy quickly; and in this situation I feel "less is more".

I Eclipse I am able to 'pin' a given call hierarchy such that I can have a few open at once, for me this deals with the uni-directional nature of the hierarchy.

**Comment by jrieken** [comment]
> My preference would be for the Eclipse style of call hierarchy over the VS style. The later, whilst more functional, I feel will get very noisy quickly; and in this situation I feel "less is more".

I was thinking along those lines but allowing all, e.g. "show calls",  "show callers", "show call & callers" (vs style). Think of the radio buttons in the Eclipse UI but in a way that both can be selected at the same time.

**Comment by hoffmael** [comment]
> I was also thinking about a breadcrumb'ish approach, similar to the columns view of the Mac Finder, where a column represents all calls of a function and where expanding a call adds a new column.

Green Hills, an embeded systems compiler and IDE, implemented call hierarchy this way, in theory it sounds good but in practice it ends up being kinda clunky because it requires so much screen real estate, as it expands in both the X and Y directions, that it needed a separate window to navigate it. I much prefer Eclipse's implementation in this regard, as it can display below the code window as.

See this screen shot from the Green Hills IDE, illustrating this, (the blurred parts are from scrubbing the proprietary info)
![image](https://user-images.githubusercontent.com/24258055/54386522-bfc8f880-465e-11e9-9c0e-946df1421aae.png)

**Comment by jrieken** [comment]
UX: The plan is to have the call hierarchy as peek **and** as bottom panel. I have started with peek because it simpler. Two ideas:

**A** Tree & Preview like it's done in Eclipse, VS, et al

![callh-tree](https://user-images.githubusercontent.com/1794099/54449814-43621280-474f-11e9-8347-89c677537e12.gif)

**B** Columns that shows calls with the actual source lines, where selecting a call drills into it

![callh-columns](https://user-images.githubusercontent.com/1794099/54449813-43621280-474f-11e9-954b-3a196662e447.gif)

**Comment by jrieken** [comment]
New UX proposal that stays closes to reference search peek. Have a tree on the right, have an editor on the left. The tree shows containers, e.g. functions calling the anchor function, with a hint of how often a function calls the anchor function. The editor itself highlight them. 

<img width="969" alt="Screenshot 2019-03-18 at 12 15 29" src="https://user-images.githubusercontent.com/1794099/54534236-3a11b980-498c-11e9-9339-fefb7c5b1c96.png">

**Comment by jrieken** [comment]
Closing as we have a UI and proposed API for this. However, this time we have been faster than extension, e.g. no extension provides data yet and will take roughly one milestone until this feature lights up. Stay tuned

<img width="948" alt="Screenshot 2019-03-25 at 14 55 51" src="https://user-images.githubusercontent.com/1794099/54925282-4490fd80-4f0e-11e9-814b-7491701d6813.png">

**Comment by asilvadesigns** [comment]
This is awesome.

**Comment by Arcenciel** [comment]
Finally some hope for call hierarchy. Thank you all.

**Comment by gandhiprachi** [comment]
@zdog234 - Is this available for golang in vscode, i'm on the latest release and i'm unable to find this feature

**Comment by zdog234** [comment]
@gandhiprachi I don't believe it's been implemented yet:
https://github.com/Microsoft/python-language-server/issues/888
