### ISSUE TITLE
Conditional breakpoint icon

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#1611]
We need a nice icon to distinguish conditional breakpoints from regular ones. Some ideas:
* Use a different color, for instance gold (chrome debugger does something similar)
* Add a small question mark to the corner of the current breakpoint.svg

In both cases we would need one for light theme and one for dark theme

@stevencl suggestions welcome

**Comment by isidorn** [comment]
At the moment I am using an orange icon to get user feedback

**Comment by bgashler1** [comment]
Here are the icons.
[conditional breakpoint icons.zip](https://github.com/Microsoft/vscode/files/83463/conditional.breakpoint.icons.zip)

**Comment by isidorn** [comment]
Thanks for the icons!
Andre and me have some feedback:
* The '+' is confusing, for us it represents adding something new when clicking on it
* Some characters which better represent a conditional breakpoint: = ? !
* The conditional breakpoint looks exactly like the swiss flag
* I would also check what VS is doing
* No need for the disabled conditional breakpoint icon, in that case we will just show the disabled icon. Too many icons cause confusion imho

**Comment by stevencl** [comment]
Actually this is the VS icon for conditional breakpoints. For example:
![conditional](https://cloud.githubusercontent.com/assets/1704059/12231350/b48aa848-b84e-11e5-83c6-11aa726dc919.png)

Like you, we also thought that the + might suggest that something new is being added so we checked with the VS team first to see what feedback they had. We asked the VS debugger UX team about any positive or negative feedback they have had about this icon and apparently they have had no feedback one way or another about it in all of the studies they have done.

A quick look here too doesn't bring up anything about the icon: https://visualstudio.uservoice.com/forums/121579-visual-studio-2015?query=conditional%20breakpoint%20icon

We considered ? and ! but didn't go with those as we thought that those might suggest that there is something wrong with the breakpoint. 

In the absence of any significant negative customer feedback, we felt that the best option was to be consistent with VS. Hence the suggestion to use the VS icon.

**Comment by isidorn** [comment]
Lots of vs icons did not get negative customer feedback but we are still not using them, like the step next, step in... So I would not take that as an argument.

What about the equality character =
What about just using a different colour like the current orange?
The first and thirds point from my previous post are my biggest concerns and are the reason I do not think this issue should be closed.

@weinand @egamma opinions welcome

**Comment by stevencl** [comment]
Actually the step into and step out icons are now consistent. When we designed the VS Code icons we worked with the VS team to introduce these icons into VS too as it was felt that they were significantly better than the existing VS icons.

It was in this spirit that we talked to the VS team last week to see if there was an opportunity to improve the conditional breakpoint icon in both VS and VS Code. But we weren't in a position to be able to do so because there has been zero feedback about the current icon and, in my opinion, the options we are considering are not significantly better such that a change in VS would be justified.

Like you, we have some reservations about the + sign too but we are constrained a bit by what we can do. For example, a badge in the corner of the icon won't work because the icon is too small for the badge to be clearly visible. We feel that the orange colour is too similar to the red for a regular breakpoint.

Consistency with VS works both ways and works in our favour. We can encourage changes in VS based on what we do and we can adopt some of the best practices that VS has figured out over time. That does not mean that we will become an IDE. But when appropriate, consistency between the tools can work well for each tool. So hence the decision to adopt a consistent icon.

**Comment by stevencl** [comment]
However, having said all that, I will check with the VS debugger UX team one more time to see what scope they have for changing. I'll see what they think about the Swiss flag thing.

**Comment by bgashler1** [comment]
Thanks for explaining the thought process, Steven.

@isidorn: I completely agree with you that this "+" icon is not an ideal icon for conditional breakpoints.  Going with Visual Studio's precedent was not a decision we made lightly.  I tried to convince the VS team that the "+" icon was confusing and that the diamond logo (pictured below and indicated by the green star above it) would be the more ideal solution, since it represents a decision or condition on flow diagrams (a great metaphor).  Unfortunately and unbeknownst to me, a very similar icon was being used already for tracepoints.  So using our top pick would not work, as it would be confusing difference between both products that usually are visually similar.
![untitled-1](https://cloud.githubusercontent.com/assets/11839736/12239921/e3a6966e-b83f-11e5-818c-3d1b8718f035.png)

Your point that it looks much like the Swiss flag is also completely understandable.  I think we should continue to have a dialogue with VS and perhaps do some studies that involve users deciding which icon is more intuitive against a control of the existing icon in VS.  If we could prove a significant improvement, I think we could get VS to change it, as there was no visual design validation that users like the "+" except that no one has complained about it, according to Karl Melder, one of their researchers.

**Comment by isidorn** [comment]
Good points, thanks Brad, Steven.
Let me know once you hear back from the VS people and then I can update our breakpoint from orange to whatever we decide here.

**Comment by isidorn** [comment]
On the other side, if we chose to go with red then we should choose a different color for our breakpoints widget which is currently orange. If I put that to red then it feels weird to me and all seems like an error box so suggestions are welcome. 
But as noted last sprint I also dislike red breakpoints since they feel as errors and would much rather go with blue since they seems to solve this issue and the swiss flag problem.

![screen shot 2016-01-12 at 12 15 47](https://cloud.githubusercontent.com/assets/1926584/12262152/469d3138-b926-11e5-8627-41363f412b90.png)

**Comment by stevencl** [comment]
Good point, Brad and I will work on this.

**Comment by bgashler1** [comment]
@isidorn I agree that red doesn't look right here.  I'll take a look.
