### ISSUE TITLE
Auto close single and double quotes aren't working 

### ISSUE THREAD

**Issue by MetaDevelopment** [microsoft/vscode#161204]
EDIT: I've removed and reinstalled VSCode and now I no longer have this issue. No idea what caused it, but I guess this can be closed now. 

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.71.2 
- OS Version: Mac OS Monterey 12.5 

Steps to Reproduce:

1. Set the option "Auto Closing Quotes" to "always" 
2. Input a single or double quote in a document, for example an HTML-file 

Same issue as #26820 (closed), that had been (partly) fixed, but not working for me: not the open and close quotes nor the wrap quotes. No extensions installed, just a new version of VSCode on a new notebook. I have the Dutch keyboard layout, but I tested it with US layout as well.

**Comment by rafaelbeckel** [comment]
I have the same issue.

I don't know what caused it, and reinstalling did not solve my problem.

All auto-close tags work as expected, except for a single quote or double quote.

Something is clearly overriding it. When it happens, and I press Cmd+Z, the `undo` operation shows both quotes. However, the same thing happens when I disable all plugins.

My auto-close configuration is set to `always.`
