### ISSUE TITLE
No coloring of function return value types in interfaces 

### ISSUE THREAD

**Issue by Franziskus1988** [Microsoft/vscode#1612]
```typescript
interface TestInterface {
  testvar: string <- "string" colored;
```
```javascript
  testfunc(): string <- "string" not colored;
}
```

**Comment by aeschli** [comment]
@Franziskus1988 For what language is that?

**Comment by aeschli** [comment]
I can reproduce in typescript
```typescript
interface TestInterface {
  testvar: string;
  testfunc(): string;
}
```
![image](https://cloud.githubusercontent.com/assets/6461412/12236972/ad24bffc-b87c-11e5-8e12-82054fb74949.png)

The problem is that the `interface` and `the first `string` both get the `storage.type.ts` scope.
We would like to color type names with a different color from the keyword. Maybe give `interface` `keyword` scope instead?

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#44
