### ISSUE TITLE
Watermark should hide when size becomes too small

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#16130]
Noticed this while dragging the bottom panel large enough so that there was not enough space for watermark and logo:

![image](https://cloud.githubusercontent.com/assets/900690/20658322/28986abe-b53c-11e6-89b3-f151022b7dab.png)

In this case I would also expect the watermark to hide.

**Comment by bgashler1** [comment]
@chrmarti this is because we're relying on media queries which only detect the window's height.  I'm wondering if some JavaScript like `window.onresize = function() { }` should be used to turn on/off a class that hides the watermark and repositions the logo.

**Comment by chrmarti** [comment]
There is to be no event for element resizes, only for window resizes. Someone came up with a clever way of using scroll events on invisible 'sensor' elements: https://github.com/marcj/css-element-queries

@bgashler1 Maybe there is a simple way to improve resize behavior with CSS? Otherwise I'd suggest to keep it as is.

**Comment by bgashler1** [comment]
@chrmarti that's too bad we don't have an event for that.  By the way, that's a cool CSS polypill you found.  I think we might have trouble using it, though, (since we use the `file://` protocol for stylesheets):

> **Issues:**
> ... Local stylesheets do not work (using file:// protocol).

We could probably poll for element size changes on an interval using JavaScript whenever there is an empty workspace, I suppose.  Not sure how that would affect performance.
