### ISSUE TITLE
Glitches when backspacing on a remote SSH zsh terminal

### ISSUE THREAD

**Issue by tekumara** [microsoft/vscode#161442]
Glitches when backspacing on a remote SSH zsh terminal... eg: deleted letters repeat themselves

https://user-images.githubusercontent.com/125105/189907407-63633925-e0a4-4e4e-a5d7-6a1ad0983ff7.mp4

## Steps to Reproduce:

1. Install zsh on a Ubuntu remote with:
  - [minimal.zsh](https://github.com/tekumara/setup-ubuntu/blob/64c7479/dotfiles/.zshrc.d/minimal.zsh)
  - [sindresorhus/pure](https://github.com/sindresorhus/pure) terminal prompt
  - [zsh-users/zsh-autosuggestions](https://github.com/zsh-users/zsh-autosuggestions)
(NB: see all my [dotfiles here](https://github.com/tekumara/setup-ubuntu/tree/64c74796e75eed1697cfe6a6af59fb83fba53896/dotfiles))
2. complete an autosuggestion and then backspace

## Details

Version: 1.71.0
Commit: 784b0177c56c607789f9638da7b6bf3230d47a8c
Date: 2022-09-01T07:25:25.516Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 21.6.0
Sandboxed: No

- Remote OS Version: ubuntu
- Remote Extension/Connection Type: SSH

Does this issue occur when you try this locally?: No - i have the same dotfiles locally and it's fine
Does this issue occur when you try this locally and all extensions are disabled?: Not sure

**Comment by david-morris** [comment]
I've had to turn on terminal.integrated.localEchoEnabled back on because on Windows -> WSL -> Docker, the latency grows with uptime and the term can become unusable without local echo.

With the newer versions of VSCode, I've found that local echo will correct itself if you wait for the roundtrip, and if it gets stuck, you can force it to update reliably without losing the line by sending ^L/Ctrl+L/Line Feed.

It's a lot more usable. But it's still frequently moving the wrong number of charachters if you hold a key like backspace or the left arrow.

**Comment by Tyriar** [comment]
Merging into https://github.com/microsoft/vscode/issues/126209
