### ISSUE TITLE
[Intellisence] How to reference auto-fetched typings in my custom typings file?

### ISSUE THREAD

**Issue by Spown** [Microsoft/vscode#16153]
- VSCode Version: 1.7.2
- OS Version: Win10 x64

So now after the new auto-fetching of typings option was introduced structures like ``///<reference path="../nunjucks/index.d.ts" />`` obviously won't work in a custom ``.d.ts`` file if no such typings were installed manually. If I understand it correctly the auto-fetched typings reside under ``%APDATA%\Local\Microsoft\TypeScript\node_modules\@types\`` and these ``.d.ts`` contain tripple-slash refs with the key ``types`` (like ``/// <reference types="serve-static" />``). I couldn't find any documentation for that anywhere (much less in the [official ts docs](http://www.typescriptlang.org/docs/handbook/triple-slash-directives.html)). Using such ref in my custom ``.d.ts`` ~doesn't seem to work, even~ only if I copy the whole ``node_modules\@types\[module_name]`` folder into the location where my custom typings file resides (and also after some time delay).

Is it even possible? If not then consider it as request. Like f.e.
```
///<reference path="${auto-fetched-typings}/nunjucks/index.d.ts" />
///<reference auto-fetched-typings="nunjucks" />
```
Or something...

Thanks

**Comment by mjbvz** [comment]
Adding explicit references to acquired typings files is not supported and this is by design. Automatic Typings Acquisition is used to power our intellisense and other editor features. It happens behind the scenes using the Typescript server, so your code should not rely on this behavior or the presence of these typings files.

To manually manage typings, try adding the target `@types` packages to your `package.json` like so:

```
"dependencies": {
  "@types/nunjucks": "0.0.32"
}
```

This is the same package that typescript downloads behind the scenes for automatic typings acquisition.

Please let me know if you have any other questions.

Thanks.

**Comment by mhegazy** [comment]
Please find more documentation about this in http://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#dependencies

**Comment by Spown** [comment]
thank you
