### ISSUE TITLE
[folding] Folding is "jumping" when a file is opened in 2 windows

### ISSUE THREAD

**Issue by abMarlim** [microsoft/vscode#161647]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.71.2
- OS Version: MAC Monterey 12.6

Steps to Reproduce:

Before this last update it was common for me to use a file opened in 2 windows, "fold" the functions of window 1 and leave only what I wanted while looking for parameters or other things to use in window 2 for example in other functions.

However, now if I change anything in both windows, the "cursor" jumps to where it was changed and no longer respects the "folding" in the previous window, as shown in the images below.

**1 - somefunction2 window 2** - If I change something, window 1 "lose folding" previous
![1](https://user-images.githubusercontent.com/57630985/192057223-b7a87480-fe91-462d-ac3b-d1cc12bc9cd6.gif)

**2 - somefunction1 window 2** - If I change something, window 1 "lose folding" previous
![2](https://user-images.githubusercontent.com/57630985/192057259-cd3a9546-f8ed-4834-bd95-5a478e7695fa.gif)

Is there any configuration to keep the feature prior to this update?
Thanks.

**Comment by aeschli** [comment]
Yes, I can reproduce. 
This was an intentionally change, but we didn't think of the split screen scenario
The idea is that if we detect that a folded range has gotten larger (or smaller), we expand it.
https://github.com/microsoft/vscode/blob/eab981234f42194a815a62af1aeaa39d450614c8/src/vs/editor/contrib/folding/browser/foldingRanges.ts#L332
FYI @PieterBranderhorst

**Comment by abMarlim** [comment]
Hey @aeschli,

Thanks for the answer, do you think we will have any option to disable this change? I believe the old format helps a lot when there are multiple codes in a single file and split screen is needed.

**Comment by PieterBranderhorst** [comment]
@aeschli I don't think the line you identified is the culprit here. I think this is happening because of the following code in foldingModel.ts:

`	if (isCollapsed && (isBlocked(decRange.startLineNumber, decRange.endLineNumber) || decRange.endLineNumber - decRange.startLineNumber !== foldRange.endLineNumber - foldRange.startLineNumber)) {`

I don't know why the test for a change in the size of the range is there. I think that just testing for `if (isCollapsed && isBlocked(...))` would be correct. But I'm not 100% sure. Can you think of a reason for the decorated range to change which would require that we unfold? I've done a test with 
` || decRange.endLineNumber - decRange.startLineNumber !== foldRange.endLineNumber - foldRange.startLineNumber
`
removed from that line and the split view then behaves properly, not auto-expanding things.

It would be a different matter if the range returned by the folding provider changes, i.e. the test you identified. I think unfolding is correct in that situation.

**Comment by abMarlim** [comment]
Hey guys, any news? I updated to version 1.72.2 and the problem still persists, in fact this is very annoying 😞

**Comment by PieterBranderhorst** [comment]
@aeschli Nudge

**Comment by OziOcb** [comment]
@aeschli, are there any plans for fixing this issue? As a Vue dev, I must admit that this auto-expanding behaviour is super annoying when working with single-file-components.

**Comment by aeschli** [comment]
I'll look at it in November.

**Comment by ddenev** [comment]
@aeschli , I have updated VSCode to 1.75.1 and this is still a problem - the issue I described in #159646 is still the same. So it doesn't seem fixed.

**Comment by aeschli** [comment]
The fix will be in 1.76
