### ISSUE TITLE
Dynamic code evaluation for vscode hacking

### ISSUE THREAD

**Issue by noxdafox** [Microsoft/vscode#16160]
The core feature which is keeping me with Emacs is its dynamic code evaluation property.

Whenever I want to change the editor behaviour, I open an empty buffer, I write some code, I evaluate it and it's ready to be used. I use the editor itself for a while and if I like the new functionality, I add it to my default configuration.

Is this even possible with Visual Studio Code? It would indeed speed up extension writing significantly.

The workflow I picture in my mind would be: opening an empty file, writing a bit on TrueScript language and evaluating it. If it works I'd add it to my personal extension. If I think it would be useful to the community I'd publish it in the Marketplace.

**Comment by noxdafox** [comment]
Any reason this got closed? 

Was it implemented?
Is it invalid?

**Comment by jrieken** [comment]
Yeah, we have a new rule that issues labeled as `extension-candidate` get closed. That doesn't mean they are lost or worth less but it just to reduce the amount of issues we daily look at and just because they won't be fixed in this repo. We will setup dedicated queries for extension candidates and encourage people to look at them.

Thanks and Happy Coding

**Comment by noxdafox** [comment]
Makes sense. thanks
