### ISSUE TITLE
`Invalid model for label change, rebuilding`

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#161788]
For me on macOS:
* open a folder with 1 file `Test.go`
* right click rename to `test.go`

=> console prints `Invalid model for label change, rebuilding`

**Comment by lramos15** [comment]
This is interesting, the reason this is happening is because the label change doesn't trigger and open and close if it's the same URI with different casing, but our IDs are case sensitive so when we go to look up this tab to update it's label we go "hey we can't find it, it must not exist". Is there a case insensitive version of the URI that I should be using? Right now I use `EditorResourceAccessor.getOriginalUri(editor, { supportSideBySide: SideBySideEditor.BOTH });`

**Comment by lramos15** [comment]
Ah, canonical URIs is what I want. A bit weird that uppercase to lowercase triggers a label change, but not the other way around 🤷‍♂️
