### ISSUE TITLE
Test extension logging API

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#161786]
Refs: https://github.com/microsoft/vscode/issues/159892

- [x] any @mjbvz
- [x] any @lszomoru 
- [x] any @alexr00 

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23161786%0A%0A&assignees=sandy081)

---

[Proposal](https://github.com/microsoft/vscode/blob/1dd67592e120d916a8963903babaf0fae74440c5/src/vscode-dts/vscode.proposed.extensionLog.d.ts#L1)

We now have a proposed API for creating a log output channel where you can log messages with different log levels. Only messages those meet the current product log level are logged just like the product logs. Logs are restored on reload just like window and extension host log.

Test the proposal either by adopting in your extension (preferably) or in a sample test extension

**Comment by alexr00** [comment]
I was only able to test `info`, but `info` worked great!

**Comment by sandy081** [comment]
@alexr00 Thanks for testing and fixed logging other log levels too.

**Comment by lszomoru** [comment]
I have looked at this for the `git` extension but it needs a little more work as probably we will have two "channels": 1) git commands, 2) extension logs. I have filed some issues with some additional features that would be very nice to have. I have also filed https://github.com/microsoft/vscode/issues/162185 so that complete the adoption next milestone.

**Comment by mjbvz** [comment]
API looks good. Nice work!

After using it, I think I may prefer having a single `.log` function that takes the level as the first argument:

```js
output.log(vscode.LogLevel.Info, "my message", ...)
```
