### ISSUE TITLE
Merge Editor: Merging UI

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#161834]
Refs: 

- [x] anyOS @IanMatthewHuff
- [x] anyOS @chrmarti

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23161834%0A%0A&assignees=hediet)

---

This is an issue to test the general experience in the new merge editor. This is not about the merge editor git-integration.

* Clone https://github.com/hediet/diff-merge-dataset/tree/b5a498ce19c915b4b25f88b53f2d7fe9afcd9843/merges for some samples
* Use the `Load Merge Editor State From Folder` command and select a folder from the cloned repository that has a `base.*`, `input{1,2}.*` and a `result.*` file. In the quick pick, chose `result`. Note that you can also edit any of those files to test the behavior of the merge editor for tricky inputs.
* Play around with the merge editor and report any seemingly buggy or confusing behavior.

**Comment by hpmv** [comment]
My feedback on the new merge UI is that it is a very negative experience and I struggled to produce correct merges even after using the UI multiple times, and the conflicts were simple enough that I could easily produce the intended results without the UI (with just a plain editor). I was doing real world merges in multiple codebases.

Trying to be constructive here but it's unfortunate that UIs like this either clicks or doesn't; for me, it doesn't click at all and I'll try to give some concrete reasons:
 1. The default of having the merged view at the bottom is something I've never seen before and I struggle to understand the rationale (I'm guessing it's to have more screen width?). It makes it difficult to see how the changes line up with the merge result. Luckily there's a setting to change that to the side-by-side three-panel view. I'll talk about this view below.
 2. It's not clear what exactly the middle section is showing. I'm thinking it's the merge result? But then it also has collapsed conflict markers (?) in there which I can't expand and can't easily delete.
 3. When first entering the merge UI for a file (without making any resolutions) and looking at a conflict, I want to understand (a) what is the original content; (b) what did commit A do to this content; (c) what did commit B do to this content. I struggled to answer any of these three questions - this is related to point 2, where I don't know what the middle section shows. For comparison here, I love the IntelliJ merge UI because it begins with the middle section showing the original content before either change (including changes that don't have conflicts; the middle section just shows precisely the original content).
 4. Throughout the merge it is not clear which section on the left (i.e. a bracket with a checkbox) corresponds to which section on the right and the center. This is especially the case when there are long conflicts, or if some conflicts have already been manually resolved by editing the center. Some lines that go between the three panels would be helpful here (again IntelliJ does an amazing job here).
 5. When there's a conflict and a section's checkbox shows a dot, it's not clear what exactly happens when I click the checkbox. Does it mean (a) choose this side of the conflict and reject the other side? or does it mean (b) apply this side's change and let me separately decide the other side? For changes that add lines I think (b) seems to be the behavior but overall I'm confused, and I don't know how I should click the boxes to produce the (a) behavior.
 6. The contrast between sections that have conflict and sections that don't have conflict is too subtle (I'm using light theme; the conflict section is a slight orange color but it's hard to tell if I just scroll through a long file).
 7. It's not clear how to navigate to the next conflict. Do the up and down arrows do that? It's also not clear how many total conflicts there are - for a while I was trying to close the merge UI in order to detect whether there are more conflicts. But eventually I discovered there was a counter shown above, but it wasn't obvious. IntelliJ, once again, does well here by showing a little popup when there are no conflicts remaining.
 8. I would like an option (that is easily discoverable; I'm sure it is a setting but then I'd have to Google it) to disable the UI and go back to the plain text editor.

**Comment by hediet** [comment]
@hpmv thanks for your feedback!

Can you please try out the latest insiders of VS Code? We changed many things.

> The default of having the merged view at the bottom is something I've never seen before and I struggle to understand the rationale (I'm guessing it's to have more screen width?). 

[Visual Studio](https://learn.microsoft.com/en-us/visualstudio/version-control/media/git-merge-editor.png?view=vs-2017&viewFallbackFrom=vs-2022), [KDiff3](https://i.stack.imgur.com/tkQup.png), [P4Merge](https://i.stack.imgur.com/I3iJs.gif) (and others) do this too.

But there is a toggle in "..." to change this.

> It's not clear what exactly the middle section is showing. I'm thinking it's the merge result? But then it also has collapsed conflict markers (?) in there which I can't expand and can't easily delete.

It is the merge result, right. We got rid of the conflict markers alltogether.
(Before you could select the text around the collapsed markers and delete it, the collapsed conflict markers would disappear then.)

> When first entering the merge UI for a file (without making any resolutions) and looking at a conflict, I want to understand (a) what is the original content; (b) what did commit A do to this content; (c) what did commit B do to this content.

We have a base view now that allows you to do exactly this. There always have been commands to compare yours/theirs with base, but they are hidden in the "..." context menu (we were thinking of making them more prominent).

> Throughout the merge it is not clear which section on the left (i.e. a bracket with a checkbox) corresponds to which section on the right and the center. 

You mean the border VS Code draws is not strong enough? This is the first time we hear that feedback. Can you add some screenshots to clarify your point?

> When there's a conflict and a section's checkbox shows a dot, it's not clear what exactly happens when I click the checkbox.

We got rid of the dirty state on open. Also, we got rid of checkboxes, now a text explains the current state.

> The contrast between sections that have conflict and sections that don't have conflict is too subtle (I'm using light theme; the conflict section is a slight orange color but it's hard to tell if I just scroll through a long file).

By default, we don't highlight non-conflicts any more (there is a toggle).

> It's not clear how to navigate to the next conflict. Do the up and down arrows do that?

Exactly. We also noticed some users struggled with this, but it is the same concept as in the existing diff editor. We have to think about this.

> I would like an option (that is easily discoverable; I'm sure it is a setting but then I'd have to Google it) to disable the UI and go back to the plain text editor.

We changed the default back to the plain text editor.

**Comment by hpmv** [comment]
Thanks @hediet ! I did try the insider version on a tiny merge, and I did see many of the aspects you mentioned improved! It will be a while till I merge some large changes again but I will certainly give it another try then. Much appreciate you listening to community feedback and addressing them with an open mind!!
