### ISSUE TITLE
when using `dom` renderer, command execution stalls and cursor can be in the wrong place 

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#161970]
Testing #161851
with `gpuAcceleration:off` EDIT or `on`
https://user-images.githubusercontent.com/29464607/192535337-bb6bab6e-8fb8-4315-8d2c-c781124aa284.mov

**Comment by meganrogge** [comment]
![Screen Shot 2022-09-27 at 6 12 29 AM](https://user-images.githubusercontent.com/29464607/192535792-42fd2634-c1cc-4919-9ae2-84f76f3872de.png)

**Comment by meganrogge** [comment]
![Screen Shot 2022-09-27 at 6 13 11 AM](https://user-images.githubusercontent.com/29464607/192535944-e36fc753-9ae5-49c5-81c7-822d6ac0e3ce.png)

**Comment by meganrogge** [comment]
on `bash` the stall is less, but nothing gets printed
![Screen Shot 2022-09-27 at 6 14 55 AM](https://user-images.githubusercontent.com/29464607/192536382-a0b56b63-94e9-485f-86e5-243a399817de.png)

**Comment by meganrogge** [comment]
stalls in `bash` and puts the cursor in the wrong place when I echo though 🤔 

![Screen Shot 2022-09-27 at 6 16 00 AM](https://user-images.githubusercontent.com/29464607/192536621-34e4e6b5-3278-4c40-987d-8caf303cf139.png)

**Comment by meganrogge** [comment]
also happens with `gpuAcceleration:on`

**Comment by Tyriar** [comment]
@jrieken did some change happen around trusted types? The dynamically loaded xterm.js script needs to set inline attributes/innerHTML

**Comment by jrieken** [comment]
> @jrieken did some change happen around trusted types?

No, nothing that I am aware of. Tho, the `charElement. innerHTML = 'Enbsp;": &` assignment (https://github.com/microsoft/vscode/issues/161970#issuecomment-1259488459) should have never worked with trusted types enabled because it's a bare string, not `TrustedHTML`

If you have to use `innerHTML` assignment (which should be the exception) you need to use a trusted types policy and create trusted html through that. This is a sample: 

https://github.com/microsoft/vscode/blob/1643a42b2510f99d524135e270e218c5220731ef/src/vs/editor/contrib/stickyScroll/browser/stickyScrollWidget.ts#L218. 

However, you should try to avoid that and keep things more simple, e.g use `innerText` and/or `appendChild`

**Comment by Tyriar** [comment]
Ah you're right, this was a coding error introduced with underlines: https://github.com/xtermjs/xterm.js/commit/72d18f7d5e
