### ISSUE TITLE
Terminal quick fix title should show the command that should be run

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#161907]
Testing #161846

1. `git checkout -b lalala`
2. `git push`
3. Notice quick fix title is "git push lalala". Title should be what will actually be run `git push --set-upstream origin lalala`

Right now the user does not know what will be run, so it is surprising and does not give confidence.

![Screenshot 2022-09-27 at 10 20 01](https://user-images.githubusercontent.com/1926584/192472878-90950f03-e398-41fa-bf0d-12db1d7d6506.png)

**Comment by meganrogge** [comment]
Not sure if we want to show all of those details - maybe we could on hover of the action?

**Comment by isidorn** [comment]
If you do not want to render all the details then I suggest to render the first n characters and render `...` at the end. That way the user can understand that we only took the beginning

And :+1: for on hover to show the whole thing

**Comment by Tyriar** [comment]
https://github.com/microsoft/vscode/issues/161599 is is about coding convenience, plug this issue. For simple commands like this we should always show the full thing without hover imo (hovering also can't happen on native dropdowns). This will increase the user's trust in the feature

**Comment by isidorn** [comment]
Agreed. We could have a long command cutoff limit - 50 characters for example. After that we can render elipses `...`

**Comment by Tyriar** [comment]
Commands that long are probably too complicated anyway, such as how we free the port which is a little different as it's handled outside of the terminal

**Comment by Tyriar** [comment]
I think we should also show the URL we're navigating to

https://github.com/microsoft/vscode/blob/08578603ee434e8d6574a26f1f83cda98335b2dc/src/vs/workbench/contrib/terminal/browser/terminalQuickFixBuiltinActions.ts#L131

A good example of why this trust is important is because this:

![image](https://user-images.githubusercontent.com/2193314/192646552-2a63b6e2-0ac1-4b65-88e7-8daffe9fe96b.png)

Was navigating to `https://github.com/microsoft/vscode/compare/tyriar/wording%20%20%20%20%20%20%20%20remote:To%20https:/github.com/microsoft/vscode%20*%20%5Bnew%20branch%5D%20%20%20%20%20%20%20%20%20%20%20%20%20%20tyriar/wording%20-%3E%20tyriar/wordingBranch%20'tyriar/wording'%20set%20up%20to%20track%20remote%20branch%20'tyriar/wording'%20from%20'origin'.?expand=1` due to a bug (https://github.com/microsoft/vscode/issues/162074). If a user clicked "Create PR" and they go there, they may never use the feature again
