### ISSUE TITLE
AAC audio tracks in mp4 files are not supported

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#162062]
Testing #161823

1. play an mp4 file with audio in vs code
result - video plays, but the speaker icon is disabled and no audio plays

**Comment by mjbvz** [comment]
This is likely because the mp4 you were playing has an audio track format that we don't support (such as `aac`). I tested with a mp4 using an mp3 audio track and sound worked find

From a quick search, don't think we can easily figure out if the audio track of a video is supported or not (although [`audioTracks`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/audioTracks) may help in the future)

@deepak1556 @isidorn Is `aac` support something we could explore since it's pretty a common audio format for mp4s?

**Comment by isidorn** [comment]
@mjbvz we can not support `aac` since we did not get CELA approval after they did the review.

**Comment by xgqfrms** [comment]
# ferture wanted 👀

> not support `audio` with `video`

![image](https://user-images.githubusercontent.com/7291672/196906244-a967bfb1-789c-409e-b38a-2053bf201fab.png)

## refs

```md
Note: Audio is not supported due to limitations on VSCode webview extensions. 
This extension is for video preview only.

```



https://marketplace.visualstudio.com/items?itemName=analytic-signal.preview-mp4

**Comment by isidorn** [comment]
Closing as this will not happen until we get CELA approval.

**Comment by muhammad-mobeen** [comment]
What's the update? It's 2024 now and how on earth this is still an issue?
