### ISSUE TITLE
Debug control's "filter" action has no effect when hidden

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#162004]
Testing #161802

1. Open the debug panel
2. Right click on panel controls to hide the `filter`
3. Now use the `...` to try running `filter` 

![Screen Shot 2022-09-27 at 8 57 11 AM](https://user-images.githubusercontent.com/12821956/192576216-8a762ce0-d303-4f64-b5b4-cd6172728c6f.png)

**Bug**
Nothing happens

**Comment by roblourens** [comment]
That item shouldn't be hideable, I think

**Comment by roblourens** [comment]
@jrieken any ideas here - since we just contribute actions to a common view pane menu that we don't have control over, can I make this single item not hideable, or override this for the Debug Console view to not be hideable?

**Comment by roblourens** [comment]
Or, when I click Filter in the overflow menu it should do a different action like unhide it

**Comment by jrieken** [comment]
Yeah, needs some good ideas. I guess preventing to hide is the best option, esp for the upcoming release. I can look into this

**Comment by jrieken** [comment]
This looks like another strike for [code bunnies](https://humanwhocodes.com/blog/2015/05/14/the-bunny-theory-of-code/) 🐰 This seems to be a pattern across different panels (output, marker, comments, debug etc): register a fake action which doesn't do anything just to get a funnel into rendering something inside the toolbar. E.g [repl filter](https://github.com/microsoft/vscode/blob/42a198b98b279460e1c11310759c4fb34d6be2ab/src/vs/workbench/contrib/debug/browser/repl.ts#L879-L897), [testing filter](https://github.com/microsoft/vscode/blob/f3f9f7a10d877fd2177daec3e1f6054706c7e5bc/src/vs/workbench/contrib/testing/browser/testingExplorerFilter.ts#L245-L254), [markers filter](https://github.com/microsoft/vscode/blob/1643a42b2510f99d524135e270e218c5220731ef/src/vs/workbench/contrib/markers/browser/markers.contribution.ts#L409-L423) etc...

I will attempt a tactical fix that allows to mark an action as fake action so that it won't participant in hiding but there is debt and this should be fixed properly. Being an action for the sake of one specific UI is wrong, users can bind keybindings to these actions, extension can call them etc... They should have default behaviour or not be actions

**Comment by jrieken** [comment]
PR https://github.com/microsoft/vscode/pull/162220 is up to mark these action as fake. Going forward there should be a more straight-forward way of rendering a filter box inside panel headers and/or these action should be more graceful

**Comment by jrieken** [comment]
Closing this and creating an adoption issue to move off the `_isFakeAction` vehicle
