### ISSUE TITLE
Edit Sessions view entry lists repo twice

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#162096]
Testing #161860

Not exactly sure how I ended up with this nested view of the Edit Sessions.

I made a change, ran Store Current Edit Session
Open Edit Sessions view and didn't see an entry for vscode-website after refresh.
Ran Store Current Edit Session a second time.
Now after Edit Sessions view refresh, I see an entry listing vscode-website twice and two nested trees with the changed file

![image](https://user-images.githubusercontent.com/12818376/192665227-1c64bd5d-c8e8-41ec-bfa1-d8d0e04d03f8.png)

**Comment by joyceerhl** [comment]
This was a bug in how the Continue On > Clone Locally flow was implemented on desktop, should be fixed in insiders.

Verification
1. In desktop RemoteHub, open a repo and make some edits
2. Select Continue Working On > clone locally
3. Ensure your changes are successfully applied in the created clone
