### ISSUE TITLE
Outline not collapsed by default

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#162143]
* create a new empty profile
* open explorer
* notice that files, timeline, and outline are all expanded and equal height

This isn't happen as the outline sets itself to [`collapsed: true`](https://github.com/microsoft/vscode/blob/044571548e0268d0e4f09300a05887e4495b84a8/src/vs/workbench/contrib/outline/browser/outline.contribution.ts#L28)

<img width="1253" alt="Screenshot 2022-09-28 at 11 33 55" src="https://user-images.githubusercontent.com/1794099/192744665-431883ec-6013-4c5b-aa2a-475f99040674.png">

**Comment by sandy081** [comment]
What was the state of these view before creating the profile? A profile does not include the workspace state. So if these views are expanded before, then they will remain expanded as the collapse state is stored in workspace.

**Comment by jrieken** [comment]
Timeline is the bottom panel, outline in the hidden aux-side-view

> What was the state of these view before creating the profile? A profile does not include the workspace state.

TBH I am surprised that matters because I expect "create new profile" to start fresh

**Comment by sandy081** [comment]
It seems these views were expanded before and hence they are shown expanded.

Collapse state is workspace state because we do not want views to be collapsed or expanded in other windows when they are collapsed/expanded in one window. We cannot reset the workspace state when a new/empty profile is created because this might be unexpected in other areas like opened editors getting closed. 

CC @bpasero Any insights?
