### ISSUE TITLE
Cleanup / remove `_tarballProxyEndpoints`

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#162109]
We should either make this an official API or find an alternative and remove it from the embedder API:

https://github.com/microsoft/vscode/blob/835d39cfac9ede6c7c90678c8d6c3d4d0171ed6d/src/vs/workbench/browser/web.api.ts#L181-L185

**Comment by joyceerhl** [comment]
To summarize:
- We have this option _tarballProxyEndpoints that is currently in core and part of the web api
- It doesn't look like it's going away anytime soon
- We have a way to clean it up by moving knowledge of it to the embedders rather than keeping it in core

Action items:
- [ ] Register new command `_remotehub.getTarballProxyEndpoints` in embedders
    - [ ] vscode.dev (fyi @joaomoreno)
    - [ ] github.dev (fyi @jkeech)
- [ ] Ensure both embedders' changes are deployed
- [ ] Adopt this command in RemoteHub
- [ ] Remove knowledge of old options in embedders, RemoteHub, and core
