### ISSUE TITLE
JavaScript Syntax highlighting bug when having forward slashes and parentheses

### ISSUE THREAD

**Issue by VPenkov** [Microsoft/vscode#16218]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:06:37.428Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.0.18|
|project-manager|alefragnani|0.12.2|
|npm-intellisense|christian-kohler|0.1.4|
|path-intellisense|christian-kohler|1.1.0|
|jshint|dbaeumer|0.10.15|
|vscode-eslint|dbaeumer|1.1.0|
|githistory|donjayamanne|0.1.2|
|LogFileHighlighter|emilast|1.0.0|
|auto-rename-tag|formulahendry|0.0.8|
|theme-karyfoundation-themes|karyfoundation|10.0.0|
|jscs|ms-vscode|0.1.9|
|node-modules-resolve|naumovs|1.0.2|
|vscode-icons|robertohuertasm|4.0.2|
|final-newline|samverschueren|0.3.2|
|whitespace|sandcastle|0.0.4|
|stylelint|shinnn|0.20.2|
|guides|spywhere|0.5.1|
|colonize|vmsynkov|1.0.1|
|gitblame|waderyan|1.3.0|

---

Steps to Reproduce:

1. Open a new JavaScript file
2. Paste the following piece of code:
```javascript
function test() {
    var result = 1 / (2 / (3 + 4));
    return result;
}
```
3. My code appears as a comment as seen below:
![image](https://cloud.githubusercontent.com/assets/1693651/20710729/67d5fce2-b644-11e6-9a34-8c614b117c4c.png)

**Comment by mjbvz** [comment]
Thanks. I believe this is fixed in the latest insiders builds:

![screen shot 2016-11-29 at 9 43 06 am](https://cloud.githubusercontent.com/assets/12821956/20721596/3fef0c7c-b618-11e6-9f33-0be33b4c78b7.png)

1.7.2 is below, with 1.8 insiders shown above.

Please give one of the [1.8 insiders builds](https://code.visualstudio.com/insiders) a try and let me know if you still see this issue.
