### ISSUE TITLE
Bugged Highlighting in Javascript in all '(default ...)' Themes

### ISSUE THREAD

**Issue by Tigerwulf** [Microsoft/vscode#16215]
- VSCode Version: 1.7+
- Mac

For singleton i use a not really comment syntax and with that syntax the Color Theme is little bit bugged. The bug is only in the Default Theme, like 'Dark+ (default dark)' or 'Light+ (default light)'.

Steps to Reproduce:

1.  add the lines of code:
const fooSingleton = new (class fooSingleton{
    constructor() {
        let foofoo = {};
    }

    foo() {
        //Do somthing
    }
})();
2. Use 'Dark+ (default dark)' Color Theme for Javascript

Example:

VS Code version 1.7.2:
![dark default_v_1-7-2](https://cloud.githubusercontent.com/assets/9695586/20708850/2ee9d12c-b632-11e6-8236-3a0497bd94b4.png)

VS Code version 1.6.1:
![dark default_v_1-6-1](https://cloud.githubusercontent.com/assets/9695586/20708851/2eef13f8-b632-11e6-9b41-4ba85d54ea48.png)

**Comment by mjbvz** [comment]
Thanks. I believe this is somewhat fixed in the latest insiders builds:

![screen shot 2016-11-29 at 9 45 04 am](https://cloud.githubusercontent.com/assets/12821956/20721674/902fedc8-b618-11e6-97b7-4a321df19c9f.png)

1.7.2 is below, with 1.8 insiders shown above.

Keywoards inside the class (such `class` and `constructor` and `let`) are still colored incorrectly. The colorization should be the same as if the class were declared at a top level:

![screen shot 2016-11-29 at 9 47 37 am](https://cloud.githubusercontent.com/assets/12821956/20721783/ea82ed02-b618-11e6-8599-9b92a87c0a98.png)

**Comment by Tigerwulf** [comment]
I just check this with the new insider version and yes the bug is fixed. Hope it will come with the next release version. Good work, thanks for that
