### ISSUE TITLE
Revisit toolbar action wiggling when menu is opened

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#162292]
I recently noticed an animation to indicate toolbar actions can be changed:

![Recording 2022-09-29 at 06 34 49](https://user-images.githubusercontent.com/900690/192939775-abfd808c-f675-45f9-95eb-85ab0999eea6.gif)

This seems to be inspired by Safari toolbar when you edit it:

![Recording 2022-09-29 at 06 36 13](https://user-images.githubusercontent.com/900690/192939902-3731127f-e2b1-4d72-bd07-5916cd8cc554.gif)

I am seeing a few issues with our approach:
* we allow to change visibility of actions in a lot of places (activity bar, status bar) where currently there is no such animation
* in Safari to get into this mode, the user explicitly picks an action "Customize Toolbar" while for us it starts on right click already
* in Safari you can actually grab an action and move it, I even think they only animate the action to make that more obvious (not so much the fact that you can hide the action)

I would vote for not having the animation until we can support what Safari does including to drag and reorder actions.

I think the menu makes it already clear what the right click gesture allows you to do:

<img width="299" alt="image" src="https://user-images.githubusercontent.com/900690/192940337-dc7d3666-352a-4b90-b90a-208286275567.png">

**Comment by roblourens** [comment]
Yes, thanks, this feels very strange to me. I don't think animating the whole menubar make sense when you are only operating on a single item.

**Comment by gjsjohnmurray** [comment]
How about beginning a right-click menu with an inactive entry that acts as a header? Something like "Button Visibility". It would also act as a protection against accidental hiding, since I can imagine some folk inadvertently pressing right button down, moving the mouse a few pixels right, releasing the button and seeing vanish the button they intended to actuate.

Especially on Linux where there's a longstanding issue about this happening on context menus at certain Zoom levels and certain places on the screen.

**Comment by jrieken** [comment]
related/motivation https://github.com/microsoft/vscode/issues/161999

**Comment by jrieken** [comment]
>  I don't think animating the whole menubar make sense when you are only operating on a single item.

Well, strictly speaking you operate on the whole menu because you also have toggle actions for all its entries. 

> How about beginning a right-click menu with an inactive entry that acts as a header? Something like "Button Visibility". 

I like that direction. We already do something similar to right click the overflow item. You cannot hide that but you get a disabled "Hide" entry for consistency. On the flip side it is bogus use of menu items as "headers"

<img width="340" alt="Screenshot 2022-09-29 at 08 23 30" src="https://user-images.githubusercontent.com/1794099/192954701-0f9a3d65-2bf8-43bd-a800-3c6d68b25604.png">

---

Overall the motivation for same kind of animation is mostly the `...`. Left and right click show a context menu which do very different things but look very similar

**Comment by gjsjohnmurray** [comment]
Any scope for changing the button icon when in this edit mode? Maybe to pencil or gearwheel.

**Comment by Tyriar** [comment]
Note that animations like this look pretty terrible on standard DPI monitors due to the blurriness. It also removes sub-pixel anti-aliasing which makes it look even more different to non-animating.

![Recording 2022-09-29 at 03 42 49 (1)](https://user-images.githubusercontent.com/2193314/193011128-beffcace-72a7-4480-b2e0-1927e785e116.gif)

Regular:

![image](https://user-images.githubusercontent.com/2193314/193011308-13672bc8-c05c-482d-8bdb-01aad43966b2.png)

Animating:

![image](https://user-images.githubusercontent.com/2193314/193011376-efc906f1-2882-4850-a30e-811858955a30.png)

**Comment by jrieken** [comment]
> Note that animations like this look pretty terrible on standard DPI monitors due to the blurriness.

@Tyriar is that specific to this animation or something you notice with animations in general?

**Comment by Tyriar** [comment]
@jrieken I also think the spinner looks pretty bad, though it's less noticeable than this

> language status wiggle

I don't think I've noticed this, but any animation like these should have this problem. You can notice it when websites use animations as well, the shift from animated to non-animated is often jarring.

**Comment by gjsjohnmurray** [comment]
> Maybe to pencil or gearwheel.

Or even **spinning** gearwheel 😀
