### ISSUE TITLE
Toolbar actions wiggling animation never stops

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#162290]
**Steps:**
* right click on a toolbar action
* hit ESC

🐛 wiggling does not stop

**Comment by jrieken** [comment]
@bpasero works for me... Would also be surprising because this is controlled by the [`onHide`](https://github.com/microsoft/vscode/blob/ae526a1a3c239d545579b2ecb80885abbd82c782/src/vs/platform/actions/browser/toolbar.ts#L199)-logic of the context menu service


https://user-images.githubusercontent.com/1794099/192961098-4a28edb1-3c48-4ede-9f1c-8e65e1aebe25.mov

**Comment by bpasero** [comment]
Yeah strange, somehow cannot reproduce anymore. I also have that weird issue that when running out of sources, every right click is a left click too. This might cause issues that no one else is seeing...
