### ISSUE TITLE
Badge appearing with "Checking for pending edit sessions"

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#162301]
<img width="70" alt="image" src="https://user-images.githubusercontent.com/900690/192963518-89a09471-744c-4bb7-9c8b-ef53de6f4649.png">

This badge does not go away. I have explicitly turned off edit sessions for this workspace, so it maybe related. Nothing in the "Edit sessions" logs.

**Comment by roblourens** [comment]
I'm  not sure what I need to do to actually get that badge to show up at all

**Comment by roblourens** [comment]
Actually I might have triggered the same issue while verifying another one...
<img width="307" alt="image" src="https://user-images.githubusercontent.com/323878/193351129-464a1ad6-945e-4c85-b450-6b8c745b85b4.png">

- Turn off Edit Sessions on desktop
- Open https://insiders.vscode.dev/github/microsoft/vscode, make an edit
- Continue on > "Reopen on the Desktop"
- I get a prompt to enable edit sessions, I said "continue without my changes" or something like that
- Now I am stuck with this badge

I think the badge is not necessary because I was already prompted to turn on edit sessions and I said no. I shouldn't have a badge that I can only hide by enabling edit sessions. Also from the context menu I can't tell why the badge is there, although the tooltip helps me

**Comment by roblourens** [comment]
> I get a prompt to enable edit sessions, I said "continue without my changes" or something like that

Actually I tried this a couple more times in a different repo and I didn't see any prompt like this... did I imagine that?

**Comment by joyceerhl** [comment]
Choosing "Continue without my changes" configures that preference in a setting `"workbench.editSessions.continueOn": "prompt"` so that users who don't want their edits to end up on our services aren't repeatedly prompted.

If you said "Continue without my changes" you should not have gotten a badge at all. It's possible you are in a bad state on desktop (i.e. there was some state that wasn't cleaned up before but should now be getting cleaned up)--can you repro with a clean user data dir on desktop?

**Comment by roblourens** [comment]
In a new user-data-dir, I can't get the extension URI handler to trigger - I think that's probably a weird issue with using an alternate user-data-dir.

In my default user-data-dir, I don't have that setting set. But I tried again, got the prompt again, picked "continue without my working changes", and I still don't have that setting set and have the badge

<img width="282" alt="image" src="https://user-images.githubusercontent.com/323878/193630867-92042647-b27f-4dbb-92b4-e6bb11942672.png">

**Comment by joyceerhl** [comment]
Oh I think I understand your scenario now. If you have an edit session but choose to continue without your working changes in the source workspace, you should not be prompted to sign in to edit sessions (and I just verified that this is the behavior today). 

But if you said you wanted to continue with changes from the source workspace (if you were not prompted in the source, that is because you already said you wanted your changes when using Continue On before), then go to the destination and say you don't want your changes, then we display the badge and you can't dismiss it until you sign in. This was by design because in this case we did actually store an edit session that is pending.

For this issue I fixed the case where if you:
1. Use Continue On to desktop from web and did not have edit sessions turned on locally
2. Turned on edit sessions when prompted
3. Later turned off edit sessions
then the badge would appear. I just verified that that scenario works as expected.

**Comment by joyceerhl** [comment]
Verification steps for this specific scenario 

1. Use Continue On to desktop from web and do not have edit sessions turned on locally (turn it off locally if it was already on locally; turn it on and off if you already have the badge locally)
2. Turn on edit sessions in desktop when prompted
3. Later turn off edit sessions
4. You should not get the badge
