### ISSUE TITLE
not sure but there might be error or i dnt knw have a look at image

### ISSUE THREAD

**Issue by Rahulshahare** [Microsoft/vscode#16234]
- VSCode Version: 1.7.2 
- OS Version: wndows 8.1

Steps to Reproduce:

we usually use ctrl + + for zooming in  but i saw ctrl + = and as it define for function it work properly, m not sure about is it mistake or wht , if its a mistake then make it correct 
1.   relace  the equal (=) sign with  plus (+) at zooming in option from view on menubar
![vscode](https://cloud.githubusercontent.com/assets/13538433/20723380/49c0a954-b690-11e6-9d91-d69b0624fa80.jpg)
 
2.

**Comment by chrmarti** [comment]
`Ctrl +` is bound too. It is not the primary keybinding and because of that not shown in the menu.

@alexandrudima Maybe we should make that the primary keybinding since zooming out is bound to `Ctrl -`?

**Comment by alexandrudima** [comment]
<kbd>ctrl</kbd>+<kbd>=</kbd> means <kbd>ctrl</kbd>+<kbd>VKEY_OEM_PLUS</kbd>. On the US standard layout pressing <kbd>VKEY_OEM_PLUS</kbd> produces `=`, therefore the label is printed as `ctrl+=`. If you would switch your keyboard layout to a different one, the label will print whatever pressing <kbd>VKEY_OEM_PLUS</kbd> produces under that keyboard layout.

We also bind by default <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>=</kbd> and <kbd>ctrl</kbd>+<kbd>numpad_add</kbd> to zooming in. The <kbd>numap_add</kbd> cannot be displayed in the menus because Electron cannot parse the numpad key codes (see https://github.com/electron/electron/blob/master/docs/api/accelerator.md).

Also read more about it in our docs at https://code.visualstudio.com/docs/customization/keybindings#_accepted-keys or https://github.com/Microsoft/vscode/wiki/Troubleshooting-Keybindings
