### ISSUE TITLE
`Go To` could use more words

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#162384]
`Go to 1st Error`?

![Screen Shot 2022-09-29 at 10 08 42 AM](https://user-images.githubusercontent.com/29464607/193103629-37402a6a-78b0-45af-935f-b922f8d20ae5.png)

**Comment by andreamah** [comment]
<img width="140" alt="image" src="https://user-images.githubusercontent.com/31675041/193110057-58c96128-2014-4868-83a0-baea948569f4.png">

We wanted to keep the string as short as possible, since the top bar is really starting to fill up. You can hover the button for more info, though! We thought this would be sufficient for people to know what the button does.
