### ISSUE TITLE
Microsoft Authentication Provider fails to authenticate in sovereign aka national/gov clouds e.g. Mooncake, DoD

### ISSUE THREAD

**Issue by ashishchoudhary001** [microsoft/vscode#162539]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Version: 1.71.2
- OS Version: Windows 11 Enterprise, Version: 21H2, OS Build: 22000.978

Steps to Reproduce:

1. Open PowerPages Studio (https://make.powerpages.microsoft.cn/)
2. Login with correct credentials of a user in Mooncake
3. Launch VSCode for web
4. Notice the authentication popup (the AzureAD endpoint is https://login.microsoftonline.com/ it should have been https://login.partner.microsoftonline.cn/)
5. Since the AzureAD endpoint is incorrect it is not able to find the user.

![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/908570/193502470-1f26e328-53b6-4951-9d6a-25f50f547341.png)

**Comment by TylerLeonhardt** [comment]
Couple of questions I need to answer:
* Can we leave it up to the extension to ask for a particular Cloud? Or does the User have to start a specific "Azure Cloud" flow? (example in the wild: currently the Azure Account extension asks the user to choose Azure or Azure Cloud)
  * If the later, can we do so without disrupting the users flow today since 99% of customers don't know and don't need to know what an Azure Cloud is? (ex: GitHub Enterprise is a separate auth provider that is only enabled if the user applies a setting `github-authentication.uri`)
* Can vscode.dev, a service not hosted in an Azure Cloud, do a POST request to `/{tenant}/oauth2/v2.0/token` or will it be blocked?
* To have confidence, I will want to validate this works in all Azure Clouds. What's the process for getting an account in each of these clouds?

**Comment by bwateratmsft** [comment]
The core Azure extensions are considering using the MS auth provider built in to VSCode; this is likely to be a necessary feature for that.

**Comment by bwateratmsft** [comment]
Relating to the questions that @TylerLeonhardt raised, I can offer some insights from how the Azure Account extension does things.

There are two ways to log in to a sovereign cloud in the Azure Account extension. The first is to set some VSCode settings, and then log in. The second is a separate login command, "Log in to Azure Cloud...", which first prompts for which sovereign cloud to log in to, and then sets the setting, and then proceeds with login as normal.

I think that both a setting in the auth provider extension _and_ an input hack like `VSCODE_CLIENT_ID` would be helpful. The former would be ideal for users that want to configure every Azure extension all from one place. The latter would be good if there was an extension that wanted to reach "across" to a separate sovereign cloud. I saw in source code that the default login URL, `microsoftonline.com`, is hardcoded; I think that the default could be controlled by the setting, while including the ability to override with something like the `VSCODE_CLIENT_ID`.

@jingloumsft I know we have some sovereign cloud accounts for testing, can we share these with Tyler?

**Comment by jinglouMSFT** [comment]
@bwateratmsft mooncake probably but not Fairfax. Pls talk to me when you need this.

**Comment by TylerLeonhardt** [comment]
@bwateratmsft on the GitHub auth side, we have GitHub Enterprise Server support which uses the `github-enterprise.uri` setting that the user sets in their settings and enlightens the GitHub Auth extension to register an additional Auth Provider that uses this URI as the base instead of github.com...

I wonder if a similar pattern for the sovereign clouds could be used:

```
"microsoft-enterprise.cloud":"Mooncake" // or "Fairfax"
```

and then we register a Mooncake Auth Provider that you could consume. `getSession('microsoft-enterprise', [...])` and that would return sessions based on Mooncake.

**Comment by bwateratmsft** [comment]
I'd have to think about it some more but at first glance I'm not sure I like the idea of having a separate auth provider (i.e. `microsoft-enterprise`) for sovereign clouds.

**Comment by TylerLeonhardt** [comment]
99 percent of the time, Sovereign Clouds won't be used. Esp since at the moment, the majority of folks use the Microsoft Auth provider to sign in to Settings Sync, something that Sovereign Clouds shouldn't be able to sign in to as our Settings Sync server is hosted outside of those clouds.

Today, you cannot (and shouldn't be able to) use your GH enterprise account to sign in to Settings Sync and Sovereign Clouds align with that thinking.

**Comment by bwateratmsft** [comment]
> the majority of folks use the Microsoft Auth provider to sign in to Settings Sync

Good point. For the purposes of "let all the configuration be in one place", do you expect extensions to use the presence of a value for `microsoft-enterprise.cloud` as an indication that they should use the `microsoft-enterprise` auth provider instead of `microsoft` (assuming that they care about sovereign clouds)?

e.g. should the Azure extensions use that setting to indicate that the user wants to use sovereign clouds instead of public for Azure resource management?

**Comment by TylerLeonhardt** [comment]
> e.g. should the Azure extensions use that setting to indicate that the user wants to use sovereign clouds instead of public for Azure resource management?

Likely. This is what we are doing in the GitHub Pull Request Extension... although there, there are other signals that are used to help decide when a user wants GHES.

I'm thinking that Azure extensions can still have their quick pick "Sign in to Azure Cloud" which either:
* sets the setting thus triggering the Microsoft Auth extension to register the `microsoft-enterprise` auth provider... then you can call `getSession('microsoft-enterprise'...)`
* we always register `microsoft-enterprise` then when you do `Sign in to Azure Cloud` that calls `getSession('microsoft-enterprise')` which then shows a quick pick to choose the cloud and then we save the setting for future `getSession` calls

The former is what we do for GHES... and I understand it is a bit more indirect... but then we don't have to register an auth provider that will rarely be used... so I'm inclined to lean that way.

The other option is we ship another extension that activates on `microsoft-enterprise` but that would be quite a refactoring in order to share code.

**Comment by bwateratmsft** [comment]
Shouldn't the auth provider extension _always_ register both auth providers?

**Comment by TylerLeonhardt** [comment]
in order for the extensions to activate as fast as possible, registering both would be extraneous for most users.

**Comment by bwateratmsft** [comment]
Fair enough, but wouldn't we only be talking about a couple microseconds?

**Comment by TylerLeonhardt** [comment]
Yeah it's worth profiling on my end.

**Comment by TylerLeonhardt** [comment]
Also GCC-H clouds are a thing. Just wanted to call that out as I am merging an issue about that with this issue.

**Comment by bwateratmsft** [comment]
I'm currently discussing with @isidorn and we talked about adding an optional `providerOptions?: unknown` object to the `vscode.authentication.getSession` API. Or, packing additional options into the existing `[AuthenticationGetSessionOptions](https://code.visualstudio.com/api/references/vscode-api#AuthenticationGetSessionOptions)` object that gets passed along to the provider.

There is already an implicit contract that each provider has to "declare" with respect to scopes--scopes will mean different things to different auth providers. I don't think it's a problem to have an additional implicit contract that the auth caller and auth provider know about, without VSCode needing to know.

**Comment by TylerLeonhardt** [comment]
@bwateratmsft yes I want that for this as well: https://github.com/microsoft/vscode/issues/115626

**Comment by bwateratmsft** [comment]
Nice! Great minds think alike :smile:

I think the signature of `providerOptions` in your draft could be made more generic, i.e. `unknown`, assuming that there aren't problems with crossing process boundaries or something.

**Comment by TylerLeonhardt** [comment]
@stgarf-sx how are you using this account? The fix for this was to offer a new auth provider called `microsoft-sovereign-cloud` and an extension has to leverage this auth provider. Do you work on an extension?

**Comment by TylerLeonhardt** [comment]
@stgarf-sx LiveShare has to intentionally make a change to support sovereign clouds so I doubt you are leveraging this change. (Telemetry says that no one is yet)

So when you initiate a sign in, login.microsoftonline.com opens, right? And do you but your Sovereign Cloud email in there? I'm still wondering how you're getting this error through the normal public cloud flow.

**Comment by TylerLeonhardt** [comment]
> At the login screen when I enter my email I am redirected to our on-prem ADFS for SSO then redirected

Ah so I need to figure out how to make sure you don't redirect in that flow...

**Comment by TylerLeonhardt** [comment]
@stgarf-sx I just thought of something for you to try out for me... can you give this a go:

* Install [my Fugio extension](https://marketplace.visualstudio.com/items?itemName=TylerLeonhardt.fugio) which I made specifically for testing out auth providers
* Set the setting `"microsoft-sovereign-cloud.endpoint": "Azure US Government"`
* run the command `Fugio: Mint token`
* put `microsoft-sovereign-cloud` in the first quick pick
* put `email` in the second as the scope
* See if you are able to get through the flow alright

Btw, when you set the setting to US Gov... we use this url to log you in:

```
https://login.microsoftonline.us/
```

Is this the normal url you see when you get redirected?

**Comment by TylerLeonhardt** [comment]
Glad to hear that my extension works. This means we _can_ get to a good state!

> I still believe the login flow was working for me previously as well but the returned data wasn’t being properly processed/handled by the Live Share extension probably?

Yeah if it was working previously, I'm suspicious of the Live Share resource `9bd5ab7f-4031-4045-ace9-6bebbad202f6/all`... unfortunately, the Live Share team has the control over this resource, not I...

Have you gotten an issue going over here?: https://github.com/MicrosoftDocs/live-share/issues

@jramsay looks like the configuration of the Live Share resource might not work right for Sovereign Clouds.
