### ISSUE TITLE
No end of support prompt while installing latest version on Windows 7 (64 bit)

### ISSUE THREAD

**Issue by mdibnjihan** [microsoft/vscode#162524]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.70
- OS Version: 6.1 (Build 7601: Service Pack 1)

Steps to Reproduce:

1. Hi, I uninstalled Visual Studio Code a few months ago and during this time the support for Windows 7 was ended for Visual Studio Code. I love VS Code and today I tried to re-install after a few months. I did not know that the support was ended for Windows 7. The program installed (downloaded the latest version) but did not open at all. After doing some research, I got the point.
2. My suggestion is it would be better if it gave a prompt like "This version is no longer supported on Windows 7" and block the installation. I think it would remove the confusion and also provide a better information on what's going on. Thanks, and take love <3

**Comment by yume-chan** [comment]
> Is Windows 7 missing some features required by VS Code?

Yes, Electron uses a patch for libuv to maintain compatibility with Windows 7 for a long time.

> I would like to know is there real need to end support Windows 7?

Node.js and Electron already ended their support for Windows 7. Not long ago, Electron had a bug (https://github.com/electron/electron/issues/35219#issuecomment-1247067136) that broke the patch mentioned above, so it no longer runs on Windows 7, and VSCode team also decided to officially end the support for Windows 7.

> By releasing version 1.71 you threw them away.

The bug is minor and now being fixed, so VSCode will work on Windows 7 again after upgrading its Electron version.

But since there is no automatic testing on Windows 7, and no Electron/VSCode developers use Windows 7, this situation can happen again and again, until one day there is a compatibility issue with Windows 7 that can't be fixed (or simply not worth fixing)

**Comment by mightyeagle82** [comment]
Thank you for the answer. I am glad to hear that you do your best to support compatibility with Windows 7.

**Comment by abhiandthetruth** [comment]
@joaomoreno created a PR, can you please review?

**Comment by mightyeagle82** [comment]
Please don't block installation, just show the warning. You said that after the fix it will be support Windows 7.

**Comment by abhiandthetruth** [comment]
@mightyeagle82 minVersion parameter is blocking. We can have custom handling of versions in Code section in InitializeSetup function withing code.iss. I'll try that.
Meanwhile can @yume-chan please confirm if this check has to be blocking?

**Comment by mightyeagle82** [comment]
@abhiandthetruth I think you should give a chance Windows 7 users to use the latest versions of VS Code as long as it is possible according to @yume-chan comment.

**Comment by lorand-horvath** [comment]
Please don't block installation on Windows 7.

**Comment by mdibnjihan** [comment]
[abhiandthetruth](https://github.com/abhiandthetruth) as he did only change the innosetup minversion to Windows 8.
![image](https://user-images.githubusercontent.com/101347202/194801516-bec8fd81-55a0-49cc-9be8-158f08bfdda3.png)
Though, it is awaiting a review to get merged.
You can modify this code if the Electron issue and vscode update the fix for Windows 7. I think it would be better if users switched to some other editor or OS like Win 8/10/11 or even Linux if they really need to use it.
It's better to use a maintained version rather than unmaintained version which somehow works on a platform with a risk that things might break in future due to lack of support and also affecting product impression.
Thank you, take love <3

**Comment by mightyeagle82** [comment]
@mdibnjihan The installer can show the warning that support of Windows 7 is ended and VS Code operation is not guaranteed and . So the product impression won't be affected.

**Comment by joaomoreno** [comment]
Thanks for the discussion, everyone.

Blocking the installation on Windows 7 is the right thing to do here. Regardless of Electron's compatibility, we have made a product decision in terms of what OSs we want to support, and we've decided that Windows 7 is behind us. Besides, allowing to install on Windows 7 will just cause situations of "well, why can't you help me since I was able to install". It's best that we just don't allow to install. Old versions are still available, as usual.

**Comment by lorand-horvath** [comment]
@joaomoreno You could just as easily just update to the fixed version of [Electron 19.1](https://github.com/electron/electron/pull/35702) and it would work without issues on Windows 7. I really don't understand the reason for choosing the path of higher resistance here, instead of simply making a few Windows 7 users happy.

**Comment by mightyeagle82** [comment]
@lorand-horvath More than few. :)

**Comment by joaomoreno** [comment]
> I really don't understand the reason for choosing the path of higher resistance here, instead of making a few Windows 7 users happy.

This is a VS Code product decision. Like any development team, our resources are not infinite and we can't commit to everything. Thanks for understanding.

**Comment by Rike-cz** [comment]
Well I have 8 yrs old high-end Fujitsu ntb with i7, it could work for more than next 4 yrs with no problems with performance, but after Microsoft denied upgrade to Windows 10+ due to some hardware stuff, next you denied upgrading VS Code/Codium due to weird reasons, so my ntb become a waste. This is what you thinking when talking about future, sustainable development, ecology, earth-saving Microsoft?

**Comment by joaomoreno** [comment]
@Rike-cz No one's forcing you to upgrade. Feel free to stay on version 1.70: it will run for a long long time.

**Comment by Rike-cz** [comment]
@joaomoreno I have better solution. Gimme big red alert that I am using unsupported version on my own risk and do not kick me **restrictively** from a stream of upgrade innovations. I will be with Windows 7 as every Linux user - or do you test VS Code/Codium against every possible Linux distro/forks? If someone has Windows 7 and VS Code/Codium together in these days, he knows what he's doing with all consequences. Do not upbring him by denying this service or **being up-to-date**.

**Comment by BuslikDrev** [comment]
I work in Notepad++
