### ISSUE TITLE
Minimap fill/fit is blurry

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#162581]
![image](https://user-images.githubusercontent.com/2193314/193596287-fe83d428-ef5f-4bb2-9178-66b124f815c5.png)

Looks like it's just scaling a texture which ends up looking pretty bad:

![image](https://user-images.githubusercontent.com/2193314/193596316-69929bd8-7b35-4788-a3e5-234d158cb781.png)

vs normal:

![image](https://user-images.githubusercontent.com/2193314/193596343-14a84a33-fdbd-46c6-ad98-c8e22ce595f3.png)

Might be able to disable anti-aliasing and use nearest pixel on scale?

Version: 1.72.0-insider (user setup)
Commit: bcb6c9b7e0e795bdf65ea440025d204060e4bfc8
Date: 2022-09-30T10:53:16.316Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes

**Comment by alexdima** [comment]
@Tyriar Does this happen all the time for you or only under certain circumstances? Are you using `window.zoomLevel` or display scaling in windows desktop settings? We read the pixel ratio [using this code](https://github.com/microsoft/vscode/blob/cb1113ac32862559fde2b724f2eff8d1ba5991d5/src/vs/base/browser/browser.ts#L108-L117) and we monitor it for changing using a CSS media query which should fire when moving the window from one monitor to another or when zooming in.

**Comment by Tyriar** [comment]
This happens on a 100% scale display with a `window.zoomLevel` of 1 when `"editor.minimap.size": "fit"` is set:

![image](https://user-images.githubusercontent.com/2193314/208142829-e1ec7327-ec81-4564-8af9-c3e6ce0f4913.png)

I think it's scaling the height of the minimap to the size of the viewport, which is what leads to the blurriness on the y axis:

![image](https://user-images.githubusercontent.com/2193314/208142987-ef156ee3-0737-407b-8391-9ab1c94e8d4b.png)

**Comment by alexdima** [comment]
Aha! Thanks for the extra information. This is as designed and due to `"editor.minimap.size": "fit"`. When using `fit`, in case the minimap would be larger than the editor height, the minimap is stretched vertically (shrunk).

For example, suppose a minimap line height ends up being 3 (the exact value depends on the screen DPI and the settings `editor.minimap.renderCharacters` and `editor.minimap.scale`). Then, a pixel perfect minimap for a file of 500 lines would take 1500 pixels. And, when using `"editor.minimap.size": "proportional"`, it does. If the editor height is smaller than 1500 pixels, then the minimap also scrolls.

But when using `"editor.minimap.size": "fit"`, the 1500 pixels need to be resized down to fit in the editor's height. This causes it to no longer be pixel perfect.

**Comment by Tyriar** [comment]
Would imageSmoothingEnabled work? https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/imageSmoothingEnabled

**Comment by Tyriar** [comment]
Oh I see, in that case if `image-rendering: pixelated;` doesn't do it (which works on regular images) I doubt it's possible without changing how the drawing is done.
