### ISSUE TITLE
Add "exclude" option for search in context menu

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#162628]
Add an option to exclude a folder in future searches in the context menu. This folder would be added to the "files to exclude" in the search bar.

![image](https://user-images.githubusercontent.com/31675041/193713699-b0e4fe05-f899-4c5c-b929-b3a7a5947390.png)

**Comment by gjsjohnmurray** [comment]
Which context menu do you plan to add to? If one Belonging to search results list/tree, 👍. But if the File Explorer view"s tree, 👎 because it is already long and to add another entry unconditionally will be unpopular with some users. Maybe someday users will be able to hide/show individual items on each menu, just like 1.72 adds for toolbars.

**Comment by andreamah** [comment]
> Which context menu do you plan to add to? If one Belonging to search results list/tree, 👍. But if the File Explorer view"s tree, 👎 because it is already long and to add another entry unconditionally will be unpopular with some users. Maybe someday users will be able to hide/show individual items on each menu, just like 1.72 adds for toolbars.

I was thinking for it within the search context menu, where I think it'll be a lot more used. I was thinking the use case would be when you see some results that you don't want to see in future searches, it could be nice (instead of needing to continually dismiss results).
