### ISSUE TITLE
Consider finding a new PHP grammar

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#162707]
Our built-in PHP grammar is based on https://github.com/atom/language-php, which is no longer maintained. There are a number of open issues, especially around different embedded languages https://github.com/atom/language-php/issues/created_by/roblourens

If there is an alternative well-maintained grammar, we could consider switching to that.

**Comment by KapitanOczywisty** [comment]
Sure I could make a fork, however I feel this is just kicking the can down the road. Above that any dependent project have to be changed (if they even would know and trust potential fork) and you have even worse influence on the repository direction than now. At least you should consider if there is a chance to keep some repositories not-archived in atom organization and get permissions to merge PRs.

With community fork variant, I'd like to know if you, or any vscode team member, would be willing to at least make PR reviews. I can put time to migrate grammar and maintain it, however I feel pushing changes without reviews would be irresponsible, so somebody needs to be on-board with that. And again I think this should be still under some organization account controlled by Microsoft, just to have option to take over "in case".

**Comment by KapitanOczywisty** [comment]
@roblourens I've converted tests to use vscode-textmate instead of atom https://github.com/KapitanOczywisty/language-php/pull/1 It's a crud patch, but will allow to get things moving. Please take a look if you can. I'd like to have also some way to implement highlighting preview to not require contributors to replace php extension in vscode, though this is not that important right now. Other language-* repositories could be converted the same way, will see how it will go.

Update for PHP 8.2 should land somewhere around a new year.

**Comment by KapitanOczywisty** [comment]
@aarondfrancis I'll be maintaining fork at https://github.com/KapitanOczywisty/language-php

**Comment by roblourens** [comment]
Since we have gotten onto https://github.com/KapitanOczywisty/language-php, I will close this
