### ISSUE TITLE
Alert messages covering the tab bar is just a bad idea

### ISSUE THREAD

**Issue by ancientbuho** [Microsoft/vscode#16278]
I've been trying to switch to VS Code for a while, but one single annoyance makes me stop using it: any kind of error or informational message covers the tab bar, making me unable to do anything unless I dismiss it.  This could be a plugin announcing a new feature, or a plugin announcing that there is a warning.  For example, Unity projects always announce warnings when they build, so for every build, the tabs hide behind a message.

One possible solution: an icon appears in the status bar when errors appear. Clicking on it shows them. Clicking outside hides them. 

- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:01:10.756Z)
- OS Version: Darwin x64 16.1.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|theme-realgithub|NoHomey|1.0.4|
|material-icon-theme|PKief|1.0.3|
|theme-dreamweaverweb|Persephona|1.5.4|
|unity-tools|Tobiah|0.1.4|
|unity-debug|Unity|1.1.0|
|theme-onedark|azemoh|0.2.12|
|theme-ezekel|be5invis|0.1.1|
|theme-dracula|dracula-theme|1.2.5|
|theme-karyfoundation-themes|karyfoundation|5.2.0|
|quicksnippet|mousetraps|0.0.1|
|csharp|ms-vscode|1.4.1|
|theme-readable-material-darker|petemill|0.0.2|
|vscode-icons|robertohuertasm|4.0.4|

**Comment by bpasero** [comment]
Messages deserve some UX overhaul imho.

**Comment by soyuka** [comment]
For those who want to know the shortcut to close them it's "shift+esc"!

**Comment by raould** [comment]
+1 this is kind of driving me batty! It is an underwhelming UX element because it doesn't add much help e.g. hyperlink over to build output, as well as it just sort of sticking around in my face.

Another hack fix suggestion: allow the status bar to expand to 2 lines, with the error message being reported in there on its own line. (Thus not as an overlay, as something that expands and reduces the size of the other panels that are all tiled-laid-out together in the window.)

(Thanks for all your great work. I desperately want F# to be able to rule the world, so I really want VSCode to go gangbusters. :-)

**Comment by airtonix** [comment]
alerts/message bar/ popups whatever you guys are calling it... make it configurable:

```
messages.enable = true/false
messages.showAs = [Popover|StatusBarIconPopover|DebugLogEntry]
messages.statusBarIndicator = true/false
```

**Comment by isidorn** [comment]
Closing as dup of https://github.com/Microsoft/vscode/issues/1135
