### ISSUE TITLE
Wrong javascript error

### ISSUE THREAD

**Issue by pollirrata** [Microsoft/vscode#16288]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:01:10.756Z)
- OS Version: Darwin x64 16.1.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|bower|donjayamanne|0.0.3|
|csharp|ms-vscode|1.5.3|

---

Steps to Reproduce:

1. create a javascript function
2. add `return 0;` inside
3. add a break line between `return` and `0`

> Error message is displayed
> severity: 'Error'
> message: 'Unreachable code detected.'
> at: '13,9'
> source: 'js'

<img width="378" alt="screen shot 2016-11-30 at 1 26 49 pm" src="https://cloud.githubusercontent.com/assets/759392/20767648/b60c505c-b700-11e6-951b-b19d887b0a94.png">
<img width="284" alt="screen shot 2016-11-30 at 1 26 08 pm" src="https://cloud.githubusercontent.com/assets/759392/20767649/b65c9404-b700-11e6-9eeb-8a708251cdd4.png">

**Comment by mjbvz** [comment]
The compiler is correct, and this error is actually pretty helpful for catching a common programming mistake.

For a function:

```js
function mul(a, b){
    return
        a * b;
} 
```

[JavaScript will automatically insert a semicolon after the return statement](http://stackoverflow.com/questions/2846283/what-are-the-rules-for-javascripts-automatic-semicolon-insertion-asi), logically rendering the function:

```js
function mul(a, b){
    return;
    a * b;
} 
```

Anything after the return statement is unreachable, which is why the compiler is complaining here.
