### ISSUE TITLE
Consider renaming "Zen Mode" to "Focus Mode"

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#16296]
The term "Zen Mode" may not translate well and might possibly be flagged by PoliCheck tools as it is school of the Buddhist religion.
Consider something like "Focus Mode" or "Editor Only Mode".

**Comment by chrmarti** [comment]
Tagging for November in case of flagging by PoliCheck.

**Comment by isidorn** [comment]
This was already named focus mode but was voted down by the team.
Alternatives are distraction free, focus.
I am personaly for zen mode because it is distincitve and descriptive

@kaiwood @chrisdias @seanmcbreen leaving this one to you to decide

**Comment by isidorn** [comment]
Also @gregvanl can we first check with PoliCheck if this term gets flagged?

**Comment by chrisdias** [comment]
sublime is "distraction free", so the term should be familiar enough. i suggest we use that.

**Comment by gregvanl** [comment]
Looks like PoliCheck won't complain about "Zen Mode". I still recommend using a different term.

**Comment by fbnlsr** [comment]
"Distraction free" is a perfect term as it states what it exactly is. One might enjoy this mode to read a licence text or markdown documentation using this mode, not necessarily to "focus", which is a bit more aggressive term.

**Comment by MatthiasWinkelmann** [comment]
I'd like to quickly add my voice[1] for "Zen Mode". It's evocative, with a hint of creativity & imagination, yet the concept has spread far enough to be understood across cultures. Case in point: Asus probably checked before naming the Zenbook. 

"distraction free" is much harder to parse, because it explains it by starting from its opposite, then negating it. "Focus" is ok, but possibly carries a hint of negative emotions – as in "Not now, I need to focus. Deadline coming up".

Other words that may capture the "state of mind" this feature creates: "Flow", "Bliss", "Pure"

[1]: Understanding full well that I'm but a lowly user, grateful for your work no matter.the outcome of the naming process.

**Comment by isidorn** [comment]
Thanks for feedback.

After discussing with @chrisdias and since Zen Mode passes policheck we decided to not change the naming. As mentioned above similar to Zenbook, zen mode has a unique and creative name which also makes it easier to discover in the command palette
