### ISSUE TITLE
editor.hover.sticky fails if the cursor hovers another popup-generating content while moving in

### ISSUE THREAD

**Issue by waldyrious** [microsoft/vscode#162946]
Version 1.72 included a much needed `editor.hover.sticky` setting (true by default). Thanks to it, [according to the release notes](https://code.visualstudio.com/updates/v1_72#_improved-hover), "the hover will stay visible as long as the mouse is moving towards it".

It seems like even though the mouse may be moving towards the desired link within the popup, if it happens to move over other pop-up generating content, the second popup takes precedence. Here's a screencast to illustrate the issue:
 
![7pT6tpQNLd](https://user-images.githubusercontent.com/478237/194567349-a4feff00-bda8-4b96-94b6-3bf35d4b92fc.gif)

Does this issue occur when all extensions are disabled?: Didn't test

- VS Code Version: 1.72.0
- OS Version: Ubuntu 20.04

Steps to Reproduce:

1. Hover a problematic string whose hover box has a quick-fix link
2. Move the cursor to the quick fix link and pass through another problematic string in the way

This is related to PR #161407 (cc @alexdima)

**Comment by alexdima** [comment]
To tackle this, we would need to add some sort of timing aspect to the logic because we would like to be able to keep a use-case like the following, where the hover comes up on the first squiggle, but then after resting the mouse for a while over the second squiggle, the hover should update to reflect the new location:

https://user-images.githubusercontent.com/5047891/194598431-faabd342-9e5e-4bdc-85e4-3b5a3698e3f6.mp4

Similarly, https://github.com/microsoft/vscode/issues/156749 , might also be addressed with a new timing aspect..

**Comment by aiday-mar** [comment]
Hi ever since this issue was filed, we have added two settings to control the delay for showing the hover and hiding the hover. Namely:

`editor.hover.delay`
`editor.hover.hidingDelay`

This issue will be closed.
