### ISSUE TITLE
Context menu should not remove focus of webview[extension development].

### ISSUE THREAD

**Issue by cweijan** [microsoft/vscode#162909]
Hi, I'm a vscode extension developer and saw that the latest 1.72 version has enhanced the webview context menu, but like the old version, when the context menu appears, the focus inside the webview will be removed, which causes this context The menu can only achieve limited features.

1. Open webview and giving the element the focus:
![image](https://user-images.githubusercontent.com/27798227/194452042-72145109-3dc0-4e49-a7a4-dd3b6ae3a46d.png)
2. After context menu appears, focus inside the webview will be removed.
![image](https://user-images.githubusercontent.com/27798227/194452087-393faaa6-f405-460c-806c-ff9a365fa2db.png)

**Comment by mjbvz** [comment]
Unfortunately this is not something we can really workaround since our custom context menus are outside of the webview element

If this is a problem for your extension, I suggest either:

- Manually track and restore focus 
- Avoid using context menus in this case (or even suppress the existing ones)
