### ISSUE TITLE
HTML color names are not recognized in settings.json

### ISSUE THREAD

**Issue by i207M** [microsoft/vscode#163099]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.72.0
- OS Version: Windows 21H2

Steps to Reproduce:

1. Set any property which ought to be color to an HTML color name, e.g. "white"
2. That line gets a warning, but the setting does take effect

Expected: No warning

Screenshot:

![image](https://user-images.githubusercontent.com/32705083/194744928-e0dc7f3e-b7da-4606-9ae3-d30765cae60a.png)

I'm wondering why VS Code does not support HTML color names, which are supported by almost every browser.

**Comment by sandy081** [comment]
Warning is because that the extension contributing this setting also contributed its schema that does not matches the values you added. Settings file is not an HTML editor it is a general json file and those contributing the settings shall contribute the right schema. So please file issue against the extension.
