### ISSUE TITLE
Cannot open Account menu: unexpected token A

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#163151]
I can reproduce this in my Stable VS Code 100% of the time. I can not reproduce in VS Code Insiders.
Click on the Account icon in the activity bar -> nothing happens 🐛 

Open developer tools console and notice exception

```
ERR Unexpected token A in JSON at position 2: SyntaxError: Unexpected token A in JSON at position 2
    at JSON.parse (<anonymous>)
    at D (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2121:9431)
    at async kc.resolveMainMenuActions (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2786:23490)
    at async kc.run (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2786:22225)
```

**Comment by TylerLeonhardt** [comment]
can you run this simple one-liner and tell me if you get a value?:
```
npx @emacs-grammarly/keytar-cli find-creds -s vscode.login
```

This is using the following open source package: https://github.com/emacs-grammarly/keytar-cli

What you should get is something like this:
```js
[
  {
    account: 'github.auth',
    password: '....... longggg string ......'
  }
]
```
> NOTE: on macOS I got a system prompt to allow this process to access the keychain... that may or may not be the case for you

If that returns a value, then I'm shocked that it did because nothing in core sets that (only embedders do this in the web)... could an embedder be writing to this on accident? 🤔

If it doesn't.... that's also odd since your stacktrace is [pointing here](https://github.com/microsoft/vscode/blob/a2aeb3110a7e5cf2667e312dd5bfca01bb029769/src/vs/workbench/services/authentication/browser/authenticationService.ts#L95)

**Comment by isidorn** [comment]
@TylerLeonhardt I just ran that, and yes I get 
```
[
  {
    account: 'account',
    password: '..... long string ......'  }
]
```

**Comment by TylerLeonhardt** [comment]
verification:

1. Run this: `npx @emacs-grammarly/keytar-cli set-pass vscode.login account asfdkjhasdfhjkadsfjhkdfas`
2. Open vscode insiders
3. log in to an account/open the account menu

It shouldn't throw the error above.
