### ISSUE TITLE
jsdoc multiple generic type doesn't parse right in hover popup

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#163130]
<img width="957" alt="image" src="https://user-images.githubusercontent.com/41773861/194778520-ef8bc4c9-d220-40f3-8850-028355b7d44c.png">

Version info:

```
Version: 1.73.0-insider (Universal)
Commit: fad3a77833b9249158dfd88477114a06435e46a2
Date: 2022-10-07T05:18:56.885Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 21.6.0
Sandboxed: Yes
```

**Comment by Suven-p** [comment]
https://github.com/microsoft/vscode/blob/d53074babf60f0d1b9d93e6c86d130082184f5e1/extensions/typescript-language-features/src/utils/previewer.ts#L87

I think the issue is this line. From what I understand the regex `/^(\S+)\s*-?\s*/` matches  the first word causing split to return 3 element array
0: empty string(cause there is nothing before the first word)
1: the first word
2: rest of the string.

However, `/^(\S+)\s*/` seems to have the same effect. What am I missing?

**Comment by Suven-p** [comment]
> However, `/^(\S+)\s*/` seems to have the same effect. What am I missing?

nvm got it. It is not the same for strings like 'iterable' and 'iterable -'
