### ISSUE TITLE
API: Ability dismiss own showInformationMessage/showErrorMessage

### ISSUE THREAD

**Issue by vanowm** [microsoft/vscode#163298]
Please add ability dismiss own messages.

Here is a use case:
Show error/information message when user entered none-existent path in the settings and remove the message when path is correct.
Yes, we can specify `type: "uri"` for the setting, but this will not allow user to leave the field blank or enter relative paths.

This will also allow us to create temporary messages that would hide themselves after some time.

Currently we can force to close all currently displaying messages by displaying same message 4 times in a short period of time, but that's just a hack that can't be used to dismiss one specific message.

**Comment by jrieken** [comment]
> Since it is common to need to jump several times to find the point of interest, I pop up an information message with Last and Next buttons to support this. 

This sounds like a really great feature. However, you also make the point for why we won't allow to dismiss messages. They aren't meant to be used for such interactions, but for important heads up things that do need interaction. We would rather  give you specific UI contribution points inside the debugger UI than enabling the "kitchen sink UI" which notifications would become by this. 

Btw you can use the `debug/toolBar` menu contribution point to enrich the debug toolbar with any custom command. Won't that be an option for you and what do we need to do so that this becomes an option again?

**Comment by vanowm** [comment]
wait, and you totally ignored the first use case? there is no other useful feature to notify user available, the toolbar messages is the most useless thing ever, unless one stares at it, no human being be able notice anything there if they don't look at it directly.

**Comment by vanowm** [comment]
When VSCode launched with `--disable-extensions` argument it shows information message for 15 seconds then closes it. So, the feature is already there, just not exposed in API?

**Comment by BenHizak** [comment]
Hi All,

Can you please help me understand if this issue (assuming it was implemented) would help in [this case](https://github.com/James-Yu/LaTeX-Workshop/discussions/4940)? 
Briefly it's about frequent errors which occur and are quickly fixed as a user types latex (for example, an unclosed brace). 

Compile-as-you-type generates an error and then fixes it, but the error notification isn't dismissed.

Thank you,
