### ISSUE TITLE
Issue with IntelliSense window only present on Notebooks

### ISSUE THREAD

**Issue by ArielG100** [microsoft/vscode#163221]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

While I'm writing code, when I insert a "comma", the IntelliSense help window is offered, but it keeps covering all future help windows and doesn't show the command suggestions that are hidden behind this window. It only happens in a Jupyter Notebook, not in a normal python file as seen in the video below.

https://user-images.githubusercontent.com/54652541/194437730-5c737271-4481-470a-be75-518f2baaf1c0.mp4

### VS Code Version

Versión: 1.71.0 (user setup) Commit: 784b0177c56c607789f9638da7b6bf3230d47a8c Fecha: 2022-09-01T07:36:10.600Z Electrón: 19.0.12 Chromium: 102.0.5005.167 Node.js: 16.14.2 V8: 10.2.154.15-electron.0 OS: Windows_NT x64 10.0.19044 

### Jupyter Extension Version

v2022.8.1002431955

### Running Jupyter locally or remotely?

Local

**Comment by jrieken** [comment]
That's caused by these lines (equalising all z-indexes of editor widgets)

https://github.com/microsoft/vscode/blob/86f0f9bfa268fe21af7efae37d8f0da1dba8137f/src/vs/workbench/contrib/notebook/browser/media/notebook.css#L18-L21

That breaks the custom-tuned z-index we have for [suggest](https://github.com/microsoft/vscode/blob/36fdf6b697cba431beb6e391b5a8c5f3606975a1/src/vs/editor/contrib/suggest/browser/media/suggest.css#L10) and [signature help](https://github.com/microsoft/vscode/blob/559e9beea981b47ffd76d90158ccccafef663324/src/vs/editor/contrib/parameterHints/browser/parameterHints.css#L8)
