### ISSUE TITLE
Add Portable configuration

### ISSUE THREAD

**Issue by locklose** [Microsoft/vscode#16327]
- VSCode Version:1.3
- OS Version:WIN10 PRO X64

Add the portable version of the settings, to save the configuration and plug-ins to the UserData directory.

**Comment by chrmarti** [comment]
Could you explain more what you want to do? Would this extension solve your case: https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync

**Comment by locklose** [comment]
I need to integrate MinGW and some of the commonly used plug-ins to VSCode.
And save it to a portable device.
When used in other computers, I need to re download the plugin and configure the environment.
It was a problem for me,
Therefore, on the basis of the portable version, added support to read the specified directory configuration and plug-ins.

**Comment by chrmarti** [comment]
You can use `--user-data-dir <dir>` and `--extensions-dir <dir>` as a cli parameters to do that. (See `code --help` for more cli parameters.) Note that it appears that `--extensions-dir` might not be working in the current stable version 1.7.2, but is fixed in the upcoming version 1.8. Also, since you are still using 1.3: I'm not sure if these parameters exist in that version. /cc @joaomoreno

**Comment by joaomoreno** [comment]
#329
