### ISSUE TITLE
Latest release has the incorrect year in title; September 2019 should be September 2022

### ISSUE THREAD

**Issue by remlapmot** [microsoft/vscode#163329]
The latest release at
https://github.com/microsoft/vscode/releases/tag/1.72.1

should surely have the title **September 2022 Recovery** instead of **September 2019 Recovery**.

**Comment by mjbvz** [comment]
Fixed. Thanks!

**Comment by cj81499** [comment]
@mjbvz

The links appear to be incorrect too.

Updates links to <https://code.visualstudio.com/updates/v1_71> rather than <https://code.visualstudio.com/updates/v1_72>

issues links to <https://github.com/Microsoft/vscode/issues?q=is%3Aissue+milestone%3A%22September+2022+Recovery%22+is%3Aclosed> rather than <https://github.com/microsoft/vscode/issues?q=is%3Aissue+milestone%3A%22September+2022+Recovery+1%22+is%3Aclosed>

This is not the first time I have found this kind of mistake (#154394). It might be worth setting up some tooling to ensure this stops happening.

**Comment by mjbvz** [comment]
Fixed
