### ISSUE TITLE
Window freeze when accepting a completion item with the enter key

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#163465]
For certain completions, when I press enter, I notice the VS Code window freezes. This happens consistently for certain completions, requiring the window to relaunch. Unfortunately collecting a profile just shows 100% of the time in `(program)`, so I think this might be a native issue. Let me know if there's extra info I can get on this.

**Comment by Velocity-** [comment]
This has been happening consistently for me too, since approximately when you've reported it.

It's extremely hard to get proper additional information too and it's driving me insane; originally I thought it was related to the rust-analyzer extension, but disabling it did nothing to fixing it.

During this hang, other windows stay responsive just fine, until the process manager (?) notices the freeze and asks if I want to restart the window.

Any guidance on providing the right info (or even where to begin collecting) would help, as the usual paths don't work and attaching a debugger gives absolutely no fruitful results either :(

**Comment by rzhao271** [comment]
Hi, is this issue still occurring on the latest Insiders?

**Comment by connor4312** [comment]
I've not seen it in a while.
