### ISSUE TITLE
Feature suggestion: cursorColumnStart and cursorColumnEnd

### ISSUE THREAD

**Issue by plievone** [Microsoft/vscode#16367]
`cursorColumnStart` and `cursorColumnEnd` or similar would assist in navigating paragraphs quickly. It would always keep the column position and jump vertically skipping white space (beginning of line and end of line). It is especially convenient when navigating indented code, as one can adjust the granularity of movement by moving left/right and then continuing skipping up/down.

I often use `cursorWordStartLeft`/`cursorWordEndRight`, and `cursorHome`/`cursorEnd`, so this would be a nice companion to those.

**Comment by alexandrudima** [comment]
To keep the number of issues in our inbox at a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: we look at the number of votes the issue has received and the number of duplicate issues filed. Thank you for your time and understanding.

If you disagree and feel that this issue is crucial: we're happy to listen and to reconsider.
