### ISSUE TITLE
Feature request: Segmented ts language service?

### ISSUE THREAD

**Issue by unional** [Microsoft/vscode#16361]
- VSCode Version: 1.7.2
- OS Version: doesn't matter. 🌷 

With tools such as [`lerna`](https://github.com/lerna/lerna), it is easy to create one repo with multiple npm packages. For example https://github.com/sencha/extjs-reactor

Currently, ts language service does not work when opening from the root folder (unless you point tsdk to one of the package's typescript lib, but that would be meaningless), and opening from individual package folder makes ts language service works ~~but now git integration does not (because there are no ".git" folder).~~

It is related to https://github.com/Microsoft/vscode/issues/396 but also different as it is specific for one repo + multiple packages scenario.

**Comment by mjbvz** [comment]
In our multiroot design discussions, we've currently settled on using a single typescript server for all folders in a workspace. As you note, this is not a perfect solution since different workspace folders may have different typescript versions, however usually these versions are not substantially different from the language server perspective.

This decision was made for performance reasons. We may revisit it in the future if a large number of users start running into issues caused by this once we roll out multiroot workspaces to mainline

**Comment by unional** [comment]
One significant issue with single typescript server is the 20mb file size limitation as mentioned in https://github.com/Microsoft/vscode/issues/35549

With multiple projects, this limit will be hit much sooner.

**Comment by vilic** [comment]
@mjbvz This is the main issue blocking us from switching to multi-root workspace. We are using Angular and Node.js, and Angular would usually be a slow adapter to newer TypeScript version. And if we want to use the latest TypeScript version for the backend, we have to give up multi-root workspace due to this single language server issue.

**Comment by timm-gs** [comment]
@vilic So multi-root workspaces currently don't support multiple TypeScript instances (and possibly versions) running?

That would be a pity, as in our project initial compilation takes a while, so it would be very desirable to just compile individual packages quickly (the ones one is actually working on) and not the whole project. Also publishing JS npm packages IMHO requires `tsc` to be invoked for just that package, so that the output files are in place (otherwise some linking/copying on top would be needed).

[The above is probably not 100% related to this ticket, but I am trying to understand your and our use case, so we can file specific follow ups where appropriate.)
