### ISSUE TITLE
Notebooks: clicking go to risks restarting the kernel

### ISSUE THREAD

**Issue by Ugzuzg** [microsoft/vscode#163729]
The "Go to" running cell button disappears after the execution is finished, and the "Restart" kernel button takes its place. When you're trying to follow the execution of a notebook by clicking "Go to" button, if the execution is finished, you risk restarting the kernel and losing the final state of the notebook.

Alternatives that could be implemented:
- Always show the "Go to" button, but disable it if there's no active execution.
- Move it to the end of the toolbar, so that when it disappears, you will click on an empty space.

**Comment by roblourens** [comment]
Second time this has come up - https://github.com/microsoft/vscode-jupyter/issues/11451#issuecomment-1275430047 it's still true that showing it all the time may not fix the issue. I can experiment with it though.

**Comment by roblourens** [comment]
Solutions I'd consider

- A confirm dialog for the Restart button
- The Go To button is always visible, and goes to the last executed cell (it does this currently, only for cells that failed)

**Comment by rebornix** [comment]
Another option is Jupyter contributing the restart button to group `navigation/execute` and we increase the order of "Go To" to ensure that restart is always next to Run/Interrupt.

**Comment by roblourens** [comment]
It turns out that we do have a confirm dialog on the Restart button, and it has a "Don't show again" option. You must have picked that at some point @Ugzuzg. We could remove the "Don't show again" option if it causes confusion but I think I am ok with letting users opt to not see the confirm dialog. I don't think we need to mess with the order of the buttons
