### ISSUE TITLE
Why my VS Code version is consuming too much memory?

### ISSUE THREAD

**Issue by MiguelLattuada** [Microsoft/vscode#1638]
**I have three questions:**
- first of all why do I have eight process of VS Code?
  ![code](https://cloud.githubusercontent.com/assets/5618566/11995879/20900ce8-aa37-11e5-9a59-5042827a6715.png)
- then why VS Code is consuming something like 522096KB of memory? Isn't that too much?
- and last, if electron allow 64-bit build why VSC still target 32-bit ?http://electron.atom.io/docs/v0.36.0/development/build-instructions-windows/#64bit-build

**Extra info:**
- I'm running windows 7 ultimate x64. 6GB memory, and this processor http://www.notebookcheck.net/AMD-A-Series-A6-3400M-Notebook-Processor.55753.0.html. VSC version 0.10.6
- I took that screenshot with a small project (12 files, and 18 folders) on VSC, and with no file editing.

**Comment by alexandrudima** [comment]
To keep the number of issues in our inbox at a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: we look at the number of votes the issue has received and the number of duplicate issues filed. Thank you for your time and understanding.

If you disagree and feel that this issue is crucial: we're happy to listen and to reconsider.
