### ISSUE TITLE
Avoid sync fs-calls when opening windows

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#16381]
Like [this](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/electron-browser/main.ts#L119) (already in an async context) and [this](https://github.com/Microsoft/vscode/blob/master/src/vs/code/electron-main/windows.ts#L644)

**Update (bpasero):**
* we still `statSync` files on startup to figure out e.g. the identifier ([here](https://github.com/microsoft/vscode/blob/9f8431f7fccf7a048531043eb6b6d24819482781/src/vs/platform/windows/electron-main/windowsMainService.ts#L921-L921), [here](https://github.com/microsoft/vscode/blob/e5e83321c1c22826a6dce12b04f1f3374feedde8/src/vs/platform/workspaces/electron-main/workspacesManagementMainService.ts#L355-L355)) but these methods are not in an async context unfortunately
* we use sync fs APIs for setting up backups [and before opening windows](https://github.com/microsoft/vscode/blob/4613b417c215d1d514c32beefd81273b46d45dd6/src/vs/platform/windows/electron-main/windowsMainService.ts#L1341-L1350), which is reported in https://github.com/microsoft/vscode/issues/16375

**Comment by jrieken** [comment]
related to #15455

**Comment by bpasero** [comment]
Backup service is no longer writing to its metadata on startup in a way that it blocks the startup. Previously we had:
* an async write very early (async but still blocking)
* a sync write for each window that opens

This showed up as largest block in profiles for me when looking for main process and seems to result in a significant reduction from todays exploration build:

![image](https://user-images.githubusercontent.com/900690/188868545-9346d22a-ce07-4c84-802d-89bde603d0e0.png)

Tracing the remaining sync fs operations, we still do they seem not to be significant:
* [`configureCommandlineSwitchesSync`](https://github.com/microsoft/vscode/blob/5f9946a307aeb94adf6662d2d114067b232aeb8b/src/main.js#L153) - we read `argv.json` on startup to support runtime flags very early and we must set the flags before `app.on("ready")` so imho this is fine
* [`getUntitledWorkspacesSync`](https://github.com/microsoft/vscode/blob/5f9946a307aeb94adf6662d2d114067b232aeb8b/src/vs/platform/workspaces/electron-main/workspacesManagementMainService.ts#L237) - we check for untitled workspaces with a `readDirSync` call since we always restore untitled workspaces
* [`statSync`](https://github.com/microsoft/vscode/blob/5f9946a307aeb94adf6662d2d114067b232aeb8b/src/vs/platform/windows/electron-main/windowsMainService.ts#L1024) - we still check paths to open with a `stat` call to know if the file exists and what type it is (folder vs file)

These remaining ones are not in an async context and I wonder how far we want to push it. I think changing the remaining ones would require us to change to `async` window opening which would probably be a larger undertaking.

**Comment by bpasero** [comment]
And found some more that can actually be fixed, either by removing or since they are in an async context:
* https://github.com/microsoft/vscode/pull/160591
* https://github.com/microsoft/vscode/pull/160593
* https://github.com/microsoft/vscode/pull/160594

**Comment by bpasero** [comment]
Ended up making opening windows async, and thus was able to remove the sync fs calls. We still need to read `argv.json` on startup to configure Electron switches, but the rest is all async now, esp. the initially mentioned `statSync` calls to validate paths to open.

**Comment by jrieken** [comment]
Thanks @bpasero - This issue almost turned 6 🍰 and yielded good speed up
