### ISSUE TITLE
Falhas com git

### ISSUE THREAD

**Issue by davilmaster** [Microsoft/vscode#16405]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:06:37.428Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|

---

Steps to Reproduce:

1.Git sempre falha.. ao fazer alterações depois de um tempo aberto. 
2.Não existe um local para saber o que houve com o processo git.

**Comment by mjbvz** [comment]
translated:

> 1. Git always fails to make changes after a while open.
> 2. There is no place to find out what happened to the git process.

To show messages from git, go to `View -> Output` and then change the output selector to `git`

![screen shot 2016-12-02 at 2 29 27 pm](https://cloud.githubusercontent.com/assets/12821956/20852650/c1d0068a-b89b-11e6-9843-fcc84d1ff721.png)

Please share the output so that we can investigate.

Thanks.

**Comment by mjbvz** [comment]
Closing as we need more information to investigate this.

@davilmaster Please let us know if you are still seeing this and provide some additional information to help with the investigation.

Thanks
