### ISSUE TITLE
SCM: Timeline refresh calls trigger other refresh calls

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#164113]
1. Move Timeline view to under the SCM view
2. Refresh the SCM view
3. Notice the SCM view refreshes

🐛 The Timeline view refreshes as well
🐛 Then, the SCM view refreshes again

![Recording 2022-10-20 at 09 52 45](https://user-images.githubusercontent.com/22350/196889499-a6fa9f73-9e50-4c7b-8af9-51bc33cfa8ab.gif)

**Comment by yiliang114** [comment]
VS Code Will execute the  `git.refresh` command when clicking the refresh button.

https://github.com/microsoft/vscode/blob/9c76d66e695381ac392144bc3ec5c7e21edbb472/extensions/git/src/commands.ts#L380 and https://github.com/microsoft/vscode/blob/9c76d66e695381ac392144bc3ec5c7e21edbb472/extensions/git/src/repository.ts#L1163

Then, it will go into here which causes it refresh twice. After `updateModelState` method is executed, `GitTimeline` will be notified to update. This means that the `run` method will be executed again.
https://github.com/microsoft/vscode/blob/9c76d66e695381ac392144bc3ec5c7e21edbb472/extensions/git/src/repository.ts#L1879

https://github.com/microsoft/vscode/blob/9c76d66e695381ac392144bc3ec5c7e21edbb472/extensions/git/src/repository.ts#L1867

**Comment by lszomoru** [comment]
Here is the sequence of events:
1. Refreshing the SCM viewlet will call status - show progress in SCM viewlet
2. GitTimelineProvider listens to status operations and emit `onDidChange` event
3. GitTimelineProvider provides the timeline items - show progress in Timeline view
    - While providing timeline items it calls `logFile()` - show progress on the SCM viewlet

**Comment by lszomoru** [comment]
I have made a tactical change so that no progress is being shown while running the `LogFile` operation. By doing so, we will not be showing progress in the "Source Control" view while the Timeline is refreshing. This however does not fix the fact that when the Timeline is shown, it refreshes every time `git status` is being executed which is excessive. 

@joaomoreno, one approach that would be valuable in multiple scenarios would be for the `onDidRunGitStatus()`  event  to pass the name of the "Operation" that was executed. This would enable listeners of the event to decide whether they want to do something or not based on the operation that was just executed. what do you think?

**Comment by joaomoreno** [comment]
> @joaomoreno, one approach that would be valuable in multiple scenarios would be for the onDidRunGitStatus() event to pass the name of the "Operation" that was executed. This would enable listeners of the event to decide whether they want to do something or not based on the operation that was just executed. what do you think?

Love it. 👌
