### ISSUE TITLE
Reason for ctrl+q binding to workbench.action.quickOpenView

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#16418]
We just bound ctrl+q to quit the application on Linux, I think it would make sense to bring that to Windows too. Also being very similar to how ctrl+tab works, I find ctrl+q to open the quickOpenView feels a bit weird when ctrl+shift+q opens the debug console. Holding ctrl+q and using arrows feels strange to me.

**Comment by bpasero** [comment]
I assigned it to Ctrl+Q a) because it is one of the few free keybindings on most OS and b) because it is very close to Ctrl+Tab so you do not need to do lots of exercises to navigate between files and between views.

I do not think that Ctrl+Q is the standard keybinding for Windows, that is why I did not assign it there. I am looking at references like these:
* https://support.microsoft.com/en-us/help/12445/windows-keyboard-shortcuts

Best I could find is Alt+F4 as outlined in https://support.microsoft.com/en-us/kb/126449 but most applications I saw use it to close a window, which will only close the application if the last window was closed.
