### ISSUE TITLE
Smart handling of GitHub's remote responses when pushing

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#164105]
GitHub's remote response when pushing a branch already provides a shortcut to create a PR, and even warns about dependabot alerts, or even rejects pushing due to branch protection and secret scanning:

```
> git push -u origin digitarald/branchy

Create a pull request for 'digitarald/branchy' on GitHub by visiting:        
     https://github.com/…/pull/new/digitarald/branchy   

GitHub found 153 vulnerabilities on …'s default branch (3 critical, 29 high, 118 moderate, 3 low). To find out more, visit:        
     https://github.com/…/security/dependabot
```

When users push with VS Code, this information is lost (or at least buried in git output).

Ideas (there might be other responses I am not aware of)

1. Branch protection: https://github.com/microsoft/vscode/issues/169779
2. Secret scanning: https://github.com/microsoft/vscode/issues/169355
3. Create PR: https://github.com/microsoft/vscode/issues/169776
4. Security Alerts: Potential for a security extension.

**Comment by 15MariamS** [comment]
Notes from our meeting today. Super looking forward to collab-ing and making push protection the _best_ dev experience on VS Code!

### Today, we block secrets in GHAS private and public repos
- Over 1k potential tokens blocked per month
- We expect this number to rise in **December** when we introduce [custom patterns for push protection](https://github.com/github/secret-scanning/issues/3167)

### In CY23 Q1/Q2, we'll expand [push protection to free public repos](https://github.com/github/secret-scanning/issues/3013)
- We expect the number of blocks to significantly increase
- Repo admins with secret scanning and push protection enabled will block their contributors from pushing secrets
- All GitHub Free _users_ will also be opted into push protection, by default, so that we protect them no matter which repo they push to

### Goals
- Make the error message as clear as possible to developers so that they can (1) understand why they're blocked and (2) figure out the next step
- Make rewriting commit history as easy as possible for developers, i.e. reverting the offending commit when it's the last commit or stacked beneath newer commits

### Demo videos
- [Secret getting blocked](https://docs.google.com/presentation/d/1DfJcY_4ml47WdAFmvKyDTdHVPqsZYr7P/edit#slide=id.p32)
- [Bypassing and viewing associated alert](https://github.blog/wp-content/uploads/2022/04/4-4-22-sec-post.gif?resize=1910%2C1222)

**Comment by digitarald** [comment]
The concept of git's [`registerPushErrorHandler`](https://github.com/microsoft/vscode/blob/9e0b95f08178d8b0b150f5aa6b4ecdd06bdae201/extensions/git/src/pushError.ts#L9) could be added for handling successful push messages as well, so this area becomes extensible.

**Comment by heyheyhello** [comment]
> buried in git output

Indeed the git output is really really noisy. Unreadable noisy. I'd be happy with being able to just limit the logs to the stdout of the remote to be able to see the "Create MR" link. 

There are settings that seem to hint this would be possible, but I just updated vscode yesterday and the "git.logLevel" went away 😕 

![image](https://user-images.githubusercontent.com/44614862/202557522-1b4c5d43-e93b-4856-b5bf-c272c7c017a2.png)

**Comment by heyheyhello** [comment]
Ok I fixed it for Linux and Mac.

Create a script bash script, I'll use `/usr/local/bin/vscode-git.sh`:
```sh
#!/bin/bash
if [[ $@ = push* ]]; then
    git $@ 2> >(tee /tmp/vscode-git-push)
    if grep -q \'remote:\' /tmp/vscode-git-push; then
        code /tmp/vscode-git-push
    fi
else
    git "$@"
fi
```

Make it executable:
```
chmod +x /usr/local/bin/vscode-git.sh
```

Add it to settings.json so vscode uses it:
```
"git.path": "/usr/local/bin/vscode-git.sh",
```

https://user-images.githubusercontent.com/44614862/202574072-3e8f03ec-ba57-4570-b56c-44313a10d449.mp4

**Comment by digitarald** [comment]
Duplicate of #169355
