### ISSUE TITLE
TypeScript Any-Type Error & Double Error

### ISSUE THREAD

**Issue by zhiyan114** [microsoft/vscode#164391]
Type: <b>Bug</b>

# 1st Error (TypeScript Any-Type Error)

1. Git clone https://github.com/zhiyan114/Firey-Bot
2. Run `npm i`
3. Open VSCode and go to the file `src/services/TwitchHandler.ts`
4. Keep restarting vscode or just make random code edits on that file until the error pops up 

Expected: vscode should determine the correct type for those two line everytime.
Actual: vscode will determine the two line as any type instead of the correct type and throws an error (not 100% of the time but occurs very frequently).
![image](https://user-images.githubusercontent.com/20156291/197410217-d7e02dfa-27aa-4f46-b793-8d36cf9faa1b.png)

Can be temporary fixed by copy and repasting any lines of code or restarting vscode.

Line in question:
```
59. const args = message.split(" ")
66. const userData = await userDataModel.findOne
```
# 2nd Error (Double Error)

1. Git clone https://github.com/zhiyan114/Firey-Bot
2. Run `npm i`
3. Open VSCode and go to the file `src/services/TwitchHandler.ts`
4. Find any variables that is in use and change it to an undefined type (ex: `authUsers[tags['user-id']] = userData._id;` to `authAUsers[tags['user-id']] = userData._id;`)

Expected: The VSCode should warn the user about the error once
Actual: VSCode duplicates the error, making the error counts higher than there is.
![image](https://user-images.githubusercontent.com/20156291/197410725-360c1cf0-d453-4075-9a44-53b29f885f6c.png)

VS Code version: Code 1.72.2 (d045a5eda657f4d7b676dedbfa7aab8207f8a075, 2022-10-12T22:15:18.074Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.85GB (8.45GB free)|
|Process Argv|--crash-reporter-id dfe35c48-5b50-4e83-8700-30eab7d852d1|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
copilot|Git|1.54.7077
discord-vscode|icr|5.8.0
python|ms-|2022.16.1
vscode-pylance|ms-|2022.10.30
jupyter|ms-|2022.9.1202862440
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.10
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
printcode|nob|3.0.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyonecf:30548226
2144e591:30553903
pyindex848cf:30577861
nodejswelcome1:30587005
fc301958:30573243

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by grumd** [comment]
I think I'm getting the same 1st issue in my codebase. Some of my types are not calculating properly and get fallen back to "any". Adding empty lines and saving files fixes it. Restarting vscode also sometimes fixes it. The issue is intermittent.

What's interesting, on my side it doesn't happen with TS 4.7.4. Does happen with 4.8.4. @zhiyan114 can you test it with TS 4.7.4?

**Comment by zhiyan114** [comment]
Hey, @grumd

Interesting enough, the issue is still reproducible under TS 4.7.4.

**Comment by bkniffler** [comment]
Same issue here. Tried 4.8.4 and 4.7.4 and can confirm issue persists on both versions.
Randomly adding new lines will fix the issue, but will also reintroduce.

https://user-images.githubusercontent.com/4349324/200170198-17dc2e14-aeb3-47f6-999c-d0ce3601fcc1.mov

**Comment by mjbvz** [comment]
Unfortunately I haven't been able to reproduce this to investigate further 

If you're still seeing this in the latest VS Code insiders build with extensions disabled, please try collecting the TypeScript server logs:

1. Set `"typescript.tsserver.log": "verbose",`
1. Restart VS Code and reproduce the problem
1. In VS Code, run the `TypeScript: Open TS Server log` command
1. This should open a large log file called `tsserver.log` 

This should help us debug diagnostics are being computed

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

**Comment by grumd** [comment]
@mjbvz My bug indeed isn't reproduced with extensions disabled, but please hear me out.

I have reasons to suspect this is caused by custom themes, which is weird.

My testing process is as follows:
1. Enable my custom theme, open a file, reload VSCode. Wait for TS to load. Hover a keyword:
1.1. ![image](https://user-images.githubusercontent.com/5869818/229926920-2834c32a-71a8-43f0-8d58-b71b8e99a3ae.png)
2. Enable a default theme. Reload VSCode, do the same.
2.1. ![image](https://user-images.githubusercontent.com/5869818/229927189-8059d663-a280-4773-9ad5-d437c76a6755.png)

As you can see with a custom theme enabled, on-hover tooltips don't show types.

Here's the custom theme I'm using: https://github.com/pygaurav/vasuki-dark-vscode-theme/blob/master/themes/vasuki-dark-theme.json

Can it be caused by something weird in the theme? Some tokenColors are incompatible with tsserver? I'm out of ideas lol.

This does NOT affect ts-server reporting errors. It only affects what's written in the tooltip.
I will still get errors with the correct type, BUT the tooltip will show "any" anyway.
![image](https://user-images.githubusercontent.com/5869818/229927720-93bd09d1-1951-496e-a063-3212e0b5ce97.png)
