### ISSUE TITLE
Extension Preview - Don't show drop down with a single option only

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#16440]
When the workspace is not opened on a folder, then the extension preview should only have a button 'disable' and not a drop down 'disable' with an option 'always'

![image](https://cloud.githubusercontent.com/assets/172399/20861516/77e23d66-b992-11e6-8a2e-52afa78e7ce3.png)

**Comment by sandy081** [comment]
Made actions in the viewlet and in the editor to be consistent. They either show one of the two following groups always.
- Enable (Workspace)
- Enable (Always) 
OR
- Disable (Workspace)
- Disable (Always)

If an action is disabled it shows disabled instead of hiding it, which is consistent behaviour across VS Code.
