### ISSUE TITLE
Could not find the task: Similar (npm) tasks causes only last defined one to be recognized.  

### ISSUE THREAD

**Issue by itorres-1** [microsoft/vscode#164485]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.72.2
- OS Version: MacOS 12.6

I have two very similar tasks in VS Code. They're pretty much identical except for a pre task I need to run which echos different text into a .env file. What I have found so far is that between my _start-dev_ and _start-local_ tasks, whichever is defined last is the only one that can be found. This is true even when I have more than two similar tasks. 

Steps to Reproduce:

1. Configure the following launch.json and tasks.json:

**launch.json:** 
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Start Dev",
            "type": "chrome",
            "request": "launch",
            "url": "http://localhost:3000",
            "webRoot": "${workspaceFolder}",
            "preLaunchTask": "start-dev",
            "postDebugTask": "Terminate All Tasks"
        },
        {
            "name": "Start Local",
            "type": "chrome",
            "request": "launch",
            "url": "http://localhost:3001",
            "webRoot": "${workspaceFolder}",
            "preLaunchTask": "start-local",
            "postDebugTask": "Terminate All Tasks"
        },
    ]
}

**tasks.json:**
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "start-dev",
            "type": "npm",
            "script": "start",
            "isBackground": true,
            "problemMatcher": {
                "owner": "npm",
                "background": {
                    "activeOnStart": true,
                    "beginsPattern": ".*",
                    "endsPattern": "To ignore, add.*eslint-disable-next-line to the line before.*"
                },
                "pattern": {
                    "regexp": ""
                }
            },
            "dependsOrder": "sequence",
            "dependsOn": [
                "setup-dev-env"
            ]
        },
        {
            "label": "setup-dev-env",
            "command": "echo REACT_APP_STAGE=dev > ./.env; echo BROWSER=none >> ./.env",
            "type": "shell",
            "presentation": {
                "echo": false,
                "reveal": "never",
                "focus": false,
                "panel": "shared",
                "showReuseMessage": true,
                "clear": false,
                "close": true
            }
        },
        {
            "label": "start-local",
            "type": "npm",
            "script": "start",
            "isBackground": true,
            "problemMatcher": {
                "owner": "npm",
                "background": {
                    "activeOnStart": true,
                    "beginsPattern": ".*",
                    "endsPattern": "To ignore, add.*eslint-disable-next-line to the line before.*"
                },
                "pattern": {
                    "regexp": ""
                }
            },
            "dependsOrder": "sequence",
            "dependsOn": [
                "setup-local-env"
            ]
        },
        {
            "label": "setup-local-env",
            "command": "echo REACT_APP_STAGE=local > ./.env; echo BROWSER=none >> ./.env",
            "type": "shell",
            "presentation": {
                "echo": false,
                "reveal": "never",
                "focus": false,
                "panel": "shared",
                "showReuseMessage": true,
                "clear": false,
                "close": true
            }
        },
        {
            "label": "Terminate All Tasks",
            "command": "echo ${input:terminate}",
            "type": "shell",
            "problemMatcher": []
        },
    ],
    "inputs": [
        {
            "id": "terminate",
            "type": "command",
            "command": "workbench.action.tasks.terminate",
            "args": "terminateAll"
        }
    ]
}

2. Attempt to launch "Start Dev" launch configuration.

**Comment by iKlask** [comment]
I think I have noticed the same/similar bug. I'm on vscode 1.74.3 on windows 10

I've been trying to setup tasks in an extension with the TaskProvider and CustomExecution API. I've noticed that when selecting a task to run from the UI, only the last task in the list returned by provideTasks gets executed.

I've simplified some of my code below to something more generic for an example:

```
taskProvider = vscode.tasks.registerTaskProvider("mylang", {
		provideTasks: () => {
			return [ 
				new vscode.Task(
					{type:"mylang"},
					vscode.TaskScope.Workspace,
					"Build",
					"mylang",
					new vscode.CustomExecution( async (): Promise<vscode.Pseudoterminal> => {
						// Custom Execution
						return new CustomBuildTaskTerminal("Build"); // Pseudoterminal implementation
					}),
					["lang-error"]
				),
				new vscode.Task(
					{type:"mylang"},
					vscode.TaskScope.Workspace,
					"Clean",
					"mylang",
					new vscode.CustomExecution( async (): Promise<vscode.Pseudoterminal> => {
						// Custom Execution
						return new CustomBuildTaskTerminal("Clean"); // Pseudoterminal implementation
					}),
					["lang-error"]
				)
			];
		},
		resolveTask(_task: vscode.Task): vscode.Task | undefined {
			return undefined;
		}
	});
```

For "mylang" example, I have two basic tasks: Build and Clean. CustomBuildTaskTerminal is a Pseudoterminal implementation that takes in a string ("Build" or "Clean") and executes the correct task based on that string. When running this example, the "Clean" task is the last task in the array, so no matter which task I select in the UI, the CustomExecution that gets called is the one defined for my clean task. I've made sure via debugging that provideTasks returns an array of unique tasks with unique custom executions. It seems like when VSCode selects a task execution, picks the execution for the last task in the array.

I can add more tasks and move them around, its always the last task in the array that ends up getting called. I've tried a lot of small changes to see if this issue is my code or if its a bug in VSCode. Since other people seem to have this issue I'm wondering if its a VSCode bug.

**Comment by meganrogge** [comment]
are you still seeing this issue? there have been a lot of fixes since you created this.

**Comment by bwateratmsft** [comment]
@meganrogge I think we are hitting the same issue here: https://github.com/microsoft/vscode-docker/issues/4138

**Comment by S-p-Ace** [comment]
same issue here,
only the last definition of a custom _npm: start_ task is recognized. 
(type: npm, script: start) 
vscode v.1.85.1

**Comment by kyleyoung1121** [comment]
Hello, I think I am having a similar issue.
Is there any word on potential fixes?

I am using VS Code version 1.89.1, and I am trying to develop a VS Code extension.
I believe my issue is nearly identical to what I was seeing in @iKlask 's message.

For my extension, I am providing tasks to the user using VS Code's Task Provider.
This is working great for my set of tasks that use ShellExecution.
But the 3 that use CustomExecution are having a weird issue where all 3 tasks, when run, execute the task that was defined last.

I will provide an example from my code. 
qudu_tasks is my array of Tasks that I pass into my TaskProvider.

`
	qudu_tasks.push(
		new vscode.Task(
			{ type: 'QUDU', id: 'QWHERE' },
			vscode.workspace.workspaceFolders[0],
			'QWHERE',
			'QWHERE Task',
			// This task requires user input, so we will use a custom execution
			new vscode.CustomExecution(QWHEREfunction),
			[],
		)
	);

	qudu_tasks.push(
		new vscode.Task(
			{ type: 'QUDU', id: 'QX' },
			vscode.workspace.workspaceFolders[0],
			'QX',
			'QX Task',
			// This task requires user input, so we will use a custom execution
			new vscode.CustomExecution(QXfunction),
			[],
		)
	);

	qudu_tasks.push(
		new vscode.Task(
			{ type: 'QUDU', id: 'STY' },
			vscode.workspace.workspaceFolders[0],
			'STY',
			'STY Task',
			// This task requires user input, so we will use a custom execution
			new vscode.CustomExecution(STYfunction),
			[],
		)
	);
`

Notice that my STY task is defined last. When I run any of these 3 tasks, I see a terminal pop up saying the correct task name, but all will call the STYfunction instead of their respective functions.
I've tried removing, adding, and rearranging tasks, but the bug persists. 
I've tried including/removing the "id: 'STY'" from "{ type: 'QUDU', id: 'STY' }," 
In any case, the last task is the one executed.

When I change the type value to be unique for each task, this issue seems to disappear.
So, I could make separate Task Providers and have the tasks appear separately, but that is not really an acceptable solution, as I need my tasks to appear together. Otherwise, it will defeat the purpose of the extension (convenience)
