### ISSUE TITLE
Lines in editor are not read when moving cursor

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#164633]
Testing #164512

With NVDA on Windows.

1. Open an editor with wrapped lines
2. Place cursor on a line.
3. ✅ line is read
4. Without moving focus out of the editor, put cursor on another line
5. Line will not be read

**Comment by meganrogge** [comment]
@alexr00 a gif would be helpful

**Comment by alexr00** [comment]
![Recording 2022-10-25 at 15 23 31](https://user-images.githubusercontent.com/38270282/197863624-c8a3b5b4-1475-4de5-97a2-7fbfc2129812.gif)

**Comment by isidorn** [comment]
@meganrogge let me know if you would like me to try to repro on my win VM.

**Comment by meganrogge** [comment]
@isidorn that would be great as I won't be back w my windows computer until next week

**Comment by isidorn** [comment]
I just tried it out on windows. And when I am on a wrapped line and if I navigate using the keyboard off that line the new line will be read properly.

When I navigate between lines using the mouse the new lines will not be read. This is independent if the line is wrapped or not. And this is how NVDA has always behaved (also with VS Code stable). 
I think this is expected behaviour since NVDA users mostly do not use the mouse and nobody so far complained about this.

@alexr00 can you also reproduce just with the keyboard? If not, I suggest we go ahead and close this issue.

**Comment by alexr00** [comment]
I was seeing the issue with mouse navigation.
