### ISSUE TITLE
There is no `Developer: Apply Upate` command

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#164692]
Testing #164465

<img width="507" alt="image" src="https://user-images.githubusercontent.com/1931590/197991747-d91e0023-0f78-4b1b-b51b-40401cdf124a.png">

**Comment by gjsjohnmurray** [comment]
Did you use "Run as administrator" to launch VS Code after installing it from the User Installer? Running as administrator should append `[Administrator]` to the window title. Running a user install as administrator intentionally doesn't start the update service. Look for a message like this in Log (Main):

2022-10-26 11:21:02.503 [info] update#ctor - updates are disabled due to running as Admin in user setup

**Comment by dbaeumer** [comment]
I did this in a Windows Sandbox which seems to run with a user that has Administrator rights.

**Comment by dbaeumer** [comment]
When installing the NON user version of VS Code into a Sandbox updates are available

<img width="317" alt="image" src="https://user-images.githubusercontent.com/1931590/198017046-4d0d4e8a-467c-4288-8445-60a815b8ecdd.png">

but the command is still missing.

**Comment by dbaeumer** [comment]
Was available right after restart.
