### ISSUE TITLE
Error in syntax highlighting in JS computed property name expression

### ISSUE THREAD

**Issue by bgoscinski** [Microsoft/vscode#16469]
- VSCode Version: 1.7.2
- OS Version: Windows 10 Pro

Steps to Reproduce:

1. Paste following code in editor:
```js
  const a = {
    [[foo, bar].join(',')]: 3
  }
```
2. Set language mode to JavaScript
3. Observe the error:
![bad syntax hl](https://cloud.githubusercontent.com/assets/5730169/20870305/f4388836-ba85-11e6-8fdc-e2402ee896df.png)

**Comment by mjbvz** [comment]
@bgoscinski, I believe this is fixed in the latest insiders builds:

![screen shot 2016-12-05 at 10 52 18 am](https://cloud.githubusercontent.com/assets/12821956/20897858/ede9d9c8-bad8-11e6-804f-b7aa7120e549.png)


This will be going into VSCode 1.8.

Please try this out and let us know if you notice any other issues. I'm going to open another issue to track the VS Light and Dark Themes having odd colorization in these cases (other themes seem ok):

![screen shot 2016-12-05 at 10 55 01 am](https://cloud.githubusercontent.com/assets/12821956/20897947/43f185c8-bad9-11e6-8d0c-fe890f83d43f.png)
 

Thanks

**Comment by bgoscinski** [comment]
Thanks :)
