### ISSUE TITLE
TS doesn't show dependencies

### ISSUE THREAD

**Issue by microshine** [Microsoft/vscode#16477]
- VSCode Version: 1.7.2
- OS Version: Windows 10

I've got a nodejs with `moduleResolution` like `node`. When I start to use node module TS doesn't suggest objects from module, but when I write it by myself it's working.

1. Want to use classes from node module
![image](https://cloud.githubusercontent.com/assets/7333669/20875235/1c316986-baca-11e6-8ba8-da71736bf64a.png)

2. It knows names on validation
![image](https://cloud.githubusercontent.com/assets/7333669/20875250/414dd79a-baca-11e6-915b-e2403cd63ecf.png)
![image](https://cloud.githubusercontent.com/assets/7333669/20875297/a9751c2a-baca-11e6-8d56-34f4564a9d74.png)

[example.zip](https://github.com/Microsoft/vscode/files/630212/example.zip)

**Comment by mjbvz** [comment]
Thank you for the detailed example. I confirmed this behavior in 1.7 and in the current 1.8 insiders builds, but I see this fixed in my build of VSCode from master (which include an updated version of TypeScript). To try this out this fix early, install a preview release of TypeScript locally:

```
$ npm install --save typescript@2.1.4-insiders.20161201
```

Reload the workspace and choose `Use Workspace version of typescript` when prompted (or add ` "typescript.tsdk": "./node_modules/typescript/lib"` to your workspace settings).

After upgrading the version of TypeScript, I see the correct completion in VSCode 1.7.2

<img width="634" alt="screen shot 2016-12-05 at 2 50 42 pm" src="https://cloud.githubusercontent.com/assets/12821956/20905812/42e6b088-bafa-11e6-817d-6f5ef37d266a.png">

The next VSCode insiders release will have this new build of TypeScript, as will VSCode 1.8

**Comment by microshine** [comment]
Thank you for the answer.
