### ISSUE TITLE
Turn off adding a space after selecting intellisense option with tab.

### ISSUE THREAD

**Issue by DanJ210** [Microsoft/vscode#16473]
- VSCode Version: 1.7.2
- OS Version: 14971

Can't search for anything VScode on Bing as you get all for Visual Studio...

Is there a way to turn off the auto addition of a space after tabbing to select an intellisense choice? So when I'm typing in CSS and I tab to select something, it automatically adds a space after the colon which I don't want and can't find where to change anywhere in any of the settings.

Am I overlooking this or can I request this option?

**Comment by aeschli** [comment]
Sorry, there is currently no option for this..

**Comment by DanJ210** [comment]
@aeschli No problem. Any way of requesting it!?

**Comment by aeschli** [comment]
This issue is the request for it... But unless there are multiple users asking for it, we'll not add a new setting, to avoid setting bloat. 
The space after the color is good practice for readability and especially when writing LESS and SCSS to avoid confusions with pseudo selectors in nested rule sets such as 
```scss
.foo { div:hover { ...} }
```

**Comment by DanJ210** [comment]
Ok. I mean I guess I could change to it. I thought it looked a little silly. Though I'm only writing basic CSS. I follow all other best practices and I make sure my code looks great, don't need to use some auto-formatter like some do, but I didn't care for the space and how it makes the code look.

Thanks for the info @aeschli
