### ISSUE TITLE
TypeScript Kernel selected as default for new Jupyter notebook

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#164827]
Type: <b>Bug</b>

**repo**
1. With the node.js notebooks extension installed
1. Create a new Jupyter notebook using the `Create: new Jupyter notebook` command

**Bug**
The `TypeScript` kernel is selected by default

VS Code version: Code - Insiders 1.73.0-insider (Universal) (9ad069358e9f09d1f49a90db36b73c953505438a, 2022-10-27T08:46:34.216Z)
OS version: Darwin x64 21.6.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|5, 4, 4|
|Memory (System)|32.00GB (0.54GB free)|
|Process Argv|--crash-reporter-id 48781ca2-1705-4f64-9bab-325055aab55d|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by DonJayamanne** [comment]
I think what's going on here is:
* Jupyter extension loads and detects kernel specs from disc and creates a controller for that (which happens to be typescript_
* Note: In the back ground Juyter extnesion is still busy finding other kernelspecs and Pytohn environments
* Jupyter extension has only one controller and sets that controller as the preferred controller.
* Jupyter then sees other controllers later, but doesn't find any matching controllers.

I think there are a few problems here:
* VS Code issue - VS Code might be setting the kernel as selected because there's only one controller at a given point? (may be)
* Jupyter Extension issue - We should un-set the preffered controller once we get other controllers loaded

**Comment by DonJayamanne** [comment]
Closing this, as the new kernel picker will ensure user is forced to select a new kernel.
