### ISSUE TITLE
GitHub authentication prompts me at least 3 times for login

### ISSUE THREAD

**Issue by timheuer** [microsoft/vscode#164896]
Type: <b>Bug</b>

I have a few GitHub capabilities enabled and when I am prompted for "GitHub Authentication" I finish and it succeeds...but pull requests, settings sync and other GitHub things prompt more times to login again.  This is not an ideal experience for the user to login three times to the same application.

VS Code version: Code 1.72.2 (d045a5eda657f4d7b676dedbfa7aab8207f8a075, 2022-10-12T22:15:18.074Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

https://user-images.githubusercontent.com/4821/198675628-86eb1ff7-6bbf-4c06-b343-fc084bb9f814.mp4

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3900X 12-Core Processor             (24 x 3793)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|127.92GB (74.84GB free)|
|Process Argv|--crash-reporter-id d2c91f49-7cf5-4a88-bfb8-425825bf92ad|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
vscccc:30566498
pyindex848:30577860
nodejswelcome1:30587005
fc301958:30595537
2e4cg342:30596373

```

</details>

**Comment by TylerLeonhardt** [comment]
The problem is, each of these things requires a different set of scopes (capabilities).

* Setttings Sync, just wants your identity to use it to authenticate with Settings Sync APIs
* GitHub Pull Request requires more than that... It wants access to your repo and needs an access token powerful enough to do that
* GitHub Copilot isn't owned by the VS Code team so I don't know what capabilities they need to function

All the potential solutions to this problem are sketchy or not ideal:
* Have SS GHPR GHC all request the same capabilities so that they can reuse the same token - then someone will wanna know why Settings Sync needs the ability to mess with repos
* Give SS, which requires less permissions, GHPR's token - only helps when you sign in to GHPR first... plus it's sketchy to give a feature/extension a token that's more powerful than it requested

We will be doing some alignment though to minimize prompts where we can... like Settings Sync & Edit Sessions and GHPR & GH Repositories but for some of these we won't be able to do much

**Comment by TylerLeonhardt** [comment]
I think it's important to call out that VS Code is not alone. Here's an example of this exact behavior in the `gh` CLI:

![Image](https://user-images.githubusercontent.com/2644648/206557843-a2f3f1af-7906-42a5-89c2-fa15161350d4.png)

Now it does seem that the way they do it is they hold on to just 1 token that will be replaced with a bigger and bigger one as a user uses more of the `gh` CLI. 

However, we can't do that because we have 3rd party extensions _also_ asking for auth and I fear giving them a token that is more powerful than actually requested is dangerous.

**Comment by TylerLeonhardt** [comment]
I think we are doing as best we can here with what's available for GitHub OAuth apps... if something changes on that side to make things smoother, we can investigate at that time.
