### ISSUE TITLE
TS server never finishes

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#164907]
* Open VS Code repo
* TS server starts immediately and never finishes, using 250% CPU 
* Though the ts server is running through another process, it's still blocking the whole extension host and no other extension can work
* I can't switch to another TS version as none of the command is responsive.

**Comment by rebornix** [comment]
I found out why it never finishes https://github.com/microsoft/vscode/issues/162968#issuecomment-1295255209. If there is a way for me to kill the ts server (other than just restart), it can help me out next time and at least have a working VS Code.

After https://github.com/microsoft/vscode/issues/162968#issuecomment-1295255209 and a few window reloads, I have a dozen of zombie ts server processes hanging around after killing VS Code.

**Comment by mjbvz** [comment]
@rebornix The server should be cleaned up automatically when the extension host exits. I'm not sure why they were not in your case. If this happens, I believe the only option is to kill them using the process explorer since VS Code no longer knows about them

Are there other processes hanging around too, such as the extension host process?

**Comment by rebornix** [comment]
@mjbvz I killed all of the manually, didn't get a chance to check if there is a parent extension host process though. Closing it for now, will check if it happens the next time.
