### ISSUE TITLE
Problems: list is jumping after making a change

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#16492]
I have a long list of problems and want to go through each of them. If I edit the file of the current result and jump back to the result list, the list jumps:

![view-picker](https://cloud.githubusercontent.com/assets/900690/20880295/acbbe83e-bad7-11e6-8c4c-f6b9a18bfeaa.gif)

The way I got to the list is by:
* enable `"noImplicitReturns": true` in `tsconfig.json` inside the `src` folder
* build from within VS Code

**Comment by sandy081** [comment]
This is happening because of auto reveal is enabled. Since there is a change in markers data auto reveal is getting triggered. I am triggering auto reveal when

- Markers panel is opened/focussed
- Filter in Markers panel is changed
- Editor is changed
- When markers data is changed

It makes sense in all first three cases but it is bit aggressive during last case. During last case, I should only do auto trigger if the current active file got added to markers data which helps user as it was not there before
