### ISSUE TITLE
Saw the following stack trace while selfhosting

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#16509]
I didn't do anything special at the time (i.e. I was typing in a TypeScript file, right after typing in keybindings.json). I have the following settings:

```
// Place your settings in this file to overwrite the default settings
{
	"editor.fontFamily": "Hack",
	"editor.fontSize": 16,
	"editor.renderWhitespace": "boundary",
	"editor.renderIndentGuides": true,
	"files.autoSave": "afterDelay",
	"editor.renderLineHighlight": "gutter",
	"telemetry.enableTelemetry": false,
	"telemetry.enableCrashReporter": false
}
```

```
shell.ts:540 A system error occured (ENOENT: no such file or directory, stat 'c:\Users\alexdima\AppData\Roaming\Code - Insiders\Backups\ad08f2029706e72480f9216ce0db91d9\file\09c2dfdc538a2e9dc22c92d69ab27978'): Error: ENOENT: no such file or directory, stat 'c:\Users\alexdima\AppData\Roaming\Code - Insiders\Backups\ad08f2029706e72480f9216ce0db91d9\file\09c2dfdc538a2e9dc22c92d69ab27978'
    at Error (native)e.onUnexpectedError @ shell.ts:540
(anonymous function) @ shell.ts:456
e.onUnexpectedError @ errors.ts:68
o @ errors.ts:88done @ winjs.base.raw.js:1378
v @ winjs.base.raw.js:1224enter @ winjs.base.raw.js:901
_run @ winjs.base.raw.js:1068
_chainedError @ winjs.base.raw.js:1031
n @ winjs.base.raw.js:736
then @ winjs.base.raw.js:1436
enter @ winjs.base.raw.js:747
_run @ winjs.base.raw.js:1068
_setCompleteValue @ winjs.base.raw.js:1052
v @ winjs.base.raw.js:1209
enter @ winjs.base.raw.js:901
_run @ winjs.base.raw.js:1068
_error @ winjs.base.raw.js:1041
(anonymous function) @ async.ts:654
(anonymous function) @ original-fs.js:123

```

**Comment by bpasero** [comment]
@alexandrudima to be clear, this error was only showing up in dev tools but not shown to you via error message right?

**Comment by Tyriar** [comment]
Having difficulty reproducing but my guess is that this is a race condition when auto save is on since the default delay is the same as the backup's delay (1000ms). @bpasero unless you think it's something else, how about we disabling all backups for text files when `afterDelay` is on?

**Comment by Tyriar** [comment]
I also hit this, I had auto save on at the time:

```
shell.ts:540A system error occured (ENOENT: no such file or directory, stat '/home/daimms/.config/Code - Insiders/Backups/45f8cb37345e6af816edadc2d14de789/file/fd1efab8f93adb9063c41d598b09ccaa'): Error: ENOENT: no such file or directory, stat '/home/daimms/.config/Code - Insiders/Backups/45f8cb37345e6af816edadc2d14de789/file/fd1efab8f93adb9063c41d598b09ccaa'
    at Error (native)
```

No error on UI.

**Comment by alexandrudima** [comment]
@bpasero Yeah, saw it in dev tools, not in an error popup

**Comment by bpasero** [comment]
@Tyriar when I look at how `discardResourceBackup` and `backupResource` are triggered in `backupModelTracker` I think you will always have a chance to hit this if someone manages to save the file while the backup is being made. The reason is that `backupResource` is not an atomic operation, it has a chance of being in the middle of work while `discardResourceBackup` is kicking in. 

Since it is currently not possible to cancel any running `backupResource` call, maybe it would be best to check if there is a pending `backupResource` running and only afterwards delete the backup?

As for auto save: hot exit for auto save enabled does not add much value because upon quit we save all dirty files if any of the auto save configurations is enabled. Basically you will never see a confirm dialog on quit, unless you have untitled files opened.

Now, if we take out backups when auto save is enabled, we would probably solve this issue for the 90% case. However, doing so would also mean that there is no backups being made for people that have auto save on. If you happen to configure auto save `onWindowFocusLost` and have many dirty files and hit a crash, you still loose your data.

I agree though that with auto save after 1 second, backups are not making much sense...

**Comment by Tyriar** [comment]
@bpasero for the auto save case I'm suggesting only disable text file backups when it's set to `afterDelay`.

Proposed actions:

- Make discard and backup go through a queue
- Disable text file backups when `files.autoSave` is `afterDelay` and `files.autoSaveDelay` <= `TextFileEditorModel.DEFAULT_CONTENT_CHANGE_BUFFER_DELAY`

**Comment by Tyriar** [comment]
I made the auto save change, let's push the queue out to Jan as I don't think it's critical enough to get fixed at this point.

**Comment by aeschli** [comment]
@bpasero Are there steps to verify?

**Comment by bpasero** [comment]
No, I think we should mark this as verified given it was not reported again in a while.
