### ISSUE TITLE
cursor not at input after auto-fill on an inline CSS property

### ISSUE THREAD

**Issue by lavishsaluja** [microsoft/vscode#165007]
hey, just wanted to report a small improvement that can be made in auto-fill of properties inside inline style elements.

upon auto-filling the property inside an inline style element the cursor is taken to after the `;` - for all other elements VS code auto-fill takes the cursor automatically to the place where input is required which is very helpful, doing the same for inline style element will be great i.e, take the cursor to before `;`

https://user-images.githubusercontent.com/25464742/198877265-7a88e56a-c2c4-4c22-b1c3-4cd60ff32f9c.mov

**Comment by aeschli** [comment]
The problem is that after completing `style`, you are in snippet mode (visible by the line after "") :

![image](https://user-images.githubusercontent.com/6461412/199033024-40846090-0a08-441d-81e1-f7ce1934476d.png)

When typing further, the css completions for `background-color` also comes back with a snippet. But code completion doesn't not allow nested snippet modes (I assume) and just applies it as a text.

**Comment by jrieken** [comment]
When a snippet is active, IntelliSense as you type (aka quick suggestions) is disabled. That is because there is a conflict between the <kbd>Tab</kbd>-key which moves to the next placeholder but also accepts a completion. You wouldn't be able to type in a placeholder and then move to the next placeholder as you would accept a suggestion then. You have the following options

* change the default via the `editor.suggest.snippetsPreventQuickSuggestions`-setting
* in snippets trigger suggestions manually (via Ctrl+Space, Alt+ESC (macOS), or `ctrl/cmd+i`)

**Comment by lavishsaluja** [comment]
hey I did not fully get you but how is this working for height placeholder? (attaching below)

here the cursor did not move to after `;` but instead at the place where input is required before `;`

https://user-images.githubusercontent.com/25464742/199081775-898b002e-13c6-4501-829c-ee046a41d5e9.mov

**Comment by aeschli** [comment]
@lavishsaluja To see the bug you must start typing `style`
`
@jrieken changing `editor.suggest.snippetsPreventQuickSuggestions` makes no difference. Note that the second suggestion window is triggered by the completion itself (it has am accept command), not by quick suggest

I think would be ok to end the first snippet mode when the second completion dialog is opened. Currently `Tab` accepts the proposal.

**Comment by jrieken** [comment]
I believe what you are seeing is actually https://github.com/microsoft/vscode/issues/163808
