### ISSUE TITLE
Can't submit a Linux Alpine only build

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#165139]
![image](https://user-images.githubusercontent.com/22350/199208180-63c60100-e7a8-41cc-8556-703739c3dcba.png)

**Comment by joyceerhl** [comment]
We needed to revert this PR because it broke the Code-OSS build (no jobs ran but the failure was only visible on Azure Pipelines and not on GitHub CI). 

This is the only error info available: https://dev.azure.com/monacotools/Monaco/_build/results?buildId=197039&view=results
![image](https://user-images.githubusercontent.com/30305945/207953627-684f4662-fef3-42b8-92ca-a2e050ee2704.png)

**Comment by joaomoreno** [comment]
New PR: https://github.com/microsoft/vscode/pull/169368
