### ISSUE TITLE
Classic scroll functions / page up/down

### ISSUE THREAD

**Issue by SailorMax** [Microsoft/vscode#16513]
- VSCode Version: 1.7.2
- OS Version: Windows 10 x64

Steps to Reproduce:

1.  open any long file
2.  click in middle of scroll bar

Expected: Page Down

Actual: Goto Scroll position where I clicked minus scroll cursor height/2. (But if file too large, minus height)

Can you add option to return classic behavior scroll bar, where user can use page up/down functions?

**Comment by alexandrudima** [comment]
To keep the number of issues in our inbox at a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: we look at the number of votes the issue has received and the number of duplicate issues filed. Thank you for your time and understanding.

If you disagree and feel that this issue is crucial: we're happy to listen and to reconsider.
