### ISSUE TITLE
improve terminal quick fix telemetry

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#165190]

**Comment by Tyriar** [comment]
In https://github.com/microsoft/vscode/pull/163323 we accidentally shipped a telemetry event that sends the actual commands run instead of the ID of the quick fix. Most of this is filtered out automatically by our data ingestion pipeline but some branch names like those not containing a `/` weren’t. This issue has already been mitigated by rejecting the events on the server side and purging all old data from our tables, but we should also avoid initiating these network requests.

To Verify:

1. Ensure telemetry is enabled.
2. Set log level to trace
3. Trigger and accept a terminal quick fix
4. Ensure a generic description of the type of quick fix and not the actual command is recorded in the telemetry output channel
