### ISSUE TITLE
terminal

### ISSUE THREAD

**Issue by princegas** [microsoft/vscode#165370]
ADD ISSUE DESCRIPTION HERE

My terminal is blank, I can't write anything there. I deleted my account and made a new one and still the same issue

**Comment by meganrogge** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.
/label info-needed terminal

**Comment by meganrogge** [comment]
disable `terminal.integrated.gpuAcceleration`

**Comment by bartvanandel** [comment]
Why is this broken (again) all of a sudden? It worked for me yesterday, then I did an update, and now today it's not working. Well, that is, for most terminals. I currently have 2 terminals open, the first one renders fine, the second one (and any other that I open) remain blank. Even the title of subsequent terminals aren't rendered, while the first one is.

List of open terminals:
![image](https://user-images.githubusercontent.com/1194804/200020379-8491ad40-4596-4068-bcaf-d48548462f87.png)

**Comment by bartvanandel** [comment]
I switched GPU acceleration off, then it worked a couple times, but yesterday I got the same faulty result with GPU acceleration turned off, so this isn't the entire solution.

I checked Task Manager though, and when this behavior occurs, it looks like no actual terminal is started. That would explain why the title stays empty, because there is none at that point.

Note that this also happens when using `npm start` from a launch command, not just when manually opening a terminal. At least that part is consistent.
