### ISSUE TITLE
Sticky scroll breaks VS Code on Ctrl+A+Delete

### ISSUE THREAD

**Issue by ahkhanjani** [microsoft/vscode#165385]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.73.0
- OS Version: Windows 11 Pro 21H2

Steps to Reproduce:

1. Enable sticky scroll.
2. Create a .js or .md file or anything.
3. Write a Javascript function or markdown header or something that can stick to the top.
4. Hold <kbd>Enter</kbd> to insert new lines until the header sticks to the top.
5. Select all text with <kbd>Ctrl</kbd>+<kbd>A</kbd> and delete all the text.

The sticked header will stay on top even after changing files. Restarting VS Code solves the problem temporarily.

**Comment by santhosh-raghul** [comment]
This also happens when I create a new file, type something, scroll down and delete all the content. It even persists on every new file that is opened later on using ctrl + n.
Disabling and enabling sticky scroll doesn't fix the issue but reloading does.

![image](https://user-images.githubusercontent.com/62311240/202158907-173c3f2a-bba7-4349-ae05-91082820080b.png)

**Comment by jrieken** [comment]
fyi @alexdima this might be the same issue that causes sticky stick scroll in diff editors
