### ISSUE TITLE
Close, minimize and maximize buttons missing on Arch Linux

### ISSUE THREAD

**Issue by D3vil0p3r** [microsoft/vscode#165481]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.73.0
- OS Version: Arch Linux (Linux x64 6.0.2-arch1-1)
![image](https://user-images.githubusercontent.com/83867734/199950161-9b641669-0f86-41b5-8341-1a63abb33f20.png)

I read several issues related the missing of close, maximize and minimize buttons occurring in Windows and macOS. I'm noting the same issue is happening also on Arch Linux.

Here, I have a full upgraded Arch Linux environment and when I open Code, I don't get these buttons:
![image](https://user-images.githubusercontent.com/83867734/199950444-9218eb0e-6391-497c-aaa1-f4b231e899c5.png)

This issue should be related to Electron19 because, when I downgrade electron19 package from 19.1.4 to 19.0.13, I get the three buttons:

![image](https://user-images.githubusercontent.com/83867734/199950785-05c5b725-7115-4eb2-9952-f2512d49b18a.png)

Steps to Reproduce:

1. On a full upgraded Arch Linux environment, install code by `sudo pacman -Syy code`
2. Open the software by `code`
3. When Code is opening, the three buttons on the top-right are missing
4. Try now to downgrade `electron19` package to 19.0.13 by using `sudo downgrade electron19` and choosing the 19.0.13 version
5. Reopen Code and the three buttons should appear

**Comment by Nuc1eoN** [comment]
Same here on arch:
![2022-11-08_19:31:53](https://user-images.githubusercontent.com/2538022/200650303-b4f54997-4380-43ba-9b5f-80f5b9b25f90.jpeg)

**Comment by major-mayer** [comment]
I can also confirm this
```
Version: 1.73.0
Commit: 8fa188b2b301d36553cbc9ce1b0a146ccb93351f
Date: 2022-11-03T14:04:08.642Z
Electron: 19.1.4
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 5.19.17-2-MANJARO
Sandboxed: No
```

**Comment by l0ud** [comment]
Can confirm. How can you even invent such bugs I don't know.

**Comment by bvobart** [comment]
I'm having the same problem on Manjaro (which is based on Arch)

```
Version: 1.73.1
Commit: 6261075646f055b99068d3688932416f2346dd3b
Date: 2022-11-14T09:01:30.462Z
Electron: 19.1.4
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 6.0.8-1-MANJARO
Sandboxed: No
```

Apparently this happens on Linux, MacOS as well as Windows, as there are similar issues for [MacOS](https://github.com/microsoft/vscode/issues/161586) and [Windows](https://github.com/microsoft/vscode/issues/165337).

The Windows issue also shows people using Electron 19.1 getting this problem, so it seems like the problem was introduced when moving from Electron 19.0.13 to 19.1.x. https://github.com/microsoft/vscode/issues/165337#issuecomment-1302040524 mentions setting `"window.experimental.windowControlsOverlay.enabled": true` as a fix, but that doesn't work for me.

Notably, the Windows issue has been closed with https://github.com/microsoft/vscode/pull/165384, but I don't know if that also fixes it for Linux & MacOS and when that will be released in a stable version.

@sbatten Thanks for the PR, would you mind updating us on whether that also fixes the issue on Linux & MacOS? If so, when can we expect it to be released in a stable version?

**Comment by sbatten** [comment]
Can anyone in this thread verify that the issue still remains on the latest insiders on arch(-based) linux?

**Comment by major-mayer** [comment]
Just tested it with the build from today on Manjaro and indeed the issue seems to be fixed.
![grafik](https://user-images.githubusercontent.com/17907799/204369886-d6b43ca4-2c09-4939-a4df-07a4ef974083.png)
Version: 1.74.0-insider
Commit: ac084d723b7405591d2110fe374648345ecb8ce6
Date: 2022-11-28T05:23:46.430Z
Electron: 19.1.6
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 5.19.17-2-MANJARO
Sandboxed: Yes

**Comment by sbatten** [comment]
@major-mayer thank you very much for the confirmation. This fix will make its way to the next stable release.

**Comment by D3vil0p3r** [comment]
I confirm too on Athena OS (Arch-based) the latest insiders version is working correctly:

![image](https://user-images.githubusercontent.com/83867734/204372739-4392a87f-6684-49db-bf90-7ae3b53dcc33.png)
