### ISSUE TITLE
VS Code Cannot update some extensions through VSIX 

### ISSUE THREAD

**Issue by Jacobify** [microsoft/vscode#165591]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.73.0
- OS Version: Windows 10 Enterprise 19044.2006

When I tried to install an extension's .vsix file eg. [https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools](url) in vs code , the app throws the error **Corrupt ZIP: end of central directory record signature not found**.

I have already found an older closed issue ( [https://github.com/microsoft/vscode/issues/71610](url) ) but I could not figure out a solution for this matter. 

![2022-11-05 12_10_11-Window](https://user-images.githubusercontent.com/39615077/200111638-39d9439b-d054-4c6f-83b1-4f0c3957593f.png)

Also it is visible above that vs code was not able to detect that there was an update for the same extension either ?!

ps:
I have encountered the same issue in the insiders edition with the difference that the insiders edition was able to detect the new update for the extension.

Thanks for your consideration in advance

**Comment by Minktong** [comment]
I have also faced the same problem.

**Comment by msh-shf** [comment]
The same problem!!!

**Comment by sandy081** [comment]
Above error means that the downloaded ZIP is incomplete or corrupted. Please double check the VSIX you downloaded and probably reach out to Marketplace in case it is corrupted. I assume an update was not shown because you have installed stable version of the extension and the latest version is pre-release. You have to switch to pre-release version to get the latest latest.
