### ISSUE TITLE
Walkthrough tile buttons are missing background color

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode#165526]
## Before

<img width="449" alt="CleanShot 2022-11-04 at 10 42 17@2x" src="https://user-images.githubusercontent.com/25163139/200041092-5002242b-c98a-4901-8469-04272109fcf2.png">

## Current

<img width="467" alt="CleanShot 2022-11-04 at 10 39 43@2x" src="https://user-images.githubusercontent.com/25163139/200040739-f585c363-4ec4-4921-a1c3-4fa94dd20175.png">

**Comment by daviddossett** [comment]
@lramos15 maybe related to CSS var changes?

**Comment by lramos15** [comment]
@bhavyaus Assigning you in case you also wanted to take a look since you're working in this area. The bug is likely caused by https://github.com/microsoft/vscode/pull/165185 the fix would be to compare to stable and see what color variable is now being missed in `gettingStarted.css` feel free to reach out if you get stuck or don't have time to work on this item :+1:
