### ISSUE TITLE
[CSS] Syntax highlighting no longer works for property keyword values and functions

### ISSUE THREAD

**Issue by dstorey** [Microsoft/vscode#1656]
Before Dec update:

![screen shot 2015-12-25 at 7 54 16 pm](https://cloud.githubusercontent.com/assets/465069/12005061/54abec08-ab41-11e5-8330-4ed4adae99a4.png)

After:

![screen shot 2015-12-25 at 7 54 42 pm](https://cloud.githubusercontent.com/assets/465069/12005062/5a3ab38e-ab41-11e5-9457-034bb64b5284.png)

As you can see, while the property names are highlighted, the values are the same whether it is valid or not. The data is in the css.plist file, it is just not getting read, or the colour is no longer set, for whatever reason.

**Comment by aeschli** [comment]
We changed the default themes to be more consistent with Visual studio where css attribute values are white (or red for string values) regardless if valid or not.

**Comment by aeschli** [comment]
I think the validation if a value is correct or not should be done in a validator. Having this also in the  tokenizer will make the tokenizer more complex and we will have to update on every spec change.

**Comment by Tyriar** [comment]
Marked as verified, which basically means it reverted to the previous behavior as the change was rejected.

**Comment by aeschli** [comment]
@Tyriar The change was not rejected. It just needed extra changes in for SASS.

**Comment by Tyriar** [comment]
@aeschli oh, I guess I wasn't seeing it because I was on the VS theme.

I don't see CSS consistency with Sass on latest alpha:

## Dark+

**CSS**
![image](https://cloud.githubusercontent.com/assets/2193314/13922398/5053a560-ef39-11e5-9b77-747e5472bbbd.png)

**Sass**
![image](https://cloud.githubusercontent.com/assets/2193314/13922408/608fa49c-ef39-11e5-8ef0-553a43b5da0d.png)

**Less**
![image](https://cloud.githubusercontent.com/assets/2193314/13922477/b7ec6946-ef39-11e5-9117-70bd66cfd0af.png)

## Light+

**CSS**
![image](https://cloud.githubusercontent.com/assets/2193314/13922454/a1ab8fea-ef39-11e5-8dba-05d26af67bc9.png)

**Sass**
![image](https://cloud.githubusercontent.com/assets/2193314/13922450/9b5197fc-ef39-11e5-85e4-1f1914587d8c.png)

**Less**
![image](https://cloud.githubusercontent.com/assets/2193314/13922432/7e7f25fe-ef39-11e5-8c88-f8111bb29c7b.png)

**Comment by aeschli** [comment]
Looks like there's still an issue with functions then.
Please open a new issue.

**Comment by Tyriar** [comment]
Adding back verified as the new issue is captured in #4509
