### ISSUE TITLE
Presing Tab key after a word in markdown file creates XML tags

### ISSUE THREAD

**Issue by jaywick** [Microsoft/vscode#16569]
- VSCode Version: 1.7.2 (7ba55c58)
- OS Version: Windows 10.0.14393

Steps to Reproduce:

1. Create a `test.md` file
2. Add a sentence of text such as 

        Lorem ipsum sit dolar amet.

3. Put your keyboard cursor after `Lorem`
4. Press <kbd>Tab</kbd>

Expected: Spaces or tabs to be added between `Lorem` and `ipsum`
Result: `Lorem` word gets converted into an XML tag and auto closed, leaving us with

        <Lorem></Lorem> ipsum sit dolar amet.

### In Action

![in action](https://cloud.githubusercontent.com/assets/3955052/20914967/0d655710-bbd7-11e6-9a10-6fbc13886549.gif)

**Comment by mjbvz** [comment]
This is coming from Emmet. To disable this, add:

```json
    "emmet.excludeLanguages": ["markdown"],
```

to your settings. 

Although this is currently the expected behavior, I think we should probably disable emmet expansions in markdown by default because this behavior is annoying. @ramya-rao-a Any thoughts?

**Comment by egamma** [comment]
@ramya-rao-a this behaviour is a consequence of #9500, which has as the goal to not hard code in which language modes emmet is enabled for. As a heuristic #9500 uses the grammar's scope name hierarchy as a hint. This heuristic has worked pretty well.

The scope of the markdown grammar is `text.html.markdown`. This means Markdown is treated as a specialization of `html` and therefore `emmet` is enabled in markdown. 

According the emmet doc there is no special syntax profile available for Markdown https://github.com/Microsoft/vscode/issues/9500#issuecomment-242221652.

So a quick fix would be to:
- hard code an exclusion for markdown in #isEmmetEnableMode
- change the scope name of the markdown grammar, so that it doesn't inherit from html, not sure what the consequences of this are.

@mrmlnc do you have other ideas how to improve the support for emmet in Markdown and avoid the surprise described in this issue?

**Comment by mrmlnc** [comment]
Hello, @egamma,

I see the same way as you suggested above. But, perhaps, we can also disable Markdown in the settings, as it was for `files.exclude`.

But my 2 cents:

Markdown is a lightweight markup language and it presupposes the existence of HTML constructs within yourself. Thus, it seems to me, to disable Emmet inside Markdown is not correct.

**Comment by egamma** [comment]
@mrmlnc thanks for the feedback. I agree with your point that disabling emmet without some way to re-enable it, if someone really wants emmet is better than to totally disable it.

Glad to hear about Emmet 2.0.

**Comment by mjbvz** [comment]
@egamma Could `"markdown"` just be in the default setting for `emmet.excludeLanguages`? That would stop most users from triggering emmet unexpectedly in markdown files, while still allowing users to opt back in to emmet for markdown if they wish

**Comment by egamma** [comment]
@mjbvz the idea is good. It has a small drawback. If someone defines `emmet.excludedLanguages` in the settings, then they will not profit from this fix. 

However, if someone if familiar with this setting and then they know how to disable emmet in markdown, if they are annoyed by it. Bottom line I'm fine with this fix.

**Comment by mjbvz** [comment]
Ok, I've merged in #17094 which adds `"markdown"` to the default list of excluded languages. Not a perfect solution, but it should stop many users from hitting this behavior unexpectedly
