### ISSUE TITLE
Mac Emoji Panel Shows in Wrong Location 

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#16561]
- VSCode Version: 1.8 insiders
- OS Version: OSX 10.10.6

Steps to Reproduce: 

1. Create blank file
2.  type a word and go to the end of the word.
3. Trigger the mac emoji panel

**Expected**
Popup shows from where the cursor currently is in the editor.

**Actual**
![screen shot 2016-12-05 at 5 34 54 pm](https://cloud.githubusercontent.com/assets/12821956/20909521/28fb37b8-bb11-11e6-9dda-63de9ebda218.png)

The panel is off to the side in the gutter somewhere. The cursor was on the last line in this case

**Comment by alexandrudima** [comment]
Same root cause as #356 -- the textarea (when not doing comoposition) is positioned in the top left corner of the editor. When we get a `compositionstart` event, we move the textarea near the primary cursor. In this case, I think we don't get any event until an emoji is picked and we don't get a chance to reposition the textarea.
