### ISSUE TITLE
Opening a file always opens two windows

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#16574]
We've been like this for as long as I can remember, but I just realised how annoying it is.

In Windows, have Code closed and:

1. Double click a file

or

1. Run `code-insiders file`

You **always** get two windows open: one empty and one with the file. We should only get one.

![image](https://cloud.githubusercontent.com/assets/22350/20918117/ac355526-bb95-11e6-97c5-9a4ef4d529e8.png)

**Comment by bpasero** [comment]
@joaomoreno no, we never behaved like that. looks like a regression (could be hot exit)?

**Comment by joaomoreno** [comment]
Oh snap, I was remembering wrong! 😮

**Comment by bpasero** [comment]
@Tyriar please note my fix, somehow the backup service was returning its actual data structure that was changed while opening windows, basically what happens is:
* code opens on a single file
* we store the empty window as backup workspace
* we wrongly open the empty window in https://github.com/Microsoft/vscode/blob/master/src/vs/code/electron-main/windows.ts#L437 because meanwhile that window was added into `emptyToRestore`

**Comment by Tyriar** [comment]
Nice find, this may have been the cause for the mysterious extra empty workspace window I was seeing sometimes while adding empty workspace support :smile:
