### ISSUE TITLE
Patch gave me issues that persist in fresh install...

### ISSUE THREAD

**Issue by Arebee88** [Microsoft/vscode#1658]
[C:/Users/Robbie Blair/.vscode/extensions/eg2.tslint]: Cannot read file C:/Users/Robbie Blair/.vscode/extensions/eg2.tslint/package.json: ENOENT: no such file or directory, open 'C:\Users\Robbie Blair\.vscode\extensions\eg2.tslint\package.json'

I dont know what eg2 is.. presumably if I installed the extension itd go away???

**Comment by Arebee88** [comment]
It's remarkable how often I want to go screw around with some code just to have VSCode throw shit in my way.

**Comment by bpasero** [comment]
Not sure what happened here, maybe @egamma knows how the update could cause this.

**Comment by egamma** [comment]
This could be a consequence of a failed uninstall/update of the tslint extension.

@Arebee88 do you remember whether you did uninstall the tslint extension?

>I dont know what eg2 is.. presumably if I installed the extension itd go away???

extensions are scoped to a [publisher](https://code.visualstudio.com/docs/tools/vscecli) and `eg2` is the name of the publisher of the tslint extension (in this case me).

>It's remarkable how often I want to go screw around with some code just to have VSCode throw shit in my way.

pls do not stop filling issues when things are getting thrown in your way

**Comment by egamma** [comment]
We could reproduce the problem. 

- It happens when an extension is uninstalled and the extension has code that is loaded into a server (tslint runs a server process). 
- The files loaded into a server process cannot be deleted and removed and you end up with a partially uninstalled extension.
- On the next startup Code doesn't find the package.json and complains.

We have addresed this the January update by keeping track of deleted extensions.

**Comment by Arebee88** [comment]
![twoerrors](https://cloud.githubusercontent.com/assets/13505971/12868377/91470f92-ccc2-11e5-98ff-409fabf98dcb.png)

[C:/Users/Robbie Blair/.vscode/extensions/eg2.tslint]: Cannot read file C:/Users/Robbie Blair/.vscode/extensions/eg2.tslint/package.json: ENOENT: no such file or directory, open 'C:\Users\Robbie Blair\.vscode\extensions\eg2.tslint\package.json']

[C:/Users/Robbie Blair/.vscode/extensions/eg2.tslint-0.5.15]: Cannot read file C:/Users/Robbie Blair/.vscode/extensions/eg2.tslint-0.5.15/package.json: ENOENT: no such file or directory, open 'C:\Users\Robbie Blair\.vscode\extensions\eg2.tslint-0.5.15\package.json'
Close
Error

**Comment by Arebee88** [comment]
I got the second one after trying to install tslint to fix the first issue and then uninstalling it after no avail...

I also did another 'fresh' reinstall.

How do I make it go away?

**Comment by egamma** [comment]
The fix is currently only available in the insiders build and will apply when you uninstalled the extension using the insiders build: https://blogs.msdn.microsoft.com/vscode/2016/02/01/introducing-insiders-builds/

Otherwise the work around is to manually delete the extension folder ${HOME}/.vscode/extensions/eg2.tslint*
