### ISSUE TITLE
Join Lines: not multi cursor aware

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#16587]
Testing: https://github.com/Microsoft/vscode/issues/16545

Steps to Reproduce:

1. set multiple cursors 
2. run "Join Lines" command

=> only happens for the first cursor

**Comment by bpasero** [comment]
@rebornix when I run this action having multiple cursors on a single line, I loose the cursors and get a selection. When I undo and redo, I am not seeing that though:

![view-picker](https://cloud.githubusercontent.com/assets/900690/21005322/a48ec8e8-bd34-11e6-857b-320b50a414d1.gif)

**Comment by rebornix** [comment]
Changing multi cursors into one selection is not intentional, it's already fixed.

For one single cursor, we move the cursor before the newly added space and next line's trimmed content. For one single selection, we still persist the selection. This is the normal behavior of both Vim and Sublime Text.

When we take multi cursor into consideration, if people put multi cursor in one single line, running Join Lines on every cursor leads to the same result, so these cursors merge into a single one.

![multicursor-combat](https://cloud.githubusercontent.com/assets/876920/21024883/0e010678-bd3b-11e6-83a4-dd970f125779.gif)

Above the behavior after the fix. However, there are still issues about the undo/redo stack. As we need to modify the cursor position after executing the commands, an undo followed by a redo will generate wrong cursor positions. This happens both here and **Delete All Left**.

![redo](https://cloud.githubusercontent.com/assets/876920/21025010/a6ea94b2-bd3b-11e6-9f72-c9520c5fa9fa.gif)

@alexandrudima it seems that we are not getting expected cursors while redoing `editor.executeEdits`, any hint on this? IMHO this one can be fixed in following iteration.

**Comment by alexandrudima** [comment]
`executeEdits` goes into `model.pushEditOperations` which gets a cursor state computer that returns where the cursors end up according to markers logic. We could enhance `executeEdits` to optionally take a second argument `resultingSelections` which would be set on the cursor and in the cursor state computer.

**Comment by rebornix** [comment]
This issue was already fixed by community.
