### ISSUE TITLE
It is not intuitive to user where to add compound configurations in launch.json

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#16594]
Testing #16026 

In launch.json it is not intuitive where to add compound configurations.

**Comment by isidorn** [comment]
Agree, however this is a feature for expert users.
@joaomoreno had a nice idea of just having an empty `compounds` array at the end of launch.json

**Comment by isidorn** [comment]
Adding empty `compounds` array sounds like a nice way to improve discoverablity however I think it would just provide noise for the novice user. And compound users shuold be experts which will find this feature one way or another.

@weinand let me know what you think about adding an empty `compounds` array for discoverabilty at the end of `launch.json`

**Comment by weinand** [comment]
I agree that adding the empty array makes the launch.json look more complex, so I think we should not go that route.

Users interested in "Compounds" should be able to find documentation in the provided link https://go.microsoft.com/fwlink/?linkid=830387.

However there a two problems:
- the link does not go to "Launch Configurations" section,
- the Launch Configuration section does not explain Compounds at all
This must be fixed (without changing the link because that is out for a long time and users have tha link already in their launch.jsons).

**Comment by weinand** [comment]
We will improve the documentation as part of the December docathon.

**Comment by isidorn** [comment]
I checked and the link is good, it nicely opens the `Launch Configuraitons` section.
In the Launch Configurations I have added a short sentence with a link to the compound configurations part of the doc
