### ISSUE TITLE
selectionHighlight regression in 1.73

### ISSUE THREAD

**Issue by zachvalenta** [microsoft/vscode#165920]
Does this issue occur when all extensions are disabled?: yes

- VS Code Version: 1.73.0
- OS Version: macOS 12.1 21C52 x86_64

Recently upgraded to 1.73 and no longer seeing selection highlighting.

<img width="1728" alt="Screen Shot 2022-11-09 at 8 44 07 AM" src="https://user-images.githubusercontent.com/11388735/200846144-ef65adb1-2241-4d40-ae7c-04364c8b0164.png">

Default setting still `true` and set on the user level as well to no avail.
<img width="1728" alt="Screen Shot 2022-11-09 at 8 41 34 AM" src="https://user-images.githubusercontent.com/11388735/200846421-56ef6c59-4700-41c6-9093-6e931bf7df8f.png">

<img width="803" alt="Screen Shot 2022-11-09 at 8 41 56 AM" src="https://user-images.githubusercontent.com/11388735/200846451-e265f393-ee14-41c0-b39d-a3082525170b.png">

**Comment by zachvalenta** [comment]
I am only seeing this in Markdown (including code blocks) but not source code.

**Comment by zachvalenta** [comment]
The problem seems to be that previously you'd get a match if the cursor was at the start of the word but now only if you select/highlight the entire word (or subset). If this is a change in functionality, any way to update settings to restore previous out-of-box behavior?

**Comment by alexdima** [comment]
I believe this might be caused by markdown now registering a document highlight provider. When a language registers a document highlight provider, the non-semantic based, text editor word highlight takes a back seat. I think you can turn this down via `"editor.occurrencesHighlight": false`, or maybe `"markdown.occurrencesHighlight.enabled"`. Let me loop in @mjbvz , maybe he has more ideas.
