### ISSUE TITLE
toggle in/out of zen mode with settings.json file changes active editor

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#16616]
Testing #15647 

- VSCode Version: insiders 1.8.0 a8d5b9
- OS Version: MacOS

Steps to Reproduce:

1. open a folder
2. close all editors
3. single click on a file to open it in preview mode
4. open settings.json (CMD+,), now the editor should be replaced
5. go into zen mode (CMD+K, Z)
5. exit zen mode (CMD+K, Z)

Result: the last file you had open, before opening the settings file, is now in view. In other words, the settings file is no longer visible.  Only seems to happen with settings.json

**Comment by isidorn** [comment]
As designed. On explorer open we always open the revealed file - there is a setting for this 'explorer.autoReveal'.

So you can get the same behavior if instead of going in and out of zen mode you would show / hide the viewlet.

Though I do agree that your scenario is not nice. But the key problem here is that explorer.autoReveal does not make much sense when an editor is open in preview. Though this is up to ben to decide how to tackle this.

**Comment by bpasero** [comment]
This is a consequence of the explorer restoring the last active file when you open it. Another example where we do this is when you jump from Git viewlet back to the explorer we close the diff editor that you likely have open and bring back the file you last worked on. In that scenario I like the flow, however in the described scenario it is not very nice.

Btw the same happens when you open a markdown as preview, close all other editors and hide and show the explorer. The last file you had open restores. 

One way to probably fix this is by only restoring the file if it is still open in the editor group.

**Comment by bpasero** [comment]
The explorer is now treating the settings and keybindings in the same way as a normal file, so this bug as reported is fixed.

**Comment by chrisdias** [comment]
LGTM

**Comment by isidorn** [comment]
@chrisdias feel free to add a verified label :)

**Comment by chrisdias** [comment]
@isidorn sorry, added.
