### ISSUE TITLE
Color completion only displays color squares for hex variables

### ISSUE THREAD

**Issue by allan2** [microsoft/vscode#166197]
This issue has appeared before in #63062 and #68269.

When defining variables, color squares appear for all variables sources (hex, RGB, RGBA, string).
When using color completion, only hex gets color squares in the autocomplete option.

![mixed-var](https://user-images.githubusercontent.com/6740989/201491040-ad2648a2-49bb-4a96-b30b-00c45b5e3b50.png)
![hex-only](https://user-images.githubusercontent.com/6740989/201491041-3d3d0e33-0cd8-4b06-8d4f-b4d22e0a8eab.png)

**Comment by GauravB159** [comment]
I have been checking this out and have found a couple issues. Part of this can be fixed in [microsoft/vscode-css-languageservice](https://github.com/microsoft/vscode-css-languageservice)

![image](https://user-images.githubusercontent.com/22005033/201509349-7b5a3d1a-92f0-4c23-96ec-5311e5a21125.png)

File: [cssCompletion.ts](https://github.com/microsoft/vscode-css-languageservice/blob/main/src/services/cssCompletion.ts)

This function only tests for built-in colors and hex values. Adding another part to it that checks for color functions fixes the two color functions. 

Making this change fixed `$rgb` and `$rgba`. 

However, another fix needs to be made for `$string` and also a possible variable called `$hwb` that uses the `hwb` color function. 

![image](https://user-images.githubusercontent.com/22005033/201509423-fb9905e5-a0ff-491d-b511-5dc264350ebf.png)

File: [suggestWidgetRenderer.ts](https://github.com/microsoft/vscode/blob/main/src/vs/editor/contrib/suggest/browser/suggestWidgetRenderer.ts)

This function only adds the preview color for elements that have rgb, hsl, or hex codes. It ignores all other values. I am pushing a potential fix that adds an extra condition when the Completion Item Kind is color and the color cannot be extracted using Regex. This would handle cases such as the internal color issue because the CSS Extension can easily determine if the color is an internal color but the main code cannot.

**Comment by aeschli** [comment]
Marking this as dup of https://github.com/microsoft/vscode-css-languageservice/issues/314
