### ISSUE TITLE
Terminal buffer is no longer read by NVDA

### ISSUE THREAD

**Issue by justas2481** [microsoft/vscode#166238]
Type: <b>Bug</b>

When I use CTRL+up/down arrow in a terminal output / terminal buffer, screen reader (NVDA) says list item 1/10 for example and nothing more. I'm sure that output is there, because if I use applications key and press select all, then hit applications again and copy / paste to some text editor, I I get the output. Please fix, because now terminal is rendered useless and that is really important with something like Java where is way harder to use native CLI by enterring commands manually.

VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T04:27:29.066Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.15.0-52-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|23.76GB (13.29GB free)|
|Process Argv|--crash-reporter-id 9299f5d7-25a9-4bcd-a568-4b4322b2c507|
|Screen Reader|yes|
|VM|40%|

|Item|Value|
|---|---|
|Remote|SSH: 192.168.65.128|
|OS|Linux x64 5.15.0-52-generic|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (4 x 2303)|
|Memory (System)|7.73GB (5.60GB free)|
|VM|100%|
</details>

**Comment by pleveris** [comment]
Yep, this indeed would be an important fix for screen reader users!

**Comment by snufas** [comment]
@andreamah  @isidorn 
yep, the issue is there...
I wonder why does it say "List item"? something has been changed for sure...

Interesting behavior though, I just tested with simple Python script that asks to enter the player name
the output is like so:

Enter the player name; and ask for input here,  
the screenreader reads that line   repeatedly whenever I enter the 1st letter of the word behavior is like so
if I type John Doe
the screen reader would tell me J "please enter the player name" D "please enter the player name" 
I am assuming that  is by design? I

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/164684
