### ISSUE TITLE
Do not see full path for settings.json, keybindings.json

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#16623]
Testing #15808 

- VSCode Version: 1.8.0-insiders a8d5b9
- OS Version: MacOS

Steps to Reproduce:

1. Open Settings (`CMD+,`)
2. Set `"window.showFullPath": true`

Result: i do not see the full path in the title bar to `settings.json`.  if i open other files in my workspace, everything seems to work properly

And, I see the same behavior for the workspace `settings.json` and `keybindings.json`, i don't see the full path in the title bar.

**Comment by bpasero** [comment]
what the St Nicholas... ❓

**Comment by chrisdias** [comment]
settings.json has focus...
![image](https://cloud.githubusercontent.com/assets/1487073/20923863/d439d1a0-bbae-11e6-92aa-ef32267ddd93.png)

Dockerfile has focus...
![image](https://cloud.githubusercontent.com/assets/1487073/20923874/deeb188e-bbae-11e6-871e-1cd18751a18d.png)

**Comment by chrisdias** [comment]
I do see the full path when I select the `settings.json` file directly in the `.vscode` folder through the explorer.

![image](https://cloud.githubusercontent.com/assets/1487073/20924187/8b647e42-bbb0-11e6-94b1-1bcbeeaf936f.png)

**Comment by bpasero** [comment]
@sandy081 this is a consequence of using the `SideBySideEditorInput` for settings and keybindings. The title only looks for files being opened to show the full path and I think it should not check for side by side editors because that would mean we would show the path for diff editors, which is not wanted.

I wonder if we should start to make the name of the editor more explicit towards the fact that it is a settings editor. I see a chance to:
* call it User Settings when opening that
* Workspace Settings otherwise
* or just Keybindings

Moving to you to decide how to proceed here.

**Comment by sandy081** [comment]
I think giving a logical name might hide the file name and which would cause discoverability issue. I am not sure hovering on the title can be the solution for seeing the full path incase of providing logical names

**Comment by sandy081** [comment]
Moving this to January as it is not a pressing issue for this milestone

**Comment by bpasero** [comment]
I think a good solution would be to add a flag to `EditorInput.getName()` so that `history.ts` can ask for either a verbose name (with full path) or not. Then it is up to the inputs to decide how to implement it as opposed to checking for the editor being a file and then doing it in `history.ts`.

**Comment by sandy081** [comment]
@bpasero With latest changes in window title area does the above solution still applies? Another solution which I am thinking is to provide a function `getResource` in `PreferenesEditorInput` that returns file resource. Do you think it makes sense?

**Comment by bpasero** [comment]
@sandy081 yeah the code is still the same around how to get the absolute path: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/parts/titlebar/titlebarPart.ts#L165

Not sure your solution is a good one because there is a difference between your editor and the editor when showing just the file. To the outside returning the same resource might cause some unwanted behaviour where code expects the editor to be a file editor and nothing else. Basically we would have to check each call to `toResource` to see if it can deal with a side by side editor.

**Comment by sandy081** [comment]
@bpasero Right, I see the drawback of the solution. 

But, asking verbose name from editorInput for activeFilePath does not sound symantically correct to me. Having an API for file path in editorInput is also not correct. Not sure if we can change the variable activeFilePath just for this case.

**Comment by bpasero** [comment]
Needs thinking...

**Comment by bpasero** [comment]
I renamed the `window.title` variables to be non-file specific so I think this should enable us to do something smarter for settings. The variables are now called `activeEditorLong/Medium/Short` and can work with any kind of editor 👍

**Comment by huangzhiyang166** [comment]
I want show full path, so i set window.title :  "${dirty}${activeFilePath}${separator}${rootPath}${separator}${appName}"  , but not work

**Comment by bpasero** [comment]
Late in the end game we decided to rename ${activeFilePath} to ${activeEditorLong}. Then it should work.

**Comment by bpasero** [comment]
@sandy081 I pushed a change to add `EditorInput.getTitle(verbosity)`. It is up to the editor input to now provide this information, so you can add it to your editors. The verbosity flag maps 1 to 1 to the setting (short, medium, long title).
