### ISSUE TITLE
[html] HTML, script type=langid should properly tokenize any mode

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#16629]
Testing #16526

We used to be able to tokenize any mode inside a `script` tag, as long as the user provided the correct `type` attribute.

![image](https://cloud.githubusercontent.com/assets/22350/20923657/ca836802-bbad-11e6-9bb4-724365da5a00.png)

**Comment by aeschli** [comment]
This is no longer supported. Browsers typically only support scripts of type javascript.
What does <script 'type=markdown'> mean anyway?

**Comment by joaomoreno** [comment]
Many build tools support it. Some runtime tools do too. [Python](https://github.com/search?utf8=%E2%9C%93&q=script+type+text%2Fpython+extension%3Ahtml&type=Code&ref=searchresults), [TypeScript](https://github.com/search?utf8=%E2%9C%93&q=script+type+text%2Ftypescript+extension%3Ahtml&type=Code&ref=searchresults), [CoffeeScript](http://coffeescript.org/#scripts).

**Comment by aeschli** [comment]
Requires a enhancement request to the textmate grammar we use (https://github.com/textmate/html.tmbundle)

**Comment by aeschli** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.
If you disagree and feel that this issue is crucial: We're happy to listen and to reconsider.
Maybe you want to give it a try yourself and provide the feature through an extension or a PR: We're happy to give advise and get you started.
Thanks for your understanding. Thanks for helping and happy coding!
