### ISSUE TITLE
[Bug] [VSC-Web] Pasting dependence on ClipboardEvent

### ISSUE THREAD

**Issue by MasterInQuestion** [microsoft/vscode#166231]
Pasting would be seriously broken (input content messed by "Refactor") when ClipboardEvent API is unavailable (e.g. disabled in Firefox via "dom.event.clipboardevents.enabled").
    This should be optimized.

    Also, even simple function like "Cut" has dependence on such. Which is beyond reasonable.

&#x2D;---

Version: 1.73.1
Commit: 6261075646f055b99068d3688932416f2346dd3b
User Agent: Mozilla/5.0 (X11; Linux x86_64; rv:106.0) Gecko/20100101 Firefox/106.0
Embedder: vscode.dev

**Comment by alexdima** [comment]
@MasterInQuestion What are the steps here? In the editor, if you use the default `ctrl+x`, `ctrl+c`, `ctrl+v` without any keybinding customizations, cut, copy, and paste should work regardless of the browser clipboard API, since they would generate native `cut`, `copy`, `paste` events.

**Comment by MasterInQuestion** [comment]
Exactly like what you describe.
    Firefox 106 (probably also other versions), in "about:config" set "dom.event.clipboardevents.enabled" to false.
    Then just play with the editor. (obvious one: "Cut" doesn't cut)

    Pasting input: try random XML.

**Comment by alexdima** [comment]
Indeed, I can reproduce `cmd+x` not working after setting "dom.event.clipboardevents.enabled" to false. `cmd+c` and `cmd+v` work correctly.

**Comment by MasterInQuestion** [comment]
Would pasting this [ [https://github.com/MasterInQuestion/Markup/raw/main/!clock.htm](https://github.com/MasterInQuestion/Markup/raw/main/!clock.htm) ] work normally?

**Comment by alexdima** [comment]
This works as designed. After setting`"dom.event.clipboardevents.enabled" to false`, Firefox no longer emits cut, copy or paste events. In this case, copy works because we always maintain the selection in the hidden textarea, and paste works because we think it was typed into the editor. But Firefox does not emit cut, copy or paste events.

I've used the following test page to track this down: https://jsfiddle.net/5vu8ojhm/

**Comment by MasterInQuestion** [comment]
This is extraordinary.
    Receiving these events or not, the basic operations should not be interfered.

    It appears the app has wrapped the handling of such basic operations; and which has dependence on ClipboardEvent API.

**Comment by alexdima** [comment]
The VS Code editor is implemented using DOM concepts. The blinking cursor in the editor is not a blinking cursor coming from the browser, it is a dom node which is animated to show and hide. For example, this allows us to implement a feature called multiple cursors, which is not available in native browser inputs.

We also implement other useful features that are not available in native inputs, like an overview ruler in the scrollbar, rendering squiggles and other annotations on text, supporting vertical gaps between lines or supporting opening files with millions of lines which would otherwise crash all native inputs, etc. 

In order to implement `cut` in our custom widget, we need to listen on the `cut` event. I haven't studied the way `"dom.event.clipboardevents.enabled"` is implemented in detail, but there are two concepts for dealing with the clipboard in the browser:
* `cut`, `copy`, `paste` events (these events are >10 years old and safe)
* the `navigator.clipboard` API (this is relatively new API <5 years)

The `navigator.clipboard` API allows a web page to read and write to the clipboard at any time. Someone who is very privacy oriented might want to deny access to this API to websites they don't trust. The problem is placing something sensitive in the clipboard (like a password) and then hovering over a page which then can read the clipboard data.

The `cut`, `copy`, `paste` events API are events emitted securely by the browser when pressing the cut, copy, paste keybindings or choosing Cut, Copy or Paste from the Edit menu. These events give access to a clipboard API during the event handling. So only if you press `cmd+v` will a webpage get the `paste` event and be able to read your clipboard. This is as secure as pasting to a native input box. If you find a case where this doesn't apply, then I believe you have found a security issue and I encourage you to report this securely to browser maintainers.

My suggestion would be to reconsider turning `cut`, `copy`, `paste` events off, as IMHO this doesn't give any privacy or security advantages. But I agree that turning `navigator.clipboard` off gives increased privacy and security advantages. I don't know if there exists a Firefox flag that allows turning off only `navigator.clipboard` but allow `cut`,`copy`,`paste` events.

**Comment by MasterInQuestion** [comment]
Thanks for the suggestion. I know about the details.
    The primary intention is to prevent unwanted clipboard meddling by certain web apps.
    Plus some lightweight defense against typical selection poking.

    "navigator.clipboard" access is typically directly configurable in apparent UI. (as displayed in [ [https://code.visualstudio.com/docs/remote/codespaces#_how-do-i-allow-vs-code-to-access-my-clipboard-for-reading](https://code.visualstudio.com/docs/remote/codespaces#_how-do-i-allow-vs-code-to-access-my-clipboard-for-reading) ])

    Access to Clipboard or ClipboardEvent API, is not necessary to support the elementary text editing functionality:
    As demonstrated in similar web editor projects like [Ace](https://www.google.com/search?hl=en&gl=us&num=10&q=ace.js) (ace.js).
