### ISSUE TITLE
keymaps are confusing to configure

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#16638]
IMO  keymaps are similar to themes and icon themes. You get them from the marketplace, can install many, but only one is active at a time. For themes and icon themes we have an aligned story which goes in two steps (1) install extension, (2) enable theme. For keymaps we chose a different approach and I don't understand why? Also, the message to disable other extensions that happen to have set the `Keycaps`-category is easy to dismiss leaving me without an explicit action to configure the active keymap-extension.

**Comment by jrieken** [comment]
@Microsoft/vscode other opinions/feedback/ideas?

**Comment by joaomoreno** [comment]
Relevant discussion in #15159

**Comment by jrieken** [comment]
![dec-06-2016 12-39-02](https://cloud.githubusercontent.com/assets/1794099/20924282/0e501140-bbb1-11e6-979e-a11ab736e339.gif)

**Comment by bpasero** [comment]
+1 for having a picker to choose the keymap from. I would even argue that we should ship with keymaps most popular editors out there and guide the user how to switch.

**Comment by chrmarti** [comment]
Having a picker implies having the available keymaps built-in if I understand correctly.

Simple keymaps might not be too hard to have built-in. We would also need to consider the Vim case which comes as a full-featured extension.

**Comment by joaomoreno** [comment]
> Having a picker implies having the available keymaps built-in if I understand correctly.

How come?

**Comment by alexandrudima** [comment]
[Theme contributions](https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributesthemes) are mutually exclusive: if multiple extensions contribute multiple themes, only one theme can be selected at a time.

[Keybindings contributions](https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributeskeybindings) are cummulative: if multiple extensions contribute multiple keybindings, they all get appended and merged into the default keybindings.

This is IMHO similar to installing two or three extensions that add rich language features to the same language (e.g. extensions `A`, `B` and `C` all contribute go to definition for php). For an end user, it maybe would not make sense to have `A` and `B` and `C` active at the same time, as they try to cover the same functionality. We would not build a custom UI to pick between `A`, `B` and `C`, unless we add some new concept to `package.json`.

**Comment by chrmarti** [comment]
The keymaps we have focused on are close to mutually exclusive because they cover much of the same commands. It might also confuse users to get the result of overlapping keymaps. (Not sure which wins when there is overlap.)

**Comment by rebornix** [comment]
Making keymaps exclusive (or ppl think it's exclusive) requires two steps:

1. Keymap authors write the keymap as complete as possible, even if it shares most of the same keybindings as Code does. 
2. You can only choose one keymap at one time.

Step 1 is like a best practice as we don't want to break the experience if Code changes the keybindings for a command somehow. It's controllable as right now most of the keymaps are maintained by us but there is no such guidance for community authors.

Step 2 is *missing* as right now you can choose not to disable the second keymap. Users might do this by purpose as they want to enable multiple keymaps and fix the overlap/conflicts themselves.

Making it real exclusive is difficult as above while making it cummulative provides the possibility to choose your favorite key bindings but it's a little confusing and is not Intuitive.

**Comment by bgashler1** [comment]
I wonder if anyone is using more than one keymap at the same time?  Seems unintuitive in how conflicts between different keymaps would be resolved.

Personally, I like the idea of a picker for mutually exclusive keybindings.  What we could do is possibly make an activation event for when a keymap is active. That way, when the Vim keymap is selected, the rest of the Vim extension can run (this could also be applied to any other extension supporting modal emulation).

**Comment by waderyan** [comment]
These are great thoughts. 

I recommended the current approach to @chrmarti. My reasoning was as follows. 

1. The value of showing the keymap's README and contributions.

I ended up not recommending the picker because I want users to have the opportunity to see the keymap's README and contributions before installing. For both themes and icons you can preview what you are installing from the picker. Not so with keymaps. The best preview for keymaps is in the contributions tab. 

> Well, why not open the README from the picker?

This is a valid suggestion and we considered it. I did not recommend it because it would not be consistent with themes / icons experience. 

The MP query seemed a straight forward way to get users to the READMEs.

2. We want to move away from a curated list. 

Initially, I wanted to ship with keymaps already installed and allow you to switch between them. I pivoted away because of the downsides of keeping a curated list (note - we ended up going with a curated list, but that was for a different reason that will be addressed in time, see https://github.com/Microsoft/vscode/issues/16156). There didn't seem to be significant value to ship with keymaps when we could get them so easily from the Marketplace.  

My comments on mutual exclusion:

In principle, we want these extensions to have command coverage and be mutually exclusive. In reality they are not. Keymaps can be used together as different products have different command / keyboard shortcut coverage. @chrmarti and I landed on the message box experience as a way of warning a user that they will likely see conflicts. If they want to proceed they can. 

(As a single data point - @rebornix uses two keymap extensions: Visual Studio and Sublime Text.)

I don't have customer data that this is the right experience, nor do I have customer data showing that customers want us to ensure they don't have more than one keymap installed (a route that would enforce only one keymap extension at a time). 

My preference is we keep the experience as is and see how customers respond.
