### ISSUE TITLE
Extension output missing new lines

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#16640]
- VSCode Version: 1.8.x
- OS Version: Windows

See screen shot

![capture](https://cloud.githubusercontent.com/assets/1931590/20924599/89718ca4-bbb2-11e6-939e-75f52ffe0ddd.png)

Not clear is this is the debug console or the extension host test support.

**Comment by bpasero** [comment]
I can reproduce. This is a regression from stable and I am not sure what to do here because all I do in https://github.com/Microsoft/vscode-extension-vscode/blob/master/lib/testrunner.ts#L45 is to run the mocha tests programmatically (triggered from https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/node/extensionHostMain.ts#L156).

I would expect the newlines to show up since the output of Mocha contains them.

**Comment by isidorn** [comment]
Previosuly we were artifically adding newlines between output events in the debug world. Now we just append output as it comes.
@bpasero are you sure that you are sending me strings that end with '\n'

**Comment by bpasero** [comment]
I have to check what mocha produces but I would assume it should contain newlines.

**Comment by isidorn** [comment]
@bpasero also take note that mocha test get nicely formated when run for instance in vscode repo or vscode-node-debug

**Comment by bpasero** [comment]
@isidorn are those extension tests?

**Comment by isidorn** [comment]
@bpasero no, that is the difference

**Comment by bpasero** [comment]
@isidorn I looked into it and mocha correctly uses console.log for each line it wants to output. This travels over to the debugService via broadcast and is then appended to the repl by joining the arguments with whitespace. This is not good because each entry should produce a new line at least when it comes from the extension host.

I believe this is a regression from handling the extension output and the debug output in the same way.

**Comment by bpasero** [comment]
Btw an easier repro is to just console.log multiple times from an extension.

**Comment by isidorn** [comment]
Yes I was trying not to have two code paths for dealing with output from extension and debug. We can simply add a fake \n for every output that comes from extension host on the debug side near the code pointer you put

**Comment by bpasero** [comment]
Yeah that would probably help, since this broadcast is only ever triggered from a `console.log`, `console.error` or `console.warn` it makes sense to print it on separate lines each.

**Comment by isidorn** [comment]
Ok now I am appending a new line on each output coming from an extension.
We need to verify this does not break stuff.

Also it feels a bit ugly that I need to do this.
