### ISSUE TITLE
Snippets: default variable value makes snippet treat the variable as regular text

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#16668]
Refs #15873 

Have the following snippet. Insert your snippet in a text, notice how the postCode is not being treated as a variable. It is being nicely treated as a variable if no default value is specified.

```js
provideCompletionItems(document, position, token) {
            
	    const mySnippet = new vscode.SnippetString();
            mySnippet.appendText('zurich ');
            mySnippet.appendVariable('postCode', '8008');
            
            const item = new vscode.CompletionItem('ZURICH', vscode.CompletionItemKind.Class);
            item.insertText = mySnippet;

            return [item];
        }
```

**Comment by jrieken** [comment]
> It is being nicely treated as a variable if no default value is specified.

It is treated as *placeholder* because it is undefined and has no value. That is very special and exists only because we have been falsely advertising TM snippet syntax (even for static snippets) and confused variables and placeholders. We have document that here: https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/snippet/common/snippet.md#L15.

Undecided yet how to proceed with unknown variables that have a default value. The implemented behaviour is correct in TM-terms but I have to see what else we have been falsely selling as TM-syntax
