### ISSUE TITLE
Ctrl+c to copy in terminal should clear the selection

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#166697]
This has bugged me for years but wasn't sure how we should handle it. I think we should do this:

- ctrl+shift+c: works as it does now, when there is a selection this will copy the selection and retain it
- ctrl+c: if this is bound to copy when there is a selection (Windows), it should copy the selection _and clear it_, such that the next ctrl+c will send an interrupt.

**Comment by ssbarnea** [comment]
On Unix (MacOS and Linux), `CTRL-C` is used alongside `CTRL-Z` to control the run sending intetrupt signal to the process for the first and suspend for the other.

I ended up on this ticket because Ctrl-C was not working to stop the Python debugger with CTRL-C in vscode. Windows version of the debugger uses Ctrl-D for that, but don't be confused that is only for Windows.

Clearly something wrong is happening with Ctrl-C on vscode terminal for sure. While looking at this bug may it be possible to address the Ctrl-C not being send to the terminal?

**Comment by Tyriar** [comment]
@ssbarnea ctrl+c does send SIGINT, it works a little differently on Windows though; if there is a selection it will copy. The proposal here is to copy and clear the selection, such that the next ctrl+ sends SIGINT.

You can verify that ctrl+c is sending SIGINT by running the toggle escape sequence logging command as that will show what gets sent to the process.

**Comment by Tyriar** [comment]
This is a minor feature that would be good to call out in the release notes.
