### ISSUE TITLE
Display language change not taking effect for extensions running in remote extension host

### ISSUE THREAD

**Issue by zWingz** [microsoft/vscode#166836]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:  Codespaces
- OS Version: Codespaces

Steps to Reproduce:

1. change display language to `zh-cn`
2. see scm view

Some of the characters are Chinese and some are English

<img width="623" alt="image" src="https://user-images.githubusercontent.com/13031838/202988814-775e173a-4307-4d4b-937d-369d6c102d2f.png">

<img width="808" alt="image" src="https://user-images.githubusercontent.com/13031838/202988689-aac19798-8652-424c-b841-6eaea1c4afdc.png">

**Comment by TylerLeonhardt** [comment]
/duplicate https://github.com/microsoft/vscode/issues/165974#issuecomment-1310465539

This will be fixed in the next stable release of vscode projected for this week.

**Comment by zWingz** [comment]
<img width="841" alt="image" src="https://user-images.githubusercontent.com/13031838/206388744-41a2da2c-f633-4d3d-bffd-d089919fe8c0.png">
It still not work on Codespace in 1.74.0
<img width="527" alt="image" src="https://user-images.githubusercontent.com/13031838/206388827-8777ecb0-74e1-4e28-9386-7706b0c42762.png">

**Comment by TylerLeonhardt** [comment]
Yes this is actually a different issue. Nice catch. The problem here is that you have a client (your browser) and your remote (the Codespaces machine). The Language pack is being used for the _client_ but not the _remote_ and the Git extension runs on the remote side.

Through various brute forcing, this can eventually work... but it's not intuitive at all. Here's an example:

![image](https://user-images.githubusercontent.com/2644648/206539704-c091d552-16ff-4847-9d76-b38401e0ea27.png)


You can see that I have the Spanish Language Pack installed on the remote side... I don't remember when I did that or how... but I have it there. If I set to Spanish, it works:
![image](https://user-images.githubusercontent.com/2644648/206539880-3c6abe77-8d90-450e-81bf-2313f1e94044.png)

However, now I try Chinese:
![image](https://user-images.githubusercontent.com/2644648/206540226-0b92c93b-7d56-40d3-a721-817db19f30c6.png)

my UI is in Chinese but the language pack is not installed on the Remote side so the Git extension isn't translated:
![image](https://user-images.githubusercontent.com/2644648/206540345-ea0d5f59-439e-4f8b-a222-a2a42e713d10.png)

We need to make sure that setting the language in the client gets properly sent to the remote and the language pack installed.

**Comment by zWingz** [comment]
@TylerLeonhardt you can download the language pack install it from vsix, then restart the codespace.

**Comment by M69W** [comment]
Maybe same issues like https://github.com/microsoft/vscode/issues/168683#issuecomment-1344945234

**Comment by TylerLeonhardt** [comment]
So this should work on Desktop now but there's still some work to be done on the web for this.
