### ISSUE TITLE
Syntax highlighting breaks when editing a Python file that is also in a GitHub repo

### ISSUE THREAD

**Issue by Tetrapak0** [microsoft/vscode#166865]
I have recently noticed that VS Code keeps breaking syntax highlighting when I edit my code. I noticed it only happen in Python files, that are in a Github Repo.practically drives VS Code useless for me as Python is currently the only language I know and it throwing errors that don't exist at me like it's no tomorrow is just not ideal. This also happens on the insiders version, but doesn't seem to happen on Linux. Because of this I have temporarily switched to PyCharm until this bug is fixed. 

https://user-images.githubusercontent.com/112382253/204102407-fbdeb27d-5b07-471a-b4cc-ce1f8c739584.mp4

**Comment by DiDeoxy** [comment]
I have been having this same issue since last week on Mac OS 12.6.1. I thought maybe it was related to extensions or linters that I installed but after aggressively eliminating all warnings and errors in my VSCODE logs I have not solved the problem. I also tried eliminating any settings issues by running the following commands:

`
rm -fr ~/Library/Preferences/com.microsoft.VSCode.helper.plist
rm -fr ~/Library/Preferences/com.microsoft.VSCode.plist
rm -fr ~/Library/Caches/com.microsoft.VSCode
rm -fr ~/Library/Caches/com.microsoft.VSCode.ShipIt/
rm -fr ~/Library/Application\ Support/Code/
rm -fr ~/Library/Saved\ Application\ State/com.microsoft.VSCode.savedState/
rm -fr ~/.vscode/
`

and by re-installing vs code.

I also looked for issues in all of my settings.jsons but found none.

I can say that the error does not occur when I edit a file in a copy of the repo using Remote-SSH to a remote HPC cluster running Linux.

**Comment by andreamah** [comment]
Hi @Tetrapak0! Would you be able to share some screenshots of your issue?

**Comment by amal-khailtash** [comment]
This might be related to: #165225.  Some screenshots are included.

**Comment by Tetrapak0** [comment]
> Hi @Tetrapak0! Would you be able to share some screenshots of your issue?

I have added a screen recording of this bug.

**Comment by Tetrapak0** [comment]
I fixed this by installing an older version of Pylance. Specifically 2022.11.20
