### ISSUE TITLE
VSCode suggestions/intellisense not coming up unless I leave the quotes and go back in.

### ISSUE THREAD

**Issue by Phoebian** [microsoft/vscode#166824]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.73.1
- OS Version: Windows 10 22H2 19045.2251

Steps to Reproduce:

Test 1: I type `<input type` and press `tab`. VSCode populates the `=""` and provides me a list of all possible options for the attribute type.

Test 2 (Which I believe does not work correctly): I type `<input type=`, it automatically populates the double `""`. It does not provide any suggestions/Intellisense for my options for the attribute type. That is, until I leave and re-enter the quotes and press a letter, only then does it provide me with examples based off the letter I type, but not all that are available.

Is this normal behavior? It seems odd if it is.

I would have liked to be shown all possible options regardless of whether VSCode completed the code when I pressed `tab` (like in the Test 1), or if I manually type it out and it populates `""`.

[GIF example here](https://i.stack.imgur.com/k0l1X.gif)

**Comment by jrieken** [comment]
When a snippet is active, IntelliSense as you type (aka quick suggestions) is disabled. That is because there is a conflict between the <kbd>Tab</kbd>-key which moves to the next placeholder but also accepts a completion. You wouldn't be able to type in a placeholder and then move to the next placeholder as you would accept a suggestion then. You have the following options

* change the default via the `editor.suggest.snippetsPreventQuickSuggestions`-setting
* in snippets trigger suggestions manually (via Ctrl+Space, Alt+ESC (macOS), or `ctrl/cmd+i`)

**Comment by AhmedMohamedDesoky** [comment]
> عندما يكون المقتطف نشطًا ، يتم تعطيل IntelliSense أثناء الكتابة (ويعرف أيضًا باسم الاقتراحات السريعة). وذلك بسبب وجود تعارض بين Tabالمفتاح -key الذي ينتقل إلى العنصر النائب التالي ولكنه يقبل أيضًا الإكمال. لن تتمكن من كتابة عنصر نائب ثم الانتقال إلى العنصر النائب التالي حيث ستقبل اقتراحًا بعد ذلك. لديك الخيارات التالية
> 
> * تغيير الافتراضي عبر `editor.suggest.snippetsPreventQuickSuggestions`الإعداد
> * في المقتطفات ، قم بتشغيل الاقتراحات يدويًا (عبر Ctrl + Space أو Alt + ESC (macOS) أو `ctrl/cmd+i`)
