### ISSUE TITLE
Integrated Terminal is buggy, cursor jumps to line start and old commands are removed by hitting up arrow 

### ISSUE THREAD

**Issue by snake-py** [microsoft/vscode#167044]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.73.1
- OS Version: Ubuntu 20.04

Steps to Reproduce:

1. So this will randomly happen to me and I am unsure how to reproduce 
My integrated terminal is pretty messed up. When I start to delete characters the cursor will jump to the beginning o f the line also if I hit upwards the selected line will move upwards and remove older commands. 

![image](https://user-images.githubusercontent.com/59285387/203532430-ec83096b-759a-4ae9-84eb-621fc6a20057.png)

Below you will see also a video of the bug:
[Screencast from 18.11.2022 13:40:25.webm](https://user-images.githubusercontent.com/59285387/203532290-ca5cf146-5cc1-4211-b84e-636aa6fcdc9a.webm)

**Comment by Nicoolandgood** [comment]
Same here. I also use Ubuntu 20.40 with VsCode 1.73.1. Sometimes even entiere lines are deleted. For me it happens when i press arrow keys to jump to previously used commands et move the cursor to change some parameters.

I tried to reproduce and it looks like this:

https://user-images.githubusercontent.com/102982398/203534758-f4061a38-d0b1-4725-ab1b-a7e993575465.mp4
