### ISSUE TITLE
Notebook webview is frequently positioned incorrectly

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#167087]
I've seen this a lot over the past month and it seems like a major issue for notebooks, please consider investigating further for November

![image](https://user-images.githubusercontent.com/2193314/203622712-dd0403c1-dafa-4eb8-babe-e494886d53f4.png)
![Recording 2022-11-11 at 11 05 48](https://user-images.githubusercontent.com/2193314/203622731-4213926b-09c3-4008-af0e-142c024da294.gif)
![image](https://user-images.githubusercontent.com/2193314/203622751-0a250609-9a08-4104-9270-202e10b84cd0.png)
![image](https://user-images.githubusercontent.com/2193314/203622765-38fdb4cd-0a10-43c0-807b-4c1cfa80c86c.png)

---

While running integration tests today (23rd November):

![Recording 2022-11-23 at 10 33 58](https://user-images.githubusercontent.com/2193314/203622639-67a80931-c8e3-47b1-8882-fc1c9751cacc.gif)

Version: 1.74.0-insider (user setup)
Commit: 58e7c7b8865e3c3ea77055461ffb5d656a7a46af
Date: 2022-11-23T05:25:25.108Z
Electron: 19.1.3
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes

**Comment by rebornix** [comment]
@mjbvz it's likely related to the position performance optimization this month.

**Comment by mjbvz** [comment]
@rebornix @roblourens Can you try debugging. I can never reproduce this 

The best place to start debugging is:

https://github.com/microsoft/vscode/blob/7ae2857bf0d9d0e01512c959afb59414dfab40cb/src/vs/workbench/contrib/notebook/browser/notebookEditorWidget.ts#L1704

Let me know if you want to pair on this later this afternoon too

**Comment by mjbvz** [comment]
Was finally able to repo this by dragging to create a new editor group (it happens maybe 20% of the time for me)

@joaomoreno @sbatten  I think the root cause is that the notebook widget is passed the wrong position. I'm going to work around this by making the notebook editor ignore the position it is given, however this will also undo the performance fixes we may for notebook layout

I don't fully understand the grid layout code but I believe that `SplitView.layoutContext` is incorrect. Here's what I see happening when creating a new editor to the right of the current editor (splitting a single editor into two:

1. A new Split View is created
2. `layout` is called on it. At this point, `this.layoutContext` is:

    ```
    {orthogonalSize: 1129, absoluteOffset: 0, absoluteOrthogonalOffset: 0, absoluteSize: 759, absoluteOrthogonalSize: 1129}
    ```

3. By the time layout is called on the notebook editor widget, `position.left` is computed as zero. This results in the wrong layout

If I then slightly resize the window, here's what happens:

1. We call `layout` on the split View for the new group 
2. However now `this.layoutContext` is:

    ```
    {orthogonalSize: 1129, absoluteOffset: 265, absoluteOrthogonalOffset: 28, absoluteSize: 760, absoluteOrthogonalSize: 1129}
    ```

3. When we layout the notebook editor, `position.left` is not correctly computed as `658`

Still trying to debug  why `this.layoutContext` is incorrect in the first case but that's likely a fix for December. For November, I'll work on more scoped fix just for the notebook widget

**Comment by joaomoreno** [comment]
Created new issue: https://github.com/microsoft/vscode/issues/167816
