### ISSUE TITLE
'Add configuration' doesn't work on empty launch.json

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#16709]
Testing #16214:

- create launch.json, clear its content. Try 'Add configuration' button. Doesn't work.

**Comment by isidorn** [comment]
@aeschli what would be the expected behavior for you here?
That we generate the whole launch.json until 'configurations' and trigger inteli-sense there. Or that we simple trigger intelisense so user can build up his launch.json

There are quite some corner cases so at the moment the add configurations does something only if there is a 'configurations' attribute.
We could also remove the action is the launch.json is not in a good state

Let me know what you think is best. Thanks

**Comment by aeschli** [comment]
It's just a nice-to-have. I was thinking that when you don't see the configuration array, just set the content to the default content (version and configuration) and go from there. The user can always undo

**Comment by isidorn** [comment]
That is a bit too aggressive imho, but worth experimenting with
