### ISSUE TITLE
adopt conditional breakpoint support

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#1671]
I've added conditional breakpoint support to the debug protocol and node-debug.
To adopt this, please do the following:
In addition to the "lines" attribute of the SetBreakpointsArguments structure, provide the "breakpoints" attribute as well: for each breakpoint just pass the "line" attribute and an optional "expression" attribute.

In the future we will drop the "lines" attribute.

see Microsoft/vscode-debugadapter-node#6

**Comment by weinand** [comment]
@isidorn It is not obvious that the breakpoint context action "Edit Breakpoint" allows to create conditional breakpoints. I suggest to rename to "Edit Breakpoint Condition"

**Comment by isidorn** [comment]
In the future the breakpoint widget might provide additional options for editing a breakpoint, so that is why I choose the general name. We can use the 'edit breakpoint condition' now, but then we might need to rename it in the future.
Also chrome uses the same name, so chrome users would not be surprised.
