### ISSUE TITLE
Clicking edit icon in editable settings.json scrolls horizontally

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#16714]
- VSCode Version: Code - Insiders 1.8.0-insider (c425cd159bd389844e9400be801675f54f2443c7, 2016-12-06T16:53:46.634Z)
- OS Version: Darwin x64 15.6.0

---

Testing #16530

Steps to Reproduce:

1. Open settings
2. Pick any setting
3. Narrow the editable setting.json's editor such that the edit icon no longer fits on the screen
4. Place text cursor on a different line than the setting (important!)
5. Scroll horizontally to reach the setting's edit icon and click
-> Editor scrolls to reveal the first column (where the cursor is now placed)

**Comment by sandy081** [comment]
@chrmarti Nice catch, this is happening because of using decorations for rendering action. I am listening to click event from the editor which has side affect of revealing the beginning of the line. I cannot also stop propagation of the event since it has other side affects. Proper solution is to move away from decorations and use zone/overlay widgets for rendering actions which is needed for other requirements too. Hence moving this to next milestone.

**Comment by ramya-rao-a** [comment]
@chrmarti I am guessing this is no longer applicable with the icon now being in the left gutter?

**Comment by sandy081** [comment]
@ramya-rao-a Right

**Comment by ramya-rao-a** [comment]
Ok, marking as verified so that it doesnt come up in the verification list
