### ISSUE TITLE
Pasting TS code removes indentation

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#167299]
Copy this TS code:
```ts

export type IncludeReference =
	| BaseReference
	| SelfReference
	| RelativeReference
	| TopLevelReference
	| TopLevelRepositoryReference;

export const enum IncludeReferenceKind {
	Base,
	Self,
	RelativeReference,
	TopLevelReference,
	TopLevelRepositoryReference,
}
```

Create an new TS file, disable all auto formatters and paste the copied source.

Actual result:
```ts

export type IncludeReference =
| BaseReference
| SelfReference
| RelativeReference
| TopLevelReference
| TopLevelRepositoryReference;

export const enum IncludeReferenceKind {
Base,
Self,
RelativeReference,
TopLevelReference,
TopLevelRepositoryReference,
}
```

Expected result: Indentation should be preserved.

Maybe this was caused by a community PR that changed how enter rules are applied to pasted text.

**Comment by ssigwart** [comment]
@hediet, I thought you might be referring to #136579, so I was trying to test this out in case my branch broke something. I'm having a little difficulty duplicating this.  Maybe I have the wrong settings. I have `typescript.format.enable` and `editor.formatOnPaste` disabled.

However, I do notice something odd about copying from the code in your GitHub comment. If I manually copy and paste it, I don't see what you do. However, if I use the copy icon GitHub provides, the copied text includes an extra newline at the top.
If I paste that in the current VS Code version or Insider, I see what you're seeing, but also that line 1 is a blank line.

I think what might be happening is that GitHub is not properly displaying your code. I'm guessing the code you actually wrote includes a blank line above it, but GitHub won't render it.

Since I see this in version 1.73.1, I don't think it's my branch that causes this, but please let me know if you want me to try to track down the issue here.

**Comment by ssigwart** [comment]
@hediet, I submitted #167687 that seems to fix this.

**Comment by hediet** [comment]
This happens when pasting the text on the second line:

![Code_-_Insiders_RwT0sgdVhu](https://user-images.githubusercontent.com/2931520/204811511-fcc96e41-45f6-4de9-ba3c-b5e5494bcdb4.gif)

**Comment by aiday-mar** [comment]
Issue closed with the PR https://github.com/microsoft/vscode/pull/167687
