### ISSUE TITLE
Quick open previous editor default setting change to match that of other Ides

### ISSUE THREAD

**Issue by skyhirider** [microsoft/vscode#167337]
When pressing Ctrl + E, Code shows a list of files. The same functionality is in Intellij Idea but it automatically selects the next file, allowing for quick switching.

Code already has a setting for that, I would like to suggest the default be changed so its easier to use for others without needing to spend the time manually searching for the setting (workbench.action.quickOpenPreviousEditor).

**Comment by TylerLeonhardt** [comment]
Does `Ctrl`+`Tab` do what you want?

**Comment by skyhirider** [comment]
No, the only change needed would be to configure "workbench.action.quickOpenPreviousEditor" to use the Ctrl + E shortcut.
Try it in your Code and see what it does.
The change is minor, the previous file is always selected but the list of files remains opened if you need to search for another file instead.
Ctrl + Tab switches to the previous window without keeping the list of files open or allowing you to type in another one.

For example, see https://www.jetbrains.com/pycharm/guide/tips/recent-files/ 

My suggestion is to change the default in Code so that it behaves like other editors, less confusing and easier to use for others (as honestly I think most developers use several Ides or tools for different tasks).

**Comment by TylerLeonhardt** [comment]
Changing the default would impact every single user who uses that default today. If we made this change, undoubtably we would have a bunch of issues asking to change it back. Because of muscle memory, we can't make this change.

This seems like a good candidate for the [jetbrains keymap extension](https://marketplace.visualstudio.com/items?itemName=isudox.vscode-jetbrains-keybindings) though.
