### ISSUE TITLE
Supporting ruler settings

### ISSUE THREAD

**Issue by greybax** [Microsoft/vscode#1673]
Ruler settings would be helpful for showing end of row text.
**Sublime text**:
![1234](https://cloud.githubusercontent.com/assets/3235047/12016568/ae2bb45c-ad5d-11e5-8a91-c8ef43c7a0cb.png)

**Comment by bpasero** [comment]
@alexandrudima fyi

**Comment by tucker-m** [comment]
I'd definitely like to see this as well -- it's the reason I asked [this question](https://stackoverflow.com/questions/34444872/accessing-the-editors-dom-in-a-visual-studio-code-extension) about plugins changing the interface. I'd be nice if one of the options was for it to match the `editor.wrappingColumn` setting.

**Comment by Kroc** [comment]
I use rulers a lot as part of a standard code format that varies slightly from language to language and filetype to filetype. I have a need to be set different rulers on a per-language, per-project basis. For example, text files will wrap at 77, assembly files at 88, HTML/PHP at 124...

**Comment by tucker-m** [comment]
Adding this div below the `.view-overlays` div seems to do it:

```html
<style>
.ruler-thing {
    position: absolute;
    height: 100%;
    width: 80ch;
    border-right: 1px solid white;
}
</style>

<div class="ruler-thing"></div>
```

I'll see about making the width and color configurable, and try making a PR this weekend.

I think Kroc's idea could be done by an extension that switches settings based on what file type is open. That would allow for all types of settings to be changed, including the ruler width.

**Comment by Kroc** [comment]
I believe that a broad range of feature requests for VSCode fit into the bracket of persisting configuration choices on a per-project basis (word-wrap, tab-settings, rulers &c.), so that code formatting standards can be carried from user to user. No editors currently do this comprehensively enough, and I would opt for VSCode over Atom / Notepad++ if I could ensure that people who access my code would get the same tabs/rulers as I use (which I should stress, vary from one filetype to another).

That however, is a different bug/issue; for basic ruler support, a custom width option is crucial. Multiple rulers is nice, but not critical (an extension could handle this). A lot of people like to combine the ruler with the word-wrapping options, so you have to be careful of the complexities that creates. Again, per file-type ruler widths is a feature no other editor has.

Kind regards,
Kroc Camen.

**Comment by Tyriar** [comment]
I prefer to have 80, 100 and 120 set up as rulers in my editors. Multiple rulers would be handy.

**Comment by jamiebarrow** [comment]
Not sure if this is the right place to ask, but is there an easy way to customize the style of the rulers, e.g. using a dotted or dashed line instead of a solid line?
