### ISSUE TITLE
Test Partial Suggestion Acceptance

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#167421]
Refs: https://github.com/microsoft/vscode/issues/140708

- [x] anyOS @eleanorjboyd 
- [x] anyOS @amunger

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23167421%0A%0A&assignees=hediet)

---

## Preparation

* Add this to your keybindings.json file:

```json
{
    "key": "alt+shift+right",
    "command": "editor.action.inlineSuggest.acceptNextWord",
    "when": "inlineSuggestionVisible"
},
{
    "key": "alt+shift+left",
    "command": "undo",
    "when": "inlineSuggestionVisible"
}
```

* Make sure you have Copilot installed.

## Steps

* Use the command `editor.action.inlineSuggest.acceptNextWord` to accept a suggestion partially. Alternatively, use the configured shortcuts to trigger the command.
* Make sure you can use that command to accept parts of a copilot-suggestion.
* Try out different keybindings for this command and report which keybinding works best for you (and which keyboard/OS you use)

**Comment by amunger** [comment]
- used logitec ergonomic keyboard on Windows
- alt-shift-left/right works fine for me. Other modifications on the arrow keys would be fine too, but I think left/right arrow makes the most sense for me.
- it would be nice to continue onto the next line of the suggestion
- the character groups that are completed for a regex are a little odd - it will complete `})\`, including the `\`, but not the character it is escaping.

**Comment by eleanorjboyd** [comment]
- used a Macbook M1 pro, regular mac keyboard
- the alit-shift-right works well, the left one not so much as outlined in issue above
- I agree with @amunger if I could move onto the next line of selection after doing one to make that flow easier
- two different bugs / inconsistencies I found which I just pointed out in those issues above

generally this is a great fix and I have been wanting something like it since I started using co-pilot!
