### ISSUE TITLE
Stable quick pick can not be closed using mouse / touch

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#167546]
Testing #167161

![image](https://user-images.githubusercontent.com/2931520/204555377-1e365f65-ebed-4534-a562-5e91a5a680b0.png)

You need to use the keyboard (escape) to close this dialog.
This is especially problematic for tablet usage.

There are two options:
* Close the dialog when it loses focus (like F1)
* Show a close button in the dialog (the X)

This applies to many such dialogs, but I just noticed this while testing this feature.

**Comment by isidorn** [comment]
As you say I think this is a general quick pick problem - when the quick pick client chooses to create a quick pick that does not hide on blur. I think quick pick currently does not support rendering the X button for closing.

In this use case using a stable quick pick is the way to go imho, so assigning to @TylerLeonhardt since he might have heard similar requests for quick pick in the past.

**Comment by hediet** [comment]
What is the decision criteria of when a quick pick is stable and when not?

**Comment by isidorn** [comment]
When you might need to alt-tab to get something, like a profile URL then it should be stable.

**Comment by gjsjohnmurray** [comment]
Previously discussed in #99081
