### ISSUE TITLE
NVDA is not recognized on Windows After Reload Of VS Code

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#167583]
Testing #167159

Steps:
* Start NVDA
* Start VS Code Insiders
* Screen reader is detected.
* Reload VS Code
* Screen reader is not detected anymore.

**Comment by hediet** [comment]
Updated steps. Stable has the same issue.
It works if not reloading VS Code.

**Comment by deepak1556** [comment]
@isidorn the runtime will emit the a11y event when there is a change triggered by assistive technologies connection to the runtime. So for the reload scenario the application instance already got the event before reload that it has entered a11y mode, after reload the application should query the runtime to determine the current status, for ex: calling https://github.com/electron/electron/blob/main/docs/api/app.md#appisaccessibilitysupportenabled-macos-windows.

**Comment by isidorn** [comment]
@deepak1556 thanks. Sounds like a bug in the https://github.com/microsoft/vscode/blob/main/src/vs/workbench/services/accessibility/electron-sandbox/accessibilityService.ts#L30
So `accessibilityService` should make sure to ask Electron if accessibilitySupport is enabled on start

@meganrogge is this something you might be interested for next milestone?
fyi @sbatten as the original author of `accessibilityService`

Assigning to next milestone since this feels low hanging and high impact
