### ISSUE TITLE
Indent Using Spaces Dissociates Tab Size From Spaces

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#167571]
Testing #167471

* Empty profile

![image](https://user-images.githubusercontent.com/2931520/204591664-b5eb75b0-ee90-43bf-aa83-51e5f4153bff.png)

* Click on "Spaces"

![image](https://user-images.githubusercontent.com/2931520/204592011-d5de1679-dfa2-450b-af21-b5d078b468ac.png)

* Select "Indent using Spaces", chose 3

Then I get this:

![image](https://user-images.githubusercontent.com/2931520/204592098-9f1bc007-25b8-41d7-8b5c-e5777e46b90f.png)

I would expect the tab size to adjust to the indent size.
However, you could argue it also makes sense as it is, in that case feel free to close this issue.

**Comment by chrisant996** [comment]
Ideally there would be a command to set both tab+indent size at the same time (which should be the general default, since that's the most common usage), and also commands for setting tab size and indent size independently from each other.

If no commands set both together, then the experience gets broken for the general case.

If all commands set both together, then the experience is broken for the cases whether tab size and indent size should be different.

**Comment by alexdima** [comment]
I agree, only "Change Tab Display Size" should cause a dissociation between indent size and tab size.
