### ISSUE TITLE
Testing continue working on: dialog for cloning repo

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#167658]
Testing #167433

When cloning a repo to continue working on, I get this dialog:
<img width="387" alt="image" src="https://user-images.githubusercontent.com/31675041/204668175-de8dcf7d-de6a-499f-8a97-c915537942ad.png">

I found it sort of odd that "cancel" wasn't the last option. And what exactly does "open" do? Is that like "Open here"? I felt like it took a little thinking to process this dialog 😅

**Comment by joyceerhl** [comment]
cc @lszomoru as that dialog is from the git extension. In this scenario I think it is appropriate that "Open" is the default option, since presumably the user wants to open the repo they just cloned. I think "Open" refers to opening in the current window but that would be pretty verbose to spell out in full.

**Comment by andreamah** [comment]
That's true.  I think it's the ordering that throws me off a little, since I expect cancel to be off to one of the sides and all of the "non-cancel" stuff to be together. But that does make sense.

**Comment by sbatten** [comment]
yes, what @lszomoru states is correct. Windows has a different ordering and since @andreamah is typically on Windows, I'm guessing that's why this expectation is there. The ordering in the image appears to be correct for the platform.
