### ISSUE TITLE
How to get process id of a process started via RunInTerminalRequest via the debug protocol

### ISSUE THREAD

**Issue by davidanthoff** [Microsoft/vscode#16786]
- VSCode Version: 1.7.2
- OS Version: Windows 10

I'm trying to implement a debug adapter for the julia language. At this stage I'm just trying to get the Ctrl+F5 functionality going. I'm using the ``RunInTerminalRequest`` to start the current julia script. How can I get the process ID for the instance of julia that I'm starting in that way? The ``RunInTerminalResponse`` has an optional field ``processId``, but the response I get for my ``RunInTerminal`` request never contains that information. I tried both the ``integrated`` and ``external`` option for ``kind``, but in neither case do I get a process id back.

**Comment by weinand** [comment]
@davidanthoff VS Code's implementation of `RunInTerminalRequest` has a hard time figuring out the process ID of the process launched through `RunInTerminalRequest` (It just sends a command line to the terminal which passes it to the command interpreter shell. Getting back the process ID from the shell on all platforms is difficult and not yet implemented).

Since running a debug target in an external terminal is optional, I suggest to start by implementing launching the target without a terminal. You can collect any output of the target in the debug adapter and send it back as 'OutputEvents' which VS Code will show in the (builtin) debug console.

**Comment by davidanthoff** [comment]
Thanks! I think I'll just try to start the debug target myself from my debug adapter in that case, probably the simplest solution.
