### ISSUE TITLE
Notebook rendering screen cheese on load

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#167806]
* open `.vscode/notebooks/my-endgame.github-issues`
* :bug: notice how during loading layout shift and ugly overlaps happens

<img width="590" alt="Screenshot 2022-12-01 at 08 55 52" src="https://user-images.githubusercontent.com/1794099/204997151-fa17f790-df8c-4226-970b-469d2780d0c0.png">

https://user-images.githubusercontent.com/1794099/204997107-dc4ec4da-9a94-4a55-a520-04a6a52b82ba.mov

**Comment by rebornix** [comment]
It seems we lost the viewport warmup in this scenario.

**Comment by roblourens** [comment]
I know we lost the horizontal scrollbar fix due to the editor layout optimizations. Is there something else or is it just that?

**Comment by rebornix** [comment]
Fixed via https://github.com/microsoft/vscode/pull/174266

**Comment by alexdima** [comment]
Catching up with notifications...

I think the PR improves this, but FYI @rebornix this issue was created before we switched to `FastRenderedViewLine` for long lines via https://github.com/microsoft/vscode/commit/3ebfaadb9b856e58eef7d84d177a98dc6c149146 on Dec 11th, so I think it was a problem before that.
