### ISSUE TITLE
Error message "Linter pylint is not installed" persists after "Disable this linter" is clicked

### ISSUE THREAD

**Issue by alex75it** [Microsoft/vscode#16796]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:06:37.428Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.5.5|
|csharp|ms-vscode|1.5.3|

---

Steps to Reproduce:

1. Open a .py file.
2. Open another .py file, add something and save.
3. Error "Linter pylint is not installed" appears.
4. Click on "Disable this Linter"
5. Edit the file again and save.
6. Error "Linter pylint is not installed" appears AGAIN.

Note.
Close and restart VS Code does not solve the issue.
I don't want pylint (it is too noisy).

Thanks,
Alessandro

**Comment by mohamed-elsaka** [comment]
same for me on ubuntu 16.04

**Comment by MahonyCZ13** [comment]
Same for me on Win 10 build 14393.447

**Comment by bighomeyg** [comment]
Same for me on OSX 10.12 with VS Code 1.8.1

**Comment by sid8128** [comment]
This annoying pop-up can easily be turned off. Just add the following line to workspace setting file:
"python.linting.lintOnSave": false

**Comment by NableLucas** [comment]
Hi,
Set the configuration manualy. Open or create file settings.json and set parameters.

Example for pep8

vscode/settings.json
{
    "python.linting.pep8Enabled": true,
    "python.linting.pep8Path": "C:/Python27/Scripts/pep8.exe"
}

for the pylint it`s same

**Comment by kieferrm** [comment]
This is an issue with the Python extension. Moved to https://github.com/DonJayamanne/pythonVSCode/issues/763. Please subscribe there.

**Comment by l00c00l** [comment]
I got this message too, even after I have installed it.

**Comment by minorpoet** [comment]
i am wondering how this plugin find python2 / 3  related packages installed via pip / pip3

**Comment by ManPython** [comment]
@NableLucas 
> for the pylint it`s same

Not exactly..
>"python.linting.pep8Path": "C:/Python27/Scripts/pylint.exe"

Should be
 "python.linting.pylintPath": "E:/PYTHON/Python34/Scripts/pylint.exe",

I think that problem is often if ppls has other path of Python in someProject\.vscode\launch.json and the Pylint is instaled to other enviorment eg venv or Python27 or python34

But I can confirm that I'm not happy from this all, and often have some strange issues around Pylint in VSC,

**Comment by boydthomson** [comment]
resolved this issue on VS Code for linux by changing:
"python.linting.pylintPath": "pylint"
to
"python.linting.pylintPath": "pylint3"

**Comment by uint16** [comment]
On Linux(Ubuntu 16.04) one of the following should work

Install pylint using apt
```sudo apt install pylint```

or change
"python.linting.pylintPath": "pylint"
to
"python.linting.pylintPath": "{your pylint package path}"

**Comment by existme** [comment]
This is an **environment** issue, just add the `~/.local/bin/` to whatever profile your terminal is set to use as the default.
Then enable this setting in vscode so it uses the same shell as your default terminal for running tasks:
```json
"code-runner.runInTerminal": true
```
If you do like this you don't need to specifically change the pass for every required externally installed app or extension. 

:information_source: In my case I needed to add `export PATH=~/.local/bin/:$PATH` to my `~/.zshrc` since my default shell is zsh.

**Comment by lyingsheng** [comment]
I met this annoying problem even if i have installed pylint.
I solved it by changing
"python.linting.pylintPath": "**pylint**"
to
"python.linting.pylintPath": "**pylint.exe**"
it works! :D

--
vscode version: 1.15.0 x64 on Windows x64
python: 3.6.1
