### ISSUE TITLE
Please create inbuilt brower search inside visual studio, in tabs maybe or besides terminal 

### ISSUE THREAD

**Issue by swapnilxi** [microsoft/vscode#168089]
it would be great if I could open edge inside vs code and do google searches!
Browser inside visual studio code

**Comment by andreamah** [comment]
You can use a browser within the editor using [Simple Browser](https://stackoverflow.com/questions/37077591/how-do-i-open-a-browser-window-in-a-visual-studio-code-extension). However, you can't access Google using that because Google itself doesn't allow itself to be framed within an iframe. That's a security limitation from Google itself.
