### ISSUE TITLE
debug floater select wrong process

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#16809]
re #15305

* have two nodejs apps (attached below)
* run them both
* select `app.js` in the floater and select pause
* 🐛 the floater reveals `js/app.js`

**Comment by jrieken** [comment]
![dec-07-2016 12-10-05](https://cloud.githubusercontent.com/assets/1794099/20965490/24c8a7c8-bc76-11e6-91c5-0bed306f0749.gif)

both apps
```js
setInterval(function () {
    console.log(__filename);
}, 1000);

```

config
```json
{
    // Use IntelliSense to learn about possible Node.js debug attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "js/app.js",
            "program": "${workspaceRoot}/js/app.js",
            "cwd": "${workspaceRoot}"
        },
        {
            "type": "node",
            "request": "launch",
            "name": "app.js",
            "program": "${workspaceRoot}/app.js",
            "cwd": "${workspaceRoot}"
        }
    ]
}
```

**Comment by isidorn** [comment]
Looking at the gif you select Process A click pause -> Process A gets paused. Then Process B gets automatically selected

This is designed behavior as it seems to me. As the process dropdown always shows the process that is currently focused (and since A is paused now B gets focus automatically).
What is your expected behavior here?

**Comment by jrieken** [comment]
Well, my expected behaviour is that the control stay scoped the process I manually selected and paused. After pausing comes stepping or resume but the floater is now wrongly scoped making me pause the other process

**Comment by isidorn** [comment]
We need to revisit when and how we automatically focus processes.
Joh's suggestion is to only automatically focus process if no other process is stopped. This makes sense to me and I would like to experiment with it in january (nothing for last day of endgame)

**Comment by isidorn** [comment]
I have changed the behavior that we only automatically focus stack frames if no other stack frame is focused (stopped).

Joh had a point that it would be otherwise impossible to debug a multi clustered program which might stop as many times at arbiatary times and then you would always loose focus.
Also bein overly smart and automatically changing focus can screw with the user's expectation of what the global debug actions would do.

FYI @weinand
