### ISSUE TITLE
unsafe repo warning when opening a parent folder that is not a repo

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode#168109]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
```
Version: 1.74.0-insider (user setup)
Commit: 5235c6bb189b60b01b1f49062f4ffa42384f8c91
Date: 2022-12-05T10:17:57.998Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes
```
- OS Version: Windows 11

Description of problem:

I have a folder `src` which is not a git repo, but has sub folders that are repositories. when i open the `src` folder i'm being warned that that the folder is "unsafe"...

![image](https://user-images.githubusercontent.com/1487073/205739267-3ab82b7b-5f7a-44f4-b7d7-9e440cf9e6f8.png)

I also don't understand how the repositories are owned by someone other than the current user (me).  

To Repro:

- create a folder `d:\testtest`
- open that folder in vscode
- assert that you trust the folder
- in the terminal, create a sub-folder (e.g. `d:\testtest\repo1`)
- `cd repo1` 
- `git init`

Result: You are now prompted that the folder is potentially unsafe.

Also, if I say that I trusted the folder, why are we asking again about trust?  I would think that once I trust the parent folder, I trust everything in it...

**Comment by chrisdias** [comment]
here are the git output logs

```
2022-12-05 13:54:17.823 [info] Log level: Info
2022-12-05 13:54:17.823 [info] Validating found git in: "C:\Program Files\Git\cmd\git.exe"
2022-12-05 13:54:19.227 [info] Using git "2.38.1.windows.1" from "C:\Program Files\Git\cmd\git.exe"
2022-12-05 13:54:19.373 [info] > git rev-parse --show-toplevel [136ms]
2022-12-05 13:54:19.373 [info] fatal: not a git repository (or any of the parent directories): .git
2022-12-05 13:54:19.587 [info] > git rev-parse --show-toplevel [206ms]
2022-12-05 13:54:19.587 [info] fatal: detected dubious ownership in repository at 'D:/testtest/repo1'
'D:/testtest/repo1' is owned by:
	'S-1-5-32-544'
but the current user is:
	'S-1-12-1-4264147254-1165426732-340612995-518093424'
To add an exception for this directory, call:
	git config --global --add safe.directory D:/testtest/repo1
```

I did `git config --global user.name` and `user.email` and the prompt goes away.

I wonder if we can be more prescriptive with a solution here in the error message.  i worry that new git users may run into this problem and not know what to do.

**Comment by lszomoru** [comment]
Thanks @chrisdias. The error message in the git output window indicates that the repository is currently owned by `S-1-5-32-544` which is the well-known SID for the `BUILTIN\Administrators` group. The discussion around the handling of the built-in administrators group by git is being discussed in the following issue - https://github.com/git-for-windows/git/issues/3798. 

Couple of things that I would like to track down:
1. How was the repository created so that it is owned by the built-in administrators group
2. How did the prompt go away when running the `git config` commands listed above

**Comment by lszomoru** [comment]
Closing this issue following our conversation from last week:
1. Turns out the repository was cloned from an elevated Terminal window
2. Made couple of improvements following our conversation:
  - Fixed the "Learn More" link to point to the correct anchor
  - Added a section to the docs to call out the scenario in which a repository is closed from an elevated application

**Comment by andreamah** [comment]
I can't seem to get that prompt to show up to click the `Learn More` button, even with the repro steps. Is there another way of triggering it?

**Comment by roblourens** [comment]
It seems like there is nothing to verify here, since it's marked as-designed and has no commit
