### ISSUE TITLE
registerTextEditorCommand doesn't wait for promises to finish

### ISSUE THREAD

**Issue by fcrespo82** [Microsoft/vscode#16814]
- VSCode Version: 1.7.2
- OS Version: Mac and Linux but should affect all OSs

Steps to Reproduce:

1. Create a new extension
2. Register a command using `registerTextEditorCommand`
3. Use `showInputBox` inside the callback
4. The callback returns before the end of the `showInputBox`

The command doesn't wait for the promise to finish.

Shouldn't `registerTextEditorCommand` return a `T | Thenable<T>` just like its **big brother** `registerCommand`, or am I doing something wrong?

**Comment by alexandrudima** [comment]
This is by design. The `registerTextEditorCommand` should run synchronously, as it gets passed in a `TextEditor` and a `TextEditorEdit`, If you wish to show input boxes, then register a regular command and initiate the edit operation when you have all the information (after checking the target editor is still there or hasn't changed). i.e.:

### Bad
```js
function run() {
  var ed = vscode.window.activeTextEditor;
  setTimeout(function() {
    // Don't use captured `ed` here, the editor might have been closed
  }, 10000);
```

### Good
```js
function run() {
  setTimeout(function() {
    // Fine to use vscode.window.activeTextEditor (if it's not null, i.e. all editors closed)
  }, 10000);
}
```
