### ISSUE TITLE
Add Tauri Support

### ISSUE THREAD

**Issue by AbhijithGanesh** [microsoft/vscode#168287]
VSCode will take way less memory and operate faster when Tauri is used. As previously mentioned in the linked ticket. This ticket is made to specifically track the changes for migrating to Tauri.

Linking #118308

**Comment by widersky** [comment]
Tauri has support for many windows, is much lighter than Electron and faster on the backend thanks to Rust. At the moment, the stable version is 1.2 and I am surprised that no one from the VSCode team even considers such a highly scored proposal.

I believe that even if the implementation of Tauri would take a long time, it is worth sacrificing because of the above.

**Comment by plutoniumm** [comment]
> I am surprised that no one from the VSCode team even considers such a highly scored proposal.

Hey @widersky I believe it probably might be because VSCode is a very tightly coupled system, so allowing for Tauri may mean a lot of things need to be decoupled and in fact some completely rewritten considering Tauri low level access is largely in rust
