### ISSUE TITLE
Hot Exit: Opens the same file twice in two separate windows

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#16820]
Testing #16544

* have a file `fileA.txt` that is empty
* run `code-insiders fileA.txt`
* type `asdasd`
* the file is dirty
* close the window
* run `code-insiders fileA.txt`
> Two instances of VS Code appear, both showing `fileA.txt` and one of them also showing an untitled editor. This behaviour is very surprising to me.

![image](https://cloud.githubusercontent.com/assets/5047891/20970308/3ba89388-bc8d-11e6-9065-179d0858df05.png)

**Comment by alexandrudima** [comment]
> Note: This also happens after explicitly setting the option `window.openFilesInNewWindow = false`

**Comment by bpasero** [comment]
This is tricky: on the main side we open one window as instructed from the command line with the file and we also open another window to restore backups. Since we do not actually know the files to restore on the main side (we just rely on the renderer side to do this), we are opening 2 windows without knowing that the same file ends up being opened 2 times.

Imho what should happen is this: if we know that we are restoring empty windows with backups, we just add all the files (as instructed from the command line) to one of those empty windows to avoid that we open multiple windows. This should happen in `windows.ts#open()` method ideally.

**Comment by bpasero** [comment]
I have a PR up for this via https://github.com/Microsoft/vscode/pull/20938 though I am not sure this is the best fix :).

Basically what it does is to see if upon startup we have windows opening with hot-exit files to restore (either folder or untitled). If we find any such window to open, we open 
* files to open
* files to create
* files to diff
inside the first of these windows that upon as a matter of restoring hot-exit data.

So instead of getting an extra window opened for the files to open, they would open into the first window that is being opened as a matter of hot-exit restore.

@Tyriar what do you think?

**Comment by Tyriar** [comment]
I think this is a pretty good fix. It seems to align with how the CLI works when windows are opened as well; instead of opening the files in the last active window, the first window to be restored is selected.

**Comment by bpasero** [comment]
Ok, merged.
