### ISSUE TITLE
Auto Detect Color Scheme broken after switching profiles

### ISSUE THREAD

**Issue by Hzbeta** [microsoft/vscode#168391]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: stable 1.74.0 and insiders 1.75.0
- OS Version: Win11 10.0.22623

Steps to Reproduce:

1. Open Profiles feature by ``workbench.experimental.settingsProfiles.enabled``
2. Originally there was a default profile, now add a profile, name it A, there will be two profiles, this bug does not appear when there is only one profile.
3. Switch system to light theme.
4. Open vscode, then switch the vscode themes of both profiles to light colors and enable Auto Detect Color Scheme for them. Then close vscode.
5. Switch system to dark theme.
6. Open vscode again, it will automatically switch the vscode theme to dark.
7. Switching profiles, the vscode theme will change to light theme because the vscode theme in the other profile is light theme and will not automatically switch to a dark theme unless you manually turn it off and then turn on the Auto Detect Color Scheme option.

After vscode is started, Auto Detect Color Scheme does not work properly after switching profiles, you need to close and reopen it manually, restarting vscode at this time will not solve the problem, the theme will still not be set correctly.

**Comment by A-ClassMed** [comment]
Wow fast response!

**Comment by sandy081** [comment]
@aeschli I think, theme component shall listen to profile switching event and update the theme accordingly. 

https://github.com/microsoft/vscode/blob/62d2aad6a61cb6e9b47f1bd0697c883cd2f0d606/src/vs/workbench/services/userDataProfile/common/userDataProfile.ts#L31

Can you please adopt/fix it?

**Comment by aeschli** [comment]
It's a limitation of the way we implement Auto Detect Color Scheme. When the OS reports a scheme change, we just change the setting `workbench.theme`. We still allow the user to manually change the theme and will see this as an override. We will keep that theme until a new OS scheme change is reported.

When the profile changes, we get the setting change for `workbench.theme` from theme A to theme B. We don't have the information whether theme B was (at the time when profile B was created) manually chosen by the user or whether theme B was a result of autodetecting the OS theme.

A solution (but quite a refactoring) would be to have a specific placeholder `${preferredTheme}` instead of an actual theme.
This is issue https://github.com/microsoft/vscode/issues/91231

Closing in favor of that issue.
