### ISSUE TITLE
Window laggy when resizing

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode#16845]
Testing #15811 

See below. Grab either top or bottom of window, drag up/down quickly, notice that the UI refresh lags.

![image](https://cloud.githubusercontent.com/assets/762848/20983644/15a10a50-bc72-11e6-86a8-02c901438498.png)

<hr>

- VSCode Version: Code - Insiders 1.8.0-insider (7499a9f3c565f4fbe5205e30c8664e5a5a11ae94, 2016-12-06T16:16:15.865Z)
- OS Version: Windows_NT ia32 10.0.14965

**Comment by bpasero** [comment]
I see the same with other electron apps, -> upstream

**Comment by bpasero** [comment]
Actually this is only partially upstream, I think we are just doing lots of things during resize. 

@alexandrudima basically I am calling `workbench.layout()` every time the window.resize event is triggered and this eventually reaches the editor which seems to trigger quite expensive operations:

![image](https://cloud.githubusercontent.com/assets/900690/21014336/e89c996a-bd5d-11e6-8e0e-ba0ad3e781a2.png)

If you have ideas how to maybe improve this let me know. E.g. would it make sense to buffer the resize events a little bit before forwarding the layout call to the editor so that it has more chance to catch up and react?

**Comment by alexandrudima** [comment]
For sure there's some optimization opportunities, especially in the "removing lines from the bottom" case.

**Comment by alexandrudima** [comment]
![16845](https://cloud.githubusercontent.com/assets/5047891/25334541/3e2d2d3e-28ef-11e7-99fe-e896ccb7795e.gif)

I don't believe this is editor related as I can reproduce even when displaying an error message.

**Comment by bpasero** [comment]
There is always lag, but it gets a lot worse once the more editors are opened.

![panel-red](https://cloud.githubusercontent.com/assets/900690/25447539/ddf00716-2ab5-11e7-8c92-c97fecc90843.gif)

**Comment by alexandrudima** [comment]
IMHO the problem here is simple: the window resizes immediately on mouse move as it lives in the main process. The renderer process then needs to react and repaint on a different window size.

There will always be a delay >0 from when the window is physically resized until its contents are painted due to the separation in multiple processes.

The only workaround we could do is to paint a white overlay or something on our side until the user calms down and finishes the resize (i.e. the size stabilizes). We could also try to debounce the resize events. Perhaps our Electron friends hold more tricks up their sleeves.

**Comment by learning** [comment]
I got the same problem, it's so laggy on Windows, especially in High-DPI scaling.

- OS: Windows 10 v1803
- DPI Scaling: 200%

It works well in macOS with Retina Display

**Comment by richardgrantscorpion** [comment]
Same, this needs to be fixed.

**Comment by gamepad-coder** [comment]
I was experiencing other PC issues, and thought this was a symptom.

Glad to see this is expected behavior and  
relieved to know it's not just my PC.

In my search results, I found [a post on Reddit ](https://www.reddit.com/r/vscode/comments/dzd4nt/vs_code_is_unbearably_slow/f86xuk7/?utm_source=reddit&utm_medium=web2x&context=3) where a user noted that resize lag seems to be reduced:
- when you do not have a folder open in the VS Code explorer, and also
- when you set `Code.exe`'s process to a higher priority in Task Manager.

I tried both of these and can confirm they do reduce lag.
Each does a little, doing both considerably reduces resize lag.

All in all, still love VS Code.

**Comment by ottworks** [comment]
Drives me crazy! Until this is fixed, Code will never be as responsive as a native application.

**Comment by axelf** [comment]
The problem still exists under macOS Ventura 13.1

Version: 1.74.1
Commit: 1ad8d514439d5077d2b0b7ee64d2ce82a9308e5a
Date: 2022-12-14T10:33:40.793Z (5 days ago)
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 22.2.0
Sandboxed: No
