### ISSUE TITLE
code-tunnel from snap package fails to start with missing GLIBC symbols

### ISSUE THREAD

**Issue by yanxke** [microsoft/vscode#168427]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.74.0
5235c6bb189b60b01b1f49062f4ffa42384f8c91
x64
- OS Version: Ubuntu 22.04

Steps to Reproduce:

1. Use Snap to install the latest VS Code
2. Run "code tunnel"

Error reported

/snap/code/114/usr/share/code/bin/code-tunnel: /snap/core/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /snap/code/114/usr/share/code/bin/code-tunnel)
/snap/code/114/usr/share/code/bin/code-tunnel: /snap/core/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.27' not found (required by /snap/code/114/usr/share/code/bin/code-tunnel)

**Comment by deepak1556** [comment]
This is expected since VSCode snap is based on Ubuntu 16 and `code-tunnel` executable inside the snap will try to use glibc from the snap which does not support GLIBC_2.27. Please use the tunnel cli standalone installer from https://code.visualstudio.com/#alt-downloads as alternative.

This will get addressed once we update our snap base https://github.com/microsoft/vscode/pull/127320

**Comment by CarrascoFrank** [comment]
same problem here !

**Comment by dvlprlat** [comment]
Same here on Manjaro
