### ISSUE TITLE
Just my code debugging is very slow

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#16847]
#16208

- VSCode Version: Code - Insiders 1.8.0-insider (0d65ced0fa7398dc9d50c39a23a2a8cc8406ff18, 2016-12-07T07:04:22.691Z)
- OS Version: Linux x64 4.8.0-27-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.3.4|
|lorem-ipsum|Tyriar|1.0.0|
|theme-glacier|Tyriar|0.0.10|
|vscode-svgviewer|cssho|1.2.0|
|python|donjayamanne|0.5.5|
|tslint|eg2|0.7.1|
|git-project-manager|felipecaputo|1.0.0|
|Theme-Wombat|gerane|0.0.2|
|md-navigate|jrieken|0.0.1|
|Go|lukehoban|0.6.50|
|vscode-scss|mrmlnc|0.6.0|
|csharp|ms-vscode|1.5.3|
|java|redhat|0.0.7|
|annotator|ryu1kn|0.10.1|

---

1. Clone and open https://github.com/Microsoft/vscode-smoketest-express.git
2. Created the launch.json:

    ```js
    {
        // Use IntelliSense to learn about possible Node.js debug attributes.
        // Hover to view descriptions of existing attributes.
        // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
        "version": "0.2.0",
        "configurations": [
            {
                "type": "node",
                "request": "launch",
                "name": "Launch Program",
                "program": "${workspaceRoot}/bin/www",
                "cwd": "${workspaceRoot}",
                "skipFiles": [
                    "node_modules/**"
                ]
            },
            {
                "type": "node",
                "request": "attach",
                "name": "Attach to Process",
                "port": 5858
            }
        ]
    }
    ```

3. Put a breakpoint at `bin/www:28` on `server.listen`
4. Start debugging
5. Hit the breakpoint
6. Step in, it took 20-30 seconds for the next line to be hit.

Instead of continually stepping in which is very time consuming, could it just step out once a skip file is reached?

**Comment by weinand** [comment]
Accessing the node runtime via the (obsolete) v8 debugger protocol does not provide runtime support for 'just my code'. For this reason node-debug emulates the 'just my code' feature by automated stepping. And yes, this is slow.

Your suggestion to "step out once a skip file is reached" would make stepping faster but it has the potential to skip "too much" code, that is code indirectly called within the first skipped file.

I will close this item because we cannot do much here and we got `node2` which does not suffer from the problems. We will mention this in the release notes.
