### ISSUE TITLE
More specific more specific Configure Excludes message

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode#16853]
Testing #16534

Related to #16757

Few ideas:
* make it clearer what the specific action is the user should perform - (if it fits) consider referencing the property itself "use the'exclude' property to exclude... then restart the window"
* consider adding a link to documentation in the status bar 
* consider adding infobar that pops up after you click the "configure excludes" that gives you a link to reload the window
* Make it clear that this isn't just about better performance - we literally don't have any completions at this point, right? "JavaScript/TypeScript completions disabled... "
 
<hr>

- VSCode Version: Code - Insiders 1.8.0-insider (7499a9f3c565f4fbe5205e30c8664e5a5a11ae94, 2016-12-06T16:16:15.865Z)
- OS Version: Windows_NT ia32 10.0.14965

**Comment by mjbvz** [comment]
#16774 reworked the phrasing of message to address some of these concerns. The main challenge is that we only have a single line of text, so fully explaining things is difficult. Take a look at the new message and let me know if you have an suggestions

Adding a `More Info` button would be worth investigating, as would warning about reload after the user touches their `jsconfig.json` file, but let's target the next milestone on those instead of this release. As it is, with the changes the excldues that came in this month, hopefully users will be seeing this message less often than the were before (although, when they do see it, there really is a problem instead of likely a false positive).
