### ISSUE TITLE
customer javascript object.it's properties isn't in suggestions.

### ISSUE THREAD

**Issue by tonn2y** [Microsoft/vscode#1685]
![1](https://cloud.githubusercontent.com/assets/2756249/12031114/4a8e6476-ae43-11e5-8302-05d91f266815.jpg)

**Comment by bpasero** [comment]
Not sure if TS would support this.

**Comment by tonn2y** [comment]
I test the 'window', it doesn't work also.
![image](https://cloud.githubusercontent.com/assets/2756249/12032127/b692f162-ae4f-11e5-83bc-3aa1367d1b77.png)

**Comment by tonn2y** [comment]
but when I use 'window' keywords. It can work well.
![image](https://cloud.githubusercontent.com/assets/2756249/12032148/e51e7da8-ae4f-11e5-81e3-eaf89a48fc95.png)

**Comment by massimocode** [comment]
@tonn2y This is because you are using JavaScript not TypeScript. The type of the variable is determined at the point of declaration. i.e. for the parameter 'win' in your anonymous function, there is no way for the language service to know what type win will be. You could pass anything into it. Just because your own usage passes window into it, does not mean that it should definitely be of type window. However, perhaps that's an improvement that should be made? i.e. types being inferred from usages.

And in the case above where you do var todoList = this; the variable todoList is assigned the type of this. If no type can be detected, then it has no type (or type 'any'). You are then adding new properties dynamically which will not be 'added' to the variable's original type. Because of the nature of the TypeScript language service (which I believe powers the JS language service), you would only get suggestions based on the type detected at the point of declaring the variable.

However, in JavaScript it certainly would be nice if the language service could alter the type of the variable after it was declared, or detect its type based on usage (i.e. parameters), due to the lack of interfaces and type annotations, so that better code completion could be offered... Although I'm pretty sure this would not be desirable in TypeScript as you should be doing that using interfaces/type annotations.

**Comment by massimocode** [comment]
@tonn2y If you can use TypeScript in your project it's probably a good idea

**Comment by tonn2y** [comment]
you mean's it  doesn't support dynamic attribute definition?
![image](https://cloud.githubusercontent.com/assets/2756249/12059798/4445acfe-af9d-11e5-8809-3a9c82a33b07.png)
![image](https://cloud.githubusercontent.com/assets/2756249/12059808/68580132-af9d-11e5-91d2-07d85ee3bca3.png)

**Comment by massimocode** [comment]
@tonn2y Yes you're right. I've read that in the January release they might add Salsa support, which from what I gather will be a smarter language service for JavaScript editing. However I don't know if this will be supported with Salsa or if it will require separate work.

**Comment by tonn2y** [comment]
thinks.

**Comment by jrieken** [comment]
Closed with the adoption of Salsa (https://code.visualstudio.com/Updates#_languages-javascript).
