### ISSUE TITLE
Cannot run two different npm start scripts in monorepo

### ISSUE THREAD

**Issue by Igorgro** [microsoft/vscode#168562]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.74.0
- OS Version: Arch Linux

I have a monorepo with Node.js backend and frontend in it. When I'm trying to start both of them using `npm start` command from "npm scripst" menu, it doesn't work, instead it prints "Prevented duplicate task from running npm: start".

Steps to Reproduce:

1. Open a folder or a workspace
2. Create two subdirectories, for example backend and frontend, with package.json in each
3. Add a `start` task to both of them
4. Open "Npm scripts" panel and try to start both backend and frontend using "start" script
5. :bug: Only one task can be executed

**Comment by markw65** [comment]
I'll just note that this is not in fact a duplicate of https://github.com/microsoft/vscode/issues/168378, and the fix for that does not fix this one.

I've opened a [new issue](https://github.com/microsoft/vscode/issues/168741), and put up a [pull request](https://github.com/microsoft/vscode/pull/168742) that does address this issue.
