### ISSUE TITLE
[folding] Auto import or organize import unfolds imports

### ISSUE THREAD

**Issue by benasvip** [microsoft/vscode#168523]
Type: <b>Bug</b>

Even though I have `"editor.foldingImportsByDefault": true` in settings. Using auto import from suggest widget, quick fix import or organize imports action - **unfolds imports**. They should be folded and don't scroll the editor.

### Auto import from suggest widget (same with quick fix)
![auto-import](https://user-images.githubusercontent.com/10441177/206582903-802bef4b-bad4-48a5-b9d2-7ef4571a90a1.gif)

### Organize imports
![organize imports](https://user-images.githubusercontent.com/10441177/206582699-7c123a52-c13f-45a2-9797-93d2a2341e68.gif)

/cc @alexdima @mjbvz  - https://github.com/microsoft/vscode/issues/161396

VS Code version: Code 1.74.0 (5235c6bb189b60b01b1f49062f4ffa42384f8c91, 2022-12-05T16:37:54.581Z)
OS version: Darwin arm64 22.1.0

**Comment by svipas** [comment]
@aeschli If it adds new import in the middle same thing happens it unfolds

**Comment by benasvip** [comment]
@aeschli I saw you made a PR to fix issue with organize imports which now works in Insiders build, but if I add new import it expands folding. Are you planning to fix it as well? It would be awesome if it kept folded state after adding new import, because of `"editor.foldingImportsByDefault": true`

**Comment by aeschli** [comment]
Thanks @benasvip !

Fixed by https://github.com/microsoft/vscode/pull/226479

The PR fixes that adding imports via code completion or code action will not open the folded imports. The imports section only open if the selection/cursor is inside it.

Please try on todays insider build. If you see that the imports expand, please create a new issue with the code sample and detailed steps.
Thanks!
