### ISSUE TITLE
Moving cursor across folded code should not automatically unfold

### ISSUE THREAD

**Issue by michael-yx-wu** [Microsoft/vscode#16858]
- VSCode Version: 1.7.2
- OS Version: OS X 10.11.16

Folding code is often a strategy for hiding parts of files that aren't important or relevant to the current task and making it more manageable to scroll up / down. Given this context, I propose that when code is folded, it should perhaps remain folded until the user explicitly wants to unfold it. 

Steps to Reproduce:

1. Fold code
2. Attempt to move cursor over folded code

Example:

![dec-07-2016 15-51-21](https://cloud.githubusercontent.com/assets/3681045/20986072/10e8d29a-bc95-11e6-8686-4c5a30577d75.gif)

Desired Behavior:

1. Fold code
2. Be able to move cursor past line of folded code without auto-unfolding

**Comment by aeschli** [comment]
I can not reproduce that. When move the cursor over a folded section (cursor down, cursor down) or I place the cursor at the end of the line, this does not unfold the section.
What key sequence do you exactly press?

**Comment by michael-yx-wu** [comment]
This happens when I press `j`, `k`, `up`, `down` in either normal or insert mode. In gif, you can see that my cursor is also at the end of the line.

**Comment by aeschli** [comment]
@michael-yx-wu I guess you are using a VIM extension. Which one is it? You have to file this issue against that extension.

**Comment by michael-yx-wu** [comment]
Okay I'll refile against the vscode vim extension. I believe I'm using the one published by msft

**Comment by aeschli** [comment]
Thanks. Closing issue then

**Comment by emyller** [comment]
This happens to me even with all extensions disabled. I really wish to place the cursor after a folded code, hit `Enter` twice and be able to write new stuff after the folded code block. Here's what happens instead:

- Scenario 1: I focus/click the region after the folded code block. The block expands.
- Scenario 2: Even if I manually fold the expanded block, hitting `Enter` in there will add the new chars right after the folded block's first line instead of where I need (completely after it).

Sublime Text 3 delivers the expected behavior: https://streamable.com/5yct3
VSCode is weird about that: https://streamable.com/gjfcy
