### ISSUE TITLE
Snippet suggestions doesn't appear until suggestion window is reactivated with shortcut

### ISSUE THREAD

**Issue by westernwontons** [microsoft/vscode#168580]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
1.75.0-insider
b92894493e6f971a3c71912d823e699d3a05d643
arm64

- OS Version:
MacOS Ventura 13.0.1

Steps to Reproduce:

1. Have any kind of snippet that you trigger by a prefix.
2. See it appear in the suggestions window.
3. Fully type the prefix out.
4. It's no longer in the suggestions window.
5. Reactivate the suggestions window with a shortcut (mine is cmd+i)
6. The snippet now is visible in the suggestions window.

I have `"editor.snippetSuggestions": "inline"` set.

Here's a video:

https://user-images.githubusercontent.com/75550932/206693070-0e132c20-0cd1-4374-9414-6fc0f0129c5b.mp4

**Comment by jrieken** [comment]
What you `editor.quickSuggestions` configuration value? What the snippet (in source!), what's the code file (in source!)

**Comment by westernwontons** [comment]
<img width="296" alt="image" src="https://user-images.githubusercontent.com/75550932/206703628-8db08352-46f5-4c6c-ae5f-ec3f320f7aa4.png">

The snippet is the following:

<img width="282" alt="image" src="https://user-images.githubusercontent.com/75550932/206703714-ce4fe7e2-a8e2-4d1c-ade8-198cbf39be42.png">

Sorry, but I'm not sure what you mean by "what's the code file".

**Comment by westernwontons** [comment]
I've noticed that this only starts happening when any of the language servers kick in. If I manage to trigger the suggestions window before that or just type the prefix of the snippet, they appear.

**Comment by jrieken** [comment]
/
It looks like the issue is caused by one of your installed extensions. All extensions execute together on a single nodejs process, so in order to narrow down the possible problematic extension, please try the following:
* run `F1 > Help: Start Extension Bisect`
* (this will restart VS Code with half of your extensions disabled)
* try to do the steps which reproduce the problem
* if the problem reproduces, click "This is bad" (this narrows down the problematic extension to the half which was enabled)
* if the problem does not reproduce, click "Good now" (this narrows down the problematic extension to the half which was disabled)
* these steps will repeat until the problematic extension is found

| initial | step | final |
|---|---|---|
| ![image](https://user-images.githubusercontent.com/5047891/101918658-e9170f80-3bc9-11eb-9977-857baa291937.png) | ![image](https://user-images.githubusercontent.com/5047891/101918683-ef0cf080-3bc9-11eb-9f9e-98b0177991b2.png) | ![image](https://user-images.githubusercontent.com/5047891/101918706-f502d180-3bc9-11eb-8c86-e56355958bd4.png) |

**Comment by westernwontons** [comment]
Okay, I repeated the steps with a Rust project and it says rust-analyzer is at fault there. I'm not sure how to interpret this.

**Comment by westernwontons** [comment]
It seems like the bisect will hold the active extension accountable for the programming language used
