### ISSUE TITLE
Security enhancement: Suggestion of implementation of Scorecard Github Action

### ISSUE THREAD

**Issue by diogoteles08** [microsoft/vscode#168669]
Hello! I'm part of the Google Open Source Security Team ([GOSST](https://github.com/diogoteles08#about-gosst-ghost)), that joins effort with [OpenSSF](https://openssf.org/) to enhance Open Source Security. I'm here to suggest the adoption of [Scorecard](https://securityscorecards.dev/) Github Action on VSCode repo, and put myself available to raise a PR with the changes needed to use it =)

I'm reaching out to you because VSCode is a huge and influent project, so enhancing or certifying its security is important for the whole Open Source community, and I think Scorecard could help to achieve this goal. This tool works with a set of security [checks](https://github.com/ossf/scorecard#scorecard-checks) that would be automatically run over your repo and point, on your security tab, possible vulnerabilities or ways to enhance the security of your project.

If this specific tool does not make sense to your repo, I also make myself available to help with any other security concern that seems relevant to you. 

Thanks for the attention!

**Comment by TylerLeonhardt** [comment]
👋 @diogoteles08, really interesting tool. Thanks for sharing!

We have very rigorous security testing pipelines that are not only used on the VS Code team but across Microsoft so I don't think this tool makes sense for our repo at this time.

I will share it with the channels I have here at Microsoft so other folks are aware anyway since it does look like a really cool tool. Thanks again!
