### ISSUE TITLE
Improve exception experience

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#16860]
For details see https://github.com/OmniSharp/omnisharp-vscode/issues/1007

We could consider to revive the Peek UI.

**Comment by isidorn** [comment]
Not a fan of using peek UI since showing errors in the peek is the ugliest part of vscode that we have now imho. Another reason that peek UI is not the best for this is because peek has a lot of horizontal space and not a lot of vertical, which is not correct for exceptions which usually want to show a stack trace, e.g

```
Error
    at Object.<anonymous> (/Users/isidor/Development/w/standup/fib.js:20:8)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Timeout.Module.runMain [as _onTimeout] (module.js:590:10)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)"
```

As for the motivation of this I only see the request from the C# exception. Do all the other languages also expect an experience which is similar to Visual Studio?
Yes I see that the exception is not that discoverable when it is not in the users face but it is a tradeoff in the end.

In any case I do not see a rush for doing this in January -> I propose we push it to February and then design this nicely if we decide we want to change something here.

**Comment by weinand** [comment]
Showing the stacktrace in the peek UI is not necessary because we already have the CALLSTACK view). 
What we should show more prominently:
- the Exception type,
- if this is an unhandled exception, 
- and the exception message.

Currently:
- the exception message can only be found by finding $exception in the locals window, which can be confusing to find if one is in a big function
- the exception type and unhandled/handled status can be found by hovering over the 'PAUSED ON EXCEPTION' text, which is nice, but not all that discoverable.

We'll defer the implementation to February.

**Comment by weinand** [comment]
VS for Mac:

![2017-02-02_17-48-49](https://cloud.githubusercontent.com/assets/1898161/22558996/fa819fca-e96f-11e6-9c76-0f570188b7bf.png)

**Comment by weinand** [comment]
see https://github.com/Microsoft/vscode-debugadapter-node/issues/97 for the corresponding protocol change

**Comment by isidorn** [comment]
ping @michelkaporin

**Comment by isidorn** [comment]
Closing this since we have an initial exception widget (still needs a bit of ux polish) thanks to @michelkaporin https://github.com/Microsoft/vscode/pull/20807
I suggest to create a new item for March where we can capture on how to make the widget more feature rich.

**Comment by weinand** [comment]
@isidorn @michelkaporin make sure that the hover information available on the CALL STACK view is shown in the peek UI. I'm referring to the bullet item 
> The exception type and unhandled/handled status can be found by hovering over the 'PAUSED ON EXCEPTION' text, which is nice, but not all that discoverable

from OmniSharp/omnisharp-vscode#1007
