### ISSUE TITLE
high contrast mode - inconsistency between viewlet icons and sidebar icons

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode#16870]
Testing #15811

Not sure if this is acceptable, but the icons in the sidebar get brighter in high contrast mode, whereas the icons in the viewlets (e.g. the settings icon in the debug viewlet) do not. 
![image](https://cloud.githubusercontent.com/assets/762848/20992243/9fa7c89a-bc97-11e6-9e5d-c6faa11a97b5.png)

<hr>

- VSCode Version: Code - Insiders 1.8.0-insider (7499a9f3c565f4fbe5205e30c8664e5a5a11ae94, 2016-12-06T16:16:15.865Z)
- OS Version: Windows_NT ia32 10.0.14965

**Comment by bgashler1** [comment]
This has been this way for a while (longer than I've been here) and is not a regression.  Also, while these icons don't match, they do exceed AAA accessibility requirements (> 7:1 contrast).

A cool solution to fix this would be to inline all our SVG in the DOM so we can apply styles to them for themes (it would allow us also to cut the number of icons we have in half, since we have the same icons tuned for light and dark theme).  Otherwise, we need to add hundreds of more icons that are high-contrast-tuned.
