### ISSUE TITLE
vscode can not get  uri._rootUri. Path any more

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode#168758]
Does this issue occur when all extensions are disabled?: Yes

版本: 1.74.0 (system setup)
提交: 5235c6bb189b60b01b1f49062f4ffa42384f8c91
日期: 2022-12-05T16:38:16.075Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.25262
沙盒化: No

Steps to Reproduce:
click the button from git-repo extension's icon
we can not get uri._rootUri but `uri.Y`?
![image](https://user-images.githubusercontent.com/1876302/206884418-bb190a00-86dc-4c5c-9a4b-6699b08957c5.png)

**Comment by heartacker** [comment]
https://github.com/heartacker/vscode-gerrit-helper/issues/1

**Comment by gjsjohnmurray** [comment]
Maybe a consequence of microsoft/vscode-discussions#257?

**Comment by heartacker** [comment]
I am a newbie， and Can any body help me to fix this issue

thanks verymuch

**Comment by lszomoru** [comment]
That is correct. Starting with the latest Stable release protected and private fields are being mangled as described [here](https://github.com/microsoft/vscode-discussions/discussions/257). As a quick/tactical workaround you could change your code yo use `uri._rootUri.y` but I would also immediately start exploring a long-time fix as relying on private/protected fields is not recommended. Is there any reason why you are using a private/protected field? Is there API missing?

**Comment by yi-Xu-0100** [comment]
@lszomoru I found that I also encountered this problem. In [vscode-conventional-commits#issue289](vscode-conventional-commits#289), if there is no such `uri._rootUri`, we need to choose which repository to submit to each time.

I tried to find a long-time fix, but found that the order of `WorkspaceFolders` does not change when I select different icons in "Source Control" panel.

I tested the previous version (1.73.1), the `uri._rootUri` worked fine, and actually returned the path corresponding to the icon I selected.

Can you help me find out what public api can solve this issue?

**Comment by lszomoru** [comment]
@yi-Xu-0100, I am happy to help but I would like to ask you do describe the exact scenario for which you relied on the private/protected property. Thanks!

**Comment by yi-Xu-0100** [comment]
@lszomoru Thank you for your kindness. After a temporary solution, I try to search for a long-term solution. Finally, after referring to a similar type of VS Code extension, I have fixed the issue that I meet ([PR#292](https://github.com/vivaxy/vscode-conventional-commits/pull/292)). Thank you very much! I don't have this issue for now.

**Comment by MichaelCurrin** [comment]
Hi @yi-Xu-0100 

Thanks for the info. I have tried using `rootUri` replacement but it is not compatible on Windows. So perhaps so you can use my error to help you improve the way that value is set? 

More details below

---

I had the issue in my VS Code extension recently where `Repository._rootUri` was not working in certain cases (multiple repos open at once). So I switched to the public field `Repository.rootUri` and this fixed it.

However, Windows users of my extension reported a bug in my extension.

It turns out when I print the `Repository.rootUri` value in a pop-up that on Windows it is still formatted as a Linux path. 

![image](https://user-images.githubusercontent.com/18750745/212175490-413f3466-d08d-44e8-b12d-504cac35d462.png)

The forwardslash is not an issue so much. But the leading forwardslash was **not** valid for a path on Windows. e.g. `ls c:/Users/` is fine but `ls /c:/Users/` causes a shell spawn error in my extension.

**Comment by yi-Xu-0100** [comment]
👋 @MichaelCurrin, I checked your code and found that it's not `rootUri`'s problem, but you use `rootUri.path` to handle disk operations, and I use `rootUri.fspath`. You can find the corresponding difference, I think the latter can handle the problem correctly with the different platform path. 👀

**Comment by MichaelCurrin** [comment]
@yi-Xu-0100 Aha I understand now, appreciate your input.
