### ISSUE TITLE
Diagnostic Hover improvements request

### ISSUE THREAD

**Issue by joshbw** [microsoft/vscode#16884]
I'm working on an extension that tries to put rich security guidance in front of developers as they introduce potential vulnerabilities, and there are a couple of improvements to the hover functionality of a diagnostic that would allow me to improve the overall experience with my extension

1) It would be great to be able to make URLs in the hover into working links, instead of requiring someone to copy the text and paste it in the browser.  I'm reasonably constrained in the length of guidance I can put in a diagnostic, since the hover popup has a max width and height, so I include a URL off to more info on the problem being flagged.  However it would be a lot more usable if the user could just click on this URL and be off to the guidance

2) I would really love to provide different text into the output window versus what I put in the hover window.  Currently, since the diagnostic source and message are echoed to both the output window and hover, but displayed very differently (single line in output vs. a decent sized area in the hover window) I'm in the position of offering a sub optimal experience in one area or the other  (for example, I abbreviate the severity of the security finding to Crit, Imp, Mod, etc. so that it fits well in the output window, but that terseness isn't necessary in the hover window)

I know there is a desire to keep diagnostics lightweight, and I certainly agree with decisions to keep CSS styling out of the mix, but the two requests above would let me deliver a fair bit better user experience to users of my extension.

**Comment by joaomoreno** [comment]
Not saying that you should, but have you tried using the [`hoverMessage` in a decoration](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L895) instead of relying in Diagnostics? Does that [formatting flexibility](https://github.com/Microsoft/vscode/issues/2330#issuecomment-245214728) allow you to render what you want to render?

It's been my will to have the same formatting power in diagnostics as we have in decorations. There's more information about the power of decorations vs the lack of it in diagnostics in #2330 cc @jrieken

**Comment by nrc** [comment]
> I would really love to provide different text into the output window versus what I put in the hover window.

We would also love to have a facility like this (for the Rust extension). We also have pretty large error messages and it would be great to be able to put a short version in the output panel (even better if there were an expand button to show a long version) and a long version on hover.

We would also like to be able to have links in the diagnostic, but to jump to locations in the project, rather than to a URL. I appreciate this would need a fair bit more work than a long message though.

**Comment by sandy081** [comment]
Wow.. this is a very old request. There were some improvements done to the hover so please revalidate this request again. Re links, we already have a feature request to support it.

So closing this.
