### ISSUE TITLE
Support for toggling case of selection along the lines of IntelliJ

### ISSUE THREAD

**Issue by thekalinga** [Microsoft/vscode#16895]
IntelliJ allows the user to toggle the case of text selection to upper/lowercase with a single action called `Toggle Case`.

Once you select text & apply this action via shortcut, it converts the selection to uppercase by default, if you press the shortcut it again, the selected text would be converted to lowercase.

Currently uppercase & lowercase are implemented as separate actions.

It would be good to have a `Toggle case` action so that user need to remember just one shortcut instead of two different shortcuts to toggle case

Reference:
https://github.com/Microsoft/vscode/issues/3776

**Comment by kumarharsh** [comment]
There is an awesome extension for that already: https://marketplace.visualstudio.com/items?itemName=wmaurer.change-case

**Comment by thekalinga** [comment]
Agreed, but what they are adding now is most basic & most commonly used.

Not sure how many times I would utilise a fraction of options that the extension provides other than the upper & lower case.

Thanks for pointing it out.

**Comment by alexandrudima** [comment]
To keep the number of issues in our inbox at a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: we look at the number of votes the issue has received and the number of duplicate issues filed. Thank you for your time and understanding.

If you disagree and feel that this issue is crucial: we're happy to listen and to reconsider.
