### ISSUE TITLE
[regression] TypeScript word highlighter (provideDocumentHighlights) now highlights entire strings

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#16909]
* open vscode repo on `cursor.test.ts`
* click inside a test name

### Stable behaviour (expected): No highlights for strings
![image](https://cloud.githubusercontent.com/assets/5047891/21005295/88182808-bd34-11e6-97bb-8bab2b121fa2.png)

### Insiders behaviour (unexpected): Highlights entire string
![image](https://cloud.githubusercontent.com/assets/5047891/21005329/aac6fffa-bd34-11e6-9e6f-1fe02d2aee3f.png)

**Comment by mjbvz** [comment]
Closing as upstream TypeScript issue: https://github.com/Microsoft/TypeScript/issues/12780

**Comment by dbaeumer** [comment]
@mjbvz since this is quite disturbing I would suggest to add the following workaround on our end:

If the highlight is for the current document we look at the source and filter the match if enclosed in " or '.  I know hacky :-). And we pressure for a better fix in the tsserver for the next update. I proposed that they give us a 'type' information for the document highlight request telling us to which SymbolKind the symbol under the cursor resolved.

**Comment by dbaeumer** [comment]
Another idea to solve this would be as follows: we don't highlight anything if the result only contains one match and contains the current cursor position. This would then convey  the  information that there aren't any references in the document for that symbol. This might work for most of the strings.

**Comment by mjbvz** [comment]
@dbaeumer I'm testing the first workaround now, since it seems like the more scoped fix. I agree that we need some additional information back from TypeScript to handle this properly. Highlighting literal string types for example probably makes sense, but not highlighting content strings.

**Comment by alexandrudima** [comment]
@mjbvz Thank you!
