### ISSUE TITLE
Configuration service does not emit event on deletion of .vscode folder

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#16902]
I just deleted the .vscode folder and the debug viewlet still looks configured:

![image](https://cloud.githubusercontent.com/assets/22350/21004335/0bb2bdfe-bd30-11e6-8d17-a4820849a5b2.png)

**Comment by isidorn** [comment]
Ok I can only repro this if I delete the whole .vscode folder - not if I delete just the launch.json
The root of the problem is that configurations service does not emit a change event when the .vscode folder gets deleted. Even though it emits once launch.json gets deleted. Thus forwarding to @bpasero as I would expect a change event also if the whole folder gets deleted

**Comment by bpasero** [comment]
A very bad regression from https://github.com/Microsoft/vscode/commit/a744e4e1bda12e3860bf36e9f70f2d8c80648b8b
