### ISSUE TITLE
Seperate File Uploading in Marketplace for insiders

### ISSUE THREAD

**Issue by shanalikhan** [Microsoft/vscode#16910]
Hi,

There should be another tab in the upload new items when publishers does upload their extension. 
Which should be available only to insiders, so extension writers dont have to upload the package.json file again and again in order to publish for insiders separately. 

![capture](https://cloud.githubusercontent.com/assets/8774556/21073021/4c8ae0c8-bef6-11e6-8cd6-14fc5005951d.PNG)

To interact with insiders separately the following things can be done.
1. Extension writers should always upload the newer version for insiders compared to normal build release in that tab.
2. Extension page should show the extension version for insiders in the left side below to owner information.
3. Extension writers will have an option to release that insiders build to normal build in just one click as insiders build will always be newer than normal so writes than use that method to update.
4. When the normal build version matches either by publishing new build or transfer from insiders build like in step 3, if its version is equal to insiders build verison or newer than insiders build- this extension insiders build should be removed.

**Aim**
Extension writers can upload two version at once, one for insider and one for normal and transfer the insider build version to normal version in one click.

_Its just an idea can be further extend or improved._

Thanks

**Comment by joaomoreno** [comment]
What do you mean by _ when publishers does upload their file_? Can you share a screenshot of the UI you are referring to?

**Comment by shanalikhan** [comment]
i have updated the comment, there should be another tab to insert extension for insiders in that dialog box for that purpose.
Other enhancements in that post.

**Comment by joaomoreno** [comment]
We recommend you to use [`vsce`](http://code.visualstudio.com/docs/tools/vscecli) to publish your extensions.

We don't currently support separate publish actions for Insiders vs Stable. But there is a mechanism that should accomodate your needs:

The reason for you to want to distinguish between insiders and stable is mainly due to the fact that your extension already benefits from API available only in the insiders release. Now, on any given point in time, stable is on version N, while insiders is on N+1. For instance, right now, the latest stable release is `1.7.2`, while the latest insider release is `1.8.0`.

When you author an extension, you need to indicate your **version compatibility** to Code itself via the `engines.vscode` field in `package.json`. If you put in `^1.8.0`, for example, you tell us that your extension _can only run on Code >= 1.8.0_. If you publish your extension this way, users in stable 1.7.x won't ever see that version. Users on insiders will get the update. And as soon as Code stable updates itself to 1.8.x, those users will get the extension update.
