### ISSUE TITLE
TS/JS missing import messing up

### ISSUE THREAD

**Issue by enguerranws** [microsoft/vscode#169141]
- VS Code Version: 1.74.0, reinstalled, no plugins, settings.json is empty
- OS Version: macOs 13.0.1

Steps to Reproduce:

1. Create an exported TS module
2. import it in another TS file where you can resolve the module you created in 1
3. remove the import instruction
4. try to resolve the missing import

![ezgif-1-d94f09cb52](https://user-images.githubusercontent.com/2190121/207641649-37596d93-43be-4be7-a293-f3c2e235d166.gif)

**Comment by mjbvz** [comment]
This isn't related to auto imports, that's just how the normal insert behavior of suggestions works. You will see the same when completing a local variable with the cursor in the middle of an existing word

To change this, you can set: `"editor.suggest.insertMode": "replace"`. This will replace the current word instead of inserting into it

**Comment by enguerranws** [comment]
Well, I didn't find that setting. That's really good to know. However, I can't keep wondering why `replace` is not the default behavior.
