### ISSUE TITLE
Escape characters visible in Hover

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#16936]
Version 1.8.0-insider
Commit e0871329738682651367be4e8a618912ad693e03
Date 2016-12-08T07:04:29.620Z

- in the settings add `"html.format.unformatted": "a" ` and hover on it

![image](https://cloud.githubusercontent.com/assets/6461412/21016887/a4914d2e-bd67-11e6-929a-1fc16e6e4364.png)

Content generated by the JSON server is:
`List of tags, comma separated, that shouldn't be reformatted\. 'null' defaults to all tags listed at https://www\.w3\.org/TR/html5/dom\.html\#phrasing\-content\.`

**Comment by mjbvz** [comment]
Related to #14968, but not exactly the same. This one is more about when we escape input strings.

Here's the input string:

```
List of tags, comma separated, that shouldn't be reformatted. 'null' defaults to all tags listed at https://www.w3.org/TR/html5/dom.html#phrasing-content.
```

Because this is treated a raw input string in the hover (and not as markdown content) we end up escaping all special characters, producing the following markdown:


```
List of tags, comma separated, that shouldn't be reformatted\. 'null' defaults to all tags listed at https://www\.w3\.org/TR/html5/dom\.html#phrasing-content\.
```

This markdown parser then identifies `https://www\.w3\.org/TR/html5/dom\.html#phrasing-content\` as the link (github has the same behavior).

Two potential fixes:

* Really treat the hover input as a marked string (may cause regressions for text that was not expecting to be treated as markdown).
* Add a special case to handle links (possibly by identifying links before we do the markdown escaping in the first step)

**Comment by aeschli** [comment]
Give that markdown has special link syntax [..](...) and <...> it seems to me that the link detection by pattern should be done after converting the text input to markdown.
If it were the other way around, why would the escaping inside the link even be necessary?

**Comment by mjbvz** [comment]
@aeschli The problem is that we don't treat hover content as markdown, we treat it as plain text and escape all special markdown symbols to ensure it renders as plain text. This escaping pass is what ends up generating : `https://www\.w3\.org/TR/html5/dom\.html#phrasing-content\.` from which the markdown parser identifies the link: `https://www\.w3\.org/TR/html5/dom\.html#phrasing-content`

**Comment by jrieken** [comment]
We should maybe use the same markdown library we use for the md-extension
