### ISSUE TITLE
Quick pick needs bottom padding

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#169405]
![image](https://user-images.githubusercontent.com/22350/208130187-fae2e653-40f8-4ab5-ae98-4ef028c42420.png)

![image](https://user-images.githubusercontent.com/22350/208130243-c942c132-fd25-4b1b-ac5f-24017ff38f90.png)

**Comment by TylerLeonhardt** [comment]
I think this was the result of moving the progress bar below the input. Since the progress bar use to provide the padding.

**Comment by TylerLeonhardt** [comment]
let's just call it an exploration of compact mode :) /s

**Comment by daviddossett** [comment]
This is partially as designed, but it still needs improvement. The latest changes make it so we have a nice cutoff when the quick pick list is scrolling:

<img width="653" alt="CleanShot 2022-12-16 at 09 23 10@2x" src="https://user-images.githubusercontent.com/25163139/208154028-fd4cc234-dcba-40a8-a707-906669685aa2.png">

However it should probably still use padding at the bottom of the list, rather than the container, to ensure this doesn't happen when the entire list is visible/not scrollable.

**Comment by bpasero** [comment]
I dont want to be the annoying guy at the party here, but an empty quick pick now looks like this:

<img width="647" alt="image" src="https://user-images.githubusercontent.com/900690/208170490-d8171db8-4462-45bf-87e0-748d8a3d2981.png">

🙈

**Comment by daviddossett** [comment]
Haha, whoops. I'll have another go at this then.

**Comment by TylerLeonhardt** [comment]
Continuing this in https://github.com/microsoft/vscode/issues/208227
