### ISSUE TITLE
Save all will perform paste operation

### ISSUE THREAD

**Issue by AndrewLang** [Microsoft/vscode#16952]
- VSCode Version:1.7.2
- OS Version:Windows 10

Steps to Reproduce:

1. Open two files in VS code, I get this issue with html, css, js and ts files.
2. Edit file 1, make it dirty but do not save
3. Switch to the other file then click "Save All" from main menu or from the side bar
4. The dirty file was saved, but the content of the dirty file will paste to current file editor. 

Actually this is not a new issue, I found it in early version as well.

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by AndrewLang** [comment]
@bpasero You are right, thanks. 

This issue is caused by an extension "js-beautify for VS Code" , after disable it, the issue get solved.
