### ISSUE TITLE
Breakpoint line numbers have bad contrast on new dark theme

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#169673]
<img width="468" alt="image" src="https://user-images.githubusercontent.com/4544166/208750572-ecf2826c-f4de-4696-9c41-5e013cbfbd81.png">

Looks the same as a disabled button for example

**Comment by daviddossett** [comment]
These are styled as disabled unless selected so I think this is at least somewhat intentional. However given the recent theme updates I think the new dark theme fairs slightly better now:

<img width="327" alt="CleanShot 2023-01-12 at 12 46 42@2x" src="https://user-images.githubusercontent.com/25163139/212177902-aaf3574e-48c1-4b6b-8e19-02fed7f1d86e.png">

https://github.com/microsoft/vscode/blob/246f6f4e470865881c67154b22adfba393dfe4f1/src/vs/workbench/contrib/debug/browser/debugColors.ts#L142-L146

cc @roblourens

**Comment by roblourens** [comment]
I think it should definitely be easy readable when unselected, and just a little brighter when selected. I think it looks ok in your screenshot
