### ISSUE TITLE
Unpretty language name

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#16976]
* Open a `.log` file in the editor
* 🐛 the language status read "vscode-output-colorizer"

![screen shot 2016-12-09 at 13 01 21](https://cloud.githubusercontent.com/assets/1794099/21048452/b9f5c23c-be0f-11e6-9218-b50a693437aa.png)

**Comment by bpasero** [comment]
@jrieken this is an extension, so please report it there (https://github.com/IBM-Bluemix/vscode-log-output-colorizer/blob/master/package.json#L32)

**Comment by jrieken** [comment]
I don't have that extension installed

**Comment by sharwell** [comment]
@jrieken I can't reproduce this locally. For me, the language appears as "Plain Text".

**Comment by bpasero** [comment]
@jrieken how can this not be caused by an extension if our repository does not contain any such string as vscode-output-colorizer

![image](https://cloud.githubusercontent.com/assets/900690/21052327/b7dda8d8-be24-11e6-8d38-1e9424877c43.png)

**Comment by sharwell** [comment]
@bpasero Could it be caused by a settings file? I.e. can you assign a language name to a file extension without actually having an extension for that language installed?

Also possible is that another extension embedded the output colorizer extension for one reason or another, and now the functionality exists in the installation even though the extension does not.

**Comment by bpasero** [comment]
@jrieken do you have file.associations? does it repro when running with disabled extensions?
