### ISSUE TITLE
Linux: Flickering when starting to drag editor tab

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#16992]
- VSCode Version: Code - Insiders 1.8.0-insider (40243d1e01f426f54670f3dbaa6b77d18469310d, 2016-12-09T12:05:39.439Z)
- OS Version: Linux x64 3.13.0-91-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|
|regex|chrmarti|0.0.4|
|python|donjayamanne|0.3.21|
|cpptools|ms-vscode|0.9.2|

Verifying #14470. There is still some flickering at the start of the drag:
![linux-tab-flicker](https://cloud.githubusercontent.com/assets/9205389/21057898/5475d150-bdf0-11e6-9eb3-b37fbd3fcce0.gif)

**Comment by bpasero** [comment]
@chrmarti please check if this reproduces on a real Linux box, I do not trust whatever Parallels does.

**Comment by Tyriar** [comment]
Yes this repros for me on a real Ubuntu install.

**Comment by bpasero** [comment]
This is because there is a `DRAG_LEAVE` event being fired right on start on the label inside the tab container because the DND handling is registered on the tab container and not its children. I believe the only way to solve this is to actually put an overlay over the children in the tab and thereby prevent any DND events from targeting the children. I also played around with `pointer-events: none` but without success. Willing to accept a PR on this one if anyone has a better idea.

**Comment by bpasero** [comment]
@chrmarti do you still see this? I am not seeing this anymore on Ubuntu 17.10.

**Comment by chrmarti** [comment]
@bpasero There seems to be a flash now:
![ubuntu-dnd-tab-flash](https://user-images.githubusercontent.com/9205389/33031953-97ccdbd4-cdd4-11e7-9c6b-bced01d26a5a.gif)
