### ISSUE TITLE
BUG: Improper tag insertion possible

### ISSUE THREAD

**Issue by goseungduk** [microsoft/vscode#170428]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

# Summary

You can trigge XSS on Visual Studio Code with vscode-jupyter.

# Description

Jupyter on Visual Studio Code has the markdown rendering function.

It can also render some HTML tags which is allowed by Visual Studio Code. For Example, `<script>` and `alert` function can’t be used on vscode-jupyter markdown editor.

In some HTML tags, I found which can be used on vscode-jupyter. That is, `<video>` tag. And then, I added a usable event handler on `<video>` tag like `onmouseover`. 

With this, you can write on vscode-jupyter's markdown editor XSS payload.
```
<video onmouseover="console.log('XSS')"></video>
```

![](https://i.imgur.com/xsL7qS2.png)

Let me give you an example of the damage this can cause like DoS.

This is a payload which I made for Denial of Service.

```
<video onmouseover="while(1){ console.log(1) }"></video>
```

If write this on jupyter notebook file and open that, the XSS payload can causes user's memory exhaustion and vscode process will be killed until the file is closed.

more PoC video and information are in my report. 

Please check this:
[Report](https://western-donut-113.notion.site/Denial-of-Service-on-VSCODE-with-XSS-on-VSCODE-Jupyter-20608caa04424a3ba5f351d5ad3d7c3d)

---

# Contact

If you have any problems, contact me via a42873410@gmail.com or bob11.devranger@gmail.com. Thank you :)

### VS Code Version

1.74.0

### Jupyter Extension Version

2022.10.110

### Coding Language and Runtime Version

Python v3.9.6

### Running Jupyter locally or remotely?

Local

**Comment by mjbvz** [comment]
This only happens in trusted workspaces. In untrusted workspaces, we strip all unsafe tags and attributes. This is also how we handle notebook output

For trusted workspaces, we don't sanitize the rendered markdown because some notebooks rely on scripts and styles and other potential unsafe content 

PS: In the future, please make sure to go through the security reporting process for any security related concerns: https://github.com/microsoft/vscode/security/policy
