### ISSUE TITLE
`Format on Save` setting enabled with`modifications` is formatting the whole file

### ISSUE THREAD

**Issue by fergald** [microsoft/vscode#170936]
I'm running into this while working on chromium. Repro steps below are for a chromium checkout ([multiple chrome devs are seeing this](https://crbug.com/1402278)). I tried to repro in a simple clean repository but couldn't repro steps are (from a checkout of chrome).

1. run the following
  ```
  SHA=[1ed2224941c2f33a34c906561963495e796a7cd0](https://crrev.com/1ed2224941c2f33a34c906561963495e796a7cd0)
  git checkout -b rebase-format-repro ${SHA}^
  patch -p1 << EOM
  --- a/content/browser/renderer_host/render_frame_host_impl.cc
  +++ b/content/browser/renderer_host/render_frame_host_impl.cc
  @@ -9573,6 +9573,7 @@ void RenderFrameHostImpl::RequestAXTreeSnapshot(
   
   void RenderFrameHostImpl::RequestDistilledAXTree(
       AXTreeDistillerCallback callback) {
  +  // this will conflict.
     // TODO([https://crbug.com/859110](https://bugs.chromium.org/p/chromium/issues/detail?id=859110)): Remove once frame_ can no longer be null.
     if (!IsRenderFrameLive())
       return;
  EOM
  git commit -a -m'conflict'
  git rebase $SHA
  ```
2. Note that line 9565 is
  ```
    if (!IsRenderFrameLive())
      return;
  ```
3. Resolve the conflict in vscode (just delete it all)
4. Save

You'll see that 9565 is now
```
  if (!IsRenderFrameLive()) {
    return;
}
```

and a bunch of other places have been reformatted throughout the file.

This might not be a recent problem, however chrome recently changed it's clang-format to add braces to all `if`s so it is now very noticeable, as every file has `if`s that get reformatted.

**Comment by jrieken** [comment]
There is two parts involved here. For once the SCM (git) that tells us the modification ranges and second an extension that does the actual formatting work. We invoke it with said ranges and apply its edits. We don't limit the edits to the requested-ranges and it might be that the formatter in your case in a bit excessive with that. What formatter extension are you using?

**Comment by fergald** [comment]
Thanks, that makes sense.

> What formatter extension are you using?

I don't know the correct answer to that. I don't see anything in active extensions specifically about formatting. I have C/C++ Intellisense, clangd, C/C++ extension pack and some others. I remember I used to use something from grunt-fuggly to format only diffs but then that wasn't needed anymore.

Is there a config file or something I can attach that would let you answer the question?

Is there a way to enable debugging so that I can see the interaction between vscode and clang-format. If this is actually clang-format being over-formatty, that will be helpful for filing a bug there.

**Comment by jrieken** [comment]
Yeah, trace logging should help here

* F1 > Set Log Level > Trace
* F1 > Show Logs > Extension Host
* then do a save with modifications and search for the last occurrence of `provideDocumentRangeFormattingEdits`

A typical message looks like this `2023-01-10 09:55:50.733 [trace] [vscode.typescript-language-features] INVOKE provider 'we=>we.provideDocumentRangeFormattingEdits(a.URI.revive(H),Q,J,he)'` which includes the extension id.

**Comment by fergald** [comment]
Thanks that didn't produce anything useful, perhaps because I'm working over ssh. Is there a way to get trace logs from the remote side?

I also tried working directly on the host where this occurs. I've actually never done that before, so I turned on settings-sync but format-on-save is not working at all (despite the settings being set for it and clang-format is installed). If possible let's not debug this and just stick with the remote case if we can.

**Comment by fergald** [comment]
OK, I got format on save working in the local vscode too and it repros and this is what I see in the logs

```
2023-01-10 10:21:58.138 [trace] [ms-vscode.cpptools] INVOKE provider 'be=>be.provideDocumentRangeFormattingEdits(a.URI.revive($),X,_,le)'
2023-01-10 10:21:58.422 [trace] [ms-vscode.cpptools] provider DONE after 283ms
2023-01-10 10:21:58.624 [debug] onWillSaveTextDocument-listener from extension 'ms-vscode.cpptools' finished after 15ms
2023-01-10 10:21:58.686 [trace] ExtHostSCM#$provideOriginalResource 0 file:///usr/local/google/home/fergal/chromium/src/content/browser/renderer_host/render_frame_host_impl.cc
2023-01-10 10:21:58.686 [trace] [ms-vscode.cpptools] INVOKE provider 'le=>le.provideInlayHints(a.URI.revive($),X,_)'
2023-01-10 10:21:58.688 [trace] [InlayHints] NO inlay hints from 'ms-vscode.cpptools' for [object Object]
2023-01-10 10:21:58.688 [trace] [ms-vscode.cpptools] provider DONE after 8730ms
2023-01-10 10:21:58.698 [trace] ExtHostSCM#$provideOriginalResource 1 file:///usr/local/google/home/fergal/chromium/src/content/browser/renderer_host/render_frame_host_impl.cc
2023-01-10 10:21:58.698 [trace] [ms-vscode.cpptools] INVOKE provider 'le=>le.provideFoldingRanges(a.URI.revive($),X,_)'
2023-01-10 10:21:58.750 [trace] [vscode.merge-conflict] INVOKE provider '_=>_.provideCodeLenses(a.URI.revive($),X)'
2023-01-10 10:21:58.751 [trace] ExtHostCommands#executeCommand setContext
2023-01-10 10:21:58.751 [trace] [vscode.merge-conflict] provider DONE after 1ms
2023-01-10 10:21:58.798 [trace] [ms-vscode.cpptools] provider DONE after 100ms
2023-01-10 10:21:59.496 [trace] [vscode.git] INVOKE provider '_=>_.provideLinks(a.URI.revive($),X)'
2023-01-10 10:21:59.505 [trace] [vscode.git] provider DONE after 9ms
```


BTW to get format on save to work, I ended up selecting some text, the ctrl-shift-p "Format Modified Lines" at which point a prompt popped up asking me to configure the default formatter. After that, formatting started working.

**Comment by fergald** [comment]
Ping @jrieken . Can you see something useful in that trace?

**Comment by jrieken** [comment]
>  I ended up selecting some text, the ctrl-shift-p "Format Modified Lines" at which point a prompt popped up asking me to configure the default formatter. After that, formatting started working.

This happens when there are multiple formatter (extensions) installed but non has been picked yet. The modal picker prompt that you have seen only shows after an explicit user-gesture (to format), for non-explicit formatting requests as with saving we show a status bar message (in addition to the permanent language status, see image below). We do that because saving can "just happen", e.g triggered by extensions, automatically after delay or on focus-out, etc. In those cases we don't want to show a modal dialog that forces you to make a permanent decision. 

<img width="1113" alt="Screenshot 2023-01-16 at 16 54 37" src="https://user-images.githubusercontent.com/1794099/212719856-ba470331-3676-42af-ad32-ebc109435335.png">

**Comment by fergald** [comment]
@jrieken The formatter choice thing is a side-issue.

The original issue here is that the whole file is being reformatted. You asked me to turn on tracing. How can we debug the formatting issue?

**Comment by jrieken** [comment]
> The original issue here is that the whole file is being reformatted.

That's always an issue of the underlying extension doing the actual formatting edits

**Comment by fergald** [comment]
Right and the purpose of adding tracing was to identify which extension it was and allow debugging it. Can you see which it is from the tracing?

**Comment by jahuarcristian** [comment]
Ok

**Comment by jrieken** [comment]
`[ms-vscode.cpptools] INVOKE provider 'be=>be.provideDocumentRangeFormattingEdits`

**Comment by fergald** [comment]
Thanks. I've filed that over in https://github.com/microsoft/vscode-cpptools/issues/10391

**Comment by Colengms** [comment]
@jrieken .  Since VS Code decides what ranges should be formatted, how would incorrect ranges be an extension issue?

Since the only changes the user made were to remove code, wouldn't that result is NO ranges to format, making it unnecessary to invoke the formatting provider at all?

Also `provideDocumentRangeFormattingEdits` accepts only a single range.  Does VS Code invoke it several times, to format each modification?  Or, is VS Code coalescing those into a single range?  That could explain what the user is seeing, as it would impact all of the code between their edits.

**Comment by fergald** [comment]
@Colengms 
> Since the only changes the user made were to remove code, wouldn't that result is NO ranges to format, making it unnecessary to invoke the formatting provider at all?

If I delete a line that only contains `}` then the formatter definitely needs to be invoked and the formatter should reformat far outside of whatever 1-2 line range vscode provided to it, so I think it's definitely possible for the formatter to format more than it was asked to.

**Comment by fergald** [comment]
One more point to note. If I trigger the conflict and resolve it cleanly, `git diff` outputs nothing. Could this be the problem? That could explain why it only seems to happen with merge conflicts.

**Comment by jrieken** [comment]
> Since VS Code decides what ranges should be formatted, how would incorrect ranges be an extension issue?

@Colengms We make a request with changed ranges (the logic is the same that drives the `scm.diffDecorations` setting/feature, e.g it's our diff implementation) and expect extensions to return reasonable text edits. We don't enforce that computed edits are contained within or overlapping with the request range because we want to allow for some "wiggle room"

> Also provideDocumentRangeFormattingEdits accepts only a single range. Does VS Code invoke it several times, to format each modification?

Yes, we don't yet support multi-range formatting requests so we sequentially ask for formatting edits for [each range](https://github.com/microsoft/vscode/blob/ab1a31add4608f484d555e3c791f03321a4dda5f/src/vs/editor/contrib/format/browser/format.ts#L216). We will coalesce two ranges if their respective results have computed overlapping edits (we perform all edits at once and they cannot overlap) 

I have pushed a change that will add logging. Once that's out do "F1 > Set Log Level > Trace" and check the window log ("F1 > Show Logs > Window")
