### ISSUE TITLE
Diagnostics with severity Hint and Information have no visual indication in UI

### ISSUE THREAD

**Issue by hoovercj** [Microsoft/vscode#1710]
Diagnostics created from an extension with `DiagnosticSeverity.Hint` or `DiagnosticSeverity.Information` have no indication in the UI. They show up very gray in the Errors/Warning selector (ctrl+m) and do not show indicators in the status bar and are not underlined in the editor.

**Comment by dbaeumer** [comment]
That the don't show up in the status line is by design. 

Moving to Joh for the Ctrl+M list.

**Comment by jrieken** [comment]
`Hint` has no indication by design, `Information` shows in the editor like a warning, the status bar being aligned with Ctrl+M list is also by design - which we may should discuss.

@hoovercj Can you make validate that severity information shows up? Because according to (this)[https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/services/modelServiceImpl.ts#L135] it must

**Comment by hoovercj** [comment]
Regarding `hint` having no underline indication by design, what is the intended use-case of then?

@jrieken I'll look into that, yes

**Comment by jrieken** [comment]
It would allow you to hint to a code action provider what to propose

**Comment by hoovercj** [comment]
Apologies for the late follow-up.

I just verified that:
1) Information diagnostics now show up in the status bar
2) Information diagnostics are underlined the same as warnings
3) Hint and Information diagnostics are shown in the ctrl+m list just fine.
