### ISSUE TITLE
Settings sync is suspended because of successive authorization failures. Please sign in again to continue synchronizing

### ISSUE THREAD

**Issue by Sa1D1111** [microsoft/vscode#171004]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. I keep getting this error when i keep trying to sync my settings with my github account. Settings sync is suspended because of successive authorization failures. Please sign in again to continue synchronizing
It was working just fine but then I turned off sync, and it wont come back on. I can publish to my branch still and its still signed on it says but it wont sync at all. Its still one of my authorized apps in GH so Im not sure what is going on.

**Comment by sandy081** [comment]
@TylerLeonhardt Can you please help here to understand why the auth is not working?

**Comment by TylerLeonhardt** [comment]
👋  do you use GitHub or Microsoft for Settings Sync. 

Can you follow these steps so that we can get more information on what's going on?

* Open the Command Palette
* Run the `Developer: Set Log Level...` command
* Choose `Trace`
* _Wait for the issue to happen..._
* Open the Output pane (ctrl+shift+u I think on Windows)
* drop in this issue he contents of the following:
  * `Microsoft Authentication` Output channel or `GitHub Authentication`
  * `Log (Settings Sync)` Output channel
  * `Log (Window)` Output channel

**Comment by Sa1D1111** [comment]
I got it to start working again. 
I had to delete all credentials and keys. 
Now using PAT.
