### ISSUE TITLE
Wrong translation of `format document`

### ISSUE THREAD

**Issue by calidion** [Microsoft/vscode#17120]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:14:18.217Z)
- OS Version: Linux x64 4.8.0-30-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|
|Angular2|UVBrain|0.2.9|
|html-snippets|abusaidm|0.0.13|
|project-manager|alefragnani|0.7.1|
|vscode-eslint|dbaeumer|0.10.17|
|vscode-stylesheet-formatter|dbalage|0.2.0|
|githistory|donjayamanne|0.0.6|
|python|donjayamanne|0.3.17|
|sass-lint|glen-84|0.0.1|
|docker-linter|henriiik|0.2.0|
|Angular2|johnpapa|0.4.4|
|Go|lukehoban|0.6.39|
|prettify-json|mohsen1|0.0.3|
|debugger-for-chrome|msjsdiag|0.4.4|
|sass-indented|robinbentley|0.1.3|
|addDocComments|stevencl|0.0.8|
|JavaScriptSnippets|xabikos|1.0.0|
|Material-theme|zhuangtongfa|0.0.1|

---

Steps to Reproduce:

1. right click on xx.js file
2.   Format document should be [格式化代码] instead of [设置文档格式]

**Comment by kieferrm** [comment]
@rebornix ?

**Comment by calidion** [comment]
1. [帮助] 
2. [键盘快捷方式引用]  better be [键盘快捷方式参考] or [键盘快捷方式说明] 
3. [介绍性视频]  better be [介绍视频]

**Comment by rebornix** [comment]
![screen shot 2016-12-13 at 11 16 00 am](https://cloud.githubusercontent.com/assets/876920/21155074/8deafc16-c125-11e6-8e5c-60ec4d122fe2.png)

设置文档格式 is ambiguous，it's better to translate `format` as a verb instead of non.

**Comment by johnliu2016** [comment]
@lukaschal Please send to lingual review

[formatActions.nls.resx.lcl](https://monacotools.visualstudio.com/Monaco/_git/MonacoLocalization#path=%2FLocalize%2Fchs%2Fvscode%2Fsrc%2Fvs%2Feditor%2Fcontrib%2Fformat%2Fcommon%2FformatActions.nls.resx.lcl&version=GBmaster&_a=contents)
      <Item ItemId=";formatDocument.label" ItemType="0;.resx" PsrId="211" Leaf="true">
        <Str Cat="Text">
          <Val><![CDATA[Format Document]]></Val>
          <Tgt Cat="Text" Stat="Loc" Orig="New">
            <Val><![CDATA[设置文档格式]]></Val>
          </Tgt>
        </Str>
        <Disp Icon="Str" />
      </Item>

**Comment by lukaschal** [comment]
Waiting for linguistic input.

**Comment by lukaschal** [comment]
@calidion See linguistic answer:

Actually "format" is not translated as a noun in the existing translation, it can be backtranslated to the effect of "set the format of the document", which is not an uncommon way of translation. 

And the translation of the word "format" is not even that important to me here. If the developer prefers "格式化", we can use "格式化", because that's also an acceptable translation. However, I'm a little bit dubious about translating "format document" as "格式化代码" (format code); I have yet to be convinced why we should translate "document" as "代码" (code).

And please consider the point I made yesterday:

If you look at the screenshot closely, it appears you can choose either to "format document" or "format code".

I'm asked to assess whether "Format Document" is mistranslated, the developer may have very good reason to use "格式化代码" in this context, but if it is a question about "Format Document" itself, I wouldn't say the existing translation is incorrect. 

Again, the way I see it, the problem lies in the strings below: "设置选定内容的格式" (backtranslation: set the format of the selection) and "Format Code", the developer's suggestion would be perfect for "Format Code". I have added the backtranslations of the Chinese strings in the screenshot attached (named "backtranslations"). I hope that will make my point clear.

![backtranslations 1](https://cloud.githubusercontent.com/assets/18324331/21351152/56e4dc1e-c6bb-11e6-9f89-ac81a88a1041.png)

**Comment by calidion** [comment]
@lukaschal 

Maybe it is due to the conventions we use.

Translate "Format Document"  to "设置文档格式" or  “格式化文档”  is a bit strange to me.
"设置文档格式” means "Set a type for a document" instead of "Set the format of document"。
which likes I would set it to doc,xls,ts, js etc.

"格式化代码" and "格式化文档” may have very similar meanings in Chinese, but we use "格式化代码" to describe the action of formatting a source code document. while "格式化文档” may mean nothing to do with coding or software development, it is widely used to describe the action of making a rich text docment more beautiful.

Here the word `formart` and its corresponding chinese chars -- "格式化”  are both verbs, not nouns.

so I would like to recommend: 
“Format Document" to be translated as "格式化代码“。
“Format Code" to be translated  as "格式化选定代码“。

thanks.

**Comment by HiZhaoxiaoyang** [comment]
“Format Document格式化文档” 和 “Format Code格式化代码” 不行？ 为何都是代码。

**Comment by calidion** [comment]
@HiZhaoxiaoyang 
 
应该很少有人会使用”格式化文档“这种用法。 一般我是没有见过。

**Comment by sliontc** [comment]
As a coder from china, I agree calidion.

**Comment by dengxqi** [comment]
agreed with calidion, it is better to use [格式化代码].

**Comment by lukaschal** [comment]
Fixed as suggested.

File: src\vs\editor\contrib\format\common\formatActions.nls.resx
ID: ".resx", 0; "formatDocument.label"
SRC: Format Document
TGT: 格式化代码
