### ISSUE TITLE
Code size increased quite a bit since the last version

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#17128]
- VSCode Version: 1.7, 1.8-insiders

I guess this is known, do we know why that is the case?

![screen shot 2016-12-13 at 10 12 21 am](https://cloud.githubusercontent.com/assets/9205389/21152791/ae1a8334-c11c-11e6-8ae9-a888922a9387.png)

**Comment by bpasero** [comment]
The electron update seems to account for ~2 MB in increase. What is weird is that the extensions folder grew ~8 MB. I see a new top level node_modules folder in the extensions folder that accounts for 5 MB and then many extensions also seem to have larger dependencies.

Adding @jrieken and @aeschli because I thought we did some work this milestone to reduce our footprint and now it seems we increased it.

**Comment by jrieken** [comment]
I didn't deliver my `node_module`-changes

**Comment by jrieken** [comment]
![dec-12-2016 17-21-46](https://cloud.githubusercontent.com/assets/1794099/21175434/8fd8e69c-c1e2-11e6-88e1-6b5042e31edd.gif)

**Comment by aeschli** [comment]
The problems are the new @types/ folders in the extensions.

**Comment by bpasero** [comment]
@jrieken how did you get to the numbers, is that an extension?

**Comment by bpasero** [comment]
We should remove all types folders as a post-build step, no?

**Comment by jrieken** [comment]
`du -sh * > file.txt`

**Comment by bpasero** [comment]
@jrieken thanks, useful to know for the future 👍

**Comment by joaomoreno** [comment]
Thanks for the table, @jrieken.

@chrmarti Comparing them in that way is irrelevant, since the `exe` and `deb` files are compressed, while the OSX application bundle isn't.

Here are the numbers. You can see that in their compressed form, they haven't actually increased by much:

```
👊  Downloads → du -hs stable/*
 49M	stable/VSCode-darwin-stable.zip
 32M	stable/VSCodeSetup-1.7.2.exe
 47M	stable/code-stable-code_1.7.2-1479766213_amd64.tar.gz
 48M	stable/code-stable-code_1.7.2-1479767514_i386.tar.gz
👊  Downloads → du -hs latest/*
 51M	latest/VSCode-darwin-insider.zip
 32M	latest/VSCodeSetup-1.8.0-insider.exe
 50M	latest/code-insider-1.8.0-1481622173_i386.tar.gz
 49M	latest/code-insider-1.8.0-1481623033_amd64.tar.gz
```

It's only when extracted that you actually see the difference:

```
👊  Downloads → du -hs stable/Visual\ Studio\ Code.app
147M	stable/Visual Studio Code.app
👊  Downloads → du -hs latest/Visual\ Studio\ Code\ -\ Insiders.app
153M	latest/Visual Studio Code - Insiders.app
```

**Comment by joaomoreno** [comment]
We could perform the same trick for the extensions that we do for VS Code: to read the shrinkwrap file and only copy the dependencies listed within.

An alternative is to simply ignore `@types` folders.

**Comment by joaomoreno** [comment]
Went with the _blindly remove @types_ fix.

Note: this is not a candidate.

**Comment by aeschli** [comment]
verified that the 1.9 build doesn't contain the @types folders.
Also compared against the 1.7 build and files issues for major size increases.
