### ISSUE TITLE
Zombie TS-server processes

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#17156]
- VSCode Version: 1.8 insider
- OS Version: macOS

Steps to Reproduce:

(note that I am running out of sources, did not try to reproduce from a real build)

1. open the vscode source code folder
2. run a search for "copyright"
3. replace all with "copyright2"
4. wait for all the heavy work to be done
5. ensure a ts file opens as dirty (it should automatically)
6. save all dirty buffers
7. wait for 5 seconds for the dust to settle
8. reload the window

=> at this point the activity manager shows left over TS server processes that seem to have no parent

![image](https://cloud.githubusercontent.com/assets/900690/21174229/2641c1fa-c1dc-11e6-9733-996b903d5513.png)

The process in question seems to be the typings installer:

![image](https://cloud.githubusercontent.com/assets/900690/21174337/db1d4dec-c1dc-11e6-91cf-9c917733755c.png)

**Comment by bpasero** [comment]
Update: I think this is easy to reproduce by just reloading the window with TS files open. The typings installer seems to cause the TS server to stay alive.

**Comment by dbaeumer** [comment]
I am not able to reproduce this on Windows however Windows has a more aggressive strategy to kill processes when parent processes die. 

@mjbvz can you have a look on Mac please. The way how that should work is as follows: the tsserver listen on a close event on the stream it is reading / writing to and exits if this happens. See https://github.com/Microsoft/TypeScript/blob/master/src/server/server.ts#L396

So either the streams don't close or the tsserver can't process the event since it is busy. 

@bpasero the ATA process is in since quite some time. Have you seen this before. 

Might be a change caused by adopting 2.1.x ?

**Comment by bpasero** [comment]
I never actually looked for this issue so I am not sure if it is new or not.

**Comment by intellix** [comment]
I'm also getting this. Not sure if it's exactly the same but towards the end of the day I'll have between 1-5 extra "Code Helper" processes, each taking around 100% CPU each. 
I start to notice when my projects take AGES to build, so I look at Activity Monitor and see a load of processes hanging. 
Was working last night and then upon opening my laptop this morning I notice there's another process still hanging which I have to manually kill. I've no idea what to look for or how to help you guys find the issue, but I've taken screenshots of activity monitor and process dumps etc in hopes that it helps. 

Ping me if you want me to do anything, cause it happens all the time to me

![screenshot 2016-12-22 10 18 58](https://cloud.githubusercontent.com/assets/1162531/21421143/949c3242-c831-11e6-8390-650cc1a2776b.png)
![screenshot 2016-12-22 10 21 50](https://cloud.githubusercontent.com/assets/1162531/21421141/9499feb4-c831-11e6-869c-4e66bf2bd7be.png)
![screenshot 2016-12-22 10 21 58](https://cloud.githubusercontent.com/assets/1162531/21421142/949ad604-c831-11e6-931e-3cf019dc92ec.png)
![screenshot 2016-12-22 10 22 01](https://cloud.githubusercontent.com/assets/1162531/21421140/9499cc32-c831-11e6-8e46-26db62e12ba3.png)
![screenshot 2016-12-22 10 22 13](https://cloud.githubusercontent.com/assets/1162531/21421144/94a441a8-c831-11e6-8039-9bcab1670ecf.png)

**Comment by bpasero** [comment]
@intellix To find out more about this issue, we need to get at the process that is causing the high load. VS Code creates multiple processes, each with different tasks. Depending on your OS you can get at the full command line of the process and paste it here. On Mac, the **Activity Monitor** allows to find the `PID` of the process and from a terminal `ps aux | grep <pid>` reveals its arguments. 

![image](https://cloud.githubusercontent.com/assets/900690/18907063/65806550-856a-11e6-8b2e-83da9111445d.png)

On Windows a tool like **[Process Explorer](https://technet.microsoft.com/en-us/sysinternals/processexplorer.aspx)** helps:

![image](https://cloud.githubusercontent.com/assets/900690/18907037/476f0aa8-856a-11e6-8ac3-4c1f3e803f32.png)

Once you have the information please update this issue with it. Thanks!

**Comment by intellix** [comment]
ok so it seems to be caused by this: https://github.com/angular/vscode-ng-language-service

```
/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Users/dominic/.vscode/extensions/Google.ng-template-0.0.10/node_modules/vscode-languageclient/lib/utils/electronForkStart /Users/dominic/.vscode/extensions/Google.ng-template-0.0.10/server/server.js --node-ipc
```

**Comment by mjbvz** [comment]
During last month's TS performance investigation, we tracked down many cases of these zombie processes to this TS file watcher bug: https://github.com/Microsoft/TypeScript/issues/14636 One possible workaround is to make sure that all of your `jsconfig` and `tsconfig` files specify an `include` configuration to limit the number of files that TypeScript scans. TS is looking into a fix with the next release

If you are still seeing either tsserver or typingsinstaller processes hanging around in the VSCode 1.11 even after you have properly setup your `jsconfig` or `tsconfig`, please open a new issue so that we can continue investigating this bug
