### ISSUE TITLE
Green lightbulb not displayed

### ISSUE THREAD

**Issue by memotive** [Microsoft/vscode#17154]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:01:10.756Z)
- OS Version: Darwin x64 15.6.0
- Extensions: none

According to the [documentation](https://code.visualstudio.com/docs/languages/javascript#_writing-jsconfigjson), without a `jsconfig.json` file in a workspace, VSCode should displays a **green lightbulb** on the Status Bar prompting you to create one.

This is not the case. 

This issue was already mentioned in Stack Overflow:
[http://stackoverflow.com/questions/40428298/vs-code-javascript-green-lightbulb-is-not-visible](http://stackoverflow.com/questions/40428298/vs-code-javascript-green-lightbulb-is-not-visible)

**Comment by sergeromero** [comment]
While this issue is being addressed it would be nice if someone could include the workaround to create the file manually including where in the file structure the file should be in as well as the basic content.

Thank you.

**Comment by kieferrm** [comment]
The documentation is out of date and currently being reviewed. Because of the introduction of [automated type acquisition](https://code.visualstudio.com/updates#_172-recovery-build) the need for a `jsconfig.json` is greatly reduced. Now, when you add a `jsconfig.json` file we assume that you explicitly want to define a project context and thus have in-depth knowledge about it.
