### ISSUE TITLE
TypeScript misses document symbols

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#17168]
* open https://github.com/Microsoft/vscode/blob/master/src/vs/code/electron-main/windows.ts
* trigger outline
* search for `ready`
* 🐛 you get only one result, but there is [`IWindowsMainService#ready`](https://github.com/Microsoft/vscode/blob/master/src/vs/code/electron-main/windows.ts#L92) and [`WindowsManager#ready`](https://github.com/Microsoft/vscode/blob/master/src/vs/code/electron-main/windows.ts#L156) 

![screen shot 2016-12-14 at 12 39 59](https://cloud.githubusercontent.com/assets/1794099/21180684/7187f8aa-c1fa-11e6-9cc7-d66261c6182d.png)

**Comment by mjbvz** [comment]
I believe this has been fixed by TS. We still point to TS 2.0.x for vscode itself using `"typescript.tsdk"`. After removing this setting so that we use TS 2.1.4 for analysis, I now see both symbols listed.

![screen shot 2016-12-14 at 11 37 13 am](https://cloud.githubusercontent.com/assets/12821956/21197802/aa4fe642-c1f1-11e6-82fc-45b452248942.png)
