### ISSUE TITLE
Closing a terminal in the editor view unfocus the editor view

### ISSUE THREAD

**Issue by pierrelegall** [microsoft/vscode#171758]
Type: <b>Bug</b>

When you use the terminal in the editor view (`terminal.integrated.defaultLocation` set to `editor`), closing it with `exit` shell command unfocus the editor view ; which is not consistent with the behavior of closing a file in the editor view (and kind of annoying).

Same result with extensions disabled.

Steps to reproduce:

1. Open a terminal (with `terminal.integrated.defaultLocation` set to `editor`)
2. Exit the terminal (with `exit` shell command)
3. The editor view is not focused

System info:
- VS Code version: Code 1.74.3 (97dec172d3256f8ca4bfb2143f3f76b503ca0534, 2023-01-11T09:00:07.949Z)
- OS version: Linux x64 6.1.6-arch1-1

**Comment by pierrelegall** [comment]
Related to: #171759

**Comment by Zaxiure** [comment]
This issue breaks my flow with using the VIM extension and using Lazygit inside the terminal with a keybind. The command it runs is lazygit && exit, so whenever I exit lazygit it exits the terminal afterwards. The issue is that it breaks the flow of not using my mouse as it fails to focus the editor again as seen in the screen recording. My pull request fixes this issue by focussing the panel once it exits the terminal.

https://github.com/microsoft/vscode/assets/8901040/f81a7755-06cd-4f3e-b085-da20724c857e

**Comment by bpasero** [comment]
PR: https://github.com/microsoft/vscode/pull/201047
