### ISSUE TITLE
[Codespaces] flask application not getting port forwarded

### ISSUE THREAD

**Issue by AnveshMora** [microsoft/vscode#171994]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Code space VS code
- OS Version: Codespaces

Steps to Reproduce:

1. Below is the .devcontainer/devcontainer.json file for initializing docker in codespace:
```
// For format details, see https://aka.ms/devcontainer.json. For config options, see the
// README at: https://github.com/devcontainers/templates/tree/main/src/python
{
	"name": "Python 3",
	// Or use a Dockerfile or Docker Compose file. More info: https://containers.dev/guide/dockerfile
	"image": "mcr.microsoft.com/devcontainers/python:0-3.11-bullseye",

	// Features to add to the dev container. More info: https://containers.dev/features.
	// "features": {},

	// Use 'forwardPorts' to make a list of ports inside the container available locally.
	// "forwardPorts": [],

	// Configure tool-specific properties.
	"customizations": {
		// Configure properties specific to VS Code.
		"vscode": {
			"settings": {},
			"extensions": [
				"streetsidesoftware.code-spell-checker",
				"ms-python.python"
			]
		}
	},

	// Uncomment to connect as root instead. More info: https://aka.ms/dev-containers-non-root.
	// "remoteUser": "root"
	//"postCreateCommand": "pip3 install -r requirements.txt",

	"waitFor": "onCreateCommand",
	"updateContentCommand": "pip install -r requirements.txt",
	"postCreateCommand": "",
	"postAttachCommand": {
		"server": "uvicorn main:app --host 0.0.0.0 --port 3000 --reload"
	},
	"portsAttributes": {
		"3000": {
		"label": "Application",
		"onAutoForward": "notify"
		}
	},

	"forwardPorts": [3000]
}
```
2. Code space is not automatically port forwarding or I'm not able to manually add the port forwarding.
3. I've tried with and without --host in `postAttachCommand`

**Comment by AnveshMora** [comment]
@alexr00  any help here? much appreciated!

**Comment by alexr00** [comment]
@AnveshMora since you have `"forwardPorts": [3000]` in your `devcontainer.json` I would expect Codespaces to forward the port when you connect to the Codespace. For that, I would recommend you report an issue over in https://github.com/community/community/discussions/categories/codespaces.

If you don't include the `forwardPorts` property then we should see that something is listening on 3000 and forward it. However, we don't forward ports that already have something listening on them at the time that VS  Code connects to the Codespace. I think that your `postAttachCommand` is happing a bit sooner than we expect and then we don't forward the port. 

Since you do have `portsAttributes` configured we should still forward the port. I'll make a fix for this. It should be in a VS Code insiders build by the end of the week.
