### ISSUE TITLE
Zen Mode could have an option to show only the current tab

### ISSUE THREAD

**Issue by jx22** [Microsoft/vscode#17207]
- VSCode Version: 1.8
- OS Version: macOS and Windows

Steps to Reproduce:
1. Zen Mode

I love Zen Mode. Thank you. The line of tabs on the top of the app can be just a tad bit distracting, though. It would be great to switch to only a single window at a time; if you move your mouse to the top of the window then the line of tabs should drop down, just as the dropdown menu does when you're in full-screen mode. I imagine that it would be most accommodating to all users to enable hiding of the line of tabs as an option, as opposed to the default.

**Comment by isidorn** [comment]
Zen Mode should just disable tabs - similar to what you get when you enter 	`"workbench.editor.showTabs": false`

However this setting is currently not centrilazide and some service needs to be aware of it.
@bpasero is it fine if you upgrade the part service to also be in charge of displaying of tabs

Assigning to January to investigate into enabling this - since even the venture beat article wants this feature 😁  
http://venturebeat.com/2016/12/14/microsoft-releases-visual-studio-code-1-8-with-hot-exit-zen-mode-view-picker/

**Comment by bpasero** [comment]
As discussed, I move the tabs boolean to `IPartService` and let all clients read it from there including eventing.

**Comment by jensbodal** [comment]
Sorry to comment on a closed issue, but is it possible to re-enable this feature through a setting? From what I tried there’s no way to see the tabs in zen mode, I need to press CMD+P to see what’s open then select using arrow keys.  I like swapping between editors with `gt` and `gT` but find it helpful to see the tabs so I know which direction to go.

**Comment by isidorn** [comment]
"workbench.editor.showTabs": true

**Comment by itsFrank** [comment]
@jensbodal it's actually this setting: `"zenMode.hideTabs": true,`
