### ISSUE TITLE
Clone repository locally weird label

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#172172]
Testing #172040

Why is there "... Git" part at the end? Can we remove the "Git" part of the label?

![Screenshot 2023-01-24 at 15 24 54](https://user-images.githubusercontent.com/1926584/214320948-65ef38b1-e953-49b2-be47-54847e5c6498.png)

**Comment by joyceerhl** [comment]
That's the extension which contributes that option included in the quickpick item description. I included this because we've always had it for the Continue On picker, and I think we have/had a pattern of showing which extension contributed which QPI... @TylerLeonhardt do we have guidance for quickpicks which display extension-contributed elements?

**Comment by TylerLeonhardt** [comment]
For 1 to 1 scenarios, doing what you're doing makes sense. The alternative is using the `detail` but I think that's a waste of space.

For 1 to many scenarios, using a separator to group by extension is a common pattern.

**Comment by joyceerhl** [comment]
Thanks for the context @TylerLeonhardt! Remote Repos does contribute two entries if you're on desktop in a remote repo (continue on web and continue in local clone) or in web in a remote repo (continue in desktop and continue in local clone), but all the rest of the Continue On options are the only ones from their extension... so I think the separator is mostly going to add visual weight and would prefer to keep things as is.
