### ISSUE TITLE
Auto publishing: Create New Codespace fails

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#172148]
Testing #172030

Choosing Never failed:
<img width="458" alt="image" src="https://user-images.githubusercontent.com/9205389/214288041-6ad4da36-839b-43a2-85c8-f02c235db3a7.png">

**Comment by chrmarti** [comment]
Choosing Always also failed:
<img width="453" alt="image" src="https://user-images.githubusercontent.com/9205389/214289228-9ee905fa-b915-412c-9a07-d9dd0658f271.png">

**Comment by chrmarti** [comment]
I was using a public repo: https://github.com/chrmarti/smktst

**Comment by bamurtaugh** [comment]
I experience the same on Windows 11 with the repo: https://github.com/bamurtaugh/theCatSaidNo.

**Comment by bhavyaus** [comment]
Create New Codespace still fails with ContinueOn

**Comment by joyceerhl** [comment]
The original issue reported here was due to the fact that we weren't properly awaiting the branch publish before invoking the codespace creation. @bhavyaus based on our offline discussion I think you're encountering a different issue because the publish completes but the codespace creation doesn't start, and only if you aren't signed into the GitHub Codespaces extension, so I'm going to close this issue and we can file a new one to investigate the scenario you've uncovered.
