### ISSUE TITLE
`logger.logError("hello error");` does not trigger error handler

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#172130]
Testing #172057

When you pass a string to `logError`, it seems to trigger the `sendEventData` handler but not `sendErrorData` handler. Works fine when you pass in an error though.

**Comment by lramos15** [comment]
This is expected. The only difference between `logError` with a string and `logUsage` is what telemetry setting level we let through. This allows the authors to have more leeway in terms of what they think in error is rather than requiring an error stack. Let me know if you think the docs could be more clear on that. `sendEventData` vs `sendErrorData` is just in case your sender handles stacks different than string data.
