### ISSUE TITLE
Should large file limit depend of source, not env?

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#172138]
Testing #171743

The serverless large file limit is 50MB which makes sense when browsing GH repos, however when browsing local files it doesn't make sense I would expect no limit or a much higher limit. So, instead of defaults that are runtime/environment specific should this limit be defined by the provider of the file system?

**Comment by bpasero** [comment]
I like the idea of letting the file system provider decide, but for now went with a simpler approach in https://github.com/microsoft/vscode/pull/172355: we simply check for the resource scheme being `file` and return our highest limit in that case for both desktop and web. 

The slight downside of this approach is that the `workbench.editorLargeFileConfirmation` is not applying in all contexts, i.e. if a user configures that to be 1 MB and opens a local file with 1 GB, we still allow to open it. But I think that is tolerable because the main intent of this change was not to make it harder to open local files, but to make it less likely to open large files in remote only.

**Comment by bpasero** [comment]
via https://github.com/microsoft/vscode/pull/172355
