### ISSUE TITLE
Auto publishing dialog missing Yes option

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#172144]
Testing #172030

I can't choose to publish and ask again next time:
<img width="264" alt="image" src="https://user-images.githubusercontent.com/9205389/214285867-3282a3ac-257d-46f1-a8dc-88b95d91b6ac.png">

**Comment by chrmarti** [comment]
Also: The text doesn't indicate that the Always/Never choice only applies to the current workspace folder (as I just discovered) and not to all repositories.

**Comment by bamurtaugh** [comment]
+1, I was about to file the same issue. 😄

**Comment by joyceerhl** [comment]
Great feedback, this leads me to think we should just have 'Yes' and 'Cancel' as the options here, because choosing 'Never' will break the Continue On flow (i.e. it's not an option that we can actually support, and per https://github.com/microsoft/vscode/issues/172147 we should actually throw a `CancellationError` and bail out of the whole flow here).

**Comment by chrmarti** [comment]
'Publish Branch' might be clearer than 'Yes'. The PR extension uses this dialog:
<img width="261" alt="image" src="https://user-images.githubusercontent.com/9205389/214513882-1dc8f436-3c08-4d78-b233-bd560fd1dea4.png">

**Comment by Meligy** [comment]
The "fix" for this is more problematic for me.

I used to have this in my settings:

```json
  "git.publishBeforeContinueOn": "never"
```

Now every time I quit VS Code (I'm on Mac if it makes a difference), I see the dialog and I have to press "Cancel". Even worse, pressing "Cancel" seems to only close the dialog and reopen it again.

Can we reopen this issue and restore the setting at least?
