### ISSUE TITLE
Unable to save to gist when using user-data instance of vscode

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/vscode#172340]
Testing #172051

This is unrelated to profiles but a general issue with logging into Github.

1. Start VSCode log out of github.
2. Instance1: start an instance of vscode with default user-data: `code .` , leave this running.
3. Instance2: start another instance of vscode with user-data set: `code --user-data-dir=userdata1 --extensions-dir=extensions1 .`
4. Do any action that requires github login. In my case it was export profile to gist.
5. You get a prompt  to login using web. follow the prompt. after logging in, you get a prompt on the browser to open vscode.
6. The link does not open in the right instance of vscode. The Instance 2 fails logon.

**Comment by TylerLeonhardt** [comment]
Just to be clear, you're saying when the browser redirect back to VS Code, it does not redirect to the right one?

This is almost certainly because you're using --user-data-dir which is more of a debugging tool than anything else. I would guess that if you didn't have that, this would work as expected.

In any case, I'll pass this over to @joaomoreno who owns UriHandlers

**Comment by joaomoreno** [comment]
Yeah this scenario isn't supported.
