### ISSUE TITLE
Clarify length definition for quick fixes

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#172474]
This was meant to be _wrapped lines_ in my eyes, so we might want to clear that up later? I made a change in this area recently as it was causing a freeze

_Originally posted by @Tyriar in https://github.com/microsoft/vscode/pull/172471#discussion_r1087248257_

**Comment by rzhao271** [comment]
I actually find the term wrapped lines more confusing, because I wasn't sure whether it meant taking what the user sees and splitting those into lines, or whether it meant imagining wordwrap wasn't there and then splitting that result into lines. I was thinking of the term "actual lines", but that's also confusing.

I reduced the terminal width a lot and still saw the lightbulb show up asking me to create a PR though :+1:
