### ISSUE TITLE
github.dev "unable to open" repositories

### ISSUE THREAD

**Issue by dakotablair** [microsoft/vscode#172537]
Does this issue occur when all extensions are disabled?: Yes

I am having trouble with github.dev originally [described here](https://github.com/community/community/discussions/45352).

I switched from Insiders back to Stable and this seems to have fixed things for now. Here is the version I was having difficulty with, as reported by the web issue reporter:

>Version: 1.75.0-insider
Commit: 270c3b12906a88e9c67fc5ddef87be6aa3b75551
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Embedder: github.dev
>
>&lt;!-- generated by web issue reporter -->

and for stable:
>Version: 1.74.3
Commit: 97dec172d3256f8ca4bfb2143f3f76b503ca0534

I have observed this using Insiders on github.dev, but using insiders.vscode.dev does not produce the same issue.

Steps to Reproduce:

1. Load https://github.dev/django/django
2. Switch to insiders channel.
3. Observe error (image has extensions enabled, but I observed the same behavior with them disabled): ![unable to open error](https://i.imgur.com/owINGOp.png)

**Comment by joyceerhl** [comment]
The `vscode-vfs` filesystem provider ships with the Remote Repositories extension, and the latest published stable version of Remote Repositories is not compatible with the latest published VS Code Insiders due to proposed API changes. insiders.vscode.dev ships with the latest prerelease of Remote Repositories which _is_ compatible with VS Code Insiders. This issue will be resolved with the next stable Remote Repositories, and is mitigated in the meantime by using github.dev stable or insiders.vscode.dev.
