### ISSUE TITLE
vscode.dev splash screen is not lifted

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#172560]
**Steps:**
* open incognito browser window (I used Chrome)
* navigate to https://insiders.vscode.dev/github/microsoft/vscode/blob/main/package.json
* 🐛 a splash shows and never hides
* when you remove the splash DOM node via devtools, you see this:

<img width="1047" alt="image" src="https://user-images.githubusercontent.com/900690/214911408-0c25cfb8-ba7e-481a-9f19-b3a4047b2da6.png">

and eventually this:

<img width="1047" alt="image" src="https://user-images.githubusercontent.com/900690/214911457-d6a6ae7f-34e4-4277-bb6c-cb7240ad7fc6.png">

Video:

![Recording 2023-01-26 at 18 50 14](https://user-images.githubusercontent.com/900690/214911305-804c706d-efc6-4da1-af13-8f08f8705cf6.gif)

//cc @joaomoreno

**Comment by bpasero** [comment]
The splash is removed here:

https://github.com/microsoft/vscode/blob/2238a146cf93f0f668fccf5054fb4a2140dc3e4d/src/vs/workbench/contrib/splash/browser/partsSplash.ts#L42-L45

Which seems to indicate that `LifecyclePhase.Restored` is not reached. We set it here:

https://github.com/microsoft/vscode/blob/2238a146cf93f0f668fccf5054fb4a2140dc3e4d/src/vs/workbench/browser/workbench.ts#L444-L445

Since we have a fallback timeout of 2s here:

https://github.com/microsoft/vscode/blob/2238a146cf93f0f668fccf5054fb4a2140dc3e4d/src/vs/workbench/browser/workbench.ts#L426

I think we never reach at least one of the layout ready promises here:

https://github.com/microsoft/vscode/blob/2238a146cf93f0f668fccf5054fb4a2140dc3e4d/src/vs/workbench/browser/layout.ts#L731

**Comment by bpasero** [comment]
Also adding @sbatten for the layout piece. Since Zurich is about to go to bed, maybe Redmond could continue the investigation.

**Comment by sbatten** [comment]
I was investigating and noticed this reproduces with vscode.dev as well, it is not unique to insiders. https://vscode.dev/github/microsoft/vscode/blob/main/package.json

**Comment by bpasero** [comment]
@sbatten thanks, indeed this has been like that forever.

@joyceerhl the underlying reason seems to be this call that never returns without user action:

https://github.com/microsoft/vscode/blob/acbbdaa41a459aab86072e8d97255cd2ea1d9529/src/vs/workbench/services/extensions/common/abstractExtensionService.ts#L199

Can you check in the extension what is going on there?

We actually try to resolve the initial editors to open on startup and this is the reason it only shows when you do a deep link such as https://vscode.dev/github/microsoft/vscode/blob/main/package.json. The promise that never returns is actually this one:

https://github.com/microsoft/vscode/blob/acbbdaa41a459aab86072e8d97255cd2ea1d9529/src/vs/workbench/common/editor.ts#L1435

As part of the file service call we activate the file system provider to ensure it can answer the request.

It is weird to me why this resolves with another window reload, so I suspect the extension maybe able to fix this?

**Comment by jrieken** [comment]
I remember a similar endless activation issue in the command service where we ended up to race activation against a [timeout](https://github.com/microsoft/vscode/blob/990a496681948ec274da5503b35cd49a7d06c0a2/src/vs/workbench/services/commands/common/commandService.ts#L38-L47)

**Comment by bpasero** [comment]
Yeah, something like that would be my fallback solution.

**Comment by joyceerhl** [comment]
I debugged this back into the main thread, it looks like this promise in `IDialogService#show` never resolves:

https://github.com/microsoft/vscode/blob/8cd2eb1b3273e8f874c62e0b508ced1d3f34422a/src/vs/workbench/services/dialogs/common/dialogService.ts#L58

That call comes from MainThreadAuthentication (fyi @tylerleonhardt):
https://github.com/microsoft/vscode/blob/8cd2eb1b3273e8f874c62e0b508ced1d3f34422a/src/vs/workbench/api/browser/mainThreadAuthentication.ts#L189
 
We need this call to resolve in order to display the modal dialog for GitHub Repositories authentication, since GitHub Repositories requires authentication in order to fetch editor contents at the moment.

What is interesting is that if I am stuck on the splash screen and reload the page, I briefly see the expected modal dialog show up.

**Comment by bpasero** [comment]
@joyceerhl thanks for debug, but this can be explained by the fact that the dialog shows waiting for user input behind the splash screen right?

I wonder why it resolves though after a window reload...

**Comment by joyceerhl** [comment]
What I see on a reload is the following sequence of events: 1. the dialog appears, 2. the callback for `LifecyclePhase.Restored` runs and `_removePartsSplash` runs. Thus it seems like on a reload the splash screen is never rendered to begin with.

**Comment by joyceerhl** [comment]
Editors cannot restore without user interaction with the modal dialog that we show, so I wonder if we can render the dialog atop the splash screen instead to ensure the user doesn't get stuck like this. If we're not willing to do that, I could also look into unauthenticated support for GitHub Repositories so that we remove the requirement to show the modal dialog in the first place.

**Comment by bpasero** [comment]
One idea like that would be to lift the splash when a dialog appears. We have events for that case:

https://github.com/microsoft/vscode/blob/c3890ef381100de93609e6e4e6976de888ba5941/src/vs/platform/dialogs/common/dialogs.ts#L533

**Comment by bpasero** [comment]
Idea after talking with Jo is to have a new event from layout to signal that the parts have rendered and use that as a signal to lift the splash screen.
