### ISSUE TITLE
Prompt users to install an extension when editor fails to open due to missing fs provider

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#172660]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. on desktop I had a RemoteHub repo opened
2. then I created a new blank profil
3. reloaded the window and wondered why I got this:
![image](https://user-images.githubusercontent.com/2644648/215162972-8b07ffe1-035c-4603-9373-97a954c249b9.png)

Then I realized... my profile no longer had RemoteHub in it 🤦 and I shot myself in the foot.

I feel like this experience could be improved whenever you don't have the extension required to load the filesystem or a Custom Editor.

The "Try Again" button seems lacking. I wish there was another button that said something like:
* oh you have this installed just not in this profile
or 
* oh you don't have that installed let’s go find that on the marketplace

**Comment by joyceerhl** [comment]
The best-case scenario would be something like what we do with extension URI handlers--if the desired extension is not already installed, we actually prompt the user to install it, wait for the install to complete, and then actually call its URI handler, so the user never ends up in an error state.

**Comment by bpasero** [comment]
Maybe a simpler change would be to just show another button to search for extensions that provide a file system provider for the extension, if we can query for that.

**Comment by joyceerhl** [comment]
This issue only covers when there are open editors, but relatedly, @lramos15 we have no handling at the moment for when the explorer `stat`s a workspace folder and it throws due to missing fs provider. 

The fs provider can be missing for the following known reasons:
1. the extension host fails to load (extensionHostWorker fails to download)
2. the extension host fails to start (e.g. another extension crashes the host)
3. fetching extension info from the Marketplace API during extension scanning fails due to transient network conditions or service outages
4. downloading the extension bundle from the VS Code unpackage service fails due to transient network conditions or service outages
5. the extension itself fails to activate (which happened several times due to proposed API carnage across VS Code versions and the current extension scanning behavior which first loads existing extensions from local cache which may not be compatible with the latest VS Code workbench)

There is currently zero UI indication of what went wrong when any of these cases happens. In all of these cases I think we should display a dialog with something like the following text:

```
"The workspace folder could not be loaded because the filesystem provider is not available. Please ensure the extension contributing this filesystem provider is installed and enabled. Try reloading the window, or report an issue if this persists."
```

With options to
- open extensions view to search for `@installed`
- reload window
- report issue

**Comment by bpasero** [comment]
> In all of these cases I think we should display a modal dialog with something like the following text:

Not sure about a modal dialog, but I agree that the explorer showing the entry with yellow exclamation mark can probably be improved. If instead we could show welcome content to guide the user into installing the right extension, would that work?

As for the editor, we can do a similar thing with asking users to check for extensions. The editor pane has support to show errors with actions, see for example:

https://github.com/microsoft/vscode/blob/43db9d2d06df4ff7b7f029b30bbdaea51b8f16f5/src/vs/workbench/contrib/files/browser/editors/textFileEditor.ts#L200-L224

Throwing such an error will show the editor similar to here:

![image](https://user-images.githubusercontent.com/900690/216768112-52e54db0-9b7e-40e9-8f4e-aaa7df329f5d.png)

Since you feel strong about it, I suggest you start working on this issue and loop in Logan for the explorer as well.
