### ISSUE TITLE
[themes] Provide default colour for custom syntax highlighting scopes

### ISSUE THREAD

**Issue by tomqwpl** [microsoft/vscode#172726]
Let's say I'm creating a syntax highlighting grammar for a file type that doesn't constitute a "language". For example, I want a highlighter for a log file. Naturally I want my grammar to generate scope names like "log.error", "log.warning", "log.info". 
If I do that, then nothing gets highlighted, since no theme will provide colour definitions for those scope names.

My options would appear to be to create a suite of new themes that add these definitions, but them someone using my mode also has to use a matching theme. If they are using a custom theme of their own already, they they are going to have to modify it otherwise my syntax highlighting mode will basically do nothing.

Alternatively, rather than using something like "log.error", I pick an existing scope name that has nothing semantically to do with my mode, it just happens to have the right kind of colour in the default themes. My syntax highlighting mode then works out of the box, stuff gets coloured, but using basically random scope names, and someone's custom theme might change the colour inadvertently in odd ways.

It feels like what I want to do is provide a default colouring to go with my scope names. So my extension provides information that says "for a basically dark theme, use this colour if nothing has been defined by a theme, for a basically light theme use this colour".

I'm raising this partly to clarify that this is indeed the situation, that I'm not missing something, and if it is, as a request for this default colour functionality.

**Comment by aeschli** [comment]
The problem of coloring errors/warnings/infos in output file is a known one. 
For that the following scopes are available by default in every theme:
`token.info-token`, `token.warn-token`, `token.error-token`, `token.debug-token`

But I assume you just brought that up as example for a language construct that is not common and unknown to mainstream TextMate themes. 
Yes, if you want colors in most themes, you have not other choice than use [well-known scopes](https://macromates.com/manual/en/language_grammars). That said, the TextMate scopes are kind of general, and you can extend them by adding more specific scopes and a language suffix. That gives you basic support in all themes, and still allows themes to provide more support once they are aware of your language.

As you see, we implemented default colors for `token.info-token`, `token.warn-token`, `token.error-token`, `token.debug-token`
This 'kind of works' as errors are normally red, warnings yellow and so on. But also there we fail if a theme happens to have a red background.
That's why its better to not add extra colors but only use only colors defined themes. And that's why adding default colors is IMO not such a good idea. Also, we want to stay TextMate compatible.

**Comment by aeschli** [comment]
We currently have no plans of a adding (more) default colors for syntax highlighting

**Comment by tomqwpl** [comment]
Ah, I hadn't found "token.warn-token", and I'd looked around the theme definitions.
I was using a log file as an easy to understand example that didn't fit into the standard "programming language" pattern.

What I've seen done is to define the scope name as two values, such as "comment log.verbose" or even "string.regexp, strong log.error". The first one gives you a "default" (it's a common scope name that gives the right colour) and the second one is a custom name that can then be referenced in a theme of you want. I suspect that this isn't intended to work, it probably works because these things end up as CSS styles? I can find no reference in any documentation to the fact that that's allowed anyway.

Anyway, thanks for the clarification.
