### ISSUE TITLE
Hot exit does not preserve the Language mode for unsaved files

### ISSUE THREAD

**Issue by stoinov** [Microsoft/vscode#17319]
- VSCode Version: 1.8.0
- OS Version: Windows 7 x64

Steps to Reproduce:

1. Create new file in VSCode and do not save it
2. Change the **Language Mode** to something other than **Plain Text**
3. Restart the editor with **Hot Exit** enabled.

The reopened **Untitled-1** tab will have Plain Text as Language, even though another one was selected previously.

**Comment by TheEskhaton** [comment]
- VSCode Version: 1.8.0
- OS Version: Windows 10 x64

Having the same problem.

The Serialized data for the editor seems to be fine, saves the modeId correctly.

![image](https://cloud.githubusercontent.com/assets/1377663/21263036/ca060b16-c394-11e6-91c9-6a4f6bbf8576.png)

There might be a problem in deserializing, but I cannot debug the deserialize method since the debugger won't break in it. It starts listening after the editor is already loaded.

Is there any way to debug this?

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/16803
