### ISSUE TITLE
Unsaved notebook fails to render when a folder is added to the workspace

### ISSUE THREAD

**Issue by minsa110** [microsoft/vscode#173219]
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.75.0-insider (user setup)
Commit: e2816fe719a4026ffa1ee0189dc89bdfdbafb164
Date: 2023-02-01T15:16:18.248Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes

Steps to Reproduce:

1. Open a folder
2. Make changes to an `ipynb` file but don't save
3. Add a folder to the workspace
4. Click "Cancel" when prompted to save
5. The `ipynb` file doesn't render in notebook view (I could open it as `json` if I click "Open in Text Editor" though)
6. Workaround is to reload the window

![new workspace ipynb rendering issue](https://user-images.githubusercontent.com/10833267/216466470-414dff5f-1d0f-4ba3-aa90-4647a7516952.gif)

**Comment by bpasero** [comment]
The underlying reason is very likely the fact that we restart the extension host which is tough for any editor that requires the EH to work (for example custom editors).

Here the stack trace is:

```
notebookEditor.js:194 TypeError: Cannot read properties of undefined (reading 'onDidChangeContent')
    at NotebookEditor.setInput (notebookEditor.js:154:64)
    at async EditorPanes.doSetInput (editorPanes.js:292:17)
    at async EditorPanes.doOpenEditor (editorPanes.js:166:44)
    at async EditorPanes.openEditor (editorPanes.js:65:24)
    at async editorGroupView.js:809:65
```

**Comment by roblourens** [comment]
I guess

1. Why is it forcing a save?
2. And if I cancel the save, why doesn't that cancel reloading the EH?

**Comment by bpasero** [comment]
@roblourens because all notebooks get disposed:

https://github.com/microsoft/vscode/blob/43db9d2d06df4ff7b7f029b30bbdaea51b8f16f5/src/vs/workbench/api/browser/mainThreadNotebook.ts#L41-L44

Which triggers closing:

https://github.com/microsoft/vscode/blob/43db9d2d06df4ff7b7f029b30bbdaea51b8f16f5/src/vs/workbench/contrib/notebook/browser/notebook.contribution.ts#L562-L568

We cannot cancel restart of the EH today through any user interaction and to be fair, restarting the EH is somewhat silly still and just to support deprecated API for the root path...

**Comment by roblourens** [comment]
Yeah, I just would have to read more to follow how this is different than closing vscode where hot exit works. But true, we still have the huge thread at https://github.com/microsoft/vscode/issues/69335 and I think that getting rid of restarting the EH is the right fix for this situation.
