### ISSUE TITLE
git.stage command doesn't work with Uri arguments

### ISSUE THREAD

**Issue by justanotheranonymoususer** [microsoft/vscode#173204]
Does this issue occur when all extensions are disabled?: No (although probably need built in git extension)

Version: 1.74.3 (user setup)
Commit: https://github.com/microsoft/vscode/commit/97dec172d3256f8ca4bfb2143f3f76b503ca0534
Date: 2023-01-09T16:59:02.252Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: No

I tried to call `git.stage` with extension API to stage a single file like this:
```
vscode.commands.executeCommand('git.stage', vscode.Uri.file(path.join(repoPath, 'file.txt')));
```

Like it's done in smoke tests:
https://github.com/microsoft/vscode/blob/96af2a5e2e1344e3a697c0efb963ceca2caba153/extensions/git/src/test/smoke.test.ts#L103

After some debugging, I understood that the tests use the `Uri` type, but the command expects the internal `class Resource` type which I cannot use. I don't understand why. So 2 things are wrong here:
1. Tests don't use the correct arguments
2. It's impossible for extensions to stage a single file.

I prefer if the tests would end up being correct and if you can fix API to accept `Uri` types, thank you.

Steps to Reproduce:

1. Call `vscode.commands.executeCommand('git.stage', vscode.Uri.file(path.join(repoPath, 'file.txt')));`
2. File isn't staged, unless by accident it's focused, because with wrong arg types the API confusingly stages the focused file. Wasted lots of time to me.

**Comment by lszomoru** [comment]
Thanks for filing this issue. The commands implemented in the git extension are not really meant to be invoked by other extensions exactly for the reasons that you have outlined. The Git extension exposes [an extension API](https://github.com/microsoft/vscode/tree/main/extensions/git#api), that other extensions can use in order to programatically interact with a git repository. 

In order to stage a file you can use the `ApiRepository.add(paths: string[])` method.

**Comment by lszomoru** [comment]
@gregvanl, what would be the best way to surface the git extension API on the documentation portal?

**Comment by gregvanl** [comment]
@lszomoru A good first step might be to add a Git-specific section into the Source Control extension guide at https://vscode-site-prod-weu.azurewebsites.net/api/extension-guides/scm-provider.
There is already a link to the Git extension API in the Next Steps section.  
Adding an H2 with a few paragraphs about the API and a couple short examples would probably be enough. 
I don't think we need to generate a new API reference page as once an extension author adds git.d.ts to their project, they'll get IntelliSense along with descriptions in the editor, rather than jumping back to the website to review the API.

**Comment by justanotheranonymoususer** [comment]
> The Git extension exposes [an extension API](https://github.com/microsoft/vscode/tree/main/extensions/git#api)

I tried that by adding this to a test extension, as instructed:
```typescript
const gitExtension = vscode.extensions.getExtension<GitExtension>('vscode.git').exports;
const git = gitExtension.getAPI(1);
```
And I got the following error:
> Activating extension 'vscode-samples.cat-coding' failed: Extension 'vscode.git' is not known or not activated.

I want to run a command on extension init, how can I be sure that the 'vscode.git' is ready? Or how to wait for it?

**Comment by lszomoru** [comment]
Please add `extensionDependencies` ([docs](https://code.visualstudio.com/api/references/extension-manifest)) into the `package.json` of your extension.
