### ISSUE TITLE
Can hide "split terminal", but hide is grayed (minor UI bug)

### ISSUE THREAD

**Issue by justanotheranonymoususer** [microsoft/vscode#173221]
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.75.0 (user setup)
Commit: e2816fe719a4026ffa1ee0189dc89bdfdbafb164
Date: 2023-02-01T15:23:45.584Z (1 day ago)
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: No

Steps to Reproduce:

See screenshot. Interestingly it's the only button with this bug.

![image](https://user-images.githubusercontent.com/5781692/216472492-eb444f59-8f1b-43fc-ae52-3cefd8cb13e6.png)

**Comment by jrieken** [comment]
This happens because the "Split Terminal" command is very special. Hiding is only supported for menu item actions but for this specific command an [ad-hoc replacement action](https://github.com/microsoft/vscode/blob/c600c105793d31942279de2ad95dbbb61c29715f/src/vs/workbench/contrib/terminal/browser/terminalView.ts#L204) is being created. The configure menu further down the road cannot offer the contextual hide because it doesn't know to what menu the command belongs

**Comment by Tyriar** [comment]
Currently this command's visibility is determined by this setting `terminal.integrated.tabs.showActions`
