### ISSUE TITLE
Question: How do I remove `Microsoft` folder from my `$HOME`?

### ISSUE THREAD

**Issue by pftbest** [Microsoft/vscode#17336]
- VSCode Version: 1.8.0
- OS Version: Ubuntu 14.04

Every time I start vscode this directory structure is being created inside my home folder:
```
~/Microsoft $ tree
.
└── TypeScript
    ├── node_modules
    │   └── types-registry
    │       ├── index.json
    │       ├── package.json
    │       └── README.md
    └── package.json

3 directories, 4 files
```

How do I change it's path, so it will be created somewhere else, or how do I prevent it from being created at all?
It ruins alignment of my other folders inside $HOME, and makes me feel uneasy.

**Comment by mjbvz** [comment]
I think you are running into #16318. This is a known issue with TypeScript 2.1.4. The only workaround for now is it to install a new version of typescript that has this fixed (such as 2.1.5 insiders or any of the 2.2.x insiders builds). We plan on picking up a version of TS with this fixed in the insiders builds shortly.

**Comment by mjbvz** [comment]
You should also be able to set `"typescript.disableAutomaticTypeAcquisition": true` to prevent this folder from being recreated with the current typeScript builds. Automatic typings acquisition is what creates this folder.

**Comment by pftbest** [comment]
Thank you!
