### ISSUE TITLE
problem when launching vs code from terminal on a folder in Ubuntu 14 

### ISSUE THREAD

**Issue by lucianFXD** [Microsoft/vscode#1733]
I get this message:
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
After this message the terminal freezes and I can launch for example another vs code instance.

**Comment by bpasero** [comment]
@lucianFXD how do you launch it from the terminal?

**Comment by lucianFXD** [comment]
I typed  code . inside a test folder. And I get that message.

**Comment by bpasero** [comment]
@lucianFXD what linux distro is this?

**Comment by lucianFXD** [comment]
I am using Ubuntu 14.04.This is the problem:
![proof](https://cloud.githubusercontent.com/assets/16511061/12128211/8bbd4aae-b404-11e5-8a2c-21b05b7f080d.png)

**Comment by bpasero** [comment]
@lucianFXD so code actually works normally after this point right? You say, the terminal freezes, but what really happens is that the terminal is launching Code and does not return from that process.

@joaomoreno do we have something like code.bat for Linux too so that you can run code and it returns immediately and hides any output? I see https://code.visualstudio.com/docs/editor/setup#_linux but I wonder if that one eats the output and returns immediately?

**Comment by joaomoreno** [comment]
We don't, we should definitely do one.

**Comment by bgse** [comment]
@bpasero @joaomoreno I don't really see the need for a startup script here if this is just about returning control to the shell or silencing standard output.

If the user wishes to do so, they can start VSCode from the shell (assuming current directory is supposed to be opened):

code . &

This will return control to the shell immediately. If standard/error output is supposed to be silenced, this would be:

code . &> /dev/null &

Probably depends a bit on which camp you're in, personally I prefer applications that are started from a shell to stay in foreground (e.g. killable by ctrl+c on the shell afterwards), unless I specify otherwise using the commands described above.

**Comment by lucianFXD** [comment]
@bpasero Yes  this is the issue .I cannot type other commands in the terminal.

**Comment by bpasero** [comment]
Closing, code . & works.

**Comment by jokeyrhyme** [comment]
> Closing, code . & works.

A problem with this is the `code` process is killed when the shell terminates.

**Comment by Tyriar** [comment]
@jokeyrhyme there's now a wrapper script that launches code in a detached process. Debian-based distros will get this in the March release when installed via the .deb package :smiley:

**Comment by joaomoreno** [comment]
:+1:

**Comment by jokeyrhyme** [comment]
@Tyriar awesome! I found the `disown` shell built-in in the meantime. Not hard to make an alias or function for the time being. :D

**Comment by jokeyrhyme** [comment]
@Tyriar also, hi! :D

**Comment by Tyriar** [comment]
@jokeyrhyme :wink:

**Comment by jokeyrhyme** [comment]
In case anyone else was wondering, here's how I tailored the OS X instructions to work with my Linux setup:

```
if [ -x /opt/VSCode-linux-x64/code ]; then
  function code () { VSCODE_CWD="$PWD" /opt/VSCode-linux-x64/code "$@" & disown; }
fi
```

**Comment by jbeaudoin11** [comment]
This is weird, maybe i've done something wrong but when i launch `code` on my laptop it does launch as a detached process but on my other pc it doesn't and i can't use the terminal...

how can i change it so it creates a detached process ?
