### ISSUE TITLE
refs counter for each overloads [feature]

### ISSUE THREAD

**Issue by djmisterjon** [microsoft/vscode#173395]
Sup, can we have refs counter and filter for each overloads ?  ((per signature))
thanks

---

current:
![image](https://user-images.githubusercontent.com/24865815/216741244-e5b14721-19a1-41c2-86f2-a3374b837b87.png)

expected:
![image](https://user-images.githubusercontent.com/24865815/216741300-799f24a0-2e34-4fdf-901e-6a13ee2af3e7.png)

**Comment by mjbvz** [comment]
This feature is powered by the TypeScript project. Please [file a feature request upstream](https://github.com/microsoft/TypeScript/issues/new?template=Feature_request.md)

But note, this also applies to `find all references` and you likely can't do this safely because functions can be passed as objects
