### ISSUE TITLE
Suggestions box's first choice is sometimes selected, sometimes NOT

### ISSUE THREAD

**Issue by iuliust** [microsoft/vscode#173387]
Type: <b>Bug</b>

Since last update, auto-completion is completely broken.

As I type a few characters, the suggestions box appears, but more ofter than not (and contrary to expectation), none of the box's proposals is selected : I have to press the down arrow to select the 1st line!

Consequence:
if I don't pay attention to whether the first choice is pre-selected, I hit ENTER if the first result looks like it's what I want to insert, but since nothing was actually selected, this creates a new line instead... This is probably a bug because this is a terrible UX.

Aside from that, thank you so much for your hard work, VS Code is such a outstanding product!

VS Code version: Code 1.75.0 (e2816fe719a4026ffa1ee0189dc89bdfdbafb164, 2023-02-01T15:23:45.584Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.64GB (5.05GB free)|
|Process Argv|--crash-reporter-id 7dc5599a-5121-4310-803e-9045cdb3905e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
codesnap|adp|1.3.4
ng-template|Ang|15.1.0
markdown-mermaid|bie|1.17.4
npm-intellisense|chr|1.4.4
vscode-markdownlint|Dav|0.49.0
vscode-eslint|dba|2.2.6
gitlens|eam|13.2.0
EditorConfig|Edi|0.16.4
vscode-test-explorer|hbe|2.21.1
angular2-switcher|inf|0.4.0
karma-test-explorer|luc|0.8.1
dotenv|mik|1.0.1
vscode-docker|ms-|1.23.3
vscode-language-pack-fr|MS-|1.75.2023020109
remote-containers|ms-|0.275.0
remote-wsl|ms-|0.75.1
test-adapter-converter|ms-|0.1.6
vsliveshare|ms-|1.0.5828
material-icon-theme|PKi|4.23.1
vscode-npm-scripts|tra|0.2.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1cf:30587006
2e4cg342:30602488
pyind779:30657576
f6dab269:30613381
pythonsymbol12:30657548
vscsb:30628654

```

</details>

**Comment by KunalTanwar** [comment]
Same Issue!!

Before 1.75.0 it autofocuses on the suggestions we just need to use Arrow keys for the desired one but now it is not auto focusing and if we press any Arrow key the cursor just shifts to the above or below line hiding the dropdown suggestions.

**Comment by ArturoDent** [comment]
Check this new setting:

```plaintext
Editor > Suggest: Selection Mode
```

Is that set to `always`?

**Comment by KunalTanwar** [comment]
Yes it is set to `always`

**Comment by dalbitresb12** [comment]
Related #173343.

I've also checked that option and it is also `always`, but the first choice is still not always selected.

**Comment by jrieken** [comment]
Does this occur when invoking a completion when just having accepted one, esp. a snippet completion? Do you have the `editor.suggest.snippetsPreventQuickSuggestions` setting configured?

**Comment by KunalTanwar** [comment]
> Does this occur when invoking a completion when just having accepted one, esp. a snippet completion? Do you have the `editor.suggest.snippetsPreventQuickSuggestions` setting configured?

Yes it is set to `true` but still same problem sometimes working sometimes not!

**Comment by dalbitresb12** [comment]
I think the real problem here is that the suggestion box is showing up when using snippets with `editor.suggest.snippetsPreventQuickSuggestions` set to `true` (which is the default). It should only show up when it is set to `false`.

I've done some testing using Windows Sandbox with versions 1.74.3 and 1.75.0. With `"editor.suggest.snippetsPreventQuickSuggestions": false`, the first option is selected in both versions. With `"editor.suggest.snippetsPreventQuickSuggestions": true` (or unset), in 1.74.3 the box doesn't show while in 1.75.0 it shows up with the first option **not** selected.

You can see both behaviors in the following videos:

<details>
<summary>1.74.3</summary>

https://user-images.githubusercontent.com/7624090/217130517-fd54477f-f72a-40fc-9ac9-9a86ccecdd08.mp4

</details>

<details>
<summary>1.75.0</summary>

https://user-images.githubusercontent.com/7624090/217130552-e16884d4-3cf8-4de0-8786-0bc3ea4b2fb8.mp4

</details>

**Comment by jrieken** [comment]
> in 1.74.3 the box doesn't show while in 1.75.0 it shows up with the first option not selected.

That change was done on purpose but it wasn't clearly communicated. In the past we would truly suppress Intellisense when in snippet mode. Over the last years this has caused much confusion and heated debates because people believe IntelliSense is broken. The underlying conflict is that both (snippets and suggest) use `Tab` to either advance to next placeholder or accept a completion. They are mutually exclusive and one is given precedence making folks believe things are broken. 

Since IntelliSense has the new "no select" mode I figured it is a good compromise to use that instead of suppressing suggest. Wrt muscle memory nothing should have changed, pressing `Tab` still goes to the next snippet placeholder but wrt the UI are now seeing the suggest widget (as ambient offering)

**Comment by waynebloss** [comment]
I am not sure what the correct workaround should be, but I think that things started working again when I set `snippetsPreventQuickSuggestions` to `false`.

I searched around for a "no select" Intellisense setting but I couldn't find one. (Is this a reference to `editor.suggest.selectionMode` and setting it to `never`?)

Basically, I guess I just want it to work the way that it always had worked: Whether I'm using a snippet or not, when I see the autocomplete/intellisense popup list the first item should always be highlighted and when I press `Tab`, it completes the selected item and moves to the next snippet placeholder if in snippet mode...

Thanks!

**Comment by fabioz** [comment]
Is there any way to revert to the previous mode since it was done "on purpose"?

Personally, I find the new way extremely annoying (and given that it always was this way, I think it should default to the way it always was and an option could turn on the new option which doesn't select completions even though they're being shown).

**Comment by fabioz** [comment]
As a note, it seems that setting `"editor.suggest.snippetsPreventQuickSuggestions": false` does improve it for me (at least when a completion is shown it can be applied).

But now I'm confused... when `"editor.suggest.snippetsPreventQuickSuggestions": true`, the completions are actually being shown but without marking a completion item as the selected item (so, it doesn't prevent quick suggestions, it makes it so that it shows it but requires the user to use `Ctrl+Space` again to focus it, which is not good IMHO -- definitely not good as a default, and that seems to be the bug here... in 1.74.3 the completions wouldn't be shown in that case, so, there was no confusion, the new way of handling  `"editor.suggest.snippetsPreventQuickSuggestions": true` to show completions but not select it is very confusing).

Maybe it'd be better if it'd be controlled by something as:

``"editor.suggest.onSnippetMode": "showCompletionsButDontSelect"`` (current behavior -- seems strange to me... maybe it could be there but not default)
``"editor.suggest.onSnippetMode": "dontShowCompletions"`` (old behavior -- maybe not ideal, as users think completions don't work but is reasonable for those preferring placeholders over completions?)
``"editor.suggest.onSnippetMode": "showCompletionsAndApplyOnTabAndEnter"`` (old behavior when `"editor.suggest.snippetsPreventQuickSuggestions": false` was active -- it can backfire because pressing tab wouldn't go to the next snippet and would apply the completion, but maybe that'd be a better default as there wouldn't be a confusion that code-completion isn't working).
``"editor.suggest.onSnippetMode": "showCompletionsAndApplyOnEnter"`` (I guess that'd be the ideal setting for me -- as I use enter to apply completions and not tab, but for users using tab to apply completions I don't really see a way out anyways as the conflict is there by design).

I understand there's a conflict that needs to be solved where `tab` can be used both to apply a completion and go to the next placeholder and that maybe a setting can help there, but showing a completion and not letting it be applied makes it confusing IMHO and shouldn't be the default.

**Comment by KunalTanwar** [comment]
I updated the vscode and I think it is fixed now!! in `v.1.75.1`

**Comment by fabioz** [comment]
@jrieken note that there is no conflict when a user uses tab to go to the next placeholder and enter to apply a completion (so, if the completions are there I'd definitely expect enter to apply it and tab to go to the next placeholder...).

**Comment by daguitosama** [comment]
> editor.suggest.snippetsPreventQuickSuggestions : false

This setting fixed the issue for me, big thanks. 
At this point I think is pretty hard to not press Enter when the suggestion widget shows up. That Enter almost press itself.

**Comment by jrieken** [comment]
I was OOF and this slipped a little bit. For February I will push a new command `focusAndAcceptSuggestion` that focuses and accepts a suggestion (https://github.com/microsoft/vscode/pull/174856). By default it will _not_ have a keybinding but you can add one like this (keybindings.json)

```json
// Place your key bindings in this file to override the defaults
[
    {
        "command": "focusAndAcceptSuggestion",
        "when": "editorTextFocus && suggestWidgetVisible && !suggestWidgetHasFocusedSuggestion",
        "key": "Enter"
    }
]
```

**Comment by michaeldaw** [comment]
@jrieken Thank you for updating this. Could you please provide some additional info on what this new command will do? How did the suggestion system work before this command? The issue described here has only been happening for the last few weeks.

**Comment by jrieken** [comment]
@michaeldaw See https://github.com/microsoft/vscode/issues/173387#issuecomment-1420405130

**Comment by waynebloss** [comment]
Just curious if there's any ETA on this - the best thing about VS Code (great intellisense experience) has been broken for me. Here's what I'm experiencing now whenever I try to import a package.

As you can see, when I press TAB to try and complete the package name and jump to the next snippet spot - it doesn't complete the package name.

https://user-images.githubusercontent.com/623736/224780749-a9d4acbb-65ef-4cc7-9bca-2b4f7e07d92d.mp4

**Comment by waynebloss** [comment]
OK, setting `"editor.suggest.snippetsPreventQuickSuggestions": false,` fixed it for me. I thought I had already had that set but it was actually only being applied to the `"[Dart]"` section.

**Comment by typehorror** [comment]
This change really broke the user experience, I love VSCode but every few minutes I face that bug as I'm trying to use autocomplete instinctively and an empty line appear or no completion happen (I honestly don't know if I should use the down arrow, tab or enter). It made the whole autocomplete very unpredictable and therefore a impossible to use without having to think about it. I find myself more and more often resorting to typing the whole word as it's faster than undoing the result of autocomplete. I don't want to romanticize coding too much but **typing code is an action that happens in a state of flow, and this simply breaks it**

**Comment by jespertheend** [comment]
I haven't had any issues ever since I set `editor.suggest.snippetsPreventQuickSuggestions` to `false`. But I'm not sure why this isn't the default.

**Comment by ramtinabadi** [comment]
> I haven't had any issues ever since I set `editor.suggest.snippetsPreventQuickSuggestions` to `false`. But I'm not sure why this isn't the default.

The problem with setting that to `false` is that you cannot use `tab` anymore.

The idea is that in the snippet mode, you would be able to select the suggestions with `enter` AND jump to the next placeholder by pressing `enter`. The Golang extension provides this correct behavior. But when I switch to TS or Rust or python (python has actually getting really bad), the illogical behavior really bothers me and haven't been able to get used to it.

I believe it was the behavior until it was changed in 1.74 or 1.75.

**Comment by thernstig** [comment]
I am not sure the answers in here sufficiently capture the problem that the original author describes.

Replies seem to suggest that `editor.suggest.snippetsPreventQuickSuggestions` is the culprit. But what I am seeing, and I would guess from reading the original post, is that it is intermittent.

E.g. I just tried typing this:

![image](https://user-images.githubusercontent.com/30827238/235701744-9e3c90cf-d913-4f12-8ad8-6f3c904489f4.png)

Notice how `parsedModels` is not selected.

I then press backspace to remove the `p`. Then the first option gets selected:

![image](https://user-images.githubusercontent.com/30827238/235702014-29ec6137-ec97-4b9b-b525-141526a1f68a.png)

Is this not a bug?

**Comment by jrieken** [comment]
Next 1.79-insiders will contain a fix/change for this. 

I have removed the `editor.suggest.snippetsPreventQuickSuggestions ` setting and I have removed the "open suggest but not focus it" behaviour. Instead keybindings are contextual, e.g <kbd>Tab</kbd> will NOT accept a completion when in snippet mode but <kbd>Enter</kbd> needs to be used. 

Again, this will be 1.79-insiders first (http://code.visualstudio.com/insiders/), not in next 1.78-stable that we are shipping today

**Comment by kodmanyagha** [comment]
When you make stable release?

**Comment by jrieken** [comment]
> When you make stable release?

This will ship early June

**Comment by michaeldaw** [comment]
In 1.79-insiders, this problem still occurs. 

If 'snippet mode' means being in the middle of filling out a snippet, then this still happens when not in snippet mode. 

Occasionally (frustratingly, not always), the completion window is not focused when it pops up and so pressing tab inserts an indent instead of selecting the first item in the completion list. If I then delete a few characters and try again, then this second time the first item in the completion list will then be selected and pressing tab inserts the completion as expected.

**Comment by michaeldaw** [comment]
This is what is happening for me in 1.79-insiders:

https://github.com/microsoft/vscode/assets/8949148/005a0738-c255-4ca0-a5a5-6c759856a33d

**Comment by michaeldaw** [comment]
I just read this comment in #183411
<img width="539" alt="image" src="https://github.com/microsoft/vscode/assets/8949148/269f9ffc-c09f-4170-8d04-761b6f6ffb7d">

Frankly, I find that remark inflammatory.

I've been using various IDE's for nearly 20 years. You can always use TAB to confirm a completion suggestion. Always. Whatever the original intent of this change was, it is an unmitigated failure. Restore the original functionality.

**Comment by rami3l** [comment]
As someone from the "Team Tab" I second @michaeldaw's comment.

As a matter of fact, `editor.suggest.snippetsPreventQuickSuggestions` being true by default has already caused confusion for people like me and I have been using VSCode with this value set to false since I'm aware of this option exactly in order to use Tab completions in snippets.

Personally I don't mind jumping to another completion point using other shortcuts.
Better yet, maybe the hot key for jumping to the next completion point should be customizable... I wonder if this will be difficult to change.

**Comment by jrieken** [comment]
To verify

* ensure the `snippetsPreventQuickSuggestions` setting is back and its default is `false`
* ensure typing inside a placeholder of a snippet shows suggestions, ensure `TAB` accepts it
* ensure `ESC` dismisses suggestion and that snippet mode stays on (until hitting `ESC` again)

**Comment by hediet** [comment]
> turn snippetsPreventQuickSuggestions to true and ensure typing in a snippet placeholder doesn't trigger quick suggestions

Does not work for me:

![Code_-_Insiders_XGunqwfNfA](https://github.com/microsoft/vscode/assets/2931520/b5465fdb-f125-40e2-8e20-983b58867a62)
