### ISSUE TITLE
Add setting to limit quick open results to current opened folder

### ISSUE THREAD

**Issue by pharmmd-rich** [Microsoft/vscode#17330]
Right now, quick open (Command/Ctrl P) searches outside the currently opened folder for files.  Due to the number and size of the projects I work on, QuickOpen often finds files outside the current folder I'm working in.  It would be nice to have a setting to limit quick open to the currently open folder.

**Comment by kieferrm** [comment]
@pharmmd-rich What do you refer to as 'currently open folder'? I'm guessing is the folder containing the file that is selected in the file explorer.

**Comment by pharmmd-rich** [comment]
Yes, the explorer pane within VS Code.

**Comment by bpasero** [comment]
@pharmmd-rich quick open will not search outside the currently opened folder however it may include files that are opened as tabs which are from outside the folder. Could that happen for you here?

**Comment by pharmmd-rich** [comment]
@bpasero yes, sorry, I meant to follow up on this earlier, but it's quite busy for us right now.  It is the recently opened files, is there any way to turn this off?

**Comment by BillDenton** [comment]
I think I'm seeing the same problem. I have the same code base in different folders (for different development branches). Sometimes when I attempt to open a file using quick open Ctrl-P <filename> it will pick a the file from a different folder. I think this is because I have recently opened that file in a different folder. It needs to be restricted to the current folder. It would be good if the recently opened files could be stored per folder. I'm often working across multiple folders, so switching between them as I work. It necessary to keep these folders separate so I don't accidently edit a file on a different branch.

**Comment by chrmarti** [comment]
A workaround could be to `Clear Editor History` (to remove all files) or `Remove From History` (to remove individual files).

**Comment by BillDenton** [comment]
True, that would be a workaround, but I won't remember to do that.

**Comment by pharmmd-rich** [comment]
The recently opened files is definitely an issue.  I believe that quickly opening recently opened files should probably be a different keyboard shortcut, or at the very least have an option to disable it.  However, this made me realize that there is a bigger issue with quick open.  The sorting should sort by folder.  For example, let's say you have the following folder structure:

```
parent/
  project1/
    folder1/
    folder2/
    file1/
  project2/
    folder1/
    folder2/
```

if you are currently editing a file in project2/folder2, quick open should prioritize the listing of files in project2/folder2 as well as project2/ over the listing of files in project1/folder1.  Right now it does not appear to do that.  This results in irrelevant files being displayed.  For example, I have 11 different projects listed in the explorer window right now, if i do a search for a filename that is present in all of them, the correct file is **not even listed** without scrolling down.
