### ISSUE TITLE
Code disappear while using python notebooks

### ISSUE THREAD

**Issue by prpretzel** [microsoft/vscode#173300]
Type: <b>Bug</b>

I noticed that the issue appears when I scroll my notebook. When it happens a few code blocks turn out empty. Only collaps/decollaps helps the code become visible

VS Code version: Code 1.75.0 (e2816fe719a4026ffa1ee0189dc89bdfdbafb164, 2023-02-01T15:23:45.584Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7Y75 CPU @ 1.30GHz (4 x 1608)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.88GB (1.33GB free)|
|Process Argv|--crash-reporter-id 2d69ae77-a670-4bbf-99a5-4299c1cf9727|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
isort|ms-|2022.8.0
python|ms-|2023.2.0
vscode-pylance|ms-|2023.2.10
jupyter|ms-|2023.1.2000312134
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.14
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
sqlite-viewer|qwt|0.1.5
LiveServer|rit|5.7.9

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848cf:30577861
nodejswelcome1:30587005
2e4cg342:30602488
pyind779:30657576
89544117:30613380
pythonsymbol12cf:30657549
a9j8j154:30646983
vscsbc:30628655

```

</details>

**Comment by HarshDubey1011** [comment]
**Have you tried opening new notebook tried the code and again facing same difficulty?**

**Comment by glasvase** [comment]
experiencing exactly the same on macos 13.2 @ Apple Silicon.

**Comment by prpretzel** [comment]
> **Have you tried opening new notebook tried the code and again facing same difficulty?**

Yes, I`ve tried to open/close notebook, open/close VS Code, I`ve reinstall VS Code, but the issue is still here
I also noticed, that this trouble appears when I scroll too fast. If I scroll calmly everything is ok

**Comment by rebornix** [comment]
@prpretzel thanks for reporting, it would be very helpful if you can share a screen recording of what you are seeing. We did hide the suggest widget when scrolling widget to avoid it being wrongly positioned, but we might be doing that too eagerly.

**Comment by prpretzel** [comment]
> @prpretzel thanks for reporting, it would be very helpful if you can share a screen recording of what you are seeing. We did hide the suggest widget when scrolling widget to avoid it being wrongly positioned, but we might be doing that too eagerly.

Hi! 
Yes, here it is:
https://user-images.githubusercontent.com/42389955/216760145-bf820dd4-3141-453e-a86e-6cef9fd51885.mp4

In the beginning of the recording you can see, that everything is ok, but when I collapse one the cell and continue scrolling starts to disappear

**Comment by ShantanuKodgirwar** [comment]
Facing the same issue on Ubuntu 22.04. I may have to revert back to the previous vscode version as nothing (reinstalling/reopening app) helps.

**Comment by TheProjectsGuy** [comment]
![image](https://user-images.githubusercontent.com/29420733/216803683-8dbd604c-16bb-4071-8d53-d2266763ad63.png)
@forestGoroli 
The issue seems to be happening with both the releases of the VSCode Jupyter extension. I have tried the vscode-jupyter versions `v2023.1.2000312134` (latest stable) and `v2022.11.1003412109` (older). The older version worked with the previous release (before the VSCode update).

**Comment by TheProjectsGuy** [comment]
I may have found a temporary workaround: Downgrade the VSCode installation. I tried this on Debian and had to install the _then working_ versions of python, jupyter extensions. I will upgrade and patch this when this issue is closed.
**Risk**: This could cause some extensions to break. Please do this at your own risk.

Here's what I did:
1. Use the apt-history command from [here](https://unix.stackexchange.com/a/236711/456203). Since I had updated recently, the older version ID was there in my `/var/log/dpkg.log`. My older release was `code:amd64=1.74.3-1673284829`
2. Install it using `sudo apt install code:amd64=1.74.3-1673284829`
3. After loading VSCode, the remote server had to be downloaded again (I use VSCode over remote SSH). Jupyter and python extensions had to be downgraded. Several extensions switched to their "pre-release" versions.

Assuming this gets fixed, here's what I plan to do
1. Install the latest code version using `sudo apt install --only-upgrade code`
2. Comb through the installed extensions and install the latest stable version of them.
3. VSCode will re-download the remote server

After using it for a while, I can say that the following is working
VSCode version: `code:amd64=1.74.3-1673284829`
Python version: `v2022.20.2`
Jupyter version: `v2022.11.1003412109`

This, kind of, made my workflow a little unstable (I use VSCode as my main editor and sync everything). I hope this gets fixed soon

**Comment by TheProjectsGuy** [comment]
@prpretzel My issue is with the interactive python feature in VSCode.
If you (or anybody else) can risk it, could you downgrade and see if it works? I haven't experienced it since downgrading.

**Comment by NZambranoc** [comment]
Experiencing the same issue as well.

Jupyter version: v2023.1.2000312134
VSCode: 1.75.0 x64

**Comment by ShantanuKodgirwar** [comment]
@TheProjectsGuy I did try to downgrade it. But yeah as you mentioned, it opens up a new can of worms, where you need to also downgrade extensions and honestly it was just easier to switch to the ordinary jupyter notebook till the issue is resolved. But yes, this certainly is a workflow disrupting issue and I hope it gets fixed asap. 

It's probably also possible to manually change some configs for the vscode jupyter-notebook extension, but yes, if @rebornix  could point to such a workaround till this is fixed, I'd also be content with it.

**Comment by ZupoLlask** [comment]
This issue is important... I need to be collapsing and expanding (Jupyter) cells all the time, to be able to see the code.

**Comment by TheProjectsGuy** [comment]
Maybe some fix is coming: https://github.com/microsoft/vscode-jupyter/issues/12732#issuecomment-1418553775

**Comment by rebornix** [comment]
This shares the same root cause as https://github.com/microsoft/vscode/issues/173590. Let's track it there. Thank you all for the reports.
