### ISSUE TITLE
Status bar is hidden in Zen mode, made VIM extension unusable

### ISSUE THREAD

**Issue by leira** [Microsoft/vscode#17348]
I'm using [vscodevim.vim extension](https://marketplace.visualstudio.com/items?itemName=vscodevim.vim), which need status bar to indicate current mode, and input search terms.

I like the idea of Zen mode in 1.8, but it hides the status bar, and there is no way to get it back, which pretty much make VIM extension usable. Please add an option to keep status bar in Zen mode.

**Comment by mAlvarado1986** [comment]
Alternately you can switch to Full Screen Mode (F11), Hide Activity Bar and toggle menu bar, letting visible the status bar

**Comment by leira** [comment]
@mAlvarado1986 yes, this is exactly what I am doing right now.

**Comment by bpasero** [comment]
Looks like another setting is needed :-|

**Comment by isidorn** [comment]
Currently there is `window.fullScreenZenMode`
We can add an additional setting `window.statusBarInZenMode`
Which is a bit ugly since we already have `workbench.statusBar.visible`, thus they have different prefixes.

I think optimally we would have the following settings
`workbench.zenMode.fullScreen` default true
`workbench.zenMode.statusBar`  default false

I think depricating the old full screen setting is not a big deal since it is not widely used imho

**Comment by bpasero** [comment]
Yes, +1 for aligning the settings. Another idea I had was to somehow allow an extension to control the Zen mode or come up with a more configurable Zen mode. We will soon add support to hide tabs when entering Zen mode and thus we have quite a bit of things going on:
* fullscreen: yes/no
* status bar: visible/hidden
* activity bar: visible/hidden
* panel: visible/hidden
* side bar: visible/hidden
* tabs: visible/hidden

Introducing settings for each is a bit overkill. If each of the things that Zen mode potentially toggles would be commands, there could be a "Zen on Steroids" extension that basically could allow the user to configure what happens when entering "Zen on Steroids".

**Comment by isidorn** [comment]
Please install this extension https://marketplace.visualstudio.com/items?itemName=isidor.power-zen-mode

And use it to configure behavior of zen mode

**Comment by isidorn** [comment]
After discussion we have decided to support the following settings in the vscode core product
`zenMode.fullScreen`
`zenMode.hideTabs`
`zenMode.hideStatusBar`

So for this issue simply put - it will be avilalbe in tomorrow's insiders build
`"zenMode.hideStatusBar": false`

Due to that we have removed the extension from the marketplace.
