### ISSUE TITLE
Intellisense filters

### ISSUE THREAD

**Issue by svenvNL** [Microsoft/vscode#17344]
- VSCode Version: 1.8.0
- OS Version: Windows 10 home 

Steps to Reproduce:

1. create or edit an css file
2. inside an selector, type wid and hit tab
3. widows will be inserted

I never use widows. It annoys me its in intellisense.
I just want width inserted. 
I suggest to add an filter option which can exclude items from intellisense like files can be excluded.

My format suggestion:
```json
css.intellisenseExclude [
  "widows"
]
```

for html it would be something like
```json
html.intellisenseExclude [
  "font",
  "header[force-refresh-image]",
  "*[force-refresh-image]"
]
```

related: #12986

**Comment by crabicode** [comment]
#17419

**Comment by aeschli** [comment]
Hm, widows is an interesting example. Code completion actually selects width and `enter` will complete to width. What's happening is that the tab key invokes emmet, which expands `wid` to `widows`
![image](https://cloud.githubusercontent.com/assets/6461412/21574871/99d1e94a-ced1-11e6-8137-5264e99767fd.png)

If you never use emmet you could disable emmet completion with the option
  `"emmet.triggerExpansionOnTab": false`

If you want tab to always select the completion item when the suggestion window is open, add this to your keybindings:
```json
{ "key": "tab",                   "command": "editor.emmet.action.expandAbbreviation",
                                     "when": "config.emmet.triggerExpansionOnTab && editorTextFocus && !editorHasMultipleSelections && !editorHasSelection && !editorReadonly && !editorTabMovesFocus && !suggestWidgetVisible" }
```

@egamma @ramya-rao-a  Is it intentional that emmet is triggered even when the suggestion window is open?

@svenvNL Is your request still to allow filtering intellisense proposals, or is it more about the 'widows' case?

**Comment by ramya-rao-a** [comment]
As far as I know when emmet expansion is triggered by TAB, it is not aware of the suggestion window's existence at all.

Including @mrmlnc for emmet history

**Comment by svenvNL** [comment]
@aeschli 
My request is still about intellisense filters.
I switch a lot between emmet and standard intellisense.
I always thought that intellisense and emmet use the same autocomplete, thats why only intellisense is mentioned in the issue title.

with filters I want to remove things from intellisense and emmet.
A lot of times I type 'pad' and hit enter or tab and intellisense or emmet complete to 'pad: '.
I expected 'padding: ' and not 'pad: '. I never use pad so I rather remove it from css intellisense / emmet.
The same goes for widows, 
typing 'width: c' I would like to have intellisense and emmet to complete to calc, not 0ch. I rather have nothing then completion that inserts something like 0ch. 0cm, etc.

on html elements like div, I never use the title attribute.. I rather have completion to tab-index then title.

**Comment by ramya-rao-a** [comment]
@svenvNL @aeschli I am able to repro the `pad` example but not the `wid`
Inside a selector hitting tab after `pad` gives me `pad: ` and hitting tab after `wid` gives me `width: `, both being the result of autocomplete and not emmet.

I believe emmet only gets triggered by tab if there are no suggestions by autocomplete.

**Comment by giyyapan** [comment]
My vscode also suggest `widows` as first candidate instead of `width` when type `wid` and I get a typo almost every time :(
I'm using vscode 1.10.2 on ubuntu 16.04LTS

**Comment by CharlesGouldmann** [comment]
I also have vscode suggesting `widows` instead of `width` as the first option when writing `wid`. I can see why this would be the first option when sorting alphabetically, but it does not make a lot of sense in regards to which is used more often.

Is there really no way to change this behaviour?

![screen shot 2017-09-15 at 10 50 23](https://user-images.githubusercontent.com/5164493/30474359-b76fed6e-9a03-11e7-8034-4de760500701.png)

**Comment by aeschli** [comment]
I think such a filter should be provided across languages e.g. with a language specific setting.

**Comment by jrieken** [comment]
In latest insiders and with the 1.19 release we will remember the last select suggestion and pre-select that. This is per workspace and language, so once `width` has been selected for for `wid` it will be the default selection for the future. Closing this as duplicate
