### ISSUE TITLE
Bridging the connectivity between the mind, code, and settings/manifest files via IDE intelligence

### ISSUE THREAD

**Issue by nav9** [microsoft/vscode#173418]
**Reference:** [This question on StackOverflow](https://stackoverflow.com/questions/75309580/ide-or-extension-that-provides-complete-connectivity-for-webapp-code-and-manifes).  
Whether it's Spring MVC or Django, Kubernetes, Docker or even VS Code's JSON files, it's currently a pain to have to remember where to find settings, manifest files and be very careful to avoid typos. **We need the IDE to be more intelligent in not requiring us to remember a whole lot of things about how to use the IDE** and also to make it easier to find our way through large architectures.  
In a purely class or function oriented program, you can just right click on a function and find references. But in Django, you can't simply do a right-click and figure out from which part of `urls.py` a function is being invoked from. **There's this huge gap in connectivity between code and settings/manifest files that needs to be bridged**.

**Comment by lszomoru** [comment]
> In a purely class or function oriented program, you can just right click on a function and find references. But in Django, you can't simply do a right-click and figure out from which part of urls.py a function is being invoked from. There's this huge gap in connectivity between code and settings/manifest files that needs to be bridged.

@brettcannon, could you please triage this issue? Thank you!

**Comment by brettcannon** [comment]
This would be something for a Django extension to provide, and even then I don't think it could be provided in a manner that's 100% consistent since Django configuration comes via code and not a static configuration file. That means users can do anything they want to generate details which may not be easy to analyze to make the connection back.

Regardless, such a feature would be a feature request for https://github.com/microsoft/pylance-release  (and thus I'm closing this).
