### ISSUE TITLE
Improve Quick Open View experience from Command Palette

### ISSUE THREAD

**Issue by wallverb** [Microsoft/vscode#17350]
- VSCode Version: Code - Insiders 1.9.0-insider (89bdb7c35a89535612d386199ee33e6bd74ee068, 2016-12-15T07:05:19.776Z)
- OS Version: Darwin x64 16.3.0

---

Steps to Reproduce:

1. Open Command Palette `Cmd+Shift+P`
2. Type `Quick Open View`
3. Hit Enter to select
4. Window is seen for a fraction of second and closes

Maybe if it's run form command palette it should stay open until selection / Esc

**Comment by bpasero** [comment]
The command "Quick Open View" can actually not really be run from the command palette because it opens a quick open picker that closes right after. The same is true for our "quick navigate" command. These pickers are only meant to be interacted with using the keyboard.

Please instead just type "view " into the picker.
