### ISSUE TITLE
[macOS] updating never works, loops forever

### ISSUE THREAD

**Issue by shiftkey** [Microsoft/vscode#17368]
- VSCode Version: 1.8.0-insider 2abfc207828739bd5b10d0bb8dbfea13506cfc69 (also reproducible on stable, but easier to trigger here due to nightly updates)
- OS Version: Mac OS 10.12.2

Steps to Reproduce:

1. Extract the given build from code.visualstudio.com, move it into Applications
2. Launch the app, wait a bit
3. When VS prompts you that an update is available, "Update Now"

![](https://cloud.githubusercontent.com/assets/359239/21250177/6e8e54d4-c397-11e6-8d23-7674bb98a152.png)

4. The application closes, and never re-launches.

Launching the app manually has it at the original version.

Apologies for the lack of details, if there's specific log files I can give you around the update process let me know where to look.

**Comment by Vishal-Isharani** [comment]
i also have this problem after updating to 1.8.0-insiders

**Comment by bpasero** [comment]
The dialog popping up is an indication that you have the application installed in another directory. This can happen easily if you have the same version laying around in the downloads folder as well as the applications folder. 

Does this reproduce if you 
* remove all versions of Code first
* download 1.7 to the applications folder
* start and get the update

?

**Comment by shiftkey** [comment]
> The dialog popping up is an indication that you have the application installed in another directory. 

I'm not worried about the dialog appearing. I'll update the repro steps to indicate this isn't important, as the prompt occurs only after I'd extracted it to `~/Desktop`, rather than moving it into Applications.

> download 1.7 to the applications folder

I was on 1.7.x before I first saw this happening, but I couldn't find an installer for those versions to switch back to. Does someone have a link?

**Comment by bpasero** [comment]
here you go (VS Code 1.7): https://az764295.vo.msecnd.net/stable/7ba55c5860b152d999dda59393ca3ebeb1b5c85f/VSCode-darwin-stable.zip

**Comment by shiftkey** [comment]
@bpasero installing 1.7.2 (38746938a4ab94f2f57d9e1309c51fd6fb37553d) and then updating it successfully relaunched the app as 1.8.0 (38746938a4ab94f2f57d9e1309c51fd6fb37553d). This worked twice for me.

Removing it and then installing 1.8.0-insider again (2abfc207828739bd5b10d0bb8dbfea13506cfc69) was updating unsuccessfully. Tested twice to confirm it wasn't a fluke...

**Comment by joaomoreno** [comment]
What dialog was popping up?

**Comment by shiftkey** [comment]
@joaomoreno the dialog asking for your credentials to install a helper as part of updating - this will show depending on where you launch the app from, and isn't important to the issue (I think)

**Comment by bpasero** [comment]
@shiftkey did the dialog pop up when it was NOT working?

**Comment by shiftkey** [comment]
@bpasero moving it under Applications (whether stable or insiders) before launching would not display the dialog - and didn't seem to affect whether the update applied succesfully

**Comment by Vishal-Isharani** [comment]
@bpasero can i get insiders 1.7.0 link ?  cus i'm using insider's

**Comment by bpasero** [comment]
For insiders since we update nightly, any older build is OK to try, e.g. from 1 week ago: https://az764295.vo.msecnd.net/insider/46e96d6d73bcf731c9907955e89c9a154f7a9050/VSCode-darwin-insider.zip

@shiftkey thanks, so maybe this is indeed unrelated from where you open the application and update it and might be a red herring.

**Comment by Vishal-Isharani** [comment]
thanks @bpasero  i will try and update you.

**Comment by Vishal-Isharani** [comment]
@bpasero i have downloaded vs code from above link and followed all steps you have mentioned but the issue still persist and also it asks password for setting update helper even i have downloaded it in  /Application and also tried from different dir

**Comment by baslr** [comment]
Problem is maybe that the logged in user is not an administrator but an standard user?
I have VSC.app in my ~/Downloads directory, there updates are working, but on an different mac, VSC.app is in /Applications directory and also loops forever. After every update restart the version did not changed.

**Comment by bpasero** [comment]
@shiftkey @Vishal-Isharani @baslr can you please
* delete any instances of Code you have on your machine in either `Applications` or `Downloads` folder or anywhere else
* run as normal user and **NOT** as administrator (we do not support nor recommend running Code as administrator)
* download [Code 1.7.2 ](https://az764295.vo.msecnd.net/stable/7ba55c5860b152d999dda59393ca3ebeb1b5c85f/VSCode-darwin-stable.zip)
* move it to Applications folder
* run it
* wait for the update notification
* apply the update

=> does it ask for credentials from this dialog?
=> does it restart as 1.8?

**Comment by Vishal-Isharani** [comment]
@bpasero i have clear all instances of code and tried following 

1. when i have downloaded to direct /App.. folder it asks for password
2. when i move from another directory it don't ask password 
  but in both above case after clicking update now nothing happens vscode never  restart.

**Comment by shiftkey** [comment]
@bpasero testing 1.7.2 (the only difference I did was forcing "Check for Updates" rather than waiting):

> does it ask for credentials from this dialog?

No, no prompt for credentials occurring.

> does it restart as 1.8?

Yes, I was running 1.8.0 38746938a4ab94f2f57d9e1309c51fd6fb37553d after the update was applied and VS Code was relaunched.

**Comment by mingsai** [comment]
Hi all,

This sounds similar to a problem I've seen while updating other editors which attempt to do in-line updates (such as atom). Here are the relevant facts that seem to impact the behavior:

I never operate the editor as an admin when creating code. My user account is not the same as that which installs software. For example, when I load a new package the operating system prompts me for an admin credential. However, when running the internal updates, the operating system does not prompt me for an admin credential.

The editor attempts to keep related configuration data in the following user-based subdirectory:
/Users/<username>/Library/Application Support/code

In the case of atom, the permissions on the sub-directory structures where files need to be written were not equivalent to the user active, when the updates are installed AND no system prompt appears. The install appears to succeed but after the editor relaunches, the updates start again (because the appropriate files are not actually being written to disk). In short, it appears that a permissions issue occurs...

If anyone can share the directories impacted by the internal update process then I can check whether the permissions issue is occurring.

**Comment by baslr** [comment]
@bpasero

**Comment by joaomoreno** [comment]
Merging with #7426
