### ISSUE TITLE
Efficient way to switch between profiles

### ISSUE THREAD

**Issue by Ramin-RX7** [microsoft/vscode#173630]
What I have noticed when using profiles is that switching between them takes a bit longer than it should. I don't mean the duration it takes when I click on the profile I want, I mean the part that I should click on `manage`>`Profile`>`otherProfile` manually each time I wanna change the profile. 
Basically what I'm thinking is if there could be a way to set a keyboard shortcut so it will go to next profile would make it better.
Also thought that it would be better if we had the option to have `Profile` button above `accounts` in the side bar

**Comment by asherber** [comment]
Yes, please bring back the Profile button that was in the preview of this feature! Among other things, it made it much easier to see which profile was active. I find that the profile name doesn't stand out for me in the title bar, and if I have the Command Center turned on, it doesn't show up at all.

**Comment by sandy081** [comment]
> Basically what I'm thinking is if there could be a way to set a keyboard shortcut so it will go to next profile would make it better.

I will come up with a command for switching profiles action. I though there is one already, but it doesnot.

For profile icon specific feedback, please comment here - https://github.com/microsoft/vscode/issues/166983

**Comment by mj-spencer** [comment]
@sandy081 
A command to switch would be a huge help. I realize some of this is 'growing pains' of getting profiles attached to all of my existing workspaces, but since most of my frequent workspaces have folder-specific overrides on the window.title (so even if the profile does have that variable enabled, it would be overriden and hidden), and I typically keep the activity bar hidden, the only way for me to check that I'm using the right profile is to toggle into the activity bar visibility, click the settings icon, see the listing next to profiles. This also comes into play when I'm editing the profile settings. While I appreciate the 'Open Current Profile Settings (JSON)' option to distinguish between that and the default profile, I run into the same issue where I need to double check I'm editing the 'right' settings. I've somewhat worked around this by adding a comment at the top of my settings.json with the friendly name of the profile, having an easy way to switch between profiles (and see the actual name of the profile) from the command palate would be very helpful.

I also think being able to see the name of the current profile in the status bar would be more helpful than the titlebar (keeps me having to remove the workspace override on the custom title regardless). (Though this may be better suited to an extension. That said, I cannot seem to find how to get the profile name in the api docs)

**Comment by sandy081** [comment]
@mj-spencer Thanks for the feedback. As requested, please provide your feedback in this issue https://github.com/microsoft/vscode/issues/166983. This issue is meant to discuss how to represent the profile in the activity bar.

Another tip for you here is that you can simply hover on gear icon to see the current profile

<img width="500" alt="image" src="https://user-images.githubusercontent.com/10746682/218035109-2dfdb3ab-6b07-46a2-b69e-b8ffea619486.png">

**Comment by Viijay-Kr** [comment]
@sandy081 with your changes in  https://github.com/microsoft/vscode/pull/174032 can the command be bound to a keyboard shortcut ? 

I guess switching profiles using keyboard shortcut will also make it easier to switch between profiles

**Comment by sandy081** [comment]
Yes, the command `workbench.profiles.actions.switchProfile` can be assigned to a keyboard shortcut. This will open a quick pick in which you can choose the profile.

**Comment by Viijay-Kr** [comment]
Would love it 👍🏽

**Comment by sandy081** [comment]
Verify the command `Profiles: Switch Profile...` command

**Comment by bpasero** [comment]
We maybe should do a pass about how an "active" item in quick pick is indicated. For example the picker for windows does this:

![image](https://user-images.githubusercontent.com/900690/220366112-38ea268d-d8a5-4601-8ead-486eef312c88.png)

Here the profiles picker does this:

![image](https://user-images.githubusercontent.com/900690/220366164-bb78a191-42ce-4a01-9fde-d25ea6e3c4e2.png)

cc @TylerLeonhardt @daviddossett

**Comment by TylerLeonhardt** [comment]
Setting the active item in the quickpick is unfortunately not accessible so that needs to be thought through some more.

**Comment by bpasero** [comment]
I think that should possibly be a concept in quick pick and then some ARIA roles/things set accordingly.

**Comment by AzulaBeKinky** [comment]
> Yes, the command `workbench.profiles.actions.switchProfile` can be assigned to a keyboard shortcut. This will open a quick pick in which you can choose the profile.

Would it be possible to switch to a specific profile like so "workbench.profiles.actions.switchProfile.myProfile"
I love that profiles can save UI states, but not being able to hotkey them directly, so I don't get a popup feels bad and sluggish.
