### ISSUE TITLE
VSCode started to lag wtih CSS in Head

### ISSUE THREAD

**Issue by Sokol-ua** [Microsoft/vscode#17382]
- VSCode Version:  1.8.0
- OS Version: Windows 10

Steps to Reproduce:

1.  Inline compiled css (about 500 lines) from sass into page head
2.  Try to scroll

After updating to 1.8.0 version, it started to lag while scrolling into <head> with css injected in <style> tag.  Currently if css inlined in head, I am unable to scroll top of the .html page.

![vscode](https://cloud.githubusercontent.com/assets/8975621/21257845/dde0f0ae-c382-11e6-84cc-47d7b7bf9ec6.gif)

**Comment by mjbvz** [comment]
I believe you may be running into #17208

Can you please try the latest 1.9 insiders builds and let us know if you still see the issue. Another workaround is `"editor.wrappingColumn": -1`

Thanks

**Comment by seltzer1717** [comment]
I'm still seeing scrolling issues in 1.8.1.  Scrolling is not smooth - screen pauses for a third of a second then tries to catch up.  This is quite annoying.  Happens on all files including the release notes on 1.8.1.

**Comment by alexandrudima** [comment]
@seltzer1717 

### Scrolling with the trackpad is not smooth

VS Code is built on top of Chromium. At this point it is Chromium v53. There are a number of issues that have been already fixed in newer versions of Chromium. We will benefit from these fixes once we adopt a newer version of Electron, which we do quite frequently.

### What you can do

Download Chromium v53 and see if scrolling with the trackpad is smooth when you browse the internet.

Download the latest version of Chromium and see if scrolling with the trackpad is smooth.

If it is not, then consider creating an issue against Chromium.

### Known workarounds

For example, my trackpad (on a Surface Book) works correctly after "restoring" and then maximizing back the VS Code window (Possibly related #13612).

There are no code change we can do on our side to workaround these issues.
