### ISSUE TITLE
Quickpick should reflect when it has additional items 

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#173851]
When a quickpick has more items than can fit into the initial list, it's not obvious there are hidden items that need to be scrolled into view. The current visual treatment is a very subtle scrollbar flash when the quickpick is first opened, but thereafter there is no visual indication that there are more items. 

The current behavior presents issues for the remote indicator menu, which displays actions from all installed remote extensions (connect to host, create new codespace) etc. The remote indicator menu is meant to improve discoverability and ease of access to remote actions, and the current truncation inhibits discoverability of those remote actions.

Proposals: 
1. render a 🔽 arrow button at the bottom of the quickpick when there are items offscreen which will scroll down to the next 'page' of items when clicked
2. always render the scrollbar

**Comment by TylerLeonhardt** [comment]
Looking at prior art here:

### shows scrollbar always:

Slack
![image](https://user-images.githubusercontent.com/2644648/217616747-75c68a0c-7849-42b5-8324-b3459027df13.png)

Spotlight
![image](https://user-images.githubusercontent.com/2644648/217617433-ca999b26-cc1e-414b-9c3c-680d5133b893.png)

GitHub
![image](https://user-images.githubusercontent.com/2644648/217619214-f20ef893-95aa-4bd2-ad5d-7d54faeaf6a3.png)

### Does what we do (nothing):

Teams
![image](https://user-images.githubusercontent.com/2644648/217617128-201943e5-a7e5-4d6e-a402-c3ff788cba41.png)

Alfred
![image](https://user-images.githubusercontent.com/2644648/217617608-2db3bee0-a1ba-4cd5-99ce-73b0dccb1c13.png)

Docker
![image](https://user-images.githubusercontent.com/2644648/217617863-668ba747-7608-45bc-96a3-7a016770ffdd.png)

### Some thoughts

One thing I'm noticing is that some render the height as the middle of an item... which is an indication that there is scroll. Not sure if that is intentional or not, but it would be something that we have control of.

While the 🔽 is a neat idea, I fear that it will be in the way while reading the item it is on top of...

My preference is either render the scroll bar... or maybe do nothing since the "command palette" experience can be seen across many products and most if not all allow scrolling.

**Comment by TylerLeonhardt** [comment]
Oh, I wanted to point out that the scroll bar does flash today:
![Recording 2023-02-08 at 10 31 03](https://user-images.githubusercontent.com/2644648/217620308-c79a8f2c-0216-4ed3-9cac-4b2a2a620e88.gif)

and if your mouse is hovering over the list, the scrollbar sticks around.

This feels like enough of an indication that there's scroll.

**Comment by joyceerhl** [comment]
> While the 🔽 is a neat idea, I fear that it will be in the way while reading the item it is on top of

Instead of rendering it atop an item, what if we rendered it _below_ all the items in the quickpick?

**Comment by TylerLeonhardt** [comment]
Do you not think the flashing scroll bar is enough? The Explorer does this too.

**Comment by joyceerhl** [comment]
I don't think it's enough, particularly for the remote indicator scenario where you're triggering it by clicking the status bar--there will be a brief flash when it's first opened, and if you then use up/down arrows to navigate through the list, you don't see the scrollbar.

**Comment by TylerLeonhardt** [comment]
Is this a hunch or based on user feedback?

I talked to @bpasero a bit about how the fading went when we rolled it out everywhere and there were some issues opened:
https://github.com/microsoft/vscode/issues/66000
https://github.com/microsoft/vscode/issues/15106

not scoped to quickpick but rather holistically.

We have settings to control the behavior but only in the editor I guess:
![image](https://user-images.githubusercontent.com/2644648/217881840-0d8b5612-d853-4560-bd9e-cab34500db6e.png)

in terms of proposal 1 for scrollbar visibility, I feel like the issues I linked are a better holistic way forward.

As for the ⬇️ ... I'm not sold. Either it makes the quick pick taller (just for a little arrow) or it covers up content.... plus I couldn't find a single quick pick example in the wild that takes this approach.

**Comment by joyceerhl** [comment]
I think it's fair to consider a global treatment for scrollable content as you say, the linked proposals look promising.

**Comment by TylerLeonhardt** [comment]
Proposed solution: increase the `max-height` by a little bit so it renders like:
![image](https://user-images.githubusercontent.com/2644648/223197486-0e9f82ca-71d3-40be-91c0-71baf3c742c9.png)

**Comment by TylerLeonhardt** [comment]
steps to verify:
* open the command palette
* it should render in the middle of the item (like my last screenshot) to indicate that it does scroll
