### ISSUE TITLE
Add symbol provider for terminal accessible buffer

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#174079]
Right now, we present only the command, the exit code if non-zero, and the output. 

Some questions:

- is presenting `...exited with code #` useful?
- should we add the `cwd`
- should we include the prompt

cc @jooyoungseo for any thoughts

**Comment by jooyoungseo** [comment]
The recently introduced heading semantics in the accessible terminal buffer does not seem to live up to our expectation because the screen readers' vague support for "document" role landmark. In theory, "document" role would work like a web page and will auto-activate screen readers' virtual cursor (AKA, browse mode). Tagging each command with heading semantics, thus, would make sense. Unfortunately, most major screen readers do not seem to properly support "document" role, which introduces some side effects against heading semantics defined within the document role. For example, NVDA seems to behave like a document mode instead of browse mode against "document" role and it does not properly recognize heading semantics in the terminal buffer unless you explicitly switch to browse mode. JAWS is even worse... I did not have a chance to file a new issue regarding this, but I will demonstrate this when we meet soon.

**Comment by meganrogge** [comment]
Okay thank you for that insight. I wonder if a list structure would be better so this can be navigated with arrow keys?

**Comment by meganrogge** [comment]
explored using `role: presentation` and using the arrow keys to navigate line by line on this branch https://github.com/microsoft/vscode/tree/merogge/role-presentation

because that's what we do for the output view

**Comment by jooyoungseo** [comment]
@meganrogge -- The ideal model that I refered to previously was Ctrl+Shift+U (Tasks Output) and it has a textbox role.

**Comment by meganrogge** [comment]
@Tyriar and I had a look at the output together and noticed that it is a monaco editor. We will see what the overhead is of inserting that in the terminal

**Comment by meganrogge** [comment]
It looks like the monaco editor will work. 

We can use this issue to track also the possibility of adding a language/symbol provider so that landmarks such as commands and output can be navigated to separately. We could also use the editor quick fixes to present our terminal quick fixes in an accessible manner.

**Comment by jooyoungseo** [comment]
@meganrogge Regarding your original questions on symbol provider, I would recommend making the integrated shell outcome as similar as possible to the non-integrated shell results by default. Users may feel confused if they see different styles between enabled and disabled integrated shells.

It would be even more ideal if you could add some settings for users to customize the buffer output by allowing them to toggle on and off for "cwd", "prompt", "command", "non-exit code."

My personal preference would look like the following:

``` json
{
  "display.cwd": false,
  "display.prompt": false,
  "display.command": treu,
  "display.non-exit-code": false
}
```

**Comment by meganrogge** [comment]
Great idea 👍🏼

**Comment by Tyriar** [comment]
I think we should present the entire buffer as is in a monaco instance (like a regular editor) and then use symbols to expose the command smarts if shell integration is enabled:

![A quick pick could open when navigating 'symbols', for example ls at working directory exited with code 1](https://user-images.githubusercontent.com/2193314/221631755-7cbe1e40-0ae1-40ea-bd23-e22d5e967b12.png)

**Comment by meganrogge** [comment]
I investigated and we'd need to use an `EditorPane` and either have our own `OutlineProvider` similar to notebooks or register a terminal language provider. Both seem like overkill and more complicated than what we need.
