### ISSUE TITLE
Keybinding processing doesn't stop after user keybinding

### ISSUE THREAD

**Issue by akbyrd** [microsoft/vscode#174117]
Type: <b>Bug</b>

The [documentation](https://code.visualstudio.com/docs/getstarted/keybindings) explains how bindings are intended to be processed

> When a key is pressed:
> * the rules are evaluated from bottom to top.
> * the first rule that matches, both the key and in terms of when, is accepted.
> * no more rules are processed.
> * if a rule is found and has a command set, the command is executed.

Further, it explicitly states that to disable a binding it's valid to register a user binding with an empty command:
> // To override and disable any `tab` keybinding, for example, add in keybindings.json:
> { "key": "tab", "command": "" }

However, there are cases where this doesn't work. For example, you cannot "unbind" Shift+Tab with this method. If you add a binding for Shift+Tab with an empty command instead of doing nothing Shift+Tab will move focus from the text editor to the breadcrumb bar. This happens even when explicitly removing every built-in binding for Shift+Tab, so it's not another binding executing. The Keyboard Shortcut Troubleshooter indicates the user keybinding is executed.

Steps to Repro:
* Explicitly unbind all built-in bindings for Shift+Tab
* Add this keybinding: `{ "key": "shift+tab", "command": "" },`
* Focus a text editor
* Press Shift+Tab
* Notice focus moves to the breadcrumb bar instead of doing nothing
* Change the keybinding to `{ "key": "shift+tab", "command": "noop" },`
* Focus a text editor
* Press Shift+Tab
* Notice nothing happens and focus does not move

VS Code version: Code - Insiders 1.76.0-insider (c7930ca55d072608625ba76c13b5f9baaf9a2136, 2023-02-10T16:22:19.445Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5950X 16-Core Processor             (32 x 3400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.92GB (20.05GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
pylantcb52:30590116
pyindex848:30611229
nodejswelcome1:30587009
pyind779:30611226
pythonsymbol12:30651887
2i9eh265:30646982
showlangstatbar:30659908
pythonb192cf:30661257

```

</details>

**Comment by alexdima** [comment]
You're right, there is another aspect that makes things even more complicated: default browser behavior and when does the keybinding system call `event.preventDefault()` on the `keypress` event. Our keybinding system intercepts all keypresses and then:
a) if the keypress matches a keybinding rule and the keybinding rule enters a chord or executes a command, we call `event.preventDefault()` and enter a chord or execute the bound command
b) if the keypress doesn't match a keybinding rule or it matches a keybinding rule without a command, we don't do anything, which results in the browser doing its default for that particular event.

Let's focus on pressing `A` in the editor. For example, when binding: `{ "key":"A", "command":"noop" }`, it is no longer possible to type `a` in any editor. That is because the keybinding system will find a keybinding rule which matches the keypress and will call `event.preventDefault()` on the keypress. This results in no subsequent `input` event from the browser, we effectively stop the browser from generating input on `A`. When doing `{ "key":"A" }` or `{ "key":"A", "command":"" }`, this is a keybinding rule which matches, but it doesn't have a command, so our keybinding system will not call `event.preventDefault()` on the keypress.

The same is happening with `Shift+Tab` and `Tab` and some other keys which would have a default browser behavior. If you find that this is something we should improve in our documentation, then please don't hesitate to create a PR against https://github.com/microsoft/vscode-docs/blob/main/docs/getstarted/keybindings.md
