### ISSUE TITLE
"Cannot read property 'substring' of undefined" when formatting adding newline at end of file

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#17424]
From https://github.com/Microsoft/vscode-go/issues/690

- On Linux or Windows, Install Go extension
- Set `"go.formatOnSave": false`
- Open any go file with no newline at the end of the file like
```go
package main

func foo() {
}
```
- "Format document"

The Go extension returns one edit which inserts a newline at the end of the document. This looks correct to me. At some point, a calculation in vscode fails because the end of the edit is off the end of an array of lines.

![image](https://cloud.githubusercontent.com/assets/323878/21279628/ff8a5430-c395-11e6-801a-a01950673c07.png)

Doesn't repro on MacOS because the formatter there apparently doesn't return a trailing newline.

Doesn't repro with the Go extension's 'format on save' because it works through extension APIs. Also reported for python files.

**Comment by baslr** [comment]
Same, If I issue formating via context menu I get a Error, via shortcut I get a warning.

**Comment by NikosEfthias** [comment]
how come this issue is closed ? I havent seen any solution above in the comments @jrieken

**Comment by jrieken** [comment]
@NikosEfthias This issues wasn't and isn't closed.

**Comment by rjmacarthy** [comment]
Same issue here.

**Comment by NikosEfthias** [comment]
i solved (kinda) the issue by adding a new line to the end of files well this not the solution but at least it works

**Comment by jrieken** [comment]
@roblourens Sorry, I am not really able to reproduce because of the go installation pain. However, I am able to understand what's going wrong. Seems like we accessing an invalid range of the document without validating the range first. Two things are next: (1) validate the ranges the formatter gave us, (2) understand why the formatter gives a range the exceeds the document. For (2) I looking at you because my guess is that vscode-go crafts an invalid replace range some
