### ISSUE TITLE
Cannot unbind wordWrap

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#17420]
Extracted from #17406

VSCode Version: Code 1.8.0 (3874693, 2016-12-13T17:38:28.425Z)
OS Version: Darwin x64 16.3.0

Steps to Reproduce:
1. On macOS choose Polish programmer keyboard layout in System Preferences
2. Go to **Preferences > Keyboard Shortcuts** and unbind wordWrap:

```json
{ "key": "alt+z",                 "command": "-editor.action.toggleWordWrap" }
```
3. Type `alt+z`
-> `Ω` is inserted and word-warp is toggled

//cc @mikchmie @coreh

**Comment by rebornix** [comment]
@mikchmie @coreh can you help confirm if you still run into this issue in 1.8.1 stable or Insider? I can't reproduce this anymore. Moreover, when I debug 1.8.0 bits, sometimes I can run into the issue but just after a few trails the issue is gone.

**Comment by rebornix** [comment]
The solid repro steps:

* Launch VS Code with a clean keybinding
* Make changes to user's keybinding file, unbind Toggle Word Wrap
* Do not quit/relaunch VS Code, press `alt+z`, `Ω` is injected and the word wrap is toggled.

The root cause is after we make changes to the keybindings file, the corresponding Menu item is not updated. cc @bpasero we may want to *redraw* the menu when menu items are affected.

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.

**Comment by alexandrudima** [comment]
It is possible to remove any keybinding. 

However, if a keybinding is shown in a top level menu, it might be necessary to restart VS Code until the change takes effect.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/18731
