### ISSUE TITLE
The extension was activated unexpectedly

### ISSUE THREAD

**Issue by thqby** [microsoft/vscode#174214]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.75.1
- OS Version: win11

Unlike previous versions, the extension is activated after vscode starts when its package.json contains the following configuration:
```
"contributes": {
	"languages": [
		{
			"id": "code-output",
			"mimetypes": [
				"text/x-code-output"
			]
		}
	]
}
```
and extension's activation event is displayed as `onLanguage:code-output`.

**Comment by gjsjohnmurray** [comment]
1.74 introduced implicit activation for some contributions. See https://code.visualstudio.com/updates/v1_74#_extension-authoring

Your extension declares that it contributes (to) the code-output language, so VS Code now behaves as if you had also declared `onLanguage:code-output`.

Is this causing you a problem?

Pinging @joyceerhl

**Comment by thqby** [comment]
Yes, at present, it seems that the extension is always activated after associating with `text/x-code-output`. However, this is unnecessary because the relevant language file has not been opened and there will be no output requirement.

**Comment by thqby** [comment]
Of course, what I'm actually using is `myextension-output` instead of `code-output`, but activation event is still `onLanguage:myextension-output`.

**Comment by gjsjohnmurray** [comment]
By listing `text/x-code-output` in the `mimetypes` array property of your `myextension-output` language contribution I think you are making VS Code set all output channels to use your language unless the creator of the channel explicitly specifies another language for it. So when the channel gets created your extension activates in order to contribute the language.

I suggest you remove the `mimetypes` property.

**Comment by thqby** [comment]
I see what you mean, thank you.

**Comment by gjsjohnmurray** [comment]
If this works please close the issue.
