### ISSUE TITLE
Duplicate prompt in terminal only in tunnel mode in browser

### ISSUE THREAD

**Issue by malaybasu** [microsoft/vscode#174382]
With the recent update and vscode server using tunnel mode in browser, a prompt like "username:wordking_dir" directory shows up. I tried to figure out where this is coming from. I tried modifying my PROMPT but the terminal prompt is always there. Can anyone tell me how to fix this? Thanks.

Version: 1.75.1
Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
Embedder: vscode.dev

**Comment by karthiknadig** [comment]
We sincerely apologize for the delay in responding to your issue. Due to the high volume of reports, we’ve been unable to address every submission promptly, especially those that lack the details needed for us to investigate effectively.

To ensure that we can help you and others more efficiently, we kindly request that issues include detailed and actionable information. Please refer to our [issue reporting guidelines](https://aka.ms/vscodeissuereporting) for guidance on how to provide the necessary details.

Additionally, to help us understand the problem more clearly, please consider providing a screen recording showing exactly what isn't working as expected. While we can work with most standard formats, .gif files are preferred as they display inline on GitHub. You may find https://gifcap.dev/ helpful as a browser-based tool for creating .gif recordings.

We value your feedback and thank you for taking the time to report issues—it helps us make the product better for everyone.

Happy Coding!
