### ISSUE TITLE
resolveDebugConfiguration is called twice for msedge launch configuration

### ISSUE THREAD

**Issue by kuojianlu** [microsoft/vscode#174310]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.75.1
- OS Version: Windows_NT x64 10.0.22623

I have an extension implementing debug configuration provider that resolves `msedge` and `pwa-msedge` launch configurations. I found that when using this extension to debug a project with `msedge` launch configuration, `resolveDebugConfiguration` method will be called twice.

I created a minimal repo for you to reproduce this issue. Steps to Reproduce:

1. Clone https://github.com/kuojianlu/vscode-msedge-issue.
2. Open `vscode-msedge-issue/vscode-msedge-issue-extension` with VS Code.
3. Run `npm install`.
4. Add breakpoints in `src/debugConfigurationProvider.ts` line 9.
5. F5.
6. Open `vscode-msedge-issue/vscode-msedge-issue-project`.
7. F5.

Before Microsoft Edge browser is launched, the breakpoints will be hit twice. In the first hit, the type of debug configuration is `msedge`, but in the second hit, the type is `pwa-msedge`.

I would like to know if this behavior is by design or is a bug?

**Comment by roblourens** [comment]
I think this is by design, msedge still gets resolved to the pwa-msedge type, but you shouldn't need to register for `pwa-msedge` since this is deprecated for users and people should not be using it in launch configs. But if you are finding that users still use that type, then your code will need to handle being invoked twice.

@connor4312 is that right? Can the DA register for `msedge` directly instead of `pwa-msedge` now?

**Comment by connor4312** [comment]
No, DA's should (only) register for `pwa-msedge` since that will be used internally--didn't move the other way since that would break a couple years of new extensions that depended on the `pwa-` prefixed types.
