### ISSUE TITLE
Allow scrapbook untitled working copies

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#174485]
required for https://github.com/microsoft/vscode/issues/172974

We would like a `IFileWorkingCopy` implementation that is related to `UntitledFileWorkingCopy` as in, there is no file on disk backing the model so it wouldn't auto-save and would be recovered from a hot exit, but can more easily be discarded without prompting to save.

- If a user closes a window without `onExitAndWindowClose` hot exit enabled, the user would not be prompted to save
- The dirty indicator would not show for that file type

**Comment by bpasero** [comment]
@amunger I am trying to understand the requirements for such a change and maybe notebook team could help out. I see that backups are really tied to dirty state tracking, meaning that if a working copy does not report it is dirty, we do not create any backups.

So I am wondering if we can keep the dirty state of the working copy as it is today so that backups work, but see for certain UI locations where we show a dirty indicator today to hide it. We can expand on that strategy that to also hide any dialogs that would appear today when hot exit is off.

However, I miss a little bit the greater picture here for where else scrapbook working copies would have to alter its behaviour. 

For my testing, I am running the command "New GitHub Issue Notebook" which normally opens an editor dirty, but with a few tweaks shows like a scrapbook:

![image](https://user-images.githubusercontent.com/900690/223692965-b90720ce-1866-434d-a234-75367b1137f3.png)


**Dirty State in Editor**
Changing this line to return `false` should remove the dirty indicator in the editor tab:

https://github.com/microsoft/vscode/blob/815295b041a4a1d59dbe7c33a17168fef36e8138/src/vs/workbench/contrib/notebook/common/notebookEditorInput.ts#L120

**Dirty State for Working Copies**
Changing this method to do an early `return` should remove the global dirty indicator:

https://github.com/microsoft/vscode/blob/815295b041a4a1d59dbe7c33a17168fef36e8138/src/vs/workbench/contrib/files/common/dirtyFilesIndicator.ts#L43

**Comment by bpasero** [comment]
Ping

**Comment by amunger** [comment]
Sorry - I read through your comment too fast the first time and missed the ask.

Playing around with those two hacks seems to provide the behavior we're looking for except for the case of exiting with hotexit=`off`/`onExit` - Ideally we would not prompt to save the file in that case.

**Comment by amunger** [comment]
could probably verify with https://github.com/microsoft/vscode/pull/183310

**Comment by bpasero** [comment]
I will not push those changes for May though, there are still some UX concerns.

**Comment by amunger** [comment]
I figured that was the case, but still probably the best way to verify - checking that out and running locally. Or you could mark verified if you're comfortable with that.

**Comment by bpasero** [comment]
I think we can move this to June and have it verified then, either with notebooks or my work 👍
