### ISSUE TITLE
Terminals launching using terminal.integrated.cwd do not check for invalid paths

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#17450]
Invalid paths will cause the terminal to start at terminalProcess.js' dir.

**Comment by millergarym** [comment]
Is a variable a valid option to  `terminal.integrated.cwd`?
If so what variables?
eg the directory of the current active document.

This would replace the need for @Tyriar's addin.
https://marketplace.visualstudio.com/items?itemName=Tyriar.vscode-terminal-here

https://github.com/Microsoft/vscode/issues/17387#issuecomment-267718790
https://github.com/Microsoft/vscode/issues/15531#issuecomment-260853892

**Comment by Tyriar** [comment]
@millergarym created https://github.com/Microsoft/vscode/issues/31677

**Comment by lifez** [comment]
@Tyriar Would you suggest me to work on this thing and #31677

**Comment by Tyriar** [comment]
Sorry for the delay, anything with the help wanted label is up for grabs 😃

**Comment by SylannBin** [comment]
I'm sorry if it's not the correct issue to post this. I came here from following a bunch of now closed issues.
So in case it could help you figure out what's wrong with this:
I am having the very same error as described by @siegebell [here](https://github.com/Microsoft/vscode/issues/36758).
It started just after I upgraded budgie 17.10 (based on ubuntu) to 18.04

It happens only if all 3 of these conditions are met:

1. I have no terminal opened in the current instance of vscode.
2. I have several folders opened in the workspace
3. I have no `terminal.integrated.cwd` specified (more on this below).

### More details:

If I use the command `workbench.action.terminal.new` instead of the command `workbench.action.terminal.toggleTerminal`,
it prompts me to chose one of the opened folders in the workspace, and the terminal always starts successfully in this case.

When trying to **toggle the terminal** (without any currently opened):
Using `"terminal.integrated.cwd": "~"`, the terminal fails to start.
But using `"terminal.integrated.cwd": "/home/myusername"`, the terminal starts successfully.

**Comment by Amanej** [comment]
I have the same issue as #56849 , is there any solution to do this ?

Split Terminal used to work, but now just trows 
'chdir(2) failed'
and
'The terminal process command '/bin/bash -l' failed to launch (exit code: 1)'

**Comment by timdmackey** [comment]
I noticed this problem for the first time today. I get the same **`chdir(2) failed`** error when I try to split the terminal.

- The issue occurs whenever I use the "Split Terminal Command".
- Using the "New Terminal" command **does not** throw this error.

**Comment by Tyriar** [comment]
@timdmackey the cwd in split terminal is driven by this:

![image](https://user-images.githubusercontent.com/2193314/50838835-d9268f00-1313-11e9-81af-ba2ac19da14f.png)

It sounds like inherited (likely) breaks when it contains a `'`? Can you create a new issue for this?
