### ISSUE TITLE
keybindings colision with non US keyboard layout

### ISSUE THREAD

**Issue by nunojpg** [Microsoft/vscode#17474]
- VSCode Version: Code 1.8.0 (38746938a4ab94f2f57d9e1309c51fd6fb37553d, 2016-12-13T18:03:00.506Z)
- OS Version: Linux x64 4.8.0-30-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|
|cpptools|ms-vscode|0.9.3|

---

Using a PT-PT layout KB, even tough the mapping of keys looks correct (For example on the vscode desktop Toggle Terminal presents `CTRL+\` as the shortcut, which is the equivalent of the US layout ``CTRL+` ``), when pressing it, instead the Split Editor is activated.

The Split Editor is actually configured to use the `CTRL+\` shortcut on the US layout, but on the PT layout the equivalent is `CTRL+~`, which *also* causes the same action.

So it seems that while the equivalent key on the current layout is considered, the original key is still mapped, which causes a mapping collision after, in this case Split Editor is declared first, which binds to `CTRL+\` and `CTRL+~` simultaneously, and Toggle Terminal then can't use `CTRL+\`.

Steps to Reproduce:

1. Use a Portuguese-Portugal keyboard layout. (reported in Ubuntu as layout: 'pt,us',)
2. With the default keybindings configuration, both `CTRL+\` and `CTRL+~` activate workbench.action.splitEditor, and neither activates workbench.action.terminal.toggleTerminal.
3. Add the overlay: { "key": "ctrl+\\",                "command": "workbench.action.terminal.toggleTerminal" },
4. Now both `CTRL+\` and `CTRL+~` activate workbench.action.terminal.toggleTerminal and neither activate activate workbench.action.splitEditor.

**Comment by web2style** [comment]
I have the same issue. In my case I want to toggle line comment, default shortcut for this is `cmd+/`, but instead I get my editor splitted.

My keyboard layout is ANSI (United States and others). Tried changing to ISO (European), but nothing changed.

This happened after upgrading to 1.8.

**Comment by alexandrudima** [comment]
I have validated that we now (i.e. after PR #22894 aka #17521 -- in tomorrow's Insiders build) appear to behave correctly for this keyboard layout

![image](https://cloud.githubusercontent.com/assets/5047891/24253086/9f673370-0fdf-11e7-80a2-20f45d713ba4.png)


---
### Analysis of default keybinding for `workbench.action.terminal.toggleTerminal`
* `workbench.action.terminal.toggleTerminal` is bound by default to the key code binding `` ctrl+` ``
* `` ` `` can be produced through two scan code combinations: ``Shift+[BracketRight] `` and `` Ctrl+Alt+[Backslash] ``. i.e.:
![image](https://cloud.githubusercontent.com/assets/5047891/24253148/ca7793ca-0fdf-11e7-917e-10570a8c7fd5.png)

* because `Ctrl` must be used to produce the visual character, the key code binding `` ctrl+` `` is not mappable to `` Ctrl+Alt+[Backslash] ``. i.e. the scan code combo would need to be something like `` Ctrl+ Ctrl+Alt+[Backslash] ``, which we don't support.
* therefore, `` ctrl+` `` is mapped to to ``Ctrl+Shift+[BracketRight]``. i.e.:
![image](https://cloud.githubusercontent.com/assets/5047891/24253268/24f50120-0fe0-11e7-838d-57c95e8e788a.png)
* this is correctly indicated (labeled) in the `F1` list when searching for the action:
![image](https://cloud.githubusercontent.com/assets/5047891/24253312/40014a96-0fe0-11e7-8262-be93c5360987.png)

* the default binding might be unfortunate, but it is correct. We don't ship with keyboard layout specific default keybindings, that is something you can upvote in #1240

---
### Analysis of pressing `Ctrl+[Backquote]`

![image](https://cloud.githubusercontent.com/assets/5047891/24253399/89f907ec-0fe0-11e7-8d7b-a9dcbb257423.png)

We correctly label it:
![image](https://cloud.githubusercontent.com/assets/5047891/24253363/7008cf2a-0fe0-11e7-854f-b195bdc1370e.png)

By default, it executes `workbench.action.splitEditor`

---
This makes me believe the fix in PR #22894 aka #17521 resolves this issue. Please double check in tomorrow's insiders build.
