### ISSUE TITLE
Installing shell command 'code' in PATH does not persist

### ISSUE THREAD

**Issue by benjamin-rood** [Microsoft/vscode#17475]
- VSCode Version: Version 1.7.2 (1.7.2)
- OS Version: macOS Sierra 10.12.1 (16B2657)

Secondary problem: If you create a permanent symbolic link or addition to `~/.bash_profile` referring to `code`, VS Code complains about it. So you're stuffed either way. 

Steps to Reproduce:

1.  Ran the `Shell Command: Install 'code' command in PATH`.
2. Open new terminal window, `code` will launch VS Code.
3. Restart machine OR even just close VS Code and then restart terminal.app...
4. Fail

I doubt it's the configuration of my`~/.bash_profile` – as any and all other PATH additions are working correctly... I include it below for reference, as you can see it is very minimal:

```export PATH=$PATH:/usr/local/go/bin
export GOPATH=$HOME/go
export GOSRC=$GOPATH/src
export PATH=$PATH:$GOPATH/bin
export GOBR=$GOPATH/src/github.com/benjamin-rood

#code () { VSCODE_CWD="$PWD" open -n -b "com.microsoft.VSCode" --args $* ;}
```

The commented-out code script works, btw.

**Comment by joaomoreno** [comment]
This command will place `code` inside `/usr/local/bin`, can you confirm this? Why does your machine clean that folder when restarting?

**Comment by MooseTheory** [comment]
I am experiencing this issue.
A link is being created at `/usr/local/bin/code`
The first one is:
`/usr/local/bin/code@ -> /private/var/folders/k3/rp4pclyd7cq3_yfntqx4533w0000gn/T/AppTranslocation/8501FF93-8B84-4304-83CC-96BA4F61C002/d/Visual Studio Code.app/Contents/Resources/app/bin/code`

If I exit VS Code, the link breaks, and when I re-run the install 'code' command in path, the new link is:
/usr/local/bin/code@ -> /private/var/folders/k3/rp4pclyd7cq3_yfntqx4533w0000gn/T/AppTranslocation/C2E2789E-2364-4FEE-B928-67A35D4493B6/d/Visual Studio Code.app/Contents/Resources/app/bin/code



(Throwing this in since my config is slightly different from the original poster)
VSCode Version: Version 1.9.0
OS Version: macOS Sierra 10.12.3

**Comment by MooseTheory** [comment]
I did some digging on my own, and I suspect the issue is related to placing the application in the ... "global" `Applications` folder, not my user `Applications` folder.
I moved the binary there to see if that fixed an issue with the automatic updater, and my `code` command started working properly now.

**Comment by mattbaker** [comment]
Stuck with this same issue but moving VS Code to ~/Applications or /Applications doesn't appear to make a difference. The `code` command doesn't seem to persist (it is similarly symlinked into that `/private/var/folders` business). It also looked like updates weren't persisting either.

OS: macOS 10.12.2
Trying with a fresh download of Code 1.11.2, I'll report back when the issue pops up again. This certainly is a curious one.

**Comment by joaomoreno** [comment]
Same underlying issue as #7426.

The location of the app is irrelevant. Only the quarantine attribute matters. [More info here](https://github.com/Microsoft/vscode/issues/7426#issuecomment-277737150). Mitigation fix coming this month

**Comment by mattbaker** [comment]
Gotcha, thanks for the update.

**Comment by lsps9150414** [comment]
Remove `/usr/local/bin/code` and reinstall the shell command from the command palette fix it for me.
