### ISSUE TITLE
VS Code doesn't clean folders of old extension versions

### ISSUE THREAD

**Issue by xiaoxi-david** [microsoft/vscode#174907]
Although @sandy081 in #132896 claimed that VS Code cleans up folders of old versions of extensions, I have folders from two years ago that show that VS Code doesn't delete folders of old versions of extensions.

![image](https://user-images.githubusercontent.com/24303680/220326706-2506ba27-cd6c-464d-bb51-3fe709bd0994.png)

Version: 1.75.1 (system setup)
Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf
Date: 2023-02-08T21:32:34.589Z
OS: Windows_NT x64 10.0.19045
Sandboxed: No

**Comment by sandy081** [comment]
Can you please check if these folders have valid `package.json` files?

**Comment by xiaoxi-david** [comment]
> Can you please check if these folders have valid `package.json` files?

Only the latest version has a `package.json` file. The remaining folders have (and not always) the folders `out`, `filesPython` and `resources`.

**Comment by sandy081** [comment]
Ok, it seems the folders are not complete deleted during the clean up and hence VS Code is not able to detect them as installed extension folders. This behaviour is fixed recently. But the fix will not delete these folders because we are unsure if these folders are user created or vscode created. Hence I would recommend to delete them manually for now. Apologies for this.

https://github.com/microsoft/vscode/issues/162051
