### ISSUE TITLE
Ability to find replace in a Jupyter notebook by cell

### ISSUE THREAD

**Issue by jimhavrilla** [microsoft/vscode#174978]
Hey, I'd love the ability to not only find and replace within a specific Jupyter notebook cell, but also to have my find/replace start where my cursor actually is in a cell instead of replacing the topmost one and then having to figure out where it is.  Then, often when I try to "Undo" that "Undo" only works cell-specifically.  If I "Undo" outside of the cell it makes larger changes to whole cells but not changes within cells. Admittedly, this may be an issue with Jupyter extension more than VSCode, but I do feel the cursor is something VSCode can control.

Anyway thanks for listening!

**Comment by rebornix** [comment]
Thanks @jimhavrilla for the suggestion. It's a valid user case of a in-cell find/replace widget. Ctrl/Cmd+F will always open the notebook level find widget and in a few cases (for example cmd+e), we accidentally opened the in-cell find widget before but recently we fixed it. Turns out that's a feature that some actually like.

**Comment by jimhavrilla** [comment]
Awesome I’m glad to hear it, I’d love to see it since I’ve been using vscode so much lately. 
By the way is there any way to have the cursor scroll to each notebook level Redo/Undo?

**Comment by rebornix** [comment]
> By the way is there any way to have the cursor scroll to each notebook level Redo/Undo?

@jimhavrilla can you elaborate a bit more on this? It would be great if you can give us an example of how you expect the cursor scrolling to work on undo/redo. Currently the notebook level undo/redo is separated from cell level undo/redo (controlled by `notebook.undoRedoPerCell`), and the notebook level undo/redo doesn't touch the cell editor cursor/selections, so I'd love to know what's your expectation.

**Comment by jimhavrilla** [comment]
Hey no problem, thanks for following up.
Yes, so it's kind of hard to show visually, but I'd like it to be work similar to Undo's cursor memory in Microsoft Word:


https://user-images.githubusercontent.com/6568964/222940579-1ee3c5c0-58b1-49b1-81bb-0f013f810398.mov

Currently it does not seem to save cursor position and scroll to changes on the notebook level, or it least it seems like it does not for me as of Jupyter extension version v2023.2.1000592019 and VSCode version 1.76.0 (Universal)
Commit: 92da9481c0904c6adfe372c12da3b7748d74bdcb.

Here is me attempting to do it on a small notebook:


https://user-images.githubusercontent.com/6568964/222940583-f39951fa-46f9-458f-b413-913b9a95bf89.mov

**Comment by Kirow** [comment]
I did not want to create new issue, but I have something to report and it seems that topic does match.

When I using Find and Replace feature inside `.ipynb` file - there is no possibility to replace inside selection (missing icon to enable this feature). It would be nice to have it (or inside context menu of filter button)
<img width="453" alt="Screenshot 2024-02-19 at 15 51 00" src="https://github.com/microsoft/vscode/assets/1594953/23070612-fb3d-492d-ace5-2e4358d4e98a">
<img width="335" alt="Screenshot 2024-02-19 at 15 50 31" src="https://github.com/microsoft/vscode/assets/1594953/5ea1d897-66f5-4c2d-9c1d-31e6a1d4798f">

As for the topic of Undo/Redo, I can confirm that I also have problems. It is very often when instead of removing last code change - it removes whole cell. Not intuitive behaviour.

**Comment by jimhavrilla** [comment]
Sounds good thanks!
