### ISSUE TITLE
'Real' Files not Being Reopened

### ISSUE THREAD

**Issue by Jonatino** [Microsoft/vscode#17507]
- VSCode Version: 1.9.0-insider
- OS Version: Windows 10 x64 Pro

I noticed that when I have a bunch of untitled-unsaved files with hotexit enabled and if I open a file from explorer, if I close VSCode and open it only the untitled-unsaved files will be restored and not the file I opened from explorer.

Steps to Reproduce:

1. Create new untitled-unsaved tabs 
2. Click File -> Open File -> and choose a random file
3. Close VSCode
4. Reopen VSCode and notice how the file you chose in step 2 is not restored

Video: https://dl.dropboxusercontent.com/u/91292881/ShareX/2016/12/2016-12-18_22-59-55.mp4

**Comment by kieferrm** [comment]
This happens in a workspace without an open folder.

**Comment by Tyriar** [comment]
@Jonatino yes there is 😄. Before hot exit we didn't support restoring windows with no folder opened at all, here is the feature request for that #207. The reason it's being partially restored with only the dirty files is because hot exit restores on no folder windows currently rely on the fallback hot exit code, where we go through the backups for the window and open/restore them if they weren't already present (say if there was a crash).

Closing this off in favor of #207.
