### ISSUE TITLE
Clicking on a search result for a markdown cell in a notebook puts the cell into edit mode

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#175010]
Testing #174724

1. Create a markdown cell with the following contents `# header`
2. Search for `header` in global search
3. Click on the result for the markdown cell in step 1
4. :bug: the notebook cell is put into edit mode

**Comment by andreamah** [comment]
^ This is also what the notebook find widget in its default state does in order to make editing easier. However, the find widget has an option to search for `rendered markdown` (instead of `markdown source`), which will also be added to search in an upcoming PR. Selecting for `rendered markdown` won't make the cell go into edit mode.

<img width="221" alt="image" src="https://user-images.githubusercontent.com/31675041/220465145-3405d44d-b98a-4c71-b9f4-0d54f844e4c9.png">

Would adding this solve the confusion with cell states? Or do you think that searching for `markdown source` (what the search does currently) shouldn't change the cell state?

**Comment by joyceerhl** [comment]
I think of the rendered markdown state as the 'default' state of a notebook so I was surprised that search would take me out of that view. That being said maybe it does make sense to switch to edit mode automatically if we assume that users are searching so that they can immediately edit.

**Comment by andreamah** [comment]
That's true. It's mostly because the find widget is already like this, and searching the markdown source will allow things like "replace all" possible (which is a big use case for search). 

I'll close this for now, but I'll keep it in mind when getting UX feedback for the feature.
