### ISSUE TITLE
VS Code Walkthrough Instructions disappearing in Playground

### ISSUE THREAD

**Issue by D1M1TR10S** [microsoft/vscode#175386]
Does this issue occur when all extensions are disabled?: Yes/No (don't know)

- VS Code Version: 1.75.1
- OS Version: macOS Ventura 13.0.1

VS Code walkthrough instructions disappear when opening the hello-world.yaml file from the link (simple workflow step).  Hearing the same feedback from multiple users doing internal testing.

https://www.loom.com/share/10520221501240ea812aba76d3dbce24?t=87

Steps to Reproduce:

1. Open a codespace from [the Actions Playground repo](https://github.com/github/codespaces-actions-playground).
2. Skip to the second walkthrough called "Writing workflows".
3. In the first step ("Actions workflow"), click the link to open the hello-world.yml file

**Comment by mjbvz** [comment]
This could potentially happen because the webivew that displays the welcome content has been reparented. This is actually easy to simulate:

1. With a single editor group open
1. Open a walkthrough 
2. Run `View: Grid editor layout`

This will destroy the webview content because one of its parent nodes changes. The iframe still exists in the dom, but nothing is rendered inside of it. This is a limitation of how iframes are designed and is not something we can disable (but we do workaround it in other places)

---

@bhavyaus To fix this, you can either try switching the welcome webview to use an [`IOverlayWebview`](https://github.com/microsoft/vscode/blob/8b76efe9d317d50cb5b57a7658e09ce6ebffaf36/src/vs/workbench/contrib/webview/browser/webview.ts#L274) or explore forcing the webview to re-render itself if it get reparented 

Webview like the readme and markdown preview all use `IOverlayWebview` to fix this
