### ISSUE TITLE
allow showing line above {} scope in case of c# like formatting for `editor.stickyScroll`

### ISSUE THREAD

**Issue by jNaimXIII** [microsoft/vscode#175420]
I've been using the `editor.stickyScroll` feature for a while now and it's been great at showing me the context I'm in. Recently, I opened a C# file and noticed the following behavior.

<img width="754" alt="image" src="https://user-images.githubusercontent.com/115424698/221351730-130a65e4-51af-4567-9a80-1f3daa4a3cac.png">

Due to how C# code is usually formatted, the `{` ends up in the next line after a function declaration or conditional. So, VSCode just shows an empty `{` without any kind of clue of the actual definition.

It would be nice to have it show the previous line for braces which have only whitespace before them.

**Comment by aiday-mar** [comment]
Hi @jNaimXIII, sticky scroll uses one of three different models to define what lines to sticky: the outline model, the folding provider model or the indentation model. This setting is configurable under `editor.stickyScroll.defaultModel`. These define the hierarchical structure of the code and influence the sticky scroll lines. Currently there is no plan to change these models, however you may track and upvote the following issue https://github.com/microsoft/vscode/issues/168428 which aims to introduce a sticky scroll API so that extensions can define their own sticky models. In your case, the C# extension could define their own sticky model and address this issue. In the meantime this issue will be closed.
