### ISSUE TITLE
Hot-Exit: works only if there is one instance (window) of VS Code open

### ISSUE THREAD

**Issue by lypscan** [Microsoft/vscode#17548]
- VSCode Version: 1.9.0-insider (also reproducible in 1.8.0)
- OS Version: Windows 10

Steps to Reproduce:

1. Open VS Code anywhere, create new file, write something but don't save
2. Open another VS Code window ( Ctrl+Shift+N ), create new file, write something but don't save
3. Close either window

The expected behavior would be for the hot-exit feature to kick in and not to display the file-save prompt.
I'm not sure if this is a bug or a missing feature.

Well, probably a more common and practical use case would be to open two folders into separate VS Code windows.

**Comment by bpasero** [comment]
This works "as-designed" and was an explicit decision. The rationale is that you cannot close a window unless the application quits in the same way you cannot close a dirty editor when you click the close button. In other words, we prevent you from "hiding" dirty things by explicitly asking to save or discard so that upon next restart there is not things being restored that have been closed before.

**Comment by lypscan** [comment]
I see what you mean, but for me, the hot-exit feature is almost useless, because, since VS Code doesn't allow opening two or more project folders in the same window, I am kind of forced to work with multiple windows open at the same time. This is why I felt the need to report this, I though perhaps I wasn't alone :)

**Comment by Tyriar** [comment]
#15467 is exploring our options for this, one of my goals for January is to have a solid way forward on less strict hot exit/customization so expect movement on this in 1.10.
