### ISSUE TITLE
Allow access to terminal/process created by debug session launched into internal terminal.

### ISSUE THREAD

**Issue by indiejames** [Microsoft/vscode#17555]
- VSCode Version: 1.8.0
- OS Version: All

I have run into an issue where when I close a debug session launched in the integrated terminal my code to stop the running process hangs (not a VS Code bug per se). I could ensure that the process gets killed completely if I had access to the process id created during the launch or if I had access to the Terminal created. Providing access to the Terminal (either in the debug adapter or in the associated extension) might be useful for other things as well.

**Comment by weinand** [comment]
@indiejames in node-debug I'm using an "evaluate(..)" to find the ID of the node process (for killing it).
Could you do something similar?
Returning the correct process ID through the runInTerminal API is difficult...

**Comment by indiejames** [comment]
@weinand Let me take a look at that. My big concern would be somehow getting the wrong process id and killing the wrong process.

**Comment by weinand** [comment]
@indiejames I think the likelihood for getting the wrong process id is small.
If you have a connection to your runtime/debuggee and this connection was working fine for duration of the debug session, then you can be pretty sure that you are talking to the correct process (and got its correct process ID via the 'evaluate').

On the other hand, getting the correct process ID from the terminal is much more error prone because you do not really know what intermediate shells, commands, or wrappers are involved. So you do not really know whether the process ID is the ID of the runtime/debuggee or the ID of some parent process.

**Comment by weinand** [comment]
Assuming that you are using the DAP's `runInTerminal` request to launch the debuggee in the integrated terminal, then there is an optional `processId` returned in the `body` of the response from the request.

In theory this is the process ID you are looking for.

However, since VS Code's integrated terminal does not know how the process id, `runInTerminal` doesn't return any.

So I still suggest to use the approach sketched above (and I will close this issue because I cannot do anything better).
