### ISSUE TITLE
Switch to Unsaved Tab When Prompting to Save

### ISSUE THREAD

**Issue by Jonatino** [Microsoft/vscode#17552]
- VSCode Version: 1.9.0-insiders
- OS Version: Windows 10 x64 Pro

Steps to Reproduce:

1. Open any file in VSCode (We will call this tab A)
2. Create new untitled tab and make changes but do not save (We will call this tab B)
3. Switch back to tab A
4. Right click tab A select close others

I think the 'Do you want to save the changes you made to Untitled-1?' should switch to the appropriate tab (in this case tab B) to show the user the contents before they decide to delete them forever.

**Comment by Jonatino** [comment]
I will take a stab at this :)

**Comment by jontro** [comment]
In addition to this it would be great if all saved files will be closed automatically even if you press cancel

**Comment by kieferrm** [comment]
This works as expected on Widows. On macOS, the untitled editor is not revealed.

**Comment by bpasero** [comment]
@kieferrm any steps to reproduce?

**Comment by bpasero** [comment]
I speculate that @kieferrm tried to verify this on yesterdays insider build but the fix is only in todays insider build.

**Comment by kieferrm** [comment]
@bpasero I just retried on the latest insider and it's working fine. It still puzzles me though, since when I saw the discrepancy between the platforms I compared the build ids and commit ids and they were the same.

**Comment by bpasero** [comment]
@kieferrm well there is actually a timing issue with my fix because opening a modal dialog (like the one you get when you are asked to save the file before closing) stops the entire JS process and rendering. So, if the dialog managest to get into the way of me trying to reveal the editor that is to be saved, you will not see the current editor getting revealed in time.

For that I do a bit of trickery where I wait for 2 request animation frames before showing the modal dialog. In my testing I could not get the issue you describe but I am also thinking that it might still happen if the renderer is slow doing rendering...

**Comment by sandy081** [comment]
I see the Unsaved tab before the dialog shows up.
