### ISSUE TITLE
Open User Settings (JSON) command should open current profile settings while in a profile

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#175598]
Ref https://github.com/microsoft/vscode/issues/173841#issuecomment-1423811214
Ref #156144

When a user switches profiles, what is considered the "user settings" changes, where
- Application-scoped settings are still saved to the default profile's settings.json
- Other user settings are saved to the current profile's settings.json

The current commands are "Open User Settings (JSON)" and "Open Current Profile Settings (JSON)". One idea is to have the commands be "Open Application Settings (JSON)" and "Open User Settings (JSON)" instead.

I'll leave this issue open in case anyone has any feedback. Also feel free to vote on the issue even though it's not filed under Backlog Candidates.

**Comment by Ramin-RX7** [comment]
I still find this a bit confusing. At first I thought `user` settings is the global settings that we want the user to have for all of his different profiles. for example `files.autoSaveDelay`. 
and `profile` setting will be a type of configuration that dives deeper in details like `python.linting.mypyEnabled`
But it seems no. I'm totally misunderstanding this topic. So is there any documentation that differentiate between these expressions we use like `user`, `profile`, `global`, `Application-scoped`, etc. settings  and show their relations?

> One idea is to have the commands be "Open Application Settings (JSON)"

IMO this won't be a good command since not only the application settings/configs do not necessarily need to be separated but also it's still a bit confusing like other settings that were mentioned

**Comment by isidorn** [comment]
+1 for cleaning up things here. 
Have separate commands in the command palette makes sense.

What are your thoughts on the Setting title area action? Is there concern that the current flow is confusing to the users? Could we just open the Profile settings? 

Thank you!
