### ISSUE TITLE
Default focus to "find" input on execute of replace

### ISSUE THREAD

**Issue by mfrost66** [Microsoft/vscode#17562]
Executing a replace (in file) should set default focus to "find" input field when multiple lines are selected as the find value is not set from the selection and has the value set to the previous find/replace

**Comment by mylowillem** [comment]
Yes please add a setting that controls whether or not selection is turned on by default.

**Comment by rebornix** [comment]
Right now, if the current selection is not empty and not multi line, we will use current selection as search string. Since search string is determined in this way, we will focus the Replace Input.

If both current selection and existing search string in Find Widget are empty, we'll focus the Find Input as users need to type in something to search.

If you are not that satisfied with the auto-populating search string feature, let's talk about it in https://github.com/Microsoft/vscode/issues/20768 .

**Comment by mfrost66** [comment]
Find/replace in vscode is possibly the least usable of any editor I've used in the last 20 years.  Seriously.  You haven't even bothered to support keyboard usage.  You clear my selection when I try to search.  You erase my previous search.  You don't support find history.  You have violated all the 7 pillars of search usability and have placed your eternal soul in jeopardy.

Please, pretty please, with sugar on top - assign someone to this who will give it some love

**Comment by rebornix** [comment]
@mfrost66 

> You clear my selection when I try to search
We don't but as we have incremental search, once you type characters that exist in the document, the current selection will be moved to the first find result. Do you mean you actually don't like this feature?

> You erase my previous search
If you don't like our populating query keyword from selection automatically, you should be able to turn it off later in settings (once we have a new version of Insiders)

> You don't support find history
Valid feature request.
