### ISSUE TITLE
Ubuntu: can't run vs code under wayland

### ISSUE THREAD

**Issue by kobiaszu91** [microsoft/vscode#175654]
I'm trying to rung vs code with --enable-features=UseOzonePlatform --ozone-platform=wayland but I'm getting "not in the list of known options" and vs code stays blurry 

system: Ubuntu 22.04.2 LTS

![Screenshot from 2023-02-28 15-36-58](https://user-images.githubusercontent.com/54553518/221885611-9544a7d5-9568-4ddd-8ef5-6467da70cb75.png)

**Comment by devansh08** [comment]
These options might work instead: `--ozone-platform-hint=auto --enable-features=WaylandWindowDecorations`. Works fine so far for me on Arch Linux (KDE Plasma).
Source: https://wiki.archlinux.org/title/Wayland#Electron

**Comment by kobiaszu91** [comment]
@devansh08 Tried almost every possible command, still blurry :/

**Comment by aron-barm** [comment]
Hi,
I use the same OS and VScode version and encountered the same problem.
When I ran `code —enable-features=UseOzonePlatform —ozone-platform=wayland` (notice the em dashes instead of the double dashes), vscode opened without those warnings. Try this, maybe it circumvents the problem in your case.

So I **don't get the warnings** anymore, but no matter which options I try with code, the UI still **remains blurry**. In my case, things are scaled by 150% with fractional scaling. Looked at the other issues, and none of the suggested options solves the blurriness for me.

Appreciate any help.

**Comment by aron-barm** [comment]
I encountered the exact same problem, using the same OS and VScode versions.
Appreciate any help.

**Comment by FeryET** [comment]
Getting the same warning, VSCode is starting blurry as of late, didn't have this issue till this week.

**Comment by aron-barm** [comment]
I installed the latest version of insiders, then ran:
```bash
code-insiders --enable-features=UseOzonePlatform --ozone-platform=wayland
```
and text is just as sharp as without using fractional scaling on wayland, which is great. The warning messages did not disappear but I suppose that's not an issue.
Thank you for fixing this!

**Comment by kobiaszu91** [comment]
@deepak1556 @aron-barm Wow! This is the first time I can see sharp VS Code! The only is I can't resize the window. The top ribbon is missing

**Comment by aron-barm** [comment]
I'm happy to hear that it also works for you @kobiaszu91. Yes, inserting `"window.titleBarStyle": "custom"` seems to solve that issue. 
Not sure why say "partially"?

**Comment by TylerLeonhardt** [comment]
Can you all verify once more now that 1.78 will actually ship with Electron 22?

**Comment by TylerLeonhardt** [comment]
verified based on comments above.
