### ISSUE TITLE
[Feature Request] SHIFT + SCROLLBAR scrolls all open windows simultaneously in sync with each other

### ISSUE THREAD

**Issue by emveeoh** [Microsoft/vscode#17570]
Please add the ability to scroll all open code editor windows simultaneously when the user holds the SHIFT KEY and then scrolls the page using the mouse, the mouse scroll wheel, arrow keys or page-up/page-down keys.

Holding SHIFT should synchronize all window scrolling regardless of which code pane scrollbar is selected.

Thank you!

**Comment by compilenix** [comment]
Alt+Scroll would be more usefull as Shift+Scroll is already used for horizontal scrolling.
In addition, i would like it more if this would scroll only all windows within the current vertical or horizontal split view.

**Comment by alexandrudima** [comment]
To keep the number of issues in our inbox at a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: we look at the number of votes the issue has received and the number of duplicate issues filed. Thank you for your time and understanding.

If you disagree and feel that this issue is crucial: we're happy to listen and to reconsider.

**Comment by compilenix** [comment]
:pensive: Well... OK.
