### ISSUE TITLE
onDidChangeContentHeight not fired after calling updateElementHeight

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#175832]
- Have a list with dynamic heights disabled
- Call `updateElementHeight`
- The event `onDidChangeContentHeight` is not fired even though it feels like it should be

Happy to send a PR but I'm not totally sure where the right place is for it to be fired in this flow- maybe just as an `else` here? https://github.com/microsoft/vscode-distro/blob/e8cda7adf83c007f07e4ebce6f5a5419fff463e5/src/vs/base/browser/ui/list/listView.ts#L527

fyi @rebornix

**Comment by legomushroom** [comment]
@roblourens are you passing `undefined` as the second parameter in the `updateElementHeight()` call? If the `supportDynamicHeights` is disable it will indeed [ignore the call](https://github.com/microsoft/vscode/blob/main/src/vs/base/browser/ui/list/listView.ts#L532), but a warning message should be logged in that case.

If a `height number` is passed instead (as we do [in the chat widget](https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/chat/browser/chatWidget.ts#L699)), then the `onDidChangeContentHeight` is called only [if the height value has changed](https://github.com/microsoft/vscode/blob/main/src/vs/base/browser/ui/list/listView.ts#L539), could it be that you were confused by this caching behaviour? I've tested it thoroughly for this case, and it does work as expected ✅ (if you take the height caching part into consideration of course)

Closing this as part of the `housekeeping` effort assuming the later was the case back then for you. Please reopen if you think that the issue is still relevant 🤗

**Comment by roblourens** [comment]
From this

> Have a list with dynamic heights disabled

I assume I was either talking about some non-chat list, or more likely, some early version of the chat list that didn't set `supportDynamicHeights`. Dunno why that was, but this probably indeed isn't relevant anymore. Thanks for digging into it @legomushroom!
