### ISSUE TITLE
VSCode does not auto-detect IPv6 Processes for port forwarding

### ISSUE THREAD

**Issue by aishwaryabh** [microsoft/vscode#175805]
Does this issue occur when all extensions are disabled?: No (we need the codespaces extension enabled to repro)

- VS Code Version: 
- OS Version: 

Steps to Reproduce:
Some users have been receiving errors where VSCode does not detect the running process and the ports tab does not populate specifically for IPv6 processes. We believe it's due to VSCode not being able to pick up IPv6 processes as shown below. [This issue](https://github.com/github/codespaces/issues/12575) here causes intermittent issues with port forwarding on the web and [this issue](https://github.com/github/codespaces/issues/11384) does not let the user forward a port.

Here are the repro steps for the second issue:
1. Create a Codespace using this [repo](https://github.com/mor10/gatsbydemo/tree/main)
2. Run `npm init gatsby`, `cd my-gatsby-site/`, `npm run develop`
3. The process is not detected and the ports tab is not updated. Even if you try to add port 8000 to the ports tab, the forwarded port's content is not displayed
4. Stop the process from the terminal
5. Update `package.json` under `scripts:develop` to be `gatsby develop -H 127.0.0.1` and do `npm run develop`
6. The process is detected and the ports tab is updated. If you click on the ports tab you get the forwarded port content

**Comment by alexr00** [comment]
Optimistically adding for March, but likely won't be done until April given that we have < 1.5 dev weeks left.

We scrape the proc files system for processes that listen on ports, and we do try to catch IPv6, but if the problem here is only with IPv6 then we must be missing something:

https://github.com/microsoft/vscode/blob/da15b03a10fc2095fa69325c581657da1427ca7a/src/vs/workbench/api/node/extHostTunnelService.ts#L375
