### ISSUE TITLE
Scrollbar missing in preview on split view.

### ISSUE THREAD

**Issue by rajinder-yadav** [Microsoft/vscode#17617]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:41:20.664Z)
- OS Version: Linux x64 4.4.0-53-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-markdownlint|DavidAnson|0.6.0|
|EditorConfig|EditorConfig|0.3.4|
|jslint|ajhyndman|1.2.1|
|jshint|dbaeumer|0.10.15|
|vscode-eslint|dbaeumer|1.2.2|
|tslint|eg2|0.7.1|
|cpptools|ms-vscode|0.9.3|
|Spell|seanmcbreen|0.9.1|
|vim|vscodevim|0.4.9|

---

Steps to Reproduce:

1. Open a markdown file
2. Open preview 
3. Split windows side by side

For some reason the scrollbar keeps disappearing on the left split view. Not exactly sure how to reproduce reliably, but it has happened to me several times.

![nosb](https://cloud.githubusercontent.com/assets/439226/21360218/f6d0cdf0-c6ac-11e6-996e-12adc65ba900.png)

**Comment by mjbvz** [comment]
I'm able to repo this as well. It only seems to happen in split view preview when we update the contents of the preview rather than recreating the preview document.

I think it may be an upstream chrome issue, [similar to this one](https://bugs.chromium.org/p/chromium/issues/detail?id=670880&can=1&q=scrollbar%20disappears&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified), but will investigate further.

**Comment by mjbvz** [comment]
This is an upstream chrome issue. I can repo it using a simple html page with an iFrame. Here's the chrome issue tracking this: https://bugs.chromium.org/p/chromium/issues/detail?id=678821

We may be able to workaround this, but so far, nothing I've tried has worked.

**Comment by mjbvz** [comment]
Fixed by #19394 which works around the Chrome issue
