### ISSUE TITLE
go to definition reopening same file, but changes Path casing.

### ISSUE THREAD

**Issue by gregatcssi** [Microsoft/vscode#17612]
- VSCode Version: 1.8.1
- OS Version: Windows 10

Steps to Reproduce:

1. open a file where a class has a definition in the same file.  
(mine is under src\app\Services\movieModel.ts)
2. right click and go to definition. 
3. check the open in editor files (opens file src\app\services\movieModel.ts  this one is in lowercase on Services) 

for me both are listed as open and require to be saved.  if i save the wrong one when closing it basically overwrites all the work i did in the one which is supposed to be saved. 
![two open same file path](https://cloud.githubusercontent.com/assets/4807657/21353508/520c1eea-c694-11e6-8cdd-bca21971ad06.JPG)

**Comment by gregatcssi** [comment]
renaming the folders to all lowercase seems to have removed the second file opening.

**Comment by jrieken** [comment]
@gregatcssi Can you share your `tsconfig.json` with me or do have TypeScript configured to be case sensitive?

**Comment by gregatcssi** [comment]
Thanks Jrieken.   

I didn't configure Code to be case sensitive, unless that was defined by default.
I built the application using the angular-cli with below versions
Angular-CLI : 1.0.0-beta.18
node: 7.0.0
os: win32 x64

tsconfig.json is
```
{
  "compilerOptions": {
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": ["es6", "dom"],
    "mapRoot": "./",
    "module": "es6",
    "moduleResolution": "node",
    "outDir": "../dist/out-tsc",
    "sourceMap": true,
    "target": "es5",
    "typeRoots": [
      "../node_modules/@types"
    ]
  }
}

```

**Comment by jrieken** [comment]
Not really able to reproduce with a small sample... Are you using a special version of TypeScript, e.g. not the one ship by default? Iff so a small indication will show in the status bar.

Passing this one to @mjbvz and @bpasero because TypeScript shouldn't return such references and the workbench should resolve the *real path* before showing the same file as two different files

**Comment by bpasero** [comment]
There is no API to get the "real path" of a path in node.js. They tried to add it, but failed miserably. TypeScript should try harder to return the path as it is on disk to avoid these issues.

**Comment by gregatcssi** [comment]
I updated TSC a little while ago, so the bottom right is showing Typescript 2.0.3 along with cmd  and package.json.  Not sure if this is going to help, but i'm going to update the angular-cli version to beta 24 to see if there are any updates there which might help this.  it's also using 2.0.3. 
If you would like I can send you a zip of the project.  it's still very much in beta, so be kind :-) also you would need angular-cli installed.  i did rename the folders, to all lowercase, but can bring them back to the way they were to replicate issue. (just tried it again and it still causes the bug.)

**Comment by sprinkle131313** [comment]
If you are still having trouble reproducing I think I have something reproducible. Just to be sure it seems this is only a Windows issue.

1. Create the folder and file so that you have "root/folder/file.txt".
2. Open the "root" folder as the work space.
3. Open "file.txt" in the vscode editor using Ctrl+P, and typing file. Make sure it is not just temorarily opened, edit the file and save.
4. Close vscode, doesn't seem to work if vscode is open.
5. Rename "folder" to "Folder".
6. Press Ctrl+P and type "file", now there should be two files, `Folder/file.txt` and `folder/file.txt`.

![untitled](https://cloud.githubusercontent.com/assets/8701667/21444019/53b75ed2-c877-11e6-841c-900784bf84f7.png)

**Comment by bpasero** [comment]
The quick open issue is actually covered in https://github.com/Microsoft/vscode/issues/12448 already and was reported in https://github.com/Microsoft/vscode/issues/6152

**Comment by mjbvz** [comment]
For anyone seeing this issue while working with JavaScript or TypeScript, can you please try collecting a TypeScript server trace to help us track down what may be going wrong here:

1. Set `"typescript.tsserver.trace": "verbose",` in your user settings
2. Restart VSCode and reproduce the problem
3. Open the output pane and share the output from `TypeScript`

Thanks
