### ISSUE TITLE
Upgrade to Node.js v18 (LTS)

### ISSUE THREAD

**Issue by aitor-gomila** [microsoft/vscode#176166]
Hi! While setting up VSCode, I found out it supports only Node `v16>` and `<v17` because it apparently depends on package `@azure/msal-node@1.3.3`.

Reading on [@azure/msal-node](https://www.npmjs.com/package/@azure/msal-node),
> MSAL Node enables applications to authenticate users using [Azure AD](https://docs.microsoft.com/azure/active-directory/develop/v2-overview) work and school accounts (AAD), Microsoft personal accounts (MSA) and social identity providers like Facebook, Google, LinkedIn, Microsoft accounts, etc. through [Azure AD B2C](https://docs.microsoft.com/azure/active-directory-b2c/active-directory-b2c-overview#identity-providers) service

It seems package `@azure/identity` version `^2.0.4` is at fault. `build/package.json`.

Why is this in build package.json? This really shouldn't be a core vscode thing. sure, you can bundle it in a builtin extension, but right in the VSCode base code? Why? To overcome a self-imposed limitation (extensions can't put new actions in the lower part of the activity bar, as far as I know)?

This is not a nerdy linux open source guy thing, `@azure/identity` requires an Azure subscription. Is this really the way in an open source product?

**Comment by lramos15** [comment]
We use the @azure/identity package to upload the built builds to our CDN. The reason this is in the open source repo is so that we're transparent about the build process, this package is not necessary to build the VS Code product and is not why we're stuck on Node 16. We're stuck on Node 16 due to our electron dependency, we're currently working to upgrade to electron 22 which is still Node 16 and then later this year when we upgrade to future electron versions is when we will adopt support for Node 18. Electron upgrades take time as they often break things and have unknown implications.

**Comment by aitor-gomila** [comment]
> We use the @azure/identity package to upload the built builds to our CDN. The reason this is in the open source repo is so that we're transparent about the build process, this package is not necessary to build the VS Code product and is not why we're stuck on Node 16. We're stuck on Node 16 due to our electron dependency, we're currently working to upgrade to electron 22 which is still Node 16 and then later this year when we upgrade to future electron versions is when we will adopt support for Node 18. Electron upgrades take time as they often break things and have unknown implications.

Thanks for clarifying. I still don't get why @azure/identity is in the open source repository, as it will be installed on most people's computers when it's not really needed. It's 1 more hassle.
