### ISSUE TITLE
File explorer is expanding all root folders in a MR workspace

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#176226]
Steps to Reproduce:

1.  Create a MR workspace file with more than one folder
2. Open the MR workspace

🐛 All top level folders are expanded. This is very slow if there are lot of root folders and also if the MR workspace is in remote

**Comment by gjsjohnmurray** [comment]
@sandy081 how are you creating your MR workspace? By composing an XXX.code-workspace file directly, then opening it? Or by opening the first folder from File\Open Folder... and then using File\Add Folder to Workspace... to add more folders to make it MR? Or some other way?

When I create a MR workspace and save it, then collapse the top-level folders, then exit VS Code, restart and reopen the MR workspace, the top-level folders remain collapsed. But if I then create a copy of that .code-workspace file and open this, the root folders get expanded (and I also get asked the trust question). Presumably the expand happens because my local storage hasn't got any collapse-state record for a workspace with this name, so it defaults to expanding the first level. I suppose VS Code could be changed so it defaults to keeping root folders collapsed for a workspace it hasn't previously seen. But some users might complain about such a change.

**Comment by lramos15** [comment]
> I suppose VS Code could be changed so it defaults to keeping root folders collapsed for a workspace it hasn't previously seen. But some users might complain about such a change.

I think like @bpasero suggested in the duplicate issue, we probably need a limit here. It's nice when you have 3-4 folders to expand but 100s+ can crash VS Code.

**Comment by sandy081** [comment]
> By composing an XXX.code-workspace file directly, then opening it?

Yes
