### ISSUE TITLE
failed github login setting token in crostini

### ISSUE THREAD

**Issue by excelsior091224** [microsoft/vscode#176232]
Does this issue occur when all extensions are disabled?: Yes
I installed VSCode for Arm64 with Gnome-keyring installed on Crostini for Arm64 Chromebook and tried to synchronize settings by GitHub account, but I get the following error.
When I exit VSCode, it logs me out of my GitHub account, and I have to log in again when I restart it.

```
2023-03-06 21:24:11.389 [info] Logging in for the following scopes: user:email
2023-03-06 21:24:11.444 [info] Trying without local server... (user:email)
2023-03-06 21:24:43.733 [info] Exchanging code for token...
2023-03-06 21:24:45.587 [info] Token exchange success!
2023-03-06 21:24:45.626 [info] Getting user info...
2023-03-06 21:24:46.364 [info] Got account info!
2023-03-06 21:24:46.376 [info] Storing 1 sessions...
2023-03-06 21:24:47.569 [info] Getting user info...
2023-03-06 21:24:47.620 [error] Setting token failed: Error: パス /org/freedesktop/secrets/collection/login のオブジェクトにインターフェース“org.freedesktop.Secret.Collection”がありません
2023-03-06 21:24:47.622 [info] Stored 1 sessions!
```

- VS Code Version: 1.76.0
```
バージョン: 1.76.0
コミット: 92da9481c0904c6adfe372c12da3b7748d74bdcb
 日付: 2023-03-01T10:23:02.008Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Linux arm64 5.10.159-20950-g3963226d9eb4
Sandboxed: No
```
- OS Version: ChromeOS 110.0.5481.181(Official Build)(32bit) Crostini Debian GNU/Linux 11 (bullseye) (Linux arm64 5.10.159-20950-g3963226d9eb4)
```
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

Steps to Reproduce:

1. buy ASUS Chromebook Detachable CM3 CM3000
2. install crostini
3. install gnome-keyring and vscode
4. turn on setting sync with github

**Comment by aitor-gomila** [comment]
I would like to note, this also happens in Ubuntu 22.04/WSL 2. Gnome Keyring and libsecret is installed, getting this:

![image](https://user-images.githubusercontent.com/46191980/223164972-639318ba-cd0c-4ef5-97f7-a022bde4c1d0.png)

Also appears to happen to other people, haven't yet found a solution

The docs assume Arch/Pacman, this doesn't make sense at all.
New linux users, most of them will be using Ubuntu/Debian-based, will get errors and have no idea how to fix them, and take a long time before realising what the problem was. We should at least add a note for Debian-based/ubuntu.
![image](https://user-images.githubusercontent.com/46191980/223165636-ffd5eb25-57e3-41e3-b37a-f9876c4e421c.png)

**Comment by TylerLeonhardt** [comment]
When we get to the bottom of this, we should update the docs here:
 https://code.visualstudio.com/blogs/2020/12/03/chromebook-get-started

**Comment by excelsior091224** [comment]
The fact that nothing is found in seahorse suggests that the keyring was not saved in the first place.
When I authenticated, I did not get a dialog to save the keyring password either.
I am also concerned that the URL handler icon stays out in the loading state (it does not disappear until the Chromebook itself is restarted).
![image](https://user-images.githubusercontent.com/44745901/223581079-bd4c231b-b2cd-4044-bd9e-0a723c7aac65.png)
![Screenshot 2023-03-08 08 50 29](https://user-images.githubusercontent.com/44745901/223582289-86518a63-24d5-4c45-a4e1-a7b585a009d5.png)

**Comment by excelsior091224** [comment]
And I tried to make a password keyring with seahorse, but I can't.
```
No such secret collection at path: /
```
Something is wrong, but I don't know what it is.
![image](https://user-images.githubusercontent.com/44745901/223629914-1faff1d5-f619-4bc4-82d4-7fefa743b35d.png)
![image](https://user-images.githubusercontent.com/44745901/223629812-c74b7364-ea47-4e31-8aae-43ba2ebe86e5.png)

**Comment by TylerLeonhardt** [comment]
I believe that there is some set of steps within crostini to get this working, but I don't have a crostini setup so it's hard for me to make suggestions and get to the bottom of this. Perhaps a good first step is to open a question on the crostini-tagged StackOverflow and see if someone with more experience on this platform has some ideas.

**Comment by excelsior091224** [comment]
> I believe that there is some set of steps within crostini to get this working, but I don't have a crostini setup so it's hard for me to make suggestions and get to the bottom of this. Perhaps a good first step is to open a question on the crostini-tagged StackOverflow and see if someone with more experience on this platform has some ideas.

https://stackoverflow.com/questions/75773606/failed-vscode-github-login-setting-token-in-crostini
It has been nearly a week and no one has responded.
Nobody seems to be able to solve this problem.
Useless.
Is there a "don't buy a Chromebook" rule at Microsoft?
The cheapest one only costs about $400, so you should buy one and test it.

**Comment by excelsior091224** [comment]
I finally Powerwashed and reset the device and then set it up and it works properly. Sorry.

**Comment by TylerLeonhardt** [comment]
> Is there a "don't buy a Chromebook" rule at Microsoft?

It's not this (though it would take some time to procure one)... it's that once I _get_ one, I need to learn how to setup this environment (I have zero Chromebook experience). Also, as you've discovered, there's a "right" configuration that didn't work for you initially... and I don't know why that is. I'd have to do a ton of experimenting to figure it out.

That's why, for this kind of bug, it's best to lean on those who do use this more obscure setup because they might has insights into why things aren't working. Sorry I couldn't be more helpful... but I am glad to hear that you managed to get yourself unblocked.

I know it's not the best answer but I hope you can empathize with me. I wanna do what I can, given the knowledge and time I have, to help.

**Comment by TylerLeonhardt** [comment]
@aitor-gomila did you happen to see the https://stackoverflow.com/a/73525513 . I did see that this helped other folks before so I would love it if you gave that a try
