### ISSUE TITLE
AutoSave setting is lost

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#1762]
The now deprecated Auto Save setting isn't preserved by the latest changes to move it into user-settings. That's sort of data-loss and the setting should be populated with my old choice of what I had selected (Auto Save|!Auto Save).

**Comment by bpasero** [comment]
Adding @egamma to this thread.

I see a couple of options:
 * in the message where I educate users how to make the change, offer an action to make this change into the settings.json file
* make this change to the settings.json file automatically
* do not touch the settings.json file but silently carry over the previous auto save setting and use it over the setting defined in settings.json

I do not like 1 and 2 because it is risky to modify user created files (which settings.json is). Option 3 is working but also odd because the UI to disable this previous setting is no longer there (from the File menu).

Maybe a variant of option 3 is to only enable auto save from the previous setting if the user has not modified the setting in settings.json. @aeschli is there a way to find out from the configuration service if a setting was actually set by the user or comes in via defaults?

**Comment by bpasero** [comment]
Went with the approach to migrate this setting into settings.json.
