### ISSUE TITLE
Delay for saving in large files

### ISSUE THREAD

**Issue by MusabDev** [microsoft/vscode#176344]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.76.0
- OS Version: Windows_NT x64 10.0.22621

Steps to Reproduce:

1. Open a large file and do some changes.
2. Save the file.

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by MusabDev** [comment]
Okay. It's working fine without extensions. Thank you! I will have to check which extension is making this issue.
