### ISSUE TITLE
Adopt typescript to use log output channel

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#176479]
I see that Typescript extension is creating an output channel for logging. Recently we have introduced a log output channel that has following advantages

- You can log at different levels (trace, debug, info, warn, error)
- Respects the log level defined at the product level
- User can control the logging level from VS Code UI 
  - For the complete product
  - For only your log
  - Across restarts
- Will make your logs consistent with VS Code logging
- It will also allow you to remove some formatting code

It would be great if you can adopt to the new log output channel. If there are any gaps for adopting, please let me know.

**Comment by mjbvz** [comment]
@sandy081 @dbaeumer  Do language servers now use these log levels instead of having their own settings to enable logging?

**Comment by dbaeumer** [comment]
@mjbvz I have an issue to convert to log channels in the LSP client. What I plan to do is the following:

- keep the old implementation to not break extensions with their settings
- add a new implementation based on log channel. This one will work with log levels only

**Comment by mjbvz** [comment]
@sandy081 Looks great overall for TS!

One quick question: when I log an object, is it possible for the logger to nicely format it automatically? Right now I still have to use `JSON.stringify` it

**Comment by sandy081** [comment]
I believe logger is fomatting the object argument as you expected

https://github.com/microsoft/vscode/blob/d6dae3a640e0564e4ff439651489b1886cf46f4e/src/vs/platform/log/common/log.ts#L82

Is this not what you are seeing?

**Comment by mjbvz** [comment]
@sandy081 Should that line be `a = JSON.stringify(a, null, 2);` so that the object is nicely formatted with whitespace? Right now the objects are printed as a single line json string

Will submit a PR for this

**Comment by mjbvz** [comment]
Actually maybe pretty print objects needs to be a separate option to avoid regressions?

**Comment by sandy081** [comment]
I think so too.

**Comment by DanielRosenwasser** [comment]
Hi all!

Partially documenting the new workload since it's not very explicit from the description.

It looks like for users who were previously relying on

```json5
"typescript.tsserver.trace": "verbose",
```

the new alternative is to

1. Open the Command Palette (<kbd>Ctrl</kbd>+<kbd>P</kbd> or <kbd>Cmd</kbd>+<kbd>P</kbd>)
2. Select `Developer: Set Log Level`
3. Select `TypeScript`
4. Select `Trace`

Is that correct?

Also just confirming - there's no way to persist these settings in a `settings.json`, right?

**Comment by sandy081** [comment]
That's correct. To persist the log level you can change the default log level of the Typescript log. You can do it using the same `Developer: Set Log Level` command but selecting the action to change the default log level - https://code.visualstudio.com/updates/v1_76#_configure-default-log-level

**Comment by jakebailey** [comment]
I gave this feedback in the TS editor sync channel, but I'm not sure that I'm personally a fan as someone who uses this for debugging tsserver problems. Now, I have to go through 4 UI menus to enable it, and by then it's too late to capture the trace, so I have to restart tsserver to get back to the beginning again. And if it doesn't persist, any reloading of my window means I get to do it all over again. If it does persist, now there's a setting not in my settings.json that has a massive impact on performance, because logging the entire tsserver trace is very costly. I accidentally spent a month with tracing enabled as it is, only discovering I had it on when I was cleaning up `settings.json`.

There's definitely no way to configure this via `settings.json`?

**Comment by sandy081** [comment]
I hear you. But I feel the issue is magnified a bit.

Is not it 2 menus excluding opening the command pallette which is obvious for any action/command? Probably might take same time / gestures from before which is open settings > look for setting > update value. You also have an option to set the log level to trace for the complete application that makes it more handy and if you are not concerned about other logs. This reduces one additional click.

You can persist the log level as mentioned here https://code.visualstudio.com/updates/v1_76#_configure-default-log-level and there is better one place UI now to see what log levels are configured. Probably makes it more easy to discover.

One main intention is to streamline and unify the logging in VS Code and make it consistent. It will also help users to configure/discover various logs in the application.

**Comment by jakebailey** [comment]
What I am experiencing is:

- Open command palette.
- Set log level.
- Select TypeScript (I do not want to enable tracing for every extension).
- Click on "Trace", or, make it default.

Reloading without making it the default kept the setting around, which is helpful, though relaunching the editor entirely didn't keep it, which matches my expectation.

I don't mind being able to use a UI to do it. But, now, if I want to capture a trace from the beginning, my options are:

- Restart/reload `tsserver` or the window after enabling trace mode.
- Make "Trace" the default, and hope I don't forget to turn it off. This is exactly the kind of thing I will forget; I legitimately do not remember what I had for lunch yesterday. I am not joking. I will forget that this is set, as I have already done many times before, but a least I eventually noticed the setting in my user JSON.

Frankly, I don't agree that this is more discoverable; I had to know what the command was called ("log level"). I had started by looking for "trace" because (again) I forgot the name overnight and had to refer back to this issue. Before, I could type "typescript." into my JSON settings and auto-complete gives me all applicable settings. I could type "trace" and get a fuzzy match. I can quickly uncomment out the line I keep in my settings to remind me how to do it, and can give people that string in order to get logs from them.

So, like I said, I don't mind being _able_ to use a UI to do it. But, I don't use the settings UI either; I would strongly appreciate a way to achieve the same thing via a JSON setting I can quickly toggle or share.

**Comment by sandy081** [comment]
The default log level is stored in the runtime arguments JSON file 

![image](https://user-images.githubusercontent.com/10746682/232410892-0302ce89-13d1-4d01-af84-87b9c3f572df.png)

in the following format

```json
"log-level": [
		"vscode.typescript-language-features:trace"
	]
```

You can probably directly edit this file you do not like to use UI

I am also open to suggestions for how to make the current flow more easy and discoverable. One idea is to provide a context menu action in the output view to configure log level of a given logger directly.

**Comment by sandy081** [comment]
Thanks for the feedback.

Created https://github.com/microsoft/vscode/issues/180354 for setting log level for an extension even before activating.
