### ISSUE TITLE
[loc][Query][VSCode] Please clarify the context

### ISSUE THREAD

**Issue by mkyjakova** [Microsoft/vscode#17648]
Hi, we have a question from our translator. Can you help please? Thanks!

Source:
Copy to Settings

File Name:
src\vs\workbench\parts\preferences\browser\preferencesEditor.nls.resx

Resource ID:
".resx", 0; "copy"
".resx", 0; "copyToSettings"

Query:
Can you please provide some more context for this string? Where/when does it appear?

**Comment by sandy081** [comment]
This happens when
- Open settings editor
- On a setting edit icon, hover on it
- If it is just a copy to settings file on the right, this message is shown

See the screenshot below

![screen shot 2016-12-21 at 16 16 11](https://cloud.githubusercontent.com/assets/10746682/21394423/e0a8579a-c798-11e6-9505-87f17584359b.png)
