### ISSUE TITLE
terminal links aren't working

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#176412]
I'm hovering and holding cmd here

https://user-images.githubusercontent.com/29464607/223498201-8be9a61c-b004-4178-9da0-2f81bf892f22.mov

**Comment by Tyriar** [comment]
There's a known issue where links can break somehow that's been there for like years now which I haven't figured out a repro yet which is similar to this, but I'm guessing the problem you're seeing is actually https://github.com/microsoft/vscode/issues/176285 since that's meant to be an extension contributed link.
