### ISSUE TITLE
Auto-indentation goes to wrong in arrow callbacks

### ISSUE THREAD

**Issue by mysticatea** [Microsoft/vscode#17645]
- VSCode Version: 1.9.0-insider (04f541160e0d41be95df9a964b1b570aec549157)
- OS Version: Windows 7

Steps to Reproduce:

![wrong-auto-indent](https://cloud.githubusercontent.com/assets/1937871/21379909/e3887d04-c794-11e6-8e98-7d81aa168797.gif)

- In an arrow function as a callback.
- The start of the line is an opening parenthesis.
- I typed a `*` character.

I searched with `"auto indent js is:issue"` then I have not found the issue of this problem.

**Comment by mjbvz** [comment]
This does not seem to be an issue with the Typescript formatter. When debugging the insert of `*`, I see no formatting events from the TS server.

I think the root cause is this line in the `autoClosingPairs` language config for JavaScript:

```json
		{ "open": "/**", "close": " */", "notIn": ["string"] }
```

after removing it, I no longer see this issue. Similarly, after adding a fake entry:

```json
		{ "open": "{&", "close": "&}" },
```

to the `autoClosingPairs`, I now see the same problem when typing `&` on the line.

@alexandrudima can you please take a look at this

**Comment by rebornix** [comment]
`*` is the trigger of the this problem but the root cause is we are finding the matched pair incorrectly.

```
()
   ( 3 + 4 ) |
```

When `*` triggers our pair matching logic, we'll try to see if we are aligning matched pairs correctly. We search in reverse and find the first `)` and then ideally we should find the matched open character, which is `(`. Since they are in the same line, we shouldn't change the indentation.

However, we did the `column` wrong. We did find the last `)` but while trying to find the matching pair, we forgot the existence of `)`, so to that part of code, we are trying to find matching paren in below text

```
()
    ( 3 + 4
```

The `(` in the second line matches `)` in the first line so we align the second line with the first line :(
