### ISSUE TITLE
Streamline find & replace in selections

### ISSUE THREAD

**Issue by ljusten** [Microsoft/vscode#17653]
Find and replace text in a selection is cumbersome. You have to
1) Mark the selection.
2) Hit CTRL+H to open the Find&Replace tool.
3) Remember to click "Find in selection". If you type into the "Find" field the selection is cleared and you have to start over again.
4) Click the "Find" field.
5) Erase previous text.
6) Enter text to find.
7) Hit tab to get to the "Replace" field.
8) Erase previous text.
9) Enter text to replace with.
10) Confirm by click or keyboard shortcut.

This could be streamlined a lot by getting rid of 3), 5) and 8):

- CTRL+H should auto-select "Find in selection" if there is a selection. This gets rid of 3).
- CTRL+H should always focus on the "Find" field (not "Replace") and select the text. I don't think anyone wants to enter the "Replace" text first and reuse the previous "Find" text or enter the "Find" text after the "Replace" text. This gets rid of 5).
- Finally, if you hit tab to jump from the "Find" field to the "Replace" field, the text should be selected, so that you can just start typing. This fixes 8).

OP: Ubuntu Linux 14.04.

**Comment by LC43** [comment]
I have the impression that in earlier versions "CTRL+H should auto-select "Find in selection" if there is a selection."  this was the case. 

i just upgraded from 0.4 and i believe that ctrl+space would replace within the selection only. I can go back and double check if needed.

**Comment by mylowillem** [comment]
They changed the behavior to require you to click the extra button when you want to find in selection to appease users of other editors that required a manual selection of "find in selection". I believe this behavior is common among editors in the MAC world.

Of course if you are coming from a windows or Linux background, the new behavior is extremely annoying. I have previously requested a config setting that will allow us to choose whether or not we want selection to be turned on by default if you have a selection in your document, but alas, for some reason the developers have refused to do. I really don't understand why they can't just give us a setting, even if it does default to selection off. 

If they did add a setting since I last investigated, please post it here.

**Comment by LC43** [comment]
i agree. when Seaching and Replacing, I used to be able to do it just with keyboard. having to use mouse to click on a tiny button when there was clearly a good logic before is insane :/

**Comment by JohannesRudolph** [comment]
Just want to chime in here, I'd greatly appreciate if this gets fixed. It would also align VSCode with the behavior of Visual Studio (if that's of any interest to the team).

**Comment by alexandrudima** [comment]
The problem here is that there are two strong opinions:
* some folks really hate it when find in selection is seeded from the editor selection (i.e. Visual Studio behavior)
* some folks really hate it when find in selection is not seeded from the editor selection (i.e. the current behavior)

The funny story here is that we had the Visual Studio behavior for about 1 year before we flipped the switch to the current one. I think the only way to make everyone happy is to introduce an option.

**Comment by JohannesRudolph** [comment]
Sounds like a perfect plan that would make everyone happy :-)

**Comment by baynes** [comment]
I don't think "find in selection" has to be auto selected when there is a selection. I would just go for having a "replace all in selection" button. It is a lot more intuitive and obvious (it was only by reading this bug that I realised that to do a "replace in selection" that I had to do a "find in selection" first) and also "Replace in selection" is a common idiom in other editors.

**Comment by mylowillem** [comment]
I think by now it's pretty clear that we need the option. I wan't "in selection" to be turned on by default if I have an active selection when I use find or replace,  it just makes sense to me. I understand that other people would prefer it not to be so I've been advocating the for the option since they changed the behavior. What I don't appreciate is people trying to force other people doing it one way or the other.

**Comment by rebornix** [comment]
This issue is solved in master with following changes:

* We can set `editor.find.seedSearchStringFromSelection` as `false` to disable seeding the search string from selection
* We can set `editor.find.autoFindInSelection` as `true` to turn on Find in Selection by default if there is selection in the editor
* If the find input box is empty and there is no selection in the editor (or `seedSearchStringFromSelection` is set as `false` by default), we focus on the Find Input box instead of Replace input box when you do Replace

**Comment by ljusten** [comment]
Can't Replace just ALWAYS focus on the find input box as in Visual Studio, or can you at least add a setting for this? Having it switch behavior based on context is VERY disruptive since it requires you to check where the cursor is before you can type. Also note that you pretty much always have something in your find input box if you ever searched before.

Does editor.find.seedSearchStringFromSelection distinguish between one-line selections and multi-line selections? Currently it seems like one-liners are seeding the find box, whereas multi-liners are not. I can't imagine anyone would turn that off for Search, but I would never want it for Replace.
