### ISSUE TITLE
toggleTerminal shortcut does not work on French keyboard layout

### ISSUE THREAD

**Issue by angexis** [Microsoft/vscode#17651]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:41:20.664Z)
- OS Version: Linux x64 4.4.0-53-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|
|material-icon-theme|PKief|1.1.5|
|vscode-docker|PeterJausovec|0.0.10|
|ActiveFileInStatusBar|RoscoP|1.0.2|
|path-intellisense|christian-kohler|1.2.0|
|githistory|donjayamanne|0.1.4|
|python|donjayamanne|0.5.5|
|tslint|eg2|0.7.1|
|relativepathrefactor|jakob101|0.8.0|
|docthis|joelday|0.3.5|
|Angular2|johnpapa|1.0.2|
|goto-last-edit-location|krizzdewizz|0.2.1|
|cpptools|ms-vscode|0.9.3|
|tsimporter|pmneo|1.2.13|
|gitblame|waderyan|1.3.0|

---

Steps to Reproduce:

1. Type CTRL+² to toggle the terminal as indicated in the shortcuts for a [French keyboard](https://en.wikipedia.org/wiki/AZERTY#/media/File:KB_France.svg) (notice the ² sign above the TAB key)
2. Nothing happens
3. Add
```
    { "key": "ctrl+'",                "command": "workbench.action.terminal.toggleTerminal" }
```
in the keybindings.json
4. The CTRL+² now works properly and toggles the terminal... 
5. But CTRL+' (below the 4 key) does not toggle the terminal as one would expect...

Notes:
1. looking at the binary form of keybindings.json, the single quote is indeed the expected 0x27
2. my ² key works properly otherwise... (I used it to type in this bug report).

**Comment by alexandrudima** [comment]
I have validated that we now (i.e. after PR #22894 aka #17521 -- in tomorrow's Insiders build) appear to behave correctly for this keyboard layout

![image](https://cloud.githubusercontent.com/assets/5047891/24252601/2ad65686-0fde-11e7-8da5-53f766386430.png)

---
### Analysis of default keybinding for `workbench.action.terminal.toggleTerminal`
* `workbench.action.terminal.toggleTerminal` is bound by default to the key code binding `` ctrl+` ``
* `` ` `` can be produced through two scan code combinations: `` Ctrl+Alt+[Digit7] `` and `` Ctrl+Alt+[Backslash] ``. i.e.:
![image](https://cloud.githubusercontent.com/assets/5047891/24252654/5a6edc10-0fde-11e7-9bce-c6bfcdafc3e7.png)
* because `Ctrl` must be used to produce the visual character, the key code binding `` ctrl+` `` is not mappable . i.e. the scan code combo would need to be something like `` Ctrl+ Ctrl+Alt+[Digit7] ``, which we don't support.
* therefore, the action is unbound by default. That is unfortunate, but correct.
* we don't ship with keyboard layout specific default keybindings, that is something you can upvote in #1240

---
### Analysis of pressing `Ctrl+[Backquote]`

![image](https://cloud.githubusercontent.com/assets/5047891/24252736/9f6f1cee-0fde-11e7-9ca0-b69bb2efbd32.png)

We now correctly label it:
![image](https://cloud.githubusercontent.com/assets/5047891/24252754/ad96c95c-0fde-11e7-85ae-f99dc07c31c6.png)

And it is possible to bind it to `workbench.action.terminal.toggleTerminal` via the following keybinding rule:

```
{
    "key": "ctrl+[Backquote]",
    "command": "workbench.action.terminal.toggleTerminal"
}
```

---
This makes me believe the fix in PR #22894 aka #17521 resolves this issue. Please double check in tomorrow's insiders build.
