### ISSUE TITLE
Walkthrough's quick picks close unexpectedly

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#176539]
Type: <b>Bug</b>

Context changes causes images to flicker and, worse, quick picks to close.

- Run `Developer: Reset Welcome Page Walkthrough Progress`
- Open `Get Started with VS Code` walkthrough
- Open step `One shortcut to access everything` or `Quickly navigate between your files`
- Hit the button

🐛 Quick pick closes right after clicking and image flashes.

VS Code version: Code - Insiders 1.77.0-insider (b2ea6aa9fc4c9bebc3d2c2992a891244819dbccd, 2023-03-08T05:22:25.379Z)
OS version: Darwin x64 22.3.0
Modes:
Sandboxed: Yes

**Comment by digitarald** [comment]
Seems as the context changes, which changes focus and closes the quick picks.

**Comment by bhavyaus** [comment]
Working on a fix for this...

**Comment by bhavyaus** [comment]
`syncStatus` fires the context changed event too many times which causes us to reload the media
Ill add a guard to prevent media from being rebuilt if its already open and expanded. 
But there is likely a larger issue to be fixed with the `syncStatus` being fired too many times.

You can turn off settings sync and try the steps described above - no repro.
