### ISSUE TITLE
Incorrect Typescript bracket colorisation 

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode#176618]
Does this issue occur when all extensions are disabled?: Yes/No

Note the red-coloured `>`. Something similar was reported for PHP but thought it's worth bringing this one for TS as well

<img width="552" alt="image" src="https://user-images.githubusercontent.com/16353531/223985193-50270cdd-b1a8-4ab2-8a42-53bccb0b9dcd.png">

```ts
const removals = new Map<string /* foo */, ResolvedKeybindingItem[]>();
```

<img width="1002" alt="image" src="https://user-images.githubusercontent.com/16353531/224057748-f7d8269f-cc54-454f-be7f-f98b677da82a.png">

Version: 1.77.0-insider (Universal)
Commit: 502ac5b213e373026527efdbcea4e669d930d9e1
Date: 2023-03-09T05:22:33.512Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin arm64 22.3.0
Sandboxed: Yes

**Comment by hediet** [comment]
This is actually a typescript grammar bug. However, I think this is probably a known bug.
The feature request for bracket pair colorization that would also fix this issue is https://github.com/microsoft/vscode/issues/176644.

I'll close this issue in favor of the feature request. I don't think the grammar bug is actionable.
