### ISSUE TITLE
Set editor readonly for files that are readonly on disk

### ISSUE THREAD

**Issue by adelphes** [microsoft/vscode#17670]
A small gripe, but one which gets me every time.
I use vscode with some auto-generated source files which are marked on disk as read-only. Because the auto-generated files appear similar to the normal source files in my project, I start to edit them and only discover when I try to save that I'm in the wrong file.

As well as #17621, it would be really useful to have a configurable editor option that prevents any editing of read-only files. Any keystrokes, pasting, etc are simply ignored.

**Comment by MattSutherlin** [comment]
Based on the source control I use and the way I use it, this is currently the biggest hurdle for me in migrating to VS Code.

From my experience, both Visual Studio and Notepad++ just respect file status on disk when it comes to editing.  Sublime does not, but it's API supports a set_read_only function on views.  VS Code currently does not seem to have either of these.

Ideally, VS Code would have a similar API support for plugins to be able to control view edit status, as well as a settings configurable ability to just respect on-disk file status.  I'm personally more concerned with the API aspect, but I see them both as being useful.

**Comment by alexandrudima** [comment]
The editor has an option `readOnly` that would need to be exercised by the workbench => removing `editor` label.

**Comment by DanTup** [comment]
I'd love to see this too. I raised #31410 and based on the responsed implemented a text content provider however it caused a bunch of issues (for ex. Code didn't know that my new scheme was actually files, so paths to breakpoints etc. get messed up) and I've had to revert it. Now my users can edit package sources (equiv of `node_modules`) which is really not ideal.

**Comment by zdovcj** [comment]
I'd love to see this as well. We are using source control using locks. Being able to edit read only files causes only confusion.

**Comment by adelphes** [comment]
@alexandrudima Hi - is there any chance the fix you created in #37496 could be easily applied to this issue. Displaying your "Cannot edit" hint when trying to edit read-only source files would be great way to solve this.

**Comment by gjsjohnmurray** [comment]
@adelphes I think what's needed is for `FileSystemProvider` to be able to indicate readonly as part of what it returns from its `stat` method. I created #73122 to request this. Starting at 1.34 even access to the local filesystem is implemented as a `FileSystemProvider`, so its [stat method](https://github.com/Microsoft/vscode/blob/473af338e1bd9ad4d9853933da1cd9d5d9e07dc9/src/vs/workbench/services/files/node/diskFileSystemProvider.ts#L67) would be able to check file permissions (and the readonly file attribute on Windows) and return the appropriate readonly value.

**Comment by RefinedSoftwareLLC** [comment]
Could this feature also allow your workbench configuration to mark entire folders as read only?

**Comment by johnhubbard** [comment]
Wait, what? The editor should have an option to prevent accidental editing of read-only files. For people who are stuck in older version control systems, the current behavior leads to easy accidents, such as:

1. Accidentally click a key or paste into an editor window that contains a file that is set as read-only on disk.
2. Autosave runs, and prompts a dialog in the lower right.
3. User (me, or maybe you!), in a rush, absent-mindedly (and incorrectly--we are human and prone to mistakes) clicks "overwrite".
4. perforce is now broken hard, because it tracks state via file read-write attributes, and will now fail to update that file. This is a classic, easily overlooked problem that many people have lost much time over, especially in large projects.

**Comment by iacobfred** [comment]
> If you disagree and feel that this issue is crucial: We are happy to listen and to reconsider.

I disagree and feel that this issue is crucial.

**Comment by johnhubbard** [comment]
Yes. I think it's time to get this re-opened and into the queue.

At the very least, a real live person from the core team should comment here, please.

**Comment by bpasero** [comment]
This continues in https://github.com/microsoft/vscode/issues/4873 so no need to reopen?

**Comment by jackpunt** [comment]
While working on #161715, I made [a patch](https://github.com/jackpunt/vscode/commit/7639971f3d0467ec6c923b89bf189bdc653b9969) that propagates stat.mode to set FilePermission.Readonly so textEditorModel.isReadonly() can dynamically sync with FileSystem.Readonly)

That patch (and the branch its in) explicitly addresses the issue of "files which are marked on disk as read-only" being non-editable. 

(which is technically different from #4783, which is about files that are disk-writeable, but intended to be non-editable)

(although it relies on code from #161716 to set `model.isReadOnly()` and present the 'lock' icon...)

**Comment by adelphes** [comment]
@bpasero 
> Duplicate of #4873

I disagree that this is the same as #4873 - simply reading through the comments makes it clear that there are two different scenarios.
4873 refers to a dynamic option which allows a developer to mark files or editors as read-only.

This issue is focused on the read-only state of files in the file system and automatically preventing editing of those files.

**Comment by jackpunt** [comment]
Since this is reopened:
**Would you like me to make a standalone PR for [the patch](https://github.com/jackpunt/vscode/commit/7639971f3d0467ec6c923b89bf189bdc653b9969) mentioned above?**

It simply applies the 'readonly' bit returned in the file-stat  method to set the Permissions.readOnly flag.
(which is already tested/recognized in [textFileEditorModel.isReadonly()](https://github.com/microsoft/vscode/blob/main/src/vs/workbench/services/textfile/common/textFileEditorModel.ts#:~:text=override%20isReadonly(,%7D)
				`this.fileService.hasCapability(this.resource, FileSystemProviderCapabilities.Readonly));`
				
I know you have concerns that other Editor/Models may also be interested in the readonly status; 
But in *this* case, that only means other places should be checking `FileSystemProviderCapabilities.Readonly`

**Comment by johnhubbard** [comment]
Fixing it now sounds good, yes. There is no need to wait for other, more exotic features that happen to be related.

And I see a much higher value-to-effort ratio for fixing this one, too. This is something that is obvious and required; most editors do.

**Comment by jackpunt** [comment]
There's the PR (one-line + import)

**Comment by jackpunt** [comment]
Resolved as follows:

Because `throwIfFileIsReadonly()` needs to not throw for DiskFileSystemProvider [to allow unlock/sudo]
the legacy/historical solution was to remove 'permissions:' from its reported IStat

As a result, the actual file-stat readonly-ness could never be used to signal non-editibility.

To preserve the 'allow DiskFileSystem to bypass throwIfFileIsReadonly()' feature,
while also _including_ FilePermissions.Readonly, we take the simple approach to mark DiskFileSystemProvider with a special feature/capability/permission: `IgnoreReadonly`  (as always I'll defer to the authors for better naming)

That is: instead of _removing_ the standard, righteous Readonly permission indicator for the DiskFSP feature,
we instead _add_ a special permission indicator for DiskFSP (& others that may offer the unlock/chmod/sudo feature)

This fix is 4 lines:
1 & 2: define the new bit in FilePermissions (in files.ts & vscode.d.ts)
3: set the bit in `DiskFileSystemProvider.stat()`
4: check the bit in `throwIfFileIsReadonly()`

This provably gives that same results as before, since the place that relied on a null FilePermission now detects the `IgnoreReadonly` bit.

**Comment by bpasero** [comment]
This landed in our insiders behind a new setting `files.readonlyFromPermissions`. You can give our preview releases a try from: https://code.visualstudio.com/insiders/
