### ISSUE TITLE
Save on focus out doesn't work for new files

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#17729]
* use `"files.autoSave": "onFocusChange",`
* create a new file in the explorer
* make changes, notice it is dirty
* move focus out (editor or vscode)
* 🐛 the file stays dirty

**Comment by bpasero** [comment]
I cannot reproduce with those steps:

![view-picker](https://cloud.githubusercontent.com/assets/900690/21587035/e6664b36-d0d7-11e6-9942-be7fb9535902.gif)

Though since I also have https://github.com/Microsoft/vscode/issues/17430 there must be something weird going on ever since I changed auto save to kick in only when editor focus is lost.

**Comment by bpasero** [comment]
Merging into https://github.com/Microsoft/vscode/issues/17430. please add more info there if you have any.
