### ISSUE TITLE
Broken keyboard shortcut "shift+cmd+e" on OS X El Capitan

### ISSUE THREAD

**Issue by iryston** [Microsoft/vscode#17753]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:42:49.304Z)
- OS Version: Darwin x64 15.6.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|beautify|HookyQR|0.6.2|
|minify|HookyQR|0.3.0|
|vscode-eslint|dbaeumer|1.2.2|
|theme-gruvbox-dark-medium|jdinhlife|0.0.6|
|vscode-icons|robertohuertasm|4.2.0|
|change-case|wmaurer|1.0.0|
|JavaScriptSnippets|xabikos|1.2.0|

---

Steps to Reproduce:

1. Open SideBar
2. Press keyboard shortcut "shift+cmd+e", nothing happens
3. Press all other combinations "shift+cmd+f" etc
4. Press keyboard shortcut "shift+cmd+e", nothing happens

**Comment by bpasero** [comment]
@iryston 
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by iryston** [comment]
@bpasero I'm sorry for this mistake. I have installed [Boom2](http://www.globaldelight.com/boom/index.php) and there was the shortcut  conflict with VS Code.
After disabling shortcuts in Boom2 everything works as expected.
