### ISSUE TITLE
runCommands doesn't work with "type" command

### ISSUE THREAD

**Issue by YKG** [microsoft/vscode#177625]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.77.0-insider
- OS Version: Windows_NT x64 10.0.19044

Steps to Reproduce:

1. Add an entry in user's `keybindings.json`:  
    ```json
    {
          "key": "alt+u",
          "command": "runCommands",
          "args": {
              "commands": [
                  {"id": "type", "command": "type", "args": {"text": "aaa"}}
              ]
          }
    },
    ```
2. Press `Alt + u`

Expected: a string `aaa` added around the cursor in the editor

Actual: got warning message `Found non-callable @@iterator`

It looks like this PR https://github.com/microsoft/vscode/pull/177104 was not correctly implemented

**Comment by ulugbekna** [comment]
Hi @YKG ,

Thanks for filing the issue and your [comment](https://github.com/microsoft/vscode/pull/177104#discussion_r1141653404) on the PR! :-)

This issue should be fixed by #177640 along with various improvements, including renaming `id` to `command`. The fix should be released in tomorrow's insiders.
