### ISSUE TITLE
Setting cursor with scrolling view out of sync after update 1.75(1.74.3 works fine)

### ISSUE THREAD

**Issue by geril2207** [microsoft/vscode#177633]
Type: <b>Bug</b>

After updating VS Code to 1.75.0 i see the out of sync operations where firstly cursor set to a new position and then execute scroll which leads to desynchronization.This out of sync is annoying and I want to stay on 1.74.3. U can check it out in https://github.com/VSCodeVim/Vim/issues/8243 (video).

Steps to reproduce:
1. Install Vim extension, for tests i test code on the image below and there same issue
2. Use `<C-u>` and `<C-d>` or write code to change scroll view with cursor position and u might see a second cursor blinking position in places where you scroll (bottom or top).
3. Downgrade to 1.74.3 On this version actions works in sync(u can see second video in vim issue reference)

![image](https://user-images.githubusercontent.com/62308020/226278116-187d5eca-0081-4273-90a0-a3d8486f6f0c.png)

VS Code version: Code 1.76.2 (ee2b180d582a7f601fa6ecfdad8d9fd269ab1884, 2023-03-14T17:55:54.936Z)
OS version: Windows_NT x64 10.0.19045
Modes: Unsupported
Sandboxed: No

**Comment by alexdima** [comment]
Does this reproduce when disabling all extensions? Press `F1` and then choose `Developer: Reload Window with Extensions Disabled`

![Kapture 2020-07-20 at 15 28 23](https://user-images.githubusercontent.com/5047891/87943040-c3b02a80-ca9d-11ea-847d-5f850fae8f05.gif)

**Comment by geril2207** [comment]
https://user-images.githubusercontent.com/62308020/226331634-94809fb9-b792-47d0-b5c0-6b436c4a1de9.mp4

**Comment by geril2207** [comment]
0.25 Slow, as you can see this two actions executes with little delay (but on 19-24 sec 2 times they executes sync)
https://user-images.githubusercontent.com/62308020/226334128-ac04f489-325e-4827-9b54-b6549501540d.mp4

**Comment by alexdima** [comment]
I think this might be caused by the switch to use `UtilityProcess` by default for the extension host. This was turned on by default with the 1.75 release -- https://code.visualstudio.com/updates/v1_75#_utility-process-for-extension-host . With the `UtilityProcess` API, we are now using a `MessageChannel` for sending messages back and forth between the extension host and the workbench. Before, we would be using a socket. I think the old mechanism had a delay in sending data which would cause that multiple messages would be delivered "at once" to the renderer process.

We could explore delaying writing to the next tick here to get the previous "batching" behaviour -- https://github.com/microsoft/vscode/blob/652134cc225cef86eb9d1bec75bd1b5e9b536ab7/src/vs/workbench/api/node/extensionHostProcess.ts#L131

**Comment by geril2207** [comment]
Would be great to have something like "batching" or maybe will have a command to set cursor and view scroll in one message

**Comment by alexdima** [comment]
Thank you for filling #179368 , looking at the timeline (working in 1.74.3, not working in 1.75.0), this aligns more with https://github.com/microsoft/vscode/commit/1476d6fa71732dd601ba5ca31a228c2988703845

<img width="612" alt="image" src="https://user-images.githubusercontent.com/5047891/230442601-08ea7ff2-bdb3-46af-9f6e-4afb813c803e.png">

So I think this shares the same root cause as #179368. Let's continue tracking there.

**Comment by geril2207** [comment]
@alexdima Thank you for fixing #179368, but current issue still exists. I can reproduce this in 1.78.0.
