### ISSUE TITLE
Typing a closing curly brace in my code indents it

### ISSUE THREAD

**Issue by kumarharsh** [Microsoft/vscode#17764]
- VSCode Version: 1.9.0-insider
- OS Version: Windows 10

Steps to Reproduce:

1. Open any JSX file
2. Type:
```jsx
render() {
  <div name={'vs'}>
  </div>
}
```
then, put cursor just after `'vs'`, and type another curly brace (`}`). Instant indentation which is not expected.

![bug](https://cloud.githubusercontent.com/assets/760112/21450747/8e962148-c91f-11e6-870d-6752d358e17c.gif)

**Comment by egamma** [comment]
Since this can be reproduced with the setting `"editor.formatOnType": false`, this looks like an issue on the VS Code side.

I suspect that our indent rules do not fully handle the `jsx` syntax with curly brackets inside a tag yet:
https://github.com/Microsoft/vscode/blob/master/extensions/typescript/src/typescriptMain.ts#L175

@alexandrudima knows all about the indent rules

**Comment by mjbvz** [comment]
This seems to be fixed in current insiders builds. I believe the work @rebornix has been doing around indentation rules may have been what fixed this.
