### ISSUE TITLE
VS Code allows external file changes to overwrite current file state

### ISSUE THREAD

**Issue by cori** [Microsoft/vscode#17773]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions:

|Extension|Author|Version|
|---|---|---|
|xml|DotJoshJohnson|1.6.1|
|csharp|ms-vscode|1.6.1|
|qub-msbuild|qub|0.5.0|

---

As noted by several people at http://stackoverflow.com/a/30083688/8151 I've had numerous experiences where file changes triggered by source control activity have overwritten the current state of a buffer. In one case this has caused the loss of a great deal of work but since I realized the behavior it's been more of a (significant) annoyance.

Steps to Reproduce:

1. Open a file.
2. Make a few changes
3. Trigger a source control event that overwrites or deletes the file on disk.
4. Depending on the type of file changes, VS Code either silently updates the buffer or pops a warning saying the file can no longer be found and offering to create it. My experiences have generally been with Perforce as the source control provider, but others in the stackoverflow question seem to have experienced it with git as well.

**Comment by BillDenton** [comment]
I also had this issue so reported #14298 (Show a warning when Files modified externally on disk). This is important with silent updating it is very easy to lose changes. I will often edit files in VS Code and also a diff tools (I use WinMerge) so that I can compare my changes with the previous version in SCM (ClearCase). It is essential that I don't lose changes in this process. I would like to be able diff the file so I can merge the changes from the disk into my edited (but unsaved version).

**Comment by bpasero** [comment]
VSCode will never drop a buffer that has changes that are not saved to disk. However, if the changes are saved to disk and an SCM decides to change the file as it is on disk, then Code will show the changed contents. 

@cori @BillDenton please confirm that the files that change are actually not dirty but saved to disk. If that is true then I am not seeing any issue with Code here other than maybe there should be an option to ask the user if the changes from disk should be applied to the opened tab (which is #14298)-

**Comment by cori** [comment]
I have not specifically tested or verified that unsaved buffers are protected from this behavior, but I can confirm that when I *saw* the behavior it was always with saved buffers. Perhaps I was unclear about what I thought the bug was, but what I'm speaking to is the silent updating of an open window without notification or warning.  Is that respect this issue is probably a duplicate of #14298, which I wasn't aware of until @BillDenton commented above.

**Comment by BillDenton** [comment]
I've just checked again:
1. If the changed are saved (i.e. buffer is clean) and the contents is updated silently in VS Code when updated on disk.
2. If the buffer is dirty and the contents is updated on disk nothing will happen until to attempting to save. On save an error messages ("Failed to save ... The content on disk is newer. Click on Compare ..") appears. You can use the Compare file to compare and resolve differences. (BTW I think the Compare file could be improved to allow copying of individual differences between the two sides. I may raise a separate issue for that).

So I think this bug is a duplicate of #14298.
