### ISSUE TITLE
Not getting Jupyter file content based recommendation

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#177781]
Testing #177675

1. Set up a folder with a file `sample.py` which contains the following:
```python
print("HI")
#%%
print("cell")
#%%
print("something else")
```
2. Open the folder with new `--user-data-dir` and `--extensions-dir`
3. Install the Python extension and uninstall all the Jupyter extensions that get installed with it.
4. Reload.
5. Open sample.py
6. At this point I expect to see a recommendation for the Jupyter extension.

**Comment by sandy081** [comment]
Just tried these steps and it is expected. Because the recommendation prompt at step 3 has both python and jupyter extensions. Since you have accepted the recommendation, it is remembered and we do not want to show the same recommendation again if you manually uninstall any of the recommended extensions. For eg we do not recommend python extension if you uninstall python extension.
