### ISSUE TITLE
Replace all on file shall not be shown if none of the matches support replace

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#177808]
Testing #177709

<img width="1014" alt="image" src="https://user-images.githubusercontent.com/10746682/226611531-79a75cfb-48be-4b5c-a881-2518f2a0dd9c.png">

**Comment by rzhao271** [comment]
The file-specific button is gone, but I'm wondering whether the general Replace All button next to the replace inputbox can also be disabled? Otherwise I can do the following:

1. Open a GitHub Issues Notebook.
2. Search for a string specifically only in the output. Add a string in the replace inputbox.
3. Press the replace all button.
4. :bug: It claims that it was able to replace the string.

![The file-specific button is gone, but there's still an enabled Replace All button](https://github.com/microsoft/vscode/assets/7199958/e603d77a-734d-4f81-8e7d-7177c43b2eb6)

**Comment by andreamah** [comment]
created issue for it in https://github.com/microsoft/vscode/issues/184081
