### ISSUE TITLE
when clause not working on .css file

### ISSUE THREAD

**Issue by eleanorjboyd** [microsoft/vscode#177832]
Testing #177738

tried to change one of the when clauses in my package.json of my extension to:

```
        {
          "command": "ctxkey-extension.helloWorld4",
          "when": "editorLangId != .css"
        }
```
and this did not work. I still saw `present 4` on a `.css` file. Not sure if `.css` is an allowed file type but was inferring based on this section in the doc: 
```
Inequality        |      !=      |      "resourceExtname != .js"
```

**Comment by ulugbekna** [comment]
The same: Oh, I'm really sorry, the instruction should've said "it shows in anything that's NOT json - so this works as intended.

**Comment by eleanorjboyd** [comment]
Hi! Just to clarify what happened here is I tried to change the value to `.css` and then it didn't work as intended because `present 4` still appeared even when I was on a `.css` file which given the clause "show `present 4` when the editor is not .css" is false. This is a bit more tangential to your issue since I ended up expanding my testing to ask something outside your parameters so maybe this is a separate bug unrelated to your new changes. Sorry this issue is a bit confusing

**Comment by ulugbekna** [comment]
Oh, should've read the description first, sorry 😅

So the problem in this particular case is that `editorLangId` has value `css` for a CSS file -- that's why your when-clause evaluates to true and you see the command.

<img width="287" alt="image" src="https://user-images.githubusercontent.com/16353531/226668231-644396e7-04d1-42f7-bb68-97dbf400fc75.png">

I use this awesome tool inspect context key values - https://code.visualstudio.com/api/references/when-clause-contexts#inspect-context-keys-utility

--- 

Let me know if you have any questions/feedback; I can also review PRs related to when-clause changes in your extension :-)

**Comment by eleanorjboyd** [comment]
ah understood thank you! And I will send any of when-clauses I need to add to my extension. Appreciate it!
