### ISSUE TITLE
Telemetry opt out link broken on welcome page

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#177833]
Appears the opt out link at the bottom of the welcome page on a new instance of vscode.dev is broken.

Looks like the command `settings.filterByTelemetry` was deleted at some point.

We must fix this for the upcoming release.

**Comment by bhavyaus** [comment]
This has likely been broken for a while now since there have been no changes on the welcome page initialization which removed showing this footer. We never did set the `showTelemetryNotice` when setting up the getting started editor.
https://github.com/microsoft/vscode/blob/f0c6f3ef58e121c898a04877d8361ab52a7e63c5/src/vs/workbench/contrib/welcomeGettingStarted/browser/gettingStarted.ts#L1561

I can set it to be true but the opt out link is no-op without the command. 
Where did `settings.filterByTelemetry` comes from? I look through the git history to find where it went if I have a general idea of where to look.

**Comment by lramos15** [comment]
> We never did set the `showTelemetryNotice` when setting up the getting started editor.

Not sure I understand. This notice is currently shown on a new visit to vscode.dev you can see this by visiting `insiders.vscode.dev` in incognito. We just need to bring back the missing commands. I'm not sure when they were removed.
`settings.filterByTelemetry` should open the settings ui filtered to the `@tag:telemetry`. Is the privacy statement broken too?

**Comment by bhavyaus** [comment]
> > We never did set the `showTelemetryNotice` when setting up the getting started editor.
> 
> Not sure I understand. This notice is currently shown on a new visit to vscode.dev you can see this by visiting `insiders.vscode.dev` in incognito. We just need to bring back the missing commands. I'm not sure when they were removed. `settings.filterByTelemetry` should open the settings ui filtered to the `@tag:telemetry`. Is the privacy statement broken too?

My bad. I misunderstood the question and checked on OSS. You're right that it shows up on insider.vscode.dev and the privacy statement also works.
