### ISSUE TITLE
`Shift`+dragging is cool, but undiscoverable

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#177821]
Testing #177535

It's so nice to be able to shift and drag things into a markdown document. However, I'm not sure how a user would ever discover this given they have to click then press shift then drag. 

Maybe I couldn't find it, but I think there should be a command that let's you do this for discoverability and accessibility reasons.

**Comment by mjbvz** [comment]
You do not have to hold shift before dragging, you can press `shift` at any point while dragging a file. To help users discover this, we also have an overlay which tells users that they can hold shift to drop the file into the current editor instead of opening it

For accessibility, we instead have the  `Markdown: Insert ...` commands
