### ISSUE TITLE
Install Docker extensions says plural but gives singular

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#177888]
Testing #177675

Repro:

- Open vscode with new user data dir and ext dir
- Open a folder with a Dockerfile
- Open the Dockerfile

<img width="350" alt="image" src="https://user-images.githubusercontent.com/2193314/226736490-a3979763-2072-4d22-9d10-faa6e466467a.png">

Clicking install or show only gives a single extension, but I was expecting multiple to show because of the previous notification:

<img width="220" alt="image" src="https://user-images.githubusercontent.com/2193314/226736603-a74793c4-8462-4606-9b6f-e1d52ab6c894.png">

I also found it a little weird how I get this when I open the Docker extension detail view:

<img width="352" alt="image" src="https://user-images.githubusercontent.com/2193314/226737063-fd958d76-f902-43ed-9de1-15909646e179.png">

Any reason this isn't one of the recommended docker extensions installed originally?

**Comment by sandy081** [comment]
Docker recommendation is for the Dockkerfile  and Dev Containers recommendation is because the workspace has .devContainer file configured insider. They are independent and we show workspace recommendations a little later and you might have hit that timing when you opened the extensions view.

Fixing the message for singular and plural.
