### ISSUE TITLE
tasks.json config g++ occur error: no input files in vscode

### ISSUE THREAD

**Issue by wikinee** [Microsoft/vscode#17797]
- VSCode Version: 1.7.1
- OS Version: Mac OS 10.10.5

Steps to Reproduce:

1. I config my tasks.json file, cpplint is via pip install cpplint by myself

```
{
    /*
     * http://code.visualstudio.com/docs/editor/tasks
     * 2016.12.23
     */
    "version": "0.1.0",
    "command": "sh",
    "isShellCommand": true,
    "showOutput": "always",
    "args": [
        "-c"
    ],
    "tasks": [
        {
            "taskName": "cpplint",
            "suppressTaskName": true,
            "args": [
                "cpplint --verbose=0 --output=vs7 --linelength=80 ${cwd}/*.*"
            ]
        },
        {
            "taskName": "g++ -std=c++11 -Wall ${file} -o ${fileBasenameNoExtension}.o",
            "args": [
                //"g++ -std=c++11 -Wall ${file} -o ${fileBasenameNoExtension}.o"
            ]
        }
    ]
}
```
2. I have a problem is about taskName "g++", when I enter

```
"taskName": "g++"
"args": ["g++ -std=c++11 -Wall ${file} -o ${fileBasenameNoExtension}.o"]
```
and press `cmd+p` , type `task g++` , it will return a error:

clang: error: no input files

But, cpplint (you need $ pip install cpplint by youself) also have no parameter, it's work well, why? THX.

**Comment by egamma** [comment]
@wikinee thanks for you detailed description. The issue is really a question on how to configure tasks for g++. Our suggested way for asking such questions is to use stackoverflow with the tag `vscode`. Asking a question on Stackoverflow reaches the broad VS Code user community. Please, see our [guidelines](https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#before-submitting-an-issue).
