### ISSUE TITLE
Provide help link in 'Connect to'

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#177940]
Testing #177702

Should the connect to list also include a link to documentation about remote development? Without this, the options we show may be confusing to new users

**Comment by bhavyaus** [comment]
@bamurtaugh is this a good link to use for directing users via the help link https://aka.ms/vscode-remote/start ?

Ideally we would point users to the getting started documentation contributed by each extension but we only have that information after install whereas the remote picker is showing this help link before that. 

Here is what the help link button looks like (the link also has a tooltip which reads "Learn More" but isn't captured in the video): 

https://user-images.githubusercontent.com/25044782/227121998-9cc12328-c13b-41d5-a2a1-cc7e421cb39f.mp4

Let me know if you have any feedback.

cc: @joyceerhl

**Comment by bamurtaugh** [comment]
@bhavyaus in the video you share above, it looks like each extension could have its own link to docs via the (i). Could we link to each extension's page in VS Code docs? i.e. https://code.visualstudio.com/docs/remote/ssh for SSH, https://code.visualstudio.com/docs/remote/tunnels for Tunnels.

If we were only to provide one link to docs overall, I'd suggest https://code.visualstudio.com/docs/remote/remote-overview (close to the aka.ms link you provide but a bit higher up on the page so that users get the overview of remote dev).

**Comment by joyceerhl** [comment]
+1 to what Brigit said, I think we should have an info entry per item.

**Comment by sandy081** [comment]
Moving this to next milestone as part of issue tracking and cleaning for the current milestone as we are close to the release.

**Comment by meganrogge** [comment]
I don't see an info entry per item

**Comment by bamurtaugh** [comment]
Worked for me, thanks for the steps!
