### ISSUE TITLE
Missing hover info on "Connect to GitHub Codespaces" under "connect to..." picker 

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode#177955]
Testing #177702

When I don't have any of the remote extensions installed, I see a "Also installs dependencies - <ExtensionName>" when hovering over all the items, expect the Connect to GitHub Codepsaces one. Is that intentional?

I was also wondering if there could be a more descriptive text for hover  (e.g. "Install dependencies and connect")?

**Comment by bhavyaus** [comment]
The Codespaces extension does not define any dependencies which is why it didn't show up. 

I love the recommendation "Install dependencies and connect" but one of the feedback items from the team was to ensure we're showing information about all the extensions we might download. 

Having said that, the extensions page also does not show all the dependencies when we hit "Install". It's up to the user to open up the extensions pack. So I'm leaning towards not having a tooltip at all. 
cc @bamurtaugh

**Comment by bamurtaugh** [comment]
I like that we show which other extensions each path might download. For Codespaces, could there be a hover like `Installs the Codespaces extension` or `Installs the Codespaces extension and no other dependencies` (not sure the best wording). Or if you add "Connect" to all of the hovers, they could look something like:
- `Install dependencies (list dependencies here) and connect` for extensions with other dependencies
- `Connect` for extensions without other dependencies

**Comment by sandy081** [comment]
Moving this to next milestone as part of issue tracking and cleaning for the current milestone as we are close to the release.

**Comment by bhavyaus** [comment]
Leaving this experience as is. We have also added a `Learn more` info link in the picker to help users. We have also not seen any user issues related to this. Closing this issue.
