### ISSUE TITLE
No option to Connect to a RemoteHub repo when connected to a remote

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#177944]
Testing #177702

![image](https://user-images.githubusercontent.com/2644648/226775096-4dd5d1c1-a4da-4b55-8120-5ffb454446e7.png)

While connected to a Tunnel, I don't see the option to Connect to... a Remote Repository, even though I have those extensions installed.

**Comment by bhavyaus** [comment]
Fixed in latest insiders.

**Comment by TylerLeonhardt** [comment]
Still noting seeing GitHub Repos options here when connected to a Tunnel... even though that extension is installed


![image](https://user-images.githubusercontent.com/2644648/227387977-933282a1-8184-4c49-9e81-0e033928cdda.png)

**Comment by bhavyaus** [comment]
Same repro from Codespaces.
Remote Repositories commands do not appear to be available when tunneled in -
1. Remote Repositories commands are no-op from the command palette.
2. Remote Repositories actions are no-op from the remote explorer

**Comment by joyceerhl** [comment]
This is because the open remote repo picker depends on the git-base extension, and in a remote window, the git-base extension is already running on the remote agent because it is also a dependency of the git extension.

There are at least two ways to fix this, neither of which I think is appropriate to fix for March:
- easy but duplicates code: break dependency on git-base extension
- needs exploration: allow extensions to acquire and execute the api of other extensions which do not run in the same extension host
