### ISSUE TITLE
Disable first start browser opening

### ISSUE THREAD

**Issue by BarryWheeler** [Microsoft/vscode#17809]
Hi!
Why VSCode needs to open web browser at its first start? It is very annoying when it doing this :(
May be it is a good idea to remove such behaviour?

**Comment by seanmcbreen** [comment]
Hi @BarryWheeler 

Apologies for the delay in replying here - we are all just getting back up to speed post the holiday break.

We agonized over when we open the documentation page in VS Code on a fresh install for a while within the team.  Our concern was that it would be a distraction.  That said we did have a clear goal, we did this to help people quickly learn more about the product (via the videos and documentation) and therefore hopefully increase a new users chance of success.

We experimented here a little (first we had a page in product - but people wanted an open editor, then we landed on docs, then on videos and right now we continue to experiment).   Our over-riding goal is to help new users be successful (it only occurs on a fresh install) since we did add this we have seen improved results (more new users learn more), so it seams to be working.  We certainly would not want to do this on every open - that would be incredibly frustrating.

So for now our plan it to continue to experiment to help new users be successful.  That said as we come up with fresh ideas we will take this feedback into consideration.

Thanks for taking the time and Happy Coding!
Sean

p.s. closing this issue for now - but feel free to re-open if I did not provide sufficient context.
