### ISSUE TITLE
Proposal: Usability Improvement Suggestions

### ISSUE THREAD

**Issue by SetTrend** [Microsoft/vscode#1780]
The approach of maintaining a task using two different files seems more pain than necessary to me. May I suggest a few improvements to the way projects are administered in VS Code:
<br/>
### Add `npm install` context menu to package.json file

When cloning a project from GitHub or after editing the `package.json` file in VS Code, no Node module is getting downloaded. So currently it's required to leave VS Code and execute `npm install` in a command prompt.

I suggest to add a context menu item to the Explorer when a `package.json` file is selected to simplify this task. The context menu item is suggested to run `npm install` from the directory of the `package.json` file:

![package](https://cloud.githubusercontent.com/assets/9283914/12097398/d07d5402-b31b-11e5-961a-c3cb0e03769d.png)
<br/>
### Use `pragma comment` for running tasks in VS Code:

Maintaining two distinct files to have tasks get run in VS Code seems more administration pain than necessary.

I suggest to support a pragma comment preceding a task, fulfilling the same purpose as the `tasks.json` file does:

```javascript
var gulp = require("gulp");
var ts = require("gulp-typescript");

//# task { isShellCommand: true, isWatching: true, problemMatcher: "$tsc" }
gulp.task("tsc", function () { gulp.src().pipe(ts).pipe(gulp.dest()); })
```
(The `tasks.json` file may still be applied, e.g. for legacy/compatibility purposes or if a complex task configuration needs to be set. If both, a `# task` pragma comment and an entry in the `tasks.json` file existed for a task, any of the two definitions would prevail.)

<br/>
### Add `Run Task` context menu to any `.js` file containing a `# task` pragma comment

Currently, running a task requires much typing.

I suggest to add a context menu to Explorer for any `.js` file containing a `# task` pragma comment so tasks can easily be browsed for and a task can simply be started by two clicks:

![run task](https://cloud.githubusercontent.com/assets/9283914/12098333/f1cc0666-b321-11e5-8f50-cfc10fae09db.png)

The tasks in the list should be alphabetically sorted and the first task name letter should be used for the mnemonic, so starting a task could be as easy as `CTXT, T, L` for "less" or `CTXT, T, T` for "tsc" in the above screen shot.
<br/>
### Add option to automatically start tasks
Whenever a project is opened in VS Code, which is indicated by the following preconditions:
  * a folder gets opened which contains one or more `.js` files
  * any of those `.js` files contains one or more `# task` pragma comments
  * any of those `# task` pragma comments comes with an `autoStart: true` property set

... then the tasks marked with `autoStart: true` should automatically be executed.

Here's a screenshot depicting how the `autoStart: true` property is suggested to be applied:

![auto run 1](https://cloud.githubusercontent.com/assets/9283914/12098517/2161e340-b323-11e5-854d-c4357cef5c60.png)
<br/>
Depending on user/workspace settings, a confirmation dialog might be displayed before the tasks are automatically getting started:

![auto run 2](https://cloud.githubusercontent.com/assets/9283914/12098540/3f001566-b323-11e5-8381-5af2a884aacc.png)

**Comment by rhires** [comment]
I would suggest/recommend that you list these items separately, so that they can evaluated/commented on separately.

**Comment by roslanr18** [comment]
User@gmail.com

**Comment by egamma** [comment]
CC @dbaeumer

**Comment by SetTrend** [comment]
I have now created a number of sub issues, each mentioning my proposals seperately:

* #1788 - Add npm install context menu to package.json file
* #1789 - Use "pragma comment" for running tasks in VS Code
* #1790 - Add "Run Task" context menu to any ".js" file containing a "# task" pragma comment
* #1791 - Add option to automatically start task runners' tasks
* #1792 - Add mnemonics to context menu items

**Comment by dbaeumer** [comment]
@SetTrend thanks for opening the separate issues. I will close this one.

**Comment by roslanr18** [comment]
You have been invited to the following event.

Title: Samsung
When: Thu Feb 4, 2016 10am - 11am GMT (no daylight saving)
Where: http://opensource.samsung.com
Calendar: rnordin95@gmail.com
Who:
     * roslan nordin - organizer
     * licensing@fsf.org
     * Gmail Team
     * prime@gmail.com
     * lino lin
     * Microsoft/vscode
     * ezam fareeza
     * Triton Lite
     * candycrushjelly.techhelp@king.com
     * vivian hu
     * spw-play-support@cervomedia.com
     * vscode@noreply.github.com
     * hrydgard+ppsspp@gmail.com
     * support@npmjs.com
     * nizam ezam
     * Roslan Nordin
     *  
reply@reply.github.com
     * Candy Crush Jelly Saga
     * Inc.
     * Marketing
     * raimi nordin
     * kadz kadir
     * KingRoot Studio
     * Rasminah Rakib

Event details:  
https://www.google.com/calendar/event?action=VIEW&eid=MW84b3MwMGlrMjU1bzNsNTV1b3VpY2ZuZjggcmVwbHkrMDBmMzJmMTE3NWVjNmMwNGZhYmI4ZTI3ZjhlOGZmMDI1ODFiZmVmNTE2Y2ZlMTA1OTJjZjAwMDAwMDAxMTJhMmQxNWE5MmExNjljZTA3NzE1Yzk1QHJlcGx5LmdpdGh1Yi5jb20&tok=MTkjcm5vcmRpbjk1QGdtYWlsLmNvbWY3NDIzOGQ2YTZmNzUxZjE5ODZjNTE5Yzc4NTIwMzBlOTdiYTczYmE&ctz=UTC&hl=en

Invitation from Google Calendar: https://www.google.com/calendar/

You are receiving this courtesy email at the account  
reply@reply.github.com  
because you are an attendee of this event.

To stop receiving future updates for this event, decline this event.  
Alternatively you can sign up for a Google account at  
https://www.google.com/calendar/ and control your notification settings for  
your entire calendar.

Forwarding this invitation could allow any recipient to modify your RSVP  
response. Learn more at  
https://support.google.com/calendar/answer/37135#forwarding
