### ISSUE TITLE
Highlighted quick input option is not announced

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#178163]
When typing in the text field, the number of results is announced by NVDA but not the highlighted option. This can be a productivity killer. I believe the announcement of the highlighted option is the most important piece of information while typing. the number of results is irrelevant at this point. It becomes important when the user starts to navigate with the arrow keys, and at that time the screen reader takes care of it.

Version: 1.77.0-insider (user setup)
Commit: 6fe3014566312d1e2a41925c78201b8e8490fe77
Date: 2023-03-23T10:21:45.873Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes

_Originally posted by @rperez030 in https://github.com/microsoft/vscode/issues/166920#issuecomment-1481498386_

**Comment by connor4312** [comment]
Following up during verification: when typing, there is no highlighted option. So I'm not entirely sure what the intended behavior is here.

**Comment by meganrogge** [comment]
> Following up during verification: when typing, there is no highlighted option. So I'm not entirely sure what the intended behavior is here.

This is as a result of the fix for https://github.com/microsoft/vscode/issues/166920. It's a tricky dilemma

**Comment by rperez030** [comment]
Personally, I would strongly suggest to roll-back the fix until a more global solution becomes possible. between that and the unnecessary announcement of results while typing, the experience of using the command palette can be perceived as significantly poorer for screen reader users. Being able to simply start typing a command and press Enter to execute is something I find very powerful as a keyboard user. It is possible that this fix is also affecting other areas in the editor. For example, when using CTRL +G to navigate to a specific line, it is no longer possible to type the number and press Enter to confirm, and this only happens when screen reader mode is enabled.

**Comment by meganrogge** [comment]
@rperez030 I agree with your concerns and created this issue about that here. https://github.com/microsoft/vscode/issues/177476

we should have a setting for this

**Comment by TylerLeonhardt** [comment]
We can't have a setting if that behavior is unaccessible and the only reason it is different in the first place is because the non-accessibility mode experience is not accessible.

**Comment by TylerLeonhardt** [comment]
The only solution forward is to make they non-accessibility mode experience accessible... but it is unclear if the platform has what we need to accomplish this.

**Comment by TylerLeonhardt** [comment]
I have captured the "try using something other than `aria-activedecendant` here: https://github.com/microsoft/vscode/issues/176081 

Let's have that issue be the center point of what this should all look like.
