### ISSUE TITLE
If rename file, a zero-length file is created at old name

### ISSUE THREAD

**Issue by dtgriscom** [Microsoft/vscode#17829]
- VSCode Version: 1.8.1 (1.8.1)
- OS Version: OS X 10.10.5

Steps to Reproduce:

1. Click on file in Explorer pane to select the file
2. Press return to go into rename mode
3. Type in a new name
4. Press RETURN to save new name

Results:
1. File will be properly renamed
2. After a few moments, a new empty file will be created at the old file location.

Comments:
- Problem DOES occur if move file into directory by dragging in the Explorer pane
- Problem does NOT occur if rename using native command line
- As this problem is so obvious, and I can find no reports of it, I suspect an environmental issue, specifically a VSCode extension. I currently have the following installed:
  - Complete JSDoc Tags 0.0.2
  - Document This 0.3.5
  - ESLint 1.2.2
  - Regex Previewer 0.0.7
  - TODO Parser 1.8.3
  - TSLint 0.7.1

Happy to provide further information or do additional tests.

**Comment by bpasero** [comment]
@dtgriscom 
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by dtgriscom** [comment]
Thanks for the help. I tried `code --disable-extensions` and tested, and the problem was gone. However, when I reenabled extensions (`code --enable-extensions` worked, although there's no documentation whatsoever for that), the problem was still gone. I'm going to call this "Not VS Code's Problem" and close it; I'll reopen with more details if it happens again.
