### ISSUE TITLE
Deprecate "Provide Feedback" in remote explorer help

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#178246]
This is pretty nitpicky, but I notice that if I say "Provide Feedback" in the remote explorer, the first entry for codespaces takes me to a github community page. However, since the icon "Provide Feedback" was a twitter icon, I thought that all options would take me to twitter. Is there a more generic icon that we can use?

<img width="216" alt="image" src="https://user-images.githubusercontent.com/31675041/227589815-71d5efb4-7292-4380-a0a6-713f1ce5be7e.png">

**Comment by bamurtaugh** [comment]
If this is for Codespaces, I believe the GH Discussions is still the preferred spot: https://github.com/orgs/community/discussions/categories/codespaces. I also think it makes sense to combine Provide Feedback & Report Issue into one node!

**Comment by alexr00** [comment]
Sounds good to me!

**Comment by joyceerhl** [comment]
Tasks:
- [ ] Remove `Provide Feedback` from remote help
- [ ] Remove `Provide Feedback` entries for 
	- [ ] Codespaces
	- [ ] Remote Repos
	- [ ] Remote Tunnels
	- [ ] Remote SSH
	- [ ] WSL
	- [ ] Dev Containers

**Comment by joyceerhl** [comment]
Slight edit--Codespaces' Provide Feedback and Issues links go to the GH discussions tracker, but Codespaces' Report Issue command opens the builtin issue reporter prefilled to the GitHub Codespaces extension. Clicking the `Create on GitHub` button in the issue reporter then inexplicably opens the Windows file explorer.

<img width="387" alt="image" src="https://user-images.githubusercontent.com/30305945/227645661-0b34c44d-0fcc-4814-8bf7-582d822e5160.png">


I believe Codespaces actually wants issues to be reported in GH discussions instead of the VS Code issue tracker, so what I'd suggest is:
- we introduce a new optional property `reportIssue` which Codespaces would point to their GH discussions tracker
- all other remotes would not provide this property
- we would not show the Provide Feedback item anymore since Report Issue will do the same thing

cc @jkeech for feedback on the proposed change to the Codespaces extension

**Comment by jkeech** [comment]
@joyceerhl those changes sound good to me 👍
