### ISSUE TITLE
Suggestion ranking should honour order

### ISSUE THREAD

**Issue by Spown** [Microsoft/vscode#17836]
- VSCode Version: 1.8.1
- OS Version: win10x64

Case: 
```js
var path = require('path');
```
when I type "path." I get
![](https://dl.dropboxusercontent.com/u/105338698/ShareX/2016-12/Code_2016-12-27_00-46-52.png)
next I want to select "parse" method so I hit "p" and get
![](https://dl.dropboxusercontent.com/u/105338698/ShareX/2016-12/Code_2016-12-27_00-47-50.png)

Notice that the list is scrolled to the bottom, the Intellisense stuff remains on the top.

Problem:
``path`` is definitely typed and Intellisense serves all it's properties and methods. Intellisense' stuff is already on the top and it is shown immediately after I hit ".". It's quite unlikely I'll ever need access anything else. So why would VSCode suggest otherwise? It would be ok if this auto-generated stuff would stay on the bottom of the list, just like it does, but why is it preferred?

I tried
```
"editor.snippetSuggestions"
"editor.quickSuggestions"
"editor.quickSuggestionsDelay"
"editor.suggestOnTriggerCharacters"
"editor.wordBasedSuggestions"
```
but nothing seems to have an effect in this regard.

thank you.

**Comment by jrieken** [comment]
this is TypeScript/JavaScript always suggesting *all* symbols found in the project

**Comment by Spown** [comment]
@jrieken so?

**Comment by mjbvz** [comment]
@jrieken I believe returning all symbols is by design for JS document. In this case, we generate the completions for the `path` module and give then a weight of `0` while everything else has a weight of `1`.

![screen shot 2017-01-04 at 6 27 19 pm](https://cloud.githubusercontent.com/assets/12821956/21667185/9ddc1686-d2ab-11e6-8c47-69171a474501.png)

The problem seems to be that after typing the first letter, `p`, this order is not respected when determining the current selection. In this case, we jump to `path` even though `parse` should be given priority. 

Is this the expected behavior? Do we need to do something differently on the TS side to mark certain completions as preferred?

**Comment by jrieken** [comment]
There are two things: *Sorting* and *Matching (the current word against all suggestions)*. Because completions come from multiple sources, there is only a global sort order (alphabetically). That order can be influenced with the `label` and `sortText` of a completion. What happens next is that we *pre-select* the best matching word. That [algorithm](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/suggest/common/completionModel.ts#L169) takes into account: number of case-sensitive matches, number of case-insensitive matches, first match index, and characters not matching. The last condition has the side-effect of preferring shorter words (`path` vs `parse`).

**Comment by Spown** [comment]
If you ask me, the whole suggestion sorting needs a little overhaul. For example Snippets are the only thing that can be ordered via `editor.snippetSuggestions = top|bottom|none``; ``editor.wordBasedSuggestions = boolean`` can only be turned on and off; Definitely Typed suggestions have no control whatsoever.

I suggest for both ``editor.snippetSuggestions`` and ``editor.wordBasedSuggestions`` to become polymorphic, i.e. accepting their old values as before (string and boolean respectively), but additionally (alternatively) accept a Number that would determine both the order in which to place them in the list (lesser - higher, i.e. 0 - top) and also the preference while selecting items. That would imply there is a need for a new option for the Definitely Typed, like ``editor.typingsSuggestions`` or ``editor.intellisenseSuggestions`` that would abide by the same rules. So that if I had
```
"editor.typingsSuggestions": 0,
"editor.snippetSuggestions": 1,
"editor.wordBasedSuggestions", 2
```
They would show in this order and as long as the typed in part of the word is matching something from the group with index 0 - it would select it even if there are better and/or shorter matches in the groups with a higher indexes.

**Comment by Spown** [comment]
Another alternative - a dedicated option, that would take precedence over the old ones if defined:
```
"editor.typingsSuggestions": [
    "typingsSuggestions",
    "snippetSuggestions",
    "wordBasedSuggestions"
]

**Comment by jrieken** [comment]
@Spown You are talking about *sorting*, this issue is about *matching*. Also, note that word based suggestion don't show when there are 'typings suggestions'.

**Comment by jrieken** [comment]
You are confusing word based suggestion (those with the ABC-icon) which we compute as the last resort in the lack of other results with JavaScript always throwing in names of other symbols. In that list you will not find words from comments or strings

**Comment by Spown** [comment]
> One issue, One topic
but it is one issue. I suggest that the said preference would be controlled through the same config option(s) as the the one(s) that control the ordering in the list

**Comment by kumarharsh** [comment]
Related: https://github.com/Microsoft/vscode/issues/17796

**Comment by kumarharsh** [comment]
@jrieken there is also the issue that the matching doesn't seem to be working perfectly, as you can see in the screenshots in the related issue. Many times, vscode matches words which I have typed once over more obvious choices such as those offered by intellisense *or* more frequent words. This inevitably makes me type the whole word. 😞

**Comment by mjbvz** [comment]
@jrieken Thank you for clarifying the behavior.

TypeScript only returns all these extra suggestions in JavaScript files, not in TypeScript files. I believe this is by design, as we generally cannot fully determine the complete set of properties that are valid on a JavaScript object, so we play it on the safe side by returning all symbols in the current context.

I think that the matching logic could be improved in this case by also weighing the original sort order, but I'm not sure exactly how this would fit with the existing algorithm. The number of characters not matching is what is responsible for the poor ordering in the example and this is something we would still want to take into account when displaying the results.

Given that we likely want to keep the more comprehensive JavaScript suggestion behavior, is there anything else we can do in the TS extension currently to improve the matching or would this have to be changed within VSCode? @waderyan You've looked at how other editors handle matching JavaScript suggestions, any thoughts on this?
