### ISSUE TITLE
Gutter click action removes *all* breakpoints on a line

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#178595]
1. Set a breakpoint on a line, then set an inline breakpoint once the locations are revealed
2. Click the line again
3. All breakpoints in the line are removed, instead of just the line breakpoint. The inline breakpoint should be left intact 🐛

**Comment by joyceerhl** [comment]
This seems to repro in stable, so not a regression from the context menu changes this iteration AFAICT (unless I've misunderstood the scenario):

https://user-images.githubusercontent.com/30305945/228630958-d87eee01-43b7-4f85-be3a-f01ac3f526ea.mp4

And also seems like it might have always been this way:
https://github.com/microsoft/vscode/blob/666e4172979f1414efdf83979efdbb445a21051c/src/vs/workbench/contrib/debug/browser/breakpointEditorContribution.ts#L303

Though, maybe worthwhile to change to the following since I imagine losing the inline breakpoints on a global gutter action can be frustrating and unexpected:
```ts
		const column = e.target.position.column;
		const breakpoint = this.debugService.getModel().getBreakpoints({ uri, lineNumber, column })[0];
		if (breakpoint) {
			this.debugService.removeBreakpoints(breakpoint.getId());
		}
```

**Comment by connor4312** [comment]
Yea, apologies, I was just looking at this and see it wasn't touched by the context menu stuff.

I'm pretty sure this didn't used to happen 🤔 and if it did, then it shouldn't.

**Comment by connor4312** [comment]
Actually, this is the same as when devtools does. So I think this behavior is fine, but the issue is that we don't show any inline decoration for the breakpoint if it's on the first non-whitespace character of the line. I will make a change so that we do show them inline if there's more than one breakpoint per line so that they can be addressed individually.
