### ISSUE TITLE
Extensions' icons on activity bar are not being highlighted on mouse over

### ISSUE THREAD

**Issue by AlbertoFabbri93** [microsoft/vscode#178536]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 
Version: 1.76.2 (system setup)
Commit: ee2b180d582a7f601fa6ecfdad8d9fd269ab1884
Date: 2023-03-14T17:55:54.936Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes
- OS Version:
Edition	Windows 11 Pro
Version	22H2
Installed on	‎28 ‎Sep ‎2022
OS build	22621.1413
Experience	Windows Feature Experience Pack 1000.22639.1000.0

Steps to Reproduce:

1. Move the mouse pointer over an extension icon on the activity bar, see gif:

![Activity bar](https://user-images.githubusercontent.com/51910894/228384417-02113f24-9f24-4385-8f87-24325d20fc30.gif)

**Comment by sandy081** [comment]
It is because those icons cannot be highlighted.

**Comment by AlbertoFabbri93** [comment]
Ah ok, so it has always been like that... I never noticed it before.

**Comment by daviddossett** [comment]
I think this is because these are simple SVGs contributed by the extension, which don't allow us to manipulate styles like color on hover/focus/etc. We can only control our own theme icons internally.

@sandy081 @aeschli I see this happening a lot wherever extensions contribute SVGs and it feels like a paper cut from a user's POV. It's a shame that we ask them to supply `dark` and `light` variations too. Is there anything we can do like automagically changing SVG `fill` values to make these respond to themes? I assume it's not that simple else we would have done it already.

**Comment by aeschli** [comment]
We can change the color of an URI-icon by rendering it as `mask`
https://github.com/microsoft/vscode/blob/c4495f0c4956bfc9de4ffb9e6baa8be2f18a9a0e/src/vs/workbench/browser/parts/activitybar/activitybarPart.ts#L652

Looks like we missed a css rule for the uri-icon case when being hovered. I created a PR: #178684
