### ISSUE TITLE
[Feature request] A switch in configuration to disable/enable the hiding behavior in Explorer filter.

### ISSUE THREAD

**Issue by xc1427** [microsoft/vscode#178588]
# Background
The behavior of Explorer filter has been changed since the merge of #167047. Previously the visually unmatched files/folders were hidden, which can be observed in this release note https://code.visualstudio.com/updates/v1_70#_tree-find-control . PR #167047 by @gjsjohnmurray makes the hiding not executed any more, which I understand the intention is to mitigate #66971, in the meantime makes this feature unusable in regards to searching in large number of files, e.g., node_modules unfolded.

See following example. I want to search `antd`. But I have to do large scrolling to get what I want.
https://user-images.githubusercontent.com/5611770/228592846-d844a7b4-a479-409c-bc99-7d0bc21ed04d.gif

# Feature request
A switch in configuration to disable/enable the hiding behavior.

# Extra notes
I would think the Explorer filter is designed to do _**visual**_ search, which means the user should not care about if a subfolder's content is resolved. If the user wants to do a thorough search, `Cmd-P` is right there exactly for that.

**Comment by gjsjohnmurray** [comment]
> @gjsjohnmurray Any thoughts

@lramos15 I'm not opposed to a setting, maybe `workbench.list.filter.includeUnresolvedFolders` with a default of `true`. But I wonder how many other users have been inconvenienced by the change.

**Comment by ADTC** [comment]
While I really appreciate the effort to include unresolved folders as per my own suggestion, I do think now that it was hastily released, breaking existing behavior without any configuration. It should have been released with a configuration defaulting to `false` (thus not breaking behavior) and with a notification that the feature exists, so that those who want it can turn it on. Then telemetry could help determine whether we should eventually turn it on by default (set to `true`) for new installations.

**Comment by ADTC** [comment]
@xc1427 does it not jump to the next result if you press Return key in the search box? That could be a workaround to avoid scrolling. (On mobile now, can't test it myself yet.)

**Comment by gjsjohnmurray** [comment]
> But I have to do large scrolling to get what I want.

I just submitted PR #180078 to improve this situation by adding keyboard navigation between matches.

**Comment by xc1427** [comment]
> @xc1427 does it not jump to the next result if you press Return key in the search box? That could be a workaround to avoid scrolling. (On mobile now, can't test it myself yet.)

It jumps to the nearest result. But when I press Return again, it triggers "rename" functionality. So this cannot mitigate scrolling.

**Comment by gjsjohnmurray** [comment]
> It jumps to the nearest result. But when I press Return again, it triggers "rename" functionality. So this cannot mitigate scrolling.

NI, but my PR will.

**Comment by lramos15** [comment]
I don't think we will be introducing a setting here as it will involve maintaining both features. Clearly many users believe that the filter is an actual filter rather than a visual one as evident by https://github.com/microsoft/vscode/issues/66971

It was unintentional to break people's muscle memory with this change, but undoing it would just break people's muscle memory once again. During issue grooming maybe @joaomoreno will have some time to take a look at @gjsjohnmurray's PR which will add keyboard navigation to assist with this case.
