### ISSUE TITLE
vscode.workspace.findFiles() case insensitive on Windows ?

### ISSUE THREAD

**Issue by buzzzzer** [Microsoft/vscode#17851]
- VSCode Version: 1.8.1
- OS Version: Windows 10

vscode.workspace.findFiles should be case insensitive on windows ?
Writing in the extension:
```javascript
var searchPattern = "**/sample.ini";
var files = vscode.workspace.findFiles(searchPattern, "");
files.then((value) => {
 // do something
}, 
(reason) => {
    console.log(reason);
});
```
how can I find `Sample.ini`, `SAMPLE.ini` or `SamPLe.iNi` ?
In fact in windows environment it is the same file...

**Comment by sean-mcmanus** [comment]
The C++ debugger extension also is hitting the same problem when the user opens a file via the Explorer in one case and it opens a duplicate file with a 2nd casing on Windows. Please fix VS code so that it understands that Windows is case insensitive for files so it doesn't open 2 of the same ones, which causes things like breakpoints and bookmarks to be attached to only one of the files, which is confusing.

**Comment by roblourens** [comment]
@sean-mcmanus I think that issue would be covered by https://github.com/Microsoft/vscode/issues/12448

**Comment by roblourens** [comment]
@chrmarti Are you looking at this for January or should I take a look? Making it a case-insensitive search seems like the right thing to do.

**Comment by chrmarti** [comment]
I'm unlikely to get to this for this milestone. If you get a chance to look into this, could you check if all usages of glob.ts need to be case-insensitive on Windows? It might make sense to have it as an option that is passed in to glob.ts depending on that.

**Comment by roblourens** [comment]
Related: https://github.com/Microsoft/vscode/issues/10633

**Comment by roblourens** [comment]
This is basically https://github.com/Microsoft/vscode/issues/10633
