### ISSUE TITLE
Make CLI build faster

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#178692]
Not only is the CLI stage the current bottleneck for our build's first stage, it also keeps a lot of agents busy as it runs. We should look into speeding it up. An obvious first step is to cache the `target` folder... maybe even use something like [sccache](https://github.com/mozilla/sccache).

**Comment by connor4312** [comment]
sscache didn't end up being that useful. It seemed like maybe a 10% time reduction, but these are also pretty noisy.

Instead I opted to only run a dev build with `clippy` for main's CI, which is much faster than a full optimized production build. Real production builds are unchanged, but I think these are a much lesser concern since they only run ~once a day.

**Comment by connor4312** [comment]
Easy verification, check that PR builds in https://dev.azure.com/monacotools/Monaco/_build?definitionId=111 are only linting and not compiling the CLI, and so are much less than 10 minutes 🙂
