### ISSUE TITLE
Terminals are named `kernel_task`

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#178693]
* Use *insiders-1.78* or run out of source
* start a terminal
* the name is "kernel_task"
* start a long running task, like `yarn watch`, press `ctrl+c` and see it's not terminating

https://user-images.githubusercontent.com/1794099/228880022-344ef467-c338-4a74-8c2a-a28e7cb090a5.mov

**Comment by zt123123** [comment]
same question

**Comment by shealan** [comment]
Same issue on my brand new Apple M2 Mac Mini. Running latest Insiders. I thought I was going crazy.

**Comment by hawkkiller** [comment]
Works fine on latest version of insiders.

**Comment by shealan** [comment]
Yeah fixed now. Thanks everybody!

**Comment by gitSambhal** [comment]
Not working for me. I am using `CTRL+Z`

**Comment by pramod1221** [comment]
Not working for me after updating today (May 09, 2023)

Version: 1.78.0 (Universal)
Commit: 252e5463d60e63238250799aef7375787f68b4ee
Date: 2023-05-03T20:11:00.813Z
Electron: 22.4.8
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin x64 18.7.0
Sandboxed: Yes

**Comment by pschmidtke** [comment]
> Not working for me. I am using `CTRL+Z`

That doesn't kill the process. It just suspends it. Just be aware of that (if you do it a lot ;)

**Comment by avi-l** [comment]
same for me, no control-c or any kill commands will work:
Version: 1.78.1
Commit: 6a995c4f4cc2ced6e3237749973982e751cb0bf9
Date: 2023-05-04T09:57:42.343Z (5 days ago)
Electron: 22.5.1
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin x64 18.7.0
Sandboxed: No

**Comment by gitSambhal** [comment]
It stopped working for me due to an extension which had created a key binding starting with `ctrl + c` so I removed the key binding and it started working. [This SO answer](https://stackoverflow.com/a/57711883/6613333) helped me.

**Comment by Tyriar** [comment]
@gitSambhal what extension was causing the issue?

**Comment by gitSambhal** [comment]
@Tyriar I forgot the name but you can check your keyboard bindings.

**Comment by Tyriar** [comment]
@gitSambhal I don't have the same extensions as you?

**Comment by loicguichaoua** [comment]
Hi, this "Ctrl+C" (terminate task) feature suddenly stopped working a few days ago for us as well:
- the "^C" still displays in the terminal but without any effect
- and there is not a single shortcut associated to Ctrl+C and no way to add one

This is a huge pain as we simply cannot work anymore using vs-code, this was such a central feature
There is SO MUCH content on the topic online, yet no simple solution:
- What happened? Why did vs-code team do this? 
- How is there not a SIMPLE option in Keyboard Shortcuts (JSON) to add it back? 

We won't be able to ship our work this weekend solely because of the delay caused by this.
Thanks in advance to those currently working on a solution

**Comment by gitSambhal** [comment]
@Tyriar what is shown in the vscode status bar when you press `ctrl + c` ?

**Comment by Tyriar** [comment]
@loicguichaoua it was a bug we introduced and fixed shortly afterwards, see https://github.com/microsoft/vscode/issues/181939. One of the downsides of using Insiders is occasionally things like this slip in.

**Comment by atabv** [comment]
> 

Still no update to fix it. How do we opt OUT of Insiders. I never have opted in!
