### ISSUE TITLE
Enter key is not working

### ISSUE THREAD

**Issue by yogicse12** [microsoft/vscode#178782]
Type: <b>Bug</b>

Enter key is not working in vs code editor with recent updates. Could you please check this bug.

VS Code version: Code 1.77.0 (Universal) (7f329fe6c66b0f86ae1574c2911b681ad5a45d63, 2023-03-29T09:57:11.797Z)
OS version: Darwin arm64 22.3.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (0.04GB free)|
|Process Argv|--crash-reporter-id 3771d4ff-7f9c-433d-938b-5cdab1cb1c5f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (46)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
vscode-tailwindcss|bra|0.9.11
npm-intellisense|chr|1.4.4
path-intellisense|chr|2.8.4
doxdocgen|csc|1.4.0
split-html-attributes|dan|1.0.10
vscode-eslint|dba|2.4.0
vscode-styled-components|die|0.1.33
javascript-ejs-support|Dig|1.3.3
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|13.4.0
vscode-html-css|ecm|1.13.1
vsc-material-theme|Equ|33.8.0
vsc-material-theme-icons|equ|2.7.4
prettier-vscode|esb|9.10.4
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
vue-snippets|hol|1.0.4
vscode-language-babel|mgm|0.0.38
dotenv|mik|1.0.1
vue-volar-extention-pack|Mis|1.1.8
vscode-duplicate|mrm|1.2.1
vscode-docker|ms-|1.24.0
vetur|oct|0.37.3
vscode-twoslash-queries|Ort|1.1.0
material-icon-theme|PKi|4.25.0
prisma|Pri|4.12.0
LiveServer|rit|5.7.9
synthwave-vscode|Rob|0.1.15
vue-vscode-snippets|sdr|3.1.1
firacode|Sey|2.2.1
vscode-scss-formatter|sib|2.4.5
autoimport|ste|1.5.4
code-spell-checker|str|2.20.3
vscode-styled-components|sty|1.7.5
sass-indented|syl|1.8.26
es6-string-html|Tob|2.12.1
cmake|twx|0.0.17
codelf|unb|11.7.0
volar|Vue|1.2.0
vscode-typescript-vue-plugin|Vue|1.2.0
vscode-todo-highlight|way|1.0.5
snippet-generator|wen|0.3.4
vue|Wsc|1.0.26
JavaScriptSnippets|xab|1.8.0
material-theme|zhu|3.15.8

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30610678
nodejswelcome1:30587005
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
showlangstatbar:30672706
vsctsb:30677850
vscodedisable:30660115
defaultazurewalk:30687958
pythonms35:30701012

```

</details>

**Comment by luke-meadows** [comment]
I have same issue

**Comment by dmitriiivashko** [comment]
Same issue here

**Comment by amitkumarhq** [comment]
I'm also facing the same issue with the `Enter` key.

**Comment by yogicse12** [comment]
Looks like I just found a fix for this:

In your settings.json
<https://code.visualstudio.com/docs/getstarted/settings#:%7E:text=Workspace%20settings.json%20location&text=The%20workspace%20settings%20file%20is,inside%20the%20workspace%20configuration%20file.>
 add

"editor.acceptSuggestionOnEnter": "smart"

Reload vscode and you're good to go

Thanks & Regards,
YOGENDRA
*YADAV*

**Comment by amitkumarhq** [comment]
> I'm also facing the same issue with the `Enter` key.

## Fixed
After monitoring the running extensions, I found that when I clicked the `Enter` key the status bar showed `Activating Extensions...` On further investigation I found out that this behaviour was caused due to the [vscode-styled-components](https://marketplace.visualstudio.com/items?itemName=diegolincoln.vscode-styled-components) extension. Now the problem is fixed 👍

**Comment by chloe-samdesk** [comment]
Same issue for me, and it was the vscode-styled-components extension. So is this an issue with the vs-code update? or should it be reported to the vscode-styled-components extention library?

**Comment by ArturoDent** [comment]
As reported in this SO question: https://stackoverflow.com/a/75896428/836330, you might try this keybinding as a temporary fix:

```jsonc
{
  "key": "enter",
  "command": "type",
  "args": {
    "text": "\n"
  },
  "when": "textInputFocus"
}
```

**Comment by shadybassily** [comment]
> As reported in this SO question: https://stackoverflow.com/a/75896428/836330, you might try this keybinding as a temporary fix:
> 
> ```js
> {
>   "key": "enter",
>   "command": "type",
>   "args": {
>     "text": "\n"
>   },
>   "when": "textInputFocus"
> }
> ```

this will mess auto complete

**Comment by ulugbekna** [comment]
Hello everyone! 

Thank you for patience with this. 

This problem indeed is caused by the [diegolincoln.vscode-styled-components](https://marketplace.visualstudio.com/items?itemName=diegolincoln.vscode-styled-components) extension because of the new VS Code when-clause parser. 

I tried sending a PR to this extension fixing the syntax error it has (which was just ignored by the previous parser), but it seems the extension (at least its repository) is archived. It seems like there's a new vscode-styled-components extension that's very popular - https://marketplace.visualstudio.com/items?itemName=styled-components.vscode-styled-components

### Workarounds

#### Option 1 (recommended)

This particular extension seems unmaintained. I strongly suggest switching to using this extension if it fits your needs - https://marketplace.visualstudio.com/items?itemName=styled-components.vscode-styled-components  

#### Option 2 

Remove that keybinding: invoke "Preferences: Open Keyboard Shortcuts" from the Command Palette, search `"enter"`, and right-click on the command contributed by vscode-styled-components (see right-most column for the source of the keybinding) 

<img width="1464" alt="image" src="https://user-images.githubusercontent.com/16353531/229239421-b1e4f92f-03d3-4360-b3f7-0e3c873d8353.png">

---

I will close this issue because this extension is unmaintained. I recommend switching to https://marketplace.visualstudio.com/items?itemName=styled-components.vscode-styled-components, which seems to be very active and fixes this keybinding in several ways (both the syntax error and integration with auto-completion)

Thanks everyone for investigation and help with this issue! I very much appreciate it :-)

**Comment by starball5** [comment]
Related on Stack Overflow:

- (already linked above) [Cannot create line break with Enter key in VS Code](https://stackoverflow.com/q/75896153/11107541)
- [after pressing Enter button new line is not creating in ubuntu 22.04 after updating the new version 1.77](https://stackoverflow.com/q/75937558/11107541)
