### ISSUE TITLE
terminalSupport.ts should be moved into terminal land

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#17878]
I do not think this file belongs in the debug land
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/terminalSupport.ts#L14

It should be moved into the terminal folder - or the terminal service should provide this functionality, it does not make sense for this to live in the debug folder

**Comment by Tyriar** [comment]
Looks like the right fix here is to have a `ITerminalService.runInTerminal` in parts/terminal. This appears to be duplicating a bunch of command prep code in parts/execution as well so they should share the common components.

**Comment by isidorn** [comment]
Do we plan to do something about this?
I do not mind doing a PR if somebody provides the right pointers

**Comment by weinand** [comment]
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/terminalSupport.ts#L14 is the VS Code-side implementation of the DAP protocol request "runInTerminal". If you believe that "terminal land" has a sufficient implementation that could support the "runInTerminal" request for the integrated as well as an external terminal, please free to make the move happen. But the "runInTerminal" handler itself will remain in debug land (because it is a DAP request) and belongs into debug land.

**Comment by Tyriar** [comment]
Right now integrated (`parts/terminal`) and external (`parts/execution`) terminals are separate parts, and I'm still not sure whether it's a good idea to merge the external and integrated terminal. The code they share is very minimal really.

**Comment by weinand** [comment]
Since this is a feature of DAP, we will keep it in debug land.
