### ISSUE TITLE
[FR][Terminal] allow addons to be added/enable/disable

### ISSUE THREAD

**Issue by farfromrefug** [Microsoft/vscode#17897]
xterm.js already have a few interested addons.The one that would be especially useful for vscode is the linkify one.

Would be great to have the possibility to enable that addon from the API. The same it would be great for extensions to be able to add their own custom xterm addons.

Related discussion: https://github.com/Microsoft/vscode/issues/17678

**Comment by Tyriar** [comment]
So linkify is currently broken upstream (https://github.com/sourcelair/xterm.js/issues/27) and I wouldn't be surprised if it doesn't work at all anymore since I don't think anyone has looked at it in a while. There are a bunch of other issues as well.

My plan with linkify was to wait until it's worked out upstream either by myself or another contributor and then mold it so it works with VS Code. This may need to be put into xterm.js' core depending on how it performs. Also simply enabling addons will not just let it work as xterm.js is build for the browser, not electron. linkify adds `<a>` tags which will need to be handled specially within VS Code and thus will need tighter integration. Here's the feature request for that https://github.com/Microsoft/vscode/issues/7321

I'm going to close this off as I don't see this ever happening due to the browser/electron issue. In the meantime you can upvote #7321 which will help bump it higher in my queue.
