### ISSUE TITLE
Feature Request: Pasting code in new tab retains syntax highlighting.

### ISSUE THREAD

**Issue by TeffenEllis** [Microsoft/vscode#17890]
Sublime Text allows you to copy text from one tab and paste it in a new tab, automatically changing the syntax highlighting to match the source text. It'd be awesome to have this in VSCode.

Cheers

**Comment by dbaeumer** [comment]
Nice idea. Paste with language mode.

**Comment by alexandrudima** [comment]
To keep the number of issues in our inbox at a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: we look at the number of votes the issue has received and the number of duplicate issues filed. Thank you for your time and understanding.

If you disagree and feel that this issue is crucial: we're happy to listen and to reconsider.

**Comment by TeffenEllis** [comment]
@alexandrudima,

I'm still interested in seeing this feature added. Can we reopen the issue?

Cheers
