### ISSUE TITLE
Git - 3wm editor not closed when enabling `git.closeDiffOnOperation`

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#179045]
1. Have `git.closeDiffOnOperation` enabled
2. Resolve a merge conflict in 3wm editor
3. Stage it
4. :bug: 3wm editor is not closed

I realize it's technically a merge editor not a diff editor but would it make sense for the git extension to also close 3wm editors when the corresponding resource is staged? Otherwise after resolving the conflict, the merge editor hangs around and has empty inputs:
![image](https://user-images.githubusercontent.com/30305945/229596452-3343cf12-d8c5-4a80-9f35-2167f2e5280f.png)

**Comment by lszomoru** [comment]
I took a look at this flow again and I believe that most people use the "big blue button" to complete the merge which will close the merge editor. Not sure if the "big blue button" was in place when the issue was filed. I would not want to conflate diff editors with merge editors so I will close this issue as "not planned".
