### ISSUE TITLE
Explore prompting to enable Cloud Changes on web

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#179014]

**Comment by andreamah** [comment]
Should there be a picture of an overlay widget in the above comment? I think the comment mentions it but I can't see one.

Also, I tried this just now in an incognito window (after logging into github) and I didn't see an overlay widget? I had to use a non-msft repo because I can't authenticate the msft org from incognito.

**Comment by joyceerhl** [comment]
@bhavyaus is there an experimental setting that folks need to set to see the overlay widget still?

**Comment by bhavyaus** [comment]
**Verification Steps:**
1. **Please reach out to @bhavyaus to have this dialog be enabled for your machine id**
2. Ensure that you have a clean setup. We only show this for a new user who has never used insider.vscode.dev before.
3. Open a GitHub URL such as https://insiders.vscode.dev/github/microsoft/vscode
4. Edit any file in the repo.
5. An overlay widget, such as the one shown below, should appear in the top right-hand corner of the editor when you have paused typing.

<img width="379" alt="image" src="https://github.com/microsoft/vscode/assets/25044782/b315f160-1717-486d-ad78-c56babeba493">
