### ISSUE TITLE
SQLite3 not supported?

### ISSUE THREAD

**Issue by DanJ210** [Microsoft/vscode#17919]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 10.0.14986
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-css-formatter|aeschli|0.0.2|
|vs-code-css-comments|ashhitch|1.0.2|
|vscode-icontheme-nomo-dark|be5invis|1.2.1|
|javadebugger|donjayamanne|0.0.2|
|python|donjayamanne|0.5.1|
|vscode-html-css|ecmel|0.0.30|
|javac-linter|faustinoaq|1.2.1|
|php-intellisense|felixfbecker|0.0.12|
|auto-close-tag|formulahendry|0.3.7|
|auto-rename-tag|formulahendry|0.0.9|
|code-runner|formulahendry|0.6.5|
|csharpextensions|jchannon|1.1.0|
|format-indent|Kasik96|1.3.0|
|format-php|Kasik96|1.1.2|
|ftp-sync|lukasz-wronski|0.3.2|
|cpptools|ms-vscode|0.9.3|
|csharp|ms-vscode|1.6.2|
|theme-railscasts|PaulOlteanu|1.0.0|
|material-icon-theme|PKief|1.1.5|
|vscode-icons|robertohuertasm|4.3.0|
|elise|schematrix|0.0.1|
|theme-tinaciousdesign|tinaciousdesign|0.1.1|

---

Steps to Reproduce:

1. Trying to use SQLite3 with PHP in the editor, everywhere says it's built in without any installation needed.
2. $test = new SQLiteDatabase; (Says Fatal Error: class not found)

What do we have to do to get this awesome DMB with its classes into VS code? Am I missing something?

**Comment by dbaeumer** [comment]
This has to come from the Python extension (https://github.com/DonJayamanne/pythonVSCode). Moving.

**Comment by dbaeumer** [comment]
This issue was moved to DonJayamanne/pythonVSCode#611

**Comment by DanJ210** [comment]
@dbaeumer Can someone give me some more info here and help me out, please?

**Comment by DonJayamanne** [comment]
@dbaeumer  Reopening as this isn't an issue with the Python extension @DanJ210 , has mentioned the language **PHP**

**Comment by DanJ210** [comment]
![vscode - sqlite3](https://cloud.githubusercontent.com/assets/16159685/21583362/791fcdb8-d04b-11e6-94db-a5c70fd8f05d.png)

I guess I could show an update in that I did get the ability to extend an SQLite3 class as seen in the screenshot. I just can't do what I've seen in a few training videos in the screenshot I first posted above. Not sure if it has changed since then or not.

**Comment by mousetraps** [comment]
@DanJ210 I'm a little confused - this seems to be a general PHP configuration issue, rather than a VS Code issue. And from your screenshot, it doesn't look like there are any errors that VS Code is throwing. Is there some specific support you're expecting to see in the editor that's not there? 

That said, I took a look at the PHP docs, and couldn't find any recent references to SQLiteDatabase. It appears to only be available in [PHP 5 < 5.4.0](http://php.net/manual/en/function.sqlite-open.php). For PHP 5 >= 5.3.0, PHP 7, the it looks like the SQLite3 constructor should offer the same functionality, with a slightly improved API - http://php.net/manual/en/sqlite3.construct.php

Anyways, hope that helps :smiley:. lmk if there's something VS Code-specific about the issue that I missed or if it's fine to close.

**Comment by DanJ210** [comment]
The only error I was getting was the fatal class error from above. I posted as I wasn't sure if this was a PHP or Editor error. Everything I read said that this stuff was built in so there should be no extra installation nor configuration needed. If that's the case then why isn't it working? So I wasn't sure what kind of error it was. Figured I'd post just to see what another expect thought, I'm still new and learning all of this.

I did find a different way of getting done what I needed by using a different class. I didn't want to waste anyone's time but figured it was worth a shot to see what someone else thought. Perhaps the way I'm trying to use SQLite3 is no longer supported? idk. So far the other way of using SQLite3 has been fine with zero issue. I suppose this thread could be removed entirely as I was only looking for some direction or insight.

Thanks for the response @mousetraps  I do appreciate it.

**Comment by mousetraps** [comment]
@DanJ210 - yeah, I hear ya - frameworks change so fast that I've gotten into the habit of just looking up the docs (or source code) for every function call I'm unfamiliar with. In this case, I think you're correct that the way you were trying to use it is no longer supported. In particular, rather than doing this (which worked in PHP5)
```php
$test = new SQLiteDatabase;
```

You should be able to do:
```php
$test = new SQLite3($filename);
```
As shown in the example on [this page](http://php.net/manual/en/sqlite3.construct.php) - well, in theory, that is. Either way, glad you've got it working, and good luck w/ the rest of your project!
