### ISSUE TITLE
code tunnel: use win32 app mutex to detect running tunnels and tunnel sevices

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#179265]
For #177226

Windows update (using Inno-setup) can use win32 app mutexes to detect running applications that need to stop before an update can continue.

The code tunnel should add:

- 1 mutex for tunnels started by the user
  - to block the update flow
- 1 mutex for tunnels started as service
  -  in order to stop & start service around update flow

**Comment by aeschli** [comment]
Adding @joaomoreno. He recommended the mutex. Inno-setup allows to easily test for these. Also having 2 different mutexes allows it to distinguish between a tunnel started from a service vs a manually started tunnel.

The idea is that if Inno-setup sees the tunnel-as-service mutex, it stops/uninstalls the service (running `code tunnel service uninstall`) and waits for the mutex to be released.
Once the mutex is released, it updates VS Code and starts/installs the service again (`code tunnel service install`)

If the Inno-setup sees a user-tunnel-mutex, it will ask the user to manually stop the tunnel and wait until that has happend.

**Comment by joaomoreno** [comment]
Inno Setup needs API in order to (1) detect whether the cli is currently running (as a service and otherwise) and (2) stop and start the cli as a service. The proposal is:

1. Use app mutexes. This is the standard way Inno Setup has to detect whether an application is running. Using a mutex for the regular cli usage will be necessary in order for the setup/update flow to detect an active cli tunnel and prevent install/update. Using a mutex for the cli as a service would just be conveniently consistent: it wouldn't block install/update but would act as a signal to stop and start the service during an update flow.
2. We could simply have Inno Setup spawn the CLI to stop and start the tunnel service. The spawn args would become API.

**Comment by connor4312** [comment]
Yea, I can have it register a mutex easily enough 👍

**Comment by connor4312** [comment]
There will now be a lock named `code_tunnel_service_${quality}` for the service, and `code_tunnel_${quality}` for the CLI/non-service mode.

**Comment by aeschli** [comment]
@connor4312 To make this [consistent with the existing win32 app mutex](https://github.com/microsoft/vscode/blob/7843ea546acdb8e8f614e1516a9f215e03f148c8/product.json#L6), let's have the name of the mutexes in `product.json`.
