### ISSUE TITLE
Cannot open top menu (File,Edit,...)

### ISSUE THREAD

**Issue by fabiopapajani** [microsoft/vscode#179261]
Type: <b>Bug</b>

Cannot open top menu when I open a new window instance and I'm trying to maximize the window to full screen.

VS Code version: Code 1.77.0 (7f329fe6c66b0f86ae1574c2911b681ad5a45d63, 2023-03-29T10:05:35.165Z)
OS version: Linux x64 5.19.0-38-generic
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2948)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 0|
|Memory (System)|15.32GB (10.26GB free)|
|Process Argv|--unity-launch --crash-reporter-id 428d0b08-6ce8-4e19-8f73-08149052b9fa|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.4.0
gitlens|eam|13.4.0
prettier-vscode|esb|9.10.4
Kotlin|mat|1.7.1
dotenv|mik|1.0.1
isort|ms-|2022.8.0
python|ms-|2023.6.0
vscode-pylance|ms-|2023.3.40
jupyter|ms-|2023.3.1000892223
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
makefile-tools|ms-|0.6.0
vscode-gradle|vsc|3.12.2023032800
gitblame|wad|10.1.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30610679
nodejswelcome1:30587005
3biah626:30602489
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
a9j8j154:30646983
showlangstatbar:30672706
defaultazurewalk:30687958
pythonms35:30701012
j16hj152:30706079
pythonclientmvcf:30705674

```

</details>

**Comment by igavrysh** [comment]
This issue also happens for me: when the window is resized or moved, any click on menu item `File`, `Edit` : 
* either shows menu without items (just plain rectangle() for split second and instantly hides it
* or just does not react at all

If I switch to other programs back and forth after resizing the code window, this issue would be gone. After I do resizing of vscode window, the same issue happens again.

Systems I tried:
* Ubuntu 22.04
* Fedora 37
* Kde neon 5.27

This issue was introduced in vscode 1.71 and it still present in current version (1.77). If I install 1.70 version - this issue does not exits and vscode works correctly.

**Comment by igavrysh** [comment]
Demo:

![demo-vscode-menu-bug](https://user-images.githubusercontent.com/10332978/230410979-ba4bd037-5cca-45ab-90f9-5b0a733bae80.gif)

**Comment by daniel-larraz** [comment]
I can confirm the issue reported by @fabiopapajani . The issue also occurs when all extensions are disabled.

Steps to Reproduce:
1. Open VS Code.
2. Open New Window
3. Try to open top menu.

If I switch to other window back and forth, the issue is gone.

Affected VS Code versions: 1.77.0 - 1.77.1
OS: Ubuntu 20.04.6
Desktop environment: GNOME Classic

Switching to v1.76.2 solves the issue.

**Comment by igavrysh** [comment]
The issue still persists for VS Code `1.76.2` for my case. The max version that does not have this issue is `1.70` on my side.
![demo-vscode-menu-bug-1-76-2](https://user-images.githubusercontent.com/10332978/230425111-30e3e576-c418-46e5-ae01-86c305d536f0.gif)

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/163736
