### ISSUE TITLE
clicking on file:// urls doesn't support line+col

### ISSUE THREAD

**Issue by samdenty** [microsoft/vscode#179412]
1. Type `file:///PATH:1:1` into an editor, replacing PATH with the path to a file that exists
2. Click the link

### Actual behaviour

The opened file is `PATH:1:1`, which of course doesn't exist

### Expected behaviour
The opened file is `PATH` and it jumps to line 1 column 1

**Comment by jrieken** [comment]
You need to use the url fragment for this, adding this to the path won't work because we don't know if the colon portion is part of the path or not, e.g any of these will work

file:///some/file.js#73
file:///some/file.js#L73
file:///some/file.js#73,84
file:///some/file.js#L73,84
file:///some/file.js#73-83
file:///some/file.js#L73-L83
file:///some/file.js#73,84-83,52
file:///some/file.js#L73,84-L83,52
