### ISSUE TITLE
Provide ability for pasting over highlighted Markdown text to turn the text into a link to the pasted URL

### ISSUE THREAD

**Issue by brettcannon** [microsoft/vscode#179628]
GitHub supports highlighting some text in an issue and then automatically converting the test to a link when pasting over it. I have come to use that feature so much that it surprises me every time in VS Code when that isn't the semantics. I also checked for a setting to turn such semantics on and I could find one either.

**Comment by lgarron** [comment]
I would also love to see this feature.

Since GitHub and certain other apps added support for this functionality, I've gotten very used to using it.[^1] It's always a bit jarring when I do it in VSCode out of instinct, only to delete some text.

For some people, I think it would also be nice to support ⇧⌘V (or Ctrl-Shift-V) to paste the link directly, [like in GitHub](https://github.blog/changelog/2022-02-02-paste-links-directly-in-markdown/):

> To paste HTML links as plain text, use cmd/ctrl + shift + v instead.

(I believe I've seen at least one app also add an option to swap ⌘V and ⇧⌘V.)

[^1]: I use it while composing this very comment!

**Comment by vanossj** [comment]
After seeing the [paste as](https://code.visualstudio.com/updates/v1_79#_paste-as) feature in v1.79, I was disappointed to find out it wasn't pasting links over text to create hyperlinked text.  We need this feature in VSCode too!
