### ISSUE TITLE
When clause not working when the config is an object

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode#179842]
Version: 1.78.0-insider (user setup)
Commit: c9df8ee8e8c316f38dcc75a894ba150024ce3718
Date: 2023-04-13T05:25:44.823Z
Electron: 22.4.4
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: Yes

Steps to Reproduce:

1. Apply this change: https://github.com/microsoft/vscode-extension-samples/commit/18adb78d1ef549e6bdfdb03a224b25c01e648dcf
2. Launch the sample extension
3. According to the when clause, the refresh button will appear when
```
test: { abc: true }
```

and disappear when

```
test: { abc: false}
```

But after changing the value more than 2 times, the button will not show anymore:

![bug](https://user-images.githubusercontent.com/6193897/231688121-4b78fc66-3362-43f9-8cf0-3f29ff86b3f5.gif)

**Comment by alexr00** [comment]
Took a look at this, and the short answer is that this is by design.

When a setting changes, we update the corresponding context keys. In this case the setting that changes is just `test`, not `test.abc`. When the context key is updated, it is just `config.test`. The setting key that we use for this is always the setting key as defined in the package.json, no object properties will be used as part of this key. 

If we were to change this we would need to expand _every_ when updating the context, which is not feasible as that would mean checking the individual values of each setting to an indeterminate depth.

The best I can recommend for this is to change you setting in `package.json` to `test.abc` instead of a `test` object with a property `abc`.
