### ISSUE TITLE
Expose client (browser) logs for smoke tests running in browser

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#180102]
Browser Smoke tests in our builds are only exposing server side logs. It would be great if the build also have client side logs like window log. This will be helpful to diagnose if there are issues.

**Comment by bpasero** [comment]
This makes sense to me and maybe you want to take a stab at it as owner of the browser based logs? We currently have no client side logs for both integration tests and smoke tests so ideally the solution would work in both cases.

For Electron and server having the logs as artefacts attached is easy because they end up being files on disk that we can simply upload. For browser tests we would need a way to extract the logs from browser storage to files as well.

Some code pointers:

Here we set the logs dir specifically for tests (integration):

https://github.com/microsoft/vscode/blob/682afdd61dd66e83cfdbefdf6b8214dbbc65e135/scripts/test-integration.sh#L16

Here we produce the artefacts based on that directory:

https://github.com/microsoft/vscode/blob/682afdd61dd66e83cfdbefdf6b8214dbbc65e135/build/azure-pipelines/darwin/product-build-darwin-test.yml#L184-L186

Here we use playwright for the tests, maybe we can use playwright APIs to extract the logs into files?

https://github.com/microsoft/vscode/blob/682afdd61dd66e83cfdbefdf6b8214dbbc65e135/test/automation/src/playwrightBrowser.ts#L88

https://github.com/microsoft/vscode/blob/682afdd61dd66e83cfdbefdf6b8214dbbc65e135/test/integration/browser/src/index.ts#L35

**Comment by weartist** [comment]
I want to solve this problem

**Comment by weartist** [comment]
@sandy081 @bpasero  I would like to ask for some help, I observed that after running the smoke test of electron, the following file appears under the folder:
![image](https://user-images.githubusercontent.com/17105034/233416605-29a8319d-5e07-47c3-a911-032e40d7d992.png)


But after running the browser test, no file is generated under the folder, so what we need to do is to make the browser test generate log files as well? thanks!
![image](https://user-images.githubusercontent.com/17105034/233416674-18b2578e-4c56-4a64-8ba5-254a207f6351.png)

**Comment by bpasero** [comment]
Some first baby steps in https://github.com/microsoft/vscode/pull/181146. It is quite ugly that we get no direct access to IndexedDB from playwright and reading from the logs store is also quite raw, but that gets the contents of the logs into the logs folder for both web integration and web smoke tests.

I am a little bit worried that this call might hang or fail for obscure reasons...
