### ISSUE TITLE
PHP 7 Return Type Declarations

### ISSUE THREAD

**Issue by Keith-Cancel** [Microsoft/vscode#18025]
- VSCode Version: 1.9.0-insider
- OS Version: macOS Sierra 10.12.2

The IDE shows a syntax error when I use the PHP 7 Return Type declarations.
**The Error**:
file: 'file:///Users/keith/Development/keith/PHP/test.php'
severity: 'Error'
message: 'parse error, expecting `'{'''
at: '2,1'
source: ''

Here is the [PHP Documentation](http://php.net/manual/en/functions.returning-values.php#functions.returning-values.type-declaration) regarding return types.

Here is a simple piece of code that causes the syntax error:
```
<?php
function hello(string $name): string {
    return "Hello $name!\n";
}
```

I hope it's nothing to major to fix since the last version of PHP 5 is no longer actively supported, as of December 31. It's only receiving security updates.

**Comment by mousetraps** [comment]
Thx for reporting! Here's my guess - PHP 5 is in your PATH, not PHP 7, so the VS Code validation (simply runs php under the covers to identify syntax errors) is unhappy because PHP5 only knows PHP5 stuff. You can validate this by running "php --version" from the terminal. 

So, assuming that's the case, you have two options:
1. add PHP 7 to your PATH, so that VS Code can automatically discover it
2. update the `php.validate.executablePath` to point to PHP 7 instead

Hope that helps! Let me know if that doesn't work, and we can dig into it further.

**Comment by Keith-Cancel** [comment]
Well I don't even have PHP installed on my system. I normally test my code on a set remote systems.

**Comment by JStiller** [comment]
I can just agree 👍 - I already requested such a feature. https://github.com/Microsoft/vscode/issues/11328

**Comment by roblourens** [comment]
You will need PHP 7 installed locally to use the PHP tooling. Otherwise, https://github.com/Microsoft/vscode/issues/11328
