### ISSUE TITLE
Setting to not automatically show inline suggestion is not respected

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode#180224]
# Description 

The setting to not automatically show inline suggestion is not respected.

https://user-images.githubusercontent.com/16353531/232801321-b980c77f-e8f4-4504-b582-476bf19abc9b.mov

# Version info

Version: 1.78.0-insider (Universal)
Commit: 95396f14dbae4d5def754d8635010f8e5743f56c
Date: 2023-04-18T05:24:10.529Z
Electron: 22.4.5
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.4.0
Sandboxed: Yes

**Comment by hediet** [comment]
Thanks for finding this issue!

I think this is a tough problem. When you hit escape while a ghost text is shown, the session is stopped and remains stopped until you trigger inline completions again explicitly.
I also think it has been like this before, but before we would clear/restart the session also when the cursor changes the line.
We cannot do this anymore because of partial word acceptance that spans lines.

I think it's okay to fix this next iteration.
