### ISSUE TITLE
Change jsconfig.json "target" default value to "es2015"

### ISSUE THREAD

**Issue by SaschaNaz** [Microsoft/vscode#18023]
- VSCode Version: 1.8.1
- OS Version: Windows 10

Steps to Reproduce:

1. Create a new empty `jsconfig.json`
2. Write `compilerOptions` and `target`
3. VSCode gives `es6` by default whereas the name `es2015` is now preferred

**Comment by mjbvz** [comment]
I'm going to move this issue over to schemastore, which is where we pick up the `jsconfig.json` schema. It should be as simple as updating this line: https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/jsconfig.json#L172

@SaschaNaz do you want to submit a PR against schemastore since you have more knowledge of this area?

Thanks

**Comment by mjbvz** [comment]
This issue was moved to SchemaStore/schemastore#262
