### ISSUE TITLE
Format will work very slow on big files

### ISSUE THREAD

**Issue by andreiropotica** [Microsoft/vscode#18026]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions:

|Extension|Author|Version|
|---|---|---|
|jsrefactor|cmstead|0.5.3|
|jshint|dbaeumer|0.10.15|
|vscode-stylesheet-formatter|dbalage|0.2.0|
|githistory|donjayamanne|0.1.4|
|jquerysnippets|donjayamanne|0.0.1|
|JSDocTagComplete|HookyQR|0.0.2|
|prettify-json|mohsen1|0.0.3|
|jscs|ms-vscode|0.1.9|
|debugger-for-chrome|msjsdiag|2.4.2|
|stylelint|shinnn|0.21.2|
|addDocComments|stevencl|0.0.8|
|sort-lines|Tyriar|1.1.0|
|gitblame|waderyan|1.3.0|
|bootstrap-3-snippets|wcwhitehead|0.0.9|

---

Steps to Reproduce:

1. Create or have an unformatted 10+k .js file
2. Hit the format combination
3. No format will be executed, not even selected code (>500 lines) format.

**Comment by jrieken** [comment]
There are limits to what VS Code can do. Since you say 10k+ files I assume you have a really large file in which case you hit the case in which we stopping offering fancy features like format et al. That's because we know if will be slow and blocking.

**Comment by andreiropotica** [comment]
not even selected code format? for 500 lines?

**Comment by andreiropotica** [comment]
I belive the best way is to warn the user and let the user decide if it's ok to wait and format or not...

**Comment by jrieken** [comment]
> not even selected code format? for 500 lines?

The design is that the file doesn't even exist for extensions. That is because most extension don't check for the size of the document they operate on and just start crunching data on load. That's why we are so conservative with very large files. 

Sorry that I don't have a better answer but that's the current design and there is no easy way to make a small chance that enabled your (valid) scenario.
