### ISSUE TITLE
Extract node_modules cache flake in pipeline

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#180371]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=211471&view=logs&j=9833cdaa-2e92-5f8d-56a8-239fd18fd628&t=ba20f3c3-572a-5fba-98e2-dcb31723a3fa&l=60423

A similar error has appeared for other Azure Pipelines tasks https://github.com/microsoft/azure-pipelines-tasks/issues/13785

**Comment by meganrogge** [comment]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=211852&view=logs&s=d26761af-f5e8-5e3e-3ed3-ef1ee2069094&j=78322c78-e078-5e20-184d-1b2bb6aed118

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=211871&view=logs&j=260a512b-e5ca-5cf1-3f8e-20c0fa41efc9&t=22113586-ca8b-59fc-5d74-ba15236b4ee3

**Comment by joaomoreno** [comment]
Odd:

- @joyceerhl's one is about extracting
- @meganrogge's first one shows no error at all (copy paste mistake?)
- @meganrogge's second one is about creating a zip

**Comment by meganrogge** [comment]
@joaomoreno I reran the failure for the first one which is why it no longer shows an error

here's the precise link to the failure

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=211852&view=logs&j=55ac390b-ffb1-50ea-3650-525dd9a3fd80&t=7a41f864-1411-5635-a6d8-563d674ed440&s=a56e7651-4213-56af-9488-c25fe636c10c

**Comment by joaomoreno** [comment]
Thanks!

**Comment by meganrogge** [comment]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=212170&view=logs&j=9833cdaa-2e92-5f8d-56a8-239fd18fd628&t=ba20f3c3-572a-5fba-98e2-dcb31723a3fa
