### ISSUE TITLE
still show error message when "noUnusedLocals": false

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#180309]
![image](https://user-images.githubusercontent.com/41773861/233039895-1d9e1894-d5e5-4fb2-8b37-ab37557841d4.png)

I had set `"noUnusedLocals": false` in tsconfig.json

@mjbvz 

Seems your extension https://github.com/zardoy/vscode-disable-ts-errors also can't disable this message @zardoy

**Comment by zardoy** [comment]
@tjx666

The title says "error message". From the screenshot I see it's a suggestion diagnostics rather than error. If you hover over `noUsedLocals` in your tsconfig you'll see that [docs says](https://www.typescriptlang.org/tsconfig#noUnusedLocals) it enables error reporting of unused locals (warning diagnostic instead of hint). 

I was pretty sure that setting `"typescript.suggestionActions.enabled": false` should disable all suggestion diagnostics, but it doesn't work for some reason.

> Seems your extension [zardoy/vscode-disable-ts-errors](https://github.com/zardoy/vscode-disable-ts-errors) also can't disable this message

How did you test it? I created it with ability to customize all types of diagnostics in mind (including suggestion diagnostics). Just do this:

```json
"disableTsErrors.customizations": [
    {
        "code": 6133,
        "severity": "off"
    }
],
```

**Comment by zardoy** [comment]
If you mean web version, last time I checked it there were an issue that `tsExtensionApi.configurePlugin()` simply doesn't work and I didn't see an easy workaround...

**Comment by mjbvz** [comment]
The tsconfig setting only controls if unused locals are treated as a warning/error. We still fade out unused locals as a hint unless you set `"editor.showUnused": false`

**Comment by tjx666** [comment]
> The tsconfig setting only controls if unused locals are treated as a warning/error. We still fade out unused locals as a hint unless you set `"editor.showUnused": false`

`"editor.showUnused": false` can only control whether fade out unused variable, can control whether show the message When I hover over ir.

I want to hide the message because I had use eslint to check it:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/233150908-59d6c439-c247-4e57-a7ae-f27ff7022d93.png">
