### ISSUE TITLE
Search settings , Activate input bug

### ISSUE THREAD

**Issue by tisilent** [microsoft/vscode#180469]
Version: 1.77.3 (user setup)
Commit: 704ed70d4fd1c6bd6342c436f1ede30d1cff4710
Date: 2023-04-12T09:16:02.548Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No

![20230421_114321](https://user-images.githubusercontent.com/48614781/233536096-dcbaab99-2326-4ae0-b6a5-b3710c35bf18.gif)

**Comment by rzhao271** [comment]
1. Navigate to the Settings editor, widen the application, and hide any sidebar so that the search inputbox is long.
2. Click on the middle of the inputbox. It should focus into the inputbox.
3. Click near the end of the inputbox around two cm left of the clear search button. It should now focus into the inputbox, still.
