### ISSUE TITLE
[folding] Fold highlights part of the line

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#18047]
- Open any file
- Place the cursor on a line with a fold icon
- Click the fold icon
- Part of the line with the cursor is now selected

**Comment by roblourens** [comment]
I guess this isn't specific to 'fold all' and reproes in 1.8, has it always been that way?

**Comment by rebornix** [comment]
This one is quite interesting after some investigation. We are trying to make the selection correct when we fold or unfold.

If selection is LTR and selection end is in the first line of folding area
![selstartinrange](https://cloud.githubusercontent.com/assets/876920/21943637/01523d4e-d987-11e6-81f5-e975ec7c070b.gif)

If selection is LTR and selection end is inside the folding area

![selstartinrange2](https://cloud.githubusercontent.com/assets/876920/21943684/3473d89a-d987-11e6-9ee3-a920cb3e51fc.gif)

SelectionEndPosition inside the folding area or RTL selections are similar. The only catch is we didn't take care the edges: when the selection boundary is at the first line of the folding area, which is not actually *folded*, we'd better not extend the selection. Instead we may want to keep the selection untouched.

Since there are quite a few corner cases, I'll say it's a feature request or enhancement for folding area.

**Comment by yousifalraheem** [comment]
I would love to have code folding for only the highlighted area. If I use fold or ( alt+cmd+[ ) this will fold the parent but this isn't what I want. I just want to fold the highlighted area just like Dreamweaver. It's super helpful when you have a long code.

**Comment by aeschli** [comment]
I think this is fixed now. If the selection is on the first line, is no longer adjusted. Adjustment only should happen when a selection is starting or ending inside a folded region.
