### ISSUE TITLE
Debug frame indicator should go in the same decoration column as breakpoints

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#180439]
<img width="288" alt="image" src="https://user-images.githubusercontent.com/323878/233472800-06172ca8-1569-4c45-a378-989460b03b86.png">

This leads to the editor shifting to the right every time I pause, because it's adding an editor gutter. We actually already have a combo decoration that shows the two things together. I don't actually know exactly how that works but can look it up if you need it.

Actually this combo decoration doesn't exist for all breakpoint types, which is annoying, but that's an issue for me

**Comment by joyceerhl** [comment]
> We actually already have a combo decoration

If you have a code pointer that would be awesome, I wasn't aware we had a notion of combined decorations today

**Comment by roblourens** [comment]
So when I see this

<img width="76" alt="image" src="https://user-images.githubusercontent.com/323878/233496990-096ea4bb-50e5-49b6-bd1e-9b7b91a78760.png">

there is a `::before` and an `::after`, that is where the different colors come from

I think the `::before` comes from the normal decoration, then we set the `::after` content here
https://github.com/microsoft/vscode/blob/510f3ee64641993e05db37e4a9795803f8a22cb0/src/vs/workbench/contrib/debug/browser/media/debug.contribution.css#L34-L38

and color here

https://github.com/microsoft/vscode/blob/510f3ee64641993e05db37e4a9795803f8a22cb0/src/vs/workbench/contrib/debug/browser/breakpointEditorContribution.ts#L780-L788

It seems like we are hacking editor decorations with css a bit

**Comment by roblourens** [comment]
The actual stackframe decorations come from here 

https://github.com/microsoft/vscode/blob/510f3ee64641993e05db37e4a9795803f8a22cb0/src/vs/workbench/contrib/debug/browser/callStackEditorContribution.ts#L60

**Comment by joyceerhl** [comment]
The trouble is now we also have this notion of a `zIndex` to ensure e.g. that testing decorations always render atop other decorations, so if there are multiple decorations in the same lane we pick the first one and discard the rest. 

To show those decorations together, I think I have to restore the old behavior so that decorations with the same `zIndex` get the classnames combined like in the previous stable. But as you said that only works because of some CSS hackery, maybe we also want a more formalized way to combine decorations.
