### ISSUE TITLE
Diff: arrow and breakpoint do not work well together

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#180789]
<img width="725" alt="image" src="https://user-images.githubusercontent.com/900690/234209487-b531df1e-4a12-4afd-a769-cfa521687a62.png">

Clicking the breakpoint executes the revert action it seems. Looks like click handlers are not yet separate.

**Comment by joyceerhl** [comment]
Yeah, I plan to tackle introducing glyph widgets in the margin next iteration, we cannot yet discern the click target. Would it make sense to disable a revert on click when there are multiple decorations for now?

**Comment by joyceerhl** [comment]
On second thought, it might be worse to disable a click to revert when there's also a breakpoint, especially since there's no contributed command in the context menu for reverting that can be used as a fallback. I expect to address this by allowing decorations to have dedicated click targets, therefore assigning to May.

**Comment by joyceerhl** [comment]
Superseded by https://github.com/microsoft/vscode/issues/185814
