### ISSUE TITLE
Unexpected link highlighting in search editor

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#180813]
Testing #179922

![Recording 2023-04-25 at 12 58 12](https://user-images.githubusercontent.com/38270282/234256901-4b7f8e78-0cc0-45ad-ae74-bc4b24c5f616.gif)

**Comment by andreamah** [comment]
Looking through the code, it seems that it comes from returning multiple `DefinitionLinks` from my `DefinitionProvider` for the search editor. https://github.com/microsoft/vscode/blob/ab1a31add4608f484d555e3c791f03321a4dda5f/extensions/search-result/src/extension.ts#L81

The problem is with the `originSelectionRange`  functionality that allows certain lines to be underlined for mouse definition hover. https://github.com/microsoft/vscode/blob/6cea9da535eb70c831255b2fa27935a2504f7703/src/vscode-dts/vscode.d.ts#L6036 

Instead of underlining the lines individually, it underlines the whole range starting with the start of the first range and ends at the end of the last range.

cc @alexdima @jrieken

**Comment by alexdima** [comment]
@jrieken I think the underlines are added by the go to definition feature and not by the link provider. Do you think the API is used incorrectly or is there an issue on the UI side?

**Comment by jrieken** [comment]
The UI receives two locations for the definition request. To draw the underline it merges both into a combined range. Looks like it doesn't check if the origin ranges actually contains the position at which the request has been made - I am unsure if that's on purpose or not. 

So, there might be something in the UI side to fix but the extension also return bogous data. It looks like it return all results when being asks for the definition [of the file name](https://github.com/microsoft/vscode/blob/ab1a31add4608f484d555e3c791f03321a4dda5f/extensions/search-result/src/extension.ts#L81). That's not how it is intended to work and either a the file itself should be used or no definition should be provided

<img width="1461" alt="Screenshot 2023-06-13 at 15 32 19" src="https://github.com/microsoft/vscode/assets/1794099/0ce7ca23-40cf-489c-a17b-c5eec26b324e">

**Comment by andreamah** [comment]
> Looks like it doesn't check if the origin ranges actually contains the position at which the request has been made - I am unsure if that's on purpose or not.

I'm not sure if I understand this correctly. What is the position at which the request had been made and what would be wrong with this being the origin?

> So, there might be something in the UI side to fix but the extension also return bogous data. It looks like it return all results when being asks for the definition [of the file name](https://github.com/microsoft/vscode/blob/ab1a31add4608f484d555e3c791f03321a4dda5f/extensions/search-result/src/extension.ts#L81). That's not how it is intended to work and either a the file itself should be used or no definition should be provided

Makes sense. I haven't actually editing anything in this extension before, so I'll take another look at what was intended when it was first implemented.

**Comment by andreamah** [comment]
@jrieken I'm taking another look at this and I have a few questions about the `DefinitionProvider` API.

I think that the original intention of using a definition provider was this: https://github.com/microsoft/vscode/issues/89467#issuecomment-579653166 so that double-clicking the filename in the search editor would pop up references to the code snippets that are directly below it. Given this, I'm wondering:

- If I want multiple references listed like this, do I get the provider to return more than one `vscode.DefinitionLink` and they would all have the same `originSelectionRange`? 
- What is the difference between the `targetRange` and `targetSelectionRange`? I read the docs and I don't know the difference between the full target range and the span.

**Comment by jrieken** [comment]
The `DefinitionLink` has two ends - the origin at which it starts and its target to where it goes. The origin defaults to the word at the current position (cursor) but can be refined if that isn't good enough. The two target ranges are the whole target and its focal point, think of a function where the whole function (comment, signature, body) is `targetRange` and its name is `targetSelectionRange` - when navigation a definition link the cursor is placed at the target selection range but the whole targetRange is reveal and/or highlighted etc.
