### ISSUE TITLE
Save all pastes contents of unsaved file into current tab

### ISSUE THREAD

**Issue by PooperPig** [Microsoft/vscode#18082]
- VSCode Version: 1.8.1
- OS Version: MacOS 10.12.2

Steps to Reproduce:

1. Open two existing files in the editor
2. Make a small change to one, do not save
3. Move to the tab of the unchanged file
4. Hit cmd-alt-s

The files are saved, and the contents of the changed file pasted into the unchanged file.
See attached screen capture for example on newly created project
[VSCodeSaveAllError.mov.zip](https://github.com/Microsoft/vscode/files/684074/VSCodeSaveAllError.mov.zip)

**Comment by bpasero** [comment]
@PooperPig I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by PooperPig** [comment]
You are right, of course. My fault for not checking this first; my apologies.
the culprit appears to be the Document This extension - I will raise the issue there.

**Comment by bpasero** [comment]
@PooperPig yes please bug them! Thanks.
