### ISSUE TITLE
provide alt text for image outputs

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#180970]
Is it possible to provide any default alt text for this image element? Currently, it is read as a random data:

> 1hj50ih7po3rqbhu39heu77llnngjdfil607d24f9urcv5smm9ma/446c9cd2-f4dd-4107-b78a-e8d9b1b46d23

Maybe, "figure" or "cell {index} figure" or possibly the text output as an alt text?

_Originally posted by @jooyoungseo in https://github.com/microsoft/vscode/issues/176293#issuecomment-1523915040_

**Comment by amunger** [comment]
verification steps: 
1. create a notebook with a cell that outputs an image:

```
import matplotlib.pyplot as plt
plt.plot([1, 2, 3, 4])
plt.ylabel('some numbers')
plt.show()
```

SVG:
```
%config InlineBackend.figure_formats = ['svg']

import matplotlib.pyplot as plt
plt.plot([1, 2, 3, 4])
plt.ylabel('some numbers')
plt.show()
```

2. ensure the vscode built in renderer is being used (change presentation in the output menu to the left of the output)
3. a screen reader should read the text output mimetype for the image e.g. '<Figure size 640x480 with 1 Axes>'

**Comment by roblourens** [comment]
What I see is that it never gets read because it's interrupted by an alert. I am tabbing from the output button into the output, is there something else I should do? It just starts reading it then switches to "Cell 0, the cell output is focused"
![Recording 2023-05-30 at 15 41 53](https://github.com/microsoft/vscode/assets/323878/62dca825-a586-480d-a036-dfccb5a4c29e)

**Comment by roblourens** [comment]
Also shouldn't it work with the Jupyter renderer too?

**Comment by amunger** [comment]
oh interesting. @rebornix - the aria-alert that I can't get to trigger will interrupt alt-text for the image

**Comment by amunger** [comment]
aria-alert has been removed
