### ISSUE TITLE
appear the windows is not responding, but I still can use it.

### ISSUE THREAD

**Issue by boxstudy** [microsoft/vscode#180906]
![image](https://user-images.githubusercontent.com/63934175/234454889-74ba1303-9e4c-4f43-a98a-5333db311740.png)
but I can use it success.

vscode version 1.77
install only C/C++ v1.14.5 extension

**Comment by DonJayamanne** [comment]
> but I can use it success.

This means VS Code hangs only temporarily.

> install only C/C++ v1.14.5 extension

Please could you disable the C++ extension and try again,
If the issue doe not exist with C++ extension disabled, then please file an issue on the C++ extension as its caused by that extension

If you still run into this issue then Please see https://github.com/Microsoft/vscode/wiki/Performance-Issues for creating actionable performance problem issues.
Once you have that information please feel free to re-open this issue or ping here and we'll re-open this, optionally please feel free to create a new issue

/label info-needed

**Comment by arunspacek** [comment]
Hi. I have the same issue. Usually, it takes only a second or two to open vscode in my system. Since yesterday, it takes atleast 15-30 seconds to open. And after it opens, "The window is not responding dialog is shown". I was able to close that dialog and start using vscode, but it has become so slow that it seriously affects my workflow. I'm searching for a solution for hours. Please help.
