### ISSUE TITLE
[html] Configure source root in for html documents

### ISSUE THREAD

**Issue by smallp** [Microsoft/vscode#18096]
- VSCode Version:1.8.1

My workspace is like this:

```
- root
-     application
-     html
-        css
-        assets
```
In the html, the src is this `<script src="/assets/ztree/jquery.ztree.all.min.js"></script>`. So when I click it with ctrl, VScode cannot jump to the right file.

Is there any way to rewrite the src? Or just add a API in extension?

**Comment by aeschli** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.
If you disagree and feel that this issue is crucial: We're happy to listen and to reconsider.
Maybe you want to give it a try yourself and provide the feature through an extension or a PR: We're happy to give advise and get you started.
Thanks for your understanding. Thanks for helping and happy coding!
