### ISSUE TITLE
Introduce enums for common mime types in drop API proposal

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#181076]
Re: https://github.com/microsoft/vscode/issues/180741

Non-urgent API feedback: have we considered introducing enums for common mime types like `files` and `text/uri-list` to reduce the learning curve for extension authors when using this API? This doesn't have to be an exhaustive list of all mime types ever, since that's not really feasible and it's possible to have custom ones, but it would at least help with mime types that are known to the OS or to VS Code

**Comment by mjbvz** [comment]
I'm leery of adding this due to the potential for api creep. Having an incomplete list may also suggest that we only support those types, which isn't correct

I think `text/uri-list` and `text/plain` would be the main candidates. `files` is a special metatype you can use when registering providers but you can't actually use it to retrieve a data transfer item
