### ISSUE TITLE
Regex replace with single space replaces with no space

### ISSUE THREAD

**Issue by mikeblome** [Microsoft/vscode#18111]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|cpptools|ms-vscode|0.9.2|

---

Steps to Reproduce:

1. In an MD file, add this text: HRESULT OnAmbientPropertyChange(DISPID   dispid);

2. fire up replace dialog and insert this regex: \b\s{3}\b and in the replace box put a single literal space
3. expected:  "DISPID dispid" actual: "DISPIDdispid"

**Comment by alexandrudima** [comment]
@mikeblome Very nice find!

FYI @sandy081 The ReplacePattern in `/platform/` was very weird, it was trying to rematch on the specific matched string. i.e. in this case it would try to match again `/\b\s{3}\b/` against `"   "` (3 spaces), which of course would fail.

IMHO the only correct way to fix this in the find widget was to record capture groups in the actual model search and then use them for group substitutions, which is what I have implemented. I did not adopt these changes in the `ReplacePattern` in `/platform/` because I could not understand how it is used by the search service, so I "forked" it.

I am not sure if the search/replace in files suffers from the same issue or not, I leave it up to you to investigate that and adopt the new `ReplacePattern` I've written.

**Comment by sandy081** [comment]
@alexandrudima You are right that replace pattern is performing match on the given text to get the replace string. But, this is not doing on a match. It depends on what value is passed to getReplaceString. To get replace string for the current match, I am passing the text starting from the current match. I agree it is bit weird but rematching was done to fix the look ahead reg ex. I am not sure how this could be the reason, since it was not matching the specific match, instead the complete text from the beginning of the match.

But I liked your approach of recording capture groups while searching. Will investigate how to adopt this in Search.
