### ISSUE TITLE
Contribute command without it showing up in the command palette

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#18117]
I want to contribute a command for a context menu item, which doesn't make sense in the command palette. The command is for the debug call stack, to add a frame to the skipFiles list. Any way to do this? Otherwise it will just be a noop in the command palette.

**Comment by roblourens** [comment]
Actually, maybe it does make sense for it to show up in the command palette, if we have an extension API to get the currently active stack frame, just as we have one to get the active file.

People may want to use the command palette or set a keyboard shortcut for it to blackbox the file they're currently looking at. Thoughts @isidorn?

**Comment by isidorn** [comment]
For first steps I would not expose the active stack frame via the api as it is impossible to just expose parts of the debug world in our api without exposing the whole debug world.

As you say, people may want to use it to blackbox the current file and for that we have api - it is possible to figure out the currently open file and then the debug extension could try to match the uri of the file with the stack frame elements, if it finds something it blackboxes the file, otherwise it is a noop.

**Comment by roblourens** [comment]
Oh duh, of course the active file will let us find the active stack frame... I'll do that.
