### ISSUE TITLE
Search: using "files to include" does not speed up search

### ISSUE THREAD

**Issue by IllNate** [Microsoft/vscode#18123]
- VSCode Version: 1.7.2
- OS Version: Ubuntu 14.04

Steps to Reproduce:

1. Open large directory with many files
2. Open search and enter term 
3. Use "files to include" to filter results to one directory with no subdirectories
4. Start search

Search takes a LONG time. It would be nice if filtering the results using "files to include" would speed up the search.

**Comment by roblourens** [comment]
The thing is that if you set 'files to include' to `foo/bar`, it doesn't just search `/foo/bar` from the root, it searches for any `.../foo/bar` subtree in the workspace. It actually translates this to `[foo/bar/**, **/foo/bar]` and searches the whole tree for any matching path. So we would have to change the way that field works. Is there actually a way to do this that I'm missing, @chrmarti or @sandy081?

I think this could be misleading at least for the case of right-clicking in the file explorer and selecting 'find in folder', because it will... find in other folders too.

In Sublime I can use `./foo/bar` to search only in that folder relative to the open folder.

**Comment by roblourens** [comment]
Search is now provided by ripgrep which is faster and smarter about applying these patterns. And #18334 will help.
