### ISSUE TITLE
Debug Pause not working on VSCode 1.8.1

### ISSUE THREAD

**Issue by pieandcakes** [Microsoft/vscode#18121]
- VSCode Version: 1.8.1
- OS Version: Ubuntu 14.04, Windows 10 Anniversary

Steps to Reproduce:

1. Attach or launch using Microsoft C++ extension
2.  Try and break all (pause).

Expected - Break into application
Actual - Break command isn't sent to debugger.

**Comment by chuckries** [comment]
This is also repro-able with the C# extension.

**Comment by pieandcakes** [comment]
If a breakpoint is hit first, then pause is coming through

**Comment by isidorn** [comment]
Currently after vscode sends all breakpoints and after the `configurationDone` request it asks for the debug adapter for all the threads via `threads` request [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/debugService.ts#L255).

From then on if new threads appear vscode should be notified via the [ThreadEvent](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/common/debugProtocol.d.ts#L128).

When debugging is stopped vscode will still ask for all the threads.

With that in mind here is what is happening for C++ and C#
1. Debugging is started, vscode asks for threads debug adapter returns none
2. Pause action is clicked - vscode is unaware of any threads, thus it can not stop any - noop

In order to fix this issue the C++ or the C# adapter should return a thread list for the inital request or should fire a 'thread' event if these threads are becoming live some time afterwards.

Hope this analysis makes sense - closing this issue as vscode is behaving as expected and C++ and C# extension should fix this on their end.
This was previosly working due to an ugly workaround on our end where if we did not find a thread we would pause a thread with ID = 0 (this has been removed now).

**Comment by chuckries** [comment]
@isidorn How does vscode choose which thread id to use for the pause command?

**Comment by isidorn** [comment]
@chuckries as all in the debug UI, the pause command is scoped per focused stack frame. To whatever thread the focused stack frame belongs that thread will get paused

**Comment by pieandcakes** [comment]
@isidorn We don't provide stack info if we are running but I did attempt to select a different thread and hit the `pause` button and it still comes through as the last threadId to come through. 

We do a `break all` instead of pausing on a specific thread so we don't verify the id that comes through.

**Comment by isidorn** [comment]
@pieandcakes You do not have to provide the stack info, but you should provide if some threads get created or not.
As for the break all that is up to your adapter to handle the pause event as it likes. 

If you are seeing the pause sending an incorrect id that might be an unrelated bug. Probably you have to select a stack frame, and not a thread. You could also right click on a thread and click pause.
