### ISSUE TITLE
(feature request) Scroll Binding

### ISSUE THREAD

**Issue by GitClickOk** [Microsoft/vscode#18137]
- VSCode Version: 1.8.1
- OS Version: Windows 10 AU

Please, refer to [Vim Scroll Binding](http://vimdoc.sourceforge.net/htmldoc/scroll.html#scroll-binding):

> Occasionally, it is desirable to bind two or more windows together such that
> when one window is scrolled, the other windows are also scrolled.  In Vim,
> windows can be given this behavior by setting the (window-specific)
> 'scrollbind' option.  When a window that has 'scrollbind' set is scrolled, all
> other 'scrollbind' windows are scrolled the same amount, if possible.  The
> behavior of 'scrollbind' can be modified by the 'scrollopt' option.

Its really nice with with 2 VSCode panels, side by side, we can have that option too.

**Comment by rebornix** [comment]
@mjbvz this feature has similarities with markdown scrolling one. Another user case for scrolling event.

**Comment by mjbvz** [comment]
@rebornix Yes, this type of scenario is worth considering for  #5047

When @kieferrm and I discussed the potential design of #5047 yesterday, we were generally in favor of a higher level api for scrolling synchronization rather that individual events. One current thought would have the workbench understand the links between documents and be able to synchronize their scrolling behind the scenes..

**Comment by samirageb** [comment]
I find myself needing this functionality more and more when comparing config files for provisioning resources. Anyone doing config management would benefit from this.

**Comment by alexandrudima** [comment]
To compare files, please use (in the explorer) Right Click -> Select For Compare. Then Right Click -> Compare With ...

---

To keep the number of issues in our inbox at a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: we look at the number of votes the issue has received and the number of duplicate issues filed. Thank you for your time and understanding.

If you disagree and feel that this issue is crucial: we're happy to listen and to reconsider.
