### ISSUE TITLE
Copy/Paste line is not putting it to new line

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#181489]
Regression range: https://github.com/microsoft/vscode/compare/9ab88c7abc4d90e67c94ac341bc0fee7679c5556...70dcd62d397867fe03626f938139b834950a985c

Steps:
* put cursor at end of line
* copy & paste

🐛 the newline is not in the beginning

![Recording 2023-05-04 at 10 40 21](https://user-images.githubusercontent.com/900690/236155506-ea71fe08-5f5b-4a2e-ab3f-2299fbf6423b.gif)

**Comment by hediet** [comment]
I'm quite sure this is caused by https://github.com/microsoft/vscode/commit/6384b9bcdf8f2b11988ad2339242955f400895be

In older builds it would bail here:
![chrome_7l8h7Falye](https://user-images.githubusercontent.com/2931520/236166955-61f42e25-1b56-47b3-9994-b039d76947b3.png)

In the latest nightly of monaco editor, it doesn't.

**Comment by mjbvz** [comment]
As a temp fix, I'll make it so that if we are only pasting text and there are no external paste providers, we don't use the copy paste contribution at all and instead fall back to using the editor's copy paste logic

This, https://github.com/microsoft/vscode/issues/181550, and  #181486 are all a little tricky to handle with copy paste providers. Ideally the providers would not have to know about these special cases and we would just handle them automatically
