### ISSUE TITLE
Tabs (as in tabs vs spaces) make vs code lag and crash

### ISSUE THREAD

**Issue by TheKnightCoder** [Microsoft/vscode#18150]
- VSCode Version: Code - Insiders 1.9.0-insider (d384271ffb5655cee1ddf8f93f51cd892ee2cc40, 2017-01-03T07:10:03.605Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|tortoise-svn|fantasytyx|0.1.1|
|PowerShell|ms-vscode|0.8.0|

---

Steps to Reproduce:

1. for some reason sometimes tabs make vs code crash/lag
2. especially after copy paste

**Comment by bpasero** [comment]
@TheKnightCoder you talk about "tab" as being "tab vs spaces" or the "tab UI control"?

**Comment by TheKnightCoder** [comment]
Tab vs spaces.... So the actual tab on the keyboard... Indenting

**Comment by alexandrudima** [comment]
@TheKnightCoder Can you please try disabling emmet?

`File` > `Preferences` > `Keyboard Shortcuts` and add this rule:
```
{ "key": "tab", "command": "-editor.emmet.action.expandAbbreviation" }
```

emmet has some well known bugs where it loops forever.

**Comment by ramya-rao-a** [comment]
@TheKnightCoder I believe what you are experiencing is a lag the first time you press TAB.
This is because of the lazy loading we do for emmet and is being tracked in #17220

Therefore, closing this one as duplicate.

If you don't use emmet much, then follow @alexandrudima 's suggestion and unbind TAB and the short cut for emmet expansions

If you see the lag not just the first time you press TAB, then please let us know, we can re-open this issue for further investigation
