### ISSUE TITLE
"Unbinding" by using empty command in keybindings.json no longer works in v1.78

### ISSUE THREAD

**Issue by nikita-r** [microsoft/vscode#181654]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.78.0
- OS Version: Windows 10

Steps to Reproduce:

1. Bind `command: ""` in order to remove any system binding (used to work in v1.77.)  See the screencap: in particular, I wanted to access the menu bar `Run` via a "mnemonic" as opposed to toggling regex search by `Alt+r`.
2. Press `Alt+r`: in v1.78, it now errors out with `command '' not found` instead of invoking the `Run` menu as it used to in v1.77.

Please let me know if there is now another workaround to unbind all system bindings at once...  Unbinding each system shortcut individually is not workable, since new ones are constantly added...  `Alt+r` is just one example, another one that I found in my config is `{ "command": "", "key": "ctrl+shift+a" }` which is useful in the Web version in order to always pass `Ctrl+Shift+a` to Chrome.

![image](https://user-images.githubusercontent.com/53914057/236519488-348dbd6f-c702-47d2-a0e5-a41a001f6a8c.png)
---
![image](https://user-images.githubusercontent.com/53914057/236519548-7979d199-44c9-4cfb-878b-60d492170931.png)

**Comment by af4jm** [comment]
I've got `{ "key": ".", "command": "" }` so that auto-complete doesn't insert random stuff as I'm typing, but since updating to 1.78 `.` gives the same `command '' not found` error in the original poster's screenshot, and does NOT type a `.` into the editor

**Comment by ulugbekna** [comment]
hello everyone!

Thank you for filing this issue, @nikita-r . 

I think you should be able to achieve what you want using the command `noop` (a command that doesn't do anything), eg

```json
    {
        "key": "cmd+i",
        "command": "noop"
    }
```

Please, let me know if this doesn't solve the problem. 

---

Usually, having an empty command name is an oversight rather than an intentional decision, so we're trying to warn the user when they have such a keybinding. 

---

You can also remove a specific keybinding if you like - https://code.visualstudio.com/docs/getstarted/keybindings#_removing-a-specific-key-binding-rule

**Comment by nikita-r** [comment]
No, @ulugbekna, `"noop"` does not achieve what I want.

I does not do what @af4jm wants, either — please read our comments.

We do not want a shortcut to do *nothing* (`"noop"` captures the keyboard event and does nothing,) we want it to be passed to "environment", so to speak:
1. Menu as mnenomic
2. Editor as character
3. Terminal as control code
4. Chrome keyboard shortcut

So, we have a bunch of use-cases where the long-standing behaviour is broken.

> we're trying to warn the user

Empty commands do not just appear in someone's config by accident...  The stronger justification would be to notice that the shortcuts that were "unbound" this way do not appear in the "Keyboard Shortcuts" UI, which is a UI issue, which by the way is in no way resolved by the new behaviour.  Alternative: return the original behaviour and show empty commands in the "Keyboard Shortcuts" UI.

Please re-open this issue.

Maybe it can be re-opened with an alternative solution, like providing explicit `"command": "unbind"`, but, as it stands now, the new behaviour breaks existing long-standing use-cases with no alternatives.

**Comment by af4jm** [comment]
as @nikita-r said, this is a breaking change of behavior that's been in VSCode wince long before v1.0, and there is no work around that gets back to the original behavior

**Comment by ulugbekna** [comment]
Oh, now I understand the problem. Thank you very much! Sorry for the confusion and the regression. We'll work on fixing this ASAP.

**Comment by ulugbekna** [comment]
@nikita-r Does putting `^noop` as the command ID achieve what you want? I tried it on Mac & Windows, to my understanding, this does what you want. 

Prefixing a command ID with a caret (`^`) runs the command but also doesn't prevent the propagation of the event to the system.

----

@af4jm Could you also try the workaround with putting the command ID `^noop` and report back if that does what you expect? 

I'm not exactly sure why auto-complete would "insert random stuff" in the first place. You usually need to accept a completion item with "enter" or "tab".

**Comment by af4jm** [comment]
to both of your questions... yes

`^noop` works like an empty string used to... and by setting `"editor.suggest.selectionMode": "never"` and commenting out the keybinding, I also get the typing experience I want... because yes, by "random" I meant whatever happened to show up in the intellisense popup

**Comment by af4jm** [comment]
a possible "fix": update the docs to cover this breaking change (the docs still say to use `""`) & update the keyboard shortcuts to change `"command": ""` to `"command": "^noop"`... and leave the new behavior as is

**Comment by ulugbekna** [comment]
The old behavior will be restored in this week's release - 1.78.2. Thank you everyone for help and sorry for the inconvenience!

**Comment by ulugbekna** [comment]
# How to verify this is fixed: 

## If you're on **Windows**: 

1. Create a keybinding with `key` set to `alt+r` and `command` to an empty string. 
2. Open search input (`ctrl+f` within an open editor/file)
3. Make sure that pressing `alt+r` opens the system menu `Run` rather than toggling the regex search. Also, you shouldn't see an error notification "command '' not found"

---

## If you're on **Mac:** 

1) Create a keybinding in your `keybindings.json` (invoke command `Open Keyboard Shortcuts (JSON)`) with `"key"` matching a system keybinding (e.g., if you're on Mac, `cmd+h` works) and `command` set to some command, e.g., "workbench.files.action.focusFilesExplorer". Trigger the new keybinding and notice that the command is indeed is invoked.

2) Create a keybinding below the one you created above, with the same `"key"` but with `"command"` set to an empty string. 

3) Trigger your keybinding. It should trigger the system keybinding rather than the command bound with the first keybinding. Also, no error notification "command '' not found" is shown.
