### ISSUE TITLE
Better git integration

### ISSUE THREAD

**Issue by nitzcard** [microsoft/vscode#181636]
Now that vscode is almost complete I think it is wise to add better github support.
I always find myself the need for branches compare with working branch, git graph, etc...
Those things can be found in an extension (such as git lens) or an IDE, but I prefer the real deal.

thanks.

**Comment by lszomoru** [comment]
@nitzcard, thank you very much for the issue. I would recommend that you file individual issues for the various feature request so that we can track them independently. While we are planning on making improvements to the built-in git extension, we will not be covering all functionality that is enabled by extensions.
