### ISSUE TITLE
Explorer rendering is slow

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#18178]
re #15455

* close all editors, open explorer with ~50 files/folders visible
* add profiling instruction for viewlet restore (`console.profile, console.profileEnd` in https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/electron-browser/workbench.ts#L289)
* reload the workbench
* 🐌 restoring the explorer takes ~450ms, 200ms of that time is spend in the tree, a significant amount of time is spend in `FileLabel`, `ResourceLabel`, `IconLabel`

[CPU-20170105T174926.cpuprofile.zip](https://github.com/Microsoft/vscode/files/687785/CPU-20170105T174926.cpuprofile.zip)

**Comment by bpasero** [comment]
@jrieken I am not seeing the same or any significant amount of time spend in the labels when I run. The labels should not have an impact on the number of folders expanded because they only kick in to the visible viewport of the tree. I also see some viewlet unrelated times in that profile (spawn, JSON??)
 
Attached is a trace of expanding every folder in the `extensions` directory of our source tree (including all of `node_modules` which gives a large test set). 

Most of the time is spend in `paths.isEqualOrParent` which I am able to fix. Looking at the second trace, most time is imho spend resolving files from disk and updating the tree (which is https://github.com/Microsoft/vscode/issues/18180).

Before:
[CPU-20170112T081858_before.cpuprofile.zip](https://github.com/Microsoft/vscode/files/700923/CPU-20170112T081858_before.cpuprofile.zip)

After:
[CPU-20170112T081926_after.cpuprofile.zip](https://github.com/Microsoft/vscode/files/700924/CPU-20170112T081926_after.cpuprofile.zip)

**Comment by jrieken** [comment]
I drilled very deep into the `setInput` and `expandAll` call found the renderer to take time (apart from the tree burning time). Unsure where I have seen the 200ms but I see this (in the original trace). Also looking in the traces

![screen shot 2017-01-12 at 10 35 19](https://cloud.githubusercontent.com/assets/1794099/21884334/258059d2-d8b3-11e6-899c-45e9140cce87.png)

**Comment by jrieken** [comment]
Yeah, unsure where that time came from. With newer version I don't see it anymore. Maybe some dom-distorition effects?
