### ISSUE TITLE
Tree slow!

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#18180]
Look at the screen shot form the attached profile. I might be reading this wrong, but it seems that the tree looses 10ms between `expandAll` and `onModelEvents` but just emitting events to/from itself. 

![screen shot 2017-01-05 at 17 53 52](https://cloud.githubusercontent.com/assets/1794099/21689244/0f1cf88c-d370-11e6-8dec-a81734ddb2fb.png)

[CPU-20170105T174926.cpuprofile.zip](https://github.com/Microsoft/vscode/files/687801/CPU-20170105T174926.cpuprofile.zip)

**Comment by joaomoreno** [comment]
Repro steps?

**Comment by jrieken** [comment]
Open explorer with 50 items, start profiler, reload workbench

**Comment by joaomoreno** [comment]
Are they all direct children of the root? Are some expanded?

**Comment by jrieken** [comment]
@joaomoreno Unsure what your question meant, but notice that the profile is attached to this issue

**Comment by joaomoreno** [comment]
For the tree, we gotta get rid of

1. Promises
2. Events

**Comment by joaomoreno** [comment]
Nothing will be done on the old tree. A few new tree widgets have started to appear in our code base: `IndexTree`, `ObjectTree` and `DataTree`, all of them considerably improving performance across all features, the former 2 implementations completely dropping promises and events. New issues will be created for adopting the new tree widgets in order to benefit from this.
