### ISSUE TITLE
Detecting moves in the diff editor

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#181902]

**Comment by ElianCordoba** [comment]
I’m working in this problem too, although my approach is rather a 180 from myers algorithm and character by character diffing. [Here](https://github.com/ElianCordoba/better-diff) is my work, still very WIP

**Comment by ElianCordoba** [comment]
Hi @hediet, thank you for taking the time to look at my work. I'm keen to contribute! I believe there is _significant_ room for improvement in the field of text diffing.

Here are a few quick thoughts. I wanted my tool to be integrated within VSCode so you could check the diff without leaving the editor. There were two ways to do this, but neither convinced me:

- Use API to create a view: I found this was somewhat limited. The text decorating API wasn't flexible enough to implement a somewhat complex diff UI, which involves more than just marking additions and removals with green and red text. More on this bellow.
- Go the Iframe route: This could work but it would introduce unnecessary complexity. I'll revisit this option once my project matures, but I would prefer to use the API to leverage all the work you've put into the components.

My tool produces an array of changes, which are objects that holds the necessary infomation to, along side with the sources, render the change. These are a `type`, which can be `deletion`, `addition`, or `move`. The two ranges, and, in the case of moves a `moveID`.

When rendering, I take the original source code and locate the ranges to highlight them – additions in green, deletions in red. Moves affect both sources, which I color in blue.

While attempting to implement the move UX with the current API, I encountered a blocker, I couldn't figure out how to create a custom hoverable range, this was what I was trying to archive:

![move-diff](https://github.com/microsoft/vscode/assets/34920585/50364d92-a8b5-437d-a645-dd51a04edf39)

For these two ranges, my plan was to color them in blue and, when any of these are hovered over, find the corresponding code with the same ID (on the opposite side) and highlight that too.

### Brief note on move UX

I realized that displaying code movements required some effort to make it clear where the code had moved. If the code only moved to the line below, it would be easy to spot because it would be immediately visible. However, if the code moved to the bottom of the file, you would need a way to link the before and after, and this becomes even more crucial when multiple moves are involved.
Ideally, when you highlight a move, you could see this in the minimap and click to select the move to keep it focused. These features are especially useful when the move is far off and you have to scrolling to view the new location.
A more ambitious idea was to draw some kind of arrow linking the two ranges. Here's an example from another project that uses arrows to visually link ranges.

![image](https://github.com/microsoft/vscode/assets/34920585/4ffd4215-9aaf-4d63-8534-2d30ba5cac09)

This is the [website](https://meldmerge.org/#features) of that project

**Comment by hediet** [comment]
Some [example](https://microsoft.github.io/monaco-editor/playground.html?source=v0.39.0-dev.20230524#XQAAAALIDQAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscxQrOXoBJ5fGqgZNtIIGM6BnaWNlFk-HzucdJmwgffCJwWZ7P2mi3pjMKBhAZkCYzCwNyRuscN-jbeqHOmuKRyQNR1ayaLp7K4KNvsJfKI-AWqYHltVvpVHUy7RWjrJcoriUEdLQ24vhmS-97M4jQVZcyBvDv70Psz0bIXdaxjNAgN8JpOxUdF0PhmTrVAJX3yUSr1NzzR1gRoeq5ThygHM5lcZNrWgCGGc41BOomTF11Jn-xCRytf9XoslH4P-VhkRNQDr1APR7xxEfkwSTZSuLEpC7Sa3KtHcRQa2J7gbgVd4UO4qnaEj8F7cqTHKAco1mVV5od3cnk8-gkR6dmn7gLwe47oIe3T4tEhKW6DB_JC2k4GIGeMQN3iY7zxkTakbP_WLwfgJWEwDXBgr67ZfM8ppghPP6N8JE8-HqOGlmJKnbL_iYmez4Nnw9xJ_I84Ks6x6dMnUZhd6It440ZR5fKCXksoRogqszBaXUnDuOQIn3-8q2jtDDZU2CbXtEm23n9Vp2GxNpKNbtSDcHYtZzR8lv6GNJDLVVKxrteLpafTH_vhzmMidrHHwHOPEqwkhGWEquvf9P5sXn6-nNt_SE-QeNeRQB40WrSVHf2X4pGx5uvC9XCi1Pp0WN2DEZzXc2RDQU5AzYlqAWE7c8-m6yd0obLiRVYmmmlGxFOBV4nb-s2RihQ_gJBKI-Xdxhfk8t0rOwN2Q6AxCSSOcfEpc14gufwZqidXJlaA4g7VWGtRiAX9OI16UehhJ9QJkU8BT529s4rQ0PHYfLkJhBh_a_sOPpC0OQki75EauaaiGu4WeKmCc_eXtANhRxzssRPZQ56DmzE_v3tBoGHF-W5Uf60bfSOnC9_pBGkcysKqFLinzyTuGE4_JbQaF3OXbIt_6E0Gv7Y4kmW25Is6DgLu-J_bTG98yDyThenV5wIsQ7afAFbiHy65YQKyZZ5ugSOf2sHWlywxM3QRD_7lO5S7KbMVH3rTGyvsYJEw7SOZHqHZhs_7OJNt_-llw9QBKuieISYvBhnu3en7rRNpISess0Y-sA5um0l6_vAG1OFKKvzUGig)

It would be nice to show [this diff](https://microsoft.github.io/monaco-editor/playground.html?source=v0.39.0-dev.20230524#XQAAAAJEBgAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscw_L5IRgmSatbNyrNa50VLHWwDOn0YI7IfU0xJ0CGYU1vRtgnKPmZzQcQ1L9J7fCG48SpY2EIkpDE0S8hEos94TYukUPQeT6EwT6hD0m3NKBrk0qi3c05l8H9a73uwLhXeJEs-lcun8iegyMFQLzgeYgV3vSbw_-Rk5W-8fhgCgQ7A-EQ9wvPF84A15jr8fLLmPiXsnf_T7z09u7aonxDwbk0gyV4dEJWEKbqNax-4PfDq8i8m5GJJtpHJD8d3EZVg36CQbHD7-GrqqMhBZvwDE0mbISuGgsXcX0oxOO72aaxDrX6kkG-O63UiHdha8WaBHZvLEV8m0FIIaNeZxm4JnfCH83mQ12QIBscB9bq8RcHKjrP3tVhVIh6wMUrx-6WLlXWRb1X-kePjq4uhXPLl1rTtyu9i1M-pE5hFqjQxb1uYTqWe3zvHczeARx_StWQhZ5nOom9VQxJzoAQL43sDOMc7m7V7iqYfUXPPYxrwaLFYYZqUiIZNmxPYU2P6f_AWoWkz2HMsec7FJvVO8lvK5AP5etgugnBvF9BFd848TpZAv-E2tAUjP4LI-vJTHwyy6Qj7ceMmdc7ajw9aKs5gxbJoz28hMqMpsPMvMMPxEXQaMKh2PRwmAo0VB4bPJ6eOJSiF-X7-g9u0if32iyfM).

**Comment by hediet** [comment]
This feature is now available in the latest stable.

set `"diffEditor.experimental.useVersion2": true` and `"diffEditor.experimental.showMoves": true` to try it.
