### ISSUE TITLE
Horizontal scrolling is visually confusing

### ISSUE THREAD

**Issue by wavebeem** [Microsoft/vscode#18200]
- VSCode Version: 1.8.1
- OS Version: macOS

#### Steps to Reproduce:

1. Disable line wrapping
2. Open a file large enough to make horizontal scrolling appear
3. Scroll to the right
4. Observe that it's hard to tell where the line numbers gutter ends and the code begins

![image](https://cloud.githubusercontent.com/assets/176815/21703532/ae6f2922-d367-11e6-99d0-dea72b09a78b.png)

#### Expectation

My expectation would be either a line shows up or a little drop shadow shows up on the line numbers when not scrolled all the way to the left, providing me a way to tell what I'm looking at.

#### Mockup

![image](https://cloud.githubusercontent.com/assets/176815/21703573/0fd6385e-d368-11e6-9215-6633270a13a6.png)

**Comment by alexandrudima** [comment]
@bgashler1 I need your guidance here. It is straight-forward for me to render a line in there, but I think it would look bad if I do it :). Any thoughts/mocks on what we could do?

**Comment by wavebeem** [comment]
Just a suggestion, but the shadow that Sublime Text uses is pretty nice.

![image](https://cloud.githubusercontent.com/assets/176815/21770925/37f65d76-d63a-11e6-91e6-cab491072ee4.png)

![image](https://cloud.githubusercontent.com/assets/176815/21770957/52cc0808-d63a-11e6-9a77-a020b56ed4ca.png)

**Comment by bgashler1** [comment]
I kind of like the box-shadow idea, because it's in harmony with what we do elsewhere in VS Code to convey layering and separation upon scrolling.

![artboard 1 copy 3](https://cloud.githubusercontent.com/assets/11839736/21790531/e0c04848-d691-11e6-8d02-b74d08dc5d85.png)

A margin background color is something Atom uses (only in the Atom dark theme).  Applying it to us looks like this.
![artboard 1 copy 6](https://cloud.githubusercontent.com/assets/11839736/21790558/128dd87c-d692-11e6-9b16-62fb904241dc.png)

A `backdrop-filter` blur (similar to the glassy look you see in iOS and macOS) on the margin might be cool, also implying your code is subducting under the margin as you scroll.  (However, `backdrop-filter` is still behind a feature flag in Chromium).
NOTE: You have to look a little closer to see this one (purposefully subtle).
![artboard 1 copy 2](https://cloud.githubusercontent.com/assets/11839736/21790535/e73e8ba8-d691-11e6-91ac-9ed81b34ef3e.png)

I agree that the line separator isn't nice looking; plus we don't normally use lines in this way.  We try to only use lines resizable partitions (like between editors).

**Comment by bgashler1** [comment]
One more idea is a text fade on the left margin.  (I dislike it though, because it removes a clean edge that my eyes really want).
![Uploading Artboard 1 copy 4.png…]()

**Comment by wavebeem** [comment]
Box shadow looks the best and is consistent as you said 👍

**Comment by stevencl** [comment]
Thanks for the feedback. We're pruning our list of open issues and since there hasn't been a lot of activity on this issue I'm going to close it for the moment.

**Comment by wavebeem** [comment]
Is there anything I could do to help with this? I could work on an implementation of the shadow approach, possibly?

This is particularly a an issue for me in diff view where you can't use word wrapping
