### ISSUE TITLE
CharWidthReader performance

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#18211]
The character width reader is consuming roughly ~250ms in the open editor cycle. The number is to understood with the knowledge of 'don-distortion'. That is, because it needs to layout and measure things it pays the price of all previous dom modifications, e.g from creating the workbench etc. However, there are things that can be improved

* [x] use an off-don canvas to measure character width (no possible as we have dropped support of IE9) @jrieken, @alexandrudima 
* [ ] don't make the editor do the work twice. The `BaseEditor` first create an editor widget with the default config just to immediately update the config to the 'real' config @bpasero 
* [x] consider running the measure logic before the dom is 'busy'. The theory (needs confirmation) is that the measuring takes longer the more busy and dirty the render tree is @alexandrudima

**Comment by jrieken** [comment]
[editor-restore1.cpuprofile.zip](https://github.com/Microsoft/vscode/files/689378/editor-restore1.cpuprofile.zip)

**Comment by bpasero** [comment]
@alexandrudima @jrieken I also noticed a little bit of time spend in `WindowManager.getPixelRatio()` which seems to have similar bad characteristics on Windows. This seems to be used for the overview ruler.

**Comment by jrieken** [comment]
re https://github.com/Microsoft/vscode/issues/18211#issuecomment-270858456 - That's interesting. I assume that's a similar problem to "dom distortion", enforcing a full layout.

**Comment by alexandrudima** [comment]
IMHO reading the width of characters using the `ctx.measureText` method is not slow per-se, it is simply triggering a forced dom layout and all the dom changes that happened before it will show up in the profile time. i.e. try that code in a standalone HTML page, it is quite fast.

**Comment by bpasero** [comment]
@alexandrudima what about we do this very early on workbench construction and I can pass this into the editor as some kind of option?

**Comment by alexandrudima** [comment]
@bpasero :+1:

The thing has a static cache anyways (such that all editors share the measurements). Someone simply needs to call `CSSBasedConfiguration.INSTANCE.readConfiguration(bareFontInfo)` very early on.

To get a `bareFontInfo`, some minimal editor logic is needed (i.e. the part that defines a line height if it is configured to be `0`, etc.).

But this has to happen with the correct font and the editors should not be created with the default font and then switched to the configured font in order to benefit from it.

If you can point me to some location where I can add this call in the workbench start-up (i.e. needs configuration service) I can extract the editor logic that deduces the line height and do it.

**Comment by bpasero** [comment]
@alexandrudima the configuration service gets created very early before any DOM element is added and is ready after the `initialize()` call here: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/electron-browser/main.ts#L135

That is, ready without extensions of course because they are not loaded yet. But including any user and workspace settings.

Maybe add it into the [`shell.open()`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/electron-browser/shell.ts#L378) method?

**Comment by alexandrudima** [comment]
Added to shell.open(). There remains the issue that the editor is created with no options and then the options are updated.

**Comment by bpasero** [comment]
Pushed a change to create the editor with the real config. There is still more calls to `updateOptions` due to extensions contributing to the config and the theme service doing some thing in there, however the options should not change for the editor after being created.
