### ISSUE TITLE
Check for places to use fast URI serialisation (like HistoryService)

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#18215]
![screen shot 2017-01-06 at 10 32 30](https://cloud.githubusercontent.com/assets/1794099/21713823/1c868380-d3fc-11e6-8b48-4ab192a42694.png)

When profiling the `"[renderer] restore editor view state"` you will notice that ~10ms are spend in the history service comparing the current input with old input. The time is spend in `handleEditorEventInHistory` which is busy retrieving data from storage, building URIs and comparing them against other URIs. The code uses `URI.parse` and `URI.toString` which have many safe guards and checks and are consequently not super-fast. However, when you can trust URI, like in this case as they are generated/stored/retrieved from use you should use `URI.toJSON` and `URI.revive` or better and easier [`marshalling#stringify/parse`](https://github.com/Microsoft/vscode/blob/master/src/vs/base/common/marshalling.ts#L9) which are drop in replacements (and used by workers/ext-host communication)

**Comment by jrieken** [comment]
[CPU-20170106T103803.cpuprofile.zip](https://github.com/Microsoft/vscode/files/689491/CPU-20170106T103803.cpuprofile.zip)

**Comment by bpasero** [comment]
Ok, I was not aware of that. I think there may even be more places where `URIs` are ending up in local storage.

**Comment by bpasero** [comment]
@jrieken there are two things around `URI.toJSON()` and `URI.revive()` that are unclear to me:

**URI.toJSON()**
When I have a file `URI` and I call `URI.toJSON()`, the resulting JSON is very verbose, specifically it looks like this:

```json
{
	"scheme": "file",
	"authority": "",
	"path": "/Users/bpasero/Documents/ticino-playground/Position.ts",
	"fsPath": "/Users/bpasero/Documents/ticino-playground/Position.ts",
	"query": "",
	"fragment": "",
	"external": "file:///Users/bpasero/Documents/ticino-playground/Position.ts",
	"$mid": 1
}
```

Since I am persisting resources, I would favour shorter data. First of all, why do we not just leave out the values for `authority`, `query` and `fragment` if they are empty values. 

Then, there is duplication in `path`, `fsPath` and `external`. So overall it would increase the data that travels between processes from a simple single string, to 3 times that size. I wonder if I am not better off using `URI.file()` and just storing `URI.fsPath` in local storage?

**URI.revive()**
This method is still calling `URI._validate()` which seems odd since I created the `URI` from a call to `toJSON()`, so I would like to avoid the extra validation happening if possible.

**Comment by jrieken** [comment]
Since `revive` is a public method I still need check for data correctness, also it's not slow, doesn't do any allocations just a few checks. 

Wrt `toJSON` the whole point of it is to be verbose such that the data doesn't need to be generated again. It's basically a dump of the whole internal state of URI, everything is duplicated/contained in `external` but that's the point. We can think about leaving out empty strings, but not about stuff like `fsPath` vs `path` vs `external`.
