### ISSUE TITLE
Add support for ctrl+k + (second command) in the Define Keybinding helper

### ISSUE THREAD

**Issue by tht13** [Microsoft/vscode#1823]
The define keybinding helper is great, but it would be nice If it could allow a second keybinding to be added it it detects ctrl+k have been entered. Like the ctrl+k ctrl+k that is needed to open the helper in the first place.
Thanks

**Comment by joaomoreno** [comment]
@alexandrudima fyi

**Comment by alexandrudima** [comment]
@tht13 I like the thought. Perhaps <kbd>Space</kbd> could extend the input into a chord. The reason is that <kbd>Ctrl</kbd>+<kbd>K</kbd> is just one possible chord start, a chord can start with any keybinding.

So the flow could be:
* type key combination
* press <kbd>Space</kbd>
* now you can enter a second level key combination

**Comment by tht13** [comment]
That would be a logical way to enable this feature :+1:

**Comment by alexandrudima** [comment]
Since many releases, the widget has been changed and this works.
