### ISSUE TITLE
Git - hide conflict icon when conflicts is resolved

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#182464]
![image](https://github.com/microsoft/vscode/assets/41773861/daac268b-0d39-4644-bf29-a0923ed955a1)

**Comment by lszomoru** [comment]
Could you please provide repro steps and possible a recording (https://gifcap.dev) to investigate this issue? Thanks!

**Comment by tjx666** [comment]
https://github.com/user-attachments/assets/3bd238c4-0ca3-4dff-980f-de45a8d052f1

**Comment by lszomoru** [comment]
@tjx666, thank you!

**Comment by lszomoru** [comment]
@tjx666, what is the output of `git status` after you have resolved the conflict?

**Comment by tjx666** [comment]
@lszomoru <img width="1512" alt="Image" src="https://github.com/user-attachments/assets/20152aad-13b3-4520-8331-5986e33c3b38" />

**Comment by lszomoru** [comment]
Thanks! the "Source Control" view is rendered based on the `git status` output and since git status still lists the resource with the "both modified" state, VS Code will render the `!` decoration. Manually staging the file will update the resource and remove the `!` decoration. Closing the issue as "by design".
