### ISSUE TITLE
Make `Log Storage Database Contents` easier to use

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#182678]
Run the command `Log Storage Database Contents`. Nothing happens

Can we show the dev tools or open an output view that gets focus?

From describing a user how to help us debugging an issue with storage:
https://github.com/microsoft/vscode/issues/182627#issuecomment-1550343756

**Comment by bpasero** [comment]
The action also runs in browsers where we cannot open devtools automatically. We cannot use the output view because we actually show a real table:

<img width="1394" alt="image" src="https://github.com/microsoft/vscode/assets/900690/4056f196-b270-4536-ac93-162e487befdd">

But we can inform the user via dialog.

**Comment by bpasero** [comment]
For the other action "Log working copies" I will reveal the window log where it is logged to.
