### ISSUE TITLE
Hide language modes without alias

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#18262]
To implement #6461 I had to define an artificial language id representing the tags inside a JSX document. The language id is used for being able to associate the language configuration with the jsx block comment tokens.

![image](https://cloud.githubusercontent.com/assets/6461412/21745431/46adae48-d502-11e6-86b4-a2e817c44d75.png)

The jsx-tags language currently shows up in the language drop down. IMO it would be better if we hide all languages that don't only consist of an id but no alias.

![image](https://cloud.githubusercontent.com/assets/6461412/21745423/eaef5f5c-d501-11e6-9e61-7cd6e291264e.png)

**Comment by aeschli** [comment]
FYI @alexandrudima

**Comment by bpasero** [comment]
@aeschli I am not sure we can do that because there maybe extensions that are not defining an alias but still want to be selectable?

@alexandrudima moving to you to confirm that this request makes sense. 

I would also probably need more API to understand that a language was contributed with no alias around here: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/parts/editor/editorStatus.ts#L862

**Comment by alexandrudima** [comment]
Ok, now interpreting languages contributed with `alias: []` (i.e. an empty array) as languages that don't want to show up in the picker.

**Comment by alexandrudima** [comment]
This feature request does not need a test plan item because a unit test verifies the new behaviour.
