### ISSUE TITLE
Can't move tabs around (again)

### ISSUE THREAD

**Issue by W3Warp** [microsoft/vscode#182758]
Type: <b>Bug</b>

For some inexplicable reason the future to move tabs around, left and right, down to terminal, split to compare, or whatever stops working...

I have already tried (not a clean one, that would be too much work) to reinstall. I've also tried disabling all extensions, no change. And looked for settings about "drag and drop" that are unchanged. (updated to be more "clear")

### UPDATE: The issue is resolved for the moment by signing out and into Windows 10.

VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:39:26.248Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.94GB (47.11GB free)|
|Process Argv|--crash-reporter-id 4329be14-42bd-4c1e-ada3-49597ab3359a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (100)</summary>

Extension|Author (truncated)|Version
---|---|---
codegeex|AMi|1.1.7
vscode-openai|And|1.1.7
vscode-django|bat|1.10.0
Bito|Bit|1.0.135
solargraph|cas|0.24.0
npm-intellisense|chr|1.4.4
path-intellisense|chr|2.8.4
codeque|Cod|0.21.1
vscode-test-explorer-status-bar|con|1.2.0
vscode-micromamba|cor|0.1.16
rapid-json-search|dat|0.1.8
vscode-eslint|dba|2.4.0
conda-wingman|DJS|0.2.1
python-environment-manager|don|1.0.4
python-extension-pack|don|1.7.0
xml|Dot|2.5.1
vscode-go-syntax|dun|0.0.18
windows-explorer-context-menu|ele|3.2.1
pythonsnippets3|Eri|3.3.18
prettier-vscode|esb|9.12.0
font-switcher|eva|4.1.0
docker-explorer|for|0.1.7
remotehub|Git|0.56.1
go|gol|0.38.0
vscode-test-explorer|hbe|2.21.1
swift|Kas|0.2.0
vsc-python-indent|Kev|1.18.0
vscode-fix-checksums|leh|1.1.0
node-module-intellisense|lei|1.5.0
markdown-auto-index|Leo|1.0.1
vscode-python-test-adapter|lit|0.7.1
regexp-preview|Lou|0.1.5
MagicPython|mag|1.1.0
python-path|mge|0.0.14
document|min|2.2.1
vscode-docker|ms-|1.25.1
dotnet-interactive-vscode|ms-|1.0.4258030
vscode-dotnet-runtime|ms-|1.6.0
vscode-kubernetes-tools|ms-|1.3.11
autopep8|ms-|2023.4.0
black-formatter|ms-|2023.2.0
gather|ms-|2022.3.2
isort|ms-|2022.8.0
python|ms-|2023.8.0
vscode-pylance|ms-|2023.5.20
jupyter|ms-|2023.4.1011241018
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.292.0
remote-wsl|ms-|0.78.5
azure-repos|ms-|0.32.0
cmake-tools|ms-|1.14.31
cpptools|ms-|1.15.4
cpptools-extension-pack|ms-|1.3.0
powershell|ms-|2023.5.0
remote-repositories|ms-|0.34.0
test-adapter-converter|ms-|0.1.7
php-docblocker|nei|2.7.0
hash|net|0.0.4
gremlins|nho|0.26.0
vscode-python-typehint|njq|1.5.1
pip-installer|Pet|0.0.4
vscode-versionlens|pfl|1.5.0
material-icon-theme|PKi|4.27.0
tsimporter|pmn|2.0.1
quicktype|qui|12.0.46
ruby|reb|0.28.1
java|red|1.18.0
vscode-xml|red|0.25.0
vscode-yaml|red|1.12.2
vs-code-prettier-eslint|rve|5.1.0
sourcery|sou|1.3.0
autoimport|ste|1.5.4
code-spell-checker|str|2.20.4
python-task-provider|ton|0.3.0
cmake|twx|0.0.17
sort-lines|Tyr|1.9.1
explorer-manager|Uro|0.0.5
errorlens|use|3.11.0
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscodeintellicode-completions|Vis|1.0.22
vscodeintellicode-insiders|Vis|1.1.10
vscode-swiftlint|vkn|1.8.3
vscode-concourse|vmw|1.46.0
vscode-java-debug|vsc|0.50.0
vscode-java-pack|vsc|0.25.11
vscode-java-test|vsc|0.38.2
vscode-maven|vsc|0.41.0
vscode-icons|vsc|12.4.0
gistfs|vsl|0.4.1
jinja|who|0.0.8
vscode-ruby|win|0.28.0
JavaScriptSnippets|xab|1.8.0
php-debug|xde|1.32.1
markdown-all-in-one|yzh|3.5.1
php-intellisense|zob|1.1.3
vscode-proto3|zxh|0.5.5

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstes627:30244334
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30705553
azdwalk:30721579
pythonms35:30701012
pythonfmttext:30731395
pythoncmv:30739700
fixhidewlkth:30730051
pythongtdpathcf:30739705

```

</details>

**Comment by bpasero** [comment]
Thanks for creating this issue! To help narrow it down, please take the time to follow below steps. Thanks a lot and happy coding 🙏 

### Is the issue caused by an Extension?
Stop VS Code and from the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If it still reproduces, jump to the next chapter.

If you see it is an issue with the extension, please run the command `Start Extension Bisect` and follow the instructions to find the extension that is causing this issue.

<img width="631" alt="image" src="https://user-images.githubusercontent.com/900690/228760008-d5790ad1-74da-46a2-917f-e1bd26281ca8.png">

Please report the issue to the extension causing this.

### Is the issue caused by VS Code Core?
If the issue is not caused by an extension, it is maybe caused by your configuration. Try to run `code --disable-extensions --user-data-dir <directory>` where `<directory>` is an empty folder. This will ensure Code is starting with a fresh data directory, e.g. no specific settings and without any extensions running. 

If it still reproduces, it was maybe fixed already in our nightly release. Please download from https://code.visualstudio.com/insiders/ and see if you can reproduce the issue.

Finally, to help us narrow down what change caused the issue, please run the following command to find the build. It will start previous releases of VS Code insiders to see where the regression was introduced:
* `npx --yes vscode-bisect@latest`
* follow the instructions until you found the offending build
* report back the commit range in this issue

Thanks!

**Comment by bpasero** [comment]
Ok this is not helpful.
