### ISSUE TITLE
White squares in terminal

### ISSUE THREAD

**Issue by XVItokaz** [microsoft/vscode#182909]
- VS Code Version: 1.78.2
- OS Version: OS Catalina, 10.15.7

Hi

Checked i all kind of forums and can´t find the issue i have with whit squares in the terminal

I have tried to change color themes, but is still there both on light and dark themes.

As soon i type in the terminal, under the time i´m type and after, i have a lot of whit squares all over the place

What can the issue be and what can i do to change it? I have tried to reinstall vscode two times, but no luck.

![image](https://github.com/microsoft/vscode/assets/121265451/95412590-4858-4206-a0a6-de52d17a2fd7)

**Comment by meganrogge** [comment]
Thanks for creating this issue! To help narrow it down, please take the time to follow below steps. Thanks a lot and happy coding 🙏 

### Is the issue caused by an Extension?
Stop VS Code and from the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If it still reproduces, jump to the next chapter.

If you see it is an issue with the extension, please run the command `Start Extension Bisect` and follow the instructions to find the extension that is causing this issue.

<img width="631" alt="image" src="https://user-images.githubusercontent.com/900690/228760008-d5790ad1-74da-46a2-917f-e1bd26281ca8.png">

Please report the issue to the extension causing this.

### Is the issue caused by VS Code Core?
If the issue is not caused by an extension, it is maybe caused by your configuration. Try to run `code --disable-extensions --user-data-dir <directory>` where `<directory>` is an empty folder. This will ensure Code is starting with a fresh data directory, e.g. no specific settings and without any extensions running. 

If it still reproduces, it was maybe fixed already in our nightly release. Please download from https://code.visualstudio.com/insiders/ and see if you can reproduce the issue.

Finally, to help us narrow down what change caused the issue, please run the following command to find the build. It will start previous releases of VS Code insiders to see where the regression was introduced:
* `npx --yes vscode-bisect@latest`
* follow the instructions until you found the offending build
* report back the commit range in this issue

Thanks!

**Comment by XVItokaz** [comment]
Hi, thanks 

I did follow all steps

Now when i have done the last one (npx --yes vscode-bisect@latest), you said report back the commit range in this issue? Copy from terminal or did i misunderstood  you to do anything else?

**Comment by XVItokaz** [comment]
How ever, here is all steps and my testin in vs code insider

`[build] total 200 builds with roughly 8 steps
[build] downloading build from https://az764295.vo.msecnd.net/insider/0ef4b667664f652165f239a5cb74cbde6cd65fbe/VSCode-darwin.zip...
[build] unzipping build to /var/folders/69/y_qrpbd53yg9h8n72z4j5j840000gn/T/vscode-bisect/.builds/0ef4b667664f652165f239a5cb74cbde6cd65fbe...
[build] starting desktop build 0ef4b667664f652165f239a5cb74cbde6cd65fbe...
✔ Is 0ef4b667664f652165f239a5cb74cbde6cd65fbe good or bad? › Good
[build] downloading build from https://az764295.vo.msecnd.net/insider/b1ad3f934ca87b76dac5cf3533fb172d1c30e6ba/VSCode-darwin.zip...
[build] unzipping build to /var/folders/69/y_qrpbd53yg9h8n72z4j5j840000gn/T/vscode-bisect/.builds/b1ad3f934ca87b76dac5cf3533fb172d1c30e6ba...
[build] starting desktop build b1ad3f934ca87b76dac5cf3533fb172d1c30e6ba...
✔ Is b1ad3f934ca87b76dac5cf3533fb172d1c30e6ba good or bad? › Good
[build] downloading build from https://az764295.vo.msecnd.net/insider/2c51b3de329d48f45eabe80316f099f46fd3a5cc/VSCode-darwin.zip...
[build] unzipping build to /var/folders/69/y_qrpbd53yg9h8n72z4j5j840000gn/T/vscode-bisect/.builds/2c51b3de329d48f45eabe80316f099f46fd3a5cc...
[build] starting desktop build 2c51b3de329d48f45eabe80316f099f46fd3a5cc...
✔ Is 2c51b3de329d48f45eabe80316f099f46fd3a5cc good or bad? › Bad
[build] downloading build from https://az764295.vo.msecnd.net/insider/761de52b5e297a8ea461dd501c897cc74c407733/VSCode-darwin.zip...
[build] unzipping build to /var/folders/69/y_qrpbd53yg9h8n72z4j5j840000gn/T/vscode-bisect/.builds/761de52b5e297a8ea461dd501c897cc74c407733...
[build] starting desktop build 761de52b5e297a8ea461dd501c897cc74c407733...
✔ Is 761de52b5e297a8ea461dd501c897cc74c407733 good or bad? › Bad
[build] downloading build from https://az764295.vo.msecnd.net/insider/cbf35328c8357175b9cd747823f39ade987c3d3c/VSCode-darwin.zip...
[build] unzipping build to /var/folders/69/y_qrpbd53yg9h8n72z4j5j840000gn/T/vscode-bisect/.builds/cbf35328c8357175b9cd747823f39ade987c3d3c...
[build] starting desktop build cbf35328c8357175b9cd747823f39ade987c3d3c...
✔ Is cbf35328c8357175b9cd747823f39ade987c3d3c good or bad? › Bad
[build] downloading build from https://az764295.vo.msecnd.net/insider/f31dffc7f9b93a1cdef21243ec30dea7d489a615/VSCode-darwin.zip...
[build] unzipping build to /var/folders/69/y_qrpbd53yg9h8n72z4j5j840000gn/T/vscode-bisect/.builds/f31dffc7f9b93a1cdef21243ec30dea7d489a615...
[build] starting desktop build f31dffc7f9b93a1cdef21243ec30dea7d489a615...
✔ Is f31dffc7f9b93a1cdef21243ec30dea7d489a615 good or bad? › Good
[build] downloading build from https://az764295.vo.msecnd.net/insider/06962b2c0159c6f6a076969ec7ad571b13724ceb/VSCode-darwin.zip...
[build] unzipping build to /var/folders/69/y_qrpbd53yg9h8n72z4j5j840000gn/T/vscode-bisect/.builds/06962b2c0159c6f6a076969ec7ad571b13724ceb...
[build] starting desktop build 06962b2c0159c6f6a076969ec7ad571b13724ceb...
✔ Is 06962b2c0159c6f6a076969ec7ad571b13724ceb good or bad? › Bad
[build] downloading build from https://az764295.vo.msecnd.net/insider/2da5a0024fe2ca407f741f19340f1a10f4d692af/VSCode-darwin.zip...
[build] unzipping build to /var/folders/69/y_qrpbd53yg9h8n72z4j5j840000gn/T/vscode-bisect/.builds/2da5a0024fe2ca407f741f19340f1a10f4d692af...
[build] starting desktop build 2da5a0024fe2ca407f741f19340f1a10f4d692af...
✔ Is 2da5a0024fe2ca407f741f19340f1a10f4d692af good or bad? › Good
[build] 06962b2c0159c6f6a076969ec7ad571b13724ceb is the first bad commit after 2da5a0024fe2ca407f741f19340f1a10f4d692af.
✔ Would you like to open GitHub for the list of changes? … yes

Run the following commands to continue bisecting via git in a folder where VS Code is checked out to:

git bisect start && git bisect bad 06962b2c0159c6f6a076969ec7ad571b13724ceb && git bisect good 2da5a0024fe2ca407f741f19340f1a10f4d692af
`

**Comment by XVItokaz** [comment]
Any help on this or what should i do?

**Comment by Tyriar** [comment]
Disabling gpu acceleration should workaround the problem by setting `"terminal.integrated.gpuAcceleration": "off"`
