### ISSUE TITLE
no new folder option or icon

### ISSUE THREAD

**Issue by ErinWelsh** [microsoft/vscode#183018]
Type: <b>Bug</b>

downloaded and installed vscode but no option or icon for new folder. unistalled and downloaded again and same issue. 

VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:39:26.248Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

**Comment by MrSchneemann** [comment]
It appears that you're experiencing a problem with Visual Studio Code (VS Code) where the option or icon to create a new folder is not available. You mentioned that you have tried uninstalling and re-downloading VS Code, but the problem persists.

To resolve this issue, you can try the following troubleshooting steps:

1. Reset VS Code settings: Launch VS Code, go to the File menu, select Preferences, and then select Settings. In the settings search bar, type "reset settings" and click Preferences: Open Workspace Settings". From there, click the "..." icon in the upper-right corner and select "Reset Settings.

2. Update VS Code: Check to see if a newer version of VS Code is available. If so, update to the latest version as it may contain bug fixes and improvements.

3. Disable extensions: Some extensions in VS Code can interfere with certain features. Disable any extensions you have installed and then restart VS Code to see if the problem is resolved.

Create a new workspace: Try creating a new workspace and see if the option to create a new folder appears in the new workspace. You can create a new workspace by going to the File menu, selecting Add Folder to Workspace, and selecting a new folder.

**Comment by lramos15** [comment]
The explorer was probably moved at some point `CTRL + SHIFT + P` -> `Reset View Locations`
