### ISSUE TITLE
[FR] `"typescript.preferences.importModuleSpecifierEnding": "ts"`

### ISSUE THREAD

**Issue by wenfangdu** [microsoft/vscode#183091]
Currently, we use `"typescript.preferences.importModuleSpecifierEnding": "js"` to add `.ts`, `.tsx`, which feels weird, I suggest adding the `ts` option to `typescript.preferences.importModuleSpecifierEnding`, which would be more accurate.

**Comment by mjbvz** [comment]
Actually this was already handled by 6a9c24cbd05062afea796a06b9fc2f8cdf746a7b. We didn't change the setting value in order to avoid breaking existing but the UI and Intellisense shows that this can be `.ts`

![Screenshot 2023-06-22 at 4 23 51 PM](https://github.com/microsoft/vscode/assets/12821956/7959825e-4b0d-4f35-b289-39994a961c26)

**Comment by wenfangdu** [comment]
@mjbvz How about using:
```ts
if (['js', 'ts'].includes(ending)) {
  // ...
}
```
So that both `js` and `ts` work?
