### ISSUE TITLE
Compare Failing for Large Files

### ISSUE THREAD

**Issue by Suraj-Yadav** [Microsoft/vscode#18327]
- VSCode Version: Code - Insiders 1.9.0-insider (12af9ea6effefeaeecde2107c960ae5222703864, 2017-01-09T07:10:36.676Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|path-intellisense|christian-kohler|1.2.0|
|python|donjayamanne|0.5.5|
|an-old-hope-theme-vscode|dustinsanders|1.1.0|
|text-transform|florianloch|0.1.0|
|ftp-sync|lukasz-wronski|0.3.2|
|MagicPython|magicstack|1.0.3|
|cpptools|ms-vscode|0.9.3|
|material-icon-theme|PKief|1.2.0|
|code-spell-checker|streetsidesoftware|0.14.2|
|cmake|twxs|0.0.15|

---

Steps to Reproduce:

1. Compared two files with approx. 1000000 lines each. Code didn't flag any difference.

![image](https://cloud.githubusercontent.com/assets/6687881/21776785/3c7e50e6-d6c2-11e6-8588-0080867f001e.png)

**Comment by alexandrudima** [comment]
For a long time we had a secondary filter to not sync large buffers over to web workers. Since then, we have improved significantly the memory usage on the worker side + buffers are dropped from memory after 1 min of inactivity + web workers are killed after 5 minutes of inactivity, so I think it is a safe change memory-wise.
