### ISSUE TITLE
Accessibility feature in output cell of notebook with VsCode

### ISSUE THREAD

**Issue by GERMANOCARELLA** [microsoft/vscode#183208]
Hello,
I am using jupyter notebook with VsCode.
Everything works pretty well, but when I display the output of a cell with control+down arrow, the screen reader announces the entire output cell, but I can't scroll through it line by line with the arrow keys.
It would be helpful if the system cursor could scroll within the output cell as in an editor.
I also searched within the options, but could not find one that would enable this feature.
Germano

**Comment by amunger** [comment]
thanks for the feedback, we are currently trying to make some improvements in this exact area.
I was using [this issue](https://github.com/microsoft/vscode/issues/176292) for improving the context when focusing on the cell since, from my experimentation with the screen reader, it tended to jump around to different outputs, but your suggested change might just resolve that issue by better containing the reader within that single output.

**Comment by meganrogge** [comment]
Will be one of the reasons we add https://github.com/microsoft/vscode/issues/184612

**Comment by meganrogge** [comment]
@amunger can you consider doing this in July?

**Comment by amunger** [comment]
verification:

run a cell with output, either click the output to focus it, or press ctrl+down (default)
press alt+F2
output should be presented in an accessible view

**Comment by alexr00** [comment]
I tried to verify with a GitHub Issues notebook, and here's what I get:

<img width="1920" alt="image" src="https://github.com/microsoft/vscode/assets/38270282/29e0396c-4b98-41ea-ac35-d9f368436d29">

This view isn't scrollable via mouse or via keyboard arrow down.

**Comment by amunger** [comment]
strange overflow behavior covered by https://github.com/microsoft/vscode/issues/188838

verification (should only affect ipynb files):

run a cell with output,
either click the output to focus it, or press ctrl+down (default)
press alt+F2
output should be presented in an accessible view
