### ISSUE TITLE
Test: open remote windows from remote explorer

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#183578]
Refs: https://github.com/microsoft/vscode-remote-release/issues/8397

- [x] Windows @bpasero
- [x] macOS @bhavyaus
- [x] Linux @connor4312

Complexity: 3
Authors: @joyceerhl @chrmarti @aeschli

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23183578%0A%0A&assignees=joyceerhl,chrmarti,aeschli)

---

In the remote explorer, remote extensions should now offer two options to connect to a remote window, 1) in the current window and 2) in a new window. These options should be available inline (when you hover over a tree item) as well as in the context menu.

Please install a few remote extensions (Ctrl/Cmd+Alt+O to open remote indicator > select Install Additional Remote Extensions), then open the remote explorer. Verify that all the views offer consistent actions to open a remote.

**Comment by connor4312** [comment]
I think the icon choices are okay, but I would perhaps rework the "new window" icon. To me it looks very much like "new folder" in the default theme, particularly because the little tab in the top-left corner that normally distinguishes the "folder" icon is obscured.

New window:

<img width="36" alt="image" src="https://github.com/microsoft/vscode/assets/2230985/98493eb3-994b-4cd5-ad63-4fb788f00625">

New folder:

<img width="28" alt="image" src="https://github.com/microsoft/vscode/assets/2230985/90f305f6-022c-4cdb-908e-55a647f859e2">
