### ISSUE TITLE
diffEditor.ignoreTrimWhitespace does not work correctly if only whitespace is changed

### ISSUE THREAD

**Issue by spahnke** [Microsoft/vscode#18353]
- VSCode Version: 1.8.1
- Monaco Version: 0.7.0
- OS Version: macOS 10.12

I initially stumbled upon this using the Monaco Editor, but could also reproduce it using VSCode.

Steps to Reproduce (see images below):

1. Create a JS file with a function indented with spaces
2. Create another JS file (or commit the file with git) with the exact same function, but indented with   tabs
3. Diff the two files/versions with `"diffEditor.ignoreTrimWhitespace": true`

The indentation whitespace **is not ignored**.

If you change anything else, such as the function name, the whitespace **is ignored**.

<img width="685" alt="whitespace only" src="https://cloud.githubusercontent.com/assets/25029871/21803032/8448fa00-d728-11e6-8415-ea22cf300615.png">
<img width="684" alt="additional change" src="https://cloud.githubusercontent.com/assets/25029871/21803042/8b34733a-d728-11e6-97ce-bead146d4f07.png">

**Comment by alexandrudima** [comment]
This is unexpected behaviour, we can fix it with some better UI.

The problem is that in the case of whitespace only changes, in vscode, the file shows up in the changes view, and then once you click on it, since whitespace changes are ignored, it shows no diff. We have therefore decided, in the case that trim whitespace is ignored and the diff produces no result, to forcefully unignore trim whitespace.
