### ISSUE TITLE
run selected text

### ISSUE THREAD

**Issue by mingming-ctr** [microsoft/vscode#183689]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. type the code in any file

Node
import puppeteer from "puppeteer";
const fs = require('fs');
2. selected all code.and then ( run selected text )
3. error in terminal:
![errorInVScod](https://github.com/microsoft/vscode/assets/12455138/79052801-fa06-4a0a-8db4-72a6092ab142)

this is an example

if a commandline need much time.
the code after will lost.

```[tasklist]
### Tasks
```

**Comment by mingming-ctr** [comment]
I run it in win10 vscode

**Comment by meganrogge** [comment]
Thanks for creating this issue! To help narrow it down, please take the time to follow below steps. Thanks a lot and happy coding 🙏 

### Is the issue caused by an Extension?
Stop VS Code and from the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If it still reproduces, jump to the next chapter.

If you see it is an issue with the extension, please run the command `Start Extension Bisect` and follow the instructions to find the extension that is causing this issue.

<img width="631" alt="image" src="https://user-images.githubusercontent.com/900690/228760008-d5790ad1-74da-46a2-917f-e1bd26281ca8.png">

Please report the issue to the extension causing this.

### Is the issue caused by VS Code Core?
If the issue is not caused by an extension, it is maybe caused by your configuration. Try to run `code --disable-extensions --user-data-dir <directory>` where `<directory>` is an empty folder. This will ensure Code is starting with a fresh data directory, e.g. no specific settings and without any extensions running. 

If it still reproduces, it was maybe fixed already in our nightly release. Please download from https://code.visualstudio.com/insiders/ and see if you can reproduce the issue.

Finally, to help us narrow down what change caused the issue, please run the following command to find the build. It will start previous releases of VS Code insiders to see where the regression was introduced:
* `npx --yes vscode-bisect@latest`
* follow the instructions until you found the offending build
* report back the commit range in this issue

Thanks!

**Comment by mingming-ctr** [comment]
Thanks for you reply
error persists

I run the code in node.exe(not in vscode)

I paste the follow code and run many times, no error 
searchSelector = "div.MmsUiMaterialModal___tab___1dQI92-24-0 > div.MmsUiMaterialModal___search___1pW_I2-24-0 > div > div > div > div > div.IPT_inputBlockCell_5-66-0 > input"

![1 node_run_ok](https://github.com/microsoft/vscode/assets/12455138/e2251585-7179-420f-a7be-506ed864944a)

I start vscode by your sugguest
code --disable-extensions --user-data-dir G:\gitsrv\pdd


![2start_vscode](https://github.com/microsoft/vscode/assets/12455138/b1b7bd80-e11e-41c6-8728-cc5c4a58d8da)


type node in terminal
copy the code and paste in terminal,sometimes may be have error.
let searchSelector = "div.MmsUiMaterialModal___tab___1dQI92-24-0 > div.MmsUiMaterialModal___search___1pW_I2-24-0 > div > div > div > div > div.IPT_inputBlockCell_5-66-0 > input"


if above not error.
copy the follow code and paste ,run many times. you will see error.

searchSelector = "div.MmsUiMaterialModal___tab___1dQI92-24-0 > div.MmsUiMaterialModal___search___1pW_I2-24-0 > div > div > div > div > div.IPT_inputBlockCell_5-66-0 > input"

![3 error](https://github.com/microsoft/vscode/assets/12455138/ea3f8c30-7786-47ea-b2e7-8dbe016a2f0f)


environment

![4 version](https://github.com/microsoft/vscode/assets/12455138/c7fa9f77-7bf8-4e9b-b5d6-0a4a1ce14921)


The error only in node.
python,powershell,cmd ... all is ok.

**Comment by mingming-ctr** [comment]
my version is up to date
![5 lastvertion](https://github.com/microsoft/vscode/assets/12455138/1d0b51c3-aaf0-4d5d-a930-4c8cc2a1f53e)

**Comment by mingming-ctr** [comment]
i create  a new environment
setup win10,nodejs,vscode in vmware
and then test.

i find error less.  but have.

eg.
node 1.js  is ok in terminal

type node in terminal, copy 1.js content .you will find error.

the code runnning is not same as 1.js

**Comment by mingming-ctr** [comment]
eg.
![6](https://github.com/microsoft/vscode/assets/12455138/798dae5d-e404-41f9-9cc4-945c8ed77d0f)

**Comment by meganrogge** [comment]
here's what happens for me:

![Screenshot 2023-06-20 at 11 48 33 AM](https://github.com/microsoft/vscode/assets/29464607/2d890da8-b5cc-4e29-81e7-a8ed0391e925)

it indicates what to do about this:

```
Uncaught:
SyntaxError: Cannot use import statement inside the Node.js REPL, alternatively use dynamic import
> const fs = require('fs');
```

**Comment by mingming-ctr** [comment]
I think javascript like this.

const puppeteer = require('puppeteer');

node terminal must use javascript

You use TypeScript
import puppeteer from "puppeteer"

**Comment by meganrogge** [comment]
Sorry, i'm having a hard time understanding what your issue is. 

Is it that you have certain text selected and that text isn't fully pasted / run in the terminal?

**Comment by mingming-ctr** [comment]
Sorry, I asked this question twice,
This one is the same as the link below.
Can this question be closed？
https://github.com/microsoft/vscode/issues/185591
