### ISSUE TITLE
shell tasks are unavailable in the current environment. -mvn projects 

### ISSUE THREAD

**Issue by carlosparra95** [microsoft/vscode#183602]
Does this issue occur when all extensions are disabled?: Yes/No
Yes 

- VS Code Version: 1.78.2 
- OS Version: 22621.1702

Steps to Reproduce:

Hi can someone please help me.

When I try to create a maven project I get the following error message:

The terminal process failed to launch: Path to shell executable "cmd.exe" does not exist.

My command prompt is working good, but I'm just unable to create a maven project, I have the extension pack for java installed.

**Comment by meganrogge** [comment]
Thanks for creating this issue! To help narrow it down, please take the time to follow below steps. Thanks a lot and happy coding 🙏 

### Is the issue caused by an Extension?
Stop VS Code and from the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If it still reproduces, jump to the next chapter.

If you see it is an issue with the extension, please run the command `Start Extension Bisect` and follow the instructions to find the extension that is causing this issue.

<img width="631" alt="image" src="https://user-images.githubusercontent.com/900690/228760008-d5790ad1-74da-46a2-917f-e1bd26281ca8.png">

Please report the issue to the extension causing this.

### Is the issue caused by VS Code Core?
If the issue is not caused by an extension, it is maybe caused by your configuration. Try to run `code --disable-extensions --user-data-dir <directory>` where `<directory>` is an empty folder. This will ensure Code is starting with a fresh data directory, e.g. no specific settings and without any extensions running. 

If it still reproduces, it was maybe fixed already in our nightly release. Please download from https://code.visualstudio.com/insiders/ and see if you can reproduce the issue.

Finally, to help us narrow down what change caused the issue, please run the following command to find the build. It will start previous releases of VS Code insiders to see where the regression was introduced:
* `npx --yes vscode-bisect@latest`
* follow the instructions until you found the offending build
* report back the commit range in this issue

Thanks!

**Comment by starball5** [comment]
Possibly related on Stack Overflow: https://stackoverflow.com/q/76491706/11107541

**Comment by starball5** [comment]
@meganrogge would you mind giving a brief explanation of why this is "completed"? Is it because it needs more details and the details were not given in time?

**Comment by meganrogge** [comment]
I believe it will be fixed as of insider's tomorrow. Can you test tomorrow and lmk?

**Comment by starball5** [comment]
@meganrogge I don't have a setup to reproduce the issue (sorry). Do you have a link to whichever PR / commit fixes the issue (just for bookkeeping purposes)?

**Comment by meganrogge** [comment]
https://github.com/microsoft/vscode/pull/187159
