### ISSUE TITLE
Tasks::problemMatcher should highlight problems in output log and make files clickable

### ISSUE THREAD

**Issue by kobalicek** [Microsoft/vscode#18369]
I tried everything, but I'm not able to make vs-code to highlight problems in output log and make that problems clickable (click on file that will bring me to the file/line/column of the problem).

I know I can press Ctrl+Shift+M and see all problems, but that's kinda something I don't want to do if I already see the output log. I want to see something Visual Studio does when compiling the project, for example...

**Comment by o-lim** [comment]
👍

**Comment by dbaeumer** [comment]
Support for this will come with the new terminal runner but not with the old output runner.

**Comment by o-lim** [comment]
With the new terminal runner, when the build is done it outputs a "press any key to continue" prompt, and once you hit a key all of the output disappears, which is very undesirable.  Is there any plan to allow the output to remain after the build has completed?  This is necessary because often the problem matchers do not capture all of the information needed to analyze a problem, and with the output gone, you would be forced to run the build again to see the full error message.

**Comment by dbaeumer** [comment]
Yes, we will support to not close the terminal.

**Comment by dbaeumer** [comment]
Dups #21928
