### ISSUE TITLE
Expose detected-link color to themes

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#18378]
Extracted from discussion at #18357

**Comment by sandy081** [comment]
@alexandrudima With respect to detected-link, this was not covered before becuse, I think this is foreground color and AFIK we cannot contribute foreground colors from themes other than tokens. Hence this was not handled then.

**Comment by alexandrudima** [comment]
`linkForeground` it is.

**Comment by joshpeng** [comment]
How exactly do I set this in my themes? I've tried many scope combinations.

```
<dict>
        <key>name</key>
        <string>String URLs</string>
        <key>scope</key>
        <string>string.detected-link, detected-link, string.linkForeground, linkForeground</string>
        <key>settings</key>
        <dict>
          <key>foreground</key>
          <string>#C678DD</string>
        </dict>
      </dict>
```
But it's still not accepting my tmTheme color for it. I'm trying this on the latest VSC Insider's Build.

**Comment by alexandrudima** [comment]
@joshpeng In the same way `caret`, `foreground`, `invisibles`, `selection`, etc. can be specified: in a block without any `scope`.


https://github.com/Microsoft/vscode/blame/master/extensions/theme-monokai/themes/Monokai.tmTheme#L14

**Comment by akamud** [comment]
The way VSCode is handling links is kind of weird for theming at the moment (at least compared to Atom).

Since there is no scope controlling the link coloring, this happens when I put a `linkForeground` rule:

![image](https://cloud.githubusercontent.com/assets/954102/22629062/5d74c654-ebc6-11e6-92fe-0b679e92acb0.png)

Comparted to Atom:
![image](https://cloud.githubusercontent.com/assets/954102/22629067/82ded5d8-ebc6-11e6-9afb-5782cb4090fd.png)

How can we avoid this?

**Comment by alexandrudima** [comment]
@akamud there are two links in your first screenshot. Both links get the purple color (presumably you picked a purple color, right?)

I'm not sure what is weird about it, would you like to be able to differentiate between links that are relative and links that are absolute?

**Comment by akamud** [comment]
I'm sorry for not explaining myself.

Yes, I used `linkForeground` to get a purple link, but I think it is weird for links to be purple even when they are commented code or a string inside HTML.  
Atom exposes TM Scopes so I can color links inside strings, JSON and commented code differently. VSCode does not provide a way of doing this, since the only scope applied is the global scope `linkForeground`.

Before the TM Scopes changes I could achieve this in VSCode using the `detected-link` scope, the same scope Atom used.  
Was this intended? Do you plan on providing a way to achieve this again?

**Comment by alexandrudima** [comment]
Thank you, I understand now. Yes, unfortunately, this is intended behavior.

Links in VS Code are not detected from TM grammars, but rather from [document link providers](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L2609). So links come in "from the side", on top of TM scopes (from the extension host or from our built-in http:// , https:// or file:// link detectors).

By the time the view needs to paint the links, it now only has access to the token color and no longer to the underlying TM scopes that produced the token color. So, at this time, it is not possible to distinguish links inside strings vs links inside comments and color them differently.

**Comment by akamud** [comment]
I see, thanks for taking the time to explain this :)
