### ISSUE TITLE
unable to findout file

### ISSUE THREAD

**Issue by Rahul91025** [microsoft/vscode#183737]
Type: <b>Bug</b>

i unable to find a files i donot know why . i just shiffted java language to dart , after sometime i obseve that all the files of java get vanished.so ,tell what i do ,the file contening all the important data

VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:39:26.248Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5500U with Radeon Graphics          (12 x 2096)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|5.86GB (1.64GB free)|
|Process Argv|--crash-reporter-id 6579b100-b1dc-44b6-8e61-9f5b09b0d84f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
flutter-snippets|ale|3.0.0
dart-code|Dar|3.64.0
flutter|Dar|3.64.0
run|eto|0.1.1
code-runner|for|0.12.0
cmake-tools|ms-|1.14.31
cpptools|ms-|1.15.4
cpptools-extension-pack|ms-|1.3.0
awesome-flutter-snippets|Nas|4.0.1
java|red|1.18.0
cmake|twx|0.0.17
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscode-java-debug|vsc|0.50.0
vscode-java-dependency|vsc|0.22.0
vscode-java-pack|vsc|0.25.11
vscode-java-test|vsc|0.38.2
vscode-maven|vsc|0.41.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
2i9eh265:30646982
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
pythonfmttext:30731395
pythoncmv:30739700
fixhidewlkth:30730051
pythongtdpathcf:30739705

```

</details>

**Comment by Adesoji1** [comment]
@Rahul91025 This seems to be an issue related to file system, IDE or a potential mis-operation rather than a language-specific issue.

Before proceeding to technical solutions, please verify these points:

Did you manually or accidentally delete the Java files?
Did you use any source control system like Git where your files could be stored?
Did you check the Recycle Bin or Trash folder of your system?
Did you search for your files using Windows search functionality to see if they've been moved to a different folder?
If you've verified these points and still couldn't find your files, you can try the following steps to recover them:

1. Check VS Code's settings.json: You might have added Java or its related folders into the files.exclude or search.exclude settings. If this is the case, VS Code might be hiding these files from you. To check this:

Open your settings (File > Preferences > Settings or Ctrl + ,)
Search for files.exclude and search.exclude settings.
Make sure none of these settings are causing your Java files to be hidden.
2. Using a File Recovery Tool: If the files were deleted, and also removed from your Recycle Bin, then you might need to use a file recovery tool to recover your deleted files. Tools like [Recuva](https://www.ccleaner.com/recuva) can help you to recover accidentally deleted files.

3. System Restore: If you have a system restore point created before the files got deleted, you can restore your system to that point and get your files back.

**Comment by andreamah** [comment]
Please file this with the java or dart extensions, as it would pertain to them. This sounds like this might be a version control issue.

Java Extension: https://github.com/redhat-developer/vscode-java/issues
Dart Extension: https://github.com/Dart-Code/Dart-Code/issues
