### ISSUE TITLE
Very minimal settings dropdown highlighting in Dark Modern

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#183845]
In Dark Modern it's hard to tell what is hovered. Since there's an extremely subtle hover decoration, it looks like something is missing. I like the blue background in Dark+

![Recording 2023-05-30 at 10 54 22](https://github.com/microsoft/vscode/assets/323878/c0704885-eace-4777-8dde-2ddc8e7fe310)

**Comment by daviddossett** [comment]
This looks like it's caused by the settings dropdown list background color unintentionally being too light. 

Updated to match other list widgets:

<img width="443" alt="CleanShot 2023-06-07 at 14 45 41@2x" src="https://github.com/microsoft/vscode/assets/25163139/64a0da9e-83ff-4526-a81f-ac45b187249e">

<img width="240" alt="CleanShot 2023-06-07 at 14 45 50@2x" src="https://github.com/microsoft/vscode/assets/25163139/7f0769ad-4217-42b7-ae90-be7125626262">
