### ISSUE TITLE
Can't do regex search after opening notebook

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#183858]
- Open a notebook
- I want to do a regex search in normal text files in my workspace, but the option is disabled

<img width="136" alt="image" src="https://github.com/microsoft/vscode/assets/323878/cc0fa71d-ef74-4b3b-bddc-9bb18a200ad5">

This caught me off guard, I see that I have to disable searching in rendered markdown to enable regex mode, which makes sense, but I don't want to search in notebooks right now. Does it search in rendered markdown by default?

One thing that would be helpful would be to have a tooltip to tell me _why_ regex search is disabled

**Comment by andreamah** [comment]
I believe that I originally had it like this because notebook outputs and markdown preview doesn't support regex search, but I agree that it's unexpected to just disable regex straight-out. For now, I'm going to keep regex enabled no matter which options in the notebook find widget are checked (since, by default, all are checked). 

That would probably have a smaller impact on users, since it'll just do a plain non-regex search when looking in outputs/previews.
