### ISSUE TITLE
map8.six doesn't display

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#183840]
Testing #183563

This worked with snake.six but something is wrong with this image and nothing is displayed when I cat it https://github.com/saitoha/libsixel/blob/master/images/map8.six

**Comment by Tyriar** [comment]
@jerch any ideas why map8.six wouldn't work in xterm-addon-image? It looks fairly simple

**Comment by jerch** [comment]
It seems the image is smaller than 1 row in height - since the addon only supports vt340 cursor mode, this line will get overwritten by the next shell prompt right after image output. To work around this, just append a NL, e.g. by appending and empty echo command:
```
$> curl -s https://raw.githubusercontent.com/saitoha/libsixel/master/images/map8.six && echo

**Comment by Tyriar** [comment]
Oh, is this something that other terminals do that we don't then? Could we force the empty line for small images?

**Comment by j4james** [comment]
It's worth noting that XTerm updated their sixel cursor positioning algorithm to more closely match the VT340 behavior, so that map8.six test would also now be overwritten in Xterm, unless followed with an echo. And I know Contour also handles that case correctly.

It's been a long time since I tested any other terminals, and I suspect most are still wrong, but I'm hopeful that they'll all eventually start to converge on the correct behavior now that XTerm has gone that route (it's not perfect yet, but it's definitely improving).

**Comment by hackerb9** [comment]
Last I check XTerm worked properly for map8.six. 

Note that if you have a short prompt (`PS1='$ '`) you should actually see the image if you cat it to the screen. It's just that your prompt usually overwrites it. 

Here's a screenshot from my VT340:

![image](https://github.com/microsoft/vscode/assets/10174223/bfdcab9e-b7b6-49a5-bab8-be02db54d975)

[Not visible in this image: The flashing text cursor after the first `cat` was inverting the olive color to a surprising purple.]

**Comment by jerch** [comment]
> [Not visible in this image: The flashing text cursor after the first `cat` was inverting the olive color to a surprising purple.]

Just wondering - is this some sort of color or palette inversion going on? Do you have an idea, whats the algo behind this? (No need to explicitly test it, we deviate from text cursor coloring in other fields as well, and also on purpose...)

**Comment by j4james** [comment]
> Just wondering - is this some sort of color or palette inversion going on?

On the VT240 (at least as implemented in MAME), the pixels in the screen buffer are represented by two-bit color table indices, and the cursor inverse just XORs those values with `0b11`. So 0 is swapped with 3 (typically black and green), and 1 is swapped with 2 (typically blue and red).

On the VT340 you've got four-bit color table values, but I suspect its cursor inverse is implemented as an XOR of `0b0111` rather than `0b1111`. That way your default colors (7 on 0) will get flipped to 0 on 7, rather than 8 on 15, which is more in line with what you'd expect from a non-graphic terminal.

The behavior of the cursor on the map8 image appears to confirm that theory. The green in that image is color index 2, so XORing that with `0b0111` gives you 5, which has been mapped to magenta. If it were XORed with `0b1111` you would get 13, which isn't used in that image, but defaults to light cyan.

**Comment by jerch** [comment]
@j4james Its really fascinating, what level of insight your are able to deduct from scarce DEC related resources. You are prolly right with the XORing, sounds perfectly plausible to me.

**Comment by hackerb9** [comment]
> @j4james Its really fascinating, what level of insight your are able to deduct from scarce DEC related resources. 

Yes, @j4james is a living DEC resource.  Back in the early 80s the president of DEC was bragging about having literally a six-foot shelf of documentation. Now, we've got a six-foot @j4james of knowledge.

And, of course, he was right about xor with `0b0111`. 

[![image](https://github.com/microsoft/vscode/assets/10174223/539eb29d-b468-4bf9-8dd4-237d9ec00269)](https://github.com/hackerb9/vt340test/blob/main/colormap/defaultcolormap.md)

When using the default VT340 colormap, the inverse color will always be the same saturation and lightness with the hue angle rotated by 180 degrees. For grays (saturation = 0), changing the hue has no effect, so instead the lightness is offset by around 50 percentile points.
