### ISSUE TITLE
Tree checkbox API: Improve `manuallyManageCheckboxSelection`

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#183829]
Testing #183549

It's difficult to know what `manuallyManageCheckboxSelection` dooes without reading the docs.

From what I observe, this setting is that whether the checked state of a parent node is based on the checked states of the (visible) children.

maybe the name can be `syncCheckboxSelectionWithChildern`

**Comment by alexr00** [comment]
The name is confusing, but it should be something that is false by default. Maybe `doNotSyncCheckboxSelectionWithChildren`? It also manages parents though, so that name is still misleading.

**Comment by eamodio** [comment]
I'm having trouble even understanding reading the doc:

```
/** 
 * By default, when the children of a tree item have already been fetched, child checkboxes are automatically managed based on the checked state of the parent tree item. 
 * If the tree item is collapsed by default (meaning that the children haven't yet been fetched) then child checkboxes will not be updated. 
 * To override this behavior and manage child and parent checkbox state in the extension, set this to `true`. 
 */
```

Is it about the parent reflecting its state on its child, or is it the children's state reflected on the parent? Or a mix of both?

If the setting is off (the default), what happens in the following cases?

- If a node has 2 children and it is expanded, and you check one child?
  - Does the parent show a "mixed" checked state?
  - If you check the other child does the parent show a fully checked state?
- If a node has 2 children, and its expanded, and you check the parent?
  - Does it check each of the children?
  - What happens if the node is collapsed? Is it different if it's collapsed, but has been loaded?

How does the setting change that behavior? Does it mean you handle everything completely manually?

Its long by maybe `manageParentChildCheckboxStateManually` or just `manageCheckboxStateManually`, e.g. no automatic behaviors (assuming that is true)

**Comment by aeschli** [comment]
I would suggest to make the `manual mode` the default. It's easier to explain.

**Comment by alexr00** [comment]
> I would suggest to make the manual mode the default. It's easier to explain.

Per API discussion, this puts more work on the extension developer and also easily results in laggy checkboxes. The best user experience is for automatic to be the default.

> Unchecking child does not uncheck parent

This is a bug, which I will fix!

> When expanding for the first time, the parent check state is not applied to children (or the new child state is not applied to parent)

Also a bug.

> Is it about the parent reflecting its state on its child, or is it the children's state reflected on the parent? Or a mix of both?

Both.

> -  If a node has 2 children and it is expanded, and you check one child?
>   - Does the parent show a "mixed" checked state?

No, we don't currently support the "mixed" state. The parent will show unchecked.

>   - If you check the other child does the parent show a fully checked state?

Yes.

> - If a node has 2 children, and its expanded, and you check the parent?
>   - Does it check each of the children?

Yes.

I like `manageCheckboxStateManually`, I will likely change to that. I'm also going to add some ascii art to the doc to try to illustrate all of the above. 

>   - What happens if the node is collapsed? Is it different if it's collapsed, but has been loaded?

If it's collapsed and not loaded then the children will not get checked until the parent is expanded. If it's collapsed and loaded then the children will be immediately checked.

> How does the setting change that behavior? Does it mean you handle everything completely manually?

The setting will remove all this behavior and you have to handle everything completely manually.

**Comment by alexr00** [comment]
@aeschli I will suggested it at the next API sync, but I think this is a property we want to be stable for the whole tree, not just individual tree items.

**Comment by alexr00** [comment]
Do these doc additions make the behavior clearer?

https://github.com/microsoft/vscode/blob/07a8ee33b22ed0f78b93fef5a7eb95f47549e38d/src/vscode-dts/vscode.proposed.treeItemCheckbox.d.ts#L51-L87

**Comment by aeschli** [comment]
The examples help!

Here's my attempt to summarize:

By default, the checked state of a parent node summarizes the checked state of its children: A parent node is checked if all its children are checked.
- Checking a node will automatically
   - check all its children, including all their children.
   - check the parent, if all the parent's children are now checked. The same applies to the parent's parent.
- Unchecking a node will automatically 
   - uncheck all children and all their children.
   - uncheck the parent and its parents

Note that the checked state is only updated for the nodes that are already fetched. Nodes are fetched when they become first visible, e.g. when their parent is expanded.

**Comment by eamodio** [comment]
The examples help a ton -- thank you.

One concern is:

> If it's collapsed and not loaded then the children will not get checked until the parent is expanded. If it's collapsed and loaded then the children will be immediately checked.

IMO, if the parent is collapsed, it should either:

 - never reflect its state on its children regardless of whether the children have been previously loaded or not
- always reflect its state on its children (deferred until as the children are loaded)
- do the current behavior (reflecting if loaded) but also expand the checked children to make them visible

The current behavior is hard for a user to understand, because in some cases it will end up checking hidden children and in other cases not. It feels like that could be very confusing. 

The first option above keeps it consistent to a user as checkboxes will only reflect on to visible descendants, but may not meet expectations.

The second feels like what I think users would expect but a lot more state management etc (and makes it harder for the extension to manage too).

The third feels like a compromise between the two, but still may be confusing to the user. Although you'd always visibly see the affected children

**Comment by connor4312** [comment]
I found a couple things, but will open them on new issues since this one is kind of overloaded
