### ISSUE TITLE
Account icon shows blue badge (notification) while clicking on it, shows no actual notification

### ISSUE THREAD

**Issue by aiday-mar** [microsoft/vscode#183939]
Recently I noticed that my account icon shows a notification, despite there being no notification :bug:

<img width="498" alt="Screenshot 2023-05-31 at 15 03 30" src="https://github.com/microsoft/vscode/assets/61460952/3ae65156-24a1-4642-9b91-f3474d45eaaa">

**Comment by gjsjohnmurray** [comment]
I think it wants you to turn on settings sync.

**Comment by aiday-mar** [comment]
@gjsjohnmurray in that case perhaps we could show a little (1) in front of `Turn on Settings Sync...` to signify that an action is prompted?

**Comment by TylerLeonhardt** [comment]
This is pretty unusual. The number on the account icon is supposed to be the sum of the `(1)`s in the menu... and in fact, I have the 1 for settings sync:
![image](https://github.com/microsoft/vscode/assets/2644648/595df158-5cd9-4aca-9fbc-89636de6632b)

Do you still see this issue? I wonder if maybe your screenshot is a case of you clicking on the Account menu right as it was about to add the `(1)` to the Menu Item....but native menus can't be updated once they're shown (electron issue) so the addition of `(1)` wasn't applied until the menu is reshown.

**Comment by aiday-mar** [comment]
hi @TylerLeonhardt, I tried again and also signed into the settings sync to see if the problem would disappear, but strangely it persists. That is I have settings sync enabled and I still see the blue badge icon. In the 

https://github.com/microsoft/vscode/assets/61460952/c1bf4a78-d0fb-4964-b8cf-3f91d04e7083

**Comment by TylerLeonhardt** [comment]
How odd! @aiday-mar if you turn on those other things, does the badge go away? I'm trying to rule out some things.

**Comment by aiday-mar** [comment]
Hi @TylerLeonhardt, thanks for the reply. I clicked on the button `Turn on Cloud Changes` and the blue badge icon disappeared. I think it was not very clear that one had to click on this to make notifications disappear.

**Comment by TylerLeonhardt** [comment]
Interesting... @joyceerhl any thoughts?

**Comment by joyceerhl** [comment]
If you get into desktop via a Continue On flow from the browser and have pending changes, we first prompt you to enable Cloud Changes in order to retrieve those pending changes. If you ignore the prompt, that's when this badge would appear in the accounts menu, and on hover there would have been a `Check for pending cloud changes` message. Also, this badge goes away after you fully close and reopen VS Code. @aiday-mar assuming you used Continue On at some point, which is the only way that the Cloud Changes badge would appear, this behavior is all as expected.

We'll likely rework this soon, but in the meantime I think the change that I should make here to reduce confusion is to also add the `(1)` to the hover message.
