### ISSUE TITLE
internalConsoleOptions should be in settings and not in launch configuration

### ISSUE THREAD

**Issue by FredrikFolkesson** [Microsoft/vscode#18398]
The internalConsoleOptions setting should be in the settings.json and not as part of the launch configurations in launch.json

This would enable different developers to be able to choose for them selves if the debug console should open on session start or not while still allowing the launch configurations to be checked in to the project repo (by checking in the launch.json)

**Comment by isidorn** [comment]
I totally agree with this, but I know @weinand has a different opinion.

**Comment by weinand** [comment]
I'm typically configuring `internalConsoleOptions` per launch config: for my test launch config I want to have the debug console always open because I want to see its output. For running an extension in debug mode, I do not need the debug console and I configure it to stay closed. So for me (and others that share my view) it is important to be able to specify `internalConsoleOptions` per launch config.

However, I can understand that others want to configure `internalConsoleOptions` in a more global way, either per workspace or even as a user setting.

To accommodate both views; I suggest that we start to support both locations for `internalConsoleOptions` (and may be other flags as well). The value for these flags would be determined by walking up the chain starting with a specific launch configuration.

**Comment by weinand** [comment]
We should implement my proposal from above.
