### ISSUE TITLE
[html] useCodeSnippetsOnMethodSuggest for javascript not working in Script Blocks

### ISSUE THREAD

**Issue by AlcoholV** [Microsoft/vscode#18408]
- VSCode Version: 1.8.1
- OS Version: win10

http://stackoverflow.com/questions/30793337/vscode-intellisense-autocomplete-for-javascript

I expected : document.getElementById("")
but the result was : document.getElementById

I saw the relative merge
https://github.com/Microsoft/vscode/pull/16351
but the lastest build dosen't work too.

**Comment by mjbvz** [comment]
I'm unable to repo this in 1.8.1 in a simple JS file. Just to make sure, you are setting `	"typescript.useCodeSnippetsOnMethodSuggest": true` correct? There is no `	"javascript.useCodeSnippetsOnMethodSuggest"` setting as the stack overflow answer indicates.

**Comment by AlcoholV** [comment]
Yes. my setting is  "typescript.useCodeSnippetsOnMethodSuggest": true.
Perhaps, there was such an option in the past.

This is my test code.

<html>
<script>
   document.getElementById
</script>
</html>

**Comment by mjbvz** [comment]
@AlcoholV Are you in a js file, or inside a script block in javascript?

**Comment by AlcoholV** [comment]
@mjbvz  Oh.. It works fine in js files. I'm working in html script block.

**Comment by mjbvz** [comment]
@AlcoholV Thanks. I believe this is expected currently since script blocks are handled by the html extension instead of the js/ts extension. I've changed the title to make the issue here more clear

**Comment by aeschli** [comment]
We have this setting only for typescript. I find it a bit strange that the embedded JavaScript would listen to that setting.
IMO not a bug but a feature request.

**Comment by aeschli** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.
If you disagree and feel that this issue is crucial: We're happy to listen and to reconsider.
Maybe you want to give it a try yourself and provide the feature through an extension or a PR: We're happy to give advise and get you started.
Thanks for your understanding. Thanks for helping and happy coding!
