### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading '31')

### ISSUE THREAD

**Issue by SimonSiefke** [microsoft/vscode#184255]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.78.2
- OS Version: Ubuntu 23.04

Steps to Reproduce:

I'm not quite sure of any consistent reproduction steps, but I managed to capture the stack trace of the error:

![error](https://github.com/microsoft/vscode/assets/23744935/6b1a0b65-285f-4f2e-a0f9-850c5bb1b872)

```
workbench.js:2699 [uncaught exception]: TypeError: Cannot read properties of undefined (reading '31')
workbench.js:2702 TypeError: Cannot read properties of undefined (reading '31')
    at g._setCellUnderline (DomRenderer.ts:388:33)
    at g._handleLinkLeave (DomRenderer.ts:384:10)
    at DomRenderer.ts:82:66
    at t.EventEmitter.fire (EventEmitter.ts:55:16)
    at c._fireUnderlineEvent (Linkifier2.ts:368:13)
    at c._linkLeave (Linkifier2.ts:375:14)
    at c._clearCurrentLink (Linkifier2.ts:263:12)
    at c._handleHover (Linkifier2.ts:115:12)
    at c._handleMouseMove (Linkifier2.ts:106:12)
```

**Comment by meganrogge** [comment]
Thanks for creating this issue! To help narrow it down, please take the time to follow below steps. Thanks a lot and happy coding 🙏 

### Is the issue caused by an Extension?
Stop VS Code and from the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If it still reproduces, jump to the next chapter.

If you see it is an issue with the extension, please run the command `Start Extension Bisect` and follow the instructions to find the extension that is causing this issue.

<img width="631" alt="image" src="https://user-images.githubusercontent.com/900690/228760008-d5790ad1-74da-46a2-917f-e1bd26281ca8.png">

Please report the issue to the extension causing this.

### Is the issue caused by VS Code Core?
If the issue is not caused by an extension, it is maybe caused by your configuration. Try to run `code --disable-extensions --user-data-dir <directory>` where `<directory>` is an empty folder. This will ensure Code is starting with a fresh data directory, e.g. no specific settings and without any extensions running. 

If it still reproduces, it was maybe fixed already in our nightly release. Please download from https://code.visualstudio.com/insiders/ and see if you can reproduce the issue.

Finally, to help us narrow down what change caused the issue, please run the following command to find the build. It will start previous releases of VS Code insiders to see where the regression was introduced:
* `npx --yes vscode-bisect@latest`
* follow the instructions until you found the offending build
* report back the commit range in this issue

Thanks!

**Comment by SimonSiefke** [comment]
Fixed upstream in xterm.js
