### ISSUE TITLE
Unexpected JS outline model calculated with built-in JS language server

### ISSUE THREAD

**Issue by aiday-mar** [microsoft/vscode#184393]
While testing https://github.com/microsoft/vscode/issues/180832, it was noticed that the error results from an incorrect calculated Javascript outline model. Given the text example in the issue, the outline model is computed to have two children, while it should have 7 children. 

<img width="1402" alt="Screenshot 2023-06-06 at 09 46 50" src="https://github.com/microsoft/vscode/assets/61460952/723c9e62-eb7d-44e9-adec-3e489f9d3a14">

**Comment by mjbvz** [comment]
@aiday-mar We group the methods under the namespace itself: 

<img width="494" alt="Screenshot 2023-06-06 at 11 13 23 AM" src="https://github.com/microsoft/vscode/assets/12821956/a0b9facb-7edb-4eac-8e16-20c86492cbd9">

This makes sense for the outline view and go to symbol. Is it causing issues for sticky-scroll?

Perhaps the issues is that `mynamepscae` is said to start on the line 16:

```
mynamespace.Component.prototype._fireTitleChanged
```

Not sure where where it should start though in this case since the namespace is no explicitly defined anywhere

**Comment by aiday-mar** [comment]
Hi @mjbvz, thanks for the response. I see better now, thank you - it's my bad for not looking more closely at the example. The way the outline model is calculated makes sense. It's just not structured in the way sticky scroll expects it - according to the actual semantic scopes. In this case it would be useful to define an API to allow extensions to define sticky lines for these kinds of cases https://github.com/microsoft/vscode/issues/168428). In the meantime users can use the folding provider model or the indentation provider model to define the sticky model. I'll close this issue.
