### ISSUE TITLE
Using cmd+c on Mac in VSCode disables the cursor

### ISSUE THREAD

**Issue by kiki-lee** [microsoft/vscode#184461]
In the new version of VSCode for Mac
![Screenshot by Dropbox Capture](https://github.com/microsoft/vscode/assets/1633958/de85ed65-27a2-47b8-b8e3-e08e978579ec)

copying text using cmd+c will change the cursor and make it impossible to continue typing. 

![Visual Studio Code - sparks md — pxt-arcade 2023-06-06 at 5 36 44 PM](https://github.com/microsoft/vscode/assets/1633958/b61cd45b-2117-42a3-8202-53bff03b019c)

I notice that the text at the bottom changes to --NORMAL--  and when I double-click, it then changes to --VISUAL--.  Neither mode will allow me to edit my code. From there, I don't know how to effectively get it to go back to --INSERT-- again, as there is no option for toggling in the selection menu. Hitting random keys will either move the cursor, add lines, or delete words, but mashing vowels seems to eventually bring --INSERT-- back. 

This happens whether or not copilot is activated. 

Ideally, I'd like to be able to copy/paste using cmd+c and cmd+v without changing any of my VSCode settings.

**Comment by ulugbekna** [comment]
Hi @kiki-lee ,

What you are experiencing is caused by the vscode VIM extension that was installed in your vscode. Just uninstall or disable it (and reload vscode) to get everything working as you expect. 

<img width="370" alt="image" src="https://github.com/microsoft/vscode/assets/16353531/d4be279a-c32f-4dfa-bd29-449584100b93">
