### ISSUE TITLE
Some suggestions！【such as image!】

### ISSUE THREAD

**Issue by crperlin** [Microsoft/vscode#1844]
If sourcetree of Git operating mode incorporated into vscode very great. . .

![image](https://cloud.githubusercontent.com/assets/8272877/12161131/60e36e42-b52d-11e5-9ffb-238685c10b7c.png)

Current vscode inside git operating very friendly, not as pure command line;

We hope the next version can be improved;

We hope the next  version can add the following features:

1. minimap
![image](https://cloud.githubusercontent.com/assets/8272877/12161014/4dd0cd0a-b52c-11e5-8612-761b2f104ae9.png)

2. The plug-compatible atom or migrate part [more practical over here]
3. Increase webpack or gulp script generation tool, or execute the menu
4. Increase the syntax to test JS linter into the vscode, I see profile has css, php detect these grammar
5. Upgrade node to the latest version [Node v5.4.0 (Stable) ]
6. [If they could improve the diff function similar webstorm as very good, clicking piece offset past]
7. color show and picker, similar webstorm

![image](https://cloud.githubusercontent.com/assets/8272877/12161000/31430040-b52c-11e5-8d5d-ea05f55818db.png)

8. The code folding
![image](https://cloud.githubusercontent.com/assets/8272877/12161082/e46383d4-b52c-11e5-9cf6-3c1ab1724c4f.png)

Thanks~~~~~~~~~~

**Comment by joaomoreno** [comment]
I will simply close this issue since it contains too many items, and address each one individually:

1. Please file an issue just for this.
2. Will likely not happen, as Atom and Code have very different extension models.
3. Can you do this using the tasks mechanism?
4. I don't understand what you mean by this.
5. Code doesn't come with standalone Node. You are free to using whichever version you want.
6. Please file an issue just for this.
7. Please file an issue just for this.
8. #105

**Comment by felixfbecker** [comment]
@joaomoreno Regarding 5, this is not true, at least not on Windows. I have 5.3 installed but Code says it uses 4.1.1

**Comment by joaomoreno** [comment]
Code uses node, simply because it is built on Electron, which uses node. This makes it impossible to update node without updating Electron as well. The version of node that Electron is built with should be irrelevant to our users;  it really only influences extension developers.
