### ISSUE TITLE
on startup a new debug terminal will open as well as all previouse terminals, cannot find a setting to open only the default terminal or continue with the latest used

### ISSUE THREAD

**Issue by Kini-87** [microsoft/vscode#184425]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. open VS code
2. delete any old terminals not used
3. reload VS code
4. the last terminal loads then another debug terminal loads too

![image](https://github.com/microsoft/vscode/assets/114576565/38014a1b-36fa-4f2b-ae1f-3fca4ce0532d)

**Comment by meganrogge** [comment]
Thanks for creating this issue! To help narrow it down, please take the time to follow below steps. Thanks a lot and happy coding 🙏 

### Is the issue caused by an Extension?
Stop VS Code and from the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If it still reproduces, jump to the next chapter.

If you see it is an issue with the extension, please run the command `Start Extension Bisect` and follow the instructions to find the extension that is causing this issue.

<img width="631" alt="image" src="https://user-images.githubusercontent.com/900690/228760008-d5790ad1-74da-46a2-917f-e1bd26281ca8.png">

Please report the issue to the extension causing this.

### Is the issue caused by VS Code Core?
If the issue is not caused by an extension, it is maybe caused by your configuration. Try to run `code --disable-extensions --user-data-dir <directory>` where `<directory>` is an empty folder. This will ensure Code is starting with a fresh data directory, e.g. no specific settings and without any extensions running. 

If it still reproduces, it was maybe fixed already in our nightly release. Please download from https://code.visualstudio.com/insiders/ and see if you can reproduce the issue.

Finally, to help us narrow down what change caused the issue, please run the following command to find the build. It will start previous releases of VS Code insiders to see where the regression was introduced:
* `npx --yes vscode-bisect@latest`
* follow the instructions until you found the offending build
* report back the commit range in this issue

Thanks!

**Comment by Kini-87** [comment]
Many thanks for the respons. The VS code insider doesn't have the problem, I will be using it instead of VS code.

the `npx --yes vscode-bisect@latest` command didn't work for me on either applications, attached is a snapshot of the message returned.
![image](https://github.com/microsoft/vscode/assets/114576565/7a721a0a-69e9-4c1a-9adc-025d155151df)
