### ISSUE TITLE
Status bar priority should apply reverse for alignment LEFT

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#18458]
To get an item to the right most side of that status bar I set its alignment to `Right` and its priority to `Number.MAX_VALUE`. Now to get an item to left of side I have to use alignment `Left` and *not* `Number.MIN_VALUE` but again `Number.MAX_VALUE` which is against any of my order senses.

**Comment by bpasero** [comment]
@jrieken unhappy, but this seems to be already exposed as API, so I would not change it, other than maybe update the docs. I think my idea back then was to make the far LEFT and far RIGHT positions the ones with highest priority. For example, one should never push something to the LEFT of the git status bar because we want it to be there. That's why that guy has MAX_VALUE.

**Comment by jrieken** [comment]
Yeah, I'd change it mention it as semantic change. For me it's like the change we made for message bar action order. There we also changed the order and just mentioned it in the release notes

**Comment by bpasero** [comment]
Not planning to change this.
