### ISSUE TITLE
[vb] Switch to a more active grammar for VB

### ISSUE THREAD

**Issue by gundermanc** [Microsoft/vscode#18469]
- VSCode Version: 1.7.2
- OS Version: Windows 10 14393.577

Steps to Reproduce:

1. Open a modern VB.NET file, such as [VBEditAndContinueAnalyzer](https://github.com/dotnet/roslyn/blob/0694d5ccc05b7e1cc37c82a1c15c8f9fc23e3775/src/Features/VisualBasic/Portable/EditAndContinue/VisualBasicEditAndContinueAnalyzer.vb)
2. Observe that 'Imports', 'Namespace', 'Friend', 'Inherits', 'Protected', 'Override', and perhaps other keywords are not colorized, but simply appear as white text.

This same issue repros with the same grammar on:

- TextMate editor for Mac
- VS Code for Windows
- Visual Studio 2017 RC

I am fairly certain that this is a TMLanguages issue, as doing a quick search through the [grammar file](https://github.com/Microsoft/vscode/blob/master/extensions/vb/syntaxes/ASPVBnet.plist), there is no pattern for matching these keywords.

I'd recommend either switching to an alternative grammar, such as [Angry Ant's](https://github.com/angryant0007/VBDotNetSyntax), or better yet, updating and contributing the corrected grammar file back to [the TextMate Grammar](https://github.com/textmate/asp.vb.net.tmbundle).

**Comment by aeschli** [comment]
@chrisdias got a PR accepted in https://github.com/textmate/asp.vb.net.tmbundle. I'm not opposed to switching to a better one, but it would be great to try that.

**Comment by aeschli** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.
If you disagree and feel that this issue is crucial: We're happy to listen and to reconsider.
Maybe you want to give it a try yourself and provide the feature through an extension or a PR: We're happy to give advise and get you started.
Thanks for your understanding. Thanks for helping and happy coding!
