### ISSUE TITLE
Use `AccessibleView` for hovers

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#184620]
An excellent fix. Works as expected. It would be great if the same could be done for the Show or Focus Hover command.

_Originally posted by @jvesouza in https://github.com/microsoft/vscode/issues/173911#issuecomment-1505602012_

**Comment by jvesouza** [comment]
I did a quick test and it turned out excellent, exactly as I thought. A small detail is that when I pressed alt+f1 orca read something like terminal accessibility help.

**Comment by meganrogge** [comment]
@jvesouza this has not been implemented yet

**Comment by jvesouza** [comment]
Maybe it has nothing to do with the implementation made but I can't access accessibility help anymore.
If I am for example in an editor and I press alt+f1 nothing is announced by orca. The same happens in the terminal and in the chat input.

**Comment by meganrogge** [comment]
hm, it's working for me - and you're using the latest insider's, correct? can you try with NVDA?

**Comment by jvesouza** [comment]
> @jvesouza hm, it's working for me - and you're using the latest insider's, correct? can you try with NVDA?
> 
> what happens now for the help menus is they open in a monaco editor. can you tell what element is focused when you use `alt+f1`?

Yes, I am using The latest insider and I'll try to test using nvda as soon as possible.
However I noticed that the "show accessibility help" command doesn't seem to exist anymore because I press ctrl+shift+p, type "show accessibility help" and I get the information that nothing was found.

**Comment by meganrogge** [comment]
Yeah, that's because it is a multi-command, which doesn't allow it to show up in the quick pick. I'll make an issue for that

**Comment by jvesouza** [comment]
I can't tell which element gets the focus when I press alt+f1, but the impression I get is that the focus doesn't change. What leads me to think this is the fact that after pressing alt+f1 if I press down arrow, orca reads the next line in the file being edited.
Something similar happens when I'm in the terminal. If I press alt+f1 and then press up arrow, orca reads the last command executed.


Something that caught my attention is that I found the following in the default key bindingss:
```
{ "key": "alt+f1",                "command": "editor.action.accessibilityHelp" },
{ "key": "shift+alt+f1",          "command": "editor.action.accessibilityHelp" },
{ "key": "alt+f1",                "command": "editor.action.accessibilityView" },
{ "key": "shift+alt+f1",          "command": "editor.action.accessibilityView" },
```
Is this right?

**Comment by meganrogge** [comment]
@jvesouza that explains it - the default keybindings are:

```
{ "key": "alt+f1",                "command": "editor.action.accessibilityHelp" },
{ "key": "alt+f2",                "command": "editor.action.accessibilityView" },
```

Replacing the above with those should fix it for you

**Comment by jvesouza** [comment]
> @jvesouza that explains it - the default keybindings are:
> 
> ```
> { "key": "alt+f1",                "command": "editor.action.accessibilityHelp" },
> { "key": "alt+f2",                "command": "editor.action.accessibilityView" },
> ```
> 
> Replacing the above with those should fix it for you


Instead of using the combination alt+f2 I used alt+shift+f1 because alt+f2 is the shortcut used in gnome to activate the command execution dialog.
Once configured, I ran the following tests:
1. Open the VSCode editor.
2. Press alt+f1
The accessibility help for the VSCode editor was displayed, although orca read accessibility help for the terminal. The title seems wrong but the content is correct.

1. Open the VSCode editor.
2. Press alt+shift+f1.
Nothing was read by orca.

I ran the same tests after opening a terminal but nothing was read by orca.

**Comment by meganrogge** [comment]
I would assume the keybinding is not working for some reason in that case. Could you toggle keyboard shortcuts troubleshooting, which will print to the output what might be going on, and share that? 

Thanks

**Comment by jvesouza** [comment]
> I would assume the keybinding is not working for some reason in that case. Could you toggle keyboard shortcuts troubleshooting, which will print to the output what might be going on, and share that?
> 
> Thanks

I'm sorry I didn't respond sooner, I've had a very difficult and busy week.
In the meantime something seems to have changed as now everything is working as expected.
The exception is the alt+f2 and shift+alt+f2 keys which are probably used by gnome, at least on my machine. I have associated the command assigned to these keys to shift+alt+f1 and it is working ok.
If I still need toggle keyboard shortcuts troubleshooting I will need guidance on how to do it because I honestly don't know the procedure for doing so.
Thanks.

**Comment by meganrogge** [comment]
Sounds like it's now working for you other than the conflict with gnome, so no need to toggle the keyboard troubleshooting
