### ISSUE TITLE
PHP Language Basics Snippets Does not work after update - Function Code Auto Complete issue

### ISSUE THREAD

**Issue by mevishnudas** [microsoft/vscode#185005]
in older versions when we type func it will automatically complete to 

public function FunctionName(){
}

Now it is changed to
function FunctionName() : Returntype {
    }

The first one what a is PHP Dev's needs

Please Update This it will be really helpful for faster coding

Thank you

![php basic vscode issue](https://github.com/microsoft/vscode/assets/95905352/f45f582f-8cb9-472c-9167-dfa8e401b8e6)

**Comment by roblourens** [comment]
We modernized these in https://github.com/microsoft/vscode/pull/174889/files. You may want to use `class_fun` now. You can also add whatever custom personal snippets you like, which I would recommend if you are a heavy snippets user. FYI @soulshined in case you have anything to add

**Comment by soulshined** [comment]
> The first one what a is PHP Dev's needs

There's really no one way to define what's best for all devs at large. PHP is an extremely loosely typed language by nature, so satisfying numerous preferences across the board is tough. This is something roblourens brought up in the modernization effort since [PHP 7 is end of life](https://www.php.net/supported-versions.php) 

In regards to functions there were a lot of limitations from the old snippets, especially with things like type hints and return type hints, considering moving into PHP 8 where you have [property promotion and union types](https://www.php.net/releases/8.0/en.php)

An example of PHP development looseness is as demonstrated on [php-fig](https://www.php-fig.org/psr/psr-12/#45-method-and-function-arguments); you can have a type hint for a single parameter, but not the rest of parameters:

```php
public function functionName(int $arg1, $arg2): string
{
    return 'foo';
}
```

Same for return types. 

So the thought process was, instead of creating many different snippets for unique edge cases was to remove the tight coupling, and add idempotent snippets you can chain together as you see fit since PHP is loosely typed. 

Most things are wrapped in tab stops now so you have that flexibility to accept it or reject it conditionally. If you think about it in that regard it's not that much more typing, all you have to do is press delete if you don't need that specific component of a function. But it's there when you do need it. 

I get that it feels like a lot more tab stops to get to the end goal, but objectively, it's just going to be really hard to make snippets 1 or 2 tab stops in total when you take into account all the different variants something can be accomplished in PHP. The goal with the modernization effort was to offer flexibility, while still being backwards compatible with <PHP8 snytax; not take it away. 

It's worth noting that I am not the arbiter of PHP, so just like me if you have anything to contribute feel free to open a PR with changes and feedback will be given accordingly. Just keep in mind, what's best for you may not be the particular preference of another dev. Some PHP devs use namespace groupings others type each one out individually for example. Some PHP devs don't use type hints at all making the old func you demonstrated useless to them.
