### ISSUE TITLE
VSCode keeps signing out of Microsoft for sync settings every few hours

### ISSUE THREAD

**Issue by mcandre** [microsoft/vscode#185172]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.79.1 (Universal)
- OS Version: Darwin arm64 22.2.0

Steps to Reproduce:

1. Use VSCode for a couple hours.

**Comment by TylerLeonhardt** [comment]
Can you follow these steps so that we can get more information on what's going on?

* Open the Command Palette
* Run the `Developer: Set Log Level...` command
* To the right of `Trace`, click the double check mark button. ✔️ ✔️ (enables trace logging as the default)
* _Wait for the issue to happen..._
* Open the Output pane (ctrl+shift+u I think on Windows)
* drop in this issue he contents of the following:
  * `Microsoft Authentication` Output channel
  * `Log (Settings Sync)` Output channel
  * `Log (Main)` Output channel
* Open the Command Palette
* Run the `Developer: Set Log Level...` command
* To the right of `Info`, click the double check mark button. ✔️ ✔️ (to set the default back to info)
