### ISSUE TITLE
Add method override indicators

### ISSUE THREAD

**Issue by thekalinga** [Microsoft/vscode#18576]
Currently vscode does not show override indicators that the current class is overriding/implementing methods from super class/interface.

This indicator would help the user understand that the given method is being overridden rather than a local method.

Most editors such as intellij & eclipse have these indicators

**Comment by dbaeumer** [comment]
FYI: @jrieken @bpasero @alexandrudima

**Comment by alexandrudima** [comment]
To keep the number of issues in our inbox at a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: we look at the number of votes the issue has received and the number of duplicate issues filed. Thank you for your time and understanding.

If you disagree and feel that this issue is crucial: we're happy to listen and to reconsider.
