### ISSUE TITLE
Testing Explorer "Expand All"

### ISSUE THREAD

**Issue by zenoran** [microsoft/vscode#185771]
Running testing in Python projects does not expand the tests or appear to have any way to do it other than individually clicking every single node.  At a bare minimum, it would be nice if errored tests at least expanded.  There is Collapse All within the "..." menu but no complementary Expand All.  I tried searching for conversations about this specifically, but it seemed like there was a lot of confusion around requests for other trees requesting this functionality so Tests was never addressed.

If there is in fact a way to expand all in the tests section please let me know what I'm missing.

**Comment by connor4312** [comment]
There is intentionally no "expand all" for the Test Explorer view, since VS Code requests tests data from the test provider lazily and doing this could lead to significant unintended performance impacts. For the same reason, there's not an "Expand All" action on tree views provided by extensions or in the file explorer.

You can however see all results of a test run in the Test Results view.
