### ISSUE TITLE
Consider providing screen reader with the chat response for inline chat

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#185705]
as a screen reader user:

1. Start code chat
2. Type a request and hit enter
3. 🐛 tab 7 times to focus response

Perhaps we should align with the chat view and update via `status` with the response when it is ready

**Comment by meganrogge** [comment]
cc @jrieken

**Comment by meganrogge** [comment]
related/ intertwined with https://github.com/microsoft/vscode/issues/185706

**Comment by meganrogge** [comment]
cc @jooyoungseo and @rperez030

**Comment by rperez030** [comment]
I'm glad we are tracking this one. It is not a full blocker, but kind of, especially because the response usually contains the number of lines that have changed when copilot proposes a fix, for example. Having to figure out what has happened each time I issue a query almost defeats the purpose of using copilot in the first place.

**Comment by meganrogge** [comment]
@rperez030 yes this should be fixed soon. I've linked the PR
