### ISSUE TITLE
Terminal rendering shows space between lines with zoomlevel:1

### ISSUE THREAD

**Issue by jordwalke** [Microsoft/vscode#18588]
cc @Tyriar 

My terminal application draws background color, and this is how it looks. I believe this is a bug.

<img width="887" alt="screen shot 2017-01-15 at 8 49 46 pm" src="https://cloud.githubusercontent.com/assets/977348/21971316/5a8382d6-db64-11e6-966e-43f8c21d77e4.png">

**Comment by Tyriar** [comment]
Must be a mac-specific issue, what's in your settings.json?

**Comment by jordwalke** [comment]
```
// Place your settings in this file to overwrite the default settings
{
    "editor.fontFamily": "Menlo, 'PragmataPro', Menlo, Monaco, 'Courier New', monospace",
    "window.zoomLevel": 1
}
```

I discovered that this doesn't happen at window zoomlevel 0.

**Comment by Tyriar** [comment]
Does setting `"terminal.integrated.lineHeight": 1.2` fix the problem at "window.zoomLevel": 1
 and others? I think Mac has a different line-height that's inherited from the editor, maybe it could just use 1.2 too if so?

On my Linux machine it works until zoom level is 4.

**Comment by jordwalke** [comment]
There's a couple settings that don't work on my setup. 1 and -1. 4 works on my system. It could be some combination of my retina screen with the zoom level etc which causes some rounding error.

**Comment by Tyriar** [comment]
Yes that's likely the case

**Comment by Tyriar** [comment]
Will likely be fixed when https://github.com/Microsoft/vscode/issues/9958 is implemented

**Comment by jordwalke** [comment]
So what's happening in this bug? When I set lineheight=1, and I used a font like PragmataPro, the text should fit perfectly within one line correct? But with lineheight=1, (zoom level 0 or 1), you can see that text is clipped. Is this related?
```
{
    "editor.fontFamily": "PragmataPro, Menlo, Monaco, 'Courier New', monospace",
    "window.zoomLevel": 1,
    "editor.fontSize": 14,
    "terminal.integrated.lineHeight": 1.0
}
```
<img width="308" alt="screen shot 2017-04-17 at 1 10 30 pm" src="https://cloud.githubusercontent.com/assets/977348/25102926/5a118a52-236f-11e7-8f12-e3ed474f99fb.png">


Then, as originally discussed setting lineheight to 1.2 causes there to be lines between the background:

```
{
    "editor.fontFamily": "PragmataPro, Menlo, Monaco, 'Courier New', monospace",
    "window.zoomLevel": 1,
    "editor.fontSize": 14,
    "terminal.integrated.lineHeight": 1.2
}
```
<img width="372" alt="screen shot 2017-04-17 at 1 12 40 pm" src="https://cloud.githubusercontent.com/assets/977348/25102985/9276b6f6-236f-11e7-9afd-660261aa3c39.png">


I think the the clipping at line height 1 is unrelated but not correct, but it has me wanting to increase the lineheight, which then surfaces the originally reported bug.

When the terminal draws "background color", shouldn't it be filing in the additional line space below it?

**Comment by Tyriar** [comment]
The way this will be fixed is by implementing "virtual selection" upstream https://github.com/sourcelair/xterm.js/issues/207

It's the next terminal feature I want to work on and it will allow xterm.js to completely control the selection model, **how it's rendered** and how it's copied which will fix a huge amount of issues with the terminal. Here's the list of impacted issues it will touch when I last checked:

- Double clicking on the prompt line being flaky due to focus shifting from .xterm to the text area
- Double clicking on a URL/path to highlight the whole path (ie. don't use / and similar chars as separators)
- Selecting and copying multiple pages of the buffer https://github.com/sourcelair/xterm.js/issues/69
- Selection goes crazy when you start dragging and then use mouse wheel https://github.com/sourcelair/xterm.js/issues/68
- Making the selection's line height exact so there are never any gaps between lines https://github.com/Microsoft/vscode/issues/18588
- Don't drop the selection when there's a content change or viewport scroll https://github.com/sourcelair/xterm.js/issues/468 s://github.com/sourcelair/xterm.js/issues/318
- Allow selection to be retained in terminal when not focused (like editor) https://github.com/Microsoft/vscode/issues/9761
- Add select all command https://github.com/sourcelair/xterm.js/issues/307 https://github.com/Microsoft/vscode/issues/15199
- Selection is dropped sometimes when right clicking outside of selection https://github.com/Microsoft/vscode/issues/23866
- Black marker is shown when context menu is closed https://github.com/Microsoft/vscode/issues/9758
- Potential
  - Selection should not be visible during mouse interaction mode https://github.com/sourcelair/xterm.js/issues/140
  - Improve tmux support https://github.com/sourcelair/xterm.js/issues/456
  - Tmux ignores mouse scroll events/shits itself on selection events https://github.com/sourcelair/xterm.js/issues/329
  - Copy/paste does not work in Edge https://github.com/sourcelair/xterm.js/issues/401

**Comment by Tyriar** [comment]
Fixed in https://github.com/sourcelair/xterm.js/pull/670
