### ISSUE TITLE
Automatically expand full docstring when autocompleting

### ISSUE THREAD

**Issue by fredrikaverpil** [Microsoft/vscode#18582]
As originally posted as a [feature request in the pythonVSCode project](https://github.com/DonJayamanne/pythonVSCode/issues/645):

Would it be possible to automatically expand the docstring without requiring clicking the "info" symbol button?

Current behavior requires you to click the "info" symbol button to view the full docstring:

![01](https://cloud.githubusercontent.com/assets/994357/21966814/2f229372-db7b-11e6-9f7d-b46ba81ba7e8.png)

![02](https://cloud.githubusercontent.com/assets/994357/21966815/32b53bb6-db7b-11e6-9264-0ee9d9c0c445.png)

For comparison, here's how Atom deals with this (always expands the full docstring):

![atom](https://cloud.githubusercontent.com/assets/994357/21966818/3ad5835a-db7b-11e6-9977-b699031f755e.png)

Also, it would be useful to be able to copy paste e.g. a function's arguments from the documentation shown.

**Comment by ramya-rao-a** [comment]
Tried my hand at this and below are a few options.

Docs shown below the suggestion list

![ezgif com-video-to-gif-2](https://cloud.githubusercontent.com/assets/16890566/25311121/09b76558-27ad-11e7-96e4-26703729619a.gif)

Docs shown below the suggestion list + reduced suggestion count so that the item in focus is nearer to the docs. Less jumping of user's focus between item in focus and the docs?

![ezgif com-video-to-gif-3](https://cloud.githubusercontent.com/assets/16890566/25311124/2e9e53f4-27ad-11e7-8e73-079325f9d56f.gif)


Docs shown side to side


![ezgif com-video-to-gif-4](https://cloud.githubusercontent.com/assets/16890566/25311278/82546afc-27b1-11e7-83b4-d6b71f2e98e4.gif)

In all cases the height of the docs section is fixed and the docs is scrollable.
Some smart logic can be added to make the height of the docs dynamic.
But different font-sizes and fonts would render text with different width. So that can get tricky.

I propose to add a setting `editor.suggestAutoExpand` with `true`/`false`: `false` by default
Or with `off`, `below`, `side`. `off` by default
Get user feedback and then take it from there.

@Microsoft/vscode Thoughts?

**Comment by mrmlnc** [comment]
@ramya-rao-a, I'm outside @vscode scope, but I'm in. I think this is a very useful feature.

**Comment by Tyriar** [comment]
@ramya-rao-a the ones on the bottom need either a top border or a different background color imo.

**Comment by ramya-rao-a** [comment]
@mrmlnc So sorry, didn't mean to exclude anybody, updated my text :)

**Comment by roblourens** [comment]
I really like the last option, showing them to the right.

**Comment by Tyriar** [comment]
I'm not sure making this configurable and supporting multiple configs would be worth it. I certainly wouldn't assume that it would be configurable and seek out a setting to change it.

**Comment by chrisdias** [comment]
VS has been finely tuned for a number of years and pops a window to the right, so #3 is consistent with this behavior.  VS pops the flyout after a slight delay it appears, presumably to let you quickly scroll through the IntelliSense list and not be distracted by the flyouts. The flyout window is sized for the content, it does not take up the full height of the IntelliSense list.  This is goodness because it obscures less of the screen/underlying code, so I'm in favor of dynamically sizing the doc area.

What happens when the editor is too narrow or if the completion is near the end of a long line?

**Comment by ramya-rao-a** [comment]
@chrisdias 
When completion is near the end of a long line, the suggestion list as well as the docs show up on the left side of the cursor just like it does today.

<img width="1035" alt="screen shot 2017-04-23 at 10 26 10 pm" src="https://cloud.githubusercontent.com/assets/16890566/25323413/ed191d84-2873-11e7-84d0-7dbe9cde68cc.png">

With narrower editors, the whole section resizes to fit itself.

<img width="510" alt="screen shot 2017-04-23 at 10 25 13 pm" src="https://cloud.githubusercontent.com/assets/16890566/25323417/f45d1424-2873-11e7-9c2a-50066b37a94f.png">

**Comment by joaomoreno** [comment]
I would stay away from any configuration and just provide a single good solution. Overall I really like option 2, if we further decrease the number of options (3-5) and make the height of the documentation variable, taking up as much space as it needs up to a certain point, when it becomes scrollable.

**Comment by ramya-rao-a** [comment]
Here are some updates:

The side by side option with the docs now having dynamic height instead of fixed height

![ezgif com-video-to-gif-5](https://cloud.githubusercontent.com/assets/16890566/25353096/04fd4a0a-28e3-11e7-8449-0778a1b055bb.gif)

The below option with lesser items, border between items and docs and dynamic height instead of fixed height
![ezgif com-video-to-gif-6](https://cloud.githubusercontent.com/assets/16890566/25353288/8f33c262-28e3-11e7-86ea-4ff5fde304d5.gif)

**Comment by Tyriar** [comment]
@ramya-rao-a it would be good to trim any new lines/whitespace at the bottom of the detail message

**Comment by ramya-rao-a** [comment]
Those are not newlines/whitespaces. That is just me trying to guess how may lines the docs may need.
Which is different for different font-sizes.

Right now I have an approximation logic that works for most cases, and for a few you see a max 2 empty lines in the end.

Logic I am using (pretty hacky) is number of chars that fit in a line = 720/fontsize

Now in certain languages (example chinese), chars are wider. So this will not be accurate. Still working on that part

**Comment by ramya-rao-a** [comment]
Worked offline with @Tyriar (thanks @Tyriar!) and we now have the dynamic height being set without us needing to guess the number of lines the docs would take. Yay!

**Comment by fredrikaverpil** [comment]
Wow, this looks fantastiskt @ramya-rao-a !

**Comment by octref** [comment]
Don't know if this belongs to here, but hope the suggest item's
- documentation can be rendered as Markdown
- function signature can be syntax-highlighted

**Comment by octref** [comment]
Logged them.

**Comment by ramya-rao-a** [comment]
Update:

The Insiders Build now has this feature.

- [ ] Show docs to the side, widget should be able to flow across editors
- [ ] The list and docs should be swapped such that the list is always closer to the cursor position
- [x] Show docs below the list when there is not enough space to show the two side by side
- Ctrl+Space to move focus to the docs and back to the list. This can be used to Page Up/Down the appropriate part
- [ ] A visual cue for when focus is on the docs section vs the list
- [ ] Test accessibility and screen reader

**Comment by svipben** [comment]
@ramya-rao-a Very good job. Thank you a lot. This feature is AMAZING!

**Comment by ramya-rao-a** [comment]
Update:

The Insiders Build of 5/18 will have the below features

- [x] Ctrl+Space to expand/collapse the docs. This user choice is persisted to give the "expand docs all the time feature". This way we don't need a setting
- [x] Ctrl+Alt+Space to move focus to the docs and back to the list. This can be used to Page Up/Down the appropriate part
- [x] Test accessibility and screen reader

**Comment by svipben** [comment]
@ramya-rao-a Very good, but I think the setting will be good or make it by default to expanded/collapsed, because it's way better than before. I think if people forgot to use Ctrl+Space on new VS Code installation or if they want to send same settings to friend/college they need to use Ctrl+Space to expand/collapse the docs. With setting or making it by default it will be way easier to send settings to have the same configuration on VS Code or to use it every time even if you forgot to press Ctrl+Space. This feature must to be turned on by default or have setting instead of Ctrl+Space configuration. A lot of people who want this feature and don't manually read new VS Code release note can't find it in settings and maybe they will create issues or just don't use it, because they think this don't exists. I know it's more job to make settings and so on, but believe me this feature change the VS Code to the next level. My main criterion why I chose VS Code is the best autocomplete ever, but the problem was with the docs.

**Comment by ramya-rao-a** [comment]
Thanks for the feedback @svipben 

cc @seanmcbreen who is currently looking at default behavior/default settings of the product etc.

cc @Microsoft/vscode and everyone else on this thread for thoughts on what the default should be. Ctrl+Space can always be used toggle between expand/collapse.

**Comment by chrmarti** [comment]
For discoverability I would show it expanded by default. It is much easier to imagine what the close button does than what the info button might do. This is especially true for new users.

Also: I guess many users will keep the default and not showing the doc would just keep that feature from them.

**Comment by fredrikaverpil** [comment]
I also wish to somehow make it expanded by default. A setting in settings.json is fine with me.
I personally prefer the settings appearing on the side.

![screen shot 2017-05-19 at 08 02 58](https://cloud.githubusercontent.com/assets/994357/26235148/99a60cfc-3c69-11e7-86f7-e53e00445c5d.png)

**Comment by svipben** [comment]
@chrmarti @fredrikaverpil I love you guys! :smile:

**Comment by ramya-rao-a** [comment]
@fredrikaverpil 

> I like the docs on the side as then this section won't jump around and will always start just under the line where I'm typing.

Can you elaborate on which section jumps around and when in the latest insiders?

**Comment by fredrikaverpil** [comment]
> Can you elaborate on which section jumps around and when in the latest insiders?

Perhaps "jumping around" was not the best way to describe what I meant. :)

What I meant was that when you hit <kbd>ctrl + space</kbd>, the list of available objects varies and so does the height of this list. If you opt to have the docs at the bottom, your eyes won't immediately know exactly where the docs will show up; thus the docs text "jumps around"...

Instead, if the docs appear on the side, your eyes will know exactly where to look for it.

Does this make sense and does this answer your question?

**Comment by fredrikaverpil** [comment]
@ramya-rao-a perhaps I found a bug...

Please see here (Quicktime): https://drive.google.com/open?id=0B0b1IUnYqENgdk9nU0R1UjlmZ0U
I first hit <kbd>ctrl + space</kbd> to bring up. Then I hit <kbd>ctrl + alt + space</kbd>. See how the docs text doesn't update while I move up and down the list of objects?

I'm on macOS.

**Comment by AndyBay** [comment]
Right now when expanding docs for local variables with no documentation, the widget window shrinks when it previously did nothing. Is this supposed to happen?
![intellisense_widget_doc_expand_placement](https://cloud.githubusercontent.com/assets/1170184/26308707/938499a4-3efa-11e7-95ed-70816c4934ff.gif)
I much preferred how it was a couple updates ago with the expanded docs to the side. Will there be an option for the placement or is it now set to be below?

**Comment by ramya-rao-a** [comment]
@AndyBay No thats not suppose to happen. 

The docs are suppose to expand below only if VS Code window is too small to accommodate the side by side view.

The list section shrinks only when docs are to expand on the side. When docs end up below, they shouldn't shrink.

Are you on the latest insiders?

**Comment by AndyBay** [comment]
@ramya-rao-a I currently use `"window.zoomLevel": -1` which seems to force placement below. If I change the setting to `0` I get correct placement to the right side.

I currently work on a laptop with low resolution so I need to zoom out a bit.

I am on the latest insiders yes.

**Comment by Tyriar** [comment]
@AndyBay that's captured in https://github.com/Microsoft/vscode/issues/26886

**Comment by Tekbr** [comment]
@ramya-rao-a Some things I do not understand. So sorry for my silly question, but how do you make the suggestions look like this?

![](https://cloud.githubusercontent.com/assets/16890566/25311124/2e9e53f4-27ad-11e7-8e73-079325f9d56f.gif)

or

![](https://cloud.githubusercontent.com/assets/16890566/25353288/8f33c262-28e3-11e7-86ea-4ff5fde304d5.gif)

**Comment by ramya-rao-a** [comment]
@Tekbr that happens only when the VS Code window is too small to hold the docs on the side of the list.

**Comment by Tekbr** [comment]
-- Sorry for the English, I used Google Translator --
@ramya-rao-a Is there an issue with this request to be on the bottom? That is, make it configurable?

**Comment by ramya-rao-a** [comment]
@Tekbr no, but you can open a new issue for that. If it gets considerable up votes, we will consider adding a setting
