### ISSUE TITLE
Debug adapters cannot access workspace settings

### ISSUE THREAD

**Issue by vadimcn** [Microsoft/vscode#1860]
It appears that debug adapters cannot load the `vscode` module and therefore cannot access the workspace settings. This is unfortunate, because stuffing all debugging settings into the launch parameters is not scalable.

**Comment by weinand** [comment]
By design Debug Adapters do not run in the extension host and have no direct access to the extension API. However the extension can either add relevant settings to a launch config in the DebugConfigurationProvider.resolveDebugConfiguration method or the DA can use a custom event/request to ask for settings.
