### ISSUE TITLE
FR: Goto Implementation

### ISSUE THREAD

**Issue by unional** [Microsoft/vscode#18604]
vscode: 1.8.1

Currently, we have "Goto definition", which, when the source is js+d.ts, it goes to the d.ts file.

Please consider adding a "Goto implementation" to go to the source code (js) or the source map (ts).

webstorm has the following support:
![image](https://cloud.githubusercontent.com/assets/3254987/21986243/8ac2c5f2-dbb3-11e6-8eaf-c34f1a2705a5.png)

**Comment by mjbvz** [comment]
I implemented this for VSCode 1.9 already #10806

However, due to some bugs on the TypeScript side, it will currently only be enabled when using TypeScript 2.2+. You start trying out `go to implementation` by installing `typescript@next` locally and updating the `typescript.tsdk` setting to point to the local install. Other languages can provide their own `go to implementation` provider as well.

**Comment by hoegge** [comment]
This seems fixed, I wonder though, how to enable "go to implementation" so it actually works going to the JS implementation of functions declared in .d.ts files. I have TS 2.4 installed and just goes to the d.ts. declaration.

**Comment by unional** [comment]
I actually do not see it working.
I work with global namespace so the situation may be a bit different?
It still goes to the typings every time.
