### ISSUE TITLE
osX JS intellisense doesn't work when jsconfig.json exists

### ISSUE THREAD

**Issue by frafajec** [Microsoft/vscode#18602]
- VSCode Version: 1.8 (November 2016)
- OS Version: macOS Sierra 10.12.1

**Issue**:
I am having project with native JS, ReactJS, Coffee etc. However none of those files have an intellisence when jsconfig.json is present in project root. As soon as I delete config file and reload Code, intellisence is there.

**Steps to Reproduce**:
1. On osX create project with JS files
2. Observe how JS intellisence works
3. Add jsconfig.json to project root
4. Observe how JS intellisense doesn't work

**jsconfig.json sample**
```
{
	"compilerOptions": {
		"target": "es6",
		"module": "commonjs",
		"allowSyntheticDefaultImports": true
	},
	"exclude": [
		"node_modules",
		"bower_components",
		"jspm_packages",
		"tmp",
		"temp"
	]
}
```

**Comment by mjbvz** [comment]
I'm unable to repo this issue on VSCode 1.9 using TypeScript 2.1.5.

@frafajec, can you please try updating to see if the issue has been resolved. If you still see this problem:

* Make sure VSCode is the root cause by running with all extensions disabled: `code --disable-extensions`
* Add `"typescript.tsserver.trace": "verbose"` to your user settings
* Restart VSCode and reproduce the issue.
* Open the output pane and paste up the output from the `TypeScript` section

Thanks

**Comment by frafajec** [comment]
After adding "typescript.tsserver.trace": "verbose" into user settings linting started to work as it should. Also, which I didn't realise up till now, when I have mistakes in .jsx (reactjs) files, both js and HTML are now working and showing errors which is awesome.

So this issue can be closed I guess. Could you only provide info on what exactly happens when verbose is on?

Because beside that, and running --disable-extensions, nothing is changed. Extensions are now back.

Thank you!

**Comment by mjbvz** [comment]
Glad to hear the issue has been resolved. 

`"typescript.tsserver.trace": "verbose"` only prints info to the output pane to help us investigate issues. It should not have fixed anything so I'm thinking something else is probably to blame

Let me know if you start seeing this again in 1.9
