### ISSUE TITLE
Native Crashes when running Smoke Tests

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#186175]
My pipeline https://dev.azure.com/vscode/VSCode/_build/results?buildId=96901&view=logs&j=15f6beb8-c39c-5fa4-f1fe-6e73c89d1002&t=f548697b-f1e3-56d7-b20f-10575b2a648b&s=96ac2280-8cb4-5df5-99de-dd2da759617d

PR that triggered it https://github.com/microsoft/vscode/pull/185658

Native crashes:
[logs-linux-x64-smoke-1.zip](https://github.com/microsoft/vscode/files/11870921/logs-linux-x64-smoke-1.zip)

@deepak1556 let me know if you need more details from my side

**Comment by bpasero** [comment]
Above are just the logs, attaching crash dumps:

[crash-dump-linux-x64-smoke-1.zip](https://github.com/microsoft/vscode/files/11870992/crash-dump-linux-x64-smoke-1.zip)

**Comment by deepak1556** [comment]
This would be https://github.com/microsoft/vscode-internalbacklog/issues/3454 affecting the OSS electron builds since they don't contain the fix. I will keep this issue open to upstream the fix.

The crash itself is just a side effect of the workbench terminating the connection with the extension host eagerly, might want to investigate if the message port was disconnected gracefully.

**Comment by deepak1556** [comment]
Change has been upstreamed https://github.com/electron/electron/pull/39335

**Comment by deepak1556** [comment]
Addressed in https://github.com/microsoft/vscode/pull/189904
