### ISSUE TITLE
Add a setting for case sensitive sorting in explorer

### ISSUE THREAD

**Issue by fungl164** [Microsoft/vscode#18622]
- VSCode Version: Version 1.8.1 (1.8.1)
- OS Version: OSX 10.12.2

Steps to Reproduce:

1. Open VS Code
2. Open project folder
3. Open file explorer
4. Review File Tree

Looks like it's caused by this in ```vscode/src/vs/base/common/comparers.ts (line 10)```:
```
const FileNameComparer = new Intl.Collator(undefined, { numeric: true, sensitivity: 'base' });
```

could be changed to:
```
const FileNameComparer = new Intl.Collator(undefined, { numeric: true, sensitivity: 'case' });
```
or
```
const FileNameComparer = new Intl.Collator(undefined, { numeric: true, sensitivity: 'variant' });
```

Ideally this would be controlled in the user/workspace settings...

In the mean time, is there a way to manually change this in my local running copy?  Thnxs!

**Comment by bpasero** [comment]
@fungl164 can you give a concrete example where you expect a certain order and you do not see it?

**Comment by bpasero** [comment]
It seem native at least on macOS to ignore casing:

![image](https://cloud.githubusercontent.com/assets/900690/22009355/e11ede98-dc82-11e6-99d9-df6713f0b8ea.png)

**Comment by fungl164** [comment]
Thnxs @bpasero,

When case sensitivity is on, I would expect to see:
- out
- outb
- outd
- Outa
- Outc

Are you saying the behavior you describe only happens on OSX? Thnxs...

**Comment by bpasero** [comment]
No, on all platforms.

**Comment by soulomoon** [comment]
would really appreciate if treating order as the way Github did

**Comment by dlech** [comment]
> can you give a concrete example where you expect a certain order and you do not see it?

I know this is not the same as what the OP is requesting, but this is the order I would expect to see...

GitHub and Sublime text (among others) list files and folders starting with capital letters first, then lower case. An example where this is useful is the Linux kernel. For example, the `Documentation` folder is listed first, then other folders ([example](https://github.com/torvalds/linux)), likewise, in other directories, the `Makefile` and `Kconfig` are listed first, then other files ([example](https://github.com/torvalds/linux/tree/master/drivers/i2c)).

It really makes finding these "special" files easier instead of having in the middle of all of the "regular" files. Many other projects use this type of folder/file naming for organization as well.

So, if an option is added, this should be one of the options.

**Comment by bpasero** [comment]
Merging this issue into https://github.com/Microsoft/vscode/issues/27759
