### ISSUE TITLE
Test: fish shell integration automatic injection

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#186219]
Refs #139400

- [x] macOS @sandy081 
- [x] Linux @gregvanl 

Complexity: 3

Authors: @tyriar, @meganrogge 

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23186219%0A%0A&assignees=meganrogge,tyriar)

---

Undo this step to make sure you don't have fish shell integration manually installed
![Screenshot 2023-06-26 at 1 53 46 PM](https://github.com/microsoft/vscode-copilot/assets/29464607/dddede85-ac40-472a-93f7-84f25ed61615)

Verify that fish behaves like it does with shell integration disabled and you see all of the shell integration features working properly

Also try setting and unsetting `fish_prompt` and `fish_mode_prompt` and make sure they get applied and there are no errors.

These can be set in `~/.config/fish/config.fish` and you define them like:

``` 
function fish_prompt 
    echo 'hi'
end
```

**Comment by alexr00** [comment]
@meganrogge it is very hard to understand what need to be tested here. Can you include some setup steps (such as how to install fish and where the "Undo this step..." needs to be done) and things to look for for "fish behaves like it does with shell integration disabled" and "you see all of the shell integration features working properly".

**Comment by sandy081** [comment]
I agree with @alexr00 that it is pretty unclear to what to test here. It would be great if you can give the testers more context. 

I have done my own research to understand what to test this by going through the reference issue https://github.com/microsoft/vscode/issues/139400. If I understand correctly VS Code users does not need to do following manual installation to use the fish shell in VS Code. 

https://code.visualstudio.com/docs/terminal/shell-integration#_manual-installation

This is how and what I tested:

- Install [Fish](https://fishshell.com)
- Undo the manual installation of fish shell for VS Code - https://code.visualstudio.com/docs/terminal/shell-integration#_manual-installation
- Open VS Code and create fish shell like following
<img width="705" alt="image" src="https://github.com/microsoft/vscode/assets/10746682/46946cc5-b1f2-44b6-8f8e-07b46ab11735">
- Did some sanity testing in the created fish shell 

If you think what I have done is not correct, please assign other tester so that it will be covered by today.

**Comment by gregvanl** [comment]
No noticeable differences when running fish in the Integrated Terminal, Linux VM terminal (over RDP), and SSH connection to Linux VM.

Tried to change the fish_prompt but changing the function in config.fish didn't override /usr/share/fish/functions/fish_prompt.fish
