### ISSUE TITLE
Paste markdown link with multiple cursors -> I would expect cursor at each placeholder

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#186284]
Testing #186236

1. Have a link in your clipboard
2. Have multiple cursors in a Markdown file. Do not have anything selected.
3. Paste. Notice how the [Title] placeholder only gets selected at the primary cursor

I would prefer if we would select all "Title" for each cursor. That way it would be more convenient for the user to change all the "Title" placeholders at once.

**Comment by MeghanKulkarni** [comment]
Because the user would have selected multiple cursors, it would be expected that each cursor has different text which is why all the placeholders are not selected. It might make sense to make it that if nothing is selected, then all the placeholders could be selected at once, however the differing functionalities might get confusing.

**Comment by isidorn** [comment]
Hmm for multi cursor you will be pasting the same link multiple times. What scenario do you think is more common, that users would want different titles for the same link, or the same title for that link?

**Comment by mjbvz** [comment]
I tried this doing this all the time but found it strange. Here's what I found felt more natural:

- If the user has explicitly selected text with the cursor, make sure to preserve that. This means that each selection gets its own placeholder
-  Otherwise give empty selections the same placeholder index. That way you can update empty selections all at once
- If there's a mix of the empty and non-empty selections (a difficult state to get into), fallback to using unique placeholders for each 

This makes the behavior less consistent but feels more correct to me
