### ISSUE TITLE
Test: New Diff Editor

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#186213]
Refs: https://github.com/microsoft/vscode/issues/184164

- [x] anyOS @eleanorjboyd
- [x] anyOS @lszomoru
- [x] anyOS @roblourens

Authors: @hediet
Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23186213%0A%0A&assignees=hediet)

---

## Context

This iteration, we rewrote the diff editor with three goals in mind: Getting the codebase into a better shape, fixing a bunch of bugs of the old diff editor and adding some new features/improvements.

## Preparation

Make sure you set `"diffEditor.experimental.useVersion2": true` in your settings and restart VS Code (at the moment it is enabled by default for insiders, but we will disable that soon, as the new diff editor is still experimental and we might want to use experiments to roll it out some a small percentage of users).

## Things To Test

* Test that the new diff editor offers the same functionality as the old one
  * Diff two documents and verify you can spot the differences
  * Toggle Word Wrap and verify unchanged corresponding lines are still aligned
  * Open "peek call hierarchy" in either original or modified and verify that unchanged corresponding lines are still aligned
  * Verify going to next/previous diff works
  * Verify that the "Stage selected ranges" command still works (open a diff from the SCM view for that, you need to open a git repo)
  * Verify that the revert-arrow button in the gutter works
  * Verify that `diffEditor.*` settings are considered and have an immediate effect when you change them (e.g. disable the revert arrows). Try as many settings as you like.
  * Verify that you favorite feature of the diff editor still works
* Test that the new features/improvements work:
  * "Collapse Unchanged Regions"
![Code_-_Insiders_LOHarmHQdy](https://github.com/microsoft/vscode/assets/2931520/76c987ab-03ab-43b8-90c6-2af7df0eb67f)
     * This feature is meant to collapse unchanged code, so you can focus on the changes.
     * Try it out on two bigger documents that have some changes, but also have big regions of unchanged code
     * Check that the feature works as you would expect. Try to uncollapse the unchanged code in various ways.
     * Fee free to give feedback about your experience.
  * No flickering when opening or switching between diff editors in the same tab group
    * Some loading time is to be expected, but the shouldn't be sudden jumps
  * *Optional*: Try out the "Show Code Moves" feature (you can enable it with `diffEditor.experimental.showMoves`). This feature is still very unpolished and serves as a prototype of what to come. Feel free to give UX feedback/share ideas. (The new diff editor is still very experimental and will not replace the old diff editor in this release)

If you want to compare the new diff editor with the old diff editor to spot differences in functionality or behavior, use `"diffEditor.experimental.useVersion2": false` in a separate workspace. Make sure to reload VS Code after changing the value of that setting.

## Things Not To Test

* Any fixes of bugs in the old editor, as those are covered by bug issues.

## Reporting Bugs

When you run into a bug, please try to [reproduce in the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html?source=v0.40.0-dev.20230626#XQAAAAKrBAAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscw6-ynWJuetoVyYgiB3WIAyGCL4buFPFOLc1lAy95RUKo06z2t3AsctLSHAcjORfYRN1yg400RgiDpSRk10aTwmOBZiJDxekE7HpoFFTjJ29II8fig1Z06tLjONSUm40jJQ9GAxlcJTAk2Fc-sbDLPzWmLEt-DVac3zrE5E4RFlxodEjhT0Egp_GGnVJwzMnko66HhaprKp3QMtwLMPvojCiKIC1YWPjEAdi7qaMn07Wv0YoaySkokrRTjWOO2oBCpluzB5aHUZLNjqjMldfSC50_oKc0a5rXTxTldYfVoudtHe2Y6Gd7P8VJZUBxM7c1smedGX2fYUwcJzjB0RgyvoXLtsaHAOkiKE88h-xHXp09LDpGa7iQp1dJn6ZIRCqS9NugjABEv1-r6_nkhMgE7yTe4VRgS6kmBFs-iCpqa1VIVgLQW8VRjnlv3FEjAzaP-FcJuutW6rteSWvrPBWajQNo5uZgl4FuT0f6VIwWQrHxnzkWqaylORR9KOYGUZLaS31PczFY_laBKfmOWjViv5Wdv_KPKt1-0-eqJokS29sSSFj8e7T464YYbTcyNMprMBxs7wMAIZTxM_eZV_Stu62lNM00Z6Nqp7CsX-xFEzbe1gsNbWU3ie_4u0Hk) or share the original and modified file!

**Comment by eleanorjboyd** [comment]
This is more feedback than a bug but in using the `collapse unchanged regions` I had two thoughts. First, it was a bit confusing with the icon being greyed out when it was in the state of "not collapsed". I thought since it was grey it was not usable at the current moment similar to the "open changes with future revisions" (the two other buttons with circles and arrows in the same bar of commands). I think it might look better never being greyed out and instead the icon changing slightly for collapse and non-collapse. Secondly, when I was in a collapsed state it was nice that I could click the expand button on a specific collapsed region to see the whole thing. My one comment would be that as a user I would like to be able to re-collapse a block after looking at it, so another button there would be good because otherwise, I had to turn off collapse then back on the get them all collapsed again.

**Comment by roblourens** [comment]
Strong agree with @eleanorjboyd's first point, I opened https://github.com/microsoft/vscode/issues/186403 for it because I'd call it a bug.

The second, I get this icon 
<img width="107" alt="image" src="https://github.com/microsoft/vscode/assets/323878/ce3312f3-1904-49cd-9a7a-0f8519ead428">
which I can click to re-fold the region. However the icon is a bit odd, where did that come from? I think we have the inverse of your "fold" icon

**Comment by roblourens** [comment]
I can't get the "Show Code Moves" feature to activate. I'm trying to move a chunk or line around in a file without changing it but it always shows an add and delete, can you give an example?

**Comment by roblourens** [comment]
@lszomoru looks like you got a good start but did you finish testing this?

**Comment by lszomoru** [comment]
@roblourens, yes. Closed the issue.
