### ISSUE TITLE
Test: copy images from Markdown preview

### ISSUE THREAD

**Issue by MeghanKulkarni** [microsoft/vscode#186237]
Refs: [#184553](https://github.com/microsoft/vscode/issues/173876)

- [x] macOS @DonJayamanne
- [x] windows @cwebster-99
- [x] linux @ulugbekna

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23186237%0A%0A&assignees=MeghanKulkarni)

----

Description: When an image in a markdown file's preview editor is right clicked, there is a new "Copy" button that allows you to copy from the preview editor and paste to the markdown file. This works in all cases when the preview editor tab is highlighted and focused. If the preview editor is not clicked on before copying, no new information will be copied to the clipboard.

Testing:
Verify that images in the preview editor display a new custom context menu when right-clicked, and the copy-paste functionality works.

<img width="426" alt="image" src="https://github.com/microsoft/vscode/assets/29208738/1414ac94-e97c-4c73-a91d-a0dc2e88ea19">

**Comment by ulugbekna** [comment]
Cool feature! 

Is it expected that copying the image using right-click copies the image file (also changes jpg to  png) and puts a link to the copied file instead of reusing the existing image file and link to it? 

https://github.com/microsoft/vscode/assets/16353531/de14f52a-3a01-4d05-a5f4-422ce8f37b33


In other words, I would expect that the copied text is `![label](./cat.jpg)` instead of `![label](image.png)`

**Comment by MeghanKulkarni** [comment]
Yes it is expected that the pasted image is a new image file! I will look into why the image file type is being converted from jpg to png.
