### ISSUE TITLE
Test: glyph margin widgets

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#186210]
Refs: https://github.com/microsoft/vscode/issues/176316

- [x] anyOS @hediet
- [x] anyOS @connor4312
- [x] anyOS @roblourens

Authors: @joyceerhl @alexdima
Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23186210%0A%0A&assignees=joyceerhl,alexdima)

---

We've added support for `GlyphMarginWidget`s in the code editor. This allows decoration authors in _core only_ (not extension authors) to handle clicks on glyph margin decorations by passing in a DOM node that has attached listeners.

Test: please take a look at the `IGlyphMarginWidget` interface and the new methods for adding, layouting, and removing widgets. Verify that the methods and properties make sense, are properly documented, and behave as expected.

*edit from hediet*: Try out the new API in the monaco editor playground!

Refs:
- https://github.com/microsoft/vscode/blob/f907729180a8fb9c60a85b05d68494524d85ae0c/src/vs/editor/browser/editorBrowser.ts#L255-L271
- https://github.com/microsoft/vscode/blob/f907729180a8fb9c60a85b05d68494524d85ae0c/src/vs/editor/browser/editorBrowser.ts#L1029-L1041

**Comment by hediet** [comment]
This looks like an ideal use case to try the monaco editor playground!
https://microsoft.github.io/monaco-editor/playground.html?source=v0.40.0-dev.20230621#example-creating-the-editor-hello-world

**Comment by hediet** [comment]
[Works nicely!](https://microsoft.github.io/monaco-editor/playground.html?source=v0.40.0-dev.20230626#XQAAAAI7BAAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscw5URaSAEiAKctgAboa7AaZZDHLgrLqPRv_fRv2RyIokydlTdTYccsu6v6jDrc8jQ8ulrCVzjWBVWZVl-YrARXWjHX0-tquUNesdygYRbQM1JUnAt3S0xPRGGKDtEzxZ39mjg-pHRivv21o_hO2xujPCy2Mr8DjSa69d8_1pY6J90tR7_x11ptKC9CkAN1PEHXjrKvoj1Z9oCg22JgptgYG9RAx6YRimHoI_lutiXtM6riGk7_IunC92mxa9ZJvKy7uHQIcXeJm4e7AmYqF0isu4uXLqEqkwf3vQ-oHKbMkqcDOtjyLs7sj1kcNj7gGVSleT163_m7dR-iT_ofyZyF2kKf8AwRBQmqVRrT1zKM1zoEEKkMUvfw7aCjDz1-XZJpN4pI9SgHa0BfcjAzuUM8SvWKPxUH6q6CqaJ7MhBVgfqckGRZjGi6WVuMiz3V-qyiINAb4isjF-y2Na6yG-Dzq14AmaGwZeTybfrFdiX3ZIFBxF8XJwQg1Qj10KLikggGW-TG8LqxC8iQU6Sn453eTVW2LyZ-J2in105rBpNdqUUgnHW9Osqi2ekfdBIsxts1GVRdGLDVvjsR0qwnvIsOhOrspYs5P3ev6tYiMHZOOxuM_ftyQU1bKNNgIazxtfo9f1voFjNVxope_xHUrdI4wO4SlB8SzgJaPF839tQid-TXoxVIQFPxj--nYyzy_f9eKYsA)

Just some notes/thoughts:
* Why does a widget have a range and not just a position? Can you add some docs there?
* You followed the same API that Content and Overlay widgets have, but I think that API is quite outdated (addGlyphMarginWidget should return a disposable instead of having `removeGlyphMarginWidget`, `layoutGlyphMarginWidget` could be replaced by an "onChange" event and I don't think `getId` is needed).
   * Personally, I'd prefer a more modern API over consistency for the monaco editor (and would eventually refactor the other APIs as well), but I can understand the other side as well
* Just curious, for what feature did you add GlyphMarginWidgets?
