### ISSUE TITLE
Color picker stuck with wrong max size

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#186334]
* open a file with color values (testing https://github.com/microsoft/vscode/issues/182697, https://github.com/microsoft/vscode/issues/181597)
* split the editor pane, have the setting UI on the RHS
* resize a color picker hover
* :bug: it gets stuck to a wrong max width
* this seems not to happen having a text editor to its side

https://github.com/microsoft/vscode/assets/1794099/0a8dd1c1-e393-4a53-af2a-01300ef8cb40

**Comment by jrieken** [comment]
setting June for investigation

**Comment by aiday-mar** [comment]
It appears the error is due to the fact that after the normal rendering, we do not fid the maximum resizable node dimensions and do not update the height or width of the widget hover if the dimensions are bigger than the resizable node max dimensions. A PR has been made here: https://github.com/microsoft/vscode/pull/186469
