### ISSUE TITLE
Learn more for Remote Repos should be a docs page like the others

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#186397]
Testing #186258

<img width="673" alt="image" src="https://github.com/microsoft/vscode/assets/2644648/5b80eeac-8c9d-4075-9d16-fc2859c99ef8">

The `learn more` for all of the items here _except_ for Remote Repos take you to a nice page on our docs. Example: https://code.visualstudio.com/docs/remote/ssh

Remote Repositories takes you here: https://github.com/microsoft/vscode-remote-repositories-github/blob/main/README.md

Can we move this doc to https://code.visualstudio.com/docs/ ?

**Comment by joyceerhl** [comment]
@bamurtaugh do we have a better Learn More for Remote Repos?

**Comment by bamurtaugh** [comment]
My recommendation for a Remote Repos specific entry would be https://code.visualstudio.com/docs/sourcecontrol/github#_github-repositories-extension (I share the same reasoning described in https://github.com/microsoft/vscode/issues/184033#issuecomment-1572618769).

@bhavyaus [previously used](https://github.com/microsoft/vscode-dev/pull/918/files) http://aka.ms/vscode-web-docs, though that points to the vscode.dev doc overall rather than info focusing on Remote Repos, so I think https://code.visualstudio.com/docs/sourcecontrol/github#_github-repositories-extension would be a closer fit here.

**Comment by joyceerhl** [comment]
Thank you!
