### ISSUE TITLE
CodeSpace running in recovery mode due to configuration error

### ISSUE THREAD

**Issue by manchegouser** [microsoft/vscode#186615]
When I open the VS code for the CS50 class I am taking, this error code pops up:

"This code space is currently running in recovery mode due to a configuration error. Please review the creation logs, update your dev container configuration as needed, and run the "Rebuild Container" command to rectify."

I have no idea what to do. I am super new to this. Would love help. Thanks!

<img width="1440" alt="Screenshot 2023-06-29 at 13 07 28" src="https://github.com/microsoft/vscode/assets/137372156/0717717b-ae70-4ac2-ad99-b32752a2e6e3">

Version: 1.79.2
Commit: 695af097c7bd098fbf017ce3ac85e09bbc5dda06
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.5 Safari/605.1.15
Embedder: codespaces

**Comment by joyceerhl** [comment]
cc @jkeech

**Comment by jkeech** [comment]
@manchegouser the simplest thing would be to commit/push any pending changes and create a new codespace. If you want to troubleshoot the error, you can click "View Creation Log" and look for the error about why the codespace went to recovery mode, followed by running the `Codespaces: Rebuild Container` command once the issue is corrected.

If you are still having issues, please open a discussion at https://github.com/orgs/community/discussions which is the Community Support forum for Codespaces.
