### ISSUE TITLE
Git viewlet flashing like a discotheque

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#18664]
1. Open git viewlet, have some changes in index, open diff view
2. add a comit message, cmd + enter
3. notice the diff view and viewlet flashing

![disco](https://cloud.githubusercontent.com/assets/1926584/22025979/b11e2ba2-dccf-11e6-8947-8a5e88aff1a9.gif)

**Comment by joaomoreno** [comment]
It's pronounced _advantage_.

**Comment by isidorn** [comment]
Actually diff viewlet is also flasshing like crazy when I do any git operation. Also outside of vscode, like doing a git pull makes me feel like I am in the 70s

**Comment by joaomoreno** [comment]
cc @alexandrudima @jrieken

This started happening with the recent tokens work in the editor. What happens is that the git extension thinks something might've changed, due to a FS event inside `.git` folder. It then notifies the API that all the text documents which it has provided content for have possible changed. The API asks the extension "so what's that new content?" Git spawns itself to retrieve the content and return it, which happens to never change in this scenario.

There are a few possible fixes:

- Before firing the `onDidChange` for text documents, the git extension should first retrieve their content and only fire the event for the ones that actually changed.
- @jrieken: [The `MainThreadDocuments` could not set the model's contents if they haven't changed](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/node/mainThreadDocuments.ts#L239).
- @alexandrudima: The editor could be less aggressive in re-tokenizing in case the contents haven't really changed.

Let me know your thoughts.

**Comment by alexandrudima** [comment]
@joaomoreno The editor retokenizes if `setValue()` is called. Do not call `setValue()` if the contents didn't change. There was code in the gitland which checked for that (in a low memory pressure mode, via IRawText), perhaps that code got deleted?

**Comment by joaomoreno** [comment]
That code doesn't exist anymore. The content comes through the text document provider API now.

`IRawText` gives me the content split into lines, which is hard to compare with the full content I have in a single `string`. How cheap is `model.getValue()`?

**Comment by jrieken** [comment]
We can implement something that works for all virtual documents, like splitting and comparing lines

**Comment by jrieken** [comment]
When virtual document didn't change, despite them sending a change event, I won't touch the underlying text document anymore.

**Comment by joaomoreno** [comment]
Awesomesauce 🍻 Thanks!
