### ISSUE TITLE
Less prominent inlay hints

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode#186613]
I heavily use and love inlay hints but find their current styling too prominent for "hints" and think it harms readability and other editor features that use highlighting of words such as "highlight occurrences." 

Try finding highlighted occurrence of `defaultTabSize`: 

Current: 

<img width="1779" alt="Screenshot 2023-06-29 at 11 51 00" src="https://github.com/microsoft/vscode/assets/16353531/17f104d9-cedf-46f9-8f21-66fcc08261f7">

With less prominent hints: 

<img width="1779" alt="Screenshot 2023-06-29 at 11 47 31" src="https://github.com/microsoft/vscode/assets/16353531/0543d903-ad1d-4979-80ce-e33aaeb8cb35">

I think in the latter screenshot, inlay hints are less prominent but still as useful, as they are literally "hints" and don't need to be so prominent.

---

If not as default, having a setting to tweak the background & color of hints would be great.

**Comment by hediet** [comment]
I think I've read a similar issue recently (should have the inlay-hint label).

**Comment by jrieken** [comment]
Can be configured via ` "workbench.colorCustomizations": {...}` and leaving it up to @daviddossett to tweak this further.

**Comment by daviddossett** [comment]
Updatde the default light/dark themes in https://github.com/microsoft/vscode/pull/186658 to make these more subtle. Still want to keep the backgrounds since these could otherwise be confused with the ghost text in Copilot, comments in some themes, etc.

## Before

<img width="422" alt="CleanShot 2023-06-29 at 11 23 35@2x" src="https://github.com/microsoft/vscode/assets/25163139/b4ab8576-5092-459f-9daf-519af6e26898">

## After

<img width="430" alt="CleanShot 2023-06-29 at 11 22 43@2x" src="https://github.com/microsoft/vscode/assets/25163139/d8fafe16-3ed0-4726-8091-6b600a5e9ba5">
