### ISSUE TITLE
include matching incorrect

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#186759]
> Not sure if it was the case before, but I've noticed in vscode 1.79.2 something really weird.
> 
> If I search for `./folder1*` it finds results in `./folder2` which I would not expect!
> 
> ![image](https://github.com/microsoft/vscode/assets/387346/ce21dca4-a195-44f7-91b1-ffae93e7a4a8)
> 
> The same happens with `./whatever*` so it seems the `*` makes it not filter any folder:
> 
> ![image](https://github.com/microsoft/vscode/assets/387346/b5527308-2e62-4b6a-838e-f16426f16f47)
> 
> If I search for `./folder1`, it does find only results from `./folder1`:
> 
> ![image](https://github.com/microsoft/vscode/assets/387346/d1e076d3-b0c0-4f86-9a4c-b8f80d126176)

_Originally posted by @saidelike in https://github.com/microsoft/vscode/issues/184703#issuecomment-1614795859_

**Comment by tecssil** [comment]
I have the same case, I do a search and the results are from different directories than the one I explicitly included. I try the same opening the project folder instead of the workspace and I get a correct search.

![image](https://github.com/microsoft/vscode/assets/13209726/e76bbe86-aa74-4c90-a567-a6a9e9dda51a)
