### ISSUE TITLE
Is SCM the right messaging? 

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode#18692]
I love that we're tackling this. I was wondering though... how wide known is the acronym SCM? Maybe we should go with "Version Control"? 

I'm looking specifically right here

![image](https://cloud.githubusercontent.com/assets/2449568/22042971/5968d446-dcc2-11e6-888a-6bfaa84bdebb.png)

**Comment by Emeryao** [comment]
Then I also wonder why the url of git website is `git-scm.com` 😆

**Comment by joaomoreno** [comment]
Thoughts? @Microsoft/vscode

**Comment by bpasero** [comment]
I would let a SCM extension allow to contribute a label and use that.

**Comment by joaomoreno** [comment]
I'm not a big fan of this. Same goes to the icon #18675.

In my point of view, we provide SCM functionality backed by different engines. The viewlet is fixed and named something in the likes of "Change Management". Its contents are provided by different sources.

**Comment by chrmarti** [comment]
It is important to the user which SCM is used (because each has slightly different behavior) and less (or not) important that our architecture has an SCM layer that can use different engines. Because of that I'm for the extension providing a label (and an icon, if that's on the table) as Ben suggests.

**Comment by Tyriar** [comment]
Is there only ever a single SCM provider active at a time? The confusing thing at least now when I look at it is that it doesn't mention Git anywhere

![image](https://cloud.githubusercontent.com/assets/2193314/22074072/04d7b326-dd5c-11e6-98c5-b014fe9b4e2c.png)

I see "SCM", "press ctrl+enter to *submit*", "changes", all generic terms/iconography that would make me question whether it's dealing with git or some other SCM.

**Comment by Tyriar** [comment]
Some community feedback along the same lines as my last comment: https://twitter.com/interlogus/status/821779281374281737

> Does anyone know why I see SCM instead of GIT in #vscode insiders ? /code can't commit from code anymore

**Comment by alvipeo** [comment]
Yeah, I saw this today and what's more important - where is 'Commit' ???

**Comment by bgashler1** [comment]
I like @bpasero's idea of custom labels.  Whatever version control is initialized should own the label so it's clear what source control is being used.

When there is not source control present, I think we should do what's recommended in #18753 and use the generic "Version Control" label with an option to initialize for whatever source control system you have installed via extensions.

**Comment by jycouet** [comment]
@Tyriar @alvipeo I was looking at the same thing!!! How to commit now??? The "plus" button disappeared.
But I found it, you have to Ctrl+Enter to commit (the text is to submit, but it's a commit).

@joaomoreno, I kind of like the + button :)

**Comment by JimiC** [comment]
I'm all in favor in using `Version Control` as the generic label instead of `SCM` (as it's an acronym which can be interpreted to anything that starts with those letters).
Also, the idea of letting a `Version Control` extension change the label according to what it implements, is really appealing to me.

**Comment by seanmcbreen** [comment]
Here is my suggestion - we will continue to ship vanila Git in the product - the experience out of the box will be as it always has been.  However we will also provide the option to switch to another (workspace specific) VC plugin.  Either thought an obvious market in the workspace (like the .gitconfig file) or through a user action.

**Comment by rkeithhill** [comment]
I want to see in the top of this view which SCM/SCCM/VCS provider VSCode is using.  When I open a Git repo I want to see Git at the top of the view - not SCM.  In fact, if I'm opening a Git repo I'd rather not **see** any change to the UI.  I'd like to see the Git icon in the side bar.  Now if someone opens a Mercurial repo then fine, show their icon in the side bar and put Mercurial in the title of the view.  Now there is the issue of what to display when there is workspace open.  In that case, I'd still display the Git icon as it is the most common SCM tool.  

BTW the new icon to initialize a new repo - blech.  It is too small, folks might not even realize it is a button (as opposed to info display).  And this doesn't tell me there is no repo.  In fact, it seems to think there is a repo:

![image](https://cloud.githubusercontent.com/assets/5177512/23245678/a3c77f60-f94b-11e6-88e2-4e3306389f88.png)

The previous behavior of A) telling me the workspace isn't under source control and B) having an obvious button to initialize a repo is much more informative and discoverable:

![image](https://cloud.githubusercontent.com/assets/5177512/23245670/8a1c4212-f94b-11e6-96f5-8599fb4a6c43.png)

Hopefully this is just a peek into how the sausage is being made (ie it's not done yet) because at this point this feels like a step backwards in usability.

**Comment by joaomoreno** [comment]
![image](https://cloud.githubusercontent.com/assets/22350/24444098/8c359c12-1465-11e7-99de-5f71dce51581.png)
