### ISSUE TITLE
Proposal: Test Output and Messages Correlation

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#187104]
Testing has two ways to associate run data with test items: via `run.appendOutput(message[, location[, test])` and the messages given to `run.passed/failed/errored(test, message)`.

This is fine for runners that separate their console output versus communication that changes test state, but not all runners do. For those that don't, the required failure message may be the same as the output that caused it. This leads to duplication in our UI which is not a great user experience, as @DanTup [commented](https://github.com/microsoft/vscode/issues/185778#issuecomment-1603303818).

I propose a way to deal with this is to make `appendOutput` return a TestMessage that can be given back to the the state transition method. If this is done, the editor can know to deduplicate them:

```diff
-		appendOutput(output: string, location?: Location, test?: TestItem): void;
+		appendOutput(output: string, location?: Location, test?: TestItem): TestMessage;
```

So a consumer might do something like:

```js
runner.onLine(line => {
	const test = extractTestForLine(line);
	const msg = run.appendOutput(line, undefined, test);

	if (testFailedRegex.test(line) && test) {
		run.failed(test, msg);
	} 
});
```

Other approaches:

- Invert it and return the TestMessage from the state transition. I don't feel strongly either way, but it seems more relevant for the output-creating function to also return the TestMessage.
- Allow a TestMessage to be provided to both `appendOutput` and the state transition function. The snag here is that currently TestMessages are never interpreted and terminal output -- they're either plain text or markdown. We could add a new message type, however, but I don't think there'd ever be a case where the "terminal" type TestMessage would be used outside of this pattern.

**Comment by DanTup** [comment]
> Invert it and return the TestMessage from the state transition.

I don't think this will work (at least for me). The problem is my events look like:

1. Test error output ("expected x, got y")
2. Test failed

When (1) arrives, I need to call `appendOutput` but I'm not ready to mark the test as failed (it may not have completed, but may be producing errors). If I buffer the messages, there will be a delay in user seeing output while the test is running.

Another possible option:

- Allow `run.failed(test)` without any message, and use the last appended output. However, this makes assumptions that there was some previous output, and that the last output is the failure output (it probably is, but maybe some teardown function could produce output after a test fails?).

With the first proposal, I can just keep track of any error events TestMessages and use them (or the first/last one?) when calling `run.failed()`.

**Comment by connor4312** [comment]
After discussion in the API sync, we think that instead we can 'fix' this from a UX perspective. Something I've wanted to do for a while is have a 'jump to'/'show output' for a specific test. If this exists, then we don't need to show the additional output messages in the tree, and then the problem of needing correlation and deduplication becomes a non-issue.

I will stage this for the next Insiders, please let me know what you think of the resulting experience.

**Comment by DanTup** [comment]
@connor4312 testing this out and it looks better to me - although is it the case that now there will always be only a single child in the tree below the test?

![image](https://github.com/microsoft/vscode/assets/1078012/996afa2d-231b-4e0e-9d42-aa1fa69deff0)

If so, could the output not be shown against the test node and the child removed? Currently it seems like clicking on the test name doesn't do anything (except maybe expand/collapse) which I find confusing. I feel like clicking on the test name and seeing the output (and it having no children) would be better - but I'm not sure if there are cases where there are more children.

Thanks!
