### ISSUE TITLE
Terminal icon switches every time when pressing Shift key

### ISSUE THREAD

**Issue by SimonSiefke** [microsoft/vscode#187265]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.80.0
- OS Version: Ubuntu 23.04

https://github.com/microsoft/vscode/assets/23744935/b5ec19c2-cdeb-4ba5-8ed9-59c3a290ba20

### Steps to Reproduce:

1. Open the panel
2. Open a file
3. Press Shift
4. The Terminal icon changes
5. Release Shift key
6. The Terminal icon changes again

### Expected behaviour

When pressing `Shift` in the editor, the terminal icon should stay the same.

### Actual behaviour

When pressing `Shift` in the editor, the terminal icon switches to a different icon.

### Code

The issue might haven been introduced here https://github.com/microsoft/vscode/pull/184688

**Comment by joaomoreno** [comment]
FYI I've removed the `regression: ` prefix to the issue's title, since the observed behavior was actually our intention. I can see how on Windows and Linux, reacting on <kbd>Shift</kbd> might be too aggressive, so I propose doing the new behavior (no need to hover) only when <kbd>Alt</kbd> is pressed, while leaving <kbd>Shift</kbd> to behave like before, on Windows and Linux.

**Comment by joaomoreno** [comment]
Verification:

- <kbd>Alt</kbd> should toggle alt state of commands no matter what
- On **Windows** and **Linux** only: <kbd>Shift</kbd> should toggle alt state of commands only when hovering them
