### ISSUE TITLE
Terminal Issue

### ISSUE THREAD

**Issue by 12dutta** [microsoft/vscode#187264]
Type: <b>Bug</b>

The half of a terminal shows a blackscreen and the output showing please help me out these.

VS Code version: Code 1.80.0 (660393deaaa6d1996740ff4880f1bad43768c814, 2023-07-04T15:06:02.407Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9300HF CPU @ 2.40GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (1.56GB free)|
|Process Argv|--crash-reporter-id 368166b1-6321-4d34-a1e0-fb1ef13919b7|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-toggle-quotes|Bri|0.3.6
npm-intellisense|chr|1.4.4
path-intellisense|chr|2.8.4
bracket-pair-colorizer-2|Coe|0.2.4
vscode-eslint|dba|2.4.2
prettier-vscode|esb|9.19.0
auto-rename-tag|for|0.1.10
code-runner|for|0.12.0
live-sass|gle|6.0.5
cmake-tools|ms-|1.14.34
cpptools|ms-|1.16.3
cpptools-extension-pack|ms-|1.3.0
material-icon-theme|PKi|4.28.0
java|red|1.20.0
LiveServer|rit|5.7.9
es7-react-js-snippets|rod|1.9.3
bootstrap-product-icons|rub|1.0.2
cmake|twx|0.0.17
highlight-matching-tag|vin|0.11.0
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscode-java-debug|vsc|0.52.0
vscode-java-dependency|vsc|0.23.0
vscode-java-pack|vsc|0.25.12
vscode-java-test|vsc|0.39.0
vscode-maven|vsc|0.41.0
html-css-class-completion|Zig|1.20.0

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30776702
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
pyind779:30671433
f6dab269:30613381
vscrp:30673768
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
pythongtdpath:30769146
i26e3531:30780429
pythonnosmt12:30779714
pythonidxpt:30784022
pythonnocebcf:30776496
e537b577:30772215

```

</details>

**Comment by meganrogge** [comment]
Thanks for creating this issue! To help narrow it down, please take the time to follow below steps. Thanks a lot and happy coding 🙏 

### Is the issue caused by an Extension?
Stop VS Code and from the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If it still reproduces, jump to the next chapter.

If you see it is an issue with the extension, please run the command `Start Extension Bisect` and follow the instructions to find the extension that is causing this issue.

<img width="631" alt="image" src="https://user-images.githubusercontent.com/900690/228760008-d5790ad1-74da-46a2-917f-e1bd26281ca8.png">

Please report the issue to the extension causing this.

### Is the issue caused by VS Code Core?
If the issue is not caused by an extension, it is maybe caused by your configuration. Try to run `code --disable-extensions --user-data-dir <directory>` where `<directory>` is an empty folder. This will ensure Code is starting with a fresh data directory, e.g. no specific settings and without any extensions running. 

If it still reproduces, it was maybe fixed already in our nightly release. Please download from https://code.visualstudio.com/insiders/ and see if you can reproduce the issue.

Finally, to help us narrow down what change caused the issue, please run the following command to find the build. It will start previous releases of VS Code insiders to see where the regression was introduced:
* `npx --yes vscode-bisect@latest`
* follow the instructions until you found the offending build
* report back the commit range in this issue

Thanks!
