### ISSUE TITLE
Local echo disable under ssh command

### ISSUE THREAD

**Issue by lifei** [microsoft/vscode#187420]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:  1.80.0
- OS Version:  Windows 11

Steps to Reproduce:

1. open the terminal, you will see the local echo function is good.
2.  just `ssh` a remote server then local echo function is disabled.

![localecho](https://github.com/microsoft/vscode/assets/350000/0b98eb99-b796-4ffc-9c1c-08f235e3469e)

**Comment by Tyriar** [comment]
This is because the local echo is handled for the connection between the client (terminal) and the server (shell), not the server and the SSH target. This is by design, by there are improvements that could impact things in https://github.com/microsoft/vscode/issues/135644 and https://github.com/microsoft/vscode/issues/126209
