### ISSUE TITLE
Sticky scroll often has no syntax highlighting in latest insiders

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#187637]
1. Open https://github.com/microsoft/vscode/blob/91f7ffeaf3425abda8748a34d80f02b1eb3fbabc/src/vs/editor/browser/editorBrowser.ts in VS Code
2. :bug: sticky scroll has no syntax highlighting

<img width="691" alt="image" src="https://github.com/microsoft/vscode/assets/30305945/64218f23-aaf6-457b-958c-1c1e74dd876b">

**Comment by aiday-mar** [comment]
Hey @joyceerhl, I update my insiders version and tested on the file you sent, I am currently not able to reproduce this error:

![Screenshot 2023-07-12 at 09 24 02](https://github.com/microsoft/vscode/assets/61460952/453be005-5672-4324-8157-c988c8ee98c8)

Perhaps this is linked to your theme. I was wondering what theme you are using?

**Comment by aiday-mar** [comment]
It appears this is due to the following PR https://github.com/microsoft/vscode/pull/187567 which attempted to fix https://github.com/microsoft/vscode/issues/185884. Since the state was no longer recomputed when the new state was equal to the old state, this means that the rendering was no longer done when the model tokens changed but the state remained the same. A fix will be made to revert this change.
