### ISSUE TITLE
[Bug]: Sticky scroll content stays rendered in black

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#187918]
* enable sticky scroll
* open a file and scroll such that sticky scroll appears
* reload the window
* observe that the sticky scroll lines are not colored until they get rerendered once
* there is `ITextModel.onDidChangeTokens` that could be used

https://github.com/microsoft/vscode/assets/5047891/0c604bf6-4c80-48fb-b9fa-cbbc3126ccff

```
Version: 1.81.0-insider
Commit: 2f1013a310bbd74410e74fad99497841edad0eda
Date: 2023-07-13T06:08:44.300Z
Electron: 22.3.14
ElectronBuildId: 21893604
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.5.0
```

**Comment by aiday-mar** [comment]
Hey thanks for filing the issue. The listener onDidChangeModelTokens already exists inside of the sticky scroll code. I'll investigate the issue.

**Comment by aiday-mar** [comment]
It appears this is due to the following PR https://github.com/microsoft/vscode/pull/187567 which attempted to fix https://github.com/microsoft/vscode/issues/185884. Since the state was no longer recomputed when the new state was equal to the old state, this means that the rendering was no longer done when the model tokens changed but the state remained the same. A fix will be made to revert this change.
