### ISSUE TITLE
Exact matches are hard to find in outline

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#187921]
* I wanted to go to the editor create function
* open `monaco.d.ts` (at the top)
* open outline cmd+shift+o
* type `create`
* it is difficult to find this function because there are others above it which start with `create...`:
```ts
	export function create(domElement: HTMLElement, options?: IStandaloneEditorConstructionOptions, override?: IEditorOverrideServices): IStandaloneCodeEditor;
```
* I tried using `create(` but that didn't work and then I had to use the find widget

<img width="756" alt="image" src="https://github.com/microsoft/vscode/assets/5047891/873ca060-9469-4967-a259-1192e28e0564">

**Comment by jrieken** [comment]
Passing this quick pick land. Unfortunately my attempts to have this sort by match quality have not survived.

**Comment by bpasero** [comment]
@jrieken can you clarify, symbols picker is still using `fuzzyScore` which I believe is the same we use for completions:

https://github.com/microsoft/vscode/blob/64b28fbd1b0f8293c1bbf3fd27ffefd8c71f68f4/src/vs/base/common/filters.ts#L628

In my testing I see a score of `10` for both `create` as identical match and for others. In that case we resort to sorting by appearance in the document:

https://github.com/microsoft/vscode/blob/64b28fbd1b0f8293c1bbf3fd27ffefd8c71f68f4/src/vs/editor/contrib/quickAccess/browser/gotoSymbolQuickAccess.ts#L409-L413

We could change that to sort by result length, but I wonder if a 100% identical match should get a score boost.

**Comment by jrieken** [comment]
@bpasero Use the `boostFullMatch`-option when calling `fuzzyScore`

**Comment by bpasero** [comment]
@jrieken ah, we already set that, but looking into it I see the issue: we pass in `"$(symbol-function) create"` as `word` because symbol results contain codicons. When you then type `@create` it will never be considered a full match.

In the logic to figure this out:

https://github.com/microsoft/vscode/blob/9784f876f9d9f3c443d6313c533e342c89fb8a79/src/vs/base/common/filters.ts#L767-L771

I wonder if we need to account for the `wordStart` that we pass in (that is the offset after the codicon), making it:

```ts
if (wordLen - wordStart === patternLen && options.boostFullMatch) {
	// the word matches the pattern with all characters!
	// giving the score a total match boost (to come up ahead other words)
	result[0] += 2;
}
```

**Comment by jrieken** [comment]
Sounds about right ;-)
