### ISSUE TITLE
[folding] Fold selection

### ISSUE THREAD

**Issue by bbofdoom** [microsoft/vscode#18805]
In Visual Studio by doing Ctrl+M followed by Ctrl+H we were able to fold ANY regions in a code.
Could we please have an equivalent feature in Code. Thanks may God bless the dev team!

**Comment by dbaeumer** [comment]
@alexandrudima FYI.

**Comment by jeff-hykin** [comment]
I think this feature request includes character-based (rather than line-based) code folding;
ex: 
before folding:
<img width="691" alt="screen shot 2017-09-10 at 12 37 34 am" src="https://user-images.githubusercontent.com/17692058/30246478-cb6e68c8-95c0-11e7-8283-f06dc1e3e0a2.png">
after folding:
<img width="640" alt="screen shot 2017-09-10 at 12 37 42 am" src="https://user-images.githubusercontent.com/17692058/30246479-da37c408-95c0-11e7-9149-404abd6e8d40.png">

And I just wanted to point out that if this kind of feature were added, then myself and others could likely start working on extensions to handle these issues:

- https://github.com/Microsoft/vscode/issues/3422 Language-Aware Folding
- https://github.com/Microsoft/vscode/issues/29890 Custom Collapse Patterns
- https://github.com/Microsoft/vscode/issues/12146 Fold Regions
 
And likely some other issues as well.

**Comment by JBrace1990** [comment]
+1 for this feature request. It's one of the more annoying things things I've found by switching over to this IDE than NuSphere PHPEd.

**Comment by coodoo** [comment]
Any update on this?

**Comment by paulomunoz** [comment]
This would be indeed a very useful feature! I'm actually wondering if this is available in any other editors, apart from Visual Studio?

**Comment by r-amaral** [comment]
@paulomunoz: I'm not sure whether this is exactly what @bbofdoom is requesting but Atom has something that's, at least, similar (from https://flight-manual.atom.io/using-atom/sections/folding/):  
> Finally, you can fold arbitrary sections of your code or text by making a selection and then typing Alt+Cmd+Ctrl+F or choosing "Fold Selection" in the Command Palette.

**Comment by ackvf** [comment]
Of course Sublime Text also has this.

**Comment by MartinJHammer** [comment]
I'd love to see this feature as well :)

BTW I love visual studio code. The dev team is an inspiration.

**Comment by BinaryShrub** [comment]
I'd like this as well

**Comment by tomatau** [comment]
This is a fairly basic feature, please add

**Comment by bjoe88** [comment]
Badly need this. Please add

**Comment by peterallcdn** [comment]
Back to coding after taking many years off. I've only been using VS Code for a week or so and already I see the need for this feature. Please add it, thanks!

**Comment by tony-thomas-git** [comment]
Adding my vote for this feature. Great code folding includes folding selection(s).

**Comment by iladin** [comment]
Adding my vote as well, looking to hide lines that begin with a REGEX

**Comment by AerionDyseti** [comment]
Adding another vote for this feature; folding statements within a mustache template.

**Comment by julesgilson** [comment]
so many less important features released each month... and still not this fairly basic one!

**Comment by coconewty** [comment]
Please add this feature! It makes such a difference and is something that I really miss after switching from Sublime to VS Code.

**Comment by Tiedye** [comment]
#50840 is required to implement this

**Comment by hanselmandrew** [comment]
Bump +1

**Comment by JanChodorowski** [comment]
Bump

**Comment by yijiangh** [comment]
Bump +1

**Comment by Tiedye** [comment]
@hanselmandrew @JanChodorowski @yijiangh please do not post empty "+1" responses, that is what reactions are for.

**Comment by mthines** [comment]
Or the `Subscribe` button in the top right. 👍

**Comment by julesgilson** [comment]
it is also pretty pointless. This issue has been ongoing for 2.5 years with zero indication it is even being considered. Still, we can now keep the cursor centred in the window when scrolling, so who needs basic functionality?

**Comment by duk3m0n** [comment]
Vote for fold selection! It is painful to scroll over whole screen for jumping over large blocks of comments and reading the important code

**Comment by psycoxer** [comment]
need this feature baked in to vs code. but this extension does the trick : [#region](https://marketplace.visualstudio.com/items?itemName=maptz.regionfolder)

**Comment by eliumoraes** [comment]
I was looking for this feature. Using Datagrip I can fold part of my queries. Can't believe that code really does not has this function.

**Comment by Zhou-Yucheng** [comment]
Really really really need this feature!

BTW, I don't think this feature request *includes character-based (rather than line-based) code folding* as @jeff-hykin mentioned. 
Actually, this feature can be considered as **folding all the selection lines**, rather than characters. Maybe it will make the implementation easier.

**Comment by dwall60** [comment]
I've been using SlickEdit for some time and it's a great editor but I decided to try VS Code since I'm tired of paying maintenance on SlickEdit. SlickEdit can fold on ANY regex pattern, and it's a line fold, not a character fold. It's called Selective Display.

This is an extremely beneficial feature for me because I review log files from embedded devices a LOT and it's great to collapse the log file based on a regex so I can see a pattern emerge when looking for specifically logged items.

VS Code appears to be very flexibile, but I was very disappointed when I found that it couldn't do this.

Also, it seems kind of silly to me to have to put #region, #pragma region, etc in the code to get it to fold when you could just use a regex to easily fold on anything.

**Comment by aeschli** [comment]
@dwall60 Thanks for the feedback. Would you mind filing a separate issue that also shows a bit how this works in SlickEdit. I'm curious to know how users provide the regexes and how the regexes look like (one regex for the whole region, or separate start end regexes)

**Comment by commadelimited** [comment]
> This would be indeed a very useful feature! I'm actually wondering if this is available in any other editors, apart from Visual Studio?

Yes. Sublime Text has had this for years.

**Comment by commadelimited** [comment]
I'll add my vote for this feature as well. Language aware folding might be nice, but just let me fold abritrary lines and you've got a solution already. I want to collapse, into a single line, every unit test in my file but for the one I'm working on. I want to collapse every controller method but for the one I'm working on. It's not enough to be able to collapse the functions themselves because that still displays the method signature.

**Comment by yubaoquan** [comment]
There years... this issue still open.

**Comment by RaptorX** [comment]
came to post a request and found this issue laying around still :(
wont even bother.

**Comment by igorcmelo** [comment]
Sadly it stills open

**Comment by NotWearingPants** [comment]
Inline folding is here: #50840

**Comment by Nice2Work** [comment]
Yes please, I do not think there is one cursor move I do all day, and that is putting at the begin and than CTRL + [, while I would love to just select and CTRL + whatever to do all parts folding that can be folded into each their own...
But I am afraid we are talking to some deaf ears as this is already requested ....> 3 years now?

**Comment by Nick-Hopps** [comment]
How to fold/unfold selected contents？seems that folding/unfolding only works on the whole document.

**Comment by yayayahahaha** [comment]
Any update?
I'm trying to migrate from SublimeText to VSCode, but it seems both of them just can't replace another.

**Comment by tjx666** [comment]
Sometime would be very helpful with this.

**Comment by jeff-hykin** [comment]
After 5 years of waiting, I'm glad to see the update. Thanks @aeschli !

**Comment by yayayahahaha** [comment]
So exciting to see this feature!

**Comment by commadelimited** [comment]
Thanks @aeschli! Do you have an idea of when this will actually be released? I can't wait to use.

Kudos to all your hard work (and to whomever else was involved).

**Comment by eliumoraes** [comment]
Thank you very much! Never believed that would be released. I'm grateful! Thanks again!

**Comment by Tiedye** [comment]
The feature doesn't seem to work as it does in the referenced apps.  If I select a range in one line it doesn't do anything, folding part way through a line also doesn't work.  It only seems to be able to collapse whole lines

**Comment by aeschli** [comment]
Yes. we still only support folding full lines, not subranges. So you need to select the lines to fold.
