### ISSUE TITLE
Find can't find \n when it's preceded by anything

### ISSUE THREAD

**Issue by cparker4486** [Microsoft/vscode#18817]
- VSCode Version: 1.8.1
- OS Version: Win 10 1607

Steps to Reproduce:

1. Open any file
2. Ctrl+F to activate Find
3. Enable regex search
4. Enter `\n`
5. See that it matches all the line endings
6. Now try searching for the last two characters from a line _including_ the line ending: \n
7. See that the nothing is found and Find believes there are "No results"

![15_06_36-adminwk-002 - remote desktop connection manager v2 7](https://cloud.githubusercontent.com/assets/1189638/22129120/07ec6022-de59-11e6-9d31-6cd27c58340a.png)

![15_07_59- untitled-4 - visual studio code](https://cloud.githubusercontent.com/assets/1189638/22129142/1a941ce2-de59-11e6-8e7d-9ac22fceecfe.png)

**Comment by alexandrudima** [comment]
@cparker4486 Please us `\r\n` if your file has CRLF line endings

**Comment by cparker4486** [comment]
@alexandrudima If that were the answer, shouldn't `\n` not match anything contrary to my first screenshot? But it clearly _does_ match line endings and you can even replace the line ending with `<something>\n` and it will work.

I strongly believe you need to take a second look at this. At the very least, it sounds like what you need to do is make Code _not_ match on `\n` when it should only be matching on `\r\n`.

**Comment by alexandrudima** [comment]
@cparker4486 

* if your text consists of `"ABCD"`
* if you search for `"C"` there will be a result
* if you search for `"AC"` there will be no results (notice how `"B"` is omitted)

The same happens here where the text is `"f\r\na"`
* if you search for `"\n"` there will be a result
* if you search for `"f\n"` there will be no results (notice how `"\r"` is omitted).

**Comment by cparker4486** [comment]
abcdef
    abcdef
    abcdef

* Search for `\n` and you get matches
* Replace with `\n` and you get no changes (at least, visually)

* Search for `\r\n` and you get same matches as above
* Replace with `\r\n` and you get

    abcdef\r
    abcdef\r
    abcdef\r

Is this the expected result? If so, I don't see how. `\r\n` should be invisible.

Further, shouldn't replacing `\n` with `\n` result in the following?

    abcdef
          abcdef
                abcdef

**Comment by alexandrudima** [comment]
Notice how you do not type a carriage return and a newline character in the replace string, but four characters: `"\"`, `"r"`, `"\"` and `"n"`. The replace string therefore consists of 4 characters.

Explanation:
* When the regex button is toggled, the replace string gets parsed.
* Here are the special character sequences we support in the replace string when regex is on:

| char sequence | replace semantics |
|---|---|
| \n | inserts a new line using the configured line ending |
| \t | inserts a TAB |
| \\\\ | inserts a "\\" |
| $$ | inserts a "$" |
| $& and $0 | inserts the matched substring |
| $n | Where n is a non-negative integer lesser than 100, inserts the nth parenthesized submatch string |

* the implementation is here:
https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/find/common/replacePattern.ts#L165

* note how `"\r"` is not interpreted in any special way, same as `"\a"` for example.

We have found these to be sufficient to get almost any job done. What is the use case of parsing `"\r"` in any special way in the replace string?

**Comment by cparker4486** [comment]
> We have found these to be sufficient to get almost any job done. What is the use case of parsing "\r" in any special way in the replace string?

That's easy to answer: **When I'm working with regex I expect to be working with regex not an arbitrary subset of regex depending on context.**

That list of special character sequences you listed makes sense only when regex is not supported in an editor and you need a rough and dirty set of regex-like sequences. But once regex is implemented, those should be replaced with legit regex.

Ask yourself this question, "Why would anyone, approaching Code for the first time, expect regex in Find and an arbitrary subset of regex in Replace?"

With all due respect to you, and the rest of the Code team, the implementation is inconsistent and requires training (the antithesis of usability). You should prefer usability and consistency over adherence to an arbitrary design decision.

Perhaps it's appropriate to keep this case closed and replace it with a new one called, "Implement full regex in Replace field in Find and Replace dialog"?

**Comment by alexandrudima** [comment]
@cparker4486 Please read my above comment again. **I talk about the replace string. The search string supports the JavaScript regex syntax**.

![image](https://cloud.githubusercontent.com/assets/5047891/22177247/4406f050-e01a-11e6-94a7-43aeb5937ae4.png)


---

Thank you for your opinion, but do take into consideration that the replace string is not a regular expression. 

The features supported in the replace string are called substitutions. In my previous comment I have listed in a table the substitutions vs code supports.

Here are, for example substitutions supported by other editors:

---

### Substitutions supported in Visual Studio
https://msdn.microsoft.com/en-us/library/2k3te2cs.aspx
![image](https://cloud.githubusercontent.com/assets/5047891/22177146/cb6f83e2-e018-11e6-9c18-99071deb4f41.png)

* Notice how they link to the substitutions supported in .NET, since Visual Studio is implemented using .NET:
https://msdn.microsoft.com/en-us/library/ewy2t5e0.aspx
![image](https://cloud.githubusercontent.com/assets/5047891/22177135/96101b62-e018-11e6-804c-7f1e70947e6c.png)

---

### Substitutions supported in Sublime Text
http://docs.sublimetext.info/en/latest/search_and_replace/search_and_replace_overview.html#regular-expressions
![image](https://cloud.githubusercontent.com/assets/5047891/22177164/1f251e52-e019-11e6-9df6-1d6787d7ef1b.png)

* Notice how the unofficial documentation links to the boost library, presumably because Sublime is written in C++ and implements search/replace using boost:
http://www.boost.org/doc/libs/1_44_0/libs/regex/doc/html/boost_regex/format/perl_format.html

![image](https://cloud.githubusercontent.com/assets/5047891/22177183/60703de2-e019-11e6-837d-ee5f0da1cde5.png)

![image](https://cloud.githubusercontent.com/assets/5047891/22177186/687deb1a-e019-11e6-96b4-4412e5ecca48.png)

---

And finally, our substitution table is the one I provided in the comment above, guided ofcourse by our runtime, JavaScript:

![image](https://cloud.githubusercontent.com/assets/5047891/22177223/dca9cc2a-e019-11e6-9a63-609d7896b9d7.png)


https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace#Specifying_a_string_as_a_parameter
![image](https://cloud.githubusercontent.com/assets/5047891/22177209/a2332028-e019-11e6-9c56-bf81ff7c7aa1.png)

---

**Comment by cparker4486** [comment]
I'm not sure if you're trying to be condescending (I presume not) but I know which field is Find and which field is Replace. I'm not sure why you felt the need to post a screenshot with big red letters and lines pointing them out. (Did you honestly think I didn't know what I had posted about?)

Secondly, if you're going to post the substitutions implemented by other editors, please, _please_, feel free to implement Sublime Text's. I would be more than happy with that. ST is where I go to do sophisticated find and replace.

Code is coming along (very) quickly but I'm afraid this component still has some improvement left in it. (Which reminds me of another usability problem in this component. The find and replace dialog covers matches. It shouldn't do this. Instead, it should move out of the way so that matches can be seen. Again, refer to ST for a good implementation of a find and replace dialog.)

Thank you.

**Comment by alexandrudima** [comment]
@cparker4486 Thanks for the extra explanation and apologies if I seemed condescending in any regard, I wanted to be sure we talk about the same things. I can summarize the following ideas from our discussion:

1. The search string `\n` when regex is on should match `\r\n` when the file has CRLF line endings. I disagree and will not do any change in this direction.
2. The replace string should support more escape sequences, like `\v` for vertical character, etc. I have created a separate feature request #19017
3. Due to it sitting at the top right corner of the editor, the find widget can sometimes be rendered on top of find matches. This has already been reported in #10662.

**Comment by cparker4486** [comment]
@alexandrudima Thanks. Looks like we're making some progress. 👍 

#1. I just don't get it. I don't understand your reasoning behind this. Why do you consider it acceptable for `\n` to match `\r\n` only when `\n` is not preceded by any other characters?

If `\n` is shorthand for `\r\n` in the Find string it should _always_ work.

Is there anyone else that can weigh in on this from the Code team? Is there possibly a language barrier between us?

**Comment by alexandrudima** [comment]
@cparker4486 

Hopefully we can overcome English language barriers and switch to JavaScript.

Try the following with nodejs or in a browser:
```js
function explain(target, regex) {
     console.log(`Looking for ${regex}. Result: ${regex.test(target)}`);
}
explain("abcdef\r\nabcdef\r\nabcdef\r\nabcdef\r\n", /\n/m);
explain("abcdef\r\nabcdef\r\nabcdef\r\nabcdef\r\n", /f\r\n/m);
explain("abcdef\r\nabcdef\r\nabcdef\r\nabcdef\r\n", /f\n/m);
```

```
Looking for /\n/m. Result: true
Looking for /f\r\n/m. Result: true
Looking for /f\n/m. Result: false
```

---

Trying one last time in English:
> Why do you consider it acceptable for `\n` to match `\r\n` only when `\n` is not preceded by any other characters? If `\n` is shorthand for `\r\n` in the Find string it should _always_ be shorthand.

`\n` matches the `\n` in `\r\n`. `\n` is not matching `\r\n`. `\n` is not shorthand for `\r\n`.

**Comment by alexandrudima** [comment]
@cparker4486 I gave it more thought and I think I understand where you're coming from and why it appears that `\n` matches `\r\n`. I have created #19225 to further track this. Thank you for your persistence with me

**Comment by cparker4486** [comment]
@alexandrudima Thanks! Very much appreciated.

**Comment by alexandrudima** [comment]
@cparker4486 Thanks again! :heart:

Just pushed a change that makes it that `\n` matches the End-Of-Line sequence, regardless if the file is LF or CRLF, so basically your original case will work as you'd expect. There is a side-effect, that `\r` will never match anything, ever, but I think that's ok, since `\n` can be used to target the EOL sequence.
