### ISSUE TITLE
`restart to update` command doesn't install latest update

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#188174]
Steps to Reproduce:

1. run `restart to update`, vs code restarts and updates.
2. check the command palette for 'update', neither `restart to update` or `check for updates` is available
3. after a minute or so `restart to update` is back again

I assume it's because I'm a couple versions behind and doesn't know about the latest yet, it would be nice if part of that command would check that it's actually going to install the latest and let me wait for it to download if there is another.

**Comment by joaomoreno** [comment]
This comes up often, but it's a hard and infrequent issue. The reason why it's hard is because by the time you see the first update notification, the update has been applied on disk; switching to a different update would requiring rolling that back and then forward with the new update. The reason why it's infrequent is because it just happens on high-frequency updates, like Insiders. It's not a common Stable issue.

To further complicate things, and adding to the hardness of it:

- On macOS, we don't control this, Electron does, so it would need to be implemented at the Electron layer.
- On Windows, rolling back would mean rolling back an Inno Setup installation already in progress. This scares me.
- On Linux, we only have in-app updates for Snap. This one should be simple enough to implement properly since updates do not overwrite but are siblings to the original version.

**Comment by amunger** [comment]
what about a notification when a new update is available right after I update? I made it through a good amount of TPI work before realizing I needed to update again.

**Comment by joaomoreno** [comment]
We check for updates [30 seconds after startup](https://github.com/microsoft/vscode/blob/268f34992c5d826a08e4b72013f95af9683044ea/src/vs/platform/update/electron-main/abstractUpdateService.ts#L112), so we're not on the critical startup perf path.
