### ISSUE TITLE
Support a `--password-store=inmemory` or similar

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#188432]
The main purpose of this would be for running in CI when you need _some_ sort of secret storage store, but it doesn't have to live on. 

Right now `--password-store=basic` allows the SecretStorage API to work, but it still stores things on disk which isn't needed in CI scenarios... and it's probably better to store it in memory than weakly on disk in CI anyway.

**Comment by deepak1556** [comment]
`--password-store=basic` atleast on the runtime side does not store anything on disk, the encryption key is derived from a password string that is embedded in the executable and everything is in-memory. When this flag is used, the encryption key is derived from `GetPasswordV10` rather than `GetPasswordV11` in https://source.chromium.org/chromium/chromium/src/+/refs/heads/main:components/os_crypt/sync/os_crypt_linux.cc

**Comment by TylerLeonhardt** [comment]
Yeah I think I need a new flag then that disables the "storing" part of the SecretStorage API.

**Comment by TylerLeonhardt** [comment]
Marking as verified since our smoke tests are happy once again.
