### ISSUE TITLE
Test: alternative Quick Question UXs

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#188542]
Refs: https://github.com/microsoft/vscode/issues/188540

- [x] anyOS: @bpasero 
- [x] anyOS @amunger
- [x] anyOS @andreamah

Complexity: 5

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23188542%0A%0A&assignees=TylerLeonhardt)

---

We have 2 more UXs to play with of the Quick Question UI. The mode can be configured with the setting `"chat.experimental.quickQuestion.mode"` … and it has 3 values:

* `singleQuestion` - 1 question, 1 answer (previous experience)
* `inputOnBottomChat` - more-or-less the Chat View lifted into a quick pick-y view
* `inputOnTopChat` - a hybrid of quick pick input at the top, and the list view of the chat

You can launch this experience by doing `cmd/ctrl` + `shift` + `i` or by typing something in the command palette and using the “Ask Copilot” option when entering a query.

Additionally, you can show a button in the titlebar using the setting: `"chat.experimental.defaultMode"`. This has 3 options:
* `chatView` - shows the Chat in the Activity Bar which opens the view in the sidebar
* `quickQuestion` - shows the Chat button in the title bar which opens the quick question experience 
* `both` - has both experiences visible

There’s some obvious polish here, but I wanted to get it to a state where you all can play around with these 3 UX to answer the following questions:

* Which feels the best?
* If this were the default chat experience over the Chat View in the Sidebar, which has the most potential to do that?

and then also any feedback that is concrete like “if you did X, I think `inputOnTopChat` would be nicer”

**Comment by bpasero** [comment]
I believe both views for chat have a reason to be there. I doubt I would want to read and follow a lengthy answer in the quick experience, rather go to the view then. Also when I want to keep track of previous searches.
But when I have a quick question and do not want to loose my context, I feel the picker is a great solution. In that case I would not expect to ask multiple questions, but just one (`singleQuestion` mode).

**Comment by amunger** [comment]
I'm not seeing a chat button in the activity bar for either "chatView" or "both" values for `chat.experimental.defaultMode`

<img width="783" alt="Screenshot 2023-07-25 093039" src="https://github.com/microsoft/vscode/assets/2019016/3478ee63-78b4-49d9-bde1-b05e23ab2129">

**Comment by amunger** [comment]
I prefer the `inputOnBottom` mostly because it's easier to see where the new question was inserted and the change is more gradual, rather than a sudden disruptive change to place the old question just out of view as `inputOnTop` does.

**Comment by andreamah** [comment]
Awesome work! Here's my experience with it:

1. I don't know if I'd use `inputOnBottomChat` and `inputOnTopChat`. It seems like a more limited version of the sidebar chat. It's a little irritating that I can't resize the window and such, but I also understand that that's just a part of it being a quick input. I would much rather use a shortcut to jump to the chat or even a chat editor in the cases that I'd usually use `inputOnBottomChat` and `inputOnTopChat`. It's implemented really well, though! I totally get how you would get from the `singleQuestion` implementation to this in terms of iterating on ideas.
2. `singleQuestion` is super useful and I think I'd use it. One thing is that I wish that the question would move to a new session when it moves to the sidebar chat. But I also understand that it'd clear the current content of the chat, which is not great. Perhaps something to consider if we ever enable support for multiple tabs with different sessions in the sidebar? Not sure if this is even productive advice haha.
3. `"chat.experimental.defaultMode"` doesn't seem like the best way to configure this. I feel like hiding/showing these two icons individually would make more sense. For me, I'd want both there such that I can click them if I want to, similar to having different badges on the sidebar. I think most people wouldn't want to hide the sidebar chat because the use the quick question and vice versa.

Hopefully you don't mind all that rambling above 😅 + hope it helps a little!
