### ISSUE TITLE
No Clone Git repository option available

### ISSUE THREAD

**Issue by RIDHAMDD** [microsoft/vscode#188630]
Type: <b>Feature Request</b>

No Clone Git repository option available

VS Code version: Code 1.80.1 (74f6148eb9ea00507ec113ec51c489d6ffb4b771, 2023-07-12T17:22:07.651Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by gjsjohnmurray** [comment]
Have you followed the instructions at https://code.visualstudio.com/docs/sourcecontrol/intro-to-git yet?

**Comment by RIDHAMDD** [comment]
![image](https://github.com/microsoft/vscode/assets/91961949/c03b9930-e537-49a8-ba61-33961eeb338d)

The button for the same doesn't show up

**Comment by gjsjohnmurray** [comment]
At a Windows command prompt please run `git version` to confirm what version you installed.

**Comment by RIDHAMDD** [comment]
[image: image.png]

It is the latest version

**Comment by gjsjohnmurray** [comment]
What do you see after you choose the third option on Activity Bar (Source Control view) instead of Explorer view?  See the screenshot at https://code.visualstudio.com/docs/sourcecontrol/intro-to-git#_clone-a-repository-locally

**Comment by lszomoru** [comment]
The git extension does indeed contribute welcome views to the "Explorer" view and it uses the `scmRepositoryCount` context key. The problem is that this particular context key is only set when the "Source Control" view is rendered. So if you switch to the "Source Control" view and then back to the "Explorer" view then the option to clone a repository will appear.
