### ISSUE TITLE
cursor will jump to the bottom after format on save/paste

### ISSUE THREAD

**Issue by zhouxinghong** [microsoft/vscode#188633]
Vscode editing json has wrong behavior

Hello! Editing json in vscode will cause wrong behavior

Error 1:
After enabling ` "editor.formatOnSave": true,`
Trigger Ctrl+S and the cursor will jump to the bottom

https://github.com/microsoft/vscode/assets/54253524/288ba573-0a0e-4412-83dd-4b0f8cde2099

Error 2:
After enabling ` "editor.formatOnPaste": true,`
After using the mouse to paste the code, the cursor will randomly jump to the bottom

https://github.com/microsoft/vscode/assets/54253524/61f65670-b7af-4701-8ab2-3c0e0537fc72

The above error has existed for a very long time. It was originally thought that it would be fixed, but it has not been fixed until now. . .

Windows 10
VSCode 1.81

Associated extensions:
Prettier

**Comment by johnphealipto** [comment]
The same issue applies only to a JSON file.
Works fine when the **editor.formatOnSave** is set to `false` on settings.json
![image](https://github.com/microsoft/vscode/assets/69410277/6c9f9aba-36c1-4cd8-94d6-54c03d81a1d9)

**Comment by hediet** [comment]
This happens because formatting emits a single edit that replaces the entire text with the formatted text.
Because in your case the file is very big, VS Code does not try minimize the edit by diffing it against the replaced text.

I think for formatting where just whitespace changes, we could implement a more efficient algorithm to minimze the edit.
Alternatively, the formatting provider should not provide a single edit, but smaller edits.
