### ISSUE TITLE
Commands do not work in single question mode

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#188797]
Testing #188542

Looks like they are not supported:

![image](https://github.com/microsoft/vscode/assets/900690/f152ccb7-adc8-427b-9254-0fb7197cd993)

**Comment by TylerLeonhardt** [comment]
slash commands do work:
![image](https://github.com/microsoft/vscode/assets/2644648/8887206a-4755-4a4b-984a-a2e82719a572)

they just don't have any cool rendering/completions experience because it's using the quickinput box not the chat input box.

This needs https://github.com/microsoft/vscode/issues/35785 but likely the inputOnTop is just a better way to go as it has more features for free and is similar to this mode.

**Comment by TylerLeonhardt** [comment]
This mode no longer exists.
