### ISSUE TITLE
Should quick chat be part of command center?

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#188799]
Testing #188542

![image](https://github.com/microsoft/vscode/assets/900690/4dbe14fa-c3a1-473c-8d6e-5b29ecf1fe73)

I find the chat button in the toolbar on the right a bit off. I wonder if the chat could be a choice for when using command center as the catch-all solution for everything the user wants to do at that point?

It seems the command center is not enabled by default though, but maybe if it is, the chat button could move into the command center to be quickly accessible, or be an entry of the command center.

//cc @jrieken

**Comment by TylerLeonhardt** [comment]
![image](https://github.com/microsoft/vscode/assets/2644648/0bfaf9f8-0949-4474-8008-5a2f50a33d3e)
on the right or left of the share button?

I didn't put it over there because the command center isn't on by default...but if that were the default, then I like having it to the right of the command center.

**Comment by bpasero** [comment]
Yes, either inside the rounded box as a button or close to it. And I think we should make it on by default.

**Comment by TylerLeonhardt** [comment]
Closing this as we settled on having it be an entry in the Command Center:


![Image](https://github.com/microsoft/vscode/assets/2644648/8301fde9-0a9c-4a2f-a47c-409188ed8ba4)
