### ISSUE TITLE
Accessible view reads instructions every time before the actual response

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#188826]
Testing #188537

Maybe users will want it to read the response first, then the extra instructions to focus next or previous responses

<img width="567" alt="image" src="https://github.com/microsoft/vscode/assets/323878/6f7632fe-204e-4c97-b1e4-44926a703931">

**Comment by meganrogge** [comment]
The response might be very long - but will await feedback from @jooyoungseo and @rperez030 on this and go with whatever they think

**Comment by rperez030** [comment]
although I agree with @roblourens  in principle, this way of presenting the information is consistent with the way we are doing it in the rest of the editor. I believe users are likely to turn that off as soon as they understand the functionality. In my opinion, instructions like this would be part of the control's description instead of the control's name. That way they will be readd by screen reader after the actual value of the field, which in this case is the response. In conclusion, I would leave it as it is for the sake of consistency. Screen reader users who are truly getting started with the editor may appreciate the way it is, but that is hard to tell without a larger survey.

@meganrogge The problem I found while testing this, and this is maybe covered somewhere else already, is that, if I switch off accessibility.verbosity.panelChat to remove the extra instructions, the automatic readout of the chat responses gets turned off as well. If this is intentional, there must be a separate setting for that in my opinion. I have not tried the equivalent for the inline chat yet.

**Comment by meganrogge** [comment]
thanks, we will close this issue for now and gather more feedback @rperez030. 

that sounds like a different bug - i'll make an issue if I can repro

**Comment by meganrogge** [comment]
I can reproduce this problem with accessibility verbosity enabled

**Comment by meganrogge** [comment]
tracking that here #188835

**Comment by rperez030** [comment]
> I can reproduce this problem with accessibility verbosity enabled

Me too. In mac as well. Messages do not get announced consistently.

**Comment by meganrogge** [comment]
will be fixed in insider's tomorrow, thanks for the nudge
