### ISSUE TITLE
Weird vertical gap between input and results in test view

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#188841]
Testing https://github.com/microsoft/vscode-python/issues/13301

None of the other views which have inputs at the top have a gap like this, not sure if this is specific to Pytest:

<img width="515" alt="image" src="https://github.com/microsoft/vscode/assets/30305945/7fbabba3-bce1-4319-b6be-2c46438600e7">

**Comment by connor4312** [comment]
That's from https://github.com/microsoft/vscode/pull/188484, and it goes away(/is filled) once tests are run for the first time. I'm happy to hear other ideas for that area. Or maybe we can indicate state in ways that don't require showing text there...

**Comment by eleanorjboyd** [comment]
I think a better solution would be to display this text differently to notify the issuer. I think the fact that it says pytest discovery as part of the dropdown is weird to begin with. Might be worth spending time doing a further investigation in ways to display testing errors to users. @connor4312 would be interested to know if you have any ideas. Otherwise, this would be something I can explore following the rewrite and some more pressing performance issues.

**Comment by connor4312** [comment]
I think I want to put some kind of less-literal display of text there. Something like

```
[ Filter box here          ]
❌ 123/126							12.4s
												^ timer counts up as tests run
^ tooltip "123 of 126 tests passed"
```

Then text "waiting for a test run" when there wasn't any previous test run.

I think the pytest discovery error is not what Joyce was talking about here, but I'm happy to hear ideas to improve it.

**Comment by eleanorjboyd** [comment]
understood thank you! I think a display like that would be great

**Comment by karthiknadig** [comment]
Verified
![image](https://github.com/microsoft/vscode/assets/3840081/3254d22e-c119-4ae8-b1b8-f60604a58d5b)
