### ISSUE TITLE
[WelcomeUX] Pressing F8 to jump to next error in embedded editor loses place in walkthrough

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode#18929]
Testing #18091

**Comment by chrmarti** [comment]
This happens when MarkerNavigationWidget calls focus() on the container. Commenting that makes the viewport not jump anymore. Tried for some time to understand what is going on without luck. @jrieken Any hints you can give on that? I see the zone widget being offscreen, but that seems to be the same in the regular editor.

**Comment by jrieken** [comment]
Not really sure what you mean.

**Comment by jrieken** [comment]
Ok, now i have seen it. According to @alexandrudima this happens because we call `focus` and because then the browser wants to really, really make sure the element is in the viewport. Unsure what to do next. We call focus because of accessibility but we can also thing about having a second set of command that only reveal and don't focus

**Comment by alexandrudima** [comment]
Well, that is what I speculate happens. But it needs to be confirmed by looking if the scrollTop changes.

**Comment by chrmarti** [comment]
scrollTop of the div that is used for scrolling by the DOMScrollableElement does indeed change. Removing the .focus() call stops the scrolling. What I don't quite understand yet is why we don't see the same happening with the regular editor, does that use a different approach for scrolling?
