### ISSUE TITLE
[json] Support extending JSON completion

### ISSUE THREAD

**Issue by WebFreak001** [Microsoft/vscode#1893]
Right now there are some hard coded completions like npm or bower versions (https://github.com/Microsoft/vscode/tree/master/src/vs/languages/json/common/contributions)

However it seems it isn't extensible with custom packages, so adding an API for that would be great because I would really like to add support for completing versions in my package

**Comment by egamma** [comment]
Great minds think alike :smile: This is on the plan and we start on it in January, pls see the January iteration plan #1826, in the Debt section.

CC @aeschli

**Comment by WebFreak001** [comment]
Seems like this has been added in vscode 1.1.0

**Comment by aeschli** [comment]
Yes, correct. I forgot to close this issue and comment.
The previously hard coded completions like npm or project.json versions have now moved to the JavaScript resp C# extensions.
Each of these extension registers a completion and hover provider for the corresponding JSON files, and uses the new `javac-parser` node-module to parse the JSON in order to evaluate the current location in the JSON file.
Have a look at https://github.com/OmniSharp/omnisharp-vscode/pull/224 to see how this works.
