### ISSUE TITLE
Shortcuts with Italian key layout work randomly

### ISSUE THREAD

**Issue by ehteqx** [Microsoft/vscode#18949]
- VSCode Version: 1.8.1
- OS Version: Ubuntu 14.04 LTS (Dell Custom)
- System language: English US
- Keyboard: Standard Italian

Steps to Reproduce:

1. Set keyboard layout (thorugh Ubuntu) to Italian - this is the standard setup of mine, since keyboard layout is Italian.

2. Go to File -> Preferences -> Keyboard shortcuts, and look for i.e. "Toggle new terminal" (that is Ctrl+` for US layout and Crtl+\ for Italian layout - they are on the same physical key, so I assume this is the rationale).

3. Execute the shortcut and (a) nothing happens or worse (b) something different from expected happens.

4. Set keyboard layout (thorugh Ubuntu) EN-US (it might work, sure, but it takes a bit, making it useless to use shortcuts)

5. The command works, if the Italian-keyboard key combination is pressed.

To my knowledge and limited testing, this is the only way to make some shortcuts work.

**Comment by ehteqx** [comment]
I will add now - after some deeper testing - new information that may help solving (or better, identifying...) the issue. I entered in File -> Preferences -> Keyboard shortcuts, as if I needed to define a new custom shortcut in order to check how VSC rendered characters and keys. This is what I found.

**UBUNTU SET TO ITALIAN LAYOUT**
- Keys pressed: Ctrl+Shift+\ (it IT keyboard, corresponding to Ctrl+Shift+`  in US one)
- Characters shown in the textbox: Ctrl+Shift+\ 
- Characters shown as rectangular key images: Ctrl+Shift+ù (ù is in the same place as \ on US keyboard)

**UBUNTU SET TO US LAYOUT**
- Keys pressed: Ctrl+Shift+\ (it IT keyboard, corresponding to Ctrl+Shift+`  in US one)
- Characters shown in the textbox: Ctrl+Shift+` 
- Characters shown as rectangular key images: Ctrl+Shift+\ (\ is in the same place as ` on US keyboard)

However, changing layout and then rebooting VSC does not trigger any change in the overlay which says "With current keyboard layout: ..." over default keybindings.

To conclude, with keyboard layout set to Italian (if it can help), pressing Ctrl+Shift+ù does nothing, exactly as Ctrl+Shift+\. With layout set to US, it works if following Italian suggestions, that is pressing the key on the keyboard with the Italian symbol as suggested.

To me, it seems that VSC suggests as language-specific shortcuts the shortcuts one had to press if the keyboard for that language is used with US layout. And that way it works just fine (what's difficult that way is the act of writing itself).
If a different layout is selected, something unexpected happens, and I am not able to figure out what.

Thank you (the editor itself is great, though!) and sorry for the long follow-up.

**Comment by alexandrudima** [comment]
Related: #17521

**Comment by ehteqx** [comment]
Thanks for your interest for the issue. I am happy, at least, that the problem is known... And I can confirm that #17521 is the case, because with the same machine and same settings under Windows 10 VSC works perfectly.

Thanks for the support and keep it going, because the editor rocks!

**Comment by alexandrudima** [comment]
I have validated that we now (i.e. after PR #22894 aka #17521 -- in tomorrow's Insiders build) appear to behave correctly for this keyboard layout

![image](https://cloud.githubusercontent.com/assets/5047891/24251418/683e5234-0fda-11e7-8437-f30d7b661134.png)

---
### Analysis of default keybinding for `workbench.action.terminal.toggleTerminal`
* `workbench.action.terminal.toggleTerminal` is bound by default to the key code binding `` ctrl+` ``
* `` ` `` can be produced through two scan code combinations: `` Ctrl+Alt+[Minus] `` and `` Ctrl+Alt+[Backslash] ``. i.e.:
![image](https://cloud.githubusercontent.com/assets/5047891/24251591/ef57dfba-0fda-11e7-94cb-a6e469dfd829.png)
* because `Ctrl` must be used to produce the visual character, the key code binding `` ctrl+` `` is not mappable . i.e. the scan code combo would need to be something like `` Ctrl+ Ctrl+Alt+Minus ``, which we don't support.
* therefore, the action is unbound by default. That is unfortunate, but correct.
* we don't ship with keyboard layout specific default keybindings, that is something you can upvote in #1240

---
### Analysis of pressing `Ctrl+[Backquote]`
![image](https://cloud.githubusercontent.com/assets/5047891/24251917/0f5717b2-0fdc-11e7-86fe-93dd12c2bf61.png)

We now correctly label it:
![image](https://cloud.githubusercontent.com/assets/5047891/24251943/285da212-0fdc-11e7-8f57-23609b26bfbf.png)

---
This makes me believe the fix in PR #22894 aka #17521 resolves this issue.
