### ISSUE TITLE
Console warning about PHP extension confusing snippet variables and snippet placeholders

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#189561]
1. Run Code-OSS
2. Open dev tools
3. See this message
```
[vscode.php]: One or more snippets from the extension 'php' very likely confuse snippet-variables and snippet-placeholders (see https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax for more details)
```

**Comment by roblourens** [comment]
From https://github.com/microsoft/vscode/pull/174889, cc @soulshined do you want to look at this?

**Comment by soulshined** [comment]
@roblourens I'm in the middle of moving otherwise I would. If it can wait until next weekend I don't mind

**Comment by soulshined** [comment]
@roblourens sorry about the late response. I just returned from moving and a wedding and can sort this out tomorrow if you are not already working on it?

**Comment by roblourens** [comment]
Sure, I haven't looked closely, thanks

**Comment by soulshined** [comment]
> From #174889, cc @soulshined do you want to look at this?

After reviewing I can say this is not from our changes. This is prehistoric to us [example](https://github.com/soulshined/vscode/blob/9f8dd87d482aac8456d686168f219ac4302ebbb4/extensions/php/snippets/php.json#L188) and [example2](https://github.com/soulshined/vscode/blob/9f8dd87d482aac8456d686168f219ac4302ebbb4/extensions/php/snippets/php.json#L166). For my changes I just did the same thing for continuity.

Additionally using vscode I can not see these warnings in dev console or any of the output channels. So this may be specific to code-oss, could be wrong though.

Either way, perhaps the solution is to correctly escape the `$` prefixes in all instances where needed

Since I don't use code-oss and can't reproduce in vscode I can't verify if that change sufficiently satisfies the code-oss warning

**Comment by roblourens** [comment]
That's a different pattern, in those the second $ is actually part of a snippet variable. Escaping the $ fixes it
