### ISSUE TITLE
InvalidatedEvent not updating line highlight 

### ISSUE THREAD

**Issue by sanannavyaa** [microsoft/vscode#189691]
When we issue an InvalidatedEvent([‘all’]) after changing the current CUDA thread in our extension, the cursor position in the editor does not update if the new thread PC is different than that of the old thread. Please note that in CUDA because of the large number of threads running concurrently, we have specialized UI to change the active CUDA thread (a.k.a. CUDA focus) rather than through the “Call Stack” view. This specialized UI issues a debugger command to change the CUDA focus, followed by an InvalidateEvent([‘all’]) to update the views.
 
From our logs (attached), we can see that once our InvalidatedEvent is issued, the following threadsRequest and stackTraceRequest retrieve the updated stack information including the PC and source file/line for the top stack frame. However, position of the cursor in editor is not updated to match the new location. We expect that changing CUDA threads would result in the UI synchronizing to the updated state, but we do not see that.  I have attached a video of the bug and some logs to help you better understand this situation.

https://github.com/microsoft/debug-adapter-protocol/assets/84747621/5447fd7a-827c-4a38-a0a4-014ab6f92f4c

[InvalidatedEventBugLogs.pdf](https://github.com/microsoft/debug-adapter-protocol/files/12265228/InvalidatedEventBugLogs.pdf)

**Comment by wsq-7** [comment]
I had a similar problem. During a normal debugging session, when I used events to refresh the variable view, the line highlight disappeared. My expected result is that the base re-requests the data and the current line of code remains highlighted. This happens when I assign the areas property in the event to'all'|'stacks'|'threads'|'variables'. The vscode version I'm using is 1.81.1.

**Comment by roblourens** [comment]
We reset the views correctly but not the focus state of the interface. You can fix it by just clicking in the stack frame and it will highlight the frame in the correct position.

Instead of using `InvalidatedEvent` for this, I think you would have more luck just sending another `StoppedEvent` to reset the whole current stopped position.

I might attempt another fix for this later, but `InvalidatedEvent` is a bit of an oddball and it's not clear what all exactly is supposed to be invalidated. For example there is state that is on the last received `StoppedEvent` that we can't just re-request.

I think that most but not all of the code in https://github.com/microsoft/vscode/blob/f7973f357e7c316a88e8817886f41a843021fe74/src/vs/workbench/contrib/debug/browser/debugSession.ts#L978-L1022 should run when an `InvalidatedEvent` is received. That will update the stacktrace in the model and fix the focus but we should keep the details from the last `StoppedEvent`.

**Comment by roblourens** [comment]
I'd forgotten that I already investigated this in https://github.com/microsoft/vscode/issues/172544 and we have a PR

**Comment by sanannavyaa** [comment]
Based on https://github.com/microsoft/vscode/pull/188490#pullrequestreview-1636378364 I request we reopen this.
