### ISSUE TITLE
[WelcomeUX] Interactive Walkthrough CSS

### ISSUE THREAD

**Issue by seanmcbreen** [microsoft/vscode#18984]
Testing #18091 

This needs updating to match the standard one...

**Copy Release Notes Format**  we should match the CSS of the release notes, there are a number of differences i.e.

- [ ] The font used for headings and content is thicker also slightly different spacing
- [ ] Pre-formatted elements are not highlighted e.g `hello` should be a monospace font in yellow by default.
- [ ] Keyboard shortcuts also should be formatted yellow.
- [ ] Blocks (used for Tips) have a different font and color i.e. blue bar not grey

**Comment by joaomoreno** [comment]
There are still a few slight differences:

- The headings are different. It feels like the Interactive Playground starts with h2 instead of h1. Especially, the first heading is quite different, the release notes has a bigger font and is underlined.
- The font color is definitely different, the interactive playground seems to have a slight more faded color.

![image](https://cloud.githubusercontent.com/assets/22350/22364976/5ef4df4e-e475-11e6-9644-4956d1db5d8e.png)

Moving to February.
