### ISSUE TITLE
✨ Open VSCode & run command in terminal via `code` cli

### ISSUE THREAD

**Issue by jd-solanki** [microsoft/vscode#190142]
Hi 👋🏻 

In most of the cases, when I open VSCode, I would like to run commands like `npm install` or `poetry install` to install project dependencies. For example, When I clone the repo via git, I use `git clone XXX && code XXX` once VSCode is open I had to run `npm install` or `poetry install` in terminal.

We can install the dependencies before opening VSCode but it's common that everyone will start the dev server in VSCode and not in the (temporary) terminal. For example:
```bash
git clone XXX && cd XXX && npm install && echo "oops! I don't want to start server in this terminal"
```

It will be much easier if we can provide cli argument to run the specific command in terminal when vscode is opened via `code` command. Once this is implemented it will easy as below:
```bash
git clone XXX && code XXX -e 'npm install && npm run dev'
```

**Comment by Tyriar** [comment]
I think we can merge this into https://github.com/microsoft/vscode/issues/93241 which is essentially asking for a terminal subcommand. We wouldn't implement terminal control without it being sectioned off like that since there are many things a user may want to do with the terminal like Windows Terminal's CLI:

![image](https://github.com/microsoft/vscode/assets/2193314/904c434e-7e87-426f-bd6f-fd73ef9b8c43)

You might find automatic tasks useful https://code.visualstudio.com/Docs/editor/tasks#_run-behavior

/duplicate
