### ISSUE TITLE
Cannot find module 'jsdom'

### ISSUE THREAD

**Issue by 928PJY** [Microsoft/vscode#19010]
- VSCode Version:1.8.1
- OS Version:win10

Hi, when I writing an extension for vsCode, I got a problem as followed.
![image](https://cloud.githubusercontent.com/assets/17958546/22188664/5a9bc12c-e152-11e6-9e9b-5bcb049816b3.png)
As you can see, When I want to import a package, I got an error "Cannot find module 'jsdom' ". But I had written it in the 'package.json' like this
![image](https://cloud.githubusercontent.com/assets/17958546/22188752/f63c45f2-e152-11e6-8d8f-98de083972fd.png)
and there actually was 'jsdom' folder in node_module
![image](https://cloud.githubusercontent.com/assets/17958546/22188785/3f14b3a4-e153-11e6-8781-dd1c81a8bb80.png)
I appreciate it if you can give me some advice.
BTW, I have tried the method mentioned( extension *typescript-hero*) in this [issue](https://github.com/Microsoft/TypeScript/issues/10346), but it doesn't work for me

**Comment by rozzzly** [comment]
This is because typescript cannot find a type declaration _**`(.d.ts)`**_ file for **`jsdom`**. Sometimes npm packages will come pre-bundled with them, but most of the time you'll need to install them manually. You can read about how to do this: [here](https://blogs.msdn.microsoft.com/typescript/2016/06/15/the-future-of-declaration-files/) and [here](https://medium.com/@Pelle_Jacobs/typescript-declaration-files-of-external-libraries-an-introduction-to-typings-b3d1fbaa07c7#.bt5f04u9j). The first approach is the newer, and preferred method.

It's a simple one command fix:
>```bash
>npm install --save-dev @types/jsdom
>```

This acutaly has nothing to do with **`vscode`**, just typescript itself. In the future please check with StackOverflow first for issues like this. Anyway, I hope that helped! Send me a link to your extension when you've got something running 😉

**Comment by mjbvz** [comment]
@rozzzly is correct. This looks like a TypeScript issue. Closing as upstream.
