### ISSUE TITLE
The replace string should support additional escape char sequences

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#19017]
Today it supports:
* `\t` for a tab character
* `\n` for a line break (depending on the file's EOL settings)

Consider supporting more from the following table:

![image](https://cloud.githubusercontent.com/assets/5047891/22177186/687deb1a-e019-11e6-96b4-4412e5ecca48.png)

**Comment by lazdmx** [comment]
I would like to see '\b' escape char in the list. My use case: I write LaTeX a lot and I write it in Russian, but since LaTeX is overloaded with markup I need to switch input-lang very often, so in order to minimise my switching I define a lot of snippets. But there is a problem with snippets - they are activated only when new word is started, so extra space (from left side or new line)  is required, but there are cases where space must not exist. So in that case support '\b' would help.

For instance if I need to type `январь\,--\,февраль` and I if `\b` is supported, then I simply define a snippet like `йй --> \b\,--\,` and would allow to type `январь`, `<space>`, `йй`, `<enter>`, `февраль` all in Russian without need to come back after `<enter>` to delete extra-space between  `январь` and `\,--\,`

**Comment by chenzhwsysu57** [comment]
> I would like to see '\b' escape char in the list. My use case: I write LaTeX a lot and I write it in Russian, but since LaTeX is overloaded with markup I need to switch input-lang very often, so in order to minimise my switching I define a lot of snippets. But there is a problem with snippets - they are activated only when new word is started, so extra space (from left side or new line) is required, but there are cases where space must not exist. So in that case support '\b' would help.
> 
> For instance if I need to type `январь\,--\,февраль` and I if `\b` is supported, then I simply define a snippet like `йй --> \b\,--\,` and would allow to type `январь`, `<space>`, `йй`, `<enter>`, `февраль` all in Russian without need to come back after `<enter>` to delete extra-space between `январь` and `\,--\,`

hiii, have you solved this problem? I also have this \b problem now, but can't find any more info about this on the Internet.

**Comment by amunger** [comment]
This issue hasn't generated much interest over its long lifetime, closing
