### ISSUE TITLE
Add "editorSide" option for `terminal.integrated.defaultLocation`

### ISSUE THREAD

**Issue by forivall** [microsoft/vscode#190285]
When commands create a new terminal window, I prefer that they create a terminal in my editor area: this feature was added in https://github.com/microsoft/vscode/issues/126249. However, with that option, they will create a new tab in my current editor group, obscuring whatever I was working on. I would prefer them to be placed to the side instead of in the current group, as the action `workbench.action.createTerminalEditorSide` does. My primary use case is with test runner plugins (such as [`Orta.vscode-jest`](https://marketplace.visualstudio.com/items?itemName=Orta.vscode-jest) running tests in debug mode, where they will launch a new terminal tab automatically.

I propose a new option of `terminal.integrated.defaultLocation: "editorSide"`, where new terminals are created to the side.

**Comment by bpasero** [comment]
@Tyriar there is no registry in workbench editor land to force open editors to the side based on a setting. Best you can do today is to set the respective option to open to the side based on a terminal related setting from the commands that open terminals in the editor area.

**Comment by ArturoDent** [comment]
I am confused, the command `workbench.action.createTerminalEditorSide` always opens a terminal to the side (i.e., the next group) for me??  It doesn't for you?

**Comment by Tyriar** [comment]
As @ArturoDent mentioned, I think the right fix for this is to just tweak your keybindings such that ctrl+shift+` runs `workbench.action.createTerminalEditorSide`, instead of new feature work

**Comment by forivall** [comment]
Sorry, I should have mentioned this in my initial comment: This isn't about my keybindings, this is when a different command launches a terminal, such as with the task runner (`workbench.action.tasks.runTask`), or with an extension that runs commands in the terminal, like [Jest Runner](https://marketplace.visualstudio.com/items?itemName=firsttris.vscode-jest-runner)

**Comment by meganrogge** [comment]
Closing as no one else has requested this

**Comment by forivall** [comment]
@meganrogge would you be open to a PR for this (If I submit it, I could re-open or re-create this issue)

**Comment by ELLIOTTCABLE** [comment]
I'd be another user of this prospective setting. As @forivall (also, hi! i recognize you from some of your work!) pointed out, it's not a matter of the keybind - the `terminal.integrated.defaultLocation` setting affects a bunch of various, disconnected workflows; and they all become a lot more flow-breaking when every single one of them ends up "replacing" the code you're currently looking at.

----

My own cents: The problem here is less that this isn't an appropriate tweak to this feature, and more that the feature itself isn't really descriptive. Those of us using `terminal.integrated.defaultLocation` _at all` are effectively trying to get VScode into an alternative mode where it's "terminals, whatever their purpose and wherever they come from, are more integrated into the usual pane-management interface."

Although `terminal.integrated.defaultLocation` does what it says on the tin, I'd argue that it doesn't do what the user _wants_ when they're activating it. Terminal-editor-panes still feel like second-class citizens; they're something of an afterthought.

(Sweeping generalizations and all that, but I suspect the numbers of users who want what-it-says-on-the-tin would be perfectly pleased with adjusting their keybinds to replace some of the terminal-creation-actions to, well, create those terminals in the editor-area.)

Anyway, I both want what OP wants, and also see it as a potential source of bloat - I'm absolutely sure 1. `editorSide` won't be the only one from the variety of first-class pane/editor options that will be desirable when trying to use VScode in a terminals-as-normal-panes-by-default way; and 2. that this setting isn't the last one that will feel "rough around the edges" in that usecase.
