### ISSUE TITLE
VS Code Server crashes on Raspberry Pi

### ISSUE THREAD

**Issue by hex-developer** [microsoft/vscode#190242]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.81.1
- VS Code Server Version: commit 6c3e3db
- OS Version (on machine with client): Windows 10 22H2
- OS Version (on machine with server): Raspberry Pi OS Lite 64-bit

Description of the problem:

I have a Raspberry Pi 4 which I use to run a few Docker containers. I have no issues with it. I use Visual Studio Code on my laptop with the Remote - SSH extension and I connect to my Pi. The extension logs show that VS Code Server is installed to ~/.vscode-server. 

I log in normally and start working on a project for a while. I have installed the Python, the Tailwind CSS IntelliSense and the Vue Language Features (Volar) extensions.

After approximately an hour, I am suddenly disconnected from the Pi. VS Code cannot reconnect, nor can I, over SSH. I cannot access any web service running on my Pi and cannot resolve it's hostname. This has happened every time I connected to the Pi with VS Code. 

I have debugged this issue and while connected to the Pi, I can see many processes for VS Code Server running and taking up many resources. Eventually, the Pi crashes and starts responding after a few minutes if I stop trying to reconnect to it. 

The Pi has passive cooling and is in a well ventilated room. VS Code Server is clearly taking up too many resources. Please look into this issue and tell me if there is any way I can stop VS Code server from crashing the system.

**Comment by hex-developer** [comment]
This is the second time my Pi crashed today. This time I had htop running in another terminal. I am attaching a screenshot.
![image](https://github.com/microsoft/vscode/assets/77530549/d813e193-5cd3-4cd4-8ca3-a548bdfb2c5b)

You can clearly see that VS Code is causing the problem.

**Comment by steveiliop56** [comment]
Hello @hex-developer,

As I can see from your screenshot your pi seems to struggle with ram usage. From the memory tab all 4 gigabytes are full and the swap is full too. So I would recommend increasing the swap to 2 gigabytes or so, but make sure to use an SSD or USB drive if you can because random reads/writes are bad for your SD card. Last but not least if 2 gigabytes swap are not enough make sure to also edit ``/sbin/dphys-swapfile`` so you can increase the limit. Here is a [raspberry pi issue](https://forums.raspberrypi.com/viewtopic.php?t=150141) on how to increase the limit and here is a [tutorial](https://pimylifeup.com/raspberry-pi-swap-file/) on increasing the swap on a raspberry pi.

**Comment by hex-developer** [comment]
Hi @steveiliop56,
Thanks for your reply. I understand that increasing swap space may help my situation. However I am reluctant to do so, since that would result in a poor experience. I could go and buy a device with more memory, but the point of this issue is limiting the resources VS Code Server uses, so more people can use it, even if they own a low-end device, like a Raspberry Pi. I would prefer a solution instead of a workaround.

**Comment by steveiliop56** [comment]
Hey @hex-developer,

As I told you before it's not exactly possible to limit code server bellow arround 200mb of ram that it uses because it may seem lightweight but there are a lot of things going on in the background. So there isn't exactly a possible solution rather than just increasing your swap or getting a device with more ram. Also I want to mention that you may already have noticed that every visual studio program requires a reasonable amount of ram to run, so if you have to run it on a raspberry pi I would recommend just stopping other memory consuming apps like docker containers. Personally I haven't ever noticed any problem with my raspberry pi 4 with 4gb of ram crashing* although I run around 7-8 docker containers.

*notice here that I have had a lot of situations that I left vs code open on my computer for an extended period of time without doing anything and it lost connection without being able to reconnect through the retry button and having me to close and reopen vs code.

**Comment by hex-developer** [comment]
I added more swap, and so far, I haven't had any problems. I am closing this issue since I haven't received any response, and I no longer have a problem. However, it should be noted that currently, VS Code Server is not something that can be run on low-end devices without issues. I believe Microsoft should look into this problem instead of having users switch IDEs or look for workarounds.
