### ISSUE TITLE
diff giving more priority to blank lines

### ISSUE THREAD

**Issue by goyalyashpal** [microsoft/vscode#190384]
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.81.1 (user setup)
Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
Date: 2023-08-09T22:22:42.175Z
OS: Windows_NT x64 10.0.19045

Steps to Reproduce:

1. Open two new/blank editors
2. Compare both the editors 
(Open Editors `ctrl-k e` > select both `shift-up/down` > right click > compare selected)
3. Paste this on one side, and that on the other (mind the empty lines)
4. Now, on "that" side: try to make it match the left side by say:
    * removing one empty line from starting, or 
    * putting `# ` before `async`

<details><summary>this and that</summary>

this: 

```

# async def handle(request):
#     keyvals = request.match_info
#     return web.Response(text=keyvals)


async def fetch_name(request):
    pass


async def insert_name(request):
    pass
```

that:

```


async def handle(request):
    keyvals = request.match_info
    return web.Response(text=keyvals)
```

</details>

wrong diff result:

<img src="https://github.com/microsoft/vscode/assets/19423063/70add44f-989a-457d-81c8-474b003cceef" width=550px/>

after the step 4 given above - i.e. on increasing similarity; it detects common part correctly:

<img src="https://github.com/microsoft/vscode/assets/19423063/43a515dc-8e31-4d70-b2bc-020c827dd052" width=550px/>

https://github.com/microsoft/vscode/assets/19423063/6cccdcac-64b3-4bcd-a38b-281c91c621a9

**Comment by hediet** [comment]
[Fixed in latest diff algorithm improvements.](https://microsoft.github.io/monaco-editor/playground.html?source=v0.42.0-dev-20230809#XQAAAAJ-AwAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscw4VlRu_1uhrp2RzO_KSoj3BnqSCFzt4AfU0xJ0CGYU1vRtgnKPmZzQcQ1HJnaCu5f-1dobOlrSyV9lhyCGfRXqdSbMn6zMfUGoD97I56mYgm6DEcO5piRQZee1EWzFN_pKlNxOnmRMDkyNRU2vYBbwyvWgPWj9ZX9pO2n4w66RBJXibhfpEF-lGaLQgkTe1zpngOS9Yc0uqAbLphdoYhoAbzLMq0k_QQB9FsNY6LwaI28UNcW4kpBt48v5cJJLBw8yTGn-WuurHw9z-BZTQ1daDgIEa59x41GMWQddPUb9BlUq6wX0z7w83Zs9DqiyCklHerq1OZg68OpSC5DLNt11oCnSXWYgG6LdrNo0AWOCRKkRbKfch9fMxYrJhEyPy1fB72fl2kgfLdm8QvffQFHRFC38YSec446qt5oWSIjWQUSpo4J3gS6JYYZ4UreG7zcwryegwoRIZFs1gZBYHebKcu_5fBJIc8ChIH3pq4YXBCPHoWxhaD1fkR2urU4WrNyiqf_6dD5uA)

**Comment by goyalyashpal** [comment]
i had the experimental diff algo enabled, and the latest _stable_ vs code installed - so, those diff algo improvements are not release yet. right?

following is from my settings.json:

```json
{
    // Diff Editor
    "diffEditor.diffAlgorithm": "advanced",
    "diffEditor.experimental.useVersion2": true,
    "diffEditor.experimental.showMoves": true,
    "diffEditor.maxComputationTime": 10000,
    
}
```

**Comment by hediet** [comment]
Try the latest vscode insiders!
