### ISSUE TITLE
vscode ipynb cannot plot corrected compared to jupyterlab

### ISSUE THREAD

**Issue by ck0099** [microsoft/vscode#190343]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

[error_ipynb_not_plot.ipynb.zip](https://github.com/microsoft/vscode/files/12328980/error_ipynb_not_plot.ipynb.zip)

The following python pip packages are needed:
backtesting
jupyterlab

1. Run the following ipynb in vscode and jupyterLab respectively.
2. In vscode, the plot will not get generated inside vscode ipynb notebook, but instead got plotted out onto a browser. This is because it cannot detect vscode's notebook.

<img width="1375" alt="Screen Shot 2023-08-13 at 3 30 59 PM" src="https://github.com/microsoft/vscode/assets/132270603/7eb9e764-7172-4432-81d4-06a6a10c2cfb">

3. In jupyterLab, the plot will be generated just underneath the cell that executed the code, which is what it suppose to do.

<img width="1216" alt="Screen Shot 2023-08-13 at 3 31 10 PM" src="https://github.com/microsoft/vscode/assets/132270603/b1ad931b-861b-415f-a232-dd9216adda71">

**Comment by ck0099** [comment]
From the discussion of this issue from backtesting.py's repository, it seems this is vscode issue:

https://github.com/kernc/backtesting.py/issues/1043

**Comment by DonJayamanne** [comment]
This seems to be an issue with backtesting package and bokeh
Backtesting package makes assumptions about some environment variables, and latest bokeh doesn't seem to work correctly.
If you install `bokeh==2.4.0` and add necessary env variables and setup some settings, then it works as expected,
I.e. this isn't an issue caused by VS COde.

Here's a working copy

![Screenshot 2024-03-21 at 09 37 20](https://github.com/microsoft/vscode/assets/1948812/0ab6e43f-55e6-4eab-bf9c-8ae0d7417d40)
