### ISSUE TITLE
[WelcomeUX] workbench.welcome.enabled default value should be false, not null

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#19035]
The current way when this is choosen null gets auto filled 

![screen shot 2017-01-23 at 16 15 10](https://cloud.githubusercontent.com/assets/1926584/22209551/297d7376-e187-11e6-9695-1b33f0ace64f.png)

**Comment by chrmarti** [comment]
Ideally I would like to not have the setting and any of the Welcome commands if the Welcome experiment is disabled. If the experiment is enabled the default should be `true`. In the absence of being able to do that (because I need the storageService to look up the experiment), having a default of `true` would be even more confusing, because it would still be disabled if the experiment was disabled. Not sure if there is a better way out.

**Comment by isidorn** [comment]
IMHO just put 'false' here https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/welcomePage/electron-browser/welcomePage.contribution.ts#L23

That is how all our settings behave

**Comment by chrmarti** [comment]
The default should be `true` if the experiment is on.
