### ISSUE TITLE
Test light bulb everywhere

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#19046]
- [x] @dbaeumer
- [x] @bpasero  

re #16911 

Test that we now also ask for code actions on just words. Previously we would ask for code actions only on errors and warnings. Make sure that

* we only ask once per word
* we only ask once per squiggle and that squiggles that precedence

**Comment by egamma** [comment]
Reassign @dbaeumer he asked for the change and I'm not sure the change implements @dbaeumer's wish.

**Comment by bpasero** [comment]
I verified by installing TS 2.2 and having multiple unused variables in one line. I did not see a combined list of warnings for the line, but individual entries when I navigated around the line (clicking on the warning).

**Comment by jrieken** [comment]
> having multiple unused variables in one line

@bpasero Did you get a warning for those?

**Comment by dbaeumer** [comment]
@jrieken I was hoping for something like this (using TS 2.2):

```ts
class A {

}

class B extends A {
	constructor() {
		super();
		let a;
	}
}
```

Have the cursor anywhere on line 8. I would expect the light bulb to show up. The reason is that not all errors will have fixes and now I have to directly navigate to the error to see whether it is fixable or not. Would be nice if it is enough to simply have the cursor on the line. Pressing Ctrl+. would open the quick fix menu. If there are more fixable errors on that line taking the first one would work for me.

**Comment by bpasero** [comment]
> Did you get a warning for those?

Yes

**Comment by bpasero** [comment]
I verified that `provideCodeActions` is called when I navigate into a word only once. It is called multiple times while I type a word, but I guess that is expected. 

I think I also verified @dbaeumer scenario using TS 2.2 with no-unused-locals warning:

![untitled](https://cloud.githubusercontent.com/assets/900690/22293651/b84bab1a-e310-11e6-91fd-aeddcde934b6.gif)

**Comment by dbaeumer** [comment]
@bpasero I tested it with 2.2 from nightly and a light bulb is not shown if the cursor is not on the token with the error.

**Comment by bpasero** [comment]
Yes, same here.
