### ISSUE TITLE
Theme color `icon.foreground` is inconsistent and does not work with `.svg` icons everywhere

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#190679]
To reproduce:
- install GitLens
- set 
```
	"workbench.colorCustomizations": {
		"icon.foreground": "#ff0000"
	},
```
- open an editor
![image](https://github.com/microsoft/vscode/assets/6461412/bf02656c-2af1-466a-848c-2cd32e1d3a30)

_Originally posted by @aeschli in https://github.com/microsoft/vscode/issues/189201#issuecomment-1682438191_

**Comment by bpasero** [comment]
Sorry for sending back, but there are many things to report here and I feel that doing a one-off fix in editor toolbar is wrong and just a band aid.

**Inconsistencies**
It looks like `icon.foreground` is not applied consistently everywhere. Notice how the view toolbars do not change, while the editor toolbar does change (these 2 are essentially the same part toolbars):

<img width="1008" alt="Screenshot 2023-08-22 at 11 10 35" src="https://github.com/microsoft/vscode/assets/900690/ce313b4f-9dd0-41b1-8061-16a4c175e526">

I think the underlying reason is this CSS rule:

https://github.com/microsoft/vscode/blob/8caa1c80f5ff68a6a6b78d36057d2a6ec21362b1/src/vs/workbench/browser/media/part.css#L85-L87

**Missing Adoptions**

The editor header really just uses a standard `WorkbenchToolbar` and imho should not be responsible for making this color work for entries, rather the component should do that:

https://github.com/microsoft/vscode/blob/8caa1c80f5ff68a6a6b78d36057d2a6ec21362b1/src/vs/workbench/browser/parts/editor/titleControl.ts#L192

You can see that the same issue applies to other toolbars, such as the view toolbars, which is not surprising.

**Code Duplication**

There seems to be code involved to make the color work for SVG icons, but that code is heavily duplicated and should be reused:

https://github.com/microsoft/vscode/blob/8caa1c80f5ff68a6a6b78d36057d2a6ec21362b1/src/vs/workbench/browser/parts/views/viewPane.ts#L362-L374

https://github.com/microsoft/vscode/blob/8caa1c80f5ff68a6a6b78d36057d2a6ec21362b1/src/vs/workbench/browser/parts/panel/panelPart.ts#L347-L365

https://github.com/microsoft/vscode/blob/8caa1c80f5ff68a6a6b78d36057d2a6ec21362b1/src/vs/workbench/browser/parts/activitybar/activitybarPart.ts#L645-L663

**Comment by aeschli** [comment]
@bpasero I don't think assigning this issue to me and David is useful. I'm not familiar with toolbars.

**Comment by daviddossett** [comment]
I hear about this issue quite often from extension authors. They want to either add the CSS vars to the SVG code itself and have it respond to themes, or just have us do it automatically.

**Comment by bpasero** [comment]
@aeschli its unlikely a thing to fix in toolbars but more a thing to fix where we allow `.svg` icons from extensions to enter our world, because in the end we only use Codicons and nothing else.

I believe this is happening from where menus are being created based on `MenuId`:

https://github.com/microsoft/vscode/blob/41cb0fc5647a171b40a89c1e1ceb5e65913132ec/src/vs/platform/actions/browser/menuEntryActionViewItem.ts#L260-L266

Which I think is the place to add the mask, but @jrieken might know better.

**Comment by jrieken** [comment]
I can help to get this working with the MenuEntryActionItem things. Those are created for contributed commands/menus and we do support SVG via this path.

**Comment by jrieken** [comment]
@aeschli thanks for the mask trick

<img width="1139" alt="Screenshot 2023-08-31 at 12 10 56" src="https://github.com/microsoft/vscode/assets/1794099/f0061f76-0141-47ef-9c08-5baf7bb7c45a">

**Comment by pflannery** [comment]
@jrieken 

I just updated to 1.83.0 and found this update has broken the ability for versionlens to show if its enabled or disabled via its icon.

With previous versions of vscode it showed as enabled
![image](https://github.com/microsoft/vscode/assets/1727302/8e95525b-9b1d-4aac-906d-08f60b950d05)

in 1.83.0 when the icon is enabled it is now masked
![image](https://github.com/microsoft/vscode/assets/1727302/02d840a5-a077-4c89-ba7b-c4d7a34287ce)


I understand that theming icons is preferable but how can we specify enabled\disable state with theme styles? 

For instance the icon for showing diff whitespaces has the ability to be enabled or disabled
![image](https://github.com/microsoft/vscode/assets/1727302/ceac922a-3005-4be9-bc04-b59188ac3e4c)

How do we implement the same behaviour for extensions?
