### ISSUE TITLE
Native crash in integration tests (macOS)

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#190725]
Build: https://dev.azure.com/monacotools/Monaco/_build/results?buildId=228104&view=results

Dump: 

[36f2ea25-b74e-4dd8-b003-ccb7b3da98b7.dmp.zip](https://github.com/microsoft/vscode/files/12376731/36f2ea25-b74e-4dd8-b003-ccb7b3da98b7.dmp.zip)

**Comment by deepak1556** [comment]
Seems to be a crash when the `TracingController` attempts to use the main thread task runner, this is unlikely since the controller lives for the lifetime of the `node::Platform` which does not get destroyed until `ElectronBrowserMainParts` goes out of scope.

I think this is a one time crash and not actionable, will keep it open for a while and decide on a path forward.

**Comment by bpasero** [comment]
Maybe again: https://github.com/microsoft/vscode/issues/190854

**Comment by deepak1556** [comment]
Another report https://github.com/microsoft/vscode/issues/191298

**Comment by bpasero** [comment]
I think another one right after: https://dev.azure.com/monacotools/Monaco/_build/results?buildId=229103&view=results

**Comment by rzhao271** [comment]
Does this crash still occur on the current Insiders builds?

**Comment by rzhao271** [comment]
Closing optimistically.
