### ISSUE TITLE
Retain last typed query in command palette

### ISSUE THREAD

**Issue by goyalyashpal** [microsoft/vscode#190840]
Currently:
* When exploring any particular keyword related commands by executing them, then for next exploration (after execution) same keyword has to be typed again & again.

* this behaviour feels very jarring as users are too habitual to seeing autocompletion dialogs & using enteries from that to the input field

* this need of exploring rises very often for beginners to learn different capabilities of the editor (say, `case`, or `emmet: `, or `select`, etc) & to non-beginners alike when trying out a new extension (so, `<extension>: `)

the proposal is:
* to add  a "last typed query" at the top if command palette history 
* so, the "last executed command" will become 2nd entry now; therefore, have the last command entry (first or second whichever number it is at) highlighted by default on opening cmd palette (behaviour similar to `ctrl-r` - recent workspace dialog)
* going to that last typed query and pressing will fill it in the command palette's prompt

**Comment by TylerLeonhardt** [comment]
We can't add it as an item in the list because that would break existing muscle memory where users _expect_ that the top item is the last item they ran.

However, we do already have a setting for this:
<img width="768" alt="image" src="https://github.com/microsoft/vscode/assets/2644648/438a012c-f1eb-4841-8c97-d2628e646fb5">
```
"workbench.commandPalette.preserveInput": true
```

which will preserve what you had in the input after you run a command:
<img width="660" alt="image" src="https://github.com/microsoft/vscode/assets/2644648/e822c67d-dd7c-4d14-b839-b0eddabd87a1">

**Comment by goyalyashpal** [comment]
> ```
> "workbench.commandPalette.preserveInput": true
> ```
> 
> which will preserve what you had in the input after you run a command:

yes, thanks a lotttt 😃 . it worked flawlessly.

trying different "cases" or "todo md: " or "markdown timer: " is sooo easy now. it was super annoying before.

and thanks to the input being all pre-selected, the different states related to input are easily reachable too in single keypress (erase all, unselect all)


thanks a lot again.
