### ISSUE TITLE
Align on save breaks up the < div> tags

### ISSUE THREAD

**Issue by dnecklesportfolio** [Microsoft/vscode#19095]
- VSCode Version: 1.8.1 (1.8.1)
- OS Version: Sierra 10.12.1 OS X

Steps to Reproduce:

1. I type:

```
import React from 'react';
import ReactDOM from 'react-dom';

var HelloWorld = React.createClass({
    render: function() {
        return ( 
            <div>
            HelloWorld!
            </div>
        );
    }
});
```
2. When I save it 
formats to this 
![image](https://cloud.githubusercontent.com/assets/2013689/22224596/2c37db1e-e18d-11e6-9a3c-6ecf78f5b2e1.png)

No matter which align plugin i have from the two in the picture, it does that..
![image](https://cloud.githubusercontent.com/assets/2013689/22224691/82c3e34c-e18d-11e6-8fa8-9d02cf91154c.png)

Let me know if you need more information.

**Comment by mousetraps** [comment]
@dnecklesportfolio that's no fun! Unfortunately I can't seem to reproduce with the steps you provided. In order to help narrow down the issue here, would you mind trying the following?
1. run VS Code using `code --disable-extensions` - does the issue still occur? (Also ensure you're running w/ this option for the next couple steps)
2. does it matter where the cursor position is when you save?
3. Do you have any custom formatting settings specified? (e.g. editor.tabsize, javascript.format.insertSpaceBeforeAndAfterBinaryOperators, etc.) And if so, could you post them here?

**Comment by dnecklesportfolio** [comment]
Hi @mousetraps,

1. No the issue doesnt happen anymore
2. It didnt matter i tried it before between and have the div tag
3. Here are those settings
```
// Place your settings in this file to overwrite the default settings
{
    "sync.gist": "",
    "sync.lastUpload": null,
    "sync.autoDownload": false,
    "sync.autoUpload": false,
    "sync.lastDownload": null,
    "sync.version": 242,
    "sync.showSummary": true,
    "sync.forceDownload": false,
    "sync.workspaceSync": false,
    "sync.anonymousGist": false,
    "vsicons.projectDetection.autoReload": true,
    "files.autoSave": "onFocusChange",
    "editor.tabSize": 2
}```
4. Yeah it didnt do the funky aligning anymore...
 
Should I remove all extensions and see which one caused it?

Thanks,

**Comment by mousetraps** [comment]
Awesome, we're getting somewhere! Yep, if it worked fine with extensions disabled, I'd recommend sifting through to see what the culprit is. Would be awesome if you could also update this thread with your findings in case anyone else runs into it, an also file a bug on the extension author so they know to fix it.

**Comment by mousetraps** [comment]
Also, you don't need to uninstall all extensions - you can actually try disabling extensions one at a time instead. 
![image](https://cloud.githubusercontent.com/assets/762848/22227121/803c5c1c-e17e-11e6-98be-578b196e0323.png)

**Comment by dnecklesportfolio** [comment]
It was the JS-CSS-HTML-Formatter that did it, and they have [been having similiar issues before](https://github.com/Lonefy/vscode-JS-CSS-HTML-formatter/issues/26)
![image](https://cloud.githubusercontent.com/assets/2013689/22228182/7f464998-e19d-11e6-8c27-f4ac1d0d2cbf.png)

Last question
Which align plugin do you use? 
Does it make sense to have more than one?

Any thank you for your time!

**Comment by mousetraps** [comment]
Sweet! Glad everything's working out!

As to your question - personally, I'm not the best person to ask because I don't actually use any of the align plugins because I'm happy enough with VS Code's built-in formatting options.

Definitely doesn't make sense to have more than one - seems like added complexity with no added value.

Anyways, that's my 2c - happy coding! 😃
