### ISSUE TITLE
Go to Implementation

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#19099]
In IDEs (e.g. Eclipse, Intellij) Go to Implementation is used to refer to a navigation from an interface to an implementation or an abstract method to implementating methods.

Therefore the command should be renamed to 'Go to Defining Type'.

// CC @kieferrm

**Comment by mjbvz** [comment]
The TS `go to implementation` command does this. I think the problem is that our API name is confusing.  

In #18346, I originally called the api `ImplementationProvider` which we then decided to rename `TypeDefinitionProvider`. At the time, I didn't realize that `type definition` was actually its own concept. 

I think we should instead just switch the name `TypeDefinitionProvider` to `TypeImplementationProvider`

**Comment by mjbvz** [comment]
@egamma Just to make sure I fixed the right thing, were you seeing unexpected behavior with the current `go to implementation` command, or was the original API name the source of confusion?

**Comment by kieferrm** [comment]
@egamma `Go To Implementation` is supposed to exactly do what you are describing the other tools do.  That's why we're asking for the case in which it potentially didn't work for you.

**Comment by egamma** [comment]
@mjbvz @kieferrm all is good and I've verified that it behaves as expected, sorry for the noise.
