### ISSUE TITLE
vscode.dev loading as blank page on iPad

### ISSUE THREAD

**Issue by MitchHamill** [microsoft/vscode#190930]
- VS Code Version: 
- iPad OS Version: 16.2

When opening vscode.dev in any browser on iPad I am getting a blank screen, inspecting the browser there are two logs for `script error`

![D414C8AA-144E-4571-9A50-94E7D91650AE](https://github.com/microsoft/vscode/assets/57971013/bd59d964-9033-4dd8-a17c-b9266cc9bfa6)

**Comment by joaomoreno** [comment]
I can't repro this on my iPad, running OS 16.6. Can you get any more details of those errors?

**Comment by MitchHamill** [comment]
Hmm yeah must have been a 16.5 issue - I updated and it's working fine now

**Comment by robertandrews** [comment]
Same for me, and at least one other - https://reddit.com/r/vscode/s/cy2ozq09Fr

I last used vscode.dev successful on iPad a couple of months ago. Now that I have tried it again, in iPadOS Safari (or iPadOS Chrome) it only loads a grey blank page. Same in Private mode and with Content Blockers turned off.

Brave browser on Mac in same location loads fine.

I have **not** modified the iPad (ie. Updated iPadOS) since I last successfully accessed vscode.dev on the iPad Pro a couple of months ago. It is running 15.6.1 (a different vrsion to @joaomoreno), and I don’t really want to have to update it. This seems to point to the code base, not the client?

**Comment by robertandrews** [comment]
The problem also affects github.dev, which stops at “Setting up your web editor”

**Comment by SkyfallWasTaken** [comment]
Any way to get vscode.dev working on 16.2? Would prefer to stay on this version (waiting for a jailbreak) - that said, I can still update to 17 if it's necessary./

**Comment by robertandrews** [comment]
> Any way to get vscode.dev working on 16.2? Would prefer to stay on this version (waiting for a jailbreak) - that said, I can still update to 17 if it's necessary.

@joaomoreno Could we get some clarity on whether the change that has caused this can be rolled back?

**Comment by einbequemesbrot** [comment]
I’m on the most recent iOS version (17.0.3) and vscode.dev does only load as a blank black site. 
A few days ago (while still on the beta of 17.0) I did not have any issues using vscode.dev
