### ISSUE TITLE
Provide an option not to automatically configure apt, when installing the deb package

### ISSUE THREAD

**Issue by rgl** [microsoft/vscode#190960]
The [debian package postinst script](https://github.com/microsoft/vscode/blob/1.18.1/resources/linux/debian/postinst.template) should not (unconditionally) install/configure the apt repository. That goes against the expectation that we, the administrators, are in control of all the repository sources. Also, having a .deb setup the repository source, is a really weird pattern, as one will have a new package source that we have no idea what created it (e.g. dpkg -S does not return that file).

So please, drop that part of the code, and do not install `/etc/apt/sources.list.d/vscode.list`.

- VS Code Version: 1.81.1
- OS Version: Ubuntu 22.04

**Comment by rgl** [comment]
The current behavior goes against the expectations of any user. The typical user knows the difference between an apt repository and a package.

This package is currently conflating a package file with the setup of its/an apt repository, which might not even be the same (e.g. when using a package cache hosted somewhere else).

At least, this package should be modified to have a dconf setting to prevent it from automatically configure APT. That way, it can still support the current behavior.

**Comment by joaomoreno** [comment]
> At least, this package should be modified to have a dconf setting to prevent it from automatically configure APT. That way, it can still support the current behavior.

That we can do.

**Comment by rzhao271** [comment]
Now that you mention it, I do find it off.
I'm used to installing .deb files using `dpkg -i` and pulling from repositories using `apt install`.
I don't expect a package manually installed with `dpkg -i` to then show up after running `apt-get upgrade`. Let me know if you've seen other packages set up something like that before.

I second making it a feature rather than deleting it, though, because of https://github.com/microsoft/vscode/issues/141788.

**Comment by rzhao271** [comment]
@rgl I'm wondering if there's a standard dconf key name that we can reference?

Also feel free to send up a PR if you've a specific implementation in mind.

**Comment by rgl** [comment]
@rzhao271 I have no particular preference for the name. could be something like:

```bash
debconf-set-selections <<'EOF'
vscode vscode/skip_package_repository_configuration boolean true
EOF
```

**Comment by jme52** [comment]
I agree with the OP, manipulation of repositories should not happen in the same package that installs software from that repository, and the fact that it is done on-the-fly via a script is a problem because then the created files are not known to the tools used for package management (`dpkg`, `apt-file`, etc.).

Note that issue https://github.com/microsoft/vscode/issues/215744 is also triggered by this.

**Comment by rzhao271** [comment]
Duplicate https://github.com/microsoft/vscode/issues/22145
