### ISSUE TITLE
Provide way to specify the server version with 'code tunnel'

### ISSUE THREAD

**Issue by JtMotoX** [microsoft/vscode#191047]
Currently there is no way to downgrade to a previous version of Visual Studio Code Server.  It always uses the latest version, regardless of the version that is locally installed (full or cli).  Please provide a way for us to specify the server version and/or commit.

I ask this because there is a recent Visual Studio Code version (1.81.1) which has a major bug that prevents me from using VSC Server and I have had to resort to direct ssh connections.  I would like to downgrade to 1.80 until the bug is resolved but there does not seem to be any way to do this.

**Comment by connor4312** [comment]
This is not in the scope of `code tunnel`. The tunnel _must_ always use the VS Code server version that the client connects with, otherwise communication between the remote and local instances will probably not work. To use a different version of VS Code on the remote, connect with a different version of VS Code on the client.

**Comment by JtMotoX** [comment]
@connor4312, my client does not have VS Code installed.  The client is using the web tunnel.  Is there any way to have the client web use a specific version?

**Comment by connor4312** [comment]
Not presently. If whatever bug you're hitting is fixed on Insiders, though, you can access insiders.vscode.dev
