### ISSUE TITLE
Inline chat is not in `IChatWidgetService`

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#191191]
There is a `IChatWidgetService` to access the active chat widget, but the inline chat does not seem to be part of this. For actions wanting to contribute to all chat input fields (such as voice-to-text), it would be nice if all chat input widgets would be the same and available from the widget service.

//cc @jrieken

**Comment by roblourens** [comment]
2 of them are really the same thing though. Since it gives access to the chat session data model that is definitely specific to how panel chat works, I think that the inline chat should have its own service for this kind of thing. Or it's just going to be a mostly independent set of types in IChatWidgetService that cover inline chat
