### ISSUE TITLE
don't show the terminal quickfix on `ctrl+c`

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#191226]
the user's intention with `ctrl+c` is clear, so IMO, we shouldn't show the lightbulb

![Image](https://github.com/microsoft/vscode/assets/29464607/b23e5a73-1071-4fb1-a007-c6f2edd576d2)

**Comment by Tyriar** [comment]
Not sure if it's possible to do this in the current API, it'll be a sparkle soon so it'll be less prominent. I guess the sparkle shouldn't do the audio cue as well.

**Comment by Tyriar** [comment]
We can't fix this currently because interrupted commands still have a command and an exit code set, so it's a failed command and it's working as design where copilot suggests a fix. It is more muted now:

![image](https://github.com/microsoft/vscode/assets/2193314/da6618a3-80b4-45d4-b050-230e3f6b5d24)
