### ISSUE TITLE
"window.openFilesInNewWindow" why default and off

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#19123]
Refs: https://github.com/Microsoft/vscode/issues/18609

The document says for default and off that it will open in the last active window. Why do we have two settings then.

**Comment by bpasero** [comment]
@dbaeumer this is a bit unhappy but on macOS there is a difference:

![image](https://cloud.githubusercontent.com/assets/900690/22249480/67fefd92-e243-11e6-9443-caea730afee1.png)

Since people might have an interest to share settings across OS I would want to stay away from introducing OS specific differences here.

**Comment by dbaeumer** [comment]
@bpasero makes sense, but then please add it to the description of `default`. Currently they are the same which doesn't help.

**Comment by dbaeumer** [comment]
I mean the description that is shown when you hover over `"window.openFilesInNewWindow"` in a settings file

**Comment by bpasero** [comment]
@dbaeumer yeah I can tweak the description. It is now on all OS:

`default: files will open in the last active window unless opened via the dock or from finder (macOS only)`
