### ISSUE TITLE
format broken

### ISSUE THREAD

**Issue by kgtkr** [Microsoft/vscode#19128]
My computer was frozen and I forced to quit.
Then TypeScript format no longer works well.
What should I do

**Comment by mousetraps** [comment]
Hey @kgtkr, sounds frustrating, sorry to hear that you're running into issues. We'll need a few more details to help narrow the issue down:
1. When you say "typescript format", do you mean "code formatting" for typescript, or something else?
2. Could you give a specific, reproducible, example of something that's not working? What do you expect it to do instead?
3. Does the issue occur with only typescript files, or other file-types too?

Thanks in advance!

**Comment by kgtkr** [comment]
1.yes,
2.
0bytes file
↓
    Error: Source sample is missing.

```
class Hoge<T>{
    t:T
}
```
↓
```
class Hoge < T > {
    t : T
}
```

normal→<T>
now→< T >

3.I only used typescript, so I do not know

Sorry I'm not good in English.

**Comment by mousetraps** [comment]
@kgtkr thanks for the additional info! Unfortunately I can't reproduce the issue. 
```ts
class Hoge<T>{
    t:T
}
```

gets formatted to:
```ts
class Hoge<T>{
    t: T
}
``` 

A couple followup questions:
1. What version of VS Code are you running? (you can get this information from `Help > About`). If you're not on the latest version
2. I suspect this issue might be caused by an extension - could you try launching vscode with `code --disable-extensions` and check whether the issue still occurs?

**Comment by kgtkr** [comment]
Sorry.
I remove and install yesterday.
"Program Files" and "${userName}\AppData/code" and "${userName}\vscode"
solved

**Comment by mousetraps** [comment]
Nice, I'm happy to hear it's working for you now!
