### ISSUE TITLE
Ranges / Selections Are Difficult To Inspect When Debugging VS Code Extension

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#191390]
Renaming private fields to one character names and properties that are not evaluated automatically make it very difficult to inspect some values, in particular ranges and selections:

![Image](https://github.com/microsoft/vscode/assets/2931520/6202a915-ef66-4ac5-a692-e87275b75aec)

I suggest to add more toString implementations, so that the hover becomes more useful.

Also, I wonder why we cannot evaluate getters automatically? I think cdp has an option to run code without side effects.

**Comment by connor4312** [comment]
You can evaluate gettings automatically with the setting `"debug.autoExpandLazyVariables": true`.

If there's a custom toString, the debugger would use them. That's Joh's area though 🙂

**Comment by jrieken** [comment]
> Renaming private fields to one character names and properties that are not evaluated automatically make

I'd say this is less about field name mangling than minification in general, all debugging is affected by this, e.g when stepping into the EH code or when inspecting call stacks. 


Unsure how I feel about `toString` because folks might take that as API and depend on its inner workings which means more maintenance for us

**Comment by connor4312** [comment]
You can also use the debug.description symbol, but that carries similar risks

```
class Foo {
  [Symbol.for("debug.description")]() {
    return 'description';
  }
}
```
