### ISSUE TITLE
Extension keybindings that are deleted don't get reinstalled

### ISSUE THREAD

**Issue by ImDino** [microsoft/vscode#191389]
- VS Code Version: 1.81.1 (Universal)
- OS Version: macOS Big Sur 11.7.4

I installed WindowsKeybindings by fredhappyface and tried removing some of its keybindings to figure out an issue I had with a third party app. Once I figured it out and wanted to start over I reinstalled the extension but it wouldn't re-apply the keybindings I had removed previously. I tried uninstalling, rebooting vscode, and _then_ installing but it didn't help. 

Steps to Reproduce:

1. Install WindowsKeybindings by fredhappyface.
2. Show extension keyboard shortcuts.
3. Remove one of the keybindings.
4. Uninstall and re-install the extension.
5. Show extension keyboard shortcuts again.
6. Notice that the one you removed before isn't there.

Edit:

I got the answer in a [reddit post](https://www.reddit.com/r/webdev/comments/1624f2z/comment/jxvbs6g/?utm_source=share&utm_medium=web2x&context=3), just wish It wouldn't be so hard to find, should be easier to figure out in the UI itself, so I'm leaving this issue open.

_Open command palette, go to "Open Keyboard Shortcuts (JSON)" , and either look for "command": "-....." or the extension name you care about. Any command starting with - was unmapped from the key._

**Comment by ulugbekna** [comment]
This is because modifications you make to any keybinding are stored in `keybindings.json` (invoked by command "Preferences: Open Keyboard Shortcuts (JSON)". 

When uninstalling an extension, we do not clean modifications to your keybindings -- hence, your keybinding changes were preserved even when you installed the extension 2nd time. While this behavior may be annoying, imagine how annoying it would be to lose all your shortcut modifications if you uninstall the extension accidentally. 

It's easier to clean up the modifications yourself than lose them accidentally.
