### ISSUE TITLE
Test: `focusedView` window title variable

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#191341]
Refs #97790

- [x] Windows @lszomoru 
- [x] macOS @joaomoreno  
- [x] Linux @roblourens 

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23191341%0A%0A&assignees=meganrogge)

---

Add `${focusedView}` to `window.title` and click around the workbench. Verify that it displays the expected view title.

Note that the editor is not a view, so you won't see anything when focus is on one of those.

**Comment by roblourens** [comment]
This works great. Just had a couple thoughts and wondering whether you had considered this

- Instead of separate variables for current view (which is blank when not focused) and current editor (which is still set when not focused) how about one variable which is just the name of the currently focused "thing" and will show the editor or view? This also avoids the problem of having a variable in my `window.title` which is blank and means that I can't use separator characters to demarcate it without having them dangling when the variable is empty. Also it's extendable to other types of focus targets besides editors and views, if that's ever needed
- I wonder if you want to expose the view container name too somehow. eg `Explorer` instead of `Folders`
  - Also on this point, when focus is technically not inside the view, the variable is empty. Examples are the search bar in Extensions, and all view container toolbars and search bars
  - This idea might contradict my first point, like someone might want separate view and view container variables

**Comment by meganrogge** [comment]
@roblourens I did think about those points but given that the views service is owned by @sandeep-sen, just wanted to implement what was requested and wait for feedback.

I also figured that a user might want to know simultaneously which view is focused and which editor is active.

> This also avoids the problem of having a variable in my window.title which is blank and means that I can't use separator characters to demarcate it without having them dangling when the variable is empty. 

One can put this variable at the start or end of the window.title to avoid this.

**Comment by roblourens** [comment]
Sure, but if it's shipped to stable then you decide you want to change the behavior, you may not be able to un-ship it without breaking people's window title.

> One can put this variable at the start or end of the window.title to avoid this.

The point is that then it is next to some other text, so I want to add a `-` or something to separate it from the next thing, then my title starts with a `-` when that variable is empty.

**Comment by meganrogge** [comment]
I'm not able to reproduce that issue @roblourens. Could you provide me with the setting value you're using?

**Comment by meganrogge** [comment]
I think we should go with the more flexible approach here and allow the two to exist simultaneously.

**Comment by roblourens** [comment]
I forgot we have `${separator}` which avoids what I'm talking about, I used a literal `-`, so that certainly helps

**Comment by joaomoreno** [comment]
@paulacamargo25 I stole this TPI from you.
