### ISSUE TITLE
Notification and notification buttons lack border radius

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#191532]
1. If the notification content is sufficiently long, insufficient height is allocated for the action buttons to grow, consequently they appear cramped and lack border radius

2. When a notification is focused the focus border radius is truncated 

![Image](https://github.com/microsoft/vscode/assets/30305945/37be5cfc-0747-4d31-a77b-66ab57a43208)

**Comment by joyceerhl** [comment]
The border radius issue on the buttons still occurs if the VS Code window is resized 
![image](https://github.com/microsoft/vscode/assets/30305945/362549ca-d53b-4d02-bad3-16a230cdf4bf)

**Comment by bpasero** [comment]
I cannot reproduce when resizing the window, are you sure you tested on latest?

Here is the sample code I run from a command to trigger this:

```ts
notificationService.prompt(Severity.Error, `The terminal process "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe -Command yarn run watch:remotehub" terminated with exit code: 1.`,
	[{
		label: "Open Help",
		run: () => { }
	},
	{
		label: "Open Help",
		run: () => { },
		isSecondary: true
	}]);

notificationService.prompt(Severity.Info, `Are you using a screen reader to operate VS Code?`,
	[{
		label: "Yes",
		run: () => { }
	},
	{
		label: "No",
		run: () => { }
	}]);
```

**Comment by joyceerhl** [comment]
Yeah, still repros in today's insiders 
<img width="328" alt="image" src="https://github.com/microsoft/vscode/assets/30305945/9c5fa54c-d569-4bd2-944e-67cd8da8ba9b">

**Comment by bpasero** [comment]
Can you distill better steps for me to reproduce exactly into this state, ideally even running out of sources?

**Comment by joyceerhl** [comment]
What I do is open the VS Code repo in VS Code Insiders without having first actioned the notifications above, you can probably trigger the notifications by starting with fresh user data and extensions dir. Then resize the VS Code window so that the notification text starts to wrap. Eventually the button radius gets cut off when I do this.

**Comment by abhijit-chikane** [comment]
though I don't see the button's border getting cut off 
but I do see the whole notification border is getting cut off at the corner

![image](https://github.com/microsoft/vscode/assets/50770619/7a4dca6b-4a77-41c9-85bc-60f752778c0a)


steps to reproduce
prerequisite -> have 2 profiles with recommended extension not installed
1. try to switch the profiles
2. it will show the above dialog
3. now click on it so that notification get's focus and see the border at the corner is not rounded properly

**Comment by bpasero** [comment]
@joyceerhl but for this to reproduce you need to make the window small enough that the notification itself gets smaller in width right? In that case, there is a slight chance that the text of the notification wraps to the next line and then pushing the buttons down.

Notifications do not have any logic to grow larger because we assume that they are small enough that a user would not cause them to shrink. You would need to make the window size smaller than `500px` for this.

I still fee the original issue is addressed, meaning that the notification when opening applies the correct size.

**Comment by abhijit-chikane** [comment]
![image](https://github.com/microsoft/vscode/assets/50770619/dcb9158c-16fb-4b4f-9eb6-87c50ee1f1df)

![image](https://github.com/microsoft/vscode/assets/50770619/661018f6-0f6a-4dbd-8fe1-c0973deaf29e)

**Comment by joyceerhl** [comment]
> the notification when opening applies the correct size

Yes this is true, I will close and mark verified
