### ISSUE TITLE
Strange item selection when using the keyboard

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#191566]
Testing #191521

- clone https://github.com/microsoft/vscode-languageserver-node.git
- npm install
- open messageBuffer.ts
- select line 44 -47
- press Ctrl+Shift+r
- select show disabled
- press `s` to select another item

Observe:

- sometime pressing `s` does nothing
- soemtimes it moves but the order in which it moves to the next is not always the same

**Comment by sandy081** [comment]
I also observed this, the order changes if I type 's' bit faster in which case it seems to look for 'ss'

**Comment by justschen** [comment]
This might have to do with the delay or timeout. I'm currently matching the keyboard support in things like the breadcrumb picker, so there is some time needed between successive `S` keyboard inputs to go to the next `S` labeled item. @sandy081 is correct that if you type `SS` faster, it'll do fuzzy search and find `Extract to method class...` instead.

Not sure what people prefer - if you guys have input/suggestions let me know!

Example of succesive `mm` in the breadcrumb picker which I loosely based this off of.
![Recording 2023-08-29 at 10 26 08](https://github.com/microsoft/vscode/assets/54879025/797ed428-c16e-43c0-9eb9-3c7bc6c479a9)

**Comment by kieferrm** [comment]
Same issue here. The timeout feels confusing at times. I type and it works correctly. I type again and it doesn't. But when I wait 3s then everything works as expected. I'm unsure that's an issue in real life. I usually don't jump around between menu entries I just want to select one. The one exception I can see is when I mistype and then start over but nothing happens since I didn't wait enough.

**Comment by justschen** [comment]
So the timeout is currently set to 800ms. With the typos, since it's fuzzy matching, depending on _how bad the typo was_, it might still get picked up. No sure if the timeout is something that should be lowered so in the instance of someone spamming `S`, it would cycle through all `S` labeled options really quickly.

**Comment by justschen** [comment]
closing for now - after a couple months I haven't seen any additional complaints about the timeout 👍
