### ISSUE TITLE
Error when trying to `alt+F1` in terminal

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#191619]
Testing #191345

1. Turn on screen reader accessibility mode.
2. Open the terminal and focus into it.
3. `alt+F1`.
4. Get a warning "Cannot read properties of undefined (reading 'getAriaLabel')"
5. Accessible view doesn't open.

**Comment by meganrogge** [comment]
@alexr00 I cannot repro - could you pls provide the full error stack trace?

**Comment by alexr00** [comment]
I checked, there wasn't an error stack trace in the console.

![image](https://github.com/microsoft/vscode/assets/38270282/4cc0a007-d78b-4ce1-8b63-67f2c7e3e5fe)

**Comment by meganrogge** [comment]
Does this only happen in the terminal for you?

**Comment by meganrogge** [comment]
I'll try on Windows, maybe that's the difference

**Comment by meganrogge** [comment]
nope doesn't repro for me there either 😢

**Comment by meganrogge** [comment]
I see what could lead to this, thanks

**Comment by alexr00** [comment]
I'm also trying to find where it's coming from.

**Comment by meganrogge** [comment]
pretty sure it's coming from here https://github.com/microsoft/vscode/blob/2af3045474f52bad8f14f01b09acfd5912e7fb5a/src/vs/workbench/contrib/terminalContrib/accessibility/browser/terminalAccessibilityHelp.ts#L60-L63

and for some reason, `lookupKeybindings` finds two for me which is why I cannot repro whereas it's only finding one for you, so arr[1] is udf

**Comment by alexr00** [comment]
I've just reload, which I though I had already done at least once since encountering the issue, and now I can't repo.
