### ISSUE TITLE
Support unfocused dimming of all workbench components like output and debug console

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#191616]
Testing #191527

I find the choice of dimming just the terminal in the panel strange, why not dim the output pane or maybe debug console?

**Comment by Tyriar** [comment]
Let's discuss in https://github.com/microsoft/vscode/issues/191610

**Comment by bpasero** [comment]
Having talked about this in the Zurich standup, there was pushback on why only terminals and editors, but e.g. not output or debug console was included. So I am reopening this for consideration.

**Comment by Tyriar** [comment]
The plan is to add a  `.views: { viewId: boolean }` setting but keep the default opinionated as terminals and editors, unless feedback from the community hints we should do otherwise.

**Comment by svipas** [comment]
@Tyriar would be awesome if we are able to control or at least when you're navigating in the sidebar with extensions like Git, GitLens you're seeing content in the editor with 1 opacity, because now it is hard to read even though I find this feature useful. But when working only with terminal & editor it is awesome, because it dims terminal and vice versa so I thought it would be cool to have view array list which should dim so we have control over this. Or maybe this will be improved in the future so that viewing search results, Git, etc. will not dim.

**Comment by Tyriar** [comment]
@svipas doesn't that kind of defeat the purpose of the feature as input will not be going into the editor if you have the sidebar focused?

**Comment by svipas** [comment]
That is true, but it is hard to view code changes when you're looking around from Git view and then editor is dimmed, you need to manually focus to have full opacity, in all other cases I found it valuable. If I'm viewing diff that means I need to see content I'm viewing with full opacity, but then I'm just typing commit message, focusing on terminal, etc. in that case it makes sense to have dimmed view. Anyways, I guess this is mostly personal thing, that's why it would be awesome if this could be under config so everybody could adapt it to their needs.

**Comment by Tyriar** [comment]
Ah I see, this is similar to the problem when searching too: https://github.com/microsoft/vscode/issues/190102

**Comment by svipas** [comment]
Yep, that what I meant, if it is going to be "fixed" together with search that is very good, because I like this new feature 👏

**Comment by Tyriar** [comment]
Merging into https://github.com/microsoft/vscode/issues/236576

/duplicate
