### ISSUE TITLE
Unclear when terminal changes to unfocused state.

### ISSUE THREAD

**Issue by bhavyaus** [microsoft/vscode#191673]
Testing #191527

Repro:
1. Open a terminal panel.  
New terminal opened with state = Focused
3. Open another terminal by clicking on +
Another terminal is opened with state = Focused
4. Switch back to the first terminal and its state is now Un focused. Switch to the second terminal and it is also. unfocused. 
5. Create new terminal by again clicking on + and we're back to being focused.

Throughout steps 1 to 4, I never left the terminal context but somehow ended up in the unfocused state which is confusing to me.

**Comment by Tyriar** [comment]
This is by design as the focus is in the list not the terminal for accessibility reasons and to align with how lists work across the workbench. It also aligns with the purpose of the setting (which I clarified in the settings text this morning) that it's primarily a helper for where text is going to be typed into.

To change to what you're probably after:

```
"terminal.integrated.tabs.focusMode": "singleClick"
```

It makes it more difficult to select the tab then though.
