### ISSUE TITLE
Why is sidebar not included

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#191610]
Testing #191527

Conceptually panel and sidebar are very similar to me, so is there a reason dimming would not apply to the sidebar? For example, I may have decided to move output editor into the aux sidebar.

**Comment by bpasero** [comment]
That is the opinion of one user, do we have consensus that this is what we want to build? I personally would at least want other panels that accept keyboard focus to participate as well because these can show lots of output and even may look like an editor.

**Comment by Tyriar** [comment]
It's 3/3 users that commented on it recently (see https://github.com/microsoft/vscode/issues/30522#issuecomment-1682851529, https://github.com/microsoft/vscode/issues/30522#issuecomment-1687917241), plus the requestor of the feature (https://github.com/microsoft/vscode/issues/30522#issue-242406571 - "Dim or otherwise indicate "inactive" editor/terminal"). Additionally, almost all comments on the issue mention only terminals and editors.

Dimming all other views would make the feature less useful imo, the reason users want this is to dim less relevant editors and terminals (primary work areas), dimming other parts of the UI that show auxiliary information would harm the user experience as they often augment the active editor. I understand it seems somewhat arbitrary, but it's solving a targeted problem.

We can expand it later if needed `(accessibility|workbench.view).dimUnfocused.views: { terminal: true, ... }`, but right now that's solving a problem that no one is asking for and I wanted to solve the issue efficiently for those requesting it.

**Comment by bpasero** [comment]
Ok thanks for clarifying.
