### ISSUE TITLE
Terminal: some tokens not light theme aware?

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#19191]
Refs: https://github.com/Microsoft/vscode/issues/19071

I am using the light theme and the results from npm are sometimes shown in black, which looks bad in this theme:

![image](https://cloud.githubusercontent.com/assets/900690/22248597/9a3646f2-e23f-11e6-9395-dba8e6e79bf8.png)

**Comment by Tyriar** [comment]
It's like that because npm is saying print yellow on black background. Looks better on a dark terminal:

![image](https://cloud.githubusercontent.com/assets/2193314/22258779/c142e728-e217-11e6-8317-784822087c22.png)

Nothing we can do other than tweak the colors, which then may cause more contrast issues for yellow on light.
