### ISSUE TITLE
VS Code 1.81.1 starts *all* onTaskType extensions when debugging

### ISSUE THREAD

**Issue by larsch** [microsoft/vscode#192043]
This issue is to ressurrect #175821 which was fixed, then closed, then reverted without comment.

The issue remains in 1.81.1. Attempting to run any task loads ALL extensions.

For example, for me it loads PlatformIO, Rust Analyzer, etc. when I'm working on a C project.

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  1.81.1
- OS Version: Linux

Steps to Reproduce:

1. See #175821

**Comment by Blokyk** [comment]
Any update on this? I'm still encountering this bug using 1.84.1, and it's very overwhelming to have every extension startup all at once (with their associated notifications) when you just want to debug your project :/

@meganrogge since you were the one to revert the fix commit, could you at least explain why?

**Comment by hyangah** [comment]
I am a maintainer of the Go extension. We are observing that the Go extension is activated randomly due to this bug.
Is there any workaround extension authors can use until this issue is addresssed?

**Comment by blaine** [comment]
This is an extremely annoying bug. I have the rust-analyzer extension installed, and when I'm working on non-rust projects (e.g., a platformio C++ arduino project), rust-analyzer shows a very urgent red error message at the bottom of my screen. From all the related bugs, it sounds like this is a vscode issue, and extension authors are unable to fix it.

**Comment by carsonfarmer** [comment]
Seeing this issue as well from within a Swift project. I found this issue via: https://github.com/rust-lang/rust-analyzer/issues/17018

**Comment by meganrogge** [comment]
I see the issue here. I don't think we ever should've adopted implicit activation for tasks - which means that `onTaskType:x` is added as an activation event for any extension that contributes a task `x`. 

https://github.com/microsoft/vscode/blob/842e001a3dc9ff9d9241287c1d170ba0860f043e/src/vs/workbench/contrib/tasks/common/taskDefinitionRegistry.ts#L86-L92

Thus, that extension will get activated when the build task command is run for example because in doing that, we call activate task providers, which fires the events for the whole registry.

https://github.com/microsoft/vscode/blob/842e001a3dc9ff9d9241287c1d170ba0860f043e/src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts#L600-L602

Reverting this should fix it:

https://github.com/microsoft/vscode/pull/173192

**Comment by meganrogge** [comment]
This would also happen when debugging if the configured task for debugging lacks a `type`, which may be undefined

https://github.com/microsoft/vscode/blob/4e9bc6223baf3084ed4f2bf3c8e601f75d1ef03c/src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts#L792-L795

https://github.com/microsoft/vscode/blob/4e9bc6223baf3084ed4f2bf3c8e601f75d1ef03c/src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts#L817

**Comment by meganrogge** [comment]
I have to revert this fix once again because we need to activate all task providing extensions when debugging as otherwise, a `preLaunchTask` might not be found. A user can set their `preLaunchTask` to be anything. 

Similarly, build tasks can be set programmatically, using the `TaskGroup` API property. Thus, when the build task is run, we need to activate all extensions that contribute tasks.

In order to minimize the number of extension activations, we encourage people to set the `type` property for their `preLaunchTask`.

**Comment by isidorn** [comment]
This is unfortunate. Is there an alternative approach to fix this issue? Or is there some capability for tasks that we would have to add to tackle this?

**Comment by meganrogge** [comment]
One idea for the debugging case would be to make the `type` property for `preLaunchTask` mandatory. But that would break people's setups.

**Comment by meganrogge** [comment]
I can repro when I set `preLaunchTask` to be `${defaultBuildTask}`. 

Currently, when `${defaultBuildTask}` is used as a `preLaunchTask` we fetch all tasks, activating all providers, then filter to find the default build task. We then run it, which redundantly activates that provider.

The fix is to wait on activation. If we find a default build task, then its provider will be activated when its run. 

If we don't find one, then we'll fall back to the current behavior - activating all providers.

**Comment by connor4312** [comment]
I think that's good behavior. We might still be able to add some optimization for the case of extension-provided configurations. Maybe in workspace storage we keep a small LRU (say ~5 entries) to associate labels of tasks with the extensions that provide them, to avoid having to activate all extensions all the time?

**Comment by isidorn** [comment]
Thanks @meganrogge for improving this. I just tried it out and it behaves better for me. Adding verified label 
@larsch if you can still reproduce with the latest VS Code Insiders build do let us know. Thanks!
