### ISSUE TITLE
highlighted count in the status bar

### ISSUE THREAD

**Issue by fthebaud** [Microsoft/vscode#19208]
It would be nice to have the **highlighted count** (the number of occurrences of the word in the file) in the status bar, maybe on the left, like in Atom.

It's a different information than the number of **selected** occurrences of a word, and it's handy if you want to know the number of occurrences of a word in the file without having to launch a search or to select all occurrences.

**Comment by ToMakeSense** [comment]
[#496](https://github.com/Microsoft/vscode/issues/11973#issuecomment-316256618) totally agree on you!!!

**Comment by lleeoo** [comment]
To be clear, are we referring to search only? Or just plain editing? What I would like is for the number of occurrences of the word under the cursor to appear in the status bar, like in SynWrite.

For example, if the text of the description of this issue were in the editor and you clicked or used the arrows so that the cursor were on the word "number", then "3" would appear in the statusbar.

This feature often makes me not need to search at all.

**Comment by rebornix** [comment]
This can be done by an extension and we don't have plans to do this in the core in the near future.

**Comment by nemchik** [comment]
If anyone comes across an extension that does this please share!
