### ISSUE TITLE
Backspace triggering completion proposals can be confusing

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#19238]
- VSCode Version: Code - Insiders 1.9.0-insider (4265f5e35cb3ea8ba7e0cf6b14ec606b6f8647ea, 2017-01-24T10:29:13.076Z)
- OS Version: Darwin x64 15.6.0
- Extensions: None

Steps to Reproduce:

1. Open empty html file
2. Type: foo`<space>`f`<enter>`
3. Completes to: foo`<space>`foo`<caret>`
4. Assume `<enter>` was meant to start a new line
5. Therefore type: `<backspace><backspace><enter>`
6. Expected: foo`<space>`f`<newline><caret>`
7. Actual (again): foo`<space>`foo`<caret>`

**Comment by jrieken** [comment]
Agreed, we don't trigger auto suggest on backspace anymore.

**Comment by varkor** [comment]
Did this change remove auto-suggest for backspace entirely?
When mid-word, dismissing the auto-suggest menu on backspace is unhelpful, as it is likely you made a small typo (such as typing an additional character by mistake) and still want suggestions. The issue here seems to have been showing suggestions when typing backspace *specifically before whitespace*. The current behaviour is inconvenient, and there seems to be no way to modify it in the settings.

**Comment by smuuf** [comment]
This is simply bad.

Suggestions should not disappear `when pressing backspace` + `when suggestions were already shown`. One small typo, person tries to correct the mistake, presses backspace,... and "everything's gone".

And if one tries to re-trigger suggestions (eg. `ctrl+space`), the original suggestions are now filtered by the first letters of the word I've already written.

![erg](https://user-images.githubusercontent.com/6860713/29328111-b2996f92-81f1-11e7-87d7-86667581f64f.gif)

**Comment by dennisfrostlander** [comment]
@jrieken This inconvenience is reported by the developers using our extension as well. The behavior is inconsistent with the regular VS where the backspace does re-trigger code completion.
Any chance to reconsider the default behavior or at least provide a setting to control that?

**Comment by jrieken** [comment]
Yeah, valid. Please file a new issue, the chance of us looking at closed issues is very low. Sorry, that!
