### ISSUE TITLE
Smoke test flake: turns off editor line numbers and verifies the live change

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#192610]
Build: https://dev.azure.com/monacotools/a6d41577-0fa3-498e-af22-257312ff0545/_build/results?buildId=231209
Changes: https://github.com/Microsoft/vscode/compare/088d730...079d0ab

```
  1) VSCode Smoke Tests (Web)
       Preferences
         turns off editor line numbers and verifies the live change:
     Error: Timeout: get elements '.line-numbers' after 20 seconds.
      at Code.poll (/Users/runner/work/1/s/test/automation/src/code.ts:277:11)
      at Code.waitForElements (/Users/runner/work/1/s/test/automation/src/code.ts:218:10)
      at Context.<anonymous> (src/areas/preferences/preferences.test.ts:22:4)

  2) VSCode Smoke Tests (Web)
       Preferences
         changes "workbench.action.toggleSidebarPosition" command key binding and verifies it:
     Error: Timeout: get element '.part.activitybar.right' after 20 seconds.
      at Code.poll (/Users/runner/work/1/s/test/automation/src/code.ts:277:11)
      at Code.waitForElement (/Users/runner/work/1/s/test/automation/src/code.ts:222:10)
      at ActivityBar.waitForActivityBar (/Users/runner/work/1/s/test/automation/src/activityBar.ts:28:3)
      at Context.<anonymous> (src/areas/preferences/preferences.test.ts:33:4)

```

**Comment by bpasero** [comment]
This actually looks like a real issue to me wrt settings. Both tests fail because settings have been written to in a way that renders them wrong. I wonder if our disposable work could have any impact here:

![playwright-screenshot-1-turns_off_editor_line_numbers_and_verifies_the_live_change](https://github.com/microsoft/vscode/assets/900690/e08fcbb2-5fbb-4c32-aecc-9aee2ba4eea7)
![playwright-screenshot-2-changes__workbench_action_toggleSidebarPosition__command_key_binding_and_verifies_it](https://github.com/microsoft/vscode/assets/900690/019a0af9-bcda-4649-bfd1-b07f92f743e2)

**Comment by bpasero** [comment]
Ok wait, this is really bizarre: the playwright playback shows the custom title with command center in the beginning and then suddenly disappearing. I wonder if at that moment we issue a click that then ends up in the wrong location?

![Recording 2023-09-08 at 20 03 49](https://github.com/microsoft/vscode/assets/900690/6d7f966b-0608-40cb-845d-564b595c5326)

I cannot explain the removal of the custom title in this case. Are we running some kind of settings sync? The theme also seems to change.

**Comment by bpasero** [comment]
Looks like a flake.

**Comment by bpasero** [comment]
Actually, it turns out we configure the command center and layout actions to not be visible in smoke tests:

https://github.com/microsoft/vscode-smoketest-express/commit/f041f67cf235b1fd983780750d9e376fac6d1f74

This explains why the custom title area hides after a while. I think I will see to revert that change because it would mean that at anytime while the test runs, the entire workbench moves up by 22px...
