### ISSUE TITLE
Task execution could give focus to the terminal

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#19266]
Testing #19057

- create a task in task.json
```json
{
    "version": "0.1.0",
    "isShellCommand": true,
    "showOutput": "always",
    "tasks": [
        {
            "taskName": "yeoman",
            "command": "yo"
        } 
    ],
    "_runner": "terminal" 
}
```
- Run the task
- the terminal opens and shows the yeoman generator.
- Try starting the generator UI. You first need to give focus to the terminal

**Comment by dbaeumer** [comment]
Good point. If showOutput is always I should give focus.

**Comment by dbaeumer** [comment]
I tried it and it actually is bad. The reason is that ShowOutput.Always is the default which would make the terminal take focus almost always. 

So I think we need to have an additional field here to indicate that the terminal should take the focus. Will first look how to best make this in the API and the port it to the JSON.

**Comment by dbaeumer** [comment]
The final task 2.0.0 version has a `presentation.focus` property to control this.
