### ISSUE TITLE
Add terminal highlighting support

### ISSUE THREAD

**Issue by clearoce** [microsoft/vscode#192671]
Type: <b>Feature Request</b>

The reason is that when I used WSL to compile the opencv library, the information displayed by the terminal was all white font, and it was difficult to capture some key information. Can I add a highlight effect like mobaxterm? However, I remember that GitHub's codespace had some highlighting, but as a user there was no more convenient way to set it up, or plugins.

VS Code version: Code 1.82.0 (8b617bd08fd9e3fc94d14adb8d358b56e3f72314, 2023-09-06T22:07:07.438Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Connection to 'wsl+Ubuntu-22.04' could not be established

**Comment by meganrogge** [comment]
Programs and plugins can set the color of the terminal's text, so I don't think we want to mess with that, example below. Thoughts @tyriar?

![Screenshot 2023-09-11 at 11 10 10 AM](https://github.com/microsoft/vscode/assets/29464607/e30d7e28-a46e-494a-a2b6-4331fcddc4f8)

**Comment by clearoce** [comment]
@Tyriar  The first screenshot is mobaxterm's terminal interface, and the next one is in vscode. I guess it might be a feature of the software. I'm not sure either, as both sides are the default configuration.

![mobaxterm](https://github.com/microsoft/vscode/assets/47705500/2072d702-d82b-4f5f-8c30-ae4639e70e02)
![vscode](https://github.com/microsoft/vscode/assets/47705500/f55ab05b-c233-47f7-bd58-5c41d307c2ed)

**Comment by Tyriar** [comment]
@clearoce can you run `env` in each of the terminals and compare? There's likely something related to color there that is triggering the difference.

**Comment by clearoce** [comment]
Sure. These are the information after comparing with diff tools, VSCODE on the left and Mobaxterm on the right. I guess the only color-related parameter between them is 'COLORTERM=truecolor', and that doesn't matter. 
I found pre-selected color themes in mobaxterm, which simply change the theme of the terminal without affecting the highlighted content, and I suspect they may just be using some kind of keyword search.
![diff](https://github.com/microsoft/vscode/assets/47705500/e86c0861-575a-4ff1-b61e-0348ff3a033c)
![setting](https://github.com/microsoft/vscode/assets/47705500/ac9e1343-887e-4eb1-82b0-92701fac1268)
![test](https://github.com/microsoft/vscode/assets/47705500/e8072b60-9233-4b0e-87c6-ff8344c67481)

**Comment by Tyriar** [comment]
Often `$TERM` defines what colors are used, but normally it's more colors when moving from `xterm` to `xtem-256color`. I also really doubt a keyword search for this is happening since things like `\`numpy.disttools\`` are highlighted. I'm going to close this off am I'm sure this is related to the program you're running, not the terminal. We also don't plan on adding special highlighting like you're proposing.

If you want to look more into it you can enable trace logging (Set Log Level in command palette) and then look at Output > Terminal when you run this, it will show exactly what the program sends to the terminal which should include a bunch of `(ESC)[3<n>m` sequences to change the colors of the text. Given this, you can search around for how color output works in cmake.
