### ISSUE TITLE
Multiple debugging sessions when play button is hit multiple times while debugging single file without launch.json

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#19268]
Testing #18397 on Windows

- Open a single js file in VS Code Insiders (no breakpoints)
- Open the Debug Side Pane
- Click the Play button to start debugging
- Click again
- Now there are 2 Launch processes running. As a user, I am not sure why. The first one should have closed. Or the second should be a no-op
![image](https://cloud.githubusercontent.com/assets/16890566/22263120/3d62bed6-e228-11e6-924c-4e2e43fa792b.png)
- Click on the red stop button. Now I see this
![image](https://cloud.githubusercontent.com/assets/16890566/22263171/5e87113e-e228-11e6-8437-cb2fb9c37a23.png)
The drop down has just 1 option.
Why is the drop down even here?
- Click on the red stop button a second time. All debugging is stopped.

If I tried the same in a workspace with a launch.json,
- Clicking on the Play button the second time is a no-op
- Clicking on the Red stop button stops the debugging. No need to click twice
- The drop down is in the side pane not in the floating debug bar
![image](https://cloud.githubusercontent.com/assets/16890566/22263339/f3703b2c-e228-11e6-9b59-3afe1233556c.png)

**Comment by isidorn** [comment]
Thanks for feedback. However all of this is intentionally designed. Let's try to answer your questions:
1. The first program does not close because there is an issue in node that programs do not exit on end
2. There is still a dropdown even though there is one process since we want the user to be aware that he was in the multi process session and that the second process is no longer there. This was discussed in detail when we introduced multi process support

The actual progblem here is that you ended in a multi process debugging even though you did not want that.
What we can do to prevent this is to simply disable multi process debugging in no folder workspace. However that has its pros and cons.

@weinand opinion?

**Comment by isidorn** [comment]
We decided to disable multi process debugging in no folder workspace. We can bring it back if users request it
