### ISSUE TITLE
No Launch Gear to create launch.json file when no workspace is open

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#19264]
Testing #18397 on Windows

- Open a single js file in VS Code Insiders
- Open the Debug Side Pane

You can see the Play button to start running/debugging, but no gear button to configure launch.json
The gear is available if you open a workspace though.

**Comment by isidorn** [comment]
This is as designed as for the no folder workspace we support debugging but we do not support a launch.json. User currently has to open a folder in order to configure a launch.json (similar to how he can not have workspace settings in a no folder workspace) - we might change this in the future, so we just pickup a nearest launch.json (but this is currently not on the immedaite plan)
