### ISSUE TITLE
Multi-line diagnostics

### ISSUE THREAD

**Issue by ccapndave** [Microsoft/vscode#1927]
Some error messages (e.g. from Elm) are quite verbose, and are very hard to read properly without line breaks.

Therefore it would be nice if the `vscode.Diagnostic` message could contain line breaks (these could be stripped out in the `Errors and warnings` selector to keep the UI sensible).  It would be even nicer still if error messages could contain colors and styles.

This is an example of the kind of thing it would be nice to have in a diagnostic popup:

![image](https://cloud.githubusercontent.com/assets/297992/12235454/19c3e236-b874-11e5-9193-cb6870eeae0a.png)

**Comment by jrieken** [comment]
Wd do support this with the hover. I'll add support for the `F8` feature, unsure what to do with the new error list.

**Comment by sandy081** [comment]
With regards to error-lists, showing long error messages completely would occupy space. So, I am thinking to provide an expand/collapse option for the error-entry to show or hide the complete description.

**Comment by jrieken** [comment]
Also, a mono-space font should be used. Otherwise whitespace based formatting won't work

**Comment by jrieken** [comment]
Like the hover, the message part of the in-editor error display now uses the editor font.

![screen shot 2016-06-07 at 11 32 38](https://cloud.githubusercontent.com/assets/1794099/15853043/c4ca685a-2ca3-11e6-81bd-51b4a3cef1ad.png)

**Comment by jrieken** [comment]
cc @stevencl for how to handle multiline diagnostics in the error list view

**Comment by sandy081** [comment]
Supporting multiline or long descriptions is not trivial with current infrastructure. Firstly, I will be showing them with ellipsis.

@joaomoreno mentioned different ideas on how we can support this in trees.. Will look into them.

**Comment by sandy081** [comment]
Marking this as a feature request for problems view to show multi line descriptions

**Comment by trixnz** [comment]
I'm not sure if this belongs in its own issue or is suitable to piggy back on the discussion here: Some languages (Rust, for instance) output additional references to lines of code that contributed to the error. Adding these to the Problems window would be helpful to the end user, but doing so causes confusion because the diagnostic entries are sorted on the `Range` field, resulting in out of order results.

Allowing a `Diagnostic` object to contain child errors that show up in a tree display would be a big step forward. Is that what you meant by trees, @sandy081?

**Comment by sandy081** [comment]
@trixnz Scenario you mentioned is different than what is being discussed here. Its about showing long/ multi line description problems. 

Trees, I mentioned here is an implementation detail. But, we do show problems as tree with only one level. Your scenario is interesting and I would suggest to make that as a separate issue, since, it needs changes at multiple places for eg: Diagnostic model, api etc

**Comment by faceyspacey** [comment]
any progress on this? As it currently stands, Flow for VS Code is basically useless because of issues like this:
https://github.com/flowtype/flow-for-vscode/issues/39#issuecomment-272881674

and this:
https://github.com/flowtype/flow-for-vscode/issues/39#issuecomment-273012454

The general problem being that typed modules are barely helpful for its usages. The system won't notify you of what usages for typed React components are missing props. And for redux `connected` components, there is no type reporting in usages of the wrapped react component. 

For VS Code to be an option for Flow projects, there's a long way it must go. It's almost as if typescript is intentionally being favored and little progress is being made on Flow to cripple it. A lot of people are choosing VS Code these days (dare I see it's the most popular choice right now when picking a new editor), and a lot less people than otherwise would are choosing Flow for the aforementioned reasons. I have a hunch Flow would be doing a lot better if it was properly supported in the editor du jour. I have a hunch Flow would be what most React developers instantly pick over Typescript if that was the case. There are clear winners in this industry for many things: React over Angular, Redux over everything else, Jest has finally done what's needed to be done for React testing, VS Code has beaten Atom and Nuclide, but the battle for the winner-takes-all typing solution between Typescript and Flow are still very much up in the air. It's my opinion that *that* absolutely would not be the case if Flow had proper editor support by the top editor of the day.

The way I see it is: the VS Code team has a decision: to take Flow seriously--perhaps more seriously than Typescript--or in the time until it does be beaten by Atom as it catches up in the areas its weak like debugging. In other words, VS Code could conquer the market if they took Flow seriously, instead of letting Typescript dictate what's best for it. VS Code is a great editor, it's unbelievable at this point in time that it doesn't support Flow--cuz it doesn't. It needs way higher caliber sort to reach that category. And of course proper intellisense for typed React components, updates to reported errors on keypress not just saved files which reload the app and trigger runtime errors. These are missed opportunities and it's beginning to be very late in the game.

**Comment by sandy081** [comment]
Multiline errors are not yet planned, we will definitely come to this when there are free cycles. Thanks.

**Comment by dmitriid** [comment]
Is it possible to bump this in priority? Off the top of my head, Elm, Reason/Bucklescript, Typescript would greatly benefit from this. Rust was mentioned above.

In general, most modern languages/build tools provide multiline errors which become unreadable when squashed into single line.

Hovering to display the error is nice-ish, but it breaks the mostly-keyboard flow that developers are in when developing.

**Comment by jonsterling** [comment]
I second @dmitriid's comment. I'm building a proof assistant, and lack of multiline errors makes the diagnostics view essentially useless for my purposes—but with a modification to support multiline errors (or at the very least, a modification so that diagnostics are displayed in the order that they are reported!) it would become an essential part of my users' workflow.

As it stands, I may have to implement my own diagnostics pane, which I was hoping to avoid.

**Comment by jonsterling** [comment]
(See #16099 for a description of the out-of-order diagnostics issue I mention in connection with this.)

**Comment by damassi** [comment]
For those who are curious, I fixed this by following these (somewhat hacky) steps: 

1. Install https://github.com/be5invis/vscode-custom-css … and get it working
2. Add this to stylesheet:
```css
.panel .monaco-tree-row {
    white-space: pre-line;
    height: auto !important;
}
```
3. Reload the JS/CSS, and fixed: 

![dqafoiqueaaxv2q](https://user-images.githubusercontent.com/236943/34343551-c207473e-e988-11e7-8d23-1a2eda3b00e6.jpg)

**Comment by dmitriid** [comment]
@damassi You are the hero we don't deserve :)

**Comment by sandy081** [comment]
@damassi The hack might break other behaviour like Scrolling if there are many problems. 
I am open to take a PR for this with proper fix.

**Comment by damassi** [comment]
@sandy081 - Indeed it does but for most of my cases its been more than sufficient. I'll look into opening a PR for a proper fix today 👍

**Comment by DanTup** [comment]
Dart is considering more verbose messages to help users too, so I'd love to see this. I did wonder about using the additional info and just setting the same range (since it already expands/collapses), but it shows the filename/range even if it's the same:

![screen shot 2018-10-31 at 10 27 59 am](https://user-images.githubusercontent.com/1078012/47782438-24129d80-dcf8-11e8-9f6e-f87b37ed667e.png)

Maybe hiding the filename/range info if it's the same as the parent diagnostic would be a relatively simple way to get part-way there (the diagnostic provider would have to split the lines, of course).

**Comment by damassi** [comment]
Note that my vs-code-custom CSS solution to this no longer works in the latest VSCode, haven't had time to investigate why, but 👍 👍 for getting multiline in core!

**Comment by sandy081** [comment]
Problems view now shows multi-line diagnostics in multiple lines. You can expand/collapse the message to be shown in multiple or single line. There is also a global command to show all message in multiple or single lines. Check it out 👇 

![multiline-diagnostics](https://user-images.githubusercontent.com/10746682/50275092-ed771a80-043e-11e9-97af-462133aedcc9.gif)

**Comment by damassi** [comment]
Beautiful @sandy081 💯 🎉
