### ISSUE TITLE
support identifier-based jumps in markdown hyperlink

### ISSUE THREAD

**Issue by DingWeizhe** [microsoft/vscode#192884]
We can now navigate to specific lines in the source code files within markdown using the syntax `[test](./a.ts#L8)`. 

However, due to frequent code changes, markdown link line numbers often become inaccurate. 
To address this issue, I propose enhancing markdown links to support identifier-based jumps, 
starting with '@' (matching the behavior of the Command Palette) and split with dot.

like `[extractSelection](src/vs/platform/opener/common/opener.ts#@extractSelection)`
and `[registerValidator](src/vs/platform/opener/common/opener.ts#@IOpenerService.registerValidator)`

This enhancement will significantly improve the efficiency of code documentation maintenance.

**Comment by mjbvz** [comment]
Interesting idea but what other tools support this?

**Comment by DingWeizhe** [comment]
In fact, I don't see similar functions in other tools. I just feel troubled when maintaining documents.

**Comment by mjbvz** [comment]
Marking this as an extension candidate

With our built-in markdown support we generally try to support what existing tooling support instead of adding our own functionality. So maybe if a site like Github adds support for this syntax, we could consider building support into VS Code too, but until then it's a better fit for an extension instead
