### ISSUE TITLE
quick search: preserveInput priority over selected text

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#192898]
We added support for auto-populating selected text to quick search (https://github.com/microsoft/vscode/issues/191513), but setting `preserveInput` overrides this.

This is because `preserveInput` takes precedence over any default string (even if `defaultFilterValue` is defined).

https://github.com/microsoft/vscode/blob/26f41a49948c6da4eec5c93836c1c331364b54f2/src/vs/platform/quickinput/browser/quickAccess.ts#L83-L87

(from https://github.com/microsoft/vscode/pull/191956)

**Comment by TylerLeonhardt** [comment]
To me, this feels backwards... I'd want whatever was passed in to take precedence... and only if the default is set to the default value (aka the prefix) should the LAST be restored.

@bpasero was there a reason for this behavior that maybe I don't know about?

**Comment by bpasero** [comment]
I do not remember. I assume you already bisected this to the origins?

**Comment by TylerLeonhardt** [comment]
@bpasero the origin of this change came from:
https://github.com/microsoft/vscode/commit/042fded9b676a530899d0c198ce6f8b4e3f1e944

I now understand why this code behaves like it does. It's because it's provider (& prefix) agnostic. This code actually knows nothing about the prefix and nothing about the provider _except_ the last accepted value per-provider.

So basically, it's up to the caller of `quickInputService.quickAccess.show(...)` to say no don't `preserveInput`.

**Comment by TylerLeonhardt** [comment]
I've sent a PR that makes the search one work as we expect.

**Comment by andreamah** [comment]
verif steps:
1. `search.experimental.quickAccess.preserveInput:true`
2. `Search: Quick Text Search (Experimental)` command, then search for some text and select one of the results.
3. Repeat step 2, but make sure that the input that previously had is retained.
4. Select something in the pick, then highlight some text in the editor.
5. Try `Search: Quick Text Search (Experimental)` again. You should see your selected text in the input box.
