### ISSUE TITLE
Formatting json file removes new line at the end and save adds it back

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#19281]
VS Code Insiders dated 2017/01/24

1. Open any json file with 1 or more new lines at the end
2. Format the file => the new lines in the end get removed
3. Save the file => one new line in the end gets added.

Save does not add that new line in VS Code 1.8.1

**Comment by mousetraps** [comment]
Format should remove the newline at the end by design, but adding a newline at the end is unexpected. That said, interestingly enough, I can't reproduce. A few Qs:
1. Are you sure it's not an extension that's causing the line to get added?
2. Do you have format on save enabled?
3. What happens if instead of saving for step 3, you try doing "format document" again?

**Comment by ramya-rao-a** [comment]
Ah! It was not an extension but a setting.

While testing the config settings UI, i was randomly adding settings and one of them was

`"files.insertFinalNewline": true`

which adds the new line on save.
