### ISSUE TITLE
JavaScript and TypeScript differences in coloring

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#19293]
Test item #18318

- VSCode Version: Code - Insiders 1.9.0-insider (4265f5e35cb3ea8ba7e0cf6b14ec606b6f8647ea, 2017-01-24T10:29:13.076Z)
- OS Version: Darwin x64 15.6.0
- Extensions: Atom One Dark Theme 0.3.0

Steps to Reproduce:

Atom One Dark Theme 0.3.0

1.8:
![screen shot 2017-01-24 at 2 30 59 pm](https://cloud.githubusercontent.com/assets/9205389/22269806/c9693428-e241-11e6-97f9-8a8469cd770f.png)

1.9:
![screen shot 2017-01-24 at 2 33 01 pm](https://cloud.githubusercontent.com/assets/9205389/22269880/13735170-e242-11e6-8cba-c04d4fda8722.png)

Many differences, 1.9 has much more red. The source is from our repo.

**Comment by chrmarti** [comment]
JavaScript with Atom One Dark Theme 0.3.0

1.8:
![screen shot 2017-01-24 at 2 37 03 pm](https://cloud.githubusercontent.com/assets/9205389/22270009/a74038b4-e242-11e6-9cf7-b84c61a968c2.png)

1.9:
![screen shot 2017-01-24 at 2 39 03 pm](https://cloud.githubusercontent.com/assets/9205389/22270071/e3d09530-e242-11e6-97e5-449d50c9cef7.png)

**Comment by chrmarti** [comment]
Marking as important for awareness.

**Comment by chrmarti** [comment]
Reloading 1.9 produced the same result.

**Comment by chrmarti** [comment]
Also Red's background and tab-rules where more red in 1.8.

1.8:
<img width="278" alt="screen shot 2017-01-24 at 4 26 03 pm" src="https://cloud.githubusercontent.com/assets/9205389/22272883/e7e67d60-e251-11e6-9fc4-b46c0f2c5a18.png">

1.9:
<img width="342" alt="screen shot 2017-01-24 at 4 27 05 pm" src="https://cloud.githubusercontent.com/assets/9205389/22272898/ff5138dc-e251-11e6-8095-1ac93ed85919.png">

**Comment by alexandrudima** [comment]
### ✅  Atom One Dark Theme 0.3.0 Case 1 (TypeScript)

#### Before
It was matching the theme rule `support.class` (due to CSS class name matching):
![image](https://cloud.githubusercontent.com/assets/5047891/22282443/ae480c32-e2dc-11e6-998e-3bca88e7c8b9.png)

#### After
It does not match the theme rule `support.class` which is correct according to TM theme matching rules
![image](https://cloud.githubusercontent.com/assets/5047891/22282470/ef661696-e2dc-11e6-9013-d80870216760.png)

#### Conclusion: No bug here unless TS wants to change its grammar (i.e. current TS grammar + Atom One Dark Theme looks now the same in VSCode, TextMate and Sublime)

---

### ✅ Atom One Dark Theme 0.3.0 Case 2 (JavaScript)

#### Before
It was matching the theme rule `variable.meta.function.readwrite.js` (due to CSS class name matching):
![image](https://cloud.githubusercontent.com/assets/5047891/22282609/d3d96dc8-e2dd-11e6-878d-dc5b5232051d.png)

#### After
It does not match the theme rule `variable.meta.function.readwrite.js` which is correct according to TM theme matching rules, but it matches some other rule `variable`, which is correct.
![image](https://cloud.githubusercontent.com/assets/5047891/22282632/f0e3c76a-e2dd-11e6-8458-900f75ad83d2.png)

#### Conclusion: No bug here unless TS wants to change its grammar (i.e. current JS grammar + Atom One Dark Theme looks now the same in VSCode, TextMate and Sublime)

---

Red theme background

This is a regression, but it is unrelated to syntax tokens -- created #19344 to track it.
