### ISSUE TITLE
Negative character group [^)] not working with multiline characters

### ISSUE THREAD

**Issue by namex42** [microsoft/vscode#193010]
- VS Code Version: 1.82.1 (user setup)
- OS Version: Windows_NT x64 10.0.22621

Steps to Reproduce:

0. CTRL+N and enter text from an image below
1. CTRL+F to find 
2. Enable regex search
3. Enter `(hello\([^)]*)(world)`
4. See that nothing is found, but in [regex101](https://regex101.com/r/Vvix7D/1) the world matched as Group 2

![image](https://github.com/microsoft/vscode/assets/58660882/f78e4f8d-aaf8-4674-a93e-eed1eacf1869)

**Comment by ArturoDent** [comment]
I assume this is because of the special handling of newlines by vscode in a regex.  Probably newlines are not assumed in this: `[^)]` for performance reasons.  You can trigger the inclusion of newlines by explicitly including a `\n` in your regex.  So note that this works

```
(hello\(\n*[^)]*)(world)
```

But there may be a better explanation.

fyi @bpasero

**Comment by amunger** [comment]
that's correct, same issue as https://github.com/microsoft/vscode/issues/108368
