### ISSUE TITLE
Sidebar remains in debug section after terminating a debug session

### ISSUE THREAD

**Issue by jlandersen** [Microsoft/vscode#1931]
In 0.10.6 when starting in debug mode (F5), the side bar switches to debug section. When terminating the debug session the side bar remains in the debug section (Shift+F5). I would expect the editor to return to the previous state (e.g. with explorer open).

**Comment by isidorn** [comment]
This is something which we have explored in the past but it did not feel good to us so we reverted it after a week. We are very reluctant to automtically change UI for the user, when the user starts debugging it means he actually wants to be focussed on debugging and thus revealing the viewlet makes sense, however when the user stops debugging it does not mean he wants to go back to editing, he might want to add some breakpoints / inspect repl and then start debugging again thus staying in the debug viewlet might be a correct choice sometimes.

@bpasero @stevencl opinons more than welcome

**Comment by bpasero** [comment]
Also @chrisdias

**Comment by stevencl** [comment]
I also think that switching back to the prior viewlet after stopping the debug session would be the right thing to do, but we need to think carefully and be clear about the actions that are interpreted as stopping a debug session. Pressing the stop button on the debug toolbar is one (obviously :-) ) but we would need to think about whether or not closing the application being debugged should also be interpreted as stopping the debug session.

**Comment by chrisdias** [comment]
:+1: on switching back to the explorer when you stop debugging. 

More often than not, my intention when pressing Stop or terminating the extension instance is to go back into "development mode" rather than stay in "debugging mode".  In "development mode" the Explorer is what I typically want to work with.

Isi's point about the user might want to start debugging again is completely valid, but the real issue I believe is that there is no way to press the "play" button from any view other than the Debug viewlet.  I think we should keep these two issues separate and try to correct both.

**Comment by egamma** [comment]
I would also like a quick way to go back to 'editing' when I'm done 'debugging'. In addition to switching to the explorer viewlet I also want to restore the state of the editors and get rid of the debug output.

In my opinion there are two separate actions: `stop the debug target` and `end/close my debugging session`, I don't feel comfortable to bundle them together with the current `stop` action. Would it make sense to explore some 'x' or close action in the debug tool bar on the right of stop. This action would mean end my debugging session?

![dbg](https://cloud.githubusercontent.com/assets/172399/12288854/1b22b516-b9d8-11e5-8b9e-5087badd14a1.png)

**Comment by jlandersen** [comment]
@egamma that sounds like a good approach - as long as there is a keyboard shortcut for the close debugging session part as well :-)

**Comment by chrisdias** [comment]
@egamma how is this different from stop debugging? i know what it would do, but from an intent perspective, why would i choose one over the other?  do i have to make a decision between the following?

A.  i would like to stop debugging and keep my debug layout
B.  i would like to stop debugging and return to development

i have trouble envisioning when i would choose option A. What would I want to do  next at this point? What is the most common choice?

**Comment by egamma** [comment]
@chrisdias 
>how is this different from stop debugging?

This is where we differ. To me the action is not `stop debugging` it is `stop the debug target` or `disconnect from the debug target` the action doesn't mean stop debugging to me.

I sometimes stop the debug target to start it again to be sure I debug from a clean state, my intent is not to `stop debugging` when press `stop`.

**Comment by isidorn** [comment]
have we come to some consensus here? I am fine with experimenting with some solution to get feedback
Erich's proposal looks good to me and I would start with that

fyi @stevencl @bgashler1

**Comment by chrisdias** [comment]
I suggest that we do this in two steps. 

First, we should make the Stop button switch back to the Explorer view, which is consistent with how Visual Studio works (our gold standard). 

![image](https://cloud.githubusercontent.com/assets/1487073/12907529/69c7f5a4-cea1-11e5-9c0c-a12ca8626a91.png)

Given this is the expected behavior (see top of this issue) we would be improving the E2E experience for many (most) developers. We can measure the effectiveness of this by measuring how many people click on the debug viewlet right after clicking on the stop button.  

Step 2 would be to introduce this a new stop mode using an A/B test so we can measure how many times people click the new stop action as compared to the control group that does not have the new action. We can also measure how many people bring up the explorer view or debug view after.

fyi @waderyan

**Comment by joaomoreno** [comment]
I don't agree that `stop` should implicate going back to the Explorer. A similar situation is committing from the git viewlet. I don't expect Code to send me back to the Explorer then, even when its clear that is a transition from *reviewing mode* to *development mode*.

I think about automatic viewlet switching when there is *something new to show*. For example, the debug viewlet comes up only when it has something new to show. Opening the Explorer without that reason doesn't seem logical to me.

This is clearly an opportunity for a setting, but I would keep the current behaviour as the default.

**Comment by chrisdias** [comment]
You make an interesting point about the Git viewlet and not switching back to the Explorer. But, that is a different workflow for me at least. I may be doing a partial commit or I may want to do a Publish after the commit (which I love by the way).  Unlike pressing stop in the debugger, there is no clear end to the source code control workflow.

I suggest we establish a hypothesis and measure it. We can get data on what the workflow is through the product after people stop debugging.  We can measure how many people do "X" within some time range (say 30sec) after stopping the debugging session and produce a heat map showing what the common tasks are.

Hypothesis: Most people will switch to the Explorer View after stopping the debug session such that we should automatically switch to the viewlet when pressing Stop, as in Visual Studio.

Timeline: 30 sec, how often people get from Stop to the following events:

Stop -> View Explorer
Stop -> Quick Navigation
Stop -> Any debugging activity
Stop -> Other

Assigning to @SofianHn to crunch the numbers.

**Comment by SofianHn** [comment]
:+1:

**Comment by joaomoreno** [comment]
:+1:

**Comment by chrisdias** [comment]
With the debug console now horizontal I find that i'm doing even more document/window management after i press Stop in the debugger.  

I have to open the Explorer and i have to close the debug panel so that i can use the full height of the editor.  This is especially painful on my laptop where the screen is not very tall.

**Comment by SofianHn** [comment]
@chrisdias how critical is this? I am trying to triage my bugs?

**Comment by chrisdias** [comment]
We are not going to change this is the //build timeframe so I would be ok pushing it out.

**Comment by stevencl** [comment]
We should discuss this in conjunction with https://github.com/Microsoft/vscode/issues/10437

**Comment by isidorn** [comment]
I introduced a setting `debug.openExplorerOnEnd` to control this behavior which has the default value `false`. So the behavior is unchanged unles the user explicitly sets it to true.
Feedback on the setting name is welcome
