### ISSUE TITLE
Windows crashes on load of large tests

### ISSUE THREAD

**Issue by eleanorjboyd** [microsoft/vscode#193240]
Karthik experienced this on his computer on the following [repo](https://github.com/microsoft/lsprotocol). I tried it on my own (mac arm) and did not experience the problem. Here are the steps:

1. Clone this repo
2. Create a new `.venv` and select the requirements to install with the `.venv` 
3. Run `python -m generator --plugin testdata`
4. Now go to the testing panel click `tests -> python -> test_generated_data.py`
5. When I click to see all the subtests for `test_generated_data.py` Karthik's vscode crashes trying to render all of them, my computer can successfully view them all.

I think this is a rendering concern which is why adding it to the `vscode` repo but let me know if it might be a problem on python testing end. Thanks

<img width="903" alt="image" src="https://github.com/microsoft/vscode/assets/26030610/ba292417-a626-499e-a55e-001949b8eb46">

**Comment by connor4312** [comment]
The expansion is okayish for me -- "only" takes about 600ms". However, clicking "refresh tests" results in a UI stall."

**Comment by connor4312** [comment]
Turns out the refresh was because _removing_ the items was unnecessarily slow. But then recreating all of them is done in <=1s. Not the fastest, but also, for 70,000 tests, that's not bad. I'm unable to get the stall you mentioned without refreshing tests -- do you or Karthik still experience the issue?
