### ISSUE TITLE
Disable Primary Side bar auto hiding

### ISSUE THREAD

**Issue by Cyoxite** [microsoft/vscode#193464]
Does this issue occur when all extensions are disabled?: Yes

I want to have opened explorer in primary side bar all the time.
Now Primary side bar auto hiding when i go to text editor.
I'm looking for option to disable this function. But i can't find this.

I find option autoHide.toggleHideSideBar but only for current workspace.

- VS Code Version: 1.82.2 (user setup)
- Commit: abd2f3db4bdb28f9e95536dfa84d8479f1eb312d
- Date: 2023-09-14T05:55:25.390Z
- Electron: 25.8.1
- ElectronBuildId: 23779380
- Chromium: 114.0.5735.289
- Node.js: 18.15.0
- V8: 11.4.183.29-electron.0
- OS Version: Windows_NT x64 10.0.22621

**Comment by ArturoDent** [comment]
Since there is no built-in `autoHide` settings, I strongly suspect this autohiding is caused by an extension.  Try the `Help: Start Extension Bisect` command to see if it is caused by an extension (I know you said the issue occurs when all extensions are disabled but you should still try the command).

**Comment by Cyoxite** [comment]
Yes, it's extension "feature" not vscode. After uninstall extension all working properly.
