### ISSUE TITLE
IntelliSense not working when using absolute import paths

### ISSUE THREAD

**Issue by henrikra** [Microsoft/vscode#19342]
- VSCode Version: 1.8.1
- OS Version: OS X El Capitan 10.11.6

Steps to Reproduce:
1. As an example I use my `actionTypes.js` which has redux action type constants like this:
```javascript
export const START_THING = 'START_THING';
export const START_THING_DONE = 'START_THING_DONE';
```
2. Then when I import them with relative path like this the IntelliSense is working like so:
![image](https://cloud.githubusercontent.com/assets/12229968/22282298/2b5dd844-e2e4-11e6-9155-c7cff4b27847.png)
3. But if I use absolute import (which is always better choice than relative) then IntelliSense does not pick up constants from `actionTypes.js` file like so:
![image](https://cloud.githubusercontent.com/assets/12229968/22282354/775c87d6-e2e4-11e6-97ee-77b82e4278bd.png)

**Comment by mjbvz** [comment]
Try creating a `jsconfig.json` file at the the top of your project:

```json
{
    "compilerOptions": {
        "module": "es6"
    }
}
```

Also try using `"system"` if `"es6"` does not work. You can read more about the `module` configuration option here: http://www.typescriptlang.org/docs/handbook/compiler-options.html

Give this a try and let me know if it works

**Comment by henrikra** [comment]
Wow this works! But why is it working? I did not have to do anything else that add your jsconfig.json file :D

**Comment by mjbvz** [comment]
Glad to hear that it works now.

Here's some more info about the `jsconfig.json` file and why it is required: https://code.visualstudio.com/Docs/languages/javascript#_writing-jsconfigjson

Our standard intellisense defaults to looking for commonjs style module and module paths. If you are using a different style of modules, you must configure your JavaScript project using a `jsconfig.json` so that intellisense knows about this.

You would generally check in a `jsconfig.json` into git so that other users pick up these settings as well.
