### ISSUE TITLE
Linux and Windows has Different Shortcuts

### ISSUE THREAD

**Issue by KaduAmaral** [microsoft/vscode#193529]
Hello,

I was wondering, because sometimes I've to work on Linux, and some times on Windows, and the vscode default shortcuts are different for both environment. IE, the shortcut to comment some code on Linux is `CTRL+/` and on Windows is `CTRL+;`. This is just a example, I use many others shortcuts that are different on both environments.

There are some possibilite to toggle to Linux Shortcuts on Windows?

**Comment by ulugbekna** [comment]
Hi @KaduAmaral :-) 

- Looking at how keybindings for toggling line comments are [defined](https://github.com/microsoft/vscode/blob/95ae03f652a79d56a0a8d696f32aa5d3206d8959/src/vs/editor/contrib/comment/browser/comment.ts#L81-L101), I see we don't have different keybindings based on OS. I suspect you have different keyboard layout maybe on your windows machine? 

- Side Note: We do have different keybindings based on the system sometimes, but usually this comes because that keybindings is bound by the OS.

- There is no great way to have linux shortcuts on windows (which is unlikely what you want because you might have clashes with OS shortcuts), but you can invoke command "Preferences: Open Default Keyboard Shorcuts (JSON)", copy that file's contents and paste it into your Windows machine's keybindings.json (to open it you invoke command "Preferences: Open Keyboard Shortcuts (JSON)"
