### ISSUE TITLE
Markdown: editing our 1.9 release notes flickers more than before

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#19351]
I notice that when I edit our 1.9 release notes, the markdown preview seems to jump up and down all the time there is a change. Compared to 1.8 stable, this seemed to not happen.

**Comment by bpasero** [comment]
Better, I still see flickering that it jumps up and down a little bit and the decoration to the left to show me the current edited location is also flickering. @mjbvz let me know if I should open a separate issue on that or if you think that is fixable.

**Comment by mjbvz** [comment]
@bpasero The flicker should now be better than VSCode 1.8, but we can still do better. I've noticed the same sort of slight flicker on images in particular and on the current paragraph indicator as you noted. 

Please open another, lower priority issue so that we can track further improvements

Thanks
