### ISSUE TITLE
When toggle auto attach bugger, the icon would change if the option key pressed.

### ISSUE THREAD

**Issue by DevinJohw** [microsoft/vscode#193911]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.82.2
- OS Version: macOS 13.5.2 (22G91)

Steps to Reproduce:

1. Enable Toggle auto 
2. Run a normal Node.js program, and the bugger would be attached automatically.
3. Press the option⌥  key, the disconnect icon would change.
![2023-09-24 20 28 28](https://github.com/microsoft/vscode/assets/143488669/1fec6b08-20b5-42b0-8a52-4ba66b6edc66)

**Comment by IllusionMH** [comment]
AFAIK this is intended behavior for many buttons that are altered to related action when Alt/Option is pressed.

For example: split editor switches between vertical and horizontal splits

**Comment by DevinJohw** [comment]
What about Disconnect button?

**Comment by IllusionMH** [comment]
As you can see - it has an alternative related action as well - stop instead of just disconnect and leave process running.

I've shared example of other buttons.

Please clarify what is the problem you are reporting here?
If it's switch between Disconnect and Stop - it's intentional and it's not only place with such feature.

**Comment by DevinJohw** [comment]
Thanks for your explanation, I think I should close this issue.
