### ISSUE TITLE
Test Editor Tab Height Density

### ISSUE THREAD

**Issue by benibenj** [microsoft/vscode#193981]
Refs: #42253 

- [x] anyOS @aiday-mar
- [x] anyOS @andreamah 

Complexity: 1

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23193981%0A%0A&assignees=benibenj)

---

We added a new setting `window.density.editorTabHeight: 'default' | 'compact'`. This setting allows the user to reduce the height of editor tabs. It also affects the title bar when tabs are hidden (`workbench.editor.showTabs: false`).

<img width="400" alt="image" src="https://github.com/microsoft/vscode/assets/44439583/0f36bae3-5692-46d0-a7c6-8c30209d0496"><img width="380" alt="image" src="https://github.com/microsoft/vscode/assets/44439583/0190c604-6e9d-4e3d-b2e1-13126fb7b9e1">

1. Set `window.density.editorTabHeight: 'compact'`, does the height of the title bar shrink? It should! Now toggle the `workbench.editor.showTabs` setting. Is it still small? It should be!
2. Set `workbench.editor.showTabs: true`
3. Set `workbench.editor.wrapTabs: true` and open many tabs until they wrap. The height of an individual tab should still be the same.
4. Open a file that contains a line which has more characters then can fit in your window, causing a scrollbar to appear at the bottom of the editor. Check that the scrollbar is placed at the right height. (Placed on the bottom of the editor as in the image bellow) 
<img width="334" alt="image" src="https://github.com/microsoft/vscode/assets/44439583/a791ce45-65be-4fe8-987b-0c152a5e25cf">

**Comment by aiday-mar** [comment]
This works well! Unrelated to this test plan item, I was testing this feature `workbench.editor.wrapTabs` and I noticed how the tab width all of a sudden changes on resize of the window. I am wondering if we want this behavior, because it looks a bit off to me. I think this is happening because we are wrapping the tabs (the other tab jumps to the bottom) but do we need the tab before to be so wide? I'll open an issue concerning this, perhaps it'll get upvotes.

https://github.com/microsoft/vscode/assets/61460952/e95ef488-f14f-4ec1-b6fa-942963aa1676
