### ISSUE TITLE
Test: Configurable scroll behavior on `notebook.cell.executeAndSelectBelow`

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#194069]
Refs: https://github.com/microsoft/vscode/issues/191086

- [x] macOS @aeschli
- [x] linux @TylerLeonhardt
- [x] windows @Tyriar

Complexity: 5

Authors: @rebornix @Yoyokrazy @DonJayamanne 

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23194069%0A%0A&assignees=amunger)

---

## Description

Two new settings have been added this iteration, `notebook.scrolling.revealCellBehavior` and `notebook.scrolling.anchorToFocusedCell`, which both help determine how the notebook should scroll when executing a cell and focusing the next. The default settings should be very similar to the previous behavior.

*note: the default behavior includes anchoring to different elements depending on whether the element being resized is partially off the screen which can cause [strange behavior](https://github.com/microsoft/vscode/issues/193231). I'm hoping you don't spend too much time trying to figure out what's going on with that.

## Pre-requisites - If you **don't** have python set up to run notebooks

1. ensure python is installed on your machine
2. open a workspace where you will be running tests for this TPI
3. `Create: new jupyter notebook` and run `print(1)` in a cell. 
  a. If the cell runs successfully, you're already set up, otherwise...
4. The kernel picker should open, select "Python Environments..." -> "Create Python Environment..." -> select venv or conda, and whichever version you'd like.

A virtual environment should get created in your workspace with all necessary packages installed, and the cell should run successfully.

## Testing

1. Create a notebook with several cells that generate output in a variety of ways (examples below), and has enough cells to take up multiple screen heights.
2. Execute the cells in the notebook with shift+enter which will select the next cell as they are executed.
3. Try exposing different behaviors by 
  a. shrinking the viewport
  b. scrolling to put the executing cell in different positions on the screen
  c. executing a cell that is followed by a very large cell
4. Try different combinations of `notebook.scrolling.revealCellBehavior` and/or `notebook.scrolling.anchorToFocusedCell`, specifically:

```
"notebook.scrolling.revealCellBehavior": "firstLine" / "fullCell"
"notebook.scrolling.anchorToFocusedCell": "true" / "false"
```

Do you have any solid favorites? Any confusing behaviors? Any adjustments that should be made?

#### Remove and add output (when run multiple times)

```
import time
time.sleep(3)
for i in range(29):
    print(i)
```

#### Stream in output

```
import time
for i in range(20):
    time.sleep(.5)
    print(i)
```

#### large outputs that are immediately replaced

```
for i in range(20):
    print(i)
```

**Comment by TylerLeonhardt** [comment]
So after talking to @amunger, there appears to be two mental models of how folks use SHIFT+ENTER:
* "fire off this cell and move me to the next one so I can deal with the next cell"
* "fire off this cell, but let me watch it... and queue up the next cell so I can just hit SHIFT+ENTER"

I can't say which is better because I don't feel like I use notebooks heavily enough to answer... however, I'll say this. Either `fullCell` or `firstLine` pick the favorite... and then wait a bit. If no one complains, great. If they do, then consider a modifier that influences the focus behavior to completely fit these 2 mental models.

Either way, I agree with @Tyriar that the anchoring setting seems like it should not exist and just be "auto" and smart enough.
