### ISSUE TITLE
Unsaved file - single file - debug

### ISSUE THREAD

**Issue by seanmcbreen** [Microsoft/vscode#19415]
- VSCode Version: Code - Insiders 1.9.0-insider (4265f5e35cb3ea8ba7e0cf6b14ec606b6f8647ea, 2017-01-24T10:29:13.076Z)
- OS Version: Darwin x64 16.3.0

Steps to Reproduce:

1. Open code on a new file e.g. `code-insiders foo.js`
2. Importantly this is s a non-saved file i.e. a new file
3. Add code (I have a snippet)
4. `F5` you get an error - I expected single file debug

**Comment by bpasero** [comment]
If the file does not exist on disk it is an untitled:// file in our system. Since it has an associated path, it is save to save it without user interaction (we just take the path the user wanted). Not sure about having an untitled file open without associated path (saving here would trigger a dialog).

In both cases, it is an interesting scenario to allow to debug from an untitled file.

**Comment by isidorn** [comment]
@bpasero so I can easily change the textFileService to saveAll including untitled files [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/debugService.ts#L562) 
However this uncovers some weird issue in the workbench. Namely follow Sean's steps and after the change to save all untitled files now debugging nicely starts but the workbench hides the file and it can not be seen anywhere.

Gif attached, no errors in console, notice how the program is successfully ran in the debug console
![heyben](https://cloud.githubusercontent.com/assets/1926584/22513194/b86f02e6-e89b-11e6-9e69-3442150a0a3e.gif)

**Comment by bpasero** [comment]
@isidorn maybe better to not save all but just the current active file? what about executing the command `workbench.action.files.save` and then starting debug?

**Comment by isidorn** [comment]
@bpasero executing `'workbench.action.files.save '` did the trick. 
However in the untitiled file the save dialog appears and no debug is started, this is because the promise probably does not nicely flow from the save dialog. Though the experience is still fine, when the user hits f5 for the second time he starts debugging.

Sean's use case works perfectly now

**Comment by bpasero** [comment]
Yeah, its a bit fragile. Let's see how it goes and wait for bugs.

**Comment by isidorn** [comment]
After discussions we have decided to revert this behavior since it introduced some unexpected consequences - as seen by the issues linked
