### ISSUE TITLE
Can not set breakpoint in .c files

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#194146]
Testing #194071

I have the DWARF extension installed but I can not set breakpoint in `.c` files.
Should Dwarf contribute the ability to set breakpoints in `c` files?

Or am I missing something?

**Comment by connor4312** [comment]
Which c file are you trying to set breakpoints in, and which HTML page are you on when you try to set breakpoints?

**Comment by joyceerhl** [comment]
This was for `fibonacci.c`

**Comment by connor4312** [comment]
Oh, right. We need to register what languages our extension lets us set breakpoints in... but there's an arbitrary number of languages that can compile to WebAssembly. And if we add some kind of "*" language, then that will effectively disable the per-language breakpoint ability in VS Code since js-debug is built-in.

@roblourens thoughts? For the moment I could just register common languages people are compiling to wasm (C/++, Rust, maybe Zig?)

**Comment by roblourens** [comment]
Yeah, it bugs me too, on one hand it's weird to just let breakpoints be set in every .md and .json or whatever but also you can't really enumerate all the possible bp languages in scenarios like this. I'd stick with the common known set for now.
