### ISSUE TITLE
Similar commands: "how do I save automatically" does not show Toggle Auto Save

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#194108]
Testing #194021

1. Disable copilot
2. Open command palette -> "how do I save automatically"
3. "File: Toggle Auto Save" does not show up 🐛 

![Screenshot 2023-09-26 at 11 44 37](https://github.com/microsoft/vscode/assets/1926584/f6d69b11-b967-4e09-89dc-5576e728e2c1)

**Comment by TylerLeonhardt** [comment]
This is because the only word that matches is Save and it's towards the end of the label so its score is lower than the others and we only take the top 5.

This command would work well if it had a command description that would use the word "automatically". I think that would probably boost it to the top.

**Comment by TylerLeonhardt** [comment]
In https://github.com/microsoft/vscode/pull/193937 I added the description:

> Toggle the ability to save files automatically after typing

This causes your query to only show `Toggle Auto Save` because TF-IDF is _so confident_ that you're talking about that command :) nice
