### ISSUE TITLE
Unexpected context menu

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#194131]
Testing #193991

* disable editor tabs
* select the `...` overflow menu
* it contains two configuration command (enable tabs, preview editors)
* enable tabs
* those (or related) config commands show in the context menu of the title area blank which I would also expect for non tabs. 

<img width="800" alt="image" src="https://github.com/microsoft/vscode/assets/1794099/e197c4da-55a0-4da8-bea5-f70d6a095198">

**Comment by bpasero** [comment]
@jrieken I think the main difference is that when tabs are disabled, we basically treat the entire title area like a very wide single tab:

![image](https://github.com/microsoft/vscode/assets/900690/0368f41f-e2c3-4412-8189-ac7784b577a2)

As such, there is no real "empty space" when tabs are disabled because all space is the tab. We can only show those other actions in the "..." menu.

**Comment by jrieken** [comment]
Yeah, but IMO it is still more natural to right-click into that area for similar commands (instead of having them overflow). Also in the menu are some pane management actions, like Split Up/Down/..., already present

**Comment by bpasero** [comment]
I don't have strong feelings where these commands appear, I think they are both "wrong" in the tab context menu and wrong in the "..." menu. We are essentially missing the context menu for the tab stripe.

The reason I went with the "..." menu is mainly to keep the already huge tabs menu shorter.

**Comment by bpasero** [comment]
One idea would be to simply not show them when tabs are disabled 🤷 . The one for pinned tabs on separate row does not work without tabs enabled anyway.

**Comment by jrieken** [comment]
Also fine for me
