### ISSUE TITLE
Strange lines appears sometimes

### ISSUE THREAD

**Issue by plantain-00** [Microsoft/vscode#1941]
v0.10.6 windows

not the red arrow

<img width="230" alt="default" src="https://cloud.githubusercontent.com/assets/7639395/12256756/0d55963a-b93b-11e5-9fd2-c36881dd28ba.PNG">

**Comment by isidorn** [comment]
Can you please share the file for which you see this?
What windows version?

**Comment by plantain-00** [comment]
@isidorn 
windows 10
The file is from https://github.com/Microsoft/TSJS-lib-generator/blob/master/baselines/dom.generated.d.ts

**Comment by isidorn** [comment]
I tried with the file provided and could not reproduce both for Win 10 and OS el capitan
Will reopen if more users see this issue

**Comment by plantain-00** [comment]
a gif

![1](https://cloud.githubusercontent.com/assets/7639395/12260926/fea107c8-b958-11e5-9f79-6ca5d2484b3f.gif)

**Comment by isidorn** [comment]
Thanks!
@alexandrudima can you please also try to repro?

**Comment by alexandrudima** [comment]
@plantain-00 That looks most annoying, sorry about that. I cannot repro either. To help us track this down, can you please try the following:

Here I'm doing it: http://recordit.co/MVsleuKLan or gif: http://g.recordit.co/MVsleuKLan.gif

* `F1` > `Developer: Toggle Developer Tools`
* Select magnifying glass (Inspect Element) and click somewhere on the text in the editor
* Collapse the `<div linenumber="...` and select the parent `<div class="view-lines" ...`
* Hit `Escape`
* Go to the Rendering tab
* Check Show paint rectangles and Show composited layer borders
* Scroll


The reason I'm asking is because at one point in long files (when the accumulated line heights get to more than 500k pixels), we wrap the positions, so you might be hitting that case -- the `top` properties changing on line divs should show if that is the case. In my example, I am scrolling intentionally around that limit.

If that is not the case, can you please check if you see any correlation between the black lines and the composited layer borders? (the grid lines appearing).

Do you use any Windows zoom? What version of Windows are you on? Are you zoomed in in VSCode (from the View menu) or from the settings? And finally, does this repro if you run Code.exe from the command line with the ` --disable-gpu` flag?

**Comment by plantain-00** [comment]
@alexandrudima I tried these:

1. If I opened `Developer: Toggle Developer Tools`, I can not repro the black lines any more, and if closed the tool window, I can repro the black lines again.

2. If I opened `Developer: Toggle Developer Tools` and Check Show paint rectangles and Show composited layer borders, I can see the lines, but actually invisible if didn't check the two options.
<img width="372" alt="1" src="https://cloud.githubusercontent.com/assets/7639395/12263879/921a6274-b96d-11e5-845e-b381d4a4ef03.PNG">
<img width="254" alt="2" src="https://cloud.githubusercontent.com/assets/7639395/12263861/74ad27a8-b96d-11e5-99b9-8b50d65e8d43.PNG">
<img width="228" alt="3" src="https://cloud.githubusercontent.com/assets/7639395/12263862/76ae2778-b96d-11e5-8d80-7f6e5f16ded8.PNG">

3. I didn't follow the `the top properties` part

4. It's a Windows 10, It's 150% in `Settings->System->Display`

5. I forget whether I zoomed in in VSCode, but now, if clicked `zoomed out`, it doesn't change the view, I can repro the black lines, then if I clicked `zoomed in`, the view changes, and I cannot repro the black lines. Then if I clicked `zoomed in` again, I can repro the black lines again.

**Comment by plantain-00** [comment]
6. My vscode settings just changed `typescript.tsdk`

7. I cannot repro the black lines when I run `code --disable-gpu`

**Comment by alexandrudima** [comment]
@plantain-00 Thank you for trying all the steps. I think the Windows zoom at 150% might be the trigger for this issue.

Most likely, it is an upstream Chromium issue (similar to #1896), but in this case besides blurry text there is also an issue around composited layer borders. My best guess is that the first/last pixel row of some composited layers are all zeroed (hence the black).

In the meantime, please work-around by using `--disable-gpu`.
