### ISSUE TITLE
Dragging an editor group into the pinned tab row does not pin the tabs

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#194199]
Testing #193991

Have a group on the left with pinned and non-pinned tabs. Have a group on the right with any number of non-pinned tabs. Move the entire right group (by dragging from empty space in tabs bar) into the empty space of the pinned tabs bar.

The result is that the editors are not pinned, when they should be.

![Recording 2023-09-26 at 20 16 20](https://github.com/microsoft/vscode/assets/900690/70ae0b21-864b-4a02-b9ac-f92d65b39c33)

**Comment by benibenj** [comment]
This is intentional. We keep the state of the tabs when merging groups. Imagine having pinned and unpinned tabs in the dragged group, and pulling it into the pinned tab bar. All pinned tabs will stay pinned, but you don't want to pin the unpinned tabs then.
What if you only have a pinned tab bar in the target group? Then you will always have to pin all the tabs.

I think the behaviour is correct, however, one potential change I considered was to highlight both tab bar containers when dragging an editor group over one of the tab bar containers.

**Comment by bpasero** [comment]
Yeah you bring up a good point, so lets leave it as it is. Your suggestion makes sense to me, but not high prio.

**Comment by benibenj** [comment]
This is the only change I could imagine.  This change probably relies on the debt work we do here: #193690

![Image](https://github.com/microsoft/vscode/assets/44439583/35846605-8f84-4eb3-b06b-6f8c0765f6d4)

Theoretically we could also just highlight one container if there is only un/pinned tabs, however, this will create it's own complications.

**Comment by benibenj** [comment]
As there sometimes is only one tab bar with just pinned tabs, this makes it much harder to make this a nice experience without users accidentally pinning/unpinning all tabs. I haven't seen any community members mention this as a problem, so closing for now.
