### ISSUE TITLE
Autocomplete / Intellisense stopped working

### ISSUE THREAD

**Issue by sryze** [Microsoft/vscode#19422]
After some time JavaScript autocomplete completely stopped working for my project. It worked at some point but then it stopped and I didn't notice it until a while ago.

However, if I create a new project with one file and type "console.", method suggestions pop up, i.e. autocomplete works in a new project.

I tried deleting the .vscode/ folder, and also typings/, jsconfig.json, etc, but it didn't help.

I think it might be caused by large amounts of JS code in third-party libraries. The project uses Ionic (version 1, no TypeScript), so there are a lot of code in dependencies as well as a bunch of other stuff in node_modules/.

VS Code version: 1.8.1
OS: macOS Sierra 10.12.3

**Comment by mousetraps** [comment]
Thanks for reporting! A few Qs to help narrow it down:
* When you say "completely stopped working".. what happens if you press ctrl+space - does a popup appear at all? (and could you take a screenshot?)
* For large projects, we'll often automatically disable IntelliSense. Do you see a green "configure excludes" button in the bottom right hand corner? This'll allow you to specify any large folders you think might be causing the issue.
![image](https://cloud.githubusercontent.com/assets/762848/22353003/44ab2438-e3d3-11e6-8b2b-76e947b2ca39.png)

**Comment by sryze** [comment]
* Yes, the popup appears but all it shows is "Loading..." and seems to freeze there (I waited for like 5 minutes)

![vscode-autocomplete-loading](https://cloud.githubusercontent.com/assets/4525736/22358305/25a58ee4-e468-11e6-9c59-8d7651a9351b.png)

* Configuring excludes did help indeed! Thanks! Here is my excludes in `jsconfig.json` in case anyone using Ionic comes across this:

```
{
  "exclude": [
    "node_modules",
    "platforms",
    "plugins",
    "www/lib"
  ]
}
```

I'll check this on my work Mac today too, it everything is OK I'll close this issue. 

Thank you!

**Comment by sryze** [comment]
Could you guys add an error or something if VS Code detects that there are too many files and autocomplete might fail?  Like a really annoying popup that opens every time someone opens their project, until they add an exclude to their `jsconfig.json` (even if empty) to acknowledge.
