### ISSUE TITLE
vscode - scss “cube” suggestions

### ISSUE THREAD

**Issue by esaramago** [Microsoft/vscode#19429]
- VSCode Version: 1.8.1
- OS Version: Windows 8

Steps to Reproduce:
In scss files, there are some suggestions with a "cube" as icon.
![jkcoe](https://cloud.githubusercontent.com/assets/1698166/22328585/fcc36edc-e3b4-11e6-88c3-0e06da3acb70.jpg)

I'm not sure, but I think those are mixins and I don't know where this comes from.

**Comment by mousetraps** [comment]
Hey @esaramago, thanks for reporting! The "cube" icon denotes a function/method, and this out this is actually the expected behavior, as SASS includes many built-in functions, so we want to provide completions for those - see http://sass-lang.com/documentation/Sass/Script/Functions.html

Hope that helps!

**Comment by esaramago** [comment]
Thanks for the answer!
Anyway, I think it doesn't make sense for the property position, for example, to have the functions desaturate or fade-in as value.
Could this autocomplete be smarter?
