### ISSUE TITLE
Consider changing the bold headers in the quick fix

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#194223]
Testing #194072

The quick fix text is the only bold text on the screen and stands out a lot:

![Image](https://github.com/microsoft/vscode/assets/2193314/5cd4fbc9-00b3-4079-b0fc-605b15f106aa)

**Comment by justschen** [comment]
Quickly fixed with comparison:

<img width="1160" alt="Screenshot 2023-09-29 at 11 45 54 AM" src="https://github.com/microsoft/vscode/assets/54879025/7ec8fd12-f009-4dcd-aafb-7fba2a9525d8">

vs.

<img width="1213" alt="Screenshot 2023-09-29 at 11 45 05 AM" src="https://github.com/microsoft/vscode/assets/54879025/e2d2b32a-8a23-4c10-8774-d707338738cd">

Any thoughts on this? Personally, I do like that it's a bit cleaner but wonder if the color of the header title blends in too much to label contents.

**Comment by Tyriar** [comment]
@daviddossett?

**Comment by daviddossett** [comment]
We do use semibold headers in other areas like this. Would prefer to align to that if possible.

<img width="273" alt="CleanShot 2023-09-29 at 11 56 27@2x" src="https://github.com/microsoft/vscode/assets/25163139/bf1b8329-d5c0-49d3-ba85-3c31079a5644">

**Comment by justschen** [comment]
Gotcha. We had convos about aligning the colors as well, I'll double check to make sure these are the same ones
