### ISSUE TITLE
Continue on for comments doesn't work sometimes

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#194288]
Testing #193104

To repro, follow the steps in the above test.

**Comment by alexr00** [comment]
@joyceerhl I'm seeing an unexpected URI in the object that I get from the storage service when I try to restore comments:

<img width="373" alt="image" src="https://github.com/microsoft/vscode/assets/38270282/1ec49069-5259-4628-9dc9-5250d7bfacf8">

The two with the shorter URI restore, because that URI matches the URI that of the files "locally" (it's actually GitHub Repositories, but it's the machine I'm trying to restore on).

**Comment by alexr00** [comment]
On the machine I'm storing the comment from, the URI doesn't have that long authority:
![image](https://github.com/microsoft/vscode/assets/38270282/9b24b5b5-f150-4025-88c8-f36ec1ae55c6)

**Comment by alexr00** [comment]
I'm seeing this URI difference when trying to restore across two actual different machines using VS Code insiders (desktop) on both.

**Comment by joyceerhl** [comment]
Hm, I cannot repro because comments aren't showing up at all for me in web https://insiders.vscode.dev/github/microsoft/vscode/pull/193812 
<img width="1574" alt="image" src="https://github.com/microsoft/vscode/assets/30305945/b91ed9d2-5ec2-4fb3-be8f-a21e4992256c">

**Comment by alexr00** [comment]
@joyceerhl I'm seeing comments show up as expected for that PR. Can you share output from GitHub Pull Request and see if there are any errors in the console?

**Comment by joyceerhl** [comment]
OK, comments show up properly for that PR now. I'm still running into some issues though:
1. I had to enable `comments.experimentalContinueOn` first, otherwise no state was getting stored: https://github.com/microsoft/vscode/blob/d00c196d89ba16c27d1522f70c0255be2a56fc3a/src/vs/workbench/contrib/comments/common/commentsConfiguration.ts#L12
2. I see the following comment state getting stored for the above PR, the first entry seems like stale state since it's not coming from the current workspace. Do you have insight into where it comes from?
```
[
  {
    owner: 'Hide launcher on Run and Debug title bar when debugging-GitHub.vscode-pull-request-github',
    uri: {
      '$mid': 1,
      fsPath: 'c:\\Users\\huer\\Source\\vscode\\src\\vs\\workbench\\contrib\\debug\\browser\\debug.contribution.ts',        
      _sep: 1,
      external: 'file:///c%3A/Users/huer/Source/vscode/src/vs/workbench/contrib/debug/browser/debug.contribution.ts',       
      path: '/c:/Users/huer/Source/vscode/src/vs/workbench/contrib/debug/browser/debug.contribution.ts',
      scheme: 'file'
    },
    range: {
      startLineNumber: 455,
      startColumn: 1,
      endLineNumber: 455,
      endColumn: 1
    },
    body: 'foo'
  },
  {
    owner: 'Hide launcher on Run and Debug title bar when debugging-GitHub.vscode-pull-request-github',
    uri: {
      '$mid': 1,
      fsPath: '\\microsoft\\vscode\\src\\vs\\workbench\\contrib\\debug\\browser\\debug.contribution.ts',
      _sep: 1,
      external: 'vscode-vfs://github%2B7b2276223a312c22726566223a7b2274797065223a332c226964223a22313933383132227d7d/microsoft/vscode/src/vs/workbench/contrib/debug/browser/debug.contribution.ts',
      path: '/microsoft/vscode/src/vs/workbench/contrib/debug/browser/debug.contribution.ts',
      scheme: 'vscode-vfs',
      authority: 'github+7b2276223a312c22726566223a7b2274797065223a332c226964223a22313933383132227d7d'
    },
    range: {
      startLineNumber: 453,
      startColumn: 1,
      endLineNumber: 453,
      endColumn: 1
    },
    body: 'foooo'
  }
]
```
3. If I set a breakpoint [here](https://github.com/microsoft/vscode/blob/d00c196d89ba16c27d1522f70c0255be2a56fc3a/src/vs/workbench/contrib/comments/browser/commentService.ts#L176) I don't see it get hit after we call `storeAll` with the restored value, i.e. the `onDidChangeValue` event listener that comments registers doesn't fire, so it doesn't update with the restored comments data, will keep investigating why that might be the case
