### ISSUE TITLE
Question on activating yellow lightbulbs

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#194209]
Testing #194072

I attached a picture below of a small TypeScript file with some underlined misspelled variables.
I notice that a yellow lightbulb shows up sometimes, even on a line with misspelled variables.
When I press `ctrl+.`, I get a suggestion to fix a misspelled variable.
When I move my cursor over a misspelled variable, I notice the lightbulb turns blue.

I wonder how to show the yellow lightbulb context menu contents while the `editor.codeActionWidget.includeNearbyQuickfixes` setting is enabled?

![Small TypeScript file with some underlined misspelled variables. There's also a yellow lightbulb on the left of one line](https://github.com/microsoft/vscode/assets/7199958/13f011fb-f5b8-403e-a117-458c6ac0ec34)

**Comment by justschen** [comment]
Can you check if the behavior is the same when it's disabled?

atm I haven't added support for inline fixes for the lightbulb widget, and it'll only provide quickfixes on selections or positions that have fixable errors. 

There is an interesting thing with the lightbulb position however. It shouldn't be covering text like that....

**Comment by rzhao271** [comment]
`Ctrl+.` pulls up the context menu for the yellow lightbulb in that case
![Yellow lightbulb along with the context menu for that lightbulb, showing items such as "Move to a new file"](https://github.com/microsoft/vscode/assets/7199958/a6727ffd-d3d6-478c-8ddc-4a9a26f5ba49)

**Comment by justschen** [comment]
The contents should still be displayed (`Move to a new File` and `Move to file`) when the setting is enabled. They'll just be under a different section:

<img width="349" alt="Screenshot 2023-09-26 at 12 47 56 PM" src="https://github.com/microsoft/vscode/assets/54879025/a49ff9d1-5d78-46e5-9f46-fdbc107901fc">

However, there won't be a menu that has ONLY those options (since the lighbulb and quickfix from `ctrl + .` now use different models) if that makes sense.
