### ISSUE TITLE
scode cpptools

### ISSUE THREAD

**Issue by yamcenutzer** [Microsoft/vscode#19432]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

**Comment by mousetraps** [comment]
@yamcenutzer - Hey @yamcenutzer, thanks for reaching out! Unfortunately I'm still brushing up on my mind-reading abilities, and there's not enough info provided here for me to help you out. Are you running into an issue? Is this a feature request?

In any case, you mention that this is related to the vscode cpptools extension, rather than VS Code itself, so I'm going to close this issue, and recommend you head over there instead. https://github.com/Microsoft/vscode-cpptools

**Comment by yamcenutzer** [comment]
how did this even get here? did I press some magic button in vscode? Never intended this, sorry.
I'm already talking to the cpp guys and have aqn open issue there.
