### ISSUE TITLE
Add support to edit the php executable path as a non sharable workspace setting

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#19436]
- VSCode Version: 1.9
- OS Version: Window

It should also provide support to migrate an existing workspace setting.

**Comment by chrmarti** [comment]
When starting with a new user data dir on a workspace with that property set, I first get a message and later this question:
![screen shot 2017-01-27 at 1 50 28 pm](https://cloud.githubusercontent.com/assets/9205389/22389155/1f41dec8-e499-11e6-98f3-fc299b688b63.png)

At the time this question pops up, I might have forgotten that this might have something to do with workspace settings. I think is would make sense to mention that context again as part of the question.

Reopening since this might affect the original goal of the issue.

**Comment by isidorn** [comment]
New feature request -> feb

**Comment by dbaeumer** [comment]
@chrmarti I change the flow. You now see a message before the input dialog asking you if you want to reuse the previous setting. Please re-verifiy

**Comment by dbaeumer** [comment]
Is on master and release/1.9

**Comment by chrmarti** [comment]
The message reads "This Workspace contains settings that can only be set in User Settings. (php.validate.executablePath)" which doesn't seem to be true anymore with #19624.

**Comment by chrmarti** [comment]
Wrong build, the latest does not have this message anymore. Verified.
