### ISSUE TITLE
Dismiss Parent Directories in Search Context Menu

### ISSUE THREAD

**Issue by sedghi** [microsoft/vscode#194452]
In "Search", I can write click and Dismiss one file, but it would be much better If can choose parent directories of that file to be dismissed in the context menu as well
Right now 

![image](https://github.com/microsoft/vscode/assets/7490180/5f6d9212-ecd2-453e-b45c-9ce2ffcfbbd0)

Feature Request (parents, to some configurable level)

![CleanShot 2023-09-28 at 21 15 15](https://github.com/microsoft/vscode/assets/7490180/c6c59fb1-0b9d-4cd1-8bf3-6c3e52f459ad)

**Comment by andreamah** [comment]
This might not be the best UI for this, since the list would 
1. Be growing by how nested the file could be.
2. Easily look like a wall of text.

To easily collapse things that are under the same directory, I'd advise to browse in tree mode from the search action buttons:
<img width="131" alt="image" src="https://github.com/microsoft/vscode/assets/31675041/d4c51234-c5e3-46f8-8db6-095bffa4530c">

Otherwise, I'm open if there's a better way (UI-wise) to dismiss by directory.

**Comment by sedghi** [comment]
I completely understand your concerns. I frequently find myself needing to utilize this missing feature repeatedly throughout the day.

One possible solution is to restrict the number of parent levels to either 2 or 3, as this is typically the situation in these scenarios.

**Comment by andreamah** [comment]
That's a reasonable suggestion, but it feels a little like a small patch solution to a bigger problem where people want to dismiss whole directories. I still believe that viewing results in the tree view and dismissing the folders from there is the best experience if you want to do something like this currently.

<img width="274" alt="image" src="https://github.com/microsoft/vscode/assets/31675041/3039f2ac-7b6d-4273-950a-1d4f8b479ca3">

**Comment by sedghi** [comment]
I think what you proposed (Tree) makes sense so I will close this comment
