### ISSUE TITLE
Zombie extension hosts running at 100%

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#194477]
* over the last week I have seen zombie processes running at full CPU load
* when trying to debug them (via SIGUSR1) they die
* @deepak1556 analysed a crash dump and sees that this is because the EH is already in the process of shutting down
* the previous point matches the observation that no window reports its EH as having crashed

<img width="1290" alt="Screenshot 2023-09-29 at 13 31 34" src="https://github.com/microsoft/vscode/assets/1794099/991acf1f-a254-4e94-a2d1-a9d18342e6b3">

**Comment by deepak1556** [comment]
Can you take a process sample from the OS activity monitor, I hope the native stack can give a clue to what is happening.

**Comment by jrieken** [comment]
Just happening. This is the command line of such an EH

```
99701   ??  R    299:41.47 /Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper (Plugin).app/Contents/MacOS/Code - Insiders Helper (Plugin) --type=utility --utility-sub-type=node.mojom.NodeService --lang=en-GB --service-sandbox-type=none --dns-result-order=ipv4first --inspect-port=0 --user-data-dir=/Users/jrieken/Library/Application Support/Code - Insiders --standard-schemes=vscode-webview,vscode-file --enable-sandbox --secure-schemes=vscode-webview,vscode-file --bypasscsp-schemes --cors-schemes=vscode-webview,vscode-file --fetch-schemes=vscode-webview,vscode-file --service-worker-schemes=vscode-webview --streaming-schemes --shared-files --field-trial-handle=1718379636,r,8003835085444679389,18150943907601750289,262144 --disable-features=CalculateNativeWinOcclusion,SpareRendererForSitePerProcess
99704   ??  S      0:04.19 /Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper (Plugin).app/Contents/MacOS/Code - Insiders Helper (Plugin) --ms-enable-electron-run-as-node /Users/jrieken/.vscode-insiders/extensions/kisstkondoros.vscode-codemetrics-1.26.1/dist/server.js --node-ipc --clientProcessId=99701
99706   ??  S      0:03.39 /Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper (Plugin).app/Contents/MacOS/Code - Insiders Helper (Plugin) --ms-enable-electron-run-as-node /Users/jrieken/.vscode-insiders/extensions/kisstkondoros.vscode-gutter-preview-0.30.0/dist/server.js --node-ipc --clientProcessId=99701
99750   ??  S      0:01.17 /Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper (Plugin).app/Contents/MacOS/Code - Insiders Helper (Plugin) --ms-enable-electron-run-as-node /Users/jrieken/.vscode-insiders/extensions/ms-vscode.anycode-0.0.72/dist/anycode.server.node.js --node-ipc --clientProcessId=99701
16791 s034  S+     0:00.00 grep 99701
```

**Comment by jrieken** [comment]
This the process sample

[Uploading EH-spin-sample.txt…]()

**Comment by jrieken** [comment]
@connor4312 Not sure about the `--inspect-port=0` part. Does this mean we run the EH under development or not?

**Comment by connor4312** [comment]
That means that EH is being debugged, though you'll need to [find the port it's listening on](https://unix.stackexchange.com/questions/157823/list-ports-a-process-pid-is-listening-on-preferably-using-iproute2-tools) if you want to attach to it. Then you could grab a performance profile using the edge/chrome devtools on edge://inspect, or by attaching to that using an attach-type launch config VS Code and using the "take performance profile" command.

**Comment by connor4312** [comment]
It looks like we set that for all local EH process launches. Just having inspect-port doesn't put the process in debug mode.

What you can do is use the "Debug: Attach to Node.js Process" command and select that process. This will fail, since the debugger won't then know what port it's listening on (if --inspect-port isn't given in the args, it always listens on 9229, and js-debug assumes that is what happens). But, then you can [find it](https://unix.stackexchange.com/questions/157823/list-ports-a-process-pid-is-listening-on-preferably-using-iproute2-tools). AFter doing so you could grab a performance profile using the edge/chrome devtools on edge://inspect, or by attaching to that using an attach-type launch config VS Code and using the "take performance profile" command -- if the spin sample you recorded above isn't enough for Deepak to figure out what's going on.

**Comment by jrieken** [comment]
> What you can do is use the "Debug: Attach to Node.js Process" command and select that process.

Does that use SIGUSR1? Asking cos I have tried that first and sending the signal kills the process. From the crash dumps we do know that the process already was shutting down

**Comment by deepak1556** [comment]
Attaching the symbolicated sample [EH-spin-sample-symbolicated.txt](https://github.com/microsoft/vscode/files/12801842/EH-spin-sample-symbolicated.txt)

Going from the top, `electron::NodeService::~NodeService()` indicates the EH process is already in the shutdown phase and  has started to destroy the [Node.js environment](https://github.com/electron/electron/blob/b5646778e931f7901d8fa94337c7eed8a672fd85/shell/browser/javascript_environment.cc#L346) `node::FreeEnvironment(node::Environment*)` . At this point, connecting via a debugger is not possible since the agent host will stop receiving connections due to the following [check](https://github.com/nodejs/node/blob/55ff64001a372e31813f801fd7da86d015a7b4db/src/inspector_agent.cc#L721-L724), so we cannot get perf profile from these processes.

Moving further down most of the sample time is spent in `node::NodePlatform::DrainTasks` which [happens before](https://github.com/nodejs/node/blob/a94966ffc114e831d4a917a97f9958d3385ab6f7/src/api/environment.cc#L439) the environment gets deleted, this flushes the pending tasks in the libuv event loop but one thing to note is that entering JS via these tasks is not allowed due to the [scope](https://github.com/nodejs/node/blob/a94966ffc114e831d4a917a97f9958d3385ab6f7/src/api/environment.cc#L418-L419). But there are GC tasks being executed `v8::internal::FinalizationRegistryCleanupTask::RunInternal` and `v8::internal::Heap::CollectGarbage` which can enter JS. I think the error calls ``node::errors::TriggerUncaughtException`` are from these callsites eventually leading to [node::OnFatalError](https://github.com/nodejs/node/blob/v18.15.0/src/node_errors.cc#L476-L496). At this point, I expect the process to abort and the main process should be able to reap the utility process but that is not happening.

There is another data point looking back at the screenshot from https://github.com/microsoft/vscode/issues/194477#issue-1919108667, the zombie EH processes are titled `utility-process` and not `extensionHost` in the process explorer. We resolve the pids to respective titles based on a map maintained in the main process, the process explorer gets it periodically via the following [ipc]( https://github.com/microsoft/vscode/blob/e6fb75347302315664c2bb8e00feb0a75c84a3b7/src/vs/code/electron-sandbox/processExplorer/processExplorerMain.ts#L246-L252) and the utility process related values are populated from [here](https://github.com/microsoft/vscode/blob/e6fb75347302315664c2bb8e00feb0a75c84a3b7/src/vs/platform/issue/electron-main/issueMainService.ts#L133-L135). We default to [utility-process](https://github.com/microsoft/vscode/blob/e6fb75347302315664c2bb8e00feb0a75c84a3b7/src/vs/base/node/ps.ts#L74-L88) when the pid map no longer has an entry for the process which can only happen when [onDidExitOrCrashOrKill](https://github.com/microsoft/vscode/blob/e6fb75347302315664c2bb8e00feb0a75c84a3b7/src/vs/platform/utilityProcess/electron-main/utilityProcess.ts#L415-L421) got invoked which inturn suggests that the main process did receive an exit or crash signal from these EH hosts. @jrieken can you check the main process logs next time if it has any of the following entries for the corresponding zombie EH pid to validate this data
* https://github.com/microsoft/vscode/blob/e6fb75347302315664c2bb8e00feb0a75c84a3b7/src/vs/platform/utilityProcess/electron-main/utilityProcess.ts#L310
* https://github.com/microsoft/vscode/blob/e6fb75347302315664c2bb8e00feb0a75c84a3b7/src/vs/platform/utilityProcess/electron-main/utilityProcess.ts#L322
* https://github.com/microsoft/vscode/blob/e6fb75347302315664c2bb8e00feb0a75c84a3b7/src/vs/platform/utilityProcess/electron-main/utilityProcess.ts#L408

**Comment by deepak1556** [comment]
I attempted to setup a similar flow based on the stack with base Electron app but the utility process are cleaned up as expected. I can make a change in the destruction phase of the utility process to signal termination of isolate so that tasks which require to enter JS will not do so and I hope that resolves the long running draintask.

I won't be able to make a new insiders build with this change until I am back from vacation but I can provide a custom electron build for local testing with OSS. @jrieken would that help to validate incase you face similar issue with OSS as well ?

**Comment by connor4312** [comment]
> Does that use SIGUSR1? Asking cos I have tried that first and sending the signal kills the process. From the crash dumps we do know that the process already was shutting down

Ah, my bad, skimmed over that part. Disregard.

(Yes, it sends SIGUSR1 on unix)

**Comment by jrieken** [comment]
> 2023-10-06 10:26:53.084 [info] Extension host with pid 19510 exited with code: 0, signal: unknown.

I am seeing this for `PID-19510` which is currently spinning forever

**Comment by nzhl** [comment]
i think i have the same issue

<img width="963" alt="CleanShot 2023-10-09 at 19 46 49@2x" src="https://github.com/microsoft/vscode/assets/16397293/615ca42b-870b-422e-b302-643187ca2f92">

**Comment by ClockRide** [comment]
Having the exact same issue. utility-process is running at 100% all the time on M1 Max, very annoying.

**Comment by taoky** [comment]
[output.txt](https://github.com/microsoft/vscode/files/13055986/output.txt)

Manually sampling with eu-stack running every second, for one minute.

**Comment by sebdanielsson** [comment]
Sorry if I'm hijacking the thread but would uninstalling Node and installing Bun solve this problem? Doesn't sound like it's a VSCode bug, right?

**Comment by deepak1556** [comment]
Thanks for the logs @taoky , the stack does look related. I wouldn't be surprised if the issue is also present on Linux since the shutdown path is same for both.

**Comment by taoky** [comment]
Checked log and it looks weird.

`/home/username/.config/Code/logs/20231022T205712/main.log`:

```
2023-10-24 03:44:26.258 [info] Extension host with pid 1331811 exited with code: 0, signal: unknown.
```
However, PID 1331811 still exists and is running at 100%.

**Comment by taoky** [comment]
> Checked log and it looks weird.

Another hang process today with log:

```
> rg 1706525
20231022T205712/window9/exthost/exthost.log
1:2023-10-24 15:40:45.945 [info] Extension host with pid 1706525 started
326:2023-10-24 16:00:07.408 [info] Extension host with pid 1706525 exiting with code 0

20231022T205712/main.log
17:2023-10-24 16:00:07.409 [info] Extension host with pid 1706525 exited with code: 0, signal: unknown.
```

"Extension host with pid 1706525 started" => https://github.com/microsoft/vscode/blob/a8b7239d0311d4915b57c837972baf4b01394491/src/vs/workbench/api/common/extensionHostMain.ts#L171

"Extension host with pid 1706525 exiting with code 0" => https://github.com/microsoft/vscode/blob/a8b7239d0311d4915b57c837972baf4b01394491/src/vs/workbench/api/common/extHostExtensionService.ts#L271

"Extension host with pid 1706525 exited with code: 0, signal: unknown." => https://github.com/microsoft/vscode/blob/a8b7239d0311d4915b57c837972baf4b01394491/src/vs/platform/extensions/electron-main/extensionHostStarter.ts#L76

**Comment by fenvalle** [comment]
Is there any temp workaround? any script or bash command that we can run to identify and kill those pid? I am interested to do it manually, because i have a M2 and i am rebooting my macbook after some hours because get soooo slow

**Comment by jrieken** [comment]
@NullEnt1ty @fenvalle @taoky @Maktel @ClockRide @nzhl 

Please help by posting the list of installed extensions. I am looking for similarities between our setups as this is possibly caused by an extension.

This is my list

```
amodio.tsl-problem-matcher
chrisdias.vscode-opennewinstance
connor4312.css-theme-completions
connor4312.esbuild-problem-matchers
dbaeumer.vscode-eslint
dtsvet.vscode-wasm
eamodio.gitlens
esbenp.prettier-vscode
GitHub.codespaces
GitHub.copilot
GitHub.copilot-chat
GitHub.github-vscode-theme
GitHub.remotehub
GitHub.vscode-pull-request-github
ipatalas.vscode-postfix-ts
jrieken.browser-links
jrieken.esm-helper
jrieken.references-plusplus
jrieken.regex-notebook
jrieken.vscode-pr-pinger
jrieken.vscode-tree-sitter-query
kisstkondoros.vscode-codemetrics
kisstkondoros.vscode-gutter-preview
meganrogge.template-string-converter
ms-python.python
ms-python.vscode-pylance
ms-vscode-remote.remote-containers
ms-vscode-remote.remote-ssh
ms-vscode-remote.remote-ssh-edit
ms-vscode.anycode
ms-vscode.anycode-c-sharp
ms-vscode.anycode-cpp
ms-vscode.anycode-go
ms-vscode.anycode-java
ms-vscode.anycode-kotlin
ms-vscode.anycode-php
ms-vscode.anycode-python
ms-vscode.anycode-rust
ms-vscode.anycode-typescript
ms-vscode.hexeditor
ms-vscode.remote-explorer
ms-vscode.remote-repositories
ms-vscode.remote-server
ms-vscode.vscode-github-issue-notebooks
ms-vscode.vscode-markdown-notebook
ms-vscode.vscode-selfhost-test-provider
ms-vscode.vscode-speech
ms-vscode.vscode-typescript-next
rust-lang.rust-analyzer
wayou.vscode-todo-highlight
```

To get this list run `code --list-extensions` or `code-insiders --list-extensions`. Please do the same and post your results here. Thanks

**Comment by taoky** [comment]
```
> code --list-extensions
aaronduino.chisel
bbenoist.Nix
coolbear.systemd-unit-file
cschlosser.doxdocgen
eamodio.gitlens
esbenp.prettier-vscode
GitHub.copilot
GitHub.copilot-chat
GitHub.copilot-labs
golang.go
haskell.haskell
James-Yu.latex-workshop
jeff-hykin.better-cpp-syntax
justusadam.language-haskell
kokororin.vscode-phpfmt
llvm-vs-code-extensions.vscode-clangd
llvm-vs-code-extensions.vscode-mlir
luniclynx.bison
luniclynx.lex
ms-azuretools.vscode-docker
ms-python.isort
ms-python.python
ms-python.vscode-pylance
ms-toolsai.jupyter
ms-toolsai.jupyter-keymap
ms-toolsai.jupyter-renderers
ms-toolsai.vscode-jupyter-cell-tags
ms-toolsai.vscode-jupyter-slideshow
ms-vscode-remote.remote-ssh
ms-vscode-remote.remote-ssh-edit
ms-vscode.cmake-tools
ms-vscode.cpptools
ms-vscode.cpptools-extension-pack
ms-vscode.cpptools-themes
ms-vscode.hexeditor
ms-vscode.live-server
ms-vscode.remote-explorer
ms-vsliveshare.vsliveshare
ms-vsliveshare.vsliveshare-pack
nvarner.typst-lsp
prince781.vala
rust-lang.rust-analyzer
sswg.swift-lang
twxs.cmake
vadimcn.vscode-lldb
Vue.volar
wholroyd.jinja
```

**Comment by sebdanielsson** [comment]
```
1Password.op-vscode
bierner.github-markdown-preview
bierner.markdown-checkbox
bierner.markdown-emoji
bierner.markdown-footnotes
bierner.markdown-mermaid
bierner.markdown-yaml-preamble
bradlc.vscode-tailwindcss
Brigit.devcontainer-image-convert
charliermarsh.ruff
christian-kohler.npm-intellisense
DavidAnson.vscode-markdownlint
dbaeumer.vscode-eslint
denoland.vscode-deno
esbenp.prettier-vscode
GitHub.codespaces
GitHub.copilot
GitHub.copilot-chat
GitHub.remotehub
github.vscode-github-actions
GitHub.vscode-pull-request-github
GrapeCity.gc-excelviewer
hashicorp.terraform
hediet.vscode-drawio
jakeboone02.cypher-query-language
mikestead.dotenv
ms-azuretools.vscode-docker
ms-dotnettools.vscode-dotnet-runtime
ms-kubernetes-tools.vscode-kubernetes-tools
ms-python.autopep8
ms-python.isort
ms-python.python
ms-python.vscode-pylance
ms-toolsai.jupyter
ms-toolsai.jupyter-keymap
ms-toolsai.jupyter-renderers
ms-toolsai.vscode-jupyter-cell-tags
ms-toolsai.vscode-jupyter-slideshow
ms-vscode-remote.remote-containers
ms-vscode-remote.remote-ssh
ms-vscode-remote.remote-ssh-edit
ms-vscode-remote.vscode-remote-extensionpack
ms-vscode.azure-repos
ms-vscode.cmake-tools
ms-vscode.cpptools
ms-vscode.cpptools-extension-pack
ms-vscode.makefile-tools
ms-vscode.remote-explorer
ms-vscode.remote-repositories
ms-vscode.remote-server
ms-vscode.test-adapter-converter
ms-vscode.vscode-markdown-notebook
ms-vscode.wordcount
ms-vsliveshare.vsliveshare
mtxr.sqltools
mtxr.sqltools-driver-pg
Oracle.oracledevtools
ParallelsDesktop.parallels-desktop
pomdtr.excalidraw-editor
redhat.ansible
redhat.vscode-yaml
ritwickdey.LiveServer
snyk-security.snyk-vulnerability-scanner
Tailscale.vscode-tailscale
timonwong.shellcheck
tomoki1207.pdf
twxs.cmake
Tyriar.sort-lines
VisualStudioExptTeam.intellicode-api-usage-examples
VisualStudioExptTeam.vscodeintellicode
VisualStudioExptTeam.vscodeintellicode-completions
vscode-icons-team.vscode-icons
waderyan.gitblame
```

**Comment by jrieken** [comment]
Thanks everyone. Looks like the intersection is 

```
esbenp.prettier-vscode
GitHub.copilot
GitHub.copilot-chat
```

**Comment by NullEnt1ty** [comment]
@jrieken 

> Thanks everyone. Looks like the intersection is
> 
> ```
> esbenp.prettier-vscode
> GitHub.copilot
> GitHub.copilot-chat
> ```

Yep, I'm using those extensions too. Here's the full list:

```
Armitxes.sqf
astro-build.astro-vscode
bungcip.better-toml
CodeQue.codeque
darkriszty.markdown-table-prettify
dbaeumer.vscode-eslint
DotJoshJohnson.xml
eamodio.gitlens
EditorConfig.EditorConfig
emmanuelbeziat.vscode-great-icons
esbenp.prettier-vscode
GitHub.copilot
GitHub.remotehub
goz3rr.vscode-glualint
KatjanaKosic.vscode-json5
MS-CEINTL.vscode-language-pack-de
ms-python.isort
ms-python.python
ms-python.vscode-pylance
ms-vscode-remote.remote-ssh
ms-vscode-remote.remote-ssh-edit
ms-vscode-remote.remote-wsl
ms-vscode.azure-repos
ms-vscode.hexeditor
ms-vscode.remote-explorer
ms-vscode.remote-repositories
ms-vsliveshare.vsliveshare
nhoizey.gremlins
nidu.copy-json-path
platformio.platformio-ide
redhat.vscode-commons
redhat.vscode-yaml
ryu1kn.partial-diff
stkb.rewrap
timonwong.shellcheck
venner.vscode-glua-enhanced
VisualStudioExptTeam.intellicode-api-usage-examples
VisualStudioExptTeam.vscodeintellicode
wmaurer.change-case
zhuangtongfa.material-theme
```

**Comment by taoky** [comment]
https://github.com/microsoft/vscode/pull/196809 is not a very good workaround: what if the process exits, but another innocent process just takes this PID?

**Comment by paulrutter** [comment]
> #196809 is not a very good workaround: what if the process exits, but another innocent process just takes this PID?

It probably cannot do that as the pid is still taken? I agree it's not a great workaround, but until the root cause is clear it does solve the issue where a cpu is occupied.
