### ISSUE TITLE
Reconsider strategy for syncing commandPalette.mru.* storage keys

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#194491]
`commandPalette.mru.cache` and `commandPalette.mru.counter` are two of the keys that trigger syncs a lot since they update every time the user runs a non-most recently used command in the command palette. Could we save this using `IStorageService.onWillSaveState` instead? I'm not sure how conflicts work exactly when using the event and there are multiple machines syncing, but it also doesn't matter too much if the command palette history cache is clobbered.

**Comment by TylerLeonhardt** [comment]
I don't have a lot of context around `onWillSaveState` so I'll defer to you and @sandy081 to make the decision of what would be best. Let me know what you need me to do.

**Comment by sandy081** [comment]
Also adding @bpasero as he has bit more context. One observation I saw with commands history is that this state is not synced across windows. This means the LRU commands in one window are not same as in the other window. Also window from which a command is executed will override the state. This means if you run commands in multiple windows, LRU state from the window that you run the last command wins. 

Since we are not syncing this state across windows, I think it is not worth to live sync this across machines. Hence my recommendation here would be to let the window save the LRU state when window is about to shutdown.

**Comment by bpasero** [comment]
Yes, 👍 for that approach. I intentionally did not want the MRU list to sync across windows live because that is very confusing when you jump between windows and quickly execute the last command.

**Comment by bpasero** [comment]
Btw can we figure out the top keys that are causing sync to trigger maybe in our team and gather that data for a week to see if we miss something?

**Comment by sandy081** [comment]
> Btw can we figure out the top keys that are causing sync to trigger maybe in our team and gather that data for a week to see if we miss something?

Yes using the new `Developer: Download Settings Sync Activity` command - I can figure out the most frequently changed state/resources.

**Comment by sandy081** [comment]
I am also wondering why this is not workspace scoped because most of the times the commands I run are related to the workspace.

**Comment by Tyriar** [comment]
FYI @joyceerhl this may affect continue on. We might want to force a sync of the command palette MRU specially when continue on is triggered.

**Comment by bpasero** [comment]
via https://github.com/microsoft/vscode/commit/5389e6196e8efe8487d4338c1156c007cda04732
