### ISSUE TITLE
Codespaces crashes upon starting jupyter notebook server

### ISSUE THREAD

**Issue by Yoyokrazy** [microsoft/vscode#194507]
While verifying [#14215](https://github.com/microsoft/vscode-jupyter/issues/14215)
cc @DonJayamanne 

Repro Steps:
- start blank codespace
- install python
- start venv
- install jupyter
- start jupyter notebook with the command `jupyter notebook`
- 🐛 terminal clears itself, freezes, and pop-up message saying:
<img width="661" alt="image" src="https://github.com/microsoft/vscode/assets/12552271/3c5559a5-9ab6-4090-9014-910f3e52562d">

Version: 1.83.0-insider
Commit: ba36ae4dcca57ba64a9b61e5f4eca88b6e0bc4db
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36 Edg/117.0.2045.43
Embedder: codespaces

**Comment by DonJayamanne** [comment]
This is an external program that’s causing the work bench to crash

**Comment by bpasero** [comment]
It looks like this is caused by the Codespaces extension. Please file the issue in the [Codespaces Discussion Forum](http://aka.ms/ghcs-feedback). Make sure to check their issue reporting template and provide them relevant information such as the extension version you're using. See also our [issue reporting guidelines](https://aka.ms/vscodeissuereporting) for more information.\n\nHappy Coding!
