### ISSUE TITLE
Improve startup performance to meet our thresholds

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#194560]
Over the past month we managed to get above our threshold for what we consider a fast startup. The actual source of this regression is not yet identified, but we can look at startup traces and try to improve performance in certain areas to meet the threshold again.

![image](https://github.com/microsoft/vscode/assets/900690/da3493a6-b78f-4010-8081-9eb8681b7837)

Minification and mangling make it impossible to read a perf trace, so below is from a locally build macOS ARM version that disables both: [Trace-20231001T140054.json.zip](https://github.com/microsoft/vscode/files/12777086/Trace-20231001T140054.json.zip)

The trace measures window reload time on a `package.json` file.

Looking at the [perf dashboard](https://dataexplorer.azure.com/dashboards/2e20491b-d517-40b5-bab4-269607f05221?p-_startTime=30days&p-_endTime=now#329a8a51-b9c8-40c1-8663-4fc87d7267c0), I believe there to be a regression in how much time the workbench spends in restoring things:

![Image](https://github.com/microsoft/vscode/assets/900690/885e6a19-8abe-4ab7-a130-61145e2c9723)

![Image](https://github.com/microsoft/vscode/assets/900690/79163003-5f69-49d3-ac2e-7bde467cd98f)

Going over the trace, some things I noticed (feel free to report others if you find out):

**`shouldRenderHint`**

- [x] @joyceerhl @bpasero

This seems quite new and takes almost `10ms` to decide if the hint should be shown, even though we open a `package.json` file?

![Image](https://github.com/microsoft/vscode/assets/900690/3b14c805-945d-4dc1-b8e3-fdf8c97d935c)

**`CommandCenter`**

- [ ] @jrieken 

One of the larger things consuming time, relatively recently made the default (though already in the previous milestone):

![Image](https://github.com/microsoft/vscode/assets/900690/c52b2352-1a8d-49eb-9c02-25c7fde91427)

**`ViewsService`**

- [ ] @sandy081 @sbatten 

Not sure we can do anything about it, since this seems to be creating all parts. But still quite some time spend:

![Image](https://github.com/microsoft/vscode/assets/900690/1dbc7c6b-800a-416e-a4ba-d320afdb8367)

**`onDidRegisterViews`**

- [ ] @sandy081 @sbatten 

There seems to be a major GC happening within, not sure if that is triggered by what seems to be a recalculate style:

![Image](https://github.com/microsoft/vscode/assets/900690/f77d5701-4cd5-4219-9724-1570ea7572a4)

**Comment by sandy081** [comment]
> Not sure we can do anything about it, since this seems to be creating all parts. But still quite some time spend:

Yeah, this is creating all parts. But we are aggressively creating them even if not needed. For example, auxiliary bar is not shown by default, but it is still being created. CC @sbatten. Otherwise, I removed the dependency of this from views service ie., views service does not need to access this service in the given call stack.

> There seems to be a major GC happening within, not sure if that is triggered by what seems to be a recalculate style:

I do not know if GC is being triggered by style recalculation or just a random one. But something what I figured out from the above call stack is that style recalculation that is triggered by `scanDomNode` should not be happening in this case. Because, this style recalculation is done on welcome view which does not exist in the file explorer view when opening a folder. I am adding a small fix that will avoid this style recalculation when there is no welcome view that saves **~5ms** on my machine. I would leave it to @joaomoreno if this can be made better.

**Comment by bpasero** [comment]
@sandy081 great stuff!!

**Comment by joaomoreno** [comment]
Here's that cleanup: https://github.com/microsoft/vscode/pull/194868

**Comment by bpasero** [comment]
Its a tight race but it has gotten better:

![image](https://github.com/microsoft/vscode/assets/900690/e28adebc-dff2-4d27-88fe-4f9f9489b6d5)
