### ISSUE TITLE
Telemtry footer not shown in welcome page

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#194741]
1. Open VS Code with a fresh user data dir
2. Open welcome page. No telemetry footer is shown 🐛 

We should show the telemetry footer. It is a requirement from our legal team.
My suggestion is to fix this as part of the September stable release.

This is how it should look like. And there is already code that computes this [here](https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/welcomeGettingStarted/browser/gettingStarted.ts#L1508)

![Screenshot 2023-10-03 at 19 49 19](https://github.com/microsoft/vscode/assets/1926584/cdce7f44-04cd-4e15-adad-6b47351e303a)

@bhavyaus confirmed this a regression probably introduced with https://github.com/microsoft/vscode/pull/184770/files

fyi @devinvalenciano @chrisdias

**Comment by bhavyaus** [comment]
Apologies for the confusion. Not a regression.
We show the privacy and telemetry statement on first launch per usual:

On desktop, this is on the walkthrough page:
<img width="771" alt="image" src="https://github.com/microsoft/vscode/assets/25044782/039c1b8d-c4ca-4941-aae8-6faf7b40005c">

On insiders.vscode.dev, 
<img width="1153" alt="image" src="https://github.com/microsoft/vscode/assets/25044782/59e155c5-2707-4908-aee0-f95062bb2afc">

Subsequent launches do not show the statement due to this check:

https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/welcomeGettingStarted/browser/startupPage.ts#L93

**Comment by isidorn** [comment]
This make a lot of sense thank you.
I was unaware that I need to explicitly pass the empty ext-dir as well to make it a real fresh launch.
