### ISSUE TITLE
TSServer Service dies on rename

### ISSUE THREAD

**Issue by con-ssc** [Microsoft/vscode#19482]
- VSCode Version:
![image](https://cloud.githubusercontent.com/assets/8189808/22365098/fd563b7e-e475-11e6-8a30-e082e114260c.png)

- OS Version: Windows 100

Steps to Reproduce:
1. Trying to rename a function in a typescript class output skeleton. Renaming function _c.

```
var a;
(function(a) {
    var b= (function() {
        function b() {}
        function _c(){}

        return b;
    };
    return a.b = b;
})(a || (a={}))
```

```
[Trace - 09:35:48] TypeScript Service: canceled request with sequence number 347
[Error - 09:35:49] TSServer exited with code: 3
[Error - 09:35:49] 'navtree' request failed with error.
Error: Service died.
    at c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\typescript\out\typescriptServiceClient.js:442:46
    at Array.forEach (native)
    at TypeScriptServiceClient.serviceExited (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\typescript\out\typescriptServiceClient.js:441:37)
    at ChildProcess.<anonymous> (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\typescript\out\typescriptServiceClient.js:362:35)
    at emitTwo (events.js:111:20)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
[Info  - 09:35:49] Using tsserver from location: c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\typescript\node_modules\typescript\lib\tsserver.js
[Trace - 09:35:52] TypeScript Service: canceled request with sequence number 377
```

**Comment by con-ssc** [comment]
And I know have an ongoing progress indicator
![image](https://cloud.githubusercontent.com/assets/8189808/22365161/4d87b212-e476-11e6-9729-de79a783c307.png)

**Comment by mousetraps** [comment]
@con-ssc sorry to hear that! We've seen this issue in the past, and have a *very* long ongoing thread trying to narrow it down, so any additional info helps. https://github.com/Microsoft/TypeScript/issues/10735

Any chance you could post more details over there? Are you seeing the issue for every file, or just some files?

Also it would be helpful if you could capture a log so we can have a better chance of tracing it down. 
1. set the environment variable `TSS_LOG` to `-level verbose`.
2. Launch VS Code in administrator mode (otherwise the log won't be able to get captured)
3. Try and reproduce the issue again
4. A log file written next to `tsserver.js` that would have the form of `.log[0-9]+` (in your case, the log will be in `C:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\typescript\node_modules\typescript\lib`)

cc @mjbvz @waderyan

**Comment by con-ssc** [comment]
I have the verbose logging in vscode active all the time because those errors happen so infrequently. Good to hear that there is an output possibility for the log now. I will start logging and post in the above issue when I encounter the problem again.

**Comment by con-ssc** [comment]
I added the variable and opened as admin but the error is not logged, but it is logged in vscode tsserver log.
