### ISSUE TITLE
vscode always replace symlink `settings.json`

### ISSUE THREAD

**Issue by akiirui** [microsoft/vscode#194856]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.83.0 (e7e037083ff4455cf320e344325dacb480062c3c)
- OS Version: Arch Linux

Steps to Reproduce:

1. `ln -s SOURCE/settings.json VSCODE_USER/settings.json`
2. Restart vscode
3. `VSCODE_USER/settings.json` is replaced by vscode with a regular file

Older version is work fine.

**Comment by daniel-liuzzi** [comment]
I also started having this problem today after updating to 1.83.0

**Comment by RasmusLeupold** [comment]
It is the same behavior on MacOS. 😢 It would be very nice if you guys could fix this. 🙏

**Comment by sandy081** [comment]
@bpasero Thanks for the fix. Tagged this as a candidate.

**Comment by sandy081** [comment]
@bpasero Wondering if this impacts not only sym links but also mapped drives or other types?

**Comment by sandy081** [comment]
Reopening for tracking candidate.

**Comment by jstm88** [comment]
I've observed that on my machine (macOS 13.5.2) the symlinks are not deleted, but instead all settings simply fail to save. There is no error message, but the settings UI spontaneously changes it back to the original value. The JSON file on disk is never changed. If I make a local copy of the file instead of a symlink, the file *is* updated with the new setting and it works.

This leads me to believe that something about the way VS Code accesses its settings files has been changed, and it was done incorrectly resulting in it being incapable of writing to a file when it is a symlink.

In the meantime, I've force downgraded VS Code to the previous version and disabled updates. Hopefully this gets fixed quickly.

**Comment by bpasero** [comment]
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line
* reproduce the issue
* attach the log files you find from running the command "Open Logs Folder"

Thanks!

**Comment by wwwangzhou** [comment]
When can we expect the new version to be available in the stable release, please?

**Comment by ElectricRCAircraftGuy** [comment]
Here's a functional workaround, meanwhile: my tutorial/comment here: [How to write custom git hooks to automatically copy the changed VSCode `settings.json` and `keybindings.json` files whenever they change](https://github.com/microsoft/vscode/issues/195539#issuecomment-1763255597)

**Comment by inclyc** [comment]
Also confirmed on 1.83.1
