### ISSUE TITLE
Add audio cue for when something is cleared

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#194939]
This will reduce verbosity.

cc @afre100, @jooyoungseo, @rperez030

**Comment by jooyoungseo** [comment]
Yes, I vote for the audio cue.

**Comment by rperez030** [comment]
An audio cue only will exclude users who are deaf as well as those who are primary Braille users. I don't think the word "cleared" adds significant overhead in terms of verbosity. If we are doing this to check a compliance box, and audio cue only probably wouldn't be sufficient to meet SC 4.1.3 Status Messages since the standard requires that such messages must be programmatically determined through roles or properties.


My very personal opinion as an AT user is that neither the "cleared" announcement or the audio cue are really necessary. I'm not suggesting that it could be harmful or that it shouldn't be done, just that based on my experience I personally don't need that in this particular instance.

**Comment by meganrogge** [comment]
Thank you both for your feedback. While I agree that "Cleared" is not verbose, I can imagine some users would prefer an audio cue to indicate this, so think it'll be good to have that option. Perhaps we can `alert` by default and not do so if that audio cue is enabled?

**Comment by rperez030** [comment]
> Perhaps we can `alert` by default and not do so if that audio cue is enabled?

It makes sense to me as long as the audio cue is not enabled by default.

**Comment by meganrogge** [comment]
We will `alert` when the audio cue is disabled, which it will be by default. 

Discussed with @jooyoungseo that we might want to have an option to `alert` in place of audio cues more broadly across the workbench to accommodate deaf blind and/or primarily braille users.
