### ISSUE TITLE
Lost space in preview mode

### ISSUE THREAD

**Issue by rajinder-yadav** [Microsoft/vscode#19505]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:41:20.664Z)
- OS Version: Linux x64 4.4.0-59-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-markdownlint|DavidAnson|0.6.1|
|EditorConfig|EditorConfig|0.3.4|
|jslint|ajhyndman|1.2.1|
|jshint|dbaeumer|0.10.15|
|vscode-eslint|dbaeumer|1.2.2|
|tslint|eg2|0.8.1|
|cpptools|ms-vscode|0.10.0|
|Spell|seanmcbreen|0.9.1|
|vim|vscodevim|0.5.2|

---
In split screen look like someone tired to fix the disappearing scrollbar bug, which still exist, but now I've lost a big chuck of screen real-estate which I would like returned. This is more so a problem in split view when I am looking am editing markdown file and looking at preview side by side.

![scrollbar](https://cloud.githubusercontent.com/assets/439226/22372941/7e02d664-e46d-11e6-892c-93c7a36b7c02.png)

**Comment by mousetraps** [comment]
Hey @rajinder-yadav, thanks for reporting! This issue is already being tracked at #5745 (markdown preview uses webview), so I suggest following that thread for updates. If you try zooming out a bit (either `Ctrl+-` or by setting your "window.zoomLevel" setting to 0), you should be able to reclaim that space.

**Comment by rajinder-yadav** [comment]
Thanks @mousetraps, I'm getting old and need bigger fonts :)
