### ISSUE TITLE
Suggestion: When quick open is active, fill search field with selected item when pressing left arrow key

### ISSUE THREAD

**Issue by PunchyRascal** [Microsoft/vscode#19500]
This would help when you search for a file, that shares name with many files in different directories and you opened the wrong one at first and want to go back to the search result to find the right file.

Of course, this could alternatively be achieved by retaining the last search result in quick open.

**Comment by mousetraps** [comment]
@PunchyRascal Cool idea! So, just to clarify, the underlying issue is that sometimes when you use quick open, you get tons of results, and the filename alone sometimes isn't enough info to select one of those results, so you want an easier way to find the result you need. And you're suggesting a couple ways to solve this issue:
1. a view be populated with all the original results from quick open, so you don't have to go find your place again. 
2. quick open save "your place" in the results, so you can more quickly browse through them.

Does that sound about right?

**Comment by PunchyRascal** [comment]
Yes. I was also suggesting, when quick search is active, pressing the left arrow to fill name under cursor into the search field, but that may be considered separate suggestion.
