### ISSUE TITLE
Very long tab titles when opening settings editor and settings file

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#19504]
* open settings editor
* open the underlying user settings file in a 'normal' editor
* 🐛 very long titles

![screen shot 2017-01-27 at 14 45 07](https://cloud.githubusercontent.com/assets/1794099/22372849/52dc0014-e49f-11e6-8e8c-56a2ed5afb07.png)

**Comment by bpasero** [comment]
@sandy081 this is a bit unhappy because literally the 2 editors have the same label and description (the full path to the file on disk) so our logic cannot do much to distinguish these two editors if you manage to open them at the same time. 

Maybe we should just override `getDescription` in `PreferencesEditorInput` to return a specific description for this editor, e.g. "User Settings" and "Workspace Settings"? Downside is that the user would no longer see where the file exists on disk.

**Comment by sandy081** [comment]
We already have tabs inside Settings editor to identify User and Workspace settings. I do not think it is good idea to show that again in the main editor description by removing the file path. Taking out the file path for above scenario is not good because I think most users go to Settings editor and not showing the file path will not be good.

**Comment by bpasero** [comment]
Actually I have an idea, if the label + description happens to be the same there is no value in showing the description. Let me take care of that. Since both editors are literally the same file I think it is also fair to show the same label.

**Comment by sandy081** [comment]
In fact, I am thinking the same.
