### ISSUE TITLE
json-schema.org/schema 404

### ISSUE THREAD

**Issue by 6nv** [microsoft/vscode#195189]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.83.0
- OS Version: MacOS Ventura 13.6

I've been getting a 404 not found error code from https://json-schema.org/schema in VS Code and in multiple different browsers, and on different networks. Additionally, VS code no longer provides intellisense when I use that schema URL.

Steps to Reproduce:

1. Create `<file>.json` (for example, `schema.json`)
2. Insert this code:
    ```json
    {
        "$schema": "https://json-schema.org/schema"
    }
    ```
3. Notice this error, and intellisense is not working:
    ![example](https://user-images.githubusercontent.com/91281131/273673438-b500e8cd-e50c-44ed-a689-3195c2f3f862.png)

**Comment by gregsdennis** [comment]
This error is due to a revamped https://json-schema.org where we are only hosting HTTPS content.  I believe we _are_ serving a 301 from the meta-schema URLs, though.

Potential problems:

1. `http://json-schema.org/schema` should never be used to identify a meta-schema.  This is not a valid meta-schema URI.  Historically this URL hosted the latest meta-schema, but that led to unpredictable behaviors as new versions were released and the "latest" was updated, so we decided to remove it.
2. The value of `$schema` is to be interpreted as a URI, not a URL.  If the value happens to also be a URL, it is not to be interpreted to actually _be_ at that location.  It is an identifier only.
3. Implementations (including editors) should not be downloading well-known meta-schemas.  They should be packaged with the implementation.  (@6nv, does the problem still occur if you use `http://json-schema.org/draft-07/schema#` or another well-known meta-schema URI?)

**Comment by 6nv** [comment]
Some updates after meeting with the json-schema team:

- A Cloudflare redirection was added (@benjagm)
- http://json-schema.org/schema is deprecated and should not be used (@jdesrosiers)
-  `$schema` is to be interpreted as a URI, not URL (@gregsdennis)

Here are some updates after the redirection was added, and restarting VS Code:

- New error message `Problems loading reference`
- Now, there are a few intellisense options (see image)

<img width="1263" alt="Screenshot 2023-10-09 at 2 06 11 PM" src="https://github.com/microsoft/vscode/assets/91281131/78fa4386-374a-49a1-ad39-85eab59128d3">

<img width="531" alt="Screenshot 2023-10-09 at 2 06 20 PM" src="https://github.com/microsoft/vscode/assets/91281131/068878c4-8e74-46e2-bbd1-e405c6149b84">

**Comment by 6nv** [comment]
Last thing to add here for now: By default, draft-04 and draft-07 are written with `http` instead of `https`, however using either `http` or `https` works just fine for these schemas.

<img width="614" alt="Screenshot 2023-10-09 at 2 19 53 PM" src="https://github.com/microsoft/vscode/assets/91281131/c1f11ede-70fc-461a-b58c-6264b42035e9">
<img width="858" alt="Screenshot 2023-10-09 at 2 20 17 PM" src="https://github.com/microsoft/vscode/assets/91281131/72df3742-271f-46eb-8824-dd662ee3842a">

**Comment by benjagm** [comment]
> however using either `http` or `https` works just fine for these schemas.

Yes, those redirections serves both http and https.

**Comment by aeschli** [comment]
I verified that we do not use or propose `http://json-schema.org/schema` in vscode or the json language service.
I created a PR to access json-schema.org always with `https`.

**Comment by gregsdennis** [comment]
@aeschli please be aware that the `/schema` route will likely not be available much longer. We have decided to discontinue it as it does not nap to a known meta-schema.

Furthermore, could you verify that the published meta-schema URIs are not downloaded, please?  They should be considered well-known and supported offline.  These definitely SHOULD NOT be regularly accessed by download.

- draft 4
- draft 6
- draft 7
- draft 2019-09
- draft 2020-12

We're not sure yet what the next iteration will be.

**Comment by gregsdennis** [comment]
@aeschli please confirm the other meta-schemas are not regularly downloaded.  Otherwise this issue is NOT completed.
