### ISSUE TITLE
Multiline object properties in intellisense should auto-complete using bracket notation

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#19528]
- VSCode Version: Code - Insiders 1.9.0-insider (3af0e9d6b79145011a7be3970c1d4b83d69b0443, 2017-01-27T10:46:43.625Z)
- OS Version: Windows_NT ia32 10.0.14986
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-svgviewer|cssho|1.3.0|
|EditorConfig|EditorConfig|0.3.4|
|git-project-manager|felipecaputo|1.0.1|
|md-navigate|jrieken|0.0.1|
|vscode-scss|mrmlnc|0.6.0|
|seti-icons|qinjia|0.1.3|
|lorem-ipsum|Tyriar|1.0.0|
|terminal-tabs|Tyriar|0.1.1|
|theme-glacier|Tyriar|0.0.10|

---

Testing https://github.com/Microsoft/vscode/issues/18937

![image](https://cloud.githubusercontent.com/assets/2193314/22384834/efa541be-e484-11e6-9165-d25805e0916e.png)

Results in this which causes an error:

![image](https://cloud.githubusercontent.com/assets/2193314/22384840/f8b08bec-e484-11e6-9244-298ed4706e2c.png)

It would expect `a['aasdasdlkmask\nb']` in this case.

**Comment by weinand** [comment]
@isidorn node-debug now returns DebugProtocol.CompletionItems with a `text` attribute and a `start` position for items where `name` contains spaces.

My test case:
```js
var o = {};
o['hello world'] = 123;
console.log(a);
```

**Comment by isidorn** [comment]
@weinand did you accidently close this? I still need to respect the start on my end?

**Comment by weinand** [comment]
@isidorn the commit comment closed this prematurely.

**Comment by isidorn** [comment]
ping @michelkaporin

The issue here is that vscode frontend is not respecting the `start` provided by the debug adapter backend. We need to start respecting that and convert that number to an appropriate in the [`ISuggestion`](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/modes.ts#L207) interface. We also need to make sure not to break previous completion behavior.

[code pointer](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/common/debugModel.ts#L604)

**Comment by michelkaporin** [comment]
I have looked at the current code there, and it seems that there is no quick fix (apart from going for 'hack') that can be produced without changing some of the API. Postponed until @isidorn or somebody else more familiar with the code base can look into it.
