### ISSUE TITLE
Allow git.init to programatically initialize an arbitrary path

### ISSUE THREAD

**Issue by dbolack-ab** [microsoft/vscode#195301]
I've been working on a specialized workspace plugin for setting up projects in a predefined way. One of the core parts is initializing a git backing store for the workspace in the project setup. Due to the way the folder is structured the git project root needs to be at a location other than the workspace root folder.  Passing true with the git.init does not solve this need.  It is preferable to not have the user prompted for the path.  

An additional optional parameter for git.init providing this path would be very helpful.

**Comment by lszomoru** [comment]
Instead of using the `git.init` command you can use [the git extension api](https://github.com/microsoft/vscode/blob/1b80381919f9398553ff51be55e167408bd69802/extensions/git/src/api/api1.ts#L301) to initialise a git repository. When using the git extension API, you can specify the location as well as the default branch name. Give it a try and let me know if you run into any issues. Thanks!

**Comment by dbolack-ab** [comment]
I did not realise that was an option . That's a better choice.

Thanks!
Closing.
