### ISSUE TITLE
Copilot Quick Fix with specific actions

### ISSUE THREAD

**Issue by justschen** [microsoft/vscode#195305]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: MacOS

A case where specific lint/styling quick fixes are still below. Could be something to do with warnings vs actual fixes. Not sure if this is intentional or not, but in cases where it is wrapped by quick fixes above and below, it does seem a little weird.

Example:
![Screenshot 2023-10-10 at 12 23 08 PM](https://github.com/microsoft/vscode/assets/54879025/99d085f0-12f7-4d30-bef7-4461b2105f2b)

Warning for missing semicolon according to linter, activate quickfix:
<img width="789" alt="Screenshot 2023-10-10 at 2 26 38 PM" src="https://github.com/microsoft/vscode/assets/54879025/17e8becf-752e-4910-a3b2-10f50ebca731">

Other warnings with direct fixes is okay:
<img width="772" alt="Screenshot 2023-10-10 at 2 29 56 PM" src="https://github.com/microsoft/vscode/assets/54879025/7af7c80e-08da-4a0c-9cc2-d45bd0767d89">

**Comment by justschen** [comment]
related to https://github.com/microsoft/vscode/issues/194213

**Comment by aiday-mar** [comment]
Hi @justschen, the reason this is the case is likely because of this part of the code:

```
private static codeActionsComparator({ action: a }: CodeActionItem, { action: b }: CodeActionItem): number {
	if (isNonEmptyArray(a.diagnostics)) {
		return isNonEmptyArray(b.diagnostics) ? ManagedCodeActionSet.codeActionsPreferredComparator(a, b) : -1;
	} else if (isNonEmptyArray(b.diagnostics)) {
		return 1;
	} else {
		return ManagedCodeActionSet.codeActionsPreferredComparator(a, b); // both have no diagnostics
	}
}
```

The code actions you mentioned that appear below the Copilot actions have an empty `diagnostics` field, hence they are placed below the copilot ones. You can see this in the image below where the Copilot actions have associated diagnostics, the eslint one does not. 

<img width="691" alt="Screenshot 2023-10-11 at 09 19 55" src="https://github.com/microsoft/vscode/assets/61460952/06649b40-37d8-4776-af1c-8ea2e93a1a04">

<img width="673" alt="Screenshot 2023-10-11 at 09 20 59" src="https://github.com/microsoft/vscode/assets/61460952/b5bc95ea-1837-4153-9436-86de0da3091f">

I am wondering if we want the Copilot diagnostics to appear at the very bottom of this list? Thoughts @aeschli

**Comment by aeschli** [comment]
I suggest we have the ai code actions appear always at the end.
So, first criteria: isAI, second criteria whether it has diagnostics attached.

 @jrieken Ok for you?
