### ISSUE TITLE
editor.rulers should not be zero indexed

### ISSUE THREAD

**Issue by dinhani** [Microsoft/vscode#19539]
`editor.rulers` seems to be zero index. If I set the value to 80, I expect it to be displayed at column 80, but it is displayed at column 81. To display at column 80, I have to set it to 79.

- VSCode Version: 1.81
- OS Version: Windows 7 SP1

Steps to Reproduce:

1. Set the user setting: `"editor.rulers": [80]`
2. Rulers are displayed starting at column 81, not 80

![column 81](https://cloud.githubusercontent.com/assets/1139781/22394680/a979c15e-e50d-11e6-88fd-fdaf16a45090.png)

**Comment by mousetraps** [comment]
Hey @dinhani, thanks for reporting! Agreed that this behavior is inconsistent w/ line/column indexing, so I totally understand the confusion.

That said, I think this design is probably the most intuitive way to do it. I suspect that most users setting editor.rulers care about the "width" rather than the column - e.g. if you're trying to meet some rule like "lines should be 80 characters long", it would make sense to specify `editor.rulers = 80`, because that means that 80 characters should come before the ruler. And specifying `editor.rulers = 0` should mean that the ruler appears before any text. 

cc @rebornix @alexandrudima

**Comment by rebornix** [comment]
Thanks @mousetraps for the perfect explanation, rulers are character count/width instead of column number which is 1 based. Current behavior is consistent with other editors as well AFAIK.
