### ISSUE TITLE
aria label [object Object], terminal tabs

### ISSUE THREAD

**Issue by SimonSiefke** [microsoft/vscode#195661]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.83.1
- OS Version: Ubuntu 23.04

**Steps to Reproduce**

1. In VSCode, open two terminals
2. inspect the terminal tabs using chrome devtools
3. Notice that both terminal tabs have `aria-label="[object Object]"`

![aria-label](https://github.com/microsoft/vscode/assets/23744935/62fab064-f4f7-4024-8b85-a41a7735c775)

<br>

**Source Code**
It seems the issue might be here (`options.title` can be of type `string` or `ITooltipMarkdownString`): https://github.com/microsoft/vscode/blob/ae774a04cf1f5ecfc03d79165f30b8001cde862d/src/vs/base/browser/ui/iconLabel/iconLabel.ts#L140-L142

**Comment by monstajoe2002** [comment]
Hello can anyone assign this issue to me?

**Comment by amaust** [comment]
Hi, @meganrogge. I was looking into this issue and like @SimonSiefke suspected it seems like in this instance the aria-title is a Markdown string which is why its showing up as an object. I'm not exactly sure what the best to be handle the Markdown string would be. However, using the tooltip label marks the aria-label as "$(terminal) zsh" would that be sufficient or should I look for another solution. Not exactly sure of the guidelines surrounding aria. Thanks!

**Comment by meganrogge** [comment]
Can you call `.toString()` on the markdown string? 

If not, using the tooltip seems fine.

**Comment by amaust** [comment]
Unfortunately, toString doesn't solve the problem.
<img width="877" alt="Screenshot 2023-10-18 at 12 07 42 PM" src="https://github.com/microsoft/vscode/assets/144873395/60c90653-8f54-4e2d-91b9-937fd095b998">
This is what the input is getting as ITooltipMarkdownString. Because the IIconLabelValueOptions interface accepts both a string or a markdown string for the title I'm unsure of a function that will allow me to just get the markdown property without causing other issues. Plus in this case I dont know if the string is even suitable for a aria-label. However if tooltip works, I'll run tests and submit a PR soon.
