### ISSUE TITLE
Unwanted views showing up in sidebar

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#195692]
The gitlens views showed up my sidebar. I have manually hidden and didn't change that back today, yet they show. 

<img width="787" alt="Screenshot 2023-10-16 at 13 04 10" src="https://github.com/microsoft/vscode/assets/1794099/e9465313-cb46-441a-b954-22e171187fba">

**Comment by sandy081** [comment]
- Have gitlens installed and enabled on one workspace and unpin gitlens view containers
- Open another workspace and disable gitlens extension for this workspace and reload
- Gitlens view containers are pinned in first workspace

Caused by this change - https://github.com/microsoft/vscode/pull/195637 - 
Reverted - https://github.com/microsoft/vscode/pull/195734
