### ISSUE TITLE
VSCode does not differentiate when we use tab or space when Toggle Render WhiteSpace is active.

### ISSUE THREAD

**Issue by Tekbr** [Microsoft/vscode#19587]
- VSCode Version: 1.9.0 - insider e68cede
- OS Version: Windows 10

-- Sorry for the English, I used Google Translator --

Steps to Reproduce:

See the gif. All extensions disabled.

![space](https://cloud.githubusercontent.com/assets/19866231/22432674/d874580c-e6fc-11e6-877c-db7b8ddca732.gif)

Tab represented by `->`, Space represented by `...` right?

If I give tab by any program the VSCode recognizes `->`, but if it gives tab by the VSCode itself it recognizes as space `...`.

**Comment by rebornix** [comment]
Your `editor.insertSpaces` is set as `true` so when you press `tab`, the characters get inserted into the editor are actually spaces instead of tab. While `renderWhitespace` is rendering what's in the editor instead of what you type.

Another way to prove that is, press `tab` in Notepad, save the file and then open it in VS Code, you can see tabs are rendered correctly. This is because Notepad doesn't have this kind of insert-tab-as-spaces.

**Comment by Tekbr** [comment]
@rebornix It worked. Thank you so much. :smile:
