### ISSUE TITLE
Flaky smoke test: install and enable vscode-smoketest-check extension

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#195850]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=237761&view=logs&j=260a512b-e5ca-5cf1-3f8e-20c0fa41efc9&t=82df682a-a732-590f-d041-2bbd067871c9

```
 1) VSCode Smoke Tests (Web)
       Extensions
         install and enable vscode-smoketest-check extension:
     Error: QuickAccess.runCommand(commandId: Extensions: Focus on Extensions View) failed to find command.
```

**Comment by sandy081** [comment]
@bpasero / @TylerLeonhardt Any idea what could have gone wrong? I am not sure how I can figure out if the workbench is restored or not from the screenshots.

**Comment by bpasero** [comment]
@sandy081 have you tried to see the trace at https://trace.playwright.dev/?

Trace link: https://artprodeus21.artifacts.visualstudio.com/A341001b6-62a6-4d7e-aa61-779aea3de100/a6d41577-0fa3-498e-af22-257312ff0545/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21vbmFjb3Rvb2xzL3Byb2plY3RJZC9hNmQ0MTU3Ny0wZmEzLTQ5OGUtYWYyMi0yNTczMTJmZjA1NDUvYnVpbGRJZC8yMzc3NjEvYXJ0aWZhY3ROYW1lL2xvZ3MtbWFjb3MteDY0LXNtb2tlLTE1/content?format=file&subPath=%2Fsmoke-tests-browser%2F9_suite_Extensions%2Fplaywright-trace-1-install_and_enable_vscode-smoketest-check_extension.zip

**Comment by TylerLeonhardt** [comment]
This is likely the same as that other issue where the contributor of this command isn't starting up fast enough because of what it's activated. It's on `Restored` right?

**Comment by sandy081** [comment]
This is the same issue indeed and it's the same command as before. I have added a new API `whenWorkbenchRestored` to our window driver and let smoke tests commands util to wait until workbench is restored if the command is not found.

https://github.com/microsoft/vscode/blob/29cbf57374f33a0a1ab111eac12650891aad1a94/src/vs/workbench/services/driver/browser/driver.ts#L30

This is failing even waiting until workbench is restored. I wonder if there is a race condition on waiting this promise?

**Comment by sandy081** [comment]
@bpasero I checked the trace and it seems this command was not found even after 10s

<img width="676" alt="image" src="https://github.com/microsoft/vscode/assets/10746682/56e0c569-1db8-46ff-9b89-1f07e4187859">

**Comment by bpasero** [comment]
@sandy081 I see you added `whenWorkbenchRestored` utility but only use it in `quickaccess.runCommand`. How about moving this into here:

https://github.com/microsoft/vscode/blob/2ff3e98d7747f922188bb4c7eca2c28733f3ae51/test/automation/src/application.ts#L117

That way at least we can know for sure that smoke tests only begin to execute when the workbench is restored. I think that would be a good way to have consistent runs.

I am not sure it would address this issue here but think its a good start: if smoke tests run after restored and the commands do not appear in quick pick, then the command registration is broken.
