### ISSUE TITLE
All installed callstack context menu items are shown during every debug session

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#19608]
I always assumed that during a debugging session, I'd only see the context menu items contributed by the active debug adapter. But in prepping the chrome extension to release, I just realized that I see all of them during every debug session.

![image](https://cloud.githubusercontent.com/assets/323878/22452769/924088a6-e72e-11e6-808a-128647d84c9e.png)

This is a Go debug session, and I see callstack context menu items from node2 and chrome. They don't do anything. I think they should both be hidden. Normally if you have the Chrome extension installed, you'll see two instances of "toggle skipping this file".

@isidorn @weinand

**Comment by roblourens** [comment]
Well, what I can do for now is just not contribute it from the Chrome extension. When you click the context menu item during a chrome debug session, it will activate the node2 extension and send the correct message to the chrome debug adapter.

But if it's easy, it might be worth considering for January?

**Comment by isidorn** [comment]
Not for january, this is not critical and only happens if you have chrome extension installed. Also having 2 of the same actions is not the end of the world.

In a perfect world these actions should have a precondition when they are enabled, for instance
'debug:chrome'
'debug:node'

We already have a context 'inDebugMode', but I can look into introducing the dynaminc context based on debug type

**Comment by weinand** [comment]
@isidorn yes, we need to provide a dynamic context based on debug type.

**Comment by isidorn** [comment]
Ok so I introduced a dynamic context based on debug type, namely you should now be able to do the following:

`"when": "inDebugMode && debugType == 'chrome'" `

**Comment by roblourens** [comment]
Looks great, thanks
