### ISSUE TITLE
Linux: Collision between OS and VSCode shortcut

### ISSUE THREAD

**Issue by SRNissen** [microsoft/vscode#196163]
Does this issue occur when all extensions are disabled?: Yes/No

## System

- VS Code Version: All on Linux
- OS Version: All Ubuntu since at least 18, possibly earlier

## Steps to Reproduce:

1. Start with focus on editor, e.g. because you just edited something
2. Press Ctrl+Shift+E to open the explorer

## Expected result:

The explorer opens

## Actual result

An underlined e appears in the editor at the cursor location. Typing is weird until the e is removed.

## Notes:

The underlined e indicates the linux ibus emoji picker has been activated.

As a workaround, the ibus emoji picker can be changed to activate on a different shortcut, using `ibus-setup`.

I honestly don't know how to fix this - VSCode cannot change default shortcut keys every time any random OS decides to introduce a new hotkey, but I would bet nobody involved in this affair from the other side of the aisle are interested in conforming to any kind of good UX standards that will prevent similar issues from cropping up in the future.

**Comment by ulugbekna** [comment]
Hi @SRNissen ,

Thank you for filing this issue and understanding the difficulty here in dealing with the abundance of OSes and shortcuts they have.

If you want to use `ctrl+shift+e` to focus the vscode explorer, try disabling the OS shortcut, if possible.

Otherwise, I would recommend to change the shortcut for the explorer to something that doesn't clash with the OS. 

Unfortunately, that's not something we can fix on our end.
