### ISSUE TITLE
API doesnt update settings if there are trailing commas in settings.json

### ISSUE THREAD

**Issue by shanalikhan** [Microsoft/vscode#19625]
Users of my Settings sync extension having problems https://github.com/shanalikhan/code-settings-sync/issues/190

When they have trailing commas in settings.json , API doenst allow extension to add keys and values in settings.json file , Giving error code `4`.

There should be way in code to let users know that they dont have valid JSON in settings.json file e.g trailing commas, without opening that file may be in status bar or let API to add settings in the settings.json file even it have trailing commas.

**Comment by bpasero** [comment]
I think it would be nice if we would allow to edit a JSON when it has trailing commas.

/cc @sandy081

**Comment by sandy081** [comment]
@aeschli I had implemented this in Config edit service in last milestone when writing into the model. This is to ignore errors. But in this case, we write into the disk directly, so ignoring errors might not be a good idea. So how about having an option to ignore trailing comma (to json language server not sure) so that the json is still valid ?

**Comment by bpasero** [comment]
Yeah, +1 for only ignoring trailing commas but not in general any error.

**Comment by aeschli** [comment]
The json parser that we use (json.ts, our own implementation) already ignores trailing commas. It doesn't matter of the file is written to disk or not, as its our file and we read it.
I was assuming the bug is in json edit processor (without digging deeper into it) (jsonEdit.ts). Don't you use the json edit processor to modify the settings?

**Comment by sandy081** [comment]
I use the json parser ([json.ts](https://github.com/microsoft/vscode/blob/master/src/vs/base/common/json.ts#L1)) which is giving errors while parsing the json. This is pre-validation step before writing. If there are errors in parsing here, we quit (if it is writing to disk).

**Comment by aeschli** [comment]
Ok, errors are reported, but the parser continues to parse and will report all properties.
Feel free to add an pption to also not emit an error. https://github.com/microsoft/vscode/blob/master/src/vs/base/common/json.ts#L1115

**Comment by sandy081** [comment]
Sure will do. Thanks for the pointer.

**Comment by sandy081** [comment]
@aeschli Fixed it as we discussed
- Defining a new option to allow trailing comma in json parser
- Config edit service provides this option while parsing

**Comment by bpasero** [comment]
Awesome!

**Comment by sandy081** [comment]
To verify:

- Have a trailing comma in the settings file
- Try to update a setting that uses the API underlying. For eg: `Toggle Word Wrap`. This should succeed

**Comment by bpasero** [comment]
This is a great fix!
