### ISSUE TITLE
Highlights flicker when clicking on them

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#196355]
Testing #196342

* enable `editor.multiDocumentOccurrencesHighlight`
* open `src/vs/workbench/contrib/inlineChat/common/inlineChatServiceImpl.ts` and `src/vs/workbench/contrib/inlineChat/common/inlineChat.ts` side by side
* select `IInlineChatSessionProvider`
* click on occurrences
* :bug: whenever an occurrence is selected for the first time all highlights disappear and reappear

This also happens in the single document highlight case and I am sure is a regression

**Comment by Yoyokrazy** [comment]
Looks like this is fixed with https://github.com/microsoft/vscode/pull/196642. Seems like two birds, one stone. Cannot repro in OSS with latest `main`.

Insiders behavior (broken)
https://github.com/microsoft/vscode/assets/12552271/edbae45c-6998-4b5e-9e31-2a076c91179d

latest OSS (fixed)
https://github.com/microsoft/vscode/assets/12552271/8e872601-29a7-4db0-a3a4-27bfbffd2c2f

**Comment by Yoyokrazy** [comment]
bug for verification

**Comment by alexdima** [comment]
@Yoyokrazy Also the milestone should be set.
