### ISSUE TITLE
move debug adapter protocol to separate repository

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#19636]
move [debug adapter protocol schema](https://github.com/Microsoft/vscode-debugadapter-node/blob/master/debugProtocol.json) and accompanying documentation (Readme.md) to a separate repository.

**Comment by svenefftinge** [comment]
Any progress here?
Can we somehow help get this going?

**Comment by smarter** [comment]
It'd be great to see some work towards standardizing the vscode debug protocol following the success of the LSP (see also https://github.com/Microsoft/vscode-debugadapter-node/issues/59), and this would be a good first step.  Getting other IDEs to implement the vscode debug protocol would be especially useful now that the [Java Debug Server](https://code.visualstudio.com/blogs/2017/09/28/java-debug) has been released.

**Comment by weinand** [comment]
Is the fact that the [debug protocol](https://github.com/Microsoft/vscode-debugadapter-node/blob/master/debugProtocol.json) lives in https://github.com/Microsoft/vscode-debugadapter-node  blocking anyone from adopting it?

**Comment by gorkem** [comment]
@weinand I think debug protocol feels more like an internal vscode thing than LSP. It starts with the name of the repositories, LSP lives on [language-server-protocol](https://github.com/Microsoft/language-server-protocol) vs the [vscode-debugadapter-node](https://github.com/Microsoft/vscode-debugadapter-node) which is prefixed vscode. README file for the debug things repo also does help either.  It only talks about VS Code and has no information around contribution. I love the fact that there is a json schema for debug protocol but there is no information on the repository that schema is the source of truth for the protocol. At the moment,  it is even a bigger leap of faith (yeah, I think LSP needs open governance) for Eclipse Che, Atom or any other editor to adopt debug protocol. And because it feels like an internal implementation so far Red Hat could not consider it for adoption.

**Comment by CestDiego** [comment]
This feature has great potential. I believe that with more documentation and some in-house guides on how to create adapters for other editors (starting with Atom maybe?) this would be a step in the right direction.

**Comment by weinand** [comment]
@CestDiego The idea behind debug adapters is to be **independent** from a debugger frontend (IDE). So "creating adapters" for Atom doesn't make any sense. The correct approach would be to **host** debug adapters in Atom.

**Comment by weinand** [comment]
The DAP now lives here: https://microsoft.github.io/debug-adapter-protocol/
