### ISSUE TITLE
Restoring comments again duplicates them

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#196574]
Testing #193104

1. Follow the pre-requisites from https://github.com/microsoft/vscode/issues/193104
2. In a file, sprinkle three separate comments.
3. Store changes in Cloud.
4. In another machine, same file, restore changes in Cloud. All three comments show up.
5. Update the first comment by adding a line.
6. Store changes in Cloud.
7. Back to the first machine, restore changes in Cloud.

🐛 Now there are 6 comments. All "new" 3 have been appended to the 3 existing comments.

**Comment by alexr00** [comment]
Good bug, thanks for finding!

**Comment by alexr00** [comment]
@joyceerhl I can't reproduce this. Are you using 2 separate machines (or equivalent) + desktop VS Code?

**Comment by rzhao271** [comment]
LGTM.

Some notes:
- I had to add a line to the PR to get the changes to store the first time, which corresponds to step 4 of https://github.com/microsoft/vscode/issues/193104
- After restoring on the second machine, the PR comments didn't automatically show up. I had to refresh the PR for the comments to show up or update.

Adding verified because no duplicate comments showed up.
