### ISSUE TITLE
memory leak when clicking already open notebook files in the Explorer

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#196861]
Steps to Reproduce:

1. Open a saved notebook
2. Click the notebook file in the explorer a bunch of times.
🐛 A new `notebookEditorInput` is created for each click, and previous ones are not disposed

For each click, the editor is resolved, which calls the registered factory method `selectedEditor.editorFactoryObject.createEditorInput(editor, group)` in the `EditorResolverService`.
It looks like text editors hold a cache so that the inputs get re-used, but I'm a little surprised that the implementors of those `create` methods would be expected to handle it that way.

**Comment by amunger** [comment]
This also applies to replacing editors in place in the case of renaming the file with a case difference on Windows. A new editorInput is created for the new resource, and the model is updated, but the old editorInput is still used.

**Comment by bpasero** [comment]
Yes, this is (currently) up to the editor implementation to do. I am not sure we can just build this from the outside because we would not know if the same editor should be cached across multiple editor groups or not. 

File and untitled editors build their own caching and the same input is always used even across groups.

**Comment by amunger** [comment]
Anything specific that I should be concerned with when sharing EditorInputs between groups? When would an editor not want to do this?

**Comment by bpasero** [comment]
No nothing specific that I can think of.
