### ISSUE TITLE
how i fix this?

### ISSUE THREAD

**Issue by ghambar-moz** [microsoft/vscode#196821]
023-10-15 19:16:40.405 [error] Unexpected non-whitespace character after JSON at position 1206: SyntaxError: Unexpected non-whitespace character after JSON at position 1206
    at JSON.parse (<anonymous>)
    at Object.factory (c:\Users\GhazalCO\AppData\Local\Programs\MicrosoftVSCode\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:99:85837)

**Comment by GeekyShacklebolt** [comment]
Yes, getting the same error upon install extensions.

```
[error] SyntaxError: Unexpected non-whitespace character after JSON at position 29622
    at JSON.parse (<anonymous>)
    at Object.factory (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:99:85837)
```

I recently fresh installed v1.83.1.

**Comment by alexr00** [comment]
Can you share steps on how to trigger this error?

**Comment by GeekyShacklebolt** [comment]
Hey @alexr00 !

Not sure how to reproduce it. But here are the events that let this error happen in my case.

**Context**
* I previously had vscode installed on my machine but I hardly used it. But I remember that I installed a couple of extensions in it using the vscode GUI options. Those were successful installs.
* Then recently I thought to upgrade vscode to the new version, so I uninstalled the older vscode and downloaded the 1.83.1 version to install.
* Installation was successful.
* Then I went to install extensions. But this time instead of installing extensions through GUI, I attempted to install these through command line. I attempted to install a [lot of extensions](https://github.com/CuriousLearner/dotfiles/blob/master/setup/vscode/install-extensions.sh) in a single command like
```shell
code --install-extension bradlc.vscode-tailwindcss --force &
code --install-extension budparr.language-hugo-vscode --force &
code --install-extension charliermarsh.ruff --force &
...
```
* half of the installation went smooth, then in the middle I started receiving this error message
```
[error] SyntaxError: Unexpected non-whitespace character after JSON at position 29622
    at JSON.parse (<anonymous>)
    at Object.factory (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:99:85837)
```
* since then, I am unable install packages via GUI option, everytime I try I get this error in logs.
* I have tried uninstalling, re-installing it doesn't help.
* I am on MacOS ventura 13.6
* This is happening in vscode 1.83.1

**Comment by alexr00** [comment]
@sandy081 I looked at the error location in 1.83.1, and it appears to be coming from here:

https://github.com/microsoft/vscode/blob/0b1e8b379dfb06beec92d6846224bfb7d72aa018/src/vs/platform/extensionManagement/common/extensionsProfileScannerService.ts#L228

**Comment by sandy081** [comment]
Please open `extensions.json` file in the folder where extensions are installed. Looks like this file was corrupted. Delete this file and start VS Code again.

**Comment by GeekyShacklebolt** [comment]
Hey @sandy081 ,
Awesome thanks, this helped. I deleted my `~/.vscode/extensions/extensions.json` file, and now the issue is fixed, I can install extensions from UI. Thanks again!

The title of this issue is not very helpful for others to find it on google, I can't edit it. Hey @ghambar-moz could you please change the title of this issue to sound it more related to the error?
