### ISSUE TITLE
Support virtualization in Code action list

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#196857]
while working on a python/notebook file, language server suggests tons of code actions, which blocks the UI for ~5 seconds

<img width="2229" alt="image" src="https://github.com/microsoft/vscode/assets/876920/bce962ec-99d8-4fcc-8f6c-2bad0a6b0f45">

**Comment by rebornix** [comment]
The UI freeze is caused by DOM reads

![Uploading image.png…]()

**Comment by justschen** [comment]
related to https://github.com/microsoft/pylance-release/discussions/3873

**Comment by mjbvz** [comment]
The list is already virtualized but this `layout` call forces the entire thing to render (before correctly shrinking it back down):

https://github.com/microsoft/vscode/blob/e9b6a7750d320eb5cb9c6f47f0372b3adac44b58/src/vs/platform/actionWidget/browser/actionList.ts#L248

The layout call is used to find the max width of the items in the list and then resize the widget to fit this. I'm not sure what the best way to do this for a list is, but at the very least we could probably make a single call to `getBoundingClientRect` on the container node instead of on each element

**Comment by justschen** [comment]
After change from above PR
<img width="1097" alt="Screenshot 2023-11-22 at 1 56 32 PM" src="https://github.com/microsoft/vscode/assets/54879025/17a2c73a-35ad-4027-9b69-4acdee2300b2">
