### ISSUE TITLE
VSCode tasks using different node path than integrated terminal

### ISSUE THREAD

**Issue by mclean25** [microsoft/vscode#196930]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.83.1
- OS Version: MacOS 14.0 (23A344)

Steps to Reproduce:

My `tasks.json`:

```
{
    "version": "2.0.0",
    "tasks": [
      {
        "label": "Which node",
        "type": "shell",
        "command": "which",
        "args": ["node"],
        "options": {
          "cwd": "${workspaceFolder}"
        },
        "group": {
          "kind": "build",
          "isDefault": true
        },
        "presentation": {
          "reveal": "always",
          "panel": "dedicated"
        },
        "problemMatcher": [],
        "isBackground": true
      },
   ]
}
```

If I open a terminal in VSCode and run `which node`, I receive this `/Users/alex/.nvm/versions/node/v18.17.1/bin/node`
But if I run the task `which node`, it will output this `/usr/local/bin/node`

This causes lots of issues as the Node version ends up being very different in some cases. Both are using my `zsh`, and when I run `which zsh` in both places like above they both resolve to the same spot. How can this be?

**Comment by KhushiSharma0313** [comment]
It seems like your issue might be related to the way the PATH environment variable is set and managed. When running commands in VS Code tasks, it might be using a different PATH variable than your interactive shell.

Here are some steps to diagnose and potentially resolve the discrepancy in the Node versions:

1. **Check the environment variables:**
   - In the VS Code terminal, type `echo $PATH` to check the PATH variable set within VS Code.
   - In your regular terminal, type `echo $PATH` to check the PATH variable in your interactive shell.

2. **Compare the PATH variables:**
   - If the PATH variable is different between the VS Code terminal and your regular terminal, that might be the root cause of the discrepancy in the resolved Node versions.

3. **Modify VS Code task to use the absolute path:**
   - Instead of relying on the PATH variable in the VS Code task, you might directly specify the absolute path to the Node binary. For example:
   
   ```json
   {
       "version": "2.0.0",
       "tasks": [
           {
               "label": "Which node",
               "type": "shell",
               "command": "/Users/alex/.nvm/versions/node/v18.17.1/bin/node",
               "options": {
                   "cwd": "${workspaceFolder}"
               },
               "group": {
                   "kind": "build",
                   "isDefault": true
               },
               "presentation": {
                   "reveal": "always",
                   "panel": "dedicated"
               },
               "problemMatcher": [],
               "isBackground": true
           }
       ]
   }
   ```

4. **Adjust the PATH variable in VS Code:**
   - You can modify the PATH variable in VS Code settings to match the one in your regular terminal. This might involve adjusting settings or profile files in VS Code or adding the necessary paths in the task's environment.

5. **Debug the PATH issue:**
   - If the PATH variables are different, you might need to debug why they are set differently. Check shell configuration files like `.bash_profile`, `.zshrc`, or others. VS Code might not be loading the same configuration files as your interactive shell.

6. **Update VS Code or Extensions:**
   - Ensure that both your VS Code and any relevant extensions are updated to their latest versions, as there might have been fixes or enhancements related to this behavior in newer releases.

By comparing the PATH variables and possibly adjusting how the Node binary is referenced in the task, you might be able to resolve the discrepancy between the versions of Node being used in VS Code tasks and your regular terminal.

**Comment by mclean25** [comment]
Yes, that appears to certainly be the issue. I haven't tried your fixes yet but I'm going to post what I was looking into:

From running task:
```
 *  Executing task: which -a node 

/usr/local/bin/node
/Users/alex/.nvm/versions/node/v18.17.1/bin/node
 *  Terminal will be reused by tasks, press any key to close it. 
 ```
 
In VSCode integrated terminal:
```
❯ which -a node
/Users/alex/.nvm/versions/node/v18.17.1/bin/node
/usr/local/bin/node
/Users/alex/.nvm/versions/node/v18.17.1/bin/node
```

**Comment by mclean25** [comment]
I think the issue is likely from here: https://github.com/microsoft/vscode/issues/187955

**Comment by meganrogge** [comment]
Yes, same as #187955

/duplicate
