### ISSUE TITLE
Extension packs: allow to specify explicit extension version

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#197023]
Extension packs need to be able to specify and explicit extension version of a containing extension.

We should only support equals.

Use case: I am an extension author of a very popular pack. And I want to add a dependency for an extension that I reviewed from another extension author. I do not want to allow that other extension author to auto update their extension without my review. Thus I want to have specify an explicit version in my pack.

**Comment by alefragnani** [comment]
Hi @isidorn ,

I totally understand, and agree, with the motivation to pin specific version of _third party_ extensions contained on your pack. But I think instead of only support equals, it should follow semantic versioning, just like node dependencies, specially if the pack is filled with your own extensions only. 

I mean, I created the [Delphi Extension Pack](https://marketplace.visualstudio.com/items?itemName=alefragnani.delphi-pack) containing solely my own extensions, smiply to provide an easy to use Delphi experience. Microsoft itself publishes a few packages containing only their own extensions, like the [C/C++ Extension Pack](https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools-extension-pack), and the [Remote Development](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.vscode-remote-extensionpack). 

Forcing the publisher to specify an explicit version of the containing extension would require republishing those packs as frequent as the extensions contained in it.

Thank you
