### ISSUE TITLE
onDidChangeTabs is not triggered when switching between split custom editor tabs

### ISSUE THREAD

**Issue by deser** [microsoft/vscode#197256]
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version: Version: 1.84.0 (Universal)
- OS Version: OS: Darwin arm64 22.6.0

Steps to Reproduce:

1. Subscribe to `vscode.window.tabGroups.onDidChangeTabs`
2. Open 2 custom editors for different files in split view (1 editor in left tab group 2nd in the right)
3.  Switch focus from 1 tab to another
4. Observe that **no** `onDidChangeTabs` event fired
5. Move tab 2 into the same tab group as for tab 1 (unsplit).
6. Switch tab focus between the tabs and observe that `onDidChangeTabs` event **is** fired

**Comment by bpasero** [comment]
I think this is normal behaviour, I see the same when switching between 2 text editors across 2 groups. So this seems unrelated to custom editors?

**Comment by lramos15** [comment]
Yeah it may be as designed to be honest. This is the complexities of having the event owned by the top level `tabGroups`.

The reason no event is fired is because each tab is active within its own group so switching between the groups doesn't switch the tabs but instead just fires a `onDidChangeTabGroups` that changes the `isActive` property
