### ISSUE TITLE
Showing occurrences breaks after finding references

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode#197224]
# Description 

Having a cursor on a symbol shows occurrences of that symbol. Triggering "Go to references" on that symbol shows the references view, after closing this view, the occurrences aren't shown anymore. 

https://github.com/microsoft/vscode/assets/16353531/8370aad5-e0ed-44b5-b7d6-c3f54cca2fd6

# Repro

1. In a typescript file, put the cursor on a symbol with a couple of references
2. Trigger "Go to references" on that symbol
3. Close the references view
4. :bug: Occurrences disappear

# Version

```
Version: 1.85.0-insider
Commit: 98417b150aeb47dd81dc58893789da4b4cb0e095
Date: 2023-11-01T18:38:57.852Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 23.0.0
```

Can't repro with 1.84 stable, so should not be a candidate. But feel free to also try repro-ing.

**Comment by Yoyokrazy** [comment]
Revisiting this now after a lot of work to the occurrence highlighting in general. My opinion is to close this as expected behavior. 

When you trigger go to occurrences (`shift+f12`), the code editor you are in is blurred, and focus gets shifted to the list view on the right side of the peek. This allows the arrow keys to jump between occurrences (which are highlighted in the peek editor). Additionally, clicking into the peek editor will highlight occurrences within that peek editor and also the blurred code editor if you have occurrences highlight set to `multifile` in the latest versions of vscode.

I think this mostly aligns with how we treat a loss of focus throughout the rest of the editor, ie clicking from an editor to the debug console, file explorer, or an outline view for ex. Your focus would now be in that view, and you would lose highlights in the previous editor. Returning to that editor (closing the peek view, clicking to the tab, or just an alt-arrow would then trigger an occurrence request and re-highlight based on the cursor position. (this exact behavior will come with https://github.com/microsoft/vscode/pull/227607/files)
