### ISSUE TITLE
Trigger willSave even if file is not dirty to support code formatters

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#19723]
- VSCode Version: 1.9.x
- OS Version: Windows.

With the introduction of `willSave` events extensions provide code which for example format on save or fix errors on save (eslint, tslint). All these will save participants do nothing if `autoSave` is set to `afterDelay` since the text manipulation could infer with typing. For example a user types `{}`, save kicks in and the linter removed the empty block because it is superfluous.

To still give users a single short cut to trigger all code cleanup actions it would be cool if we can bind these to `Ctrl+S` if `autoSave === delay`. We could do the following: if `autoSave === delay` and the file is saved, trigger `willSave`. If `willSave` changes the document (makes it dirty) save the document and trigger save event. If the document is not dirty after will save do nothing.

@jrieken FYI.

**Comment by bpasero** [comment]
I think there are 2 pieces to the solution:

**File is dirty and user invokes save manually (Ctrl+S)**
I think in this case we can just ignore the auto save setting and treat this as a manual save that triggers all save participants. In fact I was actually assuming we do this today already but I might be wrong.

**File is NOT dirty and user invokes save manually (Ctrl+S)**
Today we literally do not run through the save code at all, we leave very early because the file is not dirty. With the advent of save participants, we actually do not know if a participant might make the document dirty again (e.g. format), so in this case we should probably run the participants and again treat the save as an explicit save not triggered from auto save.

**Comment by dbaeumer** [comment]
@bpasero I can confirm that the first case works. I tested it today.

**Comment by bpasero** [comment]
Ok awesome.

**Comment by dbaeumer** [comment]
Thanks!

**Comment by bpasero** [comment]
* [ ] to verify: you can trigger save participants (e.g. formatting) by Ctrl+S(aving) a document even when it is not dirty and the participants will trigger and can change the document.
