### ISSUE TITLE
How to handle empty CodeLenses?

### ISSUE THREAD

**Issue by fbricon** [Microsoft/vscode#19724]
- VSCode Version: 1.8.1, 1.9-insiders
- OS Version: All

So the vscode-java extension relies on the Java Language Server to provide CodeLenses to VS Code. We have, as per the language protocol, 2 calls:
- document/codeLens: which lists all the places in the current document that might have references. This calls returns fairly quickly
- codeLens/resolve: will actually compute all references to the given codelens (the ones currently displayed on screen), it's time a consuming operation.

In the case of vscode-java, when no references are found, we return/display `0 references` as a codelens label, which is fairly annoying, as it eats some screen real estate. 

![](https://cloud.githubusercontent.com/assets/865769/22558569/24398e7e-e93c-11e6-8cc8-0614cf52fa43.png)

Eagerly resolving codelenses during the `document/codelens` call would help but it is not an option, for performance reasons.

Even returning an empty label adds unnecessary pseudo-lines, moving some code off the screen.

So I was wondering: what's the best way to handle that use case? Is there a way to return special codelenses that would not generate these extra lines, or is this something that could be fixed at the vscode level, i.e, when the codelens label is empty, release that extra space? Or maybe there's another approach?

This relates to  https://github.com/redhat-developer/vscode-java/issues/148

**Comment by bpasero** [comment]
Assigning a bunch of people because I am actually not sure who is best to answer this.

**Comment by jrieken** [comment]
Yeah, there are with the January release two options: 

1. You keep doing this and either say '0 References' or something like 'No References' which takes away screen real estate but has the big advantage of keeping things stable, or
2. You use the newly introduced [`onDidChangeCodeLenses`](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L1601)-event to signal to the editor that the set of code lenses has changed (like after typing). That will allow you to take away lenses but it might result "nervous" UI because lenses or their space keep appearing and disappearing
