### ISSUE TITLE
Default language-specific settings

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#19733]
Now that we have language specific settings we should consider enabling default language-specific settings to work around some of the annoyances for particular languages:

**Markdown**: Disable intellisense by default:

```js
"[markdown]": {
"editor.quickSuggestions": false
}
```

**Makefile**: Always use tabs for indentation since spaces are invalid (related: https://github.com/Microsoft/vscode/issues/4815)

**YAML**: Always use spaces for indentation since tabs are invalid.

**Comment by rmunn** [comment]
Python: default to spaces since [PEP 8](https://www.python.org/dev/peps/pep-0008/#tabs-or-spaces) recommends spaces as the standard Python coding style.

F#: default to spaces since [the F# code formatting guidelines](https://docs.microsoft.com/en-us/dotnet/articles/fsharp/language-reference/code-formatting-guidelines) forbid using tabs.

**Comment by Tyriar** [comment]
@rmunn Python might be going a bit far since it still works with tabs right?

**Comment by rmunn** [comment]
@Tyriar Yes, Python does allow tabs, even though its official style guide recommends spaces. But setting spaces as the default in VS Code wouldn't prevent anyone from overriding them with tabs if they choose. I believe that if a language has an **official** style guide, then any editor capable of per-language settings should *default* to following that style guide, so that out of the box, the editor will produce code that complies with the style guide. And for Python, that means space indentation, and 4-space indents (https://www.python.org/dev/peps/pep-0008/#id17). Therefore, that's what VS Code should default to for Python files.

**Comment by rmunn** [comment]
Two questions that will probably come up regarding language-specific defaults:

- If the language default specifies space indentation but you open a file that uses tab indentation, which one wins? The language default, or the file's previous indentation?
- If the language default specifies one setting but an `.editorconfig` file in the project folder specifies a different setting (and the user has installed the EditorConfig plugin), which should win?

My personal opinion is that the second answer is obvious: `.editorconfig` is a way to specify a project-specific set of coding standards, and more specific settings should always override less specific settings. Therefore, the `.editorconfig` file should trump the language default settings if the two conflict.

The first answer is less obvious, but I think in the case of editing an existing file that does not match the language-specific settings, the file's existing indentation style could be considered a "more specific setting", specific to that file. E.g., if the Python standards say "uses spaces for indentation", but I'm working on someone else's code where the other coder used tabs, the editor should default to using tabs *for this one file*, because that creates consistent indentation. (This is also in line with what PEP 8 says, which is "Tabs should be used solely to remain consistent with code that is already indented with tabs.")

So I think the following set of rules would be good ones to use regarding language-specific defaults:

- If the language-specific settings for indentation conflict with what can *easily* be autodetected from the file (e.g., spaces vs. tabs), then the file's existing indentation style should trump the language-specific default settings.
- If the language-specific settings for indentation conflict with an `.editorconfig` file in the project folder, then the `.editorconfig` file should trump the language-specific default settings.

**Comment by sandy081** [comment]
@rmunn Good questions and suggestions.

Agreed that `.editorconfig` always takes the precedence over defaults/user/workspace settings which is also true currently. 

Regarding file specific conflicts, you can always say detect the indentation from the file using the property `editor.detectIndentation: true`. By setting this, editor will always take the indentation from the file which overrides defaults/user/workspace/editorconfig settings. This would be same for default language based editor settings. With this new feature, language extensions can also register this setting to true which will let indentation from file takes the precedence above all.

**Comment by sandy081** [comment]
Here is how an extension can contribute default language specific editor configurations. A new contribution point `configurationDefaults` is introduced in extension's package.json. 

Sample:

```json
"configurationDefaults": {
	"[markdown]": {
		"editor.wrappingColumn": 0,
	        "editor.quickSuggestions": false
	}
}
```
