### ISSUE TITLE
Layout menu sorting

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#197336]
<img width="418" alt="image" src="https://github.com/microsoft/vscode/assets/900690/332a4d14-e0ed-4358-8770-a6523a35957e">

I wonder: should the menus with submenus be grouped together and the one ("Move Primary Sidebar Right") without move to the top? Or is there a specific reason for this sorting.

**Comment by gjsjohnmurray** [comment]
I also wonder whether a "Customize Layout..." option should be added to this section to increase visibility of that widget, especially for folk who don't have the right-hand-end titlebar button for getting to it.

Perhaps "Customize Layout..." could replace "Move Primary Side Bar Right" (yes, there may be some people who will object to its disappearance). If so, I think it belongs at the bottom of the group rather than at the top.

**Comment by sandy081** [comment]
@gjsjohnmurray Good idea, can you please make it a separate request?

**Comment by gjsjohnmurray** [comment]
> @gjsjohnmurray Good idea, can you please make it a separate request?

Done - #197344
