### ISSUE TITLE
Timeline view in sidebar opens automatically on launch

### ISSUE THREAD

**Issue by atri-dastidar-snkeos** [microsoft/vscode#197334]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.84.0 (user setup)
Commit: d037ac076cee195194f93ce6fe2bdfe2969cc82d
Date: 2023-11-01T11:29:04.398Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19044

Steps to Reproduce:

1. Launch VS Code (with an open folder)
2. Show explorer view if not already visible
3. Timeline view will be visible/expanded
4. Collapse the Timeline view
5. Exit and relaunch VS Code
6. Timeline view is visible/expanded again (expected behavior: it shall remain collapsed)

**Comment by in-in** [comment]
After a few days of working with it, I find this thing extremely annoying and it has almost become something I despise 😤
![23311030919](https://github.com/microsoft/vscode/assets/8797432/97e9b342-0010-4165-8e6b-eb50b8813337)

**Comment by plashenkov** [comment]
Very annoying!

**Comment by aliuq** [comment]
Same issue

**Comment by atri-dastidar-snkeos** [comment]
For now I just hide the Timeline completely from the Explorer view (right click on the Timeline bar and de-select it from the menu):

![image](https://github.com/microsoft/vscode/assets/1412951/00dd97ea-ea2d-4b5d-be12-65417d2e9d4a)

**Comment by starball5** [comment]
Related on r/vscode: https://www.reddit.com/r/vscode/comments/17ue45q/why_does_expandedcollapsed_state_of_the_timeline/

**Comment by gjsjohnmurray** [comment]
I think this was caused by #195665, specifically this code:

https://github.com/microsoft/vscode/blob/773e2b4dbfda2fabba86702d4b0016af74983f66/src/vs/workbench/browser/parts/views/viewPaneContainer.ts#L1071-L1075

I can repro it reliably if I first move the Outline view out of the Explorer view container, for example by dragging it onto the Secondary Side Bar.

Here's what I see happening.

1. On startup the Timeline view initially gets added alone to the empty Explorer view container, causing the code above to expand it (and also set it non-collapsible).
2. Very soon after, the Explorer view (and maybe the Open Editors view) get added. Now there's more that one view in the container, so the else-block immediately after the fragment shown above sets them all collapsible, but Timeline remains expanded.

pinging @sandy081

**Comment by gjsjohnmurray** [comment]
I have submitted a PR.

**Comment by starball5** [comment]
Related on Stack Overflow: [VS Code Timeline view isn't collapsed by default](https://stackoverflow.com/q/77522118/11107541)
