### ISSUE TITLE
Consolidate and update built-in walkthrough content

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode#197503]
I observe a few bits of low-hanging fruit that we could go after to improve the built-in walkthroughs. As they stand today, I noted that:
- 3 distinct walkthroughs feels like a lot—and is probably asking for a big drop off after the first one
- New user pain points (getting started content, pointer to settings) are buried

What if we consolidated the 3 walkthroughs into 1 or 2, and had a pointer to docs/YouTube/etc. for some of the additional content? We could also pull up steps related to intro videos and settings as part of the changes.

cc @bhavyaus

**Comment by daviddossett** [comment]
Preview of initial changes proposed in #197689:

![CleanShot 2023-11-07 at 15 27 22@2x](https://github.com/microsoft/vscode/assets/25163139/29abb2f2-b037-4b20-bc7c-03d0123b5ea8)

![CleanShot 2023-11-07 at 15 29 01@2x](https://github.com/microsoft/vscode/assets/25163139/7387d819-a54e-4f53-acf7-ed8627ee5403)

**Comment by sandy081** [comment]
This pushed Settings Sync down in the list. Any reasoning for this?

CC @isidorn @bhavyaus

**Comment by daviddossett** [comment]
1) Settings sync is almost certainly an unexpected concept be presented with when installing and opening VS Code for the very first time. The getting started walkthrough was intentionally designed to have users step through the basics—theme, lang extensions, open a folder, etc. Settings sync is important, but I strongly oppose this being first in the list. 
2) These latest changes pulled the Settings UI and tutorial videos steps into the 1st walkthrough in response to the NPS verbatims claiming users couldn't find or understand those things. After pulling in the Settings step, it makes sense to co-locate settings sync with it. In fact, I'd actually consider putting both CTAs on the same setp (Open Settings | Backup and Sync Settings). For the moment they are still discrete steps.

I'm more than happy to play with the positioning. I just don't think it should be first just to move a metric.

**Comment by daviddossett** [comment]
This is a devtools hack, but you get the idea. We could have a shared step e.g. 

![Image](https://github.com/microsoft/vscode/assets/25163139/e3b75610-e221-4efa-a2ac-bafa3fa01918)

Just one idea!

**Comment by IAmHopp** [comment]
Just to add my experience here: It just so happens I recently installed Insiders on a new machine and I saw this page for the first time. I understand if it stays that way if it's backed by user research, but it did confuse me that retrieving my synced settings wasn't the first thing that was proposed to me.

To be clear, I didn't know it was the first option before because I haven't gone through the first-use experience in a long, long time. But it was my immediate expectation.

The first thing it asked me for was choosing a theme. And, well, if I already have that setting saved in the cloud...
