### ISSUE TITLE
Finish migrating 'interactive' chat panel APIs to "chat agents"

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#197687]
Tracking further work on the ChatAgents2 API.

- Needed to fully get rid of `interactive` chat API
    - [x] A static contribution for the default agent. This is so we know to show the chat view even before the extension is activated and logged in
        - Try to avoid a static contribution, cache that we previously had a chat provider and wait a bit for it to be registered
        - Could optimistically register the chat agent from the extension side to speed things up
    - [x] Add welcome message/sampleQuestions to the default agent
        - Can add a provider for this, use a separate type for the followups
    - [x] Add requesterUsername/icon to the default agent
    - [x] `transferChatSession` can't use a Session object- it could take a `ChatAgentResult2` instead?
        - This is a weird case, shouldn't have a global function that takes a private object. Other options: a workspace uri property on the result, an argument to vscode.openFolder, a separate api command
    - [x] `sendInteractiveRequestToProvider` can't work on a providerId. Should it be api (generic `sendChatRequest`) or an api command?
        - It should be possible to get rid of this
    - [x] Get rid of the global `interactiveUserActions` proposal event, move those types into `chatAgents2Additions` and rename
    - [x] Should `InteractiveSessionReplyFollowup` keep its `metadata` property, or should we return the same instance back to the extension in `onDidPerformAction` so it can add its own custom properties?
    - [x] `/help`: https://github.com/microsoft/vscode/issues/197081
- Other API improvements
    - [x] More doc comments
    - [ ] ~~Make interfaces classes~~
    - [ ] https://github.com/microsoft/vscode/issues/199908

**Comment by umpox** [comment]
API Feedback (apologies if I've overlooked anything):

These changes seem to suggest that the only way to access the `interactive` UX flow would be to register as an agent. However that seems to take away a lot of control that I would otherwise have, it seems quite strictly gated for other extensions - especially ones that do not have as much sway to influence internal VS Code development.

How can I, as a third-party extension, use the `interactive` chat UX after this proposal?

**Comment by roblourens** [comment]
Sorry, I don't really understand the question. What is it you want to do?

Yes, the extension model that we are focused on right now is for extensions to contribute chat agents which can be invoked through the chat view.

**Comment by umpox** [comment]
@roblourens Apologies, I was out on vacation last week - only just saw this!

**What I want to do:**

I, as a third party extension, want to provide the most optimal user experience to my users. The `interactive` chat API is a great API proposal that I have been following because it provides numerous benefits for my use case. It is a great tool for cases where a user can provide an input or a task, and an extension can reply with an example of some proposed changes that the developer can quickly review and then accept, discard or amend.

There is no alternative API that VS Code currently offers that provides a similar experience.

**My concern with the direction of this change:**

By removing this API, and requiring that developers register as a "chat agent", I am losing much of the control I would otherwise have as a third-party extension. What if I want to trigger the interactive UX from a codelens? Or from a keyboard shortcut? I believe enforcing these constraints will make it harder for extensions to build great user experiences and will be detrimental for VS Code users.

Furthermore, it seems that "chat view" is "Copilot Chat"[1][2]. This raises many further concerns to me, does a user need to install Copilot before they can use my intended functionality? Does this mean I have a coupling with another third party extension? Does the user need an active Copilot subscription?

I think providing **both** mechanisms (`ChatAgents2` and `interactive` APIs) is great. I think constraining extensions to only use `ChatAgents2` is bad.


[1] [Blog post](https://code.visualstudio.com/blogs/2023/11/13/vscode-copilot-smarter) Referenced many times and "we added the concept of agents to Copilot Chat."
[2] [Demo extension](https://github.com/microsoft/developer-platform-vscode-chat) 
<img width="420" alt="image" src="https://github.com/microsoft/vscode/assets/9516420/c69db9ed-d719-416b-8705-29f4c5b0adfe">

**Comment by roblourens** [comment]
Thanks. It is true that the extensibility experience will be based around contributing chat agents to the Github Copilot Chat view for now. But I don't think that this excludes triggering the chat from other UX surfaces like a codelens or keyboard shortcut. We are already hooking up lots of other entrypoints like quick fixes and hovers, and that will be possible for any extension.

**Comment by umpox** [comment]
@roblourens I think gating features like this so that they can only be used via GitHub Copilot Chat is unfair to other extensions and unfair to users.

GitHub Copilot Chat is one of **many** extensions that interface with LLMs (via chat or directing editing code). This change means that Copilot is the **only** extension that is allowed to use this improved user experience flow. That is not a level playing field.

I hope you will reconsider this direction and consider opening up the `interactive` API for other extensions.
