### ISSUE TITLE
terminal.integrated.commandsToSkipShell is unintuitive

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#19770]
The `commandsToSkipShell` setting requires users to override the entire list, this sucks for users as they need to add a bunch of stuff to their settings.json file, it sucks for us and users because the list can change between versions.

An example: https://github.com/Microsoft/vscode/issues/19751

Maybe the ability to add and remove instead of setting an absolute list would be better? How would the default list be communicated if so?

I'm open to feedback on how to solve this :smile:

**Comment by kaiwood** [comment]
Ok, this one is really, really ugly to solve in a user friendly way. You would need to either have a completely user managed array that gets outdated as soon as a new default gets added. Or you have two arrays to remove and add from a default array which can't be represented in a sane way via the current `settings.json`. Not the best choice to make.

As far as I understand the motivation for the skipped commands, it's to make various shortcuts work "cross-pane".

Most of the skipped commands are easy, for example: `workbench.action.debug.run` is bound to a function key (f5?)  by default. The shell shouldn't interpret any function key, those can all be skipped by default and sent to VSCode instead of the shell if they are bound – without an explicit setting. There are "full screen" terminal apps that use the Curses library plus function keys, Midnight Command comes to my mind, but I think it's obvious for a user that he needs to decide and configure the overlapping keys.

Problem solved, all commands/keys should go to VSCode first! Oh, wait… History repeating…

The one shortcut that was always a huge pain: `ctrl+c`. Thanks to IBM's CUA standard, two super essential keys overlap. Copy to some, quit to others. I really thought I left this behind, thanks to Apple's additional modifier key, `cmd+c` solved it at least for their own platform.

Anyway, if history is any indication, there is only one solution: VSCode needs to interpret it's shortcuts first, no questions asked. And common stuff like "copy" needs a separate shortcut that gets send to the terminal. KDE and Gnome both had something like `ctrl+alt+c` or `ctrl+shift+c` for "copy" in their respective terminal applications and leave `ctrl+c` alone. Can't verify as I have no GUI Linux at hand, but I wouldn't be surprised if Konsole and Gterm still have the same "solution" to this.

I don't like it, but if those devs didn't come up with something better for the past 20 years, its at least a possibility that there is no "clean" way to solve it :-/

**Comment by Tyriar** [comment]
Some other alternatives:

- The current list as well as a setting to modify it via "-command" and "+command"
- The current list as well as ".additions" and ".removals" settings

Everything is ugly :stuck_out_tongue: will leave this open for now, as the fixes don't seem much better than the current solution. Might think of something better in time.

**Comment by moward** [comment]
Another possibility. Instead of an array of commands, use an object with commands as keys and values as boolean. `true` would add a command, `false` would remove a command, and if a command is not included, it is inherited from the default.

Biggest downside is it's not at all backwards-compatible.
