### ISSUE TITLE
Feature Request: setting to change default behavior when a Source Control file is clicked

### ISSUE THREAD

**Issue by DanKaplanSES** [microsoft/vscode#197878]
Keywords: UX, Setting, SCM, source control, default, default behavior, default setting, Source Control Explorer

To establish terminology, here is a screenshot of the right-click context menu in the Source Control explorer:

![image](https://github.com/microsoft/vscode/assets/373675/b118486e-1ec5-4399-909f-da4368fa4ad4)

When the user left clicks on a file in this view, it behaves like "Open Changes" in the screenshot. I usually want to "Open File" instead. I would like a setting that allows the default behavior to change. 

If this setting already exists, I couldn't find it in the "Source Control" section.

**Comment by lszomoru** [comment]
Is `git.openDiffOnClick` the setting that you are looking for? Thanks!

**Comment by DanKaplanSES** [comment]
@lszomoru Thank you, that is the exact setting I was looking for. May I change my original issue to be about making it easier to find this setting? e.g., Every SCM tool I've used uses the concept of diffing, so why is this specific to `git` settings?

**Comment by lszomoru** [comment]
@DanKaplanSES, glad that this was the setting that you were looking for. The setting itself is specific to the `git` extension because the command that is being executed when you click on a "resource" is contributed by the `git` extension and VS Code has no knowledge of it. 

We are exploring making improvements to settings search but we are not planning on changing the setting name.
