### ISSUE TITLE
Keybindings using brackets (eg. indent) doesn't work with a Danish keyboard layout on Mac OSX

### ISSUE THREAD

**Issue by Machtan** [Microsoft/vscode#198]
The reason is likely that to enter these keys on the layout, you have to use the 'option' (alt) button.
So in this instance, the command is effectively "Cmd+Alt+8" for Cmd+[.
Perhaps VS Code needs better OS-support for text input (or at least for their use in keycodes).

**Comment by alexandrudima** [comment]
@Machtan Please see #713 where the problem is explained. The UI renders `Cmd+[` when in fact the keybinding for decrease indent is `Cmd+VK_OEM_4`. I am not sure where exactly `VK_OEM_4` sits in Danish keyboard, nor what its label is (you can probably find it by trying all the non apha numeric keys), but this is currently a limitation in the platform we're building on (electron / chromium). I'd also like to invite you, if you figure it out, to let us know what would be good default keybindings for the Danish keyboard layout and we can work from there to improve the experience for others (creating an extension...).
