### ISSUE TITLE
Block cursor is not rendered properly (visual glitches)

### ISSUE THREAD

**Issue by mafredri** [Microsoft/vscode#19808]
After updating VSCode I noticed that my cursor (block) was not behaving correctly.

While examining the behaviour I noticed the following:
1. All problem disappear when changing back to regular cursor
2. The weird cursor placement (out of bounds) depends on my current font (Operator Mono Light)
3. The block cursor tab highlighting that follows inappropriately is unaffected by font change

- VSCode Version: 1.9.0
- OS Version: macOS 10.12.3

Steps to Reproduce:

1. Set `"editor.cursorStyle": "block"` (and change font to e.g. `OperatorMono-Light`)
2. Move or click around with cursor

![vscode19-block-cursor-problem](https://cloud.githubusercontent.com/assets/147409/22585147/fc1a7016-e9fe-11e6-9696-97565e2e6c92.gif)

**Comment by bk-m** [comment]
- Same issue on Windows Server 2012R2.
- I hadn't made a connection to the font myself but I use 'Droid Sans Mono'.
- Most annoying of these visual bugs: inserting a new line with Enter will not display the block-cursor at the beginning of the new line but at the same column you were at when you hit Enter
- Changing to line-cursor fixes everything.

**Comment by alexandrudima** [comment]
This happens when the cursor is at the end of a line and the block cursor tries to read the px offsets for an invalid range from a ViewLine.

It fails for non-100%-monospace fonts, such as Droid Sans Mono (e.g. which has a char width of 8.40234375px for regular characters and 8.68359375px for bolded characters at fontSize 14 on my machine).

The only workaround at this time for the block cursor to render correctly is to use a 100%-monospace font.

**Comment by mafredri** [comment]
Thanks for the quick fix @alexandrudima. 02fa69d fixes both my issues 👍!

**Comment by eduardonunesp** [comment]
OSX 10.12.2

Well, I'm not sure if the issue is gone, I'm using the Insiders Code and something weird happened.

![screen shot 2017-02-09 at 09 45 55](https://cloud.githubusercontent.com/assets/582516/22782182/04a2f2fa-eead-11e6-8f81-f2382d2f12ae.png)

![feb-09-2017 09-46-44](https://cloud.githubusercontent.com/assets/582516/22782186/08792d40-eead-11e6-953d-d80d1a5d3c0e.gif)

The cursor is jumping between letters `fi` in `first`word as you can see in the gif above. Also the cursor behave different besides the letter `fi`. Like press left and right, you need to type twice, like if the cursor is lost and can't appear between `f` and `i`

My Config

```json
{
  "workbench.editor.enablePreview": false,

  "editor.wrappingColumn": 0,
  "editor.fontFamily": "Monaco",
  "editor.fontSize": 15,
  "editor.fontLigatures": true,
  "editor.tabSize": 2,
  "editor.lineHeight": 20,
  "editor.detectIndentation": true,
  "editor.rulers": [
    80,
    100,
    120
  ],
  "editor.quickSuggestionsDelay": 0,
  "editor.renderIndentGuides": true,
  "editor.renderWhitespace": "all",
  "editor.tabCompletion": true,
  "editor.formatOnType": false,
  "editor.selectionHighlight": true,
  "editor.cursorStyle": "line",
  "editor.renderControlCharacters": true,
  "explorer.autoReveal": true,

  "eslint.run": "onType",
  
  "explorer.openEditors.visible": 0,

  "files.exclude": {
    "**/.git": true,
    "**/.svn": true,
    "**/.hg": true,
    "**/.DS_Store": true,
    "**/node_modules": true,
    "**/*.pyc": true,
    "**/*.zip": true
  },

  "search.exclude": {
    "**/node_modules": true,
    "**/bower_components": true,
    "**/deps": true
  },
  "vsicons.projectDetection.autoReload": true
}
```

**Comment by eduardonunesp** [comment]
@alexandrudima days ago it seems to be fixed, not sure if the issue back or my previous test was a flaw, sorry to "reborn" this issue

**Comment by Inachos** [comment]
@eduardonunesp fi as one glyph is a typical font ligature (i.e. it is literally only one letter, both squished together). Does that also happen if you set font ligatures to false?

**Comment by eduardonunesp** [comment]
@Inachos humm, looks like it's fixed my issue ! thank you

**Comment by Inachos** [comment]
@eduardonunesp You're welcome, glad it works. If you want ligatures enabled, you should probably open a new issue concerning editing of ligatures.
