### ISSUE TITLE
Sometimes loading into a terminal doesn't show the right sticky scroll result

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#198012]
Before:

![image](https://github.com/microsoft/vscode/assets/2193314/a06b3afc-1316-401f-8bc8-9b4ac2271092)

After:

![image](https://github.com/microsoft/vscode/assets/2193314/6e7981dc-af23-440f-b08b-dadfb2de1134)

After scrolling once it's the same as before

**Comment by rzhao271** [comment]
Which result is the expected one?
Also, my prompt is one line long, so I'm wondering whether it needs to be adjusted to verify the issue?

**Comment by andreamah** [comment]
I *think* that I have the functionality as expected. When the terminal is two lines and records as two lines in the history, it shows both lines. Otherwise, if it doesn't record two lines, it will show a single line?

[![Image from Gyazo](https://i.gyazo.com/b2d0379aac2138cdc535fa728bd9252f.gif)](https://gyazo.com/b2d0379aac2138cdc535fa728bd9252f)

**Comment by andreamah** [comment]
Wait, I notice that the sticky scrolling is inconsistent.
Repro:
1. Use `thecyberden` theme on powershell https://ohmyposh.dev/docs/themes
2. `ls` twice on the vscode repo.
3. Notice that the second `ls` has a sticky scroll header that is wrong.

[![Image from Gyazo](https://i.gyazo.com/46bf532f2d8e954da16427c55e0f0fb7.gif)](https://gyazo.com/46bf532f2d8e954da16427c55e0f0fb7)

**Comment by Tyriar** [comment]
Problem that this was reopened for is related to conpty

/duplicate https://github.com/microsoft/vscode/issues/224488
