### ISSUE TITLE
Toggle Tab Visibility is not found on version 1.84.2

### ISSUE THREAD

**Issue by sammtan** [microsoft/vscode#198151]
At VSCode 1.7x.x I assign a keyboard shortcut to hide tabs visibility. It looks like this.
```
// keybindings.json

{
    "key": "ctrl+t ctrl+t",
    "command": "workbench.action.toggleTabsVisibility"
}
```
Then updating to 1.84.2 shows command `workbench.action.toggleTabsVisibility` not found. Is it removed or is there new command for that?

**Comment by ArturoDent** [comment]
See your SO question: https://stackoverflow.com/questions/77476579/workbench-action-toggletabsvisibility-command-is-missing-after-1-84-2-update

There are 2 good responses there.

**Comment by sammtan** [comment]
yes exactly because that's me also asking right there 😄

**Comment by benibenj** [comment]
In the last update we changed the `workbench.editor.showTabs` setting from a boolean value to an enum (`multiple`, `single`, `none`). Due to this change we can't support the old command anymore, however, we added 3 new commands:
- `workbench.action.showMultipleEditorTabs`
- `workbench.action.showEditorTab`
- `workbench.action.hideEditorTabs`

This means you can create the same shortcut as you previously had. Mark has posted a good answer to your question on Stack Overflow. If you use his suggested keybinding, the behaviour should be identical to how it used to be.
