### ISSUE TITLE
Write diff editor inline/side-by-side preferences to user settings

### ISSUE THREAD

**Issue by preetsaimutneja** [Microsoft/vscode#19819]
- VSCode Version: 1.9.0
- OS Version: Windows 10 Enterprise

Steps to Reproduce:

1. Initialize a git repository with a file and perform an initial commit.
2. open folder in vscode.
3. Make changes to the file.
4. Press Ctrl+Shift+G and click on the file to see the diff.
5. Switch to inline view.
6. Press Ctrl + to make the font appear larger (or Ctrl - for smaller)

Observed behavior:
1. The editor switches back to side by side view. 
2. In screenshot attached see the options. The view is side-by-side diff but the options still say switch to side-by-side view. Note that the wrong options only appear when I zoom in or out.
![screenshot 5](https://cloud.githubusercontent.com/assets/14777648/22586683/2a42cbee-ea24-11e6-8290-8b8fde274970.png)

**Comment by bpasero** [comment]
@alexandrudima I am not finding this issue anymore but I think you had one for making the diff editor toggle a real user setting?

**Comment by Aleyenda** [comment]
Still seeing the issue. My problem is not when zooming but when changing in between modified files. 

- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|1.7.0|
|PowerShell|ms-vscode|0.9.0|

---

Steps to Reproduce:

1. Initialize a git repository with at least two files and perform an initial commit.
2. Modified both files.
3. Go to see the diff in the GIT section.
4. Switch to inline view.
5. Now click on the second file to see its diff.

Observed behavior:
1. The editor switches back to side by side view.
2. The toggle options are wrong, same way as in the screenshots by preetsaimutneja.

Should I open an independent issue since it is a bug for me?

Also I agree with the feature request.

**Comment by spottedmahn** [comment]
Manual workaround: Change your settings by setting the following: `"diffEditor.renderSideBySide": false`

[Source](https://github.com/Microsoft/vscode-tips-and-tricks)
