### ISSUE TITLE
Screen wiggling when adding breakpoint

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#198267]
- Select some code so the sparkle button shows up
- Press F9 to add a breakpoint
- The screen shifts as the breakpoint appears then replaces the sparkle icon a moment later

![Recording 2023-11-14 at 22 13 05](https://github.com/microsoft/vscode/assets/323878/652add2f-439d-420d-b25a-40ee93a090bc)

**Comment by aiday-mar** [comment]
@aeschli this issue is in relation to the discussion we were having yesterday about the sparkle icon obstructing the way for the breakpoints.

I can fix this issue by disabling the addition of breakpoints when a sparkle icon is not visible in the gutter, this would help us avoid the flickering behavior. I am not sure if this is the best decision here though?

**Comment by aeschli** [comment]
Let's wait until we know if we want the sparkle or if we are going to remove it.

**Comment by aiday-mar** [comment]
The sparkle in the gutter has been entirely removed from the code base, therefore this issue can be closed.
