### ISSUE TITLE
Terminal closes immediately on macOS

### ISSUE THREAD

**Issue by ciaojep** [Microsoft/vscode#19823]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:23:30.856Z)
- OS Version: Darwin x64 16.4.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|angular-material-snippets|4tron|0.3.1|
|material-icon-theme|PKief|1.2.0|
|project-manager|alefragnani|0.13.2|
|angular2-snippets|danwahlin|1.0.12|
|theme-dracula|dracula-theme|1.2.5|
|angular-bootstrap|herrherrmann|4.0.6|
|icon-fonts|idleberg|1.3.2|
|vscode-icons|robertohuertasm|7.1.2|
|stylelint|shinnn|0.21.0|
|upload|wuwei|0.1.5|
|blade-runner|yukidoi|1.0.0|

---

Steps to Reproduce:

1. open terminal
2. the terminal closes by itself

**Comment by Tyriar** [comment]
What's in your settings.json file?

**Comment by Giampietro** [comment]
`// Percorso della shell usata dal terminale in Linux.
  "terminal.integrated.shell.linux": "/bin/bash",

  // Argomenti della riga di comando da usare nel terminale Linux.
  "terminal.integrated.shellArgs.linux": [],

  // Percorso della shell usata dal terminale in OS X.
  "terminal.integrated.shell.osx": "/bin/bash",

  // Argomenti della riga di comando da usare nel terminale OS X.
  "terminal.integrated.shellArgs.osx": [],

  // Percorso della shell usata dal terminale in Windows. Quando si usano le shell incluse in Windows (cmd, PowerShell o Bash in Ubuntu), preferire C:\Windows\sysnative rispetto a C:\Windows\System32 per usare le versioni a 64 bit.
  "terminal.integrated.shell.windows": "cmd.exe",

  // Argomenti della riga di comando da usare nel terminale Windows.
  "terminal.integrated.shellArgs.windows": [],

  // When set, this will prevent the context menu from appearing when right clicking within the terminal, instead it will copy when there is a selection and paste when there is no selection.
  "terminal.integrated.rightClickCopyPaste": false,

  // Controlla la famiglia di caratteri del terminale. L'impostazione predefinita è il valore di editor.fontFamily.
  "terminal.integrated.fontFamily": "",

  // Controlla se i caratteri legatura sono abilitati nel terminale.
  "terminal.integrated.fontLigatures": false,

  // Consente di controllare le dimensioni del carattere in pixel del terminale.
  "terminal.integrated.fontSize": 12,

  // Controlla l'altezza della riga del terminale. Questo numero è moltiplicato dalle dimensioni del carattere del terminale per ottenere l'altezza di riga effettiva in pixel.
  "terminal.integrated.lineHeight": 1.2,

  // Controlla se il cursore del terminale è intermittente o meno.
  "terminal.integrated.cursorBlinking": false,

  // Controls the style of terminal cursor.
  "terminal.integrated.cursorStyle": "block",

  // Consente di controllare il numero massimo di righe che il terminale mantiene nel buffer.
  "terminal.integrated.scrollback": 1000,

  // Controls the whether the terminal emulator will use flow control in order to catch up with the shell process, the main effect of this is that ^C and other signals should be much more responsive when commands give lots of output. You should this disabled if you have custom ^S or ^Q keybindings that override the XOFF and XON signals used.
  "terminal.integrated.flowControl": true,

  // Controlla se le variabili delle impostazioni locali sono impostate all'avvio del terminale. Il valore predefinito è true per OS X e false per altre piattaforme.
  "terminal.integrated.setLocaleVariables": true,

  // An explicit start path where the terminal will be launched, this is used as the current working directory (cwd) for the shell process. This may be particularly useful in workspace settings if the root directory is not a convenient cwd.
  "terminal.integrated.cwd": "",

  // Set di ID comando i cui tasti di scelta rapida non verranno inviati alla shell e verranno sempre gestiti da Code. In tal modo i tasti di scelta rapida normalmente utilizzati dalla shell avranno lo stesso effetto di quando il terminale non ha lo stato attivo, ad esempio CTRL+P per avviare Quick Open.
  "terminal.integrated.commandsToSkipShell": [
    "editor.action.toggleTabFocusMode",
    "workbench.action.debug.continue",
    "workbench.action.debug.restart",
    "workbench.action.debug.run",
    "workbench.action.debug.start",
    "workbench.action.debug.stop",
    "workbench.action.openNextRecentlyUsedEditorInGroup",
    "workbench.action.openPreviousRecentlyUsedEditorInGroup",
    "workbench.action.quickOpen",
    "workbench.action.showCommands",
    "workbench.action.terminal.clear",
    "workbench.action.terminal.copySelection",
    "workbench.action.terminal.focus",
    "workbench.action.terminal.focusNext",
    "workbench.action.terminal.focusPrevious",
    "workbench.action.terminal.kill",
    "workbench.action.terminal.new",
    "workbench.action.terminal.paste",
    "workbench.action.terminal.runSelectedText",
    "workbench.action.terminal.scrollDown",
    "workbench.action.terminal.scrollDownPage",
    "workbench.action.terminal.scrollToBottom",
    "workbench.action.terminal.scrollToTop",
    "workbench.action.terminal.scrollUp",
    "workbench.action.terminal.scrollUpPage",
    "workbench.action.terminal.toggleTerminal"
  ],`

**Comment by Tyriar** [comment]
That looks like the default values (on the left) do you have anything on the right side of settings?

**Comment by Giampietro** [comment]
Hello,on the right i have these settings:
`// insert the settings in this file to override the default ones
{
"git.Confirmsync": false,
"window.Zoomlevel": 0,
"vsicons.Dontshownewversionmessage": false
}`

**Comment by Tyriar** [comment]
What happens when you run `/bin/bash` in a native terminal?

Also could you check the developer tools console for an errors (Help > Toggle Developer Tools).
