### ISSUE TITLE
content of accessible terminal view udpated on dynamic data for inactive terminal

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#198370]
1. run a command which generates dynamic output in a terminal
2. split the terminal
3. with screen reader mode on, `alt+f2` 
4. 🐛 the content of the terminal with dynamic output has taken over the accessible view

**Comment by eleanorjboyd** [comment]
What do you mean by "the content of the terminal with dynamic output has taken over the accessible view". When I tried this I split the terminal and then kept hearing it try and read the dynamic output which I used the "top" command and it seemed incapable of getting through a single word before it restarted I am assuming to say the new dynamic result.

**Comment by rzhao271** [comment]
The issue seems to be resolved on macOS assuming the verification steps mean the following:

1. Run the `top` command in a terminal
2. Split the terminal
3. In the new empty terminal, while Screen Reader Optimized mode is on, open the accessible view (with the command or Option+F2 keybinding)
4. Verify the accessible view displays the contents of the new terminal rather than the old one.

If I open the accessible view for the top command, the contents do keep changing even in the accessible view.
