### ISSUE TITLE
do i just losing all my .workspaces tabs organisation for all my projects by moving project folder !?

### ISSUE THREAD

**Issue by djmisterjon** [microsoft/vscode#198392]
Hi, where does VSCode store tab organization for the profile? 
I thought all the data are in those files `.workspace` because when I open those files, VSCode restores all tab organizations!

![image](https://github.com/microsoft/vscode/assets/24865815/b5d39a67-8f91-459e-a834-1f616979ef60)

---

**But since I moved my project folder to a new drive**, I opened my `xxx.workspace` again, and **VSCode just has no tabs opened!**
So I opened the `.workspace` in WordPad, and those `.workspace` files seem not to have profile tabs organization info.
So i am curious where you store those data!?
Is it possible for me to bring back those data because it will take me several days to restore manually all organizations tabs to all my .workspace files in all my projects !

I hope this isn't a bug!
I am surprised that the workspace opened tabs are not stored in these files !
It seemed logical to me to place them there for make easier projects or disks migrations!

thanks

**Comment by Tyriar** [comment]
Opened tabs are stored internally inside the "user data directory". If you're talking about unsaved files that you may have lost, these can hopefully be restored by checking the folder called out here: https://code.visualstudio.com/docs/editor/codebasics#_hot-exit

If you're talking about just tab layout, you can maybe restore that by moving the project back, but this is meant to be very transient information and we don't go to particular effort to keep backups.

A workspace's identifier is based on the code-workspace file or the folder. If you change where the code-workspace file is on disk, you change the workspace identifier. It's intentional tab and backup information is not kept in these files as they're designed to optionally be pushed to your SCM.

**Comment by djmisterjon** [comment]
> If you're talking about just tab layout

yes it about tab layout, i have my own disposition for each workspace inside a project.
each file here have they own disposition because my project have ~120 files and it the only way i can work simultaneous and focus on each groups.
![image](https://github.com/microsoft/vscode/assets/24865815/b13d9db6-f728-480f-b417-9871ad3d4402)

I find this really unfortunate! In certain projects, one might want to structure the project into several regions according to certain design patterns. When you need to work on one region rather than another, it's normal to want to find your organization just as it was when saving the workspace

I was also hoping for better support because I used a feature of your company's OS that allows pointing the data folders to another hard drive.
![image](https://github.com/microsoft/vscode/assets/24865815/3af27e92-fe98-4c25-9ccc-298747ef7834)

It's essentially a relocation, but designed to avoid these kinds of problems with software and the registry.
I didn't encounter any issues with the majority of third-party software that pointed to the documents on the C drive, now stored on the D drive.
It the same access from the top of window API.
