### ISSUE TITLE
'{{' inside code block breaks highlighting

### ISSUE THREAD

**Issue by moritz-t-w** [microsoft/vscode#198462]
The following markdown:
\`\`\`
{{
\`\`\`
breaks any following syntax highlight. Putting a space between the brackets or adding this:
\`\`\`
}}
\`\`\`
makes it work again

![image](https://github.com/microsoft/vscode-markdown-languageservice/assets/90388353/295c4ad1-11c7-44ab-9114-445fc1b211ab)

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

I suspect one of your extensions is causing this because it doesn't happen for me

**Comment by moritz-t-w** [comment]
Ok thanks for testing, I just sorta assumed this wouldn't have anything to do with other extensions, sorry.
