### ISSUE TITLE
Can't find the \r caracter with the new VS Code 1.9 Update

### ISSUE THREAD

**Issue by Davilink** [Microsoft/vscode#19864]
With the new VS Code 1.9, you change the Regexp Handling method that we cannot only replace OR find « \r » character, because now it's only the « \n » character that it's used.

How do i can distinguish \r in \r\n in the file now ?

**Comment by rmunn** [comment]
Can't you just search for a `\r` character by itself? Just because `\n` now matches a CR+LF combination doesn't mean that `\r` won't still match a CR character, right?

**Comment by alexandrudima** [comment]
VSCode prohibits by design to create inconsistent End-Of-Line sequences. That means it will never allow an edit to do anything inside the End-Of-Line sequence. The End-Of-Line sequence can be changed from the status bar in the bottom right (where LF or CRLF sits)

So, if an extension, if the find widget, etc. tries to edit or "target" in any way in between a `\r` and a `\n` in a file with `\r\n` End-Of-Line sequences the edit will be adjusted and moved either to before the `\r\n` or after the `\r\n`.

As a result, in a CRLF file, there is no `\r` without a `\n` immediately after it. Nothing has been lost, there is no need to distinguish the `\r` from the `\r\n` since nothing can be done to that character by itself.
