### ISSUE TITLE
Bulk comment / uncomment is broken in certain cases

### ISSUE THREAD

**Issue by johnbrett** [Microsoft/vscode#19868]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:23:30.856Z)
- OS Version: Darwin x64 16.4.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-wakatime|WakaTime|1.0.6|
|node-module-intellisense|leizongmin|1.3.0|
|Theme-GitHubCleanWhite|saviorisdead|0.0.3|

---

Steps to Reproduce:

1. Highlight multiple a block of code like example below, and press `cmd` + `/`, it creates the following *multiline* comment:
````javascript
/*if (foo === 'has long contents') {
  return (
    <div>
       test
    </div>
  )
}*/
````
The problem here is if you press `cmd` + `/` again, it actually **adds extra inline comments** instead of removing the code block just added.

// NOTE, doesn't happen for all cases, the following still works correctly (not `test` is inline this time, as opposed to its own line).

````javascript
//  if (foo === 'has long contents') {
//    return (
//      <div>test</div>
//    )
//  }
````

I've only noticed this since the latest update, 1.9.0. 

BTW - I absolute LOVE VSCode - you people rock. Anything I can do to help fix this let me know ❤️

**Comment by rebornix** [comment]
Firstly, if you want to use block comment always, there is another command for that `shift+alt+a` -> `Toggle Block Comment`. In this case you won't see any unexpected behavior.

Secondly, about the root cause of this issue. We tried to do Line Comment for this block however there is no line comment for `test`, which is a HTML tag. So we fall back to Block Comment in this case. When you do another `Cmd+/`, we think you are going to another Line Comment as we really don't know if that's your purpose. So in this situation, a Undo or Toggle Block Comment is what you need to revert the comment.

Make sense @johnbrett

**Comment by johnbrett** [comment]
Happy with these workarounds, I was pointing it out in case there was an error interpreting the code to try comment. 

Thanks for the quick & detailed response @rebornix.

**Comment by ralphsmith80** [comment]
Is there a way to always choose line comment? I do a lot of with with JS and JSX. The line comment always works to comment out JS, but the block comment doesn't work if I have nested JSX that's commented out because the syntax is similar to a block comment.

**Comment by phocks** [comment]
I still think this is a bug. If it detects and adds a block comment with cmd+/ then it should detect and remove the same block comment with cmd+/

Amy I wrong? Should I look at the source code and try to figure out a fix myself?
