### ISSUE TITLE
Word wrap is broken with introduction of v1.9

### ISSUE THREAD

**Issue by adbertram** [Microsoft/vscode#19875]
- VSCode Version: 1.9
- OS Version: MacOS Sierra

Steps to Reproduce:

1. Open a Markdown file.
2. Toggle word wrap

This word wrap feature used to work before upgrading to v1.9 but it seems to be broken now. When I attempt to toggle word wrap, it does nothing at all.

**Comment by kaiwood** [comment]
Same as #19842

@alexandrudima You might want to look at this. Hard to notice on a big screen, but I think I found a way to reproduce it on my 13":

If you set `editor.wrappingColumn` to any value **lower** than the max col that **can** be displayed in a row, `editor.wordWrap` is ignored.

![screen shot 2017-02-03 at 21 42 22](https://cloud.githubusercontent.com/assets/7542/22607860/11d8f43a-ea5a-11e6-832f-fcc3692f5499.png)

![screen shot 2017-02-03 at 21 42 38](https://cloud.githubusercontent.com/assets/7542/22607918/5783b4d4-ea5a-11e6-9118-b7bce82aed2e.png)

In the previous release, `editor.wordWrap: false`  took precedence over the wrapping column (and it absolutely should stay that way, if a setting with a simple boolean says "Don't wrap", it should definitely not wrap, no matter what a more fine grained "wrap column"  says)

**Comment by adbertram** [comment]
editor.wordWrap is set to false and wrappingColumn is set to 300. I'm on a new MacBook Pro 15".

**Comment by kaiwood** [comment]
Hmm, strange. If I set it explicitly to 300 I can toggle the word wrap. I just played around with it, in the setup shown in my screenshots the toggling stop as soon as I set `wrappingColumn` to 121.

**Comment by Bill-Stewart** [comment]
Before 1.9.0 I set `editor.wrappingColumn` to `-1` so I could toggle wrap dynamically with `editor.action.toggleWordWrap`. This no longer works, but  I verified that I can update wrap to something very long (e.g., `32767`) to get the previous behavior.

The description for `editor.wrappingColumn` still says `-1` should work for this purpose, but it appears this is not the case?

The actual behavior is described by the `editor.wordWrap` setting: "The lines will wrap at min(editor.wrappingColumn, viewportWidthInColumns)." This behavior makes sense, but it seems that the `-1` value in `editor.wrappingColumn` is not honored?

**Comment by alexandrudima** [comment]
The toggle word wrap action has changed (to be aligned with all the other View actions) and is now writing to user settings. Specifically, it writes to user settings `editor.wordWrap: true` or `editor.wordWrap: false`. Before, it would change an in-memory value which would be lost as soon as any other view action that would write to user settings would be executed (e.g. zoom in / zoom out) or as soon as `settings.json` would have been touched on disk.

Since the action now writes to the user settings, one thing to keep in mind is that the setting should not be present in the workspace settings, since workspace settings overwrite user settings. In other words, if the workspace settings contains `editor.wordWrap`, then the action will be a no-op. This is similar to the other View actions, such as zooming in/zooming out, etc. It is generally not a good idea to keep presentation options in the workspace anyways.

### Mastering line wrapping

There are two important settings in VS Code that control line wrapping.

* `editor.wrappingColumn` (300 by default)
* and `editor.wordWrap` (false by default)

It is important to understand the need for two distinct settings and how to tweak them to suit your use-case:

Examples (with explanations):

| `wordWrap` | `wrappingColumn` | Explanation |
|---|---|---|
| false | 300 | Lines will wrap at <code>300</code> |
| false | 0 | Lines will wrap at <code>viewport_column</code> |
| false | -1 | Lines will never wrap. |
| true | 300 | Lines will wrap at <code>min(viewport_column, 300)</code> |
| true | 0 | Lines will wrap at <code>viewport_column</code> |
| true | -1 | Lines will never wrap. |

**Comment by Bill-Stewart** [comment]
It is not intuitive that any wrapping occurs when `wordWrap` is set to `false`. IMO the following is much more intuitive:

**`wordWrap`** | **`wrappingColumn`** | **Explanation**
----------------|-------------------------|---------------
`false`               | any value                      | Lines will never wrap
`true`               | -1                                  | Lines will wrap at min(viewport_column, wrappingColumn)
`true`               | 0                                   | Lines will wrap at viewport_column
`true`               | >= 1                             | Lines will wrap at specified column

**Comment by smithbr** [comment]
@alexandrudima in your example table, it appears that therefore wrapping is no longer toggle-able between 'Lines will wrap...' and 'Lines will never wrap' because `wrappingColumn` needs to be changed in order to unwrap all lines. Alt-Z basically doesn't work anymore.

**Comment by Bill-Stewart** [comment]
What is the actual purpose of the `editor.wordWrap` setting?

If it is set `false` and some wrapping is still occurring, I find this counterintuitive and confusing.

In this case I would suggest giving this option a different name that tells better what it does.

Otherwise, I would suggest implementing behavior like described in my table above. If `wordWrap` is `false`, then there should be no wrapping. Ignore `wrappingColumn`.

If `wordWrap` is `true`, then honor setting in `wrappingColumn`.

**Comment by Download** [comment]
> It is not intuitive that any wrapping occurs when wordWrap is set to false.

It is the actual reason I'm here... reading this bug. Because that's what was introduced in 1.9 afaic. A bug.
I find it strange this issue is closed. Check out how many are reporting that they perceive this as a bug.

I used to love the column editing feature of VSCode (took a while to get used to, but is marvelous!), but now, because the lines wrap (no matter whether I enable or disable word wrap), I can't use this column editing feature effectively.

I guess the workaround is to set `wrappingColumn` to a very high value?

Please consider re-opening this. The feature is not an improvement imho.
