### ISSUE TITLE
Markdown is not auto scrolling.

### ISSUE THREAD

**Issue by idvorkin** [Microsoft/vscode#19898]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:31:00.827Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|

---

Steps to Reproduce:

1. Open Markdown file
2. Open preview to side
3. Scroll in markdown window (preview does not scroll)

**Comment by fabiorocha** [comment]
@idvorkin This reproes for me as well. It seems to happen only when the file is opened from the file system directly and not from a folder currently loaded in the file explorer. For instance, from the picture below, 

![image](https://cloud.githubusercontent.com/assets/1686833/22621036/e3662094-eace-11e6-89da-3e5262e9a5c2.png)

_README.md_  opened directly as file, **will not** auto scroll.
_generators.md_ opened from the docs folder which is loaded in the file explorer, auto scrolls fine.

Do you see the same behavior? Probably a path resolution issue.

**Comment by idvorkin** [comment]
@fabiorocha Good debugging :) I've got the same behavior.

**Comment by fabiorocha** [comment]
@idvorkin awesome. What do you think about updating the issue description (step 3)

From:
_Scroll in markdown window (preview does not scroll) :(_

To:
_Scroll in preview window (source does not scroll)_ 

Since it's expected to sync only preview -> source, not the other way around?

---- 

I looked briefly at this today and it seems the problem is on _vscode\extensions\markdown\src\extension.ts_, in the path comparison made in snippet below  

```ts
context.subscriptions.push(vscode.commands.registerCommand('_markdown.revealLine', (uri, line) => {
  const sourceUri = vscode.Uri.parse(decodeURIComponent(uri));
  vscode.window.visibleTextEditors
    .filter(editor => editor.document.uri.path === sourceUri.path)
    .forEach(editor => {
      const sourceLine = Math.floor(line);
      const text = editor.document.getText(new vscode.Range(sourceLine, 0, sourceLine + 1, 0));
      const fraction = line - Math.floor(line);
      const start = Math.floor(fraction * text.length);
      editor.revealRange(
        new vscode.Range(sourceLine, start, sourceLine + 1, 0),
        vscode.TextEditorRevealType.AtTop);
    });
}));
```

Note the drive letter:

![image](https://cloud.githubusercontent.com/assets/1686833/22623245/28be42a0-eb08-11e6-9d35-e72b4caca3cf.png)

A simple toUpperCase() on both sides make this work which proves this is the issue. Obviously this isn't a proper fix for OSs that have a case sensitive file system. It also seems that having the lowercase windows drive letter is by design in many places:

![image](https://cloud.githubusercontent.com/assets/1686833/22623433/d53dfec4-eb0f-11e6-8fb8-9607e22736f0.png)

So I get a proper fix here would be finding out why editor.document.uri.path doesn't return a normalized path.

**Comment by idvorkin** [comment]
I've updated the description, although both directions should work! Thanks for digging in.  By the way, thanks your digging I'm unblocked, and this is a great feature!

**Comment by mjbvz** [comment]
Thanks all for the investigation. I've created #20064 which I believe should fix this. As noted, in some Windows scenarios, the  drive letter differs between the preview document and the editor document. Using `fsPath` should fix this. I'm planning to take the fix into the 1.10 insiders builds and also our next 1.9 recovery build

**Comment by fabiorocha** [comment]
Thanks for the quick fix @mjbvz! I've looked into this a bit more and the root cause is on the way the original source document's URI is created on \vscode\src\vs\base\common\uri.ts

An else if on "public static file(path: string): URI" would help you avoid all those || on your case and probably prevent other future bugs too.

else if (URI._upperCaseDrive.test(path)) {
     // windows drive letter: file:///c:/far/boo
     ret._path = path[0].toLowerCase() + path.substr(1);
}

**Comment by mjbvz** [comment]
Thanks @fabiorocha. That be worth looking into in the future, but I don't want to touch functionality that is so central for this fix. After reviewing the `fsPath` logic, I think using it should be safe and address the problem. Path casing issues have caused us lots of trouble in the past, so this is an area that we certainly need to revisit but one that can also be pretty finicky

b4aac1c cherry-picked this workaround into our 1.9 branch to be picked up in the next recovery build

**Comment by fabiorocha** [comment]
@mjbvz Totally understandable. Thanks again for the quick fix and for the great feature!
