### ISSUE TITLE
The issue of pulling only specific repositories in VSCode

### ISSUE THREAD

**Issue by sanbuphy** [microsoft/vscode#199086]
In vscode git, I can pull all my repositories from Github. But is there a way to only pull certain repositories? (only allowed via SSH) Or is it necessary to enforce two-factor authentication? Thank you. Because I don't want to log in to Github in vscode and be able to pull all repositories.

**Comment by lszomoru** [comment]
@sanbuphy, thank you very much for filing this issue. No, at the moment there is no way to limit the list of repositories that appear in VS Code when you are signed in with your GitHub account.  VS Code is using the GitHub REST APIs in order to get the list of repositories. As far as I am aware there is no way to limit the list of repositories based on the requirements that you have listed above.
