### ISSUE TITLE
[folding] Show first property when folding object

### ISSUE THREAD

**Issue by unional** [Microsoft/vscode#19912]
VSCode: 1.9.0

Currently, when folding an object, the object is folded into `{...}` which is not that useful:

```ts
    var someArray = [
        {
            name: 'x',
            value: 1
        },
        {
            name: 'y',
            value: 2
        },
        {
            name: 'z',
            value: 3
        }
    ];
```
When folded:
![image](https://cloud.githubusercontent.com/assets/3254987/22616931/46ea7442-ea6d-11e6-98af-98fe3064ec5b.png)

In comparison, WebStorm fold it to:
![image](https://cloud.githubusercontent.com/assets/3254987/22616935/618c4686-ea6d-11e6-8378-4c7f97b1a9ca.png)

**Comment by aeschli** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.
If you disagree and feel that this issue is crucial: We're happy to listen and to reconsider.
Maybe you want to give it a try yourself and provide the feature through an extension or a PR: We're happy to give advise and get you started.
Thanks for your understanding. Thanks for helping and happy coding!
