### ISSUE TITLE
Quick Open Recent does not support key modifiers to force new/reused window

### ISSUE THREAD

**Issue by starball5** [microsoft/vscode#199289]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.84.2
- OS Version: Ubuntu 22.04.2

Steps to Reproduce:

1. Open workspace A
2. Bind `workbench.action.quickOpenRecent` and then use it.
3. Select workspace B and then press `enter` while holding `ctrl/cmd`.
4. Observe that a new window is not used and the same window is used instead.
5. Open workspace A
6. Invoke Open Recent and select workspace B and then press `enter` while holding `ctrl/cmd`.
7. Observe that a new window is opened for B.

This caught my attention as a result of this question on Stack Overflow: [Is there any way to use `workbench.action.quickOpenRecent` to open a new window?](https://stackoverflow.com/q/77561856/11107541)

Related source code looks to be in https://github.com/microsoft/vscode/blob/3481f35b91afff6c93d4888a528318d4f9f01a16/src/vs/workbench/browser/actions/windowActions.ts#L141

Additionally, when I debug Open Recent, pressing down and releasing <kbd>ctrl/cmd</kbd> does nothing, but pressing it down and then pressing <kbd>enter</kbd> down enters the `onKeyMods` callback with `{ "ctrlCmd": true, "alt": false }`. Whereas when I debug Quick Open Recent, pressing down and releasing <kbd>ctrl/cmd</kbd> enters the `onKeyMods` callback with `{ "ctrlCmd": false, "alt": false }`, and same for pressing it down and then pressing <kbd>enter</kbd>. I'm not sure why this happens, but I suspect that this is unintended behaviour. Can a maintainer please take a look and confirm?

**Comment by TylerLeonhardt** [comment]
Yeah so `workbench.action.quickOpenRecent` is one of these `quick` commands... which can also be confirmed via code [isQuickNavigate](https://github.com/microsoft/vscode/blob/cf1b0ce3d660a35a7060dbac9be7c045293ebaee/src/vs/workbench/browser/actions/windowActions.ts#L277) is set to `true`. This changes the behavior of how this quick pick operates which does have some quirks... for example, you don't see the input box, but the most important one relevant to this issue is that this is not intended to be used with modifier keys to alter the behavior. It's suppose to be a "quick" way of switching contexts. Having alternate behavior is intended to be used with the non-quick version of Open Recent.

All that to say, this behavior is expected. The quick versions of these commands aren't intended to have alternate open behavior.
