### ISSUE TITLE
[JavaScript] Syntax highlighting issue

### ISSUE THREAD

**Issue by Nimzozo** [Microsoft/vscode#19931]
- VSCode Version: 1.9.0
- OS Version: Windows 10

Steps to Reproduce:

0. Use the **Dark+ (default dark)** theme.
1. Declare a variable named _url_.
```javascript
var url = "";
url = "www.google.com";
```
2. The variable is not correctly colored (white but should be blue).

**Comment by mjbvz** [comment]
Thanks. I confirmed this in 1.9 but believe it was been fixed in master and in the latest insiders builds by  2c55fde :

<img width="262" alt="screen shot 2017-02-06 at 10 52 26 am" src="https://cloud.githubusercontent.com/assets/12821956/22661495/6486f932-ec5a-11e6-90d1-bfb6de6d9e0e.png">

Please try out 1.10 insiders builds and let us know if you still see this issue.

Thanks
