### ISSUE TITLE
Terminal title doesn't update

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#199302]
Testing #199046

armhf setup

When for example running `find` the terminal title in the terminal panel doesn't update. It always shows `qemu-arm`

**Comment by deepak1556** [comment]
This behavior has been there since the beginning, we get the process name using `/proc/pid/cmdline` on linux refs https://github.com/microsoft/node-pty/blob/d6ce76a801f68730f7204b7b27bb21dbf8e63001/src/unix/pty.cc#L666 and when running binaries via qemu, the cmdline will always be of the format `/usr/bin/qemu-<arch> ...`

@Tyriar assigning it to you
