### ISSUE TITLE
Extensions with auto update flow uninstalled after reload

### ISSUE THREAD

**Issue by deepak1556** [microsoft/vscode#199309]
Testing #199180

* Set update flow to `OnlySelectedExtensions`
* Have multiple extensions from same publisher installed, in my case installed Docker, ESLint and DevContainers
* Set `Auto Update` for Docker and ESLint
* Downgrade the extension versions as mentioned in https://github.com/microsoft/vscode/issues/199180#issue-2012652519
* See the update banner popup on the selected extensions
* Extensions were auto updated but the banner still persists
* `Package.json` of the extensions still refers to the old version although the extension UI reports differently
* Now update the `Package.json` value to the current installed version
* See `reload required` banner pop up
* Click the reload action and extension gets removed

https://github.com/microsoft/vscode/assets/964386/efd4f509-5419-4bef-8602-df10a7b8e36b

**Comment by sandy081** [comment]
I have to say manually messing up the version in package.json and extensions.json file can cause unexpected behaviour like this. Sorry that I recommended this workaround to see updates. 

This seems to be suspicious. VS Code has clean up mechanism to remove outdated versions. Because of manual edits, clean up mechanism would have kicked off and uninstalled the extension.

If this approach helped you to test auto update feature then this should be sufficient. Side affects like this are due to the manual edits.

**Comment by deepak1556** [comment]
Makes sense. Curious, when you were developing this feature how did you test it ? Was it using published extensions that you control ?

**Comment by sandy081** [comment]
I was also updating above files I mentioned but differently.

- Used Install Another Version action from the UI
- Removed the `pinned` attribute from the extensions.json file
