### ISSUE TITLE
SCM Incoming/Outgoing: Provide setting to disable `All Changes`

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#199317]
Testing #199177

I would actually prefer not having the `All Changes` section. Let's get a setting for this.

**Comment by lszomoru** [comment]
Added `scm.showChangesSummary` that you can use to toggle the visibility of the "All Changes" node. 
Happy to take suggestions for the setting name/description in case you have a better one :)

**Comment by lszomoru** [comment]
Verification steps:
1. Launch the latest VS Code Insiders
2. Open a folder/workspace that contains a git repository
3. Switch to a branch that has an upstream
4. Make at least 2 local commit so that the "Outgoing" node has 3 entries ("All Changes" + 2 commits)
5. Toggle the `scm.showChangesSummary` setting
    * Confirm that the "All Changes" node is hidden/shown accordingly
