### ISSUE TITLE
Aux window: show screen reader status entry everywhere

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#199428]
Testing #199023

![Screenshot 2023-11-28 at 1 08 10 PM](https://github.com/microsoft/vscode/assets/29464607/39671283-22bd-4228-8247-d6cc26a2b803)

**Comment by bpasero** [comment]
**Verification:**
* open some floating editor windows
* enable accessibility mode
* ensure the status indicator appears in all windows including floating windows and is functional
* verify it disappears when the mode is turned off again

**Comment by justschen** [comment]
verified fix!

was wondering if it was possible to have pop-ups in aux windows as well (since some of the other status bar items are opened in the aux window, like the quick pick or Typescript/eslint status)?

for example,  if I hit `screen read optimized` to turn it off, the pop up shows up in the main window, but ideally it would show up in the aux window if it has focus.

**Comment by bpasero** [comment]
You mean notification toasts? We do not allow them in floating windows currently.
