### ISSUE TITLE
Unexpected lock and close button in empty window

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#199454]
Testing #199023

Repro:

1. Open untitled file
2. Drag out to new window
3. Close untitled file, 🐛 2 buttons remain

This may be by design, if so I don't think the `x` should be there as is duplicates the regular title bar close button.

![image](https://github.com/microsoft/vscode/assets/2193314/dccc1f33-af27-471f-b26e-1db35555561c)

**Comment by bpasero** [comment]
Showing the lock icon was an explicit decision specifically for floating windows: https://github.com/microsoft/vscode/issues/182265

The close icon appears because floating windows naturally extend the editor groups concept: once you have a floating window, you have more than one editor group and thus we show actions to close editor groups. We do not show a close icon for the main editor group because you cannot close the main editor group.

I think this is ok as it is, people using multiple editor groups will find this to be familiar I think.
