### ISSUE TITLE
inform screen reader users of chat response progress details

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#199422]
Some commands take a while to resolve. We indicate that progress is happening for screen reader users with the progress audio cue and we indicate completion by reading the response immediately after it's resolved. 

Sighted users now see step by step progress. For example, for `@workspace` requests, the following are presented with spinner information:
- Collecting workspace structure 
- Deciding which workspace information to collect
- Collecting workspace info

This information is fleeting and disappears when the response begins to render.

![A screen shot of the above information in the chat response panel](https://github.com/microsoft/vscode/assets/29464607/3e9f2463-5fff-4d91-8c61-6ade1a594eb8)

Because these can take a variable amount of time, and could be very noisy, I'm considering a few approaches and would like your feedback @jooyoungseo, @rperez030, @isidorn, and @joyceerhl. I think number 3 is the best. 

1. We use `aria-status` - a downside is the announcement might not be relevant by the time it is announced. 
2. We use `aria-alert` - a downside is this is really noisy and could be disruptive.
3. We have a command and key binding to query the status. So, if it's taking a while, a user could run this to find out which step it is on.

**Comment by rperez030** [comment]
I believe there is not a good solution for things like this one at the moment. I think I would prefer approach number 1 (alert). At least with Voiceover, and alert would be cancel if a second alert comes in. approach number 2 wouold create a queue of invalid messages that will be read even if the response is already available, and approach number 3 (a new key-binding) would requiree learning and integrating a new keyboard command for something that is not worth it in my opinion. I would also make these announcement customizable in settings so that people can turn them off if they don't find them helpful.

**Comment by rperez030** [comment]
I was thinking of status messages. Is this like a progress bar where each steps gets highlighted as it progresses?

**Comment by meganrogge** [comment]
Yes, it is clear which step is happening at any given time.

**Comment by meganrogge** [comment]
Enable a screen reader. Run a command which reports progress steps - `@workspace`. Verify that you hear each of these steps as it becomes visible.
