### ISSUE TITLE
Sparkle on a new line doesn't relocate inline chat

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#199442]
Testing #199158

Steps:
* open a file with 5 empty lines
* set cursor to line 1
* click on sparkle -> inline chat shows
* click on line 5 in the editor (moving the cursor to line 5)
* click on sparkle
* 🐛 nothing happens

I expected inline chat:
* to move down (how would that affect an already open inline chat with text in it?)...
* or maybe a new one?

**Comment by aiday-mar** [comment]
Hi @TylerLeonhardt thank you for writing the issue. The reason this happens is because when an inline chat is already open, triggering the 'inlineChat.start' command does nothing in VS Code. I think the appropriate fix in this case would be not to show a sparkle if an inline chat is already open because the inline chat can not appear elsewhere where it is closed. Unfortunately we currently do not have a mechanism to detect if the inline chat is open from an extension. I will think about what we can do here.

**Comment by aeschli** [comment]
I don't think we need extensions to know whether the inline chat is visible. The lightbulp-sparkle is managed in the renderer.
If we decide to not show the sparkle when inline chat is open, we would not request any code actions in that case, or filter out the ai-code action.

But first we need to agree if it's ok to not show the sparkle, but still show the lightbulb. In the end, the sparkle is just a special kind of light bulb.
