### ISSUE TITLE
If I can have a Chinese version of the release notes

### ISSUE THREAD

**Issue by arvin0** [Microsoft/vscode#19959]
- VSCode Version:1.9
- OS Version:win7

Steps to Reproduce:

1.VSCode release notes no Chinese version

**Comment by bpasero** [comment]
@arvin0 you mean you want our release notes translated to the language you run code with?

**Comment by arvin0** [comment]
![1](https://cloud.githubusercontent.com/assets/5111701/22625067/e8c3b71a-ebc6-11e6-93d0-54a231ec6bc0.jpg)
well, I want to these release notes with our language

**Comment by Tekbr** [comment]
@bpasero I agree ... but not only for Chinese, but for several languages ​​... In my case for Portuguese Brazil.

The main site could also be translated, like Visual Studio.

![capturar1](https://cloud.githubusercontent.com/assets/19866231/22626175/fa24ab5a-eb8e-11e6-9fba-88cd21947748.PNG)

I know that there is no VSCode translation yet for Portuguese Brazil ( #15077 ). :cry::cry::cry::cry::cry:

See that Visual Studio website we have notes we have notes in Portuguese in general, and also other languages. (When it is not available for the language, they keep the site in Portuguese, but with the English notes.)

![capturar](https://cloud.githubusercontent.com/assets/19866231/22626179/071be92c-eb8f-11e6-9cd1-892a175e1c2f.PNG)


I know that the team has worked hard with the editor ... I leave my congratulations :clap::clap::clap::clap::clap: ... but I could have a bit of dedication to the language as well.

I'm not saying that the translation should be done all at once ... go slowly ... if it were found errors of writing or places that need translation we could go informing.

This translation process could extend to extensions ... allow extensions to use the language pack.

The same goes for the extensions page. Yes I know it goes from the creator, but a basic description should be put so that it can be translated into all languages.

There are editors like Adobe Brackets that already have Portuguese translation (remembering that there is difference in Portuguese from Brazil to Portuguese in Portugal)

![gif](https://cloud.githubusercontent.com/assets/19866231/22626650/ad51cfaa-eb99-11e6-9efa-1324c4b29209.gif)

**Comment by gregvanl** [comment]
Thank you for your interest in the VS Code documentation. At this point, we don't have any near term plans to create localized versions of the website. This may change in the future and we are aware of the demand for localized documentation.
