### ISSUE TITLE
Error when trying to use the `lzma-native` npm module

### ISSUE THREAD

**Issue by LaurentTreguier** [Microsoft/vscode#19969]
- VSCode Version: 1.9.0
- OS Version: Fedora 25

Steps to Reproduce:

1. Create a new extension using `yo code`
2. Add the `lzma-native` npm module as dependency
3. Import the module and use it in the extension (simply `console.log`ging it is enough)
4. Start the extension debug mode

VSCode gives the error message `Here is the error stack:  Error: Module version mismatch. Expected 50, got 48.`. The problem could be coming from the `lzma-native` module, but so far using the module outside of VSCode seems to work just fine.

This module uses `node-pre-gyp` to provide ready-to-use precompiled binaries. Could the error be related to this ?

**Comment by bpasero** [comment]
@LaurentTreguier if you want to use native modules with your extension you have to compile it against the headers of the electron version we are using. 

In general we discourage use of native modules with extensions because they will fail once we update our electron version.

You can see in our scripts/npm.sh script how we setup npm to install for the version of electron we are using.
