### ISSUE TITLE
Yaml and Markdown yaml front matter doesn't like single digit months or days

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#19960]
According to the YAML spec http://yaml.org/type/timestamp.html, single digits are allowed:

>  -[0-9][0-9]? # (month)
>  -[0-9][0-9]? # (day)

Note this applies to both the front matter section at the top of a markdown file (as below) and in a `.yml` file

Test text:

```
---
date1 : 2016-8-2
date1 : 2016-8-20
date1 : 2016-08-2
date1 : 2016-08-20
date2 : 2016-11-20
---
```

![image](https://cloud.githubusercontent.com/assets/2193314/22624179/398edf2a-eb28-11e6-8fd1-2feb228cdef2.png)

![image](https://cloud.githubusercontent.com/assets/2193314/22624184/47c199b6-eb28-11e6-927d-7f0ee2f6b0af.png)

![image](https://cloud.githubusercontent.com/assets/2193314/22624183/4114c17e-eb28-11e6-85d1-03e0df70ce02.png)

**Comment by mjbvz** [comment]
I think this is by design. The [yaml timestamp spec](http://yaml.org/type/timestamp.html) is weird in this case. Iit looks like single digit months and years are only supported in full timestemp literals that include times:

```
 [0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9] # (ymd)
|[0-9][0-9][0-9][0-9] # (year)
 -[0-9][0-9]? # (month)
 -[0-9][0-9]? # (day)
 ([Tt]|[ \t]+)[0-9][0-9]? # (hour)
 :[0-9][0-9] # (minute)
 :[0-9][0-9] # (second)
 (\.[0-9]*)? # (fraction)
 (([ \t]*)Z|[-+][0-9][0-9]?(:[0-9][0-9])?)? # (time zone)
```
In the first ymd option, you have to use two digits for months and days. I've checked a few yaml validators and they seem to be consistent in parsing `2016-8-2` as a string instead of as a date

**Comment by Tyriar** [comment]
Ah you're right, I didn't look thoroughly enough and thought the opening paren on the hour line ended at the end. :+1: 

I guess I'll just use double digits then :wink:
