### ISSUE TITLE
Image opened in editor will closes if writing to it takes too long

### ISSUE THREAD

**Issue by kevinthr** [Microsoft/vscode#19965]
Hi, I'm developing a node script that generates PNGs, and I like to have the generated PNG open in one pane of the editor, the script in the other, and run the script and watch the PNG update in the editor. However, sometimes when generating the image, the tab will close with this error:
![image](https://cloud.githubusercontent.com/assets/6397222/22624446/62a6fb96-eb31-11e6-803f-decb092fab6a.png)
I don't think it is a problem with my script, as it runs without issues outside of Code, and I've never had this issue with Sublime. Does anyone have some insight into this?

- VSCode Version: 1.9.0
- OS Version: macOS 10.12.2

**Comment by bpasero** [comment]
@kevinthr can you somehow send me the contents and steps to reproduce?

**Comment by rmunn** [comment]
I wonder if there's a race condition anywhere. @kevinthr, how does your script write the .png file? Does it write it directly to the output location, or does it write it to a temp file and then rename the temp file into the output location?

Because if it writes the file directly to the output location, I could see a potential race condition that goes like this:

1. The script asks the OS to write several dozen kilobytes to `output.png`.
1. The OS buffers this output in chunks of, say, 1K, and starts writing them.
1. Halfway through the write, the OS decides that it's time to switch to the VS Code process. At this point, half of `output.png` has been written to disk, while the other half is still in OS buffers. The half that's been written to disk is not (currently) a valid .PNG file since it does not yet contain an `IEND` chunk, and it almost certainly contains at least one `IDAT` chunk that's not complete (and whose chunk length doesn't match the data inside it).
1. VS Code, having been awakened by the OS, sees that its filesystem watcher has given it a "file changed on disk" event for the `output.png` file which was open in the editor. (This assumes that the filesystem watcher is not aware of OS buffers, which may not be the case in every single OS. I don't use OS X so I don't know its ins and outs.)
1. VS Code tries to load the new version of `output.png`, which is currently an invalid PNG file.
1. VS Code sees that an invalid PNG file was loaded, and decides to close the tab with an error.
1. At some later point, the OS switches back to the Node script, and finishes writing its buffers to disk. The `output.png` file is now a valid PNG, but it's too late: VS Code has closed the tab.

One way to replicate that hypothetical race condition would be to write a script that would write *half* of a `.png` file, pause 15 seconds, then write the other half of the file. Open that `.png` file in VS Code, then overwrite it with that pause-in-the-middle script.

If this race condition is what's happening, then one solution could be for VS Code to issue an error in the `.png` file's editor window, but *not* close the editor tab. Then, when the `output.png` file finishes being written to disk and the OS (and/or filesystem watcher) sends another "file changed on disk" event, VS Code tries again to load the file, and this time the file is a valid .PNG so it loads just fine.

**Comment by bpasero** [comment]
This is an interesting explanation, though not sure it applies. VS Code has a simple way to detect if a file is binary or not: Check the first 512 bytes for 0-bytes. If at the time VS Code checks the file, the file has no 0-bytes, we assume it is text and then open it. If before opening it you manage to write 0-bytes into it, this error might happen. Very unlikely to happen though...

**Comment by kevinthr** [comment]
I am writing with the pngStream functionality in node-canvas, described here: https://github.com/Automattic/node-canvas#canvaspngstream

**Comment by kevinthr** [comment]
Here is a script that will produce this behavior

```
var Canvas = require('canvas'),
    fs = require('fs'),
    Image = Canvas.Image,
    out = fs.createWriteStream(__dirname + '/image.png')

var canvas = new Canvas(512, 512),
    ctx = canvas.getContext('2d'),
    stream = canvas.pngStream()

ctx.fillStyle = 'goldenrod'
ctx.rect(0, 0, 512, 512)
ctx.fill()

stream.on('data', function(chunk) {
    console.log('writing png chunk')
    out.write(chunk)
})

stream.on('end', function(){
  console.log('saved png')
})
```

**Comment by bpasero** [comment]
@kevinthr facing issues running `npm install`:

```
> canvas@1.6.2 install /Users/bpasero/Desktop/bug/node_modules/canvas
> node-gyp rebuild

Package cairo was not found in the pkg-config search path.
Perhaps you should add the directory containing `cairo.pc'
to the PKG_CONFIG_PATH environment variable
No package 'cairo' found
gyp: Call to './util/has_lib.sh freetype' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.4.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/bpasero/Desktop/bug/node_modules/canvas
gyp ERR! node -v v6.9.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN vscode-png-example@1.0.0 No repository field.
npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
```

**Comment by kevinthr** [comment]
Oh yeah, you need to install some libraries for canvas to install. Described here: https://github.com/Automattic/node-canvas#installation

**Comment by kevinthr** [comment]
did it work

**Comment by bpasero** [comment]
No, I was not able to install the dependencies for some reason.
