### ISSUE TITLE
TypeScript: Global variables and functions marked duplicate

### ISSUE THREAD

**Issue by theOriginalMuktaka** [Microsoft/vscode#19971]
- VSCode Version: 1.9.0
- OS Version: Windows 10

Ran into this while learning TypeScript.

Steps to Reproduce:

1. Create an empty folder with a new TypeScript file helloWorld.ts in VS Code.
2. Type in declaration `let my_var : number = 100`
3. Compile into a .js file into the same folder using command `tsc helloWorld.ts` (compile succeeds without warnings)
4. Open compiled .js in VS Code (either in right pane or in a new tab).
5. Navigate back to the open TypeScript file.
6. Add a space to the file.

At this point, `my_var` is underlined in red and the tooltip on hovering over it says:

[ts] Cannot redeclare block-scoped variable 'my_var'.
let my_var: number

One can observe a similar behavior with functions, where VS Code claims there is one more override somewhere, ie

[ts] Duplicate function implementation.
function doNothing(): void (+1 overload)

![2017-02-05 1](https://cloud.githubusercontent.com/assets/15193589/22625862/09e1bd4e-ebc6-11e6-94e4-ac000437422a.png)

VS Code marks the function / variable as duplicate only when it is present in the compiled .js file.

Deleting the .js file makes the underlines go away.

**Comment by mjbvz** [comment]
VSCode does not know that the javascript file is compiled from the TypeScript file in this case, so it is viewing them both part of the same project. That's why it thinks there are duplicate symbols.

To fix this, create a `tsconfig.json` file in the root of your project. The file can just consist of `{}`. The important compiler setting specified by the `tsconfig.json` is `allowJs` which has a default value of `false`. This instructs TypeScript to ignore JavaScript files.

You can also include or exclude specific files using the `files` or `include`/`exclude` settings: https://www.typescriptlang.org/docs/handbook/tsconfig-json.html . In this case, you would want to include the TypeScript file but not the JavaScript one

**Comment by theOriginalMuktaka** [comment]
Is there a reason why VS Code waits for the user to navigate to the JavaScript file to see whether there is a duplicate?

**Comment by theOriginalMuktaka** [comment]
Shouldn't VS Code automatically scan the workspace on opening the window / creation of the JS file and not wait for the JS file to be opened to check for possible duplicates (as it did in my case)?

I am going to go out on a wing and assume that if a JS file with a duplicate symbol was created in the same folder as the TypeScript file through a git pull then VS Code wouldn't detect the duplicate.

**Comment by mjbvz** [comment]
@theOriginalMuktaka We only treat the workspace as a TS or JS project if the workspace root contains  a `jsconfig` or `tsconfig` file. Otherwise only opened files are included in the active project
