### ISSUE TITLE
'Extensions: Check for Updates' does nothing

### ISSUE THREAD

**Issue by borekb** [Microsoft/vscode#19981]
_Extensions: Check for Updates_ does nothing even though there is at least one update:

![image](https://cloud.githubusercontent.com/assets/101152/22627424/3cfc026e-ebc3-11e6-84a5-bae3cbfe3751.png)

Code 1.9.0
Windows 10

**Comment by sandy081** [comment]
@borekb May I know if that particular extension was installed through `vsix` option or normally?

**Comment by borekb** [comment]
Normally. When I restarted Code, the update showed up.

**Comment by joaomoreno** [comment]
That new version might not be compatible with your version of Code.

**Comment by joaomoreno** [comment]
That version might not be compatible with your version of Code.

When you restarted, was that due to a Code update?

**Comment by borekb** [comment]
No, it was not after a Code update. The flow was, roughly:

- I updated Code from 1.8 to 1.9 a week ago.
- The author of API Elements rapidly released version 0.6.1, 0.6.2, 0.6.3 and 0.6.4 in one day. They all work in VS Code 1.9 just fine.
- When I was on 0.6.3 and 0.6.4 was already released, the "Check for Updates" command did nothing.
- I restarted Code and the update popped up immediately (I was notified in the Extensions side bar roughly after 5s after the start).

**Comment by joaomoreno** [comment]
Interesting. @sandy081 ring any bells?

**Comment by sandy081** [comment]
Hmm no. Is this could be any caching from Market place?

**Comment by joaomoreno** [comment]
Could be...

**Comment by sandy081** [comment]
I would try to reproduce it by mimicing the above scenario

**Comment by gandhis1** [comment]
This looks like it may be related to https://github.com/DonJayamanne/pythonVSCode/issues/712

**Comment by sandy081** [comment]
When I tried to reproduce it, Update button for an extension did not appear immediately after I published a newer version of it. After couple of minutes, I checked for updated then it appeared. It could be due to the caching in Market place. I assume this issue is also due to same reason. 

If it is seen consistent or update button does not appear after couple of minutes until reload please reopen it. In such case, please also provide more information that can help us in reproducing it.

Thanks.
