### ISSUE TITLE
HTML string inside TypeScript and JavaScript files?

### ISSUE THREAD

**Issue by mohsen1** [Microsoft/vscode#2000]
When using Angular 2 and TypeScript I noticed that editing `template` strings of components in TypeScript files are not working as one expect. There is not autocomplete for tags and other usual HTML editing features. 

For example

``` ts
import {Component} from 'angular2/core';

@Component({
    selector: 'my-app',
    template: '<h1>My First Angular 2 App</h1>'
})
export class AppComponent { }
```

Of course it's because the type definition has declared `template` as a String and no part of VSCode knows that it's an HTML string.

My proposal is to define a `HTMLString` type where it's basically just string but helps tooling in cases like this.

If it was possible to do this, then we can define `CSSString`, `JavaScriptString`, `SCSSString` and so on...

**Comment by cebor** [comment]
:+1:

**Comment by dbaeumer** [comment]
I copied the item to the TS repository to hear their opinion: https://github.com/Microsoft/TypeScript/issues/6778

**Comment by sheldonbarnes** [comment]
Consider using templateUrl, and specifying a HTML file name.  You can then get all the autocomplete in that HTML file. I think that is better than mixing code and HTML like Classic ASP.

Example:

https://github.com/sheldonbarnes/Angular2Learning/blob/master/app/app.customerdetailscomponent.ts

**Comment by felixfbecker** [comment]
#1751

**Comment by MarkPieszak** [comment]
I don't know if this would help in VSCodes case, but @GregOnNet came up with a brilliant solution for adding HTML highlighting to the \` \` back-tick section here for Atom-typescript

https://github.com/TypeStrong/atom-typescript/pull/948

Hoping that might help potentially add this ability to VSCode!

**Comment by dbaeumer** [comment]
@aeschli please see the latest comment. With what we discussed last week can we achieve them?

**Comment by aeschli** [comment]
@dbaeumer @egamma The solution mentioned above adds the html/angular syntax highlighting directly to the TypeScript grammar. That's one of the options we discussed last week. It would be up to the TypeScript team to decide that. Alternatively we work on adding injection support: https://github.com/Microsoft/vscode/pull/6331.

**Comment by juliusl** [comment]
In the meantime looks like this extension works pretty well:
https://marketplace.visualstudio.com/items?itemName=nwallace.language-vscode-javascript-angular2

**Comment by stefanaerts** [comment]
@dbaeumer @egamma @juliusl @aeschli 
Well the color works with the extension, but the autocomplete of
-> custom html tags, in a angular2 component we call it a selector:.
template: `

              <color-pi...      

will not complete.

**Comment by MarkPieszak** [comment]
True, it doesn't autocomplete html but at least it'll help you with variables you have within that file.

Let's say you had `public someString : string;` in your class, when you do `{{ som...`(it'll show someString). Better than nothing I suppose ;)

**Comment by icenold** [comment]
https://marketplace.visualstudio.com/items?itemName=natewallace.angular2-inline

**Comment by ntziolis** [comment]
Just for other people finding this thread the **link above is the working one**. The other extension from the same author no longer works with the current version of vscode as far as I know. 

The extension does provide:
* intellisense 
* and coloring

But sadly **NO formatting**. There is an open feature request for formatting, give it some love if you also wanne see it included too: https://github.com/natewallace/angular2-inline/issues/6

**Comment by robhaswell** [comment]
Is it desirable to turn this into a more generic solution? What if my backtick contained some JS code for evaulating (yuck), or more likely, I'm providing some inline scripting to an Elasticsearch query?

**Comment by felixfbecker** [comment]
https://github.com/Microsoft/vscode/issues/1751

**Comment by n1ru4l** [comment]
@robhaswell Also SQL would also be awesome

**Comment by kenchris** [comment]
This would be quite useful for hyperHTML/viperHTML and lit-html as well

https://github.com/PolymerLabs/lit-html
https://viperhtml.js.org/

**Comment by motss** [comment]
Meanwhile I found this. https://github.com/Microsoft/typescript-lit-html-plugin

**Comment by mjbvz** [comment]
Yes for angular, try the angular-inline extension and for lit-html, try:

- lit-html syntax highlighting extension: https://marketplace.visualstudio.com/items?itemName=bierner.lit-html
- Lit-html IntelliSense TypeScript plugin: https://github.com/Microsoft/typescript-lit-html-plugin

![lit-html](https://user-images.githubusercontent.com/12821956/31469293-27e03aee-ae96-11e7-9b37-072aa4bdac13.gif)

---

I posted more information about embedded language support in https://github.com/Microsoft/vscode/issues/5961#issuecomment-335964652 as well. To sum up, you can already write extensions and TypeScript plugins that contribute support for embedded languages. The main remaining work is to polish the experience so that you only need to install a single vscode extension to get syntax highlighting and intellisense for your template strings. This work is now being tracked by #5961

Closing this issue in favor of #5961

**Comment by ntziolis** [comment]
A bit more context. The feature used here is called `Tagged_template_literals`
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#Tagged_template_literals

It actually gives the ability to effect replacements on the fly like (null values etc).

Since it tags the following code it can than easily be used to switch to the right language for formatting. Detecting the tag and mapping that to a formatting is all the extension does.

There are literal tags for SQL already, not sure about T_SQL though:
https://www.npmjs.com/package/sql-tagged-template-literal
https://www.npmjs.com/package/sql-template-strings

So all one has todo for SQL formatting one is to create a simple extension detecting the tag and using one of the available sql formatters. 

Instead of building one extension for each tag I would suggest todo one of the following:
- Create a generic extension that allows a to configure a mapping of **file extension + tag to vscode formatter**  so that we don't need tens of extension for inline formatting.
- Or instead of a generic extension build this config based mapping capability into VSCode directly.
  - This is basically an extension of the existing approach as vscode already allows to specify formatting for unknown file types via config.
  - It should be off by default to not impact perf.

I personally vote for the second option as I feel:
- the IDE should handle all cases of formatting detection if it already handles file extensions and 
- it being very straight forward and not bloating

Here is a super simple reference to build your own literal tag:
http://exploringjs.com/es6/ch_template-literals.html#sec_implementing-tag-functions
