### ISSUE TITLE
Right clicking on unstaged files and Stash changes stash all files not only this one file.

### ISSUE THREAD

**Issue by dzienisz** [microsoft/vscode#200120]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Version: 1.84.2 (Universal)
- OS Version: MacOS Sonoma

Steps to reproduce:

1. Have few files staged and one file unstaged
2. Right-click on unstaged file and choose `Stash changes`
3. Write stash name

When I repeated the process, all files—staged and unstaged—were stashed, but only the unstashed files vanished from the source control list. Initially, I believed that nothing had happened because the user interface haven't refreshed.

My idea is to stash only one file (stashed or unstashed) for future development. Is that even possible?

**Comment by lszomoru** [comment]
The `Stash changes` action in the context menu is not part of VS Code core, and is probably contributed by an extension that you have installed. Do you by any chance have GitLens installed? If so, could you please file an issue in [their repository](https://github.com/gitkraken/vscode-gitlens/issues) so that the extension author can investigate this further? Thanks!
