### ISSUE TITLE
Allow to contribute to settings.json via config-editing extension

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#20030]
My scenario is that I have a setting (`window.title`) which I want to provide IntelliSense for because the value of this setting can have variables (e.g. `$(activeFile)`).

I tried two different strategies:

1. from the main side: this is https://github.com/Microsoft/vscode/issues/20028

2. do it proper and from the `config-editing` extension. however I fail to provide a completion item provider for `**/settings.json` that gets triggered. In the [activate](https://github.com/Microsoft/vscode/blob/master/extensions/configuration-editing/src/extension.ts#L16) method I do:

```typescript
context.subscriptions.push(registerSettingsCompletions());
```

Which is implemented as:

```typescript
function registerSettingsCompletions(): vscode.Disposable {
	return vscode.languages.registerCompletionItemProvider({ pattern: '**/settings.json' }, {

		provideCompletionItems(document, position, token) {
			const location = getLocation(document.getText(), document.offsetAt(position));
			console.log("location");
			if (location.path[1] === 'window.title') {

				const range = document.getWordRangeAtPosition(position) || new vscode.Range(position, position);
				return Promise.resolve([newCompletionItem('huhu', range)]);
			}
		}
	});
}
```

But again nothing. Not even the `console.log` is printed so I think my contribution is not even being called when I press `Ctrl+Space` in settings.

**Comment by aeschli** [comment]
The code snippet above works when setting the selector to
{ language: 'json', pattern: '**/settings.json' }
The reason is that the JSON language server contributes to `language: 'json'` and already has proposals for `window.title`. Your proposals are never requested as the `pattern: '**/settings.json'` selector is weaker than `language: 'json'`.
The difference to the keybindings.json proposals is that the JSON language server does not have proposals for values there.

I (also) think that this is difficult to figure out as there's no easy way to debug what selectors are used by other provider . @jrieken FYI.

Additionally you need to change `location.path[1]` to `location.path[0]`.
Note: The console output shows up only in the dev tools console (nothing in the output view, not sure if that's a bug)
