### ISSUE TITLE
Move setting specific code out of the JSON language server.

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#20049]
I saw that 
`extensions/json/server/src/jsoncontributions/windowTitleContribution.ts`
got added.
Please move this to
`configuration-editing/src/extension.ts`

When at it, also do the same for
`extensions/json/server/src/jsoncontributions/fileAssociationContribution.ts`
`extensions/json/server/src/jsoncontributions/globPatternContribution.ts`

**Comment by bpasero** [comment]
@aeschli maybe you could see my changes in [extension.ts](https://github.com/Microsoft/vscode/blob/master/extensions/configuration-editing/src/extension.ts#L97). Everything seems to work fine, except for some unknown reason I am not getting the list of languages in the `files.associations` completion when I am inside a value. I verified that my code gets executed but IntelliSense shows no languages.

Otherwise I am also not sure if I am doing the check for `key` vs `value` right. In the previous code I was nicely being called to provide key or value completions.

Finally, we still need to convert `projectJSONContribution.ts`, not sure who owns that.

**Comment by aeschli** [comment]
Removing projectJSONContribution depends on https://github.com/OmniSharp/omnisharp-vscode/pull/224 being merged.

**Comment by aeschli** [comment]
I pushed a fix for the languages (quotes were missing). 
To find out wether key or value is completed, use `location.isAtPropertyKey`.

There are still issues for completing directly after 'files.associations' (curly brackets are missing). Assigning back to you.

**Comment by bpasero** [comment]
@aeschli thanks!
