### ISSUE TITLE
In the Find/Replace widget, labels for the "Replace" and "Replace All" buttons don't show keybindings

### ISSUE THREAD

**Issue by ajkerrigan** [Microsoft/vscode#2004]
In the Find widget, the "Previous match" and "Next match" buttons have labels which include their associated keybindings in parentheses. The "Replace" and "Replace All" buttons in the Replace Input box don't display keyboard shortcuts.

I looked into this a bit before creating an issue, and the solution isn't the simple "look up keybinding --> add to label" approach that I hoped for. It looks like Replace and Replace All don't actually have keybindings defined. Instead, the keys are hardcoded into the `_onReplaceInputKeyDown()` method of [findWidget.ts](https://github.com/Microsoft/vscode/blob/85de39a54d78de5d247b57d1e2c50cc81192212e/src/vs/editor/contrib/find/browser/findWidget.ts#L284-L292).

I would like to see Replace and Replace All get configurable keyboard shortcuts. The defaults would come from the existing hardcoded values, so the core functionality would be unchanged. With configurable keyboard shortcuts it would be easier to display them cleanly on the Replace and Replace All buttons, and we get some flexibility as a free bonus.

I would like to implement this and submit a PR, but wanted to document and perhaps discuss the issue first to make sure that sort of contribution would be OK. Some comments in #406 brushed up against what I'm suggesting here, but I didn't find any other potential duplicate issues.

**Comment by isidorn** [comment]
I know the find widget is undergoing some reconstruction but @alexandrudima is better to comment on this

**Comment by alexandrudima** [comment]
@ajkerrigan PR welcome! :+1:

I don't have any big changes planned in the find widget anymore, perhaps only to address feedback in #1476 (to move the match count outside the find input), but that shouldn't prevent you from doing a PR :).

I would suggest the following:
* add two new commands in `findController.ts` (similar to `CloseFindWidgetCommand`)
* maybe you have ideas for default keybindings for them that don't collide with others, otherwise they would be fine even without any keybindings
* use the new ids to lookup their keybindings for the labels when the widget is constructed in `findWidget.ts` 

Looking forward to the PR! :+1:

**Comment by alexandrudima** [comment]
Thank you for the PR!
