### ISSUE TITLE
Add ability to style "go to" link without underlines

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#20051]
- VSCode Version: Version 1.10.0-insider (1.10.0-insider)
- OS Version: 10.12.3

It would be excellent if, instead of the normal link underlines on detected "go to" links:

![screen shot 2017-02-06 at 10 05 28 am](https://cloud.githubusercontent.com/assets/835148/22652315/fe67b23c-ec53-11e6-88bc-34bcd6bb5606.png)

We could have — perhaps as part of a user-created theme — a `border-bottom: dotted` sort of underline.

**Comment by alexandrudima** [comment]
To keep the number of issues in our inbox at a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: we look at the number of votes the issue has received and the number of duplicate issues filed. Thank you for your time and understanding.

If you disagree and feel that this issue is crucial: we're happy to listen and to reconsider.
