### ISSUE TITLE
Should we auto-reload from time to time?

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#2006]
Here is a crazy thought:

If we would be better at persisting view state (e.g. find widget, commit message, undo/redo stack, etc.).
And if it would be a good time (e.g. no unsaved files, no debug session, user is idle for > 10 min).

... Maybe we could auto-reload the window after X hours?

@bpasero @joaomoreno @egamma @jrieken Thoughts?

**Comment by bpasero** [comment]
Why? to clean up memory leaks?

**Comment by alexandrudima** [comment]
I wouldn't say it's just about leaks, but yes, memory consumption would be "improved" :).

**Comment by jrieken** [comment]
might be unexpected for extensions that drive some process with state

**Comment by egamma** [comment]
we would have to handle the case when auto save is off, so that the user doesn't get prompted to save the file.

**Comment by joaomoreno** [comment]
![homer](http://i.giphy.com/4pMX5rJ4PYAEM.gif)

**Comment by justsml** [comment]
Yikes, that sounds like a 'solution' I've seen in Java sites... Ha, @joaomoreno 

Events, with OS listeners is the best, most scalable option IMHO.

**Comment by Tyriar** [comment]
Feels like this would be like hitting the problem with a big hammer instead trying to fix the root cause. Some potential things that could be looked in to instead:

- reducing memory usage
- plugging leaks
- making it easier to find leaks and memory hogs
- periodic clean up without reloading?
- writing about extension development best practices

It would also not work for some users:

- those who typically have unsaved files in their workspace for long periods of time (me)
- users who don't idle for 10+ minutes before there's a problem

Plus extensions could get in to a bad state as @jrieken mentions.

**Comment by alexandrudima** [comment]
Agreed. Too big of a hammer.
