### ISSUE TITLE
Automated functional interface testing (QuickPick, etc)

### ISSUE THREAD

**Issue by Jakobud** [Microsoft/vscode#20068]
- VSCode Version: 1.9.0
- OS Version: OSX 10.11.6

Is there any way to develop automated Extension testing for various VSCode interface elements? For example, if my extension uses a QuickPick to display some options for the user to choose. Is it possible to automate this from a testing standpoint?

**Comment by joaomoreno** [comment]
This is about functional testing, or about testing the function of components.

Specifically about the QuickPick example, there are two components to the whole thing:

- VSCode's quick pick widget, which you should assume to _just work_, since we test it.
- Your extension's code which calls it.

Both components communicate via the [`showQuickPick` API](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L3738), which is just a communication layer.

Instead of asserting that given a certain state, VSCode's QuickPick would show certain elements, you should instead be asserting that given a certain state, your extension will call that API in the right way.

So, the solution is to make a stub of `showQuickPick` which you would make sure to be called instead of the actual API during the tests.

**Comment by Jakobud** [comment]
That makes sense. Thank you.
