### ISSUE TITLE
Terminal toolbar disappears when terminal in panel is focused and terminal editor is open

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#200897]
1. Open terminal panel
2. Open a second terminal in the panel
3. Move the second terminal to the editor area
4. Focus the terminal in the panel area 
5. Click the + to create another terminal in the panel area
6. Click the trash icon to kill that terminal 
7. :bug: the terminal tab area remains momentarily open and then disappears; the icons to e.g. kill terminal for the remaining terminal in the panel area do not come back until you switch to and from a different view in the panel or resize the window

Expected icons:
<img width="164" alt="image" src="https://github.com/microsoft/vscode/assets/30305945/3cb5953c-f5e7-4862-8030-f8aa715f31a1">

Actual icons: 
<img width="770" alt="image" src="https://github.com/microsoft/vscode/assets/30305945/b29f21e9-2bd7-421b-95fc-db5b0ed8803a">

**Comment by Tyriar** [comment]
Dragging a 2nd terminal out of the panel isn't hiding tabs properly. This should only happen if the cursor is over the tabs:

![image](https://github.com/microsoft/vscode/assets/2193314/6960231a-acef-4841-be28-b0ade064cf4f)

I think it's because the mouse leave event never ends up being handled because the drag is
