### ISSUE TITLE
Unable to format the code

### ISSUE THREAD

**Issue by StasyaChehriy** [microsoft/vscode#200844]
Type: <b>Feature Request</b>

When I press the appropriate key combination and go to the command palette, the command "Format document with" is not displayed, but only "Format document". When following this command, the notification " There is no formatter for "python" files installed"  comes, but when the formatter is installed and activated, the code cannot be formatted again.  I tried different formatters, looked at the settings and selected the formatter that is installed at the moment. But despite everything, it is not possible to format the code.
The latest version of VS Code and Python version 3.12.1 is installed on the computer. 

VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.19045
Modes:

```[tasklist]
### Tasks
```

**Comment by brettcannon** [comment]
@StasyaChehriy what formatter do you have installed?

**Comment by StasyaChehriy** [comment]
> @StasyaChehriy what formatter do you have installed?

Prettier - Code formatter

**Comment by brettcannon** [comment]
Prettier doesn't format Python code (see https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode for what it supports).  I would recommend the [Ruff extension](https://marketplace.visualstudio.com/items?itemName=charliermarsh.ruff), otherwise [Black](https://marketplace.visualstudio.com/items?itemName=ms-python.black-formatter) or [autopep8](https://marketplace.visualstudio.com/items?itemName=ms-python.autopep8) extensions.
