### ISSUE TITLE
“visual studio code.app” would like to access data from other apps.

### ISSUE THREAD

**Issue by Ahmed-Fathy-Abkarenoo** [microsoft/vscode#201087]
Does this issue occur when all extensions are disabled?: Yes/No
yes

- VS Code Version: 1.85.1
- OS Version: 14.2
<img width="1440" alt="Screenshot 2023-12-17 at 8 30 48 PM" src="https://github.com/microsoft/vscode/assets/73021160/646e76ce-7ff7-4493-a0b7-db5413345423">

Steps to Reproduce:

1. 
2.

**Comment by fraune** [comment]
Following this thread... I just saw this exact prompt as well today, curious why I'm being asked this.

**Comment by deepak1556** [comment]
This is a macOS sonoma privacy feature when any application tries to access data from a folder that it is not meant to or don't have permissions. This would be related to one of the folders you have open in the workspace. Also, the allow permission is only alive for the instance of the application, so you will get the prompt on every start if the folder is still being accessed. There is not much we can do here, you can try to narrow down the folder by opening a fresh profile in VSCode using `Profiles > Create a temporary profile`

**Comment by GerryWilko** [comment]
Hello, I think this may have been closed prematurely. This issue seems to have started in the latest VSCode release. And the permissions prompt is continous. Clicking allow or deny results in another prompt. I believe I triggered this behaviour by clicking on the comments tab in the bottom terminal window. First it prompted for iCloud Drive permissions then upon denying this I seem to have got my installation in this broken loop. Only a reboot temporarily sorts this issue.

I wonder if this is perhaps related to issues with where the PNPM cache is? Thats all I can think of in terms of files that are outside the repo but referenced within.

This does seem to be a VSCode issue in latest release though from what I can see.

**Comment by cwinters8** [comment]
This may or may not be a good idea 😅 but I did figure out how to suppress the message. In System Settings > Privacy & Security > Full Disk Access, enable the toggle for Visual Studio Code.

<img width="706" alt="full disk access settings" src="https://github.com/microsoft/vscode/assets/40615752/6ff703fd-356c-4676-9fa2-459bf066ee5a">


Obviously this gives VS Code full access to everything everywhere on your hard disk, but frankly VS Code already has access to environment variables in every .env file that gets opened in a workspace and can use my SSH key for git, so I'm not sure how paranoid I can be about other things on my system.

**Comment by fraune** [comment]
It would be nice to see a message that explains _why_ and _what data_ VS Code is trying to access, so I can make an informed decision of whether I should allow or keep it turned off.

**Comment by Eric-llos** [comment]
> This may or may not be a good idea 😅 but I did figure out how to suppress the message. In System Settings > Privacy & Security > Full Disk Access, enable the toggle for Visual Studio Code.
> 
> <img alt="full disk access settings" width="706" src="https://private-user-images.githubusercontent.com/40615752/293598545-6ff703fd-356c-4676-9fa2-459bf066ee5a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5ODY4NjIsIm5iZiI6MTcwNDk4NjU2MiwicGF0aCI6Ii80MDYxNTc1Mi8yOTM1OTg1NDUtNmZmNzAzZmQtMzU2Yy00Njc2LTlmYTItNDU5YmYwNjZlZTVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDE1MjI0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwMzE4OTlmODg0MzIxNDZkMjZmODUzYjYzYjI3YTg0NTgzOTUwOWNmNjE3NmMwNjE2MzUzMjgzZWU4NTc2YzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.M6j-3R7ej3iPeD28lnhBqHLjgc_6TyjEJsVbW2AggDM">
> Obviously this gives VS Code full access to everything everywhere on your hard disk, but frankly VS Code already has access to environment variables in every .env file that gets opened in a workspace and can use my SSH key for git, so I'm not sure how paranoid I can be about other things on my system.

I did the same and it was the only solution I found... I dont like to give full permision but it was the only way :/ Tried to reinstall it and more but nothing worked

**Comment by memeplex** [comment]
Yes, this has become maddening a couple of months ago, I had to restart my computer a couple of times because it went one dialog after another to no end, not even killing the Code process would shut it up. I've given code access to Documents where all my stuff resides. It may be a issue with Sonoma but no other app is showing such bizarre behavior. This issue should be reopened.

**Comment by harripj** [comment]
I am still experiencing this issue using VS Code version `1.86.0` on MacOS 14.3. The prompt is raised and appears to loop (reraise) if I press `Allow`. It appears to desist if `Don't Allow` is selected. On multiple occasions the prompt has been raised even though the VS Code app is not open (although it was opened previously during the same session).

As others have mentioned, the issue appears to be resolved if `Full Disk Access` is granted to VS Code, but I don't think this is the best solution, as a) VS Code is not requesting this permission and b) the access scope should be limited to what is required. Ideally there would also be some explanation for the requested permissions (access to the Documents and Downloads folders etc. is self-explanatory).

I also think this issue should be reopened.

VS Code details:
```
Version: 1.86.0
Commit: 05047486b6df5eb8d44b2ecd70ea3bdf775fd937
Date: 2024-01-31T10:29:15.765Z (1 wk ago)
Electron: 27.2.3
ElectronBuildId: 26495564
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin x64 23.3.0
```

**Comment by perat** [comment]
Still the same the same awful prompt for access to unknown data from other apps.
VS Code is quite interesting IDE, but the ask for permissions without explanation is unacceptable.

```
Version: 1.86.1 (Universal)
Commit: 31c37ee8f63491495ac49e43b8544550fbae4533
Date: 2024-02-07T09:09:01.236Z
Electron: 27.2.3
ElectronBuildId: 26495564
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin arm64 23.3.0
```

**Comment by spinicist** [comment]
I encountered this problem for the first time today.

It occurred because a colleague opened the Home Directory in VS Code. If they opened any subdirectory of their home directory, it did not happen.

I suspect that when VS Code opens ~/ it tries to index everything in ~/Applications, leading to the repeated prompt. It would be useful if Microsoft could add some heuristics to stop this (maybe ignoring `.app` directories?).

**Comment by memeplex** [comment]
> tries to index everything in ~/Applications

Not Applications but Library/Caches|Containers|Application Support|etc is where the data may be. I hope this is not the cause.

**Comment by kiki-hash** [comment]
I would also like to vote that this issue be reopened. With the new Sonoma update I'm periodically getting this infinite look of access requests. Trying the remedy of giving access in System Settings but this should really be investigated.

**Comment by craigtubbpush** [comment]
Surely the devs can do something here. Please reopen - fobbing this off as a user problem seems like a cop out.

**Comment by Lwheat96** [comment]
I am also having the same issue, would love to see a good compromise to this!
