### ISSUE TITLE
"Open in Integrated Terminal" does not set the environment variables of the profile

### ISSUE THREAD

**Issue by momvart** [microsoft/vscode#201247]
Type: <b>Bug</b>

1. Create a custom profile for the integrated terminal and set it as the default.
1. Add an environment variable to be set for the profile.
1. Right click on an item in the explorer view and click "Open in Integrated Terminal"
1. The variable is not set in the environment.

Here's a GIF demonstrating the issue:
![Recording 2023-12-19 at 14 25 55](https://github.com/microsoft/vscode/assets/27495015/5d572fe5-2c58-40a3-880a-7954d8380bb1)

VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:47:11.635Z)
OS version: Linux x64 6.6.3-200.fc39.x86_64
Modes:
Remote OS version: Linux x64 6.6.3-200.fc39.x86_64

**Comment by r-sargento** [comment]
working on this issue

**Comment by r-sargento** [comment]
Hello, 

I have already solved the bug and developed a new unit test for it. My problem is that in my test I have to wait for `TerminalInstance._xtermReadyPromise` to resolve but this is a private attribute, currently my test is working because I have a `setTimeout` before the `deepStrictEqual` so gives time for `_xtermReadyPromise` to resolve and for the code inside the `_xtermReadyPromise.then` to execute but I think this is not a very good solution. 

Any other suggestions so that I can implement this unit test?

**Comment by momvart** [comment]
@r-sargento 
Thank you!
