### ISSUE TITLE
Quick input service needs ugly casts to work well

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#201203]
See this code where I cannot workaround the fact that I have to use `... as ...`:

https://github.com/microsoft/vscode/blob/81604a093b0d8a347e269b5b2f64416025bca28d/src/vs/workbench/browser/parts/notifications/notificationsCommands.ts#L315

https://github.com/microsoft/vscode/blob/81604a093b0d8a347e269b5b2f64416025bca28d/src/vs/workbench/browser/parts/notifications/notificationsCommands.ts#L320

The returned type seems to include `IQuickPickSeparator` and hence the casts are needed.

**Comment by TylerLeonhardt** [comment]
It's been like this forever... one thing we did in API is merge separators with items:
https://github.com/microsoft/vscode/blob/ed220eff3fca4afd17b4714fc3e8e85e98319144/src/vscode-dts/vscode.d.ts#L1857

maybe it's worth doing the same... esp since separators are getting more "item-like" features like buttons.

**Comment by bpasero** [comment]
I would have expected that I can enable separators in options and unless I do, the separator type is not returned. I would assume in most cases no separators are used in simple pickers.
