### ISSUE TITLE
Make a transition for sidebar when toggle open/close sidebar

### ISSUE THREAD

**Issue by AhmedBaset** [microsoft/vscode#201460]

**Comment by sbatten** [comment]
are you asking for an animation?

cc @sandy081

**Comment by A7med3bdulBaset** [comment]
> are you asking for an animation?
> 
> cc @sandy081

Yes

When toggling open/close sidebar it would be great to gradually

**Comment by sbatten** [comment]
We wouldn't do this specifically for the side bar, it would likely apply to all panel-types. We have some precedent for this with view collapsing, but not sure if we want this for the larger panels

**Comment by Tyriar** [comment]
We intentionally use animation very sparingly, and I'm not sure it's a good idea to add more. Animation on the panel or side bar would cause a significant layout in the editor and terminal on each frame for example, and potentially mess up the terminal's rendering on Windows due to the fast consecutive resizes. Also while it may feel "smoother", it could detract from perceived performance as the action takes longer.
