### ISSUE TITLE
Please add a placeholder at lang attribute for built-in html snippet

### ISSUE THREAD

**Issue by ungjinPark** [microsoft/vscode#201531]
Hello, I'm in South Korea working for improving web & application accessibility.

When creating a basic html structure using snippets ("!") in an empty html file, many developers are forgetting they have to modify a lang attribute to service language.  I've seen a lot of cases like that. setting document language is basic for html, but, easy to forget.

I can find pages that different displayed language and html language to easy.

Currently VSCode built-in html snippet's lang attribute is "en", there's no placeholder. I think placeholder may decrase the probability of developers making mistakes.

A lot of developers are starting the writing a document with snippet. but their services are not for only English speakers and readers.

I know that developers can modify that snippet themselves, but since the default snippets are widely used, I want a placeholder to be added to the 'lang' attribute by default.

**Comment by rzhao271** [comment]
Currently, users have to add an entry to the `emmet.variables` setting.

**Comment by rzhao271** [comment]
`lang` and `charset` are still modified in Emmet with the `emmet.variables` setting. The variables are referenced in the `!` snippet as follows: https://github.com/emmetio/emmet/blob/master/src/snippets/html.json#L155.

I don't plan to change how the snippet appears for all VS Code users, but a way for your team to add the lang attribute is to add `emmet.variables` as a workspace setting so that anyone using your workspace will have that Emmet variable set.

**Comment by rzhao271** [comment]
I'll close this issue as out of scope for VS Code, but feel free to file an issue or PR for one of our upstream dependencies, Emmet, at https://github.com/emmetio/emmet/tree/master
