### ISSUE TITLE
VS code terminal 

### ISSUE THREAD

**Issue by Anush0327** [microsoft/vscode#201538]
Type: <b>Feature Request</b>

the vs code terminal is automatically closing and is not working at all

VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by AldrinMathew** [comment]
The terminal gets stuck some time after starting. This happens when any command is run, and not when it is idle. The dialog that shows options to close or keep waiting appears and if I press on `Keep Waiting` many times, sometimes the terminal recovers with the output of the command.

## VSCode Details
- Version: 1.85.1
- Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
- Date: 2023-12-13T09:47:11.635Z
- Electron: 25.9.7
- ElectronBuildId: 25551756
- Chromium: 114.0.5735.289
- Node.js: 18.15.0
- V8: 11.4.183.29-electron.0
- OS: Linux x64 6.2.0-39-generic

## System
OS: Ubuntu 22.04.03

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
/label info-needed

**Comment by meganrogge** [comment]
related https://github.com/microsoft/vscode/issues/201129
