### ISSUE TITLE
When file is open in two editors, symbol highlighting stuck in right-side panel upon deselect

### ISSUE THREAD

**Issue by cdietz7** [microsoft/vscode#201856]
Type: <b>Bug</b>

Steps to reproduce:
1) Open the same file in split window (ctrl + \). For example, I can reproduce the issue with a .tsx or a .gitignore file.
2) In either window, click a symbol name such as a variable or function name. VSCode will highlight all the term occurrences.
3) Deselect (take away focus of symbol) by clicking in empty space somewhere.

Expected result:
Either (A) the split view would act together and deselect the symbol in both views, or (B) each view would act independently and selecting/deselecting would not affect the other window.

Actual result:
The left window deselection happens as expected, but the right window symbol remains highlighted even though the cursor may be nowhere near that symbol.

Doesn't hurt too much...just kind of annoying when I want to stop highlighting a spot to look at the rest of my code.

VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3700X 8-Core Processor              (16 x 3593)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (21.35GB free)|
|Process Argv|--crash-reporter-id 27ea0307-6c51-45cf-be55-0c8508bb4ddc|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vshan820:30294714
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
py29gd2263:30899288
vsclangdf:30486550
c4g48928:30535728
azure-dev_surveyonecf:30548226
89544117:30613380
pythongtdpath:30769146
i26e3531:30792625
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2cf:30928864
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:30885897
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232
dsvsc019:30917259
cp7184t3:30927821

```

</details>

![DeselectBug](https://github.com/microsoft/vscode/assets/1537789/cf1df944-9b9e-4ade-84a2-922d05bac04d)

**Comment by Miphera** [comment]
I also encountered this problem, and saw this issue report after writing my bug report, but I did some more testing and have some additional information on when exactly this occurs:

When using the Split View feature in Visual Studio Code to edit the same file in different sections of the editor, the highlighting of multiple occurrences of variables or symbols when selecting one of them persists even when moving the text cursor to a different point in the code, such as an empty line.
This behavior only occurs for the instances that were opened after the initially active instance. Specifically, if multiple panes are opened side by side with the same file, the panes opened subsequently will be affected. Meaning if there are 3 split view panes with the same file open and their tab is selected/active, Pane 2 and Pane 3 will experience this issue, while Pane 1 will remain unaffected.
Changing the file in Pane 1 to a different tab will clear the behavior in Pane 2, but not in Pane 3, as that was opened after Pane 2, and is therefore affected by Pane 2.
This behavior is independent of the spatial arrangement of the panes.

In the following image, the cursor was moved from the eventsByDate variable in line 638 to line 640, yet the highlighting on each occurrence of the eventsByDate variable persisted:
![image](https://github.com/microsoft/vscode/assets/142249046/5b9983b2-0671-4e0d-9cc1-c38173d1054f)



**Steps to Reproduce:**

1. Open a file in Visual Studio Code. (Pane 1)
2. Use the Split View feature to open the same file in another pane (either by dragging the file tab to a new section of the window or using the middle mouse button). (Pane 2)
3. Select a variable or symbol in Pane 2 to highlight all occurrences.
4. Click on an empty line or select a different part of the code in Pane 2.

**Expected Behavior:**
The highlighting of the variable or symbol and its other instances should clear when the selection is changed or when clicking on an empty line.

**Actual Behavior:**
The highlighting remains across all instances of the file in split view, even after changing the selection or clicking away. The only way to clear the highlighting is to select another variable or symbol.

**Additional Information:**

- The issue does not occur when the split views are of different files.
- The issue was replicated in multiple files, in different projects.
- Extensions installed: All Extenstions were disabled
- OS: Windows 10 Pro 22H2
- VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)

**Comment by cdietz7** [comment]
I can't reproduce it anymore either, looks good from my end. Thank you so much!
