### ISSUE TITLE
Retrieving per-language settings with the extensions API

### ISSUE THREAD

**Issue by stkb** [Microsoft/vscode#20190]
VSCode version 1.9

Is there an official way to do this yet? For example given this settings.json and I want the `editor.rulers` setting for javascript:
``` json
{
  "editor.rulers": [80],
  "[javascript]": {
    "editor.rulers": [100]
  }
}
```

Using `workspace.getConfiguration('[javascript]') ... `doesn't seem to work.

I've found that `workspace.getConfiguration().get('[javascript]')` will give me an object for the whole section, which I can work with, but I don't know if there's a better way.

**Comment by sandy081** [comment]
@stkb There is no api exposed to read configuration given a language because only core editor configurations are supported and I did not see the requirement for exposing it. But would definitely think if there is an appropriate one. But as you said you can work on complete configuration object which has access to the information you need. Under the hood we also do the same. If there are more users doing the same in extensions we can move it as an API.

**Comment by stkb** [comment]
@sandy081 Thanks. My use case was stkb/vscode-rewrap#25 where the extension uses the rulers setting.
As long as a there's a method to retrieve the settings that works that's fine, and nicely this method works for the extensions own settings too. (I understand that's not really supported yet and am following #19642)

**Comment by sandy081** [comment]
As mentioned in my previous comment, all settings data is available through the API. Extension authors can always compute the required settings from it.

This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
