### ISSUE TITLE
Copy line problema

### ISSUE THREAD

**Issue by ProtocolLive** [microsoft/vscode#201929]
Type: <b>Bug</b>

When copy without any selection, and paste, the vscode dont add new line like before

VS Code version: Code - Insiders 1.86.0-insider (1cfc62d46e6b9dd217cd485d7d4591136f421d70, 2024-01-05T16:21:29.391Z)
OS version: Windows_NT x64 10.0.26020
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|11.83GB (4.33GB free)|
|Process Argv|--crash-reporter-id 0cbc0209-e0e1-4885-8ed3-d586cc39c6e1|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.4.2
vscode-intelephense-client|bme|1.10.2
codeium|Cod|1.6.18
dbclient-jdbc|cwe|1.3.4
phptools-vscode|DEV|1.42.14672
profiler-php-vscode|DEV|1.42.14672
gitlens|eam|14.6.1
vscode-github-actions|git|0.26.2
minifyall|jos|2.10.0
vscode-gutter-preview|kis|0.30.0
remote-server|ms-|1.5.0
sftp|Nat|1.16.3
gremlins|nho|0.26.0
code-spell-checker|str|3.0.1
code-spell-checker-portuguese-brazilian|str|2.2.1
tabnine-vscode|Tab|3.56.2010
vscode-input-sequence|tom|0.2.0
change-case|wma|1.0.0
php-debug|xde|1.34.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vshan820:30294714
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
py29gd2263:30784851
vsclangdf:30492506
c4g48928:30535728
a9j8j154:30646983
pythongtdpath:30726887
i26e3531:30792625
welcomedialog:30812478
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30926734
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
aa_t_chat:30882232
cp7184t3:30927821

```

</details>

**Comment by icocar-nts** [comment]
I'm also seeing this same issue this version. 

Expected behavior: copying and pasting without selection pastes the copied line on a new line.
Actual bevavior: 
- When copying and pasting without selection from the start of the line it adds a new line and copies the line which is expected
- When copying and pasting without selection from anywhere else it adds some indentation and pastes the copied line where the cursor is

This works on version 1.85.1

**Comment by boris-garvis** [comment]
I am facing a similar issue on Chromebook - when line is copied without selection expected behavior is it is pasted in new line above cursor but instead it inserts line in position of cursor.

![Screen recording 2024-08-21 00 33 24](https://github.com/user-attachments/assets/5fe07ac2-a375-4504-867f-d66aa97888c5)


VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Linux arm64 6.6.30-02726-gb84bbdf6955e
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|unknown (8 x 0)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off<br>webnn: disabled_off|
|Load (avg)|8, 2, 1|
|Memory (System)|6.48GB (5.34GB free)|
|Process Argv|--crash-reporter-id f3c33404-4b44-4df6-9b27-dbb3a2c5df44|
|Screen Reader|no|
|VM|100%|
|DESKTOP_SESSION|undefined|
|XDG_CURRENT_DESKTOP|X-Generic|
|XDG_SESSION_DESKTOP|undefined|
|XDG_SESSION_TYPE|wayland|
</details>

**Comment by connor4312** [comment]
This was a regression for one version of Insiders and has since been fixed.

**Comment by boris-garvis** [comment]
@connor4312 I just checked on 1.96.2 and I see that unfortunately the issue is still present.

System info is same as in my previous message https://github.com/microsoft/vscode/issues/201929#issuecomment-2299880277 except version is 1.96

**Comment by connor4312** [comment]
Your issue is not related to the original. Please open a new one. Thanks!
