### ISSUE TITLE
Hello world extension doesn`t work 

### ISSUE THREAD

**Issue by Aaronphy** [Microsoft/vscode#20200]
- VSCode Version:1.9
- OS Version:capitan mac os

Steps to Reproduce:

1. I followed the steps of [extensions of hello world](http://code.visualstudio.com/docs/extensions/example-hello-world),  press debugg icon. 
   However,  It didn`t work correctly . 
2.  ERROR NOTICE
     can`t  connect running process (reason:connect ETIMEOUT my ip address:32426)

my node.js  version is  6.9.5.   How to fix it.

**Comment by jrieken** [comment]
@weinand Could that be a debugger connection issue?

**Comment by weinand** [comment]
@Aaronphy debugging the "hello world" extension works fine for me in VS Code 1.9.1 and macOS.
This means that I need additional information.

It would be great if you could list detailed steps so that I can try to reproduce the problem.
What do you mean with "debug icon"? The green play button?
When exactly do you see the error message?
If possible add a screenshot with the error message here.
Open the VS Code "Debug Console" and paste the messages here.

**Comment by jrieken** [comment]
Closing this issue because we still have not seen more information that would allow us to reproduce this.

**Comment by Aaronphy** [comment]
o  . It  solved  tks
