### ISSUE TITLE
"Open Recent" selects an item out of the viewport after filtering

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#20216]
- I have a ton of stuff in my recent history
- I type to filter the list, and it narrows down
- I press the arrow keys to select something and realize that the first selected item is not visible, so the view jumps to somewhere else

I can help debug if you can't repro it. Sometimes it works more as expected, sometimes not.

What determines which item is selected, when it's not the first one? It seems related to which one was more recently selected, and if I flip through a few windows, then I'll see it selecting a different one. But it often is selecting things that I haven't opened in a long time.
![feb-08-2017 08-58-00](https://cloud.githubusercontent.com/assets/323878/22747746/bf01f708-eddc-11e6-800e-aee018140210.gif)

**Comment by bpasero** [comment]
@roblourens yes I need some help here, ideally you could debug this somehow to find out more because this behaviour seems very weird to me.

Quick open has a concept of `autofocus` that we set to determine how entries in the list should be automatically selected while you type. For the picker we typically use `autoFocusFirstEntry` so that the selection is always the entry to the top. There are other values like `autoFocusSecondEntry`, `autoFocusPrefixMatch` but these should not apply here. 

Ideally you could try to reproduce this "running out of sources" so that we can add some logging? I am actually wondering about the behaviour in [`QuickOpenWidget.autoFocus()`](https://github.com/Microsoft/vscode/blob/master/src/vs/base/parts/quickopen/browser/quickOpenWidget.ts#L530) that updates the selection after you typed. I wonder if for some reason we decide to select an element that is not the first element?

If that does not yield results, you could always directly add logging to the [`Tree.setFocus()`](https://github.com/Microsoft/vscode/blob/master/src/vs/base/parts/tree/browser/treeImpl.ts#L268) method which is being called here it seems with the wrong element.

**Comment by roblourens** [comment]
I think that because of https://github.com/Microsoft/vscode/blob/master/src/vs/base/parts/quickopen/browser/quickOpenWidget.ts#L606, once you type something and an item is selected, a new item is not selected unless the selected item is filtered out. And as you type, the order of items can change, and the selected one won't be near the top anymore.

Simpler repro:
- In your history, have a folder `foo-bar/` and a file, `foobar/foobar.txt`
- Type `foo`. Folder is sorted first
![image](https://cloud.githubusercontent.com/assets/323878/22800413/2a1b5e94-eebe-11e6-936c-154f08262941.png)
- Type `foob`
![image](https://cloud.githubusercontent.com/assets/323878/22800420/30dad386-eebe-11e6-828a-c19fe380da1c.png)
- The selected folder is still selected, even though the file is not sorted first

In my case, the initially selected thing is now near the bottom of the list, because I have a ton of things with similar names.

**Comment by bpasero** [comment]
@roblourens thanks I can reproduce now. I really don't know why I added this code:

```typescript
if (doAutoFocus && !autoFocus.autoFocusPrefixMatch) {
	doAutoFocus = !this.tree.getFocus(); // if auto focus is not for prefix matches, we do not want to change what the user has focussed already
}
```

Seems to be coming from https://github.com/Microsoft/vscode/commit/194fa300367de6535717ef5ac588bb310da3d716

Taking it out fixes this issue, let's see how it goes.

**Comment by roblourens** [comment]
Awesome, works just as I expect now

**Comment by aeschli** [comment]
Marked as verified based on [robs comment](https://github.com/Microsoft/vscode/issues/20216#issuecomment-279488732)
