### ISSUE TITLE
[Feature Request] Don't require --verbose flag to display fatal errors

### ISSUE THREAD

**Issue by kjkent** [microsoft/vscode#202115]
When running vscode on a linux system with the kernel flag `unprivileged_userns_clone = 0` set, `/opt/visual-studio-code/chrome-sandbox` fails to run on Arch Linux as it needs 4755 perms but has 0755 perms. I suspect this is something that can/should be fixed in packaging; however, the helpful error message:

```
[30741:0110/011726.909451:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper
binary was found, but is not configured correctly. Rather than run without sandboxing I'm
aborting now. You need to make sure that /opt/visual-studio-code/chrome-sandbox is owned
by root and has mode 4755.
```

 is hidden away unless `code` is run with `--verbose`. Additionally, the program immediately exits successfully with return code 0.

My suggestion is that fatal errors that prevent the program from starting shouldn't require any flags in order to be displayed, and a change may help future users expedite their troubleshooting.

As always, thanks for all your work on vscode :pray:

**Comment by deepak1556** [comment]
The particular log is from the runtime rather than the application and is controlled via `--enable-logging`. We don't have a way to separate fatal vs other logs from the runtime and always enabling them will just flood the console. I understand that it would be nice to show the error without any flags but that is not possible with the current runtime support.
