### ISSUE TITLE
Support git-credential-manager OAuth for Gitea and other git server

### ISSUE THREAD

**Issue by nick008a** [microsoft/vscode#202123]
https://github.com/git-ecosystem/git-credential-manager/pull/1442
In GCM 2.4.1, OAuth for Gitea and other sites are supported. However, if you log into a remote server over ssh and try to push a git repo there (even if GCM is updated to 2.4.1 on the remote server), vs code will still prompt for username and password like in a HTTP basic auth.

**Comment by lszomoru** [comment]
@nick008a, I see that you have already filed an issue in the git credential manager repo. I think that is the best course of action as this does not seem to be an issue with VS Code. I will go ahead and close this issue for now, but please feel free to reopen it if it turns out to be an issue with VS Code. Thanks!
