### ISSUE TITLE
Add a openFilesInNewWindow setting that opens depending on being inside VS Code or not

### ISSUE THREAD

**Issue by stefcameron** [Microsoft/vscode#20213]
Before I get into this bug, thank you for adding this new setting for finer control over how files are opened with Code. Much appreciated!

- VSCode Version: 1.9.0
- OS Version: Win x64 10.0.14393

Steps to Reproduce:

1. Set the new `openFilesInNewWindow` setting to `"on"`
2. Activate an existing Code window and choose "File > Open" or "File > Open Recent" to open a file.

Whether the file is within the open/active folder in the Code window or not, the file is always opened in a new window. I don't find this behavior to be intuitive.

I believe "on" should mean that when I'm working in an **existing** Code window, any "open file" commands I issue **from that window** should result in the file(s) being opened in that same window.

If I take action **outside** any Code window (i.e. from Explorer or double-clicking on a file I've associated with Code (which is technically still Explorer I suppose)) to open the file(s), they should open in a **new** Code window.

As for `"default"` and `"off"`, these values work as I would expect them to so far.

(Note that the `ctrl+p` quick-open command is not affected and works as expected, opening files within the active window.)

**Comment by rmunn** [comment]
I would have the same expectations: that the `openFilesInNewWindow` setting would only control actions taken from *outside* VS Code. If I already have a VS Code window active and choose File->Open (or File->Open Recent), I'd expect that my currently-active VS Code window to be the one to receive the file.

The reason I expect this is because when I'm already inside VS Code, it's trivial to get a new window if that's where I really wanted to open a file: just hit `Ctrl+Shift+N` first, then hit `Ctrl+O`.

BTW, I can confirm that Linux (specifically, Ubuntu 14.04) has the same behavior as Windows in this regard. Not surprising, of course, since this behavior is what was intended by the code, even if it's not what some users apparently expect. :-)

**Comment by bpasero** [comment]
@stefcameron @rmunn again there are platform differences. Mac users expect choices made from the File > Open menu to open inside a new window (as you can see from https://github.com/Microsoft/vscode/issues/371).

Looks like what is needed here is yet another option (or enum value) to do what you suggest here.

**Comment by plmrry** [comment]
The biggest issue for me is that opening a folder will **replace** the content of the active window. What I want is to open a new project folder in a new window, and if I don't remember to open a new window before I open a project folder, all the work (and terminals!) in my active window get blown away.

**Comment by stefcameron** [comment]
@plmrry Have you set `openFoldersInNewWindow: "on"`? That sounds like the behavior you're looking for when opening folders instead of files.

**Comment by bpasero** [comment]
Btw independent from the settings you can force open file/folder into a new window by pressing `Ctrl` on Windows/Linux or `Alt` on macOS.
