### ISSUE TITLE
Voice: from extension link to speech related settings

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#202254]
<img width="1061" alt="Screenshot 2024-01-11 at 7 28 03 AM" src="https://github.com/microsoft/vscode/assets/29464607/b017a8ce-8483-4701-a27b-c42becb1040b">

**Comment by bpasero** [comment]
Any recommendation on the time?

**Comment by meganrogge** [comment]
I tried 2000 ms and it feels nice

**Comment by bpasero** [comment]
I think here we need to find a balance between usability and performance. The current value is `1200` and it means it only takes 1.2s after pause before your text is executed. If we increase this to 2s, people will actually think the feature got slower.

**Comment by meganrogge** [comment]
I think that some users would rather have no auto send. The challenge is how do we make the setting discoverable.

**Comment by bpasero** [comment]
@meganrogge I wonder if the default should adapt to whether accessibility mode is on or off? So that we increase the timeout for when its on?

@sandy081 is there anything I can do to bring a user into the settings editor to a setting that impacts the extension from here:

![image](https://github.com/microsoft/vscode/assets/900690/e1f821b8-0978-4565-9cd7-f03adc5bc453)

The setting is not contributed from the extension though but is a core setting:

![image](https://github.com/microsoft/vscode/assets/900690/16035588-e5cb-486f-8c05-7c2f65ffd85c)

**Comment by bpasero** [comment]
@sandy081 yeah but my understanding is that the command only appears when the extension contributes settings. In this case, the extension does not contribute settings but we have core settings that impact the behaviour of the extension.

**Comment by sandy081** [comment]
You can contribute an action to [ExtensionContext](https://github.com/microsoft/vscode/blob/83127004a87124b1b8b976b9f9022da41814dfd0/src/vs/platform/actions/common/actions.ts#L78) menu id, that opens settings

**Comment by bpasero** [comment]
Thanks!

@meganrogge I am able to contribute an action that opens the setting, would you think thats fine then?

![Recording 2024-01-15 at 16 37 53](https://github.com/microsoft/vscode/assets/900690/1421ac3b-fe95-41c4-b51d-7c8fcd3b0321)

**Comment by meganrogge** [comment]
Yes, that's awesome 👏🏼

**Comment by bpasero** [comment]
**Verification:**
* install `ms-vscode.vscode-speech` extension
* right click it and select "Extension Settings"
* verify the settings editor opens with "voice" settings
