### ISSUE TITLE
DocumentData for notebook cell documents looses notebook releation ship when switching from trusted to untrusted workspace

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#202232]
For the steps see: https://github.com/microsoft/vscode-languageserver-node/issues/1394#issuecomment-1885888954

When a workspace switches from trusted to untrusted only the extension host is reloaded not the workbench itself. When the extension host is initialized it looks like that the link between a cell document and its notebook is not correctly restore. The corresponding document data in the debugger looks as follows:

<img width="934" alt="image" src="https://github.com/microsoft/vscode/assets/1931590/10c6ec60-f580-4316-9f66-d28b3b6258ef">

Observe the undefined notebook.

This makes the corresponding match methods fail.

The extension host does know about the notebook itself

<img width="390" alt="image" src="https://github.com/microsoft/vscode/assets/1931590/55a7fbfe-6c0c-42fa-a578-931ed2f63276">

**Comment by eleanorjboyd** [comment]
steps I took:

1. created new folder, selected trust
2. created new notebook, ran my single print line
3. switched to untrusted (I was prompted to save the notebook since I had not yet)
4. selected to name and save it
5. what used to be the print output message now displayed this error
<img width="1306" alt="Screenshot 2024-02-22 at 11 33 49 AM" src="https://github.com/microsoft/vscode/assets/26030610/a99815a2-de0b-4139-b658-72e23f718ba7">

also got this other error but the error message was much more helpful and explains why it switched
<img width="633" alt="Screenshot 2024-02-22 at 11 35 09 AM" src="https://github.com/microsoft/vscode/assets/26030610/e53f1e9e-853b-463b-826c-41cdaf045735">

**Comment by rzhao271** [comment]
I'm unsure if the scenario above is in scope of the fix, or if the main point of the fix was to fix the issue demonstrated in https://github.com/microsoft/vscode-languageserver-node/issues/1394#issuecomment-1885888954.

Adding verification-steps-needed.

**Comment by jrieken** [comment]
Verify in code that text document data never holds on to a notebook but that this information is freshly computed when calling `match`
