### ISSUE TITLE
Coverage hover covers source code

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#202600]
* run with coverage
* see the nice decorations
* hover over them
* 😕 the hover talks about code it covers...

<img width="709" alt="Screenshot 2024-01-16 at 18 37 35" src="https://github.com/microsoft/vscode/assets/1794099/205bdb6e-bcdf-46e3-b0bb-522ee0cbd47f">

**Comment by connor4312** [comment]
That's part of the reason why I ended up with the "togle inline coverage" action 😛 

Do you have any thoughts on a way to present it better?

**Comment by jrieken** [comment]
The hover text seem quite repetitive, e.g "XYZ was executed N time(s)". I believe the N part is the most valuable because the rest is already rendered as code or redundant. Can you use extra gutter space or inlay hints to show the execution times?

**Comment by connor4312** [comment]
I now show hit counts inline on hover rather than having a bit hover for them. But I still show the "toggle inline coverage" action -- I'm not sure of a better place to put that, and that's an action that users will readily want to take when diving into coverage specifics. Let me know how it feels to you.

<img width="723" alt="image" src="https://github.com/microsoft/vscode/assets/2230985/9c3bb331-7af2-4d0e-9763-81d6d27043cc">
