### ISSUE TITLE
Doesn't read .bash_profile in integrated terminal when using command line 'code' 

### ISSUE THREAD

**Issue by goha111** [Microsoft/vscode#20265]
If you use command line `code` to start the VS Code and then launch the integrated terminal, it doesn't read the .bash_profile prompt, just the origin pure bash.

- VSCode Version: 1.9.1
- OS Version: Mac OS 10.12.3

Steps to Reproduce:

1. Enter `code` in command line to start VS Code
2.Get integrated terminal in VS Code
3.You will find that your .bash_profile isn't read

**Comment by Tyriar** [comment]
You will want to add the following setting to launch bash as a login shell:

```js
"terminal.integrated.shellArgs.linux": [
  "-l"
]
```

More information: https://code.visualstudio.com/docs/editor/integrated-terminal#_linux-os-x

**Comment by Tyriar** [comment]
This is happening because we don't run the integrated terminal as a [login shell](http://unix.stackexchange.com/a/46856/115410) by default. You will need to add the following to launch bash as a login shell:

```js
// macOS:
"terminal.integrated.shellArgs.osx": [ "-l" ]
// Linux
"terminal.integrated.shellArgs.linux": [ "-l" ]
```

More information:

- [Official documentation](https://code.visualstudio.com/docs/editor/integrated-terminal#_linux-os-x)
- [Reasons for this default behavior](https://github.com/Microsoft/vscode/issues/20145#issuecomment-278172268)
