### ISSUE TITLE
Roll out sticky scroll by default

### ISSUE THREAD

**Issue by aiday-mar** [microsoft/vscode#202655]
This iteration we would like to roll out editor sticky scroll by default, since terminal sticky scroll as well as tree sticky scroll will be rolled out by default too.

**Comment by Rishit30G** [comment]
Hi, 
Could you elaborate more on this, I would like to take this up!

**Comment by aiday-mar** [comment]
Hi @Rishit30G thank you for proposing your help. This change is in fact quite minimal and requires likely one of our team members to set up an experiment to roll out sticky scroll to part of our user base. This wok can therefore only be done internally. If you are looking for relatively easy issues where you can contribute you may look at the issues under the VS Code repo having the label `help wanted` here https://github.com/microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22.

**Comment by Rishit30G** [comment]
Sure, glad to hear that 👍🏻 
Will check those issues, thanks for guiding!

**Comment by rjgotten** [comment]
Hi, any way to pre-emptively opt out of having any of the sticky scrolls enabled?
I hate these things with a passion. Great if sticky scroll works for you. It doesn't for me.

**Comment by aiday-mar** [comment]
Hi @rjgotten. When sticky scroll rolls out by default, you will be able to turn it off in the settings. I am not aware of a way to preemptively disable it.

**Comment by mlynch** [comment]
I noticed this was turned on by default, and really did not like the UX. It took quite a while to find the new setting to disable it. I would vote for this to not be turned on by default or at least notify the user.

**Comment by aiday-mar** [comment]
Hi @mlynch thank you for letting us know, we will take this into account. Our ultimate decision will be based on how many people eventually decide to keep it on.

**Comment by gothate** [comment]
Fuck offffff with changing the default

**Comment by promi** [comment]
> I noticed this was turned on by default, and really did not like the UX. It took quite a while to find the new setting to disable it. I would vote for this to not be turned on by default or at least notify the user.

I second that. It took me out of my workflow and I wasted valuable time to find out how to disable it.

**Comment by mlynch** [comment]
I think this is just design bias, so the outcome here is predetermined. It's not possible to really know what this feature is called, and finding it in the settings is really hard. Thus, most people will just leave it on and not really even realize something changed, just maybe that the project explorer feels off, but since they can't figure out how to disable it the analytics will show that it's a huge success. Anyways, just pointing out the flaw here.

**Comment by mattbruv** [comment]
I also agree with @mlynch, turning something on and then using the metric of people that revert it as a way to make the decision to keep it as a default is stupid.

**Comment by rjgotten** [comment]
Agree with @mlynch and @mattbruv - moreover, this is not the first time Microsoft has made this rather dumb mistake.
I've seen it happen over the past year with many of the Github UI updates as well.

**Comment by tzargar8** [comment]
So more "accessibility" turned on by default huh, and no surprise where the demand is originating from.

**Comment by unknownconstant** [comment]
Took me a good twenty minutes to track this down. There's nothing in the UI that says what setting should be changed to get rid of this. I tried searching a bunch of terms but 'sticky scroll' didn't occur to me.

@aiday-mar Any plans to make it clearer in the UI how to disable this, or should I open a bug/feature request?

**Comment by aiday-mar** [comment]
Hi @unknownconstant thank you for sharing your concern. We already have a feature request for making it clearer in the UI. I will discuss this proposition with my colleagues.

**Comment by Ghustavh97** [comment]
I'm really frustrated by how much time I've wasted on what I initially thought to be a bug, only to discover it's actually a feature. The logic behind this does not make sense. What possible use case could justify this feature? When I'm scrolling past a section of code, it's intentional, I'm trying to focus elsewhere. Yet, this feature seems to undermine that very purpose.

Turning on such features is a significant source of frustration for me personally. As developers, we're already navigating complex code, troubleshooting and debugging it to ensure everything works correctly. The last thing we need is for our carefully customized workspaces to be disrupted by an unexpected update. These environments are the result of countless hours of meticulous adjustment, tailored to suit our unique workflows and preferences.

Auto a updates are suppose to be a source of improvement, they are not suppose to throw a wrench into the gears of our productivity. We rely on these tools to enhance our efficiency, not detract from it. It's crucial for developers of such tools to recognize the impact of their design choices on the user experience and to offer more control over these changes, rather than imposing them by default.
