### ISSUE TITLE
VSCode CompletionItemProvider does not work properly or strange behaviour

### ISSUE THREAD

**Issue by 3uovgcfthl** [Microsoft/vscode#20275]
- VSCode Version: 1.9
- OS Version: macOS 10.11.6

Hello, I am developing an extension using API offered by VSCode, concretely the problem happens with `CompletionItemProvider` which is used to provide intelliSense completions.

The problem is that intelliSense is not activated properly and must be activated manually using CTRL+Space. The completion is provided in JSON files, more specifically in the value side. Below you can find some examples:

- Not activated
![screen shot 2017-02-09 at 11 24 36](https://cloud.githubusercontent.com/assets/25660349/22779317/92c20a96-eeba-11e6-88fb-c2a8b0b40b13.png)

- Must be activated manually
![screen shot 2017-02-09 at 11 24 54](https://cloud.githubusercontent.com/assets/25660349/22779324/a0dfa2c8-eeba-11e6-87a6-6b51887348ef.png)

Another strange behaviour:
- You can see in below img that intelliSense is not triggered
![screen shot 2017-02-09 at 11 25 20](https://cloud.githubusercontent.com/assets/25660349/22779346/b5618edc-eeba-11e6-83c4-c308bb0c2015.png)
- But when I hit backspace until colon is removed, the completion showed up:
![screen shot 2017-02-09 at 11 25 28](https://cloud.githubusercontent.com/assets/25660349/22779361/c21f4cfe-eeba-11e6-952b-200978081ecb.png)

Any helps is appreciated!

**Comment by jrieken** [comment]
The 24x7 IntelliSense is constrained by a few rules and sometimes not triggered. We do that make it not to annoying. For instance we don't invoke it when the word left of the cursor is a number or not a word like `://`. Also we don't auto trigger suggestion when the cursor is in the middle of the word - JSON is a bogus word definition because it things `"` is part of a word.
