### ISSUE TITLE
Settings editor shows unrelated settings for "speech"

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#202708]
I was not expecting the 2 settings for formatter and folding to appear:

![image](https://github.com/microsoft/vscode/assets/900690/4f5899b8-8826-4cee-9b2f-97b558e860af)

**Comment by rzhao271** [comment]
It's because of vscode-speech, but I wonder whether it should be an option under those settings in the first place?


![vscode-speech showing up as an option for the editor default folding range provider setting](https://github.com/microsoft/vscode/assets/7199958/49dba5d0-d6a3-45c1-9273-468284ccb88d)

**Comment by bpasero** [comment]
thanks, you are right.
