### ISSUE TITLE
Emmet regression on latest insiders (last two versions) - despite tab bar working again.

### ISSUE THREAD

**Issue by admmasters** [Microsoft/vscode#20282]
- VSCode Version: 1.10.0-insider (1.10.0-insider)
- OS Version: OSX 10.12.3

Steps to Reproduce:

1. Start typing an emmet expansion in a react native project. i.e. View>
2. Press tab

Expected:
View> becomes <View></View>

Actual:
Nothing happens.

Notes:
I have the following set in my user settings:
```
"emmet.syntaxProfiles": {
  "javascript": "jsx"
},
```
This is working fine in the current mainline release.

**Comment by dwperrin** [comment]
#20268 might be caused by same underlying issue

**Comment by ramya-rao-a** [comment]
@admmasters What is the language mode and file extension for the file you are attempting this on? Emmet expansions are working for me in Insiders: in a `js` file, `jsx` file, with and without the setting for `emmet.syntaxProfiles` you mentioned.

`View` gets expanded to `<View></View>` all the time.

Can you try emmet expansions in a html and/or css file? This is to see if your issue is specific to `jsx` or emmet in general.

Any errors in the console?

**Comment by admmasters** [comment]
Hi - I'm not sure what has changed with the latest insiders - but it is now working as of the latest Insiders.

**Comment by ramya-rao-a** [comment]
Good to know, thanks!

**Comment by ramya-rao-a** [comment]
@admmasters 

From VS Code 1.15 onwards, please use `emmet.includeLanguages` instead of `emmet.syntaxProfiles` to get Emmet abbreviation expansion features in your language of choice. And use languageIds on both sides of the mapping.

We are making this move because of the confusion around what `emmet.syntaxProfiles` setting was originally meant for i.e [Customizing final output](https://docs.emmet.io/customization/syntax-profiles/) and what it became i.e enabling emmet in new languages.

Please read more on this at [Emmet 2.0](https://code.visualstudio.com/blogs/2017/08/07/emmet-2.0)
