### ISSUE TITLE
Add support for URL vscode://gitclone/<path> to do a git clone of the specified repository and open it

### ISSUE THREAD

**Issue by StanislawStempin** [Microsoft/vscode#20291]
I would like to be able to achieve the following scenario using URL handlers for VS Code, giving a quick start for any new developers interested in developing using my extension. This issue is about step 2:

//1. Install VS Code -  https://code.visualstudio.com/download
**2. Clone a git hub repository with sample source code -  vscode://gitclone/https/github.com/Microsoft/AL/**
//3. Install extension - vscode://extension/microsoft.al

Step 3 seems to be supported but doesn't work - see #20289

**Comment by joaomoreno** [comment]
Good idea!

**Comment by jordanmkasla2009** [comment]
This idea could be normalized to something like 
`vscode:git/clone?url=https%3A%2F%2Fgithub.com%2FMicrosoft%2FAL%2F&outPath=path%2Fto%2Fproject` 

or even some sort of API for extensions to hook into the URLService something along the lines of `vscode:extension-short-name/command?query=params`

**Comment by hoovercj** [comment]
@joaomoreno How could I even begin to experiment with solutions for this?

As a very basic experiement, I tried to add an additional handler in `extensionsWorkbenchService`, but nothing gets to the debug version of code. If I click on a link such as [<a href=the "vscode:git/clone?url"](vscode:git/clone?url) I never hit debug points (even in the exisitng extension protocol handler with a link that should work) and nothing happens. I assume this is because the actual vscode installation receives the URL, not vscode window that I'm running from source.

What do you or the tema do to the test this/what did you do while developing it?

Thanks!

**Comment by joaomoreno** [comment]
Correct @hoovercj.

This is now much harder... since Git is an extension. So, needs thought.

**Comment by Thaina** [comment]
@joaomoreno I think we could generalized this by allowing url `vscode://extensions/extension.id/SomeThing` can pass the relative path to extension endpoint. And each extension could write a handler to do custom work

`vscode://extensions/git/clone?url=githubURL`

And if that extension was not installed then it would fallback to `vscode://extensions/extension.id`

**Comment by Thaina** [comment]
Seem like general protocol handler supported #46256

https://code.visualstudio.com/updates/v1_23#_protocol-handler-api

Just make it work in git extension then?

**Comment by hoovercj** [comment]
@stanislawstempin does the new [git clone uri support](https://code.visualstudio.com/updates/v1_23#_git-clone-improvements) meet your needs?

**Comment by StanislawStempin** [comment]
Perfect! That covers it
