### ISSUE TITLE
Debug Actions Menu out of window boundaries

### ISSUE THREAD

**Issue by goodlifeinc** [Microsoft/vscode#20298]
- VSCode Version: 1.9.1
- OS Version: Windows 10

Steps to Reproduce:

1. Start Debugging session.
2. Drag Debug Actions Menu more than maximum size of window to the left.
3. You cannot Drag and Drop it again, bacause Drag area is not vissible.
![screenshot_11](https://cloud.githubusercontent.com/assets/7376399/22787132/edd0aa90-eee3-11e6-84b0-448e915f15af.png)
![screenshot_12](https://cloud.githubusercontent.com/assets/7376399/22787133/edd1b764-eee3-11e6-9c08-a636ffaccf29.png)
![screenshot_13](https://cloud.githubusercontent.com/assets/7376399/22787131/edced68e-eee3-11e6-8c86-4c0d3c432fd2.png)

As you can see from the screenshots, when I resize the VSCode window, the Debug Actions Menu is appearing but yet, I cannot see Drag button :)

On fullscreen the menu is completely invisible.

**Comment by isidorn** [comment]
Sorry about this issue, it is fixed in vscode insiders. You can switch to vscode-insiders and everything should work fine.

In case you do not want to do that, here are steps to get out of this bad state
1. Open developer tools
2. Application > Local Storage > File // 
3. Find key `storage/workspace/WORKSPACE_PATH/debug.actionswidgetposition`
3. Delete that key
Here's an example in my workspace
![screen shot 2017-02-10 at 11 31 40](https://cloud.githubusercontent.com/assets/1926584/22823572/838563f0-ef84-11e6-9e12-d14794bf378f.png)

**Comment by goodlifeinc** [comment]
Thank you,
The solution worked perfectly :)

**Comment by davidmurdoch** [comment]
How do you get to dev tools for VSCode?
