### ISSUE TITLE
Test: new auto save options

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#202928]
Refs: https://github.com/microsoft/vscode/issues/181942, https://github.com/microsoft/vscode/issues/189895, https://github.com/microsoft/vscode/issues/160651

- [x] anyOS @lramos15
- [x] anyOS @benibenj

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23202928%0A%0A&assignees=bpasero)

---

Auto save can now be configured on a per-language / per-resource basis. This means that there can be a mix of auto saved and non-auto saved editors. In addition, new settings are provided to prevent auto save in some cases:
* when there are errors in the file
* when the file is outside of the opened workspace

**Testing**
* review the new setting `files.autoSaveWorkspaceFilesOnly` makes sense to you
  * enable it and ensure files outside of the workspace do not get auto saved when auto save is enabled and show a dirty indicator
* review the new setting `files.autoSaveWhenNoErrors` makes sense to you
  * enable it and ensure files with error markers do not get auto saved when auto save is enabled and show a dirty indicator
  * ensure the editor gets auto saved once the marker is gone
* open a multi-root workspace with a few folders and configure auto-save differently per-folder
  * verify that auto save applies as you configured it for each file belonging to the respective workspace folder
* open settings and configure auto save per-language using the `"[language-name]": {}` notation 
  * verify that auto save applies per-language as you configured it when editing files of said language

**Comment by cpojer** [comment]
@bpasero Thank you so much for working on this feature, I just tried it and it's a really good start.

However, it has a significant drawback compared to my initial request in #189895 as it only saves when there are no problems reported for a file at all. My initial request was to auto save when there are no syntax errors. The current behavior won't auto save when there is a TypeScript error (possibly from a type mismatch with another file, requiring me to switch tabs) or an eslint error, even if the code is otherwise totally fine to run in an app.

As a result, this option actually makes me move more slowly and I had to revert to always auto saving regardless of errors. Could this feature possibly be extended with an option to auto save when there are no syntax errors?

**Comment by bpasero** [comment]
@cpojer yeah I understand and sorry for that. I suggest you open a new issue specifically for that case. One challenge is that markers are quite generic:

https://github.com/microsoft/vscode/blob/56ed836ea9bae1602cf83bc286c7480b1370a99f/src/vs/platform/markers/common/markers.ts#L23

At the time I implemented this, I was not aware of a way to know if an error marker is a sytanx error or anything else. We would possibly need to have a setting where you can explicitly spell out which marker category you want to exclude auto save for.

**Comment by cpojer** [comment]
No need to apologize, and I super appreciate that you are working on this at all. I just care about getting to the most perfect developer environment, and this is a stepping stone towards it 😅

I created #204211. Will you be able to prioritize it directly or do we have to do the upvote dance first?
