### ISSUE TITLE
Testing #203095: selection with text not turned into link when setting is `smartWithSelection`

### ISSUE THREAD

**Issue by aiday-mar** [microsoft/vscode#203168]
Testing #203095

- Set “markdown.editor.pasteUrlAsFormattedLink.enabled" to “smartWithSelection”. 
-  Open md file with following text:

```md
    Registry: A service storing and distributing container images and related artifacts, with features like authentication, 
    geo-replication, and more.

    Repository: A collection of container images or artifacts in a registry, identified by the same name but different tags.

    Artifact: An item within a registry associated with tags and layers, identified by a manifest.

    Manifest: A unique identifier generated when an artifact is pushed to the registry, specifying the artifact's 
```

- Select a word and paste a link.
- The word is not turned into the textual part of an md link. Could this be intended? :bug:

https://github.com/microsoft/vscode/assets/61460952/3c4c811c-ef02-4ccf-8e74-e589cbee25de

**Comment by mjbvz** [comment]
@aiday-mar Are the leading spaces part of the actual text in that file? If so, the text will be rendered as a code block instead of markdown:


![Image](https://github.com/microsoft/vscode/assets/12821956/32190551-0bb5-4aa6-aa88-89ad122b4d2a)

We disable markdown link pasting inside of code blocks so I think this is actually the expected behavior. You can then use the paste selector to switch back to a markdown link if you really want

**Comment by aiday-mar** [comment]
Hey @mjbvz, that makes sense and explains what I was seeing. Thanks for the explanation!
