### ISSUE TITLE
VS CODE Team,

### ISSUE THREAD

**Issue by TJM-CODE** [Microsoft/vscode#20329]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|1.6.2|
|mono-debug|ms-vscode|0.13.0|

---

I had spent 2-3 hours last night creating a THEME, in place under...

C:\Program Files (x86)\Microsoft VS Code\resources\app\extensions

...I was enjoying using my new theme this morning when VS CODE announced a update was available.

After the update was install, *blam* all my work last night is gone, my Theme and all assocaited files *gone*, not in the trash, no where to be found.

Steps to Reproduce:

1. Create a Theme in C:\Program Files (x86)\Microsoft VS Code\resources\app\extensions
2. Allow an auto-update of VS-CODE to take place
3. Try to use your custom theme... GONE.

**Comment by sean-mcmanus** [comment]
I'm not on the VS Code team, but that sounds "by design". You're not supposed to make modifications to the Microsoft VS Code folder. What gave you the idea to make changes there? It's owned by VS Code and subject to VS Code updates. Instructions for making your own themes can be found at https://code.visualstudio.com/docs/customization/themes . Extensions under .vscode/extensions persist on VS Code updates.

**Comment by Tyriar** [comment]
Yes if you want to make your own theme derived from one of the default ones you will want to create your own theme and then copy the default theme file over to your theme.
