### ISSUE TITLE
"Configure Do Not Disturb" menu doesn't seem to provide value

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#203225]
Testing #202924

The "Configure Do Not Disturb" menu seems to contain a fixed number of entries followed by a "More..." entry. I'm not a huge fan of this because it is ordered alphabetically, I believe, and that makes its utility limited. I'm likely to always click more since I probably have more extensions than are listed and the chance of the one I want to configure being in the top X is small. If the list were sorted by "recently sent a notification", maybe that would make it more useful. But I would probably just prefer the cleaner single entry approach of "Configure extension notifications..."

**Comment by bpasero** [comment]
Not sure on this one...

I think the jump from bottom right corner to quick pick is always brutal because its totally not in-context. We often hear this feedback when people click on the status bar and do not realise that quick pick has opened as a result.

I somewhat like the idea of sorting the filters by recency, I would even argue to put the most recent one to the bottom to make it appear close to the mouse. I wonder if people would actually understand this or if people would think the list is always random.

The current limit is to show 10 extensions at max.

**Comment by bpasero** [comment]
I will leave it as is.

**Comment by sbatten** [comment]
> I think the jump from bottom right corner to quick pick is always brutal because its totally not in-context.

Yea that makes sense. Though, I would argue that this is more of a configuration step that you do for all your extension at once. If you were doing this in response to a notification, the gear on that notification is the nicer approach.

I feel like there are a lot of cases where we use the quick pick as a somewhat modal form. Should we explore UX of the quick pick that functions that way? e.g. A centered view with dimmed background like custom dialogs?

We would still make it super keyboard friendly but give some focus to it and room to add context.
