### ISSUE TITLE
Markdown live preview doesn't update with missing file extension

### ISSUE THREAD

**Issue by Jamedjo** [Microsoft/vscode#20337]
- VSCode Version: 1.9.1 Win
- OS Version: Windows 10 & OSX

Steps to Reproduce:

1. Create and open markdown file without `.md` extension
2. Open preview editor to the side
3. Make changes to the file
4. Live update doesn't work, neither does reopening the preview
5. Rename the file to have the `.md` extension
6. Live preview still doesn't work
7. Close and reopen file and preview
8. Live preview now works

**Comment by mjbvz** [comment]
Is the language mode for the file set to `markdown`? Once you remove the extension, the file defaults to plain text mode which does not update the preview.

We could change the markdown preview to update for all files types. I believe this is being tracked by #17592

**Comment by SeanPackham** [comment]
No after renaming any file which is recognized as having "Plain Text" content to have a `.md` extension, the content is recognized as "Markdown" but the preview does not update. You need to close the existing preview window and re-preview to get live Markdown updating.

**Comment by mjbvz** [comment]
Renames currently don't work after a preview has been opened. This is tracked by #12033

My question was: what happens if you switch the language mode of the plaint text document to markdown without renaming it? In my testing, this makes the preview start updating again. #17592 tracks supporting live preview update for other language modes besides markdown

**Comment by mjbvz** [comment]
Closing as designed. #17592 Tracks supporting previews for other content types besides markdown
