### ISSUE TITLE
`workbench.statusbar.hidden` entry in the global state is having too many `status.workspaceTrust` entries

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#203439]
While investigating the issue - https://github.com/microsoft/vscode/issues/202359 - I figured out that `workbench.statusbar.hidden` entry is of size 46 KB and has around 1K `status.worksapceTrust.*` properties. We should revisit this and understand why there are that many workspaceTrust entries and minimise it.

**Comment by bpasero** [comment]
Workspace trust status bar entry does 2 things that are questionable:
* each entry gets a random identifier
* the entry is programmatically hidden even if not created [1]

If as a user I decide to hide the entry, I would hide it everywhere.

[1] https://github.com/microsoft/vscode/blob/b0d1f894c38a163ac23e400d41c800decede6117/src/vs/workbench/contrib/workspace/browser/workspace.contribution.ts#L629

**Comment by lszomoru** [comment]
@sbatten, could you please chime in on this as I remember you working on this. Thanks!

**Comment by sbatten** [comment]
This was the relevant message for what we were trying to achieve with the current design https://github.com/microsoft/vscode/issues/120500#issuecomment-814334567

**Comment by bpasero** [comment]
Would it at least be possible to only create the entry when visible and if not, do not create and hide it? The underlying issue here is large amount of state accumulating for hidden trust entries.

**Comment by sbatten** [comment]
I realize that justification talks about unspecified trust state, that is no longer a concept. We also have the banner now. Ok so we can:
- Only create an entry (unique id), if the entry will be visible (i.e. untrusted). User can hide with status bar UX. Con: User cannot make the entry visible in a trusted workspace if it was never loaded untrusted.
- We could go to a single entry id, so that visibility is linked across workspaces. Con: trusted workspaces would show if the user wanted to see when untrusted workspace. 
- Single entry id, but dispose the entry when the workspace is trusted. Con: Can't manage the entry when in a trusted window (who cares, right?)

**Comment by bpasero** [comment]
Yes, thats a great change, even though it causes a slight regression for people in untrusted workspaces that have explicitly hidden the indicator. It will now come back, but then its also easy to hide it again.

Given the status bar entry ID is now no longer dynamic, we could actually now clean up the very large state in `workbench.statusbar.hidden` by removing all entries that are dynamic. I will see to make such a change.

Thanks!
