### ISSUE TITLE
Scrolling lag and unresponsiveness

### ISSUE THREAD

**Issue by Gerwinnz** [Microsoft/vscode#20348]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|

---

Steps to Reproduce:

1. Scrolling with a 'precision trackpad' one direction and then changing direction a few times suddenly scrolling becomes unresponsive and slow. Takes up to a second to start the scroll action from the touch and makes navigating a file very hard. This started recently. PC is a Dell XPS 13 Kaby lake model. 1080p at 125% zoom.

**Comment by pixieaka** [comment]
https://github.com/Microsoft/vscode/commit/e8e1a2e46ec692912dfc618d78f0f9cdc31fb7e8

**Comment by CyrisXD** [comment]
Same problem here.

I think I'm zoning in on this issue. I just got the XPS 15 (9650) and noticed it would freeze and lag 2-5 seconds randomly when using Chrome or Electron apps. Through some research I believe it to be due to Chrome and Chromium's Hardware Acceleration with the Intel HD 630 drivers for Kaby Lake. 

Intel recently released driver updates which seems to have helped the freezing in Chrome a bit, but not so much in VSCode. Scrolling is still very laggy and jumps instead of a smooth scroll. Makes it unusable really.

But Atom seems to have a much nicer scroll at the moment using the Precision Touchpad.

**Comment by alexandrudima** [comment]
Let's track in #13612. The issue should resolve itself once we adopt the latest Electron version. In the meantime, a popular workaround is to "restore" and then maximize the window.

**Comment by warpdesign** [comment]
@alexandrudima any ETA on the adoption of newer Electron ? 1.6.5 which is actually in beta is based on chrome 56.

**Comment by Gerwinnz** [comment]
@alexandrudima Thanks for the update. Can't believe that hack actually resolves the scrolling somewhat and sorry I didn't spot the previous issue. Cheers.

**Comment by alexandrudima** [comment]
@warpdesign: @bpasero is driving it for the April milestone
