### ISSUE TITLE
Document the vscode-languageserver-node modules

### ISSUE THREAD

**Issue by tht13** [Microsoft/vscode#2035]
Please document these modules to make extension development easier.

**Comment by dbaeumer** [comment]
@tht13 there is quite some documentation around. The is a getting started documentation here: https://code.visualstudio.com/docs/extensions/example-language-server and the TypeScript API code here https://github.com/Microsoft/vscode-languageserver-node has JSDoc comments. What kind of documentation are you missing?

**Comment by wholroyd** [comment]
I personally have issues trying to determine where to start tearing apart the example because of how compact it is in a minimal number of files. If the purpose is to teach, the structure of the vscode-go project separating the different features of the language support features into separate files (https://github.com/Microsoft/vscode-go/tree/master/src) does a better job. If the example project did the same thing, it would help a bunch.

The downfall of the vscode-go project is that it lends it's functionality to other tooling written in Go instead of keeping it in the extension. I think the example project does a great job covering all of the features, but it's a bit intimidating today to grok.

**Comment by tht13** [comment]
I have used the example server to its fullest extent to create a python linter, but wish to go further with it. I have seen the JSDocs but struggled to produce documentation from it due to the limited community support to create docs from *.ts files. If you guys could include a gulp script or something similar to generate the docs that would be great :smile:

**Comment by DonJayamanne** [comment]
I believe the documentation on the following pages will help:
- [A Common Protocol for Languages](https://code.visualstudio.com/blogs/2016/06/27/common-language-protocol)
- [Language Server Protocol](https://github.com/Microsoft/language-server-protocol)

**Comment by tht13** [comment]
Thanks @DonJayamanne 
I still think it would be nice to have a generated documentation in the same way the API does, but I am fine for this to be closed as well :smile:

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/vscode-languageserver-node#54

**Comment by dbaeumer** [comment]
Notived that the issue is in the wrong repository.
