### ISSUE TITLE
Generated links in the Chat Markdown are not clickable while the agent handler has not returned a result

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#203794]
I have an agent that adds markdown links to the chat, same as the https://github.com/roblourens/chat-agent-dalle.

Clicking the added links works fine once the chat agent handler has returned its result. Clicking a link before the result was returned has no effect. 

I've made a PR to chat-agent-dalle that illustrates the problem https://github.com/roblourens/chat-agent-dalle/pull/6.

The PR adds a sleep after the link has been added and before the chat result is returned (see <=====):
```ts
		const content = `Here ya go:
		
![image](file://${smallFilePath})

[Full size](${resultUrl})

Have a great day!`;
		progress.report({ content });

	const morecontent = `  \nmore happy days`;   //  <=====
	sleep(10000); // <====
	progress.report({ content: morecontent }); // <=====

		return {};
	});
```
Clicking the link will have no effect until 'more happy days' appears and the chat handler returns the result.

**Comment by roblourens** [comment]
I was aware of this and I always thought it was a different issue- https://github.com/microsoft/vscode/issues/195949 where we can't click something because it is being constantly rerendered. But with your repro I realized that I can't click the link even when there is no rendering going on. And it's actually because I dispose the disposables for the rendered element even for a turn when a render doesn't take place while content is loading.

**Comment by rzhao271** [comment]
I don't have an OpenAI key to test the extension with. Removing verified for now.
