### ISSUE TITLE
Backup & Sync to GitHub Enterprise

### ISSUE THREAD

**Issue by Comnenus** [microsoft/vscode#203893]
I would like to use the Backup & Sync feature, but instead of using a GitHub account and infrastructure, I would like to leverage GitHub Enterprise.

**Comment by sandy081** [comment]
@TylerLeonhardt / @Tyriar Is GitHub enterprise authentication supported on the server and client?

**Comment by TylerLeonhardt** [comment]
It's supported on the client (`github-enterprise` auth provider) but I don't see how we could properly support this because:
1. We have no way of validating the token on the server side because to do so requires making a request to the some random URL (the user's GitHub Enterprise Server (GHES) instance which could be my-random-server.com)
2. Often times organizations put access to this server behind a VPN. This would be impossible to access from Settings Sync servers

The only way to really do this, I think, is if we provided a standalone Settings Sync that could be deployed alongside the GHES instance.

**Comment by Comnenus** [comment]
In my use case, GitHub Enterprise is behind a VPN, and we are not allowed to post internal projects to cloud GitHub, which is exactly why I am looking for this integration.

**Comment by Tyriar** [comment]
Closing as out of scope, I don't think we would implement this without some direction and push from GH.
