### ISSUE TITLE
TS: Goto definition ends up in wrong result

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#20413]
- VSCode Version: Code - Insiders 1.10.0-insider (ef3a8c9e2b642613635c1c53f70bcc86e123ad9a, 2017-02-10T07:05:02.015Z)
- OS Version: Darwin x64 16.4.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|close-all|benjpas|1.0.2|
|vscode-eslint|dbaeumer|1.2.0|
|tslint|eg2|0.8.1|
|vsc-travis-ci-status|felixrieseberg|1.0.5|
|yo|samverschueren|0.9.3|
|ayu|teabyii|0.2.1|
|vscode-open-in-github|ziyasal|1.2.3|

---

Steps to Reproduce:

1. open https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/referenceSearch/browser/referencesWidget.ts#L585
2. click on `Controller`
3. Goto definition

=> you end up in `treeDefaults.ts` even though there is a `Controller` defined within `referencesWidget.ts`

**Comment by mjbvz** [comment]
Verified. Not fixed in TS 2.2 either. I'll see if I can get a smaller repo so that TypeScript can investigate

**Comment by mjbvz** [comment]
This is the correct behavior actually. Since this is a `new` call, we jump to the constructor definition, not the class definition. The `Controller` in `referencesWidget.ts ` does not have a constructor so we open the constructor on the base class.

To jump to the class itself, you can use the new `go to type definition` command
