### ISSUE TITLE
Find in Files (or Replace in Files) with selection should start immediately and not take the focus

### ISSUE THREAD

**Issue by Gruntfuggly** [Microsoft/vscode#20427]
If I select some text and then do Ctrl+Shift+F (or H) it should start the search immediately. Currently I have to press Enter to start it.

I appreciate that it is only a single key press, but it's seems inconsistent with the normal find function (Ctrl+F) which works immediately, and it sort of breaks my 'flow' as I use two hands to press Ctrl+Shift+F, which means I have to move my right hand back to the Enter key.

With normal Find, I can press Escape to refocus the main window - this doesn't work with Find in Files either, so I have to then use the mouse to refocus the main window.

As the results are displayed in a separate window, it shouldn't even really require focusing the search box if some text was already selected.

**Comment by dakaraphi** [comment]
It might be useful to have a new command that runs search immediately.
I can see that there could be cases in a very large project where you would want to set the include or exclude prior to running a search.

**Comment by roblourens** [comment]
I'm not sure, I think I would prefer the current behavior, since I use cmd+shift+f to focus the search viewlet and often have text highlighted on accident. But I can imagine having a command that would do what you're asking for, so it can be configured.

By the way, there are a couple ways to get focus back to the editor. You can actually press cmd+shift+f again to toggle focus back (I just learned this) or cmd+1 to focus the first editor group. Or add your own binding for `search.action.focusActiveEditor`.

**Comment by roblourens** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
