### ISSUE TITLE
Font becomes blurry after a certain amount of tab indentations

### ISSUE THREAD

**Issue by simonvizzini** [Microsoft/vscode#2043]
I saw that there are already a couple of font rendering related issues, so apologies if this issue is already covered by another issue, but I think this may be a special case.

I have installed the [ProggyClean](http://www.proggyfonts.net/download) bitmap font (the TrueType version) and noticed that the font suddenly becomes blurry after 4 tab indentations, but using spaces it looks fine:

![image](https://cloud.githubusercontent.com/assets/10862380/12351756/7a451094-bb80-11e5-8736-be7ff03ebf48.png)

These are my font settings:

````
{
	"editor.fontFamily": "ProggyCleanTT",
	"editor.fontSize": 16,
	"editor.lineHeight": 16
}
````

Other than that I have no special font/editor settings. I'm running Windows 8.1 and latest VS Code.

**Comment by alexandrudima** [comment]
@simonvizzini Thank you for filing! This is definitely a new kind of blurry I haven't seen before. I think it is caused because the font gives the arrow character we use to render leading whitespace (`→`) a width of `15.0313px`, while all other characters get a width of `7px` and because this font is so "thin". Perhaps the font doesn't even contain the arrow (`→`) and an arrow from a fallback font is used.

This makes `HelloWorld` sit at different offsets depending on the number of tabs:
* line with 1 tab: `36.0313px`
* line with 2 tabs: `72.0625px`
* line with 3 tabs: `108.094px`
* line with 4 tabs: `144.125px`
* etc.

These non-round numbers causes the text to be mis-aligned w.r.t. actual screen pixels. Chromium correctly uses screen pixels antialising, but of course it uses different shades as the text becomes more and more mis-aligned, until the text is aligned again. This theory is backed by the fact that one point the text "feels" sharp again, as lines get more and more indentation:

![image](https://cloud.githubusercontent.com/assets/5047891/12420229/1127b19c-bec4-11e5-81e5-a5d601896309.png)

Here is the zoomed in transition at 4 tabs:
![image](https://cloud.githubusercontent.com/assets/5047891/12420385/fc7790e0-bec4-11e5-876a-b9c071271594.png)

And the zoomed in transition at 20 tabs:
![image](https://cloud.githubusercontent.com/assets/5047891/12420415/1f0a26c2-bec5-11e5-8e7d-d5e5dad7cc16.png)

The only thing I can imagine us doing on our side is to render the arrow (`→`) on top or behind the actual text to prevent such mis-alignments.

For now, the only workarounds are to disable `editor.renderWhitespace` or change the font family settings to force Chrome to fall back to a different font for the arrow (`→`). I have tried the following and could notice an improvement in the font rendering, but the arrow becomes more blurry:
```
"editor.fontFamily": "ProggyCleanTT, Arial"
```

This gives each tab indent a width of `37px`:

![image](https://cloud.githubusercontent.com/assets/5047891/12420499/b0a10254-bec5-11e5-941d-e5d11fd4b555.png)

**Comment by simonvizzini** [comment]
@alexandrudima Thanks a lot for the thorough analysis! This makes perfect sense.

Personally I don't think many people use these kind of thin bitmap fonts and I haven't noticed this rendering issue with all the other "programming fonts" I've tried so far. Definitely not a high priority issue in my opinion. The workaround with Arial as a backup font works fine for me. I don't mind the blurry arrow at all, with a dark color theme it's barely noticeable.

**Comment by mitsukuri** [comment]
I guess it has nothing to do with the arrow character and tabs, consider the following renditions: (click to see 100% zoom)
![renderings](https://cloud.githubusercontent.com/assets/14021464/13882491/af7a64de-ed36-11e5-8628-93249701f326.png)

The font is Envy Code R. Notice how the letters 'A' are fully aligned and how the VS Code's rendering ends up being one pixel shorter (compare at lowercase 'z').

**Comment by alexandrudima** [comment]
@simonvizzini I am happy to report that due to some changes I did a couple of months ago, the initial reported bluriness with ProggyClean is gone (leading tabs widths are now defined explicitly)! :)

@mitsukuri I can reproduce the bluriness with Envy Code R at font size 13, but when I go to font size 14 I see it rendered a lot better. I believe the font rendering pipelines of Chromium and Visual Studio are different, and sometimes, when choosing a certain font size, Chromium needs to approximate the glyphs as the specific font size might not be optimized in the font. I can suggest to use fontSize 14.

You can also file a bug against Chromium to raise this issue.
