### ISSUE TITLE
Typing in Find adds many non relevant entries to navigation history

### ISSUE THREAD

**Issue by dakaraphi** [Microsoft/vscode#20435]
When typing in the Find in file input box, many entries are added to navigation history.
After doing a search, I often want to return to the previous location I was at prior to launching find; however, that is often not possible as navigation history is full of locations that were jumped to during typing in the find input box.

**Comment by bpasero** [comment]
@alexandrudima I assume there is no way for me to find out that the selection was changed due to find? Currently I check for the event type being api ([here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/history/browser/history.ts#L60)) but maybe there is more I can do?

**Comment by alexandrudima** [comment]
@bpasero I'm sorry we don't have anything else at this time. Also, since we're doing the extension host, `api` doesn't really mean anything for e.g. vim.

Perhaps we need to completely revisit how is e.g. Visual Studio defining navigation history stops. One idea was to make it time based or distance based, but we should examine there first and figure out if we can implement it...

**Comment by bpasero** [comment]
@alexandrudima here is the strategy today:
* workbench listens for editor changes and editor selection changes
* anytime the editor changes to a different file, we add an entry
* anytime the user navigates more than 5 lines, we add an entry
* anytime the change happened via API we add an entry (*)

(*): I did this last thing only 3 months ago because people complained that using "Goto definition" was not adding a history entry. Now I see how this causes the problem described here because Find is also changing selection via API.

I think we had this discussion before, imho the editor should fill in the history for when navigation happens within the editor because from the outside it is hard for me to decide what serves as history entry and what not.
