### ISSUE TITLE
Add a "select all" button to the find UI

### ISSUE THREAD

**Issue by dgileadi** [microsoft/vscode#20453]
Sublime Text has three buttons in its Find UI: Find, Find Prev, and Find All.

VSCode has the Prev and Next buttons (as arrow icons) but no button to find/select all. There is a keyboard shortcut to select all (Command+Enter on OS X), but a button in the UI would make the feature much more discoverable.

In my case, since the button was missing I instead tried using the command palette to search for a command to select all results. I found Select All Occurrences of Find Match (Shift+Command+L on OS X) but that behaved badly—it replaced the regular expression I was searching for with the currently-selected text, and so it didn't select the items I was searching for. I'd argue that that command should have preserved my original search term, but that's a separate issue.

- VSCode Version: 1.9
- OS Version: OS X El Capitan.

Steps to Reproduce:

1. Open the Find UI and type a search term.
2. Notice there is no button to select all instances.

**Comment by roblourens** [comment]
That's not a very good name for that command - it selects all occurrences of the highlighted string and has nothing to do with find. That's why it replaced your regex. You are looking for alt+enter which isn't in the command palette, but selects all find matches.

We should think about adding a button and changing the name of 'select all occurrences of find match'.

**Comment by diaconesq** [comment]
Here's one killer scenario for 'Select all matches', one that's asked again and again: 

"How do I *keep* only lines matching some text?" 

The simplest answer being: 

- Search for `.*text.*` 
- Select all matches (Alt-Enter)
- Copy
- Paste in new file (or, Select All -> Paste to overwrite the current file)

This is much easier than trying to figure out negative lookaheads or custom regexes that work only for particular search terms.

The problem here is, it's completely non-obvious that VS Code even supports 'Select all matches'. 
Please add a 'Select all' button in the 'Find' dialog box!

VS Code: not obvious how to select all instances.
![VS Code](https://user-images.githubusercontent.com/3482077/53729767-03a54c00-3e6e-11e9-82ec-e68334909a50.png)

Visual Studio has a 'Find All' button in a drop-down. Admittedly, it doesn't do 'Select all', but rather 'list all matches in a different pane'.

Sublime makes this easy, via a 'Select all' button.
![VS](https://user-images.githubusercontent.com/3482077/53729806-27689200-3e6e-11e9-8e12-487397b730fa.png)

![image](https://user-images.githubusercontent.com/3482077/53729866-49faab00-3e6e-11e9-8773-654af9706490.png)

**Comment by chriskuech** [comment]
I find myself doing heavy ad-hoc log manipulation with heavy use of multi-cursor and regex selection.  This is the only scenario for which I still feel I need to use Sublime.  Sublime feels like find and multi-cursor are different facets of the same feature and work very fluidly together, whereas VS Code feels like multi-cursor and find are two completely isolated features, and subsequently not holistic.
