### ISSUE TITLE
Allow manually triggering parameterHints when set to false

### ISSUE THREAD

**Issue by braver** [microsoft/vscode#20455]
I'm interested in the information available in the parameterHints, but the popup is invasive and distracting. However, there is only an option to completely disable the feature.  

I would like to have the option to just disabling it opening by itself. I might then use the command palette or the keybinding to open it at will.

Using VS Code 1.9.1.

**Comment by alexandrudima** [comment]
fyi @joaomoreno @jrieken

**Comment by wyckster** [comment]
The shortcut key (Ctrl + Shift + Space) is supposed to bring up this hint box, but if "editor.parameterHints" is false, then this isn't possible.  This seems like a bug.  There should be a setting to control whether or not they pop up automatically while you are typing, but there should also be a key to allow manually asking for parameter help when you need it.  I assumed that's what "editor.parameterHints" was, but apparently it just turns off the feature entirely.  That's not what I want.  I want what braver described.

Incidentally, I might tolerate the tips always appearing provided that they don't cover source code near where I'm typing.  If they could be made into a bottom-bar or something that doesn't overlap code, then I'd use it.  Otherwise, I prefer it off and I prefer to ask for the hints on demand by pressing a shortcut key.

**Comment by neodon** [comment]
I'm having trouble with this as well.  The popups appear in exactly the most inconvenient location possible and cover up sections of code that I need to see.  It's frustrating to have to keep hitting ESC to get the popup to go away so I can see what I'm doing.  I can disable it entirely via `parameterHints: false`, but then when I need the parameter information I can't get it easily.

It would be useful to have at least one way to manage the popup's behavior.  Even if it's just something like `parameterHints: 'shortcut'` so that I can bind it to *ctrl+p* and get the same behavior as ReSharper in Visual Studio.  Alternatively (or in addition), it would be helpful if I could configure the offsets of the popup.  Then it could always appear, but just not in the most inconvenient location possible in my workspace.

**Comment by samson-sham** [comment]
+1
I need this feature in particular. Since parameter hint is catching the arrow keys, which I can't navigate the code with hints showing up.

**Comment by eriknelson** [comment]
+1, is there any confirmation that this is on the roadmap at all?

**Comment by mjbvz** [comment]
I believe this was fixed during my refactoring of the parameter hints code

![Screen Shot 2019-08-21 at 6 13 01 PM](https://user-images.githubusercontent.com/12821956/63478613-5c2dcd00-c43f-11e9-9ed0-9268fa277f79.png)
