### ISSUE TITLE
Sticky scroll still doesn't work with C++ 17 nested namespaces

### ISSUE THREAD

**Issue by albtam** [microsoft/vscode#204618]
Does this issue occur when all extensions are disabled?: Yes/No

VS Code Version: 1.86.0
Commit: 05047486b6df5eb8d44b2ecd70ea3bdf775fd937
Date: 2024-01-31T10:27:46.147Z
OS Version: Linux x64 5.15.0-92-generic snap

I can still see the exact same issue reported [here](https://github.com/microsoft/vscode/issues/159271#issue-1351966440)

**Comment by aiday-mar** [comment]
Hi could you please include a copy paste of the code where you are seeing this issue, as well as the sticky lines you see and the sticky lines you would expect to see?

**Comment by albtam** [comment]
![image](https://github.com/microsoft/vscode/assets/30054037/974c6707-2dda-4891-8e74-833dd70ad422)

I would expect to see on the left side the  `bool my_function()` line.

I realized that the bug only happens when the clandg extension is enabled. So it might be that the problem is not on the vscode side

**Comment by albtam** [comment]
The code examples are shown under `// Actual code`

**Comment by aiday-mar** [comment]
Hi yes. I tested this on my machine. This may be a bug with rendering the sticky lines from an outline model, we will look into it when there is time.

**Comment by zhourrr** [comment]
Are there any updates on this issue?

By the way, I wanted to express my gratitude for the sticky scroll feature. I've been using it since its early experimental stages, and it has been working wonderfully.

**Comment by aiday-mar** [comment]
Hi @zhourrr unfortunately I have not looked at the issue yet, we receive quite a lot of issues daily. Thank you for the ping.

**Comment by mortinger91** [comment]
I have observed different bugs while using different models.
While using `foldingProviderModel`: a function defined on multiple lines will just show the last one.
```
void myFunc(
    int arg1,
    int arg2)
{
#define myVar
    // body
}
```
This is not true when using `outlineModel`.
I did found a different bug when using `outlineModel`: after a `#define` the sticky scroll will stop displaying the function name.

So both are flawed in different ways basically.
I tried disabling clangd and got the same behaviour.

It's a pity, because otherwise it would be a quite useful feature if it worked consistently

**Comment by aiday-mar** [comment]
would be fixed by https://github.com/microsoft/vscode/issues/168428, closing this issue
