### ISSUE TITLE
intellij-style terminal UI

### ISSUE THREAD

**Issue by DetachHead** [microsoft/vscode#204672]
intellij recently introduced a new terminal UI that significantly improves the user expecrience when using the terminal: https://blog.jetbrains.com/idea/2024/01/intellij-idea-2024-1-eap-2/#revamped-terminal tool-window

https://github.com/microsoft/vscode/assets/57028336/737d7664-94ee-4740-8075-d63a4aa13a63

https://github.com/microsoft/vscode/assets/57028336/d4d9e86d-e974-4c5a-97c3-4d3e32f67998

it would be awesome to get something like this in vscode, since terminals are notoriously ancient and janky to use, this seems like a huge step in the right direction

**Comment by Tyriar** [comment]
I've actually thought quite a bit about this and the conclusion I came to was to have this sort of "block" knowledge available, but not display it so prominently because of said jankiness, especially on Windows where ptys are emulated. We've surfaced that same information as you're calling out for some time now, but do it via the the more minimalist shell integration decorations:

![image](https://github.com/microsoft/vscode/assets/2193314/faa8940d-ec16-429e-b8d1-f2bbab1f34e8)

We also surface the entire command on hover currently, we don't want to show this all the time in order to keep a minimalist design and not clutter the UI with too much information:

![image](https://github.com/microsoft/vscode/assets/2193314/6eed8342-55ca-444d-a1e3-7da9a8e50339)

Recently we also added better prompt detection that knows more about multi-line prompts and commands:

![image](https://github.com/microsoft/vscode/assets/2193314/dba182c8-dadf-4b95-9ca1-12e8dd31be64)

You can navigate between commands like above with ctrl/cmd+up/down, and select between commands by doing the same but holding shift.

For completions, we've had a work in progress for some time but was put on hold and my attention has been moved elsewhere. The approach we're taking there is to keep your usual terminal prompt/input and add intellisense on top of that, as opposed to a textarea which would act differently to the same shell in other terminals. We get this information by communicating directly with the shell, as opposed to some auto complete database ala Fig which can have compatibility issues with CLI versions.

**Comment by DetachHead** [comment]
in my experience this doesn't solve any of the jankiness that comes with interacting with terminals such as text being rendered incorrectly. Here's an example that happened to me today:

![image](https://github.com/microsoft/vscode/assets/57028336/efe1f71f-a74a-4e03-933f-b531af11c9b8)

The command line is such ancient technology and it's baffling to me that nothing has been done to improve it since it was invented decades ago. Text editors have been improved significantly with GUIs, why can't the same be done with the terminal itself?

**Comment by Tyriar** [comment]
@DetachHead plenty has changed, especially in the last few years (like what you and I show above), but ultimately it is built upon a very old technology which has a lot of limitations and baggage. It's not the same with text editors because there is zero baggage there, ie. no APIs which they must adhere to in order to keep compatibility.

Unless IntelliJ is doing something more radical like using separate shell sessions per block, which will likely result in changed behavior WRT other terminals,  those sort of problems will still happen in it as well.
