### ISSUE TITLE
Output channels with same name confuse VS Code

### ISSUE THREAD

**Issue by hoovercj** [Microsoft/vscode#20476]
- VSCode Version: 1.9.1
- OS Version: Windows

Steps to Reproduce:

1. Create a language client/server extension
2. Initialize the Language Client with the name "repro". (`let languageClient = new LanguageClient('repro', serverOptions, clientOptions);` )
3. In the client, create an output channel with the name "repro" (`let outputChannel = vscode.window.createOutputChannel('repro');`)
4. In the client, write something to the output channel (i.e. 'client side')
5. In the server, perform a console.log statement (i.e. 'server side')

Observe in the output pane there are now two channels named 'repro'. Selecting each of them will show the contents of whichever output channel was written to last.

**Comment by dbaeumer** [comment]
This is actually on purpose since there are two separate output channels both having the same label. I agree that we should do something about the labels but output channels can't be shared passed on labels.

The right fix for this is to provide the output channel in the server protocol. 

On which version of the library are you. In 3.0.x version of the libraries all IConnection.console.log notification should appear in the output channel managed by the  client.

**Comment by dbaeumer** [comment]
Closing. We should continue the discussion in https://github.com/Microsoft/language-server-protocol/issues/184
