### ISSUE TITLE
Terminal scrolling regression in application with alternative screen buffer

### ISSUE THREAD

**Issue by jaminthorns** [microsoft/vscode#204769]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.86.1 (Universal)
Commit: 31c37ee8f63491495ac49e43b8544550fbae4533
Date: 2024-02-07T09:09:01.236Z
Electron: 27.2.3
ElectronBuildId: 26495564
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin arm64 23.2.0

Steps to Reproduce:

1. Open a program that uses the alternate screen buffer (like `less`).
2. Scroll really fast.
3. Observe that:
  - The terminal doesn't stop scrolling immediately when you stop scrolling.
  - Changing scroll direction quickly is delayed.

I noticed this regression in the January update (1.86). It's very noticeable when flicking a MacBook's trackpad or flinging a scroll wheel that supports fast scroll (like my Logitech mouse). Here's a video that demonstrates the issue:

https://github.com/microsoft/vscode/assets/6618434/bc2e4f67-7dcd-4872-bd0a-b3ae6a918111

VS Code is on the left, and WezTerm (which doesn't have the issue and behaves similarly to VS Code pre-1.86) is on the right.

**Comment by jaminthorns** [comment]
Clarification: the issue occurs only when the application using the alt screen buffer does _not_ use mouse events for scrolling. When an application uses mouse events, everything seems fine. So, while running this has the issue:

```
man ls
```

This does not:

```
PAGER="$PAGER --mouse" man ls
```

**Comment by eddyb** [comment]
*(on `1.86.2` / 903b1e9d8990623e3d7da1df3d33db3e42d80eda, but also tested `1.88.0-insider` / 61187a0b6547df5911a0ee259f7afda46bac7ec3 and it behaves identically)*

I can confirm both the original issue, and that `--mouse` works around it, though it's weirder than that.

With `--mouse`, the frustrating delayed behavior goes away, but it's still *much slower* than a terminal should be in terms of the maximum scrolling speed (past which physically scrolling faster doesn't change anything), and it's really noticeable with an unlocked scroll wheel (Logitech G502 Hero in my case, as in the air duster memes, tho that would be way overkill for this bug).

I suppose the difference is that with `--mouse`, `less` only waits for a mouse input *after* after each line it scrolls, guaranteeing a very slow-scrolling terminal will have finished before any new inputs are processed.

Whereas by default (mouse scroll events turning into down/up *key presses*), the inputs still get collected while the slow-scrolling terminal is taking its time, and can easily pile up.

---

<details>
<summary>(click to open first, less reliable, benchmarking attempt)</summary>

Using `--mouse` and `-e` (exit when reaching the end), I was able to benchmark the VSCode Terminal:
```console
$ date -Ins; seq -w 1000 | less --mouse -e; date -Ins
2024-03-05T00:08:36,110989866+02:00
2024-03-05T00:08:43,803949975+02:00
```
That's almost 8 *seconds*, during which I had to keep flinging my scroll wheel.

By comparison, Konsole (my main terminal outside of VSCode), with the same setup, can get as fast as:
```
2024-03-04T23:46:49,615374333+02:00
2024-03-04T23:46:49,777998377+02:00
```
That's ~160ms, or *50x faster than VSCode's Terminal*. In part that's because I was had already gotten the scroll wheel up to speed before pressing Enter, but that was also the case for the VSCode run.

Initially I thought reducing the VSCode Terminal height was making it faster, but I got ~8 seconds again after shrinking the height to the minimum allowed (6 lines), so it likely only _feels_ faster.

</details>

---

Sadly, at some point I stopped being able to reproduce those numbers, so I'm less sure of them now.
(And instead started getting 16-18 seconds in VSCode, so it's not like it was in a positive direction)

However, the mouse/human factor can be automated away if we assume that the problem has to do with scrolling performance, and we start benchmarking that, directly:
```console
$ date -Ins; tput smcup; seq -w 100000 | sed 's/$/\x1b[10S/'; tput rmcup; date -Ins
2024-03-05T00:22:50,639432483+02:00
2024-03-05T00:23:00,216516418+02:00
```
So a bit over 10 seconds for VSCode's Terminal. My Konsole seems to handle that in about `0.6s`.

Shrinking the VSCode Terminal's width and/or height doesn't appear to have an effect on timings.

---

However, looking at an old version of VSCode I could easily get (1.78.2), it's not any *faster* according to the automated benchmark, it just seems to somehow combine what `less` is doing (whether explicit scrolling or something else) and only visually update every few frames, resulting in choppy scrolling, and the status line at the bottom flashing a lot.

So this regression may have been caused by trying to make the terminal *look* better, without having the throughput to actually handle all the necessary updates as fast as other implementations.

**Comment by eddyb** [comment]
This is confusing: I tried coming up with a way to benchmark scrollwheel speed (it starts timing after the first 3-byte sequence - `\e[B` for scrolling down - and expects 1000 of them):
- Konsole:
```console
$ bash -c 'tput smcup; saved="$(stty -g)"; stty cbreak -echo; dd bs=3 count=1 of=/dev/null; report="$(dd bs=3 count=1000 of=/dev/null 2>&1)"; stty "$saved"; tput rmcup; echo "$report" >&2'
1000+0 records in
1000+0 records out
3000 bytes (3.0 kB, 2.9 KiB) copied, 1.06856 s, 2.8 kB/s
```
- VSCode 1.78.2:
```console
$ bash -c 'tput smcup; saved="$(stty -g)"; stty cbreak -echo; dd bs=3 count=1 of=/dev/null; report="$(dd bs=3 count=1000 of=/dev/null 2>&1)"; stty "$saved"; tput rmcup; echo "$report" >&2'
dd: warning: partial read (2 bytes); suggest iflag=fullblock
941+59 records in
941+59 records out
2922 bytes (2.9 kB, 2.9 KiB) copied, 0.50047 s, 5.8 kB/s
```
- VSCode 1.86.2:
```console
$ bash -c 'tput smcup; saved="$(stty -g)"; stty cbreak -echo; dd bs=3 count=1 of=/dev/null; report="$(dd bs=3 count=1000 of=/dev/null 2>&1)"; stty "$saved"; tput rmcup; echo "$report" >&2'
1000+0 records in
1000+0 records out
3000 bytes (3.0 kB, 2.9 KiB) copied, 5.16949 s, 0.6 kB/s
```

What happened, was VSCode dropping input events before? (the partial read itself is a bit suspicious)

This change seems independent of scrolling performance, because nothing should be written during the test, and in fact the "alternative screen buffer" feature is *only* used to enable inputting arrow keys with the mouse scrollwheel.

**Comment by eddyb** [comment]
Oh no, this a fix for a cursed bug: https://github.com/microsoft/vscode/commit/d92c1a8aa7c097181ab04d3fc0365bc2923d12ec

By setting the log level to Trace, I could see this:
```
2024-03-05 11:26:01.325 [debug] [1709593] sending data "␛[B␛[B␛[B␛[B␛[B␛[B␛[B" [[27,91,66,27,91,66,27,91,66,27,91,66,27,91,66,27,91,66,27,91,66]]
```
```
2024-03-05 11:26:01.334 [trace] node-pty.IPty#write ␛[B
2024-03-05 11:26:01.339 [trace] node-pty.IPty#write ␛[B
2024-03-05 11:26:01.343 [trace] node-pty.IPty#write ␛[B
2024-03-05 11:26:01.349 [trace] node-pty.IPty#write ␛[B
```
(and a lot more single-escape-sequence trace logs)

This explains everything and is a non-starter: for most smooth scrolling inputs, the 5ms delay can easily slow everything down by 5x, and e.g. scrolling for 10 seconds could take 50 seconds to finish writing.

Write queue logic:
https://github.com/microsoft/vscode/blob/8aca9a53311890fa54f0459c6ef2e8994d4d8ae4/src/vs/platform/terminal/node/terminalProcess.ts#L484-L514

Chunking logic:
https://github.com/microsoft/vscode/blob/8aca9a53311890fa54f0459c6ef2e8994d4d8ae4/src/vs/platform/terminal/common/terminalProcess.ts#L81-L107

---

@Tyriar I'm amazed it took this long to become a problem, one escape sequence every 5ms is really bad throughput, I guess it's just hard to hit with keyboard, only scroll wheel in pager-managed altbufs (or TUI mouse cursor?).

I would suggest decreasing the delay to 1ms, but there is another more immediate problem/solution: the chunking stops just before the 2nd `\e`, but it could stop just before the last `\e` in the chunk, which in my case would send e.g. 7x `\e[B` at once (as decided by `xterm.js`), and 5ms is then fast enough to keep up.

**Comment by eddyb** [comment]
I was able to test changing the timeout to `0`, using:
```sh
env -C $(mktemp -d) $(nix-build --no-out-link -E "with import <nixpkgs> {}; vscode.overrideAttrs (orig: { postFixup = orig.postFixup + ''
  sed -E -i 's/(setTimeout)\((\(\)=>\{[^{}]+\}),5\)/\1(\2,0)/' \$out/lib/vscode/resources/app/out/vs/platform/terminal/node/ptyHostMain.js
''; })")/bin/code --user-data-dir ./vscode-data --disable-extensions
```
(i.e. patching the single use of `Constants.WriteInterval` from `5` to `0`)

And medium-speed scrolling (i.e. the kind of "7 `\e[B` in 7ms" scenario I previously described) now feels real-time, *but* it's not enough: over-scrolling past the end of a pager, especially at higher speed, can still incur a second or two of waiting, so the chunking is the bigger problem/solution.

---

```sh
env -C $(mktemp -d) $(nix-build --no-out-link -E "with import <nixpkgs> {}; vscode.overrideAttrs (orig: { postFixup = orig.postFixup + ''
  sed -E -i 's/(\+1\]===.).x1B(.)/\1\2/' \$out/lib/vscode/resources/app/out/vs/platform/terminal/node/ptyHostMain.js
''; })")/bin/code --user-data-dir ./vscode-data --disable-extensions
```

This second attempt disables the special `\e` (`\x1B` here) handling in chunking, *not* a correct fix by any stretch of the imagination, but I'll take whatever weird bugs it may cause with e.g. pasting, over not being able to use pagers with a mouse scroll wheel.

And testing this version, I can't make it fall behind noticeably, even when trying really hard, so it always feels real-time (even if the hacky chunking workaround means it could theoretically fall behind 5-10ms etc.).

**Comment by Tyriar** [comment]
@eddyb thanks a bunch for looking into this 👏. Do you want to make a PR with your condition so you get credit?

> I'm amazed it took this long to become a problem

Looks like this specifically was introduced relatively recently: https://github.com/microsoft/vscode/pull/201157

---

I think we can also disable the chunking logic outright unless we're on Windows here:

https://github.com/microsoft/vscode/blob/465e40226b7105d183535fccc61a6c018142f172/src/vs/platform/terminal/node/terminalProcess.ts#L443-L445

I'm pretty sure it was only to workaround a weird Windows issue where text was truncated randomly. The chunk logic improvement in #201157 was a general improvement to that workaround which was only needed for Windows to avoid cutting sequences in half.

**Comment by Tyriar** [comment]
Actually looking into it more I remembered wrong apparently, the chunking was required on macOS 🙁 https://github.com/microsoft/vscode/issues/38137. Any optimizations to the chunking algorithm are definitely welcome

**Comment by Tyriar** [comment]
@jaminthorns brand new scroll bar implementation in v1.92 so it makes sense this behavior would have changed 👍  https://code.visualstudio.com/updates/v1_92#_new-scroll-bar

**Comment by eddyb** [comment]
> Do you want to make a PR with your condition so you get credit?

Sorry, I've been swamped and only originally looked into this as it was increasingly impacting my work at the time, I didn't get to spend time on it after I found the workaround.

---

> brand new scroll bar implementation in v1.92 so it makes sense this behavior would have changed

Not 100% sure I understand the connection, but I guess one way they could interact is that the scroll wheel could be ignoring hardware events while previous events' chunks have not been sent yet, instead of accumulating them at the same time?

The new behavior in e.g. `less` feels similar to `less --mouse --wheel-lines=1`, in that it's still *orders of magnitude slower* than the new terminal scrollbar outside of the alternate-screen mode (or pagers in other terminal emulators, like Konsole), and also it doesn't even respect the "hold Alt to modify speed" (or it does respect it but something else neuters it regardless?).

The benchmark I described in https://github.com/microsoft/vscode/issues/204769#issuecomment-1977701889 is still disappointing in VSCode (in fact it takes 16.6s for me now, instead of 5s, whereas for Konsole I can take it down to 2**ms** depending on the scrollwheel speed).

And this is *with* my chunking patch applied still, which is a bit surprising.

---

![image](https://github.com/user-attachments/assets/32e59806-d01e-418c-9775-aab08a9a0772)

I had to go back to confirm but that's 1.91.1 doing 0.4s somewhat consistently (and you can tell it has my patch because the escapes get truncated/corrupted, which is why the chunking is needed AFAIK, but ideally it should allow keeping multiple escape sequences in the same chunk).

Meanwhile 1.92.0, *both with and without chunking patches*, does 16.6s, and never seems to show any truncation/corruption of escapes *even with the chunking patch*.

---

Anyway, the summary is that the jarring "scroll event buffering" is gone, but whatever changes were made result in a "lockstep" slowdown instead - it's not *as* bad, and e.g. `less --mouse --wheel-lines=5` is arguably usable, but there's still a massive discrepancy between regular scrolling (in the terminal backscroll or in a regular editor, etc.) and using a pager.

**Comment by eddyb** [comment]
@Tyriar wait, I made the mistake again of not tracking down the relevant changes first, it looks like you just removed the scroll amount? https://github.com/xtermjs/xterm.js/commit/721d483cc33189150b28c8090aea97610e2e207b

This explains what we're seeing, the value was usually around 7 in my testing - so the only "fix" here was making scrolling 7x slower, which means the chunking can keep up even without my patches.

Was this only done because the correct value was hard to compute?

**Comment by Tyriar** [comment]
@eddyb I pulled that out since the old viewport is gone and with it the ability to translate events into lines scrolled. Created https://github.com/xtermjs/xterm.js/issues/5123 to bring that back

**Comment by Tyriar** [comment]
@eddyb did you want to submit a PR with the chunk improvements?
