### ISSUE TITLE
Supported ffmpeg codecs broken in 1.86

### ISSUE THREAD

**Issue by deepak1556** [microsoft/vscode#205055]
Refactoring in the internal build broke the supported codecs for all custom build flavors, refs https://domoreexp.visualstudio.com/Teamspace/_git/electron-build/pullrequest/949043

**Comment by deepak1556** [comment]
Issue has been addressed in `main` branch with https://github.com/microsoft/vscode/commit/983a3bc0aecfc0772dd7b37919d7da36c89a6f2d

**Comment by deepak1556** [comment]
Isolated and backported the fix to `27-x-y` branch at https://domoreexp.visualstudio.com/Teamspace/_git/electron-build?version=GBhotfix/27-x-y/vscode-macos-env-filtering-and-ffmpeg-config&_a=history

New builds based on `v27.2.3` are not available at https://github.com/microsoft/vscode-electron-prebuilt/releases/tag/v27.2.3-26908389

**Comment by deepak1556** [comment]
**Steps for Verification:**

* F1 > Help: List Audio Cues > you can hear all the audio cues being played
* Play video from release notes 
* Load the following html in simple browser `Simple Browser: Show` and ensure no audio is played. Video file can be downloaded from [here](https://docs.evostream.com/sample_content/table_of_contents). Choose mp4 format with AAC codec.

```
<html>
<meta http-equiv="content-security-policy" content="script-src 'self' 'unsafe-inline'" />
<body>
<video controls>
    <source src="bun33s.mp4" type="video/mp4"/>
</video>
</body>
</html>
```

**Comment by aiday-mar** [comment]
Hi, I am trying to verify this issue. I loaded the HTML pointing to the correct video and am using the command in order to display the HTML within VS Code. When I select the URI, I see a blank page where I suppose there should have been a video. When I click on the button to open the HTML within the browser I see the video. I was wondering if this is expected behavior, or if I am testing wrong?

https://github.com/microsoft/vscode/assets/61460952/795b901f-8550-419a-b5a7-d283a29af35a

**Comment by deepak1556** [comment]
Local resources are not allowed in the simple browser mode, serve the file over http and it should work.

```
> cd TestingFiles
> python3 -m http.server 3000

// In the simple browser, now point to http://localhost:3000/html/test3.html
```
