### ISSUE TITLE
Cannot scroll in terminal window created by api until resize

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/vscode#20505]
_From @hun1ahpu on February 12, 2017 10:22_

## Environment data
VS Code version:  1.9.1
Python Extension version:  0.5.8
Python Version:   3
OS and version: win 10

## Actual behavior
Mouse wheel scroll doesn't work
Scroll bar is not visible
After resizing the terminal window it starts working

## Steps to reproduce:  
-  Open any python file and execute any line of it

![pythonscrollbar](https://cloud.githubusercontent.com/assets/4397796/22861272/648d3436-f115-11e6-8cf6-4b54c628cf35.gif)

_Copied from original issue: DonJayamanne/pythonVSCode#739_

**Comment by daviwil** [comment]
Ahhh!  I'm seeing this too in the PowerShell extension.  I thought it was something I was doing wrong :)

**Comment by KillyMXI** [comment]
Vertical scroll doesn't appear initially in integrated shell, if I have GHCi (Haskell interactive shell) there, running on top of default shell (PowerShell).

**Comment by jsk01** [comment]
The scrollbar now seems to work correctly in the insiders build when using powershell.

**Comment by Tyriar** [comment]
@jsk01 this bug was a little flaky, I don't think any changes were made in this area.

**Comment by gandhis1** [comment]
Ironically enough, I used to not get this bug, but now I do on the latest official release. I get this behavior with a Python file that is executing in the terminal - I cannot use the mouse scroll button to scroll the terminal, nor is there a scroll bar that I can click on available. However, once I use the resize arrow or actually drag to resize, the scrolling begins to work. It's quite annoying

**Comment by stayfool** [comment]
This problem is ok in windows 10.

**Comment by KillyMXI** [comment]
Windows 10 Pro (v 1607), VS Code 1.12.2

Problem still exists.
The **first opened** terminal works as intended (with scroll). All the next terminal sessions will have no scroll until resized or VSCode restarted.

**Comment by shmutalov** [comment]
VSCode 1.13.1, Windows 10 x64

**Comment by chrmarti** [comment]
@Tyriar Can reproduce with Python's 'Run Selection' command on Windows. Logging `this.charMeasure.height` in `Viewport.refresh()` shows that charMeasure isn't initialized in time.

**Comment by Tyriar** [comment]
Sat together with @chrmarti yesterday to figure this thing out, the fix for this is coming in 1.15 :tada: 

It was an obscure bug that was happening when the terminal was created before the panel was shown. It was caused by https://github.com/Microsoft/vscode/commit/eb85ea83e04a1e308dc96fbf5da576ba0b68abcd to fix https://github.com/Microsoft/vscode/issues/22328. The reason is because since we were not setting the pty and xterm.js to the correct size before the terminal existed, xterm.js didn't bother doing a proper resize and the adjustments necessary (like re-measuring the character size) here https://github.com/sourcelair/xterm.js/blob/85c892c218c5529efd01569b7dc9b1123ae53582/src/xterm.js#L1942

**Comment by shmutalov** [comment]
@Tyriar good to hear that :cat:
