### ISSUE TITLE
VSCode icon on OS X is not transparent

### ISSUE THREAD

**Issue by andmos** [Microsoft/vscode#2051]
I notice that the VSCode icon on OS X is not transparent in the center between the lines. I guess this breaks with Apples design line guide for OS X? 
<img width="47" alt="vslogo" src="https://cloud.githubusercontent.com/assets/1283556/12366163/b4fefd4a-bbd9-11e5-9799-1098a4796d64.png">

**Comment by Sankra** [comment]
I have the same issue on my machine.

**Comment by egamma** [comment]
When the areas between the lines are transparent, then you cannot click in these areas, which is not desirable.

CC @weinand does this violate Apple's design guide lines?

@bgashler1 fyi.

**Comment by Sankra** [comment]
The HIG says this about icons on OS X: "Use transparency when it makes sense." 

On my Mac i can start apps by clicking on the transparent portion of their icons, even if it's in the center like yours.

Examples are the Monogame Content Pipeline app (uses the MonoGame icon) or Kaleidoscope:

![Portion of my dock](http://hjerpbakk.com/s/Screen-Shot-2016-01-17-at-095737.png)

**Comment by felixfbecker** [comment]
The icon is the same across all OS. I think this is designed intentionally like this.

![screenshot 4](https://cloud.githubusercontent.com/assets/10532611/12377357/637443ac-bd1b-11e5-80cc-fff7f70ad88d.png)

Visual Studio 2015 updated the icon with a white outline, which also included the inner white space. VS Code adapted it.

**Comment by andmos** [comment]
@Sankra I think it would make sense here. The icon looks kind of strange next to the other programs in my dock (like VMWare Fusion and MonoGame).

**Comment by bgashler1** [comment]
Thanks for your concern.  We originally designed the icon this way to match the Visual Studio family (and because transparency traditionally caused problems with clicking the icon--although it's not an issue anymore).

Since this icon doesn't violate Apple's icon design guidelines, and because the scope of this issue is related to Mac OS X (and our icon is shared across all platforms) this issue would be better discussed on [UserVoice](https://visualstudio.uservoice.com/forums/293070-visual-studio-code).  We would definitely want users of Linux and Windows to have their say before we changed anything.  Please feel free to lead a discussion, and we'll be monitoring the feedback.

**Comment by bobmajdakjr** [comment]
can't it be png based now? even the windows ico can be. then the insides could just be 99% transparent to retain clicking.

also I have never experienced any os making the transparent parts unclickable.

**Comment by bgashler1** [comment]
@bobmajdakjr Thanks for sharing this.  We are addressing this and other icon related issues in an upcoming release.

**Comment by Hammerstad** [comment]
In case someone still wants this icon with transparency: 

Browsing through issue #35783 I found someone has made this icon.

Link to repo containing the file: https://github.com/1l0/logo/tree/master/vscode
Direct link to file: https://raw.githubusercontent.com/1l0/logo/master/vscode/vscode.png

You can follow this SO link to change application icons on mac: https://superuser.com/questions/37811/how-can-i-change-an-application-icon-in-mac-os-x
