### ISSUE TITLE
Add "onDidChangeActiveDiagnostic" event

### ISSUE THREAD

**Issue by ivy-lmu** [microsoft/vscode#205209]
We have a custom editor with associated errors and warnings (diagnostics) in use. If such a diagnostic gets selected in the problems view, the correct custom editor is focused, but the affected element is not selected.

see problem illustration:
![problemsview](https://github.com/microsoft/vscode/assets/93579455/d8d3fd11-e9f7-493a-a468-460f0e874c87)

Some kind of `onDidChangeActiveDiagnostic: Event<Diagnostic>` would be great, so that a custom element selection procedure can be called at the time a user selects an item in the problem view.

**Comment by sandy081** [comment]
Clicking on the problem, opens the editor with selection range. So, I believe there is information passed to the editor to open the file and select the range.

**Comment by ivy-lmu** [comment]
> Clicking on the problem, opens the editor with selection range. So, I believe there is information passed to the editor to open the file and select the range.

I also think so. But I cannot confirm that the method `openCustomDocument(...)` of our `vscode.CustomEditorProvider` implementation a) is triggered and b) contains such range information when clicking on a marker. Or do you have another idea where it should be possible to intercept?

**Comment by MiklosMagyari** [comment]
I would also love to have an action for mouse selection as well.

I have checked the source, and I could not find any events/commands for this. The editor with the selected range is opened directly using editorService. Look for **this.editorService.openEditor()** in:

    vscode\src\vs\workbench\contrib\markers\browser\markersTreeViewer.ts
    vscode\src\vs\workbench\contrib\markers\browser\markersView.ts

By the way, a command is fired for selecting the marker with the **Enter** key because the Problems view supports **list.select**.
