### ISSUE TITLE
Hover: reduce impact of `setupCustomHover`

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#205341]
With https://github.com/microsoft/vscode/commit/e4e853fecf4e83033bade6bad9ea74c6f58dd1ef there is now a lot more calls to `setupCustomHover` going on, potentially N per list item (resource label, actions). That method does some heavy listener registration:

https://github.com/microsoft/vscode/blob/877caad9437ec2f26970b48e60e394a7a45b47e3/src/vs/base/browser/ui/iconLabel/iconLabelHover.ts#L195-L205

The list widget already has all these listeners in place, so maybe we could somehow delegate this down to reduce the amount of listeners that need to be created? If this is tough, some more ideas:
* maybe we can delay the creation of custom hovers for actions until the user hovers or otherwise makes them visible?
* do [passive event listeners](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#using_passive_listeners) help here reduce the impact?

**Comment by Tyriar** [comment]
`setupManagedHover` (previously `setupCustomHover`) is now deprecated:

https://github.com/microsoft/vscode/blob/a9dfdca4be93be2512a9d4577197c6530fd1d3e6/src/vs/base/browser/ui/hover/hover.ts#L115-L131

Instead we recommend using `setupDelayedHover` or `setupDelayedHoverAtMouse` which only listens to mouse over (and key down is the option is present):

https://github.com/microsoft/vscode/blob/a9dfdca4be93be2512a9d4577197c6530fd1d3e6/src/vs/editor/browser/services/hoverService/hoverService.ts#L144-L164

So I'm calling this fixed since we are slowly removing `setupManagedHover` usages during debt weeks.
