### ISSUE TITLE
Test language model access API

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#205568]
Refs: https://github.com/microsoft/vscode/issues/199908

- [ ] anyOS @mjbvz 
- [x] anyOS @ulugbekna

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23205568%0A%0A&assignees=jrieken)

---

We have added API that allows extensions to access/reuse language models. This allows them to implement arbitrary features with LM support. The proposal is the [vscode.proposed.languageModels.d.ts](https://github.com/microsoft/vscode/blob/683205493230f8d65208644527e0600e9ba19aee/src/vscode-dts/vscode.proposed.languageModels.d.ts), the entry point is `vscode.lm.requestLanguageModelAccess`

* Start by [creating an extension](https://code.visualstudio.com/api/get-started/your-first-extension) or fork an existing [extension sample](https://github.com/Microsoft/vscode-extension-samples)
 * Add the proposed API to the `package.json` (see below)
 * Then run `npx vscode-dts dev` to get the typings
```json
	"enabledApiProposals": [
		"languageModels"
	],
```

This TPI is about testing the API, make sure

* the API is well documented and names are logic
* the API works and allows you to implement a simple idea (add a command that says something about the selected line)
* the concept of LM access and access getting revoked again is explained and clear

**Comment by ulugbekna** [comment]
Implementing rename suggestions provider through LM access. Didn't have any problems, was able to be productive with the API fast. Cool work 💯  

![Image](https://github.com/microsoft/vscode/assets/16353531/301c5d6e-7c17-40ed-ba7e-0dec7fb4997c)

----

Couple of nits on API & docs: 

- as discussed, an extension dev could have more type safety when it comes to getting access (because it throws) and they need to check for `isRevoked` manually 

- documentation maybe could reference other symbols in the API that help with dev, e.g., `makeChatRequest` should use a model ID from `vscode.lm.languageModels`. Maybe mention that `vscode.lm.languageModels` is updated as extensions come in and one can use `onDidChangeLanguageModels` to subscribe to changes, etc.

- documentation could use tags `@throws` to indicate what errors are thrown (and that the operation may throw)  and `@remarks`

**Comment by mjbvz** [comment]
Nice work! Works nicely in my testing and pretty easy to get started with. Also submitted a PR with a few small suggestions to the types/docs: https://github.com/microsoft/vscode/pull/205819
