### ISSUE TITLE
`stream.progress` is different than our existing Progress API

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#205734]
Testing #205609

So, we already have our existing `withProgress` API:

```ts
window.withProgress(
    {
        location: { viewId: 'asdf'}
        title: 'Doing a thing'
    },
    async (progress) => {
        progress.report({ message: 'asdf', increment: 23 });
    }
);
```

I'm wondering why we aren't extending this instead of inventing a new thing. The location property could be extended by allowing it to take in the request or the response in the handler... and then you provide progress just as you would anywhere else in the UI.

Progress seems fairly different than true output so that would help keep them separate. The existing API would also allow for handling incremental progress.

**Comment by roblourens** [comment]
Originally we did use a normal Progress object that was passed into the handler. The problem is that there are many different types of things that you can return, and having many different interfaces to keep track of is a pain. For example, you can't really use intellisense to discover what types of content you can return as progress updates. So we decided to do it this way where you can type `progress.`, see what pops up, and use it in an easier way. I think we will keep adding new types of content too. I think this scenario justifies inventing something slightly new.
