### ISSUE TITLE
ctrl+clicking a link in the terminal caused weird state

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#205881]
I was testing https://github.com/microsoft/vscode/issues/184046 and I ctrl+clicked a relative file link in the terminal. The whole VS Code window went blank, then came back with the terminal looking like this:

![image](https://github.com/microsoft/vscode/assets/38270282/7115361f-3316-4262-8bc0-05486d719bcf)

Whole bunch of WebGL output in the console:

![image](https://github.com/microsoft/vscode/assets/38270282/c7a2b141-7bde-4012-885d-1fdd9dcd1979)

**Comment by alexr00** [comment]
All my terminals in that window are like this now:

![image](https://github.com/microsoft/vscode/assets/38270282/426fe8b0-6c6d-41de-950e-d17649ae581b)

**Comment by Tyriar** [comment]
Looks like you're hitting a context loss which typically happens when something unexpected happens with the GPU. We have an issue tracking the handling of it is not graceful here https://github.com/microsoft/vscode/issues/94513. To workaround the problem if you get in this rare situation you can try zooming in and out or switching gpuAcceleration to something and then back again.

/duplicate

**Comment by alexr00** [comment]
Zooming in and out did indeed resolve it.
