### ISSUE TITLE
1.84.2 version link not available

### ISSUE THREAD

**Issue by NieZhuZhu** [microsoft/vscode#205938]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. https://update.code.visualstudio.com/1.84.2/darwin-arm64/stable
2. 
![image](https://github.com/microsoft/vscode/assets/44939961/142d1d17-35bc-4b75-8192-9eba2303df9c)
![image](https://github.com/microsoft/vscode/assets/44939961/79cc82b9-34ed-4c24-8c12-44822d0fc5da)

**Comment by joaomoreno** [comment]
Oh, I know what the problem is! On it.

**Comment by joaomoreno** [comment]
Currently deploying to production, fix should be available in ~30 minutes. Could I ask you to comment in this issue if you can confirm the issue is fixed?

**Verification:** Be in China mainland and ensure that `https://update.code.visualstudio.com/1.84.2/darwin-arm64/stable` resolves to `https://vscode.download.prss.microsoft.com/...` instead of `https://vscode.cdn.azure.cn/...`.

**Comment by joaomoreno** [comment]
@NieZhuZhu Could you confirm this is working for you now?

**Comment by testforstephen** [comment]
Hi @joaomoreno, I confirmed that https://update.code.visualstudio.com/1.84.2/darwin-arm64/stable now resolves to https://vscode.download.prss.microsoft.com/... in China mainland.
