### ISSUE TITLE
Greater link navigation in the integrated terminal

### ISSUE THREAD

**Issue by IlIllII** [microsoft/vscode#205905]
Currently you can click on links in the terminal or use a hotkey to access the most recent file link, but it's helpful to be able to navigate through stacktraces with hotkeys. I've explored adding this functionality through an extension, but my understanding is that there is not an easy way to get terminal output to parse for links. My proposal is adding two new, unbound commands to the command palette: 

```
openNextLink
``` 
and 
```
openPreviousLink
```

## Demo

https://github.com/microsoft/vscode/assets/78166995/16f1c873-6861-4c8c-b589-211cfa27c15f

**Comment by meganrogge** [comment]
We have the `Open detected link` command which is helpful for doing this

**Comment by IlIllII** [comment]
Hmm that's good to know. I'll admit I am more familiar with emacs than vscode, so I might be missing something or just need to conform, but `Open detected link` isn't my favorite for a couple reasons:

1. It takes several keys to go up or down the stack trace.
2. It doesn't scroll the terminal so you can see trace's accompanying information.

I want to be able to quickly navigate through a stack trace with hotkeys, like `ctrl-alt-n` and `ctrl-alt-p` to move up and down the stack.

**Comment by Tyriar** [comment]
If we were to move forward on the PR it would require a bunch of extra work around accessibility and general UX (eg. highlighting the link as it's opened). I wonder if instead we could improve the exiting open detected link functionality instead. For example I would love it if a preview editor opened underneath the open detected link, it would also be fantastic if it would similarly highlight and scroll to (if needed) the currently selected link.

One of the biggest problems with the proposal is it would fix your problem, but it would add a bunch of code that is seldom used as it doesn't have a keybinding. And finding a keybinding that makes sense, is intuitive and is not taken is a tough order at this point.

> It takes several keys to go up or down the stack trace.

It would only ever be one additional keybinding though, so instead of ctrl+alt+n, ctrl+alt+n, ctrl+alt+n for example it would be ctrl/cmd+shift+o (default find symbol key), down, down which is arguably easier for the user.

---

I've gone ahead and created some issues to improve the behavior but we're open to other suggestions:

- https://github.com/microsoft/vscode/issues/206124
- https://github.com/microsoft/vscode/issues/206126
- https://github.com/microsoft/vscode/issues/206127

I'll close this as I don't think we will be implementing an open next/previous link command.

**Comment by IlIllII** [comment]
Yeah, I see what you're saying. I think the new issues are good. I checked out your PR for the preview editor and it works great! It would be nice to scroll or highlight the link in the terminal as you suggest (especially for large traces that are larger than terminal viewport), but even #206126 alone is very valuable. Nice job guys 👍

**Comment by Tyriar** [comment]
@IlIllII thanks for the suggestion, I'm also a big fan of the new preview 🙂
