### ISSUE TITLE
AutoComplete Will Add Extra Brace At The End Of The Line

### ISSUE THREAD

**Issue by Vikingama** [microsoft/vscode#205944]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.86.2
- OS Version: Windows_NT x64 10.0.22621

**Comment by Vikingama** [comment]
Does this issue occur when all extensions are disabled?: Yes

**Comment by Vikingama** [comment]
https://github.com/microsoft/vscode/issues/204222

**Comment by Vikingama** [comment]
https://github.com/microsoft/vscode/issues/204037

**Comment by Vikingama** [comment]
版本: 1.86.2 (user setup)
提交: 903b1e9d8990623e3d7da1df3d33db3e42d80eda
日期: 2024-02-13T19:40:56.878Z
Electron: 27.2.3
ElectronBuildId: 26908389
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.22621

**Comment by Vikingama** [comment]
版本: 1.86.2
提交: 903b1e9d8990623e3d7da1df3d33db3e42d80eda
日期: 2024-02-13T19:42:12.210Z
Electron: 27.2.3
ElectronBuildId: 26908389
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin arm64 23.3.0

**Comment by jrieken** [comment]
This issue lacks

* mentioning of the programming language and extension you are using
* a copy paste friendly sample

**Comment by Vikingama** [comment]
> This issue lacks
> 
> * mentioning of the programming language and extension you are using
> * a copy paste friendly sample

programming language: typescript@4.1.6
extension: have all extension disabled
sample: need some code?

**Comment by jrieken** [comment]
This issue lacks

* a copy paste friendly sample

**Comment by Vikingama** [comment]
> This issue lacks
> 
> * mentioning of the programming language and extension you are using
> * a copy paste friendly sample

emm, can you see the gif?
https://github.com/microsoft/vscode/issues/205944#issuecomment-1958915553

**Comment by jrieken** [comment]
The gif doesn't help me

**Comment by Vikingama** [comment]
emm, sample means [this](https://gist.github.com/Vikingama/2128b5fefa2c780c529b4f72a4e0ef2b)?

**Comment by jrieken** [comment]
It looks like the issue is caused by one of your installed extensions. All extensions execute together on a single nodejs process, so in order to narrow down the possible problematic extension, please try the following:
* run `F1 > Help: Start Extension Bisect`
* (this will restart VS Code with half of your extensions disabled)
* try to do the steps which reproduce the problem
* if the problem reproduces, click "This is bad" (this narrows down the problematic extension to the half which was enabled)
* if the problem does not reproduce, click "Good now" (this narrows down the problematic extension to the half which was disabled)
* these steps will repeat until the problematic extension is found

| initial | step | final |
|---|---|---|
| ![image](https://user-images.githubusercontent.com/5047891/101918658-e9170f80-3bc9-11eb-9977-857baa291937.png) | ![image](https://user-images.githubusercontent.com/5047891/101918683-ef0cf080-3bc9-11eb-9f9e-98b0177991b2.png) | ![image](https://user-images.githubusercontent.com/5047891/101918706-f502d180-3bc9-11eb-8c86-e56355958bd4.png) |

**Comment by Vikingama** [comment]
https://github.com/microsoft/vscode/issues/204222
https://github.com/microsoft/vscode/issues/204037
There are two closed issues, having same problem. Does it work?

**Comment by Vikingama** [comment]
![Microsoft Remote Desktop-2024-02-22-10 00 13](https://github.com/microsoft/vscode/assets/26019582/c23e7f95-1e93-4622-b329-de50cc6d3aec)

**Comment by Vikingama** [comment]
There is no this bug in 1.87.0-insider

**Comment by Vikingama** [comment]
> the same problem

this bug was fixed at two weeks ago, insider-released only.
