### ISSUE TITLE
Same file opened twice with different filename casing

### ISSUE THREAD

**Issue by markusjohnsson** [Microsoft/vscode#20594]
- VSCode Version: 1.9.0
- OS Version: OS X 10.11.6

Steps to Reproduce:

1. create file `a.ts` (note lower case)
```
import B from "B";
```

2. create file `b.ts` (note lower case)
```
export default class B {}
```

3. create file `tsconfig.json`
```
{
    "compilerOptions": {
        "module": "system"
    }
}
```

4. save all files
5. close all editors (cmd+w multiple times)
6. open `a.ts`
7. place cursor att the first `B`
8. hit F12
9. click on `b.ts` in explorer

Now `b.ts` is opened twice. Once as `b.ts`, once as `B.ts` and the two editors are independant with regards to save state.

![image](https://cloud.githubusercontent.com/assets/557685/22929313/4a357146-f2bb-11e6-9af0-2baca80f4d7a.png)

**Comment by pitAlex** [comment]
I'm experiencing a slightly different behavior related to files opening twice. I don't have an exact way on how to replicate it but with same system as mentioned above I often get the file I'm working on opened again in a new tab like in the following screenshot. It mostly happens when I press cmd+s.
<img width="466" alt="screen shot 2017-02-17 at 12 45 13 am" src="https://cloud.githubusercontent.com/assets/17630336/23044795/6ac1dc56-f4aa-11e6-9929-715fc22cf62d.png">

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/12448
