### ISSUE TITLE
Debug variable value double click seems broken

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#20604]
![image](https://cloud.githubusercontent.com/assets/22350/22938962/a030eea0-f2dd-11e6-8d1e-dd3565f2c987.png)

When I double click the exception's stack field, I get this:

![image](https://cloud.githubusercontent.com/assets/22350/22938985/aab40fc4-f2dd-11e6-86f5-c07db1c710dd.png)

**Comment by isidorn** [comment]
@bpasero it was hard for me to figure out why am I getting a [blur event](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/debugViewer.ts#L174) immediatly after I create an input box in the tree so I did a bisect to find the commit to blame f0e59a39ae7660185da32b42a000384c55f26d11
Are you doing some blur tricks because the tree is now registered in the list service?

![screen shot 2017-02-20 at 17 39 43](https://cloud.githubusercontent.com/assets/1926584/23134042/95c27c44-f793-11e6-86f1-35d6e6bb74c6.png)
