### ISSUE TITLE
Question: How to disable markdown preview sync

### ISSUE THREAD

**Issue by AndrewSav** [Microsoft/vscode#20614]
Given how markdown preview sync is currently horribly broken if markdown has tables or images in it, I'd like to know how to disable this feature. It's getting in the way, by scrolling to the wrong place, and thus constantly hiding the right place that I'm currently editing.

Could you please let me know, what is the setting I need to change to disable this altogether?

Thank you in advance!

**Comment by mjbvz** [comment]
* `"markdown.preview.scrollPreviewWithEditorSelection"`  - Enable/disable scrolling the preview view based on editor selection
* `"markdown.preview.scrollEditorWithPreview"` - Enable/disable scrolling the preview to move the editor


If you are seeing an issue, please open a bug with some example markdown so that we can investigate this
