### ISSUE TITLE
Android version

### ISSUE THREAD

**Issue by Aldijonas** [microsoft/vscode#206267]
I highly request the Visual Studio Code app for android. Vs code server is fine, but it can't work offline, and of course, you need a running server. I hope you will develop an Android version.
Best Regards

**Comment by catafest** [comment]
I think will be a good idea to use on tablets !

**Comment by IllusionMH** [comment]
FYI https://vscode.dev should be installable as PWA and has some offline capabilities.

**Comment by folarinmartins** [comment]
This is crucial for productivity on my 14.6" tablet

**Comment by Shriradhakrishnasharnam** [comment]
Respected Visual Studio Code Team,

I trust this message finds you in good spirits and well.

As an avid developer and a long-time user of Visual Studio Code, I am reaching out to request the release of a dedicated VS Code application for Android devices. With the rapid advancements in mobile technology, Android smartphones now come equipped with powerful RAM, high-performance processors, and even dual-screen or foldable designs. This has effectively minimized the gap between laptops and mobile devices, making it more feasible to carry out professional development tasks on the go.

Currently, there are mobile code editors like Spck Code Editor on the Play Store, which provide a commendable coding experience. However, as a developer who is deeply familiar with and reliant on Visual Studio Code, having a native Android version would enhance productivity significantly, especially when developing apps, extensions, and web applications while mobile.

I kindly request you to consider releasing a VS Code app for Android. This would benefit many developers who, like me, are increasingly leveraging mobile devices for development work due to their enhanced capabilities.

Thank you for your time and consideration. I look forward to your positive response.

Warm regards,
B R Shriradhakrishnasharnam
