### ISSUE TITLE
saving file shows `Error: Error: spawn EACCES`

### ISSUE THREAD

**Issue by thewhitetulip** [Microsoft/vscode#2065]
On every file save I see this error message. It is rather annoying.
I searched online but didn't find anything useful. Seems to be a node issue.

**Comment by bpasero** [comment]
@thewhitetulip maybe something off with permissions. are you sure the user you are opening code with has rights to write to the files in question?

**Comment by thewhitetulip** [comment]
Yes, the user I am running has full rights on the path where the files are stored.

**Comment by bpasero** [comment]
@thewhitetulip actually the error indicates an issue spawning a command, not writing to a file. Does it reproduce when you disable extensions by running "code --disableExtensions"? Can you attach the full error that is printed.

**Comment by thewhitetulip** [comment]
Hey, I ran it with `code --disableExtensions` then I am not seeing that error, but if I start with `./code` then I see the error again.
```$ ./Code 
Gtk-Message: Failed to load module "pantheon-filechooser-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell```
I don't see the spawn error printed on the commandline
`Error: Error: spawn EACCES`
![screenshot from 2016-01-19 23 04 43](https://cloud.githubusercontent.com/assets/6261877/12426702/0b82e350-bf01-11e5-96df-d420263c72a3.png)

**Comment by bpasero** [comment]
@thewhitetulip this indicates one of your extensions is causing this error, can you find out which one and please report it to the extension writer.

**Comment by thewhitetulip** [comment]
Okay, how do I understand which extension is causing the error, as I said there is no command line error message

**Comment by bpasero** [comment]
@thewhitetulip I think we need to do better error reporting in the future to help you. currently the only way forward is to manually remove extensions one by one until the issue is gone I fear.

**Comment by thewhitetulip** [comment]
:+1: Cool. At least some positive aspect for the editor :smile:

**Comment by thewhitetulip** [comment]
Hey I found a hack to make that annoying dialog box disappear
to the class `global-message-list` I add the following css property in the dev tools
`display: none;`

**Comment by agt313** [comment]
I had this error when I was trying to link to php program to the application.
While I was doing it I went and copy the path were the application resides... something happen and the VC turned off when I turned it back on (Before adding the application name to the path "php") I did not get the error message that php compiler could not be found but rather the "spawn EACCES" error.
I also noticed that php errors were not underlined.!!
When I went to check the php.validate.executablePath this was there...
```
// Points to the php executable.
    "php.validate.executablePath": "/opt/lampp/bin/" 
```
I added the "php" to the end ... restarted it .. the the Spawn Eacces error was gone.

Not sure why that error came up instead of the php validate error that should pop up.

**Comment by aircokol** [comment]
@agt313 thanks, it helped me too.

**Comment by wallmarkets** [comment]
@aircokol Andrey, hello. I can't follow - where I should add "php to the end"?

**Comment by wallmarkets** [comment]
@agt313 it seems to me I've got the same problem here. Also, it's like you've solved the problem by "adding php to the end", and I've tried to do so - can't understand where exactly I had to add "php" in settings files of my Visual Code. 

I've locally installed php71 via Homebrew. Also, I do have MAMP Pro installed on my Mac El Capitan. It's like they are "competing" with each other. When I saved .php files on my Visual Code IDE (v1.9.1), there was an error with PHP installed version of 5.5.6 instead of required above 7.0, so I'm just stuck here.

**Comment by aircokol** [comment]
@wallmarkets Hi. I fixed it like so (in MAMP case): 
`"php.validate.executablePath": "/Applications/MAMP/bin/php/php7.0.10/bin/php",`
Earlier I didn't have `php` at the end of the PHP executable path.

**Comment by BoraDev** [comment]
Awesome guys! Thanks for sharing the solution! I also solved it (mamp case) by inserting php at the end of php.validate.executablePath value, I was missing that php at the ned,same as aircokol. 
Thanks!

**Comment by SpacemanPete** [comment]
Thanks for this thread too! 

I first tried the command line option `code --disableExtensions` to run VSCode without extensions to rule those out as the cause very quickly as I still had that error appear. So I didn't need to go one-by-one through them all. 

The advice to check the  `php.validate.executablePath` setting was crucial for me as well. It was not present on my workspace settings so adding that resolved the nagging error.

If anyone else is using Acquia for Drupal Development, you can get the path to the php executables for your particular site through the Acqiua DevDesktop Preferences>Config>PHP panel, which shows the location of all the php.ini files for each version of PHP that your sites are using. Just remember to remove the '.ini file extension when you copy the path.

I'd recommend updating the `php.validate.executablePath` setting using the VSCode workspace.settings file instead of user.settings file so you can configure the correct PHP version for each site/workspace in case you have sites using older versions of PHP.
