### ISSUE TITLE
fucking piece of shit program im going to the board to domonstrate how slow and unreliable this program is . we pay to go to school and you have the nerve to frustrate students with this shit product. I should sue your fucking asses for the tuition cost of my class and book. infact i think i will request a refund in court. my fucking program wont grade and its due at 11. I believe i can sue you just for that . I will have this program removed from this schools curriculam i promise you that .fix my god damn program you fuckers

### ISSUE THREAD

**Issue by Madhattin22** [microsoft/vscode#206657]
ADD ISSUE DESCRIPTION HERE

Version: 1.85.2
Commit: 8b3775030ed1a69b13e4f4c628c612102e30a681
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 Edg/122.0.0.0
Embedder: codespaces

**Comment by coder0107git** [comment]
I'm sorry you feel that way. It runs very fast and beautifully on my potato pc (very underpowered chromebook). VSCode is a free, opensource, code editor (and so much more). The [license](https://github.com/microsoft/vscode?tab=MIT-1-ov-file) says:

> THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

which in effect means there is no warranty of any sort for VSCode. I'm sorry that you are unhappy about the price of your tutition and books which are both outside of VSCode/Microsoft's control. When you say your program "won't grade", what do you mean?
