### ISSUE TITLE
Investigate opening parent folder with `.vscode` when opening files from CLI or desktop

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#20671]
Related: #17640

**Comment by jrieken** [comment]
@chrmarti Can you provide some help to verify?

**Comment by bpasero** [comment]
@jrieken basically the idea is that when you open a single file in VS Code, we now walk up all folders until root is reached and if we find a .vscode folder we open this folder in the window instead of just opening the single file.

I suggest to use Windows to verify because on macOS there is a specific behaviour where in most cases we still only open the single file because macOS is more document oriented.
