### ISSUE TITLE
[feature request]rename symbol should be more intelligent

### ISSUE THREAD

**Issue by bruceauyeung** [Microsoft/vscode#20698]
i have a variable `test_name`, when my cursor is between `_` and `n`, if i press `F2`, the rename symbol window is popped up, here i expect :
1. i think the cursor in the popup window(rename symbol window) should also be exactly in the same place in the source editor window instead of the whole variable name being selected.
2. if i press `arrow left` / `arrow right` key, the cursor should move left / right one character instead of moving to the most left / right
3. if i press `home` / `end` key, the cursor should move to the most left / right

when the whole variable name is double clicked and selected(cursor is at the very end of the word), if i press `F2`, the rename symbol window is popped up, and  the whole variable name in the popup window(rename symbol window) is selected , here i expect:
1. if i press `arrow left` key the first time, the selection goes away and the cursor should move towards left one character instead of moving to the most left

**Comment by kumarharsh** [comment]
About the second part of your suggestion: 

> when the whole variable name is double clicked and selected(cursor is at the very end of the word), if i press F2, the rename symbol window is popped up, and the whole variable name in the popup window(rename symbol window) is selected , here i expect:
if i press arrow left key the first time, the selection goes away and the cursor should move towards left one character instead of moving to the most left

The current behaviour is consistent with every other place in vscode, and it'd be surprising to be different here, IMO.

**Comment by jrieken** [comment]
The input box comes up having the full text selected because we assume you want to change/overwrite it. Because the selection spans the whole word the arrow keys behave like that (which is correct)

If you select parts of the word, the selection will be carried over into the input box. I am unsure of carrying over the cursor position (which is like an empty selection) because I am afraid it will produce many false positives. It raises the following questions

* how often do you want to rename parts of an identifier vs the whole identifier
* how often are you exactly at the beginning/end of an identifier when you want to rename the whole identifier

**Comment by bruceauyeung** [comment]
> how often do you want to rename parts of an identifier vs the whole identifier

people can choose to rename parts of an identifier / the whole identifier by placing cursor on identifier  / selecting the whole identifier. and in my experience, renaming parts of an identifier is more often than the whole, usually i will rename an identifier because it has inaccurate meaning / does not conform name conventions / has word typos , most of time some words in an identifier can be reserved when renaming

**Comment by jrieken** [comment]
Acknowledged. This is the first time that this is reported and I am a little reluctant to change the behaviour immediately. I keep my eyes and hears open to see if more people have the same ask

**Comment by jrieken** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
