### ISSUE TITLE
Custom hover disappears before you can mouse over into it

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#206998]
1. Have a status bar contribution with an actionable tooltip, like Rust Analyzer's contribution in a repo with Rust code (like vscode) or Joh's PR pinger
2. Hover over the status bar entry and try to move your mouse to interact with it
3. It disappears 🐛 

![Image](https://github.com/microsoft/vscode/assets/2230985/d97d7088-900f-472a-ac6c-32dacea8fc28)

**Comment by bpasero** [comment]
This seems like a recent regression to me because for the window zoom status entry this used to work recently.

@benibenj can you see if its maybe something you changed?

**Comment by Tyriar** [comment]
Unless it's explicitly indicated as not hoverable any hover with markdown will allow it. I do notice `hideOnHover` is set to true in the new workbench hover delegate which is surprising to me, not sure why it wouldn't be using the default which is dynamically selected:

https://github.com/microsoft/vscode/blob/ead483888530303c5914f7078bcf0ed6ce17cf0d/src/vs/platform/hover/browser/hover.ts#L285-L292

@benibenj has been making a lot of hover changes recently.

**Comment by Tyriar** [comment]
@benibenj please cc me on workbench hover-related PRs so I can track changes going in. It's good you're taking some ownership but I just want to make sure I'm kept up to date 🙂

**Comment by alexandruavadanii** [comment]
So this is a bug. I noticed it a while ago and just got used to keeping `Alt` pressed (using Windows).

**Comment by Tyriar** [comment]
@alexandruavadanii some hovers intentionally cannot be moused over so I'm glad you discovered alt 👍

**Comment by benibenj** [comment]
Initially the new `WorkbenchHoverDelegate` was introduced to have a simple way to replace the native hover. Due to this it made sense to set `hideOnHover: true` to make sure the behaviour is similar to the native one. 
It afterwards turned out that using the `WorkbenchHoverDelegate` was a nice way to clean up some of the existing custom hover code such as the one in the status bar. 

It makes sense to switch back to the default behaviour for `hideOnHover`.
