### ISSUE TITLE
Debugger crashes and is not usable anymore

### ISSUE THREAD

**Issue by stoplion** [microsoft/vscode#207355]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:  Insiders and latest Code
- OS Version:  Mac 14.3.1 (23D60)

Steps to Reproduce:

1. Use the debugger, it crashes. Also tried to use VSCode with no extensions, same result. Debugger is unusable.

I use the debugger almost daily, and now it is unusable. 

The debugger consistently crashes and is completely unstable to use. 

Not sure why this happens, can we please fix this? THanks!

**Comment by stoplion** [comment]
<img width="517" alt="CleanShot 2024-03-11 at 13 22 55@2x" src="https://github.com/microsoft/vscode/assets/231343/edfaeb02-0885-4d6f-ab63-9b21efe42b54">

**Comment by roblourens** [comment]
Debugging js/ts?

**Comment by connor4312** [comment]
Possibly fixed in https://github.com/microsoft/vscode/issues/206630 which is available on the latest Insiders https://code.visualstudio.com/insiders/

If you still see crashes there, please share logs using these instructions https://github.com/microsoft/vscode/issues/207317#issuecomment-1989939639

Merging into #207317
