### ISSUE TITLE
Consider a different color for meta.preprocessor in Dark / Dark+

### ISSUE THREAD

**Issue by Gama11** [Microsoft/vscode#20743]
Currently, the Dark and Dark+ themes highlight the `meta.preprocessor` scope (`#if`, `#else`, `#end`...) like this:

![](http://i.imgur.com/pMgvWq6.png)

That's the same color that keywords use, which makes for bad readability.

That's why we currently employ a hack in the Haxe extension's grammar - we use the `punctuation.definition.tag` scope to get a nicely distuingishable, grey color for conditional compilation statements.

Compare this with the previous image:

![](http://i.imgur.com/zILClf0.png)

To me, this is significantly more readable.

Other language grammars that use `meta.preprocessor` include C# ([Example](http://i.imgur.com/OeuRRIy.png)). C++ [only uses `meta.preprocessor` for the actual define](http://i.imgur.com/6QuffnG.png), but not `#ifdef` and friends.

**Comment by aeschli** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.
If you disagree and feel that this issue is crucial: We're happy to listen and to reconsider.
Maybe you want to give it a try yourself and provide the feature through an extension or a PR: We're happy to give advise and get you started.
Thanks for your understanding. Thanks for helping and happy coding!
