### ISSUE TITLE
Unable to open notebook diff view from timeline (Leaking event listener)

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#207418]
https://github.com/microsoft/vscode/blob/be776fbfff16d18b19457cc271e4e049b766490d/src/vs/workbench/contrib/notebook/common/notebookEditorInput.ts#L55

**Comment by DonJayamanne** [comment]
Was already looking into this exact same issue today, and its part of iteration item (https://github.com/microsoft/vscode/issues/205634)

**Comment by DonJayamanne** [comment]
Steps to replicate the bug:
* Open a workspace folder
* Disable auto save
* Create an ipynb file
* Save this
* Verify you have an entry in timeline
* Add cells, save
* Wait for 1m, add more cells and save
* Wait for 1m, add more cells and save
* Wait for 1m, add more cells and save

In the time line entry, click each item, and the diff view should show up.
Previously (due to the bug), diff view will no show up and will display an empty view with an error message about not being able to load the editor model.

Verification - verify the diff view shows up
