### ISSUE TITLE
Should sticky scroll apply the `focused` class to the sticky scroll items?

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#207657]
I was surprised to see the sticky scroll element have the `focused` class:

`<div class="monaco-tree-sticky-row monaco-list-row focused" data-index="29" data-parity="odd" id="list_id_6_29" role="option" aria-label="tasks.json, tasks.json" aria-selected="false" aria-expanded="true" style="top: 0px; height: 24px; line-height: 24px;">`

caused by:
https://github.com/microsoft/vscode/blob/ca19ca605b3a2f4e2a87f4d787905861be6ffd19/src/vs/base/browser/ui/tree/abstractTree.ts#L1648

mostly because, well, it doesn't feel "focused" to me and because it _is_ focused, the Action bars get colored using `--vscode-quickInputList-focusIconForeground` instead of `--vscode-icon-foreground`.

To me the icons should probably just use `--vscode-icon-foreground`... although, I admit, I do want the icons to show up while it's sticky... I haven't thought long about how I would do that if we stopped marking these rows as "focused"

**Comment by benibenj** [comment]
Sticky Scroll supports being focused which is why an element can have `.focused`. However, we can improve it such that it is only set when sticky scroll actively has focus (compared to the list which has .focused set even when it doesn't have active focus). I've made an attempt to fix this and from my testing it seems to work well now, but there is a lot of complexity to list and sticky scroll focus so please let me know if you see anything weird regarding this.
