### ISSUE TITLE
Support escape on paste (semantic paste)

### ISSUE THREAD

**Issue by brandonJY** [Microsoft/vscode#20771]
Nice done for format on paste (#13945). Wondering if it is possible to add feature to escape characters on paste. 
E.g. If paste string `"foo" bar` into javascript `var str="[paste  here]";`
we would want the paste string to auto convert to something like `\"foo\" bar`

**Comment by gwicksted** [comment]
Please include TypeScript/ES6 template literal support (the backtick) where newlines are left as-is and special support for escaping `${}`.

**Comment by alexandrudima** [comment]
To keep the number of issues in our inbox at a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: we look at the number of votes the issue has received and the number of duplicate issues filed. Thank you for your time and understanding.

If you disagree and feel that this issue is crucial: we're happy to listen and to reconsider.

**Comment by gwicksted** [comment]
I have written an extension to address this issue.  Available on the [marketplace](https://marketplace.visualstudio.com/items?itemName=gwicksted.paste-escaped) or search within vscode via `ctrl`+`shift`+`x` type `Semantic Paste` -- it's currently the top result.

To paste with the semantic escaping turned on, use `ctrl`+`shift`+`v`.
