### ISSUE TITLE
Powerline glyphs no longer rendering correctly in integrated terminal

### ISSUE THREAD

**Issue by ssalbdivad** [microsoft/vscode#207836]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.88.0-insider
- OS Version: Windows 11 22631.3296 + WSL Ubuntu 22.04.4

Steps to Reproduce:

1. Open integrated terminal with powerline glyphs (I am using `CaskaydiaCove Nerd Font`)
2. Note glyphs are the incorrect width

This appears to be a result of https://github.com/microsoft/vscode/pull/207740

![Screenshot 2024-03-15 081649](https://github.com/microsoft/vscode/assets/10645823/dbbe7398-3b3c-474b-b04d-ae412b7495ca)

**Comment by Tyriar** [comment]
These glyphs are meant to not be scaled, not sure why they aren't working properly. This setting was switched to off by default in Insiders and probably be turned on for stable in a month.

**Comment by Tyriar** [comment]
I can't reproduce this. See below all the nerd fonts icons work fine and the Ⅻ character is scaled correctly according to the new feature:

<img width="222" alt="Screenshot 2024-03-29 at 8 38 29 AM" src="https://github.com/microsoft/vscode/assets/2193314/7d385ff2-cdef-4fc9-9659-ef044c47af6c">

I suspect you were on a slightly older version of Insiders before the fix was applied to include powerline and nerd fonts glyphs.

**Comment by ssalbdivad** [comment]
@Tyriar Yes this works fine now, thank you!

**Comment by Tyriar** [comment]
Phew 🙂
