### ISSUE TITLE
Matplotlib window behaves annoying with Stage Manager on MacOS

### ISSUE THREAD

**Issue by DDDOH** [microsoft/vscode#207937]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.87.2 (Universal)
Commit: 863d2581ecda6849923a2118d93a088b0745d9d6
Date: 2024-03-08T15:21:31.043Z (1 wk ago)
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin arm64 23.0.0

Steps to Reproduce:

1. Write a python script that will show a maptlotlib figure.
2. Debug the file.
3. The figure window will pop out, and the VS Code window is hidden. I can drag the VS Code window and the figure window together to view the figure and code at the same time. But if I restart debugging, I will have to drag the new figure window and VS Code window again. Is it possible to make it default that the popped out figure window stays together with VS Code window?

Please see the recorded screen directly.

https://github.com/microsoft/vscode/assets/25512742/eeb6b439-5d13-4d14-b1ab-73ab8172438f

I really like Stage Manager and VS Code is the biggest obstacle that stops me enabling Stage Manager all the time.

**Comment by DonJayamanne** [comment]
Unfortunately VS Code cannot control the external windows/applications displayed.
You can get around this by installing the Jupyter extension and running code in a notebook or Python file as follows

This is made possible with the ipympl python package.
More information here https://matplotlib.org/ipympl/
You can find more information about Widgets here https://jupyter.org/widgets
& Jupyter here https://jupyter.org/

Here's all you need
* Install the Jupyter extension 
* Write the following code in a python file & from the command Palette select the command `Jupyter: Run All Cells`
    * When prompted click ok to install `ipykernel` (this is the Python kernel required by Jupyter)
```python
#%%
!pip install ipympl

#%%
%matplotlib widget
import numpy as np
import matplotlib.pyplot as plt

x = np.linspace(0, 20, 200)
plt.plot(x, np.sin(x))
plt.legend(bbox_to_anchor =(1.1, 1.0))
plt.show()
```
 
Some times the widget might not load the first time, this is because everything was just installed,
You will need to close this window and re-run the second cell (i.e. you can now remove the code `pip isntall...`)

**Comment by DonJayamanne** [comment]
Here is a sample of this working in VS Code with Jupyter extension

![Recording 2024-03-27 at 16 20 44](https://github.com/microsoft/vscode/assets/1948812/8a4e4b3c-b69f-4b13-86e7-21c3206b65b8)
