### ISSUE TITLE
Hover sometimes shows nice colors and sometimes not

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#2081]
When I hover over functions I often see a nice hover similar to what the editor would show in terms of tokens and colors. But often I get no colors. What is the rule when a hover does show nice colors and when not?

@aeschli any ideas, is this your area?

To reproduce: open workbench.ts and hover over "registry" in line 200 and then over "Registry" later in that line. Only the first gets colors.

**Comment by aeschli** [comment]
I think @jrieken worked on the hovers

**Comment by jrieken** [comment]
We use the tokenisers for that

**Comment by aeschli** [comment]
@jrieken For the given example, the hover has content:
Workbench.registerEmitters(): void

That's not a valid TypeScipt syntax, that's why 'void' and 'registerEmitters' aren't colorized.
I don't think the tokenizer can be blamed for that. Looks like a the hover needs to use a different snippet such as `function registerEmitters(): void` or `class Workbench { registerEmitters(): void }`
Also note that the TypeScript grammar is somewhat context sensitive, so you can just feed it some tokens and hope for a consistenly colored content.

**Comment by jrieken** [comment]
I would totally blame the TypeScript grammar for this because it makes no sense to be context sensitive when tokenising. The 'fix' would be for TypeScript to not use this feature but have their source unhighlighted.

**Comment by jrieken** [comment]
@dbaeumer In the hover provider basically don't mark something as code but just return plain text

**Comment by dbaeumer** [comment]
Actually I like having color in the hover. In Feb I will try to make a request to TS to better support this.

**Comment by bpasero** [comment]
Thanks :+1:

**Comment by dbaeumer** [comment]
Was too busy this milestone. Moving to march.

**Comment by dbaeumer** [comment]
Guess what :-)

**Comment by mjbvz** [comment]
Please let me know if you are still seeing this for and js/ts code
