### ISSUE TITLE
Intellisense completely not working

### ISSUE THREAD

**Issue by trayana-hansen** [microsoft/vscode#208254]
Type: <b>Bug</b>

There is no intellisense suggestion whatsoever when using .

VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:20:17.278Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz (8 x 1190)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.67GB (1.42GB free)|
|Process Argv|--crash-reporter-id cfae85b9-a271-4d65-8e9e-b3a389f7994d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
codesnap|adp|1.3.4
npm-intellisense|chr|1.4.5
path-intellisense|chr|2.8.5
vscode-eslint|dba|2.4.4
gitlens|eam|14.9.0
vscode-html-css|ecm|2.0.9
vsc-material-theme|Equ|34.3.1
vsc-material-theme-icons|equ|3.5.0
auto-rename-tag|for|0.1.10
vscode-pull-request-github|Git|0.82.1
live-sass|gle|6.1.2
vscode-styled-components|mf|0.2.2
remote-ssh|ms-|0.109.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.86.0
vscode-remote-extensionpack|ms-|0.25.0
vscode-typescript-next|ms-|5.5.20240319
vsliveshare|ms-|1.0.5918
color-highlight|nau|2.8.0
indent-rainbow|ode|8.3.1
LiveServer|rit|5.7.9
vscode-styled-components|sty|1.7.8
snippets|tah|3.1.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vscode-icons|vsc|12.7.0
es7-react-js-snippets|woo|2.5.1
material-theme|zhu|3.17.0

(10 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
vscrpc:30673769
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:30992801
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
pydisww1:30991133
cppperfnew:30979542
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r6:30993542
dsvsc020:30976470
pythonait:30992953
gee8j676:30988843

```

</details>

**Comment by jrieken** [comment]
It looks like the issue is caused by one of your installed extensions. All extensions execute together on a single nodejs process, so in order to narrow down the possible problematic extension, please try the following:
* run `F1 > Help: Start Extension Bisect`
* (this will restart VS Code with half of your extensions disabled)
* try to do the steps which reproduce the problem
* if the problem reproduces, click "This is bad" (this narrows down the problematic extension to the half which was enabled)
* if the problem does not reproduce, click "Good now" (this narrows down the problematic extension to the half which was disabled)
* these steps will repeat until the problematic extension is found

| initial | step | final |
|---|---|---|
| ![image](https://user-images.githubusercontent.com/5047891/101918658-e9170f80-3bc9-11eb-9977-857baa291937.png) | ![image](https://user-images.githubusercontent.com/5047891/101918683-ef0cf080-3bc9-11eb-9f9e-98b0177991b2.png) | ![image](https://user-images.githubusercontent.com/5047891/101918706-f502d180-3bc9-11eb-8c86-e56355958bd4.png) |

**Comment by VilsonJrCorrea** [comment]
I did the extension bisect in my case was the extension Markdown All in One.

**Comment by jrieken** [comment]
ping @trayana-hansen

**Comment by jrieken** [comment]
@VilsonJrCorrea please file an issue against that extension

**Comment by trayana-hansen** [comment]
In my case it wasn't any extension causing it but completely uninstalling VScode and wiping out the stored information and installing it again worked perfectly
