### ISSUE TITLE
after removing mono-debug from VSCode help users to install from the marketplace

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#2083]
Since we will remove mode-debug from VSCode soon, we should help existing users to install mono-debug from the marketplace when they try to run a mono session.

**Comment by isidorn** [comment]
@jrieken FYI I know you are thinking about proposing extensions, just to make sure we propose mono-debug for mono projects

@weinand what exactly did you have in mind here - help existing users? When we show the mono is missing error that there is an action that takes them to the mono extension in marketplace? Or an action that would automatically install mono? Or something else?

**Comment by weinand** [comment]
@isidorn we should align with what @jrieken is doing for omnisharp.

**Comment by isidorn** [comment]
After the standup discussion today I think we came in agreement that once starting the mono session fails we show a nice error message with an action to install mono-debug.
Now what I am not sure is if we should always show this error, or when the user clicks dismiss to never show it again. For our use case I argue we should always show, because it only happens when there is an actual error (user is trying to debug mono) and it should always show when mono is not there and user explicitly wants to debug it.

**Comment by isidorn** [comment]
@weinand let me know once you publish the mono-debug to the extension gallery so I can start working on this. If you want I can also remove mono from our vscode and publish it to the gallery, anything works for me 😊

**Comment by jrieken** [comment]
@isidorn checkout this: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/extensions/electron-browser/extensionsAssistant.ts#L48

**Comment by isidorn** [comment]
@jrieken looks sexy, I'll try it out

**Comment by isidorn** [comment]
I am now doing same as Joh once a user tries to start a mono debug session.
Notice that currently nothing will be visible in the UI since the mono-debug extension is not yet in the gallery. I have user `andreweinand` as publisher and `mono-debug` as name, since I think we used those in other places, but we can change it.

**Comment by weinand** [comment]
@isidorn you could try to use mock-debug in the meantime.
