### ISSUE TITLE
Duplicate extension in search results

### ISSUE THREAD

**Issue by fzzr-** [Microsoft/vscode#20833]
- VSCode Version: Version 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519)
- OS Version: OS X 10.11.6 (15G1217)

Steps to Reproduce:

1. Search Marketplace Extensions for "`ext:xml`"
2. See duplicated "XML Tools" by DotJoshJohnson.xml

![vsc dub issue mov](https://cloud.githubusercontent.com/assets/888526/23084216/5467e626-f572-11e6-8227-b1a2d93b212a.gif)

**Comment by joaomoreno** [comment]
Good catch.

**Comment by joaomoreno** [comment]
A bit more narrow way to repro the issue: `ext:xml tools`

This happens because we run two queries in parallel:

- One for finding the specific extensions we recommend for that file extension: `{"filterType":7,"value":"DotJoshJohnson.xml"}`
- Another one for finding all extensions that are tagged with working with that file extension: `{"filterType":10,"value":"tag:\"__ext_xml\" tag:XML tag:\"XML\" tools"}`

Merging two paged queries is troublesome, especially when they contain duplicate items. Our current approach is easy: each `n-th` page of the result is the concatenation of the `n-th` page of both the first and second queries.

Ideally we should be able to query the Marketplace using an `OR` operator and have the Marketplace filter out the results:

```
{"filterType":7,"value":"DotJoshJohnson.xml"}
OR
{"filterType":10,"value":"tag:\"__ext_xml\" tag:XML tag:\"XML\" tools"}
```

cc @hamenon @modigrv

**Comment by modigrv** [comment]
Since these are two exclusive filter types, the results of both the filters cannot be combined on the server side. Search filter is compatible with additional filters which can further restrict the search result rather than add to the result.

The result of the first query will always result in 0 or 1 extension. 
So the VS Code client can remove any duplicate entry coming from the result of second query which will be paged. 
I.e. Add the results coming from the result of second query to your final display list if it is not already there.

**Comment by joaomoreno** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.

Thanks for your understanding. Happy coding!
