### ISSUE TITLE
Prepending using shell integration does not work for fish when using starship prompt

### ISSUE THREAD

**Issue by karrtikr** [microsoft/vscode#208465]
[starship](https://github.com/starship/starship) is a customized prompt. Same issue as https://github.com/microsoft/vscode/issues/205133#issuecomment-1981529690 but for fish.

Turns out https://github.com/microsoft/vscode/pull/206994 was just fixing it for zsh, we should make sure to apply these changes to all shell integration scripts using `VSCODE_SHELL_INTEGRATION`.

cc/ @Tyriar 

Originally reported in https://github.com/microsoft/vscode-python/issues/23110 https://github.com/microsoft/vscode-python/issues/22429

**Comment by Tyriar** [comment]
Turns out just shell integration does not work at all when using starship under fish currently.

**Comment by Tyriar** [comment]
Shell integration overwrites the prompt completely which replaces our hooks that apply the env changes. To get shell integration working in this case you need to install it manually and disable the setting inside VS Code:

```json
"terminal.integrated.shellIntegration.enabled": false
```

config.fish:

```fish
if status is-interactive
    starship init fish | source

    string match -q "$TERM_PROGRAM" "vscode"
        and . (code-insiders --locate-shell-integration-path fish)
end
```

<img width="214" alt="Screenshot 2024-04-15 at 2 24 11 PM" src="https://github.com/microsoft/vscode/assets/2193314/416f54ef-955f-4b3c-8930-6574110f92d7">

The only way to work around this AFAIK is to write files to `~/.config/fish/conf.d/` which is something we don't want to do as it's overstepping our bounds and messing with a user's machine. The `onDidChangeTerminalShellIntegration` event should never fire when this by default so it should not block `EnvironmentVariableCollection`-based activation. cc @anthonykim1

**Comment by Tyriar** [comment]
Actually we do use conf.d to inject, the problem is that we run before starship's conf.d entry since shellIntegration.fish < starship

**Comment by anthonykim1** [comment]
@Tyriar Thanks for the insight. 
Just to be clear, am I correct that ```onDidChangeTerminalShellIntegration``` event would NOT fire GIVEN user hasn't opted-in for manual shell integration & has not modified their config.fish when using starship prompt?

Would ```onDidChangeTerminalShellIntegration``` fire when user goes from not having shell integration manually installed to when they do have it installed?

**Comment by anthonykim1** [comment]
I'm not sure if I understand: ```Shell integration overwrites the prompt completely which replaces our hooks that apply the env changes. ``` correctly.

Shouldn't we still attempt to apply environment variable collections like in https://github.com/microsoft/vscode/pull/206994/files for other shells like fish to have EnvironmentVariableCollection-based activation even in case shell integration is disabled?

**Comment by Tyriar** [comment]
@anthonykim1 `onDidChangeTerminalShellIntegration` fires when we have "command detection":

https://github.com/microsoft/vscode/blob/5a68b6475a0fede326094469cb21c8ee9db5be9f/src/vs/workbench/api/browser/mainThreadTerminalShellIntegration.ts#L37-L44

This happens when we get any `633;` command sequence (not cwd):

https://github.com/microsoft/vscode/blob/5a68b6475a0fede326094469cb21c8ee9db5be9f/src/vs/platform/terminal/common/xterm/shellIntegrationAddon.ts#L334-L394

Or `133;` sequence:

https://github.com/microsoft/vscode/blob/5a68b6475a0fede326094469cb21c8ee9db5be9f/src/vs/platform/terminal/common/xterm/shellIntegrationAddon.ts#L334-L394

> Would onDidChangeTerminalShellIntegration fire when user goes from not having shell integration manually installed to when they do have it installed?

`onDidChangeTerminalShellIntegration` fires per terminal after it launches. It will fire when it's manually activated or when the automatic injection succeeds
