### ISSUE TITLE
Editor decoration doesn't show up when changing from multiple lines to one line at the same time

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#208511]
I set a 'placeholder' editor decoration here: https://github.com/microsoft/vscode/blob/7cfb8755f35b9d7bbdfa3e1fee3624e7c6d358e8/src/vs/workbench/contrib/chat/browser/contrib/chatInputEditorContrib.ts#L146

I noticed that when the chat input had multiple lines of text in it, then the placeholder doesn't show up. Here I show it not working, then working with a single line of text.

![Recording 2024-03-23 at 16 22 10](https://github.com/microsoft/vscode/assets/323878/fb5ed550-62a6-4edf-a5ec-1cb4fedcb843)

Maybe it's related somehow to the issue we had in https://github.com/microsoft/vscode/pull/203902? I can't debug this on my own, but it reproes 100% of the time for me, happy to help investigate.

**Comment by hediet** [comment]
```
setTimeout(() => {
  this.widget.inputEditor.setDecorationsByType(decorationDescription, placeholderDecorationType, decoration);
}, 0);
```
This fixes it, but it sucks.

@alexdima it looks like `setDecorationsByType` cannot be used when certain events are fired.
Looks like the view fires a scroll change event, which causes the event queue to flush, which causes a content change event, which calls the callback that sets the decoration...

**Comment by alexdima** [comment]
AFAIK nothing changed here in the editor recently, so @roblourens not sure if this is bad enough to add the workaround Henning found for this release on your side.

IMHO we need to add proper placeholder API to the editor instead of doing this from the outside with injected text. We now have something like 3 or 4 places implementing placeholder text via injected text, which doesn't make sense to me.

**Comment by hediet** [comment]
Created https://github.com/microsoft/vscode/issues/208976 for the placeholder API.
Feel free to close this one in favor of #208976
