### ISSUE TITLE
Language capabilities and URI schemas

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#20859]
# Language Capabilities and URI schemas

## Current situation

Documents in VS Code are currently classified using two dimensions:

- the language mode: It determines the programming language used. Examples are: TypeScript, JavaScript, HTML, ...
- the document source, expressed using the schema of the documents URIs. Examples are: file, inmemory, untitled, git, ...

The features set usually offered on a document depends on a combination of these two. For example a TypeScript file stored on disk (having the schema `file`) should offer the full TypeScript feature set like diagnostics, code complete, document symbols or find all references. In contrast a TypeScript file loaded from a git index (schema `gitindex` not 100% sure about the schema name) should not provide code complete since the file is read only. Even diagnostics are questionable since users can't fix them. However document symbols are useful to navigate in large files loaded from a git index.

Currently the feature set offered doesn't take the schema into account. The editor requests all features per language mode and then disables features if the document is read-only (this is why there is no code complete on files loaded from the git index).

However binding features to the read-only characteristic of a document can be conflicting: a prominent example are diagnostics. They are not very useful on files loaded from the git index, especially if errors are caused through inter file dependencies. However showing diagnostic for a read only file on disk does make sense since fixing the problem might be possible by changing another non read-only file.

## Ideas

To handle these cases correctly VS Code could offer a capability registry for URI schemas. The extension that brings a new URI schema into the system describe the language capabilities that usually make sense on that form of URI. However it is unclear how fine grain that registry should be. One approach would be to list all language capabilities currently available in the extension API. Drawback being that when we introduce new capabilities users need to either opt in or opt out. If we use opt in then at least extension don't need to be changed if a new capability is introduce. Alternatively we can describe capability sets. Something like:

- Diagnostics: it makes sense to compute diagnostics on the URI schema
- Manipulating: it makes sense to provide features that manipulate the document. For example code complete, rename, ...
- Structural: it makes sense to support feature that provide structural information about the document. For example document symbols
- Navigational: it makes sense to support features that help navigate documents. For example: goto declarartion
- Searching: it makes sense to support feature that search for symbols. For example: find all references

There is another dimension that is interesting. Language modes that are single file (like HTML) and language modes that are multi file (like TypeScript and C#) where inter file dependencies matter. Providing navigational and searching features on multi file language modes loaded from the git index for example might be confusing for users since most language server will only compute the result for that single file only. However navigating or searching for local symbols (like goto declaration of a local variable) do make sense.

If we introduce such a capability register do we need to enforce the correct behavior. We have the following possibilities:

- we enforce only the read-only ness of a document (this is what we do today)
- we enforce the capabilities as well. If for example an extension computes diagnostics for a URI schema that doesn't list the capability we drop the diagnostics.
- we treat the capabilities has a hint and extensions / language providers need to honor them.

## Proposal

I propose that we implement such a schema capability registry. Contributions to the registry can be done via code or the package.json file. The registry can be queried in the render and the extension host. A query passes in a schema or a URI and answers back the suggested capabilities. We should not enforce the honoring of the capabilities beside the read-only ness. It will unnecessarily hinder innovation. I would go with the above 5 capabilities. But reducing them to Diagnostics, Manipulating, 'Non-Manipulating' (may be someone has a better name) would address all use case I am are currently aware of.

**Comment by dbaeumer** [comment]
@vscode FYI

**Comment by aeschli** [comment]
From how I understand it, what we need is a way to configure (and limit) validation.

What's special about validation is that is not explicitly demanded by clients, but it's the language server that starts a validation after seeing that buffered documents have been opened or modified.

All other capabilities (code assist, hover...) are explicitly requested by a client, typically an editor. An editor that shows a read-only document will also not request any code completions or code actions.
So unless there's a bug, there will not be a code complete request to a gitindex:// resource. 

Still having a scheme registry on these demand-driven capabilities just limits future use cases.  Think of the virtual CSS documents for code completion in embedded CSS in HTML that we we had in the old Monaco or shorty in VSCode. Read-only documents but still the code completion proposals were requested as they were used programatically.

What's missing is an API where one can announce an interest in validation of a set of URIs patterns.
There's a built-in interest in validation to file://** and untitled://**. But maybe there's this client that also want's validation also on all resources myVirtualProject:// because he has something useful to do with these markers.
Based on this validation pattern, a language client can
- configure its server to not validate certain URIs
- do not send over buffered documents for certain URIs unless there's a a request for hover, code complete or such.

There's also the aspect of what can a language server do with a custom scheme URI such as gitindex://. 
In what context can he resolve it, how can he find referenced resource and libraries etc. For now and as default I'd say all custom-scheme URIs are only treated single-file. That gives limited capabilities, restricted to local declarations. Thats IMO good enough for a use case like gitindex://.

**Comment by alexandrudima** [comment]
IMHO this problem looks somewhat like a 3D table:

> Don't get too hang up on the actual values, the idea is that they all depend on:
> * uri scheme
> * language
> * rich language feature
> * (possibly also on the current open workspace)


| should have hover | C# | TS | CSS | JSON |
|---|---|---|---|---|
| `gitindex://` | false | false | true | true |
| `file://` | true | true | true | true |
| `untitled://` | true | true | true | true |

| should validate | C# | TS | CSS | JSON |
|---|---|---|---|---|
| `gitindex://` | false | false | false | false |
| `file://` | true | true | true | true |
| `untitled://` | true | true | true | true |

...

---

I think we're all agreeing the fact that `gitindex` is the URI for the left-hand-side file of a diff editor should not be knowledge belonging to a language server at all, since language servers should be editor agnostic (i.e. `tsserver` should not have special knowledge about `gitindex`).

IMHO the problem with cross-cutting tables is that they don't fit in anywhere :). But anyways here are the possible options:

#### a) Let the text document provider extension decide
@dbaeumer I think your proposal sits sort of under this option, although you propose simplifying the problem by grouping language features in "capabilities". That is quite nice, but it still cannot express e.g. that `gitindex` should have a different behavior for `TypeScript` vs. `CSS` vs. `C#`. 

#### b) Let the language extension decide
This sort of aligns with vscode API (i.e. `DocumentSelector`), but it is limiting if the css extension would only bind the hover feature to `file://` and `untitled://`. It would require a code change to the css extension to add another scheme. 

#### c) Let a third extension or the end user decide
This is an interesting under-explored option :).

---

Finally my two cents:

* Option c) looks pretty unlikely given that both text document providers and language feature providers are dynamic/imperative and not descriptive (in package.json).

 * Option a) seems better than Option b), but it will only really work for a handful of languages: json, css, html, single file languages. i.e. it will never work out of the box to register a random text document provider (e.g. I can register a `github://` text document provider that always fetches the files from a github repository, but I will never have `tsserver` or `Omnisharp` working without changing them).

 * There is no really good option...

**Comment by weinand** [comment]
@isidorn this proposal makes a lot of sense for our "debug://" scheme as well. Today we are lucky because some language features are disabled for read-only files.
With this proposal we would register the "debug://" scheme with the language features that make sense.

**Comment by aeschli** [comment]
Lots of discussions yesterday, here are my take outs:

- Core problem is the growing usage of TextDocument in the extension host. TextDocument are not only for to editors model but also by content providers as a vehicle to transport content . The new Git supports uses them extensively for diff markers. Our language extensions/linters eagerly synchronise these documents to language servers, resulting in unnecessary traffic, computation and validation. Likely extensions from the community also do the same.
We need to better define the role of TextDocument.
- Language clients should configure their servers with a selector of what documents are of interest to validate.
For VSCode the default will be only resources with scheme 'file' and 'untitled', but we should add a registry where contributors can add more schema.
- Language servers should only ask for synchronization on documents to be validated. They can still register supports on all resource of a given language id
-when asked to provide a result for a resource that is not synchronized, the server should request the content from the client

**Comment by dbaeumer** [comment]
I think this is still an issue. Sop keeping it open.

**Comment by dbaeumer** [comment]
I am closing the issue. If we start tackling this we can reopen.
