### ISSUE TITLE
`TerminalShellExecution#createDataStream`

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#208640]
Testing #208462

The `TerminalShellExecution#createDataStream` should be a plain property and not a method

**Comment by Tyriar** [comment]
I was thinking about this guideline when I switched it to a method as it's creating a new object every call:

> Note: Providing synchronous data comes with some additional engineering cost and will consume extra memory. However, it guarantees fast (zero-cost) data reading.

Can switch it back, is it worth a discussion in the API sync?

**Comment by jrieken** [comment]
https://github.com/microsoft/vscode/blob/b0d975fc6370f15570c380f41015b1ca2cdcb791/src/vs/workbench/api/common/extHostTerminalShellIntegration.ts#L243-L258

I don't think it does create a new object but that's also not the point here. Your data is never sync with an async iterable but the point is the consumer should just have `TerminalShellExecution#stream` which is still an async iterable (and likely implemented as lazy getter)

**Comment by Tyriar** [comment]
@jrieken I might be doing something wrong as I don't think I've used an async iterable before, but doesn't this need to return a separate iterable per call in order to support multiple extensions? Currently the `ShellExecutionDataStream` is a multiplexer for multiple iterators:

https://github.com/microsoft/vscode/blob/b0d975fc6370f15570c380f41015b1ca2cdcb791/src/vs/workbench/api/common/extHostTerminalShellIntegration.ts#L256

https://github.com/microsoft/vscode/blob/b0d975fc6370f15570c380f41015b1ca2cdcb791/src/vs/workbench/api/common/extHostTerminalShellIntegration.ts#L278-L285

**Comment by jrieken** [comment]
Maybe a better name for a method would be `read` or `readData`.
