### ISSUE TITLE
Workspace extension does not detect when an installed extension is built

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#208697]
Testing #208184

1. Check out the vscode branch `connor4312/selfhost-test-provider`
2. Install the extension. It initially doesn't activate because it's not built (its entrypoint is not found)
3. `yarn watch`
4. It's built but not activated unless I restart the extension host

Based on "Test that installing the workspace extension which is not built will not be activated until the extension is built" I would expect this to work

**Comment by sandy081** [comment]
It works for me. These are the steps I followed

- I cloned VS Code 
- Installed VS Code Selfhost Test Provider extension from recommendations
- Extension is not activated because of missing entry point file
- Build VS Code
- After building finished, I see extension is activated automatically.

Are there any steps I missing?

**Comment by connor4312** [comment]
Yea, this works for me now too. I'll reopen if I get better steps
