### ISSUE TITLE
Splitting a cell can show an empty markdown cell message

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#208673]
Testing #208546

Repro:

Create a markdown cell, click the split cell button

![image](https://github.com/microsoft/vscode/assets/2193314/784b3b34-e990-4955-abfd-b1e1c9d1c339)

I found it a little strange how an empty markdown cell can have 2 states:

![image](https://github.com/microsoft/vscode/assets/2193314/6da3f1b4-8c76-41d0-9d6c-82c9c326da18)

and this:

![image](https://github.com/microsoft/vscode/assets/2193314/29392a24-e3ca-4a4a-9b18-c59b1b961848)

I'm sure it was added for a reason, but it just seems like a weird inconsistency to me. Additionally, it says to press enter to edit but that's only true when it's focused so the advice is somewhat misleading imo. We also tend to not show keybindings or click instructions in our UI.

**Comment by Tyriar** [comment]
I don't think I can press enter without clicking?

**Comment by Yoyokrazy** [comment]
this fixes the split -> preview mode bug, however the two states for the md cell is intentional. Rather than show an empty void in the notebook if an empty cell is set to preview mode, an empty message is shown.

re: not being able to use enter to edit, that is likely because your focus wasn't in the cell container, which is also intentional
