### ISSUE TITLE
was executed "false" times

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#208721]
Testing #208463

The API allows for false instead of 0:
![Image](https://github.com/microsoft/vscode/assets/9205389/1b6f5cbf-7aed-42a2-8a5a-8ea8342ef78f)

**Comment by connor4312** [comment]
Fixed in https://github.com/microsoft/vscode/pull/208740

**Comment by connor4312** [comment]
1. Have something that uses the test coverage API (like the selfhost test provider)
2. Use boolean counts rather than numbers for execution (e.g. by setting `booelanCounts: true` in https://github.com/microsoft/vscode-selfhost-test-provider/blob/main/src/coverageProvider.ts#L7)
3. Verify the labels on things are correct
