### ISSUE TITLE
Inline Comment Incorrectly Applied in JSX Attribute Properties

### ISSUE THREAD

**Issue by ethanselzer** [Microsoft/vscode#20874]
- VSCode Version: 1.9.1
- OS Version: OSX 10.11.4

Steps to Reproduce:

1. Create a file with .js extension
2. Type a JSX tag with a spread attribute
```
<Foo {...{
  bar: 'baz'
}} />
```
3. Select the second line `bar: 'baz'`
4. Apply "Add Line Comment" command

Expected: A line comment is applied `// bar: 'baz'`
Actual: A JSX JavaScript expression is applied with block comment `{/* bar: 'baz' */}`.
Issue: The applied comment is not valid syntax in this context.

**Comment by mjbvz** [comment]
As noted in #23071, this was introduced by d826ad6e4fd52d9997fd144531c952af13218146

**Comment by didierfranc** [comment]
Is there a way to fix that ?

**Comment by OliverJAsh** [comment]
This behaviour occurs regardless of whether one is using spread or not:

``` jsx
import React from 'react';

const node = (
  <div
    id={1}
  >
    child
  </div>
);
```

Comment the `id` prop and you will get `{/*id={1}*/}`.

**Comment by ipelekhan** [comment]
Any update on this issue?

**Comment by mjbvz** [comment]
Here's the fix for the originally reported problem: 

![blocky](https://user-images.githubusercontent.com/12821956/30565883-c068f1e0-9c7e-11e7-8d8b-11058e5def9f.gif)


@OliverJAsh 761d23b should fixes line / block comments with the cursor within the `{}` but not when you have `id` selected. What would the expected behavior be in that case? Can you please try out the next insiders build and open new issue with any other edge case you notice around this

**Comment by OliverJAsh** [comment]
Thanks @mjbvz! Will give it ago.
