### ISSUE TITLE
no decorations when switching back to the branch with incoming changes

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#208701]
Testing #205540

I'm using branch `merogge/test`. I created and pushed this branch from local VS Code. On github.com, I made changes. I ran `git fetch`, saw the decorations. Switched branches using the status bar item. Swtiched back to `merogge/test` and saw no decorations, which was unexpected based on the below.

9. Click on the branch name in the status bar and switch back to the original branch
Confirm that the files have the correct decorations

![Image](https://github.com/microsoft/vscode/assets/29464607/8e319df5-de88-40da-90f9-1fe9dd1479ed)

**Comment by meganrogge** [comment]
It says my branch is up to date, so I guess this is expected. But I'm surprised it's up to date because I never pulled. I did run get fetch per the instructions, but then why did I see the incoming changes/ their decorations before switching branches 🤔 ?

![Image](https://github.com/microsoft/vscode/assets/29464607/138b95cd-d8e9-42b1-94fc-88b7289feb84)

**Comment by lszomoru** [comment]
The behaviour that you are seeing is due to the fact that the `microsoft/vscode` repo has a workspace setting, `git.pullBeforeCheckout`, set to `true`. This means that when you are switching branches we always pull the latest changes from that branch before we check out the branch. This fits our team's workflow really well as when we switch to `main` we always get the latest so that when you create a topic branch you are doing so using the latest of `main`.
