### ISSUE TITLE
Make inline chat work with chat participants

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#208898]
For inline chat we have adopted the generic chat widget. That works with the chat model and service which is driven by participants (aka agents). Today there is a bridge that connects both APIs but we should move inline chat onto participants as well. 

Doing this is a win for our upcoming extension story and will also clean up a lot of debt

**Comment by GavynWithLayer** [comment]
I see that this issue is marked as completed. Is there a way to have a `chatParticipant` use locations other than `panel` now?

From what I can tell in the `chatParticipantContributions.ts`, `locations` is not an allowable field for the contribution point. How does one add other locations for a participant?
