### ISSUE TITLE
Incurring significant energy on mac M3

### ISSUE THREAD

**Issue by shengwenyuan** [microsoft/vscode#208820]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.87.2  863d25
- OS Version: arm64

Steps to Reproduce:

1. Install C/C++ andPython extensions

**Comment by shengwenyuan** [comment]
I installed vscode on a new MacBook with M3 chip with two common extensions from Microsoft (for C/C++ and Python). I only scripted for simple Lua files or leave it in the background mostly, while during which my Mac was overheating. Vscode drains 50% battery in 1.5h.
Also, there was an abnormal process named ‘Chrome_crashpad_handler’. Cosidering the pretty simple scenario, this issue may be useful to locate the bug.

**Comment by jrieken** [comment]
It looks like the issue is caused by one of your installed extensions. All extensions execute together on a single nodejs process, so in order to narrow down the possible problematic extension, please try the following:
* run `F1 > Help: Start Extension Bisect`
* (this will restart VS Code with half of your extensions disabled)
* try to do the steps which reproduce the problem
* if the problem reproduces, click "This is bad" (this narrows down the problematic extension to the half which was enabled)
* if the problem does not reproduce, click "Good now" (this narrows down the problematic extension to the half which was disabled)
* these steps will repeat until the problematic extension is found

| initial | step | final |
|---|---|---|
| ![image](https://user-images.githubusercontent.com/5047891/101918658-e9170f80-3bc9-11eb-9977-857baa291937.png) | ![image](https://user-images.githubusercontent.com/5047891/101918683-ef0cf080-3bc9-11eb-9f9e-98b0177991b2.png) | ![image](https://user-images.githubusercontent.com/5047891/101918706-f502d180-3bc9-11eb-8c86-e56355958bd4.png) |

**Comment by shengwenyuan** [comment]
I have updated macOS and restarted. Vscode works well now. The battery keeps in normal during the bisect steps.
