### ISSUE TITLE
v1.87.2 CPU Usage 

### ISSUE THREAD

**Issue by totalhack** [microsoft/vscode#208902]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.87.2
Commit: 863d2581ecda6849923a2118d93a088b0745d9d6
Date: 2024-03-08T15:14:59.643Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Linux x64 6.5.0-1018-oem

Steps to Reproduce:

1. Open vscode.
2. Observe your CPU usage.

I just updated to 1.87.2 and this is new behavior. If I close vscode CPU usage drops to ~1-2%, with it open its hovering around 25% across all cores/threads. 

![image](https://github.com/microsoft/vscode/assets/43683140/c86db9c9-3718-4cb9-b8e5-06ab8b752ada)

**Comment by gjsjohnmurray** [comment]
Does the `Start Extension Bisect` command help you identify an extension causing this?

**Comment by totalhack** [comment]
It happens with all extensions disabled. I downgraded to 1.85.2 and the
issue goes away.

**Comment by msakrejda** [comment]
I'm also seeing similar behavior. Extension Bisect (what a cool feature! I did not know about it before) told me it was not an extension. Here's my Code info:

Version: 1.87.2
Commit: 863d2581ecda6849923a2118d93a088b0745d9d6
Date: 2024-03-08T15:14:59.643Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Linux x64 6.5.0-26-generic

(Notably, I'm also on Linux.)

For me, this happens when I engage completion features with Ctrl+Space. The CPU sits at ~100% for minutes and eventually comes down. Code is also using a terabyte (!) of virtual memory.

This seems to happen in my React code, but not in my Rails, Rust, or Go code.

**Comment by msakrejda** [comment]
Curiously, code-insiders also has the issue, but the interface remains usable (whereas code completion features hang on the release version when this happens).

Version: 1.88.0-insider
Commit: 9e0b3f311a68dce476b6209519d5b1506077bbcb
Date: 2024-03-27T21:46:06.351Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Linux x64 6.5.0-26-generic

**Comment by msakrejda** [comment]
I tried to add a performance trace as suggested [here](https://github.com/microsoft/vscode/wiki/Performance-Issues#visual-studio-code-is-sluggish), but I seem to be running into [this bug](https://github.com/electron/electron/issues/39818), which is only fixed in Electron 29.

**Comment by msakrejda** [comment]
I also tried downgrading to 1.85.2, as suggested above, and that also fixes the issue for me.

**Comment by msakrejda** [comment]
For what it's worth, I also started seeing the problem with 1.85.2. However, I rebooted my system and Code is now working fine. Idle CPU usage is minimal, and completions are responsive (once the system is initialized). I've upgraded back to 1.87.2, and things are still fine.

I think there's still something fishy here, since CPU usage was unreasonable and I don't think I did anything wrong to get into that state, but it's nice to know at least there's a workaround. If a reboot does not fix the original problem, maybe what I was seeing was only vaguely related. If that's the case, sorry for the noise; if the problem comes back, I might try to open a new issue.

**Comment by LcsGa** [comment]
I've got the exact same issue with that config :disappointed: 
```
Version: 1.89.0
Commit: b58957e67ee1e712cebf466b995adf4c5307b2bd
Date: 2024-05-01T02:08:25.066Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Linux x64 6.8.0-31-generic snap
```

**Comment by msakrejda** [comment]
I've had the problem come back pretty regularly, but I just upgraded to

Version: 1.89.0
Commit: b58957e67ee1e712cebf466b995adf4c5307b2bd
Date: 2024-05-01T02:08:25.066Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Linux x64 6.5.0-28-generic

and I have not had any issues yet.

**Comment by deepak1556** [comment]
If users are still experiencing this issue with latest stable, please share the perf profile following the steps at https://github.com/microsoft/vscode/wiki/Performance-Issues#visual-studio-code-is-sluggish. Also share the full command line of the process with increased cpu usage.
