### ISSUE TITLE
Can't open a folder with the simple file dialog

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#208937]
Steps to Reproduce:

1. set `"files.simpleDialog.enable": true`
2. press ctrl+k ctrl+o (workbench.action.files.openFolder) to open a folder
3. find a directory and press enter, press the ok
:bug: folder is not opened

![Recording 2024-03-27 at 10 42 36](https://github.com/microsoft/vscode/assets/2019016/62cae818-7a6b-4482-aae6-635cbfd7d659)

**Comment by amunger** [comment]
I'm on windows, does not repro in stable

**Comment by connor4312** [comment]
I poked into it to try to avoid a candidate if the fix was simple, but the logic is kind of tricky. With a change in the last Insiders we always end up here 

https://github.com/microsoft/vscode/blob/d948d379b210e25df76d7e08da7420a68fc7ab68/src/vs/workbench/services/dialogs/browser/simpleFileDialog.ts#L598

which makes us no-op the accept

https://github.com/microsoft/vscode/blob/d948d379b210e25df76d7e08da7420a68fc7ab68/src/vs/workbench/services/dialogs/browser/simpleFileDialog.ts#L523

**Comment by FannoFlow1** [comment]
I thought I was going crazy. Thank you for reporting this! Wild bug to encounter just trying to open a folder.

**Comment by amunger** [comment]
adding to march milestone to try to ensure it is looked into
