### ISSUE TITLE
Automate yum repository install

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#20895]
https://github.com/Microsoft/vscode/issues/229

We would like the yum repository to get installed automatically when you install the .rpm package, when I tried to do this however I ran into problems with `rpm` being locked in the `post` script of the .rpm package. [Chrome manages to do this somehow](https://cs.chromium.org/chromium/src/chrome/installer/linux/common/rpm.include?sq=package:chromium&type=cs&q=rpm.include&l=1).

**Comment by iavael** [comment]
> Chrome manages to do this somehow.

Chrome manages to do this very bad. It ignores user configuration and enforces its own.

**Comment by iavael** [comment]
If you want to make repo configuration easier to end user, create separate package (e.g. vscode-release) with it like rpmfusion does (https://pkgs.rpmfusion.org/cgit/nonfree/rpmfusion-nonfree-release.git/tree/ and https://pkgs.rpmfusion.org/cgit/free/rpmfusion-free-release.git/tree/)

**Comment by Tyriar** [comment]
@iavael thanks for the feedback. It's not clear to me what rpmfusion and microsoft-prod do?

Also what user configuration in particular does Chrome's route ignore?

**Comment by iavael** [comment]
@Tyriar 

> It's not clear to me what rpmfusion and microsoft-prod do?

These packages provide GPG public key for repo and repo-file itself. They update rarely (almost never), so that user's configuration in /etc/yum.repos.d is not violated on every update of software from these repos.

> Also what user configuration in particular does Chrome's route ignore?

It ignores if chrome repo is already described in another repo file (e.g. if user tries to have consistend naming of his/her repo files) and creates second entry with the same repo.
