### ISSUE TITLE
Always alert 'Typescript' is error

### ISSUE THREAD

**Issue by vladimirmian** [Microsoft/vscode#20906]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|

---

Steps to Reproduce:

1.install react snippet & close the window;
2.re-open the software & put a project floder in it & always tell me that

**Comment by mjbvz** [comment]
What does the error say? Can you provide a screenshot?

**Comment by mjbvz** [comment]
Closing as we need more info to investigate this. There two probable causes to Typescript service warning messages:

1. You are opening a mapped network drive. This is fixed in TypeScript 2.2 which is included in the current VSCode insiders and in VSCode 1.10
1. If you see a message about a missing `typescript/...` file, you may be seeing #20496 in which an antivirus program is deleting our TypeScript implementation. See [this comment](https://github.com/Microsoft/vscode/issues/20496#issuecomment-279518845) for workarounds

If neither seems to fit for what you are hitting, please let me know and we can reopen this to investigate further
