### ISSUE TITLE
Support dismissing sticky hover via escape regardless of focus

### ISSUE THREAD

**Issue by diminutivesloop** [microsoft/vscode#209129]
Currently if `editor.hover.sticky` is enabled it is possible to hide a hover panel by pressing escape. This is especially helpful if a panel is obscuring some other editor text you'd like to interact with. However this currently only works when the editor is focused even though the hover panels can appear w/o focus such as when a file has been opened via the explorer. It would be helpful if the escape shortcut worked globally and didn't require editor focus.

**Comment by aiday-mar** [comment]
Hi @diminutivesloop thank you for posting this idea. We currently do not have this implemented because we can not easily assume you would like to dismiss the hover on pressing Escape when the editor is not focused. Suppose the cursor is placed within the `Replace` box of the search widget. Clicking Escape here hides the replace box. It would be incorrect to assume the hover should be hidden in this context. What we can implement however is a new command called `Hide Hover` which you can then bind to some keybindings which will always hide a hover when there is one. 

In the meantime you can use the command `Show or Focus Hover` in order to focus the hover that is shown and then you can hide it, once it is focused, with the regular Escape character.

https://github.com/microsoft/vscode/assets/61460952/122cb904-c598-4b6d-bbe2-a5df465fba33

**Comment by diminutivesloop** [comment]
So I tried using the command you referenced but it didn't work. Instead it just showed a hover for the current cursor position in the editor but it didn't do anything for the hover shown under my mouse cursor. I do think the feature you proposed would be a good solution. Another option would be to disable sticky hover although that won't be very practical for me to do until https://github.com/microsoft/vscode/issues/151763 is implemented.

**Comment by aiday-mar** [comment]
I recently added a command `Hide Hover` for which you can assign keybindings. I will close this issue.

**Comment by diminutivesloop** [comment]
So I tried setting a keybinding for this:
```
  {
      "key": "shift+escape",
      "command": "editor.action.hideHover",
      "when": "!editorTextFocus && editorHoverVisible"
  }
```
However this didn't work and when I enabled keyboard shortcut troubleshooting it output a message that "no when clauses matched the context". If I remove `editorHoverVisible` then it works.

**Comment by aiday-mar** [comment]
Hi @diminutivesloop so you are saying the command works as such but the context key does not work? Could you open a new issue about this?

**Comment by nathaniel-palmer-simplisafe** [comment]
Opened an issue https://github.com/microsoft/vscode/issues/236745
