### ISSUE TITLE
search counter doesn't update

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#20920]
* search for something that has 1 hit
* open that file and change it so that it doesn't match anymore
* 🐛 the tree is now correctly empty, the counter not

![screen shot 2017-02-20 at 12 53 53](https://cloud.githubusercontent.com/assets/1794099/23124127/adca6ff4-f76b-11e6-97f6-715627d705af.png)

**Comment by wimspaargaren** [comment]
Hello, I'm new here, but I think I found what caused the bug. In the file src/vs/workbench/parts/search/browser/searchViewlet.ts the function updateSearchResultCount() should be adjusted, I think the if statement should be adjusted to if (fileCount >= 0). Since I saw there were already participants I thought I should let this know via a comment instead of a pull request.

**Comment by roblourens** [comment]
Not really, the check is there so I don't show an annoying "0 results in 0 files" while the search is running. I need to hide the label if the count goes from >0 to 0.
