### ISSUE TITLE
del

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode#209216]

**Comment by rebornix** [comment]
Thanks for your feedback. Regarding Find in Selection, I think we need to rethink how this should work in Monaco/VS Code, it stays so since the introduction of this feature.

**Comment by sinewave-2097** [comment]
I read some previous comments from devs regarding the find/replace dialog box, including one that said they didn't want to move it because "that's what other apps do". I get wanting to be different, but think of your users. Let's get something flexible and easy to use. I want to be able to increase the size of the dialog box and have it be a change that sticks. The icons are so tiny as to be almost completely unreadable on a modern monitor. Need an option to include text instead of tiny, tiny icons. BBEdit and jEdit (RIP) do it well. Everyone has different needs, so please give us the option of displaying find/replace outside of the included default.

**Comment by ermshiperete** [comment]
> 3. The replace window should open by default with CTRL + F. Why do I have to manually use my mouse and unfurl the downward arrow to re-enable this feature every time I go to execute the shortcut?

Replace is a different command (which happens to be accessible by pressing the down arrow in the find window, in addition to other ways to get there). You can press CTRL+H to get the replace window. This even works if the Find window is already open.
