### ISSUE TITLE
(settings) Multiple "workbench" categories

### ISSUE THREAD

**Issue by schmuli** [Microsoft/vscode#20923]
- VSCode Version: 1.10.0-insider 64801727521592cf5fe64fd911b1efe41b1ea732
- OS Version: Windows 10 Insider - Slow Ring

In settings, there are two different "workbench" categories, one capitalized and one lowercase.

**Comment by bpasero** [comment]
I see it, same for `editor.tabCompletion`:

![image](https://cloud.githubusercontent.com/assets/900690/23161625/2af9a0e8-f82b-11e6-9e5f-77b7e71c0cfa.png)

**Comment by jrieken** [comment]
@aeschli I register the tab completion property like this: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/snippets/electron-browser/tabCompletion.ts#L112

**Comment by sandy081** [comment]
It was expected to provide `title` while registering configurations even though `id` was being reused because there was no merging of nodes happening in Config registry. Merging was happening in the View (Settings editor) but based on title. 

Will fix it either in Config registry or in Settings editor.
