### ISSUE TITLE
setup environment using Visual studio

### ISSUE THREAD

**Issue by AminMhmdi** [Microsoft/vscode#20937]
- VSCode Version:
- OS Version:Windows 7 SP1 [Version 6.1.7601]

i clone VSCode using visual studio and Git extension but i dont know how to work with it in visual studio
how can i install  [Prerequisites ](https://github.com/Microsoft/vscode/wiki/How-to-Contribute#build-and-run-from-source)?? 
what i should do ??

**Comment by jrieken** [comment]
> what i should do ??

Outline at which step you fail, what error messages you see etc etc

**Comment by MartinSGill** [comment]
As I just setup a development environment myself, I'll chime in here, because I suspect you mean actual "Visual Studio 2013/2015".

If you're trying to contribute-to/build VSCode then instructions to build and run from source are here: https://github.com/Microsoft/vscode/wiki/How-to-Contribute#build-and-run-from-source

VSCode development happens in VSCode (or any editor really) and the instructions are for that. 

The only reason to have VS 2013/2015 installed (as far as I can tell) is for the C++ tool-chain to build dependencies, also why you need python 2.7.

Nothing stopping you using VS for development, but you'd still need to follow all the command line steps in the instructions. There are no project or solution files, nor will you be able to run the NPM from a VS extension (at least not easily) as VSCode requires a customised NPM.

**Comment by bpasero** [comment]
Thanks
