### ISSUE TITLE
Minimap: Implement dragging the minimap slider.

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#20935]
Perhaps also render it only on minimap hover (or have it as an option).

**Comment by nojvek** [comment]
I'm happy to help and work on a PR if you are able to offer me hints and some guidance on how to make this work. 

Great job getting minimap out. 

The big fat scrollbar is a great UX experience that I absolutely love about sublime.

**Comment by CoenraadS** [comment]
Would it also be possible to have it extend all the way to the bottom of the editor? Similar to visual studio:

![image](https://cloud.githubusercontent.com/assets/5593825/23131778/a0710082-f78b-11e6-87fa-7afb977e1d76.png)

**Comment by ristomatti** [comment]
If this is implemented I think it would make sense to allow disabling the current scrollbar.

Another related thing that comes to my mind would be a setting to be able hide the minimap if the window is narrower than a set character width. But I guess that should be a separate sub issue?

**Comment by martin-wiseweb** [comment]
@ristomatti As an option, maybe, but the scrollbar has more information than the minimap does - for example it shows you changes since last commit, etc.

**Comment by ristomatti** [comment]
@martin-wiseweb Yes exactly. On some occasions it's useful to have an overview of what is changed, but on some it's more useful to have the ability to quickly move around the files.

I too often find myself in a situation where I'd like to either have a browser window (reference/something I'm working on) or another code panel open side by side but cannot comfortably do so. This can be because the site does not wrap text and requires a wide view to show everything in a readable font size or if the codebase does not enforce limiting the columns to a decent width. This is where it becomes important to be able to configure the editor to only show the parts I need the most. Usually I work on a 27" screen so this is not an issue with the screen estate. 

I would also like to note that nothing prevents from including similar visual cues on the minimap that are currently found on the scrollbar. This could done with an overlay shading or simply a thin line on the side of the minimap.

**Comment by alexandrudima** [comment]
@ristomatti Let's explore painting more than just characters in the minimap in #20934. As a follow-up we can then explore if the overview ruler is redundant.

I intend to close this issue once dragging the slider is implemented.

**Comment by SoullessWaffle** [comment]
I noticed dragging the minimap slider does not seem to work if you start the drag by clicking outside the highlighted area, is this a bug?
