### ISSUE TITLE
Minimap: Add option to render blocks instead of characters

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#20947]
From @sprinkle131313 

Extracted from https://github.com/Microsoft/vscode/issues/4865#issuecomment-281124983

---

What about this comment? https://github.com/Microsoft/vscode/issues/4865#issuecomment-255368352

I'd prefer it over small unreadable text and it provides the information I need. I'm not sure how difficult it would be but by the sounds of it you could just create a new font where every character is just a solid square, minus whitespace.

---

Even when I really don't miss the minimap on @code, if I need to choose I can say I really like the minimap approach on Atom (plus, the code is OS). Is not a zoom-out version of the code, but a schematic representation. That is clever, because what you want is to quick identify sections of the code and not the code itself, and you can visually improve the key elements that make that possible, like color, line lenght, white space...

![2016-10-21_09h34_59](https://cloud.githubusercontent.com/assets/6965667/19598661/5e904ffc-9772-11e6-8cad-995e38677d3c.png)

**Comment by druellan** [comment]
Wow, thanks @alexandrudima for noticing my suggestion. I'm just testing minimap on a full HD notebook:

* Windows 10
* 1920x1080 resolution
* 125% desktop upscale
* VSCode "window.zoomLevel": 1.5,

This resolution is not enough to trigger the x2 font, so, the minimap looks kind of small, lacking contrast on the highlighted area, and even worse if you are hovering the cursor. Besides of that, the result is good.

![2017-02-23 06_04_22-handlebars js - wp-content - visual studio code - insiders](https://cloud.githubusercontent.com/assets/6965667/23253763/766e27c8-f994-11e6-8988-0fc5176a112a.png)

Now, I'm comparing that in Atom, using their 2x1 solid blocks approach. I'm switching to Ayu Dark, a high-contrast theme that has a pretty similar version for Atom.

Visual Studio Code, Ayu Theme 2x1 font
![2017-02-23 06_22_29-handlebars js - wp-content - visual studio code - insiders](https://cloud.githubusercontent.com/assets/6965667/23253790/876e4198-f994-11e6-8611-15118b1e7b3d.png)

Atom, Ayu Theme, 2x1 blocks
![2017-02-23 06_21_57-handlebars js c__users_psy_documents_davinci_htdocs_wp-content_plugins_pods_ui](https://cloud.githubusercontent.com/assets/6965667/23253806/92e13544-f994-11e6-9dc3-09353352b5bc.png)

The "blocks" approach improve the contrast there, maintaining the "shape" of the code, but not so much. Looks clean for sure, specially the large string area, but is not that I strongly prefer one version over the other.

Now, switching to a low-contrast theme:

Visual Studio Code, Solarized Dark, 2x1 font
![2017-02-23 06_34_10-handlebars js - wp-content - visual studio code - insiders](https://cloud.githubusercontent.com/assets/6965667/23253855/b4b5b7c6-f994-11e6-8558-e9528f465de6.png)

Atom, Solarized Dark, 2x1 blocks
![2017-02-23 06_33_47-handlebars js c__users_psy_documents_davinci_htdocs_wp-content_plugins_pods_ui](https://cloud.githubusercontent.com/assets/6965667/23253866/ba94247a-f994-11e6-8b19-9b503a59e1a9.png)

I really like the block approach on this one, I can easily edge-sight the code while working.

The blocks also allows you to fine-tune the shape. Testing a 4x2 block size:
![2017-02-23 06_48_06-handlebars js c__users_psy_documents_davinci_htdocs_wp-content_plugins_pods_ui](https://cloud.githubusercontent.com/assets/6965667/23253904/d8bae330-f994-11e6-8f3a-77c57e36ac02.png)

So, in the end looks convenient. I'm really curious to know if coders really like or want to have something that somehow resembles the shape of a font, instead of a more abstract representation. I'm also curious about speed improvements, since performance is going to be a factor on this feature.

Anyway, sorry about this long unsolicited feedback, I really wanted to explore this. Keep the good work guys and girls!

**Comment by octref** [comment]
Glad this made to Feb release. Blocks is much more eye-pleasing. Thanks @druellan and @alexandrudima !

**Comment by gamedevsam** [comment]
I just want to say, you guys rock!

**Comment by Xsmael** [comment]
how do i enable the blocks ??

**Comment by HazardDev** [comment]
@Xsmael If you haven't already found it: 

`"editor.minimap.renderCharacters": false`
