### ISSUE TITLE
Experience issue: when git actions require a password, the experience is not discoverable

### ISSUE THREAD

**Issue by lebaro-msft** [microsoft/vscode#209481]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:
1. Clone a repository housed in ADO, not GitHub. This gives you the option to Generate credentials: e.g. 
![image](https://github.com/microsoft/vscode/assets/99359352/b61e0f97-efe0-441b-804c-99aa993e2cb7)

2. Try to take a git action that requires auth. Observe that a small little window to enter password shows at the top. It is super not-discoverable and easy to miss, and I end up waiting for a while for something like _git pull_ to happen when its actually waiting for input from me.
![image](https://github.com/microsoft/vscode/assets/99359352/3ba045b5-57df-4f63-b679-eb1744598be2)

**Comment by lszomoru** [comment]
@lebaro-msft, thank you very much for filing this issue. I do agree that the current flow can be confusing but at the moment the quick input widget (the one that appears at the top of the window in the middle) is the UX element used for input across the workbench. 

Having said that, VS Code is the last in the git authentication pipeline and should only be used as a last-resort option. Since you are using Azure Repos, I would suggest to  install, and configure git credential manager (included in Git for Windows) as that would provide a much smoother experience.
