### ISSUE TITLE
Expand usage of standard token type inside of the auto indentation to ignore comments and strings for indentation

### ISSUE THREAD

**Issue by aiday-mar** [microsoft/vscode#209519]
We currently have some issues with indentation when strings and comments are involved. We should ignore the indentation rules when the cursor is inside of a comment or string. This would help resolve certain issues including but not limited to:

- https://github.com/microsoft/vscode/issues/209517
- https://github.com/microsoft/vscode/issues/209418
- https://github.com/microsoft/vscode/issues/208232

**Comment by RedCMD** [comment]
looking at this
I'm trying to set some decent indentation rules for YAML

I have this for a block-scalar with a explicit 9 indent indicator
pressing enter will indent 9 spaces
```jsonc
{
	// indent 9 spaces on block-scalar with indentation-indicator 
	"action": {
		"appendText": "         ",
		"indent": "none",
	},
	"afterText": "^(?![ \t]*#)",
	"beforeText": "(^[ \t]*|[-?:][ \t]+)(>|\\|)[+-]?9"
}
```

however, I don't want to indent if the text is already within a string (or comment)
atm the current VSCode feature set allows me to get decently restrictive, but not perfect

I have `<>` set as brackets
but I'm unable to do the same to `|`
`["|", ""]` doesn't work
```yaml
>

 >9

 |9
```
pressing enter after `>9` correctly yields one space indent
but pressing enter after `|9` incorrectly yields 9 spaces of indent

`"previousLineText"` can help slightly, but will still fail in that example

and to also throw a spanner in the works
block-scalar is a multiline string
however the indentation on each line is **not** of type string.
which I assume VSCode will detect it as a single line string instead of multi-line

it would be nice if I could define custom character sets to remove from strings rather than just relying on brackets
which would allow me to remove `: ` (yes colon and space combined, not separate) combinations from strings to help with `block-maps:`

**Comment by aiday-mar** [comment]
HI @RedCMD could you file a new issue about the comment? The original issue has been fixed since.
