### ISSUE TITLE
Peek definition works like Go to Definition if it runing from command palette

### ISSUE THREAD

**Issue by osenvosem** [Microsoft/vscode#20952]
- VSCode Version: 1.9.1
- OS Version: MacOS 10.12.3

Steps to Reproduce:

1. Place cursor on a simbol
2. Open command palette and choose Peek Definition
3. Repeat this several times.

Instead of showing a Peek Definition window, the editor opens a file with a definition. It happens in about 50% of cases.

**Comment by jrieken** [comment]
I can reproduce... It seems like the Enter from the command palette reaches the preview widget and then is interpreted as go to definition.

**Comment by jrieken** [comment]
The problem is that the F1 list seems to dispatch on key_down where the default tree controller dispatches on key_up. That means the key_down triggers peek definition and that the key_up of that same keypress selects the definition from the preview tree, therefore revealing it.

@joaomoreno @bpasero Why do the tree widgets behave so different? Why does the tree by default work on key_down except for Enter and Esc?

**Comment by jrieken** [comment]
*Easy* steps to reproduce

* open TypeScript file, select a symbol
* F1 > Peek Definition
* Press Enter, *do not* release key
* when the preview shows, release key
* 🐛 definition is revealed

**Comment by bpasero** [comment]
Good old https://github.com/Microsoft/vscode/issues/6146
