### ISSUE TITLE
VS Code crashed and won't open now. code: -1073741819

### ISSUE THREAD

**Issue by MythicPalette** [microsoft/vscode#209771]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

I have no idea. I was typing a line of CSS and it crashed. I tried to reopen it and now I have this:

![image](https://github.com/microsoft/vscode/assets/67084868/5bb10687-dcdd-4e7e-86b5-5c9b4b3a8534)

It opens three of them and all three crash with the same negative number code.

**Comment by Nezarn** [comment]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.90.2
- OS Version: Win10 22H2

Steps to Reproduce:

I have this issue too, I was working on some cpp file, my pc went to sleep because I was afk, after waking it up I got this:
![image](https://github.com/microsoft/vscode/assets/3817985/9c7d4769-9df4-47ca-98a7-02c143206e2f)
Pressing reopen showed same error, after quitting and restarting vscode I got 
![image](https://github.com/microsoft/vscode/assets/3817985/013e120f-d191-408a-a094-de0fdbad3e03)

Now its in this error loop, can't run vscode at all from any folder or with new window.

**Comment by xiezhipeng-git** [comment]
has the same error.
And more times open vscode.find it is update jupyter.and then this error disappear

**Comment by xiezhipeng-git** [comment]
There are also other similar errors.
![image](https://github.com/user-attachments/assets/c38486e3-4e6b-40ff-8249-355b849ce239)

**Comment by xiezhipeng-git** [comment]
The project has only a few files and only a few lines of code in each file.There is absolutely no reason to oom

**Comment by xiezhipeng-git** [comment]
This problem is coming up a lot now.It's the latest version of vscode. it can crash at any moment.Especially when opening a file at the beginning.Never crashed vscode once before (for years) @deepak1556
