### ISSUE TITLE
tslint module is missing?

### ISSUE THREAD

**Issue by BleyChen** [Microsoft/vscode#2098]
when i get latest code of vscode source and run the following command,it shows that UNMET PEER DEPENDENCY tslint@^3 || >=3.1.0-dev || >=3.2.0-dev || >=3.2.1-dev ,anyone can help me?
![mak](https://cloud.githubusercontent.com/assets/15098626/12413167/deefdc14-bec7-11e5-8425-6b8462cfca76.png)

**Comment by weinand** [comment]
@BleyChen Please run "npm install" from the scripts folder, e.g. `./scripts/npm install`

**Comment by billti** [comment]
I just hit this same issue.

This is due to NPMv3 not installing peer dependencies by default, which gulp-tslint uses to install tslint itself. See https://github.com/panuhorsmalahti/gulp-tslint/blob/master/package.json#L40 . Another example of this breaking a project is at https://github.com/yeoman/yeoman/issues/1488 .

If you take a direct dependency on tslint and typescript, then this seems to work with NPMv3 (tslint itself has typescript as a peer dependency also :confused: ).

**Comment by egamma** [comment]
@billti thanks for the background.

Adapted the package.json (04b451c914c16a60d0030ab990141fac9e23b2b2) and we will need to change `gulp-tsb` to use peerDependencies as well jrieken/gulp-tsb#25.
