### ISSUE TITLE
Extensions > install and enable vscode-smoketest-check extension smoke test sometimes fails

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#209870]
Example runs:
- https://dev.azure.com/monacotools/Monaco/_build/results?buildId=267204&view=results
- https://dev.azure.com/monacotools/Monaco/_build/results?buildId=267252&view=results
- https://dev.azure.com/monacotools/Monaco/_build/results?buildId=267507&view=results

Logs:
```
VSCode Smoke Tests (Electron)
       Extensions
         install and enable vscode-smoketest-check extension:
Error: Timeout: get element '.extension-editor .monaco-action-bar .action-item:not(.disabled) .extension-action.uninstall' after 20 seconds.
      at Code.poll (D:\a\_work\1\s\test\automation\out\code.js:204:23)
      at async Code.waitForElement (D:\a\_work\1\s\test\automation\out\code.js:163:16)
      at async Extensions.installExtension (D:\a\_work\1\s\test\automation\out\extensions.js:51:9)
      at async Context.<anonymous> (out\areas\extensions\extensions.test.js:15:13)
```

**Comment by sandy081** [comment]
Looked all failed instances and it is caused because of the network issues on the machine. Hence closing it as no fix.

**Comment by roblourens** [comment]
How did you determine that? Just wondering because I saw that in https://dev.azure.com/monacotools/Monaco/_build/results?buildId=277192&view=logs&j=260a512b-e5ca-5cf1-3f8e-20c0fa41efc9&t=ecad4960-5379-5108-563e-8a65e2414e29&s=a56e7651-4213-56af-9488-c25fe636c10c too but I can believe it's just network issues because we've had a lot of that in CI lately

**Comment by sandy081** [comment]
> How did you determine that?

From the logs mostly.
