### ISSUE TITLE
Allow extensions to change font for source code in editor

### ISSUE THREAD

**Issue by notduncansmith** [Microsoft/vscode#20997]
It would be really cool to be able to customize the display of my source code a little more generally than just colorization. The ability to apply CSS to editor elements would be fantastic, but individual preferences would be fine with me. As an example of what I mean, this would enable re-styling comments to be in a hand-written font, or have calls to certain functions be extra large. Hopefully this request makes sense, I think it could unlock some really powerful feedback mechanisms, but maybe I'm barking up the wrong tree. Would love to know either way. Thanks VSCode team!

**Comment by alexandrudima** [comment]
To keep the number of issues in our inbox at a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: we look at the number of votes the issue has received and the number of duplicate issues filed. Thank you for your time and understanding.

If you disagree and feel that this issue is crucial: we're happy to listen and to reconsider.
