### ISSUE TITLE
Test: API Modal messages

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#21004]
Test for #19717

- [x] Windows @michelkaporin 
- [x] macOS @weinand 
- [x] Linux @kieferrm 

Complexity: 2

Test the new modal message API. Example:

```typescript
window.showWarningMessage('hello world', { modal: true }, 'hello', 'world');
```

Make sure it works nicely with both strings and `MessageItem` instances, which use the `isCloseAffordance` property.

**Comment by michelkaporin** [comment]
For testers information:

To be able to fetch the latest vscode.d.ts you should switch engine configuration to `*`:
1. Set `"vscode": "*"` so that the latest API can be fetched. 
2. Then do `npm i`, it will fetch the latest d.ts. 
3. Once done, bring it back to the previous version (e.g. `"vscode": "^1.5.0"`), so that you will be able to run extension with new API.

**Comment by weinand** [comment]
I do not really understand the 'isCloseAffordance' property in the modal case (on macOS):

- If I set both to false, they still close the alert but a 'Cancel' button shows up (as the default button).
- If I set any one or all to true, the alert has no 'Cancel' button but the buttons behave identically (and the left button is always the default).

```js
        vscode.window.showWarningMessage<vscode.MessageItem>('hello world', { modal: true },
            { title: 'hello', isCloseAffordance: false },
            { title: 'world', isCloseAffordance: false }
        );
```
