### ISSUE TITLE
page flickers when debug java 

### ISSUE THREAD

**Issue by Meaningisuse** [microsoft/vscode#210207]
https://github.com/microsoft/vscode/assets/15310195/f1fcdc40-8809-491a-bae6-0253bb5d95bd

- VS Code Version: 1.88.1
- OS Version: MacBook M1  14.4.1

**Comment by hugoqnc** [comment]
I have the same issue, with the exact same version of VSCode/macOS, on a M1 Mac.
Some additional context:
- It only happens when "Word Wrap" (option + Z) is enabled, and when the file window is too small to show a code line and its debugging annotations (the text highlighted in yellow) on a single line.
- The bug also happens on VSCode Insiders version 1.89.0.
- It is a quite recent bug that I have only since one or two weeks.

**Comment by aaguirre-te** [comment]
I am also experiencing this with:
- VS Code Version: 1.88.1
- OS Version: Windows 11 Pro 23H2

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/210733
