### ISSUE TITLE
Notebook: status bar is not floating window aware

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#210383]
This is a missing adoption when notebooks became floating window capable. Notice how the status bar entry appears in the main window and not the floating window:

![Screenshot 2024-04-15 at 11 56 20](https://github.com/microsoft/vscode/assets/900690/5e9a6df0-acad-4359-880e-1152c1c497a3)

We have had a similar issue with the text editor status bar and solved it by instantiating it per-window:

https://github.com/microsoft/vscode/blob/b41db6119374a19f030f194ac859733a95eb7009/src/vs/workbench/browser/parts/editor/editorStatus.ts#L895-L904

I think a similar approach would work for notebooks too. 

The key for this to work is that you get a scoped `IEditorService` in the `onDidCreateAuxiliaryEditorPart` that allows you to listen only to editor change events in the respective window. Consequently, you use a main-window scoped editor service for the main-window status bar:

https://github.com/microsoft/vscode/blob/b41db6119374a19f030f194ac859733a95eb7009/src/vs/workbench/browser/parts/editor/editorStatus.ts#L897

Let me know if you have questions, but I think its easy to copy what we do for editor status here.

**Comment by bpasero** [comment]
When I reload the window with a floating notebook, the status bar does not appear (macOS):

![image](https://github.com/user-attachments/assets/cb804cde-9435-4d52-a6ee-52289521972c)

**Comment by rebornix** [comment]
This is my attempt to fix this issue https://github.com/microsoft/vscode/pull/224222.

The problem here is if we register the contrib `afterRestore`, we won't get the `onDidCreateAuxiliaryEditorPart` event. The event is the only place where we get the window's unique instantiationService (which gives us the right statusbarservice). Without the right statusbarservice, we can't register notebook status bar items to the right place.

**Comment by bpasero** [comment]
Not very happy about that, filed https://github.com/microsoft/vscode/issues/224256
