### ISSUE TITLE
在过去5分钟，TypeScript语言中断服务5次

### ISSUE THREAD

**Issue by Simmon12** [Microsoft/vscode#21039]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|stylus|buzinas|0.1.0|
|vscode-eslint|dbaeumer|1.2.2|
|vscode-wakatime|WakaTime|1.0.6|

---

Steps to Reproduce:

1.
2.

**Comment by rebornix** [comment]
He is saying TypeScript service stops working five times in last 5 minutes.

**Comment by mjbvz** [comment]
@Simmon12 Two questions:

* Are you opening a project on a network drive?
* Do you see a message about a missing `typescript/...` file?

**Comment by mjbvz** [comment]
Closing as we need more info here. There are two probable causes:

1. You are opening a mapped network drive. This is fixed in TypeSscript 2.2 which is included in VSCode insiders (VSCode 1.10)
1. If you see a message about a missing `typescript/...` file, you may be seeing #20496 in which an antivirus program is deleting our TypeScript implementation. See [this comment](https://github.com/Microsoft/vscode/issues/20496#issuecomment-279518845) for workarounds

If neither seems to fit for what you are hitting, please let me know and we can reopening this to investigate further
