### ISSUE TITLE
TS & Extensions: warning about version mismatch between our TS version and extensions

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#21055]
Steps to Reproduce:

1. use insiders on a fresh hello world extension
2. open it and see

![image](https://cloud.githubusercontent.com/assets/900690/23203164/abb9e8c6-f8e1-11e6-8486-7c6e32942b82.png)

We should either update your generator-code to use the same TS version or make sure we wait until TS 2.2 official is released and then announce stable. Otherwise every extension author will get this cryptic message.

**Comment by bpasero** [comment]
Sorry I got things confused, this is independent from the TS extension but it seems users will have to globally install the exact same TS version we bundle but 2.2.1 is not yet released. It think we should avoid to ship with a nightly TS, otherwise it makes it hard for our users to resolve this issue.

**Comment by mjbvz** [comment]
@bpasero We ship insiders TS builds (essentially release candidates) in the VSCode insiders channel in order to catch bugs in the next version of TypeScript and to be able to adopt it more quickly. TS 2.2 final is being released today, but the delta between 2.2.1-insiders and 2.2 should be small and we've already had lots of real world testing on the 2.2.1-insiders bits. Shipping insiders allows us to pick up TS 2.2 final with more confidence in VSCode 1.10

Can you explain the bug a bit more. Showing a tsc mismatch warning is the expected behavior currently

**Comment by bpasero** [comment]
I think its all good now that we adopted the final 2.2.1 version. My point was just that we should not ship a stable release with a nightly TS version.
