### ISSUE TITLE
test: comments accessible view

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#210598]
Refs #203928

- [x] Windows @ntrogh 
- [x] macOS @bhavyaus  
- [x] anyOS @ulugbekna

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23210598%0A%0A&assignees=meganrogge)

---

There is now an accessible view for GHPR comments. Enable `Screen Reader Optimized` mode to test this. 

Checkout a PR, open the comments view, and use `alt+f2` to review the comment in detail. 

Also try:
- taking the actions that are available in the toolbar
- using `Escape`, which should focus the comment item in the view
- having several replies to the comment, verify these are rendered in the accessible view

**Comment by DonJayamanne** [comment]
> Checkout a PR, open the comments view, and use alt+f2 to review the comment in detail.

@meganrogge 
Please can you share a screen recording.
I'm on a mac, & struggling to understand the instructions here.
Perhaps because I'm not very familiar with voice over and accessibility features.

Would it be possible to share a screen recording of this, so I understand this better and can test this.
Thanks
