### ISSUE TITLE
settings.json don't remind position

### ISSUE THREAD

**Issue by ManishJain-JKV** [Microsoft/vscode#21052]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|

---

Steps to Reproduce:

1.Open **Visual Studio Code**.
2.On **Welcome page**->**Configure settings**->**settings.json**
3.In left side editor pane expand **Editor** click on any line on opended collapsible panel
4.Go to **Welcome page** and come back to **settings.json**
5.**settings.json** editor lost when you last clicked

**Comment by roblourens** [comment]
Not specific to the welcome page - open the settings page by any means, then ctrl+tab to another editor, then ctrl+tab back, and it loses your place.

**Comment by sandy081** [comment]
Default settings is not a real editor but like a web preview and hence the view state is not preserved. But same is a bug in Editable settings (RHS), filed a separate bug for that - https://github.com/Microsoft/vscode/issues/22141

This will be handled separately since it is more a feature to me as we never supported it.

**Comment by sandy081** [comment]
As mentioned in my previous comment, Default settings editor not a normal text editor, so reminding the cursor position does not makes sense.

Closing this as I do not have plans in implementing this in next 12 months.
