### ISSUE TITLE
Exception widget: handle content overflow better

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#21087]
Testing: https://github.com/Microsoft/vscode/issues/20812

![image](https://cloud.githubusercontent.com/assets/900690/23207592/19d686ce-f8f2-11e6-81e8-e99c1dbe0f28.png)

Maybe allow to resize the viewzone?

/cc @isidorn

**Comment by isidorn** [comment]
I think the exception widget should have a dynamic height based on the content if possible. 
Some height calcualtions will be needed for this - peek widget currently claculates this height based on font size and such, but since we used a fix font we will only have to calucluate it based on the text length
