### ISSUE TITLE
Verbose Hover: Keybindings don't always work

### ISSUE THREAD

**Issue by benibenj** [microsoft/vscode#211067]
Testing #210904

The `ctrl+k | ctrl+p` keybinding does not work on windows due to quick open. Also the `ctrl+k | ctrl+m` keybinding collides with the `Maximize Editor Group` command. I wonder if this could be solved without registering keybindings. One idea could be that when the hover is focused the user could just use `+` and `-` on the keyboard to increase and decrease the hover (possibly also arrow keys could work). 
Make sure to mention in the hover of the increase and decrease actions what the keybinding or keyboard key is.

**Comment by aiday-mar** [comment]
That's a very good point. I think we would still want ideally the + and - to be linked to keybindings so they can be configured by the user. I'll remove the keybindings, so they can simply be set by the users if they so wish.

The current code already renders the keybindings if they are set (https://github.com/microsoft/vscode/blob/a49c81edea6647684eee87d204e50feed9c455f6/src/vs/editor/contrib/hover/browser/markdownHoverParticipant.ts#L321). Perhaps they are not fetched correctly in your case because of the keybinding collisions. 

![Screenshot 2024-04-23 at 14 59 06](https://github.com/microsoft/vscode/assets/61460952/1cbaed90-1175-449e-9819-6be3c77a4974)
