### ISSUE TITLE
Window activity API - batch events when going back to a window

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#211055]
Testing #210978

When switching back to an inactive window (which is a very common scenario) I see that the event fires twice:
- `{focused: true, active: false}`
- `{focused: true, active: true}`

I think it would be nice if these two events would be batched so that only event fires:
- `{focused: true, active: true}`

**Comment by connor4312** [comment]
There's not a super nice way to do this, because focus is separate from user activity. In theory a user could alt-tab to the window and never interact with it, which would make it gain focus but not track any user activity. We could debounce the event and emit the last state, but there's not a specific duration to use...

While both are copies of the window state, I suspect that any given extension only cares about one of the properties -- or at least that they are not often used in tandem.

Unless you feel some conviction I would tend to leave this as-is due to the complexity/benefit tradeoff

**Comment by lszomoru** [comment]
Thanks for the additional context. I am fine with closing this issue.
