### ISSUE TITLE
"Create Issue" not working- possibly due to SAML

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#211128]
Testing #210874

![image](https://github.com/microsoft/vscode/assets/31675041/54712c8e-412f-44ad-bee7-ba92f1c59dd0)

I clicked "create issue" on this configuration and nothing happened. This is possibly because I haven't authenticated SSO on this device. So clicking on any of the issue links, for example, takes me here.
![image](https://github.com/microsoft/vscode/assets/31675041/900b5495-c38e-4c84-8e2e-d5a50eef2288)

I might need to jump through some hoops to get SSO working on this device to verify my hypothesis 🤔

**Comment by justschen** [comment]
@andreamah that's interesting. in my testing, when I'm not logged in on sso (after like 24 hours or something), it creates the issue no problem, opening in new web page and I hit continue and the issue is created.

it should be tied to the GH token, so as long as you're logged in, it would authenticate and open that url. did it work after logging in on SSO already in your default web browser? can also test by trying in a different browser (try changing the default web browser)

**Comment by andreamah** [comment]
I'm having troubles passing SSO on this device. I can try to look into it, but as I am right now, clicking on "create on github" just isn't doing anything. Is there a loading animation of some sort or some error logs? I can try to change my default browser from firefox to edge also.

**Comment by justschen** [comment]
gotcha yeah defo try swapping!

i did add in dialogue for if there is a failure to open the URL, should have something in console? if not, I'll try to debug and see if i can recreate.

**Comment by andreamah** [comment]
I'm not sure if this was because of my strange configuration, but if you're not seeing the same thing when you need to SSO, we can probably close this.
