### ISSUE TITLE
Zooming doesn't cancel depending hover request

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#211153]
Testing #210904

* have a provider like below
* show the hover, select `+`
* while it is waiting, select `+` again
* :bug: the previous request isn't cancelled

```ts
vscode.languages.registerHoverProvider('*', new class implements vscode.HoverProvider {
		async provideHover(document: vscode.TextDocument, position: vscode.Position, token: vscode.CancellationToken, context?: vscode.HoverContext) {

			await new Promise(resolve => {
				setTimeout(resolve, 3000)
				token.onCancellationRequested(resolve)
			})

			if (token.isCancellationRequested) {
				console.log("HOVER CANCLED")
				return undefined
			}

			let value: MySuperHover;

			value = new MySuperHover('Hello', 1);

			if (context?.previousHover instanceof MySuperHover) {

				const dir = context?.action === vscode.HoverVerbosityAction.Increase ? +1 : -1
				const newLevel = context.previousHover.level + dir;
				const newValue = `Hello ${newLevel}`
				value = new MySuperHover(newValue, newLevel)

			}

			console.log(value);

			return value;
		}
	});
```

**Comment by jrieken** [comment]
This might unveil an issue with how the API is designed, I think pressing `+` repeatedly should get me to the respective level quickly (1,2,3,4) without needing to await all intermediary results/hovers. However, as of today the API makes us await a previous result before knowing that we can advance further

**Comment by aiday-mar** [comment]
Hi @jrieken yes that's correct, the API is designed so that we pass into the context the previous hover as well as the hover verbosity action. We therefore need to await the current hover before doing a request for a higher level hover.

I suppose we could consider a different API, wherein we don't pass the previous hover. This would allow us to cancel a request and go straight to a higher level request.

**Comment by jrieken** [comment]
Yeah, let's consider the pros and cons of passing an absolute zoom level (and the previous zoom level). That would allow to jump multiple levels at once!

**Comment by aiday-mar** [comment]
As you suggested we could change the HoverContext so that we send the absolute zoom level in the request instead of the hover verbosity action as follows:

```
export interface HoverContext {
    /**
     * Hover verbosity zoom level request
    */
     readonly zoomLevel?: number;

   /**
    * Previous zoom level
    */
     readonly previousZoomLevel?: number
}

```

Advantages:

+ We can send a request for level `n+2`, starting from level `n` without having to pass through level n+1. This means that ultimately, if the user wants to see the most expanded information, they will get there faster.

Disadvantages/Points to think about:

- How would we surface being able to increase by more than one level in the hover? I see two options:
  - The + and - icons intuitively indicate that the level should be increased by one. Suppose we only use the + and - icons to allow the user to increase the hover level by more than one. Then we need some logic which delays sending the hover request until we are more or less sure the user clicked as many times as they wanted on the + or -. We would then need some logic that goes more or less as follows: _If the user clicked on the + icon, wait for 300 ms for another interaction with the + or - icon. If an interaction happens add this to the verbosity level request, and reinitialize the timer of 300 ms_. The issue here is that the timer of 300 ms is somewhat arbitrary and we can never be sure that the user has finished interacting with the + and - icons.
  - We could also show in the hover a number indicating the current hover level, and let the user type the level they would want to increase to. On Enter keystroke, we would directly send a hover request for that level. The issue here is that the user may type an arbitrarily large number like 1000 and this may look strange. If this is to be implemented, it would be good to know the maximum depth of the hover sequence and not let the user write a number bigger than that. We would also need the hover object to return their current absolute level, so we know how to initialize the number in the hover. 

- The `canIncreaseVerbosity` and `canDecreaseVerbosity` on the VerboseHover class partially loose their meaning. Suppose we have a hover at level `n` and we know we can increase to level `n+1`. We don't have any information however for level `n+2`, so if we do a request for level `n+2` we could find out that a hover at this level does not exist. Does it make sense then to introduce a `VerboseHover` with the `canIncreaseVerbosity` and `canDecreaseVerbosity` fields which may or may not be useful?
  - To counter argument the above point, the fields would be useful to know when we reach the border past which we no longer can increase the verbosity at all.

- Related to the above, generally it is possible we send a request for level `n` only to find out that a hover at level `n` does not exist and that the hover sequence stopped at a lower level. This could be an issue for the user experience depending on how the extension implements the code action calculations. It could wind up doing all sorts of computations only to find out this level does not exist. The combination of the `canIncreaseVerbosity` and `canDecreaseVerbosity` fields and the fact that currently one can update only by one level, means we have some confidence that when we request a hover level update the wait will not be in vain.

**Comment by jrieken** [comment]
```
export interface HoverContext {

  // replaces `action`
  readonly verbosityDelta: number;

}
```
