### ISSUE TITLE
IntelliSense for language specific settings is weak

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#21114]
testing #19149

While IntelliSense works for the `"[]"`-case it doesn't work for the `[]`-case.

**Comment by sandy081** [comment]
Yeah, this was due to the issue in json parser not giving proper path which @aeschli aware of.

**Comment by aeschli** [comment]
@sandy081 I fixed getLocation in jsonc-parser@0.4.0.

getLocation inside a object will always return a property from inside that property. Can be empty string if the object has no properties or if the offset is before a actual property    

`{ "a": |` will return location ['a']
`{ "a": { |  }` will return location ['a', ' ']
`{ "a": { |  "key": "value"}}` will return location ['a', ' ']
`{ "a": {  "key"|: "value"}}` will return location ['a', 'key']

As always you can use location.isAtPropertyKey to find out if the offset is at a property or at a value position.

**Comment by sandy081** [comment]
Thanks @aeschli for the fix in JSON parser. But unfortunately the fix does not help this problem. Because, this problem is happening due to the word definition. I am relying on VS Code Document word definition which does not contain character `[`. Hence I do not see this character in my rang I compute. I would have to provide the word definition that includes `[` character while computing range. May I know if you had come across such issues before and had a different approach to fix.

**Comment by aeschli** [comment]
You can [pass in your own regex](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L195) when asking for the current word...
E.g. [this one](https://github.com/Microsoft/vscode/blob/master/extensions/json/client/src/jsonMain.ts#L91) matches the full JSON tokens (full string literal, with quotes)
