### ISSUE TITLE
SystemColorTheme set to matchColorTheme doesn't work

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#211123]
Testing #210929

I have `SystemColorTheme`set to `matchColorTheme` while my workbench color theme is set to a light theme. My native dialogs are no in dark mode.

Other values are working as expected.

**Comment by bhavyaus** [comment]
I'm not seeing `matchColorTheme` as a setting value for   
`"window.systemColorTheme": "default","
`

**Comment by andreamah** [comment]
I think that the options in the settings UI still has `auto` instead of `matchColorTheme`.
![image](https://github.com/microsoft/vscode/assets/31675041/58f8555d-d6eb-4968-9f69-bad8ca36daeb)

I think that the contribution needs to be updated. 
https://github.com/microsoft/vscode/blob/0ed0a9fe1395f8263ba31f7a20cf8987666ac21d/src/vs/workbench/services/themes/electron-sandbox/themes.contribution.ts#L18-L24

**Comment by aeschli** [comment]
Sorry, yesterdat I changed bay the options from `matchColorTheme` to`auto` as to not break existing users.
What's new is that `window.systemColorTheme` is ignore when `window.autoDetectColorScheme` is enabled

**Comment by aeschli** [comment]
I verified this works in Version: 1.89.0-insider (user setup)
Commit: 2fb3fa8dd2f85d7f452066f8a64e8bf259d21412
Date: 2024-04-26T00:56:34.034Z
