### ISSUE TITLE
untitled files aren't exactly restored

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/vscode#211183]
Testing #210915

Repro steps: with Single-repository folder/workspace
* Launch VS Code Insider
* Open a folder/workspace that contains a git repository
* Switch to the git repository's default branch (ex: `main`)
* Open a bunch of files and place them in the workbench grid
* Modify some of the file (but do not save the changes)
* Add some untitled files
* Click on the branch indicator in the status bar and create a new branch
    * Confirm that the current working set is used for the new branch
* On the new branch close some of the editors, and open others
* Close the untitled file and create a different untitled file         **This is the repro part**
* Use the branch indicator in the status bar and switch back to `main`
    * Confirm that the working set associated with the `main` branch is restored
    * Confirm that the dirty editors and untitled files remain opened

**Comment by karthiknadig** [comment]
The issue is that the original "untitled-1" is to replaced with the new "untitled-1"

**Comment by bpasero** [comment]
Untitled files are just identified by a path that is not unique, so this can happen. I would argue that the same can happen if you replace the contents of a file in the one branch and then switch to another branch where the file is open.

In other words: because untitled files are simple (`Untitled-<N>`) and do not have a UUID, this is somewhat expected and I think nothing we can easily fix.

**Comment by karthiknadig** [comment]
I was suspecting this might be the case. Closing this.
