### ISSUE TITLE
 Errors don't show in the Problems panel when warnings are hidden

### ISSUE THREAD

**Issue by georgefst** [microsoft/vscode#211243]
#153219 is still an issue, which I hit pretty much every day, mostly when using the Haskell extension.

Steps to reproduce:
- Hide warnings
- Introduce code which triggers an error
- Problems pane shows "No results found with provided filter criteria"
- Showing and hiding warnings again does eventually show the error

The same happens with hiding infos and introducing warnings/errors, which is the case I mostly run across. Which is to say, this issue could also be titled "Warnings don't show in the Problems panel when infos are hidden".

CC @jminer.

**Comment by jminer** [comment]
I can also still reproduce the bug. With Rust, it doesn't happen with any error, only certain ones (maybe due to compiler pass timing?). I've noticed borrow-checker errors are more often not shown.

**Comment by georgefst** [comment]
Yeah, I've found that it's not _100%_ reproducible, but it happens much more often than not.

**Comment by sandy081** [comment]
It is working for me with Typescript lang. Could be an issue with extension. Please file issue against the extension to get initial investigation done.

**Comment by jminer** [comment]
But the extensions are telling VS Code about the errors because VS Code shows the correct number of errors in the status bar and because it works if you don't hide warnings. Is the extension even told about the show/hide warnings check box? Regardless of what the extension is doing, VS Code is showing inconsistent data in its UI (status bar vs Problems view). Switching to the Terminal tab and back to the Problems tab is enough to get VS Code to show the error like it should. Everything points to it being an issue with VS Code, not the extensions.

**Comment by sandy081** [comment]
Can you please share the steps to reproduce the issue?

**Comment by jminer** [comment]
Sure, I copied steps from the last issue and updated them. Compared to 2 years ago, I couldn't reproduce it with exactly the same source code, but I edited the code a bit to have a different error and now can reproduce it again. I can reproduce it on Windows and Linux.

Here is how I can reproduce it:

1. Install Rust nightly. You can do this by downloading rustup from https://rustup.rs and running it (rustup is the installer/updater for Rust tools). When you install rustup, it will have several options. You can leave them all default except you probably should customize the installation and choose nightly (instead of stable or beta). Right now, I'm reproducing it with `nightly-2024-04-26`.
   Rustup will just install the newest nightly build (which will likely reproduce the bug still), but running `rustup toolchain install nightly-2024-04-26` will install that specific nightly build and `rustup default nightly-2024-04-26` will set it as default. Let me know if you have any questions about installing it.
2. Install the rust-analyzer extension from the Marketplace. It should automatically download the rust-analyzer LSP binary for your platform.
3. Clone this project: `git clone https://gitlab.com/jminer/librsyncr.git`
4. Check out the `vscode-error-bug` branch.
5. In the Problems view, uncheck "Show Warnings" but leave "Show Errors" checked.
6. Open the `librsyncr` folder in VS Code and by default, rust-analyzer should run `cargo check` every time a file is saved in the project (`cargo check` runs the compiler frontend just to get errors and warnings). The `vscode-error-bug` branch has 1 error and 4 warnings. It may take a few seconds for cargo to download the dependencies and run the compiler, but then the status bar should show 1 error and 4 warnings.

After these steps, I would expect the Problems view to always show the 1 error, but it doesn't always. There seems to be a race condition, because it sometimes works and sometimes doesn't. If it doesn't show for you, try saving the file a few times (to get rust-analyzer to rerun `cargo check`). With this project and branch, my desktop computer just reproduced the bug 15 out of 15 times I saved a file. I just tried a laptop I have with the same version of Rust compiler (`nightly-2024-04-26`) and reproduced the bug 9 out of 15 times I saved. Whether it works also depends on what diagnostics the compiler outputs, but the diagnostics should be constant with the fixed project/branch.

**Comment by georgefst** [comment]
This is trivially reproducible for me across separate devices with 100% accuracy. For the following example, it's enough to just install GHCup and let it pick the default Haskell toolchain. Single file, no dependencies. And it turns out that it's not just showing and hiding warnings that causes the error to correctly show up, but almost any sort of UI refresh.

https://github.com/user-attachments/assets/e27f6de4-b88d-4cc8-b1f0-fd6a47d8f368
