### ISSUE TITLE
Long lines are wrapped even though word wrap is turned off

### ISSUE THREAD

**Issue by NiklasRosenstein** [Microsoft/vscode#21124]
- VSCode Version: 1.9.1
- OS Version: Windows 10 x64

Steps to Reproduce:

1. Disable word wrap in the user settings
2. Create a new file
3. Enter a very long text line

---

It appears that VS Code has a column at which it will wrap a line even though word wrap is disabled.
The line wrap doesn't change when I resize the window, it's always wrapped at column 301. This is very annoying when viewing large XML files.

![image](https://cloud.githubusercontent.com/assets/1318438/23211898/82990bb6-f904-11e6-86d6-a9c126dbc6f6.png)

**Comment by alexandrudima** [comment]
Let's track in #21262, the wrapping settings will get an overhaul

**Comment by lukas879** [comment]
As of version 1.13.0 for Mac and Windows (and 1.14.0-insider for Mac), opening a file with lines extending past 10000 columns causes the lines to be wrapped to the viewport's dimensions even though editor.wordWrap is set to "off" (including the language specific override for markdown).

Additionally, copying and pasting a long line of text into a new document behaves fine (no wrapping), until the file is saved. It then wraps the line.

I was able to test the behavior with version 1.12.2 on Windows and it did not seem to be a problem (did not wrap). However, after updating to version 1.13.0 the wrapping behavior was the same as on my Mac with the same version.

See attached files for examples. The only difference between the two files is that "long_line_wrap.txt" contains one extra character at the end of the line - causing it to be wrapped when opened.

Current work around is to toggle word wrapping using Alt+Z, or the menu.

[long_line_no_wrapping.txt](https://github.com/Microsoft/vscode/files/1075097/long_line_no_wrapping.txt)
[long_line_wrap.txt](https://github.com/Microsoft/vscode/files/1075100/long_line_wrap.txt)

**Comment by alexandrudima** [comment]
@lukas879 Yes, this is a "by design" behaviour to workaround a short-coming we have.

* The editor is vertically virtualized (i.e. only the visible lines in the viewport are inserted to the DOM)
* However, the editor is not horizontally virtualized (i.e. if a line is visible, it is sent in its entirety to Chromium for painting)
  * We don't do horizontal virtualization because that would involve us reading the font information, and implementing Unicode layouting + font layouting rules on our side, in our JS runtime, across OSes. Today, we leave it up to the browser to layout the text (think e.g. RTL, bidi text, etc.). Also, any change in the layouting algorithm w.r.t. the painting algorithm would yield many bugs, so we would need to also paint all the characters by ourselves.
* So if a long line is visible in the viewport, we give Chromium the entire line. Chromium ofcourse paints only the visible parts, but it has to deal with the entire line. Unfortunately, if the line is very long, this causes Chromium to slightly freeze, which makes it a very bad experience when scrolling around these long lines.
* As a workaround, we have implemented a heuristic where we try to identify "minified" files, i.e. files that have very long lines are highly atypical for source code and possibly represent that a resource has been inlined in the source code or that we are dealing with a CSS/JS/etc. minified file.
* Our heuristic consists of counting characters that sit on regular lines vs. characters that sit on long lines. A long line is a line with more than 10k characters. If more than 50% of the file's characters sit on long lines, then we consider the file to be a "minified" file.
* In the case of such files, which we call "dominated by long lines", we will wrap the file to protect against the freezes I mentioned above. By freezes I mean that sometimes painting a frame in the editor could take more than >20-30ms, which quickly becomes noticeable, as the large line goes outside the viewport or goes inside, but of course depends on the actual line, etc.
* The only way to unwrap such a file is current via `alt+z` or the menu or the special icon that appears next to the editor title area (actions) only in such cases and the unwrapping is temporary for the current window lifecycle.

I'm sorry for the funny experience that looks like a bug, but it is a (perhaps too-involved) workaround to avoid freezes/pauses.

**Comment by lukas879** [comment]
@alexandrudima That's good to know. I was going crazy trying to find a setting I had maybe misconfigured or overlooked. Thanks for the in depth explanation.
