### ISSUE TITLE
Attach to process launch shows command 'PickProcess' is not found if protocol is inspector'

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#21120]
Testing #20991 

Launched the application from terminal using node v6.5.0 as follows
```
node --inspect --debug-brk=24056 --nolazy server/out/server.js
```

When changed node version to v6.10.0 it works

![kapture 2017-02-22 at 12 42 35](https://cloud.githubusercontent.com/assets/10746682/23210129/7be5e1ac-f8fc-11e6-8bbd-fde3f000f288.gif)

**Comment by polysok** [comment]
while waiting for a fix, you can juste rename **P**ickProcess to **p**ickProcess. That works for me.

**Comment by cramhead** [comment]
The pickProcess trick does not work. I get info message "Please set up the launch configuration file for your application. command 'pickProcess' not found" on MacOS Sierra 10.12.5 (16F73)

**Comment by weinand** [comment]
@cramhead sorry, but I don't understand your problem. It does not seem to be related to the original problem.

How does your launch config look like?

**Comment by millermatt** [comment]
@weinand 

> sorry, but I don't understand your problem. It does not seem to be related to the original problem, though.

It's the exact same error shown in OP's gif.

VS Code 1.13.1
Node 8.1.2

```
{
    "type": "node",
    "request": "attach",
    "name": "Attach to Process",
    "processId": "${command:PickProcess}",
    "port": 9229,
    "protocol": "inspector"
}
```
Running this configuration results in the message:
> Please set up the launch configuration file for your application. command 'PickProcess' not found

If you add `"protocol": "inspector"` to your launch configuration then PickProcess is no longer a command that VS Code recognizes.

**Comment by weinand** [comment]
@millermatt the use of `processId` and `"protocol": "inspector"` is not supported in VS Code < 1.14. In earlier versions only the "legacy" protocol is supported.

**Please note 1:** use "Attach via Process ID" only if you did **not** start node.js in debug mode. If you have started node.js with the "--debug" or "--inspect" options, there is no need to use the `processId` attribute because there is only one process that listens on that port.

**Please note 2:** starting with VS Code 1.14 please don't specify the `port`and  the `protocol` attributes when using `processId`. We will use the correct port and protocol automatically if you attach via a process ID.
