### ISSUE TITLE
Few Small issues regarding the `Menu Bar` after recent updates to enable `Top` positioning option

### ISSUE THREAD

**Issue by RadhiRasho** [microsoft/vscode#211353]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.88.1
- OS Version: Windows 10 Enterprise 22H2

Steps to Reproduce:

1. Set `Activity Bar` to `Top`
2. Set `Menu Bar` to `hidden`
3. Set `Side Bar` to location to `right`
4. Click `Alt` which should switch to the `Menu Bar` (Hamburger menu) in the `Activity Bar` don't do so now, possibly due to the switching of the position of `Activity Bar` to `Top`
5. Click the `Menu Bar` item and you'll see that the context menu opened is misaligned with the current position of the `Menu Bar`, this doesn't seem to be an issue when the `Side Bar` location is to the `left` only on the `right`.

Image: 
![image](https://github.com/microsoft/vscode/assets/54078496/7b8792ec-4336-4e91-b323-87f5b8356c27)

**Comment by Lyqst** [comment]
Hello! This has been bugging me for a while now (I use the sidebar to the right and the activity bar on top), so I decided to go ahead and try and fix this.

I realized the underlying issue is that when the `Side Bar` is to the left and you hide the `Menu Bar`, the hamburger button is placed to the left regardless of the position of the `Activity Bar`, but when the `Side Bar` is to the right, so my proposed fix is to move the hamburger button to the far right in this case, so its position is more consistent.
### Sidebar right and activity bar default
![image](https://github.com/microsoft/vscode/assets/78376862/e10be188-816f-49c5-b097-8b9897ab5639) ![image](https://github.com/microsoft/vscode/assets/78376862/724d7f8c-b65b-4e92-a4a1-faf05e61471c)

### Sidebar right and activity bar top
![image](https://github.com/microsoft/vscode/assets/78376862/f6473412-522c-40e2-8198-b0feaffd6c38) ![image](https://github.com/microsoft/vscode/assets/78376862/ca21cf13-6b12-4b95-bdc0-97fc36f2a1dd)

Let me know what you think and I'll create the PR.

**Comment by benibenj** [comment]
I fixed to position of the menu bar when the side bar is to the right. 
I check regarding alt moving focus to the compact menu and saw it does work, but we just don't show any indication that focus is there. Which we need to fix
