### ISSUE TITLE
Git commit box does not warn long messages

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#21144]
Testing #20999 

There is a setting to enable warning for long commit messages. Even though it is enabled, there is no warning shown for long messages. Also it would be helpful to update the description of the setting about the length of the message

**Comment by koddsson** [comment]
Hey @joaomoreno! I'd very much like this feature after starting using visual studio code. Can I pick this up and submit a patch? If so, something I should keep in mind?

**Comment by joaomoreno** [comment]
I admire your effort, but this won't be a simple task, since git is now an extension. You'll be limited by the extension API.

If you want to contribute to VS Code I suggest to go through the [`help wanted`](https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) issues first.

**Comment by scottclayton** [comment]
I still miss it a lot. There are a couple stupid things I do to work around this a bit though:

1. type the message in the editor on an empty line first and see its length according to the status bar. e.g. if the cursor is at the end of the line and the status bar says `Ln 15, Col49`, then it should be 48 characters long.

2. (on mac), make the font of the input box monospaced by adding css to vscode's _own_ css (located at `/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.css`) and pasting this below all of the css
```
.scm-viewlet>.scm-editor>.monaco-inputbox {
  font-family: monospace;
}
```
that does make a warning pop up in vscode that it's unsupported though, and it will have to be redone every time a new version of vscode is installed

**Comment by jayjun** [comment]
![atom](https://user-images.githubusercontent.com/4433966/31976595-0f44f22e-b96b-11e7-9519-5fbe554a2818.png)

I like how Atom tucks a character countdown in the corner.

Yellow after 55 characters, then red after 72 characters. Negative numbers to count excess characters are handy too.

**Comment by scottclayton** [comment]
@jayjun 

You gave me an idea and it totally works on the Mac version (1.17.2)!!! (I don't know if you have a Mac, so this might only be for Mac users).

![commit message length](https://user-images.githubusercontent.com/10013159/31980648-c499b312-b902-11e7-94da-c1122701b7d7.gif)

You can add additional JavaScript to the VS Code app, so why not add some DOM-manipulation!?!

You can accomplish it using the following steps:

- find the `Visual Studio Code.app` application file in your Mac's Application folder
- right-click the app and click `Show Package Contents`
- navigate to the `Contents/Resources/app/out` folder
- open the `paths.js` file
- add the following code to the bottom of the file:
```js
window.addEventListener("keyup", gitCharacterCounter, false);

function gitCharacterCounter() {
  var mirror = document.getElementsByClassName("mirror")[0]
  
  if (mirror) {
      var length = mirror.textContent.replace('Message (press Cmd+Enter to commit)', '').length
      var titleLabel = document.getElementsByClassName("title-label")[0]
      var titleSpan = titleLabel.getElementsByTagName('span')[0]
      var labelBase = titleSpan.textContent.replace(/\([0-9]{0,100}\)/,'')

      titleSpan.innerHTML = labelBase + ' (' + length + ')'
  }
};
```
- that's it! You will have to reload the current window of VS Code you're using

![screen shot 2017-10-24 at 9 33 39 pm](https://user-images.githubusercontent.com/10013159/31980686-0b3b8ec6-b903-11e7-99de-981f7e9d400c.png)

**Comment by jayjun** [comment]
@scottclayton Wow, that’s an amazing hack!

I found the actual code responsible for those elements. `InputBox` listener [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/scm/electron-browser/scmViewlet.ts#L577) and `getTitle()` [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/scm/electron-browser/scmViewlet.ts#L887).

I think adding a counter to the actual `InputBox` or surrounding elements is more acceptable since multiple SCMs could be active.

Would love to work with you to get a pull request in!

**Comment by scottclayton** [comment]
@jayjun Thanks!

I'm totally on board for working on a PR for restoring the feature—I've been missing it nearly every day since its removal.

I think implementing a running count of characters _plus_ a warning when a certain length is exceeded—(configurable as settings for whether or not the warning happens and also what the length limit would be for the warning when exceeded)—would be a nice approach, since we would be getting the character count for free every time we check if the length exceeds the limit anyway. What do you think?

I couldn't see any active PRs for the feature, so I guess this is our time to shine.

I have no idea how people on github communicate with one another, so I've made a gist for us to discuss it if you're keen: https://gist.github.com/scottclayton/2c463746002ed2070ab1914bb7c7cafb

**Comment by jayjun** [comment]
@scottclayton I submitted a WIP pull request. Let’s continue our discussion/hacking there!

**Comment by joaomoreno** [comment]
Fixed by https://github.com/Microsoft/vscode/pull/36890
