### ISSUE TITLE
Don't show D&D target cursor for original text selection

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#21158]
Testing #21012:

- select some text
- start D&D operation
- move the mouse pointer (which marks the drop target location) over the original text

Observe: the dotted cursor is shown but if you end the D&D operation by releasing the mouse button, nothing happens.

Since the original selected text is not a valid drop target, no dotted cursor should be shown.

**Comment by rebornix** [comment]
This behavior is aimed to be backwards compatible. Without Drag and Drop, clicking on a selection will move the cursor to the place your click. So right now with Drag and Drop, if you click on a selection, move it around and drop it inside the selection, we still shrink the selection to the place where the target is.

![dnd](https://cloud.githubusercontent.com/assets/876920/23233466/cb8bfb9a-f903-11e6-8232-dc3b116349c4.gif)

So IMHO, we can either 

* Stick with current behavior, or
* Do not show dotted cursor if the target is inside the selection, and when users release the mouse, keep the selection instead of shrinking it.

Let me know if my explanation makes sense.

**Comment by weinand** [comment]
I suggest to use the second option:
- It gives the correct feedback that there is no target
- it is the same behaviour that you find in other text editors.

**Comment by rebornix** [comment]
Right now as we can't distinguish a pure mouse down event and a drag event in DND contribution, we always shrink the selection if the dnd target or the mosuedown target is inside the selection.

I'll make enhancement to this part together with https://github.com/Microsoft/vscode/issues/21320 .
