### ISSUE TITLE
Folder picker always chooses my root directory

### ISSUE THREAD

**Issue by dsoodak** [Microsoft/vscode#2115]
When I try to select a folder for projects, it always chooses the root directory regardless of which one I select.
Running ubuntu 12.04.5 LTS, kernel 3.5.0-54-generic

**Comment by Tyriar** [comment]
I experience this too on only one of my Ubuntu machines. Not sure what causes it, but it happens on Atom?

The work around until this is fixed is to launch via command line:

```bash
cd my-project
Code .
```

The machine in question happens to be Ubuntu 12.04 LTS as well, so maybe it's an Ubuntu or Electron bug?

**Comment by Tyriar** [comment]
I created an Atom issue for this a few months ago, no attention though https://github.com/atom/atom/issues/9320

**Comment by bpasero** [comment]
Maybe this should be reported to Electron instead.

**Comment by Tyriar** [comment]
Created https://github.com/atom/electron/issues/4171 and closed the Atom issue in favor of it.

**Comment by Tyriar** [comment]
It was closed in favor of https://github.com/atom/electron/issues/1212. Apparently it's because Electron doesn't support `~` as it isn't meant to be meaningful outside of bash. Ubuntu 12.04's open folder dialog may be returning `~` in the path which is probably what is causing the issue. Electron removed the won't fix label though so they're open to accepting the change to support it.

**Comment by bpasero** [comment]
:+1:

**Comment by bpasero** [comment]
Closing, as there does not seem to be anything we can do.
