### ISSUE TITLE
Configurable window title: relative file path or editor name

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#21177]
While testing #20433.

When the editor is backed by a real file I'd like to see the relative file path. For editors that do not have a real/single file behind them such untitled files or settings, I'd like to see the editor name.

This could be either a new variable or support for simple conditionals `${activeFilePathRelative ? activeFilePathRelative : activeEditorName}`

**Comment by bpasero** [comment]
Some people have already asked for scripting support in that area, maybe I start to come up with my own new language for it?

**Comment by bpasero** [comment]
I decided to revisit the variables around file paths and change them because things are getting complicated when an editor is not showing a file. 

Here is my new solution:
* `${activeEditorLong}`: e.g. /Users/Development/myProject/myFolder/myFile.txt
* `${activeEditorMedium}`: e.g. myFolder/myFile.txt
* `${activeEditorShort}`: e.g. myFile.txt

If there is no long editor label, the medium one will be used. And the same is true for medium and short. To get what you want, you can now just configure `${activeEditorMedium}`

@kieferrm @egamma @mousetraps happy to hear feedback on this approach since you were the assigned testers.

**Comment by kieferrm** [comment]
@bpasero the proposal makes good sense to me.

**Comment by bpasero** [comment]
@kieferrm maybe you could verify this one

**Comment by kieferrm** [comment]
@bpasero done. Works well.
