### ISSUE TITLE
Does /** @param */ have to be in intellisense?

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#21176]
#21031

This looks a bit ugly to me and users would probably be seeing it an awful lot now:

![image](https://cloud.githubusercontent.com/assets/2193314/23224893/d97610ca-f8e4-11e6-9cfb-999349b07d16.png)

Does the feature have to be tied to intellisense? It seems to me this would be ideal:

1. Type `"/**"` on the line before a function, `" */"` is added after the cursor as before
2. Press <kbd>enter</kbd>
3. Intercept the enter key press and perform an atomic operation which transforms `/** */` into:

    ```js
    /**
     *
     * @param blah
     */
    ```

    That way it's a single undo to go back to `/** */`

The main reason I feel strongly about this is I never care about jsdoc unless I type `/**` and <kbd>enter</kbd> on the line before a function, in which case I *always* care about it. So why not just enforce the behavior there and keep it out of intellisense?

It's also kind of annoying to have the popup appear on typing /** as I'm forced to dismiss it if I want to go to another line via arrow keys.

**Comment by mjbvz** [comment]
For now, this is the best we can do. I previously implemented doc completions as you described, by using the enter key, but that introduced more concerns (see  #20990)

We need a new api to support this scenario better. @rebornix and I discussed this, and I'll put together a new API proposal for something like an `onEnterProvider` when I have a chance. 

The reason for auto-showing the intellisense when typing `/**` is to emulate the behavior of the enter key based completion flow. Now you just type <kbd>/</kbd><kbd>\*</kbd><kbd>\*</kbd><kbd>enter</kbd>and the doc is completed. However, the suggestion is being auto shown too often currently. I'm working to address that

Thanks for the feedback

**Comment by mousetraps** [comment]
Perhaps a good stop-gap measure would be getting rid of the "JSDoc comment" description so that the user's focus isn't on it as much?

Compare this:
![image](https://cloud.githubusercontent.com/assets/762848/23239515/95c1e24a-f91c-11e6-8f6c-b5aa26b190bc.png)

to this:
![image](https://cloud.githubusercontent.com/assets/762848/23239524/a3696580-f91c-11e6-8871-74a5e5c055e0.png)

**Comment by mjbvz** [comment]
Thanks, I've since updated the completion item to:

<img width="573" alt="screen shot 2017-02-22 at 4 44 58 pm" src="https://cloud.githubusercontent.com/assets/12821956/23239823/4daca2ae-f91e-11e6-8cc4-41ff97659617.png">

The `@param` part had to be removed because it was causing us to match on words like `param` when the suggestions were triggered
