### ISSUE TITLE
Sticky bar for every function doesnot update while using the function parameters inside the function

### ISSUE THREAD

**Issue by rvfreelance** [microsoft/vscode#211823]
Type: <b>Bug</b>

Make sure you are using function with parameters and you are few lines down the code inside of that function so that the function line becomes sticky at the top. And make sure you are not using atleast one of the parameters till then. Now when you see atleast one of the parameters in faded color in the sticky bar, try to use that parameter and you will see the parameter color will not become bright until you scroll to the top of the function and now you will see the parameter gets updated with the bright color. And you can try this again by deleting the code which used that parameter, but the sticky bar doesnot update till you scroll to top of the function.

VS Code version: Code 1.88.1 (e170252f762678dec6ca2cc69aba1570769a5d39, 2024-04-10T17:41:02.734Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by aiday-mar** [comment]
Hi @rvfreelance I suppose you are talking about the editor sticky scroll feature. If I understood correctly you mean that when you highlight some text inside of the editor, the corresponding text inside of the sticky scroll is not highlighted. There is a feature request tracking this issue, which suggests adding editor decorations https://github.com/microsoft/vscode/issues/187834 to the sticky lines in order to better emulate the lines of the editor. You may track this issue there. In the meantime, this issue will be closed.
