### ISSUE TITLE
after the update, the underscore is not displayed in the vscode terminal

### ISSUE THREAD

**Issue by AmIaLion** [microsoft/vscode#211933]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
Version: 1.89.0
Commit: b58957e67ee1e712cebf466b995adf4c5307b2bd
Date: 2024-05-01T02:08:25.066Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Linux x64 6.5.0-28-generic snap
- OS Version:  Linux nb-X 6.5.0-28-generic #29~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Apr  4 14:39:20 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

Steps to Reproduce:

1.  open vscode terminal
2. send mkdir test_dir
![изображение](https://github.com/microsoft/vscode/assets/124941209/b788c269-3c0b-47c4-8e7f-598e1dfc1d8a)

_ isn't displayed in some cases like `pwd` or `git checkout -b test_branch`
![изображение](https://github.com/microsoft/vscode/assets/124941209/826615f2-9b85-4361-b611-74f1e9de3be8)
it not displayed while typing, but if ctrl+c, ctrl+v it shows.

**Comment by meganrogge** [comment]
does changing `terminal.integrated.gpuAcceleration` help?

**Comment by AmIaLion** [comment]
> does changing `terminal.integrated.gpuAcceleration` help?

It helps when  set "canvas", previous setting was "auto"

**Comment by kevin-presalytics** [comment]
I had this same problem when updating to the new version.  Setting `terminal.integrated.gpuAcceleration` to "canvas" helped.

**Comment by pindjur** [comment]
Same issue, Linux.
setting terminal.integrated.gpuAcceleration to anything other than "off" fixed it. Was "auto", but now when I updated this setting once, I could not reproduce the issue with "auto", just with "off"

**Comment by k98kurz** [comment]
Looks like another regression. Same issue #123077 and #35901 before that. Changing font size fixes the display, though then you have to use a font size you did not want.

**Comment by bodik** [comment]
same here, debian linux 12, "off" uses font variant without underscore visible, any other setting works fine (but also uses little bit different font, change is visible during changing the setting)

**Comment by Mendes11** [comment]
Just updated and started having this same issue. If set to `canvas` it works, anything else don't

Ubuntu Noble

**Comment by LincolnCB** [comment]
What has worked for me (each works separately):

- Changing the font size to 13 or 15 (underscore is invisible on 14)
- Changing the Terminal Integrated GPU Acceleration to `on` or `canvas`
- Changing the Terminal Integrated Line Height to anything above 1.0625 (that seems to be the cutoff)
- Changing the Terminal Font Family (every other one I tried seemed to work)
- Changing the Terminal Integrated Font Weight to anything above 550 (close to bold, seems to be the cutoff)

I'm sticking with the Terminal Integrated GPU Acceleration to `on` right now, as it changes the least about my terminal's view.

**Comment by Tyriar** [comment]
This is happening is previously your setup would use the canvas renderer, which was removed as an option for `auto` in v1.89 and all together in v1.90. The canvas renderer includes some smarts about shifting underscores upwards when they sit particularly low which seems to be the case for some default fonts on Linux. This isn't actually a regression (https://github.com/xtermjs/xterm.js/issues/4067), it's just being hit by more people since the canvas renderer is gone.

Since these issues seem restricted to Linux, I'm thinking for the upcoming release I'll force `lineHeight` to be 1.1 by default on Linux. Then in the next release come up with a more robust solution for these fonts in https://github.com/xtermjs/xterm.js/issues/4067

---

Recommended workarounds:

- Set `"terminal.integrated.gpuAcceleration": "on"` (this might not work)
- Set `"terminal.integrated.lineHeight": 1.1`
- Change `"terminal.integrated.fontFamily"`

**Comment by heck-gd** [comment]
I'm still seeing this issue in 1.90.2. The 1.1 workaround doesn't cut it for me. It has to be at least 1.15 for the underscore to be visible.

**Comment by Tyriar** [comment]
https://github.com/xtermjs/xterm.js/issues/5240 and https://github.com/xtermjs/xterm.js/issues/4067 are tracking trying to remove the overflow CSS rule to workaround this.
