### ISSUE TITLE
CodeLens and Data Annotations

### ISSUE THREAD

**Issue by rhires** [Microsoft/vscode#21208]
This is a bit of a feature request/not quite a bug...
- VSCode Version: Version 1.10.0-insider (1.10.0-insider)
- OS Version: Mac OS

Currently, CodeLens in the Model classes sticks right above the POCO. But when I add annotations, I get the CodeLens in between the POCO and the Annotation, and when I have a couple of them, it gets confusing: 

![image](https://cloud.githubusercontent.com/assets/12577765/23231608/6df1bef8-f916-11e6-8132-6d9b4fa935fe.png)

What I would like to see is that the CodeLens be included above the annotation for the POCO, so that it's all treated as a single unit: 
![image](https://cloud.githubusercontent.com/assets/12577765/23232105/1bec87f8-f918-11e6-81c4-6709f65524b7.png)

Thank you for all of the great work you do!

**Comment by mjbvz** [comment]
VSCode allows adding a code lens to any line, so it is the C# extension that is deciding to place it after the attributes. 

Please try opening a feature request against the C# extension that is providing these code lenses. However, the existing behavior does match how Visual Studio places its code lenses, so this may be by design
