### ISSUE TITLE
TS version in status bar is confusing

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#21217]
#21037

It looked to me like that's VS Code's version initially.

![image](https://cloud.githubusercontent.com/assets/2193314/23234047/ad740420-f905-11e6-91bb-8d5105f6903f.png)

Why not use something like "Bundled TS" or something to more more useful and obvious what it really is. Users probably don't care the exact version number and it just adds visual noise.

**Comment by mjbvz** [comment]
As mentioned in #21219, this was a change made in 1.9 to be more consistent.

VSCode can either use a workspace version of TypeScript or the VSCode version of TypeScript. In the latter case, the TypeScript install may be the bundled version or it may come from a user's `typescript.tsdk` setting. Rather than try to differentiate all of these cases, we opted to always show the version to make the experience consistent.

The string will be shortened to something like `2.2.2` once we pick up the final TS 2.2 release
