### ISSUE TITLE
Missing Hot Reload button in debug toolbar

### ISSUE THREAD

**Issue by iqfareez** [microsoft/vscode#212143]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.89.0
- OS Version: macOS Sonoma 14.1.2 arm64

## Steps to Reproduce:

This issue coming from https://github.com/Dart-Code/Dart-Code/issues/5055. Cc @DanTup 

1. Install Flutter extension from marketplace
2. Open/Create Flutter project in Vscode
3. Run the app by clicking the run button inside the IDE
4. Wait until the app is running on platform (eg emulators)

 ## Expected behavior

Hot reload button will appear :zap:

<img width="405" alt="Screenshot 2024-05-07 at 12 09 20 PM" src="https://github.com/microsoft/vscode/assets/60868965/49c26e8e-403c-48de-9121-c939d4798fe4">

## Actual behavior

Hot reload button doesn't appear

<img width="537" alt="Screenshot 2024-05-07 at 12 06 06 PM" src="https://github.com/microsoft/vscode/assets/60868965/780ec5c5-e331-446b-a4a6-caf10ef6038c">

## Workaround

Toggle `debug.toolBarLocation` brings back the Hot Reload Button

https://github.com/microsoft/vscode/assets/60868965/dbdf3ac5-60d1-45ae-8c55-4f08f07a225f

**Comment by roblourens** [comment]
Hey @DanTup, are you able to repro this? I set up a test extension that contributes a command the same way that the Dart extension does, and it works fine for me. I can try in the Dart extension too, but I'm wondering whether it's a fluke for this user or something that happens regularly.

**Comment by roblourens** [comment]
Ah nevermind, I guess I do have a repro using js-debug

**Comment by roblourens** [comment]
Hey @jrieken, I can't figure out how this is supposed to work in the command center. It seems that we don't listen to updates of the debug submenu inside the command center. Easy repro steps

- Put debug toolbar in the CC
- Start debugging something with node
- Run "Start profiling"
- The red button to stop profiling doesn't appear in the debug toolbar unless I do something like move it

**Comment by jrieken** [comment]
Weird, we should receive events and redraw the menu because of the [`emitEventsForSubmenuChanges`](https://github.com/microsoft/vscode/blob/db4e4ff980f9061bb4d8455e617531f46d518328/src/vs/platform/actions/browser/toolbar.ts#L340)-flag.

**Comment by roblourens** [comment]
Debugged this for awhile, and I don't know how it supposed to work, but it basically doesn't load the context keys for extension-contributed menu items because nothing is prompting the CommandCenter menu to reload context keys for submenu items after the menu extension contrib point is handled.

1. We create a Menu for CommandCenter, and it has a MenuInfo: https://github.com/microsoft/vscode/blob/4a1c81e9590a9617f6234da348a147d81a56cdb4/src/vs/platform/actions/common/menuService.ts#L375
2. This picks up the context keys for whatever exists at that moment, and we don't have the extension menu items yet
3. Later we process the menus extension point and add those items to the MenuRegistry for the DebugToolbar
 
But at this point, something needs to bubble this up to the CommandCenter. The Menu should fire onDidChange at that moment, and I don't see how that would happen. And, the CommandCenter Menu should call `this._menuInfo.refresh()` somewhere in there.

Something is definitely missing. I didn't debug the normal submenu case but I'm guessing the inlined rendering of CommandCenter's submenus is related somehow, I assume in a normal case the context keys for submenus would get updated in some other way.

Maybe when you're back we can jump on a call and I can show you what I'm seeing.
