### ISSUE TITLE
Update Node.js version

### ISSUE THREAD

**Issue by ksmultiacc3** [microsoft/vscode#212144]
Please update node.js in https://github.com/microsoft/vscode/blob/main/remote/.yarnrc to 22.1.0 from 18.18.2.
I need it for compatibility purpose.

Newer version is available here: https://github.com/coder/code-server/blob/main/.node-version

**Comment by ksmultiacc3** [comment]
@joyceerhl please assist

**Comment by deepak1556** [comment]
Sorry our remote node version should be aligned with the client, we recently updated to Node v20 as part of https://github.com/microsoft/vscode/commit/5216c044283ba1f3c66caa092fd75ba0b3e3e5ca. We will adopt Node v22 when the runtime supports it.

> I need it for compatibility purpose.

Please expand on the need for Node v22. If there is a fix we need to backport, we can look into it.

**Comment by ksacc** [comment]
@deepak1556 
Multiple Vulnerabilities are reported in Node.JS 20 and 21<BR>
CVE-2024-21892 - Code injection and privilege escalation through Linux capabilities- (High)<BR>
CVE-2024-22019 - http: Reading unprocessed HTTP request with unbounded chunk extension allows DoS attacks- (High)<BR>
CVE-2024-21896 - Path traversal by monkey-patching Buffer internals- (High)<BR>
CVE-2024-22017 - setuid() does not drop all privileges due to io_uring - (High)<BR>
CVE-2023-46809 - Node.js is vulnerable to the Marvin Attack (timing variant of the Bleichenbacher attack against PKCS#1 v1.5 padding) - (Medium<BR>
CVE-2024-21891 - Multiple permission model bypasses due to improper path traversal sequence sanitization - (Medium)<BR>
CVE-2024-21890 - Improper handling of wildcards in --allow-fs-read and --allow-fs-write (Medium)<BR>
CVE-2024-22025 - Denial of Service by resource exhaustion in fetch() brotli decoding - (Medium)<BR>

**Comment by deepak1556** [comment]
We do security patch releases only in case we become aware of a vulnerability that affects VS Code. We are tracking all CVEs issued for all of our dependencies, including node.js, v8, chromium, electron, etc, and we have a [mechanism to receive VS Code specific security issues](https://github.com/microsoft/vscode/blob/main/SECURITY.md#reporting-security-issues).

Node.js has as its main use-case hosting servers that are exposed to the internet. VS Code does not use node.js in this way, so almost all CVEs that are reported against Node.js are not impacting VS Code.

Finally, we update regularly (monthly) our dependencies, so the next VS Code stable version will contain an updated nodejs.

/cc @alexdima
