### ISSUE TITLE
ctrl alt p Prompt mistake

### ISSUE THREAD

**Issue by zhangenming** [microsoft/vscode#212343]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. 
2. ![image](https://github.com/microsoft/vscode/assets/21235555/2ae20fa5-e03e-4c2f-8568-9ad311860c24)
3. Should match `TS` word but be independent to two positions

**Comment by TylerLeonhardt** [comment]
Hi @zhangenming, what do you expect to come first? `Accounts: Manage Trusted Extensions For Account`?

**Comment by zhangenming** [comment]
What I'm want talking about is the boldface notation
now: **t**ypescript: restart ts **s**erve
except: typescript: restart **ts** serve

**Comment by TylerLeonhardt** [comment]
Gotcha, this is because of this logic here:

https://github.com/microsoft/vscode/blob/2c626bbdb970cf661d86b22d7c9273312ab01b9a/src/vs/platform/quickinput/browser/commandsQuickAccess.ts#L50

```
or(matchesPrefix, matchesWords, matchesContiguousSubString);
```

* The `matchesPrefix` doesn't match anything so that's false...
* But the `matchesWords` _does_ match with what you see is bold. It matches the first letters of the words
* Since the `matchesWords` returned something, the `matchesContiguousSubString` never runs

If we switched `matchesWords` with `matchesContiguousSubString` here's what we get:
<img width="507" alt="image" src="https://github.com/microsoft/vscode/assets/2644648/25908b3c-a98c-4a62-b7ef-c924959fc67c">

while current behavior looks like this:
<img width="487" alt="image" src="https://github.com/microsoft/vscode/assets/2644648/1041aa8c-a8cd-454b-8646-91dbff83709d">

I feel like the current behavior is a little easier to parse... but maybe some wider improvements like addressing https://github.com/microsoft/vscode/issues/173767 is really the direction we should take.

Any thoughts @bpasero?

**Comment by TylerLeonhardt** [comment]
Let's keep the current behavior. I think it makes slightly more sense.
