### ISSUE TITLE
Can not step into WASM

### ISSUE THREAD

**Issue by guusw** [microsoft/vscode#212413]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.88.1 (user setup)
Commit: e170252f762678dec6ca2cc69aba1570769a5d39
Date: 2024-04-10T17:41:02.734Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.22621

Steps to Reproduce:

- Build any web assembly module with emscripten (version 3.1.59)
The main flags of importance in my project are:
`-gseparate-dwarf=fbl-min-test.debug.wasm -sSEPARATE_DWARF_URL=http://localhost/build-dbg/fbl-min-test.debug.wasm`
- when trying to step into wasm while attached will just hang the debugger . (This works in chrome by itself )
- Attaching vscode while already stepped in on chrome will just pull up 'binary content not shown' (both with and without the WASM extension)
![image](https://github.com/microsoft/vscode/assets/16842774/1c94fc9c-7136-41b2-b7d3-34d2b4544b61)

I considered posting this on the extension github but it seems broken even without, because stepping into wasm code freezes the debugger.

**Comment by connor4312** [comment]
Thanks for the issue, sorry it took me a while to get to. Unfortunately I don't repro this with the steps

1. Check out https://github.com/connor4312/vscode-debugging-webapp-wasm at 5ed463db2898b07fdaf9bdf1d4abc8d49e8a547a
2. Run `make build && make serve` (runs emcc in Docker)
3. Go into the generated main.js and set a breakpoint on the line like `return f(...args);`
4. F5 in VS Code and then "step in" when the breakpoint is hit
5. I'm able to step around the WAT successfully

I wasn't clear whether you're using our [DWARF debug extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.wasm-dwarf-debugging) too since you mention symbols but talk about WAT. To enable DWARF debugging in my repro, install that extension and remove the `"enableDWARF": false,` line from the launch.json.

Please let me know if you're able to repro the problem using my example. You can also collect some trace logs from a case where you do hit it which might give me some extra hints. Thanks!

/jsDebugLogs
