### ISSUE TITLE
After upgrading VisualStudio Code from 1.89.0 to 1.89.1, environment variables are no longer inherited from the current process when starting code.exe

### ISSUE THREAD

**Issue by Largo2005** [microsoft/vscode#212681]
Usually, I start Visual Studio code using a batch script which sets some useful environment variables then executes "code.exe .". However, since version 1.89.1, those environment variables are no longer being set in VSCode.

I expect to have the same behavior than with previous version 1.89.0 (and before)

- VS Code Version: 1.89.0 vs 1.89.1
- OS Version: Windows 10

Steps to Reproduce:

1. open command prompt
2. set environment variables
3. start viual studio code using "code.exe ."
4. verify the environment variables are inherited.

**Comment by JHag6694** [comment]
Similar problem for me: 
I use to start VSCode from a command prompt with some useful environment variables.
And sometimes, I start 2 VSCode from 2 different command prompt with different useful environment variables values.

Since VS Code 1.86, environment (variables and their values) of 2nd VScode run is inherited from 1st VSCode run.
With VS Code 1.85 and before, environments were different (depending on the command prompt from where I started VSCode)

**Comment by JHag6694** [comment]
Hello @Largo2005 
FYI, you can add --preserve-env to retrieve previous behavior
See : https://github.com/microsoft/vscode/issues/212964#issuecomment-2120915608
