### ISSUE TITLE
File endings abbreviated in Quick Open

### ISSUE THREAD

**Issue by Lanterm** [Microsoft/vscode#21271]
- VSCode Version: 1.9.1
- OS Version: Ubuntu

Steps to Reproduce:

1. Create a few files with the same name but different endings, e.g., foo.ts, foo.html, and foo.css
2. Open Quick Open and type "foo"

The problem is that I can't see whether I am about to open the ts, html, or css file.

![image](https://cloud.githubusercontent.com/assets/1098905/23260314/83e202e8-f9d1-11e6-8c48-8c11754d6528.png)

**Comment by bpasero** [comment]
@Lanterm I have no clue why you get this, all I can say is that we are never add the "..." like that, e.g. see:

![image](https://cloud.githubusercontent.com/assets/900690/23262308/8f15853c-f9da-11e6-8366-41760502f5be.png)

I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by Lanterm** [comment]
I ran it without extensions (they are now all having a "Reload" label next to it), but had the same problem. This used to work for me some time ago, but may have started with the upgrade to version 1.9?

It happens for both sections 'recently opened' and 'file results' btw (this isn't visible in my first screenshot).

**Comment by bpasero** [comment]
Sorry, I have no clue whats happening :-/

**Comment by Lanterm** [comment]
The workspace is confidential, unfortunately. If I manage to reproduce it in a neutral workspace, I'll share it. Thanks for looking into it.

**Comment by bpasero** [comment]
@Lanterm yeah please try from another workspace running with any extension disabled. 

Maybe you could also try to reproduce from our nightly insiders build:  You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by bpasero** [comment]
@Lanterm ping
