### ISSUE TITLE
Border around chat context might not be needed?

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#212838]
Personal preference - I do not like the border around the attached context. 
Does not align with the rest of the UI.
Do we really need the border? Have we tried this without the border?

![Image](https://github.com/microsoft/vscode/assets/1926584/bc681df1-4b05-4d96-8baf-644a00343e9a)

fyi @daviddossett @roblourens

**Comment by daviddossett** [comment]
Yeah, I've tried this because I don't love the weight it adds either. It does cause some weirdness when there are follow ups and lots of pills. But I'll keep playing with it to see if I can get to a place where we don't need it.

![Image](https://github.com/microsoft/vscode/assets/25163139/c48e9da3-9fbc-424a-bdcc-a3ab1f3912a4)

**Comment by isidorn** [comment]
Thank you David!
