### ISSUE TITLE
Suggestions: filterText not easy to use

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#21287]
`ISuggestion` [`filterText`](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/modes.ts#L215) is not easy to use. One of the reasons is the fact that the accepted suggestion has to be longer than the `filterText`.
Due to this I had to fall back to using `incomplete: true` suggestions.
In order to repro just change `incomplete: false` [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/repl.ts#L191) and debug the following code:

```
var o = {};
o['hello world'] = 123;
debugger;
```

**Comment by jrieken** [comment]
Super simple steps:

```ts
    vscode.languages.registerCompletionItemProvider('abc', {
        provideCompletionItems(doc, pos) {
            return [new vscode.CompletionItem('hell')];
        }
    });
```

* have above completion item provider
* type `hel` -> `hell` is being suggested 👍 
* type `hello` -> nothing be being suggested 👎

**Comment by jrieken** [comment]
So, after consulting with @aeschli we figured it's the best idea to keep shorter suggestions. With that you will never be able to remove noise, like having the `do` keyword also suggested when type `doApplyChanges` etc. 

The conclusion is that it's complicated and that we need some sort of doc explaining this. @isidorn For your case there is a better solution then the workaround we implemented. Instead of constantly re-triggering suggestions your filter text should be `.hello world`, so a merge of the text are going to replace `.hel` and the label of your suggestion `hello world`.
