### ISSUE TITLE
Change the default of the run/debug button in the editor to run

### ISSUE THREAD

**Issue by webreidi** [microsoft/vscode#212919]
Feedback we got from users during our diary study was that the default of the run/debug button in the editor should be Run, as you want to run your program more than you want to debug it. You only want the added weight of the debug session when you need breakpoints to figure out a problem, but you run regularly to check progress. The added click of having to select the arrow to then Run was an extra step that users weren't happy about.

**Comment by webreidi** [comment]
@isidorn This is the run as default issue we talked about today.

**Comment by webreidi** [comment]
@WardenGnaw  yes, as well as the icon change to the Run icon. So, if you don't use the arrow, you run your project.

**Comment by roblourens** [comment]
So this is from the extension, right?

**Comment by webreidi** [comment]
@roblourens No, I spoke with the Java team and the Python team and they all agree that this should be the default for all languages, not just for certain extensions.

**Comment by WardenGnaw** [comment]
@roblourens To clarify this ask. 

Instead of having extensions that contribute debuggers to contribute an additonal contributes.menus.editor/title/run. 
There should be something similar to the `Run` menu dropdown, where it will just execute the debugger associated with the file extension and provide both "Run without Debugging" and  "Start Debugging" options for any file. The existing contributions will be appened after those. 

Proposal: 
![image](https://github.com/microsoft/vscode/assets/3953714/a8ed7023-e888-4cb0-9dba-509ade0dca31)

vscode-java-debug: https://github.com/microsoft/vscode-java-debug/blob/main/package.json#L193-L204
vscode-python-debugger: https://github.com/microsoft/vscode-python-debugger/blob/main/package.json#L113-L125

**Comment by gregg-miskelly** [comment]
Suggestion: I think we should fix this in C# Dev Kit instead of trying to fix this centrally. A central fix is far trickier.

**Comment by isidorn** [comment]
@WardenGnaw @webreidi can you help me understand this better.
So right now you can contribute commands to `contributes.menus.editor/title/run`. You can control the order - so that Run is first and is the default. 

What is exactly missing? Why do you want a general Run, Debug buttons there? If I understand last comment from @WardenGnaw

**Comment by WardenGnaw** [comment]
@isidorn I believe this was a discussion you had with @webreidi to centralize this?

**Comment by isidorn** [comment]
@WardenGnaw 
My understanding was that the main C# user problem is that Run is not the default option in the Editor title area.
I wrongly assumed that extension authors can not control the order of the actions there. But I was wrong, so I would suggest that for now C# DevKit just controls the order of contributed actions, and makes sure Run is first and the default.
