### ISSUE TITLE
Notifications - show which extension they came from

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#21302]
Sometimes notification messages appear, and it isn't clear whether they are from vscode or an extension, and if so, which one. Right now I sometimes see "The internet connection appears to be offline" and don't know which extension is responsible. It would be useful to be able to easily trace the message to an extension, maybe with a tooltip on the message that shows the originating extension's name. It looks like a notification UX overhaul is on the way, #1135.

**Comment by jrieken** [comment]
I like, we already to that for status bar messages

**Comment by jrieken** [comment]
I postpone this until we get the new notification story in place

**Comment by ryh** [comment]
Could you tell us which API for extension can send the message.
some FUNCTION called `showInformationMessage` or just `showInformationMessage` ?

**Comment by jrieken** [comment]
@bpasero Given that this annoys people is there something the message service can do with ease?

**Comment by bpasero** [comment]
@jrieken so for the status bar you were talking about this right?

![image](https://user-images.githubusercontent.com/900690/29417927-1d8b053e-836b-11e7-95b8-a5ccaa91b1b5.png)

Our notification UX needs an overhaul (we started to revisit this recently but it needs more thinking - @stevencl fyi) and so we have only limited amount of things we can do in the UI we have

A couple of ideas
* add another button at the end of each message that comes from an extension to "Manage" that extension (a bit ugly because it makes the whole thing even more complicated)
* prefix the message with the name of the extension (e.g. [TypeScript] bla bla)
* decorate the message in some way that its clear the message is from an extension (maybe with the prefix as stated before):

![image](https://user-images.githubusercontent.com/900690/29418368-6d7e7b6a-836c-11e7-8a3c-da9f8a03ae04.png)

We should do something pragmatic and simple given that this UI is throwaway code anyways.

**Comment by jrieken** [comment]
To begin with, I have added a source attribute that show on hover....

![aug-18-2017 16-57-09](https://user-images.githubusercontent.com/1794099/29464579-93a3960c-8436-11e7-90cd-371f5b2cf007.gif)

**Comment by sandy081** [comment]
@jrieken I think it has to be extension display name instead of extension.name. extension id is nothing but `${publisher_id}.${extension.name}`. Showing extension name again is redundant.

Shall I file a separate issue or reopen this?

**Comment by jrieken** [comment]
@sandy081 Please make we a separate issue, thanks
