### ISSUE TITLE
No way to run a long running computation in a background thread

### ISSUE THREAD

**Issue by coolbluewater** [microsoft/vscode#213098]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. Write a handler for OnDidSaveTextDocument that is cpu intensive and takes several seconds to run

Observe:
The UI thread is blocked during file save.

I've tried several approaches without success:
- Can't use web workers (unsupported)
- Can't use child_process (was unable to get this to work and saw no examples that use this so presume unsupported.)
- Can't use worker_threads (unsupported)

Is there a way to run this task in the background? If not, please add one.
Note: This is a synchronous javascript method that invokes an external library synchronously via FFI.

If there is a way please provide a link to an example. I've spent several days on this.

**Comment by jrieken** [comment]
> The UI thread is blocked during file save.

This cannot be caused by your extension because all extensions run in a separate process, the extension host (EH).Tho, it is also recommended to spawn a separate process or thread for heavy operation (because all extensions share the one EH process). The EH process is normal nodejs process (desktop) or a webworker (vscode-web) and the defaults ways for spawning child processes and/or webworker apply. You can check their documentations or check out the LSP samples which  spawn a process/worker
