### ISSUE TITLE
Cannot paste a tab character at start of TS file

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#213167]
* create a TS file
```
interface X {
}
```
* make sure the file is configured to insert Tabs (from the status bar)
* place a `\t` character in your clipboard
* paste it at the beginning of the file
* :bug: observe nothing happens

```
Version: 1.90.0-insider
Commit: 405ce83a24f38fd70751b03438763a1503329fe0
Date: 2024-05-20T23:10:59.594Z
Electron: 29.3.1
ElectronBuildId: 9464424
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.5.0
```

**Comment by mjbvz** [comment]
This seems related to Auto indent. Setting `"editor.autoIndent": "none"` fixes the issue

**Comment by aiday-mar** [comment]
After investigating, this seems to happen because after pasting a new line character, the code becomes as follows:

```
    interface X {
}
```

The `trigger` method of the `AutoIndentOnPaste` is called and it performs automatic re-indentation. In your case, since there is nothing above that line, the indentation level on that line is zero. The inserted indentation is then removed.

It is possible to see this in more detail in the following example:

https://github.com/microsoft/vscode/assets/61460952/b1a87d44-e8b9-470e-a091-5fe236fbd577

I believe this behavior makes sense when the pasted text contains characters other than whitespace characters. Perhaps what I could do is to not trigger the re-indentation when only whitespace characters are pasted. This could be considered then as intended indentation adjustment.
