### ISSUE TITLE
Change variable object value by double clicking

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#21329]
From #19494, we can edit anything with the context menu, but we can only edit primitives by double clicking. 

![feb-23-2017 20-42-07](https://cloud.githubusercontent.com/assets/323878/23290831/a2f58998-fa08-11e6-9123-8d079f4305bd.gif)

**Comment by isidorn** [comment]
Assigning to march to investigate

**Comment by michelkaporin** [comment]
This is nice, however becomes little bit counter-intuitive when I want to update the details of the object literal. E.g. I have to do an edit and type [1,2,3] to see Array[3] [1,2,3]. However, when I double-click to edit an existing element it brings up Array[3] [1,2,3] as an edit, and I would expect I need to change what's in the square brackets, instead of typing [1,2,3,4] if I want to add 4 to an array.

Example (sorry for numbering):
![object editing](https://cloud.githubusercontent.com/assets/2239563/24446883/680548ba-146f-11e7-81ae-ed0939a77a78.gif)
