### ISSUE TITLE
Intellisense not working on composed function

### ISSUE THREAD

**Issue by harounb** [Microsoft/vscode#21321]
- VSCode Version: 1.9.1
- OS Version: Windows 10 Pro 64-bit

Steps to Reproduce:

1. write a series of functions
2. compose them into a big function (with something like ramda)
3. write jsdocs for composed function with "@function", "@param" and "@return" tags with types
4. export function
5. import and type funcName() the intellisense does not say the correct param type or name or the function description

I have created a repo where you can reproduce:
https://github.com/harounb/vscode-intellisense-issue

**Comment by mjbvz** [comment]
Thank you for the example. The bug is that `thisDoesNot` has a signature of `(x: any) => number`, correct?

Changing the this code like so:

```js
/**
 * @param {number} num
 */
function firstOp(num) {
  return num*2;
}
```

Gives the proper signature of `(x: number) => number` for `thisDoesNot`

It seems that JSDoc annotations cannot override types from `*.d.ts` files currently. I've opened https://github.com/Microsoft/TypeScript/issues/14275 to track this on the TypeScript side

**Comment by harounb** [comment]
Ah great thank you for giving this attention so quickly @mjbvz.
Apologies in advanced for a possibly uninformed question.

Would fixing this typescript bug also fix the param name and param description from the annotation? As well as the function description.

Or is that a separate issue?

My example does highlight the signature being incorrect but there's also these additional quirks.

**Comment by mjbvz** [comment]
I've added a note (https://github.com/Microsoft/TypeScript/issues/14275#issuecomment-282163301) to the TypeScript bug regarding overriding/augmenting the param name and param description as well. That should also be included as part of the fix.

**Comment by harounb** [comment]
Brilliant! Great work, thank you :)
