### ISSUE TITLE
always alert this

### ISSUE THREAD

**Issue by Shen-Yu** [Microsoft/vscode#21336]
![image](https://cloud.githubusercontent.com/assets/13065982/23298325/413ad450-fab8-11e6-850e-7bf57fc9c7fe.png)

- VSCode Version: Code 1.9.1 **[Unsupported]** (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vimStyle|74th|0.4.2|
|html-snippets|abusaidm|0.0.18|
|vscode-color|anseki|0.2.3|
|npm-intellisense|christian-kohler|1.2.1|
|githistory|donjayamanne|0.1.5|
|jquerysnippets|donjayamanne|0.0.1|
|vscode-html-css|ecmel|0.0.33|
|auto-rename-tag|formulahendry|0.0.11|
|live-html-previewer|hdg|0.0.1|
|vue-snippets|hollowtree|0.1.0|
|rest-client|humao|0.12.0|
|path-autocomplete|ionutvmi|1.4.1|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.2|
|debugger-for-chrome|msjsdiag|2.4.2|
|vscode-icons|robertohuertasm|7.1.1|
|background|shalldie|1.1.9|
|code-settings-sync|Shan|2.4.2|
|guides|spywhere|0.6.1|
|vscode-gulp|tanato|0.0.4|
|JavaScriptSnippets|xabikos|1.2.0|

---

Steps to Reproduce:

1.
2.

**Comment by mjbvz** [comment]
Two probable causes:

1. You are opening a mapped network drive This is fixed in TypeSscript 2.2 which is included in VSCode insiders (VSCode 1.10)
1. If you see a message about a missing `typescript/...` file, you may be seeing #20496 in which an antivirus program is deleting our TypeScript implementation. See [this comment](https://github.com/Microsoft/vscode/issues/20496#issuecomment-279518845) for workarounds

If neither seems to fit for what you are hitting, please let me know
