### ISSUE TITLE
Make VSCode's "Search files by name" feature understand Ruby's `::` module separator

### ISSUE THREAD

**Issue by sampart** [microsoft/vscode#213313]
When searching Ruby code, it would be great if VSCode's "Search files by name" feature understood the `::` module separator. This would make searching for files quicker when copying-and-pasting from code.

For example, if I search for `MyModule::SomeClass`, VSCode will return no results. If it instead ignored the `::` when in a codebase with Ruby code (or treated it as a slash?) then it would find `my_module/some_class.rb`. Thanks!

**Comment by andreamah** [comment]
I don't think that this is quite in scope for core vscode- perhaps an extension could be good for this? This seems closer to the symbol search than the 'search files by name'. Although not exactly what you're looking for, you could try toggling `search.quickOpen.includeSymbols`, which will query symbols when you use quick open also.

Otherwise, this seems a bit too specific for something in the core product.
