### ISSUE TITLE
Minimap: scrolling up in large file makes the slider jump a little bit

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#21346]
Steps to Reproduce:

1. macOS with zoom mode 1
2. large file with 30k lines scrolled all the way down
3. use mouse wheel to scroll up

=> at some point the thumb jumps up and then on the next scroll jumps down again
=> the other scrollbar does not show this behaviour

![untitled](https://cloud.githubusercontent.com/assets/900690/23301814/1b88bd20-fa8c-11e6-9734-9921d3b386cf.gif)

**Comment by alexandrudima** [comment]
I've tried to work around this tremor in some cases, but there are still cases where it occurs.

The root cause is:
* the minimap does not render partial lines. i.e. if a line is painted with 2px height, at y = 0 in the minimap there will always be a full line starting
* the viewport renders partial lines
* depending on the scrollTop, the viewport can contain `N` or `N + 1` lines (where the first and last lines are only partially visible)
* in such cases the minimap slider has this tremor.

Very annoying indeed.

**Comment by levani** [comment]
Not sure if it's the same problem but the slider also jumps when dragging by cursor.

![scroll](https://cloud.githubusercontent.com/assets/184472/23830506/a7cc6796-0725-11e7-960e-caec582f989f.gif)

**Comment by jens1o** [comment]
does f5e4e4f4246a70d30c32a6047874da2bbb4417e4 closes this issue?

**Comment by alexandrudima** [comment]
6df8165 should hopefully fix it
