### ISSUE TITLE
Switch workspace setting file from JSON to HJSON

### ISSUE THREAD

**Issue by ripper234** [Microsoft/vscode#21357]
[HJSON](https://hjson.org/) is a better format for JSON files that are meant to be edited/used by humans. Let's use it instead of JSON.

**Comment by roblourens** [comment]
Yaml was also suggested in #4851, which has an explanation of why we're using JSON.

**Comment by ripper234** [comment]
HJSON is not YAML. It's fully backward compatible with JSON.

> Hjson is a syntax extension to JSON. It's NOT a proposal to replace JSON or to incorporate it into the JSON spec itself. It's intended to be used like a user interface for humans, to read and edit before passing the JSON data to the machine.

**Comment by roblourens** [comment]
I know, I just mean that YAML has also been suggested, and the arguments are the same.

**Comment by ripper234** [comment]
I'm not sure the same arguments against YAML really apply here.

> There is a native parser built into the runtime and we care deeply about parsing speed. For example, we parse configuration files during startup.

There is an HJSON parser npm package you can use. Optimization is usually the last reason for a specific solution, I don't think parsing HJSON should prove much more costly, if at all, than parsing JSON.

> json structures are easily described using TypeScript, which is what we write 99% of the tool in. It is "natural" to use json in TypeScript.

So are hjson structures.

> Code itself already has great json tooling (schema, IntelliSense, formatting). This does not mean we won't improve yaml support, I'm just pointing out we've already got this in place.

I believe the same tooling should work for hjson as well almost out of the box.

> Suggesting to support both yaml and json is pragmatic but also means two code paths (bugs, bloat) and two sets of docs to maintain long term, something we would like to avoid.

I'm not suggesting that. Just support hjson (which is a superset of json).

**Comment by roblourens** [comment]
FYI @chrisdias

**Comment by ripper234** [comment]
Thanks for tagging @chrisdias . Could we reopen this issue until he responds?

**Comment by chrisdias** [comment]
@ripper234 thanks for the suggestion!

We discussed and have decided to stay with JSON, despite the limitations. Many of the same reasons apply as in #4851. Of utmost importance is parsing speed because we read a lot of json on startup, and the runtime has a native json parser built in - no dependencies, no module loading.  Another point that was brought up in the discussion was that if anyone wants to interop with us then they have to adopt HJSON which is a speed bump we don't want to introduce.

We recognize that the readability and editing of JSON can be challenging at times, but as you can see with the work we've been doing with [settings](http://code.visualstudio.com/updates/v1_8#_settings), we're trying to improve the user experience while keeping the underlying format.

Thanks again for the suggestion, it drove a good debate, please keep them coming.

**Comment by ripper234** [comment]
Thanks for the thorough discussion & answer 👍
