### ISSUE TITLE
ATA does not work for libraries shipped with their own typings with es6 target

### ISSUE THREAD

**Issue by alisabzevari** [Microsoft/vscode#21356]
- VSCode Version: 1.9.1
- OS Version: Ubuntu 16.10

Steps to Reproduce:

1. Create an npm project
2. install a library that ships with its own typings like `mobx-react`
3. create a `jsconfig.json` like this:
``` json
{
  "compilerOptions": {
    "target": "es6"
  }
}
```
Note that the `"target": "es6"` is important.

**Expected behavior:**

have intellisense for `observer` in this code:
``` js
import { observer } from 'mobx-react';

observer();
```

**Actual behavior:**

Does not work!

**Note** that I found out it is related to `target` in `jsconfig.json`. If you remove target, it will work.

**Comment by mjbvz** [comment]
Switching to `es6` also changes the `module` setting that TypeScript uses to `es6`: https://www.typescriptlang.org/docs/handbook/compiler-options.html

If I instead use:

```json
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es6"  
    }
}
```

Then I see intellisense work as expected. I believe this is by design for how the `mobx-react` types file is specified. I do see include typings files work for other packages. 

If you're working in TypeScript, well surface an error about not being able to fine the module. We are also actively working on providing errors and warnings in JavaScript files.


Let me know if that works for your project or if you feel that the existing behavior is incorrect.

Thanks

**Comment by alisabzevari** [comment]
@mjbvz Thanks. I think you are right and it is not a bug.
