### ISSUE TITLE
Aux window does not work in Firefox

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#213645]
Testing #213597

* linux VM
* FF browser `122.x`
* F1 > Report Issue
* :bug: only a blank window opens, the main window shows the error below in its console

```
Uncaught (in promise) TypeError: ct.document is undefined
    m dom.ts:1295
    ot dom.ts:1301
    xe dom.ts:1357
    u button.ts:172
    o issue.ts:88
    y issueReporterService.ts:31
    o instantiationService.ts:162
    createInstance instantiationService.ts:128
    openAuxIssueReporter issueFormService.ts:121

```

<img width="1688" alt="Screenshot 2024-05-28 at 11 49 08" src="https://github.com/microsoft/vscode/assets/1794099/b4fa472e-2d22-42df-ba75-d6207f5b0688">

**Comment by jrieken** [comment]
@bpasero This might be a general FF issue, moving an editor into a new window also fails

**Comment by jrieken** [comment]
The same happens with latest FF (126) on macOS

**Comment by bpasero** [comment]
Just to clarify: maybe its easier to fix for the issue reporter because that one is more scoped to a smaller set of problems. We could start adding those utility methods for the issue reporter and then see whats remaining for the floating windows.

But I think adopting this through our code is quite a thing, and we would need methods for basically each kind of HTML element + lint rules to prevent this from being called...

**Comment by justschen** [comment]
@bpasero I'm assuming it would be something along the lines of:

```typescript
export function isHTMLElement(e: unknown): e is MouseEvent {
	// eslint-disable-next-line no-restricted-syntax
	return e instanceof HTMLElement || e instanceof getWindow(e as Node).HTMLElement;
}

export function isTextAreaElement(e: unknown): e is HTMLTextAreaElement {
	// eslint-disable-next-line no-restricted-syntax
	return e instanceof HTMLTextAreaElement || e instanceof getWindow(e as Node).HTMLTextAreaElement;
}

....

```

how would this be used in the context of the issue reporter since I'm just calling `this.auxiliaryWindowService.open()....`?

**Comment by bpasero** [comment]
Yeah you are likely using a `dom.ts` or similar utility function that does an `instanceof` check, we would need to adopt it gradually through the usages.

**Comment by justschen** [comment]
gotcha, I see that now. I'l add the ones I am checking to `dom.ts` for now and we can see what other actions we need later if it works nicely with the issue reporter. if you'd like help with other non-issue reporter scenarios, let me know as well!

**Comment by justschen** [comment]
to clarify, would something like this be a cause of this as well?

```typescript
<HTMLInputElement>this.getElementById('issue-title')
```

**Comment by bpasero** [comment]
I think there are actually more issues, I did some testing with most instanceof checks doing it the other way and the issue reporter is not styled:

![image](https://github.com/microsoft/vscode/assets/900690/05fc2f9a-80f9-4717-a3f0-34902592fc5a)

And floating windows open and then quickly close again :-/

**Comment by justschen** [comment]
:( maybe just for firefox for now I'll disable the aux window issue reporter this while we investigate

**Comment by bpasero** [comment]
I am actually wondering if its just not possible to create DOM nodes in the main window and append them into the child window, because I do not see any DOM nodes appearing in the child window. 

We explicitly decided against creating DOM nodes using the target window because it complicates instance of checks.

Anyway, as a mitigation I would disable the window based issue reporter when in Firefox.

**Comment by bpasero** [comment]
I found a way 🚀 🎸
