### ISSUE TITLE
Broken Shortcut for "Toggle Editor Group Layout"

### ISSUE THREAD

**Issue by WillDeJs** [Microsoft/vscode#21365]
Trying to learn more on the features of VSCode, I attempted to toggle the editor group layout using its shortcut and found that it does not work. On the other hand, the action is successfully executed when done from the View menu in the menubar. Other shortcuts using the same keys separately work just fine in my computer which assures me that my keyboard is working properly.

- VSCode Version: 1.9.1
- OS Version: Windows 7 Professional SP1

Steps to Reproduce:

1. In an open instance of VSCode click  "View" from the menu bar.
2. Select option "Toggle Editor Group Layout  Alt+Shift+1" notice how the view group layout toggles between horizontal and vertical.
3. Attempt to execute the previous action by using the listed shortcut "Alt+Shift+1". Notice how it does not toggle the editor group layout.

**Comment by bpasero** [comment]
Works for me on Windows 7 when pressing Alt+Shift+1. 

I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by WillDeJs** [comment]
Thanks for taking the time to look into it. I mistakenly assumed the "1" in the shortcut referred to the numeric keypad. It does work with or without extensions using the "1" located in the alphanumeric keyboard.
