### ISSUE TITLE
Text synthesis stops when bluetooth profile switches

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#213640]
Testing #213355

E.g., here it only read "Sure!" and then stopped:
![Image](https://github.com/microsoft/vscode/assets/9205389/67cef325-1108-4f09-b274-5f4929921008)

When I then press the speaker icon, it reads the entire text.

**Comment by chrmarti** [comment]
Here it initially didn't read anything:
![Image](https://github.com/microsoft/vscode/assets/9205389/b780dfb7-2611-4db4-87e4-aa9857dd45e0)

**Comment by bpasero** [comment]
Seems to happen in inline chat, but not panel chat. Here only the first half was read out aloud:

![image](https://github.com/microsoft/vscode/assets/900690/99f15fc3-0da4-4a88-b21e-b400c0c46421)

**Comment by bpasero** [comment]
@chrmarti is it possible you did this with microphone such as AirPods connected to the machine and could you try using just the built-in microphone and speakers?

I have a theory that this is what happens, only when using a external microphone such as AirPods:
* you use voice to input to the prompt via bluetooth connected microphone
* this switches bluetooth profile for playback from high-fidelity to lower to reduce bandwidth cost (you can tell this happens when you play music at the same time and it suddenly sounds distorted)
* when prompt response comes in, voice recognition is stopped
* it seems to take 5-10 seconds for the bluetooth profile to switch back to high fidelity
* the speech synthesis seems to cut off right when the profile changes

I am not sure if above is true and if this is something we can fix on our end.

**Comment by chrmarti** [comment]
You're right, it works with the built-in microphone. One thing I now noticed (and might be related) is that with the bluetooth headphones I don't hear it go back to high fidelity (music playback stays low quality) until I reload the window. There is also a 'open mic' indicator on the window, so I guess it doesn't really stop.
