### ISSUE TITLE
Extensions: update patch doesn't show immediatly for locally installed extension

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#21375]
Verifying #17290

- download https://github.com/Microsoft/vscode-eslint/files/630866/vscode-eslint-1.2.0.zip and rename to `vscode-eslint-1.2.0.vsix`
- run `code-insiders --install-extension ./vscode-eslint-1.2.0.vsix`
- run vscode-insiders. The extensions view shows in the extensions viewlet, but with the old version
![image](https://cloud.githubusercontent.com/assets/6461412/23310270/4a98f690-fab2-11e6-90dd-e805db5544e3.png)
- enter 'eslint' in the filter box. Now the update button appears
![image](https://cloud.githubusercontent.com/assets/6461412/23310318/74c813f6-fab2-11e6-856d-ee19d9127363.png)

**Comment by sandy081** [comment]
Good catch

**Comment by roblourens** [comment]
Still reproes for me using the original steps

**Comment by sandy081** [comment]
@roblourens Thanks for validating it. There were some changes went in between which broke this. We had a workaround to query for both ids and names of extensions (instead of just names) to sync with gallery. Seems like  only ids are respected but not names. In this case, vsix extension will not have id so it is not getting synced.

Above work around was introduced until Marketplace accepts case-insensitive names as queries. This got fixed in Market place. Removing the workaround fixes this issue.
