### ISSUE TITLE
other comments on documentation

### ISSUE THREAD

**Issue by eleanorjboyd** [microsoft/vscode#213724]
Testing #213514

if I was beginning this process on my own I think I would have trouble with the `const MODEL_SELECTOR: vscode.LanguageModelChatSelector = { vendor: 'copilot', family: 'gpt-3.5-turbo' };`. I found [in the docs](https://code.visualstudio.com/api/extension-guides/language-model#send-the-language-model-request) where it describes the only options but this still feel confusing to me bc it took a while to get to this point, it is confusing what type such as "vendor" means and I am unsure how to stay up to date so my chat requests do not get messed up in future releases as more models come out.

when looking through [this doc](https://code.visualstudio.com/api/extension-guides/language-model#considerations) I would love to see something about security. I found the whole page [here](https://resources.github.com/copilot-trust-center/) but it was unclear how these connected and I feel like with this "security first" mindset they talked about a ton at build it might be worth putting something more central about it?

**Comment by roblourens** [comment]
I think we can do a better job of explaining the different selector fields, I will propose something.

> I am unsure how to stay up to date so my chat requests do not get messed up in future releases as more models come out.

This is no easy answer here- you can write a loose selector that will run your prompts against future models that you haven't tested with, or a more specific selector that will stop working at some point, and then you need to update your extension.

This is sort of mentioned in https://code.visualstudio.com/api/extension-guides/language-model#model-availability, but lmk if you think there's something else we should say.

What aspect of security do you think we should mention? Since the System prompt isn't available to extensions, that is one consideration that extensions don't have to make.

**Comment by AP1400** [comment]
I now what are you talking about  also  inow its   so easy but what i get
when  i tell you can i have access to my 15%of my shares, assets  or
anything  you call it

**Comment by roblourens** [comment]
Well actually, the `LanguageModelChatSelector` fields link to the `LanguageModelChat` fields that have a little more description, and I think that's enough. These fields don't really have a strict definition. But I did add another note on how to use `selectChatModels` in https://github.com/microsoft/vscode/pull/213867, hoping it helps.

**Comment by jrieken** [comment]
Closing this as resolved
