### ISSUE TITLE
Panel visibility is not persisted/restored on vscode.dev after restart

### ISSUE THREAD

**Issue by yiliang114** [microsoft/vscode#213885]
1. Open `https://vscode.dev/`
2. Open Termial or other Panel like this
3. ![image](https://github.com/microsoft/vscode/assets/11473889/0cf10ddc-fa03-41e4-9b0c-e1ff022b7575)
4. Use `cmd + r` to refresh the page, click the confirmation pop-up box, and refresh to find that the panel is open at this time (the status is recorded)
5. Then close the panel and click the refresh button in the address bar directly. after the refresh, it is found that the panel has not been closed  (the status is not recorded).

![reload1](https://github.com/microsoft/vscode/assets/11473889/a2740681-6eeb-4e4b-8a91-e94dedcb4204)

Version: 1.89.1
Commit: dc96b837cf6bb4af9cd736aa3af08cf8279f7685
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36
Embedder: vscode.dev

**Comment by bpasero** [comment]
As it turns out, the layout was not flushed every 5 seconds to state as we do in other cases:

https://github.com/microsoft/vscode/blob/fca05df7d4a9ce627919af8cd9fc3a3f2e14e029/src/vs/workbench/browser/layout.ts#L1537

Changing that to be included in the flush should fix this, at least as long as you do not reload before 5 seconds have passed.
