### ISSUE TITLE
在过去

### ISSUE THREAD

**Issue by xiaoxi1227** [Microsoft/vscode#21388]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.10586
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-icons|robertohuertasm|7.2.0|

---

Steps to Reproduce:

1.警告：在过去5分钟内，TypeScript语言服务意外终止了5次

**Comment by mjbvz** [comment]
Two probable causes:

1. You are opening a mapped network drive This is fixed in TypeSscript 2.2 which is included in VSCode insiders (VSCode 1.10)
1. If you see a message about a missing `typescript/...` file, you may be seeing #20496 in which an antivirus program is deleting our TypeScript implementation. See [this comment](https://github.com/Microsoft/vscode/issues/20496#issuecomment-279518845) for workarounds

If neither seems to fit for what you are hitting, please let me know and we can reopening this to investigate further
