### ISSUE TITLE
Terminate an task by keyboard

### ISSUE THREAD

**Issue by SeeeD** [Microsoft/vscode#214]
Actually I can start a gulp task by the shortcut [ctrl]+[shift]+[b]. Sometimes I wan't to restart this task by using this shortcut again. When I do this, a dialog is warning me because there is already a task running and it must stopped before. But to do this I have to move the mouse and this is uncomfortable. 

Can you create the ability to confirm this by pressing [enter] or [space]? Alternatively another shortcut for stopping the task would be great too!

This is more like a feature request - I hope it is still ok to post it here. 

Regards

**Comment by m-sanders** [comment]
Being able to ctrl+c to kill a task would be great too.

**Comment by Tyriar** [comment]
The command `workbench.action.tasks.terminate` (F1 -> type "term") exists for this already. Not sure whether a discussion has been has on whether it should be a default keybinding or not.

**Comment by dbaeumer** [comment]
@Ctrl+C is copy in and editor. To not make this too context dependent I didn't bind Ctrl+C. It would only work in the Output Task Window and you might want to copy text there as well.

I can check if Ctrl+Shift+C is available.

**Comment by dbaeumer** [comment]
I opened https://github.com/Microsoft/vscode/issues/5538 for the general request of confirming a message box with the keyboard. 

I looked for a free keyboard shortcut but it is very hard to find one that makes sense (for example Ctrl+Shift+C and Ctrls+Shift+X are taken)

Since you can bind your own keyboard short cut I suggest doing this (File -> Preferences -> Keybroad)
