### ISSUE TITLE
Allow code-serve to start with a github token

### ISSUE THREAD

**Issue by PixNyb** [microsoft/vscode#214089]
I've been using code-serve local for a while and even though i'm authenticated with the gh cli and have a github token available in the cli, there's no way to pass it on to vscode to make it automatically log in to github. This results in me having to log in manually every time i set up a new instance.

**Comment by aeschli** [comment]
@alexr00 Does the Github extension pick a token from the environment?

**Comment by alexr00** [comment]
@TylerLeonhardt would know best if the GitHub Authentication extension can do this.

**Comment by connor4312** [comment]
Can you confirm the `code serve-local --version` you're using?

**Comment by PixNyb** [comment]
Hello everyone! Glad to see some activity on this. I've made an error in my original request which is that i use the `code serve-web` command rather than the old one. I primarily use it to host some dockerised instances of vscode. The images get packaged with the latest version of code (and insiders).

The latest image has vscode version 1.89.1:

```console
$ code -v
1.89.1
dc96b837cf6bb4af9cd736aa3af08cf8279f7685
x64
```

**Comment by connor4312** [comment]
You mention setting up a new instance. Credentials are stored in the browser, but require a server-side key to decrypt as an extra layer of security. The server side key is stored in the file keychain by default, but you can reuse it by setting two environment variables:

- `VSCODE_CLI_USE_FILE_KEYRING=1` will cause it to be stored in the ~/.vscode/~/.vscode-insiders folder instead of in the system keychain
- `VSCODE_CLI_DISABLE_KEYCHAIN_ENCRYPT=1` will avoid obfuscating that file with machine-specific information, allowing it to be reuse if you share the folder between e.g. multiple containers

See https://github.com/microsoft/vscode-remote-release/issues/8358 for further discussion

**Comment by PixNyb** [comment]
This wasn't really what i was getting at. I don't want to share credentials across clients but rather have it provision the github module with a token that's available on startup. The gh cli is installed and logged in so in my logic that would be enough to have vscode sign in to github? I don't want another layer of authentication to go through in order to access various github features (pull requests, issues, copilot etc.)

**Comment by connor4312** [comment]
That's more @TylerLeonhardt's area to weigh in, but I would not think that's something we want to do because there's a lot of things that need to happen correctly and they're not all tractable

- You need to pass both the access token and the scopes it has (Github does not have an introspection endpoint)
- The token is likely not for VS Code's app ID. Some scenarios require the token be minted for a specific (VS Code's) application ID.
- If the scopes the token happened to be minted with are different than extension X requires, we need to ask for a new token anyway.

**Comment by PixNyb** [comment]
Ah alright, i understand. Thanks for the insights!

**Comment by TylerLeonhardt** [comment]
I was having deja vu reading this issue... and then realized, this is already tracked with https://github.com/microsoft/vscode/issues/191861

The work is mostly there, actually AFAIK.

As for "auto-detecting `gh` and pulling tokens out of it... Connor brought up my concerns as well around that. I don't think that's the right direction we wanna go at this time.

**Comment by PixNyb** [comment]
Ah that's great, just what i was looking for. Pulling tokens out of gh cli wasn't necessarily what i was looking for. I have the github token available when starting vscode outside of gh cli!
