### ISSUE TITLE
When user settings is opened, focus should default to search input

### ISSUE THREAD

**Issue by dakaraphi** [Microsoft/vscode#21429]
Almost every time I open user settings, I'm going to search for a command.  It would be a better flow if the focus would default to the search input box.

**Comment by sandy081** [comment]
Not sure everybody has this flow. Users also open settings to edit which needs focus to be in editable settings editor. IMO the right flow is

- By default focus the editable settings editor
- A key binding to focus search box.

This is the common flow when an editor is opened and user wants to find for something.

**Comment by roblourens** [comment]
@sandy081 I don't like binding cmd+f to focus the search box, because I have a large settings file in no particular order and I like to search within it. Unless we plan to filter settings.json based on the settings file as well, maybe we should pick a different default for this command?

**Comment by dakaraphi** [comment]
I would prefer defaulting to the search box and just hitting tab to jump focus to the editable settings editor.  Probably would be even more ideal if both views were filtered by the search box.

**Comment by sandy081** [comment]
@roblourens Search functionality in Settings editor searches across Default (LHS) and editable (RHS) settings. So, you could be able to still find in settings.json using Search functionality. I know the find widget supports much advanced functionality like Match case, Reg ex etc, but I think this is not very commonly used and Search will support all basic requirements. Please let me know if you are missing something there so that I can look at it.

This functionality makes it consistent across LHS and RHS settings editor. 

FYI: If you do not want to open the full settings editor you can disable it using the setting ` workbench.settings.openDefaultSettings`.

@dakaraphi IMO majority of the use cases, users would like to edit settings editor rather than searching. Hence, I focussed the settings editor by default. I would wait to get more feedback to see if this is not the case to switch.

Thanks

**Comment by roblourens** [comment]
Ok, I hadn't noticed exactly how it worked. I also can't search settings values now, only names. I think that's ok though. I opened https://github.com/Microsoft/vscode/issues/22159 and https://github.com/Microsoft/vscode/issues/22157 which would make it much more usable for me. Would be awesome to have a solution for https://github.com/Microsoft/vscode/issues/17129 too.

**Comment by jrieken** [comment]
verified cmd+f focuses the search field
