### ISSUE TITLE
Add focusResults option to Search Editor

### ISSUE THREAD

**Issue by mkasenberg** [microsoft/vscode#214369]
If the Search Editor has been opened from the search view ("Open in editor" button) then the focus is moved to the Search Editor results, like this:

![usecase1](https://github.com/microsoft/vscode/assets/37016009/7d651bde-b817-4a46-97fd-0c8a236a0624)

I would like to have an option that would allow to set where the focus(cursor) should be moved, to the Search Editor results or to the Search Editor input.

Fixed with https://github.com/microsoft/vscode/pull/205914

**Comment by andreamah** [comment]
Verification steps:

1. Make a search in the search view.
2. `Open in editor` from the results.
3. Verify that the focus is in the text input element in the search editor after the search in the search editor is done loading. 
4. Run another search in the search editor. It should focus in the input element when the search is done again (if not focused there before).
5. Now, set `search.searchEditor.focusResultsOnSearch` to true.
6. Verify that, after repeating steps 1-4, the cursor/focus is in the results (editor) part of the search editor instead of the input.

**Comment by rzhao271** [comment]
Thanks for the clear verification steps!
