### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by tangtanglove** [Microsoft/vscode#21436]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|laravel-5-snippets|atefth|0.0.1|
|path-intellisense|christian-kohler|1.2.0|
|jquerysnippets|donjayamanne|0.0.1|
|python|donjayamanne|0.5.8|
|vscode-html-css|ecmel|0.0.33|
|mithril-emmet|FallenMax|0.6.1|
|launcher|ilich8086|0.0.4|
|Seti-theme|TsumiNa|0.0.1|

---

Steps to Reproduce:

1.
2.

**Comment by dragfire** [comment]
What is the bug?

**Comment by tangtanglove** [comment]
when i open js file with vscode ,vscode Allways alert waring “在过去5分钟内，typescript 语言服务意外中止了5次”

**Comment by tangtanglove** [comment]
i'm from china

**Comment by mjbvz** [comment]
Two probable causes:

1. You are opening a mapped network drive This is fixed in TypeSscript 2.2 which is included in VSCode insiders (VSCode 1.10)
1. If you see a message about a missing `typescript/...` file, you may be seeing #20496 in which an antivirus program is deleting our TypeScript implementation. See [this comment](https://github.com/Microsoft/vscode/issues/20496#issuecomment-279518845) for workarounds

If neither seems to fit for what you are hitting, please let me know and we can reopening this to investigate further
