### ISSUE TITLE
BUG: when in `argv.json` add `"disable-lcd-text": true,` colors are degraded

### ISSUE THREAD

**Issue by psnet** [microsoft/vscode#214439]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.90.0 (user setup)
Commit: 89de5a8d4d6205e5b11647eb6a74844ca23d2573

Steps to Reproduce:

![зображення](https://github.com/microsoft/vscode/assets/1023918/4ee3f786-356a-4cdd-a50c-c40d1db8b4c7)

![зображення](https://github.com/microsoft/vscode/assets/1023918/83190bee-e1b5-472f-af67-1b376857eb56)

**Comment by rzhao271** [comment]
@psnet the behaviour is as expected because disable-lcd-text disables RGB subpixel rendering and replaces it with greyscale subpixel rendering. I can add that detail to the release notes in the meantime.

If you want subpixel rendering off in general, let me know if the recommendation to disable ClearType from https://github.com/microsoft/vscode/issues/195256#issuecomment-2093143057 works for you.

**Comment by psnet** [comment]
Hi @rzhao271 thanks for explain, in general I dont want to disable ClearType in windows, but asking if we can achieve functionality of `"disable-lcd-text": true,` with same color saturation (see screenshots above)?

**Comment by rzhao271** [comment]
@psnet the current behaviour is as-designed. I'm not sure what you mean by achieving functionality of `"disable-lcd-text": true`. If you want colour saturation, you can choose not to add it to `argv.json`.

**Comment by psnet** [comment]
@rzhao271 Ok, thanks for explanation.

Issue not relevant anymore.
