### ISSUE TITLE
Cannot indent properly 

### ISSUE THREAD

**Issue by ahmetb** [Microsoft/vscode#21453]
```
{
  "steps": [
    {
      "name": "foo",
      "id": "A"
    },
    {
      "name": "bar",
      "id": "B",
      "waitFor": [
        "-"
      ]
    },
    {
      "name": "baz"
    }
  ]
}
```

This is an all-spaces JSON file, if I select-all and hit Tab key once:

```
    {
    "steps": [
        {
        "name": "foo",
        "id": "A"
        },
        {
        "name": "bar",
        "id": "B",
        "waitFor": [
            "-"
        ]
        },
        {
        "name": "baz"
        }
    ]
    }
```

Note how the last ] and } are at the same indent. Not quite what I expected.

**Comment by Splike** [comment]
This is because your tab length is not equal to 2.

In the first code snippet you gave, the tab length is 2 spaces.
But if you have set you tab length to something larger, e.g. 3, then selecting everything at hitting tab will align the "]" and "}" at the bottom, placing them at the 3rd character.

I suggest that you set `"editor.renderIndentGuides": true` in the settings, so You can easily see your tab length, and that it doesn't match up with the given code.

**Comment by ahmetb** [comment]
@Splike I have `"editor.renderIndentGuides": true` and my tab length is indeed 4. However this does not match my expectations. When I select text and hit Tab, I am saying indent all these lines by  my $tabLength no matter what. So I guess vscode doesn't work that way.

It appears like `"editor.detectIndentation":true` kind of solves my problem, I guess I'll stick with that for now.
