### ISSUE TITLE
Output Window: Setting to Stop Wrapping

### ISSUE THREAD

**Issue by pmcoz** [Microsoft/vscode#21468]
- VSCode Version: 1.9.1
- OS Version: Win 7/64 Home Premium SP 1

Please introduce a setting (ideally changeable via API) to allow an output window (panel) to NOT word-wrap.

Reason: I've modified the TODO Parser extension (https://marketplace.visualstudio.com/items?itemName=minhthai.vscode-todo-parser) to write its output in tabular form, which is more concise length-wise. However, the unavoidable word wrapping in the output window usually messes up the formatting. In such cases, it would be preferable for an extension to be able to open an output window that DIDN'T word wrap, and allowed the user to scroll horizontally if required.

This suggestion was mentioned as an aside at https://github.com/Microsoft/vscode/issues/2806#issuecomment-191361158.

**Comment by isidorn** [comment]
This should be possible using language specific settings
"[Log]": {
    "editor.minimap.enabled": false
}

**Comment by gondwanasoft** [comment]
I think this issue was closed in error. It is not about the minimap, and changing minimap settings does not affect the output window's wrapping. This doesn't make any difference either:
"[Log]":{"editor.wordWrap": "off"}
Here's an image of the output window as it currently behaves with a single long line of text. I'd like the option to have this displayed as one line with scrollbar.
![outputwrapped](https://user-images.githubusercontent.com/29833658/32968451-59f96660-cc35-11e7-8508-a97927cb7bc8.png)

**Comment by gondwanasoft** [comment]
Thanks for reopening. :)
