### ISSUE TITLE
Guidance for transferring ownership of extension

### ISSUE THREAD

**Issue by mat-mcloughlin** [Microsoft/vscode#21478]
Hey guys,

Not sure if this the best place to post this but there doesn't seem to be any instructions or guidance on how to transfer ownership of an existing extension?

The extension in question is https://marketplace.visualstudio.com/items?itemName=mjmcloug.vscode-elixir

Is this even possible?

**Comment by seanmcbreen** [comment]
Hi,

There are really two approaches, both are not 100% ideal but I'll share them here:

1. Ask `mjmcloug` to give you permission to publish the extension (this is possible through the marketplace management experience).  For example we regularly publish the `lukehoban.go` extension on Luke's behalf.  The upside here is all of the metadata for the extension remains intact (download count, rating, ...) the downside is that you can publish as `mjmcloug` and that may not be desirable.

2. Deprecate the existing extension by publishing an update and point users to the next extension.  This is something we did for `editorconfig` and `sql`.  The pros here are that you get a fresh new identity and total control of publishing.  The downside is some customer action is required and the metadata is lost.

Here is an example of how the second option worked for SQL.

...
<snip>
We just published an update to the vscode-mssql prototype on the VS Code Marketplace. This is what users will see when they search for ‘mssql’ on the VS Code Marketplace.

![Uploading image.png…]()

Existing users who have already installed the `vscode-mssql` extension will see a prompt from VS Code telling them there’s a new version of the extension. After they upgrade to v0.0.5 of ‘vscode-mssql’, VS Code will show the info message below each time the extension is activated:
 
![Uploading image.png…]()

* Clicking ‘Go to VS Code Marketplace’ takes them to our official extension on the VS Code Marketplace here: https://marketplace.visualstudio.com/items?itemName=ms-mssql.mssql
*Clicking ‘Close’ dismisses the info message
 
In either case, v0.0.5 of the `vscode-mssql` extension will not add any “MSSQL” commands to the VS Code command palette with this update.

We’ve added a note saying the source code is still available on github in case the community wishes to fork or copy/paste: https://github.com/sanagama/vscode-mssql
</snip>

I'll close this for now - but fell free to re-open if you have additional questions.
Sean

**Comment by mat-mcloughlin** [comment]
@seanmcbreen hey mate, thanks for this. Because I'm obviously being blind can you please link me to the marketplace management experience page please as I don't know where I'm looking for it

**Comment by seanmcbreen** [comment]
Hey sorry I missed this - doh.

Here you go:
https://marketplace.visualstudio.com/manage

This should (once authenticated) take you to a page to manage extensions.  Since we normally use the CLI this is not well documented for VS Code sorry.

![image](https://cloud.githubusercontent.com/assets/1051190/23681935/00f7422a-0346-11e7-9013-352974c2aed6.png)

From here click on your publisher name and select `edit publisher`
![image](https://cloud.githubusercontent.com/assets/1051190/23681959/21a73ab6-0346-11e7-9a61-323d35aa54e7.png)

> **Note:** I've moved to my publisher for this screen shot not the Microsoft one in the screens above.

Under `Roles` you can add additional users and give them publish access.  You need to use the login that the user will have for VSTS.  They will also need to have created a Personal Access Token for that account with access to all accounts.

![image](https://cloud.githubusercontent.com/assets/1051190/23682006/64ef4fe8-0346-11e7-8b50-823c209bdd7f.png)

After that they can log-in via the VSCE CLI i.e. `vsce login seanmcbreen` then they should enter their Personal Access Token for the account you mapped.

Then `vsce publish` and `vsce unpublish` should work.

With that you should be good to go.  LMK if I can clarify any more.
Sean
