### ISSUE TITLE
Auto Suggestion and IntelliSense Not Working in VSCode

### ISSUE THREAD

**Issue by Ahmed82232** [microsoft/vscode#214731]
Type: <b>Bug</b>

Steps to Reproduce:
Open Visual Studio Code.
Open a project file (e.g., Dart/Flutter or any relevant language).
Start typing code where IntelliSense and auto suggestions should appear.
Expected Result:
IntelliSense and auto suggestions should appear automatically as I type, providing code completions and suggestions.

Actual Result:
No auto suggestions or IntelliSense pop-ups appear.

VS Code version: Code 1.90.0 (89de5a8d4d6205e5b11647eb6a74844ca23d2573, 2024-06-04T19:33:54.889Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (7.71GB free)|
|Process Argv|--crash-reporter-id 8f2f3683-673c-4f10-bea1-93b407f476de|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
codesnap|adp|1.3.4
project-manager|ale|12.8.0
blackbox|Bla|1.3.57
path-intellisense|chr|2.9.0
dart-code|Dar|3.90.0
flutter|Dar|3.90.0
xml|Dot|2.5.1
vsc-material-theme-icons|equ|3.6.0
prettier-vscode|esb|10.4.0
bloc|Fel|6.6.6
path-autocomplete|ion|1.25.0
flutter-intl|loc|1.19.3
python-path|mge|0.0.14
debugpy|ms-|2024.6.0
python|ms-|2024.8.0
vscode-pylance|ms-|2024.6.1
material-icon-theme|PKi|5.3.0
dtl|rea|1.5.0
java|red|1.31.0
dtl|syn|0.1.0
vscode-gradle|vsc|3.13.5
vscode-java-debug|vsc|0.57.0
vscode-java-dependency|vsc|0.23.6
vscode-java-pack|vsc|0.27.0
vscode-java-test|vsc|0.41.1
vscode-maven|vsc|0.44.0
vscode-icons|vsc|12.8.0
json|Zai|2.0.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelc:31048052
dsvsc021:30996838
01bff139:31013167
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
pythonprt:31056678
dwnewjupyter:31046869
newcmakeconfigv2:31067619
26j00206:31048877

```

</details>

**Comment by fabioh8010** [comment]
having the same issue

**Comment by jrieken** [comment]
It looks like the issue is caused by one of your installed extensions. All extensions execute together on a single nodejs process, so in order to narrow down the possible problematic extension, please try the following:
* run `F1 > Help: Start Extension Bisect`
* (this will restart VS Code with half of your extensions disabled)
* try to do the steps which reproduce the problem
* if the problem reproduces, click "This is bad" (this narrows down the problematic extension to the half which was enabled)
* if the problem does not reproduce, click "Good now" (this narrows down the problematic extension to the half which was disabled)
* these steps will repeat until the problematic extension is found

| initial | step | final |
|---|---|---|
| ![image](https://user-images.githubusercontent.com/5047891/101918658-e9170f80-3bc9-11eb-9977-857baa291937.png) | ![image](https://user-images.githubusercontent.com/5047891/101918683-ef0cf080-3bc9-11eb-9f9e-98b0177991b2.png) | ![image](https://user-images.githubusercontent.com/5047891/101918706-f502d180-3bc9-11eb-8c86-e56355958bd4.png) |

**Comment by fabioh8010** [comment]
I did the bisect and the problem still happens even with all extensions disabled. For me it seems to be happening only in a specific project of mine, the others is working normally. How can I further debug this?
