### ISSUE TITLE
Unable to edit code/write code on visual studio code editor...please help

### ISSUE THREAD

**Issue by sammpathkummar** [Microsoft/vscode#21473]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 6.2.9200
- Extensions:

|Extension|Author|Version|
|---|---|---|
|Angular2|johnpapa|2.0.3|
|csharp|ms-vscode|1.7.0|
|debugger-for-chrome|msjsdiag|2.5.4|
|vim|vscodevim|0.5.3|

---

Steps to Reproduce:

1.
2.

**Comment by bpasero** [comment]
@sammpathkummar more info please

**Comment by sammpathkummar** [comment]
1) Created an Ionic project from cmd level.
2)Open that project folder in visual studio code.
3)when i am trying to edit any file, i am unable to able edit.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by sammpathkummar** [comment]
Please may i know how to fix     "Version mismatch! global tsc (2.2.1) != VS Code's language service (2.1.6). Inconsistent compile errors might occur".

![howtofix](https://cloud.githubusercontent.com/assets/13055046/23441115/41e3dd2e-fe5b-11e6-96bc-bb7ea00c389f.png)


Thank you

**Comment by bpasero** [comment]
@sammpathkummar is that with using our insiders build?

**Comment by jordanmkasla2009** [comment]
> Please may i know how to fix "Version mismatch! global tsc (2.2.1) != VS Code's language service (2.1.6). Inconsistent compile errors might occur".

This issue is present with the production version.
- VSCode Version: Code 1.10.0 (49129d126e2c3c5592cfc8a509d872067b69d262, 2017-03-01T15:59:13.140Z)
- OS Version: Windows_NT ia32 10.0.14986
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|vscode-theme-onedark|akamud|1.3.1|
|vscode-eslint|dbaeumer|1.2.7|
|python|donjayamanne|0.5.8|
|EditorConfig|EditorConfig|0.3.4|
|tslint|eg2|0.8.1|
|cpptools|ms-vscode|0.10.1|
|csharp|ms-vscode|1.7.0|
|debugger-for-chrome|msjsdiag|2.5.5|
|vscode-docker|PeterJausovec|0.0.12|
|vscode-icons|robertohuertasm|7.3.0|
|sass-indented|robinbentley|1.3.0|
|Material-theme|zhuangtongfa|2.0.4|;

---

Steps to Reproduce:

1. Install the latest version of typescript with `npm install -g typescript`
2. Open a folder that contains a typescript project where an older version of typescript is in `package.json`.
3. Open a typescript file.
4. Error will pop up on screen. 

In my case I was still able to edit (.d).ts(x) files but there is the possibility of compiler and IntelliSense issues. would be nice if we could switch from using the global compiler to the workspace compiler.

**Comment by bpasero** [comment]
Looks like this issue is about the TSC message and not an editor issue.

**Comment by mjbvz** [comment]
See this answer on stackoverflow about what this error means and how to resolve it: http://stackoverflow.com/a/42429641/306149

This warning should not prevent you from editing any files.

Please let me know if the information about tsc is unclear or if you believe there is an actual bug here
