### ISSUE TITLE
one field missing

### ISSUE THREAD

**Issue by zhangmingchao** [Microsoft/vscode#21481]
the field "editor.referenceInfos" is missing in "settings.json" file

**Comment by isidorn** [comment]
What makes you say that?
Why would you expect it there? What is that field supposed to do?

**Comment by airbitcn** [comment]
Well, My English is poor, the field exist in old version. if set "true", 
![image](https://cloud.githubusercontent.com/assets/24471530/23443557/777d576c-fe6a-11e6-9bc8-393c7534003f.png)
then set "false", references will hide in editor.
![image](https://cloud.githubusercontent.com/assets/24471530/23443618/ee4052a0-fe6a-11e6-8f0b-9f96719f8265.png)
But in new version, this field below marked with a wavy line and show this message: "unknown configuration setting",  However it still works. So I want to know why.

**Comment by isidorn** [comment]
@ZhangMingChao you need to set `"editor.codeLens": true` and some other `codeLens` setting based on the language you are using.
`editor.referenceInfos` was never supported.

If the issue still exists then I recommend you file an bug to the C# repository here https://github.com/OmniSharp/omnisharp-vscode
Since the C# extension is responsible for this behavior

**Comment by zhangmingchao** [comment]
Thank you very much, 谢谢您! Resolved according to your answer
