### ISSUE TITLE
Error in HTML comment parsing

### ISSUE THREAD

**Issue by hugo-vrijswijk** [Microsoft/vscode#21500]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-08T23:31:51.320Z)
- OS Version: Darwin x64 16.4.0

---

Steps to Reproduce:

1. Type the following HTML in VS Code:
```
<html>
    <!-- This comment parses just fine -->
    <!-- This comment is wrongly parsed and continues afterwards--->
</html>
```
2. Note the end of the second comment not being seen as an end of comment

**Comment by hoovercj** [comment]
@hugo-vrijswijk 

per the [spec](https://www.w3.org/TR/html51/syntax.html#comment)
> 8.1.6. Comments
> 
> Comments must start with the four character sequence U+003C LESS-THAN SIGN, U+0021 EXCLAMATION MARK, U+002D HYPHEN-MINUS, U+002D HYPHEN-MINUS ().

Comments must start with `<!--` and end with `-->` and everything in between is the TEXT. The TEXT cannot end with `-`. According to that, the second comment in your example is an invalid html comment because it ends in `-`.

**Comment by isidorn** [comment]
Thanks @hoovercj 
Closing as desgined

**Comment by CoenraadS** [comment]
Is it documented somewhere how VSCode handles comments? 

![image](https://cloud.githubusercontent.com/assets/5593825/23508946/281f1828-ff54-11e6-8a42-8c527bb6135d.png)

I understand ignoring `--` in the middle of a comment because its a pain to parse, but the first 2 examples where there are post-conditions to the opening comment is also ignored.

Not a big issue, just curious because I am trying to handle html comments the same way VSCode does in my extension.
