### ISSUE TITLE
反复弹出信息：在过去5分钟，TypeScript语言服务以外中止了5次

### ISSUE THREAD

**Issue by yaolynzc** [Microsoft/vscode#21532]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|jquerysnippets|donjayamanne|0.0.1|
|csharp|ms-vscode|1.7.0|
|vscode-icons|robertohuertasm|7.3.0|
|JavaScriptSnippets|xabikos|1.4.0|

---

Steps to Reproduce:

1.Open a .js file with VS Code
2.The top menu pop a message "in the last 5 minutes，TypeScript language service has abort 5 “ again and again

**Comment by ydcoming** [comment]
检查下你的vscode的安装目录这个路径下\app\extensions\typescript\node_modules\typescript\lib是不是丢失了tsserver.js这个文件  估计是被杀毒软件杀了

**Comment by mjbvz** [comment]
Two probable causes:

1. You are opening a mapped network drive This is fixed in TypeSscript 2.2 which is included in VSCode insiders (VSCode 1.10)
1. If you see a message about a missing `typescript/...` file, you may be seeing #20496 in which an antivirus program is deleting our TypeScript implementation. See [this comment](https://github.com/Microsoft/vscode/issues/20496#issuecomment-279518845) for workarounds

If neither seems to fit for what you are hitting, please let me know and we can reopening this to investigate further
