### ISSUE TITLE
firstLine in Language Requires Entire line to match 

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#21533]
From http://stackoverflow.com/questions/42498117/vscode-syntax-highlighting-for-custom-shebang

For a file such as:

```
#!/some/directory/envroot "ENVROOT/bin/python"
....
```

We currently do not recognize the file as python even though the internal python extension's `firstLine` contribution matches. The reason is that the entire first line has to match: https://github.com/Microsoft/vscode/blob/master/src/vs/base/common/mime.ts#L206

This seems inconsistent with how TextMate uses `firstLineMatch`, and some of our grammars use `firstLine` patterns that do not work well with this restriction, such as `extension/xml`:

```
"firstLine" : "(\\<\\?xml.*)|(\\<svg)|(\\<\\!doctype\\s+svg)",
```

which fails to match:

```
<svg>
...
</svg>
```

**Comment by mjbvz** [comment]
@alexandrudima and @jrieken Adding you since I had trouble tracking down who implemented the logic in `mime.ts` originally.

Do you know why we currently require the entire line to match? Can we do like the xml grammar and add `.*` to the end of some of the `firstLine` contributions?

**Comment by bpasero** [comment]
@mjbvz sorry I cannot answer this question, the code was added a long time ago (I think by [Dimitar](https://monacotools.visualstudio.com/DefaultCollection/_git/Monaco/commit/1165896ef1f9bc85b358a6e4b07f730f1425ebff?_a=compare&path=%2Fclient%2Fvs%2Fbase%2Fmime.ts)) and since then has not been touched. 

I am fine changing this so that we align with TextMate's way of doing things. Happy to review a PR if you are interested.
