### ISSUE TITLE
[ Server response code is 404 ] keep poping on top of vscode 

### ISSUE THREAD

**Issue by karocksjoelee** [Microsoft/vscode#21535]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|vscode-theme-onedark|akamud|1.3.0|
|angulardoc-vscode|AngularDoc|2.0.1|
|vscode-eslint|dbaeumer|1.2.6|
|Angular2|johnpapa|2.0.3|
|vscode-add-angular-native-files|joshdsommer|0.0.5|
|vscode-icons|robertohuertasm|7.2.0|

---

Steps to Reproduce:

1.
2.

**Comment by isidorn** [comment]
Can you please attach a picture?
Can you also reproduce this if you disable all your extensions?
Do you see this all the time?

**Comment by andresrl** [comment]
Hi @karocksjoelee, I think I'm having the same issue as you.
**It's a problem with the AngularDoc extension**. Try to disable it.

My problem happens when Node is running and I change a .ts file.
Then a incremental compilation happens: _(12:12:02 - File change detected. Starting incremental compilation...)_
And before that the "**Error: Server response code is 404**" happens in the messages of VSCode

![angulardoc 404 problem](https://cloud.githubusercontent.com/assets/22559010/23548861/c3ea4146-0009-11e7-995f-f2b91ea93547.png)

**Comment by isidorn** [comment]
@andresrl as far as I understand this is an issue with the AngularDoc extension so can you please file it under the repository of that extensoin
