### ISSUE TITLE
Create-React-App Waring

### ISSUE THREAD

**Issue by HelloXZX** [Microsoft/vscode#21530]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|vscode-theme-onedark|akamud|1.3.1|
|ab-snippets|AlbertoBasalo|0.1.2|
|vscode-express|Compulim|0.0.5|
|python|donjayamanne|0.5.8|
|vscode-npm-script|eg2|0.1.8|
|vscode-npm|fknop|3.3.0|
|theme-atom-one-dark|freebroccolo|0.0.1|
|vscode-javac|georgewfraser|0.0.23|
|code-file-nav|jakelucas|0.7.2|
|NodeAssertionSnippets|jaymorrow|0.1.0|
|vscode-exec-node|miramac|0.2.8|
|cpptools|ms-vscode|0.10.1|
|csharp|ms-vscode|1.7.0|
|debugger-for-chrome|msjsdiag|2.5.5|
|ejs-language-support|QassimFarid|0.0.1|
|java|redhat|0.0.10|
|vscode-icons|robertohuertasm|7.3.0|
|ReactSnippetsStandard|TimonVS|1.1.0|
|python-extended-snippets|tushortz|0.0.1|
|jsx|TwentyChung|0.0.1|
|jsx-snippets|TwentyChung|0.0.1|
|expresssnippet|vladmrnv|0.1.0|
|vscode-react-native|vsmobile|0.3.1|
|JavaScriptSnippets|xabikos|1.4.0|
|ReactSnippets|xabikos|1.2.1|

---

Steps to Reproduce:

1. Use create-react-app 
2. Start vscode, warning ‘在过去5分钟内，TypeScript语言服务意外中止了5次。’

**Comment by mjbvz** [comment]
Two probable causes:

1. You are opening a mapped network drive. This is fixed in TypeSscript 2.2 which is included in VSCode insiders (VSCode 1.10)
1. If you see a message about a missing `typescript/...` file, you may be seeing #20496 in which an antivirus program is deleting our TypeScript implementation. See [this comment](https://github.com/Microsoft/vscode/issues/20496#issuecomment-279518845) for workarounds

If neither seems to fit for what you are hitting, please let me know and we can reopening this to investigate further
