### ISSUE TITLE
Regression: hover no longer shows source preview

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#21550]
Steps to Reproduce:

1. selfhost open `textFileEditorModelManager.ts`
2. ctrl-hover over the `disposeModelIfPossible` usage
3. notice you do not see the contents of the method anymore

=> works in stable
=> I am not sure if this is a TS issue or a hover issue
=> see video

![kapture 2017-02-28 at 10 50 27](https://cloud.githubusercontent.com/assets/900690/23400302/dc416570-fda3-11e6-8f68-b587779b910d.gif)

**Comment by jrieken** [comment]
This is because when being asked for a symbol definition TypeScript used to return the full range of that symbol, e.g the *full* method declaration. Now, TypeScript returns a range which is only the first line of that method declaration. 

The preview with mouse hover does the following: When a declaration has an empty range it create a new range from the given range plus 7 lines. However, when a declaration has a range that is being used (with an upper bound). The gif above shows this nicely as the first line of the method declaration is showing. 

Unsure what to do. The hover wants to respect the given range  because a method or another symbol might actually only be spanning a single line. TypeScript now seems to return the range of the method name which also isn't always bad and incorrect. Changing the hover and giving up correctness would be OK with me, but I wonder this justifies a rebuild. Likely that other languages show this behaviour ever since.

**Comment by mjbvz** [comment]
Yes, I confirmed this is a change on the TypeScript side. Here's typescript 2.1.6:

```
[Trace - 5:48:56 PM] Sending request: definition (26). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "/Users/matb/projects/vscode/src/vs/workbench/services/textfile/common/textFileEditorModelManager.ts",
    "line": 109,
    "offset": 20
}
[Trace - 5:48:56 PM] Response received: definition (26). Request took 2 ms. Success: true 
Result: [
    {
        "file": "/Users/matb/projects/vscode/src/vs/workbench/services/textfile/common/textFileEditorModelManager.ts",
        "start": {
            "line": 100,
            "offset": 2
        },
        "end": {
            "line": 105,
            "offset": 3
        }
    }
]
```

and here's TypeScript 2.2.1:

```
[Trace - 5:49:54 PM] Sending request: definition (16). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "/Users/matb/projects/vscode/src/vs/workbench/services/textfile/common/textFileEditorModelManager.ts",
    "line": 109,
    "offset": 28
}
[Trace - 5:49:54 PM] Response received: definition (16). Request took 1 ms. Success: true 
Result: [
    {
        "file": "/Users/matb/projects/vscode/src/vs/workbench/services/textfile/common/textFileEditorModelManager.ts",
        "start": {
            "line": 100,
            "offset": 10
        },
        "end": {
            "line": 100,
            "offset": 32
        }
    }
]
```


I think we even asked for this sort of behavior at some point: https://github.com/Microsoft/TypeScript/issues/8808

I don't think we should workaround this in vscode. I can either file an issue with TS for restoring the old  the behavior or try adding a workaround in the TS extension for this

**Comment by jrieken** [comment]
We decided not to do a rebuild because of this. @mjbvz Please mention this in the release notes as a temp regression which we will fix soon in insiders.

**Comment by jrieken** [comment]
Suggestion from @joaomoreno is to have some sort of *SymbolInformationProvider* that can be asked for more things, like `provideSymbolInformation(doc, pos): SomeSuperInformationContainingLotsOfInfo`. So it would become a 2-step process where we first resolve the location and the resolve the symbol at that location. Needs some more thinking. 

Since this is very specific to the hover we should maybe go with a low-profile solution that doesn't require much API change. We also show more surrounding code and highlight the range returned from the provider

**Comment by jrieken** [comment]
>  of SymbolInformationProvider that can be asked for more things, like provideSymbolInformation(doc, pos): SomeSuperInformationContainingLotsOfInfo

We could actually try to use the `DocumentSymbolProvider` for this.

**Comment by jrieken** [comment]
I have implemented a new heuristic that works with the indent of the denoted line. It works by starting with the (start) line of the returned range, read that lines indent and then going forward until a line with the same indent is found. That range (capped at 7 lines) will be used the preview range. There is still corner cases to this heuristics but it works a lot better than what we have today.
