### ISSUE TITLE
Ugly flicker when having suggested prompt

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#215519]
* have a squiggle
* open inline chat for it
* the UI flickers when coming up

https://github.com/user-attachments/assets/7e235ce5-3c3f-4333-bde9-637b05bdccaf

**Comment by jrieken** [comment]
@roblourens I believe the is the same underlying cause as https://github.com/microsoft/vscode-copilot/issues/5522. Drilling into this and it seems that setting follow up always triggers a layout with the "old" dimensions which isn't going fit. I believe that explains why the editor is looking so weirdly. It only gets very little height left 

IMO setting follow up should only trigger a content heigh change event so that the owner can issue a relayout but should not attempt to relayout with the existing dimensions. (maybe unless the number of follow up has changed in which case the content height didn't change...)

**Comment by eleanorjboyd** [comment]
tried this is a notebook and it felt very jittery still (but in a regular file it was fine) should I create a new issue for this? Seems to be due to the inline fix dialog getting placed in one spot then immediately moved


https://github.com/microsoft/vscode/assets/26030610/b6405e15-e6d3-4ac3-9814-49d82ed9d715



<img width="1273" alt="Screenshot 2024-06-26 at 10 31 06 AM" src="https://github.com/microsoft/vscode/assets/26030610/85b9d3ae-3036-46ac-8078-4396c235b117">
<img width="938" alt="Screenshot 2024-06-26 at 10 31 01 AM" src="https://github.com/microsoft/vscode/assets/26030610/6773e48a-176a-43dc-8128-721c19fc17e2">
