### ISSUE TITLE
VS code sluggish, takes secconds to switch files and laggy while typping

### ISSUE THREAD

**Issue by katwald** [microsoft/vscode#215773]
[prof-N8ij6T3l.main.cpuprofile.txt](https://github.com/user-attachments/files/15858973/prof-N8ij6T3l.main.cpuprofile.txt)

**Comment by jrieken** [comment]
The attached profile is from the main process (and doesn't look suspicious). Perceived slowness that you describe is more likely to happen from because of issues in the renderer process, please do the following:

Hit F1 > Toggle Developer Tools and select the "Performance" tab. In there select start, let it profile for 30 to 60 seconds, stop it, save it to a file and attach the file here. Thanks.


https://github.com/microsoft/vscode/assets/1794099/9287f8e1-a244-4a4f-8144-d879c0086b26

**Comment by anthonyblond** [comment]
The description sounds like the issue some people have been having with a change introduced in 1.90.0: https://github.com/microsoft/vscode/issues/212494#issuecomment-2172501949 

However that is for snap packages in linux, not the browser. @katwald are you having the issues with web vscode?
I'm not if it supports any equivalent setting, but in the snap package for ubuntu using `code --disable-gpu` to launch vscode provides some temporary relief.

**Comment by FirminEx** [comment]
If you installed it via snap, I fixed this by using `snap revert code`. Waiting for a patch.

**Comment by Shibodd** [comment]
Same problem here.

> If you installed it via snap, I fixed this by downgrading using `snap revert code`. Waiting for a patch.

Thanks, solved by uninstalling the snap package and installing code via the .deb file available on the official webpage.

**Comment by jrieken** [comment]
ping @katwald

**Comment by katwald** [comment]
> If you installed it via snap, I fixed this by downgrading using `snap revert code`. Waiting for a patch.

Thanks , this solved  my issue for now

**Comment by gfelisberto** [comment]
Hello. was this fixed on the snap package?
