### ISSUE TITLE
type script language service died

### ISSUE THREAD

**Issue by twingoliu** [Microsoft/vscode#21588]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.15042
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|Bookmarks|alefragnani|0.11.0|
|npm-intellisense|christian-kohler|1.3.0|
|path-intellisense|christian-kohler|1.2.0|
|jshint|dbaeumer|0.10.15|
|jquerysnippets|donjayamanne|0.0.1|
|vscode-babel-coloring|dzannotti|0.0.4|
|tslint|eg2|0.8.1|
|vscode-npm|fknop|3.3.0|
|beautify|HookyQR|0.8.8|
|Go|lukehoban|0.6.54|
|HTMLHint|mkaufman|0.3.3|
|prettify-json|mohsen1|0.0.3|
|csharp|ms-vscode|1.7.0|
|Theme-MaterialKit|ms-vscode|0.1.1|
|view-in-browser|qinjia|0.0.5|
|vscode-icons|robertohuertasm|7.3.0|
|yo|samverschueren|0.9.3|
|Spell|seanmcbreen|0.9.1|
|code-settings-sync|Shan|2.5.1|
|stylelint|shinnn|0.20.0|
|bootstrap-3-snippets|wcwhitehead|0.0.9|
|JavaScriptSnippets|xabikos|1.4.0|

---

Steps to Reproduce:

1.
2.

**Comment by mjbvz** [comment]
Two probable causes:

1. You are opening a mapped network drive. This is fixed in TypeSscript 2.2 which is included in VSCode insiders (VSCode 1.10)
1. If you see a message about a missing `typescript/...` file, you may be seeing #20496 in which an antivirus program is deleting our TypeScript implementation. See [this comment](https://github.com/Microsoft/vscode/issues/20496#issuecomment-279518845) for workarounds

If neither seems to fit for what you are hitting, please let me know and we can reopening this to investigate further
