### ISSUE TITLE
TypeScript语言服务意外终止

### ISSUE THREAD

**Issue by OneWordEnough** [Microsoft/vscode#21598]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|vscode-eclipse-keybindings|alphabotsec|0.9.2|
|vscode-eslint|dbaeumer|1.2.6|
|vue-snippets|hollowtree|0.1.0|
|path-autocomplete|ionutvmi|1.4.1|
|vs-color-picker|lihui|0.4.0|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.2|
|debugger-for-chrome|msjsdiag|2.5.5|
|vscode-icons|robertohuertasm|7.3.0|
|Material-theme|zhuangtongfa|2.0.4|

---

Steps to Reproduce:

1.
2.

**Comment by mjbvz** [comment]
Two probable causes:

1. You are opening a mapped network drive. This is fixed in TypeSscript 2.2 which is included in VSCode 1.10
1. If you see a message about a missing `typescript/...` file, you may be seeing #20496 in which an antivirus program is deleting our TypeScript implementation. See [this comment](https://github.com/Microsoft/vscode/issues/20496#issuecomment-279518845) for workarounds

If neither seems to fit for what you are hitting, please let me know and we can reopening this to investigate further
