### ISSUE TITLE
Multi page selection in debug console

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#2163]
I assume the console view is virtualized and so I can't copy a large amount of output at once. This is useful when debugging the Chrome adapter since it has a setting to write tons of logs into the console.

**Comment by felixfbecker** [comment]
Until you can select more than one page, could you maybe implement https://github.com/Microsoft/vscode/issues/3974 so at least the whole output could be copied at once, directly? I am also often in the position that I ask people to send me their logs and they cannot...

**Comment by MarkPieszak** [comment]
I believe this is fixed now in 1.8+ and can be closed out :+1:  @roblourens

**Comment by isidorn** [comment]
@MarkPieszak no, it is not fixed unfortunetly 🐝

**Comment by MarkPieszak** [comment]
Oh strange maybe I was in another tab sorry! Apologies :(

**Comment by JacobJT** [comment]
https://github.com/Microsoft/vscode/commit/e261525aad152779f5fda7c253a0f62d92a529ff

Did this commit just add a "copy" item to the right click context menu? If so, that button still has this same issue. If it's not feasible or easy to add a way to copy all selected text instead of only what's in the window, a "copy all" button would suffice.

**Comment by benjamin21st** [comment]
A hack of this would be redirect output to a file, what I did was to add ">" and then a filename like "output.txt" to "launch.json" in the "args" field. Works fine for now.

**Comment by scaba** [comment]
Is "selecting and copying a region of text" really so novel or difficult to figure out? I can swear I've seen such a thing in another app once.

**Comment by JacobJT** [comment]
@benjamin21st mind adding a quick snippet so we can see this formatting? This sounds very useful. Will it overwrite each time we run the debugger, or always add to the file?

**Comment by benjamin21st** [comment]
@JacobJT  Just like in command line you can do something like: 
`./myprogram > output.txt`
In VS Code, you can set up your `launch.json` file such that it has the following `args` in one of your tasks:
`"args": [
  "arg1",
  "arg2",
  ">",
  "output.txt"
]`

**Comment by mtz87** [comment]
This issue is so disturbing. It basically makes the debug console useless... worse than useless actually since you need to change perfectly good reporting code just to be able to read some logs.

**Comment by hq-mobile** [comment]
Would love to see this.  Trying to debug some rather lengthy request body differences that would be much easier to use a diff tool on.

**Comment by JacobJT** [comment]
It would also give us a way to search the console output, which currently I am not able to figure out how to do.

**Comment by QwertyZW** [comment]
This issue makes me think twice before attempting to file issues for an extension. The hack @benjamin21st mentioned does not work for me (I'm on linux)

**Comment by isidorn** [comment]
I have investigated today for the things needed in order to make this work:
1. The tree needs to auto reveal top and bottom as the selection changes. This is possible to get done using the `selectionchange` and `selectstart` events
2. Since the tree is virtualised the native selection can never span through elements which are currently not visible. In order to make copy work we would need to append selected `text`as we are scrolling in the tree. This can be rather tricky if the selection is changing directions

An alternative approach is to determine on what element in the model the selection started and where it ended and to copy the content between these elements. However the issue here is that the selection will not in some cases match what is being copied.

Another alternative approach is to use the editor for the debug console implementaion which is captured here #11462

Since the ideas above require quite an effort and would introduce additional issues for now we have chosen a pragmatic solution already suggested by @felixfbecker and have added a context menu action to simply copy all the output. So keeping this issue open as a feature request to be able to do more fine grained multi page copying but pushing it to backlog as I believe this workaround will help with most scenarios.
You can try it out in tomorrows [insider build](https://code.visualstudio.com/insiders) or in the next stable at start of june.

![screen shot 2017-05-16 at 11 31 27](https://cloud.githubusercontent.com/assets/1926584/26099515/3a096194-3a2b-11e7-8193-950bc9496798.png)

**Comment by zhaihm** [comment]
Can we add a "Copy All (Unformatted)" or "Copy All (Plain text)" function to the menu? 
When I copy/paste the log into editor (like Notepad++), there are characters that editor can't display. It would be a lot easier to analyze the log if we can just copy the log as plain text.

**Comment by isidorn** [comment]
@zhaihm please open a new issue / feature request for this and ping me on it. Thanks

**Comment by zhaihm** [comment]
Thanks for the replay. @isidorn  I opened #28094 for this feature.

**Comment by smarigowda** [comment]
I am using latest version 1.13.1, I can not see Copy All. Is there any flag to enable this?
![can-not-see-copy-all](https://user-images.githubusercontent.com/1831259/27838380-36834854-60e2-11e7-93f1-f5d504acc7e5.png)

**Comment by felixfbecker** [comment]
@smarigowda that is the variables panel, not the debug console

**Comment by smarigowda** [comment]
thank you. I can see it in debug console. Impressed with your lightning fast reply 👍

**Comment by bersbersbers** [comment]
This issue also applies to less-than-multipage selections in my opinion. Select a single character in the Debug Console, scroll the Debug Console up or down just far enough that the selection disappears, then scroll back to the original scroll position - the selection is gone.

**Comment by tjx666** [comment]
Another problem is that I can't select the first charactor.

For example, I can't select the charactor `n` in following screenshot:

![image](https://user-images.githubusercontent.com/41773861/140783438-4023891e-88ea-4483-b6d3-38234e6a6fea.png)

**Comment by roblourens** [comment]
Unfortunately I don't think this is practical with the virtualized debug console as it currently works. I think the "Copy All" context menu option which now exists is the best option.

**Comment by roa-nyx** [comment]
This is still a major pain point for me.

Even selecting doing a "Copy All" requires a lot of cleanup as the debug window shows escaped strings.

```
TEST\nstring with\tescape\tcharacters that are a pain to clean up each time.
```

Would love to see this addressed someday.

**Comment by TrueElement** [comment]
What's going on with this? Is anyone planning to address? It's super painful to use. This is a core expectation of normal editors, it should not have been shipped with this bug.
