### ISSUE TITLE
Undo triggers strange ghost text suggestion

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#216434]
1. Open https://github.com/microsoft/vscode/blob/a8e00a00ddd047fd5346408b434bcc67956754ee/src/vs/base/node/unc.js#L29
2. Select `Set`, replace with `Map`
3. Undo

🐛 Ghost text suggestion pops up strangely spreading the letters of `Set` within the suggestion.

https://github.com/user-attachments/assets/d95f3d93-b2db-40a2-8159-a1bef0b1829d

**Comment by hediet** [comment]
To verify:
* [Open this playground](https://microsoft.github.io/monaco-editor/playground.html?source=v0.50.0-dev-20240620&compareWith=v0.51.0-dev-20240621#XQAAAAKhFQAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscxjlADRgmSaumWUF-TBOsVJ4S4FwfCDQb5-2uUHXTVAefbVSd9IzaZ_vv9VR9KugsKicUBqzt3JtKN8DfDx5R0r3ur2s54RBykaL4piZfz98N2xRf8gz92yhPCtslOlXZhOEcMeAyC_9QkQRuyxDUWy2d9tCOcmfEt3MxdHBoUe53CzTleB4ALPojvlvGzVvX8ODhXjkl4ORiXsyaxzwS8AnxPm8blXyeCOiVYuODdTlQKHw0j01cCDOwMyQYBJucqHoA62MYy1qI3pfW1uxhZrpR2IUVj54lYetQyzSo4tS9nFYQTUitI9f5QBOA3maen1QvbvMdqtla3xtk8zWgBZsOmf-d8T1qGD7kxtzPfeNnndn_1CUQolZm56o1j3kUnM8fQ7Hs6rJRW6QLg7sEUGvNagBidQYCxIOFqRxdNi5mar9E-SHTMxKZBO4oeoJGv4Tue_GY--92_e3FKD4sbGKB8kDWRi9Oz1f1DaapHE_ZZr70rVqcUfv2H1NE5__2Uo6Pbw7dieThDq7BJeSb4JuThS74HmDvzic1PG9v-NJTckAh8fzhkpP-uW9E3vRwURawkj5wZ3hVUNKJNwggeFVTnLOVBWZWqjeCkZ59dBXzrp0uJS56GA0SCR6Hnzc0Bh71Qg5qQ_1jXWYSTX78wntbH3bxdL8jtlzse7YHIv4PYxamNhk9833qHMl0REs5pMGXZq8LTs-iapNTx3UOmK6Y_g-QERG7oWnHbbahQu_ieQuwRt-aQ3I45pkt1uuL60QUyOxR4N1gYMinjwd0T40DqwlQjxVnhHVp3q6WGD5jRNf_1ewGCN9rH8uE3N_sfWQNOLabaIYAvGNBGPeU5G08N0i-M067MCJly4LWMUPoMQ3sGCqv905AXQdpCu_oRbxx_LW5V-MpFxjLABYpktT7AgXtqkxgjIU1OAesR0LdeuZdZcF8knyuHOLorpDFsk0v9pqdGUsphmTi9bXMWROEIAT5YIDn8f3ZcMM-QiHF5TXh_vF585a4FbDpN7mAXy9sJFSeew1F0eO-IWQqEQEn0fpCIHR17cBP_U9d5VefthgZ55DO3UtS4Pj3wfr2KuqpOlrlX4hazhwIfeDLRjw0_eLkte-zIbsR99_ZdxAXMYYUhawZ3ocTIYGqlyafjHhw-a8xjr_TV36UyK0NW7M-X1XIhh8AdUGrPhdF-P-secKCrMQLzfsrLhzTDHAUWLiLP272O9jxe7IWaxh-IIdTFFhT9dbWG01xrJPKytkVsJpGJ_heJ0zPiLKq-W8qVXMNjA40CXRjhKpcmI_aOFXTJ4EysnRALyN7r3LvE7vEcTsOmX_X0qsyox6saZLnfyG7v7V054x3Pq2wAIQuAo8cgOSJkEzI1IqTc_4mWEug2Irh4H2Hd4CI7xVWUtEv8dKMdUYt828S7cEwwoOqVfB0-nhzokmy5xsddiakjHKqkh_i_x_2FzYgIAG0qvwny4g9DSqEZ27bPaiX5OIJHwGsaxTLXBzcocRY8-j8R-QK7iJ4ptvD_jQTIoYCiRq46wRpD8tJ-4RKI7_oHscQffzy7R9rKEhfWDbCKKIi0wKt7vIxumimofQCv55ZpLdfp9QmcUWy_39COj9r0UZqT3N1s7RCByDxwAe2cAEBzlBh0LaKksUFHDdCi59wCEN54k1KSWMgUWqcswb4QD5e8-J-FFr2HbgBIYnJ0Y7rdXZ9efLfM-yo377MnDevrHcW5MhTqS3bUX3Ym9TkQplZLQYIs3TpkJVi5tmD_irNx2czYaOO22kgnFv--TzIWFZTgjk00klpF5KQ-A1eMc5QsrIi_dpwK6HGQC71ZeClYJrHE__ILwrtENVEvhxnhDrf1Keu4gbyj_1L9cypWwA6SUPxsG8L8dpBxSL8FkKUUKqW9sWlCYe6TwwgNQD4mZxfloHtY5sGp_z_zkiwegMI3CmkCOFOClEEKpfXdUprByBS8mPqPADJbWDkmRKTB3-_sEj_URqOehdoEMUq4GN_jHvvj3PKUw-TTl-OyVUBt_iEQOul1Q57r7Mb9o7K7uPLgWEljolSySj164yg3Ux3HyzJU3gUw6oD6XQ4JOgmvd7YFW1QFYFQkb-5AmOMDExgRXe9nfeG2_9s93osQUfpOcewVW54o29EYXV7hgUK_Rn0HOdsNS_3JaS1YYxDlnlNx3k72ygvxPqocvGq9UYKEcPe3Xao80vFum7CdVyK5D3uEkzLEj2u4QywXEruUbcdj__ysyn5p6o1m4NjoHVxewAlsJj0q3ytlL5XTzaKLmFGpDqnJG8QAF6XSwVlXfHJ0yFnXn2HCPzIYI_lm1ZgZBpAnlpfHAYWzyQEb5Hy07oYNi6rbVmFl8UoIKSKcjKF9-HxFKpW_jPq7QlLFJyk2NTnISThZ4XVFnVg8dmFLH4BvP7yNUp-TczpFn__tfKiF)
* Double click on "Set" and type "Map", then undo.
* Verify this is weird in the top editor and fixed in the bottom editor.
