### ISSUE TITLE
VS Code in Windows doesn't seem to pull in user environment variables other than PATH

### ISSUE THREAD

**Issue by JasonAMelancon** [microsoft/vscode#216563]
I had a user environment variable PYTHONPATH giving the location of my personal (global) homegrown Python packages. In an administrator powershell, $env:PYTHONPATH returned nothing, but in a non-elevated shell, it returned the contents of the variable. Using the VS Code terminal, $env:PYTHONPATH behaved like an elevated prompt, returning nothing, even though I didn't run VS Code as an administrator. This was true for both a system install and a user install of VS Code.

I believe this is why my package imports weren't working until I moved PYTHONPATH to the system level.

**Comment by fcbry** [comment]
Same here, visual studio code terminal is using system PATH rather that user PATH

**Comment by cartercanedy** [comment]
Also currently having this issue

**Comment by jimbrig** [comment]
same here - been having this issue for a while now

**Comment by cartercanedy** [comment]
@Tyriar any updates?

just a friendly ping :)

**Comment by Tyriar** [comment]
I just confirmed this and it definitely does pull in user vars:

![Image](https://github.com/user-attachments/assets/dc997f0f-82a1-41a8-a346-f4e99d50102c)

![Image](https://github.com/user-attachments/assets/0e1425f6-0fb7-4d57-9b33-a49c0919c798)

One important thing to note with this though is that it requires you to restart VS Code entirely, not just a single terminal or window. This is because the environment is sourced when the window is created, not when a new terminal is created.

/duplicate https://github.com/microsoft/vscode/issues/47816

**Comment by cartercanedy** [comment]
I'd just like to add that yes, it will behave correctly in most circumstances, but there are times that I am completely unable to get a terminal window with the correct env, even between new & exclusive window instances.
