### ISSUE TITLE
I couldn't open VS code

### ISSUE THREAD

**Issue by Silverstone007** [microsoft/vscode#216866]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. I couldn't open VS code. It doesn't let me in saying that there is an uncaught exception:error in finding the module
![Issue-with-VsCode](https://github.com/microsoft/vscode/assets/173519323/43a10b42-08f9-481d-90f6-aa00e3e61536)

2.

**Comment by gjsjohnmurray** [comment]
I suggest you reinstall from https://code.visualstudio.com/

**Comment by proxsi** [comment]
App crashed on me after daily automatic update of Visual Studio Code Insiders.
Never had a problem in a year of so of insiders.
I redownloaded 1.91.0-insider, same problem. App crashes
I am running OS10.15.7 Mac Catalina on a a1278 Mid 2009 mac.


Jun 22 13:42:19 MacBook-Pro com.apple.xpc.launchd[1] (com.apple.xpc.launchd.user.domain.501.100005.Aqua): com.microsoft.VSCodeInsiders.ShipIt (lint): Assuming EnablePressuredExit=false given EnableTransactions=false.
Jun 22 13:56:03 MacBook-Pro com.apple.xpc.launchd[1] (com.microsoft.VSCodeInsiders.20768[9651]): Service exited due to SIGSEGV

That last message SIGSERV exited, repeats 9 times, at every double click on the app.

**Comment by timrc** [comment]
I suppose you could try to run it with no extensions/user data using
`code --user-data-dir /tmp/vscode --extensions-dir /tmp/vscode-ext`

**Comment by gjsjohnmurray** [comment]
@proxsi why do you think your issue with Insiders crashing on Mac is related to the one the OP has on Windows?
