### ISSUE TITLE
Multiple Instances with bash shells, histories not restored correctly

### ISSUE THREAD

**Issue by DaveAppleton** [Microsoft/vscode#21693]
- VSCode Version: 1.10.1
- OS Version: OSX 10.11.6

Steps to Reproduce:
0. Have multiple workspaces open each with bash and do stuff in each
1. Restart Code either by update or reboot
2. observe that bash histories are not restored

useful when you run a complex command to run a project in a particular way.

**Comment by Tyriar** [comment]
I believe this is related to the terminal instances not being shut down gracefully when vscode is shutdown.

**Comment by chirag64** [comment]
I'd like to attempt a PR for this.

But I'm unable to reproduce this. Here's what I tried:
1. Created multiple instances of VSCode with integrated terminals in them.
2. Ran a few commands in the integrated terminals
3. Force Quit VS Code (in Mac OS X)
4. Opened a new terminal window and hit `up arrow` key to cycle through my bash history. I was able to view the commands I ran from within VS Code.

This could also be an issue because of differences in bash configuration.

**Comment by Tyriar** [comment]
@chirag64 I believe this mainly just needs the terminalProcess.js program to also call `ptyProcess.kill()` in addition to killing itself when it's orphaned. It would be great if you could look into this. FYI here's another issue with more details which I'll close off in favor of this one https://github.com/Microsoft/vscode/issues/18990
