### ISSUE TITLE
"Open File" dialog does not open to current file directory

### ISSUE THREAD

**Issue by GreenXenith** [microsoft/vscode#216905]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.90.2
- OS Version: Ubuntu 22.04

Steps to Reproduce:

1. Open a file in a fresh window (no folder/workspace)
2. Use `Ctrl + O` or `File > Open File`

This opens the `Recent` tab in the file dialog rather than opening the same directory as the currently open file.

Yes, this same bug popped up [2 years ago](https://github.com/microsoft/vscode/issues/151668). I borrowed some wording from one of those issues.

**Comment by monk-afk** [comment]
Also affected by this, started happening after 1.89.1.

 VS Code Version: 1.90.0 & 1.90.2
Operating System: Debian GNU/Linux 12 (bookworm)    
          Kernel: Linux 6.5.0-0.deb12.4-amd64

Steps to Reproduce:

Same as above. Ctrl+O always and only opens file manager showing 'recent files'

**Comment by riccardomanfrin** [comment]
Version 1.90.1 speaking here: this problem is very annoying: every time I type CTRL+O to open  a file I find myself in the land of the void of nowhere. 

The thing that I could open a file from the same folder of the file I was browsing was soo good that I used to navigate across opened files to open other ones instead of browsing from the left menù 

1.89.1.... works perfectly, so I'm downgrading 

> sudo dpkg -i code_1.89.1-1715060508_amd64.deb
> ...
> dpkg: warning: downgrading code from 1.90.1-1718141439 to 1.89.1-1715060508
