### ISSUE TITLE
mainThreadDocuments.tryCreateDocument() is bypassing our model reference story

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#21709]
Extensions can create documents in our system that eventually cause text models to be created (via [`$tryOpenDocument`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/node/mainThreadDocuments.ts#L156)).

We correctly use `createModelReference` so that model lifecycle is ref-counted, however we fail to dispose this reference at any time (as outlined by this comment:

```typescript
// TODO@Joao TODO@Joh when should this model reference be disposed?
// ref.dispose();
```

This blocks me from adopting references for untitled/files ([TextFileEditorModelManager disposes models it doesn't own](https://github.com/Microsoft/vscode/issues/17888)) because unless I can rely on people disposing these references properly, we would end up with major leaks of models throughout the system (this is the reason why today I have weird code that disposes file models if I think they are no longer being used).

Setting to March so that we can finish this story that we started.

Also slightly related: we need a way to signal that a resource is literally gone. So, no matter how many references have been created, a way to force disposal of the underlying model (e.g. when a file gets deleted). I guess we will need this for extensions too (e.g. git).

**Comment by jrieken** [comment]
Not really sure how that blocks @bpasero because he should only release the models he has created, not others which is what https://github.com/Microsoft/vscode/issues/17888 is about. The idea with extensions is that they shouldn't be able to hold on to models indefinitely and thereby kill us. For the extension side we will likely empty some timeout logic once a document isn't visible anymore.

**Comment by bpasero** [comment]
@jrieken it blocks because when I no longer dispose models "I do not own", we start to leak any model that is created from the extension host side because today I see no code that disposes a model reference. That is the essence of what this bug is about.

**Comment by jrieken** [comment]
I am not saying this isn't a valid bug and I do appreciate that you try to fix leaks but one central place is cutting it because things like preview-html and embedded editor die because of that. The issue of releasing documents created by extension is easy, but I just wanna make sure workbench stops disposing models it doesn't own

**Comment by jrieken** [comment]
I have restored the 3 min rule. Now we have to start to return reference that are mortal.

**Comment by bpasero** [comment]
Thanks 👍
