### ISSUE TITLE
Several keybindings in menu bar displayed on left

### ISSUE THREAD

**Issue by wopian** [Microsoft/vscode#21722]
- VSCode Version: 1.10.1
- OS Version: Windows 10

#### Steps to Reproduce:
1. Click `File`
2. Open Folder is shown as `Open Folder…〔Ctrl+K Ctrl+O〕`

#### Expected:
Keybinding to not be in tortoise shells and right aligned with the rest of the keybindings.

#### Example:
![](http://i.imgur.com/FslbCsF.png)

**Comment by wopian** [comment]
Update: Also noticed the same with `Close Folder` at the bottom of the dropdown.

![](http://i.imgur.com/oIeVAIP.png)

**Comment by isidorn** [comment]
As designed. This is how we display chords - more details https://code.visualstudio.com/updates/v1_10#_display-chord-key-bindings-in-menus

**Comment by wopian** [comment]
They make the menus look a mess though

**Comment by wopian** [comment]
Is it not possible to right align the chords so they actually align with the rest of the keybindings, but remain wrapped in the brackets?

**Comment by isidorn** [comment]
No. THis is the best soluttion we could come up with the limited electron api.
Thanks for the ideas thoug.
@bpasero can provide more details

**Comment by bpasero** [comment]
This is not just for chords but for a lot more keybindings that cannot be displayed using native electron APIs. We feel that it is very important to guide users to the associated keybindings instead of having to hide some. Also it is bad to not show a keybindings a user assigned if the keybindings is not displayed.
