### ISSUE TITLE
Duplicate symbols when using 'Go to Symbols' and 'Show all Symbols'

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#2172]
Setup
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es5",
        "allowJs": true  
    },
    "exclude": [
        "node_modules"
    ]
}

Create a single file with a single function.

![symbols](https://cloud.githubusercontent.com/assets/172399/12506560/2c0b9f40-c0f0-11e5-80c4-efc124be7d65.png)

**Comment by dbaeumer** [comment]
I looked into it and the problem is that the function myFunction appears two times in the result. In the root and under the module node. See screen shot

![capture](https://cloud.githubusercontent.com/assets/1931590/12506819/d1a8443e-c0f1-11e5-8468-4cd7b3f97a70.png)

May be this is a specific problem with commonjs which I use in the setup.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#6566
