### ISSUE TITLE
No types for TS files in auto generated JSdoc (v1.10.1)

### ISSUE THREAD

**Issue by 255kb** [Microsoft/vscode#21728]
- VSCode Version: Code 1.10.1 (653f8733dd5a5c43d66d7168b4701f94d72b62e5, 2017-03-02T00:47:58.633Z)
- OS Version: Linux x64 4.4.0-64-generic
- Extensions: all extensions disabled

---

Steps to Reproduce:

1. Create a new file named test.ts
2. create a class + method or a simple function (see screenshot)
3. try to generate JSdoc for method by typing `/**` + pressing enter key
4. doc gets generated without types for parameters nor for return value (not even `{*}`)

![screenshot](http://i.imgur.com/LnNxlqu.png)

It is working correctly for JS files, all parameters getting the "any" `{*}` type.

**Comment by stephanedr** [comment]
Personally I don't want to mention the parameter types in the comment (for TS files). There is a risk of mismatch (when updating the code).
So maybe this can be controllable by an option?
However I'd like `@returns` to be added (without type for me). Either systematically or when a type is mentioned (!= `void`, `never` and maybe a few others?)

**Comment by 255kb** [comment]
@stephanedr agree it could be an option. 
But according to the 1.10 release notes types are automatically generated

**Comment by mjbvz** [comment]
We're tracking `@returns` generation here: https://github.com/Microsoft/TypeScript/issues/14248

Not generating parameter types is the expected annotations for TypeScript since the language is the source of truth for the type information. The TS compiler and the VSCode TS language support basically ignores the jsdoc types annotation in TypeScript files. If you have both jsdoc types and ts types, there is a risk they will get out of sync and lead to confusion, so we don't want to encourage this.
