### ISSUE TITLE
Cannot open previously opened files using editor's tabs

### ISSUE THREAD

**Issue by Deilan** [Microsoft/vscode#21774]
- VSCode Version: 1.10.0
- OS Version: Windows 8.1 x64

Not sure how to reproduce so far. When I click on the tab in VS Code with intention to open previously opened file in Editor, I receive a message, which states that the file doesn't exist. Tried with several files. The same files are opened just fine using explorer. I have a lot of files opened in tabs, maybe because of that the problem occurs. Here'a screenshot of the error message:

![untitled](https://cloud.githubusercontent.com/assets/4777512/23517250/d949b3a2-ff80-11e6-8a96-b09cf84d0af0.png)

**Comment by bpasero** [comment]
@Deilan yeah some steps would be helpful. The explorer is always updating live from file changes so if the file moved, it is likely that you see it in the right location. Tabs should update too though, so that is weird. Next time this happens can you compare the path from the error message with the path of the file from the explorer? Just to see if the paths differ.

**Comment by Deilan** [comment]
@bpasero Yup, I've already checked it, that's why I've posted this issue. The files and folders weren't moved or deleted. The paths are equal what you can see at the screenshot. If I find out how to stable reproduce it I'll let you know.

**Comment by bpasero** [comment]
@Deilan any findings?

**Comment by Deilan** [comment]
@bpasero Not reproduced so far. If it will I'll let you know. I think it's fine to close the issue for now until someone stumble upon it again.
