### ISSUE TITLE
Slow startup profile

### ISSUE THREAD

**Issue by stevencl** [Microsoft/vscode#21781]
- VSCode Version: <code>Code - Insiders 1.11.0-insider (4db944bc08e34fb15c5805927d9cb67470776606, 2017-03-02T07:10:18.838Z)</code>
- OS Version: <code>Windows_NT ia32 10.0.14393</code>
- CPUs: <code>Intel(R) Core(TM) i7-3687U CPU @ 2.10GHz (4 x 2594)</code>
- Memory (System): <code>7.89GB (1.53GB free)</code>
- Memory (Process): <code>129.70MB working set (149.85MB peak, 107.54MB private, 28.30MB shared)</code>
- Load (avg): <code>0, 0, 0</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>no</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|137|
|main|app.isReady => window.loadUrl()|768|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|3053|
|renderer|require(workbench.main.js)|2654|
|renderer|create extension host => extensions onReady()|2736|
|renderer|restore viewlet|686|
|renderer|restore editor view state|1542|
|renderer|overall workbench load|3653|
|main + renderer|start => extensions ready|9839|
|main + renderer|start => workbench ready|10319|

---

:warning: Make sure to **attach** these files: :warning:
-`C:\Users\stevencl\2803_main.cpuprofile.txt`
-`C:\Users\stevencl\2803_renderer.cpuprofile.txt`
[2803_main.cpuprofile.txt](https://github.com/Microsoft/vscode/files/814072/2803_main.cpuprofile.txt)
[2803_renderer.cpuprofile.txt](https://github.com/Microsoft/vscode/files/814071/2803_renderer.cpuprofile.txt)

**Comment by jrieken** [comment]
This is https://github.com/Microsoft/vscode/issues/22086, #21963, https://github.com/Microsoft/vscode/issues/22090

**Comment by agauniyal** [comment]
Someone should build a bot to identify duplicate issues 😂

**Comment by jrieken** [comment]
Please! Tho for profiles it's extra-tricky. I know it looks stupid that we ask to submit issues with profiles and then quickly close them again. Reality tho is that we receive many profiles and that they often show the same bottlenecks. That's why we extract individual issues and close profiles as 'sort-of-dupes' of them. That still means these issues are very valuable to us. We obviously profile VS Code on our machine but are often surprised about real-world behaviour.
