### ISSUE TITLE
Cannot focus list view to scroll through responses with keyboard

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#218088]
Testing #217202

Repro:
1. Use /explain in inline chat to get a long response.
2. Try using `Cmd+Up` to focus the last response (does not work)
3. Use `Shift+Tab` to focus the last response
4. Try using `Cmd+Up` to scroll up in list view of chat messages. (does not work)

**Comment by jrieken** [comment]
Same for panel chat. I believe the keybinding simply isn't bound

**Comment by roblourens** [comment]
You may have to press it twice, once to move the cursor to the top of the editor, and then another time to trigger the chat keybinding, does that work? It's working fine for me.

**Comment by roblourens** [comment]
Oh, not in inline chat though

**Comment by roblourens** [comment]
@meganrogge @Tyriar I can't remember what terminal chat looked like in March, do you still want this disabled? I think we probably want it enabled in all chat widgets now: https://github.com/microsoft/vscode/issues/208927

**Comment by roblourens** [comment]
I fixed this so that cmd+up/down will work in the terminal and inline chat widgets. But in the terminal, once the list is focused, then the arrow keys still navigate history. It looks like the terminal widget is registering a bunch of its own commands for history and for moving focus around. You shouldn't need to do that anymore, since you can use the commands that the ChatWidget has.
