### ISSUE TITLE
Wrong API proposal error/warning

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#218058]
* latest insiders
* latest chat prerelease
* reload window
* :bug: the following warning appears on the console ⬇️ 

```
ERR Extension 'github.copilot-chat' wants API proposal 'lmTools@2' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
```

**Comment by gjsjohnmurray** [comment]
Maybe related to #217140

**Comment by sandy081** [comment]
I also see the the error in the console, but the extension seems to run fine. @jrieken Is it the same for you? Is the extension running fine? Is there anything broken?

**Comment by sandy081** [comment]
Actually my existing check is wrong and `lmTools` functionality implemented by copilot chat should be broken. Because, my check is excluding allowed extensions for version check instead of considering them. 

CC @roblourens - If your TPIs are blocked because of this, please trigger a new insider with this fix.

**Comment by sandy081** [comment]
Previous fix is not good enough. Hence preparing better fix.
