### ISSUE TITLE
Extension API Request: Send Custom Requests To TypeScript Language Service Plugins #43893

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#218275]
(Follow-up of https://github.com/microsoft/TypeScript/issues/43893)

TypeScript language server plugins can now register handlers of custom commands (this is used for the VS Code inlien value provider for example).

However, VS Code extensions still cannot send such commands to the TypeScript language server.

It would be nice if the VS Code TypeScript extension would expose API to do that.

## Proposed Solution

Extend the [API returned by the TypeScript language features extension](https://github.com/microsoft/vscode/blob/0354163c1c66b950b0762364f5b4cd37937b624a/extensions/typescript-language-features/src/api.ts#L9-L18):
```ts
class ApiV0 {
  // ...
  invokeCustomCommand(customCommandId: string, uris: Uri[], payload: /* JSON serializable */ unknown): Promise<unknown> { ... }
}
```
Uris are automatically translated to file names to make life of third party extensions much easier (VS Code extensions only use Uris, typescript language service plugins use only file names).

This would then enable typescript language service plugins to react to such a command and send some data back:
```ts
export = function init(modules: { typescript: typeof ts }) {
	return {
		create(info: ts.server.PluginCreateInfo): ts.LanguageService {
			info.session?.addProtocolHandler('getRelativeFileCall', request => {
				return {
					response: {  myData: { ... } }
				};
			});
			return info.languageService;
               }
       }
}
```

**Comment by mjbvz** [comment]
@hediet Can you add some more info about the use case?

I'd like to restrict this to specific commands against TS Server. Some of the builtin commands, such as `updateOpen`, have the potential to cause major issues

Also not sure about the `uris` argument. Maybe we could expose [`toTsFilePath`](https://github.com/microsoft/vscode/blob/c1a610d1b33aae7be41bdeb6b70ed622ad8819ff/extensions/typescript-language-features/src/typescriptService.ts#L141)

**Comment by hediet** [comment]
> Can you add some more info about the use case?

My use-case is the [TypeScript Relative File Path Support](https://github.com/microsoft/vscode-ts-file-path-support) extension.
This extension [implements several VS Code features](https://github.com/microsoft/vscode-ts-file-path-support/blob/bb1cafb9aee6c4616b0be00f682d65b9fc350f3a/vscode-extension/src/index.ts) around relative file paths in ts/js sources and uses type information to do that.

These features cannot be implemented directly in the TypeScript language service (e.g. by decorating the `ts.ILanguageService` object).
For example, the completion item provider in TypeScript always uses `.` as accepting character, which is very inconvenient for file paths that have a `.` in them (I'd like to use `/` instead). Afaik this is set in the TypeScript VS Code extension, so a language service plugin cannot do anything about it.
The rename provider is tricky as well, as I want to rename an unrelated file on disk. Neither `getRenameInfo` nor `findRenameLocations` seem to be helpful here.

Generally, some features are much nicer to implement by using the VS Code API (and not the `ts.ILanguageService` API).

My current workaround is to have a very hacky `decorateLanguageServiceWithCustomService`/`createTsLspCustomServiceClient`, which uses `getApplicableRefactors` and `vscode.executeCodeActionProvider` to establish an RPC channel between the VS Code extension and the language service protocol:
https://github.com/microsoft/vscode-ts-file-path-support/blob/bb1cafb9aee6c4616b0be00f682d65b9fc350f3a/language-service-plugin/src/rpc/decorateLanguageServiceWithCustomService.ts#L9-L15

https://github.com/microsoft/vscode-ts-file-path-support/blob/bb1cafb9aee6c4616b0be00f682d65b9fc350f3a/vscode-extension/src/createTsLspCustomServiceClient.ts#L14-L22

This works, but could be more efficient. Also, coming up with this RPC channel was the most tricky/time intensive part of the extension.
Having official API to do this would enable many other such extensions!

**Comment by pawk3k** [comment]
To emphasise the importance of this request, https://github.com/mxsdev/ts-type-explorer/blob/main/packages/typescript-plugin/src/index.ts#L53 here is how one of the relatively popular extensions does the type information retrieval for vs code extension.
This change might open possibilities for more excellent experiences with typescript.
I have two ideas: 

- **What colour is your function** to get semantic highlighting on demand from the server app so the extension does not have to parse the whole project. The idea is to have all PromiseLike return functions coloured, for example, red, and all the sync functions blue.
![Image](https://github.com/user-attachments/assets/40872c80-edb1-4dd5-a422-113d27be8d59)

Here is how it's working with native semantic highlighting. I know only some people want this, but I have had this idea for two years, and every time I sit down to it, I fail to get a solution that I would be happy with. I'm not blaming. It could be a skill issue.


- TS-Sapling 
https://marketplace.visualstudio.com/items?itemName=team-sapling.sapling
Something like this sapling, but with type information, because it is all implemented with Babel and does not get any spread props.

# Why? 

This comment shows the most painful reactions in big projects.
https://www.reddit.com/r/ExperiencedDevs/comments/1dh9rly/the_chaos_of_react_in_medium_to_large_web_apps/
Except for one: Props drilling with components that might not need those props for 2-10 levels. While not a problem, code grows, levels grow, and the composition disappears. I want to feed the information about each component's tree structure and props to the GitHub copilot, for example, and get some meaningful examples of refactoring, moving components up or down, and living in a better world.

**Comment by mjbvz** [comment]
This was added in [#232663](https://github.com/microsoft/vscode/pull/232663)

@dbaeumer Can you please verify this issue for endgame

**Comment by dbaeumer** [comment]
Verified by using the new API for a TypeScript server plugin.
