### ISSUE TITLE
Notify the user when debug is blocked on prelaunch tasks

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#218267]
Clone https://github.com/microsoft/vscode-dev and npm install. Hit F5, it never starts:

<img width="484" alt="image" src="https://github.com/user-attachments/assets/7bf34879-6e67-4e7a-8b78-2215a87974bf">

I am on macOS.

**Comment by connor4312** [comment]
This is probably because a prelaunch task is still running / your problem matchers haven't matched anything. Please make sure you have the right problem matchers installed, otherwise I suggest opening issues for them if they don't match correctly.

**Comment by bpasero** [comment]
Would be great if debug could give me a hint.

**Comment by connor4312** [comment]
Will keep open to track it, it's not a rare problem

**Comment by connor4312** [comment]
We should also keep the terminal open if the task fails, currently it closes immediately which can be confusing

**Comment by joyceerhl** [comment]
Would also be nice if we could cancel the pending launch attempt, e.g. by showing the debug toolbar immediately and disabling all buttons except the stop button. Right now when I get into this state I end up just reloading the whole window and incurring the pain of all extensions reactivating, which takes several seconds on my machine (git, TS etc)

**Comment by connor4312** [comment]
The debug toolbar is quite tied to having a debug session and the interaction if you start a new debug session with a prelaunch task while another session is already running is not clear (because you could not use the normal session picker.)

I think I'll have some notification that pops up if the problem matcher hasn't matched in ~10 seconds saying what it's waiting on and giving some options.

**Comment by connor4312** [comment]
After 10 seconds we'll show

![image](https://github.com/user-attachments/assets/643b4335-773f-402a-8a3c-ad0b14c54ad3)
