### ISSUE TITLE
Pressing enter when writing ts-doc comment removes the ts-doc comment

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#21867]
- VSCode Version: Code - Insiders 1.11.0-insider (84e56fc527047223a6ad22c31a906d4a579680d0, 2017-03-03T07:10:29.111Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|copy-relative-path|alexdima|0.0.1|
|vscode-lcov|alexdima|0.2.0|
|vscode-eslint|dbaeumer|1.2.7|
|tslint|eg2|0.8.1|
|Theme-Github|gerane|0.0.3|
|Theme-MaterialKit|ms-vscode|0.1.1|
|Theme-TomorrowKit|ms-vscode|0.1.3|
|debugger-for-chrome|msjsdiag|2.5.5|
|vscode-versionlens|pflannery|0.12.1|
|RustyCode|saviorisdead|0.19.1|
|slime|smlombardi|1.2.0|
|vscode-open-in-github|sysoev|1.4.0|;

---

Steps to Reproduce:

1. open the vscode repository
2. open `editorCommon.ts`
3. add a new member to one of the interfaces, e.g. `ITokenizedModel`
4. attempt to write ts-doc comment by typing `/`, `*`, `*` and enter:

![ts-doc-not-possible](https://cloud.githubusercontent.com/assets/5047891/23544274/a2526260-fff6-11e6-9b7d-faaa84da0059.gif)

**Comment by mjbvz** [comment]
@alexandrudima Does this happen all the time? Can you try restarting VSCode and trying to reproduce the issue. 

I think the TSServer may be hung here. We have to delete the `/**` before requesting the comment documentation template from TypeScript, so I suspect that we either never receive a response or received one after a delay. If you can enable `"typescript.tsserver.trace": "verbose"`, and share the output from TypeScript after reproducing this, that would also help us track down the root cause

Thanks

**Comment by alexandrudima** [comment]
@mjbvz I can no longer reproduce. It must have been something transient.
