### ISSUE TITLE
Toggled menu bar can make the entire window contents jump up making hit zones move

### ISSUE THREAD

**Issue by newbrain** [Microsoft/vscode#21889]
Some mouse clicks are ignored when the menu bar is un-hidden (with Alt key).

- VSCode Version:
1.9.1, 1.10
- OS Version:
Windows 7 Enterprise, Windows 10 Pro

Steps to Reproduce:

1. Make sure the menu bar is hidden (View->Toggle Menu Bar)
2. Show the menu bar using Alt key
3. Select File->Preferences->Color Theme
Alt: File Icon Theme, or any menu item that will show an in-editor menu 
4. The Color Theme menu is shown
5. Left click on any theme

Expected result:
- Selected theme applied
- Menu dismissed
- Menu bar hidden

Actual result:
- The theme is not applied
- The menu is not dismissed
- The menu bar becomes hidden again.

Further steps:
6. Left click on any theme again
7. The theme is applied, the menu dismissed and the menu bar hidden, as expected.

**Comment by bpasero** [comment]
@newbrain I see a problem that the entire window moves up when clicking, is that what you are seeing?

![untitled](https://cloud.githubusercontent.com/assets/900690/23555840/bc47868a-002a-11e7-8e04-cd29369a88c8.gif)

**Comment by newbrain** [comment]
Yes,
as I described the Menu Bar disappears, so the windows content is shifted up.
That's expected when toggling the Menu Bar, but the human interface problem I see is that the left click is not registered.
One needs to click again to operate a selection (or click outside the list to dismiss it).

**Comment by bpasero** [comment]
Thanks, unfortunately I have no real answer how to solve this.

**Comment by timbanaveen** [comment]
Hi @bpasero 

Root cause of this issue is that:
1. When auto menu hide is true, and when menu is visible clicking (listens on mousedown event) any where will result in hiding of menu.
2. When we show options to select  theme or any other option in tree widget, we register click event as selection, whereas mousedown will move tree widget upward and next mouseup event will have different target then mousedown event. which creates problem.
3. If we want to solve we can do that by 2 ways, first hide menu on showing tree widget. second listen to mousedown event on tree widget instead of click event.

Please suggest further actions :)

**Comment by bpasero** [comment]
I think this is not limited to quick open but anything in the UI where you can click, no?

**Comment by timbanaveen** [comment]
Yes, anything on UI will have same effect as quick open. ie, mousedown -> menubar hiding -> mouseup on different target than mousedown.

**Comment by eamodio** [comment]
This *seems* worse lately in that the menubar seems to toggle in unwanted cases. For example, alt+click on a button on the `editor/title` -- once you release the mouse, the menubar will be shown. It seems to come up on other cases as well (that are escaping me).

Related -- is there a way to change the shortcut key for the menubar toggle?

**Comment by bpasero** [comment]
We will change to custom menus on Windows. For now you can set `"window.titleBarStyle": "custom"`.
