### ISSUE TITLE
VS Code cant save as...why

### ISSUE THREAD

**Issue by efd7887** [microsoft/vscode#218912]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: i dont feel like finding it
- OS Version: windows

Steps to Reproduce:

1. open a file i already have (we will call it a template)
2. i want to save a COPY of the file.  i cant. 

I dont know who thought this was a good idea, but it isnt.  put it back.  im really starting to hate vs code and really question the skills of the developers.  i mean, all other msoft apps allow it.....but not this?  stupid

and why are all the UNANSWERED ISSUES close without a solution other than "yup, thats our feature.  love it or just complain about it because its our tool so tough"  so much for an extensible, customizable ide.  is it really that hard?  just change a few lines of code (im sure google will help you with that) and put it in your next release.

**Comment by benibenj** [comment]
We provide a `save as...` action from the `Files` menu:

![Image](https://github.com/user-attachments/assets/c52a0a2e-789a-4f98-ae26-ad57e9ac6a23)

Otherwise you can also run the `save as...` action from the command palette:

![Image](https://github.com/user-attachments/assets/281672f2-f447-41db-9b15-5b97c32114cd)

It's also possible to copy paste a file in the file explorer
