### ISSUE TITLE
Use a chat system, such as Gitter

### ISSUE THREAD

**Issue by criswell** [Microsoft/vscode#219]
Many OSS projects these days use free services like Gitter (https://gitter.im/) to provide chat channels for their projects. I think vscode would benefit greatly from a channel. It can be included in a link from the README.md file (see Diffy for an example, https://github.com/twitter/diffy).

**Comment by RandomlyKnighted** [comment]
+1

**Comment by stkb** [comment]
+1 Gitter's very easy to set up too

**Comment by chrisdias** [comment]
Thanks for the suggestion! The vscode gitter room can be found here: https://gitter.im/Microsoft/vscode.

Now, some background on why it took so long to resolve this issue. We had quite a bit of deliberation on the team as to whether or not we have a gitter room, slack channels, or nothing at all. 

Here's why. Since moving to GitHub, we have been managing a large number of input channels (GitHub issues, Twitter, Stack Overflow, email, User Voice, etc.). This is great, but we want to be responsive. To do so, we are consolidating issues to the `vscode` repository and we will [encourage](https://github.com/Microsoft/vscode/wiki/Issue-Tracking#initial-triage-done-by-the-inbox-tracker) questions be posted on [Stack Overflow](https://stackoverflow.com/questions/tagged/vscode), the best place for getting high quality answers from us and from the community.

The challenge we face here is that a gitter room is another input channel that we don't have the bandwidth to participate in right now. And, at the same time, we do want to provide a place where the Community can get together and collaborate. It is actually great to see that folks have already started to collaborate and support each other there.

What this ultimately means is that the VS Code team's presence in the room will be very limited, at least for the foreseeable future. We hope the Community will use the room and have discussions, and all we ask is that valuable Q&A is done on Stack Overflow and issues are submitted into the repository. 

If there is anything needing urgent attention that we miss, please feel free to mention me (@chrisdias) and I'll jump in.
