### ISSUE TITLE
Add Rename File option to the context menu of file tabs

### ISSUE THREAD

**Issue by jpoehls** [Microsoft/vscode#21919]
I'd like a "Rename File" option to appear on the right-click context menu of file tabs. Ideally this would trigger a corresponding command (see #21918).

Purpose is to provide a more accessible option than the alternative of opening the explorer sidebar and right-clicking the file to rename.

**Comment by bpasero** [comment]
There is https://marketplace.visualstudio.com/items?itemName=sleistner.vscode-fileutils

**Comment by warpdesign** [comment]
How about double-click on the file tab = allows to edit in place the name (using something like contentEditable)?

Would be far more useful than an hidden command.

**Comment by jpoehls** [comment]
> How about double-click on the file tab = allows to edit in place the name (using something like contentEditable)?

Not a fan of this. Would be very annoying if you accidentally doubled clicked on tabs which seems like a pretty easy thing to do.

> Would be far more useful than an hidden command.

Double-click vs. right-click? Either way the feature is literally the same number of clicks away.

**Comment by jdforsythe** [comment]
Double click on a tab already does something, so when a file is in "preview mode" (whatever it's called when the name is in italics and the tab isn't sticky) and you double click, should it rename or make the tab sticky? You'd have to double click twice to rename. I think the context menu makes more sense because it could be performed on a preview file without making it sticky first.

**Comment by bpasero** [comment]
Closing in favour of extension.

**Comment by joshunger** [comment]
@bpasero how do you determine what features to bring into vscode?  At this point three different people have logged this issue (including myself 😄 ) and I'm wondering it would be more favorable and a better user experience if this is moved into vscode.  Just a guess, but since Atom and WebStorm include this out of the box then users are probably expecting the same thing in vscode.

**Comment by bpasero** [comment]
@joshunger I am not sure there is any other criteria than seeing if this feature could be implemented as extension and then encouraging to provide this as extension. if the extension becomes popular enough that every VS Code user has it installed, we can certainly talk about bringing the functionality back into VS Code. Makes sense?

**Comment by joshunger** [comment]
@bpasero Thanks.  Yeah if you want it added to vscode with just a help-wanted label I'd be happy to take a stab at the PR.  Just let me know.
