### ISSUE TITLE
tokenColorCustomizations SCOPE NEEDED

### ISSUE THREAD

**Issue by Dpschu2** [microsoft/vscode#219153]
Can a new token color scope be added for css attribute values? 
Currently it is selectable if the value is a string, but if is not a string, then it cannot be differentiated from the attribute key. 
This is of course needed to set the color separate from the key.

![example](https://github.com/microsoft/vscode/assets/22309201/81eee30b-aad3-4483-8a6f-1ce5e8eb609f)
(Example where 'something' is not scoped differently)

**Comment by aeschli** [comment]
This is what I see with the latest insiders and the Dark Modern Theme (Default)


![Image](https://github.com/user-attachments/assets/c94dea37-31c0-4704-a532-cb72b2b1568e)


Maybe the issue is with the theme you are using? Which on is it? If it is a theme from an extension, please file the issue against that extension.


```
.blog-caption[data=something] {
	p {
		background-color: #f00;
	}
}
```

**Comment by Dpschu2** [comment]
I am using my own color theme extension: Future Dark

https://marketplace.visualstudio.com/items?itemName=deans4.future-dark

**Comment by Dpschu2** [comment]
Found the culprit: https://marketplace.visualstudio.com/items?itemName=dannymcgee.vscode-scss-lang

Beware!!!
