### ISSUE TITLE
in past 5 minutes, TypeScript's broken for 5 times

### ISSUE THREAD

**Issue by JackZL** [Microsoft/vscode#21956]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|python|donjayamanne|0.5.9|
|csharp|ms-vscode|1.7.0|

---

Steps to Reproduce:

1. open blank js file
2.

**Comment by mjbvz** [comment]
Two probable causes:

1. You are opening a mapped network drive. This is fixed in TypeSscript 2.2 which is included in VSCode 1.10
1. If you see a message about a missing `typescript/...` file, you may be seeing #20496 in which an antivirus program is deleting our TypeScript implementation. See [this comment](https://github.com/Microsoft/vscode/issues/20496#issuecomment-279518845) for workarounds

If neither seems to fit for what you are hitting, please let me know and we can reopening this to investigate further
