### ISSUE TITLE
How about a horizontal slider in the file explorer?

### ISSUE THREAD

**Issue by tangkk** [microsoft/vscode#219644]
Sometimes filenames could be really really long, especially when you're dealing with large experiments. You add suffix to the prefix experiment to suggest a modification of a certain parameter or variable, and in another experiment, you add another suffix. 

I'm currently dealing with files/codes with VERY long names and with the same 'prefix'. Everytime I use VS code, and try to look for the one file I'd like to open, I'm seeing a bunch of files with same prefix. Then I need to drag the file explorer's pane to see the suffix of these files and choose the one, then drag the pane back again (to view the code). I wonder if you could, officially, add a horizontal slider to the file explorer, so that I could always see the suffix of file names whenever I need to?

**Comment by gjsjohnmurray** [comment]
Please use the advice at https://github.com/microsoft/vscode/issues/144120#issuecomment-1057062232

**Comment by RedCMD** [comment]
how does it impact performance?

I know 50 levels or so of nested items causes quite a performance hit

**Comment by lramos15** [comment]
It effectively increases the size of the virtual DOM and the number of nodes that can be represented.  It also causes more layout calculations so that everything is properly positioned when horizontal scrolling is enabled.

It's not something we plan to enable at this time but feel free to turn the setting on 👍
