### ISSUE TITLE
DYLD_FALLBACK_LIBRARY_PATH is not passed to extensions

### ISSUE THREAD

**Issue by somelinguist** [microsoft/vscode#219806]
Does this issue occur when all extensions are disabled?: Disabled all but relevant extensions, but still persists

- VS Code Version: 1.90.2
- OS Version: macOS 14.5

Steps to Reproduce:

1. Set and export `DYLD_FALLBACK_LIBRARY_PATH` in `.zshrc`
2. Restart VS Code to make sure change is picked up
3. Run the following script to make sure it's set using the Ionide for F# extension.

```fsharp
open System.Collections

let vars = System.Environment.GetEnvironmentVariables()
printfn $"Count: {vars.Count}"

vars
|> Seq.cast<DictionaryEntry>
|> Seq.iter (fun e -> printfn $"{e.Key}: {e.Value}")
```

Result:

All other environment variables exported in `.zshrc` are set correctly except for `DYLD_FALLBACK_LIBRARY_PATH` , which is missing.

Running the same script in the vscode's integrated terminal via `dotnet fsi script.fsx` works as expected, with the value set in `.zshrc` is passed to the script.

I can see that `DYLD_LIBRARY_PATH` is explicitly deleted when running extensions in the following code:

https://github.com/microsoft/vscode/blob/0cdc9b33419a39557fc6109ad629f196cd92439e/src/vs/base/common/processes.ts#L143-L148

However, I can't see anywhere that `DYLD_FALLBACK_LIBRARY_PATH` would be expected to be deleted.

See https://github.com/ionide/ionide-vscode-fsharp/discussions/2022

**Comment by alexdima** [comment]
@deepak1556 What is your take on this? We're deleting `DYLD_LIBRARY_PATH` because it was getting picked up by Electron/Chromium. I don't know why `DYLD_FALLBACK_LIBRARY_PATH` wouldn't survive to the extension host. I'm not sure if Electron can be built to ignore these env variables?

**Comment by deepak1556** [comment]
We have removed the `com.apple.security.cs.allow-dyld-environment-variables` entitlement from the [main application bundle](https://github.com/microsoft/vscode/commit/75e38cd91df5256e5bf6f207be82c095e20d3525) when moving to the utility process as an effort to reduce the privileged entitlements on the main process, this particular entitlement will make the OS to stop injecting any `DYLD` variables into the main process, also means any child process of the application will also not receive them. On that note, the code we are using to delete `DYLD_LIBRARY_PATH` is a no-op today since the OS already took care of it.

The integrated terminal creates pty sessions which can get those env variables without being affected. I suggest to make a similar workaround to read from the rc file for your scenario.
