### ISSUE TITLE
Wrong information about references

### ISSUE THREAD

**Issue by svipben** [Microsoft/vscode#22006]
- VS Code version: 1.10.1
- OS version: Linux Ubuntu 16.04
- Settings: `"typescript.referencesCodeLens.enabled": true`
- **Problem**: Class `App` is used in 4 places, shows `0 references`
- _Fix_: Open files where class `App` is used and when go check class `App` again, it will shows `4 references`
- **How it should be**: You don't need to open files where class `App` is used to see all references

**Comment by mjbvz** [comment]
@svipben Try creating a `jsconfig.json` in the root of your workspace: https://code.visualstudio.com/Docs/languages/javascript#_javascript-project-jsconfigjson

This tells vscode to include all JS files in the workspace in the JavaScript project, instead of only the opened files

Let me know if you run into any issues with this

**Comment by svipben** [comment]
@mjbvz Hello, thanks for response, I created `jsconfig.json` and `tsconfig.json`, but still shows `0 references`, can you say how I need to configure to get correct references?

```
{
    "include": [
        "src/client/client.js",
        "src/client/app/app.jsx"
    ]
}
```

**Comment by mjbvz** [comment]
@svipben Did you have both a `jsconfig.json` and a `tsconfig.json` in your workspace at the same time? I believe you only want a `jsconfig.json` to exist. After creating these files, make sure to reload the VSCode window too in order to make sure the change takes effect.

To check if a given file is in the correct project (that is, associated with the correct `jsconfig.json`), open the `js` file and run the `JavaScript: Go to Project Configuration` command. That should open the corresponding `jsconfig.json` or tell you if the file is not part of a project

If none of this works, if you are able to, please also share an example project so that I can take a better look at the issue

**Comment by svipben** [comment]
Yes, I want only `jsconfig.json` to exist, but I created both, because it wasn't working.

I know how to fix it, it wasn't working, because the file was with `.jsx` extension, it only works for `.js` and `.ts` files and of course you need to have `jsconfig.json` file as you said in the project root.

P.S. Everything works fine except `export default` it says `Could not determine references`, but everything else seems fine ;)

Thank you!
