### ISSUE TITLE
"Save All" replaces file content with other file content.

### ISSUE THREAD

**Issue by amolmk** [Microsoft/vscode#22053]
## - VSCode Version & other details
![image](https://cloud.githubusercontent.com/assets/3015241/23602256/b5898c1a-0275-11e7-9a94-62f9bb705cd1.png)

### **Steps to Reproduce:**
1. Open Multiple files (say file1, file2, file3, file4) from a folder which are already saved (no changes pending to save)
2. Modify say file1 (don't say yet)
3. Go to file 2, Modify something in it.
4. Go to Click on menu "File".
5. Click on "Save All" from the file menu.
6. Check the content on the current file, i.e. file2.
7. All the contents from file1 is overwritten on file2.

**Expected:** Both files should get saved with proper file content.

**Actual:** Only file1 gets saved, file2 is not yet saved & content is overwritten.

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/22330
