### ISSUE TITLE
For files with long rows the word wrap features only works on newly created empty tabs. 

### ISSUE THREAD

**Issue by abdelhakimMouslih** [Microsoft/vscode#22072]
- VSCode Version: 1.10.1
- OS Version: Linux 4.4.0-64-generic #85~14.04.1-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux
- Commit 653f8733dd5a5c43d66d7168b4701f94d72b62e5
- Date 2017-03-02T00:47:58.633Z
- Shell 1.4.6
- Renderer 53.0.2785.143
- Node 6.5.0

description:
the word wrap works perfectly with files containing short lines. But once the lines become too long (2375 characters in my example) the word wrap feature works only on newly opened empty tabs, once i save the tab's content into a new file or i change the tab, the word wrap features does not work anymore.

just to make sure it is not a settings problem, below are my settings for for version 1.9.* and 1.10.1:
- 1.9.1
    "editor.wordWrap": false
    "editor.wordWrapColumn": 300000
- 1.10.1
    "editor.wordWrap": "off"

prerequisites :
 - a file saved on the hard drive with rows containing 2375 characters.
 - word wrap feature toggled off.

Steps to Reproduce:
1. open the file save, the the content is wrapped.
2. open a new tab by pressing Ctrl+N, and copy the content of the file into the new tab, the content is not wrapped and i can side scroll until the end.
3. save the file into the hard drive, the content is wrapped.
4. open another new tab by pressing Ctrl+N, and copy the content of the file into the new tab, the content is not wrapped.
5. go to another tab, and go back to the previous tab, the content is wrapped.

**Comment by Frangible** [comment]
fwiw, this problem did not occur when `editor.wrappingColumn` was set to -1.  Unfortunately, that setting was removed.

The longest single line I've seen in a normal file not wrapping is 1536 characters.  So somewhere between 1536 and 2375 characters, there's some limit that only respects `editor.wrappingColumn`.  

At a minimum, I think the documentation and pop-up message displayed to the user should be changed.  `editor.wordWrap` is **not** a replacement setting for `editor.wrappingColumn` and I've spent hours trying to resolve this unsuccessfully because of the misleading wording, believing that I was doing something wrong or had something misconfigured.  It's rather frustrating.

Searching past issues, `editor.wrappingColumn` appears to have been removed because someone thought it *might* have been potentially confusing to a hypothetical user.  Why is creating more confusion and fixing the then-broken functionality a "backlogged" priority, when the original removal of the feature was given much higher priority?

This has been broken for about two months in the production release.  And given the "backlog" priority it'll be what, six months to a year before it's fixed?  If there isn't adequate time to test or fix this, then it simply needs to be rolled back.

A hypothetical potentially confused user that never existed shouldn't be prioritized over actual, real confused users and broken functionality.

**Comment by alexandrudima** [comment]
Let's track in #21801

@Frangible I'm sorry for the frustration this has caused. There is a workaround on the Insiders Channel since 3 weeks. We identified the issue 2 days before the ship date of 1.10 and it was **a team decision** to not include a fix in 1.10.

---

As a guard against freezes (caused by our non being able to virtualize rendering horizontally), we try to identify "minified" files. (i.e. think minified CSS, minified JS, etc.). We forcefully word wrap minified files.

**On the insiders channel**, the Toggle Word Wrap Action is able to unwrap these files. There is also an undocumented `"editor.wordWrapMinified": false` setting that works for now **on the insiders channel**.

We need to think how to better align the two desires:
* first, our desire to not "freeze" while rendering huge lines (i.e. rendering a frame in < 16ms)
* secondly, the end-user desire to never wrap
