### ISSUE TITLE
vscode.extensions.getExtension case sensitivity behavior has changed

### ISSUE THREAD

**Issue by daviwil** [Microsoft/vscode#22079]
- VSCode Version: VS Code Insiders from last Friday (see screenshot)
- OS Version: Windows 10

![image](https://cloud.githubusercontent.com/assets/79405/23614236/1c966fac-0237-11e7-9fda-7df5378abc3d.png)

Steps to Reproduce:

1. Use `vscode.extensions.getExtension` to get an extension with capital letters (like `ms-vscode.PowerShell`)
2. `getExtension` returns null
3. Call `getExtension` with all characters of extension name lowercased (like `ms-vscode.powershell`)
4. Extension details are returned

This is a **breaking change** because it means I can't support both VS Code 1.10.1 and Insiders concurrently if I change my extension code to adjust to this.  VS Code 1.10.1 allows me to get extension details for `ms-vscode.PowerShell` with that exact casing and returns null if I give it `ms-vscode.powershell`.  

I'm currently using this API to get the current version of my extension to send to my language server.

Any idea what might have changed to cause this?  I'd like to ship an update to my extension soon and I think this bug might cause trouble for my users.

**Comment by sandy081** [comment]
@daviwil Last week I introduced a change in VS Code (insiders) - lowering the case of extension id because it is case-insensitive. Also fixed the issue in the API you mentioned in the description. But later I reverted back all those changes due to more API breakages it might cause. Please refer to issue https://github.com/Microsoft/vscode/issues/19685 for more info.

Latest insiders have the reverting changes. So, please try latest insiders and there will not be any issues. 

Thanks

**Comment by sandy081** [comment]
Duplicates #19685

**Comment by daviwil** [comment]
Thanks Sandeep!  Just tried this with today's Insider build, it's fixed for me now.
