### ISSUE TITLE
stdfork does not respect stderr

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#221]
When creating a process with stdfork the stderr is not passed through.

This feature needs to be implemented in stdFork.ts and stdForkStart.js
Similar to what we already do for stdout, minus the waiting on the 'ready' signal
We also need to the cleanup similar to stdout

**Comment by weinand** [comment]
This is not a feature request but a serious bug: stdfork does respect stderr by sending it to stdout! In case of debug adapters this will corrupt the wire protocol and make VS Code abort the debug session.

Both php-debug and go-debug were hit by this:
https://github.com/felixfbecker/vscode-php-debug/issues/19
https://github.com/Microsoft/vscode-go/issues/206
https://github.com/Microsoft/vscode-go/issues/223

We were not seeing this problem before because VS Code was swallowing json parse exceptions silently and tried to continue running. However both debuggers had reports of mysterious session errors that we can now explain with this error.

We have two options for fixing this:
- introduce a separate named pipe for stderr (real fix, higher risk)
- disabled stderr output (low risk)

Since 'stderr' output is not really supported by VS Code and only shows up in the dev tools console, I think we should implement the low risk option for GA.

**Comment by felixfbecker** [comment]
@weinand I think the issue you linked was not caused by this, but I got several reports at my [Gitter channel](https://gitter.im/felixfbecker/vscode-php-debug):
![debug2](https://cloud.githubusercontent.com/assets/10532611/13668331/681b66fe-e6bc-11e5-8e63-cc60217188dc.gif)
![debug](https://cloud.githubusercontent.com/assets/10532611/13668340/6c3164dc-e6bc-11e5-8677-8affb6f3500a.gif)

I fixed them by eliminating every single occasion where logs could get output to stderr or stdout (some of which I wasn't even aware of, it was a dependency that logged stuff without my knowledge). But I constantly wondered why these issues only appeared since the Feb release. If VS Code swallowed JSON parse errors before, that is an explanation.
