### ISSUE TITLE
Track TS Server Extension API

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#22101]

**Comment by mjbvz** [comment]
Our current proposal for the implementation: 

---

The agreement with the TS team was that plugins will come through VSCode extensions. For example, if a user wants enhanced angular language support, they would install an `angular` VSCode extension that then contributes an angular TSServer plugin.  Here's a proposal of how this will be implemented:
 
In the VSCode TypeScript extension, during activation we pick up a list of contributed TSServer plugins from other installed extension. This list would come from entries in each extension's package.json:
 
```json
    {
        "contributes": {
            "typescript-plugins": [
                  "tss-angular-plugin",
                  "tss-html-plugin"
            ]
        }
    }
 ```
 
When starting the TypeScript server, the VSCode TypeScript extension will provide a list of plugin that we know about, along with the directories to search for installed plugins:
 
```
tsserver -   -plugins=tss-angular-plugin;tss-html-plugin     --plugin-dirs=/Users/matb/.code/extensions/angular-extension/;...
 ```

When resolving the plugins themselves, typescript would first search adjacent to its own install and then in each of the `plugin-dirs`. This avoids the potential security issues because we only load a plugin from a user's workspace if they have already trusted the typescript instance in that workspace.

**Comment by mjbvz** [comment]
Closing this since the investigation part is mostly complete. We'll look into prototyping plugin support next month

**Comment by kieferrm** [comment]
@mjbvz here is a more complete write-up.

### Context
The TS server is extensible via plugins. Plugins fall in two categories:
 - better TypeScript or JavaScript support through additional problem analysis and quick fixes
 - support for mixed languages that make use of TypeScript or JavaScript

For the first categories of plugins is straight forward. VS Code already knows that the TS server is taking care of TS and JS files. For the second category, configuration is required as VS Code needs to know about the new file types that the TS server can handle.

All plugins need to be installed at locations that the TS server knows. Which of those plug-ins a TS server uses for a given project is specified in the project's `tsconfig.json` file. In theory, a TS server could come with VS Code while its plugins come from a `node_modules` directory in the user's workspace.

### Constraints

In order to support TS server plugins in VS Code we need a solution that:
- allows to configure which file types are supported by the TS server
- ensures that VS Code does not run any plugins from the user's workspace without the user's explicit confirmation
- uses the existing mechanisms of the VS Code TypeScript extension 

### Proposal

Plugins will come through VS Code extensions. For example, if a user wants enhanced `angular` support, they would install an `angular` VS Code extension that then contributes an angular TS server plugin as well as the file mappings for `.ng` (and other) files.

We will implement this as follows:
 
On activation, the VS Code TypeScript extension will pick up a list of contributed TS server plugins from other installed extension. This list comes from entries in `package.json` files:
 
```json
    {
        "contributes": {
            "typescript-plugins": [
                  "tss-angular-plugin",
                  "tss-html-plugin"
            ]
        }
		*** TBD file type spec ***
    }
 ```
 
When starting the TS server, the VS Code TypeScript extension will provide a list of known TS server plugins, along with their installation directories:
 
```
tsserver -plugins=tss-angular-plugin;tss-html-plugin     --plugin-dirs=/Users/matb/.code/extensions/angular-extension/;...
 ```
When resolving the plugins listed in `-plugins`, the TS server first searches adjacent to its own install and then in each of the `-plugin-dirs`.

When the TS server is being run out of the user's workspace or is specified through a `tsdk` entry in the workspace or user settings, the VS Code TypeScript extension will not pass any value for `-plugin-dirs`. This means, that the TS server can only resolve plugins using the workspace or `tsdk` location.  This avoids any potential security issue because the TS Server will only load plugins from the user workspace or an external local if it itself comes from those locations and has been confirmed by the user.

**Comment by egamma** [comment]
@kieferrm @mjbvz I've created a VS Code extension (`vscode-ts-lint`) for the `tslint-language-service` using the `typescriptServerPlugins` contribution point. See the package.json included below.

However, there is an issue with how the `tslint` module can load the `typescript` module it requires. To describe the issue, let me first explain the setup, when the language server plugin is installed into a workspace using `npm install tslint typescript tslint-language-service`. This results on the following layout inside the `node_modules` folder.
```
node_modules
   tslint
   tslint-language-service
   typescript
```
Notice that the typescript module is a peer to the tslint module and the `tslint` module can require the `typescript` module. This is the _same_ typescript module that is used by vscode's typescript server.

Now, the question is what dependencies should be defined for the vscode extension? To make the extension work I had to include `typescript` as a dependency otherwise `tslint` cannot find the `typescript` module and the `tslint-language-service` plugin does not load. However, the `tslint` module should use the same `typescript` module that is used by the vscode typescript server? It is not clear to me how to achieve this and what the consequences are when the typescript module versions diverge.

`package.json`
```json
{
    "name": "vscode-ts-tslint",
    "displayName": "vscode-ts-tslint",
    "description": "tslint integration as a TS server plugin",
    "version": "0.0.1",
    "publisher": "eg2",
    "engines": {
        "vscode": "^1.11.0"
    },
    "categories": [
        "Other"
    ],
    "main": "./out/src/extension",
    "contributes": {
        "typescriptServerPlugins": [
            "tslint-language-service"
        ]
    },
    "scripts": {
        "vscode:prepublish": "tsc -p ./",
        "compile": "tsc -watch -p ./",
        "postinstall": "node ./node_modules/vscode/bin/install",
        "test": "node ./node_modules/vscode/bin/test"
    },
    "devDependencies": {
        "typescript": "^2.0.3",
        "vscode": "^1.0.0",
        "mocha": "^2.3.3",
        "@types/node": "^6.0.40",
        "@types/mocha": "^2.2.32"
    },
    "dependencies": {
        "tslint-language-service": "^0.9.2",
        "tslint": "^5.1.0",
        "typescript": "^2.3.1"
    },
    "extensionDependencies": [
        "vscode.typescript"
    ]
}
```
