### ISSUE TITLE
Support to synchronize dirty changes across windows

### ISSUE THREAD

**Issue by ColorFuzzy** [Microsoft/vscode#22128]
- VSCode Version: Code 1.10.1 (653f8733dd5a5c43d66d7168b4701f94d72b62e5, 2017-03-02T00:27:09.350Z)
- OS Version: Darwin x64 16.4.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|beautify|HookyQR|0.8.8|
|python|donjayamanne|0.5.8|
|rest-client|humao|0.12.3|
|vscode-icons|robertohuertasm|7.3.0|;

---

Steps to Reproduce:

1. open a window A and open a file F in that window
2. open a new window B(Shift-command-N), drag that file F to window B
3. now file F on both window A and B, change content of F on window A without save, **the unsaved content doesn't display on window B**.

**Comment by ramya-rao-a** [comment]
cc @Tyriar

**Comment by bpasero** [comment]
We do not support this today, so marking as feature request.

**Comment by Tyriar** [comment]
Something we'd have to deal with for this is what happens when a hot exit restore happens and it contains different content to the current "workspace copy":

1. Set `"files.hotExit": "onExitAndWindowClose"`
2. Open window with folder `a`
3. Edit file `foo`
4. Close window with folder `a`
5. Open window with folder `b`
6. Edit file `foo`
7. Open window with folder `a`, at this point folder `a`'s backups would be restored (changes in step 3) which are different to the current changes (in step 6).

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/11866
