### ISSUE TITLE
Format Typescript code cause error

### ISSUE THREAD

**Issue by eos3tion** [Microsoft/vscode#22144]
- VSCode Version: 1.10.1
- OS Version: Win10 14393.693
- Extensions:
code-settings-sync - Version :2.5.1
cpptools - Version :0.10.2
csharp - Version :1.7.0
debugger-for-ios-web - Version :0.1.2
docthis - Version :0.4.3
EgretCode - Version :0.0.3
git-project-manager - Version :1.0.1
gitblame - Version :1.3.0
gitflow - Version :1.1.0
githistory - Version :0.1.5
gitlens - Version :2.10.1
json2ts - Version :0.0.6
vscode-generate-getter-setter - Version :0.4.2
vscode-npm-source - Version :1.0.0
vscode-typings - Version :0.0.5

Steps to Reproduce:
![formaterror](https://cloud.githubusercontent.com/assets/8804051/23656197/a515621a-0373-11e7-8637-3763f3753b06.gif)
When i format this file(https://github.com/egret-labs/egret-core/blob/master/src/egret/utils/ByteArray.ts)
The code broken,some word split with blank.

**Comment by mjbvz** [comment]
Thanks. I've opened https://github.com/Microsoft/TypeScript/issues/14513 to track this upstream.

The root cause is the comment on line 312, which seems to contain an unicode sequence that is not renderable

<img width="861" alt="screen shot 2017-03-07 at 10 19 21 am" src="https://cloud.githubusercontent.com/assets/12821956/23671297/999de2c6-031f-11e7-9969-8609228dc6f6.png">

After line 312, all line numbers returned by TypeScript are shifted down by one, which causes the formatting operations are being applied to the wrong lines
