### ISSUE TITLE
Close button on notebooks is broken

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#221582]
* open a notebook, like `.vscode/notebooks/my-work.github-issues`
* select `X` to close
* :bug: nothing happens...

**Comment by bpasero** [comment]
The issue here is that we wrongly assume we are in list context:

https://github.com/microsoft/vscode/blob/5b5e760015c063cd44e987e4f2e5316a8ff412e2/src/vs/workbench/browser/parts/editor/editorCommandsContext.ts#L63-L64

Because in a notebook, if you focus a markdown part (above the editor), focus is on a list widget.

Previously for editor commands at least we did fallback to the active editor:

https://github.com/microsoft/vscode/blob/f1e16e1e6214d7c44d078b1f0607b2388f29d729/src/vs/workbench/browser/parts/editor/editorCommands.ts#L1371-L1377

We seem to not be doing this anymore, or only when no context is present:

https://github.com/microsoft/vscode/blob/5b5e760015c063cd44e987e4f2e5316a8ff412e2/src/vs/workbench/browser/parts/editor/editorCommandsContext.ts#L69-L75

**Comment by bpasero** [comment]
**Verification:**
- set `workbench.editor.showTabs` to `single`
- open a notebook (such as GitHub Issues)
- click the "X" button top right to close
- ensure you can close the notebook
- try with a normal text editor too
