### ISSUE TITLE
Initial terminal dimensions are reload are incorrect

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#221580]
Repro:

1. Open a terminal
2. Reload window
3. Select some rows in terminal, 🐛 the selection should show columns reaching to near the scroll bar

![image](https://github.com/user-attachments/assets/fdb41423-c9eb-4742-8273-d2051d52879a)

**Comment by Tyriar** [comment]
Repro requires `"terminal.integrated.gpuAcceleration": "on"`

**Comment by jaminthorns** [comment]
I'm not able to verify that this is fixed in the latest insiders build.

Version: 1.93.0-insider (Universal)
Commit: 3b27f1f74bc09fe2e2068997fcd42768be44a4e3
Date: 2024-08-02T05:03:53.254Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.6.0

Additionally verified that commit 79f680f373c7a5dbafb3813378e0fa73fa2da4f3 was in the build I was testing in:

```
▶ git merge-base --is-ancestor 79f680f373c7a5dbafb3813378e0fa73fa2da4f3 3b27f1f74bc09fe2e2068997fcd42768be44a4e3 && echo Has fix || echo No fix
Has fix
```


https://github.com/user-attachments/assets/f13ec7af-843e-45fd-b6ef-6f31981607c2

**Comment by jeanp413** [comment]
PR fixing it https://github.com/microsoft/vscode/pull/225554
