### ISSUE TITLE
debug console code completion stays after closing function parenthesis, with __defineGetter__ highlighted

### ISSUE THREAD

**Issue by ilovett** [Microsoft/vscode#22183]
- VSCode Version: 1.10.1
- OS Version: Mac 10.11.6

Steps to Reproduce:

code completion menu tends to stick around after closing parenthesis, but highlights the top of the menu `__defineGetter__`.  What happens is you write `.somefunc` which in the case which has the context menu showing, and then you complete `.somefunc()`, but then the completion menu still shows with `__defineGetter__` at the top

![image](https://cloud.githubusercontent.com/assets/1776100/23680968/ef5270ac-0341-11e7-8f46-97dbb58fce91.png)

You finish writing your function and then press enter, but get the trailing `__defineGetter__` on the end which is really annoying.

This is using type `node` for debugging.

**Comment by isidorn** [comment]
There are a couple of issue here:
1. Debug adapter should not propose all those things since it is being passed the full line and the current location @weinand 
2. Suggestions should not popup automatically when brackets are opened. Can this be configured? @jrieken 
3. Maybe some collision with https://github.com/Microsoft/vscode/issues/11944

**Comment by jrieken** [comment]
Generally, wee have quick suggestion enabled by default. That means we constantly ask for completion while the user types. You can turn that off for each editor, tho that will not fix the problem. I believe the underlaying issue is that the provider still returns some (meaningless?) suggestions in that case. To know the truth debugging is needed, but i definitely is related to the change we made which keeps completion results *incomplete* and there asks a lot more frequent

**Comment by isidorn** [comment]
After debugging the issue seems to be that the node adapter returns all those results after being asked for completions for` column: 10` in `text: Date.now()`. Debug adapter should not return all those results, however I think we should protect on our vscode side from bad completions by doing smart filtering.
fyi @weinand 

@jrieken If I remove our  incomplete "fix" this issue is fixed, since we smartly filter on the vscode side. However then the original issue we fixed is broken as suggest widget filters out items that have `overwriteBefore`

**Comment by jrieken** [comment]
Yes, you then must implement the proper fix which is setting the filter text correctly when computing the suggestion and overwriteBefore

**Comment by isidorn** [comment]
After lots of tweaking I deduced that the filterText needs to also contain the full label, to be more precise in order to get 'hello world' as the proposal as you are typing it the filter text must be `.hello world`
You can check out 094d4c0, but after trying it out it works fine and seems to not break anything

**Comment by weinand** [comment]
@isidorn I'm no longer returning proposals after a closing ')'
