### ISSUE TITLE
Snippets don't show up after trigger characters

### ISSUE THREAD

**Issue by wenkeming** [Microsoft/vscode#22205]
希望用户的snippet永远放在首选位置
Hope that the user's snippet will always be in the preferred position

**Comment by ydcoming** [comment]
what?

**Comment by anchenbaba** [comment]
haha

**Comment by ramya-rao-a** [comment]
Google Translation of the title: 

> VS CODE is not developed by Microsoft? It is strange why the screenshots are basically the MAC version of it, do Microsoft staff with the MAC

Well, VS Code is definitely developed by Microsoft and lots of other amazing people in the open source community.
Our team is a mix of people working on Mac, Windows and Linux, so thats what you see in the blogs and release notes :)

And I have no idea about your remark on the snippet. Can you elaborate?

**Comment by Rwing** [comment]
原谅我要说脏话了，智商真tm是硬伤

**Comment by wenkeming** [comment]
标题只是玩笑话，内容才是正题 @Rwing

**Comment by wenkeming** [comment]
@ramya-rao-a Here is a screenshot
![gif](https://cloud.githubusercontent.com/assets/8252267/23733782/c30fcc4a-04b5-11e7-8f51-8b5f752637c3.gif)

**Comment by ramya-rao-a** [comment]
@wenkeming 

Regarding your first example:
snippets work only when the prefix (in your case `ac`) is a complete word in itself. When its a suffix of another word, the snippet does not get triggered. That is by design. @jrieken correct me if I am wrong here..

In you second example, I dont follow what the issue is.
You have defined a new snippet for `if` and I see it works. Am I missing something?

**Comment by jrieken** [comment]
Please share the snippet with us

**Comment by wenkeming** [comment]
@jrieken This is the link to the snippet I defined
[https://onenote.com/webapp/pages?token=VAv-gSd67UOQX057dFGT798ot-qSMANuZp5PWO48O1tLdaInqpB_B34-FcYVaVY_JPhjeok32fZUDe2rU9BdJRzrJKsbqoXC0&id=636249714902292882
](url)

**Comment by wenkeming** [comment]
I have temporarily found a way to use autohotkey script. When I enter `.`, It will automatically trigger esc, and then there is my custom snippet

> ; vs code custom snippet
#IfWinActive ahk_exe Code.exe
:*b0:.::
Sleep 100
Send {Esc}
Return

**Comment by jrieken** [comment]
@wenkeming The link to the snippet isn't working. Please paste the snippet here as comment

**Comment by wenkeming** [comment]
> {
&emsp;"jq add class": {
&emsp;&emsp;"prefix": "ac",
&emsp;&emsp;"body": "addClass('$1')$2"
&emsp;},
&emsp;"if": {
&emsp;&emsp;"prefix": "if",
&emsp;&emsp;"body": [
&emsp;&emsp;&emsp;"if($1) {",
&emsp;&emsp;&emsp;&emsp;"\t$2",
&emsp;&emsp;&emsp;"}"
&emsp;&emsp;]
&emsp;},
}

**Comment by jrieken** [comment]
Ok, understood. The issue is that when typing `$('something')` and `.` (dot) triggers completions only for Javascript. That is because `.` is a completion trigger character (in this case for JS member completion) and we only query those provider that have registered for `.`. So, this kind of works by design but I also understand that it's undesirable... Needs some thinking...

**Comment by wenkeming** [comment]
OK. thanks @jrieken

**Comment by jrieken** [comment]
We won't trigger snippets after trigger character because they are kind of private to the extensions that have registered for it. Tho when we fix #26275 the situation here might get better.
