### ISSUE TITLE
File changes not reported after update to 1.91.1

### ISSUE THREAD

**Issue by alasdairwilson** [microsoft/vscode#222098]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
Version: 1.91.1 (user setup)
Commit: f1e16e1e6214d7c44d078b1f0607b2388f29d729
Date: 2024-07-09T22:06:49.809Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.19045

Extensions:
Issues are still present with only the WSL remote extension enabled.

I don't know the cause of this and can't provide any reproduction steps but since updating today to the latest version of vscode the source control git integration has become buggy and unresponsive in several ways.

- Changes do not appear in the sidebar unless a manual refresh is performed (even after trying "git.autorefresh": true,)
 - Related: Staging changes via terminal are not reflected in the sidebar without a refresh
- Committing is very slow, commits from the terminal are not reflected quickly in the sidebar
- Upon rebasing a branch and force pushing, the "sync changes" button did not reflect the remote and local branches were equivalent (still said 3 ahead 7 behind) clicking sync changes caused it to sit there with the progress indicator until it was closed and reopened. 
- Swapping branches via the ui was very slow, checking out branch is not reflected in sidebar without manual refresh

I don't know if this is a just me issue as I can't see any other issues about this in github.

**Comment by torickjdavis** [comment]
This appears to be related to issue #221378.

**Comment by claycoleman** [comment]
major +1 from me, this ends up being a major blocker as the source control status and edited files used to update on window refocus, file save, and other scenarios, but now requires a manual click of the refresh button to get latest data. like OP said, it seems to happen sporadically and seems to work for a period of time before it gets into a bad state.

**Comment by fredrik-j-lindberg** [comment]
Same issue here on the same version, have to manually refresh the source control for every change to be reflected

Renaming of files also did not prompt me to fix imports, not sure if that is related

**Comment by lszomoru** [comment]
If you are able to reproduce this issue consistently, could you please follow [this wiki](https://github.com/microsoft/vscode/wiki/File-Watcher-Issues) and share the logs for the file watcher? 
This should help us track down whether the issue is related to the file watcher of the git extension. Thank you!

**Comment by fredrik-j-lindberg** [comment]
I seem to have no output from file watcher tried with "File Watcher" as well), let me know if I am doing something wrong @lszomoru 

https://github.com/user-attachments/assets/c1868051-f772-4b5b-af88-7a5924e85cac

**Comment by lszomoru** [comment]
@bpasero, do you mind taking a look at [this](https://github.com/microsoft/vscode/issues/222098#issuecomment-2258094082). Thank you!

**Comment by bpasero** [comment]
This issue could originate from a problem with file watching. Let me explain how file watching works in VSCode first and then provide some details how to get more logging data from how file watching behaves in your case.

**Synopsis**
VSCode has different strategies for file watching depending on your workspace and setup:
* no folder opened: files in opened editors are watched via node.js `fs.watch`
* folder opened: folder is watched recursively for all changes via [parcel](https://github.com/parcel-bundler/watcher), opened editors with files not within the folder are watched via node.js `fs.watch`

If you are connected to a remote (SSH, WSL, Docker), the file watcher will run within the target file system. As such, even though you maybe on Windows where VSCode runs, if the remote is Linux, the file watcher will run in the Linux environment.

**Platforms**
Depending on the platform you are on, file watching is differently implemented:
* macOS: using `fsevents` services
* Windows: using `ReadDirectoryChangesW` method
* Linux: using `inotify`

Specifically on Linux, watching a large folder recursively can result in VSCode consuming too many file handles. If that is the case, you will see a warning notification with instructions how to solve that.

**Limitations**
File watching comes with a set of limitations:
* symbolic links are not followed automatically but you can explicitly add symbolic links to be watched via the `files.watcherInclude` setting
* mapped network drives or third party file system drivers are not guaranteed to produce file events
* in general, the operating system may decide to drop file events at any time, there is no 100% guarantee

**Settings**
Please review your settings to see if maybe a folder is excluded by accident. Specifically, the `files.watcherExclude` setting is relevant.

**Logging (local)**
!!! This is ONLY when you open a local workspace, for remote see below !!!
We provide logging for file events when you enable verbose logging. Steps are:
* open VSCode on the local workspace that shows the issue
* select `View | Command Palette...`
* select `Developer - Set Log Level...`
* pick `Trace`
* select `View | Output`
* select `File Watcher` from the dropdown on the right
* attach the output when doing the operation that exhibits the issue

<img width="907" alt="image" src="https://github.com/user-attachments/assets/fa2ce77e-2381-4cda-9841-5270a956c5bb">


**Logging (remote)**
!!! This is ONLY when you open a remote workspace (WSL, Docker, SSH), for local see above !!!
We provide logging for file events when you enable verbose logging. Steps are:
* open VSCode on the remote workspace that shows the issue
* select `View | Command Palette...`
* select `Developer - Set Log Level...`
* pick `Trace`
* select `View | Output`
* select `Log (Remote Server)` from the dropdown
* attach the output when doing the operation that exhibits the issue

![image](https://user-images.githubusercontent.com/900690/156323886-6b7dfa25-d6ac-4316-9150-80e5c8104d04.png)

**Comment by fredrik-j-lindberg** [comment]
But the logs provided no info whatsoever @bpasero, see my video [above](https://github.com/microsoft/vscode/issues/222098#issuecomment-2258094082)

**Comment by fredrik-j-lindberg** [comment]
I just realized that the guide that you send @bpasero sightly differs from the wiki guide, by the looks of it yours is telling me to look in the output tab for it. But I don't have any option to select it there:
<img width="904" alt="image" src="https://github.com/user-attachments/assets/1316d3b2-7ca6-4f28-8f49-0059b94f778f">

**Comment by fansek** [comment]
Hi all,

I had the same issue.

A moment ago I decided to install an older version of VS Code (version 1.90) from [this site](https://code.visualstudio.com/updates/v1_90)
and file watching began to work.

Then I retried to update VSCode just to see if there are any differences in File Watcher output between 1.90 and 1.91, but after VSCode restart there was no File Watcher option in the dropdown menu of output view and file watching stopped to work again.

Then I found out that I had some extensions enabled. So I disabled them and file watching started working again. I discovered, that it was ESLint in combination with the new VS Code that was probably causing the trouble in my case. However, after a couple of times of restarting VSCode with extensions either disabled or enabled, it currently works with enabled extensions and I can't reproduce the issue anymore.

Do you guys also tried to run VS Code with disabled extensions?

My current configuration:

Version: 1.91.1
Commit: f1e16e1e6214d7c44d078b1f0607b2388f29d729
Date: 2024-07-09T22:07:46.768Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.5.0

**Comment by ZenabKhan** [comment]
Hey I have the same issue. I followed @bpasero steps. Sharing my filewatcher screenshot

<img width="1134" alt="Screenshot 2024-07-30 at 15 29 47" src="https://github.com/user-attachments/assets/de887d58-4728-40b5-8ec0-4adcd66cb0af">

**Comment by bpasero** [comment]
Does it help at all to set `typescript.tsserver.experimental.useVsCodeWatcher` to `false` in settings and restart?

**Comment by fredrik-j-lindberg** [comment]
That seems like it did the trick for me! 🙏 Both the source control and the file renaming now works for me

_FYI I am heading off to vacation for two weeks so I will be unable to help further debugging this, but thanks for looking into it and providing a fix!_

**Comment by ZenabKhan** [comment]
@bpasero 
> typescript.tsserver.experimental.useVsCodeWatcher to false 

works me. Thanks 🙏

**Comment by bpasero** [comment]
Can people that are impacted share steps how to reproduce, specifically what workspace they open and which extensions are involved?

**Comment by liamdawson** [comment]
I think it might be related to using `pnpm` in my case — maybe heavy usage of symlinks in the `node_modules` folder causes issues? Wiping `node_modules` and reinstalling them using `bun` instead seemed to resolve the issue when I reloaded the window.

**Comment by bpasero** [comment]
@liamdawson thats a good finding, would you be able to share a repro with me that I can follow along to test this step by step?

Are others also using a setup like that?

**Comment by fansek** [comment]
Hi @bpasero, I also use pnpm. However, `files.watcherExclude` config  param with `**/node_modules/*/**` pattern should exclude any `node_modules` directory from watching, shouldn't it?

**Comment by bpasero** [comment]
@fansek only for the workspace watcher VS Code installs, however with `typescript.tsserver.experimental.useVsCodeWatcher: true` (which is the default), TypeScript extension will install watchers specifically in the `node_modules` folder and the setting has no effect in that case because extensions fully drive the file watching.

With `typescript.tsserver.experimental.useVsCodeWatcher` set to `false`, TypeScript leverages node.js built in watching, which probably does not fall over circular symlinks.

Again, a repro would be great on a repo I can try with!

**Comment by fansek** [comment]
@bpasero I just cloned [pnpm repository](https://github.com/pnpm/pnpm) and tried to change any file. File watcher was activated as expected. However, then I installed dependencies with `pnpm install` and after changing the same file, no change appeared in source control.

**Comment by liamdawson** [comment]
> @liamdawson thats a good finding, would you be able to share a repro with me that I can follow along to test this step by step?
> 
> Are others also using a setup like that?

I don't have the capacity to put together a repro right now, sorry, but sounds like @fansek found one.

**Comment by bpasero** [comment]
@fansek I tried to follow your steps but see no issue so far, here is what I did:
* `git clone https://github.com/pnpm/pnpm.git`
* `brew install pnpm`
* run `pnpm install` from the `pnpm` repository checkout
* open VS Code on the `pnpm` repository checkout
* make sure `dbaeumer.vscode-eslint` extension is installed and running
* open the file `network/auth-header/src/getAuthHeadersFromConfig.ts`
* make a change to this file externally
* it updates

Then I also tried to log the file watcher stats:
* "Developer: Set Log Level" and pick "Trace"
* in the "Output" panel from the channel dropdown pick "File Watcher"
* see that there are around 11 recursive watchers and 8 non-recursive watchers

Anything I missed?

**Comment by fansek** [comment]
I am not able to reproduce the issue reliably. When I was writing my previous comment, I already got ESLint installed. Then I ran `pnpm install` in pnpm project workspace. Then file watcher stopped working.

However, now I tried to reinstall ESLint multiple times with getting fresh clone of pnpm repository and file watcher was working almost* all the time.
*There were two times it stopped working, but when I repeated the same steps I was never able to get the same result. I have no clue why.

**Comment by cpojer** [comment]
I have been running into this consistently since the last update. I'm working on [Athena Crisis](https://athenacrisis.com), a video game which is also open source: https://github.com/nkzw-tech/athena-crisis

The open source repo is a subset of the internal one, but you should be able to reproduce the issue as the setup is exactly the same. Check out the README on how to get it running. A good way to repro I've found is to create a new file (maybe in the `hera` folder), write out the name of an adjacent import/module name, hit `cmd+.` and it won't help with the auto-import until you restart the TS server.

**Comment by bpasero** [comment]
@cpojer cool game!

When I try this out, I am not able to see your issue though (I am on macOS). When I do the steps to get the "File Watcher" output, I see these stats which indicates quite a high use of recursive watchers:

```
[File Watcher] request stats:

[Summary]
- Recursive Requests:     total: 135, suspended: 2, polling: 2
- Non-Recursive Requests: total: 1043, suspended: 150, polling: 0
- Recursive Watchers:     total: 133, active: 133, failed: 0, stopped: 0
- Non-Recursive Watchers: total: 893, active: 8, failed: 6, reusing: 879
- I/O Handles Impact:     total: 143
```

I think in general with the changes we did behind the `typescript.tsserver.experimental.useVsCodeWatcher` setting, projects that are composed of many hundreds to thousands TS projects within now produce a lot more load on our internal file watcher (https://github.com/parcel-bundler/watcher). Typically so far we only had 1 recursive watcher per workspace root, but with the changes in the TS extension we now get at least 1 recursive watcher per TS project in the workspace. This watcher will go into `node_modules` folder, unlike the workspace level one we have because TS extension needs to be aware of changes in `node_modules`.

Still, I am not sure what condition triggers this problem you are all seeing. Somehow the watcher process ends up going into a high-CPU state and does not recover. In that state it is unable to produce file events, nor produce any logging...

**Comment by cpojer** [comment]
@bpasero I'm sorry if I'm not of more help since I don't have context on what changed in VS Code. All I can say is that VS Code's file handling was spotless, and now it cannot detect changes from outside (like when I run some codegen), and TS frequently has outdated or no information about imports. It's also notable when changing branches etc. in the terminal. VS Code used to immediately notice file changes and now it only does when I navigate to the tab with that file.

In terms of the repo I shared, it's about 100k lines of code, but there is lots of private code for which the node_modules are still installed (for easier syncing). It's using the latest version of basically everything, and is likely more modern and "cleaner"/"pickier" in terms of third-party libraries. The TypeScript setup is likely stricter than most and uses modern settings like for module resolution. My hope was that it helps triage the issue.

Since you are saying the difference is that you are now observing `node_modules`, I would assume that it is related to how pnpm works with linking? Is it possible that the new watcher watches each package individually at its pnpm global cache location instead of just the project's `node_modules`, and that throws VS Code/TS off in some way?

**Comment by bpasero** [comment]
No worries, just to confirm: you are on macOS right?

**Comment by cpojer** [comment]
Yes, latest macOS, latest node, pnpm etc. I update everything daily.

**Comment by bpasero** [comment]
And when this happens, can you confirm that the file watcher process is at 100% CPU, not recovering?



![Image](https://github.com/user-attachments/assets/8475d11b-2871-4683-8cfa-be560e341eed)

**Comment by cpojer** [comment]
I'll take a screenshot when it repros the next time.

**Comment by bpasero** [comment]
There should always be a `fileWatcher` process as child from the main process in VS Code, even on Linux. Yes, we use `inotify` but we always isolate the file watcher process from the rest by using a child process.

**Comment by bpasero** [comment]
@slavos1 you can use VS Codes built in process explorer (from the help menu) to spot it:



![Image](https://github.com/user-attachments/assets/9d7dd172-cdf0-4cce-be6b-aea0f8d84a61)


Note: if you are connected to a remote machine, the file watcher would run inside the remote.

**Comment by cpojer** [comment]
@bpasero I ran into it a few more times, but muscle memory kicked in too quickly and I restarted the TS server each time 😅 I just created another file in the project mentioned above, in `athena/lib`. When trying to auto-import symbols via `cmd+.`, I saw that the file watcher was indeed stuck at 100:

![CleanShot 2024-08-05 at 10 42 23@2x](https://github.com/user-attachments/assets/adafb3fc-b7e2-4700-9ffb-7a58f45107a8)

**Comment by ericallam** [comment]
This has been happening to me, and I saw this in my File Watcher log. That `@trigger.dev/core-apps` is an cross-monorepo package that was being set as a dependency of another monorepo package with `workspace:*`. I was doing some refactoring and have removed the `core-apps` package. We also use pnpm.

![CleanShot 2024-08-07 at 13 33 34](https://github.com/user-attachments/assets/933ef55c-dd1b-4cae-a3e3-2b88465e5f54)

**Comment by bpasero** [comment]
That log message is actually fine, we have some logic to handle paths either missing or being added or deleted while watching. It should not result in a 100% CPU spike.

**Comment by ericallam** [comment]
@bpasero 👍. As it happens, I'm currently experiencing a 100% spike in the file watcher process (no output from the file watcher though). Is there something I can do to help debug this?

**Comment by levrik** [comment]
I'm seeing the same issue as @cpojer since likely 1.92.0. I have no idea what triggers it so far.

**Comment by morganick** [comment]
@bpasero I'm also running into this issue on 1.92.1 (Universal) I found that there was a `Code Helper` process stuck at 100% CPU. After killing that process, things came back to life.

**Comment by levrik** [comment]
VS Code became unusable for me. The merge conflict editor is showing me outdated file contents, complains about overwriting changes. The source control view needs manual refreshes all the time. I need to restart the TS server every time I create a new file, move a file or delete a file for it to pick up these changes. Auto-imports are broken.

I didn't manage to find out when exactly it starts yet. Couldn't find anything interesting in VS Code logs. I tried disabling letting TS use the the VS Code file watcher as suggested in https://github.com/microsoft/vscode/issues/226045. Let's see if it helps. Mabye TS' usage of VS Code's file watcher makes it go rogue.

**Comment by morganick** [comment]
@levrik I'm having a similar experience. I find the git integration unreliable. I've turned off the commit graph visualization to see if it helps. I haven't found what triggers this yet.

**Comment by bpasero** [comment]
@rickbrenn do you have steps for me to reproduce, i.e. is the repo open source?

**Comment by levrik** [comment]
@rickbrenn I guess that's what is happening for me as well. Happens most of the time when switching branches, doing interactive rebases or something similar which tends to touch a lot of files. Also using PNPM.

**Comment by levrik** [comment]
It just happened again for me. File watcher logs are spammed by things like this:

```
2024-09-10 16:27:17.378 [trace] [File Watcher (node.js)] reusing an existing recursive watcher for /Users/levrik/code/<redacted>/node_modules/.pnpm/@material-ui+core@4.12.4_@types+react@18.3.5_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@material-ui/core/StepContent/package.json
```

It seems like it tries to re-watch every single file within `node_modules`. I was doing an interactive rebase at the time. It shouldn't cause any changes in `node_modules`.

**Comment by rickbrenn** [comment]
@bpasero Unfortunately it's not open source so I cannot share but I might be able to replicate a repo with similar attributes for testing/reproducing the issue. It is a large monorepo with a lot of dependencies using pnpm which I assume is the factors needed for reproducing the issue since it seems to be because of the watcher watching/updating for every dependency in the node_modules folder.

I am able to confirm that the `typescript.tsserver.experimental.useVsCodeWatcher` setting does fix the issue. Interestingly I have not had the issue occur today even after turning that setting back on. Maybe it only starts occurring after some 'wear and tear' 😆 . 

When the issue happens I see tons of logs in the console like this one:
```
log.ts:399 TRACE MainThreadFileSystemEventService#$watch(): request to start watching correlated (extension: vscode.typescript-language-features, path: file:///Users/rick-brenn/Documents/projects/<redacted>/node_modules/.pnpm/streamsearch@0.1.2/node_modules/streamsearch/package.json, recursive: false, session: 0.7449346843230897)
```

and this one:
```
log.ts:399 TRACE MainThreadFileSystemEventService#$unwatch(): request to stop watching (session: 0.8481027998060857)
```

Then in the filewatcher output panel there are tons of logs like this one:
```
2024-09-09 16:23:35.039 [trace] [File Watcher (parcel)] correcting a path to watch that seems to be a symbolic link or wrong casing (original: /Users/rick-brenn/Documents/projects/<redacted>/packages/<redacted>/node_modules/csvtojson, real: /Users/rick-brenn/Documents/projects/<redacted>/node_modules/.pnpm/csvtojson@2.0.10/node_modules/csvtojson)
```

where it seems to be changing all the symbolic links from the individual monorepo package's node_modules to the root node_modules.

**Comment by rickbrenn** [comment]
Additionally something I noticed is that when running the 'reload window' command to fix the issue, it can occur during reload which I then have to reload the window again until it doesn't. I assume that is because when it starts up the watcher it has to start watching all of those files in node_modules which can trigger it.

**Comment by cpojer** [comment]
Just summarizing, the evidence so far points at the issue being with pnpm, likely with how it links and lays out `node_modules`. Setting `typescript.tsserver.experimental.useVsCodeWatcher` to false fixes the issue for me and many others. When I turn on the experimental watcher, the issue reappears almost immediately.

**Comment by bpasero** [comment]
ℹ I would appreciate if people impacted here could try out our latest insiders build (commit `c4efe1dc9eec4914f3076b2d954fe4fe174a5820`). It includes a change to reduce the pressure of file watching from the TypeScript extension.

**Steps:**
* download insiders from https://code.visualstudio.com/insiders/
* configure `typescript.tsserver.experimental.useVsCodeWatcher` to the default value of `true`
* please make sure your `files.watcherExclude` setting does not include `**/node_modules/*/**`
* perform your workload that was showing issues

Happy to hear back how it goes 🙏

**Comment by zxcodes** [comment]
> ℹ I would appreciate if people impacted here could try out our latest insiders build (commit `c4efe1dc9eec4914f3076b2d954fe4fe174a5820`). It includes a change to reduce the pressure of file watching from the TypeScript extension.
> 
> **Steps:**
> 
> * download insiders from https://code.visualstudio.com/insiders/
> * configure `typescript.tsserver.experimental.useVsCodeWatcher` to the default value of `true`
> * please make sure your `files.watcherExclude` setting does not include `**/node_modules/*/**`
> * perform your workload that was showing issues
> 
> Happy to hear back how it goes 🙏

This seems to work well. Haven't tested a lot but it works well.
