### ISSUE TITLE
failed to start vs code remote server

### ISSUE THREAD

**Issue by Dneeds1991** [microsoft/vscode#222142]
ADD ISSUE DESCRIPTION HERE
The workbench failed to connect to the server (Error: exception was thrown by handler. exception: failed to start vs code remote server.)

Version: 1.91.1
Commit: f1e16e1e6214d7c44d078b1f0607b2388f29d729
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0
Embedder: codespaces

**Comment by neprasad-microsoft** [comment]
I am seeing this issue today. Any fix for this?

**Comment by bpasero** [comment]
/It looks like this is caused by the Codespaces extension. Please file the issue in the [Codespaces Discussion Forum](https://github.com/community/community/discussions/categories/codespaces). Make sure to check their issue reporting template and provide them relevant information such as the extension version you're using. See also our [issue reporting guidelines](https://aka.ms/vscodeissuereporting) for more information.\n\nHappy Coding!
