### ISSUE TITLE
Selected section will be lost in replace text

### ISSUE THREAD

**Issue by yuxiaomin** [Microsoft/vscode#22254]
- VSCode Version 1.10.2 (1.10.2) (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T13:54:01.558Z)
- OS Version: macOS Sierra 10.12.3 (16D32)
---

Steps to Reproduce:

1. Edit js file. Select some lines and click "Cmd+F" to popup search&replace dialog 
2.In the first input enter some text that I want to replace. This text also appears out of the section that I selected in the above step.
3.Then I click the "Find in the selection" button in order to replace only the text in my selection part. Now the selection is lost. Only one line that which is before my selection part but also has the searched text will be highlighted. My selection before showing the search dialog is lost. 

The expected behavior is that the my selection is still there and I can continue to replace.

**Comment by rebornix** [comment]
Our find widget will do incremental search when you type in the search query, and we will move the selection to the nearest match. That's why the selection changes while you are typing. To persist the selection for following replacement, you may want to toggle Find In Selection first before you update the query keyword.
