### ISSUE TITLE
Test Tour: MEAN

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#22279]
[Test Tours/Exploratory Testing](https://msdn.microsoft.com/en-us/library/jj620911(v=vs.120).aspx#bkmk_tours). We will use a starter kit and use it for a 'GuideBook Tour'. The final goal would be to show a cool demo of how you can use VS Code to do MEAN.

You have discovered http://mean.io/ and want to use Code to get started.

- do you get the extension recommendations?
  - [angular language service extension](https://marketplace.visualstudio.com/items?itemName=Angular.ng-template&showReviewDialog=true)
- set it up for development. 
  - setup debugging
  - setup tasks if applicable
  - setup linting
  - check Intellisense behaviour (do you need a jsconfig.json)
  - configure the exclusion for search and the explorer.
- start implement something fun
- are there additional JSON schemas that should be defined/used to simplify development
- check that all artifacts/file types have syntax coloring
- think of demo of some of the VS Code goodness

Link issues you discover to this issue.
Share findings in this issue.

**Comment by dbaeumer** [comment]
Some first findings:

- installation under Windows difficult. Was not really successful so far since npm installed requires synk which requires some GNU utilities :-(. 
- No workspace recommendations. The workspace has a .jshintrc file. So we should add workspace recommendations based on these linter specific config files:
  - .jshintrc => JSHint extension
  - .eslintrc => ESLint extension
  - .csslintrc => CSS Linter

**Comment by dbaeumer** [comment]
After trying to get the install fully running under Windows I gave up since I couldn't get `snyk` with `patch` under Windows to work. Easiest work around for now is to change `"snyk-protect": "snyk protect"` in package.json to `"snyk-protect": "dir"` :-)

**Comment by aeschli** [comment]
The angular language server breaks intellisense in HTML files: https://github.com/angular/vscode-ng-language-service/issues/62

**Comment by sandy081** [comment]
Here is the summary from @dbaeumer, @aeschli and myself


## Extensions
No workspace recommendations. We should show workspace recommendations based on config files and mean.json file.
- jshint: The workspace has a .jshintrc file.
- Angular: We tried language support through Angular language service extension, but it was not working due to a bug which we filed.
- Debugger for Chrome: It has problem with the webpack structure and there are no source maps for MeanIO.
- Docker

## Language features
- Installing @types/angular gives intellisense for angular code
- Missing typings (no d.ts) for Meanio framework
- Quite some modules export a function module.exports = function (app) { …. } which doesn't allow TypeScript to infer any type for the app which makes code complete on app very hard (app is basically any). 

## Debugging 
- Server launching needed some tweaking which we already filed some bugs. Andre is working on them.
- Server debugging works well.
- The whole webpack stuff is handled nice in chrome. Not so nice in F12 nor our chromium debugger.
 
## Tasks
- there is only one task to start everything. It is triggered by gulp. Easy to run in terminal (external or internal).
