### ISSUE TITLE
Possibility to open terminal in separate window

### ISSUE THREAD

**Issue by CZDanol** [Microsoft/vscode#22305]
This need for me is because I'm using code-d (D language extension for VS code) which writes run output to the console terminal - I need more space for viewing it and simultaneously writing code.

**Comment by zaakiy** [comment]
+1. I would also like to have it in a detached window because the VS Code terminal is the perfect replacement to conhost.exe since it it natively presents extended character set font support as shown below when running fish (note that it properly displays git status with an "x" instead of "[]").

![image](https://user-images.githubusercontent.com/10609818/32141684-538e6876-bcda-11e7-90a8-07881d3ab5ec.png)

**Comment by Tyriar** [comment]
Closing in favor of https://github.com/Microsoft/vscode/issues/34442, I think there's also an issue somewhere for pulling panels out into different windows which is also what this is asking for.
