### ISSUE TITLE
`findFiles2New` should explain the advantage of using an array of glob pattersn

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#223286]
Testing #223154

GHPR had a pattern where it called `findFiles` 6 times. This was not great and spawned many ripgrep (https://github.com/microsoft/vscode-pull-request-github/issues/5923). Is there an advantage to the `findFiles2New` where this wont happen?

**Comment by andreamah** [comment]
Yes, the advantage is that you can call once if you want to include lots of patterns in a 'a OR b OR c' manner, where a, b, and c are different glob patterns.

However, due to the way that ripgrep is, it will still be called n times (in the example above, 3 times). This is just because of the way that ripgrep can only handle one glob at a time.

If these are globs that are not from user input, you could actually do something like `{a, b, c}`. This should combine a, b, and c into one glob via brace expansion, and thus being one call (this is already supported in `FindFiles`). However, ripgrep does not support brace expansion past the first level, so if these are user-provided globs that may already have braces, it's the safest to run separate searches. In the case of the new API, this would just be one call to `findFiles2` with multiple `filePattern`s. However, in the back end, this will still call 6 ripgreps.
