### ISSUE TITLE
verified flatpak support for linux.

### ISSUE THREAD

**Issue by olumolu** [microsoft/vscode#223237]
Please give official support for flatpak
https://flathub.org/apps/com.visualstudio.code
Kindly verified flatpak is really helpful.
```[tasklist]
### Tasks
```

**Comment by olumolu** [comment]
No this not duplicate the app that is found in flathub that does not have verified badge.

**Comment by Tyriar** [comment]
It's not verified because it's not published by us. We still do not plan on officially supporting it.

**Comment by olumolu** [comment]
Ok but maybe you don't have plan but if you keep this open maybe someone will plan and do it.
@Tyriar

**Comment by Tyriar** [comment]
This is just how we run the project. Managing this amount of issues isn't easy and we therefore aggressively close issues that aren't likely to be implemented sometimes, see https://github.com/microsoft/vscode/wiki/Issue-Grooming#out-of-scope-feature-requests

> Does the functionality described in the feature request have any reasonable chance to be implemented in the next 24 months?

The answer to that is most likely no due to resources on our end and the burden of maintaining a new package. It was already discussed in https://github.com/microsoft/vscode/issues/7112 and the package is currently maintained by the community.
