### ISSUE TITLE
Find and Replace is a bad experience.

### ISSUE THREAD

**Issue by jhicken** [Microsoft/vscode#22322]
I have a proposal. I think that global find and replace would be much more usable if it was laid out horizontally. Preferably where things like the "PROBLEMS", "OUTPUT", and "DEBUG CONSOLE" are.

I love Atoms and Sublimes find and replace for lots of different reasons but this is honestly my biggest hangup with vscode.

So here are what some of the competition does.

Atom (arguable my favorite experience and the most concise) ---- Horizontal and Vertical
![screen shot 2017-03-09 at 11 30 36 am](https://cloud.githubusercontent.com/assets/5297942/23764721/c6fbe91e-04bb-11e7-96b0-c686bf11d525.png)

Sublime (Cool but once you search you lose you search box) ---- exclusively Horizontal then Vertical
![screen shot 2017-03-09 at 11 24 03 am](https://cloud.githubusercontent.com/assets/5297942/23764930/854d476e-04bc-11e7-827d-a5b5955f9837.png)

after search
![screen shot 2017-03-09 at 11 32 48 am](https://cloud.githubusercontent.com/assets/5297942/23764952/96d61ccc-04bc-11e7-908f-161d0166ac92.png)

And Webstorm I feel like they gave up and just made it work.
You get a separate popup
![screen shot 2017-03-09 at 11 25 08 am](https://cloud.githubusercontent.com/assets/5297942/23765034/fccd7282-04bc-11e7-806e-8ec01292a70a.png)

then that goes away after you search and you get results (In my opinion they are muddy and hard to read) Horizontal
![screen shot 2017-03-09 at 11 33 26 am](https://cloud.githubusercontent.com/assets/5297942/23765080/2bf8ee56-04bd-11e7-9b96-41e114d09b85.png)

THE POINT
The point is most other editor at least show search results in a Horizontal layout. This is for good reason. The results are much more digestible.

Here is what my results look like most of the time. (all squished on the side)
![screen shot 2017-03-09 at 11 44 37 am](https://cloud.githubusercontent.com/assets/5297942/23765247/ce7cc206-04bd-11e7-8340-10a1062273e4.png)

The funny thing about this.. When showing search in the documentation for vscode it looks more horizontal. I think the reason why is it creates a better user experience.
https://code.visualstudio.com/docs/editor/codebasics#_search-across-files
![codebasics_search](https://cloud.githubusercontent.com/assets/5297942/23765606/f3baeab0-04be-11e7-952d-c823eb4d326a.png)

So my issue is I think I could probably make a plugin to do this a little better but I wanted to see if this is the direction vscode will be going in the future or if it should be done as a plugin.

**Comment by nekcih** [comment]
Of all the find replace options, Atom does it best in my experience. This is one of the main reasons I can't switch to VS Code.

**Comment by NKjoep** [comment]
I just came to open an issue asking for some search panel improvements and then I discovered I am not alone. I agree on all the points above. 

And I add my 2cents:

- **horizontal approach**: a more horizontal window would improve ux a lot since it would be easier to read among the results
- **multiple search**: multiple tabs and or possibility to run a new search without losing the previous results
- **options more visible and reachable**: the search options aren't easy to reach because of with those small buttons and the arrows to expand part of the panel. Those should be more visible and keyboard friendly
- **options by importance**: reorganise the options by importance. I'd say it would be nicer to have term pattern and file pattern as the very first options in the search panel. Most of the time you know where to search and which file pattern use (i.e. *.html, *.js) and that speeds up research process.
- **options history**: remember what patterns and options have been used in the previous session so the user can reuse tem easily with keyboard and/or autocomplete (see Atom)

**Comment by SyntaxErratum** [comment]
I agree. I tried VS Code for a couple of months and I like it but I went back to Atom solely because of the search functionality.

**Comment by schaveyt** [comment]
Yes, yes, yes!!! Please please please!!

Just clone atom or sublime's UX for this area and everyone and their sister will adopt vscode.

**Comment by stevencl** [comment]
Thanks for the well articulated feedback. We'll discuss this in the team and figure out how we want to proceed with this.

**Comment by leemhenson** [comment]
If I may, I'd like to also propose that once you have an search results editor window open, it would be very neat to be able to edit the matches inline. Thus I could select a range of matches and, for example, replace a typo within that range only. Then I would hit `cmd+s` and the changes I had made would be saved to the relevant files. 

CtrlSF plugin for Vim (https://github.com/dyng/ctrlsf.vim) does this, for example.

**Comment by NKjoep** [comment]
@leemhenson that's a great feature. If I were the backlog owner I would put this as an additional feature after refactoring the base experience :) very cool though 👍

**Comment by tannerlinsley** [comment]
@waderyan This is huge :)

**Comment by umpirsky** [comment]
Related https://github.com/Microsoft/vscode/issues/30104

I agree Atom does great job here, it simply looks more polished, starting with position, buttons, icons and results.

**Comment by rattrayalex-stripe** [comment]
Are there any community plugins that deliver this in the meantime?

**Comment by MikeRatcliffe** [comment]
There are no plugins at the moment. I would say that the features that should be included are as follows:

- **horizontal approach:** a more horizontal window would improve ux a lot since it would be easier to read among the results
- **multiple search:** multiple tabs and or possibility to run a new search without losing the previous results
- **options more visible and reachable:** the search options aren't easy to reach because of those small buttons and the arrows to expand part of the panel. Those should be more visible and keyboard friendly
- **options by importance:** reorganise the options by importance. I'd say it would be nicer to have term pattern and file pattern as the very first options in the search panel. Most of the times you know where to search and which file pattern use (i.e. *.html, *.js) and that speeds up research process.
- **options history:** remember which options have been used in the previous session.
- **search history:** remember the last x strings or regexes that have been used. The number of history items should be configurable.
- **access to regex captures:** use e.g. $1 - $9 or \1 to \9 to access captures.
- **regex special characters:** allow \t, \r, \n etc. Of most importance is the newline that allows modifications to whole blocks of code.
- **JS functions for replace:** an option could be added to use a JS function as the replacer... this would give the editor a fairly unique feature that devs would love.
- **display replacement preview with search results:** old value in red and new value in green as follows:
![screen shot 2017-07-28 at 10 07 54](https://user-images.githubusercontent.com/116941/28710667-c649b444-737c-11e7-8e30-a820418659ad.png)

**Comment by MikeRatcliffe** [comment]
I started working on this but, really, until there is support for creating and opening a bottom panel it is a non-starter.

**Comment by schaveyt** [comment]
[SublimeText's approach](http://docs.sublimetext.info/en/latest/search_and_replace/search_and_replace_files.html) is to skip the bottom panel all together and simply use an entire first-class file tab titled "Find Results" where all results are continually appended to the end. The vscode extension sample repo has a content provide example that is a great start to this. https://github.com/Microsoft/vscode-extension-samples/blob/master/contentprovider-sample/README.md

**Comment by spiritson** [comment]
+1

**Comment by chenka** [comment]
I agree with you, put searching bar in bottom is better than aside.

**Comment by scholtzm** [comment]
Atom even allows to open search results in a split pane. Clicking the results opens files in the left pane. This in my opinion is superior compared to tiny search panel VSCode offers. Hopefully this will be improved in the future.

![image](https://user-images.githubusercontent.com/2640934/31707307-3225234c-b3ec-11e7-8d18-ec7ffdf76c95.png)

**Comment by garconvacher** [comment]
+1. I still use atom regularly only to perform search/replace in projects. The vscode search bar is really painful.

**Comment by drawcard** [comment]
I switched from Atom about a week ago and am loving the VS Code experience, but the one thing holding it back is this UX blocker. I really look forward to the day search results appear in a bottom panel...

**Comment by pdodzweit** [comment]
I recently switched from Sublime to VS Code and I have to say that I actually like VS code's find better than Sublime's since i can quickly click on the search result and open the file to view the full context.  With sublime I have to context switch between the search results and the file, or i have split the tabs, but why do that when I could take one second to resize the search results to take up the same amount of room as the split tabs would have?

**Comment by fantasmasnc** [comment]
Microsoft/vscode
reply@reply.github.com

**Comment by gusbemacbe** [comment]
I have this bad experience.

When I find and replace a word in all files, it automatically opens all the files. I disapprove it strongly.

**Comment by viralanomaly** [comment]
I have someone actively researching alternatives to vscode because of the search location.  It is a serious concern to those of us using it every day.  Is there any plan to look at this?

**Comment by davidlygagnon** [comment]
I also feel the same about search in vscode. It's been annoying me for a while now. I can live with it for now but hopefully we'll have the option the configure the placement soon. I'd say search is a vital feature for developers and it's not the best experience in vscode so far.

I'll add to this, what about adding search and replace/modify within the search window like Intellij/Webstorm does? That feature is pretty neat!

**Comment by umpirsky** [comment]
Looks like it is available in preview?

![](https://pbs.twimg.com/media/DXtk9k-VQAAGAvF.jpg:large)

**Comment by NKjoep** [comment]
yes, read the release notes --> https://code.visualstudio.com/updates/v1_21#_horizontal-search

to enable it, add `"search.location": "panel"` to your settings.

**Comment by drawcard** [comment]
I have enabled the preview feature and so far it's working wonderfully. Thank you for addressing this! Productivity is over 9000 now...

**Comment by gusbemacbe** [comment]
Still useless. I found and replaced a word in **all** files and it open all files. What a waste of time!

**Comment by tannerlinsley** [comment]
Visually, this is better. I just made the permanent switch today. Still not
enjoying the mass file opening though...

**Comment by umpirsky** [comment]
Mass file opening is a big fail. Is it reported?

**Comment by gusbemacbe** [comment]
@umpirsky one of developers updated, but the file opening still continues, so I reported, check his update comment: https://github.com/Microsoft/vscode/issues/14554#issuecomment-372937725

**Comment by gusbemacbe** [comment]
@umpirsky, @tannerlinsley, @jhicken, @markhicken, @SyntaxErratum, @schaveyt, 

# Microsoft has just updated the version of VSCode and you can find and replace one word in all file **without opening**!!! I tested and it worked!

**Comment by daybreaker** [comment]
Horizontal search is great. Now it just needs a config option for search context that puts X lines before and after each result. There's only a fe things remaining for VS Code to be fully better at least equal to Atom, and this is one of them.

**Comment by tommai78101** [comment]
I'm just hoping that you can use regex for replacing found regexes.

```
Find: \s+
Replace: \n
```

So if it finds 1 or more than 1 whitespaces, it replaces them all as 1 newline.

**Comment by drawcard** [comment]
@tommai78101 if you hit the button with the asterisk icon, you can target the spaces you're wanting to remove:

![image](https://user-images.githubusercontent.com/1435638/39674907-72cffa22-5192-11e8-9609-9935a91a84be.png)

![image](https://user-images.githubusercontent.com/1435638/39674916-8ad490c4-5192-11e8-83b2-c6345fe5af53.png)

becomes

![image](https://user-images.githubusercontent.com/1435638/39674921-9514d1d4-5192-11e8-80cc-9fad2979c315.png)

**Comment by davidlygagnon** [comment]
One thing that I noticed with the search experience in general: 

When you have a search results spanning multiples files, and selecting each file one by one to do some editing, search looses focus on the file as soon as you go to the file. In other words, the search panel does not keep the latest file opened highlighted. 

After editing a file, when I get back to the search editor, I need to know which file I was just editing.

Has anyone else noticed that?

**Comment by frguthmann** [comment]
Is there a way to replace the search box entirely? I want to be able to hit CTRL-F and have an atom / sublime experience: open the horizontal search bar and every time I type enter it scrolls through the occurrences in the opened document?
And of course we need an option to specify if we want to search all files.

**Comment by drawcard** [comment]
@frguthmann are you using the latest version of VSCode? I get the Sublime style search panel:

![image](https://user-images.githubusercontent.com/1435638/42790591-094671b6-89ab-11e8-9d47-edd899190656.png)

**Comment by frguthmann** [comment]
@drawcard Yep I wish I could use this to search inside the opened file too.
Plus the results being displayed under the search bar is terrible imo.

**Comment by stormhillmedia** [comment]
I would also love it if it displayed the scope of your search. If you are searching a folder, have something saying "searching inside... " Most of the time I can only assume it is working but then sometimes it does not find the string I know is present in the files I am searching. Then I wonder where it is searching. The UI of VScode is overall lacking but this is one of the worst bits

**Comment by misolori** [comment]
@stormhillmedia when you do "Find in Folder" there is an input field that shows the scope:
![image](https://user-images.githubusercontent.com/35271042/45391853-804f2000-b5d9-11e8-98e2-aa8c26abc1df.png)

@apahne you can toggle and focus to search via `Shift + Cmd/Ctrl + F`

Closing this as you can now change the location of search via `search.location` in your settings file.
