### ISSUE TITLE
Blurry UI in Wayland with integer scaling

### ISSUE THREAD

**Issue by MKuranowski** [microsoft/vscode#223261]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.91.1
- OS Version: Arch Linux with Gnome 46
- Monitor resolution: 2880 x 1800, scaled 200%

Steps to Reproduce:

1. `code --ozone-platform-hint=wayland`
2. ![image](https://github.com/user-attachments/assets/1c32d70b-6dbc-4e11-b336-87b87f6e7bf0)

Compared with `code --ozone-platform-hint=x11`:
![image](https://github.com/user-attachments/assets/1cde2977-4114-4678-96f1-71ebccdbafbb)

This issue is the exact opposite of the usual scaling-related issues; where switching to Wayland mode makes UI look normal; but with integer scaling (set to 200%) the Wayland mode looks awful, and X11 looks okay.

**Comment by M3t4ll1k0** [comment]
Same problem here:
Arch Linux with latest gnome, no fractional scaling, 2 monitors one with 100% scaling and another 4k with 200% scaling integer.
If using in x11 mode text is not blurry but cant use in the 100% scale monitor since it is big and scaled to 200%, in Wayland mode the windows scales correctly when switched to the secondary monitor (the one with 100%) but is very blurry as OP demonstrates.
Tried insiders version (the one in aur) and the problem persist.
code version: 1.92.0 
GNOME Shell: 46.4
primary display: 4k @ 200% integer scaling (portrait) 
secondary display: 1080p @ 100%  integer scaling (vertical left)

**Comment by rzhao271** [comment]
I believe there was a related issue that was fixed with an Electron update. Does this issue still occur for either of you on the latest VS Code?

**Comment by MKuranowski** [comment]
Can confirm, no longer an issue for me on 1.95.3.
