### ISSUE TITLE
[Themes] Selection inside "wordHighlight"ed word does not use a proper color

### ISSUE THREAD

**Issue by obrejla** [Microsoft/vscode#22324]
Hi,

- VSCode Version: 1.10.2
- OS Version: macOS Sierra

When you have a custom theme which defines a custom color for `wordHighlight` (i.e. for occurrences of e.g. local variable inside a function), then if you click on such variable and when it has a matching usage inside the scope, then `wordHighlight` color is properly set to all occurrences. 

So far so good. But if you start "selection" (by mouse drag) inside that "active" variable, then the "selected" part of the variable is NOT replaced by "selection" color.

It does not work in [Sample Light Theme](https://github.com/Microsoft/vscode-extension-samples/blob/master/theme-sample/Sample_Light.tmTheme) either. But it works in natively provided themes (also tried it in Quiet Light).

Thanks!

**Comment by aeschli** [comment]
The problem is that `wordHighlight` is placed over the `selection`. Therefor `wordHighlight`always should defined with a transparency. Same for `findRangeHighlight`, `findMatchHighlight` and `				`currentFindMatchHighlight`. Always put a transparency.


I fixed [the sample themes](https://github.com/Microsoft/vscode-extension-samples/blob/master/theme-sample)

**Comment by obrejla** [comment]
Thanks a lot.
