### ISSUE TITLE
API doc should indicate when I should expect TextSearchMatchNew vs TextSearchContextNew in a text search result

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#223323]
Testing #223154

I can see that the `result` of `findTextInFilesNew` can be `TextSearchMatchNew | TextSearchContextNew`. When should I expect each of these types? I'm not sure I understand what the purpose of `TextSearchContextNew` is.

**Comment by andreamah** [comment]
`TextSearchContext` is like the surrounding context lines that you see in the search editor. 



![Image](https://github.com/user-attachments/assets/be82aedc-da28-47cd-8e8b-83763a978178)


For example, here, lines 1791 and 1793 are context lines because they come directly before and after line 1792.

I can try to explain this better in the docs, though!
