### ISSUE TITLE
Bad fonts rendering in editor

### ISSUE THREAD

**Issue by Kernell** [Microsoft/vscode#22336]
- VSCode Version: 1.10.2
- OS Version: 10.0.14393

Hi all. Why did not anyone notice the bad rendering of the fonts in the editor? With the same settings in different editors, only in VS Code fonts are displayed poorly.

For example, Consolas with size 9px.

notepad.exe:
![notepad](https://cloud.githubusercontent.com/assets/6692126/23774208/b8518216-0533-11e7-939d-07773f43ecaf.png)

Sublime Text 3:
![sublimetext3](https://cloud.githubusercontent.com/assets/6692126/23774214/c2714c22-0533-11e7-85e6-9a0fb4adb9c0.png)

Visual Studio 2015:
![visualstudio](https://cloud.githubusercontent.com/assets/6692126/23774232/da389932-0533-11e7-9f3f-b39780812ba5.png)

Visual Sudio Code:
![visualstudiocode](https://cloud.githubusercontent.com/assets/6692126/23774235/df39d2b6-0533-11e7-9302-820bc7aa983e.png)

Visual Studio Code with Consolas 12px:
![visualstudiocode12px](https://cloud.githubusercontent.com/assets/6692126/23774246/eae47436-0533-11e7-8f53-6f4252b3c96f.png)

As you can see, in all editors the font looks the same and awesome, except for VSCode. The font looks similar at a size of 12px, but it still looks bad.

**Comment by alexandrudima** [comment]
All font rendering is ultimately handled by Chromium. There are very few knobs we can turn on our side to influence it.

Please create or find an existing issue in the [Chromium issue tracker](https://bugs.chromium.org/p/chromium/issues/list) and link to it here.

**Comment by Kernell** [comment]
In chromium, this will never be fixed, otherwise it will affect the display of all sites.

I do not understand the idea of creating an IDE on the engine for a **web** browser. I think this is a bad idea.

**Comment by skbolton** [comment]
Its not a problem in atom. Though you can access the stylesheet directly and change the font-smoothing property

**Comment by bpasero** [comment]
Todays VS Code insider build comes with Electron 1.6.x, would be interesting to hear if this update solves this issue for anyone: http://code.visualstudio.com/Download#insiders

**Comment by ArianeLu** [comment]
@bpasero Hi, this just aggravate the problem, see #24483

**Comment by bpasero** [comment]
Ouch

**Comment by Kernell** [comment]
@bpasero, Fonts also look very bad and not readable.

**Comment by bpasero** [comment]
@Kernell can you attach a screenshot how it looks and maybe your settings and display/dpi environment? What OS?

**Comment by Kernell** [comment]
@bpasero you can see the screenshots in my first message above. Nothing changed.

Windows 10 with default dpi.

**Comment by ivancuric** [comment]
Yep, the line-height is completely off with Consolas:

**windows**
![windows](https://cloud.githubusercontent.com/assets/2827047/25070807/616336ce-22a8-11e7-8cea-b3b96a1df878.png)

**macos**
<img width="108" alt="macos" src="https://cloud.githubusercontent.com/assets/2827047/25070809/691cccae-22a8-11e7-9a89-707b72eed1a3.png">

It's probably a bug with the font, since all other monospace fonts work fine.

**Comment by Kernell** [comment]
Why are the 14px fonts in VSCode the same size as 9px in the system?

**Comment by ivancuric** [comment]
It's definetly an issue with Consolas:
http://mbauman.net/geek/2009/03/15/minor-truetype-font-editing-on-a-mac/

**Comment by steve-p-com** [comment]
My Insider's build just updated (1.12.0), and it's not great news. I'm running Windows 7 with the Control Panel's "Medium - 125% (default)" setting, and now everything is way too big at the default zoom level. Fonts in both UI elements and code windows are comically huge. If I change the zoom level using Control+= and Control+-, there's no zoom setting that puts it back how it was, only larger or smaller. The fonts seem generally out of focus, too. I really notice it because I use both blue and green editor versions at the same time on the same machine, and often switch between them. The blue version is nice and sharp, the updated Insider build is not. I've used it for a few minutes and it has actually given me a headache.

**Comment by Kernell** [comment]
In general, it turns out that all IDEs normally display the same font with the same size (Consolas 9px). Everything, but not VSCode. Here the fonts, even in an enlarged size, do not look normally.
And the reason is not even in anti-aliasing. Fonts generally look different, not as in the System. Even the same Consolas does not look like Consolas in the way it is.

**Comment by AbdelRahmanSalah** [comment]
any updates ?

**Comment by JCKodel** [comment]
Have you tried a decent programming font (like https://github.com/be5invis/Iosevka)?

My Visual Studio:
![image](https://user-images.githubusercontent.com/379339/31587857-f2f3fb1a-b1c7-11e7-9711-8242973d9523.png)

My Visual Studio Code:
![image](https://user-images.githubusercontent.com/379339/31587861-02302572-b1c8-11e7-9186-bef72dcbb83f.png)

**Comment by ArmorDarks** [comment]
Font rendering definitely an issue in VS Code, unfortunately. It is very painful to look at after smooth and elegant rendering in Sublime Text 3 :(

**Comment by alexandrudima** [comment]
This is an upstream issue (possibly within Chromium), and there are no known workarounds that we could implement on our side. This means there is no possible code change for us to do in VS Code sources to improve things. 

To keep the number of issues in our inbox at a manageable level, we’re closing issues that have been on the backlog for a long time but haven’t gained traction or that are not actionable. Thank you for your time and understanding.
