### ISSUE TITLE
File extension boost on MacOS

### ISSUE THREAD

**Issue by aiday-mar** [microsoft/vscode#223311]
Testing #223130

I was inside of the vscode repo and entered into the scripts folder of the repo. I then typed `open code` and the completions appeared. The first two results where in their order:

`./code-cli.bat`
`./code-cli.sh`

I read that .bat files are native to Windows operating systems, so I would expect in this case the `.sh` file to appear first.

![Screenshot 2024-07-23 at 14 58 21](https://github.com/user-attachments/assets/14e6888a-5a91-4aca-8020-f90505230280)

**Comment by Tyriar** [comment]
Actually this is behaving as designed, the boost only applies to when the file is the command, not an argument. The reason for this is because the boosted ones are likely to be run as commands and the negative boosted ones are unlikely. However when it comes to arguments we can't make that determination.
