### ISSUE TITLE
FindFiles2OptionsNew.useIgnoreFiles feedback

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#223397]
Testing #223154

https://github.com/microsoft/vscode/blob/d4bb523d43261a3ec2c4c9ca01052faeb0a874e7/src/vscode-dts/vscode.proposed.findFiles2New.d.ts#L25-L51

Should this be named `ignoreFileOverrides` or similar instead to make it more clear that not using it is fine and will likely be what the user expects?

**Comment by andreamah** [comment]
Actually, I think that it's a bit confusing to call it `ignoreFileOverrides`, since it sounds like you're populating this value directly with a path to a new ignore file, whereas this actually determines whether we override the setting. Perhaps `IgnoreFileSettingOverrides`, but I think it struggles with the same problem. I'll think about this.

**Comment by andreamah** [comment]
Ok, thinking about this again, I feel `useIgnoreFiles ` makes the most sense to me, It's whether or not to use the ignore files, and we mention in the setting details how it exactly deals with the conflict with the equivalent setting. If we make the setting mention "Override" in the name, I get confused about whether I'm saying:

true - will override
false - won't override

or 

true - will override with true
false- will override with false

**Comment by andreamah** [comment]
I'll close this, and maybe reopen if I reconsider.
