### ISSUE TITLE
Inline chat a11y help text is indistinguishable from panel chat a11y help text

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#223333]
Testing #222240

Maybe a11y help is showing me stale text from the last panel chat invocation (even after I closed the panel chat view), but the help text seems to be the same when I focus an inline chat response and do Alt F1.

**Comment by meganrogge** [comment]
@jrieken this is happening because `INLINE_CHAT_FOCUSED` is `false` here. I think that's unexpected.

https://github.com/microsoft/vscode/blob/12f9169c935bd3fd2730777130330c3bb19e0005/src/vs/workbench/contrib/inlineChat/browser/inlineChatAccessibilityHelp.ts#L18

![Image](https://github.com/user-attachments/assets/d74a21ea-54bb-4d7e-b01b-83d66fce6d8e)

**Comment by rzhao271** [comment]
Now I get "Inline chat occurs within a code editor" when I press Alt+F1 on the panel chat inputbox
