### ISSUE TITLE
Handling of cells outside of viewport

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#223344]
Testing #223152

1) select two cells
2) scroll the lower cell (cell 2) out of the viewport
3) cmd+/ 
4) scroll cell 2 partially into the viewport -> only cell 1 has been commented
5) cmd+/ -> cell 1 has been uncommented, cell 2 has been commented

After step 3 I'd expect both cells to be commented and after step 5 both to be uncommented

**Comment by Yoyokrazy** [comment]
Need to move the toggle comments action off of the editor command. Case is simpler overall since we are not operating on cursors or a specific selection. 

Relying on `editor.executeCommands()` is the limitation, as we don't have editors outside of the viewport. We can construct these edits in a similar way to a `LineCommentCommand` and simply apply them to the model, allowing us to apply to cells outside of the viewport
