### ISSUE TITLE
"debug.autoExpandLazyVariables": false replaced with the default

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#223315]
Testing #222238

There does not seem to be a need to keep the setting in the JSON, it can be removed because "auto" (with which the value is replaced) is the new default.

**Comment by andreamah** [comment]
Also- should `false` be translated to `off`? That was my interpretation.

**Comment by meganrogge** [comment]
Not sure I understand. Can you state steps to repro, your expectation vs what actually happend?

**Comment by andreamah** [comment]
I believe this is what Christof meant:
 
1. set `"debug.autoExpandLazyVariables"` to false.
2. reload the window
3. notice that it now says `"debug.autoExpandLazyVariables":auto`
4. Since this is the default value, we expected the line to disappear completely, since the absence of  `"debug.autoExpandLazyVariables"` already implies  `"debug.autoExpandLazyVariables":auto`

**Comment by meganrogge** [comment]
Thanks, are you in screen reader mode when that is the case?

**Comment by andreamah** [comment]
yup! but I'm not sure if it happens regardless. Isn't it just the process of auto-migrating the setting to the new one?

**Comment by meganrogge** [comment]
In screen reader mode, if you have it set to `false`, and reload, you should see it set to `off`. 
In screen reader mode, if you have it set to `true` and reload, you should not see it added because it's `auto`, the default.

In non-screen reader mode, if you have it set to `false` and reload, you should not see it added, because it's `auto`, the default.
In non-screen reader mode, if you have it set to `true` and reload, you should see it set to `on`.

**Comment by meganrogge** [comment]
I see some bugs with this, thanks for the issue.

To verify:
- With or without screen reader mode, if you have it set to `false` and reload, you should see it set to `off`. 
- With or without screen reader mode, if you have it set to `true` and reload, you should see it set to `on`.

**Comment by rzhao271** [comment]
Thanks for the clear verification steps, @meganrogge!
Also made much easier with @sandy081's profiles editor 🎉
