### ISSUE TITLE
Navigating to directories requires extra keypresses

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#223406]
Testing #223130

I'm not sure if I want this to be the behavior, but the description of `Suggest: Run on Enter` leads me to expect that if I type `cd test` where `test` is a subdirectory and press `Enter`, it will automatically `cd` into `test`. But since the entry always has the extra stuff around it(`.\test\`), it requires an extra `Enter`

**Comment by Tyriar** [comment]
Directories are handled specially to support quickly navigating between directories, run on enter doesn't play nice with this as it's not possible to complete the exact match since completions are requested when you type the last `\`. Maybe there should be another setting that drives the special directory behavior only after you add a `\` 🤔

**Comment by Tyriar** [comment]
Let's wait for more feedback on this, I'm not sure what the right behavior is either.
