### ISSUE TITLE
Files and folders feel noisy

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#223407]
Testing #223130

![image](https://github.com/user-attachments/assets/5c99206b-63c2-4e07-b07a-3ae07e58509b)

I know it is what pwsh completes to but the `.\` before every file and folder feels noisy

**Comment by Tyriar** [comment]
It wasn't there initially, but it doesn't really play nicely with how the suggest widget works because it needs to highlight the matches, it led to https://github.com/microsoft/vscode/issues/221953

![image](https://github.com/user-attachments/assets/b04f75d9-9f8e-4032-adb0-b517057d2bcf)

Going back to separating completion text and the label leads to weirdness when there are matches against the completion text and not the label like when you type `.\` and nothing gets highlighted. Everything felt much nicer imo when it just presented _exactly_ what was going to be completed.

cc @daviddossett
