### ISSUE TITLE
[Feature Request] Find in files to include find in file names

### ISSUE THREAD

**Issue by GoEddie** [microsoft/vscode#223644]
When I do a "find in files" I would like the search to also search file names for example if I have the two files:

- "Good Morning Campers.txt"
- "Good night.txt"

The first file contains the text "12345"
The second contains the text "hello campers how are you today?".

When I find all files for the work "campers" it returns both the first file and the also the second file.

Happy for this to be a toggle.

The reason is that often code bases (think python) refer to other files and I want to see where a file is imported or maybe I want to find the actual file name that contains a subset of the text.

**Comment by andreamah** [comment]
Currently, we don't have this sort of omni-search that would show both. We would invite extensions to contribute something like this via the finalizing ;`FileSearchProvider` extension API](https://github.com/microsoft/vscode/issues/73524) that can override find in files results. For now, I'll close this as not planned, since we currently don't plan to have something **exactly** like this in the core product. 

You could argue that we have file search, text search, and symbol search- so which results come first? Since we fuzzy-search the file names and symbols, do we do the same thing with text? There is some uncertainty on how we would build this, and so it might not be as cut-and-dry as it seems on the surface.
