### ISSUE TITLE
Allow user to perform terminal operations relative to project root

### ISSUE THREAD

**Issue by thekalinga** [Microsoft/vscode#22395]
- VSCode Version:

Version 1.11.0-insider
Commit 01091bb0831f7ce07db3cdc3ad66abb4141ffd8d
Date 2017-03-10T07:08:40.485Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0

- OS Version:

Ubuntu 14.04

Steps to Reproduce:

Currently there is no way to perform an operation relative to project root. If we navigate deep into the project, we always need to identify how many `../`'s needs to be made before we can reach the root and navigate. Instead, since vscode know the project root directory, it would be better if vscode can allow navigation/shell expansion relative to project root along the lines of `~`

For e.g,

If the project is located at `/home/user/myproject`, and the user at the following path within terminal `/home/user/myproject/root/child/grandchild/`

currently if the user need to reach home, he either need to close the terminal & reopen (in which case, he would lose the history)/naguivate using `cd ../../../`

The problem with the second approach is, its waste of time identifying how many backs you need to do with elipses.

Instead if we have something like `^`(or anyother single character) which is similar to user home `~`, that vscode expands as `<project root>`, then the developers life would be much simpler to navigate within the project

This way if the user needs to navigate to `/home/user/myproject/root/child2`, irrespective of where he is in the terminal, he can just do `cd ^/child2`

**Comment by Tyriar** [comment]
Well since we can't touch what bash, cmd, etc. are doing with the characters that are sent to it, the only way I know of to accomplish this would be through an environment variable which we could potentially expose:

```
cd $VSCODE_ROOT/child2
```

When `cd $VSCODE_ROOT` is tab expanded it will expand to the directory. However I'd want the environment variable name to be reasonably descriptive as to be understandable which could potentially detract from its usefulness.

You should actually be able to do this now without any changes to VS Code's by setting some environment variable to `$(pwd)` in your `~/.bashrc`:

```
R=$(pwd)
```

Then typing `cd $R` <tab> would expand to the project folder.
