### ISSUE TITLE
Show included (php) or referenced (css, or js) file as separate tabs

### ISSUE THREAD

**Issue by sirajalam049** [Microsoft/vscode#22397]
- VSCode Version: 1.10.2 Update
- OS Version: Windows 10 Pro. 64bit.

Is there any option in which the included (PHP) or referenced (CSS, js) files in separate tabs just like in Dreamweaver?

**Edit**

Here is the screenshot of what I'm looking for.

![capture_123](https://cloud.githubusercontent.com/assets/22110988/23829442/5a8c4a68-0717-11e7-9ec8-adb0b351405e.JPG)

Upper tabs the files I've opened in Dreamweaver and the lower tabs are the css, js, php files I've included in the selected file.

**Comment by aeschli** [comment]
Please add screenshots that illustrate what you imagine.

**Comment by sirajalam049** [comment]
@aeschli I've edited my question, please take a review.

**Comment by aeschli** [comment]
@sirajalam049 Thanks for clarification.

**Comment by sirajalam049** [comment]
Thanks @aeschli

**Comment by aeschli** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.
If you disagree and feel that this issue is crucial: We're happy to listen and to reconsider.
Maybe you want to give it a try yourself and provide the feature through an extension or a PR: We're happy to give advise and get you started.
Thanks for your understanding. Thanks for helping and happy coding!
