### ISSUE TITLE
Add Toggle MiniMap to View Menu

### ISSUE THREAD

**Issue by seanmcbreen** [Microsoft/vscode#22423]
We should add a toggle here for discover-ability.

**Comment by ilyabirman** [comment]
I’d also want a command for key binding.

**Comment by seanmcbreen** [comment]
![image](https://user-images.githubusercontent.com/1051190/26955147-d10fe824-4c69-11e7-80ba-b1a418e27cda.png)

**Comment by alexandrudima** [comment]
@seanmcbreen 

* Adding a toggle that writes to user settings and enables/disables the minimap for all editors is easy.
* Adding a toggle that enables/disables the minimap for the current file (similar to toggle word wrap) is ridiculous hard due to our settings story, where we need to maintain an in-memory file-based dictionary and work around the entire workbench settings story to not apply the incoming settings and to establish the toggle in all cases such as drag & dropping tabs, opening to the side, etc.

Which type of toggle do you have in mind when you say "We should add a toggle"

**Comment by summivox** [comment]
> Adding a toggle that enables/disables the minimap for the current file (similar to toggle word wrap) is ridiculous hard due to our settings story, which does not have this concept

Such an oversight, considering that vim has had `set` vs `setl` for ages.

**Comment by alexandrudima** [comment]
I went with the easy implementation that writes to user settings.
