### ISSUE TITLE
Cannot redeclare block-scoped variable 'name'

### ISSUE THREAD

**Issue by rajinder-yadav** [Microsoft/vscode#22436]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:00:46.854Z)
- OS Version: Linux x64 4.4.0-66-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-markdownlint|DavidAnson|0.7.0|
|EditorConfig|EditorConfig|0.6.0|
|sort-lines|Tyriar|1.2.0|
|vscode-eslint|dbaeumer|1.2.7|
|tslint|eg2|0.8.1|
|cpptools|ms-vscode|0.10.3|
|Spell|seanmcbreen|0.9.1|;

Below code is generating a false error:

---

Steps to Reproduce:
```js
const sub = {
  "name": "Rajinder Yadav",
  "email": "devguy.ca@gmail.com" 
};

let t = `
{
  "name": "++lib-name++",
  "version": "0.0.0",
  "description": "",
  "keywords": [],
  "main": "dist/--libraryname--.js",
  "typings": "dist/src/--libraryname--.d.ts",
  "files": [
    "dist"
  ],
  "author": "++name++ <++email++>",
  "license": "MIT",
  "engines": {
    "node": ">=6.0.0"
  },
`;


const name = "++name++";
const email = "++email++";
let s = t
.replace(name, sub.name )
.replace(email, sub.email);

console.log(s);
```

**Error**
```sh
node_modules/typescript/lib/lib.d.ts(18935,15): error TS2451: Cannot redeclare block-scoped variable 'name'.                       
src/main.ts(25,7): error TS2451: Cannot redeclare block-scoped variable 'name'.                                                    

npm ERR! Linux 4.4.0-66-generic
npm ERR! argv "/home/yadav/.nvm/versions/node/v7.5.0/bin/node" "/home/yadav/.nvm/versions/node/v7.5.0/lib/node_modules/npm/bin/npm-cli.js" "run" "--@tscli/demo:doc_folder=docs/typedoc" "--@tscli/demo:main=build/main.js" "tsc"
npm ERR! node v7.5.0
npm ERR! npm  v4.3.0
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @tscli/demo@0.1.0 tsc: `tsc`
npm ERR! Exit status 2
****
```

**Comment by rajinder-yadav** [comment]
In fact the same error can be produced with a file containing only the following line.

```js
const name = "test";
```

**Comment by mjbvz** [comment]
Thanks @rajinder-yadav 

I believe this behavior is by design. By default, TypeScript uses the DOM typings for the global execution environment and there is a `name` property on the global `window` in the DOM. In this case, TypeScript is providing a potentially helpful error message, provided the script is executed in a browser at least.

There are two easy ways to avoid this problem:

* Use modules. If the file is treated as a module, this error does not occur. There's a separate issue tracking allowing any file to be treated as an isolated module: https://github.com/Microsoft/TypeScript/issues/14279
* Don't include DOM typings. To do this, add an explicit `lib` property in your `tsconfig.json` that does not include `dom`:
    ```json
    {
        "compilerOptions": {
            "lib": [
                "es2015"
            ]
        }
    }
    ```

Let me know if you run into any trouble with this

**Comment by dziamid** [comment]
Wow, I'm so surprised to see that typescript behaves this way. Shouldn't it suppose to act similar to nodejs where each file is a module and all variables declared in a file are locally scoped?

**Comment by mjbvz** [comment]
@dziamid TS supports both use cases. If you use `import` or `export` or `module` then vars are locally scoped to the file but we still allow people to use globals in older style code

**Comment by dziamid** [comment]
What about `require`? Does it also mean that file is a module?

**Comment by piq9117** [comment]
I added `"lib": ["es2015"]` in my `compilerOptions` and the warning is still persisting. 😢
