### ISSUE TITLE
Rearrange search lables to free screen space

### ISSUE THREAD

**Issue by dair-targ** [microsoft/vscode#224382]
In the search tab, it would be nice to move "files to include" and "files to exclude" labels from being on top of input fields to be left of them as shown by red arrows on the screenshot below, or even completely replace those labels with placeholders. This would remove unused space (again, marked on the screenshot below) freeing much needed vertical space for the actual search results or the opened file above.

This should benefit whoever works on a small screens such as laptops.

<img width="837" alt="Screenshot 2024-07-31 at 11 51 10" src="https://github.com/user-attachments/assets/bcae4777-b16c-4141-b3dc-5f07019d9a3d">

**Comment by gjsjohnmurray** [comment]
The default location of Search view is the primary sidebar, where width is typically a scarcer resource than height is. Your proposal would penalize that situation.

In any case, your first highlighted row includes the `Toggle Search Details` ellipsis. Where would you want this to display when toggled off?

**Comment by dair-targ** [comment]
Even on the sidebar, the vertical space is precious for the search. Hence, I mentioned the alternative: use placeholder text (and/or tooltip) within the text input instead of the labels.

For the ellipsis, in the same spirit it could be moved to the right of the "Search" text input.

Bottom line is: two UI lines spent on a tiny button and two labels hardly anyone reads during everyday work looks like a total waste of space.

**Comment by andreamah** [comment]
> use placeholder text (and/or tooltip) within the text input instead of the labels.

The problem with placeholder text is that you'd need to delete the text to see what needs to go there. Since text in the search view can persist across reloads, it might be easy to forget what that field shows.

The fields of the search view can change depending on what you toggle it to show (replace view visibility, `files to include/exclude` visibility) so it can be dynamic-ish. I personally like having the labels there so that you know clearly which fields are visible. 

See these two screenshots:

![Image](https://github.com/user-attachments/assets/8e4ecc27-c31a-4fdf-962c-2e372939531c)

![Image](https://github.com/user-attachments/assets/e895f4cf-81d1-46dd-9c45-f718ace6eae3)

In the second case, I feel like I'd mistaken `files to include` for `replace` a lot if the labels weren't there. You could intuit that that is not the replace field, but it would be tricky to get used to.
