### ISSUE TITLE
VSCode + GitHub + portable + remote devcontainers = GH auth flow fails to call back proper window 

### ISSUE THREAD

**Issue by SAPDanJoe** [microsoft/vscode#224306]
Please see the original ticket: https://support.github.com/ticket/personal/0/2900581

I have a bug for a very specific scenario:

Portable VSCode
Portable Git
docker CLI (cli only with env vars to redirect calls to a remote docker host)
GH co-pilot
Connection to VM where VS code is running over citrix + terminal services* not sure if this is a relevant part, but it is the setup I am using, so I thought it worth mentioning
When clicking the authentication in VSCode, the auth flow opens a GH page to authenticate. After successful authentication, the callback opens a new local VSCode session that is signed in, but disconnected from the devcontainer. When you try to re-open the devconatiner, a new instance of VSCode is opened for the devcontainer, but it is not signed in to GH co-pilot.

**Comment by TylerLeonhardt** [comment]
This is because the portable install of VS Code does not install the protocol handler: `vscode://...`

You can work around this by cancelling the existing auth flow (you should see a notification with a cancel button) and that will show another notification asking you to sign in a different way. Go through that flow and this should work
