### ISSUE TITLE
CPU still running at 50% after closing VS Code

### ISSUE THREAD

**Issue by jestersoftware** [Microsoft/vscode#22469]
![capture](https://cloud.githubusercontent.com/assets/4173419/23829221/eec1ae3c-06b1-11e7-909a-2cb872e5b515.PNG)

- VSCode Version: whatever it prompted me to download as of 3/11/2017
- OS Version: windows 10

Steps to Reproduce:

1. Open VS Code
2. Do stuff
3. Close VS Code

**Comment by bpasero** [comment]
To find out more about this issue, we need to get at the process that is causing the high load. VS Code creates multiple processes, each with different tasks. Depending on your OS you can get at the full command line of the process and paste it here. On Mac, the **Activity Monitor** allows to find the `PID` of the process and from a terminal `ps aux | grep <pid>` reveals its arguments. 

![image](https://cloud.githubusercontent.com/assets/900690/18907063/65806550-856a-11e6-8b2e-83da9111445d.png)

On Windows a tool like **[Process Explorer](https://technet.microsoft.com/en-us/sysinternals/processexplorer.aspx)** helps:

![image](https://cloud.githubusercontent.com/assets/900690/18907037/476f0aa8-856a-11e6-8ac3-4c1f3e803f32.png)

Once you have the information please update this issue with it. Thanks!

**Comment by jestersoftware** [comment]
Here are screenshots of a couple of the VSCode processes, hope it helps!

![vscode-issue](https://cloud.githubusercontent.com/assets/4173419/23933694/3c995d22-090e-11e7-8d8b-3642760025cd.png)

![vscode-issue-2](https://cloud.githubusercontent.com/assets/4173419/23933693/3c98ba70-090e-11e7-9651-213e8c1e1232.png)

Perhaps it's an issue with TypeScript, or a combination. The other symptom is that, while I'm still working in VSCode, the TypeScript "intellisense" doesn't work, nor does such things as "tag matching/highlighting", etc. It's as if VSCode is leaking memory leading to a confounded state. It doesn't crash though.

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by d3viant0ne** [comment]
Ran into this on OSX using the insiders build when I finally noticed my MacBooks fan screaming at me with only Crome open on the desktop.

The issue is reproducible when @code is opened with `code-insiders --disable-extensions .`

![screen shot 2017-04-08 at 6 29 44 am](https://cloud.githubusercontent.com/assets/8420490/24828528/e1f2b470-1c24-11e7-8f25-0b4732c40c83.png)

The longer you keep code open, the more CPU the two helper processes will consume. Last I manually killed them, the CPU usage was `> 98%` with ~4 days of CPU time.

I'll try to get a more appropriate screen capture of it when it's chewing up a ton of CPU, didn't think about it until after I killed the processes.

Here we go, this is a better capture. Tested with the latest stable, launched with `--disable-extensions`

![screen shot 2017-04-08 at 11 29 01 am](https://cloud.githubusercontent.com/assets/8420490/24830586/cb12ce3c-1c4e-11e7-8f19-c02de1cd54fd.png)
