### ISSUE TITLE
Visual Studio Mac asks to save file on red "x" out of window

### ISSUE THREAD

**Issue by KyleStay** [Microsoft/vscode#22481]
- VSCode Version: 1.10.2 (1.10.2)
- OS Version: macOS 10.12.3 (16D32)

Steps to Reproduce:

1. create a new file (no folder open)
2. enter text in file
3. click the red "x" in the upper left
4. VSCode prompts for if user would like to save the file instead of just closing the window even though "hot exit" is on.

Desired functionality:
Window exits without prompting for save and resumes when VSCode is clicked on in dock

**Comment by Tyriar** [comment]
This is happening because on macOS closing the last window does not close the *application*. You have two options:

1. Keep settings as is and prefer cmd+q to kill the application to trigger hot exit
2. Add `"files.hotExit": "onExitAndWindowClose"` to your settings which is much less strict about when hot exit is triggered, the only thing to watch out for here is that folder workspaces *will not* restore when you next launch.

Check the intellisense for the `files.hotExit` setting in your settings.json for more detail.

**Comment by KyleStay** [comment]
@Tyriar This does not seem like optimal functionality. 

Different functionality could be given to the tab "x" vs. the window "x". Maybe "hot exit" is not what I'm looking for. I "x" out of windows all the time to hide them, many/most macOS applications allow this. VS Code's current implementation prevents me from doing doing this because I will get prompted to save. It would be great if it just closed, and then opened where I left off.

Is there a better place to make a request like this?

**Comment by Tyriar** [comment]
@KyleStay you're probably after this which is what I use:

```js
{
  // Allow closing any folder window
  "files.hotExit": "onExitAndWindowClose",
  // Restore all windows that were opened after a cmd+q quit
  "window.reopenFolders": "all",
}
```

The complexity of and things that could go wrong with this feature is much greater than you would probably think. You can check out some of the history on it here https://github.com/Microsoft/vscode/issues/101. Basically we opt for a conservative approach by default where if VS Code is open, *all* backups are always displayed.
