### ISSUE TITLE
root node of test run result not shown in test result view

### ISSUE THREAD

**Issue by eleanorjboyd** [microsoft/vscode#225075]
Unsure if this is a new error or if it was always this way, prior to the test result view changes with the bundled old tests. When I run a test and get pass / failure I expect the root note to show either pass (all tests in run pass) or failure (a failure exists in the tests that were run). I think it used to have a root node that was colored (same as these old test runs show a pass / fail for the whole run) but it is not showing for the current one.  Thinking if there are like 100 tests and the 99th one is a failure, you would have the scroll down to see the failure so it is nice if at the top it shows the quickest summary

![Image](https://github.com/user-attachments/assets/29fb6db7-5c76-422f-b62a-f6ef448bca03)

**Comment by connor4312** [comment]
Collapsing old results is intentional. When you run tests, any failed test should be sorted to the top of the Test Results view, so it should be easy to see any failures.

**Comment by eleanorjboyd** [comment]
The circled item is what I am thinking of- that most recent run I would think would have a summary

![Image](https://github.com/user-attachments/assets/4d02b59f-8672-4925-b20d-61d095014bab)

**Comment by connor4312** [comment]
I'm not really sure that's necessary in this case. That tree item is automatically expanded and any failures are already sorted to the top, so in effect the icon of that would be displayed there is just copying the icon of its first child.

It was useful before and is useful in previous results since we show many of them in a collapsed and the status allows the user to scan through them more easily.

**Comment by eleanorjboyd** [comment]
ah ok with the auto-sort to the top then its probably fine as is. Thanks
