### ISSUE TITLE
Massive context menus after update.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [microsoft/vscode#225055]
<table><tr>
	<th>Does this issue occur when all extensions are disabled?</th>
	<td>Yes</td>
</tr></table>

<table><tr>
	<th>VS Code Version</th>
	<td>
		<table><tr>
			<th>Source</th>
			<td><code>code-insiders-1.93.0-1722924824.el8.src.rpm</code></td>
		</tr></table>
	</td>
</tr><tr>
	<th>OS Version</th>
	<td><a href="https://download.fedoraproject.org/pub/fedora/linux/releases/40/Spins/x86_64/iso/Fedora-KDE-Live-x86_64-40-1.14.iso">https://download.fedoraproject.org/pub/fedora/linux/releases/40/Spins/x86_64/iso/Fedora-KDE-Live-x86_64-40-1.14.iso</a></td>
</tr></table>

#### **Steps to Reproduce:**

Since approximately https://github.com/microsoft/vscode/releases/tag/1.91.0 or https://github.com/microsoft/vscode/releases/tag/1.91.1 (maybe even https://github.com/microsoft/vscode/releases/tag/1.92.0) all the context menus have been massive:

1.	> ![Screenshot_20240807_143440](https://github.com/user-attachments/assets/5e5ed2d4-0eb1-4bb9-8cf5-bf8681564b93)
1.	> ![Screenshot_20240807_143459](https://github.com/user-attachments/assets/af6d6de7-2d2a-4dfa-a256-9d67a3ed87e6)

**Comment by gjsjohnmurray** [comment]
Probably #224515

**Comment by RokeJulianLockhart** [comment]
@gjsjohnmurray, it's indeed very similar to https://github.com/electron/electron/issues/42262#issuecomment-2138583635. I'll close this, because you appear to be correct.

**Comment by irm-codebase** [comment]
Also experiencing this in Fedora 40

**Comment by siferati** [comment]
Same problem for me since updating VS Code today.
It's basically the same shitty chrome refresh 2023 that people have been complaining about for the past few months.
I guess it has finally affected electron and VS Code too...
-  https://github.com/brave/brave-browser/issues/37770

**Comment by tycode** [comment]
I'm affected by this too.

I just updated VS Code from 1.91.1 to 1.92.1.

Opening the menu for an extension in the extensions view used to easily fully fit on the screen, now I get a menu that unnecessarily scrolls, because of two things:

1. it's bigger, as mentioned here already
2. it now wants to insist it's either fully above or fully below my cursor, so when the thing I'm clicking on (to open the menu in the first place) is half-way down the screen it can only use half the screen height, whereas before it was perfectly happy to move up or down a bit in order to fit fully on screen.

**Can we please have an option to use native OS menus only?**
If that's not possible, then fully custom ones that either just have sensible metrics, or have metrics we can tweak ourselves, would work fine too. Anything that successfully avoids the questionable design choices of Chrome, please.

I run Debian Linux with MATE, I use the "Native title bar" option in VS Code, and I do not use Chrome. Firefox's menus are fine, and all other non-Electron programs are fine. VS Code's menus used to be fine since they were native, now they are significantly bigger than any other menu I will ever see on my PC.

PS. I would also appreciate such an option on Windows. I've been bugged by this there since much longer ago since Electron menus have been non-native on Windows for ages, but I mostly solved that problem by switching most of my computer use to Linux(!), so for me this has now been "un-solved" since this now affects Linux too.

![menu-comparison](https://github.com/user-attachments/assets/f8d39c0a-c19a-4b85-a05e-23ac9499c5ab)

**Comment by RokeJulianLockhart** [comment]
> https://github.com/microsoft/vscode/issues/225055#issuecomment-2282192120

@tycode, indeed, this appears to be a duplicate. I'll consequently close this as unplanned.
