### ISSUE TITLE
C language syntax highlighting breaks after declaring pointer to function argument

### ISSUE THREAD

**Issue by sov1178** [Microsoft/vscode#22519]
- VSCode Version: 1.10.2
- OS Version: Windows 8
- Extensions:  cpptools / ms-vscode / 0.10.3
- Language: C

Steps to Reproduce:
1. Create .c or .h file
2. Declare function with the pointer to function argument (just type something similar to):
![image](https://cloud.githubusercontent.com/assets/25171239/23846168/3045ce48-07dd-11e7-891c-63673aab04eb.png)
arguments types (I tried char, int, long, void) are not highlighted after the pointer to function argument. Type modifiers (const) are highlighted.

**Comment by weinand** [comment]
Please file this issue against the cpptools / ms-vscode extension

**Comment by sov1178** [comment]
As far as know cpptools extension does not provide c/c++ syntax highlighting, but I will ask there with the reference to this thread.

**Comment by sean-mcmanus** [comment]
@weinand Our C++ Extension doesn't provide syntax highlighting for C++. It's provided by VS Code as part of atom/language-c. So the fix needs to go there, but who provides the fix is "up in the air"...it's open source so anyone can submit a fix, but it's hard to get anyone to take responsibility for actually submit the fix.
