### ISSUE TITLE
a tab does not match the specified number of spaces spaces

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#2252]
Recently I noticed that the width of a tab no longer matches the specified number of spaces:
![2016-01-25 20-48-43](https://cloud.githubusercontent.com/assets/1898161/12562636/97a7700e-c3a6-11e5-8ced-2490ed454723.png)
I'm using the Hack font.

**Comment by alexandrudima** [comment]
@weinand This is somewhat by design. When `renderWhitespace` is turned on we render leading spaces as `&middot;` and if a tab would be rendered as 4 spaces, we render it as `&rarr;&nbsp;&nbsp;&nbsp;`.

I have explored alternative ways of rendering the leading/trailing whitespace (ways that do not depend on the font's width for `&middot;` and `&rarr;`, but all methods I could think of involve a secondary painting of them on top of the text. I have even stared for a long time at [combining characters](http://unicode-search.net/unicode-namesearch.pl?term=COMBINING) in search of one that would look reasonably ok. A combining character would have the advantage that it would not define the width, it just renders on top of the character it is combined with.

The current method has the drawback that it makes the whitespace depend on the defined width for those two characters, but has the advantage that it consists of a single render pass.

Specifically for Hack, I have hit the same issue, please see chrissimpkins/Hack#78 => please update to Hack v2.011 or higher.

I know this is technically incorrect, but it is faster than the alternative of doing a second pass. If you feel strong about it, please reopen and I can implement the rendering of whitespace as a second pass.
