### ISSUE TITLE
Marked is not ESM compatible anymore

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#225219]
We lost changes that where ESM relevant.

I am trying to fix it in our ESM branch, maybe backport it from there:

https://github.com/microsoft/vscode/pull/166033/commits/dd5e6a1490f6cb1e41cc67bde91d58fbf0d1899d

The old code also had this line, which I am not sure is needed:

```ts
Object.defineProperty(exports, '__esModule', { value: true });
```

cc @alexdima @jrieken

**Comment by bpasero** [comment]
I can backport the solution from the branch to `main`, but please double check.

**Comment by mjbvz** [comment]
Sorry about that. Is this for Monaco or the esm work?

I'd love to get a point where we can just have this as a normal dependency instead of copying it into our sources. Marked now publishes both a commonjs and esm builds too. @hediet @alexdima Is there some way VS Code could use Marked as a normal dependency in a way that would also work for Monaco? If I recall we've tried to avoid adding real dependencies to Monaco

**Comment by bpasero** [comment]
I only noticed for our `alex/esm` work, not sure about Monaco ESM. Would be great to get it working again on `main`.

**Comment by alexdima** [comment]
> I'd love to get a point where we can just have this as a normal dependency instead of copying it into our sources.

💯 I think the ESM work will unblock this. esbuild will be able to bring in and include node modules into our bundle, which the AMD bundler we wrote >10years ago did not.

**Comment by alexdima** [comment]
@hediet I would have hoped that the Monaco Editor checks would have caught this. Is there something we should improve there?

**Comment by hediet** [comment]
For monaco-editor-core, these are the only tests: https://github.com/microsoft/vscode/blob/692ef950518b49280204cbd1ce7b654142aa854f/test/monaco/monaco.test.ts#L61

It does not test markdown features.
