### ISSUE TITLE
Compare Selected: Order of original/modified has been reversed

### ISSUE THREAD

**Issue by abartho** [microsoft/vscode#225441]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.92.1
- OS Version: Linux Mint Cinnamon 21.2, Windows 11

Steps to Reproduce:

1. Open a folder with at least two files
2. Click on one file in the Explorer, then click on another
3. Right click -> Compare selected

Actual behavior:
The diff view shows the second file on the left side and the first file on the right.

Expected behavior: The diff view shows the first file on the left side and the second file on the right. This was the behavior in previous versions.

**Comment by abartho** [comment]
Checked that the issue is still present with 1.92.1 and updated the original issue.

**Comment by hediet** [comment]
I think this was an intentional change.

I just asked some colleagues, they would also expect the first selected file to be on the left.
However, I wonder if that is because we read from left to right. Someone who reads from right to left might expect the other order.

I think one fundamental issue about diffing two (not directly related) files is that the diff editor always assumes the left one is the "original" (changes in red) and the right one is the "modified" (changes in green) version. This also means that applying a change from modified to original is called "revert". This semantic does not hold when just comparing two files where none is newer/older.

Another practical implication is that when the inline diff is turned on, unchanged lines are from "modified" and can be edited.

**Comment by abartho** [comment]
> However, I wonder if that is because we read from left to right. Someone who reads from right to left might expect the other order.
A quick search indicated that most languages are read from left to right, so I'm doubtful if this was a reason for the change. If there really is a use case for reversing the original and modified side, a settings option would be good.

I agree with the semantics issue of diffing two files that are not directly related. But I admit that I have never even noticed it, I just read the red and green parts as differences and it was all I needed.

**Comment by hediet** [comment]
> A quick search indicated that most languages are read from left to right, so I'm doubtful if this was a reason for the change.

That is not the reason for the change, but it means that when someone expects the second file to appear right, this is probably because they read from left to right, and not because they assume the second file is the modified one and the first the original.

However, VS Code always shows the modified file to the right. When ignoring right and left, if two files are selected, it would be reasonable to assume that the first file is the modified (primary) one (which just happens to be shown to the right).

I do understand the confusion though.

**Comment by abartho** [comment]
> When ignoring right and left, if two files are selected, it would be reasonable to assume that the first file is the modified (primary) one

I find the old behaviour also quite reasonable, where the first selected file is the original and the second selected file is the modified version (first file => selected first, later file => selected later). But I guess that comes down to personal preference.

**Comment by benibenj** [comment]
@abartho reversing the order for the time being and waiting to see if there is any reaction from the community

**Comment by RobPavey** [comment]
I find this change really irritating. I have been using vscode in my project for several years and use Compare Selected to compare my reference file with my test (actual) file. In all the time I have been using it the first selected file was on the left. I just updated vscode and now it is on the right.

I don't see any good reason for this change. It seems less logical.
