### ISSUE TITLE
Settings sync ruined my UI state

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#225476]
* have insiders with settings sync enabled
* add exploration build to the sync
* select replace local when prompted so that exploration because just like insiders
* 🐛 over time insiders UI state gets ruined, e.g the side bar is populated with views I have carefully hidden and rearranged

**Comment by sandy081** [comment]
This is caused due to the dependency between two states `views.customizations` and `workbench.activity.pinnedViewlets2`.

- Values of both states changed together from outside 
- Change event for first state is triggered. 
- Updating to this change can cause view container changes like (registering or deregistering)
- This triggers internal change events to update pinned viewlets
- Updating pinned viewlets is updating the stored value for second state

Bug is caused at the last step -> pinned viewlets state is getting overriden without refreshing its in-memory state.

**Comment by bpasero** [comment]
How would this be verified?

**Comment by sandy081** [comment]
Since it cannot be reproduced easily, I would ask @jrieken to verify this.

**Comment by jrieken** [comment]
@bpasero the steps are as easy as described in https://github.com/microsoft/vscode/issues/229568#issue-2545726777 or the description of this issue. 

* use settings sync
* onboard another machine
* :bug: view state of the main machine get's broken: views reappear, views are reordered etcpp

**Comment by sandy081** [comment]
@jrieken Can you please verify this? 

I believe this depends on some pre-existing state therefore not everyone can reproduce. This state is not trivial to set up. Since you have this state already, it might be easier for you to verify.

**Comment by alexr00** [comment]
I also used to see this and I don't see it anymore.
