### ISSUE TITLE
"vscode:" URL handler doesn't switch to the file's workspace if it is open

### ISSUE THREAD

**Issue by stefanhaller** [microsoft/vscode#225506]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.93.0-insider, commit 922413f6d97e16c0
- OS Version: macOS 14.6.1

Steps to Reproduce:

1. Open a workspace for a folder
2. Open another workspace for a different folder, make sure it's the active window
3. Launch a `vscode://path/to/file` URL to open a file that lives in the first folder

Expected: VS Code brings the first workspace window to the front and opens the file in it. This is what happens when you open the same file with the `code` command-line tool.

Actual: the second workspace window stays in front, and the file is opened there.

**Comment by bpasero** [comment]
Yes, I can reproduce. The reason is that we only apply our logic for finding a good window in certain contexts:

https://github.com/microsoft/vscode/blob/559107b7a92be2cfda116e3a0667f1b1ac9bf78b/src/vs/platform/windows/electron-main/windowsMainService.ts#L509-L511

I think it is reasonable to expand this logic for links as well. I hope this will not backfire though, but it makes sense from a UX point of view because a protocol link is very similar to a command line invocation.

**Comment by stefanhaller** [comment]
Thanks for the quick fix. I confirm that it works as expected in today's insiders build (27f650ea2366).
