### ISSUE TITLE
files that are opened are getting ".git" appended to their file names internally

### ISSUE THREAD

**Issue by bobmagicii** [Microsoft/vscode#22561]
.git is being appended to the names of files internally, when their filenames are accessed via the extension api.

because vscode insists on throwing file open and file close events `for tab switching` i have to compare the file that was closed to the list of files code is still keeping open, after a delay, so code asyncly has time to actually attempt to close it.

because code is appending this weird ".git" to the end it is never finding the file.

```javascript
for(Iter = 0; Iter < vscode.workspace.textDocuments.length; Iter++) {
	AutoFoldTracker.PrintDebug("file to check: " + File.uri.fsPath);
	AutoFoldTracker.PrintDebug("currently open: " + vscode.workspace.textDocuments[Iter].uri.fsPath);

	if(vscode.workspace.textDocuments[Iter].uri.fsPath == File.uri.fsPath)
	return;
}
```

```
[AF] file to check: c:\Users\bob\Desktop\atlantis\routes\Blog.php.git
[AF] currently open: c:\Users\bob\Desktop\atlantis\routes\BlogPost.php

[AF] file to check: c:\Users\bob\Desktop\atlantis\routes\Blog.php.git
[AF] currently open: c:\Users\bob\Desktop\atlantis\routes\Blog.php <<-- this one...

[AF] file to check: c:\Users\bob\Desktop\atlantis\routes\Blog.php.git
[AF] currently open: c:\Users\bob\Desktop\atlantis\core\Atlantis\Element\PagePromo.php

[AF] file to check: c:\Users\bob\Desktop\atlantis\routes\Blog.php.git
[AF] currently open: c:\Users\bob\Desktop\atlantis\core\Atlantis\Element\PagePromo.php.git

[AF] file closed: c:\Users\bob\Desktop\atlantis\routes\Blog.php.git
```

how `File` became to be:

```javascript
	vscode.workspace.onDidCloseTextDocument(
		AutoFoldTracker.OnFileClose,
		null,
		context
	);
```

```javascript
	OnFileClose:
	function(File) {
	/*//
	@argv TextDocument
	@return Void
	when a file is closed, forget about it.
	//*/

		// ...
		
	}
```

**Comment by bobmagicii** [comment]
i cannot find a single instance where code is not appending `.git` now to open file names.

this was not happening a few insider releases ago.

**Comment by joaomoreno** [comment]
Your extension gets events with Resources, not files. A resource is referenced by a URI, which looks like `file://C:/Users/foo/bar`. It can also look like `git://..`, which uses the `git` scheme.

Make sure you filter out all resources your extension is not interested in: you should only listen to resources with the `file` resource.

**Comment by jrieken** [comment]
FYI - you can use [`vscode.languages.match`](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L4232) to check if a document matches your needs, similar to how providers are registered.

**Comment by bobmagicii** [comment]
er, i need to test that the file is open...

i dont see any file:// resource paths in that example output i pasted.

you can clearly see i am reading File.uri.fsPath which surely stands for File System Path...

**Comment by jrieken** [comment]
Note that `TextDocument.uri` is a `Uri` which by its nature has a `scheme` amongst other things like `authority`, `path`, `query`, and `fragment`. The `fsPath` property is some sugar on top that helps to handle uris like `file://unc/share/path.js` for which just the _uri_-path isn't the complete *fs*-path. The comment says: "_Will *not* look at the scheme of this Uri._" which means it always concats authority and path. 

> send close signals when its not really closed, when switching tabs... that means 1 second after getting your onDidCloseTextDocument signal i have to then check if the file is REALLY

There is a subtle difference between seeing a tab for a document and the document being open. Generally, when selecting a different tab we will (a) re-use the editor, (b) set the new document, and (c) close the former document. 

Second, there are documents in the system which are *virtual*, like generated source files from dll or jar-files, generated html from markdown, or (what you have encountered) the *before*-version of files under source control/git. These *virtual* resources are discriminated by uri-schemes, not by paths. So, the is a `git`-scheme or a `markdown-preview`-scheme etc, etc. In consequence, there will be documents with those schemes.

> i dont see any file:// resource paths in that example output i pasted.

In your sample, use `toString()` instead of `fsPath` and you'll see the *full* uri of the document. Today you are just checking for a subset of the uri which is not sufficient.

**Comment by felicio** [comment]
#38431
