### ISSUE TITLE
Support UTF-16 w/o BOM

### ISSUE THREAD

**Issue by benrr101** [Microsoft/vscode#22564]
- VSCode Version: 1.10.2
- OS Version: Windows 10

Steps to Reproduce:
1. Create a UTF-16 file without a BOM at the beginning of the file
2. Attempt to open it inside VS Code, it will not open because it is detected to be "binary"

Both Sublime Text and Atom can open UTF-16 files without a byte order marker, but VS Code cannot. Sublime Text does it perfectly, while Atom needs some coaxing to get it render the file as UTF-16LE (it initially identifies it as UTF-8). However, VS Code does not provide any options changing the encoding that a file is loaded with.

For people developing CSV files, UTF-16LE w/o BOM is a format that is supported widely for opening in Excel. Without support for this encoding in VS Code, these CSV files cannot be opened.

**Comment by rmunn** [comment]
While I understand your need to support Excel in the MSSQL plugin's CSV export, I would **strongly** oppose the idea of saving UTF-16 files without a BOM. At this point, with UTF-8 being the *de facto* standard, any text file that does not have a leading BOM should be interpreted as UTF-8. Producing UTF-16 files without a BOM is going to cause all sorts of interop problems, and I'd really, seriously recommend **against** allowing VS Code to create such files.

**Comment by rmunn** [comment]
I've withdrawn my earlier downvote. I'm not opposed to giving an option to open a file as (weird encoding X) if the user specifically says "I know which encoding this file is, and it's (weird encoding X)". I don't know if VS Code has separate concepts for opening files and saving them. If you can open a file in UTF-16 w/o BOM, but it's immediately converted into a supported encoding (like UTF-16 **with** BOM) internally so that you can only save it in a supported encoding, that should work for @benrr101's use case, while not creating interop problems because *saving* as UTF-16 w/o BOM would be impossible.

**Comment by dmitrykm** [comment]
Useful feature. Here is my use case. I have to work with custom memory dumps consisting of only string content. The strings are UTF-16 C#/.net strings. Those memory dumps need to be saved on disk and loaded later for processing. Encoding and byte layout in such files must exactly match those of in-memory string content (to avoid inefficient processing), so files without BOM are preferred.

**Comment by bpasero** [comment]
Pushed 2 changes around this. The first is around us trying to detect UTF-16 (LE or BE) without BOM by looking at the typical pattern these files have if they only contain ASCII characters. For many typical use cases this means we will be able to just open UTF-16 files without BOM. We will however add the BOM upon saving.

The other change allows to force open a file into the editor that we think is binary. This is covered via https://github.com/Microsoft/vscode/issues/1218
