### ISSUE TITLE
Notification bottom item lacks border radius

### ISSUE THREAD

**Issue by hologerry** [microsoft/vscode#225750]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.92.2
- OS Version: macOS 14.6.1

Steps to Reproduce:

1. Do actions that will produce notifications
2. View the notification center
<img width="528" alt="image" src="https://github.com/user-attachments/assets/5652513a-ce8a-462a-81b2-5727c5ec0091">

Related issue and PR:
https://github.com/microsoft/vscode/issues/191532
https://github.com/microsoft/vscode/pull/191557

**Comment by hologerry** [comment]
And may I ask what is the variable name for customizing the border color (`workbench.colorCustomizations`), so that I can turn it to transparent color.

**Comment by bpasero** [comment]
There is not specific color for notifications, it is driven by the general `focusBorder`. 

I can reproduce but I am not sure how to resolve, I think the `border-radius` property on the notifications container is eating away parts of the outline.

If someone has a simple CSS fix, opening for help wanted.

**Comment by dangerman** [comment]
I had a look into this and I think I found a suitable CSS fix as suggested by @bpasero - assuming we're fine with rounding off the corners. We can use `border-radius` for this as it [seems to work on outlines](https://developer.mozilla.org/en-US/docs/Web/CSS/outline#description).

| Before | After |
| -- | -- |
|<img width="500" alt="notifications-focus-before" src="https://github.com/user-attachments/assets/25ca3956-2b59-48ac-9de0-b2872936ded6">|<img width="500" alt="notifications-focus" src="https://github.com/user-attachments/assets/8d9dc5f0-1328-4470-8c5a-6b028361d7bf">|


I also noted that it affects the individual toast notifications, and they should be fixed in the PR too.

| Before | After |
| -- | -- |
|<img width="500" alt="toast-focus-before" src="https://github.com/user-attachments/assets/dd8aad10-2be7-4378-bda9-0b0755ab1fe3">|<img width="500" alt="toast-focus" src="https://github.com/user-attachments/assets/20a63d5d-7b4b-4df3-89a5-3b10cf75e4a8">|

**Comment by hologerry** [comment]
Hi @bpasero, I confirm that this issue is correctly fixed and is working as expected now.
