### ISSUE TITLE
`IncludeFiles` might not be necessary QueryExtension to VS marketplace gallery 

### ISSUE THREAD

**Issue by lyndaidaii** [microsoft/vscode#225802]
Expected behavior: 
If extension is stable version after query with flag `IncludeLatestVersionOnly`, then flag `IncludeFiles` is not necessary to include below, 
When asking for files, versions will be included as well since files are returned as a property of the versions. 
`IncludeFile`not necessary for this case, If we remove `IncludeFile` for extension is stable version, it will improve the response time and less unnecessary data. 
 
https://github.com/microsoft/vscode/blob/3b27f1f74bc09fe2e2068997fcd42768be44a4e3/src/vs/platform/extensionManagement/common/extensionGalleryService.ts#L869C1-L870C1
```
		query = query.withFlags(query.flags, Flags.IncludeAssetUri, Flags.IncludeCategoryAndTags, Flags.IncludeFiles, Flags.IncludeStatistics, Flags.IncludeVersionProperties);
		const { galleryExtensions: rawGalleryExtensions, total, context } = await this.queryRawGalleryExtensions(query, token);
```

**Comment by sandy081** [comment]
This is required on the client for following reasons:

1. To know the existence of the files so that we can display that in the UI. For example: In the extension editor, Change Log tab is shown only if the file exists.
2. There are dynamic file asset types for language pack extensions. We only know the prefix of the asset type for the translation files, and we iterate on all files to get all translation files. Please refer to the code [here](https://github.com/microsoft/vscode/blob/c6cd724fbc1e976dd4bd3ac5ec78280b0867ed3c/src/vs/platform/extensionManagement/common/extensionGalleryService.ts#L380) for more information.
