### ISSUE TITLE
Cursor lags behind input

### ISSUE THREAD

**Issue by NeoLegends** [Microsoft/vscode#22595]
Since the newest update of VS Code the cursor sometimes lags behind when typing. This means that when I type e.g `abcdef`, the cursor is sometimes not behind, but before the `f`. This is extremely annoying.

- VSCode Version: 1.10.2
- OS Version: Windows 10 Pro v1607

Steps to Reproduce:

1. Type something
2. Notice cursor lagging behind on some inputs

Could it be caused by a plugin?

**Comment by weinand** [comment]
This sounds like an issue caused by an installed extension. Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by NeoLegends** [comment]
I primarily noticed the issue when editing rustlang, so I'm going see if it happens in other languages tomorrow.

**Comment by weinand** [comment]
@NeoLegends any update on your issue?

**Comment by NeoLegends** [comment]
It really seems like this is caused by some extension.
