### ISSUE TITLE
Python: Run Selection/Line in Python REPL (or Terminal)

### ISSUE THREAD

**Issue by peekxc** [microsoft/vscode#225908]
Neither of the above keybinds do anything. At all. Please fix this non-functionality. 

-- TO REPRODUCE -- 
1. Look at the above listed keyboard shortcuts
2. Open up a Python REPL in the terminal 
3. Observe the keyboard shortcuts above do nothing.

**Comment by anthonykim1** [comment]
@peekxc Thank you for filing the issue. 
What is the version of Python extension that you are running? 
Does opening a command palette (control/cmd + shift + p) and pressing on 'Python Clear Cache and Reload' do anything?

**Comment by peekxc** [comment]
Can confirm that reloading did not help. 

Here's a short video showing the non-functionality of the above shortcuts: 

![vscode_bug](https://github.com/user-attachments/assets/af4294e3-ffcd-4640-9113-41b42e6a1fad)

**Comment by anthonykim1** [comment]
@peekxc Thanks for the video demonstration of this. I'm trying to think of why this is happening - It may be because you have the interactive window tab opened on the bottom there? Can you try closing that interactive tab and shift+enter from the Python file?(Make it so that the Python file is the only thing you have open and then try shift+enter to trigger sending to Terminal REPL or native REPL depending on your setting). Let me know how this work out - Thanks

**Comment by peekxc** [comment]
@anthonykim1 Can confirm this did not help. 

Though, even if I keep the interactive window open, I would still classify this as a bug---the shortcut should just work regardless. 

Now that you mention it, I was able to get this working by just removing all the extraneous 'When' conditions other than config.python.REPL.sendToNativeREPL

**Comment by anthonykim1** [comment]
What you have open ('interactive-1') is called Interactive Window coming from the Jupyter Extension.
Only Native REPL(You won't have to install Jupyter or ipykernel for this), Terminal REPL belongs to the Python Extension. 
You will know when you are in Native REPL when the kernel in the right hand corner says "Python REPL"

> the shortcut should just work regardless.
Python Native REPL is not meant to send command from your Python file to Interactive Window 

I cannot repro this: 

https://github.com/user-attachments/assets/fb4ba398-ca4b-4920-bd1c-239c807605ac
Please note the first tab in the right hand editor section is interactive window(not sure why its named Python REPL instead of interactive-1, but if you see the kernel section you can see it is ..(venv)..etc and NOT Python REPL)

@peekxc Do you have the setting below checked or no? 

Is there a chance setting 
<img width="864" alt="Screenshot 2024-09-07 at 10 20 25 PM" src="https://github.com/user-attachments/assets/95701931-ab6b-4e29-8bc1-75e6e45433a6">  could be related? /cc @amunger

**Comment by peekxc** [comment]
I have two windows open, actually, an interactive window (via jupyter) and a regular terminal. 

The command should send inputs to the bottom one.

**Comment by amunger** [comment]
> Neither of the above keybinds do anything.

Can you run the command "Toggle keyboard shortcuts troubleshooting" and post the logs from that after trying to use the key binding.

The output panel for either 'python', 'jupyter' or 'window' would likely have an error if the expected command is being run.
