### ISSUE TITLE
Icon for *.scss file not showing

### ISSUE THREAD

**Issue by JimiC** [Microsoft/vscode#22612]
- VSCode Version: Code - Insiders 1.11.0-insider (dd197f19ddad6f8fa960c5f330fb7182c2321de3, 2017-03-13T07:11:52.101Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-icons|robertohuertasm|7.3.0|
|sass-indented|robinbentley|1.3.0|
---

Steps to Reproduce:

1. Create a `scss` file.
2. `scss` icon of `vscode-icons` not showing. Expected icon to be shown (https://github.com/vscode-icons/vscode-icons/blob/master/icons/file_type_scss.svg)

Issue is noticeable only on `Code-Insiders` due to this change (https://github.com/Microsoft/vscode/commit/96bbe8100efa66d25e18ada2b1cbee499d7cf736)
Probably this [line](https://github.com/Microsoft/vscode/blob/master/extensions/scss/package.json#L12) of code is to blame.

More info @ https://github.com/vscode-icons/vscode-icons/issues/808

**Comment by aeschli** [comment]
That's strange. The aliases are just used as labels to be shown to users. Why do you think this has an impact?

**Comment by JimiC** [comment]
@aeschli 
Because when I change `Sass` to `Scss` in the built-in extension instead of one entry `Sass (scss)` in the languages mode, I get two, like `Sass (sass)` and `Scss (sass)`.

**Comment by JimiC** [comment]
Furthermore, when I install `sass-intended` the `Sass (scss)` entry in language mode turns to `Sass (sass)` without me changing the built-in extension.

**Comment by aeschli** [comment]
The bug is that the published version of sass-indent [v1.3.0](https://github.com/robinbentley/vscode-sass-indented/blob/edc30526ce080c149b778fbdcead6b34bad3d6a8/package.json) makes the following file association:
```
	"languages": [{
		"id": "sass",
		"extensions": [
			".sass",
			".scss",
			".sass.erb"
		],
```
which conflicts with the built-in extension scss extension that registers ".scss" with language "scss".
With the change(https://github.com/Microsoft/vscode/commit/96bbe8100efa66d25e18ada2b1cbee499d7cf736) user installed extensions will win against built-in extension. So sass-indent wins and ".scss" goes to language id "sass".

Moving to sass-indent to remove the association of .scss

**Comment by aeschli** [comment]
This issue was moved to robinbentley/vscode-sass-indented#19

**Comment by JimiC** [comment]
@aeschli Thanks for the info. Now we know how to resolve future issues with other extensions.
