### ISSUE TITLE
Extension `vscode.typescript-language-features` setting option to disable the check on the TS 8006 error

### ISSUE THREAD

**Issue by Lerri-Cofannos** [microsoft/vscode#226176]
## Context
When migrating a codebase from Flow to Typescript, I have files in `.js` with type annotations. I would like to use all of the possibilities offered by the typescript built-in extension, but each type declaration or annotation is highlighted as an error for example `'import...type' declarations can only be used in TypeScript files.ts(8006)`. This makes the extension unusable...
This feature would resolve the issue raised by these fellow developers: https://github.com/microsoft/TypeScript/issues/35470

## Feature request
Would it be possible to have a setting option in the extension `vscode.typescript-language-features` to disable the check on the TS 8006 and TS 8010 error?

## Example:

`index.js`
```
// @flow

const foo: string = 'foo';
            ^^^^
console.log(foo);

```

**Comment by mjbvz** [comment]
Linked upstream issue is a better place to discuss this but since it's been 5 years with only 25 upvotes, it's likely not going to happen

More realistically we eventually support node's currently experimental js typing syntax, but that's not the same as Flow: https://github.com/microsoft/typescript/issues/59601
