### ISSUE TITLE
Git clone F1 command error when no folder/project is open

### ISSUE THREAD

**Issue by nicolehaugen79** [Microsoft/vscode#22620]
- VSCode Version: 1.11.0-insider
- OS Version: Win 10

Steps to Reproduce:

1. Launch VS Code - ensure that NO folder\project is open in VS Code (when a project is opened, the command works as expected)
2. Press the F1 key
3. In the commands text box, type "git: clone" - when the command becomes selected, hit enter
4. Expected: Next you should be prompted for the git project url to clone
    Actual: An error occurs saying "command 'git.clone' not found

**Comment by brodytodd** [comment]
This does not appear to be fixed yet. I have a fresh system and am in version 1.13.1 on windows 10. Following the repo steps the error is still there.

The documentation (https://code.visualstudio.com/docs/editor/versioncontrol#_cloning-a-repository) does not indicate any other pre-requisites in order to clone a library.

**Comment by ronnicek** [comment]
Still same issue in 1.18.0
