### ISSUE TITLE
add go to next/previous commented ranges in the editor commands

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#226478]
Screen reader users like @jooyoungseo want to navigate between editor ranges that have comments. 

I think this makes sense. @alexr00, the recording I will share describes this in more detail.

**Comment by meganrogge** [comment]
I just realized that these already exist, `"editor.action.previousCommentingRange"` and `"editor.action.nextCommentingRange"`.

**Comment by jooyoungseo** [comment]
@meganrogge  I respectfully think that we have miscommunication here. I am requesting a feature going to the next commented area. The commands that you are referring to are moving between commentable range, instead of commented area.

The closest commands are alt+F9 (`-editor.action.nextCommentThreadAction`) and alt+shift+F9 `editor.action.previousCommentThreadAction`. However, these commands directly and automatically opens the comment widget. I just want to jump to the next commented lines and manually open the applied comments manually if I need to review.

**Comment by meganrogge** [comment]
Ah, yes makes sense 👍 thanks for reminding me!
