### ISSUE TITLE
No autocompletion for post-2020 JavaScript features

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode#226501]
Type: <b>Bug</b>

Visual Studio Code simply does not recognize/suggest autocompletion of any JavaScript method/function released after 2020.

This list below created by me may not be complete, it would be necessary to observe all the new ECMAScript functions/methods of each year.

From ECMAScript 2021:

- `String.prototype` --> `replaceAll()`
- `Promise.any()`
- `AggregateError`
- `FinalizationRegistry`

From ECMAScript 2022:

- `cause` property on `Error` objects
- `Object` --> `hasOwn()`
- `String.prototype`, `Array.prototype` and `TypedArray.prototype` --> `at()`

From ECMAScript 2023:

- `Array.prototype` and `TypedArray.prototype` --> `toSorted()`, `toReversed()`, `with()`, `findLast()`, `findLastIndex()`
- Exclusively from `Array.prototype` --> `toSpliced()`

From ECMAScript 2024:

- `Promise.withResolvers()`
- `Object` and `Map` --> `groupBy()`
- `Atomics.waitAsync()`
- `String.prototype` --> `isWellFormed()`, `toWellFormed()`

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
- OS Version: Windows_NT x64 10.0.19045

Steps to Reproduce:

1. Create/edit a JavaScript file (e.g. test.js)
2. Start typing (e.g. `String.prototype.`)

**Comment by mjbvz** [comment]
Not sure what was going on since the user was deleted. For anyone else running into this:

- As of VS Code 1.92, the default is ES2022. We will bump this once there's widespread enough support for the new library features across all popular browsers/runtimes

- To use newer library features, you can set the `target` in your `jsconfig`/`tsconfig`

- If you're not seeing ES2022 features, check to make sure your project's `jsconfig`/`tsconifg` does not override the `target`
