### ISSUE TITLE
Test: Shell Integration API

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#226655]
Refs: #145234

- [x] macOS @meganrogge 
- [x] linux @justschen
- [x] windows @dbaeumer

Complexity: 5

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23226655%0A%0A&assignees=Tyriar)

---

The `Terminal.shellIntegration` API has been finalized this iteration. To test this:

1. Clone and open the extension sample https://github.com/microsoft/vscode-extension-samples/tree/main/shell-integration-sample
2. Test to make sure the extension functionality works - open the custom profile via the dropdown on the terminal:
  ![image](https://github.com/user-attachments/assets/139181a8-d54f-4a4b-9ed4-129529bd86cd)
3. Explore the API and its docs. Here are the entry points: [`Terminal.shellIntegration`](https://github.com/microsoft/vscode/blob/70071d2047345046d4aefa02f144e29ea528324e/src/vscode-dts/vscode.d.ts#L7334-L7344), [`onDidChangeTerminalShellIntegration`, `onDidStartTerminalShellExecution`, `onDidEndTerminalShellExecution`](https://github.com/microsoft/vscode/blob/70071d2047345046d4aefa02f144e29ea528324e/src/vscode-dts/vscode.d.ts#L10777-L10794C16)
4. Exercise other functionality of the API, the sample only uses `onDidChangeTerminalShellIntegration` and `executeCommand(string, string[])`

**Comment by dbaeumer** [comment]
@Tyriar I tried for one hour to get shell integration work for me on my Windows machine but no luck. Whatever I do, I never received any `onDidStartTerminalShellExecution`, `onDidChangeTerminalShellIntegration` or `onDidEndTerminalShellExecution` events, so the sample never worked. Here is what I tried:

- setting explicit `"terminal.integrated.shellIntegration.enabled": true`
- Added `if ($env:TERM_PROGRAM -eq "vscode") { . "$(code-insiders --locate-shell-integration-path pwsh)" }` to my profile, following the advise from https://code.visualstudio.com/docs/terminal/shell-integration#_manual-installation
- turned my own profile script off since I have a custom `Prompt` function.

Any hint on how to enable this

**Comment by Tyriar** [comment]
@dbaeumer sounds like it should be working with that setup. Try installing pwsh 7 and using that if you haven't, Windows PowerShell (5) which is shipped with Windows should work but maybe that's why?

**Comment by dbaeumer** [comment]
@Tyriar I use pwsh 7.4.5. Anything I can do (logging) to find out why it is not working?

**Comment by Tyriar** [comment]
@dbaeumer when you hover the tab you should see a long command line like this:

![image](https://github.com/user-attachments/assets/ad26e261-737a-49b4-a643-efdc6b5fafea)

Make sure you don't have `terminal.integrated.windowsEnableConpty` set.

If that doesn't help enable a trace log and check the pty host output channel when you create a terminal. You should see a `[trace] [RPC Request] PtyService#createProcess` log which will have some config associated with it like this:

```json
{"shellIntegration":{"enabled":true,"suggestEnabled":true,"nonce":"80e12edd-a671-4229-a4b9-028ae4b8f609"},"windowsEnableConpty":true,"windowsUseConptyDll":true,"environmentVariableCollections", ...
```

That would be helpful

**Comment by meganrogge** [comment]
Cool 👏 , I think this will be powerful
