### ISSUE TITLE
Visual problem when dark color themes are used

### ISSUE THREAD

**Issue by RookieZn** [Microsoft/vscode#22678]
- VSCode Version: 1.10.2
- OS Version: macOS 10.12.3

Steps to Reproduce:

1. Just use dark color theme
<img width="1440" alt="snapshot" src="https://cloud.githubusercontent.com/assets/17445652/23959945/857f76e2-09e1-11e7-848c-cfbcb0113158.png">

**Comment by weinand** [comment]
It is possible that this issue is caused by an installed extension. Can you try to run VS Code without extensions? From the command line, execute: code --disable-extensions and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/12473
