### ISSUE TITLE
Pop-up Hints showing incorrect JSDoc description or no description for variables/constants referencing a function

### ISSUE THREAD

**Issue by marbakjs** [Microsoft/vscode#22679]
![quickinfo4](https://cloud.githubusercontent.com/assets/26436450/23964510/0e03b88e-09b5-11e7-8686-2e14310e28f9.gif)

```javascript

/**
 * description of a
 */
function a() { }

/**
 * description of curry
 */
function curry() { }

/**
 * description of c
 */
var c = a;
const d = curry(a);
```

VSCode started with --disable-extensions

VSCode Version: 1.10.2
OS Version: Microsoft Windows [Version 10.0.14393]

**Comment by SandHilt** [comment]
This is correct.
Because when you write `c` pop a hint with description of c.
But, when you `c()` this call function of a and show your description and not of c.
Because you don't call c, you call function a.

**Comment by mjbvz** [comment]
Yes, @SandHilt is correct. This is the expected behavior as currently designed.


A discussion of this is being tracked on the TypeScript side the old issue: https://github.com/Microsoft/TypeScript/issues/3520 and I've also opened a new issue (https://github.com/Microsoft/TypeScript/issues/14804) to track this in relation to the signatureHelp specifically
