### ISSUE TITLE
Include some `onFile` callback in findFiles2New?

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#226834]
Testing #226670

Back when I was using the findFiles API in js-debug, it would have been handy if there was a callback to get a file match as it's found so I could start processing them asynchonrously instead of getting them all at once in the returned promise

**Comment by alexdima** [comment]
:+1: Maybe an `AsyncIterator`

**Comment by connor4312** [comment]
Yes, I think returning an async iterable instead would be nice. Currently conversion from that to an array for extensions is a bit annoying, but Node 22 will [make that nicer](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/fromAsync).

**Comment by andreamah** [comment]
I'm considering https://github.com/microsoft/vscode/issues/226734, which should be sufficient for this use case. I would rather just have a general asyncIterator for all results rather than just `onFile` for a certain file, since having a general `onResult` event might lend itself to more use cases.
