### ISSUE TITLE
IDE visual problem

### ISSUE THREAD

**Issue by riskers** [Microsoft/vscode#22683]
- VSCode Version: 1.10.2
- OS Version: 10.12.3

Steps to Reproduce:

1. when i open vscode always shows:

![](http://p1.bqimg.com/567571/bd7b2e2e3ba5e94d.jpg)

2. every theme always show.

**Comment by weinand** [comment]
It is possible that this issue is caused by an installed extension. Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by weinand** [comment]
looks similar to https://github.com/Microsoft/vscode/issues/22678

**Comment by riskers** [comment]
i disable all extensions , but vscode still show this

**Comment by weinand** [comment]
dup of #22678
