### ISSUE TITLE
[bug] Remote-SSH cannot recognize `User` in ssh config file

### ISSUE THREAD

**Issue by monagai** [microsoft/vscode#226920]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.92.2
- OS Version: Windows 10 Pro 22H2
- Remote-SSH Version: v0.113.1

Steps to Reproduce:

1. Set .ssh config fille as fig1.
2. connect ssh
3. In a window requesting my password, different user name is set. (yellow box in fig2)
<img width="269" alt="fog1" src="https://github.com/user-attachments/assets/7c85c3d6-6268-4b1c-8b1a-edff2e5bc8c5">
<img width="1004" alt="fig2" src="https://github.com/user-attachments/assets/7c51559c-d508-472e-b268-7432d6e5c52c">

**Comment by monagai** [comment]
I will move this post to https://github.com/microsoft/vscode-remote-release

**Comment by joshspicer** [comment]
what happens if you do `ssh <name_of_host>` in your terminal?  Can you check other default locations for configuration files to see if there is any conflicting configuration there? It would be easy to accidentally set configuration in another file via our UI:

![Image](https://github.com/user-attachments/assets/b7555acc-fcc6-49c5-a9e4-9511f99485e3)

Also, please try changing the identifier after `host` to something other than the IP address (e.g name it `my_remote_host`).   Your local ssh program is "in charge" of connecting to the remote, we're just pigging backing off that configuration - perhaps its connecting directly to that IP address (and using your local username)
