### ISSUE TITLE
Problem executing shell commands in build task

### ISSUE THREAD

**Issue by smarts** [Microsoft/vscode#22691]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.10586
- Extensions: C#, Docker

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|1.8.0|
|vscode-docker|PeterJausovec|0.0.12|;

---

Steps to Reproduce:

1. download github desktop (to get git and powershell git tools)
1. update your powershell profile to have the same tools that would be used by github desktop
```
Write-Host "Setting up GitHub Environment"
. (Resolve-Path "$env:LOCALAPPDATA\GitHub\shell.ps1")

Write-Host "Setting up Posh-Git"
. (Resolve-Path "$env:github_posh_git\profile.example.ps1")
# Chocolatey profile
$ChocolateyProfile = "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"
if (Test-Path($ChocolateyProfile)) {
  Import-Module "$ChocolateyProfile"
}
```
3. set up a .NET Framework project with vs code build task
4. ensure build task uses some tools only provided in the user's powershell profile (e.g., git in this case)
5. use vs code to build the project and see that it doesn't work (my guess is that it's either not respecting the configured integrated shell or not using the user's profile for the shell)

**Comment by dbaeumer** [comment]
@smarts how do you build the project. Are you running a command in the intergrated terminal or do you define a task (e.g. having a tasks.json).

**Comment by smarts** [comment]
I use `tasks.json`. This inexplicably resolved itself... I'll keep an eye on it and see if I can figure out a repro.

**Comment by smarts** [comment]
Re-opening. If I launch VS Code from a shell that has git in the path, then the task (that uses git under the covers) works. If I launch VS code from a different shell or from Windows Explorer then I see the problem I described above. Since powershell is the default shell, and is used for running the tasks in `tasks.json`, it seems like it should be using the current user's powershell profile.

**Comment by dbaeumer** [comment]
@smarts how does your tasks.json look like?

**Comment by dbaeumer** [comment]
Without additional information we can't work on this issue. Please ping when the information is available and we will reopen the issue.

**Comment by smarts** [comment]
I can show you my `tasks.json`, but it won't help you. It's just running msbuild agains a .proj file.
My repro steps should give enough info. Is there some part that's unclear? @dbaeumer

**Comment by dbaeumer** [comment]
@smarts I have an idea why this is happening but to validate I need the content of the tasks.json file.

**Comment by smarts** [comment]
ok @dbaeumer i will try to post it this weekend.

**Comment by smarts** [comment]
```{
    "version": "0.1.0",
    "command": "msbuild",
    "args": [
        "build.proj",
        // Ask msbuild to generate full paths for file names.
        "/property:GenerateFullPaths=true"
    ],
    "taskSelector": "",
    "showOutput": "silent",
    "tasks": [
        {
            "taskName": "build",
            "suppressTaskName": true,
            // Show the output window only if unrecognized errors occur.
            "showOutput": "silent",
            // Use the standard MS compiler pattern to detect errors, warnings and infos
            "problemMatcher": "$msCompile"
        }
    ]
}
```

**Comment by dbaeumer** [comment]
@smarts you are running msbuild outside a shell. Even if you would this will very likely not fix our problem since node takes cmd.exe as the default shell hence not honoring any PowerShell settings.

However the new terminal runner supports this. Switch to version 2.0.0 and make PowerShell your default terminal in VS Code and add "isShellCommand": true to the tasks.json. This should execute msbuild in PowerShell in the integrated terminal

**Comment by smarts** [comment]
@dbaeumer version 2.0.0 of what? and powershell is already my default terminal. i'll try `"isShellCommand": true` though

**Comment by dbaeumer** [comment]
@smarts 

The task definition you provided is executed as a process in the OS. That means it is not executed in a shell/terminal environment. To execute a process in a shell/terminal environment you need to set isShellCommand: true for a task. This means VS Code first spawns a shell and then executes msbuild inside that shell. The current shell execution under Windows is done using cmd.exe (tasks.json version attribute set to "0.1.0".) We have a new execution engine (not the default yet) that executes a task in the terminal (version attribute "2.0.0"). See https://code.visualstudio.com/updates/v1_10#_task-support. The new engine executes the task in the terminal instead of the output window. So if you default VS Code terminal is set to powershell it will execute the task in powershell hence starting the msbuild in a powershell environment. 

However if you execute VS Code from a shell (this wasn't clear to me) msbuild should see the environment variables. You can check if they are available doing the following:

- start VS Code
-  open the Dev Tools from the Help menu
- type process.env into a console to see if the environment contains your environement

![capture](https://cloud.githubusercontent.com/assets/1931590/26142032/1227a83e-3adf-11e7-8440-e06c5080448b.png)

**Comment by smarts** [comment]
:bulb: ! ok, thanks for that explanation @dbaeumer
