### ISSUE TITLE
The customized "path" cannot be used by debugger

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#22693]
_From @dead-lee on March 14, 2017 10:17_

I don't have admin right to my working desktop. So I am using below bat to start code:
Set PATH=%PATH%;"P:\IMWB\OCE_JXL\branches\Bluemix_POC\tools\node-v6.9.5-win-x64"
P:\Documents\VSCode-win32-1.10.2\code "P:\IMWB\OCE_JXL\branches\Bluemix_POC\src\api_connect"

I can get node working in "Integrated Terminal".  But not working in debug mode: "Cannot find runtime 'node' on PATH."

_Copied from original issue: Microsoft/vscode-docs#886_

**Comment by joaomoreno** [comment]
This is Windows, in which there isn't any PATH magic.

**Comment by weinand** [comment]
@dead-lee as a workaround you can explicitly make VS Code find your version of node by setting the `runtimeExecutable` attribute in your launch configuration to the node's path.

**Comment by dead-lee** [comment]
I tried workaround suggested by weinand but not working. Here's my updated launch.json:
{
    // Use IntelliSense to learn about possible Node.js debug attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${file}"
            "runtimeExecutableattribute": "P:\IMWB\OCE_JXL\branches\Bluemix_POC\tools\node-v6.9.5-win-x64"
        },
        {
            "type": "node",
            "request": "attach",
            "name": "Attach to Process",
            "address": "localhost",
            "port": 5858
            "runtimeExecutableattribute": "P:\IMWB\OCE_JXL\branches\Bluemix_POC\tools\node-v6.9.5-win-x64"
        }
    ]
}

**Comment by weinand** [comment]
@dead-lee your launch configurations from above are broken in many ways.

I suggest that you let VS Code Intellisense guide you when editing them. Red squigglies definitely mean that they are incorrect. Here is what I saw:

![2017-03-21_09-23-27](https://cloud.githubusercontent.com/assets/1898161/24138376/4cdefebc-0e18-11e7-8041-9e02ee3c5fca.png)

The problems in details:
- a comma is missing at the end of line 11 (`"program": "${file}"`)
- the correct name of the attribute is `runtimeExecutable`
- backslashes in the runtimeExecutable path must be escaped with a second backslash (or just use single forward slashes instead).
- the path runtimeExecutable path must point to the node.exe program in that folder not to the folder itself.
- the second launch config "Attach to Process" does not support the `runtimeExecutable` because in the 'attach' case there is nothing to launch by definition. 
  
So in the end the launch config should look like this:
![2017-03-21_09-33-55](https://cloud.githubusercontent.com/assets/1898161/24138733/a75f37ac-0e19-11e7-932d-bfd4cf129063.png)

Please note that this launch config starts a debug session for the currently open file in the editor (that's the `"${file}"` in the program attribute). This requires that you have the correct file open before pressing 'F5'.

It might be better for you to hard code the name of your program (e.g. `myProgram.js`) directly in the launch config:

```ts
{
	"type": "node",
	"request": "launch",
	"name": "Launch Program",
	"program": "${workspaceRoot}/myProgram.js",
	"runtimeExecutable": "P:\\IMWB\\OCE_JXL\\branches\\Bluemix_POC\\tools\\node-v6.9.5-win-x64\\node.exe"
},
```

**Comment by dead-lee** [comment]
Cool, workaround works.
