### ISSUE TITLE
Cannot launch vscode-languageserver-node-example server under debugger

### ISSUE THREAD

**Issue by jflam** [Microsoft/vscode#22720]
- VSCode Version: 1.10.2
- OS Version: Win 10 14393.953
- Node version 6.9.4

**Steps to Reproduce:**

```
1. git clone https://github.com/Microsoft/vscode-languageserver-node-example 
2. cd vscode-languageserver-node-example\src\client
3. npm install
4. npm build
4. cd ..\server
5. npm install
6. npm build
7. code .
8. F5
```

Error: `Cannot connect to runtime via 'legacy' protocol; consider using 'inspector' protocol (timeout after 10000 ms).`

Incidentally, I tried to enable tracing - according to the docs here: https://code.visualstudio.com/docs/editor/node-debugging there should be a `trace` attribute that I can add to my configuration, which I can set to `all` to enable verbose debugging. That fails as well, with the error: `Property trace is not allowed`

The server does run fine if I launch it via the client project. But I cannot debug the server code. This used to work ... recently - in the past month or so for me. But no longer, and on multiple machines.

**Comment by weinand** [comment]
You are missing some steps.

The "F5" in the server directory tries to attach to the language server,  but there is no language server running because you forgot to start the client.

Please follow the tutorial: https://code.visualstudio.com/docs/extensions/example-language-server#_debugging-both-client-and-server

And the tracing attribute works fine, just the error squiggly "Property trace is not allowed" in the json editor is still wrong. Please ignore it.
