### ISSUE TITLE
Add math support to Markdown

### ISSUE THREAD

**Issue by mkoske** [Microsoft/vscode#2273]
It would be nice to have math support on Markdown preview.

Maybe [this](https://github.com/Khan/KaTeX) could help?

**Comment by mjbvz** [comment]
Extensions can now extend the markdown preview with this functionality: https://code.visualstudio.com/docs/extensionAPI/api-markdown

The [MD math extension](https://marketplace.visualstudio.com/items?itemName=goessner.mdmath) is already looking into using this new API instead of providing a custom markdown preview
