### ISSUE TITLE
SystemService CI task keeps failing often

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#227386]
In the last weeks I have seen plenty of failed CI that are like this

https://dev.azure.com/vscode/VSCode/_build/results?buildId=130406&view=logs&j=f3dd96f0-7bf9-51c6-1e87-22c4cfa2ad69&t=d9d04af8-2d06-5707-c20a-49c40c558dcb

**Comment by deepak1556** [comment]
This would be an issue in the build image since we pretty much call `apt-get install` in an isolated job. I see a similar issue in the runner repo https://github.com/actions/runner-images/issues/1120 and it seemed to have been addressed with the following retry logic https://github.com/actions/runner-images/blob/ubuntu22/20240825.1/images/ubuntu/scripts/build/configure-apt-mock.sh that seems to be present with all Ubuntu agents. @lszomoru if I want to file an issue related to the build agent is there a separate repo for 1ES images where it should be filed or filing in https://github.com/actions/runner-images/issues is the way to go ?

FWIW I copying the retry logic on our end as well since in worst case it would be a double retry https://github.com/microsoft/vscode/tree/robo/fix_dpkg_lock, hoping it to work as a temporary solution.

**Comment by lszomoru** [comment]
You can engage with the team though their [Teams channel](https://teams.microsoft.com/l/channel/19%3A7c56ede040c1440cb2029ceaf6c681f3%40thread.tacv2/General?groupId=32d444ca-9d5f-477a-a65b-363785e0aa82&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47).

**Comment by deepak1556** [comment]
Failures have not been seen since the retry logic was added, closing as I don't intend to pursue further on this.
