### ISSUE TITLE
Go to symbol doesn't work unless I open corresponding file type

### ISSUE THREAD

**Issue by syabro** [microsoft/vscode#227527]
Does this issue occur when all extensions are disabled?: Go to symbol doesn't work at all with extensions disabled

- VS Code Version:  Version: 1.91.1
- OS Version: Mac OS Sonoma 14.5 (23F79)

Steps to Reproduce:

1. Open a project but don't open any py files
2. try to press got to symbold and enter `#classname`
3. See "no symbols found"
4. Open any empty file, eg `__init__.py`
5. try to press got to symbold and enter `#classname` - see it's working

Same for React components, not only for py files
Video attached

https://github.com/user-attachments/assets/a02feada-9cdb-430f-a1a2-88cae5a8cf0f

Looks like VSCODE doesn't activate language server or something like unless I open corresponding file type

**Comment by gjsjohnmurray** [comment]
I guess that the relevant extensions don't use the [`workspaceContains`](https://code.visualstudio.com/api/references/activation-events#workspaceContains) activation event.

**Comment by syabro** [comment]
PS Updated vscode - problem still exists

@gjsjohnmurray both? Microsoft's python extension and internal typescript? Can you provide me an example of the extension you sure works this way so I can check?

**Comment by syabro** [comment]
Okay, more info
I've  folder `backend`  and `frontend`
If I do 
- `code .` opening the whole project - `#Version` doesn't work
- `code backend` opening the backend folder only - `#Version` start to work even no files opened
- `code frontend` opening the frontend folder only - `#App` doesn't work unless I open any `ts` file

**Comment by mjbvz** [comment]
@gjsjohnmurray Is correct about the likely cause 

To add some additional details: in some cases, it's not enough for a language extension to be activated, you also have to open a file from the project. That's how JS/TS works. You only get workspace symbols once a js/ts project has been loaded

It's implemented this way because the alternative has the potential to be extremely slow as it would require us to activate and request workspace symbols from every installed language extension

---

If you feel there's something python specific that could be improved for this, please file an issue against the Python extension

**Comment by syabro** [comment]
> That's how JS/TS works

Sorry? I don't get it. 

> It's implemented this way because the alternative has the potential to be extremely slow as it would require us to activate and request workspace symbols from every installed language extension

Emm, but I have the project exists. Can VSCode save something like "we've opened ts + py - activate these extensions"
