### ISSUE TITLE
vscode hangs on ubuntu

### ISSUE THREAD

**Issue by obrona** [microsoft/vscode#227777]
- VS Code Version: 1.93.0
- OS Version: Ubuntu 24.04.1 LTS

Steps to Reproduce:

1.  Download vscode for linux
2.  type `code --verbose`

Then code is stuck on this command
```
[EncryptionMainService] Checking if encryption is available...
```

**Comment by KevinXuzio** [comment]
I am getting the same error, only thing to note other than a fresh install was installing github CoPilot

**Comment by Estebmaister** [comment]
I have just installed Ubuntu from scratch, installed vscode and got this error when trying to login for backup

**Comment by KevinXuzio** [comment]
> I have just installed Ubuntu from scratch, installed vscode and got this error when trying to login for backup

Probably has nothing to do with Co-Pilot then, but I haven't been able to rectify the issue so hopefully someone has a suggestions

I was a fresh install of Ubuntu as well

**Comment by jreuschPSI** [comment]
had exactly the same issue today.
was wondering, even happend in an empty directory.

just noticed that gnome-keyring was running again and was provinding the `org.freedesktop.secrets.service` endpoint.

after killing gnome-keyring and enabling this in keepassxc again vscode starts without freezing immediatelly.

i do not think it is linked to keepassxc (since it was not in the chain) but maybe that hints you in the right direction?

**Comment by Razish** [comment]
> after killing gnome-keyring and enabling this in keepassxc again vscode starts without freezing immediatelly.

Interesting, thanks for the bandaid fix.
I'm on a fresh Debian machine. VSCode started freezing after installing GitLens extension.
Killing `gnome-keyring` and starting VSCode worked for me; it now prompts to unlock my keyring at the point it would have frozen.

**Comment by its-darsh** [comment]
same here, it becomes unusable once it hangs, i notice that it hangs more when i switch to another windows and back over to vscode, i'm using vscode for Go development at the moment. notably, i've been using vscode for some python development and never been facing this issue but this might be just placebo since i don't really do much python these days

_i've really been considering moving over to another editor_

**Comment by H0lzm1ch3l** [comment]
> after killing gnome-keyring and enabling this in keepassxc again vscode starts without freezing immediatelly.

Hi,
I have the same issue and don't really know how to kill gnome-keyring, does it have a PID or how do I go about that?

**Comment by pedro-com** [comment]
You can open the system monitor, go to Processes, search for gnome-keyring-daemon and end the process. When you start vscode again it prompts you to authenticate again
