### ISSUE TITLE
programming profile quick switcher is gone

### ISSUE THREAD

**Issue by byggwir** [microsoft/vscode#227872]
Does this issue occur when all extensions are disabled?: Yes/No (don't know - the point of profiles for me is to switch between different configurations of extensions which are exclusive to each other in the profiles)

- VS Code Version: 1.93 (changed in this version !)
- OS Version: Windows 10 and Windows 11 (saw it on 2 computers)

Steps to Reproduce:

1. Open Settings gear symbol on lower left
2. Profile does not have a submenu to switch the profile anymore like in the picture below taken from the version before.
3. The new profile UI was activated in the prior version. The setting seems to be gone or I didn't find it anymore.

This was awesome. I could just change it without another dialog opening. Would be great to have it back.

![grafik](https://github.com/user-attachments/assets/b43f1df0-7b85-4b4b-b170-dd018cdab5ea)

**Comment by FH-Inway** [comment]
For me, switching profiles in a workspace was a common action. I work with monorepos and multiple customers where each customer has their own monorepo. I would reuse the profiles across monorepos for activities that are the same in each monorepo. So e.g. for customers with markdown documentation I have a markdown profile when editing this documentation. For monorepos that contain C# code, I would then switch to the C# profile to work on that. 
Note that while the activities are the same across monorepos, not each monorepo has content for all activities (otherwise I would just use one big profile with extensions and settings for all activities). So if there are activities A, B and C and monorepos foo and bar, foo would have activities A and C while bar would have B and C. 
This also allows changing a profile and have that change available in all monorepos. If the profiles are monorepo specific, it becomes harder to transfer a change for e.g. the C# activity to other profiles.

I hope this will be reconsidered and at least a setting is provided to bring back the profile quicks switcher.

**Comment by sandy081** [comment]
Reopening this to consider it for discussion

**Comment by rafaelkothe** [comment]
Same issue here (as mentioned in duplicate #228944 )!

I use VS Code for my research and switch between two profiles: one for coding tasks and another for LaTeX work (with a lighter theme, fewer or different extensions, etc.). Whenever I generate new results or need to update the Methods section of my paper after adjusting the code, I quickly switch profiles, navigate to my open LaTeX file, make the necessary changes, and then switch back to my coding profile.

While it's not a huge deal to work with the new profile editor, I can see how things could get quite messy with multiple profiles. Also, I’m not entirely sure why a profile is now linked to a workspace. Isn’t the point of workspace settings to differentiate between various workspaces, while profiles are intended for different "users" working within the same workspace?

**Comment by byggwir** [comment]
I didn't even notice it is tied to a workspace. I used the feature without workspaces except one.
I switch the profile to get a set of extensions I wanna use. I was hoping for better performance if I streamlined my extensions and settings for the task at hand. Not the workspace.
I'd then really appreciate the feature back also for non-workspaces and fast switching.

**Comment by hediet** [comment]
I think that switching profiles is more common than managing profiles. Thus, I'd also go back to this situation:

> ![grafik](https://github.com/user-attachments/assets/b43f1df0-7b85-4b4b-b170-dd018cdab5ea)

Maybe we can rename "Profiles" to "Manage Profiles..."

**Comment by isidorn** [comment]
I like @hediet suggestion to sue "Manage Profiles" I would not use the `...` since Settings and Extensions do not use `...` and it is a similar experience.

Ideally if there is just the default profile, this would not be a submenu, but just one action. And it turns into a submenu once there are 2+ profiles.

Btw Outlook also calls it Manage Profiles

**Comment by ab763** [comment]
I also use multiple profiles in a monorepo with many different file types, with different VSCode extensions per type - multiple programming languages, shell scripts, documentation files, etc., but I use the profiles as a way to reduce malware risk from a 3rd party extension downloading/running arbitrary binaries - by only having the needed extensions enabled for the current file type, I figure that gives more of a chance for Microsoft to catch an extension update that introduces malware before I have that specific extension enabled again. (Other items like adding extension permissions/sandboxing https://github.com/microsoft/vscode/issues/52116 or the not-planned auto-switch-profile-based-on-language https://github.com/microsoft/vscode/issues/174211 would also help, but in the absence of those, manual profile switching seems like the best chance to reduce the risk of extensions downloading/running arbitrary binaries on my system, presuming we aren't avoiding 3rd party extensions entirely.)

**Comment by ab763** [comment]
Also, at present in the command palette, "Profiles: Open ___ Profile" is a top-level command which opens the profile in a new window, but "Profiles: Switch Profile" is a multi-step command (with the specific command selected (after "Switch Profile" is selected) which opens the profile in the current window. I more commonly switch profiles for the current window, not a new window, so my preference would be to switch the one-step/multi-step commands, although I don't know which is more common for others.

**Comment by galloppinggryphon** [comment]
I frequently open folders on disk in vscode to peruse and/or edit files. Maybe Python, maybe JS, maybe R, maybe something else. It was extremely handy to be able to quickly select the right profile for that folder. I strongly encourage you to bring this back. While it's not hard, per se, to switch via the command palette, sometimes you're just feeling, well, mousey, and don't want to move your hands over to the keyboard. Besides, there's such a thing as too much minimalism.

**Comment by FH-Inway** [comment]
Thank you!

![Image](https://github.com/user-attachments/assets/e50a67c5-5f2b-4113-9fa5-e2993f6b34e6)

**Comment by isidorn** [comment]
@FH-Inway love your profiles! I can only imagine what is "Code Crime Scene" 😆
