### ISSUE TITLE
Indicate in the UI that conditional breakpoints are not supported by a debug adapter

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#2278]

**Comment by isidorn** [comment]
@stevencl @bgashler1 some debug features will not be supported by some debug adapters. For example, powershell might not support conditional breakpoints. We need to think about how to handle this in the UI in a good way. 
One option is just to not show any UI for adding conditional breakpoints or to somehow make the user aware that conditional breakpoints will not be respected for powershell.
Another tricky thing is that VSCode becomes aware if conditional breakpoints are supported only on the first launch of a debug session. So then it can happen that some UI is suddenly not available which might be strange. Due to this I am not in favor of hiding some parts of the UX but I prefer that we somehow make the user aware that some funcitonality is not supported in his current work flow.

We can also discuss this in our weekly UX sync.

**Comment by stevencl** [comment]
How feasible would it be to query the debug adapter before first launch to find out what is possible?

**Comment by stevencl** [comment]
One option would be that if we need to wait until debug launch that those breakpoints that have conditions attached which we know won't be hit we show with a '?' instead of '='. When the user hovers over it we say 'The [name of debug adapter] debug adapter does not support conditional breakpoints.'

**Comment by isidorn** [comment]
We can not query the adapter before first launch, since we only launch the debug adapter on debug start.
The solution you proposed sounds good to me.

**Comment by isidorn** [comment]
@bgashler1 it looks like I will need the '?' icon for this

**Comment by bgashler1** [comment]
Added the icons ae75a36b3b937b25f99912001ff77264064d033a
There is one for light and dark.
![image](https://cloud.githubusercontent.com/assets/11839736/13024737/ab596d58-d1ae-11e5-8196-edc26dacd625.png)

**Comment by isidorn** [comment]
I have adopted this on the vscode side.

@bgashler1 dark theme icon looks the same as white theme, I think you uploaded twice the same one. Also the question mark does not look properly centered. Can you look into these issue

@weinand I have added `suppportsConditionalBreakpoints` to `debugProtocl.d.ts` note 74ca4c3. If the adapter does not specify anything here I act as if the adapter does not support conditional breakpoints. I can change that such that the adapter has to explicitly specify if he does not support conditional breakpoints. Opinions? In any case, Node Adapter now needs to send this with the rest of the capabilites
We should also ping the other adapter writers to adopt this. We can just ping them on this issue or is it better to send an end of sprint e-mail regarding the changes?

**Comment by weinand** [comment]
@isidorn I'm now returning the `suppportsConditionalBreakpoints = true` from node-debug but I'm seeing the following behaviour: if I create a conditional breakpoint outside of a debug session, I'm seeing the '?' icon which gets replaced by the '=' icon on session start.
This does not match the behaviour for unconditional breakpoints, which are verified outside of a session.
We should show conditional breakpoints with the '=' icon outside of a session.

**Comment by isidorn** [comment]
I'll fix that right away

**Comment by isidorn** [comment]
@bgashler1 Joao also had a feedback that this should not be a question mark, but an exclamation mark, Not completely convinced, both work for me but just wanted to pass on the feedback

**Comment by bgashler1** [comment]
@isidorn thanks for the feedback (and for passing on Joao's feedback).  I've updated the icons accordingly.


Concerning the light/dark icons looking the same as each other, the icons are actually slightly different.  The dark theme breakpoints are slightly lighter than the light theme ones.  This was intentional to match how our current breakpoints look between light and dark themes.

**Comment by isidorn** [comment]
Nice job, I like it
