### ISSUE TITLE
"Add import from" quickfix on OSS workspace doesn't add '.js' suffix that ESM requires

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#227968]
Type: <b>Bug</b>

When contributing to OSS, make an edit that references a type for the first time in a .ts file

![image](https://github.com/user-attachments/assets/40532f89-a31c-4447-903d-fcb078afdbc4)

Use the quickfix.

Observe that the added import has a warning:

![image](https://github.com/user-attachments/assets/a6e5e114-21f7-4974-b043-cc84a2086cc5)

Fix it by adding the '.js' suffix that the quickfix omitted.

![image](https://github.com/user-attachments/assets/30f7b434-74b9-41fc-99e9-7e13be8b5365)

VS Code version: Code - Insiders 1.93.0-insider (4849ca9bdf9666755eb463db297b69e5385090e3, 2024-09-04T13:13:15.344Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by mjbvz** [comment]
Can be fixed by setting `"typescript.preferences.importModuleSpecifierEnding": "js"`. However I haven't done this as a workspace setting because it will also effect our built-in extensions if you open the entire project as a single folder

We need something like https://github.com/microsoft/vscode/issues/32693 to support this correctly, with `src` having the setting enabled but the built-in extension still using extension-less imports
