### ISSUE TITLE
[html] CSS in HTML does not handle escaped quotes

### ISSUE THREAD

**Issue by BalaM314** [microsoft/vscode#228060]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.93.0 Commit 4849ca9bdf9666755eb463db297b69e5385090e3
- User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:130.0) Gecko/20100101 Firefox/130.0
- Embedder: vscode.dev
- OS Version: Windows 11

Steps to Reproduce:

1. Paste the following code into an HTML file:
```html
<div style="font-family: &quot;Arial&quot;"></div>
```

This is valid HTML.
```
>> console.log($("div").attributes.style.value)
font-family:"Arial"
```

Issue Description:
![image](https://github.com/user-attachments/assets/d0d5da37-f08d-4ea1-b0de-42e596666c4f)

The CSS checker is directly passed `&quot`, which causes an error.
The HTML language handling should replace HTML escape sequences in style attributes before passing the CSS to the CSS checker.

**Comment by iamdereky** [comment]
Hi @aeschli

My partner, @ldaanish, and I are currently students at the University of Michigan, who are currently working on a software engineering project. For this project, we are interested in contributing to the VSCode repository. After reviewing this issue https://github.com/microsoft/vscode/issues/228060, we feel that this issue is within our skill set and project scope. As a result, we would love to work and be assigned to this issue. We will ensure that all coding and contribution guidelines are followed and upheld.

Thank you for considering our request!

**Comment by aeschli** [comment]
Hi @iamdereky, yes of course that would be great.

The code for this is in the HTML language server: 

https://github.com/microsoft/vscode/blob/main/extensions/html-language-features/server/src

The HTML server parses the document to find the embedded scripts and style elements and forwards these to a TypeScript or CSS library.

https://code.visualstudio.com/api/language-extensions/embedded-languages has more background.
We use the '[Language Services](https://code.visualstudio.com/api/language-extensions/embedded-languages#language-services) approach,

It creates a CSS document out of HTML and maps it, so it is valid CSS. But it only replaces characters, 1:1, so all offsets stay the same.

The easiest way to develop this is with the tests:

https://github.com/microsoft/vscode/blob/ff6beb57c035595c36a840d0ad8729c233c9d85f/extensions/html-language-features/server/src/test/embedded.test.ts#L119
