### ISSUE TITLE
Panel tabs lack a visual separator below them (differing from side bar tabs)

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#228083]
Type: <b>Bug</b>

Maybe this is intentional, but I first noticed it when I used the new `"workbench.panel.showLabel": false` setting to make Panel use icons, matching my top-located Side Bar tab icons.

Panel:

![image](https://github.com/user-attachments/assets/6f4d97f8-eb22-4f8a-8532-62f89cc7417a)

Primary Side Bar (top, right):
![image](https://github.com/user-attachments/assets/daacc0af-d664-4f77-a415-a83881690616)

Secondary Side Bar:

![image](https://github.com/user-attachments/assets/b20684ba-d8fc-4873-9ece-e68e1766fa84)

`"workbench.colorTheme": "Default Light Modern"`

VS Code version: Code - Insiders 1.94.0-insider (8b7eb51f54d7e1492d9baf70454ab6547a4ff9df, 2024-09-10T05:04:21.546Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by benibenj** [comment]
The reason there is no border is because the activity actions in the pane are in the same row as the view pane actions, so we don't really want a border in this case. This is the same in the secondary side bar when activity bar is set to default. When activity bar is at the top we add the border as activity bar and view container are separated.

We are still experimenting with `"workbench.panel.showLabel": false` so there might be changes here.

**Comment by benibenj** [comment]
We will keep this the same as the secondary sidebar in when activity bar location is set to default. There is currently a PR open to add a color for the bottom border. If we add it next month, users/themes will be able to have this behaviour.

![Image](https://github.com/user-attachments/assets/9ebdb475-6078-4964-9625-3fcd71b68fb8)
