### ISSUE TITLE
Document link provider API stopped working for output channels

### ISSUE THREAD

**Issue by ArtemGovorov** [Microsoft/vscode#22869]
- VSCode Version: Version 1.11.0-insider (1.11.0-insider) 05f19eec2042555ca04e5f014befa95248a65fe9
- OS Version: all

We are using the `vscode.languages.registerDocumentLinkProvider` like this:

``` javascript
vscode.languages.registerDocumentLinkProvider({language: 'wallaby-output'}, {
        provideDocumentLinks: doc => {
          ...
        }
});
```

where the `wallaby-output` is our output channel language name with `"text/x-code-output"` `mimetype`:

```
"contributes": {
    ...
    "languages": [
      {
        "id": "wallaby-output",
        "mimetypes": [
          "text/x-code-output"
        ]
      }
    ],
    ...
  },
```

In v1.10.2, the `provideDocumentLinks` is invoked as expected and we are able to add links in our output channel:
<img width="498" alt="screen shot 2017-03-20 at 3 30 50 pm" src="https://cloud.githubusercontent.com/assets/979966/24089437/64e41d6c-0d82-11e7-8843-8bf865acd52c.png">

In the insiders build Version 1.11.0-insider 05f19eec2042555ca04e5f014befa95248a65fe9, the `provideDocumentLinks` is not invoked anymore, so output channel can not provide links anymore:
![screen shot 2017-03-20 at 3 31 23 pm](https://cloud.githubusercontent.com/assets/979966/24089473/ce0f37fe-0d82-11e7-9770-923137bb28ec.png)

**Comment by isidorn** [comment]
After doing some git bisection it seems like commit https://github.com/Microsoft/vscode/commit/fcc508fd258e623c714afc97d3121df76af321f0 changed this behavior. Thus assigning back to @jrieken 

Here's a small [example extension](https://github.com/isidorn/provideDocumentLinks) that shows the broken behavior
1. trigger hello world command
2. hello from zurich should be printed to console - it does not, since the `provideDocumentLinks` is not being called

![screen shot 2017-03-20 at 15 35 23](https://cloud.githubusercontent.com/assets/1926584/24104587/e10a4ec0-0d82-11e7-92fe-10553f11565f.png)

**Comment by jrieken** [comment]
Sorry @isidorn 🙏 

This is the consequence of our new document-selector matching logic: Given a selector like above `{language: 'wallaby-output'}` it will by default only match against the `file` and `untitled` scheme. @ArtemGovorov This will work again when explicitly specifying the scheme of the output channel, my guess is that it's `inmemory`.

We have done that change because 99% of the extensions authors are confused when encountering documents like `git:///Users/Me/some/file.js` or `jar:///some/class.java` and start validation et al for this *virtual* documents.

**Comment by ArtemGovorov** [comment]
@jrieken Thanks for the explanation. Specifying the `inmemory` scheme didn't work, apparently it's `output` now for output channels.

**Comment by jrieken** [comment]
👍 great. `inmemory` was my best guess...
