### ISSUE TITLE
Unable to Run and View Code

### ISSUE THREAD

**Issue by Hstephens2024** [microsoft/vscode#228606]
I am unable to view the output for my programs. Im not sure if it is my schools external site causing a problem with your website, but it will now allow me to view any output at all.

Version: 1.93.1
Commit: 38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by karthiknadig** [comment]
We sincerely apologize for the delay in responding to your issue. Due to the high volume of reports, we’ve been unable to address every submission promptly, especially those that lack the details needed for us to investigate effectively.

To ensure that we can help you and others more efficiently, we kindly request that issues include detailed and actionable information. This allows us to narrow down the problem and work on a resolution faster. Please refer to our [issue reporting guidelines](https://aka.ms/vscodeissuereporting) for guidance on how to provide the necessary details.

We value your feedback and thank you for taking the time to report issues—it helps us make the product better for everyone.

Happy Coding!
