### ISSUE TITLE
Missing variables and call stack when pausing application

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#2289]
```javascript
var count = 1;

setInterval(function () {
  console.log(count++);
}, 1000);
```

If I launch this in the debugger and press pause, I never get variables or call stack. If I set a breakpoint and break there, I do get them.

![image](https://cloud.githubusercontent.com/assets/22350/12578443/1fe499c2-c421-11e5-96bd-76fbe415a195.png)

**Comment by weinand** [comment]
@joaomoreno that's expected. If you pause node while waiting in the OS, there is no call stack. In your example the likelyhood of waiting in the OS is rather high.

**Comment by weinand** [comment]
result of testplan item #2188

**Comment by csholmq** [comment]
@weinand How come variable list is empty except at breakpoint? In remote debugging it would make sense to have variables available to e.g. drag to Watches. Even when not at a breakpoint.

**Comment by weinand** [comment]
@csholmq the variables list is scoped to a stack frame (which is again scoped to a thread in multi threaded environments). What should the variable list show when the program is running? The stack is constantly changing, and there are multiple threads running concurrently. Updating all variables all the times is neither practical nor useful. And even if the program is waiting in the OS (but not stopped), it is not possible to show variables because the stack is empty, and there are no frames.

**Comment by csholmq** [comment]
@weinand You are right. That wouldn't make sense. I guess what I was looking for was an easy way to add a variable to Watch since hover doesn't work unless paused. 

`editor.debug.action.selectionToWatch` seems to do what I want. Pity it doesn't continuously update though. Or that hover works in all stages.

I am doing remote GDB debugging using an ELF file, so I don't have any good access to breakpoints unfortunately.

**Comment by weinand** [comment]
@joaomoreno we are now showing an explanation why the callstack is empty:

![2016-06-03 15-19-37](https://cloud.githubusercontent.com/assets/1898161/15779803/ce8f7720-299e-11e6-8e3d-54ef70b5c62a.png)

BTW, if you set the interval value to 1 (instead of 1000), you will actually get a call stack more frequently.

**Comment by joaomoreno** [comment]
@weinand Looks good. The verb is missing in that sentence though. Maybe change it to `No call stack because the program is paused outside of JavaScript.`.
