### ISSUE TITLE
Cannot create a file inside a folder with backslash in its name

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#22898]
related to https://github.com/Microsoft/vscode/issues/21684

* create folder `\eee\`
* find it in the explorer, right-click, create new file with `newfile.txt`
* 🐛 the new file will be created inside `eee/newfile.txt`

**Comment by bpasero** [comment]
@jrieken the problem is that I am using [`path.join()`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/browser/fileActions.ts#L647) to produce the new name when creating a file or folder and this takes a `backslash` and converts it to `slash`. Since `backslash` is a valid segment on Linux and macOS, I think the fix has to go into `path.join()` to leave `backslash` as they are.

This also seems to be what node.js is doing:

![image](https://cloud.githubusercontent.com/assets/900690/24151703/c066e992-0e06-11e7-9847-41a6845e88ba.png)

**Comment by jrieken** [comment]
fyi @bpasero that I have no intentions of investing more into our paths-module. Instead the path-module from nodejs should be used.

**Comment by bpasero** [comment]
Makes sense.

**Comment by jrieken** [comment]
closing as won't fix (see https://github.com/Microsoft/vscode/issues/22898#issuecomment-289033109)
