### ISSUE TITLE
Welcome screen "Welcome" button vs "Go Back" button?

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#228946]
Repro:

1. Delete code stable's user data dir
2. Launch code stable

See the `< Welcome` button in top left:

![Image](https://github.com/user-attachments/assets/517db640-d148-43dc-b069-b206c6ae6cf2)

When I did this same repro in code insiders I saw `< Go Back`:

![Image](https://github.com/user-attachments/assets/70c44679-9785-46de-a9b3-d20192c7244b)

I'm not sure under what circumstances either of these show up, but if the walkthrough shows up now instead of the welcome view I think we should just special case it and remove the welcome button all together.

**Comment by bhavyaus** [comment]
Here's how this works currently :

1. `Go Back` is shown on the walkthrough page when

-  The walkthrough is opened from the welcome page (so that you can go back to the welcome page)
- Or if you arrived at the walkthrough using the `Next` button from a prev walkthrough (so that you can go back to the prev walkthrough).

2. We Do NOT show the `Go Back` on the walkthrough page if the walkthrough was opened from the Command Palette `Developer: Open Walkthrough` -> `Pick Walkthrough` 

EXCEPT on first launch where we show the `Go Back` button. I believe we should show this on first launch just to give users the opportunity to discover the `Welcome` page.  🐛 I'll special case this scenario and show `< Welcome` in this case.

**Comment by bhavyaus** [comment]
Verification:

- Launch a new isntance of VS Code.
- Verify that you see a "< Welcome" button at the top of the walkthrough page:


![Image](https://github.com/user-attachments/assets/517db640-d148-43dc-b069-b206c6ae6cf2)

**Comment by Tyriar** [comment]
@bhavyaus the consistency is good, but it's still a little weird seeing Welcome twice:

![Image](https://github.com/user-attachments/assets/20c6805b-840f-435c-959f-642f9433ce93)

That reads to me: You're on the welcome page, but you can go back to the welcome page?

**Comment by bhavyaus** [comment]
You're on the walkthrough page and can go back to the `Welcome` Page on first launch. The confusion is because the walkthrough page title reads "Welcome" for all walkthroughs. Fixing https://github.com/microsoft/vscode/issues/169163 should help with this.

**Comment by bhavyaus** [comment]
Closing this. This should go away with https://github.com/microsoft/vscode/issues/169163
