### ISSUE TITLE
`writeTextAreaState(reason: selection changed)` keeps printing over and over to window log

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#229161]
Do we have some interval set that is triggering this? I wasn't touching the file/selection at all:

![Image](https://github.com/user-attachments/assets/d62defe5-4906-454d-ae4f-dfa47da9ee80)

**Comment by meganrogge** [comment]
this comes from a change 7 years ago https://github.com/microsoft/vscode/commit/eaf18ad3377e4113c741b92ccb2544ad675681fe#diff-37a993adfbbcde6d9fd8e61da6637960bcce354b618fb1e3dcf6bf6ded66e435R379

**Comment by meganrogge** [comment]
I am seeing `reason:render` vs `selection changed` when I focus an editor and set log level to `trace` in `window`.

Wonder if your blinking cursor is causing this to happen
https://github.com/microsoft/vscode/blob/0f6736f1be597128a1e55f2cbd6555d74f14c58d/src/vs/editor/browser/controller/textAreaHandler.ts#L309

**Comment by meganrogge** [comment]
any other settings @Tyriar ?

**Comment by meganrogge** [comment]
Reproduces when you focus the output channel (and also reproduces if you then focus the editor).

**Comment by meganrogge** [comment]
From @Tyriar :

- macOS (originally happened on Windows)
- Open output panel
- Lock the window channel
- Click the output editor
- Click the main editor

**Comment by aiday-mar** [comment]
I tried the steps, I'm currently not able to reproduce either 🤔

**Comment by Tyriar** [comment]
I confirmed that it is indeed related to the output channel being locked. Clicking not at the bottom of the output channel stops the loop, clicking at the very bottom again starts it up again.

![Image](https://github.com/user-attachments/assets/9702f754-7141-414b-baa8-43b57ba5b8f9)

**Comment by aiday-mar** [comment]
I was able to reproduce this issue by setting the log level to trace, opening the output channel and placing the cursor at the bottom. The reason this happens is because trace logs are inserted in the output channel. When this happens the cursor state changes in the output channel. This makes the cursorStateChange event fire, and this makes the text be written again. The result is then very circular.

The fix is the following: https://github.com/microsoft/vscode/pull/231392
