### ISSUE TITLE
Panel doesn't allign well when side bar is pinned to the right

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#2291]
See screen shot. The header of the editor aligns well with the header of the side bar however the header of the panel somehow 'stops' at the side bar without a nice visual ending.
![capture](https://cloud.githubusercontent.com/assets/1931590/12578529/b502a27e-c421-11e5-8874-b47aa23b976c.png)

**Comment by isidorn** [comment]
The visual ending in the editor is actually the scroll bar. Notice the small space between the panel and the scroll bar in the editor, there the editor also does not have a nice ending - same as panel

Are you suggesting we should draw the border at the end of the panel header?

**Comment by isidorn** [comment]
Forwarding to Bard so he gets the feedback and thinks about the solution

**Comment by bgashler1** [comment]
![screen shot 2016-02-03 at 7 49 22 am](https://cloud.githubusercontent.com/assets/11839736/12787556/bccf0234-ca4a-11e5-86ff-b4619d6270b7.png)
The only problem with doing that is we need to be ready to accommodate horizontal scrolling as well (which is why there is the gap).  I would suggest, however, that we draw it down anyway and make horizontal scrolling go as far as the vertical scroll bar.

Alternatively, we could do this (add stroke to the horizontal scrollbar area (not my favorite).
![screen-shot-2016-02-03-at-7 49 22-am](https://cloud.githubusercontent.com/assets/11839736/12787916/3ace94c8-ca4c-11e5-9291-68c4ff1e7ccd.gif)

**Comment by bgashler1** [comment]
Another way we can make it happen is by having the vertical scrollbar take up all the space except on a hover event which makes room for a horizontal scroll bar.  I like this approach as well as the first approach I suggested, but what do you guys think?
![horizontalscrollbars](https://cloud.githubusercontent.com/assets/11839736/12938595/bee9da42-cf6a-11e5-9cbc-116194e4244c.gif)

**Comment by isidorn** [comment]
@bgashler1 let's discuss this in our ux sync today
