### ISSUE TITLE
SSH fails only in the integrated terminal

### ISSUE THREAD

**Issue by 3f6a** [microsoft/vscode#229240]
I ran into a strange situation where:

```
ssh remote_host
```

fails, when run on the VS code integrated terminal, but the same command succeeds on my system (external) terminal. I tried to bisect what was going on with limited knowledge, and I'll attempt to give more details here.

This issue only happens on a wired connection at work, where the network has some corporate restrictions. If I connect on the WiFi, in the same network, the issue does not happen. I then figured that there must be something different in the way network connections (specifically ethernet) are handled within VS code and its integrated terminal, vs. the external terminal. However, I tried running things like `env` and `ifconfig`, but I see pretty much identical outputs (up to minor vscode specific differences that I don't think are relevant).

Lastly, my personal machine is on macOS, latest version. The remote is a Linux box within the corporate network.

If anyone with more knowledge has any specific questions, or any illuminating suggestions of what differs in terms of networking between the VS code integrated terminal and the external terminal, I'd be happy to provide more details.

**Comment by albertosantini** [comment]
A few ideas.

- Check if the `ssh` command executed is the same, intending stock MacOS or something else (`which ssh`).
- Debug `ssh` with `-v` or `-vv` or `-vvv` to see the diffs between ssh VSCode terminal and external terminal

Just my two cents.

**Comment by albertosantini** [comment]
It cannot be the same debug session: this is very weird.

It would mean ssh correctly works in both context, vscode terminal and external terminal, doesn't it?

**Comment by albertosantini** [comment]
`ssh -vvvv ...` Last try and catch the diffs. :)

**Comment by albertosantini** [comment]
The terminal itself cannot be involved.

I have been following the idea, for some reason, the enviroment or the setup is different.

- Check the env vars `$ env`
- Check the network `ifconfig`
I know you did it. Check again.

Another idea is `traceroute`, the network path in wifi and ethernet maybe are different or the company set different "filters".

I recap the tests:

- System terminal / wifi : OK
- System terminal / ethernet: OK
- VSCode terminal / wifi: OK
- VSCode terminal / ethernet: KO

Did I understand correctly?

**Comment by GreenRockD** [comment]
> I ran into a strange situation where:
> 
> ```
> ssh remote_host
> ```
> 
> fails, when run on the VS code integrated terminal, but the same command succeeds on my system (external) terminal. I tried to bisect what was going on with limited knowledge, and I'll attempt to give more details here.
> 
> This issue only happens on a wired connection at work, where the network has some corporate restrictions. If I connect on the WiFi, in the same network, the issue does not happen. I then figured that there must be something different in the way network connections (specifically ethernet) are handled within VS code and its integrated terminal, vs. the external terminal. However, I tried running things like `env` and `ifconfig`, but I see pretty much identical outputs (up to minor vscode specific differences that I don't think are relevant).
> 
> Lastly, my personal machine is on macOS, latest version. The remote is a Linux box within the corporate network.
> 
> If anyone with more knowledge has any specific questions, or any illuminating suggestions of what differs in terms of networking between the VS code integrated terminal and the external terminal, I'd be happy to provide more details.

**Comment by GreenRockD** [comment]
ssh remote_host

**Comment by albertosantini** [comment]
@3f6a When you switch from "wifi ok" to "wifi ko" do you restart VSCode?

**Comment by teddykoker** [comment]
I was having the same issue after updating to MacOS Sequoia. I was unable to use ssh from vscode to any server the same network that I was currently on (with no helpful message other than `undefined error 0`), but had no issue if I was on a different network. It turns out MacOS Sequoia added a "Local Network" security setting which limits communication between devices on your local network. Switching on vscode in Settings > Privacy > Local Network fixed this issue for me, and explains why ssh worked in the default terminal application, and in vscode while on non-local network. Hope this helps!

**Comment by karthiknadig** [comment]
Closing this as this might have been a permissions issue.

**Comment by karthiknadig** [comment]
@joshspicer Do you think the above request is possible?

**Comment by joshspicer** [comment]
I've been testing a change for next iteration (in the Remote - SSH extension) which will provide this kind of suggestion if 

1. Local machine is macOS
2. We see one of these strings in the ssh error
3. The ip address is one of the [rfc1918](https://datatracker.ietf.org/doc/html/rfc1918#section-3) private IPs

![Image](https://github.com/user-attachments/assets/63f28f60-d82a-4186-b024-7622f249bfa2)

I think it would be helpful for the terminal to do some kind of similar checks.  It's easy to miss the local network prompt, especially since it can pop up way before you'd do something you actually want local network access for.
