### ISSUE TITLE
the intellisense cannot work

### ISSUE THREAD

**Issue by apawn** [Microsoft/vscode#22935]
when i updated vscode to latest version ,the basic intellisense feature has crashed .
i dont know why
all the plugin i installed is listed, if there is any question with the plugin or the files in my project ?

please help me . thank you  very much 

- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-html-css|ecmel|0.0.33|
|vue|liuji-jim|0.1.5|
|vscode-fileheader|mikey|0.0.2|
|vetur|octref|0.5.5|
|vscode-icons|robertohuertasm|7.4.0|
|vue|seanwash|0.4.2|;

---

Steps to Reproduce:

1.
2.

**Comment by apawn** [comment]
![intellisense](https://cloud.githubusercontent.com/assets/13815338/24132360/fa7378ac-0e2f-11e7-80fd-c68d7b8715e4.gif)

which is that .

**Comment by apawn** [comment]
![4jn c437 hg2tbuxhfl n](https://cloud.githubusercontent.com/assets/13815338/24132446/9dc75a82-0e30-11e7-8515-2d1d9870671a.png)
![wvh c 00v w5 za q6ek](https://cloud.githubusercontent.com/assets/13815338/24132454/abf45470-0e30-11e7-8124-39fce5151267.png)

all i thinked would affected the  intellisense  has listed , may be i have made  a mistake

**Comment by mjbvz** [comment]
First, can you please try disabling all extensions by starting code with the `--disable-extensions` command line flag to make one of those is not the root cause.

If you still see this problem after disabling extensions, please try collecting logs from the TypeScript server which powers our javascript and typescript intellisense:

1. Add `"typescript.tsserver.trace": "verbose"` to you settings
2. Restart VSCode and reproduce the issue  
3. Open the output panel and share the `TypeScript` output section

Thanks

**Comment by bastienJS** [comment]
I... did what you asked for and my output panel is empty. For some days the intellisense in my angular .ts files is gone using v1.11.

**Comment by apawn** [comment]
thanks for the helping,when i have deleted the tsd-debug.log file , the intellisense  has recovered .
the intellisense   is so strong , and it helps me  a lot .

**Comment by mjbvz** [comment]
@bastienJS Can you please open a new issue if you are seeing problems. These sort of problems usually have different root causes so separate issues makes tracking the investigation much easier.

@apawn So it sounds like the issue is solved now? I'm not sure why deleting the `tsd-debug.log` file would make a difference though. If you run into this again, please try collecting some logs and we can reopen the investigation

**Comment by apawn** [comment]
i  am listing all the steps i have tried 
1.npm install  tsd --save-dev
2.tsd query node --action install --save
3.tsd query express--action install --save



4.so i use another way which is 

npm install @types/express --save -dev 
then add the 'expresss' to  tsconfig.json which was like this

{
   "compilerOptions": {
       "types" : ["node", "lodash", "express"]
   }
}

not worked too.

5.update the vscode . when this had completed , i found the basic intellisense has disappeared.
and after this .i found the that couldn't work 

then i asked an issues ,when waiting for the reply , i try to deleted tsd-debog.log file and npm-debug.log file,and tsconfig.json file ,  i found the intelliense has recovered . which was a big suprise .

but this morning, when i  added    tsd-debog.log file and npm-debug.log file,and tsconfig.json file  to the project , the intelliense was working well . which means the i cann't reappear the problem . sorry for that .

thank you very much .
