### ISSUE TITLE
Add button to log into a new account from the account menu if already logged into an account

### ISSUE THREAD

**Issue by aiday-mar** [microsoft/vscode#229496]
Testing #229420

- So I am logged into my main account `aiday-mar` into VS Code.
- I clicked on the account icon and opened the account menu
- I can manage the trusted extensions for my main account from there
- Maybe it would make sense to have a new entry in that menu to add another account since now this is supported. 

![Screenshot 2024-09-24 at 10 25 21](https://github.com/user-attachments/assets/74fd2ea4-0c39-477d-b891-fb19c35e785e)

**Comment by TylerLeonhardt** [comment]
This a tough one because "adding an account" doesn't matter to VS Code itself. It only really matters to extensions.

Additionally, It's very easy to support this for Microsoft, but for GitHub it's a bit challenging because scopes matter to GitHub. You have to sign in to your GitHub account for each set of scopes. For example:
* GitHub Pull Requests asks for scopes: `user:email repo workflow read:user`
* GitHub Copilot asks for scopes: `user:email`

So for an "add account" experience, how do we do that?

The the best answer I could come up with is to have an add account on here:
![image](https://github.com/user-attachments/assets/bcd3694b-bd7e-49a2-b20d-9c712df60203)

And keep track of the requests that each extension asks for.

Then when they add an account we use the last set of scopes that that extension has requested when making the request.
