### ISSUE TITLE
With `editor.experimentalEditContextEnabled`, the cursor doesn't move during composition

### ISSUE THREAD

**Issue by tamuratak** [microsoft/vscode#229451]
I tried the OSS version from the repository. With `editor.experimentalEditContextEnabled`, the cursor doesn't move during composition. For Japanese users, it is a common use case to move the cursor to correct inputs during composition.

Version: 1.94.0
Commit: 38adfa09563e871d205c2453bb29e7bc48a95a80
Date: Unknown
Electron: 30.5.1
ElectronBuildId: undefined
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 22.6.0
Steps to Reproduce:

1. Set `"editor.experimentalEditContextEnabled": true`
2. Set `"editor.wordWrap": "on"`
4. Enable Google IME for Japanese.
5. Type `sennsei`
6. Type ←
7. The cursor doesn't move.

---

`"editor.experimentalEditContextEnabled": true`

https://github.com/user-attachments/assets/a372b561-6f96-4369-b061-2dd209bff21f

---

`"editor.experimentalEditContextEnabled": false`

https://github.com/user-attachments/assets/21333caf-5c9f-481c-888b-04a6b093f73b

**Comment by aiday-mar** [comment]
Hi thank you for filing this issue. I was able to reproduce this behavior. The reason this used to work before is because we used to show a `textarea` HTML element with the composition text inside of it. When you would type the Left and Right keys inside of it, the cursor would move left and right inside of this element even if we would call `stopPropagation` on the emitted keydown event from the `textarea` element during composition. This `textarea` element is actually the reason why the editor would flicker on composition previously. 

With the new implementation, we have removed this visible `textarea` element so there is no more flickering. Now we still call the method `stopPropagation` on the keydown event during composition. As a result the Left and Right arrow key events are no longer propagated further and the Left and Right keys do not make the cursor move. 

We could fix your specific use case by not calling `stopPropagation` on the event during composition, but this would break users of other IMEs. Consider for example Simplified Pinyin IME. The IME appears as a horizontal bar as follows:

<img width="410" alt="Screenshot 2024-09-25 at 18 07 16" src="https://github.com/user-attachments/assets/0874a6c6-304d-4df2-9022-9944bf43a702">

Because it is horizontal you would use the Left and Right arrow keys to cycle through the IME suggestions. Now if we don't stop the Left and Right event propagation, the cursor would move left each time you cycle left in the IME and move right each time you cycle right through the IME. Therefore it seems to me generally we need to stop the event propagation and keep this behavior. 

Making the hidden div we use to set the EditContext on content-editable does not fix the the problem either because it does not contain any text unless accessibility mode is turned on.

From this I would argue that the behavior you were seeing previously is more a result of a bug within the previous implementation that allowed the user to use the Left and Right arrow keys to move through the composition. We could consider now making this behavior work in the current implementation, but I am not sure if this is a desirable behavior.

**Comment by tamuratak** [comment]
Version: 1.94.0-insider
Commit: be2747e47e127ec674148b78dd9556c6317d18bd
Date: 2024-09-25T05:04:31.141Z
Electron: 30.5.1
ElectronBuildId: 10262041
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 22.6.0


https://github.com/user-attachments/assets/e3e8f2b6-7449-4f49-b7b2-64285b698037

On macOS, even with Pinyin, the left and right arrow keys seem work when 
`"editor.experimentalEditContextEnabled": false`. It is natural to allow users to correct inputs during composition. So, I guess that, on typical IME implementations for any language, the left and right arrow keys would work somehow.

It would be possible to create a simplified cursor DOM on the `nativeEditContext.ts` side during composition, not the rich cursor of VS Code.

**Comment by aiday-mar** [comment]
I am not sure if we should make the caret move through the composition with the left and right arrow keys. Consider google sheets, when you type a composition in Japanese, and then press left and right this modifies what sub-composition part we are changing but does not change the caret position:

https://github.com/user-attachments/assets/1a638e57-da5d-47c4-bb03-dd58ef976fe9

Similarly on Microsoft word, when you type a composition, and press left and right, this does not change the caret position, but it changes what part of the composition is being edited. 

https://github.com/user-attachments/assets/ce7f4d72-c2cf-420a-9ef3-798ecd86fd0d

We already make explicit what part of the composition we are specifically editing, so I am not sure we need to make more changes by modifying the caret position too.

**Comment by tamuratak** [comment]
You have to set `Live Conversion` off at the setting of macOS Japanese IME. Then, after typing `sennsei`, you can use the left and the right arrows to move the cursor:

![jaime](https://github.com/user-attachments/assets/dce58f25-7714-4336-8bee-87098d3b7f9c)

When `Live Conversion` is on, 

1. Type `sennsei`
2. Type `ESC`

then you can use the left and the right arrows to move the cursor.

---
Each character in "せんせい" represents a syllable, by editing the characters you can turn it into another word with a different pronunciation. Then, you convert it to appropriate Chinese characters with IME.

**Comment by aiday-mar** [comment]
Hi, I see thank you for the clarification, I see better now. Then this behavior is a bug, and we will work on a fix.

**Comment by aiday-mar** [comment]
Hi thanks for filing this issue, after some more investigation, I discovered a way to fix this issue. I made a PR here: https://github.com/microsoft/vscode/pull/232955
