### ISSUE TITLE
Should invalid attachments (folders, deleted files, ...) be draggable into chat?

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#229547]
Testing #229409

1. Delete a file
2. Go to the SCM view
3. Drag the file into chat
4. Ask a question

I'm not sure if this should be draggable. The chat has no decoration that this is a deleted file and the response completely fails because the file is deleted.

**Comment by benibenj** [comment]
This is a bit of a corner case which is hard to catch. There are also some other corner cases where it is possible to attach a folder. I might need to do a file system call to check if the resource added is actually a file. I wanted to avoid this, but don't think I can prevent this and some similar cases otherwise.

**Comment by benibenj** [comment]
Fixed as we now do a stat call
