### ISSUE TITLE
Enum colorization is off

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#229564]
Testing #229392

Default:
![Image](https://github.com/user-attachments/assets/7a837a96-0a1b-4711-a102-93b5b115911f)

Tree Sitter:
![Image](https://github.com/user-attachments/assets/856602ca-f789-4c6b-8875-e1bba9afeabc)

Not sure if this falls under the known issue

**Comment by alexr00** [comment]
This looks like a case where the new highlighting is technically an improvement over the old, but it's noticeably different and so may not be desirable. The new color is used because `CHAT_MODEL` and `EMBEDDING_MODEL` are recognized as constants. @lramos15, what do you think of the new/different color?

**Comment by alexr00** [comment]
Alright, let's keep the new color.
