### ISSUE TITLE
Feedback New welcome page

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#2296]
Testing #2251 on OS X

Feedback:
* We need to ensure that the welcome page loads fast. The first time I've tried it took > 10s to load.
* I use Safari in Full screen mode, when the welcome page showed up in the browser it switches to Safari in full screen and I got disoriented. The welcome page should have some hint that I've installed VS Code and can now go back to it.
  * Is there a way hide the welcome page from the welcome page so that I can easily get back to VS Code?

FYI @SofianHn @bgashler1

**Comment by SofianHn** [comment]
@egamma is the 10s loading time consistent? this sounds pretty bad, the welcome page now resolves to our docs home page and nothing in the website should take that long. did you try multiple times? 

@bgashler1 is working on a design of the welcome page and it will definitely include details that is relevant for someone who just installed the product. Once that is ready, we will update the FWD link. 

> Is there a way hide the welcome page from the welcome page so that I can easily get back to VS Code?

not AFAIK, javascript can't close a window that it does not open. Even if we do that there is no guarantee that safari will exit the fullscreen mode. I get your point about the distraction tho, lets see if we get any complains.

**Comment by mousetraps** [comment]
Re: page load times - do we really want the first-run experience to be so tightly dependent on internet connection quality or network configuration?

Re: context-switching - full-screen or not, popping up a whole new window without explicit action by the user is an altogether jarring experience because it makes users feel [less in control](http://www.uxbooth.com/articles/the-perception-of-control/). It's fine if there's a link that a user clicks to trigger the action, though. Have we considered providing some basic UI within VSCode, and just populating it with a feed? This would result in a smoother first-run experience, instant load time of some predefined set of content, while keeping the benefit of being able to update it more frequently.

**Comment by SofianHn** [comment]
It was a long and difficult conversation that made us go with this design, we are aware of the downsides of it but hoping that the upside is bigger. Being on the website will allow us to provide tailored getting started content, as well as running experiments and improving our measurement. We will be listening for feedback, and again if this turns to be an issue we can always pull it out.

**Comment by mousetraps** [comment]
Gotcha, makes sense! :+1: I agree - there's certainly plenty of benefit for very little engineering cost, and it'll also help us quickly experiment with and iterate on the content, and ultimately provide the best on-boarding experience. 

In the meantime, we should at least consider checking that the the user is connected to the internet before attempting to load the page. see #2400

**Comment by SofianHn** [comment]
cool. Closing this for now.
