### ISSUE TITLE
Can't trigger intellisense in launch.json twice

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#22966]
- Open launch.json
- Trigger intellisense
- Type a few characters, `node`
- Press escape
- Trigger intellisense again

The window doesn't appear when there are already characters there, I think it would be good if it did.

**Comment by isidorn** [comment]
Not sure what exactly do you mean, maybe you provide a gif since I was unable to repro strange behavior (I atteched my gif).
While trying this out i found an unrelated https://github.com/Microsoft/vscode/issues/23005

![rob](https://cloud.githubusercontent.com/assets/1926584/24192239/9002db74-0eee-11e7-9088-48cc3901550f.gif)

**Comment by roblourens** [comment]
Sorry, I meant for launch config snippets, not inside the configuration.

**Comment by isidorn** [comment]
Still can not repro

![rob](https://cloud.githubusercontent.com/assets/1926584/24206245/eec64914-0f1d-11e7-8bcd-89a4005bcbcb.gif)

**Comment by roblourens** [comment]
Weird, that's exactly what I'm trying.

**Comment by aeschli** [comment]
Closing
