### ISSUE TITLE
I found Linux and windows under the shortcut keys are not the same, why?

### ISSUE THREAD

**Issue by crper** [Microsoft/vscode#22999]
- VSCode Version: 1.10.2
- OS Version: Deepin Linux 15.4

I found Linux and windows under the shortcut keys are not the same, why?

The keyboard is not in addition to some countries, the basic are the international unity of what? The Such as ctrl, shift, alt and so on. The The

Why Linux and windows shortcut keys but also engage in differentiated.

Now I will take the time to become familiar with the new set.

**Comment by rebornix** [comment]
Our Linux champion @Tyriar may help answer this.

**Comment by Tyriar** [comment]
In general they are the same, the reasons for differentiation are typically because of OS-specific things on certain keys. You would need to give specific examples for a more specific answer. However, you can configure your keybindings however you want to get your environments consistent https://code.visualstudio.com/docs/getstarted/keybindings
