### ISSUE TITLE
Switching project folder in Zen mode (with ctrl+r shortcut) results with unresponsive window

### ISSUE THREAD

**Issue by boris-ilijic** [Microsoft/vscode#23004]
- VSCode Version: 1.10.2
- OS Version: Windows 10

Steps to Reproduce:

1. Open project folder and enter in Zen mode
2. Switch to another project folder using open recent shortcut (ctrl+r)
3. VS Code opens another project folder but in partially unresponsive window: window menu bar is not shown, it is not possible to close or resize the window, it is not possible to move window to another monitor...

**Comment by isidorn** [comment]
@boris-ilijic you are in full screen mode, hit F11 to exit full screen and you should be good

@bpasero it is slightly confusing that the lifespan of zen mode and full screen are not the same. What happens here, zen mode triggers enters full screen, user opens new window -> zen mode is not preserved across windows while full screen is. So he is only left with the full screen state. In order to fix we can either:
* change zen mode to also be per vscode session (though I changed this previously and found revolt by users)
* change full screen to be per window not per vscode
* when opening a new window check if zen mode triggered full screen and if yes get out of full screen if you are not in zen mode

**Comment by boris-ilijic** [comment]
F11 helped. Thanks

**Comment by bpasero** [comment]
I think at least on macOS a new window opened from a fullscreen window is always also fullscreen, not sure if we have control there.

**Comment by isidorn** [comment]
Let's keep it like it  is for now and I can look into revisiting if more users find this confusing.
Since option 3 I can not easily figure out who triggered full screen - or even if the window is in full screen for that matter (not revealed in the `WindowService` api)
