### ISSUE TITLE
Extension hover shows on mousedown

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#230084]
1. Install `rust-lang.rust-analyzer`
2. Open a rust project

Hold mousedown on the rust analyzer status bar contribution. 🐛 The hover appears and disappears when the mouse is released.

**Comment by benibenj** [comment]
@meganrogge it seems like you added [these listeners](https://github.com/microsoft/vscode/blob/ba6feb59bc05bc1ea8cbab8e19aeeb07db134f15/src/vs/workbench/browser/parts/statusbar/statusbarItem.ts#L127-L136) to prevent flickering from happening in the status bar. Maybe this is not required anymore? It seems like this is causing the flickering to happen currently.

cc @bpasero as he added the if condition

**Comment by meganrogge** [comment]
I added those listeners so that the tooltip is shown and hidden when keyboard focus moves into / out of status bar items. 

I just tested and those listeners are no longer needed because of work you've done to support showing the tooltip for items around the workbench when they're focused with the keyboard @benibenj.
