### ISSUE TITLE
SCM - Graph view refreshes while switching between editor tabs of the same repository

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#230264]
Steps to Reproduce:

1.  Open a folder/workspace that contains a git repository
2. Open multiple files from the workspace
3. Open the Source Control Graph view
4. Scroll the graph
5. Switch between editor tabs

Expected: Graph should stay 
Actual: Graph is refreshed

**Comment by gjsjohnmurray** [comment]
/verified fixed in latest Insiders

Version: 1.94.0-insider
Commit: d78a74bcdfad14d5d3b1b782f87255d802b57511
Date: 2024-10-02T13:10:18.718Z
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Code-Insiders/1.94.0-insider Chrome/124.0.6367.243 Electron/30.5.1 Safari/537.36
