### ISSUE TITLE
VS code Install issue. "setup was unable to automatically close all applications..." 

### ISSUE THREAD

**Issue by srccloud** [microsoft/vscode#230221]
Some help would be amazing.
1. 
Having issues installing. stuck on current screen. i cant seem to find anything about this online. I have tried everything to find out how/what is affecting this install, im in desperate need of help, as i need to use this to progress through my studies.

<img width="443" alt="error" src="https://github.com/user-attachments/assets/3cc2b709-9bf8-4a6d-8f66-b6f3c255ab24">
<img width="443" alt="error1" src="https://github.com/user-attachments/assets/edc70d8e-e5ee-48ad-980e-d430291c7330">

2.

**Comment by rzhao271** [comment]
Hi @srccloud, apologies for getting to your issue late.
Restarting the device might help in this case if pressing the "Try again" button didn't work. Another strategy would be to manually install a later version of VS Code from the VS Code website; your extensions and settings will still remain intact.
Let me know if you have resolved the issue, assuming the issue is still relevant.
