### ISSUE TITLE
vscode not loading file change or new file in time

### ISSUE THREAD

**Issue by caiqi** [Microsoft/vscode#23029]
when opening a folder in vscode, the changed file are not updated in time. And when creating new file outside of vscode, the new file do not show in explorer and can't be searched by CTRL+P. This happens more when the folder is in a remote server and contains hundreds of files. Is there anyway to make vscode load in time? Thanks.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by bpasero** [comment]
@caiqi do you have some more specific repro steps?

**Comment by caiqi** [comment]
I have a directory on a remote server where I save models and write logs into it. Sometimes, the new created models are not shown in vscode explorer and the logs are old. However, when I click another file and then click the old logs , it gets updated.

**Comment by bpasero** [comment]
@caiqi 
VS Code is using different file watching strategies depending on your OS and your setup. 

**First thing to check:**
* [ ] I verified that the issue still reproduces in our insiders version (https://code.visualstudio.com/insiders/)
* [ ] I verified that this issue is happening outside of a `node_modules` folder. Our file watcher ignores this folder!

**To find out more about this issue, please first answer this:**
* [ ] What OS are you on
* [ ] Does this happen from an empty workspace, a single-folder workspace or a multi-root workspace?
* [ ] Do you have `files.useExperimentalFileWatcher: true` configured in settings?
* [ ] What is your configured `files.watcherExclude` setting?

**Then please answer the following depending on your setup:**
* [ ] It reproduces with any folder or workspace you open
* [ ] The files/folders you open are on your local disk and not on a network share nor a UNC drive
* [ ] The files/folders you open are not behind a symbolic link
* [ ] The folder(s) opened use the exact same casing as they are on disk
* [ ] It reproduces when I make a change to the file from another VS Code window (either from the editor or the file explorer)

**Then please attach the output of our development console**
* run `code --verbose` from the command line
* perform the action that causes you to not see the file change in VS Code
* attach the output from the console (`Help` > `Toggle Developer Tools` > `Console`)

Thanks for taking the time to fill out this questionnaire.
