### ISSUE TITLE
Deeper Json Hierarchy

### ISSUE THREAD

**Issue by blewis2-blue** [microsoft/vscode#230314]
Here's a toy example of a json file with deep nesting

```json
{
  "1": {
    "2": {
      "3": {
        "4": {
          "5": {
            "6": {
              "7": {
                "8": {
                  "9": {
                    "10": {




                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
```

If I scroll down to hide the top several lines, I see the hierarchy in the breadcrumbs only up to "4".

![image](https://github.com/user-attachments/assets/4e736ca3-a516-4912-b780-1aca8995d18b)

Please show more, or possibly even configurable. Thanks!

**Comment by gjsjohnmurray** [comment]
You can increase the value of the `editor.stickyScroll.maxLineCount` setting.

**Comment by blewis2-blue** [comment]
> You can increase the value of the `editor.stickyScroll.maxLineCount` setting.

This worked for the example above. Interestingly, it doesn't work for my real file, and now I see that it's a bit glitchy. I pasted the large, test json file from https://github.com/json-iterator/test-data/blob/master/large-file.json and it's more or less nonfunctional. Truncating that file to different lengths, 10000 lines seems fine, 100000 not so much.

Is it OK to move the goal posts on this feature request to supporting stickyScroll for large JSON files?

**Comment by aiday-mar** [comment]
Hi @blewis2-blue thank you for posting this issue. For very large files, we have disabled sticky scroll because it is computationally expensive. When you open such a file, you should see a notification which mentions that certain features like tokenization and sticky scroll are disabled, to keep VS Code running smoothly. It could also be you are seeing glitches, because sticky scroll is computationally expensive. I will close this feature in favor of https://github.com/microsoft/vscode/issues/191973
