### ISSUE TITLE
Debugging Node.js application

### ISSUE THREAD

**Issue by svipben** [Microsoft/vscode#23050]
- VSCode Version: 1.10.2
- OS Version: Linux Ubuntu 16.04
- Node.js: 7.7.3

If you're using latest Node.js version there's no `legacy` protocol, you need to use `inspector`. I suggest to auto include `"protocol": "auto"` to `launch.json` config. Because right now to debug Node.js app, I need to create `launch.json` just to include `"protocol": "auto"`.

**Comment by weinand** [comment]
@svipben please correct me if I'm wrong, but in my understanding all node 7.x version support both the legacy and the inspector protocol. I just verified this with node v7.7.4.

But anyway, in the March release we will make `"protocol": "auto"` the default. You can try this already in the Insiders build.

**Comment by svipben** [comment]
@weinand With this config:
```
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Launch Program",
      "program": "${file}"
    },
    {
      "type": "node",
      "request": "attach",
      "name": "Attach to Process",
      "address": "localhost",
      "port": 5858
    }
  ]
```

I get this: `(node:16528) DeprecationWarning: node --debug is deprecated. Please use node --inspect instead.`

Added:
```
      "args": [
        "--inspect=5858"
      ]
```

But issue still the same.

With this config:
```
    {
      "type": "node",
      "request": "attach",
      "name": "Attach to Process",
      "address": "localhost",
      "port": 5858
    }
```
I can't even attach to running Node.js server, BUT if I add `"protocol": "inspector"` everything works fine.

My Node.js version is 7.7.3

**Comment by weinand** [comment]
@svipben 
your problem 1: this is a deprecation **warning**. It does not say that the old protocol is not supported. So this should work just fine (and you can ignore the warning).

But if you want to get rid of that warning, you can switch to the inspector protocol by adding a `"protocol": "inspector"` to your launch config. This will use the correct '--inspector' option when launching node and it will use the correct VS Code 'inspector' debugger.

problem 2: by default VS Code node debugger assumes the 'legacy' protocol in the February release. If you have launched node outside of VS Code with the '--inspector' option, node-debug cannot connect because it assumes the 'legacy' protocol. To fix this add  the `"protocol": "inspector"` to your launch config.

I suggest to read this: https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_supported-nodelike-runtimes
