### ISSUE TITLE
Terminal looses split icon

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#230623]
Sometimes I see no icon in the terminal toolbar to split it:

![Image](https://github.com/user-attachments/assets/8a93bd7f-7d6b-46e6-ad89-dcd84d7155e6)

![Image](https://github.com/user-attachments/assets/a39bc9c8-b0ce-43e2-b0bc-c6a7597d607c)

**Comment by Tyriar** [comment]
The split action only shows up in the panel when there's a single terminal, otherwise it shows up in the tabs on hover:

![Image](https://github.com/user-attachments/assets/6c2f2519-8afe-4266-a84e-e53f11210b6c)

This is by design, but you can get what I think you're after with `"terminal.integrated.tabs.showActions": "always"`
