### ISSUE TITLE
Word highlighting leaks text models

### ISSUE THREAD

**Issue by flixyudh** [microsoft/vscode#230635]
Does this issue occur when all extensions are disabled?: Yes/No

- [x] Yes

- VS Code Version: 1.94.0
- OS Version: MacOS Sonoma (14.4.1)

Steps to Reproduce:

1. Open VSCode
2. create new file (CMD+N)
3. input random text
4. close file (CMD+A -> delete -> CMD+W)
5. create new file again (CMD+N)

Attach Video:

https://github.com/user-attachments/assets/d05a1225-2e59-43ae-af41-c46623cfb8d2

**Comment by bpasero** [comment]
I can reproduce.

@Yoyokrazy can you please take a look, this is a regression from https://github.com/microsoft/vscode/commit/6092f245833f7c7431825878819766716684a5b0

Specifically an editor no longer seems to get disposed when closing it when it is dirty. Steps:
* start a window on a folder without editors opened
* open an editor, type in it, close it
* do not save
* run the "Log Working Copies" action

=> 🐛 the editor that was just closed is still in there

The fact that the number for the untitled number increases is a variant of this issue: we only re-use a previously used untitled editor number if that previous editor model was disposed.

I think this meets the bar for being a candidate.

**Comment by bpasero** [comment]
@Yoyokrazy @rebornix this looks super fishy:

https://github.com/microsoft/vscode/blob/dc265add0b37d88dcf955ef83c8d483e35af242c/src/vs/editor/contrib/wordHighlighter/browser/wordHighlighter.ts#L702

and

https://github.com/microsoft/vscode/blob/dc265add0b37d88dcf955ef83c8d483e35af242c/src/vs/editor/contrib/wordHighlighter/browser/wordHighlighter.ts#L725

Anytime I make a click into the editor and change the selection, the model gets resolved and never disposed. 

Besides the fact that a model reference must be disposed, I really do not understand why the model has to be resolved like this when it should just be there from the code editor 🤔

**Comment by Yoyokrazy** [comment]
> Besides the fact that a model reference must be disposed, I really do not understand why the model has to be resolved like this when it should just be there from the code editor

This is done specifically to enable the use of multi-model occurrence highlighting in notebooks. The issue in the notebook case for the following situation:
- editor focus in cell A, with highlights requested throughout the entire notebook
- cell A scrolled off the viewport
- cell X scrolled into the viewport, WH is spun up, query is detected, and requests occurrences. 
  - occurrences should be seeded off the cell that was scrolled off the viewport, with a disposed model
  - trigger an occurrence request based off the stored position and URI within the static `WordHighlighter.query` (which requires resolving the disposed model from cell A)
  
The fix for this is quite small, just disposing the stored `IReference` after the occurrence request is resolved and decorations are rendering. I'm surprised that the testing we have in place for occurrence highlighting didn't catch the leaked disposables, I'll make an item to add that check in as a debt item as well.

**Comment by bpasero** [comment]
Yeah would be really good to have a unit test for this 👍

**Comment by Yoyokrazy** [comment]
Verification Steps:

- with occurrence highlighting set to either `singleFile` or `multiFile`
- open any file, make a selection
- close the file
- run **Log Working Copies** from the command palette and ensure that the file is not present in the list
