### ISSUE TITLE
vscode.dev authetication disabled

### ISSUE THREAD

**Issue by kwhandy** [microsoft/vscode#230763]
VS Code Web (vscode.dev) can't access remote tunnel since last week. Error message shows it's related to something in workbench and localstorage that mention `INFO [LocalWebWorker0][resolveAuthority(tunnel,1)]` on web console. I've successfully vscode.dev root path but login interface using github/ mcrosoft seems doesn't work anymore. I wonder if this issue also happened to another users or vscode.dev just end support for older browser version on top of older OS(Win 7)?

Version: 1.94.0
Commit: d78a74bcdfad14d5d3b1b782f87255d802b57511
User Agent: Mozilla/5.0 (Windows NT 6.1; rv:109.0) Gecko/20100101 Firefox/115.0
Embedder: vscode.dev

**Comment by kwhandy** [comment]
if there's no official statement about this issue a week later, i think i will close this issue and moving to another cloud ide and leave mark vscode.dev as **No longer support win 7-compatible browsers**.

**Comment by kwhandy** [comment]
well, this happened only in win 7. i've tried to do gif but it won't render in this win 7 pc. when im using win 10, vscode.dev just works without exception. my best effort to explain is just: the button/ link to sign in to github/ microsoft account doesn't exist anymore, so the account dropdown on the bottom corner, usually has button to sign in but now it's gone

**Comment by kwhandy** [comment]
@TylerLeonhardt like i said on top, it's firefox 115

**Comment by TylerLeonhardt** [comment]
Sorry I missed that when I first read the issue. I see now, this is the last version of Firefox that you could get on Windows 7:

> Version 115.0, first offered to Release channel users on July 4, 2023
In January 2023, Microsoft ended support for Windows 7 and Windows 8. As a consequence, this is the last version of Firefox that users on those operating systems will receive. Users on Windows 7 and Windows 8 will automatically be migrated to the ESR 115 version of Firefox so that they continue to receive important security updates. Visit this Firefox support article for more information.

Unfortunately, since Windows 7 is out of support, I don't think we plan on doing anything about this especially since we do use some newer browser features for security purposes.

Best I can recommend is upgrading to Win 10 or higher.
