### ISSUE TITLE
Chat response: actions are always visible

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#230785]
Each chat response shows actions, which is quite noisy, I would have expected the actions for a response only to become visible when I have focused on a response or hovered over it, similar to the "X" button a chat request:

![Image](https://github.com/user-attachments/assets/3635d69f-2119-4c28-a90c-c571c1469ef8)

**Comment by roblourens** [comment]
We changed this when we moved the toolbar. The problem is that it now takes up space in that position, so if it only appears on hover, it leaves a big empty gap. Also, we removed the border lines between rows, and the toolbar provides a nice visual separation. I wouldn't mind getting rid of the thumbs-up again to slim it down. Also most users won't see the extra 'report issue' button.
