### ISSUE TITLE
 Enable/disable JavaScript validation broken

### ISSUE THREAD

**Issue by githoniel** [Microsoft/vscode#23081]
- VSCode Version: 1.10.2
- OS Version:Win 10 x64

Steps to Reproduce:
in my user Setting 
```
"javascript.validate.enable": false,
```

it make effect in older vscode, but after the newest update , it lost effect 

```
import('../TransName').then({
    //todo
})
```

tell me Expression or comma expected

**Comment by mjbvz** [comment]
I'm unable to reproduce this. I also don't see the error you mention when validation is enabled. I see: `Declaration or statement expected` 

To help us investigate: 

* Do you have any extensions installed? Can you try running code with all extensions disabled using the `--disable-extensions` command line flag to see if one of those may be the root cause
* Share your user and workspace settings
* Share a small sample workspace

Thanks

**Comment by githoniel** [comment]
after -disable-extensions, i found it's my extension's bug
