### ISSUE TITLE
Debugger crashes after ca 10s

### ISSUE THREAD

**Issue by jali** [Microsoft/vscode#23089]
- VSCode Version: 1.10.2
- Nodejs version: 6.9.5
- OS Version: Win7

First of all: Thanks to @weinand for helping and answering similar issues which helped me progress in running the debugger.

Steps to Reproduce:

1. Using electron-forge
2. Debugger setting contains the following setup: (following @weinand [help note](https://github.com/Microsoft/vscode/issues/7583#issuecomment-279535031)s)

`"runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron-forge.cmd",`
`"program": "${workspaceRoot}/src/index.js",`
 `"runtimeArgs": [
          "start" 
      ]
`

ergo no need to set --debug-brk in the runtimeArgs. 

> And that will run something like: node_modules/.bin/electron-forge.cmd --debug-brk=46736 start src\index.js

3- The debugger starts and runs about 10 seconds before crashing with error:

> ## Cannot connect to runtime via 'legacy' protocol; consider using 'inspector' protocol (timeout after 10000 ms)

Checking on vscode documentation page:

> 
Runtime	node.js:
------------------
- 'Legacy Protocol': **< 8.x**	      
- 'Inspector Protocol': **>= 6.3 (Windows: >= 6.9)**

Runtime Electron:
-------------------
- 'Legacy Protocol': **all**	      
- 'Inspector Protocol':      **not yet**

So what's the case now? Electron-forge is not supported or is there something vscode could fix?

_P.S. ran the debugger before successfully from a transpiled folder using electron ._ 

Thanks in advance!

**Comment by weinand** [comment]
@jali are you sure that calling `electron-forge.cmd` with an `--debug-brk=46736`arguments actually works?
When I try to run this from the command line I get this:

![2017-03-23_12-40-54](https://cloud.githubusercontent.com/assets/1898161/24246106/01da1384-0fc6-11e7-84d7-7025ea6fcf68.png)

**Comment by jali** [comment]
I can't set the --debug-brk. When I do so, I get the same error you have above in screenshot.
So the only thing I could do, is set the runtimeArgs to use the command start like this:
`"runtimeArgs": [ "start" ]`


BTW. I thought may be VSCode doesn't debug ES6 and it needs to have a transpiled version of javascript with sourcemaps. So I did this but again the same error
Cannot connect to runtime via 'legacy' protocol; consider using 'inspector' protocol (timeout after 10000 ms)
 as long as I use electron-forge :(

**Comment by weinand** [comment]
The error message just means that nothing in electron listens on debug port 46736 (which prevents node-debug from attaching successfully).

How do you know, that `node_modules/.bin/electron-forge.cmd --debug-brk=46736 start src\index.js` actually starts electron in debug mode?
The fact that node-debug cannot connect to that port is a good indication that there is no such debug port open.

**Comment by jali** [comment]
I think you're right, because the status bar is blue. Usually when in debug mode, then status bar is orange.

That means the app is kicking off but not in debug mode. 
Again: is it something electron-forge need to look at, or vscode is actually also working on fixing such issues?

**Comment by weinand** [comment]
first and foremost this is a documentation problem of electron-forge. Without understanding what is going on behind their scripts, it is difficult to understand how to setup electron-forge for debugging.

For electron (see my launch config from above), it is simple because the 'electron' runtimeExecutable behaves like node, so it accepts the `--debug` or `--debug-brk` options that VS Code will use automatically. This pattern is used for other tools in a similar way, e.g. 'nodemon'.

Some npm-based tools have a 'debug' script in their package.json. This is very helpful because this script can be used directly from a VS Code launch config.

**Comment by weinand** [comment]
@jali the color of the status bar is an indication that a VS Code debug session is running. Since in your case VS Code cannot successfully attach to Electron, no session can be established and the color doesn't turn to orange.
So if the color stays blue, it does not necessarily mean that elector is not in debug mode, it just means that VS Code could not establish a session with electron (for whatever reason).

**Comment by weinand** [comment]
I suggest that you find out how to launch electron-forge in debug mode from the command line. With that information it is simple to "attach" from VS Code.
And in a second step we can then try to launch electron-forge from VS Code and attach to it in one go.
