### ISSUE TITLE
[Feature Request] - Allow for finer grained search ignore options

### ISSUE THREAD

**Issue by mtreca** [microsoft/vscode#230810]
So at the moment, as far as I understand it, global VSCode search can either ignore files and patterns from multiple sources (e.g. project or global `.gitignore`,  or globs passed to `search.exclude`), or return all results from `ripgrep`.

This lacks a bit of flexibility when working in a monorepo or in a repository with a lot of files. For instance, if I mainly work on a sub-repo in a mono repo (e.g. `root/app_1`), I might want to ignore all other apps to have a nicer quick open / global search experience but might want to sometimes do a global search in the whole project.

My issue is that running a global search will slow down to a crawl because `ripgrep` does not ignore anything, including `.git/` or `node_module`-type directories. Would it be possible to make these search settings a bit finer? For instance, adding a key `search.AlwaysExclude` or maybe setting an option to **always** exclude the projects `.ignore`/`.gitignore` file?

Let me know if what I am describing is not super clear!

**Comment by IllusionMH** [comment]
What do you mean by "global search"?
If it's Find in files, Search across files, Search panel (<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>S</kbd> on Windows) then why not use advanced search options (available after click on 3 dots)
https://code.visualstudio.com/docs/editor/codebasics#_advanced-search-options
Just follow tip from doc or add additional include/exclude folders/patterns, toggle default global ignores if needed etc.

**Comment by mtreca** [comment]
I might have phrased things poorly. What I am talking about is within the advanced search options.

Basically, as I understand, you have two options with this panel:

![Image](https://github.com/user-attachments/assets/855b969d-a59b-4b65-aa63-c5a3b8d79368)

1. The cog is pressed, and and ripgrep will use ignore files and `search.exclude` entries.
2. The cog is not pressed, and ripgrep will run on absolutely all files in the repo, ignoring ignore files, gitignore, `search.exclude` AND prevent you from adding any other form of ignores by passing the `--no-ignore` flag to ripgrep (I think).

My issue is that, when working in a monorepo with a large number of repositories, I most of the time want to be in situation 1 by adding a most other sub-projects/repositories to `search.exclude` so that the quick open / search experience is nicer (i.e. no results from other subdirectories) but I sometimes want to be able to search other project / subdirectories as well by unpressing the "Use ignore settings" cog and be in situation 2. This works, but this will override ALL of your ignore settings, including some that you probably still want to keep, such as `node_modules`, `.git/**` etc. This makes search with ripgrep slow down to a crawl on large projects.

What I would propose is some way of differenciating files that you always want to exclude from search results from files that you want to exclude or not depending on this cog setting. This could be done by for instance adding a third `always` option key to `search.exclude`:

```json
    "files.exclude": {
        "**/.git": "always",  // <- This one is always off
        "some_other_dir/": "true", // <- This one is toggled on/off depending on the cog
    }
```

**Comment by andreamah** [comment]
Since we want the syntax for `files.exclude` and `search.exclude` to be the same, I'm not sure whether we'd adopt something like what you'd have above. From what I'm hearing, it's almost like you want to have different 'exclude profiles' that you can apply to the search. 

This being said, you could use different settings profiles when you're in the different scenarios that you're describing. This way, you could just adopt different `search.exclude` settings based on what you want.

![Image](https://github.com/user-attachments/assets/3d0e2dfb-7eb2-4456-89f0-de24cd61356a)

https://code.visualstudio.com/docs/editor/profiles

Unfortunately, I don't think we'd have the capacity to create a UI for a profile regarding search configurations particularly. 

You can also try the `Search Editor`, where you can have different search configurations in different windows (although this makes you browse through a different UI, which is probably not what you'd want).

**Comment by mtreca** [comment]
Thanks for your reply. Indeed I guess this is the best option without a UI or settings change. Will close for now.
