### ISSUE TITLE
Debug hover: Show after delay

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#2309]
I find the current behavior of showing the hover instantly when mouse is over way too hectic, especially that the hover is now so large. I suggest to really show it only after a delay.

**Comment by isidorn** [comment]
Ok now it is much more sexy. I show and hide it with an 1s delay. Let me know how it feels and we can tune this interval

**Comment by bpasero** [comment]
@isidorn works good, I believe the editor hover hides quicker than it shows, maybe you want to do the same for the debug hover.

**Comment by pflannery** [comment]
@isidorn is there a way we can control the hover delay in our settings? I constantly find this gets in the way when I'm trying to work in the editor.

**Comment by isidorn** [comment]
@pflannery currently not. If we get more users requesting this we can introduce a configurable delay via settings

**Comment by pflannery** [comment]
@isidorn actually looking again I might of ended up in the wrong place as its not during debug. 
Instead its regarding hover timing whilst working in the editor.
This issue was the closest I found. Do they both share the same delay?

I find it constantly gets in the way of selecting text and also covers over what I'm trying to read.

![hover-pains](https://cloud.githubusercontent.com/assets/1727302/20353310/47eceeea-ac12-11e6-805d-41249ab3dd30.gif)

**Comment by isidorn** [comment]
No - they do not share the same delay. That one is also not configurable - but please create a new feature request if you wish for this.
