### ISSUE TITLE
[Feature Request] Drawing pad integrated to github?

### ISSUE THREAD

**Issue by jdc-cunningham** [Microsoft/vscode#23109]
This is a wishlist/not a priority just a thought that came to mind today.

A simple drawing pad where you get a canvas (instead of the code editor pane) and you draw with your mouse (simple UI example/flow diagram/etc...) and then you could share it to someone else who also uses Visual Studio Code.

I realize this would come with potential new problems like 'How big is the brush? Colors... etc...' Also probably not a good idea to mix non-coding stuff to an IDE for instance I suppose it could be possible to get real-time "push notifications" in the IDE to let you know "hey someone uploaded a file with you mentioned" which could be distracting.

It would be cool if you could upload this into GitHub from Visual Studio Code like 'Save to GitHub'

Yeah it's just a thought, I imagine the various contributors/people who have to actually develop the feature requests/fix things are already burdened with a lot of work.

I also believe that I can do it myself as well (learning the extension creation process).

Also niche use case.

VS code extensions are written in JavaScript not C# or something like that? If that's the case at least I'm closer to that than something like C#.

**Comment by rmunn** [comment]
While this is a neat idea, I'm not sure it belongs in a *text* editor. You're probably better off using an existing tool like https://draw.io/ (which can already save to GitHub, in addition to several other save options like Google Drive and Dropbox) alongside VS Code, rather than reinventing the wheel. So I'm voting :-1: on this idea, not because I don't like the idea of a drawing pad that can save to GitHub, but because it doesn't belong in VS Code AND it's already been done very well.

**Comment by mjbvz** [comment]
Yes, I agree with @rmunn that this is beyond VS Code's scope. A clever extension could try implementing this, but dedicate tool is a much better fix for this sort of functionality

**Comment by jdc-cunningham** [comment]
@rmunn 

Thanks for that neat tool (draw.io), really cool the multiple saving options.

You brought up some good points. I suppose the primary thing I was bringing up wasn't 'saving to github' but just an integrated visual aid in VS Code but again as you mentioned it's a text editor not a graphics editor.
