### ISSUE TITLE
Broken syntax highlighting in JavaScript template strings with 'Light' or 'Dark' themes

### ISSUE THREAD

**Issue by markshark05** [Microsoft/vscode#23111]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vs-keybindings|ms-vscode|0.1.3|;

---

In JavaScript, when using template strings like this:

    `My name is ${name}`

the variable 'name' is the same color as the rest of the string instead of white. This is only present when using 'Light' and 'Dark' themes and not in 'Light+' and 'Dark+'.
![image](https://cloud.githubusercontent.com/assets/15179595/24265455/4c6f94a0-100c-11e7-94ec-a206139cd8c3.png)

**Comment by mjbvz** [comment]
Thanks for the report. The bug here seems to be that the `${` and `}` were not highlighted in JS. The new colorization for the plain light/dark themes should now look like this:

<img width="250" alt="screen shot 2017-03-23 at 1 39 22 pm" src="https://cloud.githubusercontent.com/assets/12821956/24269364/2e3abb24-0fce-11e7-8a8d-94336a6554c1.png">

**Comment by jrieken** [comment]
@mjbvz please don't the `verification-needed` label for bugs, but the bug-label which also "triggers" verification but after testing new things
