### ISSUE TITLE
Provide a way to control debugger stop focus changes

### ISSUE THREAD

**Issue by daviwil** [Microsoft/vscode#23117]
- VS Code 1.10.2
- Windows 10 Anniversary

In the latest update of the PowerShell extension (0.11.0) we now use an integrated terminal instead of the Debug Console for interactive execution of commands.  PowerShell allows the user to type commands in the console to initiate debugger operations like "stepInto", "stepOut" and "continue".  When the user types such a command and presses "Enter", the focus jumps back up to the editor pane when the debugger stops at the next line or breakpoint.

I would really appreciate a way to tell the debugger client UI to not change the focus automatically so that the user can keep typing commands into the console without having to manually set focus back there.

Thanks!

**Comment by isidorn** [comment]
First I checked does it make sense in general to pass focus to the editor when stepping and I think it does. As a reference I also checked what Chrome debugger is doing and they also always pass focus to the editor.

However I understand your scenario and we could tackle it by either:
* introducing a vscode settings e.g 'debug.autoFocusEditor' - the problem with this approach is if this setting will be useful to the users in general (I think not)
* Introduce a field in the DAP stopped event which would specify if we should autoFocus editor - also not a fan of, since we rarely specify how the UX should behave in the protocol

I am fine with doing option 1 if the need for this is great or if at least somebody else will also profit.

@daviwil @weinand thoughts?

**Comment by daviwil** [comment]
I agree that option 2 isn't ideal since the protocol should focus on the details of the debugging session, not the UX.  I don't think the debug.autoFocusEditor is ideal either because it would prevent me from turning that on by default for all PowerShell extension users (unless I automatically add it to their user settings, which I'd prefer not to do).

What about a third option, allowing this to be configured by the debugger contribution in my package.json?  I know there are no UX settings right now for the debugger contributions, but this seems like the most appropriate place to start adding them.

**Comment by isidorn** [comment]
Adding a debugger contribution which specifies how ux behaves in the package.json also feels ugly imho.
Since none of the sollutions appear particularly appealing to me I would wait for us to get at least one more use case for this before implementing something.
But let's also wait and see @weinand thoughts

**Comment by pcgeek86** [comment]
This is also happening when I hit F8 to run the "current line" in the PowerShell Extension. The Integrated Terminal is capturing focus, so I have to click back into my code in order to continue working.

**Comment by isidorn** [comment]
Closing because we are not planning to implement this within the next 12 months.
