### ISSUE TITLE
工作区的所有符号搜索，只能按照所有单子首字母进行模糊搜索，希望可以拓展下

### ISSUE THREAD

**Issue by aaronyhu** [microsoft/vscode#231176]
Type: <b>Feature Request</b>

比如搜索符号test_abc，搜索tc无法搜索到，只能每个单词首字母都输入才能模糊匹配到，如ta

VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 5.4.241-1-tlinux4-0017.7
Remote OS version: Linux x64 5.4.241-1-tlinux4-0017.7

**Comment by aaronyhu** [comment]
the lastest version not resolve my problem
> 感谢您创建此问题！
> 
> 然而，由于您没有使用英语，我们很难进行处理。如果可能，请您将此问题描述修改为英文。请您直接编辑此问题，不要提交回复或新问题。
> 
> 请注意，机器翻译服务通常无法处理用于讨论软件问题所需的技术性语言，所以我们推荐您寻找一位熟悉相关技术的人来协助翻译。
> 
> 如果您无法做到，没有关系。此问题已经被标记为需要翻译，等待社区成员志愿进行翻译。
> 
> Thanks for creating this issue!
> 
> Unfortunately, as the description is not in English, it's hard for us to work on. If possible, please edit the original issue to be in English.
> 
> In our experience, automatic translation services are not able to handle the technical language needed to effectively communicate about software issues, so we recommend finding a human translator who is familiar with our technology to help.
> 
> Otherwise, we have marked this as needing translation and a community member may be able to help out.

**Comment by aaronyhu** [comment]
> Thanks for creating this issue! It looks like you may be using an old version of VS Code, the latest stable release is 1.94.2. Please try upgrading to the latest version and checking whether this issue remains.
> 
> Happy Coding!

the lastest version dont solve my problem

**Comment by Privia2023** [comment]
> Thanks for creating this issue! It looks like you may be using an old version of VS Code, the latest stable release is 1.94.2. Please try upgrading to the latest version and checking whether this issue remains.
> 
> Happy Coding!

Hi.
Original Question:
 I'm trying to find a variable named `test_abc` ("I've already defined it."). If I type `tc`, IntelliSense doesn't suggest it properly. I have to type the first letter of at least two words for it to suggest correctly."

**Comment by karthiknadig** [comment]
We sincerely apologize for the delay in responding to your issue. Due to the high volume of reports, we’ve been unable to address every submission promptly, especially those that lack the details needed for us to investigate effectively.

To ensure that we can help you and others more efficiently, we kindly request that issues include detailed and actionable information. This allows us to narrow down the problem and work on a resolution faster. Please refer to our [issue reporting guidelines](https://aka.ms/vscodeissuereporting) for guidance on how to provide the necessary details.

We value your feedback and thank you for taking the time to report issues—it helps us make the product better for everyone.

Happy Coding!
