### ISSUE TITLE
"New File" and "New Folder" buttons are greyed out if a readonly file is selected

### ISSUE THREAD

**Issue by DetachHead** [microsoft/vscode#231298]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.94.0
- OS Version: windows 10

if a file is marked as readonly, selecting it prevents you from being able to create a new file or folder.

Steps to Reproduce:

1. add a file path to `files.readonlyInclude` in `settings.json`, eg:
    ```json
    {
        "files.readonlyInclude": {
            "foo.py": true
        }
    }
    ```
2. select the readonly file:
    ![Image](https://github.com/user-attachments/assets/2f831776-dd74-4f54-a4fc-5861d7752ed0)
3. try to click "New file" or "New folder"
    ![Image](https://github.com/user-attachments/assets/6997794c-71dc-47fe-bd99-07c42fe4d004)

**Comment by DetachHead** [comment]
same issue on 1.94.2

**Comment by duncpro** [comment]
I reproduced this on version 1.94.2 on macOS. 

This is caused by [`ExplorerResourceNotReadonlyContext`](https://github.com/microsoft/vscode/blob/39fd376a04ae461e1abb4212d6395d7a56959198/src/vs/workbench/contrib/files/common/files.ts#L43) being a precondition for the actions `workbench.files.action.createFolderFromExplorer`,
and `workbench.files.action.createFileFromExplorer`.

https://github.com/microsoft/vscode/blob/39fd376a04ae461e1abb4212d6395d7a56959198/src/vs/workbench/contrib/files/browser/views/explorerView.ts#L1116-L1156

 [`ExplorerResourceNotReadonlyContext`](https://github.com/microsoft/vscode/blob/39fd376a04ae461e1abb4212d6395d7a56959198/src/vs/workbench/contrib/files/common/files.ts#L43) is true whenever the selected file/folder is writable. So removing this precondition will obviously fix it. 
```js
// precondition: ExplorerResourceNotReadonlyContext,
```
But doing so will introduce the opposite problem  that we already have. Meaning the button will appear clickable in some cases when a file/folder cannot actually be created.

## New File/Directory Button Behavior
- If nothing is selected, clicking the button will create a child file/folder in the project root.
- If a file is selected, clicking the button will create a sibling file/folder.
- If a folder is selected, clicking the button will create a child file/folder of the selected folder.

The latter case is why this precondition exists in the first place. 

I think what we really want is for the button to be greyed-out only when a read-only *directory* (not a file) is selected.

```js
ContextKeyExpr.and(
    ExplorerResourceReadonlyContext,
    ExplorerFolderContext
).toNegated()
```

Note that when a a parent directory Is readonly, no child, grandchild, etc is writable. However right now apparently we only check to see if the currently selected item is writable, not its ancestors. In order to make the greyed-out-ness of the button fully consistent with writability, some check like that will have to be implemented too.

**Comment by duncpro** [comment]
I'm working on a pull request to fix this
