### ISSUE TITLE
getWordAtPosition is slow in very long lines

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#2312]
- `large_files\result - Copy.js`
- go to last line
- click around

![image](https://cloud.githubusercontent.com/assets/5047891/12579519/cf6259a0-c428-11e5-9b97-fd3aa1ccc394.png)

[CPU-20160126T123125.cpuprofile.txt](https://github.com/Microsoft/vscode/files/104815/CPU-20160126T123125.cpuprofile.txt)

**Comment by marktrz** [comment]
The problem seems to stem from this function: 

https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/modes/snippetsRegistry.ts#L108

For some reason it looks like it is being compiled to code that parses the entire line, instead of just the 100 character cap. The translated of said function javascript:

`export function getNonWhitespacePrefix(model: IReadOnlyModel, position: IPosition) : string {
	let line = model.getLineContent(position.lineNumber).substr(0, position.column - 1);
	let match = line.match(/[^\s]+$/);
	if (match) {
		return match[0];
	}
	return '';
}`

Worth looking into, making that function do nothing as a quick check seems to solve the problem.

**Comment by alexandrudima** [comment]
Sweet!
