### ISSUE TITLE
i cannot use c++

### ISSUE THREAD

**Issue by DRAG0NE0N** [microsoft/vscode#231426]
Type: <b>Bug</b>

i dunno what to do, I have tried all the possible things I can to make it work but I cant I even tried clion but still not working. Please help me at my telegram @Govind_Ch if u can. It is my humble request.

VS Code version: Code 1.94.0 (d78a74bcdfad14d5d3b1b782f87255d802b57511, 2024-10-02T13:08:12.626Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.79GB (2.02GB free)|
|Process Argv|--crash-reporter-id 0bc8c1ab-ffa6-4958-952c-9a00aacd9081|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
c-cpp-runner|fra|9.4.9
better-cpp-syntax|jef|1.27.1
cmake-tools|ms-|1.19.52
cpptools|ms-|1.22.9
cpptools-extension-pack|ms-|1.3.0
cmake|twx|0.0.17
vscode-lldb|vad|1.11.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
da93g388:31013173
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31134774
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
defaultse:31146405
notype1:31151523
cc771715:31146322

```

</details>

**Comment by DRAG0NE0N** [comment]
nope still not working

**Comment by chan9an** [comment]
It seems like you're facing some issues with your C++ setup, and **I’m guessing you haven’t installed MinGW yet**. Since there’s no direct support for C++ on Windows, we need to install MinGW manually and configure it properly to get everything working.

First, download the MinGW installer from the following link:
[MinGW SourceForge]
(https://sourceforge.net/projects/mingw/)

During the installation process, you'll be prompted to choose components. Make sure to select the following:

mingw-developer-toolkit
mingw32-base
mingw32-gcc-g++
mingw32-gcc-objc
msys-base
Next, click on the Installation menu (in the top left corner) and choose "Apply Changes." Let the installation complete.

Once installed, the crucial step is to add MinGW to your system's environment variables. To do this:

Navigate to the folder where MinGW is installed (usually C:\MinGW).
Go into the bin folder, and copy the folder path (which will likely be C:\MinGW\bin).
Open the Start Menu, search for "Edit the system environment variables," and open it.
In the System Properties window, click on Environment Variables....
Under System Variables, find Path, select it, and click Edit.
Click New, then paste the path you copied (C:\MinGW\bin) into the field.
Click OK to close all windows and apply the changes.

**Open a terminal (Command Prompt) and type the following command:**
g++ --version

If this shows the version of the GNU compiler, congratulations

**If this process seems complicated, I recommend searching directly on YouTube for tutorials like "How to install C++ in Windows for VS Code"**
