### ISSUE TITLE
VSCode extensions marketplace in VSCodium

### ISSUE THREAD

**Issue by dverbru** [microsoft/vscode#231569]
I would like Microsoft to confirm whether the VSCode marketplace is allowed to be used for VSCodium as well.
[This question](https://github.com/microsoft/vscode/issues/31168#issuecomment-1836431221) has been unanswered for long, and we need the clarity.

**Comment by isidorn** [comment]
Marketplace terms of use https://cdn.vsassets.io/v/M146_20190123.39/_content/Microsoft-Visual-Studio-Marketplace-Terms-of-Use.pdf state that "Marketplace 
Offerings are intended for use only with Visual Studio Products and Services and you may only install 
and use Marketplace Offerings with Visual Studio Products and Services. "

Since VSCodium is not a Visual Studio product it is not allowed to use VS Marketplace from VSCodium. We will also answer that question soon.
