### ISSUE TITLE
Terminal link handler should return the matches not a single string

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#23152]
- VSCode Version: master

This would allow the link handler to take line/column information into consideration when opening the resource. If a user runs a compile task with attached problem matcher I even want to highlight resource links which indicate a problem (containing line information) and not any arbitrary file. This is why the regexp contains information to match line information.

**Comment by Tyriar** [comment]
@dbaeumer my thinking here was to make your regex include the line and column information (and anything else) in the matched link and then process it within the link handler to split the uri, line and column. This does mean that the line and column are underlined when hovered, which is probably a good thing imo.

I would prefer to keep the xterm.js API as slim as possible, it is experimental currently though so I have freedom to change it. Another option is to have the API return the entire line somehow, either in addition to or instead of the match.
