### ISSUE TITLE
Add the ability to detect what host the codespace is currently running in.

### ISSUE THREAD

**Issue by jongio** [microsoft/vscode#231531]
When developing an application that runs in the terminal like a cli or a script, we need to know if the codespace is running in the browser in vs code connected to a codespace or in a dev container. 

One possible solution would be to set an environment variable, something like `CODESPACES_HOST` and set that to either browser, vs code, code spaces or vs code dev container.

**Comment by bamurtaugh** [comment]
cc @joshspicer - I wasn't sure where this request would fit best, so started here and would love to get your thoughts.

**Comment by joshspicer** [comment]
All Codespaces should have a `$CODESPACES` env variable set.  It won't however discriminate the kind of client you're connected to (web vs. desktop client).

```bash
@joshspicer ➜ /workspaces/repo (main) $ echo $CODESPACES
true
```

**Comment by jiasli** [comment]
This issue is derived from https://github.com/Azure/azure-cli/issues/20315. We want to have different behaviors for Azure CLI's authentication in Codepsace.

We need to know **whether Codespace is connected via a local VS Code desktop application or a browser**. This is because

1. In a local VS Code desktop application, the [port forwarding](https://docs.github.com/en/codespaces/developing-in-a-codespace/forwarding-ports-in-your-codespace#using-command-line-tools-and-rest-clients-to-access-ports) feature maps **`localhost` on the remote container** as **`127.0.0.1` on the local machine**. This allows the [auth code flow](https://learn.microsoft.com/en-us/entra/identity-platform/v2-oauth2-auth-code-flow) to work as expected, as the auth code was sent to `localhost` (`127.0.0.1`), thus to the Codespace.
2. But in the browser, the `localhost` on the remote container is mapped as `https://CODESPACENAME-PORT.app.github.dev`. As explained in https://github.com/Azure/azure-cli/issues/20315#issuecomment-1898372497, a random redirect URI is disallowed by Entra.

Once we have this informaiton, Azure CLI can

1. Use auth code flow in a local VS Code desktop application
2. Use device code flow in a browser

**Comment by mitchdenny** [comment]
I'd like to pile onto @jongio's request.

I'm currently working on improving .NET Aspire's support for VSCode/Codespaces and various other remote dev scenarios. I would like the ability to distinguish whether the shell is running locally on a desktop or in Codespaces as well.

I'm already using the `CODESPACE` environment variable to enable translating Aspire dashboard URLs to the `*.app.github.dev` URLs, but if the Codespace front end is a local VSCode install then knowing this would be good to know so we can opt out of this behavior and use the `localhost` port forwarded addresses in preference.

Here is the PR on the Aspire side where I am doing the devcontainer setup:

https://github.com/dotnet/aspire/pull/6491

**Comment by jongio** [comment]
@joshspicer - Those are the scenarios.  Any questions?  Thanks

**Comment by joshspicer** [comment]
It sounds like this is a feature request that would need to be implemented by the Codespaces team to differentiate between the different clients that can be used with that product.  

For all other remote scenarios except the Codespaces web client experience (like using the VS Code Dev Containers extension) a familiar `localhost` address is available when port forwarding.

**Comment by jongio** [comment]
@bamurtaugh - Do you think we should open an issue in a codespaces repo?

**Comment by bamurtaugh** [comment]
Makes sense to me, to open one in https://github.com/orgs/community/discussions/categories/codespaces and close this out.

**Comment by jongio** [comment]
@jiasli thoughts?

**Comment by joshspicer** [comment]
Closing this out as it's related to the Codespaces product and would better be served by the Codespaces team

**Comment by jongio** [comment]
@craiglpeters - Where would be the best place to have this discussion for Codespaces?
