### ISSUE TITLE
New Terminal Launch failed

### ISSUE THREAD

**Issue by xoli404** [microsoft/vscode#231625]
Type: <b>Feature Request</b>

New Terminal Launch failed to execute, giving a mwssagw that read: 
The terminal process failed to launch: Path to shell executable "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" does not exist. 

Please assist and refer me to a chatbot if any is available. I do not have experience with the platform.

VS Code version: Code 1.94.2 (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Windows_NT x64 10.0.18363
Modes:

**Comment by dylthedev** [comment]
I have a similar issue, Mac OS (Sonoma 14.5), with the new version of VSC (1.94.2).

I know it's the version upgrade because I have two machines this has occurred on, only after the upgrade.

My specific issue is when launching the debugger:

`Can't find Node.js binary "npm": path does not exist. Make sure Node.js is installed and in your PATH, or set the "runtimeExecutable" in your launch.json`

Yet it does exist in my `PATH` and the `runtimeExecutable` is set to `"npm"`:
```
{
      "name": "Debug Server",
      "request": "launch",
      "runtimeArgs": ["run", "dev"],
      "runtimeExecutable": "npm",
      "skipFiles": [
        "<node_internals>/**",
        "${workspaceFolder}/server/node_modules/**"
      ],
      "type": "node",
      "envFile": "${workspaceFolder}/server/.env",
      "cwd": "${workspaceFolder}/server",
      "internalConsoleOptions": "openOnSessionStart",
      "outputCapture": "std",
      "serverReadyAction": {
        "action": "startDebugging",
        "name": "Debug Client",
        "killOnServerStop": true
      }
    }
```

Running the following in my zsh terminal in VSC confirms it:
```
node -v
which node
npm -v
which npm
v20.16.0
/Users/dyl/.local/share/mise/installs/node/20/bin/node
10.8.1
/Users/dyl/.local/share/mise/installs/node/20/bin/npm
```

And it's the first entry in my PATH:
`echo $PATH
/Users/dyl/.local/share/mise/installs/node/20/bin:`

It's particularly strange because, on a fresh project with a bare-minimum launch config, it points to the known npm path. Launching with:
```
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "runtimeArgs": ["run", "dev"],
      "runtimeExecutable": "npm",
      "name": "Launch Program",
      "skipFiles": ["<node_internals>/**"],
      "program": "${workspaceFolder}/index.js"
    }
  ]
}
```

Shows: `/Users/dyl/.local/share/mise/installs/node/20/bin/npm run dev ./index.js` in the debug console output.

**Comment by meganrogge** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.
/label info-needed terminal
