### ISSUE TITLE
Can't use "open loaded scripts" to load a URL with query params

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#23194]
Chrome-debug supports .js files with query parameters (`http://localhost/foo.js?bar`). But if I load one with "Open loaded scripts", the query parameter is stripped. This happens here: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/browser/debugContentProvider.ts#L40 since fsPath doesn't include the query parameter. Any idea how to make this work? I don't think URI is expecting to have a URL with another scheme.

**Comment by isidorn** [comment]
That normalize code should only be executed if the source could not be found - otherwise `source` should not be `null` and the `rawSource` should be passed to the adapter.
Do you know why is that? 
As for the `normalize(uri.fsPath)` call - I am not married to it and we can change it to whatever uri massaging techinique would work for you and not break the existing behavior. 
If we change this I would prefer to be in debt week -> april

**Comment by roblourens** [comment]
It tries to get the source from `process.sources`, but it looks like that is only populated when a bp is hit in there, right? Plus it's a different format, I have `"file:///Users/roblou/code/vscode-chrome-debug/testapp/wwwroot/index.html"` in there but the script from the quickopen is like `"debug:http%3A//localhost%3A8080/index.html"`.

**Comment by roblourens** [comment]
I don't know about replacing `uri.fsPath`, `resource.toString(true).substr('debug:'.length)` would do it if that isn't too hacky.

**Comment by isidorn** [comment]
Yes, `process.sources` is only populated once there is a call stack that contains that source - so if it breaks.
Yeah that feels like a total hack. Why don't you experiment with different solutions and create a PR where we can comment and try out different approaches if needed?

**Comment by roblourens** [comment]
This regressed from https://github.com/Microsoft/vscode/commit/ce177da9e11c7c14a143b9beaf743365ce228744 adding back the `query: ''` in DebugContentProvider.getTextContent. @weinand is that needed?

**Comment by roblourens** [comment]
Also, https://github.com/Microsoft/vscode/issues/33712

**Comment by hbenl** [comment]
I think opening the file by putting its url into a `debug:` uri is very fragile, to say the least. I have listed some problems I've noticed while implementing a Loaded Scripts Explorer for the Firefox debug adapter in #32845.
My suggestion would be to add the ability to open files using the numerical `sourceReference` that the debug adapter assigned to them or using the `Source` object that is used for identifying the file in the messages between VS Code and the DA.
Whatever solution you adopt, keep in mind that VS Code should be able to determine that the file opened by clicking on a stackframe and the file opened by clicking in the Loaded Scripts Explorer are one and the same - otherwise setting breakpoints in a file opened through the Loaded Scripts Explorer will become problematic.

**Comment by weinand** [comment]
I've addressed this issue by making sure that the flow `Source` -> uri -> `Source` preserves the data so that the initial and resulting `Source` objects are identical.

So if a Uri is constructed in the following way:
```
const sessionId: string = ...
const source: Source = ...

const uri = vscode.Uri.parse(`debug:${encodeURIComponent(source.path)}?session=${encodeURIComponent(sessionId)}&ref=${source.sourceReference}`);
```
the debugContentProvider inside VS Code will retrieve the content by sending a "sourceRequest" with a "Source" argument to the debug adapter identified by the debug session.

**Comment by weinand** [comment]
Verify that Rob's Chrome-debug  case from above works.

**Comment by roblourens** [comment]
It is escaping the query parameter, but works anyway using the new loadedSources API, because then we can rely on sourceReference instead of a string path.

`To client: {"seq":0,"type":"event","event":"loadedSource","body":{"reason":"new","source":{"name":"test1.js?blah","path":"http://localhost:8080/out/client%20with%20space/test1.js?blah","sourceReference":1000}}}`

`From client: source({"sourceReference":1000,"source":{"path":"http://localhost:8080/out/client%20with%20space/test1.js%3Fblah","sourceReference":1000}})`

**Comment by hbenl** [comment]
> It is escaping the query parameter, but works anyway

I have also seen this (with the Firefox debug adapter) and couldn't find any user-visibile ill effects. In particular, the source url is displayed correctly in the tab opened from the Loaded Scripts Explorer (i.e. the query parameter is unescaped there and other escaped characters in the url remain escaped).

**Comment by weinand** [comment]
Added "Verified" label since both comments from above confirm that this works correctly now.

**Comment by roblourens** [comment]
It does rely on me updating chrome-debug, in case anybody else tries this. I'll do that this week.
