### ISSUE TITLE
Associate profile to all folders under a folder

### ISSUE THREAD

**Issue by Banner-Keith** [microsoft/vscode#231974]
It would be really nice to be able to always load the same profile when opening a certain type of project. For example, let's say I have a react profile and a profile for some other language with little to no overlap in extensions needed etc. It would be really cool if every time I opened a workspace with react inside of it, the react profile was selected automatically even if I had never used that workspace before.

A very simplified version of this would be that we could use wildcards in the workspace folder path to select them. Some examples:

- `C:\git\react\*` would select any workspaces that have a root folder in the react folder
- `C:\git\react\**` to select subfolders too
- `C:\git\*react*` to select any folders that have react in the name

This seems like it would be a fairly simple enhancement while providing a decent amount of value.

An even more advanced approach that would be nice, but more difficult to build would be to look at items in the workspace, like if you found a package.json file, or any tsx files, or cs files could select a C# workload.

**Comment by nikhilweee** [comment]
This would be a great help when using git worktrees. I would love to simply assign `~/repos/myrepo/.worktrees/*` to a profile and not have to worry about selecting the right profile ever again!

**Comment by AlekSi** [comment]
Came here with the same need driven by worktrees

**Comment by QuiteDiam0nd** [comment]
I agree with the comments above that this would be useful in VS Code. 
The issue now has 29 👍 reactions. Could it be triaged again?

My own case is moving between several Chromium checkouts and worktrees, along with smaller C++, Rust, JavaScript, and research projects. They need different extensions and settings.

If directory inheritance is still something VS Code would accept, I can start working on a PR straight away.
I think the first version can be kept fairly small:
  1. An explicit `--profile` keeps the highest priority.
  2. An exact folder or workspace association wins over an inherited one.
  3. Otherwise, VS Code uses the most specific matching parent directory.
  4. If nothing matches, VS Code keeps its existing fallback behavior.

  I checked the relevant code. `getProfileForWorkspace()` currently checks for an exact `URI` match.

https://github.com/microsoft/vscode/blob/9afe2783a7239c915d5fc6d1bd9c842f9ca06c2e/src/vs/platform/userDataProfile/common/userDataProfile.ts#L595-L604

  This lookup happens before the window is loaded.
  https://github.com/microsoft/vscode/blob/9afe2783a7239c915d5fc6d1bd9c842f9ca06c2e/src/vs/platform/windows/electron-main/windowsMainService.ts#L1725-L1755 
There is already `isEqualOrParent()` for checking whether one local or remote URI is below another. 
  https://github.com/microsoft/vscode/blob/9afe2783a7239c915d5fc6d1bd9c842f9ca06c2e/src/vs/base/common/resources.ts#L171-L180

 Directory matching can therefore use the existing lookup without scanning the project. 

The PR would still need storage, UI, precedence handling, and tests, but the matching itself looks contained.
@sandy081, is this still out of scope, or can I go ahead with the PR?

  P.S. For my own setup, I already use a small zsh launcher that selects profiles from project markers. It works when I open a directory through the launcher, but not when a worktree or folder is opened directly from VS
  Code for example. Marker rules could be considered later, but I would leave them out of the first PR because conflicting markers and remote filesystems need separate decisions.

**Comment by QuiteDiam0nd** [comment]
@sandy081, could you take a look?
