### ISSUE TITLE
Debug settings window icon does not appear on Linux

### ISSUE THREAD

**Issue by jdelmerico** [Microsoft/vscode#23213]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:00:46.854Z)
- OS Version: Linux x64 4.4.0-66-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.6.0|
|Go|lukehoban|0.6.55|;

---

Steps to Reproduce:

1.  Select Debug from toolbar on left
2.  Notice gear icon is missing.

**Comment by rmunn** [comment]
I can't reproduce this on my Linux Mint 18 system (which is basically Ubuntu Xenial 16.04.2 with a different GUI). I have VS Code version 1.10.2 as well, and pretty much the same kernel (mine is 4.4.0-53-generic). But I doubt this issue is related to the kernel.

My installed extensions:


|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.6.2|
|Ionide-FAKE|Ionide|1.2.3|
|Ionide-Paket|Ionide|1.6.3|
|Ionide-fsharp|Ionide|2.25.2|
|Bookmarks|alefragnani|0.12.0|
|python|donjayamanne|0.6.0|
|json-tools|eriklynd|1.0.2|
|csharp|ms-vscode|1.8.0|
|mono-debug|ms-vscode|0.15.4|
|vscode-icons|robertohuertasm|7.4.0|
|Align|steve8708|0.2.0|;

**Comment by isidorn** [comment]
This is designed behvaior when you open vscode without a folder (purple vscode).
In order to configure a launch.json please open a folder in vscode and all the functionlaty should be there.
For more details check out our docs http://code.visualstudio.com/docs/editor/debugging

**Comment by jdelmerico** [comment]
Thank you @isidorn .  I can confirm this resolved the issue.  

For others running into this I also ran into a problem where my GOROOT was not using the environment variable I set in my .bashrc.  In this case I had to update the launch.json to include. I also had to figure out how to pass command-line arguments.  This also is done in the launch.json with a comma delimited list of name value pairs.  Here's my working launch.json:

{
    "version": "0.2.0",
    "configurations": [
    
        {
            "name": "Launch",
            "type": "go",
            "request": "launch",
            "mode": "debug",
            "remotePath": "",
            "port": 2345,
            "host": "127.0.0.1",
            "program": "${workspaceRoot}",
            "env": {"GOROOT" : "/usr/local/go"},
            "args": ["-from", "USD", "-to", "TRY"],
            "showLog": true
            
        }
    ]
}
