### ISSUE TITLE
Web UI will not work

### ISSUE THREAD

**Issue by alonnberg** [microsoft/vscode#232139]
Type: <b>Bug</b>

I get multiple errors:
* Unable to resolve resource vscode-vfs://github%2B...
* TypeError: error loading dynamically imported module: https://assets.github.dev/stable/384f...
* vscs:web-client:7186:LocalStorageKeychain Error: Failed to get cipher record
* Uncaught (in promise) Error: command 'codespaces.workbench.dispose' not found

VS Code version: Code - Insiders 1.95.0-insider (39fd376a04ae461e1abb4212d6395d7a56959198, 2024-10-24T05:04:31.844Z)
OS version:   
Modes:

System Info: Mozilla/5.0 (Macintosh; Intel Mac OS X 14.7; rv:109.0) Gecko/20100101 Firefox/115.0 WaterFox<details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
anycode|ms-|0.0.73
anycode-c-sharp|ms-|0.0.5
anycode-typescript|ms-|0.0.5
anycode-cpp|ms-|0.0.5
anycode-go|ms-|0.0.5
anycode-php|ms-|0.0.6
anycode-python|ms-|0.0.5
anycode-rust|ms-|0.0.6
anycode-kotlin|ms-|0.0.5
anycode-java|ms-|0.0.5
codespaces|Git|1.17.3
remotehub|Git|0.64.0
vscode-pull-request-github|Git|0.98.0
azure-repos|ms-|0.41.2024101602
remote-repositories|ms-|0.43.2024102201

(1 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
It looks like this is caused by the Codespaces extension. Please file the issue in the [Codespaces Discussion Forum](https://github.com/community/community/discussions/categories/codespaces). Make sure to check their issue reporting template and provide them relevant information such as the extension version you're using. See also our [issue reporting guidelines](https://aka.ms/vscodeissuereporting) for more information.\n\nHappy Coding!
