### ISSUE TITLE
Ability to change internal console refresh rate.

### ISSUE THREAD

**Issue by BladeMight** [Microsoft/vscode#23212]
When i debug my apps in VSCode's internal console output updates *not so fast as in external terminal*, so i think that it has refresh rate or something, i'd be really happy if i can select it. 

Also the output of internal console can't display unicode chars sometimes, it display it as **�** chars...

**Comment by Tyriar** [comment]
@BladeMight you cannot change the refresh rate, it updates up to 60 fps (depends on Chromium). When there is a lot of output there is some optimizations I made that allow it to skip additional frames in order to process the output faster, resulting in commands finishing faster. You can read some more about the recent performance improvements that were made here https://github.com/Microsoft/vscode/issues/17875

If you want to follow up on the unicode issue, could you create an issue via Help > Report issue and provide a screenshot and the content of your settings.json? Also if you're on macOS/Linux could you show the output of `echo $LANG`?
