### ISSUE TITLE
Reopen previous editor when trying to open a folder as link

### ISSUE THREAD

**Issue by pixieaka** [microsoft/vscode#23218]
It's not a problem but it not a right behavior.

![ks](https://cloud.githubusercontent.com/assets/17777237/24325618/20c913ea-11a5-11e7-9a90-78e6fa0f3c15.gif)

**Comment by aeschli** [comment]
I know it can be discussed if a link to a folder is a valid link to be returned by a link provider, VS code should definitely handle it, like any other invalid link.

**Comment by aeschli** [comment]
I reverted the change as IMO we should keep the link detection for any kind of link (also folders) as it is useful for the Monaco editor that can open any URL.

**Comment by jrieken** [comment]
The `OpenerService` call the editor service `file` links

**Comment by bpasero** [comment]
Here is what happens:
- the tab is in preview mode so opening anything else basically closes it right away
- users opens a URI that happens to be a folder
- we try to open it but cannot because it is just a folder
- we close the editor because there is nothing to show

At the time we open the resource we do not know that this is a file or folder.

Arguably we could reopen the previous file in these error cases.

**Comment by aeschli** [comment]
@bpasero I'd say, don't try to open and editor if the path ends with '/'

**Comment by bpasero** [comment]
Yeah sounds like a good idea.
