### ISSUE TITLE
Avoid `unknown` in ctor

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#232243]
We have this ctor for `LanguageModelToolResult` 

https://github.com/microsoft/vscode/blob/2eb50fc57e3084eb825ea01d1beca419df140890/src/vscode-dts/vscode.d.ts#L19900

The `| unknown` parts makes it that you can actually create this type with any kind of array. Maybe we should have `unknown` only on the property but not the ctor?

**Comment by roblourens** [comment]
I was actually looking at the same thing in `LanguageModelToolResultPart` but we can't avoid it there because you need to pass all the parts from `LanguageModelToolResult` which include `unknown`. Maybe we can make it better in the future with a similar solution to the `toolInvocationToken`, like `type LanguageModelFuturePart = { _symbol: unique symbol; }`.

But I agree that there isn't any reason for the constructor on ``LanguageModelToolResult` to take `unknown` so I'll do that as a candidate.

**Comment by TylerLeonhardt** [comment]
this... feels like a "verify by code review"

https://github.com/microsoft/vscode/blob/38dc6ac5a771cc94bde1344722bb2d02c80096ea/src/vscode-dts/vscode.d.ts#L19900

looks right
