### ISSUE TITLE
At EOL, two offsets map to same position in CRLF files

### ISSUE THREAD

**Issue by sashaweiss** [Microsoft/vscode#23247]
In a CRLF document with the text:
```
asdf
asdf
```
the position (0, 4) would refer to the spot just after the first `f`. Calling `document.offsetAt(pos)` returns 4. Calling `document.positionAt(4)` returns (0, 4).

However, calling `document.positionAt(4+1)` also returns (0, 4).

In a LF document, calling `document.positionAt(4+1)` returns (1, 0).

My current use case is running through a document's text, moving right in the document by position:

```javascript
/**
 * The position one step right in the document
 * @param document the document to move in
 * @param pos the position to move from
 * @returns the position one step right, or null if last
 */
function posRight(document: vs.TextDocument, pos: vs.Position): vs.Position | null {
    let offset = document.offsetAt(pos)
    return offset < document.getText().length ? document.positionAt(offset + 1) : null
}
```

Moving up lines works, since in the double-mapping case `document.offsetAt(pos)` returns the lower of the two offsets.

My workaround currently is to compute the next position, compare it to the current position, and if they're the same to instead increment by two.

Any advice would be appreciated! This doesn't feel like intuitive behavior - my impression was that one offset mapped to one position, and vice versa.

Thanks!

- VSCode Version: 1.10.2
- OS Version: OS X 10.11

**Comment by alexandrudima** [comment]
The reason for that is that we treat line endings (in this case `\r\n`, CRLF) as an **indivisible unit**. We don't want any edit, decoration, or any position/range based API to be led into thinking that the gap between `\r` and `\n` is targetable in any way.

More specifically, in VS Code, positions always describe a location in between characters or at the beginning of a line or at the end of a line (sort of like how a cursor works).

Here I represent the position with a red vertical bar.

### Position (0, 4) is valid and maps to offset 4
![image](https://cloud.githubusercontent.com/assets/5047891/24344898/de42abc4-12cd-11e7-937a-31ed3f0d4c53.png)

### The next valid position is (1,0) and maps to offset 6
![image](https://cloud.githubusercontent.com/assets/5047891/24344966/2babdf70-12ce-11e7-8bd3-20d9d4485581.png)

### So what happens to offset 5
Since position (0,5) is not a valid position, since it targets a location inside the EOL separator, anything that would use that position is pushed on to a valid position on the same line. e.g.
* `doc.validatePosition(new Position(0, 5))` => `(0,4)`
* `doc.validatePosition(new Position(0, 6))` => `(0,4)`
* `doc.validatePosition(new Position(0, 123))` => `(0,4)`
* etc.

Since offset 5 would normally be transformed to position (0,5), the return value gets validated into (0, 4)

**Comment by sashaweiss** [comment]
I see - thank you for the comprehensive answer!
