### ISSUE TITLE
Quick open has duplicate "recently opened" entries

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#232426]
Steps to Reproduce:

I have been opening the same file quite a lot recently, and now the quick open menu has several duplicate entries for it:

![Image](https://github.com/user-attachments/assets/478eac7d-6ce2-4684-931f-d6ac829eb54d)

**Comment by TylerLeonhardt** [comment]
@bpasero I don't think we do anything special to display this. Why would history return duplicate files?

**Comment by bpasero** [comment]
@amunger @benibenj when this happens, can you "Log Storage Contents" from F1 and find the `history.entries` value in workspace storage and diagnose the contents around the duplicates. It is very likely these are actually NOT the same paths.

![Image](https://github.com/user-attachments/assets/ebe4d494-e727-4cb5-bcea-6c47a760bbd1)

**Comment by bpasero** [comment]
I have a repro when you have the same editor opened multiple times in the editor grid.

**Comment by amunger** [comment]
I now have these two entries in history.entries, but plenty of duplicates still in there:

"resource": "file:///c%3A/src/vscode-jupyter/src/interactive-window/interactiveWindow.ts#LNaN",
"resource": "file:///c%3A/src/vscode-jupyter/src/interactive-window/interactiveWindow.ts",

![Image](https://github.com/user-attachments/assets/a9db53d2-49f2-4113-846a-ec3c83a1ccf8)

**Comment by bpasero** [comment]
@amunger but in the case of `file:///c%3A/src/vscode-jupyter/src/interactive-window/interactiveWindow.ts`, I see that the resources are not equal, the one has a suffix of `#LNaN`. Since this is a `URI`, we probably still succeed opening that resource because its the `fragment` portion and does not impact the `path`.

There seems to be code somewhere that actively opens such as `URI` into VS Code, which is not really supported, but we also do not really prevent this from happening.

Our duplication detection in the history service is purely based on `URI.toString()`, not taking fragments or query into account.

So we need to figure out how these `URIs` get into the system, any steps?

**Comment by amunger** [comment]
the LNaN URI happens from the mermaid extension not properly validating the result of a parseInt call and using the result in `vscode.commands.executeCommand('vscode.open', uri);`.

There are a bunch of other duplicates in that list in the screenshot that aren't within the history.entries though. Any concern with those?

**Comment by bpasero** [comment]
@amunger and they are not having this fragment part and are 100% same string?

**Comment by amunger** [comment]
I don't know how to check if they are the same string - there are only two entries in history.entries, and 7 occurrences of interactiveWindow.ts

**Comment by bpasero** [comment]
@amunger thats explained in https://github.com/microsoft/vscode/issues/232426#issuecomment-2443291129, the "recently opened" are stored in workspace storage. I would have not assumed that after a restart you would still see them with my fix.

**Comment by bpasero** [comment]
Maybe you can share the workspace state DB with me.

**Comment by amunger** [comment]
is that just the contents from "log Storage database contents"?
[storageDatabaseContents.json](https://github.com/user-attachments/files/17667117/storageDatabaseContents.json)

**Comment by bpasero** [comment]
yes, thanks.
