### ISSUE TITLE
[Remote SSH] Non-default profile causing connection issues in 1.95 

### ISSUE THREAD

**Issue by ruijzhan** [microsoft/vscode#232602]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.95.0
- OS Version: Windows 11

Steps to Reproduce:

1. Upgrade VSCode to 1.95.0
2. Connect any remote host by Remote-SSH

The output indicated a connection timeout, and an error window popped up. However, the logs continued to print, showing that the connection to the remote host was actually established.

![Image](https://github.com/user-attachments/assets/f96e2ca4-7145-4371-b7b9-162d0cd784ba)
![Image](https://github.com/user-attachments/assets/4c153514-46c3-466f-9f74-2b832d999360)
![Image](https://github.com/user-attachments/assets/396d5009-f095-46d9-8215-68ab0ab2a8ec)

**Comment by ruijzhan** [comment]
One more clue is that the VSCode keeps asking the OS of remote host,  then I select Linux, after that the error window pops out.

**Comment by hellcry37** [comment]
I come here to do exactly this post, thanks, UP

**Comment by gitgud5000** [comment]
code command seems to be broken aswell. `code .` or `code --wait` passed to git to use the editor don't work anymore in Remote SSH

**Comment by mlawson27** [comment]
@ruijzhan are you using VSCode profiles by chance?  I had this problem in one VSCode instance but not another, and the difference ended up being that the instance that didn't work had an enabled profile.  The instance that used a profile also worked if I reverted to 1.94.2.  When I opened the settings.json for the profile and my user settings.json and moved over the relevant settings, the failing instance started working as expected.

I think VSCode 1.95 is erroneously applying settings that are supposed to apply across all profiles on a per-profile basis.  Since they are supposed to apply to all profiles, you can't set these settings for the profile except through the profile's settings.json (though you really shouldn't need to do so; it's just a workaround that seems to work for me).

**Comment by ruijzhan** [comment]
> [@ruijzhan](https://github.com/ruijzhan) are you using VSCode profiles by chance? I had this problem in one VSCode instance but not another, and the difference ended up being that the instance that didn't work had an enabled profile. The instance that used a profile also worked if I reverted to 1.94.2. When I opened the settings.json for the profile and my user settings.json and moved over the relevant settings from the user settings to the profile settings (even though they're supposed to be "across all profiles" settings), the failing instance started working as expected.
> 
> I think VSCode 1.95 is erroneously applying settings that are supposed to apply across all profiles on a per-profile basis. Since they are supposed to apply to all profiles, you can't set these settings for the profile except through the profile's settings.json (though you really shouldn't need to do so; it's just a workaround that seems to work for me), so they use the default value. Since one of these settings is `remote.SSH.remotePlatform`, it tries to take the value from a profile (which is empty), so it asks you the platform, and it doesn't save to the profile settings (since it's not supposed to), so your platform selection never takes, and it asks you every time you connect.

Thank you. You are right. When I switched to Default profile, it works.  

@joshspicer please refer to this

**Comment by williamyizhu** [comment]
Same issue, VSCode 1.95, MacOS.

Error msg:

**Setting up SSH Host xxx.xxx.xxx.xxx: Copying VS Code Server to host with scp**

**Comment by ruijzhan** [comment]
> [@ruijzhan](https://github.com/ruijzhan) are you using VSCode profiles by chance? I had this problem in one VSCode instance but not another, and the difference ended up being that the instance that didn't work had an enabled profile. The instance that used a profile also worked if I reverted to 1.94.2. When I opened the settings.json for the profile and my user settings.json and moved over the relevant settings from the user settings to the profile settings (even though they're supposed to be "across all profiles" settings), the failing instance started working as expected.
> 
> I think VSCode 1.95 is erroneously applying settings that are supposed to apply across all profiles on a per-profile basis. Since they are supposed to apply to all profiles, you can't set these settings for the profile except through the profile's settings.json (though you really shouldn't need to do so; it's just a workaround that seems to work for me), so they use the default value. Since one of these settings is `remote.SSH.remotePlatform`, it tries to take the value from a profile (which is empty), so it asks you the platform, and it doesn't save to the profile settings (since it's not supposed to), so your platform selection never takes, and it asks you every time you connect.

Hi,

One more update here:

When I switch to the Default profile, everything works fine. However, if I edit the `settings.json` of non-default profiles to include the host platform, VSCode no longer prompts for the host platform at startup. Despite this, the error window still appears, although the connection continues running in the background.

**Comment by mlawson27** [comment]
Yeah, I did the same.  I also had to add `dev.containers.dockerPath` to my profile-specific settings.json in order to work with podman, and that setting is also supposed to apply to all profiles, so I think the issue affects to all applies-to-all-profile settings.

**Comment by devaex** [comment]
@mlawson27 

Great find. I confirm that this solves the problem and it must certainly be something related to the scope of the settings.

What I did:
- I didn't change the profile to the default. I continued on my profile.
- F1 -> Preferences: Open User settings (JSON).
- Put     `"dev.containers.dockerPath": "podman"` in settings.
- Vscode warned that this configuration is out of scope but I ignored it.
- Try to attach to the container, and the connection was made as always.

**Comment by joshspicer** [comment]
Thank you all for the investigations.  I'm looking into if there were any changes to VS Code profiles in the last release that we can handle better in this extension

**Comment by devaex** [comment]
@joshspicer Yes, the issue persist in version 1.95.1 as related here:
https://github.com/microsoft/vscode-remote-release/issues/10426#issuecomment-2451891277

**Comment by joshspicer** [comment]
I'm unfortunately not able to repro.  I tried creating a new profile (not tweaking any of the settings in the new profile).  I then swapped to that profile and ssh'd to a host. 

Some asks for anyone that can repro:
1. Share information on your profile (screenshots of that configuration) and perhaps a video demo'ing the issue to help me catch what I may be missing.
2. Running https://github.com/microsoft/vscode-bisect to narrow down this behavior to a single VS Code commit, so I can take that back to the core VS Code folks

**Comment by ruijzhan** [comment]
> I'm unfortunately not able to repro. I tried creating a new profile (not tweaking any of the settings in the new profile). I then swapped to that profile and ssh'd to a host.
> 
> Some asks for anyone that can repro:
> 
> 1. Share information on your profile (screenshots of that configuration) and perhaps a video demo'ing the issue to help me catch what I may be missing.
> 2. Running https://github.com/microsoft/vscode-bisect to narrow down this behavior to a single VS Code commit, so I can take that back to the core VS Code folks

Hello, this is one of my profile that I have problem with Remote-SSH. When I was on this profile and I tried to connect to a remote host via ssh  in VSCode, the problem can be reproduced.

https://vscode.dev/profile/github/29935e3ae18f67ccb4e06424003d9578

Let me know if you need any more information

**Comment by joshspicer** [comment]
Sorry for the delay and thanks all for the data.  I can indeed repro, I just don't see the crash due to the properties of the host I am SSH'ing to.  I do get prompted each time for the remote platform on 1.95, which is enough to prove the bug

**Comment by sandy081** [comment]
@joshspicer Can you please verify this?

**Comment by sandy081** [comment]
Can some one please verify if this issue got fixed in the following builds

VS Code Build: bc150766acea3bb8ff2dfc6e543ec2b8dc967b10

- [darwin](https://vscode.download.prss.microsoft.com/dbazure/download/stable/bc150766acea3bb8ff2dfc6e543ec2b8dc967b10/VSCode-darwin.zip)
- [darwin-arm64](https://vscode.download.prss.microsoft.com/dbazure/download/stable/bc150766acea3bb8ff2dfc6e543ec2b8dc967b10/VSCode-darwin-arm64.zip)
- [darwin-universal](https://vscode.download.prss.microsoft.com/dbazure/download/stable/bc150766acea3bb8ff2dfc6e543ec2b8dc967b10/VSCode-darwin-universal.zip)
- [win32-arm64](https://vscode.download.prss.microsoft.com/dbazure/download/stable/bc150766acea3bb8ff2dfc6e543ec2b8dc967b10/VSCodeSetup-arm64-1.95.3.exe)
- [win32-arm64-archive](https://vscode.download.prss.microsoft.com/dbazure/download/stable/bc150766acea3bb8ff2dfc6e543ec2b8dc967b10/VSCode-win32-arm64-1.95.3.zip)
- [win32-arm64-user](https://vscode.download.prss.microsoft.com/dbazure/download/stable/bc150766acea3bb8ff2dfc6e543ec2b8dc967b10/VSCodeUserSetup-arm64-1.95.3.exe)
- [win32-x64](https://vscode.download.prss.microsoft.com/dbazure/download/stable/bc150766acea3bb8ff2dfc6e543ec2b8dc967b10/VSCodeSetup-x64-1.95.3.exe)
- [win32-x64-archive](https://vscode.download.prss.microsoft.com/dbazure/download/stable/bc150766acea3bb8ff2dfc6e543ec2b8dc967b10/VSCode-win32-x64-1.95.3.zip)
- [win32-x64-user](https://vscode.download.prss.microsoft.com/dbazure/download/stable/bc150766acea3bb8ff2dfc6e543ec2b8dc967b10/VSCodeUserSetup-x64-1.95.3.exe)

**Comment by joshspicer** [comment]
validated from a windows host to a linux remote host.  When using a non-deafult profile I no longer see a prompt on each connection to select the remote platform

**Comment by ruijzhan** [comment]
Verified from Win11 to remote Ubuntu host. Problem solved. Thank you.
