### ISSUE TITLE
Ctrl+P is very slow and finds .js files now

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#23270]
![image](https://cloud.githubusercontent.com/assets/5047891/24351172/ffc0c936-12e4-11e7-9926-748c6afce56c.png)

**Comment by bpasero** [comment]
@roblourens did something change here? are we using ripgrep for quick open file search too?

**Comment by kumarharsh** [comment]
+1. My `Ctrl+P` is showing me node_modules files also, and the search has become excruciatingly slow.

**Comment by roblourens** [comment]
No, that work shouldn't have impacted this.

**Comment by t-sauer** [comment]
I think this is the same problem I described in #23274

**Comment by alexandrudima** [comment]
fyi @jrieken Perhaps also path change related?

**Comment by jrieken** [comment]
hm... @roblourens where are paths matched against the excludes?

**Comment by bpasero** [comment]
This is not path related, but introduced via the new useExcludeSettings from @roblourens I think. 

@roblourens this is a dangerous setting to add, because every client needs to set it. I would turn it around and make the flag in a way that you can opt in to disable user excludes, but by default we exclude from settings.

**Comment by roblourens** [comment]
Oh, you're right @bpasero

**Comment by Geeprox** [comment]
It's really very slow, much slower than Sublime Text...

**Comment by roblourens** [comment]
@Geeprox It should be back to its normal speed in today's insiders build. If you are using the stable version, or if it's still unreasonably slow, please open another issue.
