### ISSUE TITLE
Custom Audio Cues

### ISSUE THREAD

**Issue by Zedelghem** [microsoft/vscode#232853]
This is really a minor request with no bearing whatsoever on critical VSC features. Nonetheless, perhaps someone else would be happy to see it too.

I use **Jupyter Notebooks** a lot and in my field it is very difficult to predict how long a cell will run. I could easily spend 30m staring at a cell waiting for it to finish. That's why **audio cues** (for cell completion in this case) are so useful; I could tend to other tasks and come back when prompted.

It might sound petty, but the one and only available cell completion sound is **unbelievably annoying**. It is fine when I am waiting for ages for a cell to finish, but not so great when I run 20 cells that finish in seconds. I have my own DIY setup for that, of course, but it likes to break with VSCode updates.

**It would be wonderful to be able to change it from the settings**. Honestly, any way would be great: **choose from a predefined list, trigger system sounds or just point to a sound file**. Anything to get rid of that hellish midi birdsong. 

Please, save my sanity!

Best
Borys

**Comment by Zedelghem** [comment]
@meganrogge So we should upvote the other one?

**Comment by AFre100** [comment]
@Zedelghem  thanks for this feedback! Just to confirm, you're referring to VSC's audio cue triggered by cell completion, not something 3rd party that's somehow triggered, right? Secondly, can you please post a screengrab video of the pain point scenario (20 finishing quickly)? Important for me to get that in order to assess. Also just flagging that I'm out until late dec/early jan. Thanks!

**Comment by AFre100** [comment]
Hi @Zedelghem , I'm the sound designer for these products — can you please post a screenrecording (with sound) of many cells triggering the audio cue, as you described? Thanks!
