### ISSUE TITLE
codespace not updating

### ISSUE THREAD

**Issue by englandep** [microsoft/vscode#233077]
my cs50.dev code space isn't updating or allowing me to run any commands in the terminal

Version: 1.95.1
Commit: 65edc4939843c90c34d61f4ce11704f09d3e5cb6
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.6 Safari/605.1.15
Embedder: codespaces

**Comment by bpasero** [comment]
It looks like this is caused by the Codespaces extension. Please file the issue in the [Codespaces Discussion Forum](https://github.com/community/community/discussions/categories/codespaces). Make sure to check their issue reporting template and provide them relevant information such as the extension version you're using. See also our [issue reporting guidelines](https://aka.ms/vscodeissuereporting) for more information.\n\nHappy Coding!
