### ISSUE TITLE
Can't open vscode online

### ISSUE THREAD

**Issue by A-little-bit-of-data** [microsoft/vscode#233042]
ADD ISSUE DESCRIPTION HERE

Version: 1.95.1
Commit: 65edc4939843c90c34d61f4ce11704f09d3e5cb6
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
Embedder: github.dev

By entering` . `Or change com to dev to open `https://github.com/apache/spark/tree/v3.5.1`, the error 
`Unable to resolve resource vscode-vfs://github%2B7b2276223a312c22726566223a7b2274797065223a342c226964223a2276332e352e31227d7d/apache/spark`

It will also recommend installing the "GitHub Repositories" extension, and after clicking Install, an error message will be reported
An error occurred while installing the "GitHub Repositories" extension.

**Comment by joyceerhl** [comment]
This should be fixed in the latest Insiders after the github.dev CORS allowlist was updated to accommodate a new endpoint target for fetching extensions. I verified that loading https://github.dev/apache/spark/tree/v3.5.1 works with VS Code Insiders in the browser. Please let us know if this still repros.
