### ISSUE TITLE
Color picker is displayed in Source Control text field

### ISSUE THREAD

**Issue by AdamWr** [microsoft/vscode#233193]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.96.0-insider (user setup)
Commit: 76c27ee9ddaf998e5129418b5aba2af1d569cf50
Date: 2024-11-06T05:04:43.322Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.26100

Steps to Reproduce:

1. Initialize git repository
2. Open Source Control
3. Add a `Fix #123456` as a message
4. Color picker is displayed

<details><summary>Screenshot</summary>

![Image](https://github.com/user-attachments/assets/065c3be5-d73a-41d2-abbe-bb61555505aa)

</details>

I'm not sure if it's a bug or just a new feature, but it's not displayed in stable build `1.95.1`.
If it's done intentionally, then I think that it would be nice to have an option to disable it in `Source Control` text field :)

https://github.com/user-attachments/assets/3547ed49-05b6-43b9-b33a-9acca90206c8

**Comment by lszomoru** [comment]
@aiday-mar, this looks like a bug. Could you please take a look? Thanks!

**Comment by aiday-mar** [comment]
Hi @lszomoru thanks for the ping. This is happening because yesterday we enabled default color decorators by default in VS Code insiders. I think it would make sense to disable this setting for the special case when we are inside of the SCM view because users will often reference issue numbers in the SCM view. I'll make that change.
