### ISSUE TITLE
Consider suppressing the workspace tsserver.js file missing until npm/yarn install commands are finished

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#233290]
I've been seeing this a lot recently:

![Image](https://github.com/user-attachments/assets/10c4b21b-7195-4de6-a634-1e32727c0515)

The TS extension could use the new `shellIntegration` API and associated events here in order to suppress warning the user when it's gone purely because node modules are being reinstalled.

**Comment by mjbvz** [comment]
This should only happen when the TS server actually needs to start. Most commonly this means that a JS/TS file is open, but now it can also be that you have a js/ts code block in your chat

For editors, it  is important to let the user know that their configured version of TS is not being used because this will affect what the user sees. We probably shouldn't care about the TS version for chat code blocks, but I also don't want to spin up a whole separate server just to support them in these cases

Closing as by-design/not worth engineering work
