### ISSUE TITLE
ターミナルを再アクティブ化しています...

### ISSUE THREAD

**Issue by RyujiHata** [microsoft/vscode#233493]
Type: <b>Bug</b>

ターミナルを再アクティブ化しています...
上記の通知が続いており、いつまで経っても終わらず、ターミナルが使えません。
何度かVSCodeを再起動しても、PCを再起動しても直りません。
どうすればよろしいでしょうか。

VS Code version: Code 1.95.2 (e8653663e8840adaf45af01eab5c627a5af81807, 2024-11-07T11:07:22.054Z)
OS version: Darwin x64 21.6.0
Modes:
Remote OS version: Linux x64 6.10.11-linuxkit

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: unavailable_off<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (13.68GB free)|
|Process Argv|--crash-reporter-id 9b905864-f12c-4668-a0fa-28e00916a067|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|コンテナー docker-python-jupyterlab (docker-python) @ desktop-linux|
|OS|Linux x64 6.10.11-linuxkit|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 0)|
|Memory (System)|7.66GB (6.66GB free)|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-python-indent|Kev|1.18.0
jupyter-keymap|ms-|1.1.2
remote-containers|ms-|0.388.0
pyformat|giy|1.0.2
vscode-docker|ms-|1.29.3
vscode-language-pack-ja|MS-|1.95.2024103009
debugpy|ms-|2024.12.0
python|ms-|2024.18.1
vscode-pylance|ms-|2024.11.1
jupyter|ms-|2024.10.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.21
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
autodocstring|njp|0.6.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
724cj586:31013169
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
nativeloc1:31134641
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013

```

</details>

**Comment by Adam877773** [comment]
Subject: Wishing You All the Best

Dear [Recipient Name],

I hope this email finds you well. I wanted to take a moment to wish you all the best. 

Sincerely,

[Your Name] 



-------- Oryginalny adres e-mail -------
Z: "vs-code-engineering[bot]" ***@***.***>
Wysłano: 9 listopada 2024 18:48:10 CET
Do: microsoft/vscode ***@***.***>
DW: Subscribed ***@***.***>
Temat: Re: [microsoft/vscode] ターミナルを再アクティブ化しています... (Issue #233493)


この号を作成していただきありがとうございます。

しかし、説明文が英語ではないので、私たちが取り組むのは大変です。可能であれば、この問題を英語に編集してください。新しいコメントを追加したり、新しい問題を作成したりするのではなく、既存の問題を編集してください。

残念ながら、自動翻訳サービスでは、ソフトウェアの問題を効果的に伝えるために必要な専門用語を処理できないため、当社の技術に精通した人間の翻訳者を見つけて翻訳を支援することをお勧めします。

そうでなければ、この問題は翻訳が必要とマークされており、コミュニティメンバーが翻訳を手伝ってくれるかもしれません。

---
Thanks for creating this issue!

Unfortunately, as the description is not in English, it&#39;s hard for us to work on. If possible, please edit the original issue to be in English.

In our experience, automatic translation services are not able to handle the technical language needed to effectively communicate about software issues, so we recommend finding a human translator who is familiar with our technology to help.

Otherwise, we have marked this as needing translation and a community member may be able to help out.
&lt;!-- translation_requested_comment --&gt;

**Comment by Adam877773** [comment]
Subject: Re: [microsoft/vscode] Terminal Reactivating... (Issue #233493)

Dear VS Code Engineering Team,

Thank you for reaching out! 

I understand the importance of clear communication and appreciate your request to provide an English translation for this issue. I'm happy to assist. 

Could you please provide the original Japanese text within this email? I will do my best to translate it accurately, ensuring the technical language reflects the intent of the issue. 

Let's work together to resolve this! 

Best regards,
[Your name] 



-------- Oryginalny adres e-mail -------
Z: "vs-code-engineering[bot]" ***@***.***>
Wysłano: 9 listopada 2024 18:48:10 CET
Do: microsoft/vscode ***@***.***>
DW: Subscribed ***@***.***>
Temat: Re: [microsoft/vscode] ターミナルを再アクティブ化しています... (Issue #233493)


この号を作成していただきありがとうございます。

しかし、説明文が英語ではないので、私たちが取り組むのは大変です。可能であれば、この問題を英語に編集してください。新しいコメントを追加したり、新しい問題を作成したりするのではなく、既存の問題を編集してください。

残念ながら、自動翻訳サービスでは、ソフトウェアの問題を効果的に伝えるために必要な専門用語を処理できないため、当社の技術に精通した人間の翻訳者を見つけて翻訳を支援することをお勧めします。

そうでなければ、この問題は翻訳が必要とマークされており、コミュニティメンバーが翻訳を手伝ってくれるかもしれません。

---
Thanks for creating this issue!

Unfortunately, as the description is not in English, it&#39;s hard for us to work on. If possible, please edit the original issue to be in English.

In our experience, automatic translation services are not able to handle the technical language needed to effectively communicate about software issues, so we recommend finding a human translator who is familiar with our technology to help.

Otherwise, we have marked this as needing translation and a community member may be able to help out.
&lt;!-- translation_requested_comment --&gt;

**Comment by justschen** [comment]
looks like this is related to notifications. @RyujiHata I'll close this as stale, but let me know if you still see this.
