### ISSUE TITLE
tssserver.log enabled installation wide

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#23344]
re #23187

* have a small workspace without settings
* look at server log, get prompted about missing setting, follow steps
* 🐛 the setting is stored globally enabled logging for *all* my ts project

**Comment by mjbvz** [comment]
Thanks. I agree this is not ideal but it was by-design. The server log setting is a user-specific setting instead of one that is meant to be shared among team or project members. That's why I was hesitant to write it to the `.vscode/settings.json`.

Let me know if you have any suggestions on how this could be handled better

**Comment by jrieken** [comment]
How about not making it a setting but just stored state via [`workspaceState`](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L3390)

**Comment by mjbvz** [comment]
Interesting option. I have a few concerns with that approach though:

* The `"typescript.tsserver.trace"` setting. Having trace be a setting but logging be workspace state felt confusing
* Less knowledge of when logging is enabled or disabled for users. Having a setting makes it explicit that logging is enabled for you. We could look at exposing logging status somewhere in the UI,  but using a setting makes it more clear using logging is enabled or not

**Comment by mjbvz** [comment]
Closing as-designed. As noted, the current solution is not ideal, but this is not an option we hope to have users messing around with too often, and a user setting seems to offer the most consistent behavior here
