### ISSUE TITLE
Keybinding customization - only shows the keybindings of activated extensions

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#23356]
The `vscode-tslint` extension is contributing key bindings. However, these keybindings are only available for customization in the editor, once the extension is activated and the user has opened a TypeScript file.

The user should be able to customize keybindings independent from whether an extension is activated or not.

**Comment by sandy081** [comment]
@jrieken Any idea why the command registry is not having the commands until activation?

**Comment by jrieken** [comment]
@sandy081 The keybinding comes in right on startup (set brk-point here: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/keybinding/electron-browser/keybindingService.ts#L482). That binds the identifier of an existing or future command to some key/keycombination. 

The command itself, the id->function-thing, comes in when someone called `registerCommand`, so when becoming active. I don't think you should validate the existing of a function but should just rely on the declarative part.

**Comment by sandy081** [comment]
@jrieken Sorry if I am not clear. It's not about keybindings.. its about commands with no keybindings. 

When a user open keybindings editor, he does not see those commands without keybindings from an extension which is not active yet. This will confuse the user. Since command are registered descriptively also, is not it possible to get the information from there? I understand that Command registry is a registry of `command id -> Function` which will not be available until the extension is activated. Do we have some thing like command extension point registry from where we can get descriptive details?

**Comment by sandy081** [comment]
Is the `MenuRegistry` which you mentioned previously will have these details?

**Comment by jrieken** [comment]
Yes, `MenuRegistery` contains everything an extension defined in the [`commands`](http://code.visualstudio.com/docs/extensionAPI/extension-points#_contributescommands) section and in the [`menus`](http://code.visualstudio.com/docs/extensionAPI/extension-points#_contributesmenus) section. It is similar to a keybinding as that it registers a user-gesture (selecting a button) to run a command.

**Comment by sandy081** [comment]
But there is a catch that this will not give me command description that can tell me that command takes args or not.. Currently I am excluding all commands with args from Keybindings editor.

Also is CommandsRegistry.getCommands() is a sub set of MenuRegistry.getCommands() ?

**Comment by jrieken** [comment]
CommandRegistry holds commands which is a `id->Function` mapping. MenuRegistry holds menu items/command actions which are `ui-description->id` mapping. The latter are called commands (`ICommandAction`) because they invoke commands and I see how that is slight confusing. They have nothing in common, but join the id-parts

```
command: id -> function // dynamic, involves code

keybinding: key-event-description -> id // declarative

command_action: ui-description -> id // declarative

menu: [command_action, command_action] // declared an arrangement of command_actions
```

**Comment by sandy081** [comment]
Even though `MenuRegistry` has all registered commands through `commands` contribution point, it does not tell if these commands take arguments or not. This information is available only after registering to `CommandRegistry` which happens after extension activation. So, it would be nice if `commands` contribution point also takes `args` description.

**Comment by jrieken** [comment]
> So, it would be nice if commands contribution point also takes args description.

Then the same applies to the `keybindings` contribution point
