### ISSUE TITLE
Purpose of `authentication` extension contribution point is unknown

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#233757]
Type: <b>Bug</b>

The documentation at https://code.visualstudio.com/api/references/contribution-points omits the `authentication` contribution point, which is defined in [authentication.contribution.ts](https://github.com/microsoft/vscode/blob/5cae08d2afa91f2703d1f5f3e4dd8ad358501424/src/vs/workbench/contrib/authentication/browser/authentication.contribution.ts#L66-L74).

The built-in github-authentication and microsoft-authentication extensions use it in their package.json files, and the schema for that file recognizes it as a valid entry of the `contributes` section.

However it is unclear how (if at all) an extension that registers an AuthenticationProvider benefits from declaring this in its package.json. I have published two such extensions, neither of which do this, yet both seem fully functional.

VS Code version: Code - Insiders 1.96.0-insider (399779942db4d7ab1bd6f6ae976482d0020f10ca, 2024-11-13T05:04:32.098Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by TylerLeonhardt** [comment]
You're correct. At this time, there really isn't a lot you get from declaring the contribution. The contribution really only provides these features at the moment:
* Automatic creation of an activation event (instead of using the auth activation event directly)
* It'll show up in your extension's features
* Core has an API called `authenticationService.declaredProviders` which gives back all providers declared in `package.json`s. We use this to look for GitHub & Microsoft auth to use with Settings Sync. Outside of really those two providers, this isn't really important.

I would like to change this and have this follow our other contribution stuff, however. Plus, maybe in the future we can provide an API that makes use of this or displays the providers somewhere (even if they have not yet been activated).

**Comment by gjsjohnmurray** [comment]
Thanks. Closing this.
