### ISSUE TITLE
Perforce for VS Code extension - causes "Activating Extensions ..." indefinitely

### ISSUE THREAD

**Issue by amal-khailtash** [microsoft/vscode#234119]
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.95.3
Commit: f1a4fb101478ce6ec82fe9627c43efbf9e98c813
Date: 2024-11-13T14:50:04.152Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Linux x64 4.18.0-553.22.1.el8_10.x86_64

Steps to Reproduce:

1. I used extensions bisect and that identified this extension causing "Activating Extensions..." indefinitely.
2. Disabling this extension, makes other extensions work properly.

**Comment by nandordudas** [comment]
Sporadic Devcontainer loading failures in WSL

When using WSL with Devcontainer:

Initial setup and rebuilds work normally. After TypeScript server stopped, reloading window resulted in "Activating extensions..." hang. Unable to reopen Devcontainer afterward. Extension bisect (both non-WSL/WSL) identified shellcheck, but issue persists with only `WSL` and `Dev Containers` enabled.

Environment:

WSL
VS Code with Devcontainer
Extensions: Tested with minimal set (WSL + Dev Containers)

Note: Extension bisect performed in both WSL and non-WSL environments, but not in Devcontainer due to access issues. Reproduced on multiple devices.

https://github.com/user-attachments/assets/7c481c0c-1e4d-426a-a2ea-6453c475b316
