### ISSUE TITLE
Crash code 5

### ISSUE THREAD

**Issue by gabrielpondc** [microsoft/vscode#234159]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.85.2
- OS Version: Mac OS 15.1 (24B83)

Steps to Reproduce:

1. I create the jupyter notebook in Download folder and paste the huge data
2. then the vscode crashed by code 5 
3. every time i open this folder it will automatically open by last checkpoint and crashed every time when i open this folder  

[crashinfomation.txt](https://github.com/user-attachments/files/17811349/crashinfomation.txt)

**Comment by gabrielpondc** [comment]
> Thanks for creating this issue! It looks like you may be using an old version of VS Code, the latest stable release is 1.95.3. Please try upgrading to the latest version and checking whether this issue remains.
> 
> Happy Coding!

It's not a bout the version if i update the new version still have the crash in this folder

**Comment by rebornix** [comment]
@deepak1556 any idea of what might go wrong with the error code 5? I wonder if we have a way to avoid repeated crashes on window reloads.

**Comment by deepak1556** [comment]
It is usually a crash due to the javascript heap limit reached or oom from the system.

Can you follow the steps before to capture a heap profile,

* From a fresh instance that is open a different folder using `code <some-folder>`, run `Developer: Toggle Developer Tools`
* Switch to the `Memory` tab and select the option as shown in the screenshot below
 ![Image](https://github.com/user-attachments/assets/a0a32e6c-c350-4890-81e3-2c29a8513f75)
* Start the recording
* Open the folder that triggers the crash
* Save the profile and attach it to this issue

**Comment by gabrielpondc** [comment]
ok thx, i will try this way if i met it again
