### ISSUE TITLE
Have contextual notification in encoding status bar item

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#23428]
Testing #23322

If `files.autoGuessEncoding` is `false` and the detected encoding is different than the one that we have opened the file with, it would be great to see some sort of inline notification around the encoding status bar.

Something like GitHub's notifications: 

![image](https://cloud.githubusercontent.com/assets/22350/24408185/3dd7959a-13cd-11e7-87bb-d45741f54891.png)

**Comment by bpasero** [comment]
I like that!

**Comment by gingerbeardman** [comment]
Closing issues like this, including some I filled myself, is a real 🖕 to users who ate getting to help you improve the app. 

This makes me want to not spend time reporting issues, requesting improvements that I need for my workflow, and makes me think about moving to another editor which does have this feature.

**Comment by bpasero** [comment]
@gingerbeardman sorry to hear that. See https://github.com/Microsoft/vscode/wiki/Issue-Grooming#out-of-scope-feature-requests for rationale behind this.

**Comment by gingerbeardman** [comment]
@bpasero I disagree with that rationale. The only benefit to closing issues as "out-of-scope" is to bring down the issue count to make it easier for you guys to deal with. You're kidding yourselves by sticking your head in the sand.

What happens after the 24 months when the roadmap has changed considerably? These (currently) out-of-scope issues may then by in-scope, but because they've been closed they'll not be considered. 

I think this "out-of-scope" is a really short sighted, poor decision that benefits only your working methodology.
