### ISSUE TITLE
terminal chat can cause the window to freeze

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#234595]
1. Use terminal chat (will try to have more specific repro steps)
2. See the UI freeze, with the following in the dev tools console
3. Eventually, see the unresponsive dialog, prompting to reload the window

![Image](https://github.com/user-attachments/assets/3dfc0c9f-9453-479a-a5dd-e0250a9c077f)
![Image](https://github.com/user-attachments/assets/cd7b9e9b-4cda-49cb-bc9b-9da98a1ccea0)

**Comment by meganrogge** [comment]
This time, it just happened when I had terminal chat open in insider's and started debugging 🤔

**Comment by roblourens** [comment]
I haven't been able to repro this. It would help if you can share the full stack trace! The screenshot is only showing the preview. If that scroll is triggered by the ChatWidget `scrollToEnd` code, then maybe it would be fixed by https://github.com/microsoft/vscode/issues/234596? But I'm guessing that it won't be.

**Comment by meganrogge** [comment]
Will close until I see it again
