### ISSUE TITLE
PHP commenting is displaying as HTML comments in a pure php file

### ISSUE THREAD

**Issue by sagisar1** [microsoft/vscode#234622]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.95.3
- OS Version: Windows 10

Hello, after updating vscode, when i try to do CTRL + / in order to comment a line in php file, it comments as HTML comments 

instead of normal php comments
//

I have the built in extenstions enabled, and external extension PHP Debug by xdebug.org
Also I had php extension pack, disabled it, removed it, and the problem is still happening.

Steps to Reproduce:

1. open vs code
2. create a pure php file with extenstion .php
3. try to comment with CTRL +/
4. recieve HTML comments instead of php comments

**Comment by RedCMD** [comment]
this has always been the case

however there is a new bug
ctrl+/ toggle comment doesn't work after opening a blank php file for the first time
it used to work in 1.75.1, but broke in 1.76.0

**Comment by sagisar1** [comment]
@RedCMD I don't understand you man. for me it worked at least until version 1.94. so no relation to what you said

**Comment by RedCMD** [comment]
![Image](https://github.com/user-attachments/assets/5e098835-0c0b-4ad6-a31d-cd33d21a0c58)
as you can see, the language is set to html

if I set a php tag it works
![Image](https://github.com/user-attachments/assets/ebaca0c0-b75a-4056-ace0-8cc74c7dce34)

> I don't understand you man
https://github.com/microsoft/vscode/issues/234722

**Comment by sagisar1** [comment]
@RedCMD what extenstions do you have installed?
Because now, I have "PHP Debug" and "PHP Extenstion Pack" by Xdebug, and my <?php looks different than yours in the color as yuo can see in the image below, maybe this is the cause of the problem  
![Image](https://github.com/user-attachments/assets/73c55481-8681-491a-a4b0-d2928deef568)

**Comment by Link1515** [comment]
I encountered the same issue as well. I'm also using Windows 10 and VSCode 1.95.3.

**Comment by aeschli** [comment]
For this to work you need to install a PHP extension. The built-in PHP support is very basic.

**Comment by sagisar1** [comment]
I am sorry @aeschli , but i did install php extensions rather than the basics one, and I did mention that in my post of the issue, so please do not close the issue yet

**Comment by RedCMD** [comment]
report to the php extension
if they deem it a VSCode issues @ aeschli will reopen this

**Comment by Link1515** [comment]
Hey, @sagisar1. I had the same issue as shown in your screenshot, but I managed to fix it!

Here's what I did:

Press `F1` and run command `Developer: Inspect Editor Tokens and Scopes`

In my case, I noticed the language was detected as HTML instead of PHP.

![Image](https://github.com/user-attachments/assets/c2ada489-504b-4c90-a080-12b7cb825c73)

Next, I ran the command `Extensions: Disable All Installed Extensions`, and the PHP syntax highlighting started working again.

![Image](https://github.com/user-attachments/assets/d4e8edf6-e9fb-43c0-974a-c5252c895b43)

To identify the culprit, I re-enabled my extensions one by one. It turned out that the [EJS Language Support](https://marketplace.visualstudio.com/items?itemName=leonzalion.vscode-ejs) extension was causing the issue in my case.

If you're experiencing something similar, you can follow these steps to troubleshoot and identify which extension might be breaking PHP highlighting for you.

Hope this helps! 😊

**Comment by sagisar1** [comment]
Hi @Link1515 , I opened : `Developer: Inspect Editor Tokens and Scopes` and I saw the same thing that you have shown in your screenshots.
I didn't disable all the extensions, I just have disabled the ejs extenstion and like a miracle the comments were working again.
However, I will open a new issue (if doesn't exist) regarding the ejs extension, because now we know that this is what makes the problem 

Anyway, thank you so much for that! My problem is now solved when I disabled the ejs extension.

**Comment by Link1515** [comment]
@sagisar1 You're welcome! I've been struggling with this issue for quite a while as well. 😂

**Comment by sagisar1** [comment]
Hello @RedCMD , now knowing that the ejs extension creates the conflict with php,  who should I report to now? I think it should be ejs or vs code, but I think that is more of vs code related

**Comment by RedCMD** [comment]
EJS first
if they find it to be a VSCode issuse, then it'll come back here
