### ISSUE TITLE
Test configuring allowed extensions

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#234993]
Refs: https://github.com/microsoft/vscode/issues/84756

- [x] Mac @Tyriar
- [x] Win @benibenj
- [x] Linux @eleanorjboyd

Complexity: 5

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23234993%0A%0A&assignees=sandy081)

---

Please refer to the documentation of this feature [here](https://github.com/microsoft/vscode-docs/blob/c78318cd6f3c6953eab911fdb59dc98252e6b8d2/docs/setup/enterprise.md#L21) and test if this feature is working as mentioned in the documentation. 

Also provide feedback about the documentation if there is anything not clear or you think it can be improved.

**Comment by isidorn** [comment]
For this test plan item it is not expected that you actually set a group policy (this is optional).
Setting the group policy is covered by this test plan item https://github.com/microsoft/vscode/issues/235002

**Comment by eleanorjboyd** [comment]
Notes from the documentation:

"If you block an extension or version that is already installed, the extension is disabled and cannot be installed." This line I find a bit confusing since its already installed but then says it cannot be installed? Maybe the end should be, cannot be reinstalled or cannot be updated?

```
// Do not allow docker extension
    "ms-azuretools.vscode-docker": false,
```
What is the use case for this given it could just be left off the list and it would handle blocking it?

What happens if a person is not on a version >=1.96 but has the allowed extensions attribute? Will it be greyed out and not have any impact?

**Comment by Tyriar** [comment]
> What is the use case for this given it could just be left off the list and it would handle blocking it?

@eleanorjboyd you can invert the list as well with `"*": true` to turn it into a block list

**Comment by sandy081** [comment]
> "If you block an extension or version that is already installed, the extension is disabled and cannot be installed." This line I find a bit confusing since its already installed but then says it cannot be installed? Maybe the end should be, cannot be reinstalled or cannot be updated?

@eleanorjboyd Good point, can you please file an issue in documentation (vscode-docs repo)?

CC @ntrogh

**Comment by ntrogh** [comment]
@eleanorjboyd @sandy081 Updated the docs to remove that last part. Thanks for raising this.
