### ISSUE TITLE
Somewhat unexpected choice of cells ran

### ISSUE THREAD

**Issue by aiday-mar** [microsoft/vscode#235078]
Testing #235049

- Consider the following example:

https://github.com/user-attachments/assets/7c2c3f27-1c4b-43b5-b2b6-93a901589a57

- When I click on the first `Run in Cells` button, both code cells with the print statement run. When I click the `Run in cells` on the second markdown cell, only the second one runs. 
- I think I was not expecting in the first case, for both code cells to run. I was expecting only the ones between the current markdown cell and the next one to run. 
- Maybe this confusion could be cleared up with the following:

Have a button `Run cells under header`
And a button `Run cells after this markdown cell``

The button `Run cells under header` would be present only on the markdown cells that contain a markdown header.

**Comment by Yoyokrazy** [comment]
I'm making some changes to fix the other two bugs filed, but will maintain this behavior. In the work I've done, there's been an implicit assumption on my end that the Run Cells in Section action will always refer to the nearest enclosing parent section. In your example above, you have the following 
1. md header
2. code
3. md plaintext
4. code

Using the run in section on cell (1) will execute cells 2/4. Using the button on cell (3), the same cells will be executed. Going to close this as expected behavior for now, I can revisit this if users start to give feedback to support a change in behavior.
