### ISSUE TITLE
Copy in settings vs keybindings editor

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#23500]
Testing #23287

Copy action in settings editor, copies and pastes the settings to user's settings
Copy action in keybindings editor, only copies, user has to open the keybindings.json file and paste it themselves.

User Experience is not consistent

**Comment by sandy081** [comment]
There are lot of dis-similarties between Settings and Keybindings which makes sense because they are two different UIs. Former has settings.json file is always shown and has complete editing 
experience. Where as later one is a complete UI. 

Copy in keybindings editor does not always need to be copied into keybindings json file. User can always paste it anywhere.
