### ISSUE TITLE
Cells ran should change as headers are added and removed

### ISSUE THREAD

**Issue by aiday-mar** [microsoft/vscode#235086]
Testing #235049

- I believe this could be related to https://github.com/microsoft/vscode/issues/235083
- Open an MD file with a cell (A) that has a header
- Click on `Run cells in section` on cell (A) - code cells below it are ran
- Choose the next MD cell (B) below cell (A) and add a header there (make sure it previously didn't have one)
- Click on `Run cells in section` on cell (A) - all the same code cells below it as before are ran
- I would expect only the code cells between cell (A) and (B) to be ran
- It seems as though maybe the cell content changes are not taken into account in deciding what cells to currently run in the section 🐛 

https://github.com/user-attachments/assets/f0939cf0-8e78-4ae6-80b7-9cf1fb589ace

**Comment by rebornix** [comment]
I think it shares the same root cause as https://github.com/microsoft/vscode/issues/235083#issuecomment-2515448915. 

@Yoyokrazy maybe if the markdown cell is in editing mode, and users trigger Run in Section, we always compute the folding/toc before running the section. I'll put this in Nov milestone first, we can postpone if the change is big.
