### ISSUE TITLE
Debug console doesn't show stderr output

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#2350]
- follow steps in https://github.com/Microsoft/vscode/issues/2231
- debug the program

You see:
![capture](https://cloud.githubusercontent.com/assets/1931590/12582526/05b2278c-c43e-11e5-841e-2b0546c84108.png)

**Comment by dbaeumer** [comment]
It worked when debugging the second time. Might be a timing issue. One thing to note from my experiences with child processes: when 'exit' is received not all output from a child process is processed. You need to listen on 'close' which is sent when the streams (stdout and stderr) are flushed and read.

**Comment by isidorn** [comment]
If it is the issue that Dirk is suspecting this should be done in the adapter I believe. Forwarding to @weinand

**Comment by SofianHn** [comment]
I have seen this as well, in the very first run stderr is not shown, then it worked fine.

**Comment by weinand** [comment]
@dbaeumer since mono-debug is relying on sdb, I have no access to the streams that sdb is opening to mono or to the mono process itself. However, I've added a small delay in the debug adapter's shutdown code to increase the likelihood that sdb has enough time to read all the data from mono and pass it to the adapter.

**Comment by dbaeumer** [comment]
Verified that it is still not working. According to Andre not fixable.

**Comment by weinand** [comment]
Can only be fixed in sdb.
