### ISSUE TITLE
Quick fixes don't work if 'typescript.tsdk' doesn't point to a node_modules-parented folder

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/vscode#23511]
As I try newer versions of TypeScript that aren't `npm install`-ed, I find quick fixes haven't been working. Is there a reason they're disabled by default?

@mjbvz @mhegazy

**Comment by mhegazy** [comment]
@DanielRosenwasser, in your settings.json file set:

```json
	"typescript.tsdk_version": "2.2.0",
```

along with `"typescript.tsdk"`.

@mjbvz we need a cleaner way of doing this, how about adding a new command to the server to return the version? we can back port this to 2.1 and 2.2 if needed.

**Comment by mjbvz** [comment]
Since VSCode 1.8, the `tsdk_version` setting isn't officially exposed/supported anymore. We now always try to pick up the version from the `package.json` located in the `typescript.tsdk` path.  The only case this does not work is when you are using a version of tsserver that does not come from some `node_modules` like location

I'm hesitant to rely on a tsserver command for the version info because we've seen several issues where tsserver crashes on startup. What are the use cases for non-npm installed versions of typescript?

**Comment by mhegazy** [comment]
> What are the use cases for non-npm installed versions of typescript?

Mainly us working on TS.

**Comment by DanielRosenwasser** [comment]
Yes, typically when I'm prototyping features like quick fixes that actually go into VS Code. 😉

**Comment by mjbvz** [comment]
@DanielRosenwasser + @mhegazy Can you symlink together an environment together that looks like an npm installed version of TypeScript?

**Comment by mhegazy** [comment]
I suppose we can make our build create a synlmlink to the package.json. Should not be that big of a change.

**Comment by mjbvz** [comment]
yes, I think that would work better. Here's the logic we use for picking up the version for what it's worth: https://github.com/Microsoft/vscode/blob/master/extensions/typescript/src/typescriptServiceClient.ts#L748

All we need is a package.json that contains:

```json
{
    "version": "2.2.3"
}
```
