### ISSUE TITLE
Allowed extensions policy - improve warning message

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#235127]
Testing #235002

This does not sound good to me - "they are configured to be in...". Could we polish the warning message? 
Should we mention "group policy" instead of "configuration"?
Should we also include a link to learn more about the group policy? 

![Image](https://github.com/user-attachments/assets/44c0cab7-2798-40e2-8090-55e13e0c14de)

**Comment by sandy081** [comment]
Changed the message to `Some extensions are disabled because they are not allowed by your system administrator.`. 

> Should we also include a link to learn more about the group policy?

I do not think it is helpful given that users cannot take any action. It would be helpful to show a custom link to request access for the extension from the administrator. There is a separate issue for this.
