### ISSUE TITLE
`"terminal.integrated.tabs.description": "${shellCommand}"` doesn't include shell-command in description

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode#235135]
Testing #234760

repro: 
1. set settings: 
```
  "terminal.integrated.tabs.title": "${cwd}",
  "terminal.integrated.tabs.description": "${shellCommand}"
```
2. create new terminal
3. :bug: see how the terminal tab name is there but not the description: 

![Image](https://github.com/user-attachments/assets/83bb8e18-e152-4d6f-9875-1b4202ee9274)

Version: 1.96.0-insider
Commit: 5d6531aabba3abfbc263c1e17e965db97df9210f
Date: 2024-12-03T05:13:15.471Z
Electron: 32.2.6
ElectronBuildId: 10629634
Chromium: 128.0.6613.186
Node.js: 20.18.1
V8: 12.8.374.38-electron.0
OS: Darwin arm64 24.1.0

**Comment by ulugbekna** [comment]
Not sure. These're the settings related to terminal I have: 

```
  "terminal.integrated.suggest.enabled": true,
  "terminal.integrated.suggest.quickSuggestions": true,
  "terminal.integrated.defaultProfile.osx": "zsh",
  "terminal.integrated.environmentChangesRelaunch": false,
  "terminal.integrated.gpuAcceleration": "on",
  "terminal.integrated.macOptionIsMeta": true,
  "terminal.integrated.showExitAlert": false,
  "terminal.integrated.tabs.title": "${cwd}",
  "terminal.integrated.tabs.description": "${shellCommand}"
```

**Comment by Tyriar** [comment]
@ulugbekna if you hover the tab do you see shell integration activated?

![Image](https://github.com/user-attachments/assets/680a1ce6-9798-4e68-89b1-e16a67977eff)

You could also try manually installing to see if that makes a difference:

https://code.visualstudio.com/docs/terminal/shell-integration#_manual-installation

**Comment by ulugbekna** [comment]
@Tyriar 

> if you hover the tab do you see shell integration activated?

Yes:

![Image](https://github.com/user-attachments/assets/204dac67-df1a-4c1a-bd85-0f78ffc8e5b1)

**Comment by Tyriar** [comment]
@ulugbekna shell integration activated is actually a little ambiguous, it'll show up when any shell integration sequences comes in not all of them. This can actually happen with shells sending the non-vscode style shell integration as well.

I suspect this problem is related to your shell integration not fully activating. To investigate further you could enable trace logging and check the `Pty Host` channel, this should tell us info on the process getting launched as well as whether the SI sequences are going through.
