### ISSUE TITLE
Toggle Sidebar Visibility and Go to Line display same key mapping in Arabic keyboard

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode#23513]
Testing #23315

Windows 10, Arabic (Lebanon) keyboard

Both commands display the keybinding as `Ctrl + ل`, but Toggle Sidebar Visibility should actually map to `Ctrl + لا`

![image](https://cloud.githubusercontent.com/assets/762848/24436440/5706237e-13f0-11e7-9807-db4696ed47d0.png)
![image](https://cloud.githubusercontent.com/assets/762848/24436467/82ea00b4-13f0-11e7-9896-eba27189ddca.png)

**Comment by alexandrudima** [comment]
Oh, wow, such a great find!

I've run `F1 > Developer: Inspect Key Map` and here are the results coming in from the native C++ module for these keys:

```
	"KeyB": {
		"vkey": "VK_B",
		"value": "لا",
		"withShift": "لآ",
		"withAltGr": "",
		"withShiftAltGr": ""
	},

	"KeyG": {
		"vkey": "VK_G",
		"value": "ل",
		"withShift": "لأ",
		"withAltGr": "",
		"withShiftAltGr": ""
	},
```

I've noticed a clue:
```js
// character produced by B
"لا".length // 2
"لا".charAt(0) // ل
"لا".charCodeAt(0) // 1604

// character produced by G
"ل".charCodeAt(0) // 1604
//
```

The bug is that the keyboard mapper only considers the first UTF-16 char code in a produced value instead of the entire produced value string. To make things a bit more complicated, it happens that in this case it is the exact same character produced by a different key :)
