### ISSUE TITLE
extension dependencies

### ISSUE THREAD

**Issue by eleanorjboyd** [microsoft/vscode#235181]
Testing #234993

I disabled python extension (via allow list), but allowed pylance. It is weird here since the pylance extension depends on the python extension (as seen here). I feel like that should be displayed that the allow list is why the python extension and pylance extension are greyed out. Also is it possible to have a extension installed that doesn't have its dependencies or does this signal the pylance extension isn't installed? Would be good to clarify with a message why the pylance extension isn't installed / what state it is in.

```
    "extensions.allowed": {
        "ms-python.vscode-pylance": true,
    }
```

![Image](https://github.com/user-attachments/assets/8440aa1a-ac98-46b5-8d04-0bcb31731aa8)

**Comment by sandy081** [comment]
I am seeing following for pylance when python extension is not allowed. 

![Image](https://github.com/user-attachments/assets/482d66cf-d6e3-454d-957d-fa600847804f)

I think this is clear that pylance is disabled because the extension it depends on is disabled and there is a link to navigate to that extension. When you go to original extension it shows the real information. 

Are you seeing anything different?
