### ISSUE TITLE
在Mac电脑中撤销、恢复不正常

### ISSUE THREAD

**Issue by asoiso** [Microsoft/vscode#23528]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T13:56:35.908Z)
- OS Version: Darwin x64 16.4.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.6.2|
|vscode-todo|MattiasPernhult|0.8.0|
|vscode-eslint|dbaeumer|1.2.8|
|webpack|jeremyrajan|2.0.0|
|docthis|joelday|0.4.3|
|quicktask|lkytal|2.4.1|
|vscode-todo-parser|minhthai|1.8.9|
|debugger-for-chrome|msjsdiag|2.7.0|
|vscode-evernote|rhapsodyn|0.1.0|;

---

Steps to Reproduce:

1. 输入 1 2 3 4 5 6 7 8 9 0；
2. Command + S 保存；
3. Command+Z，撤销5次，剩下的为1 2 3 4 5；
4. Command+Shift+Z，恢复不了。

**Comment by asoiso** [comment]
1. Enter "1234567890";
2. Command + S save;
3. Command+Z, 5 times, the remaining is 12345;
4. Command+Shift+Z, Can not recover.

**Comment by rmunn** [comment]
I can't reproduce this on Linux Mint 18 (based on Ubuntu Trusty 16.04.2). My VS Code version is also 1.10.2 (commit 8076a19fdcab7e1fc1707952d652f0bb6c6db331). I went through the same steps:

1. Add characters 1234567890 to a file, moving the cursor between each one so that each one counts as a separate edit.
2. Hit Ctrl+S to save.
3. Hit Ctrl+Z 5 times, leaving 12345 in my file.
4. Hit Ctrl+Shift Z 5 times.

But when I hit Ctrl+Shift+Z, it recovers all five characters (one at a time) that were undone after saving. So it's working fine for me.

My installed extension list, in case it's relevant, is:

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.6.2|
|Ionide-FAKE|Ionide|1.2.3|
|Ionide-Paket|Ionide|1.6.3|
|Ionide-fsharp|Ionide|2.25.2|
|Bookmarks|alefragnani|0.12.0|
|python|donjayamanne|0.6.0|
|json-tools|eriklynd|1.0.2|
|csharp|ms-vscode|1.8.0|
|mono-debug|ms-vscode|0.15.4|
|vscode-icons|robertohuertasm|7.4.0|
|Align|steve8708|0.2.0|;

**Comment by alexandrudima** [comment]
@asoiso I also cannot reproduce. Is this a problem of the keybinding? i.e. does it work when pressing Redo in the Edit menu. Is it possible you have some file watchers that would interfere with the file on disk. i.e. can you reproduce when doing in a new untitled file?

**Comment by alexandrudima** [comment]
Closing after a number of days without a response.
