### ISSUE TITLE
Reload stuck on Opening Remote

### ISSUE THREAD

**Issue by dailytabs** [microsoft/vscode#235450]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.95.3
- OS Version: Windows 11 Home

Steps to Reproduce:

1. Reload window (manually or via extension update).
2. "half" the time is gets stuck on "Opening Remote..."

Waiting for an excessive amount of time, greater than 5 minutes, will finally load the window.

Similar to: https://github.com/microsoft/vscode/issues/213302

Started for me a couple weeks ago. (spell checker was only modification and the problem still happened when I reloaded window after uninstalling spell checker ext).

Closing and re-opening always works fine, with zero delay.

(Help menu does not have the "Report Issue" entry referenced by the bug report template while the window is loading - might want to fix that.)

**Comment by brijaze** [comment]
I faced the same issue and found it to be the occurence of multiple SSH agents on my system. (one from a tool for remote sessions and one other)

Funny enough, I have never had problems until very recent, where VS Code got stuck during "Connection - You know the Setting up remote: .... Initializing....."
The solution for me and rest of the company was it the Remote-SSH: Settings
![Image](https://github.com/user-attachments/assets/4d50b769-d8c6-450b-a6f6-3dc7700c68fc)

Hardtyping the path to the OpenSSH exe file. Maybe Developers of VS Code could default to this, rather than the "command" SSH


Fun-fact:
When I/we opened the prompt and typed SSH -V
![Image](https://github.com/user-attachments/assets/98c19f92-b1f2-4e55-bfb6-b9b06b84b8a9)
I would random pick one of the SSH.EXE files available in different paths on the system.

We have on one other rare occation, seen that ssh-keygen generated a keypair, that only worked half the time, now I know why :D 

Hopefully, this will solve your problem too.

**Comment by joshspicer** [comment]
Thanks for taking the time to report an issue. @dailytabs, could you share your logs (`> Remote-SSH: Show Log` in the command palette) after reproducing the issue?  From there we can see if @brijaze 's workaround would be appropriate for you, or if something else is going on.
