### ISSUE TITLE
Allow to associate a file encoding per file path

### ISSUE THREAD

**Issue by duanehutchins** [microsoft/vscode#23570]
- VSCode Version: 1.11.0-insider
- OS Version: Windows 8.1-Pro

Here is a gif of the bug in action: 
![vscode-fileencode](https://cloud.githubusercontent.com/assets/1530028/24415489/a2e93236-13af-11e7-9b70-b74938f8c1fb.gif)
TXT Files refrenced: [iso-8859-1.txt](https://github.com/Microsoft/vscode/files/876495/iso-8859-1.txt) and [shift-jis.txt](https://github.com/Microsoft/vscode/files/876496/shift-jis.txt)

Steps to Reproduce:

1. Open the attached text files with the corresponding encoding.
2. Verify the characters display properly and the encoding is correct in the bottom-right corner of VS code.
3. (Re)Save the files using the same encoding.
4. Close the files.
5. Open the files normally (Without specifying the encoding).
6. The encoding used to open the files is not the same encoding used to save the files. The characters do not display properly.
7. Enabling `files.autoGuessEncoding` does not resolve the issue, but it does change which encoding is guessed.

Note that if I run `file -bi iso-8859-1.txt` from Git Bash, I can see the correct encoding is returned.

**Comment by bpasero** [comment]
@duanehutchins this is specifically why we introduced the `files.autoGuessEncoding` setting. If you are not having this enabled by default, we use the encoding configured in files.encoding for opening and saving files. The only exceptions are `UTF-8` with BOM or `UTF-16` with BOM. 

As for your 2 cases I filed https://github.com/aadsm/jschardet/issues/30 and https://github.com/aadsm/jschardet/issues/31

I leave this open to allow to store an encoding for a specific file path.

**Comment by GitMensch** [comment]
As #30857 was closed as a duplicate of (partially) this and there's a real relevance to be able to set the encoding via file-path (although it likely will work for many to set per workspace, but not all people use the workspace approach and you are not unlikely to have files in the same workspace that use a different encoding): "please reconsider and opening this issue".

I guess the biggest point is how to handle conflicting situations (settings in a path vs. file specific extensions). I suggest to give the path specific setting the higher priority but the option to limit it:

```json
        "files.encoding": "utf8",
        "file.encodingPaths": [
           {
              "pattern": "**/folderA/**,
              encoding: "windows1251"
           },
           {
              "pattern": "**/folderA/subFolder/**,
              encoding: "*"
           }
        ]
```

This way all files in "folderA" would get the windows1251 encoding but the files in "olderA/subFolder" would not have the setting applied (and in this case because of the global setting the utf8 encoding).
