### ISSUE TITLE
[FEATURE] VS Code Wrapped: A Year in Review for Developers

### ISSUE THREAD

**Issue by DiegoDev2** [microsoft/vscode#235792]
**Proposal:**

Create a "VS Code Wrapped" feature that generates a year-end report summarizing a user's coding activity.

**Features:**
* Most used programming languages
* Total hours spent coding
* Most frequently used keybindings
* Popular extensions

**Implementation:**
* **Authentication:** Implement GitHub OAuth to securely store user data.
* **Data Collection:** Collect anonymized data on language usage, keybindings, etc.
* **Report Generation:** Generate visually appealing reports.
* **Privacy:** Ensure data is handled securely and users have control.

**Benefits:**
* Engaging user experience
* Community insights
* Marketing opportunity

**Comment by chrisdias** [comment]
Hi!  This is a fun idea! It's also an excellent candidate for an extension to VS Code.  To make it cross machine, you could let the user specify where to store the statistics (e.g., a github gist, google drive, one drive, etc.).  That way you don't have to build or have a dependency on running a service but instead can focus on collecting the data and the presentation.  Since Privacy (as you point out) is probably the most critical and expensive piece of this, giving the user control where the data is stored is a great way to deal with those complexities.

Tagging as a good extension candidate, someone should use GitHub Copilot and create the extension!!

**Comment by DiegoDev2** [comment]
I can try it, but I'm not familiar with vscode extensions. @chrisdias

**Comment by xwyzsn** [comment]
hi, does any updates for this extension? @DiegoDev2

**Comment by DiegoDev2** [comment]
Hello, no, I would like to start but I still need some help @xwyzsn
