### ISSUE TITLE
Terminal tab titles disappear until switch between tabs

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode#235931]
Not sure how to repro, but seems to occur when I hide/unhide Panel visibility

https://github.com/user-attachments/assets/e84168c0-444c-4dd9-ac83-1f92070c7f1e

Version: 1.97.0-insider
Commit: 6a5c8cf95aa814b5cb92de617096144b1f45af2d
Date: 2024-12-12T05:04:17.220Z
Electron: 32.2.6
ElectronBuildId: 10629634
Chromium: 128.0.6613.186
Node.js: 20.18.1
V8: 12.8.374.38-electron.0
OS: Darwin arm64 24.1.0

**Comment by Tyriar** [comment]
@ulugbekna I can't repro, could you check devtools console for errors?

**Comment by ulugbekna** [comment]
I don't see any related errors in dev console. 

Are you also on mac and use zsh? Could you try reproing in copilot repo with all 3 tasks running and an extra terminal as in my screencast?

**Comment by Tyriar** [comment]
I was trying on Windows because the OS shouldn't matter for this. Regardless, passing to @meganrogge as main owner of tabs now

**Comment by meganrogge** [comment]
did you toggle/untoggle zen mode? if so, can repro and is a duplicate of #176085

**Comment by meganrogge** [comment]
I cannot repro when I toggle panel visibility though on mac

**Comment by meganrogge** [comment]
started seeing this recently. maybe need to bisect

<img width="1204" alt="Image" src="https://github.com/user-attachments/assets/e857ea5d-d702-470a-92fc-93333847eadd" />

**Comment by meganrogge** [comment]
@benibenj , git bisect points to this commit: d5746c5593f6afe15e44a9f7877a064df6605d11

<img width="654" alt="Image" src="https://github.com/user-attachments/assets/35e20e87-2e0e-48cd-8cfa-77718b7e036c" />

**Comment by meganrogge** [comment]
Seems like maybe we now need to call layout when the panel is revealed?

**Comment by meganrogge** [comment]
Might want to let other view owners know about this change, I see that the debug console used to receive focus on visibility change, but now does not for example.

**Comment by meganrogge** [comment]
cc @alexr00 both Ports and Comments now do not get focused when the panel becomes visible.

**Comment by benibenj** [comment]
I don't mean that the views should take focus when they become visible. They layout/views logic tells your view when to be focused. The problem here seems to be that the terminal only renders correctly when it gets focused, which should not be the case. You need to make sure it renders properly when the visibility of the view changes.

I think #236502 should be reverted. It behaved correctly before

**Comment by meganrogge** [comment]
> I think https://github.com/microsoft/vscode/pull/236502 should be reverted. It behaved correctly before

It did not behave correctly before - it did not move focus to the debug console input box like it should and like it does in VS Code stable. This is an accessibility issue.

Stable:
https://github.com/user-attachments/assets/f19616b8-f2bf-437b-8a07-06ab3b739c6e

Insiders:
https://github.com/user-attachments/assets/9e499cda-4232-46d2-ae54-2ed7dc9b6e40

**Comment by meganrogge** [comment]
>  The problem here seems to be that the terminal only renders correctly when it gets focused, which should not be the case. You need to make sure it renders properly when the visibility of the view changes.

This is not just about rendering. The terminal has historically received focus when the panel becomes visible.

**Comment by Tyriar** [comment]
This change really should have had a larger audience before it happened with pings to owners of panel views. Ctrl/cmd+j has been around forever and people depend upon it. Consistency is good, but we must have a roll out plan for something like this that changes such old/core behavior.

> The problem here seems to be that the terminal only renders correctly when it gets focused, which should not be the case.

I agree with this, but the main issue @meganrogge is talking about wrt accessibility is the focus part. The layout problem is just another unfortunate affect of this change.

> They layout/views logic tells your view when to be focused.

The terminal cannot do this or we would break other things like the `Terminal.show(preserveFocus)` extension API. At the very least 
it's not as simple as just just focusing on visibility, how to get the old behavior back is not obvious to me.

---

imo we should revert all the changes include the original change and have the discussion about it first. This is also the lowest risk approach since most of us will be offline for most of the time.

**Comment by Tyriar** [comment]
@benibenj FWIW the purest in me agrees with you, but I think we've had this behavior for too long and we'd be better off going in the other direction where ctrl/cmd+j shows AND focuses any panel or hides it, similar to the ctrl+` behavior. A bonus of going this route is we could use a conditional keybinding to call a showAndFocus command, so if the user really wanted to just toggle the panel they can unbound the showAndFocus one.

**Comment by benibenj** [comment]
Just to explain why this got decided:

The layout logic had a bug for ages, where it would want to focus the view when toggling the pane. It would call `focus()` on the view when it was still invisible, hence the view never actually got focus. A handful of views seem to have added hacks to make sure they actually get focus as soon as they become visible. Apparently `Debug Console` is also one of those, was not aware of that one. https://github.com/microsoft/vscode/blob/acd32b17b837b05a64275c297949753df46dbe6d/src/vs/workbench/contrib/debug/browser/repl.ts#L555-L559

Most views however did not have this. As we noticed this problem, the decision was made to not give focus to the views when toggling the panes to have consistency and not break muscle memory as most views actually did not get focus before. The behaviour would hence change for the least amount of views.

**Comment by benibenj** [comment]
@Tyriar I do agree view you, so I reverted the behaviour back to what we had before and reopened https://github.com/microsoft/vscode/issues/232790. @meganrogge, sorry about the inconvenience. Also, if you think this is an accessibility issue, please comment that in the issue, this help push the opposite change to happen.

**Comment by meganrogge** [comment]
Closing now that the change has been reverted, so this should be fixed.
