### ISSUE TITLE
Different Rendering of Shortcut keys

### ISSUE THREAD

**Issue by seanmcbreen** [Microsoft/vscode#23590]
Testing #23287

The rendering of shortcuts differs in the contribution view of the ext manager:

![image](https://cloud.githubusercontent.com/assets/1051190/24467421/30faf302-1469-11e7-84f3-0718bca11637.png)

And the keyboard shortcut editor:

![image](https://cloud.githubusercontent.com/assets/1051190/24467432/3fbbd262-1469-11e7-9ecb-639ff8052e87.png)

We should ideally make the views as consistant as possible e.g the column headers, the command description layout and the key highlighting.

**Comment by eamodio** [comment]
FWIW, I also find the shortcut key rendering on extensions very hard to see the keys -- so please unify to something like the shortcut editor :)

**Comment by sandy081** [comment]
@seanmcbreen Thanks for filing an issue. I have this in my list.

**Comment by sandy081** [comment]
Agreed that keybinding should be rendered similar to Keyboard shortcuts layout but not with headers. Because, these are two different editors and showing different information in different contexts. Extension editor shows commands and their descriptions and assigned keybindings and in which menu contexts these commands are being used. This is a brief/combined view of commands/keybindings/when contributions from an extension. Keyboard shortcuts editor is specific to keybindings. 

So only fixing the representation of keybinding
