### ISSUE TITLE
shell integration command line in pwsh polluted by ghost text

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#235996]
type `c`, get a bunch of ghost text in `pwsh`
<img width="850" alt="Image" src="https://github.com/user-attachments/assets/270e06a6-98ec-4274-944b-995010a18b2f" />

`terminalContext.commandLine` contains ghost text, which causes the check to fail and it returns early without the `cd`, `code`, etc specs

<img width="1270" alt="Image" src="https://github.com/user-attachments/assets/059511c2-63a0-4c69-98ff-3f32407aa361" />

**Comment by Tyriar** [comment]
@meganrogge I think the failure here is that ghost text is included in the context you pass on to extensions. Prompt value here includes ghost text by design so we can see it, will need a change for `this._promptInputModel.value` being passed in here:

https://github.com/microsoft/vscode/blob/3b30f94f4f129e67be9b6c677aac582923da1fab/src/vs/workbench/contrib/terminalContrib/suggest/browser/terminalSuggestAddon.ts#L159
