### ISSUE TITLE
Rendering glitch when using icon on the Action2 toggled property

### ISSUE THREAD

**Issue by benibenj** [microsoft/vscode#236066]
When using `ICommandActionToggleInfo.icon` there is a rendering glitch. It first always renders the title as a label before rendering it as an icon.

Can be reproduced with changes in this PR by toggling the secondary side bar: https://github.com/microsoft/vscode/pull/236062

![Image](https://github.com/user-attachments/assets/c88d12d8-6d9c-48a9-9017-363757334013)

**Comment by jrieken** [comment]
As far as I know @sandy081 added support for the toggled icon

**Comment by sandy081** [comment]
@benibenj You seems to have icon only for toggled state and not for non-toggled state. It seems the action is first rendered in non-toggled state and immediately getting switched to toggled state. Therefore in the beginning action label is shown. This seems to be expected behaviour for all menu actions when there is no icon. I am not sure how I can fix. Please have an icon for non toggled state or fix the context such that the initial state is toggled.
