### ISSUE TITLE
Getting search results which should be ignored

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#23618]
![image](https://cloud.githubusercontent.com/assets/22350/24474915/83b88b8a-14ce-11e7-93a7-b011cfb82b47.png)

**Comment by roblourens** [comment]
You have those settings disabled, you need to click the gear icon above to enable them again. It's enabled by default, you probably clicked it at some point. But I wonder whether the UI needs to be more obvious. Could ~strike out~ the text in that line when it's disabled?

**Comment by joaomoreno** [comment]
Oh, I get it now.

In current stable the default means _nothing is toggled_:

![image](https://cloud.githubusercontent.com/assets/22350/24489904/3c7c633e-1520-11e7-9694-a4ae23f70c7b.png)

IMO it boils down to _what_ is the default UI. Having nothing toggled should have it behave in the average, most useful case: _use the exclusion rules_.

It feels weird that the default state is that the gearbox in the middle is selected:

![image](https://cloud.githubusercontent.com/assets/22350/24489867/0c39e070-1520-11e7-95c9-085c6a9c5b69.png)

We could reverse its meaning. Instead of _Use Excluded Settings_, it could be _Ignore Excluded Settings_, with a striked gearbox icon.

**Comment by roblourens** [comment]
> Having nothing toggled should have it behave in the average, most useful case

I agree with that principle, but if I flip it around for both buttons, then the gitignore icon will be selected by default, because we decided to err on the side of not flipping on gitignore support for 1000s of people, so you still have one button on by default.

The other reason is that if you reverse it, the button's meaning is a double negative - "ignore the exclusions", "skip the ignore file" - I have to stop and think about this for a second.

On the other hand, I think many people will set the option to enable gitignore support by default. I do think it makes sense for the buttons to reflect that as a default. Do you think the icons still make sense if we do that? The real settings icon will be that gear + the little "do not enter" badge. 

cc @cdias @kieferrm
