### ISSUE TITLE
Feature Request: change CodeLens position in the editor to make loading smoother

### ISSUE THREAD

**Issue by solarsailer** [Microsoft/vscode#23652]
Hello,

CodeLens is a superb feature. But right now, in its current implementation, I think it's almost unusable. :(

Because CodeLens are lazily added to the editor, they break the code structure. You open the editor, then the lines "jump", and then CodeLens appear. This is not great: my eyes look at something, then everything move. It's jarring. And it can take a bit of time before they appear if the codebase is large enough.

And it happens every time a file is opened.

Moreover, even if CodeLens were not lazily added, the problem would still be here: the code structure changes because of CodeLens, and my file is visually different because of that.

That's why I think that putting CodeLens above a line is wrong.

Possible solutions:

- The CodeLens are placed at the right of the line, instead of above (instead of using the word "References", an icon could lighten the interface a bit, too).
- Add a marker near the line number on the left.

Quick mockup:

![codelens](https://cloud.githubusercontent.com/assets/478621/24495131/8134f5cc-1534-11e7-9fcd-5d45b4796376.png)

Thanks for considering this. :)

**Comment by johnfn** [comment]
Definitely agreed. But I think the main problem is the UI jump. If the size of codelens could be precalculated such that the UI would not jump, I think that would also solve my issue here.

**Comment by stevencl** [comment]
I understand the issues and appreciate the feedback.

When the team worked on CodeLens in Visual Studio a number of years ago they considered many different ways of displaying the indicators. They ran studies comparing different fonts, colours, sizes and position. Eventually the team landed on the current design, injecting the indicators above the method signature.

One of the reasons that positioning them on the same line as the method signature wasn't chosen for the final design is due to different coding styles used by developers, especially around functions and properties.

For example, in JS and TS, it's not uncommon to have an opening curly brace on the same line:

`function foo() {`

The team didn't want to interfere with the readability of this code by inserting an indicator in between the closing parenthesis and the opening curly brace. Adding the indicator after the curly brace then leads to some potential confusion about the scope of the indicator.

In addition, it's not uncommon for the implementation of a property to be placed on the same line:

`public double Hours {
get { return seconds / 3600; }`

Placing the indicator at the end of this line made it a little more difficult to glance at the indicator since the eye has to scan to the end of the line to find the indicator. A key goal for code lens is that they provide glanceable information thus making the developer aware of something that they might not have considered looking for (such as the number of references to a method, or the number of failing test cases).

After exploring a large number of possibilities, the team ended up with the design we have today. In VS Code we took advantage of all that work and followed the guidance of the VS team.

It's not perfect by any means as the comments above has indicated. But unfortunately we have not yet been able to design the user experience such that it accomplishes the goals we have for code lens without interfering with the initial experience of opening and browsing a file. We have tried to minimise the interference by adjusting the font size, but this can only go so far before the code lens indicators become unreadable.

**Comment by DM-John** [comment]
I second this suggestion (an easier way to toggle CodeLens or show it differently).  I wish that I could hover over the reference, with maybe the Alt Key, and see the reference count in that manner.  The integrated method is jarring and breaks up my wall of text.  ;-)

**Comment by johnfn** [comment]
@stevencl I think you're missing what OP is saying. He's saying that the primary frustration is that the code jumps downwards as the codelenses are filled in a second or two after the code is loaded. 

This has nothing to do with the UI design of the code lenses. It is 100% an engineering problem. 

The code could stay in the same place even when the lenses load into place if the sizes and locations of the lenses were pre-calculated, for instance.

**Comment by stevencl** [comment]
Sorry, I was responding to the suggested UI changes to the design. I didn't respond to the idea about calculating the position and size of the code lens indicators before displaying the full file. That is indeed an engineering issue. If it is the case that we could calculate this without incurring any significant, perceptible delay, then we could do this. But if the cost of calculating these sizes was that there was a delay in displaying the file, that would have an impact on the overall user experience.

Assigning back to @jrieken to see what his thoughts are on the feasibility of calculating the sizes and location of code lens indicators prior to displaying the file.

**Comment by jrieken** [comment]
> Assigning back to @jrieken to see what his thoughts are on the feasibility of calculating the sizes and location of code lens indicators prior to displaying the file.

In VS Code, code lenses can be anywhere and the editor doesn't know the location upfront. It works in two phases: (1) ask all code lens providers for the locations at which they want to insert lenses and when that is done make space (2) then fill the empty space that is in the viewport by asking the provider to fill lenses. 

So, because VS Code is unaware of any language it does rely on extensions to help it out. It's not perfect and there are some tricks we should implement, as discussed here: https://github.com/Microsoft/vscode/issues/19917#issuecomment-277932418 but at the end it boils down to how fast an extension computes code lenses. So my suggestion is to file issues individually again those extensions that are too slow adding lenses and to add more tricks on our side.

**Comment by jrieken** [comment]
Closing this because @stevencl explained the rational for showing lenses above the code, we have issues making generic lens behaviour better, and because the actual data is always extension dependent.
