### ISSUE TITLE
[Suggestion] File icon Keybindings

### ISSUE THREAD

**Issue by Tekbr** [Microsoft/vscode#23666]
- VSCode Version: 1.11.0 insiders bc9a7bb
- OS Version: Windows 10

-- Sorry for the English, I used Google Translator --

Create a default icon for this page (regardless of the icons theme that I use), rather than the default white sheet.

Similar to Welcome page.

![key](https://cloud.githubusercontent.com/assets/19866231/24503855/42ee865c-152a-11e7-822e-5e9db1cdcde6.PNG)

**Comment by Tekbr** [comment]
@sandy081 I thought of this icon.
You may have to adjust it according to the color theme.

https://icons8.com/web-app/15899/keyboard

![capturar](https://cloud.githubusercontent.com/assets/19866231/25279245/3f0fa38c-267c-11e7-9279-35128d38f335.JPG)

**Comment by sandy081** [comment]
Please feel free to submit a PR

**Comment by eginwong** [comment]
Should this be closed? There is another icon for Keyboard shortcuts in the latest builds.

**Comment by sandy081** [comment]
@eginwong Current icon is coming from file icon themes. I am happy to close this if current icon works for everyone.

**Comment by kumarharsh** [comment]
I came across this issue because I was trying some keybindings with different when clauses for git, while editing my own code and more than once switched to the wrong tab because the icons are the same for default files and keybindings settings screen.

@sandy081 I'd like to try and fix this if possible. I believe there is already an icon for keyboard somewhere in vscode (it shows up as the Record Keys icon in keybindings editor). I think it should not be more than a few lines... I hope ;)

**Comment by sandy081** [comment]
Marking this as dup of #59985 as the other one covers also settings
