### ISSUE TITLE
Console logs are missing newlines, when debugging an extension

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#23695]
Have an extension with this line:

`setInterval(() => { console.log('hi' + Date.now()) }, 500)`

The output is all on one line:
![image](https://cloud.githubusercontent.com/assets/323878/24520767/7c7d3742-153e-11e7-8af8-c4cadef73d3d.png)

Works as expected with a node program

**Comment by roblourens** [comment]
Looks like extensionhost output comes through a back door, and I don't know where the newline is supposed to be applied.

**Comment by weinand** [comment]
@bpasero any pointers?

**Comment by bpasero** [comment]
@weinand we use a broadcast approach to send output from the extension host to the other windows (starts from https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/electron-browser/extensionHost.ts#L295).

The debug service seems to receive this output here: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/debugService.ts#L182

**Comment by eamodio** [comment]
I noticed the same change recently and I ended up just throwing newlines into my console output.

**Comment by isidorn** [comment]
We were never getting newlines from the extension logs, we were simply wrongly appending newlines to each output message in the debug console. However since we have fixed that issue now this has surfaced.
To preserve old behavior now I am always manually appending a newline when an output is coming from the extension. Which I think makes absolute sense that each log gets its own line, no matter if it ends with '\n'.

This fix is low risk since it does not change how we touch the output coming to the debug console in general.
@weinand please verify

**Comment by weinand** [comment]
@isidorn works fine with fix
