### ISSUE TITLE
Activity bar: need dark/light icons

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#23693]
So far our activity bar was always using one background. Therefor our icons are also just one set and do not adapt to theming as our other icons are. We should use a light variant and dark variant of activity bar icons depending on the configured theme.

/cc @seanmcbreen

**Comment by seanmcbreen** [comment]
My fancy custom theme as an example ;)
![image](https://cloud.githubusercontent.com/assets/1051190/24528466/75938ba8-155b-11e7-8a4b-7f506903db6e.png)

```json
	"workbench.colorTheme": "Default Light+",
	"workbench.experimental.colorCustomizations": {
		"sideBarBackground": "#DCDCDC",
		"sideBarTitleForeground": "#93A1A1",
		"activityBarBackground": "#C0C0C0",
		"titleBarActiveBackground": "#C0C0C0",
		"statusBarForeground": "#708090",
		"statusBarBackground": "#C0C0C0"
	}
```

**Comment by kumarharsh** [comment]
Also, while setting the statusBarForeground to a different colour than white, the icons don't change colour due to being images rather than SVG. Would this be something which would need to be changed?

**Comment by bpasero** [comment]
Yes that is captured in https://github.com/Microsoft/vscode/issues/23526

**Comment by bpasero** [comment]
Ways to do this via CSS:
- `filter: invert(1)`
- `-webkit-mask`

**Comment by kumarharsh** [comment]
`filter: invert(1)` would only give you black or white, but it will not match with the `fg-color()`. A better solution would be to do a hue-shift of the icon using `filter: hue-rotate(θ)` where theta would be pre-calculated depending on the hue of the foreground-colour. You'll also need to change the saturation in a similar manner `filter: saturation(x%)`.

**Comment by kumarharsh** [comment]
So, I don't think my comment would do much good, as the filter I suggested would apply to the whole thing (text AND icon), and there's no way to just target the icon which is set via `background-image`.

The options I see are:

1. Use svg image masks on each of those icons - it works surprisingly well for the icons:
![image](https://cloud.githubusercontent.com/assets/760112/24727552/054e300a-1a74-11e7-98ef-b5c3629d1024.png)
Here, I've just modified the `background-image` to `-webkit-mask-image`, and set the mask position same as background positions.
![image](https://cloud.githubusercontent.com/assets/760112/24727672/74111732-1a74-11e7-9bc8-760f7a01d33a.png)
but the downside is that the actual text beside the icon is also hidden by the mask. I've come up with two ways to counter this problem:<br>
  1a. To add a rectangle to the right of the icon, which will unmask the values. But this would be unnecessarily complicated while dealing with internationalized vscode (if text is to the left of icon, then handle those cases, etc).
  1b. See point 3.

2. Set all icons and all texts to have color/fill as `#f00`, i.e., hsl(0,100%,50%), and then use the `color` library to determine the offsets of hue, saturation and brightness to be used in a filter expression:
```
filter: hue-rotate(Xdeg) saturation(Y%) brightness(Z%)
```
which will be applied to each `.statusbar-item-label`. Downsides are too much JS & calculation is involved, and I'd like to see a more css-only solution.

3. (also 1b) Instead of using `background-image: url(...)` to set the icon, insert the SVG icon inline. This would solve the issue in the cleanest way possible. For the case in (1b), the mask would apply only to the svg if the svg is it's own element.

</End of sanity>

---

4. When the icon is being added as the css `background-image` property, [like here](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/actions/electron-browser/menusExtensionPoint.ts#L273), do a regexp match, after converting the SVG content to string:

```
createCSSRule(`.icon.${iconClass}`, `background-image: url("${URI.file(path).toString().replace(/fill='%23fff'/, `fill='${encodeURIComponent(fgColor)}'`)}")`);
```

**Comment by bpasero** [comment]
For the status bar icons I am actually thinking of switching to using a font instead of SVG. All extensions down there that use icons already use a font for it, so it would be consistent. For the activity bar we still have to find a solution, thanks for all the ideas @kumarharsh

**Comment by kumarharsh** [comment]
For the activity bar, I think using the mask would be best, and there's no accompanying text so I think it'll work well there.
+1 for using font instead of bg-image, but I'm curious - why can't we inject SVG icons in the `.statusbar-item`s since vscode already has them available?

**Comment by bpasero** [comment]
I pushed a light fix for this: if someone provides a light theme that overrides the activity bar background color, the icons flip to a light-theme version (in the same way as all other icons are throughout the workbench). 

I would like to not introduce an explicit way of coloring the icons in the activity bar (e.g. using webkit-mask) because that is not a good story for all other icons: If we introduce a way to color icons, it should be possible everywhere and not just in the activity bar. I do not think this can be done easily without having an icon font.
