### ISSUE TITLE
Failed preLaunchTask's should abort debugger launch

### ISSUE THREAD

**Issue by gregg-miskelly** [Microsoft/vscode#2370]
Currently errors in preLaunchTask's are silently ignored. This is a big problem for any compiled language which uses preLaunchTask to compile the code as this means that any build errors are ignored.

**Comment by isidorn** [comment]
After a preLaunchTask has finished we now check if there are errors in the workspace, however in our task framework we do not have a connection if a task produced an error. So it might happen that there is an unrelated error in the workspace (e.g some malformed json). Due to this in the message we offer the user to debug anyway.
This should also work for watching tasks.

![screen shot 2016-02-08 at 15 40 49](https://cloud.githubusercontent.com/assets/1926584/12888428/5c485c10-ce7a-11e5-96ac-5e60a6205713.png)
