### ISSUE TITLE
Debugger does not break on symlinked module (NodeJS/Mac OSX Sierra)

### ISSUE THREAD

**Issue by rgilling** [Microsoft/vscode#23753]
I think there's an issue with symlinks on Mac. I used npm link to link a module. The code runs fine, but adding a breakpoint does not break. 

- VSCode Version: February 2017 (version 1.10)
- OS Version: MacOS Sierra Version 10.12.3

Steps to Reproduce:

1. Create a child NodeJS module - just hello world will do. - run npm link in the module directory.
2.Create a parent module and npm link the child. `npm link child` from the parent directory.
3. Write a script to call the child code from the parent project. `child.sayHello()`
4. navigate to node_modules and add a breakpoint in the child code.
5. Run the debug for NodeJS.
6. It probably won't break on the child.
7. npm unlink child
8. Change package.json to import by adding the child as a file dependency. `child: '../child'`
9. npm install to 'copy' the files in rather than symlink them.
10. reset the breakpoint in the child code.
11. Rerun the debugger - it should now break in the child code.

**Comment by weinand** [comment]
@rgilling I can reproduce and I understand what is going on:

My setup is as follows:

![2017-04-04_17-43-59](https://cloud.githubusercontent.com/assets/1898161/24665643/4e1fa3ca-195e-11e7-8db6-1028fea1b705.png)

And my launch config is:
```json
			{
				"type": "node",
				"request": "launch",
				"protocol": "legacy",
				"name": "test.js",
				"program": "${workspaceRoot}/test.js"
			}
```

I'm opening VS Code on the 'test' project.

If I navigate to the 'index.js' file to set the breakpoint, VS Code doesn't notice that 'index.js' lives in the symlinked 'helloworld' folder. As a consequence it considers 'index.js' as a file in your 'test' workspace. So its workspace relative path becomes 'node_modules/helloworld/index.js' which is then expanded to become absolute: '/symlinks/test/node_modules/helloworld/index.js'. This path is used to register a breakpoint with node.js.

The problem is that node.js sees the 'index.js' file under the real path: '/symlinks/helloworld/index.js'.

Since these paths do not match the breakpoint is not hit.

We do not have a good solution for solving symlink issue in the general case, but there is a way to work around the issue:

- do not navigate to 'index.js' through VS Code's explorer but try to "step into it" through the debugger.  Then set the breakpoint. You will notice that VS Code creates a new breakpoint in the breakpoint view:

![2017-04-04_17-48-31](https://cloud.githubusercontent.com/assets/1898161/24665902/fd554354-195e-11e7-9a2f-f2b270ba280a.png)

Now the breakpoint's path is correct (without the symlink).
This breakpoint will be hit.

(@roblourens I noticed that my workaround does not work with the 'inspector' protocol. But may be you have a better workaround for this symlink problem)

**Comment by roblourens** [comment]
I filed this some time ago - https://github.com/Microsoft/vscode-node-debug/issues/73 - but no, I don't have a better workaround :)

**Comment by roblourens** [comment]
I often debug from the symlinked module's folder, which is painful to set up but works for my case.

**Comment by weinand** [comment]
I will enable localRoot/remoteRoot for "launch" and see whether this helps...
But why doesn't help the workaround with the inspector?

**Comment by roblourens** [comment]
It does work for me - I can step into a symlinked module, get a file with the real path, and set BPs there.

**Comment by weinand** [comment]
@rgilling thanks for the tip: adding `"--preserve-symlinks"` as a runtime argument fixes the problem for me:

```json
{
	"type": "node",
	"request": "launch",
	"protocol": "legacy",
	"name": "test.js",
	"program": "${workspaceRoot}/test.js",
	"runtimeArgs": [
		"--preserve-symlinks"
	]
}
```

@roblourens this doesn't work for me with `"protocol": "inspector"` and node v6.10.1.

**Comment by weinand** [comment]
I will add this great tip to the documentation.

**Comment by roblourens** [comment]
@weinand That doesn't work for me either. Will investigate.

**Comment by rgilling** [comment]
Hi guys, glad that helped. Per node doc `preserve-symlinks` was added node 6.3. It's probably similar to the issue I had previously then. preserve-symlinks is okay for some cases where you're running node directly, but if you're running things like npm, grunt or mocha they need to also support the param. I know mocha does, I recall I was having issues with Grunt though.

**Comment by roblourens** [comment]
I don't want to complicate the already complex breakpoint path handling by handling breakpoints on either end of a symlink.
