### ISSUE TITLE
Salsa: formatOnType does not respect current line indendtiation

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#2377]
1. js workspace, have salsa enabled
2. "editor.formatOnType": true
3. The format on type is too aggrressive and does not respect current indentiation. This is especially noticable when trying to create object literals
4. if salse is disabled this works nicely

**Comment by dbaeumer** [comment]
@isidorn I can't see any weirdness. Can you please provide some steps. I tested ts and js and they behave the same. Both honoring indent setting.

Please be aware that if a indent of for example 4 spaces exist and you have insert tab and tab size > 4 then format on type from TS will stil insert 4 spaces to align the code correctly.

**Comment by isidorn** [comment]
```
var t = {
  name: isidor,
// this line gets indented all the way to the start once I press enter after name property
}
```

**Comment by dbaeumer** [comment]
Same happens for TS.

**Comment by dbaeumer** [comment]
I debugged it and this is a tsserver behavior. When pressing enter after Isidor, VSCode inserts the right indention but the tsserver returns and edit that deletes that indention. IMO the tsserver should be smart and if Isidor is ended with , adjust the indention since there is a high likelihood that the user inserts another property.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#6700
