### ISSUE TITLE
No way to open a file that's excluded in search.exclude

### ISSUE THREAD

**Issue by AndrewRayCode** [Microsoft/vscode#23772]
- VSCode Version: Version 1.10.2 (1.10.2)
- OS Version: OSX

Steps to Reproduce:

1. Add a folder to your `"search.exclude"` setting, such as
    
       "search.exclude": {
           "**/vendor": true,

2. Press `ctrl+p` and paste in an exact file path that's in the ignored folder, like `vendor/something.java`

**Expected result:**

The file to show up, and be opened by hitting enter.

**Actual result:**

"No results found", and there is no way to open the file.

I would expect "search.exclude" to prevent files from showing up when searching, which it does. I was surprised to find out I can't open it through the normal file finder, though.

**Comment by roblourens** [comment]
This is by design. I don't want to see those files every time. But if you open the file, it should appear in that quick open list as a "recent file".

In 1.11, there's a button in the search viewlet to disable these exclude settings from a search. We discussed a similar button for the quick open, but I'm not sure.
