### ISSUE TITLE
terminal sendtext blocks if application running in PowerShell

### ISSUE THREAD

**Issue by bascott** [Microsoft/vscode#23809]
- VSCode Version: 1.10.2
- OS Version: Windows 10 v1607

Steps to Reproduce:

1. (If set differently) set `"terminal.integrated.shell.windows"` to `"C:\\WINDOWS\\Sysnative\\WindowsPowerShell\\v1.0\\powershell.exe"`
2. Create "Hello World Extension" tutorial as from https://code.visualstudio.com/docs/extensions/example-hello-world
3. Replace `vscode.window.showInformationMessage('Hello World!');` in extension.ts/js with `let term = vscode.window.createTerminal(); term.sendText("telnet"); term.sendText("quit");`
4. Debug extension and execute `Hello World` command

**Expected result**: the telnet client would immediately open in the new terminal and then exit.
**Observed result**: the telnet client remains open with no text. Typing `quit` in the terminal will exit telnet, and then `quit` is immediately sent into the terminal, giving an error stating the command does not exist.

**Comment by Tyriar** [comment]
If I understand correctly it's sending quit to powershell rather than telnet? I think this is as designed, there's nothing I can do on my end other than suggest to use a `setTimeout` before connection or to craft your shell executable and args in such a way that telnet is launched immediately (so something like `cmd.exe /c telnet` is run).
