### ISSUE TITLE
Improve performance in the text selection over minimap or without minimap

### ISSUE THREAD

**Issue by Tekbr** [microsoft/vscode#23819]
- VSCode Version: 1.11.0 - Insiders
- OS Version: Windows 10

-- Sorry for the English, I used Google Translator --

Apply a little delay instead of going straight to the end, like the Atom.

In both directions, from left to right and from right to left.

Related with #21729 

![scroll](https://cloud.githubusercontent.com/assets/19866231/24588241/0d725364-179b-11e7-92c4-94e3135811bb.gif)

**Comment by alexandrudima** [comment]
This might be doable for LTR text, but possibly not for bidi or RTL text.

**Comment by Tekbr** [comment]
@alexandrudima Left to Right, it helps a lot. 😄  Will it be possible to put this in April?

**Comment by alexandrudima** [comment]
I have investigated this and it would be quite difficult to implement. When the mouse is over the minimap, we behave in the same way as if the mouse leaves the editor. The reason is because the minimap captures the hit testing we do and it is not possible for us to know which character / what offset is painted under the minimap. We therefore set the cursor at the maximum column.
