### ISSUE TITLE
Some keys are not recognized correctly when using a Japanese keyboard

### ISSUE THREAD

**Issue by landonepps** [Microsoft/vscode#23833]
Keybindings for certain keys do not work as intended with a Japanese keyboard on macOS. When defining keybindings, the @ key (right of 'P') and '[' key are both recognized as a [. Shift+@ is recognized as shift+`. The ¥ key is 'unrecognized' and shift+¥ is recognized as shift+\.

There may be issues with other keys, too. I noticed this one specifically because there is no ` key on a Japanese keyboard and it's used to open the terminal. 

I'm using my MacBook's default keyboard which is Japanese. I also have a bluetooth Apple Japanese keyboard that experiences the same issue.

- VSCode Version: 1.10.1
- OS Version: macOS 10.12.4

Steps to Reproduce:

1. Open 'Preferences -> Keyboard Shortcuts' (cmd+k cmd+s)
2. Click 'Define Keybinding' (cmd+k cmd+k)
3. Press @ or ¥ on a Japanese keyboard.

Here's a picture of the keyboard layout for reference:
![mla22j](https://cloud.githubusercontent.com/assets/1572318/24593427/4a7be108-185e-11e7-8c53-b04922b6c234.jpg)

**Comment by landonepps** [comment]
I'd be willing to work on this, if someone more experienced with the codebase could point me in the right direction.

**Comment by alexandrudima** [comment]
@landonepps 

Quite a lot have changed in the upcoming 1.11 regarding keyboard layouts and keybinding handling. I would suggest to first try to use the Insiders Build and see how it behaves there.

I have written a wiki page documenting how keybindings work in VS Code at https://github.com/Microsoft/vscode/wiki/Keybindings

Please give that a quick read and try to see if the wiki page provides sufficient information for you to understand what's going on. For Japanese, I believe the issue is in `node-native-keymap` where the OSX specific methods return a null pointer at one point. I would very much welcome a second pair of eyes on that code.

**Comment by landonepps** [comment]
You're right. Calling `keymap.getCurrentKeyboardLayout()` with a Japanese keyboard returns an empty object. I'll have a look and see if I can figure anything out.

**Comment by landonepps** [comment]
So I changed keyboard_mac.mm in `node-native-keymap` from
```
  TISInputSourceRef source = TISCopyCurrentKeyboardInputSource();
  CFDataRef layout_data = static_cast<CFDataRef>((TISGetInputSourceProperty(source, kTISPropertyUnicodeKeyLayoutData)));
  if (!layout_data) {
    // https://developer.apple.com/library/mac/documentation/TextFonts/Reference/TextInputSourcesReference/#//apple_ref/c/func/TISGetInputSourceProperty
    args.GetReturnValue().Set(result);
    return;
  }
```
to
```
  TISInputSourceRef source = TISCopyCurrentKeyboardInputSource();
  CFDataRef layout_data = static_cast<CFDataRef>((TISGetInputSourceProperty(source, kTISPropertyUnicodeKeyLayoutData)));
  if (!layout_data) {
    // TISGetInputSourceProperty returns null with a Japanese keyboard layout.
    // Using TISCopyCurrentKeyboardLayoutInputSource as a workaround.
    source = TISCopyCurrentKeyboardLayoutInputSource();
    layout_data = static_cast<CFDataRef>((TISGetInputSourceProperty(source, kTISPropertyUnicodeKeyLayoutData)));
    if (!layout_data) {
      // https://developer.apple.com/library/mac/documentation/TextFonts/Reference/TextInputSourcesReference/#//apple_ref/c/func/TISGetInputSourceProperty
      args.GetReturnValue().Set(result);
      return;
    }
  }
```
which is apparently a workaround for the NULL return value. (see [this stackoverflow page](http://stackoverflow.com/a/1971027/1154304))

When using the modified `node-native-keymap` the ¥ key is still unrecognized, but the @ key now shows as "[BracketLeft]" instead of "[" when trying to bind the key.
<img width="516" alt="screen" src="https://cloud.githubusercontent.com/assets/1572318/24638232/d7b22a3c-1921-11e7-8eeb-279f6fd154ee.png">

**Comment by landonepps** [comment]
I created a PR for `node-native-keymap`
Microsoft/node-native-keymap#8

**Comment by alexandrudima** [comment]
Brilliant!

**Comment by landonepps** [comment]
This issue isn't quite fixed. I can now use the @ key, but the `_` and `¥` keys still show as `unknown`.

**Comment by alexandrudima** [comment]
@landonepps Thanks again for your work! :heart:

`IntlRo` and `IntlYen` should work fine after 362212b50941d1057565829c9494e530d88a630b

Unfortunately I cannot test them as I only have access to ANSI and ISO keyboards, and not to JIS ones.

**Comment by landonepps** [comment]
I can confirm this has been completely fixed as of 1.12.1! IntlRo and IntlYen also work.
<img width="498" alt="yay" src="https://cloud.githubusercontent.com/assets/1572318/25792802/df3a7fd2-3403-11e7-9d54-4deef08635f2.png">

**Comment by richardkazuomiller** [comment]
Strange. I've had issues particularly with using `[` and `]` keys to switch tabs on some machines and not others. Today I rebooted my computer (I probably updated VSCode in the process) and started having problems in 1.12.1 that I didn't have before. `shift+cmd+]` and `shift+cmd+[` don't work but `shift+cmd+@` and `shift+cmd+[` do what the expected shortcuts are supposed to, respectively just as the OP stated.

On another machine, it was always like that and I just got used to it, but then I switched to a new computer (the one I just updated) and keyboard where all the buttons worked as expected and was happy. Now I am sad.

I tried to fix it by defining custom keybindings, and for some reason `@` is recognized as `[`, `[` is recognized as `]` and `]` as `\` for some reason.

The attached image is what I see when I push `cmd+shift+]`. Why don't I see things like `[BracketLeft]`?
![screen shot 2017-05-11 at 23 15 27](https://cloud.githubusercontent.com/assets/1243814/25954139/58b263b8-36a0-11e7-940a-c049686b9d38.png)

**Comment by richardkazuomiller** [comment]
To clarify, if I type `@`, `[`, or `]` in an *editor*, they work. It's just keyboard shortcuts that are wonky.

**Comment by alexandrudima** [comment]
@richardkazuomiller 

Let's check you have something similar to the OP:
* What physical keyboard are you working on? Is it an ANSI, ISO or JIS keyboard? I can try finding some resources online to help you identify it if you don't know what I'm talking about.
* Are you using the laptop keyboard or a keyboard attached to the laptop. If you're using an external keyboard, are the built-in keyboard and the external keyboard of the same type: ANSI, ISO, JIS.
* If you use an external keyboard that is not Apple branded, did you configure it correctly with OSX?
* What keyboard layout do you use in OSX?
* What keyboard layout do we detect if you open an editor and press `F1 > Developer: Inspect Key mappings`. Could you save that to a file and attach it here?

**Comment by richardkazuomiller** [comment]
I'm using a JIS keyboard on a Mac Mini, specifically [this keyboard](https://www.logicool.co.jp/ja-jp/product/multi-device-keyboard-k380). As far as I know it's configured correctly, haven't had any other problems with it until today. `Inspect Key mappings` says:
```
{
	"id": "com.google.inputmethod.Japanese.Roman",
	"lang": "en"
}
```

**Comment by landonepps** [comment]
Does it work if you use the mac's default kotoeri IME instead of the google one?

**Comment by richardkazuomiller** [comment]
Same result for all input methods (Google Alphanumeric, Google Hiragana, Kotoeri Romaji, Kotoeri Hiragana).

**Comment by richardkazuomiller** [comment]
I also added US in OSX preferences and tried that for good measure, same result of those keys being switched.

**Comment by richardkazuomiller** [comment]
[keymappings.txt](https://github.com/Microsoft/vscode/files/993384/keymappings.txt)

Sorry, didn't attach the file

**Comment by richardkazuomiller** [comment]
My current workaround is doing this:

```
  {
    "key": "shift+cmd+]",
    "command": "workbench.action.previousEditor"
  },
  {
    "key": "shift+cmd+\\",
    "command": "workbench.action.nextEditor"
  },
  {
    "key": "cmd+]",
    "command": "editor.action.outdentLines"
  },
  {
    "key": "cmd+\\",
    "command": "editor.action.indentLines"
  }
```

**Comment by alexandrudima** [comment]
@richardkazuomiller Thank you for getting back to us.

I think this might be an issue within our C++ code that reads the keyboard layout from the OSX - https://github.com/Microsoft/node-native-keymap

The C++ module works by reading the current keyboard layout, and then proceeds to use OSX APIs to convert all scan code + modifier combinations to produced characters. In this case (by looking at the `keybindings.txt` you attached), the module reports that `@` is produced only via `Shift+[Digit2]`. i.e. 
```
"Digit2": {
	"value": "2",
	"valueIsDeadKey": false,
	"withShift": "@",
	"withShiftIsDeadKey": false,
	"withAltGr": "™",
	"withAltGrIsDeadKey": false,
	"withShiftAltGr": "€",
	"withShiftAltGrIsDeadKey": false
}
```

Looking at the picture this looks incorrect. It appears you have a scan code that produces `@` directly. I am sorry I cannot investigate this properly, because I only have access in the office to ANSI or ISO keyboards. And it appears OSX behaves differently based on using a JIS keyboard or not. If you would like to continue the investigation, it is very easy to get the node module up and running:

* pre-requisites: node.js
* clone from https://github.com/Microsoft/node-native-keymap.git
* npm install
* npm run test

This will output the mappings that we use in VS Code. And perhaps you can spot something fishy in that code or debug and see what's going on. Thank you!

**Comment by richardkazuomiller** [comment]
I haven't had time to look at any C++ code yet, but another weird thing started happening.

I have two projects open. In one window, the keyboard shortcuts I made work, the other they get overridden because VSCode started to recognize the keyboard properly. I've attached a screenshot.

Why does this happen in some windows and not others and how just make it do one or the other?

Strangely, the keymapping for `Digit2` has also changed to `"` in the window in which I took the screenshot. I've also attached the keymappings for that window.

[keymappings2.txt](https://github.com/Microsoft/vscode/files/998749/keymappings2.txt)



![screen shot 2017-05-14 at 0 30 23](https://cloud.githubusercontent.com/assets/1243814/26026774/faad5a2c-383c-11e7-9a33-8f379ddf06c3.png)

**Comment by richardkazuomiller** [comment]
So weird ... I closed and reopened the window that was recognizing they keyboard input wrong at the time I first commented on this issue, and it start working. Same keyboard, same process (haven't exited VSCode since I posted this), just different window. If I figure out how to reproduce the issue someday I guess I'll come back then.

**Comment by alexandrudima** [comment]
@richardkazuomiller This is most weird. Are you perhaps switching between two different keyboard layouts **and** between two different physical keyboards? The C++ methods we're using have the ...last... word in them. So that might make a difference, i.e. what was the last physical keyboard that was used before that code executes... I'm sorry I'm not an expert either in the OSX APIs.
