### ISSUE TITLE
Salsa: bogus intelli-sense proposal

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#2386]
* Have the following code:
```
Person.prototype.getName5 = function getName() {
  return this.name;
};

Person.getNa
```
* Trigger intelli-sense on the last line, last column, getNa*
* The first two proposals are bogus and should not appear.

![screen shot 2016-01-26 at 17 16 27](https://cloud.githubusercontent.com/assets/1926584/12586452/9a009f7e-c450-11e5-94f9-ac2fea7fc18d.png)

**Comment by mousetraps** [comment]
Yeah, getNa should not appear in the completions list because it's redundant, but the *appearance* of getName is actually intentional because JavaScript is a dynamically typed language, and we're not going to always get things right, so we want to provide a gracefully degrading experience (listing all the identifiers) rather than trying to be smart and showing nothing at all. This way, at the very least, it acts as code-completion of you already know what you want to type. The problem here, then, is they these identifiers should be better sorted by confidence (getName5, then getName), not alphabetically. 

In VS, in addition to sorting by confidence, we've considered demarcating the the lower confidence results w/ various styling attributes (eg removing the icon, changing the color) but I don't think we ended up landing on anything just yet. 

Cc @bowdenk7

**Comment by egamma** [comment]
The proposal `getNa` is not helpful and it should not be proposed, even when it is an identifier at this point.

We have changed the icons in the proposal to distinguish inferred and proposal better.
![proposal2](https://cloud.githubusercontent.com/assets/172399/12647353/011b9b16-c5d5-11e5-814b-686a8e1e4ea3.png)

![completion](https://cloud.githubusercontent.com/assets/172399/12647278/a350504e-c5d4-11e5-8ef7-4ac8af636622.png)

Moving to Salsa

**Comment by egamma** [comment]
This issue was moved to Microsoft/TypeScript#6693
