### ISSUE TITLE
Salsa: werid rendering of hover for arguments with jsdoc

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#2387]
Have the following code

```
/**
 * A person
 * @constructor
 * @param {string} name - The name of the person.
 * @param {number} age - The age of the person.
 */
function Person(name, age) {
    this.name = name;
    this.age = age;
}
```
Hover over age. The information message starts with a dot and is not centered and not aligned nicely. I would expect the hover space to be used in a better way.

![screen shot 2016-01-26 at 17 22 16](https://cloud.githubusercontent.com/assets/1926584/12586683/91bc028a-c451-11e5-96d0-5fb4f379ddcb.png)

**Comment by egamma** [comment]
This is caused by us rendering the strings as markdown and the description starts with a '-'. 

Change the description to (no dash after name) then the hover is rendered properly.
`@param {string} name The name of the person.`

This also looks like the suggested style, see http://www.2ality.com/2011/08/jsdoc-intro.html
