### ISSUE TITLE
How to get back the HTML from previewHTML?

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#23897]
From @mike-lischke in https://github.com/Microsoft/vscode-extension-samples/issues/12

> I have successfully implemented an interactive network graphic using D3 and the previewHTML feature. This is pretty cool, many thanks for that.
> 
> However, how would I read out the generated svg to e.g. to store it on disk? Is it possible to read back what is currently in the preview?

**Comment by mjbvz** [comment]
@mike-lischke Two options for sending data from a html view back to your extensions:

* Use commands. Take a look at what the markdown extension does for scroll sync for an example. [Here's the previewHtml js file for sending commands](https://github.com/Microsoft/vscode/blob/master/extensions/markdown/media/main.js#L208) and the [command handler in the extension](https://github.com/Microsoft/vscode/blob/master/extensions/markdown/src/extension.ts#L141).
* Setup a socket or websocket or server in your extension code and call it from the webview. This allows more control over passing data between your extension and the webview

**Comment by mike-lischke** [comment]
Thanks for your answer @mjbvz. It looks like your second link got a bit wrong. Is it that you actually meant [this line](https://github.com/Microsoft/vscode/blob/master/extensions/markdown/src/extension.ts#L107)? So, the trick is to send a command (the command itself doesn't seem to matter, right?) with the entire svg code encoded in an URI and then in the extension parse that URI and save that data? Woah, what an ugly hack.

However, that doesn't bring me a single step forward. My problem how to get the svg code is not solved by this approach. I would need a way to trigger code in my previewHTML content, so that it can actually send back the data. The same problem would exist with a socket approach. I first need to tell the previewHTML window that is should send the data.

**Comment by mjbvz** [comment]
Yes, that the correct location. The code lines shifted in master after I posted this

As for getting the svg data itself, that's not unique to vscode. The same logic you use for any webpage should work here: just embed some js that gets the svg element's content. For inline svg, using an [xml serializer as described here](http://stackoverflow.com/a/12865606/306149) should work

**Comment by mike-lischke** [comment]
Yes, I got this idea already, thanks. My main problem is still how to trigger the retrieval. Can I call a JS function in the preview HTML code in some way?

**Comment by mjbvz** [comment]
For editor -> preview communications, see the` _workbench.htmlPreview.postMessage` command and its use in the markdown extension
