### ISSUE TITLE
When I select one area to delete, the chosen area won't disappear. This is not convenient.

### ISSUE THREAD

**Issue by liuyuanyangscript** [Microsoft/vscode#23908]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T13:56:35.908Z)
- OS Version: Darwin x64 15.5.0
- Extensions: none
---

Steps to Reproduce:

One problem:

When I select one area to delete, the chosen area won't disappear, this is not convenient. 

<img width="773" alt="before delete" src="https://cloud.githubusercontent.com/assets/5757051/24687982/9b6871a2-19ef-11e7-92ef-89920378d78b.png">
<img width="759" alt="after delete" src="https://cloud.githubusercontent.com/assets/5757051/24687984/a0881944-19ef-11e7-9cc6-274fe403902e.png">

**Comment by rebornix** [comment]
@liuyuanyangscript can you tell us what command you use to delete the selection?

**Comment by liuyuanyangscript** [comment]
I used macbook pro's touchpad with three fingers action.  

details are here:

<img width="586" alt="1" src="https://cloud.githubusercontent.com/assets/5757051/24735735/ebfcb318-1ab6-11e7-9a72-d12c53f70c68.png">

**Comment by liuyuanyangscript** [comment]
And used 'delete' key on keyborad to delete the code.

**Comment by 0x80** [comment]
I have this issue as well. It drives me nuts! 

For me it only happens when selecting the text in reverse (from back to front). The selection stays while you start typing, and it messes up the code below by overwriting code that you didn't initially select. 

I think the issue might be related to Chromium, since I have a very similar problem with Chrome (Google Inbox and just google search and things). I filed a [bug report](https://bugs.chromium.org/p/chromium/issues/detail?id=708270) for that with a [demonstration vide(https://vimeo.com/153923660). The people on that list can't seem to reproduce it though 😨 

I hope someone can nail it, since it is biting me multiple times a day.

I'm using MacOS Sierra.

**Comment by alexandrudima** [comment]
I believe this issue shares the same root cause as #6478

Basically, we do not cancel mouse dragging operations when a non-modifier keypress occurs.
