### ISSUE TITLE
TS/JS Path Quick Suggestion IntelliSense Does Not Work Unless QuickSuggestions.strings is enabled

### ISSUE THREAD

**Issue by Syllinger** [Microsoft/vscode#23962]
- VSCode Version: 1.11.0
- OS Version: Windows 7

Steps to Reproduce:

1. type import or require statement
2. autocompletion works for keywords
3. begin to type relative directory in quotes, but receive no suggestions

**Comment by kieferrm** [comment]
@Syllinger can you give us an example project that doesn't work for you. I just opened the vscode source workspace on Win7 and I get file path completion proposals:

<img width="383" alt="screen shot 2017-04-05 at 4 45 58 pm" src="https://cloud.githubusercontent.com/assets/4674940/24731506/67445f8c-1a1f-11e7-8b77-3a4ece210476.png">

**Comment by Syllinger** [comment]
The problem persists across projects. It's as though path autocompletion in intellisense is disabled. Updated to the latest version, and it suddenly no longer works.

**Comment by chrmarti** [comment]
@Syllinger Could you attach a small sample project that reproduces the problem?

**Comment by aaronbalthaser** [comment]
I have this same problem. Can you guys please fix this. This is a nightmare developing with a large Angular 2 project.

**Comment by ZhangPuXi** [comment]
I also met this problem, you can just create two js file named a and b, an in file a requires b, there is no tip.

**Comment by mjbvz** [comment]
I'm also unable to reproduce this in a simple project like @ZhangPuXi describes. Both `import` and `require` show completions for both files and directories

To help investigate, please:

* Disable all extensions to make sure one of them is not causing problems. Just launch code with the `--disable-extensions` flag to do this
* Share a small project and your settings with us
* Describe the repo steps and the expected behavior in detail, such as:

   > hit ctrl+space in `require('./|')` and completions for `abc.js` and `folder1` are shown

You can also try collecting the TSServer trace:

1. Set `"typescript.tsserver.trace": "verbose"`
2. Restart VSCode
3. Try to trigger the completion
4. Go to the output panel and share the output from the TypeScript section

Thanks

**Comment by ZhangPuXi** [comment]
I have no extensions, and the ctrl+space is used by input method switch. In the last version, I don't need to hit ctrl+space, completions are shown automatically

**Comment by mjbvz** [comment]
@ZhangPuXi Can you try setting:

```
"editor.quickSuggestions": {
        "other": false,
        "comments": false,
        "strings": true
    }
```

I suspect the default `"strings"` setting may be disabling these automatic suggestions for ts/js imports

Can you also confirm that you can manually trigger suggestions and do see the file/directory completion items. ctrl+space is the normal keybinding but yours may be different. Look for what is bound to `editor.action.triggerSuggest`

**Comment by ZhangPuXi** [comment]
Thanks for your time and patience, I have confirmed, I set the editor.action.triggerSuggest to Ctrl + T, it works, but the problem is even though I set the quickSuggestions as you said, the automatic suggestions doesn't work. Please help me the VSCode is my favorite editor. ^-^

**Comment by ZhangPuXi** [comment]
The setting 
```
{
  "other" : true,
  "comments" : false,
  "strings" : true
}
```
works well. Maybe you should modify the default value to this, thanks a lot.

**Comment by mjbvz** [comment]
@jrieken, let me know if you have any thoughts on enabling quick suggestions selectively for js/ts imports.

For directories and files, we could create a new completion item provider that triggers on `.` and `/` for example. This would not fix the case where you are importing a module however

**Comment by aaronbalthaser** [comment]
I updated my settings and now it works. Thank you.

**Comment by IRCraziestTaxi** [comment]
Thanks, setting "strings" in "editor.quickSuggestions" to true works. My question is: why did quick suggestions work before without that setting but not after this update?

**Comment by mjbvz** [comment]
@IRCraziestTaxi Before QuickSuggestions was a binary on/off setting. 1.11 allows finer grained control so that you can disable or enable them just in comment and strings. Since js import paths are just strings, the default setting will disable disable suggestions for these as well

**Comment by Syllinger** [comment]
@mjbvz: worked for me as well. Thank you!

**Comment by cortopy** [comment]
I'm also experiencing this issue since April releases. I've changed the settings and "sort of" works. Autocompletion for paths now works when I type the first letter. However, the editor used to suggest possibilities as soon as I typed each forward slash "/". So I still need to go to the folder to see what the options are.

Any chance of getting the old behaviour back?

**Comment by cortopy** [comment]
I got it back!!! I updated the Path Intellisense extension and it's now back to normal
