### ISSUE TITLE
VSCode 1.11 - Performance Profile

### ISSUE THREAD

**Issue by macsf** [Microsoft/vscode#23994]
[5b8b_main.cpuprofile.txt](https://github.com/Microsoft/vscode/files/901647/5b8b_main.cpuprofile.txt)
[5b8b_renderer.cpuprofile.txt](https://github.com/Microsoft/vscode/files/901646/5b8b_renderer.cpuprofile.txt) 

- VSCode Version: <code>Code 1.11.0 (9122ec4b1068bd391e41974f46a4b54c1b9c90f9, 2017-04-05T20:52:01.201Z)</code>
- OS Version: <code>Darwin x64 16.5.0</code>
- CPUs: <code>Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)</code>
- Memory (System): <code>16.00GB (10.75GB free)</code>
- Memory (Process): <code>220.51MB working set (0.00MB peak, 124.59MB private, 126.50MB shared)</code>
- Load (avg): <code>1, 2, 2</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>yes</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|66|
|main|app.isReady => window.loadUrl()|258|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|438|
|renderer|require(workbench.main.js)|795|
|renderer|create extension host => extensions onReady()|16268|
|renderer|restore viewlet|0|
|renderer|restore editor view state|427|
|renderer|overall workbench load|625|
|main + renderer|start => extensions ready|17858|
|main + renderer|start => workbench ready|2199|

---

:warning: Make sure to **attach** these files: :warning:
-`/Users/sutthichok/5b8b_main.cpuprofile.txt`
-`/Users/sutthichok/5b8b_renderer.cpuprofile.txt`

**Comment by jrieken** [comment]
wow, everything seems fast except for 17seconds to start the extension host...

**Comment by jrieken** [comment]
@bpasero to clarify what `create extension host => extensions onReady()` actually is and @sandy081 because I think it is just the time we spend on the main side parsing `package.json`-files.

**Comment by bpasero** [comment]
I have seen the parsing of package.json becoming slow the more extensions are installed. The time we measure starts from [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/electron-browser/shell.ts#L374) and is from creation of `MainProcessExtensionService` until it reports `extensionService.onReady`.

**Comment by sandy081** [comment]
@bpasero @jrieken Looks like the attached profiles are not capturing the 17s main+renderer time box. Any idea how to get this data?

**Comment by jrieken** [comment]
Profiling stops with `onWorkbenchDone`-event. Unsure if that is too early or not @bpasero ?

**Comment by bpasero** [comment]
@jrieken yes, workbench signals being ready before extensions are loaded. we do not block any editing or commands when extensions are still loading so we declare the workbench as being done loading after editors and viewlets have restored. The extension host ready event can come in later. If we continue the profiling until this is done, we might capture a lot more from what the user is doing until the extensions are loaded.

**Comment by jrieken** [comment]
Thin ice because we do allow some extensions like VIM to overwrite our commands but I understand the motivation. 

Agree, we should profile for a little longer, e.g until `onReady` fires

**Comment by sandy081** [comment]
Thanks guys for explanation.. Since we do not have profiles of what happening during that time.. not sure if it is clear to assume that 16s time is being taken for parsing extension descriptions (`package.json`). Probably we need more user input here like

- How many extensions are there
- Are there any large package.jsons

**Comment by jrieken** [comment]
@macsf Can you try again with todays (11/04) insiders build? That should profile the whole thing

**Comment by sqnkov** [comment]
@jrieken extension host seems to be the only issue that keeps on appearing again and again. I have opened and closed 3 or 4 issues already and the problem is not solved. I type for half an hour really fast, autocomplete stops, I continue on typing for about half an hour without it, it appears for 2 minutes again, disappearing moments after.

**Comment by jrieken** [comment]
@sqnkov Please do not highjack issues because it makes things fuzzy and in the end no ones knows what is being talked about. 

> From a software-development point of view, is this a limitation of using browser engine solutions?

I am aware that these days it is en vouge to think using a browser engine isn't smart but I doubt that discussion is related to this issue. *All* extensions, including the built-in extensions like CSS, TS etc, run in a separate (node) process. Since all extensions share that one process, a crazy while-true-looping extension, will bring all other extensions to a halt, but not the editor (you can still type, save, exit). 

I'd say that in your case that happens, and it's not one an external extension but a built-in extension. The latter aren't disabled when you run with `--disable-extensions`. I'd say, continue to try to reproduce and give us an issue with precise steps because we can only fix issues that we can reproduce. 

Thanks and Happy Coding

**Comment by sandy081** [comment]
Related #28331
