### ISSUE TITLE
File from UNC-folders twice time opened in same instance after changes

### ISSUE THREAD

**Issue by mkszepp** [Microsoft/vscode#24003]
- VSCode Version: 1.11.0 / 1.12.0-insider
- OS Version: Windows 10 x64

Steps to Reproduce:

1. open a single file which is in an UNC folder
2. press any keys / undo changes
3. file is opend two times in the same window

Problem is also on other PC's

![problem](https://cloud.githubusercontent.com/assets/19845290/24742248/b959ee2e-1aa9-11e7-9aa7-58f376a100c2.gif)

![problem2](https://cloud.githubusercontent.com/assets/19845290/24742428/7b939f9e-1aaa-11e7-87a4-344e9b3bf627.gif)

**Comment by bpasero** [comment]
@mkszepp on each editor can you run from the command palette "Copy Path of Active Path" and paste it here? I wonder how the paths are different.

**Comment by josheinstein** [comment]
I am seeing similar behavior since the latest update, but I am unable to reproduce it reliably. In my case, what's happening is extremely frustrating because three times now, a modified file has reverted to the saved version while I am typing. File still appears dirty in the tab, but the undo buffer is gone (along with the changes since the last save.) Another copy of the file (not dirty) is opened in a separate tab when this happens.

All three times it has happened on files with a UNC path.

**Comment by bpasero** [comment]
@mkszepp @josheinstein I tried to reproduce using the UNC localhost trick (\\localhost\c$\...path) and could not. I appreciate if this happens again to copy the path of all opened editors to see where the difference is 👍

**Comment by mkszepp** [comment]
@bpasero 
the problem from @josheinstein was exactly also my problem.
Yesterday i have done a downgrade to 1.10.2 and now after the upgrade to 1.11.1 i can't reproduce it.

Is it possible that windows has cached something?

**Comment by bpasero** [comment]
No I rather think that this issue is not as obvious to reproduce. I would still like to understand if this is a regression from the 1.11 update or not (e.g. have people seen this before).

**Comment by mkszepp** [comment]
@bpasero now i have got the same error. The path is exact the same (also with the Copy Path of Active). Also the content is the same (i see my unsaved changes in every two windows

![grafik](https://cloud.githubusercontent.com/assets/19845290/24806163/3d72ca22-1bb4-11e7-9466-0a168e3e379d.png)

**Comment by bpasero** [comment]
@mkszepp the path seems to have different casing though, so it is not character identical? Can you confirm?

**Comment by bpasero** [comment]
@mkszepp can you try the same steps without enabling extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces.

**Comment by mkszepp** [comment]
@bpasero 
yes
i think the problem is, that my opend file is `\\Tuk` "T" uppercase and vscode open automatically the file with "t" lowercase `\\tuk`

**Comment by bpasero** [comment]
@mkszepp I wonder why though, can you try https://github.com/Microsoft/vscode/issues/24003#issuecomment-292565950

**Comment by mkszepp** [comment]
@bpasero same problem also without extensions

**Comment by bpasero** [comment]
@mkszepp I am trying to understand what action you are doing that is causing the other file to open. Does it also happen if you have a plain text file and type in there?

**Comment by mkszepp** [comment]
@bpasero at the moment only with css files. I have tried with css files 100+ lines, when there are more lines there is 
with js files i got the bug that he has removed some part which was not saved, but the files was not opend twice time

**Comment by bpasero** [comment]
@mkszepp could it be that you are hitting format on save? did you configure that?

**Comment by mkszepp** [comment]
@bpasero 
can you try it with following css (is the css from MS page):
[test.zip](https://github.com/Microsoft/vscode/files/906196/test.zip)

i have no "formatter on save" active.
here is my setting file
![grafik](https://cloud.githubusercontent.com/assets/19845290/24810700/8250086c-1bc3-11e7-8af9-60589a7a3782.png)

**Comment by bpasero** [comment]
I am trying to reproduce but fail, to simulate UNC I open `\\LOCALHOST\c$\someFolder` and I even use uppercase `LOCALHOST` just to see if that makes a difference. I can edit in that CSS file without a second tab opening.

**Comment by bpasero** [comment]
@mkszepp I was able to reproduce when I invoked a command that goes to the extension side (in this case rename symbol). I very much believe now that this is https://github.com/Microsoft/vscode/issues/24038

**Comment by mkszepp** [comment]
@bpasero i can reproduce the problem also `\\localhost`

![grafik](https://cloud.githubusercontent.com/assets/19845290/24811062/e14f9c32-1bc4-11e7-8b3a-057e052245e0.png)

yes, maybe the other problem solves also my problem

**Comment by bpasero** [comment]
Actually let's keep them separate, I am not sure its the exact same issue.

@jrieken to reproduce:
* on Windows open the file from https://github.com/Microsoft/vscode/issues/24003#issuecomment-292591142 in an empty workspace by opening it via the UNC localhost notation using uppercase authority: `\\LOCALHOST\c$\pathToFile\test.css`
* rename symbol on anything
=> after a while a second editor opens dirty with the authority being lowercase (`localhost`). 
=> I think what happens is that the extension host is doing an edit on a model where the URI does not match the model on the main side and as such a new model is entering the workbench (which I then open as dirty because it is different).

**Comment by josheinstein** [comment]
Sorry to chime back in late, but I figured I would add a few data points in case it helps track it down. Unfortunately, I am a bit tied up today to try to reproduce it, but some facts about my scenario:

- I too was editing a file that was on UNC path with a mixed-case server name. It's an automatic file share set up by Parallels from Mac host to Windows guest, so the path is \\Mac\Dropbox\Path\To\File.
- I didn't notice if the second tab had a different casing for the path.
- The file I was editing was a PowerShell *.ps1 file, with the PowerShell extension installed.
- The problem seems to occur while I'm typing, not when the editor is idle.

Hope this helps.

**Comment by mkszepp** [comment]
@bpasero @josheinstein can you try following steps, so i can reproduce always

1. open vscode (default there is open "Untitled-1"
2. close "Untitled-1"
3. put your file in vscode
4. add some lines in first block like width: 100%; display: block; and save file
5. make doubleclick in tabbar on the top (now there is opend a untitled
6. close untitled
7. revert changes in your file
8. add display:block or something
9. remove it and save.
10. press any key

**Comment by jrieken** [comment]
@bpasero The problem is the `ResourceMap` which blindly uses the `fsPath` property which is *not* normalised, esp wrt authority casing et al. So, somewhere `\\LOCALHOST\foo\bar` is cached and for some reason an URI pointing to the same resource with the lower-cased authority comes in which is causing a cache miss
