### ISSUE TITLE
Feature request: Input available in the debug console

### ISSUE THREAD

**Issue by delian** [Microsoft/vscode#24010]
- VSCode Version: 1.11.0
- OS Version: Mac OS X 10.12.3

You cannot debug any program which requires Input from the standard input because the debug console does not support input (in particular with Node.JS).

So the feature request is the ability to select the Debug Console output window and send there input (keystrokes), while preserving the bottom console input.

**Comment by weinand** [comment]
@delian by default, node debugging uses the debug console which does not support reading input (because it is a REPL too). Please add a `console` attribute to your launch config and set it to either `integratedTerminal`or `integratedTerminal`.  See documentation: https://code.visualstudio.com/docs/editor/node-debugging#_node-console
