### ISSUE TITLE
Errors in files of the workspace not counted in the status bar

### ISSUE THREAD

**Issue by owenders** [Microsoft/vscode#24032]
- VSCode Version: 1.11.0
- OS Version: MacOs X 10.12.3

Steps to Reproduce:

1. I open a website folder in VS Code (if I understand well this folder is now the workspace)
2. This folder contains scss files with errors
3. But the status bar shows 0 error and 0 warning
4. I have to open the files with errors to finally have the status bar showing the errors (scss errors)
5. So the problem is that the errors are only reported in the status bar for the open editors and not for the files in the whole workspace.

Thanks in advance to solve this problem.

Kind regards,
Olivier

**Comment by aeschli** [comment]
That's by design: Only files open in editors are validated by our built in language supports.
Problem is that we lack the knowledge which files belong to your project. That's knowledge that you typically have in your build files.
To have a folder / project wide validation, we recommend to create a task that analyses the output of your build files. See https://code.visualstudio.com/docs/languages/css#_transpiling-sass-and-less-into-css as an example.
