### ISSUE TITLE
Renaming a file with just character casing changes and editing it with any editor action like rename symbol, opens a file with the previous name and edits it

### ISSUE THREAD

**Issue by theofanis** [Microsoft/vscode#24038]
- VSCode Version: Code 1.11.0 (9122ec4b1068bd391e41974f46a4b54c1b9c90f9, 2017-04-05T20:59:05.375Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|rest-client|humao|0.14.0|
|mssql|ms-mssql|0.3.0|
|csharp|ms-vscode|1.8.1|
|debugger-for-chrome|msjsdiag|2.7.2|
|vscode-docker|PeterJausovec|0.0.13|
|sort-imports|peterjuras|2.3.1|
|vscode-icons|robertohuertasm|7.5.1|;

---

I'm not even sure I have correctly titled this... But for whatever is worth here's the steps...

Steps to Reproduce:

1. Create a file, typescript in my case (reproduced with C# file as well), let's say `test.ts`.
2. Rename it changing just the character case, like `test.ts` -> `Test.ts` (or change casing for all letters, doesn't matter as long as only character casing is changed) using rename from folder view.
3. Rename a symbol using right-click, or just reference a module and import it using `Ctrl + .`, just so the file is edited not manually but by an editor action.
4. The previously named file will open in the editor with the change that was made, so `test.ts` will open and include the change made and `Test.ts` will still show contents without changes.
5. Save the `test.ts` file, close it, now`Test.ts` shows the correct contents.
6. Repeat steps with any change that is done by the editor (like rename symbol) and this goes on indefinitely, a file with the previous name is opened. So a new rename to `TEST.ts` followed by an editor action like rename symbol, will open `Test.ts`.
7. Do any manual change in the file and just save it, the file is saved without opening the file with the previous name and shows correct content as expected.

This happens with git tracked files as well as entirely new files not yet tracked by git. Moreover, it happens with and rename that is only a character case change, doesn't matter how many character casings are done, so `Test`, `TEST` etc. should behave the same.

**Comment by smorzhov** [comment]
Also for .js files.

**Comment by theofanis** [comment]
I guess this happens with most, if not all, file types, as long as the editor is able to offer an edit action on the file's contents.

I can reproduce this bug with a first time installation of VS Code 1.11.0 on a clean Windows 10 machine as well.

Fyi, normal renames, that is changing the name, behave as expected, so `test.ts` to `old.ts` doesn't expose this issue.

**Comment by chrmarti** [comment]
Similar to #24003

**Comment by chrmarti** [comment]
Can reproduce with all extensions disabled. E.g., renaming a local variable in a .js reproduces it, while formatting a .js or just editing it does not.

**Comment by bpasero** [comment]
I do not think this is related to #24003. The workbench will open any dirty buffer so that users are able to track changes that are made (otherwise those would be hidden). In this case I suspect that the TS service still thinks the file is in uppercase (e.g. it did not correctly handle the rename) and then makes changes to the previous-cased version of the file which results in the workbench opening the buffer. 

@mjbvz to confirm that theory.

**Comment by theofanis** [comment]
I can reproduce with C# file as well.

**Comment by bpasero** [comment]
Right, this seems language independent.

@jrieken when I debug this I see that when I invoke rename, the resulting BulkEdit is still having a reference to the old, previous-cased version of the model. I wonder if this is a race condition, maybe you could check as well.

Steps:
* open a TS file
* rename to lowercase
* set a breakpoint to editorPart#openEditor() (to follow the stack all the way down)
* hit Rename
=> you should see the editor opening somewhere because BulkEdit pushes edits to a model that is using the casing of the previous version of the file

![image](https://cloud.githubusercontent.com/assets/900690/24787878/ef5742ee-1b6a-11e7-9a7f-c2a1b3dd9496.png)

**Comment by jrieken** [comment]
This is also the `ResourceMap` issue

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/24003
