### ISSUE TITLE
British Keyboard Layout: System keymaps overridden

### ISSUE THREAD

**Issue by jamesRaybould** [Microsoft/vscode#24044]
The system keymaps appear to have been overridden in the latest release. In all other applications using cmd + ` scrolls through all the open windows in that application. In the latest version it splits the editor window.

- VSCode Version: 1.11
- OS Version: OSX 10.10.5

Steps to Reproduce:

1. Open VSCode
2. Open another VSCode window
3. Attempt to scroll through the VSCode windows using cmd + ` 
4. It splits the current editor and doesn't scroll though open VSCode windows

**Comment by chrmarti** [comment]
@jamesRaybould Which keyboard layout (language, region) do you have?

**Comment by jamesRaybould** [comment]
Its `British - PC` - I've attached the `keylayout` I'm using in the operating system

[British (PC 105).keylayout.zip](https://github.com/Microsoft/vscode/files/903545/British.PC.105.keylayout.zip)

**Comment by alexandrudima** [comment]
@jamesRaybould Thank you for the extra information. Could you please also attach how our C++ node module detects your keyboard layout:

* open an editor
* press `F1 > Developer: Inspect Keyboard Mappings`
* save the information to a file and attach it here.

I will then take a look and check if the split editor action (bound to key code combinations `cmd+\`) is correctly mapped. 

---

However, most likely:

Please note that we do not ship with keyboard layout specific default keybindings, and therefore some actions might be unbound by default, or they might be bound to unhappy / unfortunate / poor key combinations. This is something you can upvote in #1240

**Comment by jamesRaybould** [comment]
[vscode_keymap.zip](https://github.com/Microsoft/vscode/files/905369/vscode_keymap.zip)

**Comment by alexandrudima** [comment]
@jamesRaybould I believe this might have been fixed with the fix for #24153 i.e. on ISO keyboards Chromium swaps the `KeyboardEvent.code` of `[Backquote]` and `[IntlBackslash]` which produce `` ` `` and `\`, so it sounds like we would get confused about `` cmd+` `` and ` cmd+\ ` due to this. We have added a workaround on our side where we "unswap" them. 

In certain cases (where the computer has an ANSI built-in keyboard and an ISO keyboard is attached to it), it might take up to 3 seconds after the first keypress for us to detect this case and apply the workaround.

Could you please try again in the latest stable release or [in the insiders version](https://code.visualstudio.com/insiders) ?

Here is what I am trying and `` cmd + ` `` now cycles through the windows (i.e. works for me):
* British - PC keyboard layout
* attached external ISO keyboard:
![screen shot 2017-05-05 at 17 48 00](https://cloud.githubusercontent.com/assets/5047891/25753228/04291f92-31bb-11e7-83c3-20f6cf3dfe85.png)
* enabled the setting of `` cmd+` `` moves focus to the next window
![screen shot 2017-05-05 at 17 48 53](https://cloud.githubusercontent.com/assets/5047891/25753259/2276a3a2-31bb-11e7-873a-31687f147354.png)
