### ISSUE TITLE
Default keybinding problem

### ISSUE THREAD

**Issue by EmmanuelBeziat** [Microsoft/vscode#24084]
Hi,

Just got the new 1.11 version, and there’s a problem on macOS:

![combinaisons_de_touches_-_lmde bac_2017-04-06_17-22-01](https://cloud.githubusercontent.com/assets/6781337/24762197/ee476d0c-1aed-11e7-9a74-993ff03b052c.jpg)

This key combination is the actual one for doing a pipe character: |
As it’s a very common symbol in dev, this shorcut really should be changed, or it will lead the large majority of macOS users to change the default key map.

Thanks!

**Comment by chrmarti** [comment]
Which keyboard layout are you using?

**Comment by EmmanuelBeziat** [comment]
Apple Keyboard, Azerty (french)

**Comment by alexandrudima** [comment]
We do not ship an action called "Bookmarks (Selection): Expand Selection to Next" AFAIK. Please contact the extension that contributes this action.

**Comment by EmmanuelBeziat** [comment]
I had the extension for months, and it just happened after the VSCode update (not the extension update). There's something behind this.

Here’s a same request on the Githubs issues of the plugin: https://github.com/alefragnani/vscode-bookmarks/issues/63

**Comment by alefragnani** [comment]
Hi @alexandrudima , 

I tried (really 😫  ) to _digest_ the information from [this issue you posted](https://github.com/Microsoft/vscode/issues/17521) and [the wiki section](https://github.com/Microsoft/vscode/wiki/Keybindings), to better understand the [Improved keyboard layout support](https://code.visualstudio.com/updates/v1_11#_improved-keyboard-layout-support) available in 1.11 release.  I understand the hard work you had to improve this, on all platforms, but I missed one point: What can/must we, extension developers, do from now on?

I had a similar problem right at the beginning, because I used `Ctrl + Alt` on other commands. I ignored (by ignorance) the `Developer Tools` warning, and users from Sweeden and Germany reported issues with that.

So, how can we, extension developers, avoid messing with _non-US Layout_ while defining keybindings for extension commands? Is there a **safe way** to define keybindings? I mean:

* I learned (after the first reported issue) I can't use `Ctrl + Alt`. 
* Should I avoid using `Shift + Alt` too (based on this issue)?
* Should I avoid keybindings at all?

Looking closer to VSCode core commands I noted that you use a lot of `Ctrl`, `Ctrl + Shift` and `Ctrl + K ?` (chord). Is this a _safe way_?

Thanks for your help

**Comment by alexandrudima** [comment]
@alefragnani 

I am sorry about the breakage with our switching to scan code based dispatching.

We have the same problem with the core actions. i.e. it is nigh-on impossible to come up with any default that would work on all keyboard layouts and not suck.

I don't have a good answer except perhaps #1240. 

e.g. perhaps a way where you could specify you'd want to contribute a keybinding for `ctrl+alt+L`, but only on a US standard keyboard layout and have it unbound on any other keyboard layout. This is complicated by the fact that:
* sometimes we cannot even read an `id` for a keyboard layout (we get NULL from the OS)
* all identifiers for such keyboard layouts are different on OSX / Linux / Windows. e.g.: for the German keyboard layout: `com.apple.keylayout.German` on OSX, `de` on Linux, `1031` on Windows.
* people roll out their own custom keyboard layouts on each operating system.

**Comment by alefragnani** [comment]
@alexandrudima 

You don't need to be sorry about it. I tottaly understand the complexity of this subject. And breakages, are part of _evolution_ 👍 

After the original issue, I had decided to avoid defining keybindings for new commands, on any of my extensions. I found it to be a _safe way_. But for this one in particular, I wanted to _follow a pattern_ and added keybindings (using `Shift`) for these _selection commands_.

BTW, I am aware of #1240. It is already related to my original `Ctrl+Alt` issue 😄 

Thanks again for your help
