### ISSUE TITLE
BreakpointEvent causes all other breakpoints in file to be cleared

### ISSUE THREAD

**Issue by daviwil** [Microsoft/vscode#24164]
- VSCode Version: 1.11.1
- OS Version: Windows 10 Anniversary

Steps to Reproduce:

1. User starts debugging a file which spawns a debug adapter
2. User clicks breakpoints in the gutter of that file
3. Something happens in the debug adapter causing a BreakpointEvent to be sent back to the debugger client
4. New breakpoint icon appears on the appropriate line, all other breakpoint icons disappear

I've tried this with `reason` set to `new` and `changed`, same result.

**Comment by isidorn** [comment]
@daviwil I have looked into the code and am puzzled as to how this can happen.

* Can you double check if you still see this with vscode insiders? 
* Do you nicely send the id of the brekapoint in the event? 
* Could you actually post the json object you send here? 
* Are you sure there is no other communication between vscode and your debug adapter going on at that moment? 

Since looking at the [code](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/debugService.ts#L366) for the brekapoint event it seems impossible that other breakpoints disappear.

**Comment by isidorn** [comment]
Ping @daviwil to provide additional information

**Comment by isidorn** [comment]
Closing until more data is provided
