### ISSUE TITLE
"maccenteuro" encoding works but not accepted value!

### ISSUE THREAD

**Issue by Somnium7** [Microsoft/vscode#24229]
We have MSVSCode 1.11.1. We need file encoding "maccenteuro". I set it in settings manually - it works, however, it says that value is not accepted.

Moreover, when this encoding is enabled, search in multiple files is not working.

We can repeat it on Windows 10 and Mac OS 10.12.

**Comment by roblourens** [comment]
I don't see that encoding name in the whatwg's list of standard encodings - https://encoding.spec.whatwg.org/#names-and-labels - which is why it says it isn't supported, and isn't supported by our search tool. Apparently it is supported by iconv-lite, so it will work in the editor. You can try setting `"search.useRipgrep": false` as a workaround.

**Comment by Somnium7** [comment]
Thanks for workaround. You are not going to add full support for this encoding?

**Comment by roblourens** [comment]
To support it for ripgrep search, I believe this is the library that would have to support it: https://github.com/hsivonen/encoding_rs. It's probably unlikely since it seems to be a non-standard encoding.

**Comment by Somnium7** [comment]
OK. What is purpose of using ripgrep in MSVSCode? Does it has additional functionality or better performance or something else?

**Comment by roblourens** [comment]
It's very very fast
