### ISSUE TITLE
Request - show file path intellisense in *ignore files

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode#24269]
Test tour for MERN starter kit https://github.com/Microsoft/vscode/issues/22277

- VSCode Version: Insiders
- OS Version: macOS

Steps to Reproduce:

1. Clone MERN starter kit
2. Open `.gitignore` or `.eslintignore`

It would be great to show file path intellisense in these files. This is something I miss from WebStorm. 

![image](https://cloud.githubusercontent.com/assets/2449568/24819963/a9d87b8a-1b9b-11e7-9737-e9512b8e9243.png)

Note - that I did install the Path IntelliSense extension and it did not provide IntelliSense in this location.

**Comment by aeschli** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.
If you disagree and feel that this issue is crucial: We're happy to listen and to reconsider.
Maybe you want to give it a try yourself and provide the feature through an extension or a PR: We're happy to give advise and get you started.
Thanks for your understanding. Thanks for helping and happy coding!
