### ISSUE TITLE
Debugging UI gets crowded 

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode#24262]
- VSCode Version: Insiders
- OS Version: macOS

Steps to Reproduce:

1. Start a debugging session
2. Add a bunch of breakpoints

![breakpoints](https://cloud.githubusercontent.com/assets/2449568/24818566/e111a0d2-1b95-11e7-912c-a1d3b17e378a.gif)

A couple ideas on how to handle this better. 
- There seems to be a lot of wasted space for the variables section. We could move watchers up as breakpoints moves up. 
- I wonder how often watchers are used compared to breakpoints. My gut says breakpoints are much more. Maybe we switch those two UI elements.

**Comment by Spown** [comment]
you can resize thme manually
![](https://drive.google.com/uc?id=0B-OJBofmehO3anhuY1dpb3BXWkE)

**Comment by isidorn** [comment]
@waderyan thanks for feedback - let me try to describe the reasoning behind the currenty layout
* breakpoints is a special view which always has the size of the number of breakpoints up to 10. The reasons for this is that breakpoints are not expandle and are always a flat list
* Other views are adaptive and have a default size based on how important they are (variables most, then call stack then watch experssions). Each of this views can be resized and the size is persisted across vscode sessions for better customization

Now onto your comments
* Vasted space in variables -> you might feel like that but I have hear users complaining the opposite and maybe for more complex apps it makes more sense
* Your outline is not the default you have reduced the initial size of the call stack
* Watchers are used less but due to the implementation that a breakpoint view is expanding as it is added it needs to be at the end. Also breaking the muscle memory of users is not recommended
