### ISSUE TITLE
Feature Request - Search with more mode

### ISSUE THREAD

**Issue by FFengIll** [Microsoft/vscode#24301]
The search function will do search with whole workspace, may it be possible to control the mode?
- Search in current file.
- Search in opened files.
- Search in workspace.(current mode)

This may cost less and easy to use in some situations.

**Comment by pangeax** [comment]
* You can search the currently open file with **CTRL + F** instead of using the Search Bar (**CTRL + SHIFT + F**).
* You can also restrict the search results e.g. "search in one specific folder" or use a regex:
![image](https://cloud.githubusercontent.com/assets/16874688/24829911/a3e102e8-1c7b-11e7-9717-4bfeba99fa38.png)

**Comment by FFengIll** [comment]
@pangeax  
Yep, I know these functions.
I am just thinking to combine they two (show all target in dialog and click to navigate while **CTRL+F** too).
I have built a plugin to achieve it, and wonder if it is a general request.

**Comment by chrmarti** [comment]
You can also Find in Folder from the context menu on a folder in the Explorer.

**Comment by FFengIll** [comment]
@chrmarti  May I fork a branch to implement it?

**Comment by roblourens** [comment]
@FFengIll I don't think I want to add more buttons and controls to the search viewlet, especially since it's possible to use the existing tools to perform those searches.
