### ISSUE TITLE
Bottom panel shouldn't use 'x'

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#2432]
but some hiding indication.

**Comment by stevencl** [comment]
@jrieken can you tell me more? Why shouldn't it show the x? What sort of indication did you have in mind? What does the x make you think of and how is the behaviour not consistent with your expectations?

**Comment by jrieken** [comment]
This came to my mind when we said it not proper for  suggest details and then I see that viewlets don't have it but editors do. Since I can do the drag-down-to-hide-gesture an icon indicating that is maybe more applicable?

**Comment by isidorn** [comment]
Joao had the idea that we show some icon which could also go to the status bar once this is hidden. Clicking on that would open the panel again. The good thing about the icon in the status bar is that we could indicite if more output comes and not spam the user with opening the panel again.

Something similiar to this guy in chrome dev tools 
![screen shot 2016-01-27 at 15 03 07](https://cloud.githubusercontent.com/assets/1926584/12615647/34a03cea-c507-11e5-98ea-78b943be928a.png)

**Comment by stevencl** [comment]
The x closes the panel and is different from the action that collapses the panel down into the status bar. When we worked on the design we tried different options that placed a button in the status bar that would toggle the visibility of the panel. We didn't like that design due to the fact that the status and activity bars could become cluttered with all sorts of buttons to show UI. So we backed off that design.

However, the capability to drag the panel down into the status bar was not part of the original design. In fact, the design that we ended up with called for setting a minimum height of the panel. If we support the ability to drag the panel down into the status bar we may need to reconsider this but I really do worry about the precedent that will set and the risk of adding more UI to the product (even just one button in this particular case).

It would be interesting to know if toggling the panel with the menu commands and keybindings would work just as well. It's more efficient. Pressing Ctrl-U causes the panel to disappear and pressing it again causes it to come back up in the exact same state. In everything we do, we want to enable the user to spend as little time manipulating the UI of the product and as much time working on their code.

**Comment by csinco** [comment]
Hey guys, my two cents - in the viewlet case, it is hide/show, which is more of a preference on your overall UI layout.  For the bottom panel, the idea is that the user is closing the panel because they no longer need it, similar to tool windows in Visual Studio and even the dev tools in browsers.  So for close actions, we use X.  For hide/show, you could use an icon of sorts like a < or > but it may not be necessary.

Now, you could technically argue that hide/show/open/close/expand/collapse are all one-in-the-same.  I think the important thing to think about is what is the intention behind having the panel gone and not gone.

But overall, I agree with Steven about introducing an icon for controlling the presence of the bottom panel because this can lead to other questions like will that scale if we say introduce other panels in the future.  Then you start to get into a longer conversation about controlling the proliferation of tool windows/panels.  It can also lead to adding more view management controls which may honestly not be necessary.  We have this problem in VS with all the options to close, hide, float, auto-hide, dock tool windows.  Fun stuff.

Anyway, just my thoughts.  Looks like everything is going well.  Love the progress. :+1:

**Comment by bgashler1** [comment]
Just noticed this issue.  I agree with @stevencl and @csinco due to the fact that the clicking the "X" is actually causing the panel to close and not collapse.
