### ISSUE TITLE
@summary jsdoc support

### ISSUE THREAD

**Issue by Almenon** [Microsoft/vscode#24372]
========= Feature Request ============

It would be nice if @summary and @description paramaters were recognized in jsdocs to provide better intellisense.  I'd consider the description of what the function does to be more important than its types. Visual Studio already has this feature.

**Comment by mjbvz** [comment]
Thanks. This is being tracked upstream on the TypeScript side: https://github.com/Microsoft/TypeScript/issues/13650

**Comment by mjbvz** [comment]
This should now be fixed. For the code: 

```js
/**
 * @summary 
 * Get Document body.
 *
 * @description
 * Get the document body of the view. Sometimes, it is useful to render an
 * alert view or notify the user of something that have happened. These views
 * are owned by the document body, so to reference the document body, you use
 * `this.document`. And it is only, `ContentBaseView` and it derivatives that
 * has a reference to the document body.
 *
 * @example
 * 
 * ```
 * render () {
 *     return (
 *         <div className='NameField'>{this.l('NAME_FIELD')}</div>
 *     );
 * }
 * ```
 */
function getDocument() {
    return '';
}
```

For hover we now display:

![screen shot 2017-05-10 at 4 31 45 pm](https://cloud.githubusercontent.com/assets/12821956/25925600/601f07bc-359e-11e7-8ebb-33b73705505e.png)

and for completion items we display:

![screen shot 2017-05-10 at 4 39 33 pm](https://cloud.githubusercontent.com/assets/12821956/25925718/44569dd2-359f-11e7-9ca6-262a9a180152.png)

This info is currently not rendered as markdown due to #11877

**Comment by Almenon** [comment]
thanks @mjbvz !

**Comment by wesleymostien** [comment]
What about the @return info?

**Comment by mjbvz** [comment]
@wesleymostien Opened #36462 for that
