### ISSUE TITLE
Minimap enhancements

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode#24395]
- Add an option to display minimap to the left
- Add an option to enable moving the cursor to the position by clicking inside the minimap
- Add an option for smooth scrolling in minimap or make it the default behavior

**Comment by fbnlsr** [comment]
I'd like to piggyback on that feature-request with this:

- Always draw the minimap's screen view position
- Add a keybind command to toggle it on/off

**Comment by loplopop** [comment]
Speaking of drawing the position itself, I find the current way of highlighting the position quite inelegant. I think marking the position with a rectangular border with small round corners but without any highlighting inside would be a cleaner approach and then leaving it always on wouldn't be distracting. My guess is that constant display of a blob of highlight on screen isn't very clean.
Another option is to move the highlight UNDER the position in terms of z order.
But I much prefer an empty slightly rounded rectangle marking the position, and always on.

**Comment by letmaik** [comment]
Can this be split up into separate issues please with specific titles? Makes searching easier

**Comment by tcr** [comment]
Was just looking into whether the minimap could be moved to the left today.

**Comment by Oxicode** [comment]
+1

**Comment by 544751779** [comment]
+1

**Comment by RMacfarlane** [comment]
Several of these have already been done:

> Add an option to display minimap to the left
Can be controlled with`editor.minimap.side` setting

> Always draw the minimap's screen view position
Can be controlled with `editor.minimap.showSlider`

> Add a keybind command to toggle it on/off
Not set by default, but you can add a custom keybinding for the `View: Toggle Minimap` command

For the two remaining suggestions, please open separate issues. This makes it much easier to track work, since each feature will likely be implemented independently of others, and allows people to find them through search more easily. Thank you!
