### ISSUE TITLE
New "Keyboard Shortcut" dialog should display current assignment

### ISSUE THREAD

**Issue by NCC1701M** [Microsoft/vscode#24396]
- VSCode Version: 1.11.1
- OS Version: Windows 7 [6.1.7601]

#### Steps to Reproduce:

1. Go to File -> Preferences ->Keyboard Shortcuts
2. Select a keybinding
3. Klick on + to add a new keybinding
4. Press desired key combination

#### Current behaviour
The dialog only shows the pressed key combination again.
![image](https://cloud.githubusercontent.com/assets/7260053/24847090/0b3b01f2-1dbf-11e7-9aed-40868bf73193.png)

#### Expected behaviour
The dialog should display if the combination is already bind to a command and if so to which command.

For example:
![image](https://cloud.githubusercontent.com/assets/7260053/24847211/deed03ec-1dbf-11e7-8fcd-2ed6f38560b7.png)

or

![image](https://cloud.githubusercontent.com/assets/7260053/24847234/02aa553c-1dc0-11e7-8b6e-e232adab7b23.png)

**Comment by sandy081** [comment]
Nice idea

**Comment by brandonrninefive** [comment]
I would like to work on this!

**Comment by sandy081** [comment]
@brandonrninefive That's great. Let me know if you need any help.

**Comment by brandonrninefive** [comment]
Hey @sandy081 , I'd like to ask for some direction for adding this feature.

Currently, I've been looking at the following method to start: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/preferences/browser/keybindingWidgets.ts#L200

As well as this method:
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/preferences/browser/keybindingWidgets.ts#L227

Two main questions I have:

1. Which would be the better method to use to place these changes? For example, should this be a label that displays in place of the printed key binding using the same DOM node in the event that the binding is already taken, or should it have its own DOM node underneath? If a new DOM node needs to be created, please fill me in on how to account for translation properly (which I'm guessing is handled by nls.localize()).

2. Can you point me to which variable I should be using to access the list of existing keybindings from the appropriate function in order to run my check?

Thank you!

**Comment by sandy081** [comment]
@brandonrninefive I would show the label `<number> conflicts` as follows. 

<img width="573" alt="screen shot 2017-12-12 at 17 24 28" src="https://user-images.githubusercontent.com/10746682/33896002-0ec589ea-df62-11e7-8aa7-03f9b1cc6358.png">


This has to be a new DOM element and the label should come from outside. It means, [DefineKeybindingWidget](https://github.com/microsoft/vscode/blob/master/src/vs/workbench/parts/preferences/browser/keybindingWidgets.ts#L133) should have an API to set the label from outside and also an event when keys are entered. [KeybindingsEditor](https://github.com/microsoft/vscode/blob/master/src/vs/workbench/parts/preferences/browser/keybindingsEditor.ts#L74) listens to the event and updates the label by checking if the keybindings has conflicts or not.

When no conflicts, label can be empty

**Comment by brandonrninefive** [comment]
Thank you for your help @sandy081 , I got it working and submitted the changes in PR #40405. Assuming that everything goes well with that PR, I have another suggestion for this feature. Could we perhaps make the conflict label a link, which will close the dialogue and search for the entered key combination in the keybindings list? This way, users can see what the particular conflicts are, rather than just how many there are. Please let me know your thoughts :).

**Comment by isidorn** [comment]
Adding verified label since this nicely works, however currently it says 
`2 Existing` with an underline indicating a link

I find this message weird and not clear. Why the short message it is not like there is not enough horizontal space?
I suggest to say "2 existing commands have this keybinding"

**Comment by sandy081** [comment]
![image](https://user-images.githubusercontent.com/10746682/40712444-0c233db0-63fe-11e8-94b3-d62d68785cb0.png)

![image](https://user-images.githubusercontent.com/10746682/40712480-22d3dab0-63fe-11e8-8183-3b3c2c19676f.png)

**Comment by isidorn** [comment]
Cool
