### ISSUE TITLE
Exception peek UI doesn't seem to function for me on version 1.18

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#24411]
_From @StephenBloomquist on April 6, 2017 19:58_

This is with VSCode version 1.11.1

In trying to move my debugger to version 1.18 of the protocol and adapter, but the exception UI (the red bar that spans the screen with exception details) no longer displays. My usage of stopped event hadn't changed between versions, and everything else about the exception behaves as expected.

I get these errors when I try resizing the debug side bar, which seem like they're relevant due to the exception widget calls in the stack trace:

![image](https://cloud.githubusercontent.com/assets/24838721/24772953/12c23dea-1ac8-11e7-8112-c53202611939.png)

_Copied from original issue: Microsoft/vscode-debugadapter-node#110_

**Comment by michelkaporin** [comment]
@StephenBloomquist thank you for reporting this. Can you please let me know if exception UI was/is working in VS Code version 1.10 stable? 

If not, then my first guess would be that your DA is sending StoppedEvent with `reason = 'Exception'`, rather than lower case `'exception'` as defined in the protocol https://github.com/Microsoft/vscode/blob/d66a5c2f3111d0f835338472e6b2757388cfaf7d/src/vs/workbench/parts/debug/common/debugProtocol.d.ts#L74. 
I did not go in depth in your code, but this looks to me the place where you define StoppedEvent reason: 
https://github.com/StephenBloomquist/vscode-duktape-debug/blob/master/src/DukDebugger.ts#L534.

**Comment by StephenBloomquist** [comment]
@michelkaporin Yeah it was working just fine in VS Code 1.10.

I don't have the debugger I'm referring to on github unfortunately, it's one I've built from the ground up. I'll post some code snippets on how the stopped event is formed and sent.

Here's how the exception and stop reason are set up:
```Typescript
if (this.throwData) {
    this.debugLog("(Client) Pausing is an exception, attempting to format...");
    if (srcData && (srcData.duktapePath == this.throwData.fileName)) {
        this.exceptionMessage =
              `[Duktape] ${this.throwData.message}\n`
            + `    ├─Throw status: ${duk_const.ThrowFatal[this.throwData.fatal]}\n`
            + `    ├─File: ${srcData.vsCodePath}\n`
            + `    └─Line: ${srcData.javascriptToTypescript(this.throwData.lineNumber).line}`;
    }
    else {
        this.exceptionMessage = `${this.throwData.toString()}`;
    }

    this.error(`Exception occured\n${this.exceptionMessage}\n`);
    this.stopReason = "exception";
}
```

Here's the actual sendEvent:
```Typescript
this.sendEvent(new vsAdapt.StoppedEvent(this.stopReason, DebugClient.THREAD_ID, this.exceptionMessage));
```

None of this has changed between 1.10 and 1.11.1

**Comment by StephenBloomquist** [comment]
I just went back and double-checked. The exception widget works just fine /w version 1.17 of the debug adapter for VSCode 1.11.1

If I knew of a way to roll back VSCode to an earlier version I could check 1.18 against an older version of VSCode.

**Comment by michelkaporin** [comment]
@StephenBloomquist Thanks for the provided info. The problem you are facing is a problem on VS Code side, at least in the way we handle it programmatically.

I've looked again at the stack trace calls from your image and it seems that `line` and `column` of the `StackFrame`, where exception has been thrown, are not of a `number` type. That is why there is `Error: Invalid arguments` error first and then multiple uncaught exceptions upon window resizing. 

Could you verify if you send correct `column` and `line` number for the first call stack frame in DA to us? Most likely these attributes are not of type `number` (e.g. `null`) in your case. Although if they are fine, is it possible to get your DA as .vsix file, together with a sample code to test it against (I cannot reproduce this issue in any other way)?

**Comment by StephenBloomquist** [comment]
@michelkaporin Looks like you hit the nail on the head, the mention of the column number immediately drew my attention to another part of my code. 

I switched over from using the Adapter StackFrame to the Protocol StackFrame when I changed the code to take advantage of the `presentationHint` feature. I made the mistaken assumption that, being an optional variable in the Adapter StackFrame, column should be undefined. Changing the column variable to 0 fixed the problem.

**Comment by michelkaporin** [comment]
@StephenBloomquist Great! I am glad you raised this bug, I will correct error handling around exception widget for this case.

**Comment by StephenBloomquist** [comment]
@michelkaporin 
Hey, just wanted to let you know that the change you made means that "column" can't be 0. Checking against `if (exceptionSf.column)` will fail for null, undefined, and 0 (and I think negative numbers as well but that's less relevant).

I noticed this when the update broke my exception widget again. Had to change setting my column from 0 to 1 to make it work again.

**Comment by michelkaporin** [comment]
@StephenBloomquist can you explain in which scenario you set line or column number to 0? This will make the widget to popup in the top left corner of the editor, not clarifying at all where the exception has happened (which I consider as a buggy behaviour).

**Comment by StephenBloomquist** [comment]
@michaelchiche 
It just seems the appropriate thing to do when an optional variable needs to be defined but isn't otherwise used. Originally I was simply not defining the column at all as my debugger only cares about lines, but then this issue arose and I defined it as 0. Now it's defined as 1.

Personally I feel that if the user isn't defining specific column numbers then the assumption should be made that everything which might care about columns, such as the exception widget, is to operate on the left-most column. Or line/column shouldn't be optional variables as that's what caused things to break initially. Or some documentation on what needs to be defined, and what it needs to be defined as, in order for a particular system to work as it wasn't until I looked at your change that I was able to figure out why the exception widget broke for me again.

Also the exception widget appears to be pointing 1 column in when I'd expect it to point at the left-most column:
![image](https://cloud.githubusercontent.com/assets/24838721/25858913/d58f4baa-3491-11e7-9896-ac9ce91217ec.png)

**Comment by michelkaporin** [comment]
@StephenBloomquist I was defining the behaviour with respect to the debug protocol that says the following for the StackFrame sent:
```
/** The line within the file of the frame. If source is null or doesn't exist, line is 0 and must be ignored. */
line: number;
/** The column within the line. If source is null or doesn't exist, column is 0 and must be ignored. */
column: number;
```
Hence, if there is a source set I would always expect the line and column number > 0. I can do the change to appear the exception widget at column number 1, when column is 0 but this means that we have to have the same behaviour for the line number as well (as these properties behaviour should be similar to my understanding). This would be totally wrong, making the exception UI to appear in the wrong place, not where the exception has happened. Therefore, it seems to me wrong that you try to send 0 as a column number (this column number naturally cannot exist in the code).

Regards to the arrow positioning, this behaviour is across all our peek widgets (peek definition/find all references). You can raise a separate issue if you think this is wrong.

@weinand @isidorn what are your opinions on this?

**Comment by StephenBloomquist** [comment]
@michelkaporin 
Yeah it makes sense why you chose to do what you did. I wouldn't necessarily say that it would be wrong to assume a default behavior for both lines and columns with the exception widget, though. IMO if a debugger leaves line numbers undefined, defaulting the UI to line 1 would be expected behavior as the situation is either a scenario where lines are irrelevant for the debugger, or the debugger has a bug. What you're thinking of as incorrect behavior is assuming that the exception UI should appear on a specific line with a debugger that doesn't care about specific lines.

For example, my debugger doesn't care about columns because I can't get column details from the target. You can still argue that the UI isn't pointing at where the exception happened, because it may have happened within an arrow function on the same line, but I can't do anything about it, the exception UI can only point at the correct line, but not the correct column. This is expected behavior with my debugger.

As for the arrow positioning, I didn't realize it was the intended left-most position. In that regard, I retract my comment about it appearing to start 1 column in.
