### ISSUE TITLE
Run multiple extension hosts to track down crashing extension

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#24441]
Given a command line argument, we could run one extension host per extension and with that track down which extension lets the extension host crash.

If the performance hit of this is too high, we could also run just two extension hosts and bisect the set of extensions.

**Comment by joaomoreno** [comment]
This might break extensions due to the `getExtension` API:

https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L4779

**Comment by joaomoreno** [comment]
fyi @jrieken

**Comment by jrieken** [comment]
Idea isn't new, idea is generally liked but very hard to implement given the API and our RPC implementation etc. Instead of using multiple extensions host to diagnose these kind of situation I am planning to use the, hopefully coming soon to Electron, support to profile/debug the extension host process from the outside, not from inside the JS event loop. That would allow us to make user turn on diagnose mode when things go south

**Comment by jrieken** [comment]
see #11638 for more
