### ISSUE TITLE
SCM: Collapsible SourceControlResourceGroup

### ISSUE THREAD

**Issue by stef-levesque** [Microsoft/vscode#24460]
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T14:00:34.044Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|[perforce](https://github.com/stef-levesque/vscode-perforce)|slevesque|2.0.1|;

---

I would really be great to have collapsible SourceControlResourceGroup. I usually have a lot of pending changelists in my Perforce projects :sweat_smile: 

![image](https://cloud.githubusercontent.com/assets/7251102/24877668/1413048e-1dfe-11e7-89cc-e5bf51fad159.png)

cc @joaomoreno

**Comment by ihalip** [comment]
I'm working on this issue, will submit a PR once I have a decent implementation.

**Comment by joaomoreno** [comment]
@ihalip We're not ready for this. The SCM viewlet uses a list widget, which doesn't have tree support. So you're going to have to implement a custom expansion behaviour, which isn't desirable. I'd hold off on this. We have a bunch of `help wanted` issues that you can start off with.

**Comment by ihalip** [comment]
I'm keen on having such a feature because I also use the perforce extension and have opened/shelved files spread across a lot of changelists.

I did work on this item over the weekend, and completely replaced the list with a tree widget - so far it's working great, and the behavior is exactly the same as it was before; except of course now resource groups can be collapsed/expanded.

Do you see any reason why a PR for this issue wouldn't be accepted?

**Comment by joaomoreno** [comment]
Yeah, we're moving away from that tree widget and reimplementing a tree on top of the cleaner and faster list widget.

**Comment by gulshan** [comment]
Is there any update on this? I want to collapse the `STAGED CHANGES` when the list is too long and viewing non-staged changes requires scrolling.

**Comment by joaomoreno** [comment]
No updates unfortunately, merging this with #14582
