### ISSUE TITLE
Warning messages could hint towards disabled/missing extension

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#24487]
Testing #24403

https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#debugging-in-the-editor

![image](https://cloud.githubusercontent.com/assets/5047891/24897719/47d054ce-1e9a-11e7-9a88-233d63928e81.png)

I initially thought the guide is obsolete.

I have the Chrome debugger extension, but it is disabled (same as not having it installed). So perhaps we could improve the warning messages when a `"type"` is missing to hint that an extension is missing.

**Comment by isidorn** [comment]
![screen shot 2017-04-27 at 16 21 44](https://cloud.githubusercontent.com/assets/1926584/25487818/9ffdfb6a-2b65-11e7-9f3d-23eb34d8bd33.png)

**Comment by weinand** [comment]
@isidorn The hover shows up nicely.
However, when reading the initial problem I saw that the problem was not a missing extension but a disabled extension. So an even more helpful message would be:
"The debug type is not recoginzed. Make sure that you have a corresponding debug extension installed and that it is enabled."

**Comment by isidorn** [comment]
@weinand thank you. I have improved the message

**Comment by ForgottenUmbrella** [comment]
I'd like to point out that the improved error message has a typo: "recoginzed" should be "recognized" (or "recognised", depending on locale).

**Comment by isidorn** [comment]
Thanks! Fixed via 61205ceca3
