### ISSUE TITLE
Text become fuzzy and unusable after scroll

### ISSUE THREAD

**Issue by ArianeLu** [Microsoft/vscode#24483]
- VSCode Version: 1.12.0 Insider
- OS Version: Windows 10 Version 1703

## Steps to Reproduce:

1. Install it on a Hi-DPI screen device with 125% scale (May not require, it's my environment)
2. Paste some long code into editor
3. Take a screenshot without image compress
4. Scroll down mouse wheel by once, take another screenshot, or feel it with your eye

## Screenshot
![normal](https://cloud.githubusercontent.com/assets/4962408/24896107/fc9697b2-1ec5-11e7-9dda-387ab1b50745.png)
> This is normal (clearly)

![fuzzy](https://cloud.githubusercontent.com/assets/4962408/24896116/08febf48-1ec6-11e7-87e0-13387a384386.png)
> This is **fuzzy**

## Screenshot with zoom
----
![detail_clear](https://cloud.githubusercontent.com/assets/4962408/24896124/12782000-1ec6-11e7-9483-381673777ddf.png)
> This is normal

![detail_fuzzy](https://cloud.githubusercontent.com/assets/4962408/24896140/26bf061e-1ec6-11e7-9675-0c4d1d0c2095.png)
> This is **fuzzy**

## Possible reason
I think it's an **upstream issue** with Chromium, if Code use **CSS transform** to scroll/move element will cause this issue.
I hope develop team can take a look with this, this make Code **unusable at all**

## See also
- Symbol & Text may fuzz and unclear (#7799) [upstream, electron]

**Comment by bpasero** [comment]
@alexandrudima lets sync on this when we are both in the office, looks like a Chrome regression.

**Comment by alexandrudima** [comment]
@ArianeLu I am on a Surface Book with 200% scale and regardless of the scroll top position the editor font is rendered with subpixel antialising:

![image](https://cloud.githubusercontent.com/assets/5047891/24899720/9846a6b8-1ea1-11e7-9bf7-59b6bbb03608.png)

Sometimes, when changing the scale, I need to sign out and sign back in to Windows for all the apps to react to the change. Does signing out help in any way?

**Comment by alexandrudima** [comment]
Could you perhaps share your settings? (i.e. @bpasero @aeschli is it now possible users can define transparent backgrounds via themeing?)

**Comment by ArianeLu** [comment]
@alexandrudima 
Noting to share, It's fresh install, without custom settings.
If i changed screen scale, it should more fuzzy in all time, not just after scroll

My user settings:
```
{
    "workbench.iconTheme": "vscode-icons",
    "terminal.integrated.shell.windows": "C:\\WINDOWS\\Sysnative\\bash.exe"
}
```

https://github.com/Microsoft/vscode/issues/22336#issuecomment-293188857
This commend author may have same issue

**Comment by bpasero** [comment]
I also did a quick test on my macBook pro both with my external monitor and the notebook screen and I am seeing subpixel antialising with any DPI scaling (100%, 125%, 150%). Would also like to understand what kind of setting could cause this.

Btw please only look at the editor and not anywhere else! We did loose subpixel antialising outside the editor but that is Electron unrelated (I can see this with 1.11 stable already).

**Comment by bpasero** [comment]
@ArianeLu when you say in your screenshot "this is fuzzy", it seems to me from that screenshot that subpixel antialising is still being used, can you clarify that is different from the screenshots and what produces the fuzzyness?

**Comment by ArianeLu** [comment]
@bpasero Look the char "L" on two screenshot, as you say, it looks like subpixel antialising, but it was difficult to read on my external monitor (DELL P2416D).

The fuzzy looks like have a shadow around the char, I don't think subpixel antialising will cause text fuzzy like this one. Something maybe wrong...

I can't reproduce this issue on VSCode 1.10.2.

## Relative Code:
Element with class `.monaco-editor-background` have inline attribute `transform: translate3d(0px, -455px, 0px)`


- translate3d(0px, 0px, 0px) - Good
- translate3d(0px, -1px, 0px) - A bit fuzzy
- translate3d(0px, -2px, 0px) - Unreadable
- translate3d(0px, -3px, 0px) - Better than -2px, but still unreadable
- translate3d(0px, -2px, 0px) - Good, text very clear


** I can't find this attribute on `.monaco-editor-background` with Code 1.10.2

**Comment by ArianeLu** [comment]
![compare](https://cloud.githubusercontent.com/assets/4962408/24901878/fdbada80-1eda-11e7-9d50-b88fba261c6a.png)

And this one

**Comment by ArianeLu** [comment]
@bpasero Can you understand my description? Or any idea with my guess about the `transform` attribute?

**Comment by alexandrudima** [comment]
@ArianeLu 

I think the root problem here is that Chromium decides to go to grayscale antialising on your machine/environment. Grayscale antialising is problematic exactly because, as you point out, it cannot correlate the font rendering with real screen pixels.

If you believe it is due to our usage of translate3d, then there is an easy way to test that: use the setting `"editor.disableTranslate3d": true` in your settings. You should then observe all the editor dom nodes being positioned with `top` or `left` and no longer with `transform`.

**Comment by bpasero** [comment]
@alexandrudima here is an update from what I see after doing more testing with the `editor.disableTranslate3d` setting. I can confirm that there is a regression in subpixel-aa when starting to scroll. 

**Translate3d: ON, Scrolling: NO**
![screen shot 2017-04-12 at 08 11 04](https://cloud.githubusercontent.com/assets/900690/24943584/992e6d0c-1f57-11e7-8ffc-65ce1ae964f1.png)

**Translate3d: ON, Scrolling: YES**
![translate3d_scroll](https://cloud.githubusercontent.com/assets/900690/24943490/3cdc15e0-1f57-11e7-879a-d43d86d62487.png)

I lost subpixel-aa when scrolling.

Things look a lot better with `translate3d` disabled:

**Translate3d: OFF, Scrolling: NO**
![notranslate3d_noscroll](https://cloud.githubusercontent.com/assets/900690/24943529/5899fe50-1f57-11e7-99a4-75a32f734967.png)

**Translate3d: OFF, Scrolling: YES**
![notranslate3d_scroll](https://cloud.githubusercontent.com/assets/900690/24943532/5df2b270-1f57-11e7-8bd3-193203ef053e.png)

I should add that I am only getting subpixel-aa in the editor with translate3d turned off ever since I fixed https://github.com/Microsoft/vscode/issues/24532. For some reason, the entire workbench was using grayscale-aa when the workbench container (`.monaco-workbench`) was not having a `background-color` associated. Puzzles me why that has an impact though...

Remains to understand why Chrome turns the editor into grayscale-aa once scrolling starts. Since its fixed after disabling `translate3d`, it is probably that. Checking for chrome issues that might be related I stumbled upon https://bugs.chromium.org/p/chromium/issues/detail?id=521364

**Comment by alexandrudima** [comment]
@bpasero I don't think this is happening on all environments. e.g. it is not happening for me. What is the setup that triggers it? 125% scaling in the OS (mine is configured with 200% scaling)?

**Comment by bpasero** [comment]
@alexandrudima I am running with 125% DPI but I also see this with 100% as well as 200%.

**Comment by alexandrudima** [comment]
@bpasero Do you sign out of Windows and sign back in between changes to the scaling setting? There are numerous apps (I wouldn't be surprised if Chromium is one of them) that cannot react to changes to scaling unless you sign out of Windows. (I'm trying to find out what is the root cause of this)

**Comment by bpasero** [comment]
@alexandrudima wow, you are right, subpixel-aa works in 200% after doing a windows restart. So maybe this is only an issue when the multiplier is an odd percentage?

**Comment by egamma** [comment]
According this tweet https://twitter.com/paulcbetts/status/852050882523000832 this only affects non-integral DPIs

**Comment by ArianeLu** [comment]
Really said, for my device, 100% is too small and 150% is too large.
Hack it then work with 126%? LOL, That's impossible

**Comment by alexandrudima** [comment]
@ArianeLu We will look into a solution. My favorite resolution would be to disable our usage of translate3d only in the cases where this issue is hit (i.e. not for folks running at 100% or 200%) due to the scrolling performance implications.

**Comment by alexandrudima** [comment]
I could reproduce. Here are the values I get (with window.zoomLevel: 0) for:

| Scaling factor | Zoom Level | Zoom Factor | Pixel Ratio |
|---|---|---|---|
| 100% | 0 | 1 | 1 |
| 125% | 0 | 1 | 1.25 |
| 150% | 0 | 1 | 1.5 |

I'm looking into disabling the usage of translate3d in the editor when the pixel ratio is not an integer.

**Comment by bpasero** [comment]
@alexandrudima awesome, thanks!

**Comment by ArianeLu** [comment]
@bpasero @alexandrudima Text become darken and tiny after open built-in terminal, I can't find out why

**Comment by ArianeLu** [comment]
![gif](https://cloud.githubusercontent.com/assets/4962408/26034898/a080a03a-38f6-11e7-8e23-be00c9fdc01f.gif)
Look like this one

**Comment by ArianeLu** [comment]
#26800
