### ISSUE TITLE
Wrong unfold cuts emmet

### ISSUE THREAD

**Issue by webamazingstudio** [Microsoft/vscode#24497]
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T13:58:12.954Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|vscode-theme-onedark|akamud|1.3.2|
|indent4to2|Compulim|0.1.2|
|auto-rename-tag|formulahendry|0.0.11|
|beautify|HookyQR|1.0.2|
|minify|HookyQR|0.3.0|
|bem-expand|lukazakrajsek|0.1.2|
|code-beautifier|michelemelluso|1.6.2|
|HTMLHint|mkaufman|0.3.3|
|vscode-csscomb|mrmlnc|4.0.1|
|js-patterns-snippets|nikhilkumar80|0.0.5|
|vscode-icons|robertohuertasm|7.5.1|
|code-settings-sync|Shan|2.6.2|
|guides|spywhere|0.7.0|
|html-css-class-completion|Zignd|1.0.3|;

---
For example: pos-r(position:relative) => -ms-progress-appearance: and etc, exactly the same situation with text-align and position: absolute, thats all cuts which i find on that moment.

**Comment by ramya-rao-a** [comment]
You mean that you get the item from the suggestion list instead of emmet expansion?

**Comment by webamazingstudio** [comment]
Yes. This happened after last update.

**Comment by ramya-rao-a** [comment]
This has always been the case and is being tracked in #1952, nothing changed here in the last update AFIK

There are a few things you can try

- Stop TAB from accepting the suggestions. See https://github.com/Microsoft/vscode/issues/1952#issuecomment-257811974
OR
- Set `editor.quickSuggestions` to false so that the suggestions appear only when you specifically ask for them via `Ctrl+Space` or `Cmd+Space`
