### ISSUE TITLE
Sorting of Vue extensions is not optimal

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#24511]
**Refs:** Vue.js test tour (https://github.com/Microsoft/vscode/issues/23385)

There are some issues with vue.js extensions sorting:
* there are 2 extensions for vue called vue that seem to be a fork of the other, but its not clear which to pick
* Pines vetur extension which seems very popular is not to the top

**Comment by joaomoreno** [comment]
cc @hamenon

**Comment by hamenon** [comment]
In search we give the name of the extension the top most priority our telemetry shows that that's generally what users search based one. This is followed by the publisher name. In this case since vue matches the display name of the extension exactly and hence it shows up at the top. Pines vetur extension mentions vue only in the short description and in the tag, not the two most immediately noticeable entities on the extension page. 
We do plan to introduce download count as a possible tie breaker for cases where two extensions have the same priority score. But that wouldn't help bring Pines extension to the top since that would have a lower score owing to the other extensions matching the name perfectly.

**Comment by octref** [comment]
I remember there is a list of "recommended extensions" for each language. Wondering if it's possible to always show them first when the search term is for each language/framework, such as go/golang, python, vue, etc.

**Comment by joaomoreno** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.

Thanks for your understanding. Happy coding!
