### ISSUE TITLE
Cannot click process picker in compound mode

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#24545]
Re https://github.com/Microsoft/vscode/issues/22279

When we try to debug both the client and server code of mean stack, we set up a compound launch task.

For server side code, we use `"processId": "${command.PickProcess}",` to help find the process. Once we hit F5, we see the Process Picker and before we choose the process, the debugger instance for client code launches and Process Picker dismisses.

**Comment by isidorn** [comment]
This is just the flaw of the current quick pick design, it needs to be more stable in order to support this scenario. What happens is that quick pick gets opened, and the second debug starts forcing the editor to focus (since a breakpoint is hit). Editor being focused closes the quick pick

@bpasero do we already have some feature request to make the quick pick be closed only on esc, and not on focus lost?

I could introduce a hack on the debug end to not focus the editor if the quick pick is shown but that feels a bit ugly. Also api to get if the quick pick is open is missing, I would have to listen on show / hide events.

**Comment by bpasero** [comment]
@isidorn there is a setting `"workbench.quickOpen.closeOnFocusLost"` as well as an option `ignoreFocusLost` when you open the picker to set this.

**Comment by isidorn** [comment]
Since the extension is opening the quickPick assigning this issue to @weinand 
`ignoreFocusOut` is the name of the option in the vscode api
