### ISSUE TITLE
Error with 'outFiles'

### ISSUE THREAD

**Issue by Talzar13** [Microsoft/vscode#24576]
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T13:58:12.954Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.6.0|
|theme-chrome-devtools-dark|ivanzusko|0.0.1|
|MagicPython|magicstack|1.0.9|
|mssql|ms-mssql|0.3.0|
|csharp|ms-vscode|1.8.1|
|python|tht13|0.2.3|;

---

Steps to Reproduce:

1. Wrote simple Python program: print("HI there!")

2. Used both F5 and Ctrl+F5 to debug and run w/o debugging. 

3. Get an error bar at the top that says, "Cannot launch program 'user path...\Python\py Test 01.py'; setting the 'outFiles' attribute might help. 

4. Debug Console has the message "Debugging with legacy protocol because Node v0.12.2 was detected."

5. Upgraded Node version to v6.10.2, but did not resolve the problem. 

I had some trouble setting this up on my Surface, but finally got that working by fixing the paths. I tried to do the same here, but this is a new error that I'm not familiar with. I haven't been able to find much help online. Any help or suggestions would be greatly appreciated.

**Comment by weinand** [comment]
VS Code seems to pick the wrong debugger: the errors you are seeing come from Node.js which doesn't make sense in your case because you want to debug python.
I tried to reproduce the problem but I only installed the python extension (by donjayamanne). I created a hello.py file with `print("HI there!")` and while this was open in the editor I pressed F5. This started python debugging for me.

Do you have a .vscode folder in your workspace with a file "launch.json"? Make sure that this contains launch configurations for Python. e.g. the "type" attribute should be "python" not "node". 
Otherwise delete "launch.json", open hello.py and press F5 again.
