### ISSUE TITLE
file explorer rename reverts change if mouse clicked outside of text box

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#2458]
- in VS Code file explorer select 'rename' action on a file or folder
- change the name in the textbox
- with the mouse click outside of the textbox

Observe: the name reverts to the original name.

Problem: this behaviour is very different than the native behaviour.  In the Finder (or Windows Explorer) a click outside of the textbox commits the change.

For a user who is used to click outside of the textbox in order to commit the change, this is really annoying because he will always lose the name change on first try (and has to learn that an explicit "return" is necessary).

I'm suffering from this since the beginning of time of VSCode but only today I found the time to analyse what is going on.

**Comment by bpasero** [comment]
I can reproduce when I click into the explorer, but not when clicking anywhere else. It seems the tree is disposing the input box when this happens and only after the dispose, the input box looses focus and wants to commit its changes, but it does not because it was already disposed.

The check is: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/browser/views/explorerViewer.ts#L322

@joaomoreno looks like your code in this area.

**Comment by weinand** [comment]
@bpasero yes, only clicking in the area of the tree triggers the problem.

**Comment by bpasero** [comment]
Thanks :+1:

**Comment by weinand** [comment]
@joaomoreno Awesome, finally my greatest usability issue with VS Code is gone ;-)

**Comment by joaomoreno** [comment]
:+1:
