### ISSUE TITLE
Wrong or unnecessary translation of "Closure"

### ISSUE THREAD

**Issue by ckosmowski** [Microsoft/vscode#24580]
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T13:58:12.954Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|jshint|dbaeumer|0.10.15|
|githistory|donjayamanne|0.2.0|
|Theme-Dreamweaver|gerane|0.0.2|
|Theme-PastelsonDark|gerane|0.0.2|
|Theme-TwoStones|gerane|0.0.2|
|hopscotch|idleberg|0.1.4|
|crayon-vscode|jansenfuller|0.1.3|
|jscs-formatter|moose87|0.1.1|
|jscs|ms-vscode|0.1.9|;

---

Steps to Reproduce:

1. Debug a node.js application with the integrated node.js debugger
2. Hit a breakpoint
=> In the left panel there are several sections displayed i.e. for breakpoints and variables including the section for local, global and closure scople. The german translation "Abschluss" of the word "Closure" doesn't fit here it is actully more confusing. than it helps. In fact i would recommend to not translate this word to german because it's commonly used as it is "Closure".

I tried hard to find the translation inside the project to file a pull request but i couldn't find it.

**Comment by isidorn** [comment]
Thank you for the feedback.
We just started having a process for users contributing to our translations. All the details about this can be found here https://github.com/Microsoft/Localization/wiki/Visual-Studio-Code-Community-Localization-Project
Can you please follow those steps and contribute to our translations?

**Comment by isidorn** [comment]
Just read our process for the translation issues -> reopening, adding tags and assigning appropriate people.
@ckosmowski you can still contribute using transifex but in case you do not feel like it we have an alternative solution

**Comment by isidorn** [comment]
ping @danyeh @khoiph1

**Comment by jrieken** [comment]
@isidorn I don't want these issue appear in the inbox again

**Comment by ckosmowski** [comment]
Okay i'll have a look at the translation process.

**Comment by dbaeumer** [comment]
We are discussing and fine tuning the process with the translation team. Here are some things to keep in mind:

Transifex has very limited issue tracking capabilities (to my knowledge). You can basically only add comments to translated strings. It is a translation platform not a good issue tracking system.

Since VS Code's issue tracking system is GitHub I think the best we can do for now is to have these issues in GitHub (we did for the internal translation as well). I think it will raise the bar as well to file translation issue since it requires the creation of a user id to comment on strings. And you are treated as a translator afterwards :-(

The idea how to handle this is as follows:

- we have a translation representative from the translation team which we will assign these issue to (the inbox tracker does so)
- the issues will be label as i18n and marked as help wanted so that they don't show up as bugs.
- we need to educate translators in Transifex to look at these isssues.

**Comment by dbaeumer** [comment]
@egamma FYI.

**Comment by ckosmowski** [comment]
I now created an transifex account and joined the correct team.  Still i can't really find the wrong translation.  There is a resource called "vscode-node-debug" which sounds like what i am looking for but there are no german translations at all.

Is the german translation of missing keys generated automatically so that i can't find the wrong value in the resources ?

**Comment by michelkaporin** [comment]
@ckosmowski I apologize, we've created `vscode-node-debug` resource only today for the Node debug adapter (this is an extension, not the tool). Therefore, you don't see translations for it yet, because they have not been recycled from the old translation memory we have. However, you can still create a translation suggestion for this string, even without an existing translation being present.

We will update `vscode-node-debug` resource with latest translations as soon as possible. VS Code as a standalone tool has all existing translations already there, if you wish to contribute.

**Comment by jrieken** [comment]
Thanks @dbaeumer

**Comment by danyeh** [comment]
I reverted German translation to 'closure'.
https://www.transifex.com/microsoft-oss/vscode-extensions/translate/#de/$/111444286?q=closure
Thanks @ckosmowski for the feedback.
