### ISSUE TITLE
Disable `translate3D` for list when scaling

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#24599]
Related to #13662

Check d2a5c57366f29f0366ce479e8443506dc1bfb5e1

---

In order to get subpixel antialias with `translate3d`, the dom element also needs an opaque background color. Since this would introduce an odd option to the list, we're simply gonna disable that optimization for Windows, while leaving it for the other platforms.

**Comment by bpasero** [comment]
@joaomoreno it is worth mentioning that for some reason the list widget is always grayscale-antialiasing even when not scaled (basically ever since we have it).

**Comment by joaomoreno** [comment]
There is something I don't understand.

In d2a5c57366f29f0366ce479e8443506dc1bfb5e1, @alexandrudima disables `translate3d` for the current version only if `pixelRatio` isn't an integer. Seems to work fine for him.

On my machine with `pixelRatio = 1`, the list doesn't have sub-pixel antialiasing when using `translate3d`, but the editor does...

So... what more do you know, @alexandrudima ?

**Comment by alexandrudima** [comment]
@joaomoreno 

source: https://www.html5rocks.com/en/tutorials/internals/antialiasing-101/

- make sure to use an opaque background on the dom node that becomes a new GPU layer and no fancy transparency
- make sure to always position things at integer coordinates

**Comment by joaomoreno** [comment]
> make sure to use an opaque background on the dom node that becomes a new GPU layer and no fancy transparency

That did it, thanks @alexandrudima!

![image](https://cloud.githubusercontent.com/assets/22350/24967507/a73adefa-1faa-11e7-883f-943fc2b54e58.png)

@bpasero That poses a new problem. How can the list know which background it should use? Maybe we should add that as a new theming key...

**Comment by bpasero** [comment]
I confirm we have good subpixel-aa when `monaco-list-rows` (the container that uses `translate3d`) has a background color set. We can think about adding a background color to the [theming for tree/list](https://github.com/Microsoft/vscode/pull/24612) and thereby get the color in. It is a bit ugly though because in all cases we want this color to actually inherit the one from the layer below...

**Comment by bpasero** [comment]
[Pushed](https://github.com/Microsoft/vscode/commit/30f83907e187fc9d502ebff6a4eb3d6b51793376) a change to no longer use `transform3d` under the same conditions as the editor (e.g. when zoomed or scaled) but also generally on Windows because we do not define a background color for the layer of the list widget and this causes Windows to render the list without subpixel-antialias when scrolled.
