### ISSUE TITLE
[php] Don't activate auto-completion prompts inside known comment blocks

### ISSUE THREAD

**Issue by jumpinjackie** [Microsoft/vscode#2461]
Using VSCode 0.10.6 on Windows 7

I've been finding that auto-completion prompts kicks in when I'm writing text in comment blocks and I'm typing the start of some method/variable/symbol that is known by the auto-completion

Attached is example screenshot of some PHP code I'm editing

![vscode_php_unwanted_autocomplete](https://cloud.githubusercontent.com/assets/563860/12618114/a28917ea-c566-11e5-9aa8-e8c132cde348.png)

**Comment by jminer** [comment]
This issue is likely my number one annoyance with VS Code at the moment. When I get to the end of a comment line and press enter to go to the next line, half the time I end up picking an auto-complete entry instead. I notice this issue is tagged PHP, but please fix it for all languages, not just PHP (I don't even use VS Code for PHP).

**Comment by gandhis1** [comment]
Is there any update on this? I concur that it's quite an annoying issue.

**Comment by jrieken** [comment]
Yes, this has been fixed in March with #9504
