### ISSUE TITLE
suggest widget should not eat up End key

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#24673]
Rant alert: I find the binding of End in the suggest widget very annoying and useless. IMHO:
* Likelihood I want to go to the end of line when pressing End: 99.95%.
* Likelihood I pressed End by accident: 0.04%.
* Likelihood I like to go to the last suggestion in the list: 0.01% (presumably the most useless of suggestions if our sorting is good).

I had to remove it today from my `keybindings.json` and I'm not sure why it's the default now.

**Comment by alexandrudima** [comment]
Merged two days ago... #20156

**Comment by joaomoreno** [comment]
Obviously there are users that think otherwise. Personally, I don't really care. So, do we come up with a setting for it, and what's its default value?

**Comment by jrieken** [comment]
over and out, tho I'd say the personal preference is keybindings.json and I'd revert the change tbh

**Comment by epicgirl1998** [comment]
> So, do we come up with a setting for it, and what's its default value?

i think the old behavior being the default would probably be less surprising

as a fan of using the end key to go to the end of the line (and the home key for going the other way) this issue has my sincere +1

**Comment by mlewand** [comment]
> Likelihood I like to go to the last suggestion in the list: 0.01% (presumably the most useless of suggestions if our sorting is good).

That wasn't the case, often times useful snippet is placed at the end of list. For me, one of examples was with `it` snippet.

![image](https://cloud.githubusercontent.com/assets/5353898/25269093/80f849da-267b-11e7-9f81-22730251ea76.png)

Before you mention adjusting sort order, this is sth that I don't want to touch because default order is useful in other cases.

Also it conforms common accessibility standards, thus that's the behavior you expect.

Anyway, having an option to set it is good enough for keyboard users that expect a different behavior.
