### ISSUE TITLE
TypeScript server log contains PII and source code

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#24696]
* have a `tsserver.log` file and have the goal of filing an issue
* take a look at the file
* 🐛 file is full of file paths and even source code

We should *clearly* warn about this before encouraging people to attach that file to an (public) issue.

**Comment by mjbvz** [comment]
Yes this is a known concern with both the typescript log and the trace. 

Is your suggestion to have better in-product documentation to make this clearer, and/or that we better document this when asking people for the log/trace in github issues?

**Comment by mjbvz** [comment]
I added a note on this to the two settings with 1d05d0c. For example:

> Enables tracing of messages sent to the TS server. This trace can be used to diagnose TS Server issues. The trace may contain file paths, source code, and other potentially sensitive information from your project.

Let me know if anyone has any suggestions to improve the wording here

We should add a note on this in Github issues too whenever asking for the tsserver trace or log so that people know what they are sharing publicly. They could also send us these files over email instead of uploading them on issues

**Comment by jrieken** [comment]
I like. Thanks
