### ISSUE TITLE
Newly split windows don't respect word wrap settings

### ISSUE THREAD

**Issue by digilante01** [Microsoft/vscode#24712]
- VSCode Version: 1.11.2
- OS Version: Fedora 25

Steps to Reproduce:

1. Set editor.wordWrap to "wordWrapColumn"
2. split window vertically with Ctrl + \
3. Newly split window does not have wordWrap on

**Comment by alexandrudima** [comment]
![24712](https://cloud.githubusercontent.com/assets/5047891/25430214/122df0e0-2a7c-11e7-830f-33e4b32d4fda.gif)

**Comment by alexandrudima** [comment]
Last call to `editor.updateOptions`:

<img width="588" alt="screen shot 2017-05-31 at 20 52 41" src="https://cloud.githubusercontent.com/assets/5047891/26648550/23f0664a-4643-11e7-9b6b-f7e7c1d37767.png">

I will probably nuke this (old) code:

<img width="1000" alt="screen shot 2017-05-31 at 20 53 47" src="https://cloud.githubusercontent.com/assets/5047891/26648594/461628fe-4643-11e7-8a7c-8b4aa4dedd16.png">

**Comment by alexandrudima** [comment]
fyi @bpasero - I've deleted some code that I think is no longer needed and causes issues.

**Comment by bpasero** [comment]
@alexandrudima this code was making sure that an editor would receive the correct configuration of:
* render whitespace
* render control characters
* word wrap
When being moved from one editor group to another. Since editors are not the same when you move them to other groups, these settings need to be manually carried over.

Now, it seems that at least the render whitespace option and control characters moved to be a real setting instead of an editor option that you can set on one editor alone, so these are fine.

However, word wrap still seems to apply only on the active editor and not as a setting. The following is now broken:
* have an editor open and another editor behind (inactive tab)
* toggle word wrap from the menu
* move this editor to another group (by dragging the tab and moving it to the left or right of the other tab in the background
=> word wrap is not being carried over

**Comment by alexandrudima** [comment]
@bpasero I wrote a lot of code *to work around the workbench* to fix a number of word wrapping bugs where the settings were not carried over in various other cases by the deleted code :) -- see https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/codeEditor/electron-browser/toggleWordWrap.ts#L7

I have just tried with your steps and it works fine for me. Can you consistently reproduce?

**Comment by bpasero** [comment]
@alexandrudima you are right, with my steps I cannot reproduce, not sure what I did before.
