### ISSUE TITLE
Add workbench color theme keys for terminal background and foreground colors

### ISSUE THREAD

**Issue by code4hunter** [Microsoft/vscode#24735]

**Comment by Tyriar** [comment]
Themes have the ability to set the panel background color now (public API to be finalized soon), I think we should add a key to allow the terminal background to be overridden though (so PowerShell ISE users for example can set it to blue).

**Comment by bpasero** [comment]
Fyi I removed `panel.background` in this milestone because we do not support specific overrides for the editor (output, repl) and tree/list (problems).

**Comment by Tyriar** [comment]
@bpasero not sure I understand, my theme (and the theme generator) relied on panel.background to differentiate it from the editor.

**Comment by bpasero** [comment]
@Tyriar this is the reason:

Does not work for Problems Tree:
![image](https://cloud.githubusercontent.com/assets/900690/26596261/665e1868-456e-11e7-9285-24b00b8c09f9.png)

Does not work in Output:
![image](https://cloud.githubusercontent.com/assets/900690/26596395/dd507948-456e-11e7-9d52-42f3ce07e995.png)

Does not work in Debug Console:
![image](https://cloud.githubusercontent.com/assets/900690/26596414/e91e3b0c-456e-11e7-951f-5900df26db1a.png)

**Comment by Tyriar** [comment]
@bpasero don't we still want `panel.background` though? Removing it only to add it back later seems like the wrong idea. I figured we would have the output/debug console monaco editors use `panel.background` too?

Not sure if the thing with problems is a particularly big issue - don't use bright red as the background?

Note that `terminal.background` only applies to the viewport of the terminal and I don't want it to impact the actual panel's background, so `panel.background` makes sense for the terminal as well.

**Comment by bpasero** [comment]
@Tyriar unfortunately it is not so easy to support `panel.background` given the editor is embedded in there. The editor itself defines a lot of background and foreground colors that we all need to duplicate so that the panel can be styled properly. The same issue applies for the tree, but there we have a lot less colors to support. 

I think what is missing in general is a way for a theme author to override specific color keys hierarchically. For example: 

```
panel > editor.background: #...
sideBar > list.activeSelectionBackground: #...
```

**Comment by Tyriar** [comment]
@bpasero maybe you're shooting for too much control? We could have a constraint that there is only a single set of editor colors, however the background can change (editor, peek editor, debug console). No one's going to want to define different sets of colors for each editor.

If we're getting into `panel > editor.background` territory, why not just give users a css file and we validate/strip out parts we don't want to allow?

**Comment by bpasero** [comment]
@Tyriar I am not sure I understand, if someone is able to set `panel.background` why would that someone not want the editor to use that background and all the widgets inside the editor look properly?

**Comment by Tyriar** [comment]
@bpasero removing `panel.background` will break themes that have been built to differentiate the workbench from the editor, like this: https://raw.githubusercontent.com/Tyriar/vscode-theme-sapphire/master/images/preview-bright.png

Didn't we commit to this set of colors in 1.12 so this is breaking the public API we established? Yo seem to be removing it just in case some theme author somewhere uses a color that is vastly different to `editor.background`. Instead of removing it we should change the monaco editors within the panel to use `panel.background`, just like how the peek window's editor background is based on a key different to `editor.background`.

**Comment by bpasero** [comment]
@Tyriar good point on API compatibility, I restored the color. I still think there is tons of work involved to make it work properly though because just setting the background color of the editor is not enough, there is 50+ colors associated with the editor that all need to be set depending on the background color of the editor. 

I think `panel.background` today only works if you chose a color which is not so far off from the editor background color. I can maybe push a change so that at least the editor background gets this color and the most visible parts (line numbers, minimap).

**Comment by Tyriar** [comment]
@bpasero thanks, sounds like a good plan 👍

**Comment by bpasero** [comment]
Unfortunately I cannot set the background for minimap because that one is a canvas element, not using CSS.

![image](https://cloud.githubusercontent.com/assets/900690/26715622/bf2d8762-4776-11e7-9344-17669c2a7359.png)

**Comment by Tyriar** [comment]
@bpasero still looks much better than before imo, is there an issue tracking the minimap panel bg?

**Comment by bpasero** [comment]
@Tyriar no, not yet. Feel free to create. I actually find it weird to have minimap in output to begin with...

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/27979
