### ISSUE TITLE
Strange(Incorrect) translate in 1.11.2

### ISSUE THREAD

**Issue by ArianeLu** [Microsoft/vscode#24746]
- VSCode Version: 1.11.2
- OS Version: Windows (Not OS related issue)

Steps to Reproduce:
- Source Control: Translated to "源控件", Translate it back to English, it was "Origin Control", and "Control" mean "manage something", but translate "控件" only mean "A control, like button on the form'
- Commit Staged(Signed off): Translated to "递交已暂存的更改(已注销)", translate "已注销" mean "already logged out"
- Should not translate Git command, it's a command. See #6388

**Comment by ArianeLu** [comment]
Any progress?

**Comment by michelkaporin** [comment]
Please look into it, @danyeh.

**Comment by danyeh** [comment]
"Source control" translation already corrected by community contributor 'joelyang'. See https://www.transifex.com/microsoft-oss/vscode-workbench/translate/#zh-Hans/$/111041217?q=source control.
'Signedoff' translation has been fixed as well. See https://www.transifex.com/microsoft-oss/vscode-workbench/translate/#zh-Hans/$/111042857?q=Signed off
'Git command' can be translated if we are talking about command palette because loc'd text will co-exist with English side by side. 
I close this issue. 
@ArianeLu, translation now owned by community. It will be more efficient to correct in transifex directly. See instruction at http://vscodeloc.

**Comment by danyeh** [comment]
@ArianeLu .Sorry, the instruction for community localization is here http://aka.ms/vscodeloc
