### ISSUE TITLE
Intellisense not recognizing ES6 JavaScript prototype method on import

### ISSUE THREAD

**Issue by barakbd** [Microsoft/vscode#24747]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:01:14.464Z)
- OS Version: Linux x64 4.4.0-72-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|jshint|dbaeumer|0.10.15|
|vscode-eslint|dbaeumer|1.2.8|
|prettier-eslint-vscode|RobinMalfait|0.5.0|;

---

Steps to Reproduce:

1.Create class ("Foo") with prototype method ("Foo.prototype.add") in file "class.js" and export

```
export default Foo
```

2.Import Foo (using ES6 import - not require) into file "import.js"
```
import Foo from "./class.js"
```
3. In "import.js"  - create instance of class

```
var newFoo = new Foo()
```
4. Start typing the instance.method
```
newFoo.a
```
Expected: is the method will be autocompleted to show newFoo.add
Result: method is not autocompleted (though method works when run)

**Comment by mjbvz** [comment]
If you hover over `newFoo`, what is displayed? Can you also please share the definition of `Foo`?

**Comment by barakbd** [comment]
**"Class_Foo.js" File:**
```
class Foo{
    constructor(name){
        this.name = name;
    }
}
Foo.prototype.sayHello = function(){
    console.log('hello ' + this.name);
};
export default Foo;


```
**"test.js" File:**
```
import Foo from './Class_Foo.js';
var foo = new Foo('John');
foo.sayHello();

```
hovering over says: "var foo: Foo"
When I run test.js I get output: 
$ hello John

**Comment by mjbvz** [comment]
Thanks for the additional info.  This is actually fixed in the latest insiders build in my testing:

![screen shot 2017-04-14 at 1 37 09 pm](https://cloud.githubusercontent.com/assets/12821956/25055420/8beb0f58-2117-11e7-94d7-21dcbbcc56ea.png)


This insiders build include TypeScript 2.3 which likely fixed this at some point although I can't find the exact issue on their side that tracks this. TypeScript powers both our JS and TS language features.

Please try out the latest VSCode insiders build and let me know if you still see any issues here

**Comment by barakbd** [comment]
Ok, it works in the Insiders build.
Looking forward to the stable release!

Version 1.12.0-insider
Commit 9530cf6e2b804c4b986d97f105f88d40ee4d2c47
Date 2017-04-14T12:33:54.256Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0
