### ISSUE TITLE
Node 6.10.x incorrectly triggers legacy debug mode

### ISSUE THREAD

**Issue by sinbad** [Microsoft/vscode#24764]
- VSCode Version: 1.11.2
- OS Version: Windows 10

Steps to Reproduce:

1. Install Node 6.10.x (I installed current LTS 6.10.2)
2. Debug any Node JS application
3. Debug Console reports `Debugging with legacy protocol because Node v6.10.2 was detected.`

My assumption is that the version parsing thinks 6.10.2 is earlier than 6.3 due to lexical comparison?

**Comment by weinand** [comment]
VS Code's automatic protocol switching uses the "inspector" protocol only for node.js >= 8.0 (although this protocol is already supported since node.js >= 6.3).

You can force VS Code to use the "inspector" protocol by adding a `"protocol": "inspector"` to your launch config.

See https://code.visualstudio.com/updates/v1_11#_transitioning-to-the-inspector-protocol and https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_supported-nodelike-runtimes

**Comment by jdpunk1** [comment]
I've had a similar issue with a google api demo, I tried using Yarn instead of node start, so install yarn globally first, then run yarn start after npm install.. it may resolve the issue.

**Comment by weinand** [comment]
using Yarn cannot affect what debug protocol is being used.
My comment from above explains this.
