### ISSUE TITLE
Workbench did not finish loading in 10 seconds, that might be a problem that should be reported.

### ISSUE THREAD

**Issue by jrsquared** [Microsoft/vscode#24785]
On the latest version of Code (1.11.2) on Mac OS 10.12.4, with `--disable-extensions`, the progress ticker in the Explorer keeps moving, Code Helper eats up 130% CPU, and the console only shows

`Workbench did not finish loading in 10 seconds, that might be a problem that should be reported.`

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by jrsquared** [comment]
> On the latest version of Code (1.11.2) on Mac OS 10.12.4, with --disable-extensions

Already did.

**Comment by jrsquared** [comment]
A restart seemed to have fixed it, so closing this for now.
