### ISSUE TITLE
Using integrated terminal to cat file with lots of unicode hangs terminal

### ISSUE THREAD

**Issue by xavdid** [Microsoft/vscode#24795]
- VSCode Version: `1.11.2`
- OS Version: `macOS 10.12.4`

Steps to Reproduce:

1. Open integrated terminal
2. `cat` a file with a lot of unicode. I found it with [this](https://github.com/zapier/zapier-platform-cli/blob/master/src/commands/validate.js) file, but anything with a lot of printed unicode (eg `validate\n#Validating project locally.\n#\n# \u250C\u2500\u2500\u2500\u2500\u2500\u2500\u2500 ...` should work

The terminal window is unable to scroll while the unicode characters are visible. When it does recover, it scrolls normally when looking at previous lines. Scrolling down to the unicode block hangs it again.

Repro Rate: 100%

**Comment by Tyriar** [comment]
I cannot reproduce using `fish` or `bash`. What's in your settings.json?

**Comment by xavdid** [comment]
Sorry, this is in zsh (`v5.2`) with [oh_my_zsh](https://github.com/robbyrussell/oh-my-zsh) enabled. 

I recorded a quick example video here: https://www.youtube.com/watch?v=lkpLyl8_miE

I can scroll normally before the file is viewed, can't once it's there. After ~ 30 sec, the dead window dialog shows: 

<img width="482" alt="screen shot 2017-04-18 at 3 33 40 pm" src="https://cloud.githubusercontent.com/assets/1231935/25155965/b2c6226a-244c-11e7-9975-9af9259520fb.png">

It closes properly. If I keep waiting, the `Code Helper` process jumps to 98% CPU usage and in another 30 sec, the dialog pops up again.

**Comment by xavdid** [comment]
my settings.json is here: 

```
// Place your settings in this file to overwrite the default settings
{
    "editor.autoClosingBrackets": false,
    "files.trimTrailingWhitespace": true,
    "files.exclude": {
        "**/.git": true,
        "**/.svn": true,
        "**/.hg": true,
        "**/.DS_Store": true,
        "**/node_modules/**": true,
        "**/.sass-cache/**": true,
        "**/.bundle": true,
        "*.map.js": true,
        "dist": true
    },
    "editor.fontFamily": "Iconsolata, Monaco, 'Courier New', monospace",
    "window.zoomLevel": 0,
    "editor.wordWrap": "on",
    "editor.formatOnPaste": true,
    "editor.folding": true,
    "diffEditor.renderSideBySide": false,
    "standard.autoFixOnSave": true,
    "tslint.autoFixOnSave": true,
    "editor.tabSize": 2,
    "files.insertFinalNewline": true,
    "workbench.welcome.enabled": false,
    "workbench.colorTheme": "Monokai",
    "editor.minimap.enabled": false,
    "files.associations": {
      "Brewfile": "ruby"
    },
    "eslint.enable": false,
    "eslint.autoFixOnSave": true,
    "extensions.autoUpdate": true,
    "ruby.lint": {
      "rubocop": false,
      "ruby": true
    },
    "workbench.iconTheme": "vs-seti"
  }
```

**Comment by Tyriar** [comment]
@xavdid I notice the file is in the terminal rendered correctly before you run `cat`, how did you print that?

**Comment by xavdid** [comment]
Ah, that was the same file without the unicode. I tried it to ensure the unicode characters were the issue (not `cat` or something else in the file).

**Comment by Tyriar** [comment]
But there are still unicode characters in that file though, no? Like this one `┌`

**Comment by xavdid** [comment]
oh, you're totally right. The first copy of the file is [this](https://github.com/zapier/zapier-platform-cli/blob/master/src/commands/validate.js), which has the actual unicode and works fine. 

The non-working one is after that file's been run through babel and the unicode replaced with a string (`\u2514` & co). That's available [here](https://gist.github.com/xavdid/3b96d92e50b43ad33e5e5341c92eb126). Thanks for your patience here!

**Comment by Tyriar** [comment]
Oh ok, so no issue then 👍

**Comment by xavdid** [comment]
I mean, there's still the hang displaying `/u2514`.  I was mistaken in describing it, but there's definitely a bug.

**Comment by Tyriar** [comment]
@xavdid could you try running VS Code using `code --verbose` and pasting in the output after the hang/crash?

**Comment by xavdid** [comment]
Sure thing!

```
% code --verbose
[main 11:02:16 AM] Starting VS Code in verbose mode
[main 11:02:16 AM] from: /Applications/Visual Studio Code.app/Contents/Resources/app
[main 11:02:16 AM] args: { _: [],
  help: false,
  h: false,
  version: false,
  v: false,
  wait: false,
  w: false,
  diff: false,
  d: false,
  goto: false,
  g: false,
  'new-window': false,
  n: false,
  'unity-launch': false,
  'reuse-window': false,
  r: false,
  performance: false,
  p: false,
  'prof-startup': false,
  verbose: true,
  logExtensionHostCommunication: false,
  'disable-extensions': false,
  disableExtensions: false,
  'list-extensions': false,
  'show-versions': false,
  nolazy: false }
[76592:0421/110218:INFO:CONSOLE(28)] "Conflict detected, command `workbench.action.terminal.clear` cannot be triggered due to workbench.action.showErrorsWarnings", source: file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js (28)
[main 11:02:18 AM] IPC#vscode-workbenchLoaded
[VS Code]: detected unresponsive
```

anecdotally, having the window half (instead of full) width helped. When I would resize it, the terminal wouldn't wrap appropriately. That is, going from half -> full the text in the terminal was still unresponsive and wrapped at the half width.

**Comment by wrauner** [comment]
It seems that I found another string that crashes integrated terminal. Running same VSCode version and OS, I can reproduce similar behavior using string

`\x\x\x\x\x\x\x\x\x\x\x\x\x\x\x\x\x\x\x\x\x\x\x\x\x\x\x\x\x\x\x\x\x\x\x\x\x\x\x\x`

either by cat'ing it from a file or simply by pasting it into integrated terminal. I debugged the source code and the problem seems to start in xterm module, Linkifier class, _findLinkMatch method, line 242.

`const match = text.match(regex);`

after matching text (repeated x's) against regex:
`"/(((\.\.?|\~)|([^\0\s!$`&*()\[\]+'":;]|(\\s|\\!|\\$|\\`|\\&|\\*|(|)|\+))+)?(\/([^\0\s!$`&*()\[\]+'":;]|(\\s|\\!|\\$|\\`|\\&|\\*|(|)|\+))+)+)/"`

application becomes unresponsive. Hope that my findings can help you solve the issue.

**Comment by Tyriar** [comment]
@wrauner wow, great repro steps!

I think this is a case of 'catastophic backtracking' http://www.regular-expressions.info/catastrophic.html

**Comment by silasjmatson** [comment]
I've also experienced this issue.

Using zsh on macOS Sierra.

```
$ zsh --version
zsh 5.2 (x86_64-apple-darwin15.4.0)
```

**Comment by rmunn** [comment]
In [a comment on a now-closed duplicate report](https://github.com/Microsoft/vscode/issues/32605#issuecomment-322665703), I discovered that VS Code was becoming unresponsive for X seconds, where X was directly proportional to (2 ^ length of string). E.g., if a string that could trigger the bug was pasted in, and that string was 21 characters long, I found that VS Code was freezing for about 4.5 seconds. If I added one more hex escape to the end of the string, that 22-character string would freeze VS Code for 9 seconds. A 23-character string would freeze for 18 seconds, a 24-character string would freeze for 36 seconds, and a 25-character string would freeze for 72 seconds. (I stopped at 25 characters since the pattern was clear at that point).

**Comment by rmunn** [comment]
And since it hasn't been mentioned yet, I can also reproduce this on Linux (using the `bash` shell), but **not** on Windows. Which seems consistent with @wrauner's finding that the problem seems to be in the `xterm` module of the integrated terminal, since I assume that that module isn't used in the Windows build of VS Code.

**Comment by Tyriar** [comment]
The xterm module is used in Windows, things are handled a little differently though as pseudoterminals are emulated via the node-pty module (as opposed to being a native concept on Linux/macOS).

Windows uses slightly different path regexes due to different formats which is probably the reason if it doesn't happen on Windows.

**Comment by justlurking** [comment]
Any movement on solving this bug?  I have the exact same issue with Unicode characters.  Terminal window will not scroll for several seconds, while the Code - helper" process runs at 100% of CPU.  Eventually VS Code will stop responding altogether, and I'll get the "wait or close" prompt.

I switched from Atom to VS Code for the integrated Terminal and have found the terminal completely unusable due to this issue and the work that I'm doing.

VSCode Version: 1.15.1 and 1.16-insider
OS Version: macOS 10.12.6

I've tried the insiders build, and also tried launching "code-insiders --disable-extensions" without any improvement.  Repros 100% of the time.  My settings file:

`{
    "editor.fontSize": 15,
    "terminal.integrated.fontSize": 14,
    "extensions.ignoreRecommendations": false,
    "window.zoomLevel": 0
}`

I've also checked the developer tools console.  There are no info/warnings/errors, but under verbose logging I do see the following:

[Violation] 'setTimeout' handler took 21294ms
18:56:08.251 Terminal.ts:1076 [Violation] Handling of 'wheel' input event was delayed for 20800 ms due to main thread being busy. Consider marking event handler as 'passive' to make the page more responsive.
18:56:10.943 [Violation] 'setTimeout' handler took 2685ms
18:56:32.275 [Violation] 'setTimeout' handler took 21126ms
18:56:32.441 [Violation] 'setTimeout' handler took 165ms
18:56:32.939 [Violation] 'setTimeout' handler took 166ms
18:56:33.265 [Violation] 'setTimeout' handler took 325ms
18:56:43.882 [Violation] 'setTimeout' handler took 10616ms
18:56:46.522 [Violation] 'setTimeout' handler took 2639ms
18:56:46.726 [Violation] 'setTimeout' handler took 163ms
18:56:47.383 [Violation] 'setTimeout' handler took 656ms
18:56:47.562 [Violation] 'setTimeout' handler took 163ms

Please let me know if I can provide any additional information to help track down and squash this bug.  Thanks!

**Comment by Tyriar** [comment]
I believe it's caused by one of these regex's:

https://github.com/Microsoft/vscode/blob/e38f1d18c7e72690c8f19a1a28fb1369431ea75a/src/vs/workbench/parts/terminal/electron-browser/terminalLinkHandler.ts#L19-L24

The problem is that Chromium can't detect catastrophic backtracking cases and won't stop working until it finishes executing the regex. Can't even hide it in a `setTimeout` because it will still block. Any help on whether we can improve the regex without losing the link functionality would be helpful.

**Comment by Tyriar** [comment]
@rebornix can you see anything blatantly wrong in those regexes?

**Comment by Tyriar** [comment]
Nevermind, I fixed it. I just disallowed `\` characters in paths for the greater good.

Thanks for the push @justlurking, should make it into v1.16.0 :wink:

**Comment by xavdid** [comment]
awesome, thank you!

**Comment by justlurking** [comment]
Fantastic; thanks @Tyriar!
