### ISSUE TITLE
Ctrl+W doesn't work with active window

### ISSUE THREAD

**Issue by freud** [Microsoft/vscode#24819]
It doesn't work with default key bindings.
When I add `CTRL+W` manually to keybindings.json it works.
```
{
  "key": "ctrl+w",
  "command": "workbench.action.closeActiveEditor"
}
```

Keyboard shortcut editor shows double `CTRL+W` key binding like on the following screen:
![image](https://cloud.githubusercontent.com/assets/37286/25063341/1d7d2e40-21e2-11e7-8de7-3e724ab91889.png)

So `CTRL+W` doesn't work when we have only one occurrence of `CTRL+W` binding from default configuration.

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by freud** [comment]
Hi again,

It was an issue with one of my extensions.
Thanks for your suggestion.
