### ISSUE TITLE
[css] aural properties missing from Intellisense

### ISSUE THREAD

**Issue by CPANinjaDoug** [Microsoft/vscode#24893]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-caniuse|akamud|0.5.3|
|path-intellisense|christian-kohler|1.2.0|
|vscode-simpler-icons|davidbabel|1.3.0|
|vscode-generate-getter-setter|DSKWRK|0.4.2|
|tslint|eg2|0.12.0|
|debugger-for-phantomjs|iradul|0.1.1|
|debugger-for-chrome|msjsdiag|3.0.1|
|angular2-inline|natewallace|0.0.17|
|java|redhat|0.1.0|
|simontest|SimonTest|0.11.1|;

---

Steps to Reproduce:

1. Open a .CSS file in the code editor window
2. Create a style that includes an aural property (e.g., speak:none). VS Code will report is as an unknown property.

**Comment by aeschli** [comment]
It's currently filtered as according to the database we have it is not yet supported by browsers. I also couldn't find any information on https://developer.mozilla.org

**Comment by CPANinjaDoug** [comment]
It does appear to be supported (or at least available) in Chrome version 57. At least when I use the developer tools to inspect an element it shows “speak” as a style attribute and you can update that by changing the assigned style. I’ve also seen mention of support in Opera. 

 

It looks like Mozilla is working on this: https://bugzilla.mozilla.org/show_bug.cgi?id=1339987

 

The options available for “speak” in Chrome are:

Digits

Inherit

Initial

Literal-punctuation

No-punctuation

None

Normal

Spell-out

 

The W3C reports only none, normal, auto (and a draft shows never, always, auto).

 

I’m not sure “browser support” is really the best test, though. What does it actually mean in this case? The real support issue would be whether screen readers make use of the attributes. I don’t believe they do, but I would expect this to happen sooner rather than later.

**Comment by aeschli** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.
If you disagree and feel that this issue is crucial: We're happy to listen and to reconsider.
Maybe you want to give it a try yourself and provide the feature through an extension or a PR: We're happy to give advise and get you started.
Thanks for your understanding. Thanks for helping and happy coding!
