### ISSUE TITLE
Debt - Explorer & Open Editors Context menu needs to adopt menu contribution support

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#24900]
The TFSVC extension should be able to contribute to the "rename" group.

![image](https://cloud.githubusercontent.com/assets/172399/25096786/0fbde012-23a2-11e7-8e01-410c7a5d7895.png)

**Comment by isidorn** [comment]
After discussing with @bpasero the following needs to be done:

1. All actions need to be transitioned into commands. Some of these commands need to get a hold of the active tree which should be done using the `listService`
2. Context keys need to be managed by the explorer when selection changes in order to show / hide the actions. e.g context key if the selected file is a folder
3. Need to use groups to preserve the sorting of actions
