### ISSUE TITLE
Add option to reduce set of autofetch branches to branches that have been explicitly fetched by user

### ISSUE THREAD

**Issue by JllyGrnGiant** [Microsoft/vscode#24927]
- VSCode Version: Code 1.11.1
- OS Version: Windows 10

VS Code should have an option to only autofetch remote tracking branches that were explicitly fetched by the user.

I like to work with few fetched tracking branches in Git and often set my branches to track against particular upstream branches. I also like to "checkout tracking branches" to work in detached head mode. To facilitate this I only fetch branches I'm interested in. My work's repository has hundreds of branches I'm uninterested in. When autofetch is turned on VS Code fetches all of them. I'd like the autofetch feature for the branches I've fetched, but I don't want it to fetch all of them. So for now I've turned the feature off to avoid this.

Steps to Reproduce:

1. Turn on autofetch setting

**Comment by kdmu** [comment]
Interesting feature, I'll work on this if nobody minds. 😃

How about having an `autoFetchFrom: [branches]` option instead of tracking user fetched branches? I think it's more explicit since an user may fetch sporadically certain branch but don't want it as an autofetching branch.

Any thoughts @joaomoreno @JllyGrnGiant?

**Comment by joaomoreno** [comment]
Call it `git.autofetchRefs`. The default `null` means all get fetched.

**Comment by JllyGrnGiant** [comment]
That will work for me. Thanks, @kdmu for looking into this.
