### ISSUE TITLE
When dragging folder to new editor window (to use explorer), don't make it mandatory to save any unsaved files elsewhere

### ISSUE THREAD

**Issue by therobyouknow** [Microsoft/vscode#24959]
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T14:00:34.044Z)
- OS Version: Darwin x64 16.5.0
- Extensions: none
---

Steps to Reproduce:

1. open a new window, add some text, don't save it
2. open another new separate window, drag a folder from Finder to this window
3. observe that asked to save file. why?! just leave it there unsaved and allow me to get on and use the other new window with explorer thankyouverymuch!

**Comment by mjbvz** [comment]
@Tyriar I believe this is related to hot-exit. Can you please take a look

**Comment by Tyriar** [comment]
I cannot repro by dragging into the second window and that should trigger a reload.

Dragging the file into the first window (with the unsaved file) requires you to save the file regardless of what hot exit is set to. This is because the window you drag the folder into is being reloaded and opening the folder, which means that the file will be lost. Closing this in favor of https://github.com/Microsoft/vscode/issues/396 which should eventually lead to loading/unloading folders not requiring a reload which would fix this.
