### ISSUE TITLE
Using WSL - How to use Bash for the launch configurations?

### ISSUE THREAD

**Issue by electrotype** [Microsoft/vscode#25033]
- VSCode Version: 1.11.2
- OS Version: Windows 10  (Version 1703), with WSL enabled.

I asked [the question](http://stackoverflow.com/questions/43480997/vscode-with-wsl-how-to-use-bash-for-the-launch-configurations) on StackOverflow, but without any answers, so I guess it's maybe not possible...

I use Visual Studio Code to develop a TypeScript Node application on Windows 10, with WSL enabled.

Thanks to [other][1] [threads][2], I'm almost able to run a VSCode task with Bash on Ubuntu on Windows.

But now I try to do the same with a *launch configuration*. How can I make a launch configuration to use the `node` executable *installed in WSL* instead of the one installed on Windows?

If I run this command directly in the integrated terminal, with Bash, it works :

    node src/start.js

But when I press "`[F5]`" and start a launch configuration that runs this same file, I get an error : "*Error: %1 is not a valid Win32 application*". This is because the `oracledb` library is used and has been compiled in Bash, not in Windows.

How can I make a launch configuration use Bash to run Node?

  [1]: https://github.com/Microsoft/vscode/issues/6579
  [2]: https://github.com/Microsoft/vscode/issues/24967

**Comment by CherryDT** [comment]
You should be able to use `bash.exe -c node` (or probably `C:\Windows\sysnative\bash.exe -c node`) but you will then run into https://github.com/Microsoft/vscode/issues/24072 I think

**Comment by electrotype** [comment]
@CherryDT I'm not sure I understand what you suggest. Am I wrong or a launch configuration always uses `node` as the main program, so I can't make it use `bash.exe`. For example, this doesn't work in `launch.json` :

```
{
    "version": "2.0.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "test",
            "program": "C:\\Windows\\sysnative\\bash.exe",
            "args": [
                "-c",
                "node",
                "${workspaceRoot}/src/start.js"
            ],
            "cwd": "${workspaceRoot}",
            "outFiles": [],
            "sourceMaps": true,
            "internalConsoleOptions": "openOnSessionStart",
            "timeout": 20000
        }
    ]
}
```

I may not understand correctly, but I think this kind of launch configuration will run something like :

`node C:\Windows\sysnative\bash.exe -c node ${workspaceRoot}/src/start.js`

and of course the first "`node`" makes no sense. Please correct me if I'm wrong!

**Comment by CherryDT** [comment]
Not in `program`, but in `runtimeExecutable`.

**Comment by electrotype** [comment]
@CherryDT I try to reach the point where you are so I can ask this issue to be closed and follow yours!
Setting `runtimeExecutable` seems to be the way to go, indeed, thanks! But then, even without using `${workspaceRoot}`, I'm still unable to make a simple example work. For example :

```
{
    "version": "2.0.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "test",
            "runtimeExecutable": "C:\\Windows\\sysnative\\bash.exe",
            "runtimeArgs": [
                "-c",
                "pwd"
            ],
            "outFiles": [],
            "sourceMaps": true,
            "internalConsoleOptions": "openOnSessionStart",
            "timeout": 20000
        }
    ]
}
```
This results in : "`/bin/bash: --debug-brk=37360: invalid option ...`".

Do you have a sample of a working launch configuration using`bash.exe`, without the need of an intermediate `.bat` file?

**Comment by CherryDT** [comment]
@electrotype Can't test it right now, I remember I originally used a batch file but I did so in order to convert the path from Windows to WSL.

I would try to include `-c node` in the `runtimeExecutable` already, but I don't know if this works the way I think it does. Did you try that?

**Comment by electrotype** [comment]
No luck sadly...

`"runtimeExecutable": "C:\\Windows\\sysnative\\bash.exe -c pwd",` 
=>
_`Error - Attribute 'runtimeExecutable' does not exist ('C:\Windows\sysnative\bash.exe -c pwd').`_

and

`"runtimeExecutable": "\"C:\\Windows\\sysnative\\bash.exe\" -c pwd",`
=>
_`Error - Cannot launch debug target (spawn "C:\Windows\sysnative\bash.exe" -c pwd ENOENT)..`_

**Comment by CherryDT** [comment]
I see. Then you probably need a batch file, but I'm not sure if this even works (because you can't `CreateProcess` a batch file I think), maybe you need a custom EXE.

I was now able to find the old files and see how I did it back then (before I opened https://github.com/Microsoft/vscode/issues/11681) - I had a more complex approach there because I tried to also convert paths, and environment variables (this was before Anniversary Update by the way). This worked but then I ran into the issue with the paths with VSCode debugging.

What I did back then was to build an executable on the Windows side which translates paths and environment variables and base64 encodes them to avoid escaping issues, then starts bash.exe with a custom shell script which decodes everything again and finally launches node.

FreeBasic source code of the Windows-side program: https://gist.github.com/CherryDT/0045624611834c888c24797df2844386

WSL-side shell script:
https://gist.github.com/CherryDT/44788497e8870121969b840892d99025

**Comment by electrotype** [comment]
Nice hacking!

I'm not sure I'm ready to go this way though... VSCode should make this way, way much easier.

I'll stick to the regular `cmd` shell for now...

**Comment by CherryDT** [comment]
As mentioned, this doesn't lead to anywhere anyways because of the path issues. However, according to https://github.com/Microsoft/vscode/issues/24072 and similar issues, it is possible to get WSL node to launch by setting the terminal shell (`terminal.integrated.shell.window`, I believe) to bash - but I don't observe this behavior, so I'm not exactly sure what is going on there.

My current workflow is much less hackish than what I tried there before: I just have bash as terminal shell and run `node --inspect --debug-brk` from there, and I use VSCode to _attach_ to it (instead of launching it). The downside is that I have to set `remoteRoot` correctly which is problematic if the `launch.json` is to be checked into a repository (because of paths which are different for individual developers).

**Comment by dbaeumer** [comment]
@isidorn assigning to you. It is about launch configs not tasks.

**Comment by isidorn** [comment]
Assigning to @weinand to check if he has ideas. Otherwise stack overflow is the best route for questions like this.

**Comment by weinand** [comment]
I'm only speculating here but you could try this:
- configure VS Code's integrated (or external) terminal  to use WSL (I assume this possible but I've never tried this myself).
- setup your launch config so that it launches the debug target in either the integrated or the external terminal (use IntelliSense to find the possible values):
   ```js
   {
	"type": "node",
	"request": "launch",
	"name": "Launch Program",
	"program": "${workspaceRoot}/app.js",
	"console": "integratedTerminal"
   }
   ```

With this VS Code will launch "node" in the integrated terminal and I assume that it will use the WSL "node".

**Comment by electrotype** [comment]
@weinand You are right, `integratedTerminal` doest work, in that sense that it does use the correct `node` executable!

For reference, both "externalTerminal" and "internalConsole" fail though :

"externalTerminal" :
![](http://i.imgur.com/ZcP0pKF.png)

"internalConsole" :
![](http://i.imgur.com/t0CqODa.png)

That said, "integratedTerminal" only works when the entry file is at the very root. For example, a `${workspaceRoot}/src/start.js` (instead of `${workspaceRoot}/test.js`) fails :

![](http://i.imgur.com/jo1zF3h.png)

But I think I've seen there already are existing issues about those missing backslashes?

**Comment by DhirajAdPushup** [comment]
@electrotype I was also trying to use `integratedTerminal` option and got this.
![screenshot 160](https://cloud.githubusercontent.com/assets/10044846/25937184/45e02bb0-3648-11e7-9e6a-dc8a8d29a936.jpg)

I guess when bash changes directory (**check second highlighted box** ) all the slashes are missing (**check first highlighted box** ). Issue definitely is because of missing slashes.

**Comment by weinand** [comment]
Currently VS Code launch configurations do not support WSL. The code is not aware of WSL and just assumes Windows which results in paths with backslashes.

**Comment by CherryDT** [comment]
@DhirajAdPushup your problem is #24072

**Comment by ryanstevens** [comment]
I have scoured the internet and as far as I can tell you cannot debug VSCode using WSL / bash as the executing environment.  For now I'm going to switch back using chrome dev tools built in debugger via the `--inspect` flag.

**Comment by CherryDT** [comment]
You can, you just can't launch it. Launch it manually with `--inspect` or `--inspect --debug-brk`, then attach to it using VSCode. Set the `remoteRoot` in your attach launch config to the WSL path of your project, then also the breakpoints will work properly.

**Comment by ryanstevens** [comment]
@CherryDT Thanks!  I'll try that.

**Comment by DhirajAdPushup** [comment]
@ryanstevens If that works then do share the process and experience here, that will be a great help.

**Comment by atrauzzi** [comment]
Would very much love to see this supported.  With WSL having such great support for for 3rd party applications and how much better suited linux is for web dev, I'd much prefer to develop with it as my underlying environment.

**Comment by sylvainlap** [comment]
I tried to launch my Node app with the `--inspect` flag in WSL, and Attach the VSCode debugger to it, but my breakpoints do not works, VSCode tells me that there is a sourcemap problem.

What do I need to do to make my breakpoints work ?

**Comment by CherryDT** [comment]
@sylvainlap as I mentioned above, set the `remoteRoot` in your attach launch config to the WSL path of your project in order to make breakpoints work.

**Comment by Alkasai** [comment]
@CherryDT that doesn't work. Say my WSL project path is `/mnt/c/Users/abc/project1`, but when I open files in VS code their path is `C:\Users\abc\project1`, so setting break points still won't work.

**Comment by CherryDT** [comment]
@Alkasai : Why? That's exactly what the `remoteRoot` is for. You tell VSCode that your "remote server" (in this case WSL) uses the root path `/mnt/c/Users/abc/project1` so it knows how to translate the path. It's the same thing when you are debugging on an actual remote server via SSH tunnels for example.

**Comment by Alkasai** [comment]
Ah thank you it finally works! I wasn't sure what the format was `remoteRoot` and I think I was missing `localRoot`.
Also tried `"request": "launch"` and it seems it still doesn't work. I mean the breakpoints work, but it doesn't know know how to translate a path like `/src/....`. So whenever it tries to interpret this kind of path it fails.

**Comment by weinand** [comment]
Status update:

Today VS Code node debugging knows nothing about "WSL" but since it supports "remote debugging", the WSL case is already supported nicely when launching the target manually in WSL and then using an "attach" configuration (see @CherryDT's config from above).

For the WSL "launch" case we've received https://github.com/Microsoft/vscode-node-debug/pull/156 and https://github.com/Microsoft/vscode-node-debug2/pull/126 that add the required functionality to the node debugger.

**Comment by Alkasai** [comment]
@CherryDT not sure if you can help. Your solution used to work for me for a while. I also had `"sourceMaps": true` in there.
```
{
	"name": "Attach to Process",
	"type": "node",
	"protocol": "inspector",
	"request": "attach",
	"port": 9229,
	"localRoot": "${workspaceRoot}",
	"remoteRoot": "/mnt/c/Users/david/proj/my-project",
        "sourceMaps": true
}
```

But since I switch to a new machine, the break points stopped working for me. It still attaches the debugger and breaks on the entry, just like it used to. But all breakpoint now show as 'Breakpoints set but not yet bound'.

**Comment by bitcrazed** [comment]
Hi all. Note that node debugging support in WSL is in the way soon!

**Comment by atrauzzi** [comment]
@bitcrazed - That's awesome!  What are the specific things your team has had to do to facilitate this?  ie: What barriers would I be hitting right now if I tried?

**Comment by weinand** [comment]
In the October release VS Code supports the `useWSL` flag for both the "legacy" and the "inspector" protocol of node.js.

**Comment by atrauzzi** [comment]
@weinand - You should make that `useWsl`.

**Comment by weinand** [comment]
@atrauzzi no, the name of the flag is `useWSL`.

**Comment by atrauzzi** [comment]
This is mostly in passing, but the only reason the flag in your comments jumped out at me is because most communities have settled on lower case letters for everything after the first when applying pascal case to acronyms: https://stackoverflow.com/questions/15526107/acronyms-in-camelcase (one of probably many references available)

**Comment by weinand** [comment]
@atrauzzi thanks for the references. Now I understand.
However, since the name 'useWSL' shipped in September, we will not change the spelling in October and break launch configs.

**Comment by atrauzzi** [comment]
It would be worthwhile to see this as an overall suggestion. Not just for the current flag in question here.
