### ISSUE TITLE
replace all with regexp (the end of row $)  not working properly

### ISSUE THREAD

**Issue by menorless** [Microsoft/vscode#25079]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|numbered-bookmarks|alefragnani|0.7.0|
|csharp|ms-vscode|1.8.0|;

issue:
replace all with regexp not working properly, when use end of row ($) only replace the end of row of end of file.

Steps to Reproduce:

1. Open csv file
2. find & replace
3. select regular expression
4. find end of row (**$**)
5. replace by two comma (,,)
6. click on replace all

**Comment by mjbvz** [comment]
I'm unable to reproduce this in the current 1.11.2 on MacOS. @menorless Do you also see this issue in a new file or in other file types?

**Comment by menorless** [comment]
@mjbvz  look
![capture](https://cloud.githubusercontent.com/assets/780662/25278563/86a323c8-2671-11e7-8f8d-91208bfe5429.gif)

**Comment by alexandrudima** [comment]
@menorless 
Your steps work for me. Perhaps what's weird is that since the search matches **a position and not a range**, there are no highlights in the editor, only in the overview ruler. Is that what you mean:
![25079](https://cloud.githubusercontent.com/assets/5047891/25333817/2f7a2164-28ec-11e7-8dd3-e5c13ac09615.gif)

**Comment by menorless** [comment]
I can see, that happend only with file.
You can close this issue then.
