### ISSUE TITLE
Suggestions in comments on trigger characters despite setting

### ISSUE THREAD

**Issue by Dima4ka** [Microsoft/vscode#25109]
- VSCode Version: 1.11.2
- OS Version: macOS 10.12.4

Steps to Reproduce:

1. Install C# extension
2. Set:

```
"editor.quickSuggestions": {
    "other": true,
    "comments": false,
    "strings": false
  },
```

3. In .cs file write a block comment like this:

```
/// <summary
/// Checks that Index method returns proper model and status codes.
/// </summary>
```

4. Put dot in comment (at the end)

### Expected

Nothing shows up

### Actual

Silly suggestion (`!--`) shows up

**Comment by mjbvz** [comment]
Thanks @Dima4ka! I believe that I was also able to reproduce this issue in TypeScript

**Comment by jrieken** [comment]
Yes. That is the design because trigger characters still have a purpose there, think of `@` completions for doc comments as in `/** @param <suggests foo-param>`. Unsure what `!--` is but my guess is that it's a snippet, right @Dima4ka ?

**Comment by Dima4ka** [comment]
@jrieken No, it was not snippet, it is rather "abc" guess (not intelligent). Looks like part of the HML comment `<!-- comment -->`. Anyway, although I appreciate Intellisence in comments, it is annoying when I type a line of text, hit dot to complete my sentence, hit Enter to move to the new line and it turns out that I have typed random piece of text.

**Comment by jrieken** [comment]
<img width="649" alt="screen shot 2017-04-24 at 08 51 46" src="https://cloud.githubusercontent.com/assets/1794099/25325320/51687f58-28cb-11e7-8d36-e3178c760821.png">

No 'ABC' icon for me, but the keyword icon. My guess is that this is coming from the C# extension. @DustinCampbell Ideas?

**Comment by DustinCampbell** [comment]
Note that in C#, XML documentation comments aren't precisely "comments". They're very special. Also, in the example, the `<summary>` isn't closed, so in a sense, you're tying in a tag and not in the comment itself, which is why these keywords would be suggested (contextually). That said, it's clearly a bug that typing a period makes completion appear here. That shouldn't happen. This bug should probably be moved to omnisharp-vscode.

@jrieken, we're starting to get into territory that it is pretty tricky to get make correct for C# without a little help from VS Code's completion API to let us know *how* completion was triggered. C# completion can do different things depending on what the user did. Knowing whether the user triggered completion by typing the last character that appears in the document or whether they typing <kbd>Ctrl+Space</kbd> can be important.

**Comment by jrieken** [comment]
Yeah, this has come up before (https://github.com/Microsoft/vscode/issues/752) but hasn't been tackled yet. It's a little harder to do without breaking the API because we want to keep the rule "CancellationToken comes last"...

I'll move the issue to vscode-omnisharp to begin with ;-)

**Comment by jrieken** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#1424
