### ISSUE TITLE
[html] configure initial indentation for script/style contents

### ISSUE THREAD

**Issue by gengxuelei** [Microsoft/vscode#25117]
- VSCode Version: 1.11.2
- OS Version:Win10

Steps to Reproduce:

1.
2.
```
<script>
  export default {
    name: 'app'
  };

</script>
<style scoped>
  .main {
    max-width: 580px;
  }
</style>
```
Whether it can be formated:
```
<script>
export default {
  name: 'app'
};

</script>
<style scoped>
.main {
  max-width: 580px;
}
</style>
```
![image](https://cloud.githubusercontent.com/assets/11707936/25261030/8e45f91e-2682-11e7-80a9-42c7ff7cbbe0.png)

**Comment by aeschli** [comment]
The html formatter doesn't have an option to control the indentation in scripts and styles. It's currently also not planned to add this.

**Comment by aeschli** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.
If you disagree and feel that this issue is crucial: We're happy to listen and to reconsider.
Maybe you want to give it a try yourself and provide the feature through an extension or a PR: We're happy to give advise and get you started.
Thanks for your understanding. Thanks for helping and happy coding!
