### ISSUE TITLE
Faced problem with dangerous Git COMMAND 

### ISSUE THREAD

**Issue by prokawsar** [Microsoft/vscode#25153]
I have deleted my entire project accidentally by pressing "Discard All Changes" option on Git.
This type of **DANGEROUS** command should not be in GUI. 

I know it's my mistake, why I didn't know about it. But it should be in consider that all user/developer are not same.

- VSCode Version: 1.11.1
- OS Version: Windows 10

**Comment by CherryDT** [comment]
Maybe all "discard" type actions there need a confirmation box. Something like "discard all" maybe even one with a timer (i.e. you can confirm only after 3 seconds to prevent people from accidentally dismissing it without realizing).

**Comment by joaomoreno** [comment]
@prokawsar The command has a confirmation dialog once you click it. The message in it has `ALL changes` in it.

![image](https://cloud.githubusercontent.com/assets/22350/25325561/6d5feca4-28cc-11e7-9612-d0ab9e20012a.png)

We can further add `This is irreversible!` to the message. But we won't take the command away since it's useful for a git workflow.

If you were working in a git workspace, you can commit often to avoid such situations.

**Comment by CherryDT** [comment]
Probably it would already help to just have the default focus on the cancel button instead of "discard all changes"
