### ISSUE TITLE
Problem with embedding C# syntax between delimiters

### ISSUE THREAD

**Issue by Hugibeer** [Microsoft/vscode#25154]
Hello.

I am writting a simple language extension to provide syntax highlighting for our custom DSL platform in VSCode. I am trying to embed C# highlighting in between single quotes (') and SQL in between double quotes. The problem is with C# highlighting. It seems that VSCode doesn't recognize ending single quote, and keeps the rest of the file in C# highlighting mode. Source of the extension project is on https://github.com/Hugibeer/RhetosDSL with sample test file to show the behavior.
I am not really sure if this is bug in VSCode, maybe C# support for VSCode is treating ending single quote as a start of the character definition, or is this a question of which extension "came first" to evaluate the single quote. I think it is because Sublime Text doesn't have this issue :) If I am doing something wrong, please help me correct this.

- VSCode Version: 1.11.2
- OS Version: Windows 10

Steps to Reproduce:

1. Download code
2. Open Rhetos.vscode folder and start the extensions
3. Open file Samples\SampleTest.rhe to see that ShortString is not recognizd as keyword.

Thank you

**Comment by mjbvz** [comment]
@alexandrudima can you take a look. Here's an example definition from the grammar:

```
	"csharp": {
			"begin": "'",
			"patterns": [
				{
					"include": "source.cs"
				}
			],
			"end": "'"
		},
```

This sounds similar to the issue we had with markdown code block language highlighting leaking outside of the code block itself. We eventually switched to begin/while to fix this

**Comment by alexandrudima** [comment]
@Hugibeer

Most likely you are hitting the fundamental design limitation of TM grammars when including patterns. Once control is inside an embedded state, **it and only it** owns the parsing until it decides to pop.

If inside the grammar associated with `source.cs` there is a rule that consumes `'`, it will consume `'`, regardless of the `end` condition you place. I can explain the difference with Sublime via Sublime shipping a different grammar associated with `source.cs` than VS Code does. 

You can try registering the same grammar for `source.cs` as Sublime does and most likely, the differences will be gone. Better yet, we should check how TextMate works, since it is the de-facto standard having introduced TextMate grammars.
