### ISSUE TITLE
IP list for proxy exception

### ISSUE THREAD

**Issue by Danieleeee** [Microsoft/vscode#25184]
- VSCode Version: Latest
- OS Version: Windows 7

Can I have the IP address list used by vscode?
I must set them as exceptions in the proxy configuration.
I tried to configure vscode with proxy settings, but it does not work properly in all cases, especially with extensions updating

Thanks.

**Comment by CherryDT** [comment]
I don't think that an IP exception list would be a good solution, because IP addresses change, and in some cases (e.g. Amazon's load balancers) it can be that there is no way to specify a list of IPs at all (other than specifying the whole IP range of the provider, which defeats the purpose and may not even be possible). I think it would be more important to understand what the issue is when working through the proxy.

**Comment by Danieleeee** [comment]
ok, thanks

**Comment by CherryDT** [comment]
I meant to say: What exactly are the proxy issues you are experiencing?

**Comment by joaomoreno** [comment]
Support is already there by using `--proxy-bypass-list`. Documentation comes with #27838
