### ISSUE TITLE
Incorrect tool-tip and definition path for import statements in js file

### ISSUE THREAD

**Issue by waynebloss** [Microsoft/vscode#25197]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|xml|DotJoshJohnson|1.7.0|
|EditorConfig|EditorConfig|0.9.3|
|java|redhat|0.1.0|
|html-preview-vscode|tht13|0.1.1|
|cordova-tools|vsmobile|1.2.7|;

---

Steps to Reproduce:

1. Clone https://github.com/reactjs/react-redux (edit: and run `npm install`)
2. Open the new repo folder with vscode.
3. Edit the file src/components/connectAdvanced.js.
4. Hover your mouse pointer over the string `'invariant'` on the line that says `import invariant from 'invariant'`.
5. Press F12 or otherwise activate the `Go to definition` command.

In step 4, I expected to see a tool-tip displaying the path to my local `node_modules` directory inside of my repo. Instead, I was shown a path to the global `node_modules/@types` directory on my system.

Likewise in step 5, when I pressed F12 vscode opened a `index.d.ts` instead of opening the local `node_modules/invariant/index.js` file.

Knowing the types that vscode is using to display Intellisense is not really useful to me because they almost never match the version of the code that I'm actually working with. I would **strongly** prefer to at least be able navigate to the actual implementation easily instead of to the `.d.ts` definition file.

Thank you.

**Comment by mjbvz** [comment]
Thanks for the suggestion.

This is currently a limitation of how the TypeScript server that powers both our JS and TS intellisense works. We use `d.ts` files for module intellisense in order to provide rich suggestions without having to parse or understand the JavaScript implementation. This is done both for performance reasons and to leverage TS language features when describing JavaScript APIs
 
Ideally the `d.ts` files should be transparent in this whole process however. I know the TS team has discussed improving this and here are a few related issues on the TypeScript side:

https://github.com/Microsoft/TypeScript/issues/14479
https://github.com/Microsoft/TypeScript/issues/6209

Closing this as upstream since there is not much we can do on the VSCode side to fix this. I'll make sure the TS team is aware of the issue

Thanks
