### ISSUE TITLE
Look into using npm@3 in build

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#2523]
Would address the long path issue.

Related to #2498

**Comment by Tyriar** [comment]
Linux npm3 issue: https://github.com/Microsoft/vscode/issues/2474

**Comment by Tyriar** [comment]
I don't seem to be having any issues now building with npm3 on Linux or OSX

**Comment by zrax** [comment]
It appears that the flattening of modules also breaks the package tasks currently...  It copies the top-level dependencies directly into the package directory's node_modules, but doesn't copy any dependencies (since in npm@2, such dependencies are already included in each package's directory).  This means that many dependent modules are missing from the package directory :(

**Comment by joaomoreno** [comment]
Yeah, not doing this any time soon.
