### ISSUE TITLE
Suggestion: ability to hide the mouse cursor when typing

### ISSUE THREAD

**Issue by warpdesign** [Microsoft/vscode#25251]
It would be nice if there was an option to hide the mouse cursor when typing. It would automatically reappear on mouse move.

**Comment by mlongval** [comment]
Under MacOS this happens automatically. (well on my system at least)

I found this: 

[https://github.com/jcs/xbanish](https://github.com/jcs/xbanish)

I haven't tried it on my Linux systems (yet).  I don't know about Windows systems. 
(I am guessing there is something already that does this).

**Comment by warpdesign** [comment]
@mlongval There seem to be an option for that in Windows too, but it's not working with VSCode.

![hypertermcomplete](https://cloud.githubusercontent.com/assets/199648/25409874/147a4af0-2a14-11e7-95f9-b45a166ef477.gif)

**Comment by alexandrudima** [comment]
To keep the number of issues in our inbox at a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: we look at the number of votes the issue has received and the number of duplicate issues filed. Thank you for your time and understanding.

If you disagree and feel that this issue is crucial: we're happy to listen and to reconsider.
