### ISSUE TITLE
Auto-indent on paste

### ISSUE THREAD

**Issue by poklau123** [Microsoft/vscode#25260]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|crane|HvyIndustries|0.3.6|
|NodeAssertionSnippets|jaymorrow|0.1.0|
|format-php|Kasik96|1.1.2|
|php-docblocker|neilbrayfield|0.4.2|
|laravel-blade|onecentlin|1.8.1|
|laravel5-snippets|onecentlin|1.3.4|
|upload|wuwei|0.1.5|;

---

Steps to Reproduce:

1.Create a file named 'test.php', and type some code like this:
![image](https://cloud.githubusercontent.com/assets/7621696/25366098/f7417b4e-299f-11e7-96ac-0b061390975c.png)

2.When I try to paste these selected multiline code to the first line of function 'test', it shows:
![image](https://cloud.githubusercontent.com/assets/7621696/25366148/5724212e-29a0-11e7-85af-55c7a6530b8d.png)

---
Why do not auto-indent except the first line of pasted codes?

**Comment by alexandrudima** [comment]
fyi @rebornix

**Comment by CherryDT** [comment]
@poklau123 About the "first line" question: You have copied the first line _without_ the indention, but the second line _with_ the indention, so of course the idention is unequal after pasting. To have it equal, you need to copy both lines _with_ indention (e.g. by using the left border of the code window where the mouse cursor points right).

In general, though, I am also missing a way to auto-indent after paste. There have been various issues in GitHub about this before (see also https://github.com/Microsoft/vscode/issues/13945), and in January an option was added to do that (`"editor.formatOnPaste": true`). However, I didn't want it to _format_ on paste (including things other than just indenting), I wanted it only to _indent_, in a way similar to how Sublime Text does it on Ctrl+Shift+V.

My solution for now is the plugin [https://marketplace.visualstudio.com/items?itemName=Rubymaniac.vscode-paste-and-indent](Paste and Indent). I have changed the key bindings so that Ctrl+V does normal paste while Ctrl+Shift+V invokes `pasteAndIndent.action`. It does have a slightly different behavior from Sublime Text though (see https://github.com/rubymaniac/vscode-paste-and-indent/issues/2): You have to set the cursor at the indention level which sould be the lowest indention you want for the pasted code, and then paste. It will not automatically determine the correct indention based on the surrounding code as Sublime Text did, and in the meantime I actually found this behavior not so bad because I have more control over how things get pasted.

**Comment by poklau123** [comment]
@CherryDT Thanks for your advice! It's better for me to set option `"editor.formatOnPaste": true` , it is enough. TY!

**Comment by druellan** [comment]
@poklau123 I was also experimenting with `"editor.formatOnPaste": true`. The thing is: if the extension you are using for formatting does not allow a "format-selection" command, it usually ends formatting all the file instead of the pasted code.

I'm also a bit confusing about the paste&format thing. When the discussion stared it was related to paste&indent, but then the paste&format discussion started and took over like a more advanced replacement, but I still believe paste&indent should be part of the editor for cases on where you don't want to format, but also, for languages that have no suitable formatter available, like SCSS.

**Comment by CherryDT** [comment]
@druellan I agree, that's what I meant in my comment above and that's why I ended up using the Paste and Ident extension.

**Comment by rebornix** [comment]
Already added this feature in Insider build, thanks!
