### ISSUE TITLE
Spectron Smoketest

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#25291]
- [x] Fully automate parts of smoke test on Windows - npm install & run a script. Anybody in team can run it.
- [x] Explore visual review by talking screenshots 
- [x] Can run smoke test against insiders/stable
- [x] Support to run smoketest during integration builds/CI (moved to #27845)
- [x] Support incremental wait timeouts on test failures
- [x] Make tests more robust by adding 'test classes' to DOM elements, add data attributes _(investigated)_
- [ ] Implement [the full smoke test](https://github.com/Microsoft/vscode/wiki/Smoke-Test)
  - [x] Data Migration
  - [x] Data Loss
  - [x] First User Experience
  - [x] Explorer
  - [x] Configuration and views
  - [x] Search
  - [x] CSS
  - [ ] Markdown _(skipped, webview has nodeIntegration == false)_
  - [x] JavaScript
  - [x] Debugging JavaScript _(no debug run-time test)_
  - [x] Git
  - [x] Integrated Terminal
  - [x] Status bar
  - [x] Tasks
  - [x] Extensions
  - [ ] Accessibility _(skipped due to no voice-over coverage from Spectron)_
  - [x] Localization
- [x] Support to run smoke test against fresh user data and populated user data
- [x] Contributing.md that documents how to contribute a new smoke test
- [x] Run on multiple platforms
- [x] Support Insiders (e.g. window title checks)
- [x] _Explore smarter addressing of editor span tags_

### Issues
- [x] Passing the user data directory to the spectron tests (https://github.com/electron/spectron/issues/189)
- [x] WebDriverIO command deprecation warnings due to ChromeDriver not implementing W3C WebDriver spec _(solved by redirecting warnings to separate log)_

### Unresolvable Issues
- Faking native dialogs - context menu, dialog popups (e.g. in getting asked for save on dirty editor close)

**Comment by michelkaporin** [comment]
Looked into `Make tests more robust by adding 'test classes' to DOM elements, add data attributes` task in the list above and came to a conclusion that it will not make them more robust because we do not often change CSS selectors in our code for the key elements that are tested in the Smoke Test. 

If we see that we do, or start doing changing them more often going forward, we can add those. At the current stage it seems an overhead to add those. In terms of the work on the smoke test code it will be only replacing currently used selectors with another ones, however VS Code core code will grow without any big reason.

**Comment by michelkaporin** [comment]
The implementation has been merged into master in #2784, hence closing the issue.
