### ISSUE TITLE
Your Updates Suck

### ISSUE THREAD

**Issue by svanetten1976** [Microsoft/vscode#25297]
The last two times I tried to update this software, I had to go in and find and manually shut down rogue VS processes running through my computer's Resource Monitor because the update failed. Luckily, I was able to pretty quickly figure that out both times, but many users might not. Its a quality IDE, but the updates are total garbage.  Just an FYI

- VSCode Version: 1.11.2
- OS Version: Windows 10 

Steps to Reproduce:

1. Try to update
2. Update fails

**Comment by james-gould** [comment]
On the flip side, I have daily updates (if not bi-daily) with VSCode-Insiders and it's never been a problem.

**Comment by CherryDT** [comment]
I encountered the same issue from time to time.

Since VSCode is targeted to developers, though, I would assume that the majority of VSCode users would be able to figure out how to solve this problem. Not saying it is ok like this, just that it's less critical an issue in my opinion.

**Comment by alexandrudima** [comment]
@svanetten1976 Could you help us reproduce and figure out which process lingers? i.e. this might be a deeper problem than just updating (VS Code processes might linger around in other cases). To find out which process remains, you can use e.g. process explorer and hover over the process to find out its arguments:

![image](https://cloud.githubusercontent.com/assets/5047891/25429092/263aaa0a-2a78-11e7-820c-eeedbad30ec2.png)

Once we identify which process is lingering around, we can proceed investigating.

**Comment by svanetten1976** [comment]
Hi @alexandrudima thanks for getting back to me. Well, when I shut down those rogue processes that were preventing the update (and preventing the program from even re-opening), I used the native Resource Monitor to end those tasks. Here is a screenshot of what it was like, but this is with everything working now that I've righted the update. I wish I had taken a screenshot of both the rogue processes I had to kill yesterday and the error message alert that was thrown when I first tried to launch VS after the failed update. I can't imagine I am the first person to have reported this issue? Anyways, if this occurs again in a future update, I will try to capture as much relevant information as possible and follow up for you. Thank you for looking into this, I'm sure its something your team wants to get fixed. Cheers -- Steve
![processes](https://cloud.githubusercontent.com/assets/1958184/25436365/1a1183d2-2a61-11e7-8eeb-dca2a6903769.png)

**Comment by alexandrudima** [comment]
Thank you @svanetten1976 

VS Code has a multi-process architecture. This allows us to be as fast as possible even if some extension miss-behaves and ends up in a computationally intensive task (a nice way of saying a while true loop ... ).

To fulfil their purpose, extensions themselves sometimes decide to spawn additional processes (e.g. language servers for rich language features, etc.). Sometimes we spawn short-lived processes to speed things up (e.g. searching in files spawns multiple processes).

The interesting case is if any of these places forget to properly kill their child processes. Since there are so many processes being spawned for various tasks, it is sort of important we figure out which process lingers. The best way to find out which one it is is to use a tool such as **process explorer** which can show the command line arguments the process was spawned with.

It is not so interesting to see these processes when VS Code is running, but more interesting to find out what they are when VS Code is shut down.

Under normal conditions, all processes are killed or shut themselves down gracefully, but there might be certain cases where this doesn't happen. We're considering adding a watchdog process that could monitor them, but we don't have that implemented at this time.

Thank you for getting back to me, and if you spot any VS Code processes running after you closed VS Code, please do let us know.

**Comment by svanetten1976** [comment]
@alexandrudima OK, I figured it might have been a VS extension that wasn't being properly shut down that was causing the problems I encountered. If I run into this issue with the next update, I will do a better job of documenting it and let you know. Thanks for taking the time to reply to this post. Have a good day! -- Steve
