### ISSUE TITLE
Ability to print

### ISSUE THREAD

**Issue by amir511** [Microsoft/vscode#25374]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

**Comment by alexandrudima** [comment]
As a workaround, you could copy-paste to e.g. Word and paste from there (the syntax highlighting will be maintained).

**Comment by amir511** [comment]
Yes good idea... but it would be better off course to print directly from vs code

**Comment by umpenrage** [comment]
I have to say this is an idiotic trend with newer text editors. SublimeText, VScode, and Atom all do not have the ability to print. How the hell is this not considered during implementation of a text editor??? People us text editors for notes and other reasons. Not having the feature to print is completely idiotic. The software is incomplete. How about releasing software when it is actually finished. Printing is a standard across most modern software. Hell even Notepad++ has a print feature. Notepad it self has a print feature. Is this really that hard to understand??? There must be some mental deficiencies with the developers. No, I'm not going to install some half-assed plug in to fix this issue. The Printer should be native. Copying from one text editor to another in order to print is completely retarded.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/5953
