### ISSUE TITLE
Settings editor gets emptied

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#25383]
Since a couple of days (actually might be weeks) I often see the right hand side of the settings editor turn completely empty. This typically happens when switching between tabs and then later coming back to the editor:

![image](https://cloud.githubusercontent.com/assets/900690/25425821/757cc39c-2a6d-11e7-9939-7aa01e54bf82.png)

in this case what I did was:
* change some settings
* open a file to the side
* click on another tab (settings got hidden)
* start a search
* click back to settings

Not sure yet how to reproduce better though.

**Comment by sandy081** [comment]
I hope this is not content getting erased? You see the content after closing and opening the editor?

**Comment by bpasero** [comment]
@sandy081 yeah no worries, no data loss. Just an empty editor.

**Comment by sgtoj** [comment]
@bpasero Are you sure the User Settings were not wiped? I have lost all my settings (I do a gist backup, though). 

`%USERPROFILE%\AppData\Roaming\Code - Insiders\User\settings.json` is empty.  Well, there is a new **C/C++ extension** setting that was added probably due to the fact I issued a update to the extension just before I hit **Update Now** to update VS Code Insiders.

Could it be combination of updating the extension immediately before issuing the VS Code Insider's update caused this wipe of the `settings.json`?  May be when the **C/C++ extension**  added `"editor.quickSuggestions": false` (wasn't there before) at the first load after updating the extension and (in this case) first load of the latest build, it add a new setting to *blank* settings and saved it?

**Comment by bpasero** [comment]
Yes I am very sure because I did not loose my settings.

**Comment by sgtoj** [comment]
Could the combination of events I posted lead to my settings being wiped? My [settings](https://gist.github.com/sgtoj/a44f0d4bd21e74db9ff6b17ea7a9510f) were definitely all there before updating to the latest Insider's build. 

It is easily noticeable that my settings were wipe due the fact I use a custom full workbench theme that you have been working on for the past couple months. At the first launch after updating, there was no custom theme applied and the file bar was not hidden per the pre-wiped settings. 

*Since it is hard to actually convey feelings in text, please understand this is not a rant. Furthermore, I definitely understand the risk of using beta and Insider's builds of software, hence the backing up of my settings. I just want to make you aware that my settings were, without a any doubt, wiped.*

**Comment by sandy081** [comment]
@sgtoj Thanks for sharing your issue.. I have also heard few people complaining about the same. But unfortunately, there are no clear steps to get into this situation. I created a separate issue for settings getting wiped out - #25427. It would be great if you can provide how you landed into that problem

**Comment by bpasero** [comment]
I believe that https://github.com/Microsoft/vscode/issues/25580 could also have caused this because the symptoms are very similar. Let's close this one optimistically until we see it again.

**Comment by sandy081** [comment]
Duplicate of #25580
