### ISSUE TITLE
Breakpoints tree does not grow

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#25384]
I collapsed all the other sections in order to get a good look at the breakpoints, but the list does not adjust to the window size:

![breakpoints](https://cloud.githubusercontent.com/assets/5047891/25425939/e5256b18-2a6d-11e7-96b9-d2f3da306bf4.gif)

**Comment by isidorn** [comment]
I agree that in this scenario it would be better that the breakpoint view automatically expands to the maximum size.
However on the implementation side it is a `AdaptiveCollapsibleViewletView` which does not grow past its limit (which is a flow in this case).

just fyi @joaomoreno

**Comment by joaomoreno** [comment]
Uh-hoh

**Comment by isidorn** [comment]
@joaomoreno too bad this was not fixed with the split view refactoring

**Comment by joaomoreno** [comment]
You should fix it at your layer. The breakpoints view should have an infinite max size only if all of the other views have a finite max size; it should be fixed otherwise.

**Comment by isidorn** [comment]
@joaomoreno I can fix it in my layer but it will be ugly. Currently my DebugViewlet is not aware of all the panes which are contributed.
So I would have to introduce a hack in my debug viewlet to listen to all the changes of all my views and in case that all of them are expanded excepet one I let that one know that it can have an infinite size.

Doesn't it make more sense to handle this internaly in the split view?

Or am I missing something here?

**Comment by joaomoreno** [comment]
You got the SplitView which gives you the minimalist [IView](https://github.com/Microsoft/vscode/blob/master/src/vs/base/browser/ui/splitview/splitview.ts#L22) interface. On top of that you have the PanelView which gives you more powerful panels.

If you need a view which dynamically changes the properties of a panel based on all the other panels' states, I'd either code it in the user's domain (DebugViewlet) or create yet another wrapper. Otherwise I have to introduce a _maximum size is infinite if all other panels have non-infinite maximum size_ setting per panel. That's the kind of setting which got us into the old splitview messy code.

**Comment by bpasero** [comment]
Now I am not seeing a scrollbar when breakpoints overflow:

![flicker_chrome58](https://user-images.githubusercontent.com/900690/33666426-3f6cbbf8-da9a-11e7-9c18-5da51b2d79c4.gif)

**Comment by isidorn** [comment]
Unrelated issue which was also happening in stable, please open a new bug

**Comment by isidorn** [comment]
Voila https://github.com/Microsoft/vscode/issues/39796
