### ISSUE TITLE
Completely zooming in and out causes font to slightly blur

### ISSUE THREAD

**Issue by Eksrow** [Microsoft/vscode#254]
This should probably be very low prio, it probably doesn't happen often.
It's also fixed by restarting visual code.

This is what it looks like default:

![default](https://cloud.githubusercontent.com/assets/4998498/11274683/3350697c-8eda-11e5-8797-806278ef6e93.png)

Now press ctrl++ x 9 times to completely zoom in
Now press ctrl+- x 9 times to completely zoom out

The font now seems blurred

![blurred](https://cloud.githubusercontent.com/assets/4998498/11274713/67a06c22-8eda-11e5-95af-0069d0a64892.png)

This is on Windows 8.1
![version](https://cloud.githubusercontent.com/assets/4998498/11274754/a86736dc-8eda-11e5-9a5a-c94d8864a009.png)

Great product btw, I really enjoy using it!

**Comment by smuuf** [comment]
I am probably screwed, since I percieve the VS Code's font blurry even in the `default` state, aren't I? Will this be fixed? The font is just not enough sharp as it is.

**Comment by bpasero** [comment]
@smuuf can you compare with 0.9.x release of VS code? I dont see blurriness on my Windows machine in code. Maybe you are still zoomed in?

**Comment by smuuf** [comment]
Unfortunately I can't compare it with any older version. I installed it today and fiddled a bit with for a bit, until the font's bluriness became too much of a displeasure. (on Win 7)

The question that I really want to ask here is this:

![f](https://cloud.githubusercontent.com/assets/4998498/11274683/3350697c-8eda-11e5-8797-806278ef6e93.png)

This picture *(the top one from the original post)* - **is this how the font should look like?** Because it looks too blurry for me, too. Less than in the second one, but still.

**Comment by shurcooL** [comment]
@smuuf Are you looking at the image with 100% zoom in a separate tab, so that it's displayed with 1:1 pixel ratio?

https://cloud.githubusercontent.com/assets/4998498/11274683/3350697c-8eda-11e5-8797-806278ef6e93.png

If you're looking at it in this issue, keep in mind it's scaled down via CSS because its full width doesn't fit into the width of the conversation.

**Comment by bpasero** [comment]
We pushed a major update to the UI framework to our insiders release and would appreciate feedback if this issue got resolved. You can give it a try from our insiders release today: http://code.visualstudio.com/Download#insiders

Happy for feedback!

**Comment by alexandrudima** [comment]
Fixed (for the case when zooming with ctrl+= or ctrl+- or via `window.zoomLevel`) with 289370f2f335eeb2cd8b74cd8f20101d1ed3335a

**Comment by shurcooL** [comment]
@alexandrudima Does that mean window zoom level no longer needs to be restricted to 100% and higher (i.e., you can't zoom below 100% with Cmd+-)?

**Comment by alexandrudima** [comment]
I think Cmd+- does not go below 100%, but `window.zoomLevel: -1` worked for me when doing it from user settings.

**Comment by shurcooL** [comment]
> I think Cmd+- does not go below 100%

I believe that was implemented because of the blurring issue (see [comment](https://github.com/Microsoft/vscode/pull/434#issuecomment-158865596) by @bpasero):

> We chose to not allow for zooming below 0 because some people end up in this state and wonder why the UI looks blurry.

Now that it's fixed, can't that restriction be lifted?

In other words, isn't forcing user to use `window.zoomLevel` instead of just Cmd+- to go below 100% no longer neccessary?

**Comment by bpasero** [comment]
I am easy to change this so that you can also zoom out.

**Comment by alexandrudima** [comment]
@joaomoreno You can verify by inspecting that we don't use translate3d on the dom nodes (easiest to spot is the editor scrollbar) when zoomed out or zoomed in.
