### ISSUE TITLE
Editor should provide shortcut to defocus editor to help navigate controls using tab

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#25419]
- VSCode Version: latest
- OS Version: Windows

Currently I need to use Ctrl+M however this is a toggle. What I would prefer is something like Escape to defocus the editor and focus the editor tool bar.

**Comment by alexandrudima** [comment]
:-1: I use Escape a lot (e.g. to cancel selection or remove multiple cursors) and would find it very surprising if one of the times I press it the focus would leave the editor.

**Comment by dbaeumer** [comment]
The key doesn't necessarily need to be Escape. We could use another combination. It is more the fact that Ctrl+M is a toggle that bothers me.

**Comment by alexandrudima** [comment]
@dbaeumer 

The reason `ctrl+m` is a toggle is due to a limitation in our platform. The way this works today is the following:
```
{ "key": "tab",                   "command": "tab",
                                     "when": "editorTextFocus && !editorReadonly && !editorTabMovesFocus" },
{ "key": "shift+tab",             "command": "outdent",
                                     "when": "editorTextFocus && !editorReadonly && !editorTabMovesFocus" },
```
The `ctrl+m` directly toggles the context key `editorTabMovesFocus`. In other words pressing `ctrl+m` disables or enables our bindings for `tab` or `shift+tab`.

When our bindings are disabled, `tab` and `shift+tab` are not `defaultPrevented` and then the browser executes the default action of moving the focus to the next or previous element in the focus ring.

The browser does not offer any API AFAIK to programmatically get the next or previous element in the focus ring, so we cannot add a command to "jump to next focus ring element". AFAIK the only way to jump to the next element in the focus ring is to **not preventDefault()** on the tab keypress.

**Comment by dbaeumer** [comment]
@alexandrudima thanks for the detailed explanation. Looks like that what we have is the best we can do. Closing the issue then.

**Comment by alexandrudima** [comment]
@dbaeumer We have keybindings for jumping to places:

* `ctrl+0`, `ctrl+1`, `ctrl+2`, `ctrl+3`
* `ctrl+pageup`, `ctrl+pagedown`

But we don't have any keybinding for jumping to the current editor's title area. Perhaps we can ask @bpasero nicely and he'll add one.

**Comment by bpasero** [comment]
Not sure this helps a lot, do we also add kebindings to jump from the editor to the viewlet actions? If someone feels strong about this, PR me..
