### ISSUE TITLE
Settings getting wiped out

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#25427]
Please provide the steps or scenarios how you landed into this particular issue of settings getting wiped out. It will be helpful to understand the root cause and fix it.

Meanwhile I would also think about recovery/prevention strategy.

**Comment by sgtoj** [comment]
1. Launched pre-update VS Code
   - Was previously using Monday's Insider's release (there wasn't one yesterday?)
1. Updated **C/C++** extension.
   - Only extension that needed to be updated.
1. Waited to until **C/C++** extension to finish updated.
    - i.e. Waited until the **Reload** option was available but did *not* click it.
1. Clicked VS Code's **Update Now** to update VS Code. 
    - This closed VS Code and begin to update it.
1. VS Code automatically reopen after VS Code finished updating.
    - It open my previous opened project.
    - My custom settings were no longer in effect at this time. 
1. Closed and relaunched VS Code because my theme was missing.
    - Thought maybe relaunching would solve the problem.
1. Open the User Setting since my theme was still missing.
    - Noticed at this point, the only thing in the settings was a *new* **C/C++** setting.
1. Confirmed settings were completely wiped by navigating to the `settings.json` directly.
    - With the exception of the a new C/C++ setting.
       - `"editor.quickSuggestions": false`
    - `%USERPROFILE%\AppData\Roaming\Code - Insiders\User\settings.json`

Some time after updating VS Code, I did see a **settings** or **settings.json **tab (that I didn't explicitly 
 opened) open with the right side of the editor being completely blank as described in #25383. However, explicitly opening User Settings showed there was  a **C/C++ extension**.

**Comment by sandy081** [comment]
Closing this as there are not any such reports from past 6 months.
