### ISSUE TITLE
extra space is added after every line of the selection

### ISSUE THREAD

**Issue by verebes** [Microsoft/vscode#25423]
- VSCode Version: 1.11.2   ( commit: 6eaebe3b ) 
- OS Version: Windows 10 

Steps to Reproduce:
1. Open a new Visual Studio Code editor
2.  press 'a' and enter
3.  press 'b' and enter
3.  press 'c' and enter
4.  select all the lines
-> you will see there is an extra space added after every line of the selection
5. apply 'Join Lines' command
-> the lines are joined, but there is an extra space in the text after every line: 'a b c'
![vscode-bug-selection](https://cloud.githubusercontent.com/assets/1622867/25431964/ffcb1ee4-2a82-11e7-80f2-d5ef549e9753.gif)

**Comment by CherryDT** [comment]
It would appear that this is intentional (looking at https://github.com/Microsoft/vscode/blob/8cb7cc0cb426df17005fa94bf189577e5d693644/src/vs/editor/contrib/linesOperations/common/linesOperations.ts#L591 and following lines).

The editor will intelligently detect whether spaces make sense or not. In your case, the result would have been that the three "words" `a`, `b`, `c` are mashed together, which is normally unintentional, hence the spaces were added.

Try to join the following lines to see what I mean:

```
test();
/*
    This is a comment!
    Yay.
*/
```

The result will be:
```
test(); /* This is a comment! Yay. */
```

...which makes a lot more sense than just blindly joining like this:
```
test();/*    This is a comment!    Yay.*/
```

**Comment by alexandrudima** [comment]
There are no spaces added when typing. It is indeed the join lines command that adds those spaces.
