### ISSUE TITLE
Emmet: Improve "Wrap with abbreviation" input description

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#25441]
Testing #25358

![image](https://cloud.githubusercontent.com/assets/22350/25439834/df4274cc-2a9d-11e7-952c-379d22103ff1.png)

There should be a short description of _what_ I should provide in that input box. Similar to git clone:

![image](https://cloud.githubusercontent.com/assets/22350/25439867/f477e85e-2a9d-11e7-9b18-10a4e177fcfb.png)

**Comment by joaomoreno** [comment]
Same for `Update tag`, a better description would simply be `Tag name`:

![image](https://cloud.githubusercontent.com/assets/22350/25439922/1af18fee-2a9e-11e7-9145-a3f1223c8d81.png)

**Comment by ramya-rao-a** [comment]
Good point

**Comment by ramya-rao-a** [comment]
Fixed with https://github.com/Microsoft/vscode-emmet/commit/a16f5bcc1400027c6ef21481e774f35774e17934

**Comment by joaomoreno** [comment]
Seems fixed, but there's no more `Emmet 2.0` actions...

**Comment by ramya-rao-a** [comment]
The below 5 built-in commands are now routed to the emmet extension if the user has the extension installed and enabled. So no more `Emmet 2.0` actions.

`Emmet: Update Tag`
`Emmet: Remove Tag`
`Emmet: Go to Matching Pair`
`Emmet: Wrap with Abbreviation`
`Emmet: Expand Abbreviation`

This was done so that the existing keybindings for these actions continue to work for the user.
And from the user's perspective, there is no difference in usage.
