### ISSUE TITLE
Swipe should work with any choosen gesture

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#25447]
Testing #25325

- to get swipe working I have to change the OSX preferences as shown here:
![image](https://cloud.githubusercontent.com/assets/900690/25441163/bad143e4-2aa1-11e7-98d0-26471d105135.png)
- why can't I choose to swipe pages with 2 fingers?

**Comment by bpasero** [comment]
We should follow up with Electron on this, we are just using the swipe event and that only seems to support 3-finger swipe: https://github.com/electron/electron/blob/master/docs/api/browser-window.md#event-swipe-macos

**Comment by fatty1380** [comment]
As someone who has always used the "Two-Finger Scroll" setting, switching to "3 Finger Swipe" is extremely disorienting. Two finger mode is akin to "natural scrolling" that Apple brought about with the iPhone; pages come in from the right, and you push them back to the right to go back. The Three finger mode feels "inverted" coming from this habit.

Hopefully this can be figured out here or in Electron - I doubt Apple will be adding a "Swipe Direction: Natural" setting to the "More Gestures" screen 😝

**Comment by brennanMKE** [comment]
I also use the 2 finger swipe regularly with Xcode and Safari. I have also mapped the equivalent hot keys in VS Code to match Xcode. I want the editors I use to use the same keys and gestures so I am not disoriented. If it has to be added from the Electron side I'd have it align well with how the Mac works. Instead of just calling it swipe, there should be a distinction between swiping between pages/documents and swiping between full screen apps. I use 2 for pages/documents and 3 for screens.

The gesture also cannot simply be a single event. It has to have a start, progress and end so that it can move the current document forward and backward as the user swipes. See apps like Safari and Xcode for the behavior. And for 3 finger swipes you can create multiple virtual screens and full screen apps and swipe between them.

**Comment by bpasero** [comment]
Closing, no plans to work on this currently.
