### ISSUE TITLE
Debugger isn't showing TypeScript source

### ISSUE THREAD

**Issue by SetTrend** [Microsoft/vscode#2544]
In a TypeScript project the VS Code debugger displays the generated JavaScript code instead of the TypeScript code:

![vscode debugger no typescript](https://cloud.githubusercontent.com/assets/9283914/12677669/e05d070e-c69a-11e5-9aed-21727a4a6fd1.png)

What's wrong?

Shouldn't the IDE better emit a warning when it can't find the corresponding map referenced in a file and provide a list of locations to the user listing where it's unsuccessfully been searching for the original source?

See this sample repository for a reference: [SetTrend/TS18N](https://github.com/SetTrend/TS18N).

**Comment by weinand** [comment]
@SetTrend Thanks for providing the sample repository. I tried this with VS Code 0.10.6 on Windows 10 and I don't see a VS Code problem here.

The debugger stops in the *.js file because the source map does not have a mapping for the first line ("use strict"). If you perform one step, the debugger will hit the first line in the TypeScript file just fine. The VS Code strategy for dealing with missing mappings is to show the "truth" (i.e. the *.js file) and not "invent" a bogus location in the TypeScript source.

BTW, this source map visualisation shows the missing mapping:

[visualisation](http://sokra.github.io/source-map-visualization/#base64,InVzZSBzdHJpY3QiOwp2YXIgZnMgPSByZXF1aXJlKCJmcyIpOwpmdW5jdGlvbiBUZXN0U3RyZWFtKHBhdGgpIHsKICAgIGZzLmNyZWF0ZVJlYWRTdHJlYW0ocGF0aCwgeyBlbmNvZGluZzogInV0ZjgiIH0pLm9uKCJyZWFkYWJsZSIsIGZ1bmN0aW9uICgpIHsKICAgICAgICBjb25zb2xlLmxvZyh0aGlzLnJlYWQoMSkpOwogICAgfSk7Cn0KT2JqZWN0LmRlZmluZVByb3BlcnR5KGV4cG9ydHMsICJfX2VzTW9kdWxlIiwgeyB2YWx1ZTogdHJ1ZSB9KTsKZXhwb3J0cy5kZWZhdWx0ID0gVGVzdFN0cmVhbTsKCi8vIyBzb3VyY2VNYXBwaW5nVVJMPVRlc3RTdHJlYW0uanMubWFwCg==,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIlRlc3RTdHJlYW0udHMiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IjtBQUNBLElBQU0sRUFBRSxHQUFHLE9BQU8sQ0FBQyxJQUFJLENBQUMsQ0FBQztBQUV6QixvQkFBbUMsSUFBWTtJQUU5QyxFQUFFLENBQUMsZ0JBQWdCLENBQUMsSUFBSSxFQUFFLEVBQUMsUUFBUSxFQUFFLE1BQU0sRUFBQyxDQUFDLENBQUMsRUFBRSxDQUFDLFVBQVUsRUFBRTtRQUU1RCxPQUFPLENBQUMsR0FBRyxDQUFDLElBQUksQ0FBQyxJQUFJLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQztJQUMzQixDQUFDLENBQUMsQ0FBQztBQUNKLENBQUM7QUFORDs0QkFNQyxDQUFBIiwiZmlsZSI6IlRlc3RTdHJlYW0uanMiLCJzb3VyY2VSb290IjoiLi4vc3JjLyJ9,Ly8vIDxyZWZlcmVuY2UgcGF0aD0iLi4vaGVhZGVycy9ub2RlL25vZGUuZC50cyIgLz4KY29uc3QgZnMgPSByZXF1aXJlKCJmcyIpOwoKZXhwb3J0IGRlZmF1bHQgZnVuY3Rpb24gVGVzdFN0cmVhbShwYXRoOiBzdHJpbmcpCnsKCWZzLmNyZWF0ZVJlYWRTdHJlYW0ocGF0aCwge2VuY29kaW5nOiAidXRmOCJ9KS5vbigicmVhZGFibGUiLCBmdW5jdGlvbiAoKQoJewoJCWNvbnNvbGUubG9nKHRoaXMucmVhZCgxKSk7Cgl9KTsKfQ==)

**Comment by SetTrend** [comment]
@weinand :

Thank you very much for taking the time to shed light on my problem and solving it! :clap: :smile:

**Comment by weinand** [comment]
I'm glad that I was able to shed some light on this (and that I do not have to fix a bug here 😎)

**Comment by SetTrend** [comment]
:smile_cat: 

Well, if I may still add a humble wish:

I now am aware of this behaviour. But other users may not be. And I may be confused myself again when the mapped source won't be displayed after stepping over a number of lines (which is a use case that may occur).

I believe it would be helpful if there was some minor visual cue provided by Code (e.g. a short message in the status bar) when hitting such break point, informing the user that everything in regard to mapping is alright, there's just no mapping for the current position and the original source is used for the current breakpoint. E.g. `No mapping in mapped source for code at breakpoint. Using original source.`

**Comment by weinand** [comment]
Valid request, but this will require a protocol addition and we will have to spend some design cycles on this...
We could piggyback this info on the Stopped event and show it either in the stack:

![2016-02-02 22-54-02](https://cloud.githubusercontent.com/assets/1898161/12765713/40fe5e24-ca00-11e5-86d2-c3dfc43396cb.png)

or in the editor header:

![2016-02-02 22-55-46](https://cloud.githubusercontent.com/assets/1898161/12765723/4a1148fa-ca00-11e5-9a41-e71056b612e6.png)

@isidorn what do you think?

**Comment by isidorn** [comment]
@weinand maybe instead decorate the file name in the callstack in gray / red and on hover show the info that the mapping is missing.
Or a combination of your first idea with this? 
'Paused on entry. Some source maps missing'
And then the call stack could indicate which one
