### ISSUE TITLE
Cannot read property 'resource' of null when adding new debug configuration

### ISSUE THREAD

**Issue by Nicodem** [Microsoft/vscode#25466]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|vscode-eslint|dbaeumer|1.2.8|
|beautify|HookyQR|1.0.2|
|csharp|ms-vscode|1.9.0|
|PowerShell|ms-vscode|0.12.2|
|debugger-for-chrome|msjsdiag|3.0.1|
|vscode-icons|robertohuertasm|7.6.0|
|vscode-react-native|vsmobile|0.3.2|
|markdown-pdf|yzane|0.1.7|;

---

Steps to Reproduce:

1. Open Visual Studio Code
2. Ctrl-Shift-D to activate Debug Pane

Result:
There is no Debug Configuration dropdown displayed on top of debug pane.
Moreover when clicking in menu Debug > Add Configuration, I get an error "Cannot read property 'resource' of null". I cannot add a Debug Configuration.

**Comment by shkey** [comment]
I have the same problem.

**Comment by isidorn** [comment]
This is fixed in the latest insiders. You can try it out https://code.visualstudio.com/insiders
Or wait for the next stable release next week

**Comment by lhorace** [comment]
This issue is _not_ completely fixed in the latest insiders build:

![vscode version](https://cloud.githubusercontent.com/assets/12678456/25560193/2a85c018-2d1b-11e7-88a7-57ba7948d81e.png)

![vscode window](https://cloud.githubusercontent.com/assets/12678456/25560198/510330ae-2d1b-11e7-959c-b11c3d00ef97.png)

**Comment by isidorn** [comment]
@lhorace do you have reproducable steps to always get this?

**Comment by dethwyn** [comment]
@isidorn 
Step 1: Run VS code (or VS code insiders)
Step 2: Clicking in menu Debug > Add Configuration
We see the error and cry.
The program can't find the launch.json

**Comment by isidorn** [comment]
The issue here is that you have a no folder workspace and you are trying to add debug configurations. Advanced debug configuratoins(`launch.json`) are not supported in a no folder workspace - if you would like that to be supported please file a new feature request and we will consider it.

The current fix pushed handles the error case more gracefully and informs the user he/she should first open a folder.

**Comment by eflatz** [comment]
I had the same error while trying to run debug on the individual file in the editor. It would fail silently after selecting PHP  in dropdown. Opening folder in VS Code instead of file solves the issue.

As a proposal maybe to put the same warning on the debug button after click if there are no configurations yet added.
