### ISSUE TITLE
Cannot Theme Suggest Widget ReadMore Button

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#25487]
In the suggest widget, I was not able to find a way to customize the color of the `Read More...` info button:

![screen shot 2017-04-26 at 3 04 52 pm](https://cloud.githubusercontent.com/assets/12821956/25459176/deb2921e-2a91-11e7-8999-aa9cffb44e09.png)

Maybe I was overlooking a setting? I initially expected  its color to be derived from `infoBackground`

**Comment by aeschli** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.
If you disagree and feel that this issue is crucial: We're happy to listen and to reconsider.
Maybe you want to give it a try yourself and provide the feature through an extension or a PR: We're happy to give advise and get you started.
Thanks for your understanding. Thanks for helping and happy coding!
