### ISSUE TITLE
Prevent VS Code from closing when no open files and pressing CTRL-W

### ISSUE THREAD

**Issue by stefangabos** [Microsoft/vscode#25536]
- VSCode Version: 1.11.2
- OS Version: Windows 10

Is it possible to *not* close VS Code when pressing CTRL-F4 / CTRL-W and there are no open files? 

I usually have a bunch of files open, related to what I'm currently working on, and when I'm done, I just want to close them all quickly and get them out of the way and for that, I'm used to keeping CTRL-W pressed until all files are closed. With VS Code that leads to the editor being also closed after the last file is closed.

Thank you!

**Comment by CoenraadS** [comment]
Maybe this will help you: https://github.com/Microsoft/vscode/issues/1764#issuecomment-230674122

**Comment by stefangabos** [comment]
Adding `workbench.action.closeActiveEditor{ "key": "cmd+w", "command": "-workbench.action.closeWindow", "when": "!editorIsOpen" }` stil closes the editor when using CTRL-W. 

Interestingly enough, CTRL-F4 doesn't do it even though the default action is the same as for CTRL-W 
`workbench.action.closeActiveEditor`

**Comment by bpasero** [comment]
Sorry, but this is not the right place for questions. Please post questions over at StackOverflow: http://stackoverflow.com/questions/tagged/vscode

Thanks for understanding.

**Comment by stefangabos** [comment]
Can we consider this a feature request? :)

**Comment by Arnavion** [comment]
For <kbd>Ctrl</kbd><kbd>F4</kbd>, the current default is already `{ "key": "ctrl+f4", "command": "workbench.action.closeActiveEditor" }` which has the requested behavior.

<kbd>Ctrl</kbd><kbd>W</kbd> is also bound to it with `{ "key": "ctrl+w", "command": "workbench.action.closeActiveEditor" }` by default, so you'd think it also already has the requested behavior. In reality there's another default binding `{ "key": "ctrl+w", "command": "workbench.action.closeWindow", "when": "!editorIsOpen" }` that seems to override the first one and causes <kbd>Ctrl</kbd><kbd>W</kbd> to close VSCode when no editors are open.

So the fix is to duplicate the first binding of <kbd>Ctrl</kbd><kbd>W</kbd> as a user override, ie add `{ "key": "ctrl+w", "command": "workbench.action.closeActiveEditor" }` to `keybindings.json`

**Comment by Arnavion** [comment]
For <kbd>Ctrl</kbd><kbd>F4</kbd>, the current default is already `{ "key": "ctrl+f4", "command": "workbench.action.closeActiveEditor" }` which has the requested behavior.

<kbd>Ctrl</kbd><kbd>W</kbd> is also bound to it with `{ "key": "ctrl+w", "command": "workbench.action.closeActiveEditor" }` by default, so you'd think it also already has the requested behavior. In reality there's another default binding `{ "key": "ctrl+w", "command": "workbench.action.closeWindow", "when": "!editorIsOpen" }` that seems to override the first one and causes <kbd>Ctrl</kbd><kbd>W</kbd> to close VSCode when no editors are open.

So the fix is to duplicate the first binding of <kbd>Ctrl</kbd><kbd>W</kbd> as a user override, ie add `{ "key": "ctrl+w", "command": "workbench.action.closeActiveEditor" }` to `keybindings.json`

**Comment by stefangabos** [comment]
Thanks, that did the trick!
