### ISSUE TITLE
Improve autosuggest with module exports

### ISSUE THREAD

**Issue by tSte** [Microsoft/vscode#25533]
- VSCode Version:  1.11.2
- OS Version: Win 8.1 64

Steps to Reproduce:

1. Create ES6 module with named export(s)
2. Import it

Intellisense suggests almost everything:
![suggest1](https://cloud.githubusercontent.com/assets/8778539/25476218/c5b59eac-2b39-11e7-927d-b3a203361a42.png)

Exports are recognized:
![suggest2](https://cloud.githubusercontent.com/assets/8778539/25476259/eb07f1aa-2b39-11e7-9961-285d7917b8bd.png)

It would be great if intellisense were suggesting only relevant exports or at least move them to the top of the list.

**Comment by jrieken** [comment]
@tSte What is you configuration value for `"editor.snippetSuggestions"`? I looks to me that it's set to always sort snippets atop?

**Comment by tSte** [comment]
@jrieken it is `inline`. I know that I can leave it to `bottom`, but... I want to use `inline` everywhere else. It doesn't make sense to suggest this inside of `import { ... }` statements.

**Comment by jrieken** [comment]
Yes, but our snippets aren't contextual (unfortunately). We don't have much information when inserting them since they are computed statically. We have three well known scopes: *code*, *comments* and *strings*. Making snippets aware of that is tracked here: #22661 but I am afraid it won't help you.

Because we have smart snippets we recommend to use extensions that are more contextual and can decide if a position is good for snippets. Closing as question because there is not much we can do. Thanks for understanding and Happy Coding
