### ISSUE TITLE
Annoying popup

### ISSUE THREAD

**Issue by rajinder-yadav** [Microsoft/vscode#25537]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:01:14.464Z)
- OS Version: Linux x64 4.4.0-72-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|one-monokai|azemoh|0.2.4|
|vscode-markdownlint|DavidAnson|0.7.2|
|vscode-eslint|dbaeumer|1.2.8|
|EditorConfig|EditorConfig|0.9.3|
|tslint|eg2|0.12.0|
|cpptools|ms-vscode|0.11.0|
|theme-panda|tinkertrain|0.5.0|
|vim|vscodevim|0.6.20|;

Whenever I am typing I get this suggestion popup that is really annoying. I am unable to cancel it hitting ESC key. 

Also it obscures the code I need to view while I am writing code, this is not helpful. I would suggest placing it below the cursor.

Also how to I disable this option, I don't know what it is called.

---
![image](https://cloud.githubusercontent.com/assets/439226/25481065/81511022-2b19-11e7-9275-cbef2b3cf160.png)

Steps to Reproduce:

1. Start typing, use an object that have various method.
2. See annoying obscuring popup that will not go away.

**Comment by rajinder-yadav** [comment]
The escape key cancel the popup, discovered the vim plugin was eating it up. However the other issue still exist, and how to disable. Thanks!

**Comment by CherryDT** [comment]
This popup also annoys me very much, although it goes away after ESC for me, it just comes back every time.

For example, when I write code like this:

```
someObj.someFunction({
    a: 1,
    b: {something: 2}
})
```
...then I get such a popup again and again during writing the contents of the object, and it shows me the help for `someFunction` which I don't need at that point. It is just obscuring the code I wrote in the previous lines, which is very distracting for me.

I wonder whether there is a way to improve this, so that for example it will stay dismissed after pressing ESC once until reaching the next parameter of the function (and then it should not come back just because I call another function as parameter, e.g. `someFunction(<ESC press>a: abc(<abc popup is OK>)<here someFunction popup should NOT come back>, <here it can come back>...)` - not sure how to explain it better than that, I hope you understand what I mean.

**Comment by rajinder-yadav** [comment]
@CherryDT discovered it can be disabled by adding the following to your user settings (CTRL+P, type 'user setting):

```
    // Enables parameter hints
    "editor.parameterHints": false
```

**Comment by CherryDT** [comment]
Yes but this disables it completely. I like the hints, but they are a little bit too persistent when trying to help me. I don't need them to show up for every comma a type _within_ the parameter (e.g. inside the object in above's example).

**Comment by joaomoreno** [comment]
If the popup is useless for you, you can disable it as @rajinder-yadav mentioned.

If you have a beef with the contents of it, reach out to the proper extension. In this case, it's TypeScript. You can file an issue in our repo with specific cases in which the parameter hints contents are bothering you. cc @mjbvz 

If someone eats up <kbd>Escape</kbd>, reach out to that extension. Or configure another keybinding to close parameter hints. The command is `closeParameterHints`.

**Comment by rajinder-yadav** [comment]
Not sure why this was closed without being address? The popup still needs to appear below the cursor like this. Please make the correction.

![image](https://cloud.githubusercontent.com/assets/439226/25493719/2c56637a-2b45-11e7-9f82-f3cc9c434789.png)
****

**Comment by CherryDT** [comment]
@rajinder-yadav as you just showed yourself, _below_ the cursor there is already the autocomplete dropdown, so the parameter hints can't be shown there. Remember that both the autocomplete dropdown and the parameter hints can be open at the same time (imagine typing `myFunction(myObject.` - at this point you would see a parameter hint for `myFunction` and an autoComplete dropdown for `myObject`'s properties).

**Comment by rajinder-yadav** [comment]
OK then it makes sense to keep thing as they are, I didn't realize that could occur! Thanks.

**Comment by shiki** [comment]
My experience is vscodevim seems to be eating the ESC key. But doing Shift+ESC seems to work as an alternative.
