### ISSUE TITLE
Feature Suggestion: Ctrl+d for duplicate files on explorer view

### ISSUE THREAD

**Issue by Matheus-de-Souza** [Microsoft/vscode#25563]
- VSCode Version: 1.11.11
- OS Version: Windows 10

I would like to have a command for duplicate files in the explorer view. It's a common task on another programs like Unity3D.

**Comment by alexandrudima** [comment]
@Matheus-de-Souza would `ctrl+c` and `ctrl+v` work ?

**Comment by Matheus-de-Souza** [comment]
@alexandrudima Yeah, I can duplicate in this way. But, I still need to press f2 to rename the file. It could be quicker if you only needed to press ctrl+d to duplicate the file and start to rename it. But, as I wrote in the title, it's only a suggestion.

**Comment by luissquall** [comment]
It might belong to a different request but it would be awesome if the option to duplicate a file were included in the Command Palette, as in Sublime & Atom.

**Comment by PedroC88** [comment]
I've working on this feature since last night as I wanted the same functionality. I got stuck so perhaps someone here can guide me in the right direction.I added a new option to allow the user to right click on a tab and press a new Duplicate button. This button should:

1. Create a new tab (editor)
2. Set the same language to the new editor as the one right clicked
3. Copy all text from the selected editor into the new one

At the moment I was able to create the entry in the context menu and I have access to the current editor by receiving @IEditorGroupService which implements IEditorGroupService, but I don't know how to do any of the three items above, so I have two specific questions:

1. How do I create a new editor from an EditorAction class?
2. How do I copy information from one editor to another (more specifically the language and all text)?

P.S. Don't know if I'm bad at looking for a developers guide but I haven't been able to find any reference document where I can learn about the language and architecture of VSCode. Is there such a document describing the best practices, design patterns, application tiers, main classes, even something as simple as the language this is written on?

**Comment by PedroC88** [comment]
I managed to create a new untitled editor with the following line:

> var newEditorTask = this.editorService.openEditor({ options: { pinned: true } } as IUntitledResourceInput);

so that takes care of item number 1 (unless there's a better approach), so I'm now wondering how to set the language and text on the new Editor.

P.S. `editorService` is an implementation of `IWorkbenchEditorService`.

**Comment by PedroC88** [comment]
I now managed to duplicate the content of the file by finding the `ICodeEditor` contained within the `@IWorkbenchEditorService.getActiveEditor()`. I still need to duplicate the language.

P.S. Again, if anybody is reading this and you have the knowledge of any reference guide that would be greatly appreciated. I know I'm getting this to work but I have no clue if I'm doing it _the recommended way_ as I have never worked with VSCode source de before, not even typescript...

**Comment by PedroC88** [comment]
The functionality has been created with a minor difference, instead of `Ctrld+D` it's `Ctrl+K`,`Ctrl+U`. Pull Request [35184](https://github.com/Microsoft/vscode/pull/35184) is now pending a merge into master.

**Comment by PedroC88** [comment]
Hello @Matheus-de-Souza, I recently added a pull request linked to this ticket but it appears that I may have misunderstood your feature-request. My pull request #35184 allows you to duplicate the current file within VSCode without saving it to disk. It will only create a new tab and copy the content, language and cursor position of the active tab.

It was pointed out to me that your request may be different, that your request is about duplicating physical files in the disk and not about duplicating the active tab. **Can you please confirm whether my solution relates to your request or not?**

**Comment by PedroC88** [comment]
Noted, thanks. Sorry to have gotten your hopes high on this. I was asked to develop a separate extension instead of trying to modify vscode, if I do it I'll try to include your request as well.
