### ISSUE TITLE
Indent markdown headings in Go to Symbols menu

### ISSUE THREAD

**Issue by kvaleev** [Microsoft/vscode#25574]
It'll be very useful for markdown file navigation, if _Go to Symbol_ menu shows headings list with indentation that depends on heading level, as in Sulblime Text.

Current behaviour:

![image](https://cloud.githubusercontent.com/assets/3600063/25503197/176bc060-2ba2-11e7-91e9-e2f55a291e1d.png)

Desired behaviour:

![image](https://cloud.githubusercontent.com/assets/3600063/25503229/37e725f0-2ba2-11e7-8fff-099d4c4c5403.png)

**Comment by mjbvz** [comment]
This should be in the 1.13 insiders builds once those startup again. I decided to use `#` instead of whitespace for the indentation because this allows you to filter the headings by level:
![screen shot 2017-05-02 at 2 12 33 pm](https://cloud.githubusercontent.com/assets/12821956/25639626/693a7bfa-2f41-11e7-819c-a0168b843174.png)
![screen shot 2017-05-02 at 2 13 12 pm](https://cloud.githubusercontent.com/assets/12821956/25639641/7eb7ba74-2f41-11e7-90b4-9e6aba3fbdc2.png)

**Comment by C1DY** [comment]
ERROR . NO MAIL OUT HAKER MAY LIFE NO MORE . LOW C.I.A
Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

De: Matt Bierner<mailto:notifications@github.com>
Enviado: martes, 2 de mayo de 2017 18:14
Para: Microsoft/vscode<mailto:vscode@noreply.github.com>
CC: Subscribed<mailto:subscribed@noreply.github.com>
Asunto: Re: [Microsoft/vscode] Indent markdown headings in Go to Symbols menu (#25574)


This should be in the 1.13 insiders builds once those startup again. I decided to use # instead of whitespace for the indentation because this allows you to filter the headings by level:
[screen shot 2017-05-02 at 2 12 33 pm]<https://cloud.githubusercontent.com/assets/12821956/25639626/693a7bfa-2f41-11e7-819c-a0168b843174.png>
[screen shot 2017-05-02 at 2 13 12 pm]<https://cloud.githubusercontent.com/assets/12821956/25639641/7eb7ba74-2f41-11e7-90b4-9e6aba3fbdc2.png>
