### ISSUE TITLE
save file then file tab not stop flash

### ISSUE THREAD

**Issue by maozhenhua2** [Microsoft/vscode#25592]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|vs-code-css-comments|ashhitch|1.0.2|
|vscodeEditorConfig|chrisdias|0.1.7|
|jquerysnippets|donjayamanne|0.0.1|
|vscode-html-css|ecmel|0.0.34|
|vscode-npm-script|eg2|0.1.8|
|beautify|HookyQR|1.0.2|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.3|
|code-beautifier|michelemelluso|1.7.2|
|PowerShell|ms-vscode|0.12.1|
|debugger-for-chrome|msjsdiag|2.7.2|
|vscode-icons|robertohuertasm|7.5.1|
|sass-indented|robinbentley|1.3.1|
|JavaScriptSnippets|xabikos|1.4.0|;

---

Steps to Reproduce:

1.Click(not double-click) the file in the left Explorer
2.Edit the file on the right(Not necessary)
3.Save the file on the right
4:file tab not stop flash

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.
