### ISSUE TITLE
Allowing to step over before loading a call stack and variables

### ISSUE THREAD

**Issue by wcscmp** [Microsoft/vscode#25605]
Old issue was closed so I'm opening a new one.
https://github.com/Microsoft/vscode/issues/22807

Loading call stack and fetching local variables can be a long operations especially when there are a lot of threads started and call stacks are pretty long. Some debuggers (gdb for a example) allows you to do a step over before loading call stack or fetching local variables. Please allow debugger plugin to configure if it's ok to allow to step over before loading call stack and fetching variables.

**Comment by isidorn** [comment]
Well call stack has to be known in order for the step to be "done", since the call stack deteremines the step location.
While the variables are fetched asynchrounisly. Namely, you should be able to step while the slow variables request is being completed (shown in the variables tree as a loading spinning icon)

**Comment by wcscmp** [comment]
In order to know current location only the current frame is required. There is no need to know the whole call stack and most definitely there is no need to know call stacks of all the threads.

**Comment by isidorn** [comment]
@wcscmp agree.

**Comment by isidorn** [comment]
After discussing with @weinand there is already a mechanism in the debug adapter protocol that the vscode only requests for 1 stack frame, after that is recieved it can request all the other stack frames.

An alternative approach would be that the stopped event has the top stack frame in the event, so vscode only requests the rest

Assigning to May to investigate

**Comment by weinand** [comment]
@dbaeumer we plan to improve stepping performance in this milestone.

**Comment by isidorn** [comment]
@wcscmp thanks for this great suggestion.

Now on each stop event we are only fetching the top stack frame, once that is done in the background with a delay we continue fetching the rest of the stack frames and the variables. If a new stop event occurrend we simply cancel the previous schedule of stackFrames fetching and variables - which in practice results that if a user quickly steps over his code we will only fetch variables and rest of the stack frame once he is idle.

@delmyers @gregg-miskelly @MSLaguana @DanTup @devoncarew @WebFreak001 @roblourens @andysterland @hbenl @lukaszunity @svaarala @ramya-rao-a @vadimcn @felixfbecker @daviwil @rkeithhill @DonJayamanne @MSLaguana @rebornix In order to benefit from this performance improvement debug adapters needs to support the [`startFrame`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/common/debugProtocol.d.ts#L622) and [`levels`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/common/debugProtocol.d.ts#L624) arguments in the `StackTraceRequest`.

Here's a performance comparision before and after the improvment:

![before](https://cloud.githubusercontent.com/assets/1926584/25997057/af6fc64e-371a-11e7-9526-14a7a1a306ae.gif)
![after](https://cloud.githubusercontent.com/assets/1926584/25997059/b2f50b6c-371a-11e7-8e70-9375b9c314cb.gif)
