### ISSUE TITLE
Support to attach to an electron spawned node process using the picker

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#25618]
Currently you cannot attach to an electron spawned node process like the TypeScript server using the picker, that is using a launch config like:
```json
        {
            "type": "node",
            "request": "attach",
            "name": "Attach to process",
            "processId": "${command:PickProcess}",
            "port": 5859,
            "protocol": "legacy"

        }
```

**Comment by auchenberg** [comment]
Is this because the new process isn't exposed over the HTTP debug interface? This Node issue could be related: https://github.com/nodejs/node/issues/9435

**Comment by weinand** [comment]
@auchenberg previous versions of Electron did not support the SIGUSR1 approach of bringing node into debug mode (even if it was not launched with a `--debug` or `--inspect` flag).

**Comment by weinand** [comment]
There is still no support for SIGUSR1 in the node version (v7.9) that is built into our version of Electron.

**Comment by weinand** [comment]
With the new vscode-processes extension and the option to start all processes in inspect mode, this feature is now in reach.

**Comment by weinand** [comment]
@RMacfarlane Since you now own the VS Code process viewer (#41045) I took the liberty to assign this feature request to you.

**Comment by connor4312** [comment]
For a while js-debug has been able to debug ext host child processes by setting `attachToChildProcesses: true` in the launch config. I think that covers this scenario at least from a user POV. I haven't seen feature requests otherwise for how to debug electron node processes, and as this hasn't had any other community input, I will close as unplanned for the moment.
