### ISSUE TITLE
[theming] when completing color keys in settings, fill in current value

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#25633]
That would be very helpful 👍

**Comment by hediet** [comment]
Is this hard to implement? Otherwise, I'd love to help here.

**Comment by aeschli** [comment]
The completions are schema driven. The schema is generated here: https://github.com/microsoft/vscode/blob/aeschli/terminalDecorationIcons/src/vs/platform/theme/common/colorRegistry.ts#L127
Instead of ff0000, the color value from `IThemeService.getColorTheme().getColor(id) needs to be put in.
`onDidChangeSchema` needs be triggered whenever the colorTheme changes (IThemeService.onDidColorThemeChange)
I guess the challenge is how to get the IThemeService to the colorRegistry.
