### ISSUE TITLE
Feature request: Remember UI state for search panel

### ISSUE THREAD

**Issue by atombender** [Microsoft/vscode#25651]
Whenever I open VSCode or I open a new window, and I do a search, I have to:

* Click the little arrow to make sure the "replace" field is shown
* Enable regular expressions
* Click the little arrow to make sure the file include/exclude fields are shown

These settings together are my "default" settings that I rely on all the time. It's annoying when they're not all available, so I want every search panel to always be set up like this. But these settings don't seem to persist:

* Across restarts
* In new windows
* Across existing windows (so if I change the setting in one window, other windows aren't affected)

I use all three features quite a lot, and hiding them behind little arrows and buttons isn't so great, especially since there's no keyboard shortcut to do any of them without some awkward tab-navigation. But it would be okay if these settings were simply remembered across windows and restarts.

It's a bit nonsensical that the settings are per-window, too. If I have several projects open and search in project A, there's no reason that when I go to project B that I wouldn't want these settings remembered.

---

As an aside, some of the lack of UX elegance here could be improved simply by, for example:

* Making regular expressions the default; pretty much every other search tool out there (grep, ack, ag, ripgrep, etc.) default to regexps, so why not VSCode?
* Always showing the replace field. Sublime and Atom do this, simply because replacing is a very, very common operation.
* Always showing the include/exclude box, but move them to the bottom of the view so they don't clutter the UI.
* Hiding the "files excluded through settings" field, which is arguably only useful when you have issues with the exclusions and could even be moved into the tooltip for the exclude button, since it's purely information and not editable.

Some visual clutter could also be reduced by removing the counts. Do we really need to know that the search hit "6 results in 3 files"?

**Comment by ITSecMedia** [comment]
I would suggest to also add / show a list with all the latest search & replace actions below the search popup window, so that we can easily pick & repeat the latest search and replace actions.

If you are regularly use a few complex regex search & replaces it starts to get annoying a little.
I'm used to have such a functionality from EmEditor and it's a real help.

Perhaps with a button next to each stored ( logged action ) to delete selected or permanently save as a preset.

**Comment by roblourens** [comment]
We do persist these across restarts.

I disagree that they should be persisted globally rather than per window. For me at least, they are usually a function of what I'm working on right now, not what my general preferences are, so I don't want options I set for one task to show up in every window.

> Making regular expressions the default

I think this makes more sense for a text editor vs CLI tool.

> Always showing the replace field

I think we just need the space

> Always showing the include/exclude box, but move them to the bottom of the view so they don't clutter the UI.

I think they should be next to other query options

> Hiding the "files excluded through settings" field

Done some time ago 😁 

> Some visual clutter could also be reduced by removing the counts

I do think it's useful 🤷‍♂️ 

---

> I would suggest to also add / show a list with all the latest search & replace actions below the search popup window

You can use the arrow keys to navigate history in each of the fields.
