### ISSUE TITLE
Is it possible to run multiple commands with Shift+Ctrl+B?

### ISSUE THREAD

**Issue by morhaham** [Microsoft/vscode#25677]
I've  followed the instructions but only the first command responds.

**Comment by dbaeumer** [comment]
With the old output runner you can only execute one command with Shift+Ctrl+B. With the new terminal runner you execute multiple commands with Ctrl+Shift+B by either marking multiple command as build commands or by compsing commands using the dependsOn property (see https://code.visualstudio.com/updates/v1_10#_task-support).

I am closing this issue since it is addressed with the new task runner. The new task runner will become the default in one of the next releases. Currently users need to opt in using the version property in the tasks.json `"version": "2.0.0"`
