### ISSUE TITLE
command palette sort order weirdness

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#25682]
- VSCode Version: insiders 1.12.0-insider, commit 0bec11
- OS Version: Windows and MacOS

Steps to Reproduce:

1. Install Docker extension `ext install vscode-docker`
2. Open Command Palette, type in `>docker`
3. Result: Notice the sort order is not alphabetic, but by # of characters 

![image](https://cloud.githubusercontent.com/assets/1487073/25559406/1b422d58-2cee-11e7-93c9-13351da2360d.png)

**Comment by bpasero** [comment]
@chrisdias I recently pushed a change to move shorter matches to the top by sorting by command length. This helps in cases like the following:

**Old (search for 'install')**
<img width="758" alt="screen shot 2017-04-30 at 20 02 08" src="https://cloud.githubusercontent.com/assets/900690/25566760/50516f8e-2de0-11e7-822c-b980446281b9.png">

**New (search for 'install')**
<img width="742" alt="screen shot 2017-04-30 at 20 02 17" src="https://cloud.githubusercontent.com/assets/900690/25566761/5a37a3c4-2de0-11e7-9ab6-0912634b48e1.png">

**Old (search for 'theme')**
<img width="745" alt="old" src="https://cloud.githubusercontent.com/assets/900690/25566765/7244fc8c-2de0-11e7-9bea-f114a859884f.png">

**New (search for 'theme')**
<img width="748" alt="new" src="https://cloud.githubusercontent.com/assets/900690/25566766/775c346a-2de0-11e7-9f13-88f61b0935d7.png">

I can think of a tweak here that if you are actually searching for the category of a command (as in your case 'docker'), we sort commands by name again to provide a better overview.

Since you set this to April, is there a specific scenario that is blocked with my change (I assume this is issue impacts your /build talk?).

**Comment by chrisdias** [comment]
Not necessary for //build, just wanted to ensure there wasn't a bigger issue here.  Changed milestone to May.

I'm not sure why shorter matches should be at the top of the list, are we improving search results by doing this?  Otherwise, it just looks odd.

**Comment by eamodio** [comment]
At least for extensions -- now that there is a `commandPalette` menu -- shouldn't they be ordered by the order they are in the `package.json` like other menus? Maybe even support "groups" on the palette like other menus (doesn't have to be a visual group, but more an ordering set) -- like you can do with the `group` parameter with other menus today.

**Comment by bpasero** [comment]
Makes sense, given the controversy I reverted my change for 1.12.
