### ISSUE TITLE
inherit default behaviour for custom language extension

### ISSUE THREAD

**Issue by MhMadHamster** [Microsoft/vscode#25795]
I asked on stackoverflow before, but since i didnt recieve an answer i would really appreciate any feedback about this issue from devs, so the question is:
If I'm making a language extension for postcss, is there a way to enable CSS intellisense for this language?
And the same goes for default colorbox in css/less/sass files, is there a way to inherit this type of behaviour for colors and rules, or maybe some workaround would be nice as well.

Thank you, for any type of feedback.

**Comment by aeschli** [comment]
The cheap way is to just use the CSS language extension for your PostCSS files, but this will fail if you use syntax that is not standard CSS. If you use syntax that is not standard CSS, the right way is to create a new language extension that fully understands the added syntax in order to provide language supports like validation, code completion.. 
[Our docs](https://code.visualstudio.com/docs/extensionAPI/language-support) give you an introduction on language support.
Ideally you would structure your extension the same way the [css language extension](https://github.com/Microsoft/vscode/tree/master/extensions/css) does: It runs a separate process ('the language server') where it does all the parsing and processing.
The css language server is a node app implemented the [server](https://github.com/Microsoft/vscode/tree/master/extensions/css/server) folder but all the smartness is done in a node module called [css-language-service] (https://github.com/Microsoft/vscode-css-languageservice). The VSCode css extension is in [client](https://github.com/Microsoft/vscode/tree/master/extensions/css/client). 
The [vscode-languageserver-node](https://github.com/Microsoft/vscode-languageserver-node) library makes it easy to create such a language server, and you can look at reusing the [css-language-service] (https://github.com/Microsoft/vscode-css-languageservice) in your language server as well. It supports CSS/LESS and SCSS files and you could try to massage it inputs and outputs. Or use it as a starting point for a fork.
Now, I don't know much about PostCSS and what features you use and want to support.

**Comment by MhMadHamster** [comment]
Thanks a lot for such a complete answer!
