### ISSUE TITLE
GIT Quick Open Command

### ISSUE THREAD

**Issue by Rainville14** [Microsoft/vscode#25825]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T07:56:42.517Z)
- OS Version: Darwin x64 16.5.0
- Extensions: none
---

Steps to Reproduce:

1. On Mac, either click the branch in lower left or press Command+P
2. Type git + [space]

I am not seeing any options to checkout or create a branch. In the documentation it says that I should be able to do so through the quick open.

**Comment by kieferrm** [comment]
@Rainville14 <kbd>Cmd+Shift+P</kbd> opens the command palette. If you type `git` you get 
<img width="617" alt="screen shot 2017-05-03 at 3 48 22 pm" src="https://cloud.githubusercontent.com/assets/4674940/25684790/2d45af34-3018-11e7-8e90-08b47b5ec264.png">

`Checkout to...` is what you're looking for.  

When you use <kbd>Cmd+P</kbd> you need to type `>` first in order to get to the command palette.
