### ISSUE TITLE
Sidebar is not clickable after changing Date & Time

### ISSUE THREAD

**Issue by caixw** [Microsoft/vscode#25830]
- VSCode Version:
   1.11.2
- OS Version:
   macOS 10.12.4
Steps to Reproduce:

1. 将系统时间往前调
2. 侧边栏部分选项卡用鼠标点击没反应，但可以用快捷键进行切换。

@rebornix

**Comment by caixw** [comment]
刚把时间往后调了，然后回到正常时间，也出此问题。

**Comment by rebornix** [comment]
@caixw 请问可以提供 gif 帮助 troubleshoot 吗？

**Comment by caixw** [comment]
![vsc](https://cloud.githubusercontent.com/assets/1853047/25777749/5f78a994-3319-11e7-814b-652d7cc9c508.gif)

**Comment by rebornix** [comment]
@caixw thanks for the gif, it helps a lot. I can reproduce this with latest Insider on macOS.

**Comment by rebornix** [comment]
The triggering code is https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/parts/activitybar/activitybarActions.ts#L86 . We check current time (which is already modified) against cached last-click-time, but due to the current time is not real current, the validation is not as expected.

It's a good catch and really interesting. But it's pretty rare and once you reload the window, the issue is gone.

**Comment by bpasero** [comment]
PR welcome.
