### ISSUE TITLE
Updating from 1.9.1 to 1.11.2

### ISSUE THREAD

**Issue by Xeoneid** [Microsoft/vscode#25836]
Following this: [@code reply](https://twitter.com/code/status/859554783228604416)

- VSCode Version: 1.11.2 / 1.9.1
- OS Version: Windows 7 x64 [6.1.7600]

Steps to Reproduce:

1. Install the following extensions:

- **IntelliSense for CSS class names**
- **file-icons**
- **gitignore**
- **Debugger for Chrome**

2. Update from VSCode 1.9.1 directly to 1.11.2 via the notification on the top.

3. [Bugs I noticed]: 

- **file-icons** not only become disabled but they vanish and must be reinstalled.
- **IntelliSense for CSS class names** doesn't recommend any class after typing _class="_.
- **gitignore** doesn't add any path to the gitignore file.

**Comment by kieferrm** [comment]
Thanks the information. Those extensions should clearly not be broken since there were no breaking API changes between 1.9 and 1.11.  Since we can't test individual extensions, it would be best to work with the extension authors to identify whether we broken them and have them file issues if we have. Thanks a ton!
