### ISSUE TITLE
JS Syntax highlighting gets confused with `catch`

### ISSUE THREAD

**Issue by NickHeiner** [Microsoft/vscode#25859]
- VSCode Version: 6eaebe3b9c70406d67c97779468c324a7a95db0e
- OS Version: macOS Sierra 16E195

The following code snippet does not look correct:

![image](https://cloud.githubusercontent.com/assets/829827/25683455/348cf39e-302a-11e7-9b36-be34642e6c48.png)

(Is there a different repo that this issue would be more appropriate for?)

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#448

**Comment by C1DY** [comment]
ERROR   NO MAIL NO QUIINCY LARSON BAD PEOPLE

Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

De: Matt Bierner<mailto:notifications@github.com>
Enviado: miércoles, 3 de mayo de 2017 19:09
Para: Microsoft/vscode<mailto:vscode@noreply.github.com>
CC: Subscribed<mailto:subscribed@noreply.github.com>
Asunto: Re: [Microsoft/vscode] JS Syntax highlighting gets confused with `catch` (#25859)


This issue was moved to Microsoft/TypeScript-TmLanguage#448<https://github.com/Microsoft/TypeScript-TmLanguage/issues/448>
