### ISSUE TITLE
JSDoc: pasting text should automatically add * in front of each line

### ISSUE THREAD

**Issue by warpdesign** [Microsoft/vscode#25894]
- VSCode Version: 1.12.0-Insider
- OS Version: Windows 10 Creators update

Steps to Reproduce:

1. Type `/**` followed by enter: this creates a JSDoc comment block
2. Typing `enter` will then add `*` in front of each line

However, pasting some text won't automatically add `*` in front of each line that was pasted into a jsdoc block.

![vscodejsdoc](https://cloud.githubusercontent.com/assets/199648/25704670/b559d3b0-30da-11e7-9753-174ab260371d.gif)

**Comment by alexandrudima** [comment]
To keep the number of issues in our inbox at a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: we look at the number of votes the issue has received and the number of duplicate issues filed. Thank you for your time and understanding.

If you disagree and feel that this issue is crucial: we're happy to listen and to reconsider.
