### ISSUE TITLE
Open Editors section breaks slow double-clicking a file

### ISSUE THREAD

**Issue by willfaught** [Microsoft/vscode#25911]
If you click an unopened file, its name is added to the Open Editors section. This moves the file tree below down by one row.

If you are slightly slow to make the second click in a double-click mouse input, the clicked file will be added to the Open Editors section, the file tree will move down by one row, and your second click will land on the file tree item above what you meant to click on, which just displays that item instead.

- VSCode Version: 1.11.2 (1.11.2)
- OS Version: MacOS 10.12.4 (16E195)

**Comment by isidorn** [comment]
That's just life.
We actually already introduced a delay here to make the double click scenario work. We could not make the very slow double-click scenario work since then the ux refresh in the usual case feels slow.

Ideas on how to fix this are welcome
Code pointer https://github.com/Microsoft/vscode/blob/release/1.12/src/vs/workbench/parts/files/browser/views/openEditorsView.ts#L39

**Comment by willfaught** [comment]
Why not move the top of the tree view down, and leave the content at the same scroll position such that the tree is in the same position relative to the mouse pointer?
