### ISSUE TITLE
How I can rename my theme extension

### ISSUE THREAD

**Issue by Binaryify** [Microsoft/vscode#25988]
Hey, I am the  'OneDark-Pro' theme author, I rename this theme from 'Material Theme' to 'OneDark-Pro' recently.
![image](https://cloud.githubusercontent.com/assets/12221718/25735680/93f503be-319f-11e7-9c8f-bd8a3626f9b9.png)

 I change the 'package.json' info
![image](https://cloud.githubusercontent.com/assets/12221718/25735688/9751d596-319f-11e7-9c6f-e61889225871.png)

However, if I change the 'name', it will publish with a new theme and lose the downloads, if I don't change the 'name', the market site will show "ext install Material-theme"
![image](https://cloud.githubusercontent.com/assets/12221718/25735710/bb5a330c-319f-11e7-9137-ec3a9dd61f54.png)

What should I do now?

**Comment by seanmcbreen** [comment]
Hi sorry I just saw this 


The ID for an extension is `publishername.extensionname` all meta data hangs off this e.g. downloads, ratings.  This is also used for install/updates.

In this case I actually think most users would expect this to be a new extension i.e. it's pretty different from Material.  

So I think publishing with a new ID would make the most sense - otherwise users will get updated and not understand that this is actually a different theme.

We don't have support for renaming today - so choosing a new name is typically something people only do in the display name or again they are forced to re-publish :(

Sean
