### ISSUE TITLE
Terminal: Wide characters in linkified text are being duplicated

### ISSUE THREAD

**Issue by OriginCode** [Microsoft/vscode#26038]
- VSCode Version: 1.13.0-Insider
- OS Version: openSUSE Tumbleweed
- Shell: zsh (used 'oh-my-zsh' themes) 
* If I started a terminal in the VScode 1.13.0 Insider, it will show two paths (there are some Chinese words in the path).But when I use the bash, there's no more problems:(

**Comment by Tyriar** [comment]
Upstream issue: https://github.com/sourcelair/xterm.js/issues/642

**Comment by Tyriar** [comment]
More details in duplicate https://github.com/Microsoft/vscode/issues/24743

**Comment by Tyriar** [comment]
For the issue with zsh it appears to be caused by the large blue diamond character 🔷.

Minimal test case:

```
echo '🔷~/'
```

**Comment by Tyriar** [comment]
Since local path stuff is in VS Code, minimal test case upstream is:

```
echo '🔷http://a.com'
```

**Comment by Tyriar** [comment]
Looks like this was caused by the character width wrapping in v1.13, same fix as with CJK chars.

**Comment by Tyriar** [comment]
Upstream PR out: https://github.com/sourcelair/xterm.js/pull/688

**Comment by Tyriar** [comment]
Pushed fix to master and release/1.13

**Comment by Tyriar** [comment]
Since I've pushed this to release/1.13, here is a quick illustration of the impact:

A unicode character preceeding a link (eg. `🔷http://a.com`) will duplicate the link's text. Any change to the terminal will also make the text jump back and forth between it's proper state and the duplicated state:

<img width="278" alt="screen shot 2017-06-09 at 12 21 25 pm" src="https://user-images.githubusercontent.com/2193314/26991177-46f39230-4d0e-11e7-8ce7-607e028ebb9a.png">

Impacts CJK/unicode chars within paths too:

<img width="245" alt="screen shot 2017-06-09 at 12 23 28 pm" src="https://user-images.githubusercontent.com/2193314/26991247-801a0972-4d0e-11e7-921e-1aa3dbed7551.png">

tmux splits getting screwed up:

<img width="378" alt="screen shot 2017-06-09 at 12 20 21 pm" src="https://user-images.githubusercontent.com/2193314/26991286-a2be5f3c-4d0e-11e7-94be-b6dd8bf92e4a.png">

**Comment by ksnyde** [comment]
is there any work-around until master is released?

**Comment by Tyriar** [comment]
The workaround is to change your prompt to not use the special unicode character(s), like the > char in powerlines or the `<` char in https://github.com/Microsoft/vscode/issues/28304#issue-234739000

The recovery build should be released towards the end of the week.

**Comment by aeschli** [comment]
Verified in 1.13.1 (Ubuntu 14.04 and Fedora 32bit)

**Comment by g5codyswartz** [comment]
Glad it's not just me, I was about to lose my mind and haven't had time to dig in on this until today
awesome video of the text jumping with every key (even cursoring): https://screencast.com/t/kWzY2j2AcgZa

**Comment by Tyriar** [comment]
@g5codyswartz good to hear :smile:
