### ISSUE TITLE
typescript.tsdk doesn't work as workspace setting

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#26046]
- VSCode Version: Code 1.12.0 (72672be0b7d3eef0784077b880615f91b7ec85aa, 2017-05-04T16:10:14.237Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|quokka-vscode|WallabyJs|1.0.32|
|vscode-eslint|dbaeumer|1.2.8|
|tslint|eg2|0.12.0|
|Go|lukehoban|0.6.61|
|debugger-for-chrome|msjsdiag|3.1.1|
|vetur|octref|0.6.4|
|java|redhat|0.3.0|
|vscode-icons|robertohuertasm|7.6.0|
|sass-indented|robinbentley|1.4.1|
|language-stylus|sysoev|1.6.0|
|vim|vscodevim|0.7.0|;

---

![image](https://cloud.githubusercontent.com/assets/4033249/25750788/ccd58d58-3180-11e7-9aeb-12ff7539b7b2.png)

However, if I put that same setting in "User Setting", this popup wouldn't show.

@mjbvz

**Comment by mjbvz** [comment]
For security reasons, workspace versions of typescript are not automatically loaded, you have to explicitly select it either by running `Select TypeScript Version` or by opening a TS file and clicking on the TypeScript version number in the status bar. The status bar also displays the version of ts the is currently active

See  https://code.visualstudio.com/docs/languages/typescript#_using-newer-typescript-versions for more info

Let me know if that does not resolve the issue

**Comment by octref** [comment]
Thanks it works fine now.

**Comment by brianjorden** [comment]
Unfortunately, I don't think this "solves" the original issue that was raised. The selection of that option within the GUI actually adds that config line to the `.vscode/settings.json` file, but obviously that setting isn't actually used anymore. It seems as though specifying the usage of a local version of Typescript, or ANY way to flag/indicate the precise version to be used by the engine and by the IDE should be part of either the `tsconfig.json` or the `package.json` files. Considering that you can lock in the engine version, shouldn't the IDE portion follow (or at least allow) following the same version? I've moved my codebase up to v2.6.1 but VSCode continues to try and use v2.5.3 when someone clones it.

**Comment by mjbvz** [comment]
@brianjorden As I already noted, this is done for security reasons. We cannot just start executing arbitrary node code that someone included in a workspace you cloned. That's why the extra step of selecting the active TS version is required when you first open a workspace. Setting `typescript.tsdk` in your workspace give users a hint that they should switch the active  TS version but we cannot switch for them

**Comment by drewwyatt** [comment]
@mjbvz Is it possible in future version for VSCode to at least default to the version specified in the package.json file, while still letting the user specify a specific version? I get that we can't just execute some arbitrary node code, but is there *some way* we could specify the TS version the repo maintainers expect your IDE to be running?

**Comment by mjbvz** [comment]
No. As it stand we cannot ever default to executing the typescript version from the workspace . The TypeScript server's node code is unsigned and we have no way to verify that TypeScript in the workspace has not been tampered with, even if the maintainer claims it is safe. 

#19567 tracks support for trusted TS versions which would enable this

**Comment by drewwyatt** [comment]
@mjbvz makes sense. Glad to see that there *might* be a path forward at some point.

**Comment by qm3ster** [comment]
I don't see why this can't be an editor option.
You are likely to execute the version in the workspace eventually.
I am sure not everyone has this (valid) concern.

**Comment by brianjorden** [comment]
I understand there is a security concern, but the build process may need to be locked down to a certain version of TS. Without even going to the local node_modules could there perhaps be a way to just indicate what TS version that particular workspace should target? I don't think most care about using the version from within node_modules, but instead just want to explicitly say what version the build process and/or IDE should be using.

So instead of VS Code only having ONE version of TS available, maybe it could pull in the alternate "official" version a specific workspace is calling for? Just really feels like `tsconfig.json` should have some way to indicate the targeted version and that the VSCode IDE and/or TS engine should at least throw large warnings that they don't match. I spent a good deal of time trying to sort out an error in VSCode that ran through the TS engine (2.6.1) perfectly fine because I had just cloned the repo and didn't realize that `.vscode/settings.json` file does not work as indicated in the linked articles above from the official TS documentation. The fact the GUI adds that line to the settings when you click that option made me think that is how it was configured along with the online documentation saying the same thing.

My point being, with so much constant fluctuation on libraries, build tools, and the million different versions, NPM/Yarn and other tools have given facilities to lock in exact version numbers. Today many do that very manually with TS through the local node_modules copy of Typescript. I have projects that simply won't compile in one version vs another so I specifically can't use the global version in all cases.

**Comment by qm3ster** [comment]
Please correct me if I am wrong:

If I clone a repo where `node_modules` is in `.gitignore` and view it with vscode, there will be no local typescript to resolve to.

If I clone a repo where `node_modules` is in `.gitignore` and then run `npm install` or `yarn` the commands in `preinstall` `install` `postinstall` strings of `package.json` will be executed, before I even have a chance to open vscode.

Where is the real-life case when vscode is the sole reason an execution occurs? When someone cloned someone else's malicious node_modules?

In that case, what if they contain malicious `eslint` and `prettier`, among others, so the relevant vscode extensions call those? Should all extensions be discouraged from using project-local tools, a staple of modern node ecosystem?

**Comment by mjbvz** [comment]
@qm3ster We want to prevent the case where just opening a folder in VS Code could compromise your system. Consider this scenario:

1. Evildoer creates evil github repo (under the guise of providing a helpful example when providing repo steps for an issue or something)
2. This evil git repo contains a custom `typescript.tsdk` setting. This points to a super evil node script. This script does not have to be in node_modules 
3. Evildoer then tricks a developer into cloning their evil repo and opening it in vs code

If VS Code were to use the `typescript.tsdk` setting from the workspace without asking for user confirmation, it would start the super evil node script automatically. Think of it: all the user did was open a folder and now their poor computer is being torn to bits by digital Cenobites! Obviously we cannot allow that to happen.

In general, extensions should never automatically execute arbitrary code in the workspace. That being said, when dealing with node, VS Code itself is probably the least of your concerns

**Comment by brianjorden** [comment]
I would also like to point out that this evening I've had to re-select the Typescript version in the same workspace 3 times after some new module additions/reboots/restarts of VSCode/etc.

**Comment by qm3ster** [comment]
Oh, I see. Thank you for the explanation.
Perhaps a "trusted workspace" concept should be created. It can be persisted outside the workspace or require confirmation on every open. These other extensions can start to respect this setting as well, if it's easy enough for them.
