### ISSUE TITLE
VSCode does not respect window layout during debugging [Windows]

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode#2612]
Browser snapped to left hand side, VSCode snapped to right hand side with breakpoints set. start debugging. Click something on webpage to hit a breakpoint, VSCode undocks from right-hand side and have to re-snap it to get back to original window layout.

**Comment by isidorn** [comment]
@bpasero I looked into this and it is happening due to https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/electron-browser/window.ts#L180

So the show() does not respect the window layout. If I change the show() to focus() all works nicely, but I see your comment so I guess you used it as a workaround. If you want to keep this behaviour, I will just flashFrame() instead of focus on win/linux on debug stop event.

**Comment by bpasero** [comment]
@isidorn I remember I had a bug for it, but in another scenario and I could not repro on master. Do you repro on master?

**Comment by isidorn** [comment]
@bpasero I repro on master, on windows with the above explained scenario
