### ISSUE TITLE
Multiple files with edits (not saved) - "Dont Save" saves all files

### ISSUE THREAD

**Issue by JacobGunther12** [Microsoft/vscode#26138]
- VSCode Version: 1.12.1
- OS Version: MacOS Sierra 10.12.4

Steps to Reproduce:

1. Open two files and make edits to both
2. Click the "X" on the list of open files
3. Click "Dont Save" - It saves all files even after clicking "Dont Save"

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.
