### ISSUE TITLE
Markdown formatting does not highlight block code

### ISSUE THREAD

**Issue by neilbalch** [Microsoft/vscode#26164]
- VSCode Version: 1.12.1
- OS Version: Windows 10 Home Build: 14393.1066

When making code with the ` `` ` tag (is that the right term?) in files with a .md extension, the editor color highlights the code orange/brown, but when using the block code tag ` ``` ``` `, the editor does not highlight the code. Could this be fixed so that in both situations the code is highlighted?

Thanks, Neil

**Comment by praenubilus** [comment]
I found the same question, it used to be working correct for ``` ```

**Comment by mjbvz** [comment]
Can you please share markdown source that demonstrates the problem and a screenshot of the issue

**Comment by neilbalch** [comment]
[HERE])https://github.com/neilbalch/Python-Tutorial-Calculator/blob/master/Advanced%20Calculator%20Tutorial.md) and I cannot post a screenshot on GitHub. There are multiple examples in the code snippet that exhibit the issue.

**Comment by mjbvz** [comment]
Thanks. This is by-design. Your example shows a fenced code block without any language identifier. In order to get sytax highlighting, it should be

~~~md
```py
def askForNumInput(textPrompt):
    num = input(textPrompt)
    try:
        # Try to typecast the input to a float
        float(num)
    except ValueError:
        # Catch the exception if it is not a number
        print("ERROR: Syn: Invalid Num")
    else:
        # Typecasting
        return float(num)
```
~~~

<img width="725" alt="screen shot 2017-05-08 at 11 49 09 am" src="https://cloud.githubusercontent.com/assets/12821956/25819929/61f01c5e-33e4-11e7-9831-9a03e4a2d2c9.png">

Code without a language is shown as white by most of our default themes, but any theme can customize the colorization of `markup.fenced_code.block.markdown` syntax elements
