### ISSUE TITLE
Feature Request - locale settings in menu or settings?

### ISSUE THREAD

**Issue by iamCristYe** [Microsoft/vscode#26173]
Currently locale can only be changed via editing the locale json file, which is hard to find out for beginners. Is there any plan to merge that into the main json settings file or put that into the menu(like view->language)?

**Comment by egamma** [comment]
There already is the `Configure Language` Command in the command palette and there is documentation on how to configure the language. Since this is a rare command we decided to not include in the menus directly.

![image](https://cloud.githubusercontent.com/assets/172399/25794290/8dfb1fce-33d0-11e7-9c3b-1bf2dd7d2f3f.png)
