### ISSUE TITLE
IntelliSense window got a lot more narrow with docs to the side

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#26217]
This is quite a bad user experience imho because I am typically not paying too much attention to the docs but rather the suggestion in IntelliSense. With todays build I am seeing quite a bit of horizontal space taken away to the documentation:

![image](https://cloud.githubusercontent.com/assets/900690/25810951/ed8b2cea-3411-11e7-8539-69a92e2feb16.png)

Maybe make this configurable at least? Or provide an explicit gesture to bring up docs when needed?

/cc @joaomoreno

**Comment by ramya-rao-a** [comment]
The idea is to have the docs show up all the time. Whether we will have a setting to not have the docs show up all the time is a call we will be taking based on the feedback in the next few weeks.

Meanwhile you have an excellent point that the list width is way too small.
With https://github.com/Microsoft/vscode/pull/26250, the list and the docs will occupy equal width

/Users/ramyar/Desktop/Screen Shot 2017-05-08 at 7.04.34 PM.png

And when there is not enough space to show them side by side, docs will drop to the bottom

/Users/ramyar/Desktop/Screen Shot 2017-05-08 at 7.05.10 PM.png

**Comment by ramya-rao-a** [comment]
@bpasero 

The list width in stable is about 438px. With the docs in the side, I reduced it to 330px so that the suggest widget doesn't end up occupying too much space.

Even if we increase the width to accommodate `workbench.editor.enablePreviewFromQuickOpen`, there is no guarantee that there will not be another item longer than  `workbench.editor.enablePreviewFromQuickOpen`

I feel 330px is a good sweet spot. Thoughts?

On another note, #26282 is tracking the need for a setting to control the auto-expansion

**Comment by ramya-rao-a** [comment]
@bpasero 

With #26783,

- Docs expand only after user chooses to do so either by `Ctrl+Space` or by clicking on the "Read More" icon (as before)
- Once docs expand, they remain expanded until user chooses to close it either by `Ctrl+Space` or by clicking on the "Read less" icon

Therefore with the docs not expanded, widget occupies same width as today.

With the docs expanded, the list part reduces its width by 100px so that the whole widget doesn't occupy way too much space.

This still doesn't solve the problem for completion items with very long labels in the expanded docs view.

There isn't a good solution for this. There is nothing stopping people from adding very long labels.

thoughts?

**Comment by bpasero** [comment]
I think that is a good compromise 👍 .

Btw the transition from no-docs to showing docs could be smoother I think there is an animation in the way that is probably not needed (video is not showing it very good, you gotta give it a try):

![panel-red](https://cloud.githubusercontent.com/assets/900690/26187193/5aecd978-3b97-11e7-89be-26854f817cc2.gif)

**Comment by ramya-rao-a** [comment]
Do you see it only when it is the case of docs on the left or you see it even when docs are on the right (say in the first editor group)?

**Comment by ramya-rao-a** [comment]
Should be better now with https://github.com/Microsoft/vscode/commit/452ddbf4b13d840a6768289c21d92b3882d33c7e

**Comment by ramya-rao-a** [comment]
Lets use #26887 to discuss any further animations
