### ISSUE TITLE
Docs sometimes appearing on left which make it quite confusing

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#26292]
My eye muscle memory gets all confused when I see docs on the right. I believe they should not change position as that is very confusing for the user

![screen shot 2017-05-09 at 12 28 02](https://cloud.githubusercontent.com/assets/1926584/25846675/ffcd5d00-34b2-11e7-8bf6-99235b31a281.png)

**Comment by ramya-rao-a** [comment]
This is done so that the suggest list is closest to the cursor position.

Right now, the decision to swap is taken when there is not enough space on the right of the cursor to fit the docs. 

<img width="678" alt="screen shot 2017-05-09 at 7 20 15 am" src="https://cloud.githubusercontent.com/assets/16890566/25855452/0f4356ac-3488-11e7-94e8-02fe320a2974.png">

If this is not done, then the list is away from the cursor

<img width="689" alt="screen shot 2017-05-09 at 7 19 47 am" src="https://cloud.githubusercontent.com/assets/16890566/25855433/076e23da-3488-11e7-8ce9-9d7c695c9815.png">

Would you prefer the latter?

cc @Microsoft/vscode

**Comment by isidorn** [comment]
I think the latter is worse without a question but this issue in general shows the flaw in the design imho. Not sure how to solve it though

**Comment by ramya-rao-a** [comment]
One way is to drop it to the bottom if there is not enough space on the right.

Since this only happens when you are on the right most editor group + not enough space on the right, we can hope it is not a majority scenario?

**Comment by isidorn** [comment]
I think this will happen all the time to people using at least two editor groups. It happened to me today 10+ times. 
As for the number of people using two editor groups I think we can easily get those numbers in telemetry but there should be quite a few of them.

Dropping to the bottom might help but why don't we just hide it when there is not enough space to show it? Just a simple idea since showing docs is not critical and should be done only when we feel we can do it in a good way imho

**Comment by michelkaporin** [comment]
I would prefer to drop it below as this is the expected not-enough-width flow to me. 

Hiding it totally is like introducing specific functionality which is not always understandable for the end-user. As a user I would expect the same semantics under all conditions (and don't care whether there is a space or not to fit these docs, as untuitively I would be searching for them if they appear when there is a space).

**Comment by chrmarti** [comment]
Without having seen the 'below' option, I think it is more intuitive to show the docs at the same vertical position because it is more natural to move the eyes horizontally rather than vertically.

**Comment by jrieken** [comment]
Option 2 in https://github.com/Microsoft/vscode/issues/26292#issuecomment-300180897 seems bizarre, because I expect suggestions to show next to the cursor as close as possible, not the doc popup

**Comment by Tyriar** [comment]
@ramya-rao-a and I had a chat about this yesterday. I was thinking the ideal behavior is to basically keep the intellisense dropdown where it is in stable, just fit the docs popup on the right if there's room, otherwise on the left. The main requirement we cannot shift on imo is that the dropdown should *always* be attached to the cursor.

Putting it on the bottom is pretty confusing imo.

> Since this only happens when you are on the right most editor group + not enough space on the right, we can hope it is not a majority scenario?

It also happens if you're working on a long line of code in a single editor, what "long" means here depends on the monitor's resolution and dpi as well as `window.zoomLevel`.

**Comment by ramya-rao-a** [comment]
With #26783,

- Docs expand only after user chooses to do so either by `Ctrl+Space` or by clicking on the "Read More" icon (as before)
- Once docs expand, they remain expanded until user chooses to close it either by `Ctrl+Space` or by clicking on the "Read less" icon
