### ISSUE TITLE
Welcome Page should assist user configuring VS Code

### ISSUE THREAD

**Issue by shanalikhan** [Microsoft/vscode#26300]
There should be interactive welcome page when user start the code first time. It should ask user some basic questions:

1. Which Language does he work with, with a multiple languages options.
2. Does he use code in multiple machines and want to sync them.

Upon his selections, Code should **suggest** the extensions like Python , Project Manager, My Code Settings Sync or other extensions inside the welcome page **along with the current featured extensions**

**Comment by egamma** [comment]
// @chrmarti fyi

**Comment by chrmarti** [comment]
The Quick Links already offer a few configuration options, like keymaps, color theme, settings. We might extend that further. We have so far avoided the multi-step at-first-startup configuration guide and focused on these single-step at-any-time buttons because we think that offers a more flexible experience.

**Comment by shanalikhan** [comment]
If single-step is important then

What can be done is, make a scroll bar with the configuration options sections ONLY in quick links and add new box for languages , when user click check box, box can be vertically expand with languages to choose or sync options etc.

When user select these options, the welcome page can then expand below with the featured or suggested extension upon user selection.
