### ISSUE TITLE
VS Dark + (default) theme not picked up

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#2632]
@aeschli not sure if this is intentional, but the new default theme is not being used if you update from 0.10.6 to 0.10.7 because the theme has a different name ('vs-dark' compared to 'vs-dark vscode-theme-colorful-defaults-themes-dark_plus-tmTheme')

**Comment by aeschli** [comment]
In 0.10.6 the default was the Dark theme that looks like the 0.10.7 Dark (Visual Studio).
So for existing workspaces there's no change happening regaring to colors, except that the theme name has been updated.
I think that's the expected behavior. We don't want to automatically add more colors again.

**Comment by bpasero** [comment]
:+1:

**Comment by egamma** [comment]
@aeschli please check the release notes whether this is clearly explained in there.
