### ISSUE TITLE
Error: Command with Adding Initial Configurations

### ISSUE THREAD

**Issue by WardenGnaw** [Microsoft/vscode#26335]
There is an error dialog that pops up when adding configurations created via a command through the debug window. Trying to mimic this with the C++ extension: https://github.com/Microsoft/vscode-node-debug/blob/c31d0935a28df4b4b0c85b41a9da6ad7b30e2b5b/package.json#L128

After clicking on Add Configuration and then selecting the type on this dropdown. 
![image](https://cloud.githubusercontent.com/assets/3953714/25873739/7ae1c31c-34c4-11e7-9c46-1c1353e78ce6.png)

Then this error appears.

![initialconfigerror](https://cloud.githubusercontent.com/assets/3953714/25873650/370c1f3e-34c4-11e7-9764-86216a85d37f.png)

This can be resolved, specifically for our case, if you select a .c or .cpp file, before adding configurations.

Here is the stacktrace of the error:
![image](https://cloud.githubusercontent.com/assets/3953714/25874761/dec9508a-34c8-11e7-9a07-5d1a43f95a2b.png)

- VSCode Version: 1.12.1
- OS Version: Windows 10 

Please email me if you want a vsix to repro. 

@pieandcakes

**Comment by egamma** [comment]
The issue is that the cpp extension is not activated when the command is called. This is a bug in the cpp extension. The cpp debug extension must declare the corresponding activation events in the package.json as is done here in the node-debug adapter: https://github.com/Microsoft/vscode-node-debug/blob/c31d0935a28df4b4b0c85b41a9da6ad7b30e2b5b/package.json#L74
