### ISSUE TITLE
Custom Emmet snippet for Javascript

### ISSUE THREAD

**Issue by ratishphilip** [Microsoft/vscode#26422]
VSCode Version: 1.12.1
OS Version: Windows 10 Insider Build 16188.1000

Steps to Reproduce:

1. Create a **snippets.json** file with the following content
```
{
    "js" : {
        "abbreviations" : {
            "fnrr" : "function (req, res) {\n${cursor}\n}",
            "fnrrn": "function (req, res, next) {\n${cursor}\n}"
        }
    }
}
```
2. Save this file to a local directory, say **D:\DevSettings**
3. Now in the VSCode User settings add the following key-value
```
"emmet.extensionsPath": "D:\\DevSettings\\snippets.json"
```
4. Reload VS Code and open a javascript file.
5. Type **fnrr** and press TAB.

Expected Result: **fnrr** should be replaced with 
```
function (req, res) {

}
```
Actual Result: **Nothing happens!**

**Comment by ramya-rao-a** [comment]
- Firstly, javascript is not one of the languages directly supported by the emmet library. To bring emmet expansion features in a javascript file (and other non supported languages by emmet), we introduced the feature where you can map any language to one of the supported languages. For example: 
```json
"emmet.syntaxProfiles": { 
    "javascript": "html"
}
```
The above would then enable all html snippets and abbreviations to be used in a javascript file. So that is step 1 to have emmet in a non supported language

- Second, in your snippets.json file you are using `js` which is not recognizable by emmet. You need to use a supported language there. In your case, you need to replace `js` there with say `html` if you mapped `javascript` to `html` in `emmet.syntaxProfiles`

- Third, Looking at your example, I strongly recommend you use VS Code's user snippet feature. See https://code.visualstudio.com/docs/editor/userdefinedsnippets#_creating-your-own-snippets. The `emmet.extensionsPath` is best used when you want to override the default emmet abbreviations

**Comment by ratishphilip** [comment]
@ramya-rao-a Thanks a lot for the detailed explanation. That clarifies a lot.

**Comment by ratishphilip** [comment]
@ramya-rao-a 
I tried using the VSCode's user snippet feature. I added the following snippet to javascript.json file

```
"function(err, req, res)": {
	"prefix": "fnerr",
	"body": "function (err, req, res) {\n\t$0\n}"
}
```

But now when I type **fnerr** the snippet appears at the bottom of the Intellisense list like this
![emmet](https://cloud.githubusercontent.com/assets/7021835/25962950/7b012f56-3634-11e7-908f-1fa2053a4a2c.png)

This makes it very cumbersome having to type the snippet shortcut and scrolling all the way down.

Is there any way to enable the snippets to comeup first in the list?

**Comment by ratishphilip** [comment]
Oh I found it out
"editor.snippetSuggestions": "top",

fixes it.

**Comment by ramya-rao-a** [comment]
@ratishphilip great, Happy Coding!

**Comment by ccalvarez** [comment]
Hi.  

I've followed the same steps to reproduce as described above:

- I saved the **snippets.json** file to the local directory **D:\DevSettings**

- I've added the following settings to the VSCode user settings file:

```
"emmet.syntaxProfiles": {
        "javascript": "html"
     },
     "emmet.extensionsPath": "D:\\DevSettings\\snippets.json",
     "editor.snippetSuggestions": "top"
```

No matter the folder where I place the **snippets.json** file, VSCode keeps returning the message:

_"The path set in emmet.extensionsPath "D:\DevSettings\snippets.json" does not exist."_

![image](https://user-images.githubusercontent.com/2665104/26955163-51035798-4c72-11e7-8197-e1f214a3d46c.png)


Thank you!

<br>
OS Version:  Windows 10 Pro, Version 1607, Build 14393.1198

VSCode Version:

![image](https://user-images.githubusercontent.com/2665104/26955393-aaf232d2-4c73-11e7-83e9-d479cfa1da62.png)

**Comment by ramya-rao-a** [comment]
@ccalvarez You only need to set the folder path not the file path


So use `D:\\DevSettings` and restart the VS Code window, it should work

**Comment by ccalvarez** [comment]
@ramya-rao-a Thank you very much.  Now it works.  I'll also have in mind your recommendation to use VS Code's user snippet feature instead when it comes to snippets.

Thanks a lot!

**Comment by ramya-rao-a** [comment]
@ccalvarez Yes, as much as possible use the user snippets.

emmet snippets to be used if you want to override an existing emmet snippet.

**Comment by ramya-rao-a** [comment]
From VS Code 1.15 onwards, please use `emmet.includeLanguages` instead of `emmet.syntaxProfiles` to get Emmet abbreviation expansion features in your language of choice. And use languageIds on both sides of the mapping.

We are making this move because of the confusion around what `emmet.syntaxProfiles` setting was originally meant for i.e [Customizing final output](https://docs.emmet.io/customization/syntax-profiles/) and what it became i.e enabling emmet in new languages.

Please read more on this at [Emmet 2.0](https://code.visualstudio.com/blogs/2017/08/07/emmet-2.0)
