### ISSUE TITLE
Hard hang while editing regular expression

### ISSUE THREAD

**Issue by darrenkenny** [Microsoft/vscode#26434]
- VSCode Version: 1.13.0-insider 2017-05-09...
- OS Version: Windows 8.1

Steps to Reproduce:

1. Edit a file with text in it
2. Open find, enable regular expressions, and enter: ^(.*)+

The editor will now hard-hang, there is no timeout failure, I had to reload when got the prompt to do so.

While I know that the above expression is nonsense - it just happened to be something I entered after deleting a couple of characters before the +. 

It shouldn't cause a hard-hang like this - at worst it should timeout itself, not wait for the electron to handle it at the application level.

**Comment by alexandrudima** [comment]
@darrenkenny The regex `^(.*)+` doesn't hang for me
![26434](https://cloud.githubusercontent.com/assets/5047891/25942970/9afa03aa-363e-11e7-81e7-fb8896e50f7f.gif)

Perhaps there is something special about the file that is being searched that might trigger a catastrophic backtracking of sorts ?

**Comment by darrenkenny** [comment]
[sweetpmac-running-tracks.txt](https://github.com/Microsoft/vscode/files/992593/sweetpmac-running-tracks.txt)

I attached a file that is triggering it for me, but it looks like I was slightly wrong with the RE, it is actually (minus the quotes):

    "^(.*)+ "

i.e. the same, but with a space at the end - as soon as I press space after the +, it hangs.

**Comment by alexandrudima** [comment]
@darrenkenny 

Thank you for the clarifications. Unfortunately, I still cannot reproduce. I've tried running out of master and with the latest insiders build from 11.05

![26434-again](https://cloud.githubusercontent.com/assets/5047891/25944481/c9321974-3643-11e7-82be-686522a39daf.gif)

When investigating such things, I sometimes use https://regex101.com/ which is quite good in finding out if a regex leads to catastrophic backtracking, which is a problem we suffer from. However, it appears this particular regex is not one of those...

**Comment by darrenkenny** [comment]
OK, so trying again, I again missed something, after you press space, press it again, and then it will hang, so attempt to enter:

    "^(.*)+  "

(two spaces)

I've just verified that I get this on both Linux and Windows running the same build as you now (after updating).

Thanks for your patience.

**Comment by alexandrudima** [comment]
Thanks for getting back to me. It is indeed a case of catastrophic backtracking

https://regex101.com/r/TPwgHp/1

![image](https://cloud.githubusercontent.com/assets/5047891/25946410/474efffa-364b-11e7-9cf1-9fcc5577ea98.png)

http://www.regular-expressions.info/catastrophic.html

Unfortunately, there is nothing we can do at this time on our side. When evaluating a regexp for the find widget, we rely on JavaScript's [RegExp](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp). The implementation comes from v8 and it has no mechanism for us to ask it to abort in case of catastrophic backtracking.

The easiest repro is to run the following in Chrome Developer Tools or nodejs:
```
/^(.*)+  /.exec('Born To Run – Bruce Springsteen');
```

Since all users of v8 (including Chrome and nodejs) are impacted by this, please feel free to create an issue at https://bugs.chromium.org/p/v8/issues/list , but usually I've seen regular expressions leading to catastrophic backtracking being categorized as a user error.

I will close for now since there is no possible code change I can do on our side, short of implementing regular expression matching ourselves, which is something I wouldn't want to do :)

**Comment by darrenkenny** [comment]
While I do understand what you're saying, that this is something that exists upstream - it doesn't seem to cause Chrome on that web-page to hang - which suggests that it should be possible to at least avoid that part of the problem?

Is there no way to do the evaluation of the RE in a way that would not hang the main UI thread? Which is really where the issue seems to be here?

**Comment by alexandrudima** [comment]
We could create a thread using a native C++ node module. In the separate thread we could create a new JavaScript VM. Then we could send over to that thread all the buffer and evaluate the regex in that thread. And then we'd do this on each keypress in the find input to keep feature parity with the current implementation. If the thread is unresponsive we'd know we've run into this case.

Alternatively, we could look for a different C++ regex library and integrate it via a native C++ node module.  We could then call into that module (on the same thread) and check if the regex leads to catastrophic backtracking (given the different C++ regex library supports catching such cases).

IMHO these are great and interesting things to do and given unlimited resources I'd do it. It is however a lot of work to cover these rare cases where we end up running into a regex that leads to catastrophic backtracking. 

If there is one bright side to this, it is that it helps us write better regular expressions :).

We can keep the issue open if you feel strongly about it, but I will not take any action to address it.

Also, Chrome does most definitely suffer from this issue. Look how the page is unresponsive after evaluating, i.e. no clicks are registered:
![26434-again2](https://cloud.githubusercontent.com/assets/5047891/25954080/7d5c7770-3665-11e7-9e0a-d3c3de015f8a.gif)
