### ISSUE TITLE
Implement a watch-dog mechanism which can kill runaway extension host processes

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#26445]
In certain circumstances, e.g. extension that does `while (true)` loop, the extension host process will not terminate unless killed via task manager.

Implement a watch-dog mechanism that can kill runaway extension host processes.

NB: This was not an issue on Windows until we made the process be forked with the `detached`  option to allow 5s for the extensions to gracefully shut down.

**Comment by alexandrudima** [comment]
An idea would be to:
 * write a nodejs native addon
 * it installs an interval timer on the JS event loop
 * at each execution of the timer, a call is made to C++ land to let it know the JS event loop is alive
 * create a thread that sleeps for ~20s
 * when the thread wakes up, it checks the last time the JS event loop was alive

API: http://docs.libuv.org/en/v1.x/threading.html

**Comment by dbaeumer** [comment]
Cool idea. Will avoid having yet another process running.

**Comment by sjelfull** [comment]
Can this also detect how much % CPU the process is using, give a notification which process is long-running, and give the user the option of restarting/killing it? That way you would also expose potentially problematic extensions?

**Comment by alexandrudima** [comment]
Well, we'd want the JS stack trace, not the C++ one (otherwise we'd just see v8 being in the stack). 

That appears to be *difficult* from the discussion in https://github.com/nodejs/node-v0.x-archive/issues/25263

**Comment by alexandrudima** [comment]
Due to instability (increased number of crashes), the watch-dog code is now disabled -- starting with today's Insiders Build (2017-08-23). We have also upgraded to Electron 1.7.4 and 1.7.5 and we should be cautious of introducing too much instability at once.

**Comment by markeissler** [comment]
Re-iterating thoughts expressed by @sjelfull . I've been suffering from high cpu on an rMBP and can't figure out which extension is causing this. 

This is overly tough to diagnose: whenever I launch developer tools, it seems the problem goes away...literally, I launch the tools and the fans start to calm down, eventually turning off completely. Makes no sense. Because I have no idea what's causing it, I can't try to repro. The problem just seems to randomly appear.

Having some sort of automated way to identify problematic extensions would be extremely helpful, perhaps more so than just quietly killing them.

**Comment by alexandrudima** [comment]
This has been implemented now on master.

**Comment by bpasero** [comment]
Adding verification needed, but this probably needs some test plan input and testing across OS (cc @mjbvz).

**Comment by bpasero** [comment]
I created https://github.com/Microsoft/vscode/issues/59303
