### ISSUE TITLE
Missing wordHighlightForeground

### ISSUE THREAD

**Issue by jchannon** [Microsoft/vscode#26474]
- VSCode Version: 1.12.1
- OS Version: OSX 10.11.6

Steps to Reproduce:

1. In my case, open a *.cs (csharp) file
2. Place cursor on word that is repeated
3. I think tmTheme sets a value for this, in my case I'm not sure its implemented, hard to tell what keys to change if possible. Open settings and set `wordHighlightBackground` to white for example.  My default font colour is white so now it doesn't show up, is there a way to select wordHighlightForeground, I don't see this option available

**Comment by aeschli** [comment]
We don't currently allow to selections and highlights to set the text foreground colors.
It's because of an architectural choice in the editor implementation: The implementation keeps selections and highlights in a separate layer than the text in order to avoid relayouting text on selection changes.

As this is unlikely going to be changed soon, I'm closing the issue as won't fix.
You have to pick selection colors that go well with the token colors.
