### ISSUE TITLE
Add setting to turn off the debugger peek UI

### ISSUE THREAD

**Issue by todddcls** [Microsoft/vscode#26480]
Steps to Reproduce:

1. Run VSC debugger (I'm using it for nodejs)
2. Hit an unhandled exception that stops the debugger in some deep call stack.

Result:
Gigantic red call stack that is getting in the way of seeing the offending code.  It doesn't really hide the code, but it's a real nuisance.  I need to see the code not the callstack for a second time (I can already see the callstack on the left).

**Comment by coder-mike** [comment]
I am having the problem described in #29097, which I find makes it virtually impossible to debug callstacks within large files. And of course the first thing I then tried to do was see if there is a way to disable the exception peek widget, so that the call stack becomes usable again. This is one scenario where this feature would have been useful.

**Comment by isidorn** [comment]
@coder-mike thanks. I will first look into #29097 in september and if that for some reason can not be fixed I can look into adding an option to disable this.

**Comment by isidorn** [comment]
https://github.com/Microsoft/vscode/issues/29097 is fixed, thus closing this
