### ISSUE TITLE
Incorrect encoding when using DEBUG(node.js inside vscode), it will affect extensions result. 

### ISSUE THREAD

**Issue by TonySFU** [Microsoft/vscode#26502]
- VSCode Version: 1.12.1
- OS Version: macOS 10.12.4

Steps to Reproduce:

1.Use system node.js will get the correct result.
<img width="404" alt="screen shot 2017-05-11 at 7 27 10 pm" src="https://cloud.githubusercontent.com/assets/22601843/25979938/5e466fd8-3680-11e7-8287-6d7eda8de31d.png">

2.Set up a DEBUG(launch.json) and run the same code, will return the incorrect encoding result.
<img width="539" alt="screen shot 2017-05-11 at 7 27 46 pm" src="https://cloud.githubusercontent.com/assets/22601843/25979984/a8b080cc-3680-11e7-936a-c62184e0b396.png">

This problem only happens on macOS platform, it works correct on Windows 10.

I found this issue few months ago, still can not fix.
[https://github.com/goessner/mdmath/issues/13](url)

**Comment by weinand** [comment]
'clipboardy' uses the macOS command line tools "pbcopy" and "pbpaste" to access the clipboard. From their online documentation I see that they rely on an environment variable for dealing with encodings.

From "man pbcopy":
> pbcopy  and pbpaste use locale environment variables to determine the encoding to be used for input and output. For example, absent other locale settings, setting the environment variable LANG=en_US.UTF-8 will cause  pbcopy and  pbpaste to use UTF-8 for input and output.  If an encoding cannot be determined from the locale, the standard C encoding will be used.  Use of UTF-8 is recommended.  Note that by default the Terminal application uses the UTF-8 encoding and automatically sets the appropriate locale environment variable.

I've experimented a bit with this and found that pbcopy relies on "LC_CTYPE". If VS Code is launched by double clicking or from the Dock, "LC_CTYPE" is undefined. If VS Code is launched from the command line, it inherits "LC_CTYPE" which always exists in terminals. 

Since VS Code is not a terminal, I don't think that we have a reason to initialise "LC_CTYPE" automatically.

If you have to use "clipboardy", you'll have to make sure that it always gets the environment it needs.  Either do this in your code by setting "LC_CTYPE" to "UTF-8" or set the "LC_CTYPE" in your launch config.
