### ISSUE TITLE
Implement word wrapping for non monospace fonts

### ISSUE THREAD

**Issue by paul-go** [microsoft/vscode#2654]
It's wrapping at the wrong place. I'm assuming the line measurement is happening based on character counts rather than the sum of the character widths? This doesn't work so well for us proportional font coders ;-)

**Comment by alexandrudima** [comment]
Indeed, we wrap based on the width of `n` and on the width of a double width character (think CJK). Then, the wrapping code only differentiates between latin and double width characters.

**Comment by mikemaccana** [comment]
Same here. Quick example:

![image](https://user-images.githubusercontent.com/172594/38983689-dc1e368a-43bc-11e8-9799-2d4cc0096524.png)

**Comment by paul-go** [comment]
@alexandrudima Realistically speaking, is there any chance of this ever getting looked at? Or is the refactoring that this would incur just not worth the cost?

Shameless evangelism: Proportional font coding is amazing. Can't understand why more people don't do this. Code is far more readable. Can fit 2x the amount of code on the screen at once. Helps you catch typos easier. And makes my code look so beautiful :)

**Comment by zspitz** [comment]
@paul-go I've found that using a proportional font lets me focus on the entire keyword/identifier while reading. A monospace font tends to emphasize the individual letter, This is good for APL, but for any language which uses longer keywords/identifiers -- not so much.

**Comment by alexandrudima** [comment]
@matsieftw color decorators are not taken into account when computing wrapping points (#32856)

**Comment by matsieftw** [comment]
What does that even mean? My lines wrap fine, VSCode still makes the file super wide so it still has a horizontal scroll. As I asked in my original ticket. I’d like to be able to disable horizontal scrolling since word wrapping and limiting the number of columns does not appear to be an effective way to disable the horizontal scroll bar.

**Comment by alexandrudima** [comment]
@matsieftw The computation of the wrapping points (where to break a line) occurs in the view model. The view model is currently unaware of the color decorations (the rectangles with color that are inserted in the line); those color rectangles are inserted after the fact in the view, after the wrapping points have been computed. This is tracked in #32856:

<img width="1164" alt="screen shot 2018-10-10 at 13 01 49" src="https://user-images.githubusercontent.com/5047891/46732075-c8bb3580-cc8c-11e8-85d6-65829a71c965.png">

**Comment by zspitz** [comment]
@alexandrudima 

This is what I'm seeing (when editing Markdown):
![image](https://user-images.githubusercontent.com/312166/46732587-8860b500-cc96-11e8-81ef-0a54c9259e38.png)
AFAICT this has nothing to do with color decorations.

**Comment by matsieftw** [comment]
My file doesn’t have any color decorators. I don’t understand why that’s relevant. I made a ticket because despite having proper word wrapping my files are still super wide and have horizontal scroll. I want to be able to disable the horizontal scroll. The fact that I can scroll entirely past all my text to long blank sections of my lines is annoying.

**Comment by alexandrudima** [comment]
@zspitz Yes, you are using a non-monospace font and this is a known issue tracked in this issue. Thank you for the screenshot, but really not needed at this point.

@matsieftw I've reopened your issue #59054. Let's continue investigating your precise unique problem there.

**Comment by rmorabia** [comment]
> @alexandrudima Realistically speaking, is there any chance of this ever getting looked at? Or is the refactoring that this would incur just not worth the cost?

Echoing this here. Is this being worked on at all? Any information about where it is on the priority list?

**Comment by y-spreen** [comment]
I don't think it's an issue with non-monospace fonts only. I use operator mono and usually wrapping works. But sometimes, when typing a line that is wrapped while typing, the wrapping breaks.

From that point on the horizontal scrollbar is always visible, and the last characters that are typed in a long line always mess up the scrolling.

you type normally, the line is completely visible and scrolled all the way to the left  
-> you extend the current line until it should be wrapped  
-> the last 1-2 characters go too far. The editor has to scroll to the right to show them  
-> the word finally wraps  
-> since the cursor is at the end of the word, it does not have to scroll all the way to the left
-> your editor remains scrolled 1-2 characters to the right.  
-> The first 1-2 characters of the document are not visible anymore


This issue is really bothering me, I hope this gets seen
![image](https://user-images.githubusercontent.com/12631527/61590997-cb09d300-abc0-11e9-8acb-634d6865e9f4.png)
image of the broken scrollbar. Once it breaks you can really scroll way too far

![image](https://user-images.githubusercontent.com/12631527/61591007-f4c2fa00-abc0-11e9-8fff-e0b43aa6689e.png)
Image where you can see the end result after the steps above. The first chars are hidden.

**Comment by qaqz111** [comment]
Comment from #70627.

@alexdima Yes you are right about the width of characters like `U+2018`, and that's the point. According to the [Unicode® Standard Annex #11](http://www.unicode.org/reports/tr11) these characters are [**East Asian Ambiguous**](http://www.unicode.org/reports/tr11/#ED6), therefore **require additional information not contained in the character code to further resolve their width**.

But VSCode seems to treat them as simple [**Narrow**](http://www.unicode.org/reports/tr11/#ED5) characters and give them halfwidth characters' width regardless the font used and therefore the horizontal scrollbar appears in word wrap mode.

![Wrap](https://user-images.githubusercontent.com/3367034/72389823-38f41900-3764-11ea-80c7-790efcfbb0ec.png)

To reproduce this issue:
> 1. Use a chinese or japanese font as first value of **Editor: Font Family** in preference which give these Ambiguous character wide width(e.g. Simsun in a Simplified Chinese Windows)
> 2. Input some text in VSCode editor like `ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890`
> 3. Toggle Word Wrap in VSCode through command or `Alt+Z`
> 4. Copy one or all of these characters `‘’“”` and paste to line begin repeatly, and you'll see the horizontal scrollbar appears
> 5. Press `Alt+Z` repeatly and pay attention to the horizontal scrollbar you can see the issue

The point is, these characters `‘’“”` in most East Asia context (e.g. chinese) they are always wide width as fullwidth characters, but VSCode can not process them correctly.

**Comment by alexdima** [comment]
To try out, you can use `"editor.wrappingAlgorithm": "dom"`, but be warned that it is orders of magnitude slower than the default one, `"editor.wrappingAlgorithm": "monospace"`
