### ISSUE TITLE
TypeScript type definitions not working with JavaScript in TypeScript projects

### ISSUE THREAD

**Issue by TripleSnail** [Microsoft/vscode#26550]
I'm working on a project with mixed TypeScript and JavaScript. We use ThreeJS, and we use type definitions for it. The project itself is a TypeScript project.

-----
- VSCode Version: 1.12.1
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Create a tsconfig.json, add three.d.ts, and add a JS-file
2. Try typing something like `var world = THREE.Vector3`;

Excepted: VSCode doesn't complain about THREE.Vector3, and uses type definitions to provide IntelliSense.

Actual result:
VSCode complains "Cannot find name 'THREE'.", and doesn't provide IntelliSense.

-----

If I set allowJs to true in tsconfig.json, type definitions are used, but usually in exchange, I lose JavaScript type inference, and I don't want to compile my JavaScript code.

I also tried adding jsconfig.json, but it doesn't help as long as tsconfig.json is present.

I made a project that demonstrates the problem:
https://drive.google.com/open?id=0B4T6ZT_UgfRjcG5jM3QyblZPZHM

Thank you for making VSCode!

**Comment by mjbvz** [comment]
Thanks for the report and example project

I believe there is a bug where TypeScript does not pick up the `jsconfig` if a `tsconfig` is present in the same directory. I've opened https://github.com/Microsoft/TypeScript/issues/15869 to track this.

Until this is addressed, there may be a few possible workarounds:

* At the top of the js files add: `/// <reference path="three.d.ts" />`

* Use `checkJS` in your root `tsconfig` and create a separate one for compiling:

`tsconfig.json`:
```json
{
  "compilerOptions": {
    "target": "es5",
    "allowJs": true,
    "strict": false
  }
}
```

`tsconfig.build.json`
```
{
  "extends": "tsconfig.json",
  "compilerOptions": {
    "allowJs": false
  }
}
```

This second approach isn't great because it causes you to use a different config in the editor vs for compiling 

Closing as upstream

**Comment by arackaf** [comment]
A workaround that worked nicely for us is keeping the jsconfig in a different directory than tsconfig.  The baseUrl property should allow you to keep your tsconfig one level  above where your code is, with the jsconfig file right in the src directory.

**Comment by arackaf** [comment]
Sorry for all my spam.  I'm not 100% clear on the original problem, but fwiw, we were able to get back Code's intellisense in JS files with non-relative imports by including all JS files in the tsconfig file, like so

```
{
    "compilerOptions": {
        "target": "esnext",
        "baseUrl": "./src",
        "jsx": "react",
        "allowSyntheticDefaultImports": true,
        "allowUnreachableCode": true,
        "allowJs": true,
        "moduleResolution": "node",
        "module": "es2015",
        "experimentalDecorators": true,
        "lib": ["es2015", "dom"],
        "typeRoots" : ["./typings/modules", "./node_modules/@types"]
    },
    "include": [
        "./src/**/*.ts",
        "./src/**/*.tsx",
        "./src/**/*.js",
        "./src/**/*.jsx"
    ]
}
```

Hope that's of some use to somebody :)
