### ISSUE TITLE
Bug to select second of two themes with the identical names

### ISSUE THREAD

**Issue by fadeevab** [Microsoft/vscode#26554]
- VSCode Version: 1.12.1
- OS Version: Ubuntu 14.04

Steps to Reproduce:

1. Install 3rd-party "Monokai Theme" (0.0.2 currently) from extensions manager.
2. Now there are 2 "Monokai" entries in **File->Preferences->Color Theme**:
  2.1. First one is **built-in** "Monokai".
  2.2. Second one is **3rd-party** "Monokai".
3. Select second "Monokai" (see 2.2). I want to use this one, because it doesn't change workbench colors. See https://github.com/Microsoft/vscode/issues/25986 for a reference.
4. **F1-> Reload Window**.
5. VS Code chooses the **first** "Monokai" theme (see 2.1.) **always**.

![two_monokai](https://cloud.githubusercontent.com/assets/5967447/25999292/38fce20e-372d-11e7-95ee-2ba24a00d7a3.png)

I think VS Code selects Theme by name, not by identifier, and it always selects the first one.

**Comment by aeschli** [comment]
When we switched to having themes beeing configured in the settings, we wanted to avoid a non-human readable theme ids in the user settings. Instead, we opted for the label instead. As you observe that can lead to conflicts. That is not so much a problem when both themes come from an extension as once can uninstall the conflicting extension again. But for conflicts with one of the built-in theme the fix is for the 3rd-party theme to change the name.
A unique name is also beneficial to recognize an extension in the VSCode extensions view and in the marketplaces.
I created https://github.com/gerane/VSCodeThemes/issues/42
