### ISSUE TITLE
The editor freezes

### ISSUE THREAD

**Issue by haf** [Microsoft/vscode#26561]
- VSCode Version: latest
- OS Version: OS X 10.11.6

Steps to Reproduce:

1. Install ionide
2. Start a large project
3. Make a small edit, save the file

The editor freezes while it compiles. Every time.

**Comment by egamma** [comment]
Need more information to reproduce.
What is the size of your project?
Can you share the project?
>The editor freezes while it compiles. Every time.
can you pls illustrate this with an animated GIF?

**Comment by haf** [comment]
It's about 5 fsproj, w/ 7 fs files each, with 600-3000 LoC in each.

https://github.com/haf/expecto for example

How do I create a gif?

**Comment by egamma** [comment]
>How do I create a gif?

I use licecap http://www.cockos.com/licecap/

**Comment by haf** [comment]
![freeze](https://cloud.githubusercontent.com/assets/193115/26024579/601c56ec-37d4-11e7-805f-3d8c9517aa09.gif)

You see the problem right about when I'm moving the cursor up and down multiple times in BinomialHeap.fsx after starting the compiler; and then the cursor stops moving for one and a half minutes; never being possible to move again. It jumps down a bit later when I click inside the buffer, but then remains still, even when I move it up and down with arrows/hjkl.

**Comment by alexandrudima** [comment]
@haf From the gif I noticed you are using the vim extension. Does this reproduce for you when running `code --disable-extensions`. Since the vim support is running in an extension, it shares execution environment with other extensions and perhaps one of your extensions is going to 100% CPU (i.e. while true loop) ?

**Comment by alexandrudima** [comment]
Since you mention that you open a large project, I believe this might also be caused by our file watcher. Adding @bpasero who has more steps to troubleshoot.

**Comment by haf** [comment]
Without extensions it doesn't reproduce.

These are the ones I'm using:

<img width="282" alt="screen shot 2017-05-16 at 09 04 06" src="https://cloud.githubusercontent.com/assets/193115/26093541/a4b1fc8c-3a16-11e7-8d83-92c8b746c3c0.png">

**Comment by alexandrudima** [comment]
@haf Unfortunately we don't have a straight forward way to pinpoint which of the extensions you have are freezing the extension host. My only recommendation is to selectively disable extensions that appear related (i.e. the ionide ones perhaps) and do some sort of binary search to find out which one misbehaves. Then, the best would be to contact the extension author and create an issue with the extension.

**Comment by haf** [comment]
The issue here IMO is that there's no way to log or profile what is happening. How about adding logging and metrics to vscode instead? I have a motto in my own software, that if you can't debug it with the logs/metrics, then you don't have enough logs/metrics; this is exactly the problem here.

**Comment by haf** [comment]
Also, the argument could be made that a text editor that can be frozen isn't a good text editor, even if it's caused by an extension, so perhaps consider a resource monitor of sorts? Or calling extensions with a deadline/timeouts?

**Comment by alexandrudima** [comment]
I agree. We are aware of these issues and we are thinking about making improvements.

* we have ways to debug and profile the extension host but they are not shipped with the product. i.e. there is no action to run in the shipped product that will profile or debug-brk the extension host

* all extensions share a single execution environment. This means that one extension doing a `while(true)` equivalent will make the entire extension host process unresponsive and basically bring down all the other extensions with it. Please note that an unresponsive extension host does not bring down the UI process. i.e. File > Save always works fine.

* we don't proactively detect an unresponsive extension host. In this case the problem is compounded by the fact that vim is installed which basically redirects almost all keypresses to the extension host. What happens in this case is that arrow keypresses are correctly processed by the UI and sent over to the (unresponsive) extension host which doesn't do anything because it is unresponsive.

* we don't kill an unresponsive extension host / relaunch a crashed extension host.

These are all things we are aware on and will continue to work on.
