### ISSUE TITLE
Improving IntelliSense

### ISSUE THREAD

**Issue by svipben** [Microsoft/vscode#26595]
- VSCode Version: 1.12
- OS Version: Linux Ubuntu 16.04

![screenshot from 2017-05-13 14-07-43](https://cloud.githubusercontent.com/assets/10441177/26024949/cc00fdc0-37e5-11e7-97ce-82bf1741bc5d.png)

how to remove from suggestions words like `console`, `i`, `log`, etc (all who have black document/paper)? Because it's really annoying, it even include me `i` which was in for loop... I tried to use these settings:

```json
  "editor.snippetSuggestions": "none",
  "editor.wordBasedSuggestions": false,
  "editor.quickSuggestions": {
    "other": false,
    "comments": false,
    "strings": false
  }
```

But it's still the same. If there's no chance to remove them, please think about this and add it, because it really annoying and doesn't help at all.

Thanks!

**Comment by svipben** [comment]
Tested in Latest VS Code Insiders and it's also the same.

**Comment by svipben** [comment]
As far as I understand the `editor.wordBasedSuggestions` is not working?

**Comment by mjbvz** [comment]
The root cause is the TypeScript returns all unique names in a JavaScript file: https://github.com/Microsoft/TypeScript/blob/2300a99606bed7bd9a29cf2919536cd0b25bc136/src/services/completions.ts#L74

I think we should add a `javascript.nameSuggestions` setting to disable these. Adding this for May 2017

**Comment by svipben** [comment]
@mjbvz Thank you very much! :heart:
