### ISSUE TITLE
autocomplete trigger characters need to be language dependent

### ISSUE THREAD

**Issue by bmacnaughton** [Microsoft/vscode#26598]
- VSCode Version: 1.12.1
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Change to PHP mode
2. Type a "." (period) in a comment, to concatenate strings, for any reason.

I get intellisense for every variable and function that vscode knows about - it's completely worthless. I don't need to know I can enter anything with a value there. PHP is not JavaScript.

**Comment by jrieken** [comment]
@bmacnaughton It is language dependent and defined by the provider. For us it's important to know which extension you are using to get php intellisense

**Comment by bmacnaughton** [comment]
I have not installed a PHP extension; this seems to be the default behavior of vscode.

![image](https://cloud.githubusercontent.com/assets/4171707/26065224/18dbf376-3948-11e7-9b52-e3866e08df11.png)

Here's the popup I'm gettting. Maybe it's not Intellisense and I'm calling it the wrong thing.

![image](https://cloud.githubusercontent.com/assets/4171707/26065746/bb96f01a-3949-11e7-8082-ea687d122b8f.png)

**Comment by aeschli** [comment]
The current PHP intellisense is too simple. It doesn't use a parser, so it doesn't know about comments. We should the intellisense from the built-in code it and propagate a PHP extension.

**Comment by roblourens** [comment]
Yes, our built-in support is very naive. If you are doing a lot of PHP development, I recommend using the PHP Intellisense extension: https://marketplace.visualstudio.com/items?itemName=felixfbecker.php-intellisense or another one, and disabling the builtin support.

**Comment by bmacnaughton** [comment]
OK, but the issue is that  you shouldn't be displaying everything in the world on trigger characters. Can I just turn them off? I don't need to know that anything (almost) can follow the concatenation operator.

**Comment by roblourens** [comment]
You can set `"php.suggest.basic": false`. The php extension has the ability to customize trigger characters.

**Comment by bmacnaughton** [comment]
Thanks. I mostly use JavaScript but am forced to PHP from time-to-time. Just turning it off will get me there.

**Comment by smuuf** [comment]
AFAIK *(if I understand that correctly)* Felix Becker's language server **[does define](https://github.com/felixfbecker/php-language-server/blob/a4739430f82063ac0a1800a12bbe94d01fb1128f/src/LanguageServer.php#L279)** its own trigger characters - no dot there. Still, the `dot` character **annoyingly, triggers suggestions inside a PHP file**.

I don't want to disable `php.suggest.basic`, because it displays a short doc to most PHP functions. So how should I remove the "dot" from PHP's trigger characters?

Is there no item in the configuration that could resolve this? And if not - then why? 😢
