### ISSUE TITLE
Theming suggestion: Add option to add text-shadow color to highlighted text

### ISSUE THREAD

**Issue by dsifford** [Microsoft/vscode#26601]
Hi there,

I'm the maintainer of the [Dracula theme](https://marketplace.visualstudio.com/items?itemName=dracula-theme.theme-dracula) for vscode and I've been consistently hitting a singular annoyance: Highlighting light-colored text with a light color (as is the norm for dark themes) creates a really bad contrast situation.

Examples:

![image](https://cloud.githubusercontent.com/assets/5240018/26027577/4e0530f0-37de-11e7-889b-ec5a8ab8e8d4.png)

![image](https://cloud.githubusercontent.com/assets/5240018/26027589/662fd022-37de-11e7-88db-3924d2a10f76.png)

My suggestion is to add in the ability to give highlighted text a shadow color so that contrast can be greatly enhanced. Example: https://codepen.io/dsifford/pen/GmdYvL

Thanks for considering! 😄 

**Edit:** Another idea would be to automatically apply a shadow color to the text the same color as the editor background color. 👍

**Comment by aeschli** [comment]
@alexandrudima FYI.

Currently, we are not able to easily theme the foreground color (or any style of the text) for selections or highlights. It has to do with an implementation choice in the editor to manage text and selections in separate layers. That helps with performance in order to avoid relayouting on selection or highlight changes.

**Comment by aeschli** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.
If you disagree and feel that this issue is crucial: We're happy to listen and to reconsider.
Maybe you want to give it a try yourself and provide the feature through an extension or a PR: We're happy to give advise and get you started.
Thanks for your understanding. Thanks for helping and happy coding!
