### ISSUE TITLE
Strange intellisense prediction

### ISSUE THREAD

**Issue by devinrhode2** [Microsoft/vscode#26624]
Steps to Reproduce:
![vscode-chromedot-bug](https://cloud.githubusercontent.com/assets/539816/26036921/75e3a456-38ad-11e7-830b-f34f4b3f1587.jpg)

- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:18:32.269Z)
- OS Version: Darwin x64 15.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|visual-studio-light-theme|SimoneOlivieri|0.0.7|
|elm-format|abadi199|0.1.0|
|vscode-color|anseki|0.2.2|
|vscode-eslint|dbaeumer|1.2.8|
|vscode-babel-coloring|dzannotti|0.0.4|
|vsc-ember-cli|felixrieseberg|0.3.1|
|Theme-Capo-Light|gerane|0.0.3|
|ide-purescript|nwolverson|0.4.3|
|language-purescript|nwolverson|0.0.7|
|vscode-format|ryannaddy|0.0.5|
|elm|sbrink|0.8.3|
|react-beautify|taichi|0.3.0|
|html-preview-vscode|tht13|0.0.3|;

Don't think the filename would be relevant, but it was "7-considerActivating.js".

**Comment by mjbvz** [comment]
Yes, our intellisense does not know about any `chrome` global which is why you don't see it recommended. If the visible suggestions are not helpful, you can always cancel out of them using `escape` 

To get typings for chrome, try installing `@types/chrome` in you project. The easiest way is to create a `jsconfig.json` at the root of your project with the content:

```json
{
    "typeAcquisition": {
        "include": [
            "chrome"
        ]
    }
}
```

This should let VSCode know about the chrome global in javascript files

We also should not be suggesting the `RTC...` type at all in JS files. This is tracked by: https://github.com/Microsoft/TypeScript/issues/15750

Closing as designed
