### ISSUE TITLE
Use different color for 'console' output category

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#2665]
Debug adapters usually use the three OutputEvent categories like this:
- stdout: output produced by the debuggee
- stderr: error output produced by the debuggee
- console: for information produced by the debug adapter itself, e.g. how node was launched or tracing information (if enabled)

Currently 'stdout' and 'console' can not be distinguished in the debug console: they both appear in black.
I suggest to use blue for the console category (or/and an italic font if possible).

**Comment by isidorn** [comment]
:+1:

**Comment by isidorn** [comment]
Since we use our Severity class for distinguishing between output types (info, warn, error, ignore) as an easy fix I gave the console a warn category. So we show it in orange.
I also tried blue, maybe is too strong for my taste since the sidebar is orange so it drags unnecessery attention.

Anyways, please try out the orange and if you think this is wrong reopen and I will do a bigger refactoring and change to blue.
