### ISSUE TITLE
Explorer stealing space keypresses while terminal is focused

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#26673]
- VSCode Version: Code - Insiders 1.13.0-insider (bed4aad1e055eda2f5d864bbba6968ea77262b1c, 2017-05-15T06:09:48.271Z)
- OS Version: Linux x64 4.10.0-20-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.9.3|
|lorem-ipsum|Tyriar|1.0.0|
|sort-lines|Tyriar|1.2.0|
|theme-sapphire|Tyriar|0.2.1|
|vscode-svgviewer|cssho|1.4.0|
|tslint|eg2|0.15.0|
|git-project-manager|felipecaputo|1.3.2|
|md-navigate|jrieken|0.0.1|
|vscode-scss|mrmlnc|0.6.2|
|seti-icons|qinjia|0.1.3|;

---

Not sure how I got into this state, but pressing <kbd>space</kbd> while the terminal is focused (blinking cursor) is toggling the folder in explorer.

![out](https://cloud.githubusercontent.com/assets/2193314/26078507/9dade5ba-3974-11e7-8151-0e45b54acbd0.gif)

Clicking the explorer and back to the terminal fixed the issue.

@bpasero for workbench
@sandy081 for recent custom explorer changes

Will probably be difficult to repro, close off if there's not enough info for a fix.

**Comment by bpasero** [comment]
@Tyriar could well be an issue with context keys, ever since I adopted the commands for all trees, space is one of them. So if our keybinding service thinks that the explorer has focus and you press space in the terminal, it would explain why space goes there and not to you. The only way how to find out more is if we had a way to debug which context keys are active at a certain point in time. Otherwise if you have steps for this, please reopen.

**Comment by Tyriar** [comment]
If it happens again I'll try see which context keys are active :+1:
