### ISSUE TITLE
'Go to Definition' doesn't always work when using tsconfig.json paths

### ISSUE THREAD

**Issue by pflannery** [Microsoft/vscode#26703]
- VSCode Version: 1.12.1
- OS Version: Windows 10

Given a tsconfig.json with paths setup like:
```json
"baseUrl": ".",
"paths": {
  "editor/*": [
    "editor/*"
  ],
  "common/*": [
    "common/*"
  ]
}
```

Pressing F12 will not `Go to Definition` when the definition is in a file from the same folder under `editor/*`. 

```js
// editor/tools.js
export function someFunc() {}
```

```js
// editor/myEditor.js
import { someFunc } from 'editor/tools.js'; // 'Go to Definition' not working here
```

However F12 works as expected outside of the `editor/*` folder

```js
// common/utils.js
import { someFunc } from 'editor/tools.js'; // 'Go to Definition' works here
```

**Comment by pflannery** [comment]
Seeing as using relative paths is a work around I'm gonna close this. Maybe it's my understanding of the tsconfig paths that's wrong :)?

```js
// editor/myEditor.js
import { someFunc } from './tools.js'; // 'Go to Definition' is working here
```

**Comment by mjbvz** [comment]
@pflannery Since you are working in JavaScript, did you also set `allowJs` in your `tsconfig.json`? I suspect that the files may not have been included in the `tsconfig.json` project. You check if the files are part of the project by running the `JavaScript: Go to Project Configuration` command in the javascript file. This should open your `tsconfig.json` if everything is configured properly

**Comment by pflannery** [comment]
Yes I have allowJS set to true.

This is the tsconfig.json

```json
{
  "compilerOptions": {
    "target": "es2017",
    "module": "system",
    "outFile": "out/bundle.js",
    "lib": [
      "es2016"
    ],
    "sourceMap": true,
    "forceConsistentCasingInFileNames": true,
    "allowJs": true,
    "experimentalDecorators": true,
    "baseUrl": ".",
    "paths": {
      "editor/*": [
        "editor/*"
      ],
      "common/*": [
        "common/*"
      ]
    }
  },
  "files": [
    "src/header.js",
    "src/body.js"
  ],
  "exclude": [
    "out",
    "node_modules"
  ]
}
```

**Comment by mjbvz** [comment]
Since you have `files` set, only those files will be included in your project. Nothing under `editor` or `common` will be included. To fix this, you probably need to configure [`include`](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html):


```json
   "include": [
       "editor/**/*.js",
       "common/**/*.js"
    ]
```


The `JavaScript: Go to Project Configuration` command can help you determine if a js file is included in the project or not

**Comment by pflannery** [comment]
@mjbvz 
> Since you have files set, only those files will be included in your project. Nothing under editor or common will be included.

Strange that `go to def` works between `common/*` files and `editor/*` files just not within their own space.

I just tried include and that didn't work either.
