### ISSUE TITLE
Test: copy all from debug console

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#26736]
Refs: #2163

- [x] any os @weinand (macOS)
- [x] any os @aeschli

Complexity: 2

It is now possible to copy all the content from the debug console using the `Copy All` context menu action. 
* Debug some app (e.g. our smoke test), have a lot of output in the debug console (including objects which are expanded) and verify that `Copy All` action nicely copies all the content in the debug console. 
* Debug an extension, from an extension write objects and simple text using the `console.log`, make sure the `Copy All` action also nicely copies all these content

**Comment by cleidigh** [comment]
@isidorn 
cool, this relates to something I was going to post regarding both debug output and other output windows
the mainly relate to keyboard actions (disabled keyboard/voice user)

- Proposal: 
- a command to copy the current visible (not necessarily focused) output pane - would allow quick paste into editor
- a command to focus the output select dropdown 

I'm just asking here instead of polluting the issues list if this is already in the works
I would also be willing to contribute...

**Comment by isidorn** [comment]
@cleidigh please create a new issue a ping me on it. In that issue please state what would be the benefits of your proposals and why should this not be an extension - I believe the first one is covered by our API? 
Thank you
