### ISSUE TITLE
Allow multiple views to show at the same time

### ISSUE THREAD

**Issue by whatyoubendoing** [microsoft/vscode#26777]
Would be nice to be able to have both a left and right sidebar i,e file tree in left and VSC in right.

Kinda vibing off the multi panel layout of atom with github / git integration

Something like this 

![lol screen shot 2017-05-17 at 10 19 26 copy](https://cloud.githubusercontent.com/assets/896954/26130863/cd656144-3aea-11e7-8fc2-120581ec8888.png)

**Comment by leocaseiro** [comment]
I was going to open an issue for that. It would be very handy for the [Code Outline](https://marketplace.visualstudio.com/items?itemName=patrys.vscode-code-outline) extension.

**Comment by galkowskit** [comment]
Multi-sidebar setups would be awesome, especially now with the Code Outline and GitLens 5.0+ Extensions!

**Comment by zaha** [comment]
Was just wishing for the same :)

**Comment by liaoishere** [comment]
+1

**Comment by lig** [comment]
While I'd like to see two sidebars, I would like much more a tiled window manager like in Eclipse IDE.

**Comment by Hobart2967** [comment]
+1

**Comment by b-fuze** [comment]
I want this because I want some panes on a right sidebar and the rest on the left sidebar...
![image](https://user-images.githubusercontent.com/10504957/36620263-328161dc-18c0-11e8-9da9-fe4e2564a3c7.png)
It's hard to see the code outline while also navigating my file tree.

**Comment by dimitrieh** [comment]
Going to post my mockup from https://github.com/Microsoft/vscode/issues/45283 as well: 

![group](https://user-images.githubusercontent.com/429659/37147942-e935ba1a-22c8-11e8-9c3f-46caa63ce988.png)

**Comment by parascent** [comment]
+1

**Comment by zoldia** [comment]
+1

**Comment by aliihsanmv** [comment]
+1

**Comment by ned-painless** [comment]
+1

**Comment by ewan-sinclair** [comment]
+1

**Comment by lig** [comment]
Everybody, who adds redundant `+1` comments. Please don't.

This will lead only to other people will unsubscribe from this and/or this issue will be locked out from comments. Both things are bad for the further development of this issue.

Please, consider adding :+1: to the original description. Just click the icon.

Thank you!

**Comment by mhuxain** [comment]
+1

**Comment by dawid-s** [comment]
Hi there, I was just wondering, are there any (distant) plans on implementing this?

**Comment by michaeljota** [comment]
Giving that extensions now can create its own buttons and explorer panel, this would be a big deal for us as users.

**Comment by gulshan** [comment]
I think 4+ viewlet icons on the left(or right if configured) is what gives vscode the "Iconic" look. Even if two viewlets are enabled, one on left another on right, I think only one side should have the icons. The other side can have text only vertical tabs. And then it can be configurable to enable icons on both side, or text on both side.

**Comment by saluto** [comment]
Any progress on that? Generalizing the great new grid layout to manage all components, including viewlets, is the one thing I am really missing on VSCode. File and code browsing, git, debugging - all would be much easier without having to switch the viewlets every time. I strongly suggest looking at Atom as inspiration. It's nearly perfect.

**Comment by nealot** [comment]
Another example position could be:

![example_position](https://user-images.githubusercontent.com/36805289/42848501-c972a0e4-89ed-11e8-9af5-6392b1a82e16.png)

**Comment by gersilex** [comment]
As #49755 has been closed for being a duplicate, which isn't, we may need to discuss first if we should introduce a second activity bar.

The activity bar is the column of icons, shown at the left of the sidebar by default.

I suggest to introduce a second activity bar. Icons in the activity bar are already movable by the user. We can allow the user to move icons to the second activity bar on the right, which can become visible while holding an icon (keeping the mouse button pressed). Each clicked icon can show up in its respective sidebar. So clicking an icon in the left activity bar will open the element in the left sidebar; clicking an icon in the right activity bar will open the element in the right sidebar.

Both the right sidebar and activity bar could be hidden by default, only showing up while moving icons to not force the user to use it and reduce clutter.

What do you think?

**Comment by smspivak** [comment]
+1

**Comment by nealot** [comment]
I think the activity bar should only be on the left. That way you can right click on an icon to open the view on the right side.

**Comment by gersilex** [comment]
@nealot That is an interesting suggestion. Could work and would be flexible if you want to have the views on different sides often. But I can also imagine that users might not even try right-clicking the icons. Or me just clicking on it, without thinking about the mouse button I should press. Touch users might need another way to open it on the right side as well.

**Comment by nealot** [comment]
@gersilex 
> But I can also imagine that users might not even try right-clicking the icons. Or me just clicking on it, without thinking about the mouse button I should press. 

Currently, to hide an activity bar icon you must use the context menu -- why would this action be any different? Although I do think this should be supplemented by a drag-and-drop functionality.

> Touch users might need another way to open it on the right side as well.

As I mentioned above, I think drag-and-drop would be beneficial here. I use a touchscreen and while the context menus aren't unusable, they are difficult to work with.

Having two activity bars not only looks pretty uncomfortable, but it also wastes a lot of screen space; I'm completely against the idea of adding it.

**Comment by gersilex** [comment]
@nealot 
> this should be supplemented by a drag-and-drop functionality
Completely agree here.

> Currently, to hide an activity bar icon you must use the context menu
I think I misunderstood your first comment. I thought you wanted the view to open instantly, without showing a context menu. The idea with the context menu sounds good, though.

So we would add another entry to the context menu of the icons. Should the entry be for toggling the location (like `Pin to right activity bar`)? That sounds good to me.

Talking about drag-and-drop. We could also just drag the view to the right and display the right sidebar. This would comply with the look-and-feel of the editor windows and the grid. Maybe we can do both.

I do not insist in using a second activity bar at all. You got a strong point there and I agree that we should not introduce a second activity bar.

**Comment by nealot** [comment]
@gersilex My bad, I should have worded my original comment better. I like your idea about toggling the position. 

Maybe we could do something like this:

1. User right clicks on an icon
2. Selects context menu option `Pin to right`
3. Clicking on the icon from that point on opens it on the right
4. Option changes to `Pin to left`

**Comment by dawid-s** [comment]
Hi there, is there any development going on in this area? Perhaps there is a similar feature already being worked on? If that is the case I would appreciate if someone could provided related tickets pleae. From the UI point of view this is the biggest issue for me right now.

**Comment by eazrael** [comment]
Code Outline really needs it's own window. Having Explorer and Outline open at the same time is really the best way to navigate Quick in the Code. I would even say, drop the minimap and put the outline there (or on the left side ;-) 
Since a few years, the most common screen format is 16:9 with more horizontal space than vertical space, but source code did not grow horizontal, so more screen space is wasted with a lot of whitespace on the right side of the editor.

**Comment by zacharied** [comment]
Curious what the status of this is. It seems really overly opinionated to force all of these elements into one pane. IntelliJ handles this much better, modularizing each component into its own pane that can be moved wherever.

**Comment by burtek** [comment]
@bpasero do you guys have any plans for this?

**Comment by matthewess** [comment]
Adding my desire for this feature, I'm trying to use vs-code in a vertical monitor setup, and it would be neat to have the freedom to stack the panel, activity bar, and view (sidebar?) on the bottom of the screen. This would give me all of the horizontal space for editing, and move all of the "extra" stuff above or below. Obviously not all of the views will behave as well/effectively in a short and wide widget, but that's my problem to deal with I think :P

**Comment by dawid-s** [comment]
@matthewess I wouldn't hold my breath. They have loads of other requests and bugs to fix and perhaps this one would require quite a lot of work. However, we don't know any of it for sure as there has been a dead silence from the devs about it. If I am not mistaken there isn't a single comment from any VSC developer since when the request was created, which is over 2 years ago. .

**Comment by dbechrd** [comment]
Specifically regarding the sidebar: https://github.com/microsoft/vscode/issues/89064

This is what I would like to achieve:
https://user-images.githubusercontent.com/707367/72864376-a2a28480-3c88-11ea-9d74-30d1de1c4ae0.png

**Comment by phgmacedo** [comment]
> Specifically regarding the sidebar, this is what I would like to achieve:
> 
> ![image](https://user-images.githubusercontent.com/707367/72864780-214bf180-3c8a-11ea-8bf2-cbd97d4a20fd.png)

YES! I'd like to be able to do that as well.

**Comment by najamelan** [comment]
I miss this for debugging. I have a very wide monitor, but not so high (5120x1440). However I can't double up the debug sidebar, needing constant scrolling and most of my screen space just being wasted. And I'm not even having to look at registers right now, which by itself fills the entire height of my screen. I easily would have the real estate for 10 sidebars, but I can't reorganize anything other than collapsing things.

**Comment by JavierReyes945** [comment]
I would like to also point that users who use monitor in portrait mode (vertical), would also benefit from a "Sidebar" that is not on the side (as space to the side is limited), but instead being able to configure sidebar to open top or bottom (a.k.a., splitting the editor and the sidebar vertically). When I have to make a complex search or debug, I have to change vscode to a landscape monitor, and when done, move it back to the portrait monitor. I understand that detachable windows for sidebar is complex to implement, but perhaps this here would not be easier in the short term.

**Comment by tonank** [comment]
I very happily using and loving Intellij's approach of preserving the core of your perspective whether you are writing, analyzing, or debugging. I cannot really achieve that without multiple sidebars at the moment. Having to switch between explorer, tools, and debugging info is a real pain.

**Comment by michaeljota** [comment]
Intellij is an IDE. This is a text editor. That's like comparing a Chevy and a Mustang because you can take a ride in both.

**Comment by b-fuze** [comment]
But Atom has the feature, and it's also just a text editor.

________________________________

**Comment by saluto** [comment]
As I already mentioned in #92786 [(comment)](https://github.com/microsoft/vscode/issues/92786#issuecomment-607781281), another good inspiration is [Theia](https://theia-ide.org), which uses the same concept and extensions as VSC.

**Comment by eazrael** [comment]
> Intellij is an IDE. This is a text editor. That's like comparing a Chevy and a Mustang because you can take a ride in both.

The same killer argument as always. Please draw the line between an IDE and an editor, especially when it comes to the UI. What is missing to make VSC a "real" grown up IDE? Maybe we should apply duck typing for the definition of IDEs and editors.

Thea looks interesting.

**Comment by biter777** [comment]
@bpasero, @sbatten
https://github.com/Microsoft/vscode/issues/10121#issuecomment-345497635

About "isolated context" and Electron...
Just add a one new panel, "additional panel" (for example) and add item "move to Additional panel" to the "right-click" menu, such as already implemented "move to Panel" for "outline", "variables" and others (workbench.action.moveFocusedView and others, couldn't find a link to the function's implementation, but I hope you'll understand).

In this case, it doesn't require to share the same memory to the "main" window.
It's lightweight.

p.s. Everyone will be happy, especially the users of the wide and two monitors.

And yes, thank you for your work!

**Comment by ThaDaVos** [comment]
Will this be added? If so, any eta?

**Comment by clshortfuse** [comment]
Perhaps we need a new widget/component/control to this. Visual Studio essentially uses the [TableLayoutPanel](https://docs.microsoft.com/en-us/visualstudio/ide/step-4-lay-out-your-form-with-a-tablelayoutpanel-control?view=vs-2019) from .NET. It might be worth the effort to port that over to Web.

If you need UI guidance, you can look at Visual Studio: ![collapsed](https://visualstudio.microsoft.com/wp-content/uploads/2019/03/test-dark-Still-1200.jpg)

![expanded](https://docs.microsoft.com/en-us/visualstudio/ide/media/vs-2019/pr-experience.png?view=vs-2019)

**Comment by moon6969** [comment]
Funny.
Just had an ear-bashing from a colleague about browser based apps being the way of the future.
I'm slightly dubious since they seem unable to cope with bleeding edge UI features like dockable windows and toolbars?

**Comment by dessant** [comment]
I miss having everything in one view. In Atom you can open files, edit them, and commit changes, without switching to different views. That workflow is way more superior to what vscode offers when you need to make small changes that require frequent commits.

**Comment by esDotDev** [comment]
This is certainly the missing link to making VSCode feel less like a toy and more like a grown up editor.

VS Studio, Unity, ItelliJ all allow you do dock multiple panels, in any configuration you need, customizing your workspace and use the full size of your display.

Working on VSCode on an Ultra-wide feels a bit silly with one small 400px menu hiding 8 pages of data, and no way to view more than one at a time. 

It's a shame, because other than this one major flaw, it's really an excellent IDE.

**Comment by renegadevi** [comment]
Yes I really want this... I really want to have the option to put say the debugger on the right side visible all the time rather than having to switch view.

**Comment by MuellerSeb** [comment]
At least, the sidebar is mentioned in the "Workbench-Roadmap" for 2020: https://github.com/microsoft/vscode/wiki/Roadmap#workbench

> Support a more flexible workbench layout such as allow sidebars on the left and the right. For example, you could have your outline on the right and the file explorer on the left.

**Comment by LossMentality** [comment]
I'm brand new to VS Code, so forgive if the following has misperceptions (if it does, please feel free to correct me). 

The first thing I wanted to after about 10 minutes of using VS Code (and being very impressed) was the capability to open another sidebar.  So I searched the internet and found this request.... asking for two sidebars. And while that would be far better than one, I'm not sure why it should be limited to just two. 

Indeed, in Visual Studio or most any other IDE you can have any view opened and docked somewhere. But in VS Code, many views seemed to be limited to the sidebar, of which there is only one. So I can't, for instance, have search results and the explorer open at the same time. I'm not sure why we wouldn't want to be able to do that in VS Code - that is, to be able to dock any view anywhere we want.

**Comment by martin-braun** [comment]
> Specifically regarding the sidebar, this is what I would like to achieve:
> 
> ![image](https://user-images.githubusercontent.com/707367/72864780-214bf180-3c8a-11ea-8bf2-cbd97d4a20fd.png)

This is really what I would like to see, too. But I also want to mention that the File Explorer (first icon) has several sub sections like Open Editors and Outline. This is the reason why it's important to be able to open the File Explorer on both sides instead of moving it. So your consideration is right, because it allows to show all files on the left and the outline on the right, which is what I am after.

**Comment by tjx666** [comment]
code outline is hard to use right now...

**Comment by RandomFractals** [comment]
.@mjbvz: would this be possible for the sidebars with your new api described in #46585

**Comment by biter777** [comment]
Maybe it's time to include this improvement in the road map?
Please :)

**Comment by cakeslice** [comment]
Yes please!

**Comment by hmcclungiii** [comment]
I see that this thread has been going on for over two and a half years, so it's probably a waste of time to even comment here.

Since I am such a procrastinator and am great at wasting my time, I'll go ahead and throw in my two cents and my vote for this feature.

VSC is not a full-fledged IDE, it is a text editor at heart.  As a text editor it is the best text editor you will find, for the price, ever.  It is not a basic, low footprint editor, like Notepad++ is intended to be.  It has all the bells and whistles any text editor could ever have.  It's as advanced as Sublime, but without the $80 price tag.  It far exceeds Atom, which has a huge community base.  While it'll never beat VIM, it leaves all the others in the dust.  

I've just starting checking out Komodo, and it looks like it could be a little bit of competition in the Gabteide, or the "Grey Area Between Text Editor and IDE, landscape.

Even though VSC is not a 'real' IDE (whatever that means), it is most certainly an advanced piece of software.  More advanced than any of the other editors listed above.  And you know the one thing it is missing?  It is missing something that all those other editors have.  Even Notepad++ has the ability to do it (though not well implemented).  

Multiple Activity Bar Side Panels (not multiple activity bars)  There's absolutely no reason you couldn't get this in there.  There are at least a hundred viable use cases for this feature.  

Oh yea, except VIM.  No panels at all in that one.  Nope, none.  Not much UI to speak of.  And you'll still never beat VIM!

Sadly, the lack of this feature will keep VSC at the bottom of my toolbox.  I need to be able to take in a lot of information at once.  Those extra panels allow me to do that, which can be more important than any number of editor features in terms of convenience and efficiency.

Multiple Activity Bar Side Panels (not multiple activity bars) could keep VSC at #2 though, instead of #3, #4 or maybe even #5 (tentative on how Komodo works out for me).

I'd really like to keep you VSC, but when you're only the 5th or occasionally the 4th tool choice for editing my text files, I may as well just uninstall you.

**Comment by McPan** [comment]
I've been waiting for eons for the second sidebar as described in the 2020 roadmap. 

Most monitors are probably operated in landscape view, so there is plenty of space on the sides. I too would love to use the extra sidebar for the outline view, other users for GitLens.

Moving the outliner to the panel and then moving the panel to the side is not really a viable substitution. Since the panel size in this case is probably mostly set to fit a tree view, it's hardly possible to read terminal output in those dimensions. And constantly switching the panel between bottom and right is hardly a usable workflow.

Oh well, there are still 10 days left in 2020, Christmas is coming and I'm still hoping for a miracle.

Merry Christmas, Happy New Year and stay healthy!

**Comment by martin-braun** [comment]
@hmcclungiii Remove the false references to the issues `#2`, `#3`, `#4` and `#5`, please. If you want to rank VSC, do it without using the `#` character.

**Comment by daniel-santos** [comment]
Wow, really disappointing that such an obvious need is not solved.  Modern displays are 1:1.78 aspect ration, which means there is roughly 3/4 _more_ horizontal space than vertical (e.g., 1920x1080).  vscodium is wasting this space by not allowing outlines, which consume a great deal of vertical space, to be put **next** to other views that also consume a great deal of vertical space.

**Comment by RobertWHurst** [comment]
If you are complaining that this feature should have been implemented yesterday I suggest you check your expectations. VSCode is made available for free. It's already a fantastic editor, arguably one of the best, and you don't have to pay for it. The devs that are working on it are extremely skilled, and it shows. Good faith feedback is great, but I see a lot of comments here that are rude and seem to come from a perspective of entitlement, I can guarantee you that this has the opposite effect than what you are looking for. Rather than the devs reading this and feeling motivated, it probably makes them less likely to want to work on this feature.

**Comment by evg656e** [comment]
I think people just want that highly demanded features (like this one) to be taken into account by project managers when making roadmaps, and not lying around for years in the backlog, that's all.

**Comment by jrial** [comment]
> I think people just want that highly demanded features (like this one) to be taken into account by project managers when making roadmaps, and not lying around for years in the backlog, that's all.

As I've stated before in this thread: those people should read the project guidelines, and realise that the way to promote their favourite features is not through complaining, but through upvoting. The "comments section" is for adding relevant information, not to act out as if you're confused about the difference between an issue tracker and Twitter.

Meanwhile, everyone trying to follow actual progress on this issue is constantly bombarded with these useless complaints.

**Comment by mattlubner** [comment]
> If you are complaining that this feature should have been implemented yesterday I suggest you check your expectations. VSCode is made available for free. It's already a fantastic editor, arguably one of the best, and you don't have to pay for it.

This is a peculiar attitude to hold towards OSS. If you build a tool, release it to the world for free, and it becomes so popular as to become integral to the workflow of a significant number of professionals, the maker has gained something very valuable (at the least, influence & goodwill).

The question of price (it's "free") doesn't absolve Microsoft of some responsibility to maintain it, _if they still value that goodwill._

> The "comments section" is for adding relevant information, not to act out as if you're confused about the difference between an issue tracker and Twitter.

It can be both things.

Look, this is a 3.5+ year old issue. If you don't wish to hear from folks frustrated by its continued lack of attention, you can always unsubscribe (or maybe just ignore 'em).

**Comment by MuellerSeb** [comment]
Devs gave an explanation on why this specific task is hard to accomplish: https://github.com/Microsoft/vscode/issues/10121#issuecomment-345497635

**Comment by RobertWHurst** [comment]
@mattlubner I'm not going to unsub from this issue, but thanks for your suggestion. I'm subscribed in order to observe good-faith conversations around this issue and any progress that may occur. I stand by what I said, and to clarify, unless you are paying for someone's time you are not entitled to it. That said, as I understand it significant time has already been spent looking into how to achieve this feature. It just so happens that it requires very large and difficult changes. As for conversations about what stakeholders get in value for the privilege of being used in your development workflow, I'm sure that conversation would be fascinating, but this isn't really the venue for it. I think most people subbed to this conversation just want to be notified about this issue specifically, not that someone has a grievance with the development team or management.

**Comment by mattlubner** [comment]
> Devs gave an explanation on why this specific task is hard to accomplish: [#10121 (comment)](https://github.com/microsoft/vscode/issues/10121#issuecomment-345497635)

That comment seems specific to multiple Electron windows sharing the same context. Without diving into the source myself, I can't be certain, but it seems unrelated to rendering an additional sidebar within the same Electron window.

**Comment by mattlubner** [comment]
@RobertWHurst Let's keep this civil. Remember, everyone is coming with their own personal context. No need for confrontation.

I happen to mostly agree with you, especially on a more broad discussion about OSS being fascinating, and that this isn't the proper venue for it. It wasn't my intent above to broach that discussion, but rather to illustrate it isn't without depth/complexity.

No one benefits from the complaining (meta or otherwise), but we have all certainly been there ourselves.

**Comment by martin-braun** [comment]
> Devs gave an explanation on why this specific task is hard to accomplish: [#10121 (comment)](https://github.com/microsoft/vscode/issues/10121#issuecomment-345497635)

@MuellerSeb You seem to assume that floating windows are the only solution to this particular issue. In fact multiple views can be implemented without such requirement. There were some excellent suggestions (even in the very first comment of this issue) how the devs could improve the situation without forcing to have a new window for each view. 

All it takes is a 2nd side bar on the right side and the ability to move side bar menu entries to the right or left. Also the ability to show the outline on the right while showing the file browser on the left, so maybe showing the explorer on both sides and allowing its sub sections like "open editors", project files, "outline" and others to move to the right or left explorer section, too.

In my opinion that would resolve this issue, so it could be closed. Everything beyond that would require floating windows and I agree that this is not possible without changing fundamentals.

**Comment by saluto** [comment]
Instead of just a second sidebar, which is still quite limiting, I would rather suggest to generalize all views to use the existing and excellent layout system for tabs and splits. See [Theia](https://theia-ide.org/), which is based on VSCode and has such a generalized layout system.

**Comment by ItsCubeTime** [comment]
Personally I would like to see all panels dockable/undockable - and make them dockable anywhere within a window so that one can customize the layout of the editor to ones needs without restrictions

**Comment by McPan** [comment]
> 
> Personally I would like to see all panels dockable/undockable - and make them dockable anywhere within a window so that one can customize the layout of the editor to ones needs without restrictions.

That would be the icing on the cake. Until then I would be happy with a simple second sidebar for the outliner.

**Comment by ItsCubeTime** [comment]
> > Personally I would like to see all panels dockable/undockable - and make them dockable anywhere within a window so that one can customize the layout of the editor to ones needs without restrictions.
> 
> That would be the icing on the cake. Until then I would be happy with a simple second sidebar for the outliner.

And allow the "panel" to go below the sidebars instead of the text editor window - it would save you quite a bit of vertical space.

**Comment by taasjord** [comment]
First time trying out VS Code. Of course, first thing I wanted to change in the layout was to have sidebars both left and right like any other IDE and only find this issue. Great, I'll try again in another 4 years.

**Comment by villerdex** [comment]
+1

**Comment by wendellhu95** [comment]
![Snipaste_2021-07-11_13-03-48](https://user-images.githubusercontent.com/12122021/125183369-b52bc780-e248-11eb-9eab-0ef7c39f6a97.png)

Hey guys. I just made a rough implementation here and need time to polish it. 

Let me know what you think. ;) Hope this helps.

**Comment by ItsCubeTime** [comment]
> Hey guys. I just made a rough...

Ah, looks great 👍

This will end up in the releases from Microsofts website eventually right? If so, I would appreciate if someone could send another message here to let us know of when I out.

**Comment by McPan** [comment]
Thumbs up 👍

**Comment by wendellhu95** [comment]
A demo here.

https://user-images.githubusercontent.com/12122021/125544451-ed03cd41-f551-4355-8100-00590e5fdcb7.mp4

I will send a pull request soon.

**Comment by heartacker** [comment]
> A demo here.
> 
>  thirdpanelPart.ts.-.vscode.-.Code.-.OSS.Dev.2021-07-14.09-01-30.mp4 
> I will send a pull request soon.
> 
> BTW. Third panel doesn't look like a good name. Any idea?

1. please show the experience when the panel and the third view at the same time,(even user move the exit panel to right)
![image](https://user-images.githubusercontent.com/1876302/125550491-75d6b5aa-580f-4e83-92b0-f076bd34ec59.png)

2. do not use `ctrl+shift+b` because it's the default shortcut of build task. maybe we can use `ctrl+alt+b` instead
3. I still believe that the `three panel or view` should have the icon or title, maybe small then the the side bar or only titles. 
4. we should also be able to move any other views to the three panel
5. by the way, the visual studio float panel is very useful and powerful, we could use for reference

there is the float panel(FP) of vs2019, and some of those features are yummy

   - when the `FP` is hide, there are titles standing by side.
   - when click the of title of `FP`, the `FP` show, we can do something like navigation, but  after lost the fource, the `FP` automatically hide in order to maximize the editor view
   - we could also **PIN** those `FP` for persist view.


![float_pannel](https://user-images.githubusercontent.com/1876302/125550737-d3de4a19-8146-4626-8cc7-56505007fbe6.gif)

maybe the float panel is what i want 🐶

**Comment by wendellhu95** [comment]
Thanks for you suggestions! I will add more screenshots later.

* `Ctrl + Alt + B` is a good idea. 😄 
* Another activity bar (perhaps only texts) seems reasonable to me. But so far I have not implemented yet. Will do in the upcoming next days.
* Flowing panel is another thing. It deserves another issue I guess? Since the main sidebar could be float as well.

**Comment by heartacker** [comment]
> @heartacker Thanks for your suggestions! I will add more screenshots later.
> 
> * `Ctrl + Alt + B` is a good idea. 😄
> * Another activity bar (perhaps only texts) seems reasonable to me but I have not implemented yet. Will do in the upcoming days.
> * Floating panel is another thing. It deserves another issue I guess? Since the main sidebar could be floating as well.

now the side bar can't automatically hide when lost focus, and I hope that the new panel can show when user click or longtime hover and hide when lost focus, also can PIN.

maybe the float panel is another thing. but if we can  implement this feature of float panel, I think we have no necessary to implement the  *another sidebar**.

**Comment by hmcclungiii** [comment]
> @hmcclungiii Remove the false references to the issues `#2`, `#3`, `#4` and `#5`, please. If you want to rank VSC, do it without using the `#` character.
> 
Oh, my apologies, @martin-braun, I can't believe I forgot this was Github flavored Markup!

**Comment by biter777** [comment]
@wendellhu95, it looks pretty decent!
The sidebar, instead of the "third panel", can simply be called "additional panel".
We are looking forward to the appearance of this functionality!

**Comment by hmcclungiii** [comment]
@wendellhu95 I'm loving it!  I actually pulled your PR into my fork and built it.  I'll be using the custom build until it is added to the actual product, as long as I can!

**Comment by martin-braun** [comment]
> BTW, Third panel doesn't look like a good name. Any idea?

This beautiful panel shows only Outline and Timeline? Both are sub-sections of the Explorer Panel within the Activity Bar, but they are File-centric (meaning, they show only information relevant to the file). I think we could call it "File Panel" or "Additional File Panel" (expecting that Outline and Timeline are both still available in the Explorer window on right click).

If you can show whatever panel you want, that can be shown in the Explorer, it should rather be called "Additional Explorer", "Secondary Explorer" or "Separate Explorer" (since it's not part of the "Activity Panel". We could also call it "Explorer Panel", because it is a dedicated panel for the "Explorer", instead of being a child of the Panel that is shown by the "Activity Bar".

**Comment by eazrael** [comment]
Navigation Panel?

**Comment by hmcclungiii** [comment]
I haven't had any problem dragging and dropping windows from the activity
bar over to the new panel.

**Comment by heartacker** [comment]
dock panel, floating panel

**Comment by KamasamaK** [comment]
I don't think it's very useful to pollute this issue with crowdsourced names when the VS Code team will want to come up with the name themselves.

**Comment by daniel-santos** [comment]
> If you are complaining that this feature should have been implemented yesterday I suggest you check your expectations. VSCode is made available for free. It's already a fantastic editor, arguably one of the best, and you don't have to pay for it. The devs that are working on it are extremely skilled, and it shows. Good faith feedback is great, but I see a lot of comments here that are rude and seem to come from a perspective of entitlement, I can guarantee you that this has the opposite effect than what you are looking for. Rather than the devs reading this and feeling motivated, it probably makes them less likely to want to work on this feature.

I don't mind making such a complaint at all.  Do I feel entitled?  I've contributed at least a man year or two into open source software that you are probably using right now.  When I overlook something, I need _honest_ feedback.  Yes, it should have been in the _ORIGINAL_ implementation.  But nothing is a mistake if we can _learn_ from it, and to me, that is the blessing.  As the investors say, "never waste a good crisis."

Trying to approach our computing problems where we keep our mind open to the possibilities, avoid tight coupling, and explore the consequences of design decisions can help us to see when we may be "painting ourselves into a corner", and it seems like this is precisely what happened for this issue (and likely other related issues).  In short, if you design a widget to be in a single place all of the time, you're almost certainly thinking of your software design in too narrow of terms.

Frankly, I have been forced to use this software for a Go project by my employer.  After working with KDevelop, I find it quite lacking in many areas and also very helpful in many others.  So it's not "free" for me, it's a responsibility.

**Comment by daniel-santos** [comment]
@wendellhu95 Looking great, good work!

**Comment by sketchbuch** [comment]
I would call it right panel, anything related to explorer is wrong since all views can be dragged out to any where you want. (activity bar, terminals panel). Just because the mockup shows explorer related views does not mean views from other view containers will not be put there

**Comment by martin-braun** [comment]
> Frankly, I have been forced to use this software for a Go project by my employer.

@daniel-santos Frankly, you should question your employer and your current position more than the VSCode team in regards of this issue.

**Comment by jqknono** [comment]
this feature has been exists for years, while the vscdoe-huawei from huawei has add it for one year. Maybe they cannot publish it to github.

**Comment by Pingger** [comment]
How this still an issue after 4 years ... seriously!

**Comment by eazrael** [comment]
It takes volunteers to implement such features...

https://bugs.eclipse.org/bugs/show_bug.cgi?id=58945
This feature request had it's 10th anniversary in 2014 and is still open. So 4 years is quite fast.

**Comment by stefanrybacki** [comment]
> How this still an issue after 4 years ... seriously! 

There are far more pressing features and issues that need addressing. This one is I agree nice to have but does not really impede being productive with VSCode.

**Comment by daniel-santos** [comment]
> There are far more pressing features and issues that need addressing. This one is I agree nice to have but does not really impede being productive with VSCode.

Speak for yourself, my friend.  When working in Go, I'm ever clicking to change views when I have the horizontal space for most of those views to be on the screen at the same time.  I'm either hiding and expanding the "Outline", or going back and forth between the explorer and debug views, or expanding and shrinking various panes within the debug view to either see some value or change the stack frame.

Don't assume that everyone is doing the same tasks with this editor that you are.

**Comment by daniel-santos** [comment]
> @daniel-santos Frankly, you should question your employer (and maybe your current position) more than the VSCode team.

lol! I'm just spoiled on mature IDEs.  VSCode is a young project.  I agree with my employer's decision and I think it's currently the best option for Go development.  But mostly, I need it to work for our customers.

My primary criticism lies with Microsoft's decisions in the early phase of the project.  These lessons should have been learned from the prior decades of IDEs as well as GUIs, and widgets of every sort.  It's a basic tenent to not paint ones self into a corner, which the early project management most certainly did.  Perhaps they themselves were young and inexperienced.

I haven't dug into the sources yet, but given my project goals, I presume that I will be later this year.  I sure know that it's a lot more work to retrofit such changes than to have designed and built it that way from the start.

It's a very powerful IDE and a great challenge to fit the needs of a wide swath of languages, debuggers, programming paradigms, etc. in *addition* to add-ons that alter the behavior -- which vscode seems to succeed at more than it fails.

**Comment by DrecDroid** [comment]
Just right now at work and though VSCode already had that, would be a cool feature to have, still, thank you all for the great efforts you put to make this software, perhaps this feature could take time, but you always surprise us with great features we never thought we needed. Keep up the good work.

**Comment by martin-braun** [comment]
To everybody who wants to comment here:

How about simply upvoting the comments here (incl. the first comment that is most important) instead of commenting yourself without adding something new to the conversion, please? With each comment you notify everybody who is subscribing to this issue. A lot of people just subscribed to get notified by news regarding this issue. Simply commenting that you want the feature adds really nothing to the conversion and notifies a lot of people for no good reason. Scroll up and read the countless comments and I am sure you will find plenty of people who expressed your option already.

Thank you.

**Comment by Lorenz-N** [comment]
I assume this would help a lot for extension development. While it wouldn't solve my current issue directly, it would be a good workaround to get a customized Outline view in conjunction with a custom Side Bar and other viewlets.

Related to: https://github.com/Microsoft/vscode/issues/49923#issuecomment-907573485

**Comment by Smugger21** [comment]
@martin-braun After your repeated comments on this issue, I don't think you have room to talk. As one of the people subscribed to this issue, I have no problems seeing new comments, It lets me know people are interested in this topic still. So don't think your opinion is the only one out there.

**Comment by martin-braun** [comment]
Hey everyone, big thanks to @wendellhu95 for working on a PR that will provide a 2nd side bar in VSCode to us. [He is looking for people](https://github.com/microsoft/vscode/pull/128599#issuecomment-913300178) to test his build and report any bugs before requesting the PR, right now. You still have to build it yourself, but a Windows build is on the way.

@Smugger21 You are free to have your opinion, but nobody forbids anybody to comment here, you should neither. If someone wants to comment, it's fine, but it would be nice to comment responsibly to reduce clutter, please.

**Comment by heartacker** [comment]
the new side bar is available now with insider,
enable it by:
```
"workbench.experimental.sidePanel.enabled": true,
```

thank you @sbatten  & @wendellhu95 

![image](https://user-images.githubusercontent.com/1876302/134666130-c59fbd9a-3616-4ab4-9030-40e3dd77cff6.png)

**Comment by renegadevi** [comment]
> the new side bar is available now with insider, enable it by:
> 
> ```
> "workbench.experimental.sidePanel.enabled": true,
> ```
> 
> thank you @sbatten & @wendellhu95
> 
> ![image](https://user-images.githubusercontent.com/1876302/134666130-c59fbd9a-3616-4ab4-9030-40e3dd77cff6.png)
<img width="640" alt="Skärmavbild 2021-10-06 kl  20 33 45" src="https://user-images.githubusercontent.com/10997469/136262598-ceb510d7-b386-4c38-be24-c7ba88404610.png">


This is great, a big improvement, however something is limiting it from moving everything. So I still have to switch between file explorer to debug to access the debug bar at top, but everything else I can move out from it.
