### ISSUE TITLE
Ctrl + j not working in integrated terminal with zsh

### ISSUE THREAD

**Issue by ksrb** [Microsoft/vscode#26786]
- VSCode Version: Version 1.12.2 (1.12.2)
- OS Version: OS X E Capitan 10.11.6

**Steps to Reproduce:**

1. Open integrated terminal <kbd>ctrl+`</kbd>
2. In terminal:
```bash
> bindkey '^j' backward-word`
> enter some text
```
3. Input key combination <kbd>ctrl + j</kbd>

**Expected**
Cursor moves back a word, this the behavior that iTerm and Terminal.app exhibit

**Actual**
Newline is sent, essentially the same as using <kbd>return</kbd>

**Comment by Tyriar** [comment]
`bindkey` doesn't seem to be in the path in Terminal.app/bash for me?

**Comment by ksrb** [comment]
It's in zsh which some with mac by default? So just type `zsh` in Terminal.app.

**Comment by Tyriar** [comment]
Works for me, if you remove the backtick from your command:

```
bindkey '^j' backward-word
```

Not

```
bindkey '^j' backward-word`
```

**Comment by ksrb** [comment]
Oh that was a typo, I am using `bindkey '^j' backward-word`

Hmm that works in the integrated terminal for you?

Expected (in iTerm):
![may-17-2017 13-07-22](https://cloud.githubusercontent.com/assets/3750409/26173746/cfab21e8-3b01-11e7-9525-a61fd6f09811.gif)

Actual (in integrated terminal):
![may-17-2017 13-05-11](https://cloud.githubusercontent.com/assets/3750409/26173650/7c7cb5f4-3b01-11e7-8c19-db5d2f37ae5a.gif)

**Comment by ksrb** [comment]
FYI, I just tried rebinding <kbd>ctrl + j</kbd> with bash's native binding commands:

```bash
bind -x '"\C-j": clear; ls'
```

Again this works in iTerm and Terminal.app but not in the integrated terminal.

**Comment by Tyriar** [comment]
Hm I doesn't seem to be working anymore, maybe I didn't test it right or something.

I looked into it a little bit, it seems to work fine in the xterm.js demo which is the underlying library used. `^j` [actually translates to '\n' (carriage return)](https://github.com/sourcelair/xterm.js/blob/a95ac990ffd3fab501388c8501c835d969f58cbc/src/EscapeSequences.ts#L30) so that's why it's happening. The question is why does it work in the demo but not VS Code.

It definitely gets registered within zsh inside VS Code:

<img width="430" alt="screen shot 2017-05-17 at 9 50 05 pm" src="https://cloud.githubusercontent.com/assets/2193314/26186997/dd9d7ea6-3b4a-11e7-99f9-ccd73840ed79.png">

Stepping through the code nothing stuck out as misbehaving through when run inside VS Code; they appear to both be sending '\n'. Nothing in the `env` seems to be wrong either.

**Comment by ksrb** [comment]
Aw I was really of hoping it was something wrong with my local configuration.

Also I got the same behavior when trying it on windows + cygwin with a fresh install of vscode, <kbd>ctrl + j</kbd> not being distinguished from newline.

**Comment by ksrb** [comment]
Hey just wondering if there was any progress on this?

If this is low priority could one of the contributors maybe point me a area/file you think might be causing this issue? Thanks!

**Comment by Tyriar** [comment]
I can't look into it any further right now, I'm pretty stumped on where to go from here though. It's a pretty technical problem so it might not be the easiest thing to jump in to.

If you want to you can start by cloning https://github.com/sourcelair/xterm.js and trying to reproduce it using the demo. If you can reproduce it you can check what's sent to the backend by loading up devtools and debugging https://github.com/sourcelair/xterm.js/blob/35b32b721e9be175c2eedb83c264442d171152b5/src/xterm.js#L1756

If xterm.js works fine, it would be a matter of doing a similar exercise but figuring out why VS Code behaves different by debugging similar code.

**Comment by Tyriar** [comment]
(Copied from https://github.com/Microsoft/vscode/pull/30353#issuecomment-314262105)

This was happening because ctrl+j translates to `\n` (see https://github.com/sourcelair/xterm.js/blob/e849e3f2065ba13e53460c5c1c4febcd86384b49/src/EscapeSequences.ts#L30) and since we normalized `\n` to `\r` all input to the pty, this was getting lost and converted to a new line. The fix here is to never "sanitize" data that has already been processed by xterm.js (ie. key strokes and paste) as xterm.js knows how to handle them. We only need to process text that we send directly to the terminal such as a script the user is running or text being pasted into vim, etc.

**Comment by ksrb** [comment]
Hmm just updated to 1.14.1 and this still isn't working for me...
![jul-14-2017 15-08-23](https://user-images.githubusercontent.com/3750409/28232594-6810e644-68a6-11e7-826d-d012fa59ddb4.gif)

**Comment by chrmarti** [comment]
This will only be in 1.15.

**Comment by ksrb** [comment]
Oh okay thanks.
