### ISSUE TITLE
Create .deb package for Debian-based Linux distros

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#2679]
Related (rpm): https://github.com/Microsoft/vscode/issues/229

**Comment by bgse** [comment]
Few thoughts on this:

-> 'official' (aka Microsoft-Branded) packaging vs. 'community' (OSS-Build) packaging
(community is more or less effort-free as soon as someone decides a package would be nice, MS-branded is obviously cooler for those who prefer getting it directly from creator and want the neat logo)

-> best executable name?
(I prefer the Fedora COPR over the official releases simply because its executable is named 'vscode' which is cleaner in path than 'code' or 'Code')

**Comment by Tyriar** [comment]
@bgse I looked a little at what Atom does with regards to this in https://github.com/atom/atom/issues/2956. They distribute a .deb package and have ambitions of eventually having the .deb package register a repository. This is likely the path we will take as well for auto update support.

On executable, the plan is to expose a `code` wrapper script which calls `Code` in background and redirects output away from the terminal. You will be able to create an alias or rename the `code` script to `vscode` if you want. Not sure we would change the executable name at this point though, feel free to open an issue to get a wider perspective though.

**Comment by bgse** [comment]
@Tyriar Aliasing doesn't really solve the issue properly imo, renaming post-install is a fair point, but then I'd have to ask myself why I'd take the official repo over a community repo that possibly spares me of the hassle. Taking this to https://github.com/Microsoft/vscode/issues/2722 though as to not pollute your issue.
