### ISSUE TITLE
Insiders release not installing

### ISSUE THREAD

**Issue by jsheely** [Microsoft/vscode#2680]
I tried changing my storage.json to enable insiders build but VS code has not updated and is still on 0.10.6

I followed the instructions found here: https://cmatskas.com/visual-studio-code-getting-insider-builds/

Thoughts?

**Comment by nonbackwards** [comment]
https://blogs.msdn.microsoft.com/vscode/2016/02/01/introducing-insiders-builds/

**Comment by jsheely** [comment]
Thank you

**Comment by eliashdezr** [comment]
This link redirects to the stable build:
http://code.visualstudio.com/Docs/?dv=win&build=insiders

I'm not able to get the installer for the insiders build.

**Comment by nonbackwards** [comment]
:+1:

**Comment by chrisdias** [comment]
Over the weekend we had what we believe is a false positive alert from Windows Defender on the Insiders Build setup. When something like this happens the first thing to do is pull down the drop. Since it happened over the weekend, the fastest thing I could do was change the FWLink to point back to code.visualstudio.com. 

False positives have happened before and today we are no longer seeing Windows Defender (with updated definitions) flag the issue. To be safe we will continue to look at the issue today and we will update the link when we release the Feb 2016 stable release and an updated insiders drop that matches stable.

Sorry for inconvenience. One thing we plan on doing as a result of this is adding some sort of "service status" to the website to give people an idea of what is going on in situations like this.
