### ISSUE TITLE
Upgrading Powershell module to 1.1.0 reverts to 1.0.0

### ISSUE THREAD

**Issue by manelrodero** [Microsoft/vscode#26890]
- VSCode Version: 1.10.2
- OS Version: Windows 10 v1607 x64 (14393.1198)

Steps to Reproduce:

1. New version 1.1.0 doesn't appear as an update for the module I have installed (1.0.0)
2. Uninstall 1.0.0
3. Reload Window (I've done several tests, closing and opening VSCode)
4. Search for module. 1.1.0 version is the one available
5. Install + Reload
6. Version installed is 1.0.0 again

I've started asking by Twitter at https://twitter.com/manelrodero/status/865315202845343744 but no solution.

When I uninstall the extension, my "C:\Users\Manel\.vscode\extensions" directory is empty. After I install Powershell extension 1.1.0 searching from VSCode, the "ms-vscode.PowerShell-1.0.0" extension appears in my folder. After reload window or close/open vscode, extension is named 1.0.0 as expected per the directory.

Could it be a problem with extensions repository not updated? (i.e. index is showing 1.1.0 but server is sending 1.0.0).

**Comment by manelrodero** [comment]
Continue testing.
After seeing that my VSCode was 1.10.2 and not 1.12.2 I've asked about why I don't see the update.
Probably because I'm using ZIP file and Help menu doesn't have an option for checking about updates.
I've downloaded new version and replaced my old VSCode directory.
I've started it. Release Notes about new version appear and ... extension 1.0.0 is marked with the green button indicating that an update is available.
Upgraded. Reload and voilà, 1.1.0 is here ;-) Close and open VScode and 1.1.0 still here...

**So the problem was related to 1.10.2 version and it seems solved in the current 1.12.2 version.**

So probably, you can close this issue if you don't want to investigate something else.

**Comment by daviwil** [comment]
Yep, I didn't realize Manel was using 1.10.2 when he and I were discussing the issue.  Since the new update of the PowerShell extension targets the 1.12.0 version of the VS Code APIs, that explains why the new version didn't load for him.

However, I'm a little surprised that the "Help -> Check for updates" menu item isn't available in the "portable" install of VS Code.  I'd at least expect it to be there and give the user a message that they can't auto-update a portable install of VS Code.  Not a huge issue, but definitely a cause for confusion :)
