### ISSUE TITLE
[FEATURE REQUEST] Middle click to copy in integrated terminal.

### ISSUE THREAD

**Issue by vinay-naik** [Microsoft/vscode#26902]
- VSCode Version:
- OS Version: Ubuntu 16.04

Ubuntu's terminal allows us to copy and paste any text bt selecting it and clicking the middle mouse button. This is a very usefull feature and makes the experience much smoother. This feature is not available on vsCode integrated terminal. 

Also double clicking any text in the integrated terminal doesnt highlight the entire text the same way as ubuntus terminal does.
Eg : If we double click on test in the following text "Console/Command/test.php" ubuntu terminal will select the entire string where as vscode only selects "test"

Steps to Reproduce:

1. Selcet any test on the integraed terminal and click the middle mouse button.

**Comment by jhasse** [comment]
Works for me (Fedora 26). Do you have `"editor.selectionClipboard"` set to `true`?

**Comment by Tyriar** [comment]
Yeah this has worked for me flawlessly since it was implemented nearly a year ago. I'm on Ubuntu 16.10 currently. Some questions:

- What version of VS Code are you on? 
- Any logs in the console? (Help > Toggle Developer Tools)
- Does middle clicking on the text selection or outside of the text selection work?
