### ISSUE TITLE
VSCode won't open latest files when start

### ISSUE THREAD

**Issue by bluesup36** [Microsoft/vscode#26908]
- VSCode Version:1.12.2
- OS Version:win7 x64 sp1

Why can't VSCode open latest files just like sublime text?
I think it will be a great feature and easier to use.

**Comment by kaiwood** [comment]
It can. Do you have `files.hotExit` disabled? It should be on by default.

Also, you might want to set it to `onExitAndWindowClose` if it doesn't behave like you expect.

**Comment by bluesup36** [comment]
Hi kw,
Thanks for your feedback. But what I mean is for all the files no matter it was  saved or not. Sadly, it's not implemented yet. 

Senserely,
Vincent

**Comment by kaiwood** [comment]
That's what hotExit is for, it "freezes" your current working directory and remembers file state, no matter if a file is saved or not, even if you open an unsaved, "untitled" editor with no file association at all.

It works fine here,  so if it doesn't work for you, you might want to investigate why (and maybe play with the settings I described above). Maybe you stumbled upon a Windows specific bug or some broken access rights in your file system?

Can't tell because I have no Windows machine at hand, so some other kind person needs to help here. But the feature is definitely there :)

**Comment by Tyriar** [comment]
Hot exit is definitely implemented as @kaiwood says.

I recommend trying to add the following to your settings.json file for it to be as flexible as possible:

```js
"window.reopenFolders": "all",
"files.hotExit": "onExitAndWindowClose"
```

Note that when you have no folder opened hot exit is restricted somewhat, to get the best experience you should open a folder in VS Code.
