### ISSUE TITLE
Code autocompletion suggestions is not updated live

### ISSUE THREAD

**Issue by Srekel** [Microsoft/vscode#26938]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|rainbow-brackets|2gua|0.0.6|
|EditorConfig|EditorConfig|0.9.3|
|CppSnippets|hars|0.0.9|
|tabsanity|jedmao|0.0.9|
|contextualduplicate|lafe|0.2.0|
|cppcheck|matthewferreira|0.0.9|
|cpptools|ms-vscode|0.11.0|
|indent-rainbow|oderwat|0.6.1|
|reloaded-cpp|reloadedextensions|0.1.5|
|reloaded-themes|reloadedextensions|0.2.1|
|trailing-spaces|shardulm94|0.2.11|
|vscode-fileutils|sleistner|2.5.1|
|ninja|surajbarkale|0.0.1|
|clang-format|xaver|1.4.0|;

---

Here's a gif of something that happens very frequently. I'm working in C++ but that in and of itself doesn't seem to be the problem:

![autocompletebug](https://cloud.githubusercontent.com/assets/1578924/26251317/275e55ac-3cad-11e7-8835-31dd66ae0d9d.gif)

There's actually a few bugs here but this particular issue is about the fact that I need to close the auto-complete window (with escape) and then re-open it (with ctrl-space) for it to provide suggestions that make sense.

I would expect "num_get" to be removed from the list when the current word is "num_b".

**Comment by Srekel** [comment]
I realize that the c++ extension is working on improved auto completion ( https://github.com/Microsoft/vscode-cpptools/issues/606 ), but am I correct in guessing that this issue is a bug in VS Code? Shouldn't it re-poll for suggestions for every typed character?

**Comment by bobbrow** [comment]
Actually, the extension decides whether VS Code should re-poll or not once the list pops up.  If you type "n" as your first character and the extension determines that there are only 100 possible matches, the extension will send all 100 matches to VS code, mark the operation as complete, and then let VS Code do any additional filtering based on additional characters that you type.  In this case VS Code will not ask the extension for any more results unless you delete the initial character "n" and start over.  VS Code will only re-poll for suggestions if the extension says that it is returning a partial list of matches (likely because there are too many).

**Comment by Srekel** [comment]
I see, yeah that makes sense. :) Thanks for the reply!
