### ISSUE TITLE
Inline snippets should have lower precedence then actual properties if no match

### ISSUE THREAD

**Issue by CoenraadS** [Microsoft/vscode#26944]
- VSCode Version: Code - Insiders 1.13.0-insider (ec76a9fc5146b822cdb14b982ac3e5b470dd646a, 2017-05-19T08:16:05.720Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|ng-template|Angular|0.1.3|
|path-intellisense|christian-kohler|1.4.2|
|gitignore|codezombiech|0.5.0|
|bracket-pair-colorizer|CoenraadS|0.10.3|
|githistory|donjayamanne|0.2.0|
|tslint|eg2|0.15.0|
|vscode-postfix-ts|ipatalas|1.5.0|
|Angular2|johnpapa|2.2.3|
|debugger-for-chrome|msjsdiag|3.1.1|
|angular2-inline|natewallace|0.0.17|
|better-merge|pprice|0.7.0|
|code-settings-sync|Shan|2.7.0|;

---

Steps to Reproduce:

I have reported this issue before, it seems it is back: https://github.com/Microsoft/vscode/issues/25678

1. `"editor.snippetSuggestions": "inline"`
2. Have lots of snippets, i.e. use postfix extension
3. Bring up intellisense on an object
![image](https://cloud.githubusercontent.com/assets/5593825/26254395/bc14d820-3cb6-11e7-9351-a5821d227812.png)

**Comment by jrieken** [comment]
This is the design of the extension and our dynamic sorting. Because the post-fix suggestion selects the whole preceding word it matches very strong and is therefore sorted a top.

**Comment by CoenraadS** [comment]
May I ask which property controls this behaviour?

I tried setting sortText to the snippet keyword (e.g. `log`), however the behaviour is still the same.

**Comment by ipatalas** [comment]
I think it's not that easy here. I had to use some black magic to achieve what I wanted using only `CompletionItem` features.
That includes altering completion item range: https://github.com/ipatalas/vscode-postfix-ts/blob/master/src/completionItemBuilder.ts#L36

I believe that's what causes such a strong match. However I needed to extend that range to the left to be able to replace the text before the dot using just the `CompletionItem.insertText`. It was quite tricky to get that working.

I didn't know any other ways to achieve that back then. Now I know it should be also possible with editor commands called after each completion which could completely replace all the `insertText`, `range`. That's pretty much how I implemented `.not` snippet.

That approach seems doable but it's a major rework so I won't be able to implement it quickly. 
It sounds quite reasonable to me because I could then stop relying on `CompletionItem` that much and potential new possibilities would arise.
However it will need to wait for when I have at least several hours straight.

For now I can only suggest falling back to `"editor.snippetSuggestions": "bottom"`

**Comment by jrieken** [comment]
All correct. The `sortText`-property has lost most of its meaning since we started to sort and filter based on how well a suggestion matches the text left of the cursor. The 'how well it matches' depends the current text you replace and *how much and what kind of overlap* it has with a completion item. 

Unsure if we can make `sortText` be more meaningful again; I a open for suggestions. In its presence we could use the sort text to compute the rank of an item. That would make it determine the sorting of an item again. Needs some more thinking
