### ISSUE TITLE
Present symbolic names in keybindings.json for non-US standard keyboard layouts

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#26945]
* use VK_ names instead of the us standard produced character for serialization in `keybindings.json`.

**Comment by Tekbr** [comment]
@alexandrudima I will not say it got better, but less bad. So we do not weigh that we click the wrong key. 😄 


As for me pushing `´`, the problem still continues.
Steps:
1- Open Defines keybinding
2 - Press `´`.
3- Click Define keybinding.
4- Press `[`.

Now it shows `oem_6[`.

I commented on both issues(#23685) because I was in doubt on which to track

**Comment by alexandrudima** [comment]
Extracted last comment to #27088

**Comment by roblourens** [comment]
I can't figure out what to do, to see VK names.

**Comment by alexandrudima** [comment]
Adding verified since there was a test plan item #27481
