### ISSUE TITLE
"Stage changes" command doesn't work on Merge Changes

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#26957]
- Have a merge conflict in a git repo, file is in the "Merge Changes" section of the scm viewlet
- Hover the + button on the file in "Merge Changes", it says "Stage changes cmd+shift+S" with my keybinding
- Press that shortcut, or use the command via command palette - nothing happens
- It works as expected when the file is not staged

**Comment by BugraC** [comment]
@joaomoreno I can work on this one if possible.

**Comment by marckassay** [comment]
I believe this is directly related to #24919, which has a pull-request pending.  I wasn't able to receive the tooltip keybinding as @roblourens explained.  So that may be an issue, I don't know at this point.

Something to be mindful about, this ticket was created a day after the 'extensions/merge-conflicts' was added to master.  I don't think that should of changed the lack of behavior as @roblourens mentioned but again, just be mindful about it.

**Comment by BugraC** [comment]
@roblourens are you choosing a file and then press the shortcut? If you don't do that then nothing will happen. Stage changes only looks for the files that are selected then adds it to the stage. Please let me know if that works for you.

**Comment by pabloazurduy** [comment]
same error here! its there a workaround?

**Comment by joaomoreno** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.

Thanks for your understanding. Happy coding!
