### ISSUE TITLE
Property names starting with two underscores not handled correctly

### ISSUE THREAD

**Issue by oliversalzburg** [Microsoft/vscode#26951]
- VSCode Version: 1.12.2
- OS Version: Win 10

![image](https://cloud.githubusercontent.com/assets/1658949/26257631/ba005f40-3cc1-11e7-851b-671238c2905c.png)

Here's the code:
```js
"use strict";

class Profiler {
	constructor() {
		/**
		 * @type {Set<DataSource>}
		 * @private
		 */
		this.__dataSources = new Set();
	}
}

module.exports = Profiler;
```

**Comment by Tyriar** [comment]
@oliversalzburg is this JS or TS?

**Comment by mjbvz** [comment]
The bug is the extra underscore in the suggestion, correct? 

I believe this is fixed in our current insiders builds:

<img width="831" alt="screen shot 2017-05-19 at 12 43 34 pm" src="https://cloud.githubusercontent.com/assets/12821956/26264215/d4e18b08-3c90-11e7-8f13-3cac92d4a6a2.png">

Give them a try and let me know if you still see this
