### ISSUE TITLE
Theme: Debugger task dropdown inconsistency

### ISSUE THREAD

**Issue by equinusocio** [Microsoft/vscode#26953]
- VSCode Version: 1.13.0-insider (ec76a9fc5146b822cdb14b982ac3e5b470dd646a)
- OS Version: 10.12.4

The task dropdown inside the debugger sidebar doesn't use `dropdown.border`

Steps to Reproduce:

1. Check the debugger dropdown and the integrated terminal dropdown:
<img width="1391" alt="screen shot 2017-05-19 at 19 09 31" src="https://cloud.githubusercontent.com/assets/10454741/26258845/b76c4f5a-3cc6-11e7-8e0b-391633030c6b.png">

2. The first one doesn't use the `dropdown.border` setting

**Comment by cleidigh** [comment]
@isidorn 
@Tyriar 
@bpasero 

I happen to be in the middle of this code working on the select box/dropDown

it's the border over ride in debugViewlit.css (I commented out to show what it looks like)
since the action bar already has a border including the button adding a drop-down border color
looks a bit off - FWIW


.vs-dark .monaco-workbench > .part > .title > .title-actions .start-debug-action-item .configuration,
.hc-black .monaco-workbench > .part > .title > .title-actions .start-debug-action-item .configuration {
	border-color: #3c3c3c;
}

.monaco-workbench .monaco-action-bar .start-debug-action-item .configuration .select-box {
	/*border: none;*/
	margin-top: 0px;
	cursor: pointer;
}

![image](https://cloud.githubusercontent.com/assets/25272315/26262933/a118e546-3ca4-11e7-85cc-1b067e57f058.png)

**Comment by isidorn** [comment]
@equinusocio I acknolwedge the bug. The issue here is that the debug dropdown uses custom HTML elements to immitate a native select dropdown. 
I fixed this and you can pick it up in the next insiders.
