### ISSUE TITLE
Add Command: Copy All - Current panel output (no focus needed)

### ISSUE THREAD

**Issue by cleidigh** [Microsoft/vscode#26963]
As a continuation of the newly added "Copy All" ContextMenu option @isidorn added
it would also be very useful to have a pure keyboard access for this and other output windows.

As far as I can tell from experimentation and looking at all the commands, I cannot seem
to copy terminal output using only the keyboard . if one word is clicked on with the mouse
the Terminal: Copy Selected would apply. There does not seem to be a way to enlarge the selection
with the keyboard.
It would also be helpful with moving output.

A Copy All for any output would be highly useful and much easier for keyboard only users.
I looked at the extension API and I don't think this can be done with an extension , but I may have missed something. It still makes sense to me as a built-in command, .

**Comment by Tyriar** [comment]
@cleidigh so the command would copy the entire buffer of the terminal/debug console/output panel, not just the visible parts? I was planning on adding a Select all command to the terminal which would basically solve this issue I think.

@isidorn I'm a little worried about the lack of consistently between the panels.

**Comment by cleidigh** [comment]
@Tyriar 
SelectAll as a command eg assignable to a keyboard shortcut?  that would certainly solve the select issue.
I was just thinking a global command independent of the particular output window including focus
what allow you to paste into an editor really quickly. 
just as an aside , I have also noticed some of the inconsistencies such a select and scroll method
Bear in mind my comments and observations are almost entirely derived from keyboard only use
combined mouse and keyboard approaches are killer for disabled users.

**Comment by isidorn** [comment]
@Tyriar yeah the panels are completely incosistent since they all use different things under the hood, debug console - tree, output - editor, terminal - your xTerm. Unfortunetely due to that I believe they will never be consistent.

@cleidigh thanks for the idea, however as I pointed above it is hard to have one command that will rule them all, I mean all the panels. For instance this command does not make sense for the problems panel and the output (since in the output a user can simply press `ctrl + A` to select everything)

When looking for PR we love small things that solve one issue at a time and do not change the whole world. If you would like to contribute I agree that the debug console currently has the problem that copy all is not keyboard accessibile, but instead of adding command in the command palette I might prefer adding a title command next to the clear console. For that we would need an icon but I can look for that.
As for this issue in the terminal I think @Tyriar is better to answer that part

Thank you

**Comment by cleidigh** [comment]
@isidorn 
@Tyriar 
Yes I can see that it doesn't have full parallelism between output types
the individual Select all commands for the appropriate panels will solve the key problem

**Comment by Tyriar** [comment]
@cleidigh here's the issue for select all in the terminal https://github.com/Microsoft/vscode/issues/15199. It would be great if you could create a new issue for debug/output if needed and close this one off 😄

**Comment by isidorn** [comment]
Agree with @Tyriar -> closing this one
Thanks for understanding
