### ISSUE TITLE
I keep corrupting code with inadvertent multi-selections

### ISSUE THREAD

**Issue by erictraut** [Microsoft/vscode#26978]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:13:11.413Z)
- OS Version: Darwin x64 16.5.0
- Extensions: none
---

I frequently get into a state where the editor appears to have multiple selections, even though some of them are not visible on the screen. When I start typing with the intent of replacing the visible selection, I end up corrupting the other instance of the same text elsewhere in the file, often times without realizing it until much later. This has been a problem since the early days of VSCode, but I've never been able to figure out repro steps before.

Steps to Reproduce:

1. Find a piece of text in your code file that occurs more than once (e.g. a method name).
2. Double-click on the text to select it. Press command-E to set it as the search text.
3. Click somewhere else
4. Repeat step 2. Double-click on the same piece of text as before, press command-E again.
5. At this point, you'll be able to observe two separate blinking insertion points as shown in the attached screen shot.
6. Start typing to replace the selection. Note that the replacement text affects both instances.

![screen shot 2017-05-19 at 9 06 36 pm](https://cloud.githubusercontent.com/assets/7040122/26272820/15dcb3a8-3cd7-11e7-9bf3-3c8a29d0ee3e.png)

**Comment by rebornix** [comment]
@ericlaw1979 which theme are you using? It looks like for that theme, current selection and matches are using the same background color.

**Comment by erictraut** [comment]
I'm using the default theme — I've never changed it. But that's beside the point. Regardless of how it's styled, I don't think it should ever replace multiple selections as I type.

**Comment by ericlaw1979** [comment]
Is the behavior the same as if you hit `CTRL+F2` to invoke the "Change all occurrences" feature?

**Comment by erictraut** [comment]
It's similar to that, except that
1) it doesn't appear to affect all instances; it affects only two of them
2) when using ctrl+F2, the blinking insertion points are always at the end of all selected text, but when I get into this state, the insertion points are sometimes at the beginning

Here's another screen shot that shows four instances of the word "items". Two of them are in this multi-select state and two are not. Of the two that are selected, one shows the insertion point before, the other after.

![screen shot 2017-06-01 at 1 09 10 pm](https://cloud.githubusercontent.com/assets/7040122/26698633/926d5db6-46cb-11e7-9424-0463741c2150.png)

**Comment by mgutz** [comment]
This issue happens to me daily. What is the color identifier in a theme that corresponds to `addSelectionToNextFindMatch` (`Ctrl+D`) background. The cursor color is not enough.

**Comment by ajm13** [comment]
I am also having this issue.

I use the `Ctrl+D` shortcut frequently to select the current word my cursor is on, and I have noticed that when the find window is open in the editor, `Ctrl+D` makes the current word highlight in addition to the next occurrence. Without the find window open, `Ctrl+D` properly selects the current word and will only select the next occurrence if the shortcut is pressed a second time.

More specifically, the double selection only happens when the word that is to be selected is not already in the find prompt. For example, if the find prompt is empty, and I put my cursor in the middle of the word `this`, and then hit `Ctrl-D`, the word at my cursor is highlighted, as well as the next occurrence of `this`, and `this` is added to the find prompt. If the find prompt already contains `this`, and I repeat the same steps, only the `this` at my cursor is highlighted with a press of `Ctrl+D`

**Comment by rebornix** [comment]
@ajm13 thanks!
