### ISSUE TITLE
[folding] Preserve folding state when dragging text

### ISSUE THREAD

**Issue by PLyczkowski** [Microsoft/vscode#26998]
Currently dragging around folded text drags only the top line, not the folded text within. 

How it could work:
- Select whole line that has folded text within.
- Drag and drop
- The line is moved and the text within is moved with it, stays folded

For a working example of this request, see Sublime Text.

**Comment by rebornix** [comment]
![subl](https://cloud.githubusercontent.com/assets/876920/26507744/95a66a8c-4206-11e7-9c82-9c30f2c5b1f1.gif)

@PLyczkowski Do I need to set up anything to make this happen in Sublime?

**Comment by PLyczkowski** [comment]
@rebornix Well, no, it works almost as it should in the example you provided, with the exception of code unfolding after being dropped.

**Comment by aeschli** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.
If you disagree and feel that this issue is crucial: We're happy to listen and to reconsider.
Maybe you want to give it a try yourself and provide the feature through an extension or a PR: We're happy to give advise and get you started.
Thanks for your understanding. Thanks for helping and happy coding!
