### ISSUE TITLE
Test omnisharp installation hint

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#2701]
### Assignment

- [x] Windows @stevencl 
- [x] OS X @chrisdias 
- [x] Linux @weinand 

### Details

We plan to make omnisharp an optional extension. To make a smooth transition we let the user know once and offer a direct install. 

* have no omnisharp installed
* open vs code, open any  csharp-ish resource (`*.cs, project.json, *.csproj` etc)
* you are informed and offered to install

Make sure
* that you get a reasonable hint
* the hint only shows once (check local store for `global://extensionsAssistant/legacy...`)
* you can install omnisharp from the hint

**Comment by egamma** [comment]
The experience is bad without some progress indication, filed #2835

**Comment by stevencl** [comment]
I agree with @egamma, while it works, the experience is pretty bad without any progress indication. But I also agree that we should take some time to think about how best to design a solution to this.

**Comment by chrisdias** [comment]
The OmniSharp extension is being slimmed down to remove the runtime, such that the runtime will be installed on first activation.  That means the extension should install quickly and then there will be UI to install the rest. @DustinCampbell is working on the install experience now.

**Comment by chrisdias** [comment]
From my testing: The prompt is useful but it is easy to miss it and it never comes up again. Maybe I don’t want to install it right now, because I opened the tool on the wrong folder, etc.  If I bring up the tool, get the prompt, and press Cmd+Q to exit Code I'll never get the prompt again. 

I put a suggested experience in #2748, which is effectively to have a yes/no/later prompt and to only write the "do not prompt again" flag if the user presses "no".
