### ISSUE TITLE
Ctrl+s saves/overwrites the wrong content to the wrong file - Can cause lost work

### ISSUE THREAD

**Issue by JoakimNil** [Microsoft/vscode#27032]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.6.3|
|intellij-idea-keybindings|k--kato|0.2.10|
|python|tht13|0.2.3|;

---

I've lost my work twice in a few days because of this, so I hope this is addressed quickly if it turns out it's not just me. The potential bug is best explained by describing steps to reproduce.

Steps to Reproduce:

1. Open a file in a separate VSCode window, make some changes then save changes
2. Open a new file (Ctrl+N) that opens in a new tab in the same VSCode window
3. Make changes to the new unsaved and untitled file
4. Without saving the new file, go back to original file, make more changes
5. Save the changes with Ctrl+S

Unexpectedly, the "Save as..." window appears. When this happened to me the second time I wondered if I had the wrong file/tab open when pressing Ctrl+S, but I could see that I had the correct tab open/selected behind the "Save as..." window.

6. There's no reason to rename the file, so save it with the same path/name as before

A dialog asking to confirm overwriting the existing file appears.

7. Confirm overwriting.

Upon confirming, a few things happen:

- The open/selected tab disappears
- The previously unsaved file is now displayed
- The unsaved file has now been saved with whatever specified in the "Save as..." window
- If the same path/name as the original file was specified, the original file has now been overwritten
- Ctrl+Z history from the original file has been wiped, removing the last hope for retrieving the lost file contents

**Comment by bpasero** [comment]
@JoakimNil the bug here is that Ctrl+S shows the save dialog, which is unexpected. Can you share your keybindings.json file with me? Could it be you have Ctrl+S associated with "Save All"?

Another thing to try is to see if it reproduces with extensions disabled: 
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by JoakimNil** [comment]
Thank you for the suggestion - I did in fact have Ctrl + S associated with "Save all" - in addition to "Save". I imported the keymap from IntelliJ (where Ctrl+S = "Save all" by default), so I assume that's how that happened. The problem is gone after removing the "Save all" keybinding.

**Comment by bpasero** [comment]
@waderyan fyi on the intellij keybinding issue.
