### ISSUE TITLE
Terminate all tasks

### ISSUE THREAD

**Issue by TheColorRed** [Microsoft/vscode#27041]
- VSCode Version: 1.12.2
- OS Version: Ubuntu 17.04

Steps to Reproduce:

I have multiple tasks running, One Sass and one TypeScript, I would like to be able to end all tasks with one keyboard shortcut. I currently have to end each task separately, so it would be nice to have something that will end all tasks.

Here is what I have for tasks:

```json
{
    "version": "2.0.0",
    "isShellCommand": true,
    "showOutput": "always",
    "tasks": [
        {
            "isBuildCommand": true,
            "taskName": "Build",
            "dependsOn": [
                "Build Sass",
                "Build TypeScript"
            ]
        },
        {
            "taskName": "Build Sass",
            "command": "node-sass",
            "args": [
                "-w",
                "./src/sass/main.scss",
                "./public/assets/css/prefab.css",
                "--output-style",
                "compressed"
            ]
        },
        {
            "taskName": "Build TypeScript",
            "command": "tsc",
            "problemMatcher": "$tsc-watch",
            "args": [
                "-w",
                "-p",
                "./src/typescript"
            ]
        }
    ]
}
```

**Comment by dbaeumer** [comment]
Fair request.

**Comment by Leninsky** [comment]
Still not implemented ?

**Comment by grebulon** [comment]
Is this going to be implemented?

**Comment by dbaeumer** [comment]
It is `On Deck` meaning it has some sort of priority for us. As always a PR speeds up things :-)

**Comment by alpalla** [comment]
Hi, could I try helping out? If so, any pointers would be appreciated. Thank you!

**Comment by dbaeumer** [comment]
@alexr00 could you point @alpalla to the right code.

I would may be not add another action. I would rather have an additional entry in the terminate task drop down that simeply says All running tasks

**Comment by alexr00** [comment]
I agree that we do not need another command here. Adding an additional entry to the terminate task quick pick for "All running tasks" is a good fit.
@alpalla the code is here: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/contrib/tasks/electron-browser/task.contribution.ts#L2200
You will need to add a new item to the quick pick for all running tasks. The command already takes an arg(https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/contrib/tasks/electron-browser/task.contribution.ts#L576) so you can define a value that indicates that all running tasks should be terminated for use in a keybinding. 

The keybinding shouldn't be a default keybinding so that we don't take up another default. Instead, once the work to have an "All running tasks" arg and quick pick entry is done, you can add a custom keybinding for yourself.

**Comment by alexr00** [comment]
To verify:
- Start 1 long running task. Execute the Terminate Task command. Verify that the terminate all option is not shown.
- Start more than 1 long running task. Execute the Terminate Task command. Verify that the termiante all options is shown.
- Setup this keybinding: 
````
	{
		"key": "ctrl+shift+alt+t",
		"command": "workbench.action.tasks.terminate",
		"args": "terminateAll"
	}
````
Start some long running tasks. Use your keybinding and verify that all tasks are terminated.
