### ISSUE TITLE
windows set terminal to bash cause workspaceRoot incorrect

### ISSUE THREAD

**Issue by lerit** [Microsoft/vscode#27068]
My question is similar to issue [20097](https://github.com/Microsoft/vscode/issues/20097)，it was closed
in Feb 8,but i still face this problem,my vscode version:1.12.2

"terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe",
 launch.json:
```
{
    "type": "node",
    "request": "launch",
    "name": "Nodemon",
    "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/nodemon",
    "args": ["--config", "nodemon.json"],
    "protocol": "inspector",
    "runtimeArgs": [
      "--inspect=5858"
    ],
    "port": 5858,
    "console": "integratedTerminal"
  }
```
console error:"bash: e:fda_hch/node_modules/.bin/nodemon: No such file or directory"
i think it lose '/' in my workspaceRoot.
swith:'protocol': 'legacy',and "--inspect=5858" to "debug=5858" not solve my problem,timeout and suggest
me to use inspector.

**Comment by lerit** [comment]
i hardcode:
"runtimeExecutable": "e:/fda_hch/node_modules/.bin/nodemon"
but Is there other resolution?

**Comment by josesimoes** [comment]
I'm having the same issue on a couple of var replacements with this variable.
Reported it Microsoft/vscode-cpptools#908

**Comment by weinand** [comment]
This is WSL related, correct?

**Comment by weinand** [comment]
Since you are configuring the integrated terminal with "bash.exe", everything that is launched there will launch on the linux side of WSL. This means that the paths used for the `runtimeExecutable` must be linux paths, so you cannot use variables like `${workspaceRoot}` because your workspace still lives on the Windows side.

But specifying path as linux paths (e.g. `/mnt/c/Users/abc...`) does not work either, because VS Code tries to validate those paths on the Windows side (which fails).

So the only thing that could work is to use a tool that can be found on the PATH on either the Windows or linux side. So you could try to set `runtimeExecutable` to "nodemon" (if "nodemon" is on the PATH on both sides.

If the tools can only be found in `node_modules/.bin` folder, I suggest to set `runtimeExecutable` to "npm" and create an npm script in the package.json that launches the tool (npm by default looks into the `node_modules/.bin` folder).

So this might work:
```
{
    "type": "node",
    "request": "launch",
    "name": "Nodemon",
    "runtimeExecutable": "npm",
    "runtimeArgs": [
        "run", "nodemon-script"
    ],
    "args": [ "--config", "nodemon.json" ],
    "protocol": "inspector",
    "console": "integratedTerminal"
}
```

**Comment by weinand** [comment]
I just noticed that this is not a WSL issue because you are not using `bash.exe` but `C:\Program Files\Git\bin\bash.exe`. So ignore my comments from above.
