### ISSUE TITLE
*/shell.i18n.json lost some translations in 2017-05-19. Merged in translations.

### ISSUE THREAD

**Issue by yfdyh000** [Microsoft/vscode#27063]
prof.* series in i18n/*/src/vs/workbench/electron-browser/shell.i18n.json of https://github.com/Microsoft/vscode/commit/bd14b32aeaaec846f41a8ceaee90752e7198354b#diff-971b16c06708ca467431abcce9760104.

**Comment by michelkaporin** [comment]
This has been moved to a different file in 3b6d8a3185fc9291c348f2472f56d99dfd91edc5, however seems that translations were not updated from Translation Memory in Transifex in the commit above. 

@danyeh did you wait until translations were filled from TM before pulling them to VS Code? 

Anyway this will be fixed with the latest translations pull (as they are in Transifex), thus closing.
