### ISSUE TITLE
Request: Add two software languages, and IntelliSense for both

### ISSUE THREAD

**Issue by Software-Engineer-CodewareBI** [Microsoft/vscode#27205]
Considering the effort that Microsoft's development team has put forward to produce the Power BI desktop and service suite, it makes sense to me that Visual Studio Code should recognize DAX (*.dax) files and M-language (*.m) files.

When can we expect DAX and M to be supported?

**Comment by aeschli** [comment]
Please upvote this issue (add 👍 ) so it gets added to a future plan.
Otherwise, maybe someone from the community wants to give it a try.

@seanmcbreen FYI

**Comment by codewarebi** [comment]
The native editor windows for DAX in PowerPivot, Power BI, and in Visual Studio SSAS Tabular Mode are all inadequate. Since you are creating a code editor, like you guys are doing, it makes sense to fill-in the gaps such as this one, especially since Power BI is a very important product for Microsoft.
