### ISSUE TITLE
Regex not respected in 'getWordRangeAtPosition'

### ISSUE THREAD

**Issue by pancho111203** [Microsoft/vscode#27245]
I am having issues with the method 'getWordRangeAtPostition' of TextDocument. The problem is that the regex added as second argument is not respected.

This is my code:
`
const wordRange = editor.document.getWordRangeAtPosition(selection.active, /[a-zA-Z0-9_[[:space:]]]*/);`

Using this example: 

`"bla bla bla bla" `

To my understanding, the four words should be selected, as the [[:space:]] regex indicates that spaces are part of words. But the behaviour is the same than without the regex (only 1 word is selected).

**Comment by roblourens** [comment]
Does it work with a space literal instead of the space character class?

**Comment by pancho111203** [comment]
Same thing :(

Using regex: /[a-zA-Z0-9_ ]*/

**Comment by jrieken** [comment]
The problem is that the regular expression matches the empty string which very likely causes endless loops when trying to go from word to word. Therefore it is [ignored](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/node/extHostDocumentData.ts#L244). I will update the docs and emit a warning when this happens
