### ISSUE TITLE
[icon theme] Allow icons for specific theme

### ISSUE THREAD

**Issue by equinusocio** [microsoft/vscode#27244]
Hi all, there is a way to set icons based on a theme id? Since we have

```json
"light": {
  "folderExpanded": "",
  "folder": "",
  "folderNames": {
  },
  "folderNamesExpanded": {
  }

},
```

there is a way to set the theme name instead of `light` or `contrast`? My `theme.json`have the `name` key, is possible to use it as key intead the default (light, contast)? like:

```json
"THEME-NAME": {
  "folderExpanded": "",
  "folder": "",
  "folderNames": {
  },
  "folderNamesExpanded": {
  }
},
```

I have 3 dark themes, and i'm just wondering if i can set different folder icons for each theme.

**Comment by aeschli** [comment]
There are hundreds of themes out there with new ones coming out every day. So referencing a specific theme isn't very practical.
Is your goal to match the icon colors to theme colors? Maybe we should look into giving access to workbench colors in the icon theme.

**Comment by equinusocio** [comment]
@aeschli I mean maybe you can make the theme `name` a required key, and use it inside the icons theme (instead of "likh", "dark"... ), i don't know, i'm just thinking.

> Is your goal to match the icon colors to theme colors? Maybe we should look into giving access to workbench colors in the icon theme.

Exactly. But now icons are fonts or svg... how to you handle svg icons color? I think the theme author should specify which svg to use in which theme.

**Comment by aeschli** [comment]
Right now, if you have an icon theme and a color theme that go together, name them the same so that users use them together.

**Comment by equinusocio** [comment]
So if my theme extension provide 3 UI theme and if i need to change icons
based on the active theme i have to build 3 different icon themes? Is this
right?

Il ven 26 mag 2017, 21:48 Martin Aeschlimann <notifications@github.com> ha
scritto:

**Comment by aeschli** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.
If you disagree and feel that this issue is crucial: We're happy to listen and to reconsider.
Maybe you want to give it a try yourself and provide the feature through an extension or a PR: We're happy to give advise and get you started.
Thanks for your understanding. Thanks for helping and happy coding!
