### ISSUE TITLE
Use EdgeHTML instead of Blink on Windows

### ISSUE THREAD

**Issue by Jop-V** [Microsoft/vscode#27268]
This would reduce the download size and RAM usage of the Windows version. It would also be a great incentive for the Edge team to add missing features.

**Comment by wizarrc** [comment]
If EdgeHTML and Chakra technologies were used, would that mean it could theoretically be added to the windows store?

**Comment by yfdyh000** [comment]
@wizarrc Release in the Windows Store #10759

**Comment by Wasserbroetchen** [comment]
I would love that, because edge is way smoother on low end devices.

Currently I am limited to a very bad notebook with intel atom inside and vscode is very slow. Chrome is slow aswell, but edge is smooth and fast.

So that's why I have to use sublime text right now. But I really would love to use VSCode instead.
So please do this Microsoft.

**Comment by Jop-V** [comment]
Closing this as there's no hope anymore. The newly announced Edge for Android uses Blink too, so I think we can conclude EdgeHTML is discontinued. Sad. I wonder why Microsoft hasn't announced anything yet regarding the desktop version of Edge.

**Comment by wizarrc** [comment]
@Jop-V I don't think that means EdgeHTML is discontinued. The reason Edge for Android uses Blink is that EdgeHTML is very specific to Windows and would be hard to port over to another platform. The reason Edge is even on Android and iOS is so that people have a consistent UI when using their mobile device and can sign into their Microsoft Account so they can sync their bookmarks, etc between devices.

This has nothing to do with the fact that Microsoft could bring Edge to Electron on Windows (the technology that vs code uses under the hood). In fact they have brought their technology to other components such as the core of Chakra (the Microsoft JavaScript engine) to Node.js as a swappable component. I don't see any reason Microsoft couldn't do that for Electron if running on windows.
