### ISSUE TITLE
UI: Odd scroll bar design makes it unseeable

### ISSUE THREAD

**Issue by QwertyZW** [Microsoft/vscode#27307]
- VSCode Version: 1.12.2
- OS Version: Windows 10

Steps to Reproduce:

1. Open enough editor tabs till the scroll bar appears

The scroll bar that appears is incredibly thin vertically making it quite difficult to get a hold of with the cursor and extremely long horizontally making it difficult to notice that it's there, it took me a while to realize that it existed and it was actually a mean to scroll across the tabs, I had been only closing editor tabs every time the pan overflowed.

![vscodeoddscrollbar](https://cloud.githubusercontent.com/assets/8478946/26476953/21483b32-4190-11e7-8ac4-56456db1809e.png)

![vscodeoddscrollbar](https://cloud.githubusercontent.com/assets/8478946/26477011/821799e4-4190-11e7-9f69-07db237a306e.png)

**Comment by stevencl** [comment]
Thanks for the feedback. Our original intent was for this to provide feedback that there are more tabs than can be shown. If you use the scroll wheel on your mouse while hovering over a tab you should see the tabs scroll to the left and right as appropriate. This was our desired way of interacting with the scrollable tabs, rather than clicking directly on the scroll bar.

We wanted to ensure that the scroll bar indicated that there were other tabs that could be scrolled into view but that it didn't obscure the tabs. Hence we came up with a small bar that could be scrolled with the mouse wheel.
