### ISSUE TITLE
File save-as always fails on first attempt

### ISSUE THREAD

**Issue by NeilMacMullen** [Microsoft/vscode#27329]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|Bookmarks|alefragnani|0.15.0|
|numbered-bookmarks|alefragnani|0.9.1|
|cpptools|ms-vscode|0.11.2|
|csharp|ms-vscode|1.10.0|
|PowerShell|ms-vscode|1.1.0|;

---

Steps to Reproduce:

1. Create a new file 
2. Use File/Save -as to save it in a project

I _always_ see this initial error....

Failed to save 'Persist.cpp': A system error occured (EBUSY: resource busy or locked, open 'c:\... path......\Persist.cpp')

3. Click retry - the file will be saved successfully.

I'm using git for source control - maybe there's a race condition here but this error happens consistently on two different machines across multiple projects.

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by sean-mcmanus** [comment]
The cpptools extension will release a fix for this in our next update.
