### ISSUE TITLE
showTextDocument & vscode.diff always default to ViewColumn.One

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#27408]
- VSCode Version: Code - Insiders 1.13.0-insider (770206ab9c6357943a2145bd3ea49b667f3ff539, 2017-05-26T05:14:23.944Z)
- OS Version: Windows_NT ia32 10.0.16199
---

These 2 apis should honor the ViewColumn if specified, but if left `undefined` they should default to the column of the active editor

Having this will eliminate code in many extensions such as:
```ts
(window.activeTextEditor && window.activeTextEditor.viewColumn) || 1
```

Which fails for anything that isn't a text document (since `viewColumn` will be missing)

**Comment by jrieken** [comment]
> Which fails for anything that isn't a text document (since viewColumn will be missing)

Unsure what that means?

**Comment by eamodio** [comment]
Sorry, I meant that the `window.activeTextEditor` could be `undefined` if the actual active "editor" is a non-text document (image, extension, etc). And `window.activeTextEditor.viewColumn` can be `undefined` for a diff editor (maybe other cases?). So an extension can't reliably get the real "active" column

**Comment by bpasero** [comment]
+1 for not setting ViewColumn.ONE as default if not specified so that we prefer the currently active editor column when documents open.

**Comment by eamodio** [comment]
@bpasero PR https://github.com/Microsoft/vscode/pull/27409 addresses it, but it conflicts with another change see: https://github.com/Microsoft/vscode/pull/27409#issuecomment-304564580

Any thoughts on coming to a resolution on that -- I would LOVE to see this fixed.

**Comment by bpasero** [comment]
@eamodio we have an option for editors to reveal if they are open in another group (see [`revealIfOpened`](https://github.com/Microsoft/vscode/blob/ben/32936/src/vs/workbench/common/editor.ts#L543)).

I am actually surprised that https://github.com/Microsoft/vscode/issues/25801 was fixed and marked as important because the normal workbench behaviour is to open an editor in the currently active editor group. On top of that, the solution also does not seem right because what if I start in column 2 and I open a document in column 3 and then open the document from column 2 again. It opens in column 1?

**Comment by eamodio** [comment]
@bpasero I was surprised as well as that was my argument too :)

**Comment by eamodio** [comment]
I could rebase that PR again (since its quite old) if you'd like, but it will still fail because of a test checking for https://github.com/Microsoft/vscode/issues/25801

**Comment by jrieken** [comment]
> I am actually surprised that #25801 was fixed and marked as important because the normal workbench behaviour is to open an editor in the currently active editor group.

Well, we had this behaviour in place, extensions rely on it https://github.com/Microsoft/vscode/issues/25801#issuecomment-329824653, and we don't want to break them. That's why this is tricky
