### ISSUE TITLE
Correct translation: Change of 'Cut' in Brazilian Portuguese (pt-br)

### ISSUE THREAD

**Issue by Tekbr** [Microsoft/vscode#27438]
- VSCode Version: Windows 10
- OS Version: 1.13.0 - insiders -  8c1c1d1 Date 2017-05-29T05:13:44.347Z

Switch from 'Cortar' to 'Recortar'

Just as in the context menu within the file.

![menuptbr](https://cloud.githubusercontent.com/assets/19866231/26549402/48fc2f96-444f-11e7-89bf-4dffccae7aef.jpg)

**Comment by danyeh** [comment]
Repro in insider but it is correct in Transifex. Need more research.

**Comment by Tekbr** [comment]
-- Sorry for the English, I used Google Translator --

@danyeh There are other places that have not yet been translated.

Example:

![pesquisa](https://user-images.githubusercontent.com/19866231/33480624-7df89390-d678-11e7-8eab-d57d8e353ed0.PNG)


There are other places that have not yet been translated.

Example

Can you create a new case to receive possible translation error or is it really a translation error and untranslated locations? Or can we stay in this case anyway?

**Comment by danyeh** [comment]
@Tekbr , it will be great if you can direct fix in Transifex and engage with pt-br community there. Here is how to join: https://aka.ms/vscodeloc. I'll ask my colleague more info of pt-br community and share here if any. 
If there is anything cannot be fixed in Transifex and pt-br community. You are welcome to log separate issue here is VS Code github project so we can pull more resource to investigate.

**Comment by danyeh** [comment]
We will follow up in community localization process in Transifex. Close here.
Thank you for the feedback!
