### ISSUE TITLE
Adopt fileResultsNavigation.ts in more places

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#27458]
Couple of debt issues around this file in `vs/workbench/browser`
* we typically do not talk about files in the core of the workbench (they come in via `parts/files`). if this is a file specific thing it should move into files namespace, otherwise it should be made generic enough that it can work in any viewer (and maybe moved into some place where we have viewer related utilities?)
* I am sure we have more places where we open files on click or things in general, should we adopt this everywhere to have a consistent use?

**Comment by sandy081** [comment]
Agreed to move it under `files` parts. Regarding adopting it in other places, currently this is being reused in following views.
- Search
- Problems
This gives consistent `onFocus` and `onSelect` behaviour while user navigates files in above files. Like, preview the file on focus, open the file to the side on `cmd`+`select`.

We can also adopt/reuse the same in other places like
- Debug
- File Explorer

@isidorn @bpasero

**Comment by bpasero** [comment]
Yeah, makes sense to use it in more places to have consistent picture. Maybe we need to introduce a setting to control if explorer/debug change active file on keyboard navigation. Some people have asked for this.

**Comment by isidorn** [comment]
Makes sense to try to reuse this in the debug land

**Comment by isidorn** [comment]
@sandy081 I am up for looking into this for November, let me know if you disagree and I can remove the milestone

**Comment by sandy081** [comment]
👍

**Comment by isidorn** [comment]
Moving to December and debt week

**Comment by isidorn** [comment]
I have adopted the `FileResultsNavigation` in the `CallStackView`.

I could not adopt it in the `BreakpointsView` since this view uses the `List` as the underlying implementation and the `FileResultsNavigation` only supports the `Tree`. The `List` and the `Tree` have different selection events (keyboard not exposed in the list) so it is not trivial to update the `FileResultsNavigation` to also work with the list.

As for the explorer it is a bit more tricky since it is reacting on selection changes and on the keyborad / click in the controller. I could do a bigger refactoring and try to remove these and only react on selection changes but that will probably break something. Thus I am not very passionate about this.

**Comment by bpasero** [comment]
Yeah looks like there is stuff in the tree (event payload) that would be required in order for the `FileResultsNavigation` to adopt it for the List...sucks.
