### ISSUE TITLE
I find it confusing that the keybindings.json can have mixed OEM and real characters

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#27491]
- VSCode Version: Insider 1.13
- OS Version: Windows

Testing> #27481 

In don't want to make the life for US users harder but the fact that we render OEM and real keys now in the keybindings.json is confusing for non US users. Do the following

- Swiss German layout
- create a keyboard short cut like by entering Ctrl+¨ into the widget
```
{
        "key": "ctrl+oem_3",
        "command": "workbench.action.toggleSidebarPosition"
}
```
- switch layout to US English
- create a keyboard shortcut using the widget entering Ctrl+`. You get
```
    {
        "key": "ctrl+`",
        "command": "workbench.action.toggleSidebarVisibility"
    }
```
- not that the command is different

Observe: At the end both bind to the same key however by looking at the file you don't see this. I would suggest that the key bindings editor (Sandeep) always tries to render the key to produce and the keybindings.json editor always renders OEM keys.

**Comment by alexandrudima** [comment]
The keybindings editor UI always renders keybindings with their physical labels and not with the OEM form (already today).

My operating assumption is the following:
* folks using the US standard keyboard layout are happy and have never complained.
* folks using a different keyboard layout get confused by the serialized form of key codes being their US standard produced character.

My proposed change tries to:
* keep the US standard keyboard layout folks happy
* try to make it obvious for non-US standard keyboard layout users that these are key codes and not produced characters.

I agree this is *unfair* towards the non-US standard keyboard layout users who get the burden of understanding that these are key codes, while the US standard keyboard layout users do not need to care, but I am not convinced by the rationale: if it's complicated for one set of users, then make it complicated for all users. i.e. if the US standard keyboard layout folks (>50%) are happy, why make their lives more complicated if we don't need to?

**Comment by dymo** [comment]
Adding the tooltip to the Default Keybindings is a big improvement. After decades in the dark, I finally know what the equivalent of ``ctrl+=`` is on my keyboard :thumbsup:

But I was only able to do that because I have both April and Insiders build installed so I could compare the default key bindings. If I read some documentation and it tells me to press ``ctrl+\`` then I can no longer go to the "Default Keybindings" and search for it to find out what it is on my keyboard because it has now been changed to ``ctrl+oem_5``. I think it is better to just show the US (feel free to call it standard, international or something like that) layout key – I don’t have a key labelled "oem_5", so that is not really useful information.

As a non-US keyboard user, I think it is actually more unfair that I’m not allowed to see the standard key binding that is referenced in documentation and tutorials everywhere :wink:

If I want to share my key bindings with the world, it worked better before where if I press ``ctrl+ø`` in the widget, then it becomes ``ctrl+'`` and the tooltip tells me that it is different on my layout, where in the Insiders build, it now becomes ``ctrl+oem_7`` and I would not know what to tell non-Danish layout users to press and I suspect that for Norwegian layout users, it would be even more confusing because the æ and ø keys are swapped compared to Danish layout.

A minor detail: ``ctrl+,`` becomes ``ctrl+oem_comma`` and the tooltip tells me that is ``ctrl+,`` on my keyboard (Danish layout).

**Comment by alexandrudima** [comment]
@dymo Since a couple of milestones, the Default Keybindings didn't get the warning annotations due to an accidental bad refactoring, I just noticed myself and fixed it (#27019), sorry about that.

Now, on the topic of how to serialize key codes (to use the symbolic key code name or to use the US labels for those key codes), your comments are in complete antithesis with the discussions I've had with @Tekbr in #27019, where, among many other things, using US labels for key codes was perceived as a bug by @Tekbr.

IMHO, it is great that we expose `keybindings.json` as a human-readable file, but this is also a cause of grief, i.e. most software never exposes their serialized keybindings form to users in a readable format and we've tried to make the UI version of keybinding configuration cover most common use cases e.g. of changing or removing a keybinding.

I am really not sure how to proceed, I'll bring this up with the team in today's standup to get further ideas.

**Comment by alexandrudima** [comment]
On the `ctrl+oem_comma`: the comma key is an OEM key -- https://msdn.microsoft.com/en-us/library/windows/desktop/dd375731(v=vs.85).aspx -- I believe the comment next to it "For any country/region, the ',' key" is false :).

**Comment by dymo** [comment]
@alexandrudima Thanks for the #27019 fix, it is a very good feature and one of the ways VS Code make it a good experience working with the serialized keybindings and why I agree with you that it is a good idea to expose  them.

I think you linked to the wrong issue for the discussion with @Tekbr. I can see how it may look like a bug when it inserts a different key combination than the one you choose in the widget, but I think there are several reasons to keep the existing "standard" key characters:

- They always make sense to US layout users and as you said, they are a significant part of the user base.
- ``ctrl+oem_3`` will make sense to very few users (if any).
- They are useful for non-US layout users when you somebody tells you to press ``ctrl+` `` and you know that is not possible on your keyboard, then it is nice to be able to search for the keybinding and see the equivalent on your keyboard layout.
- If somebody non-Danish ask me how to open the terminal, I already know that it will not help telling them to press ``ctrl+æ``, so it is nice to be able to see that the "standard" is ``ctrl+` `` instead of ``ctrl+oem_3``

Doing keybinding right is hard and I'm not sure there is a perfect solution, but VS Code already have one of the best.

To make this (in my opinion) good feature look less like a bug, I think the solution is to change the way it is visualized. Maybe find a way to show both the "standard" and localized key characters, so you don't have to hover or swap them, so you see the localized key characters and have to hover to see the "standard" key characters.

The first time you open the ``keybindings.json`` file, it just have one line ``// Empty``, maybe there could also be some explanation there.

**Comment by alexandrudima** [comment]
Yes, sorry about that -- #23685 it is. Note that this might be not so bad on some keyboard layouts (e.g. German where the OEM keys produce distinct language characters such as ö or ä etc), but it can be horrible on some other keyboard layouts (e.g. Portuguese - Brazilian):

For example:
* **on the US layout**: the `[BracketRight]` scan code is mapped to key code `VK_OEM_6` and produces `]`
* **on this layout**: the `[BracketRight]` scan code is mapped to key code `VK_OEM_6` and produces `[`.

So if we render `VK_OEM_6` as `]`, the key looks in json as `ctrl+]` while the physical key is labeled `[` and ... there is another physical key labeled `]`... I am confused myself while trying to write this down.

=> my prompt decision to render key codes with symbolic names on non-US keyboard layouts.

---

I cannot do "magic" neither in the default keybindings, nor in the user `keybindings.json`. The place to do magic is the keybindings UI editor where we always render the keybindings in terms of produced character (i.e. localized). In that UI there is no exposure to scan codes or key codes:

> ![image](https://cloud.githubusercontent.com/assets/5047891/26634322/89a39da4-4616-11e7-96ed-71643fdb16dd.png)

---

In the `.json` form we have two constraints: the left hand side and the right hand side must contain parsable JSON with a serialized keybindings form that is valid even when moved to a different PC or when the keyboard layout is changed (since the left hand side is often used for copy-pasting and the right hand side is saved to a file on disk)

So we can't mess with the text to massage it in any way we want. These are, after all, simple json files. Currently we have two major ways to "mess" with the text of a file: code lens style gaps (which would look bad IMHO in this context) and inline decorations. We use today the inline decorations to render an info or an error icon. 

Here I've tried to inline the localized value next to the key codes. It just looks awful IMO, the repetition is highly annoying:
![image](https://cloud.githubusercontent.com/assets/5047891/26634135/ee80adc6-4615-11e7-9d70-d7495dacd627.png)

---

IMHO the only way to get better than the current hover + info/error icon based UI is to build a custom UI, which we have done (the Keybindings Editor UI) and which works correctly and avoids all the mess of dealing with a serialized format that must make sense across keyboard layouts, machines or OSes.

---

I agree with the missing searchability, but that is solved through the Keybindings Editor UI. The problem already exists because one can write keybindings in the form "ctrl+[Slash]" which means ctrl + scan code of slash which will stay put regardless of keyboard layouts.

e.g. in the keybindings.json:
```
{ "key": "ctrl+[slash]", "command": "actions.find"}
```

=> The Keybindings UI can find conflicts (I'm not sure why ctrl+o is matched, maybe @sandy081 knows):

![image](https://cloud.githubusercontent.com/assets/5047891/26635300/a04acd22-4619-11e7-9ca0-e13bdfc03b43.png)

---

To not stir the pot even harder, I will:
* leave the US based labels when the keyboard layout is US (i.e. no change - this is IMHO the most risk free change, otherwise all the US standard folks will file issue asking what these OEM things are :) ).
* use symbolic OEM names when the keyboard layout is not US (i.e. no change - this is painful for us that use a different keyboard layout, but we *know* about the pain from other software and are IMHO more prepared to deal with this).
* add the US based label besides the localized label to the hover (i.e. more information in the hover -- this should help in the communicate with friends case -- or perhaps you can tell the friends about an action name and they can look it up in the F1 list which will always print the localized keybindings).

**Comment by alexandrudima** [comment]
@sandy081 created #27749

**Comment by alexandrudima** [comment]
To the verifier: the change out of this is basically that the hover message contains the US keyboard layout too (to help in the case that the end user reads some keyboard shortcut from online documentation). I did not have the courage to go with OEM keys in the US keyboard layout case (I'm scared of hundreds of question-issues) and I had to go with OEM keys for the non-US keyboard layout case for e.g. Portuguese-Brazilian. 

All in all - e.g.:

<img width="576" alt="screen shot 2017-05-31 at 16 52 52" src="https://cloud.githubusercontent.com/assets/5047891/26638227/e90c9056-4621-11e7-9a0f-a43ad3a94944.png">

**Comment by dymo** [comment]
I knew it was difficult, so I'm not surprised that that it turned out to be even more complicated than I thought 😉 

With the additional challenges and constraints you describe, I think you found a good solution 👍

**Comment by Tekbr** [comment]
-- Sorry for the English, I used Google Translator --

@alexandrudima , thanks for not forgetting the few non-US keyboard users. I'm happy to be part of this group. 😄 


@dymo, yes, @alexandrudima  seems to have made a good solution (I hope he's at Insiders tomorrow). 👍 

As he had told me again, it would be good that this issue (#1240) had more votes. With that many keybinding problem would be solved.

I would like the shortcut, for example `Ctrl + /` to comment, but for me it appears `Ctrl + ;` . I do not even know if this can be a problem for the extensions, can @alexandrudima ?

@alexandrudima , I may be wrong, but would it be nice to mark the issue (#1240) as _**important**_? 🤔  Even though it does not have as many votes, as they said before "there are more users who use US keyboard", this seems like it will take time to be resolved (again I say, I may be wrong), seen by the amount of non-US keyboard user.

**Comment by alexandrudima** [comment]
@Tekbr @dymo VS Code allows for an extension to define (amongst other things) keybinding rules. In fact, we have a couple of extensions which consist entirely of keybinding rules.

e.g. https://github.com/Microsoft/vscode-sublime-keybindings turns all our default keybindings into ones that are similar to Sublime's defaults.

Writing an extension, especially one that only contains keybindings rules is quite straight-forward (a single package.json file will suffice) and we have documented how to write extensions quite well at https://code.visualstudio.com/docs/extensions/example-hello-world

An alternative to waiting for us to implement #1240 (which is an umbrella item -- e.g. ship customized keyboard layouts for DE_GER keyboard layout, for DE_CH keyboard layout, etc. etc.) is to create such an extension tailored to e.g. the Brazilian keyboard layout and then you can publish it to the marketplace and other users of the same keyboard layout might hopefully find it and use it. I'm pretty sure at this point you have a great understanding of how to write keybinding rules and doing them from an extension is not so much different from doing them in your personal `keybindings.json`, except for the fact that you can target multiple OSes. If you don't have access to a mac to try it out, that's ok, ship with them optimized on Windows, and someone else might jump in and fill in the blanks on mac, etc.

So... I would really appreciate if you, our community jumps in and helps a bit on this front since there are so many keyboard layouts and we can get the basics right, but to optimize for each keyboard layout is a time-consuming matter. Just saying... this could be great! :)

**Comment by Tekbr** [comment]
@alexandrudima I think it was not clear what I wanted to say about the extensions !!

What I mean is: someone has written any extension, but when using the extension with the shortcut keys it may not work properly because it is always in US standard.

Example:
User with US keyboard - extension works correctly with combinations of shortcuts.
User with non-US keyboard - extension does not work correctly with combinations of shortcuts.

It was clear? If I can not try to write in another way.

**Comment by alexandrudima** [comment]
@Tekbr - yes, extensions have the same problem as we do w.r.t. #1240

**Comment by alexandrudima** [comment]
To verify, the only change that came out of this discussion is: 

* when using a non-US standard keyboard layout on Windows
* the hovers for the OEM-style keys now includes the US standard keyboard layout equivalent **if it is different**
* e.g.:
![screen shot 2017-06-02 at 12 18 34](https://cloud.githubusercontent.com/assets/5047891/26721817/a6f0bf72-478d-11e7-8ab5-dadaba8cc1af.png)
