### ISSUE TITLE
Nuke TaskGroup

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#27575]
In `vscode.d.ts` there is `TaskGroup` without any usage it should be removed

**Comment by dbaeumer** [comment]
It has usage, but not inside vscode.d.ts. These groups have special meaning in the core. If you for example assign `build` you can trigger the task using Ctrl+Shift+B. Same for test. I defined the other since there are pushes to add a Build menu to VS Code with Build, Rebuild All, Clean, ...

I made this a string so that users can extend these groups. I defined constants so that extensions writers don't mistype them. However since this is now open and we need to differentiate our group from other groups I propose that we start ours with $ and throw is someone assigns an unknown group.

Any objection?

**Comment by jrieken** [comment]
> I made this a string so that users can extend these groups.

How? I assign different string to the `group`-property but how will it manifest in the UI? Will I get a new command to run all `foo`-group tasks?

**Comment by dbaeumer** [comment]
Yes, don't get choked but there are discussion to have an explorer tree extension to render task in various outlines. One would be by group, name, hierarchy, ...

One 'group' people were asking for is linting since it is not always the same as building.

**Comment by dbaeumer** [comment]
Agree that a human readable label needs some contribution then as well.

**Comment by dbaeumer** [comment]
I think a task group with a human readable label would best be contributed via a extension points like menu items or tool bar buttons.

**Comment by dbaeumer** [comment]
Fixed in latest API version
