### ISSUE TITLE
merge conflict: Error in console when opening compare

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#27585]
Testing #27549

- create a file as described in https://github.com/Microsoft/vscode/issues/27288#issuecomment-304138928
- open the dev tools
- click on 'Compare Changes' 

Console says:
`[Extension Host] An error occured while running command merge-conflict.compare TextEditor disposed`

**Comment by chrmarti** [comment]
@jrieken Like in #27584 this is an empty edit that was not used by the editor command. In this case the command opens another editor and that appears to dispose the current editor before the empty edit is applied. Should the empty edit just be ignored in this case?

**Comment by chrmarti** [comment]
(Thanks @pprice for the analysis.)

**Comment by michelkaporin** [comment]
Verifying this got different problem on the same steps. This what happens after 'Compare Changes' are triggered:

![image](https://user-images.githubusercontent.com/2239563/27688813-3ea7e26a-5cdc-11e7-9456-068f62f4a6dd.png)


@chrmarti is it because I simulated merge conflict as in https://github.com/Microsoft/vscode/issues/27288#issuecomment-304138928?

**Comment by chrmarti** [comment]
Can reproduce with an untitled file. Also in 1.13. I'll open a new issue for that.
