### ISSUE TITLE
tasks.json's version property missing "2.0.0" completion proposal

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#27602]
- VSCode Version: Code - Insiders 1.13.0-insider (afe47dc84467b487ce0079ff72f55e7ef4f7ebca, 2017-05-30T10:34:18.253Z)
- OS Version: Darwin x64 15.6.0
- Extensions: none
---

Testing #27471

Steps to Reproduce:

1. Trigger content assist on the version property's value.
2. Only "0.1.0" is proposed.

**Comment by dbaeumer** [comment]
We should add the version to both schemas.

**Comment by dbaeumer** [comment]
I tried to do this but it is not possible since the version is the discriminating factor for the schema and one of types. So if I add both version the schema validator will to swap the schema if the user changes the version field. I will close the issue since adding this to code complete makes it worth. We would need to provide this with a separate code complete provider which is quite some work.
