### ISSUE TITLE
Undoing an emmet expand retains multiple cursors

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#27612]
- VSCode Version: Code - Insiders 1.13.0-insider (c2a17a7929259d3d2643cb3f98478e994a39605b, 2017-05-30T05:12:15.312Z)
- OS Version: Linux x64 4.10.0-21-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.9.3|
|lorem-ipsum|Tyriar|1.0.0|
|sort-lines|Tyriar|1.3.0|
|theme-sapphire|Tyriar|0.2.1|
|vscode-svgviewer|cssho|1.4.1|
|tslint|eg2|0.15.0|
|git-project-manager|felipecaputo|1.3.2|
|md-navigate|jrieken|0.0.1|
|vscode-scss|mrmlnc|0.6.2|
|seti-icons|qinjia|0.1.3|;

---

#27316

Steps to reproduce:

1. Set `emmet.useModules` to true
2. Open a html file
3. Type `.foo`
4. Press tab
5. Press ctrl+z
6. Press tab, notice the tab is not added, instead a cursor appears to get removed
7. Press tab, now the tab is added

**Comment by ramya-rao-a** [comment]
This doesnt happen when I run the emmet extension as an external extension in the stable VS Code.

@jrieken Any chance your work on cursors may affect this?

**Comment by jrieken** [comment]
Yeah, so this is what happens. When typing `.foo` quick suggestions pop up and therefore <kbd>Tab</kbd> inserts the emmet suggestion. Undoing the changes doesn't cancel snippet mode which it probably should. Now pressing tab moves between the (folded) placeholders until to the final tabstop which cancels snippet mode and makes tab function as it should. 

The old stable version this works because we have some sort of tab-expansion not just completions. I'll grab this bug and make sure snippet mode exists when undo'ing to the state before the snippets got inserted
