### ISSUE TITLE
Quick commands fuzzy search doesn't work for text in brackets

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#27636]
- VSCode Version: Code - Insiders 1.13.0-insider (c2a17a7929259d3d2643cb3f98478e994a39605b, 2017-05-30T05:12:15.312Z)
- OS Version: Linux x64 4.10.0-21-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.9.3|
|lorem-ipsum|Tyriar|1.0.0|
|sort-lines|Tyriar|1.3.0|
|theme-sapphire|Tyriar|0.2.1|
|vscode-svgviewer|cssho|1.4.1|
|tslint|eg2|0.15.0|
|git-project-manager|felipecaputo|1.3.2|
|md-navigate|jrieken|0.0.1|
|vscode-scss|mrmlnc|0.6.2|
|seti-icons|qinjia|0.1.3|;

---

#27316

fyi @ramya-rao-a 

![image](https://cloud.githubusercontent.com/assets/2193314/26603245/02b2cfb2-453b-11e7-9581-16a1f4d4ec6a.png)

![image](https://cloud.githubusercontent.com/assets/2193314/26603261/0f8f6b96-453b-11e7-921c-017b7955c0ab.png)

**Comment by jrieken** [comment]
The command palette doesn't use the new fuzzyScore-logic. It maybe should tho

**Comment by bpasero** [comment]
Welcome to https://github.com/Microsoft/vscode/issues/27317

**Comment by alextegelid** [comment]
I've noticed that it does in fact match characters inside parentheses, but won't match them if they're right next to the parentheses.

In my example GIF below you can see the following:
1. Misses to match completely, due to the `inc` being next to the parentheses
2. Matches if I actually type the parentheses
3. Matches if I type words inside the parentheses but aren't next to them

![screen recording 2018-11-13 at 04 23 pm](https://user-images.githubusercontent.com/7058721/48423537-1b42b280-e761-11e8-9b5c-86936f928732.gif)

**Comment by jrieken** [comment]
Thanks you @roblourens
