### ISSUE TITLE
When showing proposals above current line: Show proposals bottom to top

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#27646]
- VSCode Version: Code - Insiders 1.13.0-insider (afe47dc84467b487ce0079ff72f55e7ef4f7ebca, 2017-05-30T10:34:18.253Z)
- OS Version: Darwin x64 15.6.0
- Extensions: none
---

Testing #27315 

When showing proposals above current line: To keep the selected item close to the cursor position, the proposals should be order bottom to top, such that, the selected one is at the bottom where the cursor is:
![screen shot 2017-05-30 at 2 19 38 pm](https://cloud.githubusercontent.com/assets/9205389/26605575/749639b8-4543-11e7-8d2d-19da10baf072.png)

**Comment by ramya-rao-a** [comment]
This is existing behavior, but I agree. I think so too.

Will look into what can be done here, but not for the May milestone.

**Comment by ramya-rao-a** [comment]
@jrieken What do you think of @chrmarti's proposal?

Though initially I thought it would be nice to have the selected item close to the cursor, the change in order can confuse users who would expect alphabetically sorted items (most of the time)

Another idea is instead of changing the order, show selected item and n items before it instead of showing the selected item and n items after it. This way, the order stays, and the selected item is closer to the cursor

**Comment by jrieken** [comment]
> show selected item and n items before it instead of showing the selected item and n items after it. 

Not sure what that means. Changing the sort order seems funky esp when I think about scrolling through the list

**Comment by ramya-rao-a** [comment]
@jrieken Changing the sort order was what @chrmarti suggested.

What I am suggesting is to show
- a
- b
- c
- d (assume this is the current selection)
- e (this is out of view)
- f (this is out of view)

instead of 

- a  (this is out of view)
- b  (this is out of view)
- c  (this is out of view)
- d (this is the current selection)
- e
- f


So that the current selection is closer to the current line

**Comment by ramya-rao-a** [comment]
The same issue has been brought up in the monaco-editor as well.
https://github.com/Microsoft/monaco-editor/issues/560

**Comment by jrieken** [comment]
> d (assume this is the current selection)

This is not very realistic as in most cases the first item is selected. A different item will only be selected when the prefix/language/suggestion has been selected before

**Comment by ramya-rao-a** [comment]
Good point.

I'll close this issue then.
