### ISSUE TITLE
Inconsistent position of keyboard shortcuts in the new menu

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#27669]
Testing #27454

The keyboard shortcuts for `Command Palette` and `Settings` are right aligned but the one for `Keyboard Shortcuts` is not and has brackets.

<img width="289" alt="screen shot 2017-05-30 at 4 48 14 pm" src="https://cloud.githubusercontent.com/assets/16890566/26609756/ddc8caf4-4557-11e7-981c-77eba9f54814.png">

Can we not keep all 3 consistent?

**Comment by isidorn** [comment]
Nice catch however this is simply how we render chords. You can notice that they are rendered the same in the top menu. I am sure @bpasero already has a bug / request for this, but we previously had a discussion in one of our slack channels on how to best render key chords. In the end this is what we decided on due to various limiations electron is imposing on us
