### ISSUE TITLE
Editor: broken font render with UTF-8 text

### ISSUE THREAD

**Issue by jpap** [Microsoft/vscode#27678]
- VSCode Version: 1.12.2
- OS Version: macOS 10.12.5

Steps to Reproduce:

1. Paste the following UTF-8 into a new editor
    ```
    AF,03,7052903,Firing wa Ghārū,Firing wa Gharu,7052903
    AF,03,7052904,Guz̄argāh-e Nūr,Guzargah-e Nur,7052904
    AF,03,7052905,Khinjān,Khinjan,7052905
    ```

2. Observe that the font on line 2 does not keep fixed-width display proportions

**Comment by alexandrudima** [comment]
This appears to be rendered correctly for me, or should this be rendered somehow different?

<img width="440" alt="screen shot 2017-05-31 at 13 57 41" src="https://cloud.githubusercontent.com/assets/5047891/26630960/411cbb68-4609-11e7-9ade-84c952f86e87.png">

**Comment by jpap** [comment]
@alexandrudima, are you on Windows? I see this on macOS:

![screen shot 2017-05-31 at 7 38 05 pm](https://cloud.githubusercontent.com/assets/343842/26662444/b6d60c36-4638-11e7-9c63-ec071d9153a3.png)

**Comment by alexandrudima** [comment]
@jap Thanks for getting back to me. I am also trying on OSX, with default VS Code settings.
![screen shot 2017-06-01 at 08 01 11](https://cloud.githubusercontent.com/assets/5047891/26666494/7deb85b4-46a0-11e7-94bb-a92e5ad99155.png)

Perhaps this reproduces only with a certain font?

I was able to reproduce this in Chrome with the Inconsolata font, but not with the default monospace or Monaco fonts. Perhaps you also use a different font?

https://jsfiddle.net/6g4L3m0j/1/
![screen shot 2017-06-01 at 08 09 59](https://cloud.githubusercontent.com/assets/5047891/26666715/bac7c2c6-46a1-11e7-8173-c898497455f0.png)


Since this reproduces in Chromium, which we use for font rendering, may I kindly ask you that you find an existing Chromium issue or create a new one and link to it here. There is nothing we can do on our side at this time to influence font rendering and correct this. Here is their bugtracker --
 https://bugs.chromium.org/p/chromium/issues/list

**Comment by jpap** [comment]
Ah yes -- I was using "Roboto Mono"; I get the same (proper) font-rendering using the Monaco font.

Thanks for looking into this so quickly!  I'll let you close this issue as you feel.

**Comment by alexandrudima** [comment]
@jpap Thanks for your prompt replies. 

I can only recommend you expand on the jsfiddle I started to also include 'Roboto Mono' and let the Chromium developer know about this weirdness. By them fixing this, very many users and projects will benefit from a fix.
