### ISSUE TITLE
Theming: Add scrollbar.background

### ISSUE THREAD

**Issue by msageryd** [Microsoft/vscode#27688]
Have I missed it or is it missing? I would like to set the color of the scrollbar, but this doesn't seem to be implemented. The slider color is configurable, but not the scrollbar itself.

When I use Monokai Seti (i.e. black editor background) and position a black terminal window to the right of the editor there is no way to separate them visually. It would be great if the color of the scrollbar was configurable, or possibly a border outlining the complete VS Code app.

Link to the theme color reference for scroll bar:
https://code.visualstudio.com/docs/getstarted/theme-color-reference#_scroll-bar-control

**Comment by bpasero** [comment]
There is actually no color for the scrollbar background, we never had a color there.

**Comment by msageryd** [comment]
Great to have this on the feature-request list. Thanks.

Another option that would solve my particular problem would be to draw a line to the right of the scrollbar in the color of **"contrastBorder"**.

**Comment by aeschli** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.
If you disagree and feel that this issue is crucial: We're happy to listen and to reconsider.
Maybe you want to give it a try yourself and provide the feature through an extension or a PR: We're happy to give advise and get you started.
Thanks for your understanding. Thanks for helping and happy coding!
