### ISSUE TITLE
"Screen Reader detected" doesn't go away after closing the screenreader

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#27698]
Related to #27479 

- Open any file in VS Code in Windows
- Start Narrator and use it on VS Code
- "Screen reader detected" is shown in status bar
- Close the screen reader
- "Screen reader detected" is still shown in status bar

**Comment by Tyriar** [comment]
I don't have a screen reader as far as I know on my Windows machine yet it's still there, removing my line/col information, bright green and in my face? As someone who has never used a screen reader on this machine I don't know how to disable the message.

**Comment by alexandrudima** [comment]
@Tyriar your problem is not the same as the one experienced by @ramya-rao-a 

@ramya-rao-a starts the screen reader and then Electron is left with Accessibility mode on. This is something that can be verified in Help > Accessibility Options on the Insiders version.

Your problem appears to be that Electron/Chromium enters accessibility mode even when not using a Screen Reader. Let's continue the investigation into your problem in #27893.

**Comment by alexandrudima** [comment]
This is an upstream issue (possibly within Chromium), and there are no known workarounds that we could implement on our side. This means there is no possible code change for us to do in VS Code sources to improve things. 

To keep the number of issues in our inbox at a manageable level, we’re closing issues that have been on the backlog for a long time but haven’t gained traction or that are not actionable. Thank you for your time and understanding.
