### ISSUE TITLE
TypeScript npm setting: tell user about it

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#27707]
Testing: https://github.com/Microsoft/vscode/issues/27695

I think this message should inform about the possibility of setting the NPM path in settings:

![image](https://cloud.githubusercontent.com/assets/900690/26623860/5d38547a-45ef-11e7-890e-be22a26f4400.png)

**Comment by mjbvz** [comment]
Added blurb about `typescript.npm` at the end of the warning message. Installing NPM is the correct fix for many cases as well. Since the message is now fairly long and may get clipped, we also document  `typescript.npm` behind `More Information`: https://github.com/Microsoft/vscode-docs/commit/07c911b8ed5ef911de56ddd10eafc79bc1fbcc7b
