### ISSUE TITLE
TypeScript.npm setting does not give a warning about missing npm on Windows

### ISSUE THREAD

**Issue by michelkaporin** [Microsoft/vscode#27709]
Testing: #27695

OS: Windows
No warning as in #27707 is appearing for me after adding `const $ = require('jquery')` to a new js file, altough I've followed all prep steps.

**Comment by michelkaporin** [comment]
It seems that it finds npm automatically after I add `require` call. I've removed the following from the PATH variable:
```
C:\Users\t-mikapo\AppData\Roaming\nvm
C:\Program Files\nodejs
%NVM_HOME%
%NVM_SYMLINK%
```
I was using nvm for Windows. I've tested `npm` and `nvm` in the console, and the environment does not find those commands.

Settings related to nvm and typescript are on their defaults. Once I add `"typescript.npm": "C:\random"`, VS Code shows an expected warning.

Have I forgot to remove npm from somewhere else?

**Comment by mjbvz** [comment]
Yes it looks like we are still picking up npm from somewhere. Try running `process.env['PATH']` in the developer console for your VSCode instance to check that actual path being used to resolve npm.

If you are setting the path, make sure you launch code using the command line so that we pick up the updated path. It may be easier to just move/rename npm rather than trying to update the PATH

**Comment by michelkaporin** [comment]
Resolved it by running from the command line, rather than starting from the shortcut.
