### ISSUE TITLE
Cannot click on nodejs built-in modules

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#27712]
Testing #26203

Have a js file with the following:
```js
function fib(n) {
    if (n === 1 || n === 0) {
        throw new Error('Unexpected');
    }
    return fib(n - 1) + fib(n - 2);
}
fib(3)
```

* Start debugging (F5)
* The exception widget shows up at the correct location
* The `module.js` is clickable but it tries to open a file called `module.js` from the workspace instead of opening the nodejs built-in module
* Clicking on `module.js` from the call stack works correctly, so perhaps the debug adapter needs to be asked about how to resolve links in the error stackframe, and only if it doesn't know how to do it, the default should be to fallback to trying to open files?
<img width="565" alt="screen shot 2017-05-31 at 11 00 05" src="https://cloud.githubusercontent.com/assets/5047891/26624160/56a52d30-45f0-11e7-8fd5-0dc765e35784.png">

Other use-cases would be debugging a remote target where the error stack trace would contain the file paths as installed on the remote machine and these file paths would need to be translated according to the debug configuration to the local filesystem, or otherwise opened in readonly mode by fetching their sources from nodejs

fyi @weinand @isidorn

**Comment by michelkaporin** [comment]
https://github.com/Microsoft/vscode/pull/24451#issuecomment-293010725 I mentioned that 
> If file is coming from e.g. <node internals>, it won't be anchored.

Hence, it is as desired. I have discussed that with @isidorn and we agreed that it is not blocking issue. 

Having an agreement with debug adapter on link resolving would be a nice-to-have but it will require debug protocol change, which is an overhead just for link detection. Instead, sending a stack trace by DA in a different format that maps stacktrace links to their full paths would be a better idea, though there some complications as far as I remember from the discussion with @weinand.

**Comment by alexandrudima** [comment]
If the link detection is today string-based, I don't think there's a need to go too far... There's a widget a few DOM nodes away that knows what `module.js` is

![image](https://cloud.githubusercontent.com/assets/5047891/26630484/2d364a3a-4607-11e7-84c0-e697643b1a4e.png)

**Comment by michelkaporin** [comment]
@alexandrudima yes, the link detection is string-based. 

Debug viewlet does a call to DA to retrieve the stack frames, whereas I operate only on the stack trace string returned by DA when querying for exception. To reuse debug viewlet stack frames I would need to match up links from exception widget to the stack frames from the viewlet to maintain consistency. I did not do it because I was amending an already existing implementation of link detection in debug console, not creating a new way to detect links.

Cannot see any problems in implementation there for now, so this could be an option to go for, if @isidorn is OK with that, and we can leave it as a feature request for now then.

**Comment by isidorn** [comment]
I am ok with that, we can sketch up a solution which does not break too much layers in the debug world.
All in all not for the endgame week

**Comment by michelkaporin** [comment]
@alexandrudima yes, the link detection is string-based. 

Debug viewlet does a call to DA to retrieve the stack frames, whereas I operate only on the stack trace string returned by DA when querying for exception. To reuse debug viewlet stack frames I would need to match up links from exception widget to the stack frames from the viewlet to maintain consistency. I did not do it because I was amending an already existing implementation of link detection in debug console, not creating a new way to detect links.

@isidorn great, I will put it in the backlog for now then.

**Comment by weinand** [comment]
VS Code UI should avoid to use a heuristics for matching things across UI elements. It will always break for some case.

E.g. in the C#/C++ world the stacktrace string in the Peek UI can be a nested exceptions where the inner exception originates from some remote server process. In this case the embedded source paths are totally unrelated to the files in the local workspace but might have the same name. Just matching them by name and ignoring their remote semantics will result in confusing situations.

Let's solve this problem via the DAP.
