### ISSUE TITLE
which "build" task is picked if I run the "Run Build Task" command?

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#27719]
Testing #27448:

- in terminal:
  ```
  git clone https://github.com/Microsoft/vscode-node-debug
  cd vscode-node-debug
  npm install
  ```
- open project in VS Code and run "Build Task" command

This works fine but I wonder which task definition is used:

- start the "Run Tasks" action,
- scroll through the list to find three(!) definitions for "build"
- (there really should be four build definitions because task.json has another one which just is not named "build")

There should be a visual cue that flags either the single "build" that is used, or all potential "builds".
In the latter case a picker should be used to select the desired build.

**Comment by dbaeumer** [comment]
The name is actual not relevant. It is whether a task is mark as isBuildCommand in the 0.1.0 version and in 2.0.0 belongs to the 'build' group.

Since in our example there is a 'isBuildCommand' in the tasks.json this one is executed even if you use the 2.0.0 engine which allows you to contribute tasks.

Only if there is no build task marked in the tasks.json I currently execute all contributed build tasks (again doesn't depend on the name it depends on the group) the belong too.

I could imagine to have a picker to let the user pick one. However other users already ask for running n build tasks in parallel. So the picker could have an 'all' entry.

And finally, if the user wants to run 2 out of n contributed build tasks she can create a task.json with something like this:

```
		{
			"taskName": "My main build",
			"dependsOn": ["build one", "build two"]
		}
```

**Comment by irekeri** [comment]
Having the picker with build or test task (or really any group) would be great. For large number of test tasks (due to numerous test executables), the picker would ideally take in text as an input to allow for filtering of the tasks similar to how it filters after typing "task" in the command prompt

**Comment by dbaeumer** [comment]
For June the behavior is as follows:

- If there are more than one test or build task then a picker is shown.
- The user can mark a task as a primary test or build task then that task is executed on run test or run build without user interaction
```json
		{
			"type": "grunt",
			"task": "build",
			"group": {
				"kind": "build",
				"isPrimary": true
			},
			"problemMatcher": [
				"$tsc"
			]
		}

```
