### ISSUE TITLE
Not showing N further errors or warnings

### ISSUE THREAD

**Issue by slifin** [Microsoft/vscode#27723]
![image](https://cloud.githubusercontent.com/assets/198857/26628013/57f40b80-45f4-11e7-889d-ac8efe4ca08e.png)

Seems like there's a hard coded limit in VSCode for the amount of diagnostics that are allowed to be displayed per file, which is 250:

https://github.com/Microsoft/vscode/blob/6bddd906b09a329fb42e5e7397a676d3dc422c2b/src/vs/workbench/api/node/extHostDiagnostics.ts#L19

In Sublime Text I can display all the phpcs violations in this file which ensures all my new code in the file is correct against coding standards but as it is in VSCode I cannot see new errors because of this limit

Is it possible to expose this limit to user settings?

**Comment by jrieken** [comment]
We have put this limit in place for mostly two reasons. The one is performance. Adding diagnostics is one of the few places where extensions have just push lots of data into the system and we have to make sure things stay snappy. The other is usability and we don't believe it is of much value to see hundreds or thousands of diagnostics in one file because users will go through them one by one anyways and each change will trigger a new validation run.
