### ISSUE TITLE
"ctrl+/" matches "ctrl+o" in the Keybindings Editor UI

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#27749]
* On Windows
* write the following keybinding to the `keybindings.json`: `{ "key": "ctrl+[slash]", "command": "actions.find"}`
* in the Keybindings Editor UI
* search for `"ctrl+/"`
* unexpectedly, `ctrl+o` is matched:
![image](https://cloud.githubusercontent.com/assets/5047891/26635715/f2173e00-461a-11e7-95f0-1ce189cddbee.png)

**Comment by sandy081** [comment]
It seems underlying `strings.compareIgnoreCase()` function is returning true for

```
strings.compareIgnoreCase("O", "/")
```

While converting a character from upperCase to lowerCase instead of adding `32` looks like we are subtracting by mistake. Fixed this by changing minus to plus.

Checked that all respective tests are running green

@jrieken FYI

**Comment by alexandrudima** [comment]
Nice!
