### ISSUE TITLE
Callstack shows "VMundefined" when debugging typescript with legacy protocol

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#27769]
#26557

![may-31-2017 11-20-16](https://cloud.githubusercontent.com/assets/323878/26647137/2ea890da-45f3-11e7-938d-228538ed70d9.gif)

I step, then it shows VMundefined for frames after the first one for a second, then resolves to the correct details.

Node 7.8

**Comment by weinand** [comment]
@roblourens I cannot reproduce this when using the node-debug project (or some other smaller samples). Could you make your test program available?

@isidorn any idea why the DA is even called for the frames after the top frame?

**Comment by roblourens** [comment]
I'm debugging the TypeScript compiler with a breakpoint at tsc.ts:149. Sorry that's what I meant by "debugging typescript" :)

**Comment by isidorn** [comment]
Probably a timing issue I can also see it. Here are exact steps

Steps to Reproduce:
1. git clone https://github.com/Microsoft/TypeScript.git
2. npm install, npm install jake
3. jake local
4. set breakpoint in tsc.ts:149
5. Use the following `launch.json`

``` json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch",
            "type": "node",
            "request": "launch",
            "program": "${workspaceRoot}/src/compiler/tsc.ts",
            "stopOnEntry": false,
            "args": ["PATH TO ANY TS FILE"],
            "cwd": "${workspaceRoot}",
            "preLaunchTask": null,
            "runtimeExecutable": null,
            "runtimeArgs": [
                "--nolazy"
            ],
            "env": {
                "NODE_ENV": "development"
            },
            "externalConsole": false,
            "sourceMaps": true,
            "outDir": "${workspaceRoot}/built/local"
        }
    ]
}
```

**Comment by weinand** [comment]
To improve stepping performance VS Code has started to get the stacktrace in two chunks: the first frame immediately in response to the stopped event. And after some delay the rest of the frames and the variables for the first frame.

If the number of variables and frames is large, the node.js backend is swamped by the variable request and fails on returning valid stackframes. This results in the "VMundefined" stackframes.

The fix is to better protect against the failing backtrace request and let the stackTrace request fail instead of returning bogus stackframes.

**Comment by dbaeumer** [comment]
Verfied using the steps from https://github.com/Microsoft/vscode/issues/27769#issuecomment-305504395
