### ISSUE TITLE
ITextFileService#saveAs() should go through textFileEditorModel.save()

### ISSUE THREAD

**Issue by teggno** [Microsoft/vscode#2777]
In an extension, the callback registered in `workspace.onDidSaveTextDocument()` does not get called after  `vscode.window.activeTextEditor.document.save()` has been called when `activeTextEditor.document` is a new untitled document. The "Save As" dialog appears, I enter a filename and click save. The file gets saved (and closed) but the registered callback doesn't get called. Is this intentional behavior?

**Comment by alexandrudima** [comment]
@bpasero Here is what we listen for in `extHostDocuments`:

```typescript
		this._toDispose.push(eventService.addListener2(FileEventType.FILE_SAVED, (e: LocalFileChangeEvent) => {
			this._proxy._acceptModelSaved(e.getAfter().resource.toString());
		}));
```

**Comment by bpasero** [comment]
@jrieken I guess the issue is that the untitled model actually gets disposed when being saved and a new file is being created. I am not sure if I should introduce a new event for an untitled file getting saved, or maybe the existing events are already good to go? We should talk :)

**Comment by jrieken** [comment]
@bpasero Unless there is an issue with reusing the event we should use that and refrain form introducing yet another one. Let's give it a try...

**Comment by bpasero** [comment]
This is actually bigger then expected, postponing to after GA. Updated the summary too.

**Comment by bpasero** [comment]
The change is to let `saveAs()` go through the same code as `TextFileEditorModel.save()` so that appropriate events are being fired. This fixes two issues:
* API listeners will get notified on text document being saved both for untitled documents as well as existing documents that get `saved as` another file
* our save participant can participate and trim trailing whitespace if this is configured for the resulting file

This needs some verification from non-extension-side:
* you can still save untitled files
* you can still save files as another file name
* you do the above both in case the target exists as well if it does not exist
* the UI updates accordingly when the save is done

And from the extension-side
* you get the event for untitled files as well as files that get `saved as`
