### ISSUE TITLE
[theming] extension header background color

### ISSUE THREAD

**Issue by pahen** [Microsoft/vscode#27785]
Can't find a way to do it. Is it possible?

<img width="1205" alt="screen shot 2017-05-31 at 22 56 21" src="https://cloud.githubusercontent.com/assets/353888/26653755/76808582-4654-11e7-9316-09e42946ab62.png">

**Comment by bpasero** [comment]
No currently it is a hardcoded color (though it is using transparency).

**Comment by aeschli** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.
If you disagree and feel that this issue is crucial: We're happy to listen and to reconsider.
Maybe you want to give it a try yourself and provide the feature through an extension or a PR: We're happy to give advise and get you started.
Thanks for your understanding. Thanks for helping and happy coding!
