### ISSUE TITLE
macOS: OS services cannot pick up selected text from editor 

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#27799]
Testing #1628

**steps to reproduce**
- On a mac, open a text file and try selecting a line of text in the editor
- Run the `create sticky note` service. This is under the `code -> Services` menu or can be triggered with `cmd + shift + y`

**Expected**
The selected text in the editor is opened in a new sticky note

**Actual**
Some other text is opened in the new sticky note. I'm not sure where we are getting it from

**Comment by mjbvz** [comment]
@alexandrudima, assigning to you initially as this seems like it may be related to the editor and textinputs/textareas. Feel free to reassign if you think someone else on the team may be the better owner for this

**Comment by wgj** [comment]
I can't even get that far. MacOS Services keyboard shortcut has no behavior, and if I were to highlight text, and use the context menu (by right-clicking the text), the Services menu is not found at all, as if #1628 hadn't been implemented at all.

VSCode 1.16.1
MacOS 10.12.6

**Comment by tgharold** [comment]
On macOS 10.14.1 (Mojave) and the latest VSCode, I see the same issue.

- No Services menu in the right-click when text is selected
- The macOS Code -> Services menu says "No Services Apply"

In Slack, the macOS Slack -> Services menu works fine.  The system menu in Microsoft Teams (Teams -> Services) also works when text is selected.  (Mentioning those two because I they also use Electron.  Neither properly show the Services menu in right-click, but at least the top level menu works.)

**Comment by jgclark** [comment]
Seeing same behaviours as @tgharold as well, on macOS 10.14.5 and latest VSCode (1.36.1).
Frustrating!

**Comment by FlashSheridan** [comment]
As noted in https://github.com/microsoft/vscode/issues/53440#issuecomment-507017517, Services work correctly for text in non-editor fields.  So as a workaround, I enter text into the Find dialog, and select the Code/Services menu item.

**Comment by kevinslin** [comment]
any updates on this? using Version: 1.41.1 on mac 10.15.2 and no services menu anywhere, even for text inside the "find" menu

**Comment by lannyheidbreder-mc** [comment]
@kevinslin There are two issues here: Whether the Services menu appears on right-click, and whether VS Code properly assigns the Services context for selected text.

In the Find/Replace sheet, those text fields do properly set the context, and if you go to the `Code > Services` menu item in the menu bar, any text services you have there will be available and work fine. But this is not true of the actual editor, which of course is where you'd most want to use text services in the first place.

The Services menu item doesn't appear on any _right-click_ menus, no matter what area. But this is a minor, secondary issue compared to the one this ticket refers to, where text services can't be used in editor text at all.

**Comment by lannyheidbreder-mc** [comment]
Any chance of movement on this?

**Comment by codingHippo** [comment]
I would very much like to see this fixed.

**Comment by bbukaty** [comment]
+1 to this issue. I have a nifty little automator service that formats highlighted JSON, but I can't use it at all in vscode :(

**Comment by mtzaquia** [comment]
+1 on this... often causes me to copy stuff to TextEdit, run my service, and paste back into VS.

**Comment by tha-carta** [comment]
+1, I've got some timestamp inspection services I'd like to be able to run as I do in other apps, but can't in vscode.

**Comment by shuckster** [comment]
A little investigation led me to the following:

https://www.electronjs.org/blog/ghost#in-what-areas-should-electron-be-improved

> We would love to see Electron bring the operating system's native spellchecking capabilities to their apps. We're dreaming about a world in which an <input> field receives the same services as a NSTextView, but we are also intimately aware how difficult that is. -February 14, 2017

Also:

- https://github.com/electron/electron/issues/8394

Since VSCode is an Electron App, perhaps the difficulty in supporting Services is that they are not "natively" supported in Electron? The most recent post in the linked issue reads:

> I agree with Kevin's assessment that this is something best implemented on the client side rather than in core. It's still true that decisions are made about this on a case-by-case basis, but sometime soon in the future we can look at enumerating clearer guidelines about what is accepted into core and what's not.

I haven't followed-up on those "guidelines", but it does seem that there's little impetus to provide macOS Services support within Electron core, meaning the VSCode client must do the seemingly very heavy lifting itself.

**Comment by pingren** [comment]
@mjbvz @bpasero

Mac services are available by default on Electron app. I tested Code-OSS and it is also working fine. (You may to change conflict keyboard shortcut settings to use `cmd + shift + y` though). It seems like something goes wrong after VSCode building process.

FYI: The Mac service feature is implemented by Chromium (correct me if I am wrong) on 
https://github.com/chromium/chromium/blob/cd8de1174b3d94cf6692a1255a544865be9af01f/content/app_shim_remote_cocoa/render_widget_host_view_cocoa.mm#L2311

Screencast: Electron app and Code-OSS vs. VSCode Insider

https://user-images.githubusercontent.com/5123601/177935452-88c9e4a8-72e8-4dea-9359-be0099c3f50e.mp4

**Comment by bpasero** [comment]
Yeah I doubt this is something we do wrong within our sources because when I open vscode.dev in Chrome and try this, it actually picks up the text of the editor:

![image](https://user-images.githubusercontent.com/900690/177937855-68a5a2bf-d918-4d16-9e76-89527800c281.png)

If anyone has a clue what could drive this, we are happy for help.

//cc @deepak1556 @rzhao271

**Comment by bpasero** [comment]
This took me the longest time (years) to figure out 😱 , sorry for that. Special thanks to @pingren for the video, which pointed me to the right direction. It turns out that when you have accessibility mode enabled in VSCode, macOS can pick up the selected text from the "Services" menu as well as lookup definition (which https://github.com/microsoft/vscode/issues/31047 was about).

Upon further debugging how the editor works when accessibility mode is enabled or disabled, it turns out that only when you enable accessibility mode (via `editor.accessibilitySupport` setting), the `textarea` element that the code editor keeps in the background will contain the selected word when you select text. macOS services seem to require a valid selection in the `textarea` element to function well (which makes sense because these features require a word selection).

Here is video proof of how the `textarea` behaves when made visible:

**Accessibility mode off**
![Recording 2022-07-30 at 06 34 45](https://user-images.githubusercontent.com/900690/181872514-7f9db723-529e-44f0-9694-146fe6113507.gif)

**Accessibility mode on**
![Recording 2022-07-30 at 06 36 20](https://user-images.githubusercontent.com/900690/181872555-9f396f59-cc02-48f1-9bb7-1c83e3da76d8.gif)

@alexdima @hediet can you clarify the purpose of this, would be nice if the selection could appear in the `textarea` maybe up to a certain maximum. I also wonder why this does not reproduce in web, where we always seem to have a selection?

**Comment by bpasero** [comment]
**Update:** it looks like there is a difference on the computed `AccessibilitySupport` in `textAreaHandler` that drives this:
* desktop: `AccessibilitySupport.Disabled`
* web:  `AccessibilitySupport.Unknown`

And then this has an impact on `getScreenReaderContent` method which will return nothing:

https://github.com/microsoft/vscode/blob/dbae720630e5996cc4d05c14649480a19b077d78/src/vs/editor/browser/controller/textAreaHandler.ts#L227-L228
