### ISSUE TITLE
Wrong operate selection while selecting characters in Korean IME mode

### ISSUE THREAD

**Issue by crom0406** [Microsoft/vscode#27808]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:13:11.413Z)
- OS Version: Darwin x64 16.6.0
- Extensions: none
---

Steps to Reproduce:

1. type korean some characters. ex)한글을입력합니다
2. and select a character in front of cursor 
3. selected character replaced another character. ex)한글을입력합다다

**Comment by alexandrudima** [comment]
@crom0406 There have been a lot of improvements to the way input is handled in the upcoming 1.13 version. Could you please check if this reproduces on the insiders version which contains these fixes -- you can download from https://code.visualstudio.com/insiders

Otherwise, may I kindly ask for more detailed steps (like I would be 5 years old) -- since I don't know Korean. Some examples of kind people that did it in the past e.g. https://github.com/Microsoft/vscode/wiki/IME-Test#windows-korean

**Comment by alexandrudima** [comment]
fyi @rebornix
