### ISSUE TITLE
Emmet unexpected

### ISSUE THREAD

**Issue by svenvNL** [Microsoft/vscode#27878]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-color|anseki|0.4.1|
|npm-intellisense|christian-kohler|1.3.0|
|regex|chrmarti|0.1.0|
|gitignore|codezombiech|0.5.0|
|vscode-svgviewer|cssho|1.4.2|
|vscode-eslint|dbaeumer|1.2.11|
|githistory|donjayamanne|0.2.0|
|gitlens|eamodio|3.5.1|
|tslint|eg2|0.15.0|
|vscode-npm-script|eg2|0.1.9|
|php-debug|felixfbecker|1.10.0|
|php-intellisense|felixfbecker|1.3.0|
|php-pack|felixfbecker|1.0.1|
|vsc-travis-ci-status|felixrieseberg|1.1.0|
|file-icons|file-icons|1.0.3|
|vscode-npm|fknop|3.3.0|
|csstriggers|kisstkondoros|0.1.0|
|vscode-apache|mrmlnc|1.1.1|
|mssql|ms-mssql|1.0.0|
|cpptools|ms-vscode|0.11.2|
|Theme-MaterialKit|ms-vscode|0.1.4|
|Theme-TomorrowKit|ms-vscode|0.1.4|
|debugger-for-chrome|msjsdiag|3.1.2|
|php-docblocker|neilbrayfield|1.2.0|
|vscode-docker|PeterJausovec|0.0.15|
|vscode-versionlens|pflannery|0.18.1|
|material-icon-theme|PKief|2.0.7|
|vscode-css-peek|pranaygp|1.2.4|
|java|redhat|0.5.0|
|vscode-icons|robertohuertasm|7.8.1|
|stylelint|shinnn|0.24.0|
|vscode-csstree|smelukov|0.1.7|
|arduino-vscode|steveyin|0.2.2|
|Seti-theme|TsumiNa|0.0.1|
|babelrc|waderyan|1.0.0|
|twig|whatwedo|1.0.2|
|html-css-class-completion|Zignd|1.2.1|;

---

A fellow student of mine switched to VS Code after having used Atom. He didn't know Emmet exists, so he wasn't familiar with expansion on tab, he expected 4 spaces to be inserted. After his frustration, I guided him in the settings to turn of Emmet.

A solution I am thinking of would be to ask the user if he or she would like to use Emmet the first time a Emmet compatible file is opened. To give a user more context on what Emmet is, it could be useful to show build in extension in the extension view. The message could have a button which opens the Emmet extension page.
An extension page also solves a second concern. In my experience, for a new user it is weird turning self installed extensions off through the extension view and build in extensions trough settings.

Steps to Reproduce:

1. Normal Emmet expansion on tab in an html or php file

**Comment by ramya-rao-a** [comment]
@svenvNL Thanks for reporting this

Emmet today is not implemented as an extension. It is built-in inside VS Code, and so has a setting to turn it off.

We are working on moving away from this tight coupling and move emmet to its own extension.
You can see this in the upcoming release of 1.13 (which you can try in the current Insiders build) after adding the setting `emmet.useNewEmmet` to `true`.

With this, emmet expansion will show up in the suggestion list instead of expanding on TAB.

As for the showing of built-in extensions in the extensions page and the ability to disable them, can you open a new issue?

**Comment by svenvNL** [comment]
@ramya-rao-a,
Thank you for your response, created #27935
