### ISSUE TITLE
Random switch to 4 spaces per tab

### ISSUE THREAD

**Issue by polkovnikov-ph** [Microsoft/vscode#27919]
- VSCode Version: 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b)
- OS Version: Windows 8

## Steps to Reproduce:

Use VSCode for a prolonged period of time with TypeScript sources.

## Result:

VSCode switches from 2 spaces per tab to 4 spaces per tab, and resets only when the whole editor is restarted.

**Comment by sandy081** [comment]
@polkovnikov-ph Do you have any extensions installed? Can you try reproducing it by disabling all extensions?

**Comment by polkovnikov-ph** [comment]
@sandy081 I'm using fresh clean vscode install.

**Comment by alexandrudima** [comment]
@polkovnikov-ph I use VSCode for a prolonged period of time with TypeScript and this does not happen for me.

When you say VSCode switched from 2 spaces per tab to 4 spaces per tab, do you mean this is actively changed in the status bar:

![screen shot 2017-06-06 at 09 10 42](https://cloud.githubusercontent.com/assets/5047891/26817741/11688490-4a98-11e7-8460-a4a96b8224a5.png)

or is this something that impacts e.g. running TypeScript formatting.

Also, please note that there are 3 settings driving indentation settings in VS Code:
![screen shot 2017-06-06 at 09 11 56](https://cloud.githubusercontent.com/assets/5047891/26817771/36d75e04-4a98-11e7-9bc6-902e45f524f2.png)

`detectIndentation` (on by default) means that if you open a file that appears to be indented with spaces@4, the editor will use spaces@4 on that line.

If the indentation cannot be inferred from the file contents (e.g. such as creating a new file), the values of `editor.insertSpaces` and `editor.tabSize` are used as fallbacks.

Do you perhaps have any steps that we could try to reproduce?

**Comment by polkovnikov-ph** [comment]
@alexandrudima 

> I use VSCode for a prolonged period of time with TypeScript and this does not happen for me.

No surprise. Most likely it's a race condition in config reading code. 

> do you mean this is actively changed in the status bar

This actively changes the way indentation on new lines is added, and the way Tab/Shift+Tab work. I've never seen that "Tab Size" label. If it's guaranteed to be consistent with current tab size, then it should've been 4.

> there are 3 settings driving indentation settings in VS Code

The only modified setting is `configurations` in `launch.json`.

> Do you perhaps have any steps that we could try to reproduce?

The best I can help is to recommend reading 69 source files that have something to do with `tabSize` and find a race condition there.

**Comment by alexandrudima** [comment]
@polkovnikov-ph If you use the default settings of VS Code, the explanation is simple, I try to explain it again:

* When opening a file that has *sufficient* indentation, we will *guess* that indentation. e.g. `A.ts`:
```
  function f() {
    console.log('hello world');
  }
```
When the file is opened, VS Code will inspect each line's indentation. The first line has an indentation of 2 spaces, the second an indentation of 4 spaces and the last an indentation of 2 spaces. VS Code will *guess* that the intent is to indent with Spaces@2 for this file.

* When opening a file that does not have *sufficient* indentation, we will fall back to the configured values for `editor.tabSize` and `editor.insertSpaces`: e.g. `B.ts`:
```
function f() { console.log('hello world'); }
```
When the file is opened, VS Code does not find any indented line. It therefore cannot *guess* what the indentation is and use the configured values for `editor.tabSize` and `editor.insertSpaces`. The default is Spaces@4 and you will get Spaces@4 for this file.

> This can be observed in the status bar, together with the other file settings:
![screen shot 2017-06-07 at 08 05 41](https://user-images.githubusercontent.com/5047891/26864383-1ea138e4-4b58-11e7-8669-eac193ad6bdd.png)


It is possible, but I do not believe we have a race condition in the code dealing with indentation or configuration values. It is possible that our guessing code does not work correctly for a particular file. I would like to get such a specific file if possible where the guessing code does not work correctly. This is possible because the guessing code, is ... guessing. There is no defined standard or clear procedure for identifying indentation settings of a file, just heuristics.

IMHO I believe you have suffered from the case of `B.ts`, where you might have opened a **new file** or a file without sufficient indentation and we have defaulted to Spaces@4. The good news is that this can be configured via the settings. If you prefer to indent with Spaces@2, you can configure `"editor.tabSize": 2` such that the fallback values in case indentation guessing fails is Spaces@2.

Please let me know if you have any reproducible steps, again, I don't believe this is related to a race condition, but the file contents. I am open to fixing something, but I need your help to figure out what to fix such that others don't run into this issue.
