### ISSUE TITLE
terminal.sendText not sending text

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#27939]
- VSCode Version: 1.13.0-insiders f9773
- OS Version: MacOS

``` javascript
        let terminal: vscode.Terminal = vscode.window.createTerminal('sendText');
        terminal.sendText(`ls -l`);
        terminal.show();
```
Result: Terminal opens, but `ls -l` is not sent to the terminal.

**Comment by Tyriar** [comment]
@chrisdias I don't think anything has changed here. Was it just a once off or is it reproducing consistently?

**Comment by chrisdias** [comment]
consistent. 

create a new extension using yo code
add the above code to the activate method
run it

**Comment by Tyriar** [comment]
Looking into this now. It seems related to sending immediately after the terminal is created (not about sending when the panel isn't shown/initialized).

**Comment by Tyriar** [comment]
Confirmed this is a regression from 1.12, probably related to fixes done that related to tasks.

**Comment by Tyriar** [comment]
Might be due to https://github.com/Microsoft/vscode/issues/27182

**Comment by Tyriar** [comment]
Due to additional logic that is run in the terminal process via #27182, it appears text is being sent before the process has fully initialized.

**Comment by Tyriar** [comment]
Pushed to `master` and `release/1.13`

**Comment by dalyIsaac** [comment]
I seem to be having a similar problem, but with using [pythonVSCode](https://github.com/DonJayamanne/pythonVSCode/) from @DonJayamanne . Sending text to the integrated terminal (see the full issue [here](https://github.com/DonJayamanne/pythonVSCode/issues/1163)) seems to start before the `& python` command is fully initialized, with the start of the selected code not being loaded into the terminal. 

This occurs using Powershell on Windows 10 (build 16273). It doesn't seem to be a problem when the integrated terminal is set to use `cmd.exe`.

**Comment by chrisdias** [comment]
I'm seeing a problem with the Azure CLI extension on Insiders today as well that may be related.

When I try to execute any command (using cmd+' or ctrl+') I get this error:

![image](https://user-images.githubusercontent.com/1487073/29698418-2b74a476-890a-11e7-90c1-6c6e17411ffa.png)

Here is the command being executed that appears to be failing:

```javascript
        return commands.executeCommand('workbench.action.terminal.runSelectedText', editor);
```

And the location...

https://github.com/Microsoft/vscode-azurecli/blob/0f59292f07f1b449a8e86f9708fff61d090e569d/src/extension.ts#L141

//cc @chrmarti @Tyriar

**Comment by chrisdias** [comment]
I should note, running the command (runSelectedText) from the Command Palette works fine for me.

**Comment by Tyriar** [comment]
@chrisdias passing an editor as the parameter never worked, `this.codeEditorService.getFocusedCodeEditor()` is used to get the editor. Could this have been the issue?

I can't think of any changes recently that would have impacted this.

**Comment by dalyIsaac** [comment]
In pythonVSCode, the command which seems to be failing is [this](https://github.com/DonJayamanne/pythonVSCode/blob/d434e3cd688f2b7f7d75a096d6e155185f66b480/src/client/providers/execInTerminalProvider.ts#L142): 
``` TypeScript
terminal.sendText(unix_code.replace(/\n/g, "\r\n"));
```

**Comment by Tyriar** [comment]
sendText seems to work fine on mac/insiders in the terminal sample https://github.com/Microsoft/vscode-extension-samples/tree/master/terminal-sample

This is the code that triggers it: https://github.com/Microsoft/vscode-extension-samples/blob/522898aa8ea6aa4d6b68d4676315e57b1d40b52b/terminal-sample/src/extension.ts#L29-L34

**Comment by Tyriar** [comment]
@jrieken I just sat at @chrisdias's desk to repro this, the call:

```ts
return commands.executeCommand('workbench.action.terminal.runSelectedText', editor);
```

Appears to work fine the the `, editor` is removed. This must have been put in as a mistake as runSelectedText doesn't receive any arguments, regardless @chrisdias is concerned about this extra strictness (if that is the root cause) may cause some extensions to regress as it worked fine in 1.15.

Feel free to close off the issue if this was as designed.

**Comment by jrieken** [comment]
> Appears to work fine the the , editor is removed.

Sure. That is because `editor` is a complex object that cannot be serialised. The [code](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/node/extHostCommands.ts#L72) for this hasn't really changed in the last 2 years, so I doubt this is a recent change. We cannot be more strict I believe, at most we now surface the error (which I don't know why/how that is). 

@alexandrudima Did we change something in the IPC layer when the JSON.stringify call fails?

**Comment by alexandrudima** [comment]
Nothing has changed from the serialization point of view.

The difference is that the editor instance that is passed on to be sent as an argument to a command (which is totally bogus and a mistake on the extension side of things!) now contains a `_proxy` field, which is now a `Proxy` object and no longer a regular JS object. That makes `JSON.stringify` throw now.

IMHO we have two options:
 - accept that this now throws. This is a mistake on the part of the extension. It should not attempt to execute commands with "live" vs code objects that cannot be serialized. 
   - The code to tweak command arguments (that is in since a long time) would also throw if a circular datastructure was sent over in the past. These extensions we were just "lucky" that an instance of a "live" editor was not a circular datastructure in the past; it calls `extHostCommands.executeCommand` calls `cloneAndChange` which throws for circular datastructures.
  - There could have been any number of other changes (besides the usage of a Proxy) that could have made the editor "live" instance circular.

- make it that we identify when someone tries to execute a command and they pass an object which is "live" or contains a Proxy instance, and then manually ignore / replace with null the Proxy instance such that JSON.stringify does not throw.

@jrieken thoughts ?

**Comment by jrieken** [comment]
I am with you, the code was wrong to begin with. I'd tend to do nothing here and I also don't think that we hit many extensions with this. @chrisdias for final thoughts

**Comment by chrisdias** [comment]
The question is how many extensions may break because of this, and it seems low.  

However, the API says that you can pass in primitives and classes within the API, which would include `TextEditor`, but there is no indication which classes cannot be passed (per Alex, objects that can't be serialized). Also, it states that there are no restrictions when passing parameters to extension contributed commands but from Alex's description above it sounds like it would still fail passing the editor.

![image](https://user-images.githubusercontent.com/1487073/29883835-521fdf5e-8d66-11e7-8b0f-238f619f2df9.png)

I suggest we enhance the docs for the executeCommand API to give a hint if things do fail (e.g. "you can't pass objects that can't be serialized" and perhaps remove "there are no restrictions...") and we change the Azure CLI extension. From there, we watch to see if anything happens.

**Comment by chrisdias** [comment]
https://github.com/Microsoft/vscode-azurecli/commit/815de610e203161d56e4e0e93f27ba54e2167a21

**Comment by jrieken** [comment]
I have clarified the jsdoc comment.
