### ISSUE TITLE
[sass/scss] Go to Symbol with parent selector (&)

### ISSUE THREAD

**Issue by viperfx07** [Microsoft/vscode#27965]
![image](https://cloud.githubusercontent.com/assets/2346614/26752631/dd821350-4897-11e7-8e8a-542a26e12345.png)

- VSCode Version: 1.12.2
- OS Version: Win10 x64

Steps to Reproduce: 

1. see above image for codes
2. press Ctrl + R

It should show
1. .block (correct)
2. .block__element (currently only shows &.element)

**Comment by aeschli** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.
If you disagree and feel that this issue is crucial: We're happy to listen and to reconsider.
Maybe you want to give it a try yourself and provide the feature through an extension or a PR: We're happy to give advise and get you started.
Thanks for your understanding. Thanks for helping and happy coding!
