### ISSUE TITLE
Emmet: Manual resolve

### ISSUE THREAD

**Issue by jens1o** [Microsoft/vscode#27971]
- VSCode Version: Code - Insiders 1.13.0-insider (f977399d58f7b64db35047fafe0c6e59e15f11d5, 2017-06-02T10:54:04.063Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-reveal|evilz|0.0.9|
|php-intellisense|felixfbecker|1.3.0|
|auto-close-tag|formulahendry|0.4.2|
|php-docblocker|neilbrayfield|1.2.0|
|vscode-icons|robertohuertasm|7.8.1|
|Material-theme|zhuangtongfa|2.8.4|;

---
Feature Request: Be able to manual resolve a emmet expression:

See this:
![23f32541-981c-44d5-ab6d-b4445aa9fee5](https://cloud.githubusercontent.com/assets/11234139/26754677/3886ee7e-487f-11e7-8ebf-a1c25a843929.gif)
(Sorry for the bad quality, GitHub somehow is trying to compress the file...)
In this case, after correcting a malformed, invalid expression, I can't force an resolve without need to change something, which is kinda annoying.

**Comment by jens1o** [comment]
This would also be useful when malform hex colors:

1. type in `body[bgcolor="#ffffff"]` (Note there are seven `f`s.
2. Remove the last `f`.
3. Try to get your expression.

**Comment by ramya-rao-a** [comment]
In such cases, if you want to see the expanded value for the corrected abbreviation you can always trigger the suggestion by `Ctrl+Space`

If you are sure of your corrected abbreviation and do not need to see the expanded value in the suggestion, you can run the command `Emmet: Expand Abbreviation` either via the command pallet or using a keybinding.

We are trying to move away from using TAB for Emmet expansions, so I do not suggest using TAB as the keybinding here. Because TAB is meant for indenting. 

In the previous model, emmet was tightly coupled with VS Code, and there was a hacky way of falling back and passing the TAB to the editor when there was no valid emmet expansion. Now that we have emmet as an extension, that kind of fallback is no longer possible.

Also there were many cases where users would use TAB for indenting purposes and emmet would sneak in and expand what ever was typed in.

**Comment by jens1o** [comment]
Okay, thanks. I would love to see this hint in the release notes, so everyone knows about it.

**Comment by ramya-rao-a** [comment]
Yes, I'll make sure to add all of this and more in the release notes
