### ISSUE TITLE
Emmet: Missing possibility to encode/decode an image

### ISSUE THREAD

**Issue by jens1o** [microsoft/vscode#27978]
- VSCode Version: Code - Insiders 1.13.0-insider (f977399d58f7b64db35047fafe0c6e59e15f11d5, 2017-06-02T10:54:04.063Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-reveal|evilz|0.0.9|
|php-intellisense|felixfbecker|1.3.0|
|auto-close-tag|formulahendry|0.4.2|
|php-docblocker|neilbrayfield|1.2.0|
|vscode-icons|robertohuertasm|7.8.1|
|Material-theme|zhuangtongfa|2.8.4|;

---

Steps to Reproduce:

1. Try to encode an image
2. See that there is no command to do so
3. Lookup the manual and recognize this exists: https://docs.emmet.io/actions/base64/

**Comment by ramya-rao-a** [comment]
@mrmlnc did work on this one a while ago
See #9002

But that didn't make it and one of the main reasons was that the dependent version of the emmet module go too big.

@mrmlnc You want to give this another try in the new emmet extension?

**Comment by jens1o** [comment]
@ramya-rao-a Can you elaborate on why this doesn't fit anymore?

**Comment by ramya-rao-a** [comment]
@jens1o As explained in https://github.com/Microsoft/vscode/issues/27978#issuecomment-362984470, there hasn't been any traction on this feature request. Neither in terms of user interest or in terms of PRs from the community.

We can't just use the [Emmet library](https://github.com/emmetio/emmet) that does support this feature because we have moved on to using the newer Emmet modules.

@sergeche Correct me if I am wrong, but I believe there are no Emmet modules currently that can help with this feature. Do you have plans of adding any?

**Comment by jens1o** [comment]
That's a pity. :/

**Comment by sergeche** [comment]
There is such action in Atom: https://github.com/emmetio/atom-plugin/blob/master/lib/actions/convert-data-url.js
Since this action requires user interaction and file access, it should have editor-specific implementation mostly.

**Comment by ramya-rao-a** [comment]
Thanks for the pointer @sergeche 

Re-opening this, if anyone is interested in contributing.

**Comment by jens1o** [comment]
Yeeey.. Thank you!

Unfortunately, I lack of time to get used to the refactored codebase :/
