### ISSUE TITLE
Please support source maps with inlined source code

### ISSUE THREAD

**Issue by jamietre** [Microsoft/vscode#2803]
I have patiently tried to use Babel to produce JavaScript source maps that works with VSCode. 

The latest published version of `gulp-sourcemaps` (1.6.0) doesn't have the ability to produce a correct relateive path from the compiled code to the source file in the `sources` array when your output is in a tree parallel to your source. This made it impossible to use gulp+babel to build maps that worked with VS Code, since it doesn't support inline source code. [So I forked it and fixed it.](https://github.com/Microsoft/vscode/issues/936)

All was well for a while, but now I've come back to the project again, and they no longer work. But I have no idea why - there's no diagnostic about why the source map isn't shown. This is probably my own fault, since I had a feature request to [show native code if source map isn't available](https://github.com/Microsoft/vscode-node-debug/issues/23). Which is great!! Unless you were expecting a source map and didn't get one. Now you just don't see a source map and don't see an error. :(

I have pored over my target files & the `sources` look exactly right. Nothing has changed since I got this working a couple months ago. I've tried messing with `outDir`, I just see nothing wrong. So I am not sure if this is a new bug in vscode, or something I just can't see that I accidentally broke since the last time it worked.

I feel like trying to get nodejs + babel source maps working reliably in VS Code has become a hobby akin to using a metal detector to find gold on a beach. I want it to work so badly, because the debugging experience is so awesome compared to anything else, but I just can't seem to make it work reliably no matter how hard I try.

I think all this would go away if VSCode just supported embedded source code. There's be nothing to get lost, no relative paths to worry about, no concerns about distribution vs. source code heirarchy. It would just work, the way it always does in chrome.

What are the chances this can become a reality?

**Comment by weinand** [comment]
@jamietre VS Code 0.10.8 (available probably today) supports inlined source and includes a fix for https://github.com/Microsoft/vscode-node-debug/issues/23.

But I don't think that inlined source will fix all your problems. Inlined source is helpful if you try to debug generated JavaScript and don't have the source in your workspace. In this case VS Code is now able to show the source (but it won't allow you edit the source). An indication that the source is coming from inlined source is visible in the editor's header:

![2016-01-22 16-24-31](https://cloud.githubusercontent.com/assets/1898161/12920140/b82ccd0e-cf47-11e5-9011-7934ed7fa657.png)


On the other hand, if you have the source in your workspace VS Code will ignore the inlined source und open the source from the workspace (because it is more useful to open the source in an editor where you can actually edit the source).

This means that if you see the inlined source despite the fact that the source is available in the workspace, then you still have a source map issue (and I'm still interested in investigating the problem).

**Comment by jamietre** [comment]
Wow - ask and ye shall receive! Thanks!

I have not been generating inline source code in my source maps, because it has not been supported. I think per our conversation on node-debugger project, my latest issue is simply the "debugger" statements showing the compiled code. I am going to try a few scenarios to be sure there's really a problem and I understand how it manifests and will file a report then.

But generally speaking I'm thrilled inline source code is supported because it just makes things simpler, particularly when debugging code that's in someone else's control.

Thanks for the incredible work on VS Code in the last few months, it's quickly becoming the most valuable tool in my toolbox.
