### ISSUE TITLE
[theme] Icon for linked folders & files

### ISSUE THREAD

**Issue by Dominik-K** [Microsoft/vscode#28117]
It would be nice to display symbolic links in the "File Icon Theme" extensions. The developers from the vscode-icons extension would like to implement the feature when there's an API for it. See vscode-icons/vscode-icons#124 (comment)

Moved from https://github.com/Microsoft/vscode-extension-vscode/issues/63

**Comment by aeschli** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.
If you disagree and feel that this issue is crucial: We're happy to listen and to reconsider.
Maybe you want to give it a try yourself and provide the feature through an extension or a PR: We're happy to give advise and get you started.
Thanks for your understanding. Thanks for helping and happy coding!
