### ISSUE TITLE
Cannot Prepend RegEx Match Group Replacement with a $

### ISSUE THREAD

**Issue by crossan007** [Microsoft/vscode#28146]
- VSCode Version: 1.12.2
- OS Version: Windows 10

Steps to Reproduce:

1. Enter some text in an editor
2. Enter the Find-Replace function (Ctrl-H)
3. Supply a RegEx that matches the entered text.  Ensure to create at least one capture group in the regex
   ![image](https://user-images.githubusercontent.com/11679900/26848653-2b8603f2-4acf-11e7-9346-479de2a4b1ec.png)

4. In the Replace text box, prepend the reference to a capture group ($1) with a $.
   Note that both a literal ```$``` and an escaped ```\$``` do not produce the expected behavior; while the behavior does differ between the methods.
5. Click the Replace button
   * Expected result: The matched text is replaced with the capture group, preceded by a ```$```
    
    ![image](https://user-images.githubusercontent.com/11679900/26848737-7e2e15d6-4acf-11e7-8a97-645f88871498.png)

   * Actual result (Non-escaped ```$```): The matched text is replaced with the literal text ```$1```
    
    ![image](https://user-images.githubusercontent.com/11679900/26848687-58294734-4acf-11e7-94c0-4a82629f8ecf.png)

  * Actual results (Escaped ```\$```): The matched text is replaced with ```\$$1```
    
    ![image](https://user-images.githubusercontent.com/11679900/26848703-62478230-4acf-11e7-87d1-ccba4a130ceb.png)

**Comment by Ragzzy-R** [comment]
is this fixed yet? or atleast a way to do this? I want to find a pattern in  a json with 100k objects and append some data to them.

**Comment by irrationalRock** [comment]
Hi, I'm wondering if this bug is worth looking into. I believe I found why this bug is happening. Looking at the `parseReplaceString` method in `replacePattern.ts`, it seems like vscode uses javascript's rules for regex replace. In javascript's rules(https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace) it mentions that '$$' inserts a $. I believe this would cause $$1 to replace as $1. 

Hopefully this information will be useful.

**Comment by alexandrudima** [comment]
Thanks for looking into it @irrationalRock 

Indeed, the way to insert a literal `$` is to use `$$`, not `\$`.
