### ISSUE TITLE
Codelens Overlapping after Combining Two Lines

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#28153]
- VSCode Version: f977399d58f7b64db35047fafe0c6e59e15f11d5
- OS Version: Mac 10.12 (16A323)

Steps to Reproduce:

1. Set `"typescript.referencesCodeLens.enabled": true` 
2. Open a ts file that has code lenses on two lines next to each other:

```ts
class X {
private z: any
}
```

Place cursor before at the start of second line and delete the new line

**Bug**
The two code lenses temporarily are drawn on top of each other (look at the bit with the `18 references` text in the gif):

![jun-06-2017 14-55-03](https://user-images.githubusercontent.com/12821956/26853822-6afbabf6-4ac8-11e7-9bb2-f644a3ce81a8.gif)

**Comment by jrieken** [comment]
I have changed the behaviour so that a lens disappears when it merges into the line of another, existing lens. The request to recompute lenses will then make it show up again

![dec-11-2017 12-21-08](https://user-images.githubusercontent.com/1794099/33828806-d1f5b9a8-de6d-11e7-88e9-1b61883b0be3.gif)
