### ISSUE TITLE
Add export, import settings

### ISSUE THREAD

**Issue by okian** [microsoft/vscode#2816]
It would be great if we could export all settings, shortcuts, snippets, extensions in one step and import them in another machine.

**Comment by alexandrudima** [comment]
fyi @bpasero @joaomoreno

**Comment by savpek** [comment]
Can this be made way that it actually is integrated with git? 

What VsCode requires to integration may be user to set "git repository for user settings", and whenever user wants they can push changes to github and they can be pulled (syncronized in other locations).

I can currently do this manually because VSCode relies on json files (which is good thing), however some tooling may make this kind of syncronizing killer feature.

Why i propose this is truth that in environments where export/import is made by hand (create file -> import file), that is often actually syncronized hard way (via email for example). Its true that that file can be placed under version control (where it should be), however then cycle is following:
1. Export file to version control location and overwrite existing.
2. Add, Commit, Push etc.
3. Pull etc.
4. Import.
Question is, should this really be that hard?

Git integration makes syncronizing environments between team easy if required (however because workspace settings exist in vscode this may be rare case). If you want to use common settings just use master, if you want to modify it based on master and use it as base, just fork or branch it and merge following changes whenever you want and configure VSCode to use your branch instead.

**Comment by Tyriar** [comment]
Comment so I'm participating.

**Comment by Arrow7000** [comment]
This would be very useful

**Comment by livc** [comment]
How can I export all settings to another machine now?

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/2743

**Comment by sandy081** [comment]
Reopened this to treat this as a separate settings sync request

**Comment by Tyriar** [comment]
@sandy081 but we already have a way of doing this now, why add another way that no one has asked for yet and even fewer people would use now?

**Comment by sandy081** [comment]
@Tyriar Some users asked for it in #2743. I recommended to open new issue instead of polluting the original one. - https://github.com/microsoft/vscode/issues/93572 (Since I did not know this issue already exists).

Now that I have seen this request, I reopened this. We shall not mark this as dup of #2743 as they are different requests.
