### ISSUE TITLE
resourceScheme context does not work in in menu.commandPalette contribution

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#28211]
Create an extension that contributes a command to the commandPallette and uses `resourceScheme` in the when clause:

```json
"menus": {
	"commandPalette": [
		{
			"command": "markdown.showSource",
			"when": "resourceScheme == markdown"
		}
	]
}
```

**Expected**
`markdown.showSource` only shows up in the command palette when you are in a markdown preview

**Actual**
`markdown.showSource` never shows up in the command palette. It seems that the `resourceScheme` context is not supported?

**Comment by jrieken** [comment]
@mjbvz Do you have an editor open? Which one is active?

@bpasero The key is set like so `this.resourceContext.set(group && toResource(group.activeEditor, { supportSideBySide: true }));` and since `HtmlInput` is resource editor input things should work just fine, right?

**Comment by bpasero** [comment]
@jrieken yes, `toResource` [can deal](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/common/editor.ts#L966) with `ResourceInput`. Basically any editor that has a `getResource` method.

**Comment by mjbvz** [comment]
I had an editor with the markdown file and a markdown preview open. The markdown preview was active

Debugging the code, I see `ResourceContextKey.set` is called with the markdown preview document from `titleControl.getEditorActions`. There is also a call to `resourceContext.set` in `explorerView`. This is called when switching between text editors but not when switching to the markdown preview

**Comment by jrieken** [comment]
So, in total there four instances of the `ResourceContextKey`, one for the explorer and one for each of the three editor columns. When opening the command palette we try to evaluate when-expressions against the [active editor](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/quickopen/browser/commandsHandler.ts#L429) but we can only do that with a code editor because that's the only one exposing its context key service. 

@bpasero To fix this we need a way to access the context service of the respective editor group, not piggy-bagging on the code editor widget

**Comment by bpasero** [comment]
PR welcome.
