### ISSUE TITLE
Disable ligatures on current line

### ISSUE THREAD

**Issue by csholmq** [Microsoft/vscode#2823]
In Atom, I use 

```
atom-text-editor::shadow .cursor-line {
  -webkit-font-feature-settings: "liga" off, "calt" off;
}

div.find-and-replace atom-text-editor::shadow .line {
  -webkit-font-feature-settings: "liga" off, "calt" off;
}
```

to disable ligature rendering on the current line and in the `Find and Replace` window. Ligatures are nice to look at, but not to edit while rendered.

Atom :+1: 
![atom_ligatures](https://cloud.githubusercontent.com/assets/1297882/12910099/996ef012-cf07-11e5-9250-73b2e2f914f7.gif)

VSCode :-1: 
![vscode_ligatures](https://cloud.githubusercontent.com/assets/1297882/12910107/b06bf62a-cf07-11e5-9058-6ac202e6e11f.gif)

**Comment by jeanm** [comment]
This would be really great to have. I'm finding it quite hard to work with C++/Rust templates because my  programming font has `>>` and `>>>` ligatures. As a result I cannot see where my cursor is when moving it through the angle brackets. I would almost consider this a bug rather than a feature request.

A slightly different approach to the parent's suggestion would be to disable ligature rendering when the cursor is adjacent to the ligature, or between the characters forming it.

**Comment by csholmq** [comment]
@jeanm Most elegant, if possible.

**Comment by csholmq** [comment]
@alexandrudima Kind of missed the May 2016 milestone :)

**Comment by CoenraadS** [comment]
This can kind of be hacked as an extension. I accidentally discovered how to disable ligatures via a bug in my my extension, but I guess it could also be used on purpose. 

Setting an empty decoration of 1 character width will disable ligatures. However it also probably breaks some other stuff, and seems to shift the selected line 1px to the left. 

I don't want to publish it due to the hacky nature, but if you want to build it yourself you can get it here: https://github.com/CoenraadS/Disable-Ligatures-Current-Line

**Comment by csholmq** [comment]
@CoenraadS your extension solves this issue.
