### ISSUE TITLE
Make it possible to pin working files...

### ISSUE THREAD

**Issue by djanosik** [Microsoft/vscode#2826]
... pinned working files should stay open even if you open or close folder. I have some common files (like `TODO.md`) that I need to reopen every time.

**Comment by bpasero** [comment]
#4429

**Comment by letientai299** [comment]
I don't think this issue is duplicated or somehow could be closed after fixing #4429.

Even for a Project folder, when working with a file, I find myself need to open and check many other files. If we have the __pin tab__ feature, after checking other files, I would like to just press `Ctrl+F4` to close all but the main one. 

There's _Close other_ command on tab context menu, which we could create a key binding, but:
- It doesn't work like multiple pinned tabs.
- Keep pressing `Ctrl+F4` is more intuitive for me. 

Please reconsider this issue.
