### ISSUE TITLE
Dreamweaver-style Find/Replace

### ISSUE THREAD

**Issue by Ngranger** [Microsoft/vscode#28274]
# Feature Request

As a user coming from Dreamweaver 5.5, I've grown used to having a multiline find and replace widget with regex and the ability to search through specific files/folders for certain term(s).  What I'd like is for VS Code to have a similar search capability to Dreamweaver's.

**Comment by wsmelton** [comment]
Unless Dreamweaver changed a good bit since I last used it years ago, I'm pretty sure Code's find and replace is pretty close to the same. Likely only thing missing is the multiline ability for the find/replace fields.

![image](https://user-images.githubusercontent.com/11204251/26957762-af4a0080-4c8c-11e7-8a43-3c07c510b9ea.png)

**Comment by Ngranger** [comment]
![dreamweaver-find_and_replace](https://user-images.githubusercontent.com/28519061/26958352-bd2c2f68-4c8f-11e7-84db-d89393de8016.jpg)

This is the sort of capabilities that I was thinking of in Dreamweaver.

**Comment by wsmelton** [comment]
You can already do the "find in" part. Code only has access to the workspace and therfore searches anything in that workspace.

The extent that I use Code I see no reason for all the other stuff. Most of that is specific to the projects that Dreamweaver supports (websites).

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode/issues/13155
