### ISSUE TITLE
1.13.0 | New Emmet expansion suggestions don't honor emmet.syntaxProfiles setting

### ISSUE THREAD

**Issue by zackkrida** [Microsoft/vscode#28286]
- VSCode Version: 1.13.0
- OS Version: OSX 10.12.5

Steps to Reproduce:

1. Add new setting `"emmet.useNewEmmet": true,`
2. Enter a php file and type any HTML tag
3. The expansion suggestions **do not** appear

**Comment by blukai** [comment]
The same with vue,
With `emmet.useNewEmmet` set to `true` it doesn't work.
```
"emmet.syntaxProfiles": {
  "vue-html": "html",
  "vue": "html"
}
```

**Comment by Shouriums** [comment]
@blukai  yea happened to me too 😢

**Comment by ramya-rao-a** [comment]
Thanks for reporting this.

The feature of mapping a non emmet supported language to emmet supported language is not yet implemented in the new emmet model.

I have added this to the June plan for emmet.

For now, you will have to turn `emmet.useNewEmmet` off to get emmet expansions in any file that is not among the below

'html', 'xml', 'xsl', 'jsx', 'js', 'pug', 'slim', 'haml', 'css', 'sass', 'scss', 'less', 'sss', 'stylus'

**Comment by ramya-rao-a** [comment]
With https://github.com/Microsoft/vscode/commit/1809bb2fc15f8ff4ea52cad60fee2fdb368d66ef the `emmet.syntaxProfiles` setting works as before in the new emmet

**Comment by nanaasumadu** [comment]
@ramya-rao-a 

Can PHP with embedded HTML be added to the supported language list?

**Comment by ramya-rao-a** [comment]
@nanaasumadu Doesnt the below work for you?

```"emmet.syntaxProfiles":{
"php: "html"
}
``

**Comment by ramya-rao-a** [comment]
After enabling the use of `emmet.syntaxProfiles` for both `Emmet: Expand Abbreviation` command and the emmet suggestions, we have seen issues where the suggestions pop up in irrelevant places and tend to get either noisy or are of incorrect syntax (eg: gives html suggestions inside a style block in a vue file)

See #29318 #29185 and #29114

This is because the emmet extension is not aware of embedded languages (case of style blocks in vue files or js code in jsx files) and wrong locations (like <? in php)

Therefore, its best that we leave the decision to trigger emmet suggestions to language specific extensions who know better. 

Conclusion:
- You can still use `emmet.syntaxProfiles` to get `Emmet: Expand Abbreviation` command to give you emmet abbreviation expansions. Bind a keyboard shortcut to it (just not Tab)
- Emmet suggestions will not be showing up for languages which have been emmet enabled using `emmet.syntaxProfiles`
- Language extensions can easily trigger emmet completions by using the `vscode-emmet-helper` module. See https://github.com/Microsoft/vscode/issues/29114#issuecomment-310232680

Thanks to everyone who provided feedback!

**Comment by nanaasumadu** [comment]
@ramya-rao-a 

Emmet: Expand Abbreviation has stoped working for php files in the vscode-insiders build 2017-06-26T05:03:31.319Z.  It was working fine in the build on 2017-06-23.

I still have the following in my settings.json file:

"emmet.useNewEmmet": true,
"emmet.syntaxProfiles" : {
     "php": "html"
}

**Comment by ramya-rao-a** [comment]
@nanaasumadu I was pretty happy when I saw your [comment](https://github.com/Microsoft/vscode/issues/27697#issuecomment-310788597) on emmet working again for you after re-installing the Insiders. 

Looks like we are back to square one. 

The command `Emmet: Expand Abbreviation` continues to work for me in php files

@jens1o Can you give it a try?

**Comment by nanaasumadu** [comment]
@ramya-rao-a  Yes, it was all working until I install the latest build of vscode-insider yesterday.  Is there any way of reverting to the previous build for testing??  I am certain something has changed in the latest build that is causing that.

I have tried on two different Macs with the same result.

**Comment by ramya-rao-a** [comment]
@nanaasumadu I don't think we can go back to a previous version of Insiders.

- Are you referring to the emmet auto complete in php or the command `Emmet: Expand Abbreviation`?
- Does it work with `emmet.useNewEmmet`: `false`?
- Set `emmet.useNewEmmet` back to `true`. Open your dev tools (Developer: Toggle Developer Tools). Go to `Sources` open the file `emmetAction.ts` and add a breakpoint as shown below and run the `Emmet: Expand Abbreviation` command again. Does it hit the breakpoint?

<img width="739" alt="screen shot 2017-06-26 at 3 11 29 pm" src="https://user-images.githubusercontent.com/16890566/27562541-cdbdd30e-5a81-11e7-9a98-66e7c1990e4a.png">

**Comment by jens1o** [comment]
Timezones...

@ramya-rao-a It works for me:

![image](https://user-images.githubusercontent.com/11234139/27570309-809ba4da-5afd-11e7-8eb0-ac5e4062870c.png)
![image](https://user-images.githubusercontent.com/11234139/27570312-87651210-5afd-11e7-9322-87a1d016ce5a.png)
![image](https://user-images.githubusercontent.com/11234139/27570316-8e0793c2-5afd-11e7-945a-ec7d5253f029.png)

**Comment by jens1o** [comment]
However, it is bound to <kbd>Tab</kbd>, but I do not set it to it.

**Comment by nanaasumadu** [comment]
@ramya-rao-a  After setting "emmet.useNewEmmet" to "false" and "true" again, Emmet: Expand Abbreviation" works in my php file.  As mentioned above, tab completion doesn't work. 

If I, however, set "emmet.useNewEmmet" to false, tab completion works.

Emmet auto complete in php doesn't work now when "emmet.useNewEmmet" is set to true.  It was working fine in vscode-insider build on 23/06/17. 

Any ideas??

**Comment by nanaasumadu** [comment]
@ramya-rao-a 

I think this  [issue](https://github.com/Microsoft/vscode/issues/29318) may be what I am experiencing.  I didn't realise that emmet suggestions has been disabled for php and responsibility passed on to the language specific extensions.

Is there a fallback until the extension authors can make their extensions "emmet" aware to call emmet completion provider instead of the emmet extension itself trying to suggest ?  

I think if you can provide a user setting such "emmet.useLanguageExtension" which can be set to true or false as fallback will be good.

Alternatively, are you able to provide vscode-emmet-helper as a VSIX and provide an option for a user to set which language such as "emmet.autocompleteSuggestion": "php" ?

Some of us find the emmet suggestions and completions very useful when working in PHP/HTML mixed environment.

**Comment by ramya-rao-a** [comment]
@jens1o Thanks!

We are definitely moving away from binding Tab to Emmet. See https://code.visualstudio.com/updates/v1_13#_emmet-abbreviation-expansion-in-suggestion-list for more on this.

@nanaasumadu Let's use #29532 to track the option to allow suggestions to show up when the language is not a pure markup or stylesheet.

Meanwhile, please look at #29678 and add your thoughts there.
It is about using a different setting than `emmet.syntaxProfiles` to enable emmet abbreviation in languages other than the ones that are supported by default.

**Comment by nanaasumadu** [comment]
@ramya-rao-a 
I have tested the new setting

` "emmet.includeLanguages": {
        "php": "html"
    },`
but emmet suggestion does not work.

html file
![image](https://user-images.githubusercontent.com/29611833/27629987-7fabac24-5c37-11e7-9b40-d65744349941.png)

php file
![image](https://user-images.githubusercontent.com/29611833/27630039-a6aaa7a8-5c37-11e7-993e-b1aa54891e1a.png)

"Emmet: Expand Abbrevation", however works.

**Comment by jens1o** [comment]
As far as I interpreted the code, this is by design.

**Comment by ramya-rao-a** [comment]
@nanaasumadu Am using #29532 to track the suggestions for languages that are not pure markup or stylesheet

**Comment by nanaasumadu** [comment]
@ramya-rao-a  Sorry about that.  I have copied my comments to [#29532](https://github.com/Microsoft/vscode/issues/29532) for completeness.

**Comment by ramya-rao-a** [comment]
No problem at all
