### ISSUE TITLE
Use WSL Git as integrated VSCode Git

### ISSUE THREAD

**Issue by MarcAurel** [Microsoft/vscode#28315]
I would like to use WSL Git with VSCode instead of Git for Windows to avoid multiple Git installations.

WSL is my default terminal in VSCode, but the integrated Git in VSCode doesn't work with WSL out of the box. I tried to emulate the `git.exe` comportement with a simple bat file redirecting git commands in WSL. It works nicely in CMD, but not as the integrated Git in VSCode...

**settings.json**:
```json
{
    "git.path": "D:\\tools\\git.bat",
    "terminal.integrated.shell.windows": "C:\\Windows\\Sysnative\\bash.exe"
}
```

**git.bat**:
```bat
@echo off
bash -c 'git %*'
```

Any idea to make VSCode integrated Git working with WSL Git ?

VSCode: 1.13.0
Windows: 10.15063.296
WSL: ubuntu 16.04
Git in WSL: 2.7.4

**Comment by CherryDT** [comment]
May I add that this can be relevant not only to avoid multiple installations and possibly keeping versions in sync but also when scripts are involved such as pre-commit hooks which do a `npm run something`.

We worked around this in am ugly way by having all npm scripts go through a special `ensure_linux.js` which invokes bash.exe instead of directly calling node if it detects that it's running from Windows.

**Comment by joaomoreno** [comment]
#13138

**Comment by gdw2** [comment]
@joaomoreno , is this really resolved? I've got WSL bash integrated, but git still doesn't work.  Are the special steps to getting VSCode to recognize the WSL git?

**Comment by joaomoreno** [comment]
@gdw2 #29812
