### ISSUE TITLE
Allow changing the selection using the TreeDataProvider

### ISSUE THREAD

**Issue by orta** [Microsoft/vscode#28338]
- VSCode Version: 0.13.0
- OS Version: macOS 10.12.x

Steps to Reproduce:

1. Write an extension that uses the TreeDataProvider API to show a UI
2. Desire to be able to set the selected state programatically

I built an extension ( more details are in https://github.com/Microsoft/vscode/issues/28325 ) and in doing so, I really started wanted to be able to set the selection state programatically.

**Comment by mike-lischke** [comment]
Any chance we get this in a soonish timeframe? The custom view (TreeDataProvider) interface exists now for while but is still very limited (no formatting, no tooltips, no per-node icons, no programmatic interaction like this selection change, expand state, checkbox, no columns etc.).

Extension writers could do a lot of cool things if we would be given the necessary APIs. Since these views are a major navigation element in vscode, I think they should get much more love from the vscode dev's side.

**Comment by sandy081** [comment]
@mike-lischke 

`TreeDataProvider` api supports icons for nodes. May I know what do you mean by per-node icons?

Also Can you please elaborate about fomatting request?

**Comment by mike-lischke** [comment]
Well, it's pretty easy. A good start would be to give us all the possibilities that the file tree has:

1) It has icons per file type (hence per-tree-node-icons). We want that too.
2) It has colors for text, also a want-to-have. Markup support, like we have for tooltips in the code editor, would be awesome. 
3) We need to show additional informations per node with a tooltip (at least long text should be shown there).
4) We must be able to select nodes (yes: multi selection) per code and read out the current status.
5) Check box support is also a pretty common requirement.
6) Multi column support is something I need as well. Could be used to show grid like list of entries. This content:

![tokens](https://user-images.githubusercontent.com/2398704/35872645-a471c482-0b67-11e8-825b-46027fc40bd6.png)

would then show much nicer. All the individual values nicely aligned.

**Comment by mike-lischke** [comment]
I guess my list should go to #27823. Then we could close this issue here.

**Comment by sandy081** [comment]
This issue considers only the API for programatically selecting tree items. I would request to create separate/different issues for each of the requirements/bugs, otherwise it will be difficult to track and am afraid that some of the requests are lost. Thanks for understanding.

I am working on a proposed API for this which will be available for authors to try out in this iteration and the plan to make it available in main API is in next milestone.

**Comment by sandy081** [comment]
@orta This request is similar to the issue #30288. Is it ok, if I make this as a dup of #30288 as there is some conversation happened there?

**Comment by orta** [comment]
Yep 👍
