### ISSUE TITLE
Show Suggestions and Hints in a fixed location instead of in a pop-up near the cursor

### ISSUE THREAD

**Issue by radix** [Microsoft/vscode#28410]
This is a feature request for a new user interface component which is responsible for showing and interacting with Suggestions and Hints.

Currently, a user has two options for interacting with Suggestions and Hints: have them pop-up automatically as they type, or to trigger them manually with a keystroke (excepting a [bug](https://github.com/Microsoft/vscode/issues/28393) for Hints).

There are problems with both approaches, and I believe there could be a happy compromise between the two. First, the simple problem with *manual* triggering is that it takes extra effort to get the information that a programmer wants. Ask anyone who relies a lot on auto-suggestions or hints and they will tell you how useful it can be to *always* have this information on their screen, with no extra effort on their part.

However, there are problems with the auto-suggestions:

* At the most basic level, they can be visually distracting with constant movement in a variable part of the screen
* They can cover up other code that you'd like to be able to see while you're typing
* They also often take control of various keyboard inputs, though in most cases this can be disabled.

I think it would be great to have a panel (say, taking up a portion of the left sidebar, at the bottom, underneath the Explorer/Search/SCM/etc content), which stays in a fixed position on the screen and displays this context-aware information, without covering up any of the Editor.

This feature request is filed due to my own interest and the recommendation of @mjbvz at https://github.com/Microsoft/vscode/issues/28380#issuecomment-307544736.

**Comment by joaomoreno** [comment]
Having this information in a fixed screen position will result in a much worse experience in my opinion, since the user's eyes will need to constantly move around to be able to process it.

cc @stevencl

**Comment by stevencl** [comment]
Thanks for the feedback. From the other issue it looks like you were able to get the settings to disable suggestions. From this issue, it sounds like the problem you are trying to solve is that the suggestions list sometimes obscures some code you need to read. Is that correct?

If so, I don't think that this suggestion would successfully solve the problem of the suggestion list obscuring the code as it would introduce additional problems. As Joao suggests, it would be inefficient and annoying to have to look to a different part of the screen to see contextual information about the code the user is interacting with.

Many, many years ago we had something like this in Visual Studio (https://msdn.microsoft.com/en-us/library/aa302022(v=vs.71).aspx). It was called the dynamic help window and worked as described in the suggestion. It suffered the problem that Joao highlighted but almost even worse, many users complained that when they weren't paying attention to the dynamic help window, it was very distracting because they kept on seeing some flickering in their peripheral vision as the content in the window updated while the cursor moved around the editor.

We learned from this experience that contextual information is much more useful and valuable when it is positioned closer to the object it is relevant to. Now, we always strive to put information as close to the point of attention as possible.

There could be other ways to solve the problem of the suggestion list obscuring code underneath it (e.g., holding down a modifier key while the suggestion list is visible could make the list transparent).

**Comment by radix** [comment]
Yes, I have turned off the suggestions and hints for two reasons: they cover up code, and they sometimes take over keyboard input (I believe that it still may be impossible to disable the behavior of the Hint pop-up taking over the up and down arrow keys when there are multiple Hints available). 

I understand that for people who *like* the code popups, this suggestion sounds bad. But for those of us who can't tolerate them, this would still give us some of the benefit.

I wonder if the Hint and Suggestion systems are hookable enough to implement this idea as an extension.

**Comment by radix** [comment]
Oh, and it case it wasn't clear from my original post, I am not suggesting that the default Hint and Suggestion display use a fixed area, only that it be possible to change this behavior as a configuration setting.

**Comment by stevencl** [comment]
I'm going to close this for the moment given the discussion above. I think that there might be other ways of solving the problem of intellisense obscuring the code without changing the position. Looking into whether or not the original suggestion could be implemented via an extension as suggested by @radix seems worthwhile too.
