### ISSUE TITLE
emmet.triggerExpansionOnTab is not working

### ISSUE THREAD

**Issue by tklepzig** [Microsoft/vscode#28413]
- VSCode Version: Code - Insiders 1.14.0-insider (4541e70733f110ada8d0b4266bc922565d74950a, 2017-06-09T05:11:14.033Z)
- OS Version: Linux x64 4.8.0-52-generic
- Extensions: no extensions (I disabled all my extensions)

- Settings:
~~~
{
    "window.zoomLevel": 1,
    "editor.fontSize": 14,
    "editor.tabCompletion": true,
    "editor.quickSuggestions": false,
    "git.autofetch": false
}
~~~
---

Steps to Reproduce:

1. Create empty HTML file
2. Write `div` and press `Tab`

Expected Result: `<div></div>`
Actual Result: `div ` -> only a space character is added

**Comment by NinoFloris** [comment]
It does work if you tab the autocomplete widget result, but this does not popup in other emmet supported languages like handlebars

**Comment by ramya-rao-a** [comment]
In the insiders, we have set `emmet.useNewEmmet` to `true` by default to give the new emmet model more test coverage.

See https://code.visualstudio.com/updates/v1_13#_emmet-abbreviation-expansion-in-suggestion-list on how the new emmet model is different and why we are moving away from using `tab` for emmet.

Since you have `editor.quickSuggestions` turned off, you can try one of the below options to get Emmet expansion.
* Manually trigger the suggestion by pressing `kb(editor.action.triggerSuggest)` and then choose the expansion from the suggestion list
* Run the command **Emmet: Expand Abbreviation** explicity.
* `kbstyle(Tab)` key will no longer expand the abbreviation by default in the new model. Bind a keyboard shortcut for the command **Emmet: Expand Abbreviation** and use it.

Feel free to log any issues you see in Insiders while using emmet.

#27697 is tracking known current issues.

**Comment by tklepzig** [comment]
Ok, thank you, I wasn't aware of this. I'll try to trigger the expansion manually, maybe it's only a question of familiarization.

**Comment by ramya-rao-a** [comment]
Yes, it will take a while for emmet users with `quicksuggestions` off to get used to the new model. We'll get there :)

**Comment by tklepzig** [comment]
#28556

**Comment by tklepzig** [comment]
I have just another question to this topic :), see #28556
