### ISSUE TITLE
Text trembling while scrolling

### ISSUE THREAD

**Issue by kutsokon** [Microsoft/vscode#28439]
- VSCode Version: 1.13.0
- OS Version: macOS Sierra 10.12.5

Steps to Reproduce:

1. Open any file in vscode
2. Scroll slowly by touchpad
![jun-11-2017 03-27-05](https://user-images.githubusercontent.com/6324101/27007283-7595a72e-4e56-11e7-8565-2d804b5e5592.gif)
Not sure if it's really a bug or a result of approach but for me is really annoying. Haven't seen any such kind of bug in other editors (including Atom which is also made with electron). So, scrolling is not really smooth. The lines go up one by one increasing and decreasing spaces between them.
The last thing that I hate in vscode:)

**Comment by burknator** [comment]
Same here, same versions too. Not sure if this was the case with previous version of Code.

**Comment by alexandrudima** [comment]
@kutsokon @burknator Can you please share your settings? Are you perhaps using `workbench.zoomLevel` in your settings ?

**Comment by kutsokon** [comment]
@alexandrudima @burknator Yes, actually I've been using it, so now I set it "window.zoomLevel": 0 and it fixes my problem. I think it's still an issue for people who uses "window.zoomLevel": 0, but I close this topic

**Comment by burknator** [comment]
@alexandrudima @kutsokon Yes, I've been using it as well with a value of `-0.8`. Setting it to `0` fixes the issue. Is there any chance that this will be fixed? Because I really like it that way.

**Comment by alexandrudima** [comment]
AFAIK when using zoom level `-0.8`, the zoom factor computed by Chromium is `Math.pow(1.2, -0.8) = 0.8642810744472068` so every single coordinate or size is multiplied by `0.8642810744472068`.

Let's assume you've configured VSCode with a line height of 18px. It doesn't matter that all our coordinates are integers, since they will get multiplied by the zoom factor when transformed to screen coordinates. That gives the following positions for the first few lines:

| Line number | CSS Top | Screen Top | Screen Top Rounded | Screen line height |
|---|---|---|---|---|
| 1 | 0 | 0 | 0 | 16 |
| 2 | 18 | 15.557059340049722 | 16 | 15 |
| 3 | 36 | 31.114118680099445 | 31 | 16 |
| 4 | 54 | 46.67117802014917 | 47 | ... |

So this already shows the perils of `workbench.zoomLevel`. No other editor offers `workbench.zoomLevel` in the way we do, and every chance I get I try to push our team into removing it, but I meet too much resistance.

I wonder why customizing `editor.fontSize`, `editor.lineHeight` would not be good enough to get the perfect feel. I personally never use `workbench.zoomLevel` unless I'm using a projector and I need to demo something. I cannot stand the inherent non-pixel perfection of `workbench.zoomLevel`.

**Comment by philkunz** [comment]
But this odd trembling behaviour is definitely new, also noticing it... And if it is the fault of Chromium it should be the same when using zoom in Chrome itself, shouldn't it?

**Comment by alexandrudima** [comment]
@philkunz If there is no problem in Chrome 59, then the editor at https://microsoft.github.io/monaco-editor/ should not tremble. In this case, once we update to Chromium 59 we won't have a problem either.

**Comment by alexandrudima** [comment]
Here is a jsfiddle that should further demonstrate the problem in Chrome:

https://jsfiddle.net/xx7vqyu0/

You might need to tweak the HEIGHT and the DELTA to generate weirdness, based on the zoom level of the OS and the zoom level of Chrome. Here it is with Windows set to 125%:

Notice how all elements are defined with equal height, yet they don't up having equal height in screen pixels:

<img width="444" alt="screen shot 2017-06-15 at 15 40 58" src="https://user-images.githubusercontent.com/5047891/27184074-30eeaf38-51e1-11e7-9af0-ef667c55828f.png">

**Comment by philkunz** [comment]
@alexandrudima yes, I see the scaling effect. However **scrolling should be independent from initial structure to pixel painting**. Chrome does not repaint when scrolling, if there is no reason to do so (like position absolute in the same rendering layer).

And as expected https://microsoft.github.io/monaco-editor/ looks totally fine in latest Chrome when scrolling at any zoom level on Mac OS X.

**Comment by burknator** [comment]
@alexandrudima I hear you, sounds annoying. Funny thing though, I use that setting only to reduce the UI elements' size. I set `window.zoomLevel = -0.8`  and then make the editor text bigger with `lineHeight` and `fontSize` settings. I understand if you hate me now.

Maybe there's a way to implement a different setting which controls the UI elements' size? Or is there already such a thing? I couldn't find one...

**Comment by philkunz** [comment]
It should be a problem of some weird CSS in vscode forcing weird repainting or something. Else the rule is: If you scroll a pixel, you scroll a pixel, no matter what the initial scaling factor might be.

**Comment by niv** [comment]
> I wonder why customizing editor.fontSize, editor.lineHeight would not be good enough to get the perfect feel. I personally never use workbench.zoomLevel unless I'm using a projector and I need to demo something. I cannot stand the inherent non-pixel perfection of workbench.zoomLevel.

I'm seeing the text jitter too, but please don't remove zoomlevel. On my setup, the UI is way too disrespectful of screenspace. I set it to -1 so I can actually fit other things besides vscode on my screen.

+1 on: Could it maybe be done that the UI could be scaled separately without affecting the text view rendering?

**Comment by alexandrudima** [comment]
There is at least an issue to allow customizing the font size of the workbench. Please upvote in #519 . 

Otherwise, you can customize and remove almost all of our UI: the bar where the viewlet icons are rendered can be removed, the status bar can be removed, the menu (on Windows) can be removed, the window chrome can be removed (zen mode).

**Comment by alexandrudima** [comment]
This is an upstream issue (possibly within Chromium), and there are no known workarounds that we could implement on our side, **short of removing window.zoomLevel entirely**. This means there is no possible code change for us to do in VS Code sources to improve things. 

To keep the number of issues in our inbox at a manageable level, we’re closing issues that have been on the backlog for a long time but haven’t gained traction or that are not actionable. Thank you for your time and understanding.
