### ISSUE TITLE
Downloading ripgrep failed: Error: API rate limit exceeded

### ISSUE THREAD

**Issue by torn4dom4n** [Microsoft/vscode#28434]
Hi! I cloned `vscode` and tested it on Appveyor. It always fails in [log.txt](https://github.com/Microsoft/vscode/files/1219872/log.txt)
. How can I fix that? I can see same issues at:
https://ci.appveyor.com/project/VSCode/vscode/build/1.0.19109
https://ci.appveyor.com/project/VSCode/vscode/build/1.0.18033
https://ci.appveyor.com/project/VSCode/vscode/build/1.0.19109

**Comment by CherryDT** [comment]
Skipping optional dependencies is normal, that's why they are optional (fsevents is used only on Mac). 

It rather seems to be an issue with ripgrep:

```
npm ERR! vscode-ripgrep@0.0.12 postinstall: `node ./dist/postinstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vscode-ripgrep@0.0.12 postinstall script.
```

**Comment by roblourens** [comment]
`Downloading ripgrep failed: Error: API rate limit exceeded for 74.205.54.20. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)`

The other errored builds aren't from the same issue, because we set an API key. I wonder whether we should host the ripgrep binary somewhere besides github.

**Comment by roblourens** [comment]
Recommended workaround: produce an API key, set the `GITHUB_TOKEN` environment var, and vscode-ripgrep will pick it up.
