### ISSUE TITLE
error with pre-commit

### ISSUE THREAD

**Issue by stonelee** [Microsoft/vscode#28520]
- VSCode Version: 1.13.0 
- OS Version: OS X EI Capitan 10.11.4

Steps to Reproduce:

1. install pre-commit
2. commit with Source Control in VSCode

will show the error: Git: /Users/lxd/test/vscode/node_modules/eslint/node_modules/strip-bom/index.js:2

![image](https://user-images.githubusercontent.com/571863/27034799-a79efd86-4fb1-11e7-9782-caee17a3fb56.png)

But when I commit in the terminal, It's ok.

why vscode lint in the node_modules? I try to add `.eslintignore` and add `eslint --ignore-path .gitignore file.js`, but still helpless

I create a project that show the case: https://github.com/stonelee/vscode-pre-commit-error

**Comment by dbaeumer** [comment]
@stonelee this is not VS Code limiting. It is eslint trigger by the git hook. I am pretty sure that the same error appears if you lint in a terminal. To test this can you run eslint in a terminal to see which errors it produces. 

I will close the issue since this is not related to the eslint support provided by VS Code. If you have questions you can still ping me in this issue.

**Comment by stonelee** [comment]
in terminal, It's ok

![image](https://user-images.githubusercontent.com/571863/27222291-46f2c98a-52be-11e7-90eb-134bd291b032.png)

use Source Control in VSCode, error happens

![image](https://user-images.githubusercontent.com/571863/27222312-5bc7191a-52be-11e7-9caf-d9c503669afb.png)

**Comment by dbaeumer** [comment]
Reopening

@joaomoreno assigning to you since this is running eslint (the npm module) in a pre commit hook. It behaves differently when executing git from the terminal or from withing VS Code. Which cwd is git using when executing the pre commit hook from within VS Code. This could be a source of the problem.

**Comment by joaomoreno** [comment]
@dbaeumer It's using the same cwd.

**Comment by stonelee** [comment]
Process Hacker seems only run in windows, but mine is mac

**Comment by joaomoreno** [comment]
Use `htop` then.
