### ISSUE TITLE
Exceptions not working properly

### ISSUE THREAD

**Issue by RenaudThoraval** [Microsoft/vscode#28536]
- VSCode Version: 1.13.0
- OS Version: macOS Sierra 10.12.5 / Windows 10 Enterprise 1607

**Steps to Reproduce:**

1. Open a .NET Core project (reproduced with .NET Core 1.1)
2. Add a line which causes an exception (division by 0 for example or even `Debug.Assert(false)`)
3. Run the code in debug

**Expected behaviour:**

Visual Studio Code breaks on the line and display exception, as in previous version.

<img width="1409" alt="exception_break_ok" src="https://user-images.githubusercontent.com/16089684/27039733-1914d67a-4f8f-11e7-94c7-73c8ed5e7669.png">

**Actual behaviour:**

Visual Studio Code breaks but doesn't show the line and the exception. The debug panel remains empty for every thread.

<img width="1420" alt="exception_break_ko" src="https://user-images.githubusercontent.com/16089684/27039740-218155cc-4f8f-11e7-8a4a-a0b85c5b7c63.png">

I reproduced this bug also on latest Insider version (1.14.0). I also reproduced it on a fresh install with only Omnisharp extension (ms-vscode.csharp) in 1.10.0, 1.11.0-beta and 1.9.0 to be sure that it's a Visual Studio Code issue.

**Comment by ramya-rao-a** [comment]
@RenaudThoraval C# debugging is implemented by the C# extension. The extension owners will be able to specify if the issue you are seeing is due to the extension or VS Code.

**Comment by ramya-rao-a** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#1564

**Comment by RenaudThoraval** [comment]
@ramya-rao-a As I said in my post, I tested with previous version of C# extension and the future one in beta and I still reproduce the bug.
I made a clean install of VS Code 1.12.2 on MacOS and Windows 10. The exception works fine, as expected. But as soon as I update VS Code in 1.13, the bug reappears. I think it related with changes in VS Code extension API or something like that. 
I hope that C# extension owners will find a fix.

**Comment by ramya-rao-a** [comment]
@RenaudThoraval Sorry, it wasnt clear from your earlier message if this was a regression from VS Code's side.

**Comment by ramya-rao-a** [comment]
cc @gregg-miskelly from the C# extension side to help out with the investigations here

**Comment by RenaudThoraval** [comment]
@ramya-rao-a No problem ;) I'm not fluent in english so excuse me for all the mistakes I write. I stay tuned if you need more information. I'll do my best to help you in the debugging process.
Regards !

**Comment by isidorn** [comment]
The issue here is that we are now fetching callstacks in two requests, first the top call stack then the rest.
This case reveals an issue when another thread stops in between the first fetch and the rest. In this case we wrongly fetch the top stack frame for both threads, instead of fetching the full call stack for one of the threads, and leaving the other to be lazily fetched when needed.

My fix should take care of this, however I can not verify due to the handshake so I triggered an unreleased insiders build to verify if all is good now. @gregg-miskelly please send me the private dot net debugger so I no longer get pestered by this in the future

fyi @weinand as this is potentially a candidate. Bottom line: multi threaded debugging sometimes shows incomplete stack frames.

**Comment by isidorn** [comment]
I just verified the fix is good.

**Comment by RenaudThoraval** [comment]
Thanks @isidorn for the fix !

**Comment by isidorn** [comment]
Here's an example for which I could repro the issue and which we can use to verify

```c#
using System;
using System.Threading;

namespace dotnet
{

    class Program
    {
        static void Main()
        {
            Thread thread1 = new Thread(new ThreadStart(A));
            Thread thread2 = new Thread(new ThreadStart(A));
            thread1.Start();
            thread2.Start();
            thread1.Join();
            thread2.Join();
        }

        static void A()
        {
            Thread.Sleep(100);
            String.Format(null, 12);
            Console.WriteLine('A');
        }

        static void B()
        {
            Thread.Sleep(1000);
            String.Format(null, 12);
            Console.WriteLine('B');
        }
    }
}
```

**Comment by isidorn** [comment]
@weinand noticed that the fix is incomplete and that in some corner cases we might still hit issues. In order to have a proper solution we need a `callStackScheduler` per `Thread` and this will be a larger refactoring which I am now looking into.
Since the proper fix will touch more code areas and since this issue does not happen that often I suggest that we do not release this in the recovery build.
The fix would be available soon in insiders in either way.
