### ISSUE TITLE
Expose editor.hover setting as real setting

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#28535]
Today this setting is hidden because it is not added to the configuration schema.

**Comment by isidorn** [comment]
After talking to Alex he convinced me this is overly complicated due to debug setting the hover programitically which will fiight the whole configuration story.
Example: while debugging user opens an additional editor -> now this editor should also have hover disabled
Example2: when debugging is done which `hover` option should be respected. There might be a language specific hover which takes precedence

-> backlog

**Comment by kellytk** [comment]
@isidorn Complicated or not, FWIW, not being able to configure the hover delay introduces substantial friction to my use of VS Code.

**Comment by alexandrudima** [comment]
Done via https://github.com/Microsoft/vscode/commit/291c8e5806f046e9d7059fc2809fad001d8c6150

**Comment by kellytk** [comment]
@alexandrudima The code doesn't appear to allow for the feature to be enabled, but with a configurable delay.  Is that correct?

**Comment by alexandrudima** [comment]
The setting is now available in intellisense in `settings.json`.
