### ISSUE TITLE
Allow debug adapters to report messages to be displayed in status bar (or custom messages)

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#28551]
I don't know if this is already possible, but I can't find anything like it.

The debugger I'm using reports some status events that are designed to be shown in the status bar in the IDE. Currently I can write them into the debug output window with an `OutputEvent` but as far as I can tell I can't receive these in the extension to display in the status bar.

I think .NET in (full) VS reports things back to the status bar too (such as loading symbols for DLLs?) so possibly this is useful generally?

Note: If there's already some way to just send custom data back from the debug adapter back to the extension (I guess it's similar to #15656 but in the opposite direction) then that would also satisfy this :-)

**Comment by weinand** [comment]
@DanTup we do not plan to give a debug adapter direct access to all the VS Code UI because we want to keep the API between a DA and its clients (VS Code, VS, VS for Mac, etc.) as small as possible.

However, we understand the need and we try to make it possible that a DA can communicate to the extension (which itself has access to the vscode.d.ts). This still couples the DA to VS Code, but since the route is a bit laborious, extension will be aware of the fact that this route is optional and will not work if a DA is not run in VS Code but in some other client.
 
We just started to work on the extension API for debug extensions. Please track https://github.com/Microsoft/vscode/issues/28500 to follow our discussion.

**Comment by DanTup** [comment]
@weinand Thanks, I'll add a note on there about what I'd like to see.

**Comment by weinand** [comment]
@DanTup you can send custom events in the DA and easily pick them up in the extension and show them in the status bar.

**Comment by DanTup** [comment]
@weinand Can you clarify how you mean? Is there a new API for this? (I had a quick scan of related cases but can't see anything obvious).

Thanks!

**Comment by weinand** [comment]
Yes, use this [API](https://github.com/Microsoft/vscode/blob/ca683214de16f19e4a0e7ac62a032a5681af838d/src/vs/vscode.d.ts#L5929) to register for custom events coming from your adapter.

**Comment by DanTup** [comment]
@weinand Excellent - thanks! 👍
