### ISSUE TITLE
Command + P - Opening new code (abc.cs) does not always make new page

### ISSUE THREAD

**Issue by Cliwo** [Microsoft/vscode#28577]
- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:34:53.678Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|unity-debug|Unity|1.2.0|
|unity-snippets|YclepticStudios|0.1.2|
|eppz-code|eppz|1.2.22|
|csharp|ms-vscode|1.10.0|;

---

Steps to Reproduce:

1. Search .cs file (code) using Command + P
2. Left Click or Right Click code file which I try to find

it does not always make new page 
sometime it makes new page and sometime it does not.
it drives me crazy 
I thought that left click is showing new code file on already exist page and right is making new page but it was totally wrong.

please save me from this crazy phenomenon

**Comment by CherryDT** [comment]
Opening a file either by ctrl+P or single-clicking in the tree opens the file temporarily. You will see the filename written in italics in the tab header. 

Once you change something in the file or double-click its tab header or double-click it in the tree, it becomes permanent.

When you open another file while a temporary tab is open, its contents are replaced with the new file. Otherwise, a new tab is opened.

**Comment by ramya-rao-a** [comment]
@CherryDT is right. Thanks @CherryDT !

@Cliwo You can read more about this preview mode here: https://code.visualstudio.com/docs/getstarted/userinterface#_preview-mode

There is also an option in the docs linked above to disable the preview mode

**Comment by Cliwo** [comment]
OMG.. Thanks to everyone 
It really makes me crazy.. you guys are savior
