### ISSUE TITLE
Out-of-the-box color picker

### ISSUE THREAD

**Issue by michelkaporin** [Microsoft/vscode#28587]
To improve user experience when working with styling in CSS files we plan to add a colour picker.

There are current implementations of colour picker in extension marketplace but they are heavy-weight and do not form part of the core code.

**Comment by ajitid** [comment]
And color converter too (RGB(A)  <-> HEX <-> HSL and others)

**Comment by michelkaporin** [comment]
The initial plan is to have the following features (which could be extended going further):

1. Ability to select color, shade and transparency
2. Ability to switch between CSS Color Module Level 3 standard colours 
   - RGB values
   - hexadecimal values
   - HSL values (CSS3)
3. View and edit current selected color value inside colour picker
4. View initially selected colour from the editor

Going further we could extend the picker with:
1. Colour palettes
2. Showing all the colors of current file to easy pick an existing color
3. Color eyedropper (not sure how feasible is it at the current stage)

**Comment by ajitid** [comment]
In extending the color picker:

4. Naming colors present in the color palette. So one can type `btn-hover` (suggested by Intellisense) and press enter rather than typing `#43aaaa`.
4. Dynamic coloring- A checkbox, when ticked and a color in the palette if changed, all of its occurrence in the project will be changed.

**Comment by anseki** [comment]
Hi,
I expect this great feature, and I will do maintenance my ["Color Picker"](https://marketplace.visualstudio.com/items?itemName=anseki.vscode-color) extension until this feature is added to VS Code.

And I hope that the feature supports customizing a format of an output, when picking a color or converting colors.
E.g. it allow us to choose `70%` or `0.7`. Also, `FED` or `ffeedd`, etc.

**Comment by dstorey** [comment]
I like the plan.

Some additional ideas:
* It would be nice to default to hex shorthand where available (like #111 rather than #111111)
* It would be really cool if VS Code understood your linter rules and defaulted to that format for colours if you have one specified. I could imagine this wouldn't be easy as there are more than one CSS linter.
* CSS4 extends hex to be able to specify the alpha channel (4 and 8 digit hex). This may be nice to add but as it isn't well supported yet, maybe this would just encourage interop issues.
* Where you specify both a colour and a background-colour in the same ruleset, it would be really brilliant if the colour picker warned (and maybe clamped the sliders) when the two colours don't meet the two recommended colour contrast ratios. You probably couldn't do it beyond the current ruleset as you don't know outside the browser what will get inherited like you can in F12, but at least it is something.

**Comment by isidorn** [comment]
@michelkaporin has delivered color picker to master, you can try it out in master.
Closing
