### ISSUE TITLE
Allow quick open to control focus of the next viewlet

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#28622]
- VSCode Version: master
- OS Version: Windows

Currently the workbench gives focus to the editor when quick open closes. I would like to control which viewlet gets focus. The run function for quick open could control this via a return value.

**Comment by bpasero** [comment]
@dbaeumer is your quick open handler a real `QuickOpenHandler` or using the simple picker API? If you are a real handler you could use the following trick:

```typescript
public run(mode: Mode, context: IEntryRunContext): boolean {
	if (mode === Mode.OPEN) {
		// run your action

		this.quickOpenService.close();
		this.panelService.getActivePanel().focus();

		return false;
	}

	return false;
}
```

Basically by returning `false` from the `run` method, quick open will stay open so that you can close it via the service (this will not trigger a focus change). 

If you are using the picker API, you cannot do this at the moment.

**Comment by dbaeumer** [comment]
@bpasero I am a full `QuickOpenHandler`. Will look into it.

**Comment by bpasero** [comment]
Closing as a workaround exists.
