### ISSUE TITLE
${workspaceRoot} is empty when no file is open

### ISSUE THREAD

**Issue by cprogrammer1994** [Microsoft/vscode#28620]
- VSCode Version: 1.13.0
- OS Version: Windows 10 64bit

Steps to Reproduce:

1. Open a folder with vscode
2. Create `.vscode/tasks.json`
3. Add a task:

```
{
    "taskName": "7. Check",
    "command": "start",
    "args": ["cmd /k \"${workspaceRoot}\\check.bat\""],
    "showOutput": "never",
    "isShellCommand": true
}
```

4. **Close all the files**
5. Run the task: **7. Check**

```
'\check.bat' is not recognized as an internal or external command,
operable program or batch file.
```

If you skip **4.** (or you have at least one open file) the file is executed properly.

#### The problem:

If there is no open file in the editor the `${workspaceRoot}` is equal to `""`

**Comment by isidorn** [comment]
I tried to reproduce this and could not, if I close all files the `${workspaceRoot}` still gets substituted as expacted. I have also checked the code and it is in no way effected by the files currently opened 
https://github.com/Microsoft/vscode/blob/isidorn/explorerModel/src/vs/workbench/services/configurationResolver/node/configurationResolverService.ts#L26
https://github.com/Microsoft/vscode/blob/isidorn/explorerModel/src/vs/workbench/electron-browser/workbench.ts#L548

However if I open a no folder VSCode (purple status bar) then the `${workspaceRoot}` does not get substittued, however that is expected since in that case this is expected.

**Comment by cprogrammer1994** [comment]
I will reproduce it in a clean VM this problem occurres on all my systems.

**Comment by isidorn** [comment]
Can you first confirm if you are not using a no folder vscode(purple status bar)?
Also try putting just `${workspaceRoot}` as the argument to try to simplify the issue and we might find the root cause

**Comment by cprogrammer1994** [comment]
![tasks json](https://user-images.githubusercontent.com/11232402/27123961-c303b906-50ef-11e7-8dd8-69424d89b2ae.gif)

It seems to be an extension issue. I just realized status bar tasks are provided by an extension.
Using `ctrl+shift+P` the task is running properly.

**Comment by cprogrammer1994** [comment]
it seems that `${workspaceRoot}` is overwritten by the extension.

- [extension.ts](https://github.com/GuardRex/vscode-status-bar-tasks/blob/master/status-bar-tasks/src/extension.ts#L117)

**Comment by isidorn** [comment]
@cprogrammer1994 thanks for looking into this, you should file an issue to that extension
