### ISSUE TITLE
Dark (not plus) theme this release for PHP is broke

### ISSUE THREAD

**Issue by bobmajdakjr** [Microsoft/vscode#2864]
"dark" not plus now is mostly just "white"

![capture](https://cloud.githubusercontent.com/assets/881944/12929866/c47d4910-cf3a-11e5-9aff-ac090974fbe5.PNG)

**Comment by bobmajdakjr** [comment]
before the update

![capture](https://cloud.githubusercontent.com/assets/881944/12930315/31b9d640-cf3d-11e5-87f5-96d6fdf70fa5.PNG)

**Comment by bobmajdakjr** [comment]
the variables are a gross pastel with dark+, most of the other themes though seem to skip variables as well.

**Comment by bingzheyuan** [comment]
I mension this in #2828 as well, and I also hope the color for variables comes back in dark theme.

**Comment by aeschli** [comment]
We now two built-in dark themes: 
 - the Dark Visual Studio that follows the color scheme of Visual Studio. It has no color for variables
 - the Dark+ that is more colorful, including light blue for variables. It is now the new default, but needs to be configured manually by users that are updating from the January update.
Same with the light themes.

**Comment by bobmajdakjr** [comment]
did aeschli even attempt to understand what is going on here?

**Comment by bobmajdakjr** [comment]
I even posted before and after shots.

**Comment by aeschli** [comment]
I thought you were pointing to the fact that PHP variables are longer colored in the Visual Studio Dark theme, correct?
In my comment before I wanted to explain that this is the new expected behavior for the Visual Studio Dark theme. The [release notes](https://code.visualstudio.com/Updates#_editor) has more background information on the change.
If you want the color for the varaibles back, I'd recommend you to switch to the new Dark+ theme.

Let me know If I misunderstood your request.

**Comment by bobmajdakjr** [comment]
if anybody still cares to restore the variable behaviour to before they introduced dark+, the fix, add:

		{
			"scope": [
				"meta.parameter.type.variable",
				"variable.parameter",
				"variable",
				"variable.name"
			],
			"settings": {
				"foreground": "#569cd6"
			}
		},

to C:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\extensions\theme-defaults\themes\dark_vs.json
