### ISSUE TITLE
Feature: Setting to hide Vertical Scroll-Bar when the Minimap is Visible

### ISSUE THREAD

**Issue by stephenmartindale** [microsoft/vscode#28653]
Please can we have a setting to hide the vertical scroll-bar if the very awesome minimap is visible? With the minimap there, the vertical scroll-bar is just a waste of space.

![capture](https://user-images.githubusercontent.com/6370145/27098953-8b684438-5079-11e7-8a59-bc54529b380a.PNG)

It would also be very cool to show the current view-area in the minimap by changing its background colour in that region - like full-fat Visual Studio.

**Comment by cleidigh** [comment]
@alexandrudima 
I would be glad to do a PR on this to add a configuration option HideVerticalScrollbar ?

**Comment by alexandrudima** [comment]
There is already a "hidden" option `"editor.scrollbar.vertical": "hidden"`, but that just hides the scrollbar, but the overview ruler is still there and the minimap still leaves space for it. I would say it is a good idea to add an option to remove the vertical scrollbar, but only after we render other adornments in the minimap. e.g. errors, find matches, etc. all other stuff that renders today in the overview rule. But this needs to be implemented in a smart way, possibly via a secondary transparent canvas on top of the minimap such that repainting these adornments does not result in repainting the minimap. Furthermore, I think there are some issues with the `EditorLayoutInfo` which is "leaky" and could use some improvements. i.e. some view code still ends up computing stuff, which I don't really like. [e.g.](https://github.com/Microsoft/vscode/blob/079ad467d5d2564c6ff42ab9f9949e6d4ca5ec84/src/vs/editor/contrib/zoneWidget/browser/zoneWidget.ts#L197). I plan to make some refactorings in the area to encapsulate such math inside the `EditorLayoutInfo`. So ... a PR is welcome, but a lot of care must be taken because the layout is "leaky".

**Comment by cleidigh** [comment]
@alexandrudima 
Thanks for the detailed response/issue comments !
I've started looking at the code, and as I you've pointed out it's more complicated
then at first blush. I did one of my first PR 's for expanding and contracting views
so I got into some of the layout code and calculation issues. I've also been working on a drop-down improvement delving into layout and UI issues. I could look into this more
But because you talk about re- factoring would it be better to wait or is it helpful
to do some preliminary work?
FYI I could not find anything either in the code or configuration that matched
editor.scrollbar.vertical
thanks Christopher

**Comment by neolectron** [comment]
I, managed to do this instead : 
`"editor.hideCursorInOverviewRuler": true`

**Comment by dagolinuxoid** [comment]
@alexandrudima

**Comment by kylerdanielster** [comment]
Can confirm, "editor.scrollbar.vertical": "hidden", is no longer working. Getting an 'unknown configuration setting'. Same for "editor.scrollbar.horizontal": "hidden".

**Comment by iamandreymarchenko** [comment]
Confirmed about "editor.scrollbar.vertical": "hidden" too. Can't find this one.

**Comment by ArmorDarks** [comment]
Also hope to see this option. When minimap enabled vertical scrollbar is basically redundant and doesn't help anything except distracting.

**Comment by jvican** [comment]
The option was detected as "unknown configuration setting" but when I restarted vscode it worked.

**Comment by jonasagx** [comment]
1. you need to reload vscode for the changes to take place
2. i combined these two settings to hide my scroll bar:
```
    "editor.scrollbar.vertical": "hidden",
    "editor.scrollbar.verticalScrollbarSize": 1
```

**Comment by wzxu** [comment]
@jonasagx 
Thanks for the hint! This alone did the trick for me!
`"editor.scrollbar.verticalScrollbarSize": 0`

**Comment by Metaception** [comment]
@jonasagx Unfortunately, this doesn't work if the purpose of hiding the scrollbar is to recover horizontal space. It appears that the editor still reserves the space even if you make the scrollbar disappears (I counted the number of characters that can fit before causing the horizontal scrollbar to appear, and they were the same even when you hide the vertical scrollbar).

If there is ever an official options to hide the vertical scrollbar, then I hope this gets fixed!

**Comment by costincaraivan** [comment]
Could the very useful hidden setting ``"editor.scrollbar.verticalScrollbarSize": 0`` be promoted to available? At least for people who don't want all the bells and whistles from the regular scrollbar. Having it hidden is obviously had for discoverability and also gives a strong hint of deprecation...

**Comment by kid1412621** [comment]
2019 now, any plan?

**Comment by sanket-bhalerao** [comment]
@wzxu  thanks, 
>"editor.scrollbar.verticalScrollbarSize": 0
worked for me.

**Comment by miskeletor** [comment]
> @wzxu thanks,
> 
> > "editor.scrollbar.verticalScrollbarSize": 0
> 
> worked for me.

The tooltip says "Unknown Configuration Setting", but it works.

**Comment by WhenJavaAttacks** [comment]
Nothing really to add, but I agree that having both the minimap and the scrollbar is redundant and wasting space. I don't even care if the minimap does not yet have all the indicators as the scrollbar does, as long as I can still scroll with just the minimap present then I'd at least like the option to disable the scrollbar and reclaim the horizontal space it occupied.

**Comment by vonWolfehaus** [comment]
Using VS Code v1.44.0 on Windows 10 and using the option mentioned earlier (`"editor.scrollbar.verticalScrollbarSize": 0") not only removed the scrollbar but also gives back that horizontal space. And it doesn't require a restart. Looks like it's been secretly implemented in full!

**Comment by thinkjrs** [comment]
> Using VS Code v1.44.0 on Windows 10 and using the option mentioned earlier (`"editor.scrollbar.verticalScrollbarSize": 0`) not only removed the scrollbar but also gives back that horizontal space. And it doesn't require a restart. Looks like it's been secretly implemented in full!

I can confirm this is working for me on vscode version 1.51.1, Windows 10 19042 via WSL2 Ubuntu remote. Thank you @vonWolfehaus!

**Comment by rithviknishad** [comment]
I can also confirm that it works for me (VSCode 1.51.1 on Ubuntu 20.04), though it shows `Unknown Configuration Setting`.
![image](https://user-images.githubusercontent.com/25143503/100409936-34da9c80-3093-11eb-9296-ba5ff20ae502.png)

*I wonder why this issue is still kept open when it's solved :/

**Comment by alexdima** [comment]
This is now a real setting:
```
"editor.scrollbar.verticalScrollbarSize": 0
```
