### ISSUE TITLE
Debug viewlet section headers are blank

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#28650]
![image](https://user-images.githubusercontent.com/323878/27097406-ff5d9da8-5028-11e7-97c7-f7f9335b9098.png)

**Comment by roblourens** [comment]
Since yesterday's Insiders

**Comment by isidorn** [comment]
Sandeep broke the split view I believe, I have the same behavior for explorer -> @sandy081

**Comment by sandy081** [comment]
@isidorn I only see in Debug viewlet. Explorer is good for me

![image](https://user-images.githubusercontent.com/10746682/27171025-5c9892e2-51b0-11e7-8006-64844c08c9f1.png)

More strangely, out of sources, on same version of insiders, does not have this issue

![image](https://user-images.githubusercontent.com/10746682/27171060-7caa7d3e-51b0-11e7-8862-a5f26df2d354.png)

@jrieken  / @michelkaporin Anything to do with translations or `nls`?

**Comment by isidorn** [comment]
I see the same as @sandy081 only for debug and only for insiders, not out of source

**Comment by michelkaporin** [comment]
@sandy081 translations are good, not sure about `nls`.

**Comment by sandy081** [comment]
Debugged and found that following is returning undefined

```
nls.localize('variables', "Variables")
```

![image](https://user-images.githubusercontent.com/10746682/27196662-b1b759f6-520b-11e7-989a-5f6b271e29a5.png)

Not sure what caused this

FYI
@michelkaporin and @dbaeumer for translations
@alexandrudima for `nls`

**Comment by alexandrudima** [comment]
@joaomoreno At build time, it is expected that all nls.localize calls are patched, that's why the method expects `idx` to be an integer and it doesn't use `defaultValue`.

From @sandy081 screenshot it appears that one specific nls.localize call, i.e. `nls.localize('variables', "Variables')` is not picked up, nor patched at build time. I'm not sure how old the screenshot is w.r.t. to master, but on master the file has 13 externalized strings, and in the screenshot the file has only 8.

**Comment by joaomoreno** [comment]
The nls patching was working on top of a quite old TypeScript language service (<2)... I'm actually surprised things worked thus far. I've updated it to use the same TypeScript version we depend on in the build tools.

@sandy081 Maybe we should build insiders for this?
