### ISSUE TITLE
Support custom views in other locations

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#28662]
Support custom views in other locations

- [x] Debug

**Comment by eamodio** [comment]
@sandy081 Any way to get this bumped up -- the GitLens view is just BEGGING to be on the SCM activity. Or is there some guidance on what would need to be done here if a PR would be accepted?

**Comment by sandy081** [comment]
I would request @joaomoreno to reply since he owns SCM viewlet.

**Comment by joaomoreno** [comment]
I'm not entirely convinced that this is the way to go... I would like to keep the SCM viewlet clean, though I do see that a Gitlens view is wrong in the File Explorer.

**Comment by ADTC** [comment]
I thought I could simply drag an extension's view into any activity I like. That would be ideal since I can fully control what goes where. But if it's something that's not acceptable, I'll settle with allowing developers to plug in their extension views into other activities.

Although, *how about giving extensions the ability to add their own activities?* That would be totally awesome and the best use of the wasted vertical space on the Activity Bar between the five built-in activities and the settings cog.

PS: Really want to see GitLens and Git History in the SCM activity (or with their own activities) so that my explorer activity focuses on just exploring.

**Comment by sandy081** [comment]
Closing this as there are no plans to contribute views to SCM viewlet.

**Comment by ADTC** [comment]
How about allowing extensions to create custom viewlets?

**Comment by sandy081** [comment]
@ADTC above request is in plan - https://github.com/Microsoft/vscode/issues/43645
