### ISSUE TITLE
Support sections in Extensions viewlet

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#28663]
Support sections in Extensions viewlet
- Recommended
- Installed

**Comment by sandy081** [comment]
![kapture 2017-06-21 at 2 16 41](https://user-images.githubusercontent.com/10746682/27361455-b3da3ab2-5627-11e7-9aa4-6bb3cda6c6dc.gif)

**Comment by sandy081** [comment]
To verify:

- Installed and Recommended sections are shown by default (when Search box is empty)
- While searching from Marketplace, a **single** section showing extensions from Marketplace are shown

**Comment by ghiscoding** [comment]
@sandy081 I know this subject is closed but I'm not sure if I should open a new issue for this or not. I would have preferred to have the "Recommended" on top instead of "Installed". Why? Simply because the search, which is just over the "installed" is making this confusing since it searches through the market place (not through the installed ones) and the recommended do come from the market place so it's less confusing (in my mind anyway).

**Comment by sandy081** [comment]
@ghiscoding Agreed that not everybody wants to have `Installed` section on the top which is the feedback I received from few. With July milestone, you can reorder your sections. Please refer to #30120

**Comment by King66** [comment]
![1](https://user-images.githubusercontent.com/11925432/28104105-f9aaa0e6-670b-11e7-99cb-6a09da80eef3.JPG)


Maybe it's better not to recommend extensions under start 3 ?

**Comment by sandy081** [comment]
@King66 not sure if I understand your comment. Do you mean not to show the recommended sections at all?

**Comment by King66** [comment]
@sandy081  I mean Code recommend a extension which has 2.5 star....
![1](https://user-images.githubusercontent.com/11925432/28109520-ed22a862-6721-11e7-814e-199bdf103c39.png)

**Comment by sandy081** [comment]
@King66 Its not based on stars but we have a set of extensions recommended for languages / file patterns. Also a workspace can define recommendations.

**Comment by King66** [comment]
@sandy081 got it, thanks for you reply.
