### ISSUE TITLE
Large Chinese text file: minimap hides half character

### ISSUE THREAD

**Issue by King66** [Microsoft/vscode#28694]
- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:43:13.058Z)
- OS Version: Windows_NT ia32 10.0.14393

Steps to Reproduce:

1. open 1.md
2. open 2.md
3. open test.md, the minimap hides half character.

- If I close all editors and then only open test.md, things become normal.
- Triple click will make it normal.

- The explorer width may have an impact.
- Also reproduce using default settings.

![hidetext](https://user-images.githubusercontent.com/11925432/27119800-da2d49f2-5113-11e7-91ad-cb39c900953c.gif)

**Comment by King66** [comment]
https://drive.google.com/open?id=0B9sSiOdezYhvTkFHSlFsd3Y4cEk

**Comment by King66** [comment]
![wrap](https://user-images.githubusercontent.com/11925432/27170782-b59a9ef4-51e1-11e7-9ee6-b8263d46dbec.gif)

**Comment by alexandrudima** [comment]
The issue is not CJK specific. It reproduces when rendering line numbers and opening a file with more than 999 lines, and is more obvious when opening a file with more than 9999 lines. The line numbers need to occupy 4 digits or 5 digits, and this information is not taken into account until the first relayout. e.g. a resize.
