### ISSUE TITLE
window.zoomLevel value is -1 every time vscode is reopened

### ISSUE THREAD

**Issue by ronnidc** [Microsoft/vscode#28699]
When I launch VSCODE the `window.zoomLevel` is lower than normal. If I then click _"View >Rezet zoom"_ it zooms back to normal (`window.zoomLevel: 0`). If I reopen the app the zoomLevel is yet again to low.

(The value is set to `0` in my user settings and it's not defined in my workspace settings).

- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:43:13.058Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|Handlebars|andrejunges|0.2.0|
|handlebars-preview|chaliy|1.1.0|
|npm-intellisense|christian-kohler|1.3.0|
|vscode-svgviewer|cssho|1.4.2|
|mustache|dawhite|1.0.0|
|vscode-babel-coloring|dzannotti|0.0.4|
|gitlens|eamodio|4.1.1|
|vscode-html-css|ecmel|0.1.6|
|git-project-manager|felipecaputo|1.3.2|
|webpack|jeremyrajan|2.0.0|
|csharp|ms-vscode|1.10.0|
|material-icon-theme|PKief|2.0.9|
|sass-indented|robinbentley|1.4.1|
|stylelint|shinnn|0.24.8|
|code-spell-checker|streetsidesoftware|1.1.0|;

---

Steps to Reproduce:

1. Click _"View >Rezet zoom"_ to make sure zoomLevel is normal
2. Close all Code app windows if any are open
3. Open Code again. The zoomLevel is now lower than the default `0` value.

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.
