### ISSUE TITLE
Editor no longer closes quotes for PHP

### ISSUE THREAD

**Issue by kc9eye** [Microsoft/vscode#287]
After last update, editor no longer closes quotes (double|single) on PHP files. Does close quotes on settings file. Can't find setting to control as such. Brackets work fine.

**Comment by tominon** [comment]
This may be related to issue #179

**Comment by alexandrudima** [comment]
We need to revisit how this feature is implemented and maybe add support for it through the language configuration file linked to from package.json

**Comment by tht13** [comment]
I have the same with Python, in the insider preview email sent out for the 0.10.0 release it warned that closing bracket insertion, closing quote insertion and auto indenting would be removed due to a bug but that they would be re implemented with 0.10.1
Bracket auto closing has been implemented, but auto indentation and quotes have not.

If I remember correctly the email also stated that Python would not be the only language affected by this bug

**Comment by alexandrudima** [comment]
@tht13 Indeed, in 0.10.0 we did the large switch from monarch based tokenizers (hand written by us) to textmate bundles (mostly from the community).

Between the recovery build 0.10.1 and 0.9.x what is now missing is the quote surround/auto-completion. We need to bring this back

**Comment by abelshaw** [comment]
I'm not sure If I should add it here or start a new issue. Visual Basic is also affected by this. 
Same effect, brackets work fine but double quotes do not. As the single quote is the comment character I don't think that's ever closed and I don't think anyone would want it to.

**Comment by nchammas** [comment]
I am having this same issue. Highlighting some Python code and hitting the quote character now replaces the text instead of quoting it. This didn't start happening until recently.

I'm running VS Code 0.10.3.

**Comment by aeschli** [comment]
I verified that PHP quote completion and surrounding works.
I opened #4510 for Python and #4511 for VB.
