### ISSUE TITLE
Ligatures only work for some languages

### ISSUE THREAD

**Issue by icorderi** [Microsoft/vscode#2870]
I'm not sure if this is an intended feature but certain ligatures seem to turn on/off depending on the selected language for the file.

If that is an intended feature, then there are quite a few languages missing entries on the ligature map. 
I use vscode for Rust and the basic function result `->` is not being translated to an _arrow_. Same thing is true for `>=`, `<=` symbols.

**Comment by colinbate** [comment]
This is certainly related to my PR #2872 where I fixed a similar issue with JavaScript and TypeScript. The issue is that the language grammar parses the `-` and `>` as separate operators. Therefore they end up in separate `span`s in the editor, so the font can't do its thing.

I don't know much about Rust, but I just quickly tried to fix the arrow in a similar way, and it seems to work. You can try it for yourself by opening this file under your VS Code install:

    resources\app\extensions\rust\syntaxes\rust.json

(similar location in the application bundle on the Mac)

and on line 305 adding `|->|<=|>=` after the `+`.

**Comment by prashaantt** [comment]
I have the same problem using the `!==` in JS (using Fira Code).

![image](https://cloud.githubusercontent.com/assets/390540/12941372/af44f09e-cff7-11e5-8f72-e8ffc95caa8c.png)

The `===` by itself works well:

![image](https://cloud.githubusercontent.com/assets/390540/12941362/970be0c8-cff7-11e5-8516-600aae30bfb7.png)

**Comment by icorderi** [comment]
If any _rustacean_ comes this way, as @colinbate suggested, I changed line 305 on `rust.json` to say:
```
"match": "(\\+|->|<=|>=|=>|>>|<<|==|!=|&&|-|/|\\*|=|\\^|&|\\||!|>|<|%|::|\\bas\\b)"
```

> _Note:_ On OSX the syntax file is under `/Applications/Visual\ Studio\ Code.app/Contents/Resources/app/extensions/rust/syntaxes/rust.json`

cc: @alexandrudima

**Comment by killercup** [comment]
@icorderi, I made a PR with your suggested change (#3199) to get this (or an improved version) into the repo.

**Comment by alexandrudima** [comment]
I think 5598ee09f101158c066db7797b73e17bdc91ce78 also fixes this one:

We now merge identical sequential tokens.

![image](https://cloud.githubusercontent.com/assets/5047891/13217063/35c139ae-d960-11e5-8b1a-2ac093bb7617.png)


![image](https://cloud.githubusercontent.com/assets/5047891/13217053/20775380-d960-11e5-9713-7aa0c2aabab9.png)
