### ISSUE TITLE
"can not add index to parent of type array" Error message

### ISSUE THREAD

**Issue by arixse** [Microsoft/vscode#28728]
- VSCode Version:v1.13.0
- OS Version:windows 10

Steps to Reproduce:

1.when i change the vscode color theme or file icon theme
2.the vscode will show the "can not add index to parent of type array" error message

**Comment by ramya-rao-a** [comment]
Can you share the call stack from the console? You can open the console by running the command `Developer: Toggle Devleoper Tools` in the command pallet

**Comment by johnhamm** [comment]
I am also getting this same error.
VSCode Version: v1.13.0
OS Version: Windows 10

Stack trace:
```
Can not add index to parent of type array
e.doShow @ messageService.ts:125
e.show @ messageService.ts:104
e.resume @ messageService.ts:63
(anonymous) @ workbench.ts:892
e.invoke @ callbackList.ts:63
e.fire @ event.ts:123
(anonymous) @ quickOpenController.ts:513
```

**Comment by johnhamm** [comment]
I believe it is related to the Quick Open dialog closing.

**Comment by johnhamm** [comment]
Since I can't change my icon theme (the current one doesn't show the folder icon), does anyone know how to change file icon themes correctly without using the UI?  I assumed I would just set the workbench.iconTheme setting in user settings, by plugging in the name of the theme extension like so:
`"workbench.iconTheme": "robertohuertasm.vscode-icons"`

But I save the user settings and restart and the theme remains the default theme (vs-seti)

**Comment by johnhamm** [comment]
For anyone else trying to get around this bug, I ended up having to revert to version 1.8 before I was able to switch icon themes:
https://vscode-update.azurewebsites.net/1.8.0/win32/stable

**Comment by bpasero** [comment]
I cannot reproduce. 
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

I do not even know where this error message is coming from.

/cc @aeschli

**Comment by arixse** [comment]
This problem only occurs in Windows10 Home Edition,WINDOW10 Professional Edition has not found the problem like this.

**Comment by arixse** [comment]
I think there is something wrong with my OS. This issue does not happend again when i restore the OS.Thanks! @johnhamm @ramya-rao-a @bpasero @aeschli @threeve
