### ISSUE TITLE
Need to disable extensions not just uninstall them

### ISSUE THREAD

**Issue by SteveALee** [Microsoft/vscode#2882]
When looking for problems with intellisense (#2850) I wanted to clean up my config by disabling all extensions. However they can only be deleted.

This would be a generally useful option in case extensions are causing problems.

--

@joaomoreno

- [x] Figure out format to store extensions disablement in settings
- [x] Move extension scanning to Renderer (with @joaomoreno)
- [x] Ignore disabled extensions when scanning for them at runtime
- [x] Provide UI for enabling / disabling an extension for a workspace or globally
- [x] Telemetry

**Comment by Enet4** [comment]
As a workaround, extensions can be manually disabled by moving them away from your local extensions folder. (this is "~/.vscode/extensions" in Linux, I'm afraid I don't really know for other platforms)

But yes, I would also appreciate a more intuitive means of disabling extensions.

**Comment by alexandrudima** [comment]
fyi @joaomoreno

**Comment by bgse** [comment]
Would be really neat if we could define active extensions as multiple presets, workspace setting with individual extensions would suffice I guess but having a way to quickly switch between extension presets would be awesome (even if that means restarting vscode).

**Comment by savioret** [comment]
What about adding a ".disabled" (or .whatever) file inside the extension folder in order to set it as "not loadable". Neat and easy to implement.
for instance: `~/.vscode/extensions/myextension/.disabled`

**Comment by gregvanl** [comment]
Doc Feedback verbatim request: "I need to disable an extension without uninstalling it."

**Comment by SteveALee** [comment]
I recently notive code has a "safe mode' invoked via a command line switch. You should doc that in same place too.

**Comment by Novynn** [comment]
+1

**Comment by joaomoreno** [comment]
> @bpasero says:

> The first thing I typically ask a user when an issue is reported is to run with all extensions disabled. However, if one extension is causing issues and 30 are installed, it is very hard to find the one causing the issue.

Ideally we have UI to disable an extension selectively (from the extensions viewlet) so that a user can easily find out which extension is causing issues. 

Optionally we could also allow to do so from the command line, e.g. "`code --disable-extension vscode-icons`"

CC'ing some folks fyi @alexandrudima @joaomoreno @jrieken @egamma

**Comment by scottpschaffer** [comment]
I just wanted to note that I am running version 1.5.2 and I have only the C# extension loaded. Just now, I went to the Extension and pressed Update. It went searching for the update (I assume) and then the Update button changed to an "Enable" button. Clicking the Enable button presents me a message that says I need to restart Code for the enabling to occur. I mention this only because it shows that there is already some functionality in the program to Disable the extension (at least that one).

**Comment by JoeCodeswell** [comment]
+1 need to sometimes disable/enable pylint

**Comment by Enet4** [comment]
@JoeCodeswell This feature is already available. Enter Visual Studio code, open the extensions column, and click on the cog next to the extension. As for disabling Pylint in particular, it might be more elegant to have a custom .pylintrc file in each of your projects. With `{ "python.linting.enabled": false }`, linting is disabled entirely.
