### ISSUE TITLE
Tasks 2.0 integration with launch.json

### ISSUE THREAD

**Issue by ytimenkov** [Microsoft/vscode#29013]
I want to specify auto detected task as a prelaunch task (`npm run compile` in my case).
Right task name is just `"preLaunchTask": "run compile",` which I found only by looking into VS Code sources.

There are 2 problems with this:
### 1. there is no way for user to guess "task name" from UI ###
Task picker looks:
![image](https://user-images.githubusercontent.com/7413219/27278817-d06612be-54e2-11e7-9bfc-52a6a2879e61.png)
I tried "npm: run compile", "npm", "npm run compile" - nothing worked.

Even when I try to customize task I get `tasks.json`:
~~~json
{
    "version": "2.0.0",
    "tasks": [
        {
            "customize": "vscode.npm.run compile",
            "taskName": "npm: run compile",
            "problemMatcher": []
        }
    ]
}
~~~
Which gives no clue about task name being just "run compile".

### 2. Possible name clashes ###
If no extension name is involved in lookup process, what if task is simply called "build"?

- Related to #28235 
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)

**Comment by dbaeumer** [comment]
We discussed that yesterday and we will support specifying the label in the launch.json.

**Comment by dbaeumer** [comment]
@isidorn this required some minor changes in the DebugService. Instead of getting all tasks I added a method to the task service to receive a task using the string in the preLaunchTask property. This allows the task framework to to care of how a task is found. Please have a look at the commit attached to this issue.

@ytimenkov you can now do the following:

- either use the task's name as shown in the UI. In your example 'npm: run compile' or you can assign an identifier in the tasks.json and use that.
```
{
	"version": "2.0.0",
	"tasks": [
		{
			"type": "npm",
			"script": "compile",
			"identifier": "npm>run>compile",
			"problemMatcher": [
				"$tsc"
			]
		}
	]
}
```
defines the identifier `npm>run>compile`. The launch.json then looks like this:
```
		{
			"type": "node",
			"request": "launch",
			"name": "Launch Program",
			"program": "${workspaceRoot}/helloWorld.js",
			"preLaunchTask": "npm>run>compile",
			"outFiles": []
		}
```

**Comment by isidorn** [comment]
@dbaeumer I checked these changes and it looks good to me. Should we create a Test Plan item for this?
