### ISSUE TITLE
Dont prompt to save Untitled JSON results

### ISSUE THREAD

**Issue by Ruprect** [Microsoft/vscode#29016]
This is a Feature Request.

I use Visual Studio Code to code my SQL queries, that return JSON. But when I open the JSON resultset (in a new Untitled tab), I must acknowledge that I do not wish to save the file.

![image](https://user-images.githubusercontent.com/883620/27283496-e109fea2-54f4-11e7-8313-3d682ff9698a.png)

Please make a setting for unchanged JSON results to not prompt for save when closing.

**Comment by techird** [comment]
Not reasonable. The editor has responsibility to remind you of any unsaved content.

**Comment by bpasero** [comment]
Yeah, unlikely we would change this.

**Comment by Ruprect** [comment]
@techird and @bpasero 

But the file is unchanged, I execute my query - And click the result:

![image](https://user-images.githubusercontent.com/883620/27322246-b011f864-559d-11e7-9743-72f62ba77763.png)

And that shows my JSON:

![image](https://user-images.githubusercontent.com/883620/27322268-ce3b506a-559d-11e7-9e27-ec6fb283aee3.png)

And when I close that window (no changes made) - It prompts me to save changes, but - I did not make any changes.

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by Ruprect** [comment]
I can't reproduce the error - Because I need the SQL server extension to execute my SQL.

**Comment by Ruprect** [comment]
But I will post it into msSQL repo instead
