### ISSUE TITLE
Cannot enter text in new file and cannot open settings

### ISSUE THREAD

**Issue by idike** [Microsoft/vscode#29071]
- VSCode Version: Code - Insiders 1.14.0-insider (77bf512f0eba6c7082f5b442ac5de585febcab23, 2017-06-19T13:43:15.507Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.9.1
gc-excelviewer|Gra|1.1.15
beautify|Hoo|1.1.1
vscode-docker|Pet|0.0.16
html-snippets|abu|0.1.0
code-gnu-global|aus|0.2.2
vscode-eslint|dba|1.2.11
vscode-instant-markdown|dba|1.1.0
githistory|don|0.2.0
python|don|0.6.5
gitlens|eam|4.1.2
tslint|eg2|0.15.0
Go|luk|0.6.62
MagicPython|mag|1.0.10
prettify-json|moh|0.0.3
atom-keybindings|ms-|2.0.1
cpptools|ms-|0.11.4
csharp|ms-|1.10.0
sublime-keybindings|ms-|2.0.1
team|ms-|1.119.0
Ruby|reb|0.12.1
vscode-icons|rob|7.9.0
vim|vsc|0.8.6
gitblame|wad|1.11.3
jinja|who|0.0.8

(2 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by idike** [comment]
![image](https://user-images.githubusercontent.com/13204029/27323096-42c3bc22-5555-11e7-9984-9f5bd17bc0d1.png)

I disabled all extension and its the same thing, Cannot type in new text and cannot open settings preference.

Thanks

**Comment by sandy081** [comment]
Duplicates #29022

@idike Sorry for this. This is a bug on our side. Will fix it and do a new insiders release
