### ISSUE TITLE
unable to verify the first certificate

### ISSUE THREAD

**Issue by ybzy920** [Microsoft/vscode#29088]
How do you fix the plugin prompt error "unable to verify first certificate"?

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.
