### ISSUE TITLE
Selecting call stack entries does not move editor

### ISSUE THREAD

**Issue by mattacosta** [Microsoft/vscode#29097]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 6.1.7601

---

I have been having some intermittent issues with the call stack not moving. More precisely, it moves and then instantly moves back to the location of a thrown exception. Here's an example:

![vscode-callstack-bug](https://user-images.githubusercontent.com/1007463/27327412-5eec6ee0-5563-11e7-8c87-ecfd015ad8c9.gif)

I have been randomly throwing in new exceptions in my code, and the call stack does work properly sometimes, so I really don't know what is going on.

Notes:
- Same results when setting the protocol to "inspector".
- If I manually scroll to the proper location, the green line marker is there.
- There are no errors in the developer console.

**Comment by isidorn** [comment]
@mattacosta thanks for the additional notes, however I am not 100% clear what is wrong in the attached gif. You are clicking on the callstack is not revealing those entries in the editor, however looking at the callstack those entries do not have a file location associated with them so there is nothing to open (to make sure this is true make the callstack horizontally larger). If you were to click on the callStack entries that have the `module.js` or `phpParster.ts` as the location the file should properly open, correct?

**Comment by mattacosta** [comment]
Everything above "(anonymous function)" is within the `PhpParser.ts` file and has line/column info. It just got hidden.

Clicking on the `module.js` entries switches the editor to that file, and moves the editor to the associated lines properly as well. So it looks like this is limited to the file with the red exception thingy.

Here's another gif that hopefully shows the issue better (the low FPS of the one above doesn't really do the flickering justice):

![vscode-29097-2](https://user-images.githubusercontent.com/1007463/27377902-279dd41a-562b-11e7-8502-69049d15c981.gif)

As you can see I added that exception on line 1290. Clicking on the other two entries moves the editor to lines 540 and 250 respectively, but the editor immediately goes back to showing line 1290.

**Comment by isidorn** [comment]
Yes I see the issue, this is due to the fact that we always reveal the exception widget location. Forwarding to @michelkaporin to try handling this better

**Comment by mattacosta** [comment]
It also occurs to me that the times when I think that it works, are probably also the times when I am paused on breakpoints that I have added (and therefore the red exception widget hasn't been shown yet).

**Comment by isidorn** [comment]
@mattacosta This works fine for me in the latest [vscode insiders](https://code.visualstudio.com/insiders) release. Can you please download it and try out if this still happens
fyi @coder-mike

![stackframeclick](https://user-images.githubusercontent.com/1926584/30215375-1dfd20f0-94b0-11e7-9187-d7b91e3d2c8a.gif)

**Comment by mattacosta** [comment]
Still happens as of 1.17.0-insider (c354fca; no extensions).

**Comment by hbenl** [comment]
@isidorn To reproduce this, the line where the exception was thrown and the line that you want to jump to need to be in the same file but further apart, so that they don't fit in the window at the same time.
Try this:
```
function throwError() {
	throw new Error();
}

<lots of empty lines>

throwError();
```
start this in the debugger and click on the second stack frame - the `throwError();` line should be shown but isn't.
![peek 2017-09-11 20-51](https://user-images.githubusercontent.com/16060807/30291433-2c487184-9733-11e7-898e-7e6d7f1a7575.gif)

**Comment by mattacosta** [comment]
Yup, confirmed that it is dependant on window size. Minimized the window, moved function call ~5 lines beyond visible area, did not work. Maximized the window, worked again. Moved the function call 5 lines beyond the new max, did not work.

**Comment by isidorn** [comment]
@mattacosta @hbenl thank you for the nice reproducable steps, I was finally able to get this on my machine.
The issue was that the exception widget would relayout after the stack frame has been show in the editor, forcing the editor to reveal the exception widget -> thus we would end up in the wrong place.
To fix this I have changed our heuristic to only show the exception widget when the stack frame with the exception is focused. I think this makes overall sense since if you focus some other stack frame you do not need to have the exception widget in your face.

An alternative fix would be to add an option in the ZoneWidget layout to skip the reveal, which should the zone widget should always skip since the stack frame reveal does the trick. However I prefer the first approach. Let me know how it works for you

**Comment by mattacosta** [comment]
Except for #32397 potentially causing the exception widget to not even be in the displayed area now, everything looks good.

**Comment by isidorn** [comment]
@mattacosta thanks. Adding verified label
