### ISSUE TITLE
[themes] Add `editor.findMatchForeground`

### ISSUE THREAD

**Issue by ashclarke** [microsoft/vscode#29091]
When using Find & Replace, I like to highlight the current search match differently. This is particularly helpful when refactoring and proof-reading, especially if there are many matches.

I can add a colour customisation for `editor.findMatchBackground` to achieve this. However, as the foreground colour is not editable, I have a contrast issue with the default foreground colour in the theme.

In my case, I'd prefer to set the background colour to something light, like `#b2b231` and change the foreground colour of the match to `#000000`.

Obviously not a pressing issue; a nice to have 👍

**Comment by jacobcassidy** [comment]
Any progress on this issue? Support for TextMate's "findHighlightForeground" would solve this too. I'm unable to use the "editor.findMatchBackground" as intended because there's currently no way to change the foreground. Which means when the foreground of the text happens to be the same as the background, it disappears into the block.

See screenshots below for clarity....

First is VSC where the element's foreground text happens to be the same color as the "editor.findMatchBackground" color:

![vsc-match](https://user-images.githubusercontent.com/1895973/52351554-99aba980-2a5d-11e9-9610-95749bcb969f.png)

Then we have SublimeText using findHighlightForeground to set the foreground for the focused match:

![sublime-match](https://user-images.githubusercontent.com/1895973/52351557-9c0e0380-2a5d-11e9-9591-208f48433c1e.png)

**Comment by matthiasdailey-ccri** [comment]
![image](https://user-images.githubusercontent.com/18034092/56919085-ae607200-6a8d-11e9-9b92-f1b2529e9613.png)
:sob:

**Comment by lqzhgood** [comment]
I think all font state  **Foreground** colors should be supported.
Used to overlay stateless colors.

**Comment by thisVioletHydra** [comment]
![image](https://user-images.githubusercontent.com/11839238/82848951-6add6f00-9efe-11ea-962e-adaed0d6130a.png)
pls add this!

**Comment by TarasIvaschuk** [comment]
pls add!!!

**Comment by radek-jurica** [comment]
So I guess there is no way how to change the findmatchforeground color right?

**Comment by Iron27** [comment]
Yes, please add:
editor.findMatchForeground
editor.findMatchHighlightForeground (ideal, but optional as editor.findMatchForeground can likely offer sufficient contrast for both contexts)

Thank you!

**Comment by carpii** [comment]
`editor.findMatchForeground` has no effect

Is this still not implemented, or is there some theming stuff I should be using instead?

If not please consider implementing it, its a fairly basic setting and its been 7 years now
