### ISSUE TITLE
automatically back even after press spacebar

### ISSUE THREAD

**Issue by manjeettahkur** [Microsoft/vscode#29100]
- VSCode Version:  1.13.0
- OS Version:  Ubuntu 14.04

Steps to Reproduce:

 if I apply autosave feature on then cursor automatically back even after press spacebar or tab.if I turn off autosave functionally then it works fine, means after press spacebar cursor move to the next position

**Comment by bpasero** [comment]
@manjeettahkur do you have format on save enabled or trim trailing whitespace?

**Comment by manjeettahkur** [comment]
@bpasero  no settings are applied as you mention

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by manjeettahkur** [comment]
@bpasero  you are right I need  to more study about it because I install number of extensions so maybe one of those extension change the behaviour

**Comment by kennir** [comment]
Hi @manjeettahkur, I met same problem, did you know which extension caused this problem ?

**Comment by manjeettahkur** [comment]
@kennir have you use auto-save feature ?

**Comment by kennir** [comment]
@manjeettahkur  Sure, It's fine after files.autoSave removed from settings
