### ISSUE TITLE
Quick suggestions and emmet mismatch

### ISSUE THREAD

**Issue by Ser-Gen** [Microsoft/vscode#29105]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.14393

---

**Steps to Reproduce:**
1. Open css file
2. Enter `pb`, press <kbd>tab</kbd>
3. Get `page-break-after: `
4. Press <kbd>ctrl</kbd> + <kbd>z</kbd>, then <kbd>tab</kbd>
5. Get `padding-bottom: ;`

![vscodesuggestionsemmetmismatch](https://user-images.githubusercontent.com/1856145/27335431-0980e694-55d5-11e7-92bb-97208997a00d.gif)

**What is the expected behavior?**
Items in quick suggest menu must be sorted in accordance with emmet.

**Comment by ramya-rao-a** [comment]
`pb` -> `padding-bottom` is an Emmet feature where `pb` is an Emmet abbreviation which gets expanded to `padding-bottom`. This is what gets triggered when you hit Tab in the absence of the suggestion list.

What you see in the suggestion list is coming from the css language service which tries to determine the best match. `page-break-after` wins as `p` and `b` are closer than they are in `padding-bottom`

This is confusing. I agree.

Which is why, we are working on getting the Emmet abbreviation inside the suggestion list.

You can give this a try in our current Insiders

You can also try this in the stable build by setting `emmet.useNewEmmet` to `true`

Thanks for reporting!
