### ISSUE TITLE
Emmet takes way too much disk space

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#29123]
VS Code 1.12 for macOS was 188MB, while 1.13 is 235MB. That's a 25% increase of the overall size just for Emmet. The download itself grew from 63MB to 72MB.

![image](https://user-images.githubusercontent.com/22350/27346486-aebe4bac-55ed-11e7-966a-537ae95ecf30.png)

Although they are cool features, this seems like a very high price to pay for them.

Related to #28874 (I didn't want to hijack that one)

cc @Microsoft/vscode

**Comment by rebornix** [comment]
related https://github.com/Microsoft/vscode/issues/29054

**Comment by ramya-rao-a** [comment]
@joaomoreno  Actually, the root cause is #29054 which I assigned to you :) Thoughts?

**Comment by joaomoreno** [comment]
Great to know! Let's close this then! 👍

**Comment by ramya-rao-a** [comment]
Though #29054 is still a valid issue, the specific case of emmet bloating up was due to having typescript and vscode as dev dependency

Fixed with https://github.com/Microsoft/vscode/commit/6e366b8f9026bb65a250f0a7bca27dafad9439bd Now the size of the emmet folder under extensions is reduced to 3.6 MB
