### ISSUE TITLE
Menu Bar drop down fails on Debian 8 Linux

### ISSUE THREAD

**Issue by ghost** [Microsoft/vscode#29153]
Do you have a question? Please ask it on [Stack Overflow with `vscode` tag](http://stackoverflow.com/questions/tagged/vscode)

(Use Help > Report Issues to prefill these)
- VSCode Version:  1:13:1
- OS Version: Linux Debain 8

Steps to Reproduce:

1. Click Help
2. Move mouse to any menu item
Menu graphic changes to a black box with a circle.  All menu items are not visible.

Alternate work around is use the ctrl key combinations, but if none are available then the first letter of the sub menu item works for the first item only.  For example, Help, R gives you release notes.  Unable to reach Report Issues.
 
Interesting how the View menu item will allow you to move the mouse down to sub-menu options.

**Comment by bpasero** [comment]
@owencasaide can you share a screenshot?

**Comment by owencasaide** [comment]
Sorry, I  have moved on to another Linux distribution and do not have VS Code installed. I can tell you that the behavior I reported was consistent on all menu items except View. With View you would get the drop down that allowed you to select a sub menu item with the mouse. All the other menu items would present a black graphic with a gray circle positioned near the upper left corner of the black graphic. The circle was not perfectly round and it would change according to the size of the black surrounding box. When you clicked on the menu item it did open the list of sub menu items, but when you moved the mouse into the list to select a sub menu item, the list was replaced with the graphic as I described. With the graphic open you could use the ctrl key options or the first letter of an item in the list with out a ctrl key option, but not the second submenu item with the same first letter.I am just playing around with Linux and would not be offended if you closed the issue. I am starting to use VS Code on Windows which is working okay.  I am so new to Linux that I couldn't tell you how I got VS Code installed. I think I down loaded it and used the extractor function to open the package. Whatever came out of the box worked without much intervention on my part. That's all I remember. 11:48 AM, June 20, 2017, Benjamin Pasero <notifications@github.com>:@owencasaide can you share a screenshot?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




-- Sent from Yandex.Mail for mobile

**Comment by bpasero** [comment]
Needs more info, closing.
