### ISSUE TITLE
[php] Provide HTML tag matching/language service support

### ISSUE THREAD

**Issue by adred** [Microsoft/vscode#2915]
I don't know if it's just me but there's no support for HTML tag matching. If I click on `div`, every instance of `div` are highlighted instead of the closing `</div>`, which is a PITA.

**Comment by alexandrudima** [comment]
@adred Maybe you are on an old version?

![image](https://cloud.githubusercontent.com/assets/5047891/12971436/6fe6d35a-d09b-11e5-8822-d1e28cfa0525.png)

**Comment by adred** [comment]
![screen shot 2016-02-12 at 11 15 17 am](https://cloud.githubusercontent.com/assets/607534/12998062/31d53cca-d17a-11e5-81dc-43c98bf4e279.png)

OS X Yosemite. The same behaviour in Ubuntu 14.04.
VS Code version is 0.10.8

**Comment by sorinpopescu** [comment]
I have the same issue - http://prntscr.com/bnfaym

**Comment by LouWii** [comment]
👍

**Comment by nunoousapt** [comment]
Any update on this? 
I have the same issue.

**Comment by giancarlo88** [comment]
I'm also having the same issue.

**Comment by Lazerproof** [comment]
Same here

**Comment by naumanahmed19** [comment]
same here

**Comment by aga5tya** [comment]
Issue still persists on latest update,  on twig and php files atleast,  would love to hear if there is any progress?  @alexandrudima

**Comment by alexjose** [comment]
+1

**Comment by vasanth833** [comment]
+1

**Comment by rgfx** [comment]
+1

**Comment by robcaa** [comment]
+1

**Comment by moufeed** [comment]
+1

**Comment by cbrostrom** [comment]
+1

**Comment by bunkaisatori** [comment]
+1, I kindly ask to add this feature.

**Comment by BrunoQuaresma** [comment]
+1

**Comment by ales-k** [comment]
+1

**Comment by druellan** [comment]
Seems to match the keyword, not the pair. It is matching even the comments:

![2016-12-09_09h47_34](https://cloud.githubusercontent.com/assets/6965667/21049942/7b928b24-bdf6-11e6-8b35-e6dacc775ef3.png)

**Comment by firozz** [comment]
+1

**Comment by rschalch** [comment]
+1

**Comment by aga5tya** [comment]
@alexandrudima @aeschli, Is there any progress on this issue,  would be helpful if someone could point me in a direction to check the progress. Thank you for all your contributions.

**Comment by charanjits** [comment]
Any updates? Still facing the same issue with the latest release also v1.8.0...

![vs code - tag close start highlight issue](https://cloud.githubusercontent.com/assets/4351684/21284773/4199e492-c44c-11e6-9507-1b506adf41b2.png)

**Comment by krisbulman** [comment]
Changing the colour between the connecting line of the selected tag or an additional line in the margin would be ideal. Here is how webstorm looks in this scenario:

![closing-highlight](https://cloud.githubusercontent.com/assets/224268/21985358/9c3ac240-dbd0-11e6-8e27-6e286364900f.png)

**Comment by AlexPoirier1** [comment]
+1 here! I've been looking for an extension to do this until I found out it supposed to be built-in

**Comment by aeolingamenfel** [comment]
+1 still seeing this in 1.8.1

**Comment by Kiricon** [comment]
+1

**Comment by v33ns** [comment]
+1

**Comment by neeravp** [comment]
+1  
This is a much required feature for php / laravel developers to embrace VS Code. Most of the time the view or html is being written in `.php` or `.blade.php` file as far as PHP developers are concerned.  
VS Code is a promising tool, needs a little help from the team to make more Laravel/PHP devs try and embrace it.

**Comment by andrewmartin** [comment]
+1

**Comment by aeolingamenfel** [comment]
+1

**Comment by Hugocorp974** [comment]
It's deal breaker !
Come on Dev Team, we need this feature...

+1

**Comment by therawk** [comment]
Need this 

+1

**Comment by martin0852** [comment]
+1

**Comment by rahulnever2far** [comment]
+1

**Comment by dysol** [comment]
+1

**Comment by guilhermebrunoreis** [comment]
+1

**Comment by neuotq** [comment]
+1
Or maybe there is an extention for it?

**Comment by GoldenRust** [comment]
+1

**Comment by chrisjimallen** [comment]
+1

**Comment by amit-coditas** [comment]
i guess we have to deal with it, someone know of a extension that helps timebeing.

**Comment by guilhermebrunoreis** [comment]
for a while i'm using a different file associations settings, like below:

    "files.associations": {
        "*.tpl": "php",
        "*.php": "html"
    },

With this, the editor will recognize the php as a html file, and then we can see the tag matching.

**Comment by AlexPoirier1** [comment]
@aeschli By the way, it is not only for PHP. It does not work for any JSX file or JSX syntax in a `.js` file aswell. It would be a nice feature considering how React is becoming (already is) very popular.

**Comment by kjetilsg** [comment]
I have the same issue with the Pyramid Web Framework built with Python.

@guilhermebrunoreis solution worked for me by changing user settings to

`"files.associations": {
"*.pt": "html"
},`

**Comment by rifaldhiaw** [comment]
Thanks @kjetilsg 

I got this worked too on blade.

`"files.associations": { "*.blade.php": "html" }`

**Comment by ankitrg** [comment]
Can anyone point me how can I help/contribute towards this feature? By the amount of time it has taken to provide such a basic feature mean the team must be busy. I would love to contribute if someone can guide me. Thanks.

**Comment by afdallah-war** [comment]
+1

**Comment by chrisjimallen** [comment]
@rifaldhiaw @kjetilsg changing the file suffixes like that will disable any native intellisense it may have had before though right? So changing .php to act like .html will disable any .php support it had previously. Correct me if I'm wrong.

**Comment by tonypee** [comment]
+1

**Comment by mousetraps** [comment]
@ankitrg
> Can anyone point me how can I help/contribute towards this feature? By the amount of time it has taken to provide such a basic feature mean the team must be busy. I would love to contribute if someone can guide me. Thanks.

In order to achieve this, we'll need to include HTML as an embedded language. Improving our PHP+HTML experience will certainly be a priority in the coming months, and while I can't get to this *immediately*, I'm happy to share some preliminary thoughts and provide some quick pointers in case someone is interested in investigating it further.

## Dissecting the built-in HTML language service
A good example to look at is the built-in HTML language service, which embeds CSS and JavaScript. 
https://github.com/Microsoft/vscode/blob/master/extensions/html/client/src/htmlMain.ts#L47

A quick search reveals that the `initializationOptions.embeddedLanguages` is first used in the server initialize function, which is the main entrypoint the the language server: 
https://github.com/Microsoft/vscode/blob/master/extensions/html/server/src/htmlServerMain.ts#L52

The initialize function calls `getLanguageModes` as one of its first steps, which is defined here:
https://github.com/Microsoft/vscode/blob/master/extensions/html/server/src/modes/languageModes.ts#L53

`getLanguageModes` returns an object of type LanguageModes which includes a bunch of methods that map between the positions / language IDs, and the LanguageMode:
https://github.com/Microsoft/vscode/blob/master/extensions/html/server/src/modes/languageModes.ts#L38-L46

This helps use know which language server to ask (CSS, JS, or HTML) for requests like document highlighting (which is the feature described in this thread):
https://github.com/Microsoft/vscode/blob/master/extensions/html/server/src/htmlServerMain.ts#L209-L216

What's LanguageMode?
https://github.com/Microsoft/vscode/blob/master/extensions/html/server/src/modes/languageModes.ts#L19-L36

LanguageMode is an interface that gets implemented by each of the individual languages supported in the language service. It basically maps a language-specific ID (see `getId()`) to the language-specific feature implementations:
* HTML: https://github.com/Microsoft/vscode/blob/master/extensions/html/server/src/modes/htmlMode.ts#L12
* CSS: https://github.com/Microsoft/vscode/blob/master/extensions/html/server/src/modes/cssMode.ts#L13
* JS: https://github.com/Microsoft/vscode/blob/master/extensions/html/server/src/modes/javascriptMode.ts#L21

Now so far, this has all been plumbing - the *actual* logic for the HTML-specific features lives in `vscode-html-languageservice`, which gets pulled in as an npm module.
* https://github.com/Microsoft/vscode-html-languageservice/blob/920806f456f5991fa5840f0755edc77853963797/src/htmlLanguageService.ts#L120-L131

## Applying this to PHP
For PHP, we'll probably want to do something similar from the built-in PHP extension (at a high level, we want to have some way to distinguish between which language mode we're in, map that language mode to the corresponding feature implementation, and provide any other relevant context). PHP entrypoint here:
https://github.com/Microsoft/vscode/blob/master/extensions/php/src/phpMain.ts

For tag matching in particular, we care about `getDocumentHighlight`:
https://github.com/Microsoft/vscode-html-languageservice/blob/9ea1db325b7bb9c54f7e5fbb8c4a8474df150e7a/src/services/htmlHighlighting.ts#L11-L29

Now, one of the critical questions I glossed over when describing the HTML support above is "how do we actually differentiate between regions?" This is where things get a little trickier if you don't have a full lexer/scanner implementation because if you take the absolute simplest approach - e.g. simply look for the first start-tag, and the first end-tags, there are all sorts of edge cases like:
* `<?php // ?> *NOT PHP*`
* `<?php /* ?> *STILL PHP*`
* `<?php "hello ?> *STILL PHP*`
* 
```
<?php
$a = <<< 'PHP'
?> *STILL PHP*
```

So now we also need to account for heredoc, nowdoc, command expressions, comments, strings, template strings, etc. and any combination thereof.

The TextMate grammar (which is responsible for syntax highlighting) defines these rules, but we don't currently have a way to simply piggyback on this functionality from a language service, so we would either need to grit our teeth, and write it ourselves, or use an implementation that's already out there. Probably the easiest thing to do is use PHP's built-in tokenizer, `token_get_all` (see PHP validation logic for how we currently invoke PHP from the extension). `T_INLINE_HTML` will refer to all text outside of PHP, which is exactly what we want to know. 
* http://php.net/manual/en/function.token-get-all.php
* http://php.net/manual/en/tokens.php

And of course, token_get_all doesn't return positions, so we'd have to calculate those ourselves while iterating through the loop. E.g. we currently do this in the new PHP parser:
https://github.com/Microsoft/tolerant-php-parser/blob/master/src/PhpTokenizer.php#L75

Now that we have php and non-php blocks, we can start looking into tag matching.

Now let's take a simple example:
```
<html>
</html>
<?php
echo `hello world`;
```

This could conceivably get split up into two regions:
```html
<!-- HTML region -->
<html>
</html>
```
```php
/* PHP region */
<?php
echo `hello world`;
```
The HTML region could then get sent through for the HTML language service to find the document highlights. #winning

But wait. PHP is a templating language. Which means that you can also do stuff like this:
```php
<html>
<?php ?>
</html>
```

Now our exclusive document regions don't work so cleanly anymore because we get three of them:
* 1: HTML region
* 2: PHP region
* 3: HTML region

If we pass region 1 in alone, then we won't get proper highlights if the end tag lives in region 2 (the same is also true of the PHP code, where for instance a block's close brace can appear after an inline HTML block). So instead of sending in the regions alone to the language services, we actually need to replace everything in the middle of the regions with whitespace to generate the virtual document, which is exactly what the HTML language extension does:
https://github.com/Microsoft/vscode/blob/master/extensions/html/server/src/modes/embeddedSupport.ts#L198

## To be continued...
Anyways, hope you enjoyed that not-so-quick braindump of some of the considerations with this feature and potential places to start. Note that this is just one way of thinking about the problem, and there are also other approaches we could take. Additionally, I suspect it might be possible to simplify things for this feature in particular, but for now that's left as an exercise to the reader because it's getting late here in Seattle, and as much as I love you all, I also love sleep :wink:

cc @aeschli, @rebornix, @felixfbecker

**Comment by felixfbecker** [comment]
@mousetraps I think this should be added to LSP. The language server already has an AST, so it knows the exact ranges where other languages are embedded

**Comment by davebro** [comment]
+1

**Comment by JoelLisenby** [comment]
+1

**Comment by screengroove** [comment]
+1

**Comment by rafaelpimpa** [comment]
Hope it gets corrected soon.

**Comment by Olivia101** [comment]
Sublime Text does it really well with the help of the BracketHighlighter extension.

![screenshot_1](https://cloud.githubusercontent.com/assets/4064582/23927517/17624818-097f-11e7-8754-ae69a5114175.png)

**Comment by rgfx** [comment]
Found a temporary solution on [Stack Overflow](http://stackoverflow.com/questions/39401852/vscode-doesnt-highlighting-html-close-tags-in-php-files) Using the extension [Auto Rename Tag](http://stackoverflow.com/questions/39401852/vscode-doesnt-highlighting-html-close-tags-in-php-files)

![alt text](https://i.stack.imgur.com/SxqMx.png)

**Comment by DLMousey** [comment]
+1, Issue still present in v1.10.1, Not having much luck with @rgfx's auto rename tag workaround either, Seems to want to rename all or none of the closing tags in files with multiple `<?php` or `<script>` sections.

**Comment by fatasy** [comment]
+1

**Comment by ArtursDen** [comment]
I had this same problem, but with the end tags not being highlighted in .php files. In .html they get highlighted properly.

+1 for .php

**Comment by aboalwi** [comment]
+1
p.. p. p. please

**Comment by ArtursDen** [comment]
One little addition:

1. Just create a random.html file and copy+paste the HTML section of the PHP you're working with

2. Finish working with it (and enjoy end tags getting highlighted)

3. Just paste right back.

Doesn't take that much time and is a pretty ok workaround imo.

**Comment by michaelycus** [comment]
+1

**Comment by iamdevlinph** [comment]
Still not highlighting opening and closing tags. All keywords are highlighted.

VS Code: 1.10.2
OS: Windows 10

But the highlightning in the VS Code in my Ubuntu 16.10 just works fine. Also latest VS Code build.

**Comment by clicman** [comment]
@iamdevlinph have no luck on Ubuntu 16.04 on JSX with 1.10.2

**Comment by iamdevlinph** [comment]
@clicman tough luck. I will try to check the exact build number and OS version or whatever when I have the laptop again.

**Comment by AndyUPC** [comment]
I hope in your next version to correct this, I see that many have the same drawback when working for example php + html. Other editors do very well.
I hope that in a new version have this solved since vscode seems to me an excellent editor.

**Comment by DLMousey** [comment]
VS Code: 1.10.2
Windows 10 (10.0.14393)

Still having same issue
![image](https://cloud.githubusercontent.com/assets/8281699/24395789/b8994da8-1398-11e7-974b-c6e14218e89b.png)

**Comment by JasonScopServ** [comment]
+1 

We need this feature. It's so frustrating....

**Comment by BenRacicot** [comment]
+1 Yeah this is a must add. The feature is native in any IDE I've ever used.

**Comment by marchiore** [comment]
+1 
This will help us a lot!

**Comment by Rhiss** [comment]
+1

**Comment by sneppy** [comment]
+1

**Comment by iamdevlinph** [comment]
The broken tag matching seems to be happening in HTML codes that are inside other languages, like PHP and JavaScript. Putting a cursor on a tags seems to treat as "highlight keywords" because it is inside like JavaScript code.

Can we rename the HTML so that it will include other languages?

**Comment by yhyjy** [comment]
+1

**Comment by viktor1190** [comment]
+1

**Comment by Alexeyheyhey** [comment]
+1

**Comment by krisbulman** [comment]
@mousetraps Can we add a JSX label to this? It's also happening in React js components. Not sure if there is another issue for that or not.

**Comment by iamdevlinph** [comment]
@krisbulman I believe it happens on every HTML code that is inside another language.

**Comment by vincaslt** [comment]
+1

**Comment by erenhatirnaz** [comment]
+1
I have the same issue with twig.

**Comment by vincaslt** [comment]
Wrote a small extension that (almost) suits my needs. Here it is if you think you can find it useful: https://marketplace.visualstudio.com/items?itemName=vincaslt.higlight-matching-tag

**Comment by AndyUPC** [comment]
Hey **vincaslt** dont work

**Comment by vincaslt** [comment]
Mind telling me in detail by filing an issue?

**Comment by AndyUPC** [comment]
![captura](https://cloud.githubusercontent.com/assets/12195669/25020862/aa487200-2055-11e7-8d47-c0b9a98b5242.JPG)


I'm working with php and it does not work.

**Comment by felixfbecker** [comment]
@AndyUPC can you please discuss that in an issue at @vincaslt's repo? Thank you.

**Comment by vincaslt** [comment]
It only works on opening tags yet, but please post on my repo

**Comment by CarlosSouza** [comment]
+1

**Comment by kitsunekyo** [comment]
+1

+ heredoc doesnt get parsed properly

**Comment by DmitryNiko** [comment]
+1

**Comment by hyperjelly** [comment]
+1

For some reason my work computer does this just fine, but my home computer does not. The only difference is at work I'm on OSX Yosemite and here I'm on macOS Sierra...

**Comment by alkzzz** [comment]
+1

**Comment by felyx** [comment]
+1

**Comment by dantewebmaster** [comment]
+1

**Comment by roblourens** [comment]
Please, no more +1s - it makes the actual discussion hard to read and generates lots of notification noise. You can 👍  the top post if you like.

**Comment by Ikhan** [comment]
@AndyUPC Thanks man, for showing me the extension " highlight matching tag "

**Comment by ffpviana** [comment]
+1

**Comment by fabrobocom** [comment]
Found a quick workaround:
 1) Click the "Select Language Mode" at the bottom pane.

![langmode](https://cloud.githubusercontent.com/assets/11758061/26310133/9f6952d0-3ef7-11e7-8e4b-b3c0561eba38.JPG)

2) Select HTML from the Dropdown.

![selecthtml](https://cloud.githubusercontent.com/assets/11758061/26310308/45846146-3ef8-11e7-8af0-b9882aa5d4ca.JPG)

3) Do your tag matching.

![tohtml](https://cloud.githubusercontent.com/assets/11758061/26310371/6c35503e-3ef8-11e7-89b2-da715e2bc1e3.JPG)

 Switch back to PHP anytime same process. It's pretty quick. Hope this helps.

**Comment by mcarpenterjr** [comment]
This is one of those features you don't realize how nice it is until you switch to an editor that does not have it... Pretty sure this is also a feature when you sit down and say "We're making an IDE what are the must haves?" This is at the top of the list, just sayin'...  ¯\_(ツ)_/¯

**Comment by jerryjiao** [comment]
Use this extension:https://marketplace.visualstudio.com/items?itemName=vincaslt.highlight-matching-tag

Can solve this problem directly.

![img](https://i.imgbox.com/iIMnrqFm.gif)

**Comment by bmewburn** [comment]
Having the editor in HTML language mode will solve the tag matching issues. To get PHP completions and signature help in HTML mode install [Intelephense](https://marketplace.visualstudio.com/items?itemName=bmewburn.vscode-intelephense-client). PHP highlights and syntax colouring aren't currently available but it still provides a productive development experience.

![optimised](https://user-images.githubusercontent.com/5885195/27513357-705035a8-59a6-11e7-87ea-3901d2c9da62.gif)

**Comment by kinnedev** [comment]
@jerryjiao worked perfectly!! Thanks for the heads up on that package!

**Comment by Davemusic** [comment]
I was having the same issue and I got the easiest solution ever. Just install html spinnets extension. 
![capture1](https://user-images.githubusercontent.com/24985932/28520375-1a45fcbc-7024-11e7-908b-d186a1856cb4.PNG)

and just do some changes in setting file, goto file->preferences->settings
in the right hand side you will see User Settings 
just add this
,"files.associations": {
        // extension name : html
        "*.php": "html",
        "*.js": "html"
    }

**Comment by matheusggds** [comment]
@Davemusic did not worked here

OS Sierra 10.12.3
VS Code 1.14.2

+1

**Comment by taylorbryant** [comment]
+1

**Comment by stevie-c91** [comment]
+1

**Comment by webserviceXXL** [comment]
This would help a lot... +1

**Comment by webserviceXXL** [comment]
BTW: Until this ist fixed give the highlight-matching-tag extension a try. For me this is working perfectly (just a bit slow). https://marketplace.visualstudio.com/items?itemName=vincaslt.highlight-matching-tag

**Comment by drehimself** [comment]
+1 hopefully this gets fixed soon. The highlight-matching-tag extension does work for now but doesn't look very good IMO.

**Comment by Shehzad-Abdulcadir** [comment]
Don't expect this to be fixed anytime soon or ever in fact. I've seen similar threads with the same issue as this dating back to early 2014.

**Comment by anguswild** [comment]
+1

**Comment by spchaplin** [comment]
Hi! I would really appreciate matching tag highlighting being added for embedded HTML within PHP files.  The extensions mentioned on this page only partially work.  I looked at the development road map for VS Code and the focus seems to be JavaScript.  Are there any plans to add this functionality for PHP?

**Comment by bmewburn** [comment]
[This](https://marketplace.visualstudio.com/items?itemName=bmewburn.vscode-intelephense-client) forwards html highlight (tag matching) requests to the html language server when in mixed php/html files.

**Comment by spchaplin** [comment]
bmewburn, Thank you for the above link!  Using your "PHP Intelephense" extension solved the problem for me of html tag highlighting within php tags.  Your work is appreciated!

**Comment by tomliv** [comment]
My issue isn't really tag highlighting. It's emmet-like completion of html elements (type 'div' and hit tab or return and get <div></div>) within PHP code. Also, VS Code didn't know what the article element was in a php file - outside of PHP code.

**Comment by bennymeier** [comment]
Im writing xsl data and this is also not working for me. In html or php also. But there will be never a fix.

**Comment by bmewburn** [comment]
![intelephense](https://user-images.githubusercontent.com/5885195/33985887-f7a9d89c-e10f-11e7-8e6b-f5844e630149.gif)

@tomliv is the above what you where looking for?

@bennymeier the tag matching will work with xsl tags too. No intellisense though because it's being handled by the html language server. If there is an xsl language server out there then this could be easily be extended to forward to that instead.

The extension can be found [here](https://marketplace.visualstudio.com/items?itemName=bmewburn.vscode-intelephense-client)

**Comment by tomliv** [comment]
@bmewburn Maybe I'm not doing the settings right, but I am not getting the correct results. Where do I add this setting? User settings (command-,)?

**Comment by rez0n** [comment]
In Code Insiders html tags highlight already working a few stable releases of Code. Dont understand why not merging from Insiders to stable. Or i something missed?

Code Insiders
![image](https://user-images.githubusercontent.com/725860/34259728-0c2d0562-e66c-11e7-9960-431aa7d55afa.png)

Code stable
![image](https://user-images.githubusercontent.com/725860/34259758-28b09c44-e66c-11e7-8cfa-50dc0d44d6a5.png)

**Comment by tomliv** [comment]
@rez0n The issue is to have emmett-like tag completion INSIDE php. So, given:

`<?php
      div
?>
`

Hitting tab/return (or selecting from a hint menu) after the 'div' above would create `<div></div>`

**Comment by rez0n** [comment]
@tomliv Sorry, seems I'm choose wrong Issue.

Update: I'm checked, all issues about "highlight html matching tag" are closed. But in stable tags are not highlight both for html and php files. What i miss, option for enable it?

**Comment by aeschli** [comment]
Still works for me in the latest:
![image](https://user-images.githubusercontent.com/6461412/34779639-186f087e-f621-11e7-98d4-054aef60d0f3.png)

Please make sure that the language mode is `HTML` (not supported in `PHP`) and try with extensions disabled to make sure this is not an issue with an extension.
If you still see it, please file a new issue with the sample code.

**Comment by andremacola** [comment]
this is the kind of tiny little big giant feature that every editor needs.

**Comment by bryanlopezcodes** [comment]
same here

**Comment by eamodio** [comment]
I've found that `<input></input>` pairs break the tag matching.

If you focus on the `<div>`, it won't highlight the `</div>` because of the input (also focusing the `<input>` also won't highlight the `</input>` either)
```html
<div>
    <input id="foo" name="foo" type="checkbox"></input>
    <label for="foo">Show Git hovers</label>
</div>
```

Where as, the following will work
```html
<div>
    <input id="foo" name="foo" type="checkbox" />
    <label for="foo">Show Git hovers</label>
</div>
```

There may be other tags that break the matching too, but input is the one I've seen so far.

**Comment by andremacola** [comment]
_input_ is a self closed tag. There is no reason to use _</input>_

**Comment by eamodio** [comment]
While I agree, I don't think the tag matching should break when it comes across it.

**Comment by robertnicjoo** [comment]
should we go back to sublime, atom etc. ? :))

this is 2yrs and no fix!

**Comment by tomliv** [comment]
I already have. This issue is a big deal for me for the type of work I do most of the time. I keep Code up to date and 'check in' frequently to see progress.

Also, to be clear, this is NOT a 'highlight matching tag pair' issue. This is an emmet-like tag auto-close/completion issue - which all other major editors already do. Within php code, i should be able to type 'div' and hit tab/return and get '<div></div>' .  Sorry to reiterate this, but the thread seems to have strayed.

**Comment by robertnicjoo** [comment]
@tomliv actually is annoying me cause between hundreds lines of codes finding open/close tag is kind of time saving to me.

and what are you suggesting, to remove emmet?

**Comment by tomliv** [comment]
@robertnicjoo I'm not suggesting anything because I have no idea what it takes to make a text editor. :) I am, humbly, asking to have emmet, or what ever controls auto-close/completion, to work on html elements inside of php (and whatever other language that's broken - if any).

**Comment by KamasamaK** [comment]
@tomliv This _is_ a 'highlight matching tag pair' issue and you are the one straying it.

Your request for Emmet behavior in PHP is covered by the `emmet.includeLanguages` setting. e.g. `{"php": "html"}`

If this does not fulfill your request, please find or open a more appropriate issue.

**Comment by tomliv** [comment]
@KamasamaK OH boy..... my apologies. :(

**Comment by rgfx** [comment]
This extension works for me 

https://marketplace.visualstudio.com/items?itemName=vincaslt.highlight-matching-tag

**Comment by rimatla** [comment]
How do I change the background color of the a matching opening/closing tag?

I've tried:
```
 "workbench.colorCustomizations": {
        "editorBracketMatch.border": "#00d16e",
        "editorBracketMatch.background": "#fe6659",

    }
```
but the background color hasn't changed:
![screen shot 2018-02-23 at 11 58 30 am](https://user-images.githubusercontent.com/14306250/36609544-d2e1a82c-1892-11e8-9e92-65850d1bd638.png)

**Comment by aeschli** [comment]
@rimatla 
Try
```
    "workbench.colorCustomizations": {
        "editor.wordHighlightBackground": "#ff0000"
    }}
```

**Comment by rimatla** [comment]
@aeschli Thank you, that worked. Obscure naming convention on that one.

**Comment by petewulf** [comment]
Is there at least a working fix for matching tags in php files? All of the above suggestions are not working.
For me this is a very essential function because it slows down codewriting tremendously and i'm better reverting my editor back to sublime to be more productive and less prone to errors... 

This is not only happening for html tags, also for inline-strings, sql strings and so on.

Please guys fix this!

**Comment by aeschli** [comment]
https://marketplace.visualstudio.com/items?itemName=bmewburn.vscode-intelephense-client implements tag matching for the HTML code in `.php` files.
![image](https://user-images.githubusercontent.com/6461412/36775869-0cbd48b0-1c64-11e8-9f82-ce7308a994da.png)

Please give it a try and if it doesn't work for your use case, help to improve the extension and file an issue there.

**Comment by petewulf** [comment]
@aeschli Thanks for help, but intelephense isn't working for tag completion.

I installed `vincaslt.highlight-matching-tag` instead, which seems to do the job.

But nevertheless, this should be a core feature out of the box.

**Comment by aeschli** [comment]
@petewulf intelliphense also has code completion in html:
![image](https://user-images.githubusercontent.com/6461412/36890982-415fa3cc-1e00-11e8-8e66-5810fd4fe92b.png)

But this issue is about tag highlighting, not completion, so lets not continue the discussion here. If intelephense's code completion doesn't work in your scenario, file improvement requests directly against https://github.com/bmewburn/vscode-intelephense

**Comment by sshreya0808** [comment]
I am facing the same issue. Not sure how to handle this. This is  for react js app in visual studio code.

**Comment by aeschli** [comment]
@sshreya0808 This issue is about PHP. For React, please file a new issue with your code sample.

**Comment by sshreya0808** [comment]
@aeschli... Thanks

**Comment by irojasochante** [comment]
you know if there is a plugin for Visual Studio Code, which allows me to highlight opening and closing tags as well as the sublime text BracketHighlighter

**Comment by adal6a** [comment]
All of the suggestions are not working. 2yrs... Please fix this

**Comment by aeschli** [comment]
@adred Please try the Intelliphense extension and please file issues against the extension with a code sample that shows what's not working for you.

**Comment by aditya43** [comment]
Open `User Settings`, and make sure you have following set to `true`:
```
"editor.occurrencesHighlight": true,
```
![screenshot from 2018-03-13 12-34-11](https://user-images.githubusercontent.com/25119995/37327276-a5945b1c-26bb-11e8-82dd-31bf8d103779.jpg)

**Comment by toddicus13** [comment]
"editor.matchBrackets": true,
"editor.occurrencesHighlight": true

**Comment by Ashu131** [comment]
> Checked the settings

```
"editor.matchBrackets": true,
"editor.occurrencesHighlight": true
```
But Problem still the same @toddicus13 @aeschli @aditya43 
![vscodeerror](https://user-images.githubusercontent.com/25302874/38852877-18517836-4239-11e8-9216-2058565b849f.JPG)

**Comment by Ashu131** [comment]
Okay. It worked for me @ramya-rao-a

**Comment by LucaChiappino** [comment]
I don't know if there is some relation with this discussion but when the cursor is on a <div>,  the vertical red line (on the left in the image) that supposed to indicate the closing tag is not following the correct div but his parent

![image](https://user-images.githubusercontent.com/19210337/42169993-95f09674-7e15-11e8-8ba4-9d217792715e.png)

**Comment by KamasamaK** [comment]
@LucaChiappino That is the [indent guide](https://code.visualstudio.com/updates/June_2016#_indent-guides) and is unrelated to tag matching. The placement is intentional.

**Comment by roblourens** [comment]
As @aeschli says,

> marketplace.visualstudio.com/items?itemName=bmewburn.vscode-intelephense-client implements tag matching for the HTML code in .php files.

And it's not likely we will try to support this out of the box so I will close this.
