### ISSUE TITLE
Assess impact of multiroot workspaces on language extensions

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#29183]
exracted from #28344
- [x] JS/TS @mjbvz 
- [x] Go @ramya-rao-a 
- [x] C# @jrieken
- [x] Java @aeschli 
- [x] CSS @aeschli 
- [x] JSON @aeschli 
- [x] HTML @aeschli
- [x] PHP @roblourens  
- [x] eslint @dbaeumer 
- [x] tslint @egamma
- [x] C++ TBD
- [x] Python TBD
- [x] SQL TBD

**Comment by dbaeumer** [comment]
A couple of things to note here:

- quite some language servers start the server on the rootPath as the cwd. This is the case for all LSP language server and the TS language server
- having a different cwd will have big impact on how the language server behaves. So TS for example cuts the searching of the tsconfig.json file at the cwd. So it is NOT a going all the way up to /. So to support two workspace folders we either need to start two TS servers to ensure we don't change the behavior of the used tsconfig.json file.
- other servers use the cwd to resolve additional modules they need to load (for example jshint and tslint). Starting them on a different cwd will very likely result on not finding additional install npm packages.

**Comment by ramya-rao-a** [comment]
Go update:

Below features use `vscode.workspace.rootpath`. As long as there is a replacement for `vscode.workspace.rootpath` which would give the right folder path, these will be ok

- Build/lint/vet/test workspace
- Resolve file path for
     -  Config file for gometalinter
     -  Env file for debug, 
     -  Env file for test
- Workspace symbol search 

GOPATH
The extension tries to resolve the GOPATH to use via various means. See [GOPATH-in-the-VS-Code-Go-extension](https://github.com/Microsoft/vscode-go/wiki/GOPATH-in-the-VS-Code-Go-extension)

Once GOPATH is figured out this way, the `process.env['GOPATH'] is updated. So that when node processes are spawned to run Go tools for various features like format/lint/build/test etc. the Go tools are run in an env with the right GOPATH. 

With multi root workspace, there can be a case of different roots using different GOPATH. Therefore, the extension will need to listen in on an event for root change, so that it can update GOPATH appropriately

Go language server

The Go language server is in an experimental stage. It does not care about which folder was it run from. The use of language server is controlled by a setting and having it true for one root and false for another feels like a bad idea.

How would the `vscode.workspace.onDidChangeConfiguration()` work in the new model?
The Go extension listens to do this and updates GOPATH and the decision to whether to use the language server or not based on the settings.

**Comment by aeschli** [comment]
- CSS: No use of the workspace root
 - JSON: Uses the workspace root to resolve relative paths to schemas when made in the settings. Adoption to support multiple roots is not a problem but needs JSON to support folder specific settings with a way to know which settings got defined for which folder
- HTML: Uses the workspace root to resolve absolute links. Can be adopted when root folders are passed on the LS.

**Comment by aeschli** [comment]
Java uses the root folder as a starting point to find the project files: `pom.xml`, `build.gradle` and `.project` (Eclipse). From how I see it, adopting multi-root will require a way to ask the user/LS client which project to open if multiple project files are found. That's an addition that would be useful also in the single root scenario in order to be open projects in sub folders.

**Comment by jrieken** [comment]
AFAIK, the `omnisharp-vscode` extension uses the `rootPath` for two things: (I'll also connect with @DustinCampbell later this week)

1. Discover project files inside the root path to figure out what to launch. I believe that can be made aware of n-projects
2. Writing into `launch.json` and `task.json`. Unsure what the new story will be, some bits might be covered with the new task-api but that only solves half of the problem...

**Comment by mjbvz** [comment]
For JS/TS:

**Use of `workspace.rootpath`**
We mainly use the workspace root for resolving the location of js/tsconfig files. These should be easy enough to update for handling multiroot workspaces and I've already made initial changes to support this in 1.14. More testing is required

**Implicit Projects**
An implicit project is created for all open js/ts files that are not part of an actual js/tsconfig project. Currently, I believe that implicit projects are shared across all opened root folder. We instead likely want a separate implicit project for each root folder.

**tsconfig.json tasks 2.0**
I need to sync with Dirk about how tasks are expected to work in the multi-root world. I believe the build command should only build `tsconfig` files in  the current root, not all `tsconfig` files across all roots. These changes should not be too hard to make.

**Different TSServer Versions**
Each root folder may set a different `typescript.tsdk` setting. An extreme scenario could see a user opening a folder that users TS 1.8 and then another that uses TS 2.4. Supporting that scenario would require multiple tsservers which will be too resource heavy. Instead, at least initially, we plan to start a single TypeScript server that uses the TypeScript version from the first root folder. 1.14 contains initial work to make this happen but we need additional testing of this scenario.

**Comment by dbaeumer** [comment]
@mjbvz one more thing: when the tsserver starts the cwd of the tsserver process is set to the workspace root. This information is then used by the tsserver to stop traveling up the parent chain to look for tsconfig.json files (it stops to the cwd of the tsserver process). So to fully support n root folder we either need to start n tsservers or we need to adopt the server. For the initial case of a primary root folder we should set the cwd to this first folder.

**Comment by roblourens** [comment]
For PHP, this should be straightforward. @felixfbecker has a good summary here: https://github.com/Microsoft/vscode/issues/396#issuecomment-306294518

Essentially the PHP extension will index .php files under all root paths. They contribute symbols to the global namespace, and features like go to definition are based on names in the global namespace.

Minor complications are that the PHP language server will have to watch for nested root paths and not index files twice. And two root folders could contain PHP projects that aren't related but have name collisions. But that's just why you use proper namespaces.

**Comment by egamma** [comment]
The **vscode-tslint** language server would be a candidate for running as a shared server across all root folders. vscode-tslint is built on top of the `vscode-language-client` and `vscode-language-server libraries. These libraries assume that there is a single workspaceRoot and a single set of settings for this root.

Discussed it with @dbaumer and he will explore a shared server for `vscode-eslint`.

**Comment by dbaeumer** [comment]
I added support to the LSP to start a client/server pair per workspace folder and outlines the support to the C++ extension owners.
