### ISSUE TITLE
When editting multiple occurences(Ctrl+F2), pressing end causes cursor to be out of sync in some cases

### ISSUE THREAD

**Issue by deanagan** [Microsoft/vscode#29227]
Do you have a question? Please ask it on [Stack Overflow with `vscode` tag](http://stackoverflow.com/questions/tagged/vscode)

(Use Help > Report Issues to prefill these)
- VSCode Version: 1.13.1
- OS Version: Windows 7

Steps to Reproduce:

1. Create sample file:
Hello
Hello
/*Hello*/
2. Put cursor after 'H' and press ctrl+F2
3. Press end button.

Notice that the cursor for the 3rd line (commented out Hello) goes to the end (after '/'). This makes it difficult to rename all occurences of "Hello" when accidentally pressing end because the cursor is out of place for items like in line 3 above.

**Comment by alexandrudima** [comment]
This works as expected for me. Perhaps there is something else to it? Can you reproduce when running `code --disable-extensions` ?
![29227](https://user-images.githubusercontent.com/5047891/27418398-2d6f9fb8-571b-11e7-8d45-541da8b49b35.gif)

**Comment by deanagan** [comment]
Sorry for the incomplete info. I think it could be my understanding of the feature.
My understanding for "Change All Occurrences" is that the highlighting and modification is localized to the word being modified. Here's a better example:
![test](https://user-images.githubusercontent.com/6564227/27453467-ebecdcda-57d9-11e7-8bec-c3bc3dc818bf.gif)

Notice that I want to change the class Symbol to SymbolChangeThis. To do that, I press Ctrl+F2 on the Symbol. Suppose, I want to add a suffix to the class name. My tendency for that would be to press the end button so I go straight to the end of the class name. But in line 7, because there are extra characters at the end, the cursor goes straight there. 

To me, it would make sense for the end button on line 7 to go to the end of Symbol instead of after the semi-colon.

**Comment by alexandrudima** [comment]
Thank you for getting back to me.

This is as designed. `Ctrl+F2` is a language agnostic feature that adds multiple cursors at all occurrences of a word (including in comments, i.e. it is not semantic based). Multiple cursors can be added from a number of actions (such as alt/ctrl + clicking -- depending on a setting, using `ctrl+d`, `ctrl+alt+up/down`, searching for something and while in the find input pressing `alt+enter`, etc. etc.). In all cases, multiple cursors behave the same way, there is no special context that e.g. multiple cursors were created from `ctrl+f2` and that then they should behave in a special way.

The `ctrl+F2` is "a poor man's rename". It can be used to work around languages where there is no rename provider implemented by an extension. The rename, `F2`, is the "real" rename. It is semantic and works across files and is, IMHO, what you currently expect `ctrl+F2` to be. However, since `F2` is semantic, it will only be present for languages where there is an extension implementing it.

e.g. TypeScript / JavaScript, where when pressing `F2` on a symbol, a textbox where a new symbol name can be entered is shown:

<img width="403" alt="screen shot 2017-06-23 at 08 44 21" src="https://user-images.githubusercontent.com/5047891/27469505-2f4610d0-57f0-11e7-97c9-155a71ddc978.png">
