### ISSUE TITLE
just coding,my cpu is 80%

### ISSUE THREAD

**Issue by yy7054wyq5** [Microsoft/vscode#29240]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|project-manager|alefragnani|0.18.1|
|angular1-code-snippets|alexandersage|0.0.3|
|ng-template|Angular|0.1.3|
|path-intellisense|christian-kohler|1.4.2|
|vscode-eslint|dbaeumer|1.2.11|
|jquerysnippets|donjayamanne|0.0.1|
|vscode-html-css|ecmel|0.1.7|
|tslint|eg2|0.15.0|
|vscode-npm-script|eg2|0.2.0|
|vscode-great-icons|emmanuelbeziat|2.1.8|
|auto-close-tag|formulahendry|0.4.2|
|auto-rename-tag|formulahendry|0.0.14|
|vscode-auto-open-markdown-preview|hnw|0.0.4|
|docthis|joelday|0.4.5|
|Angular2|johnpapa|2.3.3|
|HTMLHint|mkaufman|0.3.3|
|vscode-filesize|mkxml|1.0.0|
|debugger-for-chrome|msjsdiag|3.1.4|
|code-settings-sync|Shan|2.8.1|
|autoimport|steoates|1.2.2|
|JavaScriptSnippets|xabikos|1.4.0|
|Material-theme|zhuangtongfa|2.8.8|;

---

Steps to Reproduce:

1.just coding,my cpu is 80%
2.maybe i use gulp ? but i close vscode, this still happen.
![code](https://user-images.githubusercontent.com/11879742/27417029-ca51501a-5743-11e7-9b93-effba72487ee.png)

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.
