### ISSUE TITLE
Multi root support for extensions management

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#29242]
## Workspace recommendations
Today we scan for a `extensions.json` inside the workspace `.vscode` folder: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/extensions/browser/extensionsActions.ts#L1227 and also here https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/extensions/electron-browser/extensionTipsService.ts#L71

This does not work in a multi root environment. I think we should instead go over all root folders and collect all extensions that are recommended.

**Comment by sandy081** [comment]
### Workspace disabled extensions
I do not think we would need to map workspace disabled extensions to the opened folder. It can be treated as the other UI state. Since this is stored in local storage, this would have got fixed with local storage migration.

### Workspace recommendations
- We can show recommendations from all root folders which the PR #32106 does.
- Tricky part is with the action to configure workspace recommendations which opens the `extensions.json` file. Another idea is to have `extensions` section in workspace config file just like `settings`, `tasks` and `launch` and this section contains recommendations for the workspace?

**Comment by bpasero** [comment]
@sandy081 agree that extension enablement per workspace should be fine.

As for recommendations, I think ideally we have recommendations both on the code-workspace-file level as well as within a folder. The reason is that both concepts can be shared by users and there may be the interest to share these recommendations in both cases:
* from the code-workspace file
* from an individual folder

I think the actions would need to ask the user where to store the recommendations and we would need to support the extensions-recommendations section also from the workspace file. 

Maybe to begin with we take it easy and just prompt to which folder to store the recommendations.

**Comment by sandy081** [comment]
Thanks @bpasero. I am in the same thinking to consider recommendations similar to tasks and launches. Agree that we can prompt for folder to configure recommendations. This will be similar to Opening Settings commands.

![image](https://user-images.githubusercontent.com/10746682/29623758-b6764d7e-8827-11e7-8932-53e12cab216d.png)

**Comment by sandy081** [comment]
Verification:

- Verify that workspace recommendations are union of those configured in Workspace configuration file (in a MR workspace) and in `extensions.json` file in all Workspace folders.

- Verify that there are actions to configure workspace recommendations at a workspace level and also at workspace folder level.
