### ISSUE TITLE
autoIndent doesn't handle indented wrapped TS lines well

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#29285]
```ts
if (a) {
	b = `foo` + 
		`bar`;
}
```

Put cursor after `}` and press enter:

<img width="231" alt="screen shot 2017-06-22 at 12 48 14 pm" src="https://user-images.githubusercontent.com/2193314/27452858-13fd99d0-5749-11e7-8980-06b951507a05.png">

Ran into this while changing some terminal code, specifically:

```ts
		if (fgColor) {
			css += `.monaco-workbench .panel.integrated-terminal .xterm { color: ${fgColor}; }` +
				`.monaco-workbench .panel.integrated-terminal .xterm:not(.xterm-cursor-style-underline):not(.xterm-cursor-style-bar).focus .terminal-cursor,` +
				`.monaco-workbench .panel.integrated-terminal .xterm:not(.xterm-cursor-style-underline):not(.xterm-cursor-style-bar):focus .terminal-cursor { background-color: ${fgColor} }` +
				`.monaco-workbench .panel.integrated-terminal .xterm:not(.focus):not(:focus) .terminal-cursor { outline-color: ${fgColor}; }` +
				`.monaco-workbench .panel.integrated-terminal .xterm.xterm-cursor-style-bar .terminal-cursor::before,` +
				`.monaco-workbench .panel.integrated-terminal .xterm.xterm-cursor-style-underline .terminal-cursor::before { background-color: ${fgColor}; }` +
				`.monaco-workbench .panel.integrated-terminal .xterm.xterm-cursor-style-bar.focus.xterm-cursor-blink .terminal-cursor::before,` +
				`.monaco-workbench .panel.integrated-terminal .xterm.xterm-cursor-style-underline.focus.xterm-cursor-blink .terminal-cursor::before { background-color: ${fgColor}; }`;
		}
```

**Comment by rebornix** [comment]
Root cause: don't have a clue whether the *unexpected* indentation of previous is intentional or not.

Atom/Sublime/TextMate don't have this issue as they only change indentation when type, if you press enter, it doesn't change the indentation as they think the indentation of current line is intentional so it no longer modify that.

@mjbvz do you think it's a good idea to disable indentation check on Enter?

**Comment by Tyriar** [comment]
I've use this pattern pretty frequently, either having 1 or 2 indents on wrapped lines. I'd likely opt to disable if it stayed as is. Here's another common thing I do:

```
if (someVeryLongConditionLine === true ||
    andAnotherOne) {
  doSomething();
}
```

It looks much nicer with 2 space indent 😄

**Comment by Tyriar** [comment]
The current behavior is a little better but still not ideal. Consider the following:

![image](https://user-images.githubusercontent.com/2193314/27604854-8331c31e-5b2f-11e7-8d0c-f6155fe82f7b.png)

Move up:

![image](https://user-images.githubusercontent.com/2193314/27604872-91873656-5b2f-11e7-8924-4a3891c10d06.png)

Move down:

![image](https://user-images.githubusercontent.com/2193314/27604885-9a57f162-5b2f-11e7-8ad8-4d60f1d2074b.png)

**Comment by rebornix** [comment]
Move lines up and down around the intentional indentation can lead to this problem, however if you are just moving lines across your intentional changed area, it'll not affect your final content

![movelines-wrapped](https://user-images.githubusercontent.com/876920/33100867-c993f034-ceca-11e7-9acd-5de35ca387a1.gif)

I'd like to move this fr/bug to backlog at this moment.
