### ISSUE TITLE
[html] allow to turn off underline in the src and href properties of the HTML file

### ISSUE THREAD

**Issue by jsonvot** [Microsoft/vscode#29293]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|vscode-caniuse|akamud|0.5.3|
|project-manager|alefragnani|0.18.1|
|vscode-refresh-html|bajdzis|0.0.2|
|vscode-html-css|ecmel|0.1.7|
|vscode-great-icons|emmanuelbeziat|2.1.8|
|php-debug|felixfbecker|1.10.1|
|auto-rename-tag|formulahendry|0.0.14|
|beautify|HookyQR|1.1.1|
|crane|HvyIndustries|0.3.6|
|output-colorizer|IBM|0.1.1|
|easy-icons|jamesmaj|0.3.1|
|autofilename|JerryHong|0.1.3|
|format-indent|Kasik96|1.3.0|
|string-manipulation|marclipovsky|0.1.0|
|PowerShell|ms-vscode|1.4.1|
|vuehelper|oysun|0.1.0|
|vscode-icons|robertohuertasm|7.9.0|
|indenticator|SirTori|0.4.2|
|guides|spywhere|0.8.3|
|JavaScriptSnippets|xabikos|1.4.0|
|Material-theme|zhuangtongfa|2.8.9|
|html-css-class-completion|Zignd|1.7.0|;

---

Steps to Reproduce:

1.you cannot cancel the underline in the SRC and href properties of the HTML file

**Comment by aeschli** [comment]
@jsonvot What do you mean by 'cancel'? Disable?

**Comment by kilevvri1** [comment]
@jsonvot Yes, I have this issue too.

**Comment by aeschli** [comment]
@jsonvot Why do you want to disable the link feature?

**Comment by aeschli** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.
If you disagree and feel that this issue is crucial: We're happy to listen and to reconsider.
Maybe you want to give it a try yourself and provide the feature through an extension or a PR: We're happy to give advise and get you started.
Thanks for your understanding. Thanks for helping and happy coding!
