### ISSUE TITLE
Best workflow for viewing PR in VSCode?

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#29397]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:13:05.928Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|theme-sapphire|Tyriar|0.2.1|
|quokka-vscode|WallabyJs|1.0.36|
|nord-visual-studio-code|arcticicestudio|0.3.0|
|vscode-eslint|dbaeumer|1.2.11|
|tslint|eg2|0.15.0|
|prettier-vscode|esbenp|0.19.1|
|Go|lukehoban|0.6.62|
|debugger-for-chrome|msjsdiag|3.1.5|
|vetur|octref|0.8.5|
|java|redhat|0.6.0|
|vscode-icons|robertohuertasm|7.9.0|
|sass-indented|robinbentley|1.4.1|
|language-stylus|sysoev|1.7.3|
|vim|vscodevim|0.9.0|;

---

@bpasero 
I remember previously you talked about how you views large PR in VSCode instead of GitHub for diff and easier jumping around. Wondering if you mind sharing your workflow, or is there any extension you are using.

I was trying to achieve that by checking out PR in a branch, `git reset HEAD~10` if the PR has 10 commits. But that's problematic if the PR merges in master or do updates. Also if I want to push changes to PR, I can't do a commit again and has to reclone that branch.

Thinking it'd be awesome to add a Custom View to Git Viewlet for reviewing / switching-between PR seamlessly.

/cc @Microsoft/vscode Also would like to learn how you are reviewing PRs!

**Comment by jens1o** [comment]
I'm interested into this, too!

**Comment by bpasero** [comment]
@octref I am using the diff feature from GH pull requests:
* add .diff to the URL (e.g. https://github.com/Microsoft/vscode/pull/12400.diff)
* download the file
* from the command line: `git apply file.diff`

Of course this does not allow you to do changes on the PR, it is just good for reviewing the change.

In case the diff does not apply because the PR is out of sync with master, do this:
* git clone repository of PR (master)
* git remote add upstream https://github.com/Microsoft/vscode.git
* git fetch upstream
* git co `<branch of PR>`
* git merge upstream/master
* git push

**Comment by octref** [comment]
@bpasero Thanks. I'll try to put together an extension to simplify this a bit...Doing this everyday is a pain.

**Comment by eamodio** [comment]
@chrmarti It would be great if something like this flow was integrated into the new GitHub Issues & PR extension

**Comment by chrmarti** [comment]
@eamodio: @rebornix has something in the works for that: https://github.com/Microsoft/vscode-github-issues-prs/pull/3

**Comment by eamodio** [comment]
@chrmarti @rebornix awesome -- looking forward to it
