### ISSUE TITLE
[go] Indentation for "case" lines in "switch" and "select"

### ISSUE THREAD

**Issue by kylelemons** [Microsoft/vscode#29413]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.6.5|
|Go|lukehoban|0.6.62|;

---

Steps to Reproduce:

1. Add a `case` statement to a `switch` block

Expected behavior:

1. `case` line outdents to line up with `switch`/`select`

Actual behavior:

1. `case` remains on the same level as the code inside the `case` until `gofmt` (run on save) fixes it

Example

![example recording showing the incorrect indentation](http://g.recordit.co/CG6U12vRNb.gif)

**Comment by ramya-rao-a** [comment]
@rebornix Can this be done by https://github.com/Microsoft/vscode-go/issues/1043?

**Comment by rebornix** [comment]
@ramya-rao-a  yes if the request is 

> case line outdents to line up with switch/select

while setting the increaseIndentPattern, make sure `switch (\S)* {`(or similar) is ruled out

**Comment by ramya-rao-a** [comment]
Fixed with https://github.com/Microsoft/vscode/commit/e6c60418fd865c65b114211f4148c1268277b217

![switch](https://user-images.githubusercontent.com/16890566/28944590-056c63e4-7858-11e7-848d-f953fdba489e.gif)

If you are using the Go extension, then wait until the next update (0.6.64) to see the fix.
If you are not using the Go extension, then you should be able to see the fix in VS Code 1.15
