### ISSUE TITLE
Task API feedback

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#29427]
Just small things

* `TaskGroup` has a private ctor which is a little mean but I believe I understand why we have it that way. We have to make sure that we don't break anyone when we make it public, but I think its OK. 
* `ShellExecutionOptions` should be an `interface`, not just `type`
* In the provider function make the cancelation token optional like in other providers
* We need a better name for `TaskKind`... The `xyzKind`-naming scheme is already used by enums, like `TaskRevealKind`. Maybe `TaskData` because it is the serialisable portion of a task?

**Comment by dbaeumer** [comment]
- `TaskGroup`: I tried to leave the constructor out but then I get compile errors since a default constructor with no arguments is used. Since I haven't tested the own group stuff for June the best I could come up with is to make the constructor private. When we have full custom group support we make it public. Shouldn't break anyone.
- `ShellExecutionOptions`: could catch. That was not intended. Done
- done the cannelation token
- `TaskKind`: I was thinking about this as well. I actually do think it is a kind and matches our definition of kind. If the kind was a single property and a fixed set we would have had something like this.
```
enum TaskKind {
   npm: ...
   gulp: ...
}
```
So having kind in the name is not bad since it defines a kind element. What is about `TaskKindElement` or `TaskKindInfo`.

**Comment by dbaeumer** [comment]
Some more ideas: TaskDefinition, TaskKindDefintion.

**Comment by dbaeumer** [comment]
I don't like TaskData since it sounds like 'we couldn't come up with a better name' :-)

**Comment by jrieken** [comment]
> I don't like TaskData since it sounds like 'we couldn't come up with a better name' :-)

True story, I like `TaskDefinition` and also `TaskKindDefinition`(likes in that order)

**Comment by dbaeumer** [comment]
Lets go with `TaskDefinition` then.

**Comment by dbaeumer** [comment]
I still kept it in proposed that you can have another look.
