### ISSUE TITLE
Move line up drops a line

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#29457]
See attached recording and sample snippets

* select the `whitespaceCharacter`-array with an empty selection on its last liine
* move up into be new class
* 💥 the last line gets lost half way

```ts

const regexpOracle = new class {

}

function regexpMatchMightContainWhitespace(regexp: RegExp): boolean {
	const { source } = regexp;

	const whitespaceCharacters = [
		'.', '\\s', ' ',
		'\f', '\n', '\r', '\t', '\v',
		'\u00a0', '\u1680', '\u180e', '\u2000', '\u2001', '\u2002', '\u2003', '\u2004', '\u2005', '\u2006', '\u2007', '\u2008', '\u2009', '\u200a', '\u2028', '\u2029', '\u202f', '\u205f', '\u3000', '\ufeff'
	];



	let idx = source.indexOf('.');
	if (idx >= 0 && source[idx - 1] !== '\\') {
		return true;
	}

}
```

![jun-26-2017 15-40-37](https://user-images.githubusercontent.com/1794099/27541930-07ad2192-5a86-11e7-844e-d57d16b907a7.gif)

**Comment by rebornix** [comment]
It's not a new issue actually, which means it has nothing to do with auto indent.

Code Stable
![movelines-boundary](https://user-images.githubusercontent.com/876920/27547258-429cee7c-5a4a-11e7-9ba5-bb2a1ffdc22c.gif)

The root cause is we won't expand the selection if the endColumn of the selection is 1. cc @alexandrudima

**Comment by jrieken** [comment]
@rebornix In the gif I have shared the line reading `    ];` moves a few lines up (from 97 to 94) and then sticks there. I don't think that is to be discussed but a bug. The behaviour must be consistent, no matter how it is

**Comment by rebornix** [comment]
@jrieken make sense, I'm convinced :)

![movelines-boundary](https://user-images.githubusercontent.com/876920/27550602-2a861844-5a55-11e7-929b-534d6ba4214e.gif)

**Comment by rebornix** [comment]
Revisit this issue as my previous fix for this issue actually leads to https://github.com/Microsoft/vscode/issues/29713 and https://github.com/Microsoft/vscode/issues/29682 . 

The underlying problem of this issue is how we handle the empty ending line

* Select several lines, and make sure select only whitespaces of last line
* Move Lines to trigger auto indent
* Auto indent adjusts the indentation and in some cases, the whitespaces selected in the last line is shrinked to one single cursor
* Move Lines again. The last line is not treated as part of the moving block (see https://github.com/Microsoft/vscode/issues/29457#issuecomment-311096218).

We have this behavior from the very beginning. It helps a lot as when users select several lines, they may happen to select the beginning of one line below. My first fix is if you have auto indent, then I'll always see this line as part of the moving block, which is a breaking change.

Now I reverted this change and the new way to mitigate this issue is 

* Move Lines
* If the indentation of the last line shrinks to empty, and we no longer select anything in the last line, we automatically select one more character, just to make sure this line is still in the moving block.

It's not a clean fix but as our Move Lines command is stateless, this fix solves most of the problem. Let me know if you have better ideas on this and look forward to feedback of all of you.
