### ISSUE TITLE
Typescript auto completes on open parenthesis

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#29477]
In the below gif, I have typed `end` which gives me a few suggestions
Then I type `(`

Expected: `(` gets written to the editor
Actual: The first suggestion from the list is auto completed

![eager](https://user-images.githubusercontent.com/16890566/27553074-6d9bb5fe-5a5e-11e7-91d7-4b3aa104f76a.gif)

**Comment by mjbvz** [comment]
Completing on `(` is as-design in TS files when the completion is a function. You can disable it by setting `"editor.acceptSuggestionOnCommitCharacter": false`

It looks like the bug is that the `encodeUri` completion is even being returned in this case. What is the context of where you are typing? Are you inside of a class or object literal?

**Comment by ramya-rao-a** [comment]
> It looks like the bug is that the encodeUri completion is even being returned in this case.

That was my main issue too

It doesn't repro without the preceding `get`.
I was inside an interface, but you can repro it anywhere as long as the `get` precedes it

**Comment by mjbvz** [comment]
Thanks. Seems to only repo in interfaces and not in classes, at least in TS 2.5. I've opened https://github.com/Microsoft/TypeScript/issues/16784 to track this upstream
