### ISSUE TITLE
Icons for folding and unfolding

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#2948]
I'm working on adding folding to the editor. At the beginning of the line we show twisties that signal where you can fold and which ranges are already folded.
The folding arrows are only shown when hovering over the glyph margins. Unfold arrows are always visible.
The current prototype uses the twisties from the file explorer (16x16, arrow-collapse-dark.svg)
The following screenshot is made with the mouse over the glyph margin:
![image](https://cloud.githubusercontent.com/assets/6461412/12990622/a493a05e-d10b-11e5-81ab-5c2062d20f10.png)

The following screenshot also shows git line decorators. The mouse is somewhere in the text area.
![image](https://cloud.githubusercontent.com/assets/6461412/12990670/e365726c-d10b-11e5-99ea-0c406966a189.png)

**Comment by aeschli** [comment]
@stevencl @bgashler1 @egamma @chrisdias FYI

**Comment by aeschli** [comment]
To play around with the prototype, check out the aeschli-folding branch

**Comment by ianwesterfield** [comment]
I was excited to check our your branch last night. Looked really good and I'm excited to finally get some folding, so major kudos!

A couple of feature requests (want me to open new issues?):

1) Hovering over ellipses acting like a code peek would be awesome. Moving the mouse out could close  the peek instead of clicking the glyph.

2) I would reward you many :beers:  if VS Code could remember my folded ranges per project file - perhpas settings in ./.vscode or the like?

**Comment by Tyriar** [comment]
Will themes be able to control the arrow colors? They may clash with certain themes even if there are just standard dark and light versions of them.

**Comment by egamma** [comment]
Very nice and the folder regions are even remembered.

I find it somewhat stressful to hit the twisties, they should have a larger hit target area.

**Comment by ianwesterfield** [comment]
Along the lines of what @egamma said: To me, the glyphs seem overly inconspicuous. 

Perhaps just solid white filled for dark theme and solid black for light themes, and maybe a bit larger?

**Comment by bgashler1** [comment]
@aeschli very nice work!

## Proposed Design
Here is what I'm thinking on the look and feel.  It is based on Visual Studio's experience with code folding.
![visual-studio-way](https://cloud.githubusercontent.com/assets/11839736/13024000/b7bda056-d1a3-11e5-8c6b-10487166968c.gif)
- We would use a tree view expander and collapse icon
- `#989898` for the line and 1px border-color

## Previous Designs
### In-context affordance for folding
This was an interesting idea, but I worry that it may not be scannable as easily to the eyes as a user tries to find where the folding expanders are in his/her code.  They may also be confused with code since they are inline.  Here it is.
![code-folding-02](https://cloud.githubusercontent.com/assets/11839736/13023499/3b9599de-d19e-11e5-9972-0514ce3b1545.gif)

### Hierarchical in-context
Some IDE's do a similar approach.  I have a competitive analysis doc if you want to take a look.
![leaving-it-open-all-the-time](https://cloud.githubusercontent.com/assets/11839736/13024043/933758a2-d1a4-11e5-9224-eb20857b43a0.png)

**Comment by ianwesterfield** [comment]
@bgashler1, love your points, but really loath the verticals context lines. They really gunk up the screen.

**Comment by ianwesterfield** [comment]
PS - please don't fold the closing brace - Atom does this and so many people have asked that it be left exposed.

**Comment by stevencl** [comment]
I too like the look of the first alternative design but does it offer a larger hit area (as per @egamma's suggestion)? Can the user click on the vertical line for example to collapse the region?

Can you also try showing what it looks like if you don't fold the closing brace?

It might also be worth looking at how this works/looks for other languages. For example, will this work just as well with HTML, CSS, Visual Basic (and other languages that don't use punctuation marks as block delimiters)?

**Comment by Ristaaf** [comment]
I love the Visual Studio design with plus and minus sings and the line, like the proposal of @bgashler1, however I would like to fold the closing brace too (currently looking at a file with around 40 functions and with them all folded it takes up 33% more space than needed (empty line, function declaration and closing brace instead of empty like and function declaration)), like visual studio does, so please make that an option.

**Comment by LKorowicki** [comment]
Closing brace could be folded like this:

`function simpleMethod() { ... }`

instead of

`function simpleMethod() { ...`

I am definitly for folding closing brace.

**Comment by bgashler1** [comment]
@LKorowicki and @ianwesterfield, I agree that if we show one brace we should show both.  @Ristaaf, you bring up a very good point about how VS does it.  These are both very good ideas that we will be considering.

**Comment by bgashler1** [comment]
@stevencl It's not clear in the pictures here, but I would like to make these expandos slightly larger in VS Code than in VS for this reason.  That way users get a visual reassurance that the hit area is larger instead of merely including a large and forgiving hit target.  I'm thinking the hit target should be the height of the line with some padding to both the left and the right.  I'll post some more images soon that we can discuss.

**Comment by Nimzozo** [comment]
Great work !

I'm 100% sure my favourite is __2. Hierarchical in-context__.
- The [+] / [-] signs are the best because really clear. 
- It helps to see the hierarchy in the code !!

Will this be in the next release ? Or are you doing an extension ?

**Comment by ianwesterfield** [comment]
@LKorowicki I'm digging your suggestion for folding the closing brace to the same line, but keeping it visible.

**Comment by bgashler1** [comment]
@Nimzozo: This will be in the actual product.

**Comment by Spown** [comment]
I'm also for **Hierarchical** folding. ``On hover shoving/always visible`` can be a configurable option with either as default. In case of ``always visible`` I would still make the controls 50% opacity and 100% if hovered over. The **Chevrons** kinda defeat the purpose since they introduce the same level of confusion as the level of clarity they bring with them.

Thank you for your hard work!

**Comment by bgashler1** [comment]
@chrisdias Just added new icons, so perhaps we could make this on by default in the release.

**Comment by Tyriar** [comment]
Created an issue for folding on a single line https://github.com/Microsoft/vscode/issues/3352, including a comparison with atom, brackets and sublime
