### ISSUE TITLE
Disable breakpoint checkbox while breakpoint requests are pending

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#29497]
This is debugging the "Unit tests" config in vscode, with node legacy. I can disable breakpoints if I uncheck them slowly one by one. But if I uncheck several quickly, then they turn white when unchecked, and I still hit them.

![image](https://user-images.githubusercontent.com/323878/27560655-dc872348-5a79-11e7-8469-0a0c13fe2745.png)

**Comment by roblourens** [comment]
Thanks vscodebot!

**Comment by isidorn** [comment]
June to investigate

**Comment by isidorn** [comment]
This is due to the latency between user clicking on a disable brekapoint -> that traveling to the debug adapter -> adapter checking with node -> reporting back to vscode
While that is happening user can crazily check / uncheck and bring the view in a strange state.

The proper fix would be to disable check / uncheck while vscode is waiting for response from adapter. Tackling that as a feature request -> backlog

**Comment by roblourens** [comment]
Since it's so slow, it would also be nice to have a way to uncheck multiple at a time, like click, shift+click to toggle a range.

**Comment by roblourens** [comment]
I think this is a bug - breakpoints appear disabled, but are not disabled.

**Comment by isidorn** [comment]
Will not fix, even though it is a bug
