### ISSUE TITLE
Clean up multiroot exclude glob handling

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#29505]
From #29164

We need to have a centralized place where exclude globs are resolved in a multiroot-aware fashion. Right now this is done differently in different places because the scenarios have different needs, are running in different processes, etc and I couldn't decide how to organize it in June.

https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/search/node/ripgrepTextSearch.ts#L383

https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/search/node/fileSearch.ts#L91

https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/history/browser/history.ts#L120

**Comment by bpasero** [comment]
@roblourens fyi I introduced [`ResourceGlobMatcher`](https://github.com/Microsoft/vscode/blob/ben/next/src/vs/workbench/common/resources.ts#L60) to be able to share a the filtering of history and file events in the explorer. Would be good to build on top of this guy to share it in more places.

This helper takes care of:
* caching the parsed glob expressions
* updating it on configuration changes and root changes
* providing fast access to the patterns

Unfortunately I think it currently cannot easily be used together for `files.exclude` and `search.exclude` due to the siblings feature (exclude files that have xyz siblings). But maybe you can add this functionality into and then we can also use it for those filtering conditions.

**Comment by roblourens** [comment]
I think this is in a better state than it was last month but I couldn't find another application of ResourceGlobMatcher that makes sense. Search does very little with the globs in the renderer process, and in the search process it mainly passes them to the third-party tools, or they can change on every search anyway.

**Comment by roblourens** [comment]
I spent some time trying to share ResourceGlobMatcher with search, but decided it doesn't make sense, since search is dealing with search queries and search paths, which may or may not be root folders, and if you factor that out, then you just aren't sharing that much. Also, I don't think the pattern caching in ResourceGlobMatcher is that useful because glob.ts already caches all parsed patterns.

So I have a large change in progress that centralizes the "search query interpretation" logic for fileSearch.ts and the stuff in the renderer process, and fixes #31819 in a nice clean way, but it's a WIP. And in parallel I'm still thinking about changing the search query format anyway, so... this goes to September.

**Comment by roblourens** [comment]
Lots has changed here
