### ISSUE TITLE
Native Exception in winpty

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#29540]
- VSCode Version: 1.14 test pas
- OS Version: Windows

Executed a task in the terminal and got:

![capture](https://user-images.githubusercontent.com/1931590/27579051-78fc1baa-5b26-11e7-81ed-b3d89e299318.png)

**Comment by Tyriar** [comment]
@dbaeumer what was the state of the terminal at the time? Hidden, uninitialised, visible?

Related: #27534

**Comment by dbaeumer** [comment]
It was not visible. And I saw it again today when starting VS Code out of dev and it tried to restore a terminal (no task runner). But I have no reliable steps to reproduce.

**Comment by dbaeumer** [comment]
Reopening the issue since it has all information I have.

**Comment by dbaeumer** [comment]
I see that now very frequently. Once or twice a day.

**Comment by Tyriar** [comment]
It's failing here https://github.com/rprichard/winpty/blob/ce9239af5d751195ea6982a41c7d71356ac9201c/src/libwinpty/winpty.cc#L852, meaning either `winpty_t` or `winpty_spawn_config_t` wasn't initialized correctly.

I'm guessing it was related to the config as an exception should have been thrown earlier if winpty_t 
 wasn't initialized correctly https://github.com/Tyriar/node-pty/blob/085f1b180f7cfbb66e6656dd8dc95dbde685351f/src/win/pty.cc#L211

@dbaeumer does your terminal config (shell, args, env, cwd) have any special characteristics? Unicode in one of them for example?

**Comment by dbaeumer** [comment]
I saw it just failing with the following command line under Windows:

```
C:\WINDOWS\sysnative\WindowsPowerShell\v1.0\powershell.exe -NoProfile -ExecutionPolicy Bypass Write-Host 'In
voking Pester...'; Invoke-Pester -PesterOption @{IncludeVSCodeMarker=$true}; Invoke-Command { Write-Host 'Completed Test task
in task runner.' }
```

However I see the same exception when open a single terminal inside VS Code and even in Hyper.js from time to time.

**Comment by dbaeumer** [comment]
Invoking the above command a second time worked. So might be a timing problem.

**Comment by Tyriar** [comment]
@rprichard can you think of any reason [`winpty_spawn_config_new`](https://github.com/rprichard/winpty/blob/ce9239af5d751195ea6982a41c7d71356ac9201c/src/libwinpty/winpty.cc#L801) might fail and return `nullptr`?

It seems to be happening sometimes for @dbaeumer and I verify the winpty_t so it much be the config failing https://github.com/Tyriar/node-pty/blob/085f1b180f7cfbb66e6656dd8dc95dbde685351f/src/win/pty.cc#L211

**Comment by rprichard** [comment]
@Tyriar 

> can you think of any reason winpty_spawn_config_new might fail and return nullptr?

AFAICT, out-of-memory is the only way it would return nullptr.

> I'm guessing it was related to the config as an exception should have been thrown earlier if winpty_t
wasn't initialized correctly https://github.com/Tyriar/node-pty/blob/085f1b180f7cfbb66e6656dd8dc95dbde685351f/src/win/pty.cc#L211

I had noticed earlier that the call sites to `Nan::ThrowError` in pty.cc are inconsistent.  Of the 7 calls, 3 of them return the value returned by `Nan::ThrowError`, 1 of them discards the return value but somewhat assumes that the function returns (i.e. it's followed by `goto cleanup`), and 3 of them assume the function doesn't return (implying setjmp or C++ exceptions).

I'm unfamiliar with the nodejs nan module, but my guess is that `Nan::ThrowError` *does* return. 
 I'm guessing it records the exception object somewhere so that a JavaScript object is thrown once the native function completes.  ThrowError's return type is `void`, FWIW, but that doesn't really answer the question:

```c++
inline void ThrowError(v8::Local<v8::Value> error) {
    v8::Isolate::GetCurrent()->ThrowException(error);
}
```

I commented on this previously; maybe you didn't see it?  It's here: https://github.com/Microsoft/vscode/issues/28593#issuecomment-310603927.  "Aside: the control flow with `Nan::ThrowError` in node-pty is suspicious looking".

**Comment by dbaeumer** [comment]
Got it today with Hyper.js. Here the screen shot. 

<img width="1036" alt="capture" src="https://user-images.githubusercontent.com/1931590/27953002-8f1be73a-630a-11e7-965f-fe01ecd3fe45.png">

**Comment by Tyriar** [comment]
@rprichard yeah I haven't touched that stuff since I forked it https://github.com/chjj/pty.js/blob/master/src/win/pty.cc, can have a look at that in https://github.com/Tyriar/node-pty/issues/102. We've actually been seeing more out of memory crashes on Windows than other platforms recently so maybe that's related to this.

**Comment by Tyriar** [comment]
This is likely related to winpty, tracking in https://github.com/Microsoft/vscode/issues/45693
