### ISSUE TITLE
Typescript build task should prefer bundled tsc/tsserver over global one

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#29579]
We should consider bundling tsc.js with the typescript extension and call that version if the user uses the bundled tsserver instead of the global installed one

This makes the story more consistent with the errors the user sees from the tsserver.

**Comment by mjbvz** [comment]
@kieferrm and I have discussed exposing the full ts compiler through VSCode in the past. It would make for a better quick start experience to be sure, but we also have to consider the complications that shipping bundled build tools brings.

I feel that we should also consider making it easier for users to get a copy of tsc in their workspace. For example, when a tsc build task is first run in a workspace that uses the builtin version of TS,  run `npm install typescript@BUNDLED_VERSION` in the workspace and then use the newly installed tsc for the actual build part of the task. The UX would need some thought. 

@dbaeumer Any thoughts on that kind of approach?

**Comment by dbaeumer** [comment]
I like that approach however I am not sure what happens if there is already and installed typescript that is not used (e.g. Code still uses the bundled tsserver).

**Comment by tugend** [comment]
I think maybe my problem is related. I accidentally had an old, globally version x1 of typescript installed, and and a newer version x2 installed in my project. Say file A.ts would fail for x1 but not for x2.

In my editor task file, I have a build command setup using '"taskName": "tsc",'.

When I build (ctrl+shift+b), visual code will compile using x1 and present a list of errors, but when I open A.ts, the files eventually disapear. I assume because Code continously typecheck using x2 instead.

I'd say code should warn about this, or support the option for selecting the same typescript version in the build script? Everything works too if I remove the global typescript module.
