### ISSUE TITLE
github issues extension: Clicking or double clicking on an issue has no effect

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#29592]
Testing #29507:

Clicking or double clicking on an issue has no effect.
I have to use the context action "Open Issue" instead.

Is this really the intended behaviour?

**Comment by chrmarti** [comment]
What would you want to see on single-click? Double-click currently can't be bound through the view API. /fyi @sandy081

**Comment by weinand** [comment]
A natural choice for me would be "Open Issue".

**Comment by chrmarti** [comment]
Single-click seemed to trigger to easily to use it for opening the issue. I'm hoping for support to bind double-click (or 'open' in general). Filed #29627 to track.

**Comment by weinand** [comment]
VS Code uses single-click in the explorer and that does not seem to be a problem in general.
Before we introduce double-click for a theoretical problem (for which we do not have real numbers), I suggest that we take the risk and see how prevalent this problem is in real usage.

**Comment by chrmarti** [comment]
Ok, let's do that.

**Comment by eamodio** [comment]
While I definitely agree that I expected something to happen when I clicked on an issue/pr item, imo opening the issue on single click would be even less desirable -- because `Open Issue` opens in an external web-browser rather than inside vscode. Although, If it were to open something inside of vscode, I wouldn't argue. Just my 2c ;)

**Comment by sandy081** [comment]
I do not think we do not have double click behaviour in VS Code. If an action is not prominent we always keep in context menu as secondary action. I agree with the point from @eamodio that it makes sense if have this `Open` action on single click if we open it inside VS Code. Since it is opened in a browser outside, context menu action is the right place.
