### ISSUE TITLE
Improve presentation of problem matcher picker

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#29610]
![image](https://user-images.githubusercontent.com/172399/27590144-fde1343c-5b4d-11e7-9d62-16ec3b1b1472.png)

Suggest to show the variable as the description of the quick pick item as shown below and to not use `[]`.

![image](https://user-images.githubusercontent.com/172399/27590438-062f451a-5b4f-11e7-9ad0-6ab5defacfd3.png)

You can also turn it around and show the variable name as the item and the description afterwards.
![image](https://user-images.githubusercontent.com/172399/27590566-689fc49a-5b4f-11e7-9c02-ac82494a302f.png)

**Comment by dbaeumer** [comment]
This is how it looks with the Learn more stuff. I am not too happy since the order is not good and I can not control it. So I will leave the Learn more out for now.

<img width="465" alt="capture" src="https://user-images.githubusercontent.com/1931590/27631076-a3fa5552-5bf7-11e7-8e3a-61bdba9a3951.png">

**Comment by dbaeumer** [comment]
Found a way to make it nice

<img width="493" alt="capture" src="https://user-images.githubusercontent.com/1931590/27633386-3ecd613a-5bff-11e7-9d33-0482984f26a8.png">
