### ISSUE TITLE
Tasks don't work at all with tmux setup

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#29620]
Testing #29618

I have a setup which persists terminal sessions across Code executions, described here: https://medium.com/@joaomoreno/persistent-terminal-sessions-in-vs-code-8fc469ed6b41

With this setup, I can't run any tasks. When running a task, the Terminal pops up and nothing happens.

**Comment by dbaeumer** [comment]
I tried this for the May release and it is very tricky. Besides starting the task output scanning is difficult since you can spilt the task which the terminal as no idea of.  It is basically one terminal instance having multiple windows using ASCII art. 

May be we need to sit together to see what I can do here.

**Comment by dbaeumer** [comment]
However you can force a shell to use using the following top level options
```json
	"options": {
		"shell": {
			"executable": "bash",
			"args": ["-c"]
		}
	},
```

**Comment by alexr00** [comment]
Making tmux work with tasks is out of scope. But with the new setting `"terminal.integrated.automationShell.linux"` you can work around this.
