### ISSUE TITLE
files.exclude and files.watcherExclude have different behaviour for same globs

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#29630]
Testing #29478

In a multi root workspace, for a second folder you have following folder settings

```
	"files.exclude": {
		"**/.git": true,
		"**/.svn": true,
		"**/.hg": true,
		"**/CVS": true,
		"**/.DS_Store": true,
		"**/samples": true
	}
```

Folder samples and its files are excluded, which is good. 
Now have following folder settings for it

```
	"files.watcherExclude": {
		"**/.git/objects/**": true,
		"**/.git/subtree-cache/**": true,
		"**/node_modules/**": true,
		"**/samples": true
	},
	"files.exclude": {
		"**/.git": true,
		"**/.svn": true,
		"**/.hg": true,
		"**/CVS": true,
		"**/.DS_Store": true,
		"**/samples": false
	}
```

Folder samples and its files are shown. But watcher is not excluding files under samples folder.

**Comment by Tyriar** [comment]
@roblourens @bpasero thoughts? It makes sense to me that `"**/samples": true` would only prevent events on that folder, otherwise there's no reason for the `/**`?

**Comment by roblourens** [comment]
I think the `files.exclude` behavior currently makes sense, and `watcherExclude` should match that, unless there's a good reason you'd want to exclude a folder but not its children.

**Comment by bpasero** [comment]
Well this is an issue with how the pattern is applied: In a tree structure (e.g. explorer) the exclude pattern works because we simply start to ignore everything once we reach the samples folder. For the watcher however, everything is watched by default and we need to apply the pattern against absolute paths (anything within samples). 

To be honest, I would not invest too much into the watcher exclude setting, it is debt and should go away eventually.
