### ISSUE TITLE
Add Codecov.io to trusted badge providers

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#29636]
_From @JimiC on June 27, 2017 14:35_

Please consider adding [Codecov.io](https://codecov.io) to trusted badge provider.

_Copied from original issue: Microsoft/vscode-docs#1055_

**Comment by kieferrm** [comment]
codecov.io has been down so far every time we tried to verify what it does. As long as it is not verified we won't add it to the while list.

**Comment by JimiC** [comment]
@kieferrm Not sure what you mean by `has been down`. Haven't noticed any downtimes since we started using it. It's been working fine for [us](https://github.com/vscode-icons/vscode-icons) for some time now.

**Comment by kieferrm** [comment]
@JimiC I have been getting application errors, broken badges, etc. pretty much every time I tried for the last 7 days. For example, your codecov.io badges were always broken:

![screen shot 2017-06-28 at 2 45 32 pm](https://user-images.githubusercontent.com/4674940/27661777-7555b4a8-5c10-11e7-9944-86febc30e577.png)

Today, however, it seems to work, at least their website.

**Comment by JimiC** [comment]
@kieferrm The badge is deliberately not working on our repo because we were forced to break the link due to the restriction `vsce` introduced. In @robertohuertasm attempt to publish using `v1.27.0` we had to sacrifice the `codecov.io` badge. That's actually the reason for this issue.

Proof that it works:
[![codecov](https://codecov.io/gh/vscode-icons/vscode-icons/branch/master/graph/badge.svg)](https://codecov.io/gh/vscode-icons/vscode-icons)

Now, "application errors" I have not yet seen with `codecov.io` but they are common for [issuestats](http://issuestats.com). Could it be you are confusing it with that?

**Comment by JimiC** [comment]
Resolved in https://github.com/Microsoft/vscode-vsce/pull/185
