### ISSUE TITLE
Default values don't work for objects' properties

### ISSUE THREAD

**Issue by KalitaAlexey** [Microsoft/vscode#29665]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|test-extension|test-publisher|0.0.1|;

---

Steps to Reproduce:

1. Create a new extension
2. Set configuration to *package.json* as follows:

```json
"configuration": {
    "type": "object",
    "properties": {
        "testExtension.object": {
            "default": null,
            "type": "object",
            "properties": {
                "field": {
                    "default": "hello",
                    "type": "string"
                }
            }
        }
    }
}
```

3. Make `activate` as follows:

```typescript
const inspectedField = vscode.workspace.getConfiguration('testExtension.object').inspect('field');
const field = vscode.workspace.getConfiguration('testExtension.object').get('field');
const configuration = vscode.workspace.getConfiguration();
const anotherInspectedField = configuration.inspect('testExtension.object.field');
```

`inspectedField`, `field`, `anotherInspectedField` are `undefined`/`null`.

**Comment by KalitaAlexey** [comment]
In gitter I was told that it might not be supported.
I suppose it should be documented somewhere, as example [here](https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributesconfiguration).

**Comment by KalitaAlexey** [comment]
@rebornix,
I don't think it is a feature request.
I believe it is a bug.

**Comment by jrieken** [comment]
@KalitaAlexey The outer `  "type": "object",` shouldn't be there and shows a validation error for me. 

For me the snippets returns values except for the second, `field` and I think it should return something. @sandy081 Can you clarity

**Comment by sandy081** [comment]
Here is what I see for the values in the snippets

![image](https://user-images.githubusercontent.com/10746682/28402113-b9e2bbb6-6d3b-11e7-964f-dc3b4e8237e3.png)

We respect the default value of the configuration property `testExtension.object`. In this case, it is `null`. Hence all values in the snippet are `undefined`. You have to provide a proper default value to populate a default value for the property. Rest of the definition is the schema for the property. It helps in intelli-sense and validating when user is editing this property value in settings.

I would say this works as designed.

@KalitaAlexey Can you please explain how this should work otherwise ?

**Comment by KalitaAlexey** [comment]
Now it makes sense actually.
It's little inconvenient, but it makes sense.
