### ISSUE TITLE
Auto indent in ruby doesn't play nicely with def

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#29672]
- VSCode Version: Code - Insiders 1.14.0-insider (15b579d13dbf6817bb493feff6f36cec87577929, 2017-06-27T05:11:33.154Z)
- OS Version: Linux x64 4.10.0-24-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.9.3
lorem-ipsum|Tyr|1.0.0
sort-lines|Tyr|1.3.0
vscode-svgviewer|css|1.4.2
tslint|eg2|0.15.0
git-project-manager|fel|1.3.2
md-navigate|jri|0.0.1
vscode-scss|mrm|0.6.2
seti-icons|qin|0.1.3
vim|vsc|0.9.0

(1 theme extensions excluded)

---

#29492

Not sure if this is the extension or VS Code

![image](https://user-images.githubusercontent.com/2193314/27609495-ceacaf56-5b3f-11e7-9b5b-2dcb06caf560.png)

Move up:

![image](https://user-images.githubusercontent.com/2193314/27609503-d8ac4af2-5b3f-11e7-8056-f7e82e3a7901.png)

Snippet:

```ruby
def self.sort(array, compare = lambda { |a, b| a <=> b })
  (0..array.length - 1).each do |i|
    (1..array.length - 1).each do |j|
    end
  end
end
```

**Comment by rebornix** [comment]
This is due to the limited architecture (regex based indentation rules), we may want to consider using formatters if they exist for indenation adjustment (if interested, we can discuss in https://github.com/microsoft/vscode/issues/19847).

For this particular issue, if the indentation rules are leading to more trouble than having no auto indent, you can set `editor.autoIndent` to `advanced` to disable the regex based indentation adjustment. As we don't have an easy good-enough fix for it, we close it for now and explore better solutions through issues like https://github.com/microsoft/vscode/issues/19847.
