### ISSUE TITLE
Selecting a deleted line in the Diff Review Panel doesn't go to original editor

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#29688]
re https://github.com/Microsoft/vscode/issues/29496

* Open a changed file from Git Viewlet
* F7 to go to the Diff Review
* Use arrows to move down the selection, move to a deleted
* Press enter, it always selects the last line before the deleted area in the modified editor.

**Comment by alexandrudima** [comment]
I thought about this when building the review panel. 

I think it would be confusing for visually impaired users that they land in the original editor, where there isn't a lot anyone can do except for reading the original code.

Since the original code is all presented in the diff review panel, I thought the only interesting case is if one reviews a diff and wishes to adjust the modified file after reviewing it, so that's why one always lands in the modified editor when Enter is pressed.

**Comment by alexandrudima** [comment]
Closing as I don't plan to change the behaviour
