### ISSUE TITLE
Ligatures are not working correctly for F# syntax

### ISSUE THREAD

**Issue by rexcfnghk** [Microsoft/vscode#2968]
I am using [Fira Code](https://github.com/tonsky/FiraCode) and have enabled `editor.fontLigatures`. Using a `sum` list function as an example,

```fsharp
let inline sum list =
    let rec sumImpl acc = function
        | [] -> acc
        | h :: t -> sumImpl (h + acc) t
    sumImpl LanguagePrimitives.GenericZero list
```

The `[]` and the `::` ligatures are not displayed when **F#** language mode is chosen (The `->` ligature is displayed though). However, they are displayed correctly when **Plain Text** language mode is chosen. Is there something wrong with how the syntax highlighter parses F#'s keyword/literal token?

Maybe it's related to #2872?

**Comment by colinbate** [comment]
Yes it is related. I was able to get the `::` together by playing with the syntax file, but the `[]` I think would be trickier because they are considered delimiters and seem to be parsed as such by a higher level configuration. I'm sure someone more familiar could comment, but it may not be worth the effort.

**Comment by alexandrudima** [comment]
I now get 

![image](https://cloud.githubusercontent.com/assets/5047891/13217004/c21b3e5a-d95f-11e5-826c-7884b4196ec7.png)
