### ISSUE TITLE
editor.wordWrap setting being ignored

### ISSUE THREAD

**Issue by martellaj** [Microsoft/vscode#29689]
- VSCode Version: 1.14.0-insider
- OS Version: Windows 10 Enterprise

Steps to Reproduce:

1. Have a long line of text in a file.

Reproduces without extensions: Yes

**Comment by martellaj** [comment]
I updated this morning and I'm no longer seeing this. Not sure if it was a bug in the build, or something to do with remoting into my machine and the wordwrap getting broken. I'll try to remember to remote back into my machine tonight and see if it reproes.

**Comment by alexandrudima** [comment]
@martellaj If you are using screen reader software on your machine, VS Code detects that and shows a status bar entry "Screen Reader Detected". We cannot communicate wrapping points to Screen Readers, which results in a very bad experience for people that must use such software to operate VS Code. If you hover over the status bar entry, it will show how to disable this. Also see [this](https://code.visualstudio.com/updates/v1_13#_screen-reader-detected).

I have an issue somewhere, the status bar item is too "unnoticeable" and we need to do something more to show what's going on.

**Comment by martellaj** [comment]
Got it, that must've been it. With that in mind, then I have a follow-up question. Is VS Code supposed to detect when a screen reader is no longer in use and adjust? I was using Narrator to do some accessibility testing, which I assume got it into that mode, but it wasn't on for long (and not on when I was having the wrapping problem).

**Comment by alexandrudima** [comment]
We are using some Electron APIs which let us know when Electron/Chromium enters a special "accessibility on" mode.

That code involves detecting specific Windows events being dispatched to the window, and since there is no "starting Screen Reader" / "closing Screen Reader" type of message/protocol on Windows, Electron/Chromium remains in this mode until a restart.

If you're using Screen Readers only to test other software (and not to operate VS Code), then setting `editor.accessibilitySupport: "off"` instead of `"auto"` will prevent us from doing anything special.

**Comment by martellaj** [comment]
@alexandrudima Perfect. Thank you!
