### ISSUE TITLE
Line breakpoints verified to column breakpoints are still treated as line breakpoints on next launch

### ISSUE THREAD

**Issue by hackwaly** [Microsoft/vscode#29696]
- VSCode Version: 1.13.1

I'm implementing a debug adapter for ocaml language. I found that vs code doesn't remember if a line breakpoint has been verified to a column breakpoint on next launch.

I record a gif to represent it.

![6 -28-2017 11-32-57](https://user-images.githubusercontent.com/540298/27619519-98991fc4-5bf5-11e7-9768-39c9d5b8e802.gif)

This is desired:
![image](https://user-images.githubusercontent.com/540298/27619539-bf63949a-5bf5-11e7-9553-eaf787243995.png)

**Comment by isidorn** [comment]
The issue here is that VSCode does not allow adapter to transform regular breakpoints into column. This is currently simply not supported due to this [code](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/debugService.ts#L1043)

The reason for this is that node always returns columns for each breakpoint and in the ui it would be surprising when a user clicks on a line breakpoint to get a column breakpoint.

If we want to support this behavior node and node2 adapters would have to not send columns for breakpoints when they are not expected.
fyi @roblourens @weinand

**Comment by hackwaly** [comment]
I'd like to give a suggestion: We can just treat line breakpoint as a special column breakpoint(column are before the first non-whitespace character in the line). So we can show column breakpoints as line breakpoints (not show the column indicator) if they conform to line breakpoints . In this way, we won't change a lot.
