### ISSUE TITLE
Windows: Switch Window action is not easily discoverable

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#29717]
The 'Switch Window' action has been improved and is a very useful action, but it is not easily discoverable on Windows (on OS X the action is shown in the Windows menu).

**Comment by stevencl** [comment]
One option would be to add a notification when the user creates a new window, telling them that there is a 'Switch window' action available from the command palette. We still need to clean up our notification UX...

My concern with adding another menu (at least on Windows) is that by doing that, we increase the surface area of the product, making other commands less discoverable (since there is more surface area to search through for a command) and potentially making the product feel more heavyweight.

**Comment by bpasero** [comment]
I actually have to take back the example of Visual Studio: Their "Window" menu has nothing to do with OS windows, it seems a "Window" is a file opened in a tab. Switching between windows means switching between layouts of the window it seems.

Very confusing.
