### ISSUE TITLE
Cannot rearrange root folders

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#29715]
Testing #29176

To have a certain root folder order, today, special care must be taken to open root folders in a specific order. It would make sense to be able to sort them in the Explorer and have them presented in a different order than they were opened.

**Comment by bpasero** [comment]
I think it would be cool to be able to use drag and drop to reorder root folders.

**Comment by isidorn** [comment]
@bpasero do we have new API support for this? Since now all folders are treated equal this should be possible

**Comment by bpasero** [comment]
@isidorn there is no explicit API to change the sorting order of root folders, it would probably make sense @sandy081 to add this to `WorkspaceEditingService` so that we can use it in the explorer.

Btw I do think that we need to revisit how the drop feedback for the tree is working in the case of rearranging root folders: Currently we just select the drop target, which implies that you drop a folder or file into that target folder. That imho does not make much sense when rearranging root folders. 

Instead I would expect a new visual drop indicator to show up as e.g. Windows does it:
![flicker_chrome58](https://user-images.githubusercontent.com/900690/28411053-ef835588-6d3f-11e7-89f5-f775798ef0ca.gif)

**Comment by sandy081** [comment]
I will work from an API side to change the order

**Comment by isidorn** [comment]
Yes the line drop indicator would be more fitting.
@sandy081 let me know once we have api for this and I can look into it from the UX side. Thanks

**Comment by isidorn** [comment]
Moving to october, @sandy081 ping me when there is api to change the order :)

**Comment by isidorn** [comment]
Moving to november :)

**Comment by lig** [comment]
Sorting alphabetically by default is sane option event without this being implemented

**Comment by bpasero** [comment]
@isidorn @sandy081 fyi I [pushed](https://github.com/Microsoft/vscode/commit/e9650bd5f2f7694cc782323942e96ea21fcee32a) a change to have [`WorkspaceService.updateFolders()`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/configuration/node/configurationService.ts#L120) that allows to add and remove at the same time with only single write happening to the workspace file (and proper events). I guess that method could be used to support rearranging of roots.

**Comment by isidorn** [comment]
@bpasero thanks, I was aware of that thus I assigned this to the february milestone.

**Comment by isidorn** [comment]
We now support drag and drop of root folders in the explorer.

Note that I have disabled this behavior when multiple roots are selected - because of the API and this being done sequantally it is basically mental masturabation to get this working and I do not see a use case atm.

Try it out in insiders from monday and let me know how it goes.

@bpasero thanks for the API, however not the nicest to program against, I had to write a clunky for loop in order to make this work.
