### ISSUE TITLE
Running `clear` in Terminal leaves scrollbar in bad state

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#29723]
Testing #29483

- Linux 32 bits

1. Run a few commands in order to get a bunch of output and get that scrollbar going
2. `clear`

Notice how the view is cleared, you can't scroll up, but the scrollbar shows otherwise.

![kapture 2017-06-28 at 10 55 29](https://user-images.githubusercontent.com/22350/27628768-5a6a3ed6-5bf0-11e7-97ec-cd170ec8cdf3.gif)

**Comment by Tyriar** [comment]
@joaomoreno hmm, I can't reproduce this, at least on Ubuntu 64-bit. Was it 100% reproducible?

**Comment by joaomoreno** [comment]
Yeah, all the time. 😕

**Comment by ArthurCose** [comment]
Getting this issue on Manjaro KDE 64 bit too.
I got this command from the output of clear: `printf "\e[3J\e[H\e[2J"`
I'm guessing it wasn't reproducible from the clear command outputting different things on the terminal.

**Comment by Tyriar** [comment]
I can reproduce this on Ubuntu now as well.

It looks like running clear via VS Code is producing `\e[3J` and `\e[2J` whereas running via the xterm.js demo is only doing a `\e[2J`, not sure why this is happening. Regardless, it's an issue when both are used as @ArthurCose indicates: `printf "\e[3J\e[H\e[2J"`

**Comment by Tyriar** [comment]
`echo -e '\e[3J\e[H'` also breaks the scroll bar.

**Comment by Tyriar** [comment]
`echo -e '\e[3J\e[H'` is triggering a scroll event/refresh when the new line is added (for enter) but not when the actual rows change. The reason for this is because `echo -e '\e[3J` does the following:

- (enter): line feed (and refresh scroll bar)
- Clear rows above
- Prompt comes in, causing line feeds at the *bottom* of the viewport

`echo -e '\e[3J\e[H` however does:

- (enter): line feed (and refresh scroll bar)
- Clear rows above
- Set cursor to the top of the viewport
- Prompt comes in, causing line feeds at the *top* of the viewport, which do not trigger scroll events

**Comment by Tyriar** [comment]
Upstream issue: https://github.com/sourcelair/xterm.js/issues/760
