### ISSUE TITLE
Move lines doesn't handle context around the selected range.

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#29727]
re #29492

See attached recording and source. With a two line selection things get weird, I cannot describe what it actually does. 

![jun-28-2017 11-11-31](https://user-images.githubusercontent.com/1794099/27629458-b845a8c2-5bf2-11e7-8ad2-a233f1c21fc0.gif)

```html
<html>

<body>
    <div>
        <span>move it</span>
</div>
    <div>
    </div>
</body>

</html>
```

**Comment by rebornix** [comment]
I know try to explain what's happening is not ideal but let me try 

If there is no auto indent of moving lines, you will get 
```
<body>
    </div>
    <div>
        <span>move it</span>

```

But since we add indentation regex rules (which is not context aware or smart), we decrease the indentation of `</div>` as it's a closing tag. And then all moving block aligns to the new indentation.

The final correct fix is the closing tag `</div>` should align to its opening tag. We can enhance this in our bracket matching part but not in indentation rules (at least current TextMate 4 indentation rules). Hope my explaination makes sense.

**Comment by evenicoulddoit** [comment]
Also facing this issue when trying to move lines - it just breaks everything you move it across. Auto-indent per se I love, but this makes moving lines super painful. Perhaps the easiest solution would be a setting to simply not apply auto-indent on move line commands?

**Comment by rebornix** [comment]
This is due to the limited architecture (regex based indentation rules), we may want to consider using formatters if they exist for indenation adjustment (if interested, we can discuss in https://github.com/microsoft/vscode/issues/19847).

For this particular issue, if the indentation rules are leading to more trouble than having no auto indent, you can set `editor.autoIndent` to `advanced` to disable the regex based indentation adjustment. As we don't have an easy good-enough fix for it, we close it for now and explore better solutions through issues like https://github.com/microsoft/vscode/issues/19847.
