### ISSUE TITLE
Prelaunch task does not terminate

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#29734]
testing #29447

Created an extension and upgraded the task.json to version 2.0.
After doing that the debugger waits for ever until the preLaunch task terminates.
When I terminate the task manually, then the target extension is launched properly.

When I change the compile script in package.json to not be watching, then the extension target launches correctly.

```
        "compile": "tsc -p ./",
```

my changes to the tasks.json

![image](https://user-images.githubusercontent.com/172399/27631907-72f8f154-5bfa-11e7-99f0-697590496321.png)

tasks.json
```
{
    "version": "2.0.0",

    // we want to run npm
    "command": "npm",

    // the command is a shell script
    "type": "shell",
    
    // show the output window only if unrecognized errors occur.
    "showOutput": "silent",

    // we run the custom script "compile" as defined in package.json
    "args": ["run", "compile", "--loglevel", "silent"],

    // The tsc compiler is started in watching mode
    "isBackground": true,

    // use the standard tsc in watch mode problem matcher to find compile problems in the output.
    "problemMatcher": "$tsc-watch"
}
```

Actually the preLaunch task does terminate as is shown in the console:

![image](https://user-images.githubusercontent.com/172399/27630996-76366cbe-5bf7-11e7-8474-7370230c4b5c.png)

**Comment by isidorn** [comment]
I can reproduce this issue only on windows, here are the steps

1. Create a new vscode typescript extension, via `yo code`
2. Replace the `tasks.json` with the one Erich posted above

The main issue is that 
`taskService.run(task)` returns a promise which never completes. Here is the [location](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/debugService.ts#L870) where I am calling the taskService.

IMHO the issue is that the taskService never resolves this promise, forwaring to @dbaeumer 
I believe I am using the task service correctly, if that is not the case feel free to assign back to me

**Comment by dbaeumer** [comment]
This is very likely a dup of https://github.com/Microsoft/vscode/issues/29606.

@egamma which version of node / npm are you using.

**Comment by isidorn** [comment]
I could repro with node 8.1.2 and npm 4.3.0 on windows

**Comment by dbaeumer** [comment]
Thanks, makes it more likely that it is a dup. The problem is that npm and node now sent system control characters (not on ANSI Control characters) and that makes the problem matcher fail :-)

**Comment by egamma** [comment]
@dbaeumer I'm using an older version v6.9.4.

**Comment by dbaeumer** [comment]
OK. It is not the node / npm it is a new version of the terminal that now sends the OSC. It is basically to set the Window title. We actually could use that in VS Code to do cool things as well.

**Comment by dbaeumer** [comment]
Dups #29606
