### ISSUE TITLE
Intellisense suggestions should display an horizontal scrollbar if needed

### ISSUE THREAD

**Issue by fbricon** [microsoft/vscode#29757]
- VSCode Version: 1.13.0
- OS Version: macOS Sierra 10.12.5

Steps to Reproduce:

1. install java extension
2. open java file
3. type `import o`, wait for suggestions to show up
suggestions are truncated because the package names don't fit in the suggestion window, there's no way to scroll horizontally

See https://github.com/redhat-developer/vscode-java/issues/249
[![https://gyazo.com/9f0b536a9f71d72a4939ffbb4834340d](https://i.gyazo.com/9f0b536a9f71d72a4939ffbb4834340d.png)](https://gyazo.com/9f0b536a9f71d72a4939ffbb4834340d)

Reproduces without extensions: Maybe

**Comment by stevencl** [comment]
I am not sure how well a horizontal scroll bar would work. How difficult would it be to increase the width to accomodate these longer strings, if the string is longer than would fit in the default width?

The problem with the scroll bar is that once you scroll to the right, you need to scroll back to the left if you arrow down and the next item is much shorter in length. A solution to that would be to auto scroll back to the left after making another selection but then that could run into problems if the list looks like the screenshot above.

**Comment by fbricon** [comment]
> The problem with the scroll bar is that once you scroll to the right, you need to scroll back to the left if you arrow down and the next item is much shorter in length
This is the behaviour I see in Eclipse. With a trackpad, it's absolutely manageable.
I think this would give users less surprises than trying to autoscroll back when changing the selection.
A better solution would probably be to scroll left only if the selection text size is lower than the x-position of the currently visible pane, but that's probably too complicated

**Comment by hdorgeval** [comment]
One of my colleague shows me that, in the css that drives the suggestion list, there is a width:50% that is set. when forced to 100%, the width of the suggestion list is then ok (no cropping). It could be great if the suggestion-list max width could be parameterized directly in the workspace settings

**Comment by hdorgeval** [comment]
Here is a screenshot of this css rule: 
![screen shot 2017-11-16 at 22 39 27](https://user-images.githubusercontent.com/9698924/32917344-29528652-cb1f-11e7-8738-1bc1bef169fa.png)

When I set the value to 70%:
![screen shot 2017-11-16 at 22 41 37](https://user-images.githubusercontent.com/9698924/32917457-89931b44-cb1f-11e7-9af5-9f132e485d85.png)

**Comment by hdorgeval** [comment]
I have also discovered that if you reduce the width of the VS Code editor window, then suddenly there is no more cropping as shown by the following sceenshot:
![screen shot 2017-11-16 at 22 51 12](https://user-images.githubusercontent.com/9698924/32917912-e7c07120-cb20-11e7-84f0-0047ac8726b8.png)

**Comment by hopbalabi** [comment]
This is definitely a usability issue and please take care of it. I am pretty sure you can solve it in a good way. But as @fbricon said in eclipse and others there is horizontal scroll bar appears if horizontal scroll bar needed. Also you can resize the suggestion bubble with catching it and dragging from bottom right corner.

**Comment by darkgem666** [comment]
Hi @hopbalabi , for some reason the hack didn't work for me.

- VsCode versio: Version 1.19.3 (1.19.3)
- MacOsX version: 10.13.2

**Comment by hopbalabi** [comment]
@darkgem666 please make sure you are editing `workbench.main.css` after you change this css you must restart the vscode.

**Comment by darkgem666** [comment]
I did.

![screen shot 2018-02-02 at 11 53 31 am](https://user-images.githubusercontent.com/1806541/35744957-bc7e4394-080f-11e8-955c-1adebf246dda.png)

**Comment by Aggror** [comment]
Hi @hopbalabi. Thanks for the tip. Wish we could customize this using the settings or something.

**Comment by StephenOTT** [comment]
REALLY NEEDED! +1

**Comment by s-shamesmuhametov-parc** [comment]
This hack works for me, but the VS Code version: 1.23.1 seems to have broken something. I want to configure without the hack

**Comment by rben01** [comment]
I think a superior fix would be to display attributes hierarchically to avoid rewriting common prefixes. So the window would contain:

```
x org
x     .apache.catalina
          .authenticator
              .(can't see it in the screenshot)
x     .springframework
x         .aop
              .aspectj.stuff
              .framework
                  .thing1
                  .thing2
          .boot.autoconfig
              .thing1
```

Rows not matching the typed string (such as `org` itself, `.springframework` itself, etc) would be dimmed and not selectable, as marked by a leading `x` above.

This takes more vertical space, but takes a lot less horizontal space and is a lot easier to quickly skim.

**Comment by LucianoMRrodriguez** [comment]
+1

**Comment by ramya-rao-a** [comment]
There are 2 sides to this issue
- The data being provided by the extensions is too long
- The widget is not big enough to show long data

I'd like to address the first issue while we figure out the solution to the second.

Note: I am re-using the pictures from the previous comments

In the first scenario for java, when the user has already typed `import.org.`, the completion provider from the java extension should return only the rest of the import in the completions. This is doable because `.` is a trigger character, meaning when user types `.`, VS Code calls the completion provider in the extension. The extension at this point knows what is already typed and show only the remaining parts.

I have updated https://github.com/redhat-developer/vscode-java/issues/249 accordingly.

[![https://gyazo.com/9f0b536a9f71d72a4939ffbb4834340d](https://i.gyazo.com/9f0b536a9f71d72a4939ffbb4834340d.png)](https://gyazo.com/9f0b536a9f71d72a4939ffbb4834340d)

In the second scenario by @hopbalabi, the function signature is being shown inside parenthesis, which makes most of the items have long labels. This is not the suggested way to show the signature in the auto-completion widget. In other languages/extensions, the function signature is shown as part of the docs and not the initial label itself.

<img width="1006" alt="screen shot 2017-12-25 at 00 09 07" src="https://user-images.githubusercontent.com/7443948/34329625-087260fe-e908-11e7-8d85-346847f0055b.png">

@hopbalabi Was your example Java as well?

**Comment by AlekSi** [comment]
@ramya-rao-a Here is another data point (for Go):
![2018-11-13_18-39-30](https://user-images.githubusercontent.com/11512/48424591-03c0f500-e774-11e8-8ba4-f3940c5559ec.png)

**Comment by ramya-rao-a** [comment]
@AlekSi Can you open a issue in the vscode-go repo for this? With sample code and your Go related settings? Such long labels seem very unlikely in Go

**Comment by thdoan** [comment]
For user snippets, a change that would help tremendously is to change word-wrap from `break-word` to `normal` to prevent these kinds of issues:

![image](https://user-images.githubusercontent.com/4110567/48671009-afe93f80-ead6-11e8-98ae-96cf6814e197.png)

**Comment by marcoms** [comment]
Two solutions make sense to me:

- Truncate the beginning of the suggestion enough to show the end: `... console.log()`
- Show the beginning and ends of the suggestion: `window. ... .log()`

Makes sense to have it configurable too

**Comment by JoeyRxy** [comment]
@emeentag hi,your solution is great,but I want to ask how to get rid of the word `[Unsupported]` at the title.As sort of OCD,sufferring from that.

thx!

**Comment by marcoms** [comment]
@JoeyRxy You can use the [Fix VSCode Checksums](https://marketplace.visualstudio.com/items?itemName=lehni.vscode-fix-checksums) plugin

**Comment by emeentag** [comment]
Hi all,

Sorry i could not follow the thread for along time. But as i see here i think we are still at the beginning. 
@ramya-rao-a it is nice you are trying to identify and solve the issue but what i try to say in here, this is a clear UX failure. And members who want to raise a ticket similar to that problem should not be redirected to the related repos because this is not a problem for extensions. This is a general issue. All extensions using the same interface of VSCODE to display their code suggestions right? So it seems to me hard to accept to make the same error for all the extensions. In here issue is not related with go python or java... Issue is to display some long text not properly inside these suggestion boxes. Once everyone applies this CSS hack then it fixes the issue for every language so then we should accept this is a common issue and should not be handled in different repo(s). This code suggestions is in general format for Java and provided by the language server(as i know) so other IDE or editors covering this issue by adding a scrollbar or making possible to expand suggestion box. And please do not suggest to change displaying those suggestions because they are look like the same since years and years. Hope now we could be on the same page. Better to accept this is a common problem and better to handle in a good UX. 

Thx.

**Comment by kdvolder** [comment]
We will take the suggestion of having our extension try to shorten the labels of completions as a good constructive suggestion. In our case this 'workaround' only works sometimes however. If you look at the linked issue https://github.com/spring-projects/sts4/issues/361. We see an example where it indeed would work. And perhaps that is the most common scenario. 

We should realize however that is possible in our extension to suggest those same lengthy completions without the user first needing to type the whole prefix in the editor. If you only type a snippet of the property name taken from near its end, the whole length of that property, including all the '.' in between segments will be suggested and will need to be displayed in its entirety.

So, yes, it is a good idea to shorten the labels when it makes sense, and this actually makes the popup generally more pleasant to look at for a user too. So we will do that. But it doesn't mean vscode should *also* provide a proper way to display longer completion labels, the need for them can not be completely eliminated. Sometimes it will just be the case that the labels are large, and there is no way to avoid it.

**Comment by escamoteur** [comment]
The shortening of the texts is a good proposal but I wonder why you can't make the dropdown box the double with anyway to make sure that even longer path parts are displayed fully. What speaks against this if is a simple change in the css?

**Comment by akaroml** [comment]
Here to share a related issue microsoft/vscode-java-pack#255. Java classes often have longer full names. And the current completion list is showing ellipsis which omits the most important message, e.g. the class name.
![image](https://user-images.githubusercontent.com/16755094/69028842-339d7b00-0a0e-11ea-9f8b-386052df8528.png)

Showing the horizontal scroll bar is definitely a nice workaround. But it would be nicer to ask the language server. Here are two options:
1. Vscode asks the language server to provide a short name by specifying the max length.
    a. Full name: org.hibernate.validator.internal.constraintvalidators.bv
    b. Parameter: maxLength: 50
    c: Result: org.hibernate.validator.internal.constraint...bv
2. Vscode asks the language server to mark the most significant part in the name (with a range), and then generates better short names.
    a. Full name: org.hibernate.validator.internal.constraintvalidators.bv
    b. Significant part: (54, 56) -> bv
    c. Result: org.hibernate.validator.internal.constraint...bv

**Comment by jrieken** [comment]
@akaroml Did you experiment with only using the last part as label, e.g. `FooValidatorFactory`, and to use the fully qualified name in the detail or description only? I am asking because I think that even adding a scrollbar or label-shorting won't help much with being able to quickly grasp what's showing on the screen. In addition to the short-labels you can still suggest package names, like so

```
label: FooValidator, detail: org.hip.hop. FooValidator
label: FooValidatorFactory, detail: org.hip.hop. FooValidatorFactory
label: org, detail: package
```

That would allow to type package names and type names and would make the IntelliSense widget less busy.

**Comment by muhd-ali** [comment]
> @hdorgeval mentioned a quick hack, i will try to explain this quick hack until a solution is shipped in later releases. I also want to say that, suggestions became way better for me after this hack, especially while programming in java.
> 
> Steps:
> 
> * Open VsCode's package contents folder. It is the folder where you installed VsCode on your machine. Could be different for each operating systems.
> * In mac i went through this path for the css file:
>   `Your Package Contents/Resources/app/out/vs/workbench/workbench.main.css`
> * Search for this line:
>   `.monaco-editor .suggest-widget.docs-side>.tree`
> * Edit `width` css property from 50% to 100%
> * Save and restart vscode. You will get a warning like `Your Code installation appears to be corrupt. Please reinstall.` Just ignore it because with doing this way, we broke the md5 checksum of the installation. For me a proper suggestion much more important than this warning.
> 
> **Before:**
> <img alt="screen shot 2017-12-25 at 00 09 07" width="1006" src="https://user-images.githubusercontent.com/7443948/34329625-087260fe-e908-11e7-8d85-346847f0055b.png">
> 
> **After:**
> <img alt="screen shot 2017-12-25 at 00 01 25" width="1002" src="https://user-images.githubusercontent.com/7443948/34329588-e44801f8-e906-11e7-9da4-3e3305cc60a8.png">

The directory structure on v1.40.2 seems to have changed. The css files in the stated directory are named differently. Also setting it to 100% *did not work for me*. Not sure why.

**Comment by akaroml** [comment]
> @akaroml Did you experiment with only using the last part as label, e.g. `FooValidatorFactory`, and to use the fully qualified name in the detail or description only? I am asking because I think that even adding a scrollbar or label-shorting won't help much with being able to quickly grasp what's showing on the screen. In addition to the short-labels you can still suggest package names, like so
> 
> ```
> label: FooValidator, detail: org.hip.hop. FooValidator
> label: FooValidatorFactory, detail: org.hip.hop. FooValidatorFactory
> label: org, detail: package
> ```
> 
> That would allow to type package names and type names and would make the IntelliSense widget less busy.

Just tried to put the short name in the front and it looks good enough for me. What do you think? @fbricon 
![image](https://user-images.githubusercontent.com/16755094/70110533-4066d380-168a-11ea-8471-668fafa160d8.png)

**Comment by akaroml** [comment]
Further playing with my modification, there is actually a new problem. As I keep on typing "spring" to limit the search scope, the highlighting works in a weird way. I was expecting the term "org.spring" to be highlighted, but only "spring" is. I guess it has something to do with the string match algorithm in vscode.

![image](https://user-images.githubusercontent.com/16755094/70116188-eae7f200-169c-11ea-86a8-76e8c8796c76.png)

**Comment by hxuanhung** [comment]
In case anyone wants to use the hack above, on Mac and vscode (1.41.0-insider) file name is changed to `workbench.desktop.main.css`

> Steps:
Open VsCode's package contents folder. It is the folder where you installed VsCode on your machine. Could be different for each operating systems.
In mac i went through this path for the css file:
Your Package Contents/Resources/app/out/vs/workbench/workbench.main.css
Search for this line:
.monaco-editor .suggest-widget.docs-side>.tree
Edit width css property from 50% to 100%
Save and restart vscode. You will get a warning like Your Code installation appears to be corrupt. Please reinstall. Just ignore it because with doing this way, we broke the md5 checksum of the installation. For me a proper suggestion much more important than this warning.
```

**Comment by Hopfenspirger** [comment]
What is the situation right now? Also for JS Development this box is pretty small? Resizing the Box with the mouse and remembering the width and hight for the next time would be great...

![2020-03-11_1812](https://user-images.githubusercontent.com/12065234/76445434-b1263600-63c5-11ea-8bb4-73695012b213.png)

Or a setting somewhere here: (Workspace and User)

![grafik](https://user-images.githubusercontent.com/12065234/76445954-91dbd880-63c6-11ea-8963-1215a3397438.png)

**Comment by ValentinH** [comment]
A pretty similar issue is with the "auto-import" labels which are way too short:
![image](https://user-images.githubusercontent.com/2678610/79727673-0a4e8700-82ed-11ea-86fd-8b8ec9f5b9ae.png)

When you are importing a type with a common name, it's really hard to know which one to import.

**Comment by ValentinH** [comment]
I actually noticed that if you hover the row, there is an "i" icon.
![image](https://user-images.githubusercontent.com/2678610/79730849-beeaa780-82f1-11ea-8a24-8ccbbcee90c1.png)

If you click on it, the description will be shown in a new popup attached to the first one: 
![image](https://user-images.githubusercontent.com/2678610/79730922-d9bd1c00-82f1-11ea-84fa-7e565cfac655.png)

The best part is that once you clicked it, it will stay in this mode for the next time.

**Comment by jayjun** [comment]
To everyone resorting to the CSS hack, upvote https://github.com/microsoft/vscode/issues/30140 to expose it as a proper option.

**Comment by chetrf** [comment]
To anyone having trouble getting the CSS hack to work, one more detail that finally made it work for me:  I had to change the Editore: Suggest Font Size from zero to something smaller than my default font.  I had almost given up on getting the CSS hack to work.  After I did that the change from 50% to 100% worked.  This is on MacOs Catalina.

<img width="543" alt="suggestFontSize" src="https://user-images.githubusercontent.com/64375918/84600250-3e4db080-ae35-11ea-94cb-1a5c560b1ae2.png">

**Comment by Jonathan0wh** [comment]
waiting for feature request https://github.com/microsoft/vscode/issues/29126

**Comment by JCKodel** [comment]
1) Create the following css in your user folder (figure out paths if you are not on Windows):
```css
.monaco-editor .suggest-widget.docs-side{
  left: 32px !important;
  right: 32px !important;
  width: calc(100vw - 64px) !important;
}

  .monaco-editor .suggest-widget.docs-side .tree {
    width: 34% !important;
  }

  .monaco-editor .suggest-widget.docs-side .details {
    width: 66% !important;
  }
```

2) Install `be5invis.vscode-custom-css` extension

3) Insert this on your settings.json:
```json
  "vscode_custom_css.imports": [
    "file://C:/Users/jckod/vscode.css"
  ],
  "vscode_custom_css.policy": true
```

4) Press F1 to get the command palette and run `Reload custom CSS and JS`

5) Restart VSCode when requested in the notification

6) Ignore the "VSCode install is corrupt"

![image](https://user-images.githubusercontent.com/379339/87849732-357f4d00-c8c1-11ea-828f-83de048ee554.png)

Nice full screen intellisense, with no jumping.

See? Is not that hard, Microsoft. I don't care if it is not right on the cursor position. I just care about being able to read the f☠ documentation ¬¬

**Comment by jrieken** [comment]
The suggestions and the details part are going to be resizable (see https://github.com/microsoft/vscode/issues/29126#issuecomment-716415112). I am closing this as a related/duplicated issue.
