### ISSUE TITLE
Task is running in terminal with "runner": "process"

### ISSUE THREAD

**Issue by whitecolor** [Microsoft/vscode#29785]
1.14.0-insider
b508e11e5a8b90c8fa19e6e3a7d8ccd57ab6e9b7

In the latest insiders I don't see spinner when tsc watch task is executed in status bar (it was before update). 
Then I read the docs about tasks updates
I tried to add `"runner": "process",` to task:

```
{
  // See https://go.microsoft.com/fwlink/?LinkId=733558
  // for the documentation about the tasks.json format
    "tasks": [
    {
      "taskName": "tsc",
      "version": "0.1.0",
      "runner": "process",
      "command": "node",
      "isShellCommand": true,
      "args": [       
        "./node_modules/typescript/lib/tsc.js", 
        "-w",
        "-p",
        "."
      ],
      "showOutput": "silent",
      "isBackground": true,
      "problemMatcher": "$tsc-watch"
    }    
  ]
}
```

**but it still runs in terminal.** How to make it run as a process?

**Comment by egamma** [comment]
Adding to June to discuss whether this is a regression.

**Comment by dbaeumer** [comment]
@whitecolor here is what is happening:

The tasks.json file has no top version attribute which actually mandatory. You get an error message (I agree not super visible @aeschli - we should consider improving this. May be flagging the whole literal as an error).

![capture](https://user-images.githubusercontent.com/1931590/27680501-36525412-5cbc-11e7-8046-c52cfb5df38c.png)

With 1.14 the default tasks.json version will be 2.0.0 not 0.1.0 anymore. This one always uses the terminal as the runner since it provides features that can't be used in the output panel.

I addition I want to point out that neither runner nor version is a valid attribute inside a task. The json flags them as errors.

![capture](https://user-images.githubusercontent.com/1931590/27680620-a6580c0c-5cbc-11e7-8e4c-59b03d0a59e1.png)

To get the old 0.1.0 behavior simple add `"version": "0.1.0"` as a top level property

**Comment by dbaeumer** [comment]
However I discovered a small regression in the sense that we only show the spinner if it is a build task even when running in the output panel. I fixed. that. 

To verify:

- create the following tasks.json (Windows specific, easy to adopt to Linux / Mac)
```ts
{
	// See https://go.microsoft.com/fwlink/?LinkId=733558
	// for the documentation about the tasks.json format
	"version": "0.1.0",
	"tasks": [
		{
			"taskName": "dir",
			"command": "dir",
			"isShellCommand": true
		}
	]
}
```
- Run Task > dir

Ensure that the spinner is showing up.

**Comment by whitecolor** [comment]
I don't see the spinner now? And where is the task output?

**Comment by dbaeumer** [comment]
The next insider build will come tomorrow. With task 0.1.0 the output still comes in the Output pane. With 2.0.0 it will come in the terminal.
