### ISSUE TITLE
Syntax highlighting of JavaScript code in Template Literals

### ISSUE THREAD

**Issue by Tiedye** [Microsoft/vscode#29866]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|ng-template|Angular|0.1.4|
|tslint|eg2|0.16.0|;

---

If js code is written in a template literal, the text that would normally be white (the default color) is orange (the color of the rest of the string).

Steps to Reproduce:

1. Create a template literal, add any code to a placeholder, eg
```javascript
`A string, ${[1, 2, 3].join(',')}`
```
2. The `[`,`]`,`.`,`,`,`(`, and `)` will be colored orange when they should not be.

**Comment by usernamehw** [comment]
So, this basically fixes this in Default themes (effect), but still remains for many other themes?

Is there a way to negate a selector from user settings `editor.tokenColorCustomizations`? Or selector to tell it to "inherit" coloring?

**Comment by mjbvz** [comment]
Yes, we opted to only change the themes instead of introducing special logic for this case so that we remain compatible with textmate grammars.

Please submit an issue against any theme where you notice unexpected colorization.

As a workaround, you can set the `meta.embedded` to the standard background color for your theme:

```
"editor.tokenColorCustomizations": {
		"textMateRules": [
			{
				"scope": "meta.embedded",
				"settings": {
					"foreground": "#f0f"
				}
			}
		]
	}
```

There is no `inherit` color setting
