### ISSUE TITLE
We need some way of differentiating roots with the same basename

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#29871]
From @doublehelix in https://github.com/Microsoft/vscode/issues/396#issuecomment-311867661

> When I add two "root" folders with the samename from two separate projects, there is nothing to distinguish these folders apart.
> 
> e.g. I add `/dev/www/myproject/src` and then add `/dev/libraries/mycomponent/src`
> All I see is two root folders called `src`.
> ```
> > src
> > src
> ```
> I believe we need a way to change the *display name* of the root folders.
> Which would then display:
> ```
> > My Project (/src)
> > Component 1 (/src)
> ```

Perhaps we could leverage the code that does differentiates files for tabs (eg. /a/b/c, /d/b/c becomes /a/.../c, /d/.../c).

**Comment by cecilemuller** [comment]
To expand on my comment from the other thread: VSCode can already differentiate files with the same name by showing part of the folder name, so it would make sense to use this for folders as well.

To illustrate:
![Files with the same name, in VSCode](https://user-images.githubusercontent.com/681420/27694819-85c44c18-5ced-11e7-9eba-70a108de046f.png)

![Files with the same name, in VSCode](https://user-images.githubusercontent.com/681420/27694827-8c5c629a-5ced-11e7-90a9-b697a8df11e3.png)


To compare, Sublime Text only differentiates files with the same name because multiple folders are defined by the Project settings (so you can also set a display name if needed).

With VSCode on the other hand, it sounds like you can be in a state where you have multiple folders and no workspace settings.json yet, so something automatic would be a good fit, hence using the same method as with files.

**Comment by trevorsg** [comment]
I would love the ability to customize the name of the root within the code-workspace file rather than relying on an automatic disambiguator.

Historically our team has used Visual Studio, but a number of web developers have switched to VSCode. Our engineering toolchain includes an "open" command: just run "open" from any MSBuild project directory and we will autogenerate a VS Solution file that includes that project and all of its recursive dependencies. I created a similar script "copen" that does the same dependency walking, but generates a code-workspace file instead. The only problem is there are a lot of roots with the same name. Our generated Solution files actually show two levels of roots. We group projects into a construct called "modules", so the hierarchy looks something like this:

    ModuleA
       Project1
          foo.ts
          bar.ts
       Project2
          baz.ts
    ModuleB
       Project3
          x.ts
          y.ts
       Project4
          z.ts

So, as a super nice-to-have, it would be great to be able to map a root to a hierarchy.

    {
        "folders": [
            {
                "name": "ModuleA",
                "children": [
                    {
                        "name": "Project1",
                        "uri": "file:///c:/path/to/project1"
                    },
                    {
                        "name": "Project2",
                        "uri": "file:///c:/path/to/project2"
                    }
                ]
            },
            {
                "name": "ModuleB",
                "children": [
                    {
                        "name": "Project3",
                        "uri": "file:///c:/path/to/project3"
                    },
                    {
                        "name": "Project4",
                        "uri": "file:///c:/path/to/project4"
                    }
                ]
            }
        ]
    }

**Comment by bpasero** [comment]
@sandy081 since you are about to introduce `WorkspaceFolder `to workbench API, can we have a `name` property too that comes from the workspace file? I guess we would need a change event too.

**Comment by bpasero** [comment]
You can now assign a name to a workspace folder:

```json
{
	"path": "/Users/bpasero/Desktop/notifications",
	"name": "Folder Name"
}
```

The name is shown in some selected places where it makes sense (e.g. the explorer and window title).

**Comment by bpasero** [comment]
**Verification:** add a name to a workspace folder and verify this name shows up in the explorer.

**Comment by weinand** [comment]
Assigning new names to the workspace folders works fine, but editing the workspace file from  within VS Code is a bit cumbersome. See issue #35131.

**Comment by paulolamas** [comment]
When I search for a file using Ctrl+P, I see the actual folder name as the directory label instead of the "name" property I assigned to a given folder. I do see "name" displayed properly in my workspace view.

![image](https://user-images.githubusercontent.com/11496257/30887500-6028d05c-a2e1-11e7-94d7-bafc0bd4edf9.png)

I gave these names to the folders:
c:\component1\3.0\ -> "name": "component1"
c:\component2\3.0\ -> "name": "component2"
c:\component3\4.0\ -> "name": "component3"
