### ISSUE TITLE
Can't use env namespace

### ISSUE THREAD

**Issue by daschult** [Microsoft/vscode#2989]
I tried to use the "env" namespace today, but I couldn't because it's only supported in vscode engine 10.8 and above. I updated my package.json file to reference the vscode npm package version 0.11.1, and then I updated my engine reference to be 0.10.8, but I'm still getting errors saying that the vscode module can't be found.
Here's a stripped down version of my package.json file:
{
  "engines": {
    "vscode": "^0.10.8"
  },
  "devDependencies": {
    "mocha": "^2.4.5",
    "typescript": "^1.7.5",
    "vscode": "^0.11.0"
  }
}

And here's a screenshot of the error I'm getting in VSCode:
![screenshot](https://cloud.githubusercontent.com/assets/7052303/13023242/f85e6cb0-d19b-11e5-97f2-3938e810ce7b.png)

Any thoughts?

**Comment by mattacosta** [comment]
That's typically caused by typescript not being able to find the vscode.d.ts file (which is no longer included in the vscode package).

So if it's not somewhere in your `./node_modules/vscode` folder, then you need to add the "postinstall" script from the [Update notes](https://code.visualstudio.com/Updates#_extension-authoring) and run `npm run postinstall` from a command prompt to download it.

**Comment by egamma** [comment]
@daschult it looks like you are missing an `npm install`. After the npm you will have to restart code or run the `reload window` command.
