### ISSUE TITLE
Status bar items are repositioned on their properties change

### ISSUE THREAD

**Issue by michelkaporin** [Microsoft/vscode#29937]
This is annoying when you have two or more extensions that update their status bar items. E.g. status monitoring extensions as #28586 .

### Steps to reproduce
Have the following code in your extension
```
export function activate(context: vscode.ExtensionContext) {
    const item = vscode.window.createStatusBarItem(vscode.StatusBarAlignment.Left);
    item.show();
    setInterval(() => {    
        item.text = 'Extension 1';
    }, 3000);

    const item2 = vscode.window.createStatusBarItem(vscode.StatusBarAlignment.Left);
    item2.show();
    setInterval(() => {    
        item2.text = 'Extension 2';
    }, 2000);
}
```

### Result
![statusbarelems-switching](https://user-images.githubusercontent.com/2239563/27734867-22468d58-5d9d-11e7-8d9f-17582f4c722f.gif)

### Expectation
Positioning of status bar items is kept the same at least during the same VS Code session.

**Comment by bpasero** [comment]
@jrieken I think the status bar is doing the right thing when I see what [`MainThreadStatusBar.$setEntry`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/electron-browser/mainThreadStatusBar.ts#L22) does: every time the entry is set, the previous one is disposed. Since this example does not provide a priority (priority = 0), we just [append](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/parts/statusbar/statusbarPart.ts#L83) the entry to the end of the list. 

The extension could workaround this by just setting a priority.

**Comment by jrieken** [comment]
> Can we not just update the existing status bar entry instead of always throwing away the current one?

I guess so, but I didn't write that code nor own the status bar service on which we always call `addEntry` which we dispose on update. I don't believe I can fix this because the service doesn't allow to update entries.

**Comment by bpasero** [comment]
Yeah good point, this might actually be my extension API contribution from 2 years ago...

@michelkaporin for now I suggest to assign a priority to your extension for the status bar entry.

**Comment by michelkaporin** [comment]
I see, @bpasero, thanks!
