### ISSUE TITLE
Smoke test failures

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#29940]
![image](https://user-images.githubusercontent.com/172399/27736814-137df6ea-5da6-11e7-8064-306df94fbcd7.png)

[Smoke Test Suite Data Loss verifies that contents of the dirty files are restored after 'hot exit'.zip](https://github.com/Microsoft/vscode/files/1115232/Smoke.Test.Suite.Data.Loss.verifies.that.contents.of.the.dirty.files.are.restored.after.hot.exit.zip)

[Smoke Test Suite Integrated Terminal opens terminal, runs 'echo' and verifies the output.zip](https://github.com/Microsoft/vscode/files/1115225/Smoke.Test.Suite.Integrated.Terminal.opens.terminal.runs.echo.and.verifies.the.output.zip)

**Comment by michelkaporin** [comment]
The reason for failures is the same as in #27841.

In first failure webdriver failed to type exclamation mark, whereas in the second "Ctrl+`" keybinding failed to be triggered due to layout issues again.

As a solution to this I propose not to type exclamation mark character in the first test and fallback to Command Palette command in the second case.
