### ISSUE TITLE
Emmet: Skip the default expansion to CSS property when abbreviation is not found

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#29943]
Found during Smoke Test

Notice how the first option is hardly the best one in this case:

![image](https://user-images.githubusercontent.com/22350/27737594-f46e7b96-5da8-11e7-9202-62e36f49c9c4.png)

**Comment by ramya-rao-a** [comment]
This one is due to the below from the [emmet cheet sheet](https://docs.emmet.io/cheat-sheet/)

> If abbreviation wasn’t found, it is transformed into property name: foo-bar → foo-bar: |;

I don't like it either. We can prune this type of expansion out from our side.

**Comment by ramya-rao-a** [comment]
Am out on vacation all next week. This is an easy fix. If anyone wants to give it a try, the place to add the fix is 

https://github.com/ramya-rao-a/vscode-emmet-helper/blob/543c06c55e2cd8ff26575811b0c0c0bba6d823e1/src/emmetHelper.ts#L56

Once you have the vscode dev env set up, you can start by making changes directly to the javascript file `emmetHelper.js` in `extensions/emmet/node_modules/vscode-emmet-helper`.

Once you are happy with your changes, send a PR to https://github.com/ramya-rao-a/vscode-emmet-helper
