### ISSUE TITLE
Additions to "emmet.includeLanguages" require reload

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#29968]
- VSCode Version: Code - Insiders 1.14.0-insider (7e2937237620501705e4a5276e76726d35a31905, 2017-06-30T05:07:32.086Z)
- OS Version: Darwin x64 15.6.0
- Extensions: none
---

Steps to Reproduce:

1. Launch with no `emmet.includeLanguages`
2. Add, e.g., `"emmet.includeLanguages": { "javascript": "javascriptreact" }`
3. Observe: No Emmet proposals are shown in .js files
4. Reload and observe: Emmet proposals are shown in .js files

**Comment by ramya-rao-a** [comment]
The fix is to listen to the config change event and register new completion providers for the newly added languages in `includedLanguages`

**Comment by jens1o** [comment]
I take a look, I saw this in other extension and it isn't that hard.

**Comment by ramya-rao-a** [comment]
Yes, not hard at all. Feel free to submit a PR

**Comment by roblourens** [comment]
I can't get it to work, reload or not.

**Comment by jens1o** [comment]
It works for me, for example when I add XML files manually to emmet.

**Comment by rebornix** [comment]
I still didn't see Emmet proposals after adding this setting. Should those proposals show up in the suggestion window? @ramya-rao-a

**Comment by ramya-rao-a** [comment]
The reason why @roblourens  and @rebornix were not able to get any suggestions was because they hadn't set `emmet.showExpandedAbbreviation` to `always`

I had initially introduced `always` as an option to `emmet.showExpandedAbbreviation` setting because, back then there emmet suggestions (no css) were too eager and showing up for every letter that was typed (because every word/letter was a valid abbreviation. eg `abc` -> `<abc></abc>`

But in the last month there have been many improvements and now non css emmet suggestion sonly show up if the word is one of the commonly used html tags or is a valid abbreviation with operators like `>`, `$`, `*` etc. or is a custom emmet snippet.

This "always" vs "markupAndStylesheetOnly" option may not be required any more

**Comment by ramya-rao-a** [comment]
On spending more time thinking on https://github.com/Microsoft/vscode/issues/29968#issuecomment-320348462, I feel its not wise to remove the "markupAndStylesheetOnly" option altogether.

There can still be cases where emmet suggestions showing up in wrong places annoying users.

Instead, as a middle ground, we can change the default for this setting to `always`

This way, the moment a mapping has been added to `emmet.includeLanguages`, emmet suggestions will show up and the command `Emmet: Expand Abbreviation` will use the mapped syntax.
Anyone finding this as noise, can update `emmet.showExpandedAbbreviation` to `inMarkupAndStylesheetFilesOnly`

This is done with https://github.com/Microsoft/vscode/commit/dd7adcc1615d86c33e139b677f5adf69f1c2cf91
