### ISSUE TITLE
Selection should include character under block cursor

### ISSUE THREAD

**Issue by ghost** [Microsoft/vscode#2997]
Implementing a block cursor is maybe not as straightforward as first seemed.  When there are active selections and the cursor type is a block cursor, the column that the cursor is shown to occupy is supposed to be considered part of the selection.
### STR
1. With a block cursor enabled, type "foo bar baz" in a new document
2. Using the mouse, try to select the entire word "foo"
3. Copy and paste it into some scratch space
4. Move the cursor over the "b" in "bar"
5. Using Shift+Right Arrow, select the entire word
### Expected Results

Pasting in step 3 pastes the entire word "foo", and selecting the word "bar" with the keyboard in step 5 should leave the block cursor blinking over the "r", or alternatively, leave no visible trace of the cursor at all, while the selection is active.
### Actual Results

The paste step in 3 only pastes "fo", and using the keyboard for selection in step 5 hints towards why: after selecting "bar", the block cursor is shown hovering over the space that follows instead of the "r" at the end of the word.

**Comment by chevex** [comment]
I am experiencing this issue as well. Also, the block cursor doesn't have any transparency. Meaning you can't see the character under the cursor until you move the cursor off of that character.

**Comment by alexandrudima** [comment]
To keep the number of issues in our inbox at a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: we look at the number of votes the issue has received and the number of duplicate issues filed. Thank you for your time and understanding.

P.S. If you disagree and feel that this issue is crucial: we're happy to listen and to reconsider.
