### ISSUE TITLE
HTML tag auto complete not working correctly in .jsx files (React)

### ISSUE THREAD

**Issue by Orbyt** [Microsoft/vscode#29992]
- VSCode Version: Version 1.13.1
- OS Version: macOS Sierra

**Steps to Reproduce:**

1. Open a `.jsx` file.
2. Type `<div>`/`div` or any other combination and press enter/tab.
3. On first run, typing `div` and hitting tab _will_ auto complete only once.
4. Afterwards, tag auto complete does not work at all.

**Reproduces without extensions:** Yes

I have no extensions installed.

**Comment by mjbvz** [comment]
We don't ship with builtin support for tag completion but there are some popular extensions that enable it: https://marketplace.visualstudio.com/items?itemName=formulahendry.auto-close-tag

The current behavior is caused by emmet. You can disable it by setting `"emmet.triggerExpansionOnTab": false`.  @ramya-rao-a is also updating vscode to use the next version of emmet and improving emmet support for jsx files. You can try this out in insiders builds by setting:

```
"emmet.useNewEmmet": true,
"emmet.showExpandedAbbreviation": "always"
```
