### ISSUE TITLE
Title Bar should adapt to theme

### ISSUE THREAD

**Issue by cenkt** [Microsoft/vscode#29997]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|jupyter|donjayamanne|1.1.3|
|python|donjayamanne|0.6.5|
|code-runner|formulahendry|0.6.24|
|beautify|HookyQR|1.1.1|
|Go|lukehoban|0.6.62|
|vscode-icons|robertohuertasm|7.10.1|;

---

Steps to Reproduce:

1.The title bar stays white even the theme is switched to dark
2.

**Comment by cenkt** [comment]
![image](https://user-images.githubusercontent.com/6926806/27765278-185ffab2-5eb6-11e7-893e-3ec8fb7c7875.png)
I have added a screen capture...

**Comment by cenkt** [comment]
![image](https://user-images.githubusercontent.com/6926806/27765286-4d5bf298-5eb6-11e7-9584-bc2caee3f8cc.png)
Just added a screen capture...

**Comment by jens1o** [comment]
Is that even possible on windows?

**Comment by elliott-parkinson** [comment]
Indeed it is, the fastest way might be to use a library like (or actually) the following:
https://libraries.io/npm/electron-titlebar-windows

The titlebar could use the background and text colour of the editor background.

**Comment by elliott-parkinson** [comment]
The image below is an example of an expected look (achieved through accent colour on Window titles for the purposes of the screenshot).

![expected](https://user-images.githubusercontent.com/13736856/28367472-fecf98ce-6c88-11e7-9037-da2ef7b3a43a.png)

**Comment by lawrencejob** [comment]
This is a great idea, and that mockup looks lovely. I wonder what it would mean for branding, though?

I'd love to highlight the icon issue too from discussion in #882 . It becomes much more pressing when the title bar changes for all users (so far it only get weird when people manually enable accent colours).

![image](https://user-images.githubusercontent.com/1598811/28630468-39ea3786-7222-11e7-91b5-bac7715cd18b.png) 
![image](https://user-images.githubusercontent.com/1598811/28630486-44d76ce0-7222-11e7-8581-57bcf80d56f9.png)

**Comment by elliott-parkinson** [comment]
I think this could be easily resolved by just removing the icon in the titlebar:
![titlebar](https://user-images.githubusercontent.com/13736856/28769436-6cb11ec8-75d3-11e7-8384-c459fe1ab632.png)

See the above example of the universal app for todoist. It doesn't actually need to be there at all, and it would create more space for filenames on smaller monitors.

**Comment by Hypnoes** [comment]
Infect, Electron provide APIs to create frameless window. [Frameless Window](https://electron.atom.io/docs/api/frameless-window/). So we can draw our own title bar to modify it.

**Comment by Hammster** [comment]
@Hypnoes correct, adding the frameless option to /src/vs/code/electron-main/window.ts `options` variable does remove the title bar and border of windows. But this also means reimplementation of the titelbar. An example of this is https://github.com/zeit/hyper/pull/946

Things that need to implement are:

- Custom area for the title bar, which is draggable via `-webkit-app-region: drag`
- Icons for the window interactions, preferably customizable or predefined for the OS
- Border options, for the Windows 10 look and feel around the window
- Context menu reimplementation zeit/hyper as reference

I'm also pretty sure this removes the error where  `-webkit-app-region: drag` does not work in development mode, due to the default behavior of `titleBarStyle`.

I would like to tackle the issue myself, but tbh I've got not enough time left for at least 2 months :P

**Comment by mjyocca** [comment]
For those who prefer windows and use vscode extensively, looking at a white title bar or a color that doesn't match your theme get's really annoying. Would love for this to be added.

**Comment by sulkhanp** [comment]
Will this issue get any love anytime soon?

**Comment by guledali** [comment]
Agree with windows white titlebar and vscode don't match well together. Atom has a nice solution for this problem https://atom.io/packages/title-bar-replacer

**Comment by TomSputz** [comment]
This feature has been added in a recent pull request: #39972 

*Someone tell me if I'm doing this wrong :) I just really love how well this works*

**Comment by yknomeh** [comment]
@pavittarx man... that was what I needed

**Comment by pedzed** [comment]
On macOS and most Linux distributions, the action buttons are on the left. 
![Linux VSCode look](https://user-images.githubusercontent.com/8146593/45265669-fa06d280-b44e-11e8-920c-e2a0d0de1580.png)

I would love to use the 
```json
"window.titleBarStyle": "custom"
```
setting, but it forces a Windows 10 look.

![Windows 10 VSCode look](https://user-images.githubusercontent.com/8146593/45265685-64b80e00-b44f-11e8-90a7-4bdbda9538e9.png)

**Comment by guledali** [comment]
They have just recently added it to the backlog search for [Feature Request] Customizable Titlebar Buttons

**Comment by sbatten** [comment]
The intent is to make this the default behavior on Windows this milestone.

**Comment by pavittarx** [comment]
@yknomeh Thanks, I just tried to help the ones who started this thread or the ones who may come in searching here. 😃 
<hr/>
@pedzed This feature was pending from a long time, while the problem was that title bars on Windows & Linux was unable to produce a dark title bar, when using a dark theme. I guess, you know that already. 
The feature has been implemented recently, but it is still better than what it used to be. 😆 I guess, you should look out for some other issue, or create a new one. The purpose of this one is served, finally `title bar adapts to the theme`,
