### ISSUE TITLE
Markdown preview not updating real time

### ISSUE THREAD

**Issue by kaihendry** [Microsoft/vscode#29991]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:18:03.540Z)
- OS Version: Linux x64 4.11.7-1-ARCH
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-docker|PeterJausovec|0.0.16|
|Go|lukehoban|0.6.62|;

---

Steps to Reproduce:

1. Open a .md file
2. Ctrl+k v for split view preview
3. Not realtime updating like stated upon https://code.visualstudio.com/docs/languages/markdown

https://s.natalian.org/2017-07-01/vs-md.mp4

**Comment by hamxabaig** [comment]
It works on my side. The .md file is updating real time. I've vs code on mac, same version `Version 1.13.1 (1.13.1)`

**Comment by kaihendry** [comment]
I noticed my file is actually .mdwn, not .md. 

**.md** indeed updates in realtime. Can I make .mdwn behave the same way?

**Comment by hamxabaig** [comment]
Yes, I think we should have another extension for Markdown files for linux. As according [to this answer ](https://superuser.com/a/285878) 

> .MD files in linux could be machine description files for compiling code with GCC.

But idk if there are other extensions of markdown that vscode supports.

**Comment by mjbvz** [comment]
Yes, only markdown language mode documents are updated in realtime. In VSCode 1.14, I've disabled the preview entirely for non-markdown documents because it was causing confusion like this. 

For non standard file extensions, you need need to configure file associations in your settings:

```json
files.associations: {
    "*.mdwn": "markdown"
}
```

Look in the lower right corner of the status bar to ensure that the language mode for the current document is set to `markdown`.
