### ISSUE TITLE
Simulating a keypress for extensiona

### ISSUE THREAD

**Issue by Chillee** [Microsoft/vscode#30009]
For the VSCodeVim extension, we are running into an issue where we are unable to handle tabs properly. When in insert mode, if the user presses tab, we must currently ignore it if the user presses tab, as we don't know what context the tab is done under.

The `<tab>` might be triggering an emmet abbreviation, it might be autocompleting, or it could just simply be a regular tab.

Is there any way to simulate a tab press (with all the associated context rules).

**Comment by rebornix** [comment]
@Chillee a good practice for this case is actually adding `mode == Insert` to `when` clause for `Tab`.

The problem @Chillee described is actually about delegating Tab back to Code but skipping current command override. For example, there are two extensions overriding Tab key, A and B, and B finally wins, the override chain is like 

```
B ---> A ---> core
```

But in extension B, we want to ask VSCode to Tab again, but starting from the next overridden handler `A ---> core` instead of going through the original override chain again.

Right now our solution for this is `when` clause.

**Comment by Chillee** [comment]
@rebornix That doesn't work in all cases. For example, as a simple case, say you wanted to press `<Tab>` as part of some command palette command.
