### ISSUE TITLE
Debug stepping multi-threaded application doesn't follow thread

### ISSUE THREAD

**Issue by Anketell** [Microsoft/vscode#30002]
- VSCode Version: 1.13.1
- OS Version: Fedora 21

Steps to Reproduce:

1. Place a breakpoint to interrupt execution.
2. Once the breakpoint is hit, step over (F10).

The focus in the call stack window will change from the current thread's call stack to the first call stack in the list. To continue stepping, the correct call stack (thread) must first be selected. 

This make stepping through threaded code quite tedious. 

The expected behaviour is that the focus in the call stack window remains at the top of the call stack for the current thread and doesn't change.

**Comment by isidorn** [comment]
@Anketell I believe you are debugging C# as I could repro this issue for that language.

The issue here is that the `stop` event coming from the debug adapter does not respect the threadId for the `next` request from vscode.

Example, there are threads with the following ids 1, 2, 3. User focuses thread 1, preses step, VSCode sends `next` request for threadId: 1, adapter incorrectly sends stopped event for threadId: 2 with allThreadsStopped: true. Adapter should respect the threadId in the `next` request.

As the user is pointing out this makes debugging tedious and it would be great to fix.

**Comment by isidorn** [comment]
This should be covered by https://github.com/OmniSharp/omnisharp-vscode/issues/1617

**Comment by Anketell** [comment]
My apologies I didn't mention, am debugging in C++. It does appear that the MS C++ adaptor is to blame as GDB certainly knows what thread has been stepped.

**Comment by isidorn** [comment]
@Anketell please open the same issue in the https://github.com/Microsoft/vscode-cpptools
Both C# and C++ seem to be suffering from this

**Comment by Anketell** [comment]
Thanks @isidorn will do.
