### ISSUE TITLE
And, or and not operators are treated like functions

### ISSUE THREAD

**Issue by ChaosMTA** [Microsoft/vscode#30028]
- VSCode Version: latest
- OS Version: Windows 10

Steps to Reproduce:
1. Open a Lua file and use the syntax highlighting

Reproduces without extensions: Yes

The or, and, and not operators are not properly highlighted

http://i.imgur.com/VePdYJB.png

They are treated like functions.

I was directed here from the Lua support extension stating it is a VScode issue

**Comment by rbenson** [comment]
It may be an issue with your theme. Have you tried changing it?

**Comment by ChaosMTA** [comment]
This happens on all themes

**Comment by rbenson** [comment]
I took your image, and typed it into a file. If you do F1 and search for scope, then go to and, or, and not, they all have a scope of keyword.operator.lua. To make  those colored differently, their scopes need to be changed, and then defined in a theme AFAIK.

**Comment by aeschli** [comment]
![image](https://user-images.githubusercontent.com/6461412/27813951-00c9b1fc-60ac-11e7-9f8c-0964c629f655.png)


The scope `keyword.operator` is a common scope for operators. No need to change the grammar.
But it's up to themes to decide how to colorize these tokens.
E.g. the VSCode defailt themes gives them the default foreground color as like with other operators such as +, &  (that's by design)

The solution here is to choose a theme that colorizes like you want it.
