### ISSUE TITLE
Debug Console does not support special codes (Colors, clear line etc.)

### ISSUE THREAD

**Issue by msarafzadeh** [Microsoft/vscode#3006]
An example:

```
Starting work...
[2K[1GProgress 0%[2K[1GProgress 9.03%[2K[1GProgress 17.51%[2K[1GProgress 27.11%[2K[1GProgress 35.59%
```

Those `[2K[1G` codes are printed to `stdout` in order to clear the line and move the cursor to the left. Such codes are used by any terminal program to control what's on the screen, including programs such as `vim` and so.

Colors are not mandatory in the debugger console, but controlling the cursor is - as it can confuse the poor bastard trying to understand what's going on from the terminal output.

**Comment by isidorn** [comment]
@bpasero you did the handle ansi output, forwarding to you. Feel free to give back

**Comment by danielgindi** [comment]
:+1:

**Comment by bpasero** [comment]
@isidorn the output panel uses https://github.com/Microsoft/vscode/blob/master/src/vs/base/common/strings.ts#L551 to remove ANSI codes. I suggest REPL does the same and adds the [2K thing which does not seem to get handled yet.

The output will still not make much sense though because the real fix is to fully support ANSI in output and repl which is a feature on our backlog.

**Comment by weinand** [comment]
@msarafzadeh the debug console is not a terminal emulator and it only implements a small number of ANSI control codes. If your debuggee requires to run in a terminal emulator, please use the external console by setting the `externalConsole` attribute in launch.json to true.

**Comment by isidorn** [comment]
As @bpasero suggested now we are removing ANSI codes from repl output. However I could not find the [2k thing in the [ansi escpae codes](https://en.wikipedia.org/wiki/ANSI_escape_code) so I did not add it. What is the format of these [2k escape codes - are they speced somewhere?

Also as @weinand suggested, please use the external console as a workaround since we do not handle all ansi escape codes.

**Comment by bpasero** [comment]
+1 for ext console in that case.

**Comment by m1tk4** [comment]
Also, "integratedTerminal" works very well for this.
