### ISSUE TITLE
Integrated Terminal: add "Clear Console" button

### ISSUE THREAD

**Issue by rokoroku** [Microsoft/vscode#30077]
- VSCode Version: 1.14.0-insider

Currently, the buttons in the integrated terminal panel are just `add`(+) and `kill`(trash can).
The only two way to clear terminal output is using the shortcut or using the context menu.

(Using 'clear' command in terminals seems like "cleared", but when we scroll to top later after some outputs, the previous output reveals again. -> it may seem to another bug I think)

However, I can see "Clear Console" (`clearRepl` in i18n resource id) buttons in vscode's **problems**, **output** and **debug console**.

Why don't we have "Clear Console" button in vscode's integrated terminal?
Would it be a PR-welcomed feature?

**Comment by Tyriar** [comment]
Since the user can't customize the actions the fear of adding this is causing bloat. Right now there terminal has 4 buttons and a dropdown which is the most UI along with output. I think we should revisit this when the terminal UI gets redone for tabs https://github.com/Microsoft/vscode/issues/10546 and/or the panel gets tweaked to work vertically https://github.com/Microsoft/vscode/issues/2806

Also there are other ways of doing a clear in the terminal which you might prefer:

- cmd+k on macOS
- via command palette: ctrl+shift+p, "tclear"
- via custom keybinding:

  ```js
  { "key": "ctrl+k", "command": "workbench.action.terminal.clear",
                      "when": "terminalFocus" }
  ```
