### ISSUE TITLE
[themes] Flattening of text mate scopes leads to wrong coloring

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#3008]
- Open nodeAppInsightsTelemtryAppender.ts#40
- Notice broken colouring of comments inside contructor arguments

<img width="543" alt="screen shot 2016-02-14 at 18 00 03" src="https://cloud.githubusercontent.com/assets/1926584/13035008/ed1f36a4-d344-11e5-83df-caf715965c47.png">

Other problematic languages with deep scope hierarchies:
- JSX tags
- Java

**Comment by aeschli** [comment]
Problem is the flattening of the text mate scopes

**Comment by anyong** [comment]
Is there any progress on this issue? Judging by the other issues linked here, I'm assuming this is the same problem; it happens about half the time I do object destructuring in a render method with JSX, depending on where the newlines are.

![image](https://cloud.githubusercontent.com/assets/6260469/14666148/5bcb18b8-070a-11e6-8efb-54840649fd2b.png)

**Comment by mikemimik** [comment]
I believe this is still an issue with destructuring in ES6
```javascript
let {
  first,
  second,
  third
} = destructVar;
let otherVar = 6;
```
The second `let` wont be coloured correctly.
I have a large `class` module and the `static` methods defined after a large variable destructuring (multiline) aren't coloured correctly.

**Comment by RichieAHB** [comment]
I'm noting a lot of issues in Javascript. For example, passing objects as function parameters is just a whiteout in monokai ...

![screen shot 2016-05-17 at 15 20 42](https://cloud.githubusercontent.com/assets/1652187/15325641/fc46aaa8-1c42-11e6-9622-ddedf36c386d.png)

**Comment by jasonwilliams200OK** [comment]
@aeschli, could you point to the syntax highlighting heuristic code which disambiguate these tokens, so we can try to fix it?

**Comment by aeschli** [comment]
Flattening happens at https://github.com/Microsoft/vscode/blob/master/src/vs/editor/node/textMate/TMSyntax.ts#L324
The challenge is the API ripple through the editor model APIs as well as fixing the color matching that is currently done with using CSS.

**Comment by Velok** [comment]
Don't know if I understand this correct.. One problem is the interference of the scopes because they are handled as css classes attached to the span tokens in the editor.

For example: 

A class block gets the scope `meta.class` -> css classes `meta class`
The classname itself `entity.name.class` -> `entity name class`
A method declaration in the class block `meta.method.declaration` -> ..
The methodname itself `entity.name.function`

So the methodname token gets this classes: `meta class entity name declaration method function`

If you want to style classname and methodname the highlighting depends on the order in the tmTheme file. This is because the token has the css-class `class` from the scope `meta.class` and the class `function` from `entity.name.function`. So if you style the classname after the methodname in the tmTheme File it will override the style of the methodname.

![image](https://cloud.githubusercontent.com/assets/6967752/19357117/741cd046-9170-11e6-95ef-8d6c31298758.png)
![image](https://cloud.githubusercontent.com/assets/6967752/19357135/86974c88-9170-11e6-91f8-6ca70f5d26a7.png)

How can this be fixed?

One approach is to add the scopes as they are to the html span-tokens i.e. `entity.name.function meta.class` (or with dashes instead of the periods) instead of `entity name function meta class`. 

Other ideas?
