### ISSUE TITLE
Launcher/debugger breaks something in Electron web worker (with node enviroment)

### ISSUE THREAD

**Issue by FrogTheFrog** [Microsoft/vscode#30105]
- VSCode Version: 1.13.1
- OS Version: Windows 10 x64

Steps to Reproduce:

1. Download [this](https://github.com/FrogTheFrog/electron-quick-start.git) repository.
2. Run `npm install` in working directory.
3. Run `npm run start`.
4. Open developer tools via menu or `Ctrl+Shift+I`.
5. Confirm that there are no errors and close Electron app.
6. Launch Electron app via debugger ("Electron Main").
7. Open developer tools via menu or `Ctrl+Shift+I`.
8. Get `Uncaught Error: Cannot find module` error.

Reproduces without extensions: Yes

Here's how everything looks in action:

![error](https://user-images.githubusercontent.com/22381748/27841250-703d7ab2-6108-11e7-9cb0-c4449892a880.gif)

**Edit:**
Sorry about that sad face in the gif. I spent about an hour narrowing this issue to vscode, so I was just somehow emotional, I guess.

**Comment by weinand** [comment]
I can reproduce this only on Windows.

BTW, you can simplify the launch config to this:
```js
        {
            "type": "node",
            "request": "launch",
            "name": "Electron Main",
            "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron",
            "program": "${workspaceRoot}/main.js"
        }

```

**Comment by weinand** [comment]
The problem is an environment variable `ELECTRON_NO_ASAR` that "leaks" from VS Code into the Electron debuggee from VS Code.

VS Code uses `ELECTRON_NO_ASAR` internally to turn off module loading from *.asar archives when its not needed.
However in this case, the leaked variable prevents the Electron debuggee from working correctly because files like init.js are not loaded from the electron.asar.

The fix is to prevent the leak of `ELECTRON_NO_ASAR`.

Please note: setting the value of `ELECTRON_NO_ASAR` to 0 does not fix the problem because Electron is only checking for the existence of the `ELECTRON_NO_ASAR` variable, not the actual value. So it is not possible to add a `"env": { "ELECTRON_NO_ASAR": "0" }` to the launch config.

/cc @bpasero @auchenberg @roblourens

**Comment by weinand** [comment]
@bpasero who can take care of fixing the `ELECTRON_NO_ASAR` "leak"?

**Comment by roblourens** [comment]
In the terminal config, you can set `"foo": null` to "delete" a variable, we should support the same in launch configs.

**Comment by weinand** [comment]
@roblourens yep, I've though the same and have that already implemented for node-debug. I'll create an issue for this...

**Comment by weinand** [comment]
I've verified that this works now if `ELECTRON_NO_ASAR` is undefined in the environment like this:
```
      "type": "node",
      "request": "launch",
      "name": "Electron Main",
      "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron",
      "program": "${workspaceRoot}/main.js",
      "env": {
            "ELECTRON_NO_ASAR": null
      } 
```
