### ISSUE TITLE
Suggestion: display TypeScript version in status bar for JS files

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/vscode#30129]
When viewing a JS file, the TypeScript version is not displayed in the status bar, unlike when editing TS files where it is displayed.

JS files may be used with TS via `allowJs`/`checkJs`.

**Comment by mjbvz** [comment]
Yes, we decided to disable the version status a few versions of vscode ago because the TypeScript version is generally not relevant for majority of JavaScript workspaces. I think we want to preserve this behavior, but a few thoughts:

* Perhaps we should show the status in JS files if you are using a version of TypeScript that is different from VSCode's built in version
* And/or query typescript to check if a js file is part of a `tsconfig.json` project and show the status if this is the case

**Comment by OliverJAsh** [comment]
> And/or query typescript to check if a js file is part of a tsconfig.json project and show the status if this is the case

I would favour this approach, as it can also be used as an indicator for whether the current file is picked up as part of the dependency graph.

**Comment by mjbvz** [comment]
Closing this issue since no one has expressed further interest in it
