### ISSUE TITLE
Touch: Sashes are not firing onDidEnd event when using touch to move

### ISSUE THREAD

**Issue by penproductions** [Microsoft/vscode#30138]
- VSCode Version: 1.13.1
- OS Version: Windows 10
- System: Surface Pro 4

Steps to Reproduce:

1. Split an editor vertically or horizontally
2. Resize split editor with finger to the left or right as far as possible. When horizontal any amount will do.
3. Try to resize the editor a second time with finger, pen or mouse and the cursor doesn't change to arrows and the editor will not resize. 
4. To resolve the issue you need to split the editor again and then delete the new window. 

Reproduces without extensions: Yes

**Comment by penproductions** [comment]
It isn't that I can't resize with touch, it is I can't resize a second time. When the editors are horizontal it is very hard to do the first time but once again after it has happened it doesn't work at all.

**Comment by bpasero** [comment]
@isidorn I do not think this is a regression but since you are in this area anyways, the issue seems to be that our Sashes, even though they support touch, do not fire the [`onDidEnd`](https://github.com/Microsoft/vscode/blob/master/src/vs/base/browser/ui/sash/sash.ts#L213) event when touch finishes. This causes for the editor that the sash is not moved to the correct location when the sash is no longer moved.

**Comment by bpasero** [comment]
Thanks!
