### ISSUE TITLE
Tasks - show the number of detected/matched  problems in the terminal output

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#30193]
When a task terminates, it would be nice to show the number of problems detected in the terminal.

**Comment by dbaeumer** [comment]
This requires API on the terminal to set the message. Currently this is a boolean.

@Tyriar any objection that I make the API a string or better a function returning a string.

**Comment by Tyriar** [comment]
@dbaeumer do you mean waitOnExit? It's already a string https://github.com/Microsoft/vscode/blob/40606d2e8da0201978efcf8a9dc2a882a362b75b/src/vs/workbench/parts/terminal/electron-browser/terminalInstance.ts#L585

Instead of making `waitOnExit` a `boolean | string | () => string` it might be better to just expose some `writeToTerminal` function that allows you to write as much as you want to xterm https://github.com/Microsoft/vscode/blob/40606d2e8da0201978efcf8a9dc2a882a362b75b/src/vs/workbench/parts/terminal/electron-browser/terminalInstance.ts#L590, that way you can write whatever you want on your side when the process exit happens.

**Comment by dbaeumer** [comment]
@Tyriar wasn't aware that this is already a string. Having a `writeToTerminal` is the deluxe variant with the most flexibility.  I will look into exposing it via the ITerminalInstance.

**Comment by Tyriar** [comment]
@dbaeumer :+1: should be just a matter of passing the data through to `xterm.sendText`

**Comment by dbaeumer** [comment]
Depends on #31968

**Comment by Tyriar** [comment]
`waitOnExit` became a function recently so this should be fairly easy, at least from the terminal side.

**Comment by Tyriar** [comment]
I don't think we should do this now since it will be common for the program to show x errors like this:

![image](https://user-images.githubusercontent.com/2193314/177598109-b6cfd541-3df4-4648-be2c-70835f8f147a.png)

And also the problems badge is quite prominent.
