### ISSUE TITLE
Is the search bar supposed to be a float bar?

### ISSUE THREAD

**Issue by CAIJUNYI** [Microsoft/vscode#30233]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.6.7|
|Go|lukehoban|0.6.62|
|vscode-icons|robertohuertasm|7.10.1|
|dark-plus-material|vangware|1.0.4|;

---

Steps to Reproduce:
1. Ctrl + F to search some words
2. scroll up to the top, and there will appear one blank blank with the height of the search bar
3. In my view, the search bar is supposed to be a float bar
![search bar](https://user-images.githubusercontent.com/10704251/27949777-889315d8-6331-11e7-8a8e-bb13fcc9807e.png)

**Comment by fabiospampinato** [comment]
I disagree with your view.

A floating search widget like the one VSC uses has the advantage that most of the times after you open it you will be able to read the same amount of code that you could before.

And If you want it larger you can simply expand it, there's a draggable handle at the very left of the search widget.

**Comment by drboyer** [comment]
@fabiospampinato I respect your perspective, but it does seem odd that if you aren't at the top of an editor, the Find/Search bar is floating, but if you are at the top, the code gets pushed down the height of the Find bar. What's even stranger is if you expand it to reveal the Replace box, it will not push the text in the editor down further (it will however if you scroll down then back up to the top of the editor again).

This definitely seems like unintended behavior (and I believe did not occur in earlier releases? Not 100% sure though).

**Comment by fabiospampinato** [comment]
It's actually a bit smarter about that, if you have something highlighted on the 1st line that won't be covered by the search widget there won't be a push down, otherwise there will be.

The fact that it doesn't do the same with the reveal of the replace input looks like a bug to me. Thanks for pointing that out.

**Comment by roblourens** [comment]
This is as designed. I don't think it would look good for the find widget to shift the whole editor when you show the replace input.

**Comment by fabiospampinato** [comment]
It doesn't have to always happen, just in the same cases where the search widget does it.

It doesn't look good also when it happens because of the search widget, but it does it anyway because it's functional.

I think the same reasoning should be done for the replace input, same problem same solution.

**Comment by rebornix** [comment]
@CAIJUNYI we did consider making it float when designing but it turns out to be too distracting and making the position of Find Widget less predictable.
