### ISSUE TITLE
Wrong TextEditorSelectionChangeKind for click inside a selection

### ISSUE THREAD

**Issue by KamiKillertO** [Microsoft/vscode#30230]
- VSCode Version: Code 1.13.1 
- OS Version: Darwin x64 15.6.0
- no extensions
---

The `TextEditorSelectionChangeKind.Command` is fired instead of `TextEditorSelectionChangeKind.Mouse` when a click occur inside a selection. 

**Steps to Reproduce:**

1. Select few lines
2. click anywhere inside the selection

![kapture 2017-07-07 at 9 13 52](https://user-images.githubusercontent.com/9579729/27947264-7241b014-62f5-11e7-8500-a1b82417da28.gif)

The code running in the exemple :

```typescript
'use strict';
import {
  window,
  ExtensionContext,
  TextEditorSelectionChangeEvent,
  TextEditorSelectionChangeKind
} from 'vscode';

export function activate(context: ExtensionContext) {
    window.onDidChangeTextEditorSelection((event: TextEditorSelectionChangeEvent) => {
		// 1: Keyboard
		// 2: Mouse
		// 3: Command
		console.log(`Event kind : ${event.kind}`)
	}, null, context.subscriptions);
}
export function deactivate() {}
```

**Comment by jrieken** [comment]
The [convert-logic](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/node/extHostTypes.ts#L994) checks for `command` and `mouse`... 

<img width="552" alt="screen shot 2017-07-10 at 09 59 24" src="https://user-images.githubusercontent.com/1794099/28008143-8d9d0c2e-6556-11e7-9c6b-3dffd0ce17a2.png">

**Comment by alexandrudima** [comment]
The kind is informative as best, flaky, and perhaps should never have been exposed as API, but I think we had an extension in terrible need of it.

The root cause here is: in this specific case, it is a recently added editor contribution (the dnd code), and not the editor core that reacts to the mouse move event and uses internal editor api to set the selection, that's why now the event reason is `'api'`. Disabling dnd will probably make the kind in this case be mouse again...

**Comment by jpotterm** [comment]
I can confirm that setting `"editor.dragAndDrop": false` successfully works around this bug.
