### ISSUE TITLE
Explorer: adding a folder to the explorer collapses the first

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#30247]
Steps to Reproduce:

1. be in single root, have nothing expanded in particular
2. add a folder to workspace

=> the folder is not expanded anymore

![flicker_chrome58](https://user-images.githubusercontent.com/900690/27958840-25b0861e-6325-11e7-9e63-208500c88b75.gif)

**Comment by isidorn** [comment]
I can only repro this when I am going from no-workspace to workspace.
I believe the issue is that we use a brand new ui storage for the workspace and in that case I do not know the previous state.

If nothing is expanded I could always expand the first folder but that does not feel right, since some users might want to keep all their folders in a workspace colapsed.

**Comment by bpasero** [comment]
@isidorn yeah I think the original issue is not there anymore, can also not reproduce.

Still, maybe do expand if the workspace only contains one folder and you have no previous state

**Comment by isidorn** [comment]
@sandy081 already wrote code that should do this [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/browser/views/explorerView.ts#L730). However it is not working because when that code runs `contextService.hasFolderWorkspace()` returns `false`

So the bottom line issue is that hasFolderWorkspace is returning a wrong result that early in the game.

**Comment by isidorn** [comment]
Ok, actually hasFolderWorkspace() correctly returns false, just the naming and the comments of that method could be improved since it was crpytic for me when it returns what.
Now I also added a check for multi root workspace with only one root

**Comment by sandy081** [comment]
@isidorn We have three states 

- Empty Workspace
- Single Folder Workspace
- Multi Folder Workspace

There are three methods to tell about above facts

- hasWorkspace()
- hasFolderWorkspace()
- hasMultiFolderWorkspace()

Please let me know if you have any suggestions to improve the naming.

**Comment by isidorn** [comment]
How about the following? Makes it clearer?

```typescript
getWorkspaceState(): WorkspaceState;

enum WorkspaceState {
   EMPTY,
   SINGLE_ROOT,
   MULTI_ROOT
}
```

**Comment by sandy081** [comment]
Thanks @isidorn.. Will change and adopt everywhere.
