### ISSUE TITLE
Views management feedback

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#30249]
As discussed today, some feedback on view management:

1. show "Hide Side Bar" in the context menu when seeing all views to align with activity bar menu

![image](https://user-images.githubusercontent.com/900690/27959494-f6dac6d0-6327-11e7-9a08-1dff20d086a8.png)

2. Name it "Remove from XYZ View" here:

![image](https://user-images.githubusercontent.com/900690/27959509-0bac9322-6328-11e7-9c82-27e94d948f03.png)

3. When reordering via DND I think it would be nice to drag the entire section and workaround the overflow issue with maybe tweaking the CSS just for the DND operation?

**Comment by SamVerschueren** [comment]
Is it possible to persist the settings of the explorer view?

<img width="244" alt="screen shot 2017-11-09 at 10 47 15" src="https://user-images.githubusercontent.com/1913805/32598963-5f9ae676-c53b-11e7-970a-ca410dda85d1.png">

Because to be honest, I couldn't care less about the commits, compare commits, xml document and gitlens panes in explorer. I can hide them by deselecting but whenever I open another project they come back. I want them gone, for every project I open. Couldn't find anything in the docs, but might have missed this.

**Comment by eamodio** [comment]
For GitLens at least you can set `"gitlens.gitExplorer.enabled": false` to turn it off completely

**Comment by SamVerschueren** [comment]
Jup, found out about it after I posted this. I ended up removing all the other extensions who create these custom views.

**Comment by sandy081** [comment]
Closing this as first two feedback items are implemented. There are no immediate plans to implement Drag and drop.
