### ISSUE TITLE
Search panel -- annoying "toggle replace button"

### ISSUE THREAD

**Issue by fabiospampinato** [Microsoft/vscode#30250]
The "toggle replace button" (inside the yellow rectangle in the screenshot below) is broken in so many ways, let me enumerate them:

1. It's whole purpose, I guess, is to hide a rarely used input in order to barely show a couple more lines of results. But why even hiding the "replace" input? I don't know about you but I've never found a use for the "files excluded through settings" input, it's not even editable, why not hiding it instead? maybe "files to exclude" as well? It seems like a more logic approach to me.
2. We are wasting a whole bunch of pixels (in the red rectangle below) just because of it.
3. Even if you open it, you'll probably find it closed anyway pretty soon. Just switch to another panel and come back to the search panel, it's closed again. I can't even count how many time I wrote inside the "files to include" input by mistake.
4. It can't be opened with the keyboard, it needs to be clicked. Do you want to check the explorer or git while using it? Sorry, click it again.

The best solution to me is getting rid of it all together, but I guess a reasonable solution is to add the ability to hide it via a `search.alwaysOnInputs` setting or something. I wouldn't mind an analogous setting for the floating search widget.

What do you think?

<img width="264" alt="screen shot 2017-07-07 at 14 47 56" src="https://user-images.githubusercontent.com/1812093/27958674-82b42862-6324-11e7-948f-a2cd177ae921.png">

**Comment by fabiospampinato** [comment]
I think I can answer the first point of my list on my own, it looks like there's another button for hiding the other inputs:

<img width="532" alt="screen shot 2017-07-07 at 15 52 38 copy" src="https://user-images.githubusercontent.com/1812093/27960866-27f438d2-632d-11e7-9108-ba736f612c75.png">

The fact that I haven't even noticed it in months might say something, other than I'm distracted. It looks weirdly positioned to me, it seems to be aligned with the other buttons, vertically, but all of them have another button or an input next to them, this one doesn't seem aligned with anything horizontally. It's also responsible for the inconsistent gutter between the 2nd and 3rd inputs (if you look at the 3rd and 4th inputs the gap between them is narrower).

Why not moving it to the toolbar above? There's already a button for folding the results, I think having a button next to it for "folding" the inputs might be more appropriate.

**Comment by roblourens** [comment]
I'm not sure that button is responsible for taking up that space, it's more that the file result item looks good with a bit of left margin, and the result under the file item should be contained within the file result item. It could probably be a bit tighter, but I wouldn't push it all the way to the left.

> But why even hiding the "replace" input?

I don't use it that often and think it looks better when it's hidden.

>I don't know about you but I've never found a use for the "files excluded through settings" input, it's not even editable, why not hiding it instead? maybe "files to exclude" as well?

I'll probably be removing the "files excluded through settings" box this month - https://github.com/Microsoft/vscode/issues/27226. They are hideable with the ... button.

> Even if you open it, you'll probably find it closed anyway pretty soon. Just switch to another panel and come back to the search panel, it's closed again.

If you use cmd+shift+f, then it hides replace, because that's the shortcut for 'find'. You can use cmd+shift+h if you want to replace. Or, rebind cmd+shift+f to 'replace'.

> It can't be opened with the keyboard, it needs to be clicked.
You can tab to it, or use the shortcut.

> The best solution to me is getting rid of it all together, but I guess a reasonable solution is to add the ability to hide it via a `search.alwaysOnInputs` setting or something.

Sorry, I don't want to add a setting for every tiny switch in the UI, I'd rather just try to do the right thing most of the time.

Regarding the ... button, the spacing is a little inconsistent as I tried to save some vertical space - I think it used to stand out more. I would rather keep the button close to the thing that it's acting on.

I'll be revamping the search viewlet this month via #27226 and #29977 so please follow those issues and stay tuned. I'll keep your feedback in mind.

**Comment by fabiospampinato** [comment]
@roblourens Thanks a lot for the detailed reply, having the **...** button and a shortcut for focussing into the replace input mostly overcomes the issue.

However I have to insist on the spacing, it looks even weirder without the replace button, also it's not even consistent between different panels, pretty ugly if you ask me:

<img width="1032" alt="gutter" src="https://user-images.githubusercontent.com/1812093/28147371-41ee18d2-6780-11e7-86da-529fa59d7175.png">

**Comment by roblourens** [comment]
On the other panels, I don't know of any reason for it to be uneven, and agree that it would look better centered evenly. Filed https://github.com/Microsoft/vscode/issues/30648 for that.
