### ISSUE TITLE
Files in node_modules show up in search despite being excluded

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#30266]
I have an exclusion in `files.exclude` for `**/node_modules` but files there still show up in search results:

![Search](https://user-images.githubusercontent.com/1078012/27974113-6796963e-6354-11e7-9170-a9d8721ec413.png)

I tried copying the `files.exclude` section and naming it `search.exclude` but it made no difference (the comment says `search.exclude` inherits `files.exclude` so I didn't really expect that to fix it).

**Comment by shockthetoast** [comment]
I am seeing a similar issue.

I have been able to fix it in mine when the beginning of the path does not use wildcards, by either ending without a `/` or with `/**`. For example, these work:
```
"wrap/lib/externals": true,
"wrap/lib/externals/**": true,
```
This does not, even though it did before the update:
```
"wrap/lib/externals/": true,
```

The strangest part seems to be the syntax DanTup was using. Doing this results in some, but not all, items in my "wrap" folder being excluded. And these are files sitting next to each other in the exact same subfolder of "wrap", so it's not a folder depth issue:
```
"**/wrap": true,
```

**Comment by roblourens** [comment]
Can you both copy the output from the 'Search' output panel?

@shockthetoast in your case, are any of the files open?

**Comment by shockthetoast** [comment]
Ah, all those files were open. I had no idea that having files open would add them to the search even when they were excluded. Is there any chance that could be made an option?

Now with all the files closed (except the settings.json), I'm running a search for "locked".
If the line in the excludes is: `"_src/wrap/lib/externals/": true,`

I get results in:

- `_src\wrap\css\menu.css`
- `_src\wrap\lib\externals\jquery\jquery-3.1.1.js` _[Should be excluded]_
- `_src\wrap\lib\VLessonExam.js`
- `_src\wrap\lib\VLessonMenuView.js`
- `_src\wrap\lib\VProgressManager.js`
- `client\locale-text.js`

If I use either `"_src/wrap/lib/externals": true,` or `"_src/wrap/lib/externals/**": true,` I get:
- `_src\wrap\css\menu.css`
- `_src\wrap\lib\VLessonExam.js`
- `_src\wrap\lib\VLessonMenuView.js`
- `_src\wrap\lib\VProgressManager.js`
- `client\locale-text.js`

So the jQuery file is properly ignored. I've run a number of different searches against different patterns with different results. Before I removed the trailing slash on many of my exclude patterns, I was receiving results in about 50 files instead of the desired 5.

I'm not sure if that's exactly what you were asking for - I couldn't find a way to copy the output, so I've just listed the filenames.

**Comment by roblourens** [comment]
The issue with open files is a bug, tracking it here: #29658

I think the difference between excludes with `/`, `/**`, and no trailing slash is a windows-specific thing. Works as expected on MacOS.

**Comment by DanTup** [comment]
@roblourens 

> Can you both copy the output from the 'Search' output panel?

I'm not actually sure what this is - I have an `Output` panel that doesn't seem to have anything search related.

That said, I am unable to repdoduce this issue today in the same project with the same search term! Is it possible something changed in 1.14? (I was on 1.13 before, have been sticking to Stable).

**Comment by roblourens** [comment]
I did mean the output panel, but it's great that 1.14 fixed it. @shockthetoast, which version were you using?

I'm not sure what would have fixed it in 1.14. There were a bunch of search changes but nothing that should have affected this.

For future reference, 
![image](https://user-images.githubusercontent.com/323878/28185054-bc738318-67ca-11e7-9f87-48cf5a7889f6.png)

**Comment by DanTup** [comment]
Weird, never noticed a dropdown there (not at PC now to check). I'll have another go at reproducing next time at PC but it might be worth just closing this in the meantime until/if I can repro!

**Comment by shockthetoast** [comment]
Sorry for the delay. 

I was on 1.14.0. I am now on 1.14.1. Neither version fixed the issue for me. DanTup, are you still not seeing the issue come back?

I'll just include the part of the output that changed, since it's long:

It doesn't work when I have the exclude set to this: `"**/wrap/lib/externals/": true,`
`-g '!/wamp64\www\scormcourses\r17\LessonWrapper\**\wrap\lib\externals\'`

It does work when I have the exclude set to this: `"**/wrap/lib/externals": true,`
`-g '!/wamp64\www\scormcourses\r17\LessonWrapper\**\wrap\lib\externals'`

**Comment by DanTup** [comment]
@shockthetoast Nope, I can't currently repro this!

**Comment by roblourens** [comment]
I can :) 

/shrug

**Comment by shockthetoast** [comment]
I'm glad to know I'm not alone. :) It's very strange that it's not working for DanTup but not for you. Did you switch to a Windows system to reproduce the issue, or are you seeing it on OSX now as well?

I'm on Win 10 Pro. Let me know if any other details would be helpful.

**Comment by DanTup** [comment]
Mr original screenshot looks like Windows. I'm currently on a Mac and it's fine. I now can't remember whether I may have been on the Mac every time I was unable to repro.

That said, v1.14.2 is out now which says it includes this fix?

**Comment by roblourens** [comment]
Verifier: 

`"search.exclude": { "foo": true}`
and
`"search.exclude": { "foo/": true}`
 should both exclude files in the `foo` folder.
