### ISSUE TITLE
Allow programmatically selecting a TreeItem in custom views

### ISSUE THREAD

**Issue by Gama11** [Microsoft/vscode#30288]
I've been trying to mimick the `files.autoReveal` behavior of the regular explorer in the Dependency Explorer of the Haxe extension. I can expand the necessary nodes just fine, but I don't think there's any way to scroll to the correct position in the view + highlight the node programmatically right now.

From what I can tell, the currently planned enhancements won't help with this (https://github.com/Microsoft/vscode/issues/27823). Could a function for selecting a node be added to API? I think a lot of other extensions would benefit from this as well, [Code Outline comes to mind](https://github.com/patrys/vscode-code-outline/issues/12).

**Comment by sailro** [comment]
This is a huge limitation, it would be so great to have such a basic feature when working with custom tree views

**Comment by pltrant** [comment]
Yes, this API would be very useful for code view/navigation extensions.  I have an extension with a custom view and it is frequently requested to highlight the node that represents where they are in the file.

**Comment by mike-lischke** [comment]
This FR could be tracked by #27823. I have (multi) selection per code in my feature wishlist there.

**Comment by sandy081** [comment]
@Gama11 @pltrant Can I assume is this request is to have an API to `reveal` an item in the tree? Or do you also need `select` as a separate API?

**Comment by sandy081** [comment]
I am working on a proposed API for this which will be available for authors to try out in this iteration and the plan to make it available in main API is in next milestone.

**Comment by Gama11** [comment]
If `reveal` implies `select`, that seems good enough to me.

**Comment by sandy081** [comment]
`reveal` and `select` are two independent actions. 

`reveal` - Reveals the item in the tree view.
`select` - Selects the item in the tree. Select will not show the item if it is not visible.

**Comment by Gama11** [comment]
In that case, both are needed to mimic the `files.autoReveal` behavior, as files are also highlighted in the regular file explorer when using that setting.

**Comment by pltrant** [comment]
Agreed with @Gama11.  Will the `select` API also invoke the click command associated with the node?  For my use case, I would not want it to do that, but I imagine others could want that, so I suggest there be a parameter to include/exclude that option.

**Comment by sandy081** [comment]
I think having just `select` without revealing does not make sense. So I thought, have a single api `reveal(element, select?: boolean)` would be much more appropriate.

@pltrant Yes, select will trigger the command. I will think to make it optional or trigger the command only when user did the selection.

**Comment by pltrant** [comment]
A single api for reveal to optionally include select makes the most sense (I agree with not seeing the benefit of just a select without a reveal).

**Comment by eamodio** [comment]
@sandy081 would using `reveal(element, true)` also focus the newly selected element?

Probably best as another api, but it would be great to be able to just focus the custom view itself (and whatever element was last selected in it)

**Comment by mike-lischke** [comment]
Selecting w/o also revealing a node does make sense. Imagine a file tree with some collapsed and some expanded nodes and you want to select all nodes for a given file type. Do you really want to make all collapsed node visible, only because they are in the selection set? That's a usability nightmare (and I'm assuming here, multi selection is already in).

**Comment by eamodio** [comment]
@mike-lischke Good point, we can't forget about multi-select, which would completely change the api proposed above

**Comment by sandy081** [comment]
@eamodio there are multiple variations for reveal like 
- only reveal
- reveal and select
- reveal and focus -> Not sure if this makes sense.
- reveal and select and focus

`focus` on a view might be helpful as an API that will focus the view itself and the last selected element as you mentioned. But what is the need for `focus` API on a element?

@mike-lischke Is there any existing real use case to support `select` api ?

**Comment by mike-lischke** [comment]
Focus is not a state of a tree item, but belongs to the treeview. Hence there is no need for focus for a tree item. If the notion of a single item is required you would use treeview focus + single selection.

Regarding `select`: I don't understand your question. Do you need examples to support the idea of having a selection API for treeview items? I assumed it would be so obvious how important that is.

**Comment by eamodio** [comment]
I would propose the following apis (don't consider the names just the ideas):
```ts
viewFocus() // focuses the view with the last selection preserved -- and keyboard focus should be on the last "active" selected item
viewReveal(item: TreeItem) // reveals the item, doesn't change selection or focus -- can change to an array to support multi-reveal if it makes sense
viewSetItemState(item: TreeItem, state: 'expand' | 'collapse', options: {  reveal: boolean = false }) // Expands or collapses an item, and optionally reveals it
viewSetSelection(selection: TreeItem[], options?: { focus: boolean = true, reveal: boolean = true }) // changes the view selection where the first item in the array is the active one and the one that would be focused/revealed
```

To be honest, I don't find `viewReveal` all that compelling, but I'm also probably missing a lot of use-cases

Thoughts?

**Comment by sandy081** [comment]
@mike-lischke It is obvious that every API will have many examples, but our requirement to introduce an API is driven by the extension authors use cases. Hence asked for your scenario for multi `select` api for your extension. 

@eamodio Since `focus` is for the view and not for the `item` mixing them too might not be a good idea. If I have `select` api on item, I would not add `focus` option to it. I would have `focus` as a separate api on view.

There will be a `TreeViewer` proxy for each tree view, which will have methods to access. I want to provide access to the `TreeViewer` while registering the data provider. So one idea is to return it while registering or propose a new API as follows. Its still in draft and thinking.

```typescript
namespace window {
		/**
		 * Create and show a new webview.
		 *
		 * @param title Title of the webview.
		 * @param column Editor column to show the new webview in.
		 * @param options Webview content options.
		 */
		export function createTreeViewer<T>(id: string, options: { dataProvider: TreeDataProvider<T> }): TreeViewer<T>;
	}

	export interface TreeViewer<T> extends Disposable {

		focus(): TPromise<void>

		reveal(element: T, select?: boolean): TPromise<boolean>;

	}
```

I think selecting an element without revealing it is not useful. It makes sense in multi-select but in single select, I would expect to show it. 

I see your request for `expand` and `collapse` api. I think this need an issue for itself, Can you please open a separate feature request so that to avoid hijacking this issue.

**Comment by eamodio** [comment]
@sandy081 ah great to know about the `TreeViewer` -- it would be nice if there was a way to get a `TreeViewer` by id, but that might be out of scope. As once you have that you'd need a way to get access to the items or be able to reveal/select by something other than the item itself.

As for focus, it really isn't just the view that is focused -- since the keyboard focus should be on the last selected item, not on the view itself. But I don't feel all that strongly about the api structure to that, as long as the desired behavior can be achieved.

If the views are going to support mutli-select, imo it would seem important for the api to support it as well - but I don't have a specific use-case in mind for it. Getting the current selection (with multi-select) could be important, but really for my use-case I would only need it if the command callback didn't provide similar context as multi-select in the explorer view.

As for hijacking this issue, I truly don't feel like that is a hijack. The expand/collapse state is very related to reveal/selection. And thinking about one without the other, imo, does a disservice to the api discussion. For example, how does `reveal` handling expansion -- does the item expand always (ideally not), is it controllable (I would argue it should be).

For the interface provided above, I think `reveal` should look more like:
```ts
reveal(element: T, options: { select?: boolean, expand?: boolean }): TPromise<boolean>;
```

I would argue that both, `select` and `expand` should be defaulted to `true`, since that feels like the most common case. And having the `options` object, allows for more evolveability in the api in the future.

Also what does the result `boolean` indicate?

**Comment by mike-lischke** [comment]
@sandy081 Thanks for clarification. What jumps directly to my mind is highlighting variables that have changed between two debugger stops (variables is next on my list). Another use case would be to select all input tokens of the same kind out of the list of available tokens (that's for a grammar debugger). Yet another use case is to highlight stackframes that contain a breakpoint or have otherwise special behavior.

I also like the idea of a dataprovider (simplifies implementing an MVC pattern).

**Comment by sandy081** [comment]
@eamodio 

> If the views are going to support mutli-select, imo it would seem important for the api to support it as well - but I don't have a specific use-case in mind for it. Getting the current selection (with multi-select) could be important, but really for my use-case I would only need it if the command callback didn't provide similar context as multi-select in the explorer view.

This would be consistent with explorer view that, command callback will have the selected items. This is something I am planning to implement as multi-select support for custom views.

>reveal(element: T, options: { select?: boolean, expand?: boolean }): TPromise<boolean>;

Agreed that having `options`  object will help in evolving. Interesting to have `expand` as an option to `reveal` api. I would not add it now unless you have a requirement for it.

> Also what does the result boolean indicate?

It is not needed.

@mike-lischke 

May I know if you are mentioning about the variables view and other built in views in Debug view?

**Comment by mike-lischke** [comment]
> May I know if you are mentioning about the variables view and other built in views in Debug view?

Yes, that's what I have in mind. However, working only if there's a concrete use case is not a good approach. Many ideas grow out of possibilities and are not really in a brain when the feature for it is implemented. I strongly believe the treeview in vscode should have a similar API like other treeviews have. I've written 2 of them, one ([TreeNT](http://www.soft-gems.net/index.php/controls/treent) is an extension of the Windows system tree control, the other ([Virtual Treeview](http://www.soft-gems.net/index.php/controls/virtual-treeview), which was extremely popular) has been written from scratch, with performance and low memory footprint in mind. So, it might be a good idea to look at such controls to get an idea, what makes sense to support.

On a side note: when you think about revealing a node (which is just `expand` and `collapse` in many other treeview and similar implementations and I believe you should keep this name scheme), but don't forgot about something like item visiblity, which is twofold:

1) Hide and show items, e.g. for filtering a tree quickly, without having to reload it.
2) Make it visible in the sense to expand all its parents and scroll it into view.

But this is also not related to selection. Make sense to create an own GH issue for it.

**Comment by mike-lischke** [comment]
I forgot to comment on the proposed API. Putting everything into one single function is not good. You cannot change the state of a node without revealing it, which is odd. And btw, what is the difference between reveal and expand, for you?

Better would be something like:

>TreeItem.expanded = true/false
>TreeItem.selected = true/false
>TreeItem.visible = true/false
>TreeItem.fullyVisible = true/false (like visible + all parents expanded)

which would make the API very clean and concise. Don't forget that querying a node's state is equally important as setting it. And setting one state should not affect the other states, except for obvious dependencies (e.g. for visible + fullyVisible).

I also don't understand why you would want to return a promise for these states (which is probably why you supposed a function API, instead of a property).

**Comment by sandy081** [comment]
@mike-lischke your feedback is very much appreciated. 

You can only access views you register and the API will be use case driven. I am sorry that we cannot expose methods thinking that this can be useful in future. Once API is out, it is hard to change, so we want to gather requirements before making it public.

Yes, revealing a node is expanding nodes, but it is an implementation detail. I see that, requested authors wanted to have `expand` or `select` methods so that they can reveal it in the view. Hence `reveal` is a better and useful api for them to implement their functionality. If authors requires a fine grained api to expand and collapse for some functionality, we will provide it (which would be nice to handle as a separate feature request).

Currently `TreeItem` is stateless and is just a view representation. Would not like to put state into it. Also currently it is a pull model, meaning, Tree model is owned by VS Code core and it asks the extension for the tree data. So `TreeDataProvider` can be also stateless and extensions might not know that an item is in the model / loaded or not. Providing methods on `TreeItem` to update would force both to hold state. Updating `TreeItem` would be a better approach in case of Push model where extension owns the Tree model. `reveal` API on the TreeView will allow extensions to just call that method by passing the handle to the item they have and Tree model takes care of expanding the hierarchy and revealing the element in the view. 

Promise will be returned to signal the completion of the operation.

**Comment by eamodio** [comment]
@sandy081 Back to the `reveal` api for a moment. Without the `expand` option, what would the behavior be? If you wanted to select a node in the tree -- would it *always* expand the node if it had children? If so, I'm not sure that is always desirable -- it would match mouse selection behavior, but not keyboard selection behavior.

For GitLens, I am thinking about some possible commands, that allow a user to jump to the GitLens view and select a node (i.e. the current branch, or current file, etc), and in some of the cases the user might want the node to be selected, focuses, and expanded, and others maybe not -- just selected and focused. So I would definitely like to see an `expand` option available.

**Comment by sandy081** [comment]
@eamodio By default revealed element will not be expanded. 

If you have the use case, I am happy to add that option.

**Comment by eamodio** [comment]
I think it would be useful. Here is a specific case. Currently, you can show the history of a branch in quick picks, but I would also like to have a command that would just find/open that branch and expand it in the GitLens view. Also from that same quickpick menu mentioned, I have a *Show in Results* which basically shows the *GitLens Results* view and adds that branch to it, with its history expanded. I had to do it that way, because there was no way for me to focus/select/expand the correct node in the *GitLens* view itself. So with this feature, I could basically rename that to instead of showing in results, it would just focus/select/expand the branch inside the branches node of the *GitLens* view.

I'm assuming calling reveal on a node that is nested will automatically expand all parents so that it will be visible. Correct?

**Comment by mike-lischke** [comment]
>  I am sorry that we cannot expose methods thinking that this can be useful in future. Once API is out, it is hard to change, so we want to gather requirements before making it public.

On the other hand, this is by far not the first Treeview implementation on this planet and over the decades a set of useful APIs have been defined on many of the previous implementation. It's not that we couldn't come up with a list of properties etc. that would certainly be used in one or the other form. And again: creativity comes from possibilities. If you don't provide certain APIs then users will start doing workarounds and it's pretty hard later to get all the code changed then. No offense intended, but if you only consider APIs that are requrested here and in similar FRs, instead of implementing the common set, it appears pretty short sighted.

> Yes, revealing a node is expanding nodes, but it is an implementation detail.

Why using a different name then? Expanding a hiearchy is such a common and well known term, it makes no sense to introduce a new one for the same functionality. That's just ego programming.

> I see that, requested authors wanted to have expand or select methods so that they can reveal it in the view. Hence reveal is a better and useful api for them to implement their functionality.

This is a similar approach like OOP vs functional programming. What is better? Having a linear code/functions like in C or better use objects? I'm all for objects!

If authors requires a fine grained api to expand and collapse for some functionality, we will provide it (which would be nice to handle as a separate feature request).

There is no fine grained API to implement. Either you have a function on the tree view to expand or collapse a node or you have that on the node itself (could also be a function or a property). The work is the same, it's only a matter of good or bad design.

> Currently TreeItem is stateless and is just a view representation. Would not like to put state into it. 

That's leaves me speechless. Such an item is all about state. It has a position, it has a selection state, it has a label, it has an expand state, it has a checked state, it has a visible state, it has an image and more. How can you say you don't want state for a node?

> Also currently it is a pull model, meaning, Tree model is owned by VS Code core and it asks the extension for the tree data.

Yes, I saw that and I really wondered why it was implemented that way. It's so pretty unusual and conflicts with simple things like app driven updates. Instead it should be an application provided data source. The model contains everything: hieararchy, nodes + their states, events for notifications etc. The treeview only takes such a model and visualizes that.

> So TreeDataProvider can be also stateless and extensions might not know that an item is in the model / loaded or not. Providing methods on TreeItem to update would force both to hold state. 

And what's so bad about this? Can you explain why you don't want to store state? How do you want to know what to update? If you have no state, you cannot compare what changed and are doomed to update the entire tree for every little change. The impact on performance will be terrible. And don't be suprised: when vscode doesn't provide state then the extensions will implement that. There's no win by rejecting the obvious needs.

> Updating TreeItem would be a better approach in case of Push model where extension owns the Tree model.

And that should be how it is implemented.

> reveal API on the TreeView will allow extensions to just call that method by passing the handle to the item they have and Tree model takes care of expanding the hierarchy and revealing the element in the view.

Setting `TreeItem.expanded = true;` allows extensions to just set a property to get a node expanded and the **TreeView** (not the model!) takes care to expand the hierarchy. Please think of the individual roles of models and views.

> Promise will be returned to signal the completion of the operation.

I'd rather prefer to make the data source (model) be an extension provided object that can send out events on various occasions, which are data related. The treeview can do the same for view releated operations (like, when it is done loading the content etc.). And they should coalesce notifications, so that extensions can update hundreds of tree items without refreshing the display a hundred times.

**Comment by eamodio** [comment]
Here is a specific feature request for GitLens: https://github.com/eamodio/vscode-gitlens/issues/275

I would like to use the `expand` option on this API to make this happen. But I would also really like the `expand` option to be more than just a `boolean` -- maybe an enum of `'item' | 'descendants'`. The idea is to be able to expand just 1 level, or deeper. 

So in the previous branch expand example, I gave, I would use `item`, but to fulfill feature request https://github.com/eamodio/vscode-gitlens/issues/275 I would use `descendants`.

Another option would be to keep the `expand: boolean`, but add an options `expandLevel: number` (or something like that) where it would control how many levels down would be expanded. Would need to support something like `-1` or some magic value to mean go all the way.

Or have `expand: boolean | number` -- if `true` it expands itself, if a number it would expand to that level (still would need a magic value for all the way)

**Comment by eamodio** [comment]
@sandy081 will this be making the Feb cut? (seems unlikely at this point)

**Comment by sandy081** [comment]
@mike-lischke Sorry for late reply. I was bit busy this week with our release stuff.

Yes, there are many Tree APIs in the market and they might share some common things and differ in other. We have our own set of protocols to follow before coming up with an API.

Naming is always tough. We do multiple rounds of feedback and come up with proper name. In this case the extension author  wants to reveal a node to the user which makes it obvious to call it `reveal`. On the other hand `expand` does not tell about showing to the user.

`properties` vs `methods` and other arguments of yours boils down to the design approach. Our design is pull model that extensions provide to the system, data sources and rendering (like label) providers and system asks for the data and render the view. This is one of the familiar designs for Tree implementation for eg., eclipse JFace  Tree view has the similar API: https://www.eclipse.org/articles/Article-TreeViewer/TreeViewerArticle.htm

**Comment by sandy081** [comment]
@eamodio Re eamodio/vscode-gitlens#275 If I understand correctly, you want the nodes to be auto expanded when view loads them? If so, Is not the `collapsibleState` property on `TreeItem` doing it? 
Reveal API is different that it allows you to show a node at any time. 

>will this be making the Feb cut? (seems unlikely at this point)?

It is part of `proposed` API for Feb release and becomes public for March release.

**Comment by eamodio** [comment]
@sandy081 the view will already be loaded and not expanded. I want to be able to have a command to select and expand the item (sometimes 1 level others all descendants).

**Comment by sandy081** [comment]
@eamodio Ah ok. So what is the context when this command is invoked in your case?

**Comment by sandy081** [comment]
Current status: Under discussion about how to expose views in the API.

**Comment by sandy081** [comment]
Verify that you can use the new `TreeView.reveal` API without having to run the extension in proposed API mode.
