### ISSUE TITLE
New Emmet still expanding abbreviaton with tab

### ISSUE THREAD

**Issue by Niichie** [Microsoft/vscode#30281]
- VSCode Version: 1.14.0-insiders, 1.13.1
- OS Version: Windows 10

Steps to Reproduce:

1. Open and HTML file in vscode
2. Type any emmet abbreviation and press tab for example:
`ul > tab`

According to the latest emmet update, when 
`"emmet.useNewEmmet": true,`

tab should behave as indentation, and should no longer expand the abbreviation.

In my editor, however, both tab and enter are able to expand the abbreviation.

Reproduces without extensions: Yes

**Comment by jens1o** [comment]
Can reproduce this, I was surprised, too.

**Comment by ramya-rao-a** [comment]
Have you explicitly set `emmet.useNewEmmet` to `true`?

We are prepping for the next release (1.14) where the setting will be `false` by default.
Once 1.14 is released, the next Insiders will have the setting `true` by default.

**Comment by jens1o** [comment]
Yes, I have.

**Comment by Niichie** [comment]
The only way I have been able to get emmet to stop expanding abbreviations with tab is by removing the "tab" hotkey from 
```
{
  "command": "acceptSelectedSuggestion",
  "key": ""
}
```
Which also removes my ability to insert my custom snippets with tab. This is definitely not working as intended.

**Comment by ramya-rao-a** [comment]
Do you see emmet expanded value in the suggestion list before hitting tab?

Pressing `tab` or `enter` when a autocomplete/suggestion list is present, results in accepting the selected suggestion. This is the feature of autocomplete/suggestion list.

In the new emmet model, we show emmet expanded value in the suggestion list and so when you press tab or enter, you get the expanded value.

In the old model, pressing tab in the absence of suggestion list was expanding the abbreviation.
In the new model, pressing tab in the absence of suggestion list should add the indent

**Comment by Niichie** [comment]
The issue is that no matter what I type, it brings up the emmet autocomplete/suggestion list. This is useful when trying to insert tags in HTML, say  `div class=""` or something like `ul>li*3`, but when I'm typing normal words that do not belong to any emmet snippet, there should be no "suggestion." 

for example look at this gif, this behavior is extremely annoying when trying to quickly type something, then tab to the end of a tag.

![emmet](https://user-images.githubusercontent.com/16381287/27995971-cf848e34-64a5-11e7-9d94-7ee34bece202.gif)

for reference, this is the Atom implementation using "emmet simplified" which only inserts emmet snippets when you hit `shift+space`

![emmetinatom](https://user-images.githubusercontent.com/16381287/27996009-7cbf95bc-64a6-11e7-9c16-6b1ca9ffc9d7.gif)

**Comment by ramya-rao-a** [comment]
@Niichie For your concern in https://github.com/Microsoft/vscode/issues/30281#issuecomment-313932069, please see https://github.com/Microsoft/vscode/issues/30265#issuecomment-313932822

Like I said in the linked comment, I completely agree that this is annoying and have proposed a solution. 

The fix for that will be out in the next few days.

Sorry, that emmet is causing you trouble. The new emmet model is still in the works (which is why there is a setting to opt in to it) and I appreciate all the feedback I am getting.

Hopefully for the next release (1.15), this will be completely polished.

Let's use #30265 to track the "emmet expands everything" issue.

If there are no other concerns, then is it ok if we close this issue?

**Comment by Niichie** [comment]
Yes, lets close the issue and use the other thread! Thanks :)

**Comment by ramya-rao-a** [comment]
Great
