### ISSUE TITLE
Go to definition for .jsx does not work

### ISSUE THREAD

**Issue by ilya-git** [Microsoft/vscode#30290]
I am working with es6 syntax in Visual Studio Code and when I import ordinary file, then I can click F12 (Go to definition) and it works just fine. The problem is that with components (import from .jsx files) it does not work at all (nothing happens when you click go to definition). Has anyone an idea how it can be fixed?

P.S. I have jsconfig.json like that to allow proper go to definition for ordinary .js files:

```
{
    "compilerOptions": {
        "target": "ES6"
    },
    "exclude": [
        "node_modules"
    ]
}
```

P.S. Stackoverflow question where it has originated from is [here](https://stackoverflow.com/questions/44754145/go-to-definition-for-jsx-does-not-work).

**Comment by mjbvz** [comment]
First, please try the current insiders build to see if the issue has been fixed: https://code.visualstudio.com/insiders

If you still see the issue, please share some example code so that I can investigate

**Comment by AStaroverov** [comment]
Doesnt work for me too. And i try insider and nothing.
I tried it with the 1,12 version and the bug is still alive.

**Comment by mjbvz** [comment]
Closing as we need more info to investigate this. Please share some example code and some repo steps or a small sample project

**Comment by agwells** [comment]
I was experiencing the same issue. (in VScode 1.16). With some experimentation, I found that it only happened when the component was the default export in a module.

I also found that I could fix the problem by adding `"jsx": "preserve"` to my `jsconfig.json`'s `compilerOptions`.

**Comment by agwells** [comment]
Hm, on further experimentation it seems like it's happening when I try to "go to definition" on an import from a JSX file, whether or not the thing I'm importing is a default or non-default export.

Anyway, here's a small sample project that replicates the issue for me, in VS Code 1.16. I have not yet tried it in the "insiders" build: https://github.com/agwells/vscode-issue-30290

**Comment by mjbvz** [comment]
Thanks for the example project @agwells.

In your case, I believe you just need to add `"jsx": "react"` to your `jsconfig.json`:

```json
{
    "compilerOptions": {
        "target": "esnext",
        "jsx": "react"
    }
}
```

This should make TypeScript understand the jsx in your files.

I tracked this down using [`"checkJs": true`](https://code.visualstudio.com/Docs/languages/javascript#_type-checking-and-quick-fixes-for-javascript-files) which is often a good way to catch configuration problems like this

**Comment by agwells** [comment]
Hi @mjbvz,

Thanks for the reply! What you're describing is the result I found as well. To clarify, it looks like at this point the "bug" is limited to an inconsistency between how VSCode (1.16.0) handles "*.js" files and "*.jsx" files, in a JS project, if you have *not* set `compilerOptions.jsx` in `jsconfig.json`:

1. If you have a JS project that does *not* set `compilerOptions.jsx` in `jsconfig.json`...
2. "Go to definition" *will work* on JSX tags that are imported from a `.js` file.
3. But "Go to definition" *will not work* on JSX tags that are imported from a `.jsx` file.

And, as mentioned, the easy workaround is to add the compilerOption `"jsx": "preserve"` (or `"jsx": "react"` or `"jsx": "react-native"`). So granted, that makes it a fairly minor bug. ;)

I suppose the more substantial issue is that VSCode could use better documentation for what all the settings in `jsconfig.json` do. Since it uses the same schema as `tsconfig.json`, all the tooltips describe what the `compilerOptions` settings do when you're compiling TypeScript into JavaScript. (For example, the tooltip for `compilerOptions.jsx` says "When down-level compiling, specify JSX code generation: 'preserve', 'react', or 'react-native'.") But in a JS project, some of them do nothing, and others act as flags that activate parts of the Intellisense functionality.
