### ISSUE TITLE
Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:5858).

### ISSUE THREAD

**Issue by learnercys** [Microsoft/vscode#30297]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:13:05.928Z)
- OS Version: Darwin x64 16.6.0
- Node Version: v8.1.3

Steps to Reproduce:

1. After Starting Debugging with these configurations:

```
{
    "type": "node",
    "request": "launch",
    "name": "Launch Program",
    "program": "${workspaceRoot}/bin/server.js",
    "port": 5858
}
``` 

The error: `Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:5858).` is displayed.

**Comment by reyou** [comment]
I am having same issue currently.

**Comment by weinand** [comment]
only use "port" for configs with request type "launch" if you want to deal with debug ports yourself (and want to pass the "--debug" argument to node.js explicitly).
If you don't care, just remove the "port" and VS Code will assign a random free port automatically.

**Comment by weinand** [comment]
Actually, I should protect against this kind of error.

**Comment by auchenberg** [comment]
Can we either output a better error message, or use the `port` when launching?

**Comment by weinand** [comment]
We are already honouring the port in this case as the port to attach to.

But at the same time we are using the fact that a port is specified as an indication that the user wants to configure the debug port manually and we do not pass a "--debug=1234" or "--debug-brk=1234" (or --inspect etc.) to the runtime automatically. So the runtime is not in debug mode and attach will fail (this would be a better error message for the user).

I suggest the following:
- if no "runtimeExecutable" and no "runtimeArgs" are specified, we will automatically pass the correct debug flags and use the specified port. This differs from the current behaviour, but I cannot imagine that this breaks any launch config because a "node" not launched with arguments can never be in debug mode.
- if a "runtimeExecutable" and a "port" is specified, we will not pass the debug flags automatically and expect the user to do this (this is the current behaviour)
- if a "port" is specified we improve the error message by mentioning that "maybe the runtime is not in debug mode"

**Comment by auchenberg** [comment]
This sounds good, and would align the behavior of `port` to be the same for `launch` and `attach` which I think is the confusing part here.

**Comment by auchenberg** [comment]
@weinand Do you usually open individual issues for each change (clean commits) or is it sufficient to use this issue in the backlog?

**Comment by weinand** [comment]
@auchenberg Usually we create individual issues for each change.
But I do not really understand what you mean by "or is it sufficient to use this issue in the backlog?"
To use this issue for exactly what?

**Comment by auchenberg** [comment]
@weinand I noticed that you added this issue to the July 2017 milestone, and your comment https://github.com/Microsoft/vscode/issues/30297#issuecomment-315524816, contains two parts "improved error message" and "logic change on when debug flags are passed", so I was wondering if that would be 2x issues for the backlog, or we simply don't want such planning overhead?

**Comment by weinand** [comment]
aha, I understand. No, this issue will cover all changes/commits that are planned here to address the problem.

**Comment by weinand** [comment]
The launch config from above now works with "legacy" node-debug.

In addition I've changed the error notification if a port is specified to this:

![2017-07-20_23-42-52](https://user-images.githubusercontent.com/1898161/28440164-70ef60ac-6da5-11e7-88ee-32ba213dd4a3.png)
