### ISSUE TITLE
Editor can't reload files automatically when i checkout branch

### ISSUE THREAD

**Issue by woolson** [Microsoft/vscode#30372]
- VSCode Version: Version 1.13.1 (1.13.1)
- OS Version: Version 10.12.6 Beta (16G24b)

Steps to Reproduce:

1. use iTerm2 to checkout branch;
2. back to vscode, it still show the files before i checkout branch;
3. i restart vscode, then the sidebar files refreshed.

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
@woolson 
VS Code is using different file watching strategies depending on your OS and your setup. 

**First thing to check:**
* [ ] I verified that the issue still reproduces in our insiders version (https://code.visualstudio.com/insiders/)
* [ ] I verified that this issue is happening outside of a `node_modules` folder. Our file watcher ignores this folder!

**To find out more about this issue, please first answer this:**
* [ ] What OS are you on
* [ ] Does this happen from an empty workspace, a single-folder workspace or a multi-root workspace?
* [ ] Do you have `files.useExperimentalFileWatcher: true` configured in settings?
* [ ] What is your configured `files.watcherExclude` setting?

**Then please answer the following depending on your setup:**
* [ ] It reproduces with any folder or workspace you open
* [ ] The files/folders you open are on your local disk and not on a network share nor a UNC drive
* [ ] The files/folders you open are not behind a symbolic link
* [ ] The folder(s) opened use the exact same casing as they are on disk
* [ ] It reproduces when I make a change to the file from another VS Code window (either from the editor or the file explorer)

**Then please attach the output of our development console**
* run `code --verbose` from the command line
* perform the action that causes you to not see the file change in VS Code
* attach the output from the console (`Help` > `Toggle Developer Tools` > `Console`)

Thanks for taking the time to fill out this questionnaire.
