### ISSUE TITLE
Monokai Dimmed syntax highlighting is different - with less distinctions

### ISSUE THREAD

**Issue by wschaeferiii** [Microsoft/vscode#30428]
With the update today, this syntax highlighting for Monokai Dimmed for javascript (babel) changed pretty drastically, eliminating a lot of distinctions between the text.

Most noticeably, most of text is an ugly white...  which I am used to a light blue (numbers maintain the blue). Template strings have variables still in green, like the rest of the string.  Properties on variables are just white, like the variables, not purple like they used to be.

Keywords are like `class`,` extends` and `new`, are still the same, methods are still orange, booleans are still pink.  It used to be that the keyword `this` was the only white text and now it is red like `global`, `window`, and `Promise`.

Not sure what happened, but I was very used to this theme and now I feel like I am reading something very unnatural.  I hope it is just a bug, and not that this will be the decision to eliminate those distinctions above.

**Comment by mjbvz** [comment]
I tweaked the grammar this last iteration. The changes to `this` are intentional but we may want use the blue color for more variables again

For reference, here's the 1.13 style:

![screen shot 2017-07-11 at 2 37 25 pm](https://user-images.githubusercontent.com/12821956/28091987-b7541e40-6646-11e7-9aa3-f6e46272f0b6.png)

Here's 1.14 which changes `this` and the default property color:

![screen shot 2017-07-11 at 2 37 55 pm](https://user-images.githubusercontent.com/12821956/28092004-c41926c0-6646-11e7-85a3-2a25b1cbee1a.png)

Here's Atom:

![screen shot 2017-07-11 at 2 38 10 pm](https://user-images.githubusercontent.com/12821956/28092028-d80a3296-6646-11e7-8a01-633d70dc816a.png)

----

Here's what VSCode looks like if we restore the blue color for `variable.other`:

![screen shot 2017-07-11 at 2 38 06 pm](https://user-images.githubusercontent.com/12821956/28092144-3ce97a00-6647-11e7-8349-70d37a6d7510.png)

**Comment by Tyriar** [comment]
Verified that the white words after `.` are now light blue.

<img width="653" alt="screen shot 2017-07-13 at 10 38 26 am" src="https://user-images.githubusercontent.com/2193314/28179653-71781fbc-67b7-11e7-9241-ea85a1225c7c.png">

**Comment by Ciantic** [comment]
Is this related? PHP highlighting has been broken since 1.14.0, it's also broken with 1.14.1:

**
![image](https://user-images.githubusercontent.com/64731/28202461-231473bc-687e-11e7-9a15-046f13accaca.png)
**

The tags weren't white before.

**Comment by mattbierner** [comment]
@ciantic That looks like the vs dark theme. Please file a different issue with the screenshot and the source of the code

**Comment by ionut-botizan** [comment]
The PHP class names are not fixed (still white) in Monokai Dimmed... :(
![monokai-dimmed](https://user-images.githubusercontent.com/408501/28256931-7b33bb22-6acf-11e7-96ab-8b9939aaea66.PNG)

**Comment by victor0801x** [comment]
before 1.4.x syntax color (monokai) is correct.
![2017-07-19 09-34-10](https://user-images.githubusercontent.com/4534038/28346820-e63a9638-6c65-11e7-87cb-2c2cf38ed17b.png)
after update 1.4.x, it becomes wired. Change other themes didn't solve this problem either.
![2017-07-19 09-35-23](https://user-images.githubusercontent.com/4534038/28346831-f2d0162a-6c65-11e7-9b99-d28ffe2d5422.png)

**Comment by victor0801x** [comment]
find out how to reproduce this problem (in javascript)
when comment start with `'()'` will cause some syntax parsing error.
![2017-07-19 13-33-59](https://user-images.githubusercontent.com/4534038/28352123-36234890-6c87-11e7-9d50-53b7292ad1e8.png)
![2017-07-19 13-34-18](https://user-images.githubusercontent.com/4534038/28352124-39417d94-6c87-11e7-9197-29952f02558f.png)

**Comment by mjbvz** [comment]
@victor0801x This is unrelated to the Monokai dimmed theme. The issue should be fixed in VSCode insiders builds already

**Comment by victor0801x** [comment]
@mjbvz Thanks for reply. My apologia for post here.
