### ISSUE TITLE
Terminal: No re-layout, some truncation on panel resize

### ISSUE THREAD

**Issue by cleidigh** [Microsoft/vscode#30430]
- VSCode Version:  1.14.0
- OS Version: <code>Windows_NT x64 6.1.7601</code>

Problem:

The integrated terminal does not re-layout when views change
such as adding the sidebar. The wrapped  output will stay wrapped
or get truncated.

Steps to reproduce:

- open code with no terminal
- display the sidebar
- start an integrated terminal
- size the terminals to force some wrapping
- generate output with some longer lines
- force the terminal panel to expand by hiding the sidebar
- panel expands but terminal does not re-layout

![terminal wrapping](https://user-images.githubusercontent.com/25272315/28092601-05501aca-6662-11e7-85db-e3b1c109718a.png)

**Comment by Tyriar** [comment]
The terminal doesn't relayout on Windows as a consequence of the backing library and how it works https://github.com/rprichard/winpty

winpty does not attempt to track wrapped lines or reflow them, probably because it's already complicated enough attempting to get the Windows console APIs to work like the Unix pty API.

There is a related issue https://github.com/sourcelair/xterm.js/issues/622 which will improve the case where you get some output, resize smaller and then resize larger. This should improve on all operating systems.
