### ISSUE TITLE
Make the scroll beyond last line show to two lines of code at the top, not one

### ISSUE THREAD

**Issue by hilja** [microsoft/vscode#30499]
I had this at the other day:

Prerequisites: Uses an empty line feed at every file.

1. Looks at an empty file in awe, why it's empty...
2. Restarts Code, because that always helps to everything.
3. Still empty file.
4. Checks GitHub, yep the file is there.
5. Comes back to Code and _scrolls up_, the file was there, I just didn't see it because of the empty line at the end.
6. Does a facepalm and realises why Atom shows two lines when scrolling beyond last line: because of the line feed.

**Comment by Adondriel** [comment]
I can see why this is an issue, but I also think it's kind of a small one, for me in this example: 
![image](https://user-images.githubusercontent.com/1113496/28132535-1b6ee256-670b-11e7-9616-ab9772370f12.png)
When I scroll down, the title bar gains a nice little shadow, that makes it very apparent that I have a line above it. Could this be due to your theme?

**Comment by hilja** [comment]
It's totally a minute corner case :) I use the default Light theme.

![screenshot 2017-07-13 10 03 13](https://user-images.githubusercontent.com/2558021/28156334-91fcecfe-67b2-11e7-830f-c8f860234bad.png)

**Comment by Adondriel** [comment]
The issue then becomes: "Well, what if someone puts TWO lines of whitespace at the bottom of their file, then scrolls down?" The same issue would appear, and you'd have an exponential case of the issue you mentioned above. I'm also playing devil's advocate here. Also, I feel like you should have seen the "line # 37" and thought, oh hey, let's scroll up, cause it's line 37... I feel like, there are some cases where we DO need to force the user to think a little bit. lol

**Comment by rebornix** [comment]
I don't think making it two can solve this problem, an empty line or two or three make no difference. There are several ways to mitigate it

* Disable scroll beyond last line. In this case you'll never run into that problem, but you may not like it.
* Customize current line highlight for you theme. Say you are using Default Light theme, changing current line highlight to 
    ```
    "workbench.colorCustomizations": {
      "editor.lineHighlightBackground": "#dddddd"
    },
    ```
   can make it pretty obvious.
* Lastly, what if the last line is not selected? Then I'll suggest to customize the gutter color to make it easier to see
    ```
    "workbench.colorCustomizations": {
      "editorGutter.background": ""
    },
    ```

I played with Atom as well and sometimes it shows 2 lines while sometimes it displays 3, whether there are 0/1/2/more empty lines at the end of the document, I can't figure out what's their logic.

A good solution to this problem is adding an option that scrolling beyond last non-empty line and always make sure the last non-empty line is visible, similar to how we handle `scrollBeyondLastLine`. I'd like to hear more voice on this, if it's a highly-wanted one then let's add it. Before that I'd like to keep current behavior without making users confused with several options. Close it first and reopen whenever it's necessary.

**Comment by Adondriel** [comment]
I don't think this is needed, to be honest, because if I understand you right, we already have an option for "scrollBeyondLastLine"? So, why would we need to add something on top of that?

**Comment by justinpawela** [comment]
In it's current state (a boolean setting with just one line of over-scroll), the feature makes little sense. Every text file (POSIX, at least) is supposed to end with a new line, so if you scroll all the way down, you always end with one blank line at the top of the screen. At the very least it would be nice if there were 2-3 lines showing so it was more visually obvious.

**Comment by MasonBergstrom** [comment]
It should be a variable like Scroll Beyond Last Column is an int. I'd prefer when I scroll all the way to the bottom it actually puts the last line about half way down my screen, at the moment it's either the top or bottom, no in between.
