### ISSUE TITLE
Support tilde character (~) in Razor links

### ISSUE THREAD

**Issue by rhires** [Microsoft/vscode#305]
Code does translate correctly the tilde ~ as a proper path reference when the code runs (but that may be mono or core-clr doing that magic, or roslyn), but when I cmd-click the link, Code offers to create a new folder in the path that literally includes the tilde as the folder name in that path, when it should convert it to the proper path of wwwroot...this is in the _Layout.cshtml file. I'm unsure where to look in the code so I can see what it's doing to offer a fix.

**Comment by alexandrudima** [comment]
@rhires Are you `Ctrl+Clicking` on a "detected link" inside an HTML block?

Something like:

```html
<a href="~/some/path/to/something.txt">
```

**Comment by rhires** [comment]
Yes, for example this item in _Layout.cshtml: `<link rel="stylesheet" href="~/css/bootstrap.css" />` - even though it's properly found when I run the app (`dnx web` from the command line in Mac OS X) when I cmd-click, I get an offer to create the file with the tilde in it: `File not found ([$PATH-to-project-root/Views/Shared/~/css/bootstrap.css)` If I create the file, then I have a new folder called `~` with the rest of the path in it below.

**Comment by alexandrudima** [comment]
Ok, I think I understand. In your `_Layout.cshtml` you use:

```html
<link rel="stylesheet" href="~/css/bootstrap.css" />
```

`~` is something Razor understands and resolves it at runtime to an actual path (possibly something that is configurable). Probably in this case at runtime it will be:

```html
<link rel="stylesheet" href="/css/bootstrap.css" />
```

When you `Ctrl+click` on the detected link, VSCode wants to open the file but VSCode fails to understand the special meaning of `~`.

**Comment by aeschli** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.
If you disagree and feel that this issue is crucial: We're happy to listen and to reconsider.
Maybe you want to give it a try yourself and provide the feature through an extension or a PR: We're happy to give advise and get you started.
Thanks for your understanding. Thanks for helping and happy coding!

**Comment by aeschli** [comment]
I added code to detect the '~' and remove it. So the URL will resolve to the current workspace folder. That's IMO the best we can do as we don't know the Razor application root.
