### ISSUE TITLE
Auto indent doesn't indent properly with tab/space

### ISSUE THREAD

**Issue by tmhrtwg** [microsoft/vscode#30509]
- VSCode Version: Code 1.14.0 (b8cd5b9556d8b70ea560d35b903422363f6c5c40, 2017-07-10T18:24:22.120Z)
- OS Version: Darwin x64 16.6.0
---

I've found a bug with the new auto indent feature while using nested scss maps.

Steps to Reproduce:
1. Get a nested map inside a file with scss syntax.
2. Move a line down with your keyboard and see the following effect:
![vscode-autoindent-scssmap](https://user-images.githubusercontent.com/3918317/28118335-e3f2209e-6710-11e7-9923-a73ae28b1c20.gif)

Above you'll see mixed tabs and spaces appear, but setting the file to only use spaces doesn't solve the problem.

Reproduces without extensions: Yes

Hope this helps!

edit: added the example code so you can to try yourself:
```
$scss-config-map: (
    columns: 12,
    fluid: true,
    font-sizes: (
        B:  100%,
        M:  1.5rem,
        L:  3rem
    ),
    gutter: 20px,
    layouts: (
        S:  370px,
        M:  610px,
        L:  850px,
        XL: 1090px
    ),
    max-width: 1330px,
    min-width: 320px
);
```

**Comment by rebornix** [comment]
This happens when

* `editor.insertSpaces` is set to `false`
* and most importantly `editor.detectIndentation` is set to `false`

either in the workspace setting or user setting.

With this two settings, it means VS Code editor should always use tabs whenever possible, which includes Moving Lines (which will adjust the indentation of moving lines). You can disable the auto indent feature by setting `editor.autoIndent` to `advanced`.
