### ISSUE TITLE
Cannot search for non-ASCII text in non-UTF-8 coded project files

### ISSUE THREAD

**Issue by dial8gue** [Microsoft/vscode#30583]
- VSCode Version: Code 1.14.0 (b8cd5b9556d8b70ea560d35b903422363f6c5c40, 2017-07-10T18:36:31.751Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|don|0.6.7
---

Steps to Reproduce:

1. Create text file in project folder with Windows-1251 encoding.
2. Fill out text file with sample content (russian+english): "тест test тест".
3. Save and close text file.
4. Invoke search in project (CTRL+Shift+F) with search string "тест".
5. **Nothing found**.
6. Invoke search in project (CTRL+Shift+F) with search string "test".
7. Text found, strange symbols in preview: [link](https://i.imgur.com/YwlaYw5.png)

Reproduces without extensions: Yes

**Comment by roblourens** [comment]
Did you set the `"files.encoding"` setting? This is necessary for searching other encodings, since the tool we use for search doesn't support encoding autodetection.

**Comment by dial8gue** [comment]
Yes, with "files.encoding": "windows1251" I can search in windows1251 and utf8 files.
But project contains files with different character sets, and now, when I try to open utf8 file, it opens with windows1251 encoding, even with "files.autoGuessEncoding": true

**Comment by roblourens** [comment]
@bpasero it seems that `files.encoding` takes precedence over `files.autoGuessEncoding`. I think it would make sense for `files.encoding` to be a fallback when the encoding can't be autoguessed, if that ever happens. It would also make this scenario easier, when a user wants to manipulate `files.encoding` for searching, while still using `autoGuessEncoding` in the editor. What do you think?

**Comment by bpasero** [comment]
@roblourens sounds good in theory, however I think the encoding detection does not really tell you if it could detect an encoding or not. In other words, I think you will most often get an encoding "auto detected" even though it might not be the right one. 

I wonder if for search we should not do the auto detection of encoding? Since it has lots of issues with wrongly detected encodings (see https://github.com/aadsm/jschardet/issues) maybe we should stay away from having it for search where basically each and every file's encoding is detected.

How is this setting supported with ripgrep anyways? I would assume that we can only detect the encoding if we are the ones doing the search, but not when going through ripgrep?

**Comment by roblourens** [comment]
It's not supported at all for ripgrep, you have to tell it which encoding to search with, and it uses that encoding to interpret every file.

It looks like jschardet can return null? https://github.com/Microsoft/vscode/blob/master/src/vs/base/node/encoding.ts#L115 (but maybe it usually returns one anyway)

**Comment by bpasero** [comment]
@roblourens ok then maybe I did not understand your comment https://github.com/Microsoft/vscode/issues/30583#issuecomment-315404980 fully, can you maybe explain what you mean? 

In https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/files/node/fileService.ts#L614 you see that if the encoding is null we fallback to the configured encoding. So I would assume that we already do the fallback, at least if the guessing returns null.

As I said, I think in most cases JSChardet will actually return something.

**Comment by roblourens** [comment]
I was trying the test that @dial8gue described, setting `autoGuessEncoding` and setting `files.encoding` to something. When I do that I open a typical UTF8 file and see that the encoding is set to the `files.encoding` value.

Debugging it, I see that it does detect 'ascii' or 'utf-8' but those detected encodings are ignored - https://github.com/microsoft/vscode/blob/master/src/vs/base/node/encoding.ts#L122 - so in that case it uses `files.encoding` instead. I guess this is by design then, but can you explain why it ignores those detected encodings?
