### ISSUE TITLE
onCommand activation does not work as expected for debugging command

### ISSUE THREAD

**Issue by wiktork** [Microsoft/vscode#3059]
When activating an extension using onCommand activation, the activation is not triggered when using the mouse or the command palette.

Repro (vscode 0.10.8)

1. Create an extension (mine was initially created with yo code generator). Add the following activation:
`"activationEvents": [
    "onCommand:workbench.action.debug.start"
  ],`
2. Start a debug session (e.g. using mock debugger). When starting the debug session, click the play button or run Debug:Start from the command palette.

The extension is not activated as expected. Note that pressing F5 will activate the extension.

**Comment by egamma** [comment]
@isidorn looks there are three commands to launch (F5, 'play' in the toolbar, Debug:start). It is fair to expect that they are all using the same command underneath.

**Comment by isidorn** [comment]
After discussing with @alexandrudima this issue happens because our actions can get exectued without a notion of a command. This usually happens through the UI and this does not have anything to do with debug, it is a general flaw in our action / command concept.

We will look into improving this in one of the debt weeks, which will requre refactoring all our actions to always be run through a command.

**Comment by egamma** [comment]
Assigning the April for investigation.

**Comment by isidorn** [comment]
Now when debug starts we are sending an activation event 'onDebug:${type}', e.g 'onDebug:node'
