### ISSUE TITLE
Debugging nodemon with the internalConsole causing exception

### ISSUE THREAD

**Issue by carlcheel** [Microsoft/vscode#30590]
- VSCode Version: 1.14.0 (This was fine in the previous version)
- OS Version: Ubuntu 14.04
- Node Version: v4.4.4

Steps to Reproduce:

1.  Run nodemon with the following configuration:
```js
{
            "protocol": "legacy",
            "type": "node",
            "request": "launch",
            "name": "Server (Nodemon)",
            "runtimeExecutable": "nodemon",
            "runtimeArgs": [
            ],
            "program": "${workspaceRoot}/app.js",
            "restart": true,
            "console": "internalConsole"
},
```
2. Make a change to a file and hit save.
3. Exception thrown.

Exception has occurred: Error
Error: write EPIPE
    at exports._errnoException (util.js:870:11)
    at WriteWrap.afterWrite (net.js:769:14)

**Comment by weinand** [comment]
@carlcheel does it make a difference if you remove the "runtimeArgs" from your launch config and set "console" to "integratedTerminal"?

**Comment by carlcheel** [comment]
@weinand - Thanks for the quick response.

integratedTerminal works fine. However, I have a compound configuration that already runs something in the integratedTerminal so I can't run both. Is it possible to run in 2 different integrated terminals?

As a workaround, I'm running it in an externalTerminal, however, this was working flawlessly in a previous release.

**Comment by weinand** [comment]
I suspect that "nodemon" has problems reading from the "internalConsole" because reading input is not supported from it. But I'm not aware of any changes in that area in VS Code 1.14.0.

I'll try to reproduce on linux (with the rather old version of node 4.4.4...)

In the meantime I suggest to use the "integratedTerminal". We recommend that anyway because only there you can kill nodemon by "Control-C". Killing nodemon in the "internalConsole" doesn't work. See https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_restarting-debug-sessions-automatically-when-source-is-edited

And for the other launchconfig use either "internalConsole" or "externalTerminal" so that you have no conflicts if running the launch configs as a "compound".

**Comment by carlcheel** [comment]
It's still working for a friend, I'll get the version of VS Code they're using at the next opportunity (they haven't upgraded yet).

**Comment by carlcheel** [comment]
@weinand it works fine in code_1.12.2-1494422229_amd64.

**Comment by lerit** [comment]
i face same problem，integratedTerminal work fine

**Comment by weinand** [comment]
nodemon should be used in the integrated terminal as it tries to read input (which is not supported in the debug console).
