### ISSUE TITLE
Dirty indicator is lost when changing tabs

### ISSUE THREAD

**Issue by dsreynolds** [Microsoft/vscode#30627]
- VSCode Version: 1.14
- OS Version: Windows 10

Steps to Reproduce:

1. open two files in the editor
2. make a change to one file and note the dirty indicator in the tab is visually displayed.
3. click on other file tab.
4. click back on original tab and note that dirty indicator is no longer displayed (even though the file is still dirty).

**Comment by bpasero** [comment]
@dsreynolds could it be that you have auto save enabled?

I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.
