### ISSUE TITLE
New directory isn't visible from explorer view

### ISSUE THREAD

**Issue by SpikedPunchVictim** [Microsoft/vscode#30650]
Added a directory in Finder, which is visible in Finder, but is not visible in VS Code's project/explorer view. Refreshing, closing and opening VS Code seems to have no affect.

If it makes any difference, I'm working on code under a Perforce stream, with the Perforce plugin.

- VSCode Version: Code 1.14.0 (b8cd5b9556d8b70ea560d35b903422363f6c5c40, 2017-07-10T18:24:22.120Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
unity-debug|Uni|1.2.1
python|don|0.6.7
csharp|ms-|1.11.0
vetur|oct|0.9.1
perforce|sle|2.1.1
addDocComments|ste|0.0.8

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by SpikedPunchVictim** [comment]
Running VS Code with plugins disabled doesn't fix the issue. The directory still does not show up. If it helps, the name of the directory is `Build`. Let me know if you need any other info.

**Comment by bpasero** [comment]
@SpikedPunchVictim could it be that you have a `files.exclude` setting that is configured to hide this folder?

**Comment by SpikedPunchVictim** [comment]
That was it! Thank you for your time.
