### ISSUE TITLE
Duplicate stack frame in debug view

### ISSUE THREAD

**Issue by testforstephen** [Microsoft/vscode#30660]
- VSCode Version: VSCode 1.14.0
- OS Version: Windows 10

We're developing debugger for java language. And observe duplicate top stack frame on DA.
![image](https://user-images.githubusercontent.com/14052197/28195108-e49a152c-687a-11e7-8523-25e241449031.png)

i saw the tips from another bug ##28808 and enable supportsDelayedStackTraceLoading to be true, but still got duplicate top frame.

Here are the DA requests and responses:
[Event Response] - breakpoint hit
{"event":"stopped","body":{"threadId":1,"reason":"breakpoint","source":{"name":"HelloWorld.java","path":"d:\\Work\\CodeJava\\workspace_codejavadebug\\HelloWorld/HelloWorld.java","sourceReference":0},"line":20,"column":0,"text":"","allThreadsStopped":false,"type":"stopped"},"seq":27,"type":"event"}

[Request]
{"command":"threads","type":"request","seq":23}
[Response]
{"success":true,"request_seq":23,"command":"threads","body":{"threads":[{"id":2,"name":"Attach Listener"},{"id":3,"name":"Signal Dispatcher"},{"id":4,"name":"Finalizer"},{"id":5,"name":"Reference Handler"},{"id":1,"name":"main"}]},"running":false,"seq":28,"type":"response"}

[Request]
{"command":"stackTrace","arguments":{"threadId":1,"startFrame":0,"levels":1},"type":"request","seq":24}
[Response]
{"success":true,"request_seq":24,"command":"stackTrace","body":{"stackFrames":[{"id":4,"source":{"name":"HelloWorld.java","path":"d:\\Work\\CodeJava\\workspace_codejavadebug\\HelloWorld\\HelloWorld.java","sourceReference":0},"line":20,"column":0,"name":"onChange"}],"totalFrames":1},"running":false,"seq":29,"type":"response"}

[Request]
{"command":"stackTrace","arguments":{"threadId":1,"startFrame":0,"levels":20},"type":"request","seq":25}
[Response]
{"success":true,"request_seq":25,"command":"stackTrace","body":{"stackFrames":[{"id":5,"source":{"name":"HelloWorld.java","path":"d:\\Work\\CodeJava\\workspace_codejavadebug\\HelloWorld\\HelloWorld.java","sourceReference":0},"line":20,"column":0,"name":"onChange"},{"id":6,"source":{"name":"HelloWorld.java","path":"d:\\Work\\CodeJava\\workspace_codejavadebug\\HelloWorld\\HelloWorld.java","sourceReference":0},"line":15,"column":0,"name":"main"}],"totalFrames":2},"running":false,"seq":30,"type":"response"}

[Request]
{"command":"stackTrace","arguments":{"threadId":1,"startFrame":3,"levels":19},"type":"request","seq":27}
[Response]
{"success":true,"request_seq":27,"command":"stackTrace","body":{"stackFrames":[],"totalFrames":0},"running":false,"seq":32,"type":"response"}

**Comment by weinand** [comment]
@isidorn the second "stackTrace" request still asks for 20 frames starting at 0. That looks wrong to me.

**Comment by isidorn** [comment]
@testforstephen can you also reproduce if you just use a single thread?

This might be a timing issue, july to investigate

**Comment by testforstephen** [comment]
@isidorn The five threads in call stack are JVM default threads, it seems i cannot control them.

**Comment by weinand** [comment]
@isidorn instead of just adding frames blindly to the stack (which can result in duplicates), could you do the following:
- if you request frames you know the exact index of every frame when it arrives. Use that index to set (or replace) the frame in the stack. This should solve the duplicate frame issue in any case.
- if you think that frames arrive late and they no longer apply to the stack (because there was already another stop event), introduce a "generation ID".

How to use a "generation ID":
- remember the ID for the stack and use the same ID for all requests that you perform for that stack.
- create a new ID whenever the stack got invalidated e.g. because of stepping
- if you receive frames, always compare their generation ID with the current generation ID of the stack. If they don't match, drop the frames.

**Comment by isidorn** [comment]
@weinand good ideas, for start I will use the indexes and not blindly append
