### ISSUE TITLE
Explicit "Check for update" from top menu should still show message

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#30676]
I find this flow a bit weird (Windows):
* explicitly ask for updates from the help menu
* updates are available, so the little badge shows up in the lower left corner

As a user I would expect an explicit message to show up. I suggest showing a modal dialog (not our message service) that simply asks to apply the update. It is very likely that I want the update when I explicitly checked for it. I am also fine using a modal dialog to indicate no updates are available, since I asked for it.

**Comment by isidorn** [comment]
When updates are available we could only show a message "update availble" since the actionable thing to apply the update would only come after the update is download some time later.
I think this defeats the purpose of having this experience smooth.

As for the case when no updates are availble that is fixed now and works fine.

Closing as I think no action should be done here.
@joaomoreno @bpasero feel free to reopen
