### ISSUE TITLE
Support external diff algorithms in internal diff editor

### ISSUE THREAD

**Issue by myfairsyer** [Microsoft/vscode#30694]
While #15661 asks for the ability to launch external diff programs in _their own user interface_ I'd rather like VSCode to parse the patch formatted output of another (probably mainly cli?) diff tool and **show the results  in the regular built-in diff editor**

In #15661 @joaomoreno suggested writing an **extension** but I suppose this here would not be possible with an extension, right?

Just like in #15661 one of the use cases I have in mind is using **[git's built in diff algorithms](https://git-scm.com/docs/git-diff#git-diff---diff-algorithmpatienceminimalhistogrammyers)**. For that use case I'd also love to see an option that respects what is being set in **git's settings** (although I guess _this_ should be possible to be managed in an **extension** when the base functionality of using external diff algorithms in the internal diff editor is implemented, right?)

**Comment by alexandrudima** [comment]
Since last year, we have enhanced our diff algorithm with git's whitespace heuristic that brings diff hunks together (reduces their count in many cases) and have added another heuristic for comparisons when ignore trim whitespace is off. I think we should focus on doing additional improvements in our diff algorithm rather than integrating an external diff tool that at the end of the day also contains a diff algorithm...
