### ISSUE TITLE
Better support "Add Folder to Workspace" when not in workspace context

### ISSUE THREAD

**Issue by michelkaporin** [Microsoft/vscode#30708]
OS: Windows
![workspace](https://user-images.githubusercontent.com/2239563/28214415-6f56fc6e-68aa-11e7-8531-22009dd31c05.gif)

When adding second folder (1 to 2 scenario), I am moving to a new workspace without initial folder preserved.

**Comment by bpasero** [comment]
Yeah, this transition is not nice. There is a couple of things to consider:
* should this action be enabled/disabled when not in workspace context
* should we ask the user to migrate settings, state, etc. from the current workspace
* should we avoid a window reload so that the transition is smooth

/cc @sandy081

**Comment by michelkaporin** [comment]
@bpasero agree, but the key point I was raising is that I don't have my initial opened folder in a newly created workspace, which surprised me, when I tried to add folder to a to-be-created workspace.

**Comment by sandy081** [comment]
@michelkaporin I see your point. When you are adding folder to Single Folder Workspace we redirect to new workspace case with an explicit dialog. 

I think it makes sense to auto add the existing root folder to the list. And also mentioning it in the dialog.

w.r.to smooth transition, it is our eventual goal. When we overcome our technical challenge we will get into smooth transition. This will come soon.
