### ISSUE TITLE
When a line is wrapped selecting the whole line just selects the first line of the wrapped ones

### ISSUE THREAD

**Issue by dareenzo** [Microsoft/vscode#30757]
When a line is wrapped selecting the whole line just selects the first line of the wrapped ones

- VSCode Version: 1.14.1 
- OS Version: macOS Sierra 10.12.5

Steps to Reproduce:

1. have a long line of text 
2. resize editor so text can wrap
3. try selecting the text of the whole line by pressing cmd + shift + right arrow
4. notice that only the first line of the long wrapped line was selected

Reproduces without extensions: Yes

Supporting images bellow:

<img width="1195" alt="screen shot 2017-07-15 at 12 08 46" src="https://user-images.githubusercontent.com/6130991/28238540-874e635a-6956-11e7-88aa-b24961d3b996.png">
<img width="619" alt="screen shot 2017-07-15 at 12 09 25" src="https://user-images.githubusercontent.com/6130991/28238541-878a6166-6956-11e7-8a1e-be3ea0ef71ac.png">

**Comment by rebornix** [comment]
related https://github.com/Microsoft/vscode/issues/1424

**Comment by alexandrudima** [comment]
Since quite a while, the behaviour of cmd+shift+right is:
* on first press, it goes to the end of the view line
* on second press, it goes to the end of the model line.

This is consistent with other code editors.

![kapture 2017-10-24 at 15 24 29](https://user-images.githubusercontent.com/5047891/31945441-77ddb402-b8cf-11e7-9e4b-363e152c844c.gif)
