### ISSUE TITLE
Different icon for main/project folders

### ISSUE THREAD

**Issue by r03** [Microsoft/vscode#30798]
It would be nice if I could assign a different icon for some folders. 

For example in a .net solution I would like to give the project folders a different icon. 

Maybe this could be a setting where I could give a list of names per folder set.

**Comment by aeschli** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.
If you disagree and feel that this issue is crucial: We're happy to listen and to reconsider.
Maybe you want to give it a try yourself and provide the feature through an extension or a PR: We're happy to give advise and get you started.
Thanks for your understanding. Thanks for helping and happy coding!
