### ISSUE TITLE
Quick suggestions aren't triggered inside words

### ISSUE THREAD

**Issue by imoby** [Microsoft/vscode#30811]
- VSCode Version: Code 1.14.1 (2648980a697a4c8fb5777dcfb2ab110cec8a2f58, 2017-07-13T19:08:57.197Z)
- OS Version: Darwin x64 15.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
dart-code|Dan|2.1.0
vsc-material-theme|Equ|1.0.0
beautify|Hoo|1.1.1
output-colorizer|IBM|0.1.2
vscode-simple-icons|Lau|1.4.1
vscode-docker|Pet|0.0.16
code-settings-sync|Sha|2.8.2
jsx|Twe|0.0.1
lorem-ipsum|Tyr|1.0.0
project-manager|ale|0.18.1
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.2.11
githistory|don|0.2.1
vscode-babel-coloring|dza|0.0.4
vscode-html-css|ecm|0.1.7
file-icons|fil|1.0.4
flow-for-vscode|flo|0.7.1
auto-close-tag|for|0.4.3
react-jest-vscode-snippets|jal|0.0.3
easy-icons|jam|0.3.1
fuzzy-definitions|jri|0.0.3
vscode-icon-theme|jtl|1.5.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
prettify-json|moh|0.0.3
js-atom-grammar|ms-|0.1.13
vscode-icons|rob|7.10.1
incremental-search|sie|0.2.1
guides|spy|0.8.4
ayu|tea|0.4.0
vim|vsc|0.9.0
JavaScriptSnippets|xab|1.4.1
ReactSnippets|xab|1.4.0

(4 theme extensions excluded)
---

Steps to Reproduce:

1. Go to settings
2. Start new line to add new settings manually in user settings
3. Verify autocomplete is visible during initial typing
4. Hit backspace and continue typing
5. Observe autocomplete no longer shows

![issue](https://user-images.githubusercontent.com/6380855/28249297-8e8d5d5c-6a18-11e7-8b89-ee42966695a0.gif)

Reproduces without extensions: Yes

**Comment by sandy081** [comment]
@aeschli This is happening in all json files.

**Comment by aeschli** [comment]
`LineContext.shouldAutoTrigger` that decides whether to show the content assist while typing. Because `"` is already on the line, code assist seems to think we are in the middle of a word and will not trigger 24x7 IntelliSense.

**Comment by jrieken** [comment]
Yeah, the rules are that we don't automatically trigger suggestions when typing *inside* a word but only when typing at the *end* of a word. The problem is that JSON thinks quotes are part of a word

**Comment by jrieken** [comment]
After checking with other editors I decided to not enable 24x7 IntelliSense when typing *inside* words, but keep the existing behaviour which I believe is very natural but looks bad because of the bogus word definition JSON uses.

**Comment by aeschli** [comment]
The JSON word regex contains the `"` is because IntelliSense uses it to evaluate the start offset of the token to complete. 
Changing it would break contributed IntelliSense providers that don't use text edits but rely on the current behavior where we complete JSON tokens, not some random substring inside a string literal.

Note that if we were to change the word regex to not include `"` and any other separator like `.`, 7x24 would pop up at the following locations: `|"|workbench|.colorTheme|"|`. Also not very intuitive, especially as we are going to completing/replacing the full `"workbench.colorTheme"` token, not just a string inside.

So don't blame the word regex here. If the rule is that we don't show 7x24 if we are inside the token to complete, so be it.

But nevertheless I'd also like to tackle the word regex issue:
IMO we refine our usages of the 'word regexp' as it is used in too many conflicting contexts.
Maybe we can add an additional 'token regex' that corresponds to the scanner tokens. Or allow languages to define regexes for each usage: e.g. code completion regex that is used for the start replace offset, a 7x24 regex used to decide where 7x24 is activated.

**Comment by jrieken** [comment]
> any other separator like ., 7x24 would pop up at the following locations: |"|workbench|.colorTheme|"|. Also not very intuitive, especially as we are going to completing/replacing the full "workbench.colorTheme" token, not just a string inside.

No, once IntelliSense is active 24x7 IntelliSense doesn't do anything. 

> Changing it would break contributed IntelliSense providers that don't use text edits but rely on the current behavior where we complete JSON tokens, not some random substring inside a string literal.

I'd say those contribution use the JSON syntax tree anyways and admitting that there might be some adoption work it's a lame argument to say "all are doing it wrong, let's keep it that way"

**Comment by aeschli** [comment]
Sorry, I disagree:
- they don't have the JSON syntax tree anyway. That requires using a library such as jsonc_parser. 
- they don't do it wrong. They typically want to complete JSON tokens, keys and values, and not random words inside a string literal. So I think their expectation is right that we start replacing at the beginning of the token.

> No, once IntelliSense is active 24x7 IntelliSense doesn't do `anything.`

Well, but if there's no IntelliSense active, typing before the `.` of "workbench.colorTheme" would open intellisense. Typing after the do would not.

**Comment by jrieken** [comment]
> they don't have the JSON syntax tree anyway. That requires using a library such as jsonc_parser.

I think we aren't talking about the same thing: https://github.com/Microsoft/vscode/blob/master/extensions/configuration-editing/src/extension.ts#L9

> Well, but if there's no IntelliSense active, typing before the . of "workbench.colorTheme" would open intellisense. Typing after the do would not.

Please explain why? You type `"` -> nothing happens because it isn't a word char, you type `w` -> suggestions are triggered because a word as started. That's how it works for other languages, e.g. TypeScript has IntelliSense in string literals and somehow they can do this without bending their word definition.
