### ISSUE TITLE
Word Wrap not working

### ISSUE THREAD

**Issue by mickeydelo** [Microsoft/vscode#30892]
- VSCode Version: Code 1.14.1 (2648980a697a4c8fb5777dcfb2ab110cec8a2f58, 2017-07-13T19:08:57.197Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.16
csharp|ms-|1.11.0
mono-debug|ms-|0.15.6
code-spell-checker|str|1.3.0

---

Steps to Reproduce:

1. Install latest version of code
2. Toggle Word Wrap

Reproduces without extensions: Yes/No

**Comment by femot** [comment]
The `editor.wordWrap` setting used to be a boolean - it now is a string.  
I still hat `"editor.wordWrap": true` in my `settings.json` and this broke the ability to toggle word wrap with `alt-z` for me.

- VSCode Version: 1.14.1
- OS Version: Windows 10 

Steps to Reproduce:
1. Add `"editor.wordWrap": true` to `settings.json` and save
2. Try to toggle word wrap with `alt-z` or `View->Toggle Word Wrap`
3. Doesn't work
4. Remove the line, or set it to one of the accepted string values
5. Works again

Reproduces without extensions: Yes

Expected Behaviour:
- Ignore setting
- Automatic conversion of setting from bool to equivalent string value when updating

**Comment by rebornix** [comment]
@femot thanks for your investigation, you made my day :)
