### ISSUE TITLE
TreeDataProvider: expanded nodes under a collapsed node don't work

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#30918]
from the getChildren method of a TreeDataProvider return an "expanded" root with "collapsed" children. Under those "collapsed" children return "expanded" nodes with children.

In the displayed tree view open a "collapsed" node.
Observe: the children under that collapsed node are shown expanded, but they have no children. If you collapse and then reopen them, the children appear.

![2017-07-18_11-50-35](https://user-images.githubusercontent.com/1898161/28311271-6acf1ac0-6baf-11e7-827e-adee4c0ef04e.gif)

**Comment by sandy081** [comment]
@joaomoreno This is the bug we were debugging today

**Comment by joaomoreno** [comment]
The `shouldAutoexpand` feature is badly implemented. cc @roblourens  https://github.com/Microsoft/vscode/commit/5b6dfc0293aaafd998cf5f70670385d5433b7154

**Comment by joaomoreno** [comment]
@sandy081 If you pull this off, I recommend removing that bad feature from the tree.

**Comment by sandy081** [comment]
After discussing with @joaomoreno, we want to revisit how we want to support this feature in tree or outside tree. So moving this to next milestone.

**Comment by roblourens** [comment]
Let me know if you want to talk about it. Doing it inside the tree was a big perf win vs adding the collapsed nodes then expanding them one by one. There's probably a better way to design the API.

**Comment by sandy081** [comment]
@joaomoreno What is the right thing todo here? Shall I wait for the fix to be done in the Tree?

**Comment by joaomoreno** [comment]
@roblourens How was it a big perf win?

**Comment by roblourens** [comment]
IIRC, because we rerender the tree for every modification. So we would add some nodes, redraw the tree, expand node 1, redraw the tree, expand node 2, redraw the tree, etc. I wanted to say, the datasource has these nodes, and when they are new they are already expanded. Maybe a better way is to let someone explicitly batch operations from outside the tree.

Ideally only the search tree is opted into this feature, and it wouldn't affect anything else. If that's not true then there's probably just a bug in the implementation.

**Comment by joaomoreno** [comment]
Makes sense. The search viewlet is definitely a use case which hits this performance problem.

My beef with this API method is that it is definitely in the wrong place and it is not clear what it is doing.

The data provider provides data. `shouldAutoexpand` is now a method of it, yet it seems to provide view state, something which is conventionally be done via methods on the tree instance and not via the provider pattern. A new `IViewStateProvider` would make more sense, it would affect nodes' view states.

Also, what does does it really mean? Does it only affect a node which just appeared for the first time in the tree? Does it affect it every time the node appears due to the expansion of its parent?

**Comment by sandy081** [comment]
It will be simple and easier to understand if it is for latter purpose: `affect it every time the node appears due to the expansion of its parent`

**Comment by roblourens** [comment]
I agree with your points, should I work on that?

Having a way to batch multiple expand operations on the tree would give more flexibility and avoid keeping this very specific API, but I think we'd end up with one extra render, since we would add the items, render the tree, then expand all the items and render again.

**Comment by sandy081** [comment]
@roblourens Tree exposes an API to expand/collapse several elements. This looks to me a batch operation?

**Comment by sandy081** [comment]
May be this can be improved to support batching

**Comment by sandy081** [comment]
@joaomoreno @roblourens May I know what is the update on this? Getting more dups for this bug 😞

**Comment by joaomoreno** [comment]
No progress from my side. Since I'm working on that new tree, expansion state will be supported on `getChildren`, so it will be eventually fixed if you move to it.

For the current fix, I don't mind a hacky solution.

**Comment by eamodio** [comment]
New tree? Do tell :smile:

**Comment by joaomoreno** [comment]
@eamodio Going in stealth mode for now: https://github.com/Microsoft/vscode/tree/master/src/vs/base/browser/ui/tree

**Comment by eamodio** [comment]
Any update on this -- as this still causes a poor user experience?

**Comment by sandy081** [comment]
New tree is available now from @joaomoreno. Custom view needs adoption of this which I plan next milestone.

@joaomoreno Does this issue gets fixed with new tree?

**Comment by sandy081** [comment]
https://github.com/Microsoft/vscode/issues/63566

**Comment by roblourens** [comment]
I think this is N/A now?

**Comment by eamodio** [comment]
@roblourens Until https://github.com/Microsoft/vscode/issues/63566 lands (and assuming it fixes the issue) this is still valid.

**Comment by eamodio** [comment]
Woo -- It looks like this is fixed now!

**Comment by alexr00** [comment]
Thank you for digging up this issue and verifying!
