### ISSUE TITLE
update configuration in `deactivate` does not work

### ISSUE THREAD

**Issue by Sleen** [Microsoft/vscode#30927]
- VSCode Version: Code 1.14.0 (b8cd5b9556d8b70ea560d35b903422363f6c5c40, 2017-07-10T18:24:22.120Z)
- OS Version: Darwin x64 16.3.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
mist|Sle|0.1.5
language-pde|Tob|0.1.21
tmlanguage|Tog|0.7.1
html-css-class-completion|Zig|1.7.0
jshint|dba|0.10.15
vscode-eslint|dba|1.2.11
jquerysnippets|don|0.0.1
python|don|0.6.7
tslint|eg2|0.16.0
svgpreview|kis|0.2.0
vscode-gutter-preview|kis|0.10.0
prettify-json|moh|0.0.3
cpptools|ms-|0.12.0
csharp|ms-|1.11.0
debugger-for-chrome|msj|3.1.6
java|red|0.7.0
RustyCode|sav|0.19.1
shader-toy|ste|0.4.0
json-schema-validator|tbe|0.1.0

---

Steps to Reproduce:

I am developing an extension and I want to update a config before closing workspace.

I did this in the `deactivate` function, but it does not work.

```js
export function deactivate(context: ExtensionContext) {
    return vscode.workspace.getConfiguration().update('some.config', false);
}
```

**Comment by sandy081** [comment]
@alexandrudima Is it because the main process is not available during the deactivation of extension host?

**Comment by alexandrudima** [comment]
@sandy081 

Yes, the workbench process (the renderer) gets killed almost as soon as e.g. `x` is clicked. i.e. it does not wait for the extension host process. This is a UX decision that we don't want closing the window to be blocked by the extension host. i.e. only unsaved files when hot exit is off (i.e. data loss) is allowed from an UX point of view to veto the closing of the window.

So parts of the API (that are serviced by the workbench process) might not work because the workbench process might be dead, because we don't want to allow extensions to veto or delay the closing of the window. However, extensions can clean up other resources they have allocated e.g. kill spawned processes, i.e. deactivate is a place to shut down.

**Comment by sandy081** [comment]
Thanks @alexandrudima for explanation
