### ISSUE TITLE
Open folder not discoverable enough in no-workspace view

### ISSUE THREAD

**Issue by AngelosP** [Microsoft/vscode#3093]
The Debug pane tells you to open a folder in order to debug, but there is no "Open Folder" button there like there is in the Explore pane. Perhaps we could have the same "Open Folder" button there - or at least give you a pointer as to how you can open a folder in VS Code.

**Comment by isidorn** [comment]
As far as I understood you this is for the no-workspace view.
We have the open folder option in the top menu and in my opinion user is aware that he is a non workspace vscode (everything is purple). So the issue here is that the open folder is not discoverable enough in the no workspace view in your opinion?

We have the same situtation in the git viewlet.

Forwarding to @stevencl so he can read this feedback

**Comment by AngelosP** [comment]
@isidorn yes, you have understood the core of the issue. This is more of an issue for users discovering VS Code for the first time, as I do agree with you that once you know the difference between "workspace" and "no-workspace" views it is no longer a problem.

**Comment by stevencl** [comment]
I don't believe that this has come up during any of our interviews or studies and I don't recall any feedback from elsewhere on this but I do agree that we can do more to make the initial experience smoother.
For example, we are doing some work on first launch to encourage more people to go to our web site and hopefully read our docs so that they can get acquainted with VS Code more easily. I would rather wait and see how that pans out before we start adding more UI and more commands to the product.
I will keep this issue open so that I am reminded to come back to this once we have more data.

**Comment by stevencl** [comment]
I haven't seen this come up in the last few months so I am closing this.
