### ISSUE TITLE
Files renamed using VSCode Explorer panel are listed as deleted and recreated in git panel

### ISSUE THREAD

**Issue by rensa** [Microsoft/vscode#3097]
VSCode is able to detect files renamed using `git mv` as distinct from simply showing the old filename as deleted and the new one as created. But if I rename a file using VSCode's Explorer pane while I have a git-enabled folder open, it looks like it doesn't use `git mv` (at least in OS X), because the git panel then shows the file as being deleted and recreated.  This occurs as of VSCode 0.10.8 in OS X.

**Comment by joaomoreno** [comment]
This is as designed. If you run `git status` in the command line, you'll find the same behaviour.

**Comment by rensa** [comment]
Is it possible to ask for a toggle on this behaviour as a feature request? I'd love to be able to do file management in VSCode, but there's no point if I have to dip into the Terminal every time I want to rename a file to keep my commits neat.

**Comment by joaomoreno** [comment]
You don't have to dip to the Terminal. When you commit, [git figures out which pairs of adds and deletes equate to a rename](http://stackoverflow.com/questions/7938582/how-does-git-detect-similar-files-for-its-rename-detection). This mechanism is used at commit time but also at stage time, but not before staging your files.

Meaning this:

- if your files are not staged, they appear as a delete/add;
- once you stage them, git detects a rename (and thus Code does too);
- once you commit them, regardless of whether you staged them or otherwise, they will be detected as a rename.

**Comment by rensa** [comment]
Oh, great! I'm sorry, I didn't understand this behaviour. Thanks very much for explaining it!
