### ISSUE TITLE
go to definition dose not work

### ISSUE THREAD

**Issue by chaosforfun** [Microsoft/vscode#30995]
- VSCode Version: 1.14.1
- OS Version: mac os

Steps to Reproduce:

vscode is just a editor, why you guys don't fix the bug and just close the issue.

**Comment by blopez2010** [comment]
It is happening to me too... on ES6 methods, if you click go to definition or `cmd+click` it doesn't do anything and shows a message, look at this video https://screencast.com/t/m4r39Vy3DwIF

**Comment by rebornix** [comment]
@chaosforfun you'd better provide more info, like what languages you are working on, what kind of extensions you have, etc. Otherwise we don't know how to troubleshoot.

**Comment by blopez2010** [comment]
- VSCode Version: Code 1.14.1 (2648980a697a4c8fb5777dcfb2ab110cec8a2f58, 2017-07-13T19:08:57.197Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

`DotJoshJohnson.xml
GregorBiswanger.json2ts
IBM.output-colorizer
PeterJausovec.vscode-docker
Rubymaniac.vscode-paste-and-indent
Shan.code-settings-sync
WallabyJs.wallaby-vscode
abusaidm.html-snippets
alefragnani.Bookmarks
alefragnani.project-manager
alexdima.copy-relative-path
andys8.jest-snippets
anseki.vscode-color
christian-kohler.npm-intellisense
christian-kohler.path-intellisense
codezombiech.gitignore
dbaeumer.vscode-eslint
deerawan.vscode-dash
deerawan.vscode-jasmine-es5
discountry.react-redux-react-router-snippets
donjayamanne.githistory
eamodio.gitlens
fforjan.nuget4code
fknop.vscode-npm
formulahendry.auto-rename-tag
formulahendry.code-runner
gogocrow.webpack-snippets
guosong.vscode-util
heaths.vscode-guid
herrherrmann.angular-bootstrap
humao.rest-client
iradul.debugger-for-phantomjs
jakob101.RelativePath
jchannon.csharpextensions
jeremyrajan.webpack
jock.svg
joelday.docthis
jvitor83.typings-autoinstaller
k--kato.docomment
ksubedi.net-core-project-manager
lihui.vs-color-picker
lukasz-wronski.ftp-sync
mkaufman.HTMLHint
mohsen1.prettify-json
ms-mssql.mssql
ms-vscode.csharp
msjsdiag.debugger-for-chrome
rahulsahay.Csharp-ASPNETCore
redhat.java
reflectiondm.ClassyNaming
robertohuertasm.vscode-icons
rokoroku.vscode-theme-darcula
ryu1kn.partial-diff
samverschueren.yo
sozercan.slack
steve8708.Align
streetsidesoftware.code-spell-checker
tomphilbin.lodash-snippets
vilicvane.es-quotes
vsmobile.cordova-tools
vsmobile.vscode-react-native
waderyan.babelrc
wayou.vscode-todo-highlight
wcwhitehead.bootstrap-3-snippets
wilderminds.wilderminds-aspnetcore-snippets
wk-j.webpack-progress
wmaurer.change-case
xabikos.JavaScriptSnippets
zhuangtongfa.Material-theme`

Steps to Reproduce:

1. Open a React Native app
1. Create a method and make use of it.
1. Locate the use of the method and press `cmd+left mouse click` and see if cursor went to method definition.
1. Also click on the method and select `Go to Definition`.
1. In my previews post I said it `Find all references` didn't work, it does work if I disable the extensions, otherwise don't.


Reproduces without extensions: Yes

Please let me know what else do you need and I will be happy to help.

Regards,

**Comment by inter8ection** [comment]
I can confirm the lastest VSCode releases have also broken Cntrl-Click navigation in my React Native project.

**Comment by rebornix** [comment]
@mjbvz any chance that it's related to TypeScript LSP?

**Comment by mjbvz** [comment]
Please try VScode 1.14.2 which was just released. It includes TS 2.4.2 which fixes a number of issues that could be causing this

**Comment by blopez2010** [comment]
It works!! Thanks for the good work guys, I love this IDE!!

**Comment by inter8ection** [comment]
Quick work, thanks! That seems to have fixed the issue.

**Comment by dreszczyk** [comment]
@mjbvz i updated to 1.14.2 and peek + go to definition is not working, it just moves the cursor to import declaration. I'm working on react project, .jsx files.
