### ISSUE TITLE
Pasting into terminal find doesn't work on Windows

### ISSUE THREAD

**Issue by levani** [Microsoft/vscode#30994]
- VSCode Version: 1.14.1
- OS Version: Windows 10

Steps to Reproduce:

1. Copy some text
2. Focus on terminal and click ctrl+f and then ctrl+v

Search input is focused but after clicking ctrl+v the text is pasted in terminal itself.

Reproduces without extensions: Yes

**Comment by levani** [comment]
Also on macOS when I focus in the search input and click command+a the text in terminal is selected, not the input content. Pasting works fine though.

The problem seems to be that keyboard shortcuts don't always work in the context of the search input when it's focused...

**Comment by Tyriar** [comment]
The cmd+a thing is fixed in [Insiders](code.visualstudio.com/insiders) I believe.

**Comment by ihalip** [comment]
This happens because [TerminalPasteAction](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/terminal/electron-browser/terminalActions.ts#L304) is assigned the Ctrl+V shortcut and it hijacks the input from the `TerminalFindWidget`.

@Tyriar, do you think changing the [default keybinding](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/terminal/electron-browser/terminal.contribution.ts#L282) to Ctrl+Shift+V would be ok? In this case, pressing Ctrl+V in the find widget works as expected.

**Comment by Tyriar** [comment]
It's ctrl+v as I've tried to stay in line with OS standards and that's what cmd.exe uses. This should be able to get fixed by resolving the conflict.

/cc @cleidigh @rebornix

**Comment by bartsokol** [comment]
It also happens when you right click the search box, at least on Windows - see details [described here](https://github.com/Microsoft/vscode/issues/33833).
