### ISSUE TITLE
Do not open Welcome page on every reload

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#30997]
testing #30722:

whenever the workbench reloads, the "Welcome" page opens again.

I think it is OK to be welcomed when VS Code starts anew, but a welcome for every reload is a bit too much.
And yes, I know that I can turn off the Welcome page, but I do not want to do this.

**Comment by bpasero** [comment]
@chrmarti you can find out if the window was reloaded quite easily via:

`lifecycleService.startupKind === StartupKind.ReloadedWindow`

**Comment by chrmarti** [comment]
We don't open the Welcome page when any other editor is opened on startup. I'm not sure if adding more conditions outside of the user's control will improve the user experience.

**Comment by bpasero** [comment]
@chrmarti imho reloading the window with no editor open and seeing the welcome editor pop up is not expected. Welcome should appear upon initial startup or when changing folders only.

**Comment by weinand** [comment]
I was seeing it when adding folders to my workspace (because that triggers reloads).

Showing the welcome page in that flow is confusing, because it produces additional and unexpected visual change while the user is trying to understand was is going on with the "Add folder" operation.

**Comment by chrmarti** [comment]
We have other cases: The 'install extension' links on the Welcome page ask the user to reload and in that context it seems the user would expect to return to the Welcome page.

**Comment by weinand** [comment]
Really, why?

**Comment by chrmarti** [comment]
Installing an extension just one of several interactions with the Welcome page and new users will find the guidance there helpful also after installing an extension through one of the links that install the extension without going through the extension viewlet. The Welcome page was the last thing they interacted with before the reload so it makes sense to bring them back there.

**Comment by bpasero** [comment]
@chrmarti I was not suggesting to close the welcome page when it was opened, so it is fine to have it open when it was opened before (this matches our general strategy to restore as much UI state as you had before).

The flow I find weird is:
* close all editors
* reload window
* => welcome shows up

**Comment by chrmarti** [comment]
@bpasero I'd have to remember if the Welcome page was still open on shutdown. Can you provide any code pointers on how to do this?

**Comment by bpasero** [comment]
Maybe just use the storage service to keep this info around (e.g. you clear this when welcome is closed)?

**Comment by bpasero** [comment]
@chrmarti currently no support for that. But back to opening welcome on reload: isn't the fix just NOT opening welcome when a window reload happened? I am not sure why we need to add more than that?

**Comment by chrmarti** [comment]
@bpasero (from above): We have other cases: The 'install extension' links on the Welcome page ask the user to reload and in that context it seems the user would expect to return to the Welcome page.

**Comment by bpasero** [comment]
@chrmarti maybe then it would make sense to register an editor input factory for the welcome editor. These factories cause an editor to persist between restarts (e.g. all files implement it so that they can correctly restore). An example is: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/browser/files.contribution.ts#L113

A editor input factory is asked during shutdown to persist an opened editor to a JSON and will be asked to restore it when the window comes back. If you can put the knowledge of your input into such a thing, then it can be nicely restored (this would also include the playground).

With the factory you only need to open the welcome editor if there is no other editor opened, if there was no reload and if the user has not disabled it. I think that is the cleanest solution.
