### ISSUE TITLE
Explorer background menu looks a bit silly

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#31004]
testing #30722:

The poor explorer background menu is very tiny now (and doesn't look like a menu any more):

![2017-07-19_11-58-13](https://user-images.githubusercontent.com/1898161/28361637-bb9829ea-6c79-11e7-855d-59e4a48169ef.png)

Some ideas for useful actions that could be added:
- Save Workspace
- Save Workspace as
- Rename Workspace
- Find in Workspace
- New Folder

**Comment by bpasero** [comment]
+1 for adding more workspace related actions to this menu (now that we have them). Just to compare, here is the menu when a folder is opened:

![image](https://user-images.githubusercontent.com/900690/28362209-dd3358ca-6c7b-11e7-8835-af79031befdc.png)

I think we can take some of the entries also for the workspace case. Not 100% sure about "Save Workspace". There is also "New Workspace" and "Open Workspace", though they are not so explorer specific.

**Comment by isidorn** [comment]
In this case for consistency I propose that we just copy the workspace sub menu. Also all those actions make sense to me in that context

![screen shot 2017-07-20 at 11 05 13](https://user-images.githubusercontent.com/1926584/28409595-5a972f20-6d3b-11e7-8702-dd7773aee56f.png)

**Comment by bpasero** [comment]
@isidorn not sure I would agree, for example we also do not show "Open Folder..." in the context menu for an empty folder. 

If we want to make the context menu less sparse, I think we should only add entries to the context menu which are relevant to the explorer and not to the workspace (e.g. the "Add Folder to Workspace" action is relevant because it adds a folder to the explorer). 

My suggestion was to add more of the entries we have in the single folder case. "Find in Workspace" for example should work nicely (it is just a normal search without includes specified).

**Comment by isidorn** [comment]
I have added the "Find in Workspace..." (also renamed "Find in Folder" to be "Find in Folder..."
As for the other actions proposed here 

Only Save Workspace and Save Workspace As, seem to make some sense. However I have not added them yet to not clutter the menu. Let me know if you would still prefer these actions and I can add them

**Comment by weinand** [comment]
I don't think that a 2-item menu gets already cluttered by adding two more actions:

![2017-07-27_16-56-32](https://user-images.githubusercontent.com/1898161/28677011-8f66b782-72ec-11e7-9587-721638b4251b.png)

So I think Save Workspace and Save Workspace As should be added.

**Comment by weinand** [comment]
I've added the verified label because with 100% enlargement the menu no-longer looks silly ;-)

**Comment by isidorn** [comment]
@weinand adding save actions makes sense imho
