### ISSUE TITLE
Unite all the open menu items

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#31005]
Refs: #30722

Currently we have Open File, Open Folder, Workspaces > Open Worksace
Can't we just have one Open which if the user chooses a file opens a file, same for folder and workspace.

This seems more natural and easier to use and it seems to be what sublime is doing

![screen shot 2017-07-19 at 12 06 13](https://user-images.githubusercontent.com/1926584/28361921-bbf6c31e-6c7a-11e7-82ce-921bbe8790cb.png)

**Comment by bpasero** [comment]
Yeah, on macOS we could do this because macOS allows to pick files and folders from a single dialog. However on Windows and Linux you cannot open a dialog like that so the options we have are:
* show "Open Workspace..." after "Open File..." and "Open Folder..." and not within the "Workspaces" submenu
* force users to open a workspace via "Open File..." and remove the "Open Workspace" item
* keep what we have
* macOS only: remove the "Open Workspace" item and let everything go through the existing "Open..." item

Happy for suggestions @Microsoft/vscode

**Comment by michelkaporin** [comment]
I would be happy to see "Open File or Workspace" under single menu item and "Open Folder" next to it due to Windows limitations. Thus, removing Open Workspace from "Workspaces category. 

Let everything go through single "Open..." on Mac OS makes sense.

**Comment by weinand** [comment]
"Open File or Workspace" sound strange to me.
I would keep "Open File" and "Open Workspace" (or maybe "Open Workspace File") separate because sometimes I want to open the *.code-workspace file as text and not as a workspace.

**Comment by bpasero** [comment]
That is a good point about being able to open the workspace file as plain text file.

**Comment by michelkaporin** [comment]
Right, forgot about that case. I would keep it then as it is now...

**Comment by weinand** [comment]
Clarification: I meant:
* "Open File" to open files without interpretation (this includes to open the *.code-workspace file as text)
* "Open Workspace" to open the workspace via a *.code-workspace file 

(forget about the "Open Workspace File" from above. That's confusing)

**Comment by bpasero** [comment]
![pasted image at 2017_07_20 08_17 am](https://user-images.githubusercontent.com/900690/28403271-5e57c550-6d24-11e7-9fb4-65537f8cf972.png)
![pasted image at 2017_07_20 08_17 am 1](https://user-images.githubusercontent.com/900690/28403272-5e5c76f4-6d24-11e7-8a37-82e73fe07f9e.png)
