### ISSUE TITLE
Silly dialog when removing a folder from a workspace

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#31014]
Testing #30722:

On removing the first folder from my workspace I get this warning:

![2017-07-19_12-30-11](https://user-images.githubusercontent.com/1898161/28362804-331c5514-6c7e-11e7-8799-b770badb7f7f.png)

"added or removed" sounds strange since VS Code should know exactly what I did (and I don't think that this alert is even used in the "Add" case).

Either use the correct verb or call it "change".

In addition, the second sentence is not really adding anything new (and there is not even a "restart" button).

**Comment by bpasero** [comment]
@weinand I am open to ideas here, my current idea is this:

![image](https://user-images.githubusercontent.com/900690/28369581-57368ca2-6c98-11e7-8923-cb6445e07ab1.png)

The reason we have to reload the window is because you changed the first folder of the workspace and our extension host needs to be restarted because we use the first folder as "legacy" `workspace.rootPath` still.

**Comment by weinand** [comment]
Removing the first folder from a workspace is not a "change" of that folder. So either:
   "Removing the first folder of the workspace requires a ..."
or 
   "This workspace change requires a ..."

And for the reason maybe something like this:
"... restart of the extension system."
"... reload of the extension system."
"... window reload."

"better experience" sounds wishy-washy. Our users are developers. They want correct behaviour. ;-)

And "shorter" is "better"...

**Comment by bpasero** [comment]
@weinand good points, how about this:

![image](https://user-images.githubusercontent.com/900690/28370618-040bfe4c-6c9b-11e7-8669-120985e03f3b.png)

**Comment by weinand** [comment]
I like that a lot: short but clear!

**Comment by bpasero** [comment]
@weinand thanks
