### ISSUE TITLE
debug continues to use launch.json from removed folder

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#31019]
Testing #30722:

- workspace with three folders: the first with launch config, two without
- go to debug viewlet and open launch config drop down
   -> it should show the launch configs
- remove the folder with the launch configs from workspace
- go to debug viewlet and open launch config drop down
   -> it correctly show "No configuration"
- press on the gear item
   -> launch.json from the removed folder is opened

**Comment by roblourens** [comment]
I can still repro

**Comment by isidorn** [comment]
@roblourens I can not repro following @weinand exact steps.
Can you please give me reproducable steps for which you can reproduce this? Thanks

**Comment by roblourens** [comment]
I'm following exactly the original steps, and it still reproes for me.

**Comment by isidorn** [comment]
I can repro also, was following steps wrongly.
This is dependent on https://github.com/Microsoft/vscode/issues/31597

Since [here](https://github.com/Microsoft/vscode/blob/isidorn/next/src/vs/workbench/parts/debug/electron-browser/debugConfigurationManager.ts#L313) I should be listening on root changes and not on configuration changes which I can not do currently.

fyi @sandy081

**Comment by dbaeumer** [comment]
verified.
