### ISSUE TITLE
Make sure that commands around "workspaces" are functional in single- and multi-folder workspaces

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#31012]
Refs: #30722

Since we now have a new meaning for Workspace imho we should go through our old uses of workspace in the ui and debate if we should use folder somewhere instead.
Optimally all these actions would update to our new concept of workspace and execute in that context

![screen shot 2017-07-19 at 12 23 12](https://user-images.githubusercontent.com/1926584/28362591-37032ae6-6c7d-11e7-8b81-19fe43e24dc5.png)

**Comment by bpasero** [comment]
Yeah we also have settings that use folder vs workspace semantics.

**Comment by bpasero** [comment]
@isidorn is there an entry in your screenshot in particular where you would use "Folder" instead of "Workspace"? I think we decided that we call a single folder workspace also a "Workspace" in the UI as well as a multi-folder workspace. Eventually these two will become very similar once the transition from single to multi folder is smooth.

/cc @sandy081 for input

**Comment by isidorn** [comment]
No, there is no entry in particular where I would prefer using "Folder" over WOrkspace.
However for all tbose entries I would expect that thtey work across folders in the whole MR workspace. IF that is not the case then it can be confusing.

**Comment by bpasero** [comment]
Adding @sandy081 for extensions and @Tyriar for the terminal.

**Comment by sandy081** [comment]
Extensions related commands will be taken care by the issue #29242

**Comment by Tyriar** [comment]
Almost all terminal commands work on the active terminal instances. Actual multi-root UX improvements are being considered in https://github.com/Microsoft/vscode/issues/34163
