### ISSUE TITLE
Change the behavior of file extension associations

### ISSUE THREAD

**Issue by raszi** [Microsoft/vscode#31017]
- VSCode Version: Code 1.14.1 (2648980a697a4c8fb5777dcfb2ab110cec8a2f58, 2017-07-13T19:08:57.197Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.2.11
vscode-dash|dee|1.7.0
tslint|eg2|0.16.0
vscode-npm-script|eg2|0.2.0

---

Steps to Reproduce:

1. Install Visual Studio Code
2. Click on any previously unassigned extension
3. Visual Studio Code will be opened instead of the previous app or nothing

I tried out Visual Studio Code and it is working fine but we are still in getting know each other phase. 

Unfortunately Visual Studio Code aggressively assigned itself to all the extensions it knows and that feels very intrusive. I tried to un-assign the associations with [RCDefaultApp](http://www.rubicode.com/Software/RCDefaultApp/) without any luck.

Could you please somehow change the behavior or not assign anything by default? Thanks!

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
I could never reproduce this issue. What we have set up is the fact that Code registers itself as an application which is able to open a variety of different file formats. If you have never specified another application for a specific file format, it may very well be that Windows assumes that Code is the only one that can open it. On the other hand, if you have specified that application X should open file type A and then install Code, file type A will **not** be associated with Code. If you see otherwise, please tell me which file extension it is and which application was initially associated with it and I'll try to reproduce.

Ultimately we added an option in the setup (disabled by default) which lets you skip the association altogether, for this specific purpose.
