### ISSUE TITLE
Only offer applicable settings for folder settings

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#31034]
Refs: #30722

Currently only some settings are applied for folder settings, however in intelli-sense everything is offered. 
I would expect that we only offer what is applicable for folder settings.

**Comment by sandy081** [comment]
Implementing intelli-sense showing only folder settings is blocked by following

- Dynamic schema association to a file from core. This is needed because Folder settings file is both workspace settings and folder settings in Single folder and Multi folder contexts. Currently we can only associate a JSON schema to a file through static registry (`package.json`) and reading of this registry happens in the extension. So Core does not have any way to associate schemas dynamically to a file. Extension does not have a knowledge about single folder and multi folder context (which is internal to core). @aeschli FYI

- Having such a schema supporting only folder settings will show warnings for workbench settings in this file. This will cause the concerns raised here - #29462

**Comment by sandy081** [comment]
#33083 will help in solving the second issue in above comment.
