### ISSUE TITLE
Improve wording on "Save Workspace dialog"

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#31033]
Testing #30722:

- open an untitled multi-root workspace in VS Code
- try to open a folder in the same window

Observe: you get this dialog: 
![2017-07-19_14-38-47](https://user-images.githubusercontent.com/1898161/28367161-10512250-6c90-11e7-8702-9ba20e571def.png)

I don't think that "opened in this window" is really necessary, so I would drop it from the message.

I recommend to use the term "untitled workspace" to make clear what the real reason is. For **named** workspaces you will not be prompted so save.

"Your workspace will be deleted" sounds very aggressive. I suggest to use something like
"You lose your workspace if you don't save it" (but when reading this, it sounds so obvious that I think we should drop the second sentence completely).

In general we should keep the text on these dialogs as short as possible because users don't want to spend lots of time reading these explanations.

**Comment by bpasero** [comment]
@weinand how about this?

![image](https://user-images.githubusercontent.com/900690/28369858-11b90f96-6c99-11e7-9588-e767281da928.png)

I like the "details" of a dialog because it gives it some balance over this:

![image](https://user-images.githubusercontent.com/900690/28369887-24f54eda-6c99-11e7-862c-368d63091b36.png)

**Comment by weinand** [comment]
In general, you don't have to save the workspace under a name in order to open it again. It opens automatically if it's untitled.
But in the special case of the "Open Folder", you need to save it under a name otherwise it's lost.
So "You lose your workspace if you don't save it" would be more precise.

But I'm fine with your first proposal as well.

**Comment by bpasero** [comment]
@weinand yeah it is true that you can open an untitled workspace without saving however in this case it is really gone if you do not save. I like both proposals, let's see how our users react to this 👍

**Comment by chrisdias** [comment]
I'm not sure we need to use the word "untitled" in this dialog. Is the thing that I want to save "untitled workspace" or is it a workspace with no title?  Is an "untitled workspace" a thing that I need to know about?  

As a comparison, consider this dialog:
![image](https://user-images.githubusercontent.com/1487073/28388846-e673c34a-6c88-11e7-9bfe-2c776723a071.png)
(as an aside, I'm not sure the sub-message that says your changes will be lost if you don't save them is necessary, it seems pretty obvious :))

In this case I'm being asked to save a thing "Untitled-1".  

A more consistent message would be:

"Do you want to save the changes you made to workspace "Untitled"?"

But, since there can ever only be one unsaved and therefore untitled workspace, you can even eliminate it and just prompt:

"Do you want to save your workspace?".

**Comment by bpasero** [comment]
@chrisdias I think @weinand reasoning was to emphasize that you are not being asked to save any other workspace that is saved (hence the "untitled" in the name). 

I am fine removing that again, but let @weinand speak up.

One thing we have to keep in mind is that the dialog should not look too similar to the one you get when saving files. So the wording should not be too similar imho.

**Comment by weinand** [comment]
If a user has turned on "Auto Save" she will probably be surprised if she sees a "Do you want to save your workspace?". By mentioning "untitled" I tried to make clear that the **missing name** is the problem here, and not the save (because that happens automatically).
If you do not agree that this might be an issue, then please go with the wording without the "untitled".

**Comment by bpasero** [comment]
Maybe the term "Untitled Workspace" is a bit misleading here because it is overloaded with "Untitled" file that we have when you create a new file? I am happy to change the wording if someone has a better idea.

**Comment by weinand** [comment]
"Do you want to save your workspace configuration as a file?"

(I'm using the term "configuration" to make clear that this is not the workspace content, so nothing really bad happens if you don't save)

**Comment by bpasero** [comment]
Looks good to me:

![image](https://user-images.githubusercontent.com/900690/28411295-a2b4ab3e-6d40-11e7-9a96-55bd241044fc.png)
