### ISSUE TITLE
Markdown preview button does nothing

### ISSUE THREAD

**Issue by mattacosta** [Microsoft/vscode#31038]
- VSCode Version: Code - Insiders 1.15.0-insider (9a308d1128df9af90e84b2988bce4f57f885b1c3, 2017-07-19T06:40:56.880Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: none
---

Steps to Reproduce:

1. Open a markdown file.
2. Click the open preview button.

Expected result:
A preview is shown to the side.

Actual result:
Nothing happens.

Another fairly obvious bug. Unlike #30584, the preview tab isn't even shown.
- Nothing in the developer tools console.
- Related command palette functions do nothing as well.

**Comment by mjbvz** [comment]
@bpasero Looks like the root cause is an `instanceof` check failing. The received instance in the markdown extension is a `URI` instead of a `vscode.Uri`
 
<img width="588" alt="screen shot 2017-07-19 at 12 59 49 pm" src="https://user-images.githubusercontent.com/12821956/28387503-3967f878-6c84-11e7-8165-b69875f7cffa.png">


The `resource` in this case comes from command handler. Let me know if is an area you are familiar with otherwise I can try looking into the root cause

**Comment by bpasero** [comment]
No clue, adding @jrieken

**Comment by jrieken** [comment]
>  The received instance in the markdown extension is a `URI` instead of a `vscode.Uri`

There is only one implementation of `URI` and we [assign](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/node/extHost.api.impl.ts#L557) its constructor to be `vscode.Uri`. Tho we do sub-class URI once, basically to hide its ctor. I'll take a look

**Comment by jrieken** [comment]
Yep, problem is that we have set `vscode.Uri` to the sub class we have (and already for a long time had) in extHostTypes when creating the API and that our marshaller creates instances of its super-class (URI). And a super type isn't an instance of a subtype...

**Comment by jrieken** [comment]
@joaomoreno This is also the cause of not being able to go back from a diff editor... Mea culpa maxima. 

Rewards for whom can explain to me why TypeScript complains about `vscode.Uri` being assigned with `URI` ("fixed" with any-cast 🙈). See: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/node/extHost.api.impl.ts#L557

**Comment by joaomoreno** [comment]
Good catch.
