### ISSUE TITLE
Content is newer on disk should have overwrite call to action. UX issue

### ISSUE THREAD

**Issue by nojvek** [Microsoft/vscode#31063]
I change my theme and I see this:

![image](https://user-images.githubusercontent.com/1018196/28381973-5ca64a28-6c71-11e7-879d-d37955199da7.png)

Its already on the compare screen so the CTA is meaningless.

So I click compare and I see the info box.

![image](https://user-images.githubusercontent.com/1018196/28381977-61f34e0e-6c71-11e7-936a-5cc03b779b33.png)

I type "ctrl+s" and go back to compare.

The appropriate call to actions are just present me with "Overwrite, undo, Cancel". 

I searched help for overwrite and it doesn't even exist in edit menu.

![image](https://user-images.githubusercontent.com/1018196/28382061-b085376c-6c71-11e7-92fd-38ba461d4477.png)

My solution was to just close vscode and make the change myself after a restart. That is a terrible work around but it got the job done.

**Comment by bpasero** [comment]
@nojvek the actions for overwriting or taking the change are in the editor toolbar here:

![image](https://user-images.githubusercontent.com/900690/28401567-06aec9d8-6d1b-11e7-9209-92bea190a07c.png)

We can revisit to make them more prominent somehow.

**Comment by bpasero** [comment]
Btw you should never get this error when changing a setting. @sandy081 is working on improving this flow a lot.

**Comment by bpasero** [comment]
Related: https://github.com/Microsoft/vscode/issues/14298 and https://github.com/Microsoft/vscode/issues/20876

**Comment by qqtrend** [comment]
I thought I'd +1 this, rather than start a new issue. I sometimes get this error. In the little popup I want it to offer more than just the "Compare" button. I want a "Just Save It" button. (Or, it could be called "Overwrite Anyway".

I don't want to mess around doing diffs, and having to work out what has changed and which is the correct version. I know that the version in the editor is the code I want on disk. (In my case it is because I forgot to save before I ran tests, and they have a side-effect of automatically fixing whitespace and similar issues.)

To be clear: I *do* want the popup to tell me the file on disk is newer. I just want a quick way to tell it I know what I'm doing.

**Comment by bpasero** [comment]
Merging into https://github.com/Microsoft/vscode/issues/46706
