### ISSUE TITLE
Allow to drag/drop folder onto multi-root workspace to add folder

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#31082]
testing https://github.com/Microsoft/vscode/issues/30722

![image](https://user-images.githubusercontent.com/1487073/28392903-f66c9758-6c98-11e7-9019-a3f9eed5fe2f.png)

Drag and drop of a folder onto an instance of VS Code that has multiple roots does not add the folder to the workspace. Instead, it reloads the workbench on the single folder.

**Comment by bpasero** [comment]
The UX challenge here is to allow the user to either add the folder or open the folder in the window, so it looks like we would need 2 drop targets.

**Comment by bpasero** [comment]
Given the bug https://github.com/Microsoft/vscode/issues/32537 due to the electron update, I tackled this feature request as well: If you are inside a workspace and you drop folder(s) onto the explorer, we will add those folder(s) to the workspace. Otherwise, an info message is shown to first open a workspace:

![image](https://user-images.githubusercontent.com/900690/29550942-be649594-8710-11e7-9f9f-2603f3ad42c8.png)
