### ISSUE TITLE
Introduce an API in IWorkspaceContextService to know the state of the workspace

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#31132]
From @isidorn in https://github.com/Microsoft/vscode/issues/30247#issuecomment-316621420

How about the following? Makes it clearer?

```typescript
getWorkspaceState(): WorkspaceState;

enum WorkspaceState {
   EMPTY,
   SINGLE_ROOT,
   MULTI_ROOT
}
```

**Comment by bpasero** [comment]
@sandy081 @isidorn `SINGLE_ROOT` and `MULTI_ROOT` is probably confusing to use because you can have a workspace open with just 1 folder. Maybe better:

```typescript
enum WorkspaceState {
   EMPTY,
   SINGLE_FOLDER,
   WORKSPACE
}
```

**Comment by sandy081** [comment]
@bpasero It is odd not to call Single folder a workspace. Because it is also a workspace.

**Comment by bpasero** [comment]
@sandy081 I think the API should reflect our internal state and not so much our conceptual state for users. There is a clear separation across our code between:
* having no workspace open ( = empty)
* opening just a folder
* opening a workspace file

Especially the fact that a workspace file can have 1 folder, many folders or even 0 folders (not supported today, but why not?) makes it hard to find names that reflect the visual experience. I would not try to capture the visual impact in the name but rather the internal state because this API is internal.

**Comment by sandy081** [comment]
Implemented
