### ISSUE TITLE
Text Highlighting error when using \": in json data

### ISSUE THREAD

**Issue by krum110487** [Microsoft/vscode#31148]
- VSCode Version: 1.14.1
- OS Version: Windows 10 Enterprise 1607

Steps to Reproduce:
the following JS code does not highlight as expected
```
var test = {
    "data": "\number\":8"
}

var test2 = "text is correct still, but everything else is light blue"
var testfunc = function() {
    //this is not working as expected
}
```

![image](https://user-images.githubusercontent.com/823986/28430880-197ab98e-6d50-11e7-97e3-261b5952634c.png)

if you remove the colon, or the \" it will work as expected:
![image](https://user-images.githubusercontent.com/823986/28430942-6d2f8d7a-6d50-11e7-90b9-9c9029e92450.png)

No extensions installed, fresh install of the vscode on a new pc.

**Comment by mjbvz** [comment]
Thanks. This should already be fixed in the insiders builds:

![screen shot 2017-07-20 at 11 54 07 am](https://user-images.githubusercontent.com/12821956/28433912-452094d6-6d42-11e7-901a-7b08293faaee.png)

You can also install the [latest ts grammar](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) in 1.14 to fix this
