### ISSUE TITLE
Expect value for staticPath different than expected in Debug Panel 

### ISSUE THREAD

**Issue by kscott5** [Microsoft/vscode#31172]
AH! 

This appears to happen a lot. Whenever I start coding again, the ghost in the machine interferes with my app. I don't want to return to work.

HA!

- VSCode Version: 1.13.0
- OS Version: Windows 7 Pro 64bit

Steps to Reproduce

1. git clone [Rescue Shelter Demo](http://github.com/kscott5/RescueShelter)
2. Open with VSCode
3. npm install & npm run compile-ts
4. Select the app.js file located in build\src folder
5. Add break point and step into server.js.
6. Review the Debug panel and hover over staticPath variable

![strange](https://user-images.githubusercontent.com/132991/28445333-5f61e448-6d89-11e7-85bd-584dfb99adcc.png)

**Comment by isidorn** [comment]
This is just how we decided to show whitespace in different areas, in variables and watch expressions since the space is limited we decided to show \r \n instead of newline. In the hover since we have more space we have decided to instead show the real meaning of those characters, so we are by design replacing \r with nothing.

The bug in your program is that you are a doing
`let staticPath = __dirname + "\react";`
instead of
`let staticPath = __dirname + "\\react";`
Or even better maybe a path library so this code is not os dependent

Closing as designed. For more reasons on why we present whitespace like this you can search our old issues.

**Comment by kscott5** [comment]
Ah! I should have used forward slash instead. I didn't think about escape characters at that time. Ha!
I thought this would be a quick app to write. React said it was designed for easy of use. So, the plan was get the app run and refactor. The create-react-app module was taking up most of my time with errors executing in the terminal.

Thanks for the quick peer review.
@isidorn @weinand @vscodebot
