### ISSUE TITLE
Educate users about workspaces once they are in multi-root workspace

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#31182]
**Ideas:**
	•	show something first time a workspace is opened
	•	make sure the release notes are catchy enough to promote multi root workspaces
	•	add more actions to welcome to enter multi root workspace

**Comment by chrisdias** [comment]
As a user (so far at least) I have not found any trouble understanding that I've now got a workspace to save. Perhaps it is as simple as providing a link on the save dialog where I can get more information?

**Comment by evandrocoan** [comment]
### Workspaces and multi-roots

> @chrisdias, As a user (so far at least) I have not found any trouble understanding that I've now got a workspace to save. 

As user just coming from Sublime Text, I got a lot trouble understanding this. At least I had to read the whole other thread #30854 (disturbing alert when adding another folder to a workspace) to understand why you are talking about: `-Now we have to save the workspace with multi-root`. From it, it seemed until now the VSCode users did not had to save the workspace, just create the `.vscode` folder on their project root, and VSCode would save for them the opened files, search history, unedited files (`hotexit`).

This make very sense. I come from Sublime-Text, where this is not a problem because of the workflow followed. Which is the concept of projects which lists the multi-roots, and each project has a workspace assigned automatically by Sublime Text. You can also have more workspaces, you just need to save more copies. But all them would have the same multi-root folders from their project file.

I would suggest same concept here because it is very neat to work with. Accordingly to the VSCode structure, I would suggest to save the multi-root data inside the `.vscode` workspace settings, however it seems to be a computer-based setting, hence we cannot put it there as we cannot move it around (due absolute path on it).


### Sublime Text vs VSCode

With both editors you can accomplish the same thing, but the naming used differ. A [Sublime Text Project](https://www.sublimetext.com/docs/3/projects.html) (.sublime-project) is equivalent to the new multi-root feature on the insiders version:

> As a general rule, the .sublime-project file would be checked into version control, while the .sublime-workspace file would not.

However the Sublime Text project has a little problem when listing multi-folders, you will probably need to add absolute paths, therefore these things are not welcome to pass across several computers, i.e. add them to version control.

Anyway apart from that, you can add both Sublime Text Project files and VSCode Workspaces to version control, except that on a `.sublime-project` I would add the first path as relative and them add the others as abosolute. For example for a simple `.sublime-project`:
```javascript
{
    "folders":
    [
        {
            "path": "."
        },
        {
            "path": "F:\Absolute",
            "some_setting": 10
        },
    ],
    "settings":
    {
        "tab_size": 8
    },
}
```
Following this, you guys could also add support for `multi-root` folder on the `Folder Data Settings`:

![image](https://user-images.githubusercontent.com/5332158/28486619-20105e56-6e5a-11e7-89b5-39d0076cd8a0.png)

As their difference from the `multi-root` workspace is not too much:

![image](https://user-images.githubusercontent.com/5332158/28486704-4d4c6d96-6e5b-11e7-9483-8b7030f61178.png)

Basically the `multi-root` folder workspace has a list of directories and settings, while the `Folder Data Settings` has only a list of settings. May be would not be nice to pollute `Folder Data Settings` with not portable directives as the `.sublime-project` does. What do you think?


### Workspaces, where are you?

Wait what? No, not that workspaces, the [Sublime Text Workspace](http://docs.sublimetext.info/en/latest/file_management/projects.html#workspaces) 

> Workspaces hold session data associated with a project, which includes information about the opened files, pane layout, find history and more. A project can have multiple workspaces.

I could not find where you guys put these data associated with the project. Sublime Text saves them on a `json` file called `.sublime-workspace`. Initially it is put like plague automatically together with the `.sublime-project`, using its same name. So often I put then on my projects `.gitignore --> *.sublime-workspace` . However later you can `save it as...` and put it elsewhere from the `.sublime-project`:

![image](https://user-images.githubusercontent.com/5332158/28486887-b3039b12-6e5d-11e7-801b-8bc6cbc442cf.png)


### Quotes

> @chrisdias, Perhaps it is as simple as providing a link on the save dialog where I can get more information?

Would be awesome such a link. It could be like: `Not sure what it means? Follow this tutorial...`


> @bpasero I think we must find a way to educate the user what this concept is. Maybe with a separate welcome screen 

Would be very welcome, as the warning suggested by @chrisdias:

> something like this...

> ![image](https://user-images.githubusercontent.com/5332158/28487326-711d441c-6e64-11e7-8ea3-1f76f1f26d99.png)

Every time the user is on a workspace not saved yet, make that warning pop up. But do not put a button like `Don't show this again`, because for now this is a very serious setting and they can ignore too easily. I would suggest the Windows 10 Calendar pop up:

![image](https://user-images.githubusercontent.com/5332158/28487364-217ce95c-6e65-11e7-8086-b266ca5fff1f.png) ![image](https://user-images.githubusercontent.com/5332158/28487361-12bedde4-6e65-11e7-8cc8-390cc99819e9.png)

If someone is really interested on ignoring that warning for ever and ever, we can add a setting to the user setting which disables this warning for ever and ever. So the user's more determinate on not seen seen it, will start searching, may even creating new issues here asking how to disabled that.

I would not disabled that warning, because I would like to know when I am on a workspace, which is not persistent across sessions, crashes, tornados, hurricanes, floods, etc. Please, never let me loose my work.


### Ending

Ok, may be I gone too far with the `snooze` thing, because would require more work for the implementation of the `snoozing` system. Then for simple implementation ([KISS](https://en.wikipedia.org/wiki/KISS_principle)), the warning:

> ![image](https://user-images.githubusercontent.com/5332158/28487326-711d441c-6e64-11e7-8ea3-1f76f1f26d99.png)

Should only be dismissed for the current session. If the user is interested, he should click on the `Learn More...` button and learn more things about it as the new setting which disables that warning permanently for non-saved workspaces.

**Comment by bpasero** [comment]
@chrisdias 

> As a user (so far at least) I have not found any trouble understanding that I've now got a workspace to save. Perhaps it is as simple as providing a link on the save dialog where I can get more information?

I wonder if that is because of all the background knowledge you have around this feature and know the various changes we did to it over time. Imagine a user that is seeing the untitled workspace for the first time, how does the user make the connection that workspaces are required to support multi-root workspaces? We basically took away any guidance in the process of getting into the untitled workspace (e.g. the dialog just talks about a window reload but not about us creating a workspace). 

In other words: A user might ask why she is not being asked to save a workspace when opening a folder. It will seem random when VS Code is in that "Untitled Workspace" case vs. not.

@evandrocoan 

> I would suggest same concept here because it is very neat to work with. Accordingly to the VSCode structure, I would suggest to save the multi-root data inside the .vscode workspace settings, however it seems to be a computer-based setting, hence we cannot put it there as we cannot move it around (due absolute path on it).

How would that work if you have multiple folders opened in VS Code, to which folder would you store the multi-root information? Imho in the multi-root case we cannot store any configuration into the `.vscode` folder because we have multiple folders to choose from. That is the reason why we introduce "Workspaces" outside of these folders (either in the user data directory as long as not saved, or saved to the location the user choses). 

> I could not find where you guys put these data associated with the project. 

Currently we do not support to store UI state into a file (like Sublime with their workspaces feature). There is a couple of things associated with the workspace ID:
* all UI state (currently stored in browser local storage within the window)
* all dirty files (hot exit functionality, stored inside a folder in the global VS Code data directory)
* all extension state (stored inside a folder in the global VS Code data directory)

As for the notification we can do a couple of things:
* show a message at the top that can be dismissed for good with further info
* adjust the welcome experience to educate what workspaces are for

**Comment by evandrocoan** [comment]
> How would that work if you have multiple folders opened in VS Code, to which folder would you store the multi-root information? 

It would be different situation from which is on Sublime Text, because there each folder included is not able to include new folders. Here a `folder1` could include `folder2`, and `folder2` could include again `folder1` or include a `folder3`, which include `folder1` and `folder2`. On these recursion cases we would ignore folders already added to the `multi-root` list.

Now to the saved data, we would respect the initial inclusion order. For the last example, we would save the data on the `folder1` which is the parent/master node on the folder hierarchy. It means we would ignore the other `.vscode` folders. This behavior would be the same for Sublime Text projects which include multi-roots. Sublime text associates all roots information with the parent/master folder which contains the `.sublime-project` which defines the corresponding `.sublime-workspace` to save all the project data. On this case, if the user wants to save a different set of data associated to the current state, he can save a new `.code-workspace` which will include the current open folders and starts associating its data as usually does with `.code-workspace` files.

For example, comparing the settings files between Sublime Text multi-root structure and VSCode suggested `multi-root` feature:

**MyProject.sublime-project**
```
{
    "folders":
    [
        {
            "path": "."
        },
        {
            "path": "F:\Absolute",
        },
    ],
    "settings": {},
}
```

**.vscode\settings.json**
```
{
	"id": "1500678919594",
	"folders": [
		"F:\Absolute"
	],
	"settings": {}
}
```
On this example the `.vscode` would be the folder I first opened on VSCode. If the folder `F:\Absolute` also defines a folder `.vscode` with multi-root folder, their folders/settings would be ignored. If I open a `.vscode` which defines `multi-root` folder, only its folders would be interpreted. If the remaining folder also define a `.vscode` with multi-root they would be ignored.

Implemented like this would be an exactly replica of Sublime Text Projects multi-root feature, where the `.sublime-project` defines the current folder as a relative folder `.`

I think is the best to be used here because would mimic the Sublime Text projects and Keep It Simple ([KISS](https://en.wikipedia.org/wiki/KISS_principle)), which is good. Now the user can only define one of its `.vscode` folder with `multi-root` data, if other folders define them, they would be ignored. 

This same concept would be applied if the user opened a `.code-workspace` which defined `multi-root` data. If some of the folders included by a `.code-workspace` also define a `multi-root`  data they would be ignored as well. Perhaps present to the user a warning when some of the included folders also defined multi-root data, so if the user wishes so, he can add the `multi-root` data he would like to keep to their `.code-workspace` or first `.vscode` which opened the others `.vscode` folders with `multi-root` data.

**Comment by stevencl** [comment]
The first point at which somebody might want more information about workspaces is when they first see the 'Add folder to workspace...' command, rather than after they use this then close the window. So notifying the user about documentation after the user adds a folder might be too late.

We should make documentation about workspaces/multi root prominent in the welcome page, our documentation and should include an introductory video on workspaces. We might even consider having an explicit link to the intro video from the welcome page and from the Help menu, at least for the first stable release that contains workspaces.

We should also make sure that we guide people towards the right documentation on workspaces. For example, the first time somebody sees the 'Add folder to workspace command...' they might search for 'workspaces', 'add folder to workspace', 'workspace' etc. We should make sure that these and other search terms will bring somebody straight to an article describing workspaces.

**Comment by bpasero** [comment]
@seanmcbreen @egamma @chrisdias @weinand @kieferrm @gregvanl  your input would be appreciated on the wording of this message:

![image](https://user-images.githubusercontent.com/900690/32010524-5c3e6dca-b9b2-11e7-951f-36a56b4df031.png)

My current thinking is that this message would show up only in the following condition:
* user transitioned from 0 to multi root
* user transitioned from 1 to multi root

This transition goes without window reload and will also be possible to be triggered through extensions (with new API that we plan to release), so it seems fair to tell the user what's going on. My intent is to point the user to our docs ("More Information") where the user can learn about the implications multi-root has (e.g. on extensions).

Feedback welcome.

**Comment by bpasero** [comment]
A small update based on @chrisdias earlier suggestion in https://github.com/Microsoft/vscode/issues/30854#issuecomment-316483966

![image](https://user-images.githubusercontent.com/900690/32056740-bf31c7a2-ba65-11e7-99d9-d415cfedd9ae.png)

**Comment by chrmarti** [comment]
@bpasero I can't trigger the message when running with a new user data dir. I tried:
- Add two folders when starting with an empty window.
- Open one folder and then add a second one when starting with an empty window.

**Comment by chrmarti** [comment]
Got it, had to change the quality in product.json to stable for that. Verified.
