### ISSUE TITLE
dotnet F5 build task issue

### ISSUE THREAD

**Issue by pmcgrath** [Microsoft/vscode#31207]
Note sure if this is for VS Code or the c# extension

My environment:

- VSCode Version:1.14.1
- OS Version: Ubuntu 16.04.2 LTS
- dotnet core Version: 2.0.0-preview2-006497
- c# Extension for VS Code Version: 1.11.0

Steps to Reproduce:

1.dotnet new console
2.code .
3. F5 to launch
4. Picked .NET core as environment
5. Fixed the path to include the output dll i.e. netcoreapp2.0/app.dll in the .vscode/launch.json file
6. F5 to launch
7. Picked .NET Core as the task 
8. F5 to launch

I get a "Error The preLaunchTask 'build' terminated with exit code 129."

The generated tasks.json file content is

```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "taskName": "build",
            "command": "dotnet",
            "type": "shell",
            "group": "build",
            "presentation": {
                "reveal": "silent"
            },
            "problemMatcher": "$msCompile"
        }
    ]
}
```

I needed to change the following content to include the build command

```
            "command": "dotnet",
```

```
            "command": "dotnet build",
```

Should this not be the default ?

**Comment by stephtr** [comment]
Using version "0.1.0" the task name got automatically appended to the command, but not with "2.0.0". So yes, "dotnet build" should be the default.
However as far as I know it is in the responsibility of the C# extension, therefore I created a new issue: [omnisharp-vscode/#1668](https://github.com/OmniSharp/omnisharp-vscode/issues/1668)

**Comment by gregg-miskelly** [comment]
@stephtr I am not sure I follow what you mean in step 4. Are you letting the C# extension generate assets for you by clicking here:

![Info: Required assets to build and debug are missing from your project. Add them? Yes | Close](https://raw.githubusercontent.com/wiki/OmniSharp/omnisharp-vscode/images/info-bar-add-required-assets.png)

Or are you using VS Code's .NET templates?

If you are letting the C# extension generate this, then the OmniSharp-vscode bug you opened is the right one, and we can close this.

If you are using the template from VS Code then I think that template comes from within VS Code itself.

**Comment by stephtr** [comment]
He used the 'configure "launch.json"' option in the Debugging pane (me too):
![Screenshot](https://user-images.githubusercontent.com/5764184/28727710-1d009f84-73c6-11e7-8007-d89ed9c70e29.PNG)
I think that entry originates from the omnicode extension (at least it vanished after disabling the extension).

**Comment by gregg-miskelly** [comment]
@stephtr the content of launch.json comes from the C# extension. But tasks.json does not. I believe it is from here: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/tasks/common/taskTemplates.ts#L17

As an FYI, I would recommend letting the C# extension generate these files instead of using the VS Code templates, as the C# extension can understand your projects.

**Comment by stephtr** [comment]
In the meantime I submitted PR #31678, but in my opinion it would definitely be better to provide the task template via the extension (if that is possible).

**Comment by dbaeumer** [comment]
@stephtr thanks for the PR. The template currently shipped with vscode should use the command "dotnet build". 

The C# extension should contribute tasks to the system. We have now API for this. There is not need to contribute a template since and extension can now contribute task instances directly.

I will close this issue and follow up with the OmniSharp people to contribute tasks.

**Comment by dbaeumer** [comment]
See https://github.com/OmniSharp/omnisharp-vscode/issues/1608
