### ISSUE TITLE
Colorizer. Background highlight per code block

### ISSUE THREAD

**Issue by erichiller** [microsoft/vscode#31220]
This is a feature request for the ability to colorize the _background_ of code blocks, rather than just the text/tokens themselves.  Normally text coloring is quite sufficient, but I have come across situations, namely Python, where the ability to color the current code block/context that my active cursor is in, would be **_extremely_** useful. The styling would be much like the current line highlighting (changing as the cursor moves) but for context. The `contextHighlight` would be inclusive of the start of context and end of context. Certainly language support would have to be there, but currently I don't even see a mechanism to change specific lines' backgrounds. Functionality example below...

Example:

```python
# start of file, start context a
# here my context would be of the file, say context a
# and the entire file would have contextHighlight of a
for i in range(10): # start context b
    # here my context would be context b
    # and have the matching contextHighlight b
    print(i)
    for j in range(5): # start context c
        # here my context would be context c
        # and have the matching contextHighlight c
        print(j) # end context b, end context c
# end context a
```

**Comment by rebornix** [comment]
Technically you can set line decorations for them and you are right, this needs to be language-wise but you can do that in extensions, the API for that is line decoration.  https://marketplace.visualstudio.com/items?itemName=hoovercj.vscode-dimmer is a good example for it.

**Comment by byi8220** [comment]
[Indented Block Highlighting](https://marketplace.visualstudio.com/items?itemName=byi8220.indented-block-highlighting)
I'm about half a year late, but I still didn't find anything that does this on the extension marketplace and I ended up writing something short for this.

This is somewhat simple as it only scans for indentation and no language specific semantics. Python is somewhat tricky because implicit continuations completely ignore whitespace in a language with significant whitespace.

I couldn't figure out how to highlight the **entire** line, only the background of the characters.

**Comment by 199621** [comment]
all i know is lts file
 

    On Saturday, February 24, 2018, 4:10:34 PM EST, byi8220 <notifications@github.com> wrote:  
 
 
Indented Block Highlighting
I'm about half a year late, but I still didn't find anything that does this on the extension marketplace and I ended up writing something short for this.

This is somewhat simple as it only scans for indentation and no language specific semantics. Python is somewhat tricky because implicit continuations completely ignore whitespace in a language with significant whitespace.

I couldn't figure out how to highlight the entire line, only the background of the characters.

**Comment by CodingCreate101** [comment]
How about this??
https://marketplace.visualstudio.com/items?itemName=mihelcic.colored-regions
