### ISSUE TITLE
Configure tasks shows Task creation template when there are provided tasks?

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#31251]
vscode smoke test setup https://github.com/Microsoft/vscode-smoketest-express.git.

- delete the `task.json` file
- execute Tasks>Run Task -> notice that there are provided tasks
- execute Tasks>Configure Task -> a quick pick with task templates is shown:
![image](https://user-images.githubusercontent.com/172399/28491313-4fa412b2-6eef-11e7-886d-bea85a9865cc.png)

I would have expected that I can also configure an existing provided task using quick pick with the provided tasks is shown. One option is to have entry in templates section `Customize detected task` that then shows a quick pick with the detected tasks.

**Comment by dbaeumer** [comment]
This works for me. There is one litte thing to note: Since we change the task execution engine (you delete a tasks.json with version '0.1.0' which now makes 2.0.0 the default you need to reload the Window. There should be a message pointing to this. 

I can investigate of transferring tasks running in the old execution engine into the new one but this is some work which I tried to avoid since I think this is not a very common use case.
