### ISSUE TITLE
How much time Microsoft intends to employ on VSCode?

### ISSUE THREAD

**Issue by evandrocoan** [Microsoft/vscode#31289]
It is very awesome the time employed by Microsoft workers/employers on developing VSCode, however how much time this dream is pretend to last?

As we may known every project has a determinate end, however the software life cycle never dies. There is always the maintenance process the project needs as minor changes and fixes from its dependencies updates, i.e., to be kept up to date with the state of the art.

Currently we may notice heavily contributions from the Microsoft team, but exactly how much time they are going to be present on the project? 

All of them are going to be committed for ever working with VSCode development? I can assume some of the, may be relocated to new projects. But this project is planed to be kept powered by Microsoft for how long and with how many man hours over the time period?

I can think that Microsoft has escalated, set goals of development to be achieved by this project, and after a certain time this project would end and a new project as a maintenance project would be place in action to provided maintenance for the project.

Who am I and why all those questions? I am just curious to see what is on the Microsoft's mind. Thought, I am coming from Sublime Text, a closed source project. I have been developing third part packages for it, but the Sublime Text development team does not bring much confidence on whether they can fix the core problems I have been experiencing. Therefore I am planing to move on to some new project which I can engage and not worry about unsolvable problems as low community support and segmentation faults on the software core.

On this context, or even today's context, the community support (a private team of workers also very welcome), is very important for the tool development not to stop and end up outdated. So here the point is, if I am going to be the only one working it, I am scrolled. Only by myself I cannot accomplish much in my whole life time. Hence where a great overall community support can help to solve the problem and keep the software in awesome shape.

**Comment by rmunn** [comment]
Minor grammatical nit: it looks like you meant "intends", not "pretends", in the title of the question. "Pretends" has a rather different meaning. :-)

As for your main points, I don't work for Microsoft so I can't answer your primary question. But if you look at https://github.com/Microsoft/vscode/graphs/contributors, you'll see a pattern that looks like a pretty healthy open-source project. All the top contributors work for Microsoft, which is not surprising since they're being paid to work full-time on this project. But I sorted the contributors by the number of commits and started clicking on each one, trying to find the ones that don't work for Microsoft. And the top five contributors (in terms of # of commits, at least) who do not work for Microsoft were from:

1. Japan
1. South Africa
1. No country listed, but name appears Russian
1. No country listed, but linked Twitter account is written in Japanese
1. Russia

Source: the GitHub accounts of these five contributors. (I've deliberately omitted their GitHub account names here, because I'm not trying to draw attention to them as individuals, just using them as examples).

This is a good sign. Any project that has attracted interest from around the world, not just from English-speaking countries, is (in my experience, at least) likely to last. And even if Microsoft were to drop the project tomorrow and withdraw all their employees, the fact that the project is MIT-licensed means that there's nothing to prevent the many passionate VS Code users from picking it up and continuing with it. (As happened, for example, with the Netscape browser, which became Mozilla, which became Firefox).

**Comment by chrisdias** [comment]
We are _very_ committed to the VS Code project and to building a healthy ecosystem of contributors and extensions :)
