### ISSUE TITLE
Emmet: Number as a value isn't completed in multiple items

### ISSUE THREAD

**Issue by mirao** [Microsoft/vscode#31382]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:26:08.116Z)
- OS Version: Linux x64 4.10.0-28-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
codeception-snippets|die|0.0.4
githistory|don|0.2.2
php-debug|fel|1.11.1
php-intellisense|fel|1.4.3
AWK|lug|0.0.2
ftp-sync|luk|0.3.3
code-beautifier|mic|1.7.2
mads|mir|0.0.5
HTMLHint|mka|0.3.3
vscode-icons|rob|7.10.1
code-spell-checker|str|1.3.2

---

Steps to Reproduce:

* Enter `table>tr>td{28}*2` and press `TAB`

Expected result:
```html
<table>
    <tr>
        <td>28</td>
        <td>28</td>
    </tr>
</table>
```
Actual result:
```html
<table>
    <tr>
        <td></td>
        <td></td>
    </tr>
</table>
```
String works well:

`table>tr>td{"28"}*2`:
```html
<table>
    <tr>
        <td>"28"</td>
        <td>"28"</td>
    </tr>
</table>
```
Single item with number too:

`table>tr>td{28}`:
```html
<table>
    <tr>
        <td>28</td>
    </tr>
</table>
```

Reproduces without extensions: Yes

**Comment by ramya-rao-a** [comment]
@mirao We are moving to a newer implementation of emmet which is opt-in at the moment and where this issue is already fixed.

You can set `emmet.useNewEmmet` to `true` to try out the new emmet model.

Read https://code.visualstudio.com/updates/v1_13#_emmet-abbreviation-expansion-in-suggestion-list and https://code.visualstudio.com/updates/v1_14#_emmet-abbreviation-improvements to know more about what the new emmet model has to offer.
