### ISSUE TITLE
Buggy kerning for the letters "fil"

### ISSUE THREAD

**Issue by david-cako** [Microsoft/vscode#31417]
Example:

![2017-07-25 16 12 28](https://user-images.githubusercontent.com/19675639/28596257-ebc0f0b8-7154-11e7-8539-bec8d8167d6d.gif)

In this gif, I first try to backspace the _i_, then retype it and try to backspace both the _i_ and the _f_.  I move the cursor to where it looks like it's behind the _f_ and it still deletes the _f_.  It takes one more arrow-key to the left for my backspace to delete the new-line behind the _f_.

- VSCode Version: 1.14.2
- OS Version: 10.11.5

Steps to Reproduce:

1. type `fil` and try to delete characters from it.

Reproduces without extensions: Yes

**Comment by dill0wn** [comment]
Also demonstrable with just `fl`.

**Comment by alexandrudima** [comment]
This is an upstream issue:

Here are the methods we invoke on Chromium - https://jsfiddle.net/x0r2ega6/

```
offset 0: 8
offset 1: 8
offset 2: 18
```

It would be expected that the client rect for character at offset 0 would be different than the client rect for character at offset 1.

Please feel free to report upstream at https://bugs.chromium.org/p/chromium/issues/list and point to the issue here.

**Comment by alexandrudima** [comment]
This is an upstream issue (possibly within Chromium), and there are no known workarounds that we could implement on our side. This means there is no possible code change for us to do in VS Code sources to improve things. 

To keep the number of issues in our inbox at a manageable level, we’re closing issues that have been on the backlog for a long time but haven’t gained traction or that are not actionable. Thank you for your time and understanding.
