### ISSUE TITLE
"esc" the Multi-cursor mode before hide the Find widget please

### ISSUE THREAD

**Issue by zheung** [microsoft/vscode#31422]
- VSCode Version: Code - Insiders 1.15.0-insider (fed03b66ac8acdac93897727a1d19ee0f6898bf2, 2017-07-25T07:30:52.414Z)
- OS Version: Windows_NT x64 10.0.15063

Steps to Reproduce:
1. ctrl+f to show the `Find widget`;
2. alt+shift+up/down or ctrl+click to use `Multi-cursor`;
3. touch the `esc` key to escape the `Multi-cursor`;

Before escape `Multi-cursor`, Code will hide `Find widget` first.
So I need to touch  `esc` two times for escape when `Find widget` is show.
Actually I don't want to hide `Find widget`, only escape `Multi-cursor` I need.

![3](https://user-images.githubusercontent.com/894004/28599925-120d007c-71e1-11e7-9c62-3ccfc6fdf24f.gif)

**Comment by rebornix** [comment]
Actually I think this is the expected behavior, after searching for a word, you may run command "Select All Find Matches" to select all matches in the find scope (for example you have find in selection turned on), then you can press Escape to hide the find widget and continue with the multiple selections.
