### ISSUE TITLE
Autoindent adjusts end-brace to wrong indentation level (JavaScript)

### ISSUE THREAD

**Issue by atombender** [microsoft/vscode#31455]
- VSCode Version: 1.14.2
- OS Version: 10.12.5

![vsc](https://user-images.githubusercontent.com/50314/28625272-f96cdcdc-721b-11e7-9b7d-31f9a1b20b44.gif)

Steps to Reproduce:

* Start with code:

```javascript
try {
  start()
    .catch(err => {
      // ...
    });
```    

* Now type `}` at the end of this snippet.
* It will placed one level deep, instead of being aligned with the outer `}`:

```javascript
try {
  start()
    .catch(err => {
      // ...
    });
  }  // :-(
```

* Manually fixing the indentation level and following up with `} finally {` automatically adjusts the line again, which is frustrating.

Is it because the autoindent support doesn't understand anonymous function syntax?

Reproduces without extensions: Yes

**Comment by rebornix** [comment]
This is due to the limited architecture (regex based indentation rules and only support limited code styles), we may want to consider using formatters if they exist for indenation adjustment (if interested, we can discuss in https://github.com/microsoft/vscode/issues/19847).

For this particular issue, if the indentation rules are leading to more trouble than having no auto indent, you can set `editor.autoIndent` to `advanced` to disable the regex based indentation adjustment. As we don't have an easy good-enough fix for it, we close it for now and explore better solutions through issues like https://github.com/microsoft/vscode/issues/19847.
