### ISSUE TITLE
Cannot invoke an expression whose type lacks a call signature. (Angularjs syntax)

### ISSUE THREAD

**Issue by Leonard1980** [Microsoft/vscode#3148]
VSCode gives a "syntax error" to this Angularjs code:

`var myarrayFiltered = $filter('filterName')(myarray, param);`
or 
`var myarrayFiltered = $filter('filterName')(myarray, param1, param2);`

VScode "syntax error" detail:

> Cannot invoke an expression whose type lacks a call signature.
> Usage: $filter(name);
> (parameter) $filter: ng.IFilterService<{}>(name: string) => {} (+9 overloads)

This kind of errors prevent me from using VSCode as my main editor. Is there an option to turn off "_cannot invoke ..._ " "errors"?

**Comment by egamma** [comment]
The VS Code JavaScript infrastructure will switch to Salsa and it is less agressive with errors. You can enable the Salsa preview, can you pls give it a try, see: https://code.visualstudio.com/Updates#_javascript-salsa-preview

**Comment by felixfbecker** [comment]
@Leonard1980 This has nothing to do with VS Code, but with the typings for Angular. As you can see `$filter` is a generic function that defaults the type argument to the empty object `{}`, which is not callable because it is not a function. The Angular built-in filters are defined with string literal types as overloads, but for your custom service, you would have to provide the type argument, which you can only do in TypeScript. Your options are to use Salsa, ignore the error or remove the typings.

**Comment by egamma** [comment]
Thanks for digging into this @felixfbecker - closing

**Comment by Leonard1980** [comment]
Thanks @egamma  & @felixfbecker, I will try the Salsa preview this weekend.
