### ISSUE TITLE
Boxes shown for missing multiroot file icons

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#31494]
![image](https://user-images.githubusercontent.com/323878/28655422-b70d2d8a-7250-11e7-9d1c-8c62ddc385d6.png)

This is using the Seti UI theme (from the extension) which has a folder icon available.

**Comment by isidorn** [comment]
All the built in extensions work fine. So you are using a Seti UI theme.
The issue is that @aeschli [comment](https://github.com/Microsoft/vscode/issues/30998#issuecomment-316588081) does not seem to be true.

So if the an icon theme does not provide a root icon the folder icon should be used instead.

I checked and https://github.com/hellopao/vscode-seti-icons does not provide a root folder icon.
