### ISSUE TITLE
onDidTerminateDebugSession asymmetry 

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#31580]
testing #31475

We have `onDidStartDebugSession` and `onDidTerminateDebugSession` and I feel that `start` and `terminate` isn't a good couple. Maybe `start` and `stop` or `launch` and `terminate`?

**Comment by weinand** [comment]
we use the "Start" and "Terminate" antonyms because:
- "Terminate" is the terminology from the Debug Adapter Protocol
- "Start" (in favour of "launch") because "start" has to encompass both "launch" and "attach" modes. And using "launch" to start an "attach" configuration (as opposed to a "launch" configuration) is confusing.
