### ISSUE TITLE
vscode doesn't refresh files modified externally

### ISSUE THREAD

**Issue by testing-in-chrome** [Microsoft/vscode#31600]
- VSCode Version: 1.14.2
- OS Version: Ubuntu 14.04

Steps to Reproduce:

1. Open a very large project. 
2. Open one of the files in the editor (possibly several ones? I have about 40 files open now)
3. Either:
    - Modify the file externally, or 
    - Switch to another branch where the file is modified, or
    - Modify the file in the editor, then externally in a terminal stash the changes.
4. Expect that the editor where the modified file is open will refresh - no need to Reload Window.

Reproduces without extensions: Yes.

**Comment by Tyriar** [comment]
@testing-in-chrome do you have `"files.useExperimentalFileWatcher": true` set in your settings.json?

**Comment by testing-in-chrome** [comment]
No, I don't.

**Comment by testing-in-chrome** [comment]
By the way, even adding "files.useExperimentalFileWatcher": true doesn't fix the problem. I have to >Reload Window after every checkout or running clang-format, which is very inconvenient!

**Comment by medreda** [comment]
Same here.
I'm using Ubuntu 17.04.

**Comment by simeyla** [comment]
OK I'm kinda done with VSCode if something like this isn't configurable....
Note: You can actually quit VSCode and make changes externally and the old files will come back when you open VSCode again.

**Comment by vors** [comment]
Same problem, becoming kind of deal-breaker for me.
SublimeText handle this just fine.

**Comment by cdmihai** [comment]
I'm also running into this on Windows on 1.21.1

Hitting refresh from the file explorer does not work, I have to manually close and reopen the file.

**Comment by bpasero** [comment]
@testing-in-chrome 
VS Code is using different file watching strategies depending on your OS and your setup. 

**First thing to check:**
* [ ] I verified that the issue still reproduces in our insiders version (https://code.visualstudio.com/insiders/)
* [ ] I verified that this issue is happening outside of a `node_modules` folder. Our file watcher ignores this folder!

**To find out more about this issue, please first answer this:**
* [ ] What OS are you on
* [ ] Does this happen from an empty workspace, a single-folder workspace or a multi-root workspace?
* [ ] Do you have `files.useExperimentalFileWatcher: true` configured in settings?
* [ ] What is your configured `files.watcherExclude` setting?

**Then please answer the following depending on your setup:**
* [ ] It reproduces with any folder or workspace you open
* [ ] The files/folders you open are on your local disk and not on a network share nor a UNC drive
* [ ] The files/folders you open are not behind a symbolic link
* [ ] The folder(s) opened use the exact same casing as they are on disk
* [ ] It reproduces when I make a change to the file from another VS Code window (either from the editor or the file explorer)

**Then please attach the output of our development console**
* run `code --verbose` from the command line
* perform the action that causes you to not see the file change in VS Code
* attach the output from the console (`Help` > `Toggle Developer Tools` > `Console`)

Thanks for taking the time to fill out this questionnaire.

**Comment by vors** [comment]
Why it got closed? @testing-in-chrome provided all the info, didn't he?

**Comment by nani554** [comment]
**To my Understanding from above discussion**, 
for eg: 
If i create a directive || component || pipe from **cmd** **prompt** and at the same time if the app.module.ts is opened but app.module.ts is not modified according to the changes made externally,
On using below key value
**"files.useExperimentalFileWatcher": true**
now it is modiying the app.module.ts on any external changes. 
So it is working for me.
Sorry if i didnt understand the issue or gave my experience which is not related to this issue

**Comment by pxlhero** [comment]
Any update on this issue?

**Comment by pxlhero** [comment]
Following @Tyriar suggestion and setting `files.useExperimentalFileWatcher: true` fixed this for me. Thank you

**Comment by FabianFrank** [comment]
> Our file watcher ignores this folder!
I would consider an improvement to watch files in node_modules that are in modules that were added using `npm link`. Usually this is done when working on the library and the depending project at the same time. I see why you don't want to watch everything in node_modules, but having to continuously manually open files in VSCode to trigger a refresh is a pretty bad developer experience.
