### ISSUE TITLE
Add option for hiding line numbers in Zen Mode

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#31609]
The title says it all.

`"zenMode.hideLineNumbers": false[default] || true `

**Comment by isidorn** [comment]
We can consider adding this if more users ask

**Comment by DamianPereira** [comment]
Would also be nice to have a similar option to hide minimap, those 2 would make zen mode look the same as atom's, maybe they could be added together?

**Comment by landon9720** [comment]
I too came here looking for a way to disable minimap in zen mode only.

**Comment by usernamehw** [comment]
As a workaround: using 2 extensions [macros](https://marketplace.visualstudio.com/items?itemName=geddski.macros) & [Settings Cycler](https://marketplace.visualstudio.com/items?itemName=hoovercj.vscode-settings-cycler):

`settings.json`
```json
"settings.cycle": [{
    "id": "zen",
    "values": [{
        "editor.minimap.enabled": true,
        "editor.lineNumbers": "on"
    }, {
        "editor.minimap.enabled": false,
        "editor.lineNumbers": "off"
    }]
}],
"macros": {
    "zenMode": [
        "settings.cycle.zen",
        "workbench.action.toggleZenMode"
    ]
}
```
`keybindings.json`
```json
{
    "key": "ctrl+shift+f11",
    "command": "macros.zenMode"
}
```

**Comment by saborrie** [comment]
There are a number of feature requests that are "add/allow X in zen mode"

Would it make more sense to allow zen-mode specific settings in the same way that you can do language specific settings?

Ones like these:

```
"[markdown]": {
    "editor.wordWrapColumn": 120,
    "editor.wordWrap": "bounded"
  },
  "[javascript]": {
    "editor.tabSize": 2
  },
```

For example:
```
zenModeSettings: {
  "editor.lineNumbers": "off"
}
```

**Comment by rchrdnsh** [comment]
I would also like to see this feature added.

**Comment by ShalokShalom** [comment]
https://github.com/Microsoft/vscode/issues/48035

**Comment by chetferry** [comment]
I would also like to see this feature added.

**Comment by bundgaard** [comment]
This would be nice to have, to change zenmode to each own zen preference.
Adding support to hide minimap, line numbers and other gimmicks seems like a given thing to support.

**Comment by amelandri** [comment]
I would also like to see this feature added.

**Comment by ikouchiha47** [comment]
It will be great if it could be configurable to look like Goyo for vim https://github.com/junegunn/goyo.vim

**Comment by bpasero** [comment]
@isidorn fyi I am adding a new `workbench-zen` level to free up some issues from `workbench-layout`.

**Comment by melMass** [comment]
What is the status on that issue ?

**Comment by isidorn** [comment]
This is a subset of this feature request https://github.com/Microsoft/vscode/issues/45617

However since this is the most highly requested zen mode configuration which I missing I am considering to add it without the other issue. 
@bpasero in order to implement this I would need to go over all editors and update the configuration to hide line numbers. However the editor service and the editor group service only give me the IEditorInput to work with. How do I get the IEditor on which I can change options from the IEditorInput?

I can not put this setting into editor land since it belongs to the workbench.

**Comment by bpasero** [comment]
@isidorn there is no API to get all editors that are opened because there is always just one editor open per group that is visible. A tab that is not visible does not allocate any editor widget.

**Comment by isidorn** [comment]
@bpasero thanks. But I would just need to get all the editor widgets (so at most 3). Is there some way to get them? Since hidding line number is an editor thing, not a model thing.

**Comment by bpasero** [comment]
@isidorn [`IEditorService.visibleControls`](https://github.com/Microsoft/vscode/blob/849673a5c9d6832f2adea0fe0cbc64f764098833/src/vs/workbench/services/editor/common/editorService.ts#L91)

**Comment by isidorn** [comment]
@bpasero thanks, I got this working.
The only ugly thing is that I am listening on [`onDidVisibleEditorsChange`](https://github.com/Microsoft/vscode/blob/77882bfffcfcd25400c3b2545df6da5ec028ba30/src/vs/workbench/electron-browser/workbench.ts#L1273) which might be a bit too much.

I decided to go with the default value of true for this. Since I like hiding line numbers and I think it goes perfectly with zen. Also most other zen mode hide options are on by default.

**Comment by isidorn** [comment]
To verify:

1. Make sure turning on zen mode hides all line numers
2. Openeing and closing editors in zen mode keeps line numbers hidden
3. Exiting zen mode makes line numbers shown again
4. You can disable this behavior via `"zenMode.hideLineNumbers": false`

**Comment by bpasero** [comment]
@isidorn yeah this is a bit ugly. ideally we could change zen settings to just be a special mode the workbench is in and all settings are derived from there (this would also prevent us from having to duplicate each setting name with a prefix for zen mode).

We could also think about adding this into the textEditor itself when the editor configuration is computed: https://github.com/Microsoft/vscode/blob/f886dd4fb84bb82478bfab4a68cd3f31b32f5eb5/src/vs/workbench/browser/parts/editor/textEditor.ts#L92

**Comment by isidorn** [comment]
@bpasero as for your first point, that would be covered by this https://github.com/Microsoft/vscode/issues/45617 as I mentioned above.
I want ahead with this feature request because it seems like it is the only one left for zen mode configurations that are highly requested.

Regarding adding it in the `textEditor`, I can do it. But that would require that I add a dependency on the `partService`, that I expose in `partService` something like `isZenModeActive` and the textEditor would have to respect the `zenMode.hideLineNumbers` setting. Or alternativly the `partService` would have something like `areLineNumberHidden` which the textEditor would read out.
Let me know what you think

**Comment by bpasero** [comment]
@isidorn yeah I would not add the partservice dependency, but isn't it just a setting if zen mode is on or not that you could also check?

**Comment by isidorn** [comment]
@bpasero we do not store that in settings, but in local storage. Getting it direct from local storage is ugly, so a dependency to partService would be needed.
Anyways the current solution migth be better even though it is a bit ugly.
