### ISSUE TITLE
Color picker: dismissing the picker with ESC should not apply changes

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#31641]
Refs: #31457

1. Trigger color picker and choose a brand new color
2. Dismiss the color picker using ESC
3. The color should not be applied and you should go back to the original color

Without this I do not see the way to undo your work without using the ugly editor undo.

**Comment by isidorn** [comment]
Yes, `Esc` should remove them all.

**Comment by alexdima** [comment]
We have tried this out in https://github.com/microsoft/vscode/pull/188673 and after using it, it doesn't feel right. The problem is that since 2017, the hover is now focusable. So when interacting with a color in the color picker, the hover gets focus and becomes "sticky" by default. Usually Escape is an action that is non-destructive, so to undo the chosen color would IMHO be an unexpected outcome. To undo the picked color, it is possible to click the original color in the top right:


![image](https://github.com/microsoft/vscode/assets/5047891/c7227c8a-fb21-4871-b0d0-1a4a58cd2169)

**Comment by isidorn** [comment]
This makes sense, thanks for trying it out and for thinking about it.
Also it would break user's muscle memory.
