### ISSUE TITLE
Always show the currently active launch config

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#31745]
In the multi root setup with a client and a server I frequently shift between launching the client and sometimes attaching to the server. After I've attached to the server I often forgot that I did so and then when I launch the client again, then the launching appears to fail, since the server attach launch config is the current one and the Debug viewlet is not visible. For this reason it would be helpful to the user to always see the current launch config in the UI or even better so that the user can always switch the active launch config.

One option is something similar to the git branch switcher in the status bar.

**Comment by isidorn** [comment]
Assigning to august for discussion.

We can show it in the status bar, however do we do this for all cases or only for the multi root experience? Even though the need for it is higher in the multi root case it is also helpful in the single root so being consistent and showing it always is my preffered solution.

Also do we show this only while a debug session is active or always? If always it may prove to be too much noise.
If the user does not have a launch.json configured then I would definetelly not show anything.

I think showing it while a debug session is active for any workspace is the safest path.

**Comment by weinand** [comment]
Let's try to show the selected config in the status bar.
I suggest to show it even if no debug session is running because pressing F5 outside of the debug view is often a guessing game (and the status bar item could solve that).

I do not think that it is worth the effort to hide the item when the debug view is shown (and the selected config is visible in the drop down).

Clicking on the status bar item should open QuickPick with a list of all launch configs.
