### ISSUE TITLE
On several occasions saving files using ctrl-s is delayed.  I can't point to any particular situation where it always occurs but it is very frustrating to press ctrl-s and not having the file being saved immediately.

### ISSUE THREAD

**Issue by DavidKindler** [Microsoft/vscode#31760]
- VSCode Version: Code 1.14.1 (2648980a697a4c8fb5777dcfb2ab110cec8a2f58, 2017-07-13T19:18:47.188Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
vscode-javascript-snippet-pack|aka|0.1.5
project-manager|ale|0.18.1
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.2.11
jquerysnippets|don|0.0.1
beautify|Hoo|1.1.1
vscode-cdnjs|Jak|0.14.3
sublime-babel-vscode|jos|0.2.6
prettify-json|moh|0.0.3
debugger-for-chrome|msj|3.1.6
vscode-versionlens|pfl|0.19.1
subtle-brackets|raf|2.0.2
vscode-icons|rob|7.12.0
sass-indented|rob|1.4.1
jsx|Twe|0.0.1
ReactSnippets|xab|1.4.0
html-css-class-completion|Zig|1.8.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.
