### ISSUE TITLE
Support conditional activation events

### ISSUE THREAD

**Issue by LorenVS** [Microsoft/vscode#31777]
It would be useful for a heavyweight extension to be provide configuration options for when it is activated. 

This has come up in https://github.com/Dart-Code/Dart-Code/pull/399 . The Dart-Code's extension is primarily for .dart files, but there are configuration options that enable functionality for .html files. We're hesitant to activate the extension for all html files, unless that configuration option is set, since it could lead to activating a heavy extension for no real purpose.

I'm not sure if there is prior art for this sort of functionality in package.json, but something like this would be nice:

```
"activationEvents": [
  "if(dart.previewAnalyzeAngularTemplates):onLanguage:html",
  "onLanguage:dart"
]
```

**Comment by LorenVS** [comment]
As an alternative, it would work to have custom activation rules defined in user settings. This would allow a user to opt-in to automatically loading the extension on HTML files. Something like this:
```
settings.json

{
  ...
  "activationRules": {
      "dart-code": [
         "onLanguage:html"
      ]
   }
}

**Comment by DanTup** [comment]
I'm still not entirely sure this is the best fix.. this would still activate the extension for unrelated projects (anything with HTML) - having the flag set doesn't mean every project you open with HTML is AngularDart.

If there's really no better/reliable way to tell the project is AngularDart then I think a better feature request for VSCode would be a way to force an extension to activate for a given workspace folder (similar to your last comment but with no language required, since it'd be in the workspaces settings not general user settings)?
