### ISSUE TITLE
Auto indent doesn't play nice with Google C++ Style Guide

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#31834]
The [Google C++ Style Guide](https://google.github.io/styleguide/cppguide.html) has a few ways of wrapping lines, these could be applies to JS/TS as well but are not that common in those languages. Here these are:

```cpp
// Wrap at the opening paren
GetModuleBaseName(process_handle, modules, process_name, 
                  sizeof(process_name) / sizeof(TCHAR));
GetModuleBaseName(process_handle,
                  modules,
                  process_name, 
                  sizeof(process_name) / sizeof(TCHAR));

// Double indent to indicate wrapped line
GetModuleBaseName(process_handle,modules, process_name,
    sizeof(process_name) / sizeof(TCHAR));
GetModuleBaseName(
    process_handle, modules, process_name, sizeof(process_name) / sizeof(TCHAR));
GetModuleBaseName(
    process_handle,
    modules,
    process_name,
    sizeof(process_name) / sizeof(TCHAR));
```

Both of these styles are not handled well by the auto indent logic. For example, copying this string (\n included):

```cpp

GetModuleBaseName(process_handle, modules, process_name, 
                  sizeof(process_name) / sizeof(TCHAR));
```

Into an empty line will result in:

```cpp
GetModuleBaseName(process_handle, modules, process_name, 
  sizeof(process_name) / sizeof(TCHAR));
```

Notice the single (2) indent adjustment, forcing the user to realign the text (or press undo).

---

Since we know what the indent size is (2), perhaps a good way to accommodate this style of wrapping lines is to notice that the current line has a non-standard indentation and to not be as aggressive as a result. It gets a little complicated when you consider code copied from an external source and pasted in that may have differing rules though.

**Comment by rebornix** [comment]
I thought I can make it less aggressive easily but it turns out to be pretty hard. Usually the reason that you need to adjust the indentation after pasting is because the line you paste the content into may have already have leading whitespaces and it make the indent level incorrect. For example,

let's say we select this content (including the leading spaces of the first line)
```
  GetModuleBaseName(process_handle, modules, process_name, 
                    sizeof(process_name) / sizeof(TCHAR));

```
and pasting into a block

```
if () {
  |
}
```

The result indentation of the first line becomes 4 and we want to adjust it. Then what's the expected indentation of next line? Should we adjust it or honor the existing indentation? For this case, we should leave it there.

However we are copying below content in JavaScript
```
  if (true) {
    console...
  }
```
into
```
if () {
  |
}
```

We would expect auto indent helps adjust the second line for us.

**Comment by rebornix** [comment]
For C/C++ indentation rules, let's track it in #36148, where we have comments/feedback from ms-cpp tools team. As at this moment, our indentation rules for c/cpp are not covering most user case and blocking ppl from productive c/cpp authoring, we removed indentation rules from internal c/cpp support. Please leave messages  #36148 if you have idea about how to improve it, thanks in advance!
