### ISSUE TITLE
[debug] Is StackTraceResponse.totalFrames truly necessary?

### ISSUE THREAD

**Issue by vadimcn** [microsoft/vscode#31851]
The description of `supportsDelayedStackTraceLoading` debug adapter capability stipulates that in order for delayed stack loading to work, the adapter must populate the `totalFrames` field of `StackTraceResponse`.    

However, for native debuggers, this value is not so easy to compute.  For example, when FPO (frame pointer omission) optimization is in play, the debugger may need to load debug info for *all* modules currently on stack, even those at the very bottom which the user probably didn't care about.

Since the total number of frames is never surfaced in the UI, I am wondering whether `totalFrames` is truly necessary.  Wouldn't VSCode know that it has reached bottom of the stack when it receives back less frames than the `levels` it requested?

**Comment by weinand** [comment]
Valid question. We will discuss this...

@isidorn you don't need this, right?

**Comment by isidorn** [comment]
Yes that is correct. However keep in mind the following case
There are exactly 20 frames: vscode gets all of them since we fetch 20 and display the "load more stack frame" button. If the user clicks on that button no more frames will be loaded -> just that button will disapear.

I am fine with this corner case, but just to be aware of it.

**Comment by vadimcn** [comment]
And if anyone does care, you could ask for 21 frames, but display 20.

**Comment by isidorn** [comment]
@weinand do we want to do something here? Assigning to November and debt so we discuss.

**Comment by DanTup** [comment]
Any plans for this? I'm trying to optimise something too, and knowing the full count of frames is more expensive than not. Including a boolean in the response to say the frame list was truncated is another way around the issue described above (to avoid asking for one more than required and letting the DA do it however it sees fit).

**Comment by DanTup** [comment]
I noticed that VS Code updates its count from `totalFrames` each time it fetches a batch. So - although it's not to-spec - I found this can be worked around by always telling VS Code there are `n` more frames than the last one it asked for. When it asks for those next frames, add `n` again (setting `n` to `20` seems good since it matches the original batch size).

The only niggle is that the expand text says "Fetch all stack frames" when it only fetches the next batch - however it does render nicely and provide the fetch link again on the next round trip.

So potentially this issue could be resolved by just documenting this (that a client should always use the latest `totalFrames` it was given) and changing the "Fetch all stack frames" text to maybe say "Fetch more stack frames"?

(I may ship this anyway, understanding it may break and need updating/reverting, as the gains from not having to compute the full stack length up-front can be significant in some scenarios).

**Comment by weinand** [comment]
I agree, we should relax the need for `StackTraceResponse.totalFrames` to be exact (because determining that value might be expensive).
On the other hand I do not want to introduce another backward compatible property or even a capability for this.
And since we have recently changed the action's text to "Load All Stack Frames", I would like to keep it like this unchanged...

So the only remaining option is to document how the current properties and capabilities can be used in a way that results in the desired behavior.

First lets describe the behavior observed in VS Code:
- setting `StackTraceResponse.totalFrames` to a huge value (e.g. 100000), works fine if the real number is larger than the chunk size (20). If it is smaller than 20, then the "Load All Stack Frames" action is shown even if the last `stackTrace` request did return less frames than requested. I think this is a bug in VS Code.
- setting `StackTraceResponse.totalFrames` to the value `startFrame + levels + 20` works fine and results in a paged behavior even after VS Code's recent change to fetch the rest of the stack when pressing the "Load All Stack Frames" action once.

Proposal:
TBD

**Comment by isidorn** [comment]
Makes sense to me. If we decide to go down this route, feel free to create a new issue and assign to me so I can look into fixing this issues.

**Comment by weinand** [comment]
I've created https://github.com/microsoft/debug-adapter-protocol/issues/162 with a proposal for improving the descriptions of the DAP `stackTrace` request and its `totalFrames` property.
