### ISSUE TITLE
Moving line past switch statement removes indentation in that

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#31864]
- VSCode Version: Code - Insiders 1.15.0-insider (f39385b8326671dc6389f21f8c2e2f6afdb352a1, 2017-08-01T05:07:59.267Z)
- OS Version: Darwin x64 16.6.0
- Extensions: none
---

Testing #31831

Moving a line past a switch statement:
![movinglinethroughswitch](https://user-images.githubusercontent.com/9205389/28846831-c063158c-76c1-11e7-8f6c-ae9fb458845b.gif)

Text:
```js
var foo = 1 + 2;
switch (foobar) {
    case 1:
        var a = 2;
        break;
    case 2:
    default:
        var b = 4;
        break;
}
```

**Comment by rebornix** [comment]
This is due to the limited architecture (regex based indentation rules and only support limited code styles), we may want to consider using formatters if they exist for indenation adjustment (if interested, we can discuss in https://github.com/microsoft/vscode/issues/19847).

For this particular issue, if the indentation rules are leading to more trouble than having no auto indent, you can set `editor.autoIndent` to `advanced` to disable the regex based indentation adjustment. As we don't have an easy good-enough fix for it, we close it for now and explore better solutions through issues like https://github.com/microsoft/vscode/issues/19847.
