### ISSUE TITLE
Using an invalid tsdk appears to break version selector

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#31875]
- VSCode Version: Code - Insiders 1.15.0-insider (f39385b8326671dc6389f21f8c2e2f6afdb352a1, 2017-08-01T05:10:12.703Z)
- OS Version: Linux x64 4.10.0-26-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.9.4
lorem-ipsum|Tyr|1.0.0
shell-launcher|Tyr|0.1.1
vscode-terminal-here|Tyr|0.0.5
vscode-svgviewer|css|1.4.2
tslint|eg2|0.17.0
git-project-manager|fel|1.3.2
md-navigate|jri|0.0.1
vscode-scss|mrm|0.6.2
cpptools|ms-|0.12.1
seti-icons|qin|0.1.3

(3 theme extensions excluded)

---

Testing #31785 

I set the tsdk to an invalid path (as it contained `~`). When I tried to set it to a proper path, it was not refreshing the list of tsdk's available.

![image](https://user-images.githubusercontent.com/2193314/28851128-84828a3e-76d5-11e7-9961-6ea0d4f57c7b.png)

After further experimentation it appears to be related to setting an invalid path and not being able to "switch" from VS Code's version to the correct VS Code's version.

**Comment by mjbvz** [comment]
This is the current behavior and by design. We present invalid `tsdk` values in the selector but prompt the user to fix the setting and fall back to the bundled TS version if they attempt to select an invalid one. That the path is invalid is now more clearly indicated in the selector:

![screen shot 2017-08-01 at 4 37 34 pm](https://user-images.githubusercontent.com/12821956/28851514-e539ec62-76d7-11e7-8aa2-1db3fa092e0e.png)
