### ISSUE TITLE
There are 2 active items in the TS version selector

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#31876]
- VSCode Version: Code - Insiders 1.15.0-insider (f39385b8326671dc6389f21f8c2e2f6afdb352a1, 2017-08-01T05:10:12.703Z)
- OS Version: Linux x64 4.10.0-26-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.9.4
lorem-ipsum|Tyr|1.0.0
shell-launcher|Tyr|0.1.1
vscode-terminal-here|Tyr|0.0.5
vscode-svgviewer|css|1.4.2
tslint|eg2|0.17.0
git-project-manager|fel|1.3.2
md-navigate|jri|0.0.1
vscode-scss|mrm|0.6.2
cpptools|ms-|0.12.1
seti-icons|qin|0.1.3

(3 theme extensions excluded)

---

Testing #31785 

I was playing with various user settings and swapping between the 2. (I'm assuming the dot means "active")

![image](https://user-images.githubusercontent.com/2193314/28851248-286480a8-76d6-11e7-907c-f3dcf57c4f32.png)

**Comment by ramya-rao-a** [comment]
@mjbvz What are the repro steps for verification?

**Comment by mjbvz** [comment]
To verify:

1. In a new workspace, install typescript locally so that you have two entries in the version selector.
1. set your user `typescript.tsdk` setting to `./node_modules/typescript/lib`
1. Run the version selector again
1. Try switching between the workspace and vscode version. There should only ever be one marked even though these versions are the same
