### ISSUE TITLE
We should have a unique type for a root folder in the internal API

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#31906]
I saw @isidorn work on the configuration resolve service today and I propose that even for the internal APU we introduce a unique type for a root folder instead of passing it around as a URI. This makes it more clear what is required. It is like having a URI and not passing a string around.

**Comment by dbaeumer** [comment]
What do you think?

**Comment by isidorn** [comment]
I think this might overcomplicate things and not sure what are the actual benefits. Sure in the configuration reslover api I think it makes sense since it always needs to get a root, however other services usually deal with resources.

Also adding @sandy081 since we should also consider the settings story (it is currently based around resources which are uris and do not have to be root uris). [More details](https://github.com/Microsoft/vscode/blob/isidorn/next/src/vs/platform/configuration/common/configuration.ts#L25)

**Comment by dbaeumer** [comment]
I agree that services that deal with resources should take a URI (since it can be any resource). Services that take a workspace root folder should take something of a different kind than URI.

**Comment by weinand** [comment]
+100!
In the extension API we already made the step of introducing a WorkspaceFolder type instead of using the somewhat fuzzy URI. The most important attribute on WorkspaceFolder is probably "name" which today extracts the name from the URI, but as soon as we introduce an alias name, will return the alias name. I do not see a decent way to surface the alias name on a URI.

**Comment by bpasero** [comment]
@dbaeumer there is `IWorkspaceContextService.getWorkspace()` returning an instance of `IWorkspace` which has a name property. What else did you have in mind? You are free to pass this object around if you want to make your API more explicit.

**Comment by weinand** [comment]
We are talking about the "roots" of an IWorkspace. As you can see in the interface above "roots" are just URIs and not IWorkspaceFolders.

**Comment by dbaeumer** [comment]
Agree this @weinand comments. I would like to see roots being of type IWorkspaceFolder with an URI and a name.

**Comment by bpasero** [comment]
One thing we tried is to keep the workspace object serializable via renderer and extension host. If we decide to introduce real objects here we have to make sure that they serialize properly on the other side. 

I think keeping the internal and external API somewhat in sync makes sense, but I do not have a strong opinion because currently there is not a lot of metadata associated to a root. If this changes (e.g. by having more metadata like name) we should make the move.

**Comment by dbaeumer** [comment]
I strongly opt to make the move now simply to make our internal API more explicit as well. The configuration resolve service takes an URI as a root now also it should take a IWorkspaceFolder. It doesn't make any sense to pass in an arbitrary URI. Should the resolve service throw then ? It is like us not passing around a string for an URI :-)

**Comment by bpasero** [comment]
@dbaeumer yeah sorry for being out on vacation and not up to speed with what @isidorn did in the resolver service.

**Comment by dbaeumer** [comment]
@bpasero thanks for reconsidering. Let me know if I can help.

**Comment by isidorn** [comment]
Ok back from vacation. We can look into using an IWorkspaceFolder in the configuration reslover service. However I would do this after endgame next week if nobody is depending on this this week.

**Comment by isidorn** [comment]
Now configuraitonResolverService takes a WorkspaceFolder which @sandy081 recently introduced.
@dbaeumer fyi https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/tasks/electron-browser/terminalTaskSystem.ts#L649
