### ISSUE TITLE
Warning on all settings.json: `$ref 'definitions/length' in {1} can not be resolved'

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#31932]
All settings.json files show this warning:

![image](https://user-images.githubusercontent.com/323878/28893044-e56af8ea-7784-11e7-923f-b3ca0125f21b.png)

**Comment by roblourens** [comment]
This issue was moved to hoovercj/vscode-power-mode#9

**Comment by hoovercj** [comment]
@roblourens I think there is still a vscode bug here. The error says "in {1}". Shouldn't vscode actually output what the {1} is, at least?

**Comment by roblourens** [comment]
Possibly, the warning comes from here - https://github.com/Microsoft/vscode-json-languageservice/blob/master/src/services/jsonSchemaService.ts#L408

If you know what's triggering it in vscode-power-mode, I can investigate some more.

**Comment by hoovercj** [comment]
In this line:
`resolveErrors.push(localize('json.schema.invalidref', '$ref \'{0}\' in {1} can not be resolved.', linkPath, linkedSchema.id));`

The first placeholder is escaped but the second isn't. Is it a simple.matter of changing the line to:

`resolveErrors.push(localize('json.schema.invalidref', '$ref \'{0}\' in \'{1}\' can not be resolved.', linkPath, linkedSchema.id));`

**Comment by roblourens** [comment]
There are escaped quotes around the placeholder, but the placeholder doesn't need to be escaped.

**Comment by hoovercj** [comment]
Ok, I see now that the escaped quotes around the first placeholder are simply cosmetic and there does not need to be escaped quotes around the second placeholder.

Based on that line, though, it appears that something is preventing `{1}` from being replaced with the value of `linkedSchema.id`, or perhaps that value is undefined due to a vscode bug or, more likely, an error in my schema and that prevents the placeholder from being replaced.

I didn't write the schema myself, I found it from [here.](https://github.com/rcorp/css-schema/blob/master/csstagschema.json)

I've gone in and added an `id` property at each spot in the schema that is using the `length` definition but I still get the error.

So I've reduced it to the minimal repro below (I added the id's hoping they would help but they did not):

What extra information is needed to make this schema valid? And can the vscode side of things be improved to make the error more useful in this scenario?

```
"powermode.customCss": {
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "CSS Schema",
  "id": "CSS Schema",
  "definitions": {
    "length": {
      "id": "length",
      "type": "object"
    }
  },
  "type": "object",
  "properties": {
    "border-radius": {
      "id": "border-radius",
      "$ref": "#/definitions/length"
    }
  }
}
```

**Comment by roblourens** [comment]
Now I see `'$ref '/definitions/length' in 'vscode://schemas/settings' can not be resolved.'` which is an improvement, but it doesn't give any hint to which setting or extension is causing this, which is the real frustration. Is that possible to do?

**Comment by aeschli** [comment]
I don't see a way to improve that as the JSON extension only sees one big schema. 
I guess the only way would be to add validation to prevent $ref in the contribution point handler. But we don't want to rebuild the schema logic there.

**Comment by bpasero** [comment]
I am also seeing this in latest insider, is there any help how to get out of it?

![image](https://user-images.githubusercontent.com/900690/29926953-29b1c6fe-8e65-11e7-8e2f-e82f2fdeab98.png)

**Comment by aeschli** [comment]
hoovercj/vscode-power-mode needs to fix this. It must not use $ref in the configuration contribution.

**Comment by bpasero** [comment]
@aeschli thanks, that helped

**Comment by hoovercj** [comment]
I'm flattered that some of you have my extension installed and I'm sorry that it's spamming your `settings.json` files. I thought the fix by @aeschli was going to give more information about what was wrong with the way my $ref was being used so I could fix it in my `package.json`. But now it sounds like $ref isn't supported at all in the `package.json` so I'll simply remove it and push an update tonight.

I'm confused, though, I must have misunderstood the comment by @aeschli here: https://github.com/Microsoft/vscode/issues/30762#issuecomment-321539637

> Your settings must only use the configuration contribution point....$ref should only use external refs or relative refs.

I am using the configuration contribution point and I am using a relative $ref.  If $ref is not supported in `package.json`, it should be documented [here](https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributesconfiguration). Or if it isn't supported anywhere, it should be documented 
 [here](https://code.visualstudio.com/docs/languages/json#_json-schemas-settings).

**Comment by aeschli** [comment]
@hoovercj Sorry for my conflicting statement. 
`#/definitions/length` is an absolute reference (to the root of the configuration file schema), and I just realized that there is nothing like a $ref that is relative to where the $ref is used. The current thinking is that we are going to restrict what can be used in the configuration contribution point.  It gets too complicated there otherwise.

**Comment by hoovercj** [comment]
Thanks for the clarification. I understand now that it is not possible. Now the error should be gone :-)
