### ISSUE TITLE
Clicking on LR / CRLF on the bottom brings up the menu at the top

### ISSUE THREAD

**Issue by rsmolkin** [Microsoft/vscode#32038]
When clicking on LF or CRLF on the bottom of the screen in the blue line, the menu to change it to the other line end type comes up all the way at the top of the screen.  That doesn't make any sense if I'm clicking on the bottom and looking at the bottom, the menu should come up next to the area I clicked on, not in a completely different area of the screen.

**Comment by rebornix** [comment]
@stevencl I remembered we already have a few issues talking about the same thing, look forward to your insights on this.

**Comment by stevencl** [comment]
Yes, this has come up in previous discussions I've had with @bpasero and is something we generally would like to do. I don't know if we have the infrastructure in place right now for this to be a straightforward fix for all such elements in the status bar though. We would obviously want to make this improvement for every appropriate command in the status bar, rather than one at a time.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/29193
