### ISSUE TITLE
Button positioning change [polish]

### ISSUE THREAD

**Issue by ecllipsers** [Microsoft/vscode#3203]
The close button in the feedback dialog is wrongly positioned (try highlighting the dialog by clicking, then hovering the button).

**Comment by alexandrudima** [comment]
To keep the number of issues in our inbox at a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: we look at the number of votes the issue has received and the number of duplicate issues filed. Thank you for your time and understanding.

If you disagree and feel that this issue is crucial: we're happy to listen and to reconsider.
