### ISSUE TITLE
Wrapped lines lead to wrong problems

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#32042]
- VSCode Version: Code - Insiders 1.15.0-insider (6feff11ed03402cf77e04e74e13c55529fdb4d09, 2017-08-04T17:53:03.136Z)
- OS Version: Windows_NT x64 10.0.15063

The windows smoke test fails on https://github.com/Microsoft/vscode/blob/master/test/smoke/src/tests/tasks.ts#L51.

The reason for this is that the terminal is wrapping the error message and the problem matcher only picks up the wrapped part of the line:

<img width="791" alt="screen shot 2017-08-04 at 3 14 34 pm" src="https://user-images.githubusercontent.com/4674940/28989036-c130c226-7927-11e7-91d7-5cc3a1981b97.png">

<img width="809" alt="screen shot 2017-08-04 at 3 14 50 pm" src="https://user-images.githubusercontent.com/4674940/28989040-c646613a-7927-11e7-84ab-b4c526523535.png">

**Comment by roblourens** [comment]
I think it needs https://github.com/Microsoft/vscode/issues/29840#issuecomment-315145714

**Comment by roblourens** [comment]
It looks like the terminal task runner isn't getting unwrapped lines on windows - I think this is essentially what the discussion at https://github.com/Microsoft/vscode/issues/29840#issuecomment-315145714 is about.

**Comment by Tyriar** [comment]
Pretty sure this is not a regression and applies to all platforms.

**Comment by dbaeumer** [comment]
@Tyriar from your comment here https://github.com/Microsoft/vscode/issues/29840#issuecomment-315145714 I expected to get unwrapped lines. 

If I still get wrapped lines can we tackle this using the workaround I proposed in https://github.com/Microsoft/vscode/issues/29840#issuecomment-315145714

**Comment by kieferrm** [comment]
@Tyriar FYI the problem was not reproducible on macOS.

**Comment by dbaeumer** [comment]
@Tyriar I tested this under Windows and I still get the wrapped lines with the latest insider build. Executing a task in the terminal in cmd.exe produces this in the terminal:

<img width="500" alt="capture" src="https://user-images.githubusercontent.com/1931590/29684542-a586fe14-8912-11e7-9777-7e79c2089694.png">

and captures this problem

<img width="507" alt="capture" src="https://user-images.githubusercontent.com/1931590/29684561-bac256a2-8912-11e7-9b81-7a200daaeb45.png">

Is there anything I can do to workaround this.

**Comment by Tyriar** [comment]
Not that I'm aware of, we get the data from winpty pre-wrapped.

**Comment by dbaeumer** [comment]
Unhappy :-( Would this need the view model discussed in #29840

**Comment by Tyriar** [comment]
I think it's just a limitation of how winpty works; it will try wrap the content based on the width of the terminal. I think there is some other issue that was discussing how PowerShell formats things in these tables but then wraps text in the table cells, this is similar to that.

**Comment by dbaeumer** [comment]
I disagree. Also both wrap, in PowerShell I can control whether the output is a table or not. If I use the output table style in PowerShell I expect it to be wrapped (I asked for it). For me this is comparable to asking the editor for a line and the editor returns me the wrapped content. As a user of that API it makes it almost impossible to program against this.

Would it be possible to somehow `annotate` the inserted new lines with a custom control sequence. Then at least it would be clear to the consumer of the API that it should ignore the new lines. I would really appreciate if we can find a solution for this since it makes using tasks in the terminal unnecessary hard.

**Comment by dbaeumer** [comment]
@Tyriar  Can we please move the item back to a milestone?

**Comment by Tyriar** [comment]
@dbaeumer as I mentioned in https://github.com/Microsoft/vscode/issues/26807#issuecomment-327969788, i'll be busy through September but I'm going to be making this a priority in the October iteration.

**Comment by Tyriar** [comment]
@rprichard I just looked into this a bit and came across https://github.com/rprichard/winpty/issues/21, I think that's describing the same issue that we're having. xterm.js supports wraparound mode (DECAWM) and expects that single lines do not wrap themselves. Since xterm.js wraps the lines itself, it knows what the full unwrapped line is which can enable integrations like above.

To be clear, xterm.js expects no special characters between lines when they wraps in order for wraparound mode to work, not `\n\r` which winpty reports. Could an option be added potentially to amend this behavior?

Here is the code in xterm.js that handles wrapping:

https://github.com/sourcelair/xterm.js/blob/575c10114be5002b45d4d7842a6f8741ba87f5e3/src/InputHandler.ts#L54-L72

**Comment by rprichard** [comment]
winpty gets console buffer data from `ReadConsoleOutputW`, which doesn't distinguish between a wrapped line of output and two lines separated by explicit line breaks. Some sort of heuristic might improve the situation, but maybe it'd also make winpty's behavior harder to understand.

**Comment by dbaeumer** [comment]
@rprichard thanks for the explanation.

Now that I know how that works we might need to approach this differently since 'unwrapping' these lines in winpty might do wrong things and lead to false positives.

I would propose that the terminal in VS Code in some way gives me access to the 'rendered' lines and the current wrapping column. Then the problem matcher could do the following algorithm (not fully thought through though):

- consume a line. If length of the line === terminal width add it to a buffer. 
- continue with this until a line is consumed with length !== terminal width
- try to match whole buffer as a single line. If that fails, take the last line off and match that line and the rest of the buffer. If that fails take another line off and do that same until the buffer is empty.

**Comment by Tyriar** [comment]
@dbaeumer I tried to do something like your proposed workaround yesterday and it kind of worked. I may have done something wrong though. I'll go ahead with something like this at the xterm.js level when I free up 👍 

Here are the relevant bits of code:

- Where Unix wrapping happens: https://github.com/sourcelair/xterm.js/blob/948eedba8988bcdc499f816df5aa838492e7c18d/src/InputHandler.ts#L64
- Maybe where the Windows workaround should go: https://github.com/sourcelair/xterm.js/blob/948eedba8988bcdc499f816df5aa838492e7c18d/src/InputHandler.ts#L126

**Comment by dbaeumer** [comment]
@Tyriar thanks for looking into this. Let me know when there is API I can start to use and I will try to implement the proposal in the problem matcher.

**Comment by dbaeumer** [comment]
@Tyriar any news on this. I there new API I could use to implement the algorithm I outlined here: https://github.com/Microsoft/vscode/issues/32042#issuecomment-328046581

**Comment by dbaeumer** [comment]
@Tyriar I looked at the new line data listener and it looks promising. However there is one thing I would like to see add to make it work nicely. The listener should fire with the last line when the process terminates. This ensures that no data is lost even if the last line doesn't end with a CR

**Comment by dbaeumer** [comment]
@Tyriar  just to be sure that I understand `onLineData` correctly. If a process outputs a line in the terminal and that line is split onto three lines when rendered in the terminal the `onLineData` listener is fired three times. Is this correct (this is at least what my demo case shows).

Assuming it is I would need an additional API to read the width of the terminal to implement the proposal from here:  https://github.com/Microsoft/vscode/issues/32042#issuecomment-328046581

Could you add this?

**Comment by Tyriar** [comment]
@dbaeumer for a line that is wrapped into three lines, `onLineData` will only fire once when the LF character is parsed at the end of the 3rd line.

I'm guessing (hoping) you're testing this on Windows as it doesn't work there yet until this issue is closed. I have a work in progress on https://github.com/Tyriar/xterm.js/tree/winptyCompat for working around the wrapped line problem on Windows which should make it act more like macOS/Linux. You can test your `onLineData` prototype on Linux and macOS in the meantime.

**Comment by dbaeumer** [comment]
@Tyriar great. That will make my live easier and yes I was testing this on Windows recognizing the new API today.

Can you also comment on the request to send the last line when the process terminates?

**Comment by Tyriar** [comment]
@dbaeumer yeah that makes a lot of sense to do that, working on it now

**Comment by Tyriar** [comment]
@dbaeumer done, let me know if you find any issues with it.

**Comment by Tyriar** [comment]
This should work in the next Insiders when you're using the new `onLineData` api (https://github.com/Microsoft/vscode/issues/29840), it's not perfect as it's just guessing where lines should wrap on Windows, but should cover most of the cases. See https://github.com/sourcelair/xterm.js/pull/1096 for impl details.

**Comment by dbaeumer** [comment]
@Tyriar Thanks !
