### ISSUE TITLE
Search box is transparent on uncuaght exception

### ISSUE THREAD

**Issue by nonameolsson** [Microsoft/vscode#32093]
Search box is transparent, makes it hard to see.
![screen shot 2017-08-07 at 11 03 37](https://user-images.githubusercontent.com/1493018/29035261-83a6057a-7b60-11e7-9a4f-b2a5d9e21c8d.png)

- VSCode Version: 1.15.0 Insiders
- OS Version: MacOS 10.12.5

Steps to Reproduce:

1. Start debugging
2. Provoke a uncaught exceptions
3. Open search box 

Reproduces without extensions: Yes

**Comment by rebornix** [comment]
This happens when we have two overlays and they cover each other, we don't have any logic to avoid that, same reason as content widget https://github.com/Microsoft/monaco-editor/issues/524#issuecomment-321543392 . It looks like the red exception window is transparent, this is by design right ? @isidorn

**Comment by isidorn** [comment]
@rebornix yes it is transparent by design, but I can look in September into changing that.

**Comment by mjbvz** [comment]
Verified that the error background is no longer transparent. However if a theme changes `debugExceptionWidget.background` to transparent, you can still run into this problem
