### ISSUE TITLE
vscode.window.activeTextEditor is undefined for files larger then 5MB

### ISSUE THREAD

**Issue by GreenRover** [Microsoft/vscode#32118]
I wrote an Visual Studio Code extension. Based on this example: https://github.com/Microsoft/vscode-extension-samples/tree/master/previewhtml-sample

        var editor = vscode.window.activeTextEditor;
        if (!editor) {
            console.log("No open text editor");
        }
This works fine if i open a 2MB File. But not if the file is 5MB or larger.

But if i copy (CTRL+C,CTRL+V) a 10MB into a new editor it will work and is prety fast. Has anyone an idea what kind of limitation this is?

**Comment by alexandrudima** [comment]
When we open a file (and only when opening it), we classify it:

* if the file is over 30MB or over 300k lines, we consider it to be a very large file and proceed to turn off very many features, including tokenization, word wrapping, indent guides, anything that would consume additional memory, etc.

* if the file is over 5MB, we consider it to be a large file and we actively hide it from the extension host: this reduces the feature set for such files (e.g. go to definition, find all references will not work, etc.), but leaves some basics working: tokenization, link detection, word suggestions, etc.

* otherwise, the file is considered to be a normal file and suffers no restrictions.

We have implemented these graceful degradation limits based on our experience in dealing with large files. i.e. we have found very many language servers struggle with file sizes above 5MB so we decided to introduce a limit at the extension host layer.

This classification can be circumvented by editing a file. i.e. start with a small file, and then use ctrl+c ctrl+v to increase it to a size above 5 MB, etc. The above classification is made only when the buffer is created.

**Comment by GreenRover** [comment]
In case of a LARGE file: Is it possible for an extension to get whole file contenst?

**Comment by alexandrudima** [comment]
No, I'm sorry, opened files over 5MB are currently completely hidden from the extension host.

I believe we took this decision at a time before we had such a rich extension ecosystem and it is perhaps time to revisit it. i.e. we should consider removing this restriction and push the responsibility of dealing in a smart way with large files down to the extensions themselves.

**Comment by GreenRover** [comment]
Hi can you tell me the variable where the 5MB is stored in to let me hack my local vs code?
Or is there an way to just get the path of the file that is currently in focus?

**Comment by alexandrudima** [comment]
@GreenRover Here's the location: https://github.com/Microsoft/vscode/blob/88be6de0b7ac0ac787a6ea9c472c1d7b2ca2d380/src/vs/editor/common/model/textModel.ts#L33

In the built `workbench.main.js` you could look for `MODEL_SYNC_LIMIT`

**Comment by GreenRover** [comment]
Hi a changed this value in workbench.main.js and tryed to open a 21MB file but it failed.
Are there other limitations?

**Comment by alexandrudima** [comment]
No, that single constant is responsible for the limitation.

@jrieken I suggest I simply increase the constant.

**Comment by jrieken** [comment]
> I suggest I simply increase the constant. Did we ever document the limitation? 

I don't think  so

**Comment by alexandrudima** [comment]
I increased the limit to 50MB
