### ISSUE TITLE
Suggestion: Open debug view automatically when hitting a breakpoint or exception

### ISSUE THREAD

**Issue by dlebu** [Microsoft/vscode#32150]
Steps to Reproduce:

1. Create a simple hello world program for node js.
2. Add configuration.
3. Go back to file view tab from the debug view tab.
4. Add a breakpoint.
5. F5

Expected:
VSCode switches to debug view when hitting breakpoint - I want to be able to see the callstack pane.

Actual:
VSCode hits breakpoint, but does not show the callstack (still in file view tab).

**Comment by isidorn** [comment]
We try not to change vscode ux state too much automatically.
Currently we open the debug viewlet when the debug session starts, but doing this on every breakpoint hit can be annoying - what if the user actually wants to have the explorer revelead and the debug viewlet constantyl gets opened.

Due to the reasons above closing as will not fix
