### ISSUE TITLE
Context-aware intellisense

### ISSUE THREAD

**Issue by kingdaro** [Microsoft/vscode#32170]
Atom's autocomplete-plus has a feature which allows sorting suggestions by a "locality bonus", meaning that symbols in the document that are closer to the cursor are more likely to show up first.

For example, when I type "req" in a node file, the first thing that shows up is "requestAnimationFrame", when I usually want "require" instead. With this "locality bonus", "require" would end up being the first thing to show up, since it's found in the current file already, and probably only a line higher or lower. "requestAnimationFrame" would get pushed lower, since it's not in the file at all.

Apologies in advance if this is a duplicate, or if it's already implemented. I've searched and haven't seen any issue touching particularly on context awareness. It's one of the few features I miss from Atom.

**Comment by jrieken** [comment]
Interesting, tho also spawning across extensions... In our world the first sort order depends on the suggestion provider (`sortText`) and we have seen requests against different extensions to sort by locality, like locals vs globals. In the same spirit textual suggestions can be improved. However, to implement this broadly the API should be extended to include the definition of a symbol being inserted and the us doing some uniform locality sort.

**Comment by dedmazayukr** [comment]
Similarly, when I write on node.js then instead of "require" the first in the list is "requestAnimationFrame", and no matter how much I select "require" the same thing every time.
![screenshot from 2018-07-16 00-30-02](https://user-images.githubusercontent.com/22115961/42738654-d442abc2-888f-11e8-9417-e38c5567f0a4.png)

**Comment by jrieken** [comment]
@dedmazayukr Can you try this with the setting `"editor.suggestSelection": "recentlyUsedByPrefix",`?

**Comment by dedmazayukr** [comment]
Thanks for Your reply, Jricken, this partly solve the problem. Although it is strange why the in note.js requestAnimationFrame constantly in the top place: 
![screenshot from 2018-07-16 11-29-06](https://user-images.githubusercontent.com/22115961/42749181-8b0b45fc-88eb-11e8-8ccb-b8150f1be6d4.png)

**Comment by jrieken** [comment]
This will land in September behind a new setting: `"editor.suggest.localityBonus": true`. With that sorting of suggestion depends on (in that order)

1. how well it matches the current prefix
2. the locality 
3. the sort order assigned by the extension

The locality itself is computed by the enclosing scope, think of {}-blocks in c-style languages. See the attached screen shot below. The suggestion `wzz` wins because it's inside the same scope, the outer scope has `ware` and `wert`, both have the same 'distance' and there the extension sort order (alphabetical) comes into play.

<img width="716" alt="screen shot 2018-09-24 at 14 40 29" src="https://user-images.githubusercontent.com/1794099/45952660-028f0980-c008-11e8-9d90-6d40cfbea0a2.png">

**Comment by igolskyi** [comment]
@jrieken does it work only in the insider version, for the present?

**Comment by igolskyi** [comment]
> This will land in September behind a new setting: `"editor.suggest.localityBonus": true`. With that sorting of suggestion depends on (in that order)
> 
> 1. how well it matches the current prefix
> 2. the locality
> 3. the sort order assigned by the extension
> 
> The locality itself is computed by the enclosing scope, think of {}-blocks in c-style languages. See the attached screen shot below. The suggestion `wzz` wins because it's inside the same scope, the outer scope has `ware` and `wert`, both have the same 'distance' and there the extension sort order (alphabetical) comes into play.
> 
> <img alt="screen shot 2018-09-24 at 14 40 29" width="716" src="https://user-images.githubusercontent.com/1794099/45952660-028f0980-c008-11e8-9d90-6d40cfbea0a2.png">

@jrieken it's cool, but is it work only in the insider version, for the present?

**Comment by igolskyi** [comment]
@jrieken it's cool, but is it work only in the insider version, for the present?

**Comment by igolskyi** [comment]
Awesome! Updated today Good work, thank you.

**Comment by singuerinc** [comment]
@jrieken Is is possible to get the same kind of behavior for the "open file palette" (not sure if is called in that way) based on file proximity to the file that is opened?

Let's me explain, the problem is when you have a bunch of files with the same name in different folders:

```
- component-1
--- index.ts
--- component.tsx
- component-2
--- index.ts
--- component.tsx
- component-3
--- index.ts
--- component.tsx
```

Let's say that I'm editing "component-1/component.tsx" and now I want to edit "component-1/index.ts". In the current version when I search "index.ts" I get (recently+random?) results with files named "index.ts", instead I would like to get "component-1/index.ts", close to the first results.
Kind of "I want to open a file that it's close to the file that I'm editing".

What do you think?

**Comment by jrieken** [comment]
> What do you think?

I like but should really file a new issue - we don't often look at closed issues...
