### ISSUE TITLE
launch.json: setting protocol:inspector results in bogus error 

### ISSUE THREAD

**Issue by Spongman** [Microsoft/vscode#32202]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
debugger-for-chrome|msj|3.1.7

---

Steps to Reproduce:

1. launch.json:
````
{
	"version": "0.2.0",
	"configurations": [
		{
			"type": "chrome",
			"request": "launch",
			"name": "Launch Chrome against localhost",
			"protocol": "inspector"
		}
	]
}
````
this results in the following error on the type property:
````
The debug type is not recognized. Make sure that you have
a corresponding debug extension installed and that it is
enabled..
````

if you typo `inspector` then the type error goes away.

Reproduces without extensions: N/A

**Comment by weinand** [comment]
@Spongman I do not really understand what you mean by "if you typo inspector then the type error goes away", but I guess that you've meant to say "if you remove the 'protocol' attribute, then the type error goes away".

@aeschli @isidorn this is a really annoying case of misleading error reporting:
the "chrome" debug type does not support a "protocol" attribute. But the "node" debug type would support that attribute.
We need a way to mark the "type" attribute as a "schema defining" attribute. So that the error reporting does not report the "type" attribute as wrong but flag the "protocol" attribute as unknown.

**Comment by Spongman** [comment]
by "typo" i mean "mis-spell", eg:
````
"protocol" : "Qnspector"
````

**Comment by weinand** [comment]
aha, I understand.
Yes an unknown attribute (in any schema) will result in the same (correct) behaviour as a removed attribute.

**Comment by isidorn** [comment]
This is currently not supported by the JSON schema as far as I know and would be a feature request.
@aeschl is there some workaround for this currentlyi (to give the `type` proparty some sort of weight)
