### ISSUE TITLE
[css] add semicolon on value completion

### ISSUE THREAD

**Issue by DamianPereira** [microsoft/vscode#32200]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:26:08.116Z)
- OS Version: Linux x64 4.4.0-89-generic

Steps to Reproduce:

1. Trigger a sugestion for a value of a css property (for example, writing c after `align-items: `)
2. Select a suggestion from the list (for example: `center`)
3. Now you have to write ; 

It would be nice if selecting suggestions added the semi colon at the end automatically, like atom does on css/scss files. AFAIK there's no way to configure this in current VSCode, maybe a setting could be provided if it's too strong for a default.

**Comment by dnecklesportfolio** [comment]
This is would be absolutely awesome, thanks for posting this.

**Comment by bymomo** [comment]
support

**Comment by jonathanphz** [comment]
Why is this closed? Already done?

**Comment by aeschli** [comment]
It's not closed...

**Comment by octref** [comment]
There is no way to do this consistently -- for properties that have enum property values we can auto-complete the semicolon, but for others we can't. Also there is the case of `!important`, so if we add the semicolon this might cause trouble to certain people instead of helping them.
I'm in favor of having consistency and not doing this. @aeschli What do you think?

**Comment by yyynnn** [comment]
This is crucial! Not having colon breaking flow so much. This is implemented in atom, so why no love in vscode?

**Comment by dmikester1** [comment]
I don't see any reason why this couldn't be added as an option in the settings.  Leave it disabled by default and people who want it could enable it.

**Comment by TomPoint** [comment]
a way it could work constantly is to add it wenn you put in the "align-items" it autocompletes to "align-items: ;" and the cursor is placed right in front of the semicolon so you can add in one or multiple  values...

**Comment by budislav** [comment]
Oh yes, add semicolon on value completion is really needed.

**Comment by johnasp** [comment]
I just searched for a solution to this and stumbled across this thread.  This bug is so incredibly ANNOYING!  Incredible they have shipped VS without fixing this first.

**Comment by nemanjacosovic** [comment]
This is the dumbest "feature" of VSCode by far. I'm using it for a year now and I found myself absolutely hampered while writing code. #Macromedia please come back... Dreamweaver 8 was such great tool before Adobe ruined it. I guess phpStorm/webStorm is the only way to go today in order to have a normal editor.

I like Sublime and Coda, but jetBrains is blowing everyone out of the water.

Again, it is completely unbelievable that this was shipped like this, and that it even had so many updates not having this fixed.

**Comment by octref** [comment]
I guess this comes as part of property value completion. I think the best solution is to use https://github.com/csstree/csstree to understand the `syntax` for each CSS property and offer valid completions.

The current problem:

- If you are writing `position:` and chose `relative`, then we can safely close the line with a `;`
- But imagine if you are writing `flex-flow:` and chose `row`. You might want to continue writing `row nowrap` so we shouldn't close it with a semicolon.
- Completing with semicolon and putting cursor in the middle might be problematic too. For example emmet: 
    ![image](https://user-images.githubusercontent.com/4033249/50705260-125ab880-100f-11e9-93de-a8ebe7a1eaba.png)

- Now after writing the values, I need to press `right` to get pass the `;` at the end to open a new line. This is annoying.

**Comment by yyynnn** [comment]
@aeschli no, he means this:

![image](https://user-images.githubusercontent.com/13677727/58170701-dd3cc300-7c9c-11e9-9ce2-0e8bf8a780ba.png)


this is revolting

**Comment by aeschli** [comment]
@yyynnn Please file a separate issue: This issue is about the semicolon. We already add colons for properties (but don't show this in the proposal label)

**Comment by am-awais** [comment]
Can anyone help how to active auto colons after completing css properties like 

> display:
how to add ( : ) automatically

**Comment by octref** [comment]
I'm wondering what exactly are you all asking. Please upvote below three posts accordingly.

**Comment by octref** [comment]
VS Code. Proposed change:
- Insert semicolon at end
- Automatically trigger property value completion

![vsc](https://user-images.githubusercontent.com/4033249/62811901-58519080-bab8-11e9-8a9a-5bda6003fc93.gif)

**Comment by octref** [comment]
Atom. Complete property value with semicolon. I feel when using css properties like `font-family`, `animation` etc, this can backfire and be unpleasant. Atom doesn't seem to do any completion for `animation`

![atom1](https://user-images.githubusercontent.com/4033249/62811921-6f907e00-bab8-11e9-829f-1a473a2ca6ac.gif)

**Comment by octref** [comment]
Atom, by pressing `tab` instead of `enter` to complete. Let's ignore the prefixes. The idea seems to be close to what I proposed for VS Code, it's just you need to manually trigger property value completion in Atom whereas VS Code can do it automatically.

![atom2](https://user-images.githubusercontent.com/4033249/62812068-137a2980-bab9-11e9-9c0b-f0dfedea1946.gif)

**Comment by octref** [comment]
![css](https://user-images.githubusercontent.com/4033249/64736903-8c95e380-d4a0-11e9-90cf-37e8e145ce84.gif)

After you are done writing a value, you can open a new line below by Cmd+Enter or Ctrl+Enter to avoid making the semicolon after you go to new line.

You can control this behavior with `css.completion.completePropertyWithSemicolon`.
