### ISSUE TITLE
HTML Snippets Combine 

### ISSUE THREAD

**Issue by svictoreq** [Microsoft/vscode#32211]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.15.2
vscode-color|ans|0.4.5
theme-verdandi|be5|1.5.0
color-info|bie|0.5.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.2.11
vsc-material-theme|Equ|1.0.2
beautify|Hoo|1.1.1
vscode-gutter-preview|kis|0.10.0
HTMLHint|mka|0.3.3
color-highlight|nau|2.3.0
material-icon-theme|PKi|2.1.0
vscode-icons|rob|7.12.0
code-settings-sync|Sha|2.8.2
stylelint|shi|0.28.0
ayu|tea|0.4.0

(16 theme extensions excluded)

---

Steps to Reproduce:

1. Create an HTML document.
2. Use the '!' emmet snippet to create a boilerplate.
3. In the body section create a form element and enter key.
4. Insert an input snippet.
5. Tab to edit the type attribute.
6. Edits the attribute and outer element.

![html_form_bug](https://user-images.githubusercontent.com/29575744/29154337-d09c3ae0-7d61-11e7-9c31-33f7291fc74e.gif)

Expected behaviour: edit only the attribute and keep using tab inside the snippet.

Reproduces without extensions: Yes

**Comment by ramya-rao-a** [comment]
Also repros without the form element

- Type `!` and select the suggested emmet expansion
- Tab till you reach the body
- type `input` and select the suggested emmet expansion (this expands to `<input type="${2:text}">"`
- Start typing to edit the `type` attribute, typed text appears at the end as well

@jrieken An extra cursor is being placed at the end causing the edits to the placeholder appear in 2 places. Must be due to nested snippets?

Doesn't happen if you escape snippet mode after the first snippet gets expanded

**Comment by jrieken** [comment]
> @jrieken An extra cursor is being placed at the end causing the edits to the placeholder appear in 2 places. Must be due to nested snippets?

Yeah, must be the merging of snippets... I'll take a look

**Comment by jrieken** [comment]
Ok, I can reproduce, both placeholders (of the nested snippet) get the same id assigned. We insert `<input type="${2:text}">` at placeholder `8` which is implemented as merging the second placeholder into the original snippet as `8.2`. However, the final placeholder is getting the same index because it assumes the indices of placeholder start counting at 1 and don't skip a number...
