### ISSUE TITLE
Run the default build task from launch configuration

### ISSUE THREAD

**Issue by joshtynjala** [microsoft/vscode#32239]
Currently, I can specify a `preLaunchTask` field in a launch configuration to run a task before launching. That's great! To use preLaunchTask, I need to give my task an identifier first. Typically, I want to run the default build task before I launch, though. VSCode already knows which task is the default build task, so I feel like there should be a way to tell VSCode to run this task without giving it an identifier.

If one of my tasks.json entries contains the following snippet, VSCode knows that this is the default build task:

```
"group": {
	"kind": "build",
	"isDefault": true
}
```

What if there were a field in launch.json named something like `preLaunchBuild` that could be set to `true` to tell it to run the default build task before launching? `preLaunchTask` would still be useful for running other tasks, but if I just want to run the default build task, I don't need to take the extra step of giving the default build task its own identifier.

**Comment by dbaeumer** [comment]
The ITaskServer offers API getTasksForGroup where debug could as for build tasks. So instead of using the name debug could use a generic pre launch name.

**Comment by weinand** [comment]
Adding a "preLaunchBuild" attribute to launch configs results in a proliferation of common attributes.(which we want to avoid). 

I would rather prefer to have a standard name for the "default build" so that IntelliSense could suggest a good default value.

@dbaeumer do I understand you correctly that the default build task is not available under a standard name? 

If yes, then let's use this as the default value for the "preLaunchTask" attribute.

If not, I suggest that we introduce a variable for that:

```js
"preLaunchTask": "${defaultBuildTask}"
```

**Comment by joshtynjala** [comment]
A standard name or a variable are both good alternatives to my suggestion. Thanks!

**Comment by dbaeumer** [comment]
@weinand no there is not since the name could be something already defined in a gulp file.

However what users can do is to give a task and `identifier` which could be standard. But this is like adding
```
"group": {
	"kind": "build",
	"isDefault": true
}
```

which IMO is enough to denote the standard build task. I have no problem if the ITaskServer offers API to retrieve the standard build task(s).

**Comment by weinand** [comment]
@isidorn @alexr00 I'd like to resolve this and I see the following two options (under the assumption that I **do not** want to add a new common attribute to launch configs:
- introduce a new variable that expands into the default build name, e.g. `${defaultBuildTask}`.
- since `preLaunchTask` accepts a complete structure (as an alternative to the task name), we could introduce a new attribute `"useDefaultBuildTask": "true"` inside that structure.  

I prefer the variable.

@isidorn I've created https://github.com/microsoft/vscode/issues/79625 for the missing code completion on the `preLaunchTask` structure.

**Comment by isidorn** [comment]
@weinand agree that we should not add a new common attribute to `launch.json` for this.

@alexr00 please note that the `preLaunchTask` can either be a `string` or a `ITaskIdentifier` as defined [here](https://github.com/Microsoft/vscode/blob/682f371512dc9c10b1b1929a8e8deacfc0fbff83/src/vs/workbench/contrib/debug/common/debug.ts#L465). I am open to whatever solution you prefer and what makes sense from the tasks standpoint. Something that is aligned with the current way we identify default tasks in task land.

**Comment by alexr00** [comment]
I like `${defaultBuildTask}`, but there is still the case where there is no default build task. In that case, we can show the build task picker as we do when the Tasks: Run Build Task command is executed.

All of the work for this is in the configuration resolver and in tasks. I will aim to do it in September.

**Comment by isidorn** [comment]
@alexr00 makes sense. However currentyl the `configurationResolverService` has no notion of the debug and task land. This way you would have to introduce one that sounds task specific. This works for me, but just to keep in mind. Maybe the cleanest approach would be that the task land somehow contributes this to the configurationResolverService.

**Comment by isidorn** [comment]
@alexr00 adding verification needed here, if you plan to write a test plan item feel free to remove the label. Also unassigning myself since you did all the work.
