### ISSUE TITLE
Content security warning in Markdown preview won't go away

### ISSUE THREAD

**Issue by cfjedimaster** [Microsoft/vscode#32251]
- VSCode Version: Code - Insiders 1.15.0-insider (2c3e2c291c515619f64e7c9cddf14c565b7f3d92, 2017-08-08T21:31:44.273Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
spellright|ban|1.0.42
markdown-preview-github-styles|bie|0.0.1
wordcount|ms-|0.1.0
material-icon-theme|PKi|2.1.0
htmlescape-vscode-extension|ray|0.0.4

---

Steps to Reproduce:

1. Turn on Markdown preview with content that triggers the warning
2. Select Allow insecure content
3. The "Some content has been disabled in this document" warning does not go away.

After I've made a decision, why is the warning label staying in the view? It's annoying and actually blocks text. Not a lot, but still.

If I select the Disable option it goes away, but any option should make it go away after I've made a selection.

**Comment by mjbvz** [comment]
Out of curiosity, can you share the markdown source. I'm interested to see what is being blocked with allow insecure content setting.

Possible approaches to the issue:

1. Hide the security warning in the preview after the user has explicitly selected a preview. This  may be confusing if content is still being blocked
1. Make the blocked content warning smaller or style it so that it does not overlap with text
1. Add a way to suppress the warning explicitly in a workspace

**Comment by cfjedimaster** [comment]
I believe it was the Twitter embed. Here is the document that caused it: 

https://github.com/cfjedimaster/raymondcamdendotcom/blob/master/content/post/2017/08/09/career-advice-for-a-new-web-dev.md

**Comment by mjbvz** [comment]
Yes the`<script>` is what causes this. I think option 3 is the simplest and makes the most sense here. We can add a workspace stored setting to hide the popup in the preview
