### ISSUE TITLE
Emmet falsely suggesting completion with hyphen in parent tag

### ISSUE THREAD

**Issue by johnlindquist** [Microsoft/vscode#32263]
![](https://cl.ly/160i0w1L2n38/Screen%20Recording%202017-08-10%20at%2006.23%20PM.gif)

**Comment by zouhangwithsweet** [comment]
hi , i cannot use the emmet in .vue file after i updated the  vccode today and i already has wirte "emmet.syntaxProfiles": {
        "vue-html": "html",
        "vue": "html"
    } in setting json.

**Comment by ramya-rao-a** [comment]
That's a valid bug, thanks @johnlindquist 

@zouhangwithsweet You need to use `emmet.includeLanguages` setting instead from VS Code 1.15 version onwards

**Comment by zouhangwithsweet** [comment]
Thanks, its working now.  But i cannot use `tab` to emmet code forever. That's too bad. its time to use `enter` now!!

**Comment by ramya-rao-a** [comment]
@zouhangwithsweet You can use `tab` for emmet in the latest Insiders. Download it from https://code.visualstudio.com/insiders and set `emmet.triggerExpansionOnTab` to `true`.

**Comment by ramya-rao-a** [comment]
@sergeche The same problem occurs in the atom plugin as well.

![atomemmet](https://user-images.githubusercontent.com/16890566/29234486-2ff09e96-7eac-11e7-9dde-bf76855fba05.gif)

When providing `<foo-bar>Hello</foo-bar>` as input to the `extract-abbreviation` module with the pos right after `Hello`, the extracted abbreviation is `foo-bar>Hello` instead of just `Hello`

Where as if the same without the hyphen is provided, then the extracted abbreviation is indeed `Hello`.

I was able to narrow it down to https://github.com/emmetio/extract-abbreviation/blob/v0.1.2/lib/is-html.js#L122 where the definition of identifier is to contain either  `:` or a alpha-numeric char.

`-` fails this test.

How do you suggest we tackle this?

**Comment by sergeche** [comment]
@ramya-rao-a this test should also include `-` as well. Published `@emmetio/extract-abbreviation@0.1.3`

**Comment by ramya-rao-a** [comment]
Thanks @sergeche 

@johnlindquist Am curious, is it common to write html with `-` in this way?

**Comment by sergeche** [comment]
Yes, it’s very common, especially for Web Components

**Comment by jens1o** [comment]
Exploring on @sergeche:

Yes, it is. When you obey to the standard, tags with a hyphen are the only tags that can be introduced custom. So when you want to create a new tag for your maintenance message and you want to give it unique properties, you would have to call it `<j1o-maintenance></j1o-maintenance>` (`j1o` is an acronym for `jens1o` here)

**Comment by ramya-rao-a** [comment]
Thanks @sergeche and @jens1o, I have added this issue to the July Recovery plan

**Comment by ramya-rao-a** [comment]
Fix is both in master and the release branch

**Comment by ramya-rao-a** [comment]
VS Code 1.15.1 is released and it has the fix to this issue
