### ISSUE TITLE
Typescript: Paste screws up format

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#32305]
This now feels a **lot** like what frustrated me 5 years ago in Visual Studio.

Not only paste now gets indentation wrong most of the time, it does it in two steps, requiring a double undo to go back.

This was even pointed out today in our HackerNews thread: https://news.ycombinator.com/item?id=14983231

**Comment by rebornix** [comment]
I'll revisit indent on paste this milestone and see if we still keep it turned on. Pasting is way more complex than move lines or type because 

* the indent of first line is usually wrong as there might be additional leading whitespaces before pasting
* for the rest of the line, we don't know whether their indentation are intentional or wrong. 

Right now both Atom and we only try to adjust the indent of the first line and see if we need to adjust the offset to following lines. Besides, the user on hackernews is correct, without AST, auto indent can never be perfect.

**Comment by uphlewis** [comment]
Also been getting this issue since a recent update (some time in the last 2 months), but with PHP

**Comment by rebornix** [comment]
This is due to the limited architecture (regex based indentation rules and only support limited code styles), we may want to consider using formatters if they exist for indenation adjustment (if interested, we can discuss in https://github.com/microsoft/vscode/issues/19847).

For this particular issue, if the indentation rules are leading to more trouble than having no auto indent, you can set `editor.autoIndent` to `advanced` to disable the regex based indentation adjustment. As we don't have an easy good-enough fix for it, we close it for now and explore better solutions through issues like https://github.com/microsoft/vscode/issues/19847.
