### ISSUE TITLE
Incorrect renderWhitespace for proportional fonts

### ISSUE THREAD

**Issue by mvoidex** [Microsoft/vscode#32312]
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:16:18.034Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|don|0.7.0
cpptools|ms-|0.12.2

---

Steps to Reproduce:

1. Set parameters:

    "editor.fontSize": 13,
    "editor.fontFamily": "Lucida Sans Unicode",
    "editor.renderWhitespace": "all"

2. Open new file and write 4 spaces. Rendered dots will be twice wider than real spaces.

Even more:

3. write down `foo` and 4 spaces, caret will be at most right position after rendered dots (incorrect according to proportional font)
4. start typing some letter - it will be inserted before caret, and caret will be moved to correct position

Reproduces without extensions: Yes

**Comment by rebornix** [comment]
It looks like it's an issue with non-monospaced font, please see https://github.com/Microsoft/vscode/issues/1727 for more details.

**Comment by mattflix** [comment]
Why was this closed in haste?  Please re-open.

#1727 is about the display of _monospaced_ fonts.  THIS issue is about the display of _proportional_ fonts.

I too have noticed, at least as of the last release, that proportional fonts no longer display properly in at least the following cases:

1. code folding 
2. debugging, especially intra-line debugging

The indentation gets all messed up (text is shifted left, seemingly because the whitespace is compressed).  The indentation previously was stable, regardless of font.

I have been using the same proportional font with VSCode for the least several (tens?) of versions.  This rendering issue is recent.  Same problem on Mac and Windows.

(Yes, some of us like the occasionally use proportional fonts when working with code...  it simply makes for a change.)
