### ISSUE TITLE
Compound launch configuration not preserved

### ISSUE THREAD

**Issue by edvinv** [Microsoft/vscode#32318]
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:09:15.006Z)
- OS Version: Linux x64 4.10.0-32-generic

Steps to Reproduce:

1. Create compound launch configuration based on two other configurations
2. Select compound configuration and start debugging
3. While starting, selected configuration will be changed to some other non compound 
4. Next time you must again manually select compound configuration 

This was working in 1.14.

**Comment by JohnGalt1717** [comment]
Pretty please: Release a point release for this fix. This is a brutal time waster.

**Comment by weinand** [comment]
@isidorn the problem is that `startDebugging` is called recursively: in case of a compound it is first called for the compound, then for the individual launch configs contained in the compound. In both cases it sets the name of the selected launch config which will always overwrite the compound name with the name of the last contained launch config.

To fix this I've introduced an optional arg `compoundName` for `startDebugging` with the name of the top level parent compound config.

In addition I've spotted, that the `noDebug` argument is not propagated to the contained launch configs. I've fixed that too.

Note for verification:
- make sure that this works for "compounds of compounds" as well (so the name of the outermost compound should prevail).
- make sure that the `noDebug` flag is honoured correctly.

**Comment by gregmarr** [comment]
@weinand When will this fix be released?  I just started using the version with this bug, and it's *really* annoying!

**Comment by weinand** [comment]
The fix is already in the Insiders release.

**Comment by isidorn** [comment]
@weinand I have code reviewed and this looks good to me. Thanks!
