### ISSUE TITLE
"Find in files" search shows incomplete results

### ISSUE THREAD

**Issue by volium** [Microsoft/vscode#32325]
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:16:18.034Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.2.11
project-manager|ale|0.19.0
githistory|don|0.2.3
python|don|0.7.0
cpptools|ms-|0.12.2
csharp|ms-|1.12.0
copy-file-name|nem|1.0.0
markdown-checkbox|PKi|1.0.3
material-icon-theme|PKi|2.1.0
vscode-hexdump|sle|1.4.0
change-case|wma|1.0.0

---

Steps to Reproduce:

1. Open a project and do a "find in files" search for anything valid. i.e. "foo"
2. Results should be incomplete, a file with the searched for string will not show in the results.
3. Manually open the file, either by going to symbol definition, or open file (Ctrl+P)
4. Do the same string search again
5. The string will be found in the newly open file now

The problem is I can't trust the search anymore, knowing that not all results are being returned.

Reproduces without extensions: Yes

**Comment by volium** [comment]
I just found a duplicate issue #32095. I can add that I'm seeing the issue with pure "local" files, no NFS here.

**Comment by volium** [comment]
Yes, I had some exludes ("**/*.lst, **/*.d"), but even after removing them, and disabling the "ignore" and "exclude" settings, the files don't show up.

I noticed that if the string has been seen already in a file, it will cache it and show it, but otherwise the results won't be complete.

**Comment by roblourens** [comment]
Is it the same results that are missing each time, or a random set? I'm not aware of any issues like this so it would be really helpful if you can try different searches, or different folders, and help me figure out what is different about the missing results.

If the file is open, then it will get results from the editor instead of the normal search tool, so you may want to close all files before testing.

**Comment by volium** [comment]
Ok, I have more info...

I was searching in a folder/repo that I use ALL the time, which has a bunch of VS settings already configured. If I open another source folder (completely) unrelated, then search does work fine. I have a feeling something is being cached, and things got messed up when I switched to the 64-bit build... maybe?

**Comment by roblourens** [comment]
Nothing gets cached between runs for search, so that shouldn't be an issue.

**Comment by volium** [comment]
Ok, I think I found the culprit... but I'm sure this used to work:

in "files to include" I have this: "**/*.*"  (no quotes, obviously"

If I remove the wildcard, then it shows me the results of all files,
otherwise only if the file(s) is(are) already open.... I'm pretty sure this
is a change in behavior, is it not? I usually leave the wildcard in place
so I can change the file type quickly.

**Comment by roblourens** [comment]
Good catch. That's a weird issue. It's due to a small change I made to how patterns in that box are interpreted. I think it could actually be a bug in ripgrep with patterns that include `**/**`, but the pattern I generate is so crazy that it's hard to blame ripgrep - `'/somefolder/{**/**/*.*/**,**/**/*.*}'`

**Comment by volium** [comment]
Ok, let me know if there's anything else you want me to test, in the mean
time I'll stop using the wildcards...

thanks for looking into it

**Comment by roblourens** [comment]
You could use `*.*`, it should produce exactly the same results as what you would expect from `**/*.*`

**Comment by BillDenton** [comment]
This issue is causing me a lot of problems in 64bit 1.15 on Windows 7 Professional. When will the fix be released? For now I've removed the wildcard, but it does make searches slow and shows irrelevant results. It also appears to be showing files that I have excluded, e.g. <something>.map shows when I have:
"files.exclude": {
      etc
      "**/*.map": true,
      etc
},

**Comment by roblourens** [comment]
The fix is in Insiders and will be released later this week. 

> For now I've removed the wildcard, but it does make searches slow and shows irrelevant results. 

Are you sure you're looking at the same issue? For the issue above, the workaround I suggest won't have any impact on search speed or showing different results.

> It also appears to be showing files that I have excluded

Would appreciate if you try in Insiders or open a new issue with details. The only issue I'm aware of here is that if a file is open, it will probably show up even if there are excludes for it.

**Comment by BillDenton** [comment]
"It also appears to be showing files that I have excluded"
Sorry that's my fault, I turned off "Use Exclude Settings" whilst I was trying to work out why it didn't find all the files.
"For now I've removed the wildcard, but it does make searches slow and shows irrelevant results."
I meant that I'm now searching a lot of unwanted files, so it has slowed down. Not a an issue.
"will be released later this week."
Do you mean that there will be "recovery" build for non insiders build?

**Comment by roblourens** [comment]
I also mean that you shouldn't have to remove a wildcard that causes more files to be searched. If you tell me exactly what the problem is I can work out whether you're looking at the same issue or not.

Yeah, there will be a recovery build, probably weds/thurs.

**Comment by BillDenton** [comment]
There's no issue, I was just turned off the "Use Exclude Settings" whilst trying to understand why it wasn't finding everything. Now, I've turned it back on it is working as expected. So there is no new issue and it all should be fixed once the recovery build arrives.

**Comment by roblourens** [comment]
Got it, thanks.
