### ISSUE TITLE
Emmet snippets -> to the TOP of snippets list

### ISSUE THREAD

**Issue by user3323** [Microsoft/vscode#32346]
- VSCode Version: 1.15.0
- OS Version: win7x64

Well, now "Tab" and it's double-action for tabing and Emmet expand cannot do it anymore, as I see.
So, what about setting, that will put Emmet snippets **TO THE TOP**  of the common snippets list?

We have nice setting called **"editor.snippetSuggestions"** and one of its value called **"top"**
But it works only for snippets, written in "[language].json" files.

So, what about Emmet snippets? It also should have settings like this!

![image](https://user-images.githubusercontent.com/24613274/29227489-ad8802f4-7ede-11e7-86ae-771de6c67163.png)

**Comment by ramya-rao-a** [comment]
Emmet is now an extension.

The `editor.snippetSuggestions` setting applies to suggestions from extensions that are snippets.

Currently emmet doesn't return the suggestions as snippet, because I was concerned about users who might have set `editor.snippetSuggestions` to `none` or `bottom` will never be able to see the real time preview or get emmet suggestions up top.

But you raise a good point.

When users have set `editor.snippetSuggestions` to `top`, emmet suggestion now goes down. Which is not good either.

One hacky way around this is for the emmet extension to use the "snippet" type on the emmet suggestions when `editor.snippetSuggestions` is set to `top`.

This way, when `editor.snippetSuggestions` is set to `top`, emmet will be the first in the list.
In all other times, in html, it already is the first in the list
In css, it is sorted among other suggestions.

**Comment by ianjmacintosh** [comment]
It took me a minute to find this issue, but I'm glad I did.

I downloaded 1.15.1 today and agree it would be even better if I could bubble Emmet's CSS suggestions to the top.

![screen shot 2017-08-29 at 5 07 52 pm](https://user-images.githubusercontent.com/1103259/29844261-a661b84c-8cdc-11e7-98d2-13706e45d7c8.png)

**Comment by ramya-rao-a** [comment]
Added a new setting `emmet.showSuggestionsAsSnippets`. When this is enabled, emmet suggestions will show up as snippets (with the snippet icon), grouped with rest of the snippets and will honor the ordering as configured in the setting `editor.snippetSuggestions`

With `emmet.showSuggestionsAsSnippets` enabled and `editor.snippetSuggestions` set to `top`, you can be assured to have emmet suggestions always show up at the top.

I am adding a setting and not making this the default due to the concern I explained before. Which is that users who have `editor.snippetSuggestions` set to `bottom` or `none` will be at a loss

@user3323, @ianjmacintosh, @vvs
This feature will be out in tonight's (Aug 31) Insiders build. You can get the Insiders from https://code.visualstudio.com/insiders. Can you give it a try?

**Comment by vvs** [comment]
WHOA, this is great! Now I could add all my quick Emmet snippets, like p for padding, m for margin, b for border, c for color etc, and they all are at the top the suggestion list, so they finally work as expected! :)

**Comment by dimondevs** [comment]
Thank you @ramya-rao-a , everything works as expected.

**Comment by ramya-rao-a** [comment]
@vvs When you say "my quick Emmet snippets" do you mean your custom ones or the default ones from emmet?

**Comment by ianjmacintosh** [comment]
@ramya-rao-a Awesome work, thank you for addressing. I can confirm with settings:
```json
{
    "emmet.showSuggestionsAsSnippets": true,
    "editor.snippetSuggestions": "top"
} 
```
![screen shot 2017-08-31 at 12 05 56 pm](https://user-images.githubusercontent.com/1103259/29933177-c1935904-8e44-11e7-820c-e477cabf9a49.png)

After typing `tac` in a CSS file:
![screen shot 2017-08-31 at 12 06 20 pm](https://user-images.githubusercontent.com/1103259/29933196-d2fae40a-8e44-11e7-8e72-3a3b315e0b62.png)

**Comment by vvs** [comment]
@ramya-rao-a,
> When you say "my quick Emmet snippets" do you mean your custom ones or the default ones from emmet?

I meant my custom emmet snippets. But it looks like I don't need to create those custom snippets at all, since the default ones work great when I set Emmet suggestions to snippets and put them on top.

So, all those `p`, `m`, `c` and `bd` now work as expected with no extra work to create custom emmet snippets. Well done! :)

**Comment by ramya-rao-a** [comment]
@vvs Yup, that was what I was hoping for, that you wouldn't have to create custom snippets for things which have default ones set up.

@ianjmacintosh @vvs @dimondevs Thanks for verifying and Happy Coding!
