### ISSUE TITLE
Emmet multi-cursor expansion incorrect

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#32342]
- VSCode Version: Code - Insiders 1.16.0-insider (dc3a6df693da5ad6e9219cb0269439cc6a8c401a, 2017-08-11T06:58:01.143Z)
- OS Version: Darwin x64 16.7.0

---

![emmetmulticursor](https://user-images.githubusercontent.com/9205389/29226087-8ff2a1a8-7e85-11e7-8072-de790222cf62.gif)

```html
Foo-Test[bar=baz]*4
Bar-Test[bar=baz]*4
```

**Comment by ramya-rao-a** [comment]
@jens1o You want to take this one up?

What is happening is that expanded value of the first abbreviation is overlapping with the second abbreviation.

We go through each of the cursors, extract abrbeviation and run expand on it here: https://github.com/Microsoft/vscode/blob/release/1.15/extensions/emmet/src/abbreviationActions.ts#L144

Instead of going through `editor.selections` in the order that they appear in that array, we need to sort it in descending order of their position and then go through the sorted list.

**Comment by jens1o** [comment]
I'm sorry, but my Insiders version is close to being unusable at all(#32530). And the todays release doesn't fix my problem, and the functionality is very limited. :/

**Comment by jens1o** [comment]
@ramya-rao-a Thanks for the fix!

**Comment by ramya-rao-a** [comment]
@jmdowns2 deserves the credit, he provided the fix :)
