### ISSUE TITLE
After the upgrade, emmet does not work

### ISSUE THREAD

**Issue by gangstein** [Microsoft/vscode#32372]
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:16:18.034Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
stylus|Ala|0.0.4
vscode-color|ans|0.4.5
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
jshint|dba|0.10.15
python|don|0.7.0
vscode-npm|fkn|3.3.0
beautify|Hoo|1.1.1
vs-color-picker|lih|0.6.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
material-icon-theme|PKi|2.1.0
LiveServer|rit|1.6.8
linter-xo|sam|2.1.3
stylelint|shi|0.28.0
language-stylus|sys|1.7.3
highlight-matching-tag|vin|0.4.4
vscode-bemmet|vol|0.1.1

(1 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by gangstein** [comment]
I just recently switched from sublime and then immediately broke emmet = ( what should I do? =((

**Comment by Enethion** [comment]
Before last update that problem was easily fixed by setting `"emmet.useNewEmmet": false`.
Now, that `"emmet.useNewEmmet"` is gone (at least in new x64 version) how can I fix emmet in blade files?

**Comment by ramya-rao-a** [comment]
@gangstein 

Here are your options
- If on VS Code 1.15 use emmet from suggestions, bind any other keyboard shortcut (other than tab)  for the emmet expand command
- If on VS Code 1.16 Insiders build (you can get it from https://code.visualstudio.com/insiders), then set `emmet.triggerExpansionOnTab` to `true`. You will get emmet expansions on tab

We really wanted to move away from using tab for emmet due to the problems it brings for non emmet users. But there has been feedback requesting the tab->emmet feature back, and so it is now available in the latest Insiders

**Comment by ramya-rao-a** [comment]
@Enethion To enable emmet in languages that are not supported by default (in your case, blade), you need to use `emmet.includeLanguages` from VS Code 1.15 onwards instead of `emmet.syntaxProfiles`.

This was done because `emmet.syntaxProfiles` is actually meant for customizing the final output. Like casing for tag/attribute name, using single vs double quotes for attribute values etc. You can read more here: https://docs.emmet.io/customization/syntax-profiles/
