### ISSUE TITLE
Thanks for destroying Emmet

### ISSUE THREAD

**Issue by KonradDeskiewicz** [Microsoft/vscode#32371]
I can understand that there is few people that found your "new invention" great but for most of us those changes broke workflow that we were accustomed to for years.

I really like TAB expanding, and fact that old emmet was working with blade templates and vue without issues. 
Right now I dropped VSC  as it cause me more headache than helping with do my work fast.

Can we switch new emmet off and go back to something that really work?

**Comment by jens1o** [comment]
> and fact that old emmet was working with blade templates and vue without issues.

You can make it work again:

Add this to your settings:
```json
emmet.includeLanguages: {
    "vue-html": "html",
    "blade": "html"
}
```

**Comment by ramya-rao-a** [comment]
Thanks @jens1o 

@KonradDeskiewicz 

Use of `emmet.includeLanguages` instead of `emmet.syntaxProfiles` is introduced as the latter was actually meant for customizing final emmet output as documented in the emmet website https://docs.emmet.io/customization/syntax-profiles/

Emmet in suggestions was introduced due to reasons explained in the [Emmet 2.0 blog](https://code.visualstudio.com/blogs/2017/08/07/emmet-2.0)

Your options:

- If on VS Code 1.15 use emmet from suggestions, bind any other keyboard shortcut (other than tab)  for the emmet expand command. tab is not recommended in this version, as there is no fallback to indenting when emmet doesn't apply. So you won't get to add indent in any file
- If on VS Code 1.16 Insiders build (you can get it from https://code.visualstudio.com/insiders), then set `emmet.triggerExpansionOnTab` to `true`. You will be able to use tab for emmet. The appropriate fallback for tab exists so that you get indentation when emmet is not applicable. Emmet in suggestions will also exist for easy previewing of the expanded value

We really wanted to move away from using tab for emmet due to the problems it brings for non emmet users. But there has been feedback requesting the tab->emmet feature back (like yours and the ones in #32243), and so it is now available in the latest Insiders.

**Comment by HelloDeadline** [comment]
@ramya-rao-a 

> If on VS Code 1.16 Insiders build (you can get it from https://code.visualstudio.com/insiders), then set emmet.triggerExpansionOnTab to true. You will be able to use tab for emmet. The appropriate fallback for tab exists so that you get indentation when emmet is not applicable. 

I installed it and set  `emmet.triggerExpansionOnTab` to `true` as you suggested. As a result completion of simple `div` happens not every time and when it does, it does it with a huge delay. 
This happened in JSX code in .js file. 

I also can't use Tab button for indentation. 

Related Settings:
```
"emmet.includeLanguages": { "javascript": "javascriptreact" },
"emmet.triggerExpansionOnTab": true,
"files.associations": {
    "*.js": "javascriptreact"
  },
```

I am on Linux Mint 18.1 Serena

**Comment by ramya-rao-a** [comment]
@HelloDeadline 

- Does the delay and the indentation issue happen only in jsx code in js files? Can you try in html?
- Does running the command `Emmet: Expand Abbreviation` also take similar delayed time?
- Do you have any keybindings for the expand abbreviation command that you customized?

**Comment by HelloDeadline** [comment]
@ramya-rao-a 

Sorry for disinformation. I investigated this case and found out that [this extension](https://marketplace.visualstudio.com/items?itemName=vincaslt.highlight-matching-tag) ruined my workflow. In VS Code 1.15 it simply ruined Eslint and Prettier and in Insiders it created huge delay when using Tab. 

I uninstalled it and now everything works as expected.

**Comment by ramya-rao-a** [comment]
@HelloDeadline Thanks for getting back... I was worried for a bit there :)

Happy Coding!
