### ISSUE TITLE
code menu is not visible

### ISSUE THREAD

**Issue by sreenathk** [Microsoft/vscode#32382]
- VSCode Version: Code - Insiders 1.16.0-insider (0b6da14128b4e61e331193f18786e8db2792a643, 2017-08-11T19:30:08.812Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: none
---

Steps to Reproduce:

1.
2.

**Comment by weinand** [comment]
Id on't understand. Please provide steps and/or a screenshot.

**Comment by sreenathk** [comment]
![code menu is not visible](https://user-images.githubusercontent.com/809039/29242836-a2d1170a-7fb1-11e7-87bb-32413d7b0843.png)
![few menu not available](https://user-images.githubusercontent.com/809039/29242837-a2d4ec86-7fb1-11e7-8b31-fff20e9be9b3.png)

Thanks for your reply, In one video I see some other menu options, when I have install I didn't find those options like 
code, window

**Comment by weinand** [comment]
The "Code" menu is the standard **application menu** on macOS. It always has the name of the application ("Code") but it provides only generic commands like Print or Preferences. On Windows this functionality lives in other menus.

The "Windows" menu is another standard macOS menu that provides window manipulation commands. It does not exist on Windows because the functionality is either not needed or exists elsewhere.
