### ISSUE TITLE
Small typo in the Emmet 2.0 blog post

### ISSUE THREAD

**Issue by eyalsk** [Microsoft/vscode#32388]
Someone wrote "It's features include" whereas it should be "Its features include".

Just thought to point it out. :)

**Comment by ramya-rao-a** [comment]
Thanks for reporting @eyalsk 

Fixed with https://github.com/Microsoft/vscode-docs/commit/1b471b70e6008b8761aa013911cdb9b18124084b

cc @gregvanl for publishing the website
The website will be updated early next week, as its the weekend now.

@eyalsk As a side note, all our docs are in https://github.com/Microsoft/vscode-docs. If you find any mistakes in https://code.visualstudio.com you can create an issue in that repo. PRs are welcome as well. We can use all the help we can get in improving our docs :)

**Comment by eyalsk** [comment]
@ramya-rao-a ah okay, thanks. ;)
