### ISSUE TITLE
THIS THING DELETED 3 MONTHS OF WORK!!!! 

### ISSUE THREAD

**Issue by eliecerthoms** [Microsoft/vscode#32405]
I had just downloaded vscode as an alternative and I was just playing with the source control option, seeing how it wanted to stage FIVE THOUSAND FILES I clicked discard... AND IT DELETED ALL MY FILES, ALL OF THEM, PERMANENTLY!

HOW THE FUCK IS THIS SHIT POSSIBLE, WHO THE HELL IS THE DUMBFUCK WHO MADE THE OPTION TO PERMANENTLY DELETE ALL THE FILES ON A PROJECT BY ACCIDENT EVEN POSSIBLE?? CANNOT EVEN FIND THEM IN THE RECYCLE BIN!!!! I DIDN'T EVEN THOUGHT THAT WAS POSSIBLE ON WINDOWS!!!

FUCK THIS FUCKING EDITOR AND FUCK WHOEVER IMPLEMENTED THIS OPTION. I WISH YOU THE WORST. 

I'M PERMANENTLY STAYING AWAY FROM EVERY WINDOWS DEVELOPMENT SOFTWARE FROM NOW ON AND TO THE GENIUS WHO IMPLEMENTED THIS:  
 FUCK YOU FUCK YOU FUCK YOU FUCK YOU  FUCK YOU FUCK YOU FUCK YOU FUCK YOU   FUCK YOU FUCK YOU FUCK YOU FUCK YOU  FUCK YOU FUCK YOU FUCK YOU FUCK YOU  FUCK YOU FUCK YOU FUCK YOU FUCK YOU  FUCK YOU FUCK YOU FUCK YOU FUCK YOU  FUCK YOU FUCK YOU FUCK YOU FUCK YOU  FUCK YOU FUCK YOU FUCK YOU FUCK YOU  FUCK YOU FUCK YOU FUCK YOU FUCK YOU  FUCK YOU FUCK YOU FUCK YOU FUCK YOU  FUCK YOU FUCK YOU FUCK YOU FUCK YOU  FUCK YOU FUCK YOU FUCK YOU FUCK YOU  FUCK YOU FUCK YOU FUCK YOU FUCK YOU  FUCK YOU FUCK YOU FUCK YOU FUCK YOU FUCK YOU  FUCK YOU FUCK YOU FUCK YOU FUCK YOU  FUCK YOU FUCK YOU FUCK YOU FUCK YOU  FUCK YOU FUCK YOU FUCK YOU FUCK YOU  FUCK YOU FUCK YOU FUCK YOU FUCK YOU  FUCK YOU FUCK YOU FUCK YOU FUCK YOU  FUCK YOU FUCK YOU FUCK YOU FUCK YOU  FUCK YOU FUCK YOU FUCK YOU FUCK YOU FUCK YOU  FUCK YOU FUCK YOU FUCK YOU FUCK YOU  FUCK YOU FUCK YOU FUCK YOU FUCK YOU  FUCK YOU FUCK YOU FUCK YOU FUCK YOU  FUCK YOU FUCK YOU FUCK YOU FUCK YOU  FUCK YOU FUCK YOU FUCK YOU FUCK YOU  FUCK YOU FUCK YOU FUCK YOU FUCK YOU  FUCK YOU FUCK YOU FUCK YOU FUCK YOU 

- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:16:06.988Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
vscode-twig-pack|baj|1.0.0
jshint|dba|0.10.15
python|don|0.7.0
pgsql|dou|0.0.8
EditorConfig|Edi|0.9.4
beautify|Hoo|1.1.1
format-indent|Kas|1.3.0
prettify-json|moh|0.0.3
lorem-ipsum|Tyr|1.0.0
html-css-class-completion|Zig|1.8.0

---

Steps to Reproduce:

1. Go near this fucking shit editor. 
2. Commit the deadly sin of touching the source control options.

Reproduces without extensions: Yes/No

**Comment by jens1o** [comment]
Tiny question: Are you interested in solving your problem? I didn't had experienced this after using this for over a year now... 
> I clicked discard...
But this looks like a valid operation, so, you need to watch out before you press buttons. Maybe you can pull latest changes from your SVN?

**Comment by eliecerthoms** [comment]
@jens1o I hadn't commited any of them to any repository. But that shouldn't mean that this thing is going to toss your files to oblivion because of that decision. It didn't say CAUTION: THIS WILL DELETE EVERY FILE FROM THIS FOLDER IN YOUR COMPUTER. It said: are sure to discard all the changes? which isn't similar to what it does by any means. Why on earth wouldn't you just move the files to the trash bin? 

Now I am just supposed to suck it up and start over from scratch right?

**Comment by eliecerthoms** [comment]
It damaged so much of my codebase, deleted so much dependencies too that I don't even know where to start fixing it. I am basically condemned to start over again. This is ABYSMAL design.

**Comment by eliecerthoms** [comment]
I am still in disbelief.

**Comment by eliecerthoms** [comment]
https://social.msdn.microsoft.com/Forums/expression/en-US/b32e47a9-d86c-473a-9449-a7f5c202463c/visual-studio-code-just-deleted-all-my-files?forum=visualstudiogeneral

I am not the only one who this editor has fucked over. This option is just malicious and if you have a modicum of decency and morality as developers, at least move the files to recycle bin so that this doesn't happen to people wanting to try your products. 

This is absolutely awful and I don't take back any word of contempt against whoever designed this heinous and abhorrent behavior.

**Comment by remcoros** [comment]
Even since I lost a big school project around 15 years ago I use source control, always, everywhere. Even my game saves are source controlled. On top of that, My main drives are externally backed up every day.

Why you have three months of work not under source control is the bigger question.

**Comment by EbXpJ6bp** [comment]
In git client, "Discard All Changes" usually means `git checkout`. It's in the specifications in git.

**Comment by eliecerthoms** [comment]
@remcoros yeah, so the damage done by the destructive bug in the code is now my fault for not being a clairvoyant and seeing this piece of shit software was going to fuck up my files. I don't need to explain  why I don't have a private repo with my stuff. It is the software's  concern NOT to destroy the integrity of a computer like a damn virus. You come here, see my despair and berate me for something that was not my fault, and has happened to a lot of other people? Fuck you.

**Comment by joaomoreno** [comment]
@eliecerthoms We're sorry you've hit this. We really are.

But let me address some of your feedback first:

> It didn't say CAUTION: THIS WILL DELETE EVERY FILE FROM THIS FOLDER IN YOUR COMPUTER. It said: are sure to discard all the changes? which isn't similar to what it does by any means.

Actually this is what you've seen:

![img](https://user-images.githubusercontent.com/240625/29264526-c8a1b354-80dd-11e7-82d7-76e7b0066998.png)

It seems that we weren't that way off.

---

Now let me ask you something else: what would you think would happen if you used any other application which integrates Git? Let me try to guess. You'd probably initialize a repository as well, just because why not? It's not like you're messing with code which doesn't have backups right? You'd probably see all those changes appear and try to find a way to make them disappear, just like what happened here. You'd also probably not search and try to learn a bit more about what you're messing with, similarly to this situation. Finally, the application would still delete your files, no matter how many confirmation dialogs it would pop up.

This happened with Code. It could have happened with Atom, Git Tortoise, Git Kraken. These are all powerful tools and with more power comes more responsibility. When you sell hammers you'll likely have people using them to hit their own heads, which, understandably, they will put the hammer at fault. Now, we already put a big _don't hit this on your own head_ label on our hammer. Should we actually prohibit people from head hitting with our hammers? Probably not since some users still want to hit heads with it. It's just how hammers work.

---

Now, #32459 was started by @thierer with an attempt to prevent situations like this. Let's make that happen.

**Comment by lukemartin** [comment]
🤣

**Comment by voronoipotato** [comment]
I'd say remove the warning dialog, and prompt an "Undo" that lasts 5 seconds. Behind the scenes count to 5 and then do it. People respond much better to "Undo" than they do to "Are you sure?" dialog.

**Comment by iltar** [comment]
Isn't there a local history to get everything back? Using PHP and PhpStorm as my IDE, I can simply undo this action is it's in my local history.

**Comment by planchao** [comment]
this is hilarious
