### ISSUE TITLE
Variables disappear when emmet abbreviations get expanded

### ISSUE THREAD

**Issue by opencreative** [Microsoft/vscode#32420]
- VSCode Version: 1.15.0

When I type css property and specify a variable, emmet shows what should happen.
After pressing the Enter key, the variable is not substituted.
Is this a bug or such a feature?

![sass](https://user-images.githubusercontent.com/29632606/29251460-73a121ae-8098-11e7-80b6-2c035965166c.gif)

**Comment by jens1o** [comment]
cc @ramya-rao-a

**Comment by ramya-rao-a** [comment]
@opencreative That's a bug

What's happening behind the scenes is that emmet expand module returns `background-color: $bgColor` to the emmet extension in VS Code which then inserts a snippet with the same value.

Snippet treats `$bgColor` as a snippet variable and replaces it with empty string as there is no such variable defined for the snippet.

Fix would be to escape the `$` before creating the snippet so that, VS Code leaves it as it is.

**Comment by jens1o** [comment]
Can you consider putting this in recovery release no. 2?

**Comment by ramya-rao-a** [comment]
I was working on the fix and was planning to mark it as a candidate when I have the fix ready. At the moment I am testing

**Comment by ramya-rao-a** [comment]
Fix is both in master and the release branch

**Comment by ramya-rao-a** [comment]
@opencreative @jens1o VS Code 1.15.1 is released and it has the fix to this issue

**Comment by jens1o** [comment]
Thanks!

**Comment by opencreative** [comment]
Thanks!
