### ISSUE TITLE
Copying and pasting tabbed content not working since update.

### ISSUE THREAD

**Issue by jon64digital** [Microsoft/vscode#32431]
- VSCode Version: July Update
- OS Version: Win10

Steps to Reproduce:

1. Find any HTML code with tab indentation
2. Copy and paste code to a new line
3. Indentation will be correct for first line but subsequent will be 4 spaces to the right of where they should be.

I spend a long time wondering whether there was a problem with my code, maybe an unclosed tag but then it started happening on all files, not just HTML files but js files too. It has been happening since I updated to the July update earlier today.

**Comment by seesemichaelj** [comment]
This is not just an HTML issue; I'm seeing it with Javascript as well. I think this is a generic issue with the clipboard/indentation of the editor and has been introduced recently.

I have seen this bug before in Atom (https://github.com/atom/atom/issues/5473 is just one of the handful of bugs that describe this problem). It has to do with already indented content (as @jon64digital specified in step 1). I would love to see this fixed! I may look into fixing it for Hacktoberfest

**Comment by seesemichaelj** [comment]
Turns out they turned on auto-indentation by default in the July update (https://code.visualstudio.com/updates/v1_15#_auto-indentation). I verified the behavior is no longer seen when I turn auto indentation off.

I'm not sure if this is how auto indentation is supposed to work, but it appears to happen depending on how previous lines are indented (very similar to the atom/atom#5473 issue). I don't think I'll attempt fixing this as I think there is some design choice that made the code act this way that I may get pushback in pushing if I found how to fix it.

I recorded some different use cases using different settings. You'll see me selecting text, I then copy it, and paste it. My VS Code version is 1.16.1

![peek 2017-10-03 11-26](https://user-images.githubusercontent.com/549323/31133605-05d8aa6c-a82e-11e7-9746-f6200215fa30.gif)

**Comment by rebornix** [comment]
@seesemichaelj our indentation rules and logic may not work for every case at this moment, especially when everyone may have their own preference. But for the particular issue you posted in above gif, it's already fixed in Insider.

I made some changes to auto indent for pasting to mitigate the issue @jon64digital described. If there are other unexpected scenarios, please let me know, thanks in advance!
