### ISSUE TITLE
react emmet

### ISSUE THREAD

**Issue by linmiss** [Microsoft/vscode#32435]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.In the react emmet is very inconvenient, the previous version is better

Reproduces without extensions: Yes/No

**Comment by miaojiuchen** [comment]
Emmet not work in reactjs file using Tab after the update, feel so sad :(

**Comment by miaojiuchen** [comment]
I solve this by doing these:
Open Preference -> Keyboard Shortcuts
Enter "editor.emmet.action.expandAbbreviation" and add a keyboard Shortcuts "Tab"

**Comment by ramya-rao-a** [comment]
@linmiss @miaojiuchen 

Your options:

- If on VS Code 1.15 use emmet from suggestions, bind any other keyboard shortcut (other than tab)  for the emmet expand command. tab is not recommended in this version, as there is no fallback to indenting when emmet doesn't apply. So you won't get to add indent in any file
- If on VS Code 1.16 Insiders build (you can get it from https://code.visualstudio.com/insiders), then set `emmet.triggerExpansionOnTab` to `true`. You will be able to use tab for emmet. The appropriate fallback for tab exists so that you get indentation when emmet is not applicable. Emmet in suggestions will also exist for easy previewing of the expanded value

We really wanted to move away from using tab for emmet due to the problems it brings for non emmet users. But there has been feedback requesting the tab->emmet feature back, and so it is now available in the latest Insiders.

**Comment by miaojiuchen** [comment]
I change to use Ctrl + E ...

**Comment by linmiss** [comment]
@ramya-rao-a @miaojiuchen thanks.

**Comment by jens1o** [comment]
> We really wanted to move away from using tab for emmet due to the problems it brings for non emmet users. But there has been feedback requesting the tab->emmet feature back, and so it is now available in the latest Insiders.

Well, I'm that used to the current situation, and I'm staying there. I hope the original way will be supported. 😭

**Comment by jasonHzq** [comment]
I have changed other keyboard shortcut, but get error: Emmet: Invalid abbreviation。

**Comment by jasonHzq** [comment]
I think change user habit is really a bad decision!

**Comment by ramya-rao-a** [comment]
@jens1o Am confused.. are you talking about tab->emmet feature or the suggestions

@jasonHzq We are bringing back the tab -> emmet feature in the VS Code 1.15.1 which will be released in 2 or 3 days. Until then, use the latest Insiders and set `emmet.triggerExpansionOnTab` to `true`

@jasonHzq Please share the example where you got that error

**Comment by jens1o** [comment]
I'm talking about the suggestions. I really like them. And I won't get back to <kbd>Tab</kbd> key, because nowadays, I'm really addicted to the advantages it provides.

**Comment by ramya-rao-a** [comment]
@jens1o The suggestions will stay. No changes there.

Only change is that the tab triggering emmet will be brought back. But not by default. Users will have to opt-in by setting `emmet.triggerExpansionOnTab` to `true`.
