### ISSUE TITLE
 Emmet in preprocessors?

### ISSUE THREAD

**Issue by gangstein** [Microsoft/vscode#32447]
Hello! "Emmet 2.0" works correctly with preprocessors? Specifically interested in the stylus and jade. My abbreviation is not correctly unfolding, I have to choose from the proposed options arrow control. Is it a feature, or a bug? Sorry for my english =)

**Comment by taigabrew** [comment]
Same here. Not expanding abbr on tab when Code not suggest something, eg. type "pb" then "esc" then "tab" (expect to expand padding-bottom). Tested on *.css, *.scss, *.html, *.vue
MacOS 10.12.6, VSCode 1.15

**Comment by mrmlnc** [comment]
Expand by <kbd>Tab</kbd> will be returned in the July Recovery Build (1.15.1). Now you can read [Realese Notes](https://code.visualstudio.com/updates/v1_15#_emmet-20) and [Blog](https://code.visualstudio.com/blogs/2017/08/07/emmet-2.0).

**Comment by EliazTray** [comment]
I like to use tabs and then not space indents. so when i tab,it always notice 
![image](https://user-images.githubusercontent.com/16015431/29269441-05e808d0-8124-11e7-9264-f55088d5e85f.png)
how to resolve it? :(

**Comment by ramya-rao-a** [comment]
@gangstein Please give examples for what doesnt work in stylus and jade

@taigabrew Like @mrmlnc said, tab for emmet feature was disabled in the July release (1.15) and will be back in the July Recovery Build (1.15.1) in a few days.
Until then, you can use the [Insiders build] (https://code.visualstudio.com/insiders) which has the tab feature

@EliazTray Yes, that is why we recommend not to bind tab to emmet in 1.15. You can check out the [Release Notes](https://code.visualstudio.com/updates/v1_15#_emmet-20) or the [Emmet blog](https://code.visualstudio.com/blogs/2017/08/07/emmet-2.0)

Use any keyboard shortcut other than tab or use the  [Insiders build] (https://code.visualstudio.com/insiders)or wait for VS Code 1.15.1

**Comment by gangstein** [comment]
@ramya-rao-a For example, in the stylus when I type "bgc", the abbreviation unfolds "border-clip" instead of "background-color". I had previously disconnected the suggestion / auto-completion lists, and I was based on knowledge of the abbreviations, sometimes using ctrl + space

**Comment by ramya-rao-a** [comment]
@gangstein 

I tried the `bgc` example you gave. Looks like emmet is the second option there, because of the other snippets that match better with `bgc`. 

If you are used to working after disabling the suggestion list, I would suggest any of the 3 options below

- Bind a keyboard short cut (not tab) to `editor.emmet.action.expandAbbreviation` command and you can use that to expand all emmet abbreviations
- Or use the latest Insiders (https://code.visualstudio.com/insiders) and set `emmet.triggerExpansionOnTab` to `true` . That will give you the tab -> Emmet feature back as before.
- Or wait for tomorrow's release of VS Code 1.15.1 and set `emmet.triggerExpansionOnTab` to `true` . That will give you the tab -> Emmet feature back as before.
