### ISSUE TITLE
Can't search root folder names in quickopen

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#32444]
- Have a multiroot workspace with folders 'foo' and 'bar'
- Search 'foo' in quickopen
- No results 🐛 
- Search 'f1' where 'f1/file.txt' is some file in 'foo'
- It appears ✔️

**Comment by bpasero** [comment]
@roblourens I am not sure how much sense it makes to show folders in quick open results? what should happen when you open a folder? can you clarify?

**Comment by roblourens** [comment]
I don't mean show the folders themselves, I just want to be able to be able to filter with the root folder name.

Examples:

I can find 'querybuilder' files under some 'workbench' folder
![image](https://user-images.githubusercontent.com/323878/29259381-66d3c8a8-8077-11e7-9d94-7bd718bc8eab.png)

I can see stuff under 'build/'
![image](https://user-images.githubusercontent.com/323878/29259391-7c9a6002-8077-11e7-8ef3-f5d196a4b40e.png)

And it would be useful if I could search 'vscode-chrome-debug launch.json' to get the 'launch.json' under a vscode-chrome-debug root, as opposed to some other root folder

**Comment by bpasero** [comment]
@roblourens if you give me some pointers I can look into it because I think it would be cool to have. What I wonder is why this does not work:

![image](https://user-images.githubusercontent.com/900690/32979387-9b6104b8-cc54-11e7-84b4-46256065a2ec.png)

But this does:

![image](https://user-images.githubusercontent.com/900690/32979388-a50aa758-cc54-11e7-9148-8cfe22db75c1.png)

Wouldn't this be just a matter of checking if the typed folder name is the beginning of any root folder and then automatically treating it as if `<root>/` was typed?

**Comment by roblourens** [comment]
I think that's just because they're in Recently Opened. I think the fix will be in fileSearch.ts. `isFilePatternMatch` is only looking at each candidate's relative path in the root. We probably just need to add the root folder name to the "relative path" of each candidate file.

**Comment by bpasero** [comment]
@roblourens ah yeah, you are right. To prevent spam from recently opened we only consider the path portion from those bucket when the user is intentionally searching for paths by having the path separator in the query.

**Comment by bpasero** [comment]
@roblourens is `fileSearch` still being used, isn't it the old implementation without RipGrep?

**Comment by roblourens** [comment]
Yeah, that's where it spawns ripgrep (or `find`, or does the node traversal) and checks all the results against the search pattern.

cc @chrmarti

**Comment by bpasero** [comment]
@roblourens I guess this one is a bit tricky because it actually depends on the workspace setup for how we want to match against results:
* single root: match on the path portion relative to the folder
* multi root: match on the path portion relative to the workspace

Example:
* given a path of `/some/development/folder/myfile.txt`
* and a query of `folder myfile`
* if the user has `folder` opened: we do not expect a match
* if the user has a multi-root workspace configured on `folder`: we do expect a match

So somewhere down where we convert the absolute path to a relative one for matching we need to know if the user is in a multi root workspace or not.

**Comment by chrmarti** [comment]
The `FileMatchItemAccessor` passed in here seems to be doing this: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/search/node/rawSearchService.ts#L258

**Comment by roblourens** [comment]
Somehow you need to check `folderQueries` that we have here: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/search/node/fileSearch.ts#L120

for .length > 1. That should be the case iff this is a multiroot workspace. Then ripgrep is spawned and you need to add the folder name to the relative paths coming back, over here: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/search/node/fileSearch.ts#L206

**Comment by bpasero** [comment]
@roblourens unfortunately the number of folders can still be 1 but you can be in a multi root workspace, even just with 1 folder. So this might need a new option for the query.

**Comment by roblourens** [comment]
Ah that's right.

**Comment by bpasero** [comment]
I take it back, we only show the extra root folder name if we have more than one folder in the workspace, so it looks like we could use that as a guess.

Frankly speaking `fileSearch.ts` is super hard for me to understand and any change in there I feel I would break something. It seems that the [`relativeFiles`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/search/node/fileSearch.ts#L245) array that we produce from the RipGrep search needs the root folder for each relative file so that the matching is proper. But doing that of course results in all paths being wrong because the absolute path will have duplicate root folders in them.

I am not considering to help out anymore as I find it impossible to understand the code :).

**Comment by bpasero** [comment]
@denysvitali `ticino` was the original codename for VS Code. Since we are working from Switzerland (Zurich) we picked names from here. That playground code is actually from a TypeScript sample ("Mankala").

**Comment by Nasafato** [comment]
@roblourens Would there be anything we could do to help make progress on this? Either design-decision-wise, or something else? Happy to be of service.

**Comment by radix** [comment]
As far as I can tell, this is now fixed, at least the problem as I described it in #68165. Thank you very much!

**Comment by AaronFriel** [comment]
I would very much like to see implemented the solution @bpasero described. :+1: to being able to type root folder names.

**Comment by SBRK** [comment]
That would be really nice. A typical example is when you have several npm packages in your workspace and you want to `Ctrl + P` to the `package.json` of one of the folders in the workspace. In Sublime Text I would type the first letters of my package then `package.json`. In VS Code I have to type `package.json` and select the right one, it's much less convenient
