### ISSUE TITLE
"Go to definition" - Node.js - Not working with simple example

### ISSUE THREAD

**Issue by reliasn** [Microsoft/vscode#32456]
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:16:18.034Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
sublime-keybindings|ms-|2.9.1

My "project" has just 2 files: ``app.js`` and ``hey.js``. In the example below, VSCode isn't able to find the ``hello`` function in the other file.

![](https://i.imgur.com/IYAE8pp.png)

If I declare ``hello`` local by putting ``var`` before, then it works fine, but this is not what I want since I need to call the function from ``app.js``:

![](https://i.imgur.com/eVrPkBt.png)

This issue seems to happen with anything declared in the global scope, including variables.

Do I have to add something else in order to fix this? Am I missing some configuration step? Keep in mind that I'm not following any coding good practices here.

- VSCode "About" (tested with both Stable and Insider builds):
![](https://i.imgur.com/sW4ZzWv.png)
![](https://i.imgur.com/WRREXnz.png)

**Comment by mjbvz** [comment]
Yes, our intellisense doesn't support mixing module and non-module files this way. In this case, `app` is considered a module file since is uses `require`, while `hey` is not since it is not since it does not use `module` or `export` or `import` or `require`.

If you enable [`checkJs`](https://code.visualstudio.com/Docs/languages/javascript#_type-checking-and-quick-fixes-for-javascript-files), you'll see this error reported:

![screen shot 2017-08-16 at 1 36 10 pm](https://user-images.githubusercontent.com/12821956/29384146-e4138d00-8287-11e7-983a-155a691f7d1e.png)

This behavior is as-designed. One possible workaround is to create a `d.ts` file that declares all the globals in your project: https://code.visualstudio.com/Docs/languages/javascript#_global-variables-and-type-checking

**Comment by reliasn** [comment]
Thanks for clarifying the problem. I suppose this Intellisense design affects not only "Go to definition", but also "Go to Symbol in File" and "Go to Symbol in Workspace", correct? I thought I could at least use these 2 instead of "Go to definition", but it looks like the Intellisense still isn't able to find the symbol in that first example that I mentioned above.

Finally, are there any plans to make this design more flexible? I'm coming from Sublime Text and have also used Webstorm in the past. Both tools are able to find the symbols and definitions just fine. The Node.js projects that I work on rarely use ``module.exports``, so the files aren't split in modules. ``require`` is used just to define everything that needs to run. So if I want to use VSCode, I'd need to refactor all files and my peers won't be happy to know that I'm doing this only because of a different editor. Even if I used the workaround you mentioned and created this ``d.ts`` file, it will be hard to keep track of all globals across all files in the projects.

For me, the main feature that VSCode has for Node.js development is the integrated debugger. Even the documentation says that:
![](https://i.imgur.com/HP8wwJZ.png)
But if I can't navigate my code efficiently, then it will be hard to switch to VSCode.

**Comment by mjbvz** [comment]
Yes, this limitation effects any operation that involves finding usages of a symbol in JavaScript code. Our JavaScript language support is powered by TypeScript, and TypeScript is not able to understand some JavaScript patterns. Using globals and `require` is valid Node, but it is also not a pattern we have prioritized supporting or, I suspect, really will ever get around to supporting. With limited resources, we have focused on supporting more modern JS patterns, which means properly modularized code.

While I don't know the situation with your codebase, I highly recommend that you consider refactoring the code to use a module pattern with proper dependencies, not because it will improve the VS Code editor experience but because it will make the code itself far more maintainable and easier to reason about.
