### ISSUE TITLE
No Format Document option in command pallette

### ISSUE THREAD

**Issue by kingscott00** [Microsoft/vscode#32497]
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:16:18.034Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.12.0
vscode-icons|rob|7.12.0
plsql-language|xyz|1.0.4

---

Steps to Reproduce:

1. Fresh install of v 1.15. I tried the following on a .cs file before and after installing csharp extension.
2. Command Pallete does not show "Format Document". Pressing Alt+Shift+F doesn't do anything. Pressing Ctrl+k, Ctrl+f says  "The key combination (Ctrl+k, Ctrl+f) is not a command.

Reproduces without extensions: Yes/No

**Comment by ramya-rao-a** [comment]
Did you install https://marketplace.visualstudio.com/items?itemName=ms-vscode.csharp ?
That extension doesnt provide any formatting support as far as I know.

https://marketplace.visualstudio.com/items?itemName=Leopotam.csharpfixformat on the other hand provides formatting support. I havent tried it myself, but the docs say so.

Try it.

**Comment by kingscott00** [comment]
The problem is that I do not have the default built in "Format Document" option showing at all in command palette. This command is not dependent on any extensions.

I tried the csharpfixformat extension you suggested and disabled the other extension. Still same problem.

**Comment by ramya-rao-a** [comment]
Formatting feature in VS Code is not built-in. It comes from extensions.

Some of the extensions like html and typescript which are built-in come with formatting feature and so you will see the `Format Document` command when you have an html or typescript file open.

But for almost all other languages, you need to install an extension.
If these extension register a format provider, then you will see the "Format Document" command in command pallet and in the context menu

In case of C#, the author of "CSharp: Fix Format" for some reason decided to have a separate command for formatting instead of using the format provider model. This is why you dont see the "Format Document" command even after installing the extension.

Please log an issue in the repo for that extension so that they can fix it
