### ISSUE TITLE
PowerShell formatting and indent bug when using the backtick character

### ISSUE THREAD

**Issue by woowil** [Microsoft/vscode#32494]
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:16:06.988Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: the listing length exceeds browsers' URL characters limit
---

Steps to Reproduce:

1. PowerShell 
Settings.json:
"editor.formatOnSave": true,
 "editor.formatOnType": true,

### Desired Formatting:
<pre>
Get-Process |  ForEach-Object `
   -Begin {
      $Count = 0
   } `
   -Process {
      $Count++
   } `
   -End {
      $Count
   }
</pre>

### Bug Formatting
<pre>
Get-Process |  ForEach-Object `
   -Begin {
    $Count = 0
} `
    -Process {
    $Count++
} `
    -End {
    $Count
}
</pre>

Reproduces without extensions: Yes/No

**Comment by daviwil** [comment]
@aeschli This seems to be caused by the new default of `editor.autoIndent: true`.  I've been getting a few reports of code being improperly formatted on paste with this setting turned on.  Is there an easy way to test my [indentation regexes](https://github.com/PowerShell/vscode-powershell/blob/master/src/main.ts#L51) to make sure they work correctly with this new default behavior?

**Comment by daviwil** [comment]
This issue was moved to PowerShell/vscode-powershell#994

**Comment by aeschli** [comment]
@rebornix Peng, can you help?
