### ISSUE TITLE
Missing the canvas tag. Emmet abbreviation.

### ISSUE THREAD

**Issue by opencreative** [Microsoft/vscode#32525]
- VSCode Version: Code 1.16.0 Insider
- Emmet

Hello. Please add one more ntml tag (canvas).

**Comment by MattMcMurray** [comment]
I've noticed since the most recent update, a number of "semantic" HTML tags aren't working in Emmet anymore (e.g., `<nav>`, `<header>`, `<canvas>` etc.). I first noticed in VueJS component files, but they don't work in HTML files either. Seems that only the most "common" HTML tags are coming up as suggestions. Triggering suggestions with `Ctrl+Space` isn't working either.

VSCode Info:
```Version 1.15.0
Commit 8b95971d8cccd3afd86b35d4a0e098c189294ff2
Date 2017-08-09T20:09:15.006Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0
Architecture x64
```

OS Info:
```Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
```

**Comment by ramya-rao-a** [comment]
@MattMcMurray That has been fixed in the latest Insiders which you can get from https://code.visualstudio.com/insiders

Or you can wait for 1.15.1 release of VS Code that should be out tomorrow.

**Comment by ramya-rao-a** [comment]
https://github.com/Microsoft/vscode-emmet-helper/issues/5 has the list of tags that are currently supported in the Insiders and will be in tomorrow's 1.15.1 release.

**Comment by MattMcMurray** [comment]
@ramya-rao-a Awesome! Thanks for the quick response.

**Comment by ramya-rao-a** [comment]
No problem, let me know if there is anything missing from that list

**Comment by ramya-rao-a** [comment]
Support for `canvas` will be out in tomorrow's insiders
