### ISSUE TITLE
EH debugging ("inspector"): can break before sourcemaps are done loading

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#32536]
OS: elementary OS 0.4.1 Loki (Built on "Ubuntu 16.04.2 LTS")

- use hello world extension
- set breakpoint in `extension.ts:12`
- F5 and trigger "hello" command

Observe:
breakpoint is hit and after some time sourcemap loading errors appear in debug console and the STACKTRACE refers to the extensionHostProcess.js instead of *.ts:
![2017-08-15_12-22-23](https://user-images.githubusercontent.com/1898161/29312405-6b3b7186-81b5-11e7-87dd-67adb193f5a0.png)

Loading the sourcemap urls in a browser works fine. 
Loading sourcemaps works fine on macOS.

**Comment by roblourens** [comment]
Works for me. Was the build brand new? If it fails again can you paste the sourcemap URL into the issue?

I do see an issue where it breaks on the exception in git.ts but the sourcemaps have not finished downloading, so it shows git.js. The fix for that would involve not reporting the pause event to vscode if it knows its waiting for a sourcemap to be resolved for a script in the paused stack. Or waiting to respond to stackTraceRequest. Not crazy about either of those.

**Comment by roblourens** [comment]
Filed https://github.com/Microsoft/vscode-chrome-debug-core/issues/229 for that one.

**Comment by roblourens** [comment]
Actually, you're surely seeing the same problem that I just described. Assuming the extension was activated immediately, then the sourcemap was probably still being downloaded. 

I saw this today on mac, while testing, so I should probably do something about it.

Does node-debug wait for sourcemaps to finish downloading?

**Comment by weinand** [comment]
Yes, node-debug waits (with the result that hitting the first breakpoint has a noticeable delay).
But since I cash the the sourcemap (based on its commit ID), only the first breakpoint hit after a new release is slow.

**Comment by weinand** [comment]
BTW, today I noticed the problem on macOS too. So it is not linux specific.

**Comment by roblourens** [comment]
Oh, I forgot that I disabled the downloaded sourcemap caching. I need to remember why I did that and fix it. https://github.com/Microsoft/vscode-chrome-debug-core/commit/66bef3ae7d785035cb4ca7e0178631bcad40d249

**Comment by roblourens** [comment]
I disabled the caching because it caused lots of problems for chrome-debug, where a dev setup often serves sourcemaps from a url, and our sourcemap caching strategy will cache the first instance of a url it sees, and never download the updated one.

Has that never been a problem for node-debug? It works for the extensionhost sourcemaps, which include the version in the url and never change, but could there be a dev setup for some node framework that gives the same problem that I had with chrome-debug? I haven't tried it, but it seems like webpack-dev-server would give the same issue.

**Comment by roblourens** [comment]
I have it working with the latest changes from node-debug, just need to fix some unit tests.
