### ISSUE TITLE
VSCode Debugging Toolbar is hidden behind message pop up

### ISSUE THREAD

**Issue by DanielMeixner** [Microsoft/vscode#3258]
All Error/Warning or simple "Update Available" Messages from VSC hide the debugging bar when I start debugging. 
As a user I'm confused to not be able to see & interact with the toolbar (and might not be aware that the debugger is running at all).
I'm probably supposed to close those messages, but there might be reasons to keep them open (e.g. as a reminder).

Found with: VS Code Version 0.10.8, running on a Mac.

**Comment by isidorn** [comment]
I believe we are doing a good thing here, messages should be on top of the debugger toolbar because they should be read and closed first (they are like notifications).
Also the debugger toolbar has the alternative of being triggered by shortcuts in the case that there are messages blocking the toolbar.

I am not a big fan of messages pushing the toolbar down, since they also do not push quick open or any other ui we have.
VSCode is still orange, so you still have a clear notification that debugger is running even though the toolbar is hidden.

Leaving this as a feature request

**Comment by bpasero** [comment]
@stevencl @bgashler1 one of the issues with notifications
