### ISSUE TITLE
The debug "launch" setting throws error when attempting to "Copy to Settings"

### ISSUE THREAD

**Issue by zelein** [Microsoft/vscode#32593]
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:16:18.034Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|don|0.7.0
EditorConfig|Edi|0.9.4
tslint|eg2|0.17.0
vscode-icons|rob|7.12.0

---

Steps to Reproduce:

1. Go to User Settings
2. Open "Debug" category
3. Click pencil next to `"launch": {}` and click `Copy to Settings`
4. Error should appear that says `Unable to write to User Settings because {0} does not support for global scope.`

Reproduces without extensions: Yes

**Comment by sandy081** [comment]
@weinand @isidorn  By defining `launch` as a first class setting (#23881), it started appearing in Defaults and intelli-sense etc. Description says that this is used to configure Global launch configurations. But one can also configure in workspace and folders which makes it ambiguous to `launch.json`. Not sure if it is a good idea to fix the warning by defining it as a setting, instead we can add it only to json schema? 

This issue is the side effect of #23881. `launch` and `task` namespaces are treated specially as the respective configurations come from respective `launch.json` and `task.json`. Config edit API writes such properties only into these files given the Workspace target. It bails out for all other targets.

**Comment by isidorn** [comment]
@sandy081 I understand the limitations however in a perfect world we would have a mechanism to define settings which are user only and not workspace and folder. 
However since we do not have that at the moment I am fine with both behaving as we currently do or reverting #23881 to keep this setting "special".

@weinand thoughts?

**Comment by isidorn** [comment]
If I remove it from the schema users will get an error when they add it to their user settings, which is far worse than the current behavior.

A potential solution is to allow contributing settings which are user only. An alternative is to handle the error more gracefullly.

I do not plan to do anything about this case -> unassigning myself.

**Comment by sandy081** [comment]
Makes sense to have just global settings. This will be a big feature. Some mitigation can be done for this bug is to remove the copy action in the editor for this setting.
