### ISSUE TITLE
Add ability to clear recently opened files from open file dialog

### ISSUE THREAD

**Issue by JordanBelford** [Microsoft/vscode#3260]
As far as I can tell, there is no way to clear the list of recently opened files that appears on the CMD+P window.

My problem: I have excluded node_modules from searching. Sometimes I open a package.json file from inside node_modules by navigating from the explorer. 

After that, CMD+P then typing 'package.json' shows all of the package.json files that are in the recently opened list, even though some are from the node_modules directory which is normally excluded from search. 

This can be useful behavior, but the user should be able to clear out the recently opened list so that the search exclusion rules can go back to hiding those files. 

There should be a clear all recently opened files button/command. It may be worth considering a way to clear specific items with an 'x' on the open file dialog that appears with CMD+P. Or perhaps a special command for clearing recently opened files that match any search exclusion rules.

![screen shot 2016-02-22 at 11 46 37 am](https://cloud.githubusercontent.com/assets/1946538/13230368/f30685e8-d959-11e5-93cf-6af3d33782fb.png)

Sounds similar to #1662, but that one is for clearing recent files from the OSX dock icon.

**Comment by Spown** [comment]
This is somewhat related to my issue #3215 since every time an unwanted file is opened via debugger - it puts itself into the dropdown list. So almost after any debug session it gets even harder to restore the workspace because the originally opened in that edit view file drops on the bottom of totally cluttered with trash list.

**Comment by bpasero** [comment]
You can remove entries from the list by opening an entry and invoking the "Close File" command (Cmd+K W).

I do agree though that it is nice to have more control over the recent list.

**Comment by JordanBelford** [comment]
Thanks @bpasero. The 'Close File' command solves my problem. If this feature gets implemented, it would still make managing the recent list more efficient and intuitive. 

It seems odd that clicking to remove files from the 'Working Files' list does not remove the files from the recently used list.

**Comment by dotnetCarpenter** [comment]
@JordanBelford I was thinking the same. @bpasero  How about syncing *WORKING FILES* and *recently opened*?

I usually navigate through my files via `ctrl + tab` and `ctrl + shift + tab` but control which files I work with in *WORKING FILES*. Since open files automagically ends up in *WORKNG FILES* it is nice a UX if I can control my files navigation through *WORKNG FILES*.

**Comment by dotnetCarpenter** [comment]
@bpasero In case you guys go with my proposed file navigation flow, then *recently opened* should be renamed to *working files*.
About the *recently opened* files feature - I don't have any need for it.

**Comment by dotnetCarpenter** [comment]
@bpasero just found your answer: http://stackoverflow.com/questions/30813614/keyboard-shortcuts-for-navigating-working-files-in-vscode

>The shortcut is Cmd+K Up and Cmd+K Down (on Windows use the Ctrl key).
IMHO, that's is annoying. `Navigate history` is much nice - only it should be *WORKING FILES*.

Gonna [re-map the keyboard to work as I proposed](http://stackoverflow.com/questions/30813614/keyboard-shortcuts-for-navigating-working-files-in-vscode#answer-33625951) but is sorely missing the UI from the `Navigate history`.

**Comment by bpasero** [comment]
In our latest release you can quick open working files, you can also have a key binding for it. Use the ~ prefix in quick open to get that list.

**Comment by dotnetCarpenter** [comment]
Not sure what you mean. Do you mean `ctrl+k+down` or `ctrl+p` and then `~`? Anyway, `ctrl+k+down` cycles down through the *working files* but without the nice UI dropdown list that is right in front of my eyes. Instead I have to look to the upper left of the screen which is great deal slower once you get used to use *recently opened*.

My point is, that *working files* **is** my recent files because each file I open ends up in the *working files* list. The UX for *recently opened* files is extremely well done but lack the ease of removing files I don't want to cycle through.

So vscode has two almost identical features, where one is easy to manage (*working files*) and the other is easy to use (*recently opened*).

Why not merge the two features?

**Comment by dotnetCarpenter** [comment]
Just to be clear. Don't change the UI. Just keep *working files* and *recently opened* in sync. Try it out in a beta. I'm sure it will prove to be a very nice UX

**Comment by bpasero** [comment]
@dotnetCarpenter it is `Ctrl+K Ctrl-P` to open the working files picker.

**Comment by dotnetCarpenter** [comment]
@bpasero thanks. Is there any way to map file navigation through *workingFilesPicker*? I would like the same UX as tapping through *recent files* but I can't find the right commands.
First I tried with
```json
	{
		"key": "ctrl+tab",
		"command": "workbench.files.action.openNextWorkingFile"
	},
	{
		"key": "ctrl+shift+tab",
		"command": "workbench.files.action.openPreviousWorkingFile"
	}
```
But that quick change through the *working files* which is a bit too much screen flickering. I then tried with 
```json
{
		"key": "ctrl+tab",
		"command": "workbench.files.action.workingFilesPicker"
	}
```
But that just opens the file picker. Is there commands for cycling through the *workingFilesPicker* in the same manner as *recent files*?

**Comment by bpasero** [comment]
The ones triggering navigation in any quick open are:

```json
{ "key": "ctrl+tab",              "command": "workbench.action.quickOpenNavigateNext",
                                     "when": "inQuickOpen" },
{ "key": "ctrl+shift+tab",        "command": "workbench.action.quickOpenNavigatePrevious",
                                     "when": "inQuickOpen" }
```

You can try it out now already by first typing the keybinding for working files list and then Ctrl+Tab. You can rebind those keys to get what you want.

**Comment by bpasero** [comment]
For June we plan to provide an action that clears:
* the editor navigation history (Cmd+P)
* the history of recently closed tabs
* the forward/backward history

**Comment by CreepGin** [comment]
For people who got here searching for how to clear the history (cmd+shift+p): 

![image](https://cloud.githubusercontent.com/assets/666527/17654738/518ffd80-6274-11e6-82a0-4764ead76190.png)

Though I must admit, it would be nice to be able to remove specific files from the history.

![image](https://cloud.githubusercontent.com/assets/666527/17654791/eba444f8-6274-11e6-91dd-20e1f44a44e1.png)

Adding a "X" icon next to each item sounds good to me. This way we don't need to clear the entire history to get just one bad item out of there.

**Comment by bpasero** [comment]
@CreepGin you can use the "Remove from Editor History" command to remove one entry from the list. It will open the picker to select a file to remove. I know this is not the ideal UI but is a workaround for not having "X" in the list.

![image](https://cloud.githubusercontent.com/assets/900690/17656225/c474991c-62b7-11e6-81b6-7886035a03cd.png)

**Comment by CreepGin** [comment]
@bpasero Thanks! That'll do it for now.

As several others have pointed out in issues regarding the Recently Opened list (cmd+p), a config option such as `history.exclude` may be in order. Or, have the Recently Opened list respect `search.exclude`. 

This is because the Recently Opened list is always prone to containing bad items as time goes on and we accidentally open unwanted files in the editor.

**Comment by dbrodie** [comment]
@bpasero Sadly that doesn't work for files that don't exist anymore. I had a file that was moved and I couldn't remove the old file.

**Comment by bpasero** [comment]
This command works for any entry, there is no dependency on the file existing on disk or not (there is not even a check).

**Comment by dbrodie** [comment]
Sorry, you are correct, I misunderstood how to use the feature.
Thank you, works great!
