### ISSUE TITLE
Support quote wrapping in plain text mode

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#32616]
From https://github.com/Microsoft/vscode/issues/14484#issuecomment-322671691

**Comment by usernamehw** [comment]
Isn't this doable with keybindings? Example for `'` `"` `[` `(` `{`:
```javascript
{
    "key": "shift+9",
    "command": "editor.action.insertSnippet",
    "when": "editorTextFocus && editorHasSelection",
    "args": {
        "snippet": "(${1:${TM_SELECTED_TEXT}})"
    }
},
{
    "key": "shift+0",
    "command": "editor.action.insertSnippet",
    "when": "editorTextFocus && editorHasSelection",
    "args": {
        "snippet": "(${1:${TM_SELECTED_TEXT}})"
    }
},
{
    "key": "[",
    "command": "editor.action.insertSnippet",
    "when": "editorTextFocus && editorHasSelection",
    "args": {
        "snippet": "[${1:${TM_SELECTED_TEXT}}]"
    }
},
{
    "key": "]",
    "command": "editor.action.insertSnippet",
    "when": "editorTextFocus && editorHasSelection",
    "args": {
        "snippet": "[${1:${TM_SELECTED_TEXT}}]"
    }
},
{
    "key": "shift+[",
    "command": "editor.action.insertSnippet",
    "when": "editorTextFocus && editorHasSelection",
    "args": {
        "snippet": "{${1:${TM_SELECTED_TEXT}}}"
    }
},
{
    "key": "shift+]",
    "command": "editor.action.insertSnippet",
    "when": "editorTextFocus && editorHasSelection",
    "args": {
        "snippet": "{${1:${TM_SELECTED_TEXT}}}"
    }
},
{
    "key": "shift+'",
    "command": "editor.action.insertSnippet",
    "when": "editorTextFocus && editorHasSelection",
    "args": {
        "snippet": "\"${1:${TM_SELECTED_TEXT}}\""
    }
},
{
    "key": "'",
    "command": "editor.action.insertSnippet",
    "when": "editorTextFocus && editorHasSelection",
    "args": {
        "snippet": "'${1:${TM_SELECTED_TEXT}}'"
    }
},
```

**Comment by joelricci** [comment]
It seems to be doable with what's referred to as "Smart Bracket Matching", check the documentation here with provided example for TypeScript:

https://code.visualstudio.com/docs/extensionAPI/language-support#_smart-bracket-matching

```
{
   ...

   "surroundingPairs": [
       ["{", "}"],
       ["[", "]"],
       ["(", ")"],
       ["<", ">"],
       ["'", "'"],
       ["\"", "\""],
       ["`", "`"]
   ]
}

**Comment by bkowshik** [comment]
Thank you @usernamehw!

Your snippet works for single quotes. How do I get the same behavior for double quotes?
```
{
    "key": "'",
    "command": "editor.action.insertSnippet",
    "when": "editorTextFocus && editorHasSelection",
    "args": {
        "snippet": "'${1:${TM_SELECTED_TEXT}}'"
    }
}
```

**Comment by breams** [comment]
It's especially confusing because bracket surrounding (with `()`, `{}`, `[]`) works in plaintext the way it does in all the other syntaxes. The lack of single and double quotes seems really counterintuitive. Can you provide us with a use case that would make this undesirable behaviour to have on by default?

**Comment by twnaing** [comment]
for double quote

```json
  {
    "key": "shift+'",
    "command": "editor.action.insertSnippet",
    "when": "editorTextFocus && editorHasSelection",
    "args": {
      "snippet": "\"${1:${TM_SELECTED_TEXT}}\""
    }
  }
```

**Comment by phaibin** [comment]
I absolutely agree this behavior should be default like other popular editors suck as Sublime Text and Atom.

**Comment by ZYinMD** [comment]
I agree plain text shouldn't be different, because let's suppose you selected some text and then pressed `'` or `"`:

- If you intention was to replace the selected text with quote marks, but were surprised to see it's surrounded by quotes, then all you need to do is press delete once, you'd do it on reflex and won't even think about it. Plus it's very uncommon for anybody to replace selection with quote marks in the first place.

- If on the other hand, your intention was to surround it with quotes, but were surprised to see it's replaced, then there's no reflex you can perform to fix the situation. You'd have to undo, then go to the beginning and the end of the selection to add quote marks. Very bad experience.

**Comment by dufferzafar** [comment]
Is it only just plain text mode where this feature doesn't work? Because for me it didn't work in Markdown either and I had to use @usernamehw's Keyboard shortcuts - which worked just fine!

**Comment by bxt** [comment]
I think the existing setting `editor.autoSurround` should have another option `all`. Right now you can set this to brackets or quotes which makes it work in plaintext for one of them. But never for both.
