### ISSUE TITLE
Emmet 2 not working in stylus after 1.15 release

### ISSUE THREAD

**Issue by HosseinAgha** [Microsoft/vscode#32626]
After 1.15 update emmet is completely unresponsive in `stylus` files. _I disabled all my user settings_  but had no luck. I use `language,stylus` package for highlighting.   
I heavily rely on emmet for styling and this has gotten super annoying. 

- VSCode Version: version 1.15
- OS Version: OSX 10.12.6

Steps to Reproduce:

1. Type `r12` on the stylus file there is no suggestions 

Reproduces without extensions: Cannot do this because I need stylus extension to do this

**Comment by ramya-rao-a** [comment]
@HosseinAgha it works for me. Am using the same extension `language-stylus`. Can you share a gif/video of the issue you are seeing?

![emmetstylus](https://user-images.githubusercontent.com/16890566/29369576-d727e0bc-8257-11e7-9bc8-448ea92382ec.gif)

**Comment by PetrBulanekSK** [comment]
I experience the same issue with this settings:

`"[stylus]": {
    "editor.quickSuggestions": false
 },`

Once I remove it, it works again. Btw, it was working with previous version of VS Code with this settings too.

**Comment by ramya-rao-a** [comment]
@PetrBulanekSK Without the quickSuggestions emmet was working before as it was bound to the tab key.

This was removed in 1.15 in favor of emmet in suggestions due to https://code.visualstudio.com/updates/v1_13#_emmet-abbreviation-expansion-in-suggestion-list

But we are bringing tab-> emmet feature back. Set `emmet.triggerExpansionOnTab` to `true` in the latest Insiders (https://code.visualstudio.com/insiders) or wait for VS Code 1.15.1 release (which will out today) and set the same setting to `true`. You will get emmet on tab back.

@HosseinAgha was your issue about emmet not working using tab in stylus files or emmet not working via suggestions in stylus files?

**Comment by PetrBulanekSK** [comment]
@ramya-rao-a Thanks a lot for quick reply. I'm looking forward to new release. 👍

**Comment by HosseinAgha** [comment]
@ramya-rao-a Thank you for your response. I think it has fixed after 1.15.1
