### ISSUE TITLE
Markdown document: Dragging tab to split editor doesn't work

### ISSUE THREAD

**Issue by jansensan** [Microsoft/vscode#32654]
- VSCode Version: 1.15.0 8b95971d8cccd3afd86b35d4a0e098c189294ff2
- OS Version: 10.10.5 (14F2511)

Steps to Reproduce:

1. Open a markdown document
2. Right-click on the document in the Explorer column and choose "Open Preview"
3. Try to drag the tab of the previewed document to the right or left of the editor to split the editor view (like with any other type of document)
4. No luck

Notes:
- If you press on the "Split Editor" button at the top right, the preview tab will then duplicate to create a split editor.
- If you drag the markdown file tab (not the preview tab), the split editor functionality will work as expected.

**Comment by bpasero** [comment]
I cannot reproduce, is this what you are doing?

![flicker_chrome58](https://user-images.githubusercontent.com/900690/29412587-bece1880-8359-11e7-9fb5-54155f7d2f18.gif)

**Comment by jansensan** [comment]
@bpasero You are starting from an already split editor. See the screencap below. When I try to drag the preview tab, the editor cannot be split, but when I drag the *.md tab, then it does.

![vscode-issue](https://user-images.githubusercontent.com/1410355/29424878-4f7202da-834f-11e7-861d-a9ffaf17563e.gif)

It's by no means a blocker, but it doesn't behave like other tabs do in this context.

**Comment by bpasero** [comment]
Yeah I can reproduce now. It does not always seem to happen though, after a while of dragging I can get the drop feedback to show up. This is probably an issue with the webview container we use for the markdown preview. 

Btw the same bug happens when you try to drag a file from the explorer over to the editor area over a markdown preview.

I think the only fix would be to overlay the editor area with a hidden div that takes all the drop events so that this becomes independent from the underlying editor.

**Comment by bpasero** [comment]
**Update**
Figured out that the explanation is quite simple: When dragging over the contents of the `webview` we never receive the [`dragenter`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/parts/editor/editorGroupsControl.ts#L1311) event because the `webview` just absorbs all eventing. If 2 editors are opened side by side, you can get the DND working by accident when moving the mouse over the scrollbar which seems to be outside of the `webview`.
