### ISSUE TITLE
Debug console: does not properly handle extended color sequences

### ISSUE THREAD

**Issue by perlun** [Microsoft/vscode#32696]
- VSCode Version: Version 1.15.0 (1.15.0)
- OS Version: Darwin ecvaawplun5.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64

Steps to Reproduce:

1. Run a task which executes a command that generates extended color sequences (such as the [rainbow](https://github.com/sickill/rainbow) Ruby gem).
2. As can be seen, certain escape sequences (probably traditional ANSI codes) work, whereas the extended ones are failing. More info about extended color codes can be found [here](https://en.wikipedia.org/wiki/ANSI_escape_code#Colors), where the 38,5 prefix is explained more.

<img width="1207" alt="image" src="https://user-images.githubusercontent.com/630613/29398799-52ca810c-832f-11e7-92dd-55109b25755a.png">

**Comment by weinand** [comment]
The debug console doesn't support extended color sequences because it was never meant to be a real terminal (e.g. it does not even support any input!).
We have no plans to change this.

Please configure your launch config to use an "integratedTerminal" or "externalTerminal". They might support extended colors.

**Comment by perlun** [comment]
Thanks @weinand 

> Please configure your launch config to use an "integratedTerminal" or "externalTerminal". They might support extended colors.

I will give this a try. I tried to change this by setting this:

```json
      "console": "integratedTerminal"
```

...however, it didn't seem to make any difference. I _guess_ this is a problem with the extension being used, not supporting `integratedTerminal` etc.

I will discuss with the extension author(s). Thanks anyway! 😄

**Comment by weinand** [comment]
@perlun yes, the debug extension have to opt into the terminals but after they have done, this get the functionality basically for free (because it is implemented on the VS Code side). 
Here is the link to the terminal feature that we've added a year ago: https://code.visualstudio.com/updates/v1_5#_additions-to-the-debug-protocol
