### ISSUE TITLE
Emmet suggestions stop in scss when there is an @include line below

### ISSUE THREAD

**Issue by dimondevs** [Microsoft/vscode#32703]
- VSCode Version: 1.15.1
- OS Version: MacOS Siera 10.12.6

Hello! I use mixins to write styles the BEM method. And I get such 2 bugs with emmet. The first is that if @include emmet is below the input line, it stops showing matches. The second when I write ovh I press tab, and then cmd + z then also the match will not seem any more. In other editors, I did not observe this.

Steps to Reproduce:
![1](https://user-images.githubusercontent.com/7513945/29405216-fa35e524-8345-11e7-853a-48daa9303a25.gif)

**Comment by anyclub** [comment]
the same problem
bdn, bd:n, fl:n, fln ...
and many more

**Comment by ramya-rao-a** [comment]
> @include emmet is below the input line, it stops showing matches

We have some validations in place to ensure emmet doesn't get suggested in every location in the file. For eg. it should be suggested inside the rule selector. In this case, for some reason the emmet parser thinks that the cursor is insider the rule selector (of the @import below) and so doesn't suggest emmet. I will look into this.

Until, then enable expanding of emmet abbreviations with tab by setting `emmet.triggerExpansionOnTab` to `true`. This way when you tab in the absence of the suggestion list emmet will get triggered

>  I write ovh I press tab, and then cmd + z then also the match will not seem any more

Here when you press tab, the suggestion list is open and the first choice gets selected.
When you do a cmd+z, the suggestion list disappears because it follows the same quick suggestion model as the rest of VS Code. Which is, they show up as you type and not otherwise.

You have 2 options here
- Enable expanding of emmet abbreviations with tab by setting `emmet.triggerExpansionOnTab` to `true`. This way when you tab in the absence of the suggestion list emmet will get triggered
- OR, hit `Ctrl+Space` to trigger suggestions manually after doing a `Cmd+z`

**Comment by ramya-rao-a** [comment]
@dimondevs @anyclub The fix will be available in tomorrow's Insiders build.

Please give it a try.

You should now be able to get emmet suggestions everywhere except inside the selectors.

**Comment by roblourens** [comment]
Seems the same in Insiders? I don't get Emmet above a `@include`
