### ISSUE TITLE
require is not defined in node.js console

### ISSUE THREAD

**Issue by darky** [Microsoft/vscode#32710]
- VSCode Version: 1.15.1
- OS Version: Linux 4.12.4-1-ARCH x86_64 GNU/Linux
- Node.js version: 8.4.0

### Since node 8.4.0 `require` is available from console

Steps to Reproduce:

1. Start debugging any node.js application
2. Type in "DEBUG CONSOLE" - `require`

Should be:
![image](https://user-images.githubusercontent.com/1832800/29408404-bab40326-8350-11e7-8d13-82d9d5afb280.png)

Wrong behaviour:
![image](https://user-images.githubusercontent.com/1832800/29408446-e4410ac2-8350-11e7-9803-772803dec3dc.png)

**Comment by weinand** [comment]
This is working fine for me:

![2017-08-17_14-47-14](https://user-images.githubusercontent.com/1898161/29413039-4ee16d40-835b-11e7-8cd1-606e57e9e572.png)

Make sure not to try this with VS Code extension host debugging because that uses Electron's builtin node version and not the globally installed version.

**Comment by darky** [comment]
Uses installed node.js 8.4.0
Problem is that you in debug now, you should run simple server and not set breakpoint

**Comment by weinand** [comment]
sorry, but the steps from above didn't say that this problems only occurs if the debugger is not stopped.

Why do you know that "require" should be available when not stopped?

**Comment by darky** [comment]
> sorry, but the steps from above didn't say that this problems only occurs if the debugger is not stopped.

Sorry, I not consider situation with breakpoint

> Why do you know that "require" should be available when not stopped?

Because it logical and revert situation is strange.
I can do in REPL any stuff, for example:
`1 + 1`
`Array.prototype.join.call([1, 2, 3, 4, 5], "-")`
But if I want `require` something I should set breakpoint and `require` will be available.
Also in Chrome Devtools all ok for example

**Comment by roblourens** [comment]
This is because `require` isn't a global, it's a value that's injected into a module by Node when it loads a module, so the console doesn't have access to it, unless it's paused and referencing some `require` name in scope.

Sometimes when paused, it still doesn't work, because if `require` is only referenced at the top of the file, then v8 will dispose it and it won't be available later when paused somewhere else in the file. This is a normal optimization that it does for other values too. 

Workaround for you - add a global reference to `require`, then it can be accessed at any time from the console. For example, add `console.require = require` somewhere in your program. Now you can run `console.require('fs')` from the console.

**Comment by roblourens** [comment]
Hold on, you're right about Node 8.4. This does work in Chrome devtools in 8.4, but not earlier. If they can support it, we can too 😁

**Comment by roblourens** [comment]
That turned out to be easy, thanks for pointing it out!
