### ISSUE TITLE
More useful environment variables for snippets

### ISSUE THREAD

**Issue by firelizzard18** [Microsoft/vscode#32737]
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:16:18.034Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
aurelia|Aur|0.3.4
nuget-reverse-package-search|jes|0.1.68
vscode-nuget-package-manager|jmr|1.1.4
docomment|k--|0.0.17
mssql|ms-|1.1.0
csharp|ms-|1.12.1
PowerShell|ms-|1.4.1
debugger-for-chrome|msj|3.1.8
vscode-docker|Pet|0.0.16
shell-launcher|Tyr|0.1.3
sort-lines|Tyr|1.3.0

---

I am adding my own snippets to try to replace what exists in Visual Studio, as much as I can. **I would like a variable such as `TM_FILENAME_BASE`** that does not include any extensions, since that is the default class/etc name for many languages. Or better yet, the ability to apply regex replacement rules to the variables, such as `${TM_FILENAME,/^([A-Z])/\L$1/,/([a-z])([A-Z])/$1-\L$2/g,/\..*$//}`:

  * `TM_FILENAME` - start with the filename
  * Comma separated regex replacement rules
    * `/^([A-Z])/\L$1/` - if the first character is uppercase, replace it with lowercase
    * `/([a-z])([A-Z])/$1-\L$2/g` - replace all `xY` with `x-y`
    * `/\..*$//` - if the filename ends with an extension, remove it
  * Thus, `MyCustomElement.html` becomes `my-custom-element`

**Comment by jrieken** [comment]
> Or better yet, the ability to apply regex replacement rules to the variables, such as ${TM_FILENAME,/^([A-Z])/\L$1/,/([a-z])([A-Z])/$1-\L$2/g,/\..*$//}:

Snippet transform is tracked here #6920. Just having `FILENAME_BASE` sounds like a reasonable workaround.

**Comment by jrieken** [comment]
stretch for August, PR welcome. See https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/snippet/browser/snippetVariables.ts#L85

**Comment by firelizzard18** [comment]
I'll look at it this weekend.

**Comment by joelpresence** [comment]
I would love this for creating go test files.  For example, if I'm in a go package `a/b/c`, I put my tests for package `c` in `a/b/c/tests`, its own tests package.

I have a created a snippet like the following in `go.json`:
```
{
	"Test file": {
		"prefix": "tt",
		"body": [
			"package tests",
			"",
			"import (",
			"\t\"github.com/stretchr/testify/assert\"",
			"\t. \"a/b/$1\"",
			")",
			"",
			"func Test$2(t *testing.T) {",
			"\tassert := assert.New(t)",
			"",
			"\t$0",
			"}"
		],
		"description": "Create a new test file"
	}
}
```
which produces
```
package tests

import (
	"github.com/stretchr/testify/assert"
	. "a/b/"
)

func Test(t *testing.T) {
	assert := assert.New(t)

	
}
```
However, if I'm in a file `a/b/c/tests/foo_test.go` when I expand this snippet, then the line `. "a/b/"` should be `. "a/b/c"` because these are tests for the the `c` package.

How do I accomplish this?

I tried using `TM_DIRECTORY` but it doesn't seem that I can manipulate it to remove trailing cruft.  Nor can I use `workspaceRoot` ...

I'd really like to have access to the "parent package" but being able to manipulate the current filename with knowledge of workspace root would probably be good enough.

Will the fix mentioned in this issue support my use case (pretty common for go developers) and is there an ETA?  :-)

Thanks!

**Comment by jrieken** [comment]
> Will the fix mentioned in this issue support my use case (pretty common for go developers) and is there an ETA? :-)

No, what you want is tracked here: #6920. This issue is about a pragmatic change to a new variable which is the name of a file without its extension

**Comment by joelpresence** [comment]
@jrieken thanks for responding.

I had seen #6920 but it didn't seem immediately relevant when I first read it.  I'll add my comments there.

**Comment by jrieken** [comment]
> I'll look at it this weekend.

@firelizzard18 Is this still on your radar? I don't wanna steel you thunder but I'd tackle this myself on Monday otherwise. Happy Coding

**Comment by firelizzard18** [comment]
@jrieken Feel free to tackle it. Other issues have taken precedence :/
