### ISSUE TITLE
emmet custom snippets

### ISSUE THREAD

**Issue by anyclub** [Microsoft/vscode#32752]
Do not tell me to see the doc, the doc did not say any useful instructions!!!
Do not tell me to see the doc, the doc did not say any useful instructions!!!
Do not tell me to see the doc, the doc did not say any useful instructions!!!

- VSCode Version:1.15.1
- OS Version:win10.0.15063

#32702 

other people with the same problem [stackoverflow](https://stackoverflow.com/questions/43904540/emmet-extensionpath-custom-snippet-for-javascript-file-in-visual-studio-code/43905323#43905323)

and who can tell me where to download 1.14

Reproduces without extensions: Yes/No

**Comment by ramya-rao-a** [comment]
@anyclub If your issue is the same as #32702, then you can just re-open that one and we can have a conversation, there was no need to log a new issue.

Your custom snippet from #32702 is 
```
{
    "variables": {
        "lang": "zh-CN",
        "locale": "zh-CN"
    },
    "html": {
        "abbreviation": {
            "link:tpl|link:template": "<link rel=\"template\" href=\"${1:component.html}\" />"
        }
    }
}
```

As per docs on [Html Custom Emmet Snippets](https://code.visualstudio.com/docs/editor/emmet#_html-emmet-snippets), you need to change them to

```
{
	"variables": {
            "lang": "zh-CN",
            "locale": "zh-CN"
          },
	"html": {
		"snippets": {
			"link:tpl|link:template": "link[rel=\"template\" href=\"${1:component.html}\"]" 
		}
	}
}
```

**Comment by ramya-rao-a** [comment]
Also, the stack overflow page that you linked was created 3 months ago and the changes to the custom snippets in Emmet was released last week. So the two are unrelated.

**Comment by ramya-rao-a** [comment]
We provide links to the docs so that you can better understand the reason behind the change and are able to write more of your own custom snippets easily.

If you find the docs are not helpful, link them here and tell us what was not helpful so that we can make it better.

Closing this issue as I have commented above what you need to do to get custom snippets working.

If that still doesn't work, let us know in comments in this issue and we can re-open this issue
