### ISSUE TITLE
Emmet Question: How to create user snippet or extension for common tasks?

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#32792]
- VSCode Version: Code - Insiders 1.16.0-insider (aebaece67321b35f133be393fe8adcd50333d5ee, 2017-08-18T05:10:40.239Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.4
code-settings-sync|Sha|2.8.2
sort-lines|Tyr|1.3.0
html-snippets|abu|0.1.0
Bookmarks|ale|0.15.2
project-manager|ale|0.19.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.2.11
tslint|eg2|0.17.0
auto-rename-tag|for|0.0.14
Angular2|joh|2.4.0
ecdc|mit|0.10.3
HTMLHint|mka|0.3.3
vscode-autoprefixer|mrm|2.1.2
vscode-stylefmt|mrm|2.5.0
angular2-inline|nat|0.0.17
stylelint|shi|0.28.0
ayu|tea|0.5.0
change-case|wma|1.0.0

(4 theme extensions excluded)

---

@ramya-rao-a  A question, not a bug:

1. I find myself using `Emmet > Wrap Lines with Abbreviation` and then `ul>li*|t` a lot to create unordered lists from text pasted from text editors and word processors.
2. I have mapped a shortcut to invoke the `Emmet > Wrap Lines with Abbreviation`  command, but then have to type the mnemonic.
3. The is by design and fine, but I'd like to create a complete shortcut for this entire class.  I can't figure out how to construct a snippet or command to wrap the selected lines with `ul>li*|t`.

Can someone please point me in the right direction?  If needed, I'll create an extension for this.

**Comment by heronsilva** [comment]
Well, it's possible to simplify the process so you wouldn't have to type the mnemonic every time. The solution I came up with looks like this:

1. Create a `snippets.json` file
```
{
  "html": {
    "snippets": {
      "your_snippet_id": "ul>li*"
    }
  }
}
```

2. In your vscode settings, set `emmet.extensionsPath` to the folder containing that file

3. Reload VS Code

It would work like this:
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/9641348/29478588-ed109dae-8443-11e7-87fc-effbf7dc630e.gif)

As you already have a shortcut assigned to `Wrap Lines with Abbreviation`, the only difference is that, instead of typing `ul>li*|t`, you would type anything you want. Hope it helps =}

**Comment by ramya-rao-a** [comment]
Here is a shorter way if you want to use the same abbreviation
The Emmet wrap commands take the abbreviation as argument which is usually provided by the input box that shows up. You can add a keyboard shortcut for the wrap command and provide the argument at the same time.

Add the below keybinding (change the actual key to whatever you want)

```
    {
        "key": "ctrl+e ctrl+l",
        "command": "editor.emmet.action.wrapIndividualLinesWithAbbreviation",
        "args": {
            "abbreviation": "ul>li*"
        },
        "when": "editorTextFocus && !editorReadonly"
    }
```

Now all you have to do is select the lines as before and then use the keybinding
