### ISSUE TITLE
some special string cannot be displayed completely

### ISSUE THREAD

**Issue by bysdxt** [Microsoft/vscode#32819]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|don|0.7.0
tortoise-svn|fan|0.1.1
beautify|Hoo|1.1.1
Ionide-fsharp|Ion|2.33.2
language-haskell|jus|2.3.1
cpptools|ms-|0.12.3
csharp|ms-|1.12.1
PowerShell|ms-|1.4.1
material-icon-theme|PKi|2.1.0
java|red|0.8.0
vscode-icons|rob|7.12.0
shader|sle|0.2.3
vscode-hexdump|sle|1.4.0
vscode-lua|tri|0.8.1

---

Steps to Reproduce:

1.
create a plain text file with utf8 encoding, and write 666 'Ａ's(the big A, cost 3 bytes in utf8) and '123' , like
ＡＡＡＡ....ＡＡ123
2.
use vscode to open the text file, and vscode cannot display the last character '3'

Reproduces without extensions: Yes
[text.txt](https://github.com/Microsoft/vscode/files/1236150/text.txt)

**Comment by bysdxt** [comment]
It seems that if the string of a line contains more than 2000 bytes and less than 1000 characters, vscode will display incompletely.

**Comment by alexandrudima** [comment]
@bysdxt Thanks a lot for reporting! :heart:

You are absolutely correct!

It was caused by a byte buffer allocation which assumed incorrectly that a string of `N` UTF16 code units can fit in `2*N` UTF8 code units, which is false with e.g. 'Ａ' which needs 1 UTF16 code unit and 3 UTF8 code units. Shame on me, this is the second time I make this silly mistake in the past couple of years.
