### ISSUE TITLE
High contrast: focussed line should not go over overview ruler

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#3283]
#3248

Notice how the focussed line goes all the way over the overview ruler - scroll bar at the right. I believe it should stop before the overview ruler.

![screen shot 2016-02-23 at 11 01 17](https://cloud.githubusercontent.com/assets/1926584/13248088/e044ccda-da1c-11e5-9498-83d27c390383.png)

**Comment by bgashler1** [comment]
I looked into this.  It requires logic changes, which would probably be safest for one of you to touch this close to release.  The width of the class `.current-line` is calculated via JavaScript.  Changing this would of course affect more than just this theme.  @isidorn, do you think we should change this still, and if so do you know who would be best to assign it to?

**Comment by isidorn** [comment]
I do not think this is important, it is just my feedback.
I would assign it to the backlog and you can look into it in the future when you have time.

**Comment by misolori** [comment]
Since the default behavior in our dark/light themes is to extend, going to mark this as `as-designed`.

![image](https://user-images.githubusercontent.com/35271042/45377749-4cabd000-b5b0-11e8-8c15-1355bb80e756.png)
![image](https://user-images.githubusercontent.com/35271042/45377757-56353800-b5b0-11e8-8b4a-b4316e4c71f5.png)
