### ISSUE TITLE
Hot Exit for instance with only unsaved files stopped working on upgrade to x64 bit build

### ISSUE THREAD

**Issue by M-Zuber** [Microsoft/vscode#32852]
- VSCode Version: 1.15.1
- OS Version: Win 10 Pro Insider build 1703 build 16251.0

Steps to Reproduce:

1. Have 32 bit vs code instance open that contains only unsaved files
2. Uninstall 32 bit version
3. Install 64 bit version
4. Restart vs code
5. Be amazed that everything is still in place, major kudos to the team on this one
6. Try closing instance with only unsaved files, vs code will not let without saving the files or loosing the work

In user settings I have the following:
` "files.hotExit": "onExitAndWindowClose",`

**Comment by Tyriar** [comment]
Did you happen to have another Window open at the time and did you have a folder open (the file explorer on the left was filled) or not?

**Comment by M-Zuber** [comment]
Before I uninstalled I had two instances running. One had a folder open, the other did not.
The instance without a folder contained only unsaved files

**Comment by Tyriar** [comment]
It can be a little confusing, but it sounds like this is working as designed.

For windows with no folder open, the setting `"files.hotExit": "onExitAndWindowClose"` will only allow you to close that window if there are no other windows open at the time. In other words, all windows are being closed (aka "exit").

The main reason behind this behavior is the following scenario:

1. Open a window `a` (no folder open)
2. Open a window `b` (no folder open)
3. Make changes to a file in window `b`
4. Close window `b`
5. Repeat steps 2-4 many times
6. Close window `a` (exit)

Since there is no way to explicitly restore windows with no folder opened, what would happen next is all the windows that were created in steps 2-5 will open all at once, consuming heaps of resources and potentially crashing all the windows, essentially locking you out of VS Code.

**Comment by M-Zuber** [comment]
Thanks for the explanation.
What is weird is that, as far as I can remember, with the 32bit build I could turn on my computer, open code, have it reopen all editors I had - one of them being a collection of unsaved files, the rest workspaces - and then close the non-workspace instance w/o having to save the files

Maybe I am remembering wrong though

**Comment by Tyriar** [comment]
It was always like this with regards to non-folder windows or stricter (before `onExitAndWindowClose` became a thing). Please let me know if the behavior isn't matching up with my explanation though :smile:

**Comment by M-Zuber** [comment]
Every thing seems to be going according to spec, thank you for the time!
