### ISSUE TITLE
Issue 32405 has disappeared

### ISSUE THREAD

**Issue by JivanRoquet** [Microsoft/vscode#32884]
Why has the excellent and well-written issue #32405 suddenly disappeared?

- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by skbly7** [comment]
For those interested to know what it was:
https://web.archive.org/web/20170817113559/https://github.com/microsoft/vscode/issues/32405

**Comment by cjbush** [comment]
+1

**Comment by kzhui125** [comment]
https://github.com/Microsoft/vscode/issues/32795
and
https://github.com/Microsoft/vscode/issues/32797

**Comment by seanmcbreen** [comment]
Let me start by quickly stating that data-loss [for any reason] is something we take very seriously.  So this is definitely an unfortunate story and one we want to de-risk for others in the future.  

However, In relation to who deleted the issue/users account, to tell you the truth we are not actually sure who orchestrated that.  At the same time we also have not spent any time attempting to work it out.  The issue was in violation of the [GitHub](https://help.github.com/articles/github-terms-of-service/#3-conduct-restrictions) code of conduct.  Which is grounds for such an issue to be removed when reported by anyone. 

From our perspective the most important thing is to work on a good resolution, one that lowers the risk of this happening to others.  So we are still actively discussing the issue and working on a solution over in #32459.  As a a result I propose we close this issue for now, and focus our collective efforts on improving the user experience for everyone.

Sean
VS Code Team Member
