### ISSUE TITLE
Emmet does not expand "Lorem ipsum" anymore

### ISSUE THREAD

**Issue by antony-chopin** [Microsoft/vscode#32894]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T17:16:27.618Z)
- OS Version: Linux x64 4.4.0-92-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
aurelia|Aur|0.3.4
sass-lint|gle|0.0.4
sass-indented|rob|1.4.1
vscode-multiclip|sle|0.1.2

(22 theme extensions excluded)

---

Sadly, but beautiful feature with expanding "Lorem", "Lorem30", etc. doesn't work now. :(

**Comment by ramya-rao-a** [comment]
lorem works as expected both in suggestions and via the `Emmet: Expand Abbreviation` command

![lorem](https://user-images.githubusercontent.com/16890566/29532441-070890e8-8662-11e7-9b88-cc820adda27d.gif)

If you were looking for the expansion using tab then set `emmet.triggerExpansionOnTab` to `true`

One thing I did notice was that the second time you type `lorem` you get the word based suggestion instead of the emmet suggestion.

Is that what you meant?

**Comment by antony-chopin** [comment]
@ramya-rao-a yes, thank you a lot. It was `true` before, but for some reasons became `false`. Sorry for my inattention

**Comment by ramya-rao-a** [comment]
@antony-chopin No problem. We did do a lot of changes to Emmet in 1.15.1

Do read the [Emmet 2.0 blog](https://code.visualstudio.com/blogs/2017/08/07/emmet-2.0)

Happy Coding!
