### ISSUE TITLE
Custom Emmet snippets could not use by 1.15.1 update

### ISSUE THREAD

**Issue by tamatebako** [Microsoft/vscode#32922]
- VSCode Version: 1.15.1
- OS Version: win10 x64

I can hardly speak English, I'm sorry.
I will ask a question using google translation.

In order to use custom emmet snippets I had written the following in snippets.json.
~~~~
"html": {
  "snippets": {
    "c": "class=\"|\"",
    "_": "target=\"_blank\""
  }
}
~~~~
For example
~~~~
<div></div>
~~~~
I will input it like this.
~~~~
<div c></div>
~~~~
When expanded, it becomes as follows.
~~~~
<div class=""></div>
~~~~
![](https://i.gyazo.com/492f6788105d0d88955ebacad9a230e7.gif)

In the case of a element
~~~~
<a href=""></a>
~~~~
I will input it like this
~~~~
<a href="" _></a>
~~~~
When expanded, it becomes as follows.
~~~~
<a href="" target="_blank"></a>
~~~~
![](https://i.gyazo.com/b7d3ce1742b8588050f61cf424c04e58.gif)

In css, I had written the following in snippets.json.
~~~~
"css": {
  "snippets": {
    ":h": ":hover {\n\t|\n}"
  }
}
~~~~
For example
~~~~
.test {
  
}
~~~~
I will input it like this
~~~~
.test {
  &:h
}
~~~~
When expanded, it becomes as follows.
~~~~
.test {
  &:hover {
    
  }
}
~~~~
![](https://i.gyazo.com/e7c4ff2829b9eeff48d1efe54f3ecd19.gif)

Before 1.14 it worked without problems.
However it became impossible to expanded it by updating to 1.15.1 the other day.
I read[ this page](https://code.visualstudio.com/docs/editor/emmet) but I could not solve it.

I have created a lot of snippets and it is very inconvenient if I can not use them.
Could you help me to resolve this issue?

Thank you.

**Comment by ramya-rao-a** [comment]
@tamatebako 

For the css snippet, remove the `:` from the snippet name. `:` is no longer allowed in snippet names.

The html snippets you have won't work because we have disabled Emmet inside the opening tag. 

I would suggest to use the [User Snippets](https://code.visualstudio.com/docs/editor/userdefinedsnippets) instead.

![html](https://user-images.githubusercontent.com/16890566/29584231-f2d4ae0a-8737-11e7-9c43-1a8005a5a8b0.gif)

Use Emmet snippets for creating html tags and not attributes inside an html tag.

Hope that helps.

Feel free to share any other custom snippet that is not working for you

**Comment by tamatebako** [comment]
I understood.
Thank you for a good explanation.
