### ISSUE TITLE
Emmet: Use of nested square brackets in abbreviations doesn't work

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#32986]
From @jakehockey10 in https://github.com/Microsoft/vscode/issues/32243#issuecomment-324142506

`li>a[routerLinkActive="active" [routerLink]="['/applications']"]`
should expand to
```
<li>
    <a href="" routerLinkActive="active" [routerLink]="/applications"></a>
</li>
```

**Comment by ramya-rao-a** [comment]
@jakehockey10  Can you try something simple as `div[id="hello"]`?

Can you share the version of VS Code you are using?
Can you try the same in a new html file?

**Comment by jakehockey10** [comment]
![image](https://user-images.githubusercontent.com/1821383/29591166-7caf6fd0-875a-11e7-8855-2c6bf4f3edab.png)

I'm not sure what changed, but now square brackets are working.  I've restarted my computer and that's all I can think of.  But inner square brackets continue to give the error

**Comment by ramya-rao-a** [comment]
That's much better, Thanks!

Question:

If you want 
```<li>
    <a href="" routerLinkActive="active" [routerLink]="/applications"></a>
</li>
```

then why do you have the extra [] around `/applications` in `li>a[routerLinkActive="active" [routerLink]="['/applications']"]` ?

**Comment by jakehockey10** [comment]
Sorry, for Angular, that is the syntax.  The `routerLink` input requires the path to be in an array parameter.

**Comment by ramya-rao-a** [comment]
Thanks for that clarification @jakehockey10 

@sergeche The parsing of abbreviation fails with the error "Expected attribute name at char 32" for `li>a[routerLinkActive="active" [routerLink]="['/applications']"]` at https://github.com/emmetio/abbreviation/blob/master/lib/attribute.js#L69

Would you say the use of `[` in abbreviations is valid and we should support it?

**Comment by jakehockey10** [comment]
I sure hope the answer is yes :(  It used to work beautifully.  I had no problem writing my entire template in emmet before expanding it and it was an amazing experience :)

**Comment by sergeche** [comment]
Yes, good point. I thought I’ve supported it somehow, or maybe another braces like `(` or `{`

**Comment by ramya-rao-a** [comment]
@sergeche Do you want me to log a separate issue in the @emmetio/expand-abbreviation repo?

**Comment by ramya-rao-a** [comment]
@sergeche I have submitted a PR to fix this in the abbreviation module. https://github.com/emmetio/abbreviation/pull/7

Can you take a look?

**Comment by ramya-rao-a** [comment]
The fix for this issue will be included in tonight's (Aug 31) Insiders

@jakehockey10 Can you give it a try and let me know if it works as expected? You can get the Insiders from https://code.visualstudio.com/insiders

**Comment by jakehockey10** [comment]
@ramya-rao-a I think it has improved since I last tried it.  However, before the major update, I was able to use emmet with angular template syntax in mind with no problems.  Not all of the Angular template syntax is supported anymore, which is not the responsibility of emmet in any way, but was convenient none-the-less.

For example, this used to just work:

- `[*ngIf="true"]` turned into `<div *ngIf="true"></div>`
- `a[(click)="clickHandler($event)" [ngClass]="coolClass(thingy)"]{Click Here!}` turned into `<a href="" (click)="clickHandler($event)" [ngClass]="coolClass(thingy)">Click Here!</a>
- etc.

Now, I still use emmet, but I have to split up my thinking when writing the syntax for my Angular templates such that I think of how to complete only the HTML through emmet and add in the Angular-specific syntax elements after the fact, more surgically.

**Comment by ramya-rao-a** [comment]
@jakehockey10 I'd appreciate it if you can list out all the angular scenarios that worked before and don't now. We (@sergeche and I) can look at them case by case and see if we can get emmet support for them back if possible in the new Emmet 2.0 approach.
