### ISSUE TITLE
Folding icons are too big and the grey frame looks uneven/blurry

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#3299]
On testing #2994

![2016-02-23 12-01-26](https://cloud.githubusercontent.com/assets/1898161/13249580/668cb700-da25-11e5-8bd2-f3af7097b341.png)

The four lines of the icon frame look uneven/blurry.

Why aren't we using the same triangles as in the navigator? The '+' and '-' icons look a bit out of place.

**Comment by egamma** [comment]
The new folding icons are distracting. The previous twistie icons were subtle, pls see the example below, when I using folding to work on the vscode.d.ts file.

I agree with @weinand that we should look consistent with the explorer.

![image](https://cloud.githubusercontent.com/assets/172399/13252837/24e3cd98-da39-11e5-96f9-57b21c3af244.png)

**Comment by joaomoreno** [comment]
:+1:

I got scared when I saw them just now.

**Comment by bgashler1** [comment]
Thanks for everyone's feedback.  I just spoke with @chrisdias.  After we reviewed responses from users who have seen the proposed (+/-) icons on issue #2948, we believe users actually like the idea of a (+/-) icon, but that the way we have icon represented is flawed; it's too heavy-weight, strong in contrast and it is aliased strangely.

I'm going to tone down the weight and contrast of these icons and fix the aliasing so they are very light and out of the way.  If we still aren't satisfied with how the icons look by the end of the day today, then let's revert all my changes back to the twisties and we can decide if we want to continue iterating on this later or just keep the twisties.  Thanks again for the feedback.

**Comment by weinand** [comment]
@bgashler1 for GA we should consider to achieve consistency with the explorer, that is if users prefer +/-we should use them in the navigator too. Having two sets of icons for the same purpose doesn't make sense to me.

**Comment by Tyriar** [comment]
@weinand I think the reasoning is because Visual Studio uses +/- for folding and arrows in the explorer.

**Comment by weinand** [comment]
@Tyriar I understand but that does not mean that we should not strive for some additional simplicity and elegance.

**Comment by Tyriar** [comment]
@weinand I agree, I prefer the triangles personally as +/- look so busy.

**Comment by chrisdias** [comment]
@weinand completely agree on simplicity. Feedback in https://github.com/Microsoft/vscode/issues/2948 was favorable to +/- for expand/collapse so Brad is time boxing the effort to see if we can achieve awesomeness. If not, we will revert back to same as in explorer.

**Comment by bgashler1** [comment]
@weinand, very good point about these icons not being a paradigm used in OSX.

As @Tyriar was pointing out, I was merely trying ensure we are similar enough to feel part of the same brand family as Visual Studio.  If we don't like it by the end of the day, then I won't lose any sleep over it.  Being different isn't bad, as long as we are justifiably better.

**Comment by bgashler1** [comment]
Let me know what you all think of the updates I pushed.  Smaller icons, lower contrast and perfect aliasing.  Hopefully this resolves some concerns.

Another reason why we should use the (+/-) icon is that when we eventually add vertical braces to indicate what chunk of code expand and collapse, the icon will stand better next to the brace because it's encapsulated by a square outline  Since twisties are not contained in a shape like a square, it will be hard to associate each with its paired vertical brace.

**Comment by chrisdias** [comment]
@bgashler1 thanks, these look much better.  Can folks who were against +- please take a look and see what you think? Here's my take:

- The arrows are more consistent with the Explorer tree. However, we don't indent the arrows in the code as we do in the tree, so it doesn't look consistent.
- While the hit area for the arrows is larger than the arrow itself, I still find myself feeling the need to get the mouse right over the arrow before I click. I don't have this feeling with the +- glyph because it is larger.  I feel like i have to concentrate more with the arrows.
- and contrary to the above arguments :) the arrows are cleaner.

**Comment by joaomoreno** [comment]
Adding screenshot for reference

![image](https://cloud.githubusercontent.com/assets/22350/13279102/75f2f410-dad5-11e5-9f8b-091b31f73bc4.png)

They look much *much* better. I no longer feel the rush to disable this feature.

**Comment by weinand** [comment]
@bgashler1 yes, the icons look better now.

**Comment by aeschli** [comment]
@bgashler1 Looks good! But, the icons need to scale with bigger and smaller fonts. I created #3390

**Comment by Tyriar** [comment]
Looks good!

@bgashler1 any reason for the `+` background not being transparent like `-`?

**Comment by bgashler1** [comment]
@Tyriar, yes.  This is to differentiate it further from non-collapsed icons.  It also helps it stand out as a visual landmark and it matches how VS does it.
