### ISSUE TITLE
debugger doesnt stop when exiting extension development host

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#32990]
``` console
git clone https://github.com/microsoft/vscode-docker
cd vscode-docker && npm install
code-insiders .
```
`F5` to launch the debugger
extension development host starts up
close the extension development host)

results: 
- the debugger is still running, i have to press stop to actually stop the debugger
- pressing restart hangs with following message:

![image](https://user-images.githubusercontent.com/1487073/29592178-699a7c4e-8757-11e7-9b94-678ebdbf0bd6.png)

**Comment by weinand** [comment]
@bpasero I've debugged this on the debugger side and it seems that closing the EH window does neither terminate the EH nor does it send any broadcast events for this.

**Comment by bpasero** [comment]
@weinand this seems to be a regression from us moving to `--inspect`, I cannot reproduce the hanging extension host when I do not pass over the `--inspect-brk` to the extension host on launch. 

Could it be that the debugger needs to explicitly send some signal to the debuggee to signal the session is over and otherwise the process will never terminate?

**Comment by weinand** [comment]
@bpasero yes, a terminate request from the debugger might be necessary.
@roblourens do you know something about this?

The problem is that the debugger doesn't know when the EH window's close button has been pressed. So we would at least need another broadcast event for this.

**Comment by weinand** [comment]
The issue is that `process.exit()` does not exit node if node has been started  with `--inspect`.
Since I couldn't find anything about this behaviour I don't know whether this is a bug or feature.
@roblourens do you know anything about this?

Debugging this node program with the "inspector" protocol shows the same behaviour:
```js
process.exit();
console.log("not reached");
```
The console.log statement is not reached but the node process doesn't exit.

Using `process.kill(process.pid)` in `extensionHostMain.ts:29` instead of `nativeExit(1)` fixes the issue.

@alexandrudima @bpasero how should we proceed?

**Comment by bpasero** [comment]
If that works, why not use `process.kill` if the extension host knows that it is being debugged?

**Comment by weinand** [comment]
Yes, if Rob has no better ideas I suggest that we use `process.kill(process.pid)` if in debug mode.

**Comment by roblourens** [comment]
There was an issue in Node <8 where the process refuses to terminate until the debugger detaches. This is probably related. I'm surprised that it impacts `process.exit` but I think `process.kill` is the right way to go.

**Comment by roblourens** [comment]
If it's ugly, we can revisit it with an electron version that has a node 8 equivalent (1.7.5 says node 7.9?) and maybe remove it then.

**Comment by weinand** [comment]
@alexandrudima could you please add the workaround the way you like it? Thanks.

**Comment by alexandrudima** [comment]
This is the nodejs PR that introduced this --- https://github.com/nodejs/node/pull/7252

**Comment by weinand** [comment]
@roblourens this means it is a feature and our "inspector" DA should really detach when process.exit() is called.

**Comment by roblourens** [comment]
Correct. Original node2 issue: https://github.com/Microsoft/vscode-node-debug2/issues/11

It didn't occur to me that this would impact EH debugging, thanks for the investigation and fix. I opened https://github.com/Microsoft/vscode/issues/33196 to revisit this once Electron has Node 8.
