### ISSUE TITLE
autoSave and trimTrailingWhitespace incompatible

### ISSUE THREAD

**Issue by mastersimon** [Microsoft/vscode#33003]
- VSCode Version: 1.13.1
- OS Version: MacOS Sierra 10.12.6

Steps to Reproduce:
Use the following settings
```bash
"files.autoSave": "afterDelay",
"files.autoSaveDelay": 1000,
"files.trimTrailingWhitespace" :true
```

I would expect that `trimTrailingWhitespace` removes the trailing whitespaces every time `autoSave` is triggered. This is unfortunately not the case. The combination `autoSave` with `trimTrailingWhitespace` does not work. Removing `autoSave` and saving the file manually works.

Reproduces without extensions: Yes

**Comment by yume-chan** [comment]
I can reproduce this.

But it only happens with `"files.autoSave": "onFocusChange"`, normally I use `onFocusChange`, and I also tried `onWindowChange`, they both work correctly.

**Comment by bpasero** [comment]
It is true that we do not remove the whitespace from the current line simply because that would make typing very hard. However, it works for me in other lines, so I cannot reproduce:

![flicker_chrome58](https://user-images.githubusercontent.com/900690/29656456-c7565840-88b4-11e7-8e9a-05864091fbf5.gif)

**Comment by mastersimon** [comment]
@bpasero You are right. The whitespaces for all inactive lines are removed. Does make sense to not remove it from the active line.
