### ISSUE TITLE
Extension search improvements (by category, trending)

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#33035]
Extension search improvements (by category, trending)

**Comment by sandy081** [comment]
@kieferrm I see this is part of the August plan. May I know if there was any discussion about this and if there are any details about this feature request?

**Comment by kieferrm** [comment]
The ideas around this were:
- `@category:formatter python` - with a predefined set of categories and free form search terms
- `@trending` - shows the trending list

However, I think we should defer that work to September and potentially combine it with @ramya-rao-a  work on improving extension recommendations in general.

**Comment by sandy081** [comment]
We should also think about discovering this syntax, like intelli-sense.

Ok to defer it.

**Comment by kieferrm** [comment]
Absolutely. It's a total mystery right now, not even the doc is complete.

**Comment by ramya-rao-a** [comment]
Category is already supported
Recent work on adding auto-completions takes care of the syntax discovery problem
Docs have been updated

Trending and other search types like the ones supported in the marketplace sounds like good ideas but since there have been not much user interest in the area, I will mark this as out of scope
