### ISSUE TITLE
I find it weird that the generated tasks.json has errors

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#3305]
#3159 

* Have a workspace with no `tasks.json` and trigger the command `Configure tasks runner`
* A `tasks.json` gets generated with a `ts` content so we could get the correct snippets in the intelli-sense
* I find it weird that we generate an erroneous `tasks.json` just so we could filter on the right snippets. Couldn't we generate an empty `tasks.json` and still reveal the snippets in some smart way

**Comment by joaomoreno** [comment]
Yes, this is ugly.

Not only that but the `filterText` property is heavily used here and shows the problem with it. The highlighting is all wrong.

![image](https://cloud.githubusercontent.com/assets/22350/13253421/43452a36-da3c-11e5-91a2-fcb55fb4a0b6.png)

**Comment by egamma** [comment]
The intent of this interaction is that `the user selects a snippet` forcing an Intellisense pop-up for this interaction has the issues described above. 

My suggestion is to make the snippet selection more explicit, e.g., the user picks a snippet from a quick box and then Code inserts the snippet. This is similar to picking an initial snippet for a launch configuration in the debugger. Using Intellisense to insert additional snippets makes good sense to me.

A nit, since we use a snippet we should leverage the snippet functionality and use snippet variables in the snippets, this makes it obvious what the user should modify. For example, the `tsc` snippet should make the filename argument a snippet variable.

**Comment by dbaeumer** [comment]
Addressed on latest. When you create a new tasks.json file you now only have the snippets in and no ts prefix.

**Comment by dbaeumer** [comment]
@isidorn please close as verified. The new story doesn't have snippets anymore.
