### ISSUE TITLE
code --uninstall-extension is not the inverse of --install-extension

### ISSUE THREAD

**Issue by fabiospampinato** [Microsoft/vscode#33106]
It was surprising to find out that after a:

```bash
code --install-extension ~/Desktop/test.vsix
```

and a restart, executing this:

```bash
code --uninstall-extension ~/Desktop/test.vsix
```

doesn't remove the extension, instead it throws an error:

```bash
Error: Extension '/Users/fabio/Desktop/test.vsix' is not installed.
```

**Comment by ramya-rao-a** [comment]
`--install-extension` needs source from where the vsix can be accessed and be installed. Give an extension name or path, it will find the vsix in the marketplace, download and install.
Give path to vsix file, it will install the extension using the vsix file

--uninstall-extension has nothing to do with location of the vsix. It takes extension name and uninstalls it.

This is by design.

cc @joaomoreno for more info if I missed anything

**Comment by fabiospampinato** [comment]
Is there a reason why provided the path of the .vsix file it doesn't get the name of the extension from it?

Running `code --help` displays the following, which seems to imply that both accept the same kind of argument:

```bash
  --install-extension <ext>   Installs an extension.
  --uninstall-extension <ext> Uninstalls an extension.
```

**Comment by ramya-rao-a** [comment]
I believe the `code --help` needs an update :)

**Comment by fabiospampinato** [comment]
That's good, but why not making `code --uninstall-extension` fetch the extension id from the vsix file?

**Comment by joaomoreno** [comment]
@fabiospampinato Sure, it would also not hurt... want to submit a PR for that?

**Comment by fabiospampinato** [comment]
Alright, I'll work on it.
