### ISSUE TITLE
Emet stranger behavior

### ISSUE THREAD

**Issue by DracotMolver** [Microsoft/vscode#33103]
VSCode Version: 1.15.1 (64 bits)
OS Version: Windows 10

Hi, I'm trying to make an HTML and I love using Emet. But sometimes when I type div.class-css{}, it doesn't work because of the curly braces and sometimes it doesn't work well when you lost the focus and then you get it back. Does anyone facing an strange behavior with the new version of Emet?

Reproduces without extensions: Yes

**Comment by ramya-rao-a** [comment]
I am assuming you are talking about emmet suggestions disappearing when you press `-`, `.` or `{}
as shown below. But as you keep typing, you will see emmet suggestions appear again

![htmlemmet](https://user-images.githubusercontent.com/16890566/29689145-fad9b758-88d6-11e7-9438-63a9d93f1891.gif)

In the above example, you see the suggestion disappearing at 
- `div.`
- `div.class-`
- `div.class-css{}`

The first case `div.` is a valid abbreviation but we do not show suggestions. Word ending with a `.` can be part of simple sentences and suggesting emmet will be noisy. See #31453

The second case `div.class-` is an invalid abbreviation so we don't show emmet suggestions

For the third case, when you start typing text inside the `{}`, the suggestions come back. So that should be fine.

If you find any other cases where you see emmet suggestions disappearing, please drop in a comment and I can re-open this issue.

Other than that if you want to expand Emmet abbreviations and snippets using tab, set `emmet.triggerExpansionOnTab` to `true`

There have been quite a few changes to Emmet in the July release.
Please read the [Release Notes on Emmet](https://code.visualstudio.com/updates/v1_15#_emmet-20) or [Emmet 2.0 blog](http://code.visualstudio.com/blogs/2017/08/07/emmet-2.0) and the [Emmet docs](https://code.visualstudio.com/docs/editor/emmet)

**Comment by DracotMolver** [comment]
Oooh sorry, yes I was talking about Emmet. Ok, I'll will check everything you said. Thanks for reply back

**Comment by DracotMolver** [comment]
@ramya-rao-a  `emmet.triggerExpansionOnTab: true` it was the solution. Thankyou so much

**Comment by ramya-rao-a** [comment]
No problem, Happy Coding!
