### ISSUE TITLE
Debugging client-server for extension launches 2 server processes after vscode update

### ISSUE THREAD

**Issue by dsgouda** [Microsoft/vscode#33104]
I installed the latest VS code update on my machine and I am not able to debug the extension I was working on.
I have a client/server set up for my extension, when I start the debugger (with client and server) it launches 2 server processes but no client process and throws an error eventually in `bootstrap.js`.

![image](https://user-images.githubusercontent.com/14796031/29683217-68a4e920-88c2-11e7-8a2d-3d58d5581f59.png)

This setup worked with earlier versions of vscode.

I am able to replicate this issue using one of the samples provided [here](https://github.com/Microsoft/vscode-extension-samples/tree/master/languageprovider-sample)

- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by weinand** [comment]
What version of VS Code and node.js are you using?

**Comment by dsgouda** [comment]
Node: v8.1.3
Typescript: 2.4.2

**Comment by weinand** [comment]
I'll try it again: what version of VS Code are you using?

**Comment by dsgouda** [comment]
The latest stable build, `Version 1.15` I believe

**Comment by weinand** [comment]
On Windows open "Help" menu and select "About" item.

**Comment by dsgouda** [comment]
![image](https://user-images.githubusercontent.com/14796031/29683955-0b84b6a0-88c5-11e7-8eaa-1c6f5174da05.png)

**Comment by weinand** [comment]
How does your launch.json look like?

**Comment by dsgouda** [comment]
I copied over everything straight from the example [here](https://github.com/Microsoft/vscode-extension-samples/tree/master/languageprovider-sample)

**Comment by weinand** [comment]
I see some problems with the language server sample's:
- the compound launch config in the [launch.json](https://github.com/Microsoft/vscode-extension-samples/tree/master/languageprovider-sample) uses a config "Launch Client" which doesn't exist. Probably the "Launch Client" should be named "Launch Extension"
- I don't know whether the language server runs on VS Code's builtin node runtime or the user installed runtime. In the latter case it needs to be started with the `--inspect` flag because node.js v8.1.3 only supports "inspector" mode. And the "Attach Language Server" should have a `""protocol": "inspector"` attribute.

@aeschli you might want to fix this.

**Comment by weinand** [comment]
This would be a better launch config:
```javascript
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Launch Extension",
			"type": "extensionHost",
			"request": "launch",
			"runtimeExecutable": "${execPath}",
			"args": [
				"--extensionDevelopmentPath=${workspaceRoot}"
			],
			"stopOnEntry": false,
			"outFiles": ["${workspaceRoot}/client/out/**/*.js"],
			"preLaunchTask": "npm"
		},
		{
			"name": "Launch Extension Tests",
			"type": "extensionHost",
			"request": "launch",
			"runtimeExecutable": "${execPath}",
			"args": ["--extensionDevelopmentPath=${workspaceRoot}", "--extensionTestsPath=${workspaceRoot}/client/out/test" ],
			"stopOnEntry": false,
			"outFiles": ["${workspaceRoot}/client/out/test/**/*.js"],
			"preLaunchTask": "npm"
		},
		{
			"name": "Attach Language Server",
			"type": "node",
			"request": "attach",
			"protocol": "legacy",
			"port": 6004,
			"outFiles": ["${workspaceRoot}/server/out/**/*.js"]
		}

	],
	"compounds": [
        {
            "name": "Launch Client & Server",
            "configurations": ["Launch Extension", "Attach Language Server"]
        }
    ]
}
```

**Comment by dsgouda** [comment]
I had fixed the name of the configuration before testing. (can replicate the issue even with the config you provided above), will investigate if it is something on my machine itself.
Thanks.

**Comment by weinand** [comment]
It would help if you could provide precise information in bug reports.

Above you said "I copied over everything straight from the example here". It would have be more efficient to clearly state that there was an issue with the sample launch config, so that I would not have to investigate this again.

In addition please include VS Code version and platform information in the initial issue, so that I do not have to ask for that individually. VS Code has a "Report Issues" action in the help menu that fills in this info automatically.

I will reopen this issue because the launch config from the sample is still broken and we have to fix this.

**Comment by aeschli** [comment]
Fixed with https://github.com/Microsoft/vscode-extension-samples/commit/522898aa8ea6aa4d6b68d4676315e57b1d40b52b
