### ISSUE TITLE
When using word navigation, the screen reader announces tokens twice

### ISSUE THREAD

**Issue by stevencl** [Microsoft/vscode#3312]
screen reader support turned on and using NVDA

Imagine I have the cursor at teh end of this line of code

vscode.window.activeTextEditor.document.languageId

When I press ctrl + left arrow, I hear 'languageId' being announced. I then press ctrl + left arrow again. The cursor moves to before the '.' and I head 'document' being announced (although the cursor  is positioned after the document token). I press ctrl + left-arrow once more. The cursor is now positioned before the document token but I hear 'document' being announced again. It makes it sound like I have document typed twice.

Found when testing #3247

**Comment by alexandrudima** [comment]
From our side, we set the cursor in the textarea at the right location. I think it is a Chromium bug

**Comment by zersiax** [comment]
Bump.
Possibly related. When going through a file quickly, either word by word or line by line, you do still get this behavior. Example:

class foo < bar

When I am on this line and go down, often it will repeat the line I was on rather than the new line which may or may not be a blank line. Especially when going character by character this gets annoying, for example when you want to correct a spelling mistake. Letters get repeated randomly making it hard to figure out where exactly you are in the code.
Interestingly enough this seems to be some kind of latency problem. When working with braille, you consistently get good results. Makes me think that the speech query is jumping the gun so to speak, but I don't know enough about the VS Code internals to judge that. Anyone have a clue what is causing this?

**Comment by alexandrudima** [comment]
Let's track in #26730, where we have a lot more insights into the problem.
