### ISSUE TITLE
Can't open folder wise view in new version.Please correct it.

### ISSUE THREAD

**Issue by SAJUSJ** [Microsoft/vscode#33148]
- VSCode Version:1.15.1
- OS Version:Windows 10

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by rcjsuen** [comment]
@SAJUSJ What is the "folder vise view"?

**Comment by SAJUSJ** [comment]
When I click the open folder option and select folder ,I won't display the selected folder in the left side panel. When I click and select individual files ,it will be shown.

**Comment by Tyriar** [comment]
@SAJUSJ could you post a screenshot of what you happens when you try open a folder?

Also check the devtools console for errors (Help > Toggle Developer Tools).

**Comment by bpasero** [comment]
@sandy081 this could be related to hiding files explorer

**Comment by sandy081** [comment]
@SAJUSJ Did you tried hiding the Folder view ? 

![image](https://user-images.githubusercontent.com/10746682/29769010-bf390612-8be8-11e7-9f9c-b9aa888dee68.png)

If so, you can unhide it from the header

![image](https://user-images.githubusercontent.com/10746682/29769034-d0fecf12-8be8-11e7-83f7-ec34ac459301.png)

Note: This hidden state is per workspace and will not impact other workspaces

**Comment by grantmarch** [comment]
I have the same problem on Windows 10 using Visual Code 1.15.1 with no extensions.

A folder, "my_folder" opens in the sidebar and all files and subfolders are visible as normal.

On opening my_folder at some apparently later random occasion my_folder opens but no files or subfolders are visible in the sidebar.

I know my_folder is open, because at the very top of VS code you can see the "VS Code logo - my_folder - Visual Studio Code". But there are no files or subfolders visible in the sidebar.

This behaviour is the same if you right click on my_folder in Windows Explorer and open with VS Code or if you open my_folder from the "File" drop down menu. There is no output in Developer Tools -> Console when opening the folder from the VSCode File dropdown menu.

If I right click on a file inside my_folder in Windows Explorer to open a single file, the file opens in the side bar ok as normal.

If I change my_folder in Windows Explorer to, say, "my_folder_2", then my_folder_2 will open successfully in VSCode and show all the files and subfolders in the sidebar.

If I change my_folder_2 back to my_folder in Windows Explorer, VS Code "remembers" the initial folder, my_folder, and chooses not to display the contained files and subfolders.

However after opening and closing my_folder_2 some number of times, the behaviour of not showing the files and subfolders in the sidebar for my_folder_2 happens again.

Now VSCode "remembers" both my_folder and my_folder_2 and doesn't display the files and subfolders in the sidebar.

This process of renaming folders, temporarily being able to see the contained files and subfolders and VSCode remembering these "invisible" folders can be repeated for new folder names.

Note that the dropdown View -> Toggle Side Bar has no effect on this behaviour.

**Comment by jaimemateo** [comment]
I had this same "issue", after removing my project from Side Bar I couldn't see it anymore after opening the editor again. The solution is the one mentioned above, there is this filter right clicking in the EXPLORER header. Clicking in Folders show again the folder tree. 

Thanks.

**Comment by sandy081** [comment]
This is fixed by #32962
