### ISSUE TITLE
Folder Tree Hidden

### ISSUE THREAD

**Issue by rizki-arya** [Microsoft/vscode#33177]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T17:16:27.618Z)
- OS Version: Linux x64 4.10.0-32-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
vscode-intelephense-client|bme|0.7.2
php-intellisense|fel|1.5.1
Go|luk|0.6.63
laravel-blade|one|1.8.1
laravel5-snippets|one|1.3.4
vscode-proto3|zxh|0.1.2

(2 theme extensions excluded)

---

Steps to Reproduce:

1. File > Open Folder > /var/www/targetFolder
2. Title is opened but folder tree is not visible

I have tried:

1. Open via command line inside the folder, same result.
2. `sudo chown -R $USER:www-data /var/www/targetFolder` no changes.
3. Disable all extensions & open again, same.
4. Current permission is 755, tried 777 & still the same.

Dev tools:
![devtools](https://user-images.githubusercontent.com/28424158/29739103-3e0a3342-8a60-11e7-9a71-e680d0d1d1b8.png)

Reproduces without extensions: Yes

**Comment by rcjsuen** [comment]
Maybe the same issue as #33148?

**Comment by rizki-arya** [comment]
Yes, I can confirm that it's the same issue, I can open specific file inside but couldn't make any changes.

**Comment by Tyriar** [comment]
@chrmarti looks like the call to `find` is failing

**Comment by grantmarch** [comment]
I have the same problem on Windows 10 using Visual Code 1.15.1 with no extensions.

A folder, "my_folder" opens in the sidebar and all files and subfolders are visible as normal. 

On opening my_folder later at some apparently random occasion my_folder opens but no files or subfolders are visible in the sidebar.

I know my_folder is open, because at the very top of VS code you can see the "VS Code logo - my_folder - Visual Studio Code". But there are no files or subfolders visible in the sidebar.

This behaviour is the same if you right click on my_folder and open with VS Code or if you open my_folder from the "File" drop down menu.

If I right click on a file inside my_folder to open a single file, the file opens in the side bar ok as normal. 

If I change my_folder in Windows Explorer to, say, "my_folder_2", then my_folder_2 will open successfully in VSCode and show all the files in the sidebar.

It would appear that VS Code  "remembers" the initial folder, my_folder, and chooses not to display the contained files and subfolders.

However after opening and closing my_folder_2 some number of times, the behaviour of not showing the files and subfolders in the sidebar for my_folder_2 happens again.

Now VSCode "remembers" both my_folder and my_folder_2 and doesn't display the files and subfolders in the sidebar.

This process of renaming folders, temporarily being able to see the contained files and subfolders with VSCode remembering these "invisible" folders can be repeated for new folder names.

I hope this helps in isolating the bug.

**Comment by chrmarti** [comment]
Tracking as #33148
