### ISSUE TITLE
VSCode 64bit Windows 10 starts multiple WMI Provider Host with high CPU usage

### ISSUE THREAD

**Issue by justinzhong** [Microsoft/vscode#33171]
- VSCode Version: 1.15.1 32 bit/64 bit
- OS Version: Windows 10 Pro 64 bit

Steps to Reproduce:

1. Starts VS Code and open the integrated terminal (CTRL + `)
2. Run "git status"

Reproduces without extensions: Yes

I have noticed an unusual lag when working with the integration terminal (I have configured mine to Git for Windows, but experience the same with the default cmd setting).

`
"terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe"
`

When I investigated further I notice that each time I press a key or executes a command, the WMI Host Provider service appears in the process list with high CPU usage.

Using ProcessExplorer I can see multiple instances of WMI Commandline Utility were fired via Code.exe and given my workstation is a single physical core with 2 logical cores, this appears to explain why the short burst of spike in CPU graph.

When I run the commands from a separate Git for Windows bash prompt this issue is not observed.

I have recorded an example of this event in gif and attached along with my VS Code version info.

If anyone can please advise a fix or workaround for this issue that would be much appreciated, thank you!

![vscode-about](https://user-images.githubusercontent.com/16523765/29737484-8eaf4e68-8a51-11e7-9c63-85e4ada02b3b.png)
![vscode-wmi-record](https://user-images.githubusercontent.com/16523765/29737485-8eb1abae-8a51-11e7-8cd5-dabd531cc70e.gif)

**Comment by Tyriar** [comment]
This was for a new feature in v1.15.1 that gets fills in the correct name of the program running in the terminal to the dropdown. I don't expect it to have that big of an impact because we spent quite a while minimizing the calls while keeping the info correct.

Regardless, the good news is that we've replaced it with a native, in-process solution so it's super fast and asynchronous now so performance problems should be fixed in Insiders/v1.16.
