### ISSUE TITLE
Relative paths in .code-workspace files are turned into absolute ones on save

### ISSUE THREAD

**Issue by Gama11** [Microsoft/vscode#33188]
- VSCode Version: code-oss-dev 1.16.0 (9066eedcf7597779e3a710bf997d0d9f8748d597)
- OS Version: Windows_NT x64 10.0.15063
---

I gave `.code-workspace` files another try since they now became suitable for my use-case with support for relative paths (#31203). It works great, as long as I don't add any additional folders to it via the UI and use `Save Workspace As...`. If I do that, VSCode **turns the relative file paths into absolute ones**.

In my particular case, this isn't really an issue, since I auto-generate the file, but it still seems like VSCode should try to preserve the "relativity" of the file paths so `code-workspace` files can be checked into repositories.

---

Steps to reproduce:

1. Open any workspace with relative paths in its `.code-workspace` file (I'm using [this one](https://github.com/HaxeFlixel/flixel-demos/blob/dev/flixel-demos.code-workspace)).
1. Add any other folder to that workspace via `File -> Add Folder to Workspace...` (removing a folder works too).
1. Save the workspace with `File -> Save Workspace As...` in the same location.

As an example, this:

```json
{
	"folders": [
		{
			"path": "Arcade/Breakout"
		}
	]
}
```

will be turned into:

```json
{
	"folders": [
		{
			"path": "c:\\HaxeToolkit\\haxe\\lib\\flixel-demos\\git\\Arcade\\Breakout"
		},
		{
			"path": "c:\\HaxeToolkit\\haxe\\lib\\flixel-demos\\git\\Arcade\\FlxSnake"
		}
	]
}
```

..when adding the `Arcade/FlxSnake` folder.

Note: when saving the workspace _without_ adding or removing any folders, the file remains unchanged, which is good.

**Comment by bpasero** [comment]
Nice catch, have to look.

**Comment by bpasero** [comment]
@Gama11 actually this brings an interesting question: if you add more folders to a workspace that is already using relative paths for folders, should the added folder also use relative path or absolute? 

It looks like Sublime at least always uses a relative path if the parent folder of the workspace file is a parent of the folder that is being added, otherwise the path will be absolute. In other words, an absolute path is only used if a relative path would have to be expressed by going up one directory ("`..`").

I am not sure that is the right thing to do though. An alternative would be to just preserve an absolute or relative path and always write it back in that format. On the other hand, it also seems wrong to have a file with mixed absolute and relative paths, so maybe it should at least be consistent across all paths.

So we can:
* always write relative paths if possible to use without ".."
* preserve existing relative paths but write absolute paths for new folders
* respect the format of the file (continue to use relative paths if there are, but use absolute paths by default for new workspaces)

**Comment by Gama11** [comment]
Using relative paths by default whenever possible (without `..`) makes sense to me. There's really no advantage to absolute paths that I can see? With relative paths, you have a number of advantages:

- you can check the workspace into a repo
- you can move the workspace directory around without the `.code-workspace`-file breaking
- paths are shorter / easier to read

**Comment by bpasero** [comment]
@Gama11 I am not sure about making it easier to move the workspace file around. I agree if the workspace file is within a folder and you point to other folders within that folder, but if you actually just move the workspace file itself around, it seems to me that absolute paths would be better. 

Anyway, will discuss this with the team next week.

**Comment by pr-yemibedu** [comment]
Hello,
 With each folder being an object, it is possible to have a default case and an overriding case to put the choice in the users hand. If there is a default "relative" style and the user can mark a particular path to preserve its absolute representation, then that could be a helpful alternative. Maybe with a setting value of "**pinned**".

 That would allow the best of both and possibly feel more natural. I am bias towards [simplicity](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) and [conventions](https://en.wikipedia.org/wiki/Convention_over_configuration) but highly accept the ability to choose when it is applicable. Thank you. Good day.

**Comment by bpasero** [comment]
For August we are doing the Sublime Text strategy: if a workspace folder can be expressed as relative path from the location of the workspace file, a relative path will be used. Otherwise an absolute path is used. 

Filed https://github.com/Microsoft/vscode/issues/33270 as follow up.

**Comment by Gama11** [comment]
Found another issue with this, see #33328.
