### ISSUE TITLE
Emmet --> br*2

### ISSUE THREAD

**Issue by user3323** [Microsoft/vscode#33218]
- VSCode Version: 1.15.1
- OS Version: win7x64

Emmet doesn't want to expand 2 `<br>`'s

![br x 2](https://user-images.githubusercontent.com/24613274/29752437-8a2062ea-8b66-11e7-82c8-2cc6fddad613.gif)

**Comment by Anderson-Vasques** [comment]
It seems wierd.. I have both same VSCode and OS version and can't reproduce the error. However I noticed that when I ctrl+v an abbr (`br*7`, for example) emmet does not work. Is this the expected behavior? Should I open another issue?

**Comment by ramya-rao-a** [comment]
@user3323 Look closely... It does expand `br*2`... Its just that they appear side by side. And when you have more than 2, then appear one below the other.

This is because the the property of `inline_break` is set to 3 by default. This defines how many inline elements are needed to force line break. Read more about it here: https://docs.emmet.io/customization/syntax-profiles/#create-your-own-profile

You can customize this using the `emmet.syntaxProfiles` setting. Read more on [Emmet settings](https://code.visualstudio.com/docs/editor/emmet#_emmet-configuration)

@Anderson-Vasques I am assuming what you are saying is that when copy paste an abbreviation, the suggestions don't show up? If yes, then that is the way suggestions work in VS Code. Copy pasting doesn't trigger suggestions. Typing does. There are 3 workarounds for you

1. Press `Ctrl+Space` to manually trigger suggestions
2. Bind a keyboard shortcut (other than tab) for the command `editor.emmet.action.expandAbbreviation`, and use it
2. Set `emmet.triggerExpansionOnTab` to `true` to get Emmet expansion on tab

**Comment by user3323** [comment]
@ramya-rao-a, oh, yeah, sorry. I looked at it like at div expansion, so it made me blind a little.

**Comment by ramya-rao-a** [comment]
No problem @user3323 
I appreciate all the feedback I can get
Happy Coding!
