### ISSUE TITLE
[loc] Adding language - Bengali to transifex VS Code project

### ISSUE THREAD

**Issue by taninme** [Microsoft/vscode#33217]
Hi I'm willing to translate VS Code project for Bengali(bn_BD). I'm adding my vote. My transifex id : taninme 

Thanks

**Comment by sabiha230** [comment]
I'm also willing to translate VS Code project for Bengali(bn_BD). Count me in. My transifex id : sabiha123

Thanks

**Comment by reazp** [comment]
I am willing to start working on VS code for Bengali(bn_BD). transifex id : reazp

**Comment by syedkutubahmed** [comment]
I am willing to start working on VS code for Bengali(bn_BD). transifex id : syedkutubahmed

**Comment by danyeh** [comment]
Thank you for showing interest. We are reviewing the request.

**Comment by danyeh** [comment]
Language Bengali(bn) has been enabled for vscode projects in Transifex. We use neutral language ID in order to have good coverage and usage.
@taninme , @sabiha230, @reazp , please check Transifex vscode projects.
@syedkutubahmed , I could find your account in Transifex, please join the project there by yourself.
Thank you for contributing!

**Comment by nasirkhan** [comment]
@danyeh I checked the Transifex and found that only `vscode-extensions` has the Bengali(bn) language option. But not available for the other projects. can you please enable the language for those languages too.

**Comment by fahmed1** [comment]
@nasirkhan We are now only doing that one. Once we are done with that we will start with the other ones.
