### ISSUE TITLE
Add weight/priority to autocomplete

### ISSUE THREAD

**Issue by corysimmons** [Microsoft/vscode#33219]
Just wrote a `console.log($1)` snippet with the `cl` prefix.

When I type `cl` I get autocomplete options for a billion things with `class` being the first. My actual snippet is far down in the list.

Is there a way to assign weight to autocomplete things (like snippets) so `cl` is at the top of the list? If not, can this be converted to a feature request?

In lieu of that feature, is autocomplete intelligent and will figure out what you frequently use and increase its weight? If not, can I feature request that?

**Comment by rcjsuen** [comment]
Allowing weight to be assigned could cause extension to "fight" with each other as each extension that's contributing a snippet tries to increase its snippets' priorities in order to get to the top of the suggestion list.

I don't know much about the internals of VS Code but I imagine this is technically feasible though it would be forced to potentially store quite a bit of information. Some sort of setting would probably need to be created to only record the last N days' worth of history or to only store N megabytes worth of history so that it doesn't end up growing forever and forever.

**Comment by corysimmons** [comment]
>Allowing weight to be assigned could cause extension to "fight" with each other as each extension that's contributing a snippet tries to increase its snippets' priorities in order to get to the top of the suggestion list.

So don't allow extensions access to weight. Make it a user only setting.

**Comment by rcjsuen** [comment]
> So don't allow extensions access to weight. Make it a user only setting.

Alright, you got me.

So would you expect weight to be assigned via a context menu on the suggested proposal or by manually punching in stuff through the settings file?

**Comment by corysimmons** [comment]
Probably manual. Seems like an "advanced" feature that would really clutter the UI if you added as context menu of it on every single thing.

**Comment by jrieken** [comment]
We have an issue which is about remembering what you have selected the last time. We also have an issue to prefer matches covering "more", e.g. `cl` covers 100% of `cl` but just 60% of `class`. I am closing this as a dupe of these two issues: #32886 and #22839. Thanks and Happy Coding

**Comment by corysimmons** [comment]
Fair enough thanks.
