### ISSUE TITLE
Wordwrap not working after turning "on"

### ISSUE THREAD

**Issue by ekundayo-ab** [Microsoft/vscode#33220]
Hi,

I've set *wordWrap* to be permanently on by having this `"editor.wordWrap": "on"` in my user's settings.

After this, when I try to use the horizontal scrolling feature of my Laptop's trackpad in the editor, the horizontal scroll back comes back again, but this time the words are wrapped with unneccessary spaces not wrapped.

Steps to Reproduce:
1. Set "wordWrap" to "on"
2. Use horizontal Scrolling feature of Laptop to scroll in editor which has a file with codes open

![wordwrap issue](https://user-images.githubusercontent.com/20375577/29752930-1298320e-8b5f-11e7-8396-7cd258c9907c.png)

**Comment by jlarcombe** [comment]
I think I just noticed the same thing, but in a rather simpler way:

1. Open a new window.
2. Ensure word wrap is off.
3. Paste in a long stream of text with no line breaks (so that it overflows the right of the window).
4. Turn word wrap on.

EXPECTED: The text wraps properly
ACTUAL: The text does wrap, but is scrolled horizontally off the left hand side of the window, so that the left-hand side of the text is not visible and the right-hand side has a lot of blank space after the wrap.

The problem corrects itself if the window is resized.

**Comment by alexandrudima** [comment]
@ekundayo-ab @jlarcombe

I cannot reproduce. 
![kapture 2017-10-24 at 9 49 19](https://user-images.githubusercontent.com/5047891/31930625-a4e392de-b8a0-11e7-989a-06529d86c86a.gif)

To help me identify the root cause, can you please check if this issue reproduces when **disabling all extensions**? Does the issue reproduce when **commenting out your settings**? Does the issue reproduce in all files, including plain text files?

**Comment by jlarcombe** [comment]
I can't reproduce it now either but it happened to me last night! I'll keep my eye out for it again.

**Comment by jlarcombe** [comment]
This just happened to me again. At the time, it was reproducible; I could close the window, make a new one, paste in the same large amount of text, switch on word wrap and the same thing happened. When I quit and re-ran with all extensions disabled, it stopped happening, but then when I re-ran with extensions *enabled* it *still* didn't happen. So it seems as though it only happens when the app has been running for a long time (I previously hadn't restarted it for quite a while, at least a month probably.) Odd.

**Comment by alexandrudima** [comment]
There is one scenario I can think of when we would not word-wrap: files over 30MB or over 300k lines. Have you perhaps been working with such files ?

**Comment by jlarcombe** [comment]
No, not in this case.

It's not happening at the moment. I've upgraded to the October release and I'll keep my eye out to see if the problem recurs. I don't know if it makes any difference but I usually have both the status bar and the activity bar turned off.

**Comment by alexandrudima** [comment]
I will close for now, as the issue appears to be resolved or not reproducible.
