### ISSUE TITLE
Open internal modules in preview tab

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#33237]
- Debug a node script like this

```
eval('debugger;//123')
```

- When breaking in the eval'd script, leave the tab open in the editor
- Change the eval'd code in some way, e.g. change the comment
- Debug it a second time
- If the same number is assigned, e.g. `VM65` on both runs, the editor will open the old version of the script which is already open. It doesn't send a `scriptRequest` to the debug adapter to get the new script text. This leads to confusing situations when debugging eval code.

**Comment by isidorn** [comment]
Dup of an issue that we do not dispose scripts on end of debug session -> there is currently an open issue assigned to Joao but I can not find it.
Since we need a mechansim that debug can tell the content provider that a content is no longer valid.
If you can not find the original issue and you are passionate let me know and I can try harder to dig it up

**Comment by roblourens** [comment]
Can they be opened as preview tabs?

**Comment by isidorn** [comment]
@roblourens yes we could open all internal modules as preview tabs and I like that idea

**Comment by weinand** [comment]
@isidorn am I able to set breakpoints in preview tabs?

**Comment by isidorn** [comment]
@weinand yes.
