### ISSUE TITLE
CTRL+F stopped working

### ISSUE THREAD

**Issue by crewone** [Microsoft/vscode#33240]
- VSCode Version: Code - Insiders 1.16.0-insider (d30825f323a7f77e17d25b212fef6440e73fdc14, 2017-08-28T05:23:34.544Z)
- OS Version: Windows_NT ia32 10.0.16257
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.15.2
vscode-database|baj|1.2.0
vscode-intelephense-client|bme|0.7.2
gitignore|cod|0.5.0
bracket-pair-colorizer|Coe|0.10.8
xml|Dot|1.9.2
gitlens|eam|4.4.1
php-debug|fel|1.11.1
auto-close-tag|for|0.4.3
auto-rename-tag|for|0.0.14
vscode-scss|mrm|0.6.2
sublime-keybindings|ms-|2.9.1
debugger-for-chrome|msj|3.2.0
vscode-icons|rob|7.12.0
Align|ste|0.2.0
html-css-class-completion|Zig|1.9.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Open file
2. CTRL+F to find something (Does not work)

3. Put "{ "key": "ctrl+f",                "command": "actions.find" }" in keybindings.json (the default) and it works again.

Reproduces without extensions: Yes

**Comment by yreenchan** [comment]
me too, after update to 1.16.0-insider, ctrl+f stop working

**Comment by joaomoreno** [comment]
Over here as well, @bpasero @egamma

**Comment by bpasero** [comment]
Seems to work for a while for me again after a window reload.

**Comment by enkol** [comment]
Just had the same problem, with 1.15.1 x64. `Ctrl-F` worked again after a window reload. 

I did install an extension few minutes before recognizing that `Ctrl-F` stopped working (`Ctrl-H` still worked). I don't think the extension (heaths.vscode-guid) caused the problem, but maybe the installation procedure is related to find the problem cause.

**Comment by joaomoreno** [comment]
<kbd>Escape</kbd> is also broken!!!

**Comment by alexandrudima** [comment]
I have reverted the 7 commits introduced by merging (with rebase) the PR #32113

**Comment by cleidigh** [comment]
@joaomoreno 
@bpasero 
@alexandrudima 
This was my error missing an edge condition of the context conflict with the two very similar widgets.
Sorry for the revert work/miss in testing.
Christopher

**Comment by alexandrudima** [comment]
@cleidigh No problem.

Sorry I had to revert it, as we were at the office on a different timezone than @rebornix (who understood the change) and we got updated to an Insiders build where various important things stopped working. I was not sure what would be the minimal fix in the context of that large change. The safest and fastest way to unblock folks was to revert the merge and trigger new builds.

We can try merging again after this endgame, with a bit more testing.

**Comment by cleidigh** [comment]
@alexandrudima 
Yes it was bad timing but most of all my bad for not catching it earlier.  ironically the layering issue you found (from the original work of the simpleFind) is really related.  I think the fundamental problem which you alluded to is that both widgets have too much overlap which generated the re- factoring issue.  I was trying to address some of the intermediary issues but this just makes things worse.  The overlapping functionality and key bindings was the root cause of the problem.  I read your comments about the layering and I partially understand them.  I will work with @rebornix  to address both issues for September.  Thanks for your understanding :+1:

**Comment by alexandrudima** [comment]
We are good to go for August.
