### ISSUE TITLE
Support a localized version of the Readme.md

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#3325]
see also #3289.

To complete a multi-language experience for extensions, there should also be support for a locale specific version of the README.md.

**Comment by dbaeumer** [comment]
@egamma To my knowledge the readme show in the market place UI and when we click on the readme button in the install extensions list then we open a web browser. So there is not much I can do since the nls story has to come from the market place. All we need to do to pass may be an argument to the market place when opening the extension in the browser. So IMO there is nothing we need to do here.
