### ISSUE TITLE
Bad phrasing in debug pre launch task

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#3333]
Testing #2940

--

![image](https://cloud.githubusercontent.com/assets/22350/13254679/a8d48d0a-da42-11e5-873d-ab61b5ad1903.png)

Maybe something more like:

```
Errors detected while running task 'compile'.
```

--

Also:

![image](https://cloud.githubusercontent.com/assets/22350/13254868/abfc8982-da43-11e5-966e-1abe1eb8ade1.png)

What's up with the *unique*?

```
Could not find the task 'dsa'. Make sure the task exists and it has a unique name.
```

And this should not be a warning, but an error, since debugging could not go on.

**Comment by chrisdias** [comment]
We should be consistent when referring to the "preLaunch" task because it helps people find the problem, they will look for the term "preLaunch".

So, I suggest the error message is "Could not find **preLaunch** task '*taskname*'.  I am not sure we need the second sentence "Make sure the task exists and it has a unique name".

Also, in this case I only have a "Close" option. We should be consistent and use the the same prompts as when there are other errors. I suggest "Continue" and "Stop" in #3438.

**Comment by isidorn** [comment]
We need the second sentence so it is clear to the user what might be the cause of the issue because there might be two tasks with the same name and in that case the user might not be aware what is the real casue.

Continue and stop make no sense in this case since we can not continue until the user fixes his problem in launch.json, and then he has to start debug again

**Comment by chrisdias** [comment]
re: Second sentence...  How does someone get into the state where there are multiple tasks with the same name?  It looks like if I have a gulpfile with multiple tasks gulp always picks the last one and when i run a task from the command palette it always runs the last one, so we should be consistent with when you run a task manually. I have not seen any other errors from running tasks that prompts you to ensure that a task name is unique, therefore I think we should be consistent and we don't need the second sentence.

re: Continue/Stop...  The model where there is an error if there is no task.json or gulpfile.js/gruntfile.js is that you can "Debug Anyway".  This is essentially the same scenario - the task specified in preLaunch does not exist/is in error. to use the argument above, we should not allow the user to Debug until they fix the fact that they don't have a gulp/grunt file or a tasks.json.  Therefore I suggest we follow the same response model with a "Debug Anyway" and "Close".

**Comment by chrisdias** [comment]
looks good.

**Comment by ibhub** [comment]
I have message "Errors detected while running the preLaunchTask" on every task run. But my preLaunchTask does not contain errors.

**Comment by chrisdias** [comment]
@ibhub can you open a new issue?  This issue is about the text of the message, but you are running into an issue using the feature.  Thanks.

CC @weinand @isidorn

**Comment by ibhub** [comment]
@chrisdias ok, thank you. #4070
