### ISSUE TITLE
EH Debugging: breakpoints are not verified

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#33354]
testing #33305 on Windows:

- debug TypeScript hello world extension
- set some breakpoints in the 'sayHello' command
- F5

Observe: 
The EH window appears but the breakpoints is still unverified:

![2017-08-29_11-21-35](https://user-images.githubusercontent.com/1898161/29814046-47eb9498-8cac-11e7-9f2a-fe64da04778c.png)

**Comment by roblourens** [comment]
This is one thing that node2 has always done a bit differently than node-debug - breakpoints are marked as unverified until the script is actually loaded and the breakpoint binds. I prefer it and it makes sense to me, in that the breakpoint can't actually bind until the script is loaded. And it gives you more information which is useful in diagnosing issues. A red breakpoint means "there is actually a real breakpoint set in that location". But if someone interprets the gray breakpoints as "something is wrong" then it could be confusing. Especially since it didn't work that way before. What do you think?

cc @bpasero you also commented on this in another issue.

**Comment by bpasero** [comment]
Yeah this comes to my surprise a bit just because I am probably used to the way it was before. Not sure how others would react to this change...

**Comment by roblourens** [comment]
@weinand What do you think?

**Comment by weinand** [comment]
I can understand that the new behaviour reflects the underlying implementation (and makes it transparent) and on the other hand I share Ben's concerns.

I think the "legacy" debugger is relying on the fact that a reg-exp based breakpoint verifies even if a matching file has not yet been loaded.

If you want to support the old behaviour what could you do in the "inspector" debugger other than always verifying breakpoints?

Since I'm not aware of any complaints about this behaviour for non-EH "inspector" debugging, 
I suggest that we ship with the new behaviour and wait for feedback (if any).

**Comment by roblourens** [comment]
> If you want to support the old behaviour what could you do in the "inspector" debugger other than always verifying breakpoints?

I guess in following the old behavior, you still get some feedback as to whether the adapter **attempted** to set the BP, like that it has the right sourcemaps and enough info to set the BP.

> Since I'm not aware of any complaints about this behaviour for non-EH "inspector" debugging,
I suggest that we ship with the new behaviour and wait for feedback (if any).

Agreed. I think we'll get some new comments because it's very visible in this particular case. But I can mention it in the release notes as a feature - it's easier to tell whether your extension is activated!

**Comment by weinand** [comment]
I've grouped your debugging note together with @jrieken's note about EH profiling under a new section 'Upgraded Electron only supports "inspector" protocol'
