### ISSUE TITLE
Proposal: Have Chalk and other modules output to debug console

### ISSUE THREAD

**Issue by SetTrend** [Microsoft/vscode#3336]
Debugging using colored output doesn't seem possible in VS code:

![vs code color](https://cloud.githubusercontent.com/assets/9283914/13254941/ef825614-da43-11e5-96f1-07f215c6255a.png)

Can we have the standard output of the debugger redirected to the Debug Console window so colored debugging output becomes possible?

**Comment by weinand** [comment]
@SetTrend since the VS Code debug console is not a real terminal (a 'tty'), some programs detect this and don't try to use colours (e.g. mocha). However, the debug console does support colours. You just have to force your program to output colours (e.g. the `--colors` flag of mocha).
Alternatively you can use the external console by setting the launch config attribute `externalConsole` to true (remember, launch config Intellisense is your friend ;-)

**Comment by SetTrend** [comment]
Ahh... I see... Thanks for pointing out the `externalConsole` alternative to me! :+1: 

I noticed that the above code doesn't output *anything*, regardless whether I set `externalConsole` to true or false:
<br/>
##### using chalk.*color*():
![nooutput](https://cloud.githubusercontent.com/assets/9283914/13269438/f71250e8-da87-11e5-81fd-89ca08666a5b.png)
<br/>
##### using console.log():
![nooutput2](https://cloud.githubusercontent.com/assets/9283914/13269585/d65485b4-da88-11e5-8078-cdeb2f4f5a78.png)
<br/>
I'm not sure what I'm doing wrong here ... Can you perhaps tell me: is it me or is it perhaps VS Code who's making a mistake..?

**Comment by weinand** [comment]
@SetTrend I'm not familiar with chalk but from looking at chalk's description I'm pretty sure that `chalk.blue('Hello world!')` is not supposed to output anything but only creates a string with ANSI colour sequences. So you still have to use console.log(...).

**Comment by SetTrend** [comment]
Thanks a lot for enlightening me! You are absolutely right.

The Chalk documentation didn't get clear about this. Many examples there just say `chalk()` instead of `console.log(chalk())` or similar.
