### ISSUE TITLE
SCM: Explore master-detail view

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#33363]
From @sqs

> Would you be interested in a PR that implemented a UI like this? I just hacked this together tonight.
> 
> The Open Repositories section works like the Open Editors section; it grows (to a point) based on the number of open repositories. Selecting a repository shows that repository's (and only that repository's) SourceControlView in the rest of the viewlet. Focus is in the Open Repositories list initially.
> 
> It would be fairly easy to make it possible to show multiple repositories' SourceControlViews if you multi-selected them. That would of course be duplicating some functionality of a viewlet's subviews (e.g., you could make it so right-clicking on the Source Control header would let you check/uncheck each repo, as in the extensions viewlet), but it seems quite convenient to make this always visible.
> 
> ![image](https://user-images.githubusercontent.com/1976/29813975-99e7a454-8c60-11e7-8de8-3502a4f6fbd1.png)

**Comment by joaomoreno** [comment]
Instead of multi select, we could use checkboxes for making them visible.

**Comment by bpasero** [comment]
We actually had this design under consideration but did not pursue it any further because we did not easily want to add a new concept to the UI (master-detail view). 

I personally always preferred a solution where I can pick the repository to the top and see changes below. I also think the master view should show the incoming/outgoing changes on each repository and maybe offer an action to synchronize.

**Comment by stevencl** [comment]
Yes, we had considered something similar to this early on (see the video here: https://www.youtube.com/watch?v=48Y6tB3DN1g&t=488s). One of the participants in this video makes the suggestion that we should show the list of repos, rather than the list of folders which is shown in the video which we agreed with.

I am not sure about the label 'Open repositories'. With the term 'open' being so prominent, it suggests that the user needs to manage (open and close) the repositories. Could it work if we just showed all the repos in the workspace as suggested in the video?

**Comment by joaomoreno** [comment]
@stevencl Currently you can have even more repositories. For example, you can open a file outside any workspace, which lives in a git repo. We will show it. 

Maybe we could use the term `Active Repositories`?

**Comment by joaomoreno** [comment]
A first version of this was just pushed to `master`:

![image](https://user-images.githubusercontent.com/22350/30601657-d41aa6e0-9d62-11e7-883e-5f8355d5d05f.png)

It basically works as a master-detail view, except it supports multi-select. If you only have a single repository, it should appear just as before, no section whatsoever.

Feedback welcome!
