### ISSUE TITLE
Diff blocks for 300 ms when continusly changing a large file outside of vscode

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#33378]
Refs: #33302

1. Download [Lending Club data for Q3 2016](https://www.lendingclub.com/info/download-data.action)
2. Open that file in vscode, have the following node program running
3. VSCode freezes (window is no longer responding)

If i turn on word wrap vscode crasesh with out of memory

```js
var fs = require('fs');
setInterval(() => fs.appendFileSync('message.txt', 'data to append'), 500);
```

**Comment by alexandrudima** [comment]
@isidorn I cannot reproduce the word wrap induced crash as I cannot turn on word wrap since this is one of those very large files where we disable word wrapping. How did you turn on word wrap, as I would expect the file would be detected as very large when you open it and word wrap would be disabled.

Regarding the freeze, I see the diff algorithm taking ~300ms per file refresh. I can work on improving that, but I cannot improve the time it takes nodejs to read the file from disk:
<img width="1117" alt="screen shot 2017-08-30 at 16 54 55" src="https://user-images.githubusercontent.com/5047891/29879064-5796cc70-8da4-11e7-981f-ea58ce084534.png">

**Comment by isidorn** [comment]
@alexandrudima toggle word wrap does not work when I just open the file. But it works if I open the file and have my append program running in the background. If you can not repro on your machine feel free to drop by

![screen shot 2017-08-30 at 17 09 43](https://user-images.githubusercontent.com/1926584/29879664-08c1f816-8da6-11e7-9728-140e914ffedc.png)

**Comment by alexandrudima** [comment]
:+1:

* the word wrap is available because the content is pasted in and the large file is not read from disk on file open. that is expected.
* the crash/unresponsiveness is caused by #33529 where there are too many file reads going on in parallel and they all end up consuming memory. the other cause of the unresponsiveness was #33525, where painting is very slow on long lines with many decorations when the font is not monospace or when ligatures are enabled.
* I suggest we keep this item around for improving the time the diff takes (~300ms in this case).

**Comment by alexandrudima** [comment]
The diff is now fast enough. See #39266
