### ISSUE TITLE
Poor frame rate when jumping to definition over long distances with smooth scrolling enabled

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#33414]
- VSCode Version: Code - Insiders 1.16.0-insider (d0d00e882437092f521d2d7893cc56ee296d278f, 2017-08-29T06:58:13.897Z)
- OS Version: Linux x64 4.10.0-32-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.9.4
lorem-ipsum|Tyr|1.0.0
sort-lines|Tyr|1.3.0
vscode-svgviewer|css|1.4.2
tslint|eg2|0.17.0
git-project-manager|fel|1.4.0
md-navigate|jri|0.0.1
theme-monokai-pro-vscode|mon|1.0.1
vscode-scss|mrm|0.6.2
seti-icons|qin|0.1.3
Ruby|reb|0.15.0
vim|vsc|0.9.0

(1 theme extensions excluded)

---

#33299 

1. Open this line https://github.com/Microsoft/vscode/blob/30b47ba11c3a206773953909bbf2291670c8cbd6/src/vs/workbench/parts/terminal/electron-browser/terminalInstance.ts#L763
2. Ctrl+click on `TerminalInstance`

![image](https://user-images.githubusercontent.com/2193314/29830140-3976586e-8c96-11e7-82fe-6cd29a0a52ce.png)

Specs:

CPU: 3.50GHz 4 core with hyperthreading
RAM: 64gb

**Comment by alexandrudima** [comment]
@Tyriar The animation takes 100ms. What concerns me is the high ratio of JS Scripting to Browser Rendering on your trace. Here is the trace of doing the same thing on my machine (a MacBook Pro at 3.3GHz)

(Note I have turned off Screenshots in the Timeline)

The `1` is where the editor begins to paint (i.e. related to smooth scrolling). The code before is all specific to jump to definition. We can look into improving that, but I think your point is about smooth scrolling being slow.

On my machine, the 100ms end up in 5 editor frames, the slowest JS paint happens at frame number 4, at about 12ms spent in JS. I've recently (2 days ago) further optimized the JS times by using a TypedArray based StringBuilder for generating the HTML output. I think we're at a point where we need to consider reducing the times the browser takes to recalculate styles and relayout. IMHO this could be done by using shadow dom.

<img width="784" alt="screen shot 2017-08-30 at 12 47 37" src="https://user-images.githubusercontent.com/5047891/29869053-9d4552a0-8d81-11e7-9883-9a6cabee4a73.png">

There are two things:

1) the smooth scrolling animation function does not make sense over large distances. i.e. when jumping at a distance above two viewport lengths, it does not make sense to flash a portion of source code in between the start and the end viewport. I will tweak this animation function, which should improve the feeling (actually seeing things moving rather than some unrelated viewport flashing in and out) and should improve the total consumed time.

2) What concerns me, is the high time spent on your machine in JS compared to the browser layouting/rendering. Is it perhaps that you have enabled a certain set of settings that make the editor slower: e.g. using a non-monospaced font, using ligatures, having 1000s of decorations, etc. What settings do you have enabled ? e.g. on Joh's machine painting a frame in a certain file took 60ms due to tens of thousands of decorations from the rainbow brackets extension. I need to figure out how to faster intersect the current viewport with all the multiline decorations, but yeah ... it would be nice to find out if a certain setting is causing the slowness for you ?

**Comment by Tyriar** [comment]
> the smooth scrolling animation function does not make sense over large distances. i.e. when jumping at a distance above two viewport lengths

This is one of the main places it makes sense imo. I personally don't find this feature particularly valuable when I know where I'm scrolling to, but when I don't know (jump to defintiion), it can provide some great context of where I went relative to where I was (in the same file).

> it would be nice to find out if a certain setting is causing or aggravating the slowness for you ?

Here are my settings:

```js
{
  "editor.autoClosingBrackets": false,
  "editor.codeLens": false,
  "typescript.implementationsCodeLens.enabled": true,
  "typescript.referencesCodeLens.enabled": true,
  "editor.folding": false,
  "editor.fontFamily": "Hack",
  "editor.formatOnPaste": false,
  "editor.minimap.enabled": true,
  "editor.minimap.renderCharacters": false,
  "editor.renderControlCharacters": true,
  "editor.renderIndentGuides": true,
  "editor.renderWhitespace": "boundary",
  "editor.roundedSelection": false,
  "editor.rulers": [ 80, 100, 120 ],

  "explorer.autoReveal": false,
  "explorer.openEditors.visible": 0,

  "extensions.autoUpdate": true,
  "extensions.ignoreRecommendations": true,

  "files.defaultLanguage": "markdown",
  "files.hotExit": "onExitAndWindowClose",
  "files.useExperimentalFileWatcher": true,

  "terminal.integrated.cursorBlinking": true,
  "terminal.integrated.scrollback": 5000,
  "terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe",

  "window.restoreWindows": "all",
  "window.title": "${rootPath}${separator}${activeEditorName}${separator}${appName}",

  "workbench.colorTheme": "Sapphire",
  "workbench.editor.enablePreviewFromQuickOpen": false,
  "workbench.iconTheme": "seti",
  "workbench.startupEditor": "none",

  // Languages
  "typescript.check.tscVersion": false,
  "[markdown]": {
    "editor.quickSuggestions": false
  },

  // Extensions
  "gitProjectManager.baseProjectsFolders": [
    "$HOME/dev",
    "%USERPROFILE%\\Documents\\dev"
  ],
  "gitProjectManager.maxDepthRecursion": 2,
  "window.zoomLevel": 0
}
```

**Comment by alexandrudima** [comment]
re:
> This is one of the main places it makes sense imo. I personally don't find this feature particularly valuable when I know where I'm scrolling to, but when I don't know (jump to defintiion), it can provide some great context of where I went relative to where I was (in the same file).

The smooth scrolling makes sense to work when jumping to definition. IMHO the problem lies with the animation function that determines the `scrollTop` of the editor in an indiscriminate fashion as a cubic ease out.

e.g.

### a small jump
suppose `scrollTop` is `0` and a smooth animation request comes in to jump to `500`. The line height is 20px and 30 lines fit in the viewport.

Here's what the animation will be like assuming the editor has time to render 5 frames in 100ms (~20ms per frame):

```
frame 0: 10/110=0.09, easeOutCubic:0.25 => scrollTop 124 => [6, 36]
frame 1: 30/110=0.27, easeOutCubic:0.62 => scrollTop 308 => [15, 45]
frame 2: 50/110=0.45, easeOutCubic:0.84 => scrollTop 419 => [20, 50]
frame 3: 70/110=0.64, easeOutCubic:0.95 => scrollTop 476 => [23, 53]
frame 4: 90/110=0.82, easeOutCubic:0.99 => scrollTop 497 => [24, 54]
frame 5: 110/110=1.00, easeOutCubic:1.00 => scrollTop 500 => [25, 55]
```

The animation function (in its current form) works well in this case. Each frame contains a region of lines from the other frame, so the eye would presumably form a motion. i.e.:
 * frame 1 has 20 lines overlapped with frame 0
 * frame 2 has 25 lines overlapped with frame 1
 * frame 3 has 27 lines overlapped with frame 2
 * frame 4 has 29 lines overlapped with frame 3
 * frame 5 has 29 lines overlapped with frame 4

### a large jump
suppose `scrollTop` is `0` and a smooth animation request comes in to jump to `50000`. The line height is again 20px and 30 lines fit in the viewport.

```
frame 0: 10/110=0.09, easeOutCubic:0.25 => scrollTop 12434 => [621, 651]
frame 1: 30/110=0.27, easeOutCubic:0.62 => scrollTop 30766 => [1538, 1568]
frame 2: 50/110=0.45, easeOutCubic:0.84 => scrollTop 41886 => [2094, 2124]
frame 3: 70/110=0.64, easeOutCubic:0.95 => scrollTop 47596 => [2379, 2409]
frame 4: 90/110=0.82, easeOutCubic:0.99 => scrollTop 49699 => [2484, 2514]
frame 5: 110/110=1.00, easeOutCubic:1.00 => scrollTop 50000 => [2500, 2530]
```

The animation function (in its current form) **does not** work well in this case.
 * frame 1 has no lines overlapping with frame 0, so it appears as a random flash of text
 * frame 2 has no lines overlapping with frame 1, so it appears as a random flash of text
 * frame 3 has no lines overlapping with frame 2, so it appears as a random flash of text
 * frame 4 has no lines overlapping with frame 3, so it appears as a random flash of text
 * frame 5 has 14 lines overlapped with frame 4, so a motion could be formed.

So I'm thinking to change the animation function when the jump distance is > 2*viewport such that it  stays a bit near the initial viewport and then boomerangs straight to a place near the final viewport (fyi @jrieken ).

**Comment by alexandrudima** [comment]
I've extracted the tweaking of the animation function in #33534

I don't see anything "shady" in your settings that would cause us to skip the optimized path in the rendering code, unless Hack is not detected as monospace on your machine. Minimap will probably add a couple of ms of rendering time, especially when jumping a long distance (as explained above) and I'm not really happy with the indent guide rendering times.

**Comment by Tyriar** [comment]
> frame 1 has no lines overlapping with frame 0, so it appears as a random flash of text

This is a good point 😄 Thinking about it now, the reason I felt I had context was the animation in the minimap and scrollbar

**Comment by alexandrudima** [comment]
I am not sure what else is actionable in this issue:
1. `editor.smoothScrolling` is off by default
2. the animation function is already tweaked via #33534 such that the 3-4 frames that get painted show lines next to the destination

I will close this issue for now...
