### ISSUE TITLE
View | Toggle Minimap only works when an editor is open

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#33456]
Testing https://github.com/Microsoft/vscode/issues/33301

Open an editor
Note the visibility state of minimap, either on or off
Close **all** editors
`View | Toggle Minimap`
Open an editor
Note that the visibility of the minimap has not changed
If you examine `settings.json`, you see that the value is not changed there either

This is the same behavior as the other "Toggle" commands in the menu group.

It makes me wonder, why are these all "Toggle"? Why aren't they check marks of on or off, like `File | AutoSave`.

**Comment by alexandrudima** [comment]
:+1: Nice find regarding the toggle not working when all editors are closed.

:+1: on using checkmarks next to the toggle actions. I will, however, extract this to a separate feature request. The problematic thing here is that those Toggles are possibly editor instance specific. i.e. focused editor specific. 

One could configure to see minimap only in TypeScript files and not in JavaScript files via our language selectors. Users would expect then, when focus is in a TypeScript file, and they invoke the menu, that the checkmark would be checked since minimap is enabled in TypeScript files. Also, when focus is in a JavaScript file, and they invoke the menu, the checkmark should be unchecked.

Our menus do not update when a specific editor is focused, so our only chance for these potentially editor specific actions is to have a generic "Toggle X" label, until we can make that the menus update whenever a specific editor gets focused.

**Comment by alexandrudima** [comment]
Will postpone for September. Multiple Toggle actions share the same problem.

**Comment by alexandrudima** [comment]
I have migrated `ToggleMinimapAction`, `ToggleRenderControlCharacterAction` and `ToggleRenderWhitespaceAction` to be workbench actions such that they can run also when an editor is not in opened.
