### ISSUE TITLE
Merging response from multiple DocumentFormattingEditProviders

### ISSUE THREAD

**Issue by bmewburn** [Microsoft/vscode#33477]
Many of the features in VSCode allow multiple providers to be registered. This allows a PHP language server and HTML language server to work very well together for most features with minimal effort. However, for format providers the API states:

> Multiple providers can be registered for a language. In that case providers are sorted by their score and the best-matching provider is used. Failure of the selected provider will cause a failure of the whole operation.

In this case the response from both formatters is valid, but only one result can be applied. Would it be possible to merge `TextEdit`s provided they did not overlap?

**Comment by jrieken** [comment]
> Would it be possible to merge TextEdits provided they did not overlap?

Yeah, that might be possible. The question is if its useful? I see a case which combines two different formatters, like TypeScript formatting and a "formatter" that removes trailing whitespace but two formatter of the same domain might compete and the changes of the second formatter might cause the first formatter to undo them etc

**Comment by bmewburn** [comment]
I can see how it could get messy, extensions can already interfere with each other and this could add a further way for this to happen. However, the usefulness would be in increasing the synergy between language servers. Combined HTML and PHP intellisense has been a popular feature request #670. The screenshot below shows the standard HTML language server and PHP intelephense both providing features to the IDE for the same file. They work very well together out of the box because they each return falsey responses for regions of the document they dont understand. Though, for formatting the complete document, the user must format in html language mode, change to php language mode and format again.

Thinking of this more, rather than merging the response, it would be useful to repeatedly apply format provider text edits on each response then make subsequent requests with the newly transformed source.

I guess the wider issue is how to leverage multiple language servers in the same document which is also identified in this issue #1751. It would be nice to have document range activation events, not just per document, and to assign multiple languages to a file.

![html_php_lang_server](https://user-images.githubusercontent.com/5885195/29906154-83a6ed4c-8e56-11e7-8710-4242fd30d8b4.gif)

**Comment by jrieken** [comment]
Yes, we like composing but not at that level. We have an html-extension that supports embedded JS/CSS etc but not by combing the results of different extensions but by delegating to the corresponding language brains. So, to us the extension appears as one formatter and internally it delegates the different formatters (that it consumes as library). 

We think that is the better approach because it always start with a language that embeds other languages, e.g. php embeds html. Html doesn't know that it now sits inside a php file, in fact html is much older then php and no html parser expects/skips php syntax elements. If I today invent a new language that embeds php it would be my responsibility to make it work and I cannot expect php to take care.

**Comment by jrieken** [comment]
Closing as we are not planning any work on merge formatter results
