### ISSUE TITLE
Sometimes Inline View doesn't work

### ISSUE THREAD

**Issue by jhasse** [Microsoft/vscode#33500]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T17:16:27.618Z)
- OS Version: Linux x64 4.12.8-300.fc26.x86_64
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
RPMSpec|1do|0.1.0
fortran|Gim|0.1.0
format-indent|Kas|1.3.0
vscode-docker|Pet|0.0.16
python|don|0.7.0
vscode-rust|kal|0.4.2
cpptools|ms-|0.12.3
twig|wha|1.0.2

---

Steps to Reproduce:

1. Open a Side by Side diff view.
2. Select … -> Switch to Inline View
3. Nothing happens.

After restarting VS Code it works again, I'm not sure what has caused this or how to further debug the issue.

**Comment by alexandrudima** [comment]
@jhasse If this happens again, please check the Developer Tools for any errors. 

It would also help if you can remember any specific steps you took that might reproduce the problem. Switching to inline diff works reliably for me...

`F1` > `Developer: Toggle Developer Tools` will bring up the Developer Tools and any error would be printed there. Alternatively, this might have been caused by something (an extension or something else) constantly touching the user `settings.json` or something along those lines. Every time the user `settings.json` is touched, we reload our settings, and that could potentially result in the diff editor resetting to be side by side or be however it is configured in there.

**Comment by jhasse** [comment]
Just ran into this again (1.16.0 now).

> F1 > Developer: Toggle Developer Tools will bring up the Developer Tools and any error would be printed there. 

In the "Console" tab? Unfortunately nothing shows up there.

> Alternatively, this might have been caused by something (an extension or something else) constantly touching the user settings.json or something along those lines.

I've checked the last acces/modification time with `stat`: It didn't seem to have changed.
