### ISSUE TITLE
Pass max_old_space_size to TSServer

### ISSUE THREAD

**Issue by danielscottjames** [microsoft/vscode#33524]
Per discussion here: https://github.com/Microsoft/TypeScript/issues/18055

Some things I noticed while looking into this:
* I believe either `--max_old_space_size` or `--max-old-space-size` works, v8 args can be dashes or underscores. Underscores work for sure.
* TSServer appears to have special logic if `global.gc` is available, so maybe consider adding `--expose-gc` as well.
* I believe the maximum settings for 64-bit builds of Node is `4096`
* There's this: https://github.com/electron/electron/issues/9693. Essentially when running VS Code with the `./script/code.sh` script, setting these flags in `execArgv` options in `typescriptserviceclient.ts` had no effect. ~I think it'll work if Electron is packaged and ran normally, but I'm not positive.~

**Comment by mjbvz** [comment]
I gave this a shot but was unable to get it working even when using a production build of VS Code. Looks like this is blocked by: https://github.com/electron/electron/issues/10413

**Comment by MLoughry** [comment]
@mjbvz I'm running into the same issue. Our project has to `tsc` with 4GB of memory, and investigations with @amcasey seem to indicate the issue is a lack of memory for `tsserver`.

It looks like both Electron issues are resolved, so is this issue now unblocked? It would be great if `tsserver` memory were configurable in workspace settings.

**Comment by mjbvz** [comment]
@MLoughry Can you try making the change and submit a PR if it works? Here's the code where we spawn the tsserver process: https://github.com/microsoft/vscode/blob/f4524551e98945a3025f6038d3d32500182ff167/extensions/typescript-language-features/src/tsServer/spawner.ts#L88

**Comment by MLoughry** [comment]
I'll try to set up an enlistment today/tomorrow and try adding a hard-coded value to see if it works. If it does, do you have a quick pointer on where the guide/code to add a new setting would be?

**Comment by amcasey** [comment]
@mjbvz We did an A/B test when VS made this change and OOMs did go down (as you might hope).  When I debugged locally with @MLoughry, we also tried with VS (which passes `max_old_space_size`) and I don't believe we saw a server crash (though I didn't specifically look for one).

**Comment by mjbvz** [comment]
To verify:

1. Set `"typescript.tsserver.maxTsServerMemory": 128`
1. Now open VS Code
1. This should cause the TSServer to get into a bad state because we cannot load the VS Code project in that amount of memory
1. Now set it to `"typescript.tsserver.maxTsServerMemory": 4000`
1. The project should now load (you may need to restart VS Code)

**Comment by connor4312** [comment]
Works as specified and I can see that tsserver is started with --max-old-space-size=4000/128 through htop
