### ISSUE TITLE
Support multiple (hierarchical) settings files per workspace

### ISSUE THREAD

**Issue by timjim-kr** [Microsoft/vscode#33530]
Please add support for multiple `settings.json` files per workspace.

Our team has several repositories, and each repository has a committed set of vs code settings to help with formatting files appropriate to that repo.

I would like to have a custom color theme per workspace.

Another coworker would like to disable the autoformatting and run a command line script to do autoformatting before pushing to github.

At the moment, there is not a reasonable way to have personal override settings distinct from team-wide settings on a per repository basis.

Another option would be to provide some way to import a settings override file into `settings.json`.

**Comment by ryanburr** [comment]
> Another option would be to provide some way to import a settings override file into settings.json.

This would also come in handy for my use case. We have 1 root folder with multiple repositories in that root folder.

/root
--/project1
--/project2
--/project3

The problem is that some of our developers like to work out of this root folder and others like to work out of each project individually. The solution i'm looking for would be to setup our workspace settings under the /root folder and have each project extend the root workspace settings. 

TSLint has an ["extends" configuration options](https://palantir.github.io/tslint/usage/configuration/) that we use in this way. Would be nice to have our VS Code settings shared in the same manner.

**Comment by sandy081** [comment]
@timjim-kr We have released a new Workspace Feature where you can multiple folders to your workspace. May I know if that helps will your problem of having personal settings in a workspace. 

- Open the folder / project in a workspace. You can open empty window and add the folder to the workspace.

Then workspace settings are local to that workspace. Folder settings are still applicable.

Let me know if that solves your issue
