### ISSUE TITLE
Terminal doesn't handle PowerShell's space escape character correctly

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#33584]
PowerShell supports back tick (`) as a space escape character. Using this when creating a terminal command for PowerShell makes the terminal fail. 

For example dir folder` with` spaces

The command that is constructed starting the terminal is:

<img width="397" alt="capture" src="https://user-images.githubusercontent.com/1931590/29919748-dd49017a-8e4a-11e7-9abd-c2b9c81a8031.png">

**Comment by Tyriar** [comment]
Not sure we should support this on the task/terminal config level as it seems very specific to PowerShell. What do you think @daviwil?

**Comment by dbaeumer** [comment]
I am not sure but from some testing I did in the past I had the impression that the space escaping for bash which uses \ is supported. The only difference is that PowerShell uses a different escape character.

**Comment by daviwil** [comment]
Hey guys, how does this come up in practice?  You'd definitely need the backtick character to escape spaces when invoking PowerShell commands but typically people would surround strings containing spaces with single- or double-quotes, removing the need for space escaping.  Any way you could use quotation marks instead of escaping spaces?

**Comment by Tyriar** [comment]
Nothing special is done to support `\` escape on Linux/macOS as I think it's supported at a native level. I think the backtick escaping is PowerShell specific which is why it doesn't work, it would be a little weird imo if the shell was cmd.exe and backtick was being escaped in the args. I believe single and double quote escaping works just fine in the terminal args.

**Comment by dbaeumer** [comment]
The backtick character is supported on native level in PowerShell as well. I think something is simply lost when the command line is finally passed to the PowerShell executable making the command fail. May be I expressed myself incorrectly. I am not asking to support backtick as a general space escaping mechanism and that we do some smartness to make backtick work on bash or cmd. But I do think that we should pass a string containing a backtick correctly to the PowerShell executable so that it can do the right thing.

It came up  for two reason: it was used in a task executed in a PowerShell environment. As a work around I told the user to use single quotes, but it makes it more complicated if the command uses already quotes. And I wanted to use it as well. When we resolve variables and they contain spaces the easiest on bash and PowerShell is to escape the space (e.g. consider ${file} resolves to a path containing spaces)). So for example a command like 'xxx ${file}' (notice the quotes) could then be 'xxx file` with` space'. Putting quotes around the file name is more complicated.

**Comment by dbaeumer** [comment]
Removing needs more info and reopening.

**Comment by Tyriar** [comment]
I guess this would involve tinkering with the format to see what PowerShell expects then. Seems related to https://github.com/Tyriar/node-pty/pull/47, maybe backticks need to be escaped like https://github.com/Tyriar/node-pty/pull/47/files#diff-103714ba8ecf05b4f0425c2204698064R24?

**Comment by alexr00** [comment]
We would need to add special handling for PowerShell's backtick escaping since using backtick to escape space isn't universal. You can easily work around this by passing in a `string` instead of `string[]` which was added in #57971
