### ISSUE TITLE
Polish about dialog 

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#3362]
The about dialog is exceptionally dull currently:

![image](https://cloud.githubusercontent.com/assets/2193314/13260059/c4e7de04-da0e-11e5-8702-ebe1bb0f651a.png)

The Brackets about dialog also calls out all OSS contributors which would be great to do.

![image](https://cloud.githubusercontent.com/assets/2193314/13260164/30058cc2-da0f-11e5-873b-b96979a17c95.png)

**Comment by bpasero** [comment]
@Tyriar since you seem to have some ideas, I am happy to review a PR on this. Unfortunately the native dialog does not give us much options what to put in. Not sure if we want to stop using a native dialog and use a custom one instead. I favour native over custom if possible.

Sublime seems to open a little new window for the about dialog. We could certainly also do that and just host some HTML in there:

![image](https://cloud.githubusercontent.com/assets/900690/13395285/2a01dce8-deee-11e5-9f5f-478d3708c786.png)

**Comment by bpasero** [comment]
@stevencl @bgashler1 fyi

**Comment by bgashler1** [comment]
I'm assuming @Tyriar that you're referring to the production VS Code, not just the Dev *about box*.  We could definitely improve on the look of this.  I would be in favor of sticking with a native dialogue but putting HTML in it, if that's possible (or any other means that would allow us to style it nicer).

I'll work on some mockups here.

**Comment by bgashler1** [comment]
Here are some first-pass ideas...
![vs-code-about-box-dark-02](https://cloud.githubusercontent.com/assets/11839736/13587498/92af581c-e47d-11e5-822b-5111a09ca8a3.gif)
![vs-code-about-box](https://cloud.githubusercontent.com/assets/11839736/13587497/92af25f4-e47d-11e5-889d-4181574b664a.gif)

**Comment by bpasero** [comment]
Looks cool :+1:

**Comment by Tyriar** [comment]
Yeah, looking good! The date format could be a little nicer though.

**Comment by Tyriar** [comment]
@bgashler1 what sort of dialog do you think we want to go for?

- Modal dialog (like Sublime)
- File-like tab (like Atom)
- Non-native dialog (like :smile: feedback form, <kbd>esc</kbd> & `x` button to dismiss)

**Comment by bgashler1** [comment]
@Tyriar We should use a native modal dialog, if possible.

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
