### ISSUE TITLE
Confusing highlighting of matches

### ISSUE THREAD

**Issue by user3323** [Microsoft/vscode#33621]
- VSCode Version: 1.15.1
- OS Version: win7x64

GIF:
![confusing highlighting of matches](https://user-images.githubusercontent.com/24613274/29947756-00db0ed0-8eb4-11e7-9b86-464dd6f79705.gif)

I understand why it acts like that.
But I think it's visually confusing.
I think there is a need to remove `"this."` word where you select some letters, from matching highlighting.

**Comment by alexandrudima** [comment]
@user3323 I think this is perhaps specific to the theme you are using? And that the theme does not use transparency for decorations colors? What theme are you using? Does this reproduce in our default vs dark theme ?

**Comment by rcjsuen** [comment]
@alexandrudima I see this with the "Dark+ (default dark)" theme on Windows 10.

**Comment by alexandrudima** [comment]
I can reproduce some aspects of your issue, but on my machine it doesn't seem to be that confusing.

As the selection goes from selecting `zzz` to `zzzz`, etc. those strings get searched for and then highlighted again in multiples of the number of selected characters:
* the blue is the selection
* the grey is the selection highlights (occurences of the selection)
* the light blue is where the selection goes on top of the selection highlights

I agree this is ugly. Perhaps we can eliminate all the selection highlights that would intersect with the selection.

I was asking for the theme because on my machine the colors are a bit different, or perhaps I'm dragging differently than you? (or perhaps you have some color customizations in your user settings?)

![kapture 2017-09-01 at 11 43 45](https://user-images.githubusercontent.com/5047891/29964598-d533a3ee-8f0a-11e7-8a74-47d409412d4d.gif)

**Comment by user3323** [comment]
@alexandrudima, yeah, I have this crazy blue rectangle because of this:

```
"workbench.colorCustomizations": {

  "editor.selectionHighlightBackground": "#004d99",

},
```

Anyway, I think it would be good if you can make highest priority to user's selection (_higher z-index or what do you there_), so matching letters would destroy this.
