### ISSUE TITLE
emmet BEM customization via emmet.preferences

### ISSUE THREAD

**Issue by NewFuture** [Microsoft/vscode#33631]
- VSCode Version: 1.15.1
- OS Version: Windows10

1.  can not expand BEM in html
2.  `bem`  in `emmet.preferences`  dose not work

Reproduces without extensions: Yes

**Comment by ramya-rao-a** [comment]
@NewFuture Can you share how you are expecting bem to work?

Adding the `|bem` at the end of the abbreviation works in the below example

![bem](https://user-images.githubusercontent.com/16890566/29956120-a5ece846-8e99-11e7-87f5-e9ddae527adb.gif)

**Comment by NewFuture** [comment]
@ramya-rao-a  thanks for your reply.
I prefer it to be configurable. 
Just like the previous version
```json
{
   "emmet.syntaxProfiles": {
        "html": {
            "filters": "html, bem"
        }
    }
}
```

**Comment by ramya-rao-a** [comment]
@NewFuture That is tracked in #33601. Closing this issue as duplicate.

I just added support for filters from the `emmet.sytnaxProfiles` setting yesterday.
You can try it out in our latest Insiders which you can get from https://code.visualstudio.com/insiders

Note that at present we support only the `bem` and `c` filters

Do you use the `bem.elementSeparator` and `bem.modifierSeparator` under `emmet.preferences`?
If yes, then what are the values you set them to?

**Comment by NewFuture** [comment]
great 👍 

We use the  `emmet.preferences` to config  `bem`
```json
    "emmet.preferences": {
        "bem.elementSeparator": "-",
        "bem.modifierSeparator": "_",
        "bem.shortElementPrefix": "-"
    }
```
but it seems not work now.

**Comment by ramya-rao-a** [comment]
The default bem settings work, but the customizations don't. I'll look into it.

**Comment by ramya-rao-a** [comment]
In the latest Insiders, the bem customizations from `emmet.preferences` are used by Emmet 2.0
Found an issue upstream when trying to customize the modifier though. Logged https://github.com/emmetio/html-transform/issues/4

**Comment by ramya-rao-a** [comment]
@NewFuture I need some help testing the bem customizations. We have some trouble in getting signed bits at the moment and so no Insiders builds are out. If you can share your OS details, then I can give you the link to the unsigned Insider bits which you can test

**Comment by NewFuture** [comment]
@ramya-rao-a thank you. And what do the OS details contain?

**Comment by ramya-rao-a** [comment]
@NewFuture Oh I just want to know if you are on Windows or Mac or Linux, so that I can give you the right links. I might have as well just given all links. Here they are

Win 64: https://az764295.vo.msecnd.net/insider/7ac1f1e05baad03d4dd8f8515f1e598180b2c97e/VSCodeSetup-x64-1.17.0-insider-unsigned.exe

Win 32: https://az764295.vo.msecnd.net/insider/7ac1f1e05baad03d4dd8f8515f1e598180b2c97e/VSCodeSetup-ia32-1.17.0-insider.exe

Mac: https://az764295.vo.msecnd.net/insider/7ac1f1e05baad03d4dd8f8515f1e598180b2c97e/VSCode-darwin-insider-unsigned.zip

Linux Deb 64: https://az764295.vo.msecnd.net/insider/7ac1f1e05baad03d4dd8f8515f1e598180b2c97e/code-insiders_1.17.0-1506717283_amd64.deb

Linux rpm 64: https://az764295.vo.msecnd.net/insider/7ac1f1e05baad03d4dd8f8515f1e598180b2c97e/code-insiders-1.17.0-1506717444.el7.x86_64.rpm

You `bem` settings from `emmet.preferences` should work now.

**Comment by ramya-rao-a** [comment]
If you are on Windows, then new builds for Insiders are now out.
You should be able to update by restarting vs code or get it from https://code.visualstudio.com/insiders

**Comment by NewFuture** [comment]
got it, thanks.

It works now 👍
