### ISSUE TITLE
Feature Request: A *scratch* buffer

### ISSUE THREAD

**Issue by baldmountain** [Microsoft/vscode#33684]
In emacs there is a *scratch* buffer. It's just there to take random text and musings. Yes, you can create a *scratch* file in your project and add it to .gitignore, but it might be nice if it was built in.

**Comment by bpasero** [comment]
@baldmountain File > New File?

**Comment by baldmountain** [comment]
Like I said, yes you could create a local file, and that may be fine, but I thought it might be convenient to have a scratch pad built into Code, that is always available, and that isn't meant to be saved (but probably should persist somewhere). Think of it the same way you do the pad of PostIt notes on you desk. A place to scratch a quick note to remind yourself of something, or remember a value or bit of code so you don't have to keep it in your brain.

**Comment by ZombieProtectionAgency** [comment]
File > New File doesnt actually create a local file until you save it and it would persist across closing/opening the editor. Obviously you have to keep it open as a tab somewhere but it works really well for that as is.

**Comment by baldmountain** [comment]
OK.

**Comment by TAGC** [comment]
Don't know why this issue was closed - this would be really useful. The problems with just keeping stuff in a tab are:

1. If you close the tab, the data is permanently lost
2. You can't use commands / syntax highlighting specific to files with particular extensions (e.g. Python commands/highlighting within .py files)

JetBrains have done a good job tackling this issue in their editors with the concept of scratch files. You can enter a sequence of keypresses to bring up a dialog box letting you create scratch files for a number of languages (JavaScript, TypeScript, Java, Python, etc.) and it will create a scratch file somewhere under a temporary directory with the appropriate extension and therefore the appropriate syntax highlighting / set of available commands.

**Comment by baldmountain** [comment]
@TAGC I closed it because it felt like I was arguing for something that others just didn't see a need for. I gave up. 

I really like the idea of a set of language specific scratch files. At the moment I just create a file named `*scratch*` in my project and add that name to .gitignore.
