### ISSUE TITLE
Implement Intellisense Suggestion Mode

### ISSUE THREAD

**Issue by j-manu** [microsoft/vscode#33725]
When intellisense suggestions is open it auto selects the first option. Please provide an option to disable that. I think this is called suggestion mode in Visual Studio - https://blogs.msdn.microsoft.com/zainnab/2010/01/22/intellisense-suggestion-mode/ 

Why?
-----
Apart from the use case outlined in the linked article, when there is no default suggestion the TAB key can be reconfigured to cycle through suggestions and then use enter to accept a suggestion. When no suggestion is selected, enter key will insert a new line. Currently this behaviour is impossible as far as I know.

**Comment by jrieken** [comment]
> When intellisense suggestions is open it auto selects the first option

Not really and it highly depends on the suggestions and your text left of the cursor. If there is no text typed yet, IntelliSense will use an order provided by your extensions. Otherwise the typed text will be ranked against the suggestions and suggestions are sorted by their match


Even today you should be able to reconfigure the tab-keybinding, not really sure yet what is missing here

**Comment by j-manu** [comment]
Set - **editor.acceptSuggestionOnEnte**r to "**on**"


![image](https://user-images.githubusercontent.com/72501/30015782-e9666a6a-916f-11e7-8e44-ffe81b6ebff3.png)

I have just typed fet and the first option in intellisense is selected. What I mean by selected is that if I press enter now, intellisense will autocomplete the word to fetching. What I want to happen is inserting a linebreak. I want to explicitly select an intellisense option by using arrow keys (or by rebinding tab key) and then press enter to accept it.

**Comment by philippludwig** [comment]
Yes, please! This is really annoying, especially when autocomplete comes up during writing comments.

**Comment by e-monson** [comment]
Great developer experience.

**Comment by BIKA-C** [comment]
Is there an option to fix it now?

**Comment by 2u6z3r0** [comment]
I was facing same issue for js code.
Setting **"editor.acceptSuggestionOnCommitCharacter": false** resolved my issue.

**Comment by haoadoresorange** [comment]
This is super annoying as of today, sometimes typing `{` will result in a suggestion from other intellicode (for example tabnine). Default selecting the first option mean I have to hit `Esc` everytime. Please provide a switch to disable this. This has been voiced since 2017. It's not like it was yesterday.

**Comment by macintacos** [comment]
I opened #139825 - I'd encourage folks to thumbs-up that one so that it at least gets into the backlog.
