### ISSUE TITLE
Pasting code destroys indentation of both the pasted code and nearby lines

### ISSUE THREAD

**Issue by wittlesouth** [microsoft/vscode#33760]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T17:15:57.756Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.16
jsx|Twe|0.0.1
vscode-eslint|dba|1.2.11
python|don|0.7.0
debugger-for-chrome|msj|3.2.1

---

Steps to Reproduce:

1.  Start with code that looks like the following:

```
describe('This is a test', () => {
  it('handles addTag()', (done) => {
    let tagUserUpdated = tagUser.updateField([User.USER_PREFERENCES, User.PREFERENCES_TAGS_SELECTED], 'Tag 2|Tag 1')
    .afterUpdateSuccess()
    const stateTagUpdateSuccess = setStatusMessage(
      clearUserFetching(User.setCurrentUser(stateTagUser, tagUserUpdated), tagUserUpdated), userComponentText.userUpdated
    )
    let store = createStore(testUserState, stateTagUser, applyMiddleware(thunkMiddleware))
    nock(process.env.TEST_URL).put('/users/' + userTestData[User.USER_ID]).reply(200, {})
    testAsync(store, stateTagUpdateStart, stateTagUpdateSuccess, done)
    tagUser.setSelectedTag(store.dispatch, 'Tag 1')
  })
})

```

2. copy the 2nd line, and past it before the last line. The last line will be indented two spaces to match (presumably) the code that was pasted. This is a simple example, there are lots of other broken cases. Cutting and pasting code fragments is now significantly less productive than before. This seems to be a recent regression.

Reproduces without extensions: Yes/No

**Comment by codingthat** [comment]
I'm also seeing this on:

- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T17:16:27.618Z)
- OS Version: Linux x64 4.4.0-53-generic

IIRC, before upgrading VSCode to 1.15.1, this type of operation had worked flawlessly.

**Comment by alexandrudima** [comment]
@wittlesouth @codingthat This is indeed something that shipped with 1.15. It can be turned off via `"editor.autoIndent": false`

**Comment by codingthat** [comment]
Thank you so much @alexandrudima , that works great.  This was really annoying until you provided a workaround.  :)

**Comment by agos** [comment]
For what is worth, I am seeing destructive behaviour on paste even with `"editor.autoIndent"` set to
 `false`

**Comment by robertopc** [comment]
I put editor.formatOnPaste to false and this behavior stop.

**Comment by rebornix** [comment]
This is due to the limited architecture (regex based indentation rules and only support limited code styles), we may want to consider using formatters if they exist for indenation adjustment (if interested, we can discuss in https://github.com/microsoft/vscode/issues/19847).

For this particular issue, if the indentation rules are leading to more trouble than having no auto indent, you can set `editor.autoIndent` to `advanced` to disable the regex based indentation adjustment. As we don't have an easy good-enough fix for it, we close it for now and explore better solutions through issues like (https://github.com/microsoft/vscode/issues/19847 and https://github.com/microsoft/vscode/issues/34621).
