### ISSUE TITLE
Pasting inside an array adds a semicolon to the end

### ISSUE THREAD

**Issue by johnpapa** [Microsoft/vscode#33766]
- VSCode Version: Insiders 1.16.0
- OS Version: macOS Sierra 10.12.6

Steps to Reproduce:

1. See the embedded video

![2017-09-03_19-28-44](https://user-images.githubusercontent.com/1202528/30007515-7fcae54a-90de-11e7-8c17-2e948561f384.gif)

**Comment by alexandrudima** [comment]
@johnpapa 

What values do you have configured for the following settings?
* `editor.formatOnPaste`
* `editor.autoIndent`
* `editor.formatOnSave`
* `files.autoSave`

Do you use the tslint extension? What value have you configured for the following setting?
* `tslint.autoFixOnSave`

Do you use other TS related extensions?

I am asking the above because my gut feeling is that there is some sort of autofix on save running for you. I have seen the missing semicolon proposal coming in from tslint when using a non-imported symbol. e.g. (below)

---

What is the minimum amount of turned on settings that reproduces the problem? i.e. **I would like for us to find out if this is a format on paste, a format on save, or a auto fix on save issue?** cc @egamma @jrieken if you have ideas.

---

Here I am using the symbol `Viewport` that is not imported from `vs/editor/common/viewModel/viewModel`
 * there are multiple fixes suggested (such as the good one to add an import statement), but there is also the one that suggests I add a semicolon
 * I agree that this is not 100% the same example as yours, but that is where I saw semicolons being mentioned
<img width="653" alt="screen shot 2017-09-04 at 11 41 53" src="https://user-images.githubusercontent.com/5047891/30021003-2a050e8c-9166-11e7-98d6-56bb56ba1b8f.png">

**Comment by johnpapa** [comment]
```
	"editor.formatOnPaste": true,
	"editor.formatOnType": true,
	"files.autoSave": "afterDelay",
```

I do not have the other 2 you mentioned, so whatever the defaults, are is what I expect.

I do have the tslint and prettier extensions installed, too.

**Comment by egamma** [comment]
@johnpapa formatOnPaste applies the TS formatter for a range, but as far as I know the formatter only adds/removes white spaces but doesn't insert semicolons. 

Curious whether this is caused by an extension. For example, do you have the Prettier extension installed? What happens when you have `formatOnPaste: true` but you disable all extensions (Extensions Viewlet>...>Disable All Installed Extensions).

**Comment by johnpapa** [comment]
Good idea @egamma .

I just disabled all extensions, enabled `formatOnPaste` to `true`, then pasted into an array, and I got the `;` at the end.

![2017-09-05_07-42-27](https://user-images.githubusercontent.com/1202528/30059643-efbab26a-920d-11e7-9c5f-c7f1480bc859.gif)

**Comment by egamma** [comment]
@johnpapa after disabling an extension you need to reload the window, from the movie it looks like you did not reload the window yet. There is the blue `Reload` button visible. Can you please try again disabling and then reloading.

**Comment by johnpapa** [comment]
My mistake, good catch. After reload and I paste, nothing happens at all. 
![2017-09-05_08-10-04](https://user-images.githubusercontent.com/1202528/30060528-c739b2b0-9211-11e7-934a-5829bc26d753.gif)

**Comment by egamma** [comment]
@johnpapa this proofs that this is not an issue in VS Code but in one of your installed extensions. To narrow this down to a particular extension you have to enable all extensions and then enable one extension after the other and retry. 

You can easily enable a single extension by clicking on the brush wheel

![image](https://user-images.githubusercontent.com/172399/30064492-35a9ba8e-9252-11e7-8d35-3d010b50ed26.png)
