### ISSUE TITLE
Ctrl + KZ for Zen Mode is the german abbreviation for Konzentrationslager (concentration camp)

### ISSUE THREAD

**Issue by schorschie** [Microsoft/vscode#33836]
- VSCode Version: 1.15.1
- OS Version: Windows 7

Steps to Reproduce:
1. Push Control + K Z

Is it possible to change the shortcut for Zen mode to something else? In german KZ is the abbreviation for Konzentrationslager (concentration camp) and is burned into our minds. We never use this two letters in a different context.

regards
Gregory Lippe 

Reproduces without extensions: Yes/No

**Comment by isidorn** [comment]
Hi @schorschie thanks for rasing this concern, however all keyboard shortucts in VS code are configurable, thus you can configure zen mode to be whatever keyboard shortuct you want
Preferences > Keyboard shortcuts

Changing the default shortcut is usually not a good idea since it breaks muscle memory of existing users.
Thanks for understanding
