### ISSUE TITLE
could not run in x2go session on a headless server without traditional X.org

### ISSUE THREAD

**Issue by axxName** [Microsoft/vscode#33879]
- VSCode Version: 
$ code --version
1.15.1
41abd21afdf7424c89319ee7cb0445cc6f376959

- OS Version:
```
$ uname -a
Linux debugME 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u3 (2017-08-06) x86_64 GNU/Linux
on a headless server inside LXC container with X2Go terminal server
```

```
~$ ps -ef|grep X
debug      868     1  0 \u0430\u0432\u043327 ?     00:25:41 /usr/lib/nx/../x2go/bin/x2goagent -extension XFIXES -nolisten tcp -nolisten tcp -dpi 96 -D -auth /home/debug/.Xauthority -geometry 800x600 -name X2GO-debug-50-1502958126_stDLXDE_dp32 :50
debug      925     1  0 \u0430\u0432\u043327 ?     00:00:00 /bin/bash /usr/bin/x2goruncommand 50 868 debug-50-1502958126_stDLXDE_dp32 43903 startlxde nosnd D
debug     1055   925  0 \u0430\u0432\u043327 ?     00:00:00 /usr/bin/lxsession -s LXDE -e LXDE
debug     1255  1055  0 \u0430\u0432\u043327 ?     00:20:13 lxpanel --profile LXDE
debug     1264  1055  0 \u0430\u0432\u043327 ?     00:00:29 pcmanfm --desktop --profile LXDE
```

Any other applications works fine

```
~$ code --verbose
[18391:0906/103505.218657:WARNING:audio_manager.cc(317)] Multiple instances of AudioManager detected
[18391:0906/103505.218958:WARNING:audio_manager.cc(278)] Multiple instances of AudioManager detected
{ Error: ENOENT: no such file or directory, open '/home/debug/.config/Code/storage.json'
    at Object.fs.openSync (original-fs.js:558:18)
    at Object.fs.readFileSync (original-fs.js:468:33)
    at e.load (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:4:190326)
    at e.getItem (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:4:189889)
    at e.handleRestarted (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:4:204229)
    at new e (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:4:204124)
    at t.create (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:4:29264)
    at t._createInstance (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:4:165671)
    at t._createAndCacheServiceInstance (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:4:166642)
    at t._getOrCreateServiceInstance (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:4:165832)
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/debug/.config/Code/storage.json' }
[main 10:35:05] Starting VS Code in verbose mode
[main 10:35:05] from: /usr/share/code/resources/app
[main 10:35:05] args: { _: [],
  help: false,
  h: false,
  version: false,
  v: false,
  wait: false,
  w: false,
  diff: false,
  d: false,
  goto: false,
  g: false,
  'new-window': false,
  n: false,
  'unity-launch': false,
  'reuse-window': false,
  r: false,
  performance: false,
  p: false,
  'prof-startup': false,
  verbose: true,
  logExtensionHostCommunication: false,
  'disable-extensions': false,
  disableExtensions: false,
  'list-extensions': false,
  'show-versions': false,
  nolazy: false,
  'skip-getting-started': false }
[main 10:35:05] Unable to read folders in /home/debug/.config/Code/Workspaces (Error: ENOENT: no such file or directory, scandir '/home/debug/.config/Code/Workspaces').
[18391:0906/103505.762094:ERROR:browser_main_parts.cc(123)] X IO error received (X server probably went away)
```

**Comment by isidorn** [comment]
Please make this issue readable and nicely formated if you would like us to investigate more

**Comment by axxName** [comment]
Log from application that cannot run not nicely formatted?
I don't know what to do with it.

**Comment by roblourens** [comment]
I'm not sure what's supposed to happen on a headless server. VS Code isn't very useful without a GUI...

**Comment by ihalip** [comment]
This is an error originating from [electron](https://github.com/electron/electron/blob/master/brightray/browser/browser_main_parts.cc#L122). Looks like Atom has a [related issue](https://github.com/atom/atom/issues/4360).

**Comment by cobrakoral** [comment]
@isidorn  nicely formatted:
[12651:1106/181120.117485:ERROR:gl_surface_glx.cc(411)] GLX 1.3 or later is required.
[12651:1106/181120.117560:ERROR:gl_initializer_x11.cc(148)] GLSurfaceGLX::InitializeOneOff failed.
[12651:1106/181120.137550:ERROR:gpu_child_thread.cc(324)] Exiting GPU process due to errors during initialization

I can confirm this bug exists. I am using a development machine remotely at the moment, and locally vscode works and remotely through x2go it doesn't.
I tried both vscode binary build from microsoft.com version 1.17 and building my own rpm package "vscode-oss" 1.18 and they all have the same behavior, bug exists on both versions.
I tried a fresh built with a commit from today:

commit 531d34157bf112a8af27f0d6e4bc2ee7c86324cd (HEAD -> release/1.18, origin/release/1.18)
Author: Sandeep Somavarapu <sasomava@microsoft.com>
Date:   Mon Nov 6 18:43:14 2017 +0100
    Update label #37717
commit e0e53033825dd2ad1ec75d8fb86afc74bae53bd6

I got past the error that @axxName reported maybe because I started the program locally first, so it was able to create its config files at the first time run, and I got a more meaningful message:
[cobra@localhost ~]$ uname -a
Linux localhost 3.10.0-693.5.2.el7.x86_64 #1 SMP Fri Oct 13 10:46:25 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux
[cobra@localhost ~]$ code-oss --verbose
[12651:1106/181120.117485:ERROR:gl_surface_glx.cc(411)] GLX 1.3 or later is required.
[12651:1106/181120.117560:ERROR:gl_initializer_x11.cc(148)] GLSurfaceGLX::InitializeOneOff failed.
[12651:1106/181120.137550:ERROR:gpu_child_thread.cc(324)] Exiting GPU process due to errors during initialization
[main 5:11:20 PM] Starting VS Code in verbose mode
[main 5:11:20 PM] from: /usr/share/code-oss/resources/app
[main 5:11:20 PM] args: { _: [],
  help: false,
  h: false,
  version: false,
  v: false,
  wait: false,
  w: false,
  diff: false,
  d: false,
  add: false,
  a: false,
  goto: false,
  g: false,
  'new-window': false,
  n: false,
  'unity-launch': false,
  'reuse-window': false,
  r: false,
  performance: false,
  p: false,
  'prof-startup': false,
  verbose: true,
  logExtensionHostCommunication: false,
  'disable-extensions': false,
  disableExtensions: false,
  'list-extensions': false,
  'show-versions': false,
  nolazy: false,
  'skip-getting-started': false,
  'sticky-quickopen': false,
  'disable-telemetry': false,
  'disable-updates': false,
  'disable-crash-reporter': false }
[main 5:11:20 PM] Unable to read folders in /home/cobra/.config/Code - OSS/Workspaces (Error: ENOENT: no such file or directory, scandir '/home/cobra/.config/Code - OSS/Workspaces').
[12601:1106/181120.412114:ERROR:browser_main_parts.cc(122)] cobraX IO error received (X server probably went away)

**Comment by cobrakoral** [comment]
Oh, and I have all the X.org packages installed, since this is a workstation with GUI installed and everything, so it is not related to X.org packages beings installed or not. Headless or not, the problem exists while executing vscode from a X2Go session.

**Comment by rahst12** [comment]
Any workaround?

**Comment by mattli001** [comment]
I'm on Ubuntu 15.04 and workable by follow [Could not run VS Code on CentOS 7 with x2go](https://stackoverflow.com/questions/43676727/could-not-run-vs-code-on-centos-7-with-x2go/45183666#45183666)
Add the following line to the file /etc/x2go/x2goagent.options:
```
X2GO_NXAGENT_DEFAULT_OPTIONS+=" -extension BIG-REQUESTS"
```
Then restart the server and try again.

**Comment by axxName** [comment]
Yes! Now it starts up!
But it takes about 40-50 seconds. No messages and animations at this time. Just waiting for the appearance of the application window.

Thanks a lot!

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/3451
