### ISSUE TITLE
Feature Request: iOS 11/Android IDE

### ISSUE THREAD

**Issue by samtoohey93** [Microsoft/vscode#33921]
So, with iOS 11 featuring a file system and with Android obviously offering a file system in the native OS, is there any consideration to bring this or a lighter more iOS friendly version of VS Code to iOS so there is a proper IDE on the tablet platform?

I understand there would be restrictions for what it could do, but it would really help those who cant afford the best machines and who only have iPads or Android Tablets be comfortable with tablet based programming.
I know apps like Buffer and Coda exist, built there is always room for improvement.

**Comment by ShubhamDeshmukh8** [comment]
Yes please. Editors for Windows, Linux & Mac have been done many times over, but there is a sheer lack of good editors on Android. I tried a few 'top' editors on Android, none were good enough, mostly due to their poor UI design and workflow. And more annoyingly, ads covered the editor window. Distracting to say the least, in fact a little frustrating to use any.

Visual Studio Code will add a good continuity to using on Desktop or Linux, I think this is a feature-request worth considering.

PS: Obviously a good editor needs a good keyboard, and Microsoft has a solution there already - Keyboard for Excel - worked for me. Even has 'Tab' key, solves half the problem! :)

**Comment by laem** [comment]
:+1 Android desktop mode (connect the phone to a screen and it launches a traditional desktop UI for a physical mouse and keyboard) introduced by Samsung and followed by Huawei will bring lots of users of this feature.

**Comment by sayomelu** [comment]
I also want to edit my codes JUST using a light iPad when I am on my way! Support you!

**Comment by chrisdias** [comment]
hi - we're [grooming our backlog this milestone](https://github.com/Microsoft/vscode/wiki/Issue-Grooming) and this request is unlikely to make our backlog in the next 6-12 months so i'm closing this suggestion.
