### ISSUE TITLE
Configuration for disabled extensions generates warning in problems window

### ISSUE THREAD

**Issue by Gruntfuggly** [microsoft/vscode#33931]
If I have an extension disabled in a workspace (only), any configuration settings in my User config generate a warning "Unknown configuration setting".

I understand why this is happening, but there should be a way to inhibit the warnings, otherwise it continuously obscures my build process warnings and errors.

It would be nice if contributions for a disabled extension could be processed to allow the warnings to be automatically ignored.

Alternatively, could an 'ignore warning' option be added to the context menu? This could store the ignored warning in the workspace settings.

**Comment by joandvgv** [comment]
+1 Need this

**Comment by sandy081** [comment]
Since there is a specialised settings UI editor, showing warnings for unknown or unsupported settings would be a noise. Hence they will be shown as hints as follows:

![image](https://user-images.githubusercontent.com/10746682/61665133-91c28780-acd4-11e9-9e80-d945c313d5eb.png)

![image](https://user-images.githubusercontent.com/10746682/61665160-9d15b300-acd4-11e9-8b12-231e03709c7f.png)
