### ISSUE TITLE
Stupid jsdoc completions

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#33948]
<img width="553" alt="screen shot 2017-09-07 at 17 23 19" src="https://user-images.githubusercontent.com/1794099/30171140-4d94ee2a-93f1-11e7-8009-aa0a9316e99d.png">

**Comment by mjbvz** [comment]
The cursor is inside the object literal, right? That is a valid context for JSDoc comments in general:

```js
const a = {
    /**
     * Description
     */
    b: 1
}
```

**Comment by jrieken** [comment]
> That is a valid context for JSDoc comments in general:

Why? I'd expect that jsdoc is only used on symbol-declarations, like the *declaration* of `Electron.SaveDialogOptions` not every instantiation of it. The cursor is between the curly-brackets, nothing gets declared there, indeed nothing has been written there so for what symbol am I adding jsdoc comments?

**Comment by octref** [comment]
![image](https://user-images.githubusercontent.com/4033249/31403722-dcce7f3a-adae-11e7-90d4-daf91662e13f.png)

![image](https://user-images.githubusercontent.com/4033249/31403754-f447510a-adae-11e7-8e03-aa32fd146e10.png)

This doesn't make sense, suggesting JSDoc everywhere and putting it as the first item simply because it starts with `/`.
