### ISSUE TITLE
Invalid syntax highlighing of <!----------blablabla-----------> in .html file

### ISSUE THREAD

**Issue by luqimin** [Microsoft/vscode#33944]
as mentioned in the title..

**Comment by roblourens** [comment]
I see that it messes up colorization. Not sure if it's invalid or what:

![image](https://user-images.githubusercontent.com/323878/30176411-305a12c0-93b7-11e7-9caa-a07e03ce3e97.png)

**Comment by emackey** [comment]
See also:

https://stackoverflow.com/questions/26600092/why-are-double-hyphens-invalid-in-html-comments

https://stackoverflow.com/questions/1850439/double-hyphen-in-script-makes-firefox-render-strangely

**Comment by iMahesh** [comment]
@luqimin if you a leave `space` on both sides of `--------blablabla---------` just like `<!-- --------blablabla--------- -->` instead of `<!----------blablabla----------->` it works perfectly well(It's a best practice as well). 
It'll also work if you add one more `-` on the right-hand side of the `blablabla`, just in case if you don't want to leave any space in-between. 

I wouldn't recommend typing `<!-- -->` manually to comment lines. better to use `Ctrl+/` to avoid any DOM rendering issues.

[SOURCE](https://www.w3.org/TR/REC-xml/#sec-comments)

**Comment by yume-chan** [comment]
Multiple hyphens in comments are valid in [HTML5 standard](http://w3c.github.io/html/syntax.html#comments):

> ### 8.1.6. Comments
> Comments must have the following format:
> 1. The string "`<!--`"
> 2. Optionally, text, with the additional restriction that the text must not start with the string "`>`", nor start with the string "`->`", nor contain the strings "`<!--`", "`-->`", or "`--!>`", nor end with the string "`<!-`".
> 3. The string "-->"

In fact, according to the parsing rules, `<! >`, `<!-- <!-- -->` and `<!-- --!>` are parse errors but recoverable and also represents an HTML comment.

Of course, they are invalid in XML standard, but HTML is not XML.

**Comment by aeschli** [comment]
This issue was moved to textmate/html.tmbundle#75
