### ISSUE TITLE
Debug console uses unexpected text colours for some strings

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#34043]
Add the following code in an extension:

```ts
console.log('true vs true');
console.log('true vs false');
console.log('false vs true');
console.log('false vs false');
```

When it runs, the colours of the output lines are inconsistent:

![Debug colours](https://user-images.githubusercontent.com/1078012/30224583-3c93b292-94c7-11e7-9bc2-90f754168418.png)

Looking in the dev tools, it seems the blue lines have `boolean` in their CSS class which is missing from the white lines. It seems strange that `true vs false` and `false vs true` are categorised differently.

<img width="540" alt="Dev tools" src="https://user-images.githubusercontent.com/1078012/30224674-8df8befc-94c7-11e7-9949-f991b5e736b4.png">

**Comment by weinand** [comment]
@isidorn why do we try to colorise stuff in the debug console?
I remember that I've already filed an issue about numbers being colorised in strange ways.

**Comment by isidorn** [comment]
@weinand currently we use some simple regex heuristics to try to colorise booleans, numbers and strings.
Also we colorise some ANSI output.

I can remove all of these colors but not sure if it will upset the users.
And yes I agree that the colorisation is a bit flaky.
Suggestions on what to do here are very welcome.

**Comment by weinand** [comment]
@isidorn please remove the regex heuristics for colorising because it is surprising and mostly wrong. But keep the ANSI coloring because it is deterministic and expected.

**Comment by isidorn** [comment]
@weinand makes sense. Do you get a sense that it is mostly wrong also in the watch and variables pane since we use the same heuristic there. Should it also be removed there?
IMHO it is giving some additional info in those panes and nobody complained so we should keep the heuristic for the variables and watch

![screen shot 2017-09-12 at 15 50 57](https://user-images.githubusercontent.com/1926584/30329328-43b8b758-97d2-11e7-90ca-5c6ecae0e0a3.png)

**Comment by DanTup** [comment]
My 2¢...

I was surprised to see colours in the debug output. I'm not against it, though if it's kept it should be reliable.

If the same regex is being used for the watch window, then even if colours are removed from the debug console, then I think it needs fixing, since it'll presumably also color the string `"false vs false"` and `"false vs true"` differently?

**Comment by weinand** [comment]
If we want to continue to support regexp-based "value colorisation", we should only do it where we control and understand the underlying syntax. This is true for the variables and watches view and for structured objects in the debug console since all are trees.
But we should not try to do it where we have no clue what the underlying structure is. This applies to to all "string" output in the debug console. Here only the ANSI colours should be honoured. 
 
For the trees we should make sure that the regexps only match simple values like `true` and `false`but not something like `true and false` or a `true`embedded in a string.

**Comment by isidorn** [comment]
Thanks.
Now we do not colorize in repl outside of a tree.

@DanTup I have checked the [boolean regex](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/debugViewer.ts#L1) and it looks fine to me. I think the difference in coloring comes from the fact that those output elements came in a different order from the adapter. Which means that part of tha string first came which passed the regex check making it blue.
Though this will no longer happen since I removed color for that case in the repl

**Comment by DanTup** [comment]
@isidorn I don't understand the explanation for it happening (the output is in the same order as the `console.log`s?) but I don't know the internals of how the data gets back to the debug output window. If it makes sense to you (and is no longer an issue anyway), all sounds good to me 👍

**Comment by isidorn** [comment]
@DanTup no it does not make 100% sense to me either, I was just speculating as to what might have been the cause. Since the adapter can send the output events chunked to vscode (I did not investigate further)

**Comment by roblourens** [comment]
It would be nice to keep colorization for 'evaluate' requests, since the result has a 'type'. node2 doesn't set the type... it could though.

![image](https://user-images.githubusercontent.com/323878/30943241-96845fae-a3a4-11e7-8cb1-fe458d6023a7.png)

vs previously

![image](https://user-images.githubusercontent.com/323878/30943246-9c4d074c-a3a4-11e7-8236-940398078d7d.png)

**Comment by isidorn** [comment]
@roblourens please file a feature request to me to respect the type in the debug console for colorisation
