### ISSUE TITLE
Cannot copy in DEBUG CONSOLE

### ISSUE THREAD

**Issue by CAIJUNYI** [Microsoft/vscode#34066]
- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:27:49.891Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|don|0.7.0
vsc-material-theme|Equ|1.0.2
Go|luk|0.6.65
vscode-icons|rob|7.12.0

---

Steps to Reproduce:

1. Debug the code
2. right click on the DEBUG CONSOLE window, the "Copy" item cannot execute.
![cannot_copy](https://user-images.githubusercontent.com/10704251/30238409-baee4654-9579-11e7-9286-6a15dafa3eef.png)

3. but the "Copy All" item works fine.

Reproduces without extensions: Yes/No

**Comment by isidorn** [comment]
The copy will only copy what is selected.
The issue is that we were focusing the element where the context menu is triggered, causing a confusion since it looks like that item is being selected.
The fix takes care of this by not focusing the element when context menu is invoked.

So for the copy to work please select a part of the text
