### ISSUE TITLE
Terminal crops wide character

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#34138]
My PS1 starts with `➜ ` (one arrow and one space). The space is there so there's enough space to render the arrow. But the new canvas terminal simply crops the arrow.

![image](https://user-images.githubusercontent.com/22350/30271327-2fc23a04-96f0-11e7-98bf-56db2cfb4e3f.png)

**Comment by Tyriar** [comment]
Apparently this is a particularly popular wide character (dupe in #34121), "wide" characters that take up single widths are now cropped as characters own only their cell(s). This arrow char is similar to an emoji, wherein it is a single width character followed by a space. Maybe it should be special-cased and treated like an emoji until a proper solution is devised, due to its popularity (default oh-my-zsh?).

Related: https://github.com/sourcelair/xterm.js/issues/942

**Comment by joaomoreno** [comment]
It might be the PS1 of the default theme of oh-my-zsh.

**Comment by mjbvz** [comment]
Ran into #35102 on verification but the problem with the arrow character and other wide characters seems fixed
