### ISSUE TITLE
Terminal smoke test is failing

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#34206]
https://monacotools.visualstudio.com/DefaultCollection/Monaco/Monaco%20Team/_build/index?buildId=32277&_a=summary&tab=artifacts

**Comment by sandy081** [comment]
FYI I commented out the test. Please fix it and enable it.

**Comment by Tyriar** [comment]
@sandy081 The test is failing because the DOM is no longer filled with nodes so these tests can't work the way they did previously.

Is it possible with Spectron to pull a DOM node object, including any custom properties it has? If so I could attach a reference to the xterm.js object to the terminal element which would allow querying the terminal for this sort of information really easily.

**Comment by sandy081** [comment]
@Tyriar Yes, you can access the DOM in Spectron and we do it in multiple places. For example refer to [scm](https://github.com/microsoft/vscode/blob/master/test/smoke/src/areas/git/scm.ts#L49).

This will allow you to execute java script code on the renderer process that has access to DOM and let you return the model you want. But please be aware that, Since it runs in a different process than the test process, console log does not work.

**Comment by Tyriar** [comment]
PR with fix is out https://github.com/Microsoft/vscode/pull/35381, will merge in after release is branched off.
