### ISSUE TITLE
Emmet Bem is not working in vue files

### ISSUE THREAD

**Issue by edDimensi** [Microsoft/vscode#34213]
- VSCode Version: 1.16
- OS Version: Arch Linux Manjaro i3

Steps to Reproduce:

1. `.vzr-st__content>.__left+.__right`
2. press tab

Reproduces without extensions: No

I see https://github.com/Microsoft/vscode/issues/33631 and wait for it, but now i get this problems.

![peek 2017-09-12 12-33](https://user-images.githubusercontent.com/11390039/30318834-e0207ac0-97b6-11e7-8203-7dd6bd84f67c.gif)
Vue template
![peek 2017-09-12 12-34](https://user-images.githubusercontent.com/11390039/30318835-e03dc256-97b6-11e7-86b4-5836f6e19438.gif)
in SCSS
![peek 2017-09-12 12-35](https://user-images.githubusercontent.com/11390039/30318836-e0470154-97b6-11e7-8eac-6c518c9a8498.gif)
How stop adding a class attribute permanently?

I have that settings
```
  "emmet.syntaxProfiles": {
    "javascript": "jsx",
    "vue": "html",
    "vue-html": "html",
    "html": {
      "filters": "html, bem"
    }
  },
  "emmet.triggerExpansionOnTab": true,
  "emmet.includeLanguages": {
    "vue": "html",
    "vue-html": "html"
  },
```

**Comment by ramya-rao-a** [comment]
1. For html file: Am not sure what the problem here is. I need some time to look into it. Until then avoid using the bem filter to remove the `class` attribute
2. For the vue file: I can repro it and @octref should be able to help
3. For the scss file: I am not able to repro this. Why is there html in a scss file?

**Comment by edDimensi** [comment]
All bugs in vue file.

**Comment by ramya-rao-a** [comment]
Remove the below from both `emmet.syntaxProfiles` and `emmet.includeLanguages`
```
"vue": "html",
"vue-html": "html"
```

The vetur extension now provides emmet support without you needing to add the above to get emmet support in due from VS Code core.

**Comment by ramya-rao-a** [comment]
Also, what is your expected expansion for `.vzr-st__content>.__left+.__right` ?

**Comment by ramya-rao-a** [comment]
This issue was moved to vuejs/vetur#426

**Comment by HerringtonDarkholme** [comment]
Hi

> For the vue file: I can repro it and @octref should be able to help

This is an expected behavior. Because OP mapped vue to html in `"emmet.includeLanguages"` so syntax sensitive expansion is disabled.  (See https://github.com/vuejs/vetur/issues/232#issuecomment-322709246)

Vetur provides builtin emmet suggestion which is syntax sensitive. But you have to remove includedLanguages as https://github.com/Microsoft/vscode/issues/34213#issuecomment-329242719 has said.  Also, vetur doesn't support old style tab expansion.

**Comment by ramya-rao-a** [comment]
Instead of mapping `vue` to `html` if only `vue-html` is mapped to `html`, then you should be able to get the tab expansion from the built in emmet support and the suggestion from the vetur extension, right?

**Comment by HerringtonDarkholme** [comment]
@ramya-rao-a I have tried it several weeks ago. It didn't work then. I don't know if it works now, though.
