### ISSUE TITLE
Unable to build on Windows due to oniguruma

### ISSUE THREAD

**Issue by AmadeusW** [Microsoft/vscode#34251]
- VSCode Version: 1.16.0 (source code)
- OS Version: Windows 10 1703

Steps to Reproduce:

1. Follow [Build and Run from source](https://github.com/Microsoft/vscode/wiki/How-to-Contribute#build-and-run-from-source) instructions
2. `C:\git\vscode>scripts\npm.bat install` fails while building `oniguruma`

Prerequisites:
```
C:\git\vscode>npm -v
3.10.8
C:\git\vscode>node -v
v8.5.0
C:\git\vscode>echo %PYTHON%
C:\Python27\python.exe
```

Relevant log:
```
> oniguruma@6.1.1 install C:\git\vscode\node_modules\oniguruma
> node-gyp rebuild


C:\git\vscode\node_modules\oniguruma>if not defined npm_config_node_gyp (node "C:\Users\amwieczo\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
MSBUILD : error MSB4025: The project file could not be loaded. Root element is missing.
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\amwieczo\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\amwieczo\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\git\vscode\node_modules\oniguruma
gyp ERR! node -v v8.5.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
```

The error is more descriptive when using different version of npm:
```
C:\git\vscode>npm -v
5.4.1
```

```
> oniguruma@6.1.1 install C:\git\vscode\node_modules\oniguruma
> node-gyp rebuild


C:\git\vscode\node_modules\oniguruma>if not defined npm_config_node_gyp (node "C:\Users\amwieczo\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\git\vscode\node_modules\oniguruma\build\oniguruma.vcxproj(20,3): error MSB4019: The imported project "C:\Common7\IDE
\VC\VCTargets\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct,
 and that the file exists on disk.
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\amwieczo\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\amwieczo\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\git\vscode\node_modules\oniguruma
gyp ERR! node -v v8.5.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
```

The new version of npm **reveals what the issue is**: `C:\Common7\IDE
\VC\VCTargets\Microsoft.Cpp.Default.props` omits the `Program Files (x86)\Microsoft Visual Studio 14.0` part of the path. Unfortunately, npm promptly cleans the `oniguruma` and I can't diagnose this further.

I looked at other issues that describe issues building vscode on windows, but couldn't find a good fix:

* As described in https://github.com/nodejs/node-gyp#on-windows I ran `npm install --global --production windows-build-tools` to no avail. 

* I also downloaded [Visual C++ Build Tools](http://landinghub.visualstudio.com/visual-cpp-build-tools) which didn't install, likely because I have VS 2017 (with C++ workflows and Windows SDKs installed)
![image](https://user-images.githubusercontent.com/1673956/30349642-7ae99242-97c8-11e7-9861-6bc151ed623a.png)

* I attempted to drop `vscode-textmate` into `node_modules` [as suggested here](https://github.com/Microsoft/vscode/issues/962#issuecomment-161628667) but this didn't fix the issue. Perhaps I used an incorrect version? 

My questions are:

* How do I build vscode on windows?
* Is there a workaround to ignore `oniguruma`, `textmate` or `fsevents`?

**Comment by alexandrudima** [comment]
@AmadeusW

Setting up `node-gyp` to work fine on Windows can sometimes be painful. Many times, I failed to do so myself.

Your problem is not vscode specific, it appears on your machine you cannot build any native node module... Perhaps Visual Studio is not installed completely, or something else is amiss, but I am not sure what that would be.

Anyways, I believe you have two possible paths forward:

### 1. Fix the Visual Studio or node-gyp installation such that you can build any native node module
The best place to find help with this is at https://github.com/nodejs/node-gyp . I, personally, on some VMs install Visual Studio, while on some VMs I do `npm install --global --production windows-build-tools`. i.e. I was successful with both options at https://github.com/nodejs/node-gyp#on-windows . I am not sure what could be going wrong on your machine.

### 2. Hack it
You can download the latest insiders version. Then you can copy all the `node_modules` in the latest insiders version over to your clone of the `vscode` repo. When running `scripts\npm install`, it should be the case that npm figures out you already have all those node modules and they will get skipped. This is a fast way to unblock oneself, but once things diverge you will need to repeat this operation ... again and again ... i.e. if someone from us bumps to use a new version of a specific node module, you will need to ... wait 1 day ... get the new insiders release, and copy those node modules out of there again.

**Comment by AmadeusW** [comment]
Thank you @alexandrudima 
Both your approaches sounded true but did not work due to state of my computer. There was just something about interactions of node-gyp and c++ toolkit that caused many errors.
I've got it to work in a VM, so I will close this issue.

**Comment by cleidigh** [comment]
@alexandrudima 
I was just setting up another VM and having typical set of problems despite setting up multiple others.
Happened to catch this.  Your detailed info and instructions were great !  Given how many issues
the Windows-build-tools solves perhaps it would be really helpful to add or point to this
in the main page build instructions. 

Thoughts?
