### ISSUE TITLE
更新完  查看定义和转到定义不能用了

### ISSUE THREAD

**Issue by shanyux** [Microsoft/vscode#34275]
- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:27:49.891Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
cpptools|ms-|0.12.4

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by alexandrudima** [comment]
Can you please provide clear steps for the problem ?

**Comment by hua03** [comment]
- VSCode Version:  1.16.0
- OS Version: Windows10
我的可以使用查看定义和转到定义。可能是你的快捷键冲突了，你可以通过以下方法看看你的快捷键是否被占用了：

1.暂时删除你自定义的快捷键，看看能不能查看定义
2.如果不行的话，把所有的扩展禁用试试

如果再不行，可能是更新的功能和你的系统有冲突。

**PS：下次报bug的时候请用英文，以便获得及时的反馈。**


I can use these functions to **go to declaration**  and  to **go to implementation**.May be your shortcut key conflict, you can use the following method to see if your shortcut is occupied：

1.Temporarily delete your custom shortcut keys to see whether this function is back to normal
2.If not, put all the extensions disabled

If it does not work, it may be that the updated feature is in conflict with your system. 

**PS：Please report in the next time in English, in order to get timely feedback.**

**Comment by ramya-rao-a** [comment]
@shanyux  Closing this issue as we haven't heard back from you in a while.

Follow the suggestion by @hua03 

If you still see issues, please add a comment here and re-open the issue
