### ISSUE TITLE
VERSION NEW ERROR AUTOMATIC OFFICIAL PROJECT

### ISSUE THREAD

**Issue by thandonguocmo2020** [Microsoft/vscode#34284]
- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:54:47.289Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
path-intellisense|chr|1.4.2
vue-peek|dar|1.0.2
sublime-babel-vscode|jos|0.2.8
vetur|oct|0.9.7
vscode-template-literal-editor|pli|0.8.4
vscode-icons|rob|7.12.0
vscode-react-native|vsm|0.4.1

(1 theme extensions excluded)

---

Steps to Reproduce:

1. RUN APP NODEJS  
2.  CHANGE APP RESET CODE BUILD 
3. ERROR AUTOMATIC OFFICIAL PROJECT

Reproduces without extensions: Yes/No

**Comment by alexandrudima** [comment]
@thandonguocmo2020 I'm sorry I don't understand what the issue is. Can you perhaps include more detailed steps and in some cases a screenshot might help. Are you launching and debugging a nodejs application? What do you mean when you say "CHANGE APP RESET CODE BUILD" or "ERROR AUTOMATIC OFFICIAL PROJECT" ?
