### ISSUE TITLE
Provide different settings for color picker and color preview (that square showing color)

### ISSUE THREAD

**Issue by ajitid** [microsoft/vscode#34341]
Right now in settings there is only one setting to toggle both color picker and that square which is shown at the left of the color. I found `vscode-colorize` better, which shows color behind the text and is better than a square which pops up everytime when it identifies a color. The problem is that I still want to use that in-built color picker, but as they are toggled with same setting I'm unable to do so.

**Comment by aeschli** [comment]
IMO colorDecorators should only affect the color boxes, but not the color picker.

**Comment by ajitid** [comment]
I agree. Color picker should get its own setting to toggle

**Comment by justablob** [comment]
+1

**Comment by CodyWalraven** [comment]
I would really like this feature as well, when using other extensions to show the color behind the text I would still like to be able to have the color picker available while leaving the default color decorator box hidden.

**Comment by luck2011** [comment]
Yes please stop change the color text.
We are not designers.

**Comment by TargiX** [comment]
Guys, almost 3 years you can't separate those 2 features, what's going on? Please separate settings for disable color decorators and color picker.  I believe that this is one day fix...

**Comment by joshuaptfan** [comment]
I would really like to be able to disable the color picker specifically.

Many times, while trying to select something else in CSS, I have accidentally moused over a color, then accidentally clicked in the color picker, and have to Ctrl+Z an unwanted color change that mangled my nice neat ```#F70``` into ```rgb(158, 116, 79)```.

**Comment by jzyrobert** [comment]
@rebornix This doesn't have the "help wanted" label but would you accept a PR?

**Comment by vintprox** [comment]
Just informing that this feature is dreaded, so @jzyrobert volunteered and made fork just for that. Color picker and decorator should not have been coupled in the first place.

**Comment by Drumstix42** [comment]
This would be a welcome feature split. I too use the Colorize extension, and would like to disable only the color square prefix, but retain the color picker hover feature.

**Comment by aiday-mar** [comment]
Hi thank you all for the feedback. Earlier this year we have added the command `Show or Focus Standalone Color Picker` which allows one to spawn the color picker anywhere in the file. From what I understood, the other request here is to disable the color decorators from spawning a color picker on interation with it? There is the new setting `editor.colorDecoratorsActivatedOn` which allows one to control under what circumstances the color picker is spawned. It takes as values `click`, `hover` or `clickAndHover`. You can use these two features in conjunction in order to control the behavior of the color picker. 

This issue will be closed in the meantime. If you have more feature requests or see bugs, feel free to open a new issue in the repo.
