### ISSUE TITLE
Improve preLaunch task error message and prompts

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#3437]
Testing #2940 

* I had one error detected with my `less` task, but the message used the plural "Errors". If we don't know if there are 1 or more errors, we can use the term "Error(s)"
* `prelaunch` is all lowercase but the name is really `preLaunch`
* I don't like the phrase "Debug Anyway" and "Close" says to me "close this message". I suggest change the options to "Continue" and "Stop", which are short for "Continue Debugging" and "Stop Debugging".

Message: **Error(s)** detected while running **preLaunch** task '*taskname*'.     

Prompts: **Continue** | **Stop**

**Comment by isidorn** [comment]
Well close is actually close this message, so I think that is good since we use that in all other messages. Continue debugging vs debug anyway was discussed by @weinand and me and we decided to use "debug anyway" which I prefer.
I will change prelaunch to preLaunch, and will change errors pluralirity

**Comment by chrisdias** [comment]
looks good!
