### ISSUE TITLE
Code does not support git submodules

### ISSUE THREAD

**Issue by SwintDC** [Microsoft/vscode#34390]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-jasmine-es5|dee|1.0.1
gitlens|eam|4.3.2
tslint|eg2|0.17.0
code-runner|for|0.6.28
Angular2|joh|2.4.0
typescript-hero|rbb|1.3.0
html-css-class-completion|Zig|1.8.0

---

Steps to Reproduce:

1. Create a git repo with a submodule
2. Open this git repo in Code
3. Add a change in the submodule and commit this change
4. Make sure you checkout this commit (of the submodule) in the parent repo
5. The parent repo should now contain a unstaged change with the new pointer to the new commit of the submodule
6. When you open this change in Code, a error message is shown in a popup notification

Reproduces without extensions: Yes/No

**Comment by SwintDC** [comment]
![image](https://user-images.githubusercontent.com/18047780/30437703-8e46a8e0-996f-11e7-9988-dda79b8a1142.png)

**Comment by yoyo837** [comment]
Track here #7829

**Comment by rmunn** [comment]
@yoyo837 - Please use the reactions icon (the "plus smileyface" symbol in the upper right corner of a Github issue) to add a :+1: symbol to issues, rather than posting a "+1" comment like you did on the #7829 comment thread. The reactions icon allows the MS maintainer team to sort issues by the number of :+1: reactions, while simply adding a "+1" comment does not help them. Also, adding a "+1" comment spams *everyone* who comments on the issue, sending them an email notification that contains absolutely nothing that they'll find useful. (And that is why I'm mentioning that *here*, rather than in the comment thread for #7829, because this way you'll see it but I won't spam the 25 people subscribed to that other thread).

**Comment by yoyo837** [comment]
@rmunn Ok, I got it. Thanks.
