### ISSUE TITLE
Prompting to install an extension after uninstalling extension

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#34404]
MacOS
Stable 1.16.0

Related to https://github.com/Microsoft/vscode/issues/33030#issuecomment-328021592

Open Chrome
browse to Marketplace.visualstudio.com
pick an extension, any extension
click on the "Install" button 
VS code should start (I have another issue to log were VS Code will not start...)
Click "Install" on the prompt to install the extension
Click on "Reload"
Uninstall the extension
Click on "Reload"

Result: You are prompted to install the extension again!

Click "Cancel"
F1 and then "Reload Window"

Result: You are prompted again to install the extension

![installbug](https://user-images.githubusercontent.com/1487073/30456058-fc4924d0-9956-11e7-92e1-4bd6228c415d.gif)

**Comment by chrisdias** [comment]
related issue where stable won't start when clicking "Install" from Marketplace: https://github.com/Microsoft/vscode/issues/34405

**Comment by v1adko** [comment]
Same thing on 1.16.1
In my case I see multiple prompts and only for those extensions that I've installed by opening a link on the Marketplace website and deleted them later.

**Comment by masonmark** [comment]
Yeah, until this is fixed, you should **never** use the Marketplace link to install an extension, unless you are completely sure that you want it installed forever. Because if you decide you don't want it and uninstall it, you will get this prompt over and over and over... AFAICT the only workaround currently is to leave the unwanted extension(s) installed. 

(I'm using macOS, VS Code Version 1.18.1 (1.18.1))

**Comment by sandy081** [comment]
@joaomoreno How can this be verified on insiders build?

**Comment by tsalinger** [comment]
@sandy081 You need to modify the link in the dev tools from href="**vscode**:extension/humao.rest-client" to  href="**vscode-insiders**:extension/humao.rest-client"
