### ISSUE TITLE
Cannot disable indenting when pressing Enter after a bracket

### ISSUE THREAD

**Issue by tlemo** [Microsoft/vscode#34414]
- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:19:37.192Z)
- OS Version: Linux x64 4.4.0-93-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.16.0
python|don|0.7.0
Go|luk|0.6.65
cpptools|ms-|0.12.4
perforce|sle|2.1.1
---

Steps to Reproduce:

1. set "editor.autoIndent": false
2. type { and hit ENTER -> next line is automatically indented

**Comment by alexandrudima** [comment]
I don't think we have any option turning that off.

**Comment by BillyONeal** [comment]
Possible duplicate of #32746

**Comment by alexandrudima** [comment]
I have changed the title to indicate that we should create a separate flag for this. `editor.autoIndent` controls a relatively new feature, that of using indentation rules as defined in the language configuration field `indentationRules`.

The OP desires to disable a behaviour we have had since day 1, that indentation is increased when pressing Enter after an opening bracket. e.g.:

![kapture 2017-10-21 at 12 09 13](https://user-images.githubusercontent.com/5047891/31850770-b16f47f4-b658-11e7-91f9-41529133c34f.gif)

This behaviour is much less problematic than using `indentationRules` (which have many cases where they would fail). I therefore suggest we consider this feature request, but with a different feature flag than `editor.autoIndent`.

**Comment by BillyONeal** [comment]
@alexandrudima It's possible the OP is thinking of the feature added relatively recently. The feature as it existed day 1 was fine; the problematic "I'm going to move existing braces around" behavior started in 1.15, the same release where the editor.autoIndent setting was added.

**Comment by alexandrudima** [comment]
@BillyONeal You are correct, it could be either one. 

@tlemo Can you please give a specific example (small code snippet would work), giving as details what happens vs what you would like to happen.

**Comment by tlemo** [comment]
Thanks for looking into this! 

#36148 is a bit more specific and hopefully it clarifies the distinction between the block indentation (which seems to be working as expected) and the interaction between editor.autoIndent and the "smart indentation" rules for C++.

If I understand the responses to #36148 is seems that editor.autoIndent = false is now honored (although there are still issues with the C++ specific indentation rules). So I'm going to close this one.
