### ISSUE TITLE
Editor ruler is offset by 1 column 

### ISSUE THREAD

**Issue by christoph-fricke** [Microsoft/vscode#34477]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
markdown-preview-github-styles|bie|0.0.3
python|don|0.7.0
php-debug|fel|1.11.1
php-intellisense|fel|1.5.1
php-pack|fel|1.0.1
beautify|Hoo|1.1.1
vscode-scss|mrm|0.6.2
vscode-icons|rob|7.12.0

(2 theme extensions excluded)

---

Steps to Reproduce:

1. Enable `editor.ruler` in the setting.
2. Place your cursor at the ruler.
3. Check the line/column information in the bottom right corner.

Example: When setting `editor.ruler` to 80 the information displays col: 81 after placing your cursor at the ruler in the editor. It is basically offset by 1.

I have the feeling that the ruler should be at line 80 and not line 81, since the description of the setting also says:  "Columns at which to show vertical rulers".

Reproduces without extensions: Yes

**Comment by alexandrudima** [comment]
@christoph-fricke 

The rulers are painted after the nth character. Typically, when folks want to use rulers to try to stick to a style guide, the style guide would say something like: "there should be at most 80 chars in a line". That's why configuring the rulers with 80 means that the ruler is painted at the location where 80 monospace characters would fit:

e.g.:

`"editor.rulers": [1, 10, 20, 40, 80]`:
![image](https://user-images.githubusercontent.com/5047891/30737143-da955752-9f85-11e7-85bb-be17a2fb14fb.png)

We can change the description for the ruler setting. But it is tricky to use "characters", as a tab character can take the size of N chars. The description uses column as that is the closest notion to what it tries to do.

I am open if you have suggestions for a better description that would reduce confusion.

**Comment by christoph-fricke** [comment]
@alexandrudima 

>The rulers are painted after the "nth character" (with the exception of tabs). Typically, when folks want to use rulers to try to stick to a style guide, the style guide would say something like: "there should be at most 80 chars in a line".

I have to admit that I want to use the ruler for exactly this but did not thought about it in this way. However it makes more sense and I agree with you that we should not change it.

Example for a description:
"Numbers of monospace character to fit between each vertical rulers and left border (tabs are counted as the set tab size). No rulers are drawn if array is empty."

A description like this might be less confusing and describes better how the rulers are drawn. It is a first craft and I am open to improvements.
