### ISSUE TITLE
When writing a custom debug adapter, variables are not shown on the test client

### ISSUE THREAD

**Issue by minggo** [Microsoft/vscode#3455]
I am writing a custom debug adapter, and sending result in `DebugSession.variablesRequest()` like this for testing:

```javascript
protected variablesRequest(response: DebugProtocol.VariablesResponse, args: DebugProtocol.VariablesArguments): void {

		let varialbes = [ new Variable('a', 'value') ];
		response.body = {
			variables: varialbes
		}
		this.sendResponse(response);
	}
```

But there is nothing shown on the test client
<img width="674" alt="screen shot 2016-02-25 at 9 30 28 pm" src="https://cloud.githubusercontent.com/assets/488203/13321007/8de1a75a-dc07-11e5-8fd6-a9606269ef5b.png">

I checked that, this function was invoked and returned correct value. I am not sure what's wrong.

My environment:

* vscode: Version 0.10.8
* mac os x: 10.11.2

**Comment by weinand** [comment]
@minggo implementing only a variablesRequest is not enough. You have to make sure that the whole chain works. Here is the explanation from the API doc:

![2016-02-25 14-51-18](https://cloud.githubusercontent.com/assets/1898161/13321457/5c993cb8-dbcf-11e5-95e9-e97d6c24a3d3.png)

This is the sequence of request that the debug UI will send:
- `stackTraceRequest`(threadId from stopped event) -> returns array of stack frames
- `scopesRequest`(id of top stack frame) -> returns the variable scopes for stack frame
- `variablesRequest`(id of top scope) -> returns the variables for that scope

**Comment by minggo** [comment]
@weinand 
Thanks.

I implemented all these requests, and stack frames are correct. 
Sorry, i didn't mention it for short.

The stack traces look like 
<img width="887" alt="screen shot 2016-02-25 at 10 07 12 pm" src="https://cloud.githubusercontent.com/assets/488203/13321804/324b6584-dc0c-11e5-9062-2df7492c1d19.png">

**Comment by weinand** [comment]
@minggo I see.
Ok, then what happens if you select the first Call Stack item ('ActionTest.js')?
Its scopes should show up in the Variables viewlet. Do they?
What scopes do you have?

**Comment by minggo** [comment]
@weinand 
Nothing changed when i selected first Call Stack item.

The scopes i returned is
```
{  
   "seq":0,
   "type":"response",
   "request_seq":8,
   "command":"scopes",
   "success":true,
   "body":{  
      "scopes":[  
         {  
            "name":"Local",
            "variablesReference":1000,
            "expensive":false
         }
      ]
   }
}
```

**Comment by weinand** [comment]
@minggo  the scope "Local" should appear in the Variables viewlet. Since it does not, then the problem starts already with Scopes...

Is `scopesRequest` being called when you select any of the stack frames? The arguments to `scopesRequest` should be the stack frame id.

**Comment by minggo** [comment]
@weinand 
`scopesRequest` is `only` invoked one time when first Call Stack item is selected. And i found that sometimes `scopesRequest` is invoked even no any Call Stack is selected, and sometimes, `scopesRequest` is not invoked even first Call Stack item is selected.

And it is strange that, sometimes there is a long delay `scopesRequest` is invoked.

**Comment by weinand** [comment]
@minggo the UI caches the results returned from all those requests because the VM is stopped and nothing can change. So `scopesRequest` is only called once for every stack frame. **But you have to make sure that every stack frame has a different ID!** Otherwise the UI assumes that all stack frames have the same scopes...

**Comment by minggo** [comment]
@weinand 
Yep, i used `Handlers.create()` to create a new id for every stack frame. 

I have a question, is it needed to selected a Stack Frame to trigger `scopesRequest `?

**Comment by harold-b** [comment]
Hi @minggo, got your ping from #3382. But I see @weinand is already helping you.
For what it's worth. I had a similar problem when I started my adapter, my issue was that I had forgotten to send out the initialize event.

Otherwise, you mentioned some slowness on the requests, after having the IDE open for a while and debugging several times the variables request seem to stop, they would then only be called when I hovered over a var on the text editor. I had to restart the IDE for it to start sending prompt requests as well.

> I have a question, is it needed to selected a Stack Frame to trigger scopesRequest?
AFAIK, the `threads > stackFrame > scopes > vars` request chain triggers on a stop event. You shouldn't have to select a stack frame.

**Comment by weinand** [comment]
@minggo it is not needed, but VS Code does it like this.
A scopesRequest needs to know for what frame it should return the scopes. So scopes are connected to frames. So the currently selected frame determines what scopes should appear in the Variables view.

**Comment by minggo** [comment]
@harold-b 
Thanks for you information. I haven't closed VSCode for a long time. May be i should restart it now.

@weinand 
Thanks for the answer. 
But i still don't know what to do to resolve it. There seems to have two bugs:

* When i click a Call Stack other from first Call Stack, `scopesRequest` is not invoked.
* Variables are not show on test client.

**Comment by minggo** [comment]
@harold-b 
@weinand 
After restarting VSCode, everything works fine. Thanks for your help.

@weinand 
May be it is a potential bug of VSCode.

**Comment by harold-b** [comment]
@minggo @weinand I suspect it's the same issue I reported on #3382, where the Variables view get's locked until the IDE is restarted. It often got locked with an empty view for me to, more specifically when I stopped debugging in the middle of a variablesRequest.

Glad it's working now :+1:

**Comment by weinand** [comment]
@minggo if you see issues with VS Code, just reload the window (F1, reload...). In most cases you don't have to restart VS Code.

If scopes (e.g. "Local") does not show up, then variables cannot work (because every variables lives in a scope). So you'll have to figure out what the problem with scopes is.

Compare your work with mock-debug. In mock-debug scopes and variables work. So there must be a difference in your code.

**Comment by minggo** [comment]
@weinand 
Thanks. I worked based on mock-debug, but now they are totally different, i just haven't changed the name.

@harold-b
Thanks.
