### ISSUE TITLE
to implement in vscode something like Atom-IDE

### ISSUE THREAD

**Issue by zero2000** [Microsoft/vscode#34551]
Hi, reading for the web I found something interesting like atom they will covertir from an editor to an ide by means of an extension. the idea is very good, since there is visual studio but vs code has a huge potential and could serve as a field of play to implement visual studio. and as I say the idea is very good. I do not expect the idea to be taken to do so already, but for a future it could be. since the term IDE does not have the complement that gives that functionality. but it should have an extension that these tools provide, an editor with a future

[http://blog.atom.io/2017/09/12/announcing-atom-ide.html](url)

https://user-images.githubusercontent.com/378023/29859731-741403be-8d9e-11e7-99c5-6b914e3fff9c.png

.

**Comment by welkie** [comment]
In my opinion, VS Code is already more like an IDE out of the box. It has the ability to run debuggers with extensions which are easy to add. I checked out ASP.NET Core on my Ubuntu laptop tonight and I had an ASP.NET Core MVC app running in less than an hour. I found it pretty intuitive and powerful.

**Comment by kasajian** [comment]
I agree with with welkie.  I think Visual Studio code has always been an IDE depending on your definition.   20 years ago, if asked what is the difference between an IDE and a text editor, the answer would have been, "well, with an IDE, you work with your entire project, not just one source file at a time, and you can do your editing, compiling and debugging all within the same environment."

**Comment by kasajian** [comment]
But what I think would make an IDE with today's definition, and what I would like to see for it get some exponentially larger adoption than it is now are two things.  Just two.

ONE:  And app-wizard, starter app built in.   Just like an extension, it should be able to create a starter app -- and such an app doesn't just give me the starting source code, but it configures my environment so that I can do debugging and REPL (if that make sense), build, and even package the final output, and it's obvious how to do all of that.

TWO: Discoverability of features.
    a) Too many commands are only reachable via the keyboard, so they are no way you can find it by clicking around with the mouse.  You have to go read a bunch of keyboard shortcuts to see what features the editor has.   Usually these keyboard short cuts lists are there to tell you what the keystroke is for the thing that you already know how to do, not the place where you present a particular feature to the user...  thus the description is usually too short.

   b. Too many things are configured only through json files instead of more user-friendly dialog boxes like in Visual Studio.   However, I'm not suggesting that to fix this we use dialog boxes instead of json.   I think json is fine -- we just need to do something about discovering them.   Sure an advantage of a dialog box is that it visually gives you an indicate of what the settings are, but another benefit is that you can go to Tools / Options or Edit / Preferences and find the one place where you have all the settings that are global your installation,   With Visual Studio code, the text based form in JSON is too chatty so it feels like you're zoomed into the settings and see too few of them on the screen at a time.  it's kind of like looking at a menu in a restaurant, bur through a magnifying glass so you only see 3 or 4 items at a time, and you have to hover the magnifying glass over the menu to see the rest of it.   There's no 10,000 view of all the settings in a summary form, the way you do with Visual Studio Tools / Options

It's should be clear which settings are:
1 - personal and part of a particular installation of Code, and not for a particular project.
       these should be roaming so that the user doesn't have to reconfigure every computer.
       for example, i keep my .vimrc in my .dotfiles under %userprofile% on windows, and ~./.dotfiles on OsX/Linux.

2.  Which are project specific and shared by the team.

3.  Which are project specific but not shared by the team.

4.  And while we're at it, I'd love to see non-project specific settings that can be shared by a team, for teams that want to standardize on corporate standards with certain extensions being required, etc.

thank you.

**Comment by mjbvz** [comment]
Yes I believe the VS Code already implements many of these features or can do so with extensions. Please open separate issues for any specific features you'd like to see better supported
