### ISSUE TITLE
Escaping Zen Mode doesn't work if Markdown preview active editor

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#34612]
- VSCode Version:1.15.1
- OS Version: macOS, Windows 10

Steps to Reproduce:

1.Bring up a Markdown Preview or Help > Release Notes
2.Go into Zen Mode with the Markdown preview editor open
3. Esc, Esc has not effect.

You have to manually close the Markdown preview at this point to get to another editor to return from Zen Mode.

**Comment by isidorn** [comment]
Markdown preview seems to be eating up the escape key.
Looking at the list of escape shortcuts my bet would be the `editor.action.webvieweditor.hideFind`

I would expect the hideFind action to be only available when findWidget gets visible
Due to the above assigning to @mattbierner

![screen shot 2017-09-19 at 10 07 42](https://user-images.githubusercontent.com/1926584/30581994-66bc8afe-9d22-11e7-8283-0d9016bf8a6f.png)

**Comment by mjbvz** [comment]
Yes, we need a new context key that tells when the webview find widget is visible. This is similar to what the terminal does with `KEYBINDING_CONTEXT_TERMINAL_FIND_WIDGET_VISIBLE`
