### ISSUE TITLE
Git manager tool with multi-workspace has some strange perform, is it a bug？

### ISSUE THREAD

**Issue by zhengxiaoyao0716** [Microsoft/vscode#34673]
- VSCode Version: Code 1.16.1 **[Unsupported]** (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:09.760Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-translate|chu|0.1.0
vscode-eslint|dba|1.3.1
python|don|0.7.0
tslint|eg2|1.0.7
Go|luk|0.6.65
java|red|0.10.0
background|sha|1.1.15
intelligence-change-case|zhe|1.1.0

---

Steps to Reproduce:

1. Open a multi-Workspace
![image](https://user-images.githubusercontent.com/12682063/30627180-4e61cde0-9e01-11e7-99b7-cd0eccc4e091.png)
![image](https://user-images.githubusercontent.com/12682063/30627184-59ba9ece-9e01-11e7-8777-121db90771cc.png)

2. Jump into a file, such as click on a function reference
![image](https://user-images.githubusercontent.com/12682063/30627205-70fa0c3c-9e01-11e7-8924-be95c02e0ee2.png)

3. Then you will see that the git repository for side-package has been join into the Git-Manager side  incorrectly.
![image](https://user-images.githubusercontent.com/12682063/30627309-de2c7772-9e01-11e7-9ec5-3b9efc4b106f.png)

Reproduces without extensions: Yes/No

**Comment by joaomoreno** [comment]
Why incorrectly? The file lives on a separate git repository, we're showing you that repository in the view. This seems correct to me.

The UX behind this has just changed in `master`, the experience won't be so bad as to make every view small: #33363

**Comment by zhengxiaoyao0716** [comment]
@joaomoreno Because those file is not belong to this workspace, and even not belong to me. I don't wan't to and also has no permission to manage other one's git repositories. 
I should never edit those files provide by side-packages, if I need to do that, I'll fork and pull them in my workspace, or join them to this multi-workspace manually.
What's more, I often open a lot of side-packages files to see the source code and doc, this caused the left git-tool side growing very large. Even if I close those files the repo still stay in it.

**Comment by zhengxiaoyao0716** [comment]
@joaomoreno I never see any editor performs like this, if you sure that reasonableness, we can discussion about that carefully, but please don't close this issue arbitrary

**Comment by zhengxiaoyao0716** [comment]
@joaomoreno at least, we should remove the repository of the side-package witch was already close, don't remain them in the git panel.

**Comment by zhengxiaoyao0716** [comment]
@joaomoreno I'm really like the vscode, and just want to make contribution to let it more better. But, I'm a little angry that you closed my issue, without any convincing discusion result.

**Comment by joaomoreno** [comment]
Notice that closing an issue doesn't mean that the discussion is over.

I didn't close your issue arbitrarily. We are doing the right thing because you have opened a file which lives in a git repository which Code still doesn't know about. You don't want this behaviour, but it's definitely the right behaviour for _most_ people. Nevertheless, I closed the issue deliberately since the management of multiple git repositories is now much simpler given #33363, even in your case.

Please give that a try by installing our latest insider release and let me know what you think.

**Comment by zhengxiaoyao0716** [comment]
@joaomoreno well, I'll take a try after for the insider release. However maybe I still cannot agree that add the side-packages repository into git panel in any form. For me, we should manually add the files which will be changed into the workspace unambiguous, otherwise should never edit them unsafety, let alone manage its repository.

Of cause this is not the final conclusion, I'll take a try and rethink for that. Whatever I hope that the new version should not looked so bat again:
![image](https://user-images.githubusercontent.com/12682063/30636702-cc8a35b4-9e28-11e7-88c9-ad1ece70a1aa.png)
![image](https://user-images.githubusercontent.com/12682063/30637047-dcace21a-9e29-11e7-9f4c-012a40f4bbb5.png)

**Comment by joaomoreno** [comment]
I see that in Go this is an issue, since the go tooling clones library dependencies to your machines, which appear as git repositories. We might think of having a setting to disable the automatic git repository discovery feature. Or a setting to define ignore patterns for git repository discovery.

---

Btw, we've done a lot of infrastructure work to make sure Chinese users have fast downloads. Is [this](https://go.microsoft.com/fwlink/?Linkid=852155) download slow for you? Where are you located? What does [this url](https://vscode-update.azurewebsites.net/api/geoip) show you?

**Comment by zhengxiaoyao0716** [comment]
@joaomoreno Thanks, I took a try, and it looks a bit better. If I could choise to disable it only for golang, I'll be appreciate.
![image](https://user-images.githubusercontent.com/12682063/30639916-70fe380c-9e33-11e7-872f-d1032150cf95.png)

As for the download speed, your words remind me that, my socks tool is always opening:
![image](https://user-images.githubusercontent.com/12682063/30641557-355eb27a-9e3a-11e7-8569-00d61c02738f.png)
and after I closed it the download speed became normal.
![image](https://user-images.githubusercontent.com/12682063/30641557-355eb27a-9e3a-11e7-8569-00d61c02738f.png)
