### ISSUE TITLE
"Start Without Debugging" doesn't work properly

### ISSUE THREAD

**Issue by fabiospampinato** [microsoft/vscode#34714]
I've tried to use the `Start Without Debugging` action to run a dummy javascript file, but I've found some, maybe related, issues: 

- After executing it the statusbar changes color to `statusBar.debuggingBackground`, implying that a debugging session has started, then right after the file has been run the statusbar goes back to its previous color, implying that the debugging session has terminated, but not `onDidTerminateDebugSession` nor `onDidChangeActiveDebugSession` get triggered, which instead imply that the debugging session hasn't been terminated yet.
- Terminating a `Start Without Debugging` session triggers `onDidChangeActiveDebugSession` but not `onDidTerminateDebugSession`.

PS. the whole "**Debug** -> Start **Without Debugging**" doesn't sound right.

Version: 1.16.1
OS: macOS 10.13

**Comment by isidorn** [comment]
I have pushed that the status bar does not go into orange once you do "Debug: start without debugging".

As for the events, it is expected that the noDebug session does no send a onDidTerminate event. However it is not expected that we send a onDidChangecActiveDebugSession. However I will not fix this, since that would require that I treat this no debug sessions specailly and that they are not reachable via API. Which I do not want to do.

As for the name, if you have a better suggestion please let us know

**Comment by fabiospampinato** [comment]
What about the `onDidStartDebugSession` event? I believe it and `onDidTerminateDebugSession` should behave consistently, currently `start` gets triggered but `terminate` doesn't.

Is there a way to detect if a debug session is actually debugging or just starting something?

**Comment by isidorn** [comment]
@weinand you could do some filtering on the API layer
Example here https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/electron-browser/mainThreadDebugService.ts#L28
Since the `debugService` emits a `newProcess` event which is correct in my world, however the api layer could decide if that event should be transfered into a `onDidStartDebugSession` event by looking at the `configuration` and if the `noDebug` flag is present. 

Due to this forwarding this issue to you

**Comment by connor4312** [comment]
It looks like "Start Without Debugging" now triggers the full set of session lifecycle hooks

![](https://memes.peet.io/img/20-11-1c399d50-ee6f-4bd2-b48b-389e80617313.png)

I think this is desirable (rather than omitting it) since a session is running, just with limited capabilities. The session configuration can be inspected for `noDebug` if an extension care about it.
