### ISSUE TITLE
Quick pick doesn't allow to define stable groups

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#34747]
Currently groups are defined by adding a separator to an item. However when the item gets filtered the group disappears. We should instead do the following:

- Have a special separator item
- Only filter the separator item if the group gets empty
- Don't render a border if the first item is a separator

**Comment by ThisIsManta** [comment]
@dbaeumer, would you kindly enlighten me how to add a separator to `items` in `showQuickPick`?

I'm referring to https://code.visualstudio.com/docs/extensionAPI/vscode-api#_window

**Comment by dbaeumer** [comment]
@jrieken can you please help @ThisIsManta .

The issue I made refers to our internal API.

**Comment by jrieken** [comment]
@ThisIsManta Using the API, you cannot

**Comment by ThisIsManta** [comment]
Thanks for the info. Making a public API would be nice.

**Comment by chrmarti** [comment]
The API request is tracked in #11468.

**Comment by chrmarti** [comment]
Status in the new QuickPick:
- Have a special separator item: Done.
- Only filter the separator item if the group gets empty: The separator disappears immediately when filtering because the ranking does not preserve groups. 
- Don't render a border if the first item is a separator: The border is automatically added except for the first one.

Closing as fixed.
