### ISSUE TITLE
[Feature Request] Allow bold-face for language keywords

### ISSUE THREAD

**Issue by vijaykrishna82** [Microsoft/vscode#34759]
Currently I cannot use **bold-face** for keywords in C# (for example)

**for** (**int** i=0;i<10;i++){
...
}

Here's the keyword highlighting with Tahoma font in Visual Studio:
![visualstudiokeywordhighlighting](https://user-images.githubusercontent.com/4973484/30702819-f9275ce4-9ebb-11e7-9d1b-f6ea203e9b7b.PNG)

Here's the same file when viewed in Visual Studio Code with Tahoma font:
![vscodekeywordhighlighting](https://user-images.githubusercontent.com/4973484/30702818-f927263e-9ebb-11e7-95c5-1869f7d8a75d.PNG)

I looked at settings and we can only customize colors for keywords, not boldface.

**Comment by Tyriar** [comment]
Themes can define bold/italics on different scopes, that is the only way to change the font weight right now.

**Comment by vijaykrishna82** [comment]
is there an example theme i can use?

**Comment by Tyriar** [comment]
@vijaykrishna82 turns out you can do this in your settings. First generate theme json from your current theme:

<img width="599" alt="screen shot 2017-09-28 at 8 31 00 pm" src="https://user-images.githubusercontent.com/2193314/30996082-03be5556-a48c-11e7-8287-bc9fb6f06b84.png">

Find the keyword textmate rule in the json and then add it to your settings but add fontStyle: bold like this:

```js
  "editor.tokenColorCustomizations": {
    "textMateRules": [
      {
        "name": "Markdown bold",
        "scope": "markup.bold",
        "settings": {
          "foreground": "#9fcff9",
          "fontStyle": "bold"
        }
      }
    ]
  }
```
