### ISSUE TITLE
allow running launch configs from the debug console

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#34752]
When no debug session is active, the debug console cannot be used for anything (and it prints a warning).
I suggest to allow some minimal commands in this mode. E.g. `debug` and `run`could be used to launch a launch config in debug or run mode.
If additional arguments are added, they would be passed to the launch config.

So for running a specific set of mocha tests, you could say:
```
run tests --grep api
```
"tests" is the name of a launch config.

**Comment by isidorn** [comment]
This makes sense and we could add it, however it would not be so discoverable.
On top of that we would have to support some "terminal" like fetaures in the debug console.
That the user gets completion for run and debug, we would have to parse the arguments and so on...

What I prefer and find more useful is that vscode could be run with a `-- debug tests` flag which would start debugging configuration tests. That would be more easily discoverable since we have other vscode command line arguments.
