### ISSUE TITLE
Properly handle remote content in binary editor viewer

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#34773]
Today when opening a binary file, such as an image, we don't actually open it but just create an image tag, like `<img src="file:///Users/jrieken/Code/_samples/ConsoleAppDnx/Screen%20Shot%202017-09-21%20at%2018.14.47.png">`

Now that we are adding remote files we cannot use that trick anymore. I can think of tmp-files or (when small enough) using data-uris but both have little appeal to me... Ideas anyone?

**Comment by bpasero** [comment]
@jrieken for now I suggest to add checks into [`ResourceViewer.show()`](https://github.com/Microsoft/vscode/blob/master/src/vs/base/browser/ui/resourceviewer/resourceViewer.ts#L114) to only do this when the URI scheme is `file` (this also includes to not show a link to open the file externally).

Maybe instead of that link we show another link asking to download the contents to a tmp file and inline it? I would probably not do this automatically without asking the user.

**Comment by bpasero** [comment]
Looks like this was fixed 11 months ago via https://github.com/Microsoft/vscode/issues/49278 😮
