### ISSUE TITLE
Allow to open remote resources without the need for workspace file (e.g. command line)

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#34770]
* start from command line and provide a uri, `./scripts/code.sh ftp://server/path`
* the uri is appended to the cwd

<img width="2126" alt="screen shot 2017-09-21 at 18 14 47" src="https://user-images.githubusercontent.com/1794099/30706541-f32bf48e-9ef8-11e7-84f1-dbc215156361.png">

**Comment by jrieken** [comment]
fyi @dlebu

**Comment by bpasero** [comment]
Today we assume that whatever gets opened from the command line is a file path. I think in this case what we could do is create a workspace on the fly and add the URI as only folder. We already do this when you want to open multiple folders from the command line at once.

**Comment by jrieken** [comment]
This isn't only about folders but also files

**Comment by bpasero** [comment]
One challenge is, that on startup we need to know if the "thing" to open is a file or folder to set the right context (empty workspace vs. folder workspace). How would you suggest to find out about that given a URI like `ftp://server/path`?

Another challenge is that if we support to open a remote folder, we need to make sure that the workspace service is using the file service for reading the folder's configuration. Currently the file service is created a lot later and instead direct disk access is [being used](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/configuration/node/configurationService.ts#L334) for the single folder configuration service. We would probably also see a slowdown in startup performance because the workbench is waiting for the configuration service to resolve the folder's configuration before starting to show up.

**Comment by jrieken** [comment]
> We would probably also see a slowdown in startup performance because the workbench is waiting for the configuration service to resolve the folder's configuration before starting to load.

Not sure but most settings can change at runtime, correct? So my thinking goes like not supporting those the 1% settings that require a restart and to start with reasonable default which change once the remote files/folders are resolved. That would prevent the blocking.

> How would you suggest to find out about that given a URI like ftp://server/path?

If we can't figure it out we can let the user decide that. So, when having just a path we try to open it as a file. If you want a path to be a folder, it would required a special flag, like `code --folder foo:/bar/path` etc, etc.

**Comment by eamodio** [comment]
I would love to have this as well for RemoteHub, without this support it looks like the only other option is creating a `.code-workspace` folder which is far from ideal imo.

**Comment by jrieken** [comment]
This is now possible that to @aeschli and @sandy081

**Comment by eamodio** [comment]
Is this only enabled on the command-line or is there an api for extensions to do it?

**Comment by jrieken** [comment]
The `vscode.openFolder`-command should do this, the cmd-line option is `--folder-uri`
