### ISSUE TITLE
Rely on UUIDs for extension identification

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#34812]
Extension identification is essential to the update mechanism. It is through an identifier that we're able to match several extension versions against one another.

We are currently using the `publisher.name` tuple as an identifier. This is very beneficial in some scenarios such as VSIX side-loading, in which updates would still work seamlessly.

The Marketplace team intends to provide publisher/extension renames. This will break our assumptions that the `publisher.name` tuple is valid during its entire lifecycle. So we must only rely on the marketplace UUID returned from the Marketplace, which will stay consistent in renaming situations.

This needs to be adopted in a few places:

- We should store the marketplace UUID into the extension's manifest, as soon as we are aware of it. Installing extensions from the Marketplace should immediately store that UUID.
- Internally, extension matching should always be based on UUID. This should be the stored marketplace UUID or, in case it is nonexistent, the tuple `publisher.name`.
- Our outdated mechanism currently prevents the loading of and deletes older versions of an extension, if multiple versions are installed into the user's extensions folder.
- At startup, whenever an installed extension is found without UUID, we should attempt to match it against a marketplace extension and, if matched, store that UUID.
- At VSIX installation time, we should attempt to match the extension against a marketplace extension and, if installed and matched, store that UUID.

cc @sandy081

**Comment by jens1o** [comment]
Maybe then you can implement that an extension can be renamed. @Binarify had that problem.

**Comment by Binaryify** [comment]
@jens1o 
you are awesome!

**Comment by seanmcbreen** [comment]
Adding a few more items (so I don't forget)

- any related recommendations should be updated as soon as feasible e.g. we should use the `UUID` for these not `publisher.name`
- any place on the website where we have a curated list will also need to be updated
- we should also check for any links we have in the docs
- the welcome page has a few extensions in there we need to also update those
- `ActivatePlugin`, 'ext:install', 'ext:update', 'ext:delete' should also include UUID

Sean

**Comment by sandy081** [comment]
- Market place extensions and Installed extensions has a combined identifier called `IExtensionIdentifier` that contains `UUID` provided by Market place and `id` that is `pub.name`. 

- An Extensions identity function to compare two `IExtensionIdentifer`s. They are called same if both have UUIDs and are same or both ids are same.

- Market place extensions will have both `UUID` and `id` whereas Installed extension has `id` and might have `UUID` (An extension installed from Market place will have UUID but a VSIX installed extension will not have).

- An Installed extension is mapped to a Market place extension primarily by its UUID if exist, otherwise by `pub.name`. 

- Extension enablement deals with only `IExtensionIdentfier`. Its storage is migrated from `pub.name` to `IExtensionIdentifer`. 

- Run time extensions also contain `UUID` and `id` similar to `IExtensionIdentifier` and can be used in the extension identity function.

## Test cases

### Extensions Installed from Marketplace

An extension is installed from Marketplace and 

1. syncs with Marketplace and has no updates
2. syncs with Marketplace and has a normal update
3. syncs with Marketplace and has a rename
4. syncs with Marketplace and has a rename and update

### VSIX Extensions

An extension is installed through VSIX and

1. syncs with Marketplace and has no updates
2. syncs with Marketplace and has a normal update
3. does not sync with Marketplace that has a rename
4. does not sync with Marketplace

### Update

1. Update an extension when an update available and not renamed.
2. Update an extension that is renamed and an update is available.

### Enablement / Disablement

1. An extension that was disabled and is not renamed
2. An extension that was disabled and got renamed

**Comment by shanalikhan** [comment]
and "settings sync" extension is broken for insiders with this change 😄 
https://github.com/shanalikhan/code-settings-sync/issues/428

**Comment by sandy081** [comment]
@shanalikhan Not sure if I understand, Can you explain how does this change broke your extension?
