### ISSUE TITLE
Problem pasting JSON that was indented 2 spaces

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/vscode#34846]
- VSCode Version: Code - Insiders 1.17.0-insider (f7962f0682a76516df51de4856f8ccc5d8ad578a, 2017-09-20T05:24:33.599Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: none
---

Steps to Reproduce:

1. Create a new file `foo.json`.
2. Convert indentation to tabs. Use the default `"editor.tabSize"` of 4. You should see `Tab Size: 4` in the bottom-right.
3. Paste this code:
```json
{
  "a": {
    "b": true
  }
}
```

You get:
```json
{
	"a": {
	  "b": true
	}
  }
```

4. Delete everything, convert indentation to spaces, and paste again. You get:
```json
{
    "a": {
      "b": true
    }
  }
```

**Comment by alexandrudima** [comment]
@andy-ms This is caused by the language agnostic `"editor.autoIndent"` that is set to true by default. 

One workaround is to configure:
```
"editor.formatOnPaste": true
```
At least for JSON, the language server will kick in and do correct formatting on paste. Alternatively, `editor.autoIndent` can be turned off to prevent the language agnostic auto-indenter to kick in. I think it is currently implemented to *maintain* the relative indentation of pasted lines, while adjusting them in the context of the paste.

**Comment by rebornix** [comment]
This shares the same root cause as https://github.com/Microsoft/vscode/issues/29589, let's track it there.
