### ISSUE TITLE
EOL User Setting should be able to be set per language or file type.

### ISSUE THREAD

**Issue by Everspace** [microsoft/vscode#34876]
- VSCode Version: 1.16.1
- OS Version: Win 10

Steps to Reproduce:

1. Use the following User Settings:
```
{
    "[shellscript]": {
        "files.eol": "\n", //Unknown Identifier. Use language identifiers
        "files.encoding": "utf8bom" //Unknown Identifier. Use language identifiers
    }
}
```

Reproduces without extensions: Yes

`files.encoding` and `files.eol` should be able to be set per language, much like `files.trimTrailingWhitespace` or `files.insertFinalNewline` are able to be.

On my windows machine, I edit bash scripts and the like that I use on WSL, and subsiquently `ssh` and `scp` around to actual Linux boxes. This causes some annoyances to say the least as WSL handles both but the actual systems do not.

The availability of `files.encoding` would be handy if you're editing something that can only be in ISO format like very old Python files for something like a sanity check. I've also worked with files from old game engines or the like that only take ISO as well, but still want to generally be using utf8.

**Comment by bpasero** [comment]
files.encoding is a per-language setting with our upcoming 1.17 release. I think `files.eol` is not and there may be a chicken-egg problem because we use this setting [when the model is created](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/services/modelServiceImpl.ts#L271) and there we just have `plaintext` as language.

**Comment by bialix** [comment]
+1 on setting files.eol per file type.

**Comment by uberjew666** [comment]
+1
