### ISSUE TITLE
VSCode 16.1 is not published in yum repository

### ISSUE THREAD

**Issue by rohel01** [Microsoft/vscode#34885]
- VSCode Version: Code 1.16.0  787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:19:37.192Z 
- OS Version: Linux x64 4.12.13-300.fc26.x86_64
- Extensions:  Extension|Author  truncated |Version -|-|- better-toml|bun|0.3.0 python|don|0.7.0 plantuml|jeb|2.2.2 cpptools|ms-|0.12.4 vscode-code-outline|pat|0.0.10 rust|rus|0.2.2 vscode-lldb|vad|0.6.2
- Steps to Reproduce:  
  1. sudo dnf update
Reproduces without extensions: Yes

**Comment by waltton** [comment]
I use vscode in fedora and some delay is common, but the 16.1 version is taking too long.

**Comment by Tyriar** [comment]
We had a lot of issues with releasing the rpm this release due to 2 key team members being out. The rpm was published to the repo yesterday https://packages.microsoft.com/yumrepos/vscode/

Good news: I'm currently at Ubuntu Rally working on snapcraft support which should improve the install/update story.
