### ISSUE TITLE
Data loss when disk is full

### ISSUE THREAD

**Issue by elohr** [microsoft/vscode#34915]
If saving a file fails because there is no disk space left not only the changes are not saved (which would be expected), but the original file is replaced with an empty one, loosing any previous contents which were already on disk.

- VSCode Version: 1.16.1
- OS Version: OS X (10.11.5)

Steps to Reproduce:
1. Open existing file
2. Update file
3. (run out of disk space)
4. Try to save file (it will fail)
5. Re open file, it will be empty.

Reproduces without extensions: Yes

**Comment by unparagoned** [comment]
I have a similar problem. I'm using a samba network drive with lots of space but it sounds like if there is any problems with "writing" a file due to space or network connectivity issues. VSCode then decides to write a blank file with great success. And tries quite hard to get me to throw away my working version since there is a newer file on disk. 

```
messageService.ts:126 Failed to save 'spotify.py': A system error occurred (ENOTSUP: operation not supported on socket, write)
e.doShow @ messageService.ts:126
2messageService.ts:126 Failed to save 'spotify.py': The content on disk is newer. Click on **Compare** to compare your version with the one on disk.
e.doShow @ messageService.ts:126
```

**Comment by bpasero** [comment]
**Explanation:** this is not actually a data-loss situation in the sense that the dirty buffer gets empty, but rather the file on disk gets truncated first before we write and then fail to write. The flow is:
* user types into file
* file is dirty
* at this point exit will fail with an error message that there is not enough space to backup
* user saves
* we leverage node.js file writing methods that first truncate the file
* we try to write
* this fails due to ENOSPC

=> at this point the file is basically empty because we have no way to restore the previous contents

**Comment by unparagoned** [comment]
So on ENOSPC error, could it just try again with overwrite enabled if file on disk is empty?

Or can save files be implemented like save to filename.ext~. If ok copy over filename.ext. If error no big deal you haven't delete the main file through some strange nodejs dependency.

I know these solutions aren't great but anything is better than the current behaviour

**Comment by ArkadiuszNiemiec** [comment]
Same problem here but I am working on files mounted by sftp.

**Comment by liganghui** [comment]
My 400 code is lost for this reason, heartache . 

I suggest you install the "Local History" extension to avoid this problem.

**Comment by Tyriar** [comment]
I just hit this and lost 1/2 the file I was working on.

**Comment by Maxou44** [comment]
Any news about this issue?

**Comment by baslr** [comment]
Its not only that user files are affected, but also VSC settings.

On macOS, I had 1.42.x open and disk was full. I tried to quit VSC. Nothing happened. I tried again to quit VSC. VSC eventually quit. But after opening I no workspaces were restored.
After the update to 1.43.0 VSC thankfully opened workspaces with unsaved files.

**Comment by bpasero** [comment]
A somewhat related case is https://github.com/microsoft/vscode/issues/97768. When you save a file while it is not dirty, we write the entire contents into it and a crash can turn the file empty. The underlying source of trouble is again the fact that every write truncates the file first and a crash after the truncate will leave the file empty.

**Comment by bpasero** [comment]
With https://github.com/microsoft/vscode/commit/0c3017c62e455271683df8ad2b2d4d328c68beec pushed I am quite confident that the original issue reported has been fixed and especially @Tyriar scenario. There are 2 scenarios to look at:

**1. the file is dirty and being saved**
This is the typical case of the user making changes and eventually saving these changes back to disk. If the disk is full and the user makes an attempt to save the file, there is a chance that the file ends up being empty (truncated). However, the error will bubble up to VSCode and the file will remain dirty. As such, you cannot close VSCode unless you persist the changes. E.g. you get this dialog on close:

![image](https://user-images.githubusercontent.com/900690/82190964-21839300-98f2-11ea-859e-154a299d6f6c.png)

**2. the file is not dirty but still being saved** 
This was the case that still had a bug: we allow you to save an editor, even if it is not dirty. In that case we simply write all of the contents to the file again (helps to e.g. trigger external file watchers). However, in case of the disk being full, the file would end up empty and the editor would reflect that (e.g. all contents gone). If you did not make a backup of the contents, those contents were lost. With https://github.com/microsoft/vscode/commit/0c3017c62e455271683df8ad2b2d4d328c68beec we now automatically mark the editor as dirty in case of an error so that the contents are preserved and not replaced with the empty file. 

To test running out of disk space I used a USB drive and ran VSCode with `--user-data-dir` to that drive as well as opening a folder there. I then filled the drive all the way up to have no space left. I cannot reproduce data loss in this case so I am optimistic that this issue can be closed.

I extracted https://github.com/microsoft/vscode/issues/98063 which would be the solution to https://github.com/microsoft/vscode/issues/34915#issuecomment-629083147 and to prevent truncate in general, but I am not so optimistic we can enable such a solution by default.

**Comment by bpasero** [comment]
Setting "needs more info" to ask folks on this issue to possibly verify these scenarios or give further input on cases I might have forgotten.
