### ISSUE TITLE
Keep "find" and "search" in sync

### ISSUE THREAD

**Issue by cdeutsch** [Microsoft/vscode#34970]
- VSCode Version: 1.16.1 (1.16.1)
- OS Version: OS X

Steps to Reproduce:

1. cmd+shift+f to do a global search (type in something that will occur multiple times in a file)
2. Click into a result to open the file
3. cmd+g to "find next" and it doesn't work because "find" is independent of "search"

Reproduces without extensions: Yes

Other editors like Sublime Text keep these values in sync (because they re-use the same UI). It'd be amazing if there was a way to accomplish this even if via an extension. 
If an extension is possible I can look into it. (not familiar with the APIs yet)

**Comment by roblourens** [comment]
In VS Code they are distinct features and UI concepts, but there are keyboard shortcuts to accomplish this, try F4/Shift+F4.

You can even set it up to use the same keyboard shortcuts for both. You can register something to go to the next find result with `"when": "findWidgetVisible"`, and go to the next search result otherwise.
