### ISSUE TITLE
After update VSCode can't use Git and won't launch Chrome

### ISSUE THREAD

**Issue by thatcort** [Microsoft/vscode#34998]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.3.2
prettier-vscode|esb|0.23.1
debugger-for-chrome|msj|3.3.0
java|red|0.10.0

---

Steps to Reproduce:

1. Edit file checked into git repo
2. Go to source control view
3: Read error message "There are no source controls active"

Reproduces without extensions: Yes/No

**Comment by joaomoreno** [comment]
Where is git installed in your system?

**Comment by thatcort** [comment]
C\Program Files\Git

**Comment by george-norris-salesforce** [comment]
Having same prob. I have git installed.

**Comment by thatcort** [comment]
It seems to have miraculously started working again today.

**Comment by danielnieto** [comment]
I had this issue with Mac, it turns out that my XCode updated and I needed to agree to the new user license to be able to use git. To agree it, you have to open a terminal and type "git" and then it will ask you yo follow few steps to do so, after doing that, you can restart vscode and it will work again
