### ISSUE TITLE
Variable highlight looks broken in dark theme

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#3502]
- Dark+ theme, have a multiple references of a variable in a .js / .ts file.
- Select that variable
- Notice that the variable highlight is stronger then the selection
- So it can easily be confused that the change location of the variable is selected

Nice example: vscode express smoke test / bin/www  double click on `server` on line 28

![screen shot 2016-02-26 at 16 28 22](https://cloud.githubusercontent.com/assets/1926584/13356530/fe3288dc-dca5-11e5-8d70-b827c1a673c5.png)

**Comment by bgashler1** [comment]
Agreed this needs to be fixed.  I'm going to be modifying some other colors related to other issues, and will be sure to address this.

Is there any reason why we had the variable highlight be blue?  The only reason why I can think of is that it is a strong color that stands out.  When a user wants to know where a variable was defined, this could be useful.

Perhaps for the variable highlight we could use an outline, so that it's a strong visual indicator but is not confused as being a selection highlight (see below).  What do you think?

![untitled-2](https://cloud.githubusercontent.com/assets/11839736/14162378/4077d81e-f6a0-11e5-90c0-32a22563b961.png)

**Comment by isidorn** [comment]
Not sure what was the reason for the original color.
I think it looks good, however it is hard to give feedback without first trying it out. I think this is one of those things where we have to just try it out. People will notice immediatly and you will get feedback.

**Comment by misolori** [comment]
Closing this for housekeeping and since we haven't seen other requests for this. Feel free to re-open if you disagree.
