### ISSUE TITLE
gray'ish workspace folders

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#35075]
#34775

* on mac
* have a workspace with a few folders
* open the workspace file and change the path of a few folder to non existing files/folders
* 🐛 the folders show gray'ish, I'd expect them to disappear, optionally to see a squiggle in the config file

<img width="1032" alt="screen shot 2017-09-26 at 12 47 36" src="https://user-images.githubusercontent.com/1794099/30856512-e4010e86-a2b8-11e7-94f2-721abfff1eff.png">

**Comment by bpasero** [comment]
-1 for not showing the folder because there is still a valid action to remove the workspace folder from the explorer. 

As for the warning in the workspace file, yes that would be a nice validation.

**Comment by isidorn** [comment]
For the hint I could provide a hover message. Any other suggestions?
Also assigning @sandy081 for workspace file validation

**Comment by bpasero** [comment]
Maybe the folder could have 1 child with a warning icon to indicate the folder could not be found? Or we could add something to the right of the folder label in smaller font?

**Comment by sandy081** [comment]
@isidorn What kind of validation do we need for workspace file?

**Comment by isidorn** [comment]
@sandy081 I believe Joh would like the workspace file to have some green squigles if the file path is wrong - you can see more in the top comment

**Comment by isidorn** [comment]
@jrieken next to the grayed out label I will put the warning icon using the `IResourceDecoarationService`, I will register my decoration provider which provides decoration only for unresolved roots.
As for the squigles in the config file I have created a seperate issue https://github.com/Microsoft/vscode/issues/36079

**Comment by bpasero** [comment]
@isidorn due to https://github.com/Microsoft/vscode/issues/35092 would you also handle the case of having a file set as workspace folder? I guess any kind of error situation should cause the decoration to show up.

We still have to decide if a file should end up in the workspace service API at all though.

**Comment by isidorn** [comment]
@bpasero yeah it being grayed out + warning decoariont also works for that case. I guess I could only give a different hover message

**Comment by isidorn** [comment]
I consider this state a warning since a user can continue working thus I am coloring using a warning orange color. I tried using the warning unicode character but it is too small, thus I ended up using a simple explamation mark. Here's the result

![screen shot 2017-10-27 at 12 49 25](https://user-images.githubusercontent.com/1926584/32100750-4a42f4f6-bb15-11e7-9aa1-3ab215620e14.png)
