### ISSUE TITLE
Tasks: show task log action should take terminal into account

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#35071]
Refs: #34953

We have a Tasks: show task log which always opens the output. However this can be wrong if my tasks are running in the terminal.

We should either remove this action and only use "Show running tasks", or make this action smarter that it opens the terminal if no task is appending output to the output channel

**Comment by dbaeumer** [comment]
Actually they both serve a purpose and I didn't remove the "Show Task Log" since even in the terminal case the task parse write interesting error messages into the task output channel. Considering that terminal is the default for the future I still think that keeping both does makes sense.

I will close the issue. Please ping if you disagree.

**Comment by isidorn** [comment]
Not sure if renaming the action would make it more clear
"Show Task Output"
"Show Task Output Log"

This way there shuold be some connection between name and output pane.
Just a suggestion
