### ISSUE TITLE
Bad UI for workspace folder that is actually a file

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#35092]
#34775

* have a workspace config file
* add the path of a file
* 🐛 the explorer shows it but it doesn't look nice
* ❓ unsure if should support files as workspace folder, not sure that folks expect that to happen?

<img width="1090" alt="screen shot 2017-09-26 at 14 08 52" src="https://user-images.githubusercontent.com/1794099/30859543-7665b47e-a2c4-11e7-8cff-3c83e6994e9c.png">

**Comment by bpasero** [comment]
We have a feature request open to support files in the workspace config: https://github.com/Microsoft/vscode/issues/31652

I think we should probably on the workspace service level already filter out entries which are files. But we have to be careful to not remove entries which are simply not found because I think it is still valuable to see an entry in the explorer as grey that currently cannot be loaded. Adding @sandy081

**Comment by jrieken** [comment]
> We have a feature request open to support files in the workspace config: #31652

Is that something we should prepare extension authors for? We have a type called `WorkspaceFolder` which doesn't fit well onto files...

**Comment by bpasero** [comment]
@jrieken yeah I was not suggesting to support this scenario, I am not thinking there is a lot of use cases for it. You can always open individual files as tabs if they are outside of the workspace to leave them around. I think there should be other ways to keep such files in the workspace, like being able to "pin" a tab so that it does not close too easily.

**Comment by sandy081** [comment]
If I remember our old discussions about MR workspace, we discussed about supporting `files` but obviously not in `folders` section but in a separate section called `files`. But do we need to expose them in extension host? They could be similar to other documents except they do not have any workspace folder

**Comment by isidorn** [comment]
Now I show the same decoration as for a root that has a bad path.
Note that I do not distguish these two cases, the tooltip simply says
"Can not resolve workspace folder"

**Comment by bpasero** [comment]
@isidorn when I add a new path entry that is a file the decoration does not show up yet though, only after a reload:

![image](https://user-images.githubusercontent.com/900690/32336067-9621070e-bfee-11e7-9d73-d34d28cabea5.png)

Also I am not 100% sure about showing this entry as an actual file that you can click. This will probably cause people to believe that we support having files as workspace folders. We should not encourage that. Can we show the entry as folder so that clicking does not open the file and the entry looks good compared to the other entries?

**Comment by isidorn** [comment]
@bpasero for me it shows up imediatly in orange, is there some special way how you are adding it? I simply add it to the .code-workspace file and it is immediatly orange
Maybe we could show it as a folder, I can look into it

**Comment by bpasero** [comment]
@isidorn weird, does not reproduce for me at all times. anyway, the handling of that thing as folder would be nice.

**Comment by myfairsyer** [comment]
I'm the author of the related FR.
Did you decide not to support loose files in workspaces?
Also: You seem to continue the discussion about that here, so #31652 as an issue is probably obsolete now, right?

**Comment by bpasero** [comment]
@myfairsyer we have no plans to support loose files in workspaces.

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/46014
