### ISSUE TITLE
Adding folder to single folder workspace collapses the first folder

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#35121]
Testing: https://github.com/Microsoft/vscode/issues/31195

Steps to Reproduce:

1. start with single-folder workspace
2. do not expand anything (the folder is expanded already)
3. add another folder

=> the first folder shows as collapsed

![flicker_chrome58](https://user-images.githubusercontent.com/900690/30863222-cbcc85d0-a2d0-11e7-8a86-ebd57ac21ab2.gif)

**Comment by isidorn** [comment]
@bpasero For this to be fixed please send me the original folder as being added in [`IWorkspaceFolderChangeEvent`](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/workspace/common/workspace.ts#L26)

And I think this is also intuitivly correct since the first folder is also being added to a brand new workspace.

**Comment by bpasero** [comment]
@sandy081 any objections to adding the single-folder to the `IWorkspaceFolderChangeEvent` as `added`?

**Comment by sandy081** [comment]
@isidorn Would like to understand why the first folder state is lost when the event says just a folder is added. Is it different when we add a folder to the workspace?

**Comment by isidorn** [comment]
@sandy081 yeah it is different since the whole state of the workbench changes. Now we are entering a workspace mode and all the folders are practically new. Techinically underneath the exlporer input changes to show the root folders.
Compared to we are already in workspace mode and only one folder is added.

**Comment by bpasero** [comment]
@isidorn can't you handle the workbench state change in a way that all root folders just become expanded?

**Comment by isidorn** [comment]
@bpasero probably but that will require me to handle that case specially which might be ugly on my side. 
I still think that it is intuitive that this event has all the folders in case the whole workbench changed. Currently are there any other clients who are listening on this event and expending workspaces changes?

**Comment by bpasero** [comment]
Yeah quite some, though I do not think anyone cannot handle this case.

**Comment by sandy081** [comment]
I do not think including the first folder is right solution here. It changes the semantics of the event. I think this should handled as if a new folder is added and retaining the state of the existing folder.

**Comment by bpasero** [comment]
@isidorn yeah, agree, talked with @sandy081 a bit about the issue, I think having the current folder as part of the event actually does not help you much because in your case not only should the current folder stay expanded, you also need to retain all the expanded folders. So I think in this case you will need to store the current state of the folder and restore it, including the expansion of the root node.

Btw not sure this needs fixing for September.

**Comment by isidorn** [comment]
If you both think this should be handled on the explorer side assign the issue to me and october

**Comment by isidorn** [comment]
Ok just now got your comment, assigning to me and october
