### ISSUE TITLE
quick pick fails on umlaut

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#35125]
* have a workspace called 'wörkspace', use it
* open an new window, hit `Cmd+R` for the list of recent workspaces
* type `wö`
* 🐛 the 'wörkspace'-workspace is removed from the list which is false

![sep-26-2017 15-44-27](https://user-images.githubusercontent.com/1794099/30863964-a30e0798-a2d2-11e7-85a6-47d9f7c04fc6.gif)

**Comment by bpasero** [comment]
@jrieken good catch, this is another variant of the unicode normalization issue on macOS: the OS will return umlauts as 2 unicode characters (`o` and `:`) whereas you as a user type it as one character `ö`. We already have code [here](https://github.com/Microsoft/vscode/blob/master/src/vs/base/node/extfs.ts#L22) to normalize when we receive paths from the OS which typically only happens when using `fs.readdir`.  

I missed to add this to the native Electron file dialogs (namely `showOpenDialog` and `showSaveDialog`) and added it. 

Since we put some of the paths for workspaces in a JSON file, they will still have the wrong form so to verify please try with a new workspace. I do not think it would make sense to migrate existing workspaces to NFC form given this feature has not yet hit stable.

**Comment by jrieken** [comment]
I still see this with `5d79ec8e56843b6b540a997fd1263a2ceb13d0d2`

**Comment by bpasero** [comment]
@jrieken from the gif it looks as if you are able to type "o" followed by ":", are you intentionally triggering this version of the umlaut or is this coming in via normal typing?

**Comment by jrieken** [comment]
Well, I have a US-keyboard, so I need to type <kbd>Alt+u</kbd> and <kbd>o</kbd> for an ö. However,  when I paste `Wö` into the input-field the same happens

**Comment by bpasero** [comment]
@jrieken was this a workspace you maybe added before my fix, which would indicate that the name contains the decomposed form (`o` + `:`). To make sure that is not the case, can you:
* remove the entry from the recent list
* open it again via File > Open Workspace
* in the recently opened make sure to type the `ö` as single character e.g. via copy paste, see if that works
* and then once again try with typing it in the decomposed form (`o` + `:`)

I would actually expect the first one to find it and the second to not find it. To be fair I would have never expected the second form to find it, even in stable because we are not doing any normalisation in the picker. And frankly speaking, there may be many more places where this hits us.

**Comment by jrieken** [comment]
Yeah, that did it.

**Comment by bpasero** [comment]
@jrieken ok, does it also find it when you type `ö` via your <kbd>Alt+u</kbd> and <kbd>o</kbd>?

**Comment by jrieken** [comment]
Yeah, I guess the history has the old format stored and doesn't normalise what it reads. But I'd say that is fair enough

**Comment by bpasero** [comment]
@jrieken yeah exactly, I did not bother doing a migration of that old format. Closing then as it seems ok once the new format is used.
