### ISSUE TITLE
showOpenDialog: improve spec of 'openFiles' and 'openFolders'

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#35141]
Testing #34821, Linux

- What's the default of 'openFolders' and 'openFiles'? Naturally, it would be 'false', but both false doesn't make sense to have as default for the OpenDialogOptions
- The spec says: `openFiles: *Only* allow to select files`. What does it mean if also openFolders is true?
- The spec says:  `*Note* that not all operating systems support to select files and folders in one dialog instance`. How would API users know if they now can use files and folders together?

Suggestions:
- a single property: resourceTypes: FILES | FOLDERS | ANY,  default: ANY
- a API to find out what is supported on the current OS

**Comment by octref** [comment]
Was thinking about reporting this too. Would be nice to say the default value for each option in the spec so they show up in IntelliSense.

Agree that "*Note* that not all operating systems support to select files and folders in one dialog instance" is a bit vague. But think instead of adding more to the API it's better to put the info in the spec.

**Comment by jrieken** [comment]
I like the enum

**Comment by jrieken** [comment]
I don't the enum 🙊 It makes the code look more verbose and has naming challenges... `OpenDialogSelectionKind`? Instead, I will rename `openFile` and `openFolder` to `canSelect[File|Folder]`. Also, it will be `canSelectMany`. Last, more jsdoc is needed...
