### ISSUE TITLE
Launch TypeScript out-of-the-box

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#35160]
Testing #34993

AKA "F5 a TypeScript file".

An old idea, but: Would it be possible to run a task without a `tasks.json` on disk? Similar to launching a debug session without having a `launch.json` on disk? Could we then have an in-memory launch config with a preLaunchTask that compiles the currently open `.ts` file?

Maybe not much has changed since this came up last, but I thought I'd ask. Other languages might also benefit from a solution, if it is generic enough.

**Comment by dbaeumer** [comment]
This is possible since TS contributes a task to compile the TS file. The launch config in memory should simple reference the TS contributed task that only exists in mememory (no need to have a tasks.json) file on disk.

**Comment by isidorn** [comment]
@dbaeumer just some brainstorming: for this to work the task in memory would need to have an ID and when @weinand generates the launch in memory he would need to reference the task in memory by the id. 
Or by some special way which means "run task which is in memory for this language" (which probably does not scale since I guess we can have multiple tasks in memory).
Since the connection between the tasks framework and the debug adapter is the lanugage there should be some way for adapter to say run whatever you have in memory for this langauge. Or a way to get all the tasks contributed by this language.

**Comment by weinand** [comment]
Since I've started to use the `outDir` from the `tsconfig.json` for #35055, I can now easily generate a `preLaunchTask` with a well-known build task that compiles TS into the correct directory. The resulting in-memory launch config looks like this:
```
{
    "type": "node",
    "request": "launch",
    "name": "Launch Program",
    "program": "${workspaceFolder}/foo.ts",
    "preLaunchTask": "tsc: build - tsconfig.json",
    "outFiles": [
        "${workspaceFolder}/lib/**/*.js"
    ]
}
```

With this its is now possible to launch TS without launch.json. 
But you still need a tiny `tsconfig.json`:
```
{
    "compilerOptions": {
        "outDir": "./lib",
        "sourceMap": true
    }
}
```

Any ideas how to eliminate the `tsconfig.json`?

/cc @mattbierner

**Comment by mjbvz** [comment]
@weinand You should be able to pass all the options from the `tsconfig` to `tsc` as flags: https://www.typescriptlang.org/docs/handbook/compiler-options.html

Would this work in this case?

**Comment by weinand** [comment]
@dbaeumer is it possible to create an ad-hoc "tsc" task from the node-debug extension and use that task as the "preLaunchTask"?

**Comment by mjbvz** [comment]
Sorry I misunderstood what the `preLaunchTask` was doing here. To support this case, I think the TypeScript extension  would need to generate a new task called "compiled inferred project" or something similar, and then we'd need a way to pass arguments (such as the current file name) from the launch.json to this task

**Comment by weinand** [comment]
@mjbvz yes, debug wants to use the `preLaunchTask` so that it does not have to run `tsc` itself (and deal with errors etc.)

Ideally, even the "start TypeScript debug session" code could be contributed by the TypeScript extension (instead of living in node-debug).

But a first step could be that the TypeScript extension contributes a "compiled inferred project" (as you suggested) that debug could use as the `preLaunchTask`.

Currently there is no way to pass arguments to the `preLaunchTask`, so this task should just "build" what is there and debug hopes that it can launch the target when build has finished.

**Comment by dbaeumer** [comment]
@weinand yes, but it would be a normal task contribution and therefore show up in the Run Task picker. However I could add API to mark a task as internal so that it can't be picked in a picker.
