### ISSUE TITLE
Error msg for rename failure from extension disappears after a while

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#35177]
The Go extension registers a rename provider which sends a rejected promise when there is an error in renaming. See https://github.com/Microsoft/vscode-go/blob/0.6.65/src/goRename.ts#L46

VS Code shows this message as a warning followed by a general msg about rename failure as an error

![image](https://user-images.githubusercontent.com/16890566/30885462-413937b8-a2c8-11e7-888e-19226ac67531.png)

After a while, the warning (which is the actual error message from the extension) disappears, the error with the general message remains.

Shouldnt the message from the extension stay around until user closes it

**Comment by jrieken** [comment]
> Shouldnt the message from the extension stay around until user closes it

Yes, but this is an error message from the core (the rename-feature). For extensions we have enforced that they don't auto-dispose and add the close-button everywhere. 

@bpasero Unsure what the rule in the workspace is? Do we hide error messages after timeout or do we keep them?

**Comment by bpasero** [comment]
@jrieken it looks like today we are not removing messages that either have severity `ERROR` or carry actions with them for the user to pick ([here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/message/browser/messageList.ts#L479)). 

Now, it looks like when an extension runs `showInformationMessage` we are actually adding a "Close" action and as such none of the extension messages are ever closed (I think we have this behaviour since quite some time). 

I am not sure where the message is created that originates from the rejected promise, but if that one has a "Close" action too it would stay open.

**Note:** we add a "Close" action automatically to each message that does not come with an action itself. So in general it would not be needed, however, not providing any actions results in the automated removal after N seconds.

**Comment by ramya-rao-a** [comment]
With https://github.com/Microsoft/vscode/commit/dbe0f89264dc6e9d38cf8723e358741ce9e8a131, rejected rename promise from extension was made to get rejected as `Error` instead of `string`

Only if the rename promise was rejected using string, the message would show up as error due to https://github.com/Microsoft/vscode/blob/release/1.16/src/vs/editor/contrib/rename/browser/rename.ts#L162

At present, we always end up in the `else` block.
Thus showing a standard localized "Sorry, rename failed to execute." message.
Since a wrapped error as promise is being returned again from the `else` block, that results in the warning that disappears after N seconds.

I propose this: https://github.com/Microsoft/vscode/commit/281c9386e241c9e9076ac50aad6c99160b9e69bd
