### ISSUE TITLE
link origin of messages in debug console not working under Windows

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#35213]
Testing https://github.com/Microsoft/vscode/issues/34756

OS: Windows 10
Node: 8.1.4
JS file
```
console.log("Hello World");
```

No linking happens in the debug console.

**Comment by isidorn** [comment]
There was a stupid copy/paste mistake I did. Accidently copied .mac for .css rules.
I have re-triggered builds so you can test this

**Comment by octref** [comment]
- VSCode Version: Code - Insiders 1.17.0-insider (f7dc950831c601a247e08f374df8d018fbb97b5a, 2017-09-28T17:50:54.394Z)

Actually still happens on Windows. Seems to be something else than css since `div.source` is empty.

![image](https://user-images.githubusercontent.com/4033249/30996449-d140eff0-a475-11e7-837b-0d0f55c11278.png)

**Comment by isidorn** [comment]
You are using the legacy protocol. Please check out the test item, you need to have node > 8 version installed, or protocol: inspector in your launch.json

**Comment by octref** [comment]
@isidorn Oops. I was on macOS with 8.4 and only Node V6 on windows. Sorry 😅
