### ISSUE TITLE
Auto expanding/collapsing console entries

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#35226]
* have an extension that prints an array containing a single uri
* drill into the uri
* :bug: the stack trace keeps expanding/collapsing which is very nervous

![sep-27-2017 14-45-21](https://user-images.githubusercontent.com/1794099/30914163-f706d88c-a392-11e7-8034-abe3264bb68a.gif)

**Comment by bpasero** [comment]
@jrieken yeah looks like an issue with overloading `console.group()` with complex objects and arguably a bug in dev tools. 

After I pushed https://github.com/Microsoft/vscode/issues/35222 this will be less hectic, because the stack is only 1 line. 

An alternative to using the `console.group` thing is to just add the first frame of the stack as argument to the console.log method. This would then look like:

![image](https://user-images.githubusercontent.com/900690/30915833-3ccb4998-a398-11e7-8418-9afb3804fd0d.png)

**Comment by jrieken** [comment]
Yeah, lets give that a try
