### ISSUE TITLE
When no folder or file open, the debug play button should not be shown

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#35247]
- Open a new VS Code window with no folder or file open
- Go to the debug viewlet.
- The gear icon is missing which makes sense as there is no workspace to create the launch.json file in
- The play icon is present. Clicking on it opens the "Select environment" action
![image](https://user-images.githubusercontent.com/16890566/30930092-67ad050c-a375-11e7-8820-c9ae7adbc34c.png)

Choosing any option obviously would result in an error.

We should either not show the play icon at all or on clicking on it should show an error saying "no file/folder to debug" instead of showing the "Select environment" action

**Comment by isidorn** [comment]
Thanks for your feedback, however some debuggers support debugging in no folder case - example node debug.
I also do not want to have a special case of not showing the play button if there are no files in the workspace. Since that could also in theory be covered by the debugger

If you are not getting a proper error message that is up to the debug adapter and please file accordingly to go or node, thanks
