### ISSUE TITLE
debug.hoverWidget closes when hovering over debug console panel

### ISSUE THREAD

**Issue by pflannery** [Microsoft/vscode#3528]
![animation](https://cloud.githubusercontent.com/assets/1727302/13374401/cb2b963c-dd7b-11e5-81e3-6db02a205ac3.gif)

**Comment by isidorn** [comment]
@alexandrudima the issue I have here is that the `mouseLeave` event does not have a `target`, so I can not use something like [this](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/browser/debugEditorContribution.ts#L170)

Because content widgets can now go outside the editor sometimes the `mouseLeave` event should still have a `target`, right?
Locally I tried changing the [mouseHandler](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/browser/controller/mouseHandler.ts#L211) however with my simple change (to handle it similar to `_onMouseUp()`) I would still get my hover as the target even when it is not a target. Maybe some tips on how to solve this properly?

**Comment by httpdigest** [comment]
I think this bug is not properly solved. Now, the "debug variable overlay" does not disappear anymore, but whenever the mouse cursor is above the "debug console resizing handle", we see the vertical resizing icon. When at the same time an expandable variable/tree item is rendered in the debug variable overlay, this cannot be expanded anymore, since the mouse thinks it should handle the debug console resizing.

**Comment by isidorn** [comment]
Nice find, reopening to investigate

**Comment by isidorn** [comment]
After looking into it I distilled it into a new bug https://github.com/Microsoft/vscode/issues/9678
