### ISSUE TITLE
If file is already existing and I don't want to overwirting the file when I build a file, the software will be down.

### ISSUE THREAD

**Issue by YaoLiuDL** [Microsoft/vscode#35308]
If file is already existing and I don't want to overwirting the file when I build a file, the software will be down after choosing cancel.

**Comment by isidorn** [comment]
Can not reproduce.
Please file exact repoducable so we can investigate this further.
A video would also be helpful
Also can you reproduce with the latest vscode insiders https://code.visualstudio.com/Insiders/

**Comment by YaoLiuDL** [comment]
@isidorn the gif is here, my operating system is deepin based unbuntu. And the version of vscode is 1.16.1.
![bug](https://user-images.githubusercontent.com/12014003/30960658-4363a0aa-a476-11e7-87f5-b6a8e532567b.gif)
I don't know if you can read my uploaded gif.

**Comment by isidorn** [comment]
@bpasero forwarding to you to potenitally add the freeze slow crash questionare

**Comment by bpasero** [comment]
I can also not reproduce, seems specific to the Linux distribution. @Tyriar have you seen this?

@YaoLiuDL anything in the logs? 
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by Tyriar** [comment]
Yes this looks like a distribution problem. On Ubuntu/mac the open dialog remains when in the background whereas in the above gif it disappears. This probably means that focus is being sent to the hidden modal dialog which is why things are breaking.

<img width="872" alt="screen shot 2017-09-28 at 9 24 31 am" src="https://user-images.githubusercontent.com/2193314/30968910-dec58240-a42e-11e7-83e4-faf5fe676591.png">

**Comment by Tyriar** [comment]
Pressing escape in this state may workaround the issue

**Comment by YaoLiuDL** [comment]
@Tyriar yeah, it works. Thanks!
