### ISSUE TITLE
Colorize in debug console for evaluation results

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#35324]
From #34043

It would be nice to keep colorization for 'evaluate' requests, since the result has a 'type'. node2 doesn't set the type... it could though.

![image](https://user-images.githubusercontent.com/323878/30943241-96845fae-a3a4-11e7-8cb1-fe458d6023a7.png)

vs previously

![image](https://user-images.githubusercontent.com/323878/30943246-9c4d074c-a3a4-11e7-8236-940398078d7d.png)

**Comment by isidorn** [comment]
We could do this for october.
@roblourens Can you please ping me when node2 introduces a type so I look into implementing this on the vscode side. Thanks

**Comment by isidorn** [comment]
I have pushed some support for this, preciesely:
* For evaluate expressions I always try to colorise
* If a type is "boolean", "string" or "number" I just use that type, otherwise I try to guess as before

I did it in this way such that C# does not get broken if they return "int" instead of "number".

Coloring is still disabled for simple output in repl.
In practice this has behaved the best for me, but I am open for suggestions on how to more fine tune this.
@roblourens still has to pick this up for node2 however there is already an open issue for this thus I am closing this one.
fyi @weinand
