### ISSUE TITLE
Copy/Paste Police

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#35329]
* the copy/paste detector from https://www.npmjs.com/package/jscpd
* run it `src/vs` like so `jscpd --path . --languages typescript --exclude **/*.test.ts -l 50` which will search for more than 50 duplicated lines
* see the output below

I believe the first two are just because of d.ts-stunts, but I believe the latter two are real. Please check.

```
jrieken:~/Code/vscode/src/vs$ jscpd --path . --languages typescript --exclude **/*.test.ts -l 50
info:    jscpd - copy/paste detector for programming source code, developed by Andrey Kucherenko
info:    Preprocessors running time: durationMs=352
info:    Scanning 1101 files for duplicates...
info:    Scanning for duplicates time: durationMs=21672
info:    Scanning... done!

info:    Start report generation...

info:    Found 4 exact clones with 357 duplicated lines in 7 files

	- /Users/jrieken/Code/vscode/src/vs/base/common/keyCodes.ts: 14-162
	 /Users/jrieken/Code/vscode/src/vs/editor/common/standalone/standaloneBase.ts: 51-199

	- /Users/jrieken/Code/vscode/src/vs/base/common/keyCodes.ts: 18-99
	 /Users/jrieken/Code/vscode/src/vs/monaco.d.ts: 176-257

	- /Users/jrieken/Code/vscode/src/vs/editor/standalone/browser/accessibilityHelp/accessibilityHelp.ts: 175-232
	 /Users/jrieken/Code/vscode/src/vs/workbench/parts/codeEditor/electron-browser/accessibility.ts: 138-195

	- /Users/jrieken/Code/vscode/src/vs/workbench/services/search/node/ripgrepTextSearch.ts: 301-372
	 /Users/jrieken/Code/vscode/src/vs/workbench/services/search/node/worker/searchWorker.ts: 298-369


 0.11% (357 lines) duplicated lines out of 313341 total lines of code.

warn:    output file is not provided
info:    Generate report time: durationMs=14
info:    All time: durationMs=22047
```

**Comment by alexandrudima** [comment]
My code duplication is caused by us shipping the standalone editor:

```
- /Users/jrieken/Code/vscode/src/vs/base/common/keyCodes.ts: 14-162
 /Users/jrieken/Code/vscode/src/vs/editor/common/standalone/standaloneBase.ts: 51-199
```
This one is because I want our `KeyCode` to be a `const enum` which gets inlined in all our source code and because the standalone editor exports the enum and TypeScript (correctly so) doesn't allow you to assign a `const enum` as it might disappear at runtime, depending on a flag in `tsconfig.json`.

```
- /Users/jrieken/Code/vscode/src/vs/base/common/keyCodes.ts: 18-99
 /Users/jrieken/Code/vscode/src/vs/monaco.d.ts: 176-257
```
I'm surprised there is such a low hit-rate on the `monaco.d.ts`. `monaco.d.ts` is duplicated code *by design*.

```
- /Users/jrieken/Code/vscode/src/vs/editor/standalone/browser/accessibilityHelp/accessibilityHelp.ts: 175-232
 /Users/jrieken/Code/vscode/src/vs/workbench/parts/codeEditor/electron-browser/accessibility.ts: 138-195
```
:+1: I suppose I could extract here code for an editor "pop-over". The root cause is again, that the accessibility help messages are very different in the standalone editor and in the workbench, they have different messages and different implementations.

**Comment by alexandrudima** [comment]
I don't think it is worth it to extract a widget only for `accessibilityHelp.ts` and `accessibility.ts` => so no action for me. They are different as they are different exclusive contributions (one for the monaco editor and one for vscode). I can pay the cost of maintaining both.

**Comment by roblourens** [comment]
Mine was unused code, already removed
