### ISSUE TITLE
The svg file can not be displayed in the markdown preview

### ISSUE THREAD

**Issue by zhuangyin8** [Microsoft/vscode#35374]
- VSCode Version: Code - Insiders 1.17.0-insider (f7962f0682a76516df51de4856f8ccc5d8ad578a, 2017-09-20T05:24:33.599Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-caniuse|aka|0.5.3
markdown-toc|Ala|1.5.6
color-info|bie|0.5.0
markdown-preview-github-styles|bie|0.0.4
regex|chr|0.1.0
vscode-markdownlint|Dav|0.10.1
vscode-eslint|dba|1.3.2
vscode-html-css|ecm|0.1.8
tslint|eg2|1.0.9
vscode-great-icons|emm|2.1.16
vsc-material-theme|Equ|1.0.3
prettier-vscode|esb|0.23.1
beautify|Hoo|1.1.1
minify|Hoo|0.3.0
markdown-shortcuts|mdi|0.8.1
HTMLHint|mka|0.4.0
vs-keybindings|ms-|0.1.7
debugger-for-chrome|msj|3.3.1
color-highlight|nau|2.3.0
material-icon-theme|PKi|2.2.1
vscode-css-peek|pra|1.3.1
stylelint|shi|0.29.1
html5-boilerplate|sid|1.0.1
code-spell-checker|str|1.4.0
vscode-markdown-paste-image|tel|0.5.0
html-preview-vscode|tht|0.1.1
quokka-vscode|Wal|1.0.67
vscode-todo-highlight|way|0.5.11
html-css-class-completion|Zig|1.10.0

(3 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment]
This is by design. We disable svgs by default for security reasons. You can click on the warning in the preview or run the `Markdown: Change preview security settings` command to change this.

Please see the markdown preview security documentation for more information: https://code.visualstudio.com/Docs/languages/markdown#_markdown-preview-security

**Comment by gdvallance** [comment]
@mjbvz Should the previewer render .svg images from within the project, say from an internal Images folder? I ask because in Version 1.17.2 of the software running under Ubuntu 16.04 64 bit, it does not render it.

For instance `![](/Images/BMT GVHD Pathway.svg)` renders fine if I go through Pandoc, but not in the previewer. Moreover, I found the same true for .jpg files too.

I found that changing the security preferences made no difference.

So there may yet be a bug ...

**Comment by mjbvz** [comment]
@gdvallance Not by default unless you disable the security settings. However I think your problem is that there are spaces in the path, which is not supported by commonmark. Try percent encoding them:

```
![](/Images/BMT%20GVHD%20Pathway.svg)
```

**Comment by gdvallance** [comment]
@mjbvz Thanks for the reply. It is greatly appreciated. I have tried your suggestion and it did change the rendering from the text to an icon for an image, but not the image itself for both *.svg & *.jpg. Changing security settings did not alter whether the icon rendered or not.

**Comment by mjbvz** [comment]
@gdvallance Can you please open an new issue to continue this discussion. It may be that the path is incorrect: `![](/Images/...)` will resolve to the `Images` directory in the root of your workspace
