### ISSUE TITLE
Moving a line down with alt+arrow removes tabs.

### ISSUE THREAD

**Issue by qwerji** [Microsoft/vscode#35429]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:24:39.530Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
material-icon-theme|PKi|2.2.1
python|don|0.7.0
csharp|ms-|1.12.1
ayu|tea|0.8.0
vscode-todo-highlight|way|0.5.11

(1 theme extensions excluded)

---

![move line](https://media.giphy.com/media/xT9IgJ08ex4RqXo93O/giphy.gif)

Steps to Reproduce:

1. Tab (4 spaces) in a line.
2. Move an adjacent line down past it using alt+down arrow.
3. Tab on the first line gets deleted.

Reproduces without extensions: Yes

**Comment by alexandrudima** [comment]
workaround: `"editor.autoIndent": false`

**Comment by rebornix** [comment]
Moving lines doesn't honor your intentional indentation so when you are moving it, it tries to guess by checking the indentation of previous line, that's why moving `rect(...` upwards doesn't break your indent while moving it downwards does.

If the auto indent guessing doesn't help you out most of time, you can disable it by `editor.autoIndent`.
