### ISSUE TITLE
Explore new icons to replace smiley

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode#3544]
Porting issue #3440 here. 

Looking into options of switching the icon to a less distracting icon based on feedback.

**Comment by Yahkob** [comment]
Would it make sense to perhaps offer an option to just hide the smiley from the status bar? Either with an option in the UI like: 

![screen shot 2016-11-22 at 12 37 23 pm](https://cloud.githubusercontent.com/assets/5547203/20541130/bbc8b2d4-b0b0-11e6-86ae-a65299f6bfcf.png)

and/or including a property in user settings to hide it? 

I've looked into the work involved to PR my suggestions and it seems like it would be a pretty trivial amount of work. 

It seems like there is a cult of dislike surrounding the smiley, which is... quite funny given the nature of the icon. I also realize the smiley may be a consistency thing since I've seen it across all MS products lately.

**Comment by waderyan** [comment]
@Yahkob this is a good idea. A PR would be welcome. 😄

**Comment by waderyan** [comment]
@bgashler1 wondering if this might be better on your radar. How do I move things to the UX backlog? 

ping @chrisdias relevant for your UX process deliberation.

**Comment by Yahkob** [comment]
Awesome sounds good @waderyan. Could you or anyone else help me to understand the best practice internally to modify user settings (I'm assuming this would be the most relevant place to toggle UI state)? I tried looking through the docs for any sort of internal API like `setUserSetting(k, v)` but most of the docs only have information pertaining to extensions and not internal APIs.

**Comment by bgashler1** [comment]
@waderyan / @Yahkob:
We're introducing a concept soon (in tandem with #9717) for users to be able to right click pieces of UI contributed by extensions.  The context menu would have the option for you to hide such UI.

![screen shot 2016-11-28 at 2 41 14 pm](https://cloud.githubusercontent.com/assets/11839736/20689160/c3aead88-b578-11e6-8815-dcf1fb4ef9b9.png)

We could possibly apply this to parts of the core UI, as well, including the feedback widget.  I will keep this request in mind as we continue to iterate on this concept.

**Comment by gmattie** [comment]
Until this issue is properly addressed, it is possible to remove the icon ourselves with DevTools:

_Help > Toggle DevTools > Console_

`document.querySelector(".monaco-workbench>.part.statusbar>.statusbar-item.right").style.display = "none";`

**Comment by Tyriar** [comment]
A pattern we've been using lately is to allow hiding of components via the context menu, it would probably make sense to be consistent in the status bar:

<img width="616" alt="screen shot 2017-10-25 at 10 49 15 am" src="https://user-images.githubusercontent.com/2193314/32014199-41cb2c84-b972-11e7-83cb-56378596a984.png">
<img width="194" alt="screen shot 2017-10-25 at 10 49 21 am" src="https://user-images.githubusercontent.com/2193314/32014200-439af940-b972-11e7-8c46-9f668b4de357.png">

/cc @isidorn

**Comment by isidorn** [comment]
Yeah we need to adress the status bar overflow sooner or later. And the current patterns make sense.

**Comment by Tyriar** [comment]
Closing this off in favor of https://github.com/Microsoft/vscode/issues/7893, will copy my proposal over there.
