### ISSUE TITLE
WorkspaceConfiguration.get doesn't respect defaultValue parameter

### ISSUE THREAD

**Issue by hoovercj** [Microsoft/vscode#35451]
Steps to Reproduce:

1. Create a simple extension that contributes settings without setting a default
```json
"configtest.number": {
    "type": "number",
    "description": "No default value"
},
```
2. When activating the extension, "get" the workspace value:
```typescript
'use strict';
import * as vscode from 'vscode';
export function activate(context: vscode.ExtensionContext) {
    const config = vscode.workspace.getConfiguration('configtest');

    // The default value is set to 0 despite not being set in package.json
    const defaultValue = config.inspect('number').defaultValue;

    // As a consequence, the 5 here is ignored
    const value = config.get('number', 5);

    vscode.window.showInformationMessage(`defaultValue = ${defaultValue} / value = ${value}`);
}
```

**Expected:** The info message reads `defaultValue = undefined / value = 5`

**Actual:** The info message reads `defaultValue = 0 / value = 0`

The code for [`workspaceConfiguration.get`](https://github.com/Microsoft/vscode/blob/feded35e7a23d17ab1ff69089f3ead2a883fff50/src/vs/workbench/api/node/extHostConfiguration.ts#L82) only uses the default value passed in to the `get` function if the lookup value is `undefined`, but that seems impossible to do. If I omit `default` in `package.json`, the default value for the data type is used (0, [], {}, "", etc.) and I can't put `undefined` in the `package.json`.

You can see my repro code [here](https://github.com/hoovercj/vscode-api-playground/tree/master/ConfigurationTest).

**Comment by hoovercj** [comment]
Related to this, `onDidChangeConfiguration` is NOT called if there is no default value provided, and a user adds or removes a setting line that has the default "defaultValue".

In the case of the `configtest.number` setting above, adding or removing this line in the `settings.json` file will not trigger `onDidChangeConfiguration`:

```
configtest.number: 0
```

I have an extension that has several settings, but it also has one setting that represents different "presets" or "themes". I want to resolve settings in this order:

`workspace > user > theme > default`

This means that my theme value needs to have precedence over the default value. This fails if the user wants to override a theme setting by adding the value `0`. It doesn't really make sense for me to set a "default" value because the default is undefined. Unfortunately, if the application level default set in the theme is `5`, but the user wants to override it with `0`, my extension isn't notified.

So when addressing this, it would be great if `onDidChangeConfiguration` gets called any time a setting without a default is added or removed from a `settings.json` file.

I will point out that `onDidChangeConfiguration` is also not called if a default value IS provided and the setting with that default value is added or removed. I assume that is "by design", though I can imagine situations where an extension author might want a default value but might care whether a setting is explicitly or implicitly set.

**Comment by sandy081** [comment]
@hoovercj Thanks for reporting the issue. I see you have 3 issues here

1. Default value of configuration is always set to a value (which is not undefined) when it is undefined. This makes the API `WorkspaceConfiguration.get(section, defaultValue)` useless. Will look into it in this issue.

2. > Unfortunately, if the application level default set in the theme is 5, but the user wants to override it with 0, my extension isn't notified
Not sure if I understand it. Do you mean if the user changes the user setting value to `0` when the default value is `5` and the event is not triggered? If so, I would recommend to file a separate issue for this case.

3. >I will point out that onDidChangeConfiguration is also not called if a default value IS provided and the setting with that default value is added or removed. I assume that is "by design", though I can imagine situations where an extension author might want a default value but might care whether a setting is explicitly or implicitly set.
Yes, this is by design and I think this is what most of the consumers of this API expect. Triggering a configuration change when there is no change is not correct IMO.

**Comment by sandy081** [comment]
@hoovercj Default values are set for following types

```ts
```
