### ISSUE TITLE
Can't reset font size after zooming with mouse wheel

### ISSUE THREAD

**Issue by monk-time** [microsoft/vscode#35456]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.3.2
block-travel|sas|0.0.2
selectline-statusbar|tom|0.0.2

Reproduces without extensions: Yes

---

Currently there are two ways to change font size: by zooming the UI with keyboard shortcuts or menu options and by ctrl+scrolling with `"editor.mouseWheelZoom": true` . But it is impossible to reset the zoom level after zooming with mouse wheel except by restarting the editor. 

The issue stems from this: ctrl+scrolling changes the font size independent from the UI zoom level, and "Zoom In/Zoom Out/Reset Zoom" actions change the UI zoom level (which affects visible font size) but not the font size set by the former.

Here's a recording of me (using a fresh VS Code Insiders 1.17.0 build) ctrl+scrolling (zooming out) then changing the UI zoom level then ctrl+scrolling again (zooming in). You can see that the changes to font size are impossible to reset, they don't even register in the settings file.

![2017-09-28_15-33-29](https://user-images.githubusercontent.com/7759622/30966831-f10a2a8a-a462-11e7-8328-797380aca23b.gif)

**Comment by monk-time** [comment]
Another bug report with the same issue: #25047 (closed because of a vague description).

**Comment by ahdung** [comment]
+1

**Comment by langheran** [comment]
A workaround is to just reload the window :s .

**Comment by borekb** [comment]
In VSCode 1.33 (March 2019), there's a command called **Editor Font Zoom Reset** that does exactly what is requested here (I believe). It has been implemented in https://github.com/Microsoft/vscode/issues/48838 which shipped as part of May 2018 release so maybe it just flew under the radar?

Anyway, I came to this issue because I also thought that there's no way to reset font zoom, only later discovered that there is.

**Comment by berknam** [comment]
Zooming with mouse wheel doesn't update the configuration `window.zoomLevel` and there is no `editor.fontZoomLevel` configuration so if there is anything that depends on it, it won't work properly.
Like if you have a TextEditorDecoration that depends on the fontSize, lineHeight or zoomLevel, it won't behave correctly because none of this options will be updated when zooming through ctrl+mouse wheel.

**Comment by ardunster** [comment]
I also had this issue, resolved by reloading the window, but I didn't expect "scroll wheel zoom" at all (using two fingers to scroll on a trackpad, apparently somehow I accidentally zoomed instead).  I've disabled scroll wheel zoom, but having an option to reset the editor zoom in the same part of the GUI as the other zoom options would be nice (that's where I would have expected to find it)

**Comment by jelitter** [comment]
4 years later and this is not yet fixed.

**Comment by RoniRoland** [comment]
5 years lates and still this issue persist...

**Comment by akincan-kilic** [comment]
Go to your Keybinding settings.

**Comment by akincan-kilic** [comment]
Go to your Keybinding settings.

Type in `Font Zoom`, click `Editor Font Zoom Reset`, then set a keybind for `CTRL + NumPad 0`

It should look like this in the end:
![image](https://user-images.githubusercontent.com/65862487/188761310-c6e434c0-b3bd-4bbf-a975-f6096663a3fa.png)

**Comment by ahdung** [comment]
`CTRL + NumPad 0` not a good shortcut, it bound to **View: Reset Zoom**, Binding the same shortcut won't make them work together, Maybe `Ctrl+Numpad_Decimal` better.

**Comment by UrDevBuddy** [comment]
I did this mistake today, and here is how I fixed it.

- Open your command palette with Ctrl + Shift + P
- Type _**font zoom reset**_ and click on the result

The font's gonna reset to normal.

**Comment by alexdima** [comment]
The command `Editor Font Zoom Reset` implements what the OP requested.
