### ISSUE TITLE
IntelliSense automatically completes without Tab/Enter

### ISSUE THREAD

**Issue by bsvipas** [Microsoft/vscode#35461]
- VSCode Version: 1.16.1
- OS Version: macOS 10.13

Steps to Reproduce:

1. Open new file
2. Set syntax to JavaScript
3. Reload window
4. Write `onAbort()`, but slowly you need to wait for IntelliSense popup and it will be automatically converted to `onabort()` even if I didn't press Tab or Enter.

![intellisense_auto_trigger_bug](https://user-images.githubusercontent.com/30043375/31057990-b7e9b07e-a6f4-11e7-9ea2-05d85d48e3a3.gif)

Reproduces without extensions: Yes, I disabled all extensions.

**Comment by bsvipas** [comment]
This doesn't happens in VS Code Insiders. Really weird bug, but soo annoying...

**Comment by bsvipas** [comment]
Tried with different Node versions. 7.10.1 and 8.6.0. Issue is same.

**Comment by bsvipas** [comment]
@mjbvz Updated to 1.17.0 and problem still exists. I don't get it... Tested and seems if you reload window and type it very fast it will be autocompleted, but if you wait till it load fully the problem gone. Can someone take a look at it? @ramya-rao-a @bpasero @Tyriar

**Comment by bsvipas** [comment]
[tstrace.txt](https://github.com/Microsoft/vscode/files/1361637/tstrace.txt)
This is all trace, if you search for `insertString` you will see I'm using it with `A` camel case and it was automatically autocompleted to `a`.

**Comment by karolis-gataveckas** [comment]
@mjbvz I can reproduce this as well, it's really frustrating.

**Comment by tomas-cimermonas** [comment]
Reproduced the issue. Looking for solution @mjbvz .

**Comment by ramya-rao-a** [comment]
Am on VS Code 1.17.0
I don't see the `()` being added.

My user settings are empty.

![js](https://user-images.githubusercontent.com/16890566/31287054-e747380e-aa74-11e7-8bce-6048f5d17222.gif)

What is the version of typescript that you are using?

**Comment by bsvipas** [comment]
@ramya-rao-a You need to write `onAbort` with `()` and it will automatically transformed to `onabort()` that's the issue. It automatically autocompletes code to lower case even if we don't use Tab/Enter. Or if this doesn't work try to write in one line `onAbort() onClick() onBlur()` but write them all in camel case and don't use Tab/Enter you will see the problem I'm talking about.

**Comment by ramya-rao-a** [comment]
Thanks @bsvipas, I can now repro with `onAbort() onClick()` but not with just `onAbort()`

@mjbvz has been on vacation this week and so the delay in repsonse.

@mjbvz, I was able to track down the root cause to be the fact that `(` is being considered as a commit character for these suggestion items.

@bsvipas, @karolis-gataveckas, @tomas-cimermonas A workaround for this until @mjbvz can get back with more details is to disable the setting `editor.acceptSuggestionOnCommitCharacter`

**Comment by bsvipas** [comment]
@ramya-rao-a Thank you very much for such great response so as far as I understand this will be fixed?

**Comment by ramya-rao-a** [comment]
@mjbvz will be able to provide more details soon

**Comment by mjbvz** [comment]
I believe this is the expected behavior. When you type out a name but get the case wrong, you do want the completion to fix the casing for you. We also accept a completion when you type `(` or `.` to speed up typing

If you don't want this behavior, you can either disable it completely by disabling `editor.acceptSuggestionOnCommitCharacter` or hit escape to cancel out of the suggestion widget

**Comment by bsvipas** [comment]
Thanks @mjbvz that `editor.acceptSuggestionOnCommitCharacter` helps.
