### ISSUE TITLE
VSCode hangs or freezes also with newer version

### ISSUE THREAD

**Issue by peltsi212** [Microsoft/vscode#35475]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T17:16:27.618Z)
- OS Version: Linux x64 4.4.0-93-generic (Ubuntu 16.04 LTS)
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.2.11
docthis|joe|0.4.8

---

Steps to Reproduce:

Use vscode long time like two days and let it running over night.
I cannot say exact pattern what to do to repeat freeze.
I am editing .js file which contains es2017 javascript code
Freezing happens after many hours of editing.
Freezing have happened know 4 times.
If I remember correctly freezing happens when I switch back from other program.
I was not doing anything special just editing file.
During freeze I cannot move cursor with cursor key.
If I click with mouse, the cursor is not moved to point where I click.
I have many files open.
Tabs for 7 files are visible.
If I click tab, then file name is updated in same area where menu is located.
However tab do not change to that one I click.
I can click menu and then menu dropdown appears.
If select action like Command Palette nothing happens.
This is so for almost all menu items.
One exception is Help About. It shows information of visual studio code version.
Second exception is Help Report issues is also working.
If I click x to close VSCode application, that works.

This same thing happened earlier with VSCode 1.14.2
There is closed issue #33149 about this.

Reproduces without extensions: Not tested

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by BillDenton** [comment]
I'm seeing similar problems. It was working on Friday, but it is **completely unusable today** and with extensions it is using over 40% of the CPU. After a while it produces a VS Code "The window is no longer responding" "You can reopen or close the window or keep waiting". I've just fired up without extensions and it seems to be working. **As I can't work at the moment**, two questions:
1. How do I revert to the previous version?
2. What information is required for diagnosis?

**Comment by wUFr** [comment]
similar issues, did not try it without extensions yet tho.

i also noticed, while i am editing files on SMB shared storage (local virtual network - 10Gb), SMB process on server (CentOS 7) is using 40-60% of 1 CPU thread, i did not see such utilization before. Could this be related? GIT is disabled, so idk why it would utilize it so much

**Comment by peltsi212** [comment]
Today this happened again. 
Result and symptoms are same as before.
Now I have 
VSCode Version: Code 1.16.1
I was editing a .js file.
I was writing text. Then I Copied a line in file with Ctrl+C and CTRL+V
Freezing happened when I tried to change copied line.
Vs Code was running over night.
I worked with VS code in the morning about 10 minutes before freeze.

**Comment by peltsi212** [comment]
I have not been able to repeat this problem when extensions are disabled.
I created issue 313 in eslint gitgub
https://github.com/Microsoft/vscode-eslint/issues/313

**Comment by wUFr** [comment]
i personally dont have any more problems after recent update, not even SMB load problem on server side i had before :O

**Comment by dbaeumer** [comment]
@bpasero can we reopen this. The symptoms described here https://github.com/Microsoft/vscode/issues/35475#issue-261987667 can hardly be caused by ESLint which is running in its own process and communicates with the renderer over the extension host.

**Comment by dbaeumer** [comment]
@bpasero thanks. I will ask @peltsi212 to continue the discussion here and will see if I can find out something.

**Comment by peltsi212** [comment]
CPU load is not high during hang. Computer has i7 CPU with 4 cores. 8 GB memory. SSD disk.
Ubuntu is running as wmware virtual machine in windows 10 host. Ubuntu is sometimes swapping because memory usage might be 8 GB and Ubuntu virtual machine have 5,5 GB memory allocated.
I have noticed that vscode is now more responsive when I have disabled eslint extension. When eslint was active, it sometimes happens that when I write text it appears in screen only after 2 or 3 seconds.

**Comment by dbaeumer** [comment]
@peltsi212 do I understand you correctly. You see a lag of typing not a lag of error annotations. A lag of error annotations could be on purpose. We throttle the error calculation a little based on file size.

**Comment by peltsi212** [comment]
Yes exactly lag of typing. There is also lag of cursor movement with cursor keys. This is also something that I cannot say exact pattern what to do to repeat this lagging effect. Biggest javascript file have been so far 930 lines of code. I work with same files with Eclipse and with Angelo Zerr Tern linter. There is no lagging with eclipse

**Comment by dbaeumer** [comment]
@alexandrudima do you have an idea how to understand why typing lags here.

@peltsi212 can you enable tracing for ESLint for a while to see if there is something that could explain this. Set the setting `"eslint.trace.server": "messages"`. There should be a log in the ESLint output channel. Can you attach the log when you see the lagging appear.

**Comment by jberube** [comment]
VS Code 1.16.1
Only extension is ESLint 1.3.2
With and without `--disable-extensions`
Windows 10

I have what i believe to be the same problem.
The whole window freeze, sometimes only for 5 seconds, sometimes up to 1 minute, maybe more. Contrary to others, I don't have to let the editor run for a long time, I get it right away when I open VS Code.
I noticed a CPU usage spike on all my cores, but it does not get to 100%, more like 25% or so. That spike is caused by 2-3 Code.exe processes.
Memory usage don't move dramatically.
This happen most of the time when I alt-tab out of the editor (most often to chrome), and come back.
It happen less often when I run `--disable-extensions`. 
With extensions: every 5 minutes or so.
Without extensions: about once per 30 minutes to 1 hour.
My codebase is very small, files are 50 lines max, and not a lot of them. I use a running process in the terminal (git bash), but it happen even if I stop it.

I experienced it at first on 1.18.0-insiders (with more extensions). I didn't tried to disable extensions on that version.

**Comment by alexandrudima** [comment]
@peltsi212 @dbaeumer 
If you experience any sort of lag while typing, which is indicative of lag on the renderer process, we can try to identify the root cause via a CPU profile on the renderer process.

To get a CPU profile of the renderer process:
* Run `F1 > Toggle Developer Tools`
* Go to the three dots burger menu
* Choose `More Tools > JavaScript Profiler`
* Start a new CPU profile
* Do the actions that lead to slowness
* Save the CPU profile to a file and attach it

![kapture 2017-10-21 at 13 02 25](https://user-images.githubusercontent.com/5047891/31851158-30fd860a-b660-11e7-9018-661394adb754.gif)

**Comment by dbaeumer** [comment]
@jberube since you see in contrast to @peltsi212 a CPU spike can you let us know the whole command line of the processes that consume the CPU. Under Windows use the Process Explorer (https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer) to get access to the whole command line doing the following:

- select the process
- execute Properties from the context menu
- copy the command line.

![capture](https://user-images.githubusercontent.com/1931590/31875651-61680bc4-b7cf-11e7-8a20-c9d3d9a298b1.png)

**Comment by jberube** [comment]
After updating from 1.16.1 to 1.17.2 , I don't see CPU spikes anymore, I couldn't get that information in time.

What I previously called a "freeze" problem persists, albeit a little differently, but I've realized that the screen just isn't repainting. I've split the window so it takes half the screen and Chrome takes the other half. Whenever it "freeze", if I type some characters nothing happen, but if I `alt+tab` to another window, what I typed appears instantly. When I come back, sometimes it's still "frozen", sometimes not.

My workaround for now is to `alt+tab` back and forth until I see what I type. It rarely takes more than 3 times.

A detail: before the update to 1.17.2, even the window minimize/maximize/close buttons were unresponsive. It's not the case anymore.

It looks like I was experiencing two bugs at the same time.

What i experience now is pretty much the exact same thing as the OP mentioned. It happen less often, too, even with extension on.

**Comment by peltsi212** [comment]
I have used VSCode every day.
I am also running now VSCode 1.17.2  and I have not seen anymore freeze or lagging during typing.

I did not report different kind of lagging before. This lagging is still there.
How to repeat:
Open javascript file with many hundred lines.
Click on vertical scroll bar.
Keep on pressing with left mouse button.
Drag up and down.
I see that scrolling stops now and then and there is high CPU spike when scrolling stops.
Scroll stops for about one second and then continues.
Screen resolution is HD and VSCode maximized.
If I restore VSCode to 1/3 of screen then lagging during scroll does not exist anymore.

Eslint was disabled during scrolling test.

**Comment by user1713952** [comment]
Hi

I am seeing the same problems, with Python files. Hangs randomly when typing, the resumes and typed text gets written to the screen.
> Windows 64bits
> vscode v 1.17.2
> extensions: (Linting) Python (v0.7.0 Don Jayamanne)
I will try w/o the linter and see what happens.

Cheers
Malek

**Comment by azbatuk** [comment]
Ubuntu 16.04 LTS
VS Code 1.17.2

It freezes a lot. It happens so often that I simply cannot use it. Sometimes a few minutes after I start it, other times longer but it eventually freezes and forces me to restart the computer. I have tried to run it with all extensions disabled (code --disable-extensions) to no avail. This did not happen when I was using it on Windows 10, but on Ubuntu 16.04 LTS it is a freeze fest. I did not notice any specific action that causes it to freeze. It seems completely random.
I think I'll stop using it and check it again after a major update.

**Comment by urbgimtam** [comment]
Was getting a lot of freezes since the August 2017 update on my low spec laptop (i3, 4Gb Ram), specially with Chrome open. Couldn't even open the Task Manager to close the process.
With VS Code update 1.17.2 the lag and the freeze disappeared. Great!

**Comment by peltsi212** [comment]
I installed VS Code 1.18.0 when it came out.
VS Code has now freezed 3 times.
It looks like freeze problem came back.
It looks like VS Code 1.17.2 was better when comparing freeze problem.

**Comment by rogerweb** [comment]
I'm experiencing the same thing. On the Explorer view, simply moving the mouse over the file names is enough to get the freeze/CPU spike/lag. For me it happens when loading the "tool tip" that displays the full path of the file the mouse is over. I'm running with no extensions. I've captured the CPU profile as instructed by @alexandrudima:

[CPU-20171113T163540.cpuprofile.zip](https://github.com/Microsoft/vscode/files/1468065/CPU-20171113T163540.cpuprofile.zip)

**The environment is:**
Intel® Core™ i7-7500U CPU @ 2.70GHz × 4
Intel® HD Graphics 620 (Kaby Lake GT2)
8GB RAM
Ubuntu 17.10
GNOME 3.26

**VSCode is:**
Version 1.18.0
Commit dcee2202709a4f223185514b9275aa4229841aa7
Date 2017-11-08T12:44:48.751Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

Regards

**Comment by xxRockOnxx** [comment]
Mine just freezes randomly. I'm on Ubuntu 17.04 (Gnome). Trying to resist switching back to Sublime.

**Comment by jeffhoye** [comment]
[CPU-20171127T131655.zip](https://github.com/Microsoft/vscode/files/1507065/CPU-20171127T131655.zip)

I'm having the same issue, attached the js cpu profile. Hang while typing about 1ce/10 mins.  Can last 1-25 seconds; very distracting.  It happens very randomly, so it's hard to give you a profile with just the time interval around the freeze.  This one froze for about a second right at the end (though it's not obvious that determine which part was the end from this file).

VSC 1.18.1 (Win 10 x64 32.0GB, i7-4790K 4.0Ghz, 4K display
Plugins:
  Code Outline 0.0.12 (Patryk Zawadzki)
  Go 0.6.67 (lukehoban)
  PHP INtellisense 2.0.1 (Felix Becker)
  Vim 0.10.5 (vscodevim)
  vscode-icons 7.18.1 (Roberto Huertas)

**Comment by jeffhoye** [comment]
It is the Source Control (Git) refresh.  I'm certain.  I have a ton (over 5000) "changed" Git files due to an unusual setup.  I got suspicious today and watched this panel, it always changes a lot after the hang. 
Doing this got rid of the hangs (and unfortunately my ability to use the Git Integration):
```
  "git.enabled": false,
```

If git is enabled, the issue persists (and Source Control does an occasional big refresh) even after I've configured this setting:
```
   "git.autorefresh": false,
```

The docs aren't especially clear but I would assume that is supposed to prevent it checking the disk for git changes as well as the network.  

My prefered setup would be to manually git refresh when I want. 

**Steps to reproduce**
Check out a Git repo with a lot of files.
Add over 5000 bogs files.
Edit a bit and notice intermittent hangs.

I suppose this may also be an interaction with vscode-icons.  

Also, note, my setting for autoSave is: 
```
  "files.autoSave": "off",
``` 

Scope creep: While you're at it, you may want to add a config option for the number of files before triggering the limit warning (disabled by git.ignoreLimitWarning).  I think this value is is hard coded to 5000.

Hope this leads to a fix!  Love VSCode!

**Comment by joaomoreno** [comment]
There is no fixing slow git on Windows, especially from us. We already do preventive work to limit changes to 5000. The `git.autorefresh` setting is there especially for those who want to manually git refresh when they want.

**Comment by sflxn** [comment]
This happens all the time for me.  After about and hour or two of use, it would hang the entire OS.  Used on Ubuntu 16.04, 16.10, and 17.04.  I have formed a habit of trying to close the app when it happens.  However, sometimes, it hard hangs the OS for several minutes, and I don't have the option to close it.  I usually take a break when that happens.  The only extensions I'm using are the Golang extensions.  I'm in the process of looking for a better written editor.  This used to be a good editor, but it has become so unstable over the last year on Linux.

**Comment by xbrny** [comment]
I'm using ubuntu 16.04. For my case, the lagging issue started when I ctrl + click a function after installing PHP intelliSense extension. The issue solved after I uninstall the extension. I start VSCode with `--disable-extensions` option, uninstall the extension, and relaunch it normally.
