### ISSUE TITLE
Tasks should support specifying the output encoding 

### ISSUE THREAD

**Issue by DongkunLee** [Microsoft/vscode#3550]
I think it's related to some global language problem. 

The output message is broken like this 

'luac'��(��) ���� �Ǵ� �ܺ� ����, ������ �� �ִ� ���α׷�, �Ǵ�
��ġ ������ �ƴմϴ�.

P.S> My environment is Win10 Ko(Korean version) 

https://onedrive.live.com/redir?resid=73F0A5AA67A0D48F!212183&authkey=!ACjcDNvjj7PjRmY&v=3&ithint=photo%2cpng

**Comment by joaomoreno** [comment]
For sure we're blindly converting to/from `utf8` somewhere...

**Comment by f111fei** [comment]
+1 . hope to fix as soon as possible

**Comment by shikouzhong** [comment]
+2. It's really a boring bug, hope to get it down in the next release version. 🎱 
Now I use the internal console instead of tasks. :-(

**Comment by dbaeumer** [comment]
Please see https://github.com/Microsoft/vscode/issues/15179. The idea here to move forward is to execute tasks in the terminal instead in its own output channel.

**Comment by eqr** [comment]
Have the same problem Win10/Russian MsBuild. Really annoying.

**Comment by dbaeumer** [comment]
Agree. The plan forward here is to use the integrated terminal to run tasks. This will make this work and even support input and ANSI control characters

**Comment by hia3** [comment]
Why is it a "feature-request"? Not garbling an output is not a feature. I think it should be "bug" and "important".

**Comment by EternalPhane** [comment]
In __tasks.json__:
use
```json
"command": "cmd",
"args": ["/c chcp 65001 >nul && mingw32-make"]
```
instead of
```json
"command": "mingw32-make"
```
and everything seems to work fine.

> compiling...
main.cpp
e:\projects\c++\vscode_test\main.cpp(247): error C2143: 语法错误: 缺少“;”(在“return”的前面)
mingw32-make: *** [main.obj] Error 2
Makefile:37: recipe for target 'main.obj' failed

**Comment by dbaeumer** [comment]
@EternalPhane thanks for this. Actually I am working on support for running tasks in the integrated terminal which should make the encoding problem go away.

**Comment by gyuhyeon** [comment]
@dbaeumer update on this feature would be much appreciated. Not being able to figure out what the error message is makes the task feature almost unusable, thanks.

**Comment by dbaeumer** [comment]
@gyuhyeon this will be addressed by using the terminal as the execution engine for tasks. You can alreadz opt into using the terminal by adding `"runner": "terminal"` to your tasks.json

**Comment by rajannpatel** [comment]
"runner":"terminal" does not appear to work anymore, I have had success setting the ENV before my command. I am on a Mac.

I was trying to run Jekyll.

`"command": "export LANG=en_US.UTF-8 && export LC_ALL=en_US.UTF-8 && jekyll serve --watch"`

**Comment by dbaeumer** [comment]
@rajannpatel strange, `"runner": "terminal"` is still supported. You can also switch to tasks version 2.0.0. Can you provide a tasks.json file which demonstrates the behavior.

**Comment by mmitang** [comment]
after update to .net core 2.0
the problems window shows messy code 
the output window also shows messy code like this:

e:\Work\Server\LoginServer\LoginServer\LoginServer.csproj : warning NU1701: Package 'Nancy.Owin 2.0.0-clienteastwood' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project.
���� .NET Core �� Microsoft (R) ��������汾 15.3.409.57025
��Ȩ����(C) Microsoft Corporation����������Ȩ����

**Comment by doggy8088** [comment]
I have a workaround for this issue here:
https://gist.github.com/doggy8088/ca1dd1fff42e0dd4f0ce175a460feae5/revisions

**Comment by srgmatveev** [comment]
Thanks!
export LC_ALL=en_US.UTF-8 (for Russian export LC_ALL=ru_RU.UTF-8) helped me on Debian Linux added in file .bashrc

**Comment by dbaeumer** [comment]
I am closing this issue since this can now be control using normal Terminal setups in task 2.0.0. I also wrote some doc explaining how this is best used here: https://github.com/Microsoft/vscode-docs/blob/vnext/docs/editor/tasks.md#changing-the-encoding-for-a-task-output

I will close the issue. Please reopen a new issue against the current support if it is not satisfactory for you.
