### ISSUE TITLE
VS Code Crashing

### ISSUE THREAD

**Issue by justemoilouise** [Microsoft/vscode#35509]
VSCode has been crashing since last update. I'm using the latest version (1.16)

![image](https://user-images.githubusercontent.com/6330131/31105664-72b1768e-a818-11e7-9f5e-1704832c9302.png)

**Comment by chrmarti** [comment]
Are there any steps that reproduce this? Does it happen immediately after startup? Does it always happen?

**Comment by justemoilouise** [comment]
It just happens while I'm doing some code, with gulp and node running. And, yes, it happens often.

**Comment by chrmarti** [comment]
Could you check if this still happens with the latest insiders build? https://code.visualstudio.com/insiders/

**Comment by justemoilouise** [comment]
Doesn't seem to happen with the latest insiders build.

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by chrmarti** [comment]
Could this be #34301?

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/34301
