### ISSUE TITLE
[debug] DebugConfigurationProvider.resolveDebugConfiguration does not get invoked on for the first debug session.

### ISSUE THREAD

**Issue by vadimcn** [Microsoft/vscode#35507]
VSCode Version: 1.17.0-insider, date: 2017-09-29T20:32:46.808Z

Even though my debug extension registers a `DebugConfigurationProvider` upon activation (and it *does* activate on `onDebug:<myExtensionType>` - I can see this under extension debugger), VSCode does not invoke the `resolveDebugConfiguration` method, but instead goes straight to command specified in package.json's `adapterExecutableCommand`.  If the latter isn't provided it just says "Cannot determine executable for debug adapter '{0}'.".

This happens for the first debug session only; for the second one everything works as advertised.

**Comment by isidorn** [comment]
@vadimcn thanks for reporting this however this is expected behavior. Your extension should activate on `onDebug` activation event, not on `onDebug:<myExtensionType>` since this is deprecated.
More about this can be found here
https://github.com/Microsoft/vscode/issues/33258
https://github.com/Microsoft/vscode/issues/33803
https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/v1_17.md#debug-contributions-in-packagejson
