### ISSUE TITLE
ES6 Promise leaks into base/common

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#35516]
We have `es6-promise` typings which means everywhere in our codebase the es6 promise is available. In a few places this has now spread... We have two options

* go backwards and use WinJS.Promise everywhere
* go forwards and add a polyfil for the native Promise

**Comment by joaomoreno** [comment]
We can't remove this anymore since `@types/keytar` depends on it.

So, let's move forward. @jrieken If you have passion for this please take up the issue.

**Comment by jrieken** [comment]
⏩ let's find a good polyfill for the native Promise. The plan is the following

1. We add a polyfill for the native promise
2. We allow the usage of `Promise` in our code
3. We add some on-the-side-utils that WinJS has, like `Promise.timeout` or `Promise.done`
4. Folks are free to slowly (step by step) move to native promises. *

*This isn't as easy as replacing construor-calls because WinJS promises have semantic differences, e.g. calling `resolve` synchronously from a promise-ctor resolves the promise synchronously.

**Comment by alexandrudima** [comment]
The problem is IE11 which doesn't have native promises. If we include a polyfill, can we please write one on top of winjs.Promise, rather than one from scratch. My concern is us shipping the standalone editor with two Promise implementations.

Once we eliminate the direct usage of winjs.Promise, we can go to an off-the-shelf polyfill.

Please also don't break the standalone editor. i.e. please put in place a polyfill first and then begin using the native promises everywhere you wish.

**Comment by jrieken** [comment]
> please put in place a polyfill first and then begin using the native promises everywhere you wish.

Yeah, that's what this issue/bug was originally about. It has already happened and now we need to make a move...

**Comment by joaomoreno** [comment]
Awesome stuff @jrieken! Good job!
