### ISSUE TITLE
Allow terminal environment variables to be unset via terminal.integrated.env.windows

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#35586]
Context: https://github.com/Microsoft/vscode/issues/35550

```js
  "terminal.integrated.env.windows": {
    "LANG": null
  },
```

This follows the plan set forward for setting the env in the extension API too, see https://github.com/Microsoft/vscode/issues/20446#issuecomment-314267087 and https://github.com/Microsoft/vscode/pull/30352

**Comment by lifez** [comment]
@Tyriar I would do this. Could you recommend way to unset env

**Comment by Nazeehe** [comment]
Hmm... looking further at this, I can see that there is this option:

// Controls whether locale variables are set at startup of the terminal, this defaults to true on OS X, false on other platforms.
 "terminal.integrated.setLocaleVariables": false,

Looking at the code, I don't think that setting this to false does what the comment says. Setting this to false, as per the code, will simply fallback to setting the LANG env variable to en_US.UTF-8 which is probably not the intended behavior?

**_at this point, locale is undefined since the variable above is set to false_**
env['LANG'] = TerminalInstance._getLangEnvVariable(locale);

private static _getLangEnvVariable(locale?: string) {
		const parts = locale ? locale.split('-') : [];
		const n = parts.length;
		if (n === 0) {
			// Fallback to en_US to prevent possible encoding issues.
			return 'en_US.UTF-8';
		}
seems like maybe the code should be:

if (locale)
{
       env['LANG'] = TerminalInstance._getLangEnvVariable(locale);
}

Just how I interpreted the code/comment :)

**Comment by Tyriar** [comment]
@Nazeehe nice catch, that is indeed a bug. I've reopened https://github.com/Microsoft/vscode/issues/35550 to fix that. This issue will remain open as it's a useful request still 😄

**Comment by Tyriar** [comment]
This is fixed, I've changed my mind on being able to unset `$LANG` though, the `terminal.integrated.setLocaleVariables` setting should be used instead.
