### ISSUE TITLE
TypeScript version selector can get into bad state after deleting workspace root

### ISSUE THREAD

**Issue by felixfbecker** [microsoft/vscode#35592]
- VSCode Version: Code - Insiders 1.17.0-insider (81fc22ec957de26d2bf6aada3f16f04e0164741c, 2017-10-03T22:47:28.178Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.10.1
vscode-wakatime|Wak|1.1.16
vscode-icontheme-nomo-dark|be5|1.3.2
tslint|eg2|1.0.9
php-debug|fel|1.11.1
php-intellisense|fel|1.5.1
java|red|0.11.0
sourcegraph|sou|1.0.9

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Add three roots `removed`, `notremoved` and `notremoved2` with `typescript` installed
2. Select a typescript version installed in the `removed` folder
3. Remove the folder `removed`

My workspace file after that looks like this:
```json
{
	"folders": [
		{
			"path": "removed"
		},
		{
			"path": "notremoved"
		},
		{
			"path": "notremoved2"
		}
	],
	"settings": {
		"typescript.tsdk": "removed/node_modules/typescript/lib"
	}
}
```

Note how the setting still points to the `removed` folder.

Now everytime that workspace is opened you get this error:

![image](https://user-images.githubusercontent.com/10532611/31193814-0a321bc6-a8fa-11e7-9b26-16e856101a83.png)

Notice how it combines `removed` and `notremoved`: `/Users/felix/notremoved/removed/node_modules/typescript/lib`

The same weird path combination now happens in the version selector:

![image](https://user-images.githubusercontent.com/10532611/31193997-9877177e-a8fa-11e7-8ede-a126aae76716.png)

Reproduces without extensions: Yes

**Comment by babakks** [comment]
I'd take this.

**Comment by babakks** [comment]
I tried to reproduce the issue, but had no chance. Although I could see the VS Code's error message, but there's no sign of wrong path names. Actually, everything seemed fine. Since it's quite a long time after the issue was first submitted, I guess it was resolved at some point and is not the case anymore.

@felixfbecker However, I listed the steps to make sure I've followed the right way.

### Steps
This is what I tried on VS Code v1.36.0-insider, on Windows 10 (x64):
1. Created three directories: `removed`, `notremoved` and `notremoved2`.
2. Added empty `.ts` files, named `dummy.ts`, below the created directories.
3. Installed `typescript` in all three with v2.5.0 in `removed` and the `latest` in `notremoved` and `notremoved2`.
4. Opened VS Code with no workspace/working directory.
5. Added the directories to the clean workspace (using "File" > "Add Folder to Workspace...".)
6. Opened `dummy.ts` from `removed` folder in the editor.
7. Clicked on the TypeScript version on the statusbar (at bottom-left), which was already set to default,  v3.5.1.
8. Selected the "Use Workspace Version 2.5.0" from the quick pick, which in turn changed the active TypeScript version to 2.5.0.
9. Saved workspace in the parent directory (where those three folders reside) and quit the VS Code. The workspace file is saved as follows:

```json
{
	"folders": [
		{
			"path": "notremoved"
		},
		{
			"path": "notremoved2"
		},
		{
			"path": "removed"
		}
	],
  "settings": {
    "typescript.tsdk": "removed\\node_modules\\typescript\\lib"
  }
}
```

10. Deleted the `removed` directory.
11. Opened the workspace file with VS Code.
12. Clicked on one of `dummy.ts` files to open it. The notification below popped up:
![image](https://user-images.githubusercontent.com/36728931/59122762-d090be00-8970-11e9-9bcf-fe5fa08d4000.png)

13. Clicked on the TypeScript version on the statusbar (which is now reverted to 3.5.1) to pick another version. This is the quick pick list that was shown:
![image](https://user-images.githubusercontent.com/36728931/59122837-0afa5b00-8971-11e9-9c32-62bf43158d77.png)

14. Chose one of `notremoved` or `notremoved2` and the VS Code correctly switches to the selected version.

15. Saved the workspace and quit the VS Code. This is how the workspace file looks:

```json
{
	"folders": [
		{
			"path": "notremoved"
		},
		{
			"path": "notremoved2"
		},
		{
			"path": "removed"
		}
	],
  "settings": {
    "typescript.tsdk": "notremoved\\node_modules\\typescript\\lib"
  }
}
```

**Comment by mjbvz** [comment]
@felixfbecker  Can you please let us know if you can still reproduce this issue
