### ISSUE TITLE
Sort recently opened files by recency after I start typing

### ISSUE THREAD

**Issue by borekb** [microsoft/vscode#35610]
In quick open (`ctrl+p`) the recently opened files are sorted by recency only until I start typing, then scoring is used instead (only when two files get the same score, recency is used again, see https://github.com/Microsoft/vscode/issues/20546#issuecomment-334378269).

This is unpleasant on repositories with many files of the same name, for example, we have many READMEs in our monorepo and it's unintuitive why filtering in the recently opened list should change the sort order, or in a bad case, move the item completely out of sight:

![image](https://user-images.githubusercontent.com/101152/31215164-c3e961b4-a9ae-11e7-9dc5-708e5d4cf0f8.png)

![image](https://user-images.githubusercontent.com/101152/31215202-e4c3fe4e-a9ae-11e7-9243-90bd3f2d54fd.png)

I think the natural behavior would be just to sort by recency in this list.

Related issues:

- Unintuitive result scoring with Ctrl-P in recent history #20546
- Recently opened files is just a bucket and not sorted by recency #31591

**Comment by olitomas** [comment]
This issue is INCREDIBLY annoying and affects almost all users many many times during each day. Please add this to the backlog 🙏🏻

**Comment by acidofil** [comment]
+1

**Comment by bpasero** [comment]
https://github.com/microsoft/vscode/commit/72a381699f549b3f1c7c38b2b9a6d9a1de06f603 added a new setting `"search.quickOpen.history.filterSortOrder": "recency"` that allows to strictly sort by recency in the history list. The default remains to sort by filter relevance.

**Comment by olitomas** [comment]
Maybe I am misunderstanding the solution but In my opinion this should be a mix of both. I.e in the example given the search result list should be exactly like it is apart from the recently opened /user-portal/client/README.md being at the top.

With that settings I don't see anyone needing a settings change as I cant imagine anyone wanting to change that behaviour.

Another option would have been to do it like it is done in Sublime. There they don't change the list order (like VSCode does now). But instead they auto highlight the most recently opened file in the search results list. I actually find that solution quite elegant after looking into it :)

I any case I am happy to see something being done about this issue, good job! 👏

**Comment by bpasero** [comment]
@olitomas to clarify, quick search for files in VSCode exists of 2 buckets: recently opened and all other files of the workspace that were not recently opened. Typing to search will show results from recently opened instantly and search results later (because they need to go do to disk and do the actual search).

Both buckets are sorted differently, but with this change more as you would expect: unless sorting by recency is enabled, the results in recently opened are sorted like the file results (they still appear on top though because they come first).

With this new option you can strictly sort by how recently you opened a file. I think this helpful in exactly the scenario where you type the filename of a file that has many entries with the same name.

**Comment by bpasero** [comment]
**Verification**
* configure "search.quickOpen.history.filterSortOrder": "recency"
* verify that when you start typing in quick open, the results show in the same order for the "recently opened" as they appear when nothing is typed
