### ISSUE TITLE
Search result for "UTF-8 with BOM" files shifted on first line by a character

### ISSUE THREAD

**Issue by Ranger1230** [Microsoft/vscode#35633]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
coldfusion|ili|0.0.11
Angular2|joh|2.7.0
csharp|ms-|1.12.1
sort-imports|pet|2.4.0
autoimport|ste|1.2.2
vsc-angular-cli|web|1.0.0

---

Steps to Reproduce:

1. Open a folder with a ASP.NET project in it
2. Perform a find and replace entering "Block.FeatureCard" to the find and "Block.Cards" for the replace
3. Click the replace all button
4. Look in the cs files and see it worked fine, but look in the cshtml files and notice that a line like "@using NewProj.Blocks.FeatureCard.Simple" is replaced with "@using NewProj.BBlocks.CardsSimple". Notice the B is duplicated and the '.' before "Simple" is missing.

Note: This does not seem to happen if you manually replace them one by one in the find pane. Only seems to happen when clicking replace all.

Reproduces without extensions: Yes

**Comment by thomazmoura** [comment]
VSCode Version: Code 1.17 (be377c0faf, 2017-10-04T23:44:50.318Z)
OS Version: Windows 10 Home x64 10.0.15063

I've seen that same behaviour before on .cs files and managed to get a print of it this time:
![image](https://user-images.githubusercontent.com/5599621/31303855-5d0cffd0-aaeb-11e7-971e-d54f6010161a.png)
As you can see from the print the first line will get changed to "using InsertSolutionNamespaceHere.Domain.Repositorios;" to "using ISolutionNamespaceDomain.Repositorios;" instead of "using SolutionNamespace.Domain.Repositorios;" as expected. The line 6 will be changed properly though.

If it helps the code of the print is from the following commit: ([https://github.com/thomazmoura/Generator.DotNetSolution/commit/4bf36053e16b7d4520ef211d555fcaec4106558c](https://github.com/thomazmoura/Generator.DotNetSolution/commit/4bf36053e16b7d4520ef211d555fcaec4106558c)) and the replace all parameters was from "InsertSolutionNamespaceHere" to "SolutionNamespace".

**Comment by roblourens** [comment]
Thanks for the example, I can repro! This is because the file has a BOM, and our search tool counts that as a character in the first line.
