### ISSUE TITLE
Can't close vscode while integrated terminal is focused

### ISSUE THREAD

**Issue by hugoj-goncalves** [Microsoft/vscode#35646]
- VSCode Version: 1.17.0
- OS Version: Win10 Pro

Steps to Reproduce:

1. Open integrated terminal
2. Change the focus to the integrated terminal window
3. Press Alt+F4

Reproduces without extensions: Yes

Expected behaviour: VsCode Window should close.
Current behaviour: Nothing happens.
Tested terminals: Git Bash and PowerShell

I couldn't find a command *name* to use in *commandsToSkipShell*.

**Comment by anchepiece** [comment]
Confirmed on:
- VSCode Version: 1.17.2, 1.18 (insiders)
- OS Version: Windows 7 x64

Works as expected on ubuntu, `Alt+F4` while in the terminal will close the main vscode window.
Any pointers on testing winpty-agent.exe cc: @parkovski?  It should be possible to intercept `alt+f4` call before it gets to the terminal, perhaps a quick program to test what the console is receiving.

Possibly related to: https://github.com/Microsoft/vscode/issues/9347?

**Comment by parkovski** [comment]
There's a program in the `misc` directory of a winpty checkout - `ShowConsoleInput.cc`, which shows that winpty is receiving the `Alt+F4` for me - it probably shouldn't be receiving it at all, which would be an issue of VSCode not filtering it.

The workaround right now is to assign `Alt+F4` to `workbench.actions.quit` in your keybindings, and then add `workbench.action.quit` to `terminal.integrated.commandsToSkipShell`.

**Comment by anchepiece** [comment]
Awesome feedback @parkovski and I agree, `Alt+F4` shouldn't be received by the terminal at all. Going to look at capturing this from the parent.

**Comment by hugoj-goncalves** [comment]
@parkovski `workbench.action.quit` is a little too drastic I think.
It closes all the visual studio code windows instead of just the current one.

**Comment by parkovski** [comment]
Ok, I see there's a `closeActiveWindow` command, so that's probably a better fit. Either way, the real fix for this will just filter `Alt+F4` from the terminal and then it should just take the default action.

**Comment by Tyriar** [comment]
I believe the issue here is that on Windows the terminal eats the alt+f4 keybinding. The only way currently to workaround this is to add commands to the whitelist `terminal.integrated.commandsToSkipShell`. I'm not sure alt+f4 is bound to anything though as it's a system thing.

I'm thinking just special casing this on Windows to always force skipping? Opening this up for PRs, here is the relevant code https://github.com/Microsoft/vscode/blob/40bd353361206f45f176c1f8a27943a763111690/src/vs/workbench/parts/terminal/electron-browser/terminalInstance.ts#L315
