### ISSUE TITLE
Providing different icon for the TouchBar

### ISSUE THREAD

**Issue by Krzysztof-Cieslak** [microsoft/vscode#35641]
TouchBar is completely different way of providing command from the UX point of view - it's not clearly connected to the given part of editor (what suggest context, and usage for normal commands icons, and there is no easy way to get tooltip describing what icon mean.  Also, the format of the field on TouchBar is different than usual.

I think it would be good idea to provide separate icon for the TouchBar instead of always reusing the icon that's defined for other parts of the UI, as the icon in TouchBar has different requirements from the ones put next to TreeView title, or anywhere else

**Comment by baronfel** [comment]
As an example of what this looks like, here I can't change the size of the two debugging commands I want to show, and I can't make different titles for the `F#: New Project` and `FSI: ` commands, to make them shorter due to real estate.

![img_20171005_150030](https://user-images.githubusercontent.com/573979/31250619-f9df9752-a9e0-11e7-82f2-80d3beea917b.jpg)

**Comment by Krzysztof-Cieslak** [comment]
And those green icons totally makes sense for us when we put in TreeView title:
![image](https://user-images.githubusercontent.com/5427083/31251126-39161450-aa1d-11e7-9c4c-c1ae3b3fbf07.png)

**Comment by bpasero** [comment]
I brought this up during standup and I think the suggested workaround was to contribute a command only for the touch bar so that you can provide different icons, but I let @jrieken confirm.

**Comment by jrieken** [comment]
Yes, our current menu design is to define UI for a command and not for a menu item. "Define UI" means the label, icons, category etc is per command and not per showing. I still think it is a good rule because a command that for instances saves files should always have to the same label and icon, otherwise users might have a hard time understanding what it does. 

On the other hand I understand the challenge with the touch bar and I am open for suggestions but not yet ready to water-down the definition of a command and a menu item.

**Comment by felipenmoura** [comment]
Can I disable the "built in" buttons in the touchbar?
I've published the plugin "nasc vscode touchbar" and if the user enables more than 6 buttons, the bar disappears (it breaks the "layout" I guess).
This way, I could add those buttons as options in our touchbar and users would be able to enable/disable them as needed.
Even better if we could disable separately the "< >" and "debug" buttons. More options for the user :)

**Comment by DanTup** [comment]
@baronfel how did you get icons to show up in the touchbar at all? I have a command with an Icon:

```js
{
	"command": "flutter.hotReload",
	"title": "Hot Reload",
	"category": "Flutter",
	"icon": {
		"dark": "media/commands/hot-reload.svg",
		"light": "media/commands/hot-reload.svg"
	}
},
```

However the touchbar just shows the text:

<img width="1085" alt="Touch Bar Shot 2019-03-11 at 9 59 51 am 3" src="https://user-images.githubusercontent.com/1078012/54115746-06132300-43e5-11e9-8a64-43f91ea4c582.png">
