### ISSUE TITLE
Refreshing of changed files on source control tab don't triggers automatically

### ISSUE THREAD

**Issue by evilj0e** [Microsoft/vscode#35699]
- VSCode Version: 1.17.0
- OS Version: macOS Sierra 10.12.6

Steps to Reproduce:
1. Open a project with files
2. Change several files from a project
3. On source control tab nothing changes. To refresh and see what changed you should go and press refresh trigger.

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
This is a file watcher problem.

**Comment by bpasero** [comment]
@evilj0e 
VS Code is using different file watching strategies depending on your OS and your setup. 

**First thing to check:**
* [ ] I verified that the issue still reproduces in our insiders version (https://code.visualstudio.com/insiders/)
* [ ] I verified that this issue is happening outside of a `node_modules` folder. Our file watcher ignores this folder!

**To find out more about this issue, please first answer this:**
* [ ] What OS are you on
* [ ] Does this happen from an empty workspace, a single-folder workspace or a multi-root workspace?
* [ ] Do you have `files.useExperimentalFileWatcher: true` configured in settings?
* [ ] What is your configured `files.watcherExclude` setting?

**Then please answer the following depending on your setup:**
* [ ] It reproduces with any folder or workspace you open
* [ ] The files/folders you open are on your local disk and not on a network share nor a UNC drive
* [ ] The files/folders you open are not behind a symbolic link
* [ ] The folder(s) opened use the exact same casing as they are on disk
* [ ] It reproduces when I make a change to the file from another VS Code window (either from the editor or the file explorer)

**Then please attach the output of our development console**
* run `code --verbose` from the command line
* perform the action that causes you to not see the file change in VS Code
* attach the output from the console (`Help` > `Toggle Developer Tools` > `Console`)

Thanks for taking the time to fill out this questionnaire.
