### ISSUE TITLE
indents after multiline comment incorrect

### ISSUE THREAD

**Issue by john-coloccia** [microsoft/vscode#35709]
- VSCode Version: 1.16.1
- OS Version: Windows 10

Steps to Reproduce:

1. create a multiline comment
2. hit enter twice. The first line after the comment is indented properly. the second enter indents to the indent level of the comment, which is usually incorrect.

example:
```
/*
 *
 *
 */
first enter leaves me here

/*
 *
 *
 */

 hit enter twice, and it indents me here, underneath the asterisk, which is off by a space.
```
Ideally, if I'm not actively typing in a multiline comment, I would want auto-indent to completely ignore comments altogether as if they're not even there.

**Comment by garyking** [comment]
I created a separate issue for this before finding this issue. Here is a relevant GIF I made:

![vsc-indent](https://user-images.githubusercontent.com/343940/38476699-3060692c-3b7d-11e8-8208-cd9e7614908f.gif)

**Comment by rebornix** [comment]
This is due to the limited architecture (regex based indentation rules and only support limited code styles), we may want to consider using formatters if they exist for indenation adjustment (if interested, we can discuss in https://github.com/microsoft/vscode/issues/19847).

For this particular issue, if the indentation rules are leading to more trouble than having no auto indent, you can set `editor.autoIndent` to `advanced` to disable the regex based indentation adjustment. As we don't have an easy good-enough fix for it, we close it for now and explore better solutions through issues like (https://github.com/microsoft/vscode/issues/19847 and https://github.com/microsoft/vscode/issues/34621).
