### ISSUE TITLE
when I am trying to copy and paste a variable, the variable which was deleted previously by me gets pasted instead of the copied object

### ISSUE THREAD

**Issue by digish777** [Microsoft/vscode#35742]
when I am trying to copy and paste a variable, the variable which was deleted previously by me gets pasted instead of the copied object.

step1: 
copy and object
step 2:
delete any variable:
at this stage to the copy basket in the memory, the deleted variable gets in .

step 3: 
try to paste the copied object, the deleted variable gets pasted. 

this causes head ache for me. please try to remove this bug.

**Comment by chrmarti** [comment]
@digish777 What extensions are you using (`code --list-extensions`)? Does this reproduce without extensions (`code --disable-extensions`)?

**Comment by digish777** [comment]
I am using, Atom Dark Theme, Auto Close Tag, Beautify, Intellisense for CSS Class Name, Javascript Console Util, Lorum Ipsum, Toggle Codelens.

I have not tried with them in the disabled mode.

**Comment by digish777** [comment]
this issue does not happen by default or what?

**Comment by alexandrudima** [comment]
@digish777 I cannot reproduce given your steps.

Here are the detailed steps I tried on OSX (since you don't mention your OS):
* I create a file with the contents:
```
foo
baz
bar
```
* I select `foo` by double clicking
* I right click and choose "Copy"
* I select `baz` by double clicking
* I press <kbd>Delete</kbd>
* I right click and choose "Paste"
* I get `foo` inserted

![kapture 2017-10-23 at 17 34 39](https://user-images.githubusercontent.com/5047891/31898072-7b158a80-b818-11e7-9fb5-b1a7a5134059.gif)

Can you perhaps give more precise steps and perhaps mention your OS and VS Code version ? In the product, you can choose  `Help > Report Issues` and a template will be provided with your OS and VS Code version. You can copy paste that information here and perhaps provide more detailed steps.
