### ISSUE TITLE
"Unable to open" on file copy-paste

### ISSUE THREAD

**Issue by artaommahe** [Microsoft/vscode#35743]
- VSCode Version: 1.17.0
- OS Version: Windows 10

Steps to Reproduce:
1. copy file in explorer
2. paste anywhere
3. See error `Unable to open 'package.1.json': File not found (...).`

Reproduces without extensions: Yes

**Comment by dlong500** [comment]
I'm experiencing (I believe) the same issue on the latest insider build (more details below).  It doesn't have anything to do with extensions, as the same thing happens with extensions disabled.

- VSCode Version: Code - Insiders 1.18.0-insider (af6ca44db81f5186d3104226c8e76e026789ce20, 2017-10-06T05:26:16.770Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.3.2
githistory|don|0.2.3
prettier-vscode|esb|0.24.0
vscode-console-wrapper|fab|0.4.0
debugger-for-chrome|msj|3.3.1
vscode-icons|rob|7.14.0



---

Steps to Reproduce:

1. Open a folder in vscode
2. copy one existing file in the Explorer pane and paste it anywhere
3. vscode _does_ duplicate the file, but responds with the following notification:
`Unable to open 'test.js': File not found (file://c:/local/code/test/myfolder/test.js).`
4. It appears to be OK after dismissing the message, but there sometimes are some wonky editor issues (like showing `deleted from disk` next to the editor name or even some stranger issues that I haven't been able to reproduce yet)

Of course the whole issue is disconcerting, because I get worried something is going to end up corrupting or deleting an important file due to the program getting into some type of inconsistent state when managing files/editors.  See below for some screenshots.


Reproduces without extensions: Yes

![image](https://user-images.githubusercontent.com/430481/31304919-b4119164-aafb-11e7-8d39-96d21bc1e527.png)

![image](https://user-images.githubusercontent.com/430481/31304927-cf2e10e4-aafb-11e7-95a2-4eefc4a661aa.png)

**Comment by xtbe** [comment]
+1 - Same issue here both in regular as inside version

**Comment by andrew-bickerton** [comment]
+1 on version 1.17.0
Only showed up since last published release

**Comment by dlong500** [comment]
Interestingly enough, I'm not getting the error on the very latest build (e29c517386fe6f3a40e2f0ff00effae4919406aa, 2017-10-09T05:26:14.557Z).

I've browsed through the commits over the past three days and don't immediately see what might have resolved the issue.  Was this directly addressed or did some other change have a positive side effect?

**Comment by bpasero** [comment]
@isidorn did you fix something here?

**Comment by isidorn** [comment]
Yes I have fixed something in this area.
I believe this issue should no longer happen. Please let me know if you see it in latest insiders, also the stable recovery build in the next couple of days will contain the fix.

**Comment by xtbe** [comment]
Doesn't appear anymore for me on 
![image](https://user-images.githubusercontent.com/909796/31376232-8550bab6-ada4-11e7-9ea9-4fa446517d76.png)

**Comment by genfa** [comment]
Vs updated today, and the issue is away 😊
