### ISSUE TITLE
explorer.newFile/Folder opens the file under the cursor on a preview editor.

### ISSUE THREAD

**Issue by itiut** [Microsoft/vscode#35859]
- VSCode Version: 1.17.0 be377c0faf7574a59f84940f593a6849f12e4de7
- OS Version: macOS Sierra 10.12.6

Steps to Reproduce:

1. Add keyboard shortcuts for `explorer.newFile` and `explorer.newFolder` (e.g. <kbd>a</kbd> and <kbd>shift+a</kbd>).
    ```
    {
      "key": "a",
      "command": "explorer.newFile",
      "when": "explorerViewletVisible && filesExplorerFocus"
    },
    {
      "key": "shift+a",
      "command": "explorer.newFolder",
      "when": "explorerViewletVisible && filesExplorerFocus"
    },
    ```
    
2. Close all editors.
3. Show explorer (<kbd>shift+cmd+e</kbd>) and move the cursor to a file.
4. Run `explorer.newFile` or `explorer.newFolder` command. Then, the file under the cursor is opened on a preview editor.

Reproduces without extensions: Yes

**Comment by isidorn** [comment]
I acknowledge this issue and the explorer has always behaved like this.
The problem here is that the explorer get focus due to the newFile action and whenever explorer gets focus it always opens the focused element [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/browser/views/explorerView.ts#L300)

I think this is a limiation we can live with. 
fyi @bpasero

**Comment by isidorn** [comment]
Actually dup of https://github.com/Microsoft/vscode/issues/35858
