### ISSUE TITLE
Make Ctrl+P, Shift+Enter open new preview tab and keep current one (if exists in current editor group) premament as for editing

### ISSUE THREAD

**Issue by mtsh1000** [Microsoft/vscode#35867]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by dmonay** [comment]
VSCode Version: 1.17.2
OS Version: MacOS 10.12.6

This has proven to be a serious impediment. Cmd+P is now essentially useless b/c it will just open in the same tab (unless I have unsaved changes in current tab). So to open a new file I have to find it in menu on left and **triple-click**, because single- or double-clicking opens the file in same tab. This was not the behavior in the last major release (1.16).

Let me know if I can provide any further details.

**Comment by smuuf** [comment]
I'm not sure I completely understand the issue, _but_, isn't this something...

```
    "workbench.editor.enablePreview": false,
```

...would solve?

**Comment by dmonay** [comment]
That does seem to solve it. Thank you!

**Comment by smuuf** [comment]
No problem. :) I remember I too was struggling with this *"annoying tabs stuff"* a while ago and this was the option that solved my frustration with it.
