### ISSUE TITLE
syntax highlighting is lost after call to handlebars helper with string parameter inside script block

### ISSUE THREAD

**Issue by Jusys** [Microsoft/vscode#35934]
- VSCode Version: 1.17.0 (issue present in both 32bit and 64bit)
- OS Version: Windows 7 32bit, Windows 10 64bit

Steps to Reproduce:

1. Create handlebars file;
2. Type some html code;
3. Create script block with function;
4. Inside function make a call to handlebars helper with string parameter;
5. After this syntax highlighting will be lost;

![image](https://user-images.githubusercontent.com/30110941/31359399-832c9b30-ad52-11e7-8214-df04c0f473d2.png)
![image](https://user-images.githubusercontent.com/30110941/31359421-9926dd4c-ad52-11e7-9c59-df8aa361a45e.png)

If call to helper is without string parameter, everything is ok:
![image](https://user-images.githubusercontent.com/30110941/31359437-acfcbb70-ad52-11e7-938d-7b85bc50a3f3.png)
![image](https://user-images.githubusercontent.com/30110941/31359454-bf384426-ad52-11e7-9202-b319d37fde5e.png)

Reproduces without extensions: I have no extensions installed

**Comment by aeschli** [comment]
The problem is that the handlebar grammar uses the 'source.js' grammar for embedded code. That's not really correct due to the templates. The grammar that we use in VSCode doesn't handle the {{{ helper 'param'}}} and gets stuck in a rule (FYI @sheetalkamat) . It's a weakness of TextMate that it doesn't have a proper embedding story and a problem in the embedded code can ruin the colouring of the rest of the file
IMO the right approach is for the handlebars grammar to not include source.js, but have included simple highlighting rules for embedded code, e.g. do keyword, comment and strings highlighting.

**Comment by aeschli** [comment]
This issue was moved to daaain/Handlebars#99

**Comment by Jusys** [comment]
aeschli: Thank you for clarification
