### ISSUE TITLE
Reformatting after multi-line statements in JS and TS

### ISSUE THREAD

**Issue by jtlapp** [Microsoft/vscode#35933]
- VSCode Version: 1.16.1
- OS Version: Mac OS 10.12.6

Steps to Reproduce:

1. Open a bracketed block.
2. Indent subsequent lines of a multi-line statement in Javascript or Typescript.
3. Close the bracketed block.
4. Hit return to start a new line.

Reproduces without extensions: Yes

Enter the following Javascript, leaving the cursor at the vertical bar:

```javascript
    if (test) {
        callSomething(first, second, third, fourth, fifth, sixth, seventh,
            eighth, ninth, tenth);
    }|
```

Then hit return. I get this:

```javascript
    if (test) {
        callSomething(first, second, third, fourth, fifth, sixth, seventh,
            eighth, ninth, tenth);
        }
        |
```

If you instead start with the following, as is my convention:

```javascript
    if (test) {
        callSomething(first, second, third, fourth, fifth, sixth, seventh,
                eighth, ninth, tenth);
    }|
```

You get this:

```javascript
    if (test) {
        callSomething(first, second, third, fourth, fifth, sixth, seventh,
                eighth, ninth, tenth);
            }
            |
```

The same thing happens if the cursor is within the bracketed block. From here:

```javascript
    if (test) {
        callSomething(first, second, third, fourth, fifth, sixth, seventh,
            eighth, ninth, tenth);
|   }
```

Hit return at that cursor location and you get this:

```javascript
    if (test) {
        callSomething(first, second, third, fourth, fifth, sixth, seventh,
            eighth, ninth, tenth);

|       }
```

I even get the above behavior with the following user settings:

```javascript
    "editor.autoIndent": false,
    "editor.autoClosingBrackets": false,
```

The solution may require language awareness, per issue #3422. Except that there should be a way for me to turn off attempts at intelligent reformatting of code that is already there.

**Comment by jtlapp** [comment]
There are also times when I place a closing bracket after code that I haven't finished formatting, and the above behavior relocates the bracket to an improper indentation.

For example, I encounter this after cutting-and-pasting code whose indentation levels needs to be changed at the pasted location. If for some reason I place the closing bracket before I've corrected the indentation, VSC moves the closing bracket, requiring me to reformat still one more line of code (after huffing over VSC's reformatting the line I just entered).

**Comment by jtlapp** [comment]
I'm finding myself having to do an infuriating amount of correcting of VSC's reformatting of my code.

And I can't turn `autoIndent` off to stop the nonsense (#31728). I'm switching back to BBedit.

**Comment by rebornix** [comment]
@jtlapp do you still see this issue with latest version?

With current version, when you press enter after the closing bracket

![enter-multiline](https://user-images.githubusercontent.com/876920/33099130-a9bbfe74-cec4-11e7-936c-378089d5c2ed.gif)

when you press enter after the multi-line expression, since the indentation rules are not smart about it, it indents by 1, but once you change the indentation, we won't ruin that by force

![enter-multiline-1](https://user-images.githubusercontent.com/876920/33099178-ded2ea0a-cec4-11e7-91fb-55875cd8530b.gif)

The indentation rules don't fit in all cases, so if you don't like it, now turn off `editor.autoIndent` will not honor indentation rules anymore, which means it no longer adjusts indents by guessing.

![enter-multiline-2](https://user-images.githubusercontent.com/876920/33099233-0e1d80fe-cec5-11e7-9836-436b0630ee26.gif)

**Comment by jtlapp** [comment]
Yes, everything is working properly in 1.18.1. Thank you!

How are you getting those video GIF captures?
