### ISSUE TITLE
Python running in background freezes entire computer

### ISSUE THREAD

**Issue by ricardovsilva** [Microsoft/vscode#35943]
This problem started to happen today, apparently without reason and I don't know where to look to figure out what is happening.
Everytime that I open VSCode, it starts a python process in background. That process slowly grow in cpu and memory usage, until my computer freezes.
That python process only run when VSCode is open.

I don't know if it's coincidence, but project that I'm working is also a python project, but I didn't run python in terminal or hit f5 button, so (I believe) that project is not running. Is there anything on vscode engine that uses python?

- VSCode Version: 1.17.0-1507160143
- OS Version: Ubuntu 16.04

**Comment by egamma** [comment]
@ricardovsilva can you reproduce this when you disable the Python extension (from the description I guess this is the case)? If the issue is Python related then please file the issue against the Python extension.

**Comment by ricardovsilva** [comment]
@egamma  ty for fast response. Tonight I will try that.

**Comment by joejo-unity** [comment]
I was just about to come and state I was having this issue when I saw this comment. I tries disabling the Python extension but no love. The Python process that CodeHelper launches is not being destroyed when VSCode is destroyed and that leaves this process hanging around sucking up CPU/RAM/Disk.

After disabling extensions one after another it appears the culprit is the Mercurial extension installed. I'll report over to them.

**Comment by ricardovsilva** [comment]
@joejo-unity maybe Mercurial extension caused this but I don't really think that it's a Mercurial extension problem, maybe something in vscode extension engine. I'm saying that because I don't use Mercurial extension. To be honest, I even know what Mercurial is.

**Comment by egamma** [comment]
@ricardovsilva VS Code Core doesn't use python. When you use the Python extension and edit a Python file then the Python extension gets activated in it starts Python processes to provide features like auto completion. Since this is a Python process and not a CodeHelper this looks like an issue with the Python extension. Please file the issue against this extension https://github.com/DonJayamanne/pythonVSCode/issues

**Comment by ricardovsilva** [comment]
Opened an issue on pythonVSCode repository https://github.com/DonJayamanne/pythonVSCode/issues/1301
