### ISSUE TITLE
[loc] Chinese translation of the feature 'git stash'

### ISSUE THREAD

**Issue by jindaxia** [Microsoft/vscode#35972]
now ‘stash’ is translated to ‘存储’， i think ‘暂存’ will be better，or just use ‘储藏’ as [GIT BOOK](https://git-scm.com/book/zh/v1/Git-%E5%B7%A5%E5%85%B7-%E5%82%A8%E8%97%8F%EF%BC%88Stashing%EF%BC%89)

- VSCode Version: 1.17.0
- OS Version: any

Steps to Reproduce: not needed

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
@dbaeumer Can't users contribute translations through Transifex? I couldn't find any wiki docs related to that.

**Comment by dbaeumer** [comment]
@joaomoreno yes, they can.

@danyeh do we have some documentation how users can contribute to the translation using Transifex. If not, could you write something up.

**Comment by nmur** [comment]
Disclaimer: I don't actually speak Chinese, I just made translations based on the suggestion in the OP.

I've gone ahead and made new suggestions in [transifex](https://www.transifex.com/microsoft-oss/vscode-extensions/translate/#zh-Hans/git/116961395?qt=%E5%AD%98%E5%82%A8&q=stash) for all the strings which I thought would be relevant. I haven't used Transifex before, but it looks like they will need 1-2 more votes in order for the suggestion to be chosen.

**Comment by danyeh** [comment]
I agree ‘暂存’ is better. I wouldn't say ‘存储’ or ‘储藏’ are wrong but they are not good as ‘暂存’ to reflect meaning of stash in git command context.
Thanks @jindaxia @nmur for the feedback and implementation! I will do more follow up there in Transifex.
@joaomoreno @dbaeumer , our translation contribution guide is here: https://aka.ms/vscodeloc

**Comment by joaomoreno** [comment]
@dbaeumer I suggest you somehow link to that guide from our Contribution guide.

**Comment by Joelism** [comment]
Hi, community translator here. I followed [Microsoft Terminology](https://www.microsoft.com/en-us/language/Search?&searchTerm=stash&langID=Chinese%20Simp.&Source=true&productid=All%20Products) to translate the word, but "储藏" is indeed more used and connected to this specific feature. "暂存" may not be an option because it's used for "stage".
I think we can give "储藏" a go if we are not restricted by company-wide terminology consistency.

**Comment by danyeh** [comment]
All good discussion here. You as experts who have both tech knowledge and language knowledge can influence how Microsoft define the terminology translation. I indeed filed a terminology review request when I added above comment days ago. Terminology team is aware of this issue and monitoring. We can continue our discussion here.
I want to add a new proposal here. How about "转存“？Please vote.
To summarize, 
1. Better to choose one from '储藏’ or '转存'. '储藏’ is used in [GIT BOOK](https://git-scm.com/book/zh/v1/Git-%E5%B7%A5%E5%85%B7-%E5%82%A8%E8%97%8F%EF%BC%88Stashing%EF%BC%89). '转存' is kind of reflect both 'store', 'away' and 'restore'able' which match the meaning of [stash](https://git-scm.com/docs/git-stash).
2. ‘存储’ is not good option because not distinguish with 'Store', 'Memory' etc.
3. '暂存' is not good option because not distinguish with '[stage](https://git-scm.com/docs/git-stage)'

**Comment by dbaeumer** [comment]
Added a link to our readme.md.

**Comment by Joelism** [comment]
"转存" is similar to "转储" which is the translation for dump (not a command in git). Will people get confused in this case? Dump and stash have similar meaning though.
Also, "转存" makes me feel that I can specify a location, and save there. Just a personal opinion.

**Comment by danyeh** [comment]
Ok, sounds like only option left is '储藏’. I will recommend this to terminology team.
Thank you all for the input!

**Comment by danyeh** [comment]
Thanks @jindaxia @Joelism. I am closing this issue.
Translation have been fixed by using '储藏’ for VS Code.
Terminology change to '储藏’ has been approved and implemented in termstudio.
For some reason, the term query portal still show old term. Our term team is investigating.
