### ISSUE TITLE
Allow both console and output to be displayed simultaneously

### ISSUE THREAD

**Issue by bgashler1** [Microsoft/vscode#3597]
See https://github.com/Microsoft/vscode/issues/1875#issuecomment-190820436

Whenever the console updates, he loses his output window.

**Comment by isidorn** [comment]
This is fixed in the march release of vscode, console is not so spammy and only reveals itself on new debug launch.
From what the user described his main problem is that the console pops up when not needed. Not that he needs to look at console and output at the same time

@mredbishop or did I understand wrongly? You can tryout the march insiders vscode, or the march update next week and let us know if this behavior improved for you

Let me know what you guys think and I can reopen

**Comment by mredbishop** [comment]
Actually,  for me it's the reverse.  My debug is pretty spammy,  so when I'm running a task and viewing the output window for the details it keeps jumping back to the debug window. I would really like to be able to see both as they are both important but failing that I would like an option to turn off bringing debug and/or output to the front when they updates.

**Comment by mredbishop** [comment]
P. S. I'll try the insider update anyway and see how that differs.

**Comment by isidorn** [comment]
If you understand you correctly, you do not have the reverse situation. Debug will no longer jump back to front when updates. Please try out the insider update and let us know what you think.

**Comment by mredbishop** [comment]
Will do, cheers :)

**Comment by mredbishop** [comment]
Awesome, this does exactly what I was after. Thanks :)

**Comment by isidorn** [comment]
Glad to hear :)
