### ISSUE TITLE
vscode not showing TS2454 and TS2693

### ISSUE THREAD

**Issue by avikalpa** [Microsoft/vscode#36013]
TS2454 - Variable 'ids' is used before being assigned.
TS2693 - 'Set' only refers to a type, but is being used as a value here.

- VSCode Version: 1.17.1
- OS Version: 10.12.3(macOS)
- ```"strict": true``` in ```tsconfig.json```

Steps to Reproduce:

Write in a test.ts file
```ts

class stuff {
	public id: string;
	public uid: number;
	constructor(parameter: string){
		this.id = parameter;
	}
	public getUID(): number {
		return Date.now();
	}
}

let ids: number[];
for ( let i = 0; i < 100; i++){
	ids[i] = new stuff(i.toString()).getUID();
}
assert.ok( new Set(ids).size !== ids.length );

```

No red squiggly lines are shown. What it should show is,
 ```ts

class stuff {
	public id: string;
	public uid: number;
	constructor(parameter: string){
		this.id = parameter;
	}
	public getUID(): number {
		return Date.now();
	}
}

let ids: number[];
for ( let i = 0; i < 100; i++){
	ids[i] = new stuff(i.toString()).getUID();
	~~~~
	Variable 'ids' is used before being assigned.
}
assert.ok( new Set(ids).size !== ids.length );
		   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
		'Set' only refers to a type, but is being used as a value here.

```

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
I see the expected behavior for the unused variables:

<img width="559" alt="screen shot 2017-10-11 at 10 51 16 am" src="https://user-images.githubusercontent.com/12821956/31457651-38df4ce6-ae72-11e7-9cec-4240b70503a5.png">

If `Set` is the standard library's `Set`, then `new Set` would be valid code is my understanding so I wouldn't expect `TS2693`


1. What target / lib setting are you using in your `tsconfig.json`? I tested this with `"target": "es6"`.
1. What TypeScript version is active? This is shown in the vscode status bar next to the `TypeScript` label
1. Can you confirm the file is part of your `tsconfig` project. Run `TypeScript: go to project configuration` to check this

**Comment by avikalpa** [comment]
Typescript version 2.5.3

I was running with ```"target": "es5"```. No red squiggly lines are shown for both TS2454 and  TS2693.

I changed to ```"target": "es6"``` Still no red squiggly lines are shown for TS2454.

![screen shot 2017-10-12 at 12 18 21 am 1](https://user-images.githubusercontent.com/12738336/31460129-fb24162c-aee2-11e7-8a04-78bd2af69825.png)


@mjbvz Another thing **not** related to this issue, how are you getting inline references for typescript like C#?

**Comment by mjbvz** [comment]
The `tsconfig` is what enables strict mode. Strict mode is disabled by default, so files not in the project will not show strict mode errors

Here's info about the references codelens: https://code.visualstudio.com/Docs/languages/typescript#_references-codelens Just set `"typescript.referencesCodeLens.enabled": true` to enable it
