### ISSUE TITLE
Explorer: active file no longer revealed

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#36033]
Steps to Reproduce:

1. open a file from the explorer
2. reload window

=> active file is not revealed and selected

**Comment by isidorn** [comment]
This is somewhat of same issue as #35152
However my fix from that commit is no longer working.

@sandy081 @joaomoreno did we change something in the order / timing how views are getting created?
The issue here is that the explorer view thinks it is created wheres it is not.

For some weird reason if I revert my commit https://github.com/Microsoft/vscode/commit/317a4662a1a96428292acd6d0c6ee036833b0255 this now works fine now. I can revert it but I think my commit is doing the correct thing there.

**Comment by sandy081** [comment]
This fix https://github.com/Microsoft/vscode/commit/317a4662a1a96428292acd6d0c6ee036833b0255 delays creating all views until extension host is ready which I think is not correct. Before that fix, we create the Viewlet with the available views, we update the rest once the extension host is ready.

I would revert the fix and comment there why we do not wait there.

**Comment by sandy081** [comment]
I have reverted the change https://github.com/Microsoft/vscode/commit/317a4662a1a96428292acd6d0c6ee036833b0255 and commented why the wait is not needed there. 

Also #29609 was broken which is related to the change. Fixed it.

@isidorn Even after reverting the change, I reproduce this issue. Not sure where is the root cause.
