### ISSUE TITLE
New window not created when opening a file from the command line - with our without -n option

### ISSUE THREAD

**Issue by DarrenDaGH** [Microsoft/vscode#36101]
- VSCode Version: Code - Insiders 1.18.0-insider (3ffa14e5ed86b3489f86d9f8d966ae3076f94a61, 2017-10-11T05:26:57.467Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.13.1
csharp|ms-|1.12.1

---

Steps to Reproduce:

1. Go to command line
2. Do "code-insiders filename.txt" or code-insiders --new filename.txt"

Expect:
Code to open a new window with the file specified in it

Reproduces without extensions: Yes

**Comment by chrmarti** [comment]
@DarrenDaGH You write `--new`, but only `-n` and `--new-window` work. Could you retry with one of these?

**Comment by DarrenDaGH** [comment]
Retried with both... Got it to work once but never again (it was with - - new-window). The app seems to get activated (attention/needy window on Taskbar) but a new window is never created.

Darren

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by bpasero** [comment]
I cannot reproduce the issue that a new window would not open, however there is also https://github.com/Microsoft/vscode/issues/35765 where we just blink the taskbar intead of showing the window. 

@DarrenDaGH can you do this:
* start code-insiders to get 1 window opened
* from the command line run "`code-insiders -n <somefile>`"
* check if you now have 2 windows opened (it could be that the new window did not get focus because of #35765)

**Comment by DarrenDaGH** [comment]
It is definitely intermittent – it works sometimes but not others.  What version of Windows are you using?  I am on Fall Creators Update/RS3.

Darren

**Comment by bpasero** [comment]
I tried to reproduce after updating Windows 10 to latest creators update and could not.
