### ISSUE TITLE
Open file command ignores exclude filters

### ISSUE THREAD

**Issue by shadow-cs** [Microsoft/vscode#3615]
When opening a file `Ctrl+E` command the suggestions show files that are explicitly excluded by the settings. I tried both `files.exclude` and `search.exclude` but I still get the wrong hits.

**Comment by bpasero** [comment]
@shadow-cs are those in the "files and symbols" category or "recently opened"?

**Comment by shadow-cs** [comment]
Files and symbols category.
Sorry about the delay...

**Comment by bpasero** [comment]
@shadow-cs steps?

**Comment by serkanyersen** [comment]
I'm having the same problem. I have `dist` folder which specifically ignored in the search and files. but files under this folder still shows up on quick open.

```js
// Place your settings in this file to overwrite default and user settings.
{
    "files.trimTrailingWhitespace": true,
    "search.exclude": {
        "**/node_modules": true,
        "**/bower_components": true,
        "**/dist": true,
        "**/typings": true
    },
    "files.exclude": {
        "**/.git": true,
        "**/.svn": true,
        "**/.DS_Store": true,
        "**/dist": true
    }
}
```

![screen shot 2016-08-03 at 17 04 59](https://cloud.githubusercontent.com/assets/30582/17386130/73dec85c-599c-11e6-9cd1-79c95c8f285a.PNG)

Restarting the editor does not help.

I think this happens because of the `recently opened` thing. If I can clear that list it might help. how do you clear recently opened list?

**Comment by bpasero** [comment]
There is a command: "Clear Editor History"
