### ISSUE TITLE
Where to start understanding the repository and how to console?

### ISSUE THREAD

**Issue by koolgit** [Microsoft/vscode#36167]
This is probably a really really dumb question, so I apologize for it.

I want to trace through the repository for learning purpose, but I am having trouble tracing it and debug it. Can someone point me a direction on how to

1. Find the entry point after running `npm run watch` and `./scripts/code.sh`,  specifically how does this file get called `https://github.com/Microsoft/vscode/blob/master/src/vs/base/browser/browser.ts` ?

2. How to debug through console. I tried opening `Developer: Toggle Developer Tools` but no matter how much `console.log` I put in `https://github.com/Microsoft/vscode/blob/master/src/vs/base/browser/browser.ts` the consoles don't show up.

Thanks

**Comment by isidorn** [comment]
Check out these docs
https://github.com/Microsoft/vscode/wiki/How-to-Contribute
Also try putting console logs somewhere else, maybe that file is not running in the renderer, since only the rendere output will get forwarded to the console.

As for the code base understanding docs those are missing thus assigning this to @gregvanl

**Comment by gregvanl** [comment]
At this point, there are no plans to document or give a detailed overview of the vscode code base.
