### ISSUE TITLE
Terminal does not support dim/faint style

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#36238]
```
echo -e 'normal \x1b[2mfaint \x1b[0m'
```

<img width="333" alt="screen shot 2017-10-13 at 9 25 35 am" src="https://user-images.githubusercontent.com/2193314/31556129-823a4ac6-aff8-11e7-9582-34eaec41729b.png">

Upstream PR: https://github.com/sourcelair/xterm.js/pull/1043

**Comment by monk-time** [comment]
This doesn't seem to work on Win7x64 with a freshly unzipped VSCode Insiders 1.19.0 (and also in Release 1.18) and Git for Windows 2.15.0 (and also with 2.14.2):

![clipboard02](https://user-images.githubusercontent.com/7759622/32606108-0e19f65a-c565-11e7-8045-e85b44abc9e2.png)

I don't think it's a Windows/GfW issue, because Git Bash by itself can display faint text:

![2017-11-09_15-47-06](https://user-images.githubusercontent.com/7759622/32606151-419c7fac-c565-11e7-8350-66413fad616d.png)

Should I open a new issue?

**Comment by Tyriar** [comment]
@monk-time if it doesn't work in Windows this is because we emulate xterm via winpty which has limited capabilities. I don't think it's worth creating an issue for this.

**Comment by monk-time** [comment]
@Tyriar Oh, I see. I was confused by [the changelog] that implied that this is fixed on all platforms.
