### ISSUE TITLE
1.17.1 can not format code

### ISSUE THREAD

**Issue by ryanliue** [Microsoft/vscode#36258]
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:10:17.189Z)
- OS Version: Darwin x64 17.0.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
RustyCode|sav|0.19.1

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by egamma** [comment]
The formatting support in VS Code is provided by a language extension. You do not mention what language you are using but since you have the RustyCode extension installed I suspect you are programming in Rust? Therefore please file a feature request against this extension to support formatting in this repository. Also search on the market place for other Rust extensions that might support formatting, eg., https://marketplace.visualstudio.com/items?itemName=Connorcpu.vsc-rustfmt.
