### ISSUE TITLE
Can `@ts-check` ignore `javascript.validate.enable` setting?

### ISSUE THREAD

**Issue by g-plane** [Microsoft/vscode#36276]
- VSCode Version: 1.17.1
- OS Version: Windows 10

For me I have installed `Flow Language Support` extension because I use Flow sometimes. However, once using `Flow Language Support` extension I must set `javascript.validate.enable` to true to avoid some conflicts to tsserver.
But sometimes when I don't use Flow, I want to use tsserver to check my JavaScript code. It is annoyed if I change the settings every time. So can you make that: if `@ts-check` is existed in a JavaScript file, vscode just still check the JavaScript file by using tsserver and ignore whether `javascript.validate.enable` is `true` or not.

**Comment by mjbvz** [comment]
`javascript.validate.enable` disables all error reporting. This by-design because it allows support for javascript extensions such as flow.  ts-check just enables additional type checking in a file. It cannot be used to re-enable `javascript.validate.enable`.

If you are switching between flow and normal js projects, try setting `javascript.validate.enable` in each workspace's settings
