### ISSUE TITLE
Failed to load tslint library.

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#3627]
I like the tslint extension, I use it with our vscode repo.

But I now get this error in every other workspace. I think this message should just be omitted.

![image](https://cloud.githubusercontent.com/assets/22350/13459773/1ef8a73a-e076-11e5-9544-c9f1e5cd1386.png)

**Comment by egamma** [comment]
@joaomoreno 

Since you have installed tslint locally inside the vscode repository the vsode-tslint extension doesn't find tslint in the other workspaces. Workarounds:
- install tslint globally
- in the user settings disable tslint and in the vscode workspace settings enable tslint
```json
"tslint.enable": false
```
@dbaeumer this issue shows up across all our linters when a user prefers to install a linter locally.

**Comment by egamma** [comment]
This issue was moved to Microsoft/vscode-tslint#32
