### ISSUE TITLE
Ctrl+R (recently opened folder and files) not listed in keyboard shortcuts cheatsheet (Windows)

### ISSUE THREAD

**Issue by CubixSystem** [Microsoft/vscode#36286]
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:24:50.851Z)
- OS Version: Windows_NT x64 6.3.9600

Steps to Reproduce:

1. Open https://code.visualstudio.com/shortcuts/keyboard-shortcuts-windows.pdf
2. Can't find `Ctrl+R` record (recently opened folder and files)

**Comment by CubixSystem** [comment]
Is this Windows-specific combination? I also try this in Linux, but it didn't work

**Comment by seanmcbreen** [comment]
Hi,

We are always attempting to balance how many shortcuts to put on the cheat-sheet and this one did not make the cut due to the limited space.  

The easiest way to see all shortcuts is via the shortcuts editor.
https://code.visualstudio.com/docs/getstarted/keybindings

So for now I think we can close this (as all shortcuts are in the editor or in the command palette) but I will ask the team to look to ensure that it's easy to navigate to the right docs to get this answer from the cheat-sheets.

Happy Coding!
Sean

**Comment by CubixSystem** [comment]
Thanks for clarification!
