### ISSUE TITLE
Markdown Preview: External images won't load

### ISSUE THREAD

**Issue by bluzi** [Microsoft/vscode#36284]
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:21:18.489Z)
- OS Version: Linux x64 4.10.0-37-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.3.2
vscode-angular2-component-generator|dba|0.0.3
tslint|eg2|1.0.11
auto-close-tag|for|0.5.1
cpptools|ms-|0.13.1
tsimporter|pmn|1.2.14
vscode-icons|rob|7.15.0
autoimport|ste|1.2.2
vscode-arduino|vsc|0.2.9
---

Steps to Reproduce:

1. Open Markdown file

2. Add any image from external source (for example: `![Homepage](http://eliran.net/cuckoo-images/main.png)`)

3. Open the preview

4. The image appears broken

*Example*
Please refer to [this README file](https://github.com/cuckoos-nest/cuckoos-nest/blob/master/README.md), try to open it using code, and open the Markdown preview feature. 

I'll be happy to try and solve it and make a PR if it turns out to an unresolved issue.

Reproduces without extensions: *Yes*

**Comment by maxibanki** [comment]
The problem is that the images will loaded over `http`. Referring to this article in the docs, you need to change the preview security setting to allow insecure requests. In my test a prompt appears with the decision which security i want to have. You can manually change the setting by pressing `Ctrl + Shift + P` and search for `Change preview security setting`).

**Comment by mjbvz** [comment]
Yes as @maxibanki this is by-design for http images. Please try changing the preview's security settings if you want this content to be loaded

**Comment by bluzi** [comment]
Got it, thanks!
