### ISSUE TITLE
Preview of object in debug console should go 1 level more deep

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#36301]
From https://twitter.com/loic84/status/919395524456804352
![image](https://user-images.githubusercontent.com/172399/31585031-62ffd13a-b1ba-11e7-8965-a566ecc047c4.png)

**Comment by isidorn** [comment]
This is coming from the node adapter -> forwarding to @roblourens 
However I am not convinced that the preview should go 2 levels. Why is 2 better than 3 and so on...
The previse is just a previw, for the real expansion you should expand the object to inspect more.
However this is up to the debug adapter to decide hwo to constrcut the preview

fyi @weinand

**Comment by roblourens** [comment]
When `console.log` is called, we get a 1 level deep preview of the object from node, and I process that to generate the preview string. To show more details, I'd have to make roundtrips to node, which has a cost and it gets harder to display on one line, etc.

But there's another issue which I think is shown here and I'm not sure what to do. This program terminates immediately, so if you go to the console after it's finished and expand that object, you can't inspect it because the program and the debug adapter has terminated. That is unfortunate, but Chrome Devtools gives basically the same experience IIRC. It can also happen during a debug session e.g. if you refresh a webpage and the object is disposed.
