### ISSUE TITLE
VSCode unbearable slow with HDD

### ISSUE THREAD

**Issue by tovin07** [Microsoft/vscode#36319]
21 seconds to start? Is it OK?

Link to issue: #15455 

[d2dc_main.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1386209/d2dc_main.cpuprofile.txt)
[d2dc_renderer.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1386210/d2dc_renderer.cpuprofile.txt)

- VSCode Version: <code>Code - Insiders 1.18.0-insider (dcd1aa35dfa590b4a528e1ab55e957002f430f17, 2017-10-10T05:26:33.683Z)</code>
- OS Version: <code>Windows_NT x64 6.1.7601</code>
- CPUs: <code>Intel(R) Core(TM) i7-4610M CPU @ 3.00GHz (4 x 2993)</code>
- Memory (System): <code>7.88GB (1.79GB free)</code>
- Memory (Process): <code>212.86MB working set (212.88MB peak, 196.46MB private, 36.32MB shared)</code>
- Load (avg): <code>0, 0, 0</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>yes</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|2108|
|main|app.isReady => window.loadUrl()|3068|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|4804|
|renderer|require(workbench.main.js)|5180|
|renderer|create extension host => extensions onReady()|3901|
|renderer|restore viewlet|3716|
|renderer|restore editor view state|5923|
|renderer|overall workbench load|6244|
|main + renderer|start => extensions ready|19214|
|main + renderer|start => workbench ready|21435|

---

:warning: Make sure to **attach** these files from your *home*-directory: :warning:
-`d2dc_main.cpuprofile.txt`
-`d2dc_renderer.cpuprofile.txt`

**Comment by jrieken** [comment]
wow, that is pretty bad. @tovin07 does it always start so slow for you? does it run OK once it's up and running?

**Comment by tovin07** [comment]
It happens all the time.
After I start my computer, VSCode usually takes 15 -> 30 seconds to start (first time start).
If I close VSCode for a while, the start time reduces to 7 -> 15 seconds (second time start).

However, after it fully started, everything seems to be OK.

**Comment by pgsil** [comment]
Do you by chance have an SSD, or do you have a desktop HDD or even a laptop-grade HDD (eg 5400RPM)?

**Comment by jrieken** [comment]
So, from looking at the profiles I see some issues. The infamous app-ready-issue which is often caused by over-eager AV software, see https://github.com/Microsoft/vscode/issues/22087. Then it takes roughly 2 seconds to initialise the empty, default menu. Do you have by any chance some software installed that adds something to your menus or modifies them in some other way? Last, most important, and as mentioned by @pgsil is very bad fs-performance. Opening/reading a files takes ~30ms which is at least 10 times slower than it should be...

**main process** 

<img width="1388" alt="screen shot 2017-10-16 at 12 49 29" src="https://user-images.githubusercontent.com/1794099/31608672-602043de-b271-11e7-8533-cb28826503e1.png">

** renderer process **

<img width="1377" alt="screen shot 2017-10-16 at 12 51 39" src="https://user-images.githubusercontent.com/1794099/31608683-6cc2b766-b271-11e7-9ec2-5948c7976db6.png">

**Comment by tovin07** [comment]
Thanks @pgsil, @jrieken for a really clear explanation.

I use a laptop with a HDD (5400 rpm).
Sadly, my laptop has antivirus software installed (Trend Micro).

So, is there any workaround for this issue?

I faced this issue with another computer too. It run Ubuntu. I will add a perf-profile tomorrow.

**Comment by jrieken** [comment]
> So, is there any workaround for this issue?

If you have the choice could try a different AV software or you might be able to tweak it's configuration. That can buy you ~2 seconds, the elephant in the room is the HDD which is slow, really, really slow compared to SSDs

**Comment by pgsil** [comment]
@tovin07 While I don't have 20s loadtimes, I can absolutely reproduce the issue on my notebook.

I have a Samsung Odyssey (XG1BR config) with a Core i5 7300HQ and 8GB of DDR4 RAM. While that's not an impressive setup by any means, I doubt it's enough to explain the abysmal load times. The bottleneck lies in the HDD: it's a notebook, and like most low-end notebooks, it ships with a 5400RPM HDD.

My load times are between 10 seconds on a cold start and 5 seconds otherwise. I don't use any third-party anti-virus solutions, just Windows 10's default anti-virus, which might explain the slightly lower startup times. 

My recommendation for a fix is sadly replacing your HDD with a SSD. It's absolutely worth the investment. If you have a M.2 slot on your notebook, get a M.2 SSD and install your OS on it. Otherwise, replace your HDD with a regular SSD. The performance gains are very noticeable, even outside VSCode.

On a desktop, 7200RPM HDD while the load times are obviously slower than with a SSD, they're not that bad, so I'm not quite sure how much of this problem is because of VSCode itself.

**Comment by tovin07** [comment]
Great, HDD should be replaced.
I tested with my other computer - Samsung SSD 850 EVO, Windows 10, brand new VSCode installed - without any extension. Time reduced to around 5 seconds for a cold start, 1-3 seconds for others.

Thanks @jrieken and @pgsil
