### ISSUE TITLE
Default fonts are vertically offset on some Linux distributions

### ISSUE THREAD

**Issue by jorgerabello3** [Microsoft/vscode#36322]
S.O. GNU/Linux Debian 9
VS CODE Version: 1.17.1
ISSUE:
When I use Integrated Terminal (bash) the lines appears cropped in horizontal.

**Comment by mpartipilo** [comment]
![image](https://user-images.githubusercontent.com/467049/31725460-c0b1428e-b424-11e7-9043-63fb6415abfe.png)
Adding image for reference. Changing font size and/or height does not improve it.

**Comment by Tyriar** [comment]
@jorgerabello3 @mpartipilo do you have a custom font by chance? I cna't reproduce on Debian 8

<img width="772" alt="screen shot 2017-10-21 at 9 35 56 am" src="https://user-images.githubusercontent.com/2193314/31853776-5306001e-b643-11e7-8ebc-c72e5f194d59.png">

The default font may have changed in 9. This is similar to what happened on Fedora due to the default font there, you should try using a different monospace font in the meantime.

**Comment by Tyriar** [comment]
Kali Linux also suffers from this issue

**Comment by tonila** [comment]
Debian 9. Same problem. Changing fonts/fontSizes does not help. Default font is monospace.

**Comment by Tyriar** [comment]
Upstream issue: https://github.com/xtermjs/xterm.js/issues/1170

**Comment by jorgerabello3** [comment]
Resolvido ao atualizar para a última versão !
