### ISSUE TITLE
Debugging: Provide command to continue/pause all/other threads

### ISSUE THREAD

**Issue by akaroml** [Microsoft/vscode#36394]
When debugging a multi-thread application (Java in our case), there can be multiple threads paused at the same time. Our Java debugger only stops/continues one thread at a time. So when you hit a breakpoint in a runnable which is executed by multiple threads, it is really painful for to continue them one by one:
![image](https://user-images.githubusercontent.com/16755094/31651707-45a53512-b34f-11e7-8807-265fe92383ce.png)

It would be really nice if vscode provides the menu entry to continue all the suspended threads with just one click. And maybe more like Pause All. And when right-clicking one thread, there could be entries like  Continue Other Threads or Pause Other Threads according to the thread's state.

**Comment by isidorn** [comment]
I understand how this is needed for the java case. However in order to have this we must keep in mind that vscode is language agnostic and the experience should be nice for all debuggers. 
The issue here is that most debuggers do not support continuing a single thread, but when we press continue actually all threads continue.

What I suggest that you contribute custom actions for the call stack view from your java extension.
These custom actions should show up in the thread context menu. Docs about contributing commands https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributesmenus
You should use the `debug/callstack/context` contribution point. And as the context in you action you will get the threadId the user clicked on. Just pushed a commit to make sure that is working
And these actinos should use the `[customRequest](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L6016)` to send whatever you want to your adapter.
That way you could controibute Pause All, Continue Other Threads and whatever you think would make the best exeprience for java debugging.

There still might be some things to polish on the vscode side (actions might appear for non thread entries). But let's first try to do one step and then I can polish it more from the vscode side.

**Comment by akaroml** [comment]
@isidorn Thanks for the reply. Your solution makes sense and we'll do so in the Java debug extension.

**Comment by testforstephen** [comment]
@isidorn Follow `contributes/menus/[debug/callstack/context]` in package.json, we can only add context menu at all the tree nodes of call stack view. Is there any possible to get current focused element type (e.g. thread, or stack frame), and set is to `IContextKey` as what `debugType/inDebugMode/debugState` do?
![image](https://user-images.githubusercontent.com/14052197/33198132-416e7740-d124-11e7-8895-948832244d69.png)

![image](https://user-images.githubusercontent.com/14052197/33198151-5e4d0e62-d124-11e7-8baa-073f51b4e03e.png)

![image](https://user-images.githubusercontent.com/14052197/33198253-fa298fc2-d124-11e7-8c7d-3431080dfc70.png)

**Comment by isidorn** [comment]
Created https://github.com/Microsoft/vscode/issues/39091 to track this

**Comment by isidorn** [comment]
We have added `callStackItemType` so this is now possible
More details here https://github.com/Microsoft/vscode/issues/39091
