### ISSUE TITLE
Settings can be open more in more than one tab

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#36447]
Not sure how I got into this state:

<img width="460" alt="screen shot 2017-10-17 at 12 46 22 pm" src="https://user-images.githubusercontent.com/2193314/31685852-50efc9f2-b339-11e7-8e96-74b11721df30.png">

Clicking on settings.json opened User Settings which was unexpected.

**Comment by Tyriar** [comment]
Even if "User Settings" is closed, settings.json will open a new User Settings tab. I can only close settings.json tab by middle click/clicking the x.

**Comment by sandy081** [comment]
@Tyriar We recently added a functionality to open Settings Editor when clicking on settings file. I tried to get into the above state but no success. Any steps would be helpful.

@bpasero Any insights?

**Comment by bpasero** [comment]
@sandy081 I am using your code to open the settings when you click a file in the explorer that is a settings file, not sure if your intent is to prevent opening multiple settings?

![image](https://user-images.githubusercontent.com/900690/31765311-3af8a330-b4c4-11e7-8552-d763ab575e54.png)

The code lives here: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/preferences/common/preferencesContribution.ts#L62

**Comment by sandy081** [comment]
@bpasero Opening User/Workspace/Workspace Folder settings explicitly opens them in different editors. I think, issue mentioned here is different that @Tyriar has `settings.json` file and `User Settings` editor opened simultaneously. I thought with your new feature, we always open Settings editor when user opens `settings.json` file ?

**Comment by bpasero** [comment]
Yes I see what the problem might be.

**Comment by bpasero** [comment]
The issue here was that settings.json was already opened in any of the inactive tabs and now after my change whenever the settings are opened we want to open the real settings editor. I added a check to not prevent opening of the raw settings file if it is already opened as tab. This should prevent the accidental opening of the real settings editor when you click on settings.json while it is already opened.

Still, when no settings.json file is opened, we will open the actual settings editor.
