### ISSUE TITLE
Function breakpoints - protocol allows condition but no UI to set condition

### ISSUE THREAD

**Issue by rkeithhill** [microsoft/vscode#3646]
Maybe I'm missing something in the debug UI experience but I see no way to add a condition to a function breakpoint even though the debug protocol supports it.

**Comment by isidorn** [comment]
You are correct, function breakpoints currently can not have a condition.
We will add this in the future to the UI

**Comment by rkeithhill** [comment]
Thanks for the confirmation!  Glad to hear it is a planned feature.

**Comment by weinand** [comment]
UI for conditional breakpoints exists for quite some time:

![2017-11-13_15-26-13](https://user-images.githubusercontent.com/1898161/32730321-000aac24-c887-11e7-9307-11d4c87624b5.png)

**Comment by weinand** [comment]
Ropened because function breakpoints do not appear in the gutter and provide no UI to add/edit their condition.

**Comment by davidanthoff** [comment]
@weinand should this really be closed? The feature is supported in the DAP, it would be nice if it was also surfaced in the UI.

**Comment by weinand** [comment]
Yes, this is a valid feature request and we should address it because bringing VS Code's debugger UI on par with the Debug Adapter Protocol is actually on the VS Code roadmap.

**Comment by isidorn** [comment]
Let's assign to this milestone for the inital investigation.

Ideas on how the UX would look like are welcome.
Here's how this looks for Exception Breakpoints https://github.com/microsoft/vscode/issues/111227#issuecomment-734870584

I would probably go with a similar approach for function breakpoints
fyi @connor4312

**Comment by yannickowow** [comment]
Hi,
First of all, thanks for adding this to January goal !
I saw how you handled conditions for breakpoint filters.
Since `FunctionBreakpoint` has as `hitCount` attribute as well, I see two possibilities:

- it can be shown the same way as `ExceptionBreakpoint` with a `Edit Hit Count` and `Edit Condition` actions.  
- it can be shown as a drop-down menu the same way as `SourceBreakpoint`

Thanks

**Comment by isidorn** [comment]
@YannickMeeus thanks for jumping in and for sharing ideas. 
If we do it inline like we did for Exception Breakpoint than indeed we need two actions as you proposed. Since there is not enough vertical space for a rich widget that could have a drop-down.
If we do a rich breakpoint widget than the question is where to show it, in what editor/

**Comment by yannickowow** [comment]
Yes, you are right about vertical space, I missed that point.
Maybe instead of showing full name for `Condition` and `Hit Count` we can display products icons such as `symbol-key` and `symbol-numeric` (or new/customized ones) to reduce vertical constraints. 
If you click on this logo it will display a drop-down with logo + full text and this text will be reduced after selection.

**Comment by isidorn** [comment]
Here's an idea:
* We add a Context Menu action to the Function Breakpoint: "Edit Condition". We also add an inline edit action (like propossed here https://github.com/microsoft/vscode/issues/113805)
* When this action is executed we simply open the editor breakpoint widget in the Active editor and pass focus to the widget. We open the widget on cursor location. Even though the Function breakpoint is not tied to the active editor this will give us the most space, and a same experience as for regular breakpoints. 
* Rare corner case where there is no editor open: this action is disabled

I believe that in practice this will work nicely.

@weinand @connor4312 @yannickowow let me know what you think? I can also present this in the UX meeting today.

**Comment by weinand** [comment]
@isidorn editing an object (here a function breakpoint) in a random unrelated editor is a kludge.

I see two options:
- we use the same UI as done for the exception breakpoints 
- we open the editor breakpoint widget in the breakpoints view

**Comment by isidorn** [comment]
@weinand thanks for feedback. Editor breakpoint widget can not be rendered in the breakpoints view, it requires an editor the way it is implemented.

So let's go with option 1 and use the same UI as done for exception breakpoints, and have two context menu options as @yannickowow proposed `Edit Hit Count` and `Edit Condition `

**Comment by isidorn** [comment]
I have pushed a first version of this. Please try it out with VS Code insiders from tomorrow.

A UI corner case is when a Function Breakpoint has both a Hit Cound and a Condition. I try to render both, and am happy with the final result (can be seen in the gif).

What is not shown in this demo: the `Edit Condition` inline action and the context menu action gets disabled if the Exception Breakpoint does not support conditions, or if there is a debug adapter connected which states in it capabilities that it does not support conditions.
 
![recording](https://user-images.githubusercontent.com/1926584/104580207-3cfb9500-565d-11eb-9578-0a53a595371e.gif)

**Comment by yannickowow** [comment]
It looks good and intuitive to me ! Thanks a lot !

**Comment by isidorn** [comment]
Great, looking forward to feedback.
