### ISSUE TITLE
[Feature Request] Color Picker for 'CSS-in-JS'

### ISSUE THREAD

**Issue by peterschussheim** [Microsoft/vscode#36485]
I love the `colorPicker` released in June Insiders (I think @michelkaporin shipped this) but I want to have this feature in `*.js || *.ts` files.  The use case is for CSS-in-JS.

I would either love to see **out-of-the-box support** for this provided by VS Code **OR** I would greatly appreciate any feedback or resources specific to the Color Picker that would be useful in implementing this feature as a user-created extension.

Please let me know if I can provide additional information.

Thank you,
Peter

**Comment by herrherrmann** [comment]
I could also imagine that the colorpicker should become available for all strings that match the typical CSS color hex code format (e.g. `#333` or `#333333`), maybe even independently from the file type (or maybe configurable by a whitelist of file suffixes).

**Comment by mjbvz** [comment]
I believe this could be contributed by an extensions now. See `DocumentColorProvider` in `vscode.d.ts` for contributing color pickers to a file. Please let me know if you are interested in writing an extension for this and run into any issues getting started

**Comment by peterschussheim** [comment]
Hi @mjbvz! Thanks for the tip, I will look at this tomorrow and yes, I am certainly interested in writing an extension for this. Any other references or resources you think are useful would be most appreciated. 👍

**Comment by peterschussheim** [comment]
@mjbvz 👋 Shared some thoughts below on this idea.  If you have time to provide feedback I would be most appreciative.

Looking at your [vscode-styled-components-extension](https://github.com/mjbvz/vscode-styled-components-extension) (nice work!), this is essentially what I am trying to do, except rather than embedding inside template strings, I want full CSS intellisense + color picker support in **JavaScript/TypeScript objects**.

For example:

```javascript
const styles = {
  colors: {
    blue: '#694AEA',
    red: 'tomato',
    yellow: '#FCFC48',
  },
  background: {
    dark: '#698794',
    light: 'white',
  },
  borderRadius: '3px',
  padding: '0.25em 1em'
}
```

We can see above that the DOM attributes are mapped from **camelCase** in an object to traditional, hyphen-deliminated attributes (ex: `border-radius`).

### Differences from Template String Example:

- opening/closing tokens `{}` instead of **backticks**
- attribute names using camelCase instead of traditional hyphonated style


With these differences mentioned above how do you recommend I get started?

Thanks,

Peter

**Comment by mjbvz** [comment]
Glad that you are looking into this. I don't think you actually want to write a typescript plugin here though since those plugins do not have direct access to the vscode API.

A better example to work from would be our extension helper extension which provides document links in the `vscode.d.ts` API definition file: https://github.com/Microsoft/vscode/blob/master/extensions/extension-editing/src/extension.ts

That extension uses a simple regular expression (`_linkPattern `) to identify document links in `vscode.d.ts` (which look like `[`value`](#SnippetString.value)`) and turn these into clickable links. A more robust solution would use TypeScript to parse the file and extract the document links from the typescript abstract syntax tree.

In this case, you could start by registering a new `DocumentColorProvider` that looks for all strings of the form `/['"]#[0-9a-f]{6}['"]/i` in js or ts files.

**Comment by peterschussheim** [comment]
@mjbvz Thanks for the suggestion above, however, I am confused.  I am new to VS Code  extension development as well as Typescript; forgive me if these are naive questions.

Starting with the code below:

```
import * as vscode from 'vscode'
import * as ts from 'typescript'

export function activate(context: vscode.ExtensionContext) {
  const registration = vscode.languages.registerColorProvider(/*selector: DocumentSelector, provider: DocumentColorProvider*/)
  context.subscriptions.push(registration)
}

const _colorProvider = new class implements vscode.DocumentColorProvider {
  private _colorPattern = /['"]#[0-9a-f]{6}['"]/i

 ...
}
```

Based on this snippet, can you help me understand why I see the following TS errors:

- `Property 'registerColorProvider' does not exist on type 'typeof languages'.`
- `Namespace ''vscode'' has no exported member 'DocumentColorProvider'.`

**Comment by mjbvz** [comment]
Sorry I forgot the color picker API is new for this month. You should still be able to work on your extension but it will only be able to support VSCode 1.18+. To develop an extension that users the color API:

* Make sure you are using a VSCode insiders build for writing and debugging your extension.
* Copy this [`vscode.d.ts`](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts) into your project. This should add the necessary new API definitions

**Comment by peterschussheim** [comment]
I am having trouble using the [document link extension example](https://github.com/Microsoft/vscode/blob/master/extensions/extension-editing/src/extension.ts) you posted above as a guide for the `DocumentColorApi`.  I think part of the confusion on my end is that I am new to the `vscode.d.ts` API.

Would the [`cssMain.ts`](https://github.com/Microsoft/vscode/blob/master/extensions/css/client/src/cssMain.ts) extension be a better reference?  If not, can you please clarify which parts of the `extension-editing` example are relevant to implementing this feature?

Also, are you or any other involved team members available to chat for 10 minutes about this?  It might be quicker than commenting on Github.

Thank you,
Peter

**Comment by aeschli** [comment]
@peterschussheim Yes, cssMain.ts is what you have to look at.
I understand your confusion with the vscode.d.ts. The problem is that colorpovider API are provisional API, and not yet part of vscode.d.ts. But they become API in the upcoming 1.18 release.
Things will get much easier then, so maybe just wait until then (it should come out in around 2 weeks).
Until then you need to add `"enableProposedApi": true,` to you package JSON and re-run npm install.

**Comment by peterschussheim** [comment]
@aeschli Hi Martin, thank you for confirming `cssMain.ts` as a good reference, this clears up my confusion.  :+1:
