### ISSUE TITLE
Allow developers create custom main menu items from extensions.

### ISSUE THREAD

**Issue by ilich** [Microsoft/vscode#365]
Hello,

It would be nice to have a possibility to create custom menu items for extensions' commands, e.g. `Edit -> Format Document`. I think it should work similar to `keybindings` contribution point.

Sincerely,
Ilya

**Comment by beiluo** [comment]
+1

**Comment by Thaina** [comment]
+1

**Comment by artas90** [comment]
Yes, mouse-less interface is good. But some functions are used rare. And it is better to have them in menu and do not guess how it is called in Command Palette.

**Comment by brunnopleffken** [comment]
I came here because of #6000

My point here as a VS Code (& others) user... Adobe Brackets does this (put everything in "Edit" or create new menu items for each extension), and the menus become SOOOO cluttered, with native features + extension features in the same menu makes it too long! I particularly hate this kind of solution that Adobe has taken.

I think a menu "Extensions" listing the installed extensions and submenus with the functions of each extension (like #6000 does) is an elegant solution.

![](https://cloud.githubusercontent.com/assets/7069719/14929697/5e4848f2-0e91-11e6-8641-f683860decda.png)

**Comment by diryboy** [comment]
It seems to me that Notepad++ take the similar approach with @brunnopleffken proposed. I think it's more organized and discoverable than random places. I've seen people didn't know how to "activate" some extension for VS.

**Comment by Tyriar** [comment]
I would prefer if the menu entries were isolated in an Extensions menu as in #6000. The reasons being:

- It makes it very clear which menu items belong to which extensions.
- Prevents possible duplicate menu items from multiple extensions by forcing nesting.
- Allowing menu items in the regular menu has the potential for abuse.

**Comment by smuuf** [comment]
Please, please, avoid the clutter made by many extensions extending menus at several places and create a new `Extensions` menu for extensions' menus, so our installed extensions can have menus. :heart:

**Comment by hanfengcan** [comment]
2 year now~
