### ISSUE TITLE
Rename 'Visual Studio Code' to 'code'

### ISSUE THREAD

**Issue by dur41d** [Microsoft/vscode#36511]
I think that Visual Studio is a term form the 90s that doesn't apply to this project in any shape or form. Why not rename project to simply **code** which better fits the product functionality and minimalistic character. 

If that not possible (for copyright reasons or whatever) then how about MS code? although i prefer the former since I don't want to tie the project to MS since it's used for many platforms and technologies. 

**code** only would be awesome. What do you think? vote this issue up if you support it.

Cheers

**Comment by WebDevBooster** [comment]
I agree that making the words "Visual Studio" part of the name of this product was a very dumb idea indeed! 
Just as dumb as embedding the word "Java" in JavaScript. 

Hoverever, renaming Visual Studio Code to just "Code" isn't a good idea either. Because "Code" is a very generic word. 
I think "VS Code" would be the best compromise in this particular case here. Not great by any means, but a decent compromise.

**Comment by klippx** [comment]
Wow. Just wow. This is next level...

**Comment by dur41d** [comment]
@WebDevBooster I think being generic is one of its strengths because it's an editor for all coding needs regardless of language, platform, framework, etc.

**Comment by MarekLew** [comment]
"All VS Code" 😈

**Comment by Mlocik97-issues** [comment]
Most stupid issue.....

**Comment by Radon222** [comment]
Name it MSCode then

**Comment by klippx** [comment]
M$c0d3 ftw

**Comment by maty21** [comment]
Why not just c :)

**Comment by dur41d** [comment]
Since the project is re-branding by changing its icons, I thought it is a good opportunity to re-think the name since it obviously does not make a lot of sense. Too bad the suggestion is getting so much negative feedback that I don't find necessary.

**Comment by chrisdias** [comment]
Hi - Thanks for the feedback!  We don't have any plans to rename VS Code, we're going to stick with the full name of "Visual Studio Code" as we're a part of the Visual Studio family of products. People generally refer to the tool as "VS Code" these days making search *better*, but admittedly it is still vague :).

**Comment by AleRob90** [comment]
I find changing icons pretty much frustrating already. Just because the icons changed doesn't mean the name is wrong. It gained popularity by having this name and i really haven't heard anyone not using it because it contains Visual Studio in the name. 
Vscode is already used for searching. You may find it wrong, but some people inhere just think viceversa, why is un-necessary? If people don't say their opinion then we will have a new name, just like new icons.
