### ISSUE TITLE
command: git.clone not found

### ISSUE THREAD

**Issue by tautf** [Microsoft/vscode#36528]
- VSCode Version: 1.15.1
- OS Version: Windows 7

Steps to Reproduce:

1. `Ctrl + Shift + p` > `Git clone`

Reproduces without extensions: Yes

I tried to set the default git path for vscode, because i have it installed on a usb drive.
Thats my start command for code:

```
start %input%:\_software\Code\Code.exe --user-data-dir %input%:\_software\Code\.vscode\ --extensions-dir %input%:\_software\Code\.vscode\extensions\
``` 

the variable `%input` contains the drive letter and is inserted by a cmd script.

So now i set the git path to the follwowing:
`"git.path": "E:\\_software\\Git\\bin\\git.exe"`

The path is correct because my usb drive has the letter `E`

After a restart, code still tells me command not found.
I tried every other available executable in the `Git` directory but i still have the same error.

Somebody has an idea how i can fix this issue?

**Comment by joaomoreno** [comment]
Does the issue reproduce if you start Code regularly (instead of using `start %input%...`, but setting `git.path` to the same value?

**Comment by tautf** [comment]
@joaomoreno yes it works 😕 

Im running this command because i dont want to store any data on the computer it self, only on the usb drive.
Is there any other opportunity to get this running?

**Comment by joaomoreno** [comment]
Just to confirm... it works fine when you're not using that `start %input%...`.

How does that `command not found` message surface? Can you show me a screenshot?

**Comment by tautf** [comment]
Yes it works fine without my cmd script, just by double clicking code.exe

It appears from the top window:
![unbenannt](https://user-images.githubusercontent.com/18403881/31765091-8653714e-b4c3-11e7-838c-6c2593ac8798.PNG)

**Comment by tautf** [comment]
@joaomoreno i found out whats the problem.
It works now for me with my startscript.

So if you try to run `Git:clone` **directly after the start** of code it tells you `command: git.clone not found` but if you **wait** for some seconds/minutes and then try it, it **works** for me.

But why cant code find the executable directly after the start?

**Comment by joaomoreno** [comment]
Oh. The screenshot points to the hint. It's not that it doesn't find git... it's just that it doesn't find the `git.clone` command.

**Comment by Palmer-JC** [comment]
I get this.  I was getting these 64-bit Visual studio available messages, so I un-installed the 32-bit. Installed the latest 64-bit today.  Decided to start things off by trying to clone inside of VS, so I can try its git commands.

Tried 'git.clone' from command palette.  Same message.  Opened an empty folder, just because, but I get this always.  This is not my most used IDE, but off a fresh install, I have not had much opportunity to screw it up.

Going back not worth it.  I do not even know it worked before.  I had never tried it. I will just ignore this capability, and command line GIT for this C# project.
![no_git](https://user-images.githubusercontent.com/7916131/33625758-a71f5154-d9c6-11e7-9997-b79f78321dd6.jpg)

**Comment by ibnuh** [comment]
I got same issues since I installed vscode few month ago, please help

![screenshot_19](https://user-images.githubusercontent.com/18393879/33777466-85842ef8-dc77-11e7-918e-43ba5cc57e77.png)
