### ISSUE TITLE
Enable crash reporting services for extension host

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#36540]
@bpasero What do we need to do to get this? I would like to browse extension host crashes in HockeyApp.

**Comment by bpasero** [comment]
@joaomoreno this is complicated because for each process to watch for we need another process for the crash reporter. 

@ramya-rao-a and me tried to enable the crash reporter for the extension host on macOS only (via [`getChildProcessStartOptions`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/crashReporter/electron-browser/crashReporterService.ts#L82)) but so far I have not yet seen a crash ending up in HockeyApp from the extension host, so I doubt this is working.

**Comment by ramya-rao-a** [comment]
@bpasero how are you differentiating the crashes from extension host vs other crashes? The last I checked, the only way to do this hockey app is to open crash details and look at the meta data

**Comment by bpasero** [comment]
@ramya-rao-a yeah I was going by the metadata which is very hard because you cannot search for metadata. I was never seeing an entry from the extension host so far.

**Comment by ramya-rao-a** [comment]
@bpasero Is there anything actionable here?

As far as I know, Hockeyapp is in a maintenance mode and there is no good way to differentiate extension host crashes vs other crashes.

**Comment by bpasero** [comment]
@ramya-rao-a my feeling is that this never actually worked. I got no evidence that a crash was from the extension host ever since we made the change to enable it. We should probably revisit that change and either fix it or take it out.

**Comment by ramya-rao-a** [comment]
The only way to see if a crash is from extension host is to go through each crash and look at its details, and since we cant do that, we cannot really say whether it worked or not.

I would keep the change.

In case we find a crash that happens often, then looking at its metadata we can atleast say whether it is from the extension host or not.

Unless we move to another crash reporting system that lets us parse through the crash details, there is no work to be done here.
