### ISSUE TITLE
Auto-enable python virtual environment in terminal

### ISSUE THREAD

**Issue by BenjaVR** [Microsoft/vscode#36585]
I opened this issue in DonJayamanne/pythonVSCode#1323, but it seems not possible to achieve this through an extension.

**Comment by akshaya-a** [comment]
One simple workaround I use is to set a startup script (init.ps1) for my integrated terminal in the workspace settings. In my specific case for powershell, using this for "terminal.integrated.shellArgs.windows" set to "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe":

https://stackoverflow.com/a/4845960

This has the added benefit of even more advanced setup (instead of just activating my conda env) as well as per-project conda envs tailored for that use case

**Comment by angryjohnnie** [comment]
This is something that has just broken for me with the most recent update I believe.

Previously I could start a venv then launch vscode with `code`.

The integrated terminal would then reference the version of python installed in the venv. This is no longer the case.

**Comment by scottbilas** [comment]
I put this in my workspace settings, and it works well enough:

```
"terminal.integrated.shellArgs.windows": [
    "powershell -noexit -command \"& {cd $env:VSCODE_CWD; . .venv/Scripts/activate.ps1}\""
]
```

Note: replace `.venv` with the relative path to your virtual environment.

May also want to add -noprofile if you want a clean (and faster to start) posh environment too.

**Comment by NOhs** [comment]
The scripts all have the disadvantage that they do not synchronize with the Python interpreter chosen interactively in vscode.

**Comment by Tyriar** [comment]
@DonJayamanne if you have a terminal API request to get this working I'm all ears, I don't know enough about the Python virtual environment to come up with a good solution.

**Comment by DonJayamanne** [comment]
@Tyriar the new API that you've added (event fired for when a terminal is created) should suffice. Yet to try and create a prototype using that API. Will try something this week and provide some feedback if things don't work as required.

**Comment by Tyriar** [comment]
@DonJayamanne nice! I created https://github.com/Microsoft/vscode/issues/52574 to make those ones stable as they're no brainers (compared to the other ones which need some more time).
