### ISSUE TITLE
Can no longer break in Unit tests using Code

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#3659]
I am trying to break in a test using Code and it does not work anymore. I am on Mac and add a breakpoint to fileService.test.ts#421 (test watchFileChanges).

The breakpoint is not hit but the tests seem to execute:

![image](https://cloud.githubusercontent.com/assets/900690/13487373/af0d1e70-e119-11e5-993e-84c57835e093.png)

**Comment by jvanoostveen** [comment]
I've discovered (on Windows) it no longer handles paths with spaces correctly. When removing the spaces in the path, breakpoints are hit again.

**Comment by bpasero** [comment]
This is on Mac without spaces.

**Comment by jvanoostveen** [comment]
I've just tried it on a Mac as well, breakpoints do get hit here, on both path with and without spaces.

**Comment by weinand** [comment]
@bpasero hitting breakpoints in TypeScript test just works fine.
The problem is with the tests in `service.test.ts`. They both create a server listening on the same port which results in EADDRINUSE error you are showing above. This prevents your `fileService.test.ts` to run.

If I uncomment the 'createService' test in `service.test.ts` the breakpoint in `fileService.test.ts#421` is hit.

It helps to let Mocha show what test are running by adding something like "-R", "spec".

**Comment by bpasero** [comment]
@weinand thanks! I disable the test now when run from within VS Code and now all tests run to the end and can be debugged.
