### ISSUE TITLE
Escape filename when dragging from explorer to the terminal

### ISSUE THREAD

**Issue by ShadSterling** [Microsoft/vscode#36597]
- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:12:42.401Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
angulardoc-vscode|Ang|3.0.2
angular2-inline|nat|0.0.17
java|red|0.12.0

---

Steps to Reproduce:

1. Drag a file with special characters in the filename from the EXPLORER sidebar to an Terminal.app window

Reproduces without extensions: Yes

**Comment by Polyergic** [comment]
Your bot is wrong, this is not about the integrated terminal, and does not affect the integrated terminal.

**Comment by Tyriar** [comment]
Reproduced, works dragging from Finder but not from explorer. I checked on mac as well but it likely affects Windows/Linux too.

For whoever picks this up there is some code that prepares a file from an outside or vscode explorer drag event for the terminal here: https://github.com/Microsoft/vscode/blob/cda7364a5c7c9201085284dd5ea4a3155a790c69/src/vs/workbench/parts/terminal/electron-browser/terminalPanel.ts#L311

**Comment by bpasero** [comment]
We cannot just run that method for DND because the same contents are used e.g. when dropping a file into another editor to paste it into the editor, doing some escaping would be odd in that case.

I think the only way to fix this is to introduce a new data transfer type that the terminal is preferring over the text/plain one.

Help welcome, code for the files explorer for example is here: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/browser/views/explorerViewer.ts#L797

**Comment by Polyergic** [comment]
If you're dragging from finder, you're dragging the file, not a string with the name.  Dragging from the VSCode explorer into Finder seems to copy the file (not move, as I'd expect without modifier keys).  Dragging from the VSCode explorer into TextWrangler gives an error when you drop in the file list (MacOS Error code: -4960), and pastes the (unescaped) full path when you drop in the edit area.  Dragging from Finder into TextWrangler opens the file when you drop in the file list, and pastes the content of the file when you drop in the edit area.  It seems like dragging from the VSCode explorer is dragging a string of the name rather than dragging the file itself.  I think that violates the principle of least surprise.
