### ISSUE TITLE
Unable to click and open mailto links in Markdown preview

### ISSUE THREAD

**Issue by wardoost** [Microsoft/vscode#36601]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:47:41.889Z)
- OS Version: Darwin x64 17.0.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.10.1
beautify|Hoo|1.1.1
quokka-vscode|Wal|1.0.72
path-intellisense|chr|1.4.2
vscode-svgviewer|css|1.4.3
vscode-eslint|dba|1.3.2
python|don|0.7.0
prettier-vscode|esb|0.24.0
flow-for-vscode|flo|0.7.2
markdown-shortcuts|mdi|0.8.1
color-highlight|nau|2.3.0
javascript-typescript|sou|0.0.5
vscode-todo-highlight|way|0.5.11

---

Steps to Reproduce:

1. Create a mailto link in markdown file `[Mail someone](mailto:someone@mail.com)`.
2. Preview markdown with `⌘K V` and click on link.
3. Doesn't open mail client with email address and error notification pops up `Unable to open 'someone@mail.com': no provider for mailto:someone%40mail.com.`.

Reproduces without extensions: Yes

**Comment by misoguy** [comment]
I'd like to take a look at this issue if no one is on it yet.

**Comment by mjbvz** [comment]
Great! While the error is thrown in [`remoteFileService.ts`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/files/electron-browser/remoteFileService.ts), the issue is actually much further up the callstack, in the [`openerService.ts`](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/opener/browser/openerService.ts) Take a look at how http and https links are being handled in there. We should probably handle mailto links similarly to http and https links

**Comment by misoguy** [comment]
Thank you for the heads up! I'll take a look into the code :)
