### ISSUE TITLE
Have a history per editor for in-editor navigation

### ISSUE THREAD

**Issue by Otiel** [microsoft/vscode#36634]
Could we have an option to stay in the current file when navigating back or forward using the following commands:
* workbench.action.navigateBack <kbd>Alt</kbd><kbd>←</kbd>
* workbench.action.navigateForward <kbd>Alt</kbd><kbd>→</kbd>

Currently, it navigates across all files, even the ones that have been closed.

**Comment by eteeselink** [comment]
I would like to add that this feature request might well be what most users expect. After all, VS Code is a tabbed view just like a browser is. When I hit "back" and "forward" in a browser I don't expect it to switch tabs either.

I guess you get the least surprising behavior by adding new commands `workbench.action.navigateBackInCurrentEditor` resp `workbench.action.navigateForwardInCurrentEditor` (not sure whether `editor` is the appropriate domain concept for "tab"). These could behave just like the existing actions, except they skip all the elements in the back-forward history that aren't in the current editor. This way you keep a single global multi-tab back-forward history which can be linearly understood.

**Comment by bpasero** [comment]
@Otiel @eteeselink so how would this work? The seed of the commands is the same as the current "Go Back" / "Go Forward" commands, but they would simply stop to work once either going backwards or forwards would jump to a different editor than the active one?

**Comment by Otiel** [comment]
@bpasero Not exactly. It should stop only if there is no more history to go to for the current tab, and it should "jump over" the history of other tabs.

Consider this seed of cursor positions:
* `Tab 1, Ln 1, Col 1`
* `Tab 2, Ln 2, Col 2`
* `Tab 1, Ln 1, Col 11`
* `Tab 1, Ln 1, Col 111`

At that point, if the focus in on `Tab 1` and I'm using the "Go Back" command twice, it should jump to `Tab 1, Ln 1, Col 11` then to `Tab 1, Ln 1, Col 1`.

**Comment by bpasero** [comment]
@Otiel but would you expect this to go all through one stack of history? Imagine you did go back once and it jumped over tab 2 but now you navigate forward with the normal "Go Forward", would you expect to end up in Tab2? 

In other words: should this feature run from a completely separate history stack than the one we already use.

**Comment by Otiel** [comment]
> Imagine you did go back once and it jumped over tab 2 but now you navigate forward with the normal "Go Forward", would you expect to end up in Tab2?

No, if I'm in Tab1, I should stay in Tab1 whether I'm calling "Go Backward" or "Go Forward".

> In other words: should this feature run from a completely separate history stack than the one we already use.

I would think that it would be easier to implement if there was one history stack per opened tab.

**Comment by jasonwilliams** [comment]
Is there still any possibility of this?

**Comment by ven1xus** [comment]
I also agree this should be a thing. For all ide's, dissasemblers, browsers, etc there is a navigate back and navigate forward (which i bind to mouse 4, mouse5). For vscode this isnt possible which is a little frustrating

**Comment by briankendall** [comment]
I agree that the behavior of navigateBack and navigateForward in VS Code is frustratingly different than what I expect it to be. However can someone clarify if this issue is requesting an option for it to behave the way I want?

If I understand correctly, "editor" in VS Code's terminology refers to a section of the window that has its own tab bar, and the window can be split into multiple editors, for example by using View > Editor Layout > Two Columns. (Please correct me if I'm wrong here.)

What I'm looking for would be back and forward navigation within a single editor only. So it would allow jumping between different files in the navigation history, but only within that editor. This, incidentally, is the same way it works in Qt Creator in case that's helpful.

Is that within the scope of this issue? It sounds like what @eteeselink is talking about, but I'm not 100% sure, and there's also an open issue #45233 that might be what I want.

**Comment by pauljamescleary** [comment]
I would mention, sorting open editors by "most recently visited" would be useful as well (like CMD-E in IntelliJ).  There, CMD-E auto selected the last editor every time, allowing one command to switch back and forth

**Comment by mlewand** [comment]
Just to add 2 cents: I'd really love to see ability to navigate history within a single file. Current solution makes me to lose my focus so many times, that I typically just skip using it and browse files manually.

IMHO if you want to switch across files you use hotkey to access n-th file in your tab list (or eventually use ctrl+tab as a last resort).

**Comment by LinAGKar** [comment]
> I would like to add that this feature request might well be what most users expect. After all, VS Code is a tabbed view just like a browser is. When I hit "back" and "forward" in a browser I don't expect it to switch tabs either.

The difference though is that when clicking a link to a different site in a browser, you remain in the same tab, and can go back to the previous site with the back button, while in vscode you would go to a different, possibly existing, tab due to having one tab per open file.

Not that this function shouldn't be available.

**Comment by rob-miller** [comment]
> No, if I'm in Tab1, I should stay in Tab1 whether I'm calling "Go Backward" or "Go Forward".

> I would think that it would be easier to implement if there was one history stack per opened tab.

I would like to see this supported with buttons probably in the top right corner of an editor pane (region shown under tab bar for a selected tab):

<img width="960" alt="Screenshot 2020-04-28 at 10 07 21" src="https://user-images.githubusercontent.com/3370432/80469557-a2c1b880-8938-11ea-9d39-6293d139f178.png">

I believe this would make the "history within this tab" behavior intuitive, and also quick to find when an action surprises by jumping to a different location.  

Similar buttons are also suggested [here](https://github.com/microsoft/vscode/issues/42617#issuecomment-577293810) but in reference to #42617.

**Comment by remorses** [comment]
go back should not switch tab, this is really bad UX

**Comment by Machiaweliczny** [comment]
This would be super useful for reading code. 

I often cmd+click some function to read them and then want to go back, but maybe in meantime I switch to other tab to read something else - not having history per tab is so annoying.

**Comment by ugurkoltuk** [comment]
This would make reading code *so much* easier. Exactly like the browser tabs, vscode shouldn't jump between tabs when you go back and forth.

I also think clicking a name in vscode should go to the definition/declaration of that name in the same tab, unless one clicks "open in new tab" (which does not exist now, but it would be great too).

Basically, IMO, if tabs and navigation behaviour of vscode was exactly the same as that of browsers, that would be the least frustrating and the most intuitive, since everybody knows how to use browser tabs.

**Comment by remorses** [comment]
This issue makes me mad every time i go back with more than one tab open, @kieferrm can this be added to the next months Iteration Plan?

**Comment by LinAGKar** [comment]
>I also think clicking a name in vscode should go to the definition/declaration of that name in the same tab, unless one clicks "open in new tab" (which does not exist now, but it would be great too).

That would make "go to declaration" close the current file though, which I would not want.

**Comment by ugurkoltuk** [comment]
> That would make "go to declaration" close the current file though, which I would not want.

That's the default behavior if you have single tab isn't it? All I'm asking is to keep tabs isolated.

Anyway, I'm also okay with a config option like "editor.openDeclarationsInNewTab" which is true by default, so it behaves like you want, but I can override if I need to.

**Comment by vilic** [comment]
I often have two editors group opening the same file, and navigating from the second one would result in cursor jumping to the first one. Which is really disturbing.

**Comment by pablospe** [comment]
Isn't `Ctrl+U` (Cursor Undo) what you need?
Cursor Redo is typically not assigned.

**Comment by LPTK** [comment]
@pablospe close, but not quite. I just tried it, and cursor history seems to be wiped as soon as I switch tab, so that when coming back to a tab, hitting "Cursor Undo" always sends the cursor to the very first line of the file, instead of its previous location.

**Comment by vikaschoudhary16** [comment]
waiting for this since years. This is the only missing functionality which is no letting me switch over to vscode from vim

**Comment by AdmiralKirk1701** [comment]
Yes, I would have to agree. This is a critical issue that needs to be fixed just as soon as possible.  There are a lot of little quirks in VScode that I can live with, but this issue is driving me insane, and costing dev time.  I often have several versions of the same source code loaded into many tabs, and it is just way to easy to end up editing the wrong file because alt+left navigation forcibly switched me to a different file.  I'll donate $20 if you guys can get this fixed this week or next :)  LOL. Getting desperate :)

**Comment by Blackman-Harris-Window** [comment]
Friendly bump of this thread.  This is a critical UX issue that is still open and needs to be addressed.  Thanks!

**Comment by Townsheriff** [comment]
I'm also very interested in this feature request. In my case I have two tabs open side by side in one side to check function declarations, types, etc. and in the second tab I'm actually doing the work. Once I press back button on my mouse it sometimes switches the tab and goes to a different file - that is super annoying and distracting.

**Comment by jasonwilliams** [comment]
Did anyone work on a PR for this? It looks like @Otiel @eteeselink  had some good ideas but it seems to have stalled. The UX is really jarring when hitting back and forward.

**Comment by aloucks** [comment]
I can't stress enough how frustrating it is when back/forward jump between different editor groups. The current behavior is analogous to having multiple `notepad.exe` windows cascaded on the monitor and back/forward jumping to between windows.  

I **never** want code navigation to change my active editor.

**Comment by bpasero** [comment]
Added a new setting `workbench.editor.navigationScope` that can be configured to `editor` to limit navigation actions such as "Go back" and "Go forward" to the current active editor group.

**Verification**
* review the `workbench.editor.navigationScope` setting makes sense to you
* enable `editor` as scope and validate that commands such as "Go Back", "Go Forward", "Go Last" and "Go Previous" only operate on the active editor in the active editor group
* verify each editor has its own stack that can be navigated individually backward and forward
* verify you never end up in the editor of a different group when navigating with this setting

**Comment by adaszko** [comment]
Just wanted to say thank for you implementing this 🙏 .  The editing experience is so much better now ❤️

**Comment by bpasero** [comment]
Thank you ❤️

**Comment by briankendall** [comment]
Ah, finally I can navigate in VS Code the way I need to! Thank goodness. The previous navigation behavior was the one thing about an otherwise good editor that was driving me absolutely insane on a daily basis!

Also, I applaud the `workbench.editor.navigationScope` having settings for both editor group and editor. That satisfies everyone's use case nicely and includes #45233.
