### ISSUE TITLE
Support global application menu in Ubuntu 17.10

### ISSUE THREAD

**Issue by ilyahoilik** [microsoft/vscode#36667]
Ubuntu 17.10 now uses GNOME instead of Unity.

I think it is better to move menu items from the menu bar to the GNOME application menu.
https://developer.gnome.org/hig/stable/patterns.html.en
https://developer.gnome.org/hig/stable/application-menus.html.en

It can help us to save a lot of work space.

**Comment by ZanderBrown** [comment]
#39511 is relevant here

**Comment by ZanderBrown** [comment]
GNOME has actually dropped that menu now so this issue is somewhat defunct

Still need a symbolic icon for the app menu's replacement and high contrast modes though

**Comment by bpasero** [comment]
@ilyahoilik can I ask you to report this against Electron?

**Comment by bpasero** [comment]
This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to the code. As such, I will go ahead and close it. If you can identify the component that is causing the issue, please report it upstream:
* for UI, OS integration: https://github.com/electron/electron
* for Rendering: https://bugs.chromium.org/p/chromium/issues/list
* for file IO: https://github.com/nodejs/node

Thanks for understanding.
