### ISSUE TITLE
Wrong Icon for Executable. Electron Icon shown instead of VSCode's.

### ISSUE THREAD

**Issue by Suraj-Yadav** [Microsoft/vscode#36665]
- VSCode Version: Code - Insiders 1.18.0-insider (65c08338e4bece35fb53f5a1cdf56d30b7706157, 2017-10-20T15:35:45.848Z)
- OS Version: Windows_NT x64 10.0.15063

Steps to Reproduce:

1. After update to latest Insiders version, this icon changed to electron icon.

![image](https://user-images.githubusercontent.com/6687881/31847603-c97da74e-b63c-11e7-85cb-147e23a90742.png)
![image](https://user-images.githubusercontent.com/6687881/31847627-05e43f9a-b63d-11e7-9c52-0aec24a593f6.png)

Reproduces without extensions: Yes

**Comment by johnunclesam** [comment]
Here the same problem.

![image](https://user-images.githubusercontent.com/21275217/31851276-cb38de84-b662-11e7-984e-98c7d7794031.png)

![image](https://user-images.githubusercontent.com/21275217/31851280-d5258d5c-b662-11e7-9394-2c591b92b643.png)

**Comment by ciel** [comment]
Same here.

**Comment by changavila** [comment]
Just updated mine an hour ago, and now i'm having the same issue.

**Comment by kborowinski** [comment]
Someone's tired of that whole icon drama? #35783

**Comment by dlong500** [comment]
What's sad is that I actually prefer this to the orange icon...

**Comment by christopherwolf1** [comment]
I am having this problem too; at first I thought it was some icon cached by Windows for a generic Electron binary, so I cleared all the caches and that didn't help. Then I thought to open up freshly downloaded zip files instead of using the MSI installer packages. The Portable ZIP install for VS Code is fine as you can see (it even includes the proper branding information content)...

![image](https://user-images.githubusercontent.com/15132959/31855805-82d4b21c-b667-11e7-8faf-4545260013e0.png)

But the one for VS Code Insiders is obviously quite different...

![image](https://user-images.githubusercontent.com/15132959/31855820-c491780c-b667-11e7-971b-1c8d39416cd9.png)

That means they are baked in that way from the beginning; I take it that means that the icon files and the branding information were not entered correctly in the workflow to package the Electron app for the latest build of VS Code Insiders.

**Comment by cotts** [comment]
Same Here

**Comment by Huyvu7495** [comment]
The Process name in Task Manager is also Electron
In Processes tab
![image](https://user-images.githubusercontent.com/10388179/31858864-4ecd7006-b72c-11e7-8c67-8b02ff838ab1.png)

In Details tab
![image](https://user-images.githubusercontent.com/10388179/31858868-59a71720-b72c-11e7-9bcc-88bf3796eece.png)

**Comment by bpasero** [comment]
@joaomoreno did something change in `gulp-atom-electron`?

**Comment by RDeluxe** [comment]
Same here.

**Comment by bpasero** [comment]
@joaomoreno is taking care of it and starting new builds.

**Comment by jtsom** [comment]
Latest insiders still shows Electron icon.

**Comment by frankhale** [comment]
@bpasero I think this issue needs to be reopened as the problem still exists even with today's update.

**Comment by changavila** [comment]
The icon is now Ok, but in the task bar its still the electron.
![image](https://user-images.githubusercontent.com/13307287/31982500-ad3aa1d4-b98b-11e7-8915-429b7ec6a873.png)

**Comment by christopherwolf1** [comment]
It appears to have (mostly) fixed it for me, see below; 

Taskbar:
![image](https://user-images.githubusercontent.com/15132959/31984004-9b775b30-b914-11e7-844a-e50c608a3c38.png)

Titlebar:
![image](https://user-images.githubusercontent.com/15132959/31984021-b246fb4a-b914-11e7-83ed-72cdde4d1e3b.png)
 
File Explorer Details:
![image](https://user-images.githubusercontent.com/15132959/31984067-dca0759c-b914-11e7-994e-52fd15a78621.png)

Task Manager Processes:
![image](https://user-images.githubusercontent.com/15132959/31984104-01b2e72a-b915-11e7-88b4-d83da8c1ea56.png)

(Now that is a little bit unusual, I will admit)

I will experiment with flushing the icon cache and rebooting, although most of the places the icon shows up should be correct now.....Don't know exactly what is going on with the Task Manager example, though.

**Comment by liam-potter** [comment]
This is now fixed for me (after a couple of updates) on Windows 10 64-bit 1703 (15063.674).

**Comment by cotts** [comment]
Fixed for me today!

**Comment by changavila** [comment]
Its now fixed.
