### ISSUE TITLE
Launch configuration to debug a program that starts its own debug process

### ISSUE THREAD

**Issue by electrotype** [Microsoft/vscode#36685]
I asked [the question](https://stackoverflow.com/questions/46800810/vscode-how-to-debug-a-node-program-that-starts-its-own-debugger-using-a-launc) on Stack Overflow (50 points bounty!) but received no answers.

Is it possible to have a `launch configuration` that is going to attach a debugger to a debug process _started by the launched program itself_?

I want my `launch configuration` to start a script in VSCode's integrated  terminal. This script will ultimatly use `Nodemon` to start a debug process, on port 5858, by itself. I'd like the `launch configuration` to attach a debugger to this debug process. Is it possible?

**Comment by isidorn** [comment]
Yeah, should be. Try using `compound` launch configuraiton.  More about that here https://code.visualstudio.com/docs/editor/debugging#_compound-launch-configurations

What might be missing is the timeout for the attach. In that case there is probably an open feature request for that which you can find and upvote. As a workaround you can use 2 independent launch configs, since we support launching two at the same time.

**Comment by electrotype** [comment]
A `compound` launch configuraiton doesn't work, I always get a "`Cannot connect to runtime process (reason: This socket has been ended by the other party).`" error. Launching the two launch configs one after the other does work, indeed... But is not ideal. 

I guess the issue if indeed the timeout for the attach config... I though the "`timeout`" property was exactly that, but I guess it's not.

**Comment by electrotype** [comment]
See the StackOverflow question for an anwer! It's not perfect, since the debugger doesn't re-attach itself in time when a change is made and Nodemon restarts the application, but eveything works fine otherwise!
