### ISSUE TITLE
No way to escape forward slash in snippet regex

### ISSUE THREAD

**Issue by bradzacher** [Microsoft/vscode#36715]
There's no way to escape forward slashes `/` in the snippet regex syntax.
This makes it impossible to replace/substring paths in snippets.

All of the following fail:
```
${TM_DIRECTORY/(src/)/$1/}
${TM_DIRECTORY/src[/]/$1/}
${TM_DIRECTORY/(src[/])/$1/}

${TM_DIRECTORY/src\//$1/}
${TM_DIRECTORY/(src\/)/$1/}
${TM_DIRECTORY/src[\/]/$1/}
${TM_DIRECTORY/(src[\/])/$1/}
```

For example, I am trying to create a snippet which declares a mock for the given file, so I have to strip the leading directory structure (i.e. everything before and including the `src` folder), as well as `__mocks__/`.
```
${TM_DIRECTORY/.+?\/src\/(.+?)\/__mocks__\/.*/$1/}
```
But this doesn't work, as VSCode just rejects the replacement due to the forward slashes.

I can work around this by doing a dodgy match because I know the structure of the paths will always look in a certain way.
i.e. remove the forward slashes from the regex, and select the slash trailing `src` using `.` to match the forward slash.
```
${TM_DIRECTORY/.+?(src.)(.+?)(__mocks__).*/$2/}
```
but of course if there's ever a nested folder that has `src` in it, then it will break the snippet.

**Comment by jrieken** [comment]
`${TM_DIRECTORY/src\//$1/}` should be the winner, tho keep in mind that the backslash needs an extra backslash to encode it in JSON.

**Comment by lcruz4** [comment]
@jrieken that seems to work in the regex section but not in the format section

I want a forward slash in front of the $1 but nothing seems to work. I don't think there is anyway to get this to work, because if I can successfully escape the / it acts as the separator. 

if I have
aaa
`${TM_SELECTED_TEXT/a/\/$1/g}` produces ${TM_SELECTED_TEXT/a///g}
it looks like it is just replacing the text with the literal string as there are too many forward slashes
`${TM_SELECTED_TEXT/a/\\/$1/g}` produces ${TM_SELECTED_TEXT/a/\//g}
so it looks like the same issue.

**Comment by mjbvz** [comment]
Verified original bug. Opened  #37562 to track @lcruz4's problem

**Comment by brianjorden** [comment]
Just to provide another example, I was just trying to deal with the same issue. I'm attempting to take a filename and output a split version with a `/` forward slash between the first "word" and the rest of the filename. For an actual example, I have a file named `ContactCreate.vue` so the `TM_FILENAME_BASE` ends up being `ContactCreate`. From my snippet `${TM_FILENAME_BASE/(^[A-Z][a-z]+)([A-Z].*$)/${1:/downcase}\\/${2:/downcase}/}` I'm expecting, but not getting, a result of `contact/create`. Obviously I can work around this for now, but thought I simply had the syntax wrong for a while there.
