### ISSUE TITLE
Editor Langsam nach Ordnerwechsel / Editor Slow after switching folder

### ISSUE THREAD

**Issue by Rindula** [Microsoft/vscode#36761]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
vscode-color|ans|0.4.5
sqf|Arm|1.0.4
python|don|0.7.0
gitlens|eam|5.7.1
vscode-html-css|ecm|0.1.8
vscode-npm-script|eg2|0.3.1
php-debug|fel|1.11.1
php-intellisense|fel|1.5.2
auto-close-tag|for|0.5.2
code-runner|for|0.7.4
cpptools|ms-|0.14.0
PowerShell|ms-|1.4.3
sqflint|ska|0.8.3

---

Steps to Reproduce:

1. (Zum Vergleich) Datei verändern und abspeichern
2. Ordner wechseln (mit STRG+K STRG+O)
3. Datei dort verändern und abspeichern

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.
