### ISSUE TITLE
Provide a way to highlight unmatched brackets

### ISSUE THREAD

**Issue by jkyeung** [Microsoft/vscode#36779]
Right now, it seems that the most reliable way to tell whether a bracket is unmatched is to try putting the cursor next to it and see if the bracket and its match are highlighted. If you've tried putting the cursor on both sides of a bracket and it doesn't get highlighted, it's (almost definitely) unmatched.

Clearly, this isn't as desirable as having the option to set some styling for the unmatched bracket.

**Comment by Spown** [comment]
Many [linters](https://marketplace.visualstudio.com/search?target=VSCode&category=Linters&sortBy=Downloads) would deem your source invalid if there is unclosed/extraneous brackets there and point you to the line:col. VSC doesn't do linting - only syntax coloring.

Please don't forget to close the issue.

**Comment by jkyeung** [comment]
@Spown - Respectfully, your response is dismissive. Why does VS Code attempt to highlight matching brackets at all? Why isn't *that* something left up to linters? The fact is, there are editors out there, often much less full-featured than VS Code, which already do what I am asking. (This is why I am asking in the first place!) And clearly, if the program knows *not* to highlight a brace when it is unmatched, then it *could* instead choose to highlight it using the very same logic.

**Comment by Spown** [comment]
My response is in accord with your OP which is "...a way to highlight unmatched brackets". Unmatched bracket - is a problem. It's a problem matcher's (i.e. linter's) job to point them out to you. "Much less full-featured" editors do not separate workflow into clearly separated logical layers and throw the features into the heap. VSC's syntax highlighting assumes the code to be valid, whether or not it is the fact.

The same goes for the ``Go To Bracket`` function:
```js
1{
2    {
3        {
4        //}
5    }
6}
```
You can set the cursor at 3 and go to the matching bracket, which will be at 5. But it only will ever be truly unmatched if there is no closing brackets untill the very document's end. That's why you need a linter that would try to build an abstract syntax tree and localize the true problem.

Anyway I made my point. And you just want a "magic button". I sincerely wish for your wish come true but I can't help but to explain why it probably won't. 

c ya

**Comment by jkyeung** [comment]
@Spown - I'm not asking for a magic button. I am not asking for any new or complicated logic. I am saying that when the cursor is adjacent to a bracket, there is *already* logic in place which determines whether to highlight it or not. This is already in the VS Code standard installation and has been for a long time. When that logic comes to the conclusion "this bracket should not be highlighted, because it's not a match", I am proposing to put user-definable highlighting *at that point in the logic*, so that the unmatched bracket stands out. When the cursor is somewhere else, it goes back to not being highlighted, just the way *matched* brackets are currently unhighlighted when the cursor is elsewhere.
