### ISSUE TITLE
extra characters are added to the links in the terminal 

### ISSUE THREAD

**Issue by capaj** [Microsoft/vscode#36806]
- VSCode Version: Version 1.17.2
Commit b813d12980308015bcd2b3a2f6efa5c810c33ba5
Date 2017-10-16T13:57:00.652Z
Shell 1.7.7
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
- OS Version: ubuntu 17.10

Steps to Reproduce:

1. print an output like this into the terminal:
```
templateData:  { event:
   { title: 'event one',
     location: 'room 1',
     description: 'not much 1',
     when: 'Mon. Nov 20, 11pm - 11 pm',
     timezone: 'BST',
     link:
      { yes: 'http://looopco.loc.dev:3000/#/event/1?confirm',
        no: 'http://looopco.loc.dev:3000/#/event/1?confirm=false' } } }
```
2. click on one of those URLs while holding down ctrl

expected result:
a proper link is opened

actual result:
a link is opened, but it has an extra `',` for the yes link and `'` for the no link

Reproduces without extensions: Yes

probably the regex used for the links needs tweaking

**Comment by Tyriar** [comment]
Unfortunately the `'` character is valid in URIs which is why this is happening. To support this we'll need to use a proper parser for link detection, not the simple regex-based system currently being used. Closing this in favor of https://github.com/sourcelair/xterm.js/issues/583, subscribe there for updates.
