### ISSUE TITLE
Document hidden settings

### ISSUE THREAD

**Issue by rbiggs** [microsoft/vscode#36813]
Please consider documenting all the settings, particularly the `hidden` ones. Often times users have issues that are only solved after a team member reveals there's a `hidden` setting that solves the problem. Finding the hidden setting mentioned in the thousands of issues here can be haphazard and take days or even weeks. I've been through this too many times, wasted time and lost productivity. Every time I set up a clean install the long process of search for mention of `hidden` settings begins.

Suggestion: document all `hidden` settings somewhere on the VSCode website with a proper explanation of what issue they might solve for users. 
By the way, I'm talking about `hidden` settings such as:

```json
"editor.parameterHints": false,
"editor.detectIndentation": false,
"editor.hover": false,
etc.
```

**Comment by alexandrudima** [comment]
Here is source code where they are documented: https://github.com/Microsoft/vscode/blob/b9478c2d5904c6a06b850bcf3d5d3ea25d175d0a/src/vs/editor/common/config/editorOptions.ts#L131

Here is a website where they are documented:
https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.ieditoroptions.html

They are not "productized" (i.e. do not show up in the settings editor of VS Code) because they have various issues. i.e. some of them require a product restart, some of them don't always work correctly, e.g. have you noticed that after a debug session, `editor.hover` is always set back to true, etc. There is some fair amount of real work to make them fully-functional user-facing setting (like the other settings).

**Comment by mjbvz** [comment]
Many of these have since been made into real, documented setting. Please open new issues for ones that may still be missing
