### ISSUE TITLE
Feature suggestion: hide types in TypeScript

### ISSUE THREAD

**Issue by rnemec** [Microsoft/vscode#36823]
One of good things in JS is that it is not as talkative as e.g. Java and reading the code means less text to mentally process.

For developers switching from JS to TS, would you consider having an option to **hide** parameter and variable type declarations (`: Promise<MyVerySpecialClass<Entity123Model>>`)?

**Comment by mjbvz** [comment]
Can you please provide more information about the problem you are running into?

I don't think fully hiding types is a solution. In many cases, type-inference can be used so that you do not have to explicitly write out the types. In the others, the types are part of the program. They provide important information to both the type-checker and to the programmer

**Comment by rnemec** [comment]
It's a GUI request:
I'm suggesting an option to hide, not stop using types. Same idea as folding a loop body. It's not gone, just hidden from seeing when not needed to see, or too distracting to see.

Same with the types - they may get too talkative. Often just seeing the parameter name is enough for quick reasoning about the method, while still having the detailed info there when needed.

**Comment by mjbvz** [comment]
My take: type info on a function helps you understand what the function does just as much as the implementation itself. At a glance, types are probably even better actually than trying to look through the implementation

It is also not clear how this would be implemented because you do still need to write and modify type annotations in order to write proper code. 

Would a custom grammar that visually de-emphasises type annotations help you?

**Comment by rnemec** [comment]
@mjbvz you raise 2 points:
1. types are good, use them
1. how you edit your files when something is hidden

Re 1: This is for folks coming from JS land. It is much preferred to see
```JS
function processUsers(users, adjustFn) {
}
```
This is not about NOT having the types, it is about quick reading of code.

Re 2: How do you edit your files when something is folded? You unfold the area (or editor even does it for you). Same here. It's a flavor of folding. Coloring it differently may help a bit but the problem is still about the inflation of text and spread of the code logic that may be distracting.

**Comment by mjbvz** [comment]
But what benefits would that bring besides presenting a more familiar look? My point is that for quickly scanning through code, the types are just as helpful as symbol names in most cases
