### ISSUE TITLE
Discuss usage of 'U'-character for untracked git items

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#36912]
Let's use this issue to discussion what letter/icon to use for added/untracked git resources. This is a continuation from https://github.com/Microsoft/vscode/issues/178#issuecomment-339081094 and an effort to keep the original, already huge, item a little more focused.

**Comment by jayjun** [comment]
Thanks @jrieken. I’m in favour of three colours only (excluding greyed ignored files), and each colour should have one letter associated only.

My preference is,

Untracked/Added Files
Green
A

Modified Files
Yellow
M

Deleted Files
Red
D

It’s the exact same scheme used by Atom and Xcode too (less context switching).

**Comment by WadeShuler** [comment]
Fair enough to give it its own attention :) I know my position has been stated in the other thread, I’ll post it here for clarity.

**Untracked:** These technically are new to add files. They are not in the Git tree at this point. You have added them to your project, but not in version control. Thy also are not staged at this point. Since “U” can be intreprered as “updated”, I vote we do not use it. **I believe “A” is the most appropriate.** - I feel we should put ourselves in the shoes of a newbie, who probably doesn’t understand anything more than copy-n-paste Git commands. They would not understand that “U” means untracked. They also wouldn’t understand what “??” represents. Which is why, I recommend “A”.

**Modified:** Fine as it is from what I recall from my last test run of Insiders.

**Deleted:** Fine as it is from what I recall from my last test run of Insiders. I think the “D” was a dark brownish red and the file names in Source Control tab had a line through them.

**Staged:** A darker red color. Not red colored on Source Control tab, as we can see staged group there, and could see diff between staged added and staged modified. Staged support should be optional with a setting to enable/disable it. I don’t care if it is enabled by default, I am fine with manually turning it on. If more people love it, an issue could be opened later to change it to be enabled by default in newer versions. Maybe even let people vote.

—

**Badges:** The new way without the background color bubble, just the colored letter. The file tree and Source Control tab had different sized bubbles, they looked squished, and just the letters fits Code better and looks cleaner.

What to do when both added and modified are within same directory: Atom makes the status of the parent directories (all the way up to project root) “modified” (yellow) when there is  A) modified file(s) - B) both modified and added files.

When there is only an “added” file, the parent directories (all the way up to project root) are “added” green.

So in short, the parent dirs take the status color when there is only 1 type. In the event there is both, added and modified, it considers it modified.

The directory colors go all the way up to the project root. In this project path, ‘/project/src/backend/controllers’ if you add a new file into ‘controllers’, then these folders will all turn green: controllers, backend, src. Same for if you modify a file, only they would turn yellow. If you add a file in ‘controllers’ **and** also modify a file in ‘controllers’, then the mentioned folders would turn yellow as modified. Modified overrules added.

For staged, I think it should turn the staged color, ie ‘red’ up the dirs. Staged would override modified and added.. This is good for cherry picking and ensuring all your files are included in your commit. Since staged is only temporary, they would only be red for a few seconds or minutes, until you get them staged. So it shouldn’t be an issue to do this.

Just my 2 cents. Coming from Atom, as a lot of people are, this makes the most sense.

**Comment by jayjun** [comment]
Often the solution to such diverse views is to allow customisation.

I’d imagine this is easier now that badges are single letter characters. It also allows those who don’t like badges to turn them “off” by setting `""` (selectively as well).

```json
{
  "git.badge.untracked": "A",
  "git.badge.modified": "M"
}
```

**Comment by dseipp** [comment]
Agreed with @jayjun regarding customization.  While desiring to migrate from Atom to the better editor, forging ahead with a better way is good too.  For those that like the 'U' from Atom, they will be able to change it to their liking.  :)  Defaulting to 'A' for added (untracked) seems more logical to me as well.

**Comment by WadeShuler** [comment]
@dseipp Where in Atom does it use the ‘U’ ? It doesn’t stock, unless my
theme overrode it?, I’m not sure if your using an extra plugin or not? On
my modified files, it puts a yellow dot before the file on the Git tab.

I’m not calling you out, I just don’t want mis-information to inaccurately
influence the ideas/development of this issue in Code.

**Comment by dseipp** [comment]
@WadeShuler , sorry, I was going based off of what others were saying regarding liking the 'U'.  May have misunderstood.  I will amend my comment.

**Comment by saada** [comment]
I feel differently about this. I think we shouldn't be using alphabetical letters at all.
I'm more on the symbol opinion. 
Something along the lines of

```
+: added
-: removed
*: modified
?: untracked
```

What do you guys think?

**Comment by WadeShuler** [comment]
@saada No, I don't think so. Nobody will know what it means, they will have to look it up online, and it would result in un-necessary issues/questions all over for something very very basic.

When creating things like this, it's always best to look at the "barrier to entry". Take a new programmer, opens up code, and doesn't know what much of anything is.. Your adding 1 more thing to the list that they have to look up and learn... You want to try your best to make it where the first time they see it, they understand what it is.

**Comment by joaomoreno** [comment]
Personally, I don't think it's a problem currently and I would just keep it.

**Comment by dseipp** [comment]
Now that we've been using for a while, what do people think?  Personally, every time I see the 'U' I still think 'Updated' and need to continue to remind myself that it's 'Untracked'.

**Comment by WadeShuler** [comment]
Yeah. I went back to Atom for a bit tbh. My 2 issues with VSCode are that the Git status coloring isn’t finished yet, and every time I paste code, it messes up the indenting. Once this gets finished, even if in Insiders, I will probably come back to Code and see if I can straighten out the indenting on pasting.

I agree, the ‘U’ has got to go as it’s counterintuitive.

**Comment by gulshan** [comment]
How about an U with strikethrough- ~~U~~ ?

**Comment by WadeShuler** [comment]
It's still a `U`... The problem we are having, is that at first glance, not thinking about Git and it's underlying statuses, the `U` immediately makes (some of) us think `Updated`.

From the perspective of using an editor and choosing "File > New File", you are "adding" a new file to your file tree. It has been "added" since your last state.

Only somebody who is comfortable with Git would know the various git statuses. Beginners would be opening GitHub issues, Stack Overflow questions, Quora Questions, probably even Microsoft issues, every few weeks asking what the `U` means.

I know when the badges had a rounded background "bubble", they were SVG files. Which meant the letter used, ie: `U`, can't be changed (at least easily). Since that has been done away with and it is just a letter, it shouldn't be using an SVG file anymore.

I don't care what it is by default, so long as I can change it with a config setting, like this for example: `git.status.untracked.letter: "A"`

**Comment by faustotnc** [comment]
I don't know if I should be writing this on here, but I hate that all my files are Yellow or Green. I really don't care about the icons, but the color green is really uncomfortable to the eyes.

**Comment by petkahl** [comment]
@faustotnc you can turn the colors off by setting explorer.decorations.colors to false in the settings.

**Comment by faustotnc** [comment]
Thanks @petkahl That really did help! Looks a lot better now.

**Comment by jrieken** [comment]
Closing because no code change is planned
