### ISSUE TITLE
Support Workspace tasks in a MR workspace

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#36966]
In a Multi-root workspace, provide support for Workspace tasks

**Comment by coyoteecd** [comment]
Is there any way to reference tasks from launch configurations defined in a .code-workspace file, even if the workspace is not a MR workspace? 

My setup is just a simple .code-workspace file in the root folder, configured with 
```
  "folders": [{
    "path": "."
  }]
```

I have launch configurations added in the workspace file, but cannot use a preLaunchTask because I keep getting the error mentioned in https://github.com/microsoft/vscode/issues/58818#issuecomment-424688853. I tried moving tasks.json in the root folder next to the workspace file, because the error seems to complain about folder location. But the error is the same. 

Am I missing something, or having launch configs in the workspace itself, single or multi-root, just doesn't work properly?

**Comment by sandy081** [comment]
@alexr00 I remember you started on this. May I know the status?

**Comment by alexr00** [comment]
It's in. Tasks from folder cannot be referenced from tasks in workspace files. The user settings tasks are still in a PR for you.

**Comment by sandy081** [comment]
Ok then I will close this and the other issues can be (or already) tracked separately.
