### ISSUE TITLE
Etiqueta Sombreada 

### ISSUE THREAD

**Issue by gustavorg** [Microsoft/vscode#37019]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 6.3.9600
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
vscode-html-css|ecm|0.1.8
vue-snippets|hol|0.1.5
sublime-keybindings|ms-|2.9.1
vscode-icons|rob|7.16.0

---

Steps to Reproduce:

1. Al hacer click en un tag html se sombre todas las demás, como hago para que al hacer click SOLO ME SOMBREE el tag de cierre

Reproduces without extensions: Yes/No

**Comment by aeschli** [comment]
Google translate:
When I click on an html tag it shades all the others, like I do so that when I click, I just hide the closing tag

Hi @gustavorg. This works for me in HTML files. Are you maybe in a PHP file? Also try to disable all extensions.
![image](https://user-images.githubusercontent.com/6461412/32097425-d9ca955e-bb09-11e7-88e0-5cce57f91e1d.png)
