### ISSUE TITLE
Disabling indentation detection is not enforced

### ISSUE THREAD

**Issue by BrendanBall** [Microsoft/vscode#37022]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:57:00.652Z)
- OS Version: Linux x64 4.13.8-1-ARCH
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
xml|Dot|1.9.2
vscode-docker|Pet|0.0.20
python|don|0.7.0
Go|luk|0.6.66
hg|mrc|1.2.0
mssql|ms-|1.2.0
azure-account|ms-|0.1.3
erlang|pgo|0.1.1
java|red|0.12.0
vscode-apielements|vnc|0.6.7

---

Steps to Reproduce:

1. Define user settings for apiblueprint:
```
    "[apiblueprint]": {
        "editor.tabSize": 2,
        "editor.detectIndentation": false
    }
```
2. Open apib file
tabsize changes despite setting detect indentation to false.

Note: apib files contain varying different indentations for different parts of the spec. eg.

```
+ Model

    + Headers
```
contains a tabsize of 4 spaces (or rather think of it as 2 tabs)

where actual json contains tabsize of 2 spaces, so detect indentation doesn't really work. But if I turn that feature off it should stick to my defined tabsize

Reproduces without extensions: Yes/No
No

**Comment by alexandrudima** [comment]
This works fine for me. I believe it got fixed in the meantime.

```
    "[plaintext]": {
        "editor.tabSize": 7,
        "editor.detectIndentation": false
    },
```

I create a file `test.txt` with the following content:
```
    4 spaces
    4 spaces
    4 spaces
    4 spaces
    4 spaces
    4 spaces
    4 spaces
    4 spaces
    4 spaces
```

The indentation guesser would typically guess that this file is indented with Spaces@4. When opening the file the bottom status bar shows Spaces@7.
<img width="72" alt="image" src="https://user-images.githubusercontent.com/5047891/33267592-5b9e0a60-d37a-11e7-8727-0342bbf57aa2.png">
