### ISSUE TITLE
VSCode walks all files under project, even excluded directories

### ISSUE THREAD

**Issue by ridiculousfish** [Microsoft/vscode#3703]
VS Code currently walks all everything under the project's directory, even excluded files.

1. Go to some project folder
2. Create a big directory hierarchy in a subfolder. `git clone https://github.com/torvalds/linux.git` will do it.
3. Launch VSCode and open the project folder
4. Using `fs_usage` or equivalent tool, notice that VS Code is walking that hierarchy and stat'ing all files in it
5. Try to add a setting to exclude the file:

            "files.exclude": {
                "linux/": true
            }

6. Repeat step 3 and 4. Notice that the linux directory no longer appears in the sidebar, but VS Code still walks the directory and stats everything.

In my case I have a few million files, and this directory traversal is a serious slowdown.

VS Code Version 0.10.9 (0.10.9) 45d69357c9eb068dd8e624f5b0fe461cd2078d88, OS X 10.11.3

**Comment by bpasero** [comment]
We currently do not support to exclude folders from our watching infrastructure so files.exclude does not have an impact. One reason is that e.g. we want to hide the .git folder from the explorer but we cannot disable file events for that folder because git relies on these events.

We might need to add a new option to configure watcher exclusions.

**Comment by bpasero** [comment]
For March we support a new setting files.watcherExclude that can be defined to control this behaviour.
