### ISSUE TITLE
Relative links differ from GitHub links for headers with not latin chars

### ISSUE THREAD

**Issue by KvanTTT** [Microsoft/vscode#37079]
- VSCode Version: 1.17.2
- OS Version: Windows 7 x64

The following links work fine in GitHub (also in GitLab) but not in Visual Code:

```Markdown
* [header-2](#header-2)
    * [header-3](#header-3)
* [заголовок-2](#Заголовок-2)
    * [заголовок-3](#Заголовок-3)
    * [заголовок-header-3](#Заголовок-header-3)
* [missing-отсутствует](#missing-отсутствует)
* [Заголовок](#Заголовок)

## Header 2
### Header 3
## Заголовок 2
### Заголовок 3
### Заголовок Header 3
## Заголовок
```

But the following links work fine in Visual Code but not in GitHub:

```Markdown
* [header-2](#header-2)
    * [header-3](#header-3)
* [заголовок-2](#заголовок-2)
    * [заголовок-3](#заголовок-3)
    * [заголовок-header-3](#заголовок-header-3)
* [missing-отсутствует](#missing-отсутствует)

## Header 2
### Header 3
## Заголовок 2
### Заголовок 3
### Заголовок Header 3
```

Take attention on the upper char case in the first code fragment: "Заголовок-2".

What behavior is correct? Maybe it's reasonable to add an option `markdown.type` that can values `VSCode`, `GitHub`, etc.

Reproduces without extensions: Yes

This is one the reasons why I created [MarkConv](https://github.com/KvanTTT/MarkConv), a utility for converting markdowns of different kinds (GitHub, Visual Code, Habrahabr and other).

**Comment by mjbvz** [comment]
Seems to be handled correctly in the editor but not in the preview. Here's the generated link:

```
<a href="#%D0%97%D0%B0%D0%B3%D0%BE%D0%BB%D0%BE%D0%B2%D0%BE%D0%BA-2">заголовок-2</a>
```

and here's the h2:

```
<h2 data-line="9" class="code-line" id="%D0%B7%D0%B0%D0%B3%D0%BE%D0%BB%D0%BE%D0%B2%D0%BE%D0%BA-2">Заголовок 2</h2>
```

This is possibly an issue with the markdown named headers plugin we use the generate these ids on headers

**Comment by KvanTTT** [comment]
How can I address to this markdown plugin?

**Comment by roblourens** [comment]
Seems to work for all except that `* [заголовок-header-3](#Заголовок-header-3)` goes to `### Header 3`?

**Comment by neilsustc** [comment]
The difference between VSCode and GitHub is on the `slugify` function (which is used to generate link anchor).
VSCode does `toLowerCase()` but GitHub doesn't.
For `## Заголовок 2`, it becomes
`<a href="..." id="#заголовок-2">` in VSCode, but
`<a href="..." id="#Заголовок-2"` in GitHub.

This is reported in extension [markdown-all-in-one#136](https://github.com/neilsustc/vscode-markdown/pull/136) because it generates TOC automatically.

**Comment by mjbvz** [comment]
That's no `3`... it has a code point of 1047.

Github seems to encode non-ascii characters. We strip them after performing a basic mapping (see #44779). I'll just add a basic mapping for this character too. Am hesitant to try matching github exactly since we added the mapping to fix other issues people were reporting

**Comment by kishkin** [comment]
Letter `З` in Russian is not a number `3`. Is it correct to replace a letter with a number? And only one of 33 (thirty three) letters of Russian alphabet is added to `specialChars`.

**Comment by jrieken** [comment]
@mjbvz Not sure what the expect behaviour should be but somehow clicking the link makes the whole bullet-list-section disappear. 

![apr-27-2018 12-25-26](https://user-images.githubusercontent.com/1794099/39358385-2b8fde44-4a16-11e8-844f-85cdf070f26e.gif)

**Comment by jrieken** [comment]
I

**Comment by KvanTTT** [comment]
Unfortunately still does not work if header consists of only not latin chars. I updated sample (`Заголовок`).

**Comment by jrieken** [comment]
@KvanTTT Thanks

**Comment by KvanTTT** [comment]
I used the latests stable version 1.22.2.

**Comment by neilsustc** [comment]
It is even worse in the insider build.

As commented in the [commit](https://github.com/Microsoft/vscode/commit/5a0e115453db439ff8a0fb8d55b1c79c64b1243a#diff-c37cdda79d3e222a11731744c68f5829R19),

![image](https://user-images.githubusercontent.com/7588612/39359700-adb29100-4a4d-11e8-8c77-ff1d5fc3038b.png)

all Chinese and Russian chars which are not in the `specialChars` will be removed from the slug.

---

And the root cause is mentioned in my previous comment, the `toLowerCase()` function.
GitHub only downcase ASCII chars instead of all chars (source code [here](https://github.com/jch/html-pipeline/blob/master/lib/html/pipeline/toc_filter.rb#L39), in ruby)

**Comment by jrieken** [comment]
@KvanTTT Ok, that explains it. Please use latest insiders 1.23 which you can download here: https://code.visualstudio.com/insiders/

**Comment by mjbvz** [comment]
Yeah markdown slugification is total pain because no one agrees with it should do. Lots of sites strip out non ascii characters. Github does their own thing. So does VSTS.

I'll look into adding an option that lets people choose what style slugs are generated

**Comment by KvanTTT** [comment]
@jrieken, it seems to me that it's working for now on the insider build. Thanks :)

**Comment by neilsustc** [comment]
@mjbvz Thanks.

I agree that it is hard to be compatible with all the sites. But at least current solution is unfriendly to Chinese users. Please take this test snippet into consideration after you make some change,

```markdown
<!-- generated according to current VSCode slugify function -->
- [ASCII](#ascii)
- [中文](#)
- [Ляляля](#)
- [Работа с переменными](#)

<!-- generated with GitHub compatibility -->
- [ASCII](#ascii)
- [中文](#中文)
- [Ляляля](#Ляляля)
- [Работа с переменными](#Работа-с-переменными)

# ASCII
# 中文
# Ляляля
# Работа с переменными
```

Although GitHub seems not do `URI.encode()`, but this won't cause trouble in usage, unlike upper/lowercase.

**Comment by kishkin** [comment]
Maybe simple solution from #48482 could be used - [solution](https://github.com/Microsoft/vscode/issues/48482#issuecomment-383852883)?
