### ISSUE TITLE
Tasks -> Configure Default Build Task does not preserve comments

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#37138]
I had some comments in my tasks.json. 
After running Tasks>Configure Default Build Task these comments were removed.

**Comment by dbaeumer** [comment]
This is know and a problem of the settings writer that doesn't preserve all comments. The dup is here: https://github.com/Microsoft/vscode/issues/29453

At that time I shortly investigated in using Martin's JSON parser and doing my own setting writings but then dropped it since it is a more general problem in our settings story. 

I will close as a dup. Please ping if you feel strongly about having this fixed in Task land.
