### ISSUE TITLE
Test: Cloud Shell

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#37180]
For https://github.com/Microsoft/vscode-azure-account.

- [x] Linux @auchenberg 
- [x] Windows @dbaeumer
- [x] Mac @isidorn 

Complexity: 1

- Checkout https://github.com/Microsoft/vscode-azure-account (requires 1.18 API, hence not published yet).
- Run extension from source.
- Give "Open Cloud Shell" a try.

**Comment by isidorn** [comment]
Note: when checking the vscode-azure-account make sure to chekcout the branch `chrmarti/cloudconsole` since master has no changes related to this testplan item.

**Comment by isidorn** [comment]
Authentication dance worked fine, had trouble setting up cloud shell on azure which is captured in #37214
I see a cloud shell tutorial here https://azure.microsoft.com/en-us/features/cloud-shell/ however when I login with my ms account to our portal I can not create a new cloud shell since I am not offered a cloud shell when creating a new resource. What am I missing here?

**Comment by chrmarti** [comment]
Apologies for not mentioning the branch.

The Portal has the Cloud Shell button at the top of every page:
![image](https://user-images.githubusercontent.com/9205389/32231161-1e2304b0-be12-11e7-9852-0fb909b754aa.png)

**Comment by isidorn** [comment]
@chrmarti thanks, that was not easy to find since the portal has 100+ buttons.

**Comment by chrmarti** [comment]
@isidorn My bad, I checked with the Cloud Shell team and there is currently no deep link to the Cloud Shell in the Portal.

**Comment by dbaeumer** [comment]
I couldn't get this to work under Windows :-(
