### ISSUE TITLE
Can you support arguments instead of args in launch.json?

### ISSUE THREAD

**Issue by xbcnn** [Microsoft/vscode#37200]
- VSCode Version: 1.17.2
- OS Version: win10

Steps to Reproduce:

1.  Config launch.json for Windows C++ project.
2.  Config "args".  
If there are multiple args, then we have tolist them one by one with quotation and comma seperated. For example: 
        "program": "${workspaceRoot}\\a.exe",
        "args": [ "a", "b=1", "c=2" ]

3.  I hope to do it in this way:
        "program": "${workspaceRoot}\\a.exe",
        "arguments": [ "a b=1 c=2" ]

     Which works like vs2015.

Reproduces without extensions: Yes

**Comment by weinand** [comment]
The builtin debugger extension (node-debug) uses an argument array because that makes it possible for VS Code to create the correct command line for different platforms (macOS, linux, Windows) and shells (e.g. PowerShell, bash, etc.). 

Using a single 'arguments' attribute puts the burden on the user: she has now to use the proper quoting and escaping syntax (and duplicate this for different platforms).

We have no plans to change this for the builtin debugger extension. However, the attributes available  in a launch config are defined by the debug extension. So you might want to file this feature request against the C++ debug extension.
