### ISSUE TITLE
"search.useIgnoreFiles" should be true by default

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#37211]
Refs: #37179

Currently the useIgnoreFilesByDeafult is `false` by default. IMHO it should be true, since by default we are already not seraching inside node_modules and bower_components, so by default we try to not search in too much. I belive by having the default value true this would align better with the other search settings.

fyi @bpasero

**Comment by bpasero** [comment]
@isidorn is this setting for quick open only or search in general? and is this setting for .gitignore or search.exclude?

**Comment by isidorn** [comment]
@bpasero it should use .gitignore however the rest is not very clear to me as well. Since in https://github.com/Microsoft/vscode/issues/37179 it is specified that this is for quick open, however I can not get it to work for quick open as captured here https://github.com/Microsoft/vscode/issues/37215
Maybe @chrmarti could clarify

**Comment by bpasero** [comment]
@chrmarti @isidorn looking at the code it seems to be used in both text search and file search. The settings description should probably be updated though:

> Controls whether to use .gitignore and .ignore files by default when searching in a new workspace.

I think we have to be careful to enable this by default because extensions might not expect us to ignore more things when calling the `findFiles` API. 

For performance reasons I would give my +1 for enabling this by default but we might need to expose more API for extensions to control this.

**Comment by isidorn** [comment]
@bpasero thanks. I have created additional items for the desciription to be improved. You can find all the issues I created linked in the test plan items fyi https://github.com/Microsoft/vscode/issues/37179

**Comment by chrmarti** [comment]
I'd like to enable the new resource level setting `"search.useIgnoreFiles"` by default. This is currently only used by QuickOpen, but will likely be used by text search in the future too. I think we should not change `findFiles` to use the setting for now.
