### ISSUE TITLE
Mac OS X :: 0.10.9 :: AzureRM Extension :: API Version doesn't accept [variables()] function

### ISSUE THREAD

**Issue by pcgeek86** [Microsoft/vscode#3722]
FYI, we have a validation error with the `apiVersion` JSON property in Azure Resource Manager (ARM) templates. Of course, this won't block deployment, but it is a hassle during authoring of an ARM JSON Template. :smile: Please route to the appropriate resource (eg. B. Moore).

<img width="616" alt="screen shot 2016-03-04 at 7 27 43 am" src="https://cloud.githubusercontent.com/assets/466713/13529777/14b969ce-e1db-11e5-9746-77f4979bc2fe.png">

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by bmoore-msft** [comment]
Thanks Trevor - this is a function of how the schemas are built, the intellisense is based on "type" and "apiVersion" because the schemas differ by apiVersion.  So when apiVersion is an expression the JSON editor can't resolve it to a "real" apiVersion.  So we're trying to see how we can poke into the schema based intellisense and try to evaluate a *simple* expression (we wouldn't try to evaluate all expressions).

**Comment by aeschli** [comment]
@bmoore-msft Brian, will you take care of the issue, or where should @pcgeek86 file the issue?

**Comment by bmoore-msft** [comment]
We're tracking this issue internally in task #196530 you can close it out or assign it to me (we don't have an external repo for the extension at this time).
