### ISSUE TITLE
Dangling comma in hover message?

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#37235]
![image](https://user-images.githubusercontent.com/900690/32219560-d9df2a14-be2e-11e7-906d-6b099048bb8e.png)

**Comment by isidorn** [comment]
Nah. The issue here is that those are 2 unrelated hover messages. The first one is added byt the decorationProvider and the other is the default hover message for the explorer.

We can only fix this is we say that the decorations provider tooltip always overwrites the default tooltip. Which might be ugly. Assigning also to @jrieken to decide if we want to do this

**Comment by jrieken** [comment]
replacing isn't an option as we sometimes also merge multiple decoration messages, like "1 problem in this file, Modified". Maybe a better separator than the comma

**Comment by isidorn** [comment]
I think the comma is not bad and IMHO we can swallow this bug

**Comment by bpasero** [comment]
@isidorn @jrieken oh I see, yes as a user it was not clear to me that these are actually 2 different tooltips on the same item. We are also not separating multiple hovers in the editor by "," so I would suggest to at least separate them with a stronger separator, like a newline.

**Comment by isidorn** [comment]
Newline would work for me.

**Comment by jrieken** [comment]
I'll try out some things, not yet sold on the newline because I am afraid it will look very un-aligned. More tending towards things like dash or pipe

**Comment by jrieken** [comment]
Different options: fat dot, slim dot, pipe, newline, dash. I am not a fan of the newline because the tooltip also wraps itself. That makes many newlines, my favs are the comma (as today maybe with the filename first) and the slim dot

![nov-01-2017 09-22-19](https://user-images.githubusercontent.com/1794099/32266131-7e0fbd8a-bee6-11e7-8323-edd78812ac85.gif)
![nov-01-2017 09-22-24](https://user-images.githubusercontent.com/1794099/32266132-7e282f96-bee6-11e7-9099-72f0d2724789.gif)
![nov-01-2017 09-22-28](https://user-images.githubusercontent.com/1794099/32266133-7e40314a-bee6-11e7-8bec-328a6fb69748.gif)
![nov-01-2017 09-22-32](https://user-images.githubusercontent.com/1794099/32266134-7eab1e2e-bee6-11e7-9396-b550200c5ede.gif)
![nov-01-2017 09-23-38](https://user-images.githubusercontent.com/1794099/32266135-7ec38784-bee6-11e7-9c44-da52cdf6124e.gif)

**Comment by isidorn** [comment]
+1 for small dot

**Comment by bpasero** [comment]
Yeah lets try the small dot.
