### ISSUE TITLE
Settings: searching a setting should reveal it also on the right hand side

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#37254]
Steps to Reproduce:

1. have enough settings that you can scroll some out of view
2. search for settings

=> only the left hand side reveals the settings

Wouldn't it make sense to also reveal the setting on the right hand side if found?

**Comment by sandy081** [comment]
They get revealed when you try to navigate by pressing <kbd>Enter</kbd>. 

Agreed to reveal the first match immediately.

**Comment by fabiospampinato** [comment]
@sandy081 I had no idea one could do that, thanks!

I've usually been triggering `Find Next` only to get the search bar to show up. Perhaps it should show up also on `Find` -- if one wants to find something on the left side there's already the other ginormous search bar available.

**Comment by sandy081** [comment]
@fabiospampinato Not sure if I understand. May I know which `Find Next` action you are talking about?

**Comment by fabiospampinato** [comment]
@sandy081 I'm talking about the `Find Next` action available in the command palette, which triggers `editor.action.nextMatchFindAction`, which makes the search bar show up:

<img width="635" alt="screen shot 2017-11-01 at 15 19 54" src="https://user-images.githubusercontent.com/1812093/32279160-326c76c0-bf18-11e7-8dcb-ae7a15d032f2.png">

**Comment by sandy081** [comment]
@fabiospampinato command+f focuses Search bar from left / right hand side editors.

**Comment by fabiospampinato** [comment]
@sandy081 yes, but I'm talking about the search bar for the right side:

<img width="527" alt="screen shot 2017-11-01 at 17 10 43" src="https://user-images.githubusercontent.com/1812093/32284610-0ecdf4e0-bf28-11e7-842b-cd988ee17a4e.png">

As I mentioned I didn't know that `Enter` could be used to navigate results.

**Comment by sandy081** [comment]
@fabiospampinato I am Confused 😕 . Lets get terminology in sync. I call the big Search bar as `Search bar` and the small one in the right hand editor `Find widget`.

- From Left hand side editor or right hand side editor, if you type cmd+f, the big Search bar gets focussed. 

If you want to override the above behaviour and open `Find widget` when you type cmd+f in the right hand side editor, you can do following

Open Keybindings.json from Keybindings editor and add following entries
```json
 {
    "key": "cmd+f",
    "command": "-settings.action.search",
    "when": "inSettingsEditor"
  },
  {
    "key": "alt+cmd+f",
    "command": "settings.action.search",
    "when": "inSettingsEditor"
  }

```

**Comment by fabiospampinato** [comment]
@sandy081 Alright. What I'm saying is that before knowing that I could use `Enter` in the `Search bar` for searching on the right side,  I used to trigger `Find Next` while the right side was in focus, in order to get the `Find widget` to show up, so that I could perform a search on the right side.

Basically this:

![previous](https://user-images.githubusercontent.com/1812093/32286119-bd93dcde-bf2c-11e7-9515-a61bd2d9d354.gif)

Instead of this:

![now](https://user-images.githubusercontent.com/1812093/32286125-c22ff980-bf2c-11e7-8967-e7449da6987a.gif)

Thanks for the suggestion but that would make `cmd+f` inconsistent, because if triggered from the right side you get a `Find widget` but if triggered from the left side it does nothing, and I don't like that.

**Comment by sandy081** [comment]
Ok. Good that you can use the Search Bar for both editors.

**Comment by fabiospampinato** [comment]
Actually it turns out I can't. If I search for `tab.activeBorder`, which is one of the settable colors, the whole `workbench.colorCustomizations` block gets highlighted instead, so I still have to search in it manually or fallback to the "Find Next" trick I mentioned.
