### ISSUE TITLE
Multiple level folding/unfolding does not work

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#37278]
While testing #37173.

VSCode Version: Code - Insiders 1.18.0-insider (81cca6cc606eeca3443998025bff3893fcfe3ad5, 2017-10-31T05:47:36.947Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vim|vsc|0.10.2

---

Steps to Reproduce:

1. Open a `js` file with the following contents:
```js
function createUpdateRankingHandler(projectid, ranking) {

    return function(req, res, taskCollectionid, task, oldTaskCollectionid, oldTask) {

        if (Tasks.isForward(oldTask)) {
            // update ranking with new task url
            ranking[Mongo.getId(task)] = ranking[Mongo.getId(oldTask)];
            delete ranking[Mongo.getId(oldTask)];
        }

        var jsonTask = TaskManager.builder.json(req, taskCollectionid, task, Protect.isPublicRequest(req), Timestamped.json(task));
        doUpdateRanking(req, res, projectid, ranking, jsonTask);
    };
}
```
2.  Manually, fold the `if` block, the `return` statement, as well as the function body.
3.  Put the caret at the function name
4.  <kbd>3</kbd>+<kbd>z</kbd>+<kbd>o</kbd>
-> only one level is expanded.

In stable, using the same version of the VIM extensions, all three levels are unfolded.

Reproduces without extensions: No

**Comment by aeschli** [comment]
The problem is in the VIM extension. They set the wrong 'direction' attribute to the `editor.unfold` command. Direction wasn't supported for unfold before. I added it for consistency reasons.
I created a PR for VIM. If they don't respond quick enough i can also ignore the direction attribute again and only support the 'down' direction:

https://github.com/VSCodeVim/Vim/issues/2103
