### ISSUE TITLE
Error doesn't disappear automatically after using quick action to install typings

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#37288]
- OS Windows
- ts file
```ts
import * as _ from 'lodash';
```
- execute action to install typings
- observe: the error doesn't disappear. You need to change the file / import

**Comment by mjbvz** [comment]
Should be fixed upstream: https://github.com/Microsoft/TypeScript/issues/19597

**Comment by roblourens** [comment]
It's not installing the types at all when I run the action "Install @types/lodash" under the lightbulb. What am I doing wrong?

**Comment by roblourens** [comment]
Ping @mjbvz

**Comment by mjbvz** [comment]
Yes, this is broken

**Comment by roblourens** [comment]
I see the same thing now, and should have that commit?

**Comment by mjbvz** [comment]
Ok, not sure why this worked when I tested it yesterday. Issue is that TS returns this fix as a refactoring instead of a quick fix. Since 1.19 only request refactorings when you have a selection. We also don't apply the commands returned from refactorings. This needs the same change as  bc206bb.

Pushing to December because you pretty much can't even trigger the quick fix at the moment due to the first issue

//CC @RMacfarlane
