### ISSUE TITLE
Problems decoration settings is poorly named

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#37299]
Testing https://github.com/Microsoft/vscode/issues/37159

Currently there is:

- `explorer.decorations.colors`
- `explorer.decorations.badges`
- `problems.decorations.enabled`

The last one is oddly named, since it applies to the explorer as well.

**Comment by jrieken** [comment]
Yeah, what's missing is the equivalent setting in the git land. Generally there is two concepts: (1) configure the providers such as git and problems  and (2) configure the consumers such as the explorer. The first two settings are consumer-settings and the only once because we current don't show decorations anywhere else. The latter, which we didn't announce btw, is a provider setting. We might need `git.decoration.enabled` for completeness and to make this more well-rounded...

**Comment by jrieken** [comment]
*Verify* that there is a setting `git.decorations.enabled` that controls if git feeds file decorations into the system or not.
