### ISSUE TITLE
Multiple panel title are shown as current

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#37328]
Testing #36571

1. Open the panel, choose to show it to the right
2. Close the panel using the "x" button
2. Ctrl+` to open terminal
3. Ctrl+` to close terminal
4. Open debug console via the command pallet or the buttin in the debug viewlet

![image](https://user-images.githubusercontent.com/16890566/32242453-1235572a-be30-11e7-991c-66e0ba4a838a.png)

**Comment by isidorn** [comment]
I can not reproduce this.
Do you see this all the time?
Can you get the same behavior with the activity bar on the right?
Can you get the same behavior with the current stable?

Thanks

**Comment by ramya-rao-a** [comment]
Yes, I can repro consistently in the latest Insiders as well as when building from source from master.
This occurs only when the panel is shown to the right, not when it is at the bottom
No, it doesn't repro in stable

**Comment by isidorn** [comment]
@ramya-rao-a there have been quite some fixes in this are in the endgame. Can you please try to repro again with latest insiders? Since I can not, If you can repro can you please open developer tools and inspect the title area elements:
* Do both the terminal and the debug console action item have `checked` class? 
* If yes, please put a breakpoint [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/parts/compositebar/compositeBarActions.ts#L72) and see who is callling the checked twice? Since only one action should be checked at one time.

Thanks a lot!

**Comment by ramya-rao-a** [comment]
It doesnt repro in the latest Insiders

**Comment by isidorn** [comment]
@ramya-rao-a thanks for trying
