### ISSUE TITLE
Increase/Decrease View Commands: 1 Editor Logic Bug (H\V Panel orientation)

### ISSUE THREAD

**Issue by cleidigh** [Microsoft/vscode#37347]
Code / Insiders
All OS

Part resize logic with one editor and panel.  Editor with focus, just panel does not resize.
@bpasero 
@isidorn 
To be clear and honest, this is my logic bug that actually is independent and pre-existing from
the vertical panel addition.  My issue not @isidorn ;-)  The bug is more obvious with vertical panel.

Steps to Reproduce:

1. Open code with one editor, panel open , sidebar hidden
2. Focus editor, try Increase/Decrease commands - editor does not resize
3. Focus panel, try resize - panel resizes correctly

Testing : #36906 
@Tyriar 
@octref 
I know you guys are testing and working on panel issues.  While not a panel issued directly
this bug is more noticeable with vertical panel so your guys call on PR integration...

Fixed with PR #37348

**Comment by isidorn** [comment]
@cleidigh thanks for pointing this out and thanks for providing a PR. However since this behavior is already there in stable and since there are a lot of moving parts currently in the panel area I will postpone this to November. When we can discuss on how to best fix this and then I can also review you PR. Hope that makes sense. Thanks

**Comment by cleidigh** [comment]
@isidorn 
Yup.
I will try to get the fix for command support with split windows for the same time.
