### ISSUE TITLE
NaN not colorized as number in debug console

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#37364]
Testing #35324

**Repo**
1. In a js debug session, type `NaN` in the debug console

**Bug**
NaN is not colorized as a number:

![screen shot 2017-10-31 at 4 43 46 pm](https://user-images.githubusercontent.com/12821956/32253890-b0529e0c-be5a-11e7-9a54-8d98cee56da2.png)

**Comment by roblourens** [comment]
What the heck, the node2 version packaged in the vscode build is not the right version.

**Comment by roblourens** [comment]
@joaomoreno or @sandy081, this is because Matt and I have the previous version of node2 in `~/.vscode-insiders/extensions`. It shouldn't be there since this is a built-in extension. Do you have any idea whether vscode could have copied it there for some reason?

Another symptom is that when I look for it in the extensions viewlet, it shows a "Reload" button.

**Comment by roblourens** [comment]
I can install it to that folder with `ext install`. I don't know if there's a legit use case but if someone types in the extension id, they probably know what they're doing.

**Comment by sandy081** [comment]
@roblourens I do not think VS Code would have copied it. May I know if you would have installed by mistake? 

I am not sure if `ext install` should support it or not. IMO it should not.

@joaomoreno what's your opinion?

**Comment by roblourens** [comment]
It was a version that was only there for a short period a couple weeks ago, and I don't remember installing it manually.

**Comment by roblourens** [comment]
I probably put it there for some reason.
