### ISSUE TITLE
Panel and viewlet on right should have a border between them

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#37373]
- VSCode Version: Code - Insiders 1.18.0-insider (8dfa696a1eb6ff67eb68925ddaa9e83d3c56b791, 2017-10-31T16:36:35.429Z)
- OS Version: Linux x64 4.10.0-26-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.11.1
lorem-ipsum|Tyr|1.0.0
shell-launcher|Tyr|0.1.4
vscode-terminal-here|Tyr|0.0.5
vscode-svgviewer|css|1.4.3
tslint|eg2|1.0.14
git-project-manager|fel|1.4.0
md-navigate|jri|0.0.1
vscode-rust|kal|0.4.2
vscode-scss|mrm|0.6.2
cpptools|ms-|0.14.0
seti-icons|qin|0.1.3

(3 theme extensions excluded)

---

#36906

Some themes separate the color of the workbench from the editor, if the panel and viewlet are the same color then it's hard to tell where the split is:

![image](https://user-images.githubusercontent.com/2193314/32259016-fbc9ea32-be7a-11e7-9f7b-8777d603d013.png)

**Comment by isidorn** [comment]
@bpasero agree this is theme dependent. Let's wait for users to complain before I introduce a new color and then we can allow themes to customize this.

**Comment by isidorn** [comment]
After looking deeper into this, we already have a color which does just this nicely
`"sideBar.border"`

This issue in general is panel independent since the sidebar can have the same color as the editor and then the border is needed, which gets tackled by the above mentioned color.

Closing since this works nicely imho
