### ISSUE TITLE
Provide ${workspaceRootForwardSlashes} to aid in cross platform use of file paths

### ISSUE THREAD

**Issue by benjamind** [Microsoft/vscode#37438]
Some plugins need to pass linux compatible paths to other tools no matter what platform they are on.

A good example of this is the `vscode-cpptools` plugin which in some cases wants to pass the workspace root path to gdb and other linux tools even when running on a windows platform.

As evidenced by this ticket https://github.com/Microsoft/vscode-cpptools/issues/908 there are cases where the backslashes in the variable substitution for `${workspaceRoot}` causes the paths to become a mangled mix of windows and linux path separators.

Suggest: Add a variable `${workspaceRootForwardSlashes}` which always delivers the value of `${workspaceRoot}` only with forward slashes regardless of platform.

**Comment by weinand** [comment]
I suggest to use platform specific paths in the following way:
https://code.visualstudio.com/docs/editor/debugging#_operating-system-specific-properties

**Comment by benjamind** [comment]
This doesn't work inside of the launch.json setupCommands fields. The issue here is not one of being able to pass different paths for different platforms is a need to pass Linux paths in a Windows environment inside a launch.json.

Please reopen this ticket and check the linked issue.

**Comment by weinand** [comment]
Since there are many path variables besides 'workspaceRoot', we would have to provide 'XxxxForwardSlashes' (and probably even 'XxxxBackwardSlashes') variants to cover all possible cases. This doesn't scale well and it doesn't feel right to me.
I think the problem at hand is very tool-specific and should be addressed by the (debug) extensions that support that tool set.

**Comment by benjamind** [comment]
@pieandcakes perhaps you can chime in here.

I think the issue at hand is that the setupCommands field needs Linux paths and on Windows vscode is expanding the variable and producing a bad path with mixtures of escaping.

The cpp plugin either has to fix the bad paths (icky), ask users not to use the vscode substitutions and then implement it's own (urgh) or the target gdb tool needs to know of this idiosyncratic behavior on the part of the ide and handle windows paths in a Linux tool.

None of these seem like good options.

**Comment by weinand** [comment]
The only tool that know that `setupCommands` needs linux-paths even on windows is the tool that introduces the `setupCommands` attribute. So it could convert the slashes if it sees backslashes (and would not bother the user with this idiosyncratic behavior).

If VS Code would provide a `${workspaceRootForwardSlashes}`, the burden to know when to use it would be on the user. This would be a hassle and is error prone.

**Comment by benjamind** [comment]
Yeah that's also a fair point.

I think the issue for the cpp plugin side is that it doesn't know that double backslashes in paths are not escaped backslashes in Linux paths vs mixed path separators in Linux paths on windows.

**Comment by benjamind** [comment]
Although further thinking about this in this specific case the user is well aware of the issue because they are specifically targeting a Linux tool with their launch.json so having to be aware of the path separator issue is reasonable.

It is also not like this is some third-party plugin that nobody uses. This is vscodes own cpp plugin, the docs from this are even part of the main vscode docs.

Can we at least get some cooperation between the teams started to sort this out? It makes it impossible to use the in app debugger for microcontrollers without specifying absolute paths in the launch.json.

**Comment by weinand** [comment]
@pieandcakes what's your take on my proposal from above?

**Comment by pieandcakes** [comment]
@weinand I think just replacing all slashes can introduce other issues such as if the user means to pass the other slash, the user would not be able to get around it if we always replace slashes. Also, this would not solve remote debugging from Windows -> Linux because we would still assume a Windows machine based on where the launch.json is launching from. 

My original comment in @benjamind's original request on our issues page was for us to think about adding a parameter to `setupCommands` in each object that allows the user to specify whether to replace the slashes or not. Barring that, it would be up to the user to replace the slashes.
