### ISSUE TITLE
When starting VSCode & adding a folder from the CLI, VSCode ignores the folders in the restored workspace

### ISSUE THREAD

**Issue by ggilmore** [Microsoft/vscode#37449]
- VSCode Version: Code - Insiders 1.18.0-insider (2ab10d50163f008ada9a4aa215de8c884857ce99, 2017-11-01T06:11:48.112Z)
- OS Version: Darwin x64 17.0.0
- Extensions: none
---

Steps to Reproduce:

1. Have one window open with a workspace containing a folder named`dir`
2. Hot exit the application (using `Cmd+Q` or your platform equivalent)
3. Run `code-insiders dir` to open VSCode again 

I expect to only see one window open that has the old workspace containing `dir` already, but instead I see two windows: 

- A new window containing just the `dir` folder
- The old window with the workspace that contains `dir` and whatever else 

This happens regardless of whether or not the `-add` flag is used.

VSCode should make sure that it isn't opening extraneous windows by checking to see if the folder is already contained in one of the restored workspaces.

**Comment by bpasero** [comment]
We might need a setting for this, but the current behaviour is "as designed". Let's see if more people ask for a different behaviour.

**Comment by parkovski** [comment]
I'm having a related issue, and I'm not really sure what the solution should be. I'm using VSCode with Unity, and when you double click an error the plugin opens the file by calling `code <project dir> -g <file>:<line> -r`, which used to not be a problem because I had the project window open already. Now though, it's part of a workspace with a separate server project, and that command closes the workspace and re-opens the window with just the Unity project.

I think there should at least be a command line option to use the current workspace if the file or project you're opening is part of it. I can't really think of a time when I would _want_ my workspace closed and part of it re-opened though. Also not sure if the behavior should be the same if the workspace is closed but most recent as in the original issue, or if I should open a new issue about replacing an open workspace, or if the plugin should be using a different command line.
