### ISSUE TITLE
Regression: Search viewlet doesn't get selected text when not visible

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#37454]
- VSCode Version: Code - Insiders 1.18.0-insider (2ab10d50163f008ada9a4aa215de8c884857ce99, 2017-11-01T05:19:21.302Z)
- OS Version: Windows_NT x64 10.0.17025
---

This is a regression from the behavior in 1.17.2. Also somewhat similar to this https://github.com/Microsoft/vscode/issues/25293

Steps to Reproduce:

1. Open a file and make sure to have a viewlet other than search visible
2. Select some text and press `ctrl+shift+f` to find in files
3. 🐛 Search viewlet will activate, but the selected text won't appear in the search box

Although if the search viewlet is already active, it will work fine

Reproduces without extensions: Yes

**Comment by roblourens** [comment]
This is from https://github.com/Microsoft/vscode/issues/31496, good catch.

**Comment by roblourens** [comment]
Fixed by https://github.com/Microsoft/vscode/commit/ff6c4849cf1b1766a56656e295c86bef71bac685 which has the wrong issue number.

@sandy081 this seems crazy, "Find in Files" and "Show Search" are redundant right?

![image](https://user-images.githubusercontent.com/323878/32305734-588511e8-bf34-11e7-9ea1-ddde071ed581.png)

**Comment by sandy081** [comment]
@roblourens yes it seems. When search viewlet is not visible, search input should not have focus.
