### ISSUE TITLE
Virtual Documents and compareFileWith command

### ISSUE THREAD

**Issue by Xiot** [Microsoft/vscode#3745]
I am attempting to modify the Git History extension to use virtual documents instead of temp files, but I am running into issues while executing the `workbench.files.action.compareFileWith` command.

If I open the virtual file first, then run the `compareFileWith` command, I get an error stating `Open a file first to compare it with another file.`, which would result from `workbenchEditorCommon.asFileEditorInput(this.editorService.getActiveEditorInput());` returning falsy.

Attempting the compare in reverse (open disk file, then compare, then open virtual file) I get an exception `Notification handler 'textDocument/publishDiagnostics' failed with message: Illegal argument: line must be positive` that appears to be caused by the fact that `babel-eslint` can't be loaded.

I haven't figured out how to debug the `GlobalCompareResourcesAction` directly yet, but I'll keep on digging. Also, is there a simple way to get a copy of the current call stack, so that I can post it here?

**Comment by jrieken** [comment]
@bpasero Can you provide details on how the `compileFileWith` command works?

**Comment by bpasero** [comment]
@jrieken I don't think the command is fit to be used from extensions because it expects real files on disk to be used and requires user interaction (you invoke it from a file and then quick open opens so that you can pick a file to compare with).

The Git history extension only makes this work because it generates a tmp file on disk with the contents which is ugly because that pollutes the editor history.

+1 for allowing diff on virtual documents (or any document including virtual documents), but I would suggest to introduce a new command for this and let the current one on files just piggy back on the other one.

**Comment by stef-levesque** [comment]
Any update on this? I would be interested to have this feature for [vscode-perforce](https://github.com/stef-levesque/vscode-perforce)

**Comment by jrieken** [comment]
Virtual documents are part of the normal model resolution chain. Assigned to Ben for making the command work with that

**Comment by bpasero** [comment]
:+1:

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/1865
