### ISSUE TITLE
Run Default Build|Test Task

### ISSUE THREAD

**Issue by rickvanprim** [Microsoft/vscode#37473]
Requesting a command for running the default build|test task associated with the current root and keybindings for those commands (if commands don't automatically become available for keybindings).  The idea being, based on whatever document I'm looking at, if I hit <insert keybinding> it will build that project without prompting me to choose a build task.  Same story for running tests.

**Comment by dbaeumer** [comment]
@rickvanprim you can mark a task as a default build task. If there is only one we will execute it without asking. If there are more default build tasks we will prompt. You can also bind a specific task to a keyboard short cut if you want. See https://code.visualstudio.com/docs/editor/tasks#_binding-keyboard-shortcuts-to-tasks on how to do this.

Closing the issue since I think the requested support is available.

**Comment by rickvanprim** [comment]
The above link would let me bind to a specific task, which is close, but not exactly what I'm after.  I want to bind to "the default build task for this root".  Please correct me if I'm wrong, but I'm assuming there's not currently a way to keybind to something like that which would either be a dedicated command, or involve variable expansion in the keybind such as
```
{
    "key": "ctrl+h",
    "command": "workbench.action.tasks.${root.build.default}",
    "args": "Run tests"
}
```

**Comment by dbaeumer** [comment]
It is possible via a workaround by either using unique names or by given the tasks in each root unique `identifiers` and then bind the short cut to that identifier. However sounds cumbersome. Will reopend and track as a feature request.

**Comment by alexr00** [comment]
This is already possible with the `workbench.action.tasks.test` and `workbench.action.tasks.build` commands. Example:

	{
		"key": "ctrl+h",
		"command": "workbench.action.tasks.test",
	}
