### ISSUE TITLE
Trouble with data returned from commands

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#37484]
1. Open Markdown preview
2. Click `Show Source` title action

![image](https://user-images.githubusercontent.com/22350/32318462-a6adf5f0-bfb7-11e7-849b-4e104c61f010.png)

![image](https://user-images.githubusercontent.com/22350/32317267-890fca86-bfb3-11e7-8c98-88e96948e674.png)

**Comment by joaomoreno** [comment]
It seems someone is trying to send an instance of `ExtHostTextEditor` over the wire.

**Comment by jrieken** [comment]
This has been there forever but since yesterday these errors are becoming visible with https://github.com/Microsoft/vscode/commit/93338c61f140b0be84a08372c5fb2d85e3248127 fyi @alexandrudima @joaomoreno Logging those errors was a good change but also slightly risky so late in the endgame. Unsure what else is being uncovered by this...

**Comment by jrieken** [comment]
The actual issue here is this

* we invoke a command ('Show source') which run in the extension host
* when it's done it returns an editor object
* the execute command logic returns/resolves with that editor object
* the editor object ends up in JSON.stringify
* JSON.stringify call toJSON which is interpreted as RPC call

**Comment by joaomoreno** [comment]
Well, the devtools doesn't pop up on errors, so I still think we should keep the change in. Behaviourally, nothing changes.
