### ISSUE TITLE
Improve error notification for unavailable source

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#37517]
The fix for #36757  results in `openBreakpointSource` being a no-op if a debug url is loaded outside of a debug session.

This results in a confusing UI:
if a user has breakpoints in workspace source and some breakpoints in "dynamically loaded" source, selecting a breakpoint sometimes loads the source and sometimes does nothing (which means that the users continues to see the previous source).

We will have to improve this.

**Comment by isidorn** [comment]
After discussing with @weinand this is an issue we are facing all over the workbench, apart from the use case above here are some other: file not available in explorer (ftp), resource can not be displayed for some reason(binary).
We should devise a general strategy on what to do in these cases. Currently for explorer we show an error notification which is very frustrating to the user, and for the binary file we show a "fake" editor with content of the error message. For breakpoints we do a no-op. So for three similar use cases we do 3 completely different solutions.

As @weinand points out this is basically the issue on how to show errors returned from the file system provider. Since debug adapters are also file system providers in a way.

In case we decide to go with the "fake" editor solution there would be some mechanism that a content providr can tell the workbench to drop the cache and ask again, since some resource can become available after some time.

Opinions very welcome @bpasero @jrieken @stevencl @joaomoreno

**Comment by bpasero** [comment]
If a resource exists I would show an editor which can either be file or binary as we do today. I would not show an editor if a resource does not exist because that draws the wrong impression to the user. 

I am +1 for always consistently showing an error message if opening an editor with a resource is not possible because the resource does not exist. We can show an action to create the resource as a solution (which would create and open it) IF the resource uses a scheme that has an associated file system provider.
