### ISSUE TITLE
Emmet & BEM is confusing

### ISSUE THREAD

**Issue by joepagan** [Microsoft/vscode#37520]
Hey,

I am under the impression that when using BEM an element uses `__` & a modifier uses `--` normally.

`.parent>.__child|bem` will return:

        <div class="parent">
          <div class="parent parent--child"></div>
        </div>

I would have expected this to return:

        <div class="parent">
          <div class="parent__child"></div>
        </div>

`.parent>.--child|bem` will return:

    <div class="parent">
      <div class="parent__child"></div>
    </div>

Even though incorrect in BEM world, I would have expected this to return:

    <div class="parent">
      <div class="parent--child"></div>
    </div>

[Looking at the docs for emmet](https://docs.emmet.io/filters/bem/), the functionality I have witnessed appears to be intentional.

I think it is confusing where you have to write the exact opposite of what you want to get your desired results.

I appreciate many existing emmet users would want to keep it this way.

I have see there is also a setting for `"bem.shortElementPrefix":"-"`

Could we maybe have options for `elementPrefix` & `modifierPrefix` to make this less confusing?

- VSCode Version: 1.17.2
- OS Version: macos 10.12.6

**Comment by edDimensi** [comment]
I want this feature too. After release emmet 2.0, i want only cry and cry. I first time i can't use emmet and bem, now i can't use bem.

**Comment by ramya-rao-a** [comment]
@joepagan 

> I am under the impression that when using BEM an element uses __ & a modifier uses -- normally.

You have mixed up the symbols being used in the abbreviation and the ones being used in the expanded abbreviation.

In an abbreviation using bem, the allowed symbols are `_` (modifier), `-` (element) , `--` (element that wants to use the class name of the grand parent instead of parent), `---` (element that wants to use the class name of the great grand parent instead of parent and so on. 

The expanded abbreviation i.e the output has  `_` for when you use the modifier syntax in the abbreviation and `__` for when you use the element syntax. These are customizable using the `bem.elementSeparator` and `bem.modifierSeparator` options inside the `emmet.preferences` setting.

To summarize, the symbols used in the abbreviation are not customizable but the symbols used in the output are customizable. 

Coming to your examples:

1. `.parent>.__child|bem`

`__` is not a valid symbol to be used in the abbreviation. Emmet treats it as `_` and continues the expansion

Modifier syntax means it will use the class from the parent in addition to the modified class i.e parent_child. So you end up with 
```
<div class="parent">
      <div class="parent parent__child"></div>
    </div>
```
2. `.parent>.--child|bem`

`-` is used twice. So an attempt to find the grand parent is made. There is no grand parent, so we fall back to using the parent and you end up with 

```
<div class="parent">
  <div class="parent__child"></div>
</div>
```

If you would have used `.grandparent>.parent>.--child|bem`, then you would have got
```
 <div class="grandparent">
        <div class="parent">
            <div class="grandparent__child"></div>
        </div>
    </div>
```

Hope this helps

**Comment by ramya-rao-a** [comment]
@edDimensi I have addressed the issue raised by @joepagan above.

Please log a separate issue on what exactly bothers you about emmet 2.0
