### ISSUE TITLE
Marketplace image URLs get broken

### ISSUE THREAD

**Issue by felixfbecker** [Microsoft/vscode#37545]
[![Minimum PHP Version](https://img.shields.io/badge/php-%3E%3D%207.0-8892BF.svg)](https://php.net/)

Not sure if this is the right place to file this, but recently I saw that this badge that worked before now has encoding errors in it:

![image](https://user-images.githubusercontent.com/10532611/32343165-dacedeaa-bfbf-11e7-8d0d-1ee7b4e09dbe.png)
https://marketplace.visualstudio.com/items?itemName=felixfbecker.php-intellisense#overview

It looks correct on GitHub:

![image](https://user-images.githubusercontent.com/10532611/32343182-e9ca3d64-bfbf-11e7-9d4d-43f3f1509c6a.png)

Image URLs:
```
https://img.shields.io/badge/php-%3E%3D%207.0-8892BF.svg   // markdown
https://img.shields.io/badge/php-%3E%253D%207.0-8892BF.svg // marketplace

**Comment by mjbvz** [comment]
Seems to work properly in the editor as well:

![screen shot 2017-11-13 at 1 34 45 pm](https://user-images.githubusercontent.com/12821956/32750422-71dc26bc-c877-11e7-8fc4-1ff1bf04e395.png)

@sandy081 Do you know who we should forward marketplace bugs to?

**Comment by sandy081** [comment]
@modigrv Can you please let @felixfbecker know where can he file this market place related issue ?

**Comment by Hardhik** [comment]
@felixfbecker Can you please change the url from existing "https://img.shields.io/badge/php-%3E%253D%207.0-8892BF.svg" to "https://img.shields.io/badge/php-%3E=%207.0-8892BF.svg" and it'll be shown correctly.

This issue is seen because we sanitize given urls and in this case "%3D" is being converted to "%253D". If you can change it in your next extension update, you should be seeing the expected image correctly rendered.
