### ISSUE TITLE
Cannot use `undefined` as a parameter for `vscode.debug.startDebugging` 

### ISSUE THREAD

**Issue by changsi-an** [Microsoft/vscode#37559]
- VSCode Version: 1.17.2
- OS Version: Ubuntu 16.04.3 LTS

Steps to Reproduce:

1. I am trying to call `vscode.debug.startDebugging(undefined, myConfig)`, but I got the following error if I use `undefined` as the first parameter.
![screenshot from 2017-11-02 15-19-39](https://user-images.githubusercontent.com/14335429/32353333-3424f6b6-bfe2-11e7-9c96-ce62f4f8d0dd.png)

and my debugger session is terminated afterwards.
 
Notes:

1. If I call it with 
```
vscode.debug.startDebugging(vscode.workspace.workspaceFolders[0], myConfig) 
```
then everything works as expected, I could see a debug session launched.

2. I have put all the attributes defined in the `"configurationAttributes"` of `package.json` to the `myConfig` object (the 2nd parameter), and I declared none of those attributes as `required` in `package.json`.

3. If I just launch  a debug configuration using my debugger type from `launch.json`, everything works as expected.

4. I tried to debug vscode code, the call to `vscode.debug.startDebugging()` can actually return successfully. And I do not see any exception thrown from the call. The `Cannot read property `uri` of undefined` error seem to be triggered from a later routine.

5. By [vscode.d.ts#L6105](https://github.com/Microsoft/vscode/blob/67ae810e04c7312b4361b79a53dd1ef4aec49ade/src/vs/vscode.d.ts#L6105) , I should be able to use `undefined` as the first parameter.

Reproduces without extensions: Unknown. No opportunity to check, because I am developing a extension.

**Comment by weinand** [comment]
@changsi-an If you pass `undefined` for the folder parameter to vscode.debug.startDebugging, the debug configuration `myConfig` must not contain any variables (like `${workspaceFolder}`) because variables are resolved against the folder parameter (which is undefined in your case).

@isidorn we should fail more gracefully in this case, e.g. by not substituting any variables at all.

**Comment by changsi-an** [comment]
@weinand I don't have any variables in my `myConfig` object. All plain strings.

**Comment by weinand** [comment]
@isidorn most likely passing undefined to startDebugging results in the error from above in https://github.com/Microsoft/vscode/blob/1d632ec12cd4ec0fe4f8badfbb743d5bd2807cda/src/vs/workbench/parts/debug/electron-browser/debugService.ts#L905
because the "root" passed to "doCreateProcess" is "undefined".

**Comment by isidorn** [comment]
@changsi-an good catch, thanks. You can try it out in vscode insiders in 4 days and let us know how ti works.
@weinand thanks for pointing out the issue

**Comment by roblourens** [comment]
`vscode.debug.startDebugging(undefined, 'Launch Program');` => nothing happens

`vscode.debug.startDebugging(vscode.workspace.workspaceFolders[0], 'Launch Program');` => starts debugging

**Comment by roblourens** [comment]
And I get this error in devtools: `Configuration 'Launch Program' is missing in 'launch.json'.`

**Comment by weinand** [comment]
@roblourens
What you are seeing is the expected behaviour.  
if you pass undefined for the workspace folder, then no 'launch.json' and consequently no named launch config can be found. However, in this case it is perfectly fine to pass an launch config object to startDebugging.

I agree, the error message `Configuration 'Launch Program' is missing in 'launch.json'`is misleading because the real problem is that there is no 'launch.json' in the first place.

@isidorn can we make this clearer?

**Comment by isidorn** [comment]
@weinand sure, I have improved the error message to be more precise in hte case the launch.json does not exist.

**Comment by roblourens** [comment]
Oh, I get it.

**Comment by changsi-an** [comment]
Is the bug fix released yet? I am still hitting `"uri" of undefined` error in 1.18.1

**Comment by roblourens** [comment]
No, it's in Insiders or the next stable release.
