### ISSUE TITLE
Layer breaker: references to Electron in /common/

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#37610]
There a few usages of `Electron` in https://github.com/Microsoft/vscode/blob/master/src/vs/platform/windows/common/windows.ts#L138 which is against our layering rules. I'd suggest to move the whole file into an `electron-browser` folder

**Comment by bpasero** [comment]
Unfortunately this might not be so simple given 62 references of which some would also need to be lifted up... An alternative would be to define similar interfaces that contain the properties we actually need instead of depending on Electron.

**Comment by bpasero** [comment]
Also: https://github.com/Microsoft/vscode/blob/master/src/vs/platform/windows/common/windowsIpc.ts#L62 and https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/crashReporter/common/crashReporterService.ts#L37

**Comment by jrieken** [comment]
> An alternative would be to define similar interfaces that contain the properties we actually need instead of depending on Electron.

I'd favour to lift them all instead blowing up our code size

**Comment by bpasero** [comment]
@jrieken with our current code organisation I cannot express the proper way for these references. Here are the issues:

**Moving this service into src/workbench**
This was my first idea, but it doesn't work. There are references from `src/code` (our main side of things) into the windows service because the main side basically implements that service. We should not depend from `src/code` to `src/workbench` other than the `index.html` file that we load into a window. The only way out I see here is to have something like `platform-electron` for services that are shared between `code` and `workbench`. 

**Moving the service from common into electron-browser**
This will not help because we have `electron-main` depending on the windows service and thus we would reach from `electron-main` into `electron-browser`. The only option would be to introduce a new `electron-common` layer that contains the service and that can be accessed by `electron-browser` and `electron-main`. 

To unblock your 2-CU scenario and to use ES6 features in workbench I suggest to [commit my changes](https://github.com/Microsoft/vscode/commit/7ac9835598db8092db2d759e679d1334755f86f3) that will inline the Electron references. However if we ever want to tackle this properly it needs some serious new code-structure layout on disk.

Thoughts?

**Comment by jrieken** [comment]
Yeah, makes sense... It's unfortunate but reality...
