### ISSUE TITLE
Layer breaker in common/files

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#37613]
Try to compile just the monaco-editor-bits with a special tsconfig.json-file, see a compile error in [files.ts](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/files/common/files.ts#L574) because it uses `process`. That's again our layering rules because thing in `common` must be universal, without specific dependencies.

**Comment by jrieken** [comment]
tsconfig.json-content in question

```
{
	"$schema": "http://json.schemastore.org/tsconfig",
	"compilerOptions": {
		"module": "amd",
		"moduleResolution": "classic",
		"noImplicitAny": false,
		"removeComments": false,
		"preserveConstEnums": true,
		"target": "es5",
		"sourceMap": false,
		"experimentalDecorators": true,
		"declaration": true,
		"noImplicitReturns": true,
		"baseUrl": ".",
		"types": []
	},
	"include": [
		"typings/require.d.ts",
		"typings/thenable.d.ts",
		"typings/es6-promise.d.ts",
		"typings/lib.array-ext.d.ts",
		"typings/lib.ie11_safe_es6.d.ts",
		"vs/css.d.ts",
		"vs/monaco.d.ts",
		"vs/nls.d.ts",
		"vs/editor/*",
		"vs/base/common/*",
		"vs/base/browser/*",
		"vs/base/parts/tree/*",
		"vs/base/parts/quickopen/*",
		"vs/platform/*/common/*",
		"vs/platform/*/browser/*"
	],
	"exclude": [
		"node_modules/*"
	]
}

```

**Comment by jrieken** [comment]
Similar, `editor.main.ts` depends on `exports` which is only defined in node.d.ts

**Comment by rebornix** [comment]
Moved the file size check to `node` folder.

`exports` object is available in AMD/CJS/UMD so before we need to compile Monaco to ESM, it's good to be there. I'd like to have another issue tracking it as to make the syntax off `exports` or `node` stuff, we need to 

* use `export` instead of `exports` 
* avoid `import = require()` as well and replace them with asterisk syntax, by merging https://github.com/Microsoft/vscode/commit/cb05178b697cfb43fd1d8e0d1a9bfa50bbffdfb6 .

Closing it now as the bad layering is fixed.

**Comment by jrieken** [comment]
Sorry, I have cramped to issues into one but this still is a problem: https://github.com/Microsoft/vscode/issues/37613#issuecomment-341734368

**Comment by rebornix** [comment]
I see, even though `exports` is available to standard AMD, but since there is no typings for `exports` so we get `error TS2304: Cannot find name 'exports'`. We don't see this kind of error as `tsconfig.json` as we include `node` typings there.

To get rid of the error message, adding `declare var exports: any;` is good enough. @jrieken do you have any particular thing to do with `tsconfig.monaco.json`? If it's just targeting AMD, then it can be an easy one line fix. If we want to target ESM, then we need more tweaks as ESM only supports named exports.

**Comment by jrieken** [comment]
I am good with the `declare var...` solution. The goal of `tsconfig.monaco.json` is to just describe the monaco editor and its dependencies so that at one point we can have two compilation units, one that targets browsers (including IE11) and one that targets electron/node with the freedom of using more modern JS
