### ISSUE TITLE
Option to always show problems inline without pressing F8

### ISSUE THREAD

**Issue by dj-hedgehog** [Microsoft/vscode#37628]
It is already possible to show problems inline when pressing F8 but an option to enable showing them all the time would be great. 

I would also be willing to work on an extension adding this functionality but is that possible right now?

![node js - always show problems inline in vscode - stack overflow 2017-11-03 20-10-11](https://user-images.githubusercontent.com/7140800/32391631-0249e844-c0d3-11e7-8d30-32a813d4f3c2.png)

**Comment by hoovercj** [comment]
Related to #19749

**Comment by grandslammer** [comment]
Any update on this? A dot in between the breakpoint indicator and the line number would be the best place to put it. Red for errors and yellow for warnings. I find it much faster to view issues this way rather than the problems panel.
I'm new to VS Code and have seen this feature in other editors.

**Comment by hoovercj** [comment]
@grandslammer it sounds like you're talking about something else.

Adding a gutter indicator for problems is already possible using the extension api. There are functions to get the ["diagnostics"](https://code.visualstudio.com/docs/extensionAPI/vscode-api#_languages.getDiagnostics) (vscode term for inline problems, warnings, hints, etc.) and there are functions to add ["decorations" to the "gutter"](https://code.visualstudio.com/docs/extensionAPI/vscode-api#DecorationRenderOptions). So an extension could easily add decorations to the gutter for each diagnostic.

However, this issue is about being able to trigger the current "show problem inline" functionality that already exists for a single problem to work for ALL problems in a document at the same time.

I think this issue should be closed as a duplicate of #19749

**Comment by alexandrudima** [comment]
Let's track in #19749 and #3915
