### ISSUE TITLE
Sudden inability to write

### ISSUE THREAD

**Issue by std282** [Microsoft/vscode#37687]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:57:00.652Z)
- OS Version: Linux x64 4.4.0-97-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.2.11
python|don|0.7.0
cpptools|ms-|0.14.0

---

My problem is that VS Code suddenly disabled me from typing, all of a sudden. And also there was a side-effect: VS Code became really hungry with RAM (~2 GiB; when VS Code was OK, it was consuming only ~200 MiB) and thus was starting really slowly.

The problem was solved by removing and reinstalling all extensions.

Steps to Reproduce:

1. Start VS Code and try to type.

Reproduces without extensions: No

**Comment by SE2Dev** [comment]
I had the same issue earlier today (Debian 9, with the same VSCode version, and all of those plugins installed (as well as others)). I wasn't able to type in the editor (I was able to type in textboxes, like the find dialog, etc.) regardless of the workspace I was in, but I was able to delete code with backspace, and I was also able to paste code with the mouse & CTRL+V. I haven't updated any plugins since the last time it worked, with the exception of a single theme which I have disabled.

I tried restarting vscode, my computer, logging out, checking for updates, etc. but nothing seemed to work; But when I launched with --disable-extensions, I was able to type - so I started disabling plugins to figure out what was causing it suddenly - and apparently **it was the vscode-cpptools**.

I tried disabling, and re-enabling the extension but the issue persisted when I reenabled the cpptools. Finally I tried uninstalling, and reinstalling the vscode-cpptools and the issue went away. I'm not really sure what exactly caused the issue, because it showed up even when there were no C/C++ files in the active workspace. It certainly was strange...

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.
