### ISSUE TITLE
Auto-detected npm tasks run in the wrong directory

### ISSUE THREAD

**Issue by vp2177** [Microsoft/vscode#37721]
- VSCode Version: 1.17.2
- OS Version: Win10

Steps to Reproduce:

1. Open a folder with
package.json:
```
{ 
  "name": "foo",
  "scripts": { 
    "test": "echo abc" 
  }
}
```
2. Do Tasks -> Run Task... -> select `npm: test`
3. It fails as it is run in the project folder's parent directory:
`npm ERR! enoent ENOENT: no such file or directory, open  'C:\Users\user1\Workspace\package.json'`

Reproduces without extensions: Yes/No (haven't tried yet)

**Comment by egamma** [comment]
@vp2177 I cannot reproduce this given the steps above, pls see the screenshot below. Can you attach the output you are seeing in the terminal. 

![image](https://user-images.githubusercontent.com/172399/32506464-f3d76290-c3e4-11e7-88d8-9b489c0d1050.png)

**Comment by vp2177** [comment]
![image](https://user-images.githubusercontent.com/451903/32521456-7f865618-c40b-11e7-9266-dcebb66dca87.png)

Actually I was wrong, `npm run test` is not run in the parent folder, but always in `C:\Users\<my-user>\Desktop\Workspace`. It appears PowerShell is used as the terminal (by default?), and in my PowerShell profile, there is a `cd` command into this directory.

**Comment by vp2177** [comment]
If I change the terminal that is used to `cmd`, running tasks works. I guess regardless of terminal, changing to the folder with the `package.json` before running the task would solve this

**Comment by egamma** [comment]
> in my PowerShell profile, there is a  cd  command into this directory.

This explains it, thanks. The extension is doing a `cd folder` in a multi-folder setup, in a single folder setup the assumption is that the shell is spawned in the workspace folder. Since it is no a common setup to do a cd in the PS profile. I can either add a setting or always do a `cd`. What do you think?

**Comment by dbaeumer** [comment]
@egamma I am not a fan of adding a cd into the command line since this makes all your code shell specific. The way to go is to let the system know how to start the shell when the task is run. In the case described this can be done by either specifying the shell per task or globally in the tasks.json. There is a feature request to even allow specifying it in a shell. 

However there is currently a problem with this and contributed tasks. See https://github.com/Microsoft/vscode/issues/36154

To fix this we should address 36154 and then have this in the tasks.json

```ts
    "windows": {
        "options": {
            "shell": {
                "executable": "...\\powershell.exe"
                "args": [
                    "-NoProfile", "-Command"
                ]
            }
        }
    }
```

**Comment by vp2177** [comment]
Sorry perhaps it's already this way, but if not, I think which shell to use for the integrated terminal (user's personal preference) should be independent of which shell is used when spawning tasks (configurable but by default should be `cmd` or PowerShell with `-NoProfile`)

**Comment by dbaeumer** [comment]
See also #36342

**Comment by egamma** [comment]
The proposal from @dbaeumer in https://github.com/Microsoft/vscode/issues/37721#issuecomment-342759115 resonates with me and I suggest to close this issue in favor of  #36154

**Comment by vp2177** [comment]
Yes on a second thought this is a duplicate of #36154
