### ISSUE TITLE
Using `menuBarVisibility` set to `toggle` and alt commands menu contributions.

### ISSUE THREAD

**Issue by Krzysztof-Cieslak** [Microsoft/vscode#37724]
This is a small UX  problem. 

* Setting `menuBarVisibility` to `toggle` means that top menu bar will be shown only after pressing the `Alt` button.
* Extensions can define `Alt` commands for menu contributions to provide alternative commands that get enabled when user press `Alt` button.

Problem: user wants to use `Alt` command but it also additionally causes menuBar to toggle on, which causes the whole screen to jump a bit. And there is no way to override used key for any of those actions (at least as far as I know).

Possible solution:
Make buttons used in both cases configurable with normal keyboard settings.

**Comment by bpasero** [comment]
@Krzysztof-Cieslak wouldn't it make a lot more sense to recommend to these people to set `menuBarVisibility` to `hidden` instead?

Bottom line is that there is no way to configure the Alt key when menu is set to toggling (see also https://github.com/Microsoft/vscode/issues/41070)

**Comment by lyallh** [comment]
The problem is people who set `menuBarVisiblity` to `hidden` want to be able to toggle it open sometimes to use the menubar without having to go in to settings to make it visible. They could also pop it open with e.g. Alt+f to open the file menu but then it seems the menu is stuck open with no way to hide it but to fiddle around in settings again (another electron issue I guess..)

The `toggleMenuBar` action could solve this if it didn't change the user's setting to `toggle` instead of `hidden`. Discussed in #46181

**Comment by bpasero** [comment]
@Krzysztof-Cieslak is this still an issue with our new builds that leverage Electron 2.0.0 ([Windows](https://az764295.vo.msecnd.net/exploration/b1513227ace6929e278c5d531250bc1d0cf89e2f/VSCode-win32-x64-1.22.0-exploration.zip), [Linux](https://az764295.vo.msecnd.net/exploration/51470c58bd748e1689ba3d82811fe3df9efa72d4/code-exploration-1.22.0-1521641787_amd64.tar.gz))?
