### ISSUE TITLE
Multiple VSCode windows opened when opening a workspace or file directly.

### ISSUE THREAD

**Issue by rtlayzell** [Microsoft/vscode#37768]
- **VSCode Version:** 1.17.2
- **OS Version:** Windows 10

There is a feature of vscode that caches unsaved documents after closing the editor.  When the editor is reopened the unsaved file is open within the editor giving the user a chance to save it.

This is a useful feature but its quite jarring when opening an instance of vscode via the _Open with Code_ commands as this forces two windows to be opened at the same time.  This may also occur when starting an instance of vscode via the command line + arguments.

I'd like to suggest only "resurrecting" the window with the unsaved documents/changes when opening code without a workspace or file.

**Comment by Tyriar** [comment]
You can set `"files.hotExit": "onExitAndWindowClose"` which will only restore the windows that do not have a folder/workspace attached. I think this more aligned with what you're after (and what I use 😄).

**Comment by rtlayzell** [comment]
That isn't exactly what I I was looking for, the jist of it was to only open a single window at a time and depending on the context its either a workspace the user has selected or the restored previously unsaved changes. 

Opening multiple windows is irritating, from a user experience point of view IMO. The `"window.restoreWindows"` setting seems to be the closest thing to what I'm looking for but the desired behaviour is not listed sadly.

**Comment by Tyriar** [comment]
@rtlayzell I get what you're after, and I think you can achieve it by just not having windows with no folder associated with them. The main reason we have this restriction is because otherwise the "empty" windows will stack up and then when you relaunch you may get way more windows than expected. Plus since the windows don't really have identifiers associated with them, it's impossible to restore the "empty" windows without closing every VS Code window and relaunching.
