### ISSUE TITLE
Killing Terminal causes failed assertion in winpty.dll and process exit code: 3

### ISSUE THREAD

**Issue by jmlane** [Microsoft/vscode#37780]
Killing any terminal using the UI trash icon causes the following error window:

![image](https://user-images.githubusercontent.com/95528/32504107-68f6258c-c3b5-11e7-8a51-5b4bb257b3bb.png)

In Visual Studio Code, a notification shows:

![image](https://user-images.githubusercontent.com/95528/32504486-4f3aa0c2-c3b6-11e7-86ce-c17faebc8faa.png)

---

- VSCode Version: Code - Insiders 1.18.0-insider (098bb776d2e5fdf3cc9ea27a233754acf4309857, 2017-11-04T04:43:03.436Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.12.1
PowerShell|ms-|1.5.0
vscode-docker|Pet|0.0.20
elm|sbr|0.15.1

---

Steps to Reproduce:

1. Open integrated terminal window.
2. Press "Kill Terminal" trash icon.

Reproduces without extensions: Yes

**Comment by salitynam** [comment]
Same here for me in release version 1.18.0.

- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:19:36.079Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 
Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.17.0
Gradle|caz|1.1.2
java-decompiler|dgi|0.0.1
githistory|don|0.2.3
gitlens|eam|6.0.0
code-runner|for|0.8.3
intellij-idea-keybindings|k--|0.2.16
debugger-for-chrome|msj|3.5.0
java|red|0.13.0
sass-indented|rob|1.4.5
vscode-java-debug|vsc|0.2.0
vscode-java-pack|vsc|0.2.0
vim|vsc|0.10.2
local-history|xyz|1.6.1

**Comment by k8w** [comment]
The same
VSCode 1.19.0-insiders
Win10

**Comment by HenryLie** [comment]
Same problem after updating to 1.18 release.
Might be worth noting that this problem only happens when I use WSL's terminal instead of CMD/Powershell (i.e. by adding   `"terminal.integrated.shell.windows": "C:\\WINDOWS\\system32\\wsl.exe"` to user settings). Using CMD or Powershell does not exhibit this behavior.

- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:22:49.932Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.3
prettier-vscode|esb|0.24.0
auto-close-tag|for|0.5.3
vscode-auto-open-markdown-preview|hnw|0.0.4
typelens|kis|1.5.0
vscode-autoprefixer|mrm|2.1.2
csharp|ms-|1.13.0
debugger-for-chrome|msj|3.5.0
vscode-icons|rob|7.17.0
code-settings-sync|Sha|2.8.5
html5-boilerplate|sid|1.0.1
quokka-vscode|Wal|1.0.77
vscode-todo-highlight|way|0.5.11
blade-runner|yuk|1.0.0

Reproduces without extensions: Yes

**Comment by jmlane** [comment]
@HenryLie I'm using Powershell in the build/configuration for my bug report.

**Comment by HenryLie** [comment]
@jmlane Ah, I see you have powershell extension on your list. Didn't notice that before.

I'm curious because I tested in three Windows 10 PCs (work, home, and colleague's PC) and the behavior is quite similar. On my home and work PC, the error ocurred when I close bash.exe/wsl.exe's terminal window, but does not trigger when I changed my terminal to cmd/powershell. Meanwhile on the colleague's PC which does not have WSL installed, he can also close the terminal window without any problem. That's what leads me to think the problem might be WSL related.

By any chance, do you have WSL feature turned on, even though you're using powershell as vscode's shell?

**Comment by Roscoe93** [comment]
the same bug only when using WSL as terminal

![image](https://user-images.githubusercontent.com/6510690/32777954-2c698172-c973-11e7-8463-23ab6d384aca.png)

![image](https://user-images.githubusercontent.com/6510690/32777979-426a2fb2-c973-11e7-89e5-f5b2a62b414d.png)

**Comment by jmlane** [comment]
@HenryLie I can also replicate that behaviour: WSL is enabled on the host that is described in my the issue, however on another host with a similar environment but *without WSL*, I cannot replicate the winpty.dll assertion error.

**Comment by klirium** [comment]
The same exception happens with "Tasks: Terminate Task" command.
v.1.18.0

**Comment by pkeuter** [comment]
This doesn't happen to me when I close the terminal with the default terminal settings (Powershell), but it does happen when the integrated terminal is set to bash.exe, I open bash.exe with `-c` and `/usr/bin/zsh`. I have also set the terminal font to a powerline font.

**Comment by wolf99** [comment]
Occurring on 1709 (16299.64) also, i.e. non-insiders build.

FYI I use shell launcher to launch different shells

Like @pkeuter above, I also have Zsh, with wsl.exe, but I also have another shell option with bash.exe (launches WSL bash without zsh)

**Comment by Tyriar** [comment]
Can anyone confirm whether this still occurs in v1.19?

**Comment by klirium** [comment]
@Tyriar I have 1.18.1 and everything is ok

**Comment by Tyriar** [comment]
👍
