### ISSUE TITLE
Search Viewlet is consuming a lot of CPU (even when it's hidden)

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#37818]
- VSCode Version: Code - Insiders 1.18.0-insider (af39ef560060e7e8ba8d75983c9ec1da3f4d2a20, 2017-11-07T16:42:33.037Z)
- OS Version: Windows_NT x64 10.0.16299

---

Steps to Reproduce:

1. Execute a search in the search viewlet.
2. I have ~42 results in 12 files.
3. **Open the SCM viewlet**
4. Open one of the files where there is a search result
5. Edit the file such that you add a new search result or that you remove a search result by editing

**Important** because this was so bad that I had to stop what I was doing and check what the hell is causing VS Code to stutter.

> Observe typing/working is perturbed by the search viewlet (which is not visible!). This is all on a quite fast machine

 * first one is 133ms blocked
 * second one is 142ms blocked
 * third one is 320ms blocked

![image](https://user-images.githubusercontent.com/5047891/32553012-f6a07000-c495-11e7-8f78-468f2441d74f.png)

In any case, removing one more result or adding one more result shouldn't take over 10ms.
![image](https://user-images.githubusercontent.com/5047891/32552891-a6c5d444-c495-11e7-88f6-229e3b6c3ade.png)

[CPU-20171108T150231.zip](https://github.com/Microsoft/vscode/files/1454124/CPU-20171108T150231.zip)

**Comment by roblourens** [comment]
Nothing significant has changed here on the search side, as far as I know. The tree is not the most efficient control - the entire thing is being re-rendered on each change. Most of that time is spent rendering the actionbar button. I'll look for a way to optimize that.

It's already debounced on editor changes. On my Mac, it typically updates about 3 times faster than your fastest update. But the distribution of where it spends time is the same.

And it definitely shouldn't be doing an expensive render over and over when it isn't visible! That I will definitely fix...

**Comment by roblourens** [comment]
Fixed to not render when hidden at least.

**Comment by roblourens** [comment]
Turns out that most of the time spent rendering the tree is in `addEventListener`. Did some profiling, and I see that calling `addEventListener` for touch events in particular is extremely slow. We spend a ton of time there as a result of these lines: https://github.com/Microsoft/vscode/blob/1f4ec255ab5595b70920d5338a16cf7b72caef2e/src/vs/base/browser/touch.ts#L103

for the actionbar in each row of the search tree.

Some simple profiling shows `addEventListener` for touch events to be more than 10 times slower than their mouse event counterparts. I can repro the same in normal Chrome. I can't repro this in Firefox. 

I think this is a bug, filed https://bugs.chromium.org/p/chromium/issues/detail?id=784027&can=2&q=addeventlistener%20touch&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified

**Comment by bpasero** [comment]
@roblourens I think this is #37917

**Comment by roblourens** [comment]
Yes!
