### ISSUE TITLE
Every first launch - significant lag, UI elements active but anything typed doesn't appear 

### ISSUE THREAD

**Issue by nikhilksingh** [Microsoft/vscode#37831]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:48.528Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
xml|Dot|1.9.2
gitlens|eam|5.7.1
nuget4code|ffo|0.0.2
gc-excelviewer|Gra|1.1.15
minify|Hoo|0.3.0
Ionide-fsharp|Ion|3.12.1
csharpextensions|jch|1.3.0
hex-rgba-converter|med|1.0.4
mssql|ms-|1.2.0
csharp|ms-|1.13.0
node-debug2|ms-|1.18.5
PowerShell|ms-|1.5.0
team|ms-|1.122.0
debugger-for-chrome|msj|3.5.0
yo|sam|0.9.3
cucumber|ste|0.9.6
vscode-react-native|vsm|0.5.2
change-case|wma|1.0.0

(4 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.
