### ISSUE TITLE
Allow bracket matching style customization

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#3788]
From doc feedback verbatim:
"I'm trying to find out how to change the highlight style of the bracket matching from its current near invisibility regardless of theme to something usable. One shouldn't have to create a whole theme to accomplish this commonly requested customization in all editors/IDEs--just have editor prefs for bracket matching style:[underline|box] and weight:[light|medium|heavy] and color:[#xxxxxx]"

**Comment by drKnoxy** [comment]
googling landed me here, and now i'm sad "mar 7"

**Comment by stormherz** [comment]
> googling landed me here, and now i'm sad "mar 7"

Same here. Is there a chance this will be implemented?

**Comment by eggbit** [comment]
This is an option vscode desperately needs.  Also sad to see this is a 10-month-old request.

**Comment by stormherz** [comment]
@eggbit I've made a PR recently, it will be available as soon as it will me merged

**Comment by dwilliamson** [comment]
Just to add a little support for this; an option to configure the matching cursor just like you can the normal cursor would be amazing.

Right now I find the edit cursor really difficult to locate and I'm constantly making typing errors because I can't immediately see if it's on the left or the right of the closing bracket:

![image](https://cloud.githubusercontent.com/assets/1532903/24794383/4f0a47ec-1b7d-11e7-99d2-718b51478d32.png)

A technique that I've had positive experience with is to simply make the matching brackets bold or a different colour.

**Comment by HYR** [comment]
The ability to change the style of the bracket highlighting to a solid color (instead of bordered rectangle) would be great along with the ability to change the color and opacity.

Something like...
```javascript
// Style highlighted matching brackets with "solid" or "border".
"editor.styleBracketHighlight": solid,

// Color highlighted matching brackets with rgb(), rgba(), or hex color values.
"editor.colorBracketHighlight": rgba(255,255,255,.4),
```

Please... 🙏🏼

**Comment by bpasero** [comment]
With workbench theming you can change brackets border and background color, e.g.:

```json
"workbench.colorCustomizations": {
	"editorBracketMatch.border": "#ff0000",
	"editorBracketMatch.background": "#ff00ff"
}
```

Resulting in:

![image](https://cloud.githubusercontent.com/assets/900690/26277608/3cb0fe94-3d8b-11e7-886b-cdf852715f9a.png)

**Comment by snowghost24** [comment]
Nice. I love that I can change this now.
