### ISSUE TITLE
QuickOpen: Prefill search-text-field with last entered text (Feature Request)

### ISSUE THREAD

**Issue by Michel73** [Microsoft/vscode#37932]
- VSCode Version: 1.17.2
- OS Version: ubuntu16.04

I working with angular and therefore I have similar files with different file-extensions (component.ts, component.html, component.css). Using QuickOpen I have to type the filename for each of them. In IntelliJ the QuickOpen-Dialog (ctrl+shift+n) is prefilled with the last entered text. That's really an ease of use.
Steps to Reproduce:
1. Opens quick open dialog
2. Enter your search and press enter
3. Reopens the quick open dialog --> search-text-field is empty, but should be prefilled with the text from step 2.

Reproduces without extensions: Yes

**Comment by chrmarti** [comment]
Need to reconcile with `"workbench.commandPalette.preserveInput"`.

**Comment by chrmarti** [comment]
@dbaeumer I looked into making this the default for all QuickOpen prefixes. The problem is that this immediately filters and ranks the available choices which basically removes the 'recently used' feature. Due to that we cannot make it the default without removing functionality for some users. For the same reason I'm not sure having a single flag for all prefixes will be good enough, users might rely on the 'recently used' feature more in one case than in the other.

Renaming the setting from `"workbench.quickOpen.prefill"` to `"workbench.quickOpen.preserveInput"` to better align with `"workbench.commandPalette.preserveInput"`.

**Comment by comgit** [comment]
@JimiC Why should this be off by default?

**Comment by Michel73** [comment]
@JimiC Why should this be off by default?

**Comment by chrmarti** [comment]
@Michel73 When it opens without anything prefilled it shows the 'recently opened' files with the most recent ones first. Having a value prefilled hides that feature, which makes me think we should not enable it by default. I use the 'recently opened' files a lot, so I might be biased by that.

One variation I would like to try (and we discussed in the team) is to remember the last value for each prefix and use the setting to enable that. Let me know if this is something you want to work on.

**Comment by Michel73** [comment]
@chrmarti Ok, now I understand the question about the default.
I'm afraid I have no time for further contributions now, but i would appreciate it very much if the prefill feature gets into the release soon.
