### ISSUE TITLE
Please stabilize icon branding

### ISSUE THREAD

**Issue by brianboyko** [Microsoft/vscode#37961]
I understand the need for marketing, but don't understand why you keep changing the icon. It's actually affecting productivity as I'm looking for VSCode in launchpad and didn't see it at first. This minor annoyance isn't really an issue, but it is something that maybe you should look into? The current icon is not my favorite, this is: 

https://cdn.dribbble.com/users/335095/screenshots/2361420/visual_studio_code_icon.png

but whatever, the main issue is that it keeps changing. 

- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T12:32:39.870Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|0.10.10
jsx|Twe|0.0.1
vscode-babel-coloring|dza|0.0.4
prettier-vscode|esb|0.24.0
flow-for-vscode|flo|0.7.2
coldfusion|ili|0.0.11
docthis|joe|0.6.0
vetur|oct|0.11.0
vscode-icons|rob|7.17.0
sass-indented|rob|1.4.5

(2 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by fabiospampinato** [comment]
It has been changed because of https://github.com/Microsoft/vscode/issues/35783.

I don't think they are going to change it anytime soon. If you like another icon I'd suggest you changing it in your system, it's pretty easy to do on macOS.

**Comment by retrixe** [comment]
What @fabiospampinato said.

The 1st change was triggered by the old icon conflicting in color with VSTS and also a request from because it looked out of place on the macOS dock, and was a major redesign which also changed the color to orange. The change to Insiders was the color being chosen as green, previously it was designed to be a sketched orange. The 2nd update to the icon changed the color of stable back to blue but retains design because there was a severe backlash to the color change in the issue mentioned above. Insiders will remain green, and now that most people are okay with the icon, it shouldn't really change.

**Comment by auchenberg** [comment]
Please see https://code.visualstudio.com/blogs/2017/10/24/theicon
