### ISSUE TITLE
VS Code attaches to wrong port when using process picker

### ISSUE THREAD

**Issue by jez9999** [Microsoft/vscode#37985]
I'm trying to do multi-target debugging.  I use a Launch configuration to launch my master process and then use `cluster.fork` to fork a child process.  I then try to start an "Attach to process" debug session, and I pick the forked process (one of whose arguments is `--inspect-port=17130`.  After 10 seconds I get the error:

```Ensure Node was launched with --inspect. Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:9229).```

It tried to connect to port 9229, and unsurprisingly it didn't work.  If I manually set up a launch configuration to attach to port `17130` it works, but why can't the process picker figure out it needs that port?

**Comment by weinand** [comment]
How does the "Attach to process" launch config looks like?

**Comment by weinand** [comment]
What you are seeing is the expected behaviour.

The process picker is used to attach to a node process by **process ID**, not by port.
The idea of the picker is to attach to a node process that was not started with a `--inspect` flag and consequently has no port open. In this case VS Code sends a signal to the node process which starts node's internal debug agent on a fixed port (5858 for node version < 8 and 9222 for node versions >= 8). So when attaching to a node process by ID, you cannot use port 17130 because node uses a hardcoded port anyway.

But in your case the node.js is explicitely started with `--inspect=nnnn`, so there is no need to pick the process by ID because node can directly connect to the known port and then will be the correct process. 

So using the attach config for port `17130` is the way to go.

If you really want to use a process picker, then make sure that the processes you want to pick are **not** started with the `--inspect` flag.

**Comment by jez9999** [comment]
@weinand But the port number changes every time, it seems to be random.  So you have to change the config every time which is really annoying.  Why not add the feature to the process picker that if it detects the `--inspect` flag it tries to attach on that port instead?

**Comment by weinand** [comment]
The connection between the process picker and the node-debugger is via a launch config variable `${command:PickProcess}` which resolves to a process ID. It is not possible to either return a process ID or a port number and then assign this to the corresponding attributes in a launch config. 

Could you try to configure a fixed port for `cluster.fork`?

**Comment by jez9999** [comment]
> The connection between the process picker and the node-debugger is via a launch config variable ${command:PickProcess} which resolves to a process ID. It is not possible to either return a process ID or a port number and then assign this to the corresponding attributes in a launch config.

You could have a special case where the return value `port:xxx` overrides the `port` setting and makes VS Code launch an attach to port instead.

I'm not sure how you configure a port for `cluster.fork` but it's annoying to have to do so because the number of forks is configurable so at the moment I'm just relying on it automatically picking a free port for each forked process.

**Comment by weinand** [comment]
The connection between the process picker command and the node-debugger is based on the generic concept of textual variable substitution. That does not support to substitute different attributes in a launch config.

I suggest to continue the discussion here: https://github.com/Microsoft/vscode/issues/3201
