### ISSUE TITLE
Diffrent results in node debugging and terminal

### ISSUE THREAD

**Issue by fariyAhill** [Microsoft/vscode#3799]
Here is the node debugging result
![706752e8-5f86-4a72-9c90-b268c0a08bff](https://cloud.githubusercontent.com/assets/12928690/13590315/ca4f4772-e519-11e5-973f-091066661ed2.png)

This is another one in terminal.
![601b4805-c290-442f-b935-ef8b74077cc4](https://cloud.githubusercontent.com/assets/12928690/13590317/ccfa675e-e519-11e5-9adf-b8e0864596a2.png)
I use node's FileSystem to read test.txt file,the result confuse me.

**Comment by weinand** [comment]
@fariyAhill what version of node and VS Code are you using?

I just tried VS Code 0.10.10 and node v4.3.0 and your snippet just works fine:

![2016-03-08 13-16-43](https://cloud.githubusercontent.com/assets/1898161/13601417/3f409750-e530-11e5-999e-02c4b7ff7ec1.png)

**Comment by fariyAhill** [comment]
VS Code 0.10.10 and Node V5.6

**Comment by weinand** [comment]
@fariyAhill the problem is that your program expects file 'text.txt' in the current working directory and that you are using different working directory in your two setups.

When running `node index.js` from the command line, the current working directory is where index.js lives. Since in this case the contents of the file is printed correctly, that means that your 'text.txt' lives in the same directory as 'index.js'.

In contrast you have opened VS Code three directories above the place where 'index.js' and 'test.txt' live. This location defines the 'workspaceRoot'. When launching a program from VS Code the current working directory is automatically set to the `${workspaceRoot}`. Since there is no 'test.txt' in that place, 'index.js' fails and prints 'undefined'.

You can fix this problem either by opening VS Code on the directory 'FileSystem' or you can set the `cwd` attribute in your launch configuration to `"cwd": "${workspaceRoot}/github/Node.js-Notes/FileSystem"`.

**Comment by fariyAhill** [comment]
@weinand  thanks,it works.
