### ISSUE TITLE
Contextual File Duplications

### ISSUE THREAD

**Issue by whyisjake** [Microsoft/vscode#38002]
- VSCode Version: Version 1.18.0 (1.18.0)
- OS Version: MacOS 10.13 (17A365)

It would be great if the file explorer had the option to duplicate a file as a contextual menu item. In the development that I do, I frequently take existing component files, duplicate them, and then rename as a way to kick start working on a component. 

In using Sublime Text/Atom/etc, the file tree allows adds the contextual option. In VS Code, I have to open the file in the Finder, duplicate, rename, and then co back to the app and open/edit.

It would be nice to have that all in one spot.

**Comment by isidorn** [comment]
Currently you can simply cmd+c, cmd+v in the explorer to achieve the same thing.
As an alternative you can context menu -> copy, context menu on parent -> paste.

In vscode we are usually trying to be as minimalstic as possible. Due to that I will not add this action to the explorer. Closing this feature request.
