### ISSUE TITLE
升级后编辑区鼠标右键菜单“复制”，”粘贴“等操作只显示英文，不显示中文。

### ISSUE THREAD

**Issue by kbkydwan** [Microsoft/vscode#38010]
- VSCode Version: Code - Insiders 1.19.0-insider (0fbdfff167653b233231259ceb3109f0931887ef, 2017-11-09T08:13:46.054Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|0.10.13
vscode-eslint|dba|1.4.3
jquerysnippets|don|0.0.1
gitlens|eam|6.0.0
vscode-html-css|ecm|0.1.8
php-debug|fel|1.11.1
php-intellisense|fel|1.5.4
php-pack|fel|1.0.1
auto-rename-tag|for|0.0.15
beautify|Hoo|1.1.1
phpcs|ika|0.7.0
vscode-fileheader|mik|0.0.2
HTMLHint|mka|0.4.0
mssql|ms-|1.2.1
debugger-for-chrome|msj|3.5.0
view-in-browser|qin|0.0.5
vscode-icons|rob|7.17.0
bootstrap-3-snippets|wcw|0.1.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by roblourens** [comment]
> Edit area right after the upgrade menu "copy", "paste" and other operations only show English, do not display Chinese

Can you show a screenshot of which labels are not in Chinese?

**Comment by zhangzujian** [comment]
@roblourens 

![1](https://user-images.githubusercontent.com/13048299/32644448-9c3393ee-c61c-11e7-876a-8cf40e7a6fb6.png)

![1](https://user-images.githubusercontent.com/13048299/32644434-878f2c00-c61c-11e7-8c5f-976f6d42408f.png)

**Comment by roblourens** [comment]
I can repro, in the editor context menu.

**Comment by dbaeumer** [comment]
I checked and even with the latest translations merged in yesterday the editors context menu is not translated. I check stable and the menu is correctly translated there:

<img width="284" alt="capture" src="https://user-images.githubusercontent.com/1931590/32650779-5519a4e8-c5ff-11e7-9270-25368dc8fe0f.png">


@alexandrudima moving to you. Is there anything you changed. If you moved something please close since we will recycle with the next Transifex import.

**Comment by alexandrudima** [comment]
@dbaeumer Yes, I have renamed a lot of files in `src/vs/editor/contrib/`.
