### ISSUE TITLE
vscode get slower over time

### ISSUE THREAD

**Issue by adrianpoplavsky** [Microsoft/vscode#38057]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.0
vscode-eslint|dba|1.4.3
githistory|don|0.2.3
Angular2|joh|2.10.0

---

Steps to Reproduce:

1.use vscode and keep ir open for several days, working intensivelly with it.
2.

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.
