### ISSUE TITLE
Use a different presentation style for virtual properties

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#38055]
Today "real" properties and "virtual" properties (like array ranges) are always rendered in the same style: 
![2017-11-10_12-38-23](https://user-images.githubusercontent.com/1898161/32656963-37c74926-c614-11e7-8919-a0cafe043b58.png)

I propose to use a different style for virtual properties to make it clear what is a real property of the debugged data structure and what is an artificial node introduced by VS Code.

This style should be used for the virtual properties that are introduced by the generic VS Code UI and for Variables that have a `presentationHint.kind === "virtual"`. The latter makes it possible for debug adapters to flag a Variable to be a "virtual property".

**Comment by isidorn** [comment]
@weinand makes sense. I would simply go with a different color. Or you had something else in mind?

**Comment by weinand** [comment]
yes, I agree. I was thinking of a different more neutral colour, e.g. grey

**Comment by weinand** [comment]
I've added a 'virtual' value to the VariablePresentationHint type.

**Comment by isidorn** [comment]
@weinand I have decided to go with `opacity: 0.5` to make those properties fade out a bit to make them less important. Did not want to introduce a new color since we already have a bunch. Though I can change all of this easily so let me know what you think

![screen shot 2017-12-04 at 21 41 46](https://user-images.githubusercontent.com/1926584/33575145-f1e29d08-d93b-11e7-8e5d-3fdc2c0b85f2.png)

**Comment by weinand** [comment]
I've verified that this works for a `presentationHint.kind: 'virtual'` by adding this for mock-debug:

![2017-12-05_17-19-42](https://user-images.githubusercontent.com/1898161/33617654-8d9b30d0-d9e0-11e7-9d27-44868ae81811.png)
