### ISSUE TITLE
Icons for all the VS Code file associations, looks weird.

### ISSUE THREAD

**Issue by ZenMittal** [Microsoft/vscode#38063]
- VSCode Version: 1.18.0
- OS Version: Windows 10

![Image of some files](https://image.prntscr.com/image/ZPFjS_NaQXGLn7JDsukJTQ.png)

I moved from sublime to VS Code today. But when I set VS Code as the default app for opening any programming files, it creates this weird icon Instead of some cool icon like that of sublime text.

Any help?

**Comment by agauniyal** [comment]
so you want a new icon? preferably orange colored? 😆

**Comment by ZenMittal** [comment]
haha nope. But VS code's icon embedded inside of a file icon is really offputting. Not sure it's on my end or same for everyone.

**Comment by bpasero** [comment]
We are not planning to change the icon, please see https://code.visualstudio.com/blogs/2017/10/24/theicon

**Comment by ZenMittal** [comment]
I wasn't talking about the main icon at all. I'm talking about the main icon not appearing by itself but embedded inside a file icon.

![real issue](https://image.prntscr.com/image/wdK3sJauReum6hDAohdmvg.png)

Green is okay. Red is the issue.

**Comment by ketozhang** [comment]
@bpasero I think you read the post wrong

I agree with @ZenMittal. While the icon itself looks great as a shortcut. The **file association icon** is bad because it is surrounded by a piece of paper (background is the Windows' default for no-extension).

Please look at this example of a fix. I was able to do this changing the registry however it's a hassle to do it for ALL file extensions (must do it one file type by one unless you got a script).


## Small Icon
![Small Icon](https://i.imgur.com/vxJ3lyB.png)

## Large Icon
![Large Icon](https://i.imgur.com/KImdXQw.png)

**Comment by bpasero** [comment]
@ZenMittal @ketozhang sorry for not being clear, all of the icons we use in our icon update are meant to stay like that, so the file association icon is meant to be like that showing a document.

**Comment by ketozhang** [comment]
@bpasero 
☹️ While it is a minor visual request I guess you guys would only change it if we get another EA-downvote thread like #35783
