### ISSUE TITLE
Matching brackets not highlighted in Makefiles

### ISSUE THREAD

**Issue by bobbogomip** [Microsoft/vscode#38078]
- VSCode Version: Code 1.18.0 _and_ 1.17.2
- OS Version: Linux x64 4.13.10-200.fc26.x86_64

Steps to Reproduce:

1. Open any file that is coloured as a makefile (e.g., `Makefile`).
2. Enter syntactically correct variable expansion:<br/>`a := $(if 1,2,3)`
3. Position the cursor on one of the parentheses.
4. Observe that the parentheses are not highlighted.

This oddity seems to be due to the opening `$`. Remove that and the brackets then become highlighted when the cursor is on them.

Very annoying!

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
@alexandrudima I believe the issue is that the make syntax treats `$(` as a single token. I tried confuring `$(` and `)` as a bracket pair, but this did not work

**Comment by alexandrudima** [comment]
By design, our bracket matching logic ignores brackets in strings, comments and regular expressions. We identify strings, comments, or regular expressions by looking for a specific pattern in the TM scopes coming in from the grammar. In this case, the Makefile grammar marks the `(` and `)` as strings, so our bracket matching logic ignores them.

![image](https://user-images.githubusercontent.com/5047891/32771748-04a05b2e-c924-11e7-83b2-5cc18537234d.png)

This can be corrected from the grammar side if desired.

**Comment by mjbvz** [comment]
Thanks @alexandrudima! That makes sense. I don't know much about our make language support but will investigate adding a language specific configuration for this

**Comment by bobbogomip** [comment]
Um, surely this is a bug? After all, you can bounce on any of these brackets in C++

    files = f(1, g(2, h(), i(6 + 2), 5));

_Make_ contains exactly the same type of code:

    files := \
      $(foreach _,0 1 2 3 4 5 6 7 8 9, \
        $(if $(filter undefined,$(origin $_)),, \
          $(call synchronise,$_))))

Have I typed the correct number of closing brackets?

Sure, `$(` ... `)` expands to a string, but is not itself a string before the expansion.
