### ISSUE TITLE
Improve the select/copy/paste experiences in debug console window

### ISSUE THREAD

**Issue by richardzeng1985** [Microsoft/vscode#3807]
Repro:
 
Try to select the contents in debug console window and copy to text file, only a few part of contents can be copied successfully there, it is very painful if I want to copy some useful information to somewhere.
 
More info:
 
e.g.  The console debug window display some exception, and I want to copy these information to another place, and I try following
 
1.  It makes me confused here when I press "ctrl+a", a it didn't highlight all of the strings which make me think it doesn't work. 
2.  Manually move the mouse to select these contents, and then right click to select "Copy Value" and paste into a text file,  only following contents can be copied into the test file. seems that the "Copy Value" can only copy the value of the variables, however, when I try to use it to copy the output sting, it can only copy a part of output string ? It is not a good experience here.

**Comment by isidorn** [comment]
I totally agree this is not a good experience. 
Due to this we have removed the `Copy Value` action from the context menu and it should not longer be there in March - you have to use <kbd>ctrl + C</kbd>. There are still issues captured in https://github.com/Microsoft/vscode/issues/2163

<kbd>Ctrl + A</kbd> will not work, since the console is not an editor but a tree from the implementation perspective. And due to the issue above.

Closing as the copy / paste limitation of the debug console are already captured in other issues.
