### ISSUE TITLE
CMD + Shift + P keyboard shortcut Doesn't work

### ISSUE THREAD

**Issue by arturogh** [Microsoft/vscode#38097]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T12:32:39.870Z)
- OS Version: Darwin x64 17.2.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.11.0
beautify|Hoo|1.1.1
vscode-custom-css|be5|2.5.0
vscode-multi-line-tricks|big|0.0.3
jshint|dba|0.10.15
vscode-eslint|dba|1.4.3
vscode-coffeescript-preview|dre|0.1.4
vscode-babel-coloring|dza|0.0.4
auto-rename-tag|for|0.0.15
better-line-select|kai|1.0.1
azure-account|ms-|0.2.2

(4 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by arturogh** [comment]
On a Mac, `code --disable-extensions` didn't work on Terminal.

Disabled all extensions, quit and reopened, still running into problem where CMD + Shift + P doesn't work.

Closed a few apps that have keyboard shortcuts, but didn't fix.

Tried again later...it's fixed...don't know what did it, haven't been able to reproduce it again.

Enabled all extensions again, still works. Closed, re-opened VSCode, still works.
