### ISSUE TITLE
Bad visibility of auto imported paths in completion popup

### ISSUE THREAD

**Issue by asvetliakov** [Microsoft/vscode#38102]
- VSCode Version: 1.18
- OS Version: Windows 10

See these 2 screenshots - if i have some big type, it's not possible to see from which place it will be imported until i have to scroll the doc to the bottom:

![pic1](https://user-images.githubusercontent.com/8881674/32686769-21175340-c6ac-11e7-8f81-d5d3ec30303c.png)
![pic2](https://user-images.githubusercontent.com/8881674/32686770-212ed916-c6ac-11e7-83f8-8d52497af385.png)

Suggestion: Move ```Auto import from ....``` to the top

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
Sorry, incorrectly marked this as a duplicate

---

For this issue, we cannot move the entire `auto import from '...'` part to the start of the details section because this may hide the type information information in the condensed detail view, especially for longer paths

Current:

![screen shot 2017-11-16 at 5 40 58 pm](https://user-images.githubusercontent.com/12821956/32925168-5ea630da-caf5-11e7-9797-ec5fb9f62c20.png)

With auto imports at front:

![screen shot 2017-11-16 at 5 53 47 pm](https://user-images.githubusercontent.com/12821956/32925508-1d45ebec-caf7-11e7-8dad-3a316ef026d2.png)

Not sure how we can express this so it works in both the compressed and expanded details view.

@ramya-rao-a @chrmarti @jrieken Any ideas?

**Comment by jrieken** [comment]
Can you use some markdown-styles for the path, like "Auto Import from `@types/foo`"? Another idea is to somehow shorten those overly-verbose detail labels for unnamed types...

**Comment by mjbvz** [comment]
Thanks @jrieken! Yes, I'll try some markdown formatting for the path but now now I am remembering why we went with the current presentation in the first place.

We could also just move the import blurb to the top of the details and accept that the details label will be less useful in the compact suggestion UI. The import path may be the most important part anyways in many cases
