### ISSUE TITLE
Add a new breakpoint will enable all existing deactived breakpoints

### ISSUE THREAD

**Issue by richardzeng1985** [Microsoft/vscode#3811]
Repro:
 
1. Try to set a few breakpoints
2. Deactive these breakponts
3. Try to add a new breakpoint 
 
Observe:
 
All of the deactived breakpoints become enabled

**Comment by weinand** [comment]
@isidorn  most likely a bug in the C++ extension...

**Comment by isidorn** [comment]
No, this is designed. 
Deactivate is a global concept and only all breakpoints can be activated, not a part of the breakpoints. You should use the disable all breakpoints instead of deactivate for this scenario to work.

Adding a new breakpoint is a clear signal to the UI that you are again interested in breakpoints. Also, google chrome does the same.
