### ISSUE TITLE
[Proposal] Add Debugger Controls to the sidebar

### ISSUE THREAD

**Issue by NicoAiko** [Microsoft/vscode#38122]
Currently the debugger controls are in the file's tab menu on the top.

Personally I find that disturbing!

So I thought about it where you could put it instead. 

Add it in here:
![image](https://user-images.githubusercontent.com/22343587/32690771-641b4b7e-c6fc-11e7-9991-152350889b18.png)

**Comment by isidorn** [comment]
@NicoAiko Thank you for the proposal however that is too aggresive and does not go well with the overall design of the activity bar.

Fyi you can hide the debug action bar with `"debug.hideActionBar": true`
Also there are open issues regarding the positiong of the debug action bar which we are looking into. You can find them by searching for older issues in our repo

Due to these I am closing this issue as we will not add it to the activity bar and the issue of action bar placement is already covered in other issues.
