### ISSUE TITLE
Multi-root: support Compound debug configurations across workspace folders

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/vscode#38134]
With multi-root its quite common to have back-end and front-end projects as separate folders loaded in the same workspace. Today a compound defined in one workspace folder doesn't seem to be able to reference another workspace debug config

We should enable compound debug configurations to work across workspaces, to enable a full-stack debug experience.  We already provide a aggregated debug config list in the Debug UI.

<img width="1187" alt="screen shot 2017-11-11 at 2 51 24 pm" src="https://user-images.githubusercontent.com/173559/32694239-1920199e-c6f0-11e7-94a1-edf5cee79d27.png">

**Comment by isidorn** [comment]
I think this feature request makes perfect sense. But I would wait a bit for users to pick up multi root workspaces and see if users jump on this feature before doing anything here.

**Comment by weinand** [comment]
@auchenberg in your initial comment you said "Today a compound defined in one workspace folder doesn't seem to be able to reference another **workspace** debug config".
I assume that you've meant:  "Today a compound defined in one workspace folder doesn't seem to be able to reference another debug config in a different folder of the same workspace."
I've changed the title of this issue to reflect this.

**Comment by weinand** [comment]
We have to decide whether a compound launch config spanning different folders is only allowed in a workspace launch config or in individual folder launch configs. The former case is covered by feature request: #36967

**Comment by auchenberg** [comment]
You could make the argument that a `workspace compound` should be within `<workspace>/.vscode/launch.json` in order to be able to reference a specific launch config within a workspace folder.

**Comment by Disane87** [comment]
Is there an estimated release date for this?

**Comment by weinand** [comment]
One part of this feature is a new syntax for root-folder based variables.
See this related feature request: #38977

**Comment by weinand** [comment]
This work is planned for January.

**Comment by weinand** [comment]
Topics:
1. How to reference a launch config that lives in a different root folder in a compound launch config?
3. Is there a general mechanism to scope variables to another root folder, e.g. `${workspaceRoot:Server}`? (#38977)
2. Is a compound launch config spanning different folders only allowed in a workspace launch config? (#36967)

**Topic 1:**
Assuming that the server lives in a root folder "Server" and the client in a root folder "Client" the proposed syntax looks like this:
```
"compounds": [
    {
        "name": "Compound",
        "configurations": [ "Server: Launch server", "Client: Launch Client" ]
    }
]
```
In addition we could try to resolve launch config names against all root folders and only in case of ambiguities require the root folder name.

**Topic 2:**
Without this it is not possible to support features like "outFiles" or "skipFiles". 

**Topic 3:**
Since it would be a hassle to require that compound launch config spanning different folders are only allowed in a workspace launch config, I think we should

**Comment by auchenberg** [comment]
On top my head, my gut expectation would be to use `<workspaceRoot>/<configName>"` in the configurations` array, such as

```
    "compounds": [
        {
            "name": "Compound",
            "configurations": [
                "api/node launch",
                "frontend/chrome"
            ]
        }
    ]
```

**Comment by weinand** [comment]
@auchenberg yes, that was basically our proposal but it was voted down as "unintuitive" in our standup.
/cc @vscode

**Comment by weinand** [comment]
I've created issue https://github.com/Microsoft/vscode/issues/41779 to address the fundamental issue that workspace folders have no stable ID.
Without a stable ID the folder's "path" must be used which would clash with the @auchenberg's `<workspaceRoot>/<configName>` syntax.

**Comment by roblourens** [comment]
I would resist adding an ID to every workspace folder, and use the folder's path, like "folderPath" in your proposal. It seems very intuitive to me. It would make the compound config much more readable, if I see the real path to the folder, rather than some random number ID.

**Comment by auchenberg** [comment]
+1 on avoiding another unique ID.

Do we know what the usage ratio between relative and absolute paths are? Currently I like the simplicity of `compounds` being a simple array of strings. The nested object structure as proposed in Topic 1) feels very heavy.

**Comment by weinand** [comment]
Yes, I do not like an and additional (and unreadable) ID either.
I would rather like to use the folder "name" that is shown in the explorer as an ID (option 2 in #41779).

Just using the "path" doesn't work for me because "path" is not stable.
If the path of a workpace folder is changed, folder references using that path are broken.

**Comment by isidorn** [comment]
Now we support the following:

* Variable replacment scoped per folder, example `${workspaceFolder:kenneth}` this will get replaced with the path of my workspace with name `kenneth`. This should work for all variables
* A compound can reference any configuration in a workspace simply by specifiying its name in the ` `configurations` array
* In case the `configuraiton` does not have a unique name a compound can reference it using the following syntax `configurations: [{ "name": "Launch Program", "folder": "kenneth" }, "mySecondUniqluelyNamedConfig"]`

Try it out and let me know how it goes.
