### ISSUE TITLE
search in folder, doing the search only in opened files...

### ISSUE THREAD

**Issue by arshavskiy** [Microsoft/vscode#38165]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:19:36.079Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
angular1-code-snippets|ale|0.0.3
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
angular2-snippets|dan|1.0.16
jshint|dba|0.10.15
vscode-eslint|dba|1.4.3
jquerysnippets|don|0.0.1
tslint|eg2|1.0.21
vscode-npm-script|eg2|0.3.3
code-runner|for|0.8.3
angular-bootstrap|her|4.0.6
vue-snippets|hol|0.1.5
beautify|Hoo|1.1.1
search-node-modules|jas|1.2.0
Angular2|joh|2.10.0
angular1-code-snippets-johnpapastyle|lpe|0.1.0
code-beautifier|mic|1.7.2
Angular-BeastCode|Mik|5.0.14
easy-less|mrc|1.4.5
vscode-less|mrm|0.6.3
mssql|ms-|1.2.1
debugger-for-chrome|msj|3.5.0
language-vscode-javascript-angular2|nwa|0.0.11
sort-imports|pet|3.0.1
ejs-language-support|Qas|0.0.1
view-in-browser|qin|0.0.5
autoimport|ste|1.5.3
nodejs-extension-pack|wad|0.1.9
vscode-todo-highlight|way|0.5.11
bootstrap-3-snippets|wcw|0.1.0
JavaScriptSnippets|xab|1.5.0
html-css-class-completion|Zig|1.14.0

(4 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment]
Please describe what is going wrong and provide some steps to reproduce the issue

**Comment by Wo1fie** [comment]
I am experiencing this issue as well.  It started for me today when I updated VS Code and installed this morning's VS Code Insider.  It occurs on both VS Code and Insiders.

Steps to Reproduce:

1. Open a Folder (mine happens to be through samba)
2. Ctrl + Shift + F
3. Expand elipse and add files to include.  Mine is _\*.cfm,*.cfc_ also occurs with using _\*\*/\*.cfm,\*\*/\*.cfc_ (Formatting is hard)
4. Search for anything (like 'a' or a space)
5. See no results unless they exist in a file opened in a tab.

- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:19:36.079Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
vscode-npm-script|eg2|0.3.3
vscode-great-icons|emm|2.1.20
php-debug|fel|1.11.1
php-intellisense|fel|1.5.4
azure-account|ms-|0.2.2
cpptools|ms-|0.14.2
csharp|ms-|1.13.1
mono-debug|ms-|0.15.8
PowerShell|ms-|1.5.0
vscode-docker|Pet|0.0.22
partial-diff|ryu|0.5.0
ColdFusion|Ske|0.0.1
vscode-hexdump|sle|1.6.0
twig|wha|1.0.2

(11 theme extensions excluded)

- VSCode Version: Code - Insiders 1.19.0-insider (3a7d517f65212de615f469587c2ace53275ce96e, 2017-11-15T05:17:28.098Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-cfml|Kam|0.1.4



---

**Comment by roblourens** [comment]
Are there any errors in the search output pane?

![image](https://user-images.githubusercontent.com/323878/32013959-89edf3e4-b971-11e7-8f3d-9f4b4b7790e9.png)

**Comment by Wo1fie** [comment]
It seems this issue only happens when using folder opened through the network.  I am familiar with issues like this from mounted network drives so I use UNC paths.  It occurs whether I run VS Code normally or as administrator.  When I use "whoami" in VS Code's Powershell it shows my proper domain and user which has permissions to the linux server through samba. The filtered search works normally on local directories and the output is basically identical (replace UNC path with local path by opening local folder and it works).

Here is the search output (github code tag not working for me):

`

rg --hidden --heading --line-number --color 'ansi' --colors 'path:none' --colors 'line:none' --colors 'match:fg:red' --colors 'match:style:nobold' --ignore-case -g '//server/folder/\*\*/\*.cfm/\*\*' -g '//server/folder/\*\*/\*.cfm' --max-filesize '314572800' --no-ignore --follow --fixed-strings -- 'a' '\\\\server\\folder'
 \- cwd: c:/
 \- Sibling clauses: {}
No files were searched, which means ripgrep probably applied a filter you didn't expect. Try running again with --debug.

`


- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.026Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: Extensions are disabled
---

Reproduces without extensions: Yes

**Comment by roblourens** [comment]
Somehow the slashes get flipped

**Comment by davide-rota** [comment]
Hello, same problem: happens on a local folder.
Search works if I disable Ripgrep.

This is the output:

`rg --hidden --heading --line-number --color 'ansi' --colors 'path:none' --colors 'line:none' --colors 'match:fg:red' --colors 'match:style:nobold' --ignore-case -g '!/Scripts/**/.git' -g '!/Scripts/**/.svn' -g '!/Scripts/**/.hg' -g '!/Scripts/**/CVS' -g '!/Scripts/**/.DS_Store' -g '!/Scripts/**/node_modules' -g '!/Scripts/**/bower_components' --max-filesize '17179869184' --no-ignore --follow --fixed-strings -- 'write' 'c:\Scripts'
 - cwd: c:/
 - Sibling clauses: {}
c:\Scripts: Access is denied. (os error 5)`

**Comment by ddeath** [comment]
Same here, search works only in opened files. I am using Linux version.

**Comment by FelikZ** [comment]
Same here, please like the topic, so it get better priority!

**Comment by FelikZ** [comment]
1.19.1 - still does not work. Does nobody using an integrated search feature?)

**Comment by roblourens** [comment]
This issue is tracking the search includes not working correctly in UNC paths. @davide-rota 's issue may be with searching in a onedrive-tracked directory, like https://github.com/Microsoft/vscode/issues/35433?

@FelikZ please open a new issue with as many details about your setup as possible, including the info from the search output pane as above.
