### ISSUE TITLE
Dock context menu is useless

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#38199]
The context menu in the dock is totally broken for me. It always used to show somewhat stale information but it just shows the same thing

<img width="397" alt="screen shot 2017-11-13 at 10 05 11" src="https://user-images.githubusercontent.com/1794099/32717519-38284b3e-c85a-11e7-8248-077b59354293.png">

**Comment by bpasero** [comment]
@jrieken yeah, this is partially an issue that I cannot explain, e.g. it almost seems like the context menu gets totally out of sync with the entries we put in (e.g. why would the list contain duplicates?). 

I pushed a change to try to get this list more under our control: instead of just pushing elements into the list blindly, I clear the list and then fill it from exact those elements that we have in our history. 

The added benefit of this approach is that if you remove an individual entry from the history, it should also be gone from the dock menu.

However, if for some reason `app.clearRecentDocuments` and `app.addRecentDocument` fails (which are electron methods), I am out of ideas.
