### ISSUE TITLE
Git Diff if statement braces

### ISSUE THREAD

**Issue by arunAtUman** [Microsoft/vscode#38214]
I made a change to a C++ file on an if statement at the end of a function
I added braces to the if statement changing it from 
```cpp
if (condition)
    dothis;
```
To:
```cpp
if (condition) {
    dothis;
}
```

Please refer to the attached pic of git diff.
![gitdiff_error](https://user-images.githubusercontent.com/33624413/32722944-56639616-c874-11e7-87ef-c7cf44b6fc07.png)
It confusing the end of the function brace and the if statement's end brace. Hope this makes sense.

Thanks!
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:22:49.932Z)
- OS Version: Windows_NT x6

4 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
sourcetrail|ast|0.0.2
githistory|don|0.2.3
python|ms-|0.8.0
cpptools|ms-|0.14.2
python|tht|0.2.3
clang-format|xav|1.6.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by roblourens** [comment]
It may look more as expected if you set `"diffEditor.ignoreTrimWhitespace": false`.

**Comment by joaomoreno** [comment]
@alexandrudima I forget if we already have such heuristics in our diff algorithm.

**Comment by alexandrudima** [comment]
We have some heuristics to give a prettier diff, but none of them cover this case.

@arunAtUman For a quick explanation:
* our diff algorithm uses an algorithm known as [LCS (longest common subsequence)](https://en.wikipedia.org/wiki/Longest_common_subsequence_problem) under the hood.
* the LCS algorithm computes the "equal" lines
* all the other lines are either deleted, inserted or modified


Because in most source code trailing whitespace is inconsequential, we feed all lines in a trimmed fashion to the LCS algorithm.
* for your input the left hand-side becomes:
  (A1) `if (condition)`
  (A2) `dothis;`
  (A3) `}`
* the right-hand side becomes:
  (B1) `if (condition) {`
  (B2) `dothis;`
  (B3) `}`
  (B4) `}`

The LCS algorithm can return two variants for the "equal" lines: one where (A3) matches (B3), and one where (A3) matches (B4). Both variants are technically Longest Common Subsequences. It just so happens that in this case it would have looked better if (A3) would have matched (B4).

**Comment by arunAtUman** [comment]
Thanks for the explanation @alexandrudima! Would like to see it diff as it should but I understand if its relatively low priority
