### ISSUE TITLE
Git functionality is completely  disabled

### ISSUE THREAD

**Issue by vvs** [Microsoft/vscode#38244]
- VSCode Version: Code - Insiders 1.19.0-insider (73830a36872aa1c168c085dad8cc6e2e1a05ff45, 2017-11-13T15:41:17.934Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: Extensions are disabled
---

Steps to Reproduce:

1. Open VS Code
2. Notice that git-related functionality is no there.
3. Open the Git (Source Control) tab, you'll see: "there are no active source control providers".

The log contains the following data:
```
/W:/Soft/VS Code/resources/app/out/vs/workbench/workbench.main.js:9 [Extension Host] Error: Git installation not found.
	at first.then.then (w:\Soft\VS Code\resources\app\extensions\git\out\git.js:96:42)
	at <anonymous>
	at runMicrotasksCallback (internal/process/next_tick.js:64:5)
	at _combinedTickCallback (internal/process/next_tick.js:73:7)
	at process._tickCallback (internal/process/next_tick.js:104:9
```

**Comment by vvs** [comment]
Some additional info. My `git` is not installed in the standard locations (`Program Files`), it is installed on the other hard disk (and the PATH is updated accordingly so that typing `git` works from the console).

When I move my git installation folder to the `C:\Program Files\git`, everything works.

So this VS Code regression is related to the git installed in non-standard locations.

**Comment by joaomoreno** [comment]
Unfortunately we had to disable launching git from the `PATH` due to https://github.com/Microsoft/vscode/issues/32739, https://github.com/Microsoft/vscode/issues/36843, https://github.com/Microsoft/vscode/issues/36201, etc... It was just too costly.

We might consider trying to detect git in other standard locations (such as the one contained in GitHub for Windows). But if it's an arbitrary location, you'll have to set `git.path`. I'll add a `console.log` statement to let the user know this, when this happens.

**Comment by joaomoreno** [comment]
Pushed a better message. Sorry for the breakage.

**Comment by vvs** [comment]
Thank you! :)

**Comment by joaomoreno** [comment]
I will push it further an bring a message in front of the user if we can't find git and detect this is a git repo: #38393

**Comment by pylang** [comment]
Thanks for working on this.  Is there a way to disable upgrade notifications or revert to the previous VSCode release?  While I have the "stable", non-Insider version, I feel a bit like a beta tester when things 
 like git stop working suddenly.
