### ISSUE TITLE
VSCode Insiders Git bug

### ISSUE THREAD

**Issue by superheri** [Microsoft/vscode#38271]
- VSCode Version: Insider commit 73830a36
- OS Version: Windows 10 Fall Creators Update

Steps to Reproduce:

1. Update VSCode Insider to commit 73830a36
2. Git folder is no more visible on the bottom bar near the errors and warnings icons.

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
Can you share a screenshot, showing us what you mean? Are any git features working? Where is your git.exe located?

**Comment by WorrenB** [comment]
Hi,just started vscode insiders and it showsin vscode (stable) it looks like thisGit is located in C:\Users\bjoern.ulrich\AppData\Local\Programs\Git and also included in the path system variable.thank youkind regardsBjoern UlrichJoão Moreno <notifications@github.com> hat am 14. November 2017 um 10:22 geschrieben:Can you share a screenshot, showing us what you mean? Are any git features working? Where is your git.exe located?--You are receiving this because you are subscribed to this thread.Reply to this email directly or view it on GitHub:https://github.com/Microsoft/vscode/issues/38271#issuecomment-344195081

**Comment by WorrenB** [comment]
sorry was another Issue: #38300
I'm new in Github - amateur mistake - sorry for confusion.

kind Regards
Bjoern

**Comment by superheri** [comment]
@joaomoreno 
Folder in VSCode 1.18

![image](https://user-images.githubusercontent.com/30275781/32784924-29d39c5e-c91e-11e7-933e-e7db9cce1568.png)


Same folder in VSCode Insider commit 73830a3

![image](https://user-images.githubusercontent.com/30275781/32784993-5f89c2e2-c91e-11e7-9bac-f6024d31c631.png)

The infos about the dev branch are not here anymore...

**Comment by WorrenB** [comment]
git installation based on https://git-scm.com/ setup.
like mentioned in https://github.com/Microsoft/vscode/issues/38244
my GIT Path also differs from C:\Program Files\Git

tried to set git.path in vscode User Settings - doesn't solve it.
"git.path": "C:\\Users\\bjoern.ulrich\\AppData\\Local\\Programs\\Git\\Git.exe"

Windows Environment Variable "path" was already pointing to
C:\Users\%username%\AppData\Local\Programs\Git - also no solution.

copied GIT Folder from 
C:\Users\%username%\AppData\Local\Programs\Git to 
C:\Program Files\Git 
fixes the problem - but is only a workaround.

**Comment by superheri** [comment]
@WorrenB Thank you for pointing it out. The workaround of copying the git folder on the C:\Program Files\Git works. But I don't have enough space to install everything installed on my C: so my Git and my others programs are located on D:\Programmes\Git

VSCode Insider should be corrected to find the Git folder where it is...

**Comment by joaomoreno** [comment]
https://github.com/Microsoft/vscode/issues/38244#issuecomment-344027257

Please use `git.path` to configure where `git` is located.

**Comment by WorrenB** [comment]
missed to add the "bin" subfolder
"git.path": "C:\Users\bjoern.ulrich\AppData\Local\Programs\Git\bin\Git.exe"
now it works as intended.
