### ISSUE TITLE
Git: Provide navigation through git merge conflicts

### ISSUE THREAD

**Issue by danielo515** [microsoft/vscode#38321]
This is not a bug but a feature request.

It will be very nice if VSCode provides an easy way to navigate through conflicts. Something like a button to go to the next conflict. Currently there is hotkey support only, which is nice but having a visual representation will be useful too. 
Something similar to what is possible on git diff right now.

Regars

**Comment by electriccode** [comment]
This can be an elegant solution.

![image](https://user-images.githubusercontent.com/1471581/34520066-1bf2c84c-f0ad-11e7-8516-80264189fab1.png)

or optionally with a conflict count. All these can be dropped if there is only a single conflict

![image](https://user-images.githubusercontent.com/1471581/34520499-e384fbfe-f0ae-11e7-9796-8e8fd15d2e53.png)

**Comment by danielo515** [comment]
I like the second option, but it should be supported by a non embedded UI. What happens to the UI you have proposed when you choose one option? Does it dissappear?

**Comment by electriccode** [comment]
Hey @danielo515, What do you exactly mean by "non embedded UI"? The arrow navigation will change states for all conflicts when any one of the conflicted state changes either manually or by clicking any of the options available. If I have to really get rid of this additional noise then perfect place for conflict count would be status bar.

![image](https://user-images.githubusercontent.com/1471581/34553808-8240cb2e-f14f-11e7-96a2-7f4546a01397.png)

The navigation UI can be streamlined by using text.

![image](https://user-images.githubusercontent.com/1471581/34553896-facc5734-f14f-11e7-9a76-9d75fe83f792.png)

For consistency the navigation should wrap around so that state for last and first conflict doesn't have to be maintained. For a single conflict we can choose to keep or remove them.

On a side note [this](https://user-images.githubusercontent.com/1471581/34554789-a352f058-f154-11e7-9c8c-3c0fd594ec2b.png) is what I drafted first 😉

**Comment by Billy-** [comment]
This would be a great feature. It might also make sense to automatically go to the next conflict if an option is chosen which resolves the conflict (and thus the actions UI goes away and you can no longer click to navigate to the next conflict)

**Comment by andrewtomai** [comment]
Hi, I'd like to work on this if that's alright.  I figured out how to do the text-based solution and will submit a pull request soon.

**Comment by andrewtomai** [comment]
PR #47884
