### ISSUE TITLE
Windows: Open with... list shows logo with blue background

### ISSUE THREAD

**Issue by dolanmiu** [Microsoft/vscode#38353]
- VSCode Version: 1.18.0
- OS Version: Windows 10

Steps to Reproduce:

1. Right click file > Open With > Choose another app
2. Look with eyes

Reproduces without extensions: Yes

![image](https://user-images.githubusercontent.com/2917613/32806143-769d5bfa-c983-11e7-99af-6f7b4b5d0f0e.png)

**Comment by bpasero** [comment]
As designed.

**Comment by bpasero** [comment]
@joaomoreno we can fix this by adding `AppUserModelID: Microsoft.VisualStudioCode` to the progid windows registry entry we add for each file association. Here is a screenshot how it has to look in order to work:

![image](https://user-images.githubusercontent.com/900690/32888228-d61e3ff6-cac6-11e7-8005-b0407e7cfda9.png)

Can we add this to `code.iss`. I am not sure about the syntax to do so...

**Comment by joaomoreno** [comment]
Basically, around here https://github.com/Microsoft/vscode/blob/master/build/win32/code.iss#L721 you can add:

```
Root: HKCR; Subkey: "{#RegValueName}.ts"; ValueType: string; ValueName: "AppUserModelID"; ValueData: "Microsoft.VisualStudioCode"; Flags: uninsdeletekey; Tasks: associatewithfiles
```

And similar for all file types.

**Comment by bpasero** [comment]
@joaomoreno thanks!

Fixed with one of the most useful multi-cursor invocations in quite a long time...

**Comment by joaomoreno** [comment]
I should probably macro that...
