### ISSUE TITLE
Emmet: "Wrap Individual Lines" wraps once instead of for each line

### ISSUE THREAD

**Issue by SeanKilleen** [Microsoft/vscode#38380]
First-time caller, long-time user. 😄 

Running into an issue where it seems like Emmet's "Wrap Individual Lines" feature may not be functioning as expected -- it appears to wrap a block of text rather than the actual lines, in the exact same way that "Wrap with Abbreviation" currently works. 

I think (but am not 100%) that my understanding of the expected functionality is confirmed by #33703 and #38338.

## Animated Reproduction
![vscode-emmet-wrapindividuallines](https://user-images.githubusercontent.com/2148318/32818711-d6cec496-c992-11e7-82d3-45795596c6d7.gif)

## Steps to Reproduce
* Take a selection that's wrapped in a `<ul>` and contains multiple lines (e.g. to add `li` to)
* Highlight the lines that you'd like to individually wrap with `li`
* Select the "Wrap Individual Lines" emmet functionality from the command palette
* Enter `li` and hit enter

**Expected**: Each individual line is wrapped with `<li>`
**Actual:** Only one `<li>` wrapping is added

## Versioning / Installs
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:22:49.932Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
jshint|dba|0.10.15
gitlens|eam|6.1.0
Ionide-fsharp|Ion|3.12.2
azure-account|ms-|0.2.2
csharp|ms-|1.13.1
PowerShell|ms-|1.5.0
debugger-for-chrome|msj|3.5.0
vscode-docker|Pet|0.0.22
code-spell-checker|str|1.4.12
quokka-vscode|Wal|1.0.79

(1 theme extensions excluded)

**Comment by SeanKilleen** [comment]
I found the tests are for the Emmet functionality; haven't pulled / built the source before but if this needs confirmation I can try to get a failing test in place.

**Comment by usernamehw** [comment]
Shouldn't it be `li*` instead of `li`?

**Comment by SeanKilleen** [comment]
@usernamehw that may be the case and I'll try it. My understanding was that if "wrap with abbreviation" allowed me to wrap an overall selection using `li`, then wrap individual lines would apply that same behavior to each individual line. 

Not in front of vs code now but I'll check that ASAP. Do you happen to have a reference as to why I should expect `li*` to work but not `li` in this case? I dug for a little bit but didn't see anything.

**Comment by usernamehw** [comment]
Seems reasonable. Perhaps, it's using the same parser.

https://github.com/Microsoft/vscode/issues/31814#issuecomment-319569894

Atom and Sublime Text handles this situation according to [Emmet Docs](https://docs.emmet.io/actions/wrap-with-abbreviation/#wrapping-individual-lines). Still wondering if in vscode this is considered a workaround or a permanent solution.

**Comment by ramya-rao-a** [comment]
@usernamehw is right. For wrapping individual lines you need to provide `li*` instead of `li`
@SeanKilleen https://docs.emmet.io/actions/wrap-with-abbreviation/#wrapping-individual-lines is the Emmet documentation for the "wrap individual lines" feature.

The Emmet library when asked to wrap given text with an abbreviation uses the * to make the call if the whole text should be wrapped in the abbreviation or the repeater should be used to wrap individual lines.

Hope this helps.

**Comment by SeanKilleen** [comment]
@ramya-rao-a it totally does help, thanks! Not sure how I missed it in the docs the first time around. Much appreciated!

**Comment by ramya-rao-a** [comment]
No problem, Happy Coding!

**Comment by KucharczykL** [comment]
May I ask what is the point of a separate command (Wrap Individual Lines with Abbreviation) if you still need to include the asterisk?

**Comment by ramya-rao-a** [comment]
@KucharczykL 

The reason for a separate command is described in https://github.com/Microsoft/vscode/issues/31814#issuecomment-319569894

For wrapping individual lines, the lines are passed to the emmet module as an array. See **text** under [expand options](https://github.com/emmetio/expand-abbreviation#options)

For the simple wrap command, in order to support multi cursor well (your cursors can be on lines that have totally different text, and the wrap command will work just fine), we pass `$TM_SELECTED_TEXT` to the emmet module and not the actual text.

PRs are welcome, if anyone wants to give combining the 2 commands a try.
