### ISSUE TITLE
Make "Search in files" and "Ctrl + P" option look at the current project by default

### ISSUE THREAD

**Issue by AmitJoki** [Microsoft/vscode#38421]
- VSCode Version: The Latest as of writing this.
- OS Version: Windows 10

Steps to Reproduce:

1. Include more than one projects in your workspace.
2. Try doing "Search in files" or Ctrl + P option. The results are slow because the whole workspace is being searched and the time taken is getting almost double.

Reproduces without extensions: Yes

Proposed Solution:
-

Most of the times, when I press Ctrl + P or Search In Files, I would be concentrating on the project at hand or the project which is active/tab which is active. So, it would be much semantic if Ctrl + P and Search In Files just concentrated on the project I am working on, so it would be as fast as when I was working without the Workspace option. 

One way to go about this would be to track to which the project the current active tab belongs to and to restrict the Search In Files and Ctrl + P files to that project only.

**Comment by roblourens** [comment]
I don't want to do this because

- we don't really have a 'current project' concept
- how would i switch to a different project, when I use ctrl+p exclusively to switch files? :)

If you want to do a search in just one, you can, by right clicking a folder in the explorer and saying 'Find in folder', or by setting `./folderName` in "files to include" in the search viewlet.

But I would rather focus on why it's slow and how slow it is.

How slow is it? How big is the workspace? Could windows defender be running (do you see msmpeng.exe taking cpu while searching?)

**Comment by AmitJoki** [comment]
Yes, VSCode doesn't have a 'current project' concept, but it sure is a folder-based editor. Wouldn't it be more semantic if the Ctrl + P and Search in Files worked to the context of the current root directory I am working on?

My workspace isn't "large" in a conventional sense. I had a Rails app in its initial development and was working on a React-Native app too. But inclusion of these two projects without much code than what is generated normally, did slow down those operations to a irksome level.

Could we not have a option like "Whole Workspace" or "Current Root Directory" and make the process much more easier?

**Comment by roblourens** [comment]
No, to me it just doesn't fit our model. https://github.com/Microsoft/vscode/issues/32444 will help. If quickopen is slower than one might reasonably expect, then we should investigate that.
