### ISSUE TITLE
Lines in integrated terminal are being cut off at the top

### ISSUE THREAD

**Issue by codemusings** [Microsoft/vscode#38509]
The lines in the integrated terminal are being cut off at the top no matter what font size / line height I use.

My custom settings are:
```
{
    "editor.fontSize": 12,
    "editor.fontFamily": "Liberation Mono",
    "editor.minimap.enabled": false,
    "editor.rulers": [
        80
    ]
}
```

But even if I remove these, there's no change. And like I said, setting another font or a different line height for the terminal doesn't help either.

![grafik](https://user-images.githubusercontent.com/13655994/32890153-e331564a-cacd-11e7-9cb6-c2137d8c48f6.png)

- VSCode Version: 1.18.0
- OS Version: Debian Testing / Gnome 3.26

Reproduces without extensions: Yes

**Comment by Nemo12** [comment]
I have been having the same issue since the 2 previous updates as well.
Changing the font settings does not solve the issue.

 - VSCode Version: 1.18.1
 - OS Version: Debian unstable

I can reproduce the issue with ZSH and BASH, but if I switch to SH it behaves normally.
The difference I noticed between SH and the others is that it has no colour output.
From what I observe, it seems to produce the issue when rendering lines containing colours.

In the following screenshot, we can see that only the directory and prompt are not rendered correctly.
![vscodecolorrendering](https://user-images.githubusercontent.com/1496497/33011675-f6d88d9e-cdde-11e7-812c-c0ac9c66b3f9.png)

The `env` variable LSCOLOR being set with:

```
LSCOLORS=Gxfxcxdxbxegedabagacad
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
```

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/35901
