### ISSUE TITLE
Switching between VSCode windows with any custom app switcher causes high CPU usage

### ISSUE THREAD

**Issue by squareduck** [microsoft/vscode#38516]
- VSCode Version:
1.18.0
- OS Version:
MacOS Sierra 10.12.6

Steps to Reproduce:

1. Open two VSCode windows (e.g two different projects)
2. Use any non-default window switcher (Witch, Contexts, etc)
3. Switch from one VSCode window to another

As soon as you do it for the first time VSCode Helper process with --type renderer will start eating CPU like crazy.

Disabling all extensions or cleaning user config does not help.

I have tested it with Atom and it has the same bug.
So maybe it's Electron issue?

I'm surprised not to find more reports of this. Native cmd-tab is very clunky to use with multi-space and multi-window workflow.

Reproduces without extensions: Yes

**Comment by youurayy** [comment]
related: #41557

Also happens when window-switching (not app-switching) with Karabiner-Elements.
Doesn't happen when switching with CMD+` or via Expose (both are OSX-native).
CPU goes back to normal when a top System Menu Bar item is clicked (no menu command / second menu click is necessary).

I have tried to find this in Electron Issues but could not.

Any ideas how to best debug this? A config in `launch.json` (secondary VSCode), or via Xcode? I have the PID of the helper process + I'm running from sources.

**Comment by youurayy** [comment]
Initial Electron debug & issue created: https://github.com/electron/electron/issues/12606

**Comment by youurayy** [comment]
@squareduck if you could add a reproduction to that Electron issue with the Window-switcher you are using, it may be easier than what I provided (I assume)
