### ISSUE TITLE
Avoid the trailing spaces when generating a doc snippet

### ISSUE THREAD

**Issue by caub** [Microsoft/vscode#38528]
Vscode 1.18.0 / Linux

When generating a function documentation, (typing `/**` then enter)

You get something like:
```js
/**
 * 
 * @param {*} id 
 * @param {*} param1 
 */
```
problem: there are trailing spaces after params (at the end of each lines, after `id`, after `param1`), it's annoying because most linters require no trailing spaces

**Comment by mjbvz** [comment]
Currently not possible to fix this due to how the snippets which power the jsdoc templates work. 

Suggested workarounds:

- Set `"files.trimTrailingWhitespace": true`. This will remove the trailing spaces when you save the file.
- File an issue against the linter for this case

Closing as as-designed
