### ISSUE TITLE
Missing a yarn dependency ("gulp-watch")

### ISSUE THREAD

**Issue by martellaj** [Microsoft/vscode#38581]
Steps to Reproduce:

1. Clone repo.
2. Install packages using `yarn`.
3. Build using `yarn run watch`. 

**Expected**: Code builds successfully.
**Actual**: Error!
![screen shot 2017-11-16 at 8 27 37 pm](https://user-images.githubusercontent.com/1019478/32929538-760e3926-cb0d-11e7-8fc0-327e10d118c9.png)

Note, I was able to fix it by just doing `yarn add gulp-watch` which adds it to the list of dependencies in `package.json`. Obviously it's a dev dependency, but I haven't used yarn since installing it when it came out, so I didn't know the command off the top of my head.

**Comment by martellaj** [comment]
Hm. I can't get it to repro now - might be because I attempted to install `gulp-watch` globally - it's unclear to me. For context, I just reformatted my MacBook, so my `node`/`npm` install was completely clean before trying to build this project. Might be worth looking into, but feel free to close if no one can repro.

**Comment by joaomoreno** [comment]
`gulp-watch` is a dependency from https://github.com/Microsoft/vscode/blob/master/build/lib/watch/package.json

We call `yarn install` in this folder as a `postinstall` step: https://github.com/Microsoft/vscode/blob/master/build/npm/postinstall.js#L65

Make sure that is called during the `postinstall` and that `build/lib/watch/node_modules` gets created.

Closing since user is unblocked.
