### ISSUE TITLE
Cut and paste

### ISSUE THREAD

**Issue by robertkylethomas** [Microsoft/vscode#38613]
- VSCode Version: 1.18.0
- OS Version: Windows 7

Steps to Reproduce:

1. Cut some text
2. Paste and nothing gets pasted

Reproduces without extensions: Yes/No

**Comment by smuuf** [comment]
Works for me.

**Comment by robertkylethomas** [comment]
Yeah its not 100 reproducible every time.

**Comment by wwkeyboard** [comment]
I experienced something similar on OSX. VSCode was running for more than a week, with multiple laptop sleep cycles in that time. Both copy and paste stopped working both within VSCode and between VSCode and external applications. Copy/paste kept working between separate external applications(e.g. terminal and chrome). This happened at a somewhat inconvenient time during the workday so I restarted the machine instead of digging further, this restored functionality and the problem has not resurfaced.

**Comment by roblourens** [comment]
@robertkylethomas Does this happen if you start with `--disable-extensions`? Any errors in the developer tools?

**Comment by rebornix** [comment]
@robertkylethomas @wwkeyboard @smuuf can you confirm that when VSCode stops copy/paste, you happen to launch VSCode from tmux?

**Comment by smuuf** [comment]
Unfortunately I can't confirm anything. I have _no_ problems with `copy/paste` :)

**Comment by whitfin** [comment]
Aappears to happen if you open using `code` or from Terminal in any other way. I can reproduce on latest stable.

There are numerous locked issues by people reporting the same: #13366, #24112, #30533.

**Comment by rebornix** [comment]
It's an Electron limitation and let's track it in https://github.com/Microsoft/vscode/issues/24112, thanks all for your help.
