### ISSUE TITLE
Do not create minimap dom nodes when minimap is disabled

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#38664]
**Bug**
When `"editor.minimap.enabled": false`, we still create minimap dom nodes for each editor:

![screen shot 2017-11-17 at 4 01 55 pm](https://user-images.githubusercontent.com/12821956/32974146-cdc5521e-cbb0-11e7-8d0c-c697c107678a.png)

**Comment by alexandrudima** [comment]
@mjbvz What is the impact of creating that dom node in terms of memory usage and CPU usage ?

**Comment by mjbvz** [comment]
CPU usage is not bad, ~3ms, but it does happen on startup: 

![screen shot 2017-11-20 at 11 41 48 am](https://user-images.githubusercontent.com/12821956/33037954-ebdfe8d4-cde7-11e7-8bd9-a18bce3b7d48.png)

Not sure about memory. Any recommendations for measuring this for something this fine grained?

**Comment by alexandrudima** [comment]
@mjbvz No idea of any tool that shows CPU usage of a dom element creation or memory usage due to a dom element. Since your issue mentions that the creation of dom elements have an impact, I wanted to know how you measured it. Perhaps you know of a tool that I don't know about.

The item you have highlighted at `3.69ms` is the `Minimap` class ctor, which is responsible for anything related to minimap on the editor view side. i.e. this class needs to be instantiated in case someone turns on minimap via settings.

On my machine, the `Minimap` ctor is `1.9ms`, with `1ms` spent in `getOrCreateMinimapCharRenderer`, which allocates an `Uint8ClampedArray` when first invoked for the "minimap font". I can look into postponing the call to `getOrCreateMinimapCharRenderer` until someone actually wants to render a minimap.

**Comment by alexandrudima** [comment]
`Minimap` no longer shows up for me:

<img width="1136" alt="image" src="https://user-images.githubusercontent.com/5047891/33070143-4fa3611e-ceb7-11e7-85b2-b4658c370029.png">
