### ISSUE TITLE
Unable to build VSCode using new instructions.

### ISSUE THREAD

**Issue by CoenraadS** [Microsoft/vscode#38711]
Following: https://github.com/Microsoft/vscode/wiki/How-to-Contribute#build-and-run-from-source

Previously I could build successfully using the batch file, but now I see there are different build steps, but they cause errors for me. I did this on a fresh download.

OS: Windows 10
Python: 2.7.13
Node: 8.2.1
npm: 5.3.0

Steps to Reproduce:

1. `Install Yarn`
2. `yarn`
3. `yarn run watch`

```
PS D:\Downloads\vscode> yarn run watch
yarn run v1.3.2
$ gulp watch --max_old_space_size=4096
[12:40:47] Node flags detected: --max_old_space_size=4096
[12:40:47] Respawned to PID: 7948
D:\Downloads\vscode\build\dependencies.js:46
        const raw = cp.execSync('yarn list --json', { cwd, encoding: 'utf8', env: { ...process.env, NODE_ENV: 'production' }, stdio: [null, null, 'ignore'] });
                                                                                    ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\Downloads\vscode\build\gulpfile.vscode.js:35:14)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by CoenraadS** [comment]
Works with `Node 9.2.0`, while the documentation lists `Node.JS, at least version 8`

**Comment by levani** [comment]
I'm not quite sure but you may fix the issue on 8.2.1 version with `--harmony` flag. object rest/spread properties is behind flag in this version.

**Comment by pfongkye** [comment]
Hi,
I freshly cloned the git repository and I'm getting the following error `An unexpected error occurred: "Cannot create property '-registry-yarnpkg-com' on string '{\"-registry-yarnpkg-com\":true}'"`  on the following extensions folders when post installing using yarn:
`css` `html` `json`

OS: Windows 10
Python: 2.7.13
Node: 8.9.1
npm: 5.5.1
yarn: 1.3.2

Steps to reproduce:
1. Follow [wiki](https://github.com/Microsoft/vscode/wiki/How-to-Contribute#build-and-run-from-source) to have prerequisites since first time trying to build from source
2. Run `yarn` in privileged mode

I'm not sure if it's related to this [commit](https://github.com/Microsoft/vscode/commit/50cabbc80a4e7f38ff20500c02db923e5b734081) but I found out there were modifications done to the 3 folders that I cannot build. Or maybe I'm missing something in my configs.

Any help welcome.
Regards,
Pascal.

**Comment by joaomoreno** [comment]
@CoenraadS Updated the docs for 8.9.1.

@pfongkye What modifications where there?

**Comment by pfongkye** [comment]
@joaomoreno my bad, I think I've found why it was not working with yarn install (whilst using npm install works fine in **postinstall** script in `extensions\{css|json|html}\package.json`). I had the following line in `.yarnrc` messing with my config:
`"registry=https://registry.yarnpkg.com" true`

And for the **wiki**, should `node-gyp` be added as prerequisite or is it only for the section using `windows-build-tools` ?

**Comment by joaomoreno** [comment]
@pfongkye  Good to know.

I don't think you have to install `node-gyp` yourself. Compilation will work without it.

**Comment by pfongkye** [comment]
> I don't think you have to install node-gyp yourself. Compilation will work without it.

That's right. I uninstalled the node-gyp and it worked but when using cmd in elevated mode. I was using Powershell in elevated mode and I didn't succeed unless installing node-gyp. I'm not sure why. 
Anyway, thanks again for your help.
