### ISSUE TITLE
Unable to save file

### ISSUE THREAD

**Issue by kiknag** [Microsoft/vscode#38712]
- VSCode Version: 1.18.1
- OS Version: Mac OS 10.13.1

Steps to Reproduce:
I'm running the node server and just wanted to change some JSON file which includes the website language elements. Unfortunately, when I'm trying to save it and refresh the browser window, the new code disappears and the old one is instead of new one.
![](https://media.giphy.com/media/3ohs7RS76Iy3Mf4t8c/giphy.gif)

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by kiknag** [comment]
I've figured it out what was the problem. Actually, the problem was in JSON file which I was requiring in my Express application. There was a comma after the last element, because of that some Express package work unusually and was overwriting this JSON file.
VScode works absolutely great! 
I apologize for this false alert.
