### ISSUE TITLE
After applying WorkspaceEdits the cursor gets moved to the end of the edit range

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#38728]
- VSCode Version: 1.18
- OS Version: All

**Steps to Reproduce:**

1. Create an extension and register a command with the below code which applies a workspace edit replacing the first 3 lines of the file
```
vscode.commands.registerCommand('add.edits', () => {
	let edit = new vscode.WorkspaceEdit();
	edit.replace(vscode.window.activeTextEditor.document.uri, new vscode.Range(0,0,3,0), 'new line1\nnew line2\nnew line3\n');
	vscode.workspace.applyEdit(edit);
});
```
2. Run the extension, 
3. open a file that has more than 3 lines of code, 
4. place the cursor at the end of second line
5. Run the registered command

**Expected:**
After the text replacement, the cursor remains at the end of the second line

**Actual:**
After the text replacement, the cursor moves to the end of the range that was replaced which in this case is the start of the 4th line

**Impact:**
Major impact of this is for extensions that apply edits on file save and for users that have auto-save on. The cursor keeps moving around annoying users who just want to type in some code :(

**Comment by ramya-rao-a** [comment]
This is a regression. The cursor remains in its position in VS Code 1.17 and earliar

**Comment by Stijnkool** [comment]
I am experiencing this bug in VSCode 1.18.1.
When automatically formatting code on save, the cursor jumps to the end of the file.

**Comment by alexandrudima** [comment]
@Stijnkool You do not have the same issue unless you have created the extension step-by-step, as @ramya-rao-a explains.

Please open a separate issue and describe in detail what your issue is.

**Comment by pharrisee** [comment]
Also seeing this in 1.19.0-insider, saving a Go file causes the cursor to jump to end of file.

**Comment by alexandrudima** [comment]
@ramya-rao-a It is not possible for me to bring back the old behaviour where the cursor would survive on the line it was. The old behaviour was a coincidence regarding how markers were stored per line.

Perhaps you can point me to the go extension code which registers a format provider and I can perhaps create a PR on the go extension side to make it be a format on save participant instead of submitting edits via `workspace.applyEdit`.

**Comment by alexandrudima** [comment]
@ramya-rao-a The thread calls out #13547 as a blocker, but that appears to be resolved. 

The other reason pointed out in a PR that links to the issue is:
> Telemetry shows that about 1/5th of the Go extension users have had formatting times > 1.5 secs.
If we make this switch, then formatting would stop working for such users. This was the reason that I hadn't made the change to use onWillSaveTextDocument myself when this API was released.

@ramya-rao-a Is that the only reason left ?

---

@jrieken Can we please make the format on save cut-off time a setting or increase it ? It is not feasible that I revert the interval tree work to get back the previous markers behaviour. I also cannot "emulate" the old behaviour, as the decoration nodes store `(offsets,lengths)` so they don't know where line breaks occur...

**Comment by alexandrudima** [comment]
@ramya-rao-a If all else fails, I can move all the diffing code over to the go extension to make go submit minimal edits.

**Comment by jrieken** [comment]
> @jrieken Can we please make the format on save cut-off time a setting or increase it 

Sure, accepting PRs ;-) No, should be simple @ramya-rao-a, check with `mainThreadSaveParticipant.ts`... I see that go is not even a *will-save*-participant but a *did-save*-participant which is really, really bad. However, at one point, if saving takes very long we should consider showing a progress message

**Comment by Stijnkool** [comment]
I am having this issue using https://github.com/Krzysztof-Cieslak/vscode-elm. Cursor jumps to end of file on save.
If multiple extensions experience this issue and it cannot be resolved within vscode, perhaps a general way for fixing it within the extension should be documented.
• Are extensions implementing this the wrong way?
• Is there a right way?

**Comment by ramya-rao-a** [comment]
@jrieken Apart from the speed of formatting, the blocker for Go formatting becoming a `will-save` participant is the fact that the Go tool for formatting has issues when asked to work on a buffer instead of file on disk.

> If all else fails, I can copy-paste all the diffing code over to the go extension to make go submit minimal edits.

Can you point me to this diffing code? Submitting minimal edits would be preferable

**Comment by jrieken** [comment]
> Go tool for formatting has issues when asked to work on a buffer instead of file on disk.

How about dumping the file to a temp location? This did-save, modify, save-again thing is really bad as it's easy to get into an endless loops when another extension does the same. 


This is the place which computes more minimal edits: https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/services/editorSimpleWorker.ts#L347. It's programmed against the internal API and runs inside a web worker. Be careful doing this in the extension host as large files and a single edit will freeze up the extension host when computing diffs (we have been there: https://github.com/Microsoft/vscode/issues/15221)

**Comment by ramya-rao-a** [comment]
> How about dumping the file to a temp location

Dumping in temp location won't work. The Go formatting tool compiles code as well and adds missing dependencies, so the file needs to be exactly where it is.

I'll look into the minimal edits

**Comment by alexandrudima** [comment]
@Stijnkool The recommendation is to register a format provider for the language. Then, when users configure `editor.formatOnSave` to `true`, your format provider will be invoked for the text document that will be saved. Then, the edits you return will be diffed against the current text, and a minimal set of edits will be computed and applied. Thus, if your formatter gives a replace-entire-file with new content edit, the edit will be broken up and markers (including the cursor) will survive.

**Comment by ramya-rao-a** [comment]
> Thus, if your formatter gives a replace-entire-file with new content edit, the edit will be broken up and markers (including the cursor) will survive.

@alexandrudima Manual formatting will not follow the above route and so the cursor will end up moving correct?

**Comment by alexandrudima** [comment]
@ramya-rao-a 
* everything eventually reaches the buffer editing logic.
* when editing via `workspace.applyEdits` or `editor.edit` we do not massage the edits in any way.
* when editing via a format provider, we massage the edits. **The reason is that we have had very many format providers that return a "replace entire file" edit**.
* @ramya-rao-a this is something @jrieken implemented and it can be verified by searching for `"computeMoreMinimalEdits"` in our code-base

This is why I am asking that extensions that do formatting please try to:
* create minimal edits (in a perfect world they would be only whitespace edits). This is AFAIK something pretty straight-forward to implement given you have access to an AST. If you do not have access to an AST, please ask the people who do. Any editor that tracks markers will benefit from minimal formatting edits.
* if the above doesn't work out because the people with an access to an AST refuse to help, then follow our API and be a formatting provider. We will diff the edits returned by a formatting provider.

**Comment by ramya-rao-a** [comment]
Closing this issue as the onus seem to be on the extension authors to rewire the way they do formatting.
