### ISSUE TITLE
Is the source code for Live Share available in this repo, to try it early?

### ISSUE THREAD

**Issue by trusktr** [Microsoft/vscode#38733]
Just curious if I can build VSCode myself, to try Live Share. Thanks!

**Comment by benbenbenbenbenben** [comment]
+1

We are debating writing the same functionality into a vscode/atom fork so it would be quite nice to know this work is already available for us.

**Comment by kaburkett** [comment]
This is the repo for live share:

https://github.com/MicrosoftDocs/live-share

**Comment by benbenbenbenbenben** [comment]
@kaburkett that is only the docs.

**Comment by chrisdias** [comment]
Hi!

Live Share is still in its infancy and the source is highly volatile right now. Because of this, we are not ready to release the code, accept external contributions, and more importantly we are not ready to solidify any APIs on which you could build.

So for now, we are focused on releasing updates to Live Share rapidly, enabling folks to kick the tires with the latest bits and to help validate the scenarios.

Live Share is an extension to VS Code, so for the time being please do file issues here: https://github.com/MicrosoftDocs/live-share and as the service matures we'll be in a better position to move to an open development model, like we have with VS Code.

Thanks for understanding our current state and hopefully this gives you enough insight into where we want to go.

//cc: @lostintangent
