### ISSUE TITLE
Allow to drop folder(s) into empty files explorer

### ISSUE THREAD

**Issue by user3323** [Microsoft/vscode#38746]
- VSCode Version: 1.19.0-ins
- OS Version: win7x64

When the workspace is empty - drag'n'drop doesn't work.

![workspace empty - adding folder](https://user-images.githubusercontent.com/24613274/33003286-63b19b1c-cdc2-11e7-9c2b-984bccb19de4.gif)

**Comment by bpasero** [comment]
@isidorn that error seems to be from the recently pushed changes for PR reviews (@rebornix). A window reload is not needed if the dropped folders form a new untitled workspace, however not sure we want to do that all the time. E.g. if you drop just one folder, it would make sense to me that the window reloads to open that folder. If multiple folders are dropped, then we can transition into an untitled workspace. I think that code already exists when you drop folder(s) into the explorer.

**Comment by isidorn** [comment]
@bpasero thanks, however there is no code that does this afaik. Since in the explorer we are always at least in one folder so we always go to a workspace when adding.
I agree that the behavior would be better if only one file is dropped that it is not opened in the workspace. What is the API to do this? Could not find it since there are too many variations of workspace mutation commands

@rebornix do you need a seperate issue for the bug mentioned here?

**Comment by bpasero** [comment]
@isidorn [`IWindowService.openWindow()`](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/windows/electron-browser/windowService.ts#L88) probably with the `forceReuseWindow` option set to true. 

Btw there is a helper method to handle the drop of files or folders here: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/dnd.ts#L172. If you use that one, it automatically takes care of:
* opening 1 folder if its just one
* creating a workspace for multiple folders
* opening a workspace if the dropped file is a workspace

**Comment by isidorn** [comment]
@bpasero thanks, this simplifies things a lot, was not aware of that helper class.
