### ISSUE TITLE
OSX Install shell command description is not specific on quality

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#3877]
The command to install `code` in the $PATH on OSX always says `code` in the command palette but the message following says `code-insiders` or `code-alpha` if it is one of those builds. I was concerned about what it was going to do on the insiders and alpha builds, people may be wary of adding it if they're not sure whether it will install it as a new command.

**Comment by joaomoreno** [comment]
This is due to having to [set that label](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/electron-browser/darwin/cli.contribution.ts#L221) before I know which quality you are running. cc @bpasero 

The only thing I see I can do for now is to rename it to `Install Code command in PATH`, or similar.

**Comment by bpasero** [comment]
@joaomoreno we know the quality upfront, don't we? could be in some global flags.ts thing.

**Comment by joaomoreno** [comment]
[It comes from the context service now](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/electron-browser/darwin/cli.contribution.ts#L62). Any other idea?

**Comment by bpasero** [comment]
@joaomoreno while not encouraged, in this case you can use our old flags style:
https://github.com/Microsoft/vscode/blob/master/src/vs/base/common/flags.ts#L10 and how they get filled in: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/electron-browser/index.html#L191

**Comment by joaomoreno** [comment]
:-1:
