### ISSUE TITLE
files opened by double-clicking in explorer view do not appear in 'Open Recent' menu

### ISSUE THREAD

**Issue by draeger-charles-wilson** [Microsoft/vscode#38782]
VSCode 1.18.1
OS Windows 7
C/C++ 0.14.2

steps:
1. go to explorer view
2. navigate to location of file (for instance some .c file)
3. double-click the file to keep it in the main view
4. click on the file close icon in the file tab
5. go to 'File > Open Recent'
6. note that the just opened and closed file is not in the list

**Comment by af4jm** [comment]
This has been an annoyance of mine for some time, every file that's opened (possibly except quickview) should be in Recent

**Comment by bpasero** [comment]
The recently opened list only updates from other interactions like File > Open. If you want a list of all the recent files you opened, use Ctrl+O and find the files in the "Recently Opened" category.

**Comment by af4jm** [comment]
Are you implying that it's possible for a tab to be created in VSCode without it being a File Open operation?  "Open with Code...", drag & drop, File > Open, double-click in the workspace file tree, and anything else that opens a file... I'd consider it a bug that it's possible for those actions to result in different code paths, never mind that the Recent Files list is filtered by design with no way to unfilter it.

Well, one more on the list of things to check again in a few months, to see if this might become stable enough for routine use.  Amazing how the list keeps getting longer instead of shorter, yet the bells and whistles that would be nice-to-haves if we ever get to production-ready stability are clogging up the pipeline.

Of course since it's called Visual Studio something and isn't based on the Visual Studio core that's been around for years, it's not unreasonable for it to be around this long and still be so riddled with bugs, but what is unreasonable is for those to be ignored like the users are stupid.  If this was only meant to be a Microsoft internal toy editor, why the public releases with 1.x versioning.  As an editor this is light years from 1.0.
