### ISSUE TITLE
how to toggle file menu??

### ISSUE THREAD

**Issue by Qvatra** [Microsoft/vscode#3878]
I did change somehow layout and now a have no file menu thus I even can not open projects.

how to reset this changes or where can I find shortcuts for toggle file menu?

**Comment by nelsonlaquet** [comment]
You can simply press "alt" to view the file menu. You can also hold down alt, and hit the key that is underlined in each menu item to navigate that menu with the keyboard.

Personally, I find it much preferable to having the menu always open.

Anyway, if you want to bring it back permanently without having to hit alt, check under the "View" menu. There should be an option in there to always show it.

**Comment by Qvatra** [comment]
oh my god! that's totally bad idea to bind this toggle thing to alt. I did press alt by mistake and than spend hours to search how to make it visible again. Note that I searched also for shortcut and also didn't find that. I would prefer to have view panel options somewhere on visible place.. or even disable hide option for file menu.

**Comment by nelsonlaquet** [comment]
It doesn't toggle on alt. If the file menu is visible, pressing alt doesn't do anything except bring focus to the menu (like every other application that has a file menu). If you select "View" -> "Toggle Menu Bar" then it hides the menu, but you can still access it with alt. The only way you could have hidden it was by pressing "Toggle Menu Bar" or executing that command from the command window (ctrl+shift+p).

I disagree that this feature needs to be disabled; it's incredibly useful since I never need to use that menu anyway; and it just wastes space.

Did you know you can press ctrl+shift+p to access all of the features from the file menu? For example, to open a folder, hit ctrl+shift+p, type in "ofol" (or "open fo", "ofolder", etc, fuzzy matching is a beautiful thing). You can even type in "mbar" to toggle the file menu if you wish. Much faster than using the file menu.
