### ISSUE TITLE
Slow zooming performance

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#38809]
**Repo**
1. Open editor
2. `cmd` `+` to zoom in

**Perf**
![screen shot 2017-11-20 at 10 43 14 am](https://user-images.githubusercontent.com/12821956/33035379-bd4a9e68-cddf-11e7-95fb-c8f970d112c0.png)

Specifically the call to `e._constructLines @ splitLinesCollection.ts:184` Seems to take along time. I was in the file `jsDocompletionItemProvider` with the workspace state:

![screen shot 2017-11-20 at 10 45 24 am](https://user-images.githubusercontent.com/12821956/33035459-f873da9a-cddf-11e7-8b38-0c41d698af17.png)

**Comment by mjbvz** [comment]
Not sure why this one case was so slow. Subsequent measures of this function were more around ~100ms

**Comment by alexandrudima** [comment]
@mjbvz I cannot reproduce in a clean (default options) VS Code.

I've extracted `jsDocCompletionProvider.ts` from our workspace and tried all sorts of zooming in/out and I could not get `_constructLines` to show up in the profiler.

From your screenshot, it appears the call stack leading to `_constructLines` is caused by one of the following:
* the wrapping indent has changed (`editor.wrappingIndent`)
* the wrapping column has changed (various ways this can happen, e.g. resizing the width of the editor when word wrap is on)
* the ratio of fullwidth/regularwidth characters has changed (i.e. font family change)

Can you please provide additional details, for me, zooming in does not execute `_constructLines`

**Comment by mjbvz** [comment]
Thanks @alexandrudima. I'm going to closing this issue as I'm unable to reproduce it with the current master. I'll let you know if I start hitting this again
