### ISSUE TITLE
Git installation not found.

### ISSUE THREAD

**Issue by jay121169** [Microsoft/vscode#38828]
- VSCode Version: Code - Insiders 1.19.0-insider (c8c6b13528c03986b8dad654cb1d3e796e8dbe97, 2017-11-20T05:13:59.281Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|0.23.0
vscode-eclipse-keybindings|alp|0.9.6
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|0.10.14
vscode-eslint|dba|1.4.3
githistory|don|0.2.3
translation|dus|0.0.4
tslint|eg2|1.0.22
json-tools|eri|1.0.2
paste-image-to-qiniu|fav|0.0.1
code-runner|for|0.8.4
vscode-javac|geo|0.0.47
beautify|Hoo|1.1.1
vscode-regexp-preivew|le0|0.0.3
vscode-fileheader|mik|0.0.2
mssql|ms-|1.2.1
python|ms-|0.8.0
java|red|0.14.0
vscode-icons|rob|7.18.1
vscode-sql-beautify|sen|0.0.4
code-settings-sync|Sha|2.8.6
markdown-preview-enhanced|shd|0.3.0
vscode-java-debug|vsc|0.3.1
vscode-java-pack|vsc|0.2.0

(2 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by jay121169** [comment]
Looking for git in: C:\Program Files\Git\cmd\git.exe
Looking for git in: C:\Program Files (x86)\Git\cmd\git.exe
Looking for git in: C:\Program Files\Git\cmd\git.exe
Git installation not found.

I install Git in E:\

**Comment by rianadon** [comment]
If Git is in your path and still can't be found, you can try setting the `git.path` preference in your settings.

**Comment by ZCShou** [comment]
Cannot find it too. I installed Git in D:\

**Comment by joaomoreno** [comment]
Please configure Code with the `git.path` setting, and point it to where you've installed Git.

**Comment by phpbbireland** [comment]
"Please configure Code with the git.path"? how is this done?

Git runs perfectly with all other tools (that check the path)...

**Comment by rianadon** [comment]
If you navigate to settings (either from the Command Palette or File --> Preferences --> Settings), there is an option `git.path` that you can set to the path of the git executable.

However rather than doing what it does now (which seems like looking for hardcoded paths) VS Code should really be checking the path for git. With VS Code having such great git support it's a shame the autodiscovery of git fails in these cases.

**Comment by phpbbireland** [comment]
Many thanks that sorted it... I guess the problem was meant for me as I don't install any programs to C:\Program Files, I install all development type programs to D:\ and everything else to D:\programs.... only wish windows would let change the default install and the user folder to another drive and path... ;)

**Comment by AshutoshDongare** [comment]
my 2 cents.. the path you need to give in user settings must contain executable file name as well like .....\\git.exe"
