### ISSUE TITLE
Formatter dedents pasted union

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#38833]
_From @andy-ms on July 11, 2017 22:10_

**TypeScript Version:**  nightly (2.5.0-dev.20170707)

**Code**

```ts
type T =
    | number
    | string;
```

Run "Format Document" and there is no change.
Cut this and paste it back, and it will be dedented to:

```ts
type T =
| number
| string;
```

_Copied from original issue: Microsoft/TypeScript#17108_

**Comment by mjbvz** [comment]
_From @mhegazy on November 20, 2017 23:0_

The cut+past issue seems to be VSCode specific. @mjbvz do you have any insights here?

**Comment by rebornix** [comment]
https://github.com/Microsoft/vscode/issues/36294, https://github.com/Microsoft/vscode/issues/29896, https://github.com/microsoft/vscode/issues/38833 share the same root cause: empty lines are not handled gracefully. I pushed a fix which makes this specific case work but it may not work for all cases ;)
