### ISSUE TITLE
Explorer: folders are expanded only later

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#38848]
I find it ugly that when I startup the explorer first shows collapsed and then expanded. Previously we always had everything expanded the way it was before without the extra step of first showing collapsed. 

Showing it right from the beginning if possible imho yields better visual performance and less slugginess. 

![before](https://user-images.githubusercontent.com/900690/33058521-445dfa5c-ce90-11e7-874e-7153bd53e9ad.gif)

**Comment by isidorn** [comment]
@bpasero I can not reproduce this behavior with latest insiders and out of source. Do you still see it?
Looking at the code it is theoretically possible to happen since I first call `setInput` and only then `expand` all of the things that need expansion.
Currently I am doing that [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/electron-browser/views/explorerView.ts#L822) and there is no other way to do this - since one `expandAll` will only expand the elements know to the tree, thus I must expand them in sequence the way I am doing now

fyi @joaomoreno

**Comment by bpasero** [comment]
![before](https://user-images.githubusercontent.com/900690/33565160-a40203ae-d91c-11e7-8449-62bccf0e47fb.gif)

Yeah still reproducible. Might get worse the more folders are expanded. After reload I see some hectic expansion and scrolling happening (briefly).

**Comment by isidorn** [comment]
@bpasero Ok looked a bit further into this and this is just how I designed the explorer during the ftp work.
Previous behavior: once all the roots are resolved we refresh the explorer and expand what is needed.
Now: we resolve all in paralel and as the roots get resolved we refresh the tree and expand what is needed. The downside is the effect you are seeing, the upside is if you have one slow root the whole explorer does not lag from start.

To not overkill the tree with too many refreshes (not on the first one) we have a delayer of 100ms. I could potentially reduce this timeout but apart from that I am out of ideas.

Do you have some recommendation here?

**Comment by bpasero** [comment]
@isidorn can we do this only if there is a remote root folder? The reality is that 0.0% of our users are having a remote folder.
