### ISSUE TITLE
Tests: TypeError: settingPath.split is not a function

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#38847]
I am seeing a weird issue where when I have a test failure in one of my unit tests, this exception pops up:

```
Editor Stacks Model Stack - Multiple Editors - Navigation (across groups):
			     TypeError: settingPath.split is not a function
			      at Object.getConfigurationValue (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/platform/configuration/common/configuration.js:131:32)
			      at TestConfigurationService.inspect (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/platform/configuration/test/common/testConfigurationService.js:47:40)
			      at formatValue (util.js:369:36)
			      at formatProperty (util.js:822:15)
			      at util.js:681:12
			      at Array.map (native)
			      at formatObject (util.js:680:15)
			      at formatValue (util.js:620:16)
			      at Object.inspect (util.js:203:10)
      at getMessage (assert.js:64:24)
```

To reproduce:
* have a test failure (e.g. for me it was an assertion in editorStacksModelTest.ts
* run "test.sh -g Stack"
* see the error

It almost looks like the TestConfigurationService.inspect method ends up on the global stack and is used by the assert framework!?

**Comment by sandy081** [comment]
This is because, Assert framework uses `inspect` function on an object to get its string format.  
In your case, you are asserting `EditorGroup` objects. On failure, Assert gets the string format of the object recursively using properties of the object. Since EditorGroup object has configurationService property which has `inspect` method, Assert is  trying to instantiate that method. Hence this error appears. 

![image](https://user-images.githubusercontent.com/10746682/33065541-71f91f14-cea9-11e7-910a-b0a690321a85.png)


Not sure, how to fix this in general. But one way is to provide a message during assertion.

**Comment by bpasero** [comment]
@sandy081 sucks, maybe ask mocha if there is a way to turn this off? I could not find anything in the documentation when I check just now.

**Comment by sandy081** [comment]
@bpasero This assert is not from `mocha`. It is from `node`. See [here](https://github.com/nodejs/node/blob/v6.5.0/lib/assert.js#L68)

**Comment by bpasero** [comment]
@sandy081 interesting, maybe this helps: https://github.com/nodejs/node/issues/8071#issuecomment-240259088 ?

**Comment by sandy081** [comment]
@bpasero I disabled custom inspect for tests. 

On a side note, the typings of node module does not expose the default options on inspect.

**Comment by bpasero** [comment]
@sandy081 awesome
