### ISSUE TITLE
explorer scroll bug

### ISSUE THREAD

**Issue by Yurunsoft** [Microsoft/vscode#38845]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|0.8.2
template-generator-vscode|Den|0.1.0
githistory|don|0.2.3
php-debug|fel|1.11.1
php-intellisense|fel|2.0.1
crane|Hvy|0.3.8
php-namespace-resolver|Meh|0.8.1
php-docblocker|nei|1.3.2
view-in-browser|qin|0.0.5
phpcomments|yur|0.0.1

---

Steps to Reproduce:

1. new folder
2. mouse scroll

OK:
![11](https://user-images.githubusercontent.com/20104656/33058003-70454de0-cec8-11e7-8297-3933159e2f11.gif)

Bug:
![22](https://user-images.githubusercontent.com/20104656/33058004-70bf764c-cec8-11e7-8f2e-20db3015baa0.gif)

Reproduces without extensions: Yes

**Comment by Yurunsoft** [comment]
![33](https://user-images.githubusercontent.com/20104656/33058097-e72a5c3e-cec8-11e7-8bae-ad7f09d14a33.gif)

**Comment by roblourens** [comment]
I have seen something like this now and then but didn't have reproducible steps. But I can repro it easily like this.

- In the vscode repo, expand src, vs, workbench
- Add a new folder inside workbench
- Without closing the new folder entry, scroll up and down so that it's off screen
- Scroll up and down a few times, see tree weirdness and out of order entries

**Comment by joaomoreno** [comment]
#22269
