### ISSUE TITLE
search string not seeded from selection

### ISSUE THREAD

**Issue by l11vdo** [Microsoft/vscode#38854]
- VSCode Version: 1.18.1
- OS Version: windows 10

Steps to Reproduce:

1. select a string in an open file
2. click the magnifying glass
3. the search string is empty

NB made sure the following was set:
 "editor.find.seedSearchStringFromSelection": true

Reproduces without extensions: Yes/No

**Comment by roblourens** [comment]
This is currently by design. That setting only affects the editor find widget. For search, I want to only  put the text in the search viewlet when someone uses cmd+shift+f from the editor.

**Comment by csicky** [comment]
I searched exactly for this and I find it closed :|
It was working exactly like @l11vdo described in the issue. I too am used to this behavior. It only stopped working since last update. If it's a new design then please bring it back with a user preference.

`"editor.find.seedSearchStringFromSelection": true` for me as I read, would have to set exactly what this issue describes, but it's not working, it's only for the `Ctrl+F` search box?

**Comment by roblourens** [comment]
Trying to make everyone happy :)

In Sublime, there is just one setting that controls this for local and global find. I think it's a valid request but it's different in vscode because there are more ways to activate the search viewlet, which I think shouldn't copy the selected text.

**Comment by csicky** [comment]
I understand about the one setting, I only searched on Google and found this because it stopped working like it did before the update. After searching in the preferences I found this setting which matched the problem :)
Maybe it was a "bug" that got fixed and we got used to it? Or it just happened to work without being actually designed and documented :)

Until the update it worked like this: I have the Explorer panel open >  I select a text in the editor > click on the Search icon to open Search panel > selected text from Editor is inserted by VS Code automatically into search box from Search panel

Since last update, a ~week ago, it doesn't insert the selected text int the search box and I must do 3 more steps in order to perform a search: copy selected text, select previous text in search box, paste copied text.

**Comment by roblourens** [comment]
I changed it in the last update on purpose because I found it annoying when the search viewlet would take the selected text just because I wanted to check previous search results. I think it should take the text in some cases but not others.

**Comment by csicky** [comment]
If possible, it would be good to have it as a preference.
