### ISSUE TITLE
Allow users to customize the color of the icon

### ISSUE THREAD

**Issue by brimonk** [Microsoft/vscode#38898]
Quite simply, I got used to the orange color over the month of October, and come the middle of November, the color has been changed _again!_ I'm not particular on the icon itself, as that's Microsoft's business, but I would like color to move back to orange.

As far as I could tell, the real issue was that a large percentage of the user base simply didn't like the orange coloring. A quick Google/Github search reveals many issues and comments asking for the color to be reverted.

As I write this post, the icon that I look at in the Windows taskbar is blue, but when I search for the application in the Windows search box for "Visual Studio Code", the old orange icon appears.

At the very least, consider allowing users to manipulate the icon _through_ various custom themes.

**Comment by stopthatastronaut** [comment]
Very much +1 on this. I'm red/green colourblind and was really thankful for the orange icon because although I'm told there's a difference between Visual Studio's icon and Code's icon, I'll be damned if I can see it. 

They tell me one is purple and the other is blue. Well guess what? A lot of colourblind people literally don't see purple. It's the red component in there, y'see. I shouldn't have to explain this, but there you go.

Allow users to select different colours _and_ shapes of icons. For a product with "Visual" in the name, this is somewhat laughable.

**Comment by stopthatastronaut** [comment]
I would suggest labelling this "Accessibility".

**Comment by bpasero** [comment]
Thanks for the suggestion but we are not planning to allow this kind of modification to the icon. See also https://code.visualstudio.com/blogs/2017/10/24/theicon
