### ISSUE TITLE
Read vscode-node-debug{2} oss dependencies via package-lock.json

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#38947]
cc @weinand

**Comment by weinand** [comment]
@roblourens since VS Code now uses yarn, I had to upgrade my default node/npm to v8.9.1/v5.5.1.
As a consequence the npm-shrinwrap.json was replaced by package-lock.json.
Since the  package-lock.json now contains both dependencies and devDependencies, it has become more difficult to keep the ms-vscode.node-debug/OSSREADME.json in sync with the npm-shrinwrap.json.

Joao suggested that we just copy the `package-lock.json` into the `ms-vscode.node-debug` stub directory in VS Code. He will take care of extracting the OSS information from it (instead of from the OSSREADME.json).
I've already pushed my `package-lock.json` to `ms-vscode.node-debug`.

**Comment by roblourens** [comment]
Ok, so you just copy the package-lock.json from the extension repo into vscode each time it's updated? I can do that too.

**Comment by weinand** [comment]
yep, that's Joao's suggestion. But currently the package-lock.json is not yet used. Joao has to adapt the OSS tools.

**Comment by weinand** [comment]
Great, thanks!

**Comment by weinand** [comment]
@roblourens while running the OSS tool Alex noted that the "package-lock.json" from node-debug2 has 42 entries where the "version" attribute contains a url instead of a version number.
E.g.: https://github.com/Microsoft/vscode/blob/2aa628bec349dc37827ee8077977064c02e5d714/extensions/ms-vscode.node-debug2/package-lock.json#L50
This made his tool fail.

Since I do not have those bogus entries in the lock file of node-debug I wonder where they are coming from. Do you have an idea?

**Comment by roblourens** [comment]
I'm using npm 5.5.1 (node 8.9.1) and that's just what it gave me. I didn't do anything unusual. I can try to regenerate it.

**Comment by weinand** [comment]
yep, I'm using the same version.

**Comment by roblourens** [comment]
I got the same thing. I also regenerated the node-debug package-lock.json and it changed a lot of version numbers to that same url format. I think that might just be what npm does now.

**Comment by roblourens** [comment]
I don't know why the version number isn't sufficient but the docs say that `version` can contain urls: https://docs.npmjs.com/files/package-lock.json#version-1
