### ISSUE TITLE
Text dissapears in integrated terminal since 1.18

### ISSUE THREAD

**Issue by benmatwil** [Microsoft/vscode#38987]
- VSCode Version: 1.18
- OS Version: Windows 10 16299

Steps to Reproduce:

1. Open integrated terminal with powershell
2. Launch WSL
3. All text except prompt disappears
4. Exit to powershell
5. All further text disappears

![screenshot 6](https://user-images.githubusercontent.com/11423539/33153202-a44f7186-cfd8-11e7-9cee-ef9766d3e1f5.png)

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
@benmatwil could this have started happening after you updated Windows?

**Comment by benmatwil** [comment]
I updated to 16299 in October about a month before so I didn't think so

**Comment by Tyriar** [comment]
@benmatwil does resizing the terminal fix the problem?

**Comment by benmatwil** [comment]
No the issue still remains? Could it be related to the laggy scrolling until vscode’s window is resized in windows?

**Comment by Tyriar** [comment]
@benmatwil I doubt it, also that mouse scrolling issue actually just got fixed in the latest Insider's build 🎉 

Not sure where to go with the investigation here, resizing not changing anything says to me that it's not a problem with the terminal renderer but the backend which is much harder to investigate issues in.
