### ISSUE TITLE
VSCode hangs when doing a callback of a base64 image

### ISSUE THREAD

**Issue by L1qu1d1c3** [Microsoft/vscode#39019]
- VSCode Version: 1.18.1
- OS Version: W10
- Node version 4.5.0

Steps to Reproduce:
- Using VSCode to debug a Node Express.js app
- I have an image of 84kb, 1600x900px
- Using node extension "base64-img"
- Convert a locally stored image to base64 like: base64Img.base64Sync(imagePath);
- Push the base64 value into an array
- Callback it to parent function and VS Code hangs

Reproduces without extensions: Yes

**Comment by weinand** [comment]
What version of node are you using?

**Comment by L1qu1d1c3** [comment]
v4.5.0

**Comment by weinand** [comment]
node v4.5 only supports the "legacy" debugging protocol which results in severe performance problems when debugging large arrays. So the problem you are seeing is probably not really a "hang" but just node.js being busy shuffling the array data around.
 
I suggest to use a more recent version of node.js, e.g. node versions >= 8.0.
These versions support the "inspector" protocol which should no longer have this problem.

If you cannot upgrade to node v8.x, you can try node versions >= 6.3 and < 8.0.
These versions support both the "legacy" and the "inspector" protocol.
Since "legacy" is the default, please add a `"protocol": "inspector"` to your launch config to force use of the "inspector" protocol.

**Comment by L1qu1d1c3** [comment]
If I use the inspector in my launch options, it tells me node: bad option: --inspect=29767 when doing node --inspect=29767 --debug-brk app.js

**Comment by weinand** [comment]
Yes, as I explained above support for the "inspector" protocol starts with node 6.3.
So, the v4.5.0 version you are using does not support it.

Since you are running node on Windows, I even suggest to upgrade to node.js v6.9 since earlier versions of node are unstable on Windows.

Please read our doc about this: https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_supported-nodelike-runtimes

And please note: node versions < 8.0 are not receiving any security updates.
