### ISSUE TITLE
Output panel automatically opens every time since last update

### ISSUE THREAD

**Issue by djeepih** [Microsoft/vscode#39077]
Output panel opens every time I open the application with following message "Git installation not found" (not interested in installing Git on this machine). I have to hide it (CTRL+J) every time. Started happening since last update Insiders 1.19.0 (does not reproduce with VS Code 1.18.1)

- VSCode Version: 1.19.0 VS Code Insiders
- OS Version: Windows 10

Steps to Reproduce:
1. Launch application

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
@joaomoreno Just to confirm, the fix only applies when the user has `"git.ignoreMissingGitWarning": true`, correct?

Otherwise, I see both the notification and the panel being opened:

![screen shot 2017-12-06 at 10 59 29 am](https://user-images.githubusercontent.com/12821956/33679832-af58e6ce-da74-11e7-8a10-822454af6c94.png)

**Comment by djeepih** [comment]
Correct. Look like the setting was introduced with the last update.
