### ISSUE TITLE
Breakpoints just works in my bundle.js but not in my real files [Typescript]

### ISSUE THREAD

**Issue by Arthaclarius** [Microsoft/vscode#39113]
- VSCode Version: 1.18.1
- OS Version: Windows 10

Steps to Reproduce:

1. Put breakpoints into my bundle.js
2. Shows an identical file from my src/*.ts

Reproduces without extensions: Yes

Hello, I have problems with the debugger at the time to put a breakpoint into my .ts files. 

I'm working with 2 folders: `./src/server/server.ts` and `./src/client/index.ts`. My `./webpack.config.js` is in the root, also the `./tsconfig` but the output files are in `./dist/` as `./dist/server.bundle.js` and `./dist/server.bundle.js.map`, also a folder named client but it doesn't matter. 

When I `Attach` the process(the nodejs process) it actually works but only if I put a breakpoint in the `server.bundle.js`. When I do that and the process goes to the breakpoint its open a "new file". It's actually my .ts file but its different because of its another file with the same content and the same name but without a root.

So if I put a breakpoint in my original .ts file its show the error saying `Breakpoint ignore because generate code not found (source map problem?)`

Any idea?

**Comment by auchenberg** [comment]
This sounds like a potential sourcemap and missing config of `outFiles` problem. Please see https://github.com/Microsoft/vscode-node-debug2#when-breakpoints-dont-bind-turn-gray-when-debugging

**Comment by weinand** [comment]
How does your launch config look like?

**Comment by Arthaclarius** [comment]
@weinand 
```
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "attach",
      "name": "Attach by Process",
      "processId": "${command:PickProcess}",
      "port": 8000,
      "sourceMaps": true,
      "remoteRoot": "${workspaceRoot}\\src\\server",
      "localRoot": "${workspaceRoot}\\src\\server",
      "trace": "sm"
    }
```

**Comment by weinand** [comment]
@Arthaclarius 
- why are you using "remoteRoot" and "localRoot"? If they both have the same value, they just make your launch config more complex with providing any value.
- why are you using both "processId" and "port"? If you know the port, it does not make sense to specify a processId. And if you only know the process Id, the port has no effect because "Attach by process id" uses an implicit port. So use at most one, but not both.
- Is port '8000' really the debug port for your application?
- you don't have to specify `"sourceMaps": true` because that's the default anyway. However, you should specify where the generated JavaScript lives via the `outFiles` attribute:

Try this launch config if the node.js process you are debugging has version >= 8.0:
```js
"version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "attach",
      "name": "Attach by Process"
      "outFiles": [
         "${workspaceFolder}/dist/**/*.js
      ]
    }
  ]
}
```

Try this launch config if the node.js process you are debugging has version < 8.0:
```js
"version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "attach",
      "name": "Attach by Process"
      "protocol": "legacy",
      "outFiles": [
         "${workspaceFolder}/dist/**/*.js
      ]
    }
  ]
}
```

**Comment by Arthaclarius** [comment]
@weinand 
I love you! you solve my problems. Thanks you
