### ISSUE TITLE
Extensions taking a while to load

### ISSUE THREAD

**Issue by zbs** [Microsoft/vscode#39140]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
language-haskell|jus|2.4.0
python|ms-|0.8.0
haskelly|UCL|0.4.27

Steps to Reproduce:

1. Open VS Code with several extensions already installed, and several files open that the extensions operate on (e.g. .py file for the Python extensions)

Issue:
The toolbar at the bottom -- which would normally say, e.g. "Python 2.7 64-bit" -- does not contain any of the extensions' buttons until after ~1 minute.

**Comment by alexandrudima** [comment]
@jrieken What are the steps to profile the extension host ?

**Comment by jrieken** [comment]
With latest insiders this https://github.com/Microsoft/vscode/wiki/Performance-Issues#profile-startup, otherwise this https://github.com/Microsoft/vscode/wiki/Performance-Issues#profile-the-extension-process but with `code --inspect-brk-extensions=9333` instead of `--inspect-extensions`

**Comment by alexandrudima** [comment]
@zbs Since very recently, we have a way to profile the extension host start-up sequence.

* Please install the VS Code Insiders version
* Please install the same 3 extensions over there
* Follow these steps: https://github.com/Microsoft/vscode/wiki/Performance-Issues#profile-the-extension-process
* Attach CPU profile of extension host.
