### ISSUE TITLE
Touch: clicking an action like "split editor" does it twice

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#39180]
Steps to Reproduce:

1. use a touch device
2. open an editor
3. touch on the "Split Editor" action

=> the editor splits twice

**Comment by isidorn** [comment]
The issue here was that we were no longer preventing default and stop propagation of the native tap event. This casued that in the split editor case we would both react on the tap event which we generate oand on the click event which vrowser generates for the tap.
I have fixed this to prevent default and stop propagating only if I have found a target to wihc hto forward the tap event. I can not blindly prevent since we also realy on native behavior (input boxes getting focused when tapped)

**Comment by bpasero** [comment]
While the split thing works, when I click on a tab close button, the editor closes and opens again.

**Comment by isidorn** [comment]
Pushing to next week when I have a touch laptop.

**Comment by isidorn** [comment]
@bpasero might be a similar issue as #40616
Did you go through the use of `.target`? I can also take a look

**Comment by bpasero** [comment]
@isidorn yeah good point could be fixed, let me verify when I got a touch device again. I am out tomorrow, so you can also check.

**Comment by isidorn** [comment]
I checked with latest insider on a touch laptop and could not reproduce this any more.

**Comment by bpasero** [comment]
@isidorn nice!
