### ISSUE TITLE
Debug:Evaluate command should add evaluated expression to Debug Console history

### ISSUE THREAD

**Issue by adelphes** [Microsoft/vscode#39182]
- VSCode Version: 1.18.1
- OS Version: Ubuntu 16.04 x64

Reproduces without extensions: Yes

When using the Command Palette or context menu to evaluate an expression in the Debug Console, it would be useful to add the expression to the Debug Console history so that pressing Up Arrow allows the same expression (or a slightly altered expression) to be easily re-evaluated.

- Start a debugging session
- At a stopped breakpoint, highlight a variable and choose Debug:Evaluate from the Command Palette (or Right-click menu) to evaluate the expression in the Debug Console.
- In the Debug Console terminal, press Up arrow to retrieve the last evaluation expression - notice that it isn't the expression chosen above.

**Comment by isidorn** [comment]
This makes sense. We accept PRs that fix this
Code pointers https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/browser/debugEditorActions.ts#L193
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/common/replHistory.ts#L61

**Comment by Dari-K** [comment]
A bit confused by how you should go about getting hold of replHistory. It seems like replHistory is only used in privateReplService, but private in its name and its decorator not being exported seems to suggest that this shouldn't be used outside of https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/repl.ts

**Comment by kla-s** [comment]
Hi, its been a while since this was closed, the whole product has come along way since. 

Could this kindly be reopened, i feel like this is in my 98% path of debugging:

Something throws an error, ill eval it by hitting the keyboard shortcut to evaluate in the debug console. Next i want to iterate but im always annoyed by the additional copy necessary to get it into debug console again. It breaks the flow. 

Thank you!
