### ISSUE TITLE
Cannot set caret when renaming function breakpoint

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#39203]
- create function breakpoint
- double-click on function breakpoint in BREAKPOINTS view to open edit box
- try to set caret anywhere in edit box

Observe: edit box is dismissed

You can only rename a function breakpoint by overtyping the old name.

**Comment by isidorn** [comment]
Might be duplicate of #39211
fyi @joaomoreno

**Comment by joaomoreno** [comment]
@weinand Are you using the mouse or the keyboard to set the caret?

**Comment by weinand** [comment]
the mouse

**Comment by joaomoreno** [comment]
Then it's not a duplicate of #39211.

**Comment by isidorn** [comment]
Ok the issue is that the input box emits a `blur` event even though the user just clicked inside the input box. Not 100% sure why this changed from before, maybe be connected with the fact that I am using templates for rendering.
Also, intrestingly with the latest from master I still can not use arrows to set the cursor in the function breakpoint input box.

@joaomoreno any tips?

**Comment by weinand** [comment]
While verifying I noticed that I cannot insert a space character by typing.
Is this a deliberate feature? Pasting a space character works though.

**Comment by joaomoreno** [comment]
That seems to be something else. Debugging it, it appears that <kbd>Space</kbd> is being swallowed by `debug.toggleBreakpoint`. cc @isidorn 

![image](https://user-images.githubusercontent.com/22350/33720408-23ee5ede-db64-11e7-9abd-ef24cdf0444f.png)

**Comment by isidorn** [comment]
@joaomoreno thanks for finding this, I will fix
