### ISSUE TITLE
Unable to close Miniterm

### ISSUE THREAD

**Issue by Oliv4945** [Microsoft/vscode#39212]
- VSCode Version: 1.18.1
- OS Version: Linux

Steps to Reproduce:
1. Install pyserial `apt-get install python-serial`
2. Start miniterm in VS code integrated terminal
3. Try to escape thanks to ASCII character `0x1D` (`GS` - `CTRL+]` )
While pushing `CTRL` and `]` works and exit on regular terminal, it does not work inside VSCode integrated terminal
Same question than in #22646

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
gnome-terminal and terminator both don't allow me to quit via ctrl+] either, what is your "regular terminal"?

**Comment by Tyriar** [comment]
I'm going to close this off since VS Code works the same as the standard terminals. If you can find what's not being done correctly and it's standard behavior (this is typically the reference I work off invisible-island.net/xterm/ctlseqs/ctlseqs.html) then please create an issue against xterm.js https://github.com/xtermjs/xterm.js
