### ISSUE TITLE
Smart loading of extensions based on manifest

### ISSUE THREAD

**Issue by JasCodes** [microsoft/vscode#39272]
Extensions part of vscode requires overhaul; and extension.json manifest files might be great way to fix this.

It would be great if it were possible to add manifest of extensions in project settings. So when project or workspace is open; vscode loads only extensions mentioned in either project level or workspace level or user level.

If the extension is not yet present; vscode could pulls it from internet but only load the one required as per extension.json manifest.

This will improve the performance of vscode as user if choose can put majority of extensions need for project in project setting i.e it goes into git repo itself. This will also create consistent dev experince as they are no required to manually install recommend extensions.

This approach automatically fixes setting sync issue; as all of things about vscode is manifest in files which can in turn life in github.

Thx

**Comment by jcrben** [comment]
This seems similar https://github.com/Microsoft/vscode/issues/40109:
>it would be nice to have something like an editor profile per project, so that only relevant extensions would be loaded for that project. Ideally, extensions could be installed automatically if I would checkout an existing project that contains a profile and requires extensions that I don't have, yet

**Comment by melMass** [comment]
@jcrben Why is #40109 closed ? It seems crucial to me working with different languages, frameworks, and so extensions.

**Comment by jcrben** [comment]
I'm just a user, but it seems prettt much the same as this, right? Extension loading scoped to a specific project

**Comment by melMass** [comment]
It is. Sorry, I thought you where from VS team.
I'm trying the: disable all, enable per workspace approach (manually) now but it's a pain....

**Comment by cswl** [comment]
Any updates on this or any other issue related ?

**Comment by createdbyjurand** [comment]
I work on 5 computers in 3 locations.
I had to manually enable and disable extensions for 32 projects workspaces on each computer because there is no way I can set this in .vdcode settings :(
This sucks.

I know there is already working extensions.json file in .vscode folder that supplies "Recommended" extensions list.

Please extend its use.

I know that forcing installation of extensions is dangerous and it is a bad idea, BUT, 
if user has the extension and .vscode/extensions.json has it on enabled list - enable it
if user does not have the extension and .vscode/extensions.json has it on enabled list - recommend it
if user has the extension and .vscode/extension.json has it on disabled list - disable it

and add by default option in vscode not to follow the extensions.json, BUT,
make it as an option so some of us could turn it on in user settings.json and/or workspace settings.json :)

**Comment by jlongo** [comment]
Seems to me the obvious necessity of something like profiles for extensions.
VSCode is used to develop many languages from same developper. PHP, Node, React, React.Native, C#, java, and many others. For each diferent language in use in one project we need different extensions and with all installed many times arrises some incompatibility or unexpected beavior between them and also computer resources wasted. Disabling/Enabling them at workspace level it's a tedious work each time we start a new project. Using a portable folder for each "profile" we need it's insane. We can also make symlinks to data directory with some OS scripting to avoid waste of space on portable instalation files, but we have it with user data folders and extensions folders.
Something like 
"Profile A" -> ext1, ext2, ext3.... and so on enabled
"Profile B" -> ext1b, ext2b, ext3b.... and so on enabled
"Profile N" -> ....
And all out of list disabled...
And the definition of the profile in use is associated with workspace settings
Algo give the user the possibility to fine tune the workspace to some special needs based on profile in use.

Just my opinion, thanks for the great work made with this editor.

**Comment by jlongo** [comment]
#40109

**Comment by liangjiancang** [comment]
And there should be a "no workspace profile". It's so annoying to load all extensions when opening a *.txt file.

**Comment by ldsands** [comment]
Could we not also base this upon the language as well. For example, if you open a folder and there are .csproj and fs files then all the c#/.net extensions load and then also the f# extensions as well?

A lot of the options that have been discussed in similar issues I think would be a lot easier to deal with if they took into account the languages in the folder that is being worked on.

Some example options that I have thought of could look something like one or more options below:

```json
{
    "[python]": {
        "editor.defaultFormatter": "ms-python.python",
        "editor.rulers": [
            88
        ],
        "extensions.activation": [
            "magicstack.magicpython"
            "ms-python.python"
            "njpwerner.autodocstring"
            "frhtylcn.pythonsnippets"
        ]
    },
    // global whitelist option
    "extension.global.activation": [
        "akamud.vscode-theme-onelight",
        "salbert.copy-text"
    ],
    // global blacklist option
    "extension.global.deactivation": [
        "akamud.vscode-theme-onelight",
        "salbert.copy-text"
    ],
    // per extension whitelist option
    "extension.global.activation": {
        "akamud.vscode-theme-onelight": [
            "python",
            "markdown"
        ],
    }
}
```

I also like the idea of using user defined extension groups that can be used instead of the more verbose way that I show above as mentioned in [this post](https://github.com/microsoft/vscode/issues/57548#issuecomment-417403308).

Others have suggest similar solutions or discussed this in comments [here],(https://github.com/microsoft/vscode/issues/40239#issuecomment-521186857), [here](https://github.com/microsoft/vscode/issues/78349), [here](https://github.com/microsoft/vscode/issues/40239#issuecomment-537496087), [here](https://github.com/microsoft/vscode/issues/39272), [here](https://github.com/microsoft/vscode/issues/18386) and many more.

**Comment by Metadorius** [comment]
Any further updates on this?

**Comment by mesqueeb** [comment]
I need to be able to sync the `.vscode/settings.json` file in my GIT so my whole team has the same configuration for this project.

Some plugins we use clash and break VSCode, so to avoid it we need to `disable (workspace)` a specific plugin for our workspace.

Now I need to make sure everyone does that manually... If this setting can just be saved in `.vscode/settings.json` it would make our teamwork way more efficient! 

That's my 2 cents on this : )

**Comment by hxse** [comment]
I found a way in cli:
```
code --list-extensions
code --disable-extension <extension id> --disable-extension <extension2 id> <package name>
```
This way you can start your project from the command line and disable unwanted extensions.

**Comment by g13013** [comment]
this would be a great feature

I am proposing another feature #137091 that could benefit from this feature.

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/347
