### ISSUE TITLE
Close Folder Keyboard Shortcut

### ISSUE THREAD

**Issue by mattmcnabb** [Microsoft/vscode#39274]
The keyboard shortcut for opening a folder is `Ctrl+K Ctrl+O`, but the shortcut for closing a folder is `Ctrl+K F`. This is a bit non-intuitive, and I'd prefer if both the close and open shortcuts had the same pattern. Can we have `Ctrl+K Ctrl+F` close the current folder instead? This shortcut is currently bound to Format Selection so this would technically be a breaking change. Thanks!

**Comment by cleidigh** [comment]
@mattmcnabb 
Apologies if I am stating the obvious or I've misinterpreted your question.  All the commands
you reference are configurable in keybindings.  You can set up exactly to your liking.  I don't think
the team likes to change default keybindings especially since everyone has their own favorites.
