### ISSUE TITLE
Terminal --> "clear" keybinding "Ctrl + K" doesn't work

### ISSUE THREAD

**Issue by user3323** [Microsoft/vscode#39312]
- VSCode Version: 1.19.0-ins
- OS Version: win7x64

We have keybinding for the clear the terminal bound up with `Ctrl + K`

![image](https://user-images.githubusercontent.com/24613274/33377225-6579de60-d519-11e7-877c-ff485e038bec.png)

... but it doesn't work. All I see is this:

![image](https://user-images.githubusercontent.com/24613274/33377423-174e3050-d51a-11e7-934f-b6f1d50b4eb6.png)

**Comment by Tyriar** [comment]
Do you have any ctrl+k chord keybindings set?

**Comment by user3323** [comment]
@Tyriar, nope.

It's not only about `Ctrl+K`. It's about any "Ctrl ..."

In any "Ctrl + something" - control becomes ^ and no action.

**Comment by Tyriar** [comment]
@user3323 inside the terminal the default is for ctrl+something to be sent to the terminal and ctrl in the terminal is represented as `^`. This is a little different to how it works in other Windows terminals as it's running through a system emulating how it works on Linux and macOS.

Normally ctrl+k would only not work when you have some keybinding defined that conflicts with it, this could be a keybinding you added or one contributed by an extension unfortunately. The fix for you is likely to redefine the clear keybinding at the bottom of your keybindings file:

```js
{ "key": "ctrl+k",                "command": "workbench.action.terminal.clear",
                                     "when": "terminalFocus" },
```

**Comment by user3323** [comment]
@Tyriar , I figured out why this happens.

So, it's all about `"when"` key, and not just this key in my keybinding for terminal, but about any other keybinding, that has **NOT** defined `"when"` key and has (in this case) `Ctrl+K` .... even with something after that, like `Ctrl+K Ctrl+J`

so... when you have something like this:

```
{
  "key": "ctrl+k ctrl+j",
  "command": "workbench.action.configureLocale",
  // "when": "editorTextFocus"
},
```

and don't have specific keybinding like you wrote above - it will cause in ^K

**Comment by user3323** [comment]
@Tyriar , now I don't know how to bind `Ctrl+Backspace` for deleting word on the left.

I wrote a keybinding:

```
{
  "key": "ctrl+backspace",
  "command": "workbench.action.terminal.deleteWordLeft",
  "when": "terminalFocus"
}
```

but every time I press `Ctrl+Backspace` in terminal - it becomes into `^W`
I have commented every `Ctrl+W` keybinding, so I'm sure I don't have conflicts.
But still - nothing.

**Comment by Tyriar** [comment]
@user3323 see https://github.com/Microsoft/vscode/issues/31821
