### ISSUE TITLE
See network requests made by extensions in network tab of developer tools

### ISSUE THREAD

**Issue by nicksnyder** [Microsoft/vscode#39388]
This would be useful to me both as a user (to see what extension are doing) and as a developer (to debug extensions).

<img width="1440" alt="screen shot 2017-11-30 at 3 13 27 pm" src="https://user-images.githubusercontent.com/754768/33460034-33af8466-d5e1-11e7-934b-75fc338d7142.png">

**Comment by bestkanthed** [comment]
I would want the same

**Comment by itsdarrylnorris** [comment]
Same here.

**Comment by thakkarparth007** [comment]
+1

**Comment by Fernando-Abreu** [comment]
+1

**Comment by zutshisunakshi** [comment]
![Screenshot 2023-07-12 at 3 53 49 PM](https://github.com/microsoft/vscode/assets/18541122/aaddf239-6a22-4778-ab56-9fc41eb3a231)

I don't see any requests/response coming in network tab now, did anything change?

**Comment by tinkerology** [comment]
This really would be super helpful, especially for debugging extensions.

**Comment by aryamankha** [comment]
+1

**Comment by supuwoerc** [comment]
+1

**Comment by RichardoC** [comment]
For anyone trying to do this, vscode doesn't support this but you can use a Man-In-The-Middle (MITM) proxy to capture all traffic from VScode, including from extensions.

Warning, this will capture all API calls including API tokens, and effectively disable HTTPS verfication so only use if you know what you're doing

## Steps
* Install [Zap](https://www.zaproxy.org/download/)
* Start ZAP, it'll set up a proxy running on http://localhost:8080
* Configure VScode to use this proxy by setting the following settings
  * "http.proxy": "http://localhost:8080"
  * "http.proxyStrictSSL": false
  * "http.proxySupport": "override"
* Now close Vscode, and reopen it from a terminal with `code   --ignore-certificate-errors`
* Inspect the traffic by following the [quick start guide for ZAP](https://www.zaproxy.org/docs/desktop/start/)

### Why disable all these security features?
* VScode will not trust the ZAP CA, even if it's added to the system certificate chain due to extensions ignoring [some settings](https://github.com/microsoft/vscode-remote-release/issues/2987) so we have to disable verification

### When finished
* Delete "http.proxy" setting
* Close VScode
* Reopen VS code normally

**Comment by leodotcloud** [comment]
Thanks @RichardoC, your comment was super helpful.

ZAP didn't work with an extension involving "streaming" connections, so I ended up using mitmproxy (https://mitmproxy.org/). Posting it here in case someone else finds it useful.

**Comment by GlitchedCode** [comment]
why are you not implementing this

**Comment by zoypk** [comment]
+1
