### ISSUE TITLE
can't search with unicode regular expression

### ISSUE THREAD

**Issue by feichao** [Microsoft/vscode#39404]
can't search with unicode regular expression
- VSCode Version: 1.18.1 (1.18.1)
- OS Version: macOS  10.12.6

Steps to Reproduce:

1. input a unicode regular expression, e.g. [\u4e00-\u9fa5]
2. some error occur
![error](https://user-images.githubusercontent.com/11988943/33473430-6145326a-d6b1-11e7-9e2d-5a8c2c61ecbf.png)

Reproduces without extensions: Yes

**Comment by roblourens** [comment]
I think you need to use `[\x{4e00}-\x{9fa5}]`. Does that work how you expect?

**Comment by feichao** [comment]
Thanks a lot. But it doesn't work... Actually I want to search all the Chinese in my project.

![image](https://user-images.githubusercontent.com/11988943/33516330-28cb17be-d7ac-11e7-9615-e896ae761b3f.png)

**Comment by adelphes** [comment]
You can't use unicode escape character ranges because VSCode search uses two incompatible regex engines - one search engine uses the [JavaScript regular expression](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions) syntax (albeit without the 'u' unicode flag), the other is based on [ripgrep](https://github.com/BurntSushi/ripgrep) which uses [Rust regular expression](https://doc.rust-lang.org/regex/regex/index.html#syntax) syntax.

If you use the Rust syntax: `[\x{4e00}-\x{9fa5}]` the JS RegExp parses this as a range between `}` and `x` - this is an invalid range because `x` < `{`.
If you use the JS syntax `[\u4e00-\u9fa5]` ripGrep cannot recognise the `\uXXXX` escape.

Since JS RegExp doesn't support the `\x{XXXX}` syntax and Rust doesn't support `\uXXXX` syntax, the
end result is one of the engines will always error.

**Comment by roblourens** [comment]
Correct - I filed an issue upstream. vscode could also rewrite the `\u` patterns to `\x` for ripgrep.

**Comment by skyfore** [comment]
@roblourens Well, Is there any way to slove the problem ?

**Comment by roblourens** [comment]
There is activity on the upstream issue but it's not pulled into vscode yet.

**Comment by roblourens** [comment]
This was fixed upstream recently
