### ISSUE TITLE
Find widget never empty

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#39422]
Do not have anything selected in your editor
cmd + f -> find widget, the input always has some value. If my cursor is on a word, that whole word will be inputed to the find widget.

Adding to november since this is breaking the flow of users (including mine)
I am usind to doing cmd + f and just star typing, however now there is input already there so I always end up with a broken find expression

fyi @alexandrudima

**Comment by rebornix** [comment]
@isidorn the behavior exists before I touched the code base of Find Widget 👴 , I was surprised the first time when I saw it but later I understand why it's useful for some users.

I made some changes to `editor.find.seedSearchStringFromSelection` last week, so if you set `editor.find.seedSearchStringFromSelection` to `false`, nothing will be populated to the find widget, whether there is a selection or not.

Let me know if this option is good enough for you (as a workaround). Disabling this feature (populate word under cursor to find widget) by default might be too late for Nov.

**Comment by isidorn** [comment]
@rebornix yes changing this setting fixes the issue for me.
However I feel like something has changed from before regarding this behavior whis was breaking my work flow the last couple of days. Somehow I can not distill it in a nice issue (with lates vscode insiders), thus closing this.
My problem from friday might be that the find widget was not being selected thus me typing in it would not overwrite the input

**Comment by isidorn** [comment]
@rebornix ok I found the regression

1. First editor, open find widget with some input which can not be found in the second file
2. Open another file in the same editor, open find widget -> the input is not selected, and the wrong input is pasted in the find box from the original file

Because the input is not selected, I automatically start typing and the input is not overwritten, which is brekaing behavior for my muscle memory.
Sorry for not explaining this properly in the original comment. Basically the issue here is that the find widget inputs are somehow bassed between files which is wrong.

![find](https://user-images.githubusercontent.com/1926584/33548673-3dc69944-d8e8-11e7-82f4-ca792ff65250.gif)

**Comment by alexandrudima** [comment]
@rebornix  I believe it is somehow caused by #35956. 

I also just ran into this. I got some random stuff (I guess from the "find" clipboard) showing up in the find input, but in a delayed way.

**Comment by rebornix** [comment]
I ran into the same issue this morning and thanks for finding the root cause.

**Comment by melvin0008** [comment]
I would like to know more about these issues:

@alexandrudima what do you mean by "in a delayed way"

@isidorn what do you mean by "wrong input is pasted". Also, when I tried to recreate the above, I was able to overwrite the find input.

**Comment by melvin0008** [comment]
@alexandrudima You may have copied some text in some other application like Chrome.

This changes the globalclipboard find buffer. When you go back to VSCode it repopulates the find from what it found in chrome.  I believe the globalclipboard buffer works the same way in Chrome, Firefox, Sublime, etc on MacOS

**Comment by wprater** [comment]
> This changes the globalclipboard find buffer. When you go back to VSCode it repopulates the find from what it found in chrome. I believe the globalclipboard buffer works the same way in Chrome, Firefox, Sublime, etc on MacOS

yes, the global find buffer will populate search fields across all MacOS apps.  this is by design, so I wonder if that's what you're experiencing?

**Comment by rebornix** [comment]
I played with other macOS applications and @melvin0008 and @wprater are right, auto populating search string from global find clipboard is the expected behavior, for short

1. Search `ABC` in TextEdit
2. Open Sublime/Chrome, trigger Find, `ABC` is automatically populated into the Find input box
3. Type and update the query string to `DEF`, press enter.
4. Switch back to TextEdit, `DEF` is automatically populated into the Find input box, `ABC` is being replaced and the new query string `DEF` is selected.

We didn't automatically select the new query string in VSCode, that's why it's against @isidorn 's muscle memory. It doesn't necessarily mean it's wrong (Chrome on macOS behaves the same way) but we can make it closer to what ppl used to (auto select). For @isidorn 's particular problem, it's solved.

Moreover, I added an option `editor.find.globalFindClipboard` to allow users to disable this feature. Even though this is a system level feature, our near-million macOS users may still be surprised.
