### ISSUE TITLE
Ctrl hover shows a less useful hint when fn opening brace is on a new line

### ISSUE THREAD

**Issue by bmewburn** [Microsoft/vscode#39458]
![ctrl_hover_hints](https://user-images.githubusercontent.com/5885195/33512908-825d67b6-d78c-11e7-8f6a-5188d8fa7a6a.gif)

The textDocument/definition response range is that of the entire symbol definition (header + body) in both cases.

**Comment by roblourens** [comment]
@mjbvz Problem is not with PHP, is with the hover widget and rendering these LSP messages. Who owns that?

**Comment by alexandrudima** [comment]
This is the jump to definition hover.

**Comment by bpasero** [comment]
I think the current incarnation of that hover came in via https://github.com/Microsoft/vscode/commit/34cdf9f9be1b9dcceb017dacdf4388c8fa44f7c8

**Comment by faso** [comment]
I'd like to take this one

**Comment by jrieken** [comment]
It's yours @faso. The code is here: https://github.com/Microsoft/vscode/blob/e7bc65ad3e1d5cf5b32054d86cbba6e2fef05af3/src/vs/editor/contrib/goToDeclaration/goToDeclarationMouse.ts#L144 and I slightly embarrassed that there are no tests. It's heuristic that does the following: Once the target document is resolved (`textEditorModel`) we try to find "good chunk to preview". It starts at the (start) line of the reference and walks downwards until  it finds a line with the same indentation. That works ok for `foo() {` but not for `foo()\n{`... I think a nicer model would be to look for balanced brackets, e.g. continue until you find the *right* `}`. May a combination of both approaches because often references are to fields/constants and not bracket-blocks (like functions et al). 
Hope I didn't scare you, feel free to ask questions.

**Comment by zeerorg** [comment]
If this issue is open I would like to take this up.
I also looked around the code pointed to by @jrieken and tried to figure what was going on.
As suggested, we can improve this by
1. Differentiating between variables and functions/classes
2. For functions/Classes scanning the lines and using something like a simple stack to figure out where the scope ends.

**Comment by jrieken** [comment]
@zeerorg it is up to @faso who put his stick into the ground first (albeit quite a while back). Still, be aware of us not knowing the semantics of sources. That makes assumptions like 'for a variable do this', 'for a method do that' very hard.

**Comment by jrieken** [comment]
fixed via https://github.com/Microsoft/vscode/pull/52506
