### ISSUE TITLE
Contributed explorer view won't be activated without folder context

### ISSUE THREAD

**Issue by neilsustc** [Microsoft/vscode#39469]
- VSCode Version: v1.18.1
- OS Version: Windows 10

Having a extension contributing a view in explorer

```json
"views": {
    "explorer": [
        {
            "id": "mdOutline",
            "name": "Outline",
            "when": "resourceLangId == markdown"
        }
    ]
}
```

If we directly open a md file (no folder context), the contributed view will never be activated. (Tested on "Markdown All in One" and "LaTeX Workshop")

If we *remove* condition `"when": "resourceLangId == markdown"`, it will work as expected (activating the view).

Related [vscode-markdown#60](https://github.com/neilsustc/vscode-markdown/issues/60)

**Comment by sandy081** [comment]
This is because of how context keys works in different scopes. In short, Side bar views (explorer, scm, extensions, debug) and Editor are in two different scopes. A context key can have different values in different scopes, it means, `resourceLangId` can have different value in Editor and Explorer views. Since custom views are in Explorer they respect the value of `resourceLangId` in the explorer.

My suggestion is do not use `resourceLangId` context key. Instead create your own context key to control the visibility of the view. See the jsonOutline example for how to [define](https://github.com/Microsoft/vscode-extension-samples/blob/master/tree-view-sample/package.json#L29) such views with custom context keys and how to [control](https://github.com/Microsoft/vscode-extension-samples/blob/master/tree-view-sample/src/jsonOutline.ts#L61) the view using context keys

**Comment by neilsustc** [comment]
Thanks
