### ISSUE TITLE
Bold+italic style in markdown is styled as just bold in code view

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#3948]
The last link should also be in italics.

![image](https://cloud.githubusercontent.com/assets/2193314/13660712/64e6799a-e641-11e5-83f0-3c454be23d55.png)

**Comment by bpasero** [comment]
Please reopen if you still see this with our new markdown extension.

**Comment by freebroccolo** [comment]
@Tyriar @bpasero Was this ever fixed? It seems to be broken as of `1.12.2`.

However, instead of only seeing bold for the last line, I'm only seeing italic.

Furthermore, in one of my own extensions that used bold + italic highlighting, it seems only one of those styles will apply at a time. It definitely worked properly sometime last year but it's not working now.

**Comment by Tyriar** [comment]
This has indeed regressed.

![image](https://cloud.githubusercontent.com/assets/2193314/26517024/1548def8-4245-11e7-91dd-714e6eaaafcc.png)

**Comment by freebroccolo** [comment]
Any news on this?

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/vscode-markdown-tm-grammar#3

**Comment by mjbvz** [comment]
New rendering:

<img width="442" alt="screen shot 2018-08-20 at 4 58 17 pm" src="https://user-images.githubusercontent.com/12821956/44348270-425b5200-a49a-11e8-9e17-25e9bb61daad.png">
