### ISSUE TITLE
Current support for data scientists is not enough

### ISSUE THREAD

**Issue by deerainw** [Microsoft/vscode#39492]
- VSCode Version:1.18.1
- OS Version:windows7

I'm a data modeler and I have been using Rstudio,MATLAB and Spyder for years, I've already attempted to use jupyter notebook, but i can't even create a project with notebook, then i started programming in text editor like sublime,Atom and vscode, and finally I was attracted by vscode.

I can open a new window for jupyter qtconsole from the terminal in vscode, but I wish I can use qtconsole in vscode rather than open a new window. Of course I can start original ipython in vscode, but ipython will open a new window for image when I plot function curves.

vscode is a brilliant text editor, and it will be more powerful for data scientists with a qtconsole in vscode.

**Comment by cleidigh** [comment]
@deerainw 
Since QTConsole is based on QT GUI framework, it needs to run in an environment where the window
is controlled by QT and can output the GUI objects.  The integrated terminal in VSC is based on
xterm which is a character based console interface.  I think that the only way to support QT
would require an extension.  Even an extension  probably cannot directly to this since the extensions
need to render HTML content within the interface.

**Comment by kumueric** [comment]
Please look at spyder -- especially its Variable Explorer:
https://pythonhosted.org/spyder/variableexplorer.html
I know we can use VSC's debugger, but you have to run the entire script and you cannot edit.
I know we can set breakpoints in the VSC debugger, but since we can "Run selection/line in integrated terminal," it would be so much more convenient to be able to explore the object(s) in the integrated terminal.

Please also look at RStudio.  "Data people" there are begging them to also support Python:
https://community.rstudio.com/t/r-python-in-ide/279
but I do not think that this will happen to the community's satisfaction soon (through various "workarounds," there currently are some "emulations").  It would be nice for VSC could add a "variable explorer" (especially for pandas DataFrames).  Then for data scientists, it would look a lot more like sypder and/or RStudio.

**Comment by omri374** [comment]
@kumueric . I couldn't agree more. PyCharm has some support for variable explorer and pandas data frames. This is a must for data modeling in Python.

**Comment by MikhailArkhipov** [comment]
Integrated console (with intellisense) and ability to display graphs and tables would be extremely helpful to Python and R users

**Comment by DonJayamanne** [comment]
@MikhailArkhipov the terminal is built using xterm.js, and looks like there's no immediate plan to support this (https://github.com/xtermjs/xterm.js/issues/614#issuecomment-362180939). Hopefully this will change.

**Comment by cfreundlich** [comment]
@omri374 is there any status on a PyCharm-like explorer window for pandas?  Would be great to have a colorful and scrollable DataFrame object.
