### ISSUE TITLE
Omnisharp times out when getting started

### ISSUE THREAD

**Issue by rhires** [Microsoft/vscode#395]
I'm not sure how to view any kind of log besides the basic one that vscode already provides to see what's going on with it, but for whatever reason Omnisharp fails to start because it says that it took too long. I'm happy to provide more detail for this issue, if I can get some direction on where to get the info to provide. :-)

**Comment by jrieken** [comment]
@rhires Can you provide the omnisharp log (Cmd+L,L)

**Comment by rhires** [comment]
[INFO] Starting OmniSharp at '/Users/localuser/Projects/TestProject'...
[INFO] Started OmniSharp from '/Applications/VSCode-darwin-signed/Visual Studio Code.app/Contents/Resources/app/extensions/csharp-o/bin/omnisharp' with process id 62537...
[INFORMATION:OmniSharp.Startup] Omnisharp server running using stdio at location '/Users/localuser/Projects/TestProject' on host 62510.
[INFORMATION:OmniSharp.Dnx.DnxPaths] Using runtime '/Users/localuser/.dnx/runtimes/dnx-mono.1.0.0-rc1-final'.
[INFORMATION:OmniSharp.Dnx.DnxProjectSystem] Scanning '/Users/localuser/Projects/TestProject' for DNX projects
[INFORMATION:OmniSharp.Dnx.DnxProjectSystem] Found project '/Users/localuser/Projects/TestProject/project.json'.
Process ID 62558
Listening on port 64190
Listening on port 64190
[ERROR:OmniSharp.Dnx.DesignTimeHostManager] Failed to launch DesignTimeHost in a timely fashion.
[ERROR] Error: Failed to start OmniSharp

**Comment by DiegoZoracKy** [comment]
@rhires 

I had the same problem but updating to 0.10.3 solved it.

**Comment by rhires** [comment]
Cool. Just got the vscode 0.10.3 update. I thought you meant a separate update for omnisharp. We'll see if I continue having the time out issue. It isn't a consistent thing. Meanwhile: Interesting. I notice that the update date is 11-26-15...and vscode didn't tell me there was an update. Time for a new issue: "VScode "checking for updates" hangs and doesn't check for updates.

**Comment by DiegoZoracKy** [comment]
@rhires I should have mentioned "vscode". And yes, i agree about the new issue. Like it was for you, vscode didn't tell me anything about the update.

**Comment by jrieken** [comment]
@rhires @DiegoZoracKy Do you guys have mono installed or is it just coreclr?

**Comment by rhires** [comment]
Mono here...a fairly up-to-date version, too. I'll have to come back and say which version.

**Comment by wolfspider** [comment]
I have an IMac at my office where everything works perfectly however I also have a Macbook Pro where this problem has been a continual issue. I have tried reinstalling VSCode (I'm on 0.10.3) and even getting OmniSharp from Github and running it purely from there as well which generates the same error. Right now I'm running Mono version 4.2.1 as well. I don't need to start VSCode to see the error just OmniSharp inside VSCode- if that narrows it down at all:

Jesses-MacBook-Pro:WebApplication jessebennett$ dnvm use 1.0.0-beta8 -p
Adding /Users/jessebennett/.dnx/runtimes/dnx-mono.1.0.0-beta8/bin to process PATH
Updating alias 'default' to 'dnx-mono.1.0.0-beta8'
Jesses-MacBook-Pro:WebApplication jessebennett$ "/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/csharp-o/bin/omnisharp"
info    : [OmniSharp.Startup] Omnisharp server running on port '2000' at location '/Users/jessebennett/Documents/vnext/yeoman/WebApplication' on host -1.
info    : [OmniSharp.Dnx.DnxPaths] Using runtime '/Users/jessebennett/.dnx/runtimes/dnx-mono.1.0.0-beta8'.
info    : [OmniSharp.Dnx.DnxProjectSystem] Scanning '/Users/jessebennett/Documents/vnext/yeoman/WebApplication' for DNX projects
info    : [OmniSharp.Dnx.DnxProjectSystem] Found project '/Users/jessebennett/Documents/vnext/yeoman/WebApplication/project.json'.
Process ID 1523
Listening on port 49496
error   : [OmniSharp.Dnx.DesignTimeHostManager] Failed to launch DesignTimeHost in a timely fashion.

In the source code for OmniSharp I see the socket timeout ~30 seconds before generating this error mesage. I've tried reinstalling Mono from the Xamarin website as well as from homebrew. Both the MBP and IMac have the latest stable release of El Capitan. On this same MacBook DNX has always restored and built everything just fine. Kestrel runs, starts, and stops just fine as well. The DesignTimeHost process however seems to get orphaned every time this happens and multiple instances will just get "stuck".

**Comment by rhires** [comment]
Hooray Open Source! So you were digging around in the code...roughly where were you looking? I'm curious if you saw anything about increased logging level or anything like that. Maybe we can turn up the logging level to see what else it might be doing. Or, we could custom build something for ourselves with lots of extra logging to see what's up...or maybe link this issue to the OmniSharp team? See if they can help?

**Comment by wolfspider** [comment]
I was looking at the code in the Omnisharp-Roslyn project inside the file DesignTimeHostManager.cs inside the OmniSharp.Dnx folder. Beginning at line 100 we have this routine:

// Wait a little bit for it to conncet before firing the callback
                using (var socket = new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp))
                {
                    var t1 = DateTime.UtcNow;
                    var dthTimeout = TimeSpan.FromSeconds(30);
                    while (!socket.Connected && DateTime.UtcNow - t1 < dthTimeout)
                    {
                        Thread.Sleep(500);
                        try
                        {
                            socket.Connect(new IPEndPoint(IPAddress.Loopback, port));
                        }
                        catch (SocketException)
                        {
                            // this happens when the DTH isn't listening yet
                        }
                    }

                    if (!socket.Connected)
                    {
                        // reached timeout
                        _logger.LogError("Failed to launch DesignTimeHost in a timely fashion.");
                        return;
                    }
                }

Here is my console output for when I try to run OmniSharp directly from source:

Jesses-MacBook-Pro:omnisharp-roslyn jessebennett$ ./scripts/Omnisharp -s /Users/jessebennett/Documents/vnext/yeoman/WebApplication/ -p 48971
info    : [OmniSharp.Startup] Omnisharp server running on port '48971' at location '/Users/jessebennett/Documents/vnext/yeoman/WebApplication/' on host -1.
info    : [OmniSharp.Dnx.DnxPaths] Using runtime '/Users/jessebennett/.dnx/runtimes/dnx-mono.1.0.0-beta4'.
info    : [OmniSharp.Dnx.DnxProjectSystem] Scanning '/Users/jessebennett/Documents/vnext/yeoman/WebApplication/' for DNX projects
info    : [OmniSharp.Dnx.DnxProjectSystem] Found project '/Users/jessebennett/Documents/vnext/yeoman/WebApplication/project.json'.
info    : [OmniSharp.Dnx.DesignTimeHostManager] Listening on port 49517
error   : [OmniSharp.Dnx.DesignTimeHostManager] Failed to launch DesignTimeHost in a timely fashion.

What you can see here is the issue is replicated on the OmniSharp side and even their script selects the Beta4 runtime correctly but yet we see the same error. The socket is created from a reference in System.Net.Sockets which is pretty low level in the stack compared to the other vnext features. This I suspect may be an issue with Mono creating sockets so it may be a good test to create some code that simply opens a socket in this manner using something like Xamarin studio. If that works (and there is a good possibility that it would) then absolutely it would be OmniSharp but on their issues list they have closed out multiple DesignTimeHost issues indicating that mitigating this involves building OmniSharp from source and getting VSCode to pick it up. Obviously, that didn't work for me and I'll just warn you the monolithic build script which goes into their Test suite has always had problems completing the tests. So what I'm saying is if your try and build it- it takes a little while but you will get a working OmniSharp out of it even if the CSharp tests don't complete 100% just give it a try to see if it did get built. I tried extending the timeout to 100 seconds and rebuilt it but still got the same problem.

**Comment by wolfspider** [comment]
Ok, I managed to get this to work by killing the conditional statement for awaiting the socket connection and binding to 127.0.0.1 instead of using the loopback adapter. I would only suggest this if you don't mind getting your hands a little dirty and *desperate* to get this to work. Also, not really sure why this works so that in itself is problematic- I'll try to do some more testing later to see where this is going wrong. 

Here is a gist of my updated Design Time Host Manager file: https://gist.github.com/wolfspider/79512b40a9dd25035420 

Once you rebuild omnisharp edit your ~/.bash_profile script with an export statement like so to change where VSCode runs omnisharp from:

export OMNISHARP="/Users/jessebennett/Documents/omnisharp-roslyn/scripts/Omnisharp"

After you do that you should see VSCode come up with the modified path in the log for Omnisharp, just like in the attached screenshot I included. 

![dthsocket](https://cloud.githubusercontent.com/assets/4861700/11610832/c550870e-9b7c-11e5-9df3-86dddb5f4d25.png)

**Comment by rhires** [comment]
Hmmm...you're a better coder than I...so basically, explicitly spelling out the loopback works, rather than what should be the constant (string). So maybe that's failing somehow. `socket.connected` thinks it's not connected. I wonder if the Mac OS is returning something in a way that is different than what Windows might return. Totally guessing here.

**Comment by wolfspider** [comment]
@rhires That is definitely possible, nowadays the loop back adapter is a
reference to IPv6 local address. Specifying an IPv4 address like 127.0.0.1
keeps it from binding there. That change alone didn't do it so then I had
to remove the requirement to wait for a socket to be open. There is also
the possibility that the omnisharp build process generates unreliable
results on my MacBook and I just built it so many times that something
finally hooked up right- eventually I did get one passing build but most of
the time it would fail with the "too many files open" error during csharp
tests and I already have the mono filesystemwatcher fix in my bash profile.
The answer is between those two issues somewhere and when I can look at it
again I can help narrow this down.

**Comment by wolfspider** [comment]
@rhires Alright mang, I wrote a simple socket tester with the internals of DTH you can find here:

https://github.com/wolfspider/ConsoleSocketTest

It *does* fail to bind so we can rule out the build weirdness. Here is my console output from this little experiment:

Jesses-MacBook-Pro:ConsoleApplication jessebennett$ cd '/Users/jessebennett/Documents/vnext/yeoman/ConsoleApplication' ; /Users/jessebennett/.dnx/runtimes/dnx-mono.1.0.0-beta8/bin/dnx ConsoleApplication
Port Created at: 49432
Now trying to bind...
Socket not Connected!

I think this may in fact be a Mono problem and not necessarily an OmniSharp issue but don't know enough to say why it works on some computers and not others.

**Comment by jrieken** [comment]
Thanks for the insights guys. First, I'll move this to omnisharp, then we tackle it there. @wolfspider I hear there is two changes (1) IPv4, IPv6 and (2) don't wait. Is that right. Do you want to do a PR against OmniSharp?

**Comment by jrieken** [comment]
This issue was moved to OmniSharp/omnisharp-roslyn#360
