### ISSUE TITLE
Test suggestion improvements

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#39550]
Test for: #22839 and #15419
Complexity: 2

- [x] macOS - @joaomoreno 
- [x] Any OS - @ramya-rao-a 

We have made some tweak to how suggestions are selected. Test that

* the last selected suggestion for a prefix, language, and workspace combination are now remembered and pre-selected
* small typos should be accounted for. So `cno` will also match `console`. The rule is that neighbouring letters will be swapped, the first letter must always match. Make sure this isn't too aggressive

**Comment by joaomoreno** [comment]
> small typos should be accounted for

I love this, I guess I missed the standup demo1

**Comment by ramya-rao-a** [comment]
@jrieken https://github.com/Microsoft/vscode/issues/39518#issuecomment-349455044 is a case where relaxing for typos is counter productive. In this case both `form` and `from` get the same score. Shouldnt the non typo match be scored higher than the one for the typo?

**Repro steps**: Using Insiders, type form in any jsx file. from is preselected instead of form
