### ISSUE TITLE
a question

### ISSUE THREAD

**Issue by YSHIDM** [Microsoft/vscode#39632]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.早期使用的时候，保存文件自动格式化，不满意Ctrl+Z可以回退并保存。现在不行了，不知道是功能被取消了还是我设置错了。(save the file automatically formatted, not satisfied with Ctrl + Z can roll back and save. Now die, I do not know if the feature was canceled, or did I set it wrong.)

Reproduces without extensions: Yes/No

**Comment by isidorn** [comment]
Please follow our rules of submiting bugs https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions

**Comment by ramya-rao-a** [comment]
@YSHIDM I can understand that 
- you saved a file
- saving triggered formatting
- you undid this by Ctrl+Z to roll back and then saved the file

But I dont understand what the issue is.

Try running `code --disable-extension`
This will run VS Code with all extensions disabled.
If you can still see the issue, the re-open this issue with more details
