### ISSUE TITLE
stdin file title should have number not uuid

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#39654]
Refs: #39330
`ps aux | grep code | code-insiders`

Notice the title of the file is `stdin-etxfmee.txt` I guess the second part is an generated UUID. Why not simple use a number `stdin-1.txt`, same as we do with `Untitled-1`.
Also does it have to be a .txt file (just asking)?

**Comment by bpasero** [comment]
I basically copied what sublime does:

![image](https://user-images.githubusercontent.com/900690/33605126-abbd27a8-d9b8-11e7-83ac-2a3130af0f9f.png)

But I should maybe prefix the file with "Code" so that it becomes clear this is for VS Code.

I need the random shizzle at the end because I am creating a temp file and need to ensure it does not exist yet.
