### ISSUE TITLE
Detect folder modification time

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#39652]
Testing #39593

The current cache invalidation detection works great, but the user experience is kind of rough since the user must reload the window.

We could do a little bit better by storing the mtime of the `extensions` folder and render the cache invalid at startup if the cached value differs from the current value. This costs an extra `stat` call on the `extensions` folder, sure, but makes the overall experience a bit better, when manually editing the `extensions` folder, which some people do. That way, most direct modifications to the `extensions` folder wouldn't result in having the user reloading the window.

**Comment by alexandrudima** [comment]
Verification steps:
* open VSCode once
* close VSCode
* make an edit directly on the hard-disk that would cause the mtime of the user extensions folder to change. e.g. delete or move out an extension folder
* start VSCode => no restart popup presented because the cache is dropped as the mtime changed.

> Note: this does not work for edits made inside an extension, as folder mtime does not roll up.
