### ISSUE TITLE
Select box boder changes styles when selected

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#39657]
* set a breakpoint
* edit it
* notice that the outline-style keeps changing from and to rounded corners 

![dec-05-2017 12-06-21](https://user-images.githubusercontent.com/1794099/33604028-d9b54c0c-d9b4-11e7-8e34-e8d1e3ff5302.gif)

**Comment by isidorn** [comment]
This is true for all our SelectBoxes.
The issue here is that the focus is an outline and there is no way to set the radius on the outline to also be rounded.
On the other hand the mac select box nativly is rounded thus it should stay rounded when it does not have focus.

All in all, no good idea how to fix this -> backlog
Might be fixed be a user PR which is currently in review by @bpasero

**Comment by bpasero** [comment]
@isidorn that PR does not change how the dropdown looks like when it is not expanded, it only changes the list view once clicked.

**Comment by isidorn** [comment]
I acknowledge the issue but have no plans of fixing it -> closing
