### ISSUE TITLE
Piped output automatically saved to tmp

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#39655]
Refs: #39330

`ps aux  | code-insiders` 

Notice that this is automatically saved to the /tmp folder, even if the workspace is already open? Why not do the same as with the new untitled file, just keep it in memory and user can chose where to save it?

**Comment by bpasero** [comment]
@isidorn agree that would be a nicer solution but I am doing the file trick as pragmatic solution so that further data that comes in from stdin gets nicely written into the file.

Anything else would require a direct pipe from the one terminal process to the renderer to update the contents of that file. Unlikely to happen.
