### ISSUE TITLE
When reading from stdin, do not implicitly set --wait mode

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#39682]
testing #39330

When piping output from a terminal to code, the command in terminal waits until I close the editor or until i press `Ctrl+C`.

`ps aux | code-insiders`

result: command does not terminate until `ctrl+c` or close the editor (even though it is on disk).

I would expect that the command to terminate immediately.

**Comment by Tyriar** [comment]
I believe this is a limitation of WSL to not run Windows executables as a background task. @bitcrazed any insight?

**Comment by chrisdias** [comment]
just fyi, I was on Mac.

**Comment by Tyriar** [comment]
Oh OK, nevermind @bitcrazed 😄

**Comment by bpasero** [comment]
Currently "as designed". I am setting the --wait because I do not know how much data is coming in via stdin so I simply wait until the editor is closed, because then I know that the user does not care anymore about the data. 

But maybe there is a different solution to this. If anyone wants to look into it, the code is in https://github.com/Microsoft/vscode/blob/master/src/vs/code/node/cli.ts#L110
