### ISSUE TITLE
No autocomplete when typing region keywords

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#39708]
re #39582

Tried to type in `/*#region*/` at the beginning of a CSS file but didn't get any auto-complete.

![region-autocomplete](https://user-images.githubusercontent.com/876920/33621919-285e818e-d9a1-11e7-8856-0d1769179b50.gif)

**Comment by roblourens** [comment]
I see it if I trigger suggestions manually. In other languages I see the popup when I type `#r`. Not sure if I should expect to see it when typing `#`?

**Comment by aeschli** [comment]
Yes, the idea is that you just need to type '#'. Comments are added by the completion proposal.
I just tested that and it seem to work for me
![image](https://user-images.githubusercontent.com/6461412/33652850-2e8b3762-da6b-11e7-888f-4a9b9e5b04fc.png)

Quick suggestions are normally turned off inside comments, so that's expected.
That's controlled by the setting
```
    "editor.quickSuggestions": {
        "other": true,
        "comments": false,
        "strings": false
    }
```
Closing as what you see is the expected behaviour. Please reopen if you disagree.
