### ISSUE TITLE
Open folder should start the folder picker at the current folder

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#3988]
Currently when selecting open folder it always opens the folder picker at `$HOME` on Linux. It would be much more convenient if it started in the current folder, that way I can navigate to a relative project very easily like so:
- <kbd>alt</kbd>+<kbd>&uarr;</kbd>
- (type name of desired project)
- <kbd>enter</kbd>, <kbd>enter</kbd>

**Comment by Tyriar** [comment]
It seems to be starting in the directory above now which is good. I'll reopen if I can reproduce what I think I saw.

**Comment by Tyriar** [comment]
After playing around with this for a while, it's definitely not consistently opening the currently opened folder or it's parent.

**Comment by bpasero** [comment]
@Tyriar we store the last used folder in a setting, can you provide some more steps how this happens? Is the path you picked before maybe getting deleted meanwhile?

**Comment by Tyriar** [comment]
@bpasero the issue is that it seems to retain the last folder used, I think it's more intuitive to consistently open at either the currently opened folder or the parent of that folder.

**Comment by bpasero** [comment]
@Tyriar interesting, though I did not get any bug for this from any other user besides you so maybe the way it works now is actually what all people expect?

Still, you say that often $HOME gets opened even though you did not pick it, I would like to understand when and how that happens.

**Comment by Tyriar** [comment]
@bpasero I'll try make some notes during regular use :)

**Comment by Tyriar** [comment]
Just opened it on Insiders (it's been a long time since I've done it, if ever), and it started the open dialog at `/home` (ie. `~/..`) which is pretty weird.

**Comment by bpasero** [comment]
@Tyriar the first time you open it I am not setting any folder so this might well be standard OS behaviour or an issue with Electron. From then on I am keeping your last used directory.

**Comment by thenoen** [comment]
Hi, I am not sure if my problem is related to this issue but I couldn't find better.

I am using linux with KDE desktop and when I open a file from file manager (like Dolphin) or from console with command "code /home/user/project/file.json" it is opened in vscode but location of explorer is always "/home/user" instead of "/home/user/project". But if I open a file which is not under user home dir (for example "/tmp/file.name" then no folder is opened in vscode explorer. I expect the same behavior in both cases. Either should be location of explorer set to parent folder of opened file or none folder should be opened. There is no difference if I open a file from a file manager of from console.

**Comment by bpasero** [comment]
This should be fine now in 1.18.
