### ISSUE TITLE
Feature Request: setting to disable CSS jump to definition/find references

### ISSUE THREAD

**Issue by rictic** [Microsoft/vscode#39890]
I'm implementing a language service that includes features for jumping to definition / find references with CSS Custom Properties, and I'm finding that the built in CSS languageservice clashes with the results.

e.g. jump to definition will give two results for the same location with slightly different ranges, turning an instant jump into an interaction with a menu.

(Our language service understands HTML Imports, which is very useful for our users, otherwise I'd just turn off our CSS features in our VSCode plugin and defer to the vscode css languageservice.)

**Comment by tempit** [comment]
@rictic - I faced the same problem, and saw no solution in the end but to raise the CSS server on my own and proxy all calls to it (while registering our files to our language, rather than CSS) in addition to providing my result. Then I could fiddle with them as needed (remove unneeded diagnostics, bad definition locations, etc.). 

I'm not sure such a setting should be part of VSCode, and it would have to be for every LSP feature (signature help, rename, etc.) in any case.

If memory serves, when implementing a server you can add configuration options, so IMO the CSS language server should implement that, and this should be an issue in https://github.com/Microsoft/vscode-css-languageservice

**Comment by rictic** [comment]
Starting the CSS server on my own doesn't seem like it solves the issue, as VSCode will be running its own server regardless, so I can only add information, not subtract.

I filed https://github.com/Microsoft/vscode-css-languageservice/issues/55 and was recommended to file here instead.

**Comment by tempit** [comment]
@rictic - You can still solve it on your own, you just have to contribute a language in package.json that registers .css extension as belonging to it, this should override calls to CSS service. 
Then pass all requests to the CSS service you raised on your own, and add your stuff only when it applies. This also lets you fine-tune stuff, like removing only some diagnostics/definitions/etc.

You can take a look at https://github.com/wix/stylable-intelligence/ - that's what I did there, and it works OK. [My extension is .st.css, but I'm pretty sure it works with plain .css as well]

Hope this helps

**Comment by rictic** [comment]
I think what's going on in your case is that you register `.st.css` as the `stylable` language, and in that case any CSS based languages will not activate on those files.

In my plugin I'm supporting just normal css, and inline style tags in html, and I'm still seeing results from the builtin css languageserver.

**Comment by tempit** [comment]
Yup, what I meant was you should be able to register .css to your language, and then it wouldn't send calls to CSS service. You would have to proxy everything, but the only thing you actually lose is the CSS file icon.

**Comment by aeschli** [comment]
@rictic Are the results you get from the CSS language server wrong? Is there something we can improve?

**Comment by tempit** [comment]
@aeschli - for one thing, it always returns a definition, which is almost always the same as the position of the cursor. This leads to 2 definitions instead of 1, and prevents easy Ctrl+Click navigation.
See https://github.com/Microsoft/vscode-css-languageservice/issues/48

**Comment by aeschli** [comment]
Some of the unnecessary results got removed by my fix for Microsoft/vscode-css-languageservice#48.
What's still there is to jump to the own symbol when in the declaration itself. TypeScript does that too, but I can remove that.
But why would that collide with your language server, unless you make the exact same proposals?
It would be better if you only add *additional* proposals, such as definitions in other files, and relay on the built-in css server for the same-file proposals. If these are not good enough, then I'm happy to improve them.

**Comment by tempit** [comment]
Depends on what you mean by 'collide'. 
I don't see the point of returning a definition that is at the same position as the cursor, since this has no discernible effect to the user compared to not returning one at all (AFAICT. Maybe it jumps to start of word?).
But if I have a definition of my own to provide, the fact that there are now 2 definitions means the definition pane opens instead of automatically navigating to the defining file, which is what I want.
For now I suppress the CSS definition completely, in the near future I'll start proxying CSS while filtering definitions whose range includes the calling position.

[As an aside, I have to proxy the CSS server anyway since I 'm also filtering/altering certain diagnostics, etc. E.g. in our syntax, empty rulesets are more commonplace, and should not generate a warning].

**Comment by aeschli** [comment]
- If you have your own *CSS-like* language then the right approach is to give it a new language id and only have your language server registered for it. No proxying should be necessary as your language server can even include the [CSS language service](https://github.com/Microsoft/vscode-css-languageservice) library and pick and choose what capabilities it wants, and what not.
- If you want to extend the language support for *CSS* then the right approach is to
    - help us improve the built-in css server, or provide fixes for built-in proposals that are wrong
    - have a language server that only adds additional proposals to the ones provided by the built-in css language server.

Also note:
- returning a definition that is at the same position as the cursor only happens when on the declaration itself (e.g. `-webkit-app-region: drag;`). If you have additional declaration, you can return these. This should not result in any conflicts.
- empty rulesets can already be ignored in the settings.

**Comment by rictic** [comment]
As of vscode v1.19.0 it looks like the css language server's results have improved. I tweaked the ranges we produce [here](https://github.com/Polymer/polymer-analyzer/pull/802) so that we give ranges just for the name in the declaration, and VSCode is able to deduplicate the definitions itself.

Since our language server understands HTML Imports I think our users are still served by us augmenting the results in this way. Will have to investigate the completions case though, it might make sense for us to redact some of our completions when talking to vscode..
