### ISSUE TITLE
Regions don't appear to work in .vue files

### ISSUE THREAD

**Issue by hecktarzuli** [Microsoft/vscode#39939]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vetur|oct|0.11.3
vue-vscode-snippets|sdr|1.2.0

(1 theme extensions excluded)
---
Steps to Reproduce:

1. Create a .vue file with a <script> tag in it
2. Try to create a region, example: //#region var JoshIsCool = false;//#endregion
3. Notice no folding activates
4. Cry yourself to sleep

Reproduces without extensions: Yes/No

**Comment by octref** [comment]
@mjbvz HTML folding regions seem to be picked up, but JS/TS only pick up some of them (not including `#region` ones.

Wondering if that's because the region markers are dynamically computed and controlled by TypeScript LS? (remember hearing something like this).

![image](https://user-images.githubusercontent.com/4033249/33785675-f6f18692-dc1a-11e7-968d-23eae792ed53.png)

**Comment by mjbvz** [comment]
No. The TS language is not involved in regions, it's just a language configuration we set for JS/TS.  @aeschli would know more about this

**Comment by realtruckjoshdeltener** [comment]
FYI, I'm not using TS

**Comment by erisman20** [comment]
Doesn anyone have a fix for this? Regions do not working the <template></template> section either. Folding works, just not regions.

**Comment by ashishmit14** [comment]
Facing this same problem here. Feel bad for the commented codes.

**Comment by octref** [comment]
Tracking in https://github.com/vuejs/vetur/issues/899.
