### ISSUE TITLE
OpenEditorsView: reduce unnecessary DOM re-creation

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#40039]
- VSCode Version: 1.19-insiders
- OS Version: macOS

Steps to Reproduce:

1. Turn on file auto saving
2. Type

![image](https://user-images.githubusercontent.com/876920/33847303-ec80b3ea-de5e-11e7-8fc9-6a88b0e73a66.png)

@isidorn already optimized the open editors view update and did minimal view update last month, it's already amazingly fast. Since we are on top of ListView, I'm not sure if we can do some basic diff on ListItem and then we can reuse the DOM node if there is only title change or even no change at all.

Above case is a good one, since the auto saving is on, it will always trigger some content change events as the model is dirty-then-saved, the title of the opened editor is not change at all, but we still remove the node from the list, and insert a new DOM node, which is the same as the old one.

**Comment by rebornix** [comment]
Find this while investigating https://github.com/Microsoft/vscode/issues/40038 , the event can be deferred but this is one potential enhancement for our ListView.

**Comment by isidorn** [comment]
We are doing a proper thing in the open editor, only one element changed and we only refresh that one element. The implementation details of the list is that the refresh is actually remove that element and re-add it again.
This will not change in the list and is already fast enough thus closing as will not fix.

The proper fix is that the [onModelChanged](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/common/editor.ts#L741) event is not emitted if nothing changed [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/common/editor/editorStacksModel.ts#L328)

@bpasero feel free to reopen this if you want to fix it in the model

**Comment by bpasero** [comment]
@isidorn I cannot change that event assumption, even though auto save is enabled, the file is still dirty until the file is saved. We just have some tweaks in places that we decide to not draw the dirty marker if auto save is enabled. But that is up to the consumer of that event. 

We might want to revisit this though because I have a related discussion with @rebornix about delaying events to not block typing (see https://github.com/Microsoft/vscode/pull/40041).

I think we should not artificially delay events because consumers are long running. Instead we should try to make consumers fast or if that is not possible batch events and process them after a delay.

**Comment by isidorn** [comment]
Ok makes sense. However currently you already batch an event, so only when the user stops typing I get an event and I refresh the list.

I could potentially cahce on the open editors side and compute the delta and only if something changed actually refresh the list. Though as I think this is already fast enough. @rebornix you could convince me with some numbers :)
