### ISSUE TITLE
I can set a breakpoint in the debug console or output panel

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#40060]
- Open debug console or output panel, put the cursor in
- Press F9

![image](https://user-images.githubusercontent.com/323878/33860473-d22e9e6a-de8d-11e7-97fb-2076f07c232f.png)

**Comment by isidorn** [comment]
This is because you have `"debug.allowBreakpointsEverywhere": true`
I have changed that if the modeId is `log` we never allow breakpoint which will cover the output case. However the repl has no special mode id and thus I can not detect it. Thus for the repl I will not fix this and I do not think this is an issue since of the setting you have.

**Comment by roblourens** [comment]
Oh, right
