### ISSUE TITLE
Use different warning for hidden setting options

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#40070]
For instance, options: 
```json
"editor.scrollbar.verticalScrollbarSize": 30,
"editor.hover": "hidden"
```
will generate 2 warnings: `"Unknown configuration setting"`. But ... it is known and working settings.
 
Wouldn't it be closer to truth showing `"Hidden option"`?

**Comment by sandy081** [comment]
These settings are not registered in configuration registry and hence they are shown as unknowns. @aeschli Is there a way to configure warning per setting?

**Comment by sandy081** [comment]
Since there is a specialised settings UI editor, showing warnings for unknown or unsupported settings would be a noise. Hence they will be shown as hints as follows:

![image](https://user-images.githubusercontent.com/10746682/61665133-91c28780-acd4-11e9-9e80-d945c313d5eb.png)

![image](https://user-images.githubusercontent.com/10746682/61665160-9d15b300-acd4-11e9-8b12-231e03709c7f.png)

There are no plans to show specialised message for hidden settings.
