### ISSUE TITLE
TypeScript: Unreachable code is a warning in Code, but an error in build

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#40111]
![image](https://user-images.githubusercontent.com/22350/33892855-342c13a0-df5a-11e7-939c-85e19ff97dec.png)

That squiggle on line 156 should be an error, just as it is in the build. It appears as a warning, instead.

**Comment by alexandrudima** [comment]
The same is true for unused imports

**Comment by mjbvz** [comment]
Yes, this is by design. See #37616

I've added a section on this to the release notes and will update the documentation as well

**Comment by joaomoreno** [comment]
@egamma How can we fix this? If these are errors in the build, they should be in the language service too.

**Comment by egamma** [comment]
@joaomoreno the background is that TS reports lint/style checks like 'unused variables' as errors. TS does not support to configure the severities of errors. 

We wanted to preserve the existing behaviour we had with tslint when the 'unused rules' worked. For this reason we tolerate the difference between the language service and the compiler. To me this can be justified, since the language service is used as you work on code and it gives you feedback as you type. Build is used once I'm done working on my code. 

There is the setting `typescript.reportStyleChecksAsWarnings` that allows to turn this off.

There is a setting

**Comment by joaomoreno** [comment]
I suggest to set `"typescript.reportStyleChecksAsWarnings": false` in our workspace settings, then.
