### ISSUE TITLE
VS Code opening thousands of instances of git.exe

### ISSUE THREAD

**Issue by jtleaming** [Microsoft/vscode#40121]
- VSCode Version: 1.18.1
- OS Version:Windows 10 10.0.15.063 Build 15063

Steps to Reproduce:

1.Open VS Code
2.Notice thousands of git.exe processes start to run. And continue to run, even after killing them.

Reproduces without extensions: Yes/No
No

**Comment by jtleaming** [comment]
So I think I found a resolution for this problem. VS Code kept trying to run `git --version` but for whatever reason git in my path was not working. So, it kept trying to run `git --version` over and over and over again. Changing git in my path fixed the problem, but it's still not clear why even after failure `git-version` was running again.

**Comment by joaomoreno** [comment]
> Reproduces without extensions: Yes/No
> No

Can you reproduce this issue with `code --disable-extensions`?

**Comment by Cartman16** [comment]
I am not sure but I think I got the same issue since updating to VS Code 1.19
If my repo is on a network share VS Code opens git session over session. If I clone the same repo into a local folder everything seems to be fine.

VS Code About:

Version 1.19.0
Commit 816be6780ca8bd0ab80314e11478c48c70d09383
Date 2017-12-14T12:06:43.492Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

OS: Windows 10 Version 1709, Build 16299.125

![image](https://user-images.githubusercontent.com/6966710/34080109-44e7e150-e339-11e7-9677-dc05a4bc5ffe.png)

**Comment by joaomoreno** [comment]
@jtleaming Can you reproduce this issue with `code --disable-extensions`? If you can't, what's the extension which causes the issue?

@Cartman16 #40249
