### ISSUE TITLE
Out-of-bounds link in JS's template literal

### ISSUE THREAD

**Issue by blucell** [Microsoft/vscode#40152]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:23:26.125Z)
- OS Version: Darwin x64 17.2.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.22
better-toml|bun|0.3.1
vscode-eslint|dba|1.4.3
tslint|eg2|1.0.24
Go|luk|0.6.69
vscode-elixir|mjm|1.1.0
python|ms-|0.8.0
debugger-for-chrome|msj|3.5.0
rust|rus|0.3.2
elm|sbr|0.15.1

---

Steps to Reproduce:

1. Open a new JavaScript file
2. Enter a string literal that has a URL, with a placeholder next to it, without a space in between:
```javascript
`http://example.com/${5 + 1}`
```
3. Ctrl-click the link, and a part of the placeholder is sent to the browser, too.

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
@alexandrudima Not sure what we can do about this. Seems like a generic limitation of the link detector. Only checking within a token for a link would fix this case but I'm not sure that is practical. Any thoughts?

**Comment by blucell** [comment]
Not sure. Can the link detector have a context that tells if it is inside a template or so, and changes its limits depending on that? I am not fully aware of the internals of VS Code, but I believe if it was so much work for a little benefit, a WONTFIX is the way to go.

**Comment by alexandrudima** [comment]
The built-in (language agnostic) link detector will look for `http:`, `https:` or `file:` links. By working in all languages, it is, by definition, programming language agnostic. The main purpose of the link detector is that you can paste in links to stack overflow or whatnot in comments and you can easily go there from the editor.

IMHO, the purpose of a link detector is not to evaluate expressions in the programming language, determining that `5 + 1` is `6` and then interpolate `6` to produce the link `http://example.com/6`. I would argue this issue is out-of-scope.

**Comment by blucell** [comment]
Yes, it should not do, because 1) it is not the expected behavior and 2) most of the time, the evaluation will require runtime variables to be evaluated which is mostly non-practical.

Maybe I have given a bad example. The problem is at that example, the part `http://example.com/${5` is considered a link, while a saner option is to limit it to `http://example.com/` or even disable link parsing there completely.

**Comment by mjbvz** [comment]
I think disabling link detection in template strings entirely may be a little heavy handed. The other option I see would be limiting link detection to the contents of a single token, but that may cause regression in other cases

Since the problem is relatively minor and seemingly not easy to fix, I'm going to closing this issue as out of scope
