### ISSUE TITLE
Can't break anymore on any breakpoint when debugging with nodemon

### ISSUE THREAD

**Issue by TitaneBoy** [Microsoft/vscode#40182]
Hi. I don't know since when exactly, but I can't break on any breakpoint when debugging with nodemon.

But I can break in my code when debugging without nodemon

- VSCode Version:1.18.1
- OS Version:Windows 10
- NodeJS Version: v8.4.0
- Nodemon version: 1.12.7

Steps to Reproduce:

1. Put a breakpoint on the first entry file (example: server.ts)
2. Add configuration to debug with nodemon
3. Run it.

It will never hit any breakpoints in the code

Thank you for your help

**Comment by TitaneBoy** [comment]
Here is the output trace when using "trace: true" option in my nodemon launch configuration (launch.json)
[vscode-node-debug2.txt](https://github.com/Microsoft/vscode/files/1557422/vscode-node-debug2.txt)

**Comment by auchenberg** [comment]
Try to use the `--inspect-brk=5858` runtime arg, which will pause Node on the first line, and allow VS Code to set a breakpoint before the code executes.

```
      "runtimeArgs": [
        "--inspect-brk=5858"
      ]
```

**Comment by TitaneBoy** [comment]
@auchenberg Thank you for the tip...It looks to work for me but it has a little different behaviour than what you've described: using --inspect-brk will not pause Node on the first line...But it will break at the first breakpoint it reaches.. So "--inspect-brk=" works like it is supposed to work with "--inspect=" only..

**Comment by roblourens** [comment]
`--inspect-brk` is the right flag to use - vscode will attach, set breakpoints, then continue automatically. So the behavior you see is expected.

**Comment by TitaneBoy** [comment]
@roblourens Do you know why it worked before with "--inspect" and now not ? Because few days ago, I didn't have to use --inspect-brk and all worked well as usual.

**Comment by auchenberg** [comment]
@TitaneBoy Using `inspect-brk` will start your Node process and pause on the first line as per described in the Node docs, https://nodejs.org/api/debugger.html

The reason for why you might see a difference could be caused by a difference in where your breakpoint is set in your code? If the breakpoint is set in Code that runs after the initial launch, then VS Code is able to set the breakpoint in time. If a part of the initial execution we need to pause Node as per @roblourens described in https://github.com/Microsoft/vscode/issues/40182#issuecomment-351818541
