### ISSUE TITLE
Cannot customize keybindings in peek view (referencesWidget)

### ISSUE THREAD

**Issue by dsifford** [Microsoft/vscode#40387]
- VSCode Version: 1.19.0
- OS Version: `Linux archlinux 4.14.5-1-ARCH #1 SMP PREEMPT Sun Dec 10 14:50:30 UTC 2017 x86_64 GNU/Linux`

To my knowledge and after toying around for the last 30 mins or so, it seems like it is not currently possible to adjust keybindings for the "ReferenceSearch" widget. Specifically, I'd like to navigate up and down in the tree using `ctrl+k` and `ctrl+j`, respectively.

I attempted setting `ctrl+j` to match every instance of "down" currently set in the default keybindings to no avail. 

After failing there, I looked in the source code and it appears that the event is bound to the keycode of the down key, so it looks like it's currently not possible to adjust.

https://github.com/Microsoft/vscode/blob/5bd5e07cd56d98db502411fb27fba76f2d74aa20/src/vs/editor/contrib/referenceSearch/referencesWidget.ts#L302-L306

Did I miss something? If not, would this be something that could be added?

**Comment by jrieken** [comment]
@bpasero did you add support for this in all trees?

**Comment by bpasero** [comment]
@jrieken not yet. in order to get this, the `referencesWidget` needs to use the `WorkbenchTree` and get rid of all the keybinding handling from the Controller ([here](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/referenceSearch/referencesWidget.ts#L264)) and instead leverage the focus and selection listeners for dealing with click events.

I found the controller quite complicated for the references widget and was not sure how to do all the special handling, maybe you want to take a look (added you to https://github.com/Microsoft/vscode/issues/21692).

An example of `WorkbenchTree` is in the [explorer](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/electron-browser/views/explorerView.ts#L414).
