### ISSUE TITLE
Lines with changed indentation are not highlighted

### ISSUE THREAD

**Issue by chimit** [Microsoft/vscode#40411]
- VSCode Version: 1.19.0 (1.19.0)
- OS Version: macOS High Sierra 10.13.2

Steps to Reproduce:

1. Change indentation
2. Save file

Reproduces without extensions: Yes

![2017-12-18 11 32 16](https://user-images.githubusercontent.com/839349/34088911-6e8e844c-e3e7-11e7-9ba7-2023886df135.png)
![2017-12-18 11 32 36](https://user-images.githubusercontent.com/839349/34088910-6e684f98-e3e7-11e7-8798-95ac17e0820f.png)

Line №7 was changed, but is not highlighted. While in the file explorer the files with changed indentation only are highlighted as changed.

**Comment by alexandrudima** [comment]
The call to `computeDirtyDiff` could use the setting `diffEditor.ignoreTrimWhitespace` instead of hard-coding it to `true` [here](https://github.com/Microsoft/vscode/blob/bcc46316b497d1a316dd47ae86481df3ca5784ee/src/vs/workbench/parts/scm/electron-browser/dirtydiffDecorator.ts#L930). @joaomoreno any objections?

**Comment by joaomoreno** [comment]
That's a good idea. I can take this.
