### ISSUE TITLE
Workbench doesn't finish loading when Extensions viewlet is first to load

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#40425]
Windows

1. In Dev, have no extensions in the extensions folder
2. Open the Extensions viewlet
3. Close Code
4. Open it again `.\scripts\code`

![kapture 2017-12-18 at 10 42 30](https://user-images.githubusercontent.com/22350/34099595-38114668-e3e0-11e7-843d-f9e436c4d9be.gif)

**Comment by bpasero** [comment]
Weird, I cannot reproduce :-/

**Comment by bpasero** [comment]
@sandy081 any chance some call on the restore of the extensions viewlet waits on the extension service to be ready?

**Comment by sandy081** [comment]
@bpasero Extensions viewlet has no dependency on extensions ready promise.

**Comment by bpasero** [comment]
I can reproduce, but only on Windows and only when running out of dev.

**Comment by sandy081** [comment]
But, I think the [ViewsViewlet](https://github.com/microsoft/vscode/blob/master/src/vs/workbench/browser/parts/views/viewsViewlet.ts#L299) uses extensions ready promise.. but it is not a blocking one though

**Comment by bpasero** [comment]
@sandy081 it looks like the call to [`this.extensionManagementService.getInstalled`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/extensions/electron-browser/extensionsViewlet.ts#L231) is deadlocking:

![image](https://user-images.githubusercontent.com/900690/34115532-37bd248a-e416-11e7-865f-99c0d5ec5ef1.png)

@alexandrudima could this be a regression from your changes to cache the contents?

Btw this is not reproducible all the time, when I break before this call and then jump over it does not reproduce. So maybe something that spawns in the back has a chance to then come up because of debugging.

**Comment by sandy081** [comment]
@bpasero 👍

**Comment by alexandrudima** [comment]
@bpasero I don't believe so. The caching I implemented is not in the `IExtensionManagementService` (service managing extensions). I implemented caching in `IExtensionService` (service running extensions).

**Comment by sandy081** [comment]
Right. Getting installed extensions from extension management service is not using any caching. It just reads folders from the disk. 

I will try to reproduce it in Windows and investigate.

**Comment by bpasero** [comment]
@alexandrudima @joaomoreno this is a regression from https://github.com/Microsoft/vscode/commit/b71255501de5b4c8a890abf7f6579ac1394c5d8e

The extension viewlet create method needs the shared process and probably at that time the shared process is not ready, but I am not sure why that would not eventually resolve itself for good.

**Comment by alexandrudima** [comment]
Thank you @bpasero for tracking it down.

@joaomoreno Help! This timeout is causing so much grief! And I'm not sure it is 100% working. I think I've seen the process start after 3s, not after 5s.

**Comment by alexandrudima** [comment]
Ok. I am reverting the timeout.

**Comment by alexandrudima** [comment]
Reverted via 4e3205ff36e09eeeb0ef9968679e8f4b1d6f1ba7

**Comment by alexandrudima** [comment]
Opened #40505 to track that we delay the start-up of the shared process.

**Comment by bpasero** [comment]
@alexandrudima thanks. I thought about stable but actually this will never be executed in stable because only when running out of sources we actually restore the last used viewlet. For stable and insiders when you start fresh we always open the explorer viewlet. The only time we actually open the extension viewlet is when you reload the window, but then chances are high that the shared process has started already. I think it is unlikely to hit this unless maybe you manage to start Code, open extensions viewlet and reload the window, all under 3-5 seconds.
