### ISSUE TITLE
[Regression] Debugging of typescript node apps has been broken

### ISSUE THREAD

**Issue by Deilan** [Microsoft/vscode#40430]
- **VSCode Version**:
_Code 1.19.0 (816be6780ca8bd0ab80314e11478c48c70d09383, 2017-12-14T12:06:43.492Z)_
_Code - Insiders 1.20.0-insider (08ec16001adaab8a86183431f6aec09209caa4ab, 2017-12-
15T05:15:38.886Z)_
- **OS Version**: _Windows_NT x64 10.0.16299_
- **Extensions**: _none_
---

Debugging works fine in _Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)_. Have to revert to it until the bug is fixed.

**Steps to Reproduce**:
1. clone `https://github.com/deilan/node-typescript-vscode`
2. `npm install` or `yarn install`
3. Launch `Launch via nodemon` debugging configuration

**Result**:
The process has been started, debugger couldn't start with the following error message:

> Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:35247).

**Comment by weinand** [comment]
Your launch config is wrong (and it was only working in previous versions of VS Code because of bug #16173).
The problem is that you are passing **all** arguments via the "runtimeArgs" attribute. This makes it difficult for VS Code to insert the "--inspect-brk" argument it the right location.

Instead you should only pass nodemon arguments via "runtimeArgs", then use the "program" attribute for your "real" program and then the "real" arguments through the "args" attribute. E.g.:
```
{
    "name": "Launch via nodemon",
    "type": "node",
    "request": "launch",
    "protocol": "inspector",
    "cwd": "${workspaceRoot}",
    "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/nodemon",
    "runtimeArgs": [
        "--exitcrash",
        "--config", "${workspaceRoot}/nodemon.json",
        "--exec", "${workspaceRoot}/node_modules/.bin/ts-node",
    ],
    "program": "${workspaceRoot}/src/index.ts",
    "args": [
        "--project", "${workspaceRoot}/tsconfig.development.json"
    ],
    "restart": true,
    "console": "integratedTerminal",
    "internalConsoleOptions": "openOnSessionStart",
    "skipFiles": [
        "node_modules/**",
        "<node_internals>/**"
    ]
},
```

**Comment by Deilan** [comment]
@weinand Thanks for the explanation. I've tried the suggested debug configuration and I've got the following error message on both 1.18.1 and 1.20.0:

> Cannot launch program 'c:\Dev\node-typescript-vscode\src\index.ts' because corresponding JavaScript cannot be found.

There's no `outFiles` and as far as I understand specifying them doesn't make sense. Of course if I specify `outFiles` as an empty array I get:

> Cannot launch program 'c:\Dev\node-typescript-vscode\src\index.ts' because corresponding JavaScript cannot be found.

**Comment by weinand** [comment]
You do not seem to have an explicit build task that transpiles TS to JS. 
The `ts-node` seems to be the tool that transpiles.
That means VS Code cannot really know where the generated JS lives.
But since `ts-node` takes care of it, VS Code does not really has to know.

Remove the "program" attribute and insert the "${workspaceRoot}/src/index.ts" as the first argument of the "args" attribute just before "--project".

**Comment by Deilan** [comment]
Yep, that worked. Thanks @weinand!
