### ISSUE TITLE
Error: Extension host terminated unexpectedly

### ISSUE THREAD

**Issue by Priyank1504** [Microsoft/vscode#40449]
- VSCode Version: Code 1.19.0 (816be6780ca8bd0ab80314e11478c48c70d09383, 2017-12-14T12:06:44.860Z)
- OS Version: Windows_NT ia32 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-generate-getter-setter|DSK|0.4.2
Angular2|joh|2.11.2
Go|luk|0.6.69
typescript-hero|rbb|1.8.0
ts-import-assistance|Sam|0.0.10
cordova-tools|vsm|1.3.1

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by weinand** [comment]
Please share more details as instructed in our wiki on [Performance Issues](https://github.com/Microsoft/vscode/wiki/Performance-Issues) and [Native Crash Issues](https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues)

- Can you repro this when running `code --disable-extensions`
- If not, then one of the extensions you have installed is the root cause, please log an issue against the repo of such extension.
- Do you see any perf issues just before crashing? If so, then follow the wiki linked above and share more details

**Comment by weinand** [comment]
Disable extension "typescript-hero". If problem disappears then it is most likely this bug:
https://github.com/buehler/typescript-hero/issues/363

**Comment by dougrday** [comment]
Having the same issue.  Steps to repro:

1.  Open .tsx file
2.  Perform any TypeScript Hero command, e.g. Sort imports (Ctrl+Alt+O)

Extensions:

Beautify 1.1.1
EditorConfig for VS Code 0.11.1
npm 0.3.3
npm Intellisense 1.3.0
TSLint 1.0.24
TypeScript Hero 1.8.0
Visual Studio Team Services 1.122.0

Confirmed to no longer occur when TypeScript Hero is removed.

**Comment by weinand** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please refer to our guidelines for filing issues. Thank you for your contributions.
