### ISSUE TITLE
Debug console shows even if externalConsole is true in 0.10.10

### ISSUE THREAD

**Issue by codyrigney92** [Microsoft/vscode#4045]
In my `launch.json` of my node.js project, I have `"externalConsole": true` and so it correctly opens in a new command window.  But in 0.10.10 now the embedded debug console also opens, with nothing output to it.  The expected behavior is that it shouldn't be shown at all.

**Comment by weinand** [comment]
@codyrigney92 the internal debug console is not only a console but a REPL too. This does not change if you enable the external console: the internal console is still used as the REPL. So having it open still makes sense.
But I agree, that there are situations where you do not want to see the internal debug console at all.
(BTW, this behavior hasn't changed in 0.10.10, it was always like that.)

@isidorn maybe we should consider to introduce a setting for this.

**Comment by codyrigney92** [comment]
@weinand I see.  Makes sense.  Yes I think a setting for that would be useful.

**Comment by isidorn** [comment]
@weinand I would introduce a setting if more users ask for it

**Comment by Spown** [comment]
how about making it consistent with task's ``"showOutput"`` setting? ``"always"/"never"/"silent"`` but ``"DEBUG"/"REPL"/"ALL"/"NONE"`` for ``"externalConsole"``? IDK how backward compatible it would be however. Depends on weather ``"externalConsole"`` expects strictly Boolean or just ``!=false``. But anyway I find it also annoyng that if I'm asking for external console I still get internal also.

**Comment by isidorn** [comment]
Not sure about that, I am more leaning towards making it a user / workspace setting, and not a part of `launch.json`. VSCode does not interpreet the values in `launch.json` they are always passed to the debugger which lives outisde of vscode, and hiding the console is very vscode specific behavior.

**Comment by Spown** [comment]
anyway I think I speak for everyone who sets ``"externalConsole"`` to true that unless there is something to output the internal console should remain hidden. Because (externalConsole===true) == (internalConsole===false).

I use externalConsole to maximize my editing area. It's also one of the most defining features of VSC - the interface isn't littered with all sorts of palettes, miniwindows, panels, popus, dialogs and such like in the major IDE's - only the essentials. So when an empty console view pops up when I explicitly said I want an external one - I kinda get the feeling I'm again using eclipse or MVS.

So maybe before (if at all) a new setting is added we can get a hotfix for internal console appearing only after a line was actually output (in case of ``externalConsole===true``)?

**Comment by isidorn** [comment]
I like the points you are making. I will address this issue for our april release, that is I will look into it next week.

**Comment by isidorn** [comment]
For april we changed a bit when we show the internal console, we only show it on the very first debug launch, not on every. So it is less spammy.
We would like to get feedback on that behavior and then in may we willin troduce a setting or try another heurstic, thus moving this to may

**Comment by codyrigney92** [comment]
@isidorn That sounds like good behavior.  I'll be happy to provide feedback.

**Comment by isidorn** [comment]
We have now introduced an option in the `launch.json` to control this behavior

`internalConsoleOptions` which can have the following three values 'neverOpen', 'openOnSessionStart', 'openOnFirstSessionStart'

**Comment by codyrigney92** [comment]
@isidorn Awesome thank you!

**Comment by Spown** [comment]
thnaks!

I assume it would still open with ``neverOpen`` if I init something session unrelated like a task?

**Comment by isidorn** [comment]
Yes if you start a task that has output the output panel will get opened. 
But the debug console in that case would never get automatically opened.
