### ISSUE TITLE
Support virtual folder/file entries in the file view which are managed by extensions

### ISSUE THREAD

**Issue by WebFreak001** [Microsoft/vscode#4047]
When making an extension for some package manager it would be nice if there was an API for managing custom folders in the file view in the sidebar.

For example nodejs tools for visual studio is also having a dependency view in the project explorer:
![https://i.imgur.com/bGMLm19.png](https://i.imgur.com/bGMLm19.png)

I basically want to replicate that in vscode but there are no APIs for adding entries into the file view. So having some API allowing to manage some custom node or an extra region would be nice

**Comment by asfernandes** [comment]
I'd want to create an extension that opens "files" that are actually stored modules from a database, not actual files. Is this currently possible, or will it be possible with this feature request?

**Comment by vladdu** [comment]
This kind of virtual filesystem view would be very useful in order to allow browsing a project's dependencies and libraries. These could be located in different places on disk or in archives or databases. 

Part of the reason for people wanting the most commented issue (#396: multiple projects in a window)  would be covered by this, without any issues related to git and the like, because these library files are read-only.

**Comment by WebFreak001** [comment]
Possible as of 1.13
https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributesviews
https://code.visualstudio.com/docs/extensionAPI/vscode-api#_TreeDataProvider

**Comment by Thaina** [comment]
I cannot get vscode 1.13 from npm. It said `Detected VS Code engine version: ^1.12.0`. Which has nothing about TreeDataProvider
