### ISSUE TITLE
Adding remove / edit expression button when hovering over watch expressions when debugging

### ISSUE THREAD

**Issue by LeonardAB** [Microsoft/vscode#40477]
- VSCode Version: 1.19.0
- OS Version: Win7 Pro 64bit

![remove_edit_button](https://user-images.githubusercontent.com/14308605/34138203-b9c12986-e4b1-11e7-8f32-16f8109ed665.jpg)

Steps to Reproduce:

1. debug something
2. add some expressions to the watch list
3. hover the cursor over those expressions 

Whenever I want to edit or remove an expression, I need to do at least to steps, i.e.

- to remove:  right click then click 'remove expression', or left click then press <kbd>DEL</kbd>
- to edit: right click then click 'edit expression', or left click then press <kbd>F2</kbd>, or double left click

what about showing buttons on the right of the expression (as marked by the red circle above) whenever the cursor is hovering the expression.  (maybe "copy value" button as well)

thanks.

**Comment by isidorn** [comment]
I believe we had something similar to that in the breakpoints view and maybe before in the watch expressions. However we have removed it since you can also easily delete watch expressions as you said and by selecting and pressing the 'DELETE' key.
The downside of having actions there is that they add cluter to an already cluttered view.

I can leave this open as a feature request however I am not convinced this should be added.
