### ISSUE TITLE
Missing icons in activity bar

### ISSUE THREAD

**Issue by diegoquintanav** [Microsoft/vscode#40531]
- VSCode Version: Code 1.19.0 (816be6780ca8bd0ab80314e11478c48c70d09383, 2017-12-14T09:56:48.842Z)
- OS Version: Linux x64 4.10.0-42-generic
- Extensions: 

Icons in the left ribbon are buggy, either not showing or tilting. I can access a feature using keyboard shortcuts i.e. ctrl+shift+g, and the last icon is replaced every time. As for now I have only two icons.

![image](https://user-images.githubusercontent.com/16281387/34173029-cc434ece-e4d2-11e7-8fef-82d9bb245416.png)

Extension|Author (truncated)|Version
---|---|---
vscode-pandoc|Dou|0.0.8
solidity|Jua|0.0.31
code-settings-sync|Sha|2.8.7
html-snippets|abu|0.1.0
yaml|ada|0.0.9
vscode-database|baj|1.2.0
githistory|don|0.2.3
pgsql|dou|0.0.8
vscode-html-css|ecm|0.1.8
vscode-pyvmmonitor|fab|0.0.3
badges|idl|1.0.8
vscode-todo-parser|min|1.9.1
python|ms-|0.9.0
cpptools|ms-|0.14.5
LiveServer|rit|3.0.2
preview-vscode|sea|1.4.2
sonarqube-inject|sil|1.3.1
vscode-todo-highlight|way|0.5.11
debug|web|0.21.2
markdown-all-in-one|yzh|0.11.2

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Open vscode from terminal, using `code .` from my code folder.
2. See only two icons (or three, never all of them) in the left ribbon

Reproduces without extensions: Yes

**Comment by APlowman** [comment]
I am also experiencing this after updating to Version 1.19.0. The search icon is the only persistent icon for me. I can use a keyboard shortcut to show another icon below the search icon, but it disappears after clicking on the search icon. I'm not sure, but this may have happened after I tried out Zen mode.

**Comment by bpasero** [comment]
@isidorn I wonder if something is broken in 1.19, this is the second time I hear that people lost the icons in the activity bar?

**Comment by isidorn** [comment]
@bpasero we did the big refactoring of the composite bar with the 1.18 release. So it should not be connected with that
@diegoquintanav @APlowman what context menu do you get if you right click on the activity bar (the left ribbon)?
What happens if you reload the window?
What happens if you resize the window vertically such that it no longer has enough space and then you resize it again to have a lot of space?
What happens if you hid / show the activity bar using the view menu?

Thanks

**Comment by qin-nz** [comment]
@isidorn 
- Reload window/ restart code / reboot my VM does NO effect.
-  resize the window vertically has NO effect.
- using view menu can show the icon.

Right click can fix this problem.
![image](https://user-images.githubusercontent.com/6998071/34203774-40a5fcbe-e5b7-11e7-9478-293843d9672f.png)

**Comment by bpasero** [comment]
@qin-nz do you remember that you used this menu before to remove a view from the side bar?

**Comment by qin-nz** [comment]
I think I never see this menu before.

**Comment by APlowman** [comment]
@isidorn @bpasero Right-clicking on the activity bar and adding the icons back in has fixed it for me too. I have never used that context menu before.

**Comment by isidorn** [comment]
Ok so the workaround is to show those viewlet again just use the context menu -> thus I think this is not critical candidate.
As for the issue I can only speculate why it is happening. We are now smareter as when we do the layout, so maybe we were lucky that this was not happening before due to some unneded additional layouting.

@APlowman @diegoquintanav @qin-nz if you can still reproduce this, can you F1 > developer tools> and put a brekapoint [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/parts/compositebar/compositeBar.ts#L71) and check what are the `pinnedComposites` and and what are the `options.composites`. Make sure to have the bottom panel closed while you are debugging, to not hit the wrong `compositeBar`

**Comment by diegoquintanav** [comment]
@isidorn Resizing, hiding and showing the activity bar does nothing. However, the context menu after right clicking the on the bar lets me add stuff the same way @qin-nz shows. This kind of solves it.

**Comment by APlowman** [comment]
@isidorn The problem has surfaced again. I'm happy to try to help you but I'm not very experienced with this sort of thing. What do I do after opening developer tools?

I've tried to isolate the issue a bit more. First I open a new window in Code and use the activity bar context menu to select just two icons, A and B, where A appears above B (e.g. Explorer and Search). In this state, clicking between the two icons works fine, nothing disappears. Next, I remove icon B (A) again using the right-click context menu. Next, I add the icon B (A) back in with either a keyboard shortcut or via the View menu. Now there is a problem, because clicking on icon A (B) causes icon B (A) to disappear!

**Comment by isidorn** [comment]
Thanks for more details.
If somebody who sees this issue wants to do a live skype debugging session with me would be great. Just mail me at inikolic at microsoft com

**Comment by bpasero** [comment]
@isidorn is there any place where you write to storage service maybe too early when not all viewlets are there and then we loose some?

**Comment by isidorn** [comment]
@bpasero no, just checked and I only write to `storageService` on [shutdown](https://github.com/Microsoft/vscode/blob/isidorn/explorerCommands/src/vs/workbench/browser/parts/activitybar/activitybarPart.ts#L221).

**Comment by diegoquintanav** [comment]
@isidorn I could get in skype today, I'm sending you an invite.

**Comment by isidorn** [comment]
@diegoquintanav I have pinged you on Skype from my personal account.

**Comment by bpasero** [comment]
@APlowman what you describe in https://github.com/Microsoft/vscode/issues/40531#issuecomment-353063778 is actually expected behaviour: as long as you are not explicitly "pinning" back a view to the side bar it will disappear once another view opens. We still show it if you make the view visible but it is not permanently added back to the side bar.

What still puzzles me is how you get into this state in the first place without ever using this context menu to remove an item.

**Comment by APlowman** [comment]
@bpasero Ah, OK. That makes sense then. In that case, since reinstating the icons with the context menu, there is no longer any problem for me.

**Comment by bpasero** [comment]
Still not sure how to reproduce but it looks like there is a chance that [`updateCompositeSwitcher`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/parts/compositebar/compositeBar.ts#L208) modifies `this.pinnedComposites` which later on would be stored permanently. 

The fix is to make sure a copy of that array is used in layout calls. If we decide to do a 1.19.2 we should probably include this one depending on how many users hit it.

**Comment by joaomoreno** [comment]
@bpasero @kieferrm @egamma I've cherry picked this fix to `release/1.19`

**Comment by bpasero** [comment]
@joaomoreno thanks!

**Comment by isidorn** [comment]
Adding verified label after code review (since I can not reproduce the original issue).
