### ISSUE TITLE
Editing large files - not work to replace all

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode#40580]
- VSCode Version: 1.19.0
- OS Version: Windows 10 Pro

The function does not work to replace all substrings in lines in a file with 2 million lines (2 million occurrences)

Reproduces without extensions: Yes

**Comment by Chuckame** [comment]
Still not working...

**Comment by FredVPCrazy** [comment]
Use notepad ++ for that

**Comment by wonkoRT** [comment]
> Use notepad ++ for that

I came here from https://github.com/microsoft/vscode/issues/52813 which is about find and replace in files, but since it's marked as a dup of this issue here i guess this is the right place to mention that

Notepad++ doesn't allow to exclude directories with patterns, and the "mark to be excluded directories as hidden"-workaround is not really an option in many cases.

If the 20k limit is because of some editor buffer the former might not be a 100% dup but i don't really understand why search and replace needs an editor at all. Is it to enable undo like in VS?

**Comment by FrenchMajesty** [comment]
@FredVPCrazy You know, that's a great idea! Let me just go and download Notepad++ for my Mac. Oh, wait... (sarcasm)
In any case, Notepad++ is not available on Mac so that's not a viable option. Do you know of another text editor that would allow us to perform this operation?

**Comment by sdoigmm** [comment]
@rebornix, what is the maximum amount of lines supported by VS Code?

**Comment by alessiot89** [comment]
bump, this thing is still an issue.

**Comment by ccruttjr** [comment]
bump

**Comment by Lana-chan** [comment]
still happens in 1.87.0

**Comment by Warface** [comment]
Fix this!!!! We have super computers that can handle this easily.

**Comment by b14r** [comment]
FOR THE LOVE OF GOD

**Comment by ccruttjr** [comment]
@rebornix you should think about moving this back into scope

**Comment by Seneral** [comment]
Just make it a warning with an option to proceed anyway, or allow a configurable limit
A tool that refuses to do what it is capable of (even if it's suboptimal) is ridiculous
Don't just take that option away from users - that's basic UX

**Comment by Ecommerce-Manager** [comment]
This is still a problem

**Comment by ibnahzab** [comment]
It is embarrassing, I have 32GB RAM of desktop vscode can't edit 400~ish text file. LOL.
![Image](https://github.com/user-attachments/assets/e22032ce-1d2e-4363-8056-f410dfe7e038)
![Image](https://github.com/user-attachments/assets/cbda0a5f-8fc9-472a-bf13-fc28c04f4624)

**Comment by GhostDog98** [comment]
It's kind of insane that this is still an issue... I can find replace on multi-hundred gigabyte text files in sublime text... but not in vscode...

**Comment by ccruttjr** [comment]
@weinand @alexdima @rebornix maybe take another peek at this.

**Comment by draude74** [comment]
bump, please fix

**Comment by pejrich** [comment]
If VSCode is gonna use up over a gig of RAM, it should at least have the courtesy to let me replace all on a file under 1GB. It always adds insult to injury when VSCode of all apps tells me I'm being too resource intensive.

**Comment by ccruttjr** [comment]
As was asked 7 years and two+ months ago, it seems VS Code cannot handle replace alls on files greater than 2 million lines (egregious I know).

@legomushroom @roblourens @joyceerhl @lszomoru @jrieken @Tyriar @hediet @aiday-mar @amunger @meganrogge @mjbvz @connor4312 @bpasero @deepak1556 @joaomoreno 

Sorry for @-ing all of you, but seeing as you are all active contributors to this repo, I was curious if you thoughts aligned with the rest of us and/or this is something that could be solved since our computers are much more capable than 7 years ago. This'll be the first and last time I'll bug all of you like this.
Thanks!

**Comment by OuuGiii** [comment]
bump, this is also an issue for smaller files as well (a 13 000 KB file with only 25 000 rows). Can't rely on vscode to do find&replace anymore if this doesn't get fixed.

**Comment by epuster** [comment]
Still a problem v 1.99.3

**Comment by JalinWang** [comment]
can we make it an option?

**Comment by valentype** [comment]
Update to my previous message. That worked in Win11, but not on Mac. This setting makes no difference there and no errors or   alerts even appear when attempting to "replace all"
