### ISSUE TITLE
Add option to disable copy-on-delete

### ISSUE THREAD

**Issue by mafflin** [microsoft/vscode#40645]
- VSCode Version: 1.19.1
- OS Version: Linux 4.14

Steps to Reproduce:

1. Select something
2. Copy selection
3. Remove any strings with shift+del
4. Paste

It pastes deleted strings.

Add option to disable this behavior (Do not copy anything to buffer on delete).

Reproduces without extensions: Yes

**Comment by weinand** [comment]
I cannot reproduce this behaviour.
Can you repro this when running `code --disable-extensions`?

**Comment by mafflin** [comment]
Yes, try to remove string with shift+delete.

**Comment by thinkOfaNumber** [comment]
I was about to open a new bug but found this which sounds almost identical. I hope this explanation can give you enough information to reproduce it. I have reproduced it with and without all extensions disabled.

Issue Type: <b>Bug</b>

By default Shift+Delete is mapped to the clipboard cut operation.

If I delete the mapping it (i.e. map to nothing) via File > Preferences > Keyboard Shortcuts, then Shift+Delete still cuts text.

If I map Shift+Delete to something else (e.g. at random I chose "Show Installed Extensions); then Shift+Delete no longer cuts, but shows extensions as expected.

If I then unmap it again, Shift+Delete now returns to "cut".

This is a problem for the following use-case:
1. copy some text for pasting elsewhere
2. move to another location to delete some text (I often use Shift with arrows or home/end, then press Delete, for example, "Shift+End, Delete")
3. move to another location to paste the copied text from 1. however I discover that in step 2. I didn't lift my finger off the shift key soon enough, coupled with the delete means that I've copied the text that I deleted.

Because Delete and Shift+Delete look the same (they but remove the selected text), I don't know that this has happened until I paste, by which time I could be viewing a different file and have to find where I copied the initial text from again.

I tried deleting another keyboard shortcut (at random I chose Ctrl+K - clear terminal). When this is unmapped, Ctrl+K does nothing as expected.

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz (12 x 3491)|
|Memory (System)|15.64GB (4.24GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe C:\Users\<location of project folder snipped>
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
aurelia|Aur|1.0.3
Aurelia|beh|1.2.2
EditorConfig|Edi|0.12.1
debugger-for-chrome|msj|4.3.0


</details>

**Comment by thinkOfaNumber** [comment]
Just tested with Code 1.25.0 and this is still an issue. Is there anything I can do to help?

**Comment by alexandrudima** [comment]
Just map shift+delete to delete:
```json
{
  "key": "shift+delete",
  "command": "deleteRight",
  "when": "textInputFocus && !editorReadonly"
}
```

**Comment by thinkOfaNumber** [comment]
Thanks for the suggestion Alexandru. It kind-of works, but it's really only a workaround, as this stops DEL from working.

Could this be reopened?

thanks.

**Comment by alexandrudima** [comment]
@thinkOfaNumber How does the above stop `DEL` from working?

**Comment by thinkOfaNumber** [comment]
> @thinkOfaNumber How does the above stop `DEL` from working?

I made the setting through the keyboard shortcut GUI. I realise this is not what you said, but seems to be the primary method of changing keyboard shortcuts, while the keybindings.json is for "[advanced customisation](https://code.visualstudio.com/docs/getstarted/keybindings#_advanced-customization)".

Via the GUI, all I can do is:
1. delete the shift-del shortcut, and
1. edit the "deleteRight" kebinding shortcut to be shift-del

And this is what stops DEL from deleting.

Alternatively, I can edit the keybindings.json file and add the following:

    {
		"key": "shift+delete",
		"command": "-editor.action.clipboardCutAction",
		"when": "textInputFocus && !editorReadonly"
    },
	{
		"key": "shift+delete",
		"command": "deleteRight",
		"when": "textInputFocus && !editorReadonly"
	}

The -editor command is not essential but if I don't include that, then in the GUI, cut still appears to be mapped to shift-del.

So, my humble opinion is this is very much a workaround. The litmus test I apply to this (as a developer) is _"would I include these instructions in the documentation as the normal method of configuring the shift+del keyboard mapping?"_ I think quite clearly this is an awkward way of configuring only-one keyboard binding.

> By default, Shift+Delete will cut.

I'm happy with the defaults :)

> This is consistent with the OS.

I never knew that! But interesting.

One might even expect to be able to unmap the shift+del shortcut by putting the following in the kaybindings.json file:

    {
		"key": "shift+delete",
		"command": "-editor.action.clipboardCutAction",
		"when": "textInputFocus && !editorReadonly"
    },

but that doesn't work either. (This is in fact what Code does for you when you delete the shift+del cut binding, but it does nothing. Another indication that something is not quite right).

So at the end of the day I'm thankful that you've shown a way to get around it, however I cannot see how this is intended behaviour due to the 3 or 4 inconsistencies with this particular shortcut, which is why I asked it to be reopened.

I'm appreciative of your efforts toward Code. Thanks for reading this far!

**Comment by alexandrudima** [comment]
It's a little bit complicated and I was hoping to avoid a deep explanation, but here goes..

There is a keybindings dispatching system that we (VS Code) built. That's the one that you interact with in the keybindings editor (which is just a simple GUI on top of `keybindings.json`) and that is pretty much driving all your keystrokes...

When we (VS Code) receive a keybinding, we will look up all the rules that we have and try to match it to a command to execute. If we do have a rule to execute, we will invoke `event.preventDefault()` on the `keydown` event. Since we are built on top of Electron (which is built on top of Chromium), certain keybindings have default actions. The easiest example is `Tab`. When you press `Tab`, and nobody invokes `event.preventDefault()`, `Tab` will move focus to the next focusable element. This behaviour is what is called the "default" behaviour of the key. To make it worse, some of these "default" behaviours cannot be invoked manually... So browsers don't have a way to move focus to the next focusable element outside of pressing `Tab`... So we do need to allow that sometimes keybindings end up executing their default actions... Like in the case of `Tab`, where it can be used to move focus around the UI for accessibility purposes...

Now, what happens in this specific case with Shift+Delete is the following. Out of the box, we have a keybinding which maps Shift+Delete to cut. Once you remove the keybinding (via the GUI or via `keybindings.json`), when you press Shift+Delete, we will have no rule associated to it. We will therefore not invoke `event.preventDefault()` on the keybinding. The "default" behaviour on Windows for this key combination is to invoke cut, so Chromium itself invokes `cut` (the event) on the editor. The editor reacts to raw `cut` events (even those that didn't come via keybindings) because some of these events can be emitted by screen readers or other special input devices. We therefore cut when you remove our keybinding for Shift+Delete...

The solution is not to unbind Shift+Delete, but to have a keybinding for Shift+Delete, one which you like, which appears to be the invocation of delete. I have read the issue of the OP and the OP asks for an option to suppress that Shift+Delete overwrites the clipboard. I think configuration settings are great, but I would not add an option for every little thing, especially when it comes to keybindings which are 100% configurable.

So, all in all, I closed the issue and presented a working solution without spending too much time explaining all the crap behind the scenes :)... There isn't really anything I would change in the way our keybinding system works, because we do want to allow keybindings to pass through to their default actions in case they are not mapped with us (that's how IME works, Tab that I detail above, etc...).

**Comment by thinkOfaNumber** [comment]
Sorry for not replying earlier, but I really appreciate this explanation, thanks!
