### ISSUE TITLE
Debug Problem

### ISSUE THREAD

**Issue by christianbender** [Microsoft/vscode#40664]
How can I debug the vscode-project?
I have installed the chrome debugger. But what should I use as a entere point? 

- VSCode Version: 1.20
- OS Version: Linux

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by cleidigh** [comment]
@christianbender 
Best to ask development VSC on stack overflow or slack as mentioned above.

Just to get you going:
- To start you might try adding a breakpoint on some command to try debugging that way.
- Stopping at startup is not straightforward because basic debugging is done through the extension at host which needs to start first.  Not usually a problem as most development contributions will be at the extension or main process level.

**Comment by christianbender** [comment]
@cleidigh  

My problem is I don't know whether should start first code.sh and then with debugger goes through a special file. I know what debugging is and I have practised debugging by my own projects. But at a project whats is been done. I don't know how I should start. 

Thanks for the help and the note with **slack**

**Comment by isidorn** [comment]
@christianbender https://github.com/Microsoft/vscode/wiki/How-to-Contribute#debugging
