### ISSUE TITLE
Streamline extension recommendations

### ISSUE THREAD

**Issue by ianwesterfield** [Microsoft/vscode#4074]
Towards the end of #3633 in a summary by @egamma, a design decision is listed that recommended extensions shouldn't be refreshed unless one of them was installed.

I could be misreading that thread or misunderstanding the desired behavior of the feature, but a month after opening a PHP file, I find myself staring at a bunch of PHP recommendations even though I'm into a project now that doesn't use PHP at all...making this feature useless.

Shouldn't this be based on whatever file you have open, like I believe it originally was?

**Comment by jrieken** [comment]
@joaomoreno Is that you remembering everything that has been proposed ever?

**Comment by egamma** [comment]
Since extensions are global, it is fair to recommend extensions globally. Now since the extension isn't very prominent users might to use when a particular file is open, therefore considering the history is the right thing to do.

What is missing is a way to express I'm not interested in this recommendation (e.g. PHP) do not show it to me again. 

We will not change this for march, but we will revisit the recommendation approach.

**Comment by ianwesterfield** [comment]
@egamma I think having an option to not show PHP again would be inaccurate. I may be interested in PHP extensions in the future, but not while in a node project. I think extensions are globally available, but they are often specifically scoped. Doesn't it make sense to suggest popular or new extensions based on whatever file type I'm in at that time?

**Comment by egamma** [comment]
@ianwesterfield this reasoning makes sense to me. We can also consider workspace local extensions in the future.

**Comment by joaomoreno** [comment]
Closing this as we intend to keep showing a list of all possible recommendations.
