### ISSUE TITLE
Solarized color scheme does not correctly highlight certain keywords

### ISSUE THREAD

**Issue by domoritz** [Microsoft/vscode#4079]
vscode
<img width="333" alt="screen shot 2016-03-12 at 20 04 49" src="https://cloud.githubusercontent.com/assets/589034/13726847/0140cf0e-e88e-11e5-958b-ffdc8ba0c188.png">

Atom:
<img width="333" alt="screen shot 2016-03-12 at 20 05 57" src="https://cloud.githubusercontent.com/assets/589034/13726856/12509c5c-e88e-11e5-94e7-590ad1d3dfc0.png">

Sublime:
<img width="395" alt="screen shot 2016-03-12 at 20 09 07" src="https://cloud.githubusercontent.com/assets/589034/13726864/4eaeac02-e88e-11e5-8841-e25584082c29.png">

I believe that the keywords const, export, private, and class should be darkgray as in sublime.

**Comment by aeschli** [comment]
I have fixed the issue that out default coloring interferes with the colors of the themes.
We now look similar to your sublime screenshot, although Sublime doesn't seem to use 'bold' for the modifiers as it says in the Solarized light theme.
Atom seems to use a different grammar, that's why the colorizing also looks different.

**Comment by domoritz** [comment]
has this fix landed in `0.10.11`? I'm still seeing exactly the same issue.

**Comment by aeschli** [comment]
No it's in the coming release which you can already try out as an insiders build (https://code.visualstudio.com/insiders)
