### ISSUE TITLE
Git: Missing/Incorrect the number of commits (pull/push)

### ISSUE THREAD

**Issue by Onfealive** [Microsoft/vscode#40851]
- VSCode Version: 1.19.1
- OS Version: Windows 10 Pro 10.0.16299

Steps to Reproduce:

1. Enter a folder with git
2. Check Git Status Bar. Cannot see the number of commits. (The part in red border is missing; or always 0↓ X↑, although it had a pull.)

![git number commit](https://user-images.githubusercontent.com/18258131/34367969-b38dc0e2-eae2-11e7-8a3e-568810545e2d.png)

Reproduces without extensions: Yes

**Comment by jackjamieson** [comment]
Having the same issue, all extensions disabled.

**Comment by saurabh-deep** [comment]
I am encountering the same issue after updating to version 1.19.1. I cannot see the part shown in red border in the original issue description.

**Comment by joaomoreno** [comment]
What does the following return?

```
git rev-parse --symbolic-full-name --abbrev-ref HEAD@{u}
```

**Comment by johnroper100** [comment]
I am having the same issue here as well, all extensions disabled.

**Comment by johnroper100** [comment]
This is working with the latest insiders build. 16d763ead2ff6f832dbf554a8575e70b7b821671

**Comment by joaomoreno** [comment]
@Onfealive Can you try out our [insider release](https://code.visualstudio.com/insiders)?

**Comment by Onfealive** [comment]
@joaomoreno 
![report-2018-01-10](https://user-images.githubusercontent.com/18258131/34752489-35809630-f5e5-11e7-86c0-c0cf299e7205.png)
Version insider: f4ed56b

It displays *0↓ 1↑*, but failed when using `git push`. I must use `git pull` before it, but after that, _0↓ X↑_ is disappeared.

**Comment by joaomoreno** [comment]
@Onfealive This happens because automatic fetching is now disabled by default. Fetching is `git fetch` and it is the command which lets git know whether there are incoming commits. Since it is disabled by default, `0↓` stayed.

You could have run `Git: Fetch` to fetch the latest commits from the remote. This would update the `↓` counter. Then, `Git: Push` would have worked.

You could also have run `Git: Sync` which would pull and then push.

You can also enable automatic fetching with the `git.autofetch = true` setting.
