### ISSUE TITLE
Debug adaptor crash

### ISSUE THREAD

**Issue by mike-lischke** [Microsoft/vscode#40864]
- VSCode Version: 1.19.1
- OS Version: macOS 10.12.6

Steps to Reproduce:

1. Set up the [mock debug](https://github.com/Microsoft/vscode-mock-debug) example so that you can debug.
2. Export a variable `test` from `extension.ts` like: `export let test = "blah";`
3. Import that var in `mockDebug.ts` by: `import { test } from "./extension";
4. In `launchRequest` add this assignment right after the logger setup: `let t = test;`.
5. Start debugging again and: BOOM. (error: "Debug adapter process has terminated unexpectedly").

What's especially worse here is that you neither can debug your debug adaptor (the debug session), nor do you get any info what actually happens (no further info in the error message, nor in the developer tools.

Note: you can import that variable successfully from any other ts file without any problem.

**Comment by weinand** [comment]
The debug adapter (DA) runs as an independent process outside of the extension host. It is completely independent from VS Code and cannot access any VS Code extension API.
That means you cannot import anything from the extension host code in a debug adapter.
If you try to import extension.ts into the DA, this will fail because extension.ts expects to run in the extension host.

If you need to access something in the extension from the DA,
- you can pass it from the extension to the DA on debug session start via the launch config (see `DebugConfigurationProvider.resolveDebugConfiguration`), or
- you can send a custom event from the DA and have an event handler (`debug.onDidReceiveDebugSessionCustomEvent`) in the extension that sends the data back to the DA via a custom request (`DebugSession.customRequest`).

**Comment by mike-lischke** [comment]
Great, thanks, you addressed my actual problem :-) Still, I think the DA shouldn't just crash. Also, it's not clear how to debug your DA code. Sending messages around? That's like last century debugging...

A word about the debug configuration provider. This is what I tried first, however that works only for simple values (numbers, strings), not for class instances. Now that I know the DA is a separate process, I understand why. You'd need a marshalling strategy for complex objects to make them available in the DA. How's that supposed to work? How can I, for example, create my debugger instance in the DA? The extension is required to do that. But since I cannot pass it to the DA, how can I actually create that object?

**Comment by weinand** [comment]
If you write a DA and load arbitrary JavaScript code in a DA, you'll have to protect your DA against crashing. VS Code cannot do that. 

You debug a DA by running the DA in VS Code. See https://code.visualstudio.com/docs/extensions/example-debuggers#_development-setup-for-mock-debug.

As you can see in this screenshot both the debug extension and the DA are running in debug mode:
![debug-extension-server](https://user-images.githubusercontent.com/1898161/34387214-180201c4-eb2d-11e7-80f3-344f6b791917.png)

I mentioned sending custom events from the DA to the extension to solve the problem of sharing data between the extension and the DA, not for debugging anything.

Why do you have to create the debugger instance in the extension and not in the DA? Of the ~ 40 VS Code debug extensions I'm not aware of any that does this.

With this debugger API you are using is it really possible to create a debugger instance in one process (extension host) and pass that instance to another process (DA). I have not yet seen an debugger API that supports that.

**Comment by mike-lischke** [comment]
Multisession debugging, damn that escaped me. Thanks for pointing that out.

About the backend debugger: actually I don't care so much where it is created, but the problem is that it needs data from the backend, which drives the extension. This backend holds important data without which the debugger wouldn't work. So I have to let the backend create the debugger, no way around that. However that means I either have to pass in my backend to the DA or the created debugger. Neither is possible, from what I see. And I believe this is not a very unusual approach, since the extension is what does the actual job. The adaptor is just a communicator, translating between the vscode debugging UI and the debuggee. So I find it pretty obvious that it needs something to talk to the debuggee. In my case the debuggee is not a separate process that communicates via sockets, but something that runs directly in my extension (actually in the backend, driving the extension).

**Comment by weinand** [comment]
Multisession debugging: you only need this if you have code both in the extension and in the DA. Most debuggers have only a DA, so they have no need to debug the extension (Historical fact: DAs predate VS Code extensions; early versions of VS Code had pluggable debuggers via DAs but no extensions).

Your "backend debugger":

It sounds to me that your backend could just implement the Debug Adapter Protocol (DAP) and you would not need a DA (that is a separate process) at all.

The Java Extension does something similar: they have a single Java backend process (written in Java) that implements the Language Server Protocol (LSP) and the Debug Adapter Protocol (DAP). Instead of using a standalone DA process, they tell the VS Code debugger UI to connect to a specific port of their backend server that implements the DAP. 

By using this approach you could even implement the DAP in your extension (again not as a separate process).

**Comment by weinand** [comment]
Please note: if you do not have an explicit DA it will not be possible to run your debug extension in other frontend clients e.g. Visual Studio or Visual Studio for Mac.

**Comment by weinand** [comment]
Another note: you could try to use the npm module that implements the DAP ([vscode-debugadapter-node](https://www.npmjs.com/package/vscode-debugadapter)) directly from your extension - basically as an "embedded DA".

**Comment by mike-lischke** [comment]
Thanks a lot for your suggestions. I much appreciate the time you spend trying to help me. Unfortunately, the ideas you mention are rather abstract, so I will have to find examples first, to understand what we are talking about here. Having the backend implement the DAP sounds like a good path to follow. Do you have some code that does this, which I could use to learn?

**Comment by weinand** [comment]
Moin Moin! :-)

The only example for a backend implementing the DAP is the Java extension which lives here: https://github.com/Microsoft/vscode-java-debug
But the repo doesn't contain the DA because that lives in the backend (and I don't know whether that's available in open source). I'll investigate...

On the other hand I've planned to create a branch of mock-debug that runs the DA embedded in the extension.ts (i.e. not as a separate process). This is not a lot of work and would be a nice proof of concept for the "abstract ideas" from above. Since I'm on vacation right now I don't know how if I find enough time to work on this. But I'll try...

No, use of the vscode-debugadapter-node module is not mandatory. It is only meant as a convenience for adapters that are implement in JS or TS.

The DAP is the "real beef". It is specified as a [JSON schema](https://github.com/Microsoft/vscode-debugadapter-node/blob/master/debugProtocol.json) and client libraries for different languages are [generated](https://github.com/Microsoft/vscode-debugadapter-node/blob/master/src/generator.ts) from this automatically. The Java team generates a Java library from this, and I'm aware of a .net/C# generator.

**Comment by mike-lischke** [comment]
Woah, you shouldn't answer here, when you are on vacation :-D - the more I appreciate your help. I'll wait for your new branch to see how to use an embedded DA.

**Comment by weinand** [comment]
@mike-lischke with this [small change](https://github.com/Microsoft/vscode-mock-debug/commit/b4355c4aed2cfe23e2947ce131f9b3c168bc1380) the extension runs DAs inside the extension host.
See branch [embedded-DA](https://github.com/Microsoft/vscode-mock-debug/tree/embedded-DA).

**Comment by mike-lischke** [comment]
@weinand This is just awesome. I'm so excited. Not only is the debug session now created as part of the extension, it also supports debugging out of the box **and** I can use my normal backend to create the actual debugger. Atm, everything is fine now. Thank you so much!

**Comment by weinand** [comment]
VS Code does not know why a DA is crashing (because a DA is just an arbitrary program written in any language), so I don't see a way to improve the error message.

BTW, please pull the latest from the embedded-DA branch since it now contains the final code.

**Comment by mike-lischke** [comment]
I see. Anyway, many thanks for your help.
