### ISSUE TITLE
Panel: clicking on panel shows the focus indicator jumping

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#40870]
See video:

![before](https://user-images.githubusercontent.com/900690/34389421-ce60a946-eb39-11e7-9126-e36d76192b03.gif)

**Comment by isidorn** [comment]
This was caused by https://github.com/Microsoft/vscode/commit/e5808be148c60f3a9aac27fece7eff1fa21a0264

fyi @sandy081 not sure why you introdcued a height of 82% but it breaks the outline. I have reverted the height change, if you need something special for the problems panel you can do it scoped per that panel
Also when making changes to the size of the panel title area always make sure that the outlines, focus and high contrast do not get broken. Thanks
