### ISSUE TITLE
Add settings to disable recommended extension badges

### ISSUE THREAD

**Issue by themowski** [Microsoft/vscode#40881]
I recently upgraded to version 1.19 from version 1.15.

I find that the "recommended extension" badges introduced in #36650 are really distracting. It doesn't make sense to me to show these badges for extensions that I've already installed. If I am already using the extension, its "recommended" status is irrelevant to me!

Additionally, in the "recommended extensions" pane, every extension featured is recommended, so the badges are fairly redundant.

I will admit, though, that these badges serve a purpose when performing a search for extensions, so perhaps totally disabling the badges isn't always the best solution.

Can we add a setting or two related to disabling these badges? Here are a few possible options to think about:
* Disable the badges entirely
* Disable the badges only in the "installed extensions" pane
* Disable the badges only in the "recommended extensions" pane (may be related to the fix for #37419)
* Disable the badges only in search results

**Comment by ramya-rao-a** [comment]
- The main purpose of the badge is to be able to highlight recommended extensions when performing search in the extensions viewlet.
- The purpose of the badge in other views is to maintain consistency. The badge re-enforces the idea of a "recommendation". This way, when searching, users will know at quick glance if an extension is recommended. On hover, it also displays the reason for recommendation.

I wouldnt add a setting to disable the badge in various different scenarios. 

Instead, I would be open to considering keeping the badge only during search and not in any other views (Installed/Recommended view) if there is enough user feedback supporting the same.

**Comment by usernamehw** [comment]
nvm, waiting for votes and implementation can take years... Back to good ol' hacks:
```css
/* remove all recommended extension badges */
.extensions-viewlet .monaco-list-row.recommended > .bookmark {
    display: none !important;
}
```

**Comment by roblourens** [comment]
The extensions viewlet is by far the most visually noisy UI in vscode... I don't see it as any more distracting than the repeating Install buttons or anything else.

**Comment by chrmarti** [comment]
Always showing it makes it easier to understand and navigate, I would leave it that way. I agree a setting seems too fine-grained. Would it be an improvement if the decoration was a little smaller?

**Comment by isidorn** [comment]
My setup: no need for css hacks, just hide the extensions viewlet with right click. Have auto update of extensions turned on and you can always bring it back with cmd + shift + x.

**Comment by usernamehw** [comment]
@chrmarti the size is fine, only the place is bad.

**Comment by usernamehw** [comment]
@isidorn I don't see how this is related to the badge. Extension auto-update is already enabled and it's not like someone writes code with extensions viewlet visible.

**Comment by Tyriar** [comment]
@usernamehw I think what @isidorn is getting at is that generally once you're set up, you see the extension viewlet so little that if you do find it distracting it isn't a big deal.

**Comment by laoshaw** [comment]
this is a truly distracting new "feature", please get rid of the "recommended" panel for extensions, or at least give us a flag to turn it off permanently.

**Comment by ramya-rao-a** [comment]
@laoshaw 

- In 1.19.3, you can choose to hide the recommendations panel. Right-click on the panel title and choose "Hide"
- Or if you use the latest [Insiders](https://code.visualstudio.com/insiders), you can get add the setting `"extensions.showRecommendationsOnlyOnDemand": true`. This will stop showing you recommendations altogether unless you specifically ask for it

**Comment by laoshaw** [comment]
works as expected. thanks!

**Comment by DanTup** [comment]
Does anyone understand the logic for when the badge appears? Someone reported to me that all extensions he has installed are marked as recommended except for Dart Code. Since the recommendations are based on files he's edited and he uses Dart a lot (even had a Dart file open at the time) he was surprised Dart Code didn't have the badge.

I opened my own copy of Code, and I see the same thing - Dart Code has no badge, yet my other installed extensions are (if I remember correctly, I've had all of them installed for quite a long time, though Dart Code certainly is the oldest). How does Code decide where to show them? If it's based on file types, why isn't Dart Code getting one?

<img width="553" alt="screen shot 2018-03-28 at 21 34 35" src="https://user-images.githubusercontent.com/1078012/38054909-33411aa2-32d0-11e8-8684-a180bd3273ce.png">

**Comment by ramya-rao-a** [comment]
@DanTup If you hover on any of the extensions or click on them and read the details on the right, you will see the recommendation reason there. The ones that have "... based on the files you have recently opened" are based on the files you have opened plus a white list we maintain. Since your extension is not in the whitelist, it doesnt show up in the recommendation list. We have gone through this in https://github.com/Microsoft/vscode/issues/41866#issuecomment-359057965

**Comment by DanTup** [comment]
@ramya-rao-a Aha, gotcha - apologies, I thought these stars were using the data from the prompt that does work for Dart, not that whitelist. Makes sense now!

**Comment by DanTup** [comment]
@ramya-rao-a Understood. I think the tooltip is a little misleading then, since Dart Code matches what's written in the tooltip, but thanks for the explanation.
