### ISSUE TITLE
DEBUG CONSOLE continuously scrolls on last line

### ISSUE THREAD

**Issue by hawkeye64** [Microsoft/vscode#40899]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:41:01.414Z)
- OS Version: Linux x64 4.10.0-42-generic
- Extensions: the listing length exceeds browsers' URL characters limit
---

Steps to Reproduce:

1.Run some server code with lots of output
2.In the DEBUG CONSOLE, try to go back in the history (see what some issue might be)
3.The DEBUG CONSOLE will continue to scroll, even if you scroll it up. It shoudl only scroll if the last line is visible in the window, otherwise it should just append and not scroll.
4. Right now, you have to stop the server so there is no longer any input, just to what an issue might be.

Reproduces without extensions: Yes

**Comment by isidorn** [comment]
@joaomoreno I have changed the tree to return `1` whenever the tree is scrolled all the way (this now inclued the case when the tree was smaller than the available height)
I checked and I am the only client of this method and it also makes sense (is the glass half full or half empty)

**Comment by joaomoreno** [comment]
I'd actually prefer it to return 0 since here's the rule for the normal case:

- 0, if the content's top is aligned with the viewport's top
- 1, if the content's bottom is aligned with the viewport's bottom

When the content height is less than the viewport height, the content's top is aligned with the viewport's top... so 0 would make more sense.
