### ISSUE TITLE
Preview the changelog when looking for outdated extensions

### ISSUE THREAD

**Issue by alefragnani** [microsoft/vscode#4090]
When you check for outdated extensions (`F1 / Extensions: Show Outdated Extensions`), you are able to see the `Readme` and `License`, but not `what's new` :cry: . 

Besides not being a required file when publishing extensions (in `package.json`), the `Changelog`  should be shown, if existed. Even better if it could show the difference from the installed and the new version, but for that, I know it would need _to define how changelog file is structured_).

Thanks in advance

**Comment by joaomoreno** [comment]
We can't really make people write Changelogs... Clicking README will send you in the direction of the extension's homepage from which you can see the Changelog if the extension writer was kind enough to write.

**Comment by alefragnani** [comment]
The intention was _to use_ the changelog, if existed. So, the developers that create it, would take advantage of it.

Thanks for your help

**Comment by joaomoreno** [comment]
It's a good idea, and we do appreciate the feedback.

I've changed my mind, let's keep this around for when we improve the extensions UI.

**Comment by scottohara** [comment]
Also missing is the version number for the updated version.

For example, I currently have 2 outdated extensions:

![image](https://cloud.githubusercontent.com/assets/289327/19543471/5ef05500-96c3-11e6-8603-437f7c696455.png)

For the first one, EditorConfig, I have 0.3.3 installed; and the changelog shows up to that version.

If I click "Update" now, according to the [Marketplace](https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig) I should get version 0.3.4; but the only way I can know this is by visiting the extension page on the Marketplace site.

![image](https://cloud.githubusercontent.com/assets/289327/19543509/b998efc6-96c3-11e6-9b15-d5084b169124.png)

Since VSCode already knows there is a later version available on the Marketplace, shouldn't the version number of the latest version be displayed somewhere?

(In particular this would be useful for extensions that adhere to SemVer, as it would be clear there are any breaking changes in the later version).

And since the developer in this case does have an updated changelog available on their GitHub repo, it would be far more useful to show that in VSCode, rather than showing changelog as at the version already installed:

![image](https://cloud.githubusercontent.com/assets/289327/19543530/efb97ba2-96c3-11e6-8e68-443bb4ee36c8.png)

**Comment by joaomoreno** [comment]
Every time you start a comment with _**also**_, think about whether that is a separate issue, which in this case, it definitely is, @scottohara. #12154

**Comment by alefragnani** [comment]
Closing the issue because it seems the recent updates on VS Code works as expected.

Thank you
