### ISSUE TITLE
no property autocomplete in JSX(related with an empty space)

### ISSUE THREAD

**Issue by jiyinyiyong** [Microsoft/vscode#40941]
- VSCode Version: Version 1.19.1 (1.19.1) 0759f77bb8d86658bc935a10a64f6182c5a1eeba

- OS Version: macOS, 10.12.6

Steps to Reproduce:

TypeScript React, and https://twitter.com/jiyinyiyong/status/946642303950626817

Reproduces without extensions: Yes.

**Comment by mjbvz** [comment]
@jrieken For the case:

```tsx
const z = <div c>
```

where the user has just typed `c`, `LineContext.shouldAutoTrigger` returns false since `getWordAtPosition` returns `null`. This in turn is caused by `<div c>` having the following language ranges for the string `<div c>`:

```
<div c>
xxxxxTx
```

where `x` = `jsx-tags` and `T` = `javascriptreact`. These language ranges cause `getWordAtPosition` to take  `>` as the current word, which does not match against the known word patterns

**Comment by kevinmlong** [comment]
Any update on this? The Ctrl-Space works and provides the correct autocomplete options for props with associated type. Would be nice if I didn't have to do that each time.

**Comment by gopeter** [comment]
@kevinmlong Have the same problem, but wonder about: "... autocomplete options for props ...". Is VS Code capable to autocomplete my custom `propTypes` from an imported component?
