### ISSUE TITLE
1.19.1 broken with msys2 git

### ISSUE THREAD

**Issue by jonaskello** [Microsoft/vscode#41019]
- VSCode Version: 1.19.1
- OS Version:

I used msys2 git for a long time with vscode but in 1.19 it is now broken :-(.

Steps to Reproduce:

1. Setup vscode with msys2 git as described in #4651.
2. Get multiple source code providers as in the picture below:

![image](https://user-images.githubusercontent.com/664076/34478294-7da35c9a-efa0-11e7-86e3-6e013feab9e4.png)

The problem manifests itself in the same way as described in #40249 and #40121.

Reproduces without extensions: Yes

**Comment by jonaskello** [comment]
Downgraded to 1.18.1 using [chocolatey](https://chocolatey.org/packages/VisualStudioCode/1.18.1) and now it works again.

Not sure what is going on. Is there some way to see a log of the communication between vscode and git?

**Comment by joaomoreno** [comment]
Similarly to https://github.com/Microsoft/vscode/issues/40249, do you have any `git worktree` setting configured?

**Comment by jonaskello** [comment]
Yes I read that issue. I have no special settings that I know of. My output is this:

```
$ git worktree list
/c/code/mydir/myproject  e838699 [master]
```

**Comment by jonaskello** [comment]
I think what is special in my case is that I am using the `git-wrap.bat` as described in #4651.

**Comment by joaomoreno** [comment]
Got it. VS Code doesn't support msys2 git. If it used to work, it was coincidental. The only supported mechanism is Git for Windows: https://git-scm.com/

**Comment by jonaskello** [comment]
Gotcha. I would be willing to look into a work-around like the one that worked before. Do you have any pointers where to start? For example is there a log somewhere of vscode <-> git communication? Is there any technical docs somewhere specific to the git integration?

**Comment by suzeeparker** [comment]
![sc80212-1620 _dup gits 75secs 1fps](https://user-images.githubusercontent.com/32445257/36123614-4762cd64-101b-11e8-9e0a-70e56012f098.gif)
I am also seeing the problem of "Too many repositories open" - issue #40249.  I am on Windows 10 with the following versions.  
```
git version  -> git version 2.14.1.windows.1
code --version  -> 1.19.3   7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba   x64
```
I checked the worktree setting, and the local one was set to the current repository folder.   
```
git config          --get core.worktree
git config --global --get core.worktree
git config --system --get core.worktree
git config --local  --get core.worktree
  C:/WEBs/SCN2/Files/PAGs/Email-Templates1/Dev1
```
The same path shows up here
```
git worktree list
  C:/WEBs/SCN2/Files/PAGs/email-templates1/Dev1  018bf433 [master]
```
If I unset the LOCAL config, the problem does indeed go away. 
```
git config --local --unset core.worktree
```
But since I do not know how the local worktree got set, you might want to look into the problem.  I can reproduce it everytime I open VSCode in a workspace folder, after re-setting the worktree folder.  

The behavior is not exactly the same each time, but by clicking on the refresh icon, I can cause many duplicate GIT repositories to appear.  I have uploaded a 75 second .gif that shows what happens.  

It started happening after copying files to an empty folder and issuing these three git commands
```
git init
git add . 
git commit "Add initial email templates" 
```
And editing one file.  If you want me to give you more information about the folder locations, and other adjacent folders with very similar names, I can.
