### ISSUE TITLE
[html] Why editor.action.smartSelect is not working in html file?

### ISSUE THREAD

**Issue by pokakhoaitay** [Microsoft/vscode#4101]
I can not use `editor.action.smartSelect.grow` and `editor.action.smartSelect.shrink` functions to working on html file. I don't think the develop team have any reason to disable them on html file. It's should be working on any file!! Any body know why?
Please fix it!
Thanks!

**Comment by vsaroopchand** [comment]
I tracked this down to line 58 in editor\contrib\smartSelect\common\smartSelect.ts
When the code uses model.getModel().logicalSelectionSupport it does not work
	var selectionSupport = model.getMode().logicalSelectionSupport || this._tokenSelectionSupport;
// but works with _tokenSelectionSupport
var selectionSupport = this._tokenSelectionSupport;

I just don’t know enough about the VS Code APIs to know if this is the right fix

**Comment by hinogi** [comment]
I think the problem lies somewhere in the languages\html\common\htmlWorker.ts. For me it seems as if the getRangesToPosition implementation doesn't return the appropriate Position but returns undefined. I do not know how to debug the worker thoug :( but it really aint't "effort easy" I think.

**Comment by vsaroopchand** [comment]
Agree, did some more digging and getRangesToPosition in (\languages\html\common\html.ts) essentially an empty implementation. 

TokenSelectionSupport (contrib\smartSelect\common\tokenSelectionSupport.ts) has an implementation that is used by all other languages. 

The empty implementation in html.ts is being used because in html.ts, line 311 we have 
this.logicalSelectionSupport = this;

which causes the below line in editor\contrib\smartSelect\common\smartSelect.ts to use the empty implementation which returns undefined as you noted

var selectionSupport = model.getMode().logicalSelectionSupport || this._tokenSelectionSupport;

Seems this needs some refactoring - perhaps check if <Language>Mode implements ILogicalSelectionSupport before attempting to use it.

**Comment by jrieken** [comment]
@aeschli Any reason the html implementation is a noop?
