### ISSUE TITLE
Propose refactoring API

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#41048]
Explore official API / UX support for refactorings

**Comment by jrieken** [comment]
@bpasero Do the new async-menus support lazy loading of submenus? So, we could have a 'Refactor' menu and lazily populate it's sub-menu. Is that something we could do now?

**Comment by bpasero** [comment]
@jrieken I am not 100% sure you can modify a menu while it is opened, but we can try. However we are months away from being able to use the async context menu because only recently Electron added the necessary APIs for us to find out when the menu gets closed. 

The async options for menus exists already in the Electron version we are using, but we cannot adopt it because we have code that triggers when the menu closes (`onHide` handler). With the async option there is currently no way to find out when the menu closes so we are stuck with the sync option until we adopted a new major Electron version.
