### ISSUE TITLE
Explorer and open editors should use enablement via menu service

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#41103]
In the current stable vscode we use enablement state to show if an action is applicable on the current context in the open editors and explorer menu.
In the current insiders we simply do not show the actions which are not applicabe since we have adopted the open editors and explorer to use the menu service. And we use the `when` clause.

We should look into if it is possible for the `MenuService` to expose an enablement clause.

@jrieken is this already exposed? I could not find it
fyi @bpasero

**Comment by jrieken** [comment]
The idea is that a command has a *precondition* which is must be fulfilled in order to run. Editor commands already have that. [An example](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/commands/common/commands.ts#L38) is that the format action cannot run a readonly-document. 

For commands, I did add [`ICommand#precondition`](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/commands/common/commands.ts#L38) but the enforcement must happen in the right context (not how it's currently [done](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/commands/common/commandService.ts#L57)). In essence, the user-gesture must decide how to handle the precondition, e.g. a menu item shows it as disabled, and it must do that in the same context its uses for visibility.

**Comment by jrieken** [comment]
@isidorn scrap [this comment](https://github.com/Microsoft/vscode/issues/41103#issuecomment-355261774)... I undone `ICommand#precondition` and I have added `ICommandAction#precondition` and adopted it in `MenuItemAction`. Now, when registering a command you can define its precondition and when calling `Menu#getActions` the returned actions will have the state set properly.

**Comment by isidorn** [comment]
@jrieken thanks for this, it works great
@bpasero I compared with the current stable and added some preconditions (for save, compare with saved, revert paste). I had to introduce a `dirtyEditor` context for this.
Let me know if you have more precondition ideas.
