### ISSUE TITLE
Go Back and Forward

### ISSUE THREAD

**Issue by agustinbcu01** [Microsoft/vscode#41106]
- VSCode Version: 1.19.1 and 1.20.0-insider
- OS Version: Windows 7

Steps to Reproduce: 
Go Back and Forward  using the numeric pad left and right arrows with the numlock disabled navigates incorrectly by also generates the ASCCII char. 
Example go back two times generates the character 44  => ,

**Comment by alexandrudima** [comment]
@agustinbcu01 I'm sorry I don't quite understand what the problem is.

According to [wikipedia](https://en.wikipedia.org/wiki/Num_lock)

<img width="503" alt="image" src="https://user-images.githubusercontent.com/5047891/34674571-be5f277e-f486-11e7-8743-3e1017e4521e.png">

When the NumLock LED is on, `Numpad4` will produce a `4`. When the NumLock LED is off, `Numpad4` will be `ArrowLeft`. Is this not the case ?

**Comment by agustinbcu01** [comment]
The issue happens with NumLock OFF

**Comment by alexandrudima** [comment]
@agustinbcu01 

Have you been able to use `Numpad4` successfully in any other software ?

Have you tried with a different keyboard ? (maybe it is broken?).

**Comment by agustinbcu01** [comment]
Yes, Notepad, Visual Studio Pro, Edit plus

**Comment by alexandrudima** [comment]
@agustinbcu01 What does VSCode detect when you press `Numpad4` with `NumLock OFF`:

e.g.
![keyboard-input](https://cloud.githubusercontent.com/assets/5047891/25478333/fe31c830-2b40-11e7-865c-b2c3bb10dd75.gif)

**Comment by agustinbcu01** [comment]
I not a configuration issue, I can live with the issue, if you prefer you can close.
