### ISSUE TITLE
Feature request: Filter/group items by type in the problems tab

### ISSUE THREAD

**Issue by sbrw** [microsoft/vscode#41114]
- Ubuntu 17.10
- vscode 1.19.1
- C/C++ 0.14.5

I find it unfortunate to mix intellisense/lint errors and build errors/warnings in the "Problems" tab. I might have several multi-root folders in my workspaces, some with broken intellisense include paths and others without. I would still want to be able to build a single project, and only attend to the build specific compilation errors in the "Problems" tab. 

Currently it is annoying to expand/collapse, scroll and search though the interleaved items when solving build errors (compiler/linker/...).

Would it be possible to either:
- Add an optional filter to exclude items by type in the problem tab
- Group the items in the problem tab by type
- Add a specific problem tab for build errors

Possibility to navigate the problem items by type would also be great. For instance by binding keys to next/previous item by type.

Related issues:
https://github.com/Microsoft/vscode-cpptools/issues/1398
https://github.com/Microsoft/vscode-cpptools/issues/1286
https://github.com/Microsoft/vscode/issues/39604

Thanks!

**Comment by sean-mcmanus** [comment]
Let us know if this ever gets implemented, because I think we would need to change our Diagnostic results to result a "source". VS 2017 allows error list source filter/sorting.

**Comment by aenima1891** [comment]
I'd like this feature too.

**Comment by intijk** [comment]
I am same request also. 

Also would be good if we could hide also feedback and notification icons on right bottom corner.

**Comment by cmcit-bferg** [comment]
Please do not mark/close this as a duplicate. It's not. The other threads mostly talk about file.exclude; that's not what we want.

We want the ability to show/hide/filter by problem type. I get tons of errors about PowerShell vars being "assigned but never used," because they're used in other scripts that dot-source the definitions. VS Code doesn't realize this and is constantly warning me and green-lining things.

**Comment by sean-mcmanus** [comment]
@cmcit-bferg The message filtering could implemented by the PowerShell extensions itself. That's on our TODO list for the C/C++ extension.

**Comment by voidhofer** [comment]
This is a MUST HAVE feature! Implement it ASAP!

**Comment by bryceschober** [comment]
FWIW, this is a pretty major pain point. My developer workflow is along the lines of:

1. Fix all errors (get it to build)
2. Fix all warnings (get it to build cleanly & inhibit specific warnings we don't care about)
3. Fix all lower-priority linting / spellchecking before PR

I don't know how I can do that with VS Code, because of its intermixing of categories. All I want is another level to the tree, with all errors before all warnings before all informational items.

**Comment by ezekielcodisto** [comment]
This feature is useful also if you are working on legacy code. In my case, I'm adding E4X code in my Javascript file and errors just pop up even though the code is really working upon running it.

**Comment by georgesmith2017** [comment]
I know this is not a real fix, but as workaround, type the following in the Problems View filter (top right of the panel): `*.tf`
This will effectively ignore the .tfvars files. :)

**Comment by sandy081** [comment]
Agreed that filtering problems by type is a valid request but do not see a good reason for grouping (if given that filtering is supported). Hence this is accepted for filtering and there is an issue already for that. Hence making this a duplicate.

https://github.com/microsoft/vscode/issues/47354
