### ISSUE TITLE
Git: why is "go to file" suddenly so prominent?

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#41137]
I am not a big fan of the new action to open a file directly:

![image](https://user-images.githubusercontent.com/900690/34559470-46d23012-f142-11e7-861e-7d03195f13a4.png)

I am a very frequent user of the "Discard" change action and now I have to constantly aim at the right action to pick it. Before I knew my action was always the first action and now it is in the middle.

Can we back this by some numbers? How many people are really clicking there to open the file directly? Imho the action is way too prominent now and the workaround to use the context menu is easy enough:

![image](https://user-images.githubusercontent.com/900690/34559527-72b3b570-f142-11e7-9af3-1f8371de1d38.png)

Or directly from within the editor:

![image](https://user-images.githubusercontent.com/900690/34559556-8f7aba78-f142-11e7-9616-f56750aabba5.png)

**Comment by joaomoreno** [comment]
I've actually been getting a lot of praise for that action... It was requested by a couple of users. Others have thanked me for it. Even @alexandrudima is a big fan.

We can have an option for it, but I'll leave it on by default.

**Comment by bpasero** [comment]
Sure a setting is fine, even though ugly because I am most likely the only user...

**Comment by bpasero** [comment]
@alexandrudima @joaomoreno how about a setting for what happens when you click on a change? the setting could state if the file should be opened or the diff (by default it would still open the diff).

**Comment by alexandrudima** [comment]
@bpasero My self-estimated usage of the git viewlet:
* top action by far: open diff editor on a file.
* second place: open the file for editing (not in a diff editor); sometimes I misclick and then do the editing in the diff editor because I'm lazy. Sometimes I switch from the editor title action. Sometimes I right click and look for open file.
* rest of the time: stage changes, discard changes, commit message, stage conflicts, etc.

So an option to toggle between open diff editor on a file and open the file would make my first and second picks exclusive to each other.

**Comment by ghiscoding** [comment]
Hi there, I don't want to disrupt a team discussion but I'm also a very big fan of this new "open file" button. I find the right+click too long to do and was quite happy to see this new button, which I use almost every day now. In fact my top actions are almost the same, if not identical, to @alexandrudima. 

A setting for it is probably the best approach, these small new features are a huge difference in productivity.

**Comment by eamodio** [comment]
I have a love hate relationship with this feature -- I use it a lot, but only because there isn't another mechanism (I'd MUCH rather an alt-click or something on the item). I like @bpasero find myself having to be much more careful on targeting to hit the discard button (which I also use often).

**Comment by joaomoreno** [comment]
Added `config.showInlineOpenFileAction` setting.

**Comment by ghiscoding** [comment]
@joaomoreno I'm just curious, aren't we suppose to put the fastest condition, for performance reason, at the beginning of an `if` and the longest at the end? I mean, isn't your new config the fastest condition since it's in memory? 
```javascript
"when": "scmProvider == git && scmResourceGroup == merge && config.git.showInlineOpenFileAction",
```

Please disregard if it's not relevant, I was just curious. Thanks for the new flag

**Comment by joaomoreno** [comment]
@ghiscoding That actually depends on the implementation of the if. In this case, I do believe our context keys do yield as soon as a result is obvious. But all those values are in memory so it doesn't really make any difference in that regard. Checking the config is very likely to be the most expensive operation, though, since it probably needs a few more map hops to get to the answer.
