### ISSUE TITLE
Release memory when intellisense hides

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#4114]
- have a single JavaScript file with contents `do`
- trigger IntelliSense once, dismiss with escape
- take a heap snapshot
- repeat the IntelliSense/dismiss cycle ~10 times
- take another heap snapshot, mem usage grew by 1,5MB

**Comment by jrieken** [comment]
drilling to the heap show that suggestions are referenced via the focused item of the suggest widget

**Comment by jrieken** [comment]
[Archive 3.zip](https://github.com/Microsoft/vscode/files/171760/Archive.3.zip)

**Comment by joaomoreno** [comment]
As far as I could tell, nothing is really being leaked. We do keep holding on to memory after the Intellisense widget is closed, but everything gets released as soon as it opens again. You can verify this by running a **Record Heap Allocations** instead of multiple **Heap Snapshots**.

![screen shot 2016-03-15 at 22 58 13](https://cloud.githubusercontent.com/assets/22350/13795536/b58fcdf0-eb01-11e5-9ed2-7aafc45a139d.png)

[Heap-20160315T230025.heaptimeline.zip](https://github.com/Microsoft/vscode/files/174896/Heap-20160315T230025.heaptimeline.zip)

Rendering the entire JavaScript suggestion list allocates roughly around `700KB`. Which gets release upon the next Intellisense trigger. Although a great catch, given the findings, I think this hardly qualifies as a fix for March.

There is indeed a fix (releasing the memory as soon as the widget hides) but that would take a larger refactoring that what we should do in March, which I already wanted to do after this release. Moving this to April.

@jrieken Please check whether my findings are correct and sound.

**Comment by joaomoreno** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.

Thanks for your understanding. Happy coding!
