### ISSUE TITLE
Selecting with Ctrl+Shift and left/right arrow keys is not sensible but very cumbersome

### ISSUE THREAD

**Issue by mccreeker** [Microsoft/vscode#41199]
- VSCode Version: 1.19.1
- OS Version: W10

Steps to Reproduce:

1. Put the cursor somewhere.
2. Hold Ctrl+Shift then tap the left or right arrow keys.
3. Notice how the cursor selects at nonsensical stop points, like selecting the semi-colon along with the function call parentheses but not the function name, or the function name but not the parentheses, or other bizarre or logically-inconsistent selections like Notepad for Windows does... 
![image](https://user-images.githubusercontent.com/33667567/34626568-745df3b2-f21a-11e7-8b69-0f50f63f1f51.png)
4. You can generally test where something will select or the cursor will position just by holding Ctrl and tapping the left or right arrow keys.

I'm not sure how to make a gif of me demonstrating this, but if there's a way like I see in many issues posted here, please let me know.

Notepad++, PHPStorm, NetBeans, and Eclipse for instance have more sensible selection, wherein they will select what makes more sense to copy from a developer's or editor's perspective, and have better separation of selectable chunks (try it out yourself). The Windows way of selecting has been nonsensical forever, and defaulting to it is just as bad and I hope there's some solution or extension to adjust or fix this.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mccreeker** [comment]
Just a note so I'm not adding a new issue:

I noticed when I hit Ctrl+left, the cursor goes to the beginning of the word; if I hit Ctrl+right, the cursor goes to the end of the word, however in other interfaces like this browser form text box, the cursor instead goes to the beginning of the next word... which makes a lot more sense.

**Comment by devel0** [comment]
I noticed another issue about, consider follow code situation

```
await userManager.CreateAsync(...)
```

and now suppose you want to assign that to a variable

```
var identity = _
await userManager.CreateAsync(...)
```

*note* the insertion on line above and _ is where the cursor is

when you press DEL you got the below line to come up but with some addictional spaces

```
var identity = _               await userManager.CreateAsync(new User()
```

now if you hit CTRL+SHIFT+RIGHT the selection goes from the cursor to the "await" keyword **included**

What I suppose it should do is to select until the first work **excluded** in order to allow easy deletion of extra spaces without having to move cursor selection back

**selection wrong**
var identity = **x_       _xawait** userManager.CreateAsync(new User()

**selection expected**
var identity = **x_       _x**await userManager.CreateAsync(new User()

**Comment by mccreeker** [comment]
I did find a setting that helps at least with double-clicking text:

"editor.wordSeparators": " `~!@#%^&*()-=+[{]}\\|;:'\",.<>/?",

But this doesn't seem to affect holding Ctrl or Shift while tapping an arrow key... I'm not yet finding a setting to determine that, the cursor seems to follow Microsoft logic which is nonsensible.

**Comment by alexandrudima** [comment]
Our built-in word navigation commands are programming language agnostic and work by classifying characters into whitespace, word separators, and words. The word separators character class is defined via the user setting `editor.wordSeparators`. 

As a rule of thumb, possible word navigation stops are considered at the cursor location where character class changes. So, for the following, `/\` marks a possible word navigation stop:

```
 hello&&&*^(*&%world
/\   /\       /\   /\

 hello  world()
/\   /\/\   /\/\
``` 

Thos stops are programming language agnostic and can be configured solely via `editor.wordSeparators`. Now, the question is at which possible stops to actually stop. And here there are multiple possibilities.

This is what we ship with:
```
{ "key": "ctrl+right",            "command": "cursorWordEndRight",
                                     "when": "editorTextFocus" },
{ "key": "ctrl+shift+right",      "command": "cursorWordEndRightSelect",
                                     "when": "editorTextFocus" },
{ "key": "ctrl+left",             "command": "cursorWordStartLeft",
                                     "when": "editorTextFocus" },
{ "key": "ctrl+shift+left",       "command": "cursorWordStartLeftSelect",
                                     "when": "editorTextFocus" },
```

But you can also try these other ones by editing your `keybindings.json`:
```
// - cursorWordEndLeft
// - cursorWordEndLeftSelect
// - cursorWordStartRight
// - cursorWordStartRightSelect
```

It is always possible to create an extension (a very simple one) which implements the word navigation commands that you desire. 

Otherwise, if you have good specific ideas about how to improve the default logic, I am happy to hear them. What is it that makes, in your opinion, the other editors word navigation a lot better ?

**Comment by devel0** [comment]
Thanks for detailed informations,
I know that vscode is multi-language editor but visual studio but with the last one ctrl+left/right works as expected, so I wondering if changing default behavior of vscode for keybindings would break some expected cursor moving for other languages rather than C,C++,C#,Javascript where this behavior will work well or the point is that there is the need to find out how to implement the behavior through the expression that control the cursor editor movement.

**Comment by alexandrudima** [comment]
@devel0 To get VS-style Ctrl+Right, please edit your `keybindings.json` and add:

```
{ "key":"ctrl+right",       "command":"cursorWordStartRight",       "when":"editorTextFocus" }
{ "key":"ctrl+shift+right", "command":"cursorWordStartRightSelect", "when":"editorTextFocus" }
```

**Comment by devel0** [comment]
Many thanks, it works!

just for easy I report here how to apply it:
- File/Preferences/Keyboard shortcuts (**CTRL+K,CTRL+S**)
- click on **keybindings.json** link
- edit your customization on the right panel as follow

```json
// Place your key bindings in this file to overwrite the defaults
[
    {
        "key": "ctrl+right",
        "command": "cursorWordStartRight",
        "when": "editorTextFocus"
    },
    {
        "key": "ctrl+shift+right",
        "command": "cursorWordStartRightSelect",
        "when": "editorTextFocus"
    }
]
```

**Comment by alexandrudima** [comment]
Now that @devel0 is happy, 

@mccreeker 
> If you have good specific ideas about how to improve the default logic, I am happy to hear them. What is it that makes, in your opinion, the other editors word navigation a lot better ?

**Comment by brunobely** [comment]
@alexandrudima For me the issue with this is that the cursor stops before and after word separators like they were words themselves. Is there a way to remove that? Here is an example of how it currently works:

```js
|console.log(err)
console|.log(err) // moves to end of next word: 'console'
console.|log(err) // moves to end of next word: '.'? or beginning of 'log'
console.log|(err) // moves to end of next word: 'log'
console.log(|err) // moves to end of next word: '('? or beginning of 'err'
console.log(err|) // moves to end of next word: 'err'
console.log(err)| // moves to end of line
```

As you can see, it is not consistent with the keybinding "cursorWordEndRight" (unless word separators count as words (which they should not?). Here is an example of how it works in Sublime—and Chrome, and other macOS applications—(and how I'd like to set it up for VS Code):

```js
|console.log(err)
console|.log(err) // moves to end of next word: 'console'
console.log|(err) // moves to end of next word: 'log'
console.log(err|) // moves to end of next word: 'err'
console.log(err)| // moves to end of line
```
