### ISSUE TITLE
Editors do not restore icon until clicked when not having any changes

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#41210]
- VSCode Version: Code - 1.19.1 + Insiders 1.20.0-insider **[Unsupported]** (c4065a8ba5261456338f850a37e67732d98bf57a, 2018-01-05T08:06:27.790Z)
- OS Version: Windows_NT x64 10.0.16299

Steps to Reproduce:

1. `New Untitled File`
2. Change language to known for icon theme (`javascript`, for instance)
3. Go to another editor
4. Reload window
5. The icon for untitled file is not set

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
Underlying issue is that the only way how an icon can win over the default icon (the one you see for untitled) is, if a model is loaded with a specific mode that is different from the one determined by the resource. 

Since an untitled file that is not dirty is not loaded on startup, the model is also not active and as such, the icon will only be determined by the resource but not by the user choice from the previous session.
