### ISSUE TITLE
功能请求：Emmet 使用缩写包围增强

### ISSUE THREAD

**Issue by Linrstudio** [Microsoft/vscode#41213]
Emmet 使用缩写包围增强

希望记住上次输入的内容，并处于选中状态，这样，可以快速包围相同内容；

**Comment by ramya-rao-a** [comment]
Google translates the above to:

> Emmet uses abbreviation bracketing
I hope to remember the last input, and in the selected state, so that you can quickly surround the same content;

I am assuming that you are referring to the `Emmet: Wrap with abbreviation` command and expect it to remember the previous input.

If so, then this is tracked in #40096
