### ISSUE TITLE
vscode insider opening terminal in other window error

### ISSUE THREAD

**Issue by dooboolab** [Microsoft/vscode#41263]
- VSCode Version: VERSION 1.20.0-insider
- OS Version: OSX 10.13.2

Steps to Reproduce:

1. Open vscode.
2. Press command + shift + c
3. Then 'no provider for [object Object]' appears

Does this issue occur when all extensions are disabled?: Yes/No
Yes. Even with clean install. Before I didn't but in newer version it isn't working.

**Comment by Tyriar** [comment]
@isidorn I think you may have broken this with your refactor, I can reproduce on mac and linux.

**Comment by dooboolab** [comment]
Is this really fixed? The warning message has gone but termianl is still not opening in vscode-insider like original vscode.

**Comment by isidorn** [comment]
@dooboolab there still has not been an insiders version which contains this fix. It should be there in the next 24hrs

**Comment by Tyriar** [comment]
This is not fixed in the latest version as the behavior has changed.

Previously cmd+shift+c would open an external terminal at the _workspace root_ regardless of what is set in `terminal.explorerKind`.

Now it will open the terminal defined in `terminal.explorerKind` at the current file's path (like when right clicking on a file/folder in the explorer and opening from there).

We should change it back.

**Comment by dooboolab** [comment]
now [command 'workbench.command.terminal.openNativeConsole' not found]
appears after udpate when I pressed cmd+shift+c

**Comment by isidorn** [comment]
@dooboolab this error does not make much sense. If you open preferences > keyboard shortucts do you see 'workbench.command.terminal.openNativeConsole'? There shoult only be 'workbench.action.terminal.openNativeConsole'. We never had a .command in the id for this one

@Tyriar ok in order to have this proper I have actually split this in two commands. As before the `workbench.command.terminal.openNativeConsole` will always open the external terminal at root and introduced a new one `openInTerminal` which apears in context menus.
Feel free to tweak the second ID and feel free to change the strcture, for me it was the most natural to have two seperate commands. As they have differnt titles and do different things
