### ISSUE TITLE
Allow to open the same file in multiple editors of the same group

### ISSUE THREAD

**Issue by kristiandupont** [microsoft/vscode#41289]
I wish I could open the same file in multiple tabs. Basically, I want the same functionality as cmd+2 gives me, but without creating a split.

In another editor that I use, my workflow consists of this rather than splits or bookmarks. I "duplicate" the current view, scroll to the other place in the file that I want to inspect and to "go back", I just close the tab again. Once you are used to it, it's a very nice workflow.

Now, as far as I can tell, this is not really possible? I'll gladly create an extension if possible. I guess I could allow opening files with an additional query-parameter or something, effectively showing two copies of the same file. However, I worry that this would give me constant "this file was changed outside" dialogs which is not what I want -- I want the buffers synchronized the way splits are. 

Can someone help me in the right direction?

**Comment by cdmihai** [comment]
Or at least allow opening the same directory in multiple windows to workaround not being able to open the same file in multiple tabs / editors within the same window.

**Comment by cdmihai** [comment]
Sublime has this with *File -> New View Into File*

**Comment by jamesTbaker** [comment]
+1

**Comment by afroty** [comment]
+1

**Comment by DatStorm** [comment]
+1

**Comment by kouts** [comment]
+1 this is what keeps me switching over from Sublime

**Comment by BigSpitz** [comment]
+1 would be a great feature to have for sublime users

**Comment by fhdalikhan** [comment]
+1 this feature has kept me away from switching as well.

**Comment by KurumiSerori** [comment]
+1 tired of rolling up and down, also do not like the seperate view.

**Comment by tolisg** [comment]
+1

**Comment by cbeltrangomez84** [comment]
+1

**Comment by Relequestual** [comment]
For me, the benefit here is token highligting when clicking or double clicking a token. I want to see them at multiple places in the file without needing to scroll.

**Comment by engineerbaraazakariya** [comment]
I wish this feature is going to be done, so I can just use VSCode instead of using multiple editors, this feature is useful when I need to keep my cursor position and in the same time I need to check something in the end of the file without splitting the view and with having the full width of the screen for this edit in the other view on this file.

**Comment by nahuel** [comment]
+1 this is very, very useful in Emacs for editing big files, were you can make two (or more) "windows" display the same "buffer" (file), usually in different positions.

**Comment by vivdev** [comment]
+1 Need full horizontal width for both the editor windows

**Comment by DominikSerafin** [comment]
There is a workaround where you can open context menu of the file in the sidebar and use option `Select for Compare` and then open context menu again on the same file and use `Compare with Selected`.

This allows to open the same file in two separate tabs (without splitting editor). Changes between the tabs get synced, but unfortunately highlighting is only in the scope of a single tab. And as far as I know this only lets you to open the same file twice, no more.

**Comment by ultraGentle** [comment]
@bpasero Would a PR be welcome here?  If so, could you provide a pointer to likely starting points in the code base?  Not sure I'd have time, but I'd at least like to take a look.

**Comment by bpasero** [comment]
@ultraGentle please keep PRs to issues labeled "help wanted" or "good first issue". Thanks for understanding.

**Comment by ultraGentle** [comment]
@bpasero understood.  If at some point you reconsider "help wanted" on this issue, happy to look into expediting this feature.

**Comment by ultraGentle** [comment]
Re: @DominikSerafin 's workaround -- which is using the "select for compare" function to compare a file with itself: 

This process can be streamlined to a keyboard-only sequence by opening the command palette > compare active file with ... > up arrow to select current file > enter.

Then, once you've selected "inline view" (i.e. full width) once from the top-right menu in compare-view VSCode will default to that view next time.  

Since this is all command/keyboard based, I wonder if this could be turned into an mini-extension, or a macro in the existing extension [multi-command](https://marketplace.visualstudio.com/items?itemName=ryuta46.multi-command) . 

Still not ideal, but at least it's a muscle-memory friendly way of getting the same file full-screen in two separate tabs!

**Comment by believer-ufa** [comment]
+1 sometimes you need it

**Comment by Relequestual** [comment]
It's not going to get implemented right now, it seems.
To be honest, VSCode is amazing and let's try not to be too negative here. It's amazing that the team delivers at the same pace every release. Let's cut them some slack. 4.3k open issues must be crazy to try and handle. I would suspect that the response above, while from a bot, is the result of human action in another system.

Be nice, people =]

**Comment by NeonWizard** [comment]
This is a pretty core request, and doesn't have any bells and whistles like a lot of other feature requests have. This is one thing I used regularly in Sublime before switching over, and I mirror a lot of the sentiment that's been posted in here about this being added. I think this issue should be re-opened.

**Comment by lukaszpolowczyk** [comment]
Maybe it's worth trying to deal with WebView and CustomEditor?
https://code.visualstudio.com/api/extension-guides/webview
https://code.visualstudio.com/api/extension-guides/custom-editors

Or somehow salt the URI of the file to make VSCode think it's a separate file?

**Comment by alexchandel** [comment]
Please add `File -> New View Into File`, or `New View Into Workspace` if you can't support a single file.

**Comment by datdinhquoc** [comment]
Please add this feature, it's very useful to read the logic flow in a big long file. 

I'm using `right-click > Peek > Peek Definition` instead but just can't peek deeper (peek from peeked lines)

**Comment by aaly00** [comment]
+1

**Comment by Fdrph** [comment]
+1

**Comment by high-performance-hery** [comment]
Not sure if this is what's requested, but I can open the same file in different tabs by doing

* `Cmd + Shift + P` -> `Copy Path of Active File`
* `Cmd + P` -> `Ctrl + V` -> `Enter`

**Comment by lukaszpolowczyk** [comment]
@high-performance-hery What does `Cmd + P-> Ctrl + V-> Enter` do?

**Comment by high-performance-hery** [comment]
Sorry typo, it's `Cmd + V`.

so `Cmd + P`  (Search file) -> `Cmd + V` (Paste path) -> `Enter` (Go to path)

Will edit the above

**Comment by lukaszpolowczyk** [comment]
@high-performance-hery Tell us what commands are behind `Cmd + P-> Cmd + V`.
I have no such shortcuts.

And I don't know what a "Search file" is.

Ideally, record how you do it.

**Comment by extratype** [comment]
@high-performance-hery That's opening the same file. It does not open a new tab unless you're on a different tab group or window.

**Comment by high-performance-hery** [comment]
@extratype Good point, so then:

* Cmd + Shift + P -> Copy Path of Active File
* Cmd + 2 (opens new tab)
* Cmd + P -> Cmd + V -> Enter

Sorry it's a lot of muscle memory, so steps get lost in translation.

**Comment by lukaszpolowczyk** [comment]
@high-performance-hery `Cmd + 2` does not open a new tab.
This shortcut opens a new editor column.

**Comment by high-performance-hery** [comment]
@lukaszpolowczyk You're right, I used the wrong terminology, edited.

This should, as the title suggests (`Allow to open the same file in multiple editors of the same group`), open a new editor.

**Comment by KnIfER** [comment]
Shouldn't The title  be `Allow to open the same file in the same tab group`?

**Comment by lukaszpolowczyk** [comment]
A surprisingly simple workaround - "File: Open Active File in New Window":
Shortcut: `Ctrl + K O`.
Command: `workbench.action.files.showOpenedFileInNewWindow`

Imperfect because it's a bit slow, out of context and in a separate window, but it meets some of the needs. :D

**Comment by believer-ufa** [comment]
This is not a same group.... This is a new window, isn't it?

**Comment by lukaszpolowczyk** [comment]
@believer-ufa It meets the author's two basic points of the issue. The third does not meet it.
So that is just it.

I would also prefer in a new tab rather than a new window.
Is there any point in blocking this if the topic is on all sides done, just not in the way we need?

What can I do? It's always more than nothing.

**Comment by divinity76** [comment]
Fwiw, Eclipse also supports this. related SO post: https://stackoverflow.com/questions/73565512/visual-studio-code-how-to-open-the-same-file-in-multiple-tabs

**Comment by Clev7** [comment]
Is there a reason this cannot be implemented?

**Comment by divinity76** [comment]
workaround: make a symlink of the file you want opened twice: `ln -s file.c file2.c`  - then open both file.c and file2.c in vscode :) ... just remember to put your file2 in .git/info/exclude

**Comment by lukaszpolowczyk** [comment]
@divinity76 This is brilliant. There needs to be an extension to VSCode that creates, removes such symlinks automatically, and hides these symlinks from the VSCode explorer. :D

**Comment by iTrooz** [comment]
I understand why Microsoft employees may not have the time to work on this, but why is this not marked as 'help wanted' ?

**Comment by aladynjr** [comment]
+1

**Comment by rhanqtl** [comment]
+1

**Comment by aguynamedben** [comment]
+1 I wish I could view a file in a different vertical split without dealing with the creation of multiple tab groups

**Comment by gjsjohnmurray** [comment]
@aguynamedben are you aware of this feature?

https://code.visualstudio.com/updates/v1_61#_split-an-editor-without-creating-a-new-group

**Comment by aguynamedben** [comment]
@gjsjohnmurray I am aware of that command, but that's not what I want. That command only allows me to view **a single file** across two splits. I want to be able to recall any open file into any split without regard for tabs and tab groups.

What I want is:
* I can split my window visually into parts (i.e. "split" in VS Code, "window" in Emacs)
* I can view any open file in any split
* I'm not left with the mess of having a single file open many times across many tab groups

It seems that early on, VS Code "solved" the window splitting by using the Tab Groups feature. For users coming from Emacs or vi that don't care about tabs, this is an unsatisfactory solution that is now deeply embedded in VS Code. The solution is unsatisfactory because it's (a) based on mouse-first assumptions, (b) based on IDE-like assumptions, (c) creates an unnecessary hierarchical relationship between VS Code's UI and the way VS Code manages open files.

All I want to do is view any of my open files in any of my splits, without creating a mess of redundantly open files within tab groups I don't care about. In Emacs land, I would say "I want to be able to view any open buffer within any window". In VS Code land, I would say "I want to view any already-open file within any visual split".

Users attempting to indiscriminately view/recall any open file into any split are left with messy situations such as this:
<img width="620" alt="image" src="https://github.com/microsoft/vscode/assets/107841/692072ed-6dfb-471e-a501-521853bb3194">
<img width="256" alt="image" src="https://github.com/microsoft/vscode/assets/107841/8b6ba853-93c3-42b7-9e90-2245cac4462e">

I wish to live in a "don't-care-about-tabs" world but still want a way to split my editor's UI. However, the idea of tabs and tab groups seems deeply embedded into VS Code's ability to split windows, so I'm skeptical this is coming any time soon.

**The best way out of this I can think of is some kind of settings such as:**

```json
"workbench.editor.moveToCurrentTabGroupIfOpen": true,
```

This would be similar to `workbench.editor.revealIfOpen` but opening a file that's already open in another tab group would move that file into the current tab group. Then I could disable all tab-centric UIs in VS Code and indiscriminately open any file within any split and not end up with a mess of duplicate files open across many tab groups. I *think* this might be sufficient for most tab-haters.

[Working without Tabs](https://code.visualstudio.com/docs/getstarted/userinterface#_working-without-tabs) could say:

> If you're used to text-focused editors such as Emacs or vi and simply want to view any open file within any split without regard for tab or tab groups, set:
> 
> "workbench.editor.showTabs": true,
> "workbench.editor.revealIfOpen": true,
> "workbench.editor.moveToCurrentTabGroupIfOpen": true
> 
> With this setup, tabs and tab groups will still power which files are shown in which split, but that will be mostly irrelevant. You wont see tabs, and opening a file will "move" the open file into whatever tab group ("visual split") you're focused on, similar to Emacs buffers and frames.

This might be workable. I think the best thing to do, however, would be to revisit the entire model. "Open files" should not be so tied to the idea of displaying a tab to the user. And splitting the UI should not be so tied to the idea of tab groups.

I know there's a history with tabs, and this is a very pointed request, but thanks for considering any solution or workarounds! 😄 🙏

**Comment by aguynamedben** [comment]
FWIW the original request for this seems to be more simple: "Don't group tab" (https://github.com/microsoft/vscode/issues/49062) but the lineage of "mark as dupe" and locking threads seems to over-complicate the original request. Emacs/Vim users just don't care about tabs and don't want splitting being dependent on tabs/tab groups.

@rebornix said
> @rkuska If I understand correctly, you want to turn off Editor groups but you still want to split windows/tabs, right? If so we can't do that as our concept of window/tab management is different from Vim. @bpasero can give a better explanation.

Which seems accurate. It's just a different model (...that I hope can evolve).

**Comment by EliMadden** [comment]
It's ridiculous that VS Code doesn't support opening the same document in multiple tabs. The split-screen thing is cumbersome at best.

**Comment by divinity76** [comment]
@EliMadden the symlink hack mentioned about works great tho

**Comment by EliMadden** [comment]
> @EliMadden the symlink hack mentioned above works great tho

Too cumbersome, and I might forget to clean up. I just want VS Code to have the standard features of a modern editor.

**Comment by kristiandupont** [comment]
For anyone interested, this seems to be kindof possible now, if you create a split and drag one of them out into a separate window. Maybe there is an easier way, but this at least seems to work for me. Better than nothing.

**Comment by aguynamedben** [comment]
If you care about buffer-like flows within VS Code that are inspired by Emacs and vi/vim/neovim, please review @jonathanjameswatson PR that adds a `revealIfOpenInActiveGroup` option. There's a video demo. https://github.com/microsoft/vscode/pull/205442

Please also +1 in this issue: https://github.com/microsoft/vscode/issues/204942

The option allows users to automatically recall (move) an open Editor into the active Editor Group. This allows you to use Quick Find as a buffer switcher without undesirable opening files once-per-Editor Group. It basically allows you to not really worry about which file (Editor) is in which Editor Group at all.

**Comment by EliMadden** [comment]
> For anyone interested, this seems to be kindof possible now, if you create a split and drag one of them out into a separate window. Maybe there is an easier way, but this at least seems to work for me. Better than nothing.

I use that often but it's still not the same as having true separate tabs.

**Comment by lopugit** [comment]
I M P L E M E N T 🙌👏

**Comment by lopugit** [comment]
My thinking is a tab should be like a browser tab where you can set the URL of the tab and that's that, meaning you could easily have duplicates 🙏 

And even replace the url/path of a tab?!

**Comment by Iz9Shniperson** [comment]
UP

**Comment by sromeroi** [comment]
I expected to be able to right click in the tab name and select something like "Duplicate tab" or "Open in another tab"...

Being able to have different views of the same tab is very useful. Going back and forth with Ctrl+PgUp and Ctrl+PgDn between 2 or more positions in the same file (using tabs) is easier than using Bookmarks. With tabs, you have the cursor always focused in the exact position you need it on each "view", instead of being reset to the bookmark position on each change.

I'm simulating effect this right now by using File Compare between a file and itself, and switching to Inline View, but this only allows 2 tabs and this BASIC feature this should be native and as easy as Right-clicking on the tab and "duplicating" it. I've been missing this since I migrated to VSCode.

Thanks!

**Comment by martinlicht** [comment]
A desirable feature for VSCode that is still missing ✔️ 👏

**Comment by divinity76** [comment]
Worth re-posting: sym-linking and .git/info/exclude solves this problem:

Assuming you're using .cpp (c++)  fikes: First add
`*.ln.cpp` to the .git/info/exclude file, then make a symlink of file.cpp named file.ln.cpp
And voila, you can have 2 VSCode tabs of file.cpp 👍🏻

**Comment by lukaszpolowczyk** [comment]
@divinity76 It doesn't quite work: https://github.com/microsoft/vscode/issues/41289#issuecomment-1272126354

**Comment by divinity76** [comment]
@lukaszpolowczyk  those issues can largely be mitigated by going to settings.json and setting

```js
"files.autoSave": "onFocusChange",
```

**Comment by Jackenmen** [comment]
> Why is this request closed?

This is trippy... There's no "closed" event on the timeline, or at least I can't see one, and yet the PR appears as closed.

**Comment by mnemnion** [comment]
Incredible that a billion dollar company can't implement something this basic.

@microsoft, please, pull your head out of wherever you stuck it. There's no other editor which can't do this. You're embarrassing yourself.

**Comment by martinlicht** [comment]
It would be nice to learn why this is tagged as "out-of-scope", and within which scope this belongs.

**Comment by HonestTelevision** [comment]
Why was this closed? It would be very useful to have this feature.

**Comment by andrej-mihachou** [comment]
Could you please let us know, whether there are any plans on implementing this in future? This seems small yet the benefits are huge.

**Comment by keitaroforwork-create** [comment]
広い層から需要があることを示したいのであえて訳さずに書きます。
お願いします、この機能を実装してください。

**Comment by manuel-wagesreither** [comment]
+1

This feature is crucial. Working with files that are thousands of lines long is really tough otherwise.

Why should I suffer just because the author of the document I'm editing decided to store the entire codebase in one file?
