### ISSUE TITLE
Saving a file no longer keeps it open

### ISSUE THREAD

**Issue by Brocco** [Microsoft/vscode#41314]
- VSCode Version: 1.20.0-insider (b811600ecc57992a82a1f50ed9bf128065bc8787)
- OS Version: macOS High Sierra 10.13.2

Steps to Reproduce:

1. Open a file (A)
2. Make no changes
3. Save file (cmd + s)
4. Open another file (B)

expected: B opens and A remains open
actual: B opens and A closes
Note: this is a change to previous behavior

Does this issue occur when all extensions are disabled?: Yes/No
Yes, still occurs

**Comment by bpasero** [comment]
@isidorn this looks like a regression from your refactoring. in [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/electron-browser/fileCommands.ts#L147) we pin the editor if no resource is provided but it looks like the resource is an empty object that is passed in. this seems to be originating from this weird rule (that I never understood) in [keybindings service](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/keybinding/common/abstractKeybindingService.ts#L165). 

I fear all the commands you introduced need a check for `URI.isURI()` to work properly now. I would do this check from the commands though and not from the various helper functions because otherwise it is totally unclear why this check is needed in the first place :-/

**Comment by Brocco** [comment]
FYI, this seems to have regressed again, should I open a new issue?

**Comment by isidorn** [comment]
@Brocco thanks for letting us know. However this was fixed on friday and should appear in the next insiders release.
Here's that issue https://github.com/Microsoft/vscode/issues/41841
