### ISSUE TITLE
Mouse middle click pasting doesn't work within the integrated terminal

### ISSUE THREAD

**Issue by zmingxie** [Microsoft/vscode#41354]
In a traditional terminal window, mouse middle click should paste the selected block of text into the current cursor position. This is not happening in the VS Code integrated terminal. 

- VSCode Version:  1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba / x64)
- OS Version: macOS Sierra 10.12.6 

Steps to Reproduce:

1. Launch Integrated Terminal
2. Drag your mouse to select a block of text from the terminal 
3. Try to use the mouse middle click to paste the selected text
4. Nothing happens

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
This is a Linux thing not macOS, see https://superuser.com/a/423227. It works on Linux.

**Comment by Tyriar** [comment]
Also another answer mentions it works in the terminal, but it's a feature that's scoped to the terminal window and is not the norm for mac apps.

**Comment by zmingxie** [comment]
I understand this is a linux thing. However, would you guys consider adding this since both macOS built-in Terminal and iTerm2 support this?

As a user, I expect the VS code integrated terminal works the same as the default terminal on mac.

**Comment by Tyriar** [comment]
Since we're an editor this is more a general feature that should apply to the whole window for our case. I don't think there would be enough users to warrant the effort, the feature loses a lot if you can only use it in a single window. I recommend trying out `terminal.integrated.rightClickCopyPaste` instead which changes right click to copy when there is a selection and paste when not.
