### ISSUE TITLE
VS Code suggests installing mssql extension when people have MySQL installed, but it only works with SQL Server

### ISSUE THREAD

**Issue by bergamin** [microsoft/vscode#41368]
I have installed VS Code a few days ago in my personal PC and I have MySQL installed in it.

VS Code suggested me to install the [vscode-mssql](https://github.com/Microsoft/vscode-mssql) extension for that reason, but [vscode-mssql does not support MySQL](https://github.com/Microsoft/vscode-mssql/issues/1049).

I guess there was some kind of misunderstanding when adding database extensions to the suggestions...

Thanks a lot!

**Comment by ramya-rao-a** [comment]
@bergamin Did you see the recommendation for this extension in a pop up (the notification pop up that appears at the top of the VS Code window) or you only saw this recommendations in the extensions viewlet in the side bar?

**Comment by bergamin** [comment]
@ramya-rao-a, I don't remember now it the suggestion was shown right after first start, but trying to reproduce it now, I opened an SQL file in it and it first suggests the extension on a popup based on the filetype, but then, going to the suggestions and in the extension page inside VSCode, it says it is suggested because I have MySQL.

Here is a screenshot:

![pngtemp](https://user-images.githubusercontent.com/14339291/34805308-906419bc-f664-11e7-8b4c-a66ef21aff9c.png)

**Comment by florianmonfort** [comment]
Hi,

Re-opening this since now I got the same suggestion from VSCode but only just because I was trying to run .sql files, but it did not see that I was in fact using MySQL and therefore kept on suggesting that I install the extension.

Being a noob I spent a lot of time trying to connect to MySQL using the extension until finally I gave up and days later say on this thread that actually MySQL is not supported -_-. Big bummer.

Here is what VSCode gives as suggestion when opening those SQL files:

![image](https://user-images.githubusercontent.com/1446429/40708022-e69371e2-6424-11e8-8edd-88e0e2113441.png)

**Comment by ramya-rao-a** [comment]
cc @chrisdias @seanmcbreen on why we suggest the `mssql` extension when `.sql` files are opened.

**Comment by chrisdias** [comment]
The mssql extension handles syntax colorization for .sql file types.  From its `package.json`:  

``` json
    "languages": [
      {
        "id": "sql",
        "extensions": [
          ".sql"
        ],
        "aliases": [
          "SQL"
        ],
        "configuration": "./syntaxes/sql.configuration.json"
      }
    ],
```

@florianmonfort there is a MySQL extension for VS Code here: https://marketplace.visualstudio.com/items?itemName=formulahendry.vscode-mysql

It looks like that one will let you run MySQL queries.

**Comment by florianmonfort** [comment]
@chrisdias I tried this one, and I'm using it currently, but it doesn't seem to do as much

**Comment by ramya-rao-a** [comment]
@chrisdias Syntax highlighting for sql files comes from the built in [sql extension](https://github.com/Microsoft/vscode/blob/master/extensions/sql/package.json).

**Comment by florianmonfort** [comment]
So... Yeah it would be great to have in deed an extension that works really well with MySQL. As far as I know it's a pretty common DBMS. Either bring support via mssql extension or create another dedicated extension... I don't know what would be best.

**Comment by AresAndy** [comment]
Main point is: _do not default to MS SQL just because the file extension is .sql_
It almost seems like a commercial move considering MS SQL is a product of the same company who gave birth to VScode: Microsoft. And even if that is not the case, newcomers might get the impression that VScode does not support MySQL or other DBMSs while that is technically not true. _But all you got to do is to look for the proper extension.._ True, but you're recommending the _wrong_ extension for it anyway.

Apart from this little pet peeve of mine, I also think that syntax between the two systems is not totally compatible, so one should be able to specify language binding like:
`something.mssql` -> MS SQL
`something.mysql` -> MySQL
`something.pgsql` -> Postgres

...And so forth, right?

**Comment by bergamin** [comment]
@AresAndy I personally don't see the suggestion on the filetype to be that big of a problem. In my point of view it is a legitimate marketing move.

The problem I reported is regarding it suggesting mssql because it detected I have MySQL installed. That yes confuses people into thinking mssql supports MySQL when it doesn't.

Since it seems it is possible to check whether there is MySQL, SQL Server or Oracle installed, I would first check which ones are installed and suggest an extension (or more) accordingly.

If it can't detect any of them, then suggest mssql based on filetype.

@florianmonfort I agree with you. We like how mssql works and would love to see it implemented for other databases.

So either add to this extension, or create new ones for the other major databases with the same functionality this one has.

**Comment by ramya-rao-a** [comment]
@chrisdias I agree with @bergamin 

The mssql extension is being recommended both when a sql file is opened and when the mysql executable is found. We should either remove the latter or replace it with recommendation for the mysql extension.

**Comment by AresAndy** [comment]
@bergamin I don't think that VScode detects a mysql binary in your program folder, therefore recommends the mssql extension, because that did not happen to me on 3 different PCs across 2 OSs, Windows and Arch Linux. All it does is binds any .sql file to mssql syntax. While a legit marketing move, it's quite cringy. Let's bind all .xml files to SOAP requests no matter what the file prelude says while we're at it, right?

It's definitely wrong, and there should be a way of telling: no, this is not mssql and i do not intend to install it just because. Also the syntax is not 100% compatible, like C syntax is not to C#, as an example.

**Comment by bergamin** [comment]
@AresAndy, check my screenshot up there and the commit associated to this issue. VSCode clearly detected I have MySQL installed.

But sure, we should also be able to disable file type suggestions on the file types we already have what we want, even if not in VSCode. If there isn't any issue on this yet, do it. Makes sense.

About the SQL language highlighting, I agree. The built-in syntax highlighting should let you choose which database you are working with, and the extension/s could as well switch it to match the database being connected to.

**Comment by leecolarelli** [comment]
I too have a modal window telling me to install mssql every time I have a .sql file open, even though they are MySQL files.

![image](https://user-images.githubusercontent.com/8512204/61441129-dd73da80-a93c-11e9-9e88-0caca60bb77e.png)

I would also love some good MySQL support. None of the third party extensions are very good, and the best one has several bugs which make it unusable for me. It's a real shame because its the one thing i can find about VS Code which i do not like.

**Comment by chrisdias** [comment]
The root problem is that we want to suggest an extension when we see a `.sql` file, but we can't tell if its SQL Server or MySQL, so we will get it wrong for some percentage. The best course of action might be to simply remove the "important" recommendation so that you are not prompted every time you open a `.sql` file. Instead we can leave in a passive recommendation based on the fact that you've opened a `.sql` file, and recommend both the MS SQL extension and a couple of others that would help with MySQL.

**Comment by chrisdias** [comment]
fixed

**Comment by chrisdias** [comment]
I might add the mssql important recommendation back in.  you can always click the gear and choose "Don't Show Again"

![image](https://user-images.githubusercontent.com/1487073/61975219-658d5c00-af9d-11e9-8ec6-2a13bafcbbaa.png)

**Comment by chrisdias** [comment]
based on feedback, I have reverted the change to remove the "important" [SQL Server](https://marketplace.visualstudio.com/items?itemName=ms-mssql.mssql) recommendation for for `.sql` files.
 
with my previous fix, we will still "passively" recommend [vscode-database](https://marketplace.visualstudio.com/items?itemName=bajdzis.vscode-database) and [SQL Tools](https://marketplace.visualstudio.com/items?itemName=mtxr.sqltools) when you open a `.sql` files or if mysql or postgres are on the path.

This strikes a better balance between suggesting the sql extension and ensuring extensions that support mysql are also recommended. As noted above, it is possible to click on the gear and choose `Don't Show Again` if the prompt for the SQL extension is incorrect.
