### ISSUE TITLE
File>Open Recent should not include workspaces that have been deleted on disk

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#41391]
VS Live Share creates temporary workspaces that are getting removed at the end of a sharing session. 
Currently these temporary workspaces show up in the File>Open Recent menu:

![image](https://user-images.githubusercontent.com/172399/34769075-0f4fd850-f5fd-11e7-9743-50fb6f41f534.png)

Suggestion is to filter out deleted workspaces from the menu.

**Comment by bpasero** [comment]
@egamma I would argue that the fact that Live Share creates temporary workspaces is a workaround for a missing UX story in VS Code. I would not expect (as a user) to suddenly be in workspace context as soon as I opt-in to sharing code with someone because this is an operation that is not revertible (e.g. you cannot go back to single-folder mode from there) unless Live Share would actually open the folder again at the end of the session (which would result in ugly window reload).

So the question to me is: what is the scenario for how to enter and leave sharing sessions?

A related request (https://github.com/Microsoft/vscode/issues/35407) asks for extensions being able to add workspace folders to the current set. This would enable Live Share to create "Untitled" workspaces which would go away once you close the Window. Still, that does not solve the issue of how to "leave" workspace mode after forced to enter it when starting a live share session.

/cc @stevencl @chrisdias

**Comment by bpasero** [comment]
Also @EricJizbaMSFT for input

**Comment by bpasero** [comment]
@EricJizbaMSFT I added a new command `vscode.removeFromRecentlyOpened` with a single argument `path` that can be used to remove the temporary workspace from the recently opened list.

**Comment by EricJizbaMSFT** [comment]
Thanks @bpasero but I'm not really interested in this scenario. Chris described our exact scenario here: https://github.com/Microsoft/vscode/issues/35407#issuecomment-357315681

**Comment by bpasero** [comment]
@EricJizbaMSFT yeah sorry, I confused this request with you somehow, but it is actually for Live Sharing scenarios.

**Comment by bpasero** [comment]
**Verify:** try out that https://github.com/Microsoft/vscode/issues/41391#issuecomment-357194075 works.

**Comment by davidkpiano** [comment]
Verified that it works!
