### ISSUE TITLE
Highlight calls for python

### ISSUE THREAD

**Issue by santagada** [Microsoft/vscode#41402]
Here is the same request for js, I think this should be extended to all languages, or at least to Python:

https://github.com/Microsoft/vscode/issues/3886

**Comment by aeschli** [comment]
Each language is different and based on a different grammar. So sepaparet issues need to be filed.
I suggest to focus on Python here. Please add more details:
- the theme that you are using
- a small code sample to reproduce
- a screenshot that shows the problem
- the result you expect

**Comment by santagada** [comment]
Why, that seems backwards, all languages have function/method calls, why not do it for all languages? And the result is exactly the same as JS, thats why I didn't add any pictures or info, its all there.

**Comment by aeschli** [comment]
Syntax highlighting is based on TextMate grammars. Each language has its own grammar. The grammars are coming from various authors in the community.
Unfortunately, TextMate grammars are not very strictly specified, so there are differences. Also all themes are differently implemented.
Each case needs to be looked at. Maybe it's a bug with the theme, maybe something can be improved with a particular grammar. That's why we need to proceed as outlined.
If you could add the specifics as listed in my previous comment, that would be great.

**Comment by santagada** [comment]
In which theme it is broken: all
In which language it doesn't work: python, c/c++, bash, bat files

code:
```python
bar = 1

def foo():
    pass

foo()
bar += 1
```
how it looks in vscode:
![vscode](https://user-images.githubusercontent.com/225897/35170988-6aecc22e-fd62-11e7-8ea6-488e4db36dcd.jpeg)

how it looks in pycharm (which works):
![pycharm](https://user-images.githubusercontent.com/225897/35170965-476e1d16-fd62-11e7-9a70-0aee8fbcf594.jpeg)


Same ticket in pycharm for an older version, and the same ticket for vscode for javascript:
https://youtrack.jetbrains.com/issue/PY-11418#u=1508017249053
https://github.com/Microsoft/vscode/issues/3886

**Comment by aeschli** [comment]
I created https://github.com/MagicStack/MagicPython/issues/127 against the Python grammar.
