### ISSUE TITLE
Ctrl + Backspace delete in text editor.

### ISSUE THREAD

**Issue by MDavidMR** [Microsoft/vscode#41416]
- VSCode Version: 1.19.2
- OS Version: 16299.192

Steps to Reproduce:

1. Open Quick Find (`Ctrl` + `F` my configuration)
2. Write some word to find.
3. `Ctrl `+ `Backspace` to delete the word before cursor in _Find_ textbox.
4. VS Code deletes the word before cursor in text editor not in _Find_ textbox although Find textbox has the focus.

Does this issue occur when all extensions are disabled?: No

Excuse my bad English :(

**Comment by jVanZwieten** [comment]
Same problem, extremely annoying part of an otherwise great editing experience.

**Comment by alexandrudima** [comment]
@MDavidMR @jVanZwieten I cannot reproduce with a default installation of VSCode.
I believe an extension is binding `ctrl+backspace` in a bad way (without using the condition `editorTextFocus`). Can you please use the keybindings UI (ctrl+k ctrl+s) to go to `keybindings.json` and find the definition for `ctrl+backspace`.

You can also disable all extensions to check if this reproduces.

```
{ "key": "ctrl+backspace",           "command": "deleteWordLeft",
                                     "when": "editorTextFocus && !editorReadonly" },
```

**Comment by jVanZwieten** [comment]
@alexandrudima thanks for looking into this. I tried reproducing this on a fresh install of VSCode (with no extensions; I normally work with VSCode-insiders, so a nice benefit is my normal VSCode is totally clean), and I didn't reproduce it.

I looked into my keybindings, and saw the difference:
VSCode (fresh):
![vscodebackspace](https://user-images.githubusercontent.com/16783024/36438795-ed4457de-1638-11e8-9772-2878f73f2119.PNG)

VSCode-insiders
![vscodeinsidersbackspace](https://user-images.githubusercontent.com/16783024/36438800-f150c402-1638-11e8-8334-6bfd2f4b991e.PNG)

So "deleteWordStartLeft" seems to be the culprit, or at least the difference here. Even though it lists "Source" as "Default", I had a hunch it was caused by Visual Studio Keymap. Installed it on my fresh VSCode and indeed confirmed the keybinding added and witnessed the erroneous behavior. Then found [Visual Studio Keymap Ctrl+Backspace/Ctrl+Delete keys within commit message are intercepted by extension in main editor #24](https://github.com/rebornix/vscode-vs-keybindings/issues/24).
