### ISSUE TITLE
vuejs-pb 

### ISSUE THREAD

**Issue by alcrabie** [Microsoft/vscode#41456]
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:55:03.538Z)
- OS Version: Windows_NT x64 6.2.9200
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
halcyon-vscode|bri|0.0.7
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vue-peek|dar|1.0.2
wpy-beautify|doi|2.0.10
vscode-npm-script|eg2|0.3.3
auto-close-tag|for|0.5.5
auto-rename-tag|for|0.0.15
vue-snippets-js-html-pug-razor|heb|0.0.3
vue-snippets|hol|0.1.5
vue|liu|0.1.5
vuejs-extension-pack|mub|0.3.0
vetur|oct|0.11.5
smile-icons|one|2.1.1
vuehelper|oys|0.1.0
material-icon-theme|PKi|3.2.1
vue-vscode-snippets|sdr|1.3.0
JavaScriptSnippets|xab|1.5.0

(9 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by yume-chan** [comment]
What's your problem and steps to reproduce?

**Comment by jay-bricksoft** [comment]
For the sake of completeness, please provide the following information: (as @yume-chan stated)

- Title: the title of this issue is not really saying anything about an error / issue / request

- (Please also include your themes in the list of extensions.)
- Steps to reproduce: you did not provide any information.
- Reproduces without extensions: Yes/No (either one)

**Comment by alcrabie** [comment]
sory i was in error i dont know waht hapen but now evry think is ok

2018-01-12 8:08 GMT+01:00 Jay Bricksoft <notifications@github.com>:
