### ISSUE TITLE
Visual Studio Code adding 'Unexpected character' automatically

### ISSUE THREAD

**Issue by delowar64** [Microsoft/vscode#41453]
- VSCode Version: 1.19.2 (1.19.2)
- OS Version: OSX High Sierra

When I am trying to save a file, VsCode adding 'Unexpected character' automatically. I removed these character and try to save again, but every time VsCode adding same character in my file. (check attached image & video.)

![hghja](https://user-images.githubusercontent.com/17360543/34810913-2ccbdaca-f6c8-11e7-8f16-4e85bc890f93.png)

## Video:
[![Video](https://img.youtube.com/vi/gTh4tjzc4To/0.jpg)](https://www.youtube.com/watch?v=gTh4tjzc4To)

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.
