### ISSUE TITLE
Keybindings editor header problems

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#41558]
1. It changes on hover the same exact way as rows
Expected for it to stay the same
2. On click the 1st row is selected
Expected for it to do nothing (or sort columns..., the point is - the current behavior is mostly confusing)

**Comment by sandy081** [comment]
@usernamehw Not sure if I understand the issue. Can you please elaborate it
- Steps to reproduce or
- Any screenshots or
- A gif 

would be helpful

**Comment by usernamehw** [comment]
Keybindings-editor header: `.keybindings-list-header`
![keybinddings_header](https://user-images.githubusercontent.com/9638156/34966160-c2f78fee-fa6a-11e7-8db4-7c32cc81d0dd.png)

Hover applies to it:
![hover](https://user-images.githubusercontent.com/9638156/34966173-f06eeeb8-fa6a-11e7-8184-3ac6ec35d162.gif)

Click on header selects the first row:
![click](https://user-images.githubusercontent.com/9638156/34966180-fe41e1a8-fa6a-11e7-986f-49aa2f995080.gif)

**Comment by sandy081** [comment]
@usernamehw Thanks for the explanation. 

> It changes on hover the same exact way as rows
Expected for it to stay the same

Agreed.

> On click the 1st row is selected
Expected for it to do nothing (or sort columns..., the point is - the current behavior is mostly confusing)

I see your point. It was done because when user types `down arrow` from search box, focus goes to first row (not header).

Happy to take a PR for this.

**Comment by sandy081** [comment]
There is a PR exists already
