### ISSUE TITLE
Regression: please revert JS icon color to blue

### ISSUE THREAD

**Issue by vvs** [Microsoft/vscode#41569]
<ul>
	<li>VSCode Version: Code - Insiders 1.20.0-insider (ca023a700f35212071dfe9544272719cbbf80e4c, 2018-01-12T05:14:50.541Z)</li>
	<li>OS Version: Windows_NT x64 10.0.16299</li>
</ul>

I've upgraded to the latest insiders build and the javascript file icons are ugly (yellow). Please revert back to the good old blue ones.

Similar bug was filed for `.ts` files and was fixed: #40691

**Comment by aeschli** [comment]
The seti theme is generated from the [original seti theme](https://github.com/jesseweed/seti-ui). The color of the JavaScript icon is yellow there: 
https://github.com/jesseweed/seti-ui/blob/16dc5ccb7db6329f99c20c75fc7b536965765a96/styles/components/icons/mapping.less#L151

It was a bug that previously we didn't use yellow but blue. It happends because we simply took the last coloror used the the mode:https://github.com/jesseweed/seti-ui/blob/16dc5ccb7db6329f99c20c75fc7b536965765a96/styles/components/icons/mapping.less#L461

Now we respect colors for each extension as defined.
We have no intention to have our own variant of the theme.

**Comment by vvs** [comment]
Thank you for the explanation, @aeschli!
Not a big problem, I'd just keep my own custom icon theme then.
