### ISSUE TITLE
Breakpoint not shown

### ISSUE THREAD

**Issue by sekhuat** [Microsoft/vscode#41604]
Hi,

       VSCode "sometimes" didn't show the breakpoints in the editor as shown in the image below. Although the breakpoints didn't show up, the breakpoints will still hit when the code is executed.

![image](https://user-images.githubusercontent.com/13288516/34926163-b66a4168-f9e8-11e7-9806-51fbb95e3872.png)

        This issue happens randomly. When it happened I will close VSCode and restart it and most of the time it will work properly.

- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:49:04.682Z)
- OS Version: Darwin x64 17.3.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
debugger-for-chrome|msj|4.0.0
cordova-tools|vsm|1.3.2

---

Steps to Reproduce:

Happened randomly, hard to reproduce.

**Comment by isidorn** [comment]
Can't reallyt do anything wihtout steps.
The problem is probably that the brekapoints gets removed by the debug adapter (it gets placed to some other location).

In case you reproduce this let us know and we will reopen this issue. Also make sure to check if you need to start debugging to reproduce this
Thanks
