### ISSUE TITLE
Code constantly prompts to install recommended extension which are all intsalled

### ISSUE THREAD

**Issue by bateau** [Microsoft/vscode#41674]
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:55:03.538Z)
- OS Version: Windows_NT x64 10.0.17074
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|0.10.14
prettier-vscode|esb|1.1.0
sort-typescript-imports|mic|1.4.1
debugger-for-chrome|msj|4.0.0

---

Steps to Reproduce:

1. Just open VS Code in git repo root directory.
2. Get prompted about recommended extensions, click "install"
3. Get message that all recommended extensions are already installed.  Why did it prompt in the first place then?

Reproduces without extensions: No - since it's related to extensions

**Comment by ramya-rao-a** [comment]
@bateau Can you share screenshots as well as the repo you were working on when this happened?

**Comment by rrousselGit** [comment]
I managed to reproduce this.
The problem is due to having a uppercase in the extension name ( Orta.vscode-jest for example)


If we add ` "Orta.vscode-jest"` in the extension.json, the popin will recommended extension popin will always show up. Followed by a "Recommended extensions are already installed"

Renaming it to lowercase remove the popin.

**Comment by ramya-rao-a** [comment]
@rrousselGit This has been fixed in the latest [insiders](https://code.visualstudio.com/insiders)
