### ISSUE TITLE
Different file watching strategies here and there

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#41700]
So, there is file watching for files/folders inside a workspace folder. But then there is also `IFileService#watchFileChanges/unwatchFileChanges`, `extfs#watch`, and node's `fs#watch`. We use them all and I wonder if we can consolidate them? The `extfs#watch` seems to be an improved `fs#watch` but I am unsure about the watching in the file service and how that compares to the rest. Esp wrt remote file systems, the out-of-band watching is interesting... Do we have that only because our default watching is about folders only? Can that be replaces with `extfs#watch`?

**Comment by bpasero** [comment]
@jrieken since file watching is broken + expensive, we currently do not expose the workspace watching (chokidar, C#, nsfw) to anyone, we just set it up and let it run. We have https://github.com/Microsoft/vscode/issues/3025 asking to make this API to watch also other folders.

Since that does not cover all use cases, I added `IFileService#watchFileChanges/unwatchFileChanges` specifically to watch single files (not folders). We use this for example when you open a file that is not part of the workspace to detect changes to it. I would argue that the remote file service should support these changes as well and report them properly so that an open editor updates when the content changes (if possible). 

`IFileService#watchFileChanges/unwatchFileChanges` is a bit smarter compared to `extfs.watch` with regards to file deletes: by default in node.js when a watched file is deleted, the watching stops. But we continue to watch the file if it was only momentarily deleted and then comes back ("atomic save"). 

`extfs.watch()` is basically `fs.watch()` with the NFC normalisation needed on macOS for file paths. This is to ensure that e.g. an umlaut like "`ö`" in the path is using the same codepoint as JS strings do, otherwise `===` checks would fail. In general we should always use the methods in `extfs` over anything defined in `fs` module. 

Are you asking to push the special handling of deleted files in `IFileService#watchFileChanges/unwatchFileChanges` down to `extfs.watch`?

**Comment by jrieken** [comment]
> Are you asking to push the special handling of deleted files in IFileService#watchFileChanges/unwatchFileChanges down to extfs.watch?

Not really, just trying to figure out how stuff works and why it was done in certain ways. Goal is to have one-world when it comes to API and it sound like a model where a potential file event consumer first subscribes (to a file or folder) to events isn't very far fetched. Even for us, why do we listen for all workspace folder events e.g. when not even showing the explorer.

**Comment by bpasero** [comment]
Yeah, a model where subscribers explicitly state what to watch would be better. That requires that the watcher library supports ad-hoc add/remove of file patterns.

**Comment by bpasero** [comment]
The right way forward is to let everyone use `IFileService`, especially with regards to remote file systems. This requires a new file watcher that is capable of ad-hoc subscriptions to file paths. Until we have that, the solution we have today (sometimes using file service, sometimes using extfs) is OK.
