### ISSUE TITLE
editor.autoIndent incorrectly indents comments

### ISSUE THREAD

**Issue by Zarel** [microsoft/vscode#41720]
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:49:04.682Z)
- OS Version: Darwin x64 17.3.0 (macOS High Sierra 10.13.2)
- Extensions: Extensions are disabled
---

Steps to Reproduce:

1. Make sure `editor.autoIndent = true` in settings (it's enabled by default)

2. Create a new JavaScript file, fill it as so:

```js
	async function pipeStream(taskId, stream) {
		let value, done;
		while (({value, done} = await stream.next(), !done)) {
			// @ts-ignore Guaranteed to be a child process
			process.send(`${taskId}\nPUSH\n${value}`);
		}
		process.send(`${taskId}\nEND`);
	}
```

3. Triple-click (or otherwise select) and copy the entire line

```
			// @ts-ignore Guaranteed to be a child process
```

(including indentation and trailing linebreak)

4. Press Down Down (or otherwise put your cursor before):

```
|		process.send(`${taskId}\nEND`);
```

5. Paste.

Expected result:

```js
	async function pipeStream(taskId, stream) {
		let value, done;
		while (({value, done} = await stream.next(), !done)) {
			// @ts-ignore Guaranteed to be a child process
			process.send(`${taskId}\nPUSH\n${value}`);
		}
		// @ts-ignore Guaranteed to be a child process
		process.send(`${taskId}\nEND`);
	}
```

Actual result:

```js
	async function pipeStream(taskId, stream) {
		let value, done;
		while (({value, done} = await stream.next(), !done)) {
			// @ts-ignore Guaranteed to be a child process
			process.send(`${taskId}\nPUSH\n${value}`);
		}
			// @ts-ignore Guaranteed to be a child process
			process.send(`${taskId}\nEND`);
	}
```

(Which I can't imagine anyone would consider a desirable result...)

**Comment by rebornix** [comment]
This is due to the limited architecture (regex based indentation rules and only support limited code styles), we may want to consider using formatters if they exist for indenation adjustment (if interested, we can discuss in https://github.com/microsoft/vscode/issues/19847).

For this particular issue, if the indentation rules are leading to more trouble than having no auto indent, you can set `editor.autoIndent` to `advanced` to disable the regex based indentation adjustment. As we don't have an easy good-enough fix for it, we close it for now and explore better solutions through issues like (https://github.com/microsoft/vscode/issues/19847 and https://github.com/microsoft/vscode/issues/34621).
