### ISSUE TITLE
Introduce a useful ID for a workspace folder

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#41779]
Today a workspace folder is defined by an absolute or relative "path". The path must be unique (but by using symbolic links a workspace can reference the same folder multiple times).
In addition a workspace can have an optional name, but this name is not required to be unique within a workspace.

Neither of these attributes represent a useful ID for referring to a workspace folder in a robust way:
- the "path" is unique but not stable because if the location of the folder is changed, its ID changes.
- the "name" is not unique (but probably a bit more stable than the path).

Possible options:
- introduce a new workspace folder ID that is independent from "name" and "path" (but painful to use),
- introduce a workspace folder ID based on some combination of "name" and "path" that is unique, stable, and easy to use.

I'd prefer option 2.

**Comment by bpasero** [comment]
> the "path" is unique but not stable because if the location of the folder is changed, its ID changes.

@weinand I would argue the opposite: the `path` property is a suitable ID even if the workspace file is moved around because it is used literally.

Best to demonstrate with 2 examples:

```
{
	"folders": [
		{
			"path": "ticino-playground"
		}
	],
	"launch": {
		"target": ${rootPath:ticino-playground}
	}
}
```

In this example, the path is a relative one and used in the variable. But it does not matter if the file is moved around because the variable is using the relative value. 

```
{
	"folders": [
		{
			"path": "/User/bpasero/ticino-playground"
		}
	],
	"launch": {
		"target": ${rootPath:/User/bpasero/ticino-playground}
	}
}
```

In this example the path is absolute and as such it has to be used absolute in the configuration file as well. Again, it does not matter if you move the file around.

**Comment by bpasero** [comment]
@weinand ping

**Comment by weinand** [comment]
We are now using the "name" of a folder as its ID (and if this is not unique we bail out).
Closing.
