### ISSUE TITLE
Current debug line is sometimes not highlighted correctly

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#41774]
- Debug anything normally
- Do a continue
- Sometimes, immediately after a continue, see that the current line is either not highlighted at all, or is highlighted green instead of yellow

When I click on that frame in the callstack, it becomes highlighted correctly.

I don't have better repro steps - if you have never seen this, tell me where to set a breakpoint.

**Comment by isidorn** [comment]
I have never seen this. The only way I can see something like this is using a recursive function like the following (place breakpoint on recursive call line. Then after continuing you can see the line very quickly turn green since that is expected due to the fact how we fetch frames and how the same line is also top stack frame and the one beneath it.

```javascript
function fib(n) {
    if (n < 5) {
        return 1;
    }

    return fib(n - 1) + fib(n - 2);
}

fib(60);
```

In order to investigate better I suggest to put breakpoints [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/browser/debugEditorModelManager.ts#L113) for decoration computations

Apart from that, an interesting place would be [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/common/debugModel.ts#L822) if you think this is connected with how we first fetch the top stack frame and only then the rest.

**Comment by roblourens** [comment]
Where is the code where we select the first stack frame? I notice that when the decoration isn't drawn at all, it has opened the correct file and scrolled to the right line, but the frame is not selected in the call stack.

**Comment by isidorn** [comment]
https://github.com/Microsoft/vscode/blob/isidorn/multiRootLaunch/src/vs/workbench/parts/debug/electron-browser/debugService.ts#L538
https://github.com/Microsoft/vscode/blob/isidorn/multiRootLaunch/src/vs/workbench/parts/debug/electron-browser/debugService.ts#L250

**Comment by roblourens** [comment]
I haven't been able to repro this while debugging. But I see it several times a day. Have you never seen it?

I did find better repro steps that may be related - 

- Start debugging
- Hide the sidebar, or show a different viewlet besides Debug
- Step 
- The current line is never highlighted

These steps repro 100% of the time.

This may be new of the past few days, because I think I would have noticed it earlier. But the original issue definitely reproes sometimes when the debug viewlet is active.

**Comment by isidorn** [comment]
@roblourens great catch and great repro steps.
The issue was coming from the fact that the call stack view was reacting on its own change of selected stack frame which caused too many times for the focused stack frame to change.
I also updated the call stack view to not do too much if not visible
