### ISSUE TITLE
Provide a setting to configure the multi selection modifier key 

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#41799]
With the new multi selection support a CTRL-Click no longer opens an editor to the side, but adds the selected item to the selection. Opening an editor to the side is now done using ALT-Click. 

We should support a backward compatibility setting for users that prefer the old CTRL-Click to open an editor to the side. This is similar to the `editor.multiCursorModifier`.

**Comment by bpasero** [comment]
I added a new setting `"workbench.multiSelectModifier": "alt" | "ctrlCmd"` which controls the key to be used to add to the selection (if multi select is supported). The default will be `ctrlCmd`, but when you set it to `alt` you get back to be able to use `ctrlCmd` to “open to side”

@joaomoreno I had to [touch the List widget](https://github.com/Microsoft/vscode/commit/60b1e7ed841764e3f28801b094fb27bcdd78e896#diff-01d05394919c7e105fca87c6f5b8d2d9) for this a little bit because the multi-select handling is within the widget. I am allowing to set a new `IListOptions.useAltAsMultiSelectModifier` property down to the mouse controller to control this. 

@isidorn fyi
