### ISSUE TITLE
No auto list new file in folder

### ISSUE THREAD

**Issue by tuanakka0101** [Microsoft/vscode#41794]
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:57:21.071Z)
- OS Version: Linux x64 4.13.0-26-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-devskim|MS-|0.2.0
vscode-docker|Pet|0.0.23
vscode-eslint|dba|1.4.4
tslint|eg2|1.0.24
vscode-great-icons|emm|2.1.22
php-debug|fel|1.12.1
php-intellisense|fel|2.2.5
php-pack|fel|1.0.1
mssql|ms-|1.3.0
python|ms-|0.9.1
cpptools|ms-|0.14.6
csharp|ms-|1.13.1
js-atom-grammar|ms-|0.1.14
java|red|0.17.0
vscode-java-debug|vsc|0.5.0
vscode-java-pack|vsc|0.2.0
vscode-proto3|zxh|0.1.2

(1 theme extensions excluded)

---

Steps to Reproduce:

1. I create new file by text editor outside VSCode in a folder which already added to workspace
2. Back to VS Code, open workspace and folder, I don't see that file, I have to close and open VSCode to see it.

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment]
@tuanakka0101 there is also a "Refresh" action in the explorer:

![image](https://user-images.githubusercontent.com/900690/35084989-e9b29d46-fc26-11e7-8f10-448534d684ba.png)

**Comment by Dominik-K** [comment]
duplicates #28432

**Comment by Dominik-K** [comment]
You're using a [multi-root workspace](https://code.visualstudio.com/updates/v1_18#_support-for-multi-root-workspaces), right? Do you have many folders & files inside the workspace?

Can you run `code-insiders --verbose abc.code-workspace` and paste all lines having `IPC Library: Watcher` in it, please?

**Comment by bpasero** [comment]
@tuanakka0101 
VS Code is using different file watching strategies depending on your OS and your setup. 

**First thing to check:**
* [ ] I verified that the issue still reproduces in our insiders version (https://code.visualstudio.com/insiders/)
* [ ] I verified that this issue is happening outside of a `node_modules` folder. Our file watcher ignores this folder!

**To find out more about this issue, please first answer this:**
* [ ] What OS are you on
* [ ] Does this happen from an empty workspace, a single-folder workspace or a multi-root workspace?
* [ ] Do you have `files.useExperimentalFileWatcher: true` configured in settings?
* [ ] What is your configured `files.watcherExclude` setting?

**Then please answer the following depending on your setup:**
* [ ] It reproduces with any folder or workspace you open
* [ ] The files/folders you open are on your local disk and not on a network share nor a UNC drive
* [ ] The files/folders you open are not behind a symbolic link
* [ ] The folder(s) opened use the exact same casing as they are on disk
* [ ] It reproduces when I make a change to the file from another VS Code window (either from the editor or the file explorer)

**Then please attach the output of our development console**
* run `code --verbose` from the command line
* perform the action that causes you to not see the file change in VS Code
* attach the output from the console (`Help` > `Toggle Developer Tools` > `Console`)

Thanks for taking the time to fill out this questionnaire.
