### ISSUE TITLE
Changing between recents folder will reload the window twice

### ISSUE THREAD

**Issue by Nikodermus** [Microsoft/vscode#41839]
Changing between folders with CTRL+R in Mac will cause to sometimes show the folder content and after a small dellay to reload all the window again. Issue started with November version 2.

- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:49:04.682Z)
- OS Version: Darwin x64 17.3.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|1.2.0
beautify|Hoo|1.1.1
vscode-wakatime|Wak|1.1.22
vscode-eslint|dba|1.4.4
githistory|don|0.3.2
tslint|eg2|1.0.24
path-autocomplete|ion|1.8.1
Angular2|joh|2.11.2
vscode-gutter-preview|kis|0.12.2
vscode-todo-parser|min|1.9.1
Ruby|reb|0.15.0
vscode-icons|rob|7.19.0
vscode-sass-format|sas|1.1.2
javascript-typescript|sou|0.0.5
guides|spy|0.9.1
language-stylus|sys|1.8.0
bootstrap-3-snippets|wcw|0.1.0

Steps to Reproduce:

1. Open VSCode in full-screen
2. Open folder with terminal process running and some open files
3. Hit CTRL+R and change to a folder that had opened files

Does this issue occur when all extensions are disabled?: No

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.
