### ISSUE TITLE
Generated tasks.json is incomplete - only has last 2 tasks from gulpfile

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#4183]
Related to #4019

- VSCode Version: 18ebb4a4f5491af7b16e91e42fc36410bbb2e4d7
- OS Version: El Capitan

Steps to Reproduce:

1. vscode repo, delete `tasks.json`
2. Configure task runner > gulp
3. Notice the generated `tasks.json` only has `watch-extensions-build`and `test` task, while all the other tasks from the `gulpfile.js` are ignored

```
{
	// See http://go.microsoft.com/fwlink/?LinkId=733558
	// for the documentation about the tasks.json format
	"version": "0.1.0",
	"command": "gulp",
	"isShellCommand": true,
	"args": [
		"--no-color"
	],
	"tasks": [
		{
			"taskName": "watch-extensions-build",
			"args": [],
			"isBuildCommand": true,
			"isWatching": false,
			"problemMatcher": [
				"$lessCompile",
				"$tsc",
				"$jshint"
			]
		},
		{
			"taskName": "test",
			"args": [],
			"isTestCommand": true
		}
	]
}
```

**Comment by dbaeumer** [comment]
This is on purpose. The tasks.json only augments the gulp file with additional information it doesn't wrap all targets. Otherwise you would have stuff in there like
```json
{
    "taskName":"another task"
}
```

However when you use the picker to execute the task we still show all tasks from the gulp file (as long as the command in the tasks.json is gulp).

**Comment by dbaeumer** [comment]
![capture](https://cloud.githubusercontent.com/assets/1931590/13757841/b51905d4-ea26-11e5-9197-8c9649554ce3.png)
