### ISSUE TITLE
transient issue with deb-package

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#4187]
* on ubuntu 14.04
* clicked the deb-package link on the builds page
* confirmed defaults
* then I got a message about our package being bad (didn't happen on second try)

![screen shot 2016-03-14 at 12 40 53](https://cloud.githubusercontent.com/assets/1794099/13750067/3d71d42e-ea04-11e5-8524-34847964c4f8.png)

@Tyriar Maybe this rings a bell or it was just an broken download...

**Comment by Tyriar** [comment]
@jrieken I've seen the bad quality issue before but for a different reason. Considering it only happened one time I would assume Firefox was playing with the download file at that point which is why it couldn't access it or something. Seems to me more like either an OS or Firefox-level issue so closing.
