### ISSUE TITLE
when editor.mouseWheelScrollSensitivity is set to a relative small number, scrolling to bottom does not work when scrolling speed is relative low

### ISSUE THREAD

**Issue by xc1427** [Microsoft/vscode#41912]
- VSCode Version:  Version 1.19.2 (1.19.2) 490ef761b76b3f3b3832eff7a588aac891e5fe80 and Version 1.20.0-insider (1.20.0-insider) d21e6a3e388897a2250cb10ae897b6481e0bd61d
- OS Version: macOS High Sierra 10.13.1 (17B1003)

Steps to Reproduce:

1. set `editor.mouseWheelScrollSensitivity`: 0.5,
2. Try to scroll the screen to bottom with Touchpad at very slow speed. (If the scroll direction on the mac is set to Natural, this means to move finger to top)
3. The screen does not move. It seems that there is a minimum speed  to trigger scrolling.
4. I did not test all sensitivities but it seems we have this issue when the value < 0.8.

Does this issue occur when all extensions are disabled?: Yes.

Expected behavior:

- The screen moves despite of the `mouseWheelScrollSensitivity` with a relative small number set on.
- Actually, scrolling the screen to top **does behave as expected**, so this implies that the issue is **not as designed**.

**Comment by alexandrudima** [comment]
Yes, picking a small value for `editor.mouseWheelScrollSensitivity` and using the touchpad can result in getting "stuck". This option is meant to be used by folks having a physical mouse with a scroll wheel...

Here is what I have observed and my explanation:

### When using a physical mouse with a scroll wheel
* one flick of the scroll wheel typically generates one mouse wheel event
* this event contains `deltaX`/`deltaY` properties, which represent how many pixels the OS/Chromium deems appropriate to scroll.
* typically, one scroll wheel flick would result in a `deltaY` of 30.
* ... and that is too slow for some folks.
* that's why we've added `editor.mouseWheelScrollSensitivity`, as a multiplier we apply to the incoming `deltaX` and `deltaY`.
* please note that someone suffering from this will suffer from it in all applications of the OS, and most OSes have configuration options to control this.

### When using a touhpad
* one flick on the touchpad typically generates **tens** of mouse wheel events.
* they will give `deltaY` as a series of : [20, 20, 20, 18.3, 15.4, 10, 5, 3, 2, 1], etc.
* these values are the output of some math functions which the OS deems appropriate.
* **we cannot differentiate touchpads from mouse wheels**
* we therefore also use `editor.mouseWheelScrollSensitivity` as a multiplier.
* if you barely touch the touchpad, and it creates events with the values: [1, 1, 1, ...]
* multiplying with the configured value might result in a value below <0.5
* when scrolling, we don't allow the editor to sit at floating point scrollTop or scrollLeft. we force that `scrollTop` and `scrollLeft` are integers.
* i.e. it is therefore possible, if using a small value for `editor.mouseWheelScrollSensitivity` to get stuck.
