### ISSUE TITLE
Replace workbench.customDebugRequest command usages with official API

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#41945]
- Run Chrome or Node debugging
- Use the "Toggle skipping this file" command from the call stack
- See `Error: command 'workbench.customDebugRequest' not found` error in the devtools console

I will switch to the official API, but node, node2, and Chrome still reference this so was it supposed to be removed? 

cc @weinand

**Comment by isidorn** [comment]
@roblourens yes this command was removed as specified 2 milestones ago in the release notes https://code.visualstudio.com/updates/v1_18#_debug-api-updates

Since no other debug author complained for 3 months I suggest that you simply update the node and chrome adapters to use the [`customRequest`](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L6156)

**Comment by roblourens** [comment]
Fixed in all debuggers
