### ISSUE TITLE
Repeated words in the task creation quick box

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#4196]
Testing #4019 

![image](https://cloud.githubusercontent.com/assets/172399/13751917/a8dbc866-ea0c-11e5-82fc-27b332344991.png)

- Suggest to extract the prefix Creates a task.json to the message in the input box, e.g., `Pick a task template to create a 'task.json' configuration. 

- The other repeated text is 'if x is available with auto detection'. 

- Suggest to rename 'External Command' to 'Generic Command' to make it clear that this one for others. 

// @chrisdias

**Comment by dbaeumer** [comment]
I picked external command since the command is not generic. I would be Generic Task.json which I ddn't like either. At the end it is launching an external command.

**Comment by dbaeumer** [comment]
@egamma what is your suggestion with The other repeated text is 'if x is available with auto detection'.

**Comment by chrisdias** [comment]
Debug has "Select Environment" as the prompt, i suggest we are similar with tasks: "Select Task".

The list should be trimmed down, i don't see the need for Jake nor 4 different TypeScript tasks.   Also, the list should be sorted somewhat alphabetically.   

grunt
gulp
MSBuild
.NET Core
TypeScript
Other 

Do we even need the descriptions?  do they add any real value?

**Comment by egamma** [comment]
:+1:  on removing the descriptions, but on informing the user when auto detection took place and what was auto detected.

>Debug has "Select Environment" as the prompt, i suggest we are similar with tasks: "Select Task".

If we want to be consistent with Debug I'd suggest "Select Build Environment".

**Comment by dbaeumer** [comment]
It is neither selecting a 'task' nor a 'build environment'. I still think 'Pick a task template' is the right phrase.

We can't remove Jake since we would not be possible anymore to run the Jake auto detection :-). If we remove Jake we need a 'Auto detect template' entry.

**Comment by dbaeumer** [comment]
And which TypeScript compile do you want to keep. The one with tsconfig, watch or single file.

**Comment by chrisdias** [comment]
@dbaeumer 

* TypeScript build

i would keep the tsconfig one because that is probably the most useful and common with TypeScript (having a tsconfig.json) and i would update the docs to deeply discuss the various scenarios for typescript compile.  

also, i would change showOutput to "always" because it helps people understand what is going on.  When they become familiar with the system they can change showOutput to "never" or "silent".

* Jake

My point is that the usage data of Jake is so low compared to gulp and grunt, it isn't worth having in this list.  In Feb we had about 150 instances of jake compared to 33k for gulp and 15k for grunt.

**Comment by dbaeumer** [comment]
The dialog looks 'bad' without any description due to the amount of white space. 

![capture](https://cloud.githubusercontent.com/assets/1931590/13817029/e747ce8a-eb90-11e5-8de0-1a9da50c788c.png)

**Comment by dbaeumer** [comment]
With the Jake argument I am pretty sure we need to remove MSBuild as well :-). So I actually propose to leave Jake and MSBuild in.

**Comment by dbaeumer** [comment]
I also opt to have two TypeScript one for tsconfig and one for watch for discoverability.

**Comment by dbaeumer** [comment]
Here is what I have right now:
![capture](https://cloud.githubusercontent.com/assets/1931590/13817832/fb3fc2a0-eb93-11e5-8f15-7d734d1f240f.png)

If you feel strong about further changes please comment here or got directly to https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/tasks/common/taskTemplates.ts and make the necessary changes.

**Comment by chrisdias** [comment]
The descriptions do not add any value except in the TypeScript differentiation, which I again suggest we remove and update the docs with various scenarios. The same argument (discoverability) could be made for gulp watch tasks too.  Also, without descriptions it matches the launch.json creation experience for debugging.

The number of .sln workspaces which are therefore MSBuild based projects is in the same ballpark (thousands) as gulp.  Again, Jake is a fraction of a percentage, lets remove it.

**Comment by chrisdias** [comment]
i'll make a PR.

**Comment by dbaeumer** [comment]
As said we will loose auto detection of Jake if we remove it. And I doubt that the .sln workspace all use task :-). I also agree that the description doesn't add a lot of value but it makes the dialog look nicer. Why do we have to optimize for the number of entries in the list. I have for example an request to add an entry for npm as well. And if we allow extension to contribute to it we don't have control over the list anyways. 

Don't get me wrong I am in for a good in the box expierence. I simply don't see why making the list as short as possible and moving everything to the docs helps with that.

**Comment by chrisdias** [comment]
At the end of the day what I want to do is help customers be successful while keeping the product consistent and streamlined.  I'm making a couple of assertions to achieve this goal.

First, we have clear data that indicates jake usage is extremely low. So low in fact that the presence of Jake in the list only adds what I will call "noise" to the list. It doesn't help the vast majority of people be successful and it doesn't keep the product streamlined. This issue is about removing Jake from the list, but I assert we should remove the jake detection logic from the code base as well.  More code means more bug opportunities (does anyone test for Jake, are there new versions, do we have to fix bugs here, etc.) and more download and code loading size.  Every bit counts.

Second, I don't see having multiple TypeScript entries provides enough value to keep all of them in the list. The difference between each type of TypeScript task is very subtle, in some cases it is simply an additional parameter. Having documentation that discusses why you would want one or the other option would be much more valuable than having four subtly different entries in the list, which is why I suggested to update the docs. Also, we teach rather than do, making people more successful over the long term. Having four TypeScript entries complicates the list. Why do we have four TypeScript entries and not multiple variations for gulp?  Again, I am trying to keep the product consistent and streamlined.

To help close this I suggest we establish a principle which says there is one entry for a task type (e.g. grunt, gulp, npm, etc.). Any variations on how to set up tasks for these should be covered in the documentation. Following this model would keep the list clean (one entry per type) and would also support adding npm to the list, as is being requested.

**Comment by dbaeumer** [comment]
I made a pass with Erich (he had wishes as well) and here is what the final result looks like:

- no Jake
- no description if superfluous
- Sorted except External command
- External command renamed to Others and moved to the end

![capture](https://cloud.githubusercontent.com/assets/1931590/13843529/7b0c5de0-ec34-11e5-8d8f-cba7bd47ed4a.png)

Hope that makes everybody happy.
