### ISSUE TITLE
Source control view: staging area repeatedly displayed at bottom

### ISSUE THREAD

**Issue by MichaelGrupp** [Microsoft/vscode#41970]
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:57:21.071Z)
- OS Version: Linux x64 4.13.0-26-generic
- Extensions: Extensions are disabled
---

Steps to Reproduce:

1. Open a workspace with Git repositories, switch to the Source Control view and "pull" the staging area up (see step_1.jpg)
2. Switch to Explorer view, then go back to Source Control view: the staging area is shown at the bottom again (see step_2.jpg)
[step_1](https://user-images.githubusercontent.com/8985495/35225375-6d6ff28c-ff88-11e7-9abb-8aaad61f0baf.jpg)
[step_2](https://user-images.githubusercontent.com/8985495/35225374-6d520e20-ff88-11e7-8bb9-4c178daa9686.jpg)

This can be a bit annoying, especially when the list of files in the staging area is high.

**Comment by mitchellsimoens** [comment]
This has been bugging me quite a bit also especially since I mainly work on a 43" 4k monitor... Commenting to just show a shrunken down screenshot really:

<img width="196" alt="vscode source control panels" src="https://user-images.githubusercontent.com/325473/35447969-020c3f44-0287-11e8-80b2-13e3c34b9c40.png">

**Comment by ShayBox** [comment]
Very annoying
![image](https://user-images.githubusercontent.com/9505196/35488210-d69b0930-0452-11e8-80b5-98ca0ef9d696.png)
