### ISSUE TITLE
VSC Crashed when validating the syntax for PHP

### ISSUE THREAD

**Issue by meletisf** [Microsoft/vscode#420]
Hello, today as i was writing code i came across a bug which causes the editor to crash.

That happens in the latest VSC version which introduces extensions and the new PHP linter.

**Bug Replication**
The bug apears when there is a syntax error, then when i fix it the autocomplete dies and after a while the editor crashes.

To make it easier to understand it i also made a video on youtube explaining how i did it.

+ Link: https://www.youtube.com/watch?v=_xzR2Cf0mRI

**Comment by knackrack615** [comment]
Hello, i have exactly the same problem

Running on Windows 10 Pro with VS 0.10.1

**Comment by kc9eye** [comment]
Yes same thing here. Editors pretty usless for PHP at this point. Hangs, and has to be killed when working on PHP.

**Comment by marcintokarski** [comment]
I have the same problem. It is posible to disable validate php synax?

**Comment by marcintokarski** [comment]
This bug is fixed in: https://github.com/Microsoft/vscode/commit/c89555baaf13352799a9299a284ff261d3d68c34

I have changed 45th line in "vs_code_location\Microsoft VS Code\resources\app\extensions\php\out\features\signatureHelpProvider.js" from this.lineNumber = 0; to this.lineNumber = -1;

and it's work fine

**Comment by lesmo** [comment]
Solution referenced by @marcintokarski solves this issue for me.

**Comment by bpasero** [comment]
We fixed this issue in #160
