### ISSUE TITLE
Support for Custom CompletionItemKind Icons

### ISSUE THREAD

**Issue by rionmonster** [Microsoft/vscode#4201]
I'm currently working on an extension for VS Code to add the functionality of another extension of mine that was created for Visual Studio: [Glyphfriend](https://github.com/Rionmonster/Glyphfriend). When I began working on this, I noticed that the `CompletionItemKinds` enum only seems to support a predefined set of values (e.g. `Value`,`Text`,`File`, etc.). 

Is there any way to currently set this glyph to a specific file? Or is there another preferred way that I should look at implementing this type of behavior (either via a different type of provider or through somehow extending the existing `CompletionItemKind` class)?

Any feedback or recommendations would be appreciated.

**Comment by sandyarmstrong** [comment]
As a workaround, you can override these CSS rules: https://github.com/Microsoft/vscode/blob/11b139d/src/vs/editor/contrib/suggest/browser/suggest.css#L116-L145

**Comment by jrieken** [comment]
@sandyarmstrong which is very bad suggestion since there is no guarantee from our side (1) if that file will always exist at the location, (2) what class names etc we are going to use, (3) how our build pipeline inlines, rewrites icons, and (4) that the app signing will eventually think about that. 

Everyone is always invited to help out (hello PRs) and it will be a lot more rewarding that a hack like that.

**Comment by sandyarmstrong** [comment]
@jrieken in retrospect, I was thinking from the context of a consumer of monaco-editor, not a VS Code extension author. You're absolutely right.

**Comment by jrieken** [comment]
Agreed - for the editor it's a slightly different game.

**Comment by jrieken** [comment]
For the sake of making it easier to write and share language servers, esp wrt the language service protocol we will stick to a pre-defined set of icons and kinds.
