### ISSUE TITLE
Focus border needs padding and alignment

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#42054]
### Issue Type
Bug

### Description

Pls see attached screenshot.

![screen shot 2018-01-23 at 11 12 46 am](https://user-images.githubusercontent.com/4674940/35295668-8ce2dfde-002e-11e8-85dc-9868575e236a.png)

The focus border needs left and bottom padding. 

### VS Code Info

VS Code version: Code - Insiders 1.20.0-insider (60440c72461e96893766bce73d7bdf1f5136a19f, 2018-01-23T07:11:12.714Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (3.79GB free)|
|Process Argv|/Users/kmaetzel/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_786624|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by kieferrm** [comment]
We could also look into not setting the focus border the whole element but only for the twisty. That would feel more in line with other experiences.

**Comment by RMacfarlane** [comment]
In the explorer and debug viewlets, focus on section headers is on the entire element instead of just the twisty, so I think it would be more consistent to do that. How's this?
![reporter focus border](https://user-images.githubusercontent.com/3672607/35304080-20e64ee0-0049-11e8-944e-0b3b6f54fd03.png)
