### ISSUE TITLE
Colored Output window content contains "Zero Width Spaces" when copied

### ISSUE THREAD

**Issue by dallonf** [Microsoft/vscode#42128]
- VSCode Version: v1.19.2
- OS Version: macOS 10.12.6

Steps to Reproduce:

These steps involve the use of [Quokka](https://quokkajs.com/) - the issue may exist with other extensions that provide colored output, but these are the repro steps that I've seen in everyday usage.

I did also report the issue to the Quokka team first (https://github.com/wallabyjs/quokka/issues/151), but they don't see a solution.

For context, Quokka is an extension that evaluates JavaScript in a live scratchpad environment, showing the results of `console.log` calls both right next to the line of code that called it, and in the VS Code "Output" window with a stack trace.

1. Install Quokka
2. Open a new Quokka JavaScript tab
3. Write some code that logs a value, and breaks down the characters. For example:

```javascript
// comments represent Quokka inline output
const myString = 'abcd';
console.log(myString); // abcd
console.log([...myString]); // [ 'a', 'b', 'c', 'd' ]
console.log([...myString].map(c => c.charCodeAt(0))); // [ 97, 98, 99, 100 ]
```

4. Copy the first log from the Output window - it should just look like "abcd"
5. Paste that value into some similar code that breaks down the characters:

```javascript
const pastedString = '​​​​​abcd​​​​​';
console.log([...pastedString]); // [ '', '', '', '', '', 'a', 'b', 'c', 'd', '', '', '', '', '' ]
console.log([...pastedString].map(c => c.charCodeAt(0))) // [ 8203, 8203, 8203, 8203, 8203, 97, 98, 99, 100, 8203, 8203, 8203, 8203, 8203 ]
```

Notice that there are several Unicode 8203 ("Zero Width Space") characters on either end of the pasted value. 

I would not expect these (annoyingly invisible) characters to enter my clipboard.

Here is a gif that hopefully makes the process a bit clearer:

![quokka-vs-code-8203](https://user-images.githubusercontent.com/346300/35338200-e4b5f49e-00e2-11e8-950f-342a6879f7da.gif)

Does this issue occur when all extensions are disabled?: N/A; the only repro steps I'm aware of involve the explicit use of an extension.

**Comment by dallonf** [comment]
I would request that this be reopened, as I _have_ filed an issue with the extension maintainers, as linked in the issue body, but I'll link it again for clarity: https://github.com/wallabyjs/quokka/issues/151

The maintainers of the extension seem to believe that this is a limitation of VS Code.

**Comment by isidorn** [comment]
@dallonf can you also reproduce this for regular output (for example git). I think not, because I do not see this.
Thus the extension should not append zero width space characters to the output channel.

**Comment by dallonf** [comment]
Is there a flow in normal, unextended VS Code where Git (or any system) outputs _colored_ text to the Output window? The colored text in Quokka seems to be the root cause here.

If there is, I can give it a check. if only Quokka's colored text contains these characters, then it's an obviously it's an issue specific to Quokka.

**Comment by isidorn** [comment]
@dallonf do you know how Quokka is coloring their text? Do they use decorations or ansi characters or their own text mate syntax?
Yeah in vscode insiders we have added colors via text mate syntax to all our logs (though we should first check how Quokka does it). Maybe you include somebody from their team here

**Comment by dallonf** [comment]
@ArtemGovorov can you chime in?

**Comment by ArtemGovorov** [comment]
@isidorn Hi, Quokka developer here.
We use our own language for the output with `.tmLanguage` grammar. Because the output is not a formal language, but some arbitrary text that needs to be coloured in some places, we just use zero width space characters in the grammar to let VS Code how to highlight/color certain regions.

Is there a better (and theme changes friendly) way to color the output? the only alternative I can think of is using `#TextEditor.setDecorations`, but it requires an access to an instance of the editor (of the output channel) and AFAIK the instance of the editor is not exposed anywhere in the API.

**Comment by isidorn** [comment]
@ArtemGovorov I think setDecoartions and a tmLanugage grammer are thee way to go here. But you answered this particular issue just now, the extension is adding ezro widht space characters.

@alexandrudima or @sandy081 can correct me if I am wrong here.

**Comment by ArtemGovorov** [comment]
> I think setDecoartions and a tmLanugage grammer are thee way to go here. But you answered this particular issue just now, the extension is adding ezro widht space characters.

Yes, because using a custom grammar is the only way (we found) to colorize the arbitrary output. The issue/limitation still remains - there's no easy way to colorize an arbitrary output without some tricky grammars.

> `setDecoartions`

Can you please paste an example or point to the right direction on how to use it for an **output channel**? `TextEditor.setDecorations` requires an instance of an editor, how to get an instance of an output channel editor?

**Comment by dallonf** [comment]
It's possible a new issue (as a feature request to allow extensions a way to output colored text without zero width spaces or other hacks) would be in order, as the OP of this issue definitely does seem to be a Quokka-specific problem, which might distract from having a useful conversation on how to resolve it.

**Comment by alexandrudima** [comment]
We don't have a good story for arbitrary output coloring.

Today, the output editor is colored through tokenization using TM grammars (mostly by accident, i.e. the output buffers behave the same like all other editor buffers in our system). But that is where similarities end; the output editor is not exposed as an editor on the extension host API, so there is no `setDecorations` API available, as there is no editor instance available. 

Output editors are not exposed in the API because we thought we would like to reserve the option to implement them with something else than a code editor in the future. i.e. perhaps something that doesn't support all the APIs that editors have. I always thought we might add at one point a "log viewer", where we can assume that the file on disk only gets appended and where it is safe to not hold on to the entire file in memory, and once we'd have one of those, we could use it for the output view.

Now, for what I can recommend... Perhaps the output has reached its limit. It isn't a log or an output of a process (like running something in the terminal); now it is used as a programming companion of sorts. Run a test, get to see some output, interact with the output, etc... I can recommend what we have: editors, web views, explorer trees, or otherwise you can upvote something like https://github.com/Microsoft/vscode/issues/3220
