### ISSUE TITLE
Unable to edit user settings in VC mac

### ISSUE THREAD

**Issue by irshad365** [Microsoft/vscode#42214]
- VSCode Version: 7.3.3 MAC
- OS Version: Sierra 10.12.6

There is no way to edit user settings. unable to do anything mentioned in this link
[https://code.visualstudio.com/docs/getstarted/settings](https://code.visualstudio.com/docs/getstarted/settings)

**Comment by mjbvz** [comment]
Please provide steps to reproduce the problem. A gif of what is going wrong may also be helpful

**Comment by irshad365** [comment]
oh man!!!! thats what i am asking too. can you please give me steps to open&edit user settings??

i am trying to add `"workbench.editor.showTabs": false ` this line to my `VS Mac 7.3.3. `

**Comment by mjbvz** [comment]
Please see this guide for some tips on filing a bug report or question: https://github.com/Microsoft/vscode/blob/master/CONTRIBUTING.md#writing-good-bug-reports-and-feature-requests

Basically, please describe:

* What you are trying to do
* Precise steps detailing how you are trying to do it
* What the expected behavior was after following those steps
* What the actual behavior was

**Comment by irshad365** [comment]
seriously!!! why are you answering like a BOT?? I know you understood my question. if you don't know the answer or if you are not willing to help, say it directly.

**Comment by mjbvz** [comment]
Please just answer the questions. This is not a general QA forum but I'm trying to help anyways. And I can't do that unless you can clearly describe what your issue is
