### ISSUE TITLE
windows 10 x64 tasks.json workspaceFolder is not resolved properly

### ISSUE THREAD

**Issue by saichaitanyaeruvaram** [Microsoft/vscode#42228]
My **workspaceFolder** is **D:\ws** .. tasks.json it resolves to **D:ws**
However, it works correctly in launch.json for debug .. ${workspaceFolder} resolves to D:\ws

VSCode Version: 19.2
OS Version: Windows 10 64 bit
Does this issue occur when all extensions are disabled?: Yes

tasks.json
`{  `
`    "version": "2.0.0",  `
`    "tasks": [  `
`        {  `
`            "type": "shell",  `
`            "command": "echo ${workspaceFolder}",  `
`            "group": {  `
`                "kind": "build",  `
`                "isDefault": true  `
`            }`  
`        }  `
`    ]  `
`}  `

Steps to Reproduce:

1. Add the above to tasks.json
2. Run the task using Ctr+Shift+B
3. Below is the output on my pc  
`> Executing task: echo d:\ws <`  
`d:ws`  
`Terminal will be reused by tasks, press any key to close it.`  

My **workspaceFolder** is **D:\ws** .. tasks.json it resolves to **D:ws**
However, it works correctly in launch.json for debug .. ${workspaceFolder} resolves to D:\ws

**Comment by dbaeumer** [comment]
This works for me without problems.

Which shell are you using ?

**Comment by dbaeumer** [comment]
<img width="360" alt="capture" src="https://user-images.githubusercontent.com/1931590/36843167-5b1907ac-1d4e-11e8-86c4-b8858c1e13c6.png">

**Comment by jyavenard** [comment]
The issue is that $workspaceFolder correctly uses \ characters on Windows, but when used in combination with config like tasks.json, a single \ disappear. It needs to be made a double \\.

Any suggestions on how to do so?

**Comment by dbaeumer** [comment]
As said I was not able to reproduce this. See https://github.com/Microsoft/vscode/issues/42228#issuecomment-369566790.

There might be an issue if this is \w. Let me check this.

**Comment by dbaeumer** [comment]
Even on root with c:\ws not able to reproduce.

<img width="746" alt="capture" src="https://user-images.githubusercontent.com/1931590/37201342-b439e254-2387-11e8-8ece-224ec47d29c1.png">

Any additional information to reproduce this.

Tested on latest insider.

**Comment by jyavenard** [comment]
I can reproduce it easily with the C++ extension tool 's tasks.json

    "command": "${workspaceRoot}/mach",
    "windows": {
      "command": "\"\\mozilla-build\\start-shell.bat c:/Users/jyavenard/Work/Mozilla/mozilla-central/mach\""
    },

I can't do:
      "command": "\\mozilla-build\\start-shell.bat ${workspaceFolder}/mach"

I must use:
      "command": "\\mozilla-build\\start-shell.bat c:/Users/jyavenard/Work/Mozilla/mozilla-central/mach"

when using ${workspaceFolder} I get an error that
c:usersjyavenardworkmozillamozilla-central/mach doesn't exist.

I've tried surrounding ${workspaceFolder} with single quotes ' '  (which is typically what is required for characters to not be interpreted in a normal shell), double quotes  to no available.

Ideally ${workspaceFolder} should be using / as path separator, not \ which always leads to issue as it's interpreted as escape character.

**Comment by dbaeumer** [comment]
@jyavenard this is a different issue. We are working on given users of tasks more control over how to quote arguments. In general under Windows paths should contain "\" otherwise other tools might fail. 

Which shell are you using to execute the task under WIndows. PowerShell or CMD.exe. This makes a big difference about quoting and escaping.

**Comment by dbaeumer** [comment]
One additional note. If you type a command in tasks.json these are strings in terms of JS / JSON. So if you refer to a path having \ in it you need to escape the \. So a path in a command should be `"command": "echo C:\\xxx\\yyy\\zzz"`

**Comment by jyavenard** [comment]
Exactly, the issue is the $workspaceFolder doesn't contain \\ that causes issue if that command is to be interpreted again ((here by start-shell.bat(

**Comment by dbaeumer** [comment]
@jyavenard the variable is resolve in memory and then passed on. So there is no need to put `\\` since they are never strings in a JS or JSON file as you can see in this comment https://github.com/Microsoft/vscode/issues/42228#issuecomment-371765736

**Comment by jyavenard** [comment]
I understand that..
but when passed to an external shell, then it will interpret again those \\ and treat them as escape characters.
Unfortunately, there's no way around that but enter the full path again, properly escaped.

I believe what this bug is about is having the ability to retrieve workspaceFolder such as it can be used by external script... That means either to use / or have workspaceFolder uses \\\\ literally

**Comment by dbaeumer** [comment]
As said we are working on ways that a task can better specify how to quote arguments. So if you know that you pass a something where the string should not be interpreted by the shell you need to quote it. Changing the result of ${workspaceFolder} is not the right way since there will be for sure cases where people are unhappy to either receive '/' or '\\'.

What puzzles me a little is that `echo ${workspaceFolder}` works for me under Windows correctly but obviously not for you. Which shell are you using and is the simple example working for you ?

**Comment by jyavenard** [comment]
yes, echo ${workspaceFolder} or dir ${workspaceFolder} works as you described...
