### ISSUE TITLE
[BUG, CSS, Emmet] suggestion color if said "#" like "id"....

### ISSUE THREAD

**Issue by Mlocik97-issues** [Microsoft/vscode#42245]
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:36:34.867Z)
- OS Version: Windows_NT x64 6.3.9600
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.14.6

---

Steps to Reproduce:

1. create CSS file
2. write element#id, it will suggest colors.

![screenshot_131](https://user-images.githubusercontent.com/31345346/35472216-520ecfc2-036b-11e8-9c6b-5ea0a93ba144.png)
![screenshot_132](https://user-images.githubusercontent.com/31345346/35472218-638bd7cc-036b-11e8-8894-556b2f5118ea.png)

Reproduces without extensions: Yes

**Comment by jens1o** [comment]
cc @ramya-rao-a

**Comment by marcobeltempo** [comment]
I am a new contributor to the vscode community and would like to take on this issue.  I've reviewed the contributing guidelines and setup dev environment setup.

**Comment by ramya-rao-a** [comment]
Thanks for reporting @Mlocik97-issues!

The parser that we are using marks the node as a property instead of a rule. I have logged an upstream issue for that. https://github.com/emmetio/css-parser/issues/3

I have made a short term fix via https://github.com/Microsoft/vscode/commit/7a5045618e745f4458adc765bad5c1cf88b2e889 which will be available on Monday's [Insiders](https://code.visualstudio.com/insiders) build and in the next stable release of 1.20 which should be out in 2 weeks.

The right long term fix is to stop depending on the emmet's css parser and instead use our own from the css extension. This will be done as part of #29113.

@marcobeltempo Thanks for offering! There is quite some history around the code behind this issue which is going to change a lot with #29113, so I went ahead and fixed this myself.
I would suggest to look at any issues with labels [help-wanted](https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) to get started with contributing to vscode
