### ISSUE TITLE
Allow for smaller or larger tab height size

### ISSUE THREAD

**Issue by imoby** [microsoft/vscode#42253]
Height of tabs and tab container currently is fixed. It would be nice to allow for the option to have a smaller height size of tab container by possibly having an option to set it in settings. Maybe even offer option for larger as well. One might also be able to have the option of disabling file icons to provide even more of a xsmall option. All this provides more real estate to editor instead.

**Current:**
<img width="875" alt="before" src="https://user-images.githubusercontent.com/6380855/35474566-9bd7856a-0355-11e8-9fb3-b7ae986d1936.png">

**Quick modified version of a solution. Line height still needs to be adjusted to be centered though.**
<img width="876" alt="after" src="https://user-images.githubusercontent.com/6380855/35474567-9fd87fde-0355-11e8-994a-bce7990de8db.png">

- VSCode Version: Latest
- OS Version: Latest

**Comment by darthdeus** [comment]
Is there any easy way to make the tabs of smaller height? Feels like a huge waste of space the way its done currently.

**Comment by dpren** [comment]
In terminal-based editors, I love that tabs are usually just the height of a buffer line.

**Comment by darthdeus** [comment]
Exactly, there's no reason for them to be any higher than a single line. Sometimes it feels that designers who create "pretty" designs like tabs in VS Code never really understood the needs of programmers. I mean sure, it looks pretty at first sight, but then you realize you lose 3 centimeters of your possibly small laptop screen just to a useless menu and tabs.

Comparing this to VIM for example, I don't think I ever used tabs, in the sense that I do keep multiple buffers open (and splits possibly), but don't need to see their names at all times. Kinda unfortunate that the current norm is having 40 tabs open instead of having fast and easy buffer switching.

**Comment by ngortheone** [comment]
I would love to have this feature

**Comment by adsingh14** [comment]
Options should include: Default, Compact, Manual( need of value in pixels )

**Comment by mikelnorth** [comment]
I have been searching and searching for this, sad that I cant edit the height/font size of the editor tabs. Only able to change "workbench.editor.tabSizing": "shrink", which makes it take less width.

Id love to be able to specify what font size or to specify at least a small normal and large. or something similar.

**Comment by stevenlordiam** [comment]
Any update on this feature? Is it on the roadmap yet?

**Comment by schrodog** [comment]
I really wish this feature to be launched in near future. The height of tab size waste precious space in editor

**Comment by jorgemmsilva** [comment]
+1, would really like for this customisation to be available

**Comment by schrodog** [comment]
For those wishing to use smaller tabs immediately can use custom CSS extension, but be careful when you make height of tab smaller, there will be empty space in the bottom, because the height of editor is calculated directly under assumption of tab height = 35px and make it inline CSS. :(  You can work around by setting editor-container to be `height: calc(100% - height_you_want );`

**Comment by alexramsey92** [comment]
For issues where I span the entire stack of a web application, I can have at least 10-15 files open at any given time. Config, dao, html, front end js, back end js, models, etc. This level of customization would make it great for me to be able to easily manage a larger number of open files. Having a two layer tab with adjustable height would be awesome!

**Comment by ruelasv** [comment]
Tab titles seem unnecessarily tall (top and bottom padding). This is a BIG issue when working on laptops with no extra monitor as every pixel on the screen is precious real estate. Would LOVE to get some setting that adjusts this padding and make the tab smaller but still functional. As of now it feels like I am getting old and need to have HUGE titles lol.

**Comment by wgq2633** [comment]
I'm expecting this feature too. +1

**Comment by samrayleung** [comment]
Any update on this feature? Is it on the roadmap yet?

**Comment by fega** [comment]
I also want this feature!

**Comment by fega** [comment]
For @samrayleung, @wgq2633  and anyone that need that feature, I just got the same effect ajusting the "editor.fontSize" to a bigger size and then zooming out!

(it will also decrease the sidebar font-size)

**Comment by brandonkal** [comment]
I would like to see something like this specifically for  zooming in. Using VSCode for presentations is pretty easy by pressing cmd+ a few times. But the issue is that this also causes tabs and breadcrumbs to be too large. I'd like to have tabs visible at normal size for reference so I can cmd+number between "slides"

Alternatively, the option to not zoom in the tab bar with cmd+/- would work. Changing only editor font size is okay, but it also means the command pallet is also small for a presentation.

**Comment by inwardmovement** [comment]
Would be great to be able to customize editors' tab bar height indeed.

**Comment by knighter** [comment]
Looking forward to this feature!

**Comment by webia1** [comment]
We all look to the future with hope, maybe there will be a feedback someday,.. :)

**Comment by kanlukasz** [comment]
This can be very useful, especially if you are working on a small screen. I hope you will correct it.

**Comment by debopamgupta** [comment]
This will be very useful if implied in a later update..... those huge tabs are really annoying...

**Comment by bvm84** [comment]
I need this feature too. With such tabs i can't get nice and clean editing area.

**Comment by tiagosiebler** [comment]
Lil workaround in the settings.json:
```
    "workbench.editor.tabSizing": "shrink"
    "editor.fontSize": "16px",
    "window.zoomLevel": -2,
```

Zoom affects everything, including tab sizes. Font reverts the code-font-only part of the change.

**Comment by bitagoras** [comment]
It's actually not about saving half a codeline, but when you have a small screen (in our company we have 16:9 screens) and you use dense line settings is looks kind of unaesthetic to have such unnecessary high tabs. I would appreciate having this configurable to make it smaller.

**Comment by imanhodjaev** [comment]
I would appreciate some compact UI mode very much. On 13" laptops it gets messy from time to time and makes it hard to focus on code.

**Comment by ZzAntares** [comment]
Yes please, it would be very helpful to at least know if this is something the VSCode team is considering.

**Comment by yanisdb** [comment]
Same here, it would just be awesome to be able to hide this bar completly, especially in zen mode.
But reading this thread from early 2018, in 2020, I couldn't figure if we're getting close to the solution, are we ?  Or should we just use one of the quick/crafty solution ?

**Comment by darthdeus** [comment]
What's most frustrating about this issue is how easy it is to fix/implement, and despite so many people wanting it, nobody cares. People praise Microsoft for doing an amazing job with VS Code and how they care about community ... well I'm not going to argue they're doing a great job with VS Code and releasing lots of features, but this issue perfectly shows how they only care about features that are important to them, and not to the community.

I do realize there are almost 5000 issues open here, but at the same time, when someone complained about that Christmas issue, remember how quickly it was resolved? It's just that this is something nobody at Microsoft cares about, and it isn't going to make them any money, so nobody cares. VS Code is just going to slowly turn into one of those projects that will have 5+ year old issues that people constantly comment on and upvote, yet stay unfixed.

**Comment by dguendisch** [comment]
> What's most frustrating about this issue is how easy it is to fix/implement, and despite so many people wanting it, nobody cares.

Obviously it's either not wanted so badly or not that easy to fix/implement so that someone (from the people wanting this) finally stood up and filed a PR.
I want to have that feature too, but not so badly to justify the efforts it would take to fix it myself (i.e. start with learning typescript).
I'm grateful for getting such a great Editor/IDE for free. I'm grateful for MS sponsoring the main investments and for the community helping and improving this software.

> but this issue perfectly shows how they only care about features that are important to them, and not to the community.

Sure, why not, implementing features important to them is naturally more important to them, so they take precedence.

> I do realize there are almost 5000 issues open here, but at the same time, when someone complained about that Christmas issue, remember how quickly it was resolved?

That's a strange comparison: the xmas issue made it to the top news of most IT sites, the "size-of-the-tab-bar"-issue surely won't.

> VS Code is just going to slowly turn into one of those projects that will have 5+ year old issues that people constantly comment on and upvote, yet stay unfixed.

That's true of nearly all heavily used and bigger software projects. It's a matter of priorities and investmenets of limited resources: not only for MS but also for the community.


I understand being frustrated about old, unfixed, upvoted issues, but I don't get why one would want to blame exactly the one party (MS) that is already investing the highest fraction of resources into this project.

**Comment by yanisdb** [comment]
As I'm reading your post @dguendisch, a question came to my mind: could I implement this myself ? I wouldn't really know were to start and I have never participated in any open source project like this one, but could I? Would it get accepted just like this ?

**Comment by dguendisch** [comment]
@yanisdb PRs get accepted if they are correct, don't add or change features that contradict the products more global vision, don't change things in incompatible ways, you have signed the respective contributor license agreement and so on.
Making the tab size configurable is most likely not something that needs too much discussion, vscode already allows to tweak & customize its UI in lots of detailed ways. So yes, I don't see why a sound PR for this feature shouldn't get accepted.
Most OS projects typically have some contributors guide, so your start would be https://github.com/microsoft/vscode/wiki/How-to-Contribute
If you are serious about implementing this feature I'd also start getting in touch with more experienced devs, a good place might be https://github.com/Microsoft/vscode/wiki/Feedback-Channels#slack

**Comment by flerxu** [comment]
Any update ?

**Comment by arcv** [comment]
Since Microsoft not willing to provide an option, you can edit a CSS file to change the height of the tabs.

1. For Windows; Go to VS Code installation folder, find `resources/app/out/vs/workbench/workbench.desktop.main.css` file, Linux/Mac probably have identical location for the CSS file.

2. Backup that file before editing

3. Search these CSS elements one by one and find height:35px within brackets in the `workbench.desktop.main.css` and change it to height you want
`.monaco-workbench .part.editor>.content .editor-group-container>.title .editor-actions{`
`.monaco-workbench .part.editor>.content .editor-group-container>.title .tabs-container>.tab{`
`.monaco-workbench .part.editor>.content .editor-group-container>.title .tabs-container{`

Changing VS Code installation files will trigger popup, you can ignore it by clicking "Don't Show Again", also "Unsupported" text will appear in the VS Code window title. Also each update will overwrite the CSS file and you will lose your changes.

_Default height:35px (left) vs. 20px edit (right)_
![Default height:35px (left) vs. 20px edit (right)](https://user-images.githubusercontent.com/1155206/77423310-014ac280-6de0-11ea-93f7-3adffcf26f32.png)

**Comment by sean9keenan** [comment]
So this isn't a real fix - but using this snippet that I just wrote:
```
.monaco-workbench .part.editor>.content .editor-group-container>.title .monaco-scrollable-element {
    height: 23px !important;
}

.monaco-workbench .part.editor>.content .editor-group-container>.title .tabs-container>.tab {
    height: 23px !important;
}

.monaco-workbench .part.editor>.content .editor-group-container>.title .editor-actions {
    height: 23px !important;
}

.monaco-workbench .part.editor>.content .editor-group-container>.title .editor-actions .action-label, .monaco-workbench .part.editor>.content .editor-group-container>.title .title-actions .action-label {
    height: 23px !important;
}
```

**Comment by bitagoras** [comment]
@sean9keenan
It doesn't change anything in my VSCode. I inserted your code in a file custom.css and added in settings.json the lines:
```json
    "vscode_custom_css.imports": [
        "file:///C:/Program%20Files/Microsoft%20VS%20Code/custom.css"],
    "vscode_custom_css.policy": true
```
Is it still valid for VSCode 1.45?

**Comment by vianneychin** [comment]
@bitagoras try using https://marketplace.visualstudio.com/items?itemName=iocave.monkey-patch css and javascript loader

then put this in your settings.json
```
"customizeUI.stylesheet": {
        ".monaco-workbench .part.editor > .content .editor-group-container > .title .tabs-container > .tab": "height: 23px !important;",
        ".monaco-workbench .part.editor>.content .editor-group-container>.title .editor-actions": "height: 23px !important;",
        ".monaco-workbench .part.editor>.content .editor-group-container>.title .monaco-scrollable-element": "height: 23px !important;",
        ".monaco-workbench .part.editor>.content .editor-group-container>.title .editor-actions .action-label, .monaco-workbench .part.editor>.content .editor-group-container>.title .title-actions .action-label": "height: 23px !important;",
    },
```

which would then result into this

![Screen Shot 2020-05-12 at 4 06 52 PM](https://user-images.githubusercontent.com/47989727/81754269-99713980-946a-11ea-8a86-bbbb9fd2b060.png)

**Comment by sean9keenan** [comment]
@vianneychin @bitagoras - That plugin looks better 😅.

I found that "re-loading" the custom CSS loader plugin was a bit awkward and required restarting the whole VSCode instance (as well as running the "load custom css" command in the command palette). 

On a broader note - would the core team even welcome a change where the height of the tabs could be changed via a single setting?

**Comment by vianneychin** [comment]
@sean9keenan the third css selector seems to add unwanted extra spacing to the bottom of the editor

**Comment by sean9keenan** [comment]
@vianneychin Ok - after a bit more digging I figured it out why it's not working. The issue is that the window into the text editor view itself sets fixed width / height values in... many places.

Unfortunately, I don't see an easy pure CSS solution - the correct fix is definitely to make a PR to the repo.

Which means that my above CSS does not save you any vertical space. Using this for a few days I do find that most of the benefit for me personally is in increasing the density of information at the top.

**Comment by chriszrc** [comment]
I'm using this extension already to get rid of the top title bar (and the traffic lights):

https://marketplace.visualstudio.com/items?itemName=iocave.customize-ui

And it also allows you to customize the tab row height:

<img width="1004" alt="Screen Shot 2020-05-14 at 10 49 52 AM" src="https://user-images.githubusercontent.com/25695785/81949275-a90a9280-95d0-11ea-90b0-f1335f759587.png">

I used this in settings.json:

```
"customizeUI.stylesheet": {
    ".monaco-workbench .part.editor>.content .editor-group-container>.title .tabs-container>.tab.sizing-shrink>.monaco-icon-label>.monaco-icon-label-container": "line-height: 32px !important",
    ".monaco-workbench .part.editor>.content .editor-group-container>.title": "height: 32px !important"
  }
```

**Comment by bitagoras** [comment]
Thank you guys!

**Comment by yanisdb** [comment]
@sean9keenan I've managed to set the sizes of the all divs containing the lines to 100% thinking it would fixe the issue but it did not work. The lines still disappear sooner. The size of the editor or should I say the number of line is not defined by the css code I think.
When the line arrive at the bottom (or near to it) a script removes the div containing the line. Or at least something like that I think. 
But I still think we could still get it to work better and that we could win some space. The divs take 100% of the height but the line is still partly hidden (see the last line of the screenshort). The line is still there but nearly completely hidden. I'm not good enough in CSS or HTML to figure what it hidding though. Does anyone have an idea ?
![image](https://user-images.githubusercontent.com/17860659/82231339-4cd7a380-992d-11ea-8c84-ed2f099543da.png)

**Comment by chriszrc** [comment]
@yanisdb try the approach here - https://github.com/microsoft/vscode/issues/42253#issuecomment-628688080

**Comment by yanisdb** [comment]
> @yanisdb try the approach here - [#42253 (comment)](https://github.com/microsoft/vscode/issues/42253#issuecomment-628688080)

What do you mean ? I've already used some custom css to make the tab bar disappear but its creates some kind of gap at the bottom. See my screenshot. My question was if someone new how to make disappear @sean9keenan last comment saying it's impossible.
Does the comment help with that ? I think I might be failing to see how ?

**Comment by chriszrc** [comment]
@yanisdb the approach I posted doesn't seem to create space at the bottom:

<img width="925" alt="Screen Shot 2020-05-18 at 1 29 55 PM" src="https://user-images.githubusercontent.com/25695785/82242380-be065f00-990b-11ea-890e-96cd22212131.png">

**Comment by yanisdb** [comment]
But you've still got the tab bar. We not trying to achieve the same effect. I want only the window bar (which disappear in full screen) and no tab bar.

**Comment by chriszrc** [comment]
@yanisdb oh, now I see the problem, I only made my tabs a little bit shorter so I didn't notice but when I looked closer I can see that the code is not taking up the full height of the window. I added the CSS to fix this:

```
".editor .editor-container": "height: calc(100% - 31px) !important;",
".editor .monaco-editor .overflow-guard": "padding-bottom:6px !important",
".editor .editor-container .monaco-scrollable-element.editor-scrollable": "padding-bottom:6px !important",
```

I'm only subtracting six pixels from everything (with my shorter tabs) but since you're not showing any tabs you'll need to update calc to not substract anything, and add paddings of 30 something px-

**Comment by yanisdb** [comment]
I'm sorry but I don't get it and I can't make it work. 
Why are you adding padding to the bottom ? Aren't we trying to make a gap disappear and wouldn't adding some padding my the bottom gap bigger ?
And height I've set it to 100% because I want the editor to fill the screen.
Am I getting everything wrong ?

**Comment by vianneychin** [comment]
@yanisdb chris' recent solution only works if you disable the `Breadcrumbs: enabled` to false in the Settings UI.

chris' solution works great for this particular setup

**Comment by yanisdb** [comment]
I've found a solution so easy that it really makes wonder why it's not option in VSCode directly.
In this file https://github.com/microsoft/vscode/blob/master/src/vs/workbench/browser/parts/editor/editor.ts there is at line 19, this constant: export const EDITOR_TITLE_HEIGHT = 35.
Setting it to 0 is exactly what i wanted.
![image](https://user-images.githubusercontent.com/17860659/82881130-916fca00-9f3f-11ea-8868-97cafe240f2b.png)
Now, the text gets cutted at the exact edge of the windows.
I had to modify this file : C:\Users\yanis\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\workbench.desktop.main.js but this doesn't seem like a long lasting solution as it will be overidden at each update.

**Comment by vimniky** [comment]
it'd great if there also have a setting to tweak the toolbar size. 
<img width="1109" alt="Screen Shot 2020-06-07 at 7 07 51 PM" src="https://user-images.githubusercontent.com/11426875/83967231-31d7ce00-a8f2-11ea-83de-a7d6e03759b4.png">

**Comment by vimniky** [comment]
it'll be great if there also has a setting to tweak the toolbar size.
<img width="1109" alt="Screen Shot 2020-06-07 at 7 13 10 PM" src="https://user-images.githubusercontent.com/11426875/83967325-effb5780-a8f2-11ea-8d2e-ea336e7222b5.png">

**Comment by amirmeimari** [comment]
I'm sure a shrunk version or a custom setting is needed. I like it to be as small as JetBrains WebStorm tab size is.

![image](https://user-images.githubusercontent.com/34706947/84664457-d205a680-af33-11ea-9027-96bf79c94b8d.png)

**Comment by Kein** [comment]
I'm kinda baffled it was 2 years of nothing for such basic primitive feature.  Welcome to the software of the future

**Comment by ycanales** [comment]
Googling for this in september 2020 :sob:

**Comment by Tony1324** [comment]
```
"body.inline-title-bar .monaco-workbench .part.editor>.content .editor-group-container>.title .tabs-container, body.inline-title-bar .monaco-workbench .part.editor>.content .editor-group-container>.title .tabs-container>.tab, body.inline-title-bar .monaco-workbench .part.editor>.content .editor-group-container>.title .editor-actions":"height:2.3em !important;line-height:2.3em !important",
".tab .tab-label":"line-height:2.3em !important",
".tabs-and-actions-container":"height:2.3em !important",
"body.inline-title-bar .monaco-workbench .part.editor>.content .editor-group-container>.title .tabs-container>.tab .monaco-icon-label:before":"height:2.28em !important",
".monaco-workbench .part.editor>.content .editor-group-container>.title .editor-actions .action-label:not(span), .monaco-workbench .part.editor>.content .editor-group-container>.title .title-actions .action-label:not(span)":"height:1.9em !important",
```
this works for me

**Comment by Kein** [comment]
```css
.monaco-workbench .part.editor>.content .editor-group-container>.title .tabs-container>.tab .tab-label,
.monaco-workbench .part.editor>.content .editor-group-container>.title .tabs-container>.tab.sizing-shrink>.monaco-icon-label>.monaco-icon-label-container {
	line-height: 26px;
}

.monaco-workbench .part.editor>.content .editor-group-container>.title .editor-actions .action-label:not(span), .monaco-workbench .part.editor>.content .editor-group-container>.title .title-actions .action-label:not(span),
.monaco-workbench .part.editor>.content .editor-group-container>.title .editor-actions,
.monaco-workbench .part.editor>.content .editor-group-container>.title .tabs-container,
.monaco-workbench .part.editor>.content .editor-group-container>.title .tabs-container>.tab {
	height: 23px;
}

 .monaco-workbench .part.editor>.content .editor-group-container>.title {
    height: 23px;
    line-height: 23px;
}

.editor-group-container > .editor-container {
	height: calc(100% - 23px)!important;
}

.editor-group-container > .editor-container .monaco-editor,
.editor-group-container > .editor-container .monaco-editor > .overflow-guard,
.editor-group-container > .editor-container .monaco-editor > .overflow-guard > .monaco-scrollable-element
{
	height: 100%!important;
}
```
Fixed also extra space in text editor after shrinking the tabs. Adjust to your liking.

**Comment by cig0** [comment]
I'd really like to see this functionality implemented as well, as I'd prefer to avoid the associated maintenance burden of having to hack the VSCodium files

**Comment by andradei** [comment]
I hope that after 3 years this is getting further up in the priority list. I'm using `code` without tabs for now 😄

**Comment by Kein** [comment]
Adding more """"""""""telemetry"""""""" seems like more important as of now than user experience.

**Comment by Gitleptune** [comment]
Bumping because this is so annoying, option to hide tabs with name and everything and just leave the actual editor would be great as well.

**Comment by carlocardella** [comment]
@Gitleptune, not sure if this is what you mean but you can hide the tabs entirely: 

```json
workbench.editor.showTabs
```

![image](https://user-images.githubusercontent.com/5784415/122269896-94af5e00-ce92-11eb-8f3d-a18d7c2a22c8.png)

**Comment by fmeyertoens** [comment]
There is also a command that you can bind to toggle tab visibility.
![image](https://user-images.githubusercontent.com/26410884/122270488-aa4a7500-cede-11eb-81de-d86cfacb44d2.png)

**Comment by jackb007** [comment]
**INSTRUCTIONS:**
1. Install the Monkey Patch extension.
2. Install the Customize UI extension. The Customize UI extension requires the Monkey Patch extension to be installed.
3. Open your settings.json file and paste the code below at the beginning of the file.
---------------
"customizeUI.stylesheet": {
        "_comment": "The settings below reduce the height of text block inside tabs",
        "body.inline-title-bar .monaco-workbench .part.editor > .content .editor-group-container > .title .tabs-container, body.inline-title-bar .monaco-workbench .part.editor > .content .editor-group-container > .title .tabs-container > .tab, body.inline-title-bar .monaco-workbench .part.editor > .content .editor-group-container > .title .editor-actions": "height: 2.1em !important; line-height: 2.1em !important",
        ".tab .tab-label": "line-height: 2.1em !important",

        "_comment": "The setting below reduces the height of tabs",
        ".tabs-and-actions-container":"height: 2.1em !important",

        "_comment": "The settings below eliminate the white stripe at bottom of editor caused by reducing the height of tabs",
        "body.inline-title-bar .monaco-workbench .part.editor > .content .editor-group-container > .title .tabs-container > .tab .monaco-icon-label:before": "height: 2.1em !important",
        ".monaco-workbench .part.editor > .content .editor-group-container > .title .editor-actions .action-label:not(span), .monaco-workbench .part.editor > .content .editor-group-container > .title .title-actions .action-label:not(span)": "height: 2.1em !important",
        ".editor .editor-container": "height: calc(100% - 2.1em) !important",
        ".editor .monaco-editor .overflow-guard": "padding-bottom: 2.1em !important",
        ".editor .editor-container .monaco-scrollable-element.editor-scrollable": "padding-bottom: 2.1em !important"
},
---------------
4. Customise tab height to your liking by substituting "2.1" by any other number.
5. Save the file.

**NOTES:**
1. I haven't used the attach-code functionality on this website because it leaves a big chunk of the code outside the code box for some reason unknown to me.
2. I know bugger-all about CSS. I stumbled upon the code above quite a while ago and then recently I came across this page, so I thought I'd share the code. Everything looks good for me except I get a very thin gray line between the body of the editor and the tab. The line disappears when the file is scrolled all the way up. See pictures below.
Scrolled all the way up
![Capture1](https://user-images.githubusercontent.com/86487674/123460178-26c80c80-d5df-11eb-9cb5-14dc99a8b288.PNG)
Not scrolled all the way up
![Capture2](https://user-images.githubusercontent.com/86487674/123460225-36dfec00-d5df-11eb-95a3-530db9ab2a77.PNG)
If anybody knows how to fix this minor problem, please let us know.

**Comment by dwsteele** [comment]
+1 for this feature.

**Comment by Dromantor** [comment]
I just wanted to share my current css to achieve this.
Just load it with your custom-css-loader of choice if you want to use it.

```
:root {
    --size-reduction: 10px;
}

.tabs-container {
    height: calc(35px - var(--size-reduction)) !important;
}

.tabs-container .tab,
.tabs-container .monaco-icon-label,
.tabs-container .monaco-icon-label::before,
.tabs-and-actions-container .editor-actions {
    height: unset !important;
}

.tabs-container .monaco-icon-label {
    line-height: unset !important;
}

.editor-instance > .monaco-editor,
.editor-instance > .monaco-editor .overflow-guard,
.editor-instance > .monaco-editor .monaco-scrollable-element {
    height: 100% !important;
}

.editor-instance,
.editor-instance > .settings-editor .settings-toc-wrapper,
.editor-instance > .settings-editor .settings-editor-tree {
    height: calc(100% + var(--size-reduction)) !important;
}

.editor-instance > .settings-editor {
    height: calc(100% - var(--size-reduction)) !important;
}
```
You can define how much smaller you want the tab bar to be by changing the --size-reduction value.

It works pretty well I think with all the symbols properly aligned.
![grafik](https://user-images.githubusercontent.com/1822013/129197537-1b4f9123-85f0-421d-a7f5-847a4a6b6031.png)

Just the height of the minimap is a little bit off since I can't really resize a canvas with css when its size is set inline by VSCode.
![grafik](https://user-images.githubusercontent.com/1822013/129197788-d08fd0a7-3d8b-45a7-b026-96b96232fe91.png)

Any custom editors from your extensions might be off as well by the same amount since vscode uses a lot of (useless) inline height setting (which could be avoided by just using 100% or not setting it at all).

**Comment by BenGinders** [comment]
Is this option being looked at by the VSCode team?
Personally, the tabs take up too much real-estate on the GUI

**Comment by andradei** [comment]
@Dromantor Your current solution is good but native support would be soooo much better and it seems to be highly sought for.

I removed the tab area completely using a similar solution for the time being.

**Comment by pavlexander** [comment]
I have found the (**yet another..**) solution before I discovered this topic.. Here is what I use:

```css
:root {
  --tab-height: 26px;
}

.tabs-container .tab {
  height: var(--tab-height) !important;
  line-height: var(--tab-height) !important;
}

.tabs-container .monaco-icon-label {
  height: var(--tab-height) !important;
  line-height: var(--tab-height) !important;
}

.tabs-container .monaco-icon-label:before {
  height: var(--tab-height) !important;
  line-height: var(--tab-height) !important;
}
```

before:

![image](https://user-images.githubusercontent.com/20644772/145403360-2777bfe6-d85e-48d7-8234-6a5b63b1be91.png)

after:

![image](https://user-images.githubusercontent.com/20644772/145403281-a775c355-b416-4487-b7eb-9feebc2f8eec.png)

in case if someone is interested on how to display pinned tabs on separate row here's the  other [discussion](https://github.com/microsoft/vscode/issues/98160#issuecomment-989276052).

**Comment by donut** [comment]
Using Monkey Patch + Cusomitze UI extensions, I applied @pavlexander's styles with a few modifications of my own:

```json
    "customizeUI.stylesheet": {
        ":root": "--tab-height: 26px; --font-size-tab-title: 10px;",
        ".tabs-container .tab": "height: var(--tab-height) !important; line-height: var(--tab-height) !important;",
        ".tabs-container .monaco-icon-label": "height: var(--tab-height) !important; line-height: var(--tab-height) !important; font-size: var(--font-size-tab-title); !important",
        ".tabs-container .monaco-icon-label:before": "height: var(--tab-height) !important; line-height: var(--tab-height) !important;",
        ".tabs-container .tab-actions": "display: none; !important",
        ".tabs-container .monaco-icon-description-container": "display: none;",
    }
```

**Comment by pavlexander** [comment]
@donut

I have added a missing style just now. Please check the edit. The `.editor-actions` class affects the size of the editor action button (if that is what it's called). 

Without the proper fix it looks like this:

![image](https://user-images.githubusercontent.com/20644772/146044533-9c2c2e7e-7aaa-439d-a18a-edc8e51fd2d0.png)

after:

![image](https://user-images.githubusercontent.com/20644772/146044368-80f34820-68fc-434c-a49f-061a5c8720fa.png)

(p.s. nice nickname)

**Comment by donut** [comment]
@pavlexander Thanks on both counts. I've updated the code the comment.

**Comment by mike-waev** [comment]
@donut I'm not sure if there's been any editor changes lately, but my tool bar had spacing around it vertically (sometimes). To fix that I removed the static height of the tabs-container class. I also toggled the tab actions back on if anyone else was curious, as it doesn't effect the tab height.

 ```
 "customizeUI.stylesheet": {
    ":root": "--tab-height: 26px; --font-size-tab-title: 10px;",
    ".editor-actions": "height: var(--tab-height) !important; line-height: var(--tab-height) !important;",
    ".tabs-container": "height: unset !important;",
    ".tabs-container .tab": "height: var(--tab-height) !important; line-height: var(--tab-height) !important;",
    ".tabs-container .monaco-icon-label": "height: var(--tab-height) !important; line-height: var(--tab-height) !important; font-size: var(--font-size-tab-title); !important",
    ".tabs-container .monaco-icon-label:before": "height: var(--tab-height) !important; line-height: var(--tab-height) !important;",
    // ".tabs-container .tab-actions": "display: none; !important",
    ".tabs-container .monaco-icon-description-container": "display: none;"
  },
```

**Comment by TheMFB** [comment]
@donut I'm not sure if there's been any editor changes lately, but my tool bar had spacing around it vertically (sometimes). To fix that I removed the static height of the tabs-container class. I also toggled the tab actions back on if anyone else was curious, as it doesn't effect the tab height.

```json
"customizeUI.stylesheet": {
   ":root": "--tab-height: 26px; --font-size-tab-title: 10px;",
   ".editor-actions": "height: var(--tab-height) !important; line-height: var(--tab-height) !important;",
   ".tabs-container": "height: unset !important;",
   ".tabs-container .tab": "height: var(--tab-height) !important; line-height: var(--tab-height) !important;",
   ".tabs-container .monaco-icon-label": "height: var(--tab-height) !important; line-height: var(--tab-height) !important; font-size: var(--font-size-tab-title); !important",
   ".tabs-container .monaco-icon-label:before": "height: var(--tab-height) !important; line-height: var(--tab-height) !important;",
   ".tabs-container .monaco-icon-description-container": "display: none;"
 },
```
If you want to hide the tab actions, add this:
```json
   ".tabs-container .tab-actions": "display: none; !important",
```

**Comment by aromeronavia** [comment]
2022. Feature not done yet 😢

**Comment by nidefawl** [comment]
@TheMFB  The "tabs-container .monaco-icon-label" rule has an incorrect semicolon after font-size

**Comment by AndiKod** [comment]
It worded out for me with the "Custom CSS and JS Loader" but it's still a hack.

![2022-03-12_17-48-23](https://user-images.githubusercontent.com/128460/158026990-3151dffa-f8d1-4ce2-ba5c-bf7fbb05b42c.png)

My tabs are set to "shrinked" mode, close button off, from the regular User.settings pannel, plus the @[pavlexander](https://github.com/pavlexander) code in the custom.css local file. For some reasons the height didn't applied to .tabs-container with the css variable, so I hard-coded it to 20px at the end of the file. 

It was a quick & mindless test, but as it seems to be enough, i'll keep it that way. 
Feels good using a minimalist VSCode with gruvbox & Vim keyBinds.

**Comment by RyannDaGreat** [comment]
I'm adding this comment to keep this issue alive...I want this feature! It would be nice to have it configurable by themes

**Comment by Kein** [comment]
There is no reason to update this thread. Take a look at the history of VSCode medium and below-medium "sized" features - if it is not something some popular person tweeted or said, you can expect approximately ~10 years period.

Therefore, I suggest to fallback to user-suggested workarounds.

**Comment by nidefawl** [comment]
I am using my own extension for this. It is monkeypatching the javascript code and CSS for sidebar, panel title bars, window title bar and editor tabs to a custom height. It also allows setting background images
![Screenshot_20220518_192223](https://user-images.githubusercontent.com/637382/169104346-d11b45b6-a170-4db2-8a08-aa0cb355435f.jpg)

The code is up here https://github.com/nidefawl/vscode-custom-loader for anyone interested

**Comment by AyayaFbiPls** [comment]
I moved from vscode to neovim precisely because of the lack of this feature :

![image](https://user-images.githubusercontent.com/104435563/171201975-61f86051-6585-4060-bc44-018bf606336c.png)

**Comment by dannymichel** [comment]
> https://github.com/nidefawl/vscode-custom-loader

I don't see documentation for this.

**Comment by onolox** [comment]
> I am using my own extension for this. It is monkeypatching the javascript code and CSS for sidebar, panel title bars, window title bar and editor tabs to a custom height. It also allows setting background images ![Screenshot_20220518_192223](https://user-images.githubusercontent.com/637382/169104346-d11b45b6-a170-4db2-8a08-aa0cb355435f.jpg)
> 
> The code is up here https://github.com/nidefawl/vscode-custom-loader for anyone interested

Great implementation, but you NEED at least a  small documentation on how to use it.

**Comment by benibenj** [comment]
In the newest insider we now support a setting to reduce the editor tab height. The compact option reduces the height to  the same height as breadcrumbs. The setting also applies to the editor title when tabs are not shown.
![tabHeightDemo](https://github.com/microsoft/vscode/assets/44439583/2d22c44f-f9c8-497d-83f7-dfd70a9c3457)

**Comment by Kein** [comment]
Is this planned for the next release?

**Comment by benibenj** [comment]
@Kein yes, this will be part of the September release

**Comment by Limezero** [comment]
The current implementation of this doesn't seem to let you configure how high you want your tabs to be, only switch between a preset height of 35 (way too tall) and 22 (way too short for my liking). Is there any way we can define a height manually?

I saw `--editor-group-title-height` in the commit, but I have no idea how this variable is defined or if it's accessible as a command line flag, or a JSON entry, or what.

**Comment by Limezero** [comment]
Really stupid workaround for those who need it:

1. Open `VSCode/resources/app/out/vs/workbench/workbench.desktop.main.js` in a text editor
2. Search for the text `normal:35,compact:22`
3. Change the "compact" value to be something else
4. Enable compact mode in the settings

This should survive future code changes and be a fairly reliable way of setting a custom value, at the cost of "corrupting" your installation and getting warned about that.

![2023 09 28-01 03 37_Code_-_Insiders](https://github.com/microsoft/vscode/assets/8932874/1457b3e2-e43b-4440-b733-2a6b694624c9)

**Comment by Kein** [comment]
> The current implementation of this doesn't seem to let you configure how high you want your tabs to be

> 1. Open `VSCode/resources/app/out/vs/workbench/workbench.desktop.main.js`


I can't stop laughing, we are back to where we started: editing VSCode resources. Everything is implemented in a typical MS fashion 🤣

**Comment by FabioM3** [comment]
Because of this M$ wants to obfuscate the code to stop people to mess with their holy code...

**Comment by imoby** [comment]
@benibenj I want to thank you for allowing the option for compact tabs but I still feel there is need for larger tabs for those who wish to have that. should that be a separate issue then?

**Comment by benibenj** [comment]
@imoby I suggest you make a new issue specifically for this. We can then better see how many users would need this and why. Looking threw the timeline of the current issue, I mostly see people interested in smaller tab heights.

**Comment by Limezero** [comment]
Is there a good reason not to expose the height variable to users and let them set it to whatever they want? I can't see this leading to anything except years of further complaining - "yes I wanted taller tabs but not THAT tall", "no actually I wanted even shorter tabs, this doesn't work for me".

It's a bit like people requesting the ability to use smaller or larger fonts, and then years later adding the ability to use exactly 10pt high text under a "compact" option.
