### ISSUE TITLE
Cannot connect to remote folders in Ubuntu

### ISSUE THREAD

**Issue by santi0037** [microsoft/vscode#42257]
- VSCode Version: 1.19.1
- OS Version: Ubuntu 16.04 LTS

Steps to Reproduce:
1. File->Open folder...
2. Try to see the remote folders

Is the same thing of #9881, but is working on sublime, so the problem is VsCode. When you try to open a remote folder the window don't show the remote folders, but if you try the same process in sublime the window shows it perfectly. I think.. is it possible that there are two system calls to open this window, and vsCode is using the call that does not show the remote folders.

Does this issue occur when all extensions are disabled?: Yes

![captura de pantalla de 2018-01-27 18-33-25](https://user-images.githubusercontent.com/12786093/35476578-2d9459ac-0391-11e8-89d0-5eedef8821d8.png)
![captura de pantalla de 2018-01-27 18-33-39](https://user-images.githubusercontent.com/12786093/35476579-2db61de4-0391-11e8-890e-275a8a3b4787.png)

**Comment by raulesgalindo** [comment]
Do you have different Nautilus versions? I ask because the first one is in spanish, and the other in english, It could be that you are opening the remote folder in one nautilus and code uses the other nautilus.

I opened a remote folder using sftp succesfully
![image](https://user-images.githubusercontent.com/11840157/35478479-7cf07e16-03ac-11e8-9bd7-e3fab1d81415.png)

**Comment by santi0037** [comment]
Nope, only regular nautilus. I noticed the wrong translation too, that's why I assume there are two system calls, both windows were open at the same time..
This is how ubuntu is translated for spanish, some things are ok, and others not..

**Comment by santi0037** [comment]
Temporarily solved using sshfs.
1. `sudo apt-get install sshfs`
2. `cd /mnt`
3. `sudo mkdir newFolder`
4. `sshfs -o allow_other,IdentityFile=/full/path/to/.ssh/id_rsa remoteUser@xxx.xxx.xxx.xxx:/ /mnt/newFolder/`
5. Open vsCode
6. File->Open folder...
7. Select `/mnt/newFolder`
Done..

**Comment by raulesgalindo** [comment]
I try it on a new fresh ubuntu installation and It doesn't have any problem.

![image](https://user-images.githubusercontent.com/11840157/35486212-ad37b9a4-0438-11e8-8125-66db759ec36c.png)

**Comment by akhilkedia** [comment]
Would like to throw in some more information here for anyone who comes across this thread - 

This issue seems to even depend on the specific remote server that's mounted over sftp somehow.
I have 2 servers, both of which I can browse using sftp on Nautilus.
Vscode successfully opens any folders from one server, but none from another.

What could possibly create this difference, I have no idea.
One difference could possibly be that the first server is connected directly over LAN, the second one over Internet.

Vscode version - 1.25.1
Ubuntu Version - 16.04
The issue persists on a fresh ubuntu and vscode install with no extensions.

**Comment by bpasero** [comment]
I think this is not in VSCode control to fix, please report upstream. Closing.
