### ISSUE TITLE
Unable to add watch variables when debugging Python

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/vscode#42291]
<ul>
	<li>VSCode Version: Code - Insiders 1.20.0-insider (ed4c237467bfe7c37b173da782cb65e333484a13, 2018-01-26T06:08:15.259Z)</li>
	<li>OS Version: Darwin x64 17.3.0</li>
	<li><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-generate-getter-setter|DSK|0.4.2
xml|Dot|1.9.2
gitignore|cod|0.5.0
vscode-eslint|dba|1.4.4
githistory|don|0.3.8
tslint|eg2|1.0.24
vscode-npm-script|eg2|0.3.3
docthis|joe|0.6.0
extension-manifest-editor|ms-|0.1.5
python|ms-|0.9.1
vscode-ai|ms-|0.1.6
azurecli|ms-|0.4.0
debugger-for-chrome|msj|4.1.0
typescript-hero|rbb|2.1.1
vscode-icons|rob|7.19.0
vscode-open-in-github|ziy|1.3.1

</details></li>
</ul>

---

Steps to Reproduce:

1. Install the Microsoft Python extension
2. Debug the following python code:
```python
for i in range(1,10):
    print(i)
```
3. Add a break point to the `print` statement
4. Try adding a variable in the watch window, for some reason it doesn't work

Clicking the `+` symbol once disables the `+` icon and nothing happens.

Reproduces without extensions: This is specific to the extension.

Original issue: https://github.com/Microsoft/vscode-python/issues/646

**Comment by isidorn** [comment]
@DonJayamanne the issue was that vscode was wronlgy sending an evalute request for an exression which still does not have a name definied. This is now fixed on the vscode side.
However still the python extension should be able to handle evaluate request which do not have expression set and simply return. What I was seeing was that the python extension would simply not return anytin.g You could look into improving this.

**Comment by isidorn** [comment]
@DonJayamanne Also sending `expression: undefined` would sometimes crash your debug adapter extension and the pyhton process would be left hanging around.
Just happened on my machine and ti was not a nice experience since it ate up 100% of my cpu.
Could your extensoin always make sure to termiante the running python, even if it crashes?
Would you like an issue in your repository regarding this?

**Comment by DonJayamanne** [comment]
@isidorn
>you like an issue in your repository regarding this?

Yes please, please could you include some steps to replicate this. Thanks.

**Comment by isidorn** [comment]
@DonJayamanne created https://github.com/Microsoft/vscode-python/issues/659

**Comment by weinand** [comment]
@isidorn the DAP spec says that the 'expression' attribute for the evaluateRequest must not be missing or undefined. So it is not the DA's responsibility to protect against this case. 

See https://github.com/Microsoft/vscode-debugadapter-node/blob/b61cf04501cfe7356b695f99bc60961684f89a4f/protocol/src/debugProtocol.ts#L886

**Comment by isidorn** [comment]
@weinand agree. Though ideally they should be more error tolernt and not leave pyhton process lying around :)

**Comment by weinand** [comment]
oh yes, definitely!
