### ISSUE TITLE
 Download Now attempts .tar file instead of RPM with code-insiders

### ISSUE THREAD

**Issue by jlmagee** [Microsoft/vscode#42311]
- VSCode Version: code-insiders-1.20.0-1516692255.el7.x86_64
- OS Version:  4.14.14-300.fc27.x86_64 #1 SMP Fri Jan 19 13:19:54 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Steps to Reproduce:

1.  Click "Download Now" from Settings
2.  Formerly navigated to web page with RPM download button. Now attempts to download .tar file which I do not want.

Does this issue occur when all extensions are disabled?: N/A

**Comment by tgilland95** [comment]
this happens to me as well, it started about 3 or four days ago.  

not exactly a solution, but if your prefer the .rpm (or .deb, windows or mac install) you can just go to [here](https://code.visualstudio.com/insiders/) and download the latest .rpm. 

Again, not ideal if you were used to just clicking the update and getting redirected to the download, but it still gets you the latest update.  I'm pretty new to linux and I'm not familiar with the potential benefits of a .tar over a distro specific download so I'm not sure if the change in updates behavior was intentional, but if it is I may add an alias to my shell to automate this (as I had done before the change).

**Comment by jlmagee** [comment]
@mjbvz @alexandrudima @Tyriar  There is no rational indication that #42190 has anything to do with this issue.  Until about 15 days ago, the "Download Now" selection from the settings button of the code-insiders UI opened the page at https://code.visualstudio.com/insiders/ from which an RPM of code-insiders could be downloaded.  Now it navigates a browser to a forced download of a tar file which is not what is desired on a Fedora 26 laptop.

**Comment by jlmagee** [comment]
it downloads fine for me when clicking that button on the download page.  The failure is that clicking "Downlooad Now" in this first screenshot
![screenshot from 2018-02-10 12-38-00](https://user-images.githubusercontent.com/6232618/36064893-0b4e0288-0e60-11e8-9bd2-cfe3871c87f3.png)

goes directly to this tar download in the next screenshot..  Fedora 26 with Chrome Stable
![screenshot from 2018-02-10 12-38-50](https://user-images.githubusercontent.com/6232618/36064901-50622f20-0e60-11e8-892c-274958941763.png)

Hope this helps.

**Comment by Tyriar** [comment]
@jlmagee just pushed the fix, thanks for the report and for bearing with me :smiley:
