### ISSUE TITLE
Test improved code actions API

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#42333]
Test for #34664

Complexity: 3

**OS**
- [x] any @joaomoreno 
- [x] any @RMacfarlane

**Comment by jrieken** [comment]
FYI - to test against the latest API do the following:

* open your extensions `package.json` file
* change the `engine.vscode` property to `*`
* run `npm run postinstall` (assuming you have the `vscode` module as dev-dependency)
* undo the engine-version change from step 2

**Comment by mjbvz** [comment]
Test for #34664

**Size**: 3

**OS**
- [ ] any
- [ ] any

## Overview
#34664 introduces a new type, `CodeAction`, which provides additional metadata and functionality code actions. 

## Core Testing
1. With an extension that is using the proposed API and jrieken documents above
1. Create a simple code action provider
1. Instead of returning `vscode.Command`, return `vscode.CodeAction`
     - ✅ Your new code actions show up and have the proper title and apply the  proper command when selected
1. Update the code action to use a workspace edits instead of a command
     - ✅ Edit is applied as expected
     - ✅  If you set both a command and an edit, that they are both applied (edit first then command)
     - ✅ Multiple code actions apply edits in order
1. Now set a `kind` on the code actions, such as `vscode.CodeActionKind.QuickFix`
     - ✅ These actions still show up in the normal light bulb menu
     - ✅ Actions of kind `QuickFix` does not show up in the refactor menu (triggered by running the refactor command)
1. Add some diagnostics to the `CodeAction`
     - ✅ In the lightbulb menu, code actions for the same diagnostic should be grouped together
     - ✅ In the lightbulb menu, code actions should be sorted by diagnostic severity
   
## Other cases to try
- ✅ A single provider can return both commands and code actions
- ✅ Command based provider still function as expected
- ✅ The `vscode.d.ts` documentation of the new `CodeAction` and `CodeAction` types makes sense
