### ISSUE TITLE
Debug Console should use theme-defined red/green colors

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#42388]
Themes define custom ansi colors, for example in Monokai, 

```json
"terminal.ansiBlack": "#333333",
"terminal.ansiRed": "#C4265E",
"terminal.ansiGreen": "#86B42B",
"terminal.ansiYellow": "#B3B42B",
```

The terminal uses these, but the debug console uses the same colors for every theme. Would be cool if it can use the theme colors too.

Example in Monokai

Terminal
![image](https://user-images.githubusercontent.com/323878/35549854-72eec7e2-053c-11e8-8245-c0dab73d9d60.png)

Console
![image](https://user-images.githubusercontent.com/323878/35549857-78191934-053c-11e8-923e-812c3f6274d8.png)

**Comment by isidorn** [comment]
Code pointer https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/browser/media/repl.css#L167

**Comment by shobhitchittora** [comment]
@roblourens @isidorn I'd like to take a look into this.

**Comment by marcobeltempo** [comment]
@shobhitchittora are you still working on this? I would like to take it on if you're not

**Comment by jtokoph** [comment]
I'm running into this as well. I would like my debug console to match my terminal. The current work around is manually updating css in the devtools or using the unsupported custom css extension

**Comment by iansan5653** [comment]
I'd like to take this over (I'm trying to get all these ANSI issues at once). I see we can pull the color map from here: 
https://github.com/Microsoft/vscode/blob/1f64c126721a66f30a7dcc3ac9e605e8115bcca7/src/vs/workbench/contrib/terminal/common/terminalColorRegistry.ts#L40

I know the colors are set here now: 
https://github.com/Microsoft/vscode/blob/1f64c126721a66f30a7dcc3ac9e605e8115bcca7/src/vs/workbench/contrib/debug/browser/media/repl.css#L130

I'm figuring since they're dynamically pulled from the theme, I'd need to override the CSS from `repl.css` and instead set the colors on creation in:
 https://github.com/Microsoft/vscode/blob/1f64c126721a66f30a7dcc3ac9e605e8115bcca7/src/vs/workbench/contrib/debug/browser/repl.ts#L362

Just want to make sure I'm on the right track / keep track of my plan here.

**Comment by iansan5653** [comment]
@isidorn I'm having a difficult time trying to figure out how to get a color from the currently active theme. I see the `ITheme` interface has a `getColor` function so I'm confident that once I get the theme I can easily get the color, but how do I fetch the active theme?

**Comment by isidorn** [comment]
@iansan5653 use the [`IThemeService`](https://github.com/Microsoft/vscode/blob/2f2085f3e1e3c75916ea950d5c8c2e1e4c28b3dd/src/vs/platform/theme/common/themeService.ts#L78)

**Comment by iansan5653** [comment]
@isidorn I saw that interface too, but again I'm not clear on how to get the active `IThemeService`. My best guess is to use `standaloneThemeService.getTheme()` from [standaloneServices.ts](https://github.com/Microsoft/vscode/tree/master/src/vs/editor/standalone/browser/standaloneServices.ts). Is this the best way to do it?

**Comment by isidorn** [comment]
@iansan5653 pass it in to the handliAnsiSequence function.
And you can inject it into the repl renderer like all other services [here](https://github.com/Microsoft/vscode/blob/bb35a1d223c04425c73bfa7bd4ef865018f8fe4c/src/vs/workbench/contrib/debug/browser/repl.ts#L608)

**Comment by iansan5653** [comment]
Sounds good, thanks!
