### ISSUE TITLE
Latest spdlog slows down shutdown

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#42396]
![image](https://user-images.githubusercontent.com/22350/35555917-034925b2-05a1-11e8-91df-4f32ba4ee0bd.png)

```ts


	dispose(): void {
		let then = new Date().getTime();
		this.logger.flush();
		let now = new Date().getTime();
		console.log('FLUSH', now - then);
		then = now;
		this.logger.drop();
		now = new Date().getTime();
		console.log('DROP', now - then);
	}
```

cc @bpasero

**Comment by gabime** [comment]
@joaomoreno no need to do both flush and drop. spdlog does flush when dropped. This should  reduce by half the wait time for dispose.

**Comment by joaomoreno** [comment]
Hey man! Thanks for checking up on us!

Yeah we found out about that recently, yet didn't adopt it. I'll give that a try. Is there any other thing that comes to mind which would make flush/drop slower from 0.14.0 to 0.16.3?

**Comment by gabime** [comment]
Flush in async mode might be slower indeed, since it waits for the queue te be empty(which itself takes up to 500ms even on empty queue)
possible fixes: 
1:I think flush is not really needed in your case . If i understand correctly, vscode enables  the periodic flush of 2 seconds in async mode anyway (which happens in the bg thread and doesnt block the caller).
2: I am willing to release a fix for spdlog in which flush wont wait for the queue to be empty before returning. It will still be on by default to preserve back conpitiblity, but a flag or something will configure this.

**Comment by joaomoreno** [comment]
> flush in async mode might be slower indeed, since it waits for the queue te be empty(which itself takes up to 500ms even on empty queue)

So, what has changed since 0.14.0? Was `flush()` not waiting for the queue to be empty, before?

**Comment by gabime** [comment]
No, The wait was increased from 250ms to 500ms to reduce cpu usage

**Comment by joaomoreno** [comment]
Oh I see!

**Comment by joaomoreno** [comment]
Removed the call to `flush`. Seems speedy again! I see `drop` taking anywhere from 25ms up to 439ms. This is fine as it doesn't seem to disturb any quit or reload perception.

Thanks for the help @gabime!
