### ISSUE TITLE
Issue reporter shows vslivshare and i18n-sample as installed extensions

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#42410]
### Issue Type
Bug

### Description

Issue reporter shows vslivshare and i18n-sample as installed extensions when all extensions are disabled. These might be the only ones I installed form a .vsix.

### VS Code Info

VS Code version: Code - Insiders 1.20.0-insider (98ae7354ead1f5601278e8f7d3d8b1bc74423834, 2018-01-30T06:08:11.782Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.10GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_1999336|
|Screen Reader|no|
|VM|20%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vsliveshare|ms-|0.1.0-preview.202
i18n-sample|vaz|0.1.0

</details>
Reproduces without extensions

**Comment by RMacfarlane** [comment]
Yes, this seems to be limited to only extensions installed as .vsix. There is a mismatch of the way ids are formatted for these, such that when listing them from the extensionManagementService they are in local format, with -{version} on the end, but when checking if they are enabled, they are compared against gallery format, without -{version}. Investigating

**Comment by sandy081** [comment]
@RMacfarlane Yes, Enablements happens on the gallery extension identifier (that has no version). Unfortunately you have to convert the identifier to gallery format, there is an [Util method](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/extensionManagement/common/extensionManagementUtil.ts#L30) to do that. 

But, I think the right approach is that [EnablementService](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/extensionManagement/common/extensionManagement.ts#L292) does it internally.

**Comment by RMacfarlane** [comment]
Fixed in https://github.com/Microsoft/vscode/commit/683fcaa92bc43629f615a1971deeafdbf63d0ef6. There is already code in [extensionManagementUtil](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/extensionManagement/common/extensionManagementUtil.ts#L38) that looks like it is meant to normalize ids to gallery format. It uses [EXTENSION_IDENTIFIER_PATTERN,](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/extensionManagement/common/extensionManagement.ts#L15) which does not separate out a version. I considered adding (-\d+\.\d+\.\d+(-.*)?)? to it, but the pattern is used in other places and I didn't want to break anything before release

**Comment by sandy081** [comment]
@RMacfarlane This id pattern is for gallery ids which will not have version numbers. Hence it does not has version.

`adoptToGalleryExtensionId` method converts the extension name into lower case because gallery ids are case insensitive. The util method you are using `getGalleryExtensionIdFromLocal` is correct.
