### ISSUE TITLE
Mutli selection context respected only when list has focus

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#42435]
Testing #41688

- Have three files say a, b , c listed in Open editors view
- Select files a & c
- Focus into the editor (this will remove the focus from Open editors view)
- Hover on the file `a` in the open editors view and click on close button

Expected: Both files a & c are closed
Seen: Only file a is getting closed

**Comment by isidorn** [comment]
I acknowledge this limiation but there is nothing I can do to fix it.
Since we only respect the multi selection context when the list has focus.
The only action that you can invoke by not focusing the list is the close action. Which makes me wonder, maybe I should just focus the list once you click on close action, though that might be a bit agressive.

fyi @bpasero

**Comment by bpasero** [comment]
@isidorn I am actually surprised that you can close multiple files by clicking into the close action of a specific entry and it will close all entries that are selected. But I found that already confusing in the SCM view which I think behaves the same.

**Comment by isidorn** [comment]
Closing as will not fix due to the reasons above and did not get any negative feedback around this from users.
