### ISSUE TITLE
Settings Search Progress is very nervous

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#42451]
Testing #42380

* Open settings
* Start typing in the search box
* Observe how nervous the progress bar is: it shows, it disappears, it starts again from the beginning, it disappears again, etc.

![nervous-progress](https://user-images.githubusercontent.com/5047891/35564518-afe8f77a-05ba-11e8-89b9-331175dd115d.gif)

**Comment by sandy081** [comment]
This is because, progress starts showing if the bing search is not finished in 250 ms. It looks like on an average bing search is taking 250 - 300 ms and the progress is shown for the remaining time. And bing search is triggered after waiting 200 ms between key strokes. Hence the progress is getting shown in very short intervals.


Fix is to increase the progress show time to 500ms, it means show progress only if bing takes more than 500 ms.

![kapture 2018-01-31 at 19 27 10](https://user-images.githubusercontent.com/10746682/35640206-d1bd1a0e-06bc-11e8-89dc-273570cfd9cf.gif)
