### ISSUE TITLE
Open Editors: selection not updated when changing editors

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#42452]
Testing https://github.com/Microsoft/vscode/issues/41084

Steps:
* open a couple of files
* click on the first file in "open editors" view
* click on another file using the editor tabs

=> the open editors view looks like this now:

![image](https://user-images.githubusercontent.com/900690/35565120-904e690c-05bc-11e8-8def-c2dcaf4ecdc8.png)

@isidorn could be that I broke this too

**Comment by isidorn** [comment]
Now when the active editor changes both the focus and the selection change in the list.
I proabaably broke this before because I was listeing on selection changes and did not want to react on this automatic setting of selection. However now you changed the open editors to react onOpen which does not get triggered when selection is programaticaly updated. So all works fine

**Comment by bpasero** [comment]
@isidorn should we do the same in the files explorer to be consistent?

**Comment by isidorn** [comment]
@bpasero we already do this in the files explorer, so we are conistent

**Comment by bpasero** [comment]
@isidorn not for me:

![flicker_chrome58](https://user-images.githubusercontent.com/900690/35683263-af098c02-0763-11e8-9491-032fb3a00ffa.gif)

**Comment by isidorn** [comment]
@bpasero you are correct, I have pushed 59217288fc to address this

**Comment by bpasero** [comment]
@isidorn thanks
