### ISSUE TITLE
Improve dnd drop feedback in open editors

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#42471]
Testing #41688

When dragging a file from a group to another, the entire drop group should be highlighted, not just the element under the mouse cursor. Similar to how in an explorer you can drag a file onto an expanded folder, the entire subfolder structure is highlighted.

**Comment by bpasero** [comment]
@joaomoreno @isidorn actually the current DND feedback makes more sense because in contrast to the files explorer, you can drop an editor at a specific location and it will show up there. The only time I would expect full drop feedback over the entire group is when dropping onto the group item itself.

**Comment by isidorn** [comment]
@bpasero what you are saying makes sense, the order is important.
