### ISSUE TITLE
Drop down does not match Monokai theme 

### ISSUE THREAD

**Issue by stevencl** [Microsoft/vscode#42480]
### Issue Type
Bug

### Description

Open output window
Set Monokai theme
Click on drop down
There is no selection highlight shown. In other themes, the currently selected item is highlighted.

### VS Code Info

VS Code version: Code - Insiders 1.20.0-insider (eed7e193125f3d4cfebe2089d1b2a9c674388754, 2018-01-30T09:51:29.494Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3687U CPU @ 2.10GHz (4 x 2594)|
|Memory (System)|7.89GB (1.21GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|yes|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-eslint|dba|1.4.4
tslint|eg2|1.0.24
vscode-great-icons|emm|2.1.22
vscode-gutter-preview|kis|0.12.2
csharp|ms-|1.13.1
vs-keybindings|ms-|0.1.7
vsliveshare|ms-|0.1.0-preview.171
team|ms-|1.122.0
debugger-for-chrome|msj|4.1.0
addDocComments|ste|0.0.8
cordova-tools|vsm|1.3.3

</details>
Reproduces only with extensions

See the screenshot: 
![image](https://user-images.githubusercontent.com/1704059/35570703-dbde7960-05c7-11e8-88c5-4a8f35475438.png)
Found when testing https://github.com/Microsoft/vscode/issues/40589

**Comment by bpasero** [comment]
@cleidigh I think `dropdown.background` is set to the same color as for the selected item

**Comment by raygervais** [comment]
I'd like to take a crack at this issue. 
Can you give some pointers such as where I need to look? 

Thanks!

**Comment by bpasero** [comment]
@raygervais colors are in https://github.com/Microsoft/vscode/blob/master/extensions/theme-monokai-dimmed/themes/dimmed-monokai-color-theme.json#L46

**Comment by cleidigh** [comment]
@raygervais 
Thanks.  I will review your PR when submitted.

**Comment by raygervais** [comment]
Thanks, I hope to have PR done soon.
Just did some research on the theme as well as how the new dropdown widget works.

This appears to be a Windows issue (will test on Linux as well) which I cannot reproduce on MacOS since it appears to be using Webkit defaults?

Here is what it looks like on my MacBook, and the settings I'm playing around with just to see if visual indicators are changing on UI.

<img width="1414" alt="screen shot 2018-02-02 at 10 08 08 am" src="https://user-images.githubusercontent.com/14265337/35739862-0342298a-0801-11e8-87b8-c1d4f838d92b.png">

```json
	// Dropdown Widget
	"dropdown.background": "#414339",
	"dropdown.foreground": "#f8f8f2",
	"list.activeSelectionBackground": "#75715E",
	"list.activeSelectionForeground": "#539", // Test to see what happens :D
	"list.focusBackground": "#414339",
	"list.inactiveSelectionBackground": "#414339",
	"list.hoverBackground": "#272822",
	"list.dropBackground": "#414339",
	"list.highlightForeground": "#f8f8f2",
```

Likewise, I do see that @bpasero has a point, `list.inactiveSelectionBackground` has the same color as `dropdown.background`. Will try that out on a Windows Station and see from there.

**Comment by bpasero** [comment]
@raygervais fyi this needs testing on Linux or Windows where the custom dropdown is used.

**Comment by raygervais** [comment]
@bpasero, thanks for the info. Will test with Linux / Windows today
