### ISSUE TITLE
Merge add/remove functions into a single update/splice functions

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#42481]
re #42321

I believe this is very similar to modifying workspace folders which started with add/remove functions and ended with a single update function. The update allows for more operations, like re-arrange and removal/addition in one call. 

fti @bpasero

**Comment by weinand** [comment]
For breakpoints the order is irrelevant so "re-arrange" is not a useful operation. In addition the "splice" operation does not support deletion of arbitrary elements (only deletion of consecutive ranges). 

After having used the "updateWorkspaceFolders" for testing #42195 I know for sure sure that I do not want to use this API for breakpoints.

**Comment by jrieken** [comment]
Well, now the two of you better talk

**Comment by weinand** [comment]
See my question #42642.
May be I'm missing something...

**Comment by bpasero** [comment]
I used to have a simple add/remove API but @alexandrudima filed https://github.com/Microsoft/vscode/issues/37301 so I think he should also chime in to give feedback on splice API vs. add/remove API.

**Comment by weinand** [comment]
We do not need a general discussion about splice vs. add/remove API. There are pros and cons for both API styles in different situations.

I have no problems with using the splice API for workspace folders because folders have an index and replacing folders for rename purposes profit from splice.
But I do not want to use splice for the breakpoints API.

Alex's arguments from #37301 do not apply for breakpoints:
- addBreakpoints and removeBreakpoints both take arrays of breakpoints,
- there is no need for "replace" functionality because breakpoints do not have an index and their order in the array is irrelevant. So replacing breakpoints does not make any sense.
- bulk removing breakpoints is important but those breakpoints live in random locations of the breakpoints array so a splice operation is completely useless in this case.
