### ISSUE TITLE
Recently selected suggestion should not be shown on the top

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#42494]
Testing #42329
I am not sure if I can create a sample to reproduce it, but could do it consistently in the following file in our code base - https://github.com/microsoft/vscode/blob/master/src/vs/workbench/parts/output/electron-browser/outputServices.ts#L461

- Insert a new line after 461
- Typed `this.`
- Selected `getActiveChannel` suggestion
- Undid the selection and went back to state `this.`
- Typed quickly `aaa` and deleted it to went back to state `this.`
- Triggered suggestions 
- `getActiveChannel` selection is selected
- It is revealed on the top 🐛

**Comment by jrieken** [comment]
I believe this is an issue with the list... The logic always calls reveal with 0 or 11 but the revealing logic is different in some cases..

[Untitled.mov.zip](https://github.com/Microsoft/vscode/files/1682197/Untitled.mov.zip)

**Comment by axefrog** [comment]
Not sure if this is useful extra data, but I think I'm experiencing the same bug. I am frequently getting suggestions that default to things that have a very low probably of being correct, given the context.

Suggestions should take cursor proximity and fuzzy score into account, with a preference for matches that occur at the start of the string, rather than in the middle or at the end.

![image](https://user-images.githubusercontent.com/298883/35693295-7f032624-07c9-11e8-9820-91c0dc643d78.png)

**Comment by joaomoreno** [comment]
@axefrog Please file a separate issue.

**Comment by joaomoreno** [comment]
@jrieken Reopened because the fix merged with recent upstream changes somehow broke it. I'll fix it again next month.

**Comment by joaomoreno** [comment]
Nah, I'll fix it now!

![danger](https://media.giphy.com/media/26gR2ktYgH24dGX8A/giphy.gif)
