### ISSUE TITLE
Changing the number of open editors is not resizing the open editors view

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#42508]
- Set number of open editors configuration to 10
- Open 10 files. See the open editors view is showing all 10 files
- Set the configuration to 4

Expected: View should be resized to 4 show files
Bug: View is not getting resized

**Comment by oriash93** [comment]
I'd like to discuss the meaning of this setting. The User Settings say `explorer.openEditors.visible` is the number of editors shown in the Open Editors pane. 
In my opinion, it could mean two things:
1. The Open Editors pane should show **at least** as much editors.
2. The Open Editors pane should show **at most** as much editors.

The expected behavior @sandy081 described sounds like the second option (correct me if I got it wrong).
However, in the code [(pointer here)](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/electron-browser/views/openEditorsView.ts#L369) it seems to calculate as follows:

- The minimum body size: `itemsToShow * OpenEditorsDelegate.ITEM_HEIGHT`, where `itemsToShow` is the minimum between the number of open editors from the configuration and the number of  actual open editors, and `OpenEditorsDelegate.ITEM_HEIGHT` is hard-coded to be 22.
- The maximum body size: the number of actual open editors * `OpenEditorsDelegate.ITEM_HEIGHT`.
That is the reason for the "buggy" behavior (option 1).

My question is, which one should it be?

**Comment by isidorn** [comment]
Option 1.
However the view actually always has the minimum size unless the user explicitly resizes it. So @sandy081 finds it weird that the view is still not the minimal size since he did not manullay expand it.

@oriash93 if you are passionate about open editor sizing please read these issues
https://github.com/Microsoft/vscode/issues/43501
https://github.com/Microsoft/vscode/issues/25911
https://github.com/Microsoft/vscode/issues/491
