### ISSUE TITLE
"Middleclick to close tab" shortcut assumes active file instead of clicked file tab

### ISSUE THREAD

**Issue by darkvertex** [Microsoft/vscode#42518]
- VSCode Version: code-insiders-1.20.0-1517306054.el7.x86_64
- OS Version: CentOS Linux release 7.4.1708 (Core)

Steps to Reproduce:

1. Use the "split" mode to break the file panels in two.
2. Open one file on the left, another on the right.
3. Click inside the contents of the left file, which will make this "active" (as in, if you type anything, it types inside it.)
4. Try to middleclick on the file tab on the right.
5. Wonder why the heck did the *left* file just disappear when it was the *right* one that you middle-clicked on. :p

You can redo steps 3 and 4 with right and left sides respectively for the same behaviour on the opposite panel.

Does this issue occur when all extensions are disabled?: Yes

**Comment by shixu** [comment]
Well, I fixed it....would anyone mind to tell me how to proceed from here? (PR and so on?) 👍

**Comment by isidorn** [comment]
@shixu thanks for your interest however we are wrapping up our milestone which means that we are on limited time and this bug was in need of fixing so I just fixed it.
For future contributing please check out our guide which should have all the needed details 
https://github.com/Microsoft/vscode/wiki/How-to-Contribute

**Comment by darkvertex** [comment]
That was quick! :clap: Thank you @isidorn and @shixu for looking into this.
