### ISSUE TITLE
Settings search count for "true" shows the correct count + 1

### ISSUE THREAD

**Issue by gushuro** [Microsoft/vscode#42554]
#42378 When searching for "true" in user settings, the correct count shows for an instant, then gets incremented when the search in the left (in the default settings) is performed.

**Comment by gushuro** [comment]
I can still repro the issue.

**Comment by ramya-rao-a** [comment]
@roblourens Moving to March since you are not here ...

**Comment by roblourens** [comment]
We can look at it together, but I don't think this is the same thing.

What I see now is that when I search 'true', I get a slightly different number of results each time. But if I look at the fuzzy results on the left side, there are actually slightly different results at the end of the list. The reason is that result scores can be very slightly different for the same query, so one or two at the bottom of the list may make the score threshold or not when running the same query.

The earlier issue was a race between the searches on the two sides which impacted many more searches.

**Comment by sandy081** [comment]
Verified that I see exact number of results as shown in the number badge
