### ISSUE TITLE
`Compare Selected` should not be in the context menu when one of the selected item is a folder

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#42575]
Testing #41473

`Compare Selected` should not be in the context menu when one of the selected item is a folder

**Comment by isidorn** [comment]
This is a fair feature request.
However due to the limitation of context keys and how we structured them I will not implement this. Also do not see the big downside of showing this.

Code pointers 
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/electron-browser/fileActions.contribution.ts#L276

Basically instead of WorkbenchListDoubleSelection and focus is on file the context should Double file selected.
