### ISSUE TITLE
Explorer: Change "copy path" command to "copy paths" when multiple items are selected

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#42579]
#41473

### Issue Type
Feature Request

### Description

**Steps**
1. Begin a multi-select in the explorer.
1. Right click on items

**Problem**
The "copy path" context menu command should be plural as the command actually copies the paths of all selected items.

### VS Code Info

VS Code version: Code - Insiders 1.20.0-insider (8cac1acd97466afc75c663dc1626d8562a9a3f3d, 2018-01-30T17:29:05.837Z)
OS version: Windows_NT x64 10.0.17052

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2609 v3 @ 1.90GHz (6 x 1896)|
|Memory (System)|31.93GB (24.38GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details>
Reproduces without extensions

**Comment by mjbvz** [comment]
Alternatively, "copy path" could behave like "rename" and only copy the path of the item you right click on to trigger the context menu

**Comment by isidorn** [comment]
Thanks for the nice suggestion Matt. However our command contributions are not dynamic enough to change titles based on context.
In order to fix the name we would have to introduce a brand new command. Which is a pain(due ot shortcut duplication and so on).

As your altenative suggestion I prefer to keep the current suggestion and only behave like that if we see that users get surprised by multiple paths being copied. I personally find this feature cool, so I am closing this issue as will not fix
