### ISSUE TITLE
Long file results

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode#42586]
Testing #42357

I pulled data from [Amazon public data](https://aws.amazon.com/public-datasets/) sets:  https://s3.amazonaws.com/irs-form-990

I created "base" data file:

[basedata.txt](https://github.com/Microsoft/vscode/files/1680013/basedata.txt)

which I then copy/pasted over an over until I reached about 1MM lines. From there:

- Copy All (Cmd+A, Cmd+C) crashes renderer 
- i was able to copy/paste 1MM lines in sublime, so now file is at 2MM lines and 378MB

Using a mental stopwatch:

- Stable: opens in 5 to 6 seconds
- Insiders with VSCODE_PIECE_TREEE=1: opens in about 5 seconds (so slightly faster)
- Sublime: opens in about 4 seconds

Selection:

- Ctrl+F to find a sequence of characters in every line (e.g. `b890b4`) and then Shift+CMD+L to set a cursor on every one failed (window not responsive message).
- Sublime handled setting a cursor on every line with Find All but hung when trying to type.

**Comment by rebornix** [comment]
With Electron being updated over the last two years, we can handle the file better now. Using a real stopwatch

* Open 2MM lines (375MB) in Code uses 3.3s
* Open in Sublime takes around 3.3s 

Copy 1MM lines and paste doesn't crash the renderer process as well since the string len limit is increased.

For multiple selections, there is not much we can do now, we can handle so many selections in our current implementation.
