### ISSUE TITLE
`Open to the Side` does not work when a folder is part of the multiselect

### ISSUE THREAD

**Issue by RMacfarlane** [Microsoft/vscode#42584]
Testing #41473

Repro steps:
Select a folder and file in the explorer, use menu or keyboard shortcut to run `Open to the Side`

Pane blinks in and out of existence

Would expect either all files within the folder to be opened, or the option to be disabled when a folder is selected

**Comment by isidorn** [comment]
@RMacfarlane nice catch
@chrmarti how come the bot prematurly assigned @bpasero if there is a timeout now?

**Comment by isidorn** [comment]
Now I simply ignore the selected folder when opening to the side.
I do not want to open all the children since this can be surprisin to users and in that case you could argue that we should show open to the side even if only one folder is selected.

Open To The Side is disabled when the focused element is a folder, and all our disablement is working in the context of the a focused element, not in the context of what is all selected.

Due to the reasons mentioned above I have chosen to simply ignore the selected folders when executing this commands.
