### ISSUE TITLE
Compare selected in the Open Editor Context menu when a resource + group item is selected

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#42600]
Right click on the ´README´ resource in the setup below

![image](https://user-images.githubusercontent.com/172399/35610865-48be29ae-0663-11e8-83ed-2eb6d8acbcf1.png)

Notice that the Compare Selected item is shown in the context menu, but only a single resource is enabled.

**Comment by isidorn** [comment]
This is happening becuase of the nature of context keys which we are using for the `when` clause.
That command we show when two items are selected in the list, and when the focused item has a resource. So naturally if you select two, and click on editor we will show it, even if the first one does not have a resource.

The fix for this would be to introduce a brand new context key which would be all selected items have a resource. It is a bit too specifc and I would introduce it only if more commands have a need for this. In the meantime, backlog.
