### ISSUE TITLE
When find/replace could take long, show progress bar

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#42670]
Testing #42357

When I do a find/replace for a word that occurs around 20k times, it takes 2-3 seconds, which is amazing. But still during that time the editor looks like it's stuck.

Think would be better if we could show a progress bar when the operation takes more than 1 second.

**Comment by rebornix** [comment]
We closed this issue because we don't plan to address it in the foreseeable future. You can find more detailed information about our decision-making process [here](https://aka.ms/vscode-out-of-scope). If you disagree and feel that this issue is crucial: We are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Thanks for your understanding and happy coding!
