### ISSUE TITLE
[loc] upload Ukrainian (uk) '.xlf' to transifex VS Code project

### ISSUE THREAD

**Issue by Serg-zefir** [Microsoft/vscode#42673]
Hello, my name is Serhii (I am the Ukrainian language team) I need help. I have translated vscode-editor (100%)
vscode-extensions (10%), vscode-setup (100%), vscode-workbench (100%). I have translated into "smart cat" system and I have 61 files ".xlf" file format. However, I can not upload these files to the transfix. Help me contribute to the development of the Ukrainian localization of the VScode.

**Comment by Serg-zefir** [comment]
I got all the files using gulp + transifex mytoken + vscode-nls-dev.

**Comment by danyeh** [comment]
Activate this one.

**Comment by danyeh** [comment]
@Serg-zefir , is it latest you have for files you already localized? https://github.com/Microsoft/Localization/tree/master/Locale/Ukrainian

**Comment by Serg-zefir** [comment]
@danyeh Hello. So far, that's all my work (based on the Ukrainian team of translators). Now I have little time, but I still plan to continue translating.  I think we can combine our efforts, I could help with backend for importing files using transifex mytoken + vscode-nls-dev.

**Comment by danyeh** [comment]
@Serg-zefir , thank you for confirming! Don't do anything else yet until we figure out how to make existing translation into Transifex. It should be solved in coming days ...

**Comment by danyeh** [comment]
@Serg-zefir , finally we made progress to workaround the issue. Now your change has been made into TM. This is not ideal because there are side effect. We will count 14k words contribution from you. Please let me know your Transifex account so I can associate with.
We appreciate your continuous contribution, please do it in Transifex UI.
We encourage community members to publish language pack. Please take a look at below how to topics to see if you can help to cover the language you are contributing.
https://github.com/Microsoft/vscode-loc/wiki/How-to-create-language-pack-extension
https://github.com/Microsoft/vscode-loc/wiki/How-to-publish-to-Marketplace

**Comment by Serg-zefir** [comment]
Профіль SergZ Учасник з: Пт 22 Гру 2017 - this is my account Transifex. Interesting links. Next week I read more (I do not speak English, translate online resources). How will questions on packages, then there to create Issues?

**Comment by danyeh** [comment]
@Serg-zefir , I close this issue here. If you are willing to publish Ukrainian language pack and have question, please create issue in https://github.com/Microsoft/vscode-loc/issues. Thanks!
