### ISSUE TITLE
Powershell - Debug adapter process has terminated unexpectedly

### ISSUE THREAD

**Issue by laurijsd** [Microsoft/vscode#4267]
- VSCode Version: 0.10.11 , shell 0.35.6, Renderer 45.0.2454.85
- OS Version: WIN10 Pro

Steps to Reproduce:

1. Have a working setup with VSCode 0.10.10 and powershell debug 0.5.0
2. Upgrade VSCode to 0.10.11. 
3. Debug fail: The error says Debug adapter process has terminated unexpectedly
4. Reinstall VSCode 0.10.10 and powershell debug 0.50, issue remains

[DebugAdapter.log.txt](https://github.com/Microsoft/vscode/files/174384/DebugAdapter.log.txt)

**Comment by weinand** [comment]
@laurijsd The attached log shows that this is an error in your launch config. You are passing the string "-Verbose" where an array of strings is expected:

![2016-03-16 12-33-17](https://cloud.githubusercontent.com/assets/1898161/13811046/74bbdc0c-eb73-11e5-9e43-3577aed80d5d.png)

In VS Code this error is actually flagged as a problem:

![2016-03-16 12-37-18](https://cloud.githubusercontent.com/assets/1898161/13811114/dd96b59e-eb73-11e5-9ecd-69b9a7ade214.png)

This error occurs in VS Code 0.10.10 too, so this is not a regression:

![2016-03-16 12-41-04](https://cloud.githubusercontent.com/assets/1898161/13811201/85e83c9a-eb74-11e5-9c7c-64c45aba5569.png)

I suggest to file a bug against the PowerShell extension because they should protect against these JSON parsing errors.

**Comment by irejwanul** [comment]
I had the same issue. But in my case this was problem with SVG Viewer extension. So, I've remove it, then also removed C# extension also.
After that, re-installed C# extension, then VS Code downloaded and installed .NET Core Debugger again.
And now, all are good,  even though, I've re-installed SVG Viewer extension.
[Note: Check Developer Console from 'Help' menu for your particular problem]
