### ISSUE TITLE
multi root compound debugging intellisense kicks in too early

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#42688]
Ran into this issue while testing #42036 

The very moment I click `Add Config(Workspace)`, a new config file is opened and the autocomplete dropdown shows up immediately 

![image](https://user-images.githubusercontent.com/876920/35653615-0495a802-069e-11e8-83ea-7b5974dfe87f.png)

**Comment by isidorn** [comment]
Somehow this issue slipped through my fingers since february.
Anyways now I simply do not trigger inteli-sense when the "configurations" field can not be found.
We can not do anything better than this since we would need to automatically add the missing pieces of the configuration object which is a pain
