### ISSUE TITLE
Bracket Matching: Jump between regions with Bracket Matching (Ctrl+Shift+\)

### ISSUE THREAD

**Issue by Fenweldryn** [microsoft/vscode#42729]
I would like to suggest a tweak to Bracket Matching (where you can jump between brackets with Ctrl+Shift+\\) to be able to jump between the recently added regions feature, so I can jump between #region and #endregion. Trying it it just jumps to the next matching symbols and ignore the region tag.

**Comment by brentwang23** [comment]
I was interested in tackling this because it sounded like an easy enough first issue, but it seems like it might actually be pretty involved. From what I can tell, bracket jumps are handled by JumpToBracketAction defined [here](https://github.com/Microsoft/vscode/blob/8213728043b96cc6ab3157650b95a1e6f8e4f7f1/src/vs/editor/contrib/bracketMatching/bracketMatching.ts#L28), which calls on functions like matchBracket() defined [here](https://github.com/Microsoft/vscode/blob/8213728043b96cc6ab3157650b95a1e6f8e4f7f1/src/vs/editor/common/model/textModel.ts#L2022). 

To add region-jumping functionality, it seems like we'd have to implement a new function in TextModel like matchRegion(), then redefine JumpToBracketAction to also consider regions using that. Does that sound correct? Or maybe region-matching is already defined somewhere else and I didn't see it?
