### ISSUE TITLE
Constantly looking for git on launch for no reason

### ISSUE THREAD

**Issue by akbyrd** [Microsoft/vscode#42747]
Every time launch VS Code it looks for a git installation even though nothing in the workspace uses or requires git. I know there's a setting to disable the warning, but why is VS Code spending time looking for tools I don't use on startup?

- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:36:34.867Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-npm-script|eg2|0.3.3
tortoise-svn|fan|0.1.1
Lua|key|0.0.9
python|ms-|0.9.1
cpptools|ms-|0.14.6
csharp|ms-|1.13.1
code-settings-sync|Sha|2.8.7
shader|sle|1.1.2
Align|ste|0.2.0
unity-debug|Uni|1.2.1
vscode-todo-highlight|way|0.5.11

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Don't use git
2. Launch VS Code
3. Notice the warning

![image](https://user-images.githubusercontent.com/484784/35687947-ae8b6756-0735-11e8-9528-5bcb483f3936.png)

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
You can disable git with `git.enabled = false`. This won't work in 1.19 yet, since there is an issue when that setting is applied globally. But that is fixed for 1.20.

**Comment by akbyrd** [comment]
Seems a bit backwards that I need to disable tools I don't need in a workspace. Shouldn't the default be to not do work the user doesn't need / didn't request?

I'd greatly prefer that I don't need to remember to disable this for every new workspace.

**Comment by joaomoreno** [comment]
I see your point. We can't avoid looking for git, since that's what enable us to be preemptively helpful on git workspaces.

But we could perhaps avoid alerting you about a missing git installation unless you explicitly try to use a git feature. Here's the problem with that: a user who is clueless about not having git (or simply expects git features to work without it) opens VS Code and sees no git features working. If we don't tell him he needs Git install, he'll simply file us an issue "stuff doesn't work".

Overall that's what the `Don't show again` button is there for. Once you click it, you no longer see the message.

**Comment by akbyrd** [comment]
What about avoiding the git search unless there's a .git folder?

**Comment by joaomoreno** [comment]
The git folder might not actually be inside your workspace, but somewhere further up. Implementing this is just duplicating what `git` is doing.
