### ISSUE TITLE
vscode.window.showInputBox moves cursor when validating

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Microsoft/vscode#42763]
Here's some sample code that reproduces the problem:
```typescript
function showInputBoxError(): void {
    vscode.window.showInputBox({
        prompt: 'Enter two words',
        validateInput: (text: string): string | undefined => {
            if (!text || text.indexOf(' ') === -1) {
                return 'You must enter two words';
            } else {
                return undefined;
            }
        }
    });
}
```

Here's a sample gif illustrating the problem:
![inputbox](https://user-images.githubusercontent.com/11282622/35699070-ce3b81b8-0743-11e8-894f-31abad0e2a79.gif)

You'll notice that I mispelled 'Hello' and I was trying to go back and fix it. However, When I deleted the space it moved my cursor to the end of the line and I started typing at that point

Code - Insiders 1.20.0-insider
Darwin x64 17.4.0

**Comment by StephenWeatherford** [comment]
This is very annoying.

**Comment by raygervais** [comment]
I'd like to take a crack at resolving this bug if no one else is working on it, and if it isn't fixed already.
I can test via using the code sample above to determine if this issue is still present, my only question is where exactly do I put the code sample so that it is executed in Code? I've never used Code to embed functions into it's runtime before.

Thanks 🎆 💻

**Comment by StephenWeatherford** [comment]
You could create a blank extension and put the code there. Easiest might be to repro in the extension itself: https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-azurefunctions.

Open the "Azure Functions" pane in the explorer, click on the folder icon to create a new project, select a target folder, select JavaScript. When project loaded, select the lightning icon to create a new function, select the project folder, select Blob trigger, skip selecting storage account, accept new name, select AzureWebJobsStorage for app setting. You should then be on "Provide a 'Path'".  

Select "sample-workitems" and press delete, then type "hello" to replace "sample-workitems".  BUT... As soon as you type one letter, the cursors goes to the end of the input, so "h" ends up at the beginning and "ello" ends up at the end. Go back to the beginning and add two more characters to the "h" so that it's valid - cursor just to the end again.  Every time it changes between valid/invalid, this happens.

![image](https://user-images.githubusercontent.com/6913354/36344466-719a8416-13cf-11e8-9d8a-0b93ddc42c63.png)

**Comment by raygervais** [comment]
Managed to replicate this with your tutorial @StephenWeatherford, thanks!
Will look into this and see what I can turn up! 

<img width="576" alt="screen shot 2018-02-22 at 3 19 29 pm" src="https://user-images.githubusercontent.com/14265337/36562097-d870f37e-17e3-11e8-9d33-43c4ac29e002.png">

**Comment by StephenWeatherford** [comment]
The actual validation code is in the extension, I believe here: repos\vscode-azurefunctions\src\templates\ConfigSetting.ts, but it really shouldn't matter. Yes, the validation failure is expected.  I can create a simpler repro extension if you need it.

One thing to note: This only started happening a month or two ago, so I would look for changes in the relevant code.  It shouldn't be a question of whether or not the user is still typing - the textbox selection state should not be changed because of validation failures ever.

**Comment by raygervais** [comment]
Hey Stephen and others on this thread, just an update / question for when you have a moment 😄. 
After a lot of review and testing of previous git commits spanning all the way back to August 2017 `a87dd9c`, it appears that this issue was present even then. I feel as if unless I misunderstood how to test, that the only way to truly uncover the logic failure in this is to investigate the relevant functions and scopes which autofocus after validation. Is it possible for us to confirm that these are the correct functions which affect and relate to the issue? 

*DoPick*
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/parts/quickopen/quickOpenController.ts#L293

*Autofocus*
https://github.com/Microsoft/vscode/blob/master/src/vs/base/parts/quickopen/browser/quickOpenWidget.ts#L636

Reasons why I'm looking here, is because I see there is a autoFocus configuration object which determines how the input element handles the input value and form element. Right now on version `1.21.0`, the autoFocus object contains the following when using the Azure Functions case: 

```js
{
    autoFocusFirstEntry: true
}
```

And I'm wondering if this is the issue. Who feeds the configuration for autoFocus? The extension / validator?

PS. Sorry for the delay / lack of transparency while testing and debugging this issue, finding time was incredibly difficult this week and I didn't want to bog down this thread with environment related issues and or random guesses towards what the issue could be.

**Comment by StephenWeatherford** [comment]
@raygervais Thanks!

**Comment by EricJizbaMSFT** [comment]
@raygervais tried it out on today's insiders build and it worked great! Thanks!
