### ISSUE TITLE
Configuration settings are incorrectly read for out of (single folder) workspace files (workspace.getConfiguration)

### ISSUE THREAD

**Issue by bartosz-antosik** [Microsoft/vscode#42825]
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:36:34.867Z)
- OS Version: Windows_NT x64 10.0.16299
---

Steps to Reproduce:

1. Open single folder workspace, which has a `.vscode` folder with workspace settings different than user settings.
2. Open another document which resides in a folder outside of the workspace.

When reading configuration using `workspace.getConfiguration` passing document's uri as a second parameter:

1. For a file(s) from inside of workspace workspace settings are returned.
2. For a file from outside of workspace also workspace settings are returned.

Contrary to the above described, when repeating the same in a MULTI ROOT workspace (of which each of the folders contains workspace  settings in `.vscode\settings.json`) for each of the files from one of the workspace folders respectable settings are returned and USER settings are returned for a file from outside of (any of) the workspace folders.

I suppose in the first situation USER settings should be returned for the document from outside of the workspace folder.

**Comment by sandy081** [comment]
@bartosz-antosik I see your point. We return `workspace settings` for a file outside workspace. In first (single folder workspace) case, folder settings are workspace settings (because folder is workspace) and in multi folder case, there are separate workspace settings.

I think this is consistent currently and if we read user settings for such files.. it has to be same for other workspaces too. Doing this, I afraid, might break the existing users.

Would like to know your reasoning behind falling back to user settings for such files?

**Comment by bartosz-antosik** [comment]
@sandy081 Thanks for the answer. 

The main practical trouble is what happens when the configuration is updated. 

I have a simple GUI in my [Spell Right](https://marketplace.visualstudio.com/items?itemName=ban.spellright) extension to update settings (a language selector in the status bar). The scope parameter of the update using `.update` method of the [WorkspaceConfiguration](https://code.visualstudio.com/docs/extensionAPI/vscode-api#_a-nameworkspaceconfigurationaspan-classcodeitem-id988workspaceconfigurationspan) namespace is decided on the document's **uri**. For a document from INSIDE of the workspace uri returns a workspace folder which is then used as an indicator that `ConfigurationTarget.WorkspaceFolder` should be targeted for the update. Doing the same fo a document from OUTSIDE of the workspace yields no workspace folder which says that `ConfigurationTarget.Global` should be used so User configuration is updated. 

So when I change the language for such a document from OUTSIDE of single folder workspace USER configuration is updated and WORKSPACE configuration is read. In multi root workspace correctly (according to my logic) both User configuration is updated and read for such a document.

USE CASE: It is just very inconvenient when you want to edit some file from aside, not necessarily belonging to any workspace, e.g. laying on the desktop: You get different settings when you right click on it and open it WHILE there is already VSCode opened working on some workspace, and when there is no VSCode open and it starts just to edit this file.

This lack of symmetry (between single/multi root workspaces) seemed so obvious to me... :-)

I would long ago do a workaround for such a case but it requires something not very wise which is reading the configuration on my own, because `getConfiguration` method of the [workspace](https://code.visualstudio.com/docs/extensionAPI/vscode-api#_workspace) namespace acts on it's own and does not let you decide which scope to read.

**Comment by sandy081** [comment]
@bartosz-antosik Can you please provide the update calls you make for each case

1. Single folder workspace and belongs to workspace
2. Single folder workspace and does not belongs to workspace
3. Multi folder workspace and belongs to workspace
2. Multi folder workspace and does not belongs to workspace

**Comment by bartosz-antosik** [comment]
@sandy081 With pleasure, but, could you please just tell me why, because updating configuration works fine, reading is the problem?

1. `.update("language", ConfigurationTarget.WorkspaceFolder)`
2. `.update("language", ConfigurationTarget.Global)`
3. `.update("language", ConfigurationTarget.WorkspaceFolder)`
4. `.update("language", ConfigurationTarget.Global)`

**Comment by sandy081** [comment]
@bartosz-antosik I see.. you are explicitly writing into the specific targets in each case. So you update User configuration if file is outside workspace and Workspace folder configuration if file is inside workspace. 

Read is consistent and is always read from **Workspace** for a file that is outside. In single folder case `Workspace Configuration` == `Workspace Folder Configuration` and in a Multi folder case `Workspace Configuration` has its own file. See [documentation](https://github.com/Microsoft/vscode/wiki/Extension-Authoring:-Adopting-Multi-Root-Workspace-APIs).

You can confirm it when you update the configuration to `Workspace` target in different workspaces. For eg., open two multi folder workspaces say A and B. Open a file that does not belong to A and B and update the configuration into `Workspace` (with different values)

`.update("language", ConfigurationTarget.Workspace)`

You will observe that value for each will be always read from its respective workspace configurations. 

If I am not wrong, your request is to read configuration for outside workspace files from always User settings? If so, I am not sure if we can support that because this might break existing users who wish to have configuration read from workspace. 

But we have a feature request to read configuration from the parent `.vscode` folder of the file that is outside given workspace.

**Comment by bartosz-antosik** [comment]
After bit of thinking on this I agree that your choice (to read a workspace root configuration for out of workspace file) is better. Probably much more intuitive for users. I will follow this paradigm with my extension.

Thanks for the discussion.
