### ISSUE TITLE
Feature Request: Allow snippet json prefix to be an array to support multiple prefixes for the same snippet

### ISSUE THREAD

**Issue by tylerl0706** [Microsoft/vscode#42838]
We have several of the same snippets in our snippets json:
```json
"Function-Advanced": {
        "prefix": "function-advanced",
        "body": [
            "function ${1:Verb-Noun} {",
            "\t[CmdletBinding()]",
            "\tparam (",
            "\t\t$0",
            "\t)",
            "\t",
            "\tbegin {",
            "\t}",
            "\t",
            "\tprocess {",
            "\t}",
            "\t",
            "\tend {",
            "\t}",
            "}"
        ],
        "description": "Script advanced function definition snippet"
    },
"Cmdlet": {
        "prefix": "cmdlet",
        "body": [
            "function ${1:Verb-Noun} {",
            "\t[CmdletBinding()]",
            "\tparam (",
            "\t\t$0",
            "\t)",
            "\t",
            "\tbegin {",
            "\t}",
            "\t",
            "\tprocess {",
            "\t}",
            "\t",
            "\tend {",
            "\t}",
            "}"
        ],
        "description": "Script cmdlet definition snippet"
    },
```

This could be avoided by supporting an array of prefixes like so:

```json
"Cmdlet": {
        "prefix": ["function-advanced", "cmdlet"], // <--- here
        "body": [
            "function ${1:Verb-Noun} {",
            "\t[CmdletBinding()]",
            "\tparam (",
            "\t\t$0",
            "\t)",
            "\t",
            "\tbegin {",
            "\t}",
            "\t",
            "\tprocess {",
            "\t}",
            "\t",
            "\tend {",
            "\t}",
            "}"
        ],
        "description": "Script cmdlet definition snippet"
    }
```

It'd help slim down snippet json files and support snippets that might go by different names.

**Comment by noamyogev84** [comment]
Hi, can I try this one? I'm new to this repo. :)

**Comment by jrieken** [comment]
Great. Some code pointers to get you started

0. Update the JSON-schema so that `prefix` can be a string or an array [here](https://github.com/Microsoft/vscode/blob/cc0b42784c62c6e078bbbd923b4d0751c2d51140/src/vs/workbench/parts/snippets/electron-browser/snippets.contribution.ts#L44)
1. The serialised snippet (as defined in JSON) is declared [here](https://github.com/Microsoft/vscode/blob/cc0b42784c62c6e078bbbd923b4d0751c2d51140/src/vs/workbench/parts/snippets/electron-browser/snippetsFile.ts#L123-L129) 
2. Creating snippets happens in the [`_parseSnippet`](https://github.com/Microsoft/vscode/blob/cc0b42784c62c6e078bbbd923b4d0751c2d51140/src/vs/workbench/parts/snippets/electron-browser/snippetsFile.ts#L224)-method. You are best off to create and [push a new snippet](https://github.com/Microsoft/vscode/blob/cc0b42784c62c6e078bbbd923b4d0751c2d51140/src/vs/workbench/parts/snippets/electron-browser/snippetsFile.ts#L254-L262) per prefix when it is an array

**Comment by noamyogev84** [comment]
Hi @jrieken, Thanks for this detailed howto, appreciate it.
I'm about to finish this one though I do encounter one issue:
Following **step 0** I modified the type to be `['string', array']` , but when i'm creating a new snippet with a **prefix** array e.g. `["foo","foo2"]` I get a warning **Incorrect type. Expected string**.

besides that, everything works fine.
any tips on how to solve this before I do PR?

**Comment by noamyogev84** [comment]
Hi @jrieken  thanks for this detailed howto.

**Comment by jrieken** [comment]
Done! All thanks to @noamyogev84 👏 🏅

**Comment by tylerl0706** [comment]
🎉🎉🎉

**Comment by tylerl0706** [comment]
Nice work, @noamyogev84!! 🎉

**Comment by noamyogev84** [comment]
@jrieken @tylerl0706 
Thanks guys!
