### ISSUE TITLE
Editing multiple files is increasing the memory footprint indefinitely 

### ISSUE THREAD

**Issue by SofianHn** [Microsoft/vscode#4286]
- VSCode Version: 0.10.12
- OS Version: OSX

#4001

Steps to Reproduce:

1. Open VSCode repo.
2. Take an initial snapshot for memory 
3. Edit 10 files by adding a simple statement `var x =1`
4. Take a snapshot 
5. Repeat 3 & 4 for 5 times. 

Memory footprint increased from 55MB to 75MB after editing about 50 files. I am not sure if that's an indication of liner increase of memory by editing more files. I would have expected it to grow up to a certian limit and then flat as file models are being cleaned from the memory.

**Comment by bpasero** [comment]
@SofianHn is this always the same 10 files? Once a file is under working files (e.g. you edit a file), we never dispose it until you clean working files.

**Comment by SofianHn** [comment]
No, not the same 10 files which explains it. I think this might be really dangerous. I never use the working files, on a long running multi day session this could lead to a crash. Does the working files has a limit? 10 or 15 per say?

**Comment by bpasero** [comment]
200 is the limit.

**Comment by bpasero** [comment]
This goes into a similar direction of what I discussed with @alexandrudima at some point that it would be nice to dehydrate models so that they consume less memory. I think one idea was to persist the undo cache somehow so that we can still restore that.

I am closing this one because I do not think we grow unlimited, our limit is just at 200.
