### ISSUE TITLE
JavaScript code formatting extention not working properly 

### ISSUE THREAD

**Issue by Lonefy** [Microsoft/vscode#4294]
Before v0.10.10, the formatting extention works well.After the update, `Format Code (Alt+Shift+F)` just add some spaces. :(

**Comment by dbaeumer** [comment]
@Lonefy have you installed an extension for JS formatting. If so, please report the bug there. If not I think the problem is the move to Salsa (a different JS engine we use). With 0.10.12 there are settings to control the Salsa based formatter as well.

**Comment by Lonefy** [comment]
@dbaeumer actully, I wrote this extension by using `registerDocumentFormattingEditProvider('javascript', {})`. And I don't change my code ,so I just suppose that vscode will use the default format method first.

**Comment by dbaeumer** [comment]
@jrieken can you shed some light on this. IMO the JS formatter will not be invoked in that case.

**Comment by jrieken** [comment]
@Lonefy Our JavaScript language service is now and real extension. This means, the rule of having a single best match for the `DocumentFormattingProvider` comes into play (https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L3490). 

Since both (yours and ours) have the same score the provider registered last wins. You can restore the previous behaviour (that is your provider being in charge) by declaring a dependency on the builtin JavaScript mode and thereby being _last_. In your package.json add this

```
"extensionDependencies": ["vscode.typescript"]
``
