### ISSUE TITLE
Using private git repository for extenstion development

### ISSUE THREAD

**Issue by zatsepinvl** [Microsoft/vscode#42963]
I develop my custom extension in private gitlab.com repository. I try to package it via **vsce package**, but get this error: `Error: Images in README.md must come from an HTTPS source: images/start_up.png`.

This error means that I use relative link to image in README.md, but build script can not recognize my private gilab repository mentioned in package.json:
```
 "repository": {
    "type": "git",
    "url": "https://gilab.com/zatsepinvl/vscode-sample-ls.git" (as an example)
  },
```

OK, I apply some WA: just put absolute link to image in README.md and build extension successfully.
The problem is that, when I install manually my extension in vscode there is no image seen in details due to private repository. 

![image](https://user-images.githubusercontent.com/11683340/35819664-657d4d22-0ab4-11e8-9b99-c2fa11a21e7b.png)

The main question is how to develop and install vscode extensions being under private repository?

**Comment by joaomoreno** [comment]
You can use private repos for extensions. You obviously can't reference to images hosted by the private repository hosting site. Put your images somewhere publicly accessible.

Additionally, VSCE doesn't recognize gitlab repositories. That's something else. If you want that to happen, file a feature request in https://github.com/Microsoft/vscode-vsce. Although it wouldn't fix your case since your repository is private.

**Comment by zatsepinvl** [comment]
OK. How can I use relative paths to images in README.md and see them in details in vscode extension information?

**Comment by joaomoreno** [comment]
Once you upload them to somewhere publicly, you can then use absolute URLs.
