### ISSUE TITLE
Extension handlers should be added to HKLM not HKCU

### ISSUE THREAD

**Issue by knoxyca** [microsoft/vscode#43053]
- VSCode Version: 1.19.3
- OS Version: Windows 10 1709

Steps to Reproduce:

1. Install VS Code as administrator account (different from your normal every day account).
2. Select to add "Edit with VS Code" to context menu
3. Do not get "Edit with VS Code" in context menu because they're installed to HKCU instead of HKLM.

Does this issue occur when all extensions are disabled?: Yes

This makes it very frustrating to try and use VS Code in a corporate environment, or an environment where your normal account is not an administrator on the computer.

**Comment by dsolodow** [comment]
I've run into (and been frustrated by) this issue as well, however I think a different approach will be required. 
The issue is that while a per-user (HKCU) association/handler can over-ride a system-wide one (HKLM) I don't believe it can *remove* one. 
My inclination would be to either:
a) add a parameter to code.exe  that registers/unregisters the right click options and exits
b) include (or put in the GitHub repo) a script/batch to register/unregister and notify the shell

**Comment by knoxyca** [comment]
So I've done something productive with my frustration and extracted the Classes keys from my admin user into a unified .reg file in a gist here: https://gist.github.com/knoxyca/e9631448c0e2ade7beaa18335d5e77bf 

This will add the context menu for the current user. This doesn't solve another (albeit different) issue where the Path that gets updated is also the per user one, and at least on Windows 10, you can't even access that through the GUI.

**Comment by dsolodow** [comment]
I think it depends on how you try to access it; if you go the old Control Panel > System > Advanced System Settings you need to be an admin.
However, if you go to the new Settings panel (Windows key + i) and then type"environment" you'll get a choice to "Edit environment variables for your account" which lets you modify PATH and others for your account without elevation.
