### ISSUE TITLE
editing in visible editor affects folding in not visible split editor when made visible again

### ISSUE THREAD

**Issue by uday0408** [Microsoft/vscode#43063]
- VSCode Version: 1.19.3
- OS Version: macOS 10.13.3
- Code: C#

Steps to Reproduce:

1. Make two dummy C# files (file1, file2) with empty nested methods and open them in VSCode.
2. Use Split editor (left, right groups), and display file1, file2 in both left and right.
3. On left and right, display file1.
4. On left, fold some regions in file1
5. On left, switch to file2.
6. On right, make some modifications to file1 and save.
7. On left, switch back to file1

Result: Folding in file1 on left is lost.

**Note**: If step 5 is not done, i.e. on left file1 is kept in view then after step 6, the folding in file1 on left is preserved. Seems like not having editor visible and making it visible again looses the folding.

Does this issue occur when all extensions are disabled?: Yes

![vscode_split_editor_folding_lost_2](https://user-images.githubusercontent.com/4966157/35885780-d496d612-0b43-11e8-8cc1-e1184b3087f2.gif)

**Comment by aeschli** [comment]
When an editor becomes hidden it actually get disposed. When it get visible it is recreated and we restore the previously stored folding ranges, but in this case the doucment has changed since the editor was closed, so we don't restore.

Not disposing the editor is not an option (you can have a lot of tabs). Restoring the ranges on a document that has changed will lead to strange effects and other bugs reported.

I'm in flavor to live with this behaviour.
