### ISSUE TITLE
Launch.json not automatically opened when resolveDebugConfigurations returns an error

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#43133]
This is a regression from the current stable.

Currently it is not possible for debug extensions to make vscode automatically open the launch.json in case they can not properly resolve a launch configuration.

Currently this is shown in the Dart extension, however @dantup and me have worked on a workaround.
So I would wait more until choosing to have this in the recovery release.

**Comment by DanTup** [comment]
I've pushed an update to Dart Code with the workaround which at least fixes the issue of not being able to debug; however the user experience is a bit naff - when a user hits F5 on a project without a `launch.json` they are prompted twice to select the debug type/environment. Although I've noted that in the release notes; no doubt we'll get bug reports about it - so if it's not really risky, we'd obviously really like to see it in the recovery build.

**Comment by Tyriar** [comment]
Verified via code review

**Comment by DanTup** [comment]
@isidorn Just checked this in the recovery release and it doesn't seem to do what this issue suggests; it still shows the error to the user and does not open the `launch.config`.

![err2](https://user-images.githubusercontent.com/1078012/36217124-8c4915e4-11a8-11e8-8862-1825ddf4576a.png)

**Comment by DanTup** [comment]
However, setting `debugConfig.type = null;` does cause it to open, so I no longer need to call `commands.executeCommand("workbench.action.debug.configure");`.

**Comment by isidorn** [comment]
@DanTup exactly, the idea with the recovery release fix was for you to set `debugConfig.type = null`. Sorry if I did not communicate that clearly

**Comment by DanTup** [comment]
Ah, ok!

The current workaround is working fine in 1.20.0 and 1.20.1, I was just tidying up code for my next release. I'm going to remove the `executeCommand` call and leave the `type=null` code. I will also flag is as requiring Code 1.20.1.

Going forwards, what is the preferred way for me to get `launch.json` opened? Should I throw an error? Throwing seems a little weird, but then so does setting type=null because the launch.json then appears with a type populated!

**Comment by isidorn** [comment]
@DanTup for now let's leave the curent weird behavior that you leave `type=null`.
IMHO the proper way would be for you to throw an error in your resolving of the configuration.
Are you maybe interested in contributing to VSCode to handle this case properly. 
Here's a pointer https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/debugService.ts#L764 
where you would have to open a launch.json

**Comment by DanTup** [comment]
Sure.

My only concern with throwing an error is that it causes unexpected behaviour when there's a legitimate error. Eg. I wrote some bad code in my extension, and rather than seeing the error it just silently opens `launch.json` - and if it's not silent, then it will look like an error to my users when I actually wanted it. That's why it seems like there should be a more explicit way of communicating this.

Setting up Code so I can contribute to it has been on my todo list for a while; it's just not gotten to the top yet! So much to do :(
