### ISSUE TITLE
1.20.0 IntelliSense only displays words

### ISSUE THREAD

**Issue by rwu823** [Microsoft/vscode#43155]
- VSCode Version: 1.20.0
- OS Version: macOS 10.12.6

Does this issue occur when all extensions are disabled?: Yes

1.19.3 IntelliSense works great and when I begin starting VSCode it show: `Fetching data for better TypeScript IntelliSense` on status bar, but it doesn't  happend in 1.20.0

![vsc1 19 3](https://user-images.githubusercontent.com/890063/35953481-d0590200-0cbf-11e8-9423-35f4e8bc20f0.png)

1.20.0 only displays words
![vsc1 20 0](https://user-images.githubusercontent.com/890063/35953548-23df10d6-0cc0-11e8-81bc-6ad64be5d9c5.png)

**Comment by rwu823** [comment]
![image](https://user-images.githubusercontent.com/890063/35958918-2f92b4a0-0cde-11e8-8e09-7e6e358afa37.png)

Updated: if switch to use TypeScript 2.6+ it'll work great

**Comment by mjbvz** [comment]
@rwu823 Looks like type acquisition is failing. Can you please try collecting the typings installer log so that we can investigate:

1. Set `"typescript.tsserver.log": "verbose"` in your user settings and restart vscode
2. Reproduce the problem
3. In VS Code, open a js file and run the `Open ts server log` command.
4. This should open a directory. Please share the`ti-xxx.log` file in the opened directory. This has information about typings installation

Thanks

**Comment by rwu823** [comment]
@mjbvz There is my `ti-xxx.log` 

https://gist.githubusercontent.com/rwu823/edebd740f5a973a8b1775bcf7e103466/raw/9168707113e889a2089e3fbf8f8ed7b5a6e17fd3/ti-58123.log

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#21890
