### ISSUE TITLE
Console jumps to Debug Console when console is set to integratedTerminal

### ISSUE THREAD

**Issue by jpike88** [Microsoft/vscode#43164]
- VSCode Version: 1.20.0
- OS Version: 10.13.2 macOS High Sierra

Steps to Reproduce:

1. Launch a NodeJS app with console set to integratedTerminal in the launch config
2. Expect the Terminal tab to fire up, instead the Debug Console fires up instead and you have to manually switch to the Terminal.

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
The `console` configuration is contributed by the node debug exception [here](https://github.com/Microsoft/vscode-node-debug/blob/master/package.json#L326).
VSCode is not aware of this attribute.

Due to that I propose the following fix:
* Node debug in the resolve debug configurations checks if the `console` field is present and if it is there it sets the `"openDebugOptions": "neverOpen"` in the configuration on the fly. This way vscode will not open the debug console and everything will work fine.

**Comment by weinand** [comment]
I do not like to tie the `internalConsoleOptions` attribute to a specific value of the `console` attribute. That introduces obscure magic and I'm pretty sure that someone will file a bug against that.

Instead I suggest that you add an `"internalConsoleOptions": "neverOpen"` to your launch config.

**Comment by jpike88** [comment]
But then you're just introducing obscurity for the user. It took me ages before I was going nuts to google it and sift through GitHub issues to find this workaround.

**Comment by weinand** [comment]
It is always a good idea to first use Intellisense to see what options are available.

**Comment by weinand** [comment]
We've revisited this issue and came to the conclusion to implement @isidorn's suggestion (but only if the user has not defined `"internalConsoleOptions"` himself).
