### ISSUE TITLE
Use only relative paths in extenstion README.md

### ISSUE THREAD

**Issue by zatsepinvl** [Microsoft/vscode#43173]
Imagine that:
- Work with vscode behind a proxy, there is no connection to the public Internet area
- Implement vscode extension without git repository and set relative path to images in README.md (There is no way to set absolute url due absence of image hosting and git repository)
- Successfully build custom vscode extension
- Want to check how custom extension's README.md is look in vscode
- Install custom extension in vscode
- See no image, but warning: 
     `[Embedded Page] Refused to load the image 'file:///C:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/parts/html/browser/images/custom_extension_image.png' because it violates the following Content Security Policy directive: "img-src https:".`

So question is how to use relative paths in extensions README.md?

**Comment by mjbvz** [comment]
What does image reference in the `README.md` look like? Just `![](path/to/img.png)` or similar?

**Comment by zatsepinvl** [comment]
Yes, relative to root of extension package.

**Comment by mjbvz** [comment]
I feel this is out of scope. If you were to publish that extension to the marketplace, the images also would not show up. The fix for this would only apply to vsixs that have been manually installed and are not using github or similar for image hosting. The added complexity of addressing this properly does not seem worth it
