### ISSUE TITLE
Intellisense parameter help popup reappears after dismissing it

### ISSUE THREAD

**Issue by stevencl** [Microsoft/vscode#4320]
- VSCode Version: 0.10.12
- OS Version: Windows 10

Steps to Reproduce:
In the following code, toDoListItem is an array. 

    $scope.AddItem = function (data) {
        $scope.toDoListItem.push

When I write the code to push new items on to the array I get the intellisense parameter help. I press Esc to dismiss the tooltip and fill in the rest of the code to add elements to the array. I pass in a small JSON object with two fields. As soon as I type the ',' to enter the second field of the object, the parameter help tooltip appears again, obscuring the code that I have written. I press Esc again to dismiss the parameter help.

I expected the parameter help not to come back up while I was writing code inside this block.

See this animated gif for more details:
![popup](https://cloud.githubusercontent.com/assets/1704059/13817868/b6513636-eb8b-11e5-9f70-2f3fd8d792b6.gif)

Found while testing: https://github.com/Microsoft/vscode/issues/3715

**Comment by dbaeumer** [comment]
@joaomoreno moving to you. Looks like a UI problem.

**Comment by joaomoreno** [comment]
Parameter hints gets triggered every time the user presses a parameter hints trigger key. In TypeScript that is `(` and `,`. But it's still up to the mode whether to show the hints, upon requested. If the hints are showing in that snippet is because TypeScript returned them. There is no way the widget or the editor would have knowledge that those hints should not be shown. Only the mode would know not to show them.
