### ISSUE TITLE
Icons for TreeViewItems fallbacking to default folder item if file uri is used. 

### ISSUE THREAD

**Issue by Krzysztof-Cieslak** [Microsoft/vscode#43216]
Example: 
![image 1](https://user-images.githubusercontent.com/5427083/35978658-a2b514b6-0ce6-11e8-8b6d-0b450298c25b.png)

As far as I understand this line is a problem - https://github.com/Microsoft/vscode/blob/5755810a58ac76ffedb037647f1cd6fec406efe9/src/vs/workbench/browser/parts/views/treeView.ts#L334

If an item has Expended or Collapsed state (which basically means it's an item with childs) then we expect folder icon. 

In general, I don't think we should have such convention at all, and consumers should be able to set any icon they want - in case of my extension, tree view shows some information from the file, so it makes sense for me to use file icon on the node with child elements.

CC: @sandy081

**Comment by sandy081** [comment]
@Krzysztof-Cieslak Yes, I was assuming all resources with children as folders which is true in File explorer but not in custom views. So we need a convention to determine if a resource URI is a directory/folder or not.

One [convention](https://en.wikipedia.org/wiki/URL_normalization) is to have a trailing slash to indicate if URI is for folder/directory or not.

**Comment by Krzysztof-Cieslak** [comment]
Couldn't we just check whether URI points towards folder or file with FileSystem API? Or that would be too slow?

**Comment by sandy081** [comment]
I do not think that is a good idea, because some of the URIs could be pointing to remote locations and it will make tree much slower.

**Comment by vbfox** [comment]
I need to check a few things before reopening my pr but what i did essentially was to keep the current behavior by default and allow extension developers to be explicit about folder/file

**Comment by sandy081** [comment]
To verify:

- Contribute a tree view. Refer to [documentation](https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributesviews) and [samples] (https://github.com/Microsoft/vscode-extension-samples/tree/master/tree-view-sample).

- If you specify [ThemeIcon.Folder](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L784) to [iconPath](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L5105) in your `TreeItem`, then a folder icon will be provided to your node based on current file icon theme.

- If you specify [ThemeIcon.File](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L779) to [iconPath](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L5105) in your `TreeItem`, then a file icon will be provided to your node based on current file icon theme.

- If you provide a [resourceUri](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L5113) and **no** `ThemeIcon` to `iconPath` then the node will be treated as folder if it has children otherwise file.
