### ISSUE TITLE
Page Up / Page Down in Debug Console

### ISSUE THREAD

**Issue by leegee** [Microsoft/vscode#4326]
- VSCode Version: 0.10.11
- OS Version: Microsoft Windows [Version 10.0.10586]

Steps to Reproduce:

Try using page up, page down in the debug console, and instead waste time and patience using using cursor keys or mouse :)

**Comment by bpasero** [comment]
Fyi I can use page up/down when the debug console contents has focus to navigate up and down. We have commands for the tree and list that cover page up/ page down.

**Comment by leegee** [comment]
Still not working for me, this time on build 1.12.2 on Windows 7 (ugh).

**Comment by isidorn** [comment]
@leegee are you sure that the debug console contents have focus in your case. Namely, the debug console always auto focuses the input. 
In order to focus the tree you need to `F1 > Tab Key Moves Focus`
Then go to the debug conosle and press `shift + Tab` -> now pg up, pg down should be working

I think we should improve this experience but the point is just to see if this solves the issue for you.

**Comment by leegee** [comment]
Does it get focus if I click in it with the mouse?

**Comment by isidorn** [comment]
@leegee no. It always auto moves focus to the input to make it more convenient in th 90% use case

**Comment by leegee** [comment]
Now works for me! Thank you.
