### ISSUE TITLE
Issue Reporter: re-enable extensions

### ISSUE THREAD

**Issue by borekb** [Microsoft/vscode#43298]
I've tried reporting an issue via the Issue Reporter for the first time and there were two UX issues with it:

First, the blue link to disable extensions was missing the hand pointer so it was not clear what the clicking will do:

![image](https://user-images.githubusercontent.com/101152/36019895-f9c29a40-0d80-11e8-9403-8a7e966fdd32.png)

Probably worse, clicking the link disabled all my extensions and I don't know how to turn the relevant ones back on. I've restarted VSCode and all my extensions are still disabled. I have about 30 of them and about 25 were enabled, 5 disabled. Now I assume I will need to go one by one, try to remember if it was previously enabled or disabled, and do that manually which is not something I'm looking forward to :)

### VS Code Info

VS Code version: Code 1.20.0 (c63189deaa8e620f650cc28792b8f5f3363f2c5b, 2018-02-07T17:10:31.920Z)
OS version: Windows_NT ia32 10.0.16299

Reproduces without extensions

**Comment by MaleDong** [comment]
Agree, the most puzzing thing for me is that I don't know what to do next after clicking "disabling all extensions...." ect.

I suggest the plug-in window can be designed like this following:
![default](https://user-images.githubusercontent.com/6959154/36020782-c3f5e686-0dbe-11e8-9b0e-5542c525ad31.png)

1. Each plug-in will show you a status (green for "enabled" and red for "disabled", maybe "enabled (workspace)" or "disabled (workspace)"), depending on which kind of state you choose by clicking the "settings" icon beside it.

2. And each plug-in should have a check box that we can let them multi-choosen. And when we choose some/All of them, and click "Checks Enabled"：All the "checked" plug-in will be "enabled" and on the other side, "disabled", so changed the words of the button itself.
This option isn't for "workspace enable/disable" but only for globally enable or disable plug-ins.

3. On the head bar of "Extensions" there should be a multi-choosen check box with which we can do multi chooses.

**Comment by RMacfarlane** [comment]
@borekb I've changed the behavior of `disabling all extensions and reloading the window` so that the extensions are only temporarily disabled. Reloading VS Code will return them to the original state they had, and the cursor now correct displays as a hand. Sorry for the inconvenience, let me know if that makes sense.

**Comment by borekb** [comment]
Hi @RMacfarlane , sounds good but when I tried it, the extensions stayed disabled. Steps to reproduce:

1. Go to issue reported, click **disabling all extensions and reloading the window**
2. The window is reloaded, all extensions disabled
3. Close the **Issue Reporter** window
4. Invoke the **Reload Window** command from Ctrl+Shift+P palette

**Comment by borekb** [comment]
Oh I needed to restart VSCode entirely. That enabled the extensions as you said. Before that, they were in a weird state that I haven't seen before:

![image](https://user-images.githubusercontent.com/101152/36584011-5832a21c-1878-11e8-92e6-95eb8710c1dc.png)

**Comment by RMacfarlane** [comment]
Yeah, that state is expected. It's the same as running VSCode with the `--disable-extensions` flag, the extensions are not added to the list of runtime extensions, so they are not activated and their state can't be changed.

**Comment by RMacfarlane** [comment]
Meant to close this out earlier. Verified with https://github.com/Microsoft/vscode/issues/43156

@borekb The UI should now indicate this state with "Disabled" text next to all extensions instead of the usual button to toggle state
![screen shot 2018-04-04 at 11 20 17 am](https://user-images.githubusercontent.com/3672607/38326288-4af4a612-37fa-11e8-85a3-930461dad0ca.png)

 and soon there should be a notification that pops up saying that all extensions are disabled when this state is entered

**Comment by Neutrino-Sunset** [comment]
@RMacfarlane 
> Yeah, that state is expected.

Except that is not expected by anyone using the software who is not familiar with the details of the implementation (basically anyone except yourself) because nothing in the UI explains that the extensions are all disabled until you restart VSCode. This is a tragically bad UI design.

**Comment by RMacfarlane** [comment]
@Neutrino-Sunset Thanks for the feedback, you're right that it's not intuitive and really needs more explanation. I've filed https://github.com/Microsoft/vscode/issues/47506 to track this, please have a look.
