### ISSUE TITLE
When i update to the latest version intellisense doesn't download *.d.ts

### ISSUE THREAD

**Issue by qfdk** [Microsoft/vscode#4333]
- VSCode Version: 0.10.11
- OS Version: MAC OS10.11.4

Steps to Reproduce:
1. create `jsconfig.json`
2. typer`__dirname` in `server.js`

It can't download the `node.d.ts`, but in version 0.10.9 it works.
Can your team re-add this function in the latest version ?
![20150921203749](https://cloud.githubusercontent.com/assets/2404478/13825452/f1b5960a-ebb2-11e5-8f64-996a8edd14c0.jpg)

We don't want to use `tsd install node express` for each time ...
Thx

**Comment by qfdk** [comment]
1 use tsd install node.js 
2 code.
3 create a jsconfig with VSC

the lintellisense will work after reloading the VSC. The user experience isn't as good as the version 0.10.9

**Comment by egamma** [comment]
Improving the support for fetching .d.ts files is on the backlog, but will not be in the March update, sorry.

**Comment by mjbvz** [comment]
The TypeScript team has done work to [automatically acquire typings file in the background to improve intellisense](https://code.visualstudio.com/updates#_better-javascript-intellisense). This feature was originally shipped in 1.7, but had to be disable due to a some performance concerns. However, we will be enabling it again soon and you can already try it out in the latest insiders builds.

Please try this out and let me know if you run into any problems. Thanks.
