### ISSUE TITLE
"Rename current file" command?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [Microsoft/vscode#43344]
We can do it by launching the file explorer and then pressing F12. It'd be convenient to have a single command for it.

**Comment by ozra** [comment]
This is something I've missed since GoldEdit on the Amiga (if memory serves, probably not). "Refactoring filenames", etc, are such common events for a programmer. Wonder how much time is lost in the world because of stale files, edited and saved to the wrong location after moves, etc. It should be possible to "rename" into another dir too, of course.

An additional support for _ultimate editing integrity_ would be an inotify plugin that listens to open files for moves, and could see where they're moved by looking up symlink in `\`/proc/self/fd/${fd}\`` via file-descriptor and update the reference in the editor.

It's quiet surprising really that the fundamental state management of our primary resources as programmers isn't in place after all these decades. Such a wacky industry XD

**Comment by V-ed** [comment]
I feel like this should be integrated into VSCode indeed, but until then, this extension does the job fine for me : [Fil Utils](https://marketplace.visualstudio.com/items?itemName=sleistner.vscode-fileutils).
