### ISSUE TITLE
Missing Native support for TFS

### ISSUE THREAD

**Issue by roopkt** [Microsoft/vscode#43384]
I am wondering when VSCode will support TFS natively. Like it has support for GIT. I installed TFS-VSCode extension, however that is not working nicely. Anytime I add or delete or rename a file TFS does not recognize. I also created an issue https://github.com/Microsoft/vsts-vscode/issues/362

**Comment by guillaume86** [comment]
Would it be possible to have a discussion about official TFS support?

Or maybe just sponsor the existing extension author to give him incentive to make the extension feature complete? (annotate is a must for example)

It's disappointing from Microsoft to not support their own SC system in one of their product, integrating VS Code in my company workflow has been a pain because of this.
