### ISSUE TITLE
Undoing deletion a tag angle bracket (>) results in another tag closer

### ISSUE THREAD

**Issue by Tadaboody** [microsoft/vscode#43396]
### Issue Type
Bug

### Description

1.create .html file
2. write any `<tag> </tag>` with at least one character between them (for example space/newline)
3. delete the opening tags angle bracket (resulting in `<tag </tag>`)
4 .undo - you now have `<tag></tag> </tag>`

### VS Code Info

VS Code version: Code 1.20.0 (c63189deaa8e620f650cc28792b8f5f3363f2c5b, 2018-02-07T17:09:39.780Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|Memory (System)|15.88GB (8.34GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
make-hidden|dev|2.2.1
beautify|Hoo|1.3.0
vscode-discord|max|1.0.2
gitignore|mic|1.0.1
debugger-for-chrome|msj|4.1.0
vscode-icons|rob|7.19.0
code-settings-sync|Sha|2.8.7
vscode-surround|Swo|1.0.1
vim|vsc|0.10.13

(1 theme extensions excluded)

</details>
Reproduces without extensions

**Comment by aeschli** [comment]
It's difficult to guess the users intent. Is the intent to complete an existing tag or is it inserting a new nested tag.
Right now, the closing pair is inserted unless one starts *directly* after the cursor. If that was the wrong guess, press `undo` to remove the closing tag.

I keep the issue open and we can tune the strategy if other users feel the same (in that case, please add 👍 to the description)

**Comment by subshock** [comment]
This is not a feature request, it's a bug. The key part of this is that the tag completion happens when the undo command occurs.  The tag completion shouldn't be running after an undo command as it screws up the undo/redo chain.

An example of how the chain gets broken.
1. Start with `<div>1</div>`
2. Select `<div>` and delete
3. Change the 1 to a 2
4. Undo twice
5. The editor ends up with `<div></div>1</div>`

Redo now will not work as the tag completion edited the document and broke the previous chain

**Comment by aeschli** [comment]
@subshock That's a slightly different issue: https://github.com/microsoft/vscode/issues/52777

**Comment by aeschli** [comment]
I now think it's a dup of #52777. Undo should not trigger a auto-close
