### ISSUE TITLE
[Node.js] Browser does not launch and missing set breakpoint

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#4341]
- VSCode Version: 0.10.12-alpha
- OS Version: Windows 10

Steps to Reproduce:
Following #3960 test tour
1. Create Azure Node.js Express (JavaScript) Project
2. Set a breakpoint in app.js at the line (or app.ts): 
`var app = express()`
•Set a breakpoint in routes\index.js (or routes\index.ts) at the line that begins with: 
`res.render('index'`
3. F5 or start debugging

Actual:
1. Does not launch the browser
2. Second break point is not hit

**Comment by isidorn** [comment]
Launching the browser is not expected, we never open the browser for the user.
As for the breakpoint not hit - forwarding to @weinand

**Comment by weinand** [comment]
@vsccarl thanks for trying to go through the #3960 tour (which was based on some Visual Studio tour and is not a good fit for VS Code).

I've verified that hitting a breakpoint in app.js on line `var app = express()` and in `routes\index.js` works fine.

For the TypeScript additional setup was necessary because the template does not include any support for transpiling ts to js and producing source maps. After this done, breakpoints were working fine.

/cc @egamma
