### ISSUE TITLE
Incorrect auto intend YAML files

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#43424]
From https://twitter.com/trondhindenes/status/961944911846215680

![image](https://user-images.githubusercontent.com/172399/36074051-b721b3b8-0f3a-11e8-8dc8-d1c469006ca6.png)

https://video.twimg.com/tweet_video/DVmV_wjW0AAuryy.mp4

Caused by this PR https://github.com/Microsoft/vscode/pull/41378

@aeschli can you please review whether this is a candidate for the recovery build and adjust the label/milestone as needed.

**Comment by aeschli** [comment]
The newly defined indentationRules look fine and useful to me.

The problem is caused by the "editor.autoIndent"` feature. It results in different behaviour when `indentationRules` are defined vs. undefined. It behaves as disabled when no rules are defined.

IMO the correct fix is to turn off indent on paste for YAML. Indentation defines the structure of a YAML program and the user typically very consciously at with a certain indentation. By modifying it, we change the users intent.

@rebornix FYI

**Comment by rebornix** [comment]
@aeschli thanks for investigating this issue for me, the change looks good to me.

**Comment by aeschli** [comment]
@rebornix Can you push it to release/1.12 as well?
