### ISSUE TITLE
intellisense is not showing top options first

### ISSUE THREAD

**Issue by luisrudge** [Microsoft/vscode#43429]
everytime I hit ctrl+space for auto completion of parameters, I have to scroll up up up until I find the interface options.

<img width="624" alt="image" src="https://user-images.githubusercontent.com/941075/36074572-fced770e-0f28-11e8-94c9-d3f78f5354f3.png">

<img width="660" alt="image" src="https://user-images.githubusercontent.com/941075/36074604-9cd640ca-0f29-11e8-8437-0a87f5d1f5b0.png">

`"editor.snippetSuggestions": "bottom",`

vscode: Version 1.20.0 (1.20.0)
mac osx 10.13.3

**Comment by usernamehw** [comment]
https://code.visualstudio.com/updates/v1_20#_suggestion-improvements

**Comment by luisrudge** [comment]
I think the current behavior is a bit confusing and totally not something I would expect.

Let's run some scenarios:

## Scenario 1
```
"editor.snippetSuggestions": "top",
"editor.suggestSelection": "first",
```

### ctrl+space when writing ts
![image](https://user-images.githubusercontent.com/941075/36206050-219a882a-1178-11e8-8ca2-f9182876ef3b.png)

### That's exactly what I expect

### ctrl+space when trying to autocomplete some interface properties
![github-1](https://user-images.githubusercontent.com/941075/36206145-6e63610e-1178-11e8-88bb-7ba94b876e91.gif)

### That's **NOT** what I expect. If I'm trying to auto complete properties, they should be the first one to be shown at all times.

## Scenario 2
```
"editor.snippetSuggestions": "bottom",
"editor.suggestSelection": "first",
```

### ctrl+space when writing ts
![image](https://user-images.githubusercontent.com/941075/36206201-a965cd0a-1178-11e8-977a-bb805bd5a158.png)


### That's **NOT** what I expect.  I'm trying to writing code, not instantiating a new thing. So snippets should take precedence over other stuff.

### ctrl+space when trying to autocomplete some interface properties
![github-2](https://user-images.githubusercontent.com/941075/36206327-1d862504-1179-11e8-906b-78caf1f3a19a.gif)

### That's exactly what I expect

=============================================

So, I hope I'm not asking too much here, but how can I mix both "modes" in a way that the editor is smart enough to "activate" the correct mode for the task?

**Comment by chanlito** [comment]
I'm also having this issue too, when I ctrl + space I expect top result to be property of interfaces, classes .... not having to scroll up to find them.

**Comment by JoelEinbinder** [comment]
When writing JavaScript, seeing a bunch of word selections signals to me that Intellisense lost track of my object and is considering it an `any` type. With the new behavior, it took me a few days to realize something was wrong with the suggestion box instead of the autocomplete. I think the old behavior should be the default.

**Comment by jrieken** [comment]
There is two things that collide... For once our snippets aren't contextual and always computed (without any language smarts). So, they are always there but by default sitting at the bottom. With the new suggest-memories  tho we might reveal them too aggressively. We can tweak that (e.g. don't use the memory when the line is empty). Until then you can use this setting: `"editor.suggestSelection": "first"`

**Comment by luisrudge** [comment]
@jrieken I tried this, you can see in both my scenarios I had this set to "first", which still makes it unusable with either snippets or properties (depending on the `editor.snippetSuggestions`)

**Comment by jrieken** [comment]
Yeah, once you "boost" snippets you will run in the issue of snippets being without context

**Comment by luisrudge** [comment]
@jrieken and if I don't boost the snippets, then snippets are not usable at all. Is there a way to rollback to the way it worked before? Or any set of configurations that emulates what we had before?

**Comment by jrieken** [comment]
Setting this `"editor.suggestSelection": "first"` is actually the "before" behaviour.

**Comment by luisrudge** [comment]
idk man.. Me and everyone else here didn't have this issue before.. so I'm guessing something changed.

**Comment by jrieken** [comment]
Well, I was out three weeks but I am pretty sure that I am the only one working this feature. The default value for `editor.snippetSuggestions` is `inline` (since at least [10 months](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/config/editorOptions.ts#L2269)). The implementation of `top`, `bottom` [didn't change](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/suggest/suggest.ts#L174) in more than a year.  

The new feature is about selecting not sorting and to restore the old behaviour use:  `suggestSelection: first`. That means always *select* the item *sorted* to the top.

I know that doesn't make this less frustrating and I totally agree with the static-snippet vs dynamic-completions dilemma but I don't think that this is new.

**Comment by luisrudge** [comment]
Makes sense. I'm not sure why I only noticed this now then. It was my first project with typescript, so maybe that's why 😝 
Do you think what changed is the scroll position of the suggestions? Maybe that's why more people feel that the whole suggestion situation changed?

**Comment by chanlito** [comment]
Did the vscode team broke something or it's a new feature? This behaviour never happened before.

**Comment by jrieken** [comment]
> Do you think what changed is the scroll position of the suggestions

Yeah, what's what I mean by selection. The `first` setting restores the old behaviour, the default should be conservative enough but there is plans to skip the memory when on an empty line

**Comment by jrieken** [comment]
This comment explains what each setting does: https://github.com/Microsoft/vscode/issues/41060#issuecomment-364284879

**Comment by DanTup** [comment]
@jrieken 

> there is plans to skip the memory when on an empty line

I just got this:

<img width="462" alt="screen shot 2018-03-26 at 11 11 01" src="https://user-images.githubusercontent.com/1078012/37900576-8742dcd0-30e6-11e8-9f7f-45fe47cabc3f.png">

I believe it's pre-selected `override` because of the prefix of a space, so I don't think the empty line rule will fix all the issues. Maybe the prefix should be ignored if there is any leading whitespace?
