### ISSUE TITLE
"Open Folder Settings" doesn't do anything in a single-root session

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#43430]
I have a single folder open (not a multi-root workspace). When I execute the "Open folder settings" command nothing happens.

I guess this is because in a single-root instance the settings are considered "workspace level"; however I think it's reasonable to expect this command to just open that setting. If not, there should at least be a message telling the user why the command failed to do anything.

**Comment by sandy081** [comment]
Ideally this command should not shown in single folder case. Just like open workspace settings should not be shown in empty workspace case.

**Comment by DanTup** [comment]
@sandy081 Isn't it still valid to have folder-level settings in a workspace?

**Comment by DanTup** [comment]
Also; in this case I only had a single folder open, so isn't "folder settings" the correct thing?

**Comment by sandy081** [comment]
@DanTup I think it will be confusing to the user if we show workspace settings when user asked to open folder settings. Current solution is consistent with showing what is requested.

In a multi folder workspace, we open folder settings with default settings also showing Folder settings. 

![image](https://user-images.githubusercontent.com/10746682/36198152-13c68d54-1176-11e8-9023-5bbf193a5190.png)

IMO, in single folder workspace, if user opens folder settings, showing a view similar to above instead of workspace settings is the right approach. Please open a feature request if it makes sense. Thanks.

**Comment by DanTup** [comment]
> I think it will be confusing to the user if we show workspace settings when user asked to open folder settings. Current solution is consistent with showing what is requested.

I don't think that's what I'm asking for; I think the confusion is that when a workspace has only one folder you're referring to the "folder settings" (eg. the ones that live inside `.vscode\settings.json` and not inside a `.code-workspace` file) as "workspace settings". This doesn't seem to make sense to me. Workspace settings should be those in the workspace file which apply to the set of folders that are open. Folder settings should be those inside the folder.

For example, consider this:

1. Open a single folder
2. Add something to the workspace settings
3. Add an additional folder to the workspace

The "workspace setting" that you added in step 2 is not actually applied to the workspace, it is applied only to one folder.
