### ISSUE TITLE
VSCode continuously sends/receive data from sftp server

### ISSUE THREAD

**Issue by abhijangda** [Microsoft/vscode#43442]
I have one folder in my workspace hosted on a server, which I access using sftp mounted directory. The server is accessed through a private VPN. Unfortunately, VSCode keeps sending and receiving data from the sftp server even if I am not working. I have disabled telemetry and git. Looking over the network packets from WireShark confirms that it is still accessing the server.

- VSCode Version: 1.20
- OS Version: Fedora 24 Linux 4.11.12

Steps to Reproduce:

1. Connect the server through VPN and mount the directory using sftp.
2. Add a folder from that directory to your workspace.
3. You can see continuous sending and receiving of data.

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment]
Maybe polling-based file watching?

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by abhijangda** [comment]
@jrieken I disabled new file watcher and the problem still remains.
@bpasero I executed code with all extensions disabled and the problem still remains.

**Comment by bpasero** [comment]
@abhijangda any chance you could check what data is being sent over and attach it here?
