### ISSUE TITLE
Make closing tab to open next/previous tab instead of MRU

### ISSUE THREAD

**Issue by dbkaplun** [Microsoft/vscode#43459]
Usually I tend to leave tabs open, but when I do close tabs, I close many at a time. Current behavior makes it difficult to leave in-progress files open while closing other tabs.

Thanks for considering!

**Comment by bpasero** [comment]
via https://github.com/Microsoft/vscode/pull/66635

**Comment by bpasero** [comment]
**Verification:** play with the `workbench.editor.closeTabsInMRUOrder` and make sure it works as advertised.

**Comment by octref** [comment]
@bpasero It works as advertised, but I think the name can be improved. Something like `revealLastActiveTabAfterClosingTab` as a boolean would make more sense to me.

**Comment by bpasero** [comment]
@SimonEggert as author, do you have a better name in mind? I am also not a big fan of `revealLastActiveTabAfterClosingTab` to be honest.

**Comment by octref** [comment]
Maybe `closeTabBehavior` with enum values `MRU` (or `lastUsed`) and `leftToRight`? I also realize the suggestion was too long.

**Comment by SimonEggert** [comment]
@octref This is what I implemented at first in https://github.com/Microsoft/vscode/pull/66635. After giving it some more thought I would prefer a boolean version over the enum one if a self-explanatory name can be found for it, though. It is just a better representation of the job the setting does (enabling or disabling a certain behavior).

I think you are right to focus on the selection aspect of the setting rather than it just being a closing setting. What do you think about `activateRecentEditorAfterClose`?

**Comment by octref** [comment]
@SimonEggert Maybe `focusRecentEditorAfterClose`. My problem with `closeTabsInMRUOrder` is it sounds like a setting for "closing a bunch of tabs in <setting> order", but the setting actually controls "what happens after closing a tab".
