### ISSUE TITLE
generator method of class autocomplete causes star(*) to be added to next line

### ISSUE THREAD

**Issue by limerickgds** [Microsoft/vscode#43469]
![vscode](https://user-images.githubusercontent.com/9961514/36085057-e0bb2cb8-0ffd-11e8-8777-3aa6ddbaa909.gif)

- VSCode Version: 1.20.0
- OS Version:  macos 10.13.3

Steps to Reproduce:

1.  write one class 
2.  add generator function

![image](https://user-images.githubusercontent.com/9961514/36085038-a8ed91cc-0ffd-11e8-9a26-bde16985c30d.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by octref** [comment]
I'm guessing this is JS, correct?

**Comment by limerickgds** [comment]
@octref yes

**Comment by guthyerrz** [comment]
@limerickgds Did you find a workaround for this? It's really annoying

**Comment by huarse** [comment]
+1

**Comment by elowes** [comment]
keep watching

**Comment by limerickgds** [comment]
@mjbvz do you hava time to fix it ? if you no plan to do, i can  make a PR .

**Comment by KMhook** [comment]
+1

**Comment by alexandrudima** [comment]
It took me a few tries, this **only reproduces when indenting using spaces**

e.g.
```js
class A {
    * test() {
    }
}
```

<img src="https://user-images.githubusercontent.com/5047891/45364013-5dbd0700-b5d9-11e8-9672-fb8d8d35e9c8.gif" width="300" />

**Comment by alexandrudima** [comment]
@matt-potts Please open a new issue, you might be running into a similar, but different issue. This works correctly for me:

![43469-2](https://user-images.githubusercontent.com/5047891/47493609-fd63eb00-d84f-11e8-9167-9f2231c3f746.gif)

**Comment by matt-potts** [comment]
@alexandrudima I've resolved my issue. I went to start a new issue and noticed the advice to try the insider version. I noticed the problem was gone. I then looked at my version and I was on 1.23.1. I then noticed the latest was 1.28. Strangely, It said there was no update available for me. I downloaded the latest and reinstalled. The issue is now gone. Thanks for your help and thanks for putting in the recommendation for the insiders version.
