### ISSUE TITLE
Reporting ‘missing launch.json’ while launch object has been added in global setting.

### ISSUE THREAD

**Issue by axmand** [Microsoft/vscode#43461]
Press F5 Debug report ‘missing launch.json’ while launch object has been add in global setting.

- VSCode Version: 1.2.0
- OS Version: Window 7

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by isidorn** [comment]
@axmand thanks for reporting this. The fix will be in vscode insiders tomorrow. I understand this is breaking behavior compared to our stable, however the fix is not that tricky and I speculate that the number of users depending on this feature are quite small, thus I decided to not make this a candidate (even though it is a regression). Users depedning on this feature can use the insiders from tomorrow.
