### ISSUE TITLE
Extension not activating using workspaceContains (possibly for multi-root workspace?)

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#43493]
My extension is set to activate when the workspace contains a `pubspec.yaml` or `*.dart` file, however when I opened this workspace which has two folders (both of which match both of those) the extension did not activate.

This means things like searching for symbols don't work. Once I open a Dart file the extension does then load.

![ext not active](https://user-images.githubusercontent.com/1078012/36090480-6f89e7c0-0fd8-11e8-95c1-082972d77faa.png)

I don't know if it's related, but there are some errors reported in the console:

```text
[Extension Host] [IPC Library: Search] spawn c:\Program Files (x86)\Microsoft VS Code\resources\app\node_modules\vscode-ripgrep\bin\rg
ENOENT
(at c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\services\search\node\searchApp.js:146:35)
(at Object.t.log (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:122:956))
t.log @ /C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:253
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:253 

[Extension Host]% Array(66) (at c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:712:468)
t.log @ /C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:253
```

**Comment by sandy081** [comment]
Not sure if it is @alexandrudima / @jrieken to own

**Comment by alexandrudima** [comment]
@DanTup I believe the root cause is the exclamation mark next to `cambridge-tests` in your screenshot. i.e. one of the folders of the workspace could not be resolved, and perhaps that is somehow used as a `cwd` for spawning the search process.

@roblourens [Here we are creating the `ISearchQuery`](https://github.com/Microsoft/vscode/blob/2cb15ab3bb9785cb47fdedeb0d919a23eba506bc/src/vs/workbench/node/extensionHostMain.ts#L278), but there is no mention of a `cwd`. Is the process spawned on the first folder passed in?

**Comment by alexandrudima** [comment]
Related: #43317

**Comment by chrmarti** [comment]
This look like #42219.

**Comment by DanTup** [comment]
Aha, I hadn't considered it was related to that. Indeed, it seems to work ok now when I open a workspace that doesn't have the bad first path. Happy for you to close this as a dupe if you think makes sense. Thanks!
