### ISSUE TITLE
ENOENT errors with file event avalanche 

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#4350]
* run the steps from #4010 
* some time to time (my guess is when I kill the ember and thereby removing those new files) I see such errors:
```
Error: ENOENT: no such file or directory, stat '/Users/jrieken/Code/_samples/tssCrash/tmp/broccoli_merge_trees-cache_path-0p3C5qP6.tmp'(…)onError @ fileService.js:536(anonymous function) @ flow.js:134(anonymous function) @ flow.js:73Sequence.sequenceFunction @ flow.js:116(anonymous function) @ fs.js:82
fileService.js:536Error: ENOENT: no such file or directory, stat '/Users/jrieken/Code/_samples/tssCrash/tmp/broccoli_merge_trees-cache_path-7JzsYZ8f.tmp'(…)onError @ fileService.js:536(anonymous function) @ flow.js:134(anonymous function) @ flow.js:73Sequence.sequenceFunction @ flow.js:116(anonymous function) @ fs.js:82
```

**Comment by jrieken** [comment]
![screen shot 2016-03-17 at 09 49 45](https://cloud.githubusercontent.com/assets/1794099/13840867/987ba93a-ec25-11e5-9278-9c2ca5bd3814.png)

**Comment by bpasero** [comment]
Actually I suspect this to be chokidar statting, not us.

**Comment by jrieken** [comment]
looks like our fileserver tbh

`@ fileService.js:536(anonymous function) @ flow.js:134`

**Comment by bpasero** [comment]
True...

**Comment by jrieken** [comment]
having said that it seems to behave OK. I see errors on the console but the explorer seems to recover

**Comment by bpasero** [comment]
I changed the two console.error() calls in the file service to only fire when code is run with --verbose. The errors are harmless because they are ignored in the service. They can likely happen when there are so many events that some of them cause a file resolve although shortly after the file is already deleted. I would also think that changing our file watching strategy away from watching the entire folder recursively to only watch what is need would improve this.
