### ISSUE TITLE
ExtensionHost debugging: debug action window disappears briefly

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#43516]
- VS Code Stable or Insiders
- Windows 10

Steps:
- create hello world extension
- open in VS Code
- press F5

Observe:
Debug action bar disappears and comes back.

It looks like an additional short-living session is created on startup.

I do not see this behaviour on macOS and linux.

**Comment by isidorn** [comment]
This is happening due to how we are connecting to the extension host.
This code path is very delicate since it handles both start, reload, quit, restart. Due to that pushing to backlog and will adress only if there is a bigger brekage.

**Comment by weinand** [comment]
This happens now on all platforms.

**Comment by weinand** [comment]
@isidorn what is the event that makes you turn down the debug session?

**Comment by isidorn** [comment]
@weinand I will now write down the exact ordering of events and what is going on so we can analyize on what is best to be done here.

**Comment by isidorn** [comment]
### Extension launched 
1. Process is created
2. I get a broadcast `Attach`. Currently I handle this by ending a process and starting a new one thus the flash. [Code pointer](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/debugService.ts#L157). I remember I am doing this as a workaround due to some other timing issues.
3. Process is ended
4. Process is created

### Extension restart from first window
1. Adapter exits -> thus process ends
2. I get a broadcast `Attach`, thus I try to end the process (does not exist) and create a new one
3. New process is created

### Extension restart by pressing reload in the second window
1. broadcast `Attach` -> thus I stop the process and start a new one
2. End the process
3. Starting the new one

Notice that in this case I am not getting any event that the debugger has exited and I believe that is the reason why I choose to always end and start on broadcast `Attach`

### Extension is ended from first window
1. Adapter exits -> and process is ended

### Extension is ended by clicking close on the second window
1. Adapter exits -> and process is ended

**Comment by isidorn** [comment]
We also need to be aware of that timing on different machines can be different. I remember that sometimes I would first get the broadcast and only then the adapter exit event and this would screw up my logic, however the current approach is also not error prone to this it seems.

So from this analysis the main issue is the reload in the second window which only sends the `Attach`. Ideally we would change this to not be different from the extension restart from first window, however I believe this is not possible.
I could investigate if it is possible to send some special flag in the broadcast such that we at least we know that it is this "special" case

**Comment by weinand** [comment]
The issue at hand is only item 2. under "Extension launched":

You kill the process that you've just created because you do not know that the attach is not a re-attach. Does it help if you introduce a flag ("somewhere") that tells you whether this is the first attach (which does not require to kill anything).

If you no place (i.e. object) where to store that flag, could you look at the events you receive to find out whether it is a restart?

**Comment by weinand** [comment]
While verifying this I noticed another issue: #48442

**Comment by weinand** [comment]
@roblourens based on my analysis from above I've found a very simple fix for the problem at hand:

If we prevent the stub process from emitting a terminate event on exit, VS Code will not see a 
a short running session.

This simple fix worked for me: https://github.com/Microsoft/vscode-node-debug2/pull/189

**Comment by roblourens** [comment]
Nice diagram, we need a couple poster-sized prints!

**Comment by weinand** [comment]
The fix worked for me when running out of source.
But in the real build it does not work.
So the issue seems to have a timing aspect as well.

Moving back to Isidor and re-opening.

**Comment by isidorn** [comment]
@weinand thanks for investigating. I will look into this

**Comment by weinand** [comment]
Thanks to @isidorn's perseverance we now understand why the new fix in node-debug2 was working for me: I still had the [original fix](https://github.com/Microsoft/vscode/commit/4cce36adf59fbc0f950d608ca187949ac768913c) for this issue in my workspace. And the new fix was relying on the old fix (but I wasn't aware of this). 
So when I reverted the original fix, my new fix stopped working.
So reverting the revert fixes everything...

**Comment by isidorn** [comment]
The fix resulted in https://github.com/Microsoft/vscode/issues/48955, thus reverting and assigning to May.
