### ISSUE TITLE
HTML formatter adding white space

### ISSUE THREAD

**Issue by mhchem** [Microsoft/vscode#43520]
- VSCode Version: 1.19.3

Steps to Reproduce:

1. Create a document with HTML file type
2. Insert `Hello (<span>World</span>)`
3. Call formatter
4. There will be a line break after the `(`, but this will lead to a different rendering of the HTML document.

**Comment by aeschli** [comment]
A new line normally doesn't influence the rendering of your document, unless you are in a
`pre` or `code` element (or your css sets certain styles).

To overide that, you can configure which elements should be formatted.
`"html.format.contentUnformatted": "pre,code,textarea"`

**Comment by aeschli** [comment]
Oh, sorry, my bad, you are right. We use jsbeautify as the underlying formatter. It would be great if you could  create an issue there:
https://github.com/beautify-web/js-beautify

**Comment by mhchem** [comment]
Using http://jsbeautifier.org/ with `<html><body><p>Hello (<span>World</span>)</p></body></html>`, I cannot find any setting that inserts a line break after ther `(`. So, the error might be on your side. Maybe because of the execution (line by line?).

**Comment by aeschli** [comment]
Ok, it's more complicated. jsbeautify has 'span' on the list of elements not be formatted (setting in vscode: "html.format.unformatted").
Because of that they wouldn't insert a new line before it, but they also never format anything inside it, which has confused many users of VSCode when they complained that the formatter is not doing anything.
IMO the correct approach for jsbeautify would be to never put a new line if that means adding a new white space to the content.

We could explain to jsbeautify with that example
```
<html>

<body>
    <hr>Hello (<custom>Worlds</custom>)</hr>
</body>

</html>
```
Never add a new line character between a non-whitespace content and a tag start.

**Comment by mhchem** [comment]
It seems like this is an often-complained-about bug of js-beautify. See https://github.com/beautify-web/js-beautify/issues/841 and all the issues linking there.

**Comment by aeschli** [comment]
@mhchem Thanks for finding that!

**Comment by smlombardi** [comment]
I have a similar issue.  If I have a large block of text, e.g. wrapped with `p` tags, and "format html" I get lots of arbitrary line breaks and spaces inside the plain text in the block for no apparent reason.

![feb-14-2018 09-20-50](https://user-images.githubusercontent.com/835148/36209056-ab1295b2-1168-11e8-9cd7-8ec31adca941.gif)

**Comment by aeschli** [comment]
@smlombardi I think that's not related to @mhchem issue. Please file a separate issue with the code sample. Please also check if it is reproducible on http://jsbeautifier.org/. You want to set the wrapLineLength to 120 like in VSCode.

**Comment by KyleStay** [comment]
I recommend this user setting as a work around in the mean time: 
```json
{
    "html.format.unformatted": "wbr,span"
}
```
