### ISSUE TITLE
Feature request: Make popups less clunky.

### ISSUE THREAD

**Issue by AnthonyJacob** [Microsoft/vscode#43537]
Popup windows for both autocomplete and documentation feel very clunky and not well thought out:

1. Autocomplete popup should appear after pressing backspace (right now it disappears).
2. Info popup (the i icon next to autocomplete) should appear bellow autocomplete, like this:
![untitled](https://user-images.githubusercontent.com/18863976/36118897-c93e17ee-103e-11e8-9ef0-e87212c8479d.jpg)
3. Info popup should have multiple fonts & specific areas for *documentation, type signatures, argument names, etc*.
4. It also should not wrap type signatures, so that you do not end up with:
![untitled](https://user-images.githubusercontent.com/18863976/36119783-5ae690e8-1041-11e8-9ab5-f827436ce51d.jpg)

5. Finally there should be hotkeys to trigger documentation and type signature popup.

**Comment by ramya-rao-a** [comment]
> Autocomplete popup should appear after pressing backspace (right now it disappears).

The popup remains even after pressing backspace

![backspace](https://user-images.githubusercontent.com/16890566/45395627-e6dd3980-b5eb-11e8-8da4-222d6f851cdf.gif)

> Info popup (the i icon next to autocomplete) should appear bellow autocomplete, like this:

This is by design to allow easy reading when the eyes move left to right, instead of moving the focus up to down.

> Info popup should have multiple fonts & specific areas for documentation, type signatures, argument names, etc.

Language features are provided by extensions and VS Code provides the UI to display the same. So while extensions are free to provide the data for the popup, the presentation is controlled by VS Code core which is language agnostic. 

VS Code expects extensions to provide a `label`, `detail` and a `documentation` for each item in the completion list. 

`label` is shown in the list
`detail` is shown in the top part of the info pop
`documentation` which is longer text is shown below the `detail`

So the expectation is that the `detail` contains the type signature and the `documentation` contains the actual documentation. 

Extensions are also free to provide the documentation in markdown syntax which is will rendered accordingly.

> It also should not wrap type signatures, so that you do not end up with:

That is the popup on hover which is different from the auto-completion pop up which we have been addressing so far. This has fixed width. You can imagine that if we were to not wrap the signature, then we would either end up with a scrollbar or a popup that is same width as the editor. Thus, we had to wrap.

#29757 tracks the need to have scrollbars.

> Finally there should be hotkeys to trigger documentation and type signature popup.

Ctrl+Space is the hotkey to trigger auto-completion. Once the auto-completion pop up is visible, pressing Ctrl+Space one more time gives you the documentation on the side

The pop up you see on hover can be triggered using the command `Show Hover` which uses the hot key Cmd+K Cmd+I or Ctrl+K Ctrl+I based on your OS
