### ISSUE TITLE
Custom explorer nodes with children show a "placeholder" icon now

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#43531]
### Issue Type
Bug

### Description

In the latest insiders build, I see that nodes, without provided icons but with children, have a new placeholder icon.

![image](https://user-images.githubusercontent.com/641685/36115655-b7966b64-1001-11e8-8749-ff2865afa1c5.png)

I'm hopeful that this isn't the desired behavior.

### VS Code Info

VS Code version: Code - Insiders 1.21.0-insider (ef42990520a856451ba5ad6fa1d299b0e0c185a2, 2018-02-12T05:14:21.574Z)
OS version: Windows_NT x64 10.0.17093

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|Memory (System)|31.93GB (16.32GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.18.1
openmatchingfiles|bca|0.3.0
markdown-preview-github-styles|bie|0.1.0
gitignore|cod|0.5.0
vscode-svgviewer|css|1.4.3
gitlens|eam|8.0.0
restore-editors|eam|0.2.1
toggle-excluded-files|eam|1.6.0
tslint|eg2|1.0.24
typelens|kis|1.5.0
vscode-postcss-sorting|mrm|3.0.1
vscode-scss|mrm|0.6.2
extension-manifest-editor|ms-|0.1.5
github-issues-prs|ms-|0.9.0
typescript-javascript-grammar|ms-|0.0.31
vscode-subword-navigation|ow|1.1.5
vscode-versionlens|pfl|0.19.1
partial-diff|ryu|0.5.1
code-settings-sync|Sha|2.8.7
vscode-autohotkey|sle|0.2.2

(1 theme extensions excluded)

</details>
Reproduces only with extensions

**Comment by eamodio** [comment]
Might be related to https://github.com/Microsoft/vscode/issues/43216

**Comment by sandy081** [comment]
This is due to #28974

@eamodio It is intended because to have proper alignment for tree. Alignment is broken if some nodes have icons and some does not. Hence a placeholder is placed. 

Meanwhile, I am waiting to get a better placeholder icon.

**Comment by eamodio** [comment]
@sandy081 Can this be reopened? I really don't like the forcing placeholder icons when an extension doesn't provide one when and item is expandable.

This isn't a problem for the explorer view, so why is it an issue for custom views? Now I *could* probably get behind it if it went along with the file theme, but again I feel like that should be the choice of then extension.

**Comment by sandy081** [comment]
@eamodio 

> I really don't like the forcing placeholder icons when an extension doesn't provide one when and item is expandable.

Otherwise tree will be mis-aligned right.  For example

![image](https://user-images.githubusercontent.com/10746682/36796835-d1fcb31c-1ca6-11e8-9077-977a8351b604.png)

If `feature` node does not have an icon then without place holder icon, labels are not aligned and tree looks broken.

> This isn't a problem for the explorer view, so why is it an issue for custom views? 
Yes. Because all nodes in the explorer are consistent. Either all nodes have icons or only files have icons or no icons. 

> Now I could probably get behind it if it went along with the file theme, but again I feel like that should be the choice of then extension.
Yes extension can do that (choose to go along with current file icon theme) by using the properties [iconPath](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L5105) and [resourceUri](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L5113) properties on TreeItem.

> Looking at this a bit more -- it looks like in the latest insiders it does sort of go along with the file icon theme, but not correctly. It seems to hide icons when they exist in the theme, and show them when they don't.
It is a bug to show folder icons instead of placeholders. Got fixed here - https://github.com/Microsoft/vscode/issues/44726. After the fix, screenshots in the above comment will show always same in all themes.

Long story In short, tree view will not align with File icon theme unless extension asks so. Place holder icons are placed only when needed to make the tree aligned completely. 

Gitlens tree look like following in all themes.

![image](https://user-images.githubusercontent.com/10746682/36801005-2f3b831e-1cb1-11e8-906e-ca4e0c028dfb.png)

Why not use root folder icon for the root folders?

![image](https://user-images.githubusercontent.com/10746682/36801044-47ff0f06-1cb1-11e8-9f16-1996c46dcd64.png)

**Comment by eamodio** [comment]
@sandy081 So I can definitely see this, if you have 2 items at the same nesting level where 1 has an icon and the other doesn't, but if none of them do why does it need to be forced? Forcing the addition of icons when not required (i.e. when they won't break alignment) seems to be forcing more visual noise - if an extension doesn't feel it provides value.

For example the folder icon here, on each remote and each stash. I can add an icon for each, but will it provide any useful information (maybe, maybe not).
![image](https://user-images.githubusercontent.com/641685/36804682-4cdd08ac-1c89-11e8-9cb8-a670cebfe72d.png)

So while I can certainly add icons for each of these (though stashes are a bit tricky), I just don't like adding more if it doesn't provide value. Honestly, I was thinking of removing the tag icon from each tag, because it is just a repeated icon without any added value -- where as branches provide extra value about its sync state.

Also as an aside, is there a way to provide something like a constant `resourceUri` that means I want this treated as a folder and/or a file of this type? Currently in GitLens when I want to show a "folder" type icon, I hack a `resourceUri` to some base folder -- seems a bit ugly :)

**Comment by sandy081** [comment]
I have to admit that extension authors are not liking this placeholder approach to fix the tree alignment issue. Hence I reverted the fix and revisit the tree alignment problem with a different approach in next milestone.

**Comment by eamodio** [comment]
@sandy081 Thank you and really appreciate your consideration!

**Comment by sandy081** [comment]
@eamodio Forgot to reply to your question

> Also as an aside, is there a way to provide something like a constant resourceUri that means I want this treated as a folder and/or a file of this type? Currently in GitLens when I want to show a "folder" type icon, I hack a resourceUri to some base folder -- seems a bit ugly :)

There is a constant you can set `iconPath` to `ThemeIcon.Folder` or `ThemeIcon.File`. By doing so system assigns an icon to the node based on File icon theme.

**Comment by sandy081** [comment]
To verify, make sure that no place holder icons are added to the nodes in the tree view. An example is install `gitlens` extension and check in the Gitlens view.
