### ISSUE TITLE
Terminal should remember the history of commands after VS Code's restart on Windows

### ISSUE THREAD

**Issue by user3323** [Microsoft/vscode#43557]
- VSCode Version: 1.21.0-ins
- OS Version: win7x64

Every time you restart the VS Code - you have to enter the commands again and again.

So, maybe anyone could implement a in-built history for those? It would help a lot!

**Comment by Bendjen** [comment]
Agree ! That is quite useful for me , too.

**Comment by Tyriar** [comment]
This might be happening on Windows because we're forcefully killing all console processes in the process tree when VS Code is shutdown https://github.com/Tyriar/node-pty/blob/ad71e8989d7613e2e439cc191ede6d5e48600f58/src/windowsPtyAgent.ts#L99

Without this sometimes zombie processes would be left over. Perhaps there should be a timeout or something before we kill everything to allow processes to shut down gracefully? It would then depend on how [winpty](https://github.com/rprichard/winpty) shuts down the processes.

**Comment by Tyriar** [comment]
This is likely related to winpty, tracking in https://github.com/Microsoft/vscode/issues/45693
