### ISSUE TITLE
Allow for tilde-forwardslash expansion in cli path argument

### ISSUE THREAD

**Issue by am11** [microsoft/vscode#43560]
Some editors provide special expansion for `~/` to user HOME directory. This expansion does not rely on shell's path expansion capability. For example, (unlike Windows PowerShell) in CMD, `~/` has no special meanings, yet nano-editor when invoked as  `nano ~/fs.js` in CMD or PS gets launched with the file `c:\users\username\fs.js`.

Code currently supports delayed expansion for environment variables: `code %userprofile%\fs.js` in CMD or `code $env:UserProfile\fs.js` in PS, but `~/` is not supported in either. Please add support for this popular shortcut.

Note that in Windows, `~\` is not the substitute of `~/`.

**Comment by weinand** [comment]
@am11 where exactly in VS Code are you missing this feature?

**Comment by am11** [comment]
Sorry, it's about command line interface. 8-)

**Comment by am11** [comment]
If taking a dependency on package is an option, https://github.com/sindresorhus/untildify#usage would be a good choice IMO.

**Comment by weinand** [comment]
@bpasero @Tyriar  I think @am11 is asking for something else:

Running something like `code ~/hello.js` from the command line works fine on macOS and linux, but fails on Windows because neither CMD nor PS interpret `~`.

@am11 suggests that on Windows VS Code could interpret the `~` when processing its command line arguments (like done for the editor "nano"). 
And https://github.com/sindresorhus/untildify#usage provides this functionality.

**Comment by bpasero** [comment]
@am11 is that what you mean?

**Comment by am11** [comment]
Yes.
