### ISSUE TITLE
Can not determine .cwd for user configs

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#43591]
1. Have a single folder workspace and a launch configuration in you user settings
2. Notice the error coming from the debug extension how `cwd` is not absolute
3. I would expect the node extension to try harder to figure out the `cwd`. For example even if no WorkspaceFolder is passed it could look at the workspace using the vscode API. Or it could look at the active file and based on that determine that

Example launch in user settings:

```json
"launch": {
        "version": "0.2.0",
        "configurations": [
            {
                "type": "node",
                "request": "launch",
                "name": "Launch Program2",
                "program": "${workspaceFolder}/test.js"
            }
        ]
    },
```

**Comment by lostfields** [comment]
yeah, it's really annoying. It's complaining that my cwd doesn't have workspaceFolder but even when I change my cwd to workspaceFolder it complains that it should be absolute;

typescript launch
```json
{
	"type": "node",
	"request": "launch",
	"name": "Run program",
	"args": ["app.ts"],
	"runtimeArgs": ["-r", "ts-node/register"],
	"cwd": "${workspaceRoot}",
	"protocol": "inspector",
	"internalConsoleOptions": "openOnSessionStart"
}
```` 

mocha launch
```json
{
	"name": "Run mocha",
	"type": "node",
	"request": "launch",
	"program": "${workspaceRoot}/node_modules/mocha/bin/_mocha",
	"stopOnEntry": false,
	"args": ["--no-timeouts", "--compilers", "ts:ts-node/register", "${workspaceRoot}/test/*.ts"],
	"cwd": "${workspaceRoot}",
	"protocol": "inspector"
}
```

I'm staying at VS Code 1.19 because of this.

**Comment by weinand** [comment]
@lostfields and the launch configs live in your user settings, correct?

**Comment by lostfields** [comment]
@weinand no, I'm using workspace settings

**Comment by weinand** [comment]
hmm, I cannot reproduce the problem in VS Code 1.20.1 if the launch config is in your workspace settings. How does the error message look like? Please attach a screenshot.

**Comment by lostfields** [comment]
![vscode_cwd-problem](https://user-images.githubusercontent.com/4351799/36592880-d5f81a28-1897-11e8-8245-079266c3a228.PNG)

**Comment by weinand** [comment]
Thanks, but if I understand you correctly this is the second error (after supplying the 'cwd' attribute).
What is the error if you supply not 'cwd' at all?

**Comment by lostfields** [comment]
If I skip cwd entirely I have a problem where nodejs cannot find "ts-node/register". I have problems running my mocha tests as well, as it says; `Attribute 'program' is not absolute ('${workspaceRoot}/node_modules/mocha/bin/_mocha'); consider adding '${workspaceFolder}/' as a prefix to make it absolute.`

**Comment by weinand** [comment]
Is your workspace a multi folder workspace?

**Comment by lostfields** [comment]
no. Try to clone https://github.com/tfso/njs-tfso-repository and you may see the problem yourself. It works in 1.19

**Comment by weinand** [comment]
I've cloned the project but I something looks strange: the mocha launch config refers to a "test" folder that doesn't exist ("${workspaceRoot}/test/*.ts"). What exactly is your workspace folder, "src"?

Why are you using the workspace settings for your launches and not the regular "launch.json" file? Since you are not using a multi folder workspace, the "launch.json" is the preferred location (whcih would not have any of the problems I'm currently trying to solve).

**Comment by lostfields** [comment]
njs-tfso-repository have args like `["--no-timeouts", "--compilers", "ts:ts-node/register", "--compiler", "--require", "ts-node/register", "${workspaceFolder}/src/test/**/*.ts"]` so my test is located in /src/test/* as typescript files.

I have like 30 typescript projects, and all them may be different. I cannot have a global launch for each of them as some requires some tweaks. Like, if you are going to work at my projects, it unnecessary that you have to make your own launch to make it work. I'm not checking in .vscode folder since I consider this as user-specific configs.

**Comment by weinand** [comment]
In your "mocha" launch from above the "src" is missing from the arguments. It would help if I could try the exact launch config with your project. Otherwise we are not talking about the same things.

**Comment by lostfields** [comment]
The config from my first post is from a project that isn't public, but the `njs-tfso-repository` has a similar config. You have to look at https://github.com/tfso/njs-tfso-repository/blob/master/tfso-repository.code-workspace for that project

```json
{
	"name": "Run mocha",
	"type": "node",
	"request": "launch",
	"program": "${workspaceRoot}/node_modules/mocha/bin/_mocha",
	"stopOnEntry": false,
	"args": ["--no-timeouts", "--compilers", "ts:ts-node/register", "--compiler", "--require", "ts-node/register", "${workspaceRoot}/src/test/**/*.ts"],
	"cwd": "${workspaceRoot}",
	"protocol": "inspector"
}
```

**Comment by lostfields** [comment]
I've made a new stripped-down project with the config from my first post at https://github.com/lostfields/ts-example

Both "Run program" and "Run mocha" fails.

**Comment by weinand** [comment]
You said:
> I have like 30 typescript projects, and all them may be different. I cannot have a global launch for each of them as some requires some tweaks. 

Yes, that's the reason why I suggested to use the "classic" approach where each project has a launch.json in its .vscode folder. With that approach you should have no problem because that's what VS Code is using since the beginning.

Storing launch configs in the workspace settings is a very recent addition that makes sense if you are using multi root folder projects, but otherwise just makes things more complex.

**Comment by lostfields** [comment]
ok, I love the idea of a workspace/project file for each project since I'm always avoiding checking in .vscode, .vs, .idea folders. 

I look a the workspace file as project configurations for all contributors to the project; and the .vscode folder is a private config for each contributor.

Guess I have to stick with 1.19 if you aren't planning to fix this?

**Comment by weinand** [comment]
Ok, now I understand your approach better.

One missing piece of information was that I have to open your project via the `tfso-repository.code-workspace` file, correct?

After doing this "Run mocha" runs just fine. Is this expected?

**Comment by lostfields** [comment]
Yes, you have to open the code-workspace file, but it fails for me when I run "Run mocha (workspace)" in version 1.20.1 (2018-02-13). 

It isn't failing for you with message `Attribute 'program' is not absolute ('${workspaceRoot}/node_modules/mocha/bin/_mocha'); consider adding '${workspaceFolder}/' as a prefix to make it absolute.` ?

**Comment by weinand** [comment]
The problem is the use of unqualified variables in a multi-folder setup.
- Your workspace is a multi-folder setup which happens to have only one folder "njs-tfso-repository"
- workspace launch configs can no longer use variables like `${workspaceRoot}` because a multi-folder setup has multiple roots. So `${workspaceRoot}` is ambiguous. In VS Code 1.19.0 we had a bug and just arbitrarily picked a folder. That's the reason why your setup worked. 
- In VS Code 1.20.0 we've fixed that problem by requiring that variables have to qualify the root folder with the syntax `${workspaceRoot:<folder>}`, e.g. `${workspaceRoot:njs-tfso-repository}` in your case. By applying this change to your launch configs made the work for me. This was explained in detail in the [release notes](https://code.visualstudio.com/updates/v1_20#_debugging).

**Comment by weinand** [comment]
@isidorn could we flag invalid variables (especially in workspace files)?

**Comment by lostfields** [comment]
Hmm, but the code-workspace is inside the njs-tfso-repository folder?

**Comment by isidorn** [comment]
@weinand we could flag them. This would require some regex json schema magic, but I can look into it. Created https://github.com/Microsoft/vscode/issues/44280

**Comment by weinand** [comment]
the code-workspace can be anywhere.
But you could add another arbitrary folder (outside of the njs-tfso-repository folder) to your workspace with the "Add to Workspace" action.
And then you have a real multi-root-folder workspace where arbitrary folders are grouped together and where a "workspaceRoot" is ambiguous.

**Comment by weinand** [comment]
@isidorn we could actually support @lostfields use case: if a workspace has only a single folder, variables like "workspaceFolder" (or "workspaceRoot") could be resolved against the folder unambiguously. Only if another folder is added, they are ambiguous and are flagged as such.

**Comment by isidorn** [comment]
@weinand this feels a bit magical, like if a launch in user settings would replace against if only there is a single folder. We can make this work as it would make most of the customers happy.

**Comment by lostfields** [comment]
@weinand thanks, it works fine when I use `:<name of workspacefolder>` under `folders: []`. If I do this it works just as it should and I'm happy.

But, I still think it should get fixed though, since `folder[].path` is relative to the code-workspace file, and workspaceRoot/Folder should default to the same path as the code-workspace if it isn't told which `folder[].path` it should be using. 

@isidorn Don't do the single folder thing, just go for the path of the code-workspace if `:<workspacename>` isn't used. If `:<workspacename>` is used, go for the path of `folder[].path`

**Comment by weinand** [comment]
@lostfields please file a new issue since this is fixed now.
