### ISSUE TITLE
UI/UX Experience when background updating on windows is not that good.

### ISSUE THREAD

**Issue by jens1o** [Microsoft/vscode#43640]
### Issue Type
Bug

### Description

cc @joaomoreno

When a new background update is being downloaded, the gear icon has a loading state. But when I click install, I'm being said that vscode will notify me once it's done. But it only yields to the gear icon having the state `1`,  which is confusing.

I'd expect a new UI notification where I can press restart and then it goes.

### VS Code Info

VS Code version: Code - Insiders 1.21.0-insider (4d122017332a1ed12e083d79f85a054ac3f32fcf, 2018-02-13T05:16:56.295Z)
OS version: Windows_NT x64 10.0.15063

Reproduces without extensions

**Comment by joaomoreno** [comment]
6 months ago we moved away from UI notifications for updates, especially because they are distracting and get in your face for something which is really not urgent: updates. I don't think we're going to go back to them any time soon.

It really is all about urgency. Is it really urgent that the user knows that there's an update ready to be applied? Not really. Think Google Chrome or Spotify. You don't really notice there's an update unless you pay attention to the notification badge. And, regardless of whether you do pay attention to it, the update is applied in the background anyway. This is exactly what Code's background experience is. If you ignore the 1 and close Code, Code will still update in the background.

**Comment by jens1o** [comment]
Okay, I understand your point, but I'd like to have as much control as possible. For example, I'm asked whether Firefox should pull a new update and I'm used to it for any application.

**Comment by joaomoreno** [comment]
Actually we're trying to mimic Chrome and Spotify. We really think that is the best experience: the user simply shouldn't even realise there has been an update.
