### ISSUE TITLE
Debug point not working

### ISSUE THREAD

**Issue by pujari28081984** [Microsoft/vscode#43719]
HI,
I am trying to debug the dash js player on visual code studio.
I have open the source folder from Vscode and ran "grunt dev" from the VsCode terminal to launch the application.

After that for debugging some file "MediaPlayer.js" which is under "src/streaming/MediaPlayer.js", since my working directory is at the "src"
![screenshot from 2018-02-15 12 04 34](https://user-images.githubusercontent.com/34153789/36243632-7abb4798-1248-11e8-84f4-0619d0d71fe7.png)
 level so inside launch.json i am giving this fie name for debugging:

```js
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceFolder}/src/streaming/MediaPlayer.js"
        }
    ]
```
Attaching a print screen.

It would be of really a help if I get some pointers on this .

**Comment by weinand** [comment]
I'm assuming that you want to debug a node.js application that was not started in debug mode (by `grunt dev`).
In this case you can attach the VS Code debugger via the process ID of the program you want to debug. Use this launch config:
```
{
			"type": "node",
			"request": "attach",
			"name": "Attach by Process ID",
			"processId": "${command:PickProcess}"
}
```
When you launch this, a QuickPick list with node process appears. Select the process you want to debug.

If you can't find the process you can enter the process ID in the launch config from above explicitly:
```
{
			"type": "node",
			"request": "attach",
			"name": "Attach by Process ID",
			"processId": "12345"
}
``` 
(Of course use the correct process ID instead of "12345")

**Comment by pujari28081984** [comment]
I tried giving the "processId"in the launch configuration, but it shows and error "Property processId is not allowed"

**Comment by weinand** [comment]
Please note that the "processId" attribute is only allowed in an "attach" debug configuration, that is where the "request" type is "attach".
