### ISSUE TITLE
clear terminal option dissapeared?

### ISSUE THREAD

**Issue by SteveALee** [Microsoft/vscode#43744]
I may be imagining it but I'm sure I could right click on the terminal tab (or others) and select "clear content."

This is no longer possible.

Is very useful after command output a lot of content and you want a clear sheet.

**Comment by Tyriar** [comment]
@SteveALee should still work:

<img width="205" alt="screen shot 2018-02-15 at 6 23 37 am" src="https://user-images.githubusercontent.com/2193314/36261347-e5ee68fe-1218-11e8-84c9-0d3d5303d800.png">

What platform/version are you on?

**Comment by SteveALee** [comment]
@Tyriar Nope :(

![image](https://user-images.githubusercontent.com/618922/36261457-578b7e6e-125c-11e8-916c-5e751e6cee28.png)

Windows 10, just updated to latest today

**Comment by SteveALee** [comment]
That's r-click on TABS, no context menu in main terminal area

**Comment by SteveALee** [comment]
@Tyriar 

That makes sense but in the above image I get the menu when I R click on the tabs -and was sure I used to have clear in the menu, not just hide.

I'm not on insiders - have a nice blue icon - hehe

**Comment by Tyriar** [comment]
It doesn't look like this ever happened, I just went back to 1.17 which was before you could hide panels and nothing happens when you right click on the "terminal" tab. If it ever did happen to work it was an accident 😄, maybe you're thinking about before `terminal.integrated.rightClickCopyPaste` was introduced when a context menu showed on Windows?

**Comment by SteveALee** [comment]
Haha - may be it was wishful thinking then!
