### ISSUE TITLE
Deleted folder appears again on refresh

### ISSUE THREAD

**Issue by Legends** [Microsoft/vscode#43755]
- VSCode Version: 1.20
- OS Version: win10 x64

**Steps to Reproduce:**
Delete folder and click refresh.
The folder is still there.

**I made a video:**
[Screen recording](https://drive.google.com/open?id=17ylhGlCTAK_-R2eFj5xO4oyHr63TzDHG)

Does this issue occur when all extensions are disabled?: Yes/No
Didn't search how to disable extensions.

But a restart helps.

**Comment by Legends** [comment]
How can I know which extension is interfering?

**Comment by egamma** [comment]
Regarding your steps, when you click refresh can you check whether the files are deleted on disk, do they still show up in the Windows Explorer?

@Legends here is how to enable/disable extensions https://github.com/Microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled.

**Comment by Legends** [comment]
They stay until I delete them using Windows Explorer.
After restarting VsCode it works again for some time, I cannot reproduce it right now.
I will have to check the extensions....

**Comment by egamma** [comment]
If they show up in the windows explorer then the refresh behaviour is correct. I assume when this happens you also fail to delete the folder from the Windows Explorer? If it fails what is the error message?

So the questions are 1) why can they not be deleted and 2) why is there no error message when the deletion fails. 

You are trying to delete the dist folder, is it possible that these files are used by another process, for example, you are launching a server process that uses the files in the dist folder? Is webpack keeping these files open?

**Comment by Legends** [comment]
Did you see my [screen recording](https://drive.google.com/open?id=17ylhGlCTAK_-R2eFj5xO4oyHr63TzDHG)?

**Comment by egamma** [comment]
Yes I saw the screen recording. I was wondering whether you get an error message when you delete the `dist` folder in the Explorer. I would expect an access denied error.

>I don't know if any process uses the dist folder. How can I check that?

Since you mention that restarting VS Code helps it could be a process  that got spawned by VS Code or an extension. Can you run `code --status` and attach the output.

Here is a way to do that using the process explorer https://www.techsupportalert.com/content/how-find-out-which-windows-process-using-file.htm.

**Comment by Legends** [comment]
![image](https://user-images.githubusercontent.com/966368/36301631-d2fbeb84-1305-11e8-9646-1b98ec0651ab.png)

**Comment by egamma** [comment]
The output shows that it is a code.exe with the pid/process ID 1616. Since VS Code is a multi process architecture there are multiple code.exe processes running and we need to find out which one it is.

An easy way to do this is to run `code --status` this shows you the running code processes, their pid and a descriptive name. Here is how it looks for me

![image](https://user-images.githubusercontent.com/172399/36302195-e332aa72-1307-11e8-9f09-4ddd56ddbaa3.png)

**Comment by Legends** [comment]
Here it is:
![image](https://user-images.githubusercontent.com/966368/36302277-2993c4f6-1308-11e8-9ca3-02d27d3c673a.png)

**Comment by Legends** [comment]
I clicked in the right bottom corner on something related to "Live server":
![image](https://user-images.githubusercontent.com/966368/36303986-5a803b16-130e-11e8-9d73-68ca1a37975a.png)

After that, the delete works again...

**Comment by egamma** [comment]
This makes sense, from the code --status output you can see that process 1616 is the extension host. This is the process that hosts/executes the extensions, so it must be an extension that keeps the files open. I assume that the LiveServer extension executes the files in the dist folder, therefore the deletion fails. I doubt that LIveServer can do anything about this.

There is still the issue that the delete in VS Code files silently. I file a separate issue on this.
