### ISSUE TITLE
Function breakpoint icon

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#43763]
Consider using a special icon for function breakpoints.
An idea by @weinand is to use a triangle which which goes well with the analogy of regular breakpoints having 0 edges (Circle), log breakpoints will have 4 edges (diamond like Visual Studio) and function breakpoints can have 3 edges (triangle)

@chryw I noticed that Visual Studio uses a simple red circle for breakpoints, but what do you think of our idea to use a red triangle? If you like it do you have time to find / provide some icons for this? In case we decide to use a special icon we need a regualr red icon, same variant but gray, same variant but empty gray. All of those for dark theme, same as for regular breakpoints.

The first two brekapoints in this image are function breakpoints

![screen shot 2018-02-15 at 16 02 14](https://user-images.githubusercontent.com/1926584/36263190-f0232ffc-1269-11e8-81fd-082ccac29678.png)

**Comment by isidorn** [comment]
Just a friendly reminder @chryw to get your input on this
@stevencl @chrisdias what is our new ux person in redmond, he might be interested in this?

**Comment by chryw** [comment]
@isidorn I've worked on some breakpoint icon variations for Visual Studio IDE. The feature team didn't want to use triangle because they think triangle looks like up/down pointer that has positive/negative meaning, so we went with pentagon instead.
![image](https://user-images.githubusercontent.com/7075677/36492870-0da6de34-16e3-11e8-8c9c-47d80e313907.png)
If in VS Code this isn't a problem, then I personally prefer simpler shapes like circle, diamond and triangle. Do you have a list of all possible breakpoint types? We can put together some icon options and see if they make sense/don't conflict with other meanings.

**Comment by isidorn** [comment]
@chryw awesome that you worked on this already.
I also prefer simple shapes. Here are all possible breakpoint types for now:
* regular breakpoint - red circle
* conditional breakpoint - red circle with equality sign
* function breakpoint - no design yet
* log breakpoint - no design yet

Also each of those can be in one of 3 states
* ok - regular breakpoint
* unverified - emtpy
* disabled - grayed out

As for the triangle I understand the concern. I personally do not have that conern. Also we can rotate it so it looks like left / right and not up / down if that helps.

**Comment by sbatten** [comment]
@isidorn something else. :) new dev on the team

**Comment by chryw** [comment]
@isidorn Here's my proposal
- Conditional - In VS IDE there is already an existing icon that has a "+" inside circle, instead of "=". Let's inherit that.
- Function - let's use a common triangle sitting on baseline. I don't think there is anything related to trend near this area for VS Code, so triangle should be fine.
- Colors - we often use purple for "Method/Function" related icons, hence purple triangle. We use blue for "Information/Neutral status", hence blue diamond.
- Darker grey for disabled state - Usually disabled icons inherit the greyed out control, but here I assume "disabled breakpoints" are different from un-interactive controls - they need to be visible to indicate these breakpoints are temporarily "off". I gave them darker grey that has more contrast on white background.
![image](https://user-images.githubusercontent.com/7075677/36509283-04943720-1714-11e8-81d7-cf7161cc2f29.png)

**Comment by isidorn** [comment]
@chryw thanks for your great proposal. I like the ideas, however:
* Let's not use a different color of function breakpoints / log poins, but instead always have all the breakpoints in the same color. In the future we plan to make the breakpoint color themable and I do not want to overcomplicate this task. So when one color gets changed, they should all get changed. We can introduce different colors only if users complain the breakpoints are not distuinguishable enough.
* Let's not use the + for the conditional breakpoints since it looks like a Swiss flag. Instaed let's keep the equality sign as we do now.

Darker gray is fine for me.

Code pointer for all our breakpoint svg, just so we are aware what would need to change
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/browser/media/breakpoint.svg#L1

**Comment by chryw** [comment]
@isidorn I attached these icons -
![image](https://user-images.githubusercontent.com/7075677/36620652-e6c9dc22-18a8-11e8-8766-212514a38c1d.png)

[vsc43763_BreakpointIcons_ToClient.zip](https://github.com/Microsoft/vscode/files/1753379/vsc43763_BreakpointIcons_ToClient.zip)

**Comment by isidorn** [comment]
@chryw thanks a lot for those lovely icons! I took them all, accept I changed the unverified ones  to have a gray border, not the red one (as they will not be hit, so red does not make sense imho).
Once we have the log breakopint we will also use the nice diamond icon you provided
