### ISSUE TITLE
VScode Stuck for few seconds when come back to it

### ISSUE THREAD

**Issue by auedbaki** [Microsoft/vscode#43972]
### Issue Type
Bug

### Description

This problem occur when i come back to vscode after taking a look at browser.

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|Memory (System)|7.88GB (3.71GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|50%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
uikit-3-snippets|Ken|1.2.1

</details>
Reproduces only with extensions

**Comment by tsalinger** [comment]
You mention that this problem only occurs with extensions enabled. Please disable all extensions (CTRL+SHIFT+P --> 'Disable all installed extensions') and restart VS Code.
Then check if the problem still persists. If not, try to find which one causes the trouble by enabling one extension after the other.

If the problem is not caused by an extension, please provide us with a reproducible list of steps that cause this behavior. Also, a [screen recording](https://www.cockos.com/licecap/) would be very useful in your case.
