### ISSUE TITLE
linux package names

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#4398]
the linux package file names are:

vscode-i386.deb
vscode-i386.rpm

the pattern we have for the linux zips is this:
vscode-linux-ia32-insider.zip
vscode-linux-x64-insider.zip

I would expect then the packages to have names like this:
vscode-linux-deb-ia32-insider.deb
vscode-linux-rpm-ia32-insider.rpm

**Comment by Tyriar** [comment]
The file names are named using what architecture they're built as. For deb that is i386/amd64 and for rpm that is i386/x86_64, ia32 and x64 aren't valid architectures for deb/rpm files. It's best practice to keep these in the file names for clarity0. [I've been toying with the idea that we don't even need to provide the zip](https://github.com/Microsoft/vscode-website/issues/73#issuecomment-195578442) at all since deb and rpm files can just be extracted much like zips, only the package files contain addition files like the launcher which is becoming more and more essential. Reopen if there is still an issue.
