### ISSUE TITLE
VSCode randomly removes keyboard shortcuts, breaks copying and pasting

### ISSUE THREAD

**Issue by Connorelsea** [Microsoft/vscode#43995]
VSCode randomly removes keyboard shortcuts, breaks copying and pasting. I honestly don't know how to describe it better than this, because it is seemingly all that is happening. After a few minutes in VSCode, copy/cut/paste stop working entirely in the program via the keyboard shortcuts and only work via right-click. They work outside of VSCode

- VSCode Version: 1.20.1
- OS Version: MacOS High Sierra

Steps to Reproduce:

1. Open VSCode
2. Use VSCode
3. Copy/paste/cut via CTRL work
3. Seemingly arbitrary amount of time later, copy/paste/cut stop working, random

**Comment by rhernandog** [comment]
Hello I'm experiencing something similar, but regarding the keyboard layout. I use a Latin American Spanish keyboard, which works as expected in every program on my laptop. I open VSCode and after some time (random it seems) the layout (or key mapping) changes to english, only on VSCode, in every other software it works as is set in windows. After restarting VSCode the layout is Latin American Spanish again, but after some time it changes back to english.

Of course the issue is that this changes the entire key map, which causes a few inconveniences. I don't know if this and @Connorelsea issue are related, but since both issues are quite similar instead of creating a new issue I added to this one.

- VSCode Version: 1.20.1
- OS Version: Windows 7 Pro 64

Does this issue occur when all extensions are disabled?: Yes

**Comment by egamma** [comment]
For keyboard layout related issues please follow this guide for trouble shooting https://github.com/Microsoft/vscode/wiki/Keybinding-Issues. If the guide doesn´t help please reopen the issue.
