### ISSUE TITLE
Allow themeing of debug single step line highlight

### ISSUE THREAD

**Issue by mbenkmann** [Microsoft/vscode#44030]
- VSCode Version: 1.20.1
- OS Version: Linux

When single-stepping through a program, the current source line is highlighted. It seems that there is no way to theme this highlight. I think there should be background, foreground and border options. In particular a non-transparent foreground color should be supported even for non-high contrast themes. Right now it seems that for all themes except high contrast the highlight is only a transparent background while for high contrast it's a non-transparent background with a non-transparent foreground (making the syntax highlighting go away but give more contrast in return). All of this should be up to the theme author (or user settings) to decide.

**Comment by mbenkmann** [comment]
Thank you vscodebot for your nice suggestion. That possible duplicate would count as a pretty good hit were it not for the fact that I opened that particular ticket myself. I don't think people accidentally open duplicates for their own tickets very often. Probably something to consider in the duplicate heuristic.

**Comment by chrmarti** [comment]
(Adding your suggestion to the bot's TODO list. Thanks @mbenkmann.)

**Comment by isidorn** [comment]
@mbenkmann agree
This guy should register those colors https://github.com/Microsoft/vscode/blob/isidorn/searchPanel/src/vs/workbench/parts/debug/browser/debugEditorModelManager.ts#L31

However the issue is that they are editor decorations, I am not sure how assign colors to them. Currently we only allow css clases.
@aeschli am I missing something here, can we make decoratinos themable?

**Comment by aeschli** [comment]
The decorations API in vscode.d.ts allows passing themed colors.
If you don't use that API (but the API on the editor/model), then you need to add a ThemingParticipant. 
[here](https://github.com/Microsoft/vscode/blob/efa33330fb0ab23b022bdff125311bdb21494b71/src/vs/editor/browser/viewParts/currentLineHighlight/currentLineHighlight.ts#L133:L134) is an example for that.

**Comment by isidorn** [comment]
@aeschli thanks!

**Comment by zeelux** [comment]
This would be great to have. The default yellow color does not work in all scenarios. I prefer the [Darcula theme](https://github.com/rokoroku/vscode-theme-darcula) but when debugging the current line is extremely difficult to read.

**Comment by isidorn** [comment]
@aeschli please help with the naming, currently I chose
`editor.debugStackFrameLineHighlight`
`editor.debugFocusedStackFrameLineHighlight`

I am not sure if the prefix should be editor or debug and if the name is too long.
The difference between the two being that first is the top stack frame line highlight by default yellog, and the other is when you click on some non top stack frame by default green.

**Comment by aeschli** [comment]
Is it a highlighted range in the editor, like the line highlight (`editor.lineHighlightBackground`)?
-> Then It needs the 'editor' as component.

Highlights normally come in pairs: HighlightBackground and HighlightBorder. High contrast always uses borders.

Is it always a line, or could it be potentially a just a range?
-> I suggest to just call it a `highlight`

I'd skip 'debug' to make it shorter

Here's my suggestion:
`editor.stackFrameHighlightBackground` an `editor.stackFrameHighlightBorder`
`editor.currentStackFrameHighlightBackground` an `editor.currentStackFrameHighlightBorder`

**Comment by aeschli** [comment]
some other suggestion:

- editor.debuggingFrameHighlightBackground ...
- editor.topDebuggingFrameHighlightBackground

**Comment by isidorn** [comment]
It could porentially be a range, but let's just call it highlight
I like 
`editor.stackFrameHighlightBackground `
`editor.focusedStackFrameHighlightBackground`

Notice that I changed the `current` to `focused` in the second name, since the more important one I would like to have a short name and that is `stackFrameHighlightBackground` - yellow.

Borders we do not yet have, though I understand we should probably introduce this for the HC theme.
