### ISSUE TITLE
Linux: Pinentry doesn't grab focus

### ISSUE THREAD

**Issue by tristan957** [Microsoft/vscode#44047]
- VSCode Version: 1.20.1
- OS Version: Solus 3 (Linux 4.15.3)

Steps to Reproduce:
1. Enable GPG signing upon commits
2. Make a commit through either the terminal or the GUI

Does this issue occur when all extensions are disabled?: Yes

Simple QOL improvement. Focus should move from the main VSCode window to the GPG signing window, and then back to the main window once passphrase has been entered

**Comment by joaomoreno** [comment]
@tristan957 Can you record a screencast showing me how that looks like currently?

**Comment by tristan957** [comment]
@joaomoreno here you go: https://drive.google.com/file/d/1IckyEP1manNYCRrs0z1mezsax2zPnMMB/view?usp=sharing

**Comment by joaomoreno** [comment]
@tristan957 How does it look like if you do it from a regular terminal window (not inside Code)? Does that work?

**Comment by tristan957** [comment]
Yes focus moves appropriately in a native terminal. I should've made that clear.

**Comment by joaomoreno** [comment]
That is kinda odd. I doubt the native terminal "moves" the focus to that popup window; since it doesn't have any knowledge about a window existing at all.

I postulate `pinentry` conditionally grabs focus and it isn't grabbing it when running inside Code for some reason. I suggest to reach out to https://dev.solus-project.com/ as well.

**Comment by tristan957** [comment]
I will do that. Any other things you need of me?

**Comment by joaomoreno** [comment]
Not really, unfortunately. Try to figure out other environments in which the input is focused or otherwise. Other terminals, other editors, etc.

**Comment by tristan957** [comment]
Should I file this as a bug against pinentry? I'll see if a similar behavior happens in Atom later today

**Comment by joaomoreno** [comment]
Yeah do so.

**Comment by cdenneen** [comment]
Since #5065 is locked and this is very similar, is anyone having GPG signing issue with VSCode+Mac combination?

```
git check-ignore -z --stdin
git commit --quiet --allow-empty-message --file - -S
error: gpg failed to sign the data
fatal: failed to write commit object
```

Doing this from iTerm works fine.  VSCode Terminal works as well but in trying to do this in **native VSCode** it doesn't prompt for passphrase and fails immediately.

![screen shot 2018-03-06 at 11 01 15 am](https://user-images.githubusercontent.com/720097/37043095-cfe170b4-212d-11e8-8578-aa4d1dc257bd.png)

![screen shot 2018-03-06 at 11 01 26 am](https://user-images.githubusercontent.com/720097/37043102-d41a9d9a-212d-11e8-8c0b-d889ca094dd3.png)

**Comment by joaomoreno** [comment]
Thanks @tristan957 !
