### ISSUE TITLE
ignoreRecommendations flag set to `true` stops working

### ISSUE THREAD

**Issue by jvlad** [Microsoft/vscode#44091]
- VSCode Version: 1.19.3
- OS Version: MacOS Sierra 10.12.6 (16G29)

Steps to Reproduce:

1. Open preferences, set `"extensions.ignoreRecommendations": true,`
2. Open extensions explorer
-> recommendations list is collapsed as expected
3. reload Visual Studio Code
4. Open extensions explorer
-> recommendations list is open again
**Expected**: recommendations list to be collapsed

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by ramya-rao-a** [comment]
`extensions.ignoreRecommendations` only stops the prompts about recommended extensions from showing up. Check the description on this setting. In hindsight, it should have been better named as `extensions.ignoreRecommendationsPrompts`, but we cant change the name now due to backward compat.

A few things you can do:
- In 1.19.3, you can choose to hide the recommendations panel. Right-click on the panel title and choose "Hide"
- Or if you use the latest [Insiders](https://code.visualstudio.com/insiders), you can get add the setting `"extensions.showRecommendationsOnlyOnDemand": true`. This will stop showing you recommendations altogether unless you specifically ask for it
