### ISSUE TITLE
Windows: Alt+click to open alternative commands in context menu not working

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#44136]
It looks like on Windows pressing Alt+right-click to e.g. bring up the "Delete Permanently" action is not working. When using it, the context menu does not show.

Could we possibly support the Shift+key too on Windows? I think we used to support that before, but not sure if now we have conflicts with multi-select?

/cc @dbaeumer 

@isidorn fyi this only reproduces on a real Windows machine, not VM.

**Comment by isidorn** [comment]
@jrieken do you mind if I start supporting shift for alternative commands on windows. The issue with alt is that it triggers the menu.
@bpasero this should not conflict with multi select since triggering the context menu does not affect multi selection. Also the right click does not affect multi selection

**Comment by jrieken** [comment]
> do you mind if I start supporting shift for alternative commands on windows.

Yeah, I would mind because it will break existing behaviour. It's also the *alt*ernative command, not a modification of an command. I would not mind adding shift in addition to alt on windows .

**Comment by isidorn** [comment]
@jrieken what I meant in my original comment is to support both. Glad you are +1 for that.
