### ISSUE TITLE
List: allow to splice while preserving the view state

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#44179]
It would be nice if the list widget could provide methods so that I can splice elements but preserve the vertical scroll position.

For notifications I would like to preserve the view state when new notifications are coming in, at least when the user has keyboard focus in the list.

**Comment by joaomoreno** [comment]
This already happens today. The "view state" is preserved: the list's scroll top will stay stable as you splice elements.

I believe you want something else: you want to preserve a **specific** element's viewport position. In order to do that, you must change the list's scroll top, effectively changing the view state as you splice.

Is that correct?

**Comment by bpasero** [comment]
@joaomoreno yeah that sounds about right, I can play with that once you add it 👍

**Comment by bpasero** [comment]
Seems to work nicely 👍
