### ISSUE TITLE
Activity Bar & Panels: Always show list of views on right click on view title in addition to hide

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#44208]
Follow up with #42770

In Activity bar and Panel, in addition to `hide` action, also show list of viewlets/views in the context menu. Example:

![image](https://user-images.githubusercontent.com/10746682/36545270-d1fc98a4-17e8-11e8-94a5-3fccda806030.png)

**Comment by isidorn** [comment]
Looked how this is done in the composite bar.
Needs some refactoring, since each action item is not aware of the other actions that are sourounding it. To make things a bit more complex this code is shared between actiity bar and panel.
Good thing to do in debt week -> pushing to March.

**Comment by isidorn** [comment]
As mentioned above nothing for endgame week since I was out most of milestone on vacation pushing to May.
@sandy081 code pointer in case you are interested in providing a PR 
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/parts/compositebar/compositeBarActions.ts#L540
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/parts/panel/panelPart.ts#L164

**Comment by sandy081** [comment]
Thanks. Will look into it in May.

**Comment by isidorn** [comment]
@sandy081 as I mentioned during our CompositeBar PR review this should now be easier since you nicely seperated who owns the context menu actions.
Leaving it up to you to implement if you still want this feature.

**Comment by sandy081** [comment]
Verify that on right clicking on an icon in the activity bar also shows the complete list

![image](https://user-images.githubusercontent.com/10746682/44669135-70531000-aa1f-11e8-8004-bf5410abdbeb.png)

**Comment by isidorn** [comment]
Works nicely now, good job
