### ISSUE TITLE
Question: Logging in Extensions

### ISSUE THREAD

**Issue by jpoon** [Microsoft/vscode#44212]
### Issue Type
Question

### Description

Is it possible to leverage a node logging library as an Extension developer?

Particularly, I tried using Winston, Bunyan, and Debug, but wasn't able to see any output in console (from the developer tools). 

I suspect it is due to this: https://github.com/Microsoft/vscode/issues/19750, but `"outputCapture": "std"` isn't a supported attribute in `launch.json` for `"type": "extensionHost"`.

Is there an established best-practice for logging in extensions?

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:23:28.607Z)
OS version: Darwin x64 17.4.0

**Comment by ramya-rao-a** [comment]
Doesnt `console.log()` output to the developer console?

**Comment by jpoon** [comment]
Yes. `console.log` would work but I'd prefer to use one of the above mentioned logging libraries as they have some niceties like logging time and module. Obviously, I could wrap `console.log` to do the same but why re-write the wheel when I could leverage one of these npm libraries. The problem is that I couldn't get any of them to work. 

Is there a recommended path for extension authors?

**Comment by ramya-rao-a** [comment]
cc @joaomoreno @sandy081 on logging

**Comment by roblourens** [comment]
@jpoon I can't support `"outputCapture": "std"` for extensionHost debugging because the extensionHost process is spawned by the vscode window, and the debugger doesn't have access to its stdout.

You should be able to configure one of those logging libraries to use console.log instead of something like `process.stdout.write`. That's what I'd recommend for now, our extension logging API may or may not have advanced features that you're looking for from a logging library.
