### ISSUE TITLE
Add a setting to activate workbench parts on mouse over

### ISSUE THREAD

**Issue by warpdesign** [Microsoft/vscode#44214]
Now that we can split editors and terminals I think it would be a good idea to have the ability to activate editors/terminals on mouse over.

Of course this would be a new option that would be false by default.

**Comment by Tyriar** [comment]
cc @bpasero

**Comment by bpasero** [comment]
@warpdesign why would that be a good idea?

**Comment by warpdesign** [comment]
@bpasero Because it's faster/easier to switch between panels/split terminals this way using the trackpad. Also, when switching back to an editor by pointing and clicking to activate the editor, you end up with the cursor in another line you were before. By having auto-focus you end up where the cursor was before. If you just need to test a particular setting in your code, and switch back & forth between terminal and your editor just to modify this particular line and then run your command through the terminal it can be handy.

Terminal apps (like iTerm 2) offer such an option too: I guess they found it was a good idea too.

**Comment by lambda** [comment]
Since this seems to be the one issue that is not locked to contributors on this topic, I'd like to point out here that a significant attempt was made to implement this in #53963, but it turns out that it breaks too many things, as there are cases where a quick-open window will open up and you would like to mouse over to it, but in doing so would change the focus and cause the quick-open window to disappear.

I am still interested in this feature in some form, but it's clear that it's not a trivial feature to add because of things like the quick-open popup.

**Comment by lambda** [comment]
Oh, sorry, I just noticed that this isn't the only unlocked issue on this topic. This has come up again in #93772, which received sufficient votes to move it to the backlog. It looks like that's where it should now be tracked.
