### ISSUE TITLE
Github login credentials stopped working

### ISSUE THREAD

**Issue by rrod157** [Microsoft/vscode#44244]
### Issue Type
Bug

### Description

Suddenly my github login stopped working today. It seem to work fine yesterday. I can login my github account directly in git but not through VS Code. Please help! Kindly take note that TFA is activated to my account (something you need to consider during troubleshooting).

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|Memory (System)|7.43GB (2.19GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-json|and|1.3.2
vscode-puppet|bit|0.4.5
vscode-eslint|dba|1.4.6
puppet-vscode|jpo|0.9.0

</details>
Reproduces only with extensions

**Comment by joaomoreno** [comment]
Interesting. We do not yet support 2FA https://github.com/Microsoft/vscode/issues/490

I recommend switching to [SSH keys](https://help.github.com/articles/connecting-to-github-with-ssh/).

**Comment by rrod157** [comment]
I tried following the steps here: https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/

after that, I run in my command line:
git config --global credential.helper wincred 

then I restarted VC Code.

after plugging-in my credentials (of course with the hash code generated from the link as password), it worked.

I'm not sure how it was fixed but that's how I did it.

**Comment by joaomoreno** [comment]
Glad you could fix it. Very likely something in your credential manager has expired and you need to refresh it.

**Comment by simonech** [comment]
Also for me, it was working and suddenly it stopped working.
Before I was getting the username/password and then the token screen. now this second one doesn't appear any more

**Comment by david-gudeman** [comment]
I have the same problem. I've been using the Windows Credential Manager without problems for a couple of months, pushing and pulling (from the command line) pretty much every day. Then yesterday it just stopped working. I get

```
fatal: HttpRequestException encountered.
   An error occurred while sending the request.

```
The it asked for my username and password and when I entered them it works. I tried restarting Windows and, since it was related to credentials, running a virus scan. No change. Then I tried deleting the github credentials. Now, when I try to pull, the Credential Manager window comes up, I enter the credentials (I used copy-and-paste to make sure the password is correct) and it gives me the forgot-your-password? response. After two tries, Credential Manager gives up and then I can enter the username and password directly into git command line and it works.

I've tried this with a second account on github and it does the same thing. However, Credential Manager is still working for gitlab.

**Comment by simonech** [comment]
Maybe it is some issue on GitHub? Or some change they made?

-- 
Simone Chiaretta
Microsoft MVP ASP.NET - ASPInsider
Blog: http://codeclimber.net.nz
RSS: http://feeds2.feedburner.com/codeclimber
twitter: @simonech

On 23 February 2018 at 19:31:55, David Gudeman (notifications@github.com)
wrote:

I have the same problem. I've been using the Windows Credential Manager
without problems for a couple of months, pushing and pulling (from the
command line) pretty much every day. Then yesterday it just stopped
working. I get

fatal: HttpRequestException encountered.
   An error occurred while sending the request.


The it asked for my username and password and when I entered them it works.
I tried restarting Windows and, since it was related to credentials,
running a virus scan. No change. Then I tried deleting the github
credentials. Now, when I try to pull, the Credential Manager window comes
up, I enter the credentials (I used copy-and-paste to make sure the
password is correct) and it gives me the forgot-your-password? response.
After two tries, Credential Manager gives up and then I can enter the
username and password directly into git command line and it works.

I've tried this with a second account on github and it does the same thing.
However, Credential Manager is still working for gitlab.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/Microsoft/vscode/issues/44244#issuecomment-368097651>,
or mute the thread

**Comment by CoenraadS** [comment]
You need to update your credential manager: https://github.com/git-for-windows/git/releases

**Comment by david-gudeman** [comment]
PROBLEM SOLVED: I followed the suggested link https://github.com/git-for-windows/git/releases to update the credential manager. The link didn't have anything about the credential manager, but I installed git for windows from that link and it solved the problem. Presumably git for windows installs a credential manager (although I'm a little confused because I thought credential manager was a windows app).

**Comment by theo-armour** [comment]
@CoenraadS 

VS Code on my box is pushing to GitHub again. Thanks for the tip.

BTW, I used Git-2.16.2-64-bit.exe and accepted the defaults on all prompts.

**Comment by joaomoreno** [comment]
Thanks @CoenraadS!

**Comment by theo-armour** [comment]
@joaomoreno 

If it were up to me, I would not close this issue without first adding a message to the VS Code Wiki.

Just saying,

**Comment by joaomoreno** [comment]
@theo-armour On it. Notice that this has nothing to do with VS Code, but with Github's credential manager.

Here's the official announcement: https://developer.github.com/changes/2018-02-01-weak-crypto-removal-notice/

**Comment by theo-armour** [comment]
@joaomoreno 

> On it. Notice that this has nothing to do with VS Code, but with Github's credential manager.

I'm sure that GitHub's credential manager is a very nice thing,

From my innocent/naive/newb point of view it was VS code that F'd up. 

Proof of the pudding is that that I came the VS Code GitHub presence to try to resolve the issue. And - lo and behold - it was resolved here.

Therefore in order to prevent other newbs from having issues it might be a good thing to record the tip from @CoenraadS where people can see it.

**Comment by ryankane** [comment]
May be related to what @iAmWillShepherd shared in the following [thread](https://github.com/desktop/desktop/issues/4105).

> I'm sorry you're experiencing this issue.
> 
> This may be related to us removing support for TLSv1 (see [this](https://github.com/blog/2507-weak-cryptographic-standards-removed) for more info).
