### ISSUE TITLE
Changing `search.location` doesn't remember icon position in activity bar

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#44306]
https://github.com/Microsoft/vscode/issues/9435

**Comment by isidorn** [comment]
Thanks for reporting this.
I did not want to store the previous position as that would require an additional array to be stored in storage and would overcomplicate things. Instead I decided to respect the order when a composite is added to the composite bar. In practice this means that wehn the search is returned to the activity bar it will got to the second position. And when ti is placed in hte panel it will go to the first since it has the lowest order.
