### ISSUE TITLE
Hign CPU usage when chrome open a page with canvas

### ISSUE THREAD

**Issue by littlee** [Microsoft/vscode#44348]
- VSCode Version: 1.20.1
- OS Version:  macOS 10.13.3

Steps to Reproduce:

1. open Code
2. open Chrome tab with whatever site with canvas running 

then type some text in Code, I can feel some delay when I type, and the CPU usage will get higher and higher, the machine gets heated, the fan spins faster,  and when I close the tab with canvas, I feel no delay when I type in Code, I also test it with some other text editors (Sublime Text, Atom ...), they all works fine.

Does this issue occur when all extensions are disabled?: Yes/No

Yes

**Comment by RMacfarlane** [comment]
What version of Chrome are you using? @CNSKnight can you run `htop` when this happens and share what processes have high CPU?

**Comment by littlee** [comment]
@RMacfarlane 
on macOS, when it happens, Code Helper and Chrome Helper take most CPU usage, Code Helper takes a little more than what Chrome helper takes

and this also happens on my Windows 10 machine
and it is more WEIRD ?!?! 😳 

to reproduce this situation:

open a Chrome tab, go to http://brm.io/matter-js/demo/#sprites or any canvas website
open Code, stay in not maximum size, 

then Alt + Tab to Chrome, play with the canvas site for about 5 seconds
then Alt + Tab to Code
then click the maximum size button on Code's window, and then try to type in Code, it gets stuck for a few seconds, AND when this happens, I try to open the Task Manager to see what's happening, but right after I open the Task Manager, Code gets no stuck...

Chrome version:  64.0.3282.140
Code version: 1.20.1

**Comment by alexandrudima** [comment]
@littlee I cannot reproduce with the exact same Chrome version and Code version. I am also on macOS 10.13.3.

Is this slow-down occurring for you only when you use Chrome as a web browser? What happens when you open  http://brm.io/matter-js/demo/#sprites in Firefox or Safari? Is Code somehow slowed down?

(Other than sharing the same resources -- CPU, memory, GPU -- I don't see how Chrome should affect a running instance of Code).
