### ISSUE TITLE
Open Containing Folder with Nautilus

### ISSUE THREAD

**Issue by elgs** [Microsoft/vscode#44344]
- VSCode Version: 1.20.1
- OS Version: Linux archlinux 4.15.5-1-ARCH #1 SMP PREEMPT Thu Feb 22 22:15:20 UTC 2018 x86_64 GNU/Linux

Steps to Reproduce:

1. Right click on any file from vscode, and click Open Containing Folder;
2. It opens a new instance of vscode instead of opening the containing folder with Nautilus;

This problem can be solved by editing this file `/usr/share/applications/mimeinfo.cache`, and remove the `visualstudio-code.desktop;` part from this line: `inode/directory=visual-studio-code.desktop;org.gnome.Nautilus.desktop;`. However, it comes back automatically pretty soon.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by ak5** [comment]
@elgs I fixed this by adding the line 

```
inode/directory=org.gnome.Nautilus.desktop;
```

to the file `~/.config/mimeapps.list` as described here: https://wiki.archlinux.org/index.php/default_applications

**Comment by Tyriar** [comment]
This is happening due to this line in the .desktop file:

https://github.com/Microsoft/vscode/blob/master/resources/linux/code.desktop

Which tells the system (and nautilus) that VS Code knows how to open folders.

If anyone knows how to do this in such a way that it is marked as low priority I'd love to hear it, I'm not sure how to "fix" this without removing VS Code's integration for opening folders right now.

**Comment by Tyriar** [comment]
Ah, I found the original issue. I thought I closed it https://github.com/Microsoft/vscode/issues/41037

**Comment by elgs** [comment]
@Tyriar in my system, I don't have any .desktop file at all, I always cd into the project directory and run `code .` The real problem is this `inode/directory` line in this file: `/usr/share/applications/mimeinfo.cache`. It looks like this: `inode/directory=visual-studio-code.desktop;org.gnome.Nautilus.desktop;`. I interpret it as vscode hijacking nautilus. Another side effect of this line is when you downloaded something with Chrome and click open in containing folder, it opens vscode. If you have to put it in the `inode/directory` line, at least can you please put it behind the system default file manager? Please don't close this issue until it's fixed.

**Comment by elgs** [comment]
> If anyone knows how to do this in such a way that it is marked as low priority I'd love to hear it

@Tyriar in #41037 @DerTieran has actually a way to put it to a lower priority by:

> Then I looked for the distribution-provided defaults for inode/directory
> 
> ➜ cat /usr/share/applications/mimeinfo.cache | grep inode/directory
> inode/directory=visual-studio-code.desktop;org.gnome.Nautilus.desktop;
> and it seems the order here does matter, changing it to
> 
> inode/directory=org.gnome.Nautilus.desktop;visual-studio-code.desktop;
> fixes the issue.

**Comment by Tyriar** [comment]
@elgs 

> The real problem is this inode/directory line in this file: /usr/share/applications/mimeinfo.cache

My theory is the code.desktop being added is triggering the OS to modify mimeinfo.cache, we certainly don't touch it within vscode.

> @DerTieran has actually a way to put it to a lower priority by:

That a fine manual workaround sure, but we want to find the root cause and prevent it from happening in the first place, or alternatively shell out to a system lib that manages this, like we do with alternatives:

https://github.com/Microsoft/vscode/blob/fd8e756d1498e4dc268d5ecfab29de4c1e39339b/resources/linux/debian/postinst.template#L10-L13

**Comment by elgs** [comment]
@Tyriar I'm sorry I still failed to make myself clear to you. I don't think it has anything to do with the `code.desktop` file. Because I don't have this file at all. I can prove it:

**Comment by Tyriar** [comment]
@elgs if the .desktop file doesn't exist do you know what added it there in the first place then? 😕 

Do you remember which method you used to install VS Code?

**Comment by elgs** [comment]
I don’t have that icon anywhere at all. I used pacaur to install vscode.

**Comment by Tyriar** [comment]
Your problem is likely related to the unofficial AUR package then which we do not maintain https://aur.archlinux.org/packages/visual-studio-code-bin/?comments=all

**Comment by elgs** [comment]
Thanks @Tyriar! I'm sorry for that.

**Comment by DerTieran** [comment]
I'm also using this package, the `.desktop` file should be in `/usr/share/applications/` and is called `visual-studio-code.desktop` (not `code.desktop`).
```sh
➜ cat /usr/share/applications/visual-studio-code.desktop
[Desktop Entry]
Exec=/opt/visual-studio-code/code %f
Icon=visual-studio-code
Terminal=false
Type=Application
Name=Visual Studio Code
Comment=Editor for building and debugging modern web and cloud applications
Categories=Development;WebDevelopment;IDE;Utility;TextEditor;
MimeType=text/plain;inode/directory;
StartupNotify=true
StartupWMClass=code
```

**Comment by dcelasun** [comment]
@elgs It looks like you didn't use the AUR package `visual-studio-code-bin`, since that package definitely has a `.desktop` file (I know because I wrote it).

The `mimeinfo.cache` seems like [an XY problem](http://xyproblem.info/), so just to refocus this issue on the actual problem: What were your *exact* steps installing VS code?

**Comment by dcelasun** [comment]
Also, `mimeinfo.cache` is, as the name suggests, just a reverse cache for the associations defined within `.desktop` files. There is no way to define priorities within it. Furthermore, I don't think there is an issue with the AUR package either, because "Open Containing Folder" works perfectly fine for me and opens Nautilus.

Since this is neither an upstream issue nor a packaging problem, I think this can be closed.

cc @Tyriar

**Comment by elgs** [comment]
@dcelasun I indeed installed vscode with pacaur. I followed @ak5’s suggestion to use a user profile to override the global one. Hopefully, and so far,  it works.
