### ISSUE TITLE
After 0.10.8, 'Code' executable has been renamed 'code'

### ISSUE THREAD

**Issue by pfister** [Microsoft/vscode#4434]
- VSCode Version: after 0.10.8 dated 02/05, for example 0.10.11
- OS Version: Ubuntu 15.04

Steps to Reproduce:
1. after blowing away directory, unzipped in /usr/local/lib  
2. symlink in now broken because 'Code' executable doesn't exist under /usr/local/lib/VSCode-linux-x64

Fixed by:
   Under /usr/local/lib/VSCode-linux-x64, created a 'Code' copy of 'code' executable:

    > sudo cp code Code

After which launcher icon and '> code .' work as expected.

**Comment by Tyriar** [comment]
This was intentional and follows the platform conventions (default to lowercase and no spaces). I would recommend not renaming the `code` executable but instead refreshing your symlink:

```bash
SYMLINK_PATH="/usr/bin/code" # or where ever it is
rm $SYMLINK_PATH
ln -s /usr/local/lib/VSCode-linux-x64/code $SYMLINK_PATH
```

Also note that in the March release we will be offering a .deb package for easier installation which includes a new and improved launcher that accepts more command line args. You will want to remove your `code` symlink at that point. I'll make some notes in the release notes for the March release to help out users with symlinks set up.
