### ISSUE TITLE
Emmet regression - css - opacity: 0.5 not working in 1.21

### ISSUE THREAD

**Issue by user3323** [Microsoft/vscode#44352]
- VSCode Version: 1.21.0-ins
- OS Version: win7x64

`op0.5` - should be expanded into **_opacity: 0.5_**, right?

so as `op.5`

![op0 5](https://user-images.githubusercontent.com/24613274/36639777-5be3385e-1a1c-11e8-87d6-bbb6ac19bf9f.gif)

PS:
in the stable version...
```
Version 1.20.1
Commit f88bbf9137d24d36d968ea6b2911786bfe103002
Date 2018-02-13T15:34:36.336Z
```
... it works fine.

So, the problem is in Insiders build.

```
Version 1.21.0-insider
Commit ce13bb0dabd06981913c46b5a94456647864c2e0
Date 2018-02-23T05:19:18.064Z
```

**Comment by ramya-rao-a** [comment]
Root cause: https://github.com/Microsoft/vscode-css-languageservice/issues/69

@user3323 In the Insiders, we have moved to using the same parser as the css extension does. Thus the slight changes in Insiders vs Stable.

If you find any other discrepancies, please feel free to file issues. You have been a great help in the past year along with a few other Emmet users in Insiders in finding bugs and improving the Emmet experience.
