### ISSUE TITLE
Consider to resolve ${workspaceFolder} in a multi root workspace that has only one folder

### ISSUE THREAD

**Issue by lostfields** [Microsoft/vscode#44356]
- VSCode Version: 1.20.1
- OS Version: W10

Steps to Reproduce:

1. Create a new workspace and save it in the root of you repository
```
{
    "folders": [
        {
            "path": "."
        }
    ],
    "settings": {
    }
}
```

2. Add the following launch settings in your .code-workspace file
```json
"settings": {
    "launch": {
        "verison": "0.2.0",
        "configurations": [
            {
                "type": "node",
                "request": "launch",
                "name": "Run program",
                "args": ["app.js"],
                "cwd": "${workspaceRoot}"
            }
        ]
    }
}
```
3. Open the your workspace you just created.
4. Launch the debugger by running "Run program (workspace)".
5. Notice the error; `Attribute cwd is not absolute ('${workspaceRoot}'). consider adding '${workspaceFolder}/ as a prefix to make it absolute.`

**Expected behaviour**
To make it more backwards compatible with older behaviour, old variables like `${workspaceRoot}` and `${workspaceFolder}` should be relative to either your .vscode folder, your code-workspace file etc. So instead of complaining, it should resolve the path of `${workspaceRoot}` to the same path as your `*.code-workspace` file.

If I postfix my variable with the folder name from workspace file; `{ "folders": [ { "name": "myProject", "path": "./project" } ] }` like  `"cwd": "${workspaceRoot:myProject}"` it should resolve the path to the path of `folders[@name=myProject].path` that again is relative to the code-workspace file. Old variables should work from global settings, user settings (.vscode) and workspace (*.code-workspace) and be relative to each of them.

**Comment by lostfields** [comment]
details in an earlier discussion in #43591

**Comment by weinand** [comment]
Since this "older behaviour" existed only for 1 or 2 milestones and was never documented, I'm reluctant to add this "magic".
In addition, since it becomes immediately wrong if another folder is added, we can only support the "magic" if are able to show errors whenever a variable cannot be resolved.

**Comment by lostfields** [comment]
Hmm, if you add another folder, it stills resolve to the same path of the code-workspace file. It will not resolve to another path by magic? 

If you move your .code-workspace file, yes, then it will suddenly resolve to another path than it previously did.

Are we talking about a different magic? Nothing magic as I see it. It will behave exactly the same no matter how many folders you have in your workspace. _Let it be exactly as it is today, but make it possible to use only ${workspaceFolder} without postfix instead of throwing error. The most natural path to choose then, is the path where the code-workspace file currently is saved_

**Comment by weinand** [comment]
We cannot resolve the "workspaceRoot" variable to the location of the workspace file because that would introduce a new concept is VS Code. The (deprecated) "workspaceRoot" variable represents the root path of a workspace in "classic" VS Code. In a new "multi-root" workspace they do not really have a meaning as there are multiple roots. Just tying them to the the "workspace file" is an arbitrary choice since "workspace files" can live anywhere and its location has no specific semantics. Many users keep their workspace files on the desktop so that they can easily open a workspace just by double-clickable them. Resolving "workspaceRoot" to the "Desktop" doesn't make a lot of sense.

A better solution would be to resolve "workspaceRoot" to the location of the **first** root folder of a workspace. This would have addressed your use case as well.

**Comment by isidorn** [comment]
Now if there is only one folder in a workspace we will resolve against that folder. You can check it out in tomorrow's vscode insiders
https://github.com/Microsoft/vscode/commit/872de2a131ac60b6b2e2fe477514d67afec55db9

**Comment by lostfields** [comment]
@isidorn 
thanks, will check it out

@weinand 
_"In a new "multi-root" workspace "workspaceRoot" does not really have a meaning as there are multiple roots."_

workspaceRoot may be deprecated, but shouldn't workspaceFolder resolve to the path of the .code-workspace file? _After all, all the paths under "folders: []" can be both **relative** to the .code-workspace file and absolute._

... the path is actually relative by just defining `"path": "."` when you first click "Save workspace as".

**Comment by weinand** [comment]
@lostfields I'm repeating myself but I'll try again:

Resolving "workspaceRoot" (or "workspaceFolder") to the "workspace file" location is an arbitrary choice since "workspace files" can live anywhere and its location has no specific semantics. Many users keep their workspace files on the desktop so that they can easily open a workspace just by double-clickable them. Resolving "workspaceRoot" to the "Desktop" doesn't make a lot of sense.
