### ISSUE TITLE
Editor title is not centred in centered layout

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#44499]
Testing #44127

![image](https://user-images.githubusercontent.com/10746682/36722212-3e790180-1bad-11e8-9298-aa4fcbb0e639.png)

**Comment by isidorn** [comment]
Not so trivial to do with flex box, since currently I am centering that item using flex. However it is centered relative to the title area (ignoring the actions to the right).
What I need here is cenering relative to the parent.
The only solution I see is doing flex magic on the parent, however there I failed to understand how to tell flex, first element in center, second all the way to the right.

Advice on how to solve this is welcome. @joaomoreno @bpasero 

found some ugly solutinos https://stackoverflow.com/questions/33444666/how-to-center-align-one-flex-item-and-right-align-another-using-flexbox

**Comment by joaomoreno** [comment]
Not sure you can pull this off without floating the actions to the right.

**Comment by isidorn** [comment]
yeah agree. This will be fixed as part of https://github.com/Microsoft/vscode/issues/44593
