### ISSUE TITLE
Multiple buttons that exceed notification width do not overflow

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#44538]
Testing https://github.com/Microsoft/vscode/issues/44319

```
        let buttons: string[] = [];

        for (let i = 0; i < 50; i++) {
            buttons[i] = `Button ${i}`;
        }
        vscode.window.showInformationMessage(`Hello World`, ...buttons);
```

<img width="354" alt="capture" src="https://user-images.githubusercontent.com/1931590/36726059-b333b0e6-1bb8-11e8-9b5d-ae3d2122c017.png">

**Comment by bpasero** [comment]
I am waiting for the real world example where this hits us :).

**Comment by bpasero** [comment]
Maybe I could play around with some flex magic..

**Comment by bpasero** [comment]
I can push a change that I think is "good enough" as it will cause buttons to shrink to display them all:

![image](https://user-images.githubusercontent.com/900690/36743019-7a44214a-1be9-11e8-8285-ab2fa3e8a83f.png)

The example with 50 buttons is a bit extreme because that would probably only work with some ugly wrapping or scrollbar, but this is a good sample to verify:

```typescript
let disposable = vscode.commands.registerCommand('extension.sayHello', () => {
    let buttons: string[] = [];

    vscode.window.showInformationMessage(`Hello World`, ...['Hello World this is a very long message', '2 Hello World', '3 Hello World', '4 Hello World', '5 Hello World']);
});
```
