### ISSUE TITLE
Cannot read property 'isSymbolicLink' of null

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#44543]
Issue Type: <b>Bug</b>

Testing #44097

TypeError: Cannot read property 'isSymbolicLink' of null
    at fileService.ts:1237
    at extfs.ts:55
    at C:\Program Files\Microsoft VS Code Insiders\resources\app\node_modules.asar\graceful-fs\polyfills.js:284
    at FSReqWrap.oncomplete (original-fs.js:114)

VS Code version: Code - Insiders 1.21.0-insider (1a84a882737184488d965426747a05474f54a759, 2018-02-27T09:01:48.555Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (4 x 2195)|
|Memory (System)|5.98GB (3.20GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe --user-data-dir=tmp\user --extensions-dir=tmp\exts|
|Screen Reader|no|
|VM|100%|

</details>Extensions: none
Reproduces without extensions

**Comment by chrmarti** [comment]
Reproduces when creating a dangling symlink: `mklink dangling-link.txt notthere.txt` (Run as admin from cmd.)

The progress indicator in the Explorer then doesn't stop running.

**Comment by isidorn** [comment]
@chrmarti Thanks for great steps

**Comment by isidorn** [comment]
Looking at the error that you and @crewone both are seeing the only source can be the one your nice stack trace has [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/files/node/fileService.ts#L1241)

The only case when that can be null is when there is an error case which I did not handle properly. Now I added proper error handling. @bpasero please review due to legacy code.

Let me know if you can still repro in tomorrow's insiders

**Comment by bpasero** [comment]
@isidorn much simpler fix: https://github.com/Microsoft/vscode/commit/4d6291cd4acbc5271f50e0ce87ad095d318d4c31

**Comment by bpasero** [comment]
@isidorn semantically what we changed is to now always `lstat` instead of stat and if `lstat` fails we bubble up that error. I hope we are not hitting new errors that only show up from `lstat` that stat does not exhibit. If so, another idea would be to fallback to stat if `lstat` fails to preserve the old behaviour.

**Comment by isidorn** [comment]
@bpasero thanks for simplyfing. 
Now that I think about it I would prefer that we also do a stat if an lstat fails - since this is a critical path of the explorer and to try to change as little as possible.
I pushed this in de292c2ff7

**Comment by bpasero** [comment]
@isidorn makes sense

**Comment by chrmarti** [comment]
Now a dangling symbolic link is not shown at all. Not sure if that is expected, `ls` and `dir` show links also when the target does not exist.

Version 1.21.0-insider
Commit 3fec61014742dec894b3a31cdf8556bf533cb0e1
Date 2018-02-28T05:17:16.839Z

**Comment by isidorn** [comment]
@chrmarti thanks for letting us know, however the issue is that the lstat call returns an error and I do not want to assume that if I get an error I assume it is a symlink.
Will do something about this if users also complain, if you are passionate about this create a new issue please.

**Comment by chrmarti** [comment]
@isidorn stat should tell you it's a link. Don't you fall back to that?

**Comment by isidorn** [comment]
@chrmarti I fall back to stat, however the stat does not give me that information.

**Comment by chrmarti** [comment]
Got it, it is `lstat` that gives you that. (Looking at your code, we must be in the stat case after lstat succeeded with `isSymbolicLink() === true` and then stat fails. Maybe that could be handled differently than just giving up on it.)

**Comment by isidorn** [comment]
Check my code again, we can also be in the stat case if the lstat failed.
