### ISSUE TITLE
Run Post extension uninstall script after extension is not running in any VS Code window

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#44552]
Refs: #44363

Use this extension, just rename .zip to .vsix
It is just a basic ts extension, with the following postinstall script

`"vscode:uninstall": "node hey.js", `

And the hey.js is the following file:

```javascript
var fs = require('fs');

fs.writeFile('mynewfile1.txt', 'Hello content!', function (err) {
  if (err) throw err;
  console.log('Saved!');
});
```

[test-extension-0.0.1.zip](https://github.com/Microsoft/vscode/files/1762420/test-extension-0.0.1.zip)

Notice how after uninstalling the extension the file does not get created.
If I execute that script from node command line the file gets nicely created.

**Comment by sandy081** [comment]
@isidorn Your script is creating a new file in the extension folder which is removed after uninstall hook is called. I would suggest to create the file in a different location and try.

**Comment by sandy081** [comment]
@isidorn May be not in extension folder, when I run out of sources, it is getting created in my vscode workspace. So I assume it is also creating in vscode application. Can you please try to create in a known location and test?

**Comment by isidorn** [comment]
Still does not work if I create it in an absolute location, reopening.
Did you try this out on windows following my steps?

```javascript
var fs = require('fs');

fs.writeFile('c:\\Users\\IEUser\\development\\mynewfile1.txt', 'Hello content!', function (err) {
  if (err) throw err;
  console.log('Saved!');
});
```

**Comment by rebornix** [comment]
Ran into the same problem, it doesn't seem to get executed.

**Comment by isidorn** [comment]
So the issue is that the script does not get executed on vscode reload
but once I restart vscode completelly
so if I uninstall extension and reload -> no output in shared process
Once I quite vscode and start it again the script gets exectued just fine. I find this behavior weird and would expect the script to be installed after reload.

**Comment by sandy081** [comment]
@isidorn @rebornix Script is supposed to run only after VS Code restart (not reload). Restart is VS Code shutdown and start. I assumed restart means that. I will update the description of the TPI and also the documentation of the hook.

Running script after restart was intentional because, we can rely on a window reload after uninstall as the extension might be running in a different window. We can also run the script once we know that no window is running the uninstalled extension but, this needs window management in shared process.

I would wait and see if extension authors are fine with this strategy and wait for the feedback before going crazy and implement that.

**Comment by rebornix** [comment]
@sandy081 make sense as it doesn't confuse end users, if extension authors are good with that, then it's good.

**Comment by Soothsilver** [comment]
Thank you for this thread. I spent two hours trying to discover why my uninstall script wasn't working. It turns out that I needed to uninstall, close and reopen rather than click the convenient "Reload Required" button :).
