### ISSUE TITLE
Edit breakpoint is larger than its brothers

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#44550]
Testing #43836

![image](https://user-images.githubusercontent.com/22350/36726773-3ac73378-1bbb-11e8-9e66-3ca8768a9f89.png)

**Comment by joaomoreno** [comment]
Disabled too!

![image](https://user-images.githubusercontent.com/22350/36726832-66042924-1bbb-11e8-937f-e4e4fae42627.png)

**Comment by isidorn** [comment]
Thanks for finding this.
I fixed the size of the disabled icon, the conditional was always a bit larger

@chryw it seems like the new breakpoint icons you provided are slightly larger than our previous icons. I am personally not a fan of this since I think they already draw too much attention with the red color and increasing the size is not really necessery.
Is it possible for you to decrease the size of the new icons such that they are the same as our previous breakpoint icon?
There is no hurry for this, I would like to do it next milestone if you have the time

**Comment by chryw** [comment]
@isidorn I see [this folder](https://github.com/Microsoft/vscode/tree/master/src/vs/workbench/parts/debug/browser/media) has a mix of old and new icon files. Some files are not made by me. That's probably why they're inconsistent in size and color. I can do a pass on the entire folder. Are these all the debug icons?
#44849 related color issue

**Comment by isidorn** [comment]
@chryw yes they are all debug icons and only used there.
It would be brilliant if you could make a pass and provide a PR which fixes these issues.

**Comment by chryw** [comment]
@isidorn will do this week :-)

**Comment by isidorn** [comment]
@chryw great, thanks :)
