### ISSUE TITLE
Improve drag and drop feedback of root folders

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#44551]
Testing https://github.com/Microsoft/vscode/issues/29715

Some feedback:
* I suggest to collapse all expanded folders when someone starts to drag a root folder to make it easy to find the drop target
* should the drop feedback be different in this case (see video)? it almost looks as if I could drop the root folder into another root folder. 

We could also maybe change the confirmation dialog message to make it clear that moving a root folder is not moving it physically.

![flicker_chrome58](https://user-images.githubusercontent.com/900690/36726813-5391ec40-1bbb-11e8-882e-7f9544fe4b12.gif)

**Comment by isidorn** [comment]
@bpasero I experimented with this and:
* Collapsing all folders when you start dragging gives a very weird effect since the root you are dragging changes position and is no longer under the mouse
* I do not think a confirm message is needed if only roots are dragged - it is not like any underlying fs data is changed. I would just do it without a dialog
* Yeah the drop feedback could be different however that is backed in the tree and I do not really want to hack the tree to make this customisable
* Folders should also not expand when you hover over them with a root, but this is also baked in the tree and I am not so passionate on making this customisable

Let me know what you think.
also fyi @joaomoreno

**Comment by bpasero** [comment]
> I do not think a confirm message is needed if only roots are dragged - it is not like any underlying fs data is changed. I would just do it without a dialog

It would be consistent though. People have complained that it is too easy to accidentally start a DND operation and so I added the confirmation dialog (with a setting to disable it). We can also wait for users complaining about this (again).

**Comment by isidorn** [comment]
Ok for now I will at least change the message to be more precise.
Regarding the other things I see no actionable items.

**Comment by isidorn** [comment]
![screen shot 2018-03-14 at 15 47 53](https://user-images.githubusercontent.com/1926584/37409633-155a1142-279f-11e8-822d-f0d25e8df7de.png)

Instead of 'order' I could say 'position'

**Comment by bpasero** [comment]
@isidorn yeah looks great

**Comment by isidorn** [comment]
Ok pushed the message change. Closing this issue since I do not plan to improve the other things you outlined - let me know if you have suggestions on how to do that.
