### ISSUE TITLE
Can't edit function breakpoints after first edit

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#44556]
Testing #43836

Shouldn't double click allow me to edit the breakpoint?

**Comment by isidorn** [comment]
Pushed some function breakpoint polish. Now you can double click to edit and there is also a context menu "edit breakpoint" item.
There are still some rough edges since the issue is taht I am reusing the inputBox template and the listeners have some timing issues. But will only fix those if users complain since it requires a bigger refactoring (function breakpoints are not that popular)

**Comment by bpasero** [comment]
I would probably expect the input to close when focus moves out, same as how the explorer rename works.

**Comment by isidorn** [comment]
That is not reported, just created an issue to track that 
https://github.com/Microsoft/vscode/issues/44912
