### ISSUE TITLE
Up/down in notifications should reset focus

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#44587]
VS Code version: Code - Insiders 1.21.0-insider (1a84a882737184488d965426747a05474f54a759, 2018-02-27T06:17:53.785Z)
OS version: Linux x64 4.13.0-36-generic

---

#44319

Repro:

1. Trigger 2 notifications with buttons
2. Open notifications center
3. Press tab, the first button of notification 1 should be focused
4. Press down, moving "focus" to notification 2
5. Press tab, the second button of notification 1 is focused

I expect the first button of notification 2 to be focused

![image](https://user-images.githubusercontent.com/2193314/36734939-cf59fbc4-1b89-11e8-9e63-ab94e1653324.png)

**Comment by bpasero** [comment]
@Tyriar to be clear, you expect arrow-up/down navigation to work when one of the button has focus, is that true?

**Comment by Tyriar** [comment]
@bpasero the problem is that up and down do work when the button has focus, but the actual document focus doesn't go with it. I want navigating up and down to clear the focus on the button, so pressing tab will select the first button in the active notification.

**Comment by bpasero** [comment]
@Tyriar got it

@joaomoreno it looks like our [list commands](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/electron-browser/commands.ts#L29) are fired even if the list/tree does not have DOM focus. I think previously that was not the case when we had a focus tracker in place. Now since we have a scoped context key service, I guess the list/tree keybindings remain active when focus is within a list item widget as in this case.

One idea is to fix it by always calling tree/list.domFocus() after each command that gets invoked to ensure that the list/tree has DOM focus again.

Would you agree? I fear regressions, so maybe better to do this in debt week.

**Comment by joaomoreno** [comment]
@bpasero Yup this is the problem with the context keys. That's why the `inputFocus` key exists: so we know when to exclude those rules when the user is focused on an input.

Another alternative is to create yet another scoped context key service for the action container, which would set `listFocus` to false.
