### ISSUE TITLE
Notifications center background is blue in high contrast theme

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#44596]
VS Code version: Code - Insiders 1.21.0-insider (1a84a882737184488d965426747a05474f54a759, 2018-02-27T06:17:53.785Z)
OS version: Linux x64 4.13.0-36-generic

---

#44319

![image](https://user-images.githubusercontent.com/2193314/36736305-1e3b7d78-1b8d-11e8-8c7e-d20e2c97e2d1.png)

I don't think this background is used elsewhere?

**Comment by bpasero** [comment]
@Tyriar we do, it is the editor widget background color that is e.g. also used for find widget:

![image](https://user-images.githubusercontent.com/900690/36744000-fa684264-1beb-11e8-82d5-b8b17c051c7b.png)

The idea is to pick a background color that has some contrast to the editor because that is typically where notifications will appear on top of.
