### ISSUE TITLE
Mention nvs alongside nvm in error message

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#44605]
Issue Type: <b>Bug</b>

Testing #44452

Mention nvs here:

![screenshot from 2018-02-27 16 18 07](https://user-images.githubusercontent.com/9205389/36737021-51da1aa2-1bda-11e8-8dba-80d7f3028421.png)

VS Code version: Code - Insiders 1.21.0-insider (1a84a882737184488d965426747a05474f54a759, 2018-02-27T06:17:53.785Z)
OS version: Linux x64 3.13.0-108-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (4 x 2194)|
|Load (avg)|2, 1, 0|
|Memory (System)|3.86GB (1.31GB free)|
|Process Argv|/usr/share/code-insiders/code-insiders --unity-launch|
|Screen Reader|no|
|VM|100%|

</details>Extensions: none
Reproduces without extensions

**Comment by weinand** [comment]
In addition we should show this error as a modal dialog.

**Comment by chrmarti** [comment]
Can we add 'a' before 'Node.js version manager'? /cc @chrisdias for English.

![image](https://user-images.githubusercontent.com/9205389/36893322-e3e3b1cc-1e07-11e8-844b-14e635998695.png)

**Comment by weinand** [comment]
No. 'a' would mean "no specific". This would require this sentence structure:
  `Attribute 'runtimeVersion' requires a Node.js version manager, e.g. 'nvm' or 'nvs'`
But here the semantics is wrong because no other than the two are supported.

So 'the' is more appropriate:
  `Attribute 'runtimeVersion' requires the Node.js version manager 'nvm' or 'nvs'`
