### ISSUE TITLE
Circular symlink causes file explorer to hang forever

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#44628]
Testing #44097

Have two projects:

```
a/
  foo/
    symlink2 -> b/
b/
  bar/
  symlink1 -> a/foo
```

Open project b. This setup can cause file explorer to never show anything.

Stable does not have this issue. Seems @bpasero has some logic there to prevent circular symlinks, so when you click open symlink1, symlink2 is not being shown at all.

**Comment by isidorn** [comment]
This works fine with the latest symlink fixes for me
Note that not all symlinks are shown as symlinks due to errors which is already captured here https://github.com/Microsoft/vscode/issues/44543

![screen shot 2018-02-28 at 12 04 38](https://user-images.githubusercontent.com/1926584/36784420-9503ca9e-1c7f-11e8-9c49-a83f8742e37c.png)
