### ISSUE TITLE
Show correct path for items under symlink folder

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#44635]
Testing #44097 

Let's say you have a symlink at `~/a/sym` pointing to `~/b`.
When opening the symlink and hovering on `~/b/foo.js`, the hover message shows a wrong path `~/a/sym/foo.js`. It should be `~/b/foo.js`.

Of course all hover messages are absolute path from the root instead of from home folder.

![sym](https://user-images.githubusercontent.com/4033249/36749489-c425575a-1baf-11e8-81c5-a01cab3b6239.gif)

**Comment by pwhissell** [comment]
If the symlink contains typescript which references files using relative paths, vscode will show tsling / typescript errors. Heres an attempt to demonstrate the bug
https://stackblitz.com/edit/angular-component-tree

stackblitz doesnt allow for symlinks so in a real example, the folders "sword" and "axe" under "hero" would be symlinks pointing to the ones directly under "components". In my example, the imports of the models in the src/app/components/hero/sword/sword.component.ts are in error however since the src/app/components/hero/sword is (would be in a non stackblitz example) a symlink pointing on src/app/components/sword/, the relative path should be ok

**Comment by pwhissell** [comment]
@octref @isidorn where can we track the advancements with this issue

**Comment by isidorn** [comment]
This issue is currently assigned to the backlog which means there is no immediate plan to fix it.

**Comment by pwhissell** [comment]
@isidorn does the new symptom I posted give the issue more importance?

**Comment by bpasero** [comment]
@octref isn't this https://github.com/Microsoft/vscode/issues/18837 where we do not allow you to open a symlink?

**Comment by octref** [comment]
@bpasero I've simplified the case a bit. Say I have:

```
/a
  /foo.txt
/b # This is a symlink that points to /a
```

![image](https://user-images.githubusercontent.com/4033249/45108403-5a191400-b0f1-11e8-87fb-f47fb41ba2ce.png)

I think with your new change, I can no longer open `b/foo.txt` from File Explorer, is that correct?
However, for both the real `a/foo.txt` and the symlinked `b/foo.txt`, `fs.realpath` returns absolute path for `a/foo.txt` while the hovers aren't (hovering on both items show absolute path for `a/foo.txt`).

**Comment by bpasero** [comment]
@octref the only impact my change is that when you open a single folder and that folder is a symlink we will open the symlink in the explorer and not follow it. That means, any children will show the symlink as path and not the target.

**Comment by octref** [comment]
OK, I'll close this as-designed then.
