### ISSUE TITLE
Issue reporter length error message is confusing

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#44634]
Related to #44245

**Steps to reproduce**
1. Type a lot of text in the issue reporter (especially on windows)

**Bug**

![screen shot 2018-02-27 at 11 05 09 am 1](https://user-images.githubusercontent.com/12821956/36748900-1794f744-1bae-11e8-9ff6-7190f21c690e.png)

This error message states what is wrong at the code level but not what the user should do to fix it. Something along the lines of: "There is too much text. Please enter additional information on github after opening issue"

**Comment by RMacfarlane** [comment]
I just changed the behavior of the reporter to copy the data to the clipboard in this case and open the issue preview with the text "We have written the needed data into your clipboard because it was too large to send. Please paste.". Let me know if that makes sense, I think it's a better user experience than being blocked on the form and having to figure out what to shorten.
