### ISSUE TITLE
NVS runtimeVersion not being used on windows

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#44640]
Issue Type: <b>Bug</b>

Testing #44452

**Steps**
1. Install NVS
1. Install: node 8.9 and 9.6 with nvs: `nvs add 8.9` `nvs add 9.6`
1. Run `nvs use 9.6`
1. Start vs code
1. Confirm that node `9.6` is active in the environment
1. Try debugging a programming using ` "runtimeVersion": "8.9.4"`

**bug**
The runtimeVersion does not seem to have any effect. My program always runs under node 9.6

VS Code version: Code - Insiders 1.21.0-insider (1a84a882737184488d965426747a05474f54a759, 2018-02-27T09:01:48.555Z)
OS version: Windows_NT x64 10.0.17052

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2609 v3 @ 1.90GHz (6 x 1896)|
|Memory (System)|31.93GB (16.98GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe .|
|Screen Reader|no|
|VM|0%|

</details>
Reproduces only with extensions

**Comment by chrmarti** [comment]
Same on Linux. When I don't set a default version, it complains it cannot find node.

**Comment by weinand** [comment]
This seems to be a general problem with node-debug2: it does not pick up the node version from the "Path" environment variable.

This is independent from "nvs" and it is not a regression since it was already broken in VS Code 1.20.1.

To reproduce:

- make sure that you have at least two node versions installed in "nvm" with version >= 8.0 (to force node-debug2).
- determine your default node version by running `node --version` from the command line
- create a trivial node.js program `console.log(process.version)`
- in your launch config add `runtimeVersion` and pick the non-default node version
- F5

Observe: the program outputs the default node version (which is the bug)

- now install a node version in "nvm" with version < 8.0
- set `runtimeVersion` to that version
- F5

Observe: the program outputs the correct node version

**Comment by roblourens** [comment]
I am missing https://github.com/Microsoft/vscode-node-debug/commit/52b34ebffd2b7fc5c27c978e30f1595924095464
