### ISSUE TITLE
Missing line when splitting the second time

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#44662]
Testing #44446 in Mac

There are 3 lines rendered in the terminal. The first split captures all of them. The second split results in the second terminal losing one of the lines

![terminal-missing-line](https://user-images.githubusercontent.com/16890566/36758793-45986ab0-1bca-11e8-80fa-dec48c363efc.gif)

**Comment by Tyriar** [comment]
Ok so I didn't think I could do anything about this when I saw it but I was wrong :smile: 

What caused the weirdness with the second terminal is that it received 2 layouts/resize events, one when the last terminal pane was added the group and one when the sizes are "reset" afterwards. I changed it such that terminal layouts are disabled when the pane is being added and re-enabled immediately afterwards, so they get a single "reset" resize.

**Comment by ramya-rao-a** [comment]
Checked from source. Can still repro, only now the problem occurs when you split the third terminal 
![boo](https://user-images.githubusercontent.com/16890566/36821750-5f3b96f6-1ca9-11e8-8cf6-7a1412b86613.gif)

**Comment by Tyriar** [comment]
To clarify, this will still happen because it's bash telling the terminal what to draw when the terminal is resized, it just won't happen as much as before because before it was resizing to some value (lower than correct) and then the correct value. Right now you're just seeing bash messing up when you resize the window which will also happen on external terminals.
