### ISSUE TITLE
Extension debug: --user-data-dir must be used for debug launch

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#44734]
Steps to Reproduce:

1. run VSCode with `--user-data-dir <some folder>`
2. debug an extension

=> the debugger starts another instance of VS Code without the user-data-dir argument and as such debugging will not work

Possible fix is to add the same argument again.

**Comment by weinand** [comment]
The `user-data-dir` argument is only the tip of the iceberg; there are probably more CLI arguments that would need to be passed on too. 

The debugger could probably find the relevant CLI arguments passed to its own VS Code instance and pass them onto the debuggee VS Code instance.

But I would prefer an approach where the debugger would not have to understand what these arguments are. 

I think there are two options for how to do this:

- the debugger retrieves the relevant CLI arguments en-bloc via some API and passes them on to the debuggee blindly,
- the debugger passes only an ID of the originating VS Code instance on to the debuggee so that it could retrieve the relevant CLI arguments itself.

The advantage of the first approach is that the debugger could show the real command line for the debuggee in the debug console, so the "--user-data-dir" would be visible.

/cc @isidorn @roblourens

**Comment by roblourens** [comment]
Yes I guess we would need an extension host API for this.

**Comment by sean-mcmanus** [comment]
I also hit this issue after using --user-data-dir. I discovered the workaround of passing the --user-data-dir in the args.

**Comment by sean-mcmanus** [comment]
FYI, I accidently used a space instead of = when setting --user-data-dir and it gave some confusing error message and my extension failed to activate...not sure if there's a better way to handle that type of error.

**Comment by alefragnani** [comment]
In the current releases (both Stable and Insiders), I'm not being able to debug an extension with `--user-data-dir`. 

Both releases complains about _timeout_, but the Stable, shows the _already known 10 seconds timeout message_ in the `[Extension Host]`window, and the Insiders pop ups a dialog message in the extension's source window.

Is there any current workaround for that?
