### ISSUE TITLE
${workspaceRoot} variable shouldn't be resolved in multi-root workspace

### ISSUE THREAD

**Issue by tsalinger** [Microsoft/vscode#44748]
Testing #44449

The following case fails for me on Ubuntu 16.04:
>In a multi root workspace with multiple folders the variable is not resolved and remains unchanged.

This is the workspace setup:
![capture](https://user-images.githubusercontent.com/15158320/36793435-b0ef00d4-1c9d-11e8-9b4c-486e5914705d.PNG)

Expected: The ${workspaceRoot} variable doesn't get resolved
Actual: It gets resolved to 'proj1'

Entering an invalid file name yields the following error message:
>Attribute 'program' does not exist ('/home/a/Desktop/projects/test-heuristic-workspaceVars/root/proj1/p/p_1.js').

**Comment by isidorn** [comment]
This is actually expected behavior. It should only not be resolved if the launch is in a workspace configuration file or a user configuration file.
If a launch is living inside a folder then it is perfectly fine for it to be resolved against that folder.

I just verified on my machine and both these cases work fine.
Closing as desgined
