### ISSUE TITLE
Debugger setting a different 'this' than node.js when using arrow functions

### ISSUE THREAD

**Issue by ejose19** [Microsoft/vscode#44785]
- VSCode Version: 1.20
- OS Version: Ubuntu

Steps to Reproduce:

1. Create a js file and add this code:

```
let Person = {
    name: 'Test',
    getNameF: function() {
        console.log(this.name);
    },
    getNameAF: () => {
        console.log(this.name);
    },
};

Person.getNameF();
Person.getNameAF();
```

2. Run the code with node and you will get:
```
Test
undefined
```

Which implies that the 'this' inside the arrow function is undefined (as should be), however if you add a breakpoints on:
```
Person.getNameF();
Person.getNameAF();
```

You will notice the 'this' value in the debugger is the same in both functions! so for some reason it's not binding to node 'this'

Note: Tested on chrome browser debugger and the expected 'this' value (which is undefined) appears for the arrow function, so this problem is related to vs code only.

**Comment by weinand** [comment]
I've compared the behaviour of VS Code and Chrome Dev Tools.

Here is the Chrome Dev Tools state for the two breakpoints. 

Line 4:
![2018-03-01_10-58-50](https://user-images.githubusercontent.com/1898161/36838686-1cabe5ba-1d40-11e8-9335-91faff67be71.png)

Line 7:
![2018-03-01_10-59-36](https://user-images.githubusercontent.com/1898161/36838688-1eba431a-1d40-11e8-947d-de19831bc5f7.png)

The Scope view (Variables view in VS Code) shows no difference for both breakpoints in CDT and in VS Code (which seems to be a bug both in VS Code and CDT).

Evaluating "this" in the REPL results in this (VS Code):

![2018-03-01_11-06-04](https://user-images.githubusercontent.com/1898161/36838901-ba57ce50-1d40-11e8-864a-1245d6af2883.png)

This is the same as in CDT:

![2018-03-01_11-08-31](https://user-images.githubusercontent.com/1898161/36838967-e5c5ef9a-1d40-11e8-9216-e886e6e9a0d6.png)

Again VS Code and CDT behave the same.


But I see a difference when hovering over "this".

In VS Code there are no differences (which is the bug), but in CDT they differ.

The problem is that VS Code implements the hover by matching variables against the information available in the Variables view. Since there are no differences shown in that view the hover does not show any differences either.

If I enable an option in VS Code to implement the hover by using "evaluate", the problem is solved:

![2018-03-01_11-18-04](https://user-images.githubusercontent.com/1898161/36839369-3c0385ce-1d42-11e8-9afb-8495ca802b3a.png)

**Comment by roblourens** [comment]
This is https://github.com/Microsoft/vscode/issues/13967 dupe bot found one but not the original.

It is fixed in Chrome so the fix should be coming down the pipeline to newer node versions very soon.

**Comment by roblourens** [comment]
> should we turn on evaluate based hovers for node-debug?

I don't think we should turn it on to fix one bug. I'm also wouldn't want to trigger side effects in getters without an explicit evaluate step like Chrome devtools has.

**Comment by isidorn** [comment]
@roblourens why don't we turn on evalute on hover at least for insiders to get some feedback before making a final decision?
Imho triggering a getter will be a very rare case, while the evaluate will be much more precise compared to our current heuristic of looking at the variables (ignoring the scope ranges which are wrong most of the time)

**Comment by roblourens** [comment]
We can try it. Have there been many issues besides the scope ranges issue?

Is it weird that CDT shows the ReferenceError when evaluating throws?

![image](https://user-images.githubusercontent.com/323878/37063496-6d3ae136-214e-11e8-8d96-9510afc0510a.png)

**Comment by roblourens** [comment]
> I wouldn't want to trigger side effects in getters without an explicit evaluate step like Chrome devtools has.

I'm wrong, if you hover over `something.getter` in CDT, there is no explicit step. Only when you hover `something` and see the `getter` property.

But in vscode we invoke `getter` when you hover `something`.

**Comment by isidorn** [comment]
@roblourens there have not been so many issues lately, but through history I remember people always complaing about this.
Yeah, let's try it out and get feedback for a couple of weeks and than make an informed decision.

Another idea is to do evaluate when our first strategy does not find any results. So to do evaluate as a fallback. We would probably need a new capability for this though.

**Comment by ejose19** [comment]
I updated my vscode insiders to latest version and still get this to reference the object, both by side panel and by hovering. Was this implemented yet?

**Comment by ejose19** [comment]
Also worth nothing, when I used google chrome my results differ from @weinand, as CDT was showing the correct result in both hovering and side panel.

![Image](https://i.imgur.com/s7kK8GFg.png)

**Comment by roblourens** [comment]
It's not checked in to Insiders yet.
