### ISSUE TITLE
Support for nvm aliases in runtimeVersion

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#44787]
Issue Type: <b>Feature Request</b>

While testing #44452.

I use aliases since they are easier to remember than version numbers. For example, I alias node versions with the name of the deployment environment my apps run at such as 'azure', 'heroku', 'aws'.

I'd like to use those aliases in the launch configs.

VS Code version: Code - Insiders 1.21.0-insider (3fec61014742dec894b3a31cdf8556bf533cb0e1, 2018-02-28T06:08:46.169Z)
OS version: Darwin x64 16.7.0

**Comment by rhodgkins** [comment]
I'd love this - mainly because of the ability to specify `lts/carbon` and know that it'll use the latest carbon (v8.x) that it can find from nvm. Ideally it would be nice if vscode could pick up the node version to use from the .nvmrc file though!

**Comment by weinand** [comment]
I do not want to duplicate specific nvm and nvs functionality in VS Code because it would be a pain to keep up to date.

What we currently have is the minimal set of functionality that is actually helpful and simple to implement because it just relies of version numbered folders in the filesystem. Anything symbolic (e.g. "latest". "lts"), requires to locate nvm or nvs specific mapping information.

This is not planned.

**Comment by rhodgkins** [comment]
@weinand thats a shame - I think it should at least support looking at the `.nvmrc` file for the version to use.

Currently you need to set an explicit version in the launch config, which means that version **must** be installed. This might not be the case if you're targeting 8.11.x for example as you might have 8.11.2 specified in the launch config, but `nvm use` has picked up `8.11.4` (as the `.nvmrc` specifies `8.11`).

**Comment by weinand** [comment]
Please feel free to submit a PR. The code is here: https://github.com/Microsoft/vscode-node-debug/blob/3ecc04380a20b0aba1753d80e3bb435341b3b578/src/node/extension/configurationProvider.ts#L147
