### ISSUE TITLE
"runtimeVersion" does not switch version with nvs on Linux

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#44798]
Issue Type: <b>Bug</b>

Testing #44452.

It correctly complains about the "runtimeVersion" not being available when I set it to one that is not installed, but setting it to an installed version then uses the default version instead of the specified one.

NVS_HOME is set when launching from a terminal and also when launching from the dock. 

VS Code version: Code - Insiders 1.21.0-insider (9a04587cc6b42c332609a08bfd7e2dbeac592c21, 2018-03-01T06:47:39.037Z)
OS version: Linux x64 3.13.0-108-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (4 x 2194)|
|Load (avg)|1, 1, 0|
|Memory (System)|3.86GB (0.22GB free)|
|Process Argv|/usr/share/code-insiders/code-insiders|
|Screen Reader|no|
|VM|100%|

</details>Extensions: none
Reproduces without extensions

**Comment by weinand** [comment]
For me NVS_HOME is not set when VS Code is launched from Dock:

![2018-03-01_12-45-51](https://user-images.githubusercontent.com/1898161/36843342-edd086e2-1d4e-11e8-8c45-de852d056362.png)

You can only verify this with Chrome Dev Tools because the integrated terminal loads the env vars in a different way and there NVS_HOME is correctly defined.

I've enabled the fallback code for all OSes (before it was only done for Windows).

In addition 'nvs' stores versions on linux in a subdirectory 'bin' which my code was missing. Since I had 'nvm' installed, I did not notice this...

**Comment by weinand** [comment]
Verifiers: Fix will be in Friday build!
