### ISSUE TITLE
Integrated Console - run more than one type

### ISSUE THREAD

**Issue by kevinbowman** [Microsoft/vscode#44803]
### Issue Type
Feature Request

### Description

I have Bash set as my default console, but often want to use POwershell.  I can only seem to get the powershell console open if I hit debug on a powershell script.  Why not choose the console type when a user selects "+"

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:33:21.935Z)
OS version: Windows_NT ia32 6.1.7601

**Comment by Tyriar** [comment]
The + means create a new terminal, if you want to use multiple different types you can use this extension https://marketplace.visualstudio.com/items?itemName=Tyriar.shell-launcher

The reasoning behind + not showing a selector is because the majority of people will only need one, and adding additional steps makes the UI feel more clunky.
