### ISSUE TITLE
Cursor becomes invisible at lower zoom levels

### ISSUE THREAD

**Issue by dheavern** [microsoft/vscode#44867]
### Issue Type
Bug

### Description

1.) Open a new editor
2.) From default zoom, zoom out 4 times

The cursor will become invisible and intermitantly invisible between abitrary characters of any text.  This may be dependent on screen resolution or other factors I am not aware of.

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:23:28.607Z)
OS version: Darwin x64 17.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.09GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron --disable-extensions|
|Screen Reader|no|
|VM|0%|

</details>Extensions disabled
Reproduces without extensions

**Comment by JustRiedy** [comment]
If this helps troubleshooting at all, unable to replicate issue on following version.

### VS Code Info
Version 1.20.1
Commit f88bbf9137d24d36d968ea6b2911786bfe103002
Date 2018-02-13T15:34:36.336Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

### OS Info
Windows 10 Version 1607 (OS Build 14393.1944)
Resolution: 1680x1050

### Misc
Attempted with an empty new file, a Ruby file and a PowerShell file just in case extensions change behavior.

**Comment by alexandrudima** [comment]
I can reproduce every now and then, depending on the cursor position (horizontally).

This has to do with the way zooming is implemented. e.g.:
* on my mac (on an external 4K display)
* when zooming out 4 times, the pixel ratio is:
* `window.devicePixelRatio` is `0.9645061492919922`
* so that means `1 physical pixel` = `1.0368000253125007`
* we paint the cursor with the width `1.0368px`

But still, depending on the horizontal position of the sidebar, or the cursor horizontal location, the width gets rounded down to `0` by Chromium:
![kapture 2018-03-05 at 12 22 04](https://user-images.githubusercontent.com/5047891/36972553-d62df3b6-206f-11e8-9ef5-fdd86bd867c6.gif)

My honest recommendation is to never use `window.zoomLevel` if you want to program professionally. Just use `editor.fontSize` and co. to change the size of things...
