### ISSUE TITLE
Git: weird overflow behaviour in repositories view

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#44925]
See video:

![before](https://user-images.githubusercontent.com/900690/36903510-38a0f2b2-1e2e-11e8-84c6-af2cf3ec3ed7.gif)

I think I would expect everything no the right hand side to take space away from the left hand side without ever shrinking.

**Comment by joaomoreno** [comment]
Actually no, since the repository's name is the most important thing. Otherwise you'd have actions without knowing which repository they affect, right?

**Comment by bpasero** [comment]
@joaomoreno I see. you could still hide the "git" label, since that seems to be less important.

**Comment by raygervais** [comment]
I'd like to help develop a fix for this, going off of @bpasero suggesting of hiding the git label where appropriate if that is the desired end-result. 💻 👍

**Comment by raygervais** [comment]
Just wanted to bounce a question here, I'm assuming that we don't want to use media query for this bug fix, then it has to be dynamically calculated based on the title of the branch. Where would you suggest is the best function to update to include such calculation which interacts with type? 

I want to assume here, since this is where we set the title based on the provider's variables: 
https://github.com/Microsoft/vscode/blob/e82ae3cdf12a256e134c5590df260b7d80008adb/src/vs/workbench/parts/scm/electron-browser/scmViewlet.ts#L158

I'm thinking of creating a const max-width which is the breakpoint between when the SCM type should be displayed, and when it should be hidden. If the title which is assigned below is greater than said breakpoint, hide SCM Type.
https://github.com/Microsoft/vscode/blob/e82ae3cdf12a256e134c5590df260b7d80008adb/src/vs/workbench/parts/scm/electron-browser/scmViewlet.ts#L157

Ideas? Thoughts?

**Comment by joaomoreno** [comment]
How would that look like?

**Comment by joaomoreno** [comment]
Closing as obsolete.
