### ISSUE TITLE
Emmet: Expand Abbreviation not available in interactive playground

### ISSUE THREAD

**Issue by gingerbeardman** [Microsoft/vscode#44975]
- VSCode Version: 1.20.1
- OS Version: Mac OS X 10.13.3 (17D102)

Steps to Reproduce:

1. Open interactive playground
2. Go to Emmet section
3. position caret at the end of the Emmet snippet
4. Try to invoke "Emmet: Expand Abbreviation" through command palette or shortcut key (tab)

Does this issue occur when all extensions are disabled?: Yes

See: https://github.com/Microsoft/vscode/blob/4b55cf7b5c019f092cbec418eeee16d1665c739c/src/vs/workbench/parts/welcome/walkThrough/electron-browser/editor/vs_code_editor_walkthrough.md

**Comment by gingerbeardman** [comment]
Not a duplicate @vscodebot

**Comment by ramya-rao-a** [comment]
Thanks for reporting @gingerbeardman 
We'll take a look at this, this month

**Comment by gingerbeardman** [comment]
This is fixed in Version 1.21.0 (1.21.0)

**Comment by gingerbeardman** [comment]
"Emmet: Expand Abbreviation" is not available in the Command Palette so the only way you can expand us using tab, which requires user setup.

So I think there's still work to do on this.

**Comment by ramya-rao-a** [comment]
Fixed with https://github.com/Microsoft/vscode/pull/45434

The text in the playground is updated to use the `Emmet: Expand Abbreviation` item in the `Edit` menu which works.

The Emmet commands from the command pallet will not work in the interactive playground, as access to the active editor is missing
