### ISSUE TITLE
Search shouldn't take into account unsaved changes

### ISSUE THREAD

**Issue by richardneal** [Microsoft/vscode#45006]
- VSCode Version: 1.20.1
- OS Version: 16299.rs3_release

I understand when it might be desirable to have search be able to look through unsaved changes, however it causes a frustrating experience when search can't find some text that appears in build output. 

My scenario involved changing the name of an appx, and I accidentally left the name changes in Package.appxmanifest unsaved, so the former name showed up in error messages in my build output referencing the old .exe name. I spent a good while trying to track down where the old name was still referred to in my files, but as the file was open and had the changes made, search couldn't find any.

**Comment by LWChris** [comment]
I think by default you _want_ to search through the visible text, because otherwise it could be very confusing. Imagine if I type "hello world", then search for "hello" and it finds nothing.

A better approach could be to search through the project files as is, i. e. with modifications for the opened files and the file system version for all other files. If the file is opened and has unsaved modifications, perform an additional search on the currently saved file. If at least one of both versions has a match, add them to the result with an additional level in the tree, one node being "Saved file (as on the file system)" and the other "Opened file (has unsaved modifications)", and list the respective matches.

In your case, the result would look like this:

```
[ oldappname                                          ]

1 result in 1 file:
    v Package.appxmanifest                          (1)
        v Saved file (as on the file system)        (1)
            <name>oldappname</name>
        > Opened file (has unsaved modifications)   (0)
