### ISSUE TITLE
Unable to fork a node process from extension server

### ISSUE THREAD

**Issue by mattacosta** [Microsoft/vscode#4501]
- VSCode Version: 0.10.12-insiders
- OS Version: Windows 10

I'm trying to start a new node process to handle a long, complex task, but I can't seem to get the child process to start correctly. I've also tried calling the fork method with empty args, and with an options object that had an empty env property, with no success. When running node from a command prompt, I get the expected output as well, so except for trying to do it the hard way, I'm more or less out of ideas...

worker.ts
```typescript
process.send('working');
process.exit(0);
```

server.ts
```typescript
// snippet of relevant code
let child = cp.fork('worker');
child.on('exit', (code, signal) => {
  connection.console.log('exiting child process (' + code + ')');
});
child.on('message', (message) => {
  connection.console.log('is working');
});
```

expected:
```
is working
exiting child process (0)
```
actual:
```
exiting child process (1)
```

**Comment by jrieken** [comment]
@alexandrudima @dbaeumer You guys have experience with this, right?

**Comment by alexandrudima** [comment]
@mattacosta The extension host is an Electron process running in a "nodejs mode". Because it is an Electron process (that also creates windows), under Windows, it is not possible to get the stdin/stdout when you fork from it. Our workaround consists of creating pipes to the forked process to get stdin/stdout support.

See https://github.com/Microsoft/vscode/blob/master/src/vs/base/node/stdFork.ts and https://github.com/Microsoft/vscode/blob/master/src/vs/base/node/stdForkStart.js

**Comment by mattacosta** [comment]
Ugh. I was really hoping you weren't going to say that. I had looked at enough of the language client source code to figure that's probably what was going on, but was hoping that there was a method that wouldn't require such a high implementation cost.

Also, if I'm understanding this correctly, shouldn't [stdForkStart.js#L103](https://github.com/Microsoft/vscode/blob/master/src/vs/base/node/stdForkStart.js#L103) use && instead?

**Comment by alexandrudima** [comment]
@mattacosta Nice catch! Filed #4562

It is a nasty one, but we won't do anything for March, but rather for April, as this doesn't have any user visible impact, probably because nobody uses fs.writeSync(1,...). It used to be that the TypeScript language server used that a few months ago, but they moved to use the much more sane process.stdout

**Comment by markbrocato** [comment]
Running into a similar problem here: http://stackoverflow.com/questions/37841310/visual-studio-code-extension-child-process-fork-doesnt-work.

Forked processes just hang.  It's not a question of sending/receiving messages.  The process just does nothing.  Also, the stdFork script above doesn't compile for me.  The vs/base/common/uri is not found.

Is there any better answer to how to fork a process from an extension?

**Comment by alexandrudima** [comment]
@markbrocato answered at http://stackoverflow.com/a/38915764/4850393
