### ISSUE TITLE
Improper progress during search

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#4508]
![search](https://cloud.githubusercontent.com/assets/1794099/13925649/66270d78-ef89-11e5-955f-beb231ac20a2.gif)

See attached gif, the progress bar quickly goes to ~90% and then takes a long while until it reaches 100%.

**Comment by bpasero** [comment]
@jrieken can you zip the workspace and attach and include your settings?

**Comment by jrieken** [comment]
unsure if that is needed: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/search/browser/searchViewlet.ts#L1405

tho, it is the workspace described here: Microsoft/TypeScript#7444

**Comment by bpasero** [comment]
@jrieken the progress is only fake until I know how many files to search. since file walking can take forever, and I still want to show something, there can be cases where the fake progress goes to 90% and only then a lot of more files are discovered.

There is really no good way of showing real progress without knowing the number of files to search in upfront (e.g. an index would help).

**Comment by jrieken** [comment]
I wonder if we should show the infinite progress as long as we don't know how many files there are?

**Comment by bpasero** [comment]
Yeah, that could work.

**Comment by bpasero** [comment]
Actually I notice that 2 files in this workspace are very large (> 6 MB) and essentially the search is really busy processing those 2 files in the end and the file based progress is correct. I pushed a change to adjust the progress based on the size of the file. Let me know how it goes.
