### ISSUE TITLE
Line wrapping breaks custom problem matchers

### ISSUE THREAD

**Issue by kendfrey** [Microsoft/vscode#45107]
### Issue Type
Bug

#### Steps to reproduce:
Build task with custom problem matcher:
```json
{
	"label": "build",
	"type": "shell",
	"command": "make",
	"group": {
		"kind": "build",
		"isDefault": true
	},
	"problemMatcher": {
		"owner": "tslint",
		"fileLocation": "absolute",
		"pattern": {
			"regexp": "^(ERROR|WARNING): \\((.+?)\\) (.+?)\\[(\\d+),\\D*(\\d+)\\]: (.+)$",
			"severity": 1,
			"code": 2,
			"file": 3,
			"line": 4,
			"column": 5,
			"message": 6
		}
	}
}
```
Build output:
```
> Executing task: make <

tsc
tslint -t verbose -p tsconfig.json
ERROR: (typedef) C:/Users/Kendall/Source/ncre/src/ncre.ts[77, 20]: expected arrow-call-signature to have a typedef

make: *** [lint] Error 2
The terminal process terminated with exit code: 2

Terminal will be reused by tasks, press any key to close it.
```
The bug appears for certain widths of the terminal panel and how they wrap output (see screenshots).

#### Screenshots:
1:
![1](https://i.imgur.com/MiEvRs4.png)
2:
![2](https://i.imgur.com/IFz0tQq.png)
3:
![3](https://i.imgur.com/bMT0bdi.png)
(Note the extra space in 2 that is missing from 3, because 3 has the panel slightly wider.)

#### Result:
Wrapping as in screenshots 1 and 2 cause the error to appear in the Problems panel. Screenshot 3 results in an empty Problems panel (the problem matcher does not match that error).

#### Expected result:
All three cases should result in the error appearing in the Problems panel.

#### Workaround (temporary):
Resize the Terminal panel.

#### Notes:
This looks nearly identical to #32042. I don't know if it's a regression, a missed edge case, or just a similar problem somewhere else.

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 4000)|
|Memory (System)|15.95GB (9.16GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|50%|

</details>Extensions: none
Reproduces without extensions

**Comment by dbaeumer** [comment]
@Tyriar I am passing this on to you. Looks like when reconstructing the single line from a wrapped line the terminal drops a space (e.g. `[77, 20]` gets `[77,20]`). Please assign back if this is something you think the problem matcher needs to handle better.

**Comment by Tyriar** [comment]
This is related to the guessing where a line is wrapped on Windows thing we added to get it working in the first place. Since the terminal doesn't know which lines are wrapped on windows it guessed based on the last cell in the previous line *not* being a space `' '`.

This is handled here https://github.com/xtermjs/xterm.js/blob/6e546c0f30558125c8309f78b0c9e81a49bba81d/src/addons/winptyCompat/winptyCompat.ts#L20-L38

I'm open to improving this guessing, @dbaeumer what do you think about checking if the terminal is > x cols and checking the second last column too in that case? If so what should x be? For the repro above the terminal is very narrow so I'm a bit worried about lines falsely being flagged as wrapped if x is too low.

**Comment by dbaeumer** [comment]
In the example there how does the line 

```
ERROR: (typedef) C:/Users/Kendall/Source/ncre/src/ncre.ts[77,
```

look like for the terminal. Does it have a space at the end? If so why is the created single line missing the space? If not, why did the space get lost?

**Comment by kendfrey** [comment]
@dbaeumer When I copy and paste into a text editor, the space is lost.

I think that's just because the terminal pads every line with spaces, and removes them when you copy multiline text.

**Comment by Tyriar** [comment]
@dbaeumer what @kendfrey says is right; when copying lines the space on the right is trimmed because there is no difference between an empty cell and a space character. There is actually a bug related to this that even when the lines are marked as wrapped the trimming will still occur https://github.com/xtermjs/xterm.js/issues/1286, but this isn't what you're seeing because such a line would never be marked as wrapped on Windows currently.

Yes that line has a space on the end, you can tell from the first 2 screenshots that the form is `[77, 20]`

**Comment by dbaeumer** [comment]
@Tyriar sorry for not getting it. But if it has a space at the end and this is know for the terminal why is the space lost when the terminal reconstruct a single line from it. Couldn't we simply keep the space?

**Comment by Tyriar** [comment]
@dbaeumer the terminal doesn't know the difference between an "empty" cell and a cell with a space in it. Normally when copying lines we want the right trimmed so you don't end up with a line like this, all the spaces didn't actually come from the program:

```
"test                                                                            "
```

But we should definitely keep all whitespace when the line wraps which we're not doing at the moment.  This is driven by the `true` here:

https://github.com/Microsoft/vscode/blob/25474073e5e306680b6e6665d6ece79cad5765ee/src/vs/workbench/parts/terminal/electron-browser/terminalInstance.ts#L968-L972

We should only ever be trimming the last non-wrapped line. Created https://github.com/Microsoft/vscode/issues/45412 as this is a different bug.

**Comment by dbaeumer** [comment]
@Tyriar this makes sense tome. If I understand your comment correctly #45412 will address this issue. Right?

**Comment by Tyriar** [comment]
@dbaeumer #45412 will only fix mac/Linux right now to make sure the space is retained at the end of the line.

For Windows it's not marked as wrapped in the first place because there's a space at the end. We could check the second last cell as well and mark as wrapped in that case. Note that you also pinged me on the inverse of this recently https://github.com/Microsoft/vscode/issues/43664 which would exacerbate that situation if we started to consider the second last cell.

**Comment by dbaeumer** [comment]
@Tyriar ok. I wasn't aware that this only works on Mac/Linux. Just to make sure to understand it correctly: under Windows you don't know that the last cell has a space or was not written at all. That is why you can't 'un-wrap' the line correctly under Windows.

If this is true and given #43664 I only see one solution to fix this for now until we have better API under Windows as well. I would need to give you a hint if a line is a new line even if the last line runs to the end. Or we go back to having un-wrapped lines and I do some smartness on the matcher side since I know the regular expression that matches stuff. 

Do you have a feel for when the additional API might be available under Windows ?

**Comment by Tyriar** [comment]
@dbaeumer moving back to unwrapped lines would break multi-line links, so the current heuristic definitely adds value. Let me know the shape of API that would be useful as a hint on https://github.com/xtermjs/xterm.js/blob/bf210974301392f63f3f50b277071c9b51456bc4/src/addons/winptyCompat/winptyCompat.ts#L30-L38

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/32042 fixed the common case for this, when the last character in the column is a space however, that should be fixed when we fix the winpty issues so closing this in favor of https://github.com/Microsoft/vscode/issues/45693
