### ISSUE TITLE
[vb] add quote surround/auto-completion

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#4511]
Open a VB file.
- Select a word and press single quote: Expected to be surrounded by single quotes.
- Press quote: two single quotes expected

**Comment by jrieken** [comment]
@aeschli [vb] or phyton?

**Comment by aeschli** [comment]
vb

**Comment by alexandrudima** [comment]
To keep the number of issues in our inbox at a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: we look at the number of votes the issue has received and the number of duplicate issues filed. Thank you for your time and understanding.

If you disagree and feel that this issue is crucial: we're happy to listen and to reconsider.
