### ISSUE TITLE
can't find launch.json

### ISSUE THREAD

**Issue by jc5121** [Microsoft/vscode#45144]
### Issue Type
Bug

### Description

can't find the launch.json file

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz (4 x 3408)|
|Memory (System)|15.87GB (12.18GB free)|
|Process Argv|D:\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|33%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-csv|mec|0.2.0
python|ms-|2018.1.0
cpptools|ms-|0.15.0
python|tht|0.2.3

</details>
Reproduces only with extensions

**Comment by tsalinger** [comment]
You mention that this problem only occurs with extensions enabled. Please disable all extensions (CTRL+SHIFT+P --> 'Disable all installed extensions') and restart VS Code.
Then check if the problem still persists. If not, try to find which one causes the trouble by enabling one extension after the other.

If the problem is not caused by an extension, please provide us with a reproducible list of steps that cause this behavior.
