### ISSUE TITLE
[Update] Doesn't lets me know when it's done

### ISSUE THREAD

**Issue by DaFri-Nochiterov** [Microsoft/vscode#45162]
Issue Type: **Feature Request** / **Bug Report** (?)

**Steps to reproduce**:

1. Receive an update
2. Click "Install update", you'll see notification where it says "We'll let you know when it's done"
  ![Notification](https://i.imgur.com/FkYU9zy.png)
3. Observe nothing when preparing for an update<sup>1</sup> is complete

<sup>1</sup> - this is also an important point, the notification says it installs an update in the background, but actually, it only preparing for a complete update (?), on restart you still need to wait about 10 seconds seeing "Updating VSCode" dialog

**Expected behavior**: old notification gets replaced with new one which tells you that "you should restart VSCode to complete an update" containing buttons to restart right away or dismiss the notification
**Actual behavior**: nothing but the silent badge **`1`** on the bottom gear

**VS Code version**: *Code - Insiders 1.21.0-insider (a903bd38fbe9006c076d218ff69fe1ee0160f815, 2018-03-06T11:09:37.589Z)* - not tested, but probably will behave that way on this version
**OS version**: Windows_NT x64 10.0.17112

**Comment by mcarpenterjr** [comment]
It's nice that the update occurs in the background but I've had over 3 cases where I have had to remotely power down my system and it has just hung because the vs code update needed to restart vscode and it never happened, this causes complications on multiple levels. VScode never updates so the process has to be restarted and as a convoluted indirect consequence in this instance, the system was subjected to a hard power down (Powerloss).
As much as I dislike intrusive popups or invasive interactions I wouldn't oppose being nagged by a popup, or maybe display the changelog or summary in a taller than normal toast would be acceptable, for me at least, in this case.
