### ISSUE TITLE
jsconfig typeAcqusition not working

### ISSUE THREAD

**Issue by Bigmacbook** [Microsoft/vscode#45174]
### Issue Type
Bug

### Description

Autocomplete is not working with typeAcquisition in jsconfig.json isn't it suppose to grab a def file without having to request the package with npm. However it works fine if I install the npm package, but I don't want the npm package in my project. I just want to use the autocomplete definitions.

Downloading and using the autocomplete then deleting the package is not an option because the node_module folder contains packages I need and there are millions of folders in there.

It use to work without having to install the npm package.

jsconfig.json
`{
    "typeAcquisition": {
        "include": [
            "node",
            "electron"
        ]
    }
}`

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3330 CPU @ 3.00GHz (4 x 2994)|
|Memory (System)|7.87GB (1.48GB free)|
|Process Argv|D:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vetur|oct|0.11.7

</details>
Reproduces without extensions

**Comment by mjbvz** [comment]
Can you please try collecting the typings installer log so that we can investigate:

1. Set `"typescript.tsserver.log": "verbose"` in your user settings and restart vscode
2. Reproduce the problem
3. In VS Code, open a js file and run the `Open TS Server Log` command.
4. This should open a directory. Please share the`ti-xxx.log` file in the opened directory. This file contains the typings installation log

Thanks
