### ISSUE TITLE
Status bar spinner is white in light themes and hard to see

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#45191]
In light themes the status bar text changes from white to black, but progress spinners do not so they're hard to see:

![](https://user-images.githubusercontent.com/156888/37061437-5e8462c6-2148-11e8-93f3-6baf3b4a6d15.png)

**Comment by bpasero** [comment]
This icon is probably not themable yet. E.g. for the status bar feedback smiley we use `-webkit-mask` trick to allow to change the color of it ([refs](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/feedback/electron-browser/media/feedback.css#L140)).

**Comment by bpasero** [comment]
@jrieken fyi, the fix is to use a font for the icon (in this case our octicons). I found the sync icon fitting because we already use it for SCM sync:

![before](https://user-images.githubusercontent.com/900690/37581067-2f6ed9ea-2b47-11e8-9a8e-d57131ba0d83.gif)

Alternatively we could use this animation:

![before](https://user-images.githubusercontent.com/900690/37581092-455b22f4-2b47-11e8-87a0-22f1a26e5d90.gif)
