### ISSUE TITLE
Cannot go to implementation source of node module dependency from Windows

### ISSUE THREAD

**Issue by randomcatgamer** [Microsoft/vscode#45215]
- VSCode Version: 1.20.1 & 1.21.0 insider
- OS Version: Windows 10 Pro x64

Steps to Reproduce:

1. Load a NodeJs Project
2. Go a Source file having a npm dependency for example `require('kafka-node');...`
3. Go to Definition and notice it is a typed definition `// Type definitions for kafka-node 2.0...` and not the source that you want to look into
4. Go to Type Definition and notice it is the same thing
6. Go to your colleague's Mac running Visual Code 1.20.1 and notice that for the same project, same statement, same default configuration, for steps 3 and 4 it goes to the actual source `exports.HighLevelConsumer = require(‘./lib/highLevelConsumer’);...`. Why for his case there is not TypedDefinition at all seems also quite strange

Why is this happening? I tried cleaning the installations and trying again. I looked and looked for anyone else having this issue, but to no avail. I would really want to use Visual Code, but this is a very bothersome issue. Please help

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Sorry, this issue feel off my radar

Opening a `d.ts` is generally the expected behavior for node_modules. We use these `d.ts` to provide intellisense without having to try to parse the module's code itself. 

There are a few issues already tracking a better story for this:

- https://github.com/Microsoft/TypeScript/issues/14479 for ts source
- https://github.com/Microsoft/TypeScript/issues/6209

Closing as upstream
