### ISSUE TITLE
Webview: moving an editor group around does not move webview

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#45255]
Steps to Reproduce:

1. create a new webview with the new API
2. open a second editor group
3. move the editor group

=> the webview does not move while dragging because of its absolute positioning.

![before](https://user-images.githubusercontent.com/900690/37134593-8c0c9a22-2299-11e8-8f82-d2735f1265a0.gif)

**Comment by mjbvz** [comment]
Root cause: webviews use absolute positioning to maintain their content as they are switched between editor groups.

Best solution would be to move the webview back into the normal editor dom. This is blocked by #5257 

A workaround would be to track when the editor frame change position and align the webview with this as it moves

**Comment by bpasero** [comment]
Fyi this will not be an issue anymore once Grid lands.

**Comment by bpasero** [comment]
This no longer reproduces due to grid work landing where we do not support this kind of fluent reordering anymore.
