### ISSUE TITLE
Shell tasks force terminal window regardless of presentation setting

### ISSUE THREAD

**Issue by babakness** [Microsoft/vscode#45261]
- VSCode Version: 1.20.1
- OS Version: MacOs Sierra

Steps to Reproduce:

1. Run Shell Task
2. Have no way to prevent switching to output of shell task in terminal window

Details:

I would like to be able to run a shell task without interrupting the terminal window. At the moment there is a switch over to shared terminal tab; I'd like for there to be some way to keep the messages in the tab but  not switch over to the tab to see the output. 

```json
{
      "label": "tscc",
      "type": "shell",
      "command": "echo 'this is a sample'",
      "presentation": {
        "echo": false,
        "reveal": "never",
        "focus": false,
        "panel": "shared"
      }
    },
```

**Comment by Tyriar** [comment]
@babakness tasks in output is deprecated, I think you should be able to create task terminals in the background though?

**Comment by dbaeumer** [comment]
@Tyriar the problem is if there is a terminal instance already showing then the task terminal comes to front. I do call `this.terminalService.setActiveInstance(terminal);` but only `this.terminalService.showPanel` if the reveal kind !== `never`. Will `setActiveInstance` bring it to front. What is the consequence of me not calling it.

**Comment by Tyriar** [comment]
@dbaeumer not calling `setActiveInstance` should be fine. The task will still run in the background, but there will be no indication to the user that it was launched.
