### ISSUE TITLE
Terminating a preLaunchTask will not abort launching debugger

### ISSUE THREAD

**Issue by aleksijuvani** [Microsoft/vscode#45288]
I have a habit of starting builds by pressing the "start debugging" hotkey (F5). I have a `preLaunchTask` set up to build the project first. Sometimes I want to terminate this build task (I have this bound to Ctrl+Break) if I see a lot of build errors in the terminal.

However, after terminating the build task, VS Code will proceed to launch the debugger anyway. I would expect it to also abort launching the debugger, as if the build had failed.

Here's an excerpt from my `launch.json` file:

```json
{
    "name": "sample-fonts-shared (Release x86_64)",
    "request": "launch",
    "type": "cppdbg",
    "windows": {
        "type": "cppvsdbg",
        "program": "${workspaceFolder}/binaries/windows/x86_64/release/sample-fonts-shared.exe"
    },
    "args": [],
    "preLaunchTask": "Build sample-fonts-shared (Release x86_64)"
},
```

And my `tasks.json` file:

```json
{
    "label": "Build sample-fonts-shared (Release x86_64)",
    "type": "shell",
    "windows": {
        "command": "msbuild"
    },
    "args": [
        "samples/sample-fonts/sample-fonts-shared.vcxproj",
        "/property:GenerateFullPaths=true",
        "/property:Configuration=Release",
        "/property:Platform=x64",
        "/t:build"
    ],
    "group": {
        "kind": "build",
        "isDefault": true
    },
    "problemMatcher": "$msCompile"
},
```

- VSCode Version: 1.21.0
- OS Version: Windows 10 Version 1709 (Build 16299.192)

Steps to Reproduce:

1. Set up a `launch.json` configuration with a `preLaunchTask` set
2. Start debugging with this configuration selected
3. Terminate the `preLaunchTask` task before it completes via "Tasks: Terminate Task"
4. Debugger is launched anyway

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
I would expect that the `TaskService` returns a failure exit core or throws an error when users exits a task while it is being started up in the `taskService.run`
Due to that forwarding to @dbaeumer 

@aleksijuvani note that if you see this behavior after a task has been successfully ran it is expected behavior - since if you stop a task some time after starting debugging this should not affect the current debug session. Only if you stop the task while it is being started

**Comment by aleksijuvani** [comment]
To give a bit more info, if I terminate the build task before MSBuild has output any error messages, VS Code will proceed to launch the debugger on the last good build.

But if I terminate the build task *after* MSBuild has output any error messages, VS Code will give me an error dialog that the preLaunchTask exited with code 1.

I think it's using the exit code from the process even if the task is terminated by the user?

**Comment by aleksijuvani** [comment]
> @aleksijuvani note that if you see this behavior after a task has been successfully ran it is expected behavior - since if you stop a task some time after starting debugging this should not affect the current debug session. Only if you stop the task while it is being started

The task in question is being terminated before it has completed and the debug session is not yet running.

> I would expect that the `TaskService` returns a failure exit core or throws an error when users exits a task while it is being started up in the `taskService.run`

If this is implemented with exit codes, I think it would be important to not show the "preLaunchTask exited with code" error to the user in this case. If I manually terminate a task, I wouldn't expect it to show me an error dialog about it.

**Comment by dbaeumer** [comment]
@isidorn there is: the TaskServer fires an event if a task gets terminated using the terminate command and the promise returned from starting the task with resolve with an exit code. There is not more that I can do since the terminal only know about when the terminal process exits not whether it might be killed by a OS command.

Moving back. Please ping if you think there is more API I have to provide (although that will be difficult without getting more support from the terminal /  OS)

**Comment by isidorn** [comment]
@dbaeumer Thanks for clarifyication.
We accept PRs that add this feature.
Code pointer https://github.com/Microsoft/vscode/blob/4059210607e377ae6643eeb77c1e835340952cc3/src/vs/workbench/parts/debug/electron-browser/debugService.ts#L1001
