### ISSUE TITLE
editorActiveLineNumber.foreground incorrect when line # clicked in gutter

### ISSUE THREAD

**Issue by ssteinerx** [microsoft/vscode#45316]
Clicking line number in the gutter selects entire line (expected),     "editorActiveLineNumber.foreground" is applied to the next line's line number in the gutter (not expected).  Since typing replaces the selected line, I'd think that would be the "active line number", not the next one.

The screenshot below was taken just after clicking line `46` in the gutter.

![screen shot 2018-03-08 at 11 16 09 am](https://user-images.githubusercontent.com/43063/37162260-cc856bfa-22c2-11e8-8162-4ceb4063aeae.png)

VS Code version: Code - Insiders 1.22.0-insider (24d376c2735bb1eff8993aae6b3ba5eec967b6db, 2018-03-08T06:09:01.799Z)
OS version: Darwin x64 16.7.0

**Comment by kieferrm** [comment]
Confirmed.

**Comment by rebornix** [comment]
Clicking on the gutter will select a line with line ending, which moves the cursor to the beginning of the next line. Our other contributions like commenting, move lines, etc take care of this case. @alexandrudima knows more about if this is the expected behavior (the second line being the active line)

**Comment by alexandrudima** [comment]
That is as designed. Clicking on a line in the gutter will select the entire line including the `\n`, thus setting the cursor on the next line:

![TO_UPLOAD](https://user-images.githubusercontent.com/5047891/66412744-68bdb300-e9f6-11e9-8189-57402a148540.gif)
