### ISSUE TITLE
Distinguish open and closed issue with colors

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#45333]
Issue Type: <b>Feature Request</b>

![image](https://user-images.githubusercontent.com/4033249/37169346-8d0e2828-22bc-11e8-83d1-1eeb619b088d.png)

Red and Green like GitHub's UI would be nice

![image](https://user-images.githubusercontent.com/4033249/37169388-a05d15ce-22bc-11e8-9051-a85fe9a3348c.png)

VS Code version: Code - Insiders 1.21.0-insider (a903bd38fbe9006c076d218ff69fe1ee0160f815, 2018-03-06T10:59:55.398Z)
OS version: Darwin x64 17.3.0

**Comment by RMacfarlane** [comment]
When I was originally adding this, I experimented with using the red and green of GH to color these. I decided against it because it really drew your focus to those badges, which were not the most important thing, and because there weren't good existing theme colors to use for this purpose.

Closing as as-designed
