### ISSUE TITLE
VSCode generates random _conflict files

### ISSUE THREAD

**Issue by userlip** [Microsoft/vscode#45354]
- VSCode Version: 1.21.0
- OS Version: Windows 10 Pro 1709 16299.248

Issue:
Sometimes when coding there appears a random file that is name `*originalfile*_conflict-time` so sometimes I edit the file and then VSCode just bumps me into this _conflict file and all the changes to the original file are gone and the changes only appear the conflict file.

My first guess is, that is git, but I removed/disabled all git components in VSCode but this keeps happening and its frustrating having to keep record of the same file multiple times because sometimes even the conflict file does "conflict" itself again so there are multiple conflict files and I cant track where I changed code.

No new extensions before or after this happened.

Picture here:

https://i.imgur.com/0QPB9Rv.jpg

**Comment by kieferrm** [comment]
I'm unaware of anything in the VS Code core that would generate conflict files. I'd suspect this is one of your extensions. Which ones do you have installed?  You can run `code --list-extensions` on the command line.

**Comment by userlip** [comment]
`alefragnani.project-manager
bogdan-sinitsa.theme-dark-monokai
formulahendry.auto-close-tag
HookyQR.beautify
HookyQR.minify
magicstack.MagicPython
ms-mssql.mssql
ms-python.python
ms-vscode.cpptools
redhat.java
Rubymaniac.vscode-paste-and-indent
vscjava.vscode-java-debug
vscjava.vscode-java-pack
vscjava.vscode-java-test
vscjava.vscode-maven`

Those are the extensions I have. Did not add anything recently though and this issue is quiet new.

**Comment by kieferrm** [comment]
@userlip Do you see the same problem when you restart from the command line with `code --disable-extensions`. If not, one of the extensions is causing the issue. There is no easy way to figure this out rather than bisecting. I.e. disable one after the other and see if it's still happening. When you find the extension, pls close this issue and file the issue against the extension.  BTW, extensions auto-update in the background, so you might have gotten new versions of your extensions without realizing it.

**Comment by userlip** [comment]
Problem found: Nextcloud was the reason those files were created, not Git nor VSCode nor any extension.

Thanks for all the help!
