### ISSUE TITLE
Support control flows in tasks

### ISSUE THREAD

**Issue by xster** [Microsoft/vscode#45353]
- VSCode Version: 1.21
- OS Version: macOS 10.13

It would be nice to be able to configure in tasks.json if [${file} is such, ${fileExtname}  is such, etc etc] change the "command" or "args" etc etc.

**Comment by dbaeumer** [comment]
I recommend to write a shell script and then let the task call the shell script. Otherwise we need to invent a programming language on top of JSON which is very unattractive. (people will then ask for loops, ....)

I close the issue since I don't see us working on this. If I misunderstood please ping.

**Comment by xster** [comment]
Ya totally makes sense. Thanks!
