### ISSUE TITLE
Auto Collapse Folder Tree when closing files

### ISSUE THREAD

**Issue by jpagarcia** [Microsoft/vscode#45362]
VSCode's feature on opening the file's tree on the sidebar is great, also showing it when the file is active on the editor. I was wondering if it's possible to collapse the file's tree when the file is closed?

**Comment by jpagarcia** [comment]
Same issue -> Ability to keep only the current directory expanded in the Explorer (#39025)

**Comment by jpagarcia** [comment]
The link provided in the previous issue does not provide that much help. extension is not available in the marketplace

**Comment by JeanMertz** [comment]
> The link provided in the previous issue does not provide that much help. extension is not available in the marketplace

There's a [`.vsix` file in the linked repo](https://github.com/hoovercj/vscode-api-playground/blob/master/AutoCollapseExplorer/vsix/auto-collapse-explorer-0.0.2.vsix), that you can install manually:

```
$ code --install-extension ~/Downloads/auto-collapse-explorer-0.0.2.vsix 
Extension 'auto-collapse-explorer-0.0.2.vsix' was successfully installed!
```

Then, after reloading/restarting vscode, it works as expected. The only downside I've seen so far is that it has a bit of a jarring/flickering effect when switching between files in different folders, and you can't exclude specific folders from auto-collapsing.

I might take a stab at adding that in the future, but for now this will do.

**Comment by fjcaetano** [comment]
The problem with the given extension is that it collapses all folders to then reopen the active file and this causes the Explorer tree to blink. 

I was trying to make a proper extension that would handle this correctly, but there's no access to the Explorer tree in the API. I also tried fiddling with VS Code's source but I couldn't find any reliable way of finding a tree model (`Tree`, `TreeView`, `TreeModel`, etc) based on a folder's path - probably due to lack of knowledge of the source code.

If anyone is willing to help, I'd be more than appreciative.

**Comment by rohanrajpal** [comment]
Would love to have this feature, will be very useful in a monorepo setup.

**Comment by JCcastagne** [comment]
If anybody tried searching for an extension and couldn't find a solution, **here's the extension that worked for me**: 

[https://marketplace.visualstudio.com/items?itemName=lukegeneva.auto-collapse-explorer](https://marketplace.visualstudio.com/items?itemName=lukegeneva.auto-collapse-explorer)
