### ISSUE TITLE
No hotkey is available for navigating the call stack

### ISSUE THREAD

**Issue by paul-go** [Microsoft/vscode#4537]
The latest update boasts "All debug actions are keyboard accessible", but it seems there's still no keybinding endpoint for navigating up and down the call stack.

**Comment by isidorn** [comment]
What is meant by that statement is that all debug actions can be accessed by the keyboard, not that all have a keybinding associated with them. Right now you can use tab to move focus around, evantually jumping into the call stack pane and using the keyboard up and down to navigate the call stack.

Due to this, it is not an issue with accessibility but you just want a global action to navigate up and down the call stack. If I understood properly?

**Comment by paul-go** [comment]
Yeah, I guess that's more accurate.

**Comment by isidorn** [comment]
There is debug: focus call stack in latest vscode
