### ISSUE TITLE
Arrow keys when changing a file name, screw up my explorer pane

### ISSUE THREAD

**Issue by guidojo** [Microsoft/vscode#45446]
- VSCode Version: latest and all before it
- OS Version: MacOSX latest

Steps to Reproduce:
1. Go to file explorer
2. Press F2 after selecting a file
3. Use arrow keys to navigate within the name and nothing good happens

Does this issue occur when all extensions are disabled?: Yes

https://imgur.com/12rBIct

**Comment by guidojo** [comment]
Sorry I pressed enter by accident

**Comment by bpasero** [comment]
@guidojo I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.
