### ISSUE TITLE
AlternativeKeyEmitter starts listening on key presses too late

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#45467]
Steps to Reproduce:

1. open a workspace with a single empty folder
2. as the very first action Shift+right-click on the empty folder

=> the Delete action shows up normally

When you then select the folder and try again it works nicely.

**Comment by isidorn** [comment]
I can not reproduce this with latest vscode insiders both on os x and on windows. Both when doing shift + click and alt + click.
Do you still see this?

**Comment by bpasero** [comment]
@isidorn yes reproduces, in the video I started Code-Insiders freshly. The folder is collapsed and empty:

![flicker_chrome58](https://user-images.githubusercontent.com/900690/37408223-e8537f60-279b-11e8-9562-aca923a1395c.gif)

**Comment by isidorn** [comment]
@bpasero the state of the folder should have no affect on this. Can you repro for any folder?
Can you please just put some console log or breakpoint [here](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/actions/browser/menuItemActionItem.ts#L34) just so we check if the keydown event is passed
Can you also repro on mac?

I can also just come to your machine if you prefer that.

**Comment by bpasero** [comment]
@isidorn your suspicion seems right, only the second time I get something printed so it looks like that event handler is not triggered.

**Comment by isidorn** [comment]
@bpasero might it be an electron issue that we are missing a keybinding? How to proceed here?

**Comment by bpasero** [comment]
@isidorn I do not think so, it looks like the listener is not being installed until I opened the menu once, could that be the issue?

**Comment by isidorn** [comment]
@bpasero you are correct I only create the [`AlternativeKeyEmitter`](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/actions/browser/menuItemActionItem.ts#L25) once the actions are being filled for the first time. So there is your corner case.

Ideally the `AlternativeKeyEmitter` would be a workbench contribution, but I can not do that due to layering (he is in `platform`).

Another approach is for it to be an anonyimous class like before which has no contrustor arguments. I like that approach but the issue is that I still need the `contextMenuService` because I am missing keys when the context menu is shown. This might be solved with electron 2.0 and async menus and that might simpllify this issue.
For now pushing it to on-deck. Suggestions are welcome also.

**Comment by isidorn** [comment]
@bpasero weirdly we have electron 2.0 but the menus are still async and I do not get any event while a context menu is shown. Why is that? Am I misunderstanding the concept?

**Comment by bpasero** [comment]
@isidorn are you using custom or native menus? It could well be that even though the menus are async, we still do not get the event.

**Comment by isidorn** [comment]
@bpasero native menus on the mac
