### ISSUE TITLE
preLaunchTask in global launch object not working

### ISSUE THREAD

**Issue by affenwiesel** [microsoft/vscode#45488]
Issue Type: <b>Bug</b>

### Description

When starting a debug session using a launch configuration from the section in the user-settings, I get the error: "Cannot read property 'name' of undefined".
This error only occurs for launch configurations with the preLaunchTask property!

However if I copy-paste the content into a local launch.json everything works fine!

### Steps to reproduce

- install java extension

- copy the following to global settings.json:
```json
{
       "launch":
      {
        "version": "0.2.0",
        "configurations":
        [
          {
              "name": "Java",
              "type": "java",
              "request": "launch",
              "preLaunchTask": "build java",
              "stopOnEntry": true,
              "cwd": "${fileDirname}",
              "startupClass": "${fileBasenameNoExtension}",
              "classpath": [
                  ".",
                  "${fileDirname}"
              ]
          }
}
```

- copy the following to tasks.json:
```json
{
    "version": "2.0.0",
    "tasks": [        
        {
            "label": "build java",
            "command": "javac",
            "type": "shell",
            "group": "build",
            "isBackground": false,
            "args": [
                "-g",
                "${file}"
            ],
            "problemMatcher": []
        }
    ]
}
```

- try debugging some java-code

### System Info

VS Code version: Code - Insiders 1.22.0-insider (3817c899cae312e0e989da8bfbc61308cfbf45f1, 2018-03-09T05:15:56.454Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|Memory (System)|7.66GB (3.25GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.2.0
cpptools|ms-|0.15.0
java|red|0.20.0
vscode-java-debug|vsc|0.6.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.4.0
vscode-maven|vsc|0.5.2

</details>
Reproduces only with extensions

**Comment by isidorn** [comment]
Thanks, the issue here is that the `taskService` only supports getting tasks for workspace folders. However in the future we might support tasks in user and workspace settings same as we currently support debug launch configurations in those places.

So this feature request is for the taskService to also support getting a task even if no workspace folder is passed.

In the meantime until that is implemented it would be great to get a more precise error message 'No workspace folder passed' or something in that manner.

forwarding to @dbaeumer 

Also to note is that the configuraitons resolver service has a heuristic to resolves variables against a folder if that is the only folder even if the variables are not scoped. And tasks could do the same - if the folder is not passed check if there is only one folder, if yes try to get it from there.

![screen shot 2018-03-12 at 16 00 56](https://user-images.githubusercontent.com/1926584/37291339-b9a74658-260e-11e8-97bb-701061dee5f3.png)

**Comment by isidorn** [comment]
This should work now.
@affenwiesel can you please try this out in vscode insiders from Wednesday and let us know if the issue got fixed for you
