### ISSUE TITLE
File events can wrongly trigger model.updateModel() from operation within

### ISSUE THREAD

**Issue by JayAndCatchFire** [Microsoft/vscode#45538]
- VSCode Version: 1.21.0
- OS Version: Ubuntu 16.04 and MacOS High Sierra

I apologize in advance because I'm having trouble reproducing this bug.  I haven't been able to identify a reliable pattern of actions that trigger the bug, so this is a really poor bug report.  But I'd rather report a partial or sub-par ticket than none at all.

The issue is that upon trying to undo/redo file changes using <kbd>Ctrl</kbd>+<kbd>Z</kbd> and <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Z</kbd>, there will be odd entries in the undo/redo stack that cause the cursor to jump to the top of the file.  Those entries don't see to actually cause any changes in the file.

I tried searching through the reported bugs to see if anyone had already reported this, but I came up empty.  I may have just not used the proper search terms or labels.  I looked in both the open and closed issues.

I've noticed this behavior on both my home Linux machine and my work Mac Book Pro.  This seemed to have started happening with the latest 1.21.0 release, but I'm open to the possibility that this is related to a buggy extension.  If that's the case, the bug is either related to how an extension interacts with a change in VSCode 1.21.0, or the bug was introduced in the causal extension at around the same time as the 1.21.0 release.  See below for the list of extensions I currently have installed.  Because I can't reproduce this issue intentionally, I haven't tried it with extensions disabled.

**Steps to Reproduce:**
These steps won't necessarily reproduce the bug, but here's what I did last time I observed this happening.

1. Make changes to a JavaScript file.  (The particular changes I made the most recent instance were selecting a range of text and then pressing <kbd>"</kbd> to add quotations around the selection.)
2. Save the file.  (I used <kbd>Ctrl</kbd>+<kbd>S</kbd>.)
3. I clicked into the integrated terminal and ran some commands, but I don't think this is required to trigger the bug.
4. Change focus back into the same open file.
5. Try to undo the changes using <kbd>Ctrl</kbd>+<kbd>Z</kbd>.

At that point, the cursor jumps to line 0, character 0 at the top of the document.  Pressing <kbd>Ctrl</kbd>+<kbd>Z</kbd> another few times usually eventually gets to the actual changes I was intending to undo.  If I try redoing the actions with <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Z</kbd>, those weird jumps to the beginning of the document are still there in the undo/redo stack.

_Does this issue occur when all extensions are disabled?:_ Unknown

Here's my current list of plugins.  It's very close to identical on both machines where I encountered this bug.  (By the way, if there's a better way to record the extensions I have installed than the method used below, please let me know.)
```
~/.vscode/extensions$ ls
alefragnani.bookmarks-0.18.2
bungcip.better-toml-0.3.2
christian-kohler.npm-intellisense-1.3.0
codezombiech.gitignore-0.5.0
dbaeumer.vscode-eslint-1.4.7
donjayamanne.githistory-0.4.0
dzannotti.vscode-babel-coloring-0.0.4
eamodio.gitlens-8.1.0
EditorConfig.editorconfig-0.12.1
flowtype.flow-for-vscode-0.7.3
gerane.theme-flatlanddark-0.0.2
haaaad.ansible-0.2.7
kimkwanka.theme-atomic-dark-0.2.0
ms-vscode.cpptools-0.15.0
Orta.vscode-jest-2.6.4
PeterJausovec.vscode-docker-0.0.25
pflannery.vscode-versionlens-0.20.0
robinbentley.sass-indented-1.4.8
ryanluker.vscode-coverage-gutters-1.3.1
Tyriar.sort-lines-1.5.0
yzhang.markdown-all-in-one-1.1.0
```

If there's anything else I can try or any other info I can provide to help diagnose this bug more completely, please just ask!

**Comment by prasanjitsingh** [comment]
Facing the same issue (macOS High Sierra)

**Comment by diazweb** [comment]
Same problem here since version 1.21.0 (Mac High Sierra)

**Comment by JayAndCatchFire** [comment]
I see that vscodebot has removed the new release label since a new release occurred.  I just upgraded and I'll keep an eye out for this issue.  If I witness it occur again, I'll report it here.

**Comment by HumphreyHuang** [comment]
Same problem here, Version 1.21.1, High Sierra.

**Comment by nicklasafe** [comment]
Having the same problem. Also Version 1.21.1 (1.21.1) on High Sierra. No plugins needed to duplicate the problem.

**Comment by HumphreyHuang** [comment]
Has anyone fixed this issue by any chance? 
This is killing me...

**Comment by JayAndCatchFire** [comment]
Can anyone identify a series of steps that will reliably reproduce this behavior?

**Comment by nicklasafe** [comment]
@JayAndCatchFire Could be that you need to paste in some text: https://github.com/Microsoft/vscode/issues/46208

**Comment by JayAndCatchFire** [comment]
@nicklasafe I don't know for sure since this bug is hard to reliably reproduce, but I don't think it's related.  Pasting wasn't involved the last time I experienced this.

I just did a quick test by adding pasting to my workflow.  I couldn't reproduce _this_ bug and I couldn't reproduce #46208 _exactly_.  I'll discuss what _did_ happen on #46208.

**Comment by pjb0811** [comment]
In my case, a bug occurs when you save the text consecutively and then run undo. (cmd + s -> cmd + s -> cmd + z). So I save it once. I have not found a solution yet.

**Comment by ppyupp** [comment]
I have this problem too,  since version 1.21.0 (on Mac High Sierra)

**Comment by alexandrudima** [comment]
@bpasero It looks like cmd+s leads to a call to `IModelService.updateModel`. IMHO the file should not be  **read from disk** when it is saved via cmd+s.


I can reproduce somewhat often with the following steps:
1. Apply the following diff:
![image](https://user-images.githubusercontent.com/5047891/37974987-8fde437c-31de-11e8-921c-20fab044f039.png)

2. user settings: 
```json
{
    "files.trimTrailingWhitespace": true
}
```
3. open a file and type and undo, and type and undo, etc.
4. press cmd+s twice quickly
Observe the stack:
```
(1,1,1,1)!!! Error
    at TextModel.pushEditOperations (file:///Users/alex/src/vscode/out/vs/editor/common/model/textModel.js:819:47)
    at ModelServiceImpl.updateModel (file:///Users/alex/src/vscode/out/vs/editor/common/services/modelServiceImpl.js:302:19)
    at TextFileEditorModel.BaseTextEditorModel.updateTextEditorModel (file:///Users/alex/src/vscode/out/vs/workbench/common/editor/textEditorModel.js:116:31)
    at TextFileEditorModel.doUpdateTextModel (file:///Users/alex/src/vscode/out/vs/workbench/services/textfile/common/textFileEditorModel.js:340:22)
    at TextFileEditorModel.doLoadWithContent (file:///Users/alex/src/vscode/out/vs/workbench/services/textfile/common/textFileEditorModel.js:324:29)
    at TextFileEditorModel.loadWithContent (file:///Users/alex/src/vscode/out/vs/workbench/services/textfile/common/textFileEditorModel.js:278:25)
    at TextFileEditorModel.handleLoadSuccess (file:///Users/alex/src/vscode/out/vs/workbench/services/textfile/common/textFileEditorModel.js:256:25)
    at file:///Users/alex/src/vscode/out/vs/workbench/services/textfile/common/textFileEditorModel.js:251:57
    at Object.notifySuccess [as _notify] (file:///Users/alex/src/vscode/out/vs/base/common/winjs.base.js:1185:59)
    at Object.enter (file:///Users/alex/src/vscode/out/vs/base/common/winjs.base.js:867:30)
    at Promise_ctor._run (file:///Users/alex/src/vscode/out/vs/base/common/winjs.base.js:1083:29)
    at Promise_ctor._completed (file:///Users/alex/src/vscode/out/vs/base/common/winjs.base.js:1051:18)
    at IconvLiteDecoderStream.<anonymous> (file:///Users/alex/src/vscode/out/vs/editor/common/model/textModel.js:62:21)
    at emitNone (events.js:91:20)
    at IconvLiteDecoderStream.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```
![kapture 2018-03-27 at 16 50 43](https://user-images.githubusercontent.com/5047891/37975193-0cbd6666-31df-11e8-99db-8fe6260d2b54.gif)


Notice how the undo stack is getting (1,1,1,1) because the file is loaded from disk. I can look into improving the (1,1,1,1) cursor position via the issue #46208, but it is IMHO very worrying that saving the file to disk leads to us reading the file from disk ?

**Comment by bpasero** [comment]
Moving to April, I am not brave enough to make a change in endgame because it involves how we think a file has changed on disk when reading.

**Comment by bpasero** [comment]
I pushed a change that makes it very hard for me to reproduce compared to before. We had different code execution paths upon save depending on the file being dirty or not:
- dirty: we flush the contents to disk (typical save)
- non-dirty: we call `fs.utimes` to update the `mtime` of the file (non-typical save)

It looks like modifying the `mtime` of the file on disk is not clever because we basically store `Date.now()` as `mtime` while the operating system might have other strategies for setting the `mtime` when writing to a file. Often the `mtime` of the file on disk was different from what we expect in our model. 

The fix is to not tamper with the `mtime` of the file anymore and instead just run the same code that runs when saving the file normally. That means that saving a file again that is not dirty will flush the contents to disk in the same way as if the file was dirty. I think that is a fair compromise and OK for a text editor to do. 

The potential disadvantage of this approach is that external file watchers might read such a change as 2 file events (one for truncating the file and one for writing) but that behaviour is already there for saving normal dirty files. As such, VS Code is now always doing the same operation upon save independent if the file is dirty or not.
