### ISSUE TITLE
Add a `search.action.openResult` command

### ISSUE THREAD

**Issue by fabiospampinato** [Microsoft/vscode#45615]
There's already a `search.action.openResultToSide` command, but what if I want to open the result, but not to the side? For this a `search.action.openResult` command would be needed.

I want to create an extension for opening all search results with one shortcut, but without this command I can't do it properly.

Can you please add this?

**Comment by roblourens** [comment]
Makes sense, I would take a PR for it

**Comment by bpasero** [comment]
@fabiospampinato @roblourens careful here, please do not introduce new commands for what already exists. We have a generic `list.select` command that is used in all trees and lists to open something. If you want to be able to change this keybinding ONLY for search, then instead I suggest to introduce a new context key when the search view has focus so that you can specify another keybinding that is only working in that case.

**Comment by fabiospampinato** [comment]
@bpasero that works well enough for me, I'm closing this then.
