### ISSUE TITLE
Keyboard shortcuts stop working at random

### ISSUE THREAD

**Issue by d31uz10n** [Microsoft/vscode#45655]
Hey guys.. I noticed that TAB stops working at random.. Few other shortcuts stop working too..

The most strange thing is that when I click Check for Updates button they start to work again..

I'm using newest Mac OS version.

**Comment by tsalinger** [comment]
I assume you are using version 1.21 of VS Code?
Does this problem also occur when you disable all extensions?
Please provide steps so that we can reproduce this problem.

**Comment by Tresky** [comment]
Chiming in here to say that this happens to me and my coworkers as well. There really are no steps to reproduce because it happens intermittently, as far as I can tell. I'll just be working and the keyboard shortcuts for Copy/Paste/Save (maybe others) will stop working.

Restarting VSCode fixes the issue, but only temporarily.

*I'll try running VSCode without extensions for a while and see if it persists.*
