### ISSUE TITLE
Not receiving configurationDoneRequest when no breakpoints are set

### ISSUE THREAD

**Issue by rkeithhill** [Microsoft/vscode#4567]
- VSCode Version: 0.10.12-alpha 3/22 build
- OS Version: Windows 10 1511

Steps to Reproduce:

1. Install Powershell extension and restart
2. Open folder Examples under the Powershell extension install dir
3. Select the DebugTest.ps1 file
4. Press F5 to run, now try to pause the program.  Note that there is no output and pause doesn't work.
5. Now set a line breakpoint and press F5.  Now there is output and pause works.

Our log file shows that when a breakpoint is not set, we do not get the configurationDoneRequest message.  We are counting on getting that message whether there are breakpoints or not.  BTW this is a regression from the currently shipping version of VSCode. 

The debug protocol docs state this:
```
/** ConfigurationDone request; value of command field is "configurationDone".
    The client of the debug protocol must send this request at the end of the sequence of configuration requests (which was started by the InitializedEvent)
*/
```
Am I misreading this?  I believe it implies the configurationDoneRequest message gets sent even if there are no "configuration requests" to send.  But I'm not sure. 

RE https://github.com/PowerShell/PowerShellEditorServices/issues/196

**Comment by isidorn** [comment]
Yes, configurationDone should always be sent. I will investigate

**Comment by isidorn** [comment]
@rkeithhill I have looked into this and the issue is that the powershell adapter sends the 'initialized' event before vscode sent the 'initialize' call.
[Here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/common/debugProtocol.d.ts#L54) we specify that the adapter can send the 'initialized' event at any time. However that does not seem to be the right approach since it can happen that VSCode has not yet recieved the 'capabilites' call, and is not aware if debug adapter supports `configurationDone` request. That is happening in this case, the 'initialized' event comes before the capabilites and VSCode thinks powershell does not support `configurationDone`. If there are breakpoints due to timing all seems to work out fine, since the 'initialized' comes a bit later.

@weinand is investigating what is the right approach to tackle this issue

**Comment by rkeithhill** [comment]
Thanks for the update. cc @daviwil

**Comment by rkeithhill** [comment]
@isidorn I *think* we have this fixed.  The fix behaves correctly in the Insiders build but not the Alpha build.  Strangely, it appears the Insider build at 0.10.13 is a bit ahead of the Alpha build at 0.10.12.  So I'm hoping that the Insiders build has been "fixed" whereas the Alpha build hasn't.  If this remains the case, I would consider this bug fixed.  **My only ask is that the debug protocol docs be updated to clarify this message ordering issue.**

**Comment by weinand** [comment]
@isidorn your analysis makes sense but if I send the 'initializedEvent' **after** the 'InitializeRequest' has returned the Capabilities I see in Mock Debug that the 'LaunchRequest' arrives before the 'setBreakpointsRequest'. As a consequence no breakpoints are hit because the program has already terminated.

So here is the old sequence for Mock Debug:
```
initializeRequest
    send InitializedEvent
    return Capabilities
setBreakPointsRequest
launchRequest
configurationDoneRequest
```

This sequence looks already broken because the 'configurationDoneRequest' comes after the 'launchRequest'. But since 'setBreakPointsRequest' come before 'launchRequest', breakpoints are hit.

If I send the InitializedEvent after returning the Capabilities I see this sequence:
 ```
initializeRequest
    return Capabilities
    send InitializedEvent
launchRequest
setBreakPointsRequest
configurationDoneRequest
```

This sequence is even more broken: here the 'setBreakPointsRequest' comes **after** the 'launchRequest'.

I will fix the protocol doc and I will create a new issue for the ordering problem.

**Comment by rkeithhill** [comment]
@weinand Hehe, that is why we have code in the PowerShell extension to capture "launch info" from the `launchRequest` message and not actually launch until we've received both messages (launchRequest and configurationDoneRequest) regardless of the order they come in.  That said, this is not an ideal situation.

**Comment by isidorn** [comment]
@weinand is there something I could do on the vscode side right now, or should I wait for #4902 first

**Comment by weinand** [comment]
@isidorn Is there anything that you had planned to do here? My assumption is that fixing the doc is all that we can do here. Or is there a real bug on your side?

**Comment by isidorn** [comment]
@weinand no, I do not think there is a bug on my side.

@rkeithhill alpha is ahead of insiders always, we just do not update the version number on alpha regulerly it seems. It sounds strange that your fix works for insiders, and not for alpha as there have been no big changes on alpha that would affect this.
We will release a new insider update tonight so maybe you can try it out then. If not then please let me know and I can investigate - if I can get you updated version of powershell with the fix.

**Comment by rkeithhill** [comment]
@isidorn The two channels (latest builds 0.10.14-insider 2016-04-04 and 0.10.12-alpha 2016-04-05) still behave differently for me when I return the initialized event immediately after the initializeRequest response.  

Everything appears to work except that if I pause the script and resume it, it finishes but then I get a popup `Error cancelled` window in VSCode.  I also note that we do not get the disconnect message from VSCode alpha (where I see this error).  Details on this are here https://github.com/Powershell/PowershellEditorServices/issues/196

**Comment by weinand** [comment]
I've created https://github.com/Microsoft/vscode/issues/4861 for the 'Error cancelled' message.

**Comment by isidorn** [comment]
As far as I understand there is no real bug on the vscode side, @weinand just plans to update the docs.

Let me know if I am mistaken and I will reopen

**Comment by rkeithhill** [comment]
Correct.  We are getting the configurationDone message when there are no breakpoints set.  I think this started working when I changed the order of the initialized event to be sent after the initialize request response.

**Comment by weinand** [comment]
@isidorn I've updated the doc already but there is still the ordering issue from above (please read my first comment): https://github.com/Microsoft/vscode/issues/4902
