### ISSUE TITLE
Emmet: Wrap with abbreviation doesnt work when abbr contains {}

### ISSUE THREAD

**Issue by ramya-rao-a** [microsoft/vscode#45724]
- VSCode Version: 1.21
- OS Version: Any

Steps to Reproduce:

Use `ul>li{hello}` to wrap some text using the `Emmet: Wrap with Abbreviation` command

Expected:
```
<ul>
    	<li>
    		helloHello world
    	</li>
</ul>
```

Actual:
```
<ul>
    	<li>
    		Hello world
    	</li>
</ul>
```

This gets worse during live preview that's available in the Insiders. 
By the time `{he` is typed, the text is wrapped inside `<he>Hello world</he>`

Also try `ul>li{hello}+li.bye`

**Comment by ramya-rao-a** [comment]
Upstream issue: https://github.com/emmetio/expand-abbreviation/issues/20

**Comment by vedranjaic** [comment]
Also, abbreviation cannot be expanded with TAB if it contains {} or [], only with enter

**Comment by ramya-rao-a** [comment]
@vedranjaic Please provide an example

**Comment by vedranjaic** [comment]
Ahh sorry, it is actually a problem with the way or the order of typing, for example:
I would usually move my cursor throughout the abbreviation to edit something
And then putting the cursor back at the end of the line (either by pressing "Home" or "Cmd+ArrowRight" or clicking the mouse at the end)
And then pressing Tab to expand the abbreviation, but this way I get the usual "Tab" space instead of the expanding.

I have to delete what ever the last character is and re-type it... Because this way you jump-start the Emmet recommendation tooltip and the ability to expand the abbreviation either by "Tab" or "Enter"

**Comment by ramya-rao-a** [comment]
@vedranjaic If you want emmet expansion to be triggered on tab in the absence of the suggestion widget, see https://code.visualstudio.com/docs/editor/emmet#_using-tab-for-emmet-expansions

**Comment by vedranjaic** [comment]
@ramya-rao-a working, thanks!

**Comment by rzhao271** [comment]
\closedWith dc5a3da
