### ISSUE TITLE
In case a repository doesn't have origin remote, display sync status for all remotes

### ISSUE THREAD

**Issue by TomasHubelbauer** [Microsoft/vscode#45758]
I am trying to figure out what would be the best way to deal with a situation that I have. I've opted to change the Git remotes on my project to include a `github` one and ` gitlab` one instead of just `origin` so that I could sync with GitHub or GitLab explicitly and keep my project in both services.

This is perhaps unusual, but I believe the behavior of VS Code in this case could be improved to serve this niche use-case. Currently the sync button always shows the "Publish" icon without the behind/ahead arrow indicators. VS Code won't believe my project has been published until it has an `origin` remote it could consult (it seems).

I believe a better UX/DX would be to, in case of a missing `origin` remote, duplicate the sync button for all configured remotes (so that I would get a button for both GitHub and GitLab and could choose to click either one depending on where from and to I want to sync).

I don't think it should be the default for all repositories, the current behavior where if `origin` exists, it considers that the authoritative remote, is perfectly reasonable and that's how it should be. It only breaks down for projects which don't choose to have an `origin` remote and I believe people make that choice for pretty much the only reason - to be able to push and pull from multiple remotes without calling any one of them the main one. In that case providing multiple buttons seems to make sense to me.

I should also mention that there is the `Pull from…` and `Push to…` functionality built in already which makes managing multiple remotes possible, so this is by no means a blocker or anything. My beef is only with the sync button.

I'd like to offer to write a PR for this feature, should it be deemed to be a good potential addition to VS Code.

**Comment by TomasHubelbauer** [comment]
@joaomoreno I believe you are the right person to triage this.

**Comment by joaomoreno** [comment]
Thanks for the ping and the report!

VS Code doesn't do anything smart here. The sync action is directly related to Git's [upstream](https://stackoverflow.com/a/37770744/261019) feature. In Git, a branch can have a configured upstream remote branch, or none. When configured, sync action will appear; otherwise, the publish action goes instead. It seems that your `master` branch now has none, so you always see the publish action.

It seems you want to have two separate logical upstreams for your branch, which is definitely an odd case. I suggest you create aliases in your local git configuration which let you synchronise between those two remote branches. You can then have shortcuts in Code to run those aliases via Tasks, or even via a status bar contribution if you write an extension to do so.

I don't think it's such a common use case as to put it into VS Code core.
