### ISSUE TITLE
Source control does not update status automatically

### ISSUE THREAD

**Issue by Lev09** [Microsoft/vscode#45768]
Issue Type: <b>Bug</b>

Git integration does not update status automatically.  When I change files 'source control '  does not react to any file changes, it does not show that there are changed files. 
But if I click on 'refresh' icon it loads the changes correctly.

I know there is another similar issue when files are changed not with VS Code.
This is not that case. Files were changed using VS Code. 

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T11:01:43.521Z)
OS version: Linux x64 4.8.0-34-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4160 CPU @ 3.60GHz (4 x 3600)|
|Load (avg)|0, 0, 0|
|Memory (System)|11.61GB (1.30GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|0.8.8
laravel-goto-view|cod|1.2.0
vscode-eslint|dba|1.4.7
gitlens|eam|8.1.1
vetur|oct|0.11.7
laravel-blade|one|1.17.0
laravel-5-snippets|sac|2.0.1

</details>
Reproduces without extensions

**Comment by joaomoreno** [comment]
Does the file explorer react to file changes?

**Comment by Lev09** [comment]
Yes.

**Comment by maxgardner** [comment]
I've been experiencing the same issue since the 1.21.0 update. After I commit changes, the files still show in the staged area and the little badge over the source control icon in the nav also still displays, even after hitting the manual refresh. I've been having to quit the program and re-open to get it to update. File changes show correctly in the file tree.

One thing I haven't really considered/explored—I still perform most Git operations through the command line. I use the Source Control mainly for reference or to more easily break apart a lot of file changes to smaller commits after I've gotten too deep. I don't know if that may be causing a disconnect/delay in the update process. But I've usually waited a few minutes and still experienced the issue.

VSCode: 1.21.1
OS: Mac OS Sierra 10.13.3

**Comment by marknettle** [comment]
I cloned second copy of one of my repositories to my workstation (don't ask), and discovered similar behavior when using VSCode to look at files in the new copy. The first copy was working fine. It looks like VSCode wasn't checking the repo when saving files. Modified files were not showing as modified in the file explorer, even after forcing a refresh from under Source Control.

When I create a .code-workspace file for the second repository, that seemed to fix things. 

VSCode: 1.21.1
OS: Windows 10 Enterprise 1703

**Comment by joaomoreno** [comment]
cc @bpasero File event problems.

**Comment by joaomoreno** [comment]
Very likely related to #3025

**Comment by rodhoward** [comment]
Ever since I saw the above error about file handles I've been having similar issues. 

For me is more like the trigger for the git source control "changed files list" to update isn't the saving of the files as it use to be. Instead its when I click on them or refresh the source control actively. Even then it seems to be hooked up to wait until the build is completed before displaying the changes. Which in our large angular app is quite a while more than a few seconds.

so things are working its just sometimes I'm stuck waiting for the list to properly update and reflect my changes before I can commit.

**Comment by virendrachaudhary06** [comment]
I am also facing the same issue. File changes are not at all being identified in the source control even after clicking the refresh button. 
VS Code Version - 1.24.1

**Comment by LeoLozes** [comment]
In my current setup, since the june update, most of the time my files in the tree are not updated, they show no SCM change when commits are pending. The folders usually do.

Since the last update, after commiting, the files themselves in the code editor are not updated, with a file showing "changes" since last commit when there's nothing pending:

![image](https://user-images.githubusercontent.com/11133817/42870154-587bc444-8a77-11e8-98a5-d553ac202d1f.png)

**Comment by clintwood** [comment]
I have the same issue and in my case (monorepo using `lerna` and `yarn` workspaces) I have identified what is causing the issue.

It seems that when monorepo packages (node modules) within the repo are **symlinked** into `./node_modules/` through the `lerna bootstrap` process, `git status -z -u` and friends (as seen in the Git log Output panel) are no longer called on file changes.

I verified this by manually deleting the **symlinked** modules from `./node_modules/<symlinked-packages>` and (after restarting code) all file changes caused `git status -z -u` and friends to be called again and changes were reflected within the workspace tree.

See [lerna](https://github.com/lerna/lerna#readme) for monorepo details but I think this is not `lerna` or monorepo specific and is probably due to **symlinks** within `./node_modules` although I have not verified this outside of my monorepo case.

Code-Insiders version info:
```
Version: 1.26.0-insider
Commit: e8b1ee0b4d016bc38bbc1cf06d6d1868760d5fe8
Date: 2018-07-26T05:19:02.094Z
Electron: 2.0.5
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
```

**Comment by AmirNaghibi** [comment]
I just had the same issue. The source control tab suddenly became irresponsive and I have to add the files using the command line and push them to repo.
However, I deleted my local repo and cloned the remote again and it started working again.

**Comment by nealot** [comment]
I'm having the same problem as @LeoLozes but my source control view works fine. Should this be a new issue?

**Comment by joaomoreno** [comment]
Symlink support: #5970
Git repo root not the same as open folder: #41085

@Lev09 Is this still an issue for you?

**Comment by Lev09** [comment]
@joaomoreno after getting few updates that problem seems to be solved for me. 
Now I am using following version of VSCode

Version: 1.27.2
Commit: f46c4c469d6e6d8c46f268d1553c5dc4b475840f
Date: 2018-09-12T07:11:15.873Z
Electron: 2.0.7
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
