### ISSUE TITLE
Find highlight completely off

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#45770]
In todays insiders the find highlight is often completely wrong.
How to repro -> simply edit your file, use the find widget, do some more edits while the find highlight is in the file and sooner or later you will end up in this state:

If you need exact steps please let me know.
This feels like a clear regression thus assigning to march

![screen shot 2018-03-14 at 15 55 09](https://user-images.githubusercontent.com/1926584/37410139-3a41bd6a-27a0-11e8-9f95-bcd37e5d4938.png)

**Comment by isidorn** [comment]
fyi @alexandrudima @aeschli

**Comment by rebornix** [comment]
@isidorn I believe it's due to my chunk based find optimization, even though I thought we had a lot of test cases covering it. I'll dig into it.

**Comment by isidorn** [comment]
@rebornix thanks. Let me know if you need help reproducing, though I hit this every half hour after extensive usage of find widget and multi cursor.

**Comment by dlong500** [comment]
I think there is a major issue here.  See #45904, #45931, #45891, #45884 

Personally I'm running into all sorts of weird issues with find/replace, and what's worse is that I can't seem to easily reproduce the exact same problem, but I've had dozens of issues over the past day related to this.

**Comment by rebornix** [comment]
@dlong500 thanks for your feedback and doing a curation for me, I didn't catch up my notifications.

This is bad and this is my 1st work item from now on.

**Comment by rebornix** [comment]
@dlong500 it would be great if you can have a stable reproduce and then I can do some troubleshooting. Sorry for making it broken for you, but unluckily I tried really hard to break it but failed.

**Comment by rebornix** [comment]
Found the root cause of this issue, while searching in the chunk, I somehow didn't set a correct end position, which means we search on the same partial content multiple times. And due to the same reason, the wrong search result range exceeds the line/column boundaries, that's why we can some weird partial highlight at the end of some lines.

My commit fixes this particular issue, but apparently our test cases didn't have a good coverage. That's simply because our test file is 5 lines, which usually will not run into this issue. I'll add more test cases tomorrow but this doesn't block our next Insider release.

**Comment by isidorn** [comment]
@rebornix thanks for fixing this.

**Comment by dlong500** [comment]
@rebornix Thanks for the fix.  Sorry I couldn't be more help in reproducing the problem, but I had trouble trying to find a consistent test case.
