### ISSUE TITLE
Nodejs Debug params inside file itself instead of launch.json [Feature Request]

### ISSUE THREAD

**Issue by shahidmau** [Microsoft/vscode#45834]
It will make our life easy if you allow passing **debug params** from file itself instead of configuring in launch.json everytime.

e.g. in the comment section, we should have something like this.

> /**
> debug-params: --env prod --job process-record --thread 10 --iid b048dc30
> **/

So, while debugging current file, if we have something like above in the **file itself** then debugger should take params from the same file otherwise from launch.json

It is necessary because sometimes we have so many scripts with different param combinations and its overhead to put everything in launch.json

**Comment by isidorn** [comment]
Thanks for this feature request However hard to happens since the vscode frontend is not lagnuage aware. On top of that vscode frontent is not aware of waht file will be entry point of debug, only the debug adapter is interpreting the program attribute.
I can keep this open but in reality I know we will not implement this since it goes against our architecture. So I choose to close it, hope it makes sense. Thanks
Also putting everyting in a file instead of a alunchjson does not seem like a huge benefit to me
