### ISSUE TITLE
Notification expand/collapse arrow should be reversed

### ISSUE THREAD

**Issue by djoffe** [Microsoft/vscode#45850]
When the new notifications are too long, there is an arrow button to extend it. This arrow is upside down: When the notifications are anchored to the bottom of the window, I expect an arrow pointing **up** on the first image (the button will expand the notification) and pointing **down** on the second image.

![image](https://user-images.githubusercontent.com/2979478/37457472-0322cf0a-283a-11e8-94d9-c95a0f1562e9.png)
![image](https://user-images.githubusercontent.com/2979478/37457519-2299490e-283a-11e8-9666-c4510199fbbf.png)

The current way would be correct if notifications were anchored to the top of the window.

**Comment by tlowdermilk** [comment]
Ideally, you want to have the arrow pointing in the direction that the notification will expand/collapse to. In other words, when the notification is collapsed, the arrow is pointing up - because when the customer clicks on the arrow - we will be expanding the notification in the upward direction. Conversely, to collapse the notification, the user would click on an arrow pointing down, to indicate they are ready to "send the notification down" to collapse the message.
