### ISSUE TITLE
Dedupe suggestions

### ISSUE THREAD

**Issue by LazarusX** [microsoft/vscode#45864]
I am developing an extension to add auto completion to JSON files. I would like provide completion items ("running" and "stopped") when the users is editing the "status" property. However, these completion items will be duplicate with built-in JSON completion items. As the below screenshot shows, there is one extra "running" completion items which I assume is provided by the built-in JSON extension:
![image](https://user-images.githubusercontent.com/716650/37466380-886b611e-2898-11e8-8b00-b0d651b684fe.png)

Per the [document](https://code.visualstudio.com/docs/extensionAPI/vscode-api#_languages) of the `registerCompletionItemProvider`, even if I can match both `language` and `pattern`, the score is still 10. I guess the built-in JSON completion item provider can also get a 10 with only the `language` filter. As a result, I cannot prevent the built-in completion items from showing up.

Is it possible to allow match score higher than 10 for `DocumentSelector`, or is there any way I can prevent the built-in completion items from showing up?

**Comment by jrieken** [comment]
> Is it possible to allow match score higher than 10 for DocumentSelector, or is there any way I can prevent the built-in completion items from showing up?

No, that's against the philosophy of the system being open. There is an issue to deduce identical suggestions tho

**Comment by LazarusX** [comment]
I have found some GitHub issues discussing duplicate completion items, but they are all from the editor users' perspective. Is there anything an extension author can do to prevent duplicates without users changing any settings?

**Comment by jrieken** [comment]
>  Is there anything an extension author can do to prevent duplicates without users changing any settings?

No - this is something that needs to be implemented in the model logic

**Comment by ganes1410** [comment]
i will try to do this @jrieken . can you tell where to start ??

**Comment by jrieken** [comment]
This would be a good place to start: https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/suggest/suggest.ts#L110

The `allSuggestions`-array is the merge result after invoking all providers and I'd something like this. Add a function that computes the identity/hash of a suggestion (we need to agree what that actually is). Loop over them once and drop items for which a hash has been seen already

**Comment by ganes1410** [comment]
@jrieken . where i can see the `console.log` values.i running the debugger on chrome and not seeing anything.

**Comment by pradeepmurugesan** [comment]
Hi @ganes1410. 
You should be seeing the console logs without any trouble. Please see the attached image
![screen shot 2018-03-20 at 14 13 08](https://user-images.githubusercontent.com/528317/37656620-dca1ca8a-2c48-11e8-858f-888f749ee7d6.png)

If you are not seeing the logs, then may be the execution didn't reach there ?

Let me know if this helps.. 

Thanks,
Pradeep.

**Comment by ganes1410** [comment]
Hey @jrieken @pradeepmurugesan .
I think values for not logging because the code is not executing.
However i tried to reproduce the issue and not getting duplicate suggestions.
![screenshot from 2018-03-21 21-24-52](https://user-images.githubusercontent.com/16988745/37720941-61d89836-2d4e-11e8-8d76-a87ab33cd67e.png)

**Comment by LazarusX** [comment]
@ganes1410 Please install my extension (https://github.com/LazarusX/vscode-completionitem-demo) to reproduce this issue. The issue is that currently VS Code won't dedup completion items provided my extension and the built-in JSON extension.

**Comment by Marcholio** [comment]
Hi, is this still an issue with the current version?

**Comment by felixhao28** [comment]
@jrieken Hi, while I am bugged by this issue while developing a plugin aiming to reorder the completions provided by VSCode/other extensions, I noticed a similar first-party plugin [Microsoft intellicode](https://docs.microsoft.com/en-us/visualstudio/intellicode/intellicode-visual-studio-code) seems to be able to filter out/sort the completions provided by Python(ms-python.python) plugin.

Without intellicode, notice the duplicates of "placeholder" because of other plugins like Kite:

![image](https://user-images.githubusercontent.com/2417391/56273823-22b32100-6130-11e9-87ff-920c217c40d5.png)

With intellicode, the star-marked completion is provieded by intellicode:

![image](https://user-images.githubusercontent.com/2417391/56274130-c8669000-6130-11e9-9817-9c29686117d7.png)

Unfortunately intellicode is not open-sourced, so I wonder if there is any non-public API for their team to achieve this?

**Comment by vistatest** [comment]
Please, re-label this issue as a bug. It is mis-labeled as a suggestion and a feature request but this is a bug.
The fact that the issue includes a suggestion how to fix this bug does not change the fact that this is a bug report.
I hope that correctly labeling this issue will help with fixing it sooner.

**Comment by softwareCobbler** [comment]
Hi, I'd like to vote to be able to flag my own plugin's completion items as removable if they are duplicates by name. I get that it is probably not a good thing to allow plugin `A` to remove plugin `B`'s suggestions, but I don't see an issue with plugin `A` asking the client to drop `A`'s suggestions, based on some criteria (probably just match a string literal, with a boolean case-sensitivity option). The use case is, as with OP's, building a plugin intended for use alongside an existing one, and that can add useful completion items rather than noise.

**Comment by jablka** [comment]
hello,
I experienced duplicated suggestions when using these Python extensions in VSCode: `Python`, `Pylance`, `isort`.
But this seems to work for me: in Python extension settings: 
`Python: Language server`... choose: `Jedi`.

**Comment by acbuie** [comment]
I am also experiencing duplicate suggestions, as well as duplicate information on hover, while using `Python` and `Pylance`. Switching `Python: Language server` to `Jedi` removes the duplication, so this is likely a bug with `Pylance`.

**Comment by jablka** [comment]
Just a follow up, 

I see that there were many "duplicate suggestions" issues reported on github (here under `VSCode` repository, or under `Pylance` extension repository). 
Some claimed to be fixed, some still opened.

It seems that my issue pertains to this reported `Jupyter` issue https://github.com/microsoft/vscode-jupyter/issues/12029

Switching to `Jedi` was not satisfactory for me, because Jedi in VSCode is sadly set up to pre-fill the variables in functions https://github.com/davidhalter/jedi/issues/1905 .
🤷
