### ISSUE TITLE
Highlight matching parentheses/brackets not working in latex math mode

### ISSUE THREAD

**Issue by s-ilic** [Microsoft/vscode#45890]
Pretty much said it in the title : matching parentheses/brackets are not highlighted when editing a .tex document when inside one of Latex's math modes : $ $, \begin{equation}, etc....

Is there any setting that I missed ?

**Comment by aeschli** [comment]
VSCode has no built-in support for latex, but I verified that when opening a latex in `Plain Text` mode the bracket matching works.
I guess you are using an extension for latex , and likly that extension has changed regarding the bracket matching.

Can you file the issue against the latex extension that you are using? Also, I'd suggest adding a full sample code to illustrate the problem.

**Comment by s-ilic** [comment]
The Latex extension is "LaTeX-Workshop" by James Yu; it seems that this issue has already been mentioned several time on the extension dedicated github (see [here](https://github.com/James-Yu/LaTeX-Workshop/issues/292) and [here](https://github.com/James-Yu/LaTeX-Workshop/issues/99)) but to quote the author (see second link) it seems to him that :

> this is more a textmate/vscode upstream problem which disables brackets pairing in latex.math environments. Sorry it is not a problem that can be fixed from my side. I would recommend you submit an issue on vscode's repo.

Any comments ?

**Comment by aeschli** [comment]
Ok, I see. The problem is that the Latex grammar from 'LaTeX-Workshop'  uses the scope `string.other.math.block.environment.latex` inside the ` \begin` blocks.
Surrounding pairs are disabled inside strings.

It's a bit strange to use that scope for a whole block, so I'd suggest to file an issue against 'LaTeX-Workshop' to improve that.

The request to allow or configure bracket matching inside strings is https://github.com/Microsoft/vscode/issues/12388
