### ISSUE TITLE
Option to always open all detected submodules 

### ISSUE THREAD

**Issue by phosphoer** [Microsoft/vscode#45911]
Since updating to 1.21.0, submodules in our project are no longer automatically opened. They are correctly identified as submodules in the explorer view (the S icon), and VSCode pops up a notification on launch about it detecting 16 submodules that will not automatically be opened. 

Opening a file from the submodule does open the submodule, however we tend to open the files through a symlink that does not trigger the submodule to open (#45919). Is there a setting to disable this? I don't see anything other than `detectSubmodules`, which I have set to true. 

- VSCode Version: 1.21.1
- OS Version: Windows 10 Insiders

**Steps to Reproduce**: 
- Open a project with some large number of submodules (16 for us), and observe the warning message about them not being automatically opened. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
Submodules should automatically be detected. We introduced a limit of 10 submodules that should be automatically added to the list. Are you hitting this limit or none of the submodules are detected automatically?

**Comment by phosphoer** [comment]
All 16 submodules are 'detected', meaning Code notifies me about their existence and they are properly marked in the explorer tab. However, none of the submodules are displayed in the source control provider list until I open a file from the relevant one. I'd like an option to always display all submodules in the list, regardless of the count.

**Comment by joaomoreno** [comment]
Can you maybe try a different repository? When I open a repository with a single submodule, it gets detected and is displayed in the SCM view.

Do you have any other git settings set?

**Comment by Si1en7ium** [comment]
I am also experiencing this issue since 1.21

### Steps to "reproduce"

1. Create an empty repository
1. Add 10 submodules
1. Open the root repository in Code
1. Notice that all 10 submodules and the root repo are shown in source control providers (fig. 1)
1. Close Code, add 1 more submodule and reopen the root repo in Code
1. Notice that now non of the submodules are shown in source control providers (fig. 2)

Fig. 1: With 10 submodules or less, all submodules are shown by default
![image](https://user-images.githubusercontent.com/1560283/37655376-bb6135b8-2c4d-11e8-9cd0-a66f278dc3af.png)

Fig. 2: With 11 submodules or more, none of the submodules are shown and there is no way to modify this behavior
![image](https://user-images.githubusercontent.com/1560283/37655427-ee47e8aa-2c4d-11e8-90ab-c6351fdd51a8.png)

### Motivation

We are using submodules for our microservices development environment. It is useful to open the root repo to switch development configuration on the fly. Before 1.20 I would use source control provider view to update individual submodules, change branches for submodules and see if my development setup is up to date. This is pretty much impossible to do in 1.21, since submodules (> 10) are no longer shown there and there's no way to restore pre-1.21 functionality.

### Possible fix

Allowing users to restore pre-1.21 submodules behavior or to change the default submodule threshold from 10 to any number (with 0 being unlimited) would fix this issue for those of us who have a large number of submodules without impacting existing functionality for other users

**Comment by joaomoreno** [comment]
Oh yeah, now I see it in code... yup the current implementation doesn't make sense!
