### ISSUE TITLE
Controlling the Items that show up when right clicking on the Icon

### ISSUE THREAD

**Issue by ChuckJonas** [Microsoft/vscode#45916]
- VSCode Version:  1.21.1 
- OS Version: OSX 10.12.6 

Steps to Reproduce:
1. Right click on the VSCode Icon
2. See the top section of items

<img width="220" alt="fullscreen_3_15_18__2_04_pm" src="https://user-images.githubusercontent.com/5217568/37489836-7ec9c360-285e-11e8-8b83-504345b4fcc4.png">

How are these items set?  Is it possible to control what shows up here?  I've searched the settings and preference and can't find anything that would allow me to change these.  I can't even seem to find any pattern on WHY items show up here and it's driving me crazy!

**Comment by bpasero** [comment]
@ChuckJonas this list should reflect the entries of the `File > Open Recent` menu which is basically updated whenever you open a folder or a file (from externally). 

![image](https://user-images.githubusercontent.com/900690/37506345-b639a3d4-28e9-11e8-8c86-523cb07b4247.png)

**Comment by ChuckJonas** [comment]
Then this is a bug, because mine does not reflect this list in the slightest

**Comment by bpasero** [comment]
I have seen this as well sometimes, but unclear to me how this is possible (maybe the OS can overrule something here?). We are using [Electrons APIs ](https://github.com/electron/electron/blob/master/docs/api/app.md#appaddrecentdocumentpath-macos-windows) to set the items. I did not file a bug on their end so far because I have no reproducible case yet.
