### ISSUE TITLE
Auto import is broken for typescript

### ISSUE THREAD

**Issue by sfabriece** [Microsoft/vscode#45930]
- VSCode Version: 1.21.2
- OS Version: Windows 10

Steps to Reproduce:

1.add an angular or typescript project
2. Try to use auto import (ctrl - space), it does not work.
it does show the yellow light bulb which I have to click and it the uses absolute paths instead of relative ones.

Does this issue occur when all extensions are disabled?: Yes

**Comment by sfabriece** [comment]
possible duplicate of #45902

**Comment by mjbvz** [comment]
Please provide some example code or a small example project that demonstrates this problem. This issue sounds different from #45902

**Comment by mohag519** [comment]
I'm having the same problem with 1.21.1. I does auto import, but on a separate tab. So vscode opens a new tab for the same file, imports correctly there. Now I have 2 files which both have pending changes but none of them have all of the changes. So I need to close down the newly created tab -> import manually -> save. And finally close the tab and reopen it since intellisense breaks due to this for this file. 2 colleagues could reproduce this error with the same version.
