### ISSUE TITLE
Terminal cannot enter content

### ISSUE THREAD

**Issue by wincc0823** [Microsoft/vscode#45964]
Issue Type: <b>Bug</b>

终端无法输入内容

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz (4 x 3200)|
|Memory (System)|15.93GB (9.11GB free)|
|Process Argv|C:\dev\c\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eclipse-keybindings|alp|0.9.6
vscode-markdownlint|Dav|0.14.0
vscode-javac|geo|0.0.47
Go|luk|0.6.77
mssql|ms-|1.3.0
python|ms-|2018.2.1
atom-keybindings|ms-|3.0.4
cpptools|ms-|0.15.0
csharp|ms-|1.14.0
team|ms-|1.122.0
vscode-boot-java|Piv|0.1.4
java|red|0.21.0
vscode-java-debug|vsc|0.7.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.4.0
vscode-maven|vsc|0.6.0

</details>
Reproduces only with extensions

**Comment by tsalinger** [comment]
You mention that this problem only occurs with extensions enabled. Please disable all extensions (CTRL+SHIFT+P --> 'Disable all installed extensions') and restart VS Code.
Then check if the problem still persists. If not, try to find which one causes the trouble by enabling one extension after the other.

If the problem is not caused by an extension, please provide us with a reproducible list of steps that cause this behavior.

**Comment by pnloyd** [comment]
I'm also experiencing this issue. I will try @tsalinger suggestion and report the results.
