### ISSUE TITLE
js/ts: generate overridden methods 

### ISSUE THREAD

**Issue by ribrdb** [microsoft/vscode#46038]
I'd really like a code action "Override method..." that would give a list of methods from the ancestor classes/interfaces. I'd choose one (or more) then it generates stub overrides that have the same signature and a jsdoc /** @override */ comment. Maybe also a call to the super method.
It'd also be handy if there were a quick action to generate all the missing or abstract methods from super classes/interfaces.

**Comment by rendaw** [comment]
Or when someone starts typing an inherited method name into the class body.  Relevant: https://github.com/Microsoft/vscode/issues/21343

The current workflow is:
1. Start typing method
2. Method suggestion pops up with arguments and types
3. Press enter.  The method name is completed and flagged as an error since it looks like a property
4. Add parentheses + braces, the error disappears with no way to autocorrect to the parent signature
5. Go look up documentation and copy the signature by hand

**Comment by mjbvz** [comment]
Closing this in favor of https://github.com/microsoft/TypeScript/issues/25207 upstream.
