### ISSUE TITLE
the '￥' symbol error in string

### ISSUE THREAD

**Issue by Raleigh-xc** [Microsoft/vscode#46053]
Issue Type: <b>Bug</b>

for example:
return `￥${this.minPrice}元起送`;
return `还差￥${diff}元起送`;

the ‘￥’ symbol appear differently in editor

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 x 3192)|
|Memory (System)|15.95GB (11.34GB free)|
|Process Argv|D:\InstallFiles\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vetur|oct|0.11.7
view-in-browser|qin|0.0.5
vscode-icons|rob|7.21.0
language-stylus|sys|1.9.1

(1 theme extensions excluded)

</details>
Reproduces only with extensions

**Comment by tsalinger** [comment]
You mention that this problem only occurs with extensions enabled. Please disable all extensions (CTRL+SHIFT+P --> 'Disable all installed extensions') and restart VS Code.
Then check if the problem still persists. If not, try to find which one causes the trouble by enabling one extension after the other.

If the problem is not caused by an extension, please provide us with a reproducible list of steps that cause this behavior.
