### ISSUE TITLE
命令行窗口花屏 --> Command line window screen

### ISSUE THREAD

**Issue by jiang-xiche** [Microsoft/vscode#46071]
Issue Type: <b>Bug</b>

整体花屏 --> Overall flower screen

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:39:09.335Z)
OS version: Darwin x64 14.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU           W3520  @ 2.67GHz (8 x 2659)|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (9.82GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (38)</summary>

Extension|Author (truncated)|Version
---|---|---
stylus|Ala|0.0.4
bracket-pair-colorizer|Coe|1.0.20
EditorConfig|Edi|0.12.1
beautify|Hoo|1.3.0
vscode-html-scss|P-d|0.0.42
html-snippets|abu|0.2.1
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
jshint|dba|0.10.17
vscode-eslint|dba|1.4.7
githistory|don|0.4.0
jquerysnippets|don|0.0.1
gitlens|eam|8.1.1
vscode-html-css|ecm|0.2.0
tslint|eg2|1.0.28
vscode-npm-script|eg2|0.3.3
git-project-manager|fel|1.4.0
php-debug|fel|1.12.2
php-pack|fel|1.0.1
auto-rename-tag|for|0.0.15
vue-snippets|hol|0.1.5
rest-client|hum|0.17.0
phpcs|ika|1.0.5
docthis|joe|0.6.0
vscode-fileheader|mik|0.0.2
HTMLHint|mka|0.4.0
vscode-filesize|mkx|2.0.0
easy-less|mrc|1.4.5
vscode-autoprefixer|mrm|2.1.2
mssql|ms-|1.3.0
atom-keybindings|ms-|3.0.4
team|ms-|1.122.0
debugger-for-chrome|msj|4.2.1
vetur|oct|0.11.7
vuehelper|oys|0.1.0
view-in-browser|qin|0.0.5
vscode-icons|rob|7.21.0
language-stylus|sys|1.9.1

(3 theme extensions excluded)

</details>
Reproduces only with extensions

**Comment by tsalinger** [comment]
You mention that this problem only occurs with extensions enabled. Please disable all extensions (CTRL+SHIFT+P --> 'Disable all installed extensions') and restart VS Code.
Then check if the problem still persists. If not, try to find which one causes the trouble by enabling one extension after the other.

If the problem is not caused by an extension, please provide us with a reproducible list of steps that cause this behavior.
