### ISSUE TITLE
Let the user define its own embedded languages in the settings

### ISSUE THREAD

**Issue by stef-levesque** [Microsoft/vscode#46133]
Issue Type: <b>Feature Request</b>

It would be helpful to have the user be able to define its own embedded languages in the settings (user or workspace)

This would be especially useful with C++11 Raw String Delimiters
(see issue stef-levesque/vscode-shader#13)

I would expect something like that, in a similar manner to how the editor settings can be overridden per language

```
    "[cpp]":  {
        "embeddedLanguages": [{
            "hlsl": {
                "begin": "(?:^\\s*)R\"glsl\\(",
                "end": "\\)glsl\"",
            }
        }]
    },

    "[html]":  {
        "embeddedLanguages": [{
            "python": {
                "begin": "(?:^\\s*)<\\?python(?!.*\\?>)",
                "end": "\\?>(?:\\s*$\\n)?",
            }
        }]
    }
```

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.15063

**Comment by Tyriar** [comment]
@mjbvz you probably know who to send this one to

**Comment by mjbvz** [comment]
Extensions can already contributed injected grammars, see the styled-components extension for example: https://github.com/styled-components/vscode-styled-components

Doing this properly gets rather complicated (and it is not easily simplified) so it's probably a better fit for an extension rather than a user setting
