### ISSUE TITLE
Scroll wheel event in centered layout sashes should still scroll editor

### ISSUE THREAD

**Issue by dilijev** [Microsoft/vscode#46132]
Issue Type: <b>Feature Request</b>

1. Toggle centered layout
2. Use scroll wheel in sashes on the side
3. Observe no scrolling

Expected:

Still scrolls as this is the only relevant scroll bar in the view (especially in Zen mode)

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.17123

**Comment by isidorn** [comment]
If you mean the vertical scroll this is a fair feature request.
We accept PRs that fix this, however might not be trivial since the scrolling is embeded in the editor and the sashes migh not have access to that
Code pointer https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/parts/editor/editorGroupsControl.ts#L100
