### ISSUE TITLE
Insider: Search - Exclude settings and ignore files options not shown

### ISSUE THREAD

**Issue by greggilbert** [Microsoft/vscode#46134]
Issue Type: <b>Bug</b>

When going to the Search pane, the gear to expand the Exclude settings and Ignore files doesn't show anything. 

Quick video reproducing the issue: https://cl.ly/1m3Z1H2b2O3S

VS Code version: Code - Insiders 1.22.0-insider (3a70cdfd8f84136e858b3d39e5a709e637fc35e7, 2018-03-19T06:10:23.916Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.13GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_3867568|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.12.1
vsc-material-theme|Equ|1.5.1
vscode-docker|Pet|0.0.25
vscode-base64|ada|0.0.1
vscode-intelephense-client|bme|0.8.8
json-tools|eri|1.0.2
ruby|gro|0.0.6
Go|luk|0.6.77
vscode-duplicate|mrm|1.2.0
mssql|ms-|1.3.0
python|ms-|2018.2.1
azure-account|ms-|0.3.3
php-docblocker|nei|1.3.3
vetur|oct|0.11.7
indent-rainbow|ode|0.7.2
Ruby|reb|0.17.0
gitblame|wad|2.2.0

(1 theme extensions excluded)

</details>
Reproduces without extensions

**Comment by roblourens** [comment]
The gear enables whether files in your .gitignore are ignored, it doesn't show/hide anything. The ... button above the include/exclude box does that.

I recently switched this from dedicated include/exclude boxes to a single box that can take positive or negated (with !) patterns. Maybe that's causing the confusion.

**Comment by greggilbert** [comment]
@roblourens: Ah yeah, that's somewhat confusing. Having to put the includes and excludes in the same small text box is a bit user unfriendly, not to mention hard to read or parse. 

Also, the hover text on the gear says "Use Exclude Settings and Ignore Files", which I guess is different than what you said above?

**Comment by auygun** [comment]
@roblourens, it was really useful to have two separate boxes for "Use Exclude Settings" and "Use Ignore Files". They are different things and deserve two separate boxes.

**Comment by olfilato** [comment]
@auygun agreed. It would be nice if there was an option in user preferences to toggle between the current single-bar UI and the one that shows 2 separate bars for include/exclude.

**Comment by MullinsN** [comment]
Ok, so you have a lot going on there in a very small space.

You have the toggle box [Gear Image] for switching on the use of [Ignore Files and Exclude Settings]. Also you have started to use the ! within the [files to include/exclude], which is subtle if you don't know to look for it (The example doesn't work since it is hard to see). So what may seem obvious to you, may not seem the same for some of user base.

Anyway, tiny grumble in an otherwise great piece of software.

PS - The ignore though very useful, it would be great if there was a way of specifying how results appeared, based upon their directory. I don;t really want to exclude results, but it would be great to be able to say the results from certain directories appeared at the bottom of the results.
