### ISSUE TITLE
Alert sound occurs when using keyboard shortcut on Mac for "Move Editor into Next Group"

### ISSUE THREAD

**Issue by garyking** [Microsoft/vscode#46149]
On a Mac, open a file, and use the default keyboard shortcut for "Move Editor into Next Group", which is `Ctrl+Cmd+Right arrow`. This will run just fine, but also prompt the default Mac alert sound. The alert sound occurs if this shortcut is used in any app on a Mac, although I'm not sure why, perhaps because it's a shortcut that's supposed to do something, but a text document is not the right context.

Perhaps consider changing the default shortcut to something else? Or let's find the root cause of the alert sound?

**Comment by bpasero** [comment]
@garyking you seem to be the first one reporting this so I assume it is some configuration thing on your platform that causes it so I would stay away from changing the keybinding for every other user.

You can always change your keybindings to something else from the keybindings editor.

**Comment by garyking** [comment]
It occurs when using a new account on a Mac though.

**Comment by richardgirges** [comment]
I'm experiencing this issue as well on two different Macbooks running macOS High Sierra. One of those Macbooks is a completely fresh install of macOS. So I'm guessing this issue is actually pretty common. :(

However, changing the key binding for "Move Editor into Next Group" is definitely a workaround - albeit not a good one for Mac users that want to keep the default key bindings without hearing an alert sound every time they use this particular command.

**Comment by richardgirges** [comment]
Ahh, this is an issue in Electron: https://github.com/electron/electron/issues/2617 The specific hot keys in question are:

`ctrl-cmd-down`
`ctrl-cmd-left`
`ctrl-cmd-right`

Guess there's not much we can do about it from the VS Code side of things.
