### ISSUE TITLE
Intellisense does not autocomplete modules in 'node_modules' folders.

### ISSUE THREAD

**Issue by tomekc** [Microsoft/vscode#462]
While Intellisense do index **require**d**()** modules which are provided by relative path,
it is not the case for modules found in **node_modules** folders.

Please respect modules search path as described in [Node.js documentation](https://nodejs.org/api/modules.html#modules_loading_from_node_modules_folders)

**Comment by mattflix** [comment]
Please support Node-style module resolution for projects that use Javascript, Typescript, or a even a mixture.  Intellisense should "just work" for CommonJS (require) or ES6 module imports, following the full set of module resolution rules defined by Node.

Lack of proper support for Node-style module resolution makes VS Code rather useless for modern, modular, Node-based development and debugging.  Even the simplest of projects that imports a module by name, and that can run successfully under Node, VS Code can't understand how to provide Intellisense for.

I've spent many days browsing Github issues, Googling the web, and groking VS Code config files, and trying different things (to get Intelliense to work for that simplest of projects) and have come to the conclusion that, currently, it just doesn't work.

**Comment by iki** [comment]
+1 ... and the same for moudules imported from local project path, e.g. `src` in the following webpack config:
```
module: {
    loaders: assetsLoaders.concat([
      {test: /\.js$/, loaders: ['react-hot', 'babel'], include: [path.resolve('src')]},
      {test: /myyear1.html/, loader: 'url?limit=' + embedFileSize + '&mimetype=text/html'}
    ]),
    preLoaders: [
      {test: /\.js$/, loaders: ['eslint'], include: [path.resolve('src')]}
    ]
  },
```
Is there some setting of paths, from where the module imports will be resolved in VS code?

**Comment by Orodan** [comment]
+1
as long as it is not modules from the nodejs core, Intellisense is not able to give any useful informations by default. 
Furthermore I'm working on a project with specific modules developed for it and having to add a typing file for each of them is clearly not the solution. Too bad I enjoyed vscode a lot but this poor support of nodejs modules with Intellisense makes me want to use WebStorm again more and more.

**Comment by jedmao** [comment]
I'm having the same problem. Please support IntelliSense for Node module imports!

**Comment by mjbvz** [comment]
@tomekc I believe that we now support intellisense for modules listed in the `package.json` as well the built in node modules:

```json
{
  "dependencies": {
    "express": "^4.14.0",
    "mocha": "^3.1.2"
  }
}
```

![nov-21-2016 15-53-36](https://cloud.githubusercontent.com/assets/12821956/20505521/95036440-b002-11e6-8c15-409495c29fe5.gif)

The packages have to be listed in the `package.json` in order to be suggested.

**Comment by mattflix** [comment]
Umm, I do not believe this issue was about simply auto-completing module names (though that is a nice feature) but rather providing Intelliense for the _interfaces_ exported by any module found using the standard "Node module resolution algorithm", 

Btw, said modules are not "just" those listed in the top-level package.json or found in the top-level /node_modules folder, but rather any module reachable from the current module using Node module-resolution.  This could span many /node_module folders and package.json.

**Comment by mjbvz** [comment]
@mattflix @Orodan, you seem to be talking about a different problem, namely the lack of intellisense for installed packages themselves.

Js/TS intellisense is powered by typings `*.d.ts` files, and getting rich intellisense for a package currently requires users install external typing files if they are not already bundled in a package. With VSCode 1.7, [we introduced a new feature that automatically downloads these typings files](https://code.visualstudio.com/updates#_languages) so that rich IntelliSense for common packages is automatically provided, but had to disable this feature in 1.7.1 due to a few bugs.

You can try out automatic typings acquisition in the latest insiders builds, and we plan to enable it again in an upcoming, minor 1.7 update as well. Please give it a try and let us know if you run into any issue or have any suggestions.

Thanks.

**Comment by mgwhitfield** [comment]
There has to be a way to  generate a *.d.ts file from a set of files where the generator scans for JSDoc's in the fileset.  I'm unclear on this, please advise.  I could see an npm creating such a file and an extension using resolveCompletionItem.  Thoughts?

See https://code.visualstudio.com/docs/extensionAPI/vscode-api#_workspace

**Comment by jschmold** [comment]
I managed to get the intellisense working in both JS and TS using Typings.

typings init
typings search <the library you like>
typings install <the library you like>
