### ISSUE TITLE
Cursor is moved to top of page when undoing text added externally

### ISSUE THREAD

**Issue by garyking** [Microsoft/vscode#46208]
I'm editing a file in VSC and Sublime. I add text to the file in Sublime. I then Undo this text change in VSC. The cursor then jumps to the top of the file. It should instead stay put, or jump to the start or end of the text change, instead. This is particularly jarring when the file is very long, and performing an Undo operation takes focus away from what is being undone.

![undo](https://user-images.githubusercontent.com/343940/37677950-f2e119c2-2c52-11e8-82fe-2643f2610c57.gif)

**Comment by JayAndCatchFire** [comment]
@nicklasafe asked on #45538 if that issue (which I opened) was related to this one.  I don't know for sure, but I don't think it is.

When I tried reproducing _this_ bug in an open JavaScript file I happened to have at the moment, I couldn't reproduce this bug _exactly_, but I was able to produce other incorrect behavior.  Rather than the cursor simply jumping to the beginning of the file at the beginning of the undo stack (which would actually be the _correct_ behavior for my use case) it jumped to the beginning of the file _while also selecting everything from the previous location to the beginning of the file_.

Unfortunately, like #45538, I'm unable to reliably reproduce this.  Therefore I'm also unable to provide a slick gif of it happening like @garyking was able to do.
