### ISSUE TITLE
Allow to start hidden on macOS if configured as such

### ISSUE THREAD

**Issue by garyking** [microsoft/vscode#46221]
I've put VS Code in my "Login Items" on my Mac, so that it starts when I login on my Mac. I also checkmarked the "Hide" option. But when I start my Mac, my other apps like Chrome are hidden on startup, but VS Code is not.

![mac login items](https://user-images.githubusercontent.com/343940/37687877-b24e2d52-2c73-11e8-9a73-9195a14c4cf8.png)

**Comment by bpasero** [comment]
@garyking does it work with other Electron applications like Whatsapp for Desktop?

**Comment by garyking** [comment]
I tested with Insomnia. It doesn't start hidden too. So it seems to be an Electron problem. I figured it was likely to be the case.

**Comment by garyking** [comment]
Hello, so it seems like VS Code will need to implement Electron APIs to make this work for itself. [Relevant comment here](https://github.com/electron/electron/issues/12414#issuecomment-375667746).

**Comment by bpasero** [comment]
@garyking great findings, I was not aware of that API.

**Comment by bpasero** [comment]
@garyking I wonder what the expectation is to support this setting (also @weinand as macOS expert on this topic). I tested with Safari and Chrome and when I configure these applications to start hidden on login I can see that the applications opens without any windows opened (as expected). As soon as I click the dock icon, a window opens.

What is unclear to me is if clicking the dock icon should perform the same as clicking on the dock when all windows are closed. For VS Code this means to open an empty window. However if we did that, this would mean that we would never restore the last session that was active, you would always end up with an empty window (unless maybe you right clicked on the dock icon and picked a folder from the previous session).

And there is another challenge: If you quit with some files dirty ("hot exit") we always forcefully restore these windows upon next start so that the work is not lost in these dirty files. I am not sure how this feature could work together with starting VS Code hidden upon login. I think if you leave with dirty files we need to make those windows visible that contain dirty files, anything else would be quite complicated for us to implement I fear.

**Comment by garyking** [comment]
> I wonder if that could mean it would be OK for us to restore any windows from the previous session but simply not show the windows until the dock icon is clicked. This is a bit challenging though because a user could Alt+Tab into the application and start to use the application menu (e.g. File > New Window). In that case, I guess all other windows would need to become visible too?

Yes this is best. 

When VSC is in Login Items and Hidden, I would prefer if it restored all windows like a normal startup, and just hides them. Then if they Alt+Tab into VSC, then just show all the windows.

**Comment by bpasero** [comment]
I think Electrons APIs do not allow me to open a window without moving it to the foreground so it will  be hard to implement this properly.

I am open to help here if someone has ideas how to implement this best with Electron. Some API pointers how to create a [`BrowserWindow`](https://github.com/electron/electron/blob/master/docs/api/browser-window.md).
