### ISSUE TITLE
Simplified Chinese not translating exceptions text until after debugging

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#4626]
- VSCode Version: 0.10.12-alpha
- OS Version: Windows 10

Steps to Reproduce:

1. On a fresh install of VS Code, open and debug a project in English
2. Change the locale to zh-CN
3. Reopen and open debug

![zh-cntranslation](https://cloud.githubusercontent.com/assets/12900364/13999426/85ebe9e6-f0f9-11e5-93f5-02e9388ff32a.JPG)

4. Run debugger in this locale
5. It then updates the exceptions text correctly

![zh-cntranslationfixed](https://cloud.githubusercontent.com/assets/12900364/13999465/a88150b8-f0f9-11e5-8089-a9434634849f.JPG)

**Comment by vsccarl** [comment]
In addition, it will hold on to the previous language until you start debugging.
After changing locale to Russian:
![zh-cntorussiantranslation](https://cloud.githubusercontent.com/assets/12900364/14001523/9260b22e-f103-11e5-907a-b1f791c67969.JPG)
Then it is updated after running the debugger.

**Comment by isidorn** [comment]
As designed, this translations are coming from the debug adapter. Thus they are updated only once a debug session starts, since that is when the debug adapter is started.
VSCode has no knowledge of these strings, so we can only update them when we start the debug adapter - thus the session starts.

There is nothing we can do here

**Comment by weinand** [comment]
Since the translation will be correct after the next session start (and sessions are short lived anyway), we can live with that minor problem.
