### ISSUE TITLE
Cannot copy long strings from watch while debugging

### ISSUE THREAD

**Issue by amparks100** [Microsoft/vscode#46288]
Issue Type: <b>Bug</b>

When I have a long string value, when i select Copy Value, the value it gives me includes the "+214 more", not the actual full value of the string.

1. debug code that contains a long string value
2. In the watch or local variables section of the debugger right click on the string
3. click Copy Value
4. paste into a text editor

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T11:04:09.969Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|Memory (System)|7.84GB (0.80GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|8.1.1
Go|luk|0.6.77
PowerShell|ms-|1.6.0
proto|pet|0.0.2
vscode-proto3|zxh|0.1.3

</details>
Reproduces without extensions

**Comment by isidorn** [comment]
What language are you debugging?
If not node then please file this against the extension you are using since that data is coming from the extension. Just let the extension author know that for copy value we are using evaluate on the vscode side. 

https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/electronDebugActions.ts#L27
