### ISSUE TITLE
Make files to include/exclude configurable on whether to use 1 or 2 inputs

### ISSUE THREAD

**Issue by Crazy-P** [Microsoft/vscode#46315]
With issue https://github.com/Microsoft/vscode/issues/45702 and commit https://github.com/Microsoft/vscode/commit/7fdf1e3b50b57df7c0ab54cf4012ae1880aed01c the search function: `files to include and exclude` got merged together into 1 input.

Generally usage this is okay (maybe). However, I often use both input fields with a long list to exclude or include.

The new approach is a rather poor UI/ UX. (Some might consider it as a good UI/ UX)

But e.g.:
Search: `FunctionA`
Include/exclude: `!folderA/*, !folderB/*, folderC/*, !folderD/*, folderE/*, fileA.ext, !fileA.ext`

It quickly gets tough to deal with. It gets hard to know where are the included and excluded parts.

In the previous design this was separated into 2 fields. Hence much easier to control the search.

I see no issue with using another 30 px or so for an extra field. However, if the merging of these input fields are so desired, I do believe it will be nice with a config to either let it stay as a merged field or separated into 2 fields.

**Comment by roblourens** [comment]
Are you using search in the sidebar, or panel (via the `search.location` setting)?

**Comment by Crazy-P** [comment]
I am referring to the search sidebar (I guess?)

![image](https://user-images.githubusercontent.com/9751950/37785918-4f199aea-2e36-11e8-81c5-947446c4436a.png)

**Comment by roblourens** [comment]
Would it make sense to put those exclude patterns in your `search.exclude` workspace setting? Or are you constantly changing them for different searches?

**Comment by Crazy-P** [comment]
I already use `search.exclude` for folders/files I permanent want to exclude.
The one in search panel I use quite dynamically. Not static enough to be put into the workspace setting.

I was thinking of whether it is possible to add that arrow option like the `Search` input has to expand it to use search/replace. For include/exclude it could be expanding the field to use 2 input fields.

**Comment by roblourens** [comment]
Maybe. I would wait for more feedback before making a change here.

**Comment by Yalhu** [comment]
I want to include `search/user.js` and exclude `db/user.js` . Does it work when I set `todohighlight.exclude:["**/db/user.js"]` or `todohighlight.exclude:["./db/user.js"]`?

**Comment by dpsthree** [comment]
I have another use case in support of @Crazy-P 's suggestion

I often open a root folder containing many sub-projects beneath them. For example, client, server, tools, common, etc... I often want to perform searches within just one of these top level folders at a time. With the new UI I need to explicitly exclude each top level folder in order to search within the client folder.

The previous version of this UI made it much easier to work in this way. Having the option to choose between the two would be nice.

**Comment by roblourens** [comment]
> With the new UI I need to explicitly exclude each top level folder in order to search within the client folder.

There shouldn't be any real behavior difference between the old and new versions. If you want to include one folder, you can do that the same way that you used to. Can you explain some more?

**Comment by ssandler** [comment]
I preferred the old UI for this. I constantly changed my include/exclude files and having them separate was just a little easier to manage.

**Comment by nazarkryp** [comment]
I do not like new feature as well. It is really annoying to go through all input to check everything

**Comment by viktoriatelyatynska** [comment]
go back to two inputs please. New UX is awful

**Comment by scottsb** [comment]
Also prefer the old separate boxes. For me the big issue is that include and exclude rules can now be interspersed with each other, making it hard to quickly evaluate what's getting searched if there are multiple patterns.

I could move some of those entries to the `search.*` area, but I often want to add or remove them on the fly depending on what I'm looking for (e.g., excluding test files or not, including vendor files or not, etc.), so that's not a good solution.

**Comment by yoni-tock** [comment]
I also preferred the separation, basically just for the explicitness / clarity. I find it harder to mentally parse and look for the `!`s in the one field.

**Comment by MarcosEllys** [comment]
Go back to two input, New UX is awful

**Comment by fongandrew** [comment]
> Or are you constantly changing them for different searches?

FWIW, I personally switch these up quite a bit. To give some context, I work a lot in repos where I'm searching for `*.js` and `*.ts` files but excluding things like `*.test.js` and `*.d.ts`. Whether I want to exclude the latter is highly depend on context and not something I want to stick in a settings file.

**Comment by Crazy-P** [comment]
Another reason to keep them separated is to easily remove all exclusions/inclusions with just
* ctrl + a  -> ctrl + x //Removes filter
* Do a search
* ctrl + z or ctrl + v //Adds filter back

**Comment by ucirello** [comment]
The point is that separated fields for inclusion/exclusion provided the perfect middle-way between exclusions needed once (thus combining inclusions and exclusions ad-hoc is fine), and exclusions that you know you will never care about (like .git and friends).

Perhaps, the use case to understand what is lost is the interaction between your code and your vendor code. 

You know often you don't want to search for content in the `vendor/` directory - but vendor code is not perfect, and sometimes you do need to be able to search there. Often enough that it doesn't justify the long path of going to global or workspace configurations and remove the exclusion rule only to add it back a couple of minutes later.

**Comment by roblourens** [comment]
The previous two comments are the motivation behind the "Use Exclude Settings and Ignore Files" button - it provides an easy way to do a quick search in folders that are normally excluded. Does anyone use that?

**Comment by scottsb** [comment]
I never use that button because there are some files I do always want to ignore. Those are the ones that in my settings. The items in the dedicated exclude box are the ones that I may pull in and out--and not in a simple binary all-on or all-off way.

**Comment by Crazy-P** [comment]
> "Use Exclude Settings and Ignore Files" button

Do you perhaps mean this one?

![image](https://user-images.githubusercontent.com/9751950/38712574-36f726ba-3eff-11e8-98d5-411b202a38d0.png)


Then yes, I have tried that one. The button does nothing at all. ( Or I am just too silly to know how to use it)

![image](https://user-images.githubusercontent.com/9751950/38712584-504d0940-3eff-11e8-8d18-dedf6ca62665.png)


When removed the exclude filter:

![image](https://user-images.githubusercontent.com/9751950/38712611-6e400af6-3eff-11e8-9f70-89b1dd9b9cea.png)


Nonetheless. Even if the button worked, then it doesn't solve my main problems with the current merged input fields. Nor would I actually use that button as I am too used to have to remove the input field content and reinsert it due to 100s other editors not having this button feature. ( I might get accustomed to the button eventually)

**Comment by roblourens** [comment]
The button disables the patterns in your search.exclude/files.exclude settings, and turns off excluding files that a .gitignore file matches. Patterns in the text box will still be applied.

**Comment by Crazy-P** [comment]
Alright. That explains why I never felt anything when using that button.

But then what is ur connection/reference with ur comment here and that button?
>  The previous two comments are the motivation behind the "Use Exclude Settings and Ignore Files" button

**Comment by roblourens** [comment]
The idea is that if you have patterns that you want to often exclude, but sometimes quickly disable to search in those folders, you could keep those patterns in your `search.exclude` setting normally and use the button to toggle them off.

This doesn't solve every possible case but I think it helps a lot. The case of searching in the vendor directory sounds similar to my case of searching in node_modules, which is what I usually use it for.

**Comment by ucirello** [comment]
> This doesn't solve every possible case but I think it helps a lot. 

This seems a weird trade-off. Trading a feature that was simpler and did more to a more complex feature that only achieves part of the functionality of its counterpart.

**Comment by roblourens** [comment]
I'm hearing feedback in a few categories

- Reading/skimming the include/exclude patterns is less convenient, when they're in a single box
- Temporarily removing the excludes was more convenient when they were in a separate box
- General confusion/the perception that functionality has been lost (besides the above)


Some reasons it was originally changed

- Simpler to edit - keep your cursor in one box
- Keeping include/exclude patterns together in a single history list makes more sense, since they are usually associated
- Saves vertical space (especially in search panel layout)
- Matches other editors

**Comment by Crazy-P** [comment]
> * Simpler to edit - keep your cursor in one box
> * Keeping include/exclude patterns together in a single history list makes more sense, since they are usually associated

Very debatable and is a pure preference as both ways are rather logical.

> * Matches other editors

Please don't match the other editors. :(
Sure some other editors got some good design approaches,  however VS Code is epic because it is not totally like all the others and is so flexible when it comes to customizations - fitting one's own or a specific project's needs while being extremely light.

**Comment by G1itcher** [comment]
Have to agree with the zeitgeist on this one. One box doesn't feel like good UX; requires more typing to do the same thing, is slower to parse mentally, and feels like a needles combining of concerns. I don't think the reasons for changing it out weigh the reasons for leaving it as it was.

**Comment by roblourens** [comment]
I reverted back to two boxes... please try it in tomorrow's Insiders build.

**Comment by szyhf** [comment]
Hi, 

Using multi-line box with auto-height control, as both include box and exclude box (two box) is my dream solve.

That can make a balance of people has long pattern who want clear and  people has short pattern who want focus.

**Comment by roblourens** [comment]
Verifier: We are back to two boxes and persisted patterns/history should be transitioned correctly.

**Comment by DavidBabel** [comment]
This is huge decision !

Cause the one boxe brokes totally when it's used with "search in this folder"

![image](https://user-images.githubusercontent.com/5599375/39578284-07a3d42c-4ee4-11e8-98df-6932ef69ae00.png)


Since it erase everything in your include/exclude field.

**Comment by ADTC** [comment]
Uh, an option would be nice. Default to two box, but a simple setting could merge them to one box if I'd like.

**Comment by balta2ar** [comment]
@roblourens I don't like having two separate boxes because I have nearly all my excludes in .gitignore. So in my case that's just wasted precious vertical space that I could use to see more results. Could you please add a button to collapse these boxes into one and bring back the support of the negation search term `!`? I think that would satisfy all the users.

**Comment by DavidBabel** [comment]
Because your usage is very specific.

When you have a well designed large application, you pass your time to work in a specific folder and switch frequently.
Beiing able to automate all your researches without having to change the folder time to time is a big improvement.

Consider beginners too, the "!" notation is less intuitive.

**Comment by ADTC** [comment]
I don't get why there's a debate which is better. Why not just provide both, default to split version and leave it to the user to decide if they want to switch to combined version. It's just a matter of adding `combineSearchIncludeExclude: true` to the user preferences. That way, both camps are happy.

**Comment by guidobouman** [comment]
@G1itcher Hmmm... Great points. I think I've been disappointed that at one moment I got a synced feature between my two favorite editors (VS Code & Atom), and lost it in a next update.

Your last sentence is the strongest point. I have a hard time coming up with solid arguments that I can't also use the other way around. So this must be personal preference because of muscle memory. Which means I'll get used to this. If this is easier for new developers to get started, then fine by me.

**Comment by GammaGames** [comment]
If I remember correctly the change was included to use space more wisely with the horizontal search panel. I think having the include and exclude boxes move to one line in response to the panel width would be a nice middle ground, since the two boxes take up a lot of room and I prefer the panel view.

**Comment by alejosky** [comment]
> Consider beginners too, the "!" notation is less intuitive.

!true
