### ISSUE TITLE
Restart To Update should use the latest version and not the first downloaded version

### ISSUE THREAD

**Issue by alongafni** [Microsoft/vscode#46312]
I'm using VSCode Insiders where the update frequency is high.
When I click the "Restart to Update" button under Settings, it often starts downloading the next update immediately after restarting, and then it asks for another restart to update just a few minutes after I've updated it.

I think VSCode should keep track of updates even when it already has a new version downloaded.
This way, it can download new versions while I'm using it, and when I restart to update I'd immediately get the last update.

**Comment by Tyriar** [comment]
I often see this, sucks when you wait for the update and need to restart again shortly after relaunching.

**Comment by markhu** [comment]
For me, using Version 1.21.1 (2018-03-14T14:34:33.071Z), it prompted to restart-and-update, but clicking on Update Now just exited and neither updated nor restarted.
Eventually I manually downloaded April 2018 (version 1.23) and dragged it in Finder to the /Applications dir. So far so good.

**Comment by ssteinerx** [comment]
@markhu I am just noticing this new wrong behaviour as well.  Restart to update does neither.  This is recent, maybe the last week or so?

**Comment by darrenkenny** [comment]
This is one of the main issues I have with the insider builds - I agree with the submitter that it should install the latest update, not the first one that it downloaded, which may be a few days old if you've not used VSCode in that time.

It is not a new issue - in that it has been happening as long as I've used Insider builds, which is a quite a while now, just that it is painful to do the multiple updates sometimes.

One option could be to keep the 'Check for Updates' menu item, even when there is an update already downloaded - that way a user may override the 'Restart to Update' if they know it's likely there have been a few updates since the last restart - right now they are the same menu item.

On Mac, something like this is often done by looking at whether the Option button is pressed, and if it is, changing the menu item - you can see it, for example, when you click on the Wifi icon with Option pressed, and then again with it not pressed.

Maybe something like that could be done here too - or even just allow for checking for the latest update using the command palette - right now, you can only do that for extensions.
