### ISSUE TITLE
Installer doesn't disable launch of VScode  even when installing with /mergetasks=!runcode

### ISSUE THREAD

**Issue by spitfire** [microsoft/vscode#46350]
- VSCode Version: 1.21.1
- OS Version: Microsoft Windows 10 Pro 64-bit 10.0.15063.0

Steps to Reproduce:

1. Run `VSCodeSetup-x64-1.21.1.exe /SILENT /NOCANCEL /MERGETASKS=!runcode /LOG="C:\Windows\Logs\Software\Microsoft_VisualStudioCode_1.21.1_x64_02.log"`
2. See Code being executed at the end of installation

This wasn't the case before (last tested on 1.19.3)

Does this issue occur when all extensions are disabled?: N/A

**Comment by spitfire** [comment]
https://github.com/Microsoft/vscode/issues/19319 mentions this should work.

**Comment by craigmjackson** [comment]
The issue is that the ! that would disable a task is not making from the command line arguments into the effective installer config that is used.

Here is a workaround in the mean time.
Generate a new setup .inf file:
```
VSCodeSetup-x64-1.38.1.exe /verysilent /mergetasks='!runcode,addcontextmenufiles,addcontextmenufolders,a
ssociatewithfiles,addtopath' /saveinf=vscode.inf
```

Then edit vscode.inf (change "Tasks" line so "runcode" becomes "!runcode":
```
[Setup]
Lang=english
Dir=C:\Program Files\Microsoft VS Code
Group=Visual Studio Code
NoIcons=0
Tasks=addcontextmenufiles,addcontextmenufolders,associatewithfiles,addtopath,runcode ## Change to "!runcode" instead of "runcode" 
```
Then, you can use that vscode.inf in your unattended installation:
`VSCodeSetup-x64-1.38.1.exe /silent /loadinf=vscode.inf`
