### ISSUE TITLE
Make it more obvious when "Use Exclude Settings and Ignore Files" is not applied

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#46353]
It's a common issue to toggle this off accidentally and not realize it. Recent example: https://github.com/Microsoft/vscode/issues/46269#issuecomment-375200113

Maybe adding a message "100 results in 5 files without exclude settings applied" would help? Or " - exclude settings disabled".

Need a better phrase that encapsulates "exclude settings" and "ignore files"

The message could be underlined and would expand the ... section when clicked.

https://github.com/Microsoft/vscode/issues/46269
https://github.com/Microsoft/vscode/issues/46228

**Comment by Labrat02** [comment]
Part of the problem with this is that the cog icon is ingrained in our minds to show a settings window.    Changing this icon to something that better represents "exclusion" would be helpful.

**Comment by roblourens** [comment]
It does have the circle with horizontal line (like "do not enter") overlaid on the settings gear, which is supposed to represent exclusions in your settings, but maybe it's a bit subtle

**Comment by davermont** [comment]
It took me 10 minutes just now to figure out why it was ignoring my exclude settings. The displayed message ("exclude settings and ignore files are disabled") didn't help at all in how to turn it back on, it made it sound like a setting needed to be set true or false. The "do not enter" badge is small and honestly looked like an ellipsis to my eyes. Perhaps instead of dimming the entire glyph, the badge could toggle between a check when exclude is in effect and the "do not enter" when it's disabled. I'm not sure the best solution here but the current implementation is certainly problematic.

**Comment by roblourens** [comment]
Thanks @davermont I filed https://github.com/Microsoft/vscode/issues/65317 because this does seem to keep coming up.
