### ISSUE TITLE
found a bug for explorer module view popup menu

### ISSUE THREAD

**Issue by fjqingyou** [Microsoft/vscode#46396]
Issue Type: <b>Bug</b>

Hello!

   i'm Sorry, My English very bad , please forgive! thanks!

    on explorer view , I'm unfold multiple folder, selected a file by below the screen, use mouse right button down , vscode popup a munu.

    it's popup menu hava double state, full visible or partially visible, bug is in partially visible state.

    if it's popup menu is partially visible state, have a down arrow sign menu,i move mouse icon click this menu sign, but it not response. 

    i think , it's a bug, thanks!
    

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:39:09.335Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4578U CPU @ 3.00GHz (4 x 3000)|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.52GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none
Reproduces without extensions

**Comment by yume-chan** [comment]
If you are not good at English, you can always ask in your native language, we can translate for you.

On macOS, sometimes menus will appear like this if the cursor is close to the bottom of screen.

![image](https://user-images.githubusercontent.com/1330321/37835303-d0aeeb64-2eea-11e8-835a-f65094fb7a0d.png)

Clicking or hovering on the "down arrow sign" does nothing, you can only scroll on the menu to reveal more items.

I suspect it's an upstream bug since it's a native menu?
