### ISSUE TITLE
Markdown chapters are missing in 'Goto Symbol in Workspace'

### ISSUE THREAD

**Issue by fbehrens** [Microsoft/vscode#46406]
In `Code 1.12.1` I created a single-root workspace with  two `.js` and one `.md` file.

When I `Goto Symbol in File` it shows me the headings from my markdown.

But in `Got Symbol in workspace` i only see the  javascript functions.

**Comment by pradeepmurugesan** [comment]
@mjbvz Hello..  Need some clarification

This is because the extension  [markdown-language-features](https://github.com/Microsoft/vscode/tree/master/extensions/markdown-language-features/src/features) lacks the workspace symbol provider similar to [workspace provider for typescript](https://github.com/Microsoft/vscode/blob/master/extensions/typescript-language-features/src/features/workspaceSymbolProvider.ts)

Am i right or am going in a wrong direction ?

**Comment by mjbvz** [comment]
Yes, the `WorkspaceSymbolProvider` is what powers this feature. The high level flow of what `provideWorkspaceSymbols` should do for markdown:

1. Find all markdown files in the current workspace
1. For each file, use markdown's `TableOfContentsProvider` to extract out the basic heading info for each document
1. Convert the heading info into `SymbolInformation`

We'll have to see how poorly this performs in a large workspace. We may need cache the table of contents for each file so that we don't have to reparse the files each time

Let me know if you run into any problems looking into this or have any questions

**Comment by pradeepmurugesan** [comment]
Hi @mjbvz ,

   I tried to implement the above and its partially working. The only problem i face is I am using
```
workspace.textDocuments
```

which just fetches the opened docs in the current worksapce. Is there a way to fetch all the text documents ?

**Comment by mjbvz** [comment]
Fixed by #47610
