### ISSUE TITLE
Double click file 1st time does not open in new panel

### ISSUE THREAD

**Issue by GerbenJdeBoer** [Microsoft/vscode#46410]
Issue Type: <b>Bug</b>

open one file
doubel click a 2nd file, it will open in the same panel as the 1st
only a 3rd file will open in a new window

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.15063

<details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.7
gc-excelviewer|Gra|2.0.20
python|ms-|2018.2.1
vscode-docker|Pet|0.0.25

</details>
Reproduces only with extensions

**Comment by yume-chan** [comment]
It works by design.

By default single click on a file opens it in preview mode (indicated by the italic file name in the tab bar), single click other files will re-use this tab. It's useful to prevent so many opened tabs when finding or checking files.

If you don't want this feature, set `workbench.editor.enablePreview` configuration to `false`.
