### ISSUE TITLE
Css emmet completions gets wrongly triggered at the last property value in single line rules

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#46452]
Type `a` at the cursor `.foo { margin: |}` in a css file

![image](https://user-images.githubusercontent.com/16890566/37858165-bdece85e-2ebe-11e8-90bc-b55d4ff435c5.png)

**Comment by aeschli** [comment]
@ramya-rao-a I think I commented out some similar tests here as they failed and because I wasn't sure if this is just because of the late changes in #29113
- https://github.com/Microsoft/vscode/blob/addd44d6b845348bfa7d65106b40f5692bb7b3fa/extensions/css-language-features/server/src/test/emmet.test.ts#L60
- https://github.com/Microsoft/vscode/blob/addd44d6b845348bfa7d65106b40f5692bb7b3fa/extensions/html-language-features/server/src/test/emmet.test.ts#L65
Would it make sense to add (umcomment) the tests again?

**Comment by ramya-rao-a** [comment]
@aeschli Yes, those tests needed to be commented as the work for #29113 was reverted
