### ISSUE TITLE
[php] Javascript Syntax Highlighting Error after inline PHP

### ISSUE THREAD

**Issue by tip2tail** [Microsoft/vscode#4646]
- VSCode Version:  0.10.8
- OS Version:   Windows 7 Enterprise

Steps to Reproduce:
1.  Open a new .php file
2. Add the following code:

```
<script type="text/javascript">
Cookie.Set("Test", "<?=date("Y");?>"); 
</script>
```
- Note that the syntax highlighting shows the closing bracket and semi-colon as part of a string literal.

![2016-03-24_14-29-46](https://cloud.githubusercontent.com/assets/1719754/14019963/04221ea6-f1cd-11e5-9fcd-9579682c34ca.jpg)

**Comment by mjbvz** [comment]
I believe this is now fixed in VSCode 1.7.2:

<img width="382" alt="screen shot 2016-12-01 at 4 14 00 pm" src="https://cloud.githubusercontent.com/assets/12821956/20818227/31f2d778-b7e1-11e6-92f1-b35360d73eae.png">

The colorization inside the string is now different however. 

Please let us know if you still see the original problem and open new issues for any further syntax highlighting problems you see here.

Thanks.
