### ISSUE TITLE
Improve usability of the debugger by adding new keyboard shortcuts, fixing some behaviors, adding existing and new shortcuts to the context menus

### ISSUE THREAD

**Issue by tvilim** [Microsoft/vscode#46476]
Based on my own 'user' experience, I'd like to suggest and **_IMPLEMENT MYSELF_** following 'power user' improvements. I have already implemented successfully some of it and believe I can do the rest as well.

1) When focus is in the WATCH list, INSERT key should 'Add Expression' (not having to use mouse to click the + icon), this should also work when the watch list is empty but has focus.

2) When DELETE key is used to delete Watch Expression, focus should go to the next expression and if it does not exist, to the previous one (basically to keep the context), this way it would be possible to delete multiple expressions very easily (currently after deletion, the focus goes away and user has to press DOWN key and go to whatever item needs to be deleted next, this is quite tedious when there are multiple Watch Expressions.

3) CTRL + DELETE could be used for Remove All Expressions

4) CTRL + '-' could be used to Collapse All

5) CTRL + '+' could be used to Expand All (no equivalent feature exists now)

6) CTRL + C could be used to Copy Value, CTRL + E perhaps as Copy as Expression (in VARIABLES)

7) INSERT key could be used in VARIABLES for 'Add to Watch'

8) Similar changes should be applied to the VARIABLES, CALL STACK and BREAKPOINTS for consistency.

9) Keyboard shortcuts should be listed in the context menu similarly as they are listed in the main editor menu, this would help users to discover them.

10) Another nice addition would be ability to delete WATCH expressions using mouse click (perhaps a little X on the right edge when hovering with mouse there (the X would not be visible otherwise).

11) When in DEBUG view while debugging, it would also nice to have 'Add to Watch' option in the context menu of the code editor (this would save a lot of typing).

**Comment by isidorn** [comment]
@tvilim thanks for you great suggestion. With some of these I agree with some I do not. 
1. Makes sense this should be a command, not sure about the default keybinding though
2. Makes sense
3. Remove all watch should be a global command with no default keybinding so each user can assign whatever they want
4. Similar to Files: Collapse All in the expand all should be a global command with no default keybingind.
5. Expand all - no. This would send potentially very heavy evalaution calls to the debug adapter
6. Also some command work which should not have default keybindings
7. Same sa 1.
8. We should always be consistent
9. Sure. This should be picked up via the commandService
10. Context menu already does this. We had an X before but I removed it. So no action here
11. There should be something like this if I am not mistaken

As for PRs i prefer small simple PRs that a monster change with everything that I will never reveiw.
Please note that we are in endgame week and only accept limited changes. Also on wednesday I go on vacation, so I will only be able to respond in around 3 weeks.

**Comment by hsandt** [comment]
I'll add my shortcut suggestion here since it fits the topic:

12. DELETE should remove the highlighted breakpoints, if any, in the breakpoint panel.

Note that there may be several highlighted breakpoints: after clicking on a breakpoint and jumping to the corresponding line in code, you can move with the up/down arrows (dimmer highlight), but also add breakpoints to the selection by holding shift+up/down arrow. But this "selection" doesn't seem to do anything: DELETE does nothing, and the contextual menu only offers to toggle/remove one or all the breakpoints, not the current selection. So it would make sense to have the equivalent menu items for selected breakpoints.

In this case, it would also make sense to implement ctrl+click and shift+click to pick and extend the selection. I let you decide whether we should jump or not to the corresponding line in code in this case.
