### ISSUE TITLE
Option to not wrap search back to start of file

### ISSUE THREAD

**Issue by garyking** [Microsoft/vscode#46504]
Please add an option to not wrap the search back to the start of the file.

So if I hit "Find Next" multiple times and I reach the end of the document, then I hit it once more, I don't want to return to the first search result at the top of the file. I want it to stop moving forward instead.

Or at the very least, show a "refresh" icon when the search goes back to the top. I forget where I see this, but some popular apps have this.

**Comment by DevGim** [comment]
Would implement this feature please?
I also need it.

**Comment by anseki** [comment]
I also need this option.
To check something, I press `F3` key ("Find Next") repeatedly in long file. That is, I pressed `F3` key, and I said "This is OK, and next!", and I pressed `F3` key, and I said... Uh oh, I was not looking at the scroll bar, and I backed to top of the file before I even knew it, and I checked those again wastefully.

It should stop at last keyword by option, or a message should be shown near the cursor because a message in the bottom of window may be not looked.

**Comment by Ap0100L** [comment]
Please reOpen this issue

**Comment by timrobinson33** [comment]
This feature is important to me too

**Comment by SeerGiuS96** [comment]
You should really consider about implement that feature guys

**Comment by GustavoASC** [comment]
@SeerGiuS96  @timrobinson33  @Ap0100L I've developed a setting on PR #92243 to solve this need. It is currently available on 1.45 Insiders, which will be released as the official VSCode version during this week.

There's a new setting 'editor.find.loop' which controls whether the search automatically restarts from the beginning (or the end) when no further matches can be found.

Hope it helps! :smile: 
Happy coding!
