### ISSUE TITLE
Explorer: root folder that is a symbolic link not decorated

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#46536]
Steps to Reproduce:

1. `ln -s source target` to create a link on a folder
2. add the link as single entry to a workspace config file
3. open that workspace
4. restart

=> I see no link decoration for the root folder

**Comment by isidorn** [comment]
Well it is not only the symbolic link decoration but also the title of the resource.
For root resources I see the title of the target, for all other resources I see the title of the source.

It seems we are resolving roots in some other way compared to other resources.

After some investigation it seems that the issue comes from the `contextService.getWorkspace().folders` which gives the uri of the target not of the source.
Thus my explorer model is never aware that the root was actually link, since I get the uri resolved already [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/common/explorerModel.ts#L29)

Also assigning to @bpasero and @sandy081 since you might now if this is expected from the context service

**Comment by bpasero** [comment]
@isidorn @sandy081 I am quite sure that we are not `realpath` any of the root folders. We (should) only do that when you open a single folder, but maybe that changed?

**Comment by isidorn** [comment]
@bpasero well that is what I am seeing, just put a breakpoint [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/common/explorerModel.ts#L29) on startup in a single folder workspace

**Comment by bpasero** [comment]
@isidorn but this issue is about multi-root workspace, sorry if I did not make this clear.

**Comment by isidorn** [comment]
@bpasero that is what I meant. I was not clear sorry. So have a workspace, in that workspace have any number of folders I am getting the realpath from the `contextService` for each root

**Comment by bpasero** [comment]
@isidorn ok let me check...

**Comment by bpasero** [comment]
As discussed, you need to add the link to the file manually, not going through a picker.

**Comment by isidorn** [comment]
@bpasero good catch. The issue was that I forgot to update the explorerItem merge method to respect `isSymbolicLink`

**Comment by bpasero** [comment]
@isidorn there still seems to be a case where this does not work:

![before](https://user-images.githubusercontent.com/900690/37920334-e07b8942-3126-11e8-975a-4054f3dd9b89.gif)

**Comment by isidorn** [comment]
@bpasero the issue with that corner case is timing.
I first get the event that workspaceRoots changes, the decorations update, and only then is the fileStat actually merged.

A proper fix would be for the [DecorationProvider](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/electron-browser/views/explorerDecorationsProvider.ts#L16) to also listen on whenever a file gets resolved to update decorations.
A hack is to react on workspace folder change event with a timeout.

I do not like both solutions so to the backlog. Open for suggestions
