### ISSUE TITLE
Multiple Issues Related to IntelliSense Opened Since Last Release

### ISSUE THREAD

**Issue by stereokai** [Microsoft/vscode#46546]
I thought I'll open a single issue to firstly raise more attention to this problem and secondly to consolidate efforts: https://github.com/Microsoft/vscode/issues/46025, https://github.com/Microsoft/vscode/issues/46393, https://github.com/Microsoft/vscode/issues/45993, https://github.com/Microsoft/vscode/issues/46292

I am aware of the connection to Microsoft/TypeScript#22774 - which was already fixed. I don't have enough details to say that the TypeScript bug is responsible for all the IntelliSense trouble from the latest build, but I additionally want to make sure it gets into VSCode as soon as possible (it has been merged https://github.com/Microsoft/TypeScript/pull/22779)

**Comment by mjbvz** [comment]
Thanks. I suspect many of these issues have different root causes as broken intellisense is a very generic term. 

If you are seeing any issues related to intellisense, please open new issues instead of commenting on an existing one. This makes followup and tracking simpler

Will continue following up on the individual issues

**Comment by stereokai** [comment]
@mjbvz Awesome, thank you very much.
