### ISSUE TITLE
Reduce usage of isEqualOrParent in explorer

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#46549]
We have reduced the usage of isEqualOrParent in the explorer. However there are still a couple of places left before we can change this method to properly normalize pahts.
* `ExplorerItem.create()`: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/common/explorerModel.ts#L142
* `ExplorerView.getResolvedDirectories()`: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/electron-browser/views/explorerView.ts#L879

We should also check how often these methods are being called here.
Since we are in endgame week, I am assigning this to the next milestone

fyi @jrieken @bpasero

**Comment by isidorn** [comment]
I checked and on startup the the first reference to `isEqualOrParent` is called for each visible item in the explorer.
The second reference is only called on subsequent explorer refreshes. So it seems like that one might be fine to remain `isEqualOrParent`.
The first reference we should change before slowing down `isEqualOrParent`. @bpasero suggestions to what use as an alternative are welcome.

Though I do not think this is anything for endgame week.

**Comment by bpasero** [comment]
> I checked and on startup the the first reference to isEqualOrParent is called for each visible item in the explorer.

Is that really limited to the visible items (e.g. not the ones that are scrolled away) or all children of a folder?

> The second reference is only called on subsequent explorer refreshes. So it seems like that one might be fine to remain isEqualOrParent.

Well I would argue that depends on how often this method is called. The explorer refresh can kick in any time a file event is triggered which can happen often. So I would argue this one is actually the worse usage because it can happen undeterministic.

I currently do not have a good answer for an alternative to use. Maybe if the underlying model of the explorer was a Trie similar to what we do [here](https://github.com/Microsoft/vscode/blob/ben/editor/src/vs/platform/workspace/common/workspace.ts#L131), it would help?

**Comment by jrieken** [comment]
@isidorn didn't you change your model already a read, e.g. an item with child-maps? With that you should be able to find out if something is parent or equal by using each segment of a path and trying to find it in the current parent, right?

**Comment by isidorn** [comment]
@bpasero for all children, not only visible my mistake.
Yes you are correct the second usage is more problematic, it can be triggered via file events.

@jrieken yes I changed it and this should help.
Not adventourous enough to do this in endgame -> next week
