### ISSUE TITLE
This is terrible

### ISSUE THREAD

**Issue by Serg-zefir** [Microsoft/vscode#46645]
Issue Type: <b>Bug</b>

This is terrible http://i.shotnes.com/a/03/27/screenshot_505671508.png
http://i.shotnes.com/a/03/27/screenshot_936145377.png
"Hello, my name is Serhii (I am the Ukrainian language team). I have translated vscode-editor (100%)
vscode-extensions (10%), vscode-setup (100%), vscode-workbench (100%). I have translated into "smart cat" system and I have 61 files ".xlf" file format. However, I can not upload these files to the transfix. Help me contribute to the development of the Ukrainian localization of the VScode.  "

I talked with Aldo Donetti (AldoD), about the possibility of downloading translated files. Having spent a lot of time, and me and the members of the team who have contributed have been removed from the list.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:30.761Z)
OS version: Linux x64 4.13.0-37-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2760QM CPU @ 2.40GHz (8 x 2394)|
|Load (avg)|0, 0, 1|
|Memory (System)|7.67GB (0.87GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details>
Reproduces only with extensions

**Comment by danyeh** [comment]
@Serg-zefir , appreciated your contribution! We have been looking at how to merge back your contribution to Transifex. Since we don't own the backend, the progress is slow. The platform supports contribution in Transifex UI by default.
As for the contributor list, it only lists contributors for current monthly release. So it is not an issue.
Your name will be listed in Ukrainian language pack readme as top contributor. But first we need to figure out how to merge back your translation.
See an example of top contributor here: https://github.com/Microsoft/vscode-loc/blob/master/i18n/vscode-language-pack-tr/README.md

**Comment by danyeh** [comment]
@Serg-zefir , I close this one and we will follow up in 42673.
