### ISSUE TITLE
Tasks: Single/double quotes not quoted/escaped

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#46709]
1.22 insiders on Linux. Testing #46567.

Default quoting does not quote/escape when using a single or double quote in an argument or the command name.

**Comment by chrmarti** [comment]
Same when using a task provider.

**Comment by ramya-rao-a** [comment]
Same for $

```
...
"command": "echo",
"args: [
   {
      "value": "hello $PATH",
      "quoting": "escape"
    }
]
```

This will print the $PATH variable, I was expecting the $ to be escaped

**Comment by dbaeumer** [comment]
@chrmarti and I discussed this a little and here is what we should do:

- if an argument has a ' or " in it and an escape is requested they need to be escaped as well.
- if an argument has a ' in it and strong quoting is requested the ' must be escaped as well.
- if an argument has a " in it and weak quoting is requested the " must be escaped as well.

This might be problematic so under cmd.exe since it doesn't support escaping. I fall back to strong quoting for cmd.exe.

@ramya-rao-a I think the current behaviour is correct since escaping is more used like weak quoting than strong quoting. So `echo Hello\ $PATH` is more like `echo "Hello $PATH"` than `echo 'Hello $PATH'`. Please ping if you disagree.

**Comment by dbaeumer** [comment]
More complicated. In both bash and PowerShell you can't escape stuff in a strong quoted arg. This makes sense since in a strong quotes string is not interpreted by the shell.

**Comment by dbaeumer** [comment]
You can escape " in weak quoting. There is not need to escape ' in weak quotes since ' will not be interpreted in weak quoted args.

**Comment by dbaeumer** [comment]
Tested a little more:

- under bash you can't create a single strong quoted argument that contains a `'`. Even not when you escape it
- under PowerShell you can by putting `''` into the string (e.g. `echo 'Hello '' World'`)

**Comment by dbaeumer** [comment]
Here is what I fixed:

- if escaping is requested I escape `"` and `'` as well.
- I will not do anything special for cases where a string contains `"` or `'` and weak or strong quoting (including default) is requested. Reason being is that this can not be supported on all shell in all combinations and it will be hard to explain when we do something magically and when not. If users want to have such args they need to do the write thing in the arg and may be have special command per OS / Shell.

**Comment by dbaeumer** [comment]
To verify:

```json
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "dir",
            "type": "shell",
            "command": "echo",
            "args": [
                {
                    "value": "'Hello World'",
                    "quoting": "escape"
                }
            ],
            "problemMatcher": []
        }
    ]
}
```

Should print `'Hello Works'`
