### ISSUE TITLE
Allow to "force overwrite" from the notification about dirty write prevention

### ISSUE THREAD

**Issue by acdha** [microsoft/vscode#46706]
Issue Type: <b>Usability Improvement</b>

Currently the notification for a file which has local modifications on disk forces you to open the compare dialog and reconcile changes there before being allowed to save the contents. While in some cases using the comparison view has value there should be the option to simply overwrite the file directly.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:39:09.335Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4771 CPU @ 3.50GHz (8 x 3500)|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.08GB free)|
|Process Argv|/Users/cadams/Applications/Visual Studio Code.app/Contents/MacOS/Electron .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|1.9.2
EditorConfig|Edi|0.12.1
vscode-docker|Pet|0.0.25
django-html|bib|1.2.0
vscode-eslint|dba|1.4.8
prettier-vscode|esb|1.2.2
dotenv|mik|1.0.1
vscode-apache|mrm|1.1.1
vscode-stylefmt|mrm|2.5.0
python|ms-|2018.2.1
cpptools|ms-|0.15.0
rust|rus|0.4.0
stylelint|shi|0.35.0
rewrap|stk|1.8.0
vcl|tho|0.1.2
shellcheck|tim|0.3.0

</details>
Reproduces only with extensions

**Comment by gnprice** [comment]
Adding a voice because this thread has been quiet for a while: This is a recurring annoyance for me, and I'd love to see it fixed. When there's unsaved state in the editor and I try to save it, I basically always really do want to save it to the disk. A warning is good to get, but then I want to save the file.

For me it's usually impossible, even, for the comparison tool to be helpful: if the file on disk has changed it's usually because I switched branches, so the version on disk now is completely irrelevant and I want to compare to some previous commit I was on. Which is what `git diff` excels at -- which I'm going to use as soon as I can just get the data out to the file.

Even a button would be more friction than I'd like; I'd rather hit Ctrl+S again, or some other keyboard action. But it'd be a big improvement over just being told I can't save my data without going through these other steps.
