### ISSUE TITLE
Context menu triggers preview automatically

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#46733]
Re #46604

* Search `lifecycle` and type `lifecycles` in replace box
* Right Click

An editor is opened automatically, it seems weird that we try to show the diff view automatically. Another problem is the diff view rendering seems being blocked as well.

![searchcontext](https://user-images.githubusercontent.com/876920/37984908-5ae81116-31ac-11e8-98fc-bb03cafee5cf.gif)

**Comment by roblourens** [comment]
Because we open the file when the item is focused, and all tree context menu contexts are based on which item is focused. So this matches what the problems tree does. Need to find a way to work around it.

**Comment by roblourens** [comment]
I could...

- Give the TreeResourceNavigator the ability to focus a file without opening it, even when openOnFocus is set on the tree, via the focus payload
- Right now we only focus the tree here because the active menu items are set with context keys that depend on focus. We could also skip the context keys and return the correct actions by checking `element` in `onContextMenu`. Using context keys based on focus for registering menu items seems weird but it seems to be what we do elsewhere.
- Or, use different context keys that aren't based on focus, but that we just set based on `element` in `onContextMenu`. This way onContextMenu wouldn't have to know about particular menu items which is good

@isidor do you know whether we solve this problem anywhere else?

**Comment by roblourens** [comment]
Should be @isidorn on the last message, oops :P

**Comment by eamodio** [comment]
For the menu part, this might be related too: https://github.com/Microsoft/vscode/issues/22403#issuecomment-377596006

**Comment by isidorn** [comment]
@roblourens this issue does not exist in the explorer becuase when you right click we focus the item
and in the explorer we only open the item on selection.

I see that the search behaves differently (you open on focus change) so you might need a custom solution since we always open on selection in other trees afaik.
