### ISSUE TITLE
Multi Quick Pick: filtering should uncheck items.

### ISSUE THREAD

**Issue by gushuro** [Microsoft/vscode#46747]
Testing #46587

1. Open a quick pick with all items preselected
2. Start writing
3. Some items get filtered out but stay selected

There's a `xxx items selected` showing the correct number, but I still think it's not a good idea having non-visible selected items.

**Comment by chrmarti** [comment]
The filtering is done to simplify checking items in a large list. That simplification should not interfere with which items are already checked. The user might just want to add to the existing selection.

The fact that not all checked items are visible is a down-side, but that also happens when the list is large and not all checked items fit within the viewport. While that might be improved, I don't think unchecking filtered items would be the way to go.

**Comment by gushuro** [comment]
I understand that, and it makes sense. If someone wants to check different subgroups of options, it becomes much easier.
But when having all the items checked by default, I find the behaviour odd. The flow I picture is:
1. I run a command that prompts me with a multi quickpick list, with all the items checked
2. I only want the one thats called `hello world`, so I start typing until it is the only one visible
3. I press enter and realize (or not) that all the other items have been chosen as well.

Maybe I'm missing the "common" use case for this feature, and this is not a scenario users will face.

**Comment by chrmarti** [comment]
I see the problem, but I don't have a better solution currently than the selection count that we have. Let's see what the user feedback is and if we can come up with additional improvements.

**Comment by chrmarti** [comment]
I'll close this since there hasn't been negative feedback on this part of the UX. We can revisit it when needed.
