### ISSUE TITLE
Allow to mark settings as user settings only

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#46750]
Testing #46460

- VSCode Version: 1.22.0-insider  d656cdac7d61c16330520420e57a103697dde16d
- OS Version: MacOS 10.13.3

**Steps to Reproduce:**

1. Try adding `"window.openWithoutArgumentsInNewWindow": "on"` to workspace settings

**Bug**
Setting does not seem respected but there is no warning to indicate this

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
Good point and there might actually be more settings that should show a warning.

@sandy081 how can I mark my setting as global one only?

**Comment by sandy081** [comment]
@bpasero We do not have Global / User settings. We have only Window / Resource settings.

**Comment by bpasero** [comment]
@sandy081 then we might have a bug, try to set the `typescript.tsserver.pluginPaths` setting as workspace setting and notice the error.

**Comment by bpasero** [comment]
Renaming to reflect the desire. Once we have support for this I can make a pass to change it for specific settings.

**Comment by bpasero** [comment]
@sandy081 cool! any reason you did not reflect the location of the setting in the scope, e.g. "scope: user", "scope: workspace"....

I guess we would also need to allow extension authors to define this from their schema.

**Comment by sandy081** [comment]
@bpasero

> any reason you did not reflect the location of the setting in the scope, e.g. "scope: user", "scope: workspace"....

Because, we already defined scope with `window` and `resource` values. New value `application` will align with them to define application scoped settings.

> I guess we would also need to allow extension authors to define this from their schema.

Yes, I am planning to support `application` scope for extensions too. At the same time, I would like to deprecate the property `isExecutable` in favour of `application` scope. 

@kieferrm What do you think deprecating `isExecutable` property with `application` scope. It means those executable configuration properties has to mention `"scope": "application"`. And  do we still need to show the warning [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/trust/electron-browser/unsupportedWorkspaceSettings.contribution.ts#L62)? If so, it will be shown to all application scoped settings when applied in workspace settings.

**Comment by sandy081** [comment]
@kieferrm May I know if we still need `isExecutable` property and show the warning [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/trust/electron-browser/unsupportedWorkspaceSettings.contribution.ts#L62)?

**Comment by kieferrm** [comment]
So, it serves the same purpose it seems. If so, we can deprecate `isExecutable`.
