### ISSUE TITLE
Emmet wrap with abbeviation preview shows tabs instead of spaces

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#46779]
Issue Type: <b>Bug</b>

Testing #44833

**Steps**
1. With `"editor.renderWhitespace": "all"`
1. In an html file

    ```html
    <div>
        a
        b
    </div>
    ```

1.  Select a + b
1. Run `Wrap with abbreviation`
1. Type div

**bug**
In the preview, see tabs for the indentation instead of spaces. 

![screen shot 2018-03-27 at 4 06 29 pm](https://user-images.githubusercontent.com/12821956/37999756-2156fa48-31d9-11e8-853c-a377865ccbd9.png)

The inserted text correctly uses spaces however

VS Code version: Code - Insiders 1.22.0-insider (5fbcfff69a9af92efd823f18e4c9f4b8c4dbdf2a, 2018-03-27T20:55:46.655Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.09GB free)|
|Process Argv|/private/var/folders/_0/611900jn0yb43f1rc47_2wmh0000gp/T/AppTranslocation/03D24729-1C16-49B5-801F-6914290FC331/d/Visual Studio Code - Insiders.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|20%|

</details>

**Comment by ramya-rao-a** [comment]
@mjbvz This seems harmless. Any scenario where this causes disruption?

**Comment by gushuro** [comment]
This is actually two separate issues. 

The one @mjbvz shows is because of how we define the text to wrap for the previews. The effect is that between the innermost element of the abbreviation and the text we're wrapping we always insert tabs. In [here](https://github.com/Microsoft/vscode/blob/master/extensions/emmet/src/abbreviationActions.ts#L98) is where we use tabs directly but I think we could fetch configuration for the open editor and use tabs/correct amount of spaces accordingly.

A separate issue is when trying to wrap with a nested abbreviation, such as `div>ul`. The upstream module we use for expanding abbreviations adds the tab between the `div` and the `ul` blocks, and we change it if needed when inserting the result as a snippet. Since in the preview we are directly editing the open editor, I'm not sure if we can replace them easily from our side. 
Maybe there's an option we can pass to the module so that we can force it to use a predefined amount of spaces.

**Comment by ramya-rao-a** [comment]
The way to really fix this is not trivial and since the final snippet uses tabs/spaces as expected, I wouldnt want to spend much time here.
