### ISSUE TITLE
Local variables are not suggested in log message completions

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#46824]
Testing #45962

* add a log point
* very likely, in a log point, you might want to log the value of a local variable or argument to a function (i.e. not global variables)
* observe, the local variables are not suggested

![image](https://user-images.githubusercontent.com/5047891/38019107-03278a4e-3277-11e8-9250-f73b9cb82681.png)

**Comment by isidorn** [comment]
@alexandrudima there are quite some flaws with our current suggest approach
However I changed that I get the inteli-sense for the location of my breakpoint and not for the start of the document, this shuold make it more precise and I expect to fix this case.
In case it does not get fixed it might be an related to https://slack-redir.net/link?url=https%3A%2F%2Fgithub.com%2FMicrosoft%2Fvscode%2Fissues%2F46827

**Comment by ramya-rao-a** [comment]
While I do see completions, they seem to skip the first letter and use the rest 

In the example that @alexandrudima provided above, we get completions for `r` instead of `nr`

In the below example, we get completions for `urr` instead of `curr`

<img width="946" alt="screen shot 2018-03-30 at 2 58 46 pm" src="https://user-images.githubusercontent.com/16890566/38155178-13b5fb2e-342b-11e8-98ec-661f4ac36c47.png">

cc @jrieken

**Comment by weinand** [comment]
@isidorn I have disabled Intellisense for now with commit https://github.com/Microsoft/vscode/commit/18e38684e25908cd2b4b019a09465905dc1ffba2

**Comment by isidorn** [comment]
@weinand with the help of Joh this now behaves much better imho. Please try it out and if we decide to include it we can put it in release notes (I guess we did not do it last release)

**Comment by weinand** [comment]
@isidorn yes works better now. Let's ship this.
