### ISSUE TITLE
when i click ctrl+K and Ctrl+b

### ISSUE THREAD

**Issue by HelmiTatanaki** [Microsoft/vscode#4683]
- VSCode Version:0.10.11
- OS Version:Windows 7

I got this error message when i try to view in default browser?

No handler found for the command: 'extension.viewInDefaultApp'. Ensure there is an activation event defined, if you are an extension.

Steps to Reproduce:

1. 
2.

**Comment by egamma** [comment]
This looks like a problem with one of your installed extensions. I cannot reproduce this error and I get the message that this key combination doesn't bind to a command.

To run without extensions launch code with `--disable-extensions`

**Comment by HelmiTatanaki** [comment]
OK can you please tell me how to remove the extensions....
i will remove one by one and see where the issue stops

**Comment by HelmiTatanaki** [comment]
Hi there,

I sorted the issue out, i removed all the extensions and then installed them one by one...

Thanks

**Comment by egamma** [comment]
Command palette > `Extensions: Show installed Extensions` lists the installed extensions and you can uninstall them by selecting the 'x' button.

Since it looks like the culprit is the `extension.viewInDefaultApp` command you can search in `HOME_DIR\.vscode\extensions in the `package.json` for this string.

**Comment by egamma** [comment]
OK - happy end :smile: 

Now you have to tell me which extension has caused this, you should consider to file an issue against it.
