### ISSUE TITLE
Feature: Specifying the load order of extensions (reduce startup wait-time)

### ISSUE THREAD

**Issue by Lisoph** [microsoft/vscode#46846]
Allow the user to specify in what order installed extensions get loaded. This could reduce wait times quite a bit, or at least give the impression of a faster startup; by allowing small, essential extensions to get loaded first.

Users often install a lot of extensions, but in reality, only very few are really vital for the user's workflow. By allowing these "vital" extensions to be loaded first, the user has to wait less time before being able to work.

**Proposal**
The load order could be specified as an array, where extensions lower in the array (= with lower index) get loaded first:
```json
"extensions.loadOrder": [
    "my_super_important_extension",
    "somewhat_important",
    "mildly_important",
    "whatever"
]
```

Extensions not mentioned in the list would get loaded after the last specified extension (after whatever).

**Comment by alexandrudima** [comment]
Already today not all extensions are loaded on startup. Loaded extensions can be seen via `F1 > Show Running Extensions`

**Comment by Lisoph** [comment]
@alexandrudima True, however I still think this feature would be useful. When I take a look at my loaded extensions during normal workload, there are two extensions with around 33 ms, a bunch around 500 ms and one > 2400 ms. The most important extension needs 366 ms. If I could make this important one load first, followed by the two very quick ones and then the rest, could speed up my workflow.

By the way, what's the difference between "Activation" and "Startup Activation"?

**Comment by alexandrudima** [comment]
@Lisoph Can you create issues against the extensions with slow startup? It is somewhat crazy that an extension would take 2400ms to activate...

Startup Activation means that the extension got activated on VSCode startup (it uses `*` or `workspaceContains:` activation events).

The other got activated by you doing something. e.g. clicking an action, opening a certain file type, etc.

**Comment by Lisoph** [comment]
@alexandrudima good idea with raising an issue on the extension's GitHub, but I don't think this can apply to all extensions. I wouldn't necessarily consider slow startup a bug of an extension. Some extensions just need some time to load (for whatever reason).

Thanks for clarifying the activations!

**Comment by metjuperry** [comment]
I still think this would be really helpful. From experience, loading extentions such as Docker, Azure or Live Share takes priority over things such as XML and JSON formater, so I need to wait few seconds before i can format a document. I would like to put these extentions first because they take almost no time to load and I need them availible as soon as possible

**Comment by EPonyA** [comment]
I have installed a tab which replaces the empty workspace view of VS Code. Its startup activation is 12ms, but I have to wait two or three seconds from VS Code's startup to see it because it's a ways down the load queue. This is the only extension I want to have loaded almost instantly, so I second this feature request.

**Comment by hyprhare** [comment]
I'm finding visual conflicts with extensions that enhance the text editor visuals/experience and want to decide which extensions have priority over the others... I'm assuming being able to set the load-order (as well as the draw-order, supposing that could be different) would be a welcome addition to VS Code users.

**Comment by pikajude** [comment]
This feature would be useful for my workflow that uses both `direnv` and `rust-analyzer`. `rust-analyzer` needs to run **after** `direnv` has already loaded the environment, because otherwise it's not able to find the command line tools it needs. Currently this is fixable using the `Rust Analyzer > Restart server` action, but I vaguely remember using other language servers that don't support a restart action (or their restart action doesn't work properly).

**Comment by BstevensG4G** [comment]
I believe this may be what is causing the Redwood repository reported issue
VS Code Extension wont load in remote - ssh mode. #1478

**Comment by NomarCub** [comment]
Isn't https://github.com/microsoft/vscode/issues/57481 the same issue?

**Comment by Lisoph** [comment]
> Isn't https://github.com/microsoft/vscode/issues/57481 the same issue?

It appears it is. It was created 5 months after this one and mostly other people are commenting there. This yields > 60 upvotes (22 here, 43 there).

I don't think I'm a fan of their priority solution though. Shuffling around precedence scores could become unwieldly.

**Comment by peterwaller-arm** [comment]
Hi, please reconsider this one. See for example the issue above referencing this one: https://github.com/rust-lang/rust-analyzer/issues/15852 and the number of thumbs down on the above triage bot comment.

Without being able to control the startup order, it seems it's not possible to influence the environment which is necessary so that later extensions see the environment configured by the earlier extensions.

cc @isidorn @alexdima

**Comment by L-i-o** [comment]
In my setup Bookmarks extensions (alefragnani.Bookmarks, tintinweb.vscode-inline-bookmarks) conflict with Outline generation extensions (Oracle.sql-developer) when are activated before (the Outline panel remain empty).
I need to manually Disable and Enable the Bookmark extensions after all Outline extension are activated

**Comment by ackvf** [comment]
I don't really care about the order of extensions, but I would really love to be able to have a JS or Python related extension load only when first JS or Python file is opened, or simply being able to defer loading of any extension n seconds after startup and then have them load with lowest priority so that the IDE doesn't hang
