### ISSUE TITLE
Issue Reporter: Don't show anything when no duplicates are found

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#46844]
Testing #46595

The `No results found` phrase pushes the whole UI down and caught me by surprise: I actually didn't know what that was about for a couple seconds.

![image](https://user-images.githubusercontent.com/22350/38029720-f506d35a-3296-11e8-9ae7-768988bdd602.png)

**Comment by RMacfarlane** [comment]
@joaomoreno Instead of removing it, what if it was just changed to `No similar issues found`? It seems useful to me to explicitly tell the user that we didn't find any duplicates. I experimented with adding some progress text that shows up when a search is being done, but because search is fast and debounced to every 300ms when typing, it just added a lot of ugly flashing. I think showing some sort of indicator that a search is being done would be a better experience though

**Comment by joaomoreno** [comment]
Sure, works too

**Comment by RMacfarlane** [comment]
Changed text to `No similar issues found` and now only perform a search if there's text in title when title or description update.
