### ISSUE TITLE
TypeScript debugging impossible. Breakpoints randomly get hit and jump up and down in the file

### ISSUE THREAD

**Issue by therawk** [Microsoft/vscode#46905]
- VSCode Version: 1.21.1
- OS Version: Win 10 Pro 1709 

Steps to Reproduce:

1. Set breakpoint in VS Code
2. Click on Debug (I'm using the Chrome Debug extension)
3. When Chrome loaded refresh the page (doesn't matter if in browser or in VS Code)
4. See the breakpoints randomly move up or down in the .ts file

I tried many configurations but ended up using this:

```
"version": "0.2.0",
  "configurations": [
    {
      "name": "Launch Chrome against localhost",
      "type": "chrome",
      "request": "launch",
      "url": "http://localhost:4200",
      "webRoot": "${workspaceRoot}/src"
    }
  ]
```

Which looks good to me. Tried attatching, different webRoot configurations but nothing seems to work.

VS Code didn't hit one single breakpoint I set which makes it impossible to use the debug feature at all.

Angular CLI 1.7.3 btw

**Comment by roblourens** [comment]
Can you share your project?

**Comment by Mates1500** [comment]
I've been encountering the same problem.

It started appearing when I upgraded my Angular project from version 4.2 to version 5.2. I've noticed that WebPack has a little different behavior, so I imagine that one has been upgraded as a part of the process, too.

1. In the previous version, the root of webpack:// started referencing the source map files/folders outright, but the new version has this "." folder first.
![image](https://user-images.githubusercontent.com/732314/38109493-92b1b2ee-3398-11e8-868a-0cc6b961ebf2.png)
I tried playing with source maps override for a couple of hours in launch.json, but to no avail.

2. The furthest I got was one of every like 5 breakpoints _sometimes_ working, and even then VS Code started opening new tabs of readonly files it couldn't match due to the new **// WEBPACK FOOTER //** markup syntax at the end of the source map files.
![image](https://user-images.githubusercontent.com/732314/38109659-29f24ca4-3399-11e8-8643-ef1513f91cce.png)

So I have a feeling there might be an issue with the new WebPack version due to the issues explained above

**Comment by therawk** [comment]
I just tried the insider build to see if it works with that, unfortunately it doesn't.
I am facing the same problems as @Mates1500 - a readonly file gets opened + the webpack:// in sources are in the "." folder

**Comment by roblourens** [comment]
Thanks for the details, I found the issue at least for @therawk's project. Will be fixed in the next update.

**Comment by therawk** [comment]
Was this supposed to be fixed in the update which was released today?

Unfortunately nothing changed :|

**Comment by roblourens** [comment]
It was actually a little too late for the 1.22 release but you should see the fix in Insiders.

**Comment by roblourens** [comment]
Can someone try again with the latest chrome-debug version, 4.4.1? It seems to be working better for me, I didn't fix anything specifically for this but the other version was a little stale.

**Comment by Mates1500** [comment]
Well, after toying with it for over an hour, I have gotten it working again after doing things in this order

1. Remove and reinstall all `node_modules`
2. I changed my launch json task to the following 
``` 
{
  "name": "ng serve",
  "type": "chrome",
  "request": "launch",
  "url": "http://localhost:4200/",
  "webRoot": "${workspaceFolder}/RealEstateApp"
}
```
considering my workspace looks like this, YMMV
![image](https://user-images.githubusercontent.com/732314/39673111-7f56d89e-5136-11e8-8c73-96edab0eaecf.png)


3.  remove all the old breakpoints and reinsert them again afterwards (seriously, prior to the complete removal, they were randomly jumping up and down everywhere).

**Comment by roblourens** [comment]
I can't get this project to build anymore. I get `ERROR in node_modules/@angular/flex-layout/core/typings/observable-media/observable-media.d.ts(1,22): error TS2305: Module '"/Users/roblou/Downloads/messedUp_Breakpoints/node_modules/rxjs/Rx"' has no exported member 'Subscribable'.`

I think flex-layout depends on a different version of rxjs, not sure how to fix it. There's no package-lock.json.

There have been lots of changes to the debugger since this was reopened, let me know if you are still having issues.
