### ISSUE TITLE
Multi select: cursor over button should be same as for other buttons

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#46929]
E.g. compare with this cursor:

![image](https://user-images.githubusercontent.com/900690/38085466-f0f45af2-3350-11e8-82ae-ff085a0a6e64.png)

The cursor over the multi select widget seems to be the pointer and not hand cursor.

**Comment by kieferrm** [comment]
@chrmarti: We now have the hand cursor everywhere in the multi-select except over the checkboxes. (It's actually the same behavior on the welcome page.)  The cursor over the checkbox is consistent with what the OS does and also for example what you

- [ ] here on the left

but it feels awkward since a checkbox is something I interact with just like the rows themselves.

**Comment by chrmarti** [comment]
Indeed, at least on Mac the pointer cursor is used very sparingly.
