### ISSUE TITLE
Provide a fallback DOM renderer for terminal to use when GPU it turned off

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#46954]
Upstream: https://github.com/xtermjs/xterm.js/issues/1360

**Comment by micage** [comment]
It's not true that it takes very long. It does not get visible at all. I have to downsize the terminal pane to a certain size to make it visible again. In my case it's about 5-10 lines. Seems to me that the canvas is not resized properly. There are no problems if I disable GPU rendering (code --disable-gpu). Also without any noticeable performance issues.

Would be nice to have a flag in the preferences to disable GPU rendering as a quick workaround.

One of the reasons for using code (instead of Atom or Sublime) was the integrated terminal which seems to be broken since the new canvas rendering was introduced.

My System Config: OS X 10.11.6, GPU: NVidia 8800, 4GB RAM

**Comment by Tyriar** [comment]
@micage that will probably get fixed as part of this as well, it's probably something to do with your GPU/Chromium not liking the texture sizes above a certain size.
