### ISSUE TITLE
Error 'Unexpected Token' not displayed

### ISSUE THREAD

**Issue by JustifiedFlaw** [Microsoft/vscode#4695]
- VSCode Version: 0.10.11
- OS Version: OS X 10.10.5

Steps to Reproduce:

1. Create a javascript file
2. Type in 
var a = "abc".replace(new RegExp("abc", "g"), );

Expected: A warning that something should be between the comma and parentheses at the end

**Comment by Reanmachine** [comment]
I may be wrong, but I think this is actually a bug with [TypeScript](https://github.com/Microsoft/TypeScript/). I saved your example into both a `.js` and a `.ts` file and ran the following:

![Output](http://i.imgur.com/WjHaT4t.png)

As you can see both `node` and `tsc (typescript)` generate expected errors, but when typescript is parsing it as javascript it ignores the error. The output of `tsc` is as follows:

    var a = "abc".replace(new RegExp("abc", "g"));

Since VSCode's diagnostics for JS are based on the TypeScript Server I feel that the EcmaScript5 mode of TypeScript doesn't see this as a problem because it just compiles the trailing parameter away.

There's an open Issue in the typescript project for TS to support trailing parameter lists [Microsoft/TypeScript#7279](https://github.com/Microsoft/TypeScript/issues/7279)

**Comment by Tyriar** [comment]
Thanks for deduping this @Reanmachine :+1:
