### ISSUE TITLE
Select To Next/Previous Command loses terminal focus when invoked from the command palette.

### ISSUE THREAD

**Issue by sbatten** [Microsoft/vscode#46961]
Issue Type: <b>Bug</b>

When invoking `Select to next/previous command` from the command palette, the terminal loses focus  and causes confusion.

VS Code version: Code - Insiders 1.22.0-insider (952b2a641da89a6c7bc28387474bc8afd47f0d2f, 2018-03-29T05:17:25.524Z)
OS version: Windows_NT x64 10.0.16299

**Comment by kennyle1412** [comment]
I don't think it's just the Select to Next / Previous Command. Anytime the command palette is invoked, the focus goes to the workbench(?) and the terminal will lose focus. Excluding the commands that refocus the terminal afterwards (eg. createTerminal, splitTerminal).

Maybe default it so that all terminalActions refocus terminal afterwards?

**Comment by Tyriar** [comment]
@kennyle1412 when the command deals with focus or selection we should definitely make sure focus works. Maybe there's a way we can do this generally @bpasero?

**Comment by bpasero** [comment]
@Tyriar currently we just always put focus back to the editor which is probably not clever and can be improved. PR welcome.

**Comment by kennyle1412** [comment]
@Tyriar Then I guess every terminalAction that deals with those things should do a terminal.focus() before it returns. That should work for when the action actually goes though how efficient that is I can't say.

However, if the quick command is invoked then cancelled, we'd be out of luck since nothing is executed haha. We can try to save the previousFocus when invoking quick command and refocus previousFocus if the command palette is cancelled (/ nothing selected) instead of forcing it to the editor or only focus the editor if a command is chosen. Though I haven't looked at the quick command code yet so I'm not sure if those are feasible.

@bpasero that way we can still focus to the editor in the general case, but don't change anything when the action is cancelled.

**Comment by Tyriar** [comment]
@bpasero how about adding something like this to `IAction`?

```ts
export interface IAction {
  restoreFocus(): TPromise<any>
}
```

Which would be run to restore focus when it's implemented (or noop if not) when escape is pretty or the command is triggered.

**Comment by bpasero** [comment]
@Tyriar I would stay away from adding anything to `IAction`, that interface is only meant to give a runnable an identifier and a label. 

Can you not just change focus from your action when it runs? Maybe we need to pass some extra context into the actions that get executed from the command palette.

**Comment by Tyriar** [comment]
@bpasero but there's the case @kennyle1412 brought up where cancelling the command palette will then focus the editor as `run` is not triggered.
