### ISSUE TITLE
Emmet doesn't get triggered in single line SCSS with nested rules

### ISSUE THREAD

**Issue by gushuro** [Microsoft/vscode#46973]
In the following example `.foo{ dn| .bar{display: none;}}` we get css completions but no emmet ones. Triggering with tab or with Expand Abbreviation command doesn't work either.
If we add a new line 
```
.foo{ dn|
    .bar{display: none;}}
```
everything works fine.

**Comment by ramya-rao-a** [comment]
This is because the upstream emmet css parser considers `dn` to be part of the selector `.bar`

With the newline, it no longer considers the same.

The fix would be very hacky and not worth the pains as this is a very corner case.
Closing for now and not fixing this unless there is enough user feedback about the same
