### ISSUE TITLE
SCM: Add `amend` checkbox to commit panel

### ISSUE THREAD

**Issue by dmstern** [microsoft/vscode#46994]
For now, we have the opportunity to amend commits via command palette or via git context menu.

It would be great if there were an `amend` checkbox right beside the commit message box to have this feature integrated in the source control panel.

**Comment by madig** [comment]
Atom has a nice UI for this.

**Comment by MrEfrem** [comment]
It's really needed feature. I for example use specific GIT repo where I should to `amend` my latest commit with automatically generated UID, on first commit, in commit message. Then my changes will follow to same `PR`. Otherwise if I will lost that UID on second commit (when I execute `amend`) then the GIT repo will create second `PR` instead of change previous.
Also WebStorm has this feature. Why don't you consider opportunity to implement this?

**Comment by hasardel** [comment]
On other git editors, the checkbox to amend a commit writes the commit message with previous commit if the field is empty.

**Comment by aminomancer** [comment]
There is also the arrow dropdown menu next to the Commit button. It includes Commit, Commit & Sync, and Commit & Push. "Commit Staged (Amend)" could be added to that menu. For that matter, so could "Stash"

**Comment by lszomoru** [comment]
"Commit (Amend)" is now available as a secondary action on the "Commit" action button.
