### ISSUE TITLE
In git changes view, the old file is displayed in the default language regardless of user choice

### ISSUE THREAD

**Issue by eladts** [Microsoft/vscode#4704]
- VSCode Version: 0.10.11
- OS Version: OS X 10.11.5

Steps to Reproduce:
1. Open a file and change its language.
2. Open the file in the git changes view.

The old version will be displayed in the default language for the file, ignoring the user selection.

**Comment by Tyriar** [comment]
I'm reading this as: if the file is currently open with an custom language mode active, the git changes view should use the custom language mode.

/cc @aeschli

**Comment by eladts** [comment]
That's exactly what I meant, @Tyriar. Currently the new version in the changes view is colorized according to the custom language, but the old version is not.

**Comment by Tyriar** [comment]
@eladts by old version do you mean an older version of vscode? So the latest version is working as expected/desired?

**Comment by eladts** [comment]
No, I mean the old version of the file when comparing a file to its checked in version. It does not happen when comparing two different files. I only tested it in 0.10.11, I haven't used any other version of VS Code.

**Comment by Tyriar** [comment]
@eladts got it, updated the labels to reflect it's a bug. They definitely shouldn't be opening with different colorizers. Thanks for the report!

**Comment by eladts** [comment]
Here is a screenshot showing the issue.

![image](https://cloud.githubusercontent.com/assets/6475871/14088871/dd50017c-f4ff-11e5-89d4-6b283201512c.png)

**Comment by joaomoreno** [comment]
@bpasero This happens during construction of my GitDiffEditorInput. At that time all I have is the editor input for the right side. This one returns `application/unknown` even after the user sets a specific mode via the status bar. How can I get a hold of the mimetype the user specified?

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/browser/editors/fileEditorInput.ts#L95 ?

**Comment by joaomoreno** [comment]
That does not work. [Here's the point](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/git/browser/gitServices.ts#L192) where I get the input. Even after changing the mimetype in the status bar, the **input** itself still reports `application/unknown`:

![image](https://cloud.githubusercontent.com/assets/22350/14858286/bfcc0756-0c9f-11e6-858d-36b6a6ded496.png)

![image](https://cloud.githubusercontent.com/assets/22350/14858289/c49e2b6a-0c9f-11e6-867b-3056082b6e49.png)

**Comment by bpasero** [comment]
@joaomoreno sorry, wrong spot. when you change the mode from the status bar we actually literally change it on the code editor model, bypassing my input and my model. So you would have to ask Alex model for the mode set to retrieve this info.

**Comment by joaomoreno** [comment]
*How to get it* is actually my original question. 😄

**Comment by bpasero** [comment]
Well yeah, sucks. You need to resolve the input to my model and then get Alex model from it (https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/common/editor/textEditorModel.ts#L51)

**Comment by joaomoreno** [comment]
Then we should maybe consider doing this at the diff editor level somehow? Eg: if the left hand side input's mimetype is inconclusive (which happens to be my case), the diff editor should open it with the same mime as the right hand side's model mime.

**Comment by bpasero** [comment]
@joaomoreno I think the mime type is a bit of legacy that does not play a big role here, it was used only at construction time, but in this case the user changed the mode and that change is not reflected in the mime type anywhere. In fact I even have a debt item to remove the concept of mime from the workbench.

I am not sure if we could say that the diff editor should always take the same mode for both sides because there is a use case where each side needs to use its own mode: when you compare 2 files of different extensions.

For the git case though I would not think there is any use case where you would want the left hand side to color differently from the right hand side. So maybe in that case the diff editor widget needs to always pick up the same mode for both sides?

**Comment by joaomoreno** [comment]
Not so sure about removing mime altogether. They do bring quite a bit of detail into the input and models themselves. Disregarding file extensions, they do help in caching the knowledge of *I know this is a JavaScript file because I read `#!/bin/env node` at the top of it*. But that's a separate discussion.

As for *the diff editor should always take the same mode for both sides*, that's why I mentioned *if the left hand side input's mimetype is inconclusive*. If the mimetype, coming in from the file extension or from the contents, is not inconclusive I suggest we do nothing and that's just life.

Finally, addressing the last point, if you rename a file from `foo.js` to `foo.ts`, that change appears in the diff editor and TypeScript colouring on the left would be ideal.

**Comment by bpasero** [comment]
Well we cannot remove the mime thing but would probably replace it with something that is closer to the mode ids we already have in our system.

I like the idea of using the right hand sides mode for the left hand side if the left hand side uses plain text mode otherwise. Is that what you suggest?

**Comment by joaomoreno** [comment]
I actually don't even get `text/plain` but `application/unknown`. When hitting the latter we'd do it, yeah.

**Comment by bpasero** [comment]
Argh, thats another reason for ditching the mime types, I think we only use that to find out if a file is binary or not. Anyhow, its hard to understand whats going on, lets talk about it in person when I am back...

**Comment by joaomoreno** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.

Thanks for your understanding. Happy coding!
