### ISSUE TITLE
files.exclude when $(basename) not working anymore if file name contains a uppercase letter

### ISSUE THREAD

**Issue by simon129** [Microsoft/vscode#47120]
- VSCode Version:
Version 1.22.0-insider
Commit 81335051b2d1460112905c2bce23c205e7cdd231
Date 2018-04-03T01:09:54.914Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

- OS Version: Win7

Steps to Reproduce:
1. I have 2 pair of files (xxx.js and xxx.js.meta), one is using lowercase , the other is using uppercase filenames
2. my workspace setting is the following
``{
    "files.exclude": {
        "**/*.js.meta": {
            "when": "$(basename)"
        },
    }
``

`lowercase.js.meta` is hidden correcty, but `UPPERCASE.js.meta` is there, not hidden by `files.exclude`

![step1](https://user-images.githubusercontent.com/240547/38232727-bc4e0aca-374a-11e8-8484-3eeeffa00733.png)

![step2](https://user-images.githubusercontent.com/240547/38232726-bc24901e-374a-11e8-9c08-a66d52c727ea.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by gregbacchus** [comment]
I get the same when there are any uppercase letters in the filename... i.e. `test.ts` will hide `test.js` but `Test.ts` will not hide `Test.js`

**Comment by bpasero** [comment]
This is a regression from @isidorn change to store stat names in a map as lowercase on macOS/Windows: 

https://github.com/Microsoft/vscode/blob/6ef45d9332ded9bac37c0ec43a9dd70d165c9acc/src/vs/workbench/parts/files/common/explorerModel.ts#L253

We then fail to compare the names properly. A simple change such as:

`return Object.keys(this.children).map(name => this.children[name].name);`

Would restore the old behaviour but result in ugly runtime performance because this method is being called for each element to decide if it should get filtered or not. Alternatively we could store a second Map with the original file names maybe.

/cc @jrieken

**Comment by jrieken** [comment]
>  ugly runtime performance because this method is being called for each element to decide if it should get filtered or not.

For all or until the viewport is populated? 

>  Alternatively we could store a second Map with the original file names maybe.

I think the name, as-is, is stored in the business objects. So instead of working with the keys, one could work with those from the values

**Comment by bpasero** [comment]
> For all or until the viewport is populated?

Unfortunately for all items of a folder. I think the tree needs this to show a proper scrollbar height. 

> I think the name, as-is, is stored in the business objects. So instead of working with the keys, one could work with those from the values

Yes, I am using the business objects now, but also changed to a `Map` instead of `Object` for perf reasons.

@isidorn fyi I changed the explorer model to be a `Map` instead of an `Object` literal to improve the lookup time for the actual file names for the glob filter. It turns out that we require this list of file names for each item in a folder (visible or not). Using `Object.keys()` each time gave a very bad perf hit. The current solution is still not ideal so I created https://github.com/Microsoft/vscode/issues/47187
