### ISSUE TITLE
Unable to do a console setup call when running a task

### ISSUE THREAD

**Issue by Roaders** [Microsoft/vscode#47137]
- VSCode Version: 1.21.1
- OS Version: Windows 7

In my work environment we have to run a script before we can use node. Whenever we open a new command window we need to do this. Because of this my build task looks liek this:

```
"tasks": [
    {
        "type": "process",
        "label": "build",
        "command": "cmd.exe",
        "args": ["/c", "initiateNode 8.9.4 && tsc"],
        "isBackground": false,
        "group": {
            "kind": "build",
            "isDefault": true
        },
        "presentation": {
            "echo": true,
            "reveal": "always",
            "focus": true,
            "panel": "dedicated"
        },
        "problemMatcher": [
            "$tsc"
        ]
    }
]
```

This works fine but each time I re-run the task it does the initiateNode call again.
I need a setup script that runs once when the task is first launched. Is such a thing possible?

Does this issue occur when all extensions are disabled?: Yes

**Comment by dbaeumer** [comment]
Currently not and the way tasks work this is very hard to achieve since each task run creates a new shell process (it is very hard to determine if a shell is idle).

What you can do is run `initiateNode 8.9.4` in a command shell and then start Code from that shell using code.bat. Then the tasks when executed have the right environment. 

I will close the issue since reusing shells for n tasks runs is currently not on our radar :-).
