### ISSUE TITLE
Make search tree context menu multiselect-aware

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#47166]
We need the controller at https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/electron-browser/views/explorerViewer.ts#L369 to be not Explorer-specific so it can drive multiselect in other trees.

TreeResourceNavigator https://github.com/Microsoft/vscode/blob/master/src/vs/platform/list/browser/listService.ts#L456 kind of conflicts with it, need to figure out how that's supposed to work.

We will need a generic version of https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/browser/files.ts#L27 currently the keyboard shortcuts on some of the search context menu items don't work for the same reason

**Comment by Stadly** [comment]
What would it take to get this out of the backlog and into a planned release?

**Comment by roblourens** [comment]
A PR would help

**Comment by qiangxi** [comment]
Yeah, like issue [#77749](https://github.com/microsoft/vscode/issues/77749). In the search results, I want to be able to select multiple rows of search results and then copy them, this feature will be very useful. 

Because not all search results can be used, such as some specific logs can indicate whether an application function is working properly. So if we have this feature, we can just select these specific logs and copy and paste them to the target location.

If you can release this feature, I am very grateful.

**Comment by bpasero** [comment]
I love this new addition 👏

**Comment by Eskibear** [comment]
Multiselect in Search works well! One feedback is that I cannot batch undo the replacement in different files. Imagine I replaced multiple files with wrong text, it's painful for me to undo the changes one by one.

**Comment by andreamah** [comment]
> Multiselect in Search works well! One feedback is that I cannot batch undo the replacement in different files. Imagine I replaced multiple files with wrong text, it's painful for me to undo the changes one by one.

Made a new issue for this here #157533 🙂
