### ISSUE TITLE
Notepad++-like copying file name and dir to clipboard

### ISSUE THREAD

**Issue by mrkafk** [Microsoft/vscode#47193]
Feature request:

In Notepad++ there is a useful feature on getting file path and name data by right-clicking the file tab, much like in VSCode. However, VSCode can only copy full path to the file, while in Notepad++ there are two more options:

- Filename to Clipboard (just filename)
- Current Dir. Path to Clipboard (just dir where the opened file is located)

At least I find those options useful, in VSCode I often have to copy entire path to the file and then edit it to get a path component.

**Comment by roblourens** [comment]
You could write an extension to do this.

**Comment by mrkafk** [comment]
Writing extension for such a small piece of code that this feature would require is an overkill. Every extension is additional work for plugin subsystem, additional maintenance, updates, etc. I'd argue that an overall cost of extension as such is worth only a bigger chunk of functionality than this.

**Comment by arthurblake** [comment]
I've written external tasks to do this and it's quite pretty easy (using clip.exe on windows).  Nevertheless, it would be nice to have direct support for it in vscode. Another common one I use is to copy a fully qualified class name to the clipboard. That one is very language specific obviously.

**Comment by vancouverwill** [comment]
yep in Webstorm you can copy relative path which is a killer feature as when sharing a file with a team mate or pasting it into github, ticket etc I never want to copy my local path but always need the file path relative to the repo.

**Comment by TomasHubelbauer** [comment]
I'd like to extend this request to relative file path, since #46719 has been auto-closed without a resolution proving fragmentation of information in issue threads to be alive an well. Cross-copying my comment from there:

FWIW I would also like to see *Copy Relative Path* and an internal command next to the *Copy Path* one which exists on the tab context menu currently. That one should be renamed to *Copy Absolute Path*. This feature request is titled *Copy file name*, which I am not sure refers to relative files? But that I think would be the most useful.
