### ISSUE TITLE
Autodetect indentSize takes template literal into account

### ISSUE THREAD

**Issue by SamVerschueren** [Microsoft/vscode#4720]
- VSCode Version: 0.10.11
- OS Version: Mac OS X 10.11.3

Steps to Reproduce:
1. Open a new project and make sure `editor.tabSize` is set to `auto`
2. Create a new file `test.js` with the following contents

``` js
'use strict';

const multiline = `
  this is a multiline
  string with 2 space indentation
`;

function log(str) {
    console.log(str);
}

log(multiline);
```

> Note: The indentation inside the `log` function is a `tab` but GitHub parses it to 4 spaces. So make sure to convert this to a `tab` when copy-pasting.
1. Close the file and reopen it

<img width="310" alt="screen shot 2016-03-28 at 21 33 32" src="https://cloud.githubusercontent.com/assets/1913805/14087927/c1070236-f52c-11e5-939f-3201ba14eeb2.png">

As you can see, it sets the `tabSize` to `2` because it is `2` in the multiline template literal. But it shouldn't take strings into account to determine this.

// @alexandrudima

**Comment by alexandrudima** [comment]
I think the feature request label is appropriate for now... 

The indentation detection code is language agnostic, so it just looks at the file contents (not at the tokens).

If we ever change that code to first tokenize the file and then guess, I agree that lines in multiline strings and lines in multiline comments should be omitted from the detection.

**Comment by SamVerschueren** [comment]
:+1:

**Comment by alexandrudima** [comment]
To keep the number of issues in our inbox at a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: we look at the number of votes the issue has received and the number of duplicate issues filed. Thank you for your time and understanding.

P.S. If you disagree and feel that this issue is crucial: we're happy to listen and to reconsider.
