### ISSUE TITLE
Calling workspace.rootPath gives undebuggable error

### ISSUE THREAD

**Issue by jsloyer** [Microsoft/vscode#4721]
- VSCode Version: 0.10.11
- OS Version: OSX

I am working on enhancing some functionality to vscode, PR will be coming and trying to call the following and I get the following error.

```
import {workspace} from 'vscode';
console.log(workspace.rootPath);
```

```
An unknown error occurred. Please consult the log for more details.
```

There is nothing more in the Crome dev console and also the shell window where I am running `./scripts/code.sh`.

What is the proper way to get get the root workspace path?  In an extension the call to `workspace.rootPath` works fine.

**Comment by jrieken** [comment]
@jsloyer I cannot reproduce the behaviour you are describing. The call to `workspace.rootPath` is valid as you describe it. 

Can you attach the reading from the console (Developer Tools) and try the snippet above when being enclosed in a `try-catch`-statement

**Comment by jsloyer** [comment]
@jrieken I wrapped it in a `try-catch` and still no extra output.  Try placing the code in `src/vs/workbench/parts/git/browser/views/changes/changesView.ts` in the `render` method.
```
try {
			console.log(workspace.rootPath);
		} catch(e) {
			console.log(e);
		}
```

**Comment by jrieken** [comment]
Oh.. All of the [vscode.d.ts](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts) can **only** be used in the extension host, not in the main part. Sorry, I know it's confusing, but for the extensions we try to surface all of our internal APIs in a nice & compact way - that's why we have the `vscode`-module. Our internal API is less polished and has grown. Still, I am happy to help you with that. The `workspace.rootPath` info you will find like so: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/node/extHost.api.impl.ts#L242
