### ISSUE TITLE
Markdown links: can't open md files in other directories

### ISSUE THREAD

**Issue by cweekly** [Microsoft/vscode#47247]
Issue Type: <b>Bug</b>

1. Create 2 markdown files, e.g. `~/docs/logs/we180407.md` and `~/vbox/win10x64e/devnotes.md`. Note they're in different directories.

2. In the first, create a standard markdown link to the second, e.g.
`[vbox-devnotes](~/vbox/win10x64e/vbox-devnotes.md)`
or, with an absolute path:
`[vbox-devnotes](/Users/chrisweekly/vbox/win10x64e/vbox-devnotes.md)`  

3. View the 1st in editor pane, and alt-click the link to the 2nd.

Expected / hoped-for behavior:  
2nd file opens -- as it does, if the file is in the same directory.  

Actual behavior:    
`'Unable to open 'vbox-devnotes.md': File not found
(file:///Users/chrisweekly/docs/cwlog/Users/chrisweekly/vbox/win10x64e/vbox-devnotes.md).`

This relates to e.g.
https://github.com/Microsoft/vscode/issues/3771
and even closer to
https://github.com/Microsoft/vscode/issues/26659
... but is specific to a bug in resolving the path to the linked file.
Possibly related to 
https://github.com/Microsoft/vscode/issues/27107
as well.

Please fix! Thanks! :)
Slainte,
CW

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:39:09.335Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.00GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
git-project-manager|fel|1.5.0
csharp|ms-|1.14.0
sublime-keybindings|ms-|3.0.3
JavaScriptSnippets|xab|1.5.0
markdown-all-in-one|yzh|1.1.2

</details>
Reproduces without extensions

**Comment by bryce-s** [comment]
I'm interested in tackling this, but unclear about the expected behavior for the ``~`` character. Should the resolution of ``~`` vary per the OS we're using?

It seems fixing the concatenation and returning just ``~/vbox/win10x64e/vbox-devnotes.md`` still leads to an unresolved home directory on MacOS.

**Comment by cweekly** [comment]
Thanks @bryce-s !  
> "Should the resolution of ~ vary per the OS we're using?"  

I'd think so -- but (forgive my ignorance here) if possible I think it'd be better not to introduce any custom handling here, but rather to rely on the user's extant settings for terminal integration? e.g. I've got user settings like this:
```
 "terminal.external.osxExec": "iTerm.app",
 "terminal.integrated.cwd": "/Users/chrisweekly",
```
and however my terminal handles a path like `~` should dictate what happens with these markdown links.

**Comment by mjbvz** [comment]
Actually, after thinking about this more, I don't think the current behavior should be changed.

VS Code currently treats markdown paths starting with `/` as being relative to the root of the workspace. This makes sense when dealing the documentation in most repos or for most markdown that will be hosted on a website. 

To write a truly absolute path, you can already use the `file:` protocol:

```md
[link](file:///Users/matb/Desktop/cat.gif)
```

However the file scheme does not support tildes and I don't think we should special case it either because that could result in non-portable markdown

**Comment by cweekly** [comment]
Thanks @mjbvz -- after reading your comment I actually agree.
FTR for me this was never about adding "~" support.
Using workspace-relative paths by default, and relying on `file:///` to reach other dirs, is perfectly reasonable. 
Thanks for your input -- you too @bryce-s!
Slainte,
CW
