### ISSUE TITLE
Workspace name disappears when adding file/folder

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#47474]
* have a workspace folder from a file system provider
* select it, select new file from the context menu
* the label turns blank

![apr-09-2018 11-24-47](https://user-images.githubusercontent.com/1794099/38490199-be16d10a-3be8-11e8-80af-7740cd08076e.gif)

**Comment by isidorn** [comment]
The issue is the following:
`FileViewletState` stores URI that needs to become an input box [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/electron-browser/views/explorerViewer.ts#L160)

It uses a `ResourceMap` for this.

So if my `/users/isidor/folder` needs to be renamed he stores that uri, if that folder needs a child to be created he stores `/users/isidor/folder/`. Note the `/` at the end.
@jrieken However sicne in your setup your root uri ends with a `/` those two cases are the same. So once you want to add a new child the rename is also triggered on the root and the new input box for the child happens. Due to blur effects the first rename closes and renames your root to empty string.

Will proabably refactor the FileViewletState to store objects not resource maps, investigating
