### ISSUE TITLE
Partially installed extension (Python Extension)

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/vscode#47518]
Issue Type: <b>Bug</b>

Over the past few months we ([Python Extension](https://marketplace.visualstudio.com/items?itemName=ms-python.python)) have had a number of issues being reported due to the fact that the extension has not been installed correctly. Basically some files are missing in the Python Extension directory, hence the extension does not work.

As a solution we just ask users to:
* Uninstall, Reinstall
* Or manually delete the Python extension folder and then re-install the extension

The extension is around 6mb, is this considered to be too large (I wouldn't have thought so).

This isn't similar to https://github.com/Microsoft/vscode/issues/27318
As the extension is deemed installed in VSC (after all, they are able to `uninstall` the extension, i.e. it is installed)

**Comment by sandy081** [comment]
@DonJayamanne There have been improvements and fixes in last couple of milestones to improve extension installation reliability. Some of them are 

- https://github.com/Microsoft/vscode/issues/43813
- https://github.com/Microsoft/vscode/issues/44471
- https://github.com/Microsoft/vscode/issues/47478

All of the above fixes make extension installation complete and reliable. I would assume this would be due to or dup of one of the above. Hence closing this as a dup.

I would request to please collect issues after updating to 1.23 (will be released in two weeks) and let us know if there are still such cases.

Thanks.
