### ISSUE TITLE
Feedback re: Latest Release and Search include/exclude patterns

### ISSUE THREAD

**Issue by EarthmanWeb** [Microsoft/vscode#47526]
- VSCode Version: 1.22
- OS Version: 10.13.4

Hi, love the editor - I am providing feedback in regards to this latest change to the "Search include/exclude patterns":
https://code.visualstudio.com/updates/v1_22#_search-includeexclude-patterns

I think this is a step backwards.  This is why:

Previously, I could use the 'Find in Folder' shortcut to search in a specific folder, or combinations, and RETAIN my exclusion settings as they were set in previous searches.  

NOW, in the single line view, I have to re-enter exclusions EVERY TIME I change search folders, which is very redundant and quite annoying!

Please consider changing this back, or having the option to split the two fields as they were before.

Thanks!

**Comment by roblourens** [comment]
I have https://github.com/Microsoft/vscode/issues/46315 for this.

For the "Find in folder" case, would it be more convenient if it added the new `./folder` pattern to the patterns input, instead of replacing the whole contents? Or less convenient since you would have to remove the old `./folder` pattern each time you switch folders?

If you have lots of exclusions present for a long time, you might want to add them to your search.exclude setting instead.
