### ISSUE TITLE
tasks.json change in the escape chars in args

### ISSUE THREAD

**Issue by 40tude** [Microsoft/vscode#47584]
Issue Type: <b>Bug</b>

Bonjour
I used to build my C++ code using a tasks.json looking like : 

.... 
{
            "label": "Build Test",
            "type": "shell",
            "command": "cl",
            "args": [
                "/MDd /W4 /EHsc /ZI /std:c++17 /Od",
                "/Fe:'${workspaceFolder}/Debug/test.exe'",
                "/Fd:'${workspaceFolder}/Debug/'", 
                "/Fo:'${workspaceFolder}/Debug/'",
                "main.cpp"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            }
        },
....
Read this page for more detail : See https://www.40tude.fr/blog/how-to-compile-cpp-code-with-vscode-cl/

Since this morning I need to write it as follow
...
{
            "label": "Build Test",
            "type": "shell",
            "command": "cl",
            "args": [
                "/MDd' '/W4' '/EHsc' '/ZI' '/std:c++17' '/Od",
                "/Fe:${workspaceFolder}/Debug/test.exe",
                "/Fd:${workspaceFolder}/Debug/", 
                "/Fo:${workspaceFolder}/Debug/",
                "main.cpp"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            }
        },

As you can see, now : 
1 - I need to replace spaces in the command string with ' '  
2 - I need to remove the ' and ' at the beginning and at the end of the paths

Is it an expected behavior?

Please let me know
Regards, Philippe

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T02:26:57.615Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|Memory (System)|15.85GB (8.39GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
mdmath|goe|2.2.1
python|ms-|2018.3.1
cpptools|ms-|0.16.1
rewrap|stk|1.8.1
cmake|twx|0.0.17

</details>

**Comment by dbaeumer** [comment]
@40tude we fixed bugs around not quoting args correctly in the latest release which was necessary to support proper variable replacement. So we warned for a while in the Output channel that shell task with space in the args are not supported and should me merged into the command since their execution might have failed. I apologize if I missed your case. To fix your problem you can simply merge command and args.

```json
"command": "cl /MDd /W4 /EHsc /ZI /std:c++17 /Od Fe:${workspaceFolder}/Debug/test.exe /Fd:${workspaceFolder}/Debug/ /Fo:${workspaceFolder}/Debug/ main.cpp"
```

or you split the args into single separate args like 

```json
"command": "cl",
"args": [
"/MDd",
"/W4" 
"/EHsc"
"/ZI",
"/std:c++17",
"/Od",
"/Fe:${workspaceFolder}/Debug/test.exe",
"/Fd:${workspaceFolder}/Debug/",
"/Fo:${workspaceFolder}/Debug/",
"main.cpp"
]
```

I would use the second option. It has the advantage that if for example `${workspaceFolder}` resolve to a value having space in it the task system will quote the arg correctly.

I tried to keep the changes we did in 1.22 non breaking but I have to admit I never thought about a use case where users use args to split up a command line into smaller readable pieces. I will look into making this more convenient in one of the next release by support a string[] for the command itself.

Is it OK for you to close the issue?

**Comment by 40tude** [comment]
Bonjour Dirk
OK to close the issue
Thank you very much for the lightning fast answer :-)
I will use the second option even if it is not my ideal choice (I now
understand the rational behind your choices)
Anyway...
Again thank you and please, continue the excellent job with VS Code



Cordialement, Philippe
// -------------------
40tude.fr

2018-04-10 22:05 GMT+02:00 Dirk Bäumer <notifications@github.com>:

**Comment by dbaeumer** [comment]
@40tude I will close the issue then. Have fun coding with Code :-)
