### ISSUE TITLE
editor.tabCompletion setting is ignored

### ISSUE THREAD

**Issue by dobegor** [Microsoft/vscode#47592]
- VSCode Version: 1.22.1
- OS Version: macOS 10.13.4

Steps to Reproduce:

1. Set `editor.tabCompletion` to `false`.
2. Press Tab when snippet suggestions comes on to move between function parameters. Snippet inserts instead.

Does this issue occur when all extensions are disabled?: Yes

Issue was introduced for me with the last update. Horribly annoying :( 
I.e. I'm typing h.RespondWithJSON, 
`h.RespondWithJSON(w http.ResponseWriter, status int, obj interface{})` comes with the first argument select, I type `w`, press Tab, and instead of going to next argument it inserts snippet with shorthand `wr`.

[GIF](https://media.giphy.com/media/8Z2dkxvu956ZXJQuJQ/giphy.gif)

**Comment by dobegor** [comment]
For now, I've workarounded this with the following settings:
```
"editor.tabCompletion": true,
"editor.snippetSuggestions": "top",
"editor.quickSuggestions": false
```
but 
1. I think it's a regression and it worth fixing / implementing #37826.
2. There's no way to discover snippets with these settings other than looking into their definitions.

**Comment by jrieken** [comment]
Please provide a snippet, the language, and the prefix in which this occurs

**Comment by dobegor** [comment]
@jrieken as shown in GIF (link in the issue first message), it's Go and the snippet is pretty much any function call.

**Comment by jrieken** [comment]
Sorry, GIF is complementary but not replacing the actual code snippet and snippet. You don't really expect me to play the gif and type along while you could simply copy&paste, right?

**Comment by dobegor** [comment]
@jrieken sure thing, was replying from mobile on the go.
Here's a snippet: https://play.golang.org/p/0NOrfcOhSuI

**Comment by jrieken** [comment]
Hm, I cannot reproduce. Generally, you shouldn't combine IntelliSense-as-you-type with snippet-tab-completion because they overlap. The tab-key accept the current suggestion but it also expands the current snippet. From what I understand you actually don't want snippets but you want the `w`-suggestion to be inserted. Is that correct? When you invoke IntelliSense after the w (or when just typing the w) what suggestion is preselected?

**Comment by jrieken** [comment]
> Is there any additional info I should provide?

Yes, please answer this question:  When you invoke IntelliSense after the w (or when just typing the w) what suggestion is preselected?

**Comment by dobegor** [comment]
The `wr` snippet one. However, as per settings:
```
// Insert snippets when their prefix matches. Works best when 'quickSuggestions' aren't enabled.
"editor.tabCompletion": false
```
It should not be completed when hitting tab.

**Comment by jrieken** [comment]
Sorry, I believe this was clear: "Generally, you shouldn't combine IntelliSense-as-you-type with snippet-tab-completion because they overlap."

It means there are *two* feature. Snippet-tab-expansion which works *without* the IntelliSense window visible and then there is IntelliSense which accepts the selected (visible) suggestion (must not be a snippet) when hitting tab. Use one of these settings

* "editor.suggestSelection" - control how suggestions in *IntelliSense* are pre-selected
* "editor.snippetSuggestions" - control if and how *snippets* are inter-mixed with *IntelliSense*
* remove the *keybinding* form `acceptSelectedSuggestion`
