### ISSUE TITLE
[sidebar]Double click new file make all files display grey

### ISSUE THREAD

**Issue by oDoraemon** [Microsoft/vscode#47606]
Issue Type: <b>Bug</b>

Double Click new file icon in sidebar get all files grey

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T02:26:57.615Z)

<details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.8
php-intellisense|fel|2.3.1
php-pack|fel|1.0.1
python|ms-|2018.3.1

</details>

**Comment by joaomoreno** [comment]
@isidorn Candidate?

**Comment by isidorn** [comment]
I can reproduce it and it is a regression.
However the issue is of cosmetic nature the explroer is gray and no other behavior is broken. Also the bad behavior goes away if a user clicks on a new file icon again or if he restarts vscode. 
Due to the above I belive this is not a candidate. @joaomoreno @bpasero let me know if you disagree and I can look into fixing it for the recovery

**Comment by isidorn** [comment]
This got introduced because we switched to use a map instead of an array for children.
So the NewStatPlaceholder would get ovewritten in the map.
Fix: made the new file / new folder actions noop when the parent is in the process of creating a new entry
