### ISSUE TITLE
path variables can't be updated unless restarting windows machine

### ISSUE THREAD

**Issue by donald001** [Microsoft/vscode#47651]
## steps to reproduce
1.  make sure the machine has no node installed, so the computer's path variables didn't include node.
2.  install nodeJS and it will add it's bin path to computer's path. check it by opening a console and input "node -v", the version appears.
3.  open vscode and open the console and type "echo %path%", the response doesn't contain the newly added nodeJS's path at all.
4.  restart the computer, and open vscode's console, type  "echo %path%", the new path is displayed.
## Problems:
Not only NodeJs, all other changings for path variable have the same issue:
In vscode, path variables can't be updated unless restarting windows machine.
## Expectation:
path variables can be updated without restarting windows machine

**Comment by mikevaleriano** [comment]
I don't suppose this is a vscode issue at all.

**Comment by joaomoreno** [comment]
Restarting the machine is OK.

**Comment by donald001** [comment]
But why the cmd console itself can update %path% without restarting the machine? Only VS code need to restart.

**Comment by mikevaleriano** [comment]
That's how it works on windows. It usually needs to restart for changes in PATH to take effect, and the installer warns you about it, if I'm not mistaken.

Sometimes you can just close and then restart the prompt to have the changes take effect, but it's not guaranteed. All in all, it's not a big deal, and it is expected behavior, so there really isn't a whole lot the devs can do about it.

Like stated above, restarting the machine is OK.

**Comment by buybackoff** [comment]
Standalone PowerShell and cmd do see updated path, e.g. after installing AWS CLI. It's very inconvenient to restart, sometimes it is not OK.
