### ISSUE TITLE
Плохо работает сочетание клавиш

### ISSUE THREAD

**Issue by shulgin-egor** [Microsoft/vscode#47650]
Issue Type: <b>Bug</b>

Не всегда срабатывает сочетание клавиш ctrl+` для вызова интегрированного терминала.

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T00:21:13.607Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz (4 x 1600)|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.31GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.3.1
cpptools|ms-|0.16.1
pdf|tom|0.2.0

</details>

**Comment by alexandrudima** [comment]
Google Translate:
> Bad keyboard shortcuts
> The combination of the keys ctrl + `does not always work for calling the integrated terminal.

@shulgin-egor What keyboard layout are you using ?

**Comment by shulgin-egor** [comment]
@alexandrudima Both Russian and English 
![image](https://user-images.githubusercontent.com/14257816/38781494-db68d158-40ee-11e8-8ce0-ec73c0aeb58b.png)

**Comment by alexandrudima** [comment]
@shulgin-egor Under the Russian keyboard layout, VS Code does not have any default keybinding for toggle terminal:

This is reflected in the background help page or in the `F1` list:
![image](https://user-images.githubusercontent.com/5047891/38811689-7a567a9a-418a-11e8-8d70-36a6efc27abd.png)

![image](https://user-images.githubusercontent.com/5047891/38811762-c03b8c26-418a-11e8-9a0a-9eb100665179.png)

---

Under the ABC keyboard layout, VS Code ships with `` ctrl+` `` as the default keybinding for toggle terminal:

![image](https://user-images.githubusercontent.com/5047891/38811861-036cdee6-418b-11e8-98a2-17e137f284b4.png)

---

I believe you might be switching between these keyboard layouts, and when you are using the ABC one, VSCode has a default keybinding, and when you are using the Russian layout, VSCode does not have a default keybinding. I haven't dug into it, but I believe this is because no regular key produces `` ` `` under the Russian keyboard layout.

If you wish to have a **stable** keybinding which does not modify when you change keyboard layouts, you can follow the steps in our documentation at https://code.visualstudio.com/docs/getstarted/keybindings#_keyboard-layout-independent-bindings
