### ISSUE TITLE
[c++] C & C++ Syntax Highlighting Issues

### ISSUE THREAD

**Issue by SE2Dev** [Microsoft/vscode#4769]
- VSCode Version: 0.10.11
- OS Version: Windows 7

## Issue 1:
In the following code (using C++ syntax highlighting), the string literal(s) are not highlighted at all.
This issue is exclusive to C++ syntax highlighting and does not occur with C syntax highlighting.

#### Code:
```
int main()
{
    printf("%s\n", "a string");
}
```

#### Result
![Bug Screenshot](https://raw.githubusercontent.com/SE2Dev/VSCode-BugExample/master/resources/c-vs-cpp.png "Bug Screenshot")

## Issue 2:
In custom tmLanguage based colorizers that reference source.c from within rules that begin with certain patterns, the inlined C highlighting is incorrect (this issue also applies to rules using source.c++ but does not occur in rules using source.js).

#### Code
(See https://github.com/SE2Dev/VSCode-BugExample)

#### Result
![Bug Screenshot](https://raw.githubusercontent.com/SE2Dev/VSCode-BugExample/master/resources/screenshot.png "Bug Screenshot")

**Comment by aeschli** [comment]
Hi @SE2Dev, thanks a lot for your great example project. It was very helpful understanding the issue.
I delivered a fix for the first issue.

The second one, however, is a known problem of the c grammar
The C grammar uses $base instead of $self to refer its own rules, as done in a block.
$base is the parent grammar, in your case the exampleLang grammar. So that's why you had to use start again inside a block
The c grammar does that as they assume that the parent grammar is a grammar like C++, that includes C to extend it.

http://textmate.1073791.n5.nabble.com/C-based-grammars-broken-for-embedding-restricting-base-reference-td25165.html
discusses this and recommend to use injection.

**Comment by SE2Dev** [comment]
Thank you very much. I thought the second problem might have had something to do with $base, but wasn't able to find any definitive information on it, the link you provided should definitely help.
