### ISSUE TITLE
Having so much red underlined code (errors) makes VSCode very slow to edit these files

### ISSUE THREAD

**Issue by sharno** [Microsoft/vscode#47758]
- VSCode Version: 1.22.1
- OS Version: MacOS 10.12.6

Steps to Reproduce:
(I'm using the Flow Language Support extension and mostly experience it when the extension marks a big bunch of code as having errors but this issue spans other files that have large amount of text with errors.)

1. Have a big amount of text underlined in red (having errors)
2. Performance of VSCode in this file becomes so slow to be able to edit this file

**Comment by alexandrudima** [comment]
@sharno Can you please give a very specific example, like a file which reproduces this consistently for you

**Comment by sharno** [comment]
@alexandrudima
I don't remember though how to reproduce it in other files without using Flow.
So, this is a dummy repo I made for this issue: https://github.com/sharno/vscode-performance-errors. You'll probably just need to do an `npm install` and install the `Flow Language Support` extension to make the errors appear in the editor

**Comment by alexandrudima** [comment]
I can reproduce some slowness. Each line has about 15 errors. i.e. there are 15 errors that span almost the entire file. The browser is a bit struggling to paint so many squiggles. Note the somewhat high Paint times:

![image](https://user-images.githubusercontent.com/5047891/38754899-f6738e84-3f63-11e8-95f8-10befbc0ddad.png)

To investigate if we could deduplicate error squiggles and have only one drawn per line instead of the current N overlapping.
