### ISSUE TITLE
Setting editor.formatOnSave does not work after update

### ISSUE THREAD

**Issue by isurugiu** [Microsoft/vscode#47837]
- VSCode Version: 1.22.2
- OS Version: MacOS Sierra 10.12.6

Steps to Reproduce:

Hi,

I have recently updated to Version 1.22.2 on my Mac but I am not able to disable the editor.formatOnSave. I have set it to false both on the workspace and user settings and also checked the extensions but neither of that lead to happiness.

Can anyone reproduce it on their ends?

Best,
-Iulian

Does this issue occur when all extensions are disabled?: Not sure how to do it on Mac

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.
