### ISSUE TITLE
Allow border top color in tabs

### ISSUE THREAD

**Issue by pahen** [Microsoft/vscode#47867]
Hi,

I would love to have the possibility to change the position of the active tab border to conform to the original Ayu theme in Sublime Text:
 
![screen shot 2018-04-14 at 10 28 55](https://user-images.githubusercontent.com/353888/38766175-ad886846-3fce-11e8-9ac1-ddbe9126635e.png)

It makes more sense to have the border in the top of the tab since it doesn't get so close with the editor text which can make it hard to spot sometimes like this example:

![screen shot 2018-04-14 at 10 33 45](https://user-images.githubusercontent.com/353888/38766230-61d45cf6-3fcf-11e8-87e3-4fdda8562e26.png)

Any thoughts on this?

**Comment by bpasero** [comment]
I would accept a (minimal) PR to get this in.

**Comment by mkavidas** [comment]
I'm looking to get involved in the project. This looks like a good jumping off point. Could I work on this as my first issue? If so any guidance on what I would need to do would be appreciated!

**Comment by bpasero** [comment]
@mkavidas maybe check how the current border `TAB_ACTIVE_BORDER` color (the one that appears below the tab) is used and go from there: https://github.com/Microsoft/vscode/blob/ben/editor/src/vs/workbench/common/theme.ts#L57

**Comment by mkavidas** [comment]
@bpasero Thank you for the help. by "introduce new color" would you like me to change the default color or add a new border for the top of the tab (with it's own color)?

**Comment by bpasero** [comment]
**Verify:** new colors `tab.activeBorderTop` and `tab.unfocusedActiveBorderTop`

**Comment by pahen** [comment]
Awesome @mkavidas :) But it probably needs some more tweaks to look really nice. At least for the Ayu theme. This is how it looks like now.

![screen shot 2018-05-14 at 11 04 22](https://user-images.githubusercontent.com/353888/39988017-967729a8-5766-11e8-8637-1b3e45a16674.png)

It would be nice if we can get rid of the empty space above and on the side of the border
I think it's the transparent border on the tabs that messes it up.

**Comment by pahen** [comment]
Would it be possible to use `border-top` instead of `box-shadow` maybe?

![screen shot 2018-05-14 at 11 17 52](https://user-images.githubusercontent.com/353888/39988747-7762d704-5768-11e8-87ab-4fe01473cef5.png)

**Comment by isidorn** [comment]
I verified that these colors are added however I agree with @pahen that they should be 1px to the top to actually be useful.
Apart from that `unfocusedActiveBorderTop` seems like a misleading name, since if I focus in the explorer this color is not used. It is only used when some other group has focus. Feels weird

Due to the reasons above reopening

**Comment by bpasero** [comment]
Will revisit this when I push the grid work.

**Comment by bpasero** [comment]
This is how it will look like with the grid changes:

![image](https://user-images.githubusercontent.com/900690/40833559-853ed8f8-658e-11e8-9b88-464b9fa49769.png)

The thickness is different due to https://github.com/Microsoft/vscode/issues/50933

@isidorn can you explain this:

> Apart from that unfocusedActiveBorderTop seems like a misleading name, since if I focus in the explorer this color is not used. It is only used when some other group has focus. Feels weird

**Comment by isidorn** [comment]
Sure. 
1. use the `unfocusedActiveBorderTop` color customization
2. Have one group. Click in the explorer
3. Notice your color customization is not applied. Because in your world the group is still active. However the name is `unfocused` thus I would expect it to be applied since the focus is in the explorer and not in my group

**Comment by bpasero** [comment]
@isidorn yeah this is a problem with how to name things:
* a group can be active or not
* a tab can be focused or not

In order to not use active twice, I decided to call the one thing "focused" and the other thing "active". I fear we cannot change this now as the color keys have been used like that since the beginning.

**Comment by isidorn** [comment]
@bpasero thanks for the explanation. Yeah, let's live with it
