### ISSUE TITLE
emmet not work on inline script type="text/html" again

### ISSUE THREAD

**Issue by hyingreborn** [Microsoft/vscode#47870]
emmet not work on inline script in HTML files

it work:

div 
tab->
<div></div>
not work:

<script id="xx" type="text/html">
div
tab->
div
</script>

VSCode Version: newest 1.22.2
OS Version: win10/mac os serria

**Comment by hyingreborn** [comment]
@ramya-rao-a hi，you remove the code in this commit..

**Comment by ramya-rao-a** [comment]
@hyingreborn Yes, this feature got reverted when we moved the emmet completions in html files to the the html extension. We are reverting this move (https://github.com/Microsoft/vscode/issues/28545#issuecomment-383453951) which will bring back the completions inside the script tag with html type.

This issue is fixed with https://github.com/Microsoft/vscode/commit/79a2512769762928f089e4fd0b84764e37a1ce0d and https://github.com/Microsoft/vscode/commit/c314388da21720d893e7a36345e1cac36d1cfd5f
