### ISSUE TITLE
"Stage Changes" command should be called "Add"

### ISSUE THREAD

**Issue by jameshfisher** [microsoft/vscode#47876]
There are many Git commands listed in the command palette, but the only result for "add" is "Add file to .gitignore". This is not what I want. I want the equivalent of `git add $CURRENT_FILE`. Such a command is provided, for example, by [the git-plus extension to Atom](https://atom.io/packages/git-plus).

[I eventually stumbled over the answer](https://stackoverflow.com/a/49834123/229792): Visual Studio Code confusingly calls this command "Stage changes". This is not what a Git user would be searching for, as it deviates from Git terminology.

This command's name should be changed to "Add", or "Add" should at least be an alias for this command.

**Comment by joaomoreno** [comment]
Both terms actually work. "Add" is the command line verb. It comes from "add the file to the index".

But git also uses the staging area terminology: you can stage files, which basically means adding them to the index. It's even in the official book: https://git-scm.com/book/en/v2/Git-Basics-Recording-Changes-to-the-Repository

It's a bit too late to change this, as we'd just get other issues pulling into the opposite direction, so I'm going to have to close this.

**Comment by yume-chan** [comment]
@joaomoreno How about add an alias for `add`?

**Comment by pumpkinlink** [comment]
I agree with @yume-chan 's idea, I like how, for instance, in Ubuntu Unity you can open the Dashboard and type `excel`, and the LibreOffice Calc app will show up on search. 

That is because it's `.desktop` file has this line inside it with keyword metadata:
``` desktop
Keywords=Accounting;Stats;OpenDocument Spreadsheet;Chart;Microsoft Excel;Microsoft Works;OpenOffice Calc;ods;xls;xlsx;
```

If you search for `baobab`, the "Disk Usage Analyzer" icon will show up, and if you type `disks`, the icon for "Disks" (gnome-disks) will show up, even if your system is not set up to English ("Discos" in my case).

Another good example: if you assign a nickname for one of your contacts on Android, even though only the first and last name are visible in the main listing, the nickname will still be considered for search, and also the middle name, etc.

**Comment by kanlukasz** [comment]
Everywhere git add works like git add. Here in VS not. 
It's ridiculous!
