### ISSUE TITLE
VS Code doesn't fill whole screen estate

### ISSUE THREAD

**Issue by glekner** [microsoft/vscode#47905]
- VSCode Version: Version 1.22.2 (1.22.2)
- OS Version: macOS 10.13.4

I noticed that about 1px is not being used by Code as the picture suggests:

<img width="1404" alt="screen shot 2018-04-15 at 14 48 54" src="https://user-images.githubusercontent.com/24938324/38778117-9a538e7e-40bc-11e8-9b46-d76e91204c1f.png">

This really hurts my eyes, i'm using BetterSnapTool to maximize windows so i'm sure it takes all the available screen estate

Steps to Reproduce:

1. Maximize a window behind code and notice about 1px of it when Code is maximized

Does this issue occur when all extensions are disabled?: Yes

EDIT: If I resize the dock Code resizes correctly, so i'm not quite sure how to reproduce. would like some info on this, ill do more research.

**Comment by gilad215** [comment]
@alexandrudima Do you use macOS? Can you reproduce?

**Comment by varadero** [comment]
I have the same exact problem with the following version (with title bar style set to custom):
```
Version: 1.27.0-insider (user setup)
Commit: 7b9afc4196bda60b0facdf62cfc02815509b23d6
Date: 2018-09-03T09:14:29.879Z
Electron: 2.0.7
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

"window.titleBarStyle": "custom"
```

I use my Windows 10 task bar location at the left side and when I maximize VS Code Insiders and move my mouse to the vary bottom, I can see "SizeNS" mouse cursor. Very uncomfortable for someone that wants to click something on the status bar (for example starting a debug task, switching Git branches and everything that status bar provides), because in order to reach something at the (bottom) end, the user simply moves the mouse at that position and expects it to automatically stop at the end (so he does not need to worry about where the end is exactly). I don't have this problem when I set:
```
"window.titleBarStyle": "native"
```

So the reason should be the title bar style "custom".

Look at the picture, the red arrow shows how my mouse cursor looks like ("SizeNS") while I move my mouse to the very bottom of the screen.

![vscode-mazimized-bug](https://user-images.githubusercontent.com/7610713/45032297-2939d000-b05a-11e8-920e-ee204632051d.gif)

**Comment by domiSchenk** [comment]
I also have this problem but on Windows 10 only with custom title bar style.

1. VS Code has to be maximized.
2. Drag it to the second monitor at the top so it gets full-screened
3. Happens around every 2nd/3 times
  also happens when double click, but as previous not every time

![image](https://user-images.githubusercontent.com/6347221/45148396-75565300-b1c7-11e8-8752-4721c95142a1.png)

**Comment by InKahootz** [comment]
I'm getting this white bar at the top too on every other maximize. It's about 10px wide.

Windows 10 v1803
VSCode 1.28.0
