### ISSUE TITLE
How get my own and exsiting CompletionItems in vscode

### ISSUE THREAD

**Issue by raphael2711** [Microsoft/vscode#4791]
- VSCode Version:0.10.11
- OS Version:

I try to get my own and all exsiting Completion Items.
I create a plugin and implemant the Completion Items Provider.
But my problem now is that i only can see my created item.

provideCompletionItems(document: vscode.TextDocument, position: vscode.Position, token: vscode.CancellationToken): Promise<vscode.CompletionItem[]> 
    {
        return new Promise((resolve, reject) => { 
        var completionItems:vscode.CompletionItem[] = [];
        
          var t3 = new vscode.CompletionItem("myValue");
                    t3.kind = vscode.CompletionItemKind.Value;
                    t3.insertText = "myValue";
                    t3.filterText = "myValue";
                    
                  completionItems.push(t3);
                      return resolve(completionItems) ;
                    });
    }
},".")

**Comment by jrieken** [comment]
> I try to get my own and all exsiting Completion Items.

@raphael2711 By _all existing Completion Items_ do you mean the default textual completions?

**Comment by raphael2711** [comment]
Yes i mean the default  textual completions.

**Comment by jrieken** [comment]
That the current design. When a more specific completion provider returns a non-empty result, less specific completion providers won't be checked anymore. We do that because we assume the provider is more accurate in that case.

**Comment by raphael2711** [comment]
Thank's

**Comment by atishay** [comment]
It seems the other completion items are not triggered even if I throw and exception for my trigger character.

**Comment by rnemec** [comment]
@jrieken - Please reopen this: since there are many current providers of completion (own snippets, plugin snippets, intellisense, Typescript completions, plain word completions) as well as the recent favorite: all-autocomplete (plugin that does word completion using all open buffers - addressing missing vscode feature #5312). But when the plugin provides its list of words it completely replaces all the other things (snippets, intellisense, etc).
