### ISSUE TITLE
Sidebar opens whenever I focus on one of the editors

### ISSUE THREAD

**Issue by stoplion** [Microsoft/vscode#47933]
- VSCode 1.22.2
- OS X

Steps to Reproduce:

1. Focus on an editor
2. The sidebar opens

**Comment by bpasero** [comment]
@stoplion any more steps, are you just clicking into an editor with the mouse? Can you share a screencast how this looks like?

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.
