### ISSUE TITLE
Output channel should support id and display name

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#4794]
In addition it would be nice if we change the API to have a Channel object. When calling Append on it it happens the message. I often forget the first arg which is the id right now.

**Comment by dbaeumer** [comment]
@bpasero FYI.

**Comment by bpasero** [comment]
:+1:

**Comment by isidorn** [comment]
Closed via a big output refactoring that just got pushed to master.
@bpasero I would appreciate a quick code review, at least the interface structure in [output.ts](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/output/common/output.ts#L88)

**Comment by bpasero** [comment]
Will do, thanks!

**Comment by bpasero** [comment]
@isidorn some feedback:
* there are many places now where you do getOutputChannel().doSomething(). I suggest instead to put the output channel as a variable of the object where it is used and just use it from there. this prevents having to get the output channel all the time
* instead of getContents() on the output channel I suggest to have a get property (not a function) "output" or "contents" that returns the contents of the channel
* wherever we show the output channel to the user you seem to use the ID of the channel and not the label. I think the idea was to always use the label (e.g. ARIA label, dropdown label)
