### ISSUE TITLE
Fails to render completion details

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/vscode#47988]
Issue Type: <b>Bug</b>

* Clone https://github.com/ackvf/vscode-auto-import
* Go to `SignIn.tsx`
* Start a new line at the bottom and type `Account`
* Expected completion details to show up, but there are none.

![account](https://user-images.githubusercontent.com/19274678/38828693-a91d6da8-416b-11e8-977c-0ba2efb2a510.jpg)

*Based on `tsserver.log` we are sending the details, they are just not being rendered:
```
Info 402  [11:42:52.145] response:
    {"seq":0,"type":"response","command":"completionEntryDetails","request_seq":60,"success":true,"body":[{"name":"Account","kindModifiers":"export","kind":"class","displayParts":[{"text":"class","kind":"keyword"},{"text":" ","kind":"space"},{"text":"Account","kind":"text"}],"documentation":[],"tags":[],"codeActions":[{"description":"Import 'Account' from module \"~/pages\"","changes":[{"fileName":"/home/andy/sample/vscode-auto-import/src/pages/Auth/SignIn.tsx","textChanges":[{"start":{"line":2,"offset":1},"end":{"line":2,"offset":1},"newText":"import { Account } from '~/pages';\n"}]}]}],"source":[{"text":"~/pages","kind":"text"}]}]}
```

* Hit backspace and ctrl-space to bring completions up again, and it will work.

VS Code version: Code - Insiders 1.23.0-insider (2227c70736ecaf2e1dd027be9fc6198d542a95ab, 2018-04-16T09:45:56.409Z)
OS version: Linux x64 4.13.0-37-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.63GB (1.85GB free)|
|Process Argv|/usr/share/code-insiders/code-insiders .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
typescript-javascript-grammar|ms-|0.0.39

</details>

**Comment by mjbvz** [comment]
@jrieken The TS extension is also never asked to resolve the completion item in this case. This seems related to emmet somehow. It does not happen in a normal *.ts file or if you disable emmet

**Comment by jrieken** [comment]
It the widget that calls `resolve`, not sure why. @ramya-rao-a?

**Comment by ramya-rao-a** [comment]
@jrieken `resolve` is getting called on the suggestion item, but the call never makes it through the extension host to the relevant extension. It gets stopped at https://github.com/Microsoft/vscode/blob/73f64b93127e0d297c98db2901d879ce73325c7f/src/vs/workbench/api/node/extHostLanguageFeatures.ts#L620-L623

The cache is cleared out due to https://github.com/Microsoft/vscode/blob/4ebe8217293726edfe29f4437cde0975cbfa3152/src/vs/editor/contrib/suggest/suggestModel.ts#L344-L345 which ends up calling https://github.com/Microsoft/vscode/blob/73f64b93127e0d297c98db2901d879ce73325c7f/src/vs/workbench/api/node/extHostLanguageFeatures.ts#L643-L645

This only happens, when there are multiple completion providers and one of them returns an incomplete list

**Comment by jrieken** [comment]
👏 that's one deep investigation. Thanks @ramya-rao-a
