### ISSUE TITLE
Define compatible platform for extensions

### ISSUE THREAD

**Issue by alefragnani** [microsoft/vscode#4801]
It would be interesting to be able to define the platforms (Windows, Linux, Mac) that an extension is _compatible_, and then, be filtered in `Command Palette`, to present only the compatibles.

Sometimes the extension is developed explicit for specific platforms, and sometimes it is not ready (yet) for all platforms, or present temporary issues, and could be _turned off_ until it is fixed. 

Thanks in advance

**Comment by bgse** [comment]
A problem I can see with this is that it could encourage to take the easy way out. Given most extensions probably start out as a tool someone needs for their personal use, I could already see my lazy self:

"Hmm, this will probably run on Windows just fine, but I should test it first."

Now testing it will require me to reboot my computer, but because I am a lazy person I just mark the extension as incompatible and be done with it. It already does everything I personally need it to do after all.

Since Windows users do not even see the extension, there is little chance for a PR to come in, or even just a comment like "it works without problems, just mark it as compatible".

Not saying I can't see your point of view, just there is the potential of such a thing ending up being harmful to the extension ecosystem.

**Comment by alefragnani** [comment]
I understand your point, but I think that the same way that a _lazy_ developer could choose the easier path and activate and extension only for selected platforms, he/she could publish an unfinished extension  with _known issues_, and maybe, never fix it.

At least being able to define compatible platforms, it prevents the users from installing extensions that will not work.

**Comment by joaomoreno** [comment]
@modigrv Is there any such concept? Maybe accessible through version properties, which vsce would properly map from our `package.json`?

**Comment by modigrv** [comment]
Sent the request to Marketplace PM.

**Comment by hamenon** [comment]
We don't have support for adding platform dependency in the manifest on Marketplace. Primarily because the current thinking is the extension _should_ ideally be supported on all platforms that the product is supported. But yes I have seen a few instances of where an extension is supported only on particular platforms. Will work with @waderyan to see what can be done here.

**Comment by fabiospampinato** [comment]
This would be useful, I made some extensions that interact with apps that are macOS-only (like Finder), there's no point in installing said extensions for a non-macOS. Currently if an extension defines a keybinding for mac, one for non-mac systems must be provided as well, which doesn't make sense in these scenarios.

**Comment by nschonni** [comment]
Another example of stuff like native modules only being required on particular platforms in fsevents https://github.com/strongloop/fsevents/blob/master/binding.gyp#L6
For native/C++ NodeJS stuff, it is expressed through the binding.gyp
