### ISSUE TITLE
TextDocument.insert unintentionally moves cursor to end of file when ...

### ISSUE THREAD

**Issue by remcoros** [microsoft/vscode#4802]
- VSCode Version: 0.10.11
- OS Version: Windows 10

Steps to Reproduce:

See: https://github.com/editorconfig/editorconfig-vscode/issues/40 for more info and a screenshot
1. Install editorconfig extension and create a .editorconfig file
2. set insert_final_newline = true
3. enable auto-save in vscode (using a delay)

This issue only occurs when the cursor is at last line, last character of the file when the 'TextEditor.insert' is called. After the insert, the cursor is moved to the end of the file (now with one more line, the last newline).

This does not happen when the cursor is at any other location in the file.

E.g. set auto-save delay to 5000 (easier testing).

Remove any content from the end of the file (so editorconfig will insert a newline) and (before auto-save kicks in) move the cursor a few places up.

the newline is added, and the cursor (and intellisense) are untouched.

I first tried fixing this inside editorconfig itself, by saving the current selection before any inserts, then restoring that selection after the save, but it does not have an effect. 

Also, because this does not happen when the cursor is not at the end of the file, it looks like an issue with vscode.

And also, I don't think it's appropriate for an extension to fiddle with cursor positions after an edit/insert. This should be handled by vscode (Since intellisense could be visible at the time of the insert/edit).

**Comment by SamVerschueren** [comment]
Don't need to set `auto-save` to test this. Just make sure `insert_final_newline` is set to `true` in `.editorconfig`. Create a new file. Type in some lines and make sure the cursor is at the end of the file( the last position possible) and save the file. Cursor will jump to the next line.

// cc @alexandrudima

**Comment by remcoros** [comment]
This might have something to do with the handling of the "virtual" last line. It's not a real line until it has content and it's own line ending. But from an editor's perspective, it is an empty line to render and show.

**Comment by alexandrudima** [comment]
I will double check in this specific case, but the general idea is that the cursor moves when the document is edited from an extension.

e.g. if the cursor is at the second line and an extension inserts 20 lines at the top of the file, the cursor will go to the 22nd line.

(I call this side-editing):
https://github.com/Microsoft/vscode/blob/5ba4f734dfaca254fe40354a27f1cfcffc1b75ec/src/vs/editor/test/common/commands/sideEditing.test.ts#L54

**Comment by SamVerschueren** [comment]
@alexandrudima In that case, I understand that the cursor is moved. But I'm not quite sure about the use case of adding a new line at the end of a line. I wrote a test for it, but am having issues installing the npm dependencies of vscode.

```js
test('insert at end of file', () => {
	testCommand(
		[
			'first',
			'second line',
			'third line',
			'fourth'
		],
		new Selection(4, 7, 4, 7),
		[
			EditOperation.insert(new Position(4, 7), '\n')
		],
		[
			'first',
			'second line',
			'third line',
			'fourth',
			''
		],
		new Selection(4, 7, 4, 7)
	);
});
```

This test will fail because the cursor will go to the 5th line, right? Maybe it's an idea that it should be possible to insert at `line.length + 1`. In this case `new Position(4, 8)`. This indicates that it inserts AFTER the cursor and not in front of the cursor.

Another idea is of adding an API method for inserting an empty line.

**Comment by SamVerschueren** [comment]
Any feedback on this issue? I would be happy to look into it if we discussed on how to solve the issue.

**Comment by SamVerschueren** [comment]
I did a screencapture to see what it would look like if I put the cursor back into it's original position after the newline gets added.

![cursor-position](https://cloud.githubusercontent.com/assets/1913805/19339472/db193fe8-9123-11e6-950f-4924afcf92f6.gif)

Although it is a solution, it's not perfect.

**Comment by alexandrudima** [comment]
@SamVerschueren 

Indeed, given a selection at (x,y) there is no way in the API to **hint** insert text at (x,y), but also keep selection at (x,y).

i.e.:
* we have `TextEditorEdit.insert` which moves the resulting selection to after the inserted text.
* we have `TextEditorEdit.replace` which expands the resulting selection to contain the inserted text.

This is due to the different `forceMoveMarkers` values: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/node/extHostEditors.ts#L246

There remains only the option of explicitly setting the cursor position after the edit has applied (i.e. in the `then` callback) or optimistically immediately after the edit has been sent our way (i.e. below the `textEditor.edit` call, but not in the `then` of the returned promise).

Since recently, there is a new option, to create a save participant. Since that would go through the same code-path, I'm not sure if it would help terribly:

https://code.visualstudio.com/updates#_format-on-save
![image](https://cloud.githubusercontent.com/assets/5047891/19853486/c4851d16-9f69-11e6-9e26-7795df0279b8.png)

**Comment by alexandrudima** [comment]
Another example (from #43000)

* `package.json`
```js
{
    "publisher": "alex",
    "name": "43000",
    "version": "0.0.0",
    "engines": {
        "vscode": "^1.0.0"
    },
    "activationEvents": [
        "*"
    ],
    "main": "index.js"
}
```

* `index.js`:
```js
const vscode = require('vscode');

exports.activate = function () {
	const editor = vscode.window.activeTextEditor;

	// Get the document last line.
	const lastLine = editor.document.lineAt(editor.document.lineCount - 1);

	// Select the last document char.
	editor.selections = [new vscode.Selection(
		lastLine.lineNumber,
		lastLine.text.length - 1,
		lastLine.lineNumber,
		lastLine.text.length
	)];

	// Insert 'ADDED_STRING' at the end of the editor.
	editor.edit((editBuilder) =>
		editBuilder.insert(
			new vscode.Position(lastLine.lineNumber + 1, 0),
			'ADDED_STRING'
		)
	);
}
```

![image](https://user-images.githubusercontent.com/5047891/38986656-5d4e672e-43cd-11e8-9386-e13dd092592a.png)


![image](https://user-images.githubusercontent.com/5047891/38986644-53de2512-43cd-11e8-8fa9-da226acab266.png)
