### ISSUE TITLE
Provide a deterministic method of associating the task execution with the terminal instance

### ISSUE THREAD

**Issue by alpaix** [Microsoft/vscode#48032]
Issue type: **Feature Request**

For our extension, we need an API to associate task execution instances with terminal instances that are used for rendering task output.
If that's not possible to implement, we'd need a method for determining a category of each terminal instance. This API would help us identify a subset of terminals being used for rendering task outputs.

//cc @dbaeumer @Tyriar

**Comment by alpaix** [comment]
Follow up on a discussion started in #46192.

**Comment by dbaeumer** [comment]
One thing that should be noted is that there is the concept of a composite task which simply spawns n other tasks. A composite task has no own command and therefore when executed can't provide a process id (since it doesn't spawn a process). So the processId for a task in the API can only be optional.

**Comment by Tyriar** [comment]
@alpaix can you go over the exact case you need this for? It wasn't clear to me from the other discussion. Is this for the case where VS Code is the host, launches a task and the task output needs to be sent not to a terminal but to some task output pane in a VS guest?

**Comment by alpaix** [comment]
@Tyriar Based on an earlier proposal we're trying to pursue a unified model of task output sharing. The host IDE will provide an API to enumerate terminals used for rendering task outputs along with an API to read/write from these terminals. Our extension will take care of mirroring terminals' content. In case of VSCode being a host, we're planning to share task-specific built-in terminals only, mostly because of different permissions needed for sharing interactive terminals. Given that limitation, we'd wanted to be able to identify which terminals are used for terminals. This could be done either by associating task execution with a terminal instance or by having a terminal category or similar.

Thoughts?

**Comment by alpaix** [comment]
@dbaeumer In case of a built-in terminal used for task outputs what process ID would be provided?

**Comment by dbaeumer** [comment]
@alpix the process id of the shell running the command. E.g. the same as `Terminal#processId`.

Actually if you only need to have terminal groups then I would propose that we have the API on the terminal. Something like:

```
enum TerminalGroup {
   Interactive, Task
}
```

**Comment by Tyriar** [comment]
Here is the current thinking on my side:

```ts
export namespace window {
    export interface Terminal {
        type: TerminalType;
    }

    export type TerminalType {
        Interactive,
        Task
    }
}
```

As for whether we need to associated a task with a terminal I'm still not sure. If we do I think this would be @dbaeumer providing this API, something along the lines of:

```ts
export namespace window {
    export class Task {
        terminal: Terminal;
    }
}
```

Or:

```ts
export namespace window {
    export class Task {
        processId: Thenable<number | undefined>;
    }
}
```

We cannot have an API on `Terminal` that gives the task as the tasks part has a dependency on the terminal part, not the other way around.

**Comment by Tyriar** [comment]
> We cannot have an API on Terminal that gives the task as the tasks part has a dependency on the terminal part, not the other way around.

@dbaeumer perhaps the eventual terminal type API shouldn't exist at all because of this? This will be the first task-specific API in the terminal within VS Code. My implementation will probably just check `waitOnExit` for now.

I'm leaning more towards just this in the long term to enable getting a list of task terminals and being able to link them:

```ts
export namespace window {
    export class Task {
        terminal: Terminal;
    }
}
```

**Comment by alpaix** [comment]
According to the current VSCode task execution model, task terminals can be shared across different task executions. Meaning, the same task could be associated with various terminal instances at different point of times. So I think it'd be more practical to add `terminal` property to the `TaskExecution` class. Alternatively, `terminal` property could also be placed in `TaskStartEvent`.

I like the idea of having `TerminalGroup` categories. It's beneficial to our extension to distinguish a  terminals based on the group property.

**Comment by Tyriar** [comment]
> So I think it'd be more practical to add terminal property to the TaskExecution class. 

@alpaix that's what I meant, I haven't used the task API yet 😄

**Comment by dbaeumer** [comment]
@Tyriar 

> @dbaeumer perhaps the eventual terminal type API shouldn't exist at all because of this? This will be the first task-specific API in the terminal within VS Code. My implementation will probably just check waitOnExit for now.

I agree and the whole underlying problem is that neither you nor me want to expose implementation details. That tasks use terminal as an execution engine is something I don't want to have in the API either :-) especially since there are still old tasks that don't even run in the terminal (but for LiveShare I think we need to ignore this). This is why I opted for a processId since the stable thing around tasks is that they are executed via processes (with the exception of composite tasks)

Since we split the terminal into a renderer and the tty engine I can even think about using a terminal for output that is not bound to a process. So having an indication on a terminal what is is used for might not be a bad idea. But may be that shouldn't be something you infer. It should be something tasks passes into the terminal instance.

Regarding:

> Meaning, the same task could be associated with various terminal instances at different points of time. So I think it'd be more practical to add terminal property to the TaskExecution class. Alternatively, terminal property could also be placed in TaskStartEvent.

This is exactly the opposite. A task when executed is always bound to one terminal. However tasks reuses terminal (renderers) and the same terminal can be used for different task runs.

**Comment by alpaix** [comment]
@dbaumer I'm probably missing something. 
> This is exactly the opposite. A task when executed is always bound to one terminal. 

The same task could be executed in different terminals. For instance, when the terminal instance used earlier was either closed by a user or is busy rendering some other task. Do you say `terminal` property value of the task would change after each execution?

**Comment by Tyriar** [comment]
After chatting with @dbaeumer in Slack we're leaning towards adding a processId in the task APIs. Then you will be able to compare with Terminal.processId to get the mapping.

**Comment by Tyriar** [comment]
@alpaix you should be able to map tasks with their terminals fairly reliably already by listening to the proposed APIs: `window.onDidOpenTerminal` and `workspace.onDidStartTask`, similar to the code sample in https://github.com/Microsoft/vscode/issues/46192#issuecomment-381597261.

**Comment by dbaeumer** [comment]
@alpaix I misunderstood your statement. Just to clarify: a task execution is bound to exactly one terminal. When a task execution is bound to a terminal the terminal can not serve any other task. The same terminal renderer can server n different task execution in sequence. If a task is executed 2 times it might or might not use the same terminal renderer.

One thing to add for the processId. The id will be `undefined` for tasks that are not bound to a process / shell. These tasks don't generate any output right now.

**Comment by dbaeumer** [comment]
I added corresponding API to monitor the process start / end of a task. I will close the issue. Please ping if you think there is still work to do.
