### ISSUE TITLE
Support mkdirp when saving files

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#48062]
There are scenarios, like creating `.vscode/launch.json` that assume we always run `mkdirp`-logic first. While that make sense for new files it doesn't make sense for files we have opened before, e.g. files users edit. Too address these scenarios I have added `IUpdateContentOptions#mkdirp` and the `RemoteFileService` honours that flag, the default file service always runs `mkdirp` I believe (cc @bpasero).

**Comment by bpasero** [comment]
@jrieken @weinand what is the scenario in debug where this is relevant. e.g. if we keep doing `mkdirp` for any `file://` operation as before, what is the issue from that behaviour?

And who would set `mkdirp` to `false` currently or where would we want to add it?

**Comment by weinand** [comment]
@bpasero for debug there is no issue. The problem is that debug was relying on "mkdirp" when creating ".vscode/launch.json". But the remote filesystem provider doesn't use "mkdirp", so our code was failing there.

**Comment by bpasero** [comment]
@jrieken I think that depends. the file you have opened could have been deleted (including its parent folders) and our current behaviour is to restore the full path and file when you save it. Otherwise the behaviour would be weird:
* make a file dirty
* delete it on disk and its parent folders
* save it
=> you would get an error if `mkdirp` was set to `false`

**Comment by jrieken** [comment]
We now do that...
