### ISSUE TITLE
'Not Showing X further errors and warnings' includes suggestions in count

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#48082]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Install `typescript@next`
2. Select this as your workspace typescript version
3. Open the attached file as javascript [manyUnused.txt](https://github.com/Microsoft/vscode/files/1922002/manyUnused.txt). You should see `...` suggestions on each of the consts. 
4. Open problems panel

**Bug**
The problems panel shows none of the suggestions but still says `Not showing 87 further errors and warnings`

Does this issue occur when all extensions are disabled?: Yes

**Comment by sandy081** [comment]
@mjbvz I see following

![image](https://user-images.githubusercontent.com/10746682/38932463-8e50f452-4316-11e8-8ca6-885d5ca8292f.png)

Problems panel shows the existing markers in the system. It seems there is a marker with message `Not Showing 89 further errors and warnings`. Hence it is shown. 

Not sure what is the bug here

**Comment by mhegazy** [comment]
> Not sure what is the bug here

the bug is that the suggestions are not shown in the error list. yet, the list says it is not showing them and 89 errors.
I  think this count should filter the suggestion diagnostics.

**Comment by jrieken** [comment]
with https://github.com/Microsoft/vscode/issues/49687 we have made this of severity info
