### ISSUE TITLE
Source control stop to work when the change contains a big XML file

### ISSUE THREAD

**Issue by yhvicey** [Microsoft/vscode#48105]
- VSCode Version: 1.22.2
- OS Version: Windows 10 16299.371

Steps to Reproduce:

1. Init a repo with a big XML file (~3600 lines)
2. Make some change to this XML file and source control will show nothing.

Does this issue occur when all extensions are disabled?: No

Please contact me on lync (yiwwan) if you need extension list and the xml (dsv) file.

**Comment by joaomoreno** [comment]
Can you reproduce with any other file?

What do you mean by "source control will show nothing"? Can you share a screenshot?

After modifying the file, what does `git status` return?

**Comment by yhvicey** [comment]
![capture](https://raw.githubusercontent.com/yhvicey/TempStore/master/capture.gif)

Usually if I click any file in Source Control page VSCode will show diff page automatically but if the change contains a huge xml file it will do nothing.

**Comment by joaomoreno** [comment]
Can you open the Developer Tools, Console? What errors appear there?

**Comment by yhvicey** [comment]
I'll try to repro it.

**Comment by dermoench42** [comment]
probably related:
https://github.com/DotJoshJohnson/vscode-xml/issues/122#issuecomment-391933359

When trying to open a huge xml file the xml formatter refused to work because vscode runs in some execution timeout. So the file isn't detected as xml file and all related and dependent functions doesn't work.

For working with huge files it might be usefull either to configure those timeouts or to turn it of on demand with something like a 'force' flag.

ervin

**Comment by joaomoreno** [comment]
ping @yhvicey
