### ISSUE TITLE
Intellisense VSCode for React Native its very slow, and not working after a minute code

### ISSUE THREAD

**Issue by byteskw** [Microsoft/vscode#48113]
- VSCode Version: new version
- OS Version: windows 10 x64 edu

Steps to Reproduce:

1. why my intellisense in vscode always loading? please help me, im using react native 

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
@byteskw Please do not post "me too" comments on multiple other issues.

Regarding your problem:

1. Does this reproduce in a vscode insiders build with all extensions disabled?
1. Does the workspace have a `jsconfig.json` / `tsconfig.json`?
1. Does this happen in other workspace or just this one?
1. What is the structure of your workspace?
1. Is there a specific action that seems to tigger this?

**Comment by byteskw** [comment]
@mjbvz i'm sorry for reply "me too" commnet on multiple other.

1. Does this reproduce in a vscode insiders build with all extensions disabled? yes
2. Does the workspace have a jsconfig.json / tsconfig.json? i dont know, how if i want add jsconfig.json / tsconfig.json ?
3. Does this happen in other workspace or just this one? yes
4. What is the structure of your workspace? sturcture what? i'm use react native cli 
5. Is there a specific action that seems to tigger this? no, i'm just unistall vscode full deleted extension, and install again, and back to always loading intellisense

**Comment by bradmartin** [comment]
@byteskw - I've recently been hitting this with latest version on a very large monorepo project with Angular. I disabled extensions, turned logs on and the service was just failing no matter what. Long story short, talked to some friend who has worked on large angular projects and ran into this as well. Suggested the following: https://github.com/TeamMaestro/angular-native-seed/blob/master/.vscode/settings.json#L16 - did this for my project and boom intellisense works 💯. Hope that helps.

PS - been a long time since I looked at a RN project but I recall it having a lot of directories for the native parts of the application, similar to NativeScript projects, so make sure to exclude all of those directories and it should definitely improve performance.

**Comment by mjbvz** [comment]
Info about `jsconfig`: https://code.visualstudio.com/Docs/languages/javascript#_javascript-projects-jsconfigjson

In the root of your workspace, add a file:

```
{
    "compilerOptions": {
        "target": "ES6"
    },
    "exclude": [
        "node_modules",
        "**/node_modules/*"
    ]
}
```

Please also try using `typescript@next` in your workspace by following these instructions: https://code.visualstudio.com/docs/languages/typescript#_using-newer-typescript-versions
