### ISSUE TITLE
Automatic insert or delete ending brackets

### ISSUE THREAD

**Issue by pawelzwronek** [Microsoft/vscode#48121]
- VSCode Version: 1.22.2
- OS Version: Win10

Steps to Reproduce:

1. Write a line with missing some brackets at the end: `let a = max(0, 2 * (b+1|)` with cursor placed before last ending bracket, as shown with `|`

Feature request:
After pressing `)` once insert or delete as many `')'` as needed so the error `[ts] ')' expected.` will disappear.

Today's behavior:
Now I have to first press as many `)` so the cursor is placed at the end, skipping over the existing brackets(it's quite annoying), and then manually repair missing brackets 😢

**Comment by alexandrudima** [comment]
Similar: #16915

**Comment by rebornix** [comment]
Shared the same root cause as https://github.com/Microsoft/vscode/issues/37315 and https://github.com/Microsoft/vscode/issues/6841, let's track this issue in https://github.com/Microsoft/vscode/issues/6841 . We don't check whether a open or close bracket/paren is already paired or not at this moment.
