### ISSUE TITLE
[loc][Query] Context for "{0}, picker"

### ISSUE THREAD

**Issue by josefhosek** [Microsoft/vscode#48131]
For string below community member asked to provide more context, especially for placeholder.

**Context**
src/vs/base/parts/quickopen/browser/quickOpenModel:English (en):plaintext:quickOpenAriaLabelEntry

**Resource**
vs_base

**String Hash**
59d78fc63ba5b1c1401fca9f02a3fbe7

**String text**
{0}, picker

**Comment by bpasero** [comment]
@josefhosek this is a ARIA label to help users that need to use a screen reader to understand the context. A picker is a widget to pick from a list:

![image](https://user-images.githubusercontent.com/900690/38980408-10f4d86e-43bd-11e8-948b-74ba1a1d04dc.png)

Since "picker" is very generic, we prefix it with the specific picker (e.g. "commands, picker").
