### ISSUE TITLE
Changes to CSS Code Not Being Reflected Within Browser

### ISSUE THREAD

**Issue by Brock535** [Microsoft/vscode#4814]
I have been attempting to learn HTML and have begun to use CSS. I have had no problems so far with my basic CSS codes being reflected through both IE and Chrome. But now I am only able to see HTML code instead of the CSS that supports it, as well. I tried doing a full cache to both IE and Chrome, and created completely new files to see if that would help (but with no success).  

Attached is a picture of very basic code where none of the CSS updates in my browser. All I receive are the three periods shown. As previously stated, other basic codes I've been creating for educational purposes have only resulted in the HTML being reflected.

![capture](https://cloud.githubusercontent.com/assets/18182719/14166359/d03460d6-f6e0-11e5-98c9-721be1606a2f.PNG)

**Comment by Tyriar** [comment]
[Stack Overflow](http://stackoverflow.com/) is probably the place to ask these sorts of questions. At first glance you might be running into something called content security policy by running the HTML file locally. Try moving your styles directly into `<style>` tags in the HTML file. If you want to find the root cause I recommend Googling for the problem first and then asking on Stack Overflow if nothing comes up. Good luck!
