### ISSUE TITLE
String between two slashes and variables treated as Regex

### ISSUE THREAD

**Issue by moseleyi** [Microsoft/vscode#48167]
I don't know if this is expected behaviour but I would like to know if there's a way to stop it.

Let's assume I have this test string in PHP:

`$test = '/en/'.$var.'/some-page/'.$var2;`

`some-page` is still a string but it's highlighted as a regex

**Comment by roblourens** [comment]
Regexes in PHP are just strings. Since we don't know whether a string will be used as a regex or not, we highlight any string that looks like a regex, as a regex. I guess it's annoying when it's wrong but it seems the most useful behavior. One way to prevent that would be just to make your strings not look like regexes like `'/'.'en/'`
