### ISSUE TITLE
"Format Code" in .js files doesn't work (ts server died)

### ISSUE THREAD

**Issue by crabulik** [Microsoft/vscode#4817]
- VSCode Version: 0.10.11
- OS Version: Windows 7 Enterprise

I don't know, how reproduce this issue on the other system, but in my case it looks like that.

I've started JS project with Aurelia Framework.
And at the begining "Code Format" was working, but after some time i noticed, that:
1. Code Format isn't working in JS files;
2. VS Code shows me warning, that TS engine died 5 times for the last 5 minutes;
3. Code Format works fine, when folder "jspm_packages" in my root folder is delited or contains  not all libs from jspm.

After some investigations i've found that, if I add "tsconfig.json" with:

"exclude": [
    "node_modules",
    "jspm_packages",
    "build"
  ]

Code Format works fine, but TS starts to analyse my JS code, but my project isn't TS, it's ES6 project with Gulp compilation.

Thanks!

**Comment by egamma** [comment]
@crabulik 

The recommendation is to add a jsconfig.json and to exclude the 'non source' js files. We have improved the documentation, pls give it a read: https://github.com/Microsoft/vscode-docs/blob/vnext/docs/languages/javascript.md

>VS Code shows me warning, that TS engine died 5 times for the last 5 minutes;

Can you please try this again in the insiders build which has improvements in this area https://code.visualstudio.com/download?insiders=true. It should no longer crash and you should get guidance to exclude folders.

>Code Format works fine, but TS starts to analyse my JS code

This is expected since the JS support is now powered by TypeScript.

// @jrieken

**Comment by crabulik** [comment]
@egamma Thnx, it helped with Format Code
> The recommendation is to add a jsconfig.json and to exclude the 'non source' js files. We have improved the documentation, pls give it a read: https://github.com/Microsoft/vscode-docs/blob/vnext/docs/languages/javascript.md

**Comment by egamma** [comment]
@crabulik thanks for verifying - closing.
