### ISSUE TITLE
Consistent navigation in editor without moving cursor

### ISSUE THREAD

**Issue by florianrusch** [Microsoft/vscode#48202]
Issue Type: <b>Feature Request</b>

Hi everybody,

I noticed that navigating in a file without moving the cursor is not really standardized:
- Navigating over individual lines: `Ctrl + Up/Down`
- Navigation over a whole page: `Alt + Page Up/Down`

Wouldn't it be more pleasant to use the same button: 
- Navigating over individual lines: `Ctrl + Up/Down`
- Navigating over a whole page: `Ctrl + Page Up/Down`

I haven't tested if `Ctrl+ Page Up/Down` is already used by any extension. From VSCode however apparently not yet (at least under Linux)

What do you think?

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:34:44.222Z)
OS version: Linux x64 4.13.0-38-generic

**Comment by alexandrudima** [comment]
They used to be aligned. And then we needed keybindings for opening next editor or previous editor (https://github.com/Microsoft/vscode/commit/74a960103828708593a8532bf241b41b0b9c321c).

Since keybindings are so easy to be customized, I would not change the defaults... But @bpasero what is your opinion

**Comment by bpasero** [comment]
@alexandrudima I cannot remember for sure why I added that particular keybinding, I think I found it to be used in other editors for the same command so I thought it was a good idea to have it. I would also think we should not change it now.
