### ISSUE TITLE
user snippet "log" adds new line automatically in typescript

### ISSUE THREAD

**Issue by webdevfarhan** [Microsoft/vscode#48315]
- VSCode Version: Version 1.22.2
- OS: ubuntu 16.04

Steps to reproduce :

- In any typescript file type log then press TAB for completion of console.log user snippet
- Also do the same in javascript file

Problem : 
In typescript, When i type user snippet "log" then press TAB then console.log("") is printed but a new line is also automatically added in typescript although there is no new line "\n" defined in the javascript.json file where all user snippets are defined. I tested the same in javascript also and no new line is added there, in javascript it works perfectly but in typescript console.log is printed but a new line is also added, is there any solution to solve this problem ?

**Comment by mjbvz** [comment]
Yes, the default "log" snippet for both js and ts inserts a new line. You likely are using the default one in typescript files, and your user contributed snipper in js files. 

The ability to override / disable specific built-in snippets is tracked by #10565. Until that is supported, recommend you give your user snippet a unique name so that you make sure you select the correct one

**Comment by webdevfarhan** [comment]
No, in javascript all users snippets works correctly but in typescript no user snippet is working and i found out that typescript is using its own user snippet "log" that's why it adds new line. I tested with new unique user snippet but in typescript no user snippet works.
