### ISSUE TITLE
On Mac, if VSC is hidden, then opening it from Terminal opens new window in background

### ISSUE THREAD

**Issue by garyking** [microsoft/vscode#48441]
On a Mac, open VSC, then hide it. Open Terminal, run `code .` to open the current dir in VSC. Assuming you have the setting to open it in a new window in VSC, then the new window will open in the background in VSC.

**Comment by bpasero** [comment]
If someone has energy + an idea to look into, feel free.

**Comment by garyking** [comment]
Yes possibly an Electron issue. I haven't been able to find the relevant issue yet though.

**Comment by bpasero** [comment]
This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to the code. As such, I will go ahead and close it. If you can identify the component that is causing the issue, please report it upstream:
* for UI, OS integration: https://github.com/electron/electron
* for Rendering: https://bugs.chromium.org/p/chromium/issues/list
* for file IO: https://github.com/nodejs/node

Thanks for understanding.
