### ISSUE TITLE
panel.onDidDispose can't reliable be used to avoid exceptions

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#48509]
Tests: Microsoft/vscode#48453

The documentation suggests that panel.onDidDispose can reliable be used to avoid exception. I think this is not true since the communication between the renderer and extension host is async. It can happen that the user presses the close button and the extension tries to access the WebView before the dispose event made it to the extension host. We should either make this clear in the doc or handle these cases more gracefully.

**Comment by mjbvz** [comment]
Good point, although I believe this is mitigated by how dispose is implemented. The important points:

- The extension host throws if you try accessing a disposed webview. The main thread does not.
- The main thread throws if you try accessing an unknown webview.

Here's what happens when the user closes a panel:

1. The `onDispose` callback is invoked in `mainThreadWebview`
1. The callback sends a  `onDidDisposeWebview` message to the extension host.
1. The extension host receives this message. It marks its `ExtHostWebview` object as being disposed and fires the extension `onDidDispose` method which synchronously invokes all the listeners. If an extension tries to call method on the webview object at this point, an error will be thrown
1. Meanwhile, the `mainThreadWebview` has been waiting for the extension host's `onDidDiposeWebview` event to complete. If the extension host tries to access the disposed webview while the `mainThreadWebview` is waiting, no error should occur because the main thread still knows about this webview
1. Once `onDidDisposeWebview` completes in the `mainThreadWebview`, we delete the webview. At this point, any future attempts to access it will throw errors

Do you think that this mitigates the concern?

**Comment by dbaeumer** [comment]
What happens if the extension does something with the web view between 1. and 3. If this returns reasonable results and doesn't throw I am fine with closing the issue.

**Comment by mjbvz** [comment]
Getters return the current values, while all the setters and methods no-op
