### ISSUE TITLE
Inconsistent deprecation of ViewColumn

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#48506]
Tests https://github.com/Microsoft/vscode/issues/48453

`readonly viewColumn?: ViewColumn;` is deprecated but `reveal(viewColumn?: ViewColumn): void;` not. This seems to be inconsistent.

**Comment by mjbvz** [comment]
The intent is that `viewColumn` will be replaced by `gridPosition` or similar. When this happens, `viewColumn` will be undefined if the webview is not in any of the main columns, making the properly far less useful. We will always have a `reveal` method though, it will just would be overloaded to take a `gridPosition` instead of a `viewColumn`. Calling`reveal` using a viewColumn will continue to work in grid layout
