### ISSUE TITLE
Toolbar menu ignores mouse clicks

### ISSUE THREAD

**Issue by SetTrend** [Microsoft/vscode#48519]
Clicking the `...` icon in the Git side panel is regularly ignored by VS Code. You need to click that icon twice and more times in order to get the context menu displayed:

![git menu ignores mouse clicks](https://user-images.githubusercontent.com/9283914/39181380-cc2e8b98-47b9-11e8-81c1-e236d48593fb.gif)

If this behaviour is intended, please add visual feedback to give information ...
- when toolbar buttons are disabled and 
- when toolbar buttons are "hot" (i.e. the mouse pointer hovers above the active area of that button).
<hr/>

- VSCode Version: 1.22.2
- OS Version: Windows 10x64

**Comment by joaomoreno** [comment]
@bpasero Do we ever disable the toolbar's `...` menu action?

**Comment by bpasero** [comment]
@joaomoreno no we never do that but maybe the click is interpreted as double click because the entire VM stops when the menu opens and then continues so it could be that the timing between the 2 clicks is very short. If my theory is true, it would be fixed with https://github.com/Microsoft/vscode/issues/23085

@SetTrend can you reproduce from our "Code Exploration" build: https://az764295.vo.msecnd.net/exploration/5e0fbe54562b6291114d1219f8bf5bbcb77af1b1/VSCode-win32-x64-1.23.0-exploration.zip

**Comment by joaomoreno** [comment]
Ah!

**Comment by SetTrend** [comment]
Just checked. No change:
<br/>

![git menu ignores mouse clicks - 2](https://user-images.githubusercontent.com/9283914/39201524-9446633c-47ef-11e8-8929-70ad796f29b6.gif)

**Comment by SetTrend** [comment]
Looks like everything is working fine now:

![github context menu working](https://user-images.githubusercontent.com/9283914/45820079-47543100-bce6-11e8-8730-153e02558793.gif)

Thanks a lot for taking the time and effort!

Case closed.
