### ISSUE TITLE
Capturing state of a web view when it becomes invisible

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#48542]
Tests https://github.com/Microsoft/vscode/issues/48453

While reading through the documentation I got the impression that when a web view panel becomes invisible we dispose the underlying web view. Before we do so we capture the HTML and basically put it back when the panel becomes visible again.

However I found no good way to capture any state of the web view when this happens other than constantly sending state from the web view to the extension. What I would like to code is the following (I didn't test it though):

- the extension receives a `willChangeViewStateEvent`. When the event is received the web view is still functional and the extension can send message to capture some state to the web view.
- when restore and the web view has JS enabled we should be able to call a restore hook (see also https://github.com/Microsoft/vscode/issues/48540) with some captured state so that the view can restore its state properly before it renders.

However I am not a WebView expert so I am not sure if this is possible.

**Comment by dbaeumer** [comment]
I tried to code that under Windows using the normal events but I failed.

**Comment by mjbvz** [comment]
Yes this is a known difficulty. The difficulty is in keeping the webview alive long enough behind the scenes so that it has time to persist its state. 

If this proves problematic in practice, one proposal is that we add a persisted object called something like `window.parent.state` inside the webview itself. The js in the webview would be able to update it as frequently as it wants without any extension communication overhead, and then consult this state  when restoring itself

**Comment by dbaeumer** [comment]
Nice solution.

**Comment by mjbvz** [comment]
Added  initial version of this with 6cea1412545481d91095be4f56c85142abbcef13

#49022 tracks how this will fit with the proposed serialization API
