### ISSUE TITLE
Windows 10: Deleting always fails with error message

### ISSUE THREAD

**Issue by apalchys** [Microsoft/vscode#4855]
- VSCode Version: 0.10.11
- OS Version: Windows 10 x64
NOTE: Recycle bin is disabled.

Steps to Reproduce:

1.  Try to delete any file in VS Explorer
2.  Get "Failed to move {filename} to the trash"
3.  Hitting "Delete Permanently" does nothing. 

Also it was reproducible with previous versions.

**Comment by bpasero** [comment]
@apalchys there can be many reasons why moving to trash does not work (e.g. you are on a SUBST drive, or mounted network). The bug that deleting permanently fails is fixed for our current release. You can try it from our insiders release: http://code.visualstudio.com/Download#insiders

**Comment by apalchys** [comment]
@bpasero Confirm. it is fixed in 0.10.13-insider.  Thanks.

**Comment by bmenees** [comment]
I always use VS Code in a Linux VM (in VirtualBox) against a shared folder that's mounted under /media/.  VS Code's Delete command always prompts for whether I want to Move To Trash, but then it always fails to move it to the trash presumably because the file was on a mounted folder/drive.  So then I have to click the Delete Permanently option.  It sure would be nice if VS Code was smart enough to detect that the file was on a mounted folder/drive and just prompt for "Delete Permanently" instead of "Move To Trash".  It would save me a click every time I delete a file, which has happened a lot lately.

**Comment by romanov** [comment]
Is it possible to turn off the thrash feature and always force delete file?
Same story on Windows 10.0.143.93
Very annoying.

**Comment by Landen13** [comment]
The problem still exists.
Version 1.15.1

**Comment by neodon** [comment]
I also use Windows and do development with a local Linux VM.  I use a Windows network share to access my code in the VM with VSCode (Samba in the VM, mapped to a drive in Windows).

Every time I try to delete a file it gives me an "error" because it can't put it in the trash.  Network shares don't have trash folders / recycle bins, so this is nonsensical.

A tweak or setting to work around this would be appreciated. :)

I'm on Windows 7 Ultimate SP1 with VSCode 1.16.1.

**Comment by VALIKCOOL** [comment]
I am facing the same issue. I cannot rename or delete folder. Vs code blocking this operation by itself. Only closing vs code helps. Also i have tried running app as administrator - no luck

**Comment by bbak** [comment]
IMHO VS Code should warn by default when it cannot move a file to recycle bin. But there should be an option to override this warning - perhaps even per workspace; so it gets less annoying for those Users that know what they do.
