### ISSUE TITLE
Source map debugging not working for built in extensions

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#486]
Steps to reproduce:
* clone vscode and follow steps here https://github.com/Microsoft/vscode/wiki/How-to-Contribute#build-and-run-from-source
* run scripts\code
* open VSCode on the vscode folder
* select Attach to Extension Host launch config
* Attach debugger
* open bufferSyncSupport.ts and set a breakpoint on line 62
* open a ts file in the instance started via scripts\code and type into the file

Observe: debugger not hit.

If you set a breakpoint in the JS file everything works as expected.

**Comment by dbaeumer** [comment]
Using --extensionDevelopmentPath=.\extensions\typescript didn't work either. I get some wired error message complaining about the fact the extensions/typescript/out/typescriptMain couldn't be found.

**Comment by dbaeumer** [comment]
--extensionDevelopmentPath must be an absolute path. Using an absolute path loads the extension however setting a breakpoint in TS still doesn't work.

**Comment by dbaeumer** [comment]
Andre pointed out that the TS extension doesn't generate source maps. Added the flag. Now I can set breakpoints in TS but I the breakpoint gets hit I see:

![image](https://cloud.githubusercontent.com/assets/1931590/11335568/8dcb6aea-91dd-11e5-9298-9d5cb4bab780.png)

**Comment by weinand** [comment]
I've analysed the problem and found this:

The source maps in our extensions 'out' folder have broken paths in their "sources" array. Normally these path entries should point to the source relative from the sourcemap location. But for the Monaco workspace these paths are relative to some other location. This makes it difficult for node-debug to figure out where the source lives. I can add more "guessing" heuristics to node-debug, but I think we should fix the root of the problem as well.

Here is an example from the typescript extension's "bufferSyncSupport": 

* source: vscode/extensions/typescript/**src**/features/bufferSyncSupport.ts
* dest: vscode/extensions/typescript/**out**/features/bufferSyncSupport.js

Since the sourcemap lives next to the destination file, the minimal relative path between map and source is "../../src/features/bufferSyncSupport.js".

However the actual path in the sources array is "../../vscode/extensions/typescript/src/features/bufferSyncSupport.ts".

If I run tsc in the typescript extension folder manually, the path in the source map is correct. Only the build watcher creates a broken path.

**Comment by joaomoreno** [comment]
@weinand The paths don't matter if the original sources are inlined in the sourcemaps. For `vscode/out` we don't inline them and the paths are correct. For all other `vscode/out-*` directories we always inline the sources.

No one really looked into enabling sourcemaps in extensions, I think. Someone should just dig in there and make sure that either (1) we inline the sources or (2) the paths are correct, just like in `vscode/out`.

**Comment by weinand** [comment]
@joaomoreno inlining sources (1) doesn't make sense for debugging extensions in the vscode workspace because inlined source is always readonly and has no relation to the actual source we have in the workspace. Inlined source makes sense for our distro if the sourcemaps come from a server and we reference the sourcemaps from our generated source through urls.

**Comment by joaomoreno** [comment]
Then we gotta fix the paths.

**Comment by chrmarti** [comment]
@joaomoreno this just worked on todays insiders:
- VSCode Version: Code - Insiders 1.5.0-insider (dde41be0231d6f8397d1da969ddab351f137b833, 2016-08-08T06:03:58.264Z)
- OS Version: Darwin x64 15.5.0

**Comment by joaomoreno** [comment]
Thanks @chrmarti
