### ISSUE TITLE
Option to disable the modal dialog on start debug failure.

### ISSUE THREAD

**Issue by jeffhoye** [Microsoft/vscode#48606]
When I accidentally write a bug that causes a compile failure, I get a modal error like this:
![image](https://user-images.githubusercontent.com/1181397/39214884-04ae6478-47e4-11e8-84f8-270c3af50d6f.png)

I think it's a great default setting.  However, now that I'm very familiar with vscode, I know to look in the debug console.  ... that's where I'm looking when I start the debugger.  Closing the modal every time there is a compile issue is just extra hassle since it is already very clear from the debug console that I have an error and what it is.

Please make a configurable setting to diable this modal.

I recommend:

```debug.modalDialogOnStartFailure```

See also:  https://github.com/Microsoft/vscode/issues/45998

**Comment by jeffhoye** [comment]
I made a pull request with the fix.  Pls LMK if you want any changes.  

Thanks!  vscode rocks!

**Comment by isidorn** [comment]
@jeffhoye thanks for the PR but we will only accept it if more users ask for this feature.
We try to make vscode minimalstic, otherwise we would have millions of settings.

**Comment by jeffhoye** [comment]
I understand.  I'll try to think of a way to solve it via a plugin....

**Comment by isidorn** [comment]
@jeffhoye not sure if possible via a plugin

**Comment by weinand** [comment]
I think there are two types of notifications:
- expected (frequent) problems like compiler errors,
- unexpected (rare) problems like a runtime error in a debugger or a non-existing variable in a launch config.

IMO the first type of problem should be addressed by the non-modal notification whereas the second type should result in a modal dialog because it is a fundamental problem that requires the users attention.

@jeffhoye in your original message from above you said that a compile failure results in the modal error dialog you are showing. The dialog looks strange because it does not indicate that the prelaunch task was failing. What debugger are you using and how are you compiling/building?

**Comment by jeffhoye** [comment]
I've been using vscode to program in Node.js, Python, but primarily Go (golang).  I just fired up some Python and Node.js programs and inserted syntax errors to see if it behaves the same.  *It does not.*  

Therefore, perhaps it's an issue with the Golang plugin (lukehoban.go).
https://code.visualstudio.com/docs/languages/go

 I'll have to try c++ or java around to see if it's just the Golang plugin or if it's an issue with compiled vs interpreted languages.

**Comment by jeffhoye** [comment]
Setting up C++ and/or Java environments with vscode is taking longer than I can play with this morning. 
 I was hoping to see how they behave to similar syntax errors that block building.  

I'll bring my issue over to https://github.com/Microsoft/vscode-go

... and see if there's a more compliant way to report normal compilation errors. 

I guess we can close the issue until I work with vscode-go to figure out the proper approach.

**Comment by weinand** [comment]
@jeffhoye thanks for revisiting this and filing an issue against vscode-go.
