### ISSUE TITLE
Symbol match highlight not shown on first line

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#48618]
- New file

```
hello1
hello1
hello1
hello1
```

- Put the cursor on any word
- See that the last 3 instances are highlighted as matching, but the first is not 🐛 
- Add a newline at the top of the file
- Now see that all 4 are highlighted together

This shows up in the screenshot in https://github.com/Microsoft/vscode/issues/46995#issuecomment-378883166 but I couldn't find an existing issue.

**Comment by alexandrudima** [comment]
Using these settings to emphasise the selection highlighter:
```
    "workbench.colorCustomizations": {
        "editor.selectionHighlightBorder": "#dddddd"
    },
```

The selection highlighter is built in the following way:
* when there is no selection, it will highlight the current word and all other words (for languages which do not have a word highlighter)
* when there is a selection, it will highlight all the other text that matches the selection, but not the selected text itself.

The latter is in order to avoid interfering with the painted selection and let you focus on where the cursor is. Anyways, IMHO, regular folks (not for bug purposes) would never use something so strong (like an almost white border) for the selection highlighter, as that draws too much attention to a somewhat unimportant decoration. 

![kapture 2018-04-25 at 9 11 23](https://user-images.githubusercontent.com/5047891/39230927-a9935104-4868-11e8-853e-3d2012c6552d.gif)
