### ISSUE TITLE
Strange "Canceled" message 

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#4861]
- VSCode Version: alpha
- OS Version: OS X 10.11.4

If the debug adapter terminates unexpectedly I now see this strange "Canceled" message: 

![2016-04-01 17-09-13](https://cloud.githubusercontent.com/assets/1898161/14211137/b8ff2bba-f82c-11e5-8a9e-e747a05e8405.png)

**Comment by isidorn** [comment]
Accidentely closed this, there is still an issue that I am looking into

**Comment by rkeithhill** [comment]
FYI, in the Powershell extension scenario, the script didn't terminate unexpectedly from the extension's point of view.  It successfully completed execution of the script.  But I think because VSCode did not send the `disconnect` message (or we didn't send something to cause VSCode to send that message) - VSCode thinks the debug host terminated unexpectedly.

**Comment by rkeithhill** [comment]
If it helps here is a diff of our log file - left side is latest Insiders which does *not* generate error cancelled popup and right side is latest alpha which does generate the error:
![logdiff](https://cloud.githubusercontent.com/assets/5177512/14372036/5613e7de-fcfa-11e5-86ab-22a9d230e0d0.PNG)

**Comment by rkeithhill** [comment]
Good news. With today's build of alpha 2016-04-09 I am no longer getting the `error cancelled` popup.  This might have been fixed yesterday as I didn't check yesterday but I know I checked on Thursday and it was still generating the error popup.

**Comment by isidorn** [comment]
@rkeithhill great! Sorry for the slow responses, I was out on vacation for a couple of days.
Anyways, is there something that still needs to be done here?
(except us improving the documentation and figuring out the right order of events on startup)

**Comment by rkeithhill** [comment]
@isidorn Well, with the 1.0.0 Alpha build I just installed, if I don't have breakpoints set, I get no output from my test script at all.  :-( The insiders build from 4/4 still works fine.  

We have seen this "no output from debugging" problem before. We fixed it by swapping the order of the initialized event and initializeRequest response so that we send the initialized event *after* the initializeRequest response.  That doesn't seem to be working anymore in the 1.0.0 Alpha. Did anything change in the debug protocol message ordering for the upcoming 1.0.0 release?

**Comment by isidorn** [comment]
@rkeithhill no, nothing should have changed in the ordering between insiders and alpha. If you want me to investigate please give me repro steps - is it enough to use latest powershell and just any ps script? Is this the behavior you are mentioning https://github.com/Microsoft/vscode/issues/4567

**Comment by rkeithhill** [comment]
@isidorn - hmm, trying this on another machine and seeing different results.  I'm beginning to wonder if the PowerShell extension debugger has an issue with pause/continue.  Let's keep this closed for now and I'll get back to you if I still think it's a VSCode issue.
