### ISSUE TITLE
ResolveCompletionItem is called on each keystroke

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#48619]
**Steps to Reproduce:**

1. Set   `"typescript.tsserver.trace": "messages"`
1. In a js file:

```js
function fooooooooooooo() { }

foo
```

2. Trigger suggestions at end of `foo` and start typing

**Bug**
In the typescript output panel, notice multiple `completionEntryDetails` calls in the logs as you type. This is caused by vs code calling `resolveCompletionItem` on the same item again for each keystroke

**Comment by ramya-rao-a** [comment]
This has been happening for over a year.

- Every letter typed filters the completion list and so the list control is re-filled
- When doing so, the variable tracking the current focused item is reset [here](https://github.com/Microsoft/vscode/blob/622eab8bebbe5a7b228cf890fc3ca1665a49bcf1/src/vs/editor/contrib/suggest/suggestWidget.ts#L727)
- Due to this, the code to smartly skip re-rendering the focused item is never reached.
https://github.com/Microsoft/vscode/blob/622eab8bebbe5a7b228cf890fc3ca1665a49bcf1/src/vs/editor/contrib/suggest/suggestWidget.ts#L581-L583

The root cause, is that the variable tracking the current focused item is reset. This was done in https://github.com/Microsoft/vscode/commit/a35c7da7b8f324c1e8cc7830173418e392542f6d. @joaomoreno Do you recall the reason for this change?

**Comment by joaomoreno** [comment]
My commit message and related issue #23408 seem to be very helpful. I can't even imagine how broken it was 🐛 

Serious now: I'm not sure. The suggest widget used to narrow down suggestions by itself, without asking the provider to narrow down, except if the provider returns an incomplete result. I can only reason that in that case, `showSuggestions` would only be called on the initial population of results; while further "narrow downs" wouldn't pass through that code pass. It seems that even narrowing down now uses `showSuggestions`, so that assumption is misleading.

**Comment by jrieken** [comment]
Don't reset the item when it's the same completion model?

**Comment by ramya-rao-a** [comment]
That works. Pushing this to May as there is no visible user impact of this issue.

**Comment by ramya-rao-a** [comment]
> Don't reset the item when it's the same completion model?

The completion model differs for each keystroke if there is a completion provider giving result of the incomplete kind. So checking the completion model doesn't always work

Pushed another fix https://github.com/Microsoft/vscode/commit/2e0a56423031aa7b4a8779ea23465128e6ddfef8 which doesn't rely on the completion model.

Moving this bug for June for another round of verification.
