### ISSUE TITLE
VSCode uses it's TypeScript version even though another one is specified in settings.json

### ISSUE THREAD

**Issue by trivikr** [Microsoft/vscode#48640]
- VSCode Version: 1.22.2
- OS Version: macOS Sierra 10.12.6

Requirement: When opening TypeScript files in VSCode, use the typescript version from `node_modules` instead of VSCode's TypeScript version

Steps to Reproduce:

1. In `.vscode/settings.json`, I added the following settings as defined in the [documentation](https://code.visualstudio.com/docs/languages/typescript#_using-newer-typescript-versions):
```
{
    "typescript.tsdk": "./node_modules/typescript/lib"
}
```
2. VSCode still uses it's typescript version by default.

I've reproduced the issue in [vscode-typescript-default-version](https://github.com/trivikr/vscode-typescript-default-version) repository.

Question: What needs to be done to use typescript version from node_modules by default when opening TypeScript files in VSCode?

This question was asked on [StackOverflow](https://stackoverflow.com/questions/49949148), but it appears to be a bug with VSCode

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
This is by design. As the SO question says, you need to explicitly select the typescript version when you first open a new workspace. After this first selection, vscode should remember it in the future.

This is done for security reasons. `"typescript.tsdk"` just tells vscode where to find the local copy of typescript
