### ISSUE TITLE
Provide documentation for moving away from bundled language packs to Marketplace language packs

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#48645]
Write a documentation page for moving away from bundled language packs to Marketplace language packs.

Provide me the fwd link to show it in the message.

**Comment by dbaeumer** [comment]
@chrisdias & @danyeh can you please write the page. It should contain the following information:

- a little history about language packs and that we have them for additional languages since n months
- why we make the move. The reason is that all language should be equal (exception is our default language which will still ship out of the box).
- translation issue can be fixed independent of code fixes.

We should also make clear that in n month we will remove the bundled langauges. So users need to install the language pack then.

**Comment by chrisdias** [comment]
@gregvanl can you help here?

**Comment by gregvanl** [comment]
This issue was moved to Microsoft/vscode-docs#1582

**Comment by gregvanl** [comment]
@dbaeumer @sandy081 Any reason this needs to be a separate topic? I think it might be better as a section in the existing Display Languages topic https://code.visualstudio.com/docs/getstarted/locales. You can still point the fwlink to an H2 header.
When we remove the bundled languages, we could remove the content on transitioning to the Marketplace as it will be the only way to get a language pack.

**Comment by dbaeumer** [comment]
@gregvanl +1 for having it in the existing documentation.
