### ISSUE TITLE
Tasks should ignore task definitions in ignored folders

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#48701]
Latest insider.  This behavior changed recently.

1) Open a workspace with task definitions 
2) Created a `ignoreme` folder and add it to the `.gitignore` file
3) Create a tasks that checkouts out another folder with task definitions into the `ignoreme` folder

-> While the task is running I get several "Changing the task execution engine while a task is running..." notifications.

-> After the task is finished, the task systems does not work properly anymore. I get error messages about tasks, running tasks now is like working with un-configured tasks etc. 

4) Reload window
-> Tasks are back to working normally (most of the time).

----
Can reliably be reproduced with MS-private https://github.com/Microsoft/vscode-gdpr-tooling.

1) clone repo
2) open cloned folder in Code Insiders
3) Tasks: Run Task> npm: setup-scan-repos
-> notifications spam
4) Tasks: Run Task> npm: extract-core
-> error messages
5) Reload Window
-> mostly back to normal
----

I think at the core of the problem is that I don't expect tasks to look into folders that are listed in `.gitignore`.

**Comment by dbaeumer** [comment]
@kieferrm  I am not sure I understand exactly what you mean. Tasks never looks into folders. Tasks only listens to configuration change events send out from our configuration service. Does the check out create a .vscode folder with a tasks.json file in there ?

The ignoring has to happen in the configuration service then since tasks itself doesn't make any assumption have the tasks.json file is process / stored.
