### ISSUE TITLE
Duplicate errors in error list after build

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/vscode#48709]
Issue Type: <b>Bug</b>

1. Create file `a.js`:
```ts
// @ts-check

/** @type {number} */
var a = "";
```
2. Create file `tsconfig.json`
```ts
{
    "compilerOptions": {
        "allowJs": true,
        "pretty": false,
        "noEmit": true
    }
}
```
3. Open code
4. Run build command

Observe error list is updated with errors: 

![image](https://user-images.githubusercontent.com/8000722/39269003-403e34d0-4886-11e8-9cf9-bc02c9d3b976.png)

5. Double click on the error message, `a.js` is now open

Observe error list now has duplicate errors:

![image](https://user-images.githubusercontent.com/8000722/39269016-4e73c506-4886-11e8-9204-4f017c42c33f.png)

> Note: this does not seem to happen for a `.ts` file

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|Memory (System)|15.93GB (6.67GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe stc|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|1.9.2

</details>

**Comment by mjbvz** [comment]
Root cause is that the build error comes from 'typescript' while the in-editor error comes from `typescript` (indicated by the `[ts]` and `[js]`). Potential fixes:

* Only use a single error provider for both JS and TS. This probably makes the most sense since you have have mixed projects. Not sure why these were split originally
* Make problem view smarter so it can de-dup these two languages  
* Make errors detected in js files by build task get reported as `[js]`

**Comment by mjbvz** [comment]
Yes this will be in the next insiders build
