### ISSUE TITLE
console.log in Webview client script should not pollute the main DevTool 

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#48717]
#48453

Imagine user installs a few chatty Webview extensions. This will bury all meaningful logs in dev tools.

![image](https://user-images.githubusercontent.com/4033249/39274470-ee25fc1c-4896-11e8-805f-60018b7aff35.png)

**Comment by mjbvz** [comment]
This is consistent with what we do if an extension itself calls `console.log`. I personally find the behavior useful because it lets me just run the the main VS Code developer tools to see log message and errors that happen in any webview. Launching inspectors for each webview individually can be tedious
