### ISSUE TITLE
Markdown JSDoc line breaks in parameter-suggest hover are still wrong

### ISSUE THREAD

**Issue by thw0rted** [Microsoft/vscode#48758]
- VSCode Version: 1.22.2
- OS Version: Windows 10 (latest)

Steps to Reproduce:

1. Generate some JSDoc with that spans multiple lines, but is treated as a single logical paragraph by the Markdown parser:
````
    /**
     * The docs for this go on long enough that the first line really aught to wrap at some point, probably.
     * Per the Markdown spec the second line here should not be separated by a hard break, unless the preceding line ends with two spaces, like this one.  
     * This is a separate line.
     * 
     * So is this one.
     */
````
2. Inspect the documented method by hovering over its name somewhere -- you should see a continuous paragraph with no unexpected line breaks, like this:
![image](https://user-images.githubusercontent.com/943160/39309565-9bc529ca-4968-11e8-8d0e-68292529a62f.png)
3. Now, type the name of the documented method, open-paren, and note the hard line breaks where they should not be:
![image](https://user-images.githubusercontent.com/943160/39309658-d75a3b06-4968-11e8-9996-b2c534228c16.png)

I've seen some issues about this (#2330, #11032) but they're closed, so I'm opening a new one.  Interestingly, the older of those issues has an unchecked box for "parameter hints widget" -- maybe it was intended to address this problem and the issue was accidentally closed without resolving?

**Comment by dbaeumer** [comment]
Line breaks are not added anymore, however now a new line is missing between `This is a separate line` and `So is this one`.

<img width="391" alt="capture" src="https://user-images.githubusercontent.com/1931590/40728658-e5ae8270-642a-11e8-9e66-2fc80eda1e69.png">


I am reopening the issue since I think the missing new line looks like a bug.

**Comment by mjbvz** [comment]
@alexandrudima This is cause by the css rule:

```css
.monaco-editor-hover p {
	margin: 0;
}
```

Which I see referenced in #11409. Removing the rules makes the hover better match the suggest widget docs but I'm not sure what other impact it will have

**Comment by alexandrudima** [comment]
That CSS should not be loaded in VSCode, as it is in the editor's `/standalone/` folder. The CSS ends up loaded because of this line:
https://github.com/Microsoft/vscode/blob/3311b9ec1ddc8a0e90f900265263f165cb4e18cb/src/vs/workbench/parts/terminal/electron-browser/terminalPanel.ts#L31

fyi @Tyriar do not auto-import symbols from the standalone editor's API

I will investigate into more TSLint import errors...

**Comment by dbaeumer** [comment]
Re-verified. Is fixed.

**Comment by Tyriar** [comment]
@alexandrudima thanks for the fix and the tslint rule
