### ISSUE TITLE
Support portable settings

### ISSUE THREAD

**Issue by sarbbottam** [Microsoft/vscode#4875]
In Mac following customizations are found at `~/Library/Application Support/Code/User`:
* `keybindings.json`
* `settings.json`
* `snippets`

Where as `installed extension`s are found at `~/.vscode`

Could there be a `settings` file with the installed extension, so that the extension can be installed from the list? Something like `package.json`?

I am not sure where the current `color theme`  preference is stored.

**Could all the user defined customization settings be co-located and in `~/.vscode`?**

It would be very helpful, for folks, who works across multiple system (for me it's Mac and Linux) to automatically maintain the same setting across all the system, instead of manually customizing it? Something like [sarbbottam/conf-files](https://github.com/sarbbottam/conf-files).

Thanks!!

**Comment by andmos** [comment]
I agree. Atom let's you also install extensions from the command line with the ``apm install`` command. Something similar would be nice for VSCode as well. I use OS X, Linux and Windows, keeping my settings in sync is possible with Git, but the extensions has to be managed manually.

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/3884 is working towards moving both extensions and settings into the same folder.

**Comment by sarbbottam** [comment]
I doubt #3884 will address this issue/request.
From [this comment](https://github.com/Microsoft/vscode/issues/3884#issuecomment-256128345) it seems #3884 is going in an opposite direction.

**Comment by Tyriar** [comment]
@sarbbottam how so? That issue is all about unifying app data and user data directories (in a way that makes sense for the platform)?

**Comment by sarbbottam** [comment]
But it's becoming platform specific and losing the portability.

>- %APPDATA% on Windows
>- $XDG_CONFIG_HOME or ~/.config on Linux
>- ~/Library/Application Support on macOS

The intent of the issue was to make the setting platform agnostic at least for macOS and Linux. Similar to `~/.vim`. VSCode already maintains `~/.vscode` directory. It would still prefer to have all user-defined customizations at `~/.vscode`.

**Comment by Tyriar** [comment]
@sarbbottam it must be platform specific by default, `~` doesn't exist in Windows for example. After re-reading this issue, it does indeed conflict with https://github.com/Microsoft/vscode/issues/3884. We will not be moving everything to `~/.vscode` or `%USERPROFILE%/.vscode` but instead adopting platform best practices, as they are just that, best practices. Roaming profiles on windows is something we want to support properly which is something that will come with this. A big part of #3884 though that does help with this issue is that it will unify the extensions directory with the rest of the settings.

There are a few related items that improve the situation further:

- #329 Distributing a portable version of vscode, this would likely dump all the settings in vscode's directory somewhere
- #2741 Exposing an extension API to get at these directories, this would make any automation via an extension much easier

As such I'm going to close this off as there's no plan to put the settings in the same spot for OSX and Linux. You'll just have to check the platform in your dotfiles.
