### ISSUE TITLE
Feature Request: Smarter indent guides

### ISSUE THREAD

**Issue by alecbz** [microsoft/vscode#48772]
When something is indented in a 'non-standard' way like this:

![](https://i.imgur.com/1yXCnEx.png)

multiple indent guides are shown, even though there's really only one logical indent here. Could the indent lines be smarter and only draw one here?

**Comment by alexandrudima** [comment]
The computation of indent guides is programming language agnostic.

So that algorithm does not know that `,` in this context does not introduce a new "statement". For example, in other programming languages the indentation could be intentional

![image](https://user-images.githubusercontent.com/5047891/39347996-9113ab4a-49f5-11e8-8573-0abb7fcdb61b.png)

**Comment by alkaitagi** [comment]
We already have a feature that highlights brackets over the cursor-placed region. It means that VSCode is able to detect and work with brackets over any region. How about rendering indent guides only in-between brackets?

[Example](https://github.com/microsoft/vscode/issues/87267#issue-539791601)

**Comment by hediet** [comment]
> with brackets over any region. How about rendering indent guides only in-between brackets?

Please check out [bracket pair guides](https://code.visualstudio.com/updates/v1_61#_bracket-pair-guides).
