### ISSUE TITLE
Resizing Left, Top or, Top/Left very jumpy

### ISSUE THREAD

**Issue by hossimo** [microsoft/vscode#48870]
Issue Type: <b>Bug</b>

Resize the code window using either top, left or top/left handles causes jumpy, unperdictable resizing.

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:32:53.389Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (3.31GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.3.0
vscode-docker|Pet|0.0.26
npm-intellisense|chr|1.3.0
jshint|dba|0.10.18
vscode-eslint|dba|1.4.8
vscode-npm-script|eg2|0.3.3
python|ms-|2018.3.1

</details>

**Comment by bpasero** [comment]
This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to the code. As such, I will go ahead and close it. If you can identify the component that is causing the issue, please report it upstream:
* for UI, OS integration: https://github.com/electron/electron
* for Rendering: https://bugs.chromium.org/p/chromium/issues/list
* for file IO: https://github.com/nodejs/node

Thanks for understanding.
