### ISSUE TITLE
file explorer acting up and showing wrong file names/icons

### ISSUE THREAD

**Issue by MarkKahn** [Microsoft/vscode#48909]
I thought I was going crazy because I've accidentally deleted the wrong files twice recently.  Then I noticed this (see attached video) -- something is very off in the file explorer.  A directory is randomly getting renamed back and forth to `.eslint` (which is also in the project folder).

![vs_code_file_explorer](https://user-images.githubusercontent.com/320562/39404280-45991a74-4bcb-11e8-91f7-add68e8bf54d.gif)

- VSCode Version: 1.22.2
- OS Version: OSX 10.13.1

Steps to Reproduce:

1. Uncertain.  It's random

Does this issue occur when all extensions are disabled?: Uncertain as I can't reliably repro it

**Comment by isidorn** [comment]
@MarkKahn thanks for reporting this, however we would need some more details in order to repro
Some things you could help us with:
1. When this issue occurs do: F1 > open developer tools and check if there are any errors in the console
2. Maybe try using vscode insiders for a day and check if this issue also happens there https://code.visualstudio.com/insiders/
