### ISSUE TITLE
Intellisense stops working

### ISSUE THREAD

**Issue by Chrisands** [Microsoft/vscode#48916]
Issue Type: <b>Bug</b>

1. open project
2. go deep in your project
3. write `import moduleName from 'module'`
4. try write few times `'../../../actions'` in `'module'`.

It's stops working for second or third time after i write it. And more important that you can type few "links to modules" in different components and get that issue. 

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|Memory (System)|15.94GB (9.81GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by mjbvz** [comment]
Does this happen in VS Code insiders?

**Comment by Chrisands** [comment]
No, it is in stable build.

**Comment by mjbvz** [comment]
Please test the insiders build

**Comment by Chrisands** [comment]
Tested insiders build. Still not working.

**Comment by mjbvz** [comment]
Please also try upgrading your workspace to `typescript@next` by following these instructions: https://code.visualstudio.com/docs/languages/typescript#_using-newer-typescript-versions. Make sure you select the workspace version of typescript by running the `Select TypeScript Version` command after installing

A similar bug was fixed in typescript@next

**Comment by Chrisands** [comment]
Installing `typescript@next` fixed that. Intellisense didn't lag when i tried to repeat bug. 
Current `typescript@next` version `2.9.0`.
