### ISSUE TITLE
Feature request: Please remember last x git commit messages where x is configurable or some arbitrary number (w/ option to paste any of these messages in the git message box)

### ISSUE THREAD

**Issue by jumpinjackie** [Microsoft/vscode#4896]
- VSCode Version: 0.10.13-insider
- OS Version: Windows 8.1

I was doing a commit with a big commit message, after the commit, it turns out I left out a few un-staged files, so I went and undid the last commit and started to re-commit with all files staged.

The problem was that in the process, I lost the previous commit message as I was ready to commit this one and VSCode didn't remember my last message, nor did it offer an option to paste in the last commit message. 

Please implement this capability.

**Comment by joaomoreno** [comment]
Besides the situation in which you type a commit message and later figure out you want to do another commit instead, I don't see any added benefit of remembering commit messages, since they will all be quite different from each other. I just don't see the reuse.

Also I don't think that the solution proposed would solve your problem since you didn't actually commit it, so the message wouldn't be remembered. We would only remember committed messages.

I'm sorry you lost the message.
