### ISSUE TITLE
No function hover while debugging

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#48971]
_From @mbenkmann on April 10, 2018 11:30_

While not debugging, mouse hovers work find with and without Ctrl being pressed, both with godoc and gogetdoc. While debugging, hovering over a function call does nothing, neither with nor without Ctrl being pressed.

_Copied from original issue: Microsoft/vscode-go#1617_

**Comment by ramya-rao-a** [comment]
_From @mbenkmann on April 11, 2018 8:36_

The behaviour is really weird. It seems like during debugging function hovers work in all files EXCEPT for the one currently selected in the CALL STACK. I guess it's the debug hover that shows me a variable's current value that's the issue. It's only active for the current stack frame and seems to disable all the other hovers. The desired behaviour would be to show the debug hover only over variables and only when the Ctrl-key is not pressed. If either the mouse cursor is over something that's not a variable or if the Ctrl-key is pressed, the default editor hover should be shown.

**Comment by ramya-rao-a** [comment]
This behavior occurs for all languages and is not specific to Go. So moved to the main repo from the repo for Go extension

**Comment by isidorn** [comment]
@mbenkmann please file this issue with exact reproducable steps and explain what the issue is.
We do not support ctrl-key pressing while hovering, that is a seperate feature request that already exists - you can find it in this repository. Thanks

**Comment by mbenkmann** [comment]
@isidorn I don't know what you mean by "We do not support ctrl-key pressing while hovering,"? Of course you do. Try it. It's very useful. In addition to presenting you the normal hover which has the function documentation comment, the Ctrl-hover adds a peek view of the implementation. That's in addition to making the function name a clickable link that will take you directly to the implementation.

**Comment by mbenkmann** [comment]
More detailed steps to reproduce. Platform is Linux. VSCode version is 1.22.2.

0. Pre-condition: vscode-go extension installed.
1. Download http://winterdrache.de/data/issue-48971.tar.gz
2. Extract to a location of your choice. I assume /tmp. It creates a folder "foobar"
3. cd /tmp/foobar
4. code .
5. Open file src/main/fun.go
6. Place a breakpoint at line "fun()"
7. Hover with the mouse cursor over the word "fun" in line 11 WITHOUT holding Ctrl-key pressed. You'll see something like this:

![http://winterdrache.de/data/Hovering-without-Ctrl.jpg](http://winterdrache.de/data/Hovering-without-Ctrl.jpg)

Notice the popup window that shows the function's documentation comment.

8. Now hover over the same word WITH CTRL-KEY PRESSED.

You'll see something like this:

![http://winterdrache.de/data/Hovering-WITH-Ctrl.jpg](http://winterdrache.de/data/Hovering-WITH-Ctrl.jpg)

Notice how a) the popup has expanded with a peek of the function's implementation; and b) the function name is now underlined and becomes a clickable link.

9. Start debugging with the included Launch configuration. If you haven't forgotten to set the breakpoint in 6. the debugger will stop at line 11.

10. Now hover over the word fun as in 7. NOTHING HAPPENS. NO POPUP WINDOW. THAT'S THE ISSUE!

11. Try the same with Ctrl-key pressed. You'll see something like this:

![http://winterdrache.de/data/Hovering-WITH-Ctrl.jpg](http://winterdrache.de/data/Hovering-WITH-Ctrl-while-debugging.jpg)

Notice how the word is still underlined as a clickable link. So that part of the Ctrl-Hovering works. But again there is NO POPUP. THAT'S THE ISSUE.

More notes:

* If the project had multiple files, the hovers (both with and without Ctrl-) would work in all files EXCEPT for the one that's currently selected in the call stack.
* The issue quite obviously has to do with the hover functionality that presents you with a popup of the variable value when hovering over a variable. However that hover obviously cannot appear when hovering over a function (because it has no value).
* The 1st feature request is to present the normal CTRL-HOVER when CTRL-KEY is pressed while debugging EVEN OVER VARIABLES, because there is currently no special debug hover for Ctrl, so this does not override any current debugging functionality. The fact that VS Code does react to Ctrl-key pressed hovers even during debugging is demonstrated by the function name still becoming a clickable link.
* The 2nd feature request is to always show the standard hover when hovering over a function name, because there is no debug hover for functions, so again showing the standard hover does not override any debugging functionality.

**Comment by isidorn** [comment]
Thanks for providing more information.
However that is designed behavior for now. Debug simply hides all other hovers while a debug session is started.
I have created a follow up item which would do exactly what you want.
https://github.com/Microsoft/vscode/issues/49131
