### ISSUE TITLE
Feature Request/Bug: Make it possible to copy regex-search error

### ISSUE THREAD

**Issue by TryingToImprove** [Microsoft/vscode#48996]
If you have a invalid error in your regex, it is not possible to select and copy the error message.

![image](https://user-images.githubusercontent.com/1690457/39467337-d2d4c682-4d2d-11e8-8e47-3331aacb22aa.png)

**Comment by roblourens** [comment]
I think an error message like that should be copyable. Hmm... I will have to

- Make the inputbox's contextView focusable and selectable
- Consider the inputbox still focused if focus moves inside the contextView, so that it will only be hidden if focus moves outside of the inputbox and outside of the contextView

This would impact all inputboxes with context views, including the one used by the file explorer. Or I could scope it to just the search/find inputboxes. Any opinion @bpasero?

**Comment by bpasero** [comment]
What is the use case to copy this error?

**Comment by TryingToImprove** [comment]
Mainly searching for help on google for why it is failing..

**Comment by bpasero** [comment]
I think it would be OK to allow to click into this thing to copy it as long as it dismisses quickly.
