### ISSUE TITLE
Markdown links do not allow escaping closing paren correctly

### ISSUE THREAD

**Issue by sundeepbhatia** [Microsoft/vscode#49011]
- VSCode Version: 1.20.1
- OS Version: Windows 10 version 1703

Steps to Reproduce:

1. Type the following:

```md
[A link](http://ThisUrlhasParens/A_link(in_parens))
```
2. Expect link to either go to 2nd closing parenthesis or allow escaping closing parenthesis
3. The link stops on first closing parenthesis
4. Note: UrlEncoding i.e. Using %29 instead of closing parenthesis does works

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Fixed by bd29afad2c5bff17c1dfdd96a26326cbb733746f

Fix will be in the next vscode insiders build

**Comment by Tyriar** [comment]
I'm not sure this is fixed, the scopes change inside the inner parens and they shouldn't since it's just link text:

![image](https://user-images.githubusercontent.com/2193314/40750426-24539e8e-641c-11e8-9eb6-41e5e1f09692.png)
![image](https://user-images.githubusercontent.com/2193314/40750443-2e92cc12-641c-11e8-922c-88d27dbd4d8f.png)
![image](https://user-images.githubusercontent.com/2193314/40750446-342242e8-641c-11e8-8fdd-54340a871f73.png)

**Comment by mjbvz** [comment]
Thanks for taking a look @Tyriar. I've opened https://github.com/Microsoft/vscode-markdown-tm-grammar/issues/18 to track this highlighting issue.

For this issue, can you please confirm that you can click on the link properly and it opens the correct url. That should now work as expected
