### ISSUE TITLE
API that allows code action providers to reliably get the current selection

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#49024]
**Problem**
Extensions that use `CodeActionProvider` to return refactorings almost always want to compute refactorings based on the current selection. The `range` current passed to a `CodeActionProvider` may be the selection or it may be the range of a diagnostic within the current document. 

As a workaround, extensions have to try getting the selection from `activeTextEditor`

**Proposal**

Add a `selection` property to `CodeActionContext`. This optional property would have the current selection in the document. 

**Alternative designs**

- Introduce a `CodeActionProvider2` that has more deterministic behavior for `range`.
- When registering a `CodeActionProvider`, allow extensions to request that `range` should always be the current selection

/cc @kieferrm

**Comment by jrieken** [comment]
I think adding an optional selection to the context is fair. 

We could also tweak the behaviour and always pass the current selection (as range). We are almost there anyways. A long while ago the logic was a bit more complex and the range would auto-expand to the current word etc. Because we got rid of that we might be able to make the final step. 

Also, we should be able to make the following non-breaking API change (since `Selection extends Range`)

```ts
provideCodeActions(document: TextDocument, rangeOrSelection: Range | Selection, context: CodeActionContext, token: CancellationToken): ProviderResult<(Command | CodeAction)[]>;

```

**Comment by xsburg** [comment]
I really like this change as an extension author, that's what I originally expected from the `range` parameter (as the docs don't clearly describe how the range is computed).

As for the way to introduce the change, given that the logic has already been simplified, I would prefer if we clearly state what the range is

```javascript
provideCodeActions(document: TextDocument, selection: Selection, context: CodeActionContext, token: CancellationToken): ProviderResult<(Command | CodeAction)[]>;
```

It's still a non-breaking change but this way I can rely on this always being a selection.

**Comment by jrieken** [comment]
> It's still a non-breaking change but this way I can rely on this always being a selection.

Well, it must not always be a selection, e.g. when calling it for the code-action-on-save scenario. Sure we could call it with a selection but we don't want to send the wrong message, e.g. the use didn't really select something here.

**Comment by xsburg** [comment]
I see, it's in fact the implementation that I automatically assumed for the code-action-on-save feature. That's because I would probably treat the parameter as document selection inside the extension anyway.

**Comment by srivatsn** [comment]
> We could also tweak the behaviour and always pass the current selection (as range). 

I think this would break a few providers functionally. For eg. if I just click at some location that has diagnostics, the Java provider returns codeactions but I've noticed that wasn't happening if I invoke the executeCodeActionProviders API with a zero-length span (see https://github.com/Microsoft/vscode/issues/45713). So if we change the range being passed in to just the current selection, that would result in those codeactions being missed out.

I think adding the selection to the context might be preferable.

Also tagging @DustinCampbell since the C# extension also returns different set of codeactions based on the editor selection

**Comment by jrieken** [comment]
> I think this would break a few providers functionally. For eg. if I just click at some location that has diagnostics, the Java provider returns codeactions but I've noticed that wasn't happening if I invoke the executeCodeActionProviders API with a zero-length span (see #45713)

Sure about that? Today, unless you are on a diagnostic or with an empty selection inside whitespace, the selection is used. See https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/codeAction/codeActionModel.ts#L43. My guess is, that us using the selection (as range) is quite common because of that.

**Comment by srivatsn** [comment]
>  Today, unless you are on a diagnostic 

I'm talking about this case when the user clicks on a location with a diagnostic, we would have passed in the span of the diagnostic before and with the proposal to always pass in the user selection we'd pass in an empty selection and get back no codeactions.

**Comment by jrieken** [comment]
Yeah, that's the question. We do provide the diagnostics in question in the context but folks might not use diagnostics as code action seed but the range. That's something we should check before making a change...

**Comment by mjbvz** [comment]
@jrieken Looked through the top 1000 extensions. Maybe ~50  have a code action provider. About half use the diagnostics or just ignore the range entirely. A handful seem like they would be broken by making `range` be the selection. A good example is in spellright: https://github.com/bartosz-antosik/vscode-spellright/blob/ab73ebe02ca3a11a8a86095311e6dcd82a8a4d70/src/spellright.js#L1396

This extension and others assume that if there is a diagnostic, the `range` will at least include the diagnostic. If the `range` is just the selection, this is no longer true

**Comment by jrieken** [comment]
> A handful seem like they would be broken by making range be the selection.

That doesn't sound so bad TBH. I would take the risk unless there is an extension with many, many installs that cannot update to the new behaviour.

**Comment by mjbvz** [comment]
To verify, create a simple code action provider extension and verify that the actual user selection is always passed to the provider, even when the code actions are requested inside an error span
