### ISSUE TITLE
Add setting to control UI tooltip delay

### ISSUE THREAD

**Issue by monkeyhybrid** [microsoft/vscode#49047]
When hovering over UI elements such as icons, and filenames in Explorer, the associated tooltip takes approximately 1 second to display, which can be annoyingly sluggish whilst learning the UI. As the ideal delay is subjective, it would be nice to be able to control this value in user settings.

**Comment by monkeyhybrid** [comment]
Apologies for the noise, but I understand from the assigned labels that this issue is more applicable upstream, i.e. Electron. I will raise a ticket there, but I'm just wondering if I should close this issue, or leave it open for a time when (if) it's implemented upstream?

**Comment by nick-walt** [comment]
@monkeyhybrid I feel that it is definitely good to keep this issue focused on VSCode, as that is where the problem is experienced. Electron, as a dependency, should be a consideration for the VSCode team and not for users' posting about visual UX/UI experiences.

I also experience that, with mouse use, the tool tips obscure text I want to select or click on to insert the cursor. Interestingly, the tips seem to popup more often when editing CSS documents (in contrast with HTML documents). This appears to be due to the significantly increased density of CSS properties that cause tool tip activation.

VSCode's CSS editor also treats the CSS values as triggers (not just the properties) for tool tips, which increases the trigger surface area significantly. Contrast this with HTML documents, in which only the tags properties trigger a tool tip and not the attributes or content within tags.

The Suggestions section in the Settings/JSON is quite comprehensive but could not see anything for tool tips. `editor.suggest.tooltip...` or `editor.tooltip...` would work well.

Additional options in settings for users to control tool tip behavior might include:
 - disable tool tip select-ability, so that a click instantly removes it and selects the underlying text;
 - tool tip trigger delay;
 - option to trigger on just tags/properties/keys or also values (such as CSS and JSON values);
 - set location of tool tip to include left or right of cursor;
 - dismiss tool tip as soon as cursor is moved;

**Comment by monkeyhybrid** [comment]
I like and agree with everything you've said there, @nick-walt. I'm not sure how much of this can be achieved without upstream (Electron) adding some tooltip control though.
