### ISSUE TITLE
Align SCM viewlet with ViewsViewlet

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#49054]
Currently, the SCM Viewlet and the Views Viewlet use separate implementations of the contributable views model. Additionally, SCM is a frankenstein of views: it manages part of its views and merges that with contributable views.

Suggestion:

- [x] Use the `ContributableViewsModel` in `ViewsViewlet` - #48535
- [x] Move SCM views to contributable views
- [x] Have that the selection within the `Source Control Providers` view only toggles `setVisible()` in the `ContributableViewsModel`
- [x] Remove knowledge about SCM in ViewsService

**Comment by sandy081** [comment]
@joaomoreno Adopted views model in `ViewContainerViewlet` aka `ViewsViewlet`. Since SCM Viewlet is not completely a `ViewContainerViewlet` and it has some unregistered views, I have to incorporate the knowledge of SCM viewlet in `ViewsService` to skip enablement/disablement. See - #fc6c30ed3158d2e4b30d767e97635b984c9fd32c

**Comment by bpasero** [comment]
![image](https://user-images.githubusercontent.com/900690/49581792-61032d00-f953-11e8-80ee-0fba2d35df2e.png)

**Comment by joaomoreno** [comment]
@bpasero 

![done](https://media.giphy.com/media/26uf9FlttgyOa2zrq/giphy.gif)

**Comment by bpasero** [comment]
![nice](https://media.giphy.com/media/HGYWEaaPkTxjW/giphy.gif)

**Comment by joaomoreno** [comment]
@sandy081 Can you verify w/ code review?
