### ISSUE TITLE
Manage extension is no-op for statusbarItem

### ISSUE THREAD

**Issue by nandiniYeltiwar** [Microsoft/vscode#49135]
- VSCode Version: 1.23.0-insiders
- OS Version: windows 10 build 16299

Steps to Reproduce:
1. Create an extension with statusBarItem 
2. Install the extension
3. Right click on the status bar item 
4. Click on Manage extension

There is no action after clicking manage extension.

**Comment by nandiniYeltiwar** [comment]
The extension I am looking at is VS Live Share.

**Comment by bpasero** [comment]
I can reproduce, looks like a regression. I am accepting a PR here if the fix is small.

**Comment by bpasero** [comment]
@sandy081 actually this looks like a bug in your world:

![image](https://user-images.githubusercontent.com/900690/39775570-9bb74b3a-52fe-11e8-85b6-733fb3e9fe1f.png)

![image](https://user-images.githubusercontent.com/900690/39775617-c1d3fcdc-52fe-11e8-8dd5-1d8f85212ab2.png)

**Comment by sandy081** [comment]
@bpasero It's a bug: Yes/No. This is happening because this particular extension has changed the case of `publisher` while publishing. Hence market place has `publisher` id in different cases and hence our checks are failing.

We already take care such scenarios when extension name case changes. I would extend that solution for publisher too.
