### ISSUE TITLE
View containers in activity bar are still visible if there is no view inside

### ISSUE THREAD

**Issue by vbfox** [Microsoft/vscode#49145]
- VSCode Version: 1.23.0

Steps to Reproduce:

1. Add a new item to `viewContainers/activitybar` in an extension
2. Hide all the views of this container conditionally (In the Ionide F# case the "project" view only make sense if a "project" or "solution" file is found)
3. Notice that the icon is still visible but empty

It also seem that the container icon is always visible even when the extension isn't loaded (no F# file in workspace). With 10+ extensions installed if each add an icon the activity bar will be cluttered pretty fast (While it's not needed, few workspace activate all my extensions).

Note: I found a few issue about the configurability (https://github.com/Microsoft/vscode/issues/48704 & https://github.com/Microsoft/vscode/issues/48706) but none about the fact that empty views look buggy.

Ping @Krzysztof-Cieslak

**Comment by vbfox** [comment]
My suggestion would be to by default hide them when there is no **displayable** view inside (Counting user-hidden views as displayable as a gesture exists to show them, but not views hidden via `when`).

Alternatively it can be done by extensions themselves if #48704 is done but it's a little less practical if multiple extensions wants to share a container.

In the current state I fear that the activity bar will slowly creep with as much icons as languages I have installed, with only one or two of them containing something when a user open a workspace.

**Comment by sandy081** [comment]
To verify:

- Register a view container in activity bar using `viewsContainers` extension point. For example:
```json
"contributes": {
	"viewsContainers": {
		"activitybar": [
                        {
			    "id": "test",
			    "title": "Test",
			     "icon": "resources/test.svg"
		        }
                  ]
	}
}
```
- Add views to the above registered view container with `when` context . For example:
```json
"contributes": {
	"views": {
		"test": [
			{
				"id": "myview",
				"name": "My View",
                "when": "somecontext"
			}
		]
	}
}
```
- You can implement the view by referring to [documentation](https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributesviews) and [samples] (https://github.com/Microsoft/vscode-extension-samples/tree/master/tree-view-sample). Refer to `jsonOutline` example that uses `when` property.

Verify that the view container is not visible when
- No views are registered to the container
- All views are hidden because of their `when` condition

Otherwise, view container is shown even if user hides the views.

**Comment by aeschli** [comment]
Verified with the tree-view-sample
