### ISSUE TITLE
Use one extension per language pack

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#49178]
Currently we have two extensions per language pack. One for stable and other for insiders. I do not think this is the right approach and will confuses users while searching the language pack from the market place as it shows two same extensions. This is not a good model to be followed to support insiders and stable. The preferred approach is as follows (suggested by @joaomoreno)

- Have one extension per language pack
- Publish the extension for the stable by setting the right VS Code engine property. For example
```json
"version": "1",
"engines": {
    "vscode": "1.23.0"
  }
```
- Once the insiders starts rolling and if there are changes in translations, publish the extension with engine matching to vscode insiders
```json
"version": "2",
"engines": {
    "vscode": "1.24.0"
  }
```
- If there are fixes in stable version (recovery builds) publish the extension branching out from extension version `1` and also bump extension version for insiders 
```json
"version": "3",
"engines": {
    "vscode": "1.23.1"
  }
```
```json
"version": "4",
"engines": {
    "vscode": "1.24.0"
  }
```
- When VS Code releases a new stable `1.24.0` users will get automatically updates for extension version 4.

This way, users will always see single language pack and extension provides correct vscode engine property and vscode installs right version of extension for the given user.

@dbaeumer @danyeh @joaomoreno FYI

**Comment by joaomoreno** [comment]
I was surprised to learn yesterday that we're publishing insider flavours of translation exceptions. As @sandy081 says, this is not needed.

The compatibility between a translation extension and VS Code itself should only be based on version numbers, not quality labels. This is because of the following rule: next month's Stable is today's Insiders.

My personal recommendation for versioning such extensions is:

- Use the same major and minor version numbers of the VS Code release you want to target.
- Use the `engines` field to define your compatibility with VS Code.
- Use the patch version number to publish fixes to each `major.minor` release.

---

**Example**

During April, VS Code Stable was 1.22 and VS Code Insiders was 1.23. Imagine that during that month I started working on the Esperanto extension.

1. I create my Esperanto extension by translating the entire VS Code 1.22 string collection.
2. I publish my Esperanto extension under version `1.22.0`, using `engines.vscode: ^1.22.0`
3. Later, I see that a few of my users use Insiders. I would also like to keep myself busy and start translating ahead of a stable release. So, I decide to translate all new Insider strings. Once done, I can publish another version of my Esperanto extension using number `1.23.0` and `engines.vscode: ^1.23.0`
4. During the same month of April, VS Code releases a recovery release 1.22.1. It comes with new strings. I go back to my extension's branch which has 1.22 strings, translate the new ones and publish a new version of my Esperanto extension using number `1.22.1` and `engines.vscode: ^1.22.1`.

And so on, and so forth.

Due to the fact that VS Code respects the `engines.vscode` property when querying and installing extensions, there is no need to duplicate extensions in the Marketplace and write messy code which behaves differently based on whether it is VS Code Stable or Insider.

**Comment by dbaeumer** [comment]
This makes total sense to me.

**Comment by sandy081** [comment]
Translations team changed the approach as per the suggestion here

**Comment by aeschli** [comment]
Verified that there's only a single extension for pt-br and that versions are different when installed on stable and insiders.
