### ISSUE TITLE
Updataing intellisense

### ISSUE THREAD

**Issue by changmu811** [Microsoft/vscode#49171]
Issue Type: <b>Feature Request</b>

Updataing intellisense to   stop working.

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T16:44:10.813Z)
OS version: Windows_NT ia32 10.0.16299

**Comment by mjbvz** [comment]
This issue is not actionable. Please see [this guide](https://github.com/Microsoft/vscode/blob/master/CONTRIBUTING.md#writing-good-bug-reports-and-feature-requests) for suggestion on how to report an issue. For example, describe:

* What were you trying to do?
* What went wrong?
* What steps lead up to it going wrong?
