### ISSUE TITLE
Themes don't support colors for a current debug line.

### ISSUE THREAD

**Issue by onlineservices283418** [microsoft/vscode#49185]
Issue Type: <b>Feature Request</b>

Please add support for theming a current debug line. It seems there is no way to customize it.

![debugline](https://user-images.githubusercontent.com/29972256/39617627-0f77b524-4f89-11e8-9552-b7eea0deacb3.png)

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T16:44:55.614Z)
OS version: Windows_NT x64 10.0.16299

**Comment by isidorn** [comment]
This is a fair feature request however it is a bit more elaborated since it would require to customize:
* color of an editor decoration
* color of a glyph margin icon

This currently does not seem to be in reach.
[Code pointer](https://github.com/Microsoft/vscode/blob/f6ccf070801009d468c294b1e7316b3fab068b28/src/vs/workbench/parts/debug/browser/debugEditorModelManager.ts#L305)

**Comment by isidorn** [comment]
This is actually implemented now.
Check them out 
```json
"editor.focusedStackFrameHighlightBackground": "#ff0000",
"editor.stackFrameHighlightBackground": "#ff0000",
```
