### ISSUE TITLE
Code organisation multiple issues including flow types

### ISSUE THREAD

**Issue by IljaDaderko** [Microsoft/vscode#49201]
- VSCode Version:  1.23.0
- OS Version: macOS High siearra

Steps to Reproduce:

1. Enable import organisation on save
2. Create flow file like this

```
// @flow
import React, { type Node } from "React"
```

3. Save the file

You will see that `type` bit is removed by import organiser.

4. Create file like this

```
import onboarding from "./_onboarding";

export default {
  onboarding
};
```

5. Save it

You will see that it completely removes the import.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by mjbvz** [comment]
The first issue is that the built-in js / ts extension does not support flow. Try installing the flow extension and disabling the build-in `JavaScript and TypeScript language features` extensions

The second issue is tracked by https://github.com/Microsoft/TypeScript/issues/23308 and should be fixed in VS Code insiders
