### ISSUE TITLE
Npm Scripts explorer, setting to run by default instead of open?

### ISSUE THREAD

**Issue by albinotonnina** [Microsoft/vscode#49204]
- VSCode Version: 1.23.0
- OS Version: -

Steps to Reproduce:

1. enable with {  "npm.enableScriptExplorer": true}
2. click on a npm script

Feature request:

Similarly [to this extension](https://marketplace.visualstudio.com/items?itemName=traBpUkciP.vscode-npm-scripts), would it be useful for some people to have a setting that by default, on click, run a task instead of opening it in the package.json? 

Thanks!

Does this issue occur when all extensions are disabled?: Yes

**Comment by albinotonnina** [comment]
Nope bot, doesn't look a dup to me but you know more 👍

**Comment by albinotonnina** [comment]
Hello @egamma! Thank you!
This solves the issue but I like #49282 even more :)

**Comment by egamma** [comment]
>To be honest with you I don't know why the default click action should be 'open' in that panel.

Initial user feedback was that it is too confusing to run a task on single click and the explorer should more behave like an outline and the single click is also consistent with the explorer. We will also add support for a double click action and triggering a task on double click make sense to me.

 The PR looks good to me.

**Comment by albinotonnina** [comment]
Hello @egamma, thanks for your reply.
You would open on single click and run on dblclick? That would work I guess! 
Wasn’t expecting that result from user feedback. I guess I’m used to the behaviour that the aforementioned plugin has, or webstorm.

**Comment by borgfriend** [comment]
Personally I would like to run tasks via double click on a task. However I do understand that some people prefer to open the config instead, thus my PR adding it as a configuration option.

I like the idea with the "run" button at the end of the line. It is only visible when you hover over the task. This type of interaction reminds me more of the "Edit Button" from the User Settings / settings.json.

Mockup Screenshot:
![2018-05-08 12_34_43-npm scripts explorer setting to run by default instead of open_ issue 49204](https://user-images.githubusercontent.com/3630448/39762520-27d31e10-52db-11e8-84d3-e3b55e06956c.png)

My suggestion would be to switch the two Icons. 
Depending on the task I would either display a "run" icon or the "debug" icon.
(if the task includes --inspect then debug as default) 

With the current solution there would be no easy way to enter debug mode. 
Maybe shift-lmb / ctrl-lmb on the run button to open in debug mode?

**Comment by egamma** [comment]
Added a setting npm.scriptExplorerAction that can be set to either open and run. This should address this feature request.
