### ISSUE TITLE
Events that modify state don't seem to propogate throughout the UI

### ISSUE THREAD

**Issue by josh-tepper** [Microsoft/vscode#49216]
Issue Type: <b>Bug</b>

I just upgraded to 1.23 last night.  Something is broken with updates throughout the UI:
- When a file is updated by checking out another branch on the command line, the changes are no longer reflected in the editor until I close/re-open the file
- When a file is modified by editing I no longer see the chnanges reflected in the source control panel until I refresh
- I checked out a different branch on the command line (not inside of vscode), and the branch indicator on the left side of the bottom status bar didn't update, even after a long period of time.

In all of these cases, these things used to "just work" prior to the 1.23 update

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T15:23:14.634Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (3.79GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.2.11
vscode-docker|Pet|0.0.26
ActiveFileInStatusBar|Ros|1.0.3
solargraph|cas|0.16.0
gitignore|cod|0.5.0
githistory|don|0.4.0
gitlens|eam|8.2.4
jsonnet|hep|0.1.0
git-tree-compare|let|1.2.1
Go|luk|0.6.78
python|ms-|2018.4.0
cpptools|ms-|0.16.1
csharp|ms-|1.14.0
Ruby|reb|0.18.0
java|red|0.24.0
vscode-open-in-github|sys|1.7.0
vscode-java-debug|vsc|0.9.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.5.0
vscode-maven|vsc|0.7.0
vscode-proto3|zxh|0.2.1

</details>

**Comment by joaomoreno** [comment]
@bpasero File events

**Comment by bpasero** [comment]
VS Code is using different file watching strategies depending on your OS and your setup. 

**First thing to check:**
* [ ] I verified that the issue still reproduces in our insiders version (https://code.visualstudio.com/insiders/)
* [ ] I verified that this issue is happening outside of a `node_modules` folder. Our file watcher ignores this folder!

**To find out more about this issue, please first answer this:**
* [ ] What OS are you on
* [ ] Does this happen from an empty workspace, a single-folder workspace or a multi-root workspace?
* [ ] Do you have `files.useExperimentalFileWatcher: true` configured in settings?
* [ ] What is your configured `files.watcherExclude` setting?

**Then please answer the following depending on your setup:**
* [ ] It reproduces with any folder or workspace you open
* [ ] The files/folders you open are on your local disk and not on a network share nor a UNC drive
* [ ] The files/folders you open are not behind a symbolic link
* [ ] The folder(s) opened use the exact same casing as they are on disk
* [ ] It reproduces when I make a change to the file from another VS Code window (either from the editor or the file explorer)

**Then please attach the output of our development console**
* run `code --verbose` from the command line
* perform the action that causes you to not see the file change in VS Code
* attach the output from the console (`Help` > `Toggle Developer Tools` > `Console`)

Thanks for taking the time to fill out this questionnaire.

**Comment by josh-tepper** [comment]
@joaomoreno -- this issue hasn't reproduced itself since my original post.  To be honest, I didn't have enough time to try to reproduce it in earnest.   That said, I'll re-open/try to work on this if this re-occurs.
