### ISSUE TITLE
Organize Imports adding semicolons despite semi:false

### ISSUE THREAD

**Issue by ShMcK** [Microsoft/vscode#49223]
- VSCode Version: 1.23.0
- OS Version: Mac 10.13

"organize imports" automatically adds semi colons to your import statements, even when eslint & prettier set semicolons to false.

```json
 "editor.codeActionsOnSave": {
    "source.organizeImports": true
  },
  "prettier.semi": false,
```

Steps to Reproduce:

1. Set prettier & eslint semi colons to false
2. Run save on a list of unordered imports
3. See that additional semi colons are added at the end

**Comment by rebornix** [comment]
AFAIK, the organize imports are provided by TypeScript extension, which doesn't read options from other extensions.

**Comment by mzygmunt** [comment]
I think it would be good if we could turn off the semicolons in `organizImports` configuration.

**Comment by mjbvz** [comment]
Yes, we don't use settings from other extensions.

Enabling/disabling semicolons in generated imports is tracked by https://github.com/Microsoft/TypeScript/issues/19882

**Comment by jleclanche** [comment]
For the record, adding `"editor.formatOnSave": true` to the config sort of solves that issue. The problem is that the typescript import sorting will not follow prettier rules if you're using prettier, so something like this (from prettier):

```
import {
    a,
    b,
    c,
    d,
    e,
    f,
    g,
} from "./interfaces";
```

may get turned into something like this (by typescript):
```
import { a, b, c, d, e, f, g, ... } from "./interfaces";
```

And then back into the original. With zero meaningful AST changes, and causing a flash of text on save. Super annoying :(

**Comment by jongear** [comment]
I can confirm this also happens in javascript files utilizing babel. Adding `"editor.formatOnSave": true` forces prettier to run and force cleanup the semicolons after organizing

```json
"editor.codeActionsOnSave": {
  "source.organizeImports": true
},
"editor.formatOnSave": true,
```
