### ISSUE TITLE
Add missing screenshot/icon and metadata to .deb package screen in software center

### ISSUE THREAD

**Issue by bgashler1** [Microsoft/vscode#4923]
- VSCode Version: 0.10.13-insider
- OS Version: Ubuntu 14.04 LTS

<img width="1440" alt="screen shot 2016-04-04 at 9 55 22 am" src="https://cloud.githubusercontent.com/assets/11839736/14255999/cecc2670-fa4b-11e5-8d97-6c116ef2dfe9.png">

Steps to Reproduce:

1. Open the .deb package as if you were going to install it
2. Note the page is missing its screenshot and icon as well as the fields for license and updates.

**Comment by Tyriar** [comment]
When this was previously reported, basically this is not possible as it requires an upload to Ubuntu's software repositor(ies). The reason we can't do this, apart from the fact it's inconvenient and difficult to automate, is because [our license for official builds](https://code.visualstudio.com/License/) is not compatible with [Ubuntu's license](http://www.ubuntu.com/about/about-ubuntu/licensing).
