### ISSUE TITLE
Tooltip font size problem on high resolution screen

### ISSUE THREAD

**Issue by uri65** [microsoft/vscode#49280]
![2018-05-05 22_21_44-greenshot image editor](https://user-images.githubusercontent.com/28627474/39667342-faf3a370-50b3-11e8-8f70-bb39b88e1a88.png)
Issue Type: <b>Bug</b>

On my laptop screen with resolution of 3840x2160 the tooltip font size is extremely small. On attached image please see the "Explorer" tool tip.

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T16:44:55.614Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.85GB (5.60GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.4.0
cpptools|ms-|0.16.1
csharp|ms-|1.14.0

</details>

**Comment by bpasero** [comment]
This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to the code. As such, I will go ahead and close it. If you can identify the component that is causing the issue, please report it upstream:
* for UI, OS integration: https://github.com/electron/electron
* for Rendering: https://bugs.chromium.org/p/chromium/issues/list
* for file IO: https://github.com/nodejs/node

Thanks for understanding.
