### ISSUE TITLE
Add vscode.executeSearchProvider

### ISSUE THREAD

**Issue by jacobdufault** [Microsoft/vscode#49323]
There are commands for executing existing providers, but none for search.

Existing `vscode.execute*` commands:

```
vscode.executeWorkspaceSymbolProvider
vscode.executeDefinitionProvider
vscode.executeTypeDefinitionProvider
vscode.executeImplementationProvider
vscode.executeHoverProvider
vscode.executeDocumentHighlights
vscode.executeReferenceProvider
vscode.executeDocumentRenameProvider
vscode.executeSignatureHelpProvider
vscode.executeDocumentSymbolProvider
vscode.executeCompletionItemProvider
vscode.executeCodeActionProvider
vscode.executeCodeLensProvider
vscode.executeFormatDocumentProvider
vscode.executeFormatRangeProvider
vscode.executeFormatOnTypeProvider
vscode.executeLinkProvider
vscode.executeTaskProvider
vscode.executeDocumentColorProvider
vscode.executeColorPresentationProvider
```

**Comment by jrieken** [comment]
We will add real API, similar to the existing `findFiles`-api. No plans for commands.

**Comment by jrieken** [comment]
Nothing is set in stone but for search I'd say within the next 3 months. For language commands there are currently no such plans.

**Comment by garygreen** [comment]
@jrieken I'm also interested in a search api - is there an open issue for it? Would the search api allow you to query it and get the list of results (same as the current grep search panel where you can set include/exclude files etc and it'll give you a list of results) ? Reason why I'm keen on it is because I would like to create my own extension for showing the search results in a new tab/text document rather than in the pane (and formatted in a different way, similar to Sublime text). Currently, there doesn't appear to be any way to query the search API (which uses ripgrep I believe?)
