### ISSUE TITLE
color picker box

### ISSUE THREAD

**Issue by svipas** [microsoft/vscode#49388]
- VSCode Version: 1.23.0
- OS Version: macOS

![image](https://user-images.githubusercontent.com/10441177/39715769-fe278b22-5236-11e8-8e14-65604c00afea.png)

I just moving items up and down. It also disappears after some time. As you can I just collected all boxes from items below and they are right now above.

**Comment by aeschli** [comment]
IMO it's an acceptable behavior.

**Comment by svipben** [comment]
For me it seems like a problem, also, I don't know if it's related but damn editing color theme JSON is so laggy, I need to wait a lot of time while it initializes all color boxes and enables IntelliSense, Git, etc.

About color boxes, I believe they shouldn't move and position should be absolute and don't care about moving objects because for the short time it will be like it's in the screenshot below which seems like a bug for me. Of course good thing it will normalize after some time, but that temporary confusion seems not a feature to me 😄

**Comment by svipben** [comment]
![image](https://user-images.githubusercontent.com/10441177/39920727-c5a4b80a-5520-11e8-9463-9f2f914cbf28.png)

/cc @aeschli @isidorn @rebornix

**Comment by rebornix** [comment]
I haven't seen this issue for a while so closing it for now but we can reopen it if anyone else is seeing it.
