### ISSUE TITLE
Add a top-level `Terminal` menu for better discoverability

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#49477]
The purpose of a new "Terminal" menu would be to boost discoverability of the terminal itself and some of its features.

**Comment by Tyriar** [comment]
WIP pushed to https://github.com/Microsoft/vscode/tree/tyriar/49477_terminal_menu

![image](https://user-images.githubusercontent.com/2193314/40455899-bf1e875e-5ea3-11e8-9398-98a804bc0b44.png)

**Comment by Tyriar** [comment]
I more cut down alternative:

![image](https://user-images.githubusercontent.com/2193314/40547580-2e887c1e-5fe7-11e8-955f-0a016dcb0f46.png)

**Comment by Tyriar** [comment]
As part of this, some screenshots should be updated on the website to include the new menu.

**Comment by beastdestroyer** [comment]
I personally feel that just adding a 'Terminal'button in the status bar at the bottom could. do some good too, since whilst I do like this top-level menu (first coming to VSCode, I had no idea how to open the terminal), a simple button which auto shows the terminal (or equivalent to dragging from bottom and clicking terminal/Create terminal [? ]) could be just as effective - this is a personal opinion however

**Comment by nijikokun** [comment]
I agree with @beastdestroyer because when you're using applications in full screen and using the four finger swipe mode with macOS, this menu is not visible unless you move your curser to the top, and for the majority of applications in this working environment you'll never do that except by accident.

Having it closer to the terminal and on the status bar would be much better.

**Comment by Tyriar** [comment]
The problem with something in the status bar is that space is very limited and also then the terminal is treated a differently to problems, output, etc. Currently the terminal is visible when you have any panel open and also buried away in the view menu. Adding yet another button to the status bar which is already space limited (extensions contribute to it and currently has no overflow strategy) would contribute to bloat imo. I'll go ahead with the menu and see what feedback comes in from users of Insiders.
