### ISSUE TITLE
Cannot delete files on a mounted file system

### ISSUE THREAD

**Issue by tinganho** [Microsoft/vscode#4959]
I use sshfs to mount a file system from Ubuntu on my Mac. When I try to delete files I get the following error message:

<img width="1411" alt="screen shot 2016-04-05 at 17 07 59" src="https://cloud.githubusercontent.com/assets/1324476/14279702/5d8e29ce-fb61-11e5-9268-3311e49a8db3.png">

And when I click delete permanently it doesn't delete the file. It would be good if it could delete directly without a "Delete Permanently?" message.

**Comment by bpasero** [comment]
Fixed for GA. You can give it a try from our insiders release today: http://code.visualstudio.com/Download#insiders

**Comment by tinganho** [comment]
It works on the insiders. Though it always fail on the first attempt. I didn't have this issue when using SublimeText. I wonder why it doesn't work directly? Could it be case sensitivity problems?

**Comment by bpasero** [comment]
It can well be that the trash feature is not supported in this mounted drive environment. Maybe Sublime falls back to just deleting in that case?

**Comment by tobia** [comment]
@bpasero I'm also doing all my development with `sshfs` on Mac OS X and I can confirm it does not support the system-wide Trash feature (I don't know why and I've never really needed it.)

In Sublime it works similarly as VSCode: 

1. Dialog to confirm delete operation
2. Dialog to confirm permanent delete

The ***crucial*** difference is that in Sublime both dialogs are modal, meaning that you can confirm with Enter and cancel with Esc. 

In VSCode only 1. is modal, while 2. is a notification bar, with no obvious way to confirm or cancel the operation from the keyboard.

It would be better if 2. was modal too, because there's no reason to postpone the choice whether to really delete or not (it's not like the Trash might magically reappear) and one should to be able to do so with Enter / Esc.

Moreover, if you could add an option to skip dialog 2. when Trash is not available, that would be helpful for those of us who regularly use filesystems that don't support trash.
