### ISSUE TITLE
Format page not working.

### ISSUE THREAD

**Issue by Yashwanth-T** [Microsoft/vscode#49610]
Issue Type: <b>Bug</b>

Document format not working and it is freezing all other features like peek definitions, etc

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T15:23:19.356Z)
OS version: Linux x64 4.13.0-39-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2684)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 4, 3|
|Memory (System)|15.46GB (4.67GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|2.0.1
material-icon-theme|PKi|3.4.0
code-gnu-global|aus|0.2.2
githistory|don|0.4.0
gitlens|eam|8.2.4
Angular2|joh|6.0.0
vscode-clang|mit|0.2.2
atom-keybindings|ms-|3.0.4
cpptools|ms-|0.17.0
vscode-run-git-difftool|nar|0.0.5
diff|raf|0.0.1
vscode-icons|rob|7.23.0
partial-diff|ryu|1.1.0
cmake|twx|0.0.17
clang-format|xav|1.6.2

(4 theme extensions excluded)

</details>

**Comment by Yashwanth-T** [comment]
No

**Comment by isidorn** [comment]
Can you repreoduce this if you disable all your extensions?
Can you reproduce with vscode insiders https://code.visualstudio.com/insiders/

**Comment by ferreteleco** [comment]
Same there. Since version 1.23 formatting is not responding (update to 1.23.1 does not fix the problem). Tried the following:

- disabling all extensions. 
- increasing Save and code actions timeouts.

None of those worked for me.

Additional information: if I reload window, functionalities like peek / goto definition / declaration and intelliSense recomendations work but when I try to format the file everything blows up.

![untitled](https://user-images.githubusercontent.com/3154366/39920440-58bb2962-5517-11e8-9ea9-a0f0d96b92ec.png)

**Comment by Yashwanth-T** [comment]
Yes, Same with me as well

**Comment by ferreteleco** [comment]
Any more information needed @isidorn ? Any other related issues?

**Comment by ferreteleco** [comment]
Fixed for me wuth the 0.17.3 update of vscode/ccpptools
