### ISSUE TITLE
Deleting a bunch of files freezes vscode

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#49623]
Not sure if that's the intended behavior or not.

1. Select 100-200 files 70Kb+ in file explorer
2. Delete them (Confirmation dialog disabled)
3. Interface is frozen for about 5s

Not a permanent deletion (recycle bin enabled).

---
OS version: Windows_NT x64 10.0.16299

**Comment by isidorn** [comment]
On my mac I have deleted 100 files of 100kb in size and it took less than a second
On my windows this took around 2 seconds using vscode. Doing the same operation from the windows explorer also takes 2 seconds and the explorer is blocked.

In a perfect scenario we would do this in the background and vscode would not freeze.
However not sure if we can do something about this since I call the `fileService` api asyncly from the explorer
fyi @bpasero

**Comment by bpasero** [comment]
Unfortunately if the trash is used, that operation blocks the UI thread and is not async. So VSCode will freeze as long as Windows is busy moving the files to the trash.

**Comment by usernamehw** [comment]
@bpasero Is this a duplicate of #43508 then?

**Comment by isidorn** [comment]
Yeah sounds like it, let's close as dup. Thanks!
