### ISSUE TITLE
Provide an option to that the Debug View is shown automatically when the debugger breaks

### ISSUE THREAD

**Issue by escamoteur** [Microsoft/vscode#49677]
Currently if I start my App with another View than Debug View open and the debugger breaks because of a break point or an exception I have to manually switch to the debug view.

It would be incredible if I could set an option to display the debug view in that cases automatically

Thanks for your great Work!

**Comment by isidorn** [comment]
This is a fair feature request. If we get more users asksing for this we would be willing to accept a PR that fixes this.
Thanks

**Comment by escamoteur** [comment]
@isidorn Why only as PR? I guess it will be only a very small change but I'm not a Typescript dev and have no idea about the internal structure of VS Code. For your team this should be a quick fix.

**Comment by isidorn** [comment]
Because we encourage people to be invovled in our open source project
https://github.com/Microsoft/vscode/wiki/How-to-Contribute

Code pointer https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/debugService.ts#L275

The following setting should be updated to also cover this case
[`debug.openDebug`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/common/debug.ts#L350) to also have the following option "openOnDebugBreak"

No typescript knowledge is needed for this PR

fyi @weinand
