### ISSUE TITLE
Two consecutive stackTrace requests when a breakpoint is hit.

### ISSUE THREAD

**Issue by andxu** [Microsoft/vscode#49670]
Version 1.23.1
Commit d0182c3417d225529c6d5ad24b7572815d0de9ac
Date 2018-05-10T17:11:17.614Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

Steps to Reproduce:

1. Install java debug extension published by Microsoft, add the following settings:
    "java.trace.server": "verbose",
    "java.debug.logLevel": "verbose"

2. Create a java file, set a breakpoint and F5, choose java.

```

/**
 * Hello world!
 *
 */
public class App 
{
    public static void main( String[] args )
    {
        System.out.println( "Hello World!" );
    }
}

```
3. Wait until breakpoint is hit
4. Open command panel by Ctrl+shift+p, input "Open Java language Server log file"

```
{"event":"breakpoint","body":{"reason":"new","breakpoint":{"id":1,"verified":true,"line":11,"message":""},"type":"breakpoint"},"seq":9,"type":"event"}

!ENTRY java-debug 1 0 2018-05-11 14:29:31.844
!MESSAGE 
JDI Event: BreakpointEvent: 7


!ENTRY java-debug 1 0 2018-05-11 14:29:31.849
!MESSAGE 
[[EVENT]]
Content-Length: 130

{"event":"stopped","body":{"threadId":1,"reason":"breakpoint","allThreadsStopped":false,"type":"stopped"},"seq":10,"type":"event"}

!ENTRY java-debug 1 0 2018-05-11 14:29:31.855
!MESSAGE 
[request]
{"command":"threads","type":"request","seq":7}

!ENTRY java-debug 1 0 2018-05-11 14:29:31.863
!MESSAGE 
[[RESPONSE]]
Content-Length: 302

{"success":true,"request_seq":7,"command":"threads","body":{"threads":[{"id":2,"name":"Thread [Attach Listener]"},{"id":3,"name":"Thread [Signal Dispatcher]"},{"id":4,"name":"Thread [Finalizer]"},{"id":5,"name":"Thread [Reference Handler]"},{"id":1,"name":"Thread [main]"}]},"seq":11,"type":"response"}

!ENTRY java-debug 1 0 2018-05-11 14:29:31.869
!MESSAGE 
[request]
{"command":"stackTrace","arguments":{"threadId":1,"startFrame":0,"levels":20},"type":"request","seq":8}

!ENTRY java-debug 1 0 2018-05-11 14:29:31.916
!MESSAGE 
[request]
{"command":"threads","type":"request","seq":9}

!ENTRY java-debug 1 0 2018-05-11 14:29:31.926
!MESSAGE 
[request]
{"command":"stackTrace","arguments":{"threadId":1,"startFrame":0,"levels":20},"type":"request","seq":10}

!ENTRY java-debug 1 0 2018-05-11 14:29:32.117
!MESSAGE 
[[RESPONSE]]
Content-Length: 311

```

The log shows vscode has sent two same stackTrace requests, while in previous versions, sometimes only one stackTrace is sent and sometimes two stackTrace events are sent, this bug also occurs on latest insider version.

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
@andxu thanks for the details.
And the expected behavior is that only one `stackTrace` request is sent?
Your debug adapter does not `supportsDelayedStackTraceLoading` correct?

If you F1 > developer tools > put a breakpoint [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/rawDebugSession.ts#L380)
Who are the two callers of the `stackTrace` request?

**Comment by andxu** [comment]
![image](https://user-images.githubusercontent.com/17075863/39975443-193db4fc-5761-11e8-9df0-6cd629e54a24.png)

**Comment by isidorn** [comment]
@andxu thanks for providing more details. I believe the second call is fine, since that is being called because of a stop event.
Let's investigate the first one a bit more, what caused that. 
It seems like the `callStackChangeScheduler` got scheduled, we need to find a reason why. Can you put a breakpoint [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/callStackView.ts#L153) and figure out the reason for this.

My assumption is that this might be by design, more preciesly when a new debug session starts vscode sends out a `threads` request to get all the inital threads, when that is done vscode will ask for the children of a thread if you report that some of those threads are stopped - which I believe your adapter does - and that might be the issue.
Independent of that a `stop` event comes and vscode sends a `stackTrace` request which you see as the second request.
