### ISSUE TITLE
Use wsl.exe instead of bash.exe on newer versions of Windows

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#49713]
I think from 1709 we should be using wsl.exe instead of bash.exe?

https://github.com/Microsoft/vscode/blob/b220a05fc30a99e057b70e2977e40e8a9ecaeb9f/src/vs/workbench/parts/terminal/electron-browser/terminalService.ts#L219

Could be related to issues like this? https://github.com/Microsoft/vscode/issues/48331

**Comment by Tyriar** [comment]
@bitcrazed from what version of Windows should we start recommending wsl.exe instead of bash.exe?

**Comment by DarthSpock** [comment]
I believe the first stable build it was available in is build 16299. Oh and I noticed your commit says wsl.exe and ubuntu.exe. You better add Debian, OpenSuse, and Kali to the list (yes Kali might be a bit more questionable but let's just roll with it as it's an available _rolling_ distro for WSL). 

You should also probably put a checker out there for other .exe distros since we can now build our own distro apps but that can be a separate issue/commit.

**Comment by Tyriar** [comment]
@DarthSpock so it's not super important if these are missing from the list in https://github.com/Microsoft/vscode/commit/e1a2ea39c9fbc434f57b4909efd4320364db7624, I don't think it's worth adding a setting or anything for extra distros (yet?).

We can add the other standard distros now though, do you know the exact case-sensitive exe names for them?

**Comment by alexr00** [comment]
Looks like this is fixed:
`			'WSL Bash': [`${system32Path}\\${useWSLexe ? 'wsl.exe' : 'bash.exe'}`],`
`useWSLexe` checks the windows version.

**Comment by Tyriar** [comment]
@alexr00 thanks for checking!

**Comment by bitcrazed** [comment]
We'd recommend wsl.exe instead of bash.exe for Spring 2018 Update or later.


Rich Turner | Sr. Program Manager | Windows Console & Command-Line | Microsoft

e: richturn@microsoft.com<mailto:richturn@microsoft.com> | t: @richturn_ms<https://twitter.com/richturn_ms> | c: +1 (425) 445-5755

________________________________
