### ISSUE TITLE
 If you accidentally write characters in the VSC terminal, it hangs(Python)

### ISSUE THREAD

**Issue by DrElvis** [Microsoft/vscode#49812]
- VSCode Version 1.23.0:
- OS Version Windows 10:

Steps to Reproduce:

1. Open simple Python script in VCS
2. Run debug(its OK)
![image](https://user-images.githubusercontent.com/18135018/39985380-26b71ef6-5767-11e8-96db-0db690f09111.png)

3. Write "123" or other symbols in the terminal
![image](https://user-images.githubusercontent.com/18135018/39985423-47b3c366-5767-11e8-8803-3ec2f3f3b9ea.png)

4. Run debug. And gebug is hangs. Helps only restart VCS
![image](https://user-images.githubusercontent.com/18135018/39985509-8664522e-5767-11e8-80d6-553761396cd8.png)

**Comment by weinand** [comment]
Python team thinks this is an VS Code issue. See Microsoft/vscode-python#1677

**Comment by weinand** [comment]
This works fine for me in 1.27.1:

![2018-09-13_15-35-02](https://user-images.githubusercontent.com/1898161/45491803-e61ee180-b76a-11e8-9b22-8981524ab2a3.gif)

The broken command "123cd" results in an error and the terminal is not blocked. However, since the debugger doesn't know of the problem it tries to attach until it times out after 10 seconds.
That's the expected behaviour.
