### ISSUE TITLE
support easy re-arranging of folded blocks

### ISSUE THREAD

**Issue by mhchem** [microsoft/vscode#49886]
I want to be able to easily reorder the definitions in a file.
I get the best overview about the structure of my file when everything is folded.
So, I want to be able to reorder the definitions (of functions, classes, etc.) in a file when it is folded.

Example:
- Open https://raw.githubusercontent.com/Microsoft/vscode/master/src/bootstrap.js in editor
- Fold All

One can easily see the classes, interface, functions.

Now I want to rearrange them. This doesn't work.

If I select a folded function (2 lines) and want to move it with the keyboard, I can use 'Move Line Down' (Alt+ArrowDown), but that will not skip over folded blocks, but run into them.

If I try to move the selected block by mouse (drag&drop), the folding gets lost.

Same for the clipboard (cut&paste).

I don't see a single way to do what I want.

**Comment by HerbCaudill** [comment]
+1 to this request. 

In general, there are a number of user gestures that apply to a single line. When the line in question is the head of a folded area, these apply to the first line of the folded area, which I'm pretty sure is *never* what anyone wants. 

![rearrange-folded-vscode](https://user-images.githubusercontent.com/2136620/97444073-08b0ec00-192c-11eb-85b9-5a7001f686f3.gif)

It would be great if all of these applied to the entire folded area, instead of just to the first line:
- Triple-click to select an entire line
- <kbd>Ctrl-X</kbd>, <kbd>Ctrl-C</kbd>, or <kbd>Ctrl-L</kbd> to cut, copy, or clear the line the cursor is in (with nothing selected)
- <kbd>Alt-Up</kbd> and <kbd>Alt-Down</kbd> to move the current line up or down (with nothing selected)
