### ISSUE TITLE
Show debug sessions under a new split view section

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#49881]
Similar to how git shows mulitple git repositories, debug could show multiple debug sessions in a new split view section which we would be first in the debug viewlet.
In case we choose to do this we would no longer show multiple sessions in the callstack view but only the focused one.
This new section would only show up if a user has multiple sessions running.

Pros: easy and clear to change active session (also if your debug toolbar is docked), consistent with git
Cons: eats up vertical space

This idea was proposed by @bpasero 
fyi @roblourens @weinand @auchenberg

**Comment by weinand** [comment]
Does not scale well.
Example: cluster debugging.
Number of sessions is inherently dynamic as opposed to a static number of git repositories.

**Comment by auchenberg** [comment]
I'm having a hard time visualizing this. In an ideal world we would be able to "mix" stack frames come multiple debugging targets into a unified view. Imagine debugging a front-end + back-end and being able to see the flow across the stacks in the right order.

**Comment by bpasero** [comment]
Git repositories can come and go as well depending on external (out of workspace) files opened. I suggest to mock this up an run through it to see if it would work with the other views.

**Comment by roblourens** [comment]
I like being able to see multiple callstacks at once. At least, I should be able to see the state of the other sessions (at breakpoint or not). If there was some indicator of that state, I might be ok with it.

But I also agree with @weinand that debug sessions are much more dynamic and I might expect to use more simultaneously.

**Comment by weinand** [comment]
There is no value in mocking this if we cannot see multiple callstacks at once.

**Comment by bpasero** [comment]
@roblourens @weinand see, I was not suggesting to filter the call stack like that. For that reason let's do a mockup so that you understand our idea. I think a textual description of the UX flow will only confuse you.

**Comment by isidorn** [comment]
@misolori what tool are you using for mockups? Would you have cycles to mock this up - I can also look into mocking it up if the tool is user friendly :)

**Comment by misolori** [comment]
@isidorn I'm using Figma (I can add you to our account). I've got a few things pre-built for the debugger that can help jump start this. If you can provide a quick sketch/whiteboard that'll help clarify the layout.

**Comment by misolori** [comment]
@isidorn I did a quick attempt at this (based off what I could understand). Is this what you're looking for?

![frame](https://user-images.githubusercontent.com/35271042/40155586-63c05aa4-5949-11e8-917d-19b5d5f14976.png)

**Comment by isidorn** [comment]
@misolori thanks a lot, how I understood @bpasero is something like that, but he can comment more.
The only difference that I know is that the Threads (in your example Node 49283) should still be displayed in the call stack view, and the session would be a flat list of sessions (not a tree). With some session specific actions on top.

Also thanks for adding me to Figma, I'll check it out

**Comment by misolori** [comment]
@isidorn that was what I originally had but wasn't how deep you wanted the "sessions" section. Here's that:
![debugger - multiple sessions](https://user-images.githubusercontent.com/35271042/40182847-3145fe0a-59a1-11e8-916f-e2c32d423b47.png)

**Comment by bpasero** [comment]
@misolori thanks for doing this mockup, can I try to explain what I would change (for my idea) and you add it to the mockup? Otherwise I can also start a mockup but maybe we get there:
* I would put all the debug toolbar actions right next to the sessions, in the same way how the Git view shows all the relevant controls (in this case the sync action) right next to each repository:
![image](https://user-images.githubusercontent.com/900690/40191081-b8144e3c-5a00-11e8-8e72-72ef6f20be70.png)
* the "Call Stack" view is always showing ever session that is running independent from what session is selected to the top
* when you click on a session, we restore automatically the last selected element that I had selected from that session in the callstack view

Given that, jumping between multiple sessions would update the call stack view and as such the variables view as well. We no longer need the debug toolbar in this model either unless the user explicitly has opted in to show it floating above the editor maybe.

**Comment by misolori** [comment]
@bpasero here's what that would look like. For now I place the debugger toolbar below the selected item since the space is so small. I can imagine we could reduce the spacing and place secondary actions in an overflow menu to help with the spacing issue? Is it important in the sessions group to indicate which ones are paused/running if they're also shown in the call stack group?

![debugger - multiple sessions](https://user-images.githubusercontent.com/35271042/40205608-83c714f8-59e1-11e8-83c8-8c59f16407e6.png)

**Comment by bpasero** [comment]
@misolori that is an interesting solution to not using too much space, I kind of like it. I think it is important to show running vs. stopped also in that list.

**Comment by weinand** [comment]
When debugging a client server scenario I can just keep pressing the single "continue" button in the button bar to transition between client and server breakpoints.

With the "Sessions" section I have to choose the correct session before pressing the "continue". This doesn't make multi-session interactions easier.

**Comment by roblourens** [comment]
Yeah I would rather see a single set of debug actions, at a consistent spot on the screen, that applies to whatever process is selected.

**Comment by weinand** [comment]
Another drawback of a "session" section: it is only available in the debug viewlet but not in any other viewlet, whereas the debug bar is available everywhere.

**Comment by isidorn** [comment]
I do not feel like anybody got really convinced -> out of scope
Passionate people please reopen
