### ISSUE TITLE
Fuzzy matching of snippets stopped working with inline snippet suggestions

### ISSUE THREAD

**Issue by sassjajc** [Microsoft/vscode#49895]
During the last couple of updates of VSCode Insiders, fuzzy matching for snippets when using "snippetSuggestions: inline" has stopped working.

This is what I get:
![2018-05-15_04-15-55](https://user-images.githubusercontent.com/20391356/40053811-8b15560c-57f7-11e8-8613-ddf1935fe763.gif)
Version 1.24.0-insider
Commit 5d12f53178b72e88431347f8e248c49335a7fefc
Date 2018-05-14T05:16:26.538Z

This is what I expect:
![2018-05-15_04-19-55](https://user-images.githubusercontent.com/20391356/40053812-8b2c1b30-57f7-11e8-9ba6-9028470c03a6.gif)
Version 1.23.1
Commit d0182c3417d225529c6d5ad24b7572815d0de9ac
Date 2018-05-10T17:11:17.614Z

"snippetSuggestions: top" still performs fuzzy matching for snippets just fine.
Fuzzy matching for everything else also appears to be fine.

- Does this issue occur when all extensions are disabled?: Yes
  I tested this with default snippets only (no extensions) and with snippet extensions enabled.
- OS Version: Windows 10

**Comment by sassjajc** [comment]
Upon further examination I've located the setting that causes this issue to occur.
```
  "emmet.includeLanguages": {
    "javascript": "javascriptreact",
  },
```
This setting has worked normally for at least the past 10 months, and still works fine in v1.23.1.

I also tested some JSX files. Javascript React code is showing the same symptoms both with and without that setting enabled (which shouldn't have any effect anyway).
This leads me to believe that the issue is with javascriptreact.

**Comment by ramya-rao-a** [comment]
@jrieken In the below `adopt` function, the items from the end of the array keep getting deleted which is causing this issue. This actually ends up deleting almost of half the items in the array.

https://github.com/Microsoft/vscode/blob/ab78dc7eba36a6079d7123cd891b9a92f56323c9/src/vs/editor/contrib/suggest/completionModel.ts#L107-L121


When `editor.snippetSuggestions` is set to `top`, the snippets are in the front of the array and so are saved from the deletes above.

The above code is only reached when completion results of `incomplete` type are called when subsequent letters of the word are typed. Since emmet contributes such results, this issue is only seen in js files when emmet is enabled
