### ISSUE TITLE
Better syntax highlighting for Rust

### ISSUE THREAD

**Issue by eedahl** [Microsoft/vscode#49932]
Not sure if I'm in the right place, but the syntax highlighting for VS Code seems very limited and unconfigurable. Apparently, VS Code uses the syntax highlighting from Atom, yet Atom users tell me it is better for Atom. As I've witnessed with others it makes transitioning from Atom rough, and coming from VS Code, it makes transitioning to Atom kind of tempting. Any improvements in this regard would be very nice.

**Comment by eedahl** [comment]
Yes, I wrote there before opening an issue here, they said it was bundled with VS Code and based on the atom library. Yet the Atom functionality is by all accounts better, providing subtler information, etc.

**Comment by mjbvz** [comment]
Can you please provide some examples

**Comment by eedahl** [comment]
In Atom, #[attr] annotations are clearly distinguished from variables, Option type is clearly distinguished from what it contains,
Atom: https://gyazo.com/c3df356cdedf1cca98459a5ccc7c2029
VS Code: https://gyazo.com/a877f4e271155deadfe7ed6572a6a5f7

Some matching stands out clearly, with consistent colouring across it, Ok and Err, smaller symbols like the literal integer 0, hard to spot but important program flow, stands out,
https://gyazo.com/fc7923ff10cc48c47460fd1ebc9410b7
https://gyazo.com/881b46cdebe085d3551d91c30798f872

Macro calls are clearly distinguished from function calls,
https://gyazo.com/36a83ddd140879d52ab9819147f16e86
https://gyazo.com/1ab1ff2b8aa61c61d2bc08940ff73ec8

Somewhere VS Code is arguably better, highlighting the enum type,
https://gyazo.com/8286072d946ece40bd36fba3288c109f
https://gyazo.com/57981ffd2189a2c6d54e92bdaa9191ef

In general the colour scheme (to my taste at least) leaves something to be desired and being able to customise it would make a lot of sense, like you can in Atom, see Features -> Custom Syntax Highlighting,
https://atom.io/packages/atom-language-rust

**Comment by mjbvz** [comment]
Since we use the same grammar, I believe  this is just a matter of theming. As far as I can tell, the atom rust extension injects it's [own themeing rules](https://github.com/miqid/atom-language-rust/blob/master/styles/rust.less) to provide better colors. 

Any [theme](https://code.visualstudio.com/docs/getstarted/themes) for VS Code could do the same, targeting the special rust specific scopes that the grammar creates. Here's info about writing your own color theme: https://code.visualstudio.com/docs/extensions/themes-snippets-colorizers#_adding-a-new-theme

Closing as extension candidate

**Comment by eedahl** [comment]
I don't see why this should be closed if Rust is considered an integrated part of VS Code, which given that it ships with atom rust components and (albeit underdeveloped) syntax highlighting it seems like it is.
