### ISSUE TITLE
Remove all blank lines regex not working

### ISSUE THREAD

**Issue by jozsefk9** [Microsoft/vscode#4995]
- VSCode Version: 0.10.11
- OS Version: Windows 10 64bit

Steps to Reproduce:
1. Search and replace with regex turned on: ^$ 
2. Search and replace with regex turned on: ^\s+$

VSC replaces the blank lines with blank lines :)

See more details here:
https://stackoverflow.com/questions/36350324/visual-studio-code-delete-all-blank-lines-regex

**Comment by ZombieProtectionAgency** [comment]
`^$` and `^\s+$` will only match the contents of a line, not the new line character. More specifically they are zero width tokens. `$` will match just before the end of a line which is usually defined as a `\n`. You could normally use `\n` to match a new line but VS Code doesn't actually support matching across lines yet (https://github.com/Microsoft/vscode/issues/313) so that wouldn't work either

**Comment by jozsefk9** [comment]
Thank you Zombie. It seems we still have to wait for a while. I did try \n and as you've said it's not working either. At least not at the moment.

**Comment by jgainfort** [comment]
Not sure if this was fixed or not, but I solved this using the following regex

^$\n

**Comment by alexandrudima** [comment]
Yes, in the meantime we have shipped multiline support in the find widget, and one can use `\r\n` or `\n`, etc. in the regex to target eol chars.
