### ISSUE TITLE
Feature request: Simplify custom view container titles

### ISSUE THREAD

**Issue by Gruntfuggly** [Microsoft/vscode#50044]
I have a customer view container which contains a single view. At the moment the title bar ends up with `<container-name>: <view-name>`
It doesn't make sense to have the same thing in both, but if I make the container name blank, it shows:
`: <view-name>`
and the activity bar context menu contains a blank entry.
If I make the view name blank, but leave the container name, is shows:
`<view-name>`
which looks better, but the side bar context menu contains a blank entry.

If the container name and the view name are the same, could it coallesce the names into one?

**Comment by sandy081** [comment]
@Gruntfuggly View title is shown next to view container title because the view container has only single view. If there are more views added to the view container then, view title will be shown as a separate section as follows:

![image](https://user-images.githubusercontent.com/10746682/40221129-d27bfd1c-5a7b-11e8-845c-ef1601b90965.png)

So, I would suggest not to have empty names for views or view containers. I recommend to name container and views with proper logical names like above.
