### ISSUE TITLE
Output: do not open link in new group if a file is already open

### ISSUE THREAD

**Issue by 0ge** [Microsoft/vscode#50106]
Consider the following scenario.

- Two open split windows - `A` and `B`.
- `A` shows a source file
- `B` shows the test file for the source
- I run the tests while having the test file in focus (e.g. I write test and invoke the Run Test task)
- The test task output reports an error with a link to a line in the source

When I Cmd+Click the link I want the editor to open/jump to the linked line the already open source in window `A` instead of adding an additional tab in the `B` window.

**Comment by 0ge** [comment]
Should perhaps clarify that this is not the only situation where I would want this behaviour, it was just an example.

**Comment by jrieken** [comment]
I believe that's an issue with the output view

**Comment by isidorn** [comment]
@0ge are you clicking in the output or in the editor? If you are not sure which is which just post a short video showing this issue please?
So you are arguing if an editor is already open in the left pane, it should just show that one instead of a new one in the right pane?

**Comment by 0ge** [comment]
Thanks for taking the time to follow up.

I apologise that I was unclear; I click in the output view.
And you got the wanted behaviour correct, @isidorn.

**Comment by isidorn** [comment]
The issue here is that this is just our general workbench editor opening approach.
We always open in the active group.
So if the group 2 is active whenever you click anywhere in the workbench (example: explorer) we will open a file in group 2.
In your example: you are clicking in the output and you have group 2 active and that is why it is opened there, even though you would expect the file in group 1 to be revealed and that group to be activated.

I argue the same could be said for the explorer and you have the exact same behavior there.

I believe this is as designed, but forwarding to @bpasero to decide

**Comment by bpasero** [comment]
@0ge you can configure this by setting `"workbench.editor.revealIfOpen": true`

**Comment by isidorn** [comment]
@bpasero oh there is a setting I did not know 😱

**Comment by 0ge** [comment]
Ah, I looked through the settings but didn't find anything. (UI is not a bad idea...) Thanks!
If I were to choose, the default value would be true. I never got the reason why you would want it any different. 😄
