### ISSUE TITLE
Extension contributing task

### ISSUE THREAD

**Issue by fcurts** [Microsoft/vscode#50137]
Reopening #27425. From what I can tell, the API still hasn't been promoted and there are no docs for it. An example that shows how to do the equivalent of `tasks.json` (say running an external command) would be very helpful. Even better if there was an option to register a `tasks.json` (even if the registration requires code). Thanks!

**Comment by dbaeumer** [comment]
The API is official available since a while and an example is available here: https://github.com/Microsoft/vscode-extension-samples/tree/master/task-provider-sample. I agree that separate documentation would be helpful. Created https://github.com/Microsoft/vscode-docs/issues/1624

I will close the issue. Please ping if you disagree with this action.

**Comment by fcurts** [comment]
Does this mean that all or parts of the task API in [vscode.proposed.ts](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.proposed.d.ts#L335-L526) is obsolete?

**Comment by dbaeumer** [comment]
No, this is new task API to be able to query and execute tasks. The API to provide tasks is in `vscode.d.ts`.
