### ISSUE TITLE
Task with escaped double quote now fails due to improper evaluation

### ISSUE THREAD

**Issue by kevinbeaudoin** [Microsoft/vscode#50131]
We are using custom task in vscode to compile some C# solutions using msbuild.  The tasks used to run just fine but with latest upgrade our task now fails because double quote escaping isn't performed correctly (see example below)

- VSCode Version: 1.23.1 (used to work in 1.22)
- OS Version: Windows 8.1

Steps to Reproduce:

1. Create a task similar to this one (Notice the quote escape for the Any CPU param):
{
        "label": "Build MySolutionName.sln",
        "type": "shell",
        "command": "msbuild",
        "isBackground": false,
        "options": {
          "cwd": "C:\\Program Files (x86)\\MSBuild\\14.0\\Bin"
        },
        "args": [
          "${workspaceRoot}\\..\\..\\MySolutionName.sln",
          "/property:Configuration=Debug",
          "/property:platform=\"Any CPU\"", 
          "/v:m",
          "/p:WarningLevel=0"
        ],
        "group": "build",
        "problemMatcher": []
},

2. Here is the task that vscode tries to run (Notice the issue with the part where we specify the Any CPU :
Executing task: msbuild MySolutionName.sln /property:Configuration=Debug "/property:platform="Any CPU"" /v:m /p:WarningLevel=0

3. Before the upgrade the task was run like below:
Executing task: msbuild MySolutionName.sln /property:Configuration=Debug /property:platform="Any CPU" /v:m /p:WarningLevel=0

Does this issue occur when all extensions are disabled?: Yes

**Comment by dbaeumer** [comment]
@kevinbeaudoin actually shell tasks with args quoting and spaces were poorly supported and there should have been an warning / error in the task output informing that if a shell task specifies args with spaces they should be folded into the command. I apologies if this didn't happen in your case (but I am confident it did looking at your example). (side note: the reason for this is that shell take a command line as arguments and not a command and args and VS Code always tried to create a command line from the command and the args but did a poor job on doing this correctly in the past)

To make the story better we improved the quoting/escaping behavior in `1.22` in the following way:

- args with spaces are now allowed and we quote such args strongly.
- users can control how args are quoted by providing a literal and not a single string.

For complex command lines where only parts inside the command line should be quoted the recommendation is to write one single command line. In our example something like:

"command": "msbuild ${workspaceRoot}\..\..\MySolutionName.sln /property:Configuration=Debug /property:platform=\"Any CPU\" /v:m /p:WarningLevel=0"

since this gives you the biggest control over the command. Since users uses args to split the long command line into lines I added support to provide a string[] for a command for the next release: So with `1.24` you will be able to write:

"command": [
   "msbuild",
   "${workspaceRoot}\..\..\MySolutionName.sln",
   "/property:Configuration=Debug",
   "/property:platform=\"Any CPU\",
   "/v:m"
   "/p:WarningLevel=0"
]

Noticed that there are no args. You construct a command line.

On think I take away from this is that for args we should off a "leave as is" quoting rule which leaves the args untouched even if it has spaces. I will add that.

**Comment by dbaeumer** [comment]
My last sentence is not correct. The fix here is to detect that "Any CPU" is quoted and leave it untouched.

**Comment by dbaeumer** [comment]
I added a fix to detect that `Any CPU` was correctly quoted.

**Comment by dbaeumer** [comment]
To verify write a simple task that has a space in one of the args which is correctly quoted. Something like

```
		{
			"type": "shell",
			"label": "echo",
			"command": "echo",
			"args": [
				"dirk\" \"baeumer"
			],
			"problemMatcher": []
		}

```

The executed command should be `echo dirk" "baeumer` and not `echo "dirk" "baeumer"`
