### ISSUE TITLE
 spawn osascript ENOENT

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#5019]
Issue Id: <b>def759c3-62fe-b6f1-ff32-27679721a3ff</b><br /><br />*Versions* <br />- 0.10.8<br />-  f291f4ad600767626b24a4b15816b04bee9a3049<br />-  43ff6af3d4564f59196caa9be4897fc33c15f24c<br />-  5b5f4db87c10345b9d5c8d0bed745bcad4533135<br />-  17fa1cbb49e3c5edd5868f304a64115fcc7c9c2c<br />*Stack* <br />Error: spawn osascript ENOENT<br />    at exports._errnoException (util.js:837:11)<br />    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32) <no sourcemaps><br />    at onErrorNT (internal/child_process.js:344:16) <no sourcemaps><br />    at doNTCallback2 (node.js:442:9)<br />    at process._tickCallback (node.js:356:17)<br />

**Comment by aeschli** [comment]
over 3000000 hits, on 32 machines, 100% on windows

**Comment by joaomoreno** [comment]
I suspect that uncaught errors from extensions show up in our telemetry... not very happy.

**Comment by weinand** [comment]
There are two different types of 'osascript' usages in VS Code:
- using an absolute path '/usr/bin/osascript'
- just 'osascript' and relying on the search PATH 

For the first type I've verified on Windows 10 that the error message shows the full absolute path which looks different from the telemetry error entry from above:

```
Error: spawn /usr/bin/osascript ENOENT
    at exports._errnoException (util.js:870:11)
    at Process.__dirname._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:441:9)
    at process._tickCallback (node.js:355:17)
    at Module.runMain [as _onTimeout] (module.js:444:11)
    at Timer.listOnTimeout (timers.js:92:15)
```
The second usage type is in `cli.contribution.ts:131`. Since this action is only installed on OS X and must be triggered manually, it cannot explain the high number of occurrences on Windows.

From this I conclude that this is an uncaught error from some extension.
