### ISSUE TITLE
[html] disable angular tags by default

### ISSUE THREAD

**Issue by mikemaccana** [Microsoft/vscode#50206]
Issue Type: <b>Bug</b>

When typing HTML (auto selected as being HTML), autocomplete suggests non-HTML5 tag attributes when I type 'class'. These looks like angular.js, which was a thing in 2010, and is now only used by three people. 

![image](https://user-images.githubusercontent.com/172594/40302061-d6ae41da-5ce5-11e8-8100-93923a16e4c7.png)

VS Code version: Code - Insiders 1.24.0-insider (a521c01d56ec7f07bea2471880f28a77f37983af, 2018-05-21T05:18:01.058Z)
OS version: Windows_NT x64 10.0.17672

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: unavailable_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>vpx_decode: unavailable_software<br>webgl: unavailable_off<br>webgl2: unavailable_off|
|Memory (System)|7.93GB (3.36GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe --disable-gpu -g .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
Handlebars|and|0.4.1
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.4.9
beautify|Hoo|1.3.0
PowerShell|ms-|1.7.0

</details>

**Comment by mikemaccana** [comment]
@vscodebot Wrong again. Nothing to do with integrated terminal.

**Comment by octref** [comment]
You can turn it off by `"html.suggest.angular1": false`.

**Comment by mikemaccana** [comment]
@octref Is there a reason to close this bug? Are most people editing HTML using angular.js, making `"html.suggest.angular1": true` this a sensible default? Or is it worth changing the defaults?

**Comment by octref** [comment]
I didn't do the original angular support, but I think discoverability would be a problem if this is turned off by default.
I do agree Angular support should be moved into a plugin. However our HTML completions aren't extensible by extensions yet. @aeschli what do you think?

**Comment by mikemaccana** [comment]
For discoverability, maybe have 'HTML (angular)' in the same way we have
'JavaScript (React)'?

**Comment by aeschli** [comment]
The request to extend the HTML server with custom tag providers is https://github.com/Microsoft/vscode/issues/2784

I'm happy to set the default to `"html.suggest.angular1": false` if more users want.

**Comment by mikemaccana** [comment]
Thanks @aeschli . This comment from that thread sums up my feelings here: https://github.com/Microsoft/vscode/issues/2784#issuecomment-191151611

> To add to this: it would be a great addition to move the existing Angular Tag provider into a custom extension. Using this approach, Angular tag hints would only appear if a user needs them. At the moment tag hints are displayed even if we do not use Angular.

**Comment by slimlime** [comment]
Thanks for opening this issue, there was very little accessible information to search and I was only able to find this bug by chance after hours of troubleshooting.


Indirectly related with the html built-ins for Ionic as well.
`"html.suggest.ionic": true,`
I just had a merry old time wondering why my ionic snippets were being overwritten and finally found the root cause that VS Code remarkably ships with ionic html element suggestions built-in! (For some reason this bug never showed itself until recently in my new install) 

It seems strange that a general programming IDE specifically has angular and ionic suggestions forcibly enabled for html (would think this is a space for community extensions). Especially bothersome when some of the suggestions provided are _deprecated_ and somehow were overriding the ionic extensions I installed.

Hope things like these can gain more exposure and the knowledge base improves to avoid issues like this for other users 👍

**Comment by aeschli** [comment]
Angular tags are since July turned off by default:

https://github.com/Microsoft/vscode/commit/4fa62b246c4305b4ca00507551f77c58135ce928
