### ISSUE TITLE
Disappearing unused var error highlighting with custom `tsc-watch` task

### ISSUE THREAD

**Issue by realyze** [Microsoft/vscode#50226]
VSCode version: 1.23.1

This is my `tasks.json`:

```json
{
  // See https://go.microsoft.com/fwlink/?LinkId=733558
  // for the documentation about the tasks.json format
  "version": "2.0.0",
  "tasks": [
    {
      "type": "typescript",
      "tsconfig": "web/tsconfig.tscheck.json",
      "problemMatcher": [
        "$tsc-watch"
      ],
      "option": "watch",
      "group": {
        "kind": "build",
        "isDefault": true
      }
    }
  ]
}
```

The ts config at `web/tsconfig.tscheck.json` has `noUnusedLocals` flag set to true, my main config at `web/tsconfig.json` does not (mostly for local dev purposes where I don't want my code to throw compile errors when I comment out things).

I can see the unused var errors in both the `Terminal` tab and the `Problems` tab. However, when I click on any item in the `Problems` tab (to open the file it in editor), the red squiggle shows for a second and then disappears and the unused var problem disappears from the `Problems` tab.

![pr_video](https://user-images.githubusercontent.com/596749/40323489-ce31a3c6-5d35-11e8-8c2b-e88596008d29.gif)

**Comment by dbaeumer** [comment]
The reason for this is that the Typescript extension produces errors for open files (they are computed on the editor buffer in contrast to the errors computed on the disk state by the task). Since for the editor buffer you configured the tsconfig to not show unused locals no errors are computed hence none are shown. You could give the errors from the task a different owner however then real errors are reported twice which isn't nice either.

```ts
{
	// See https://go.microsoft.com/fwlink/?LinkId=733558
	// for the documentation about the tasks.json format
	"version": "2.0.0",
	"tasks": [
		{
			"type": "typescript",
			"tsconfig": "tsconfig.json",
			"option": "watch",
			"problemMatcher": [
				"$tsc-watch"
			]
		},
		{
			"type": "typescript",
			"tsconfig": "tsconfig.json",
			"problemMatcher": [
				{
					"base": "$tsc",
					"owner": "myTypescriptErrors"
				}
			]
		}
	]
}```

Actually I tend to close the issue since there in no way (even if we try) to decide which errors to keep. Anything I am missing?

**Comment by realyze** [comment]
@dbaeumer Thanks for the reply! So I take it there is no way to configure the task that compiles the open file (i.e., the one that uses the editor buffer)?

When I add give the task problem matcher a different owner, it seems to work OK for unopened files, i.e., the unused var problems are shown correctly for tabs that are not open when compilation runs. But they're not shown for files in open tabs. So kinda halfway there. :)

**Comment by dbaeumer** [comment]
For a given file there is only on set of Typescript problem. These either come from the compiler (tsc -w) for closed files or from the language server for open files. Since you configured the server for open files to not report unused they are not shown. 

You can have to sets of problems (compile the open file) all the time but then for open files you will see double errors.
