### ISSUE TITLE
[feature] git extension - add branch name validation

### ISSUE THREAD

**Issue by raix** [Microsoft/vscode#50241]
Description:
* Add validation to the git create branch, ensuring that project branch conventions are kept.
* Make the `whitespace` char `-` configurable *(we default space etc. to underscore - meaning we cannot just past in issue title and be done)*

Example implementation:
![vscode-create_branch_validation](https://user-images.githubusercontent.com/1136718/40329313-69d7b640-5d49-11e8-9af6-0eb4e8b3b8fa.gif)

I can create an initial pr. with the implementation for further discussion, if this is something the vscode team would consider.

eg. if the change should enable extensions to lint/validate the branch name or be a configuration etc.

Kind regards Morten

**Comment by joaomoreno** [comment]
Sure, submit ahead.

**Comment by TomasHubelbauer** [comment]
Is this really something that should be in VS Code? And not say a Git server hook?

**Comment by TomasHubelbauer** [comment]
Hmm having an API for this would be actually quite interesting, because it would enable your scenario so that VS Code could work the best for you but also allow teams to publish extensions of their own which would check the branch name policies or perhaps even do clever things like suggest prepending current ticket code to the branch name automatically if forgotten etc.

**Comment by raix** [comment]
@TomasHubelbauer yes would be interesting - I'm currently digging into the vs code source. For now I've attached a gif on the pull request for both solutions.
