### ISSUE TITLE
Git extension activation should return a promise

### ISSUE THREAD

**Issue by svipben** [Microsoft/vscode#50292]
- VSCode Version: 1.23
- OS Version: macOS

Steps to Reproduce:

1. Open new VS Code window (CMD + SHIFT + N)
2. Open Command Palette and write Git: Clone

![image](https://user-images.githubusercontent.com/10441177/40378353-f66581c0-5dfb-11e8-8d7e-63587ee10dae.png)

**This problem occurs only if you do it immediately after opening new VS Code window.**

My suggestion is to first load Git: Clone command or make it gray/disabled in Command Palette till it's loading.

**Comment by alexandrudima** [comment]
@joaomoreno This appears to be a programming mistake in the git extension. The git extension returns execution from `activate` or resolves the `activate` return promise before registering its commands.

#### diff1. `extHostExtensionService.ts`:
![image](https://user-images.githubusercontent.com/5047891/40619336-fff4a46c-6294-11e8-887a-251c9ec56457.png)


#### diff2. `extHostCommands.ts`:
![image](https://user-images.githubusercontent.com/5047891/40619360-1013c7ba-6295-11e8-91d8-0d2762c3217d.png)


---

Observe the output, the commands are registered after the extension indicates that it has finished activating:
![image](https://user-images.githubusercontent.com/5047891/40619381-23ace194-6295-11e8-890a-9ec8ddfe8001.png)

**Comment by joaomoreno** [comment]
@alexandrudima I know remember why. The Git extension has some async context to resolve before it can set up everything (eg. git.exe location). There seems to be no way to have an async extension activation, since the return value of `activate` should be the extension's API.

The only alternative I seem to have is to optimistically register all my commands on activate and pass them a promise of the unresolved context. Each command should then call `then` on it in order to get the correct context, upon execution.

Did I get this correctly? Or would an async activation be something we can consider thinking about?

**Comment by alexandrudima** [comment]
@joaomoreno The `activate` function get return a promise, and the result of the promise is the exported API.

**Comment by joaomoreno** [comment]
@alexandrudima Did not know that! Thanks man.
