### ISSUE TITLE
"update image size" not working on root relative path

### ISSUE THREAD

**Issue by MrNakka** [Microsoft/vscode#50325]
- VSCode Version: 1.23.1
- OS Version: Windows 10 Enterprise Ver.1703 build 15063.877

Im trying `editor.emmet.action.updateImageSize` action.
but, this action **working only absolute path**.

is **working** code (absolute path)

ex: `<img src="./cmn/img/test.png" alt="">` - Emmet: Update Image size -> `<im g src="./cmn/img/test.png" alt="" width="xxx" height="xxx">`

**not working** code (root relative path)
ex: `<im g src="/cmn/img/test.png" alt="">` - Emmet: Update Image size -> its not working...

Does this issue occur when all extensions are disabled?: No

**Comment by ramya-rao-a** [comment]
Thanks for reporting @MrNakka 

PRs are welcome to fix this issue.
The code behind this feature is at https://github.com/Microsoft/vscode/blob/release/1.23/extensions/emmet/src/updateImageSize.ts

**Comment by irrationalRock** [comment]
Hi, I'm interested in this bug.

I noticed the person filing the bug gives `<img src="./cmn/img/test.png" alt="">` as a example of a working path. I believe that path means that in the current working directory there should be folder called `cmn` that has another folder named `img` which  has photo in it.

However,  `<img src="/cmn/img/test.png" alt="">` is given as an example of the command not working.
It is true that this path doesn't work but I believe that is intentional. `/` at the beginning means it starts at the root and because of that it may be looking for `cmn` in a different spot in the directory.

For example, if my absolute path to a image is like this:
`mnt/e/int222-assign2/images/rsz_madrid.jpg`

and the location to the html file being editing is in here:
`mnt/e/int222-assign2`

I can't run the command with this code: `<img src="/images/rsz_madrid.jpg" alt="">`

But I can run it on this: `<img src="/int222-assign2/images/rsz_madrid.jpg" alt="">`

and this: `<img src="./images/rsz_madrid.jpg" alt="">`

Hopefully this information is useful.

**Comment by ramya-rao-a** [comment]
Thanks for the detailed analysis @irrationalRock! I can confirm your findings.

@MrNakka Can you share what your folder structure is? Unless `cmn` folder is directly under root, we cannot expect the command to work on `<img src="/cmn/img/test.png" alt="">`

Also see [File paths](https://www.w3schools.com/html/html_filepaths.asp)

**Comment by MrNakka** [comment]
@irrationalRock 
@ramya-rao-a 

thx comments.
I can be submitted sample folder structure.

`
/root (work space setting folder)
　├── /cmn
　│　　　└── /img
　│　　　　　　└──test.png
　│
　└── /index.html
`

Sample folder structure is working code of path:
`<img src="./cmn/img/test.png" alt="">`

is not working code of path
`<img src="/cmn/img/test.png"  alt="">`
`<img src="/root/cmn/img/test.png"  alt="">`

but,`<img src="/cmn/img/test.png"  alt="">` code is
Ctrl + LClick (img Preview) is working.
because I think passed root path of VSCode.

**Comment by ramya-rao-a** [comment]
@MrNakka Are you on Windows, Linux or Mac?

**Comment by MrNakka** [comment]
@ramya-rao-a 
Windows

**Comment by ramya-rao-a** [comment]
```
       <img src="./cmn/img/test.png" alt="">
        <img src="/cmn/img/test.png" alt="">
        <img src="/test/cmn/img/test.png" alt="">
```

- Ctrl+Click will navigate to the image file in the first 2 cases as expected in both Mac and Windows
- The `Emmet: Update Image Size` works on all 3 cases in Mac, but only the first case in Windows.

So, at the very least, we can look into if we can get the second case working to keep the experience consistent between the Ctrl+Click and the Emmet experience
