### ISSUE TITLE
Feature request: allow named capture groups in regex for problemMatchers

### ISSUE THREAD

**Issue by ceottaki** [Microsoft/vscode#50338]
- VSCode Version: 1.23.1 x64
- OS Version: Windows 7 Professional SP1

Currently, the problemMatchers in tasks.json seem to use a javascript-flavoured regex both for patterns and background begins and ends patterns, but it does not allow named capture groups in these expressions and no backreferences (\k). Therefore, a regex such as `Executed (?<qty>\d+) of (?<total>\k<qty>)` fails with the following error: `Error: The string Executed (?<qty>\d+) of (?<total>\k<qty>) is not a valid regular expression.`

Could we have support for named capture groups and backreferences added to these regular expressions?

An example of the working regex can be seen here: https://regex101.com/r/DEnCzW/1

Thank you!

**Comment by dbaeumer** [comment]
Actually the RegExp support we provide for problem matchers is limited to what JS supports. JS has positional capture groups and positional references. In JS your example looks like this:

```js
/Executed (\d+) of (\1)$/
```

I will close the issue since there is currently no plan to implement our own regular expression matching engine.
