### ISSUE TITLE
do not always launch integrated terminal's shell as a login shell

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#50340]
On macOS VS Code's integrated terminal by default uses `bash` with a `-l` option which means:
> Make bash act as if it had been invoked as a login shell

This means that bash for a newly created integrated terminal will **always** try to read `~/.bash_profile`, `~/.bash_login`, and `~/.profile`.

IMO passing `-l` is a bad idea for (at least) the following reasons:

- if VS Code is launched from a terminal where the user has set specific environment variables, VS Code tries hard to preserve these environment variables for the workspace so that a subsequent integrated terminal (or task or debug session) inherits these environment variables. By using the `-l` option this effort is negated because bash reads `~/.bash_profile`, `~/.bash_login`, and `~/.profile` which might reset the carefully established environment.

- if a different shell is configured via the `terminal.integrated.shell.osx` (e.g. PowerShell), the user is not aware that the `-l` is passed and PowerShell fails with a strange error message.

Ideally `-l` should only be used if VS Code was **not** launched from a terminal (because that would be more in line with how Terminal.app or iTerm.app behave on macOS).

This might require a new settings attribute `loginShellArgs` that is only used if the shell is started as a login-shell. However, this does not address the second problem from above.

/cc @dbaeumer @joaomoreno

**Comment by jasper-zanjani** [comment]
I was just about to file a bug report. Because it is impossible to remove that option from the default behavior, and it is not possible to specify an empty string in settings.json, the user has to manually configure a workable option (e.g. `-Interactive` for Powershell Core) which will override the default `-l`.

But the bug does break the usability of PowerShell Core in the integrated terminal out of the box, an odd decision for Microsoft devs to make.

**Comment by Tyriar** [comment]
The solution for this is captured in https://github.com/microsoft/vscode/issues/70248
