### ISSUE TITLE
AltGr invokes Ctrl+Alt shortcuts

### ISSUE THREAD

**Issue by amcsi** [microsoft/vscode#50341]
- VSCode Version: 1.23.1
- OS Version: Windows 10

Steps to Reproduce:

1. Set keyboard to the Hungarian keyboard layout
2. Make sure there is a keyboard shortcut set to Ctrl+Alt+B
3. Press AltGr+B in the editor

Expected: a `{` is typed
Actual: The Ctrl+Alt+B shortcut is invoked

This issue is basically the same as #41225

Whoever closed that ticket quoted that `Ctrl+Alt` and `AltGr` should be equivalents [based on this wikipedia article](https://en.wikipedia.org/wiki/AltGr_key#Control_+_Alt_as_a_substitute), but I digress.
It's true that even on Windows you can press `Ctrl+Alt+<key>` to get the `AltGr+<key>` equivalent character typed, _however_ it *should not be true the other way around*.
If you read the wikipedia article, it says that the ability was there to make it possible for otherwise AltGr-only characters to be typed. It does not say though that `AltGr` should invoke the hotkeys that are for `Ctrl+Alt`. If you did, you make it impossible for people using foreign keywords to use `Ctrl+Alt` shortcut sequences. Windows most certainly does not emit `Ctrl+Alt` on press of `AltGr`!

For reference, in IntelliJ there is a custom option you can enable to make sure `AltGr` does not emit `Ctrl+Alt` events: https://youtrack.jetbrains.com/issue/IDEA-91975#comment=27-384169

**Comment by alexandrudima** [comment]
@amcsi I agree with you, but this is not under our (VS Code) control and we cannot change this. We are built with Electron, which is built on top of Chromium, which follows w3c standards.

Here is where we read a `keyboard` event sent our way by Chromium. Observe the lack of doing anything with <kbd>AltGr</kbd>. We simply read the modifier flags as we receive the event : 
https://github.com/Microsoft/vscode/blob/baf3b60651bbfac50d8297b07e71240232316de9/src/vs/base/browser/keyboardEvent.ts#L230-L233

When you press <kbd>AltGr</kbd>+<kbd>B</kbd>, the event coming our way contains the key code for <kbd>B</kbd> and the flags for `altKey` and `ctrlKey` are set to true. i.e. there is no way at our abstraction level to determine if this keypress came from <kbd>AltGr</kbd>+<kbd>B</kbd> or <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>B</kbd>.

**Comment by amcsi** [comment]
I don't know that much about Chromium internals, but I would think the problem is with your abstraction layer.

[On this website](https://w3c.github.io/uievents/tools/key-event-viewer.html) I can see that it is possible in Chrome to differentiate between if an alt key press was from the right side of the keyboard.

In the screenshot, the bottom two keyup events are me just pressing down AltGr; the keydowns higher up are left Ctrl+Alt.
True that Ctrl is always shown as pressed, but together with the knowledge that out of the Alt keys the right one is down, you could ignore that combined with the Ctrl key being pressed down for the purposes of modifier keys for shortcuts.


![2018-05-28 2](https://user-images.githubusercontent.com/116494/40610791-0e1090f4-6274-11e8-81df-673999ad25f2.png)

**Comment by alexandrudima** [comment]
@amcsi 

I'm using an ISO keyboard with the German (Swiss) keyboard layout.

Here is me pressing <kbd>AltGr</kbd>+<kbd>S</kbd> on the physical keyboard:
![image](https://user-images.githubusercontent.com/5047891/40614917-f8ec8172-6284-11e8-863c-5036a93aaee7.png)

Here is me pressing <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>S</kbd> on the physical keyboard:
![image](https://user-images.githubusercontent.com/5047891/40615022-5bf72bb4-6285-11e8-8577-dd855c8e6705.png)

Here is me pressing <kbd>AltGr</kbd>+<kbd>S</kbd> using the On-Screen Keyboard:
![image](https://user-images.githubusercontent.com/5047891/40615060-88c1237a-6285-11e8-9b8a-2a720578598f.png)

Here is me pressing <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>S</kbd> using the On-Screen Keyboard:
![image](https://user-images.githubusercontent.com/5047891/40615123-c0150dd2-6285-11e8-81d6-69adf0222881.png)

---

Our keybinding dispatching executes on `keydown`, specifically on the `keydown` at number 3 in all the screenshots above. Note how the row number 3 is identical in all cases, and how Chromium reports the modifier `AltGraph` in all 4 cases.

**Comment by amcsi** [comment]
@alexandrudima I know for a fact that unfortunately AltGraph is not a reliable way to detect <kbd>AltGr</kbd>, evident also by this StackOverflow post: https://stackoverflow.com/questions/10657346/detect-alt-gr-alt-graph-modifier-on-key-press

What I wanted to bring to your attention though is the `code` column within the cyan UI Events; you can tell that an Alt is Right by it saying `AltLeft`... and good that you brought up the on-screen keyboard where apparently it's neither left nor right for <kbd>AltGr</kbd>.

This would probably require additional work to keep track of whether the left or right <kbd>Alt</kbd> was pressed down/released in the keydown/keyup events, because probably there's not enough information just looking at the keypress event with its `.xyKey` properties.

**Comment by alexandrudima** [comment]
Currently, keypress dispatching is stateless. i.e. the event coming in from the browser is treated independent from other events (with the notable exception of chords -- but that has nothing to do with tracking modifiers). In other words, **all the data and only the data** of event number 3 above is used to dispatch <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>S</kbd>

Anyways, in my experience, tracking modifiers manually is extremely error prone. (i.e. by manual I mean looking for `keydown` and `keyup` events for the modifiers keys and trying to maintain an application level modifier state).

The reason is that **surprisingly often, keydowns/keyups go missing and don't reach us**.

For example, it is possible to press <kbd>Ctrl</kbd> when focused outside of VS Code, then bring focus (via mouse) to VS Code, and then press <kbd>S</kbd> and that should be handled as <kbd>Ctrl</kbd>+<kbd>S</kbd>. The same can happen if focus is moved out of VS Code when a modifier is pressed. Or, sometimes, people use remote desktoping software or other keyboard intercepting software which cause similarly, for events to be dropped.

From my limited Windows C++ programming from more than a decade ago, I believe the recommended way was to query if a key is pressed, rather than tracking that by yourself. There is even `GetAsyncKeyState` for avoiding unprocessed messages in the event queue. From https://msdn.microsoft.com/en-us/library/windows/desktop/gg153546(v=vs.85).aspx :

![image](https://user-images.githubusercontent.com/5047891/40619895-215a40e2-6297-11e8-9cab-568c1d803907.png)

Anyways, the problem, IMHO, is that:
- either the w3c spec is broken (or too limited)
- or Chromium implements the spec incorrectly.

**Comment by amcsi** [comment]
Alright, I see. Thanks for putting in the effort to write all this down though!

I can see that because of window focus change issues you definitely cannot rely on mousedown, and if Chromium truly makes it impossible to detect right alt specifically in the keypress event, then unless you made your own Chromium fork, this will be impossible. If that's something that you don't do here, then yes I find it unrealistic that this would ever get fixed here.

I rest my case.

**Comment by alexandrudima** [comment]
Thank you, I really appreciated the discussion. If you have sufficient energy, please go ahead and bring it up at https://bugs.chromium.org/p/chromium/issues/list . I think being able to distinguish <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+ from <kbd>AltGr</kbd>+ is something any number of web applications would want to do (including the Monaco Editor) and it would only improve the web ecosystem.

**Comment by kwinz** [comment]
AltGr+S should make an ß character. Instead I get the "run task" menu jumping at me. Using US-Int keyboard layout. Very annoying. Appreciate not handling AltGr (right alt) the same as ctrl + alt

**Comment by amcsi** [comment]
Indeed that works in my Chrome as well

**Comment by alexandrudima** [comment]
This has actually changed in Chromium, so `AltGr+` no longer equivalates to `Ctrl+Alt+`. See #68003
