### ISSUE TITLE
Inconsistent closing character cursor highlight behavior

### ISSUE THREAD

**Issue by davegear** [microsoft/vscode#50373]
When I click or arrow-key on a closing character (like a parentheses or brace or bracket), if the cursor is on the _right_ side of the character, it highlights that character (and its opening character) but only if there is not another closing character right after it... at that point it will only highlight the closing character if the cursor is on the _left_ side of that character.

![image](https://user-images.githubusercontent.com/32692076/40459939-79102128-5ec1-11e8-8102-db0d25e804f6.png)

The problems with this are getting possibly misguided indications of opening character, and cumulatively a lot of extra keypresses/clicking.

Versions:

- VSCode Version: 1.23.1
- OS Version: Windows, Mac, Linux

Steps to Reproduce:

1. Make some code like this:
```
jQuery.SomeFunction = function () {
    $.ajax({
        url: 'some.url'
    })    
    .done(function (data) {
        // do whatever
    })
    .fail(function (data) {
        // do other things
    });
}
```
2. Click on the right side of a closing paren, then click or arrow-key to the left of the closing brace.
3. Notice even Notepad++ does it correctly:

![image](https://user-images.githubusercontent.com/32692076/40460053-1ba70b72-5ec2-11e8-8887-855cb612c577.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexandrudima** [comment]
Well, the current implementation first checks for a bracket to the right of the cursor, and if no bracket is found to the right of the cursor, it checks for a bracket to the left of the cursor. 

This happens to work well also when using `"editor.cursorStyle": "block"` or `"editor.cursorStyle": "underline"`.

I think giving preference to either direction has the opposite problematic case -- when multiple opening brackets are present.

**Comment by davelogear** [comment]
The issue is really that when two block characters (of any type) are side-by-side, the cursor being on the left side of the character overrides it being on the right side of the touching character... whereas other editors typically have the right side override the left. Issue #58751 shows better screenshots of the inconsistency with other editors.

You can see this left-overrides-right behavior if you copy and paste my code into VS Code and other editors, like with `ajax({ })`, clicking between ({ and then between }) will highlight the right-side character while other editors will highlight the left-side character.

The reason why I think the other editors' behavior is more normal is because usually when I have to check for where the block begins/ends, I'm somewhere buried in multiple nested blocks and somebody's either indented inconsistently or I've just lost my column path, so I end up clicking the _ending brace or paren or bracket_ (which is usually easier to click _anywhere after the character_ to put the cursor there as opposed to the empty space before it which puts the cursor outside of touching range), which I've gotten used to in every other editor (as I'm sure most other developers have), clicking to the right of the closing character to then scroll up and see the opening one.

It is an ease-of-use issue... every little thing adds up. Why VS and Code have this inconsistency... is maybe a Microsoft thing? I don't know, but it would be nice to switch it with a setting.

**Comment by starball5** [comment]
Related on Stack Overflow: [How to prefer highlighting inner parenthesizes instead of outer?](https://stackoverflow.com/q/68964497/11107541)

**Comment by winniequinn** [comment]
I know this issue is a low priority for many—as is its duplicate, #58751—but I believe that's only because this isn't a major issue for most languages. I think the current behavior is _wrong_, and I will explain why later, but it's generally fairly benign.

**For Lisp-like languages, however, this is a true usability problem.** Plugins like Calva, the most popular language plugin for Clojure, have to intentionally defeat the built-in highlighting and implement their own because the built-in approach makes s-expression editing extremely confusing.

In other editors, the highlighting indicates one of two things:

- If your cursor is next to an opening bracket, **the highlighting indicates the element you will be inserting before** when you type.

- If your cursor is next to a closing bracket, **the highlighting indicates the element you will be inserting after** when you type.

(Note that, if your cursor is next to both, you are likely not writing Lisp: No one formats code like `(...)(...)` in Lisp. Regardless, there are valid ways to handle this, and I will discuss them later.)

Take the following code as an example:

```lisp
(foo (bar ...)
     (baz (qux ...)))
```

Here's how this works in other editors:

```lisp
; correct behavior in other editors

|(foo (bar ...)
 ^    (baz (qux ...))) ; insert before (foo ...)
                     ^

(foo (bar ...)
     |(baz (qux ...))) ; insert before (baz ...)
      ^             ^

(foo (bar ...)
     (baz (qux ...))|) ; insert after (baz ...)
     ^             ^

(foo (bar ...)
^    (baz (qux ...)))| ; insert after (foo ...)
                    ^
````

In Lisp-like languages, this behavior is essential to maintain one's sanity.

In Visual Studio code, however, **the highlighting is not symmetrical**. The problem arises when the cursor is on the right side:

```lisp
; Visual Studio Code

(foo (bar ...)
^    (baz (qux ...)))| ; highlights (foo ...)
                    ^

(foo (bar ...)
^    (baz (qux ...))|) ; still highlights (foo ...)!
                    ^
```
                     
I would go as far as to say that **this is a bug**. The correct, symmetrical behavior is to **highlight the adjacent inner matching pair**. Visual Studio Code, however, highlights whatever happens to be associated with whatever character is to the right of the cursor. It's *right-biased*, and that makes no sense given that the whole point of this feature is to associate matching left and right brackets. The correct behavior is *unbiased*:

```lisp
; correct behavior in other editors

|((())) ; highlights outermost list
^     ^

(|(())) ; highlights second outermost list
  ^  ^

((())|) ; highlights second outermost list
 ^  ^

((()))| ; highlights outermost list
^    ^
```

Contrast the above with Visual Studio Code:

```lisp
; Visual Studio Code

|((())) ; highlights outermost list
^     ^

(|(())) ; highlights second outermost list
 ^   ^

((())|) ; highlights outermost list???
^     ^

((()))| ; highlights outermost list again???
^    ^
```

To restate the problem and drive the point home, @alexdima points out that the current implementation uses whatever is to the right of the cursor. He points out that checking whatever is to the left would introduce different problems.

He is correct, but that is not the only alternative. The appropriate solution, as started above, is to highlight the inner matching set. Here's a more complex example:

```lisp
; correct behavior

|(())(())
 ^  ^

(|())(())
  ^^

(()|)(())
 ^^

(())(|())
      ^^

(())(()|)
     ^^

(())(())|
    ^  ^
```

There are some cases I omitted above where different editors make different decisions. Most, I find, make an arbitrary one. The correct solutions, I propose, are to either highlight nothing or to potentially highlight multiple sets of brackets to maintain symmetry. 

```lisp
; solution one: highlight nothing

((|))(())

(())|(())

(())((|))
```

```lisp
; solution two: potentially highlight multiple sets

((|))(())
 ^ ^

(())|(())
^  ^ ^  ^

(())((|))
     ^ ^
```

In my opinion, solution two is the better one because the semantics are then very simply described: **adjacent inner matches are always highlighted**.

If no one is willing to pick this up, I might have the available time to give this a go if there's willingness to accept a patch—I've not yet looked into how much work would be required. Please let me know.

Thanks for giving this rant a read!
