### ISSUE TITLE
File unchanged after switching branches in workSpace

### ISSUE THREAD

**Issue by ma450921** [Microsoft/vscode#50381]
Issue Type: <b>Bug</b>

0. open project by using workspace file
1. git checkout [another branch]
2. file in workspace not change

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.88GB (1.32GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe D:\workspace\project\act.code-workspace|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
Bookmarks|ale|0.19.1
copy-relative-path|ale|0.0.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.50
jquerysnippets|don|0.0.1
vscode-html-css|ecm|0.2.0
json-tools|eri|1.0.2
prettier-vscode|esb|1.3.1
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
terminal|for|0.0.10
vue-snippets|hol|0.1.5
beautify|Hoo|1.3.0
smarty|imp|0.3.0
path-autocomplete|ion|1.9.0
fecs|Mar|0.10.0
vscode-autoprefixer|mrm|2.1.2
vscode-language-pack-zh-hans|MS-|1.23.5
python|ms-|2018.4.0
vetur|oct|0.12.3
tsimporter|pmn|1.2.14
vscode-icons|rob|7.23.0
vue-vscode-extensionpack|sdr|0.1.2
vue-vscode-snippets|sdr|1.3.0
autoimport|ste|1.5.3
json-schema-validator|tbe|0.1.0
python|tht|0.2.3
vscode-status-bar-format-toggle|tom|1.3.0
vscode-todo-highlight|way|0.5.12
vscode-jumpy|wma|0.3.1
JavaScriptSnippets|xab|1.6.0
html-css-class-completion|Zig|1.17.1

(2 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
VS Code is using different file watching strategies depending on your OS and your setup. 

**First thing to check:**
* [ ] I verified that the issue still reproduces in our insiders version (https://code.visualstudio.com/insiders/)
* [ ] I verified that this issue is happening outside of a `node_modules` folder. Our file watcher ignores this folder!

**To find out more about this issue, please first answer this:**
* [ ] What OS are you on
* [ ] Does this happen from an empty workspace, a single-folder workspace or a multi-root workspace?
* [ ] Do you have `files.useExperimentalFileWatcher: true` configured in settings?
* [ ] What is your configured `files.watcherExclude` setting?

**Then please answer the following depending on your setup:**
* [ ] It reproduces with any folder or workspace you open
* [ ] The files/folders you open are on your local disk and not on a network share nor a UNC drive
* [ ] The files/folders you open are not behind a symbolic link
* [ ] The folder(s) opened use the exact same casing as they are on disk
* [ ] It reproduces when I make a change to the file from another VS Code window (either from the editor or the file explorer)

**Then please attach the output of our development console**
* run `code --verbose` from the command line
* perform the action that causes you to not see the file change in VS Code
* attach the output from the console (`Help` > `Toggle Developer Tools` > `Console`)

Thanks for taking the time to fill out this questionnaire.
