### ISSUE TITLE
could not find a declaration file for request-promise

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#50480]
``` console
git clone https://github.com/microsoft/vscode-docker
cd vscode-docker && npm install
code-insiders .
```

add a new file to the workspace, add this line:

`import * as rp from 'request-promise'`

now try to get completions:

`rp(` 

result: No completions. There is a code action which on hover shows:

![image](https://user-images.githubusercontent.com/1487073/40564979-a99b4fca-601f-11e8-92d4-0a94b5a122cb.png)

Now, if you do this with a new, fresh Express app, everything works.

``` console
express testATA
cd testATA && npm install
code-insiders .
```

in `app.js` add the following:

`import * as rp from 'request-promise'`

then use it:

`rp(`

result: you get completions, everything works as expected.

![image](https://user-images.githubusercontent.com/1487073/40565067-f3c9fa6a-601f-11e8-8eb6-a553788ab863.png)

**Comment by chrisdias** [comment]
so... i figured out that i had to install `request` manually for the `request-promise` definition file to come down properly.

**Comment by mjbvz** [comment]
`request-promise` does not ship with typings files so we have to get them from `@types/request-promise`. In the docker hub example, the presence of a tsconfg means that you must manually install these typings. 

In the express example, automatic type acquisition kicks in and downloads `@types/request-promise` to the global typings cache.

I believe that this is the expected behavior. Let me know if I interpreted the issue incorrectly
