### ISSUE TITLE
Escape stopped working with recent update

### ISSUE THREAD

**Issue by yossicadaner** [Microsoft/vscode#50483]
b"H

As of most recent update, seems like the escape button no longer closes recommendations and highlights while typing.
Using Windows 10

**Comment by weinand** [comment]
Please provide reproducible steps.

**Comment by konradw86** [comment]
Jak naprawić swój sprzęt informatyczny

pt., 25.05.2018, 23:12 użytkownik Yossi <notifications@github.com> napisał:

**Comment by yossicadaner** [comment]
B"H

- Start typing 
- Suggestions popup
- Press escape button

Expected: should close popup
Actual: nothing happens

This appears more than just annoying - but makes vs code unusable for rapid coding.

**Comment by weinand** [comment]
@yossicadaner I cannot reproduce this in VS Code 1.23.1 (stable) or 1.24.0 (Insiders).

It is possible that this issue is caused by an installed extension. Can you try to run VS Code without extensions? If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by yossicadaner** [comment]
BH

It suddenly started working back today. Haven't restarted the machine or
anything. Will monitor is comes up again.  For now this can be closed I
guess
