### ISSUE TITLE
Stale actions in toolbar after invoking Alt-command

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#50581]
Steps to Reproduce:

1. checkout `ben/editor` branch
2. run it
3. Alt+click on the split action to trigger the alternative split (Split Down)
4. 🐛 the split works but the icon of the action does not change back to the side by side split

When debugging this it looks like somehow the command and its alternative version swapped, such as the menu item thinks it has to draw the Split Down action while the alternative version is the split right action. 

I found this by:
* removing this check to always update the menu item ([here](https://github.com/Microsoft/vscode/blob/ben/editor/src/vs/platform/actions/browser/menuItemActionItem.ts#L187))
* adding a `console.log(this._action)` there to understand what the menu item thinks its action should be

Otherwise, the events seem to work fine for the Alt-key as you already figured out before.

**Comment by isidorn** [comment]
Thanks for the investigation. However I do not think they swapped, since then alt on hover would switch back to the normal one. It seems like the regular action became the alternative one.
Will look in debt week

**Comment by bpasero** [comment]
@isidorn this is a consequence of the change from https://github.com/Microsoft/vscode/commit/17a5c2f420a4fc0fe7aacf8753e296e1fe0ff28f

Here is what happens:
* the Alt-key is pressed and the user clicks the split action
* a new group is created below with a fresh title bar that is filled with actions ([here](https://github.com/Microsoft/vscode/blob/ben/editor/src/vs/workbench/browser/parts/editor/titleControl.ts#L174))
* since the Alt-key is still pressed, the title bar gets the wrong actions, in this case the ones that are only alternative
* now the title bar has commands where the main action is the alternative action and there is no alternative action

I think the change from https://github.com/Microsoft/vscode/commit/17a5c2f420a4fc0fe7aacf8753e296e1fe0ff28f is risky because it can lead to exactly this issue. It should probably be changed to not cause this behaviour.

**Comment by isidorn** [comment]
Fixed in branch, closing.


Here's my analysis from a chat so we also have it shared here

A perfect scenario would be to behave like mac and to update actions dynamically while the context menu is shown dependent if alt is clicked or not. However not sure if electron supports this.
So I believe that the actionBar should pass in to the fillInActions a special option to always give him primary actions
I belive that method should be changed to do the following:
if only one array of actions is passed do same as know
if both primary and secondary actions are passed, then fill them up acordingly and ignore the alt key

I believe this will make the distincation between action bar callers and context menus.
I will experiment with this and push it to ben/editor branch since it feels a bit risky for master
yeah my approach solves the issue, I will push it to our branch so we try it out if something else gets broken

bottomline: I need to make a distinction for an actionbar that is using fillInActions - those are actionBar which can be contributed to. Thus I have added a new option to the fillInActions and have adopted it in all proper places. I will push soon and you can check out the commit and let me know what you think
