### ISSUE TITLE
Close editor button get easily broken

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#50621]
Testing #50459

Start with an empty editor group model. Make `Open Editors` visible.

1. Open a file
2. Open another file in the same group
3. Use the `X` contextual action on the first editor in `Open Editors` to close it.
4. Use the `X` again to try to close the second editor.

It won't close.

---

Even weirder:

1. Open 3 files in the same group
2. Click the first `X`, first editor goes away
3. Click the first `X` again, last editor goes away
4. Click the only `X` now, nothing happens

**Comment by isidorn** [comment]
This is some werid contextes.
I will investigate
fyi @bpasero

**Comment by isidorn** [comment]
Very good find.
The issue here is that we set the `context` in the open editors view when we render the editor. The `context` contains the `editorIndex` and it can be used later when the `editorIndex` actually differs.

As a fix on the open editors side I will listen to group changes and update the context accordingly.
This is a bit error prone, so we could change the IEditorCommandContext to have a `getEditorIndex()` function however then the context would not be seriazible which is a pain.

so fyi @bpasero since you might also use these outdated editorIndex in the tab land.

**Comment by bpasero** [comment]
@isidorn well, that context cannot be used as your model because it is very dynamic, right? The only purpose is for running commands/actions to tell about where the thing should execute on, but it should never be persisted. 

To get the index of an editor, simply use: `group.getIndexOfEditor(editor)`.

**Comment by isidorn** [comment]
Fixed on branch -> closing
