### ISSUE TITLE
Can't remove empty group from Open Editors view

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#50625]
Testing #50459

Set `"workbench.editor.closeEmptyGroups": false`.

There seems to be no way to remove an empty group when that setting is false.

Should we maybe, additionally, show a closing `X` per group over there?

**Comment by isidorn** [comment]
Yes I like that suggestion. Either an X or a context menu action

**Comment by isidorn** [comment]
Fixed in branch.
Decided to put it in the action bar and not context menu to not duplicate too much. Try it out and let me know. It nicely aligns with the open editors titile close all action

![screen shot 2018-05-31 at 15 32 13](https://user-images.githubusercontent.com/1926584/40785082-cea56c3e-64e7-11e8-8b92-f71d36ab1ac7.png)
