### ISSUE TITLE
Mark declaration, not just identifier, as unused

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#50640]
re #50487

* have the snippet below
* not how just the `a` is marked as unused but not the whole declaration

<img width="541" alt="screen shot 2018-05-29 at 12 14 07" src="https://user-images.githubusercontent.com/1794099/40652889-de52f8cc-6339-11e8-96f5-5a120a11b15a.png">

```ts

class TestMe {

    constructor(b: boolean);
    constructor(b: string)
    constructor(b: boolean | string, a?: boolean) {
        console.log(b);
    }

    callMe(): any {
        interface Foo {
            bar: boolean;
        }

        let bazz: Foo;

        return bazz;
    }
}
```

**Comment by jrieken** [comment]
Related to this: if a class isn't used its member aren't used, right?

**Comment by mjbvz** [comment]
Opened https://github.com/Microsoft/TypeScript/issues/24598 and https://github.com/Microsoft/TypeScript/issues/24597 for some of these

We decided not to mark the entire class/function bodies as unused because users often start writing them and only reference them later. Greying out the entire thing could get in the way
