### ISSUE TITLE
Improve 'Join editors of two groups'

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#50667]
Testing #50458

- Open the grid (2x2) layout, open some editors in it

Use 'Join editors of two groups' command

-> Need to improve the label to make this useful

**Comment by bpasero** [comment]
@aeschli could you also describe in what way you would want to improve the label?

**Comment by aeschli** [comment]
Probably 'Join with editor group on the left',  'Join with editor group below'...

**Comment by bpasero** [comment]
@aeschli this command is looking for neighbour groups in this order: right, down, up, left. I think I would not want to introduce new commands for each direction (and besides, we had this command before so we still need to preserve it).

We could maybe improve this command to check for the most recently used neighbour group instead of preferring the one to the right. Would that work better?

**Comment by aeschli** [comment]
I've not used that command in the past, so I don't have any expectations on how it should behave. I just want to understand what it does before I activate it as undoing it is quite some work.
`Join with next editor group` would be clear to me, but should probably be the one directly right of me (or below me) and a no-op if there is no such group.

**Comment by bpasero** [comment]
I have renamed this action to `Join Editor Group with Next Group` and the other one we had to `Join All Editor Groups` and changed the code to only join to the right or bottom.
