### ISSUE TITLE
"Reopen closed Editor" should reopen editor in its last editor group

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#50695]
VS Code version: Code - Insiders 1.24.0-insider (41a7c4976ebd1f6ced20c034485300f46ab1829f, 2018-05-29T06:09:34.618Z)
OS version: Windows_NT x64 10.0.16299

---

#50458

Right now if you have a 2x2 grid setup and close all editors/groups until there are none left, restoring after this point will restore them all into the same group. I think closing an empty editor group should count as a "closed editor" action to make `workbench.action.reopenClosedEditor` more useful when using grid layout.

**Comment by bpasero** [comment]
Related: https://github.com/Microsoft/vscode/issues/9526

**Comment by bpasero** [comment]
@Tyriar I wonder if a better model would simply be to have a stack of recently closed editors per editor group. As such, when you invoke "Reopen Closed Editor" (e.g. from the menu) it would restore the last closed editor within the context of the currently active editor group only. I think that is what others seem to do as well. 

The downside is what to do when a group gets closed. I believe the stack of closed editors should then be merged into the stack of the next active group so that you never loose a stack.

**Comment by Tyriar** [comment]
@bpasero that doesn't really fix the problem from my perspective though, would what be ideal for me is regardless of my editor group/editor layout, if I press ctrl+w x times followed by ctrl+shift+t x times it will be in the same state as at the start. ctrl+shift+t to me is an "opps, I didn't want to do that" button, undo but for editor/editor groups.
