### ISSUE TITLE
Hovering a setting does not wrap the description popup in the grid editor build

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#50720]
VS Code version: Code - Insiders 1.24.0-insider (41a7c4976ebd1f6ced20c034485300f46ab1829f, 2018-05-29T06:09:34.618Z)
OS version: Windows_NT x64 10.0.16299

---

#50458

Pretty bad one, appears to be a regression only in this build:

![image](https://user-images.githubusercontent.com/2193314/40677438-856e2ae4-6332-11e8-8c63-7052daafb723.png)

**Comment by bpasero** [comment]
@joaomoreno this is because `white-space:nowrap` ([here](https://github.com/Microsoft/vscode/blob/ben/editor/src/vs/base/browser/ui/splitview/splitview.css#L16)) seems to travel all the way down to the editor. Seems a bit weird that a component down in the tree has to unset this property, but maybe that is the way to go?

**Comment by joaomoreno** [comment]
I can take this.
