### ISSUE TITLE
Use different text decoration options

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#50779]
Specifically, one that describes that the range should grow when typing at the end. That would be `DecorationRangeBehavior.OpenOpen` or `DecorationRangeBehavior.ClosedOpen`

![kapture_2018-05-25_at_9 04 21](https://user-images.githubusercontent.com/5047891/40713397-1895389e-6400-11e8-99ef-1780963b64b4.gif)

**Comment by alexandrudima** [comment]
@mjbvz Yes, but this is not a squiggly, it is something that always grows when typing word characters, right?

**Comment by mjbvz** [comment]
The unused markers are implemented using markers that have special rendering (see the [customTags proposal](https://github.com/Microsoft/vscode/blob/3311b9ec1ddc8a0e90f900265263f165cb4e18cb/src/vs/vscode.proposed.d.ts#L413))

I do not know if the final API for showing unused variables will also be built on diagnostics/markers. We'll take a look at finalizing this api in June.

For this release, do you think we should change the markers/problems for unused variables to use a different `DecorationRangeBehavior`? Here's the relevant function: https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/services/modelServiceImpl.ts#L124

I don't know the implementation well enough to say if making this change is a good idea or not

**Comment by alexandrudima** [comment]
I leave it to you to decide if something needs to be done for May. I personally find the current behaviour annoying (annoying enough to create an issue). We don't write a lot of JavaScript, but it looks like this is mostly annoying in JavaScript.

My point about squiggles is that squiggles tend to be reduced when typing, as oftentimes squiggles show up because of incomplete code, e.g.
![kapture 2018-05-31 at 11 17 08](https://user-images.githubusercontent.com/5047891/40773783-34d012c6-64c4-11e8-8f16-409037a135c3.gif)

But the unused variables are a lot more visible (the amount of pixels & colour change for our default themes is quite noticeable) and they tend to be increased when typing:
![kapture 2018-05-31 at 11 19 23](https://user-images.githubusercontent.com/5047891/40773901-7ffcf840-64c4-11e8-8f77-d0d4a9ce9bd0.gif)

cc @Microsoft/vscode is anyone from us programming in JavaScript anymore ?

**Comment by dbaeumer** [comment]
Agree with @alexandrudima. In JS this actually looks like a color / rendering bug.

**Comment by aeschli** [comment]
@mjbvz Why not using regular warning/info squigglies?

**Comment by Tyriar** [comment]
What's different in JS and TS? They look the same to me.

**Comment by octref** [comment]
One suggestion: Get current word and filter out unused variable response from TSServer on that word.

However I'm also worried doing this computation in TSServer would be costly if it's run on each character input. Maybe TS could run this only on syntactically valid statements. e.g:

```ts
con // SKIP
const // SKIP
const ab // SKIP
const abc = // SKIP
const abc = 3 // RUN
const abc = 3; // RUN

function foo(a, ) // SKIP
function foo(a, b) // SKIP
function foo(a, b) {} // RUN
```

**Comment by mjbvz** [comment]
I think the alternative is worse. Here's using `AlwaysGrowsWhenTypingAtEdges`:

![may-31-2018 14-16-00](https://user-images.githubusercontent.com/12821956/40808815-38c7e07a-64dd-11e8-94ab-6b7f33056bc1.gif)

What we really want here is a `GrowWhenTypingWord` setting that expands the range if it grows the current word

In favor of keeping things as-is for this iteration

**Comment by mjbvz** [comment]
Closing due to the lack of further user interest expressed in the issue over the past 2 years
