### ISSUE TITLE
Wording around debug.toolbar setting

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#50786]
testing #49892:

Some observations:

Setting name:
Previously the debug bar was called "ActionBar" ("debug.hideActionBar"), "Debug actions pane" and "floating debug widget" in the documentation. Now we call it "debug toolbar".
Since there is already an "editor toolbar", is "debug toolbar" not a bit misleading?
And keep in mind that we have already a "debug status bar".

Whatever becomes the final name, we should really stick to it and fix the documentation for consistency.

The setting "debug.toolbar" sounds very broad, given that the setting only controls the placement of the toolbar. Initially I thought "debug.toolbar.placement" or "debug.toolbar.location" would be a better name but in both cases users might expect values to be "left", "bottom", "top", "right".
IMO a better (and more specific) name would be "debug.toolbar.style" or "debug.toolbarStyle".

The setting's description currently reads:
> Controls the debug toolbar. Should it be floating, docked in the debug view or hidden.

Again "Controls the debug toolbar" is broad and unspecific and "Should it be" sounds wrong to me.

Since I like to keep UI changes small and avoid deprecations my proposal would be:

We keep "debug.hideActionBar" and stick to the name "ActionBar" because the debug bar is really "a bar with actions" (and not an editor toolbar).

Setting name and value:
    `debug.actionBarStyle: "floating", "docked"`
Description:
    `Controls the style of the debug action bar. Supported are "floating" in all views or "docked" in debug view`

@Microsoft/vscode opinions?

**Comment by isidorn** [comment]
I was debating if to use "actionBar" or "toolBar" but definetly decided on "toolBar" since that is a general term known by the community.
I am perfectly fine with changing the name. However I do not like having two different settings that do a very similar thing thus I am still leaning towards deprecting the `debug.hideActionBar`
I also prefer `debug.actionBarPosition` to "style", "style" sounds too broad imho. And position could also be "hidden".

**Comment by bpasero** [comment]
Visually, especially given the grip on the left hand side, I am reminded a lot to what a toolbar is typically:

![image](https://user-images.githubusercontent.com/900690/40724277-ffec241c-6420-11e8-9d92-c11a843a99a0.png)

So I think everyone will understand what we mean with "toolbar". 

I agree that we should probably make the setting more specific though so that a user can relate to the meaning of the setting. e.g. `debug.toolBarLocation: hidden | docked | floating`

**Comment by weinand** [comment]
I tried to keep `debug.hideActionBar` setting in order to avoid that users have to adopt their settings. As a consequence we would had to stick to the name `ActionBar`.

If we drop the old setting, I'm fine with Ben's wording for the setting and the values and this description:
`Controls the location of the debug toolbar. Either "floating" in all views, "docked" in the debug view, or "hidden"`.

**Comment by bpasero** [comment]
Can we just behind the scenes still support the old setting if the other one is not defined but not advertise it in settings?
