### ISSUE TITLE
Can't save file

### ISSUE THREAD

**Issue by ahdung** [Microsoft/vscode#50814]
- VSCode Version: 1.23.1 x64
- OS Version: 6.1.7601 (windows server 2008 r2 x64)

Steps to Reproduce:

1. new a file
2. ctrl+s or click file menu>save, no any response, maybe 1min later, then the save dialog shown

**Comment by ahdung** [comment]
@octref so what should I do?

**Comment by octref** [comment]
@ahdung Are you using a remote file system? Any extension you are using? (Run `code --list-extensions`)

**Comment by ahdung** [comment]
@octref No remote file system, only local disk and all ntfs partitions. is the command in cmd run? it just open vscode for me, so i post screenshot:

![default](https://user-images.githubusercontent.com/12094247/40784072-0dde5b5c-6517-11e8-88f4-407ff06b21cb.png)

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by ahdung** [comment]
@bpasero well, i don't know what i tried, it's work now, forgot this issue.
