### ISSUE TITLE
Accessibility issues in Extensions view

### ISSUE THREAD

**Issue by et304383** [Microsoft/vscode#50883]
I shouldn't have to touch my mouse to install an extension (clicking install).

**Comment by ramya-rao-a** [comment]
Up and Down arrows let you move across the extension list
Tab key lets you move across the actionable items in a single list item. One of these actionable items is the Install button which you can then press Enter on to install the extension.

But the fact that the Install button has focus is not clear at all which we should fix.

**Comment by misolori** [comment]
@ramya-rao-a I agree that the focus color is hard to see, this is because it's a dark (blue) color on top of another dark color. I'd suggest adding `outline-offset: 1px` to allow it to have a small transparent margin to be visible. I'd also increase the outline opacity from `.60` to `1` to make it more visible. Below are before and afters:

![image](https://user-images.githubusercontent.com/35271042/40848193-58128eda-6573-11e8-9421-12139922522f.png)

**Comment by ramya-rao-a** [comment]
Its still not very distinguishable though. I had to search through the 4 items to see which one had the outline :)

**Comment by et304383** [comment]
I can't believe the solution being proposed is "tab tab tab tab tab enter"

**Comment by misolori** [comment]
@ramya-rao-a  We could increase the size of the outline, but the outline border is our default styling across the product.

![ezgif com-gif-maker 16](https://user-images.githubusercontent.com/35271042/40853086-a85ad4c0-6581-11e8-8c4d-5a8b32662280.gif)

**Comment by ramya-rao-a** [comment]
When its moving like that, it is definitely noticeable. We'll give that a try.

**Comment by ryanwebjackson** [comment]
@et304383 It only requires one Tab button press, then Enter - I just tried this (on Windows). I believe this makes sense because without pressing tab, you get the information tab for the extension, which is the same action as if you clicked on it.

**Comment by ramya-rao-a** [comment]
Turns out pressing Enter on the list item when the item has focus does open the extension editor. What confused me was that when the cursor is in the search box, the arrow keys took the focus to the list items. Then when you press Enter, the extension editor wouldnt open. This is because the **real** focus was still in the search box. We should fix this as well
