### ISSUE TITLE
vscode does not pickup tsconfig.json files in subdirectories

### ISSUE THREAD

**Issue by CoreyCole** [Microsoft/vscode#50910]
According to @mjbvz in https://github.com/Microsoft/vscode/issues/4466

> [vscode does pick up] tsconfig.json files in subdirectories and treat those subdirectories as individual projects. If you are not seeing the correct behavior around this, please open a new issue and I can take a look

- VSCode Version: 1.23.1
- OS Version: OSX 10.13.4

Steps to Reproduce:

1. clone https://github.com/CoreyCole/tsconfig-bug
2. open vscode at the root, open another vscode window in the subdirectory `tsconfig-bug`
    - install node modules in subdirectory
3. see the root window has red lines in `tsconfig-bug/test/app.e2e.spec.ts` but in the subdirectory window the typing information is correct

[You can see me reproducing the issue](https://i.imgur.com/7Tdaufv.gifv)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
This is unrelated to the tsconfig. That file is not part of any tsconfig because you have excluded it the `include` and `exclude` rules. 

The issue you are seeing is that we don't load global types (like those used by jest) from node_modules in sub folders by default. You can fix this by adding:

```
import 'jest'
```

to the file. Or by making the file part of a real `tsconfig` that contains:

```
 "typeAcquisition": {
    "include": [
      "jest"
    ]
  }
```
