### ISSUE TITLE
Notifications: Updating message recreates notification (drops progress bar)

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#50931]
this continues  #50479. as said [here](https://github.com/Microsoft/vscode/issues/50479#issuecomment-393512359) there still a few cases missing, esp. 2 looks weird. It seems like the message is interpreted as some kind of default increment, I'd expect an infinite progress in the absence of discrete increments.

![jun-01-2018 11-17-25](https://user-images.githubusercontent.com/1794099/40833213-88038292-658d-11e8-930a-96ce7b59b0d5.gif)

```ts
        await vscode.window.withProgress(
            {
                location: vscode.ProgressLocation.Notification,
                title: "Test 2: report only message"
            },
            async (progress) => {
                await wait1();
                for (let i = 0; i < 10; ++i) {
                    progress.report({ message: `message ${i}` });
                    await wait2();
                }
            });
```

**Comment by bpasero** [comment]
Pushed a change that "fixes" this when the notification is collapsed (which it is by default) because then we notification has a fixed height independent of the content. 

If a notification is expanded the challenge is to adjust the height of the list item (that is used to render notifications) without splicing the item from the list (which is currently not possible). And splicing currently removes the spinning progress from the DOM and adds it back which unfortunately means the animation always starts at 0 again.

**Comment by bpasero** [comment]
**Verification:** please look at https://github.com/microsoft/vscode/issues/50931#issue-328443298 but craft a message that will cause the notification to wrap (i.e. has long text). We still want the notification to grow in height when text overflows.
