### ISSUE TITLE
Can't see files to commit

### ISSUE THREAD

**Issue by ryan-wong** [Microsoft/vscode#51028]
Issue Type: <b>Bug</b>

Git is in folder

add file or change file. usually if you click git button, it shows files that changed. now it shows nothing. if i click the plus button it add to stage and appear. this use to work

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T16:03:31.083Z)
OS version: Darwin x64 17.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (6.41GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
react-native-react-redux|EQu|1.9.0
beautify|Hoo|1.3.0
crane|Hvy|0.3.8
format-indent|Kas|1.3.0
vscode-react-native-storybooks|Ort|2.5.1
copy-relative-path|ale|0.0.2
npm-intellisense|chr|1.3.0
vscode-javascript-snippets|cod|1.0.0
githistory|don|0.4.1
RelativePath|jak|1.4.0
relativepathrefactor|jak|0.9.0
vue|liu|0.1.5
MagicPython|mag|1.0.12
mssql|ms-|1.3.1
python|ms-|2018.4.0
vscode-uppercase|rui|1.0.1
python|tht|0.2.3
vue-ls|van|0.1.5

</details>

**Comment by joaomoreno** [comment]
@bpasero File events

**Comment by bpasero** [comment]
VS Code is using different file watching strategies depending on your OS and your setup. 

**First thing to check:**
* [ ] I verified that the issue still reproduces in our insiders version (https://code.visualstudio.com/insiders/)
* [ ] I verified that this issue is happening outside of a `node_modules` folder. Our file watcher ignores this folder!

**To find out more about this issue, please first answer this:**
* [ ] What OS are you on
* [ ] Does this happen from an empty workspace, a single-folder workspace or a multi-root workspace?
* [ ] Do you have `files.useExperimentalFileWatcher: true` configured in settings?
* [ ] What is your configured `files.watcherExclude` setting?

**Then please answer the following depending on your setup:**
* [ ] It reproduces with any folder or workspace you open
* [ ] The files/folders you open are on your local disk and not on a network share nor a UNC drive
* [ ] The files/folders you open are not behind a symbolic link
* [ ] The folder(s) opened use the exact same casing as they are on disk
* [ ] It reproduces when I make a change to the file from another VS Code window (either from the editor or the file explorer)

**Then please attach the output of our development console**
* run `code --verbose` from the command line
* perform the action that causes you to not see the file change in VS Code
* attach the output from the console (`Help` > `Toggle Developer Tools` > `Console`)

Thanks for taking the time to fill out this questionnaire.
