### ISSUE TITLE
vscode.debug.breakpoints is empty on the first access

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#51057]
- Have a command that logs the contents of `vscode.debug.breakpoints`, like

```ts
vscode.commands.registerCommand('vscode-breakpoints.exportBreakpoints', () => {
    console.log(JSON.stringify(vscode.debug.breakpoints));
});
```

- Add some breakpoints
- Run the command, see `[]`
- Run the command again, see the correct output

**Comment by isidorn** [comment]
@roblourens good catch. I can reproduce this.
The issue seems to be that the `breakpoints` is a sync call which reallies on an async method [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/node/extHostDebugService.ts#L227) 
It seems like the `startBreakpoints` should be called before the first `breakpoints` get is called.
Though forwarding to @weinand since he is the original author. Feel free to assign back.

**Comment by weinand** [comment]
That's by design (discussed with @jrieken) and documented: https://code.visualstudio.com/updates/v1_19#_debug-api-updates

In order to not waste time on unnecessary breakpoint synchronisation, we start synchronising only after some initial breakpoint related request (e.g. an access of the vscode.debug.breakpoints array) has been issued by an extension.

However, since the EH api is async by nature, we cannot fulfill an array access in a sync way.

**Comment by roblourens** [comment]
Oh, didn't know that. Thanks.
