### ISSUE TITLE
How to suppress opening launch.json when resolveDebugConfiguration wants to cancel launching?

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#51069]
@isidorn This is slightly related to https://github.com/Microsoft/vscode/issues/43133. Currently I set `type=null` if I want to force the `launch.json` open, but now I have a new user case.. In my resolve method, if a user doesn't have a mobile device connected, I ask them to either connect one or select an emulator to launch:

<img width="700" alt="emulator_list" src="https://user-images.githubusercontent.com/1078012/40904303-363c3dae-67d2-11e8-96d7-1719956ae566.png">

If the user hits `<ESC>` here, I'd like to just cancel the launch request (silently, with no message). However currently it creates and opens a `launch.json`. Since we generally encourage people to run without a `launch.json` now, having one created here feels clumsy.

Is it possible to have a way to suppress the creation/opening of `launch.json`? I'd be fine if it was done by` type=null` and I changed the other code paths to throw errors (or similar) where I do want to open the `launch.json` (though I don't know if that would be breaking for others).

**Comment by isidorn** [comment]
This is currently not possible, in case we decide to do something here we would first need to specify and document the behavior so other debug adapter authors are not surprised.

Current behavior:
* If `resolveDebugConfiguration` return a `config` with a `type` we start debugging
* if `resolveDebugConfiguration` returns `undefined`, an error we automatically open the `launch.json` since this feels like an error that the user should fix

I understand that the second behavior does not work well with the no `launch.json` debug case and we could potentially improve it.

For example the extension could return `undefined` as a configuration and that would be a no-op. 
On the contrast throwing an error could force the `launch.json` to be opened. I understand this is breaking behavior but just throwing ideas out there

fyi @weinand

**Comment by DanTup** [comment]
The second bullet point should probably mention that an undefined `type` property triggers this (not just undefined return value).

I think your idea is good; an error should result in the error being shown to the user and the launch.json openings, and returning undefined signals a silent quit.

**Comment by DanTup** [comment]
This has been addressed in https://github.com/Microsoft/vscode/issues/54213.

cc @ThadHouse since your https://github.com/Microsoft/vscode/issues/54702 was closed as a dupe of this one.

**Comment by isidorn** [comment]
@DanTup thanks for finding this one and closing it, appreciate it!

**Comment by ThadHouse** [comment]
Thanks! I'll go and implememnt this in my extension.
