### ISSUE TITLE
NVDA should not read out 'clickable' for links

### ISSUE THREAD

**Issue by AccessibilityTestingTeam-TCS** [Microsoft/vscode#51077]
**Environment Details:**
VSCode Version : 1.23.1
OS Version : Win10

**Repro Steps:**
1. Launch VS Code while NVDA is ON.
2. Navigate to Welcome screen.
3. Read all the lists, list items, buttons, links present on the screen while navigating using "Tab" key.

**Actual:**
NVDA reads the word "Clickable" with each list, listitem, buttons, links, checkbox etc.

**Expected:**
NVDA should only read the name of the control along with relevant state, value and role. It should not read "Clickable" for every control present on the screen.

**Recommendations:**
Refer below link which is repository of bug fixes code snippets:
https://microsoft.sharepoint.com/teams/msenable/mas/pages/browse-fixes.aspx

**User Impact:**
The user will not be able to get clarity about control's name, state, role, value and other important info if screenreader reads "clickable" after each word it reads.

**MAS Reference:**
MAS 1.3.1-
(https://github.com/Microsoft/vscode/files/2067970/A11y_VSCode_Welcome_NVDA_Clickable.pptx)

https://microsoft.sharepoint.com/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={54f28d1f-a2d1-4dcd-84e1-5c9b87e8aba4}

Attachment for Reference: [A11y_VSCode_Welcome_NVDA_Clickable.pptx]

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
All those items in the welcome screen are links, so I do not understand what is unexpected in the fact that they are read as "clickable" or "link" on mac.
I just tried chrome and web browsers behave the same - so I think this is expected behavior.

So I am not sure there is a way to fix this, unless we stop using html links in the welcome screen and wrap them around with actions.
