### ISSUE TITLE
Data inspection for large ES6 Map/Set not expanding correctly

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#5108]
- VSCode Version: 0.10.12-alpha
- OS Version: Windows 10

Steps to Reproduce:
1. Follow the test plan #4949 for Set and Map
2. Expand the lm: Map [1200] variable or ls: Set [9000]
3. Try to expand a few of the nested variables in quick succession

![debuggingmap](https://cloud.githubusercontent.com/assets/12900364/14398234/751d5b7c-fd97-11e5-9209-8125cf7cbee1.gif)

If one is loading, the rest likely will not expand and will not load until you restart debugging despite trying to expand/collapse again.

**Comment by weinand** [comment]
@isidorn please investigate whether this a frontend or backend issue.

**Comment by isidorn** [comment]
Interestingly I can only reproduce this on Win, but not on Mac.

I am not recieveing any error from the backend, just the response is not coming back from nodeDebug. Due to this I believe this is a nodeDebug issue and forwarding to @weinand 

Related issue which I also sometimes see on both platforms is nodeDebug crashing after expanding a large set, and stepping. This seldomly happens but it might be that too many variables request can crash nodeDebug. nodeDebug does not send any meaningful messsage on crash - so I do not have more details.

Here's a code snippet to repro:
```js
const lm = new Map(); 
for (var i = 0; i < 1200; i++) { lm.set(i, i * i); }
```

![nodedebugcrash](https://cloud.githubusercontent.com/assets/1926584/14494658/2efa4ef4-018c-11e6-813f-a5b67df6bfe1.gif)

**Comment by isidorn** [comment]
@vsccarl Please re-test this with latest alpha and let us know if you still see it becaue we have fixed some issues

**Comment by isidorn** [comment]
I tried this with latest alpha and I still see it. Though only on windows and I do not think it is critical since it only happens if the user expands the nodes very fast -> setting to May and forwarding to Andre
