### ISSUE TITLE
Add to watch for large Map/Set is undefined

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#5110]
- VSCode Version: 0.10.12-alpha
- OS Version: Windows 10

Steps to Reproduce:

1. Following #4949 
2. Add either a large map or set

`const lm = new Map(); 
for (var i = 0; i < 1200; i++) {
  lm.set(i, i * i);
}`

3. Expand lm: Map[1200], expand some range, expand an item.
4. Add the value to watch

![mapaddtowatch](https://cloud.githubusercontent.com/assets/12900364/14399549/804b0ee4-fda2-11e5-881e-2355d075fc1b.JPG)

**Comment by isidorn** [comment]
It is impossible to access map objects directly like this. You have to use the `get` method
If you start node, or google chrome dev console you can notice the following
![screen shot 2016-04-13 at 11 47 39](https://cloud.githubusercontent.com/assets/1926584/14489449/8f4b911a-016d-11e6-9cf2-3dc90517f1e8.png)

I understand that this is unhappy behavior for the 'add value to watch' action but closing this as expected behavior.
