### ISSUE TITLE
Bad progress bar css rule

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#51135]
Their is a css-rule in `parts.css` that causes all progress bar that sit in the side bar to be weirdly positioned. See: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/media/part.css#L68

<img width="947" alt="screen shot 2018-06-05 at 11 27 30" src="https://user-images.githubusercontent.com/1794099/40967554-93670432-68b3-11e8-8d01-860e543efd1f.png">

**Comment by isidorn** [comment]
I basically put a more specific css rules. Since the current one was applied in the composite and in the grid view.
Maybe a bit ugly that I am referencing 'monaco-grid-view' in `part.css`
The alternative is to reference editor.part in parts.css, or to duplicate the css rule in the `editorgroupview.css`
fyi @bpasero
