### ISSUE TITLE
have to hit "install" 3 times before plug-in actually installs

### ISSUE THREAD

**Issue by msgregman** [Microsoft/vscode#51172]
Issue Type: <b>Bug</b>

1. open URL for a plugin, eg. https://marketplace.visualstudio.com/items?itemName=ms-vscode.csharp
2. click "install"
3. click "launch vscode"
4. click "install" after page loads
5. observe notification
6. click "install" once more

expected: after step 2, i would expect it to start installing after launching vscode...there's too many redundant steps here.

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.17134

**Comment by joaomoreno** [comment]
> after page loads

What page?

This only occurs if Code isn't yet running? If Code is already running, everything works OK?

**Comment by msgregman** [comment]
The page for the extension itself, within VSCode. I can replicate these same steps with VSCode already open, as well. My expectation is I only have to click install once, but instead it happens once in the browser, once in the extension page, and then finally the notification that shows up in the bottom right corner.

**Comment by joaomoreno** [comment]
Here's what I see:

1. Click `Install` in the Marketplace
2. Code comes up, opens the extension and a popup shows in the corner "Would you like to install?". I press `Install`, and the extension installs.

I don't think you have to click once in the extension page, like you mentioned. Can you confirm this?

Finally, we need confirmation within VS Code because ill-intended users could publish a malicious extension, and fool you into clicking a link in a page which would just download, install and possibly run malicious code in your machine.

**Comment by msgregman** [comment]
for me, before the pop up appears, I have to hit "install" once more. I think the pop up a major source of my concern: it is confusing to show up in the bottom right corner, since my focus had been in the upper left (where description is)

**Comment by joaomoreno** [comment]
That doesn't make much sense. Here's the code that runs this:

https://github.com/Microsoft/vscode/blob/e58f7975e33d042a91e39ab23c6ff6fb41d6e100/src/vs/workbench/parts/extensions/node/extensionsWorkbenchService.ts#L948

As you can see in code, the prompt should appear right after the extension is open. The only reason why the popup wouldn't open would be an occurring exception right between those two lines of code. Do you see any errors in the Devtools console?
