### ISSUE TITLE
Duplicate problems entries after rename on case-insensitive filesystem

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#51184]
*Opening individual cases to track bugs around file system casing with js/ts*

**Steps**
1. On a case insensitive file-system (normal Mac OS or windows)
1. Run `Clear editor history` 
1. Restart VS Code in a project with a basic `tsconfig.json`
1. Create a file called `abc.ts` with the contents: 

    ```ts
    const i = error
    ```

1. Opens problems panel and error note error entry for `abc.ts`
1. Use  explorer to rename file to `ABC.ts`

**Bug**
Two entries (with different cases) for `abc` are now in problems panel

**Comment by mjbvz** [comment]
Moving this out. Addressing it properly was more difficult than anticipated since the diagnostic collection is another piece of state that must be managed

**Comment by hmil** [comment]
@mjbvz This is likely related to https://github.com/angelozerr/tslint-language-service/issues/76 . Someone tried bringing your attention to it in #54164 but the issue was shut down.

There seems to be some confusion in `bufferSyncSupport.ts` with respect to filename case, most likely originating from https://github.com/Microsoft/vscode/commit/c40a2fd096973b87e4738c2c71145fecfda73d99 .

VSCode is sending mixed signals to `tsserver` with messages such as this one in the tsserver log:

```
Info 106  [20:12:45.2] request:
    {"seq":16,"type":"request","command":"geterr","arguments":{"delay":0,"files":["/Users/hmil/workspace/tslint-override-test/TestClass.ts","/users/hmil/workspace/tslint-override-test/testclass.ts"]}}
```

I could open a new issue with the exact repro to get this ☝️ message if you think that would help. It happens merely when opening a file with upper case letters on MacOS.

What is the plan here? Do you intend to always (on case insensitive systems) send file paths in lowercase to tsserver, or do you want to keep the original case?

**Comment by mjbvz** [comment]
@hmil yes that shouldn't happen but that's unrelated to this bug. Please open a new issue. The intent is that we preserve the first known casing of a file and then normalize to that on case-insenstive file systems

**Comment by hmil** [comment]
Thanks for the rapid response. #55266 is tracking that now.

**Comment by mjbvz** [comment]
This seems to be fixed in the current insiders builds in my testing.
