### ISSUE TITLE
Parameter hints eat arrow keys

### ISSUE THREAD

**Issue by mrchief** [Microsoft/vscode#51191]
- VSCode Version: 1.23.1
- OS Version: Windows 10 x64

Steps to Reproduce:

1. Start typing a method with multiple signatures.
2. After entering parameters, try going down using arrow keys.
3. Instead of cursor going to next line, it cycles the signatures in the parameter hint popup.

Does this issue occur when all extensions are disabled?: Yes

![image](https://user-images.githubusercontent.com/781818/41009411-f1740796-68fe-11e8-8a77-f067d5774775.png)

In the above screenshot, when the cursor is after the last parameter, i.e. after `s` of `this.totalPages`, I cannot go to the next line without dismissing the hint.

This popup and it stealing keys is annoying as hell. I don't want to completely disable it but I don't want to hit `esc` key everytime I enter few chars. It'd be nice if:

 - it didn't steal focus
 - can appear after a delay
 - or disabled but can be manually invoked with a key combo

**Comment by mrchief** [comment]
Agreed. Although that'd still be cumbersome with langs that run overloading on steroids (c#, java etc.) but in this case, it's better than current behavior.

**Comment by distinctdan** [comment]
This is an annoyance of mine as well. VS Code is completely obnoxious for editing lists because of it, and is annoying day to day as well. This, and the tooltip text being selectable and in the way, are serious issues that detract from everyday usability.

I think it would be best for the list to close if you've typed something that's valid.

For example, if I'm making a list of values, I'll copy and past the first one, then try to use the arrow keys to navigate to each additional item to edit it. However, because each item is an property, VS Code keeps the menu open with suggestions even though I've already finished typing what I want it to be.
```
// In-progress list, menu pops after editing each line
private readonly freeLevels = [
    LevelId.L1,
    LevelId.L1,
    LevelId.L1,
    LevelId.L1,
    LevelId.L1,
];

// After editing each item
private readonly freeLevels = [
    LevelId.L1,
    LevelId.L2,
    LevelId.L3,
    LevelId.L4,
    LevelId.L5,
];
```

**Comment by itamark** [comment]
Hey @jrieken - is this ready for implementation at least for the one-cycle option? Would love to take it if so.

**Comment by jrieken** [comment]
You mean, you wanna make a PR? Go for it.

**Comment by itamark** [comment]
Okay here's my go at it: 
#53757 

I also made it so that if you go up and are on the first signature it closes the hints. Basically, if you're going out of bounds of the list, you're closing the hints. Seems like the right solution, and will help with the larger sets of signatures issue.
