### ISSUE TITLE
Addootion to show task output in output pane

### ISSUE THREAD

**Issue by mojo2012** [Microsoft/vscode#51202]
Hi,

When i run an ant task the console output is shownin a shared terminal pane.
This makes no sense to me as it is a readonly output.
I‘d rather like to see it in the output panel under ‚tasks‘.
It should be possible to configure this on a per-task basis

**Comment by dbaeumer** [comment]
We had that in the past and we switch to use the Terminal especially since a terminal has full ANSI control character support which a simple output pane has not. 

I will close the issue since we have no plans right now to move back to the output pane. It has too many other disadvantages. Please speak up if think you think otherwise.

**Comment by dbaeumer** [comment]
You mean the Tasks channel of the Output panel. It is for problems occurring during task execution but don't come from the task / process itself.

**Comment by dbaeumer** [comment]
IMO this is partly possible with the `presentation` option when running in the terminal. You could for each task have a dedicated terminal in which case they are basically group. But there is no support yet to have two task share the same group. One share a task terminal that is marked as shared.

**Comment by mojo2012** [comment]
Define custom groups is what i need!
