### ISSUE TITLE
增加账户系统，比如把Windows账户加进来

### ISSUE THREAD

**Issue by Xanthuim** [Microsoft/vscode#51219]
把Windows账户加进来，我在VSCode在线安装的插件，只要上传了，在任何地方都可以下载使用。当然还有其他在线功能。

**Comment by aeschli** [comment]
@rebornix @octref Can you help to translate? Online translation did help much.

**Comment by helaoban** [comment]
He says: "Add an account integration system, for example allow logging into Windows accounts, so that whenever I add plugins while I'm online (connected to my account), as long as they have been uploaded, they will then be available for download and use anywhere else (other machines ?). Of course there are also lots of other uses for this". 

Yep, the question is just as convoluted in Chinese, translation won't help. I think he's referring to something like this #44246.

**Comment by octref** [comment]
For now you can try https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync
