### ISSUE TITLE
option to display parameter info tooltip in a separate pannel

### ISSUE THREAD

**Issue by aviau** [microsoft/vscode#51253]
Instead of displaying the parameter info tooltip next to cursor, I would like to have an option to display it in a separate panel, maybe a "documentation" panel next to Problems / Output / Debug Console / Terminal.

Some of us disable these tooltips because we find them annoying. However, we find them useful and it would be a good compromise to have them available somewhere.

This idea is from https://github.com/Microsoft/vscode/issues/33752#issuecomment-340151000

**Comment by jrieken** [comment]
> displaying the parameter info tooltip next to cursor

Just to clarify what you mean by 'parameter info tooltip'. Is that the hover, the intelli-sense window, or the suggest window? I'd assume the second, right?

**Comment by aviau** [comment]
I was refeferring to the following window:
![screenshot from 2018-06-07 10-10-35](https://user-images.githubusercontent.com/2706882/41105173-0b63c80c-6a3b-11e8-82b2-b35773b20f94.png)

**Comment by ivolucien** [comment]
I strongly support any configuration option that allows us to see the code we are editing while getting value from intellisense method / param suggestions.

1) first preference is for this doing **any** of the related suggestions that have been made to make text near the cursor visible, like this ticket
2) any user option to offset the window to the right and/or below the text cursor, ideally by persisting the user's drag positioning of the param hint window (will see if I should open a ticket for this suggestion)

**Comment by ramya-rao-a** [comment]
This feature request is one of the options to solve the problems discussed in https://github.com/Microsoft/vscode/issues/33752#issuecomment-340151000. 

@jrieken I would suggest to close this in favor of #33752
cc @joaomoreno

**Comment by aviau** [comment]
@jrieken The issue you mention says create an option to position it at the top or the bottom. None of these solutions would work for me.

**Comment by ramya-rao-a** [comment]
> The issue you mention says create an option to position it at the top or the bottom. None of these solutions would work for me

@aviau Can you elaborate on why those options wouldnt work for you?

**Comment by aviau** [comment]
> Can you elaborate on why those options wouldnt work for you?

I like to see all the text. Whether it is under my cursor or below my cursor, I want to be able to read it.

Also, displaying the information in another window would allow me to set the intellisense window to appear all the time, with **no delay** and **no key to press**. Disabling the delay or key shortcut would be extremely annoying if it appears over the text. However, if it is in a separate pannel, it won't be botherting at all.

https://github.com/Microsoft/vscode/issues/51253#issuecomment-411662973 is a similar example.

**Comment by Friksel** [comment]
+1
I fully support the idea of @aviau . Those tooltips show great information I'd like to fully read and use a lot, but at the same time they are annoying, because they hide the code underneath which is obviously pretty important to see at the same time. The solution of @aviau solves this and everybody can even decide to open/close/size the panel! Seems like a solution to a lot of problems!

**Comment by buggymcbugfix** [comment]
This would be very useful. I really dislike having to move my mouse pointer and wait for the popup to appear. More info and great screenshots in this issue: https://github.com/microsoft/vscode/issues/57466.

**Comment by freMea** [comment]
A bar/panel at the bottom of the editor that would appear with no delay could do the trick too.

But with the new flexible layout released in may 2020, a parameter info view that one can move everywhere would be nice too. Maybe a new activity being oriented towards code documentation that would implements the current parameter info tooltip as well as other documentation aggregator like DevDocs would be nice and complete.

I have a workaround to have access to this info tooltip without being annoyed by them. I explain it here #102198 because this highlighted another bug.

Here are other related issues more or less duplicate : #33752, #16221 (an awesome feature suggestion), #15667, #30797, #63144.

**Comment by mjbvz** [comment]
This can now be implemented by extensions. The [Docs View](https://marketplace.visualstudio.com/items?itemName=bierner.docs-view) extension for example adds a panel that shows the hover documentation in the sidebar or panel

If anyone wants to help out, this issue tracks adding a second panel/view in that extension for signature help: https://github.com/mattbierner/vscode-docs-view/issues/2
