### ISSUE TITLE
Process crashes and graphical glitches occasionally when running on ubuntu through virtualbox

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#5126]
To fix this in Chrome I needed to toggle off the "Use hardware acceleration when available" checkbox in advanced settings. This maps to the Chromium pref `hardware_acceleration_mode.enabled`, aka `kHardwareAccelerationModeEnabled`.

**Comment by Tyriar** [comment]
On second look, while I did get Atom to crash it seems that it handles this better than vscode currently. I'll look into it more after Electron is updated.

**Comment by davidmcl** [comment]
This is an issue that I have all the time when, running linux mint client under virtualbox -- since vbox additions 5.0.20 (although I believe on 5.0.18 as well).

While I suspect that it's upstream, I was hoping to find a way to turn off hardware acceleration on VS Code - which is why I was out here looking for a related issue. I was hoping that there might be a switch or config option to turn off hardware acceleration for VS Code and that would let Code run...is there?

For me, on linux mint 17.3, as a virtualbox client, both the Chrome browser and VS Code locks completely and only runs correctly when either...
1) I turn off 3D display acceleration for the the whole guest in the settings, both run OK, or...
2) I run virtualbox guest additions 5.0.16 or earlier, both run OK
2) I turn off hardware acceleration for the Chrome browser, in Chrome settings, then Chrome browser runs OK, even with the 3D accel on for the rest of the client - which is why I was looking for an option to turn it off in VS Code

interestingly, on Centos7 + vbox additions 5.0.20, VS Code runs OK

In all cases, the vbox host is windows 10 pro

Hope that makes sense.

thanks,
David
