### ISSUE TITLE
Reopen always last session

### ISSUE THREAD

**Issue by stefanocog** [Microsoft/vscode#51350]
- VSCode Version: 1.24.0
- OS Version: Linux Mint 18.3

From last update to version 1.24.0, every time I launch vscode, the last session is always opened, although in the settings there is "window.restoreWindows": "none"

Steps to Reproduce:

1. Open a folder
2. Close vscode
3. Open vscode and i have the last session

Does this issue occur when all extensions are disabled?: IDK

**Comment by bpasero** [comment]
@stefanocog does that reproduce if you:
* open a terminal
* type "`code`" and hit `Enter`
* close the window that opened
* type  "`code`" and hit `Enter`

**Comment by stefanocog** [comment]
yes, same behavior

**Comment by bpasero** [comment]
@stefanocog I cannot reproduce this behaviour, can you attach your settings file?

**Comment by bpasero** [comment]
@stefanocog thanks, from the video I see what is going on, you are actually creating an "untitled workspace" by adding a folder to the explorer. We will restore "untitled workspaces" until they are saved or closed. But otherwise we will restore them to not loose configuration data.

To open just a folder, you can use File > Open Folder instead.
