### ISSUE TITLE
Unused variable detection : Comment coloration is not instant.

### ISSUE THREAD

**Issue by Guema** [Microsoft/vscode#51354]
- VSCode Version: 1.24.0
- OS Version: Windows 7x64

Steps to Reproduce:

1. declare an unused variable
2. comment this unused variable

bug : unlike variables that are used, commenting an unused variable declaration will not instantly color it with the comment color. it happends after a little delay.

Does this issue occur when all extensions are disabled?: Yes/No
Yes.

**Comment by Guema** [comment]
Also append with unused imports.

**Comment by mjbvz** [comment]
Not easily fixable. Comment colorization comes from a grammar and can be super fast. Unused colorization comes from  semantic analysis, which is much slower. Our current method overlays the second pass onto the first. Since this works, and since I don't know if there is better approach that won't just introduce even worse jittering, closing as out of scope
