### ISSUE TITLE
Explorer pane variable line height

### ISSUE THREAD

**Issue by sureshgururajan** [Microsoft/vscode#51402]
Can we have a variable with which we can adjust the line height of the explorer pane on the left side? Adjusting the line height I feel is a good alternative to zooming out. I know we have this feature for the editor (editor.lineHeight) and I think it'd be great if we had something similar for the explorer pane too.
Please let me know if one already exists. I tried searching but didn't find one.

**Comment by sureshgururajan** [comment]
thanks guys! appreciate it ! 👍

**Comment by ssbarnea** [comment]
This request should be open because ability to lower the line heigh would improve the UX and accesibility for those with big projects.

THere is a reasons why we want ~1.5x spacing on source code editor, but the same rule should not apply to the tree view (explorer) where is essential to minimize the need for scrolling.

This is linked ot the issue of not being easy to change the font size for the explorer where the trick is to zoom out entire UI to -1 or more and to oversize the editor font to 14-16, so you would get the desired side effect.
