### ISSUE TITLE
Arrow navigation broken in "Search" panel

### ISSUE THREAD

**Issue by martellaj** [Microsoft/vscode#51472]
Issue Type: <b>Bug</b>

NOTE: I have search in panel.

1. Open search, and focus is put in first input where search text goes.
2. Hit down arrow.

Expected (old behavior): Focus shifts to "files to include" input.
Actual: Nothing.

VS Code version: Code - Insiders 1.25.0-insider (8f8ed32e737a7a906fac654fb0bd61b257b449b1, 2018-06-08T05:20:32.976Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.79GB (12.16GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
snapshot-tools|asv|0.0.7
bracket-pair-colorizer|Coe|1.0.58
gitlens|eam|8.3.5
tslint|eg2|1.0.30
prettier-vscode|esb|1.5.0
sort-typescript-imports|mic|1.4.1
csharp|ms-|1.15.2
debugger-for-chrome|msj|4.5.0
polacode|pnp|0.2.2
project-snippets|reb|0.5.0
vscode-icons|rob|7.23.0
vscode-todo-highlight|way|0.5.12

(3 theme extensions excluded)

</details>

**Comment by sandy081** [comment]
@martellaj This was due to the change of defaults

- Default shortcuts for History navigation in the input boxes are Up and Down arrows
- Default shortcuts for navigating among input boxes are `cmd+Up Arrow` and `cmd+Down Arrow`

Change was done because of this https://github.com/Microsoft/vscode/issues/12645. This made all our history navigation to be consistent and use Up and Down arrows.

You can always change the behaviour back by updating the keybindings to the following commands

Search Inputs navigation commands: `search.focus.nextInputBox` and `search.focus.previousInputBox`

Input history navigation commands: `input.action.historyNext` and `input.action.historyPrevious`

**Comment by martellaj** [comment]
@sandy081 Thanks for the explanation!
