### ISSUE TITLE
Accessibility: Pressing alt should focus window menu items 

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/vscode#51493]
Learnings from NVAccess testing:

It would be nice if pressing alt by itself would focus the menu bar, then allowing you to press left and right arrow to move between each ov the available menus (File, Edit, View, Go and Help). This would aide in much better discoverability and standardization. right now, a blind user has no way of knowing what menus are available with out previous knowledge of each individiaul emnu shortcut. Electron issue #2504

**Comment by sbatten** [comment]
resolved with #53924

**Comment by jakub-g** [comment]
Proper link to electron issue: https://github.com/electron/electron/issues/2504 (but it seems no one is working on that).

As a long-time Windows user, this is a killer feature for me - all native Windows apps (including Notepad++, Sublime etc.) support this behavior. I don't use assistive technologies, but I prefer keyboard navigation to mouse due to RSI. Glad that you're working on it!
