### ISSUE TITLE
Source Control Git Over 5000+

### ISSUE THREAD

**Issue by penghan0** [Microsoft/vscode#51519]
![3](https://user-images.githubusercontent.com/29083792/41191137-5175a28a-6c2e-11e8-8d77-952c88f2deac.JPG)
As you can see 5000+ in here how to solve? Please more details!

**Comment by DJMcNab** [comment]
You appear to have created a git repository in your user folder.

To fix this, you should navigate to `c:\Users\pengham` and delete the `.git` folder. You might need to enable (✔️) `Hidden items` in the `view` tab of file explorer in order to see it.

Alternatively, you can open a command prompt window (or use the integrated terminal) and run:
```powershell
rmdir "c:\\Users\\pengham\\.git" /S /Q
```

**Comment by penghan0** [comment]
Thanks,
when I deleted .git folder then in here show these, its ok?
![1](https://user-images.githubusercontent.com/29083792/41206968-613eed5c-6d50-11e8-8b9c-a8fd78f6052c.JPG)

**Comment by DJMcNab** [comment]
Yeah, that's right. That's what's normally shown if you're not in a git repository.
