### ISSUE TITLE
1st Level Collapse command not working properly

### ISSUE THREAD

**Issue by rclai** [Microsoft/vscode#51620]
- VSCode Version: 1.24.0 (1.24.0)
- OS Version: OSX 10.13.4 (17E202)

Steps to Reproduce:

1. Cmd + K + 1

Does this issue occur when all extensions are disabled?: Yes

That command is supposed to collapse everything in the first level. This was working right before but something changed after an auto-update?

![screen shot 2018-06-11 at 11 16 33 am](https://user-images.githubusercontent.com/1316261/41240632-fcbc2db8-6d68-11e8-83f2-b8886d477c4d.png)

In addition, template literals also are not collapsed anymore:

![screen shot 2018-06-11 at 11 18 39 am](https://user-images.githubusercontent.com/1316261/41240740-36ede418-6d69-11e8-87f9-b3b0b33a01eb.png)

**Comment by RMacfarlane** [comment]
See https://github.com/Microsoft/vscode/issues/47667 for the template literal folding issue

**Comment by aeschli** [comment]
The typescript folding provider doesn't provide ranges for parameter lists that go over several lines.

**Comment by rclai** [comment]
But the code that I wrote is not typescript. Does that matter?

**Comment by mjbvz** [comment]
This is because of our switch to syntax based folding. The old behavior you are expected was because collapsing was previously based on indentation. See this section in the release notes for more info: https://code.visualstudio.com/updates/v1_24#_syntax-aware-folding-enabled-by-default-for-jsts

Related issues:
- Folding for template strings: https://github.com/Microsoft/TypeScript/issues/23382
- Folding for mult-line parameter lists: https://github.com/Microsoft/TypeScript/issues/22915
