### ISSUE TITLE
Search: arrow up/down no longer switches between input fields

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#51681]
Instead it changes the history of things I typed? I find this change break my search flow quite a bit.

**Comment by sandy081** [comment]
@bpasero This was due to the change of defaults

- Default shortcuts for History navigation in the input boxes are Up and Down arrows
- Default shortcuts for navigating among input boxes are `cmd+Up Arrow` and `cmd+Down Arrow`

Change was done because of #12645. This made all our history navigation to be consistent and use Up and Down arrows.

You can always change the behaviour back by updating the keybindings to the following commands

Search Inputs navigation commands: `search.focus.nextInputBox` and `search.focus.previousInputBox`

Input history navigation commands: `history.showPrevious` and `history.showNext`
