### ISSUE TITLE
Support TOML Syntax out of the box

### ISSUE THREAD

**Issue by tristan957** [Microsoft/vscode#51704]
I have found #41650 as a related issue, but that seems to only tackle `TOML` support in markdown files.

I am suggesting that VSCode support the `.toml` file extension. It should be very similar to the `.ini` syntax, and is something I would be willing to tackle in a PR.

**Comment by mjbvz** [comment]
Yes, we would take a PR for this. Look at the `ini` or the `yaml` extensions for examples. We pull in the grammars used in these extension from existing repos so that we don't have to maintain them in the VS Code repo. Both the `ini` or the `yaml` extensions provide examples of this in their `update-grammar` npm script

**Comment by tristan957** [comment]
Perfect. I have found: https://github.com/textmate/toml.tmbundle, and will submit a PR later today. Thanks for the tip

**Comment by mjbvz** [comment]
After further discussion with the VS Code team, we have decided to revert this addition with f2f8b7cb08d80184d1df76234b236760ae9a72f5 See that commit for an explanation of why we feel this is the correct decision for guiding users to a better toml experience and for maintaining VS Code itself
