### ISSUE TITLE
The git repository has too many active changes, only a subset of Git features will be enabled

### ISSUE THREAD

**Issue by Syab** [Microsoft/vscode#51703]
Hello, 

I've been trying to find a solution to this problem but the existing threads/ solutions have not worked for me. I've tried creating a .gitignore file (`touch .gitignore`) in the directory of the existing project I'm working on but it doesn't seem to work (`.gitignore` does not even show up after I did an `ls` in that project directory). 

I've also seen comments to remove the .git file. Does this mean to just `rm -rf usr/bin/git` ?

I'm wondering if anyone has encountered this problem and is able to help list exact steps needed to resolve this issue? Thank you!

I'm using a macOS 10.13.3. referencing to issue #41699, which didn't actually help.

**Comment by yume-chan** [comment]
1. You encounter this situation because your working folder is in a git repository.
2. If you don't think so, you might create the repository unintentionally.
3. The [`.gitignore`](https://git-scm.com/docs/gitignore) file will exclude files/folders from your git repository, and you need to specify file names/patterns in it. It's used when you are actually using git, so if 2 is true, this doesn't apply to you.
4. The `.gitignore` file is hidden because its name starts with a `.` (period), so if you want `ls` to list it, you need to append `-a` (`--all`) argument, that is, `ls -a`.
5. If 2 is true, you can find the git repository and remove it, so your working folder won't be in it anymore.
To do so, you need to find the `.git` folder which contains information about this repository (as your expect, it's also hidden), you can do it by invoking `git rev-parse --show-toplevel` in your working folder.
Suppose it prints `/Users/simon`, the `.git` folder is located in `/Users/simon/.git`, so remove it by `rm -rf /Users/simon/.git`.
