### ISSUE TITLE
In debug mode user should not get context menu and value pop-up (datatips on hover) together.

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#5181]
- VSCode Version: 1.0.0-alpha
- OS Version:Windows10

Steps to Reproduce:
1. Launch app and open any .ts project.
2. Set configuration for tasks.json, Launch.json and tsconfig,json.
3. Set the break point and start debugging.
4. Once break point hit then mouse over on a variable to get info.
5. Verify info and right click at the same position.
6. Verify app behavior.

Actual: Variable value and context info options are displaying together.
Expected: When user perform right click then pop-up to display value of the variable(datatips on mouse hover) should go away. 

![image](https://cloud.githubusercontent.com/assets/17735796/14452122/49eca8f2-0041-11e6-9ab6-9a1500dcf8d7.png)

**Comment by isidorn** [comment]
This is happening because electron 'freezes' our renderer when he is showing the context menu. As soon as the context menu is closed the renderer is 'unfrozen' and the debug hover is hiden. You can notice that even the cursor stops blinking when the context menu is shown.

Nothing we can do here and I do not find it as a big limitation.
