### ISSUE TITLE
Multiple languages specific editor settings

### ISSUE THREAD

**Issue by aartoni** [microsoft/vscode#51935]
We definitely need the ability to set those for multiple languages at once.

Something like:
```
// Once for all
"[cpp, c]":{
    "editor.formatOnSave": true
}
```

Instead of:
```
// Once for C++
"[cpp]":{
    "editor.formatOnSave": true
},

// And once for C
"[c]":{
    "editor.formatOnSave": true
}
```

**Comment by BananaWanted** [comment]
really want it! we are using something like `[json,jsonc,yaml]` which is really hard to maintain

**Comment by JBLloyd** [comment]
I would like this as well but should the logic around having a duplicate setting for the same language? Should there be a hierarchy, ie having the settings pull from the single language specification over the multiple language specifications?
E.g. get settings for javascriptreact from [javascriptreact] over [javascript, javascriptreact]?
"[javascript, javascriptreact]": {
    "editor.insertSpaces": true
},
"[javascriptreact]": {
    "editor.insertSpaces": true
}

**Comment by janosh** [comment]
Any news? This feature would be very nice to have!

**Comment by simonhaenisch** [comment]
Yup, also want this. Currently it's just a bit of a pain.

```
{
  "[yaml]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode",
  },
  "[javascript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode",
  },
  "[javascriptreact]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode",
  },
  "[typescript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode",
  },
  "[typescriptreact]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode",
  },
}
```

**Comment by JosephTLyons** [comment]
Would love this feature, tons of duplicated settings in my settings file and this feature would clean it up quite nicely and reduce copy/pasta accidents.

**Comment by jwmann** [comment]
Also adding my +1 for this 👍

**Comment by liamross** [comment]
Looks like it's "On Deck" for consideration for an upcoming release so that's good news!

**Comment by ZulwiyozaPutra** [comment]
+1

**Comment by balupton** [comment]
Please just emoji 👍 the original post at the top, that way your demand is expressed without notifying everyone who is subscribed for updates

**Comment by Hyoretsu** [comment]
Would be nice for a simple rule to not be this long
 "[javascript]": {
  "editor.codeActionsOnSave": {
   "source.fixAll.eslint": true
  }
 },
 "[javascriptreact]": {
  "editor.codeActionsOnSave": {
   "source.fixAll.eslint": true
  }
 },
 "[typescript]": {
  "editor.codeActionsOnSave": {
   "source.fixAll.eslint": true
  }
 },
 "[typescriptreact]": {
  "editor.codeActionsOnSave": {
   "source.fixAll.eslint": true
  }
 },

**Comment by gitpancake** [comment]
Gotta add my +1 for this! 🎉

**Comment by igetgames** [comment]
> I would like this as well but should the logic around having a duplicate setting for the same language? Should there be a hierarchy, ie having the settings pull from the single language specification over the multiple language specifications?
> 
> **E.g.** get settings for _javascriptreact_ from `[javascriptreact]` over `[javascript, javascriptreact]`?
> 
> ```json
> "[javascript, javascriptreact]": {
>     "editor.insertSpaces": true
> },
> "[javascriptreact]": {
>     "editor.insertSpaces": true
> }
> ```

Should the second entry in this example be treated as a duplicate object key?

**Comment by gitpancake** [comment]
@igetgames 

Rather than duplicate object key, perhaps if there are duplicate settings for the same language then this should be highlighted. So, in the code example above:

```
"[javascript, javascriptreact]": {
    "editor.insertSpaces": true
},
"[javascriptreact]": {
    "editor.insertSpaces": true
}
```

A warning message could appear along the lines of: 

[javascriptreact] has the same setting `editor.insertSpaces` configured multiple times, in: `[javascript, javascriptreact]` and `[javascriptreact]`

**Comment by Naxos84** [comment]
But only if it has an identical value.

```
"[javascript, javascriptreact, typescript, typescriptreact]": {
    "editor.insertSpaces": true
},
"[javascriptreact]": {
    "editor.insertSpaces": false
}
```

in this example I'd expect it to have a different behaviour ONLY for "javascriptreact".
So no warning in this case.

**Comment by gitpancake** [comment]
That could overwhelm a user and add un-needed complexity. A warning should appear on the key, irrespective of the value.  I think that would be a nicer user experience overall.

**Comment by MattiaMalonni** [comment]
+1

**Comment by v-kydela** [comment]
@RMacfarlane 
@alexdima 
@sandy081 

Any updates?

**Comment by sandy081** [comment]
Sorry, not yet planned.

**Comment by starikcetin** [comment]
This would be extremely useful

**Comment by shafkathullah** [comment]
Or for time being  an Error as this as an invalid config would be useful too.

**Comment by JoakimTeixeira** [comment]
This would be extremely useful! Any updates?

**Comment by CEbbinghaus** [comment]
Terrifying that this has been open since 2018 and still isn't implemented. Really hope it can be added soon to make the lives of any person having to deal with the same config for 10+ filetypes a lot easier.

👍🏼 from me

**Comment by mayanxoni** [comment]
It's been over 3 years now since this issue first opened. @sandy081 can we have some solution for this in the upcoming update please?

**Comment by dejayc** [comment]
> But only if it has an identical value.
> 
> ```
> "[javascript, javascriptreact, typescript, typescriptreact]": {
>     "editor.insertSpaces": true,
>     "editor.formatOnSave": true
> },
> "[javascriptreact]": {
>     "editor.insertSpaces": false
> }
> ```
> 
> in this example I'd expect it to have a different behaviour ONLY for "javascriptreact". So no warning in this case.

What would your expectations be for overlapping disjointed sets with different values?  In the example below, what value should `editor.insertSpaces` be for files of type `javascript`?

```json
{
    "[javascript, typescript]": {
        "editor.insertSpaces": true
    },
    "[javascript, plaintext]": {
        "editor.insertSpaces": false
    }
}
```

@Naxos84

**Comment by Keavon** [comment]
Probably the last one should overwrite previous ones.

**Comment by Naxos84** [comment]
Last one wins.
So it should be `false` @dejayc

**Comment by brunobmello25** [comment]
yeah, I agree that the best option would be to have the last one override the previous ones, while also showing a warning that there are duplicate settings.

**Comment by Szymono** [comment]
Disadvantage of not being opensource. 3 years to make so small update it's not enaugh...

**Comment by hyoretsu** [comment]
@Szymono you do realize VSCode's the open-source one right?... You can view the source code, it's under MIT license and anyone can fork/make a PR for it.

**Comment by brunobmello25** [comment]
@Szymono well you could fork it and implement this feature instead of calling developers stupid just because they couldn't attend to it yet. That's because, you know, it is open source

**Comment by CEbbinghaus** [comment]
I had a Glance at the repo and while I do not have the time to work on this at the moment I think this is a good place to start when looking to implement such a feature:
https://github.com/microsoft/vscode/blob/ca118d406d8c5fea7a31735ad6724a3e2463ba82/src/vs/workbench/services/preferences/common/preferencesModels.ts

**Comment by Anderium** [comment]
I tried to search a bit deeper into where this could be implemented so I'll leave what I found here.

A test for language specific settings in [configurationModels.test.ts](https://github.com/microsoft/vscode/blob/7c26f27/src/vs/workbench/services/configuration/test/common/configurationModels.test.ts#L74-L84) shows us that the [configurationModelParser](https://github.com/microsoft/vscode/blob/7c26f27/src/vs/platform/configuration/common/configurationModels.ts#L22) is the object that parses settings. If I understand correctly this creates an object `_raw` representing the JSON settings which is parsed into a settings tree of the form `{"editor": {"formatOnSave": false, …}, …}`. (I'm kind of unsure about this, but it seems what's being tested.)

Settings are being tested for satisfying [`OVERRIDE_PROPERTY_PATTERN`](https://github.com/microsoft/vscode/blob/7c26f27/src/vs/platform/configuration/common/configurationRegistry.ts#L462), the Regex pattern `\[.*\]`. This allows the usage of all characters, whereas the currently expected behaviour would probably be to only accept lowercase.  (I don't remember what I'm basing this on, but if I recall correctly the languages are defined only with lowercase characters.)

Right below this Regex pattern there's the function [`overrideIdentifierFromKey`](https://github.com/microsoft/vscode/blob/7c26f27/src/vs/platform/configuration/common/configurationRegistry.ts#L464-L466) which returns the language associated for the settings to override.  It does this by assuming the input is structured as `[language]`.  Even spaces are not removed from the language identifier, but adding spaces is not a problem because these do get stripped later.  Either way, this function is referenced nine times in the whole code base over 5 files. [See these results](https://github.com/microsoft/vscode/search?q=overrideIdentifierFromKey).  Most of these references do not strip away any excess spaces, however, two do: [toOverrides](https://github.com/microsoft/vscode/blob/ee1655a82ebdfd38bf8792088a6602c69f7bbd94/src/vs/platform/configuration/common/configuration.ts#L228) and [DefaultConfigurationModel](https://github.com/microsoft/vscode/blob/e25d82010a0a5260ced20429061dfc55068865cd/src/vs/platform/configuration/common/configurationModels.ts#L217).  I'm thinking all of the cases referencing the function will have to be updated to accommodate specifying multiple languages, but perhaps a start can be made at the functions specifically trimming extra whitespace.

I've also thought lightly on how best to store these settings.  I think storing them for each language individually is okay.  This is what we're doing without this feature anyway, and other methods would likely require more complicated requests for settings than how it works now.  Those would likely not only slow down when multiple languages are defined, but always make loading the settings slower.

<details>
<summary>
Here I copy some of the behaviour we want from above so it's easier to find:
</summary>

**Doubly configured with same value:**

> ```json
> "[javascript, javascriptreact]": {
>     "editor.insertSpaces": true
> },
> "[javascriptreact]": {
>     "editor.insertSpaces": true
> }
> ```

Could be accepted or give a warning message along the lines of:

> The setting `editor.insertSpaces` is configured multiple times, in: `[javascript, javascriptreact]` and `[javascriptreact]`

**Doubly configured with different value:**

> ```json
> "[javascript, javascriptreact, typescript, typescriptreact]": {
>     "editor.insertSpaces": true,
>     "editor.formatOnSave": true
> },
> "[javascriptreact]": {
>     "editor.insertSpaces": false
> }
> ```

Should be accepted and use `"editor.insertSpaces": false` for `javascriptreact`.

**Doubly configured in disjoint sets (different value):**

> ```json
> {
>     "[javascript, typescript]": {
>         "editor.insertSpaces": true
>     },
>     "[javascript, plaintext]": {
>         "editor.insertSpaces": false
>     }
> }
> ```

Should be accepted and use `"editor.insertSpaces": false` for `javascript`.  The last case should be the one that gets used.

**Doubly configured in disjoint sets (same value):**

> ```json
> {
>     "[javascript, typescript]": {
>         "editor.insertSpaces": true
>     },
>     "[javascript, plaintext]": {
>         "editor.insertSpaces": true
>     }
> }
> ```

Should be accepted and use `"editor.insertSpaces": true` for all three languages.  The warning suggested for multiple configurations should probably not be issued because the setting wasn't defined for `plaintext` before.  This might mean it's difficult to determine when to give such a warning or we can accept that the warning is given, letting users choose to ignore it.  Since we'll take the last override, it won't matter to us in the end.
</details>

**Comment by sandy081** [comment]
Implemented this feature and you can configure editor settings for multiple languages with single key as follows:

```json
"[cpp][c]":{
    "editor.formatOnSave": true
}
```

We already use this syntax in the setting `workbench.colorCustomizations` eg.,

```
"workbench.colorCustomizations": {
		"[GitHub Sharp][GitHub Sharp Dark]": {
                       "editorPane.background": "#d6d0d01a",
			"sideBarSectionHeader.border": "#D3D3D3",
                 }
}
```

Hence, went with this syntax also here to define multiple languages.

**Comment by CEbbinghaus** [comment]
@sandy081 How come you decided to separate the languages into separate brackets?
> "[cpp][c]":{
    "editor.formatOnSave": true
}

The original issue called for it to be a comma-separated list inside the brackets and it's a lot more semantic with less verbosity. If you want to overload 20 languages that you have to match up 20 brackets for and if one of them is malformed it's likely an invalid key. A single bracket is plenty sufficient and reduces the clutter from the additional characters:

```json
"[javascript][typescript][json][html][jsx-tags][yaml][editorconfig][dotenv][astro][javascriptreact]":
{
    "editor.formatOnSave": true
}
```
```json
"[javascript, typescript, json, html, jsx-tags, yaml, editorconfig, dotenv, astro, javascriptreact]":
{
    "editor.formatOnSave": true
}
```

**Comment by janosh** [comment]
While we're at it, why not be as forgiving as possible and allow no brackets at all
```json
"javascript, typescript, json, html, jsx-tags, yaml, editorconfig, dotenv, astro, javascriptreact":
```
as well as no spaces
```json
"javascript,typescript,json,html,jsx-tags,yaml,editorconfig,dotenv,astro,javascriptreact":
```

**Comment by sandy081** [comment]
@CEbbinghaus It was decided by the team - we already use the same syntax in `workbench.colorCustomizations` setting and this makes it consistent.

**Comment by MohamadKh75** [comment]
Hey

When can we use it?

It's not supported in:

```
Version: 1.62.3
Commit: ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
Date: 2021-11-17T08:00:36.721Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.4.0-90-generic
```

**Comment by sandy081** [comment]
With next release - 1.63.0. You can also try insiders channel to use it now - http://code.visualstudio.com/insiders/
