### ISSUE TITLE
Debug Console ignores logging of empty lines

### ISSUE THREAD

**Issue by kayahr** [Microsoft/vscode#52028]
- VSCode Version: 1.24.1
- OS Version: Debian GNU/Linux 9.4

Steps to Reproduce:

1. Write a small Node application like this:

```typescript
console.log("Line 1");
console.log();
console.log("Line 3");
console.log("");
console.log("Line 5");
console.log(" ");
console.log("Line 7");
```

2.Launch it in the terminal and see the correct output:

![console](https://user-images.githubusercontent.com/580493/41466678-916cb710-70a3-11e8-8adc-db9980a282a3.png)

3. Launch it in the debugger and see the wrong output:

![debug](https://user-images.githubusercontent.com/580493/41466726-c1cf0d9a-70a3-11e8-9af1-2d302a5cd38a.png)

So when running in the debugger then `console.log()` without parameters and `console.log("")` with an empty string parameter does not generate an empty output line. But logging a single space character works.

Does this issue occur when all extensions are disabled?: Yes

This problem is similar to #24308 I reported last year. In this issue I reported that empty lines where *sometimes* ignored. Now they are *always* ignored. So looks like the bug wasn't fixed properly.

**Comment by isidorn** [comment]
The issue here is that I am not getting an output event from the debug adapter for those empty outputs -> forwarind first to @roblourens to investigate
There might be something that we are doing wrong on the ui end on top of that, but this is the initial issue, so it would be great if @roblourens could check on the adapter side. Thanks

**Comment by roblourens** [comment]
Indeed an adapter bug
