### ISSUE TITLE
Application behaving weirdly and keep adding multiple files with the same name and showing up ESLint error.

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#5207]
- VSCode Version: 1.0.0-alpha
- OS Version: Windows10

I am trying to debug .js file with node debugger. After couple of execution, I observed that application is adding multiple version of the app.js (I can see in the command pallete there are 3 app.js listed as below).
![image](https://cloud.githubusercontent.com/assets/17735796/14478481/fcae5402-00ca-11e6-9bf1-3c62e8e6f738.png)

When I open chrome developer tool to identify issue I could see so many errors listed related to app.js
![image](https://cloud.githubusercontent.com/assets/17735796/14478528/7983a8d8-00cb-11e6-8d3a-915ab56ff0de.png)

Find below ESLint error screenshot: I am not certain from where this file (app.js) is referred by eslint as the file I am referring in my project is updated properly and there is no error on it. I verified it manually as well and the changes I made in my first execution was already reverted (LN 7: aasadasds update as ss dd dd  sd)
![image](https://cloud.githubusercontent.com/assets/17735796/14478768/833f0870-00cd-11e6-9b07-3937a85a7603.png)

PFA error log for more details:
[ErrorLog.zip](https://github.com/Microsoft/vscode/files/216142/ErrorLog.zip)

Note: I am able to debug my code without any problem. I observed this weird behavior when I saw a eslint error in the status bar.

**Comment by isidorn** [comment]
Ok there are a couple of issues here which resulted in the unhappy experience
1. You have cordova extension installed which overrideds some of the debugger actions
2. You were trying to debug without fully setting up `program` in your `launch.json`
3. Somehow your app.js content on disk is newer and vscode was unable to save it (might be due to the cordove extension)
4. If there is an invalid eslint error I suggest to create a new concise issue which only address that problem.

Closing this as I see no action that can be done here.
