### ISSUE TITLE
vsccode did't update the local display panel

### ISSUE THREAD

**Issue by yuanzhangliu** [Microsoft/vscode#52199]
- VSCode Version: VSCode-darwin-stable（I download 2018-6-17）
- OS Version: Mac OS 10.13.5 (17F77)

Steps to Reproduce:

I can't make sure wether is vscode bug or git bug

my GitHub repos is  the latest source code

when I exec "git pull ",it did't update my vscode panel

here is pics

<img width="1075" alt="2018-06-18 6 47 39" src="https://user-images.githubusercontent.com/16571692/41539812-94d84190-72c3-11e8-95de-c2753d318679.png">

add some detail:
when I add some new words on it then command +s ;here is some alert

<img width="571" alt="2018-06-18 8 04 34" src="https://user-images.githubusercontent.com/16571692/41544839-9859a858-72ce-11e8-8686-8a56af774f14.png">

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by bpasero** [comment]
VS Code is using different file watching strategies depending on your OS and your setup. 

**First thing to check:**
* [ ] I verified that the issue still reproduces in our insiders version (https://code.visualstudio.com/insiders/)
* [ ] I verified that this issue is happening outside of a `node_modules` folder. Our file watcher ignores this folder!

**To find out more about this issue, please first answer this:**
* [ ] What OS are you on
* [ ] Does this happen from an empty workspace, a single-folder workspace or a multi-root workspace?
* [ ] Do you have `files.useExperimentalFileWatcher: true` configured in settings?
* [ ] What is your configured `files.watcherExclude` setting?

**Then please answer the following depending on your setup:**
* [ ] It reproduces with any folder or workspace you open
* [ ] The files/folders you open are on your local disk and not on a network share nor a UNC drive
* [ ] The files/folders you open are not behind a symbolic link
* [ ] The folder(s) opened use the exact same casing as they are on disk
* [ ] It reproduces when I make a change to the file from another VS Code window (either from the editor or the file explorer)

**Then please attach the output of our development console**
* run `code --verbose` from the command line
* perform the action that causes you to not see the file change in VS Code
* attach the output from the console (`Help` > `Toggle Developer Tools` > `Console`)

Thanks for taking the time to fill out this questionnaire.

**Comment by yuanzhangliu** [comment]
first , vscode and git extension  work well, it's my misunderstanding about git;(I am just new fish to git;)

I am so sorry to post this issue here,  vscode is simple and useful and powerful, 

thanks for your attention for this issue
