### ISSUE TITLE
Error during update: ReadProcessMemory

### ISSUE THREAD

**Issue by matheussouza9** [microsoft/vscode#52206]
- OS Version: Windows 7 Professional 64-bit Service Pack 1
[vscode-inno-updater.log](https://github.com/Microsoft/vscode/files/2111693/vscode-inno-updater.log)

**Comment by tgrandgent** [comment]
I encountered the same problem trying to update 1.26.0 to 1.26.1, also on Windows 7 Professional 64-bit Service Pack 1.  
[vscode-inno-updater.log](https://github.com/Microsoft/vscode/files/2297207/vscode-inno-updater.log)

**Comment by abidingotter** [comment]
I am seeing the same issue.  I believe the problem is (at least in my case) is that another user is logged into the same machine and is running VS Code.  We have both installed into our user AppData folders, so it shouldn't be trying to kill his running instance (but it looks like it does attempt to!)
