### ISSUE TITLE
Disabled backup service in extension tests can cause issues

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#52212]
See https://github.com/Microsoft/vscode/blob/c93d5e7d9200d4839bd8718c39b577568ab3d78a/extensions/vscode-api-tests/src/singlefolder-tests/workspace.test.ts#L556. The test fails because the document just contains `AFTER` not `AFTERBEFORE`

**Comment by bpasero** [comment]
@jrieken this is because in order to preserve the contents of a model when renaming, I go through our backup service which happens to be disabled when running in a test environment. Once I remove this check for extensions, the test runs green:

https://github.com/Microsoft/vscode/blob/8be8f654687341db407086c7e277d80b7055e12a/src/vs/code/electron-main/windows.ts#L1141-L1149

**Comment by jrieken** [comment]
@bpasero Is that backupPath something we can simply set to a temp-directory when running like this? Now, almost every extension test I wrote for the workspace edit is partially commented out which doesn't increase my confidence ;-)

**Comment by bpasero** [comment]
@jrieken yeah I can look into providing a test-implementation that just operates in memory maybe.

**Comment by bpasero** [comment]
There is now an [`InMemoryBackupFileService`](https://github.com/Microsoft/vscode/blob/0113b40fd1dab5f71eebbcee5e25f55b5c779059/src/vs/workbench/services/backup/node/backupFileService.ts#L248) whenever there is no `backupPath` configured.
