### ISSUE TITLE
[Test item] Try using the new diagnostics tag API

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#52218]
Test for #51104

Complexity: 3

- [x] Any OS @chrmarti 
- [x] Any OS @sandy081 
 
**Summary**
#51104 introduces a new `tags` field on diagnostics. This field is used to add additional metadata  about the diagnostic. We currently use it to mark unnecessary code so that it can be rendered as faded out.

**Testing**
Try using the new tags api extension that contributes diagnostics. Things to try:

- Make sure the faded out rendering plays nicely with all diagnostic severities. The fading out should disable the `...` on suggestion diagnostics but not disable squiggles on errors and warnings. 
- Make sure overlapping diagnostics are rendered correctly. 
- Make sure you can control the fading out level with `"editorUnnecessaryCode.opacity"`  and `"editorUnnecessaryCode.border"` (for high contrast) as described in the api documentation

**Comment by benjaminjackman** [comment]
Is there any way to still use the previous behavior of graying out the code instead of fading it and keeping the syntax color? I  understand from #51104 that a lot of folks like this version. However having tried it out in insiders, I find the previous grayed out version to be much easier to scan for. (I tried the borders setting and it was too noisy).

**Comment by mjbvz** [comment]
No, no current plans for an option to revert to the old behavior. The new effect is more subtile but does retain useful coloring information in the faded out spans
