### ISSUE TITLE
[html] don't add spaces when comming

### ISSUE THREAD

**Issue by r0bfr** [microsoft/vscode#52234]
**Steps to reproduce:**

1. Open a vcxproj in VS Code.
2. Type the word "Foo" at the start of a new line
3. Do Ctrl+K,C to comment the line

**ER:**
`<!--Foo-->`
**AR:**
`<!-- Foo -->`

When VSCode comments a selected line of text, it adds a blank space to the left and right side of the selection before commenting it.  Visual Studio does not do this.  The two apps should behave consistently, but don't.

In this case, Visual Studio behaves correctly.  VSCode should not be adding extra spaces around the selection before commenting it.

**Comment by aeschli** [comment]
There's no requirement that VS and VS Code must behave the same.

In VS code we chose to add spaces as this recommended by [some styleguides](https://gist.github.com/ryansechrest/8693303#1-single-line-comments). But guess in the end it's a matter of personal taste.

**Comment by aeschli** [comment]
I keep the issue open to see if other users feel the same. Please add votes.

**Comment by aeschli** [comment]
Ideally, we would allow all language configuration settings to be redefined in the user settings

**Comment by aeschli** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.
If you disagree and feel that this issue is crucial: We're happy to listen and to reconsider.
Maybe you want to give it a try yourself and provide the feature through an extension or a PR: We're happy to give advise and get you started.
Thanks for your understanding. Thanks for helping and happy coding!
