### ISSUE TITLE
WorkspaceEdit should have an option to adjust whitespaces (like snippets)

### ISSUE THREAD

**Issue by yaohaizh** [microsoft/vscode#52272]
CodeAction and CompletionItems result doesn't format according to current selected opened file. 
Code snippets (like ctor) are indented with tabs, but vscode fixes the indentation on-the-fly, according to its preferences.  And the codeaction doesn't pass the current editor's indentation setting when invoke codeaction/completions.

Snippet/CodeAction/Completion should have similar behavior.

**Comment by jrieken** [comment]
We could do this but only when the code action use an edit, not a command. @yaohaizh Can you provide a concrete sample please.

**Comment by MeikTranel** [comment]
@jrieken Given a workspace with everything set to indent using 2 spaces:

```json
{
    "editor.insertSpaces": true,
    "editor.tabSize": 2
}
```

When applying a code action like `ctor` in a well-formatted (as in formatted according to the given settings) document, the inserted code block is not automatically formatted to the standards of the document. In my particular example, vscode-java was producing tab-indented snippets.

I assume what @yaohaizh meant was that as an API consumer he wants to read the language agnostic formatting settings like `editor.tabSize` to produce compliant strings beforehand instead of relying on forced formatting to happen after the fact. Is that a correct assessment, @yaohaizh ?

**Comment by yaohaizh** [comment]
Yes, we use the Command for codeaction, but not edit. 

I have uploaded a java sample project for this. 
Repro: 
1.  Install VSCode Java extension
2. Open the project, waiting for the language server to be ready with installation of maven dependencies.
3.  Open the Inherit.java file
4.   Choose the Inherit class name, trigger the codeaction for "Add unimplemented method" and invoke it, the generated is tab based. 
[vscode-java-demo.zip](https://github.com/Microsoft/vscode/files/2117943/vscode-java-demo.zip)

**Comment by yaohaizh** [comment]
The Command object of LSP for CodeAction result.  

```javascript
Command

Represents a reference to a command. Provides a title which will be used to represent a command in the UI. Commands are identified by a string identifier. The protocol currently doesn’t specify a set of well-known commands. So executing a command requires some tool extension code.

interface Command {
	/**
	 * Title of the command, like `save`.
	 */
	title: string;
	/**
	 * The identifier of the actual command handler.
	 */
	command: string;
	/**
	 * Arguments that the command handler should be
	 * invoked with.
	 */
	arguments?: any[];
}
```


And this is the java implementation: 
https://github.com/eclipse/lsp4j/blob/83ae40a1d4b2b7076a8bb8ea28a953cf1fb1ca84/org.eclipse.lsp4j/src/main/xtend-gen/org/eclipse/lsp4j/Command.java#L44

We put the WorkspaceEdit object in the arguments array.

**Comment by jrieken** [comment]
> We put the WorkspaceEdit object in the arguments array.

Ok, so the WorkspaceEdit describes the textual changes you are making. I will update the title accordingly.

**Comment by jdneo** [comment]
Hi @jrieken, 

May I ask is there any further plan about this issue?
