### ISSUE TITLE
Clicking the + button to add a watch expression re-evaluates all expressions, which delays showing the input box

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#52317]
When adding a new watch expression with the `+` button; an `evaluateRequest` is sent for all existing expressions and the input box for the new expression doesn't appear until all of them complete.

This makes it feel sluggish if the evaluations are slow (in my case, I have a bug so I put a 3s timeout on them; and I see a 3s delay whenever I try to add a new expression because of one of the existing expressions timing out). It also seems unnecessary - at this point it's just showing an empty input box so there's no need to re-evaluate everything (the same actually goes for any edits here, it seems to re-evaluate them all).

On a slightly greater tangent, the Watch window seems to generally behave really badly if there is an evaluateRequest that hasn't completed. For ex. if you make an evaluate request take 10 seconds; for that duration the Watch window just because really strangely (the enabled/disable state of the add/remove buttons is confusing, and the text labels seem to revert when you edit them).

**Comment by isidorn** [comment]
Yes I acknowledge this limitation.
This is just the limiation of using the tree, we can not refresh parts of the tree but the whole tree has to be refreshed whenever a new element is added (input box).
Because the whole tree is refreshed each element has to be asked if it has children thus it has to be evaluated.

No immediate plans to fix this -> backlog

**Comment by weinand** [comment]
Let's go to the bottom of this limitation:
What is the reason that the tree used for watches has a limitation that other trees in VS Code don't have?

**Comment by DanTup** [comment]
I think there are two issues, and it's really the combination of them that makes this bad:

1. The expressions are being re-evaluated on every change
2. While an expression evaluation is in-flight, the behaviour of the view is erratic (eg. if you try editing an expression, it may revert when you press enter, and the add/remove buttons seem to enable/disable unexpectedly)

I think fixing just one of these would be a big improvement (for eg., if a single expression evaluation is in-flight, why can't I still add additional expressions, or delete some, or edit some others?).

**Comment by isidorn** [comment]
@weinand all trees in vscode have this limitation
@DanTup I agree these are two seperate issues, please create a new issues for the 2. Thanks

**Comment by weinand** [comment]
@isidorn could you please add a link to the tree limitation issue.

**Comment by isidorn** [comment]
@weinand as far as I know there is no issue, this is just how the tree is designed
Though @joaomoreno would know better if there is an issue tracking that I can not refresh parts of the tree. E.g if I am adding a top level element everything has to be refreshed

**Comment by weinand** [comment]
But refreshing everything in the tree does not necessarily mean that all watch expressions have to be evaluated again, right?
You could just use the old evaluation result for all existing tree nodes and only evaluate the new node.

**Comment by isidorn** [comment]
Yes, that is correct.

**Comment by weinand** [comment]
So we should try to limit the watch evaluations based on usage patterns, e.g.
- add: only evaluate new watch
- remove: no evaluate
- stopped event: evaluate all

This might require that the tree refresh is decoupled from the watch evaluations so that we have better control when we do the evaluations.

Probably the same applies to the variables tree too: If I understand the tree correctly we always reload values from the DA when we refresh the tree (because that is really needed on a stopped event). But if we would implement the feature that a DA can send notification when a variable value changes, we would need a more fine-grained refresh approach (where only a specific tree node needs to reload its value).

**Comment by DanTup** [comment]
Ok, I've opened #52423 for the strange issues while the requests are in-flight. This issue is therefore just about re-evaluating the requests on every edit (sending them to the DA).
