### ISSUE TITLE
Cannot change spacing level in auto-detect mode

### ISSUE THREAD

**Issue by perlun** [microsoft/vscode#52321]
Issue Type: <b>Feature Request</b>

When the `editor.detectIndentation` setting is set to `true`, VSCode will detect the level of indentation (2 spaces, 4 spaces, etc.) which is fine and useful.

When `editor.detectIndentation` is set to `false`, the global/file-type-specific setting will be used instead for _all_ files. If you load a file, you can easily reformat it to use the "current expected" format for the file type:

```javascript
{
    // ...
    "editor.tabSize": 4,
    "[ruby]": {
        "editor.tabSize": 2
    }
    // ...
}
```

However - what if you want to use `detectIndentation` mode, but sometimes re-indent a file (e.g. go from 2 spaces to 4 spaces or vice versa)? The current approach makes it impossible; neither one of these modes will let you "change" the `tabSize` for a file after it's been loaded. You have to reformat the file manually, or change the `editor.detectIndentation` setting.

IMHO this could be implemented as an addition to the indent dropdown that gets shown when you click here in the status bar:

<img width="120" alt="image" src="https://user-images.githubusercontent.com/630613/41593398-913b87bc-73c8-11e8-98d3-0d41294732e5.png">

<img width="740" alt="image" src="https://user-images.githubusercontent.com/630613/41593377-7eebaf7e-73c8-11e8-92ad-c1804760f4f2.png">

"Indent Using Spaces" would be replaced by "Indent Using 4 Spaces" (in my current setup), but "Indent Using 2 Spaces" and "Indent Using 8 Spaces" would also be available as options in this list.

----

(I would guess that 2 spaces and 4 spaces are by far the most common modes being used, but: I don't have any stats backing this, so this is just a hunch rather than something scientific.)

VS Code version: Code - Insiders 1.25.0-insider (11b0f3a40be055e02b721abbb93cb0012818f99e, 2018-06-14T05:11:13.121Z)
OS version: Darwin x64 17.5.0

**Comment by perlun** [comment]
Similar to #17802 - @OliverJAsh, was this about the same how you envisioned this to work?

**Comment by alvinkiett84** [comment]
Get Outlook for Android







On Tue, Jun 19, 2018 at 6:01 AM -0500, "Per Lundberg" <notifications@github.com> wrote:












Issue Type: Feature Request


When the editor.detectIndentation setting is set to true, VSCode will detect the level of indentation (2 spaces, 4 spaces, etc.) which is fine and useful.


When editor.detectIndentation is set to false, the global/file-type-specific setting will be used instead for all files. If you load a file, you can easily reformat it to use the "current expected" format for the file type:
{
    // ...
    "editor.tabSize": 4,
    "[ruby]": {
        "editor.tabSize": 2
    }
    // ...
}


However - what if you want to use detectIndentation mode, but sometimes re-indent a file (e.g. go from 2 spaces to 4 spaces or vice versa)? The current approach makes it impossible; neither one of these modes will let you "change" the tabSize for a file after it's been loaded. You have to reformat the file manually, or change the editor.detectIndentation setting.


IMHO this could be implemented as an addition to the indent dropdown that gets shown when you click here in the status bar:








"Indent Using Spaces" would be replaced by "Indent Using 4 Spaces" (in my current setup), but "Indent Using 2 Spaces" and "Indent Using 8 Spaces" would also be available as options in this list.



(I would guess that 2 spaces and 4 spaces are by far the most common modes being used, but: I don't have any stats backing this, so this is just a hunch rather than something scientific.)


VS Code version: Code - Insiders 1.25.0-insider (11b0f3a, 2018-06-14T05:11:13.121Z)

OS version: Darwin x64 17.5.0

**Comment by alvinkiett84** [comment]
Google Photos

Alvin Roy Kiett shared a photo with you

View photos here:  
https://photos.google.com/share/AF1QipNaAmpSAPd9WVtVGyB5PK7ZKYTUmXMiC8rUSgvVZpNn88OCefRlztNKqgXWRWgeCA?key=UHpmRWdrT1NuRV9IckpTaTVoNmM1V0k4UmM4ODBn

You received this mail because Alvin Roy Kiett shared these photos with  
you. If you no longer wish to receive email notifications of shared photos,  
unsubscribe here:  
https://notifications.google.com/unsubscribe/AJ7SsMnyyKGw2o61cj0TcbuB7-ob77EiDAGsAeLpXUyjsHZehOP4GUD2Pks-HQ8YNHEUyZMhfqry-tCh07338woOA_3mTw8TiH6TSHRHV4GybNTC3qQEzJHEt7Gnyc9_iqEUB4EtG3WR_29MXvkx0FaTOx6d6GB2K3UVpMZrzWbIg17C-bunrg_eMtGv2HLB6WwP022mlEhHIkkshzxyrcnf1CpoT53DN1UszUYsOf2k1vvVZvOJ3Q_kXV6HA3lFqM0-8a6yqz0u

Get Google Photos (https://google.com/photos)

Google LLC, 1600 Amphitheatre Pkwy, Mountain View, CA 94043 USA
