### ISSUE TITLE
Reference completion produces bad code

### ISSUE THREAD

**Issue by mnpenner** [Microsoft/vscode#5237]
- VSCode Version: 0.10.11 
- OS Version: Win10

Steps to Reproduce:
1.  Start typing `/// <referen`
2.  When the completion suggestion pops up, press enter

Expected output is `/// <reference path="" />` but you end up with `/// </// <reference path="" />`.

![](http://i.imgur.com/P7HXh6V.gif)

**Comment by egamma** [comment]
What you are invoking is not reference completion, but you are invoking the 'reference' snippet.  So this is the expected behaviour. 

What you are expecting is tag completion inside /// reference. I've changed the title and mark this as a feature request.

This could actually be done in an extension. FYI @jrieken

**Comment by jrieken** [comment]
I reward anyone with much  🍻 for writing such an extension.

**Comment by mjbvz** [comment]
Closing as we have not seen follow up interest in this issue. `<reference>` comments are also no longer encouraged or necessary for working with js/ts
