### ISSUE TITLE
Make the centered view margin color customizable

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#52434]
@aeschli I want to make the centered lauout margin background color customizable. Can you please help me with the name? Here's my proposal:
`centeredLayout.marginBackground`

fyi @joaomoreno

**Comment by bpasero** [comment]
@isidorn I would probably keep it simply and go with something like `centeredLayout.background` and we only show this color in the margin area because the elements within the widget have their own background colors.

If we want to make it easier for theme authors to correlate this with the editor area, it maybe should be `editorCenteredLayout.background`?

Other colors to get inspiration from: https://github.com/Microsoft/vscode/blob/b7e2e55f6df49bdee4805787aa55d6b1fde08466/src/vs/workbench/common/theme.ts#L120

**Comment by aeschli** [comment]
@isidorn @bpasero What about `editorPane.background`?

**Comment by isidorn** [comment]
I can go with editorPane.background and we can rename next week
