### ISSUE TITLE
re-creating a file updates the text editor model too late

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#52447]
* comment out the last line and then run this workspace-edit test: https://github.com/Microsoft/vscode/blob/bac2a593221e7c1141575cc4d481fe27a07d9c89/extensions/vscode-api-tests/src/singlefolder-tests/workspace.test.ts#L670
* it creates a file with overriding it 
* this will call `IFileService#createFile` and override the content with `''`
* 🐛 the text model isn't updated when the promise of `createFile` resolves, it seems the update happens async via the file editor tracker. I think `FileOperation.CREATE` event deserve special treatment.

**Comment by bpasero** [comment]
Instead of relying on `FileOperation.CREATE` (which is a bit low level) we could simply have a `ITextFileService#create()` method to be in sync with the delete and move operations we already have and that method takes care of existing models properly (possibly destroying them as indicated in https://github.com/Microsoft/vscode/issues/52414).
