### ISSUE TITLE
importModuleSpecifier value of "auto" is not choosing shortest path, is acting as if it was "relative"

### ISSUE THREAD

**Issue by ohjames** [microsoft/vscode#52485]
- VSCode Version: 1.24.1
- OS Version: archlinux

Steps to Reproduce:

1. Set   `"typescript.preferences.importModuleSpecifier": "auto"` in settings.
2. auto-import a symbol from the file `src/app/util/blah.ts` when editing the file `src/app/d1/d2/d3/file.ts` when `./src` is the `baseUrl` in `tsconfig.json`.
3. the auto-import starts with `../../../util` instead of `app/util` even though `app` is shorter than `../../..`.

I would expect the import to start with `app`, as it does when the option is set to `non-relative` instead of `auto`.

Does this issue occur when all extensions are disabled?: Yes

**Comment by ohjames** [comment]
My colleague @ukcrpb6 is also experiencing this issue running Mac OS rather than Linux.

**Comment by marknelissen** [comment]
I think it is the non-relative path behaviour that is broken, which causes this issue. I came to this conclusion, since as a test to try to fix the all-relative problem, I set both javascript.preferences.importModuleSpecifier and typescript.preferences.importModuleSpecifier to non-relative explicitely in my user settings, and the editor continues to only use relative paths.

This is on Windows, so I think the OS is not relevant for this issue.

**Comment by marknelissen** [comment]
Some additional information: this seems to only/mainly affect dependencies where the type definition is imported from DefinitelyTyped. As long as the module is already present in the import statements, the new element is correctly added to the existing import statement. If it is an import from a module that is not yet present, a relative path is generated to the `@types/...` dependency, instead of the actual dependency.

**Comment by mjbvz** [comment]
For verification: this was a documentation only change. Just check that the new description of `"auto"` makes sense and matches the behavior you see in the editor
