### ISSUE TITLE
Extremely annoying auto completion

### ISSUE THREAD

**Issue by prd0000** [Microsoft/vscode#52500]
Ok.. this isn't fun and downright a stupid feature. 
![image](https://user-images.githubusercontent.com/4971305/41676181-f7aa22ac-74ee-11e8-8411-234cd653d591.png)

![image](https://user-images.githubusercontent.com/4971305/41676271-2905a6e6-74ef-11e8-9893-3a5477aa6249.png)

Why do VScode MUST match my typed character individually instead off my partial word? And putting a snippet on top of it. When I press tab to put colon, it will PUT that snippet there, so I HAVE to retype everything ALL OVER AGAIN, and remember to press escape instead of tab. I want snippet completion, but I don't want fuzzy matches on MY snippet, much less unknown intrusive snippets. If I want my snippet, I will type my own prefix, not some random characters mumble jumble.

This is VERY frustrating, anti-productive, and I literally wanted to smash my screen for this.

**Comment by Cirieno** [comment]
Seconded (without the damage).  I've never understood why the Intellisense/Snippet/Emmet/??? engine looks for each letter typed instead of a discrete unit of letters, and it is frustrating noise.

![issue](https://user-images.githubusercontent.com/37182505/41682831-c4554102-74d0-11e8-944d-e583a890405f.png)

**Comment by Cirieno** [comment]
@prd0000 Not that this fixes the issue, but as an aside: there is a user setting "editor.snippetSuggestions" which allows you to specify where in the intellisense list snippets show <top/bottom/inline/none>

**Comment by prd0000** [comment]
Already set snippet to bottom. Why does it appear on top?

**Comment by jrieken** [comment]
@prd0000 Very interesting and something that should not happen. Weirdly enough, I cannot reproduce here... This is how it look on my machine and that's also how it should work

![jun-21-2018 09-50-26](https://user-images.githubusercontent.com/1794099/41705249-b896295e-7538-11e8-8ec9-74d6189df9c6.gif)

Can you attach source/file in which this happens? Is that TypeScript or JavaScript? What version of VS Code does that happen in? Can you attach your settings file?

**Comment by Cirieno** [comment]
@jrieken  It is happening even in your example image! -- intellisense is coming up with "private method" which does not relate to [prev] as typed.  Also the phrase "private method" contains the letters [p,r,v,e] so it doesn't even look up letters in the correct order as typed.

**Comment by jrieken** [comment]
> It is happening even in your example image! -- intellisense is coming up with "private method" which does not relate to [prev] as typed.

You and I aren't on the same page here. What the gif shows is the designed behaviour, IntelliSense tries a few permutations because it's common a mistake to swap neighbournig characters. Check the second paragraph in https://code.visualstudio.com/updates/v1_19#_smarter-intellisense. If you don't like this, then please file a separate issue. The issue here is sorting, the match on `private method` should be weaker then the perfect match on `prev`. Because of that `prev` should be sorted on top and it should be the selected by default.

**Comment by Cirieno** [comment]
@jrieken I think then two different issues are alluded to in the original comment.  I commented on the first (fuzzy intellisense is annoying and / or can lead to inserted typos that need deleting), and you have commented on the second (why isn't the stronger match at the top of the list). 

So I assumed that this issue is the nature of fuzzy intellisense to try and be over-helpful (explained by your link) -- and this fuzziness should be optional.

**Comment by prd0000** [comment]
This is the configuration file:

{
    "git.ignoreMissingGitWarning": true,
    "editor.snippetSuggestions": "inline",
    "editor.tabCompletion": true,
    "typescript.useCodeSnippetsOnMethodSuggest": false,
    "typescript.updateImportsOnFileMove.enabled": "always",
    "emmet.excludeLanguages": [
        "javascript",
        "typescript",
        "markdown"
    ],
    "emmet.showExpandedAbbreviation": "inMarkupAndStylesheetFilesOnly",
    "emmet.optimizeStylesheetParsing": false,
    "window.zoomLevel": 0
}

Version 1.24.1
Commit 24f62626b222e9a8313213fb64b10d741a326288
Date 2018-06-13T17:51:32.889Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by jrieken** [comment]
> But really, you SHOULD NOT, and MUST NOT use fuzzy search on completion. I haven't seen any single IDE, Atom, Eclipse, Netbeans, or anything that use fuzzy search because it could interfere with our work

Look at Sublime Text. 

> Also, I don't think anyone care to press down arrow to pick anything in that list. It takes too much time and work than to type the next letter or the correct thing. 

Yeah, nobody wants that and that's why we work hard to ensure the best match is placed on top. Before you throw another sample at me, can you answer my questions regarding your [initial comment](https://github.com/Microsoft/vscode/issues/52500#issue-334192700). With what value of `editor.snippetSuggestions` did that happen?

> And when I put a "space" there, the word "prev" disappeared from suggestions, and I left only with private. Shouldn't it just disappeared along with my space? Or is that VSCode trying to outsmart me again?

The text left of your cursor is matched against each suggestion. In that sample it is `prev<space>` and I don't see a space in `prev<end>` but one in `private<space>method<end>`. That's why there is only one suggestion left.

> And if you are asking, I am complaining on BOTH.

https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests

**Comment by prd0000** [comment]
When it happened, it was set on top. But I lost my snippet when I set to inline or bottom. 

Well, just remove that fuzzy search, or put an option to turn it off. That the source of all problem, both completion noise and unrelated items on top, including snippets.

**Comment by harry-sm** [comment]
This is the exact reason why I don't install snippet packs.

**Comment by jrieken** [comment]
> ...also missing snippet prefix. I guess intellisense was trying to be so smart and correct that @ prefix? 

No, my guess is that is: https://github.com/Microsoft/vscode/issues/37166. Assuming this is [JavaScript/Typescript](https://github.com/Microsoft/vscode/issues/52500#issuecomment-399009909) the issue is that TypeScript registers `@` as completion trigger character and that this excludes snippets.

**Comment by jrieken** [comment]
> @ as completion trigger character and that this excludes snippets.

fyi - I have pushed a [change](https://github.com/Microsoft/vscode/commit/81f8c8bfb2644dfc816e991c00eca784a04e3210) to ensure snippets that start with a completion character show

**Comment by jrieken** [comment]
I have extracted a feature request about having a setting to disable graceful matching to this issue https://github.com/Microsoft/vscode/issues/52789. Given that issue and the change mentioned above resolves this item.

**Comment by lazarillo** [comment]
I am glad that @jrieken has opened the issue, that's great!  I was having the same frustrations as @prd0000 and [asked at SO](https://stackoverflow.com/questions/50959592/how-to-make-vs-codes-auto-complete-more-strict) in hopes that I simply didn't understand how it worked before thinking of submitting an issue.

I guess what's frustrating is the initial reaction.  VS Code is **really great**.  Absolutely!  But this fuzzy autocomplete to me is a disaster.  @Cirieno , @prd0000 and I might be in the minority on that viewpoint, but in my case and I suspect in theirs, this is such a major issue that it is severely debilitating.  I have typos **all the time** due to it.  To have @jrieken 's initial comments come across as "it's working properly, the problem is that you cannot submit a proper bug report" is frustrating.  Yes, we're only putting in an issue, not resolving it.  But submitting issues is also a valuable part of the process.  Can we appreciate the submitter a little bit as well as those who ultimately put in the fixes?
