### ISSUE TITLE
Chokidar crashes on vscode source folder when started from command line

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#52583]
* launch vscode from terminal via `code-insiders` and open vscode repo.
![image](https://user-images.githubusercontent.com/5047891/41713718-4977f85c-754e-11e8-85c7-5aa53b40faa8.png)

Note: when launching from the dock the file watcher works. Also, the nsfw version works. Also, the search service (using the same infrastructure) works.

**Comment by bpasero** [comment]
I can only reproduce with Electron 2.0.x, which I just nuked for our upcoming release.

**Comment by alexandrudima** [comment]
I cannot reproduce with an Insiders version using Electron 1.7.12

**Comment by Tyriar** [comment]
Nevermind, I can repro on Electron 2.0.4 on both mac and linux when I launch with `./scripts/code-cli.sh`

**Comment by bpasero** [comment]
@Tyriar I spend around 4 hours on Tuesday to investigate without much luck. Here is a few things I found out:
* it does not reproduce when running with `--verbose`
* it does not reproduce when running `code.sh` (instead of `code-cli.sh`)
* it does not reproduce when I instantiate the watcher in the renderer (as opposed to doing that in the spawned process as we do for our file watchers)
* it seems to crash while chokidar is scanning the file system initially (it does so to find symlinks) because chokidar does not crash right on startup but after a short while

I managed to attach Xcode to the running file watcher process and it stopped on error but all I got was some assembly code without `symbols`. I also tried to compile fsevents with debug symbols, but without any difference. 

Then I tried to force produce core dumps on macOS when processes crash (by enabling this via `ulimit -c unlimited`) and I could not get any core dumps, so I am not 100% sure this is actually crashing in some native code. 

This remains mysterious :(

**Comment by Tyriar** [comment]
@bpasero thanks for the info!

**Comment by Tyriar** [comment]
The signal that's killing the process is a SIGPIPE

**Comment by bpasero** [comment]
@Tyriar yeah I noticed that. I wonder though if that is the cause of the crash or rather a follow up issue because of the way how we talk from the renderer to the process through our IPC wrapper.

**Comment by Tyriar** [comment]
Possibly related: https://github.com/electron/electron/issues/13254

**Comment by bpasero** [comment]
Simple repro with Electron:
* git clone https://github.com/bpasero/electron-quick-start/tree/sigpipe
* `npm install`
* `chmod +x ./start.sh`
* open developer tools and find: `CHILD EXIT: null / SIGPIPE`

This seems to reproduce with `1.8` even, but not with `1.7`.

**Comment by bpasero** [comment]
We should probably prepare for a fix on our end and understand how we can end up with a process that writes to a stdout/stderr handle that is invalid. My theory is that this is related to the fact that the `code-cli.sh` script terminates (unless you run with `--wait` or so) and as such, the `stdio` handles associated with it are gone.

**Comment by bpasero** [comment]
It looks like we always ended up configuring stdio: pipe on startup when running through the CLI script. @mjbvz you introduced this via https://github.com/Microsoft/vscode/commit/1872949236cc243750899d5ad5704760e224ce5c#diff-5abef0ee0f64ab9a837696b4688e5ae7R315 which always ended up to be true because `typeof` checks only work with strings. I changed it to `typeof !== 'undefined'`

**Comment by Tyriar** [comment]
@bpasero should the upstream issue be closed?

**Comment by bpasero** [comment]
@Tyriar I still think a forked process should not crash with `SIGPIPE` ungracefully by triggering this log statement in native code. In comparison, when I do `console.log` from that process, it also does not crash.

**Comment by garthk** [comment]
Is there a released fix or a known mitigation for `Extension host terminated unexpectedly. Code:  null  Signal:  SIGPIPE` in 1.26 on macOS?

**Comment by bpasero** [comment]
@garthk you should file an issue about that, it seems unrelated to the fix here.
