### ISSUE TITLE
文件内容搜索BUG

### ISSUE THREAD

**Issue by aspwebchh** [Microsoft/vscode#52597]
当vscode打开一个拥有大量文件并且子文件夹层次较深的大目录并进行文件内容搜索时，将无法得到正确的结果。某些文件内容中明明存在被搜索的关键字，可这个文件无法出现在搜索结果文件列表之内。简而言之某些情况下，文件内容中明明存在我要搜索的关键字， 可这个文件却被护忽略了。 

这个问题浪费了我很多时间寻找程序的问题所在，结果却是vscode的问题。

**Comment by chrmarti** [comment]
"
File Content Search BUG

When vscode opens a large directory with a large number of files and a deep hierarchy of subfolders and performs a file content search, the correct result will not be obtained. Some of the file contents clearly have searched keywords, but this file cannot appear in the search result file list. In short, in some cases, there is a keyword in the content of the document that I would like to search. However, this file is ignored.

This problem is a waste of my time to find the program's problems, but the result is vscode problems.
"

**Comment by chrmarti** [comment]
Which OS and filesystem type are you on? Is this a local or a remote filesystem? Any way you can provide a minimal reproducible case?

**Comment by aspwebchh** [comment]
系统： windows 10 企业版 17134
文件系统： 本地文件系统 NTFS 固态硬盘
BUG症状：[https://mp.weixin.qq.com/s?__biz=MzAxMDEyMDQxMQ==&mid=2649589554&idx=1&sn=334f37ff75c4ebde99925771530a887d&chksm=834c1a86b43b939077cfe4c798e185f90f22b8f7c419fb222d799b523fe1ccf880044f2f57db#rd](url)

**Comment by roblourens** [comment]
Please try the tips on this wiki page to help me narrow down the issue: https://github.com/Microsoft/vscode/wiki/Search-Issues#missing-search-results

**Comment by nabychan** [comment]
This problem does exist in the latest release version of vs code(1.24.1). You can reproduce it by searching a word in a large project with many source code files and maybe files with different encoding。

**Comment by chrmarti** [comment]
@nabychan Could you attach a file and tell us for which search text it did not show any results when it should?

**Comment by nabychan** [comment]
I made a example repository:https://github.com/nabychan/search_files_example.git
There are 5 files with the same content:MoveRecord, 3 encoded in Utf16 LE, 2 encoded in Utf8(or ANSI in OS with different languages).Open this folder in VS Code, with no files opened, then search 'MoveRecord' with default setting, and you will get 2 files showed in the result. Hope this will helps.

**Comment by roblourens** [comment]
To search files with non-utf8 encodings you'll have to set `files.encoding`. We can only search with one encoding at a time. Does that work for you?

**Comment by nabychan** [comment]
@roblourens Ok, If it is designed as that, this issue is no more a issue.
