### ISSUE TITLE
Auto focus de l'arborescence

### ISSUE THREAD

**Issue by Felix49** [Microsoft/vscode#52621]
Issue Type: <b>Feature Request</b>

Proposition d'ajout de point de configuration : 
Ne pas déplacer l'arborescence quand on prend le focus sur un fichier.
Afin de pouvoir garder le contrôle de l'arborescence. Actuellement au moment de cliquer sur un fichier déjà ouvert (sur un onglet) l'arborescence des fichiers de gauche se déplace afin de se centrer sur le fichier que l'on vient de focus. -> peu utile et très dérangeant quand on a une grande arboresnce 

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 10.0.17134

**Comment by chrmarti** [comment]
"
Auto focus of the tree

Proposal to add configuration point:
Do not move the tree when you focus on a file.
In order to keep control of the tree. Currently when clicking on an already open file (on a tab) the tree of files on the left moves in order to focus on the file that has just been focused. -> little useful and very disturbing when you have a large tree
"

**Comment by isidorn** [comment]
"explorer.autoReveal": false,
