### ISSUE TITLE
Recent Insiders release broke keyboard navigation from Search: Find In Files pane

### ISSUE THREAD

**Issue by jessejanderson** [Microsoft/vscode#52633]
- VSCode Version: 1.25.0-insider
- OS Version: macOS 10.13.4

Steps to Reproduce:

1. Open "Search: Find In Files" pane (Cmd-Shift-F on Mac).
2. Type something that will have results and hit enter.
3. Press down arrow to navigation through results.

In previous versions, the down arrow would navigate through any visible inputs and then continue down into the results, allowing you to select a result and hit `enter` to load that file and move cursor focus into that pane. Now you have to `tab` through any visible inputs (and buttons) until the results area is focused, only then can you use the keyboard arrow navigation.

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
The arrow keys now control history navigation. You can use cmd+down to get from the search input to the results.

**Comment by sandy081** [comment]
@jessejanderson  This was due to the change of defaults

- Default shortcuts for History navigation in the input boxes are Up and Down arrows
- Default shortcuts for navigating among input boxes are `cmd+Up Arrow` and `cmd+Down Arrow`

Change was done because of this https://github.com/Microsoft/vscode/issues/12645. This made all our history navigation to be consistent and use Up and Down arrows.

You can always change the behaviour back by updating the keybindings to the following commands

Search Inputs navigation commands: `search.focus.nextInputBox` and `search.focus.previousInputBox`

Input history navigation commands: `history.showPrevious` and `history.showNext`
