### ISSUE TITLE
findFiles ignores 'base' part of exclude glob

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#52651]
This searches for *.ts files and excludes .ts files in the second workspace folder.

```ts
vscode.workspace.findFiles('**/*.ts', new vscode.RelativePattern(vscode.workspace.workspaceFolders[1], '**/*.ts')).then(result => {
        console.log(result);
});
```

When I run this, I get 0 results, when it should return results from the first workspace folder.

Seems like it's always been that way. Is that intentional @bpasero? If not I can fix it. We can pass absolute exclude globs to search.

https://github.com/Microsoft/vscode/blob/b7e6e04666ca8dde560b69081c43365dce77d12a/src/vs/workbench/api/node/extHostWorkspace.ts#L357

**Comment by bpasero** [comment]
@roblourens that looks like a bug to me, I would also expect to find any *.ts file from the first workspace folder.

**Comment by ArtyMaury** [comment]
On the same idea, I'm trying to give users the possibility to include folders in a file search, in a multi or single root workspace.
It looks like:
```js
let globPatternSource = `**/*.yml`;
if (sourceFolders !== undefined && sourceFolders.length > 0) {
    globPatternSource = `{${sourceFolders.join(",")}}/**/*.yml`;
}
vscode.workspace.findFiles(globPatternSource);
```
On a single root workspace it works fine, but with multi-root they can't just include "rootA", they would have to include all of rootA subfolders because the roots are already included in the search path. 

Is that the same issue or is that intentional?

**Comment by roblourens** [comment]
> but with multi-root they can't just include "rootA", they would have to include all of rootA subfolders because the roots are already included in the search path.

Sorry I don't understand what you're trying to do. You want to search a root, but not search its subfolders?

**Comment by ArtyMaury** [comment]
Sorry I wasn't clear.
Imagine a multi-root workspace like:

RootA:
- fileA.yml
RootB:
- fileB.yml

I'd like findFiles("RootA/**/*.yml") to return fileA.yml. But at the moment it doesn't return anything because the resolved search queries are "RootA/RootA/**/*.yml" and "RootB/RootA/**/*.yml".

To me, the root folders shouldn't be included in the query.

Was I clearer?

**Comment by roblourens** [comment]
I see - this is what `RelativePattern` is for - https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L1805

**Comment by osortega** [comment]
@roblourens do you know if this is still an issue?

**Comment by roblourens** [comment]
`findFiles2` might fix it, but I don't know. Should be easy to test
