### ISSUE TITLE
Attach to process: cannot put process '18117' in debug mode. Address already in use.

### ISSUE THREAD

**Issue by Kallaste** [Microsoft/vscode#52715]
- VSCode Version: 1.24.1
- OS Version: Mac OS 10.13.5 (High Sierra)

I'm not sure how to reproduce this issue, as it just sprung up for me seemingly out of the blue. I have been running a node.js application in the debugger all day by launching via the command line and attaching the debugger to the process. It was working fine, and I made no changes to the configuration. Then suddenly it began giving me an error via a popup:

> Attach to process: cannot put process '18117' in debug mode.

I also have a console error stating "Starting inspector on 127.0.0.1:9229 failed: address already in use."

I am able to run the debugger by having it launch the program itself, however, I can no longer attach to the running process.

<img width="1440" alt="screen shot 2018-06-22 at 5 18 28 pm" src="https://user-images.githubusercontent.com/5215504/41804344-6567f1c2-7641-11e8-96ff-556845f4cdb5.png">

launch.json:
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        
        {
            "type": "node",
            "request": "attach",
            "name": "Attach by Process ID",
            "processId": "${command:PickProcess}"
        },
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceFolder}/bin/www",
            "outFiles": [
                "${workspaceFolder}/**/*.js"
            ]
        },
        
    ]
}
```

**Comment by weinand** [comment]
You are seeing the error message because VS Code cannot use the default "9229" port for your program, because there is already a program using that port. Most likely another instance of your program that was not properly terminate. Use the Activity Monitor or "ps -ax" to find the program and kill it.

Why are you attaching to your node.js program via the a process ID?
Is it because you do not want to run node.js in debug mode?
If not, I suggest to use a different approach.

The recommended way of debugging node.js programs is by using a debug configuration with `"request": "launch"`(the second configuration in your launch.json). With this VS Code launches the program for you with the correct debug arguments and terminates the program at the end. This ensures that your program stops properly.
