### ISSUE TITLE
How to remove unwanted cloned project from VS code

### ISSUE THREAD

**Issue by Mathias02** [Microsoft/vscode#52726]
Good day,

Would you please help me to remove a project from my VS code that I might have cloned by mistake, it says on the fork icon 5000 pending changes and when  I press Ctrl/Shift+G I get this long script and the location seems to be  C:\Program Files\Git\bin\git, there is not any existing repository on my Git account please assist as this interfere with any JavaScript file I try create on the VS code, 

Regards

**Comment by TomSputz** [comment]
To get rid of all changes, right click on 'Changes' in the git tab, then click 'Discard all' It might take a while, but that should revert all the changes since you last commited to git

**Comment by joaomoreno** [comment]
@Mathias02 I hope you did not follow @TomSputz's advice, since that will delete lots of files, which is very likely NOT what you want.

Run `git rev-parse --show-toplevel` to find out where your git repository root is. If that should not be a git repository, then delete the `.git` folder contained within it.

**Comment by Mathias02** [comment]
Good day,

Thanks J Moreno I got it right, much appreciated and good luck in your
career

Regards
