### ISSUE TITLE
Filter within multiple results from "Go to Definition"

### ISSUE THREAD

**Issue by nitingupta910** [microsoft/vscode#52743]
When there are multiple hits with "Go to definition", I get a list of files where that symbol is found. If this file list is very long, it's hard to further narrow down the results based on file name pattern.  Is it possible to add a search box to filter out by filename within file list returned by Goto definition.

I'm facing this issue when open project like the Linux kernel where C/C++ intellisense plugin is not accurate enough and lists many incorrect results. Since I approximately know the filename,  filtering by filename within search results would be really useful.

Also, a way to expand all results, so I can see snippet within each file which matched. Currently, I have to click on each individual file result to see it.

**Comment by jrieken** [comment]
We have the new tree that supports this

**Comment by jrieken** [comment]
> We have the new tree that supports this

Actually not, `IKeyboardNavigationLabelProvider#getKeyboardNavigationLabel` must return sync but this is an async tree, e.g. the content of child node isn't known yet. 

@joaomoreno Is this something the tree can offer?

**Comment by joaomoreno** [comment]
@jrieken So you don't have the file names at render time?

**Comment by jrieken** [comment]
I have the file names but their children are the actual source text. I am a little confused, I might actually have them when I need them...

**Comment by jrieken** [comment]
This is now working - tho only on nodes that are already expanded (just like the editor) because their children are fetched lazily. By default, the filter/find highlights use the same colour as the match highlights, in below screen shot I have tweaked the latter so make it more obvious what's happening

<img width="404" alt="Screenshot 2019-05-24 at 10 03 34" src="https://user-images.githubusercontent.com/1794099/58312251-332f7900-7e0b-11e9-88f0-b3d63a38a232.png">
