### ISSUE TITLE
Setting for hiding TOC altogether

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#52809]
Issue Type: <b>Feature Request</b>

The TOC is useful browsing and discovering. However, I'm using searching for navigating large information sets. We should have a setting to hide the TOC altogther (same as I can configure what happens in search).

VS Code version: Code - Insiders 1.25.0-insider (5d6156a0f8b68fe7e9429facbcfaa7c061a8b3e3, 2018-06-25T09:32:08.937Z)
OS version: Darwin x64 16.7.0

**Comment by roblourens** [comment]
Added `workbench.settings.tocVisible`

**Comment by isidorn** [comment]
Adding verified since the setting works.
However I feel like the new settings is UX focused design and for it a more fitting approach would be context menu -> hide -> write to storage service. Right click -> bring it back. Or sam way to expand / collapse. Since we have all that ux we shuold use it, settings are generaly good in places where we do not have so much ux space to ad options to show / hide
