### ISSUE TITLE
root folder is not shown in search results

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#52897]
Testing #52288

In a MR workspace, File paths in Search results do not have `${root_folder}.${path}` format.

![image](https://user-images.githubusercontent.com/10746682/41904026-acc454e0-7937-11e8-9b66-fb47c4824e69.png)

![image](https://user-images.githubusercontent.com/10746682/41904057-b838a772-7937-11e8-840d-f54f062743a7.png)

Even though the search results are grouped by folder, it would be consistent to show paths same as every where. It is also helpful when there are too many results and you scroll down.

**Comment by isidorn** [comment]
This is fine becuase they show the absolute path, not the relative path.
It is up to each client to decide if he want to show absolute or relative path. Search choose to show absolute - and in that case there is no reason to show the root name.

Closing this as I do not want to change the behavior of the search and also since we have many other places where we show absolute paths (no tabs title bar for example).
fyi @roblourens  if he decides he wants to change the path representation in search - in case you do, just pass the `contextService` to the getPathLabel call.
