### ISSUE TITLE
Menus: clicking the application icon should show window context menu

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#52904]
Refs: #52854

Steps:
* click on the application icon top left
* 🐛 nothing happens

If you do this on a native title, it opens the window context menu.

**Comment by octref** [comment]
Agreed. This is expected from Win apps:

![image](https://user-images.githubusercontent.com/4033249/41942891-38b6d6a8-7956-11e8-8d7f-dd42017a8857.png)

**Comment by sbatten** [comment]
Right now we get the double-click to close behavior because the this area is not draggable. The context menu is provided by the OS and works on right click if we make this draggable but we lose the double click to close, but this is a suggested change #54929. I am going to do that and resolve this with that change.
