### ISSUE TITLE
Menu: add theming support

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#52914]
Refs: #52854

Currently the menu is not themable, we need to:
* [x] implement a high contrast theme
* [x] offer theme authors new colors to implement the menu theme

![image](https://user-images.githubusercontent.com/900690/41905402-59d697ee-793b-11e8-840a-50013bb70410.png)

**Comment by eamodio** [comment]
Since this was just closed, will this still be added: https://github.com/Microsoft/vscode/issues/54156

With my Amethyst theme (dark) the shadow of the menu is hard to see
![image](https://user-images.githubusercontent.com/641685/42839811-d2d3219c-89d2-11e8-8b86-83dcf88a8656.png)

vs the quickpick, which uses the `widget.shadow` color
![image](https://user-images.githubusercontent.com/641685/42840004-73cc896c-89d3-11e8-8ded-852d664b2d8a.png)

**Comment by sbatten** [comment]
@eamodio fixed with https://github.com/Microsoft/vscode/commit/151948783814664e2087f39c817c00c27262227e

**Comment by eamodio** [comment]
@sbatten just have to say -- I'm LOVING the new menu stuff!
