### ISSUE TITLE
Make it explicit that `deleteFile` will delete a folder recursively

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#52941]
Testing #52800

The docs of `deleteFile` should be explicit in that a folder will be deleted recursively, since that's the opposite of the usual FS APIs out there in which a folder can only be removed (`rmdir`) if it's empty.

**Comment by jrieken** [comment]
Yeah, we should maybe do what already have done for file system providers. Add an option `options: { recursive: boolean }`

**Comment by jrieken** [comment]
@bpasero I have updated the API and make sure the data travels to the bulk-edit-service but it seems that the textfile-service doesn't know about recursive folder delete

**Comment by bpasero** [comment]
@jrieken that's right because the `IFileService` does not expose any option to not delete recursively. I am not sure there would be any other client, so why not assert this within the `bulkEditService` and bail out early if the folder is not empty, similar to how it already bails out if the file exists: https://github.com/Microsoft/vscode/blob/39b91f6c674882ef20fbde20b95ed6c01cd3a576/src/vs/workbench/services/bulkEdit/electron-browser/bulkEditService.ts#L345

**Comment by jrieken** [comment]
I'd say that once we expose the full 'reading'-api for file system provider we will encounter this again (see #48034). Sure, we can do a short term trick in the bulk edit service but I think the fileservice/textfileservice-couple is the place that should have this. Likely also true for `ignoreIfExists` (which we might nuke again...)
