### ISSUE TITLE
debug-console: arrow-up key affect command history instead of proposal menu

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#52964]
testing https://github.com/Microsoft/vscode/issues/52804:

- run node debug session and break somehwere
- in debug console type 'con' to open proposal menu
- use arrow-up key to select item from proposal menu

Observe: the "arrow-up" key selects an item from the command history instead of the proposal menu.

I would expect that the arrow keys affect the proposal menu as long it is showing.

**Comment by isidorn** [comment]
I have fixed this using a workaround.
The actual issue is that the suggest widget and the repl history are fighitng for arrow up / down
So I would need to specify to the history commands that they should be disabled when an additional context key is on 'suggestWidgetVisible'.
However there is currently no way to do this.

With the workaround the behavior is decent now, but something to keep in mind for the future @sandy081
