### ISSUE TITLE
onDidAccept proposed APIs don't match naming convention

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#52979]
https://github.com/Microsoft/vscode/wiki/Extension-API-guidelines#event-naming

Maybe they should be `onDidAcceptText` given https://github.com/Microsoft/vscode/issues/49340#issuecomment-391290786?

Related: https://github.com/Microsoft/vscode/issues/52882#issuecomment-400287985

**Comment by chrmarti** [comment]
For `QuickPick` it might have to be `onDidAcceptItems` because it really fires for all the different 'accept' gestures that should behave consistently for each widget. Needs some more thought.

**Comment by chrmarti** [comment]
@jrieken I believe we discussed this, did we conclude that `onDidAccept` was fine? We could use `onDidAcceptValue` on InputBox and `onDidAcceptItems` (although often it will be exactly one) on QuickPick. One reason against being specific was that we would let extensions decide what to 'accept', but we later discarded that reasoning because we expect extensions to consistently accept the value in InputBox and the items in QuickPick and use the buttons for alternative actions (like accepting the value in a QuickPick). Opinions?

**Comment by jrieken** [comment]
Yeah, the rule says `on[Did|Will]VerbSubject` but we have a few places in which we skip the `Subject` because its obvious from the context, like `WebView#onDidDispose` (instead of `WebView#onDidDisposeWebview`). It never hurts to be explicit but if the context/subject is obvious (which is likely to happen more often with "local/private" events) then it is an option to skip the subject-part

**Comment by chrmarti** [comment]
Sounds good. I'll keep the existing naming then. That also makes it somewhat consistent across these interfaces.
