### ISSUE TITLE
Read only workspace: actions in explorer that aren't actionable should be disabled

### ISSUE THREAD

**Issue by misolori** [Microsoft/vscode#53012]
Issue Type: <b>Bug</b>

Testing #52573

Shouldn't the `New File`  and `New Folder` actions be disabled when in a read only workspace? We disable the `Toggle Editor Layout` action in the explorer when in a single view. If we do, we should also update the title of each action to communicate why it's been disabled (like the current error message).

![image](https://user-images.githubusercontent.com/35271042/41927647-ab880d02-7927-11e8-9042-cd881c9300a2.png)

VS Code version: Code - Insiders 1.25.0-insider (923e9ccb3fc44bfaaf4b4049015c84e42bc40f95, 2018-06-26T13:00:22.932Z)
OS version: Darwin x64 17.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|16.00GB (0.17GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_4183037|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
svgo|100|0.8.0
vscode-svgo|ajh|0.1.0
gitlens|eam|8.4.1
python|ms-|2018.6.0

(4 theme extensions excluded)

</details>

**Comment by isidorn** [comment]
@misolori good point. However these actions can not be disabled since they are global, for example you could be in a multi root workspace, one root is readonly the other not. These actions can be run on both.
If there is only one workspace and it is readonly then these should be disabled.
However due to how these actions are structured from an engineering perspective (enablment based on resource, not on worksapce) I will not disable them
Due to that closing as will not fix. If lot of users complain about this I will reconsider to fix this
