### ISSUE TITLE
Outline "follow cursor" doesn't follow cursor during or after 'find'

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#53030]
Testing #52799

- Open fontInfo.ts in vscode
- Enable "Follow Cursor"
- ctrl+f, type _string
- Press enter to go through the 3 matches
- The current match should be selected in the Outline view, but it still shows whatever it showed before ctrl+f :bug:
- When `function _string` is the current match, press 'esc'
- The Outline view still doesn't select _string until I move the cursor

**Comment by jrieken** [comment]
We have an explicit check that revealing only happens when selection changes were made explicitly [`e.reason === CursorChangeReason.Explicit`](https://github.com/Microsoft/vscode/blob/f4e9748b6fc1ab7955c72fa4e619f71a771a6eb8/src/vs/workbench/parts/outline/electron-browser/outlinePanel.ts#L576). I'll remove that and we'll see how it feels
