### ISSUE TITLE
Show unsaved decoration in explorer

### ISSUE THREAD

**Issue by graph** [Microsoft/vscode#53042]
- VSCode Version: Version 1.24.1 (1.24.1)
- OS Version: Mac

Steps to Reproduce:

1. open a few files
2. write something in all of them and save
3. write something in 1 of them without saving.
4. By looking at the explorer you don't know which file is unsaved. All changed files are red because of version control.

Expected results: All instances where the file is referred to in the explorer it should draw the same circle signifying it's unsaved.

Actual results: It just highlights in red that it is changed according to version control but not necessarily unsaved. Except in the "Open Editors" section where it does show a circle.

In the "Open Editors" it does show a circle. But in the project node there is no indication. My project is very big I rarely look at the "Open Editors" section, the project node is more nicely organized.

**Comment by roblourens** [comment]
The red highlight shows that there are errors in the file, not that it's edited. If the file is not saved, then version control doesn't know about it. But maybe the explorer can still show a decoration.

**Comment by ilteris** [comment]
I was looking for this feature. It would be great to differentiate between files that are not saved  and unsaved in explorer. The badge on the activityBar shows me (1) but I have no idea what that meant, until I have found out a file I didn't save. Showing the file unsaved bold would at least let me allow to make a connection that that's why I am getting that badge.  Thanks!
