### ISSUE TITLE
Cannot multi-select, Add to Recommended Extensions

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#53043]
Testing https://github.com/Microsoft/vscode/issues/52850

I can multi select extensions in the extension viewlet, but the command `Extensions: Add to recommended Extensions (...)` only adds the extension that is open in the editor.

**Comment by ramya-rao-a** [comment]
There is no action on the extensions that is supported in the multi-selection mode at the moment.
That's why we resorted to making all the recommendation related actions act on the extension that is opened in the editor.

Ideally actions Disable/Enable/Uninstall/Install could be supported in the multi-select mode.

@sandy081 @isidorn Is that something we want to do?

**Comment by sandy081** [comment]
Multi-select is not yet supported in Extensions viewlet - https://github.com/Microsoft/vscode/issues/44508

**Comment by isidorn** [comment]
Since none of the actions in the extensions viewlet are mutli select aware I would disable multi select there - it is just confusing now.

If we want to do this for the future - imho not really needed, most of the time users operate on one extension, and we allready have some mass actions - like disable all extensions

**Comment by isidorn** [comment]
It is still possible to select multiple items in the extensions view by using the keyboard.
Press shit + up and you can see multiple things selected. I would expect this is disable as well -> reopening

**Comment by sandy081** [comment]
I set `multipleSelectionSupport` option to false while creating the list and I expect list disable it completely.

@joaomoreno FYI

**Comment by joaomoreno** [comment]
Please file issue! 👍
