### ISSUE TITLE
Menus: Drop shadows should look real and only be shown on 2 sides

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#53073]
Refs: #52854 

![image](https://user-images.githubusercontent.com/4033249/41945306-32221392-7961-11e8-9f26-b913962a8a04.png)

The drop shadow is only possible if you have a light source right on top of the menu, but that's impossible...You can't have a light source that's always on top of any menu.
A better metaphor is light is in the room somewhere, and the expanded Menu floats above the bottom layer to cast a 2 sides shadow. See Notepad, File Explorer, etc:

![image](https://user-images.githubusercontent.com/4033249/41945379-a06de894-7961-11e8-9d09-bea0904bac75.png)

![image](https://user-images.githubusercontent.com/4033249/41945403-b788aece-7961-11e8-9c16-0b323ad20c1b.png)

![image](https://user-images.githubusercontent.com/4033249/41945452-f78abd3c-7961-11e8-9644-9a7b558391a1.png)

**Comment by bpasero** [comment]
@octref @sbatten (also ping @misolori for some guidance) I would also put the `drop-shadow` more towards the corners of the menu and not everywhere as it is currently. E.g. with `box-shadow: 2px 3px 8px` it looks like this:

<img width="287" alt="after" src="https://user-images.githubusercontent.com/900690/42085708-84ee8ed4-7b91-11e8-9f48-08365672bb76.png">

vs

<img width="306" alt="before" src="https://user-images.githubusercontent.com/900690/42085713-87d64808-7b91-11e8-98eb-eb423a22ae17.png">

**Comment by misolori** [comment]
If you use `box-shadow: 2px 2px 2px 0px` you can get really close:

![image](https://user-images.githubusercontent.com/35271042/42099881-8562d2f8-7b73-11e8-8647-fc5a22d3e671.png)

The problem we have is that the native Windows dropdowns use a border and a gray background color so they don't need to show the drop shadow on both sides. Our dropdown utilizes the theme color, which can overlap with the content behind it. So we either need some sort of border or increase spread amount to help define the dropdown area.

I'd suggest going with `box-shadow: 1px 1px 4px 1px` so that there's a tad bit of shadow on the other sides to help define that area:

![image](https://user-images.githubusercontent.com/35271042/42100135-3e3b0606-7b74-11e8-8a7b-5b7c3ab85eb1.png)

**Comment by bpasero** [comment]
`box-shadow: 1px 1px 4px 1px` looks geat

**Comment by alinnert** [comment]
May I add my thoughts to this discussion?

While it's true that menus use a bottom-right shadow, to me they also look like a relic of Windows' older days (and I don't really like them). The shadow of application windows on the other hand seem to be exactly centered, like `0 0 20px(?)` (but it's hard to tell if they really are; maybe there's a tiny vertical offset). And I think macOS uses shadows that only have a vertical offset value. (+ The Material Design Language uses the same technique. The sum makes it almost some kind of "state of the art".)
If you take that into account I think it's kind of inconsistent to use a different angle just for the menus' light source. Or what do you think?

**Comment by sbatten** [comment]
I agree with @alinnert here. Modern applications in windows tend to use either no shadow or one with no horizontal offset. If you look at a UWP, they don't really use any shadows, which works for them because of border, so then take a look at Office which seems to use a very subtle border with a slight vertical offset only.

**Comment by sbatten** [comment]
@misolori I've slightly modified the shadows when making them themed, but sticking with the "no vertical offset" philosophy (reasoning above). What do you think?

**Comment by sbatten** [comment]
spoke with @octref and he was pleased with the new current look of shadows.

**Comment by misolori** [comment]
@sbatten LGTM!

<img width="50%" src="https://user-images.githubusercontent.com/35271042/43877349-1beff774-9b4e-11e8-96d8-d4b814156cc4.png">
