### ISSUE TITLE
Improve usefulness of extension "Contributions" view

### ISSUE THREAD

**Issue by jdforsythe** [microsoft/vscode#53146]
The Contributions tab for an extension should be a quick place to change settings for that extension.

- The "Settings" section should show the current workspace/user value for the setting as well as allowing to change the setting
  - this could be an inline editor, modal dialog, or just a "Set" link in the workspace/user columns that pops open the settings.json and adds the key to the bottom of the file or positions the cursor at the existing value

- The "Commands" section should similarly allow changing the keyboard shortcut
- The "Languages" section should have a link to show a syntax-highlighted sample of the snippets

**Comment by lucavallin** [comment]
I feel like trying to work on this, who do I ask permission to?

**Comment by lucavallin** [comment]
Thank you!

**Comment by ramya-rao-a** [comment]
> The "Settings" section should show the current workspace/user value for the setting as well as allowing to change the setting

The new settings Editor that we have has a good way of separating extension settings from the rest. As well as a way to separate settings from different extensions:

![image](https://user-images.githubusercontent.com/16890566/45391852-804f2000-b5d9-11e8-93f9-7c9000c80f4f.png)

Since we are investing quite a bit on the settings editor, we do not want to prioritize allowing edits from the Contributions view for the same at the moment.

> The "Languages" section should have a link to show a syntax-highlighted sample of the snippets

The snippets themselves follow the textmate syntax and therefore we cannot directly apply syntax highlighting on them based on the language.

But, having a way to explore what snippets are being provided is a valid ask. One way to do that today, is to visit the repository for the extension. We could make this easier, as we already know the file that powers the snippets and so can open them in a read-only mode. This is easier for installed extensions.

> The "Commands" section should similarly allow changing the keyboard shortcut

@sandy081 Would you consider this? Or can we do something in the keyboard shortcuts editor to separate commands keybindings from extensions vs default vs user?

**Comment by jdforsythe** [comment]
Agreed, the new settings editor is nice. Maybe just a link from the extension page to its settings in the editor, if it's installed, would be useful.

**Comment by sandy081** [comment]
@ramya-rao-a Yes there is a feature request to show commands grouped by extensions.

**Comment by ctf0** [comment]
is there a chance we can change the extension settings from the contributions view ? 
am aware of https://github.com/Microsoft/vscode/issues/25012#issuecomment-483340327, i was wondering if possible to take an extra step and get the ability to change the extension settings directly from its own view.

**Comment by sandy081** [comment]
Extension editor has an action to navigate to its settings in Settings UI. 

Hence closing this.
