### ISSUE TITLE
[Feature Request] Allow user to set extensions folder 

### ISSUE THREAD

**Issue by ngohungphuc** [Microsoft/vscode#53154]
I would like to make a feature request that user can choose location for their extension folder using preference -> settings.

Currently we can set extension folder by setting properties of vscode shortcut by setting target options in properties like this

> "D:\Microsoft VS Code\Code.exe" --extensions-dir="D:\Microsoft VS Code\extensions"

**Comment by nhatnguyen95** [comment]
+1 for feature request

**Comment by ngohungphuc** [comment]
Because since all of vs code setting already contain in preference setting. I think would be more easy for user to manage all settings in one place and we can save memory for C drive

**Comment by sandy081** [comment]
extensions directory is not a setting, it is an environment option and they are clearly separated. Not convinced to make it part of settings. 

Do not understand why does the user has to manage this? Also did not get how does this save memory?

**Comment by jltgroup** [comment]
@sandy081 Thanks Sandy for identifying the duplicate, I promise I did search beforehand, but clearly not thoroughly enough.

To answer your question from the 28th of June, there are a number of reasons why the default extension directory is not applicable for users. I, for example, am restricted where I can run executables from (due to Windows Group policies). Thus extensions that run executables (e.g. ms-vscode.csharp) will not work. Others, I've noticed, are restricted to how much free space is available in their profile folder.

As the only way to override this setting is via the command line option `--extensions-dir`, then a user would either need to
- create a shortcut and include the command line option
- or explicitly set the value on the command line.

This reduces the usefulness of the Windows Explorer shell integration, where a user can right click on a folder and select **Open with Code**.

With regards whether this is a setting or an environment option, I think is academic. It is a configurable value and a user would expect to alter this value in a central location, such as the application's settings window.

**Comment by joaomoreno** [comment]
It would be possible if we implemented it... Though that solution might cause confusion since one would set that env variable and all Code instances (insider, stable, etc) would use it.

It would be great if it would still be scoped inside user-data-dir... that's why settings would be great.

**Comment by jltgroup** [comment]
this may be a duplciate of #17691
