### ISSUE TITLE
Quickly start debugger in currently open file.

### ISSUE THREAD

**Issue by haemse** [Microsoft/vscode#53172]
Sometimes you quickly want to try some piece of code in a new file, without running the whole debugging tree from the entrypoint file, but just that little test file.

Currently you would have to change the settings in the launch.json

It would be super convenient to onetime-start the debugger in the currently open file with just a shortcut or so.

**Comment by weinand** [comment]
Since VS Code supports many debuggers and languages, it is not easily possible to support your proposed feature in a generic way. E.g. how should this work for C++? 

But individual debuggers are supporting this already. E.g. the built-in Node.js debugger runs a JavaScript file open in an editor (if there is no launch.json).

For which debugger/language would you like to see this feature?

**Comment by haemse** [comment]
Any ;-)

In my case node.js

Yes, by default it runs the open one, however if you work on a alrge prj you will set an entrypoint, since you dont't want to switch tabs for every debug.

**Comment by weinand** [comment]
If you need to set an entry point anyway, then you can just use a launch config for this, right?
