### ISSUE TITLE
Logpoint intellisense is not correct

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#53193]
- Open some file
- Add a logpoint, type `this` in message box
- Get intellisense for `his`

![image](https://user-images.githubusercontent.com/323878/42006987-15f8c5e0-7a32-11e8-99f7-10290bdc73f4.png)

It's ignoring the first letter, but also I shouldn't get intellisense there, only inside {}, right?

- Type inside `{}`
- Get suggestions for 'this' context

![image](https://user-images.githubusercontent.com/323878/42007028-5ec71b1e-7a32-11e8-98a1-e0fd1ccc2177.png)

- Type `{this.toD}`
- Get global suggestions starting over at the `.`, not suggestions for `this`

![image](https://user-images.githubusercontent.com/323878/42007013-42ed06a6-7a32-11e8-89b5-1bfecf277781.png)

**Comment by isidorn** [comment]
@roblourens nice catch. The issue was that the repl suggestions were jumping in.
The last issue you mentioned, regarding the suggetsions after `.` is hard to fix due to the fact how we have implemented this feature - the breakpoint widget is a fake editor that is working on the bottom editor to get the context. There is an issue already capturing this, so if you are interested I can try to dig it out

**Comment by JacksonKearl** [comment]
I'm correctly getting no intellisense when there are no braces, but even within braces I get no intellisense after any `.` (i.e. `this.` returns no results)

**Comment by isidorn** [comment]
Yeah that is expected due to the reason specified above
