### ISSUE TITLE
code-insiders --status — Failed to parse header size from asar file

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#53194]
While verifying #51100

**Steps to Reproduce:**

1. Open the VS Code source in VS Code insiders
2. Run `code-insiders  --status`

**Bug**
See this line in the output:

```
Workspace Stats: 
|  Window (extensionService.ts — vscode)
[98683:0627/174825.656901:ERROR:archive.cc(163)] Failed to parse header size from /Users/matb/projects/vscode/extensions/css-language-features/server/test/pathCompletionFixtures/src/data/foo.asar
```

**Comment by RMacfarlane** [comment]
From https://electronjs.org/docs/tutorial/application-packaging#using-asar-archives, the node APIs for reading directories treat `asar` files as virtual directories.  Since the file `vscode/extensions/css-language-features/server/test/pathCompletionFixtures/src/data/foo.asar` is just being used for a test and isn't actually formatted as an `asar` file, an error is logged within the call to `readdir`.

I can't think of a good way to suppress it since it's being logged from electron code, so I've reformatted `foo.asar` instead. Other users shouldn't run into this unless their projects also have a malformed `asar` 😄 

// cc @aeschli as an fyi

**Comment by konradw86** [comment]
sprawdzić????Terms of.txt
<https://drive.google.com/file/d/17Cbf2F9q1R_VZXo2Ci9cET-BpHpa5BIW/view?usp=drivesdk>


czw., 28.06.2018, 02:51 użytkownik Matt Bierner <notifications@github.com>
napisał:
