### ISSUE TITLE
Verify telemetry

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#5324]
@isidorn 

* [ ] any os

The telemetry services have been refactored. Verify that

* error telemetry shows extension errors
* error telemetry shows vscode errors
* error telemetry contains no PII
* data telemetry works

**Comment by isidorn** [comment]
I am blocked on this since none of the queries I input [here](https://analytics.applicationinsights.io/subscriptions/dec3cbaa-81bb-4ea0-8a37-e27a20ef4089/resourcegroups/Ticino-AppInsights-Group/components/ticino#/discover/query/?_g=()) give back any result - they just say loading for forever

@seanmcbreen @jrieken do you see the same? Or the kusto dashboard works for you


![screen shot 2016-04-26 at 16 57 09](https://cloud.githubusercontent.com/assets/1926584/14822712/f1e791f4-0bcf-11e6-9936-08189c8b13bd.png)

**Comment by seanmcbreen** [comment]
Workihng OK for me I have seen that happen when you need to re-authenticate.  Do do that refresh the window...

![image](https://cloud.githubusercontent.com/assets/1051190/14826604/80165f56-0b93-11e6-8288-a51bea5a7b34.png)

**Comment by jrieken** [comment]
@seanmcbreen Can you check there is data from the recent VS Code version (last insider release, 1.01) and tick this off?

**Comment by isidorn** [comment]
There is 1.01 data
Also verified that there is 1.10 error telemetry data here https://ticino-errors.azurewebsites.net/
Found extension errors https://ticino-errors.azurewebsites.net/?bucketIdHash=6e72a421-f70a-f1ba-0ff4-66a45c263b01
Quickly going through telemtry I did not see any PII, though those will come as seperate bugs over time

<img width="465" alt="screen shot 2016-04-27 at 10 38 03" src="https://cloud.githubusercontent.com/assets/1926584/14846483/61879e20-0c64-11e6-818c-26dc8210c6eb.png">
