### ISSUE TITLE
LiveShare: Improve support for dirty readonly files

### ISSUE THREAD

**Issue by IlyaBiryukov** [microsoft/vscode#53257]
Issue Type: <b>Bug</b>

When an extension applies edits to the documents opened from a read-only file system provider, the document becomes marked as 'dirty' but saving it always fails with an error "Failed to save 'file.ext': Insufficient permissions. Select 'Retry as Admin' to retry as administrator." Retrying as administrator does nothing and repeats the error.

VS Code version: Code - Insiders 1.25.0-insider (5d6156a0f8b68fe7e9429facbcfaa7c061a8b3e3, 2018-06-25T09:40:10.343Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.92GB (12.16GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe C:\src\cascade\vscode\extension|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.17.5
csharp|ms-|1.15.2
vsliveshare|ms-|0.4.0-dev

</details>

**Comment by bpasero** [comment]
@isidorn I wonder if a better approach would be to mark the underlying editor model as readonly instead of making the editor readonly and then having to fight for all these corner cases. I think a readonly model is the only way to prevent this from happening.

**Comment by isidorn** [comment]
@bpasero I was not aware that we have readonly models. I will look into that as it makes more sense to make the model, not the editor readonly

**Comment by bpasero** [comment]
@isidorn we do not have this currently as far as I know, I would ping @alexandrudima to ask if this is feasable

**Comment by alexandrudima** [comment]
@isidorn @bpasero We have no readonly models, we have only readonly editors.

The reason is simple: most likely you want to prevent the user from editing the model than the system. e.g. the output channel is a readonly editor with a buffer that can be modified; if we are to display a readonly file from disk, then we might want to listen to file change events and update the contents of the buffer from disk, even if we prevent the user from editing.

So I believe the current abstraction where an editor can be readonly, but that concept does not exist on a text buffer is a good abstraction.

**Comment by bpasero** [comment]
@alexandrudima but we have a lot more places where a model is not shown in an editor but potentially still can be edited programmatically, to give some examples:
* search & replace operates only on the model, not on the editor
* extensions can instantiate models (`openTextDocument`) without showing them and make edits to it through our API

So we need to carry the notion of the model being readonly on without the need for an editor somehow.

**Comment by alexandrudima** [comment]
@bpasero that should live in the layer above the `TextModel`, as the `TextModel` is not aware of file systems (reading, writing), dirty state, read only file systems, etc.

btw, it is trivial to create a readonly `TextModel` that throws every time its text is attempted to be edited or when `setValue` is called, but then you are going to need to deal with disposing `TextModel`s correctly and creating them again (with all memory usage implications) every time such read only files change on disk. i.e. a readonly `TextModel` is readonly for everybody, including the workbench file event handling code.

**Comment by bpasero** [comment]
@isidorn talked with Alex, makes sense to not push this down to the code editor model. I believe we have to check all our usage patterns where we modify a model and guard against that:
* workbench places like search & replace that operate on the model
* extensions that use edits on a visible text document
* extensions that apply workspace edits

For each we need to see how to react, e.g. after discussion:
* search & replace could simply ignore the readonly models instead of throwing an error
* workspace edits should probably either apply in total or not at all raising an error

**Comment by bpasero** [comment]
@isidorn clients of [`createModelReference`](https://github.com/Microsoft/vscode/blob/e3dc63dd0f64c2fb7c36f86f297aae3789bbf50a/src/vs/editor/common/services/resolverService.ts#L23) would be a good start, these will create a workbench editor model and potentially modify it. 

Search & replace is a bit different because I think we do not instantiate models for those unless already opened, but I could be wrong (@sandy081 would know).

**Comment by IlyaBiryukov** [comment]
About extension applying changes to a document opened from a read-only file system provider, we do need that working. The issue is the behavior of save. I think saving a document should just be disabled for read-only provider.

**Comment by bpasero** [comment]
@IlyaBiryukov yeah good point, extensions still need to be able to make changes to the model in case it updates. We could maybe change our model in a way that a readonly model never shows up as dirty to the user.

**Comment by sandy081** [comment]
> Search & replace is a bit different because I think we do not instantiate models for those unless already opened, but I could be wrong (@sandy081 would know).

Search & replace does not instantiate any model directly, but uses bulk edit service API from @jrieken.

**Comment by jrieken** [comment]
> Search & replace does not instantiate any model directly, but uses bulk edit service API from

Which uses the TextFileService from @bpasero

**Comment by bpasero** [comment]
Yeah, it is rather the `ITextModelService` which is being used to resolve the model and apply the edits. Maybe somewhere [here](https://github.com/Microsoft/vscode/blob/ecda8b719441832720c43a67b04667813f294b7e/src/vs/workbench/services/bulkEdit/electron-browser/bulkEditService.ts#L213) it should throw an error if the model is readonly (we know that at that point).

**Comment by isidorn** [comment]
@bpasero that makes sense, however at that point we have a `ITextEditorModel` not a `ITextFileEditorModel`. Just casting feels like a hack, so not sure what to do there.
If we throw an error there should it catch most of the cases or we should still go through all the usages of `createModelReference`?

**Comment by bpasero** [comment]
Maybe we need to put this property one level up then?

**Comment by isidorn** [comment]
@IlyaBiryukov can you please try this out in tomorrow's vscode insiders when you find the time and let us know if it works fine for you. Thanks a lot
Now it should not longer attempt saving but immediatly throw an error

**Comment by IlyaBiryukov** [comment]
There is a regression in the latest insiders, #57032, maybe due to the fix for this issue. 
Because of it, I cannot verify the fix.

To clarify this issue, applying edits to a file open with a read-only file system provider with `vscode.workspace.applyEdit` should still work - the file cannot be saved, but it should still be able to be modified by a vscode extension.

**Comment by isidorn** [comment]
Reopening and assigning to September per discussion in https://github.com/Microsoft/vscode/issues/57032

**Comment by dakowebrex** [comment]
hello,
you should try this for saving issue in ubantu
sudo chmod -R 777 PATH  
LIKE..
sudo chmod -R 777 /opt/lampp/htdocs/potrider

**Comment by talhashahab786** [comment]
@dakowebrex  worked for me! THANKS

**Comment by talhashahab786** [comment]
@dakowebrex First got to the folder using cd and ls.
Then :
sudo chmod -R 777 *

**Comment by bpasero** [comment]
@isidorn fyi with my latest changes around supporting custom editor save, there is also an impact here: an editor that shows up dirty but is marked readonly from the filesystem provider will no longer participate in the save. For example, the file appears as dirty but Cmd+S or Save All will ignore it. 

Editors can now signal back if they are readonly (`IEditorInput#isReadonly()`) and the file editor input implements this via the `FileSystemProviderCapabilities.Readonly` capability:

https://github.com/microsoft/vscode/blob/90a0eb3a145b7c8b8f548a6183475291ace63719/src/vs/workbench/contrib/files/common/editors/fileEditorInput.ts#L227

**Comment by bpasero** [comment]
@IlyaBiryukov here is how latest behaves (note the dirty file that is readonly).

![before](https://user-images.githubusercontent.com/900690/69213913-cef53400-0b65-11ea-88eb-dfb6735ae93f.gif)

The editor is still considered to be dirty in the workbench and that means indicators show up as usual, however `Cmd+S` and Save All for example ignore this editor. 

Still, the user cannot close the editor in this state without deciding on reverting the file. Doing so will not result in an error because it will fail but we ignore it since the editor is closing anyway.

I think this behaviour is better than before but wondering if you think it can be improved further.

**Comment by IlyaBiryukov** [comment]
It's definitely better than before. 
Will the save prompt pop up when you close workspace / VSCode?
Can we not show the save prompt for a dirty file if the file system is read-only? Save does nothing there anyway.

**Comment by bpasero** [comment]
Yeah, there are still things missing. Specifically:
* closing such an editor will still ask for save/revert
* closing the application might ask for save/revert if hot exit is disabled

I think we need to come up with a new kind of dirty state specifically for readonly resources. The situation got a bit better with the changes around Save & Revert commands, but not fully there yet.

**Comment by bpasero** [comment]
One idea would be to never show any dirty indicator for readonly documents. Assuming that the user cannot cause the dirty change of a readonly file system anyway, that would probably be an OK change to do.

**Comment by bpasero** [comment]
@IlyaBiryukov given issues I recently filed such as https://github.com/MicrosoftDocs/live-share/issues/3090, https://github.com/MicrosoftDocs/live-share/issues/3092 and https://github.com/MicrosoftDocs/live-share/issues/3093 it would probably be a good idea to find a solution that works for all these cases.

My understanding is that the LiveShare extension directly modifies the editor for each keystroke the host does. As such, the guest will see a dirty indicator as soon as that happens because every change to the model will turn it dirty until it gets saved or reverted. This can happen if:
* the user saves the file (or it get's auto saved)
* the user reverts the file (e.g by invoking the revert command or closing the dirty editor without saving it)
* the user presses undo until the last saved state is reached again

I think my suggestion in https://github.com/microsoft/vscode/issues/53257#issuecomment-573524504 is probably not a good one because we still want to indicate to the guest that a document has not been saved yet. Even if readonly, it may be interesting to know if the document is still dirty or not.

Given that, trying to find out what is missing in API today for LiveShare to handle these cases:
* an event for when a document changes its dirty state, this would allow to detect all the cases of save and revert properly
* a command or API to indicate that a document's dirty state should be cleared. I think a revert() method would come close here as it would a) clear the dirty indicator and b) load the contents as they are persisted by the host

Does that sound reasonable?

**Comment by bpasero** [comment]
Related: https://github.com/microsoft/vscode/issues/7532 and https://github.com/microsoft/vscode/issues/50969

**Comment by bpasero** [comment]
With https://github.com/microsoft/vscode/commit/d10819598b2a1525cbae9abc69c0fc98b66c7316 I pushed a change to not mark an editor as dirty when its model changes and the editor is readonly. 

The rationale is that we have an increasing number of custom file system providers built-in that register as readonly (for example Git). I think these providers are fine to make changes to the underlying model directly as needed, but should never result in dirty indicator to the user, nor play a role in hot-exit.

I tested this in todays insider build and when I join a readonly LiveShare session I am no longer seeing the dirty indicator when the host is typing. I think that is a reasonable change, but let me know otherwise.

**Comment by IlyaBiryukov** [comment]
Thanks! Appreciate it.

**Comment by bpasero** [comment]
@IlyaBiryukov I tested this and it seems to work fine, with one catch: with default settings, editors in VSCode open in preview mode unless you make changes (you see an italic title). Every editor you open replaces that preview editor. Now, since the guest no longer sees the editor as dirty, it stays in preview mode (it used to get "pinned" automatically when becoming dirty), even if the host sees it not in preview. As such, any other editor the host opens will replace the preview editor in the guest session. 

I felt this was an OK experience because it is up to the guest to e.g. double click the editor title to get it out of preview.
