### ISSUE TITLE
Outline + WebView

### ISSUE THREAD

**Issue by kozubikmichal** [Microsoft/vscode#53330]
Hi,

it would be handy if there is some kind of symbol provider for WebView Panels that would be reflected in Outline view.

Or am I missing some already existing support for that?

**Comment by jrieken** [comment]
That's currently not possible. The outline API is working with text documents and webview panels can be anything and nothing. This is unlikely to happen any time soon

**Comment by nealot** [comment]
Does this also apply to previews of text documents like the markdown preview? Could documents which have both previews and text-modes retain their outlines in either state? Currently, opening a markdown preview results in the outline disappearing. Could this behaviour be changed so that the outline which is derived from its text-form persists in preview mode?

**Comment by kozubikmichal** [comment]
Yeah I now that panels can be anything but my idea was that one could register symbol provider for some panel -> and those with symbol provider registered would be displayed within the outline view.

That means to keep it completely on the webview panel owner
