### ISSUE TITLE
Multiple windows can open when restoring workspace with dirty files

### ISSUE THREAD

**Issue by user3323** [microsoft/vscode#53457]
- VSCode Version: 1.25.0-ins
- OS Version: win7x64

You work in your workspace (with some opened tab editors), named "MyProject".
Save it to `D:/test/`
Then, close workspace.
After that, you decide, that folder `test` should be `test123`, renaming it.
Launch VS Code ---> Open workspace ...  ---> Find your workspace in test123 .... open it.
And all your tab editors - are gone!
Well, they actually not gone, they exist, but will shown only if you will rename folder back to _**test**_

What a nice **_path dependencies_**!

PS: this bug also produced this issue --> https://github.com/Microsoft/vscode/issues/52371 
Same symptoms. But even worse.
I was working with "space1". Closed it.
Created new "space2".
Closed VS Code.
Renamed folder path of these spaces.
Opened VS Code, and I've got "space2" with separate window with Untitled files from "space1".

**Comment by bpasero** [comment]
@user3323 to be clear, you are using a workspace file that has a single entry pointing to a folder? Or are you opening a folder and not a workspace?

**Comment by user3323** [comment]
@bpasero 

**MyProject.code-workspace**

```
{
"folders": [
	{
		"path": "D:\\test"
	}
],
  "settings": {}
}
```

**Comment by user3323** [comment]
@bpasero 

take a look ...

![workspaces bug](https://user-images.githubusercontent.com/24613274/42213894-af766ac6-7ec2-11e8-8163-f7e9b046bd7c.gif)

so, it turns out, that **_one workspace can contain 2 (or more) different workspaces, if the path to a workspace will differ_**

**Comment by bpasero** [comment]
Thanks, the video is helpful to understand what is going on. All UI state is associated with the path of the workspace file on disk. If the file is moved, the UI state will be dropped assuming this is a different workspace. We do this intentionally to support the case of e.g. making a copy of the workspace and opening both in separate windows.

> PS: why do we need empty "workspace" files like this? They do nothing with workspaces and files in it! That's ridiculous!

A workspace can have 0-N folders (with N 1 to many). We allow you to have a workspace without folders so that you can associate settings and UI state even in that case where you do not care about folders.

**Comment by user3323** [comment]
@bpasero  omg, as-designed.

What about this?

![image](https://user-images.githubusercontent.com/24613274/42229102-55b08360-7eee-11e8-85a8-6572d42c5b47.png)

I've recorded GIF to show you the problem, then I've closed all tabs, closed QQQ workspace, deleted it.
Opened my old workspace.
Closed VS Code.
Opened VS Code - and I've got my workspace, with ...... FOUR separate windows with Untitled files (where I was typing 11111, 22222).

Is that also **_as-designed_** feature?
I am already tired of this feature.

**Comment by jrieken** [comment]
🍿

**Comment by bpasero** [comment]
@user3323 if you have untitled files that are dirty we will restore them because they contain data from you (the user) that we cannot just ignore. We will always open editors that were dirty again when you start again. 

We might have a bug in the logic that decides how many windows to open to show these dirty files. I think currently we will open a window per (previous) workspace we had that contains untitled files.

Can you distill simpler steps how to reproduce this reliably? I have tried this:
* start with an empty window
* save the workspace to a folder "`test`" as "`test.code-workspace`"
* open 2 untitled files and make them dirty
* close Code
* delete the folder "test" (or rename it)
* start Code
* => one window opens with the 2 untitled buffers restored

**Comment by user3323** [comment]
@bpasero 

GIF:

![workspaces bug 2](https://user-images.githubusercontent.com/24613274/42264899-a80ea632-7f7a-11e8-9526-db2375344ea8.gif)

- Creating Untitled file (111111)
- Creating Untitled File (222222)
- Saving it to ZZZ (from folder mySpaces)
- ---> Open workspace (renaming mySpaces to mySpaces33)
- Opening ZZZ from mySpaces33
- Creating Untitled file (33333333333333333)
- Creating Untitled File (44444444444444444)
- ---> Open workspace (renaming mySpaces33 back to mySpaces)
- Opening ZZZ from mySpaces
- ----------> **_Close workspace_**

It should be closed and forgotten, right?

- Close VS Code.
- Open VS Code.

And you get not just your new work area, but with all those four Untitled files in 2 separate windows!

And BTW if you will close all of them WITHOUT saving - the only ones, that will be saved: 1111 and 2222 (the last chosen one)
333333333333 and 44444444444 - will be lost.
You will realize it, when you will open ZZZ from mySpaces33.
Untitled files, that had 3333333333 and 4444444444 - will be empty.

And you still think, that it is as-designed feature?

**Comment by user3323** [comment]
@bpasero  well, it's not about "many windows" problem, but is about WHY untitled files from workspace (**_that has been closed_**) open in absolutely another work area?

Why do they mix? It's totally wrong.

**Comment by bpasero** [comment]
@user3323 because these files contained changes from you (the show up as dirty). dirty files will always restore, no matter how you close the workspace or delete it. the only way to prevent that is to close these dirty files. Otherwise we would loose data that the user provided, which is a no-go.

**Comment by user3323** [comment]
@bpasero  I'm not quite sure, what you mean by "loose data". Do you mean **_lose_**?

Maybe we understand a word "workspace" in different ways.
For me "workspace" - it is something, that **_divided/separated/isolated from another work areas_**.
For you ..... I really don't know.

And, please, do not ignore my comments...

I've wrote:

> And BTW if you will close all of them WITHOUT saving - the only ones, that will be saved: 1111 and 2222 (the last chosen one)
> 333333333333 and 44444444444 - will be lost.
> You will realize it, when you will open ZZZ from mySpaces33.
> Untitled files, that had 3333333333 and 4444444444 - will be empty.

What can you say about this **_selective algorithm_**?
Why VS Code saves (anyway) 11111 and 22222, and DOES NOT save 3333 and 4444 ?..

So, it's not about windows, it's about wrong isolation.

**_Why so many windows?_**
Number of windows == number of parallel spaces of ONE workspace (when renaming folder).
It is simple as hell.

> dirty files will always restore, no matter how you close the workspace

You are wrong.
Why?

Take a look...

![wspaces - 1](https://user-images.githubusercontent.com/24613274/42275234-4a318cbe-7f98-11e8-9abc-321dd9a3b655.gif)

**_Did dirty files restore? Nope._**

And here is one more with one bug "triggering" action:

![wspaces - 2](https://user-images.githubusercontent.com/24613274/42275290-7d2f14ba-7f98-11e8-9a28-ad74ef8d6997.gif)

**_All the difference_** - that I've saved workspace by clicking "`Save Workspace As...`"

**Comment by bpasero** [comment]
@user3323 let me try to explain:
* you open an untitled file
* you write into it
* it becomes dirty indicating unsaved changes
* you quit
* you delete the workspace
* you start
* we restore the dirty changes from your previous session

This is so that we preserve changes you made to the untitled files. The same happens when you open a folder and delete it with dirty files within. It is essentially to prevent data loss for you (because a folder could be deleted by many different operations, not all triggered by you).

**Comment by user3323** [comment]
@bpasero  preventing data loss? I've created this issue, because of my huge concerns about **_data loss_**.
Because I've faced this problem.
And I'm quite sure, that many other users faced this problem, as well.
Maybe they just don't know what happened and why. And they cannot repro and describe it here.

You still don't know what to say about data loss in dirty files 3333 and 4444. (from other parallel spaces of one workspace)

And you are forcing "**_delete_**" step, only because I've said about deleting workspace.

But then, I've already realized, that it is not about deleting. Look at my last GIF. Nothing has been deleted. I've just saved my workspace with dirty files in it, closed workspace, closed VS Code, opened VS Code and ta daa!
