### ISSUE TITLE
Floating debug tool bar not properly aligned when using custom menus

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#53459]
- enable custom menus  "window.titleBarStyle": "custom"
- set the debug toolbar to floating

Notice that the debug toolbar is not properly aligned with the bottom of the tabs.

![image](https://user-images.githubusercontent.com/172399/42181795-70cdab30-7e3c-11e8-9068-affa5144c983.png)

**Comment by isidorn** [comment]
This is happening because `this.partService.getTitleBarOffset()` is returning `22px`
Which is wrong in this case, it should be `30px`
It seems like the partService [here](https://github.com/Microsoft/vscode/blob/9ab41a4464e62739fa8850d2aa312de2f72eb20d/src/vs/workbench/electron-browser/workbench.ts#L1208) should be aware if windows and custom menu is turned on
Forwarding to @bpasero and @sbatten

**Comment by isidorn** [comment]
@sbatten not sure this is a good fix. Getting the `clientRect` `height` will force a browser re-layout. And `partService.getTitleBarOffset` is called whenever quick open is shown, debug actions widget is dragged and quick open is layouted (can be very often).
Could we not instead look at the configuration service and based on that return the value like before?

fyi @bpasero

**Comment by bpasero** [comment]
@isidorn @sbatten yeah I also felt like this could be just hardcoded

**Comment by isidorn** [comment]
The current fix is fine for stable, thus pushing this out to July

**Comment by isidorn** [comment]
I just verified this works in latest insiders.

**Comment by sbatten** [comment]
@bpasero sorry wasn't sure of the impact so I did some js profiling with and without the call and didn't notice a difference in perf so I went with that to avoid hardcoding. Though this is only one of 2 places the height would be hardcoded, I would prefer something a little more dynamic. Is it an option to make the `partLayoutInfo` method public in `layout.ts` so that layout can be the source of truth?

**Comment by bpasero** [comment]
@sbatten I would add it to IPartService and then expose it from workbench.ts. Workbench can access layout.ts (and that can be public there).

**Comment by ramya-rao-a** [comment]
The milestone here is July but the fix is present in the release/1.25 branch.
Am I missing something?

**Comment by sbatten** [comment]
@ramya-rao-a  A fix is in June. A better fix is in July.
