### ISSUE TITLE
[erb] provide html instellisense in erb files

### ISSUE THREAD

**Issue by jonfer** [microsoft/vscode#53462]
- VSCode Version: 1.24.1
- OS Version: MacOS 10.13.3

Steps to Reproduce:

1. Create an html.erb file with some html in it.
2. Click in a tag, it should select the matching tag, but it doesn't

Does this issue occur when all extensions are disabled?: Yes

I really like all the features it provides, and would love to continue to use it to develop in Ruby on Rails. The problem is that not having any html support functionality makes it really hard to use, so I had to go back go Sublime Text. I'm back after some months to see if this was fixed but no luck... I tried all the erb extensions and none of them fixes this. I get this by default on Sublime Text, the code is detected as HTML (erb) and I get all the HTML features + erb syntax highlighting.

I think this should be a big priority as most Ruby on Rails developers and from other templating languages like PHP have this problem as well and makes it unuseable for web developing in these languages.

**Comment by beastdestroyer** [comment]
I agree, however for this issue, it lies. more on Pug (jade) : there isn't really any intellisense there too

**Comment by mothinx** [comment]
Is any news for this feature ?

**Comment by beastdestroyer** [comment]
@mothinx It has been added to the Backlog, meaning there is no intention to implement it. You could go ahead and learn the stuff yourself and submit a pull request, but other than that, it's unlikely in the near future for consideration, especially since this was last updates over 5 months ago

**Comment by aeschli** [comment]
Proper `.erb` support should from an dedicated language server. The HTML language features can't know of the various templating languages, and it actually shouldn't.
We have issue https://github.com/microsoft/vscode/issues/49210 to come up with way to easier teach the HTML language server about the various template syntaxes so that there's some HTML support also for html-template languages without their own full support.
