### ISSUE TITLE
Rename file refactoring opens a bunch of deleted files

### ISSUE THREAD

**Issue by amcasey** [Microsoft/vscode#53466]
Version: 1.25.0-insider
Commit: 26eb2a9af5827d71e1f65096c0ce712c5ad2740d
Date: 2018-07-02T12:37:21.268Z
Electron: 1.7.12
Chrome: 58.0.3029.110
Node.js: 7.9.0
V8: 5.8.283.38
Architecture: x64

Win10

As I've been renaming a file (app1.ts -> app2.ts -> app3.ts -> etc), VS Code has been re-opening the old, deleted versions on each iteration.

![image](https://user-images.githubusercontent.com/10508071/42189375-d6e1b9a0-7e0c-11e8-864f-ccb93d34f5b4.png)

**Comment by amcasey** [comment]
FYI @mattbierner

**Comment by amcasey** [comment]
[GH53466.zip](https://github.com/Microsoft/vscode/files/2157006/GH53466.zip)

I doubt it matters, but here's the particular project.

**Comment by mjbvz** [comment]
This is after applying the "update imports" action, correct? Do you see this if you upgrade the workspace to TypeScript@next?

**Comment by amcasey** [comment]
Yes, after updating imports.

As far as I can tell, I was running 7084e6cf473e401a1291cd637e91e9caf0b94707.

**Comment by amcasey** [comment]
Still happening in 

Version: 1.26.0-insider
Commit: 5a4eab812bd485942061f71af39f3eabc52a1035
Date: 2018-07-11T09:33:23.382Z
Electron: 1.7.12
Chrome: 58.0.3029.110
Node.js: 7.9.0
V8: 5.8.283.38
Architecture: x64

**Comment by andy-ms** [comment]
I can reproduce this with:
**a.ts**
```ts
import {} from "./a";
import {} from "./b";
export {};
```
**b.ts**: Identical to `a.ts`.
No `tsconfig.json`.

* Open a new `vscode-insiders` instance with no files open.
* Open just `a.ts`.
* Rename `a.ts` to `a1.ts` and update imports. Note this opens `b.ts` since that is updated.
* Rename `a1.ts` to `a2.ts` and update imports. A new tab `a1.ts (deleted from disk)` appears.

Looking at `tsserver.log`, it looks like we never get a close event for `a1.ts` when it is renamed, so we think it still exists alongside `a2.ts` and return edits for both.
