### ISSUE TITLE
Invalid URL results in Chrome debugging its own error handling code

### ISSUE THREAD

**Issue by czhower** [Microsoft/vscode#53558]
If launch.json specifies a URL for which a network error occurs (such as forgetting to start the web server), instead of simply displaying the error page, Chrome begins debugging its own internal code from chrome-error://.... which is used to display the page. 

Related to exception debugging. It only happens when "All Exceptions" is checked for Breakpoints, but this option is often necessary for user code to be debugged.

Of course this is easy to fix by specifying a valid URL, but instead of the actual problem being immediately obvious to the developer, the developer is sent to 2 unhandled exceptions one by one in the debugger for internal Chrome error handling code. Unless a developer connects the two dots, a lot of time can be wasted trying to determine the root cause. To me, this is akin to making an error in a configuration of a C++ or C# project and instead of being presented with the actual error, hitting a breakpoint internal to VS or the Windows Kernel.

Am using TypeScript, although I believe this will happen with normal JS as well, since because the URL is invalid no user code is ever loaded into Chrome when this happens. smartStep: true does not bypass this issue either.

Suggestion would be to ignore debugging for chrome-error:// URLs, at least by default.

**Comment by roblourens** [comment]
This has come up in the past too, but I don't really want to special-case `chrome-error://` URLs because I don't know what other situations they might come up in, and I don't want to hide a useful error. In general I just try to match whatever chrome devtools does in these situations, and they also will end up paused in the chrome-error script.

Also this won't happen by default, only if the user has enabled breaking on caught exceptions.

So I'll leave this alone for now.
