### ISSUE TITLE
Markdown file in-link can't skip right when there are some Chinese punctuation

### ISSUE THREAD

**Issue by imhuay** [Microsoft/vscode#53590]
- VSCode Version: 1.24.1
- OS Version: win 10 latest

```
<!-- TOC -->

- [test，test](#testtest)  <!-- work wrong -->
- [test,demo](#testdemo)  <!-- work right-->

<!-- /TOC -->

## test，test
## test,demo
```
When use `Ctrl+right click`, it has no reply.
If change the `，` to `,`, it can work right.

However, it can work well at Github, so I treat it as a BUG.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by mjbvz** [comment]
Root cause: We remove known punctuators when slugifying headers. `，` is not included. Fix would be to use the `puctuator` unicode character class on [this line](https://github.com/Microsoft/vscode/blob/bd953248ad6a8e2f8896bfb78b3ae40e0fd47426/extensions/markdown-language-features/src/slugify.ts#L26) instead of a hardcoded list. However this is not supported in our current node version

**Comment by imhuay** [comment]
So this problem will not be fixed recently？

**Comment by mjbvz** [comment]
If you want to submit a PR that makes it so we correctly handle this one character please do so. Here's the relevant code again: https://github.com/Microsoft/vscode/issues/53590

**Comment by imhuay** [comment]
I'm not good at JS. So all I need to change is that line?

**Comment by imhuay** [comment]
Thanks for receive this PR.
I just looked at it again. However, it seems lack some English punctuation such as` \"`.
