### ISSUE TITLE
[angular][chrome]Debugging not work with main.js in root folder

### ISSUE THREAD

**Issue by MarekMaslanka** [microsoft/vscode#53602]
- VSCode Version: 1.24.1
- OS Version: Ubuntu 18.04

Steps to Reproduce:

1. Follow official tutorial from: [https://code.visualstudio.com/docs/nodejs/angular-tutorial](https://code.visualstudio.com/docs/nodejs/angular-tutorial)
2. Create empty file main.js in root project folder.
3. Launch example project using standard cmd: "ng serve" and launch debugging using Google Chrome browser.

When root project folder contain main.js even empty or not then VC can't bind breakpoint.

**Comment by roblourens** [comment]
When you have a `main.js` in the root, and `"webRoot": "${workspaceFolder}"`, then it's telling the debugger that `http://localhost/main.js` is that empty main.js. Angular is bundling the main file and serving it as `http://localhost/main.js`.

webRoot here isn't totally necessary but it's used in resolving webpack's special sourcemap patterns. I could change this to avoid having to use webRoot but I can't decide if this is a totally valid case. What are you trying to do with `main.js`, will it conflict with angular's main.js at all?

You can work around this by removing `webRoot` and setting `sourceMapPathOverrides` to the defaults with workspaceFolder instead of webRoot, like

```
{
    "version": "0.2.0",
    "configurations": [{
        "type": "chrome",
        "request": "launch",
        "name": "Launch Chrome against localhost",
        "url": "http://localhost:4200",
        "sourceMapPathOverrides": {
            "webpack:///./*": "${workspaceFolder}/*",
            "webpack:///src/*": "${workspaceFolder}/*",
            "webpack:///*": "*",
            "webpack:///./~/*": "${workspaceFolder}/node_modules/*"
        }
    }]
}
```

**Comment by MarekMaslanka** [comment]
I care about this because in some/many (don't know exactly) Angular + electron tutorials use this file.
For me when I'm googling "angular electron example" first 3 tutorials links use main.js in root.
I also found workaround for these tutorials as rename this file to index.js.

**Comment by roblourens** [comment]
I see. Yeah I can fix this on the chrome extension's end.

**Comment by roblourens** [comment]
Closing this as it doesn't seem to have had much traffic or dupes filed. But the sourceMapPathOverrides defaults could probably be reworked in the future.
