### ISSUE TITLE
creating snippet - format-condition doesn't work

### ISSUE THREAD

**Issue by csaar95** [Microsoft/vscode#53617]
- VSCode Version: 1.25.0-insider - Commit: 0f080e5267e829de46638128001aeb7ca2d6d50e
- OS Version: Microsoft Windows [Version 10.0.17134.112]

Steps to Reproduce:

1. Creating a custom snippet
```json 
  "dummy": {
    "prefix": "dummy",
    "description": "testing regex",
    "body": [
      "#\t${TM_LINE_NUMBER/(10)/${1:?It's:It's not}/} line 10"
    ]
  },
```
2. Using the snippet

This dummy snippet should write
`#	It's line 10` in line ten and
`#	It's not line 10` if not. Isn't it?
Instead of *It's not*, I receive the current line number (in this example).
The usage of `${1:-Its'not}` also doesn't work.

[Link to Grammar](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_grammar)

Does this issue occur when all extensions are disabled?: Yes

**Comment by itamark** [comment]
Hey @jrieken not sure what the appropriate solution is yet - but the issue seems to be here:
<img width="406" alt="screen shot 2018-07-07 at 2 53 16 am" src="https://user-images.githubusercontent.com/1757393/42404369-0748f824-8191-11e8-9c4c-5934a0a3c88d.png">

value is "11" and the regex is /10/ - which means the callback in the second arg of `replace` never happens, and the line number is never reformatted - so it falls through as "11" and the result is "11 line 10".

I'm not very familiar with the snippet feature - does a syntax exist that does something like a regex `test` in the snippet grammar?

**Comment by jrieken** [comment]
YEah, I have debugged to the same point. Unsure yet, needs some thinking. You can always uses `exec` but that makes things more complex...
