### ISSUE TITLE
Recommended Extensions shows already installed extensions.

### ISSUE THREAD

**Issue by Scroul** [Microsoft/vscode#53646]
- VSCode Version: 1.25.0
- OS Version: Windows 10, version 1709, OS Build 16299.492

Steps to Reproduce:

1. Open extensions
2. Look at recommended extensions

![extensions](https://user-images.githubusercontent.com/6592815/42361153-377e1064-80ed-11e8-99e8-f7d8bf311d68.PNG)

I hope i post this at the correct place.
I find that showing already installed extensions in recommended extensions is not how it is intended to work.

**Comment by chadunit** [comment]
Same issue for me in 1.25.0; occurs after issuing Reload Window command.

Also, hovering over the already-installed extension (even in the Enabled section before the reload) gives an unnecessary "This extension is recommended..." tooltip.

![vscode-recommended3](https://user-images.githubusercontent.com/25489524/42407589-ec4922bc-8184-11e8-8016-d84c35e26341.gif)

**Comment by ramya-rao-a** [comment]
Thanks for reporting @Scroul and @chadunit!
We will include the fix in the recovery build.

**Comment by ramya-rao-a** [comment]
Steps to verifier:
- Load a workspace with workspace recommendations
- Open a C# or Go file so that you get a recommendation for either showing up in the extensions view. Install one of them
- On reload, the recommended extension you just installed shouldnt be shown in the recommended section. Check the same in stable 1.25.0. You will see this extension show up both in "Enabled" and "Recommended" sections
