### ISSUE TITLE
Customizable Titlebar Buttons

### ISSUE THREAD

**Issue by NavyAdmiral** [microsoft/vscode#53650]
Atom already offers this.
Example from Atom before:
![image](https://user-images.githubusercontent.com/40662484/42361717-e6aab35e-8100-11e8-9704-df3c05123b95.png)
Example from Atom after:
![image](https://i.github-camo.com/11225c59a0aacc69238290d7706d7266e3525405/68747470733a2f2f692e696d6775722e636f6d2f586b456d667a422e676966)

**Comment by thedonquixotic** [comment]
Want to throw in my support for this feature.

**Comment by guledali** [comment]
@sbatten Will the be a roadmap/timeline for this feature

**Comment by thedonquixotic** [comment]
Nothing yet as far as I can tell.

**Comment by guledali** [comment]
@thedonquixotic Why not just port over the https://atom.io/packages/title-bar-replacer 
to vscode

**Comment by thedonquixotic** [comment]
That could work. Though I don't know for sure. I'm a designer who is
learning how to code so I haven't yet gotten into making extensions yet.
Soon I hope though!

**Comment by sbatten** [comment]
thanks everyone for support and feedback in this area.

@guledali currently, work in this area is focusing on ensuring the new menubar is a complete replacement for the old menubar which includes ensuring they are accessible.

**Comment by Kroc** [comment]
I don't want themes messing with something that should be consistent across the OS. By all means allow it, but provide an option so I can keep the standard control box.

**Comment by lig** [comment]
For me, this is the only show stopper to use custom title bar on Linux

**Comment by ngamradt-turner** [comment]
I have been running Ubuntu since version 10.10 as my primary OS. I am really used to having the title bar buttons on the left (even though Ubuntu recently changed their default back to the right).

If Atom already has this, I would hope it could be added to vscode soon.  It is annoying having vscode and Opera be the only two applications that have the control buttons on the right (and not match the Ubuntu theme).

I know that the custom title bar can be disabled, but then I cannot see the title bar in the new Ubuntu default theme.  If this could be added to the custom bar, then I think I would be all set.

**Comment by msalcantara** [comment]
any update about this? same issue here...

**Comment by NatsuXXG** [comment]
想要这个!

**Comment by lig** [comment]
@sbatten could you please elaborate on this issue beeing closed?

**Comment by sbatten** [comment]
@lig one of the strongest arguments for keeping this around was due to linux having the custom title bar by default and not matching the native window manager. since linux now uses the native title bar by default, this is no longer needed for making an optimal out-of-box experience and won't be prioritized.

**Comment by lig** [comment]
@sbatten does `won't be prioritized` is an equivalent for `won't fix and close`?
