### ISSUE TITLE
Add mouse chording support 

### ISSUE THREAD

**Issue by jacereda** [Microsoft/vscode#5367]
Would be nice to have acme-like mouse chording. Would be even nicer letting the user configure the preferred mouse chord actions.

http://acme.cat-v.org/mouse

**Comment by l-d-s** [comment]
I'd also be very excited about this.

**Comment by alexandrudima** [comment]
To keep the number of issues in our inbox at a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: we look at the number of votes the issue has received and the number of duplicate issues filed. Thank you for your time and understanding.

P.S. If you disagree and feel that this issue is crucial: we're happy to listen and to reconsider.
