### ISSUE TITLE
Starting VSCode in the current directory fails if using PowerShell on a network share

### ISSUE THREAD

**Issue by iUnknwn** [microsoft/vscode#53764]
Issue Type: <b>Bug</b>

When using Powershell on an unmapped network share, you cannot start VSCode using the command "code ." 

You'll get the error:
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.

There are ways to work around, but it is less fast then being able to use "start powershell here" from explorer, and then typing "code .". 

VS Code version: Code 1.25.0 (0f080e5267e829de46638128001aeb7ca2d6d50e, 2018-07-05T13:11:58.697Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.93GB (1.22GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
pascal|ale|0.11.0
matlab|Gim|0.9.0
innosetup|idl|1.0.3
restructuredtext|lex|65.0.0
python|ms-|2018.6.0
cpptools|ms-|0.17.6
csharp|ms-|1.15.2
PowerShell|ms-|1.7.0
vscode-docker|Pet|0.0.27

</details>

**Comment by iUnknwn** [comment]
Certainly - here's a screenshot of what happens when you attempt to start code on a network share:
![image](https://user-images.githubusercontent.com/1129122/42477919-ce03a872-8387-11e8-9345-040098b4f186.png)

Code then opens in C:\Windows

**Comment by the-ress** [comment]
Replacing `code.cmd` with a `code.exe` (with the functionality of `code.cmd`) could solve both this issue and #43237.

**Comment by msftrncs** [comment]
FYI, `CMD.EXE was started with the above path as the current directory.
UNC paths are not supported. Defaulting to Windows directory.` is not an error, its a warning.  The problem is that the argument `.` is then taken as something like `C:\Windows\.` which is not what was intended.

The following is needed:
```PowerShell
code.cmd (resolve-path .).providerpath
```
It could be made in to a function, in the profile (which is only available if the user has switched his execution policy from 'restricted')
```PowerShell
function codehere {
    code.cmd (resolve-path .).providerpath
}
```

Now one could just use `codehere`.

BTW, `NPM` and `GIT` (for Windows) also do not support operation on UNC paths due to also using CMD based scripts with relative paths.
