### ISSUE TITLE
Suggest widget breaks

### ISSUE THREAD

**Issue by czfadmin** [Microsoft/vscode#53773]
Issue Type: <b>Bug</b>

The editor's smart prompts overlap and cannot be displayed properly.
Same as the one shown in the screenshot below.But when i reload window or reopen the VS Code ,this situation will disappear.
 

VS Code version: Code - Insiders 1.26.0-insider (bd953248ad6a8e2f8896bfb78b3ae40e0fd47426, 2018-07-06T05:17:37.386Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.88GB (1.26GB free)|
|Process Argv|D:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.9
dart-code|Dar|2.15.0
flutter|Dar|2.15.0
tslint|eg2|1.0.33
code-runner|for|0.9.3
Kotlin|mat|1.6.0
vscode-cosmosdb|ms-|0.8.0
vscode-language-pack-zh-hans|MS-|1.25.3
python|ms-|2018.6.0
vscode-ai|ms-|0.1.9
azure-account|ms-|0.4.1
cpptools|ms-|0.17.6
csharp|ms-|1.15.2
Go|ms-|0.6.84
js-atom-grammar|ms-|0.1.14
jscs|ms-|0.1.9
mono-debug|ms-|0.15.8
PowerShell|ms-|1.7.0
typescript-javascript-grammar|ms-|0.0.42
vetur|oct|0.12.5
java|red|0.28.0
vscode-yaml|red|0.0.13
rust|rus|0.4.6
vscode-arduino|vsc|0.2.17
vscode-java-debug|vsc|0.10.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.7.0
vscode-maven|vsc|0.9.0
JavaScriptSnippets|xab|1.7.0

(1 theme extensions excluded)

</details>

![3](https://user-images.githubusercontent.com/13393959/42408739-2c0d067e-8203-11e8-9777-68c389b1ef87.png)

![4](https://user-images.githubusercontent.com/13393959/42408741-34946332-8203-11e8-810d-83f665bbf29c.png)

![5](https://user-images.githubusercontent.com/13393959/42408743-381b7374-8203-11e8-8be8-2bbbfb483147.png)

**Comment by joaomoreno** [comment]
Can you reproduce this issue? What are the steps?

**Comment by czfadmin** [comment]
@joaomoreno 
I may not be able to reproduce this problem.This happend by chance,and it disappeared when i reloaded window or restarted the VS code. But I have not encountered this problem in the latest version .

**Comment by joaomoreno** [comment]
Alright, let me know if you encounter it again.

**Comment by czfadmin** [comment]
Alright.

**Comment by joaomoreno** [comment]
@Microsoft/vscode This was the first occurrence of an issue due to different semantics between WinJS and cancellable native promises.

Basically, the execution of `then` callbacks is different in a cancel situation:
- When using WinJS promises, the `then` callbacks will be called in the same execution frame as `.cancel()`. Once `cancel` returns, all `then` callbacks that were attached to that promise have executed.
- When using cancellable native promises, the `then` callbacks will be called in the next execution frame as `.cancel()`. First, `.cancel()` returns, the execution frame ends and all `then` callbacks will run on the following execution frames.

Please refer to the following 4 test cases which demonstrate the behavior:

https://github.com/Microsoft/vscode/commit/a486f518d62d5cbc3c46536f73c45e659f48301e

Keep this in mind when migrating to native promises.
