### ISSUE TITLE
Weird indenting placement

### ISSUE THREAD

**Issue by jurrid** [microsoft/vscode#53776]
There is some strange tab of behaviour. I set the `editor.detectIndentation` to false and still it places the cursor 1 tab off but when i press the return key the placement is spot on. Does anyone have an idea whether this is my fault or a bug?

- VSCode Version: 1.25.0
- OS Version: 10.13.3 (17D47)

![behaivor](https://user-images.githubusercontent.com/25743738/42410424-9f15120c-81e9-11e8-9fc1-3ffccf0291b3.gif)

**Comment by rebornix** [comment]
This is due to the limited architecture (regex based indentation rules and only support limited code styles), we may want to consider using formatters if they exist for indenation adjustment (if interested, we can discuss in https://github.com/microsoft/vscode/issues/19847).

For this particular issue, if the indentation rules are leading to more trouble than having no auto indent, you can set `editor.autoIndent` to `advanced` to disable the regex based indentation adjustment or use auto formatting (`editor.formatOnType`, `editor.formatOnPaste`). As we don't have an easy good-enough fix for it, we close it for now and explore better solutions through issues like (https://github.com/microsoft/vscode/issues/19847 and https://github.com/microsoft/vscode/issues/34621).
