### ISSUE TITLE
Support downloading of additional resources when installing an extension

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#53855]
Support downloading of additional resources when installing an extension

**Comment by jasongin** [comment]
We'd need to be able to filter applicability of resources based on:
 - OS
 - CPU architecture of VS Code (x86/x64)
 - Version of VS Code
 - Electron version of VS Code, for selecting prebuilt node native modules (or the VS Code version could be used as a proxy for the electron version)

**Comment by jasongin** [comment]
My comment above was assuming a declarative approach, such as an extension declaring additional external dependencies in its `package.json`.

If there is an API / command to do ad-hoc downloads then obviously that's more flexible so extensions can use any arbitrary logic to determine what to download and when. But for the specific case of downloading dependencies needed at extension startup, it's a little more work for extension developers, and maybe not as good user experience, since the extension has to indicate the download is in progress and the extension is not functional until that finishes.

**Comment by sandy081** [comment]
Closing in favour of #59112
