### ISSUE TITLE
Extension broke after 1.25 update (provideTas

### ISSUE THREAD

**Issue by calebporzio** [Microsoft/vscode#53879]
- VSCode Version: 1.25.0
- OS Version: Mac OSX Sierra 10.12

I built/manage an extension called "Better PHPUnit"
https://github.com/calebporzio/better-phpunit

It relies on providing a task to execute.

After the 1.25.0 update, everyone is now getting this screen:
![image](https://user-images.githubusercontent.com/3670578/42457820-756c4f32-8366-11e8-89a4-7953d4f84334.png)

I have seen other issues related to this. It seems the problem has to do with not setting a "taskDefinitions" contribution point in the package.json. However, I attempted doing this:
```
"taskDefinitions": [
            {
                "type": "phpunit",
                "required": [
                    "task"
                ],
                "properties": {
                    "task": {
                        "type": "string",
                        "description": "the task to execute"
                    }
                }
            }
        ],
```

And it didn't work/help.

Because the taskDefinitions doesn't really have documentation - I'm kind of at a loss and in the dark.

As of right now, the extension is completely broken. Any help would be AMAAAAZZZING!!

Thanks for all your hard work

**Comment by dbaeumer** [comment]
@calebporzio I apologize for the swirl this is causing. But I was somehow under the impression that every task provider has a task definition since otherwise some other features don't work either like referencing the task from a launch.json or redefining it in the tasks.json. And this didn't

```
await vscode.commands.executeCommand('workbench.action.tasks.runTask', 'phpunit: run');
```

work under a French locale. But I should have thought about extensions not declaring a task definition and should have provided a grace period of fixing this. 

I cloned your code and adding the following to the contributes section of the package.json made the task show up again:

```
    "contributes": {
        "taskDefinitions": [
            {
                "type": "phpunit",
                "required": [
                    "task"
                ],
                "properties": {
                    "task": {
                        "type": "string",
                        "description": "The task to execute"
                    }
                }
            }
        ],
        ...
    }
```

![capture](https://user-images.githubusercontent.com/1931590/42488366-737ade88-8405-11e8-8c6c-7194da7133c5.png)


I don't have all the php stuff installed so I am not sure if something else need to change. With the above addition what failure do you see. Is there anything in the developer console of the developer tools (e.g Help > Toogle Developer Tools)?

**Comment by calebporzio** [comment]
Perfect! Thanks for taking the time! Fixed the extension as far as I can tell right now.

**Comment by dbaeumer** [comment]
Thanks for pushing a new version. I also added some backwards compatibility code for the recovery build that should help mitigating this for now (see https://github.com/Microsoft/vscode/issues/53960). There are more extensions hit by this.

**Comment by calebporzio** [comment]
Great, thanks!
