### ISSUE TITLE
Sometimes TAB do strange action when use  a fullwidth symbols.

### ISSUE THREAD

**Issue by kazupi** [microsoft/vscode#53919]
Hi, my name is kazupi.
My English is not very good, but I'll be happy if we can understand each other.

- VSCode Version:
バージョン: 1.25.0
コミット: 0f080e5267e829de46638128001aeb7ca2d6d50e
日付: 2018-07-05T13:11:58.697Z
Electron: 1.7.12
Chrome: 58.0.3029.110
Node.js: 7.9.0
V8: 5.8.283.38
Architecture: x64

- OS Version: Windows7 Professional

Steps to Reproduce:

1.in Notepad
Paste this string in VScode.
(Blank is one TAB.)

![intexteditor](https://user-images.githubusercontent.com/41029949/42484748-6e19e4e6-842f-11e8-924c-d7a7f9e5b905.png)
```
aaaaaaaa	abc
ああああ	abc
／―＼―	abc
○○○○	abc
゛゜○｀	abc
？？？？	abc
＃＃＃＃	abc
￥￥￥￥	abc
（（（（	abc
＝＝＝＝	abc
～～～～	abc
ＡＡＡＡ	abc
≒≒≒≒	abc
```

2.in VScode
Not equal.

![invscode](https://user-images.githubusercontent.com/41029949/42484753-740a638a-842f-11e8-90fd-9b6ca11dda26.png)

other.My VScode settings
{
    "editor.fontFamily": "MS Gothic",
    "editor.insertSpaces": false,
    "editor.detectIndentation": false,
    "editor.tabSize": 8
}

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by nekketsuuu** [comment]
You can use the following string to copy & paste:

```
aaaaaaaa	abc
ああああ	abc
／ー＼ー	abc
○○○○	abc
゛゛○｀	abc
？？？？	abc
＃＃＃＃	abc
￥￥￥￥	abc
（（（（	abc
＝＝＝＝	abc
〜〜〜〜	abc
ＡＡＡＡ	abc
≒≒≒≒	abc
```

@kazupi Correct me if the string contains wrong letters.

**Comment by kazupi** [comment]
Sorry ,
This is my pasted string

```
aaaaaaaa	abc  
ああああ	abc
／―＼―	abc
○○○○	abc
゛゜○｀	abc
？？？？	abc
＃＃＃＃	abc
￥￥￥￥	abc
（（（（	abc
＝＝＝＝	abc
～～～～	abc
ＡＡＡＡ	abc
≒≒≒≒	abc

```

**Comment by kazupi** [comment]
Hi, Thanks for the reply.
This is my settings.

{
    "editor.fontFamily": "MS Gothic",
    "editor.insertSpaces": false,
    "editor.detectIndentation": false,
    "editor.tabSize": 8
}

**Comment by alexandrudima** [comment]
I have investigated this. The reason is a heuristic we do, we look at characters and based on their character codes try to infer if they are wide or not. In this case, there are multiple characters, like `―` [Unicode Character 'HORIZONTAL BAR' (U+2015)] which we don't consider wide. But `MS Gothic` will render that character as a wide character. Other fonts will not...

So this is just hitting the limits of what we can do by just looking at character codes as an heuristic for aligning tab rendering.
