### ISSUE TITLE
Random Crash while typing on Mac

### ISSUE THREAD

**Issue by rodolphito** [Microsoft/vscode#53928]
Sorry if this is the wrong place to submit these, but I just had this horrible crash on High Sierra/iMac Pro. I was just typing, no fancy stuff involved at all, when it suddenly stopped being responsive. I lost mouse input shortly after, Cmd+Opt+Esc did not do anything, I completely lost input to the computer. I tried several things over the course of a couple minutes, and then I decided to simply reboot the machine because it was frozen beyond all recovery. Here's the crash report, if its just some random occurrence feel free to close this.

[Code Helper_2018-07-09-224150_Rodols-iMac-Pro.txt](https://github.com/Microsoft/vscode/files/2179032/Code.Helper_2018-07-09-224150_Rodols-iMac-Pro.txt)

Thanks!

**Comment by bpasero** [comment]
@rodolphito is this reproducible for you somehow?

**Comment by rodolphito** [comment]
No, I can not reproduce.

**Comment by bpasero** [comment]
Ok let me know if you can.

**Comment by superamadeus** [comment]
I just rebooted from this happening to me as well. I was editing a typescript file in a medium/large sized angular project. I was just typing in a string (`route: 'blah'`) and my entire mac froze up. Couldn't quit, couldn't access the apple menu, couldn't interact with anything. Had to power off my mac with the power button.

Other than this problem, I've been having a lot of problems with VSCode intellisense being unbearably slow, and seemingly using more CPU (based on the Fanny app reporting a higher CPU temp on average while using my daily VSCode workflow that hasn't changed otherwise).

**Comment by bpasero** [comment]
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by superamadeus** [comment]
Sure, I'll be on the lookout for logging. You may already know this, but I've heard some mention it could be related to communication to TSServer. Related issues:

 - Microsoft/TypeScript#25435 
 - Microsoft/Typescript#19458

**Comment by bpasero** [comment]
@superamadeus so it does not reproduce with other file types?

**Comment by superamadeus** [comment]
I can't get it to reproduce under any conditions. Sorry, just to clarify, I was speaking to the performance issues in general, which in my case I only notice with TS files.

**Comment by bpasero** [comment]
Can you follow this wiki and post the results back here to understand more about why performance is so bad for you: https://github.com/Microsoft/vscode/wiki/Performance-Issues

Thanks!
