### ISSUE TITLE
Tree/List commands should only be enabled when they can execute

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#53950]
The `WorkbenchTree` in combination with the `IListService` and its commands bind some keys overly aggressive. For instance, `ArrowLeft` and `ArrowRight` always try to collapse/expand elements in a tree even though there is nothing to collapse or `Escape` tries to clear the selection when there is no selection. The consequence is that those keys cannot be used for other commands when a tree is focused (like the breadcrumbs).

**Comment by bpasero** [comment]
Maybe one way out is to add more context keys depending on:
* current element can be expanded or not
* there is an element selected in the tree

This would result in quite a bit of context key changes I guess when navigating around the key.

**Comment by jrieken** [comment]
Yeah, more context keys is always the answer to this and I wouldn't be worries about them changing

**Comment by joaomoreno** [comment]
What to do here?

**Comment by bpasero** [comment]
@joaomoreno the tree/list needs to expose some additional APIs so that the WorkbenchTree/List can set some appropriate context keys properly. E.g.:
- is first/last element
- is expanded/collapsed

**Comment by OliverJAsh** [comment]
Two other issues have been marked as duplicates of this one: https://github.com/microsoft/vscode/issues/58318 and https://github.com/microsoft/vscode/issues/98321 I was also about to file a new issue until I found this.

Until this is fixed the breadcrumbs are extremely difficult to use for keyboard users. Unfortunately, 
[the workaround mentioned here](https://github.com/microsoft/vscode/issues/98321#issuecomment-633851011) is var from sufficient because once the breadcrumbs list is open, there is no way to return focus to the breadcrumb menu.
