### ISSUE TITLE
bypass trash when deleting file (from context menu)

### ISSUE THREAD

**Issue by twig** [Microsoft/vscode#53996]
https://github.com/Microsoft/vscode/issues/9354 is _almost_ there

it's possible to hold shift+del on the keyboard to bypass the bin, but my first attempt failed because I held shift while clicking the context menu "delete".

holding shift while clicking the menu still prompts the recycle bin option.

![image](https://user-images.githubusercontent.com/59689/42542937-a5ef1180-84ec-11e8-974d-322ed0dbe3f7.png)

**Comment by isidorn** [comment]
You need to hold down 'alt' or 'shift' before invoking the context menu. We can not support the changing of commands while the context menu is already rendered since electron freezes everything while showing the context menu. Closing as no immediate plans to fix this in the near future (there is a workaround - press the key before the menu)
