### ISSUE TITLE
Menu shadow should be customizable

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#54156]
I can't find a color to change the menu's shadow.

I also have a feeling the menu shouldn't have a shadown at all, since it looks really strange when you look at its top border. It will also look strange on submenus, on their left border. Should they maybe have a 1px border instead?

![screenshot from 2018-07-12 12-17-30](https://user-images.githubusercontent.com/22350/42627533-97bcb22a-85cd-11e8-86db-c293e7124c9f.png)

**Comment by bpasero** [comment]
If we have a shadow, I agree that we should make it themeable. Since we already have `widget.shadow`, we should probably just use that to begin with.

As for how the shadow looks like or should apply, I think we tweaked the shadow already a bit. The shadow should not show up to the top of the main menu bar, I agree.

@sbatten in the end we need to make sure that no CSS includes any colors. Everything must be themable, e.g.:

![image](https://user-images.githubusercontent.com/900690/42633988-4e9a0484-85e2-11e8-8d89-c80a304a75d8.png)

**Comment by eamodio** [comment]
It seems that the usage of `widget.shadow` is different than in the quickpick. Here is it set to white (as a hack)

![image](https://user-images.githubusercontent.com/641685/44233711-a1efef80-a172-11e8-9877-5bf05383ac7f.png)
![image](https://user-images.githubusercontent.com/641685/44233727-aae0c100-a172-11e8-9128-ab8055730280.png)

Now here they are when set to my real theme color:
![image](https://user-images.githubusercontent.com/641685/44233778-cea40700-a172-11e8-9a73-23c01a715234.png)
![image](https://user-images.githubusercontent.com/641685/44233755-c0ee8180-a172-11e8-8599-e18b2ea36a20.png)

While it is a little hard to see, the quickpick gives a nice separation border, but with the menus it is basically invisible.
