### ISSUE TITLE
Unused imports aren't detected properly

### ISSUE THREAD

**Issue by trsdln** [Microsoft/vscode#54165]
- VSCode Version: 1.24.1
- OS Version: Macos High Sierra 10.13.5 

Steps to Reproduce:

1. create empty project
2. `yarn add fluture`
3.  create new file and put this code:

```js
import F from 'fluture';

F.of('test').fork(console.log, console.error);
```

Actual result:

`fluture` is marked as unused:

![image](https://user-images.githubusercontent.com/6911494/42630851-ff8b0c7c-85e0-11e8-8f34-f08c57b24e8f.png)

Expected result:

`fluture` import should be marked as used.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by mjbvz** [comment]
I'm having trouble reproducing this issue. Does this happen in specific workspace you open, or also in new empty workspace?

**Comment by trsdln** [comment]
@mjbvz I did some digging. Looks like dependencies impact this issue. Here's reproduction repo https://github.com/trsdln/vscode-used-import

**Comment by mjbvz** [comment]
Thanks. I believe that `fluture` has an incorrect `d.ts` file here. By adding `@ts-check`, we see the error:

```
'F' only refers to a type, but is being used as a value here.
```

This is because fluture's `d.ts` contains:

```ts
export default Fluture
```

with `Fluture` being an interface and not an actual instance of anything.


I suggest you open an issue to get them to fix the d.ts if this usage is valid. The following code also works correctly:

```js
//@ts-check
import util from "util";
import * as F from "fluture"; 

F.of("test").fork(util.inspect, console.log);
```
