### ISSUE TITLE
How vscode knows about the server port no of debug adapter when it itself starts debug adapter ?

### ISSUE THREAD

**Issue by tarunbansal11** [Microsoft/vscode#54173]
As I know, there are following two ways to run debug adapter. My confusion lies in the second way.

1. Run debug server explicitly on some port no and specify this port no in launch.json as value of "debugServer" attribute. In this case vscode connects on this port no.  Debug server is spawned as a separate process and the code to spawn it is written typically in extension.

2. Debug adapter is started by vscode itself. Debug adapter's executable is mentioned in package.json as the value of "program" attribute under "debuggers" section.

Now my question is regarding second point. vscode is the client of Debug adapter (which is DAP server). vscode must know the port no of the server started within the debug adapter in order to connect to it and later send request. 

Now suppose if my debug adapter is creating a server on port 9990, than how should I tell vscode to use 9990 as port no to connect to debug adapter which will be started by vscode itself.

**Comment by weinand** [comment]
@tarunbansal11 in the second case VS Code talks to DAP via stdin/stdout, it doesn't use a port.

**Comment by tarunbansal11** [comment]
Thanks @weinand.
So it means in the second case I can not use same executable for debug adapter which I use in first case. what changes I need to make in the code of debug adapter in second case than first case.

I saw the code of mock debugger extension. In the first case, debugger adapter is started with --server =4711 and we mention this port no (4711) in "debugServer" in launch.json. 
In the second case, the same debugger adapter is used by VScode as mentioned in package.json as following -
		"debuggers": [
			{
				"program": "./out/debugAdapter.js",
				"runtime": "node",
                       }.................
                      ...................
                     ]

**Comment by weinand** [comment]
It is very simple to support both modes from the same DA executable.

For instance if you are basing your DA on the vscode-debugadapter node module, then the resulting DA supports both modes automatically: if the DA is launched without arguments then it communicates via stdin/stdout. If an argument `--server=1234` is passed, it communicates via a socket.

The code for both cases is here:
https://github.com/Microsoft/vscode-debugadapter-node/blob/7b97e42f1ed19777044850c5f18bfce8e21fc598/adapter/src/debugSession.ts#L348-L369

The socket mode is very helpful for debugging the DA: you can just run the DA as a server inside the debugger and VS Code will connect to it instead of always a launching a new instance of the DA.
See https://code.visualstudio.com/docs/extensions/example-debuggers#_development-setup-for-mock-debug.

**Comment by tarunbansal11** [comment]
Now I see, thank you very much @weinand  for your quick resolving my doubt.

One suggestion - It would be nice if this information is documented somewhere though there is a high probability that It is already documented and I missed it.
