### ISSUE TITLE
Sticky folder path in Explorer

### ISSUE THREAD

**Issue by mattxo** [Microsoft/vscode#54206]
**Issue:** In Explorer, if you have a project folder with many files in it, you can't see which folder those files are in without scrolling up.

![image](https://user-images.githubusercontent.com/6966145/42659724-5309a4ae-8653-11e8-99ec-c8100cda9452.png)

**Suggestion:** Show the folder path at the top of the project files viewport (or make the folder "sticky") if the folder containing the first file in the list is not visible due to scrolling

![image](https://user-images.githubusercontent.com/6966145/42659817-a7b64b1a-8653-11e8-9ad5-23fda24fe71e.png)

**Comment by atomdmac** [comment]
+1 I routinely have workspaces that have multiple folders with deep trees.  Without the proposed functionality, the "show the current file in the explorer tree" functionality can be pretty disorienting.

**Comment by 32graham** [comment]
I would guess that most JavaScript developers have spent time scrolling up just to collapse the `node_modules` folder. I think this would be a great feature and _might_ not be terribly difficult given that CSS `position: sticky` exists.

Might be best implemented as an extension though 🤔

**Comment by waldyrious** [comment]
If anyone knows of an extension that does this (also for search results), I'd appreciate it! This looks like it should be a feature of tree widgets everywhere, not just the explorer sidebar.

**Comment by ExpHP** [comment]
I often dream of a feature like this.  I just wish that all ancestor directories of my current location in the file pane were sticky so that I could just click on the collapse button of the one I want to get out of.

However, it turns out there is another solution:

![image](https://user-images.githubusercontent.com/1411280/94098026-b133d380-fdf5-11ea-90be-a4f6c6ff562f.png)

If you click on any of the files in the folder and then press the left arrow key, it will jump out to select the containing folder.

![image](https://user-images.githubusercontent.com/1411280/94098061-c577d080-fdf5-11ea-92e9-0a2062afa529.png)

And since your hand is already there, it's worth noting that you can press the key a second time to close the folder.

**Comment by ericvicenti** [comment]
This feature would be super useful to visually understand context inside your file structure. (and yes to escape the node_modules list)

Meantime I'm gonna try the @ExpHP workaround

**Comment by kealjones-wk** [comment]
Why was this closed as out of scope?

**Comment by Yufan121** [comment]
This will be super useful. Upvote!

**Comment by waldyrious** [comment]
This has finally been [implemented in v1.85](https://code.visualstudio.com/updates/v1_85#_preview-features)!! It's still experimental so you need to manually set  `workbench.tree.enableStickyScroll: true` in the settings, but it does exactly what was asked here (and for all tree views :))
