### ISSUE TITLE
Change `Match Whole Word` button to only contain lowercase letters

### ISSUE THREAD

**Issue by jeffishish** [microsoft/vscode#54275]
Currently, the `Match Whole Word` looks very similar to the `Match Case` button - both contain a small sample of mixed-case letters. This means users (or at least this user!) often has to think about which button does what each time the button is clicked.

It would be clearer if the `Match Whole Word` button only had lowercase (or uppercase) letters because then case sensitivity wouldn't be implied by the fact that multiple cases are present in the image.

![image](https://user-images.githubusercontent.com/15920350/42710807-71fb587a-869a-11e8-99b3-a27eafee4bbb.png)

**Comment by guymguym** [comment]
I agree! very confusing.
Also I don't understand why Whole-Word doesn't have a full rectangle border?? 
These 3 borders are actually making me doubt that this will pick the entire word.

**Comment by andycastles** [comment]
I was glad I found this issue as I was just about to create a new one with just this request. I also think that the whole word icon should not have any upper case letters, all lowercase so that you are only concentrating on the lines. I also suggest that only having an underline, not an overline, Not sure if that would be clearer but I feel that the overline is used to draw attention to letters which are different height, which for a lot of letters usually is the difference between lower and upper case letters. I feel that just an underline would more clearly highlight the matching of the full word. Thanks.

**Comment by mohd-akram** [comment]
Any update on this? I have to do a double-take each time.

In addition to @andycastles's suggestion, worth trying out two lines on the left/right instead of overline/underline, since that's technically what we're looking for.

**Comment by swrobel** [comment]
Just coming here to say I can never remember which one is the "match case" icon because they both contain mixed case. I was going to file an issue, but I'm glad to see I'm not the only one confused here.

**Comment by jeffishish** [comment]
Today will be a good day!
