### ISSUE TITLE
Allow for moving panels

### ISSUE THREAD

**Issue by scriptcoded** [Microsoft/vscode#54290]
With the addition of the new Outline view, the explorer is getting rather clogged. Having _open editors_, _project_, _outline_ and additional things such as _maven projects_ all open at the same time makes it all pretty hard to interact with. Splitting the panel and allow for moving individual parts to different locations in the window would give more space to the different parts. Personally, I'd love to have the outline view on the right side of the editor :)

**Comment by TomSputz** [comment]
Though I've seen the developers speak against it due to keeping vscode 'recognizable', I am very much in support of having a more flexible GUI - The current interface using the Activity Bar can be very clunky once you are into a project and only need one pane from each of the Views, it would be amazing to be able to place these around the window freely

I think inspiration should be taken from CC, which has been working on a similar system for years, for example in Photoshop - each pane has a name and icon to identify them, and are designed to be fully resizable, so that they can be placed anywhere - as far as I know this is the same in vscode, even if many extensions default to a list-style layout.

Each tab group can be displayed in one of two modes - either expanded
![image](https://user-images.githubusercontent.com/25057690/42733740-b525426a-882e-11e8-8781-5afa5974ecd7.png)
Giving full access to the pane at all times, or not -
![image](https://user-images.githubusercontent.com/25057690/42733745-d14f15d8-882e-11e8-9001-fd644f45d1a1.png)
, allowing it to take up less space, until it is needed, at which point the tab group is displayed adjacent to the list


These tabs can actually be undocked from the main window, creating popouts containing any tabs needed - Imo this would be a great way to implement #10121 once we get over the multi-process thing

Problems that I can see coming up around this:
- Probably needs complete rewrite to the Views system. (Main reason I see not to do it)
- The Activity Bar has admittedly become a staple of VSCode, the devs may want to keep it that way, in which case we could have a scaled down version allowing for user made Views to add to the Activity Bar, which would contain any set of panes needed (I couldn't find an issue for this, but I'll add it to this post if someone can find it)

**Comment by TomSputz** [comment]
@isidorn Sorry to be a pain, but what issue is this a dupe of? I'd love to give it my support but just can't find it

**Comment by isidorn** [comment]
https://github.com/Microsoft/vscode/issues/50363
And some other from here https://github.com/microsoft/vscode/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+label%3Afeature-request+label%3Aworkbench-layout+
