### ISSUE TITLE
Paste is not performing proper indentation

### ISSUE THREAD

**Issue by jeffsaremi** [Microsoft/vscode#54326]
Why is paste so stupid on VS Code? Has anyone in the development team ever used any other Visual Studio edition or VI or any smart editor ever?
This is the most basic functionality of a code editor and it has to behave like this?
When I paste a block of code in a new line, the editor must make necessary adjustment and corrections to the indentation of what i just pasted so that the code formatting still looks sane.
For proper examples please use Visual Studio (non Code version) and see the difference.

**Comment by TomSputz** [comment]
When submitting the report, the bug report field would've asked you to:
```
<!-- Please search existing issues to avoid creating duplicates. --> 
```
and
```
Also please test using the latest insiders build to make sure your issue has not already been fixed: https://code.visualstudio.com/insiders/
```
so, considering https://github.com/Microsoft/vscode/issues/25260#issuecomment-311145315 can be found on the first page of googling `vscode paste indent`, I'm going to have to guess you didn't follow any of the guidelines, and this issue should be closed

**Comment by distinctdan** [comment]
I'm annoyed by the same thing, and the issue reference as a supposed duplicate is closed, over a year old, and doesn't appear to have resulted in a fix. The pasting really is really bad, is this currently being worked on? I do see a lot of other issues related to pasting though.

As an example, paste anything in the first line of a switch's case statement. It incorrectly aligns it with the case instead of the case's body:

    // Before paste
    case Enums.Foo.Bar:
        doStuffB();
        break;

    // After paste
    case Enums.Foo.Bar:
    doStuffA();
        doStuffB();
        break;

**Comment by jeffsaremi** [comment]
Actually, most of the issues may be related to #54352
I'd revisit this only after the other issue is taken care of.
