### ISSUE TITLE
ignore .ignore is not a function

### ISSUE THREAD

**Issue by T0toro** [Microsoft/vscode#5433]
- VSCode Version: 1.0.0
- OS Version: Ubuntu 15.10

Steps to Reproduce:

1. I try edit any .js file
2. When i try save file, i take a error:

![vs_bug](https://cloud.githubusercontent.com/assets/4591518/14596508/5ab2c422-0560-11e6-939d-a3b5567919a0.png)

Editor clean without any extensions.

**Comment by dbaeumer** [comment]
@bpasero starting with you since it is save. I search for Ignore function but wasn't successful.

@T0toro do you have any additional plugins installed?

**Comment by T0toro** [comment]
> @T0toro do you have any additional plugins installed?

no.

**Comment by bpasero** [comment]
The only place I found a ".ignore" is in https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/comment/common/lineCommentCommand.ts#L139

Moving to @alexandrudima thereby, though I am not sure if this is really being hit.

@T0toro 
Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions`

**Comment by T0toro** [comment]
@T0toro 
Can you try to run VS Code without extensions? From the command line, execute: code --disable-extensions

i try but in not help.

**Comment by alexandrudima** [comment]
@T0toro From your screenshot, I see at the bottom you might be using a vim emulation extension.

Since our codebase does not contain any invocation for a function called "Ignore" I believe it is an extension you have installed that throws this error.

Can you please share with us the list of extensions you have installed: `F1 > Extensions: Show installed extensions`

**Comment by alexandrudima** [comment]
No info => closing
