### ISSUE TITLE
FIle explorer issue

### ISSUE THREAD

**Issue by david-mcafee** [Microsoft/vscode#54426]
Issue Type: <b>Bug</b>

The file explorer often doesn't update with the most recent changes. For instance, I rebased, and after rebasing, a folder and all the files it contained were missing. I restarted VS Code, and they were there.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:33:29.235Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|7, 10, 10|
|Memory (System)|8.00GB (0.07GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
snapshot-tools|asv|0.0.7
gitignore|cod|0.5.0
vscode-svgviewer|css|1.4.4
vscode-eslint|dba|1.4.12
gitlens|eam|8.5.0
tslint|eg2|1.0.33
prettier-vscode|esb|1.5.0
atom-keybindings|ms-|3.0.4
vsliveshare|ms-|0.3.395
debugger-for-chrome|msj|4.8.0
LiveServer|rit|5.1.1
code-settings-sync|Sha|3.0.0
vim|vsc|0.15.0
vscode-import-cost|wix|2.7.2

(1 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
VS Code is using different file watching strategies depending on your OS and your setup. 

**First thing to check:**
* [ ] I verified that the issue still reproduces in our insiders version (https://code.visualstudio.com/insiders/)
* [ ] I verified that this issue is happening outside of a `node_modules` folder. Our file watcher ignores this folder!

**To find out more about this issue, please first answer this:**
* [ ] What OS are you on
* [ ] Does this happen from an empty workspace, a single-folder workspace or a multi-root workspace?
* [ ] Do you have `files.useExperimentalFileWatcher: true` configured in settings?
* [ ] What is your configured `files.watcherExclude` setting?

**Then please answer the following depending on your setup:**
* [ ] It reproduces with any folder or workspace you open
* [ ] The files/folders you open are on your local disk and not on a network share nor a UNC drive
* [ ] The files/folders you open are not behind a symbolic link
* [ ] The folder(s) opened use the exact same casing as they are on disk
* [ ] It reproduces when I make a change to the file from another VS Code window (either from the editor or the file explorer)

**Then please attach the output of our development console**
* run `code --verbose` from the command line
* perform the action that causes you to not see the file change in VS Code
* attach the output from the console (`Help` > `Toggle Developer Tools` > `Console`)

Thanks for taking the time to fill out this questionnaire.
