### ISSUE TITLE
Allow to configure the minimal width of an editor

### ISSUE THREAD

**Issue by myfairsyer** [Microsoft/vscode#54470]
I order to efficiently use limited screen real estate I'd love to be able to decrease the editor groups' minimal width via setting.

**Comment by gamepad-coder** [comment]
This is actually my biggest inconvenience with VS Code so far.

Using Windows 10 + 150% DPI scaling + 1080p.

If I zoom in twice (with 3 editors total, the rightmost 2 reduced to their smallest width) 
then the two "resized" editors take up more than half the workspace:

<img width="960" alt="2020-05-26 12_10_57-2__Test html -  jekyll gc gh io  (Workspace) - Visual Studio Code" src="https://user-images.githubusercontent.com/65138515/82929924-1cee5880-9f4a-11ea-9d1c-1761a5626986.png">


This is a basic usability issue.

**Comment by iannacone** [comment]
+1

**Comment by kokoshneta** [comment]
This was closed three and a half years ago because it wasn’t in the immediate pipeline then.

Any update on whether it could make it into some sort of pipeline now? As it is, the minimum editor group width is **way** too wide. Why is there even a minimum width at all? It should be possible to minimise an editor group to take up no space at all. But currently, you can’t make it smaller than about 15% of the entire device width on a regular 1680×1050 laptop screen.

If actually making it customisable is too much work, at least **reduce** the hard-coded value to something more sane.

**Comment by marcusnewton** [comment]
I'd also be interested in a minimum editor width based on the number set for Word Wrap Column.

**Comment by starball5** [comment]
Related on Stack Overflow: [How can I adjust the minimal width/height of an editor group in VS Code?](https://stackoverflow.com/q/76757843/11107541)

**Comment by grandrew** [comment]
I'm wondering why no one figured how to hack this yet? I believe this could be patched & recompiled or live-patched

**Comment by fabiospampinato** [comment]
This should probably be reopened. Of all the settings that vscode provides, one for not wasting too much space with tucked away editors doesn't exist, but it probably should.

**Comment by Rahulkumarmahawar** [comment]
Ok

**Comment by idning** [comment]
+1

**Comment by wangpengfeido** [comment]
+1
