### ISSUE TITLE
я не могу форматировать код

### ISSUE THREAD

**Issue by kirya355** [Microsoft/vscode#54557]
я нажимаю shift + alt + f , ничего не работает и появляется уведомление , 
Модуль форматирования документов для файлов 'csharp' не установлен.
Как установить модуль ?
![screen](https://user-images.githubusercontent.com/41366638/42873643-2d2b424a-8a88-11e8-84aa-9c3beb7ffa61.png)

**Comment by DaFri-Nochiterov** [comment]
I think the [issues supposed to be in the English language](https://github.com/Microsoft/vscode/wiki/How-to-Contribute#discussion-etiquette) here. Also, as [contribution guide states](https://github.com/Microsoft/vscode/blob/master/CONTRIBUTING.md#asking-questions), you can answer the questions on StackOverflow, rather than creating the issues here.

Still. Your problem is that there is no C# formatter found. Quick questions for you:

- **Do you have [C# extension][csharp_ext] installed?** 
  As far as I know, there is no any built-in formatter for C#, only code highlighting, so you need to install complete C# language support with [this extension][csharp_ext].

If after installing the extension above, formatter still doesn't work:

- **Did you disable any built-in extension related to CSharp language?**
  If so, try to turn them back on. In really rare cases disabling built-in extensions may break the functionality of other extensions.

Please, post an update here if any of the steps above helped you, so the maintainers can close the issue.

If nothing helped, create the issue manually using “Справка (Help)” → “Сообщить о проблеме (Report Issue)”, it will contain useful information about your version of Visual Studio Code and list of extensions.

Thank you!

[csharp_ext]: https://marketplace.visualstudio.com/items?itemName=ms-vscode.csharp

**Comment by alexandrudima** [comment]
@kirya355 Do you have additional information?
