### ISSUE TITLE
Current line is not highlighted when text is selected

### ISSUE THREAD

**Issue by PunchyRascal** [microsoft/vscode#54573]
Issue Type: <b>Bug</b>

When selecting text, the (custom) active line background color is not used, therefore it is difficult to find the active line.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.87GB (4.19GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by alexandrudima** [comment]
This is intentional in order to avoid too much noise around the selection or in case the selection is multi-line.

Even when there is a selection, it can be found pretty easily by two hints which do not disappear:

 - The highlight in the line numbers:

![image](https://user-images.githubusercontent.com/5047891/42948375-a14ac762-8b6f-11e8-9328-659753c1c026.png)

 - The mark in the overview ruler:

![image](https://user-images.githubusercontent.com/5047891/42948390-acf3c97e-8b6f-11e8-8459-f0d07e73d109.png)

**Comment by PunchyRascal** [comment]
Well multiline selection still has one active cursor i.e. one active line that IMO should still be highlighted. How moch noise it makes is up to each user - how they set this. If I recall correctly, the default current line highlight is very subtle so probablyis not very noisy.

But I find it strange, that I select a word on a line and suddenly I don't know what line is active (you mentioned secondary cues, but they IMO don't help much in this case). Say the word I selected gets highlighted on many surrounding lines, suddenly they all look the same.
