### ISSUE TITLE
Color theme shows code as comment

### ISSUE THREAD

**Issue by tomfeigin** [Microsoft/vscode#54581]
Issue Type: <b>Bug</b>

```
/********************** DATA STRUCTS *******************************/
#include "src/linked_list.h"

/********************** DATA TYPES *******************************/
#include "src/general/circle.h"
```

The above will show the include line as if it is a comment.
```

/********************** DATA TYPES ******************************
*/
#include "src/general/circle.h"
```

The above will show the include line properly

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:40:20.190Z)
OS version: Linux x64 4.13.0-45-generic

**Comment by aeschli** [comment]
@tomfeigin What is the language mode the editor is in?

**Comment by tomfeigin** [comment]
@aeschli Both c and c++

**Comment by aeschli** [comment]
This works for me in the latest:
![image](https://user-images.githubusercontent.com/6461412/45543612-394d6e80-b815-11e8-91f9-546b5f4eab2c.png)

there hasn't been any c/cpp grammar updates since february, so I'm a bit puzzled.
Can you check whether an external extension caused that. Also try different color themes to check if it's an theme issue.
