### ISSUE TITLE
vscode搜索功能不好用

### ISSUE THREAD

**Issue by ydCao** [Microsoft/vscode#54628]
搜索没有webstorm的搜索体验好，比如webstorm搜索引入的依赖只需要ctrl鼠标点击就会跳转到这个依赖定义的地方，但是vscode就不行

**Comment by alexandrudima** [comment]
automatic translation:

"Vscode search function is not good"

"Searching for a search experience without webstorm is good. For example, the dependency introduced by webstorm search only needs ctrl mouse click to jump to the location of this dependency definition, but vscode will not work."

@ydCao Sorry I don't understand what your issue is. Can you please explain clearly?

**Comment by V0idk** [comment]
兄弟还是自己翻译下吧. 
vscode本质是个编辑器.要强大的功能找找相关语言的扩展吧.

**Comment by alexandrudima** [comment]
Sorry, we need to stick with using English in our issues. Please start a new issue in English.
