### ISSUE TITLE
Don't save all files

### ISSUE THREAD

**Issue by kpoddubnyi** [Microsoft/vscode#54647]
Hi!
Today I have felt how the VS code import autocorrection works with TS :)
All my files (almost 500) were changed by VS code and all the imports were wrong.
I was clicking on `Don't Save` button 500+ times  because all my components were broken.

Could you please add a feature that will allow to close all opened files without saving?
Thanks!

**Comment by cedvdb** [comment]
at least it could like commit before changing imports so you can easily revert.

**Comment by mjbvz** [comment]
@kpoddubnyi Opening those files was a bug in the current vs code release. It should be fixed in the current insiders builds. Please let me know if you still see it

@bpasero Should the standard `close all` dialog have an option to discard all changes like the dialog that shows when you close the VS Code window does:

<img width="511" alt="screen shot 2018-07-27 at 5 41 50 pm" src="https://user-images.githubusercontent.com/12821956/43351275-65fc26be-91c4-11e8-9b0f-71b5fafd70a4.png">

**Comment by bpasero** [comment]
@mjbvz we do exactly that when you click the "Close All" e.g. from open editors:

![image](https://user-images.githubusercontent.com/900690/43711231-518b9fba-9972-11e8-83b5-1462cde44f7a.png)

**Comment by TimeBomb** [comment]
@bpasero I'm on the latest VS Code on Mac OS X. I'm clicking Don't Save dozens of times, once per file, on a project that I selected `Close All` on. I'd like to give a big +1 to @kpoddubnyi's request.

**Comment by bpasero** [comment]
@TimeBomb closing all editors of a editor group will prompt you per file but you can use "Close All Editors" (across all groups) and it will show the combined dialog:

![image](https://user-images.githubusercontent.com/900690/44248908-870e9100-a1ed-11e8-9e44-4975b51ca6bd.png)
