### ISSUE TITLE
Feature request - Log points, log content of variables

### ISSUE THREAD

**Issue by superheri** [Microsoft/vscode#54656]
Issue Type: <b>Feature Request</b>

It would be nice for the log points that we can place on the left bar, next to the numbers (like debug points) to be able to output variables so that we could see is content. For exemple, if I have a string, I could just write the name of the string var and the string will output in the log when the debugger reaches this point in the code.

VS Code version: Code - Insiders 1.26.0-insider (afc3d77e7cfc6534ba05c52f5e1289cbecd58b3d, 2018-07-19T05:18:41.292Z)
OS version: Windows_NT x64 10.0.17134

**Comment by V-ed** [comment]
So... [exactly what you wanted](https://code.visualstudio.com/blogs/2018/07/12/introducing-logpoints-and-auto-attach#_introducing-logpoints)?

You can add your variables between `{}` (in the gif example, you can see he has no `console.log()` yet can still log `fib(2): 2` because he added a logpoint that goes as `fib({num}): {result}`.

That's actually a very big feature of Logpoints... is this issue opened because you tried to use Logpoints and it didn't work? Maybe you don't have the Debug Adapter Protocol required for the language you are trying to debug (usually there with the extension for a particular language)...

**Comment by weinand** [comment]
see https://code.visualstudio.com/docs/editor/debugging#_logpoints
