### ISSUE TITLE
Double clicking a file in Unity also creates 3 new files

### ISSUE THREAD

**Issue by andymads** [Microsoft/vscode#54674]
Issue Type: <b>Bug</b>

Double clicking a C# file in Unity opens it in a new tab in Code but also creates and opens 3 other empty files in new tabs: Project and Unity, which are inside the Unity Project folder, and New which is on my desktop. New is unsaved.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU           W3503  @ 2.40GHz (2 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|12.00GB (7.48GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by tommai78101** [comment]
@andymads May want to file the issue here also:

https://github.com/Unity-Technologies/vscode-unity-debug/issues

**Comment by andymads** [comment]
@tommai78101 I disabled my extensions before posting and the bug was still there, but now I've enabled them again I cannot reproduce it now.

**Comment by alexandrudima** [comment]
@andymads This sounds like a vscode-unity specific issue. Please file the issue with them.

**Comment by milankarman** [comment]
I've got this issue too, even without any unity related extensions. It looks like the files that are created are always "Unity" and then the project name files separated by space. When I open a C# script from unity named "Kart Game" and open a script in it, the extra files that open are "Unity", "Kart" and "Game". Screenshot attached
![capture](https://user-images.githubusercontent.com/34920368/43012734-35fabd86-8c47-11e8-9cda-b1d60e48edac.PNG)

**Comment by tommai78101** [comment]
@milankarman  Ok, in other words, to reproduce this issue in a very clean fashion:

1. Open Unity.
2. Create new project.
3. In Assets folder, create new C# Script file.
4. In Unity editor, go to `Edit` > `Preferences`.
5. In Preferences, go to `External Tools` > `External Script Editor` > Set to `Visual Studio Code`.
6. Close Preferences.
7. Open the newly created C# Script file inside Unity editor.
8. Visual Studio Code opens a blank *Unity* document and a blank document that matches the name of the project. It will open up as many blank documents as there are words in the name of the project. Example, in "My Project" project, by opening a C# Script file in Unity, I see blank documents *Unity*, *My* and *Project*.

This is an issue with Unity3D editor itself, but because it also touches on Visual Studio Code, I'm not sure where to put the blame on.

It may be best to report this issue with Unity, and reference this issue in that Unity Issue Tracking Item.

**Comment by kazz900** [comment]
I think I found the solution here, not sure it works for everyone though. In my case I had all my unity projects In a folder named "My Project" since VS Code always made 2 empty files named "My" and the actual project's name I just tried to rename the parent folder of my project "My Project" to just "MyProject" without blank It just solved.

**Comment by tommai78101** [comment]
@kazz900 Well that's just a workaround.

@everyone 

I'm glad to let everyone know Unity has fixed this issue, and will be bundled in 2018.3.

**Comment by tommai78101** [comment]
It's out.

https://unity3d.com/unity/whatsnew/unity-2018.2.1
