### ISSUE TITLE
Emmet: error wrapping link

### ISSUE THREAD

**Issue by emilime** [microsoft/vscode#54711]
Hello,
wrapping an url with emmet wrapping command with "a" tag I notice this strange behavior.

wrapping with "a" preview, look at href:
![screenclip 33](https://user-images.githubusercontent.com/47943/42991089-e060b778-8c04-11e8-9289-ca3059dab403.png)

result after hitting ENTER:
![screenclip 34](https://user-images.githubusercontent.com/47943/42991071-ccc4ed92-8c04-11e8-9fc5-e43fbb98ff60.png)

href is empty instead of http://www.google.it, in Sublime href is correctly filled so I think there is a bug in this command implementation.

I'm using VScode Insiders (last version) on Windows 10

**Comment by gushuro** [comment]
The problem is that when we expand the definitive abbreviation, we treat the text to be wrapped as plain text, there is no logic to when it has another meaning (in this case, being a URL).
I wonder if there are other cases with similar behaviour.
@ramya-rao-a any thoughts? We are relying on the selected_text variable to insert the snippets properly, and to solve this we'd need to completely replace that logic, which sounds excessive if this is the only scenario where it hurts.

**Comment by dariovolaric** [comment]
I am having the same issue. Would be really great if this works for a hrefs and mailtos

**Comment by ramya-rao-a** [comment]
@emilime You are trying to wrap individual lines. Use the command `Emmet: Wrap Individual Lines with Abbreviation` command.

@sergeche Are there other examples like the `a` abbreviation, where the end result of a `Wrap with abbreviation` actions ends up with more than just wrapping the selected text? The `a` abbreviation in this case adds the wrapped text as href if it is a url

**Comment by sergeche** [comment]
Yes, it’s a missing feature with filling `href` attribute with wrapped value. Will fix it.

BTW, there’s shouldn’t be explicit `Wrap Individual Lines with Abbreviation` command, you should always pass array of (unindented) lines to wrap and Emmet will either wrap with implicitly repeating element or insert contents into deepest node

**Comment by emilime** [comment]
@ramya-rao-a thanks, I didn't know about this different behaviour, Sublime is more direct and intuitive in this implementation. I agree with @sergeche

**Comment by cbejensen** [comment]
The same thing happens with e-mails and phone numbers.

**Wrap preview**
![a-mailto-before](https://user-images.githubusercontent.com/12374723/44251463-ae496c00-a1b5-11e8-877c-1dde7c1cdd4b.png)
(note you can also type `a:mail` and it will produce the same result)

**After hitting enter**
![a-mailto-after](https://user-images.githubusercontent.com/12374723/44251462-ae496c00-a1b5-11e8-8c86-cb17e83ca2dd.png)

On a related note, it would be nice if phone numbers could be automatically entered after `tel:` like the first screenshot.
![a-tel](https://user-images.githubusercontent.com/12374723/44251464-ae496c00-a1b5-11e8-891b-b19df3419ae0.png)

**Comment by ramya-rao-a** [comment]
We can definitely do this by updating the parsed abbreviation. PRs are welcome.

At https://github.com/Microsoft/vscode/blob/1.26.1/extensions/emmet/src/abbreviationActions.ts#L605, we have access to the wrapping node.

If the wrapping node is `a` and if the selected text is a url or email, we can update the node's attributes.

**Comment by sergeche** [comment]
Actually, inserting URLs and e-mails into `<a>` tag is already supported: https://github.com/emmetio/html-transform/blob/master/lib/repeater-content.js#L182

I think there’s issue somewhere in VSCode plugin

**Comment by sergeche** [comment]
`repeater-content.js` is a good place to add more patterns for special cases of wrapped content.

Also, you can check out [codemirror-plugin](https://github.com/emmetio/codemirror-plugin) which has most recent features support and currently used in codepen.io project. It also contains most recent experiments and ideas for customization and React

**Comment by Kacppian** [comment]
May I work on this If somebody already isn't?

**Comment by contentfree** [comment]
> BTW, there’s shouldn’t be explicit `Wrap Individual Lines with Abbreviation` command, you should always pass array of (unindented) lines to wrap and Emmet will either wrap with implicitly repeating element or insert contents into deepest node

This caught me since there _is_ a `Wrap Individual Lines` command and, for example, giving just `li` resulted in all the lines being wrapped in a single `<li>` tag. Running the same command but entering `li*` as the abbreviation results in the expected behavior of each individual line being wrapped. Very surprised. (I thought it had been broken for a while now and only got frustrated enough today to search for an answer.)

**Comment by Yensan** [comment]
Emmet save my life! Is there some guys give a full handbook for it?

**Comment by 63now** [comment]
I have a temporary workaround. I too experienced the same problem as the original post. Upon wrapping the selected URL or email address, the preview was correct but upon pressing enter, the URL disappears from the output. I noticed this ONLY happens when using the "Wrap with abbreviation" single line feature within VS code Version 1.36.1 on Mac.

**The fix:** Use 'Wrap individual lines with abbreviation'. Not sure why it works, but it does. It works for URLs as well as email addresses.

After selecting asdf@asdf.com, here's the output:
`
<a href="mailto:asdf@asdf.com" target="_blank">asdf@asdf.com</a>`

After selecting asdf.com, here's the output:
   
`<a href="http://asdf.com" target="_blank">asdf.com</a>`

Hope this helps.

**Comment by rzhao271** [comment]
\closedWith dc5a3da

**Comment by rzhao271** [comment]
Verifier:

1. Type the following link into an HTML document:

`https://github.com/microsoft/vscode/issues?page=1&q=is%3Aissue+assignee%3A%40me+sort%3Areactions-%2B1-desc+is%3Aopen`

2. Place the cursor at the end of the link
3. Invoke the `Emmet: Wrap with Abbreviation` command, and type `a` into the input box that shows up, and press `Enter`. 
4. The link should be wrapped like the following with no lag:
```html
<a href="https://github.com/microsoft/vscode/issues?page=1&q=is%3Aissue+assignee%3A%40me+sort%3Areactions-%2B1-desc+is%3Aopen">https://github.com/microsoft/vscode/issues?page=1&q=is%3Aissue+assignee%3A%40me+sort%3Areactions-%2B1-desc+is%3Aopen</a>
```

What we don't want to see is an empty href attribute, i.e. `href=""`
