### ISSUE TITLE
jsconfig not working for ES6

### ISSUE THREAD

**Issue by JCaraballo113** [Microsoft/vscode#5472]
- VSCode Version: 1.0
- OS Version: Win10

Steps to Reproduce:

1. Open any javascript project
2. Use any ES6 feature such as: () => 

It tells you to use ES6 which I already set up in my jsconfig.json but it still shows errors when using es6 code such as const

I have tried resetting vscode multiple times.

**Comment by dbaeumer** [comment]
This works for me without any problems:

![capture](https://cloud.githubusercontent.com/assets/1931590/14631152/508c9290-0612-11e6-9305-4b8e480bfadc.png)

Any additional hints. Could you share your example?

**Comment by JCaraballo113** [comment]
This is what I see:

![capture](https://cloud.githubusercontent.com/assets/6374766/14647379/7b02ca62-062b-11e6-82b1-8902e0c36af1.PNG)

**Comment by dbaeumer** [comment]
When you hover over these errors what do they show. Do the have [js] in front or something else (e.g. [eslint])

**Comment by JCaraballo113** [comment]
Here you go, also thanks for the replies :D

![hover](https://cloud.githubusercontent.com/assets/6374766/14652485/8bc1b234-0642-11e6-94c4-ccacd24387f3.png)

**Comment by dbaeumer** [comment]
@JCaraballo113 I am pretty confident that this message doesn't come from VSCode itself since errors reported from the JS language service are prefixed with js

![capture](https://cloud.githubusercontent.com/assets/1931590/14665913/b33e5738-06d6-11e6-8f18-5d358d6833a4.png)

Do you have a JS linter extension installed? If you start code form a command prompt using --disable-extensions do you still see the problems

**Comment by JCaraballo113** [comment]
JSHint was causing the issue. Uninstalled it and voila. Sorry for polluting the issues D:
