### ISSUE TITLE
Consider using a lighter blue for menu selection

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#54735]
The current blue is VSCode blue which is too strong for menus.
IMHO menu should look as native as possible. Thus the blue should be like the native blue.

If we decide we want our menu to look differently then we shuold style some things differently (example visual studio). Though I am against this.

**Comment by sbatten** [comment]
@isidorn @misolori I left this around for a while so changing it now might be alarming to users. 

@isidorn are you used to the deep blue color now? :P

**Comment by isidorn** [comment]
Hehe nice try.
I am not used to the deep blue because I do not use the custom menu, I am on the mac :)
As for changing a shade of color - I believe that will not alarm users, it is not a funcitonality, just a shade of color.
However if we believe this should not be done I am fine with closing this.
Though I still think that we should look as close to native menus as possible and that this should be changed.

fyi @joaomoreno @bpasero since they use native menus and might have an opinion on this

**Comment by bpasero** [comment]
I have the following setting to get back the style in lists, trees and the menu as we used to have:

`"list.activeSelectionBackground": "#3399FF"`

I find the current blue horrible, but I think I mentioned this often enough.

**Comment by sbatten** [comment]
I personally don't mind that lighter blue, or any color really since I never use the default themes :P @misolori Are we within guidelines if we switch back to that blue? 

@bpasero your suggestion would be to switch all of those styles to this blue, correct? So they match.

**Comment by misolori** [comment]
We originally had to change the active selection color to make the text accessible since it didn't pass the color contrast ratio:

![image](https://user-images.githubusercontent.com/35271042/50107803-7a746680-01e8-11e9-9f19-c63c190c960f.png)

That meant we had to make the color darker. We could revisit this to find something that is more acceptable for everyone that still passes color:

![image](https://user-images.githubusercontent.com/35271042/50109175-e906f380-01eb-11e9-8b35-ff3eb4241af8.png)

The last option (D) is closer to the macOS menu color:

![image](https://user-images.githubusercontent.com/35271042/50109188-f02e0180-01eb-11e9-8d4f-f4c7da0f4c9a.png)
