### ISSUE TITLE
Extension performance monitoring

### ISSUE THREAD

**Issue by Leedehai** [Microsoft/vscode#54818]
Inspired by the problem in issue #54795, I think adding a window or some other gadget to monitor the performance (CPU, memory, disk IO, processes) of each extension would be helpful to quickly locating the cause of high fan speed or slow response.
It doesn't have to be updated super fast; I think just once per several second is sufficient.
That gadget can be dormant in normal times, and invoked when needed. It can be a floating window, or a script that can display the info in the "output" or "debug console" of the panel.

**Comment by alexandrudima** [comment]
Ah, but we do have one. `F1 > Developer: Show Running Extensions`.

This shows all the extensions that have code executing and their start-up times. Then, one can press the record button (a black circle) and a restart is required because the extension host process will then be re-launched with `--inspect` to allow for the renderer process to inspect it. Alternatively, code can be launched directly with `--inspect-extensions=<PORT>`.

The renderer process will then use the debugger protocol to connect to the extension host process and trigger a CPU profile. When stopping it, the CPU profile is analyzed, and the stack traces are looked at automatically. The stack traces are assigned to each extension they belong to and the time is added up and some mini-graphs are painted. Here you can see I did something that caused the git extension to take up 40ms of total time:

![image](https://user-images.githubusercontent.com/5047891/43072253-bb444252-8e75-11e8-8baf-5ad7693876f3.png)


Finally, the CPU profile can be saved by clicking on the save icon and can be sent to extension authors or to us for further analysis.

**Comment by Leedehai** [comment]
Wow thanks! Then I guess this issue could be closed.
