### ISSUE TITLE
Drunk behavior of moveLinesDownAction

### ISSUE THREAD

**Issue by Oreilles** [microsoft/vscode#54829]
- VSCode Version: 1.25.1 (1.25.1)
- OS Version: OSX 10.11.6

Steps to Reproduce:
1. Select brackets block
2. alt+down

![vscodebug](https://user-images.githubusercontent.com/33065839/43050873-f259c5fa-8e07-11e8-9312-fb8db24eacf8.gif)

**Comment by rebornix** [comment]
Good catch and it helps me understand what's going on there.

Let me use a simple if block to describe the root cause here, will work on it after the issue grooming.

```js
console.log();

if (true) {
  console.log();
}
```

We have 5 lines of code here. Say if we are going to move the 3rd line down, internally we cut the 4th line and paste after 2nd line. So `  console.log();` will be the new 3rd line, and `if (true) {` will be the new 4th. To adjust the indentation of `if (true) {` we need to check the onEnter rules on the new 3rd line `  console.log();` however right now, we are still checking `if (true) {`, which will tell us to increase the indentation. 


The expected result should be 
```js
console.log();

console.log();
if (true) {
}
```

However due to the wrong onEnter rules checking, we get 
```js
console.log();

console.log();
  if (true) {
}
```

**Comment by thany** [comment]
VSCode simply shouldn't touch the indenting when moving **lines** up and down. It's not move a statement, it's moving the **whole line**. So the editor should just stop trying to be smarter than it can be.

The correct indentation is very hard to predict with 100% accuracy, and even 99% isn't good enough, because the remaining 1% will drive one insane. Unfinished code is likely not (yet) well-formed, making it impossible to correctly predict the indentation the developer intents to go for.

**Comment by adamreisnz** [comment]
Fully agree with @thany's statement. There are a lot of auto indentation issues when moving code up and down (see other referenced issues). It might be best to (allow us to) disable auto indentation when moving code up and down, because it's clearly not working as expected in a lot of cases, and it doesn't seem like these issues are high on the priority list.
