### ISSUE TITLE
Make decoration provider API public

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#54938]
Make the following API public

```ts
export interface DecorationProvider {
	onDidChangeDecorations: Event<undefined | Uri | Uri[]>;
	provideDecoration(uri: Uri, token: CancellationToken): ProviderResult<DecorationData>;
}

export namespace window {
	export function registerDecorationProvider(provider: DecorationProvider): Disposable;
}
```

**Comment by eamodio** [comment]
Instead of `DecorationData`, what about just `Decoration` or `UriDecoration` or `ViewDecoration` or  `TreeViewDecoration` or something like that?

**Comment by jrieken** [comment]
Yeah, +1 for `Decoration`. No matter what we chose it should be aligned with the `provide`-function name.

**Comment by jrieken** [comment]
Moving this out because we wanna get a better understand about the requirements. @eamodio Did you look at the existing API proposal and is there anything you need else or different?

**Comment by rebornix** [comment]
@sandy081 @jrieken may I ask how does it work for custom tree views? @sandy081 mentioned in https://github.com/Microsoft/vscode/issues/54939#issuecomment-412520619  that it works for `file` scheme but based on what I test it's not working when the custom tree view item's resourceUri is a `file` one.

In our pull request extension, when you expand a Pull Request node, we return a list file change nodes, whose resourceUri can be `file` and we register a decoration provider. The provider works for File Explorer but not custom tree view.

**Comment by jrieken** [comment]
@sandy081 will know

**Comment by rebornix** [comment]
@sandy081 I no longer see this issue when running from source code but still saw issues with latest insider. Will report an issue if tomorrow's Insider still has issues with that (I doubt so but let's see).

**Comment by eamodio** [comment]
Any chance this api is going to progress or be altered? The `DecorationData` type itself feels more "raw" than many other vscode apis, and I would also love additional filtering rather than just a pure `Uri` matching -- maybe `Uri` and optionally a `contextValue` so that you can target a specific "version" of a `Uri` without it affecting the main explorer tree?

**Comment by jrieken** [comment]
> so that you can target a specific "version" of a Uri without it affecting the main explorer tree?

Do you have an example for that? Do you want the *same* uri to have different representations/decorations?

**Comment by eamodio** [comment]
Yeah, so in a tree I can set the `resourceUri` of an item to get the file icon/name to show (which also opts me in to any registered decorations on that Uri), but if I want to add a custom decoration for that Uri, but only for my tree (or trees) it would be great to be able to have an optional additional matcher that would use the `contextValue` of tree item before applying the decoration. That way I could customize entries for my tree without affecting the main explorer (or other representations of that Uri in other trees)

```ts
export interface DecorationProvider {
	onDidChangeDecorations: Event<undefined | Uri | Uri[]>;
	provideDecoration(uri: Uri, contextValue: string | undefined, token: CancellationToken): ProviderResult<Decoration>;
}

export namespace window {
	export function registerDecorationProvider(provider: DecorationProvider): Disposable;
}
```

Alternatively we could provide a read-only `TreeItem` if there is one, rather than just the `contextValue` and then an extension could use other context to decide whether or not to apply decorations.

**Comment by jrieken** [comment]
> Yeah, so in a tree I can set the resourceUri of an item to get the file icon/name to show (which also opts me in to any registered decorations on that Uri), but if I want to add a custom decoration for that Uri, but only for my tree (or trees) it would be great to be able to have an optional additional matcher that would use the contextValue of tree item before applying the decoration.

Today, everything is based on the `scheme` and I think that should be enough. Something like `myScheme:/some/file.ts` should be detected as TypeScript and the `myScheme` would be that context thing

**Comment by eamodio** [comment]
While using the Uri should work for most cases, imo it just isn't as convenient as the additional `contextValue` since that value is currently often used as the "state" of an item. So for example, lets say Live Share wanted to color (or bold) a user in their tree when they are online -- now instead of just changing the `contextValue` which they are likely already doing to control the commands available, they also need to change the Uri of that item in some way (scheme, querystring, something) to be able to key off of to provide the appropriate decorations at the right time. It just doesn't feel like the right place for that signal imo.

Anyway just my 2c 😉

**Comment by jrieken** [comment]
Well, context values change like crazy and I am not keen on running checks all the time or asking the providers all the time. Also it adds another dimension which can mean all kinds of things. That's why I am conservative.

**Comment by jrieken** [comment]
Latest proposal - no more `source` etc

```ts
	export class Decoration {
		letter?: string;
		title?: string;
		color?: ThemeColor;
		priority?: number;
		bubble?: boolean;
	}

	export interface DecorationProvider {
		onDidChangeDecorations: Event<undefined | Uri | Uri[]>;
		provideDecoration(uri: Uri, token: CancellationToken): ProviderResult<Decoration>;
	}

	export namespace window {
		export function registerDecorationProvider(provider: DecorationProvider): Disposable;
	}
```

- [ ] should `letter` be `title` or `label` and not be restricted to a single character anymore, e.g to enable https://github.com/ryanluker/vscode-coverage-gutters/issues/213

**Comment by jrieken** [comment]
@eamodio Is the context value still a requirement for you? What we could consider is to register a provider for a certain context, e.g `registerDecorationProvider(contextFilter, provider)` or have a context value on the `Decoration` object itself. However, that will expose more of context values which aren't typed or document and I believe this use-case is more generic than `TreeItem#contextValue` as those are usually created and consumed inside one UI piece... 

In case this is a requirement for tree views only, then we can also consider to add something like decorations to tree view items. That would maybe align with the proposal to render highlights in tree items (see https://github.com/microsoft/vscode/blob/b035116887d9ddbfc1fc0a8bebda8194824d21b5/src/vs/vscode.proposed.d.ts#L857)

**Comment by eamodio** [comment]
@jrieken Its been a while since I looked at this. My gut reaction is that having an optional `when` on the `Decoration` itself would be very handy -- where it would follow the same format/rules of normal `when` clauses. For example, I could envision using a decoration on a repository or branch in GitLens when it is marked as a favorite (or when its current), and that would just be an additional state (contextValue) on the same Uri.

Also are these decorations only applied to trees? Or would they apply to editor tabs or anything else? As the generic `Decoration` name makes me think it would be broader.

**Comment by eamodio** [comment]
Although thinking about it more -- for the cases where I would use it, I think what you suggested -- `registerDecorationProvider(contextFilter, provider)` would work better. Because often, I don't care as much about the Uri's and much more about the `when` clause.

**Comment by jrieken** [comment]
Hm, would you the `contextFilter` to describe a UI element, eg your tree or tree items or something more dynamic, e.g `registerDecorationProvider({when: 'editorHasSelection'}, provider)` would then be allowed and I think that's weird, performance-wise because we would ask that provider a lot and also UI-wise, because on some item much flicker would happen.

**Comment by JohnstonCode** [comment]
Hello. Do you know when this API will make it to stable yet?

**Comment by jrieken** [comment]
@JohnstonCode shouldn't be too far out. What's your use-case? Have you given the current proposal a try and did it work for you?

**Comment by JohnstonCode** [comment]
My use case is for the Svn extension. Yeah the current proposal worked perfectly.

**Comment by gjsjohnmurray** [comment]
What are the prospects of getting this API finalized soon?

**Comment by NicoSB** [comment]
I have used the the proposed API for this quite extensively in the last weeks. I have not encountered any issues and the api felt natural to work with. 

Is it planned to lift this into stable soon?

**Comment by RMacfarlane** [comment]
There was a request to match the GitHub Pull Request file decorations to the SCM ones with bubble and color, but setting those properties on the decoration doesn't appear to change it. Are these expected to work?

**Comment by Exelord** [comment]
Where can I find the latest Preview API? :)

**Comment by sebazai** [comment]
Hello,

Proposed API works fine for our specific case where we want to use letters indicating status of our programming exercises.
Something we would like to have is possibility for letter coloring only, because coloring the whole folder name + letter is too excessive in our specific use case. For example:

```ts
export class Decoration {
	letter?: string;
        letterColor?: ThemeColor;
	title?: string;
	color?: ThemeColor;
	priority?: number;
	bubble?: boolean;
}
```

**Comment by jrieken** [comment]
> Something we would like to have is possibility for letter coloring only, because coloring the whole folder name + letter is too excessive in our specific use case

For that we have the `explorer.decorations.colors`-setting, making this a user choice. Currently it's also the highest priority item which defines the overall color, e.g when there is an error all letters and the label turns red.

**Comment by jrieken** [comment]
Latest proposal

```ts
export class FileDecoration {

	/**
	 * A very short string that represents this decoration.
	 */
	badge?: string;

	/**
	 * A human-readable tooltip for this decoration.
	 */
	tooltip?: string;

	/**
	 * The color of this decoration.
	 */
	color?: ThemeColor;

	/**
	 * A flag expressing that this decoration should be
	 * propagated to its parents.
	 */
	propagte?: boolean;

	/**
	 * Creates a new decoration.
	 *
	 * @param badge A letter that represents the decoration.
	 * @param tooltip The tooltip of the decoration.
	 * @param color The color of the decoration.
	 */
	constructor(badge?: string, tooltip?: string, color?: ThemeColor);
}

/**
 * The decoration provider interfaces defines the contract between extensions and
 * file decorations.
 */
export interface FileDecorationProvider {

	/**
	 * An event to signal decorations for one or many files have changed.
	 *
	 * @see [EventEmitter](#EventEmitter
	 */
	onDidChange: Event<undefined | Uri | Uri[]>;

	/**
	 * Provide decorations for a given uri.
	 *
	 * @param uri The uri of the file to provide a decoration for.
	 * @param token A cancellation token.
	 * @returns A decoration or a thenable that resolves to such.
	 */
	provideFileDecoration(uri: Uri, token: CancellationToken): ProviderResult<FileDecoration>;
}

export namespace window {
	export function registerDecorationProvider(provider: FileDecorationProvider): Disposable;
}
```

**Comment by Gama11** [comment]
There seems to be a typo in `propagte` (should be `propagate`).

**Comment by jrieken** [comment]
Moving to October for finalization

**Comment by bwateratmsft** [comment]
Does this really need to be specific to files? For the Docker extension, we'd use it to show the number of running containers.

**Comment by jrieken** [comment]
Well, the API is uri-based. You get passed an URI and can respond with a *File*Decoration. We wanted to make it more specific than just Decoration but UriDecoration is somewhat wired. I think FileDecoration expresses the intent nicely because decorations show-up when you get the "file rendering" - that means we apply file icons, make paths relative to home and/or workspace folders etc.

**Comment by bwateratmsft** [comment]
Maybe I'm misunderstanding what this is for then? I was thinking it was for this:
![image](https://user-images.githubusercontent.com/36966225/94283511-18997280-ff1f-11ea-8d16-d5ad9d29523d.png)

**Comment by jrieken** [comment]
No, it is for these things

<img width="316" alt="Screenshot 2020-09-25 at 17 07 51" src="https://user-images.githubusercontent.com/1794099/94283731-ad1cc880-ff51-11ea-875f-a91f80cdb0a0.png">

**Comment by bwateratmsft** [comment]
Aha! I'm a dummy, sorry for introducing confusion. Is there anything for what I screenshotted? I didn't find anything obvious in the [API doc](https://code.visualstudio.com/api/references/vscode-api) but I'm not entirely sure what I'm looking for either...

**Comment by alefragnani** [comment]
@jrieken are Side Bar Badges in api-proposal stage?

**Comment by eamodio** [comment]
AFAIK, there isn't a proposal for sidebar/view badges

**Comment by alefragnani** [comment]
So why has #38426 been closed as _duplicate_?

**Comment by eamodio** [comment]
Hrm, I don't think it should be, since I don't think you can even create that style "badge" on a tree item with this API, nor can you add badges to the activity bar icon or view title area.

**Comment by alefragnani** [comment]
That’s exactly what I (and @bwateratmsft ) thought looking at the latest @jrieken comment. But as a few other API proposal issues did support more than one idea/scenarios, I asked about _when_ the Side Bar/Views badges would be available. 

It appears it won’t happen anytime soon 😢

**Comment by sandy081** [comment]
I am really sorry that I do not remember why I made https://github.com/microsoft/vscode/issues/38426 as a duplicate of this issue.

Reopening the other issue for badges support in custom views and view containers.

**Comment by bwateratmsft** [comment]
@sandy081 Can you also unlock conversation on the other one? Thanks!

**Comment by alefragnani** [comment]
@sandy081 no problem 😉

Thanks for reopening the other issue.

**Comment by eamodio** [comment]
@jrieken what do you think about adding a uri type filter to `registerDecorationProvider` -- maybe something like the `scheme` filter on `registerTimelineProvider`, or maybe `DocumentSelector` (without the language part?)? That way we could avoid a lot of back and forth to the extension host for Uri's that an extension doesn't care about.

**Comment by jrieken** [comment]
> That way we could avoid a lot of back and forth to the extension host for Uri's that an extension doesn't care about.

Unsure. We kinda expect that file decoration provider work for all files/schemes and that filtering by a subset is the exception. What is your use-case?

**Comment by eamodio** [comment]
@jrieken My use case is to add custom uris to many GitLens tree view items, so I would only be interested in in specific schemes (e.g. `gitlens-view`). 

Here are some other thoughts from playing around with the new APIs:
- I find myself wanting to return more than 1 decorator per uri (of course I can have multiple providers, but it seems like I should be able to return an array
- I find only having only 1 character for a badge too limiting (especially since codicons don't work), even our SCM decorations use more than 1 character. Maybe 3? For example, I wanted to but a indicator on branches in my Branches view for ahead/behind state, like `2↑` or `9+↓`
- I'm not a fan with how the tooltips are integrated into the tree items' tooltip -- I feel like these indicators should have their own separate tooltips or a single one that tries to aggregate all the badges into one
- Probably should rename `registerDecorationProvider` to `registerFileDecorationProvider` for consistency
- I know we've talked about this before, but I _really_ want an option to have the color only apply to the badge rather than the whole row

**Comment by jrieken** [comment]
@eamodio Well, it looks like you do not want to be a *file* decoration provider (please check latest proposal) but you want decorations for custom tree.

**Comment by eamodio** [comment]
@jrieken Ideally yeah, but the difference between the two imo is quite blurred.

**Comment by jrieken** [comment]
* remove badge length check (limit is 2)

**Comment by jrieken** [comment]
fyi @alexr00 I have changed the name of the event from `onDidChange` to `onDidChangeFileDecorations`. I might wanna adopt that in GHPR

**Comment by alexr00** [comment]
@jrieken thanks for the heads up. I have adopted the change.

**Comment by jrieken** [comment]
@alexr00 sorry one more change for next (tomorrows) insiders: It's now `registerFileDecorationProvider` to add a provider.

**Comment by jrieken** [comment]
Done

**Comment by sandy081** [comment]
Verified and reviewed the file decoration provider API in `vscode.d.ts.`
