### ISSUE TITLE
Horizontal scrolling - scroll the window instead of cursor

### ISSUE THREAD

**Issue by Sepci0** [Microsoft/vscode#54948]
https://github.com/Microsoft/vscode/issues/1200 
I have maneged to recreate the "bug"(?)
When you have your mouse on certain tile, it scrolls it corectly wherever your cursor is.
When you move your mouse **outside** of any tiles, but inside of VS code window (eg, Title bar of VS code),  the cursor is moving.
Option to diable cursor moving would be great, it really annoys me.
Adding (fixing?) to track cursor positon (insted of mouse?) in options would be great.

My system is win10
My touchpad - "synaptics smbus touchpad" 
Vs code version:
![image](https://user-images.githubusercontent.com/31455252/43146476-930e4e08-8f61-11e8-8569-274d6dd0cdc2.png)

_(sory for all writting errors, this is first issue i wrote)_

**Comment by alexandrudima** [comment]
This is caused by the trackpad driver and the way it implements dispatching of events. Most likely the current trackpad driver sends to Code.exe key events for arrow left and arrow right when you are using the trackpad.

This might reproduce in Chrome.exe or it might be that the trackpad driver dispatches other kinds of messages if the focused application is Chrome.exe.

In any way, there is unfortunately no possible code change we can do on our side: if we receive arrow key presses, we will interpret them as arrow key presses.
