### ISSUE TITLE
Add toggle.diff.editorMode to the command palette

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#54974]
While investigating #54967

The editor menu for the diff editor has the "Toggle Inline View" action.

1) This is not available through the command palette.
2) The command id is `toggle.diff.editorMode` but there is no description shown in the keybindings editor.

**Comment by bpasero** [comment]
@kieferrm I do not think we support to show a description for commands in the keybindings editor, e.g. check this:

![image](https://user-images.githubusercontent.com/900690/43764138-eb2b2b8a-9a2c-11e8-89f0-9029255fd15b.png)

I think we should have a general issue for fixing that situation so that every command comes up with a proper description, can you file that? I will rename this issue.

**Comment by bpasero** [comment]
**Verifier:** you can invoke "Compare: Toggle Inline View" from the command palette, only if the active editor is a diff editor.
