### ISSUE TITLE
don't use setter injection

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#5504]
It seems the workbench has established a pattern of [setter-injection](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/workbench.ts#L364) for spreading the instantiation service. Either convince me of why that is good or use constructor injection.

**Comment by jrieken** [comment]
I believe, I should understand this is as a fishy workaround for not having a `onDidCreateServices` event in the lifecycle service. Once each and everyone consumer received an instantiation service it will use it to create more things...

**Comment by bpasero** [comment]
@jrieken yes that sounds right about why I need this workaround.

**Comment by bpasero** [comment]
@jrieken I pushed a change to reduce the calls to setInstantiationService() from the workbench for all the parts. There is still 2 places where we use this pattern:
* to inject the instantiation service into other services
* to inject it into registries that are created too early to be created with the instantiation service

**Comment by bpasero** [comment]
Third one
* MessageService.setWorkbenchServices()

**Comment by jrieken** [comment]
@bpasero I will add an event ala `onDidStart` to the lifecycle service such that there are no more excuses (minus singleton registries)

**Comment by bpasero** [comment]
@jrieken I wonder if we need this in all cases. For example, when I look into https://github.com/Microsoft/vscode/blob/master/src/vs/platform/thread/common/abstractThreadService.ts#L33 it seems to me the setter is not doing any follow up work so it seems the instantiation service could just be passed in.

The real issue is that we need the instantiation service within a service but the instantiation service is only created when all services are done. Instead we should create the instantiation service as first service so that we can pass it around to other services maybe?

**Comment by jrieken** [comment]
> the instantiation service is only created when all services are done.

That is not true. We do create it [very early](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/electron-browser/shell.ts#L165) but it doesn't have all services yet. So, someone that received the instantiation service during its ctor-call doesn't know if all services are present yet which in return means contributions it creates might miss a service

**Comment by bpasero** [comment]
@jrieken ok so as long as the service is not using the instantiation service it would be safe to pass it in via ctor.

**Comment by jrieken** [comment]
If it's not using the service it should not ask for it. If it's using the service under some condition later in the code it must be very careful to know that everything is in a well-defined state. That's why I propose to have an event that signals that.

**Comment by bpasero** [comment]
I fixed another bad dependency (`message service` <=> `quick open service`). For the remaining one (`keybinding service` <=> `status service`) I think I need more infrastructure.

@jrieken facing some issues and have some feedback. in no particular order:

**UntitledEditorService**
> That is not true. We do create it very early but it doesn't have all services yet.

The instantiation service is not created early enough so that it can be used for other services. For example the `UntitledEditorService` needs the `InstantiationService` but I cannot pass it in properly because we do not create it early enough.

**Registries**

Should we do something like you do for telemetry appenders for registries too (`this.instantiationService.invokeFunction(TelemetryExtensions.TelemetryAppenders.activate)`)? Though in the end that is not much different from setting the instantiation service directly.

**ThreadService**, **KeybindingService**

Moving to you, not sure if @alexandrudima should own it though

**Comment by jrieken** [comment]
> The instantiation service is not created early enough so that it can be used for other services. 

But that isn't a limitation of the instantiation service but the shell isn't using it properly. There is nothing bad if it creates the service at the beginning of [`initServiceCollection`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/electron-browser/shell.ts#L297). The separation between instantiation service and service collection is only not allow down-level consumer of the former to alter it. Tho, if you have both you can modify the service collection and thereby the instantiation service.

> Though in the end that is not much different from setting the instantiation service directly.\

Yes, the ideas is that those things are extension-like. Ideas are still floating but image us discovering certain files from disk (according to a `xyz.contribution.ts` pattern), loading the file, and invoking the active function. My goal is to reduce the number of registries. Take telemetry, where we have the service, service extensions, and the registry. The registry is just unnecessary glue because the telemetry appenders cannot be discovered and then have access to the telemetry service. We should change that.

**Comment by bpasero** [comment]
> But that isn't a limitation of the instantiation service but the shell isn't using it properly.

Happy to hear that it is just the Shell not using it properly, so can you propose a change to be able to use the instantiation service properly and have it ready to be passed into UntitledEditorService?

+1 for ditching our static registries and replacing them with something better

**Comment by jrieken** [comment]
pushed

**Comment by bpasero** [comment]
👍 , one less setXYService() call for untitled editor service

**Comment by bpasero** [comment]
Also extracted https://github.com/Microsoft/vscode/issues/5688 for the message-service <=> statusbar-service cycle.

**Comment by jrieken** [comment]
@alexandrudima Assigning to you in order to asses the `setInstantiationService` calls on the thread service. Given the mutability of the instantiation service I see no reason for the setter injection except for a missing lifecycle event ala _services loaded_

**Comment by alexandrudima** [comment]
@jrieken I didn't understand exactly from the comments what semantics have changed w.r.t. the instantiation service. Is it safe to ask for it in the ctor and if services are instantiated later, the instance I got passed in will contain "newer" services?

e.g. In the ThreadService ctor, the instantiation service definitely does not contain a `threadService`. But later, when I need to instantiate something, the same instantiation service instance will contain the `threadService`. Did I understand this correctly?

**Comment by jrieken** [comment]
> Did I understand this correctly?

Yes - it's just not very clear when that _later_ is cos there is no explicit event or an implicit signal like the set-call is today.

**Comment by alexandrudima** [comment]
There is no more `instantiationService` usage in `threadService`
