### ISSUE TITLE
Wrong "Cannot disable extension": Arduino vs PlatformIO

### ISSUE THREAD

**Issue by ivankravets** [Microsoft/vscode#55050]
Issue: https://github.com/platformio/platformio-vscode-ide/issues/49#issuecomment-407544805

It's funny for me, do you install/promote [Microsoft's Arduino extension](https://marketplace.visualstudio.com/items?itemName=vsciot-vscode.vscode-arduino) in pair with [PlatformIO IDE extension](https://marketplace.visualstudio.com/items?itemName=platformio.platformio-ide)?

1. PlatformIO extension does not depend on Arduino IDE
2. PlatformIO extension does not depend on Microsoft's Arduino extension
3. PlatformIO extension does not depend on Java.

See 
https://github.com/platformio/platformio-vscode-ide/blob/8d54e66dbc6fd6c29e472eb6792dddb990e02c0c/package.json#L552

I've just tried to reproduce this issue and I was shocked. I can't disable Arduino extension (which I installed to reproduce this issue) for the PlatformIO workspace. The only manual removing of Arduino extension helps here.

**Comment by ivankravets** [comment]
I see you marked #55118 as feature-request. Is this a bug? I tried to disable other extensions and I didn't see any errors. The only problem is with Arduino extension. How do you track that PlatformIO depends on Arduino? That is not true.

**Comment by sandy081** [comment]
Its happening because PlatformIO depends on C/C++ extension and Arduino also. When you disable PlatformIO extension along with dependencies, it tires to disable C/C++ extension also. But since Arduino extension also depends on it, you get an error that, PlatformIO cannot be disabled. So it is not a bug.

![image](https://user-images.githubusercontent.com/10746682/43291212-efcd0e88-9130-11e8-920e-6c5ba079c109.png)

#55118 will change this behaviour by not showing a prompt in this case and disable only PlatformIO extension.
