### ISSUE TITLE
Ctrl+click not working to find variable/function/class declaration

### ISSUE THREAD

**Issue by skyvondave** [Microsoft/vscode#55092]
I've already searched for the answer for this here, on StackOverflow, and through Google, and no solutions I've found have worked.

I'm coming from PHPStorm and Eclipse where Ctrl+click on a variable or function or class object or call takes me to its declaration... I tried editing Go To Definition (F12) or goToDeclaration (why are those named differently anyways?) but the editor ignores click; F12 doesn't even do anything. I've tried editing other things like "editor.multiCursorModifier": "alt" but nothing I'm trying is working.

I found similar issues here but they're closed with no solution that is working for me, and I'm on a Mac; not sure if that makes a difference.

**Comment by skyvondave** [comment]
I seem to be going down a rabbit-hole of issue links and VS Code terminology I'm kind of having trouble understanding (at least maybe just the context of) because I'm kind of new to the program...

Can someone point to the solution? I've spent half an hour on this already.

**Comment by kieferrm** [comment]
@skyvondave VS Code relies on language extensions. You can see if your language extensions work correctly when hovering over a symbol you know is defined (for example in the same file) and the hover shows the type information. When you hold the <kbd>Cmd</kbd> modifier when hovering over the symbol you should see its definition and the symbol is represented as a link. You go to a definition of a symbol by using <kbd>Cmd+Click</kbd>.

**Comment by skyvondave** [comment]
Hovering over a method call (inside of a method definition, for instance `methodCall` in `$this->methodCall()`) in a class shows nothing; hovering over `$this` in `$this->methodCall()` shows "Refers to this current object"...

I'm not sure what language extensions you're talking about; I have PHP IntelliSense installed but only PHP 5.x and have been told by the extension author that it only works with PHP 7... but I'm not sure this is what you're talking about.

Hitting Cmd or Ctrl or Alt while hovering does nothing either... changing "editor.multiCursorModifier" to "ctrlCmd" also changes nothing.

**Comment by kieferrm** [comment]
Here is how hovering and Cmd/Ctrl click work. This example is in TypeScript. TypeScript support comes out of the box with VS Code. I hover my mouse pointer over`BreadcrumbsConfig` on line 73 and while the hover shows I press the `Cmd` modifier (`CMD` because I recorded this on macOS, it's `Ctrl` on Windows and Linux). The identifier then turns into a link that I navigate by clicking.

![sp2hdpfqw0](https://user-images.githubusercontent.com/4674940/43426853-12ea71ca-940c-11e8-9404-e6af1da2728e.gif)

The generic navigational flow is built into VS Code, just like it is built into eclipse. To get it for a specific language you need a language specific extension. For java development with eclipse for example you need the JDK plugin. You develop PHP with VS Code. So, you installed a the PHP IntelliSense extension. This extension tells VS Code which symbols are declared where etc. In your case it seems that is not properly working. I'm guessing that your project is setup in a way the extension does not understand. I'm sure the people who wrote the extension are happy to help you.  This is their repository: https://github.com/felixfbecker/vscode-php-intellisense/issues

**Comment by skyvondave** [comment]
I switched to a Mac keyboard for reasons unrelated to VS Code and suddenly hover+click works as expected.
