### ISSUE TITLE
Add remove action to debug watches

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/vscode#55108]
We should add remove action to debug watches for parity with Chrome DevTools.

Rationale: Make it easier to remove watches. We already made it easier to add by double clicking in the empty space

![screen shot 2018-07-25 at 10 45 23 pm](https://user-images.githubusercontent.com/173559/43243681-9b8a0742-905c-11e8-8013-4cff1197b3b6.png)

**Comment by isidorn** [comment]
We already had it.
I removed it because I disliked the clutter and the multiple ways of removing watch expressions
Context menu, keyboard shortuct, title area action.

Also if we add it we should also add it for breakpoints, thus creating more clutter

If more users want this I would be open for a PR.
A PR could be done by looking at our GitHub history and resurecting the old code.
