### ISSUE TITLE
Unify/clarify "Check for updates" for main code and extensions

### ISSUE THREAD

**Issue by crystalfp** [Microsoft/vscode#55114]
The bottom/left button offers a "Check for Updates..." entry. Could you clarify if the updates are for the main code only (I think so) and not for the installed extensions?

In the Extensions panel the "..." button offers a "Check for Updates" entry. Could you clarify if it check updates for all extensions installed (enabled or not)?

For this second check, could you provide a feedback mechanism? Currently you push it and nothing happens.

Maybe the two checks could be integrated into one, but it is a minor feature.

Thanks!
mario

**Comment by crystalfp** [comment]
Suggestion not relevant here.

**Comment by kieferrm** [comment]
We should use `Check for Extension Updates` and we should show dialog if there are no updates available. Same we do for application updates.

**Comment by ParkourKarthik** [comment]
I'm picking this up. Might take some time for me. Will ask for help if needed 😄

**Comment by JacksonKearl** [comment]
@ParkourKarthik sounds good. I like the idea of navigating to `@outdated`. If we do that we might actually not need to show the popup, as the list would presumably be empty if there are no updates. @ramya-rao-a what do you think?

**Comment by ParkourKarthik** [comment]
I'm stuck at build the code.
I'm facing the below error while running `yarn` as per the [How to Contribute](https://github.com/Microsoft/vscode/wiki/How-to-Contribute#build-and-run-from-source) document.

> yarn install v1.9.4
$ node build/npm/preinstall.js
[1/4] Resolving packages...
[2/4] Fetching packages...
info vscode-fsevents@0.3.8: The platform "win32" is incompatible with this module.
info "vscode-fsevents@0.3.8" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/15] ⡀ gc-signals
[6/15] ⡀ node-pty
[3/15] ⢀ native-is-elevated
[4/15] ⢀ native-keymap
error \vscode\node_modules\native-keymap: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: \vscode\node_modules\native-keymap
Output:
C:\PK\Unofficial\Projects\opensource\vscode\node_modules\native-keymap>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\n
ode-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.11.1 | win32 | x64
gyp info spawn C:\Python27\python.EXE
gyp info spawn args [ '\\AppData\\Roaming\\nvm\\v8.11.1\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   '\\vscode\\node_modules\\native-keymap\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '\\AppData\\Roaming\\nvm\\v8.11.1\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '\\.node-gyp\\iojs-2.0.5\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=..\\.node-gyp\\iojs-2.0.5',
gyp info spawn args   '-Dnode_gyp_dir=..\\AppData\\Roaming\\nvm\\v8.11.1\\node_modules\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=..\\.node-gyp\\iojs-2.0.5\\<(target_arch)\\iojs.lib',
gyp info spawn args   '-Dmodule_root_dir=..\\vscode\\node_modules\\native-keymap',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   '\\vscode\\node_modules\\native-keymap\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn msbuild
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the file specified. [..\vscode\node_modules\native-keymap\build\keymapping.vcxproj
]
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (..\AppData\Roaming\nvm\v8.11.1\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd ..\vscode\node_modules\native-keymap

I believe that these errors are due to the inability to find the VC++ build tools by `node-gyp` or `yarn`. (I've installed VS2017 along with VS2015). I could assure that the VC++ build tools are already installed for the VS2017 (since I was able to build the individual node modules through vs2017), but I'm clueless on what I should do.

Attempts that I made:
- I tried installing the alternative `windows-build-tools` as per the guidelines.
- I tried setting the environment variables before executing `yarn` command. ('C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvarsall.bat')

OS: Windows 10
npm version : 8.11.1
yarn: v1.9.4

Could someone help me with this?

**Comment by ramya-rao-a** [comment]
@ParkourKarthik Check if https://github.com/Microsoft/vscode/issues/47020 helps

**Comment by ParkourKarthik** [comment]
@ramya-rao-a Thanks for the help 😃. I saw the issue already but this time I actually installed the tools while opening in VS2015 when the prompt asked. Then executed the `yarn` command, worked well. (seems I was missing v140 build tools)

Right now looking a way to call `@outdated` as the `ShowOutdatedExtensionsAction` has `IViewletService` in param which is being utilized whereas `CheckForUpdatesAction` has param `IExtensionsWorkbenchService`. 

Currently my `breakpoint` isn't hit; says `unverified breakpoint` when the `Dev VSCode` is running.
I'll try to figure out a way for the fix.

**Comment by ramya-rao-a** [comment]
You can add the IViewletService as the 4th parameter and use it that way.

**Comment by ParkourKarthik** [comment]
>You can add the IViewletService as the 4th parameter and use it that way.

**Note:** I've replaced the 3rd param (`extensionsWorkBenchService`) with the `viewletService` as it was having no other usage. I've tested the working of other reference as well (command pallette).

**Comment by ramya-rao-a** [comment]
Note to verifier:
- Test with `extensions.autoUpdate` and `extensions.autoCheckUpdates` settings disabled. Have an extension with an older version.
- Test the label change to `Check for Extension Updates`
- Notification should tell whether 0, 1 or more updates are available
- When run from command pallet with extensions viewlet is hidden, and updates are available, the extension viewlet should show up. This is so that user can look at the outdated extensions
- When run in the presence of one of the custom views in the extension viewlet, the default view should show up after the notification on available updates
