### ISSUE TITLE
Copy in chrome dev tools not working

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#55147]
Only reproduces on mac. Works on win and linux.

1. F1 > developer tools
2. Try to copy any text via `cmd + c`
3. Text is not copied 🐛

Started appearing about the time we merged the menu work so our suscipion is that is the cause.
Also note that when doing cmd + c, chrome dev tools is expecting there is a copy command under the edit menu (which we do have)

Assigning to July since this is hurting a bit of team's productivity.

fyi @jrieken

**Comment by sbatten** [comment]
Ah, this happens because on macOS, you must register the role of the action in the menubar. In the old code it was done statically like sohttps://github.com/Microsoft/vscode/blob/1dfc5e557209371715f655691b1235b6b26a06be/src/vs/code/electron-main/menus.ts#L548 

This is only done for cut, copy, paste and on macOS so we could just add a function to menubar.ts to check the actionid and add the role. otherwise, the menuregistry would need to be extended, but I don't see that as worth it. What do you think?

**Comment by isidorn** [comment]
@sbatten great thanks for the explanation. Yeah let's solve it like that, it is a bit of a special action.

**Comment by isidorn** [comment]
Thanks, this now works great -> verified
