### ISSUE TITLE
SCM: Support monospace font in commit input field

### ISSUE THREAD

**Issue by a0js** [microsoft/vscode#55169]
I have searched several combinations of the words `git` `message` `font` and found no issues regarding this open or closed within the first few pages of results.  So I assume it hasn't been brought up before.

I really like how the box warns if you go over the preset line length.  One thing I've stared doing is expanding my sidebar to the point where the line break should be approximately so I can preemptively add my new lines.  This works relatively well, but if I could set the font of the edit box to a monospace font it would work perfectly.

**Comment by Randoragon** [comment]
``I'll second this, monospace is critical for aesthetical and intuitive writing of commit messages.``

**Comment by callumgare** [comment]
It has actually [been raised before](https://github.com/Microsoft/vscode/issues/31228) but it was closed and locked years ago so there is no way to vote on it. I think this is indefinably worth reconsidering. Or alternatively (and maybe even better) having a genial highlight that lets you know when a line is over it's recommended length. It's very annoying having to count or guess how many characters a line is in order to know where to break it.

**Comment by lszomoru** [comment]
**Verification:**
We have added a new setting (`scm.inputFontFamily`) to control the font that is being used for the input field in the SCM viewlet. The setting supports the following values: 1) `default` - use the workbench font, 2) `editor` - use the editor font, 3) `font name` - use the font name specified.

Steps:
- Open the SCM viewlet and type in a commit message. Verify that the font matches the workbench font.
- Change the setting to `editor` and verify that the font has changes to the font used by the editor.
- Change the setting to a font name (ex: `Consolas`) and verify that the font changes to the specified font.
- Change the setting to a bogus name and verify that the font changes to the default user agent font.

**Comment by isidorn** [comment]
Works great, created this follow up item https://github.com/microsoft/vscode/issues/99269
