### ISSUE TITLE
Infinite Loop when trying to delegate the request.

### ISSUE THREAD

**Issue by jens1o** [Microsoft/vscode#55222]
> Okay, I'm working on implementing this. I've got one problem though. When I pass vscode the request, it apparently passes it back to me, then I pass it to vscode... Infinite Loop. How can I get around this and declare the specific code-part as another language, so (in my example) the Emmet provider rules it all?

> That's the code currently: https://github.com/jens1o/vscode-smarty/blob/a558eb202f91c7657904e4c39a2844529e06fb39/src/completionProvider.ts#L28-L41

#47288

**Comment by aeschli** [comment]
You need to create a new text document with `languageId: html`. The content also has to be HTML. In that document, you have to clean out all smarty templating syntax that can interfere with the html syntax.
When doing that, the best is to just put whitespaces at the places where the smarty syntax is, so that positions for the code assist (and the result) stay the same.

**Comment by jens1o** [comment]
Alright, thank you. I'll try it.

**Comment by aeschli** [comment]
Marking as closed
