### ISSUE TITLE
Increase height of horizontal scroll bar

### ISSUE THREAD

**Issue by innerlee** [Microsoft/vscode#5524]
- VSCode Version: 1.0.0
- OS Version: Ubuntu 15.04

The horizontal scroll bar is too narrow to grab. And lower half being taken by updown arrow (see pic below) makes the situation worse.

![ffff](https://cloud.githubusercontent.com/assets/9464825/14661695/495a2656-06e2-11e6-849e-723a2ecc8a4d.png)

**Comment by alexandrudima** [comment]
I think we have two options:

A) Move the sash target area lower, more on top the status bar -- I think dragging up the debug console is a less used gesture than scrolling horizontally by dragging the scrollbar.

B) Increase the height of the horizontal scrollbar. Now, the vertical scrollbar is 14px wide, while the horizontal one is 10px high.

@isidorn @bgashler1 Thoughts?

**Comment by isidorn** [comment]
I agree that the horizontal scrollbar is more important than dragging the panel up.
I am fine with both A and B

**Comment by bgashler1** [comment]
I think the most conservative move is "A," because it avoids changing the look while still fixing the problem, but only if it would not make it harder to click the buttons in the status bar in a situation like below.
<img width="304" alt="untitled" src="https://cloud.githubusercontent.com/assets/11839736/14903356/5f90472e-0d55-11e6-9c86-9b78ccfdd8ad.png">
In the situation above, it seems like whenever the drag cursor is active I can't click a status bar button, even if my cursor is technically over it.

I like leaving the horizontal scrollbar its current size because we make it subordinate to the vertical one which is larger (the vertical one carries more information about the document as a whole).

My two cents.  Totally open to other ideas, though.

**Comment by alexandrudima** [comment]
@isidorn assigning to you if you want to experiment with A.

**Comment by isidorn** [comment]
@alexandrudima yup, let me play around with that

**Comment by isidorn** [comment]
I have decreased the size of the sash from 5px to 4px, and 2px are now in the scroll area, and 2px in the status bar area. This just felt best to me.
Giving to @bgashler1 to verify and give feedback
