### ISSUE TITLE
not display the space replacement character in string middle

### ISSUE THREAD

**Issue by sinaku-developer** [Microsoft/vscode#5529]
- VSCode Version:1.0.0
- OS Version:OS X EI Capitan 10.11.4

Steps to Reproduce:
1. ```
   // エディターで空白文字を表示するかどうかを制御します
   ```
   
   "editor.renderWhitespace": false,
2.    // エディターで空白文字を表示するかどうかを制御します
   "editor.renderWhitespace": true,
3. Save
4. Confirmation

first character space : replacement character is displayed

middle character space : replacement character does not appear

end character space : replacement character is displayed

**Comment by alexandrudima** [comment]
Currently, the `renderWhitespace` option only renders leading and trailing whitespace.

**Comment by ThubLives** [comment]
This seems like a pretty big oversight.  Why would anyone want to show leading and trailing whitespace characters, but ignore those in the middle?
And what about CrLf pairs?  I use this feature in other editors to troubleshoot goofy composite files (e.g. Unix and DOS files concatenated together) or special cases where a parser wants mixed CrLf behaviour.  It would be nice if I could see the individual <CR> and <LF> characters.
Should this be a separate feature request?

**Comment by ionut-botizan** [comment]
I would also like to see all whitespace being rendered. That would be helpful when reading stuff like aligned JavaScript objects, PHP arrays, etc.

Eg:
```js
let defaults = {
    type....: 'GET',
    timeout.: 500,
    secure..: true
}
```

```php
$address = array(
    'street'.=> '5th Avenue',
    'city'...=> 'New York',
    'state'..=> 'NY'
);
```

Maybe, if it doesn't adds too much complexity, make it so single spaces are not rendered, to keep regular text and strings legible, and only render it if there are at least 2 `SPACE` characters or at least one other whitespace character, like `TAB`.

Another option would be to be able to configure VSCode to only render whitespace on the selected text. (I miss this feature since I ditched Sublime last year...)

**Comment by alexandrudima** [comment]
This is already implemented via `editor.renderWhitespace: "all"` and `editor.renderWhitespace: "boundary"`
