### ISSUE TITLE
Lifecycle service has two shutdown events

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#5536]
Today, the lifecycle service has two logic events (1) `onShutdown` and (2) `addBeforeShutdownParticipant`. The former is signal while the latter also supports veto. There should only be one event, like `onShutdown` and it should send an event which support veto, similar to `preventDefault` in DOM events

**Comment by jrieken** [comment]
fyi @bpasero

**Comment by bpasero** [comment]
@jrieken having only one event will not work. there are handlers that are **not** interested in vetoing and dispose resources on shutdown (e.g. file watchers) and there are handlers that are interested in vetos (e.g. the dirty file handler).

I distinguish between before close and on close for this reason, otherwise one handler might dispose resources that are still needed when a handler after fires the veto.

**Comment by jrieken** [comment]
Understood, still it should be an event and not a participant which is just another way of eventing. It should be `onWillShutdown` and `onShutdown`

**Comment by bpasero** [comment]
@jrieken that is good for me, yeah.
