### ISSUE TITLE
UsesOnlineServices should not require @tag prefix

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#55374]
Open settings, search for 
`usesOnlineServices` notice no results
Search for 
`@tag:usesOnlineServices` notice there are results

I do not understand why is it neccessery to explicitly specify the @tag. The downsides of this are:
* less discoverable by users
* not consistent with the rest of our settings story where we behave a bit like google -> whatever you type we try to be smart and give results back. We require no explicit need to specify the name / description, we just search across both

In the extnesions view it is a different story since the searching is done by the marketplace and we can not be smart as for settings. Being consistent with extensions view does not make sense to me here.
Tag feels like an implementation detail to me.

fyi @kieferrm @roblourens

**Comment by roblourens** [comment]
I think this is a different use case than normal searching. Typically we give our best guess as to what the user wants. Here, the user wants an exact set of settings, no more and no less. So I think having different syntax is justified.

The user will probably never type out that full string. Right now they will find it under the `...` menu. In the future we could also have intellisense like we do for the extensions viewlet.

**Comment by isidorn** [comment]
My point is that the user shuold easily discover this by typing
"online service", "do not send data" and similar queries.

Also why are online services special that they deserve an entry in this menu. If we add it for all the settings people search for that menu will soon be cluttered.

![screen shot 2018-07-30 at 18 07 36](https://user-images.githubusercontent.com/1926584/43409158-75530536-9423-11e8-8caf-553d7dd22ad5.png)

**Comment by JacksonKearl** [comment]
I think online services are special because they are a well defined set of settings that users have already expressed interest in modifying as a single block. There aren't many other `tags` we can think of, so clutter doesn't seem like a big issue at the moment. If we do end up adding a lot, we can take the extensions search approach of hiding all the different tags behind the autosuggest widget and only showing the most general settings in the dropdown.

Natural language queries are nice, but not ideal for something so concretely defined. For instance, Google can be as fast as they are because if results are missing, nobody knows, and if results don't really make sense for the given query, people can mostly figure out that that isn't what they were looking for. However, if we provide an incomplete set of results, people will know, and they'll go on to say its a conspiracy to steal their data or something. And if we present results that aren't relevant, people won't know, and settings like (contrived example): `Send data to local Tensorflow service for online training` will show up in searches even though they aren't online services, leaving people confused as to whether that setting actually sends data online or just has a weirdly worded description.

Regardless, I think the plan is to augment all the online service descriptions with something along the lines of "This is an online service which sends data to `https://....`" anyways, which will make it easier to naturally search for these settings with "online service" or "send data" or similar, but even with that it would be nice to provide users a concrete set of settings so that they know the search term isn't missing out on any, and they know every result is actually a setting controlling some component of uploading data.

**Comment by roblourens** [comment]
And another point is that we can't rely on natural language search to return good results, specifically in this case, because a user who cares about these settings has probably disabled it 😁

**Comment by kieferrm** [comment]
@isidorn has still a valid argument, i.e. that I should also be able to find these settings using NLS. I.e. we should make sure that they are returned (potentially among other things) from the bing service. At the same time, we also should have a way to show they user a well-defined set of settings that are exclusively about online services.

**Comment by JacksonKearl** [comment]
@kieferrm We'd get that from adding a "This is an online which sends data to ..." right?

**Comment by kieferrm** [comment]
@JacksonKearl, yes, we need to update the descriptions of the settings accordingly, or we need to define alt words for the settings keys to the NL search service.

**Comment by ramya-rao-a** [comment]
> Tag feels like an implementation detail to me

We needed a way to have a well defined set of settings and also a way for extensions to contribute to this set. We went with tags.

Now, whether we want to support a generic tag based search or only support search for specific tags is up for discussion. A generic tag based search is indeed useful, if there are a host of tags to work with. Else we can skip the `@tag:` and just go with `@usesOnlineServices` similar to `@modified`

> Also why are online services special that they deserve an entry in this menu.

Like @kieferrm said, this was to have a way to show the well-defined set of settings to aid discovery for users who want to have a fine grained control over features that make network requests without them explicitly asking for it. The new settings editor is still in preview. If we do go with having the search box provide suggestions, then a menu entry will not be needed as much.

> we need to update the descriptions of the settings accordingly

We can definitely do this for the settings we own, it gets tricky to enforce on this on extensions.

> or we need to define alt words for the settings keys to the NL search service.

@roblourens tags could be used as alt words directly. The NLS is smart enough to split the words based on camel casing right?

**Comment by ramya-rao-a** [comment]
Core Settings descriptions are updated with https://github.com/Microsoft/vscode/commit/3b82258154ab7a6c60065a3e8a8ac36a3ccbe091

**Comment by Ngocbich95** [comment]
Hi

Tải Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ramya-rao-a** [comment]
For the July update, we wont be adding the option to show the settings for online services in the menu. It will continue to appear in Insiders, but wont in Stable with https://github.com/Microsoft/vscode/commit/582cd9547d435735e583be540d0ba0c8262880c8
