### ISSUE TITLE
Cmd+click to go to link doesn't move the cursor

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#55415]
Issue Type: <b>Bug</b>

- Enable smooth scrolling, this seems to be related
- Open vscode.d.ts
- Go to TextDocument
- Cmd+click on the #FileSystemProvider link
- The editor scrolls to FileSystemProvider but the cursor is still at the link. It should be at the link target that I scrolled to.

VS Code version: Code - Insiders 1.26.0-insider (64c433bf2bd43c85d1bfe5753bb6fb90ff4be14a, 2018-07-30T05:11:25.700Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (1.97GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron --disable-extensions|
|Screen Reader|no|
|VM|0%|

</details>Extensions disabled

**Comment by alexandrudima** [comment]
I can reproduce. The root cause is that the go to definition executes in the same stack frame as the link handler and go to definition moves the cursor back to the original location. The workaround is to resolve the link asynchronously which just so happens is the way native promises work.

Note to verifier: The location of `FileSystemProvider` is for me before its JSDoc comment. Please create a separate issue if you don't like that, but that is unrelated to smooth scrolling...
