### ISSUE TITLE
New Settings - some corrections

### ISSUE THREAD

**Issue by user3323** [Microsoft/vscode#55413]
- VSCode Version: 1.26.0-ins
- OS Version: win7x64

![new settings 1](https://user-images.githubusercontent.com/24613274/43434020-a0e439ae-9482-11e8-8f18-8cffb7aab2d2.gif)

1) Labels should be bound to radio buttons.
2) Look at the pre-last option when clicking on it .... it makes last option to be moved a little bit. All these "shakes" do not look good.
3) And these outstanding blue outlines ......... what is the benefit to put them EVERYWHERE ? They are literally everywhere! They look not bad, but absolutely "cheap" and pathetic! And they visually DO NOT belong to this specific area of new settings!

one more gif: 

![new settings 2](https://user-images.githubusercontent.com/24613274/43434317-cd1590c6-9483-11e8-8376-3d61dc81dc92.gif)

And one more blue outline around the left menu! Wow.

4) On the second GIF you can see these jumping options after you click on them.
Well, some transition for expansion movement wouldn't hurt!

5) Description of each option, if it's can be expanded - should be ended up with .... at least three dots?.. Or any other icon, that will inform, that it's not full.

![image](https://user-images.githubusercontent.com/24613274/43434522-b0c79044-9484-11e8-8cc2-c57ac9e6990e.png)

![image](https://user-images.githubusercontent.com/24613274/43434526-b3c9c9ce-9484-11e8-98a6-56773326464d.png)

6) When hover a cursor over the option, that can be expanded - cursor should have pointer type, not default.

7) When any option is clicked - background of this option should change to color a little bit lighter.

8) Add background-color change on hover cursor movement over options and items of the left menu.

9) Names and descriptions of the options should be selectable (for copying, etc.)

10) Scrollbar area of the new settings is absolutely invisible. This little scrollbar thing is flying in the air.

**Comment by roblourens** [comment]
Thanks for the feedback! 

1. I don't do this right now because someone might be clicking the description to expand it, but I plan to make some changes around that for next month, so I'll keep thinking about it.

2. I can't repro that right now, it might have been fixed in the past couple days?

3. The model here is that the list of settings is a list that works the same as other lists in vscode. You can use the same keybindings to navigate, only the selected setting is tabbable, and the outline shows the selected setting. 

4. I played with animations and wasn't a fan since I thought it just felt sluggish. But I'll likely switch to showing the full description all the time, and get rid of the expansion anyway.

5. Fixed this 👍 

6. I'm not sure, it would mean that the pointer would show up basically everywhere on the page. Will think about it.

7. We had this originally but didn't like it. Too hard to get it just right for every theme.

8. We had that too, but also didn't like seeing rectangle backgrounds on that menu when it's not in any sort of rectangle container.

9. I think you're right, https://github.com/Microsoft/vscode/issues/54694 for this

10. This should run along the far right side of the editor, but I couldn't get the layout right. https://github.com/Microsoft/vscode/issues/55795 for that.

Thanks for the feedback, and follow along with https://github.com/Microsoft/vscode/issues/55791 (not filled out yet) and https://github.com/Microsoft/vscode/issues/50249 for updates!

**Comment by user3323** [comment]
@roblourens 

11. How about adding a Smooth Scrolling feature, that we have in editors, to affect on New Settings list?

![image](https://user-images.githubusercontent.com/24613274/43671468-69a07b14-97a3-11e8-8b9c-2b0f1923f634.png)

**Comment by roblourens** [comment]
When would this apply? I don't quite follow

**Comment by roblourens** [comment]
The "smooth scrolling" applies to things like 'page down' or 'go to definition' that would normally just jump. I'm not sure what you're seeing exactly, it's hard to tell from the gif, but maybe just that rendering the list is not as fast as it could be. I'll keep optimizing it 👍

**Comment by user3323** [comment]
@roblourens 

a **_smooth scrolling_** feature is the feature, that came to us some months ago, with some of the updates...
maybe you don't use it, and you don't know what it is...

well, I don't really know how to explain you about what smooth scrolling is... 

just look at it:

GIF:
![smooth scrolling 2](https://user-images.githubusercontent.com/24613274/43696657-c58170d2-9947-11e8-9256-9f6819f18582.gif)

you really don't see the difference between **_default scrolling_** and **_smooth scrolling_** ?

**Comment by roblourens** [comment]
What are you scrolling with? Mouse wheel, trackpad?

I know what smooth scrolling is and I see the difference between the gifs. I think that it looks less smooth because of slow rendering, not because of a missing feature.

**Comment by user3323** [comment]
@roblourens 

scrolling with mouse wheel...
no, it's not rendering problem.. i can record video with 50 fps, if you need

i don't get it, are you saying that New Settings already has smooth scrolling feature?

**Comment by roblourens** [comment]
You're right, I found that smooth scrolling doesn't work the way I thought and it isn't enabled on the settings editor. With my particular hardware it already looks smooth. I'll have to look into it later.
