### ISSUE TITLE
Code detects repositories when used as a difftool in Git Bash

### ISSUE THREAD

**Issue by Christian-Marx** [microsoft/vscode#55428]
Issue Type: <b>Bug</b>

Steps to reproduce:
```shell
$ git init
$ touch 1
$ git add .
$ git commit -m"foo"
$ echo foo > 1
$ git difftool
```
The _git difftool_ command is defined as:
```shell
code-insiders --wait --diff \"$LOCAL\" \"$REMOTE\"
```
When invoking `git difftool`, VS Code will correctly show one change for the repository, but will also show more than 5k changes in `$TEMP`, but there is no git repository at that location.
![screenshot1](https://user-images.githubusercontent.com/24615132/43445387-848445d2-94a6-11e8-8186-71ff700aedd9.png)
Why would VS Code load any source control provider here?

There is also a message popping up:
![screenshot2](https://user-images.githubusercontent.com/24615132/43445499-d3e582b2-94a6-11e8-912a-14e38bc6bd90.png)

If I invoke the same command line manually, i. e. `code-insiders --wait --diff $TEMP/S9bziC_1 1`, the source control view behaves correctly, showing only one diff:
![screenshot3](https://user-images.githubusercontent.com/24615132/43445737-6807282e-94a7-11e8-942f-b4211080b1cb.PNG)
I noticed that in that case, VS code does not show a source control provider, but says 'SOURCE CONTROL: GIT'.

Why does it make a difference whether `code-insiders --diff` is spawned from the git process vs. invoked by command line directly?

VS Code version: Code - Insiders 1.26.0-insider (64c433bf2bd43c85d1bfe5753bb6fb90ff4be14a, 2018-07-30T05:19:32.584Z)
OS version: Windows_NT x64 10.0.15063
git version 2.18.0.windows.1

**Comment by Christian-Marx** [comment]
I opened a separate issue #55460 which *might* be a variation or side effect of this one. The bug I'm describing there is that a wrong base directory is picked up if changes are made in sub-folders, resulting in wrong changes in the source control view, whereas the issue described here is about the $TEMP dir being picked up additionally as a source control provider. There might be a common source of error to both problems, please also have a look at that bug report.

**Comment by joaomoreno** [comment]
Please remove the `$TEMP/.git` folder, since that shouldn't be a git repository.

**Comment by Christian-Marx** [comment]
There is no `$TEMP/.git` folder on my machine. Would you please have another look?

**Comment by Christian-Marx** [comment]
No, there is no `.git` folder in any of the parents of `$TEMP`. Were you able to reproduce the problem with the steps I provided?

**Comment by joaomoreno** [comment]
I wasn't, no.

What about this:

```
cd $TEMP
git rev-parse --show-toplevel
```

What does that return?

**Comment by Christian-Marx** [comment]
It returns `fatal: not a git repository (or any of the parent directories): .git`

**Comment by joaomoreno** [comment]
I notice you are using *nix syntax on a Windows system. Are you using WSL, or something similar?

**Comment by Christian-Marx** [comment]
Yes, that's Git bash on Windows (git version 2.18.0.windows.1).

**Comment by joaomoreno** [comment]
Yup, I could definitely reproduce now.

**Comment by Christian-Marx** [comment]
Great, thanks for looking into this.

**Comment by brunovieira97** [comment]
I can confirm this happens outside of WSL systems too. I'm using PowerShell on Windows 8.1 and this is the output for ``git status``:
```
D:\Projects\repo [master ≡ +1 ~1 -0 !]> git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   scripts/SQLServer/bar.sql

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        code/desktop/lib/

no changes added to commit (use "git add" and/or "git commit -a")
```

When I run ``git difftool scripts/SQLServer/bar.sql``, Code opens with both versions of this file and I can compare them as expected.

It identifies, however, that all of my other files from the ``scripts\SQLServer`` folder are Deleted. Not only that, it's detecting that files from other folders from the same repo (even from ``scripts\SQLServer`` parent directories) are deleted. What do I mean?

Let's say for instance that the scripts folder mentioned above is on same level of a code folder. This repository has the following structure then:
```
 .git
 code
     L desktop
          L foo.c
 scripts
     L SQLServer
          L bar.sql
```

Code's showing the following file as deleted on my Source Control tab:
``foo.c [ D:\Projects\repo\scripts\SQLServer\code\desktop\foo.c ]``

It seems like Git and Code can't talk to each other, resulting in .git data being pulled from original diff folder (my repo) and then Code trying to find the whole tree inside the current diff directory, based on .git info. 

Since it's identifying the ``C:\Users\<user>\AppData\Local\Temp ``as a Git repository too, every active change gets doubled up. I've checked and there's no .git folder in either Temp or any of it's parent directories.

---
### Visual Studio Code

Version: 1.37.1 (user setup)
Commit: f06011ac164ae4dc8e753a3fe7f9549844d15e35
Date: 2019-08-15T16:17:55.855Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 6.3.9600

### Git

git version 2.23.0.windows.1
