### ISSUE TITLE
A11y: actions within the tree are not read by screen readers

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#5544]
- VSCode Version: 1.0.1 - Insider
- OS Version: Windows 10, NVDA

Steps to Reproduce:
1. Put workbench in tab mode
2. Tab into the working files section in the explorer
3. Observe: the x button to remove a file gets focus but nothing useful is read.

**Comment by bpasero** [comment]
Seems to be true for any action in trees, I am quite sure this used to work but no longer is. No clue why so far...

**Comment by bpasero** [comment]
I found out that the fact we assign `role: tree` seems to cause this and changing it to `role: listbox` seems to fix it. However I am not feeling comfortable making such a change because the role should actually be tree.

@zersiax any clue what might be going on? we have a `tree` with `treeitem` and each `treeitem` can have one or more `button` that have a `tabindex` to navigate to. Once I change the `role` from `tree` to `listbox` the screen reader (NVDA) correctly reads out the `button` when I navigate to it.

**Comment by zersiax** [comment]
May have something to do with chromium bug 601933  https://bugs.chromium.org/p/chromium/issues/detail?id=601933
Have a look around the accessibility tree if something similar might be going on. I am guessing that changing the role to listbox breaks navigation among levels?

**Comment by bpasero** [comment]
@zersiax interesting, though I see this even with Chrome 45. I have not tested any other a11y feature after changing to listbox. I still keep role treeitem for the elements within and that seems to at least let NVDA read out the collapsed/expanded state and hierarchy level of the tree :)

**Comment by joaomoreno** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.

Thanks for your understanding. Happy coding!
