### ISSUE TITLE
Evaluate focused context, not global context

### ISSUE THREAD

**Issue by alexandrudima** [microsoft/vscode#55453]
Testing #55389

Extracted from https://github.com/Microsoft/vscode/issues/54510#issuecomment-407682618

@sbatten I tried to use `precondition` to control the enablement of Undo and Redo. One of the problems that came up is that the menubar menu entries are evaluated in the global context.

But in the workbench you can have multiple editors opened, some of which can undo and some of which cannot.

I have noticed that the menubar will refocus on the previously focused element when invoking the action, so if focus is in editor1, and then the Edit menu is opened, and Undo picked, focus is correctly brought back to editor1 before the command is invoked.

I think we could support high fidelity disablement/enablement of these commands if the menu items `precondition` would be evaluated in the context of the previous focused element. You can find the context associated with a particular element via `IContextKeyService.getContext(previousFocusedElement)`.

**Comment by sbatten** [comment]
@alexandrudima 

This has more implications than originally considered.

This first issue is that our menu registration system currently requires us to create a new menu to change the context of the actions (in order to determine enablement/disablement). We could change this so that we can call `getActions` with a another context, but we'd need to know when to call it to update the menu. You could say that we could use the lazy loading approach by only loading the menu actions when the user clicks the menu. In fact this would reduce the amount of listening the menubar would have to nearly 0 as we could just get the correct state of the menu right before we draw it. All this sounds well and good until we consider the native menubar. In this case, we can't be lazy, the menu has to be populated because we can't install a new menu as the user clicks into it and we have to send the menu over IPC.

/cc @bpasero @jrieken

**Comment by alexandrudima** [comment]
@sbatten I don't understand how evaluating in the focused context is any different (or poses any more difficulties) than evaluating in the global context (what I understand the menu system does today).

I can create a global context key called `currentlyFocusedEditorCanUndo` and manually track the focus in the page via some focus listener and when the focus lands in an editor I can find that editor and check if it has an undo stack. So, the global context key `currentlyFocusedEditorCanUndo` will be updated on each focus change. If the menus respect the global context, then the menus need to take this change into account and constantly repaint as the global context key is changed.

**Comment by sbatten** [comment]
@alexandrudima you are right about being able to map this to a global key that would solve the first problem which is that context is set when we create the menu (not show the menu).

however, another concern has been raised especially with mac, that the menu is listening a lot for context and being frequently updated as you mention at the end. if we continue adding more context, i'm afraid we will have similar struggles as last milestone where the native menus feel like a huge perf regression.
