### ISSUE TITLE
Empty macOS menu bar entries when clicking on menu bar in new window

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#55468]
Issue Type: <b>Bug</b>

1. On MacOs with multiple monitors
1. Launch 2 VS Code instances, placing each on different monitors
1. Focus on the first instance but keep the second one in the foreground on the other monitor
1. With the first instance focused, click on the menu bar of the second instance

**Bug**
All menus besides the one you clicked on are empty

VS Code version: Code - Insiders 1.26.0-insider (0707dd4940b3fdbea8339595de478f354f6dda83, 2018-07-31T05:12:08.688Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 15, 11|
|Memory (System)|16.00GB (2.38GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|17%|

</details>

**Comment by sbatten** [comment]
@mjbvz I think this is likely due to several other issues that aren't really related to the multi-monitor setup but rather the menu getting installed on itself and electron 2+ not handling this properly. I am going to close this as there are other issues tracking that behavior. Please re-open if you see this behavior when we bring back the new menu registration on macOS
