### ISSUE TITLE
QuickInputButtons namespace seems odd

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#55494]
While reviewing the generated API from vscode.d.ts, I noticed the new QuickInputButtons namespace. It doesn't follow other vscode.d.ts namespace conventions (lower case names like "commands", "extensions", "workspace") and is very small containing only one interface QuickInputButton.

Should this namespace be removed and the QuickInputButton interface just be at the global level?

**Comment by chrmarti** [comment]
The interface and the namespace should both be top-level:
![image](https://user-images.githubusercontent.com/9205389/43574646-099ba7f2-9645-11e8-83a8-aa94054a0c78.png)

The intend is for QuickInputButtons to have a (growing) set of predefined buttons. We could have made it a class with static fields, but @jrieken suggested to go with the namespace because that has advantages for documentation (I forgot which).

Does this cause any trouble?

**Comment by gregvanl** [comment]
Mostly I brought this up since it is a change in convention with the other namespaces. The difference is very visible in the auto-generated API documentation:

![image](https://user-images.githubusercontent.com/12818376/43596804-29a114a2-9635-11e8-9017-7d633f17bffc.png)

**Comment by chrmarti** [comment]
I'll change it to a class with a static field. That will be in line with others like `ThemeIcon`.
