### ISSUE TITLE
Debug exploration: Async Callstacks

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#5552]
In chrome and node dev tools you enable async callstacks which means calls like setTimeout are not without parent but it shows where setTimeout was invoked when debugging its callback function. Pretty handy

**Comment by weinand** [comment]
The v8 debugger protocol does not provide enough information for doing this. So this will require more code injection.

**Comment by roblourens** [comment]
Hijacking this issue for the async callstack exploration.

Async callstacks show the origin of an asynchronous call. For example, if the debugger pauses in a `then` handler on a promise, the async callstack will show the stack that caused the promise to be resolved. Or if the debugger is paused in a setTimeout handler, it will show the stack that lead setTimeout to be called.

In F12 and Chrome Devtools, async callstacks can be enabled or disabled with a button next to the callstack. In the inspector protocol, we use `Debugger.setAsyncCallStackDepth` to set the number of async calls to trace back. This could be incredibly large, like if a timeout handler calls setTimeout on each call. Chrome Devtools uses 4.

**UI**
In Edge's F12, async calls are shown in collapsible tree sections

![image](https://cloud.githubusercontent.com/assets/323878/22910560/97497b28-f20f-11e6-97cf-b1df87a2a130.png)

In Chrome Devtools, async sections are demarcated by a non-clickable label row with a description of the async call.
![image](https://cloud.githubusercontent.com/assets/323878/22910718/b3b8a490-f210-11e6-816e-aac030f8613b.png)
We will get this description too via the inspector protocol.

Visual Studio is similar - it shows an extra row that says `[Async Call]`
![image](https://cloud.githubusercontent.com/assets/323878/22910780/2233b2d4-f211-11e6-9713-2a5a0f434815.png)

For VS Code, if we show the async frames and include their info in the existing callstack, it might look like this: 
![image](https://cloud.githubusercontent.com/assets/323878/22911316/deae1bd2-f213-11e6-8c2b-89c70f8cf434.png)

But there are some downsides to this, like you can't tell how many different Promise.resolve calls are in that stack.

Alternately, we could allow a debug adapter to add a non-clickable frame or even collapsible sections like F12.
![image](https://cloud.githubusercontent.com/assets/323878/22911554/2e536c22-f215-11e6-9996-9c6230bb34d2.png)

We either need to
- Make async frames a first-class citizen in the debug protocol
- Build on the `presentationHint` property introduced in 1.9 to indicate a 'label' row that doesn't try to open a file when you click on it
- Or just change the way VS Code interprets existing frames, and don't complain if a frame omits the 'source' property


**Clicking an async call**
Async frames are not 'live' frames - we can't get their locals or evaluate code in their context. We only have their function names and locations. So when clicking on a frame, we would show the line in the editor, but show an empty variables window. So it needs to be obvious that a frame is an async frame. 

FYI @weinand @isidorn

**Comment by weinand** [comment]
@roblourens great analysis!

Following the "Do The Simplest Thing That Could Possibly Work" principle I suggest that we proceed along the lines of @roblourens bullets from above:

- we use the Chrome Devtools approach with non-clickable labels as separators
- we enable this feature by default for node2 and initially provide no nice UI to turn if off (because we believe that it will be always useful; but maybe we need a setting for it)
- we will not promote async frames to become first-class citizen in the DAP
- we surface the label frames and async frames as stack frames that have no source. I'm pretty sure that this is already supported. Without source clicking them doesn't do anything. 
- we use the `presentationHint` value `deemphasize` to deemphasize the label frames. If needed we could introduce a new `presentationHint` value `label` which results in a centered, deemphasized look.
- if an async frame is selected the DA has to make sure that scope, variables, and evaluate requests (which use the async frame as a parameter) are returning empty results (or a warning).

**Comment by roblourens** [comment]
Sounds good. I would add a launch config option to disable this, since it can always be enabled/disabled in other devtools (I'm not totally sure why people would disable it, maybe they just want to eliminate noise).

I was trying to return frames with no source, but was getting errors when I clicked on them. If it's supposed to work, I'll look at it again or file an issue.

I'm not sure I want to 'deemphasize' them, since it may be user code. And there may be skipped async frames, and I don't want to eliminate the contrast between async user code and skipped async code. But it needs to be obvious that they're different, so maybe I will.

**Comment by weinand** [comment]
Yep, launch config option sounds good to me.

Yes, please file a bug for the source-less frames.

I only meant to 'deemphasize' the label frames (which are basically "headers"), but not the async frames. In Chrome Devtools the label frames look 'deemphasized' as well (they are grey).

**Comment by roblourens** [comment]
Someone filed https://github.com/Microsoft/vscode/issues/20622 which is what I was seeing.

**Comment by weinand** [comment]
There is nothing to test in this milestone because it was only an exploration.

**Comment by roblourens** [comment]
Reopening for implementing this in March

**Comment by weinand** [comment]
@roblourens I've added an optional `presentationHint` attribute to type `StackFrame`.
The only supported value for now is `label`.
Available in `vscode-debugprotocol@1.18.0-pre.2`

**Comment by roblourens** [comment]
Implemented
