### ISSUE TITLE
[ts] Duplicate identifier ... for all files in the same folder

### ISSUE THREAD

**Issue by user3323** [Microsoft/vscode#55541]
- VSCode Version: 1.26.0-ins
- OS Version: win7x64

1) make a main.ts file with code:
```
class Point {
  x: number;
  y: number;

  draw() {
    console.log('X: ' + this.x + '; Y: ' + this.y);
  }

  getDistance() {
    // ...
  }
}

let point: Point;

point.draw();
```

2. use terminal for `tsc main.ts` and open main.js
3. see these red "highly danger" alerts, that saying about **_duplicate identifiers_**

![duplicate identifier](https://user-images.githubusercontent.com/24613274/43494611-68c955da-953c-11e8-90d0-f1f2adf9b010.gif)

Is that typescript side or VS Code's?
When was it implemented?
How to turn it off?

Ok, I can agree, that in building projects it is a good feature, but here is the question ...

![duplicate identifier 2](https://user-images.githubusercontent.com/24613274/43494961-1f7b825c-953e-11e8-885d-f098e5492be6.gif)

... why does a user need to visit every file for this feature to start working and telling a user about duplicates?
Take a look at the second GIF.
It shows up like everything ok in main.ts file after force reloading the VS Code, and telling about duplicates **_only after_** visiting main.js
Not good.

**Comment by mjbvz** [comment]
Create a [`tsconfig.jon`](https://code.visualstudio.com/Docs/languages/typescript#_tsconfigjson) file. This tells VS Code to treat all files in the workspace as part of the same project. Otherwise, files are added to an inferred tsconfig project as you open them

The duplicate identifier error is because the two declarations here in the global scope. Either make the files into modules or wrap them in namespaces to avoid naming conflicts
