### ISSUE TITLE
Live reload without saving

### ISSUE THREAD

**Issue by James2516** [Microsoft/vscode#55577]
On sites like https://codesandbox.io, https://snack.expo.io, the app constantly reloads as we type.
On vscode, auto reload only happens when we save the file.
Is it possible to allow auto reload even before file is saved (i.e. reload constantly as we type)?

**Comment by V-ed** [comment]
I assume that by "auto reload" you mean update your website in real time, so as soon as you make a modification in your code you see the result in your browser on your other monitor, for example.

Under that assumption, I'd say your best bet is to use the [Live Reload extension](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer) paired with the `Auto Save` feature turned on (view image below or use Command Palette `Toggle Auto Save`).

![image](https://user-images.githubusercontent.com/16652915/43529786-03929d32-957a-11e8-8764-e572ee8154a6.png)

I'm saying this because I'm guessing the services you mention does this in the background automatically.

I may be completely off-track here, feel free to provide more info if that's not what you asked for :)

**Comment by isidorn** [comment]
@V-ed Sounds good. 
If you are debugging node checkout nodemon
