### ISSUE TITLE
cannot debug sourceMap from http on node

### ISSUE THREAD

**Issue by dmail** [Microsoft/vscode#55659]
I cannot debug a file like below using node debugger on vscode

```javascript
var value = true

debugger

console.log(value)
//# sourceMappingURL=http://127.0.0.1:8567/file.es5.js.map
```

 

- VSCode Version: 1.26.0-insider
- OS Version: mac 10.13.6

Steps to Reproduce:

Because it needs a set of files and a server I've made a repository providing the files to reproduce: https://github.com/dmail/vscode-debug-sourcemap-http

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
Thanks for the test repo. You are serving sourcemaps from a server running in the same process as the code you're debugging. So what happens is, file.es5.js gets loaded dynamically, and the debugger tries to start downloading the sourcemap, but then we hit the `debugger` statement. Since your server is in the same process which is now paused, it can't serve the sourcemap.

But when I tried this a few times, it did work after the second time because we cache sourcemaps. You can see it loading the cached sourcemap in the log where it says `Reading cached sourcemap file from...`.

I don't recommend developing this way because we assume that sourcemaps served from some server don't change, so if it changes you'll still get the old cached version. I recommend using `outFiles` in your launch config to preload the sourcemaps from disk.
