### ISSUE TITLE
Native menus show '(empty)'

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#55683]
Elementary Loki (Ubuntu 16.04)

Version: 1.26.0-insider
Commit: c86cab2
Date: 2018-08-02T05:18:18.450Z

- start up vscode, directly click on the menu bar (typically to open a folder)
- All entries show `(empty)`.
- continue clicking until, finally, the menus appear.

That not an optimal experience. I've never seen an app that shows 'Empty' in the menu.
We should at least have 'Open File / Folder / Exit)` in there. Also 'Open Dev tools' is missed if something goes wrong on startup.

Maybe we can remember the previously shown menus, so that at least on the second start you have a fully populated menu.

**Comment by isidorn** [comment]
@aeschli do you enjoy having the inbox tracker assign all your issues 😁

**Comment by joaomoreno** [comment]
This is independent from custom menus, this affects even native menus.

**Comment by alexandrudima** [comment]
A few things that were discussed in today's standup:
1. It feels weird to see the VSCode window come up and see no menu entries for a couple of seconds (i.e. empty menubar).
2. It feels weird to see the VSCode window come up and see 3 menus for a couple of seconds, and then the other menu entries show up (i.e. growing menubar).
3. It feels weird to have menus that show "(Empty)" when clicked.
4. In case something goes wrong, end users do not have a means to open a different folder, report an issue, or quit vs code, because the menus are not there. A few critical menu entries should always be available:
 - File > Open...
 - File > Exit
 - Help > Toggle Developer Tools
 - Help > Report Issue
 - Help > About
etc. (the above is not necessarily a complete list)

**Comment by isidorn** [comment]
Because this affects the native menus we have assgined this to July so we look into tackling it for this milestone.

**Comment by sbatten** [comment]
after discussion with @kieferrm, we've decided to resolve this by no installing the menu if any menu is incomplete and only fallback to the 3 menus after closing the last window (but not quitting the app). 

The result is the following:
1) If a user freshly launches VS Code, the app menu (macOS only) (the one titled Code) will be populated but the rest of the menubar will be empty until we have a full menu.
2) Once the full menu is ready, it will appear once and will not change in size (reducing any flashing).
3) When you close the last menu, we will fallback to having 3 menus only.


Caveat: If you leave the app with no windows open and return by opening a new window via command line, the menu will not be ready but the 3 menus will still be drawn until the full menu is ready. 

While there is still some minor visual noise, it is reduced to a minimum in order meet the rest of the requirements.


commits: https://github.com/Microsoft/vscode/commit/1a1b92fbd020353051b51d2efa2dd88a63416a26 and https://github.com/Microsoft/vscode/commit/e30a864fe80e6e032e87417afa4cf6ecf14ad4ef

**Comment by joaomoreno** [comment]
cc @aeschli @weinand

**Comment by aeschli** [comment]
Verified on Ubuntu 16.04 (ElementaryOS)
