### ISSUE TITLE
Cursor color to distinguish between solitary cursors and groups of cursors

### ISSUE THREAD

**Issue by brandondrew** [microsoft/vscode#55780]
Searching didn't turn up any requests like this, or any means of accomplishing this.

I am not talking about distinguishing between the "main" and additional cursors, such as in https://github.com/Microsoft/vscode/issues/22621, but rather single cursors and multiple cursors.

It would be very useful to know at a glance whether edits you make will _only_ affect the cursor you're currently looking at, or whether there are other cursors (potentially out of the viewable area of the editor) that will have changes made too.  Since _a_ cursor is almost always in the center of your focal area when you're looking at your editor and typing, it would make sense for every cursor to indicate visually whether it is solo or one of many, rather than for the indicator to be (for example) in the status bar, where it will generally be unnoticed.

I have on many occasions accidentally edited my code in multiple places because a previous change left multiple cursors hanging around.  In some cases I was interrupted from working and came to work without remembering about the multiple cursors.  In others it was the fact that VS Code has different rules about how long multiple cursors persist than the editor I used before it.  So (through years of using the other editor) I was accustomed to having the multiple cursors go away (for instance, after using an arrow key to move to another line) and through force of habit forgot that VS Code behaves differently in this regard.

A strong visual indicator--such as the color of the cursor, though it could be something else--would solve this problem.  Ideally it would be configurable.

**Comment by brandondrew** [comment]
@vscodebot This is quite clearly _*not*_ a duplicate of those three other issues.

**Comment by brandondrew** [comment]
For an editor to give you _no indication_ that there are multiple cursors (or that there are cursors hidden from view, at least) and to allow you to inadvertently make edits you are unaware of—don't you see that as a very large problem?

**Comment by alexandrudima** [comment]
@brandondrew In the latest insiders, when using themes that use a background color for the current line highlight, the current line highlight will render for all cursors. So that would bring the number of places rendering different for multiple cursors to 4:

![image](https://user-images.githubusercontent.com/5047891/68106989-ab828600-fee3-11e9-9365-cbfd2645e8fb.png)

1. the cursors themselves
2. the line highlights for the cursors themselves
3. the overview ruler
4. the status bar

**Comment by atombender** [comment]
I've thought about this issue many times, glad to see I'm not entirely alone.

@alexdima For those of us who have line highlighting turned off, there's often no visual indicator anywhere near the cursors; aside from the fact that cursors are small and not very visible, _the next cursor may in fact be outside the editor viewport_. The status bar and ruler are both far off from where you are actually looking when you edit.

This last one is what hits me the most; I'm editing in multiple locations that are far apart, and I forget that the editor is in multi-cursor mode. I find myself being in multi-cursor mode by accident many times a day because for whatever reason it did not exit; for example, maybe I did hit the Esc key, but VSCode had an autocomplete box focused — yet another modality — and so the Esc closed the autocomplete box but didn't cancel the multiple cursors.

It's true that multiple cursors must be explicit started, but once they _are_ started, they must ipso facto also be exited manually. The lack of visual feedback when you do exit means that there can be some uncertainty about which mode are you currently _in_. If the cursors are multiple pages apart, for example, then you cannot look at the immediate radius of the current editing position to know if you're in multi-cursor mode. The only way is to look at the status bar or ruler, or simply hit the Esc key "just in case".

If the VSCode team isn't interested in adding UI affordances like this, perhaps an extension could be created that did this. For example, something like a gutter bar in a bright colour.

**Comment by brandondrew** [comment]
@alexdima Having all lines with cursors show a highlight is great, and I very genuinely appreciate that it has been added, but it does not really solve the problem since only one cursor may be visible on the screen at any given time.  

As far as I can see, the only possible solution which is both complete and usable is to visually change every visible cursor.  

(Most or all of this was already said by @atombender, but you can consider this my emphasis of what I consider the main points.)

**Comment by klunko** [comment]
> This last one is what hits me the most; I'm editing in multiple locations that are far apart, and I forget that the editor is in multi-cursor mode. I find myself being in multi-cursor mode by accident many times a day because for whatever reason it did not exit; for example, maybe I did hit the Esc key, but VSCode had an autocomplete box focused — yet another modality — and so the Esc closed the autocomplete box but didn't cancel the multiple cursors.

This is my case too. There is hardly a day that I don't find myself in text mangling mode because for some reason I didn't get out of multi-cursor mode. It doesn't help that I've already acquired two specific habits - hitting Esc twice, and periodically glancing at the status bar to see if I forgot to turn off the multi-cursor.

If you find the problem after a few days, Ctrl+Z will no longer be able to help you. In a couple of cases I had to use a backup to restore data.

It is worth saying that I had troubles to find this issue, since I did a search for the official name of the mode (multi-cursor). It may be important if one will decide to reopen this issue someday.
