### ISSUE TITLE
cmd+ . no longer works for auto import when using typescript 3.0.1 

### ISSUE THREAD

**Issue by sfowl73** [Microsoft/vscode#55785]
- VSCode Version: 1.25.1
- OS Version: osx 10.12.6

Steps to Reproduce:

1. Change typescript version to workspace version 3.0.1
2. Try using cmd + . to auto suggest imports, and note "No Code Action" message.
Using vscode version 2.9.2 works as expected.

Does this issue occur when all extensions are disabled?: Yes

**Comment by MicrosoftEurope** [comment]
Typescript 3.0.1 is no longer supported.

4 авг. 2018 г. 0:54 пользователь "Sarah Fowler" <notifications@github.com>
написал:


   - VSCode Version: 1.25.1
   - OS Version: osx 10.12.6

Steps to Reproduce:

   1. Change typescript version to workspace version 3.0.1
   2. Try using cmd + . to auto suggest imports, and note "No Code Action"
   message.
   Using vscode version 2.9.2 works as expected.

Does this issue occur when all extensions are disabled?: Yes

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Microsoft/vscode/issues/55785>, or mute the thread

**Comment by sfowl73** [comment]
@MicrosoftEurope No longer or not yet supported? I was mostly opening the issue to log the desire for typescript 3 support to be on the roadmap. Thanks!

**Comment by mjbvz** [comment]
@sfowl73 Disregard that user. Please share a code example or small example project that shows this problem (also make sure you are using the VS Code insiders build for testing)

**Comment by MicrosoftEurope** [comment]
Hello Sarah,

Can you please be more specific about the request? This feature could be
included in the next release of Visual Studio Code Pro.

сб, 4 авг. 2018 г., 1:14 Sarah Fowler <notifications@github.com>:

**Comment by sfowl73** [comment]
Looks like it's a problem with our set up, maybe a dependency clash. Standing up a tiny example did, in fact, work correctly. Closing issue!

**Comment by geirsagberg** [comment]
Please re-open this, I have the same problem whenever I am using TS 3.0.1.

**Comment by geirsagberg** [comment]
Seems to only be an issue with scoped packages, e.g. '@material-ui/core'.

**Comment by geirsagberg** [comment]
I can open a new bug with the details.
